### ISSUE TITLE
[8.0] Demo data not fully recreated

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#10001]
This is weird. If you for example you use demo data and install `account`, it creates some invoices with invoice lines. Now if for example you delete invoice (like draft one) and then upgrade `account` module, it will recreate invoice, but it will have no lines. I checked, maybe lines are not deleted, when you delete invoice, but it is. So basically for some reason lines are permanently deleted and can't be recreated from XML.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yentheoerp-odoo
