### ISSUE TITLE
[8.0 Official Odoo forums] Unable to subscribe to topic

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10005]
**Unable to subscribe to a forum thread**

Impacted versions:

 - 8.0 (Odoo official forum)

Steps to reproduce:

 1. Open an existing forum topic (for example: https://www.odoo.com/forum/help-1/question/xpath-errors-in-customise-qweb-report-of-odoo-9-94356)
 2. Click on 'Subscribe' => You will now see that the e-mail that is prefilled is removed from the field.
 3. Try to fill in your e-mail to subscribe. => You can't because the field is disabled.
```
<input type="email" name="email" class="js_follow_email form-control" placeholder="your email..." disabled="disabled">
```

Current behavior:

 - E-mail is removed when clicking on subscribe, field is read-only so you can't fill it in again.

Expected behavior:

 - User is subscribed to topic.

**Comment by Yenthe666** [comment]
@mart-e could you let somebody look at this ASAP please? It is impossible to subcribe to a thread at this moment.

**Comment by mart-e** [comment]
Duplicated of #9980 
We are aware of the issue, lead by our recent migration to 9.0.
Please keep in mind that, as [explained in guidelines](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues), github issues will always be treated with a much lower priority than a Pull Request or an Odoo Enterprise support ticket.
