### ISSUE TITLE
Point Of Sale issue with ClosePosPopup.js

### ISSUE THREAD

**Issue by mthiermann** [odoo/odoo#100151]
Impacted versions:15.0

Steps to reproduce:Close POS session popup input counted cash

Current behavior:Javascript no longer works correctly after update core with the modified file ClosePosPopup.js at cash closing. Input counted cash does not update cash difference, boolean for (accept cash difference) always appear and the close session button is always grey. This behavior has been observed since the last commit 2bc4560.

Expected behavior: When input counted cash, cash difference will be updated, if the difference is 0 the boolen field "accept difference.." will be hidden and the close session button ist not grey.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by PratikTechultra** [comment]
Same issue, we are facing

**Comment by PratikTechultra** [comment]
https://github.com/odoo/odoo/pull/100462
Check this. Maybe helpfull!!

**Comment by pedrambiria** [comment]
Hello,
Thanks for reporting this issue.
This bug has been fixed.
