### ISSUE TITLE
[9.0] module scaffold generating headless templates.xml

### ISSUE THREAD

**Issue by matheo** [odoo/odoo#10019]
The `demo.xml` and `templates.xml` file generated by `odoo.py scaffold` subcommand doesn't contain the xml first line:
```
<?xml version="1.0" encoding="utf-8"?>
```
only the `views.xml` file does.

**Comment by xmo-odoo** [comment]
The XML declaration is not required and this specific one is completely useless: 1.0 is the default version (not that anyone uses or supports 1.1) and UTF8 is an autodetected default. If you really want to create a PR, remove it from view.xml, don't add if to the other two.

**Comment by matheo** [comment]
All right, thanks! :)
