### ISSUE TITLE
Require allocation functionality not working when apply leave for multiple employee

### ISSUE THREAD

**Issue by RiteshSerpentCS** [odoo/odoo#100133]
Impacted versions: 15.0 and 16.0

Steps to reproduce:

Time Off -> Configuration -> TimeOff Types
 -> Create Leave type with required allocation "yes"
Time Off -> approvals -> Allocation
 -> Create Allocation with 2 employee
Time Off -> approvals -> TimeOff 
 -> Create Leave request for 3 employees with 2 employees which is used in allocation.

Current behavior:
- System allows a third employee that has no allocation (see video)
Expected behavior:
- The system should not allow employees which employee has no allocation
Video/Screenshot link (optional):

https://user-images.githubusercontent.com/76728462/190120693-e71cbc5b-0cca-48c0-9e24-6fd17be21240.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by RiteshSerpentCS** [comment]
@sswapnesh

**Comment by jabirmisnedtech** [comment]
https://github.com/odoo/odoo/issues/95167
I have posted similar bug 2 months before and in github they didn't respond. In odoo bug report they manipulate this bug report as feedback for future version. 
<img width="824" alt="Screenshot 2022-09-24 at 9 29 59 PM" src="https://user-images.githubusercontent.com/45730318/192113413-678e444a-8488-4b99-aab3-f38baf21f057.png">

**Comment by Yenthe666** [comment]
@tivisse 😉

**Comment by tivisse** [comment]
Hi @RiteshSerpentCS 

Thanks for the report, I wasn't aware of this issue. 

For the record, I've created an internal R&D task (id=2995120), you'll be notified as soon as the issue is addressed.

Have a nice day,

Yannick Tivisse.

**Comment by RiteshSerpentCS** [comment]
@tivisse 

Thanks for the update.

**Comment by RiteshSerpentCS** [comment]
> Hi @RiteshSerpentCS
> 
> Thanks for the report, I wasn't aware of this issue.
> 
> For the record, I've created an internal R&D task (id=2995120), you'll be notified as soon as the issue is addressed.
> 
> Have a nice day,
> 
> Yannick Tivisse.

Still waiting for the update

**Comment by RiteshSerpentCS** [comment]
The issue has been fixed
