### ISSUE TITLE
[8.0] Odoo POS Session - Quantity UoS / UoM not change after set Decimal Accuracy

### ISSUE THREAD

**Issue by busel7** [odoo/odoo#10053]
Please help, After I set Decimal Accuracy for UoS and UoM there is no change in Odoo POS Session, attached screenshoot.

![odoo-pos-session-uos-uom-qty](https://cloud.githubusercontent.com/assets/14789844/11767261/5ae91d40-a1da-11e5-8b53-75de64d6143b.png)
![odoo-setting-decimal](https://cloud.githubusercontent.com/assets/14789844/11767262/5ee0ed60-a1da-11e5-9532-50df4f209ea1.png)

**Comment by busel7** [comment]
For temporary solution I edit file : addons/point_of_sale/static/src/js/models.js
Line 721:
                    var decimals = Math.ceil(Math.log(1.0 / unit.rounding) / Math.log(10));
to
                    var decimals = 0;

**Comment by lukebranch** [comment]
@busel7 ,

I'd recommend asking this question on the Odoo Community mailing list here:

https://www.odoo.com/groups

I think you'll find editing core module code is never the solution, and will always cause unexpected behaviour somewhere down the line.

**Comment by busel7** [comment]
@lukebranch,

I think its related to bug, thats why I'm report here.

**Comment by lukebranch** [comment]
@busel7 ,

I'm not connected to Odoo, i'm just a user like yourself, however if you'd like this looked at i'd recommend putting together detailed steps to reproduce on the latest runbot for the branch you're working with.

If it's something that can be demonstrated visually then I suggest adding a screencap GIF using something like licecap:

http://www.cockos.com/licecap/

If it is indeed a bug, once you've got the above put together i'd recommend pinging (@)xmo-odoo to see if they can help. I would however first recommend hitting the community mailing lists and forum here:

help.odoo.com to see if anyone else has run into the same problem.

**Comment by Yenthe666** [comment]
Hi @busel7 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@lukebranch Thanks a lot for always trying to help others and give usable feedback!

Regards,
Yenthe
