### ISSUE TITLE
"wget -O-  https://raw.git..." should use odoo 9.0 instead of 8.0 now

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#10052]
The Readme suggests, that if you are a developer you may type the following command at your terminal:
wget -O- https://raw.githubusercontent.com/odoo/odoo/master/odoo.py | python

The underlying functoniality should be updated to 9.0 to avoid confusion for new developers trying odoo

**Comment by Yenthe666** [comment]
This is fixed at https://github.com/odoo/odoo/commit/623fbf58f0a0798e735b831fdc29798b6d3c4316 
@mart-e this one is for you.
