### ISSUE TITLE
Error installing odoo 9 with LESS

### ISSUE THREAD

**Issue by f-ewald** [odoo/odoo#10050]
Hi,
I have an error installing the current version of odoo 9 on ubuntu. As far as I know I installed all the required packages, like npm, less and node. Still, I have the following error message:

```
2015-12-12 06:25:18,011 9233 WARNING xxx openerp.addons.base.ir.ir_qweb: This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/src/less/mimetypes.less
    - /web/static/src/less/animation.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_editor/static/src/less/web_editor.less
2015-12-12 06:25:18,135 9233 WARNING xxx openerp.addons.base.ir.ir_qweb: This error occured while compiling the bundle 'web.assets_backend' containing:
    - /website/static/src/less/import_bootstrap.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/enterprise_compatibility.less
    - /web/static/src/less/utils.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/notification.less
    - /base_import/static/src/less/import.less
    - /web_tip/static/src/less/tip.less
    - /web_calendar/static/src/less/web_calendar.less
    - /web_diagram/static/src/less/diagram_view.less
    - /web_kanban/static/src/less/kanban_dashboard.less
    - /web_kanban/static/src/less/kanban_view.less
    - /web_settings_dashboard/static/src/less/dashboard.less
```
This seems to me like the path is not correctly set. I didn't do anything in this direction. Is there maybe a possibility on how to reset this? I already followed all of the tricks, like cleaning tables, reinstalling the database etc. Nothing helped so far. Is this a bug in odor itself or did I do something wrong (which i most likely assume).

Regards,
F

PS: I just cloned the git repo with the commit #: 2a89c926ecd7d60eaed65af9f7708780ea6982a8

**Comment by raycarnes** [comment]
Did you do:

**sudo ln -s /usr/bin/nodejs /usr/bin/node**

**Comment by bsphil** [comment]
I'm running into the same issue on Lubuntu 14.04.  Here's what I've tried that hasn't worked:

- nodejs symbolic link
- Downgrading to less version 1.4.2: https://github.com/odoo/odoo/issues/8674
- Installing less-plugin-clean-css: https://github.com/odoo/odoo/issues/7951
- Installing lxc: https://www.odoo.com/forum/help-1/question/this-error-occured-while-compiling-the-bundle-web-assets-backend-containing-after-insta-llation-of-odoo-version9-89243
- Following official source install instructions: https://www.odoo.com/documentation/9.0/setup/install.html
- Recreating a new database after trying something new

Is there a way to debug the less css compiler to see exactly where it's failing?

Using Odoo on the current 9.0 branch at commit: 9a56bf5

**Comment by sharkende** [comment]
Hello bsphil, I have the same problem and I did everything you did but nothing worked,did you solve it ?

**Comment by tesserB** [comment]
Would anyone else care to confirm @sharkende's fix? @bsphil or @f-ewald, maybe?

@mart-e Good sir...

**Comment by Yenthe666** [comment]
@tesserB and @sharkende this is actually a requirement. Enterprise addons MUST be loaded before the community addons, I'm sure about that.

**Comment by mart-e** [comment]
Yes definitely need to be loaded before

https://www.odoo.com/documentation/9.0/setup/install.html#id6

> If you use git, you must modify the --addons-path parameter of your launch command (init.d, custom script, configuration file, etc.). The Enterprise addons folder should be included before the default addons folder.
> 
> For example:
> 
> $ odoo.py --addons-path=~/src/custom_modules,~/src/enterprise,~/src/odoo/addons
>
