### ISSUE TITLE
Missing dependency for mailcap in RPM package

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#10067]
In RHEL & derivatives, the `mailcap` package installs the `/etc/mime.types` file, which is used by the `mimetypes` Python package to guess the attachment mime type. Without it, SVG files are not served properly for instance. It should be a dependency for the RPM package.

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one?

**Comment by Yenthe666** [comment]
@sle-odoo could you check please?

**Comment by sle-odoo** [comment]
ping @d-fence who is now in charge of the packaging

**Comment by pedrobaeza** [comment]
@Yajo is this still applying?

**Comment by Yajo** [comment]
No idea, long time since I don't use RPM to install Odoo :roll_eyes:

**Comment by pedrobaeza** [comment]
OK, let's close it then.
