### ISSUE TITLE
Odoo9 in "Sales">"Your Pipeline" page title "Your Pipeline" is not translatable

### ISSUE THREAD

**Issue by inventolabs** [odoo/odoo#10066]
in .po file defined this:

> # . modules: sales_team, crm
> # . openerp-web
> # : model:ir.actions.act_window,name:crm.crm_lead_opportunities_tree_view
> # , python-format
> 
> msgid "Your Pipeline"
> msgstr "Ваша воронка продаж"

But when you open "Sales">"Your Pipeline" (on russian "Продажи">"Ваша воронка продаж") text "Your Pipeline" is not translated to "Ваша воронка продаж", but when page is reloaded (F5 in Chrome) - displayed "Ваша воронка продаж", but without left menu.

**Comment by Yenthe666** [comment]
HI @inventolabs,

Thanks a lot for the bug report.
This issue has been solved in the meanwhile, as you can see here on the latest Odoo 9:
![image](https://user-images.githubusercontent.com/6352350/36200081-d22eb85c-117b-11e8-9755-162441310efb.png)

If you still face this issue on your local instance then please update your Odoo source code and translations.

Regards,
Yenthe
