### ISSUE TITLE
[9.0] Product Template with Variants always shows: Warning, The record has been modified...

### ISSUE THREAD

**Issue by javieralmancevo** [odoo/odoo#10063]
I am running Odoo v9, I pulled the code 30 minutes ago to see if this was solved. I have created a new database with only official modules (no custom modules were installed) to verify the bug 

When I create a product with no attributes (so only one variant) everything works fine, but when I create a product template and assign attributes and attr values, the product template form always shows this warning when I click on one of the form buttons even when the record has not been modified and even when it is not being edited:

Warning
The record has been modified, your changes will be discarded. Are you sure you want to leave this page ?
Ok   Cancel

If I open the product template form and directly select a different screen (like Manufacturing or Inventory) the warning does not show. But if I open the product template form, click on a button (f.e. Bill of Materials), select cancel and then select a different screen the warning comes up. So it seems clicking on a product template button form messes up something that makes Odoo think the form has been modified when it is not the case.

**Comment by flotho** [comment]
+1
Same here.
It also appears on invoice

**Comment by nono6677** [comment]
+1

**Comment by javieralmancevo** [comment]
This has been solved for me. Can be closed.

**Comment by nocoolyoyo** [comment]
+1 ! !!!
