### ISSUE TITLE
Erroneous check for editable causes null error

### ISSUE THREAD

**Issue by NeuMediaTech** [odoo/odoo#10073]
Inside set_quantity function (around line 1127), null error exception thrown due to this.order being null when cloned. This impacts bill splitting functionality. 
Steps to repeat: 
1) create restaurant setup with demo data
2) perform bill splitting in POS mode
3) observe exception thrown when selecting an item to split to customer. 

This was added since a9ec289.

**Comment by sauljabin** [comment]
Yes i need this.
Line 1127
addons/point_of_sale/static/src/js/models.js

Maybe //this.order.assert_editable(); ??????

![atributos3](https://cloud.githubusercontent.com/assets/5039802/11908328/1e854946-a5a9-11e5-932d-4df6e0771fb9.png)

**Comment by jorenvo** [comment]
Hi,

This particular issue was fixed in saas-6 at 6e945de681452d6753f58a749352bfbe099bac1d and should be forward-ported to 9.0 shortly.


Kind regards,
Joren

**Comment by Yenthe666** [comment]
This issue was solved at https://github.com/odoo/odoo/commit/6e945de681452d6753f58a749352bfbe099bac1d but was never closed. Closing as this has been solved.
