### ISSUE TITLE
[8.0/9.0] res.lang: Only en_US has xml_id

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#10081]
Hello,

If I need to modify the configuration of a language (fr_BE, pt_PT, etc) using a record in an xml data file, is not possible because loaded translations don't have a defined xml_id, only en_US.

Why other translations are missing xml_id? Can you suggest a clean way to modify installed languages from a module installation?

**Comment by adekock11** [comment]
Good day @aristobulo-eezee. Taking a look at the base module, there is only ever one record added to the res.lang table and that is indeed en_US.

How did you add the fr_BE and pr_PT languages? Manually using Administrator or via a module? If via a module, which module did you use?

**Comment by aristobulo-eezee** [comment]
Installed by going to the menu Load translation with Admin user

Sent from My smartphone, sorry if contain any typos.

_____________________________

**Comment by adekock11** [comment]
Taking a look at https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_lang.py#L46, I can see that when loading a translation in Odoo, if the language does not exist, it is created via Python, meaning that it won't have an xml_id.

I suggest building a module which will add the languages through XML, thus giving them an xml_id. Do this *before* you load a translation.

Else, if you've already got servers where you added the fr_BE and pt_PT languages, take a look at the ir_model_data table. This table is responsible for managing xml_ids. You can manually add records there to give fr_BE and pt_PT an xml_id.
