### ISSUE TITLE
[account] Cancelling Closing (Opening) Entry should not be carry on Closed Periods

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#1008]
Let's create our scenario.

1) Have periods for 2014 FiscalYear
2) Have periods for 2015 FiscalYear
3) Create some invoices and approve them
4) Let's Generate Fiscal Year Opening Entry, fill the regarding fields, and hit Create.
5) Look for the newly created Journal Entry, 
6) Post the Opening Journal Entry.
7) Close the Opening Period for 2015.
8) Let's Cancel Closing Entry, fill 2014, Hit Cancel Closing Entries
9) Search for your Opening Journal Entry in your just closed Opening Period.

Conclusion: This behavior is not according to the principle that after a Period is closed it can not bear any more changes, be them deletion, modifications and additions.

Thanks in advance for your cooperation,

Best Regard

**Comment by mart-e** [comment]
Hello,

It was fixed at 0a1f52ccb5b3704d65760e392f123fab15e3847f.
Thanks for the report.
