### ISSUE TITLE
[9.0] POS Bill Splitting Error

### ISSUE THREAD

**Issue by sebastianbinder** [odoo/odoo#10089]
![image](https://cloud.githubusercontent.com/assets/5227469/11835816/81592f62-a3d6-11e5-995c-2dc04592158f.png)

**Comment by jorenvo** [comment]
Hi,

This issue was fixed a couple of days ago in saas-6 [1] and will be forward-ported to 9.0 soon.

[1] https://github.com/odoo/odoo/commit/6e945de681452d6753f58a749352bfbe099bac1d#diff-b4910f2e838d1b125a771a87dfb8afda


Kind regards,
Joren
