### ISSUE TITLE
Emails with longer top level domains are invalidated

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#10098]
Tried to change my email on https://accounts.odoo.com/my/account to my new @opener.amsterdam address, but Odoo invalidates email addresses with a top level domain longer than 6 characters.

https://github.com/odoo/odoo/blob/9.0/openerp/tools/mail.py#L638

Email validation is known to be difficult. Would you consider using a small, dedicated library like validate_email (https://pypi.python.org/pypi/validate_email) ?

**Comment by wtaferner** [comment]
:+1:

**Comment by mart-e** [comment]
Duplicated of #8608, fix at #8685

**Comment by mart-e** [comment]
Oh well, it has been fixed by @beledouxdenis at 7f29a231186deb1856098d81703848ab6b24328c actually

**Comment by StefanRijnhart** [comment]
@beledouxdenis thanks for the fix!
