### ISSUE TITLE
[8.0] Can't finish "Portal Access Management" wizard.

### ISSUE THREAD

**Issue by kodemi** [odoo/odoo#1010]
I can't choose contact in  "Portal Access Management" form.
![1](https://cloud.githubusercontent.com/assets/213874/3516445/2303e3a0-06e1-11e4-9ad6-e8149318b836.png)
![2](https://cloud.githubusercontent.com/assets/213874/3516444/2303d1c6-06e1-11e4-9bb6-bc6a841ec25f.png)

**Comment by Yenthe666** [comment]
Hi @kodemi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
