### ISSUE TITLE
strange behavior with search_count

### ISSUE THREAD

**Issue by smorele** [odoo/odoo#10103]
Hi,
I have documents which may have a thematic.
If I do:
doc = self.pool.get('document').search(cr, uid, [('thematic', '=', int(thematic_id))]) i'll get [75]
with
doc_counter = self.pool.get('document').search_count(cr, uid, [('thematic', '=', int(thematic_id))]) i'll get 0

How is it possible ?

**Comment by pedrobaeza** [comment]
This is old API, so it doesn't apply anymore and it's not an Odoo issue itself, but something specific to the custom module being developed. Thus I close.
