### ISSUE TITLE
[master] Leave name should not contain spaces to be used in payroll python formula

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#10101]
When defining salary rules there is an option to use python code for computation.
If we want to use number of days leaved this month we can use `worked_days.'LEAVE_NAME'.number_of_days` but usually leave name (`hr.holidays` object) has long name containing space bars for informative description like "Legal leaves 2015" which breaks python code parsing.
Obvious fix would be to provide short `code` field for leave type which will be used in payroll computation instead of `name` field.

**Comment by pedrobaeza** [comment]
This has changed in latest versions, so I invite you to check new rules, and put a new issue if you still find problems.
