### ISSUE TITLE
customer name translate

### ISSUE THREAD

**Issue by it-yagmena** [odoo/odoo#101057]
Impacted versions: 15.0

Steps to reproduce: 'res.partner' -> name = fields.Char('Name', required=True, index=True, translate=True)

Current behavior: form view, translate icon not appearing 

Expected behavior: res.partner name translatable 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Why would you ever want to make a name translatable? 🙄 A name is a name and does not change. If you want this do it in a custom app :)

**Comment by it-yagmena** [comment]
> Why would you ever want to make a name translatable? 🙄 A name is a name and does not change. If you want this do it in a custom app :)
KSA all documents like invoices need to be in Arabic. so we need to provide both English and Arabic. In the custom module, we try to translate name and addres. address translate icons showing.  but the name translation icon not showing 
<img width="868" alt="Screenshot 2022-09-25 at 8 00 51 PM" src="https://user-images.githubusercontent.com/108719657/192155836-d8083f21-cbc5-43a4-98b7-3c487184211e.png">

<img width="791" alt="Screenshot 2022-09-25 at 7 56 58 PM" src="https://user-images.githubusercontent.com/108719657/192155684-5ef49bbb-a44e-4705-a046-10f2c437e447.png">
<img width="859" alt="Screenshot 2022-09-25 at 7 58 14 PM" src="https://user-images.githubusercontent.com/108719657/192155690-026b4bd0-2d47-4074-ae5c-507a3b2f1878.png">
