### ISSUE TITLE
[META] Help Forum : Wrong Profile Picture displayed when you open any Flagged Question.

### ISSUE THREAD

**Issue by malaycmkhamar** [odoo/odoo#101048]
**Impacted versions:**

Live version

**Steps to reproduce:**

- Log in to the Odoo Forum and open any flagged question.
- Check your profile picture.

Current behavior:
It will replace the loged in account profile picture by the person image who has flagged that question.

**Expected behavior:**
It should not replace your profile picture by any other Person's Picture.

Video/Screenshot link (optional):
![profile_issue](https://user-images.githubusercontent.com/114251616/192024038-302f5402-a57b-4638-9d9a-44280d6fa9ee.png)

**Comment by niyasraphy** [comment]
hi @malaycmkhamar ,
this has been fixed in the following commit:  https://github.com/odoo/odoo/commit/31ad927c825f0aea02b3031fa228002ca33f65fd/

feel free to close the ticket's.
thanks
