### ISSUE TITLE
sign-cla.md link redirects to wrong URL

### ISSUE THREAD

**Issue by ArturAronov** [odoo/odoo#101056]
Impacted versions:
15.0 

Steps to reproduce:
Visit ``https://github.com/odoo/odoo/blob/15.0/doc/cla/sign-cla.md`` and click on ``odoo/odoo`` link on LOC 12. 

Current behavior:
Redirects to ``https://github.com/odoo/odoo/blob/15.0/odoo/odoo``, which returns 404

Expected behavior:
Should redirect to ``https://github.com/odoo/odoo``.
Perhaps the ``[odoo/odoo](/odoo/odoo)`` should be changed to ``[odoo/odoo](https://github.com/odoo/odoo)``

**Comment by niyasraphy** [comment]
hi @ArturAronov ,
this has been fixed in:  https://github.com/odoo/odoo/commit/181a1a10451f20c7c0b44aba44addc7a9127c219

feel free to close the ticket.
thanks
