### ISSUE TITLE
9.0 no more 'title' for Company

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10112]
There is no more 'title' field for company
To separate title for contact and title for company is a good idea
Because it was a mess
But we still need a field to define the type (legal obligation) of companies : sa, sprl etc.

**Comment by Yenthe666** [comment]
Hi there,

Thanks for the feedback/suggestion.
As 9.0, 10.0 and 11.0 are stable branches these kind of changes won't be made as they're an improvement, not a bug.

Regards,
Yenthe
