### ISSUE TITLE
Taxes not updated while importing purchase order v8

### ISSUE THREAD

**Issue by haroonhayat** [odoo/odoo#10123]
The bug is that i associated a tax with the product. When i select the product when creating a purchase order the tax field automatically gets populated. But when i import a purchase order the tax field doesnot get populated on the base of product.

**Comment by Yenthe666** [comment]
Hi @haroonhayat,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
