### ISSUE TITLE
odoo16 widget  invalid

### ISSUE THREAD

**Issue by snowtianyou** [odoo/odoo#101255]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by snowtianyou** [comment]
reference  model 'sale_stock' widget

To inherit   js_class="sale_discount_form"  else invalid

**Comment by vava-odoo** [comment]
@snowtianyou Feel free to re-open the issue if you have more information to provide
