### ISSUE TITLE
[9.0] html.Field hyperlinks don't work

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#10128]
The problem is twofold 

Windows 10
Firefox 42.0
Version 47.0.2526.80 m

1) The hyperlinks don't do anything with a left mouse click. But you can open them with a right mouse click selecting "Open in new tab" from the context menu.

2) While editing the link tool tip/popover does't show properly.

In summernote it above the link and in none SAAS versions its not there at all. Only sometimes showing up at the black menu bar.

![tooltip](https://cloud.githubusercontent.com/assets/5089101/11892689/3a9d3e80-a573-11e5-8823-afad199c7717.png)

**Comment by Yenthe666** [comment]
Hi @InfernalLV,

This issue is no longer present on the latest Odoo codebase / browser version.
Closing this since it has been fixed already.

Regards,
Yenthe
