### ISSUE TITLE
(0,0,{values}) invalid

### ISSUE THREAD

**Issue by snowtianyou** [odoo/odoo#101254]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by snowtianyou** [comment]
odoo16  adding record
(0,0,{values}) invalid

order_line_values = {
                'name': '%s (%s)' % (new_order_line.product_id.name, new_order_line.specs_edit.name),
                'partner_decor' : new_order_line.partner_decor.id,
                'attribute_name' : new_order_line.specs_edit.id,
                'product_id' : new_order_line.product_id.id,
                'product_uom':new_order_line.product_uom.id,
                'product_uom_qty' : new_order_line.product_qty,
                'price_unit': new_order_line.price_unit,
            }
            order_lines.append((0,0,order_line_values))
'default_order_line':order_lines,

**Comment by vava-odoo** [comment]
@snowtianyou Feel free to re-open the issue if you have more information to provide
