### ISSUE TITLE
[8.0] point_of_sale: product lots are ignored when creating stock moves

### ISSUE THREAD

**Issue by crimoniv** [odoo/odoo#10136]
When a `stock.picking` is created after confirming a `pos.order`, the generated `stock.move` lines do not keep any reference to the products' current lot (`stock.production.lot`) as they do not have any related `stock.quant`. It is due because of the lack of any **procurement_id** (`procurement.order`) and **group_id** (`procurement.group`) values in the `stock.move`. Also, the **PoS** calls `force_assign` instead of `action_assign` and this does not generate any quant that could keep the product lot.

This issue could be related to the PR #3370.
### Steps to reproduce
- Create new DB with demo data.
- Enable the options **Track lots or serial numbers** and **Expiry date on serial numbers** in `Settings > Warehouse`.
- Ensure that the current user has the access right **Manage Push and Pull inventory flows**.
- Edit the location **Physical Locations / WH / Stock** and set the **Removal Strategy** as **First Expiry First Out (FEFO)**.
- Edit the lot **Lot0 for Ice cream** in `Warehouse > Traceability > Serial Numbers`. Set date 10 days ahead current date in **Removal Date**.
- Edit the product **[1] Ice Cream**. Ensure that it has the type **Stockable Product** and that **Available in the Point of Sale** and **Full Lots Traceability** are checked. Update the **Quantity On Hand** and set a new quantity in the previously configured lot.
### Current behavior
- Create and confirm a PoS Order - in the `pos.ui` view - with any quantity of **[1] Ice Cream**.
- Go to `Warehouse > All Operations > PoS Orders` and click **Transfer** in the created `stock.picking`.
- The lot **is not** automatically assigned.
### Expected results

A similar behavior as in the sale orders:
- Create and confirm a Sale Order with any quantity of **[1] Ice Cream**.
- Open the delivery order, check the availability and click **Transfer**.
- The lot **is** automatically assigned.

**Comment by ZahraMekiAbdallah** [comment]
Dear Crimoniv, Did you find the solution?

**Comment by tafaRU** [comment]
I think that https://github.com/odoo/odoo/pull/14119 could fix it.

**Comment by Yenthe666** [comment]
Hi @crimoniv,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
