### ISSUE TITLE
[8.0] POS Receipt and taxes included in price

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#10137]
Hello, 

I noticed a problem in 8.0 regarding the pos receipt. It is not correct when products have taxes included in price. 

Steps to reproduce
-------------------------

* Create a tax included in price 

Name = 15% INC
Checkbox "Tax Included in price" = true
Tax Type = Percentage 
Amount = 0.15

* Create a product with following characteristics : 

Name = product 1
Sale price = 115
Customer taxes =  15% INC

* Open a POS session

* Choose Product 1, Pay and validate

Current behavior 
---------------------

On the receipt : 

Subtotal : 115
Tax 15% INC : 15
Total : 115

Expected behavior : 
-------------------------

The subtotal must be the amount without taxes

Subtotal : 100
Tax 15 INC : 15
Total : 115

Thanks in advance,

**Comment by jni-odoo** [comment]
Yes Agree..

When a tax with 10% , included in price , gives following in the normal customer invoice..

https://drive.google.com/file/d/0B5j41T1Hqv1sOVd1akRtR3FsS1U/view?usp=drivesdk

Thanks,
Nikunj Jani (Odoo India)

**Comment by jorenvo** [comment]
Fixed in https://github.com/odoo/odoo/commit/dfb0e4b8f1596fe3672791ced17e8f2773fb6051.
