### ISSUE TITLE
Landed Cost - Valuation line with more than 400 lines is taking more than 20mints to complete the process

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#10146]
Adding Landed cost with 8 types of cost lines which generates 420 Valuation lines, and it is taking more than 20mints for validate the landed cost. Is any fix/solution to fix the delay in validating landed cost with more number of valuation lines. ?

**Comment by jeffery9** [comment]
can you give the data of your environment ?

**Comment by pedrobaeza** [comment]
No more feedback, so I close.
