### ISSUE TITLE
[9.0] Discard after duplicate problem

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#10145]
Scenario
1 Enter in CRM module
2 Select a partner
3 The partner form view appear
4 Click on Action->Duplicate
5 A new form appear with the name of the previous partner follow by "Copy" string
6 Click on "Cancel" button
7 The duplicate partner is not delete and is still in database

I have the same problem with account.tax entities.

Regards

**Comment by Yenthe666** [comment]
Hi @rgeromegnace,

Thanks a lot for your report! I've just checked this on the latest Odoo V9 and this is still the case and is actually the behaviour around Odoo.
@mart-e could you throw in an official statement here? Not sure where Odoo stands about this one.

**Comment by mart-e** [comment]
Yes it's because the duplicate button is not opening a new window with suggestions, it is really creating a copy. As people usually wants to modify it after duplication, we open the new in edit mode but really it has already created a copy.
Works as expected.

**Comment by Yenthe666** [comment]
Alright, I was already thinking that. Thanks. (and sorry for mislabelling)
