### ISSUE TITLE
Many2many with track_visibility shows ids in place of names

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10149]
**Many2many with widget mail_thread is not parsed to human content**

Impacted versions:
- 9.0 and above

Steps to reproduce:
1. Create a new many2many in a model
2. Add the many2many to a view and add in the widget mail_thread
3. Add a track_visibility='onchange' on the many2many.

For example in Python:

```
class my_class(models.Model):
    _name = 'many2many.demo'
    _inherit = ['mail.thread', 'ir.needaction_mixin']
     contact_ids = fields.Many2many('res.partner', string='Contacts', track_visibility='onchange')
```

In XML:

```
<field name="message_ids" widget="mail_thread"/>
```

Current behavior:
- When you modify something on the many2many you will get a new message in the chatter with the ids from the record:
  <img src="http://i.imgur.com/4FOYASr.png" alt="Id example"/>

Expected behavior:
- The many2many shows the record names, not ids. No human ever needs to see ids.
  I believe this comes from https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L519-L539

**Comment by Yenthe666** [comment]
@odony and @fpodoo is this something we could change by default behaviour? Nobody has a need to see database id's, right? :smile:

**Comment by tdombos** [comment]
It is the same issue as: https://bugs.launchpad.net/openobject-addons/+bug/1219437

**Comment by Yenthe666** [comment]
@tdombos indeed! So this issue has been in Odoo for more than 2 years..

**Comment by odony** [comment]
@Yenthe666 That's an improvement you could suggest to @tde-banana-odoo indeed, but I'm not sure it [qualifies for a bugfix in stable](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), especially if no core module uses it. It mostly depends on the risk/benefit ratio of the patch: if there's a tiny chance it might break other cases, we're better off saying `track_visibility` doesn't support `many2many` until next version.
BTW from your description it does not seem to have anything to do with the `mail_thread` widget, right? It is simply the result of using `track_visibility='onchange'` on a `many2many`, and your use of the `message_ids` field in combination with `mail_thread` widget is just a way of displaying the effect of `track_visbility`. You could just as well remove the `widget` attribute. If that's correct, you may want to alter the title/description to make it less misleading (I initially thought you were using the `mail_thread` widget to display the many2many field, which made no sense!)

**Comment by Yenthe666** [comment]
@odony thanks for your feedback. Even if its only landing in the next Odoo version I'm happy, it is just one of those things that need a fix for usability.
You're also correct that I'm talking about the ```track_visbility='onchange'``` on a ```many2many```, in essence it doesn't have anything to do with the ```mail_thread``` widget, I'll change the title.
That being said, what would be the cleanest way to get the names from the field in place of the ids? https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L519-L539 how can I detect if it is a ```many2many``` and how could I best parse out the values?

**Comment by odony** [comment]
> That being said, what would be the cleanest way to get the names from the field in place of the ids? https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L519-L539 how can I detect if it is a many2many and how could I best parse out the values?

Detecting the type is trivial, `col_info['type']` contains the field
type already, and is used by `convert_for_display()` to extract
display strings. The basic fix would be to improve
`convert_for_display()` so it would iterate over the records held in
`value` for x2m fields and use their implicit `display_name` field
(`name_get`).
But we should probably fix the algorithm for tracking changes as well,
so it properly detects addition/removal of records and does not
trigger for every change.

**Comment by nhomar** [comment]
@odony We did this module to solve such issue:

https://github.com/Vauxoo/addons-vauxoo/blob/8.0/message_post_model/model/message_post.py


And we made a new one in order to make the unit tests (it need improvements due to every module need to be able to have their own tests).

https://github.com/Vauxoo/addons-vauxoo/tree/8.0/message_post_test

If you think the approach onthose modules is incorrect and the way @odony is the correct one, it should be cool validating the use case tested on the test module.

Regards.

**Comment by nhomar** [comment]
@odony I think models like sale.order and purchase.order can benefit hugly on this feature, now only the total is tracked but it is usefull track the lines also.

We used our module for such deal and it helps a lot.

Then may be a core module can use the feature if it is available.

**Comment by Yenthe666** [comment]
@odony and @xmo-odoo could I ping you guys again on this one please? I'd like to have this fixed in V10 atleast.

**Comment by tde-banana-odoo** [comment]
Hello,

Supporting the m2m field could be an interesting feature for the messaging module, indeed. However we cannot ensure it will be done for v10.

**Comment by Yenthe666** [comment]
Hi @tde-banana-odoo,

Is there a reason why this cannot be made by V10?
it would be quite an improvement to the system and otherwise it will take another year atleast to introduce this, since it cannot be added in a stable release.

**Comment by tde-banana-odoo** [comment]
Well the basic reason is time. If you have a PR to submit, feel free to do it, I can review it. But currently we have other priorities, like the new MRP, migrating the modules to the new API, ... I would like to have a look at this feature, but I am not sure I will have time to do it. We have to carefully implement it to avoid a costly feature, and I think it will take some time. That's why I cannot ensure it will be done for v10.

**Comment by Yenthe666** [comment]
Hi @tde-banana-odoo,

Could you give me an update / feedback for this one?

**Comment by Yenthe666** [comment]
@tde-banana-odoo any update?

**Comment by Yenthe666** [comment]
@tde-banana-odoo and @odony is there any update on this please?

**Comment by tde-banana-odoo** [comment]
Hello,

Not really. Tracking mechanism will probably change between v11 and v12 but there is still nothing specified. We have to find a tradeoff between readability, performances and use of stored tracking data. It is one of the tricky point we will have to figure out before v12.

**Comment by seyed-mohammad-motahar** [comment]
Reading this, I think https://github.com/Vauxoo/addons-vauxoo/tree/11.0/message_post_model on v11 is what we should look after to migrate for our customer.

**Comment by pambudisatria** [comment]
Is there any update on this? Because it's also impact in version 8.0

**Comment by Yenthe666** [comment]
@pambudisatria no there is no update and it is relevant in any Odoo version at the moment.
P.S: Odoo 8 is end of life so don't expect any changes or fixes anymore there.

**Comment by pambudisatria** [comment]
@Yenthe666 great, I have to fix by myself 😄  Thanks for your information.

**Comment by Yenthe666** [comment]
@mart-e and @tde-banana-odoo could you give an update please?

**Comment by mart-e** [comment]
I guess same answer as before, nothing was done and it is not on our roadmap at this time but if somebody got a PR, we can review it.

**Comment by guewen** [comment]
We've made some work in the OCA for 10.0: https://github.com/OCA/social/pull/170 and 11.0: https://github.com/OCA/social/pull/254

**Comment by pedrobaeza** [comment]
@guewen maybe you can propose the change on master branch

**Comment by pedrobaeza** [comment]
Closing as it's not expected in the near roadmap and it's complicated to get it with good performance. See the proposed OCA modules as an alternative.
