### ISSUE TITLE
[15.0] Purchase Order: decreasing ordered quantity creates an outgoing Delivery Order

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#101426]
Impacted versions:
15.0

Steps to reproduce:
1. On Decimal Accuracy, set "Product Price" to 4
2. Create PO for "[FURN_6666] Acoustic Bloc Screens", Qty=10, Price=0.8652, Tax=15%
3. Click on "Confirm Order"
4. Edit to decrease quantity from 10 to 9, ensure that Price=0.8652, and save

Current behavior:
- The original Receipt  is unchanged with Qty=10
- The PO Receipts will list an additional WH/OUT transfer with qty=1

Expected behavior:
- The original Receipt  is changed to Qty=9

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1246629/192783260-0dfac96a-960f-4117-95ba-ddd33aa28702.png)
![image](https://user-images.githubusercontent.com/1246629/192783525-85cfd62d-ef7c-4f31-ae0d-1462e7f5607c.png)

Support ticket number submitted via odoo.com/help (optional):
#3002361

**Comment by dreispt** [comment]
Updated with support ticket number: #3002361

**Comment by nouraellm** [comment]
fixed in #97344
