### ISSUE TITLE
[8.0] translation export for fields.Selection doesn't work in case of field extension

### ISSUE THREAD

**Issue by codingforfun** [odoo/odoo#10144]
If a new case is added to an already existing selection field by extending the field in another module, the new selection cases do not get exported for translation.

**Comment by danimaribeiro** [comment]
I also find that when the selection field have the property "related=" the translation is also ignored.

**Comment by danimaribeiro** [comment]
I have identified the problem is here:
https://github.com/odoo/odoo/blob/8.0/openerp/tools/translate.py#L749

_columns does not contain the field in those cases, there is also the value _fields in this object, in _fields it shows up.

**Comment by Yenthe666** [comment]
Hi @codingforfun ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: If I am not mistaking you don't get the translations exported for your custom module but you would get them when exporting the original module you've extended. 

Regards,
Yenthe
