### ISSUE TITLE
how we inatall WTForm in wnidows for odoo v9

### ISSUE THREAD

**Issue by kartikdanidhariya** [odoo/odoo#10153]
hi,
i create one custom module in Ubuntu odoo v9
after that when i try to install that same module in windows environment in odoo v9
so it return error like "import error : no module installed wtform"

after that i install wtform in my windows using "pip install WTForm"
and it install successfully after i check using "pip freeze" so it installed 
but it still return same error
so how can i solve this error
please help!!!

**Comment by Yenthe666** [comment]
@kartikdanidhariya issues is made for bugs inside Odoo, not for asking questions.
I see you've created a question here https://www.odoo.com/nl_NL/forum/help-1/question/how-we-install-wtform-in-odoo-v9-in-windows-environment-94739 nobody from Odoo will help you with this I'm afraid, this is a community question.

**Comment by xmo-odoo** [comment]
Pretty much what @Yenthe666 explained, this is not an Odoo issue or an issue with an Odoo dependency, this bug tracker isn't the right place to ask about it.
