### ISSUE TITLE
[9.0 OE] Could not get content defined in bundle 'web.assets_backend' when doing -u all

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10157]
**Could not get content defined in bundle when doing -u all**

Impacted versions:

 - 9.0 Enterprise

Steps to reproduce:

 1. Install a clean Odoo V9 & V9 Enterprise on top of it
 2. Create a new database
 3. Install some modules
 4. Do a git update for the code. For example:
```
git fetch origin 9.0
git reset --hard origin/9.0
```
 5. Do a ```./openerp-server -u all``` 
 6. Behold new errors about the web.assets_backend bundle:
<img src="http://i.imgur.com/UbHtNCT.png" alt="Asset issues"/>

What I've tried so far:
- Installed all requirements with ```sudo pip install -r requirements.txt```
- Added a symlink for NodeJS ```ln -s /usr/bin/nodejs /usr/bin/node```

If you wish you can simulate this issue very easily. Use my installation script for Odoo V9 enterprise and follow the steps I've written above. You can find my script at https://github.com/Yenthe666/InstallScript/blob/Enterprise/odoo_install.sh

Possible related issues:
https://github.com/odoo/odoo/issues/4755
https://github.com/odoo/odoo/issues/8432
https://github.com/odoo/odoo/issues/8674
https://github.com/odoo/odoo/issues/8676
https://github.com/odoo/odoo/issues/8809

Current behavior:

 - 'web.assets_backend' issues regarding content

Expected behavior:

 - No asset issues, everything is rendered correctly.

**Comment by Yenthe666** [comment]
This <b>might</b> have to do with the fact that the ```.odoo.py --xmlrpc-port=8080``` doesn't know where to find the Enterprise resources when you've split the Communtiy code and Enterprise code.
A possible fix could be ```.odoo.py --xmlrpc-port=8080 -c /etc/yourConfigurationfile.conf```.
I'll test this further soon and keep an update on this topic.

**Comment by felixvillafranca** [comment]
Hello;
Have you installed the enterprise edition too?
If yes then You have to reference the entrerprise addons folder before the community addons folder in the open-server.conf.
For me It works.

**Comment by Yenthe666** [comment]
@felixvillafranca thanks for the tip but this is the case! It seems to have to do with manually starting the Odoo without the configuration file. If I have some time I'll play around a bit more to find all usecases.
