### ISSUE TITLE
[8.0][hw_blackbox_be] New module breaks OCA runbots

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#10159]
[This warning](https://github.com/odoo/odoo/blob/8.0/addons/hw_blackbox_be/controllers/main.py#L46) breaks OCA runbots, which are configured to fail on warnings.

The error message is:

```
2015-12-17 16:57:15 	WARNING 	server 	openerp.addons.hw_blackbox_be.controllers.main:46 _find_device_path_by_probing /dev/serial/by-id/ doesn't exist
```

You can see it in any OCA runbot, https://runbot.odoo-community.org/runbot/build/3137559 for example.

Please remove it or convert to info. Thanks.

**Comment by rafaelbn** [comment]
Please help Odoo

**Comment by jorenvo** [comment]
Hi,

The hw_* modules are supposed to be blacklisted on the runbot. I'll take care of it today.


Kind regards,

**Comment by jorenvo** [comment]
Hi,

I was under the impression that we managed that runbot but we don't. So there's not much I can do. hw_* modules should be blacklisted on the runbot:

https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L714

Perhaps you need to update the runbot code you're running, it was added relatively recently (Jun 18):

https://github.com/odoo/odoo-extra/commit/ff3a7b1b6e5d333daafcb41884be3d4ec4b73527

The reason we don't install the hw_* modules on the runbot is that there's no point in installing them. They're not tested, and they spawn threads that poll for certain devices, which is not something we want on the runbot.


Kind regards,

**Comment by Yajo** [comment]
@pedrobaeza Do you know who is in charge of OCA runbot blacklists?

**Comment by pedrobaeza** [comment]
There is no blacklist on runbot. @gurneyalex is fixing runbot, so maybe this problem (that is only a warning, so it's not critical) goes with the fixing.

**Comment by gurneyalex** [comment]
@Yajo @pedrobaeza that's part of the things I intend to fix in the coming days. The OCA runbot is running on a different branch than the official runbot (https://github.com/gurneyalex/odoo-extra/tree/OCA-runbot to be precise). I tried to introduce the blacklists  last week but this did not quite work as intented and I have more work to do on this. 

Pull requests against the OCA-runbot branch of that fork are welcome.

**Comment by jorenvo** [comment]
Thanks for clearing this up @gurneyalex. I'm closing this issue since it's out of our control.
