### ISSUE TITLE
[8.0] reordering rule doesn't work

### ISSUE THREAD

**Issue by mylbco** [odoo/odoo#10151]
Scenario : 
Use the standard runbot version 8.0 with standard demo data set.
1) Settings > Warehouse
Checkbox  ‘Manage multiple locations and warehouses’ should be checked.  

2)  Warehouse > Settings > Warehouse
Incoming Shipments Unload in input location then go to stock (2 steps) 

3) Sales > Products > Products
I use the product Blank CD in my scenario (it has stock 0, forcasted 0)
filter product : Blank CD
check checkbox only on route  'Buy' 

4) Add reordering rule to this product 

Warehouse : YourCompany 
Location : WH/Stock 
minimum : 10
maximum  : 20

5) Warehouse > schedulers > Run scheduler
6) Purchase > Purchase > Request for Quotation
Filter on product Blank CD and you will get a new RFQ (supplier mediapole).
Change the quantity 20 to 9  in het RFQ and press the red confirm button.

Click on the Shipments button and receive all (9) of the ‘Blank CD’
Now you can see the problem …

7) Warehouse > schedulers > Procurements
Filter on the product ‘BLANK CD’

You see 2 procurements : 
![procurements](https://cloud.githubusercontent.com/assets/3402495/11920281/bd540cf2-a76a-11e5-948a-b55fc0c96c44.png)

8) We goto the Warehouse > All Operantions > ‘Internal transfer’ 
select the internal transfer for the 'BLANK CD' (input -> stock)
Change the quantity of the stockmove from 20 to 9 (+ save) 
Press the red 'transfer' button 
Transfer all 9 products. (status = done) 

9) Warehouse > Scheduler > Run Schedulers
We should get now again a new RFQ (Blank CD’s) with qty 11.

Because there is a procument that is open on the stock location, odoo will not create a new procurement to purchase the product.

How can I get this procurement ‘Done’ to solve the situation ?

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your (very detailed!) bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
