### ISSUE TITLE
thank you very much for this solution! , how can we do same so team leader to view and edit sales orders of team members ?

### ISSUE THREAD

**Issue by ali123pyth** [odoo/odoo#101598]
thank you very much for this solution!
for newbies like me:
to apply this solution, I need to 
1) click profile -> about -> activate the developer mode 
2) to visit settings -> groups http://......./web?&debug=#page=0&limit=80&view_type=list&model=res.groups&menu_id=78&action=68
3) open Setting -> Security -> Record Rules
/web?&debug=#page=0&limit=80&view_type=list&model=ir.rule&menu_id=36&action=20
find "All Leads"
action -> duplicate
name "Team Leads"
Replace Rule Definition (Domain Filter)
[(1,'=',1)]
with 
['|','|','|',('user_id','=',user.id),('user_id','=',False),('team_id.member_ids','in', [user.id]),('team_id.user_id','=',user.id)]

3) to find group "Sales / See All Leads" (use search for "sales"), then click     action -> duplicate -> insert name "See Team Leads"

5) edit new created  "See Team Leads", open ''Rules" tab 
delete all rules
add rule "Team Leads"

6) Settings-> users
find team lead person, edit him
Set active checkbox on 'See Team Leads'

7) test it.

_Originally posted by @kaurov in https://github.com/odoo/odoo/issues/4682#issuecomment-237640104_

**Comment by nouraellm** [comment]
@ali123pyth can you please explain the issue clearly? also, put steps to reproduce.

**Comment by ali123pyth** [comment]
Salam Noura : i've been trying to gather our sales people in teams , and each team has a team leader , which is "out of the box" in Odoo, but what team leader privileges ? almost nothing , our team leaders want to have a closer look of what their team members are doing , what leads they are handling, quotations , sales order , invoices or even delivery notes. so i found many apps that i can buy, which i don't want, and i found this post here, so i amended this steps and now our teams leaders can view and monitor their team members records on Odoo. that's all ... please let me know if you need anything.  RGDS / Ali

**Comment by ali123pyth** [comment]
i just finalized sales orders as well. now team members can see team's leads and team's quotations/sales , and off course we can always keep these privileges  to be for team lead only. super easy..
