### ISSUE TITLE
[9.0] Tutorial tips on archive buttons unclickable

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10155]
**Tutorial tip is unclickable**

Impacted versions:

 - 9.0 Enterprise

Steps to reproduce:

 1. Create a new database
 2. Install the project module
 3. Go to Projects > Tasks and open up a project
 4. Follow the tutorial that gives you hints about how Odoo works. You will now get one for the archiving button:
<img src="http://i.imgur.com/ZRVkj7a.png" alt="Tooltip"/>
 5. Click on the tooltip, you will now see the click event triggers the task to be archived and that there is no way to make the tooltip go off.

Current behavior:

 - The tutorial tip is unclickable and makes you archive the task.
Expected behavior:

 - Tutorial tip is clickable and shows you the information.

**Comment by Yenthe666** [comment]
@odony and @xmo-odoo who should I tag for Enterprise issues?

**Comment by dreispt** [comment]
+1
This issue seems to be specific to the "Archive" smart button, at least both on projects and on Tasks.
I find no way to dismiss that tip.

**Comment by odony** [comment]
As noted by @dreispt and @adekock11, this applies to all archive buttons, and in 9.0c as well

**Comment by odony** [comment]
@qsm-odoo @ged-odoo perhaps you guys could have a quick look at this? Thanks!

**Comment by qsm-odoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/813b6a84ab9397508d41e15ffc4bc45f3cdb06c2
