### ISSUE TITLE
[account_anglo_saxon] Price Difference Account should be a required field

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#10168]
Impacted versions:
- 8.0

Steps to reproduce:
1. Install module 'account_anglo_saxon'
2. Activate the setting to generate accounting entries from stock moves
3. Create a new GL account X1115 Goods Received Not Invoiced
4. Assign the GL account to product category "Ipad". 
5. Field 'Price Difference Account' in product category is left blank
6. Edit product "iPad Mini" and set Inventory Valuation = Real Time. Standard price is 800
7. Create a Purchase Order for 1 Unit of iPad Mini with PO price "1000" & confirm
8. Receive the product
9. Create and validate supplier invoice

Current behavior:
Journal entry 1 (Created from stock move):
Dr. Stock Valuation 800
Cr. X1115 Goods Received Not Invoiced (Stock Input) 800

Journal entry 2 (created from invoice):
Dr. X1115 Goods Received Not Invoiced (Stock Input) 1000
Cr. Accounts Payable 1000

Expected behavior:

Journal entry 1 (Created from stock move):
Dr. Stock Valuation 800
Cr. X1115 Goods Received Not Invoiced (Stock Input) 800

Journal entry 2 (created from invoice):
Dr. X1115 Goods Received Not Invoiced (Stock Input) 800
Dr. Price Difference 200
Cr. Accounts Payable 1000

Note: While assigning the Price Difference account to the product category will make the journal entries be correct, it should not be allowed for a user to validate a supplier invoice in this circumstance, as it will generate incorrect journal entries and a debit balance in the Goods Received Not Invoiced GL Account.

**Comment by raycarnes** [comment]
I worked with a Customer who didn't want this field required - they preferred to see what the difference was at the end of the period and then credit the entire amount out (I'm not even sure where to!).

**Comment by Yenthe666** [comment]
Hi @jbeficent ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
