### ISSUE TITLE
[8.0] In stock moves with products with real-time valuation production/inventory loss/scrap location gl accounts should be required

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#10169]
Impacted versions:
- 8.0

Steps to reproduce:
1. Create a new product with real-time inventory valuation
2. Maintain as stock input account "Goods Receipt Not Invoiced"
3. Maintain as stock input account "Goods Delivered Not Invoiced"
4. Go to Inventory Loss location and leave empty stock input & output accounts
5. Create a physical inventory and report variances
6. Validate the physical inventory

Current behavior:

The journal entries resulting from the stock move will use the gl accounts "Goods Receipt Not Invoiced" and "Goods Delivered Not Invoiced" defined in the product.

Expected behavior:

If a stock move occurs to a production or inventory location, where the product is stockable and subject to real-time inventory valuation, it is expected that the production or inventory location should have defined GL accounts for stock input & output fields. Otherwise the system should not allow the user to complete the inventory adjustment or production.

I cannot see a business scenario where the result should be the use of the product's stock input & stock output accounts.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
