### ISSUE TITLE
[9.0] Error POS restaurant

### ISSUE THREAD

**Issue by sauljabin** [odoo/odoo#10166]
When split order
Line 1127
addons/point_of_sale/static/src/js/models.js
this.order.assert_editable();

See: https://github.com/odoo/odoo/issues/10073
![1e854946-a5a9-11e5-932d-4df6e0771fb9](https://cloud.githubusercontent.com/assets/5039802/11933067/8f578042-a7c7-11e5-9fea-cc07eda8b12a.png)

**Comment by jorenvo** [comment]
Hi,

This particular issue was fixed in saas-6 at 6e945de681452d6753f58a749352bfbe099bac1d and should be forward-ported to 9.0 shortly.


Kind regards,
Joren
