### ISSUE TITLE
[8.0] Exception when filtered on account journals and periods in the reconciliation view.

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#10174]
Hi,

Here a scenario on runbot 8.0

Steps to reproduce
-------------------------

- Go on runbot 8.0
- Logon with Admin
- Go on Accounting/Periodic Processing/Manual Reconciliation
- Add a filter on EUR journal. Just type 'EUR' in the search bar and click on  "Search Journal for: EUR"
- Add a filter on 2015 period. Just type '2015' in the search bar and click on  "Search Period for: 2015"

Expected behavior
-------------------------

There should be a filter on periods and journals

Current Behavior
-----------------------

An exception is raised.

![capture du 2015-12-22 08 46 01](https://cloud.githubusercontent.com/assets/8035793/11950433/7995155a-a888-11e5-8ea2-5b52221677c0.png)

**Comment by adrienpeiffer** [comment]
OPW 660591

**Comment by simongoffin** [comment]
Closed by this commit d96050d3e0ec5731c37309e39001c0e127ad7899
