### ISSUE TITLE
[8.0] Do not allow a user to change the product type, GL accounts or Inventory Valuation if there's stock or open orders

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#10171]
It should not be possible to change a product type (e.g. from stockable to consumable or viceversa) or valuation GL account in the product or product category if stock or open manufacturing orders or open purchase orders exist for that product, when the product is maintained under the real-time valuation. This will prevent the generation of accounting inconsistencies due to such changes, since a change in the product type or gl account would normally require a re-classification of the inventory value to a different gl account.

Only when there's no stock, no manufacturing orders, no open purchase orders, can the change occur.

**Comment by Yenthe666** [comment]
Same question here - do you feel it is still relevant and that we should change it to another version? 😄
