### ISSUE TITLE
[8.0] Cannot easily reconcile debits and credits of GL account 'Goods Received Not Invoiced'

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#10172]
GL Account "Goods Received Not Invoiced" (associated to the Perpetual inventory accounting system, and with Anglo Saxon general accepted set-up) should normally stay low or zero, and the balance should reflect the transactions that are outstanding from the 3 way match perspective.

In order for the user to be able to analyze the status of this GL account, there should be the possibility to reconcile debits and credits of the same transaction, so that the remaining balance indicates the value of products that have been received, for which no invoice has been entered or viceversa.

If this reconciliation between transactions does not occur, it will be very hard to identify the causes of an existing balance in this GL account.

Current reconciliation in Odoo using manual process is now difficult due to the lack of information about the purchase order & line available in the journal items.

Existing automatic reconciliation tools in Odoo will only use the GL Account and Partner as the basis to reconcile debits and credits.

In order to be able to reconcile this account the journal items should indicate the originating purchase order (and ideally the purchase order number as well).

The automatic reconciliation tools should be adjusted in order to incorporate the PO as criteria for the reconciliation process.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Are you fine with me closing this since 8.0 has lost its LTS?
If you still feel like this problem is relevant we might change the title to a newer version. Waiting for your feedback. 😉
