### ISSUE TITLE
Odoo 9 Error in Firefox 42 TypeError: context.nodeName is undefined

### ISSUE THREAD

**Issue by tomisweet** [odoo/odoo#10180]
I found this Error only in Firefox the app works perfectly in other browsers. The Error is: 
<em>TypeError: context.nodeName is undefined<em>
![error](https://cloud.githubusercontent.com/assets/9625459/11965427/855d602c-a905-11e5-972f-660d14985730.png)

http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:495
Traceback:
Sizzle@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:495:93
Sizzle</Sizzle.selectors.pseudos.has</<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:558:495
elementMatcher/<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:577:124
matcherFromGroupMatchers/superMatcher@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:595:107
Sizzle</Sizzle.select@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:613:2
Sizzle@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:499:8
.find@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:623:20
Widget<.$@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:2637:24
WebClient<.toggle_bars@http://localhost:8069/web/content/956-f53e29e/web.assets_backend.js:3113:1904
WebClient<.show_application@http://localhost:8069/web/content/956-f53e29e/web.assets_backend.js:3113:2614
.show_application@http://localhost:8069/web/content/956-f53e29e/web.assets_backend.js:4218:282
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:2535:368
.show_application@http://localhost:8069/web/content/956-f53e29e/web.assets_backend.js:4386:1687
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:2535:368
WebClient<.start/<@http://localhost:8069/web/content/956-f53e29e/web.assets_backend.js:3111:545
.Deferred/promise.then/</</<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:650:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:651:31
loadJS/script.onreadystatechange@http://localhost:8069/web/content/953-0ecc113/web.assets_common.js:2549:25

**Comment by Yenthe666** [comment]
Hi @tomisweet,

This issue can no longer be reproduced so it is probably fixed in the meanwhile.
If you still face this problem please let me know and add more information about how to trigger it step by step.

Regards,
Yenthe
