### ISSUE TITLE
[9.0] Installing python-xlrd package breaks CSV preview (and therefore import)

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#10199]
On Ubuntu 14.04 LTS, I have noticed that installing **python-xlrd** (0.9.2-1) breaks CSV preview (and therefore import).

By running **sudo apt-get remove python-xlrd** and restarting the server, CSV preview (and import) works again.

Note: Runbot instances do not appear to have python-xlrd library installed.

---

CSV preview (before import) **without** XLRD installed:
![Without XLRD](http://i.imgur.com/4iukCwv.png)

---

CSV preview (before import) **with** XLRD installed:
![With XLRD](http://i.imgur.com/XFy3rW0.png)

---

On runbot, I always get the first (success), but when I try to import an XLSX file, I get:

Import preview failed due to: Unable to load "xlsx" file: requires Python module "xlrd >= 0.8".

**Comment by boscoerp** [comment]
Facing same issue. 

![image](https://cloud.githubusercontent.com/assets/17794701/13735339/293183d2-e9ce-11e5-8b75-8288d9cf0139.png)

any work around !

**Comment by bistaray** [comment]
I can't replicate this on runbot as of today (http://139699-9-0-f4cc88.runbot.odoo.com/).  I am now wondering if this has been resolved. Runbot now seems to have py-xlrd installed (because XLS import works).

**Comment by bistaray** [comment]
However, the SAAS version is UNABLE to import XLS files:

Import preview failed due to: Unable to load "xls" file: requires Python module "xlrd".

For CSV files, the issue could be an incorrect encoding.

**Comment by wtaferner** [comment]
@bistaray 
Not sure about the SaaS but at least a big part of the issue was fixed in https://github.com/odoo/odoo/pull/10374 in two steps.

**Comment by Yenthe666** [comment]
I believe this was all handled & fixed (as @wtaferner pointed out).
Don't hesitate to comment / reopen if you can still reproduce it.
