### ISSUE TITLE
[15.0] account.report_invoice_document: date label is printed 2 times

### ISSUE THREAD

**Issue by OKT96** [odoo/odoo#102087]
Impacted versions: 
15.0

Steps to reproduce: 
Print out any invoice or credit note

Current behavior: 
The date label is printed 2 times in the invoice:

![image](https://user-images.githubusercontent.com/85667041/193820973-6cf46f2c-9c14-4ed9-9fcb-de63d913b713.png)

Expected behavior:
The date label should be printed 1 time, depending on the move_type

**Comment by OKT96** [comment]
5fc79dc8da4ff4912404426b0609b3a5859e68e7 introduced additional date labels depending on the move_type of a invoice

**Comment by hoangtrann** [comment]
Could you propose a PR for this?

**Comment by william-andre** [comment]
https://github.com/odoo/odoo/pull/102558
