### ISSUE TITLE
[PATCH] missing .id on restrict_partner_id leads to errors on database write

### ISSUE THREAD

**Issue by awpeters** [odoo/odoo#10206]
<pre>
diff --git a/addons/stock/stock.py b/addons/stock/stock.py
index 98a15b5..e8b5953 100644
--- a/addons/stock/stock.py
+++ b/addons/stock/stock.py
@@ -1362,7 +1362,7 @@ class stock_picking(osv.osv):
             'product_uom_qty': qty,
             'name': _('Extra Move: ') + name,
             'state': 'draft',
-            'restrict_partner_id': op.owner_id,
+            'restrict_partner_id': op.owner_id.id,
             'group_id': picking.group_id.id,
             }
         return res
</pre>

**Comment by Yenthe666** [comment]
Hi @awpeters,

Please submit such changes as a pull request, with detailed information about what it does and why you want to change it.
I see no problem with the current way and this is not an issue so I'm closing this.

Regards,
Yenthe
