### ISSUE TITLE
[9.0] zh_CN time format can't save (datetime fields)

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#10200]
Impacted versions:
- 9.0

Steps to reproduce:
1. create a datetime field
2. change my language to zh_CN
3. set time on form

Current behavior:
- can't save, it's invaild on js

Expected behavior:
- save it

Solution:
- res.lang model
- zh_CN record
- change time_format field to   %H:%M:%S

Please set time_format %H:%M:%S  by default when generate zh_CN res.lang record

![qq 20151224102722](https://cloud.githubusercontent.com/assets/11750796/11988335/f1f9ec54-aa28-11e5-9375-735b1bb2e935.png)

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
