### ISSUE TITLE
Web Display errors still in V9.0 nighly build  on a clean build fedora 22

### ISSUE THREAD

**Issue by ptj531** [odoo/odoo#10215]
last fedora 22 build
ODOO  V9.0 nightly build

First time bring up localhost:8069   in firefox
Still are seeing TypeError:  invalid data error.

similar to https://github.com/odoo/odoo/issues/7951
Have tried suggested work arounds and are not effective,

![image](https://cloud.githubusercontent.com/assets/16452466/12010483/f92acac0-ac76-11e5-8541-c579900df84f.png)

**Comment by eronlloyd** [comment]
I'm having the same exact issue on Fedora 23; clean, fresh new install of everything, pulled down Odoo from nightly. The install went completely smooth with no errors, but the web interface is still rending like above.

**Comment by sle-odoo** [comment]
Please try again with the latest build.
```
dnf install postgresql-server postgresql-contrib
postgresql-setup --initdb --unit postgresql
systemctl start postgresql
dnf config-manager --add-repo https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
dnf update
dnf install odoo
systemctl start odoo
```
These commands on Fedora 23 are working at my end.
Regards
