### ISSUE TITLE
[16.0] bad display of text field

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#102167]
Impacted versions: 16.0 alpha (maybe previous version). (12.0 is working correctly.)

### Steps to reproduce:

- with Odoo CE commit https://github.com/odoo/odoo/commit/6c6d7ce06ed4b18162db893a0afb65e0479ee11f (October, 4 2022)
- install ``product`` module
- go on product form. try to edit internal note.

Current behavior:

- the field is bad displayed.

(empty field)
![image](https://user-images.githubusercontent.com/3407482/193908022-94398b27-452b-43f6-8b66-2669fc9e9059.png)

(with some text)

![image](https://user-images.githubusercontent.com/3407482/193908366-6bbc873e-0830-4c0e-a2df-0292bd7e3865.png)

### Expected behavior:

- field well displayed.

CC : @bouvyd

**Comment by bouvyd** [comment]
Fix is about to be merged

**Comment by bouvyd** [comment]
(in #102119)
