### ISSUE TITLE
track issue regarding for mail template

### ISSUE THREAD

**Issue by shivam-laxicon** [odoo/odoo#10212]
version 8: 
    when move to next stage, gives with responsible in chatter v8
    https://github.com/odoo/odoo/blob/8.0/addons/crm_claim/crm_claim.py#L90 (working  track_visibility='always'

please check the diff @runbot
http://121843-8-0-2fa038.runbot8.odoo.com/web?db=121843-8-0-2fa038-all#id=9&view_type=form&model=crm.claim&menu_id=554&action=667

version 9:  
    issue : when move to next stage, not gives with responsible in chatter v9
    https://github.com/odoo/odoo/blob/9.0/addons/crm_claim/crm_claim.py#L65 (not working track_visibility='always')

please check the diff @runbot
http://121976-9-0-bcca4a.runbot8.odoo.com/web?#id=9&view_type=form&model=crm.claim&menu_id=476&action=657

![claim1](https://cloud.githubusercontent.com/assets/10597339/12002658/14334fac-ab2a-11e5-9eb1-1f1c40e6cdf1.png)
![claim9 0](https://cloud.githubusercontent.com/assets/10597339/12002657/143329dc-ab2a-11e5-94f3-ba26d2c231d4.png)

**Comment by KCITSindia** [comment]
Currently my issue was closed by mart-e but until i can not have any solution

**Comment by Yenthe666** [comment]
Hi @shivam-laxicon ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
