### ISSUE TITLE
[8] chatter history dose not follow the real history

### ISSUE THREAD

**Issue by OmniaGit** [odoo/odoo#10237]
![capture](https://cloud.githubusercontent.com/assets/14873448/12048214/5988d0ac-aed8-11e5-96ff-13c6a5eb5f0d.PNG)
as you can see from the attached image, the chrono story of the chatter is wrong.
in our case we have a scheduled action every 30 minutes and the e mail arrived after the log message.
The chatter seems to sort the items in creation order instead of date of the events

regards
Matteo

**Comment by Yenthe666** [comment]
Hi @OmniaGit,

I can no longer reproduce this issue on the latest runbots. An example:
![image](https://cloud.githubusercontent.com/assets/6352350/16076635/87239380-32f4-11e6-94f4-040d46866b81.png)

Regards,
Yenthe
