### ISSUE TITLE
[9.0] Discuss app does not work with translated language

### ISSUE THREAD

**Issue by njeudy** [odoo/odoo#10230]
Hello,

# Discuss app can not be used with translated language:

## To reproduce:

- Connect to runbot with entreprise 9.0 or community 9.0
- Add french language
- Use franch lang on administrator account
- Go to discuss app

**Odoo version used**: http://122201-9-0-ab3d1f.runbot8.odoo.com/web?#menu_id=151&action=164&active_id=channel_inbox

## Whats apprend ?:

- Discuss app does not list existing channels
- You can not add new channels

See this video: https://www.youtube.com/watch?v=omF0rcQtGfg&index=3&list=PLay1utIeXbcJ4QF78r2nENKp-v0OBNAMq

## Technical:

![data-type are translated !](https://www.dropbox.com/s/glhisx02vw4bfod/Capture%20d%27%C3%A9cran%202015-12-29%2012.32.51.png?dl=1)

- Data-type arg on html / qweb template are translated in french and js code use it to trigger events, list, etc ..

Think data-type should not be translatable.

**Comment by aab-odoo** [comment]
Hello,

Thanks for your bug report. This has been fixed at https://github.com/odoo/odoo/commit/3f370651c7035137a8fb71ce391d820e5e12bda4.

Regards
