### ISSUE TITLE
[9.0] Financial Report not sorted the right way...

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#10240]
Hi there,

I think there is a problem with the implementation of account_financial_report, the tree of accounts is not browsed deep first as it should.

The _get_children_by_order should be fixed into something like :

```
def _get_children_by_order(self):
        '''returns a recordset of all the children computed recursively, and sorted by sequence. Ready for the printing'''
        res = self
        children = self.search([('parent_id', 'in', self.ids)], order='sequence ASC')
        if children:
            for child in children:
                res += child._get_children_by_order()
        return res
```

Best Regards,

Jerome

**Comment by csnauwaert** [comment]
Hello,

It would seems that this issue has already been fixed a while ago by this commit: https://github.com/odoo/odoo/commit/9807ff8a91bd81d4cff7a5def02d231f8514db59

Therefore I'm closing this issue. Feel free to comment if there is still a problem.
Best regards
