### ISSUE TITLE
wkhtmltopdf for armhf

### ISSUE THREAD

**Issue by DavidGoodenough** [odoo/odoo#10249]
I am running odoo (still on 8) on a cubieboard-2 under Debian.  It runs very nicely - except that I can not print anything as wkhtmltopdf is only available as the standard debian version.

Would it be possible to put either the recipie for building the odoo version of wkhtmltopdf somewhere accessible, or to add an armhf version on the nightly server.

Thank you.

**Comment by witwall** [comment]
I use wkhtmltopdf on my android (GNUROOT Debian),  it wkhtmltopdf needs an X server (screen), so you need install xvfb too. 

I have a post talks about it, feel free to have a look,

[GNURoot in Action–Install and Run wkhtmltopdf | RubyPDF](http://blog.rubypdf.com/2015/11/06/gnuroot-in-action-install-and-run-wkhtmltopdf/)

**Comment by odony** [comment]
@DavidGoodenough we simply use the official static builds from the upstream project: 
         https://wkhtmltopdf.org/downloads.html
You might want to get in touch with @ashkulz at https://github.com/wkhtmltopdf/wkhtmltopdf and see if you can manage to build it for the cubieboard. Not sure we'd be of much help here ;-)
