### ISSUE TITLE
no gantt chart forecast odoo9

### ISSUE THREAD

**Issue by bbyambasuren** [odoo/odoo#10243]
![forecast](https://cloud.githubusercontent.com/assets/12806798/12060581/033d40c6-afae-11e5-84b9-d62c0240970d.png)

**Comment by bbyambasuren** [comment]
please help me

**Comment by eneldoserrata** [comment]
gantt view only available on enterprise edition

**Comment by bbyambasuren** [comment]
ok thank you

**Comment by Yenthe666** [comment]
As @eneldoserrata has pointed out, this is only for the Enterprise version.
Closing this issue since it has been answered.
