### ISSUE TITLE
[Purchase]: UI - Issue -  Terms and Conditions in Purchase Order is not proper.

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#102628]
Impacted versions: 16.0

Steps to reproduce: 
1. Open the purchase module.
2. Create Requests for Quotation.
3. Check terms & conditions.

Current behavior: The details are not showing properly.

Expected behavior: Details should be displayed properly for terms & condition.

Video/Screenshot link (optional):
![Purchase_order_Scrollbar](https://user-images.githubusercontent.com/32053757/194552129-0adf17d2-448e-4cb4-86c4-759e18ad3bcb.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
seems already fixed

**Comment by niyasraphy** [comment]
@kup-odoo @odooaktiv this can be closed

**Comment by kup-odoo** [comment]
Thank You @odooaktiv
