### ISSUE TITLE
[9.0]hr_attendance: worked_hours are not recomputed when sign-in or sign-out times are changed

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#10265]
It is possible to change sign-in and sign-out times in the hr_attendance module. However, after such changes the original worked_hours remain the same and are not recalculated.
Observed in Version 9.0c-20151228.

**Comment by invitu** [comment]
in hr_attendance/hr_attendance.py line 33
add
@api.depends('name')
before the function definition
def _worked_hours_compute(self, cr, uid, ids, fieldnames, args, context=None):
and test again
if it works, you could provide a fix to Odoo SA

**Comment by treviser** [comment]
Thanks very much for your help, unfortunately I'm not a developer and I do not know how to test and provide such a fix.

**Comment by invitu** [comment]
ok, I do it for you

**Comment by treviser** [comment]
Thank you, that's really kind.

**Comment by rmu-odoo** [comment]
Hello,

@api.depends('employee_id', 'name', 'action')
    def _worked_hours_compute(self):
        for attend in self:
            if attend.action == 'sign_in':
                attend.worked_hours = 0
            elif attend.action == 'sign_out':
                last_signin = self.search([
                    ('employee_id', '=', attend.employee_id.id),
                    ('name', '<', attend.name), ('action', '=', 'sign_in')],
                    limit=1, order='name DESC')
                if last_signin:
                    # Compute time elapsed between sign-in and sign-out
                    workedhours_datetime = (fields.Datetime.from_string(attend.name) - fields.Datetime.from_string(last_signin.name))
                    attend.worked_hours = ((workedhours_datetime.seconds) / 60) / 60.0
                else:
                    attend.worked_hours = False

hope. this will work

thanks

**Comment by invitu** [comment]
@rmu-odoo Finally, it is more complicated because it has to be translated to new api

**Comment by treviser** [comment]
Any news on this issue?

**Comment by treviser** [comment]
@Yenthe666 Could you have a look at this?

**Comment by Yenthe666** [comment]
@treviser sure thing, I'll have a look at this on monday. Think you could make a little example video please? That would make it easier for me.

**Comment by pedrobaeza** [comment]
This has been fixed in v10 and later versions with the switch to the new API and `@api.depends` declaration (in this version is still in old API):

https://github.com/odoo/odoo/blob/eb84a309992cb6545180294ab51f51d7eefbafc3/addons/hr_attendance/models/hr_attendance.py#L42

So if you are still in this version and have an enterprise contract, you can submit an OPW for solving the problem in this version that is in its end of life cycle. I close this as considered solved in latest versions.
