### ISSUE TITLE
[8.0] Listbox fill problem, RPC read not called

### ISSUE THREAD

**Issue by thomaspaulb** [odoo/odoo#10273]
I am on the newest 8.0 branch, commit a40d48378d22309e53e6d38000d543de1d2f7a78.
I am on newest version of Chrome under Windows.

When I go to Financial / Taxes / Fiscal Position I see two listboxes containing my tax and journal translations. (But I also see this problem when I open a product and then under second tab look at Suppliers. Same listbox, same problem.)

What happens is that I browse through my form view, seeing records. Some records have the listbox filled, some records do not. (eg. in the case of fiscal positions the first one is generally "Inland" and it has no tax translations, second and third one are "EU" and "Non EU" and contains some translations). When I refresh the page (F5) at a filled record, the entries show correctly. Browsing back and forth to another record that has entries in the listbox also works. But when I browse to a record that has NO listbox entries, and then I browse back, I get an empty list on all subsequently opened records.

I looked in the browser Network tab and the search_read RPC call gets the same response:

```
{"jsonrpc": "2.0", "id": 897486020, "result": [{"country_group_id": false, "display_name": "BTW verlegd", "name": "BTW verlegd", "sequence": 0, "country_id": false, "company_id": [1, "My Company"], "auto_apply": false, "note": false, "account_ids": [], "vat_required": false, "active": true, "id": 2, "tax_ids": [1]}]}
```

but is not followed by a read RPC call anymore.

**Comment by Yenthe666** [comment]
Hi @thomaspaulb ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
