### ISSUE TITLE
[9.0] Reconfirm Cancelled Delivery Order

### ISSUE THREAD

**Issue by uynil** [odoo/odoo#10277]
Impacted versions:
 - 9.0

Following these steps:
1. Create a sale order with an stockable product.
2. Confirm the sale order.
3. Cancel sale order.
4. Reconfirm sale order.

Expected behaviour: delivery order (related procurement order) should be confirmed again.

Obtained behaviour: delivery order is still cancelled.

**Comment by uynil** [comment]
@odony 
Hi, There is no feedback on this issue, who should I contact with for this?

**Comment by odony** [comment]
@jco-odoo @nim-odoo Could you have a look, seems to be a valid issue (I can reproduce it). We should possibly reset the picking/proc state or create new ones? Thanks!

**Comment by nim-odoo** [comment]
I'm gonna have a look at it. However, it is probably more logical to create new procurements. Indeed, when a SO is in state 'draft', no procurement is supposed to be linked to it.

**Comment by jco-odoo** [comment]
A move/picking never goes from cancelled to confirmed normally.  New
procurements seem logical to me too.

**Comment by odony** [comment]
@nim-odoo @jco-odoo Thanks!

**Comment by uynil** [comment]
@nim-odoo @jco-odoo @odony Thanks!
