### ISSUE TITLE
[15.0] Rounding incoherence between SO and created invoice taxes

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#102838]
Impacted versions: 15.0

Steps to reproduce:
1. Create 2 taxes like this:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/7678583/194838381-a049585a-661a-4553-9ddc-f336964ee290.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/7678583/194838439-f76f0e94-2583-48e7-9e98-b9c9e0cc577d.png">

So exactly the same, just labels that are different

2. Configure company rounding methot to "Round globally" 
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/7678583/194838630-3a597bb0-6540-4229-9993-ba64d577687c.png">

3. Change the product accuracy of "product price" to 5 digits

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/7678583/194841092-e2c6d9c6-e1a8-49a8-a223-95cd57e73032.png">

4. Create a SO with these unit price and quantities
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/7678583/194838839-b207d4d8-d82b-4b5d-b16d-64aa0978002e.png">

5. You'll see taxes amout to 63.00
6. Create your invoice from SO and you'll get tax price to 63.01
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/7678583/194839066-60abdeb2-c876-4d10-a701-27cabf7c420d.png">

Current behavior:
Tax amount is different on SO and invoice

Expected behavior:
Tax amount should be the same on invoice than on SO

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
opw-3012904

**Comment by manishkumarbohra** [comment]
Hello @jlaloux , 

Kindly pull the code. For now I'm unable to recreate the same issue.

![screenshot-localhost_8015-2022 11 16-18_05_54](https://user-images.githubusercontent.com/72200254/202182393-082ee635-66eb-4030-acb1-b970c963b2f4.png)
![screenshot-localhost_8015-2022 11 16-18_06_20](https://user-images.githubusercontent.com/72200254/202182402-29f813b9-5c21-4e34-8da8-d8ea1f422d83.png)

@Yenthe666 can we close this issue?

**Comment by Yenthe666** [comment]
@jlaloux are you sure you are on the latest code? From when is your source? :)

**Comment by vava-odoo** [comment]
Linked ticket is closed
