### ISSUE TITLE
[9.0][Update] Cannot save line in sales order due to missing product due to upgrade of sale_crm, sale_service, sale_timesheet, portal_sale or project_timesheet 

### ISSUE THREAD

**Issue by tehXor** [odoo/odoo#10289]
The "Product" column in this form sale.order.form is missing and as it is required I cannot save sale orders. The header from where you can send the order sales as emails for example also went missing.

I found out that this happens after triggering an upgrade from the "Upgrade" button of the sale App. I installed the DB in question on the first 9.0 which was released for docker and am now running into this problem after upgrading my container to the 9.0c-20151215. Upgrading any other Apps does work. 

I know that the /sale/ addon itself is not responsible as I tried to replace it alone. What "fixes" the problem is to use the complete 20151215 codebase but overwrite the addons /sale_crm/, /sale_service/, /sale_timesheet/, /portal_sale/ and /project_timesheet/ with their code from v9-20151008. Hitting "Upgrade" on the Sale App after that brings back the product column and the header bar.

It would be great if there was a real fix though and we could upgrade to newer versions of these apps in future.

This problem also only seems to take effect on upgrades. Creating new databases with the 20151215 codebase works as it should.
Thanks for looking into it.

**Comment by tehXor** [comment]
Update/Bump: This problem seems to only be related to DB upgrades and has something to do with *sale_crm*, *sale_service*, *sale_timesheet*, *portal_sale* and *project_timesheet*

**Comment by shams3049** [comment]
I am facing the same issue, and I was wondering How did you resolve the issue?!

**Comment by tehXor** [comment]
I'm sorry to have to say that we never really resolved it :(

While experimenting with 9.0 we discovered pretty soon that it was (and most sure still is) a rip-off of what 8.0 and previous versions once where. See for example this issue https://github.com/odoo/odoo/issues/10384 and besides `account_analytic_analysis` there are other modules which got - allow me the word - _brutally_ ripped out of the code in favor of new enterpries modules of the  Odoo S.A.. You can follow this practice quite good if you look at the differences between git branches.

I just write you this as I would honestly suggest you to move back to 8.0 if you still can and haven't invested too much in 9.0. That was what we did and therefore the issue wasn't relevant for us anymore. But beware, it is not to expect that 8.0 will be supported well by the Odoo S.A. in future (just have a look at the current state of the code and issues...). So you should only consider this if you are content with the current 8.0 feature set and have the technical knowledge to fix stuff yourself (and maybe even private forke it - that's also what we did).
Obviously you also could think about sticking with 9.0 and investing money in the enterprise version but considering the prices I again would advise against it as you will find much better ERP solutions, which are also provided as SaaS if you prefer this, if you are willing to pay that much.

Maybe this still was somewhat helpful for you also it doesn't really answer your question.

Best regards.
