### ISSUE TITLE
Improvement the invoice in Point of Sale (backend)

### ISSUE THREAD

**Issue by JMODaERP** [odoo/odoo#10292]
Ticket and Invoice in Point of Sale.

To improve the presentation and the understanding of an invoice, in addition to expire with the in force regulation.

Followed steps

Purchasing:

![2016-01-05 07_59_01-compra](https://cloud.githubusercontent.com/assets/15608043/12110302/37f136ac-b38b-11e5-9b03-34af3b99e69f.jpg)

The Ticket

![2016-01-05 08_01_26-ticket](https://cloud.githubusercontent.com/assets/15608043/12110404/2a4ad426-b38c-11e5-8732-7d43daace5f3.jpg)
Invoice.

![2016-01-05 08_03_24-orders - odoo-invoice](https://cloud.githubusercontent.com/assets/15608043/12110327/755d17ae-b38b-11e5-9286-0eadad6733e4.jpg)

![2016-01-05 08_09_33-orders - odoo-reprint](https://cloud.githubusercontent.com/assets/15608043/12110335/84255c38-b38b-11e5-82fa-b39281224b99.jpg)

Current behavior.

In the current invoice the discount appears as an amount and is accompanied of the symbol of the currency. Nevertheless the discount is a percentage. Since we can see in the visual one.

![2016-01-05 08_10_16-point_of_sale report_receipt-1 pdf - adobe acrobat reader dc-reedited](https://cloud.githubusercontent.com/assets/15608043/12110341/8c8bbda4-b38b-11e5-9996-ead575054d24.jpg)

Expected behavior.

The improvement consists of changing the symbol of the currency into the symbol of the percentage since(as,like) the ticket goes.

![2016-01-05 08_22_25-deberia](https://cloud.githubusercontent.com/assets/15608043/12110342/92ac0e46-b38b-11e5-8060-09277d9de7aa.jpg)

Thank you for addresing my request

**Comment by jorenvo** [comment]
Fixed in a54802bad5c07d7fa108e9ee22e41923585dcbca.
