### ISSUE TITLE
[9.0] There is no way to cancel employee expenses once it is in "Waiting Payment" state

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#10296]
### Impacted versions:
- 9.0
### Steps to reproduce:

Create an expense and process the expense until the state is `Waiting Payment` (the state becomes `Waiting Payment` after you press `Post Journal Entries` button
### Current behavior:

There is no way to cancel the expense.
### Expected behavior:

There should be some means so that the user can correct the document if necessary.  e.g. show "Refuse" button which triggers deletion of the associated journal entry and cancellation of the expense.

**Comment by AWDGroup** [comment]
+1

**Comment by gonzaloruzafa** [comment]
+1

**Comment by relshire** [comment]
+1

**Comment by bst-odoo** [comment]
Thx for the feedback.
It cannot be qualified as a bug but we will take it into acocunt for a future R&D task.
