### ISSUE TITLE
[9.0] acute and some bad strong tag translation causing conflicts

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#10299]
Hi!
- first, on sale/i18n/es.po and es_DO.po, line:
``` po
 msgstr "<stong>Comercial:</strong>"
```
must be :
``` po
 msgstr "<strong>Comercial:</strong>"
```
- There are a lot of terms on spanish language with &..acute; that was causing  issues i.e  when you want print a invoice , gets: 
``` xml
QWebException: Entity 'oacute' not defined,
```
I'm try fixing on transifex.

**Comment by eneldoserrata** [comment]
I all ready fix all; pull the last commit and if translation not ready merge to github you can pull direct from transfix using the transfix api -> tx pull -r "odoo-9.*" -l es_DO --mode reviewed

https://github.com/odoo/odoo/wiki/Translations

"<strong>Comercial:</strong>" for es_DO is "<strong>Vendedor:</strong>"

**Comment by sebastian-code** [comment]
Does this also works for es_CO and the es base?

**Comment by dansanti** [comment]
Fixed on https://github.com/odoo/odoo/commit/2efa359e41b5d0953127fb60f28784a5398b35ff
