### ISSUE TITLE
"No rule matching this procurement"

### ISSUE THREAD

**Issue by Ayhamhafez** [odoo/odoo#10294]
After creating procurement rule and define the minimum stock, after making compute stock minimum and run the scheduler I got the right procurement but when make run procurement, no PO automatically created and I got log that say "No rule matching this procurement"

I think it's a bug since it was work before couple of months.

**Comment by lap-odoo** [comment]
@Ayhamhafez I cannot reproduce your issue. We would need more detailed steps to be able to help you. I'm closing your issue. If you can provide detailed steps to reproduce your issue I'll reopen. Thanks for your understanding.
