### ISSUE TITLE
[8] noupdate="1" not taken into account

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#10293]
Hi !

Yesterday, I updated a module A, which then triggered the update a module B. This B module have a data file with noupdate="1" at the top of it. However, the server did not take it into account and erased data that were in the database. Hours wasted restoring the database.

Any clue what might causing it ?

**Comment by yannprada** [comment]
@xmo-odoo Is that the way it should work ? I'm very afraid of putting data in modules now, as it might srew up a database in the future...

**Comment by fjouatte** [comment]
No answer from the odoo team ? I experienced the same kind of problem, any explanation would be appreciated

**Comment by yannprada** [comment]
@fjouatte Nice to hear I'm not alone in this. I've been paranoid with data since that happened :-/

**Comment by yannprada** [comment]
@xmo-odoo 
Test on Version: 8.0-20160308
With `<data noupdate="1">` and `forcecreate="0"`
Records deleted were created again
Modifications were reverted

**Comment by yannprada** [comment]
Oops miss click (close)

**Comment by yannprada** [comment]
@xmo-odoo 
I did a test today, on version 8.0-20160308.
*sample:*
```
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data noupdate="1">

        <record id="my_record_id" model="some.model" forcecreate="0">
            <field name="name">Foo</field>
        </record>

    </data>
</openerp>
```
I deleted a record, modified another. I then restarted the server, updating the module where this sample of code is. The deleted record was back, the modified one was reverted back to original.

Any explanation ?

**Comment by yannprada** [comment]
Just tested on latest version (8.0-20160318), with the same issue

**Comment by xmo-odoo** [comment]
@yannprada that seems very odd, would it be possible to have a reproduction case module, and a listing of the exact commands you're performing?

Also please check that you do not have an `init` key in a configuration file somewhere (that's not supposed to happen, or to do anything, but …)

**Comment by yannprada** [comment]
@xmo-odoo Ok, now I can't reproduce it at all.

**Comment by odony** [comment]
@yannprada thanks for the feedback, we'll close this issue for now then :-)

**Comment by pedrovagner** [comment]
Initializing *Odoo* with the command `odoo --init my_module --update my_module` causes `my_module` to be installed if it's not already installed. If I use the same command, the database records are updated even with `noupdate="1"`.

Initializing *Odoo* with `odoo --update my_module` database records aren't updated. But what command line I need to pass to automatically install a module (if it's not installed previously) and don't updated database records? I'm facing a scenario where where the command line can't be changed (Docker).
