### ISSUE TITLE
stage move Functionality on Project Module (kanban view) is not working on Odoo16

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#103194]
Impacted versions:
Odoo V16

Steps to reproduce:
Go to Project Module 

Current behavior:
Stage move functional on kanban view (Project View) for stages sequence is not working

Expected behavior:
stage move functional on kanban view for stages sequence should work
Video/Screenshot link (optional):
![2022-10-13_21-10](https://user-images.githubusercontent.com/22232100/195649365-9dd24835-0534-410c-a029-fb391ff369af.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @usmanfarzandali ,

Thanks for your feedback, I think now the issue has been fixed. 🙂 🤔
