### ISSUE TITLE
account_reconciliation_widgets.js not read custom res.partner record rule if partner_id in account_bank_statement_line is empty

### ISSUE THREAD

**Issue by bimajatiwijaya** [odoo/odoo#10316]
my record rule for res.partner running well but not in account_reconciliation_widgets.js

if do tranfer in account_bank_statement and one of account_bank_statement_line have partner_id empty
show error (can't read res.partner)

i supposed the js return partner with 3 domain because static.

1730 domain: [['parent_id','=',false], '|', ['customer','=',true], ['supplier','=',true]],
and account.move.line 

for now we replace the js and change domain with context from method in py file.

**Comment by pedrobaeza** [comment]
Is this still reproducible in latest code? If so, please specify all the needed steps (create the rule with this value, go to this place, etc) for being able to reproduce the problem.

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
