### ISSUE TITLE
[9.0] Calendar Event Form Attendee Bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#10319]
Hello Odoo,

Today I updated the latest code from Odoo,
and after that when I look on calendar form,
there's no name show on the attendee field.

![ttatt](https://cloud.githubusercontent.com/assets/7590534/12135935/7ebdd426-b47d-11e5-98b5-5076c318feee.JPG)

This behavior happen on runbot too, you can check it.

**Comment by msh-odoo** [comment]
@falinwa Should be fix here: https://github.com/odoo/odoo/pull/10261
