### ISSUE TITLE
[16] Sell subscription plans at shop

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#103176]
Impacted versions: 16

anyway to sell subscription plans at shop ?

**Comment by Feyensv** [comment]
@Williambraecky @pierre-pde what's the news about website & subscription ?

**Comment by esakarya** [comment]
With 16, subscriptions have become more capable. but the subscription plans created must be able to be ordered by the customer on its website.

**Comment by Williambraecky** [comment]
@pierre-pde @dalaOdoo this is for you :)

**Comment by esakarya** [comment]
C'mon guys :) its important. cant sell subscription plans on website:) 
also if you try selling recurring product on website. website cant place order during place order its ge this error 
"You cannot save a sale order with recurring product and no recurrence." 
SO have to select recurrance period.

**Comment by dalaOdoo** [comment]
Hello @esakarya, do you have the module "website_sale_subscription" installed on your database ?

**Comment by esakarya** [comment]
yes its installed. but i cant see my created plans in shop. and plan doesnt has a settings publish or un publish on website.

**Comment by esakarya** [comment]
i checked with latest update. subscription product can be sell now. what about plans ?

**Comment by esakarya** [comment]
I just want. sell plan, approve sales order and create invoice when payment received. 
Subscription Plans support auto invoicing.

**Comment by dalaOdoo** [comment]
With Odoo 16, if you sell a recurring products through the e-commerce & if that product has at least one "Time-based price" defined (a price for a period), then it will lead to the creation of a recurring Sale order = a subscription. 
It means that you need to define at least one price rule for this product in the Price tab of the form view.
If a product has several rules, for example a price per month and a price per year. The e-commerce will only consider the smallest period, in this case, the monthly period.
  
FYI It is only possible for now to sell simple subscriptions through ecommerce, not yet "Subscription plan" (including several products, a specific period, ...)
This video may help you to understand changes in Odoo 16 :  https://www.youtube.com/watch?v=l6NB82U4TlA

**Comment by esakarya** [comment]
Ok bro thank for your interesting. 
Product price is yearly. checked also prices tab price is only one item its yearly. but still period doesnt select automatically. 

this is product
![image](https://user-images.githubusercontent.com/61056242/196401818-0204c217-0b37-4464-a9e2-945a32438878.png)

this is sale order

![image](https://user-images.githubusercontent.com/61056242/196402072-c99907a8-bce9-4323-9369-b0cac13687dc.png)

can u see ? so has only one line, one recurring product yearly.
product prices tab set only one period is yearly. still so main recurring period are empty.

**Comment by dalaOdoo** [comment]
Is the pricelist on the SO equal to the pricelist of the recurring price (Genel Fiyat Listesi TRY) ?

**Comment by esakarya** [comment]
after equal its select period. thank you boss!!! i am waiting selling plans.
