### ISSUE TITLE
odoo 16.0 error installing requirement packages

### ISSUE THREAD

**Issue by maherkhalil07** [odoo/odoo#103164]
Impacted versions: 16.0

Steps to reproduce: install package in ubutnu 22.0 LTS

Current behavior:Failed to build gevent python-ldap Modules/common.h:9:10: fatal error: Python.h: No such file or directory

Expected behavior:no error

Video/Screenshot link [(optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
--> https://stackoverflow.com/a/21530768
You need to properly install python dev libraries.
