### ISSUE TITLE
[16.0] E-commerce multi-warehouse problem

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#103219]
Impacted versions: 16.0

We have multiple warehouses. 
If no warehouseis selected in the website settings, and the Out-of-Stock setting is not checked as Continue Selling. 
Products are displayed as out of stock.

If the warehouse is selected, it can be added to the cart.

**The website should be able to work with more than one warehouse.**

**Comment by esakarya** [comment]
any solution ?

**Comment by pierre-pde** [comment]
Hi, are you sure this is related to 16.0? 
I could reproduce this in 15.0
Video; https://bit.ly/3EiYHFB

**Comment by esakarya** [comment]
Please add one more warehouse. and try again. if you have one warehouse there is no problem. but we are working multi warehouse.

**Comment by pierre-pde** [comment]
Hi @esakarya , we don't need to put a M2M field. 
A M2O is enough. 
If you need stock from multiple warehouse, I think you can create virtual ones.

**Comment by esakarya** [comment]
virtual one ? i hear first time can u tel me how ?
