### ISSUE TITLE
[15.0] Order lines with optional products from the configurator disappear

### ISSUE THREAD

**Issue by Robrechtc** [odoo/odoo#103262]
Impacted versions: 15.0

Steps to reproduce:

1. Create a new sale order
2. Add an order line with a configurable product
3. In the configurator, add an optional product to the cart
4. Confirm the configurator
5. Click on the description of the order line for the optional product
6. Click something else (not the order line you just clicked)

Current behavior:

The order line disappears

Expected behavior:

The order line doesn't disappear

Video/Screenshot link (optional): https://youtu.be/q2ZZIchKGgk 

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
This issue is solved since 16.0, but won't be in 15.0 because it requires too many changes in the JS Framework
