### ISSUE TITLE
[8.0] BUG in product csv export

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#10327]
Hello,

I noticed a V8.0 regarding the csv export of a product.

# Way to Reproduce

Select Product IPad Mini.
Set a price on the product supplier info.

![print_1](https://cloud.githubusercontent.com/assets/7813258/12142761/f486ddf4-b47a-11e5-97ef-f3254ca6e874.jpg)

Select Product on Tree view, More Options, Export and select columns Supplier/Supplier Pricelist

![print_2](https://cloud.githubusercontent.com/assets/7813258/12142850/880d0832-b47b-11e5-8e84-8f5a6425b16a.jpg)

Save fields export as Test.

![print_3](https://cloud.githubusercontent.com/assets/7813258/12142862/a74e0de0-b47b-11e5-82f9-25032d0cdd78.jpg)

Export File
The header of the file exported is **id,seller_ids/pricelist_ids/id**

Close the export window and reopen it.

Use the Save fields List **Test**

![print_4](https://cloud.githubusercontent.com/assets/7813258/12142903/12c9c460-b47c-11e5-9c9d-9e58079afdb4.jpg)

Export the file.

The header of the file exported is **id,seller_ids/pricelist_ids** which is wrong.
All values for column seller_ids/pricelist_ids are False.

**Comment by nle-odoo** [comment]
Hello,


It should be solved with https://github.com/odoo/odoo/commit/29be9ae

Thanks for reporting :smile:

**Comment by Cedric-Pigeon** [comment]
@nfl-odoo Tested and it worked, Thanks for the fix
