### ISSUE TITLE
[16.0] Scrap Order Creation Error

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103236]
Impacted versions: 16.0

Steps to reproduce: Disable Manage Multiple Units of Measure from the settings or remove users from this user group and try creating a scrap order.

Current behavior: Error will be raised

Expected behavior: Scrap Order has to be created

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![Screenshot from 2022-10-16 14-28-10](https://user-images.githubusercontent.com/27989791/196032883-20891f4d-8525-4ebe-b7b4-cc49e5ef46ab.png)

**Comment by niyasraphy** [comment]
Fix:  a168e16eef9e0487edf3fec47a0c7f54cd332272

**Comment by niyasraphy** [comment]
PR to fix: 103228

**Comment by niyasraphy** [comment]
FIX: a168e16eef9e0487edf3fec47a0c7f54cd332272

**Comment by niyasraphy** [comment]
FIX: ba72882574eedda72b9a4747075674c22b80042c

**Comment by niyasraphy** [comment]
FIX:  ba72882574eedda72b9a4747075674c22b80042c

**Comment by Feyensv** [comment]
@odoo/rd-logistics

**Comment by amoyaux** [comment]
Thanks for reporting we already have a fix ongoing

**Comment by niyasraphy** [comment]
@amoyaux that means this PR wont going to get merged ?  https://github.com/odoo/odoo/pull/103238

**Comment by ticodoo** [comment]
fixed with https://github.com/odoo/odoo/pull/104806
