### ISSUE TITLE
[8.0] Bug: Delivery costs not showing up on sale.order.line

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#10328]
What I mean by cost is the cost for the company. The price for the customer works as expected.

**Steps to reproduce**
- Open runbot
- Make sure the delivery grid lines have a cost value
- Create a sale order
- Add some products
- Add a delivery line, using the button provided at the bottom
- (Press update if needed)

**Current behavior**
At the delivery sale.order.line, the value of the field Cost is 0

**Expected behavior**
At the delivery sale.order.line, the value of the field Cost reflect the cost provided by the delivery.grid.line

**Comment by spadae22** [comment]
If you add a delivery line, it will not add another. I assume you defined Delivery Method correctly. The delivery costs will appear on the the invoice, not the sales order. We use this 150 to 200 orders per day.

<img width="364" alt="screen shot 2016-01-21 at 12 12 15 am" src="https://cloud.githubusercontent.com/assets/7741100/12472209/b0d94d3a-bfd3-11e5-82c2-548ade63c9b7.png">

**Comment by yannprada** [comment]
I only see the customer price (unit price) here in your invoice line, not the cost for the company.

**Comment by Yenthe666** [comment]
Hi @yannprada ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
