### ISSUE TITLE
bug for translate attribute values on odoo V8

### ISSUE THREAD

**Issue by nono6677** [odoo/odoo#10320]
Hi,

It's impossible to create an other translation for the attribute values, it's not save.
After multiple research, i found a solution but, it's not normal.

For create a new translation, i need to change the existing by my language (English to french) and when i refresh, i have 2 translations : the original and my language (english AND french) . It's funny .

Can you fix it or explain me the functioning.

Ps : i have tested on runbot V8

**Comment by flotho** [comment]
Hi @nono6677 , we are also affected with this on v8.

regards

**Comment by slerendu** [comment]
Hello guys,
It also affect the v9

**Comment by nono6677** [comment]
Thank you everybody
i also tested in other object like product.templane,name and the result is the same.
Why my translation is not save ?
I need to proced differently ?

**Comment by nono6677** [comment]
Process :
I create a new translation like this
![image](https://cloud.githubusercontent.com/assets/9798171/12289397/8c45e3c8-b9db-11e5-914f-dfdb393b4c35.png)

when i save it, my source becomes empty (is it normal?)
![image](https://cloud.githubusercontent.com/assets/9798171/12289424/c05f64cc-b9db-11e5-883c-c25bc2e184f1.png)

finally, i refresh the view and my translation disappears
![image](https://cloud.githubusercontent.com/assets/9798171/12289466/fe95e5e0-b9db-11e5-833c-68ba8ad9d363.png)

It's a bug, no ??

**Comment by nono6677** [comment]
hi, nobody has an anwser ?

**Comment by mart-e** [comment]
Hello,

It is because you don't have all the required field, you need also to specify the ID of the record (it's not displayed in the list view but it is in the form view).
