### ISSUE TITLE
HTTPSConnectionPool(host='id.eta.gov.eg', port=443): Max retries exceeded with url: /connect/token (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

### ISSUE THREAD

**Issue by codebuildhub** [odoo/odoo#103218]
Impacted versions: 15 Community

Steps to reproduce: 
Using Egypt E-Invoice Integration
we have configured all pre-requsites as odoo documentation 

Current behavior:
After signing the Invoice we got this stuck error,

HTTPSConnectionPool(host='id.eta.gov.eg', port=443): Max retries exceeded with url: /connect/token (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

Note : the error caused by odoo not from E-Tax API as we tested using post man and its working
Expected behavior:

Also Note when we run that command from the server 
curl https://api.invoicing.eta.gov.eg/
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

![5](https://user-images.githubusercontent.com/46281104/195886211-835f675f-d7df-4992-ac9c-5704e2012a85.png)
![3](https://user-images.githubusercontent.com/46281104/195886218-794c3de9-9221-4ca1-8c32-a7eebf3ebe65.png)
![4](https://user-images.githubusercontent.com/46281104/195886220-bf6488e7-0d06-42c9-af82-3ec73f417010.png)
![2](https://user-images.githubusercontent.com/46281104/195886224-b7ebd767-9d03-480c-afc3-79484050cad3.png)
![1](https://user-images.githubusercontent.com/46281104/195886227-8cc62944-0e6c-4f82-98e6-9877bff673ca.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by codebuildhub** [comment]
Solved With ETA

**Comment by victor4pro** [comment]
@codebuildhub Hi, how do you solved this issue? I having the same issue in Chile invoice integration.

**Comment by codebuildhub** [comment]
> @codebuildhub Hi, how do you solved this issue? I having the same issue in Chile invoice integration.

Its due to server issue, our administrator has solved the problem , you can redirect to info@kitsolutions.org for more information
