### ISSUE TITLE
[15.0][project] break compatibility with TRUE_DOMAIN expression

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#103214]
These changes break compatibility with the use of expressions
TRUE_DOMAIN = (1, '=', 1)
FALSE_DOMAIN = (0, '=', 1)
because try to split a number:
https://github.com/odoo/odoo/blob/6aead37617657391b01af3191f67fcfa2d645d4d/addons/project/models/project.py#L1642

@Tecnativa

**Comment by pedrobaeza** [comment]
@tivisse maybe when you recover from this intense week, you can check this one. We can propose the bugfixing PR if you prefer. The technique would be to check first if the operand is an string before trying to obtain the field name.

**Comment by tivisse** [comment]
Indeed, thank for the feedback @carlosdauden 

@xavierbol is gonna handle the fix :)

Have a nice day :)
