### ISSUE TITLE
HOW TO CHANGE A MENUITEM POSITION?

### ISSUE THREAD

**Issue by GabrielBatista191** [odoo/odoo#103332]
Impacted versions: Odoo v14

Hey! I'm trying to change the position of the menuitem in my module but I can't.
I need this menu item patrimony, to be between vendors and reports.
![image](https://user-images.githubusercontent.com/71337084/196265596-3b4a050f-a998-4d70-8d3f-f97cb13616bb.png)

putting the sequence in the code, I can't, by the technician either.

**Comment by niyasraphy** [comment]
Hi @GabrielBatista191 is this a custom menu or activated the translation ?
Did you tried updating the sequence value for patrimony menu sequence value in between customers & vendors sequence values ?

**Comment by vava-odoo** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
