### ISSUE TITLE
Debug/Developer mode won't activate

### ISSUE THREAD

**Issue by itaine** [odoo/odoo#10336]
Debug/Developer mode won't activate in the latest Version 9.0c-20160106. When activated it just stalls. Resumes when ?debug=# is removed from the URL.

**Comment by Yenthe666** [comment]
@itaine just tested on runbot.odoo.com and seems to work for all runbots from the last day? Can you double check again?

**Comment by itaine** [comment]
Must of been a glitch in the matrix. It works :-)
