### ISSUE TITLE
[16.0]  Keep unexpected index for different models in Logs

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103473]
Impacted versions: 16.0 CE and EE

Steps to reproduce: Install sales and purchase or any modules that inherits the analytic.mixin and see the log file

Current behavior: Showing keep unexpected index messages in log
2022-10-19 07:48:25,334 19619 INFO 16_19ee odoo.schema: Keep unexpected index sale_order_line_analytic_distribution_index on table sale_order_line 
2022-10-19 07:48:25,334 19619 INFO 16_19ee odoo.schema: Keep unexpected index purchase_order_line_analytic_distribution_index on table purchase_order_line 

Expected behavior: Clean log

Video/Screenshot link (optional):

![Screenshot from 2022-10-19 10-51-33](https://user-images.githubusercontent.com/27989791/196629915-df5ba6bf-dc5c-4269-824d-d79042787c63.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
By adding index True for the field seems to be working as init query creates the index for the fields.
Created a PR with the same:  https://github.com/odoo/odoo/pull/103475

**Comment by william-andre** [comment]
https://github.com/odoo/odoo/pull/103748
