### ISSUE TITLE
[16.0] stock: Stock Package Type button box

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#103420]
@amoyaux Do you think it's reasonnable to do a PR introducing a button box (a void one) for stock.package.type form view (and get merged in 16.0) ?

If not, I'll do a small OCA module for that.

https://github.com/odoo/odoo/blob/16.0/addons/stock/views/stock_package_type_view.xml#L10

**Comment by rousseldenis** [comment]
https://github.com/OCA/stock-logistics-warehouse/pull/1509

**Comment by amoyaux** [comment]
@rousseldenis since it's only the start of 16.0 it wouldn't be too risky. Try to do it fast if possible
