### ISSUE TITLE
[v9] Mass Mailing: Unable to view filter

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#10359]
Hi

Using my "regular" user, which is Manager in mass mailing I go to segments for a campaign, then I click on the filter and I get an access error, I can not read ir.filter.

Surely the manager must have the right to view the filter?

**Comment by Yenthe666** [comment]
Hi @bringsvor,

Thanks a lot for the report.
This issue has been fixed in the meanwhile so please update your Odoo source code in order to fix this locally.

Regards,
Yenthe
