### ISSUE TITLE
Journal Entry view filed alignment is not proper.

### ISSUE THREAD

**Issue by konsultoo-nimesh** [odoo/odoo#103528]
Impacted versions:
16.0
Steps to reproduce:
Go To Journal entry and hit create or open any existing journal entry

Current behavior:
Field alignment for date and journal is not proper. 

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/80413921/196696621-69b8b199-3bd1-417a-bd58-a6e6841a9217.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by konsultoo-nimesh** [comment]
![image](https://user-images.githubusercontent.com/80413921/196696855-3fb0c01b-4dce-4dac-abae-52702302b1ef.png)

Alignment for reference field is also not good

**Comment by niyasraphy** [comment]
@konsultoo-nimesh currently it seems fine in runbot and may be already fixed it. Can you confirm the same

**Comment by Yenthe666** [comment]
Yep, looks fied in the meanwhile :)
