### ISSUE TITLE
[16][pos] error opening the pos from pc browser

### ISSUE THREAD

**Issue by LuigiFerranteBW** [odoo/odoo#103524]
Impacted versions: 16 EE
Installed on: odoo.sh
Version app: 16.0.1.0.1

Steps to reproduce: install pos app and open it

Log error:
TypeError: this.get_taxes_after_fp is not a function
get_taxed_lst_unit_price web/assets/823-4adff6b/point_of_sale.assets.min.js:1906

Installed apps:
sales
account
website
stock
account_accountant
purchase
website_sale
hr
plannig
mail
calendar
appointment

From mobile version, works

**Comment by pedrambiria** [comment]
Hello,

Thanks for reporting this issue. It has been fixed with this commit:
https://github.com/odoo/odoo/commit/269b89ddfe9f8f6b03552ca4f5c57a889fbe9ac0

Regards,
