### ISSUE TITLE
9.0 - Task not created from SO / product 'Create a task and track hours' if qty on previous line = 0

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10354]
If you create a sales order 
with several lines, with products "service" Configured as Track Service = 'Create a task and track hours' 
and on one line, the quantity is zero
then tasks will be created for the first lines until the lines with quantity zero
and NOT created for lines AFTER the line with quantity = zero

(Same sales order, with same products, with all quantites > 0, creates a task for each product)

[bugs task creation.pdf](https://github.com/odoo/odoo/files/81447/bugs.task.creation.pdf)

**Comment by raycarnes** [comment]
Can you explain the use case for having an order line with an order quantity of 0?  Wondering if that should be prevented?

**Comment by stephaniemillet** [comment]
Hi Ray, 

It could happen in several cases, two examples : 

If you use quotation template, with 0 quantities (supposed to be filled in when you use it it a quotation), and you forget to delete a line or put a quantities
(for instance, my customer user quotation templates of decade of lines, so he can forget one)

Or if you want to add a line with no quantities, because it is going to be on time sheet, only for information...

But anyhow, it is a bug, no ?

**Comment by pedrobaeza** [comment]
This has been solved meanwhile, so I close:

![seleccion_011](https://user-images.githubusercontent.com/7165771/38645591-e27867cc-3de4-11e8-8023-85e2eec81a7c.png)
