### ISSUE TITLE
Expense date from emails

### ISSUE THREAD

**Issue by jaitjulien** [odoo/odoo#103538]
I have a question regarding the creation of expenses from emails. Would it possible to also automatically fill in the expense date, by adding it in the subject?

Thanks for your answer!

**Comment by kba-odoo** [comment]
That's for you @bouvyd :smile:

**Comment by bouvyd** [comment]
Hello

I'm not really up for it, as it would make the mail alias code either more complex (too try and extract the date from different places without messing up other parts of the parsing) or make the feature somewhat more difficult to use (we see that users don't really use the code/product prefix already, adding more complexity is pbly not ideal).

We have the OCR for date extraction (thought it is an Enterprise and credit-based feature, so not available to all indeed).

We already parse numbers in the subject (for the amount), and date formatting is a rather bigger nightmare than monetary amounts (the whole MMDDYYYY vs DDMMYYYY debate). I don't believe it will be the time saviour you might think it would be- rather the kind of feature you end up doubting too much to trust.

I don't see antyhing like that in [@OCA/hr-expense](https://github.com/OCA/hr-expense/tree/15.0) either, which doesn't mean they might not want contributions there :)

Have a good day
