### ISSUE TITLE
[16.0] Exception on clicking smart button before creating the record

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103609]
Impacted versions: 16.0 CE and EE

Steps to reproduce: Open a customer/contact form, click on any of the smart buttons in the form, before filling any details in the form. Now it will return a message with "The operation cannot be completed: Contacts require a name", then on clicking discard changes from pop up, throws exception

Current behavior: Exception is shown in UI

Expected behavior: Better way to handle the case, without showing the exception to user

![Screenshot from 2022-10-20 11-14-30](https://user-images.githubusercontent.com/27989791/196894447-f4d3b52b-9f2f-47ca-9d0b-92c78d513266.png)

![Screenshot from 2022-10-20 11-14-40](https://user-images.githubusercontent.com/27989791/196894464-e043cc64-5b78-4944-a6bb-8fe2a0b52b2e.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
@bouvyd  ?

**Comment by niyasraphy** [comment]
Fixed by: https://github.com/odoo/odoo/commit/a1ed27352f393b8fff8c4f8985e3f503a07e6e37
