### ISSUE TITLE
[16.0] Picking Operation Report Name not proper in Formation

### ISSUE THREAD

**Issue by sutharhardik** [odoo/odoo#103688]
Impacted versions: 16.0

Steps to reproduce: Print Picking Operation Report From Transfers.

Current behavior: Name field not in proper formation.
![picking_opration_current](https://user-images.githubusercontent.com/41465217/197004261-e16f4787-5586-4875-9eb4-52bff6178bea.png)

Expected behavior:
![picking_operation_expected](https://user-images.githubusercontent.com/41465217/197004047-78a7b8b3-a9d6-4426-9689-6de78b521ac7.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @sutharhardik, this issue can be closed as it fixed already
