### ISSUE TITLE
[16.0] sms: error on sending sms without content

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103717]
**Impacted versions:**
16 CE and EE

**Steps to reproduce:**

1. From Calendar menu, switch to list view
2. Select multiple meeting records
3. Click on Send SMS button in the header of the tree
4. Click Put In Queue or Send SMS without entering the message content
5. Error will be raised as the message content(body) field is required at model level

**Current behavior:**
Exception is raised without sending SMS.

The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Send SMS Wizard (sms.composer)
Field: Message (body)

**Expected behavior:**
Send SMS or add SMS to queue without exceptions.

![Screenshot from 2022-10-21 09-47-45](https://user-images.githubusercontent.com/27989791/197132088-a121d9b3-0ecb-4026-82ed-f46f9aaef95d.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
FIX: https://github.com/odoo/odoo/pull/103718

**Comment by abdounasser202** [comment]
Question: why are you sending an SMS without content ? I mean it should'nt be possible, this is why the field content is required
