### ISSUE TITLE
[16.0] rtl languages won't work in odoo 16

### ISSUE THREAD

**Issue by MohammadSafaeii** [odoo/odoo#103862]
in odoo 16, when we want use rtl languages like Arabic, when we want change preferences or editing an event system will freeze
Cause new `ir_attachment` record will add (named `web_editor.assets_wysiwyg.min.css`) and system will use the new one in rtl languages
in this css we will get circular import
`web_editor.assets_wysiwyg.min.css` import list:
```less
@import "vendor/rfs";
@import "mixins/deprecate";
@import "mixins/breakpoints";
@import "mixins/color-scheme";
@import "mixins/image";
@import "mixins/resize";
@import "mixins/visually-hidden";
@import "mixins/reset-text";
@import "mixins/text-truncate";
@import "mixins/utilities";
@import "mixins/alert";
@import "mixins/backdrop";
@import "mixins/buttons";
@import "mixins/caret";
@import "mixins/pagination";
@import "mixins/lists";
@import "mixins/list-group";
@import "mixins/forms";
@import "mixins/table-variants";
@import "mixins/border-radius";
@import "mixins/box-shadow";
@import "mixins/gradients";
@import "mixins/transition";
@import "mixins/clearfix";
@import "mixins/container";
@import "mixins/grid";
```

**Comment by Yenthe666** [comment]
Should've been fixed two days ago with https://github.com/odoo/odoo/pull/103681? 🤔

**Comment by MohammadSafaeii** [comment]
thanks

**Comment by niyasraphy** [comment]
@MohammadSafaeii you can close the ticket as the issue is already resolved.

**Comment by alawiya** [comment]
i have the same issue but i didnt understand where to fix exactly
