### ISSUE TITLE
[16.0] mrp_plm: approvals field is not properly aligned

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103861]
**Impacted versions:**
16 Enterprise

**Steps to reproduce:**

1. PLM -> Configuration -> ECO Stages
2. Open / Create a recor
3. Approvals one2many field in the view is not properly aligned

**Current behavior:**
Field is not properly aligned in the view.

**Expected behavior:**
Clean form view.

**Video/Screenshot link (optional):**

![Screenshot from 2022-10-22 11-24-52](https://user-images.githubusercontent.com/27989791/197329574-36a9f4c0-5968-4467-a66a-db7d2177aa87.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
FIX: https://github.com/odoo/enterprise/pull/33099

**Comment by Yenthe666** [comment]
Don't make bug reports if you make PR's :) Somebody will look at your PR and nobody at your issue and we again have loads of open/floating tickets.

**Comment by niyasraphy** [comment]
Okay thanks for the suggeston
