### ISSUE TITLE
Creating Invoice from Picking is not considering the unit price as per the UOM #8.0

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#10386]
Steps to reproduce
1. Creating Picking and some move lines. Change the uom of the product to different uom
2. Complete the transfer and create the Invoice.
3. The Invoice lines will create with the unit price as per the product master with out considering the UOM selected.
Note: It is noticed that if stock move is having partner_id it is working fine as expected. as per the following code.

```
    def _get_price_unit_invoice(self, cr, uid, move_line, type, context=None):
        """ Gets price unit for invoice
        @param move_line: Stock move lines
        @param type: Type of invoice
        @return: The price unit for the move line
        """
        if context is None:
            context = {}
        if type in ('in_invoice', 'in_refund'):
            return move_line.price_unit
        else:
            # If partner given, search price in its sale pricelist
            if move_line.partner_id and move_line.partner_id.property_product_pricelist:
                pricelist_obj = self.pool.get("product.pricelist")
                pricelist = move_line.partner_id.property_product_pricelist.id
                price = pricelist_obj.price_get(cr, uid, [pricelist],
                        move_line.product_id.id, move_line.product_uom_qty, move_line.partner_id.id, {
                            'uom': move_line.product_uom.id,
                            'date': move_line.date,
                            })[pricelist]
                if price:
                    return price
        return move_line.product_id.lst_price

```

but when creating stock move from picking the partner_id is not getting updated to the stock move.

**Comment by Yenthe666** [comment]
Hi @lithint,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
