### ISSUE TITLE
[16.0] project: changing state from kanban raise exception

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103851]
**Impacted versions:**
16.0 CE and EE

**Steps to reproduce:**
1. Project -> My Tasks
2. From kanban view, drag a task to different state
3. Exception is raised

**Current behavior:**
exception is shown and state wont be updated.

![Screenshot from 2022-10-22 08-32-20](https://user-images.githubusercontent.com/27989791/197322314-e73c9e0d-35a0-40cb-a3e9-0dcb4e3bddb3.png)

**Expected behavior:**
user should be able to drag and drop records from kanban.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @niyasraphy ,

Thanks for your feedback, the issue will be fixed by the following PR: #104263

The issue will be closed when the PR will be merged.

Have a nice day! 🙂

**Comment by niyasraphy** [comment]
@xavierbol thanks and closing
