### ISSUE TITLE
[HOT][v8][v9][Enterprise]No more Serial Tracking in the POS

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10389]
Hi everyone,

I tried to implement serial number tracking in POS.
I started with v9 :
* The POS is configured there : http://124427-9-0-staging-jke-91aa45.runbot9.odoo.com/web?#id=2&view_type=form&model=pos.config&menu_id=572&action=821
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12229662/31ecb2c2-b84a-11e5-8692-dbb68ad0db52.jpeg)

* The product for testing is : http://124427-9-0-staging-jke-91aa45.runbot9.odoo.com/web?#id=269&view_type=form&model=product.template&menu_id=566&action=806
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12229763/084eabb8-b84b-11e5-9c54-aa311962ddff.jpeg)

* The picking type is : http://124427-9-0-staging-jke-91aa45.runbot9.odoo.com/web?#id=21&view_type=form&model=stock.picking.type&menu_id=441&action=624
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12229776/2356c878-b84b-11e5-8cfc-f8cc09ff8d2e.jpeg)

When I tried to sell the product in the fresh brand new POS session, nothing is thrown in the UI while selecting the product.
Am I missing something?

regards

**Comment by flotho** [comment]
I precise that I tested also there : http://124496-9-0-c0f112.runbot9.odoo.com/web?#view_type=kanban&model=pos.config&action=919&menu_id=625 with the same parameters and it failed, No Serial is asked by the POS!

**Comment by bwilmus** [comment]
I have the same problem. It looks like something is missing to trigger the serial fllow up in the POS.

**Comment by pbetschen** [comment]
I am in the same case, I can not enter the serial number into the point of sale.

**Comment by fpoyer** [comment]
Same problem here...

**Comment by flotho** [comment]
Hi @mart-e is it possible to have a review on this?
Is it really a bug or did I miss something?
regards

**Comment by mart-e** [comment]
Hello,

Sorry it looks like something that is simply not present, it's a new feature.
And I don't think we want this as the point of sale is detached from the warehouse management, you don't want to interrupt the cashier with serial numbers, this is intended for backend.

**Comment by flotho** [comment]
Hi @mart-e, thanks for the answer.

If it's a new feature it should be a great one. 
To illustrate, I have some additionnal question. How do you handle the market of high value and traceability products. If working with weapons fro example, your have to track everything, what could be the workflow for this regarding to you?
Do you ask to the cashier to close the order and then fill correctly the shipping?
Implementing the lot tracking in the front end of the POS could be a great answer for the customers.

regards

**Comment by wtaferner** [comment]
@flotho 
It seems for me quite easy to fix this as the serial should have a unique name which is currently used to identify the product behind and the name is encoded as a code-128 barcode for example in the picking list...so, by doing a little module that makes sure to retrieve the serials could be taken to resolve the correct product and serial in one step without interfering with the normal workflow of the PoS.

Indeed, some work needs to be done to achieve this kind of integration, but in case it is worth it a customer...

:+1: for having the integration of serial numbers in the PoS in the future for standard Odoo

**Comment by flotho** [comment]
Damned, I was expecting this http://acespritechblog.com/2014/11/26/odoo-openerp-8-point-of-sale-assign-unique-serial-number/ to be the standard.
regards

**Comment by mart-e** [comment]
@flotho no this is a custom module, not in standard.

**Comment by flotho** [comment]
for sure @mart-e , my brain was stuck in 2015 ;-)

**Comment by treviser** [comment]
Good news from Acesprite: see https://www.odoo.com/forum/help-1/question/odoo-9-0-serial-numbers-in-pos-99149

**Comment by flotho** [comment]
Hi @treviser , for sure, we financed this port ;-)
