### ISSUE TITLE
[16.0] Invoice report: payment conditions displayed twice 

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#103876]
Impacted versions:
16, latests, repoducable on runbot
Steps to reproduce:
Enable the 'Add a payment QR-code to your invoices' setting
Current behavior:
Payment terms (and qr if applicable) are shown twice on invoices
Expected behavior:
Not to have these lines repeated.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/50528773/197394181-682934b2-dd3a-4bc3-afc8-548fd29e5b6f.png)

**Comment by niyasraphy** [comment]
PR to FIX:  https://github.com/odoo/odoo/pull/103878

**Comment by niyasraphy** [comment]
hi @jwaes ,
this has been fixed in:  https://github.com/odoo/odoo/commit/56d00814fed92782dca9425c4471382d26004198

feel free to close the ticket.
thanks
