### ISSUE TITLE
Error: Translations are not ready yet. Maybe use _lt instead?

### ISSUE THREAD

**Issue by saidbenthabet** [odoo/odoo#103857]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Can you share more details about this issue

**Comment by Yenthe666** [comment]
Sorry but this ticket contains no info so we cannot help you :) Please create a new one with detailed info.

**Comment by saidbenthabet** [comment]
Hello
I am using odoo 16 enterpris, and I am getting this error randomly when I open any app

**Comment by niyasraphy** [comment]
@saidbenthabet please try to reproduce the same in odoo runbot and also make sure that you are using the latest source code
