### ISSUE TITLE
[16.0] event_crm: lead generation rule exception

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103867]
**Impacted versions:**
16 CE and EE

**Steps to reproduce:**
1. Enable Developer mode
2. Events -> Configuration -> Lead Generation
3. Click on Create Button, exception will be raised

**Current behavior:**
Exception on clicking create button in lead generation menu

**Expected behavior:**
Allow to create without exception

Video/Screenshot link (optional):

![Screenshot from 2022-10-22 20-09-14](https://user-images.githubusercontent.com/27989791/197353429-6343439c-2b8b-4cfa-9691-158f6c501726.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sutharhardik** [comment]
Hii , @niyasraphy 

Can you please review again ?
I think its working. or need to follow any extra steps ?
[Odoo - Lead Generation Rule.webm](https://user-images.githubusercontent.com/41465217/197360648-2645eba0-b832-4002-a76c-23fd6b8ef9ef.webm)

**Comment by niyasraphy** [comment]
Seems this too working fine now

**Comment by niyasraphy** [comment]
This is happening only when debug mode is activated
