### ISSUE TITLE
[9.0] BUG on POS odoo  CASH PAYMENT METHODE

### ISSUE THREAD

**Issue by abourouis** [odoo/odoo#10383]
dear  community

I would like to poste an issue that I recontred when evaluating the free version. The scenario is when you select payment on the POS and you choose Cash methode and when you try to put the offert (both by keyboard or virual keybord) you obtain the following errors!
1- 

TypeError: Not enough arguments to Event.initEvent.
http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:285
Traceback:
Gui<.download_file@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:285:74
ErrorTracebackPopupWidget<.show/<@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:292:1013
jQuery.event.dispatch@http://localhost:8069/web/content/360-116775f/web.assets_common.js:740:378
jQuery.event.add/elemData.handle@http://localhost:8069/web/content/360-116775f/web.assets_common.js:713:151

2- 

ReferenceError: instance is not defined
http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:285
Traceback:
Gui<.numpad_input@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:285:479
PaymentScreenWidget<.payment_input@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:336:374
PaymentScreenWidget<.click_numpad@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:340:1
PaymentScreenWidget<.render_numpad/<@http://localhost:8069/web/content/733-39639b0/point_of_sale.assets.js:340:186
jQuery.event.dispatch@http://localhost:8069/web/content/360-116775f/web.assets_common.js:740:378
jQuery.event.add/elemData.handle@http://localhost:8069/web/content/360-116775f/web.assets_common.js:713:151

Regards

**Comment by abourouis** [comment]
any person can help please

**Comment by jorenvo** [comment]
The issues you're encountering are due to a mistake in the forward-port from saas-6 to 9.0. I've resolved these issues last week at 17bb5fd374b32e7ef98d042f6042d925bcfc3feb. Could you update your source code and try again?

**Comment by abourouis** [comment]
Thank you I'll try it.
