### ISSUE TITLE
[16.0] website_slides_forum: exceptions in posts menu

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#103871]
**Impacted versions:**
16 CE and EE

**Steps to reproduce:**
1. Enable developer mode
2. Elearning -> Forum -> Posts
3. On clicking the menu exception is raised.

**Current behavior:**
Exception is raised on clicking the posts menu.

**Expected behavior:**
open the menu without any exceptions

**Video/Screenshot link (optional):**

![Screenshot from 2022-10-22 21-14-42](https://user-images.githubusercontent.com/27989791/197356509-0eebb8ad-5353-4951-ae2a-0153e106f3de.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sutharhardik** [comment]
Hii, @niyasraphy 

In Community its working fine.
Can you please review with only Community version if currently you are testing with Enterprise?
[Odoo_Forum.webm](https://user-images.githubusercontent.com/41465217/197361402-32ac2510-810b-4cde-93fa-a5ed6febe18f.webm)

**Comment by niyasraphy** [comment]
@sutharhardik seems working fine in both versions now.

**Comment by niyasraphy** [comment]
Seems its still happening in run bot

![Screenshot from 2022-10-23 09-44-05](https://user-images.githubusercontent.com/27989791/197378129-5d6c30d5-80c7-405e-8c1c-767b8bae7754.png)
