### ISSUE TITLE
[16.0] Website Carousel block produces Javascript error with pop-up

### ISSUE THREAD

**Issue by seppedl** [odoo/odoo#103906]
Impacted versions: 16 Community Edition

Steps to reproduce: Add photo's to Carousel and remove all Titles, texts and buttons from all photos. Add filters. Remove some photos, add new photos, and let the Carousel run. After some time, this error occurs:

UncaughtClientError > TypeError
Niet-afgevangen Javascript-fout > Cannot read properties of null (reading 'classList')
TypeError: Cannot read properties of null (reading 'classList')
    at Carousel._setActiveIndicatorElement (https://www.coderdojohasselt.be/web/assets/789-7923b0f/1/web.assets_frontend_lazy.min.js:4163:184)
    at Carousel._slide (https://www.coderdojohasselt.be/web/assets/789-7923b0f/1/web.assets_frontend_lazy.min.js:4171:6)
    at Carousel.next (https://www.coderdojohasselt.be/web/assets/789-7923b0f/1/web.assets_frontend_lazy.min.js:4135:13)
    at Carousel.nextWhenVisible (https://www.coderdojohasselt.be/web/assets/789-7923b0f/1/web.assets_frontend_lazy.min.js:4136:71)

Current behavior: Site reports error via popup that user has to click

Expected behavior: Carousel to run continuously

Video/Screenshot link (optional): website: https://coderdojohasselt.be
![image](https://user-images.githubusercontent.com/15945940/197483638-010437c5-23df-49f2-80f3-20425d9e4382.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
@Williambraecky ?

**Comment by Feyensv** [comment]
Or probably more for @odoo/rd-website :thinking:

**Comment by qsm-odoo** [comment]
> Or probably more for @odoo/rd-website thinking

Yes, we will have a look. It was already in my TODO list in the form "Add carousel -> play with slides -> save -> slide -> click -> traceback". I think it is a BS5-related issue (cc @adr-odoo). @Guillaume-gdi could you have a look at it as soon as possible? Thanks :+1:

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/pull/103963 I think this is the fix? 🤔

**Comment by qsm-odoo** [comment]
The mentioned PR was indeed the fix. It was forward-ported in 16.0 11 days ago with https://github.com/odoo/odoo/commit/212e8ce620f6eb95aeff6426e06cb29b2c06d0c1 (actually this was a minor fix in 16.0 which introduced this critical bug -> we actually merged the correct minor fix in 14.0 and solved the critical bug in 16.0 along the way).
