### ISSUE TITLE
PDF Reports: Paper Format is not working 

### ISSUE THREAD

**Issue by ErpMstar** [odoo/odoo#104011]
Impacted versions: 16

Steps to reproduce:  Customise a  paper format and use it with Sale Order Report and other pdf reports also 

Current behavior: It is not using the Customise paper format, padding and margin also not working. always show same 

Expected behavior: the pdf must use the selected paper format

**Comment by ErpMstar** [comment]
OK, Here are the screenshots, it is tested on runbot.
![screenshot-20487845-16-0-all runbot77 odoo com-2022 10 25-18_04_56](https://user-images.githubusercontent.com/76473725/197775797-ec08e28c-9b06-46cd-9c2c-3d1b732c097c.png)
![screenshot-20487845-16-0-all runbot77 odoo com-2022 10 25-18_10_15](https://user-images.githubusercontent.com/76473725/197775827-42cbd5d3-fbed-4fa9-a94e-67798c7939d8.png)
PDF before changing the paper format
[Order - S00050.pdf](https://github.com/odoo/odoo/files/9860308/Order.-.S00050.pdf)
PDF after changing the paper format
[Order - S00050 (1).pdf](https://github.com/odoo/odoo/files/9860309/Order.-.S00050.1.pdf)


the paper format  changes are not applied.

I also checked same in ver 15 and it works fine

**Comment by SistemERP** [comment]
you are right, this problem also occurs in enterprise edition

**Comment by jabirmisnedtech** [comment]
Yes, it is not working. It is taking only the default paper format set on Settings / "Configure your document layout". Custom format set for reports are not taking effect.

**Comment by niyasraphy** [comment]
FIX: https://github.com/odoo/odoo/pull/104561

**Comment by niyasraphy** [comment]
Fixed by: https://github.com/odoo/odoo/commit/78e2c6456d2f9f06d42c18d7b1849d5fad4deb46
