### ISSUE TITLE
[8.0] supplier invoice residual  count double.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#10410]
CAS in china ask must encode supplier prepaid  into  prepaid account, not payable account.  when  create a prepaid invoice use prepaid account, and the account type of which is payable.   after validate the invoice, the balance should be count as double.

this issue should impact odoo9 also, but not tested.

i guess the logic of `_compute_residual` should rewritten.  the following step is how to reproduce this issue.
1. setup prepaid account...

![image](https://cloud.githubusercontent.com/assets/1404460/12253977/f619983e-b91e-11e5-9375-1f7ed0e70c22.png)

the internal type is payable, and check allow reconcliliation....
1. setup repaid product, should be used in  prepaid invoice..

![image](https://cloud.githubusercontent.com/assets/1404460/12254002/2b4c094c-b91f-11e5-86f6-1643a2fb210a.png)

set the default expense account to the account created above.
1.  create prepaid invoice..

after validated it, the balance became double.

![image](https://cloud.githubusercontent.com/assets/1404460/12254101/2be33014-b920-11e5-8de1-785f169d14e3.png)

account 2202 is payable also.

![image](https://cloud.githubusercontent.com/assets/1404460/12254145/a910853c-b920-11e5-907a-6ee4a48b0626.png)

**Comment by elicoidal** [comment]
Hi @jeffery9 
Technically the account type should be receivable, not payable (otherwise they would be together in the balance sheet).
I agree with you that the concept of prepayment is not easily handled in Odoo but in v8 and 9, it is getting easier. I miss the possibility to add a second account for prepayment in the customer as they are not in the same place in reporting (one is asset other is liability).
In previous version we had a community version account_prepayment which allow the full management of prepayment concept, now it can be handle via buttons in reconciliation so I think it is OK (most of the time the account is the almost the same for all customers).

**Comment by jeffery9** [comment]
what ever the account type.. both receivable and payable, the supplier
invoice always count as double, because it not consider the debit and
credit.

the prepayment is paid to supplier, i agree that it is asset, so the
account type is on asset side.  but it's internal type should be payable,
because the prepayment should be reconciled by later. if internal type set
to receivable, the reconciliation should not worked.



On Tue, Jan 12, 2016 at 11:47 AM, Eric Caudal <notifications@github.com>
wrote:

> Hi @jeffery9 <https://github.com/jeffery9>
> Technically the account type should be receivable, not payable (otherwise
> they would be together in the balance sheet).
> I agree with you that the concept of prepayment is not easily handled in
> Odoo but in v8 and 9, it is getting easier. I miss the possibility to add a
> second account for prepayment in the customer as they are not in the same
> place in reporting (one is asset other is liability).
> In previous version we had a community version account_prepayment which
> allow the full management of prepayment concept, now it can be handle via
> buttons in reconciliation so I think it is OK (most of the time the account
> is the almost the same for all customers).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/10410#issuecomment-170776875>.
>



-- 
Jeffery        -odoo expert form kunshan, suzhou, china

**Comment by feketemihai** [comment]
Hi all,

We had the same issue in residual invoice, and modified the invoice residual to take in consideration only payments that have the same account as the one specified in the invoice, so everything is ok when calculating, even if you record and advance, storno a prepayment, the residual is ok.

Mihai Fekete
OpenErp Specialist

E-Mail:       mihai.fekete@forbiom.eu<mailto:mihai.fekete@forbiom.eu>
Mobile:      +4(0) 746 – 028 477
Office:       +4(0) 356 – 173 953

Forest and Biomass Services Romania S.A.
Address: 11A Calea Buziasului, building B, 3rd floor | Timisoara 300699 | Romania

**Comment by feketemihai** [comment]
See https://github.com/odoo-romania/l10n-romania/blob/8.0/account_storno/invoice.py#L97

**Comment by elicoidal** [comment]
I tested those modules (storno) long time ago and they are suitable for China AFAIR

**Comment by feketemihai** [comment]
I will update the PR in the OCA/account-financial-tools with the storno module (still have to create tests) and probably to create a new tiny moduel for residual calculation only based on the account of the invoice...

**Comment by jeffery9** [comment]
@elicoidal  account type is used for financial report, and internal type use for application only. for example, payable  account can be used in supplier invoice

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
