### ISSUE TITLE
Odoo 8 Created User can't see nothing in helpdesk!?

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#10413]
When I'm creatign a new usr and give him all rights as the administrator, he can't see nothing in helpdesk. But when I'm duplicate the administrator user, and give them only rights to read leads, he can see all task in helpdesk.
Why is that so? Is this a bug?

I can make a user with "create" and give him all administrator rights and he is can't see not only 1 task in helpdesk.

**Comment by Yenthe666** [comment]
Hi @diezcode,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
