### ISSUE TITLE
 odoo 9 show popups

### ISSUE THREAD

**Issue by ahmedkhak** [odoo/odoo#10422]
I am working on odoo 9. I need to show popup. I am using that code to show popup

`raise osv.except_osv(_('UserError!'), _("Invoice not completed yet. Please complete that invoice"))`

and it shows that message

`WARNING odoo openerp.exceptions: except_orm is deprecated. Please use specific exceptions like UserError or AccessError`

 and popup do not shows up. Please help me in that

Another thing, for example if i have invoice id 1, or any other invoice info. I want to show user an lnvoice link, when user click on that link user will be redirected to that invoice. Please help me in that

**Comment by artaf** [comment]
from openerp.exceptions import UserError
....
raise UserError( _('Your msg here') )

Ah?

**Comment by Yenthe666** [comment]
Yep - the answer from @artaf will work.
