### ISSUE TITLE
pylibdmtx package is missing from requirements.txt

### ISSUE THREAD

**Issue by o-app-coder** [odoo/odoo#104271]
Impacted versions: 16.0

Steps to reproduce:
* create a venv
* install requirements from requirements.txt
* start odoo server

Current behavior:
This error message shows a missing python library:
` INFO ? odoo.addons.base.models.ir_actions_report: A package may be missing to print Data Matrix barcodes: pylibdmtx or libdmtx.`

Expected behavior:
This python package should be included in requirements.txt, because it seems that this is a requirement from the base module.

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/pull/103277

**Comment by vava-odoo** [comment]
Related PR is closed
