### ISSUE TITLE
[9.0] uncheck "expand all" button does not work in pivot view

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#10427]
In Pivot view, the expand all button works well. But when we unclick the button, nothing happens

The correct behavior would be : when we unclick the expand all button, we should have a collapse all action

**Comment by invitu** [comment]
better : we should return to previous state (before the button was clicked)

**Comment by pedrobaeza** [comment]
Right now, that's not the expected behavior (that's why the button doesn't change it icon). You can remove the upper level group, and expand again for obtaining a similar result.
