### ISSUE TITLE
Display Issue at Product Cart for BOM Cost Price

### ISSUE THREAD

**Issue by ramazansubasi** [odoo/odoo#104316]
Impacted versions: 16 

Steps to reproduce:

- Create Products
- Create Bom List 
- Check BOM Cost at Product Cart

Current behavior:
When I check the Product Cart for BOM Cost I see this error

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/6476677/198284277-9c53312c-d444-4a16-b380-1f5e880227fc.png)

**Comment by niyasraphy** [comment]
Hi,
thanks for reporting the issue, if you are talking about the overlapping issue of unit of measure and cost, it is fixed by: https://github.com/odoo/odoo/commit/812614b7d6e194f510491ff83f9a8e48594ae7c5

**Comment by ramazansubasi** [comment]
Thanks your notify.
