### ISSUE TITLE
[9.0][Enterprise]Sepa Module Bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#10431]
When we don't set the company name of sepa configuration on the company form,
and we want to download sepa file,
there's an technical error message,

It should be generate the information that we need to filled the company name on the sepa configuration on the company form, so the end user will not confuse about this.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thanks for your report.
Can you please add more information about how to reproduce this issue? Can you still reproduce this in Odoo 9?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in quite a while (almost a month).

Regards,
Yenthe
