### ISSUE TITLE
Feature Request for Odoo online: 

### ISSUE THREAD

**Issue by PHRPowerhouse** [odoo/odoo#104404]
I would like to add Affirm as a payment method via Stripe or add Affirm as a payment acquirer. 

Impacted versions: 15 and 16

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by kup-odoo** [comment]
Hello @PHRPowerhouse 

Appreciate your request.
As we only discussing issues here, you can post your bugs/issues if any.
For feature request, you can send an email in feedback@mail.odoo.com

This request will be closed from issues.
Thank you
