### ISSUE TITLE
Getting Error When try to Validate Scrap order 

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#104468]
Impacted versions: V16 

Steps to reproduce:
Step 1 : Open Inventory Module 
Step 2 : Click on Operation 
Step 3 : Click on Scrap 
Step 4 : Create Scrap order 
step 5 : Click on Validate button 
Step 6 : Error generated 

Current behavior: When try click on Validate button getting Error.  

Expected behavior: User able to Validate Scrap order. 

Video/Screenshot link [(optional): [](https://drive.google.com/file/d/1qaw1G-ZN56GNVUWWoaC4tOqDSKBKBnHf/view?usp=sharing)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
This happens when the unit of measure feature is not activated and as per my understanding the fix is on the way

**Comment by niyasraphy** [comment]
PR:  https://github.com/odoo/odoo/pull/104806

**Comment by ticodoo** [comment]
fixed with https://github.com/odoo/odoo/pull/104806
