### ISSUE TITLE
9.0 Invoice creation from Sales order : date missing

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10448]
When generation invoices from sales order, we MISS a field (we used to have V8) to define invoice DATE on invoice draft
Invoices are usually create some days AFTER end of month, so invoice date MUST be manually defined.

Easy to correct when generating few invoices
But when a customer need to create thousand of invoice every month, it  is not possible to do.

This field 'invoice date' must be added in invoices generation from SO

**Comment by pedrobaeza** [comment]
This has been changed in this version to avoid problems when setting manually the date, as you can easily generate invoices and validate them in an incorrect chronology, so by default the date is empty. If you still want this dangerous behavior, you can always program a community module for having it back.
