### ISSUE TITLE
[9.0][8.0][whislist] website_sequence of products to be set per category

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#10441]
would be a nice feature to have for products to keep them in order/styles differently for each category so this would help to increase the sales in e-commerce. 

currently you update/enable/publish etc a product and it keeps popping on top of everything else.

**Comment by Yenthe666** [comment]
Hi @ddfs ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). As this change would require changes in a stable that are not allowed I'm closing this.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
I'll label it wishlist so it keeps popping up though!

Regards,
Yenthe
