### ISSUE TITLE
cannot send an invoice : 'mail.compose.message' object has no attribute 'message_post'

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#1045]
Trying to send an invoice with the "Send Invoice" button :

  File ".../odoo/addons/account/account_invoice.py", line 1623, in send_mail
    self.message_post(body=_("Invoice sent"))
AttributeError: 'mail.compose.message' object has no attribute 'message_post'

**Comment by Yenthe666** [comment]
Hi @ccomb,

Thanks a lot for your report. This issue has been fixed a while ago with commit https://github.com/odoo/odoo/commit/299246e2aec867cc90f56caaefad6c99d8f2f31f but this issue was never closed.
Closing this since it has been fixed.

Regards,
Yenthe
