### ISSUE TITLE
[9.0]Supplier invoice line get the sale price instead of the cost/supplier info

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10450]
Hi,

While creating a new supplier invoice, the sale price is used in the invoice lien instead of the supplierinfo or the cost!

**Comment by pedrobaeza** [comment]
On invoices, no pricelists are used, neither for customers nor vendors, but the only price that is taken from the list price or cost price respectively:

https://github.com/odoo/odoo/blob/73425edfe9e03c8ea7e97ab9d7cd6eddec718849/addons/account/models/account_invoice.py#L1522-L1527

So this is correct in latest versions with its constraints.
