### ISSUE TITLE
[Feature Request] Dynamic Variants should be createable at the BOM stage

### ISSUE THREAD

**Issue by SvbZ3r0** [odoo/odoo#104581]
Currently, dynamic variants are only created when a SO or a PO is generated for the product. This is pretty useful when the total variant combinations number in the thousands, and only certain combinations are actually needed at any one time. 

Dynamically creating variants would also be extremely useful in a manufacturing setup where the number of component variants is in the thousands. However, in most manufacturing setups, a BOM is always created before a PO or SO is issued. Currently, you can only select existing variants as components in a BOM.

The feature I would like to see is that BOM component selection should work the same way as choosing products in a SO or PO. If you choose a product with variants, it should show the grid selector or the product configurator.

Product selection in BOM
![image](https://user-images.githubusercontent.com/57280279/198866536-3034c23e-a776-4ef1-876d-58734c162aaf.png)
vs
Product selection in PO
![image](https://user-images.githubusercontent.com/57280279/198866580-bb54df01-3686-4808-975b-792b81577faa.png)
![image](https://user-images.githubusercontent.com/57280279/198866596-921244f4-c0ae-4ab5-bfad-28d453013e5e.png)

**Comment by SvbZ3r0** [comment]
Hi @kup-odoo 
The issue is that dynamic variants aren't createable at the BOM stage. It is a problem with the current work flow.

**Comment by SvbZ3r0** [comment]
![image](https://user-images.githubusercontent.com/57280279/199019389-eb5b3852-2c54-4ffd-97ed-1dd8fd94afbd.png)

**Comment by kup-odoo** [comment]
Hello @SvbZ3r0 ,

You can submit your request in odoo.com/help
