### ISSUE TITLE
[16.0] stock.view_picking_type_tree can not multi_edit="1"

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#104579]
Impacted versions:
16.0
Steps to reproduce:
1、Install stock app
2、Edit stock.view_picking_type_tree and add multi_edit="1"
3、Can not save change and got an error message“
Field 'company_id' used in domain of field 'warehouse_id' ([('company_id', 'in', [company_id, False])]) is restricted to the group(s) base.group_multi_company.
Current behavior:
![图片](https://user-images.githubusercontent.com/46485742/198857681-db9c5ce6-f5c4-49eb-8ef7-ee4f4f8cc319.png)

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Bonainifo** [comment]
When I delete the groups of company_id, multi_edit work property
![图片](https://user-images.githubusercontent.com/46485742/198857716-42d89d41-50f8-4b14-9118-1a9a35964404.png)

**Comment by john-herholz-dt** [comment]
I have the same problem for purchase orders. 
Is it a bug or intendet?

**Comment by niyasraphy** [comment]
hi @Bonainifo ,
this has been fixed in:  https://github.com/odoo/odoo/commit/dad9d98697781307a1cb537e8e818a775b50432a

feel free to close the ticket.
thanks
