### ISSUE TITLE
[8.0] Incoming mail are not correctly sanitized

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#10452]
**Incoming mail with embedded content are not correctly sanitized. (The colors too)**

Impacted versions:
- 8.0

Steps to reproduce:
1. Into Odoo, send a mail to a partner
2. Reply to this email using thunderbird and including an embedded picture
3. Into Odoo: fetch email.

Current behavior:
- Into the partner form the tag `<img>` is now `&lt;img&gt;` and then not rended anymore.

Expected behavior:
- tag img correctly rendered

Note:

With an embedded picture, the mail client add a `cid:` and the `cid` of thunderbird has a `@`. So into the `openerp/tools/mail.py/html_sanitize` the `regexpr : r"(<(([^a<>]|a[^<>\s])[^<>]*)@[^<>]+>)"` take the image tag into consideration and then apply the `cgi.escape`

By a more general way, this `html_sanitize` is really too restrictive: even color from a mail client are not well passed. It's really problematic for customers who use the Odoo mailing feature

**Comment by JonathanNEMRY** [comment]
OPW 666776

**Comment by JonathanNEMRY** [comment]
@csnauwaert what do you think about this one?

**Comment by csnauwaert** [comment]
I think that @tde-banana-odoo who created the mail module will probably answer this question better than I. There is probably a good reason for the html_sanitize to be this restrictive.

**Comment by JonathanNEMRY** [comment]
Any news @tde-banana-odoo ?

**Comment by tptruth** [comment]
Same problem, impossible to use on a daily basis. Clients send e-mail that are illegible.

**Comment by tde-banana-odoo** [comment]
Hello,

This is due to email escaping being a bit too broad. It has just been fixed in 9, and I try to backport it in 8. However please note that cids are not recognized in 8 and 9, so images won't be displayed inline. In master this will be improved soon.

**Comment by Yenthe666** [comment]
Hi @JonathanNEMRY,

Thank you for your report.
As @tde-banana-odoo mentioned this has been fixed in V9. Since V8 is no longer supported I'm closing this bug report.

Regards,
Yenthe
