### ISSUE TITLE
Odoo invoice preview too much space

### ISSUE THREAD

**Issue by numabit** [odoo/odoo#104646]
Impacted versions: 16

Steps to reproduce: create a basic invoice and click preview

Current behavior:  to much space on left and right 

Expected behavior: a preview of an invoice correctly aligned 

Video/Screenshot link (optional):
![odoo too much space](https://user-images.githubusercontent.com/69018770/199115812-475ff61c-a814-4fca-87bd-5c1a0de48266.jpg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Hi,
upon trying to reproduce the same in runbot, it seems to be working fine for me.

![Screenshot from 2022-11-01 09-11-01](https://user-images.githubusercontent.com/27989791/199170286-f6cff9d7-034c-42fd-b7f8-febc47b5c193.png)

Did you made any changes inside report paper format and that is responsible for this ?

Thanks

**Comment by numabit** [comment]
i tested it again on a clean docker server.

steps:

1. clean Install the docker image
2. clear browser cache 
3. database config wizard
4. login
5. install the invoice module
6. open invoice
7. create invoice
8. preview invoice

no other modifications



my docker stack
-------------------

version: "3.8" 
services:
  odoo:
    image: odoo:latest
    container_name: odoo16
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"   
    #tty: true
    #command: -- --dev=reload
    environment:
      - HOST=db
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASS}
    volumes:
      - web-data:/var/lib/odoo
      - web-addons:/mnt/extra-addons
      - web-conf:/etc/odoo
      - web-logs:/var/log/odoo
      
    restart: always            
   
 
  db:
    image: postgres:13.8
    container_name: odoo16-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${ODOO_USER}
      - POSTGRES_PASSWORD=${ODOO_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

    restart: always            

volumes:
  web-data:
  web-conf:
  web-logs:
  web-addons:
  db-data:

**Comment by numabit** [comment]
live example: https://test784.odoo.com/my/invoices/2?access_token=40016c6e-9ab9-4f5e-9bbb-90c8a1845221

**Comment by kup-odoo** [comment]
Hello @numabit 

It's seems working fine in runbot.odoo.com
You can raise ticket for this issue in odoo.com/help.

This issue will be closed from here.
Thank you
