### ISSUE TITLE
9.0 Invoicing from SO : no more possible for a certain dates range

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10464]
On V8, in invoicing sales order lines or time sheet,  we were able to  select invoicing period when filtering on lines -> this is not possible anymore as we invoice  from the whole sales order now (and not lines) so we no possibility to filter anything

We might need this as, very often, especially for time and material, invoicing is done for a certain period, as week or month.

We have to re-create theses possibility 
When creating invoices from Sales order (menu Sales > Sales order > "select SO" > action > invoice order) 
We should have two fields to define 
a start date
a end date
to select products time and material to invoice

**Comment by Yenthe666** [comment]
Hi @stephaniemillet,

I guess you could find a way around it with the invoicing options or with custom development:
![image](https://user-images.githubusercontent.com/6352350/34992677-3183e120-face-11e7-8fca-fc2f7e71e2f6.png)

As V9 is a stable version this won't/can't be changed.

Regards,
Yenthe
