### ISSUE TITLE
Save Sale order When the language is Arabia

### ISSUE THREAD

**Issue by ahmedfh** [odoo/odoo#10468]
Hello guys, 

I tried to save sale order when the language is Arabic but I cannot. I can save the sale order when the Lagrange is English. The Error is The expire date and order date in not valid. I tried to change the format of the date but it does not work. please, can anyone help with this issue?

Thanks

**Comment by Yenthe666** [comment]
Hi @ahmedfh,

I can't reproduce this error on the latest code anymore. An example:
![image](https://cloud.githubusercontent.com/assets/6352350/16008787/e1bda686-3179-11e6-8600-889d8081afa2.png)
Please update your Odoo codebase, your issue should be resolved then.

Regards,
Yenthe
