### ISSUE TITLE
Shortcuts to switch to list/kanban views stopped working on v15

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#104667]
Impacted versions:
- 15.0
- 16.0

Steps to reproduce:
- Open any view that implements list and kanban, e.g. contacts
- Press Alt+L or Alt+K

Current behavior:
Nothing happens

Expected behavior:
It should switch between list and kanban views, as it did in version >= 14.0. Those shortcuts are documented in the shortcuts page (Click on user name -> Shortcuts), so they should work.

Support ticket number submitted via odoo.com/help (optional):

OPW #3052364

**Comment by luisg123v** [comment]
CC @moylop260 @nhomar

**Comment by desdelinux** [comment]
@brboi Can you help us with a solution to this?, please

**Comment by vava-odoo** [comment]
This is not supported anymore (see discussion here https://github.com/odoo/odoo/pull/105293)
