### ISSUE TITLE
Deliveryslip formatting

### ISSUE THREAD

**Issue by netfxtech** [odoo/odoo#104645]
Impacted versions: 16.0

Steps to reproduce: 
- Print delivery slip from a transfer

Current behavior:
- PDF is generated but table formatting is off. Name is small.

Expected behavior:
- PDF should print with tables formatted correctly and name should not be small

Below screenshot is from runbot v16.0
https://20665062-16-0-all.runbot66.odoo.com/web#id=78&menu_id=570&cids=1&action=826&model=stock.picking&view_type=form

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/62037189/199113226-0f5f42a4-d843-4ee2-b35b-d984799de095.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
seems this is already resolved in 16.0

**Comment by netfxtech** [comment]
This is correct. Thank you.  Closing issue.
