### ISSUE TITLE
After Enable purchase Agreement not able to see Purchase Agreement button in menu bar 

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#104650]
Impacted versions:V 16 

Steps to reproduce: 
1) Open Purchase Module 
2) Click on Configuration in menu bar 
3) Click on Setting 
4) Enable Purchase Agreement 
Current behavior:
After Enable purchase Agreement Not able to see Purchase agreement in any menu and also not able to create new purchase agreement.

Expected behavior: 
User should be able to Create New Purchase agreement after Enable Purchase Agreement. 

Video/Screenshot link (optional): [](https://drive.google.com/file/d/1vAayBu6qSBgxYdxpxYEPA9TuhlFjCYkJ/view?usp=share_link)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
See: https://github.com/odoo/odoo/commit/00689e7fc61ac08a2f75d856dc077a9ef46b2b26
