### ISSUE TITLE
Custom favicon doesn't work in Odoo 9

### ISSUE THREAD

**Issue by lrazov** [odoo/odoo#10472]
We want to override the website template to be able to use our own favicon on website in Odoo 9. 

We have created a custom module website_favicon with the following structure:

__init__.py (empty)

__openerp__.py

views

    - website_templates.xml 

static 

    -  src

        - img 

            favicon.ico 

In  __openerp__.py I put {
    'name': "Website Favicon",
    'version': '1.0.0',
    'author': 'Me',
    'category': 'Custom',
    'description': '''Website Favicon''',
    'depends': ['website'],
    'data': [
        'views/website_templates.xml',
        ],
    'installable': True
}

In website_templates.xml I put 

<?xml version="1.0" encoding="utf-8"?>
`<openerp>`
` <data>`
  `<template id="website_favicon" inherit_id="website.layout" name="Website Favicon">`
        ` <xpath expr="//meta[@name='keywords']" position="after">`
          `<link rel="shortcut icon" href="/website_favicon/static/src/img/favicon.ico" type="image/x-icon"/>`
         `</xpath>`
    ` </template>`
 `</data>`
`</openerp>`

The module installed successfully and I see the <link.../> code being inserted in the page source, but  the new favicon is not used on my website. Could you advice? Thank you

**Comment by Yenthe666** [comment]
Hi @lrazov,

The Github issues are only for bugs on the official Odoo, not for custom development or help.
I'd suggest you to create a new question on the official Odoo forums (help.odoo.com) if you still face this issue, I'm sure somebody can help you!

Regards,
Yenthe
