### ISSUE TITLE
Custom font doesn't work in Odoo 9 Clean theme

### ISSUE THREAD

**Issue by lrazov** [odoo/odoo#10471]
We are building a website in Odoo 9 using Clean theme and would like to use a custom font which would be selectable from the customize theme panel. 

I have uploaded the font into theme_common\static\src\font directory, edited fonts.less and customize_modal.xml files, created font_FONTFONT.less file (FONTFONT is just for explanation purpose) but when I select the new combination from the customization theme panel the Times New Roman is used, not my font. BTW, the custom font is rendered correctly in the customization theme panel.

I also tried to add a new font combination using the OOTB fonts (Oswald Regular with Oswald Light) to the customization theme panel and followed the same steps as above with the same result - the Oswald Light font is not used, Times New Roman is used instead.

Do I have to install custom fonts on Odoo server first? Am I missing something? Thank you

**Comment by pedrobaeza** [comment]
Sorry, but this is not a problem itself of Odoo, but something about development. Please ask in the forums or mailing lists.
