### ISSUE TITLE
[9.0] New Install - Landing Page Not Rendering Correctly

### ISSUE THREAD

**Issue by lukasbradley** [odoo/odoo#10470]
I just did an install of Odoo 9 from https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo on Fedora 23.  Version number is 9.0c_20160114.

After logging in as admin, the homepage/landing page looks like the following:

![image](https://cloud.githubusercontent.com/assets/526286/12342532/3c7011ba-baf9-11e5-945f-4db0fd95809a.png)

I get the same rendering problems in Firefox 43.0.1 and Chrome Version 47.0.2526.106.  I also get the same problems viewing the page in Windows 10 and Fedora 23.

I would normally assume this is due to a nightly build.  However, the installation instructions suggested it would be the most stable version.  If this is a nightly build issue, is there a stable 9.0 version I could play with?

Thanks for your help.

**Comment by xmo-odoo** [comment]
@sle-odoo could this be related to missing/misgenerated CSS in the assets bundle?

**Comment by sle-odoo** [comment]
Closing as it's most probably fixed in 52f55ed4936bcbab733ecbc999cb6b6bff16bb3c
