### ISSUE TITLE
Not such group for Accounting Feature - Readonly

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#104711]
Impacted versions: V 16 

Steps to reproduce:
1) Open General Setting 
2) Open any User 
3) Scroll Down to Technical  

Current behavior: Accounting Features group not shows means it's Read only Filed. 

Expected behavior: User should be able to see all Accounting group for see all the Accounting Dashboard.

Video/Screenshot link : [Accounting Feature](https://drive.google.com/file/d/1FnxGeUZd_qSDITrNSd5PbC4ihDPX0-29/view)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Hi,
this is intentionally removed from users form view, see: https://github.com/odoo/odoo/commit/0624e3f728292e0aededf93139fd2d7f22bd1c20

Thanks
