### ISSUE TITLE
[14.0 EE] Regression : contact creation on the fly

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [odoo/odoo#104713]
Impacted versions: Odoo v14 online

Steps to reproduce:
Create a lead with no contact, but just an email.
click on the checkbox of mail chatter to add the email as contact, the error pops up.

Current behavior:
BLOCKS you. ""The information you have entered does not match the existing contact information for this record. The partner was not created.""

Expected behavior: should allow to go ahead like earlier. Its a new record we are creating so the issue should not arise.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5909386/199478774-9fe6628f-0a60-4682-84c2-ba8b6d906516.png)

![image](https://user-images.githubusercontent.com/5909386/199479128-2a31047d-b338-46b2-88b4-41c924509650.png)

Support ticket number submitted via odoo.com/help (optional):
https://github.com/odoo/odoo/commit/14e0abd1f4c88fd6f548401bf517e95c798c0c22 seems to be the source of issue

**Comment by pedrobaeza** [comment]
It seems reverted in #104689
