### ISSUE TITLE
[9.0] Point Of Sale Client Screen is not inheritable 

### ISSUE THREAD

**Issue by chrisdilbert** [odoo/odoo#10489]
Dear commnunity,
I want to modify the ClientListScreenWidget but it's missing from screens.js in the static files from point of sale

```javascript
return {
    ReceiptScreenWidget: ReceiptScreenWidget,
    ActionButtonWidget: ActionButtonWidget,
    define_action_button: define_action_button,
    ScreenWidget: ScreenWidget,
    PaymentScreenWidget: PaymentScreenWidget,
    OrderWidget: OrderWidget,
    NumpadWidget: NumpadWidget,
    ProductScreenWidget: ProductScreenWidget,
    ProductListWidget: ProductListWidget,
};
```

**Comment by Yenthe666** [comment]
@chrisdilbert please create a topic on the official Odoo help forums (https://www.odoo.com/forum/help-1). This is for bugs within Odoo and this is clearly not an issue but a question. :+1: 
@mart-e locky lock.
