### ISSUE TITLE
9.0 doc in mail addon out of date

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#10480]
https://github.com/odoo/odoo/tree/9.0/addons/mail/doc is out of date and therefore close to unusable.

**Comment by Yenthe666** [comment]
Hmm either a new rewrite or a removal would be nice. Good catch :+1:

**Comment by gurneyalex** [comment]
having some up to date documentation for mail is really needed. This is a complex topic and quite difficult to test.

**Comment by tde-banana-odoo** [comment]
I don't see what you mean :rooster:

**Comment by Yenthe666** [comment]
@tde-banana-odoo any update on this? :gem:

**Comment by tde-banana-odoo** [comment]
Yes, deprecated documentation has been removed :man_astronaut:
