### ISSUE TITLE
Odoo Forum Issue (No Badges)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#10498]
Hello,

I am not getting any badges on Odoo Forum Website 

I have filled up all details and also answered Some Question but still i am not getting any badges

I have also asked question for that : https://www.odoo.com/forum/help-1/question/meta-i-am-not-receiving-any-badges-95566

Here is my Profile link: https://www.odoo.com/forum/help-1/user/569045

Thanks

**Comment by Yenthe666** [comment]
@odony is this the same behaviour as a while back where the schedulers couldn't handle the massive job? He should have atleast gotten the bio badge. (https://www.odoo.com/forum/help-1/user/569045)
I'm going to guess this is the same problem showing up again.

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

In the meanwhile the forum has been updated and the speed has been improved. A few days ago I've personally got a new badge so I think this has been fixed by now.
If this issue still persist don't hesitate to comment and I'll reopen it.

Regards,
Yenthe

**Comment by thayifkabir** [comment]
Hello,
still not  getting any badges in odoo

**Comment by Yenthe666** [comment]
@thayifkabir you have to update your local Odoo instance 😉

**Comment by cvshayar** [comment]
Hi,
I am new to odoo
I have filled up all details and also asked some questions and not getting any badges
