### ISSUE TITLE
Odoo 9 on binami - Google Cloud - Developer Mode UI is all messed up

### ISSUE THREAD

**Issue by adrianpipo** [odoo/odoo#10493]
![image](https://cloud.githubusercontent.com/assets/8686054/12371885/d41829a8-bc5c-11e5-9f66-4941cd82f952.png)

**Comment by Nathaniel401** [comment]
I've experienced the same exact issue too.

**Comment by JayVora-SerpentCS** [comment]
Either it could be a cache issue, or less files, or 'blog' module.

**Comment by pedrobaeza** [comment]
This is not a problem of Odoo itself, but a deployment problem. It's not the first time someone reports problem with the Bitnami image, so it seems something on their side.
