### ISSUE TITLE
[12.0] zip nitghtly is not updated

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#104987]
Impacted versions:
12.0

Hi there, I see the official zip in particular the last tarbal  https://nightly.odoo.com/12.0/nightly/tgz/  not conain all code code of 

https://github.com/odoo/odoo/tree/12.0.

For istance there isn't the module for microsoft outlook integration and Google oauth integration.

Is it possible release a news tarball?

Thank you

**Comment by Xavier-Do** [comment]
12.0 version was deprecated one year ago. 
Some fixes may be merged on github but the zip are not generated anymore. I would suggest you to use the source code version from github if you need them.

**Comment by matteoopenf** [comment]
I'm not agree with this way

**Comment by matteoopenf** [comment]
In the past the zip of other version was updated

**Comment by Xavier-Do** [comment]
It is possible that sometimes we forget to disable the version for a while, but we cannot support all version indefinitely. 
I summon @d-fence for an expert opinion.

**Comment by matteoopenf** [comment]
I agree For no support indefinitely.But only in this case.Thanks in advanceMatteo ***@***.*** Il giorno 10 nov 2022, alle ore 13:34, xdo ***@***.***> ha scritto:﻿
It is possible that sometimes we forget to disable the version for a while, but we cannot support all version indefinitely.
I summon @d-fence for an expert opinion.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano
