### ISSUE TITLE
Rename "openerp" to "odoo"

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#105]
The project's name change ought be impacted on the project content (collecting, may not be correct):

- rename the `openerp` (and `openerp.addons`) modules
  - add a BC layer so the old name remains available (import hook? that's going to be fun...)
  - for CSS classes, do we add a `odoo` class next to the `openerp` one and leave `openerp` in for partners &al?
  - what about `oe_`-prefixed classes?
    - not necessary (fme)
  - scripts? eg `openerp_mailgate`, duplicate? (symlinks not an option because windows)
- manifest file (`__openerp__.py`)
  - Maybe a generic name (eg: `__manifest__.py`) ?
- Thunderbird & Outlook plugins
- Windows service
- root element in XML data files (IIRC the parser doesn't even look at them)
  - odo proposes to get optionally use <data> as root
- references in comments
- odooframework!
- root logger
- email addresses
- PO file strings (non-POT)

Not sure?
- project name in POT file comments? (fix POT exporter instead?)
- license headers
- SAAS url (`*.my.openerp.com`) don't seem to work on `odoo.com`
- config/environ keys (`openerp.tools.config` -> `env['OPENERP_SERVER']`; mailgate `OPENERP_*`)
- functional documentation :

things to *not* rename (collecting, may not be correct)
- user names (e.g. `Last-Translator` tags in PO files)
- company name references (OpenERP SA)?
- debian/changelog contents?

(ignoring PO files, there are 25530 instances of `/open\s?erp/i` in the working copy it seems)

**Comment by sebastienbeau** [comment]
Renaming __openerp__.py to __manifest__.py is a really good idea.

**Comment by Yenthe666** [comment]
@xmo-odoo is this here for you to remember what to do or can it be closed?
This will all be handled in V10 anyway.

**Comment by xmo-odoo** [comment]
> is this here for you to remember what to do

Yes, to an extent. At least to remember some of the issues and concerns.

**Comment by Yenthe666** [comment]
Alright I'll leave the issue open then.

**Comment by lmignon** [comment]
@xmo-odoo Since you are moving from openerp to odoo, It would be nice to properly declare `odoo` and `odoo.addons`as namespace packages. https://github.com/odoo/odoo/pull/8758.

**Comment by Yenthe666** [comment]
Hi @xmo-odoo,

I believe this one can be really closed now. Odoo 10 is here, the old API is dropped and pretty much everything is renamed.
Just re-open this if you find that it should be open though.

Regards,
Yenthe
