### ISSUE TITLE
[8.0] calling multiple documents (templates) in Qweb bugged (with t-forearch)?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#10508]
I need to call another template of invoice (it is related with invoice, but not invoice itself) just after invoice (`account.invoice` model) was generated, so it would print two templates in one pdf.

I tried doing this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>     
    <data>
        <template id="report_invoice" inherit_id="account.report_invoice">
            <xpath expr="//t[@t-foreach='doc_ids']" position="after">
                <t t-raw="translate_doc(doc_id, doc_model, 'partner_id.lang', 'account_packing_report.report_packing_document')"/>
            </xpath>
        </template>
    </data>
</openerp>
```

After doing this, it seems it tries to call that template, but it is either bugged or something is not right.
My template looks like this (its for `account.invoice` model):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>     
    <data>
        <template id="report_packing_document">
            <t t-call="report.external_layout">
                <div class="page">
                    <div class="row">
                         <div class="col-xs-5 col-xs-offset-7">
                            <address t-field="o.partner_id"
                                t-field-options='{"widget": "contact", "fields": ["address", "name"], "no_marker": true}' />
                            <span t-if="o.partner_id.vat">TIN: <span t-field="o.partner_id.vat"/></span>
                        </div>
                    </div>              
                </div>
            </t>
        </template>
    </data>
</openerp>
```

For some reason it prints yourcompany, chicago header (demo data), instead of yourcompany header (invoice is for yourcompany and invoice header is for yourcompany). If in template I add just simple text, then it prints it, but if I try to add any field from model record, it then prints empty white page, but no errors at all.

So this feature is not working or I am missing something?

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
