### ISSUE TITLE
password reset does not work, signup_email is in url

### ISSUE THREAD

**Issue by wpichler** [odoo/odoo#105007]
Impacted versions:
16.0

Steps to reproduce:
Create new user
Let him do the normal signup
Send Password reset mail

Current behavior:
User will get redirected to login page

Expected behavior:
User whould get to the /reset/password site

the function _get_signup_url_for_action does generate a new signup url for a user. Since Odoo 16 it will generate a signup url always with the signup_email included as parameter. This does cause the controller function web_auth_reset_password to make a redirect to /web/login - instead of the password reset.

In odoo 15 the signup_email was not included as a parameter

**Comment by wpichler** [comment]
Replace this
```
query = {'db': self.env.cr.dbname, 'signup_email': partner.email}
```

with this after the signup_type = self.env.context.get('signup_force_type_in_url', partner.sudo().signup_type or '')

```
        if signup_type == 'reset':
            query = {'db': self.env.cr.dbname}
        else:
            query = {'db': self.env.cr.dbname, 'signup_email': partner.email}
```

then it will work


complete function:
```
def _get_signup_url_for_action(self, url=None, action=None, view_type=None, menu_id=None, res_id=None, model=None):
    """ generate a signup url for the given partner ids and action, possibly overriding
        the url state components (menu_id, id, view_type) """

    res = dict.fromkeys(self.ids, False)
    for partner in self:
        base_url = partner.get_base_url()
        # when required, make sure the partner has a valid signup token
        if self.env.context.get('signup_valid') and not partner.user_ids:
            partner.sudo().signup_prepare()

        route = 'login'
        signup_type = self.env.context.get('signup_force_type_in_url', partner.sudo().signup_type or '')
        # the parameters to encode for the query
        if signup_type == 'reset':
            query = {'db': self.env.cr.dbname}
        else:
            query = {'db': self.env.cr.dbname, 'signup_email': partner.email}
        if signup_type:
            route = 'reset_password' if signup_type == 'reset' else signup_type

        if partner.sudo().signup_token and signup_type:
            query['token'] = partner.sudo().signup_token
        elif partner.user_ids:
            query['login'] = partner.user_ids[0].login
        else:
            continue  # no signup token, no user, thus no signup url!

        if url:
            query['redirect'] = url
        else:
            fragment = dict()
            base = '/web#'
            if action == '/mail/view':
                base = '/mail/view?'
            elif action:
                fragment['action'] = action
            if view_type:
                fragment['view_type'] = view_type
            if menu_id:
                fragment['menu_id'] = menu_id
            if model:
                fragment['model'] = model
            if res_id:
                fragment['res_id'] = res_id

            if fragment:
                query['redirect'] = base + werkzeug.urls.url_encode(fragment)

        signup_url = "/web/%s?%s" % (route, werkzeug.urls.url_encode(query))
        if not self.env.context.get('relative_url'):
            signup_url = werkzeug.urls.url_join(base_url, signup_url)
        res[partner.id] = signup_url

    return res

```

**Comment by Oluwaseun241** [comment]
can i work on this @wpichler

**Comment by wpichler** [comment]
sure - feel free to use the code fragment directly

**Comment by Oluwaseun241** [comment]
Ok on it

**Comment by Oluwaseun241** [comment]
@wpichler I'm having difficulty in finding the file path

**Comment by wpichler** [comment]
https://github.com/odoo/odoo/blob/a0fcadb272f050d72711494e4684ab228e4bd681/addons/auth_signup/models/res_partner.py#L61

**Comment by BT-apadron** [comment]
I am having the same issue with the 16 version. 
I have already tried the solution proposed and it works perfectly.
What is the status of this issue?

**Comment by Oluwaseun241** [comment]
I don't know what's happening with the bot checks some are failing maybe you can help

**Comment by BT-apadron** [comment]
Hello again,

I wrote the solution in your PR https://github.com/odoo/odoo/pull/105097

**Comment by BT-apadron** [comment]
Hello, first of all, happy new year! 

The PR [#105097 ](https://github.com/odoo/odoo/pull/105097#) was closed. 

Are you working on the solution in other PR?

I am pleased to help with the solution of it.

I look forward to your response.

**Comment by BT-apadron** [comment]
Hello @wpichler 
There is any news about this issue?

**Comment by wpichler** [comment]
@BT-apadron Can't belive that this issue is still not resolved. I've resolved it for my customer - but did not created the PR - because there was already one... No idea why odoo is not acting on that.

**Comment by wpichler** [comment]
@BT-apadron I've looked at the current version - it does seem that there is a fix already. Please checkout latest odoo version from git. It should work already.
