### ISSUE TITLE
[16.0] web: add menu item error

### ISSUE THREAD

**Issue by sturlan** [odoo/odoo#105000]
Impacted versions:
16.0-20221104
Steps to reproduce:
website - site - menu editor - add menu item
Current behavior:
Odoo Client Error
Expected behavior:
add menu item dialog box

Full error:
UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    OwlError@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1098:1
    handleError@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1105:101
    handleError@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1932:29
    complete@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1343:37
    processFiber@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1909:43
    flush/this.frame</<@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1905:109
    flush/this.frame<@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1905:87

Caused by: TypeError: this.website.pageDocument is null
    setup/<@https://recruit.prog-ram.com/web/assets/760-2446517/web.assets_backend.min.js:13322:672
    useEffect/<@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1940:145
    complete@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1341:196
    processFiber@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1909:43
    flush/this.frame</<@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1905:109
    flush/this.frame<@https://recruit.prog-ram.com/web/assets/759-40e4c2c/web.assets_common.min.js:1905:87

**Comment by kup-odoo** [comment]
Hello @sturlan 

I follows your suggested steps to reproduce an error.
it's working fine for me.
can you provide video url or screenshot?

**Comment by sswapnesh** [comment]
Hello @sturlan 

It seems to be issues with your setup as it is working well on runbot too.
![Screenshot from 2022-11-10 03-12-39](https://user-images.githubusercontent.com/16624719/200948032-1ae61784-3790-419c-97a8-76c472ce81d4.png)

**Comment by sturlan** [comment]
Yes, maybe you are right, i can only reproduce it on this server. Will try toi localize
https://user-images.githubusercontent.com/47605285/200948669-daff6778-d2f4-439d-8a65-d81c49f828e4.mov

**Comment by sturlan** [comment]
Yes, so sorry for false positive.
I did not manage to repeat the problem on any other server, so i also concluded it is a local problem
