### ISSUE TITLE
[9.0] DE Transifex Work Issue (already reviewed terms)

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#10500]
Sofern es ein **Problem mit einem Begriff gibt, der bereits gesperrt ist (reviewed)**, dient dieser Fall dazu, um die Vorteile von Github Issues nutzen zu können bzw. die Kommunikation zu erleichtern (Screenshot zur Darstellung von fehlerhaften Übersetzungen im Kontext).

**Bitte in solchen Fällen:**
- den Tag (#de) hinzufügen
-  einen Alternativvorschlag erstellen oder einen bereits vorgeschlagenen Begriff votieren
- einen Screenshot mit etwaigen zusätzlichen Begründungen hier posten
- diesen Kommentar (Klick auf das Datum des Kommentar und URL kopieren) auf Transifex beim besagten Begriff posten z.B.: `https://github.com/odoo/odoo/issues/9480#issuecomment-163139334`

Bitte stets das **komplete Browserfenster** als Screenshot hochladen.

Zusätzliche Informationen sind hilfreich (Auflösung, Browser, etc.)

**Comment by treviser** [comment]
![selection_145](https://cloud.githubusercontent.com/assets/1814941/12377152/206cb894-bd13-11e5-84de-126fb2b12cf0.png)

**Comment by treviser** [comment]
![selection_146](https://cloud.githubusercontent.com/assets/1814941/12377180/e5349462-bd13-11e5-8707-5839d334fc41.png)

**Comment by treviser** [comment]
![selection_147](https://cloud.githubusercontent.com/assets/1814941/12377193/919c763e-bd14-11e5-9fa7-f6c5aa72244b.png)

**Comment by treviser** [comment]
Ich habe es jetzt ausprobiert. Ein Bild wird im Comment auf Transifex als Thumbnail angezeigt und kann durch Anklicken in Originalgrösse angeschaut werden. Wir müssen hier auf Github also nicht zusätzliche Kommentare schreiben sondern können es einfach als Bildablage "missbrauchen". 

So kann man nämlich einen Screenshot gleich für verschiedene Übersetzungsbegriffe verlinken, das spart Arbeit.

Siehe:
![selection_148](https://cloud.githubusercontent.com/assets/1814941/12377254/42154b2e-bd17-11e5-8bed-8454332c8124.png)

**Comment by wtaferner** [comment]
Passt, theoretisch kann man hier auch alte und nicht mehr benötigte Kommentare editieren (alle Bilder in einem Kommentar, womit man nicht jedes Mal einen neuen Kommetar aufmachen muss (führt zu einer Benachrichtigung der Subscriber).

**Comment by treviser** [comment]
![selection_149](https://cloud.githubusercontent.com/assets/1814941/12377498/c0af7b86-bd20-11e5-88df-1231a3bf0219.png)

**Comment by treviser** [comment]
![selection_150](https://cloud.githubusercontent.com/assets/1814941/12378163/2e1727b8-bd36-11e5-993f-1379b59e6383.png)

**Comment by treviser** [comment]
![selection_152](https://cloud.githubusercontent.com/assets/1814941/12378485/69bf9724-bd3f-11e5-9ef0-357a5a4bc9e9.png)

**Comment by mart-e** [comment]
Hi,

I have not followed the German discussion on Transifex (I saw my name in one ;-)) but I guess this is the place where you reports wrongly translated terms. Right?

**Comment by wtaferner** [comment]
Hi Martin,
Right, we abuse a little bit Github as a ressource for screenshots to enable a more efficient workflow between translators and reviewers :-)

Might be a workflow which could be adapted by other translation teams...

**Comment by mart-e** [comment]
No problem, go for it, it's true Transifex is not very efficient for long discussions.

**Comment by wtaferner** [comment]
Hehe, not even for short discussions ;-) and my aim was to have as little discussions as possible to transport the message and the best translation :-)

**Comment by treviser** [comment]
Es wird Zeit, die unsäglichen Übersetzungen in der Buchhaltung aufzuräumen!!!
Fangen wir an mit den Account Types:
![selection_159](https://cloud.githubusercontent.com/assets/1814941/13201938/ef96ea8e-d886-11e5-9922-8832c17a94cb.png)
![selection_158](https://cloud.githubusercontent.com/assets/1814941/13201936/ef94419e-d886-11e5-85ed-1b87cd517b46.png)
![menu_157](https://cloud.githubusercontent.com/assets/1814941/13201937/ef944874-d886-11e5-9789-d37187f8dda5.png)
![menu_156](https://cloud.githubusercontent.com/assets/1814941/13201935/ef94493c-d886-11e5-8a01-675d0f48c6b3.png)

**Comment by treviser** [comment]
![menu_162](https://cloud.githubusercontent.com/assets/1814941/13211536/5ab25d5a-d939-11e5-85a8-65800c6f669a.png)
![menu_161](https://cloud.githubusercontent.com/assets/1814941/13211535/5ab0a0d2-d939-11e5-8732-b300013e507c.png)

**Comment by Yenthe666** [comment]
Hi @treviser, @wtaferner and @mart-e is this issue still open and active or can it be closed? :smile:

**Comment by wtaferner** [comment]
@Yenthe666 
It is a helper issue, so please keep it open...in case the issues are down to 1.000 I will close it myself personally to celebrate 999 ;-)

**Comment by Yenthe666** [comment]
@wtaferner ok I'll keep it open. Also, is this a challenge? :wink:

**Comment by treviser** [comment]
Leave it open, soon I'll start again flooding it :-)

**Comment by wtaferner** [comment]
@Yenthe666 
Well, it is :wink: 

Although I doubt you and Daniel can make the difference but maybe an army of devs might be able to clean up the issue pile together with Odoo SA. It is like always a matter of priority :wink:

So, keep on fighting and good luck! :+1: 

@treviser 
As long it makes it easier to communicate you are my most important ally to improve quality this way...

**Comment by Yenthe666** [comment]
@wtaferner well, atleast it is going in the right way:
![image](https://cloud.githubusercontent.com/assets/6352350/15471233/35e0b4e6-20f5-11e6-8a7b-2b8115c6ad4c.png)
That is probably about the first time more issues are being closed than opened. :smile: 
But yes just me and Daniel can't handle the mass influx of reports on our own I'm afraid. Just trying to keep it from going out of proportion. :smile:

**Comment by treviser** [comment]
@Yenthe666 : Good job!

**Comment by treviser** [comment]
@wtaferner : I'm glad to help, in many areas the translation is in a miserable shape :-(

**Comment by Yenthe666** [comment]
@treviser and @wtaferner are you guys talking about missing translations? As in source terms that are not available to translate on Transifex?
If that is the case please post them all at this topic and I'll make sure somebody from Odoo handles all of them.

**Comment by treviser** [comment]
It is less the problem of missing translations, but more of a mysterious mistake when transporting translations to 9.0 and after that many terms were translated disastrously wrong but nevertheless reviewed and now we have quite a mess.

**Comment by Yenthe666** [comment]
Why don't one of you guys fix them on Transifex? It would take at most 7 days for the correct translations to be merged in Odoo 9.

**Comment by wtaferner** [comment]
@Yenthe666 
Everything is under control here...read the topic and you know what it is about...it is a working issue nothting to do with Odoo code here...

**Comment by treviser** [comment]
I'm not a reviewer, so I have to report wrong translations, and the reviewers only believe me if I deliver the proof by documenting screenshots... :-)

**Comment by Yenthe666** [comment]
Hmm when you don't have the reviewer rights it is a bit annoying yes.. :-)
Well I'll leave this open, too bad somebody has merged in so many bad translations.

**Comment by treviser** [comment]
![selection_242](https://cloud.githubusercontent.com/assets/1814941/17455760/74a00f3a-5bc2-11e6-9276-8b4711ce02a8.png)

**Comment by treviser** [comment]
![selection_250](https://cloud.githubusercontent.com/assets/1814941/17521806/00147c6a-5e55-11e6-82e7-e26a58ac5563.png)

**Comment by treviser** [comment]
![selection_251](https://cloud.githubusercontent.com/assets/1814941/17664638/d5d79fea-62f5-11e6-96c3-2625a46b0c17.png)

**Comment by treviser** [comment]
![menu_350](https://cloud.githubusercontent.com/assets/1814941/20858209/d25f867a-b93f-11e6-9f21-492c2e6c2a87.png)

**Comment by treviser** [comment]
![menu_358](https://cloud.githubusercontent.com/assets/1814941/20880048/a38fad82-bad6-11e6-8f69-fdf78651dd05.png)

**Comment by wtaferner** [comment]
As @treviser is now able to review himself and probably no one else is aware of this issue I close it.
