### ISSUE TITLE
Odoo 16 - Broken WSGI (Missing Code/Files)

### ISSUE THREAD

**Issue by kgix-jdargie** [odoo/odoo#105190]
**Impacted versions:** Odoo 16

**Steps to reproduce:** Deploy Odoo 16 via WSGI/Passenger and attempt to load website.

**Current behavior:** Odoo is throwing errors, relating to AttributeError related to module _odoo.service_ not having any attributes _wsgi_server_.

Specifically:
`AttributeError: module 'odoo.service' has no attribute 'wsgi_server'`

This appears to be caused by Odoo removing certain python files in the Odoo v16 code release. 

Namely, if we look at the odoo-wsgi.example.py file (Ref: https://github.com/odoo/odoo/blob/16.0/setup/odoo-wsgi.example.py), the Odoo applications initialized using the following two lines of code (Lines 41 - 43):

`application = odoo.service.wsgi_server.application`
`odoo.service.server.load_server_wide_modules()`

When reviewing Odoo v15 Repo, we can see that wsgi_server python files exist: 
https://github.com/odoo/odoo/tree/15.0/odoo/service
https://github.com/odoo/odoo/blob/15.0/odoo/service/wsgi_server.py

These files do not exist within Odoo v16 Repo:
https://github.com/odoo/odoo/tree/16.0/odoo/service

Yet, the application is still attempting to locate the file!

**Expected behavior:** Missing files should be redeployed to the Repo, allowing for Odoo v16 WSGI functionality to work.

**Comment by Julien00859** [comment]
The application entrypoint has been moved from `odoo.service.wsgi_server.application` to `odoo.http.root`.

https://github.com/odoo/odoo/pull/105434
https://github.com/odoo/documentation/pull/2927

**Comment by Julien00859** [comment]
opw-3018684

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/odoo/pull/105715
