### ISSUE TITLE
[9.0] --auto-reload not supported any more?

### ISSUE THREAD

**Issue by morphace** [odoo/odoo#10517]
If I try to use odoo.py with the --auto-reload option, I get an invalid option error. Also, pyinotify is not any more used in the source, as opposed to Odoo 8.
Is this option not supported any more?

**Comment by lucasdiedrich** [comment]
@morphace , did you found any workaround? This auto-reload option should be very useful while in dev mode.

**Comment by morphace** [comment]
@lucasdiedrich, no I didn't find a workaround. Unfortunately... interestingly #10697 states that --auto-reload is the default behavior now. Should give it a try...

**Comment by lucasdiedrich** [comment]
@morphace, i have found the problem, indeed auto-reload is default, but i noticed that when i started my server with --dev option, it showed an warning saying that Python "watchdog" lib was missing, after i installed the auto-reload started to work.

I installed with: 

> easy-install watchdog

Take a try.
