### ISSUE TITLE
[8.0] website_hr_recruitement multilingual problem

### ISSUE THREAD

**Issue by leemannd** [odoo/odoo#10529]
Hello,
We have an issue with the website_hr_recruitment module. Globally the website is multilingual. It is possible to edit all the pages in order to have them translated. But this doesn't work with the "website_hr_reruitment" module.
Steps to reproduce:
1. Create a job offer
2. Publish it on the website
3. Go on the website with the default language
4. The job offer is editable
5. Switch language
6. The job offer is not editable and it is not possible to translate it

**Comment by mart-e** [comment]
Probably temporary bug with the website translator. Now it's working fine.
Let me know if you still have issues

**Comment by leemannd** [comment]
@mart-e It's no temporary bug. It's working fine now, but it has been fixed here https://github.com/odoo/odoo/commit/0c3cd7cbb48c2291c2e79ce6907547b79342ad91
