### ISSUE TITLE
Default journal_id in hr.payslip not work

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#10521]
1) Steps to reproduce the issue you have observed
Create a new payslip in Payroll -> Employee Payslips

Can find a demonstrative video here:
https://youtu.be/5H-3Hg6R89o

2) The result you observed
The default value to journal is load, but inmediatly disappears, and the field have a default in the model

 3) The result you expected 
I hope that the journal is set when I create a new Payslip

4) The Odoo version
1812b8f337962dd059a2adb69d73cc48b31b5914

**Comment by simongoffin** [comment]
closed with c790464fd62e7415589d2ed230e5c3c0e2a8cc4a
