### ISSUE TITLE
[8.0][BUG] CRM deduplicate partners with same VAT will destroy all contacts

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#10534]
Hello,

Tested in http://126022-8-0-1812b8.runbot8.odoo.com

This is a bug as Odoo consider duplicated a company with their contacts when VAT is set only in the company.
- Lets say we have a company with VAT:

![19-01-2016 14-19-53](https://cloud.githubusercontent.com/assets/8736623/12419693/fd41fa72-beb7-11e5-9cfe-0daeed8abaeb.png)
- As we can see, contacts of Agrolait doesn't have VAT number as Odoo doesn't let me write any data on Accounting tab

![19-01-2016 14-22-52](https://cloud.githubusercontent.com/assets/8736623/12419723/3606abc8-beb8-11e5-826d-f6f69ddacea5.png)

But when we you run CRM utility for deduplicate in Sales - Tools - Deduplicate contacts Odoo say that all are duplicated.
## ![19-01-2016 14-25-04](https://cloud.githubusercontent.com/assets/8736623/12419781/775de56e-beb8-11e5-8075-1284d9101407.png)

![19-01-2016 14-25-38](https://cloud.githubusercontent.com/assets/8736623/12419817/abe2356a-beb8-11e5-9109-65190c87e467.png)

Expected is that Odoo check by VAT only betwen partners which VAT is set manually.

Thanks

**Comment by rafaelbn** [comment]
After all our work @pedrobaeza please take care of this issue

**Comment by pedrobaeza** [comment]
You have to mark also the "Is company" check. This way, they are not considered together, but there's no way to filter out contacts or companies in the selection dialog, which is a desirable feature.

**Comment by rafaelbn** [comment]
Closing to old
