### ISSUE TITLE
[8.0] Barcode scanning does not work from barcode interface

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10537]
**No action happens when scanning a barcode in the barcode interface**

Impacted versions:
- 8.0

Steps to reproduce:
1. Create a new product named 'Bonbons' with a price and give it the barcode 7610700600054
   For example:
   <img src="http://i.imgur.com/OCufUPp.png" alt="Product example"/>
2. Create a new transfer from Warehouse > All operations and add this product to it. For example:
   <img src="http://i.imgur.com/g54TlEt.png" alt="Operations example"/>
3. Mark the transfer as To do.
4. Click on the barcode to open up the barcode interface:
   <img src="http://i.imgur.com/mr9IxL9.png" alt="Barcode interface click"/>
5. Take your barcode scanner and scan the product.

Current behavior:
- The scanned product is not changing anything in the barcode interface. The amount is not changed and no action is done

Expected behavior:
- The counter for the number of scanned products goes up by one for the just scanned product.

**Comment by Yenthe666** [comment]
@mart-e I was just wondering. Could you (or somebody else) tell me if I am doing this correctly or if I am just messing this up? I'm not sure if I'm doing this correctly. :smile: 
I'm guessing it is a bug since I wouldn't really see another way..

**Comment by spadae22** [comment]
@Yenthe666 Hi, I have tried the interface and it is not what it seems. We have 100 machines with serial numbers incoming. Since the product is full trace, you could goto the delivery order, click the barcode icon. Now you would think you could scan the product barcode once, then scan all serial numbers and watch the countdown, does not work, you have to change lot each time, so I just import with a speadsheet. I wish this worked! 

![screen shot 2016-01-19 at 10 50 03 am](https://cloud.githubusercontent.com/assets/7741100/12423709/ce5452f4-be9a-11e5-9e40-21fdd794a062.png)

**Comment by Yenthe666** [comment]
@spadae22 this has to be a bug then. Why would it otherwise be called barcode interface if you can't even scan those? The whole implementation of this part wouldn't have any sense if you can't scan barcodes there.
This would be a major improvement if you could scan the products with a barcode scanner and see the counters going up.

**Comment by spadae22** [comment]
@Yenthe666 I agree see if @mart-e can chime in, we have a enterprise contract, so maybe I am confused also, but it would be great so the warehouse could scan these in,

**Comment by mart-e** [comment]
@Yenthe666 @spadae22 sorry I can not help you much on this, I don't know exactly the required configuration and don't have a scanner here to test it but I would expect the same result as you. According to a quick look in the code, it should match on locations, product or package code.

Maybe @csnauwaert or @jco-odoo knows better but anyway, for these questions I advise you to contact the support where appropriate people will be able to check it.

**Comment by spadae22** [comment]
It is just the way it works as coded. I have tested and does not work as expected. What does work for outgoing products, you can scan the barcode right into the serial number on the transfer. I have tested in ubuntu, OS X Chrome, IOS Chrome.

<img width="1187" alt="screen shot 2016-01-20 at 1 00 07 am" src="https://cloud.githubusercontent.com/assets/7741100/12441082/686e469e-bf11-11e5-97e8-492fb9ee3b62.png">

**Comment by spadae22** [comment]
I would as for importing serial numbers, hundreds or thousands, we get a spreadsheet from the manufacture with all serial numbers. Import the serial numbers, create a inventory adjustment spreadsheet.  Then I turn off traceability on each product that I need to adjust. Do the bulk transfer. Then import the inventory adjust from bulk to serial numbers. Better than taking the skids apart and typing or scanning for bulk.

<img width="773" alt="screen shot 2016-01-20 at 1 07 34 am" src="https://cloud.githubusercontent.com/assets/7741100/12441224/cd32778e-bf12-11e5-8ec3-17a4ddea49c2.png">
<img width="1425" alt="screen shot 2016-01-20 at 1 13 06 am" src="https://cloud.githubusercontent.com/assets/7741100/12441243/025804e2-bf13-11e5-9fbc-496d18e8b9bd.png">

**Comment by Yenthe666** [comment]
@spadae22 sadly that isn't really an option for our customer, they or not tech savvy at all either so that is another major downside.
I'll see what @csnauwaert and @jco-odoo have to add to this since I'm also still wondering why on earth there would be a barcode interface otherwise.

**Comment by spadae22** [comment]
@Yenthe666 I agree, at this point with 8.0 I am sure it will go as a "feature" I already fought this battle and lost. In v9 the now have the option of serial number and lot. v8 treats them the same, so you need to split the incoming shipment. This is the "official documentation" https://www.odoo.com/fr_FR/forum/how-to/warehouse-management-6/how-can-i-specify-unique-serial-numbers-for-the-same-product-during-incoming-shipment-registration-55446

**Comment by spadae22** [comment]
@Yenthe666 I am sure we are going to develop a module for this as we already have 25,000 lines of code in custom modules, so we are used to it.

**Comment by csnauwaert** [comment]
@Yenthe666 I tried with a barcode scanner the exact same process you did on version 8.0 and it works as intended on my end. When I open the barcode interface and scan the barcode of a product, it add "1" to the count of scanned product. Can you please check the following: open any text editor and scan your barcode, is the value printed the same as the one you entered on the product EAN? Depending on the barcode scanner, sometimes it can behave differently.
@spadae22 I understand your use case but I must unfortunately agree that it is considered as new feature in version 8, and since the barcode interface has been removed and replaced by a completely new module "barcode" in version 9. We probably won't add that new feature for version 8. I don't know if that feature is implemented in v9, @jco-odoo knows that module better than me, but if it is not the case, I don't see any reason not to add it for the next version. 

Cheers

**Comment by Yenthe666** [comment]
@csnauwaert thanks for the feedback!
As to to your question: that was the first thing I tested, I was thinking the same as you. When I open up a notepad I will get exactly the same barcode printed as the one that is entered on the product. There are no spaces in the barcode, no space behind it and no enter either. There just doesn't seem to happen any action from Odoo.

**Comment by csnauwaert** [comment]
@Yenthe666 Can you please try the following:

- open the barcode interface (in chrome if you have it), in the url add '?debug' between the '/' and the '#' character. It should look somehow like that: "/barcode/web/?debug#action=stock.ui&picking_type_id=1". Then press enter, it will reload in debug mode (which will give you access to the javascript code).
- If you are using chrome: press F12 to open the dev tools (or right click "inspect element").
- Click on "sources" tab, unfold the folder "stock/static/src/js" and double click on "widgets.js". This will show you the source code for the barcode interface.
- Go to the line 847: inside the scan function, add a line with the following code just before var self=this:
"console.log(ean);"
![screenshot from 2016-01-21 11 38 08](https://cloud.githubusercontent.com/assets/7338483/12478426/24e45ce0-c035-11e5-81b4-8d086c90b7cd.png)

- Press ctrl+s to save then go to the "console tab". Focus the barcode interface (click anywhere on the barcode interface) then try again scanning your product with the scanner: you should see in the console below the value of what has been scanned (it should be the value of your barcode)
![screenshot from 2016-01-21 11 38 24](https://cloud.githubusercontent.com/assets/7338483/12478432/2c9ec1e6-c035-11e5-9f61-bb9e7fb40b55.png)

If you don't see your barcode in the console, it probably means that your scanner has a delay larger than 100ms between 2 characters. Please note that the value printed should not be different from the EAN you put on your product.

Thanks.

**Comment by Yenthe666** [comment]
Hi @csnauwaert,

We've encountered the same behaviour on Odoo 9 (and Odoo 10) in the barcode interface.
Odoo cannot interpret the barcode because the delay between the characters is too slow. We've tested your procedure / example and this is the result:
![image](https://cloud.githubusercontent.com/assets/6352350/22776367/acce6b92-eeaf-11e6-83e9-1f9de76d193a.png)
The log:
![image](https://cloud.githubusercontent.com/assets/6352350/22776401/c9b04c44-eeaf-11e6-9195-b8db8bad6c8e.png)

Could this be looked at again or can the time be changed?
P.S: We've tested this with a scanner from the brand Symbol New York and the MFD = 15NOV06A

Regards,
Yenthe

**Comment by csnauwaert** [comment]
Hello @Yenthe666 I haven't worked on the barcode interface in V9 so I don't know how it works, maybe @sle-odoo will know better?

Best regards

**Comment by Yenthe666** [comment]
@sle-odoo could you look at this please?

**Comment by sle-odoo** [comment]
@Yenthe666 hi, could you try to increase the value of [this variable](https://github.com/odoo/odoo/blob/9.0/addons/barcodes/static/src/js/barcode_events.js#L29) and see if it fixes your issue?

If so, we could probably increase it by default (something like 100 or 150ms doesn't seem exaggerated) or make it configurable.

thank you
