### ISSUE TITLE
[7.0, 8.0] Module load order bug

### ISSUE THREAD

**Issue by bwrsandman** [odoo/odoo#1053]
## Description

Odoo doesn't seem to follow the correct dependency graph when installing and
testing modules which depend on each other. Instead, it seems to install them
in alphabetical order if their dependencies are satisfied.

This causes a problem when trying to write good unittests for project under one
module which depends on two module which will conflict with each-other if
initialized in the wrong order.

4 modules which demonstrate this bug source at the end of report(also available at https://github.com/savoirfairelinux/Odoo-loading-dependency-bug):

### **parent_module**

Topmost module, dependency list lists **b_module** and **a_module** in that order

### **b_module** 

Has a unittest which tests the module in **parent_module** and with whatever 
modifications to the model are made in **grandchild_module**.
This model only depends on **grandchild_module** and is meant to be functional 
on its own, independently from **a_module**, but can work with it installed.
The unittest, however do not take into account **a_module** as it is not a 
dependency.

### **a_module**:

Add a required field to the model in **grandchild_module**.
Lists only **grandchild_module** as its dependencies and is meant to be 
functional on its own, independently from **b_module**, but can work with it.

### **grandchild_module** 

Defines an example module. Has no dependencies.

## How to reproduce

Install **parent_module** with tests enabled using

```bash
openerp-server -d test -i parent_module --test-enable --log-level=test
```

## Expected behaviour

Odoo goes down the dependency graph finding that once **grandchild_module** is
installed, **b_module**, **a_module** can be installed and installs them in the
order defined by **parent_module**.

When **b_module** installs, it runs its tests and passes. Then, **a_module**
installs and adds the required field.

## Actual behaviour

Odoo goes down the dependency graph finding that once **grandchild_module** is
installed, **b_module**, **a_module** can be installed and installs them in
alphabetical order.

That means **a_module** is installed first, adding a required field, then 
**b_module** is installed and triggers its tests. The tests run into an 
exception due to the required field being set from **a_module**. 

## Source
*at https://github.com/savoirfairelinux/Odoo-loading-dependency-bug*

### **grandchild_module** 

Defines an example module. Has no dependencies.

#### `__init__.py`
```python
from . import example_model
```

#### `__openerp__.py`
```python
# -*- encoding: utf-8 -*-
{
    'name': 'Grandchild Module',
    'version': '0.1',
    'author': 'Savoir-faire Linux',
    'maintainer': 'Savoir-faire Linux',
    'website': 'http://www.savoirfairelinux.com',
    'license': 'AGPL-3',
    'category': 'Others',
    'description': "Adds example model",
    'installable': True,
}
```

#### `example_model.py`
```python
# -*- encoding: utf-8 -*-

from openerp.osv import orm, fields


class example_model(orm.Model):
    _name = 'example.model'
    _columns = {
        'name': fields.char('Name'),
    }
```

### **b_module** 

Has a unittest which tests the module in **parent_module** and with whatever 
modifications to the model are made in **grandchild_module**.
This model only depends on **grandchild_module** and is meant to be functional 
on its own, independently from **a_module**, but can work with it installed.
The unittest, however do not take into account **a_module** as it is not a 
dependency.

#### `__init__.py`
```python
```

#### `__openerp__.py`
```python
{
    'name': 'Module B',
    'version': '0.1',
    'author': 'Savoir-faire Linux',
    'maintainer': 'Savoir-faire Linux',
    'website': 'http://www.savoirfairelinux.com',
    'license': 'AGPL-3',
    'category': 'Others',
    'description': """
Has a unittest which tests the module in **parent_module** and with whatever 
modifications to the model are made in **grandchild_module**.
This model only depends on **grandchild_module** and is meant to be functional 
on its own, independently from **a_module**, but can work with it installed.
The unittest, however do not take into account **a_module** as it is not a 
dependency.
""",
    'depends': [
        'grandchild_module',
    ],
    'installable': True,
}
```

#### `tests/__init__.py`
```python
from . import test_example_model

checks = [test_example_model]
```

#### `tests/test_example_model.py`
```python
from openerp.tests.common import TransactionCase


class test_example_model(TransactionCase):
    def setUp(self):
        super(test_example_model, self).setUp()
        self.model = self.registry("example.model")

    def test_create(self):
        self.model.create(self.cr, self.uid, {'name': 'test'})
```

### **a_module**:

Add a required field to the model in **grandchild_module**.
Lists only **grandchild_module** as its dependencies and is meant to be 
functional on its own, independently from **b_module**, but can work with it.

#### `__init__.py`
```python
from . import example_model
```

#### `__openerp__.py`
```python
{
    'name': 'Module A',
    'version': '0.1',
    'author': 'Savoir-faire Linux',
    'maintainer': 'Savoir-faire Linux',
    'website': 'http://www.savoirfairelinux.com',
    'license': 'AGPL-3',
    'category': 'Others',
    'description': """
Add a required field to the model in **grandchild_module**.
Lists only **grandchild_module** as its dependencies and is meant to be 
functional on its own, independently from **b_module**, but can work with it.
""",
    'depends': [
        'grandchild_module',
    ],
    'installable': True,
}
```

#### `example_model.py`
```python
from openerp.osv import fields, orm


class example_model(orm.Model):
    _inherit = 'example.model'
    _columns = {
        'required_field': fields.char('Required Field', required=True),
    }
```

### **parent_module**

Topmost module, dependency list lists **b_module** and **a_module** in that order

#### `__init__.py`
```python
```

#### `__openerp__.py`
```python
{
    'name': 'Parent Module',
    'version': '0.1',
    'author': 'Savoir-faire Linux',
    'maintainer': 'Savoir-faire Linux',
    'website': 'http://www.savoirfairelinux.com',
    'license': 'AGPL-3',
    'category': 'Others',
    'description': """Topmost module, dependency list lists **b_module** and **a_module** in that order""",
    'depends': [
        'b_module',
        'a_module',
    ],
    'installable': True,
}
```

**Comment by agb80** [comment]
@bwrsandman do you found any solution for this problem? 

I'm trying to create a module that replace invoice workflow for a series of signals based on blinker, on our test the result are faster compute an a more reliable behavior, but don't know how to make a monkey patch for change some functions.

**Comment by bwrsandman** [comment]
Odoo's official response to me was that it won't be fixed

**Comment by agb80** [comment]
No surprise, thanks any way @bwrsandman would look into a different way to accomplish this task

**Comment by sle-odoo** [comment]
Closing as https://github.com/odoo/odoo/issues/1053#issuecomment-104391309 answered the actual position of Odoo on this matter.
Regards
