### ISSUE TITLE
[9.0]/[8.0]Product Variants attributes  saving issue

### ISSUE THREAD

**Issue by johnwdmems** [odoo/odoo#10539]
Once we remove some attributes on one attribute, and there is only one attribute defined on this line, when do saving, I got one error message: 
Error! It is not allowed to choose more than one value for a given attribute

Please see the attachment for detail, I found the reason and fix it on my side now.
[Product template bug1.docx](https://github.com/odoo/odoo/files/96962/Product.template.bug1.docx)

**Comment by aisopuro** [comment]
I've encountered the same problem with a build from 2016-03-18. @johnwdmems, could you please post the source files that are affected and where (what lines) you changed? I think you mean the function `_check_attribute_value_ids` in [product/product.py](https://github.com/odoo/odoo/blob/9.0/addons/product/product.py#L1001). 

The change in question is from commit 1466a0063f631ea086c57ec6654b92e399b494d3 by @nim-odoo, maybe he could shed some light on this?

**Comment by nim-odoo** [comment]
That should have been solved with https://github.com/odoo/odoo/commit/018b53b
