### ISSUE TITLE
9.0 Creation of vendor bill line -> select sales price instead of cost price

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10546]
When we create a vendor bill, NOT from a purchase order
It should take the supplier price, and if not, the cost price  but NOT the sales price !

**Comment by sle-odoo** [comment]
Hi,
I think it's really a detail. If you're creating a vendor bill without a linked purchase order, you should correctly check all the values.

We noted the feedback though, thanks.

Regards
