### ISSUE TITLE
Public Price - new Product (template) - after saving 1st time value is always 1 in trunk version

### ISSUE THREAD

**Issue by BusinessTec** [odoo/odoo#1054]
Each time while creating new product  which ever value is entered for Public Price after saving always value 1.00 is saved/display.
After editing the product again changes are taking effect - it looks like only initial value is affected.

**Comment by Yenthe666** [comment]
Hi @BusinessTec,

Thanks a lot for your report! This is however wanted behaviour and has been like this in atleast the last 3 versions.

Regards,
Yenthe
