### ISSUE TITLE
9.0 Credit notes (refund) creation ?

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10545]
How can we create a credit notes for a customer or supplier NOT from an existing invoice.
Can't find the menu... 
If we make a 'create' on invoice, there is no way to select 'refund'...
neither accounting journal, as it is now the same journal for invoice and return.

**Comment by bene1505** [comment]
Go to accounting Dashboard, click on More on the Customer Invoices, there you'll get the New Refund button.  

 
<img width="1370" alt="create new refund" src="https://cloud.githubusercontent.com/assets/12964307/12579264/fe9cf1fa-c426-11e5-83f0-3037e4293168.png">

**Comment by itautomationo** [comment]
1) Go to the configuration menu, and activate the developer module.

2) Now go to "Menu items"

3) Create a new menu item, and call it "invoice refound", your father may be the one you choose, but I recommend you use "Accounting / Sales", and most importantly: Link to this menu a window action called "invoice" refunds ".

4) Ready

If what you need is also to have a tree view that shows you only invoice refunds, you must add the tree option to the created menu, and define a tree view with the elements you want.

**Comment by Yenthe666** [comment]
I believe this has been answered.
In the future you're better of asking these questions on the official help forum (odoo.com/help) instead of here. The Github tracker is for bugs only, not for asking questions.
