### ISSUE TITLE
[9.0] HR Expense with > 1 taxes selected, crash when Post Journal Enteries

### ISSUE THREAD

**Issue by kittiu** [odoo/odoo#10543]
Simply create an Expense with 2 taxes. During post journal enteries, following error appear. Code assume only 1 tax !!!

  File "/home/odoo/runbot/extra/runbot/static/build/126314-9-0-44ac79/openerp/models.py", line 5384, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.tax(8, 9)

**Comment by kittiu** [comment]
![050](https://cloud.githubusercontent.com/assets/1973598/12443727/92713f3e-bf8c-11e5-8948-7091adfe7ed2.png)

**Comment by kittiu** [comment]
I think the fix is using 'ids', instead of 'id',
            account_move[-1]['tax_ids'] = expense.tax_ids.id
to
            account_move[-1]['tax_ids'] = expense.tax_ids.ids

**Comment by Yenthe666** [comment]
Hi @kittiu,

Thanks a lot for the bug report.
This bug has been fixed in the meanwhile though:
![image](https://user-images.githubusercontent.com/6352350/34992013-f59dd74e-facb-11e7-90c1-cf850ce1d16d.png)

Please update your Odoo source code in order to fix this issue on your Odoo.

Regards,
Yenthe
