### ISSUE TITLE
[8.0] new created move Lines are not linked to bank statement

### ISSUE THREAD

**Issue by msteinfeld** [odoo/odoo#10553]
Impacted Versions:
- 8.0

Steps to reproduce:

1.Create Bank Statement and reconcile alle items
2.See that you forgot the tax on input
3. Cancel the move
4. Make a new line for input tax and justifiy credit and debit
5. save and book
6. go back to statement and look at belonging moves (right top corner smart button)

Current behavior:
- debit and credit for all is not equal
- new line for input tax is not linked

Expected behavior:
- new row for input tax is linked with bank statement OR
- new row can be linked via UX with bank statement

**Comment by Yenthe666** [comment]
Hi @msteinfeld,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
