### ISSUE TITLE
Outdated module in requirements.txt

### ISSUE THREAD

**Issue by Frisle** [odoo/odoo#105527]
Psycopg2==2.8.5 causing ImportError when trying to launch the server,  but new one Psycopg2==2.9.5 working just fine

**Comment by Xavier-Do** [comment]
Can you give us more information about the versions you are using (odoo, operating system, ....)

**Comment by Frisle** [comment]
I am using OS Windows 10 and 16.0 (default) of Odoo. Currently i am working on test case for a job and found this issue during preparing enviroment for developing new modules on my own copy of the repository.

```
Traceback (most recent call last):
  File "C:\Users\wda61\odoo\odoo-bin", line 5, in <module>
    import odoo
  File "C:\Users\wda61\odoo\odoo\__init__.py", line 113, in <module>
    from . import modules
  File "C:\Users\wda61\odoo\odoo\modules\__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry, neutralize
  File "C:\Users\wda61\odoo\odoo\modules\db.py", line 4, in <module>
    from psycopg2.extras import Json
  File "c:\Users\wda61\odoo\venv\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
```

Changing version to 2.9.5 resolves this issue. Version of the module has been changed early already due to the same problem

**Comment by Xavier-Do** [comment]
Also, the 16.0 windows requirement is 2.8.6 not 2.8.5. (since 3ed0f6df8b43838c57a5360c4202746a542cbe0e)
 
> Changing version to 2.9.5 resolves this issue. Version of the module has been changed early already due to the same problem

We cannot change blindly a requirement like that, we need a good understanding of what is the case of the issue and implication of changing that. 

We managed to install 16.0 on windows 10 a few weeks ago  with this version issue. I'm just not sure if we didn't use psycopg2-binary instead, I don't remember why but this is maybe because we were using python 3.10. 

What is your python version?

**Comment by Frisle** [comment]
I am using Python 3.10.2. Instalation from requirements.txt was succesful. But when i try launch server via:

`python odoo-bin -r db_login<login> -w db_pass<pass> -d db_name`

The ImportError is occured. So changin version of psycopg2 is resolve the problem and server launch was succesful. Altough i monitored issues list and did not find similar problem.
