### ISSUE TITLE
[8.0] - Cancel Invoice included in a Payment Order

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#10556]
Steps to reproduce.
1) install account_payment & account_cancel
2) set Allow Cancelling Entries to TRUE on your purchase journal
3) create a supplier invoice, validate it and include it into a payment order
4) try to cancel the supplier invoice 

=>

Error!
You cannot cancel an invoice which has already been imported in a payment order. Remove it from the following payment order : xxx.

Can this be changed to a non-blocking warning?

**Comment by jdegoy** [comment]
This is the comment from the standard code to explain why it was added;

# Forbid to cancel an invoice if the related move lines have already been
# used in a payment order. The risk is that importing the payment line
# in the bank statement will result in a crash cause no more move will
# be found in the payment line

Why didn't you handle the problem in the import lines logic for the bank statement?

**Comment by Yenthe666** [comment]
Hi @jdegoy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
