### ISSUE TITLE
[9.0] Traceback on the stock root menu

### ISSUE THREAD

**Issue by sylvain-garancher** [odoo/odoo#10558]
A mistake in HTML tags has been added in the fr.po translation file of the stock module : https://github.com/odoo/odoo/blob/c7b01fea24fdc06c322f8907ebc1442a4eae3a3b/addons/stock/i18n/fr.po#L6064
The `<i>` tag should be closed by `</i>` instead of another `<i>`

Steps to reproduce the bug :
- Create an empty database
- Add the french language
- Install the stock module
- Set the current user's langauge to French
- Go to the inventory root menu

Expected : Everything works

Issue : An "ending tag mismatch" traceback appears

cc @mart-e

**Comment by gurneyalex** [comment]
@mart-e fixed this in transifex 5 days ago. But a forced sync of the translations would be nice, since it makes Odoo 9's stock difficult to use in french at the moment.

**Comment by mart-e** [comment]
@sylvain-garancher indeed already fixed. It should have been synchronised but seeing the logs, we have yet, been throttled with the quite low API limit from Transifex before reaching stock :-/
Relaunching the synchronisation, should be done soon
