### ISSUE TITLE
[15.0] French translation

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#105643]
@mart-e 

Impacted versions:
15.0

Steps to reproduce:
On `website_sale_delivery` > Try to translate from transifex

Current behavior:
Not possible to suggest translations

Expected behavior:
Be able to suggest translations

Video/Screenshot link (optional):
https://www.transifex.com/odoo/odoo-15/translate/#fr/website_sale_delivery/333339802?q=text%3Afree

**Comment by mart-e** [comment]
Hi,

Thanks I have accepted the translation and made you a reviewer so you can accept such translations.
