### ISSUE TITLE
[16.0] Promise error when you enter to settings 

### ISSUE THREAD

**Issue by drkpkg** [odoo/odoo#105629]
Impacted versions:
16.0

Steps to reproduce:

![image](https://user-images.githubusercontent.com/972555/201507748-1389814c-6a00-4937-9d09-ac3aec3b73f6.png)
Go to settings

Current behavior:
Shows a promise error

Expected behavior:
Should show settings

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/972555/201507956-eedef458-d4fc-41da-b7d6-0dbbd02de245.png)

Support ticket number submitted via odoo.com/help (optional):
None

My odoo.conf
```conf
[options]
addons_path = /opt/odoo-16.0/addons/,/opt/extra-16/
admin_passwd = SECRET
csv_internal_sep = ,
db_host = localhost
db_user = secret
db_password = secret
db_name = False
db_maxconn = 255
db_port = 5432
db_sslmode = prefer
db_template = template0
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
limit_time_real_cron = -1
list_db = False
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile =
max_cron_threads = 2
osv_memory_age_limit = False
osv_memory_count_limit = False
pidfile =
proxy_mode = True
reportgz = False
screencasts =
screenshots = /mnt/data/screenshots
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = all
workers = 6
```

Nodejs and npm are installed well.

```
npm 8.19.2
node v16.18.1
```

**Comment by kup-odoo** [comment]
Hello @drkpkg 

I checked this in odoo runbot and locally too, 
It's working fine for me.

**Comment by drkpkg** [comment]
I try again, the problem start when I install the website module, any way to reproduce it?

**Comment by DevDorrejo** [comment]
have this issue, in container.

**Comment by Yenthe666** [comment]
I've actually had a similar issue in one of my databases too a few days ago. For me it was a view (`documents_account.view_account_move_form_inherit_documents_account`) which was loaded in the database but the app was not (or no longer) installed. For me the issue was with the app `documents_account`

**Comment by DevDorrejo** [comment]
Installing website app fix the issue.

**Comment by DevDorrejo** [comment]
Hello, i installed website app, but how can I omit the website view?

**Comment by drkpkg** [comment]
I'm closing this because the patches solve the problem, now v16 works in local and production mode.
