### ISSUE TITLE
[v9]Impossible to create a procurement from a non admin user in child company

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10572]
Hy,

Context : 
i'm working in multi company mode.
Company A, Warehous A
Company B (child of company A), Warehouse B
Wharehouse A is resupplied by warehouse B
A user userAB non admin is allowed to access to both A & B 

Expected results :
userAB could create PO from anywhere

Observed results :
As a userAB I can create a procurement order from the company A for the companyB and WareHouse B
As a userAB logged in the comanyB I can't create a ProcOrder for warehouse B :

```
Security restrictions
(Type de document : stock.warehouse, Operation : read)
```

In the code it seems to be unable to create a PO here : https://github.com/odoo/odoo/blob/9.0/addons/stock/wizard/make_procurement_product.py#L39

Additionnal tests :
- A whC has been created without interwarehouse resupplying route => userAB could create ProcOrder

What is working :
Adding this kind of rules ![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12479239/1c21ea78-c03a-11e5-9670-194bbc01c0ed.jpeg)

![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12479226/03242ab8-c03a-11e5-974f-e143f823acd5.jpeg)

allows to create procurement in the warehouseB but not propagate to anyhere

Any advice wourl be appreciated!

**Comment by flotho** [comment]
Changing all the rules as follows :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12497114/1b0d4848-c09a-11e5-9d1b-9214cccd1340.jpeg)

Make all the process worked. 
Won't it be better to user .sudo in the methods that are creating proccurements etc...

**Comment by zbik2607** [comment]
Related:
https://github.com/odoo/odoo/issues/4956
https://github.com/odoo/odoo/issues/4627

**Comment by flotho** [comment]
Hi @zbik2607 ,

I read your related post an see I'm not the only one struggling with those reservation issue.
Maybe this on https://github.com/odoo/odoo/issues/11008 is also a reservation problem. 
Quants don't seems to be reserved properly.

**Comment by Yenthe666** [comment]
@nim-odoo I see you've self assigned this, did you ever solve it? (this would be a pain to reproduce..)

**Comment by pedrobaeza** [comment]
@nim-odoo any news about this?

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
