### ISSUE TITLE
Bug in process stock picking with UoM  with ratio with long precision

### ISSUE THREAD

**Issue by uynil** [odoo/odoo#1058]
Stock picking with product with  UoM with ratio with ratio " 13.620000000038 " can not be delivered.

**_Impacted versions:**_
- log version 84e9a67cdf78db94cb7a09543c1b7ac4ad19d8b4

**_Steps to reproduce:**_
1. Create a UoM  "Pack (6 x 5 Lb)" in category "weight", with type "   Bigger than the reference Unit of Measure", ratio " 13.620000000038 "
   ![1 uom](https://cloud.githubusercontent.com/assets/1239704/3535378/686b79b6-07ff-11e4-8b90-c42e96e54402.png)
2.  Create an incoming shipment with  test product in UoM "Pack (6 x 5 Lb)".
   ![2 is_new](https://cloud.githubusercontent.com/assets/1239704/3535457/9c7a7864-0800-11e4-8571-c9a713285233.png)
3.  Confirm and receive incoming shipment. An error pops up.
   ![3 error](https://cloud.githubusercontent.com/assets/1239704/3535452/8c3d549e-0800-11e4-845c-73ec260e2310.png)

**_Current behavior:**_
-  An error will pop up. Incoming shipment can not be processed.

**_Expected behavior:**_
-  The incoming shipment can be delivered.

**Comment by Yenthe666** [comment]
Hi @uynil,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
