### ISSUE TITLE
Menu Item Action Missing

### ISSUE THREAD

**Issue by finintra** [odoo/odoo#105882]
Impacted versions:16

Steps to reproduce:
Enable Debug mode. Open Settings-Translations
Current behavior:
No menu item "Translated terms"
Expected behavior:
The menu item exist and allow to edit the translations.

This menu item was in all previous versions, on 16 is does remain in menu items, but this menu item has no action defined for it, so it is not shown to users.
Probably it is because file https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/views/ir_translation_views.xml
was not ported to version 16.
Please return back the menu item- we used it a lot
Support ticket number submitted via odoo.com/help (optional):
3071558
![photo_2022-11-16_13-26-39](https://user-images.githubusercontent.com/91319739/202214377-248500b8-3fcc-4570-b429-d990dc9dec4c.jpg)

**Comment by bosskopp** [comment]
Same issue here on Odoo.sh after migration from 15.0 -> 16.0.

Seems not to be an issue when using an i[nstance recently created](https://23597222-16-0-all.runbot162.odoo.com/) by runbot:
![odoo-translation-menu](https://user-images.githubusercontent.com/1733427/216940736-81743305-3d85-42ec-97b4-f8a8a8acfb6d.png)

**Comment by bosskopp** [comment]
@finintra What do you think about changing the title of this issue to something more specific like "[16.0] Menu item missing: Translations -> Application Terms"?

**Comment by finintra** [comment]
Received an answer from odoo that the approach to translations os changes in ver 16.

**Comment by bosskopp** [comment]
In case others are facing this issue, here's the response from Odoo:

There is no longer a Menu item that shows all the translated terms in a list as they are no longer stored this way. In Odoo 16 you may now translate directly from the form view with the new translation modal. Translated terms are now stored with the native term in the model form.
(i.e. Translations for product name are now stored directly in the name field. )
Any field that is translatable now stores JSON data representing all translations of all translated language values.

However, you may still import and export translations.

For your reference here is our documentation regarding translations in Odoo 16
See also https://www.odoo.com/documentation/16.0/developer/howtos/translations.html
