### ISSUE TITLE
[7.0][8.0][master] database.uuid

### ISSUE THREAD

**Issue by filsys** [odoo/odoo#1059]
When odoo create a database, then also create a record in ir.config.parameter with database.create.date and database.uuid keys.
If restore a dump backup odoo database into another new database and connect odoo to that database, in system parameters will see database.uuid value of first databae.
This kind of problem broke common sense of uuid and confuse admins who manage more databases in the same sistem.
May be recompute database uuid from pg OID at user autentication ?

Thanks.

**Comment by eronlloyd** [comment]
Is this still an issue with the "Generate a new database uuid" option on DB restore in 9.0?

**Comment by antonylesuisse** [comment]
Generate a new database uuid fixes this
