### ISSUE TITLE
East Timor Country Data

### ISSUE THREAD

**Issue by JawidC** [odoo/odoo#10596]
Small issue with East Timor (Timor-Leste)
The iso-code is actually TL as per: https://en.wikipedia.org/wiki/East_Timor and the dialing code is missing, should be 670.

**Comment by Yenthe666** [comment]
Hi @JawidC,

Thanks a lot for your report.
It has already been fixed partially at https://github.com/odoo/odoo/commit/bfbaaa7d1319d109018b4e77ff930dadb8211cee#diff-c935af95c0540fa947cf91a105585dd4 
This corrects the iso-code. 
As for the dialing code: I've just made a PR to fix this at https://github.com/odoo/odoo/pull/22272
