### ISSUE TITLE
Facturas de cliente pagadas en el PTV  

### ISSUE THREAD

**Issue by jsvargasr** [odoo/odoo#10601]
Cuando facturo en el PTV de odoo v9 y contabilizo y cierro la sesión, mi factura se encuentra en estado "Contabilizado" pero mi factura de cliente (en el módulo de Contabilidad) aparece con el estado "Abierto".

**Comment by pedrobaeza** [comment]
Please, you should report the issues in English. Any way, that problem should be solved. If not, please open a new one in English with all the detailed steps to reproduce the error.
