### ISSUE TITLE
[9.0] Send email via template without partner

### ISSUE THREAD

**Issue by morphace** [odoo/odoo#10604]
Sending emails via a template seems to always require a partner to exist. If you send an email from any other model than a partner, a partner is required to exist, otherwise a default one with only the email address is being created. The context key 'tpl_partners_only' is influencing that (see mail_template.py). That just doesn't make sense... there should be a possibility to not create a partner when a template is being used...

**Comment by Yenthe666** [comment]
Hi there,

How the flow currently works is actually desired behaviour.
If you still find this incorrect or if you can explain into detail why you find this a breaking problem then please do create a new bug report with more details.

Regards,
Yenthe
