### ISSUE TITLE
Accounting entries are incorrect when for MO using real price/perpetual inventory.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#10600]
These two videos show the creation of new products, setting the real price/perpetual inventory, adding landed costs, and manufacturing the item. The inventory valuation report shows the correct total but the balance sheets and journal entries for the MO are incorrect.

This was done on Odoo runbot 9.0 but I have also confirmed it on enterprise edition.

This affects everyone!!

https://youtu.be/NVoruFy1nUs

https://youtu.be/KAq7Hg6-sMo

**Comment by elevationO** [comment]
[Financial report.pdf](https://github.com/odoo/odoo/files/101172/Financial.report.pdf)
![screen shot 2016-01-22 at 9 21 31 am](https://cloud.githubusercontent.com/assets/8355352/12517816/ae66b904-c0e9-11e5-85f4-5fd50ef601b3.png)

**Comment by pedrobaeza** [comment]
Is this still happening in latest code?

**Comment by Yenthe666** [comment]
Hi @elevationO ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
