### ISSUE TITLE
project_task_work class/model missing in Odoo9

### ISSUE THREAD

**Issue by ikzent** [odoo/odoo#10606]
When trying to migrate to Odoo9 all the project_task_work relation is missing.
No correct explanation how the work is related to the task.
Why and how is the new model functionning

**Comment by wtaferner** [comment]
It seems it was removed in https://github.com/odoo/odoo/commit/14183ba2be54a10247419f110f512cc6844a41b4 for the sake of simplification of Odoo Core although I am not sure whether this was properly replaced by any other model to not loose the work entry (start time) and based on this I would call it a **regression**. 

Now the task work is gone and only the ```account.analytic.line``` is left with the date (without time) and the hours worked which is compared to the ```hr.attendance``` in case needed in timesheets.

Properly I would have put a relation to the corresponding  ```account.analytic.line``` on the ```hr.attendance``` and create a new ```hr.action.reason``` (e.g. action) which will separate a work from the new work...therefore the information about when a work was exactly done could be retrieved and eventually also correctly migrated...

@antonylesuisse 
Anything I have missed? Could you eventually consider such an improvement / fix to bring back the time from ```project.task.work```? What does the migration team say?

**Comment by antonylesuisse** [comment]
project.task.work was almost just a proxy for account.analytic.line we decided to remove it.
But you are right it's a date on analytic.line where is was datetime on task.work. I'll check with @tac-odoo

**Comment by antonylesuisse** [comment]
@ikzent project.task.work was a proxy with some helper functions to set  to for account.analytic.line we decided to remove it as most helpers where not needed anymore (we moved the remaning ones and task_id on analytic lines).

@wtaferner we checked and thimeheet sheet handles timezones correctly so this not be a problem both for attendance and analytic lines.

**Comment by wtaferner** [comment]
@antonylesuisse 
Sorry but the issue was the missing time which is lost for a certain booking not the timezone, but as you closed it I guess you are not willing to provide any fix for this regression, right?

**Comment by antonylesuisse** [comment]
Nope the issue was "where did project_task_work task go ?" Truncating time on the date field of task work when migrating to v9 is an other problem. Handling the timezone correctly will ensure that you lines will be linked to the corrrect timesheet sheet, so the issue is mitigated. We cannot change nor we want to change the data model of analytic line. create_date is there if you need more precise info about when it was created.

**Comment by wtaferner** [comment]
Got it, but the ***regression*** is still there as a functionality (```datetime``` of the user work start) is gone...the ```create_date``` cannot be associated to the time a work was started, but when a record was created...
But thank you for taking the time to explain why you closed the issue itself.

I will not insist further now or file a OPW, but we will see if other partners and customers have this issue and it get hot anytime in the future by people sharing my opinion about a regression and somehow ask for a fix (which could be as simple as adding a extra time field on the ```account.analytic.line```)

**Comment by ikzent** [comment]
I do understand that the issue is closed, but the regression remains that the date is gone.

**Comment by wtaferner** [comment]
@ikzent 
The date is not gone, but the exact time of the work entry

**Comment by ikzent** [comment]
Correctly, this is what I ment. If you are trying to track job entries. This information is gone.

**Comment by antonylesuisse** [comment]
In v8 Human Resources -> Timesheet -> Timesheet Activities, it's a date field. In task work the datetime hours minute are discarded when analytic lines are created and that's what matter from a costing/invoicing point of view. The creation time is still available  in the create_date field.

And yes if you are trying to track job entries from tasks the exact hours and minute of the work is not saved anymore. 

In our use case those lines are used to either invoice the customer (Product type service, invoice mode delivered quantities) or to compute the cost. In accounting we dont record the exact time of the day just the day.

Can you explain me the exact use case where time would be needed ?

**Comment by wtaferner** [comment]
Hi Anthony,

In **v8 Project -> Task -> Work activities**
Enabled via **Settings -> Configuration -> Project -> Log work activities on tasks**

I do agree that it was never needed in ```account.analytic.line``` but it was needed to track exact working times on ```project.task.work```. So it is now not possible to say when a work was done exactly which is the way you normally document performance in a fully transparent way.  

The tracking based on the module ```project``` via the task was used to be able to bill the customer and have a back-tracking to know the time and the task (in terms of a many2one) too in case needed (```account.analytic.line``` is only aligned to a project which actually is another regression and the description what have been done is lost too)...the timesheet was improved and was in focus lately, but was and is always missing the time, so the best way and only way to track the time via the core was ```project.task.work``` to get the wanted result.

As you know I can easily do and maintain such a regression myself as it was a stub before but it is a pity that it just got dropped without proper replacement or improvement and makes it even more difficult to follow the core (based on this I will have to invest quite an effort for my depending customizations).

**Comment by pedrobaeza** [comment]
I agree with @wtaferner that if you want to log work activities, and you go to the task and access "Timesheets" tab, the only possibility is to enter the date, not the time when you have made the work, so this can be considered a regression.
