### ISSUE TITLE
[9.0 : stock] cannot edit name warehouse

### ISSUE THREAD

**Issue by bimajatiwijaya** [odoo/odoo#10610]
i got this error:
  File "/odoo9/odoo9-server/addons/stock/stock.py", line 3844, in _handle_renaming
    push_obj.write(cr, uid, push.id, {'name': pull.name.replace(warehouse.name, name, 1)}, context=context)
UnboundLocalError: local variable 'pull' referenced before assignmen

then i found typo stock.py line 3844 typo. fixed after change variable

for push in route.push_ids:
     push_obj.write(cr, uid, push.id, {'name': [should be push].name.replace(warehouse.name, name, 1)}, context=context)

**Comment by Yenthe666** [comment]
Hi @bimajatiwijaya,

Thanks a lot for your report.
This issue has been resolved in the meanwhile as you can see here:
https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L3974-L3975

Please update your Odoo source code if you still face this issue in order to fix it.

Regards,
Yenthe
