### ISSUE TITLE
[8.0] Invalid BoM filter generated from product.product form view?

### ISSUE THREAD

**Issue by slu-010101** [odoo/odoo#10628]
Steps to reproduce:
- create product with variant and internal reference set
- create BoM for product.template
- open product.product form view 
- "Bill of Materials" button shows 1 BoM
- however: when button is clicked, a filter including the internal reference is generated which will not match any BoM

**Comment by spadae22** [comment]
This is expected, the change was made here, https://github.com/spadae22/odoo/commit/4152e99bbdd56f45b24fe71af6e4f58dd33358fb

**Comment by spadae22** [comment]
[FIX] mrp: duplicated find bom buttons
The product_id field is not required on a mrp.bom (while product_tmpl_id is). When searching for BOMs linked to a product.product, we should display the one specific to this product and the ones linked to the template (but not linked to another variant).

**Comment by spadae22** [comment]
This has been confirmed by enterprise support, bug will be fixed soon.

**Comment by slu-010101** [comment]
Thanks for the feedback.

**Comment by Yenthe666** [comment]
Hi @slu-010101 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
