### ISSUE TITLE
No safeguards against concurrent running of manually launched procurement schedulers

### ISSUE THREAD

**Issue by leio** [odoo/odoo#1062]
When launching schedulers from the wizard (Run Schedulers), it is launched directly, not via ir_cron, and as such it doesn't adhere to the locking mechanisms in place that avoid multiple schedulers of the same action at the same time.
I don't see any such locking in place for the wizard, so I believe it could happen that multiple procurement.run_scheduler calls are running concurrently, possibly causing multiple procurements or manufacturing orders, especially when the process takes a lot of time due to many procurements involving big bills of material.

This seems to have happened in practice for us, where at one point a double MO happened and it escalated quickly into a lot of double procurements (turned into MOs thanks to manufacturing type product) due to deep level of BOMs. One of the MO is with source document OP/nnn and the other with source document SCHEDULER, with timestamps differing between 3-5 seconds and 40 seconds.
This was either from running it manually from the menu during an automatic scheduler going on as well, or launching it manually multiple times before the previous time is completed. In this instance, the former is likely, because of the source document being SCHEDULER for one of the duplicates, but I believe it could as easily happen from "spamming" it manually.

**_Impacted versions:**_

 7.0, but relevant procurement/wizard/schedulers_all\* and procurement.run_scheduler code in origin/8.0 is identical.

**_Steps to reproduce:**_
1. Have enough procurements or MOs triggered from one run of procurement scheduler via a deep level of big BOMs and many production going on
2. Enable "Run mrp scheduler" scheduled action at e.g every 10 minutes and perhaps changing arguments to (True, True) under technical data could trigger the issue more likely (enable automatic orderpoints)
3. "Run Schedulers" from the Warehouse menu at the same time the automatic scheduler from ir_cron is running

This may or may not reproduce the issue, as it depends on luck, and mostly one is lucky and the issue isn't hit. But if unlucky with concurrent postgres transactions and one run taking a lot of time, it seems to be possible to run into such duplication issues.

**_Current behavior:**_

 Slight chance of duplicate procurements when "Run Schedulers" wizard is used

**_Expected behavior:**_

Proper locking in place for the manual "Run Schedulers" runs as well, not only reliance on scheduler row locking in ir_cron base code.

**Comment by antonylesuisse** [comment]
Fixed in v8
