### ISSUE TITLE
[15.0][BUG] Mass Mailing sends immediately when duplicated

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#106232]
Impacted versions: 15

Steps to reproduce:

1. Take a mailing that was previously sent via a scheduled date, and duplicate it
2. On the new mailing, click the [Schedule] button
3. Email sent immediately, no calendar selection dialog displayed

Current behavior:

- Email mass mailing sent immediately without dialog appearing to select desired date/time on a calendar as usual
- Verified that this DOES NOT occur when creating a new mailing from scratch, only when duplicated from a copy

Expected behavior:

- Calendar should appear

Summary of findings

After looking into the code for the schedule button, it became clear that it works differently in V14, V15 and V16
In V14 the calendar dialog was ALWAYS shown regardless of schedule type.
In V15, the email is sent immediately without showing the calendar if there is a "scheduled_date" set (as per a previously sent email).
In V16, a small change was made to check if the scheduled date is LATER than today's date to prevent this problem occurring.

Temporary workaround options

- Add the fields "scheduled_date" and "scheduled_type" to the view. These need to be manually changed EVERY TIME a mailing is to be sent after created from a duplicated copy
- Add an automated action that automatically clears the scheduled_date after a mailing has been sent to prevent issues when it is copied in the future. Also run manually on all existing mailings beforehand.
- Add an automated action that automatically clears the scheduled_date after duplicating a mailing to create a new copy

### mailing.py - V14

```
def action_schedule(self):
self.ensure_one()
action = self.env["ir.actions.actions"]._for_xml_id("mass_mailing.mailing_mailing_schedule_date_action")
action['context'] = dict(self.env.context, default_mass_mailing_id=self.id)
return action

def action_put_in_queue(self):
self.write({'state': 'in_queue'})
```

### mailing.py - V15

```
def action_schedule(self):
self.ensure_one()
if self.schedule_date:
return self.action_put_in_queue()
else:
action = self.env["ir.actions.actions"]._for_xml_id("mass_mailing.mailing_mailing_schedule_date_action")
action['context'] = dict(self.env.context, default_mass_mailing_id=self.id)
return action

def action_put_in_queue(self):
self.write({'state': 'in_queue'})
cron = self.env.ref('mass_mailing.ir_cron_mass_mailing_queue')
cron._trigger(
schedule_date or fields.Datetime.now()
for schedule_date in self.mapped('schedule_date')
```
)

### mailing.py - V16

```
def action_schedule(self):
self.ensure_one()
if self.schedule_date and self.schedule_date > fields.Datetime.now():
return self.action_put_in_queue()
action = self.env["ir.actions.actions"]._for_xml_id("mass_mailing.mailing_mailing_schedule_date_action")
action['context'] = dict(self.env.context, default_mass_mailing_id=self.id, dialog_size='medium')
return action

def action_put_in_queue(self):
self.write({'state': 'in_queue'})
cron = self.env.ref('mass_mailing.ir_cron_mass_mailing_queue')
cron._trigger(
schedule_date or fields.Datetime.now()
for schedule_date in self.mapped('schedule_date')
)
```

Support ticket number submitted via odoo.com/help (optional): 
#3077698

**Comment by yelizariev** [comment]
Fixed https://github.com/odoo/odoo/commit/881bf06126869df5af7ee716cdc2b6c87f5b7157
