### ISSUE TITLE
Error with code128 in sale report and website_sale

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#10621]
1) Steps to reproduce the issue you have observed
- Add in report sale a code bar with this line 
```<img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 180, 50)" style="width:180px;height:50px;"/>```

- Install the website_sale module
- Start the server to run test to module website_sale with:
--test-enable --log-level=test -u website_sale

Can find a demonstrative video here: 
https://youtu.be/codyrUsYEwE 

2) The result you observed
The test not finish, and this generate a cycled in the terminal.

 3) The result you expected
The tests pass ok.

 4) The Odoo version is 8.0
ab245fcaa2338d6fe180c17fca7f6acc131a5a3a

**Comment by luistorresm** [comment]
You can see the error in the runbot of this PR:

https://github.com/odoo/odoo/pull/10622

**Comment by beledouxdenis** [comment]
Hello Luis,

Here is my pull request that suggest a solution to your issue. The full explanation why your test is failing is described in this pull request.

https://github.com/odoo/odoo/pull/10631/

However, instead of

**Comment by luistorresm** [comment]
Hello @beledouxdenis 

I applied you changes in my dummy PR #10622, and I yet get the error,

Regards

**Comment by beledouxdenis** [comment]
Luis,

Have you skip the part where I said to replace

```
<img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 180, 50)" style="width:180px;height:50px;"/>
```
by
```
<span t-field="o.name" t-field-options='{"widget": "barcode", "type": "Code128", "width": 180, "height": 50}' style="width:180px;height:50px;"/>
```

**Comment by luistorresm** [comment]
:+1: 

Thanks @beledouxdenis

**Comment by luistorresm** [comment]
Hi @beledouxdenis 

Do you know when will be merger this change?

Regards

**Comment by luistorresm** [comment]
Hello @beledouxdenis 

Do you have news about this Issue?

Regards
