### ISSUE TITLE
[8.0][stock_account]invoice from picking out with qty wrong

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#10623]
Impacted Version
* 8.0

Steps to reproduce
* To set warehouse with three steps to delivery
* To create sale order with product qty **100**
* To confirm sale order
* To change qty of pick(change stock.move) by qty **99**
* To transfer pick by 99
* To transfer pack and out
* To create invoice from picking out

Current Behavior
The invoice was created with qty **100**

Expected Behavior
The invoice should be created by qty **99**

I can see when changed stock.move qty from pick the **product_qty**, **product_uom_qty** and **product_uos_qty** are changed in pick as well, but in the pack/out picking the **product_uos_qty** are not changed

I made a video,
https://youtu.be/z-2CtjrjALU

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/3ac46ee3d4b9775c5d18acc8ffb95188508a20af
