### ISSUE TITLE
[16.0][FW][ISSUE] dark mode in import window

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#106294]
Impacted versions:

16.0

Steps to reproduce:

enable dark mode, then go to the import product window, and you can see some parts of the windows look in normal mode.

Current behavior:

see parts in white

Expected behavior:

see the import window in dark mode.

Video/Screenshot link (optional):
![Captura de pantalla 2022-11-22 a la(s) 18 10 32](https://user-images.githubusercontent.com/21046957/203445958-1e23bb8d-d1e3-41a8-81fb-a408d80464b7.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @chapital ,
this has been fixed by this commit:  https://github.com/odoo/odoo/commit/7691b543283cf47d47dcc5ee14395ee0ae0d8ae9

please verify and close the ticket.
thanks
