### ISSUE TITLE
[9.0] Emoji button in Discuss not working any more

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#10633]
Clicking on the emoji button in **Discuss** composer doesn't work any more. The emoji pop-up won't show. I installed Odoo from source (latest). The emoji button beside the Form's **New Message** works.

![selection_001](https://cloud.githubusercontent.com/assets/13848476/12603374/07f478e2-c4ed-11e5-8490-093035079c41.png)

![tooltip_002](https://cloud.githubusercontent.com/assets/13848476/12603423/84b3de72-c4ed-11e5-9422-4f944ac9589d.png)

Can you please take a look into this?

**Comment by Yenthe666** [comment]
@macdelacruz seems to be fixed again. Just did a test on the latest V9:
<img src="http://i.imgur.com/AOwoFK6.png" alt="Emoji screen"/>

**Comment by lukebranch** [comment]
@Yenthe666 ,

Any idea on why the discuss input field has shrunk? It's an easy fix, but i'm just wondering if this was a design decision by Odoo SA, or something else.

**Comment by Yenthe666** [comment]
@lukebranch,

No idea, I'm going to assume that this accidently got merged in from a previous version or something.
I really don't see any good reason why they would ever make it so small while you have the full width. If you'd make a pull request to fix this it would probably get accepted.

**Comment by lukebranch** [comment]
@Yenthe666 ,

Good to know, thanks.

**Comment by aab-odoo** [comment]
@lukebranch @Yenthe666 It will be fixed tomorrow, among many other small ui bugs. Commit is ready.
