### ISSUE TITLE
[9.0e] Save keyboard shortcut will try to save form even if another form is on top of it

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#10632]
1) Start a new sale order
2) In the customer fields, use "Create and edit" to open the new customer dialog.
3) On Windows, press Alt-S to save.

You will get errors related to the sale order, not to the currently edited customer.

**Comment by Yenthe666** [comment]
Hi @krueger80,

Thanks a lot for your bug report!
This is actually still the case in the latest Odoo 9.0:
![image](https://user-images.githubusercontent.com/6352350/34990110-29a00ad2-fac5-11e7-8a8f-eed69a59e891.png)
@nle-odoo I see you've made commits to odoo/dev but couldn't find a commit to odoo/odoo itself. Can you check?

**Comment by nle-odoo** [comment]
Hi @Yenthe666 

The PR was https://github.com/odoo/odoo/pull/11280 and this has been refused two years ago mainly for the reason given: seeing the difference between browser it seems we should aim to have only one given access button per page (eg. so only one button with CTRL + A where this applied).

Thus in this instance we can't (at least accross main browser) have several buttons "CTRL + S" that would change behavior depending if we are in the top window or 9th opened modal.

So the consensus at the end was to keep  "CTRL + S" as only working for the top view (so in your last screenshot, the sale order form view).

**Comment by Yenthe666** [comment]
Hi @nle-odoo,

Thanks a lot for the very fast and detailed answer!
@krueger80 I'm sorry but I guess this answers everything. Nothing that we can do to make it work correctly cross-browser.

Regards,
Yenthe
