### ISSUE TITLE
Using mulitple payments for one bank/journal?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#10636]
Is it possible to somehow make payments for one journal, but in more than one currency? Now I see I can either use company currency or specify second currency. But what I need is to mimic payments like they are in banks. I mean I can pay with any currency I want, but it is converted to my base currency.

To do that now I need to create new method for every new currency I want to pay.

**Comment by pedrobaeza** [comment]
That's not possible. You have to perform several payments in respective journals for each currency.
