### ISSUE TITLE
[15.0][16.0] [Inventory]Security Lead Time for Purchase not Wroking 

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#106433]
**Impacted versions:**
14, 15, 16

**Steps to reproduce:**

**Set Security Lead Time for Purchase from the Settings**

![image](https://user-images.githubusercontent.com/62367855/203799511-35dd3779-d19e-49f7-b895-394bc1471f23.png)

**Set Vendor and vendor lead time, and enable To Replenish and Buy routes inside the product form**

![image](https://user-images.githubusercontent.com/62367855/203800867-102be4da-4b78-4aca-94cd-92b94a2d5062.png)

**Create Sale Order and Set Delivery Date and Confirm it**

![image](https://user-images.githubusercontent.com/62367855/203805145-0946a31e-69d9-4517-b45f-1eff2341b2b6.png)

It creates PO with the following dates. 
![image](https://user-images.githubusercontent.com/62367855/203806717-ba411eb0-5bc2-476b-b69c-b178731cefc0.png)

and if the PO confirmed, it creates the Receipt Order as follows
![image](https://user-images.githubusercontent.com/62367855/203808420-21fc346c-e197-4c24-9a7e-c7bd7b939ff2.png)

Security Lead time for Purchase doesn't reflect anywhere

**Comment by QaidjoharBarbhaya** [comment]
Hi @thomasdeleval , I am also unable to see the change in scheduled date on incoming receipt after configuring security lead time for purchase. Can you please help? Thank you.

**Comment by thomasdeleval** [comment]
if there wasn't any security lead time, your PO would have been generated on the 28th. I see nothing wrong here

**Comment by QaidjoharBarbhaya** [comment]
@thomasdeleval Thank you for your reply. I have got the success while testing the security lead time for purchase this morning.
