### ISSUE TITLE
[v9]Invoices generated from POS are not keeping the right taxes in the invoice

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10648]
Hi,

I'm working on latest v9, in multi company environment.
Company A parent of company B
A product set with 2 different taxes, one for each company
I create a user with only company B access and accounting rights (BTW, same problem with or without this access right)
First I have this behavior that I consider as a real issue : https://github.com/odoo/odoo/issues/10647 

On a second part, there is a more consequent issue. In the invoice created for the company B there are some Taxes used for the company A. So there is a mix and so it's impossible to validate the invoice. I was wondering if the logged-in company of the administrator could interfere and actually no, if there are multiple invoices set up on the product, the invoice used is always the one of the company A (parent of B)

Hi @nim-odoo Could it be reviewed? I have other issues (https://github.com/odoo/odoo/issues/10572 for example) with multi company and would like to be sure that no bug is hiding in the hood 

Thanks

**Comment by flotho** [comment]
Additionnal info here, I'm using the option that share the products between companies, yet the products are associated to the companyA.
Maybe it could be an part of the answer

**Comment by flotho** [comment]
I also tried something else. With the demo datas, I added a tax for the child company and add it on a product.
With the demo user when I create the pos.order it keeps the both account_taxes!
Amazing

**Comment by fpoyer** [comment]
Hi,

I'm working on a java API for Odoo (using Apache XML RPC Client) that I test against a demo database, and indeed I don't receive the correct taxes for products in multi-companies cases...

**Comment by bwilmus** [comment]
> I also tried something else. With the demo datas, I added a tax for the child company and add it on a product. With the demo user when I create the pos.order it keeps the both account_taxes!

Same here!
Very strange behavior...

**Comment by nim-odoo** [comment]
Thanks for reporting, I am having a look at it

**Comment by flotho** [comment]
The taxes sent form the POS to the server are multiple.
It looks like the POS load all the taxes without considering the company of the POS.
How to filter this? Passing context in some function somewhere?
regards

**Comment by flotho** [comment]
couldn't we add a domain on the models account.tax : https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/js/models.js#L206

**Comment by flotho** [comment]
Changing the global access rule on account.tax solve the problem but it's not really a good way to do this.
I set : 
``` ['|',('company_id','=',False),('company_id','in',[user.company_id.id])] ```
instead of 
``` ['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])] ```
So the problem is really with the context/domain passed from the POS.

**Comment by flotho** [comment]
This part is definitively not doing what expected : https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/point_of_sale.py#L1156

**Comment by nim-odoo** [comment]
The issues probably come from the following commit: a29e291b69335260b26840c195599ed5bf845e16

The PoS user might not be an accountant, so the invoice is created with the SUPERUSER_ID, i.e. the administrator. That would explain why the administrator is the user who created the invoice, and why all taxes appear (record rules don't apply to the SUPERUSER).

**Comment by nim-odoo** [comment]
@flotho : could you try with these commits https://github.com/odoo/odoo/pull/10676

**Comment by flotho** [comment]
Hi @nim-odoo ,

I'm not totally confident with you patch, I'm wondering why you limit your filter on the superuser environment.
Actuallly, when you have multiple companies, you can see thaxes from your child even if you're not an admin. Even if I'm not approving this way of doing (everything in accounting SHOULD be independent and no child_of SHOULD be used in access rules), it still part of the standard so if you're a user form the top level company, all the taxes you'll get will come form all you childs, and you are not super user.
Could you please consider to ALWAYS filter on the current company of the user.

**Comment by flotho** [comment]
Additionnaly this behaviour should be  also reported in all the orders :
* pos.order
* sale.order
* purchase.order
