### ISSUE TITLE
translatable field can not been search by value other then en_US 

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#106501]
Impacted versions:
16.0
Steps to reproduce:

```
>>> pt = env['product.template'].search([('id','=',3)])
>>> pt.name
'Virtual Interior Design'
>>> pt.with_context(lang='zh_CN').name
'虚拟室内设计'
>>> pt = env['product.template'].search([('name','=','Virtual Interior Design')])
>>> pt
product.template(3,)
>>> pt = env['product.template'].search([('name','=','虚拟室内设计')])
>>> pt
product.template()
>>> pt = env['product.template'].with_context(lang='zh_CN').search([('name','=','虚拟室内设计')])
>>> pt
product.template()
```

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by jeffery9** [comment]
already fixed     26b5c8c2baeaee9fcd5384aafa5f9b39543d6903

**Comment by jeffery9** [comment]
#104928

**Comment by GoodERPJeff** [comment]
Thanks @jeffery9 ,I update my source code to later version and the issue gone.

So in odoo dictionary the 'Accent' word means non-ascii character ? fine.
