### ISSUE TITLE
With resupply between warehouses, reorder rules need to execute in sequence

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#10653]
With resupply between warehouses, the _procure_orderpoint_confirm() method should execute orderpoint rules in sequence.  e.g. When you have multiple orderpoints of the same product (usage location and resupply location), check the procurement rules to see which orderpoints need to be executed first.

**Comment by flotho** [comment]
Hi @matt454357 

I agree with you. Do you also already had this kind of issue : https://github.com/odoo/odoo/issues/10572.
If you reproduce it, we probably could consider that sequence is really important even for access rights.
regards

**Comment by matt454357** [comment]
I'm making a lot of assumptions, but here is a more detailed description of the problem.

First of all, I don't see a way to automate resupply between warehouses.  For make-to-stock operations, I would add routes on orderpoints.  For make-to-order, I don't have a ready solution.  For now, let's assume we have an automated solution.

We have 2 orderpoints for a given product:
* Orderpoint 1
  * Location in warehouse X
  * Route = Buy
* Orderpoint 2
  * Location in warehouse Y
  * Route = Resupply warehouse X --> warehouse Y

Orderpoint 2 must be executed before Orderpoint 1.


Incorrect sequence:

1. Execute orderpoint 1: no procurement orders needed
1. Execute orderpoint 2: create a procurement order to transfer, reducing warehouse X inventory below orderpoint min
1. **Warehouse X left with stock shortage, and no procurements to buy more**


Correct sequence:

1. Execute orderpoint 2: create a procurement order to transfer
1. Execute orderpoint 1: create a procurement order to buy

**Comment by matt454357** [comment]
@jco-odoo, Here is a continuation of my thoughts from over on issue #4315.

We need to differentiate between 1-way and 2-way resupply.  In 2-way resupply, you could have one product resupply in one direction, and another product resupply in the opposite direction:
* Product A
  * Orderpoint A1
    * Location in warehouse X
    * Route = Buy
  * Orderpoint A2
    * Location in warehouse Y
    * Route = Resupply warehouse X --> warehouse Y
* Product B
  * Orderpoint B1
    * Location in warehouse Y
    * Route = Manufacture
  * Orderpoint B2
    * Location in warehouse X
    * Route = Resupply warehouse Y --> warehouse X

In short:
* Route for Product A: Warehouse X --> Warehouse Y
* Route for product B: Warehouse Y --> Warehouse X

The method  _procure_orderpoint_confirm() is currently grouping orderpoints by location.  It then executes all orderpoints for a given location, before working on the next location.  With this grouping, we would need to **restrict resupply, between locations, to one direction only.**  With location grouping, and 2-way resupply between warehouses, there is no sequence of locations possible that would solve in a single run.

Now, I don't see a good reason to group orderpoints by location.  Simply sort by llc first, then by orderpoint sequence.  Then 2-way resupply is no problem.  The only question is how to set that sequence.  Let the user do it manually, or set it automatically based on the direction of resupply?

**Comment by pedrobaeza** [comment]
@jco-odoo any news about this?

**Comment by jco-odoo** [comment]
Group by location was an optimization done probably for forecasted
quantities.  Although I like the solution of the LLC, it is not that easy
to implement overall.  I see it as a feature we could implement in the
future, but not as an issue we are going to solve now.

**Comment by pedrobaeza** [comment]
OK, then please take note about this in a task or whatever you use, hehe, and I'm closing the issue for cleaning up the GitHub tracker.
