### ISSUE TITLE
[8.0] in warning module, onchange_product_id changes argument names

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#10666]
In warning module:
https://github.com/odoo/odoo/blob/8.0/addons/warning/warning.py#L235-L237

the arguments to `onchange_product_id` are called differently than in the overridden method from the `purchase` module:
https://github.com/odoo/odoo/blob/8.0/addons/purchase/purchase.py#L1165-L1167

As a result, when the method is run from the UI with positional args it works, but when the method is called with keyword arguments and `warning` is installed, you get a crash.

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
