### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kwameaj67** [odoo/odoo#106792]
Impacted versions: odoo 11

Current behavior: i've restored database and added new modules(addons) to my addons directory. I tried upgrading but from the logs, it shows 'KeyError: odoo'. I don't know what the issue is.

Expected behavior: modules should be installed fully after upgrade

Video/Screenshot link (optional): 
<img width="677" alt="odoo" src="https://user-images.githubusercontent.com/42741527/204573641-b20e9647-0898-4761-8e1d-0d8ea95c112b.png">

**Comment by kwameaj67** [comment]
my addons path in odoo.conf is also perfectly pointing to my modules

**Comment by alesisjoan** [comment]
@kwameaj67 in the logs says, "Unmet dependencies: petra"

**Comment by kwameaj67** [comment]
@alesisjoan  i think that error came up becuase i added that dependency to the depends array. just removed it. the other error is in this image

<img width="643" alt="odoo" src="https://user-images.githubusercontent.com/42741527/205642728-ee931f0f-dd20-46a5-bb61-61f975d1f8a2.png">

**Comment by alesisjoan** [comment]
@kwameaj67 look for a Many2one field definition or related, sometimes it's like a butterfly effect on other fields

**Comment by kwameaj67** [comment]
Alright. I also thought same that there was a missing field some where

**Comment by alesisjoan** [comment]
@kwameaj67 please if it is related to your customization, close the tickets since it's not related to Odoo
