### ISSUE TITLE
[8.0] sale_stock: Browse record instead of id as argument in product.pricelist price_get call

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#10678]
Impacted versions:
- 8.0

Steps to reproduce:
Not a functional issue, the problem comes when inheriting and using the content of products_by_qty_by_partner in price_rule_get_multi.

Current behavior:
Currently, products_by_qty_by_partner contains something like [(product.product(720,), 50.0, res.partner(13543,))] if it runs the [faulty line](https://github.com/odoo/odoo/blob/edeb5a8c0fb5c837364f1d92db731f89824bb28a/addons/sale_stock/sale_stock.py#L409)

Expected behavior:
products_by_qty_by_partner should contain something like [(product.product(720,), 50.0, 13543))], a partner ID instead of a browse record.
price_get receives a partner ID, as you can see in [many](https://github.com/odoo/odoo/blob/edeb5a8c0fb5c837364f1d92db731f89824bb28a/addons/stock_account/stock.py#L126) [other](https://github.com/odoo/odoo/blob/edeb5a8c0fb5c837364f1d92db731f89824bb28a/addons/purchase/purchase.py#L1252) [calls](https://github.com/odoo/odoo/blob/edeb5a8c0fb5c837364f1d92db731f89824bb28a/addons/purchase/purchase.py#L1415)

Fix:
Change `sale_line.order_id.partner_id` for `sale_line.order_id.partner_id.id` [in this call](https://github.com/odoo/odoo/blob/edeb5a8c0fb5c837364f1d92db731f89824bb28a/addons/sale_stock/sale_stock.py#L409)

**Comment by Yenthe666** [comment]
Hi @pablocm-aserti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
