### ISSUE TITLE
[8.0] utils: Float utils round malfuntion

### ISSUE THREAD

**Issue by P4R** [odoo/odoo#10684]
The function **float_round** from **/odoo/openerp/tools/float_utils.py** is not working correctly. It is always using the same two first decimals in any number between [1024.62x .. 2047.62x]. 

Steps to reproduce:

```
(Pdb) from openerp.tools import float_round
(Pdb) float_round(1023.6200000001, precision_rounding=0.01)
1023.62
(Pdb) float_round(1024.6200000001, precision_rounding=0.01)
1024.6200000000001
(Pdb) float_round(1050.6200000001, precision_rounding=0.01)
1050.6200000000001
(Pdb) float_round(2000.6200000001, precision_rounding=0.01)
2000.6200000000001
(Pdb) float_round(2047.6200000001, precision_rounding=0.01)
2047.6200000000001
(Pdb) float_round(2048.6200000001, precision_rounding=0.01)
2048.62
```

Other Odoo branches could be affected, also.

**Comment by Yenthe666** [comment]
Hi @P4R ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
