### ISSUE TITLE
[9.0e] DHL will use KG as UoM instead of the one chosen in settings

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#10698]
Impacted versions:

 - 9.0e

Steps to reproduce:

 0. In the DHL delivery settings, set DHL Domestic to Pounds instead of KG
 1. create a new sale order on a database with demo data
 2. select a local customer
 3. select DHL domestic delivery method
 4. add a line with product 'iMac', quantity 1
 5. confirm the sale order
 6. jump to the newly created delivery 
 7. Force availability if not reserved already
 8. Validate
 

Current behavior:

 - The label with be generated using the KG UoM
 - "K" is hardcoded in the code, file dhl_request.py, line 84. 

Expected behavior:

 - The label should be generated using the UoM from the settings
 - In file dhl_request.py, line 84, the UoM should be taken from settings

**Comment by nim-odoo** [comment]
Solved in https://github.com/odoo/enterprise/commit/3342c0ea00dfca151b18c03da865aa3ccb4faac2
