### ISSUE TITLE
[V9]Purchase prices for template are not reported on variant in purchase order line

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10699]
**Supplier info is not used in purchase order line when defined on the template**

Impacted versions:
- 9.0 (latest on github)

Steps to reproduce:
1. Create a new product with variants > 2
2. On the template create a supplier info for the template
3. Create a purchase order for a variant of this template for the supplier/vendor

Current behavior:
- In the line, the price used is zero 

Expected behavior:
- The template supplier price should be used

**Comment by flotho** [comment]
maybe related to https://github.com/odoo/odoo/issues/10450

**Comment by pedrobaeza** [comment]
See the same explanation as in https://github.com/odoo/odoo/issues/10450#issuecomment-380616751
