### ISSUE TITLE
social media links cannot be modified 

### ISSUE THREAD

**Issue by maherkhalil07** [odoo/odoo#106955]
Impacted versions: 16.0

Steps to reproduce: create website then edit social media links

Current behavior: cannot be edited

Expected behavior:can be edited

Video/Screenshot link [(optional):](url)
![social media editing](https://user-images.githubusercontent.com/38738435/204905346-857c9a87-3064-449f-912a-89060d2fd7ef.jpeg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by wai** [comment]
#104048

**Comment by vava-odoo** [comment]
Solved by https://github.com/odoo/odoo/pull/105964
