### ISSUE TITLE
[V9] Filtering on available products variant is very slow

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10703]
Hi,

I'm working on a database with ~40k products variants dispatched on 5 warehouses.
I would like to filtter on available product on a specific warehouse.
This operation takes almost 2 minutes.
Is it a normal response time for such quantity? what kind of tips could I use to reduce this computing time?

regards

**Comment by tesserB** [comment]
flotho,
     I'm afraid we would have to know a lot more to answer your question. That said, the Github Issues are used to reports bugs. If you would still like help with this issue, please try one of the resources below:

Mailing Lists:
https://www.odoo.com/groups

Help Forum:
https://www.odoo.com/forum/help-1

Respectfully,
Cody K.
ckitterm@gmail.com

@mart-e Same vein as #11932, we're good here.
