### ISSUE TITLE
editing users from user list keeps showing the same (first clicked user)

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#107161]
Impacted versions: 21559357-master-all.runbot135.odoo.com

Steps to reproduce: go to users in list view, edit 1 user, go back to list, click another user -> will show first user's info. 

Current behavior: shows the first opened user on all users

Expected behavior: should show the clicked user

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/69362083/205395189-0bcbec49-0f07-4e40-bbec-d5b62fcccecf.png)
![image](https://user-images.githubusercontent.com/69362083/205395224-8d25f59d-4445-4ae1-b09a-ed54c964e823.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @werkwolk ,
could you provide little more info like the version, i tried to reproduce the same in 16.0 and seems working fine in runbot.
can you confirm and see if this is still happening or not.

in case if this is not able to reproduce, feel free to close the ticket.
thanks

**Comment by vava-odoo** [comment]
Hi @werkwolk 
Feel free to re-open, but looks like it is solved.
Cheers
