### ISSUE TITLE
[Bug Multi-Currencies ] In Invoice Payment with Multi-Currency 

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#10715]
Regarding invoice payment.

Installation of default odoo, demo data.

Create invoice for different currency.
Register payment with payment rate, payment currency id.

partial payment done with new currency rate. 

Even pay partial, it show Invoice Paid. No more repay.

Its bit more wired stuffs with multi-currency.

Can I have fix for this or patch ?

Does someone confirm it ! Or let me know some one try with different payment rate.

Odoo 8.0 stable

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
