### ISSUE TITLE
[V8] Wrong Stock Valuation with FIFO

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#10713]
How to reproduce:
1. PO00005: buy 100 Product X at unit price of $40,000
2. PO00006: buy 100 Product X again at unit price of $50,000
3. Complete stock picking for the both above
4. SO.160201.789: sell 110 Product X and delivery to Customer
5. Navigate to Warehouse > Inventory Control > Current Inventory Valuation
6. Filter for Product X and find the wrong inventory value as attached.

![selection_114](https://cloud.githubusercontent.com/assets/7938973/12714165/a09a6ba8-c905-11e5-9a13-9b17397bc4bb.png)

The expected result should include 4 lines: the first two is for receiving, the another two should should 100 units and 10 units. correspondingly.

**Comment by odony** [comment]
This should be solved after commit 1d7c12022dcffce4792b9eec85706e19338cfa9f. If yes, would you mind closing this issue? Thanks!

**Comment by davidtranhp** [comment]
Tks!
