### ISSUE TITLE
[v8-v9]Default journal account is not used in invoices

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10720]
Hi,

Is it normal that the default journal account is not used in the invoices?

regards

**Comment by flotho** [comment]
Won't it be reasonnable to add the account of the journal here : https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L1333

**Comment by Yenthe666** [comment]
@qdp-odoo could you answer this question? It probably takes you like 10 seconds. 😉

**Comment by qdp-odoo** [comment]
the default accounts set on sale/purchase journals _are_ used in invoices/bills: when there is no product selected on an invoice line, the default account of the invoice line will be defaulted to the debit/credit account set on the journal.

That was the case in v8 already and is still True so far (v11)
