### ISSUE TITLE
in months where the last day is at the end of a week you can't drag things into the next month

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#10730]
Depending on what day your start of the week is, January 2016 or April 2016 might end on a week boundary, with the last day being a Sunday or Saturday.
This means that in screens like the manufacturing order planner or the project task list there is no way to drag an item across into the next month, unlike months where there are some grey dates of the next month on screen. This is particularly important in the order planner, as there appears to be no other way to change the date of an order.
Screenshot showing the project task planner for April, where the 30th is a Saturday and there are no days in May on screen to drag items to. You can see the last days of March at the top of the calendar with the grey day numbers, so you can drag back a month, but not forward.
![screenshot from 2016-02-02 11-38-57](https://cloud.githubusercontent.com/assets/691857/12748422/05da6ae4-c9a2-11e5-8bc6-75fe150c9dbe.png)

**Comment by pedrobaeza** [comment]
Newest versions supports to drag on previous/next month days in grey, so this can be considered solved.
