### ISSUE TITLE
[8.0] Employee are not auto-subscribed anymore to their leave request

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#10739]
Into 8.0 with this commit https://github.com/odoo/odoo/commit/e74c12ffe2f0ced4d5e67e9377e0934bae54fa3d

The employee are no more automatically set as follower of the leave request they just created.

As this change of behavior appears into stable branch 8.0 then the users abrutly lost a usefull fonctionality: they are no more notifed by mail when their holidays are approved.

@tde-banana-odoo  do you have any explanations to clarify the motivation of this improvement?

Thanks

**Comment by JonathanNEMRY** [comment]
OPW 668515

**Comment by tde-banana-odoo** [comment]
Actually the leave creator is not necessarily the employee. In several cases the creator is an HR or an automatic process that should not explicitly be added in the followers.

In 9.0 the employee is added as follower (see create and write calling add_follower). Therefore removing the automatic subscription of the creator had no effect on the employee subscription.

Effectively this is missing in 8.0 as automatic employee subscription does not seem to be implemented. Probably that the right way of keeping the old behavior is to manually subscribe the employee to the leave request, like was is done in 9.0 cc @beledouxdenis .

**Comment by JonathanNEMRY** [comment]
Hi @tde-banana-odoo 
you mean that you back-ported a v9 improvement into a stable v8 without the related v9' modification that allows to keep the same behavior from a user's point of view?

I think something should be done into v8 too because the users were used to receive email.

Moreover as you said and as I understand If someone else create a leave requets for an employee then this person will not even be aware of this leave request.
This improvement into the stable 8.0 branch has clearly introduce a functional bug into it.

**Comment by adrienpeiffer** [comment]
:+1: 

@tde-banana-odoo @beledouxdenis Have you considered Jonathan's remarks ?

**Comment by adrienpeiffer** [comment]
@tde-banana-odoo @beledouxdenis  ?

**Comment by simongoffin** [comment]
Closed with 05179389bf78badad26ca5198e81f0f8c708eb53

**Comment by JonathanNEMRY** [comment]
Hi @simongoffin 
Tested on runbot. Thanks!
