### ISSUE TITLE
[V9]POS Cache dont use the coreect Display name for the products

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#10736]
Hi,

I have a problem with the display_name in the POS :
* In the Back Office the value of the name is correctly diplayed with the correct translation
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12751606/5175be7e-c9be-11e5-87a9-adb0a02683a1.jpeg)

* On my product I have a single ir_translation with a src <> from the value on the french language
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/12751631/6f357bb6-c9be-11e5-997c-c6f447b4a780.jpeg)

* My user is set up  with the french language
* Once the PoS is loaded the displayed label on the product is the src one instead of the value one

The POS CACHE don't use the correct translation

**Comment by odony** [comment]
@flotho the "source term" field actually represents the English translation for the term, so this is easy to correct. It most probably stems from the initial creation of the product: another product was duplicated and the english version was never adapted. Maybe this actually matters to you if there is a chance that *some* users/customers will be looking at the English translations?
Still, this looks like a bug indeed, and if the PoS user is using French the product names should be the French ones.

@jorenvo could you check if you can reproduce this? There is a chance that `self.env.context['lang']` should be set to the value of `self.compute_user_id.context_lang` inside [`refresh_cache()`](https://github.com/odoo/odoo/blob/7c11d4e7/addons/pos_cache/models/pos_cache.py#L24-L31)

**Comment by jorenvo** [comment]
@odony, yes, you're right, without setting the language in context you always end up with untranslated product names in the cache.

@flotho, the issue has been resolved. Do keep in mind that you need to manually clear the cache in the pos.config form view (recompute cache button) for changes to take effect.

**Comment by flotho** [comment]
Great, I'll try this ASAP.

regards
