### ISSUE TITLE
[9.0] Website - Dynamic menu translation does not work

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#10749]
**Dynamic menu generated from XML data are not translated**

Impacted versions:
- 9.0

Steps to reproduce:
1. create some menu in XML file with model _website.menu_
2. create a template and inherit _website.layout_
3. displaying menu with _<span t-field="submenu.name"/>_ does not translate.
4. using a static string instead about will get translated.

Current behavior:
- Menu does is not translated

Expected behavior:
- Menu must be translated.

**Comment by JKE-be** [comment]
Cannot reproduce.

Please provide video or 'short module' to reproduce it.

**Comment by Yenthe666** [comment]
Hi there,

We're closing this topic as the Github user no longer exists.
Feel free to respond, or create a new bug report, if you (or anyone else) can still reproduce it.

Regards,
Yenthe
