### ISSUE TITLE
Sales Price Update Report error 

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#107452]
Impacted versions:14

Steps to reproduce:0

Current behavior: error

Expected behavior: error

Video/Screenshot link (optional):https://i.ibb.co/vL1FRFC/Untitled.jpg
![Untitled](https://user-images.githubusercontent.com/109812166/206263709-9b145a6a-e55d-4e19-ba85-0df0861085a7.jpg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by bodyx1994** [comment]
????

**Comment by niyasraphy** [comment]
@bodyx1994 as it is some third party app, you have to report the issue through their channels.
thanks

**Comment by bodyx1994** [comment]
> @bodyx1994 as it is some third party app, you have to report the issue through their channels. thanks

i think its nginx conf

**Comment by niyasraphy** [comment]
@bodyx1994 if so please see nginx log/error files for more details

**Comment by bodyx1994** [comment]
I have made the report to be downloaded to the computer instead of the browser 
THX

**Comment by bodyx1994** [comment]
I have made the report to be downloaded to the computer instead of the browser
THX
