### ISSUE TITLE
object with reference: picking_policy - picking.policy

### ISSUE THREAD

**Issue by ferdinand10** [odoo/odoo#10748]
hi,
please im trying to edit a sale order in odoo v8 and i have this errors when i want to save the order:
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: picking_policy - picking.policy]

please can someone help me to fixe it.

**Comment by seckt0r** [comment]
Having the same problem but creating a new vendor.

**Comment by madeadi** [comment]
I have the same problem too when **creating a new vendor**. 

This is the error message.

```
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: picking_warn - picking.warn]
```

**Comment by temuccio** [comment]
Hello, i have the same problem of @madeadi 
Do you have solve it?

**Comment by Yenthe666** [comment]
Hi @ferdinand10,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by alihusnainarshad** [comment]
@madeadi @ferdinand10
 @temuccio 
I have the same problem.
I'm Using Odoo 10.
Please Help
