### ISSUE TITLE
[9.0] hr_payroll_account: analytic entry is created on both credit and debit lines

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#10758]
When analytic account is set on any salary rule, analytic entry will be created on both debit and credit account moves which will lead to zero total amount on analytic account (+amount and - amount).
see https://github.com/odoo/odoo/blob/9.0/addons/hr_payroll_account/hr_payroll_account.py#L136

Expected behavior would be analytic entry only on debit account move line when expense account is debited.

Also analytic account is taken from salary rule but it would be more convenient to make checkbox to indicate that analytic account will be taken from contract settings. In that case there would be no need to define new rule (and salary structure) for each new analytic account.

Salary rule's move with random debit and credit accounts and Administrative analytic account, just for example:
![payroll_analytic](https://cloud.githubusercontent.com/assets/5942291/12786253/d920ec10-ca98-11e5-9009-cdab126c1c64.png)

Corresponding salary rule:
![payroll_analytic1](https://cloud.githubusercontent.com/assets/5942291/12786626/9e954cba-ca9a-11e5-831d-1236d2ef5b32.png)

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
