### ISSUE TITLE
9.0 Missing option 'allow cancelling entry' on Accouting journal

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10756]
field still exist in the journal, but no more accessible in the form

**Comment by elevationO** [comment]
This is only shown when in developer mode.

**Comment by stephaniemillet** [comment]
hi
no,
not even
not accessible at all

_____________________________
Stéphanie Millet 
Project Manager

stephanie.millet@eezee-it.com<mailto:stephanie.millet@eezee-it.com>
 + 32 486 38 70 67
www.eezee-it.com<http://www.eezee-it.com/>



[cid:305BAE5E-48F1-45B4-BE16-B64B88231FF6@home]

On 04 Feb 2016, at 19:23, elevationO <notifications@github.com<mailto:notifications@github.com>> wrote:


This is only shown when in developer mode.

**Comment by elevationO** [comment]
Activate Developer mode.  Click on user name in the top right corner-> about->activate developer mode.

Go to Accounting->configuration->journals->click any journal->advanced settings->allow canceling entries

**Comment by Yenthe666** [comment]
Hey all,

This field is in the view but does require developer mode (as mentioned by @elevationO):
![image](https://user-images.githubusercontent.com/6352350/34988716-ee02bd4e-fabf-11e7-8b99-7d9a05e307d2.png)

Regards,
Yenthe
