### ISSUE TITLE
No option to scan UPC barcode in the Barcode app.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#10760]
The Barcode app does not have an option to enter inventory/pickings via scanner.  There is no field for the EAN code.

Isn't this the purpose?  To scan items for quick and easy data entry?

**Comment by sle-odoo** [comment]
Hi,
In the barcode application, you can scan the name of the picking to open it. By default, it'll generate an code128. If you generate the name of the picking in another barcode type, like upc, you'll be able to open it. I would advise to generate a new reference and extend the code to open the picking.

Regards
