### ISSUE TITLE
V7.0 / V8.0 Account Followup : Duplicate res.partner copy account.move.line

### ISSUE THREAD

**Issue by Julien-BARRAU** [odoo/odoo#1077]
Hi,

We have encounter a huge issue : When account_followup is installed and you duplicate a res.partner (customer), this duplicate account.move.line linked by the field 'unreconciled_aml_ids'. It leads you to unbalanced account.move.line with one more useless row. 

V7.0 : We solved this by extending res.partner in account_followup.py :
    def copy(self, cr, uid, id, default=None, context=None):
        if default is None:
            default = {}
        if context is None:
            context = {}
        default = default.copy()
        default.update({
            'payment_note': None,
            'payment_next_action': None,
            'payment_next_action_date': None,
            'unreconciled_aml_ids': [],
            'payment_note': None,
        })
        return super(res_partner, self).copy(cr, uid, id, default, context=context)

V8.0 : We didn't have time to test it on this version but i think you simply need to add "copy=False" to 'unreconciled_aml_ids'

Best regards,
Julien BARRAU
SOGEXIS

**Comment by qdp-odoo** [comment]
Hello,

it was fixed in 7.0 at revision https://github.com/odoo/odoo/commit/7cc3e65b

for v8, copy=False is the default for one2many fields, so it is fine as well.

Thanks for the contribution
