### ISSUE TITLE
[9.0][base_action_rule] Records never filtered into action rules

### ISSUE THREAD

**Issue by corentinpb** [odoo/odoo#10773]
Branch: 9.0
Addon: base_action_rule
Observation: records are filtered from any action rules
Cause: wrong api decorator on methods base_action_rule._filter_pre and base_action_rule._filter_post
Fix: replace @api.model by api.multi + self.ensure_one()

**Comment by beledouxdenis** [comment]
Hello Corentin, 

We are not able to understand / reproduce your issue with the given explanation.

Here is a simple example I made, to show that the filter is working in the automated actions. It simply prevents the creation of partners having "aa" in their name (with a wonderful division by zero):
https://drive.google.com/file/d/0B5GVjjwUC-ygaXBqTzlfbGZneFE/view?usp=sharing

Could you please explain your exact case where the filter is not working.

Regards,

**Comment by pedrobaeza** [comment]
Closing as no answer.
