### ISSUE TITLE
[FEATURE] Odoo PWA

### ISSUE THREAD

**Issue by gengns** [odoo/odoo#107736]
### Overview
Most employees are used to desktop apps at the office. A PWA is really easy to implement in an already built web app (we need a manifiest.json + service worker) and the main advantage is that it provides a native app-like experience, without the need to download and install a native app. It will look like you have installed Odoo on your Linux, Windows or Mac.

### PWA advantages
- They are faster and more responsive than traditional web apps, which can improve the user experience.
- They can work offline or in low-quality network environments, which is not possible with traditional web apps.
- They can be installed on the user's device, which makes them more accessible and convenient to use.
- They are more secure than traditional web apps, because they are served over HTTPS and are subject to the same security policies as native apps.
- They are easier and cheaper to develop and maintain than native apps, because they use the same technologies as regular web apps.

### Current Behavior
Employees always need to open browser and access Odoo to do anything.

### Goal
Give Odoo more relevance inside your OS and improve overall user experience.

Note: you can always decide if you want to install Odoo in your OS or keep using the browser.

----
I can try to implement this in collaboration with someone who is already familiar with Odoo codebase.

**Comment by Yenthe666** [comment]
Just for your interest, there are already some options for this outside of Odoo their code.
Free: https://odoo-community.org/shop/progressive-web-application-5382#attr=17133
Paid: https://apps.odoo.com/apps/modules/15.0/odoo_ecommerce_pwa/

**Comment by cliffkujala** [comment]
@pedrobaeza Does the Odoo Community PWA suffer the same issues as the new Official Odoo PWA in regards to constantly resetting the permissions of Desktop Notifications?  And are there plans to upgrade this to v17 or will it be abandoned since v17 now offers out of the box PWA?

**Comment by cliffkujala** [comment]
> We don't plan to migrate it, as Odoo is offering natively such support, and with more features like push notifications. About the permission reset that you are mentioning, just open an issue/enterprise ticket with Odoo, as that seems a bug.

OK that is understandable not to migrate.  Should be no need and better to use out of the box when possible.

I opened an Odoo support ticket, and started a new [Github Issue #165822](https://github.com/odoo/odoo/issues/165822) for the Notifications permissions bug.
