### ISSUE TITLE
[9.0][base_iban] Depends on account instead of base

### ISSUE THREAD

**Issue by corentinpb** [odoo/odoo#10774]
Branch: 9.0
Module: base_iban
Observation: involve the installation of account addon whereas it's not useful
Fix: in **openerp**.py, replace "'depends': ['account']" by "'depends': ['base']"

**Comment by Yenthe666** [comment]
Hi @corentinpb,

Thanks for the bug report.
This is however nothing we can/want to change in a stable version.
As it works tighly with the companies & accounting related info the dependency is fine.

Regards,
Yenthe
