### ISSUE TITLE
hi when i put www.sinergiait.com.ar my site have error 

### ISSUE THREAD

**Issue by perezarrieu** [odoo/odoo#10781]
Restablecer las plantillas

Las plantillas seleccionadas serán restablecidas a su configuración por defecto.

Type 'yes' in the box below if you want to confirm.
Inicio
Volver

500: Internal Server Error
and.....
 when i access all page the message:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at you@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by JKE-be** [comment]
You probably have a typo in one qweb template.
Please use https://forum.odoo.com for this kind of bug, except if you can reproduce it.
In any case you need to show the server log if you want help. because this message show nothing.
