### ISSUE TITLE
[8.0][stock] Quant moved in wrong location

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#10782]
Impacted Versions
- 8.0

Steps to reproduce
- Set warehouse with three steps to delivery
- Create one product and assign availability on hand **2**
- Create SO with quantity **2**
- Transfer **pick, pack**
- Transfer **out** with quantity **4**
- Assign availability on hand again **2**
- Create another SO same product and same quantity **2**
- Transfer **pick** and **pack**

Current Behavior
The pack when is transferred the quant moved is into location of **customer** and the **out** is not reserved

Expected Behavior
The transfer in **pack** must move the quant into **output** and **out** must be reserved

I made a video,
https://www.youtube.com/watch?v=Q1yiPjbkB8M

**Comment by hugosantosred** [comment]
:+1:

It's also happening to us in a warehouse with two steps to delivery an lot numbers.

In our case the steps to reproduce are as follows:
- Set warehouse with two steps to delivery
- Create a test product, mark the track outgoing lots field. Set an on hand quantity of 2
- Create a Sale Order with 1 unit of this product
- Transfer internal picking
- Transfer outgoing picking and create a lot for this product
![image](https://cloud.githubusercontent.com/assets/200092/12893050/4f9a4914-ce8f-11e5-9a7a-3e799f801add.png)
- Create a new Sale Order with 1 unit of this product
- Check reserved quant on internal picking
![image](https://cloud.githubusercontent.com/assets/200092/12893175/f80f9f7c-ce8f-11e5-8a49-f1d835f409a6.png)
- Transfer the internal picking
![image](https://cloud.githubusercontent.com/assets/200092/12893201/219c0aba-ce90-11e5-82ef-8e5fa397f221.png)

The processed quant is the quant with serial number assigned an moved to the customer of the first sale order which is absolutely incorrect and very dangerous.

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
