### ISSUE TITLE
[8.0] stock: Odoo client error. Uncaught error: QWeb2: Template 'One2Many.viewmanager' not found

### ISSUE THREAD

**Issue by KarenKawaii** [odoo/odoo#10780]
#### Steps to reproduce:
1. Go to Warehouse menu.
2. Go to Operations > All operations.
3. Go to Delivery Orders > Ready 
4. Create a Transfer or use one is "Ready to Transfer".

This is a random error.
It happens frequently when you do not allow the page to be refreshed and just clean before all is loaded.
#### Current behavior:

![ready transfers odoo2](https://cloud.githubusercontent.com/assets/11741384/13961416/2dc03ff6-f022-11e5-8740-da8705a54b3c.png)
#### Expected behavior:
- No message of Odoo Client Error.

**Comment by s2d4theworld** [comment]
Apparently this error only happens in debug mode.

**Comment by KarenKawaii** [comment]
Hello @s2d4theworld , so there is a fix for this bug?

**Comment by KarenKawaii** [comment]
This error happens as well without debug mode.

**Comment by field-roo** [comment]
I've rolled back to the 20150801 release from nightly - which doesn't have this problem

**Comment by Yenthe666** [comment]
Hi @KarenKawaii,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
