### ISSUE TITLE
Missing `hr.holidays.summary.dept` model referenced by `action_report_holidayssummary` action report

### ISSUE THREAD

**Issue by ypapouin** [odoo/odoo#107812]
Impacted versions:
13.0, 14.0, 15.0, 16.0

`action_report_holidayssummary` seems useless since the `hr.holidays.summary.dept` model does not exist anymore since 13.0

https://github.com/odoo/odoo/blob/c8b9e70ced543e89e00c6f7a04ba752f4e6c13df/addons/hr_holidays/report/hr_holidays_reports.xml#L4-L26

Note that the `print_report` function is still referencing this action.

https://github.com/odoo/odoo/blob/c8b9e70ced543e89e00c6f7a04ba752f4e6c13df/addons/hr_holidays/wizard/hr_holidays_summary_employees.py#L21-L31

**Comment by niyasraphy** [comment]
hi @ypapouin ,
this has been fixed in master by this commit:  https://github.com/odoo/odoo/commit/ee00f84c21b20c81467cdab23f1f03774c0daf56

feel free to close the ticket.
thanks
