### ISSUE TITLE
[8.0]Search one field boolean with another lenguaje does not work

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#10783]
Impacted Versions
* 8.0

Steps to reproduce
* Load another lenguaje like **Spanish(MX)**
* Go to customer and try to find partner with Active=False

Current Behavior
The search shows error

Expected Behavior
to make the search

I made a video,
https://www.youtube.com/watch?v=x3J5lklzyes

**Comment by JKE-be** [comment]
Thank you for the reporting. 
The error is due to a bad translation.
It has been fixed in Transifex. So it should be ok in the next days and after an update of 'translated terms'.

**Comment by JulioSerna** [comment]
Hello @JKE-be 

This issue was solved?

**Comment by JKE-be** [comment]
It should be ... !
But you need to reload your translations !
A traductor translated the filed name :/
