### ISSUE TITLE
_quant_create ignores force_location_from usage

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#10793]
The function `stock.quant._quant_create` is used to create new quants as necessary when processing moves ([source](https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L494)). It by default assumes that source and destination locations are the same as for the given `move` parameter. These can however be overwritten using the `force_location_from/_to` parameters respectively.

The `force_location_from` override doesn't apply for the creation of a negative quant however. As can be seen on [line 516](https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L516) the `if` only checks the move's location. However, the logic immediately under that, on [line 520](https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L520) _does_ take `force_location_from` into account. This means that you can override the source location to be an inventory location, but the check will succeed, meaning you now have negative quants in an inventory location.

Expected behaviour:
The `force_location_from` parameter should affect whether we create negative quants or not.

**Comment by aisopuro** [comment]
At a glance, I'd say that the fix should be as simple as changing [this](https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L516)
```python
if move.location_id.usage == 'internal':
```
to something like
```python
target_location = force_location_from or move.location_id
if target_location.usage == 'internal':
```

**Comment by sle-odoo** [comment]
Hi,
This doesn't seem used at first sight. Anyway, you'll have to find a problematic issue in standard if you want us to patch something there, as it is quite touchy.

Regards
