### ISSUE TITLE
9.0 Odoo task uploaded at V9 update -> to be removed

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#10795]
When updating V9, 

several 'odoo' tasks are created
We have to delete them manually at each update
useless, confusing, and time consuming.

-> to be removed from Update process

Tasks name
Welcome to Odoo 
Try to play with the search bar. Use the filters 
Try to drag a task wherever your want 
Use tags to organize your tasks 
Guess what happens if you set this task as favorite? 
Try to customize this card. Change its background. 
Set this task as 'Ready for next stage' to proceed further in the process 
Use the chatter to collaborate with your members 
Do you want to learn more? Try our implementation guide! 
Finished with this stage? Archive it ! 

 

Send an message with a picture in attachment, and see what happen! 

 

You can set a deadline on a task 

 

You want to add a stage? Add a new column !

**Comment by dreispt** [comment]
You probably are using an instance with demo data installed.
For production use you should have the instance installed without demo data.

**Comment by stephaniemillet** [comment]
Hi Daniel

No, we don’t use demo data.
we are in production. (live system)
The update WITHOUT demo data install odoo task
Please check  it and correct it
txs

_____________________________
Stéphanie Millet 
Project Manager

stephanie.millet@eezee-it.com<mailto:stephanie.millet@eezee-it.com>
 + 32 486 38 70 67
www.eezee-it.com<http://www.eezee-it.com/>



[cid:305BAE5E-48F1-45B4-BE16-B64B88231FF6@home]

On 09 Feb 2016, at 11:42, Daniel Reis <notifications@github.com<mailto:notifications@github.com>> wrote:


You probably are using an instance with demo data installed.
For production use you should have the instance installed without demo data.

**Comment by parthivgls** [comment]
yes, it's a confirm issue. We are having same trouble with one of our
customer instance as well.

On Tue, Feb 9, 2016 at 4:37 PM, stephaniemillet <notifications@github.com>
wrote:

> Hi Daniel
>
> No, we don’t use demo data.
> we are in production. (live system)
> The update WITHOUT demo data install odoo task
> Please check it and correct it
> txs
>
> _____________________________
> Stéphanie Millet
> Project Manager
>
> stephanie.millet@eezee-it.com<mailto:stephanie.millet@eezee-it.com>
> + 32 486 38 70 67
> www.eezee-it.com<http://www.eezee-it.com/>
>
>
>
> [cid:305BAE5E-48F1-45B4-BE16-B64B88231FF6@home]
>
> On 09 Feb 2016, at 11:42, Daniel Reis <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
>
> You probably are using an instance with demo data installed.
> For production use you should have the instance installed without demo
> data.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/odoo/odoo/issues/10795#issuecomment-181810415>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/10795#issuecomment-181818254>.
>



-- 
Thanks & Regards,
Parthiv Patel

**Comment by Yenthe666** [comment]
I've noticed this 'problem' before too, when you update the project module it will create 1 project with 12 tasks. @dreispt it is also on live databases, not on demo only.
@mart-e could we please change this? This has bothered me a few times already.

**Comment by mart-e** [comment]
Are you using the command line? 
```
$ python2 odoo.py --help
...
    --without-demo=WITHOUT_DEMO
                        disable loading demo data for modules to be installed
                        (comma-separated, use "all" for all modules). Requires
                        -d and -i. Default is none
```

**Comment by Yenthe666** [comment]
@mart-e through the interface you have the same issue and you can reproduce it on the latest runbots.
 1. Delete the project 'Start here to discover Odoo'
 2. Update your apps list
 3. Update the project module
 4. Go back to the project views and you'll see the project 'Start here to discover Odoo' will be back, with 13 tasks linked to it.

**Comment by mart-e** [comment]
Oh ok your bug is not that demo data got installed, it is that data that should have been in demo end up in production.
I agree these tasks should have never been in data but indeed when you update the module, deleted data will be back again. You need to archive the project, not remove the data.

It's unfortunately not something we can change in stable but we have a branch to improve that in master (not see them by default, appears only when launching the tour).

**Comment by Yenthe666** [comment]
@mart-e alright, so in V10 we will no longer face this behaviour?

**Comment by dreispt** [comment]
@mart-e I agree with @Yenthe666 : a fix should be provided for some version
