### ISSUE TITLE
[16] border in table in qweb despite css

### ISSUE THREAD

**Issue by testtrem** [odoo/odoo#107989]
Impacted versions:
16
Steps to reproduce:
In runbot for 15 enterprise 
in the record of an employee in the employees module
select the print badge option from the print menu

the procedure is the same for odoo 16

Current behavior:
the pdf that 16 produces adds some borders to the table despite the fact that the definition of the report
doesnt have such style
https://i.imgur.com/ZuCH5Ml.png

even in a custom report such borders are added to the tables
https://i.imgur.com/PFXG8F0.png

Expected behavior:
While the pdf should be generated without such borders like in odoo 15 and prior
https://i.imgur.com/lDuhCo4.png

the same custom report from odoo 14
https://i.imgur.com/6IBQK68.png

and the css and style is the same in both versions of the reports

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
3126185

**Comment by niyasraphy** [comment]
hi @testtrem ,
on checking for the same in runbot, it seems to be getting printed as you shown in the expected sample.
attaching the image from the runbot.

![Screenshot from 2023-05-23 20-40-44](https://github.com/odoo/odoo/assets/27989791/27a57560-4978-4db1-afc2-d4989aa4c913)

may be in between it get fixed ? feel free to check and in case if this is resolved, please close the ticket.

thanks :+1:

**Comment by testtrem** [comment]
yeah, it was fixed before you message
