### ISSUE TITLE
Odoo 9 warning - Validation Error

### ISSUE THREAD

**Issue by Stefano7777777** [odoo/odoo#10801]
hi,
i new with odoo, i've just installed on server Ubuntu, it's seems work but later that i've create a product when i update quantity on hand it's give me this error:

Odoo Avviso - Validation Error
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: weight_uom_id - weight.uom.id]

with or without variants

can anyone help me please?

sorry for my bad english?

**Comment by valvalvalvalval** [comment]
Hi,
I've the same issues. Have you found a solution for this?

**Comment by Yenthe666** [comment]
Hey all,

We can't reproduce this issue anymore.
Please update your Odoo source code to the latest version in order to fix this.

Regards,
Yenthe
