### ISSUE TITLE
[9.0] Can't answer  mails

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#10809]
In discuss , you can't answer incoming mails , because there are not a button to make it, just can star, or mark as read

**Comment by aab-odoo** [comment]
This is no longer the case: https://github.com/odoo/odoo/commit/90d4f76100f2520f599bf3998ade81ac5e6183e5

**Comment by dansanti** [comment]
@aab-odoo There are a problem with fontawesome, deb package don't include some files needed .

here  are 6 files but on deb package there are only  3 files  
https://github.com/odoo/odoo/tree/9.0/addons/web/static/lib/fontawesome/fonts

**Comment by aab-odoo** [comment]
This is fixed by https://github.com/odoo/odoo/commit/52f55ed4936bcbab733ecbc999cb6b6bff16bb3c

**Comment by dansanti** [comment]
@aab-odoo  a last question, why mails with message.record_name no can only can be reply ,if I configure a incoming mail, mails can't be answered,  because  they have'nt a message.record_name

**Comment by aab-odoo** [comment]
For now we can only reply to messages linked to a document (messages coming from a chatter)
