### ISSUE TITLE
 How to activate the button to print list of products in V9 ?

### ISSUE THREAD

**Issue by WalterFalla** [odoo/odoo#10807]
How to activate the button to print list of products in V9 ?

**Comment by Yenthe666** [comment]
Hi @WalterFalla,

If you still face this issue: this report has been moved to product variants, it is no longer under products.
This issue tracker is however for reporting issues, not asking questions. Should you still face this issue or do not know enough with my response please create a question on the official Odoo help forum (help.odoo.com).

Regards,
Yenthe
