### ISSUE TITLE
Question about MySql

### ISSUE THREAD

**Issue by luca-vercelli** [odoo/odoo#10804]
This is not an issue, but a general question about databases & odoo.
I see that there is really /too/ integration between odoo and postgresql. I would prefer the possibility to choose which database I want to connect to - postgresql, mysql, or whatever. Is it possibile such an improvement? Maybe somebody already thougth about it?
Googling around, I see that I am not the only one with this need.

**Comment by flotho** [comment]
Hi,  
AFAIK, No support for myself is planned by Odoo Sa.
From my opinion pg is much more performant than myself. 
Anyway,  Odoo still an open source product and you're able/free to migrate the or. 

Regards

**Comment by JayVora-SerpentCS** [comment]
@flotho meant for mysql, not 'myself':)  
Jokes apart, it is a huge investment to choose another db engine now.

**Comment by luca-vercelli** [comment]
Thank you both for your answers.
My point is not which db engine is "more performant". My point is, there are some customers that already have "their datacenter", with "their favourite db", and they want to use it. So it would be great not to rely on the presence of Postgresql.

**Comment by xmo-odoo** [comment]
That kind of questions belong more on the forums or mailing lists than the bug tracker. As @flotho noted there currently is no intention to add non-pg support internally.

**Comment by luca-vercelli** [comment]
Please, don't close this thread. You can see this as a "new feature request", isn't it?
Maybe you can give me some hint about which classes I should modify in order to give at least MySQL support.

**Comment by xmo-odoo** [comment]
> Maybe you can give me some hint about which classes I should modify in order to give at least MySQL support.

All of [those which perform explicit SQL queries](https://github.com/odoo/odoo/search?l=python&p=1&q=cr.execute&utf8=✓) followed by the internal query-building stuff, and those which build SQL content for other subsystems to execute. It's a pharaonic endeavour, and that's not even considering how to replace features MySQL doesn't (AFAIK) have which Odoo or community modules use (computed or GiST indexes).

Again I would recommend discussing this with partners on the forums or mailing lists, saying that it's a non-trivial endeavour is one hell of an understatement.

**Comment by Yenthe666** [comment]
@luca-vercelli you really can't call such a dramatic change a "new feature request". This is literally taking an existing solution and re-building the whole base. 
Do throw it on the Odoo Help forums though! Who knows somebody wants to join effors on this.
