### ISSUE TITLE
UX odoo 9: database management Backup

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#10803]
After a backup is made, the dialog box stays displayed, which is not consistent with the other dialogs of the database management screen.

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

Agreed that this is not consistent with other dialogs around Odoo.
@mart-e could you forward this to the correct person? It would be a nice extra to have this fixed.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@mart-e another ping for you :gem:
