### ISSUE TITLE
BUG in purchase.py Can't confirm a sale order that generate purchase procurements

### ISSUE THREAD

**Issue by mteok** [odoo/odoo#10813]
in odoo/addons/purchase/purchase.py at line 808:
`taxes_id = taxes_id.filtered(lambda x: x.company_id.id in companies)`
**company.id in companies** is an error!
companies is a recordset, company.id return an int.
Mixing apples and oranges.

**Comment by Yenthe666** [comment]
Hi @mteok,

Thanks a lot for your bug report.
This has been resolved in the meanwhile:
https://github.com/odoo/odoo/blob/11c73cd0aa2ff9cbfde8e5eebf3f22dfa1c805f1/addons/purchase/purchase.py#L860
Please update your source code if you still face this issue.

Regards,
Yenthe
