### ISSUE TITLE
[9.0] Calendar Error

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#10812]
When unchecking a partner to filter on calendar, the following JS error is thrown:

```
TypeError: self.view.all_filters[e.target.value] is undefined

/web_calendar/static/src/js/widgets.js:238
Traceback:
SidebarFilter<.filter_click@/web_calendar/static/src/js/widgets.js:238:13
Widget<.proxy/<@/web/static/src/js/framework/widget.js:398:20
jQuery.event.dispatch@/web/static/lib/jquery/jquery.js:4640:50
jQuery.event.add/elemData.handle@/web/static/lib/jquery/jquery.js:4309:41
```

I'm working on the latest commit which is f2146d360dc2753d4f47562db2f0092584b3eaad at this point in time.

**Comment by adekock11** [comment]
I think that this commit 924c2dee21fffec7eb2df68cbe703238afc9b438 fixed the issue.

**Comment by Yenthe666** [comment]
@adekock11 are you talking about unchecking a partner on the meetings calendar under 'Calendar'? Like this:
![image](https://cloud.githubusercontent.com/assets/6352350/15274611/f7f81d5c-1ab6-11e6-9ec0-c0a525d6202f.png)

If this is the case then the bug is no longer present in the latest runbot.
