### ISSUE TITLE
Cannot edit a parent object from an onchange event

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#10829]
It doesn't seem to be possible to catch an onchange event on account.voucher.line object that will return a value that edit the current voucher_id. When trying to return something like:

```
{"value": {"voucher_id": {"amount": 0}}}
```

It raise an error with NewID not serializable to JSON. Which is a shame because it doesn't seem possible to change objects other than the one we're actually working except if we're creating new relations for one2many or many2many...

**Comment by pedrobaeza** [comment]
This is a limitation of the framework that is expected and documented right now. There are some plans for trying this to improve, but this hasn't been yet implemented. I close as the documentation about this is already included in reference.
