### ISSUE TITLE
[Q&A] How can i add image in doc.rst file to display in odoo apps store

### ISSUE THREAD

**Issue by duong77476** [odoo/odoo#108345]

**Comment by niyasraphy** [comment]
hi @duong77476 ,
you can add an index.html file and add image inside it, as a sample refer this:  https://github.com/odoomates/odooapps/blob/16.0/om_account_accountant/static/description/index.html

feel free to use odoo forum in future for such Q&A, as this is issue tracker.
thanks

**Comment by duong77476** [comment]
> hi @duong77476 , you can add an index.html file and add image inside it, as a sample refer this: https://github.com/odoomates/odooapps/blob/16.0/om_account_accountant/static/description/index.html
> 
> feel free to use odoo forum in future for such Q&A, as this is issue tracker. thanks

Hey thanks for your help,  since Odoo use original sphinx and not customize any to allow using ..image in manifest so i think i need to use your suggestion instead
