### ISSUE TITLE
[15.0][BUG] hr_holidays: Creating time off from calendar view

### ISSUE THREAD

**Issue by DinhTien24** [odoo/odoo#108340]
Impacted versions: [15.0]

Steps to reproduce:
- Go to Time Off/Approvals/Time Off
- Switch to Calendar view
- Click the button "New Time Off"

Current behavior:
TypeError: this.model._getTimeOffDates is not a function
![image](https://user-images.githubusercontent.com/32015466/208573326-3c490f9d-3a0b-4bed-b036-1a713f21c755.png)

Expected behavior:
The Time Off form appears without error.

**Comment by ingesis-automatizacion** [comment]
I tried the follow and it's works for me (https://github.com/odoo/odoo/commit/6bc2a933528bec6bc073d7a4e18ff232fe526f0f):
![Captura de pantalla 2022-12-26 122903](https://user-images.githubusercontent.com/58471295/209554781-b45905e8-ac25-43c7-b8e4-9dcb730a1c85.jpg)

**Comment by DinhTien24** [comment]
I'll close this issue because it has been fixed in this PR: https://github.com/odoo/odoo/pull/108890
