### ISSUE TITLE
[9.0][Users]Modify User's access rights

### ISSUE THREAD

**Issue by fanliugen** [odoo/odoo#10836]
Add a new user,i only want to give it the access right of inventory.but now when i save ,the user also choose the access right of  accounting&finace  apps. i'm not sure whether it is a bug!

**Comment by Yenthe666** [comment]
Hi @fanliugen,

This behaviour has been fixed in the meanwhile. An example on the latest Odoo 9:
![image](https://user-images.githubusercontent.com/6352350/34985384-1f7eecf0-fab4-11e7-8010-2846de88688f.png)

Please update your Odoo source code if you still face this problem.

Regards,
Yenthe
