### ISSUE TITLE
[16.0] [BUG] With Add Multiple pages in notebook.

### ISSUE THREAD

**Issue by Rajan-SerpentCS** [odoo/odoo#108406]
Impacted versions: 16.0

Steps to reproduce:
   - Add Multiple pages in notebook.

Current behavior:
  - Pages Goes out of the sheet.

Expected behavior:
   - Paged must wrap if number of pages are multiple.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/54793346/208835811-d874ea01-975a-4b95-b034-bf4694c9b0af.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Fixed in:  https://github.com/odoo/odoo/commit/19c03accdb5754a6c223bce8ce2cc142e9b2be08
