### ISSUE TITLE
[9.0 + 9.0 OE] Could not get content for announcement.less

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10853]
**announcement.less is missing from the Odoo repo**

Impacted versions:

 - 9.0 and 9.0 Enterprise

Steps to reproduce:

 1. Install a new Odoo / Odoo enterprise
 2. Open up your Odoo in the browser

Current behavior:

 - Could not get content for "/mail/static/src/less/announcement.less defined in bundle 'web.assets_backend'
<img src="http://i.imgur.com/AYrSiKO.png" alt="Issue"/>

Expected behavior:

 - The announcement.less file is loaded and no issues happen.

The problem is coming from the commit https://github.com/odoo/odoo/commit/50a4ca31f8de8bb427cb1d0f182322a3d1e04486 which removed the announcement.less file from Odoo, while it is still referenced and used by Odoo.

**Comment by Yenthe666** [comment]
@xmo-odoo and @odony could this be fixed asap? This literally breaks all functionalities for Odoo.
This problem has been created by a commit 18 hours ago. (https://github.com/odoo/odoo/commit/50a4ca31f8de8bb427cb1d0f182322a3d1e04486)

**Comment by xmo-odoo** [comment]
@Yenthe666 on both runbot and local, a *new* install (and database) work fine. I expect the issue is you're working on a db which predates the commit and haven't updated `addons/mail/views/mail_templates.xml` which still tries to bundle the less (and JS) files

**Comment by beledouxdenis** [comment]
@Yenthe666 I am on it :).

**Comment by Yenthe666** [comment]
@xmo-odoo thanks for that. We have a new guy at the company and I didn't think about the fact that he could be doing this. :+1: 
I do find this a rather intrusive commit though, I don't get why this has been done on the 9.0, this can really break live environments in some cases.
So, technically it is not really an issue but is this really wanted behaviour from Odoo?

**Comment by xmo-odoo** [comment]
> I do find this a rather intrusive commit though, I don't get why this has been done on the 9.0, this can really break live environments in some cases.

No you're completely right.

> So, technically it is not really an issue but is this really wanted behaviour from Odoo?

It is an issue (and @beledouxdenis is looking at it), you shouldn't *have* to `-u` your database on a stable. I was just pointing out that your step 1 was misleading: when following it, the issue doesn't appear.

**Comment by beledouxdenis** [comment]
Thanks for the report Yenthe :).

**Comment by Yenthe666** [comment]
Fair point about the fact that the issue wouldn't appear when creating a new, clean Odoo.
I'm happy this is fixed so fast, thanks @beledouxdenis and @xmo-odoo! Keep up the good work. :+1:
