### ISSUE TITLE
[9.0] POS + account : Accounting Sale Entries has no taxes if generated via PoS 

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#10855]
### Accounting Sale Entries has no taxes if generated via PoS

**Consequences:**
It's not possible for accountant to deliver VAT declaration if PoS is used ;

**Impacted versions:**

 - 9.0 (Tested on https://github.com/odoo/odoo/commit/d2574b7018c2ff9ae140ce2a9728479a8b5ed7df)

**Steps to reproduce:**

 1. Create a Product with default demo sale and purchase VAT (15%) ;
 2. Open a PoS session;
 3. Sell the product (qty = 1) ; pay the Order ; 
 4. Close the session and post entries;
 5. Check generated sale accounting entries ; Open the move.line related to the sale.

**Current behavior:**

 - 'tax_ids' is not defined; (image 2)

**Expected behavior:**

 - 'tax_ids' = the vat of the product (image 3)

### References

**Image 1 : product settings**
![product_setting](https://cloud.githubusercontent.com/assets/3407482/12944477/9e1ad546-cfe7-11e5-87c8-898079c22331.png)

**image 2 : bad account.move.line generated. (via PoS)**
![bad_line](https://cloud.githubusercontent.com/assets/3407482/12944482/a17f8f42-cfe7-11e5-9c5c-bbb52dcafab0.png)

**image 3 : good account.move.line generated (via normal Account Invoice)**
![good_line](https://cloud.githubusercontent.com/assets/3407482/12944485/a4b94fae-cfe7-11e5-866f-58e33be698f6.png)

CC : @fvdsn 

Thanks for your review.

**Comment by legalsylvain** [comment]
@nim-odoo : any news about that bug ? How can I help you ?

Regards.

**Comment by yuntux** [comment]
Up !

**Comment by Yenthe666** [comment]
@qdp-odoo can you have a look at this?

**Comment by dkrimmer84** [comment]
Ping! Any solution on that? @nim-odoo

**Comment by legalsylvain** [comment]
Thanks !
