### ISSUE TITLE
 object has no attribute 14.0 

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#108522]
**When I set the branch for the user I get this error**

modules>>>>>>>Branch
full name>>>Multiple Branch Unit Operation Setup for All Applications Odoo

Traceback (most recent call last):
  File "/stander/stander-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/stander/stander-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'function' object has no attribute 'clear_cache'

**Comment by niyasraphy** [comment]
hi,
as it is coming from a third party addon, try reporting the same in the authors support channels.
thanks

**Comment by bodyx1994** [comment]
> 
I already did, but I'm waiting for a response

**Comment by niyasraphy** [comment]
lets wait for their response.
reporting the same here wont make any difference, rather than just closing it.
