### ISSUE TITLE
[16.0] - Odoo Blog Post Website - Error page appear when the field post_date is not set.

### ISSUE THREAD

**Issue by DucTruongKomit** [odoo/odoo#108577]
Impacted versions:
16.0
Steps to reproduce:
Go to Website > Site > Blog Spot
Then, go to any record and clear Public Date(post_date) field
Current behavior:
The error page will appear
Expected behavior:
Make sure the page will not face any error.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/19970138/209290132-ee76b195-f18c-4375-8edf-f50d35a63b44.png)

![image](https://user-images.githubusercontent.com/19970138/209290037-714d7046-921b-4fa6-b620-43166ca1adc8.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @DucTruongKomit ,
fixed in this commit: https://github.com/odoo/odoo/commit/f2f45cddede53d201e4efbe27a86e208ebf51ab1

feel free to close the ticket.
thanks
