### ISSUE TITLE
Slowing product import in database contain millions of accounting entries

### ISSUE THREAD

**Issue by akloptim** [odoo/odoo#108693]
https://github.com/odoo/odoo/blob/e2e6d68b4ddfa2d5bc9f4d588d35e5e390e6afb8/addons/account/models/product.py#L86

It's almost impossible to import a minimum of 100 products at a time in a database that contains 5 million account_move_line records

**Comment by maizarrahman** [comment]
To improve _check_uom_not_in_invoice method:
1. add index for product_id field in account.move.line model
2. remove for-loops, search in once by using list of product template IDs

**Comment by niyasraphy** [comment]
Fixed:  https://github.com/odoo/odoo/commit/ace565ee49d126b53d23cc97ae4cdea2626a9ea9
