### ISSUE TITLE
odoo configuration parameters

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#108651]
**Hello everybody
I have Odoo version 14 and I need the config file
odoo 14.0
Processor information = AMD EPYC 7282 16-Core Processor, 6 cores
Real memory = 16gb
Operating system=Ubuntu Linux 20.04.5
Kernel and CPU=Linux 5.4.0-105-generic on x86_64

db_maxconn = 
limit_memory_hard =
limit_memory_soft = 
limit_request = 
limit_time_cpu = 
limit_time_real = 
limit_time_real_cron = 
max_cron_threads = 
osv_memory_age_limit = 
osv_memory_count_limit = 
workers = 

Thanks in advance**

**Comment by nilshamerlinck** [comment]
Hello sir, you can have a look at https://www.odoo.com/documentation/14.0/administration/install/deploy.html#id5
