### ISSUE TITLE
[8.0] and [9.0] Documentation Bug

### ISSUE THREAD

**Issue by readikus** [odoo/odoo#10866]
The documentation for module creation in v8 and v9 has a bug with the latest releases. I followed the steps, to the letter, and was unable to create a module. The following error was received:

Regards,

Ian:
 File &quot;/usr/lib/python2.7/dist-packages/openerp/api.py&quot;, line 496, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File &quot;/usr/lib/python2.7/dist-packages/openerp/models.py&quot;, line 4285, in _create
    recs._validate_fields(vals)
  File &quot;/usr/lib/python2.7/dist-packages/openerp/api.py&quot;, line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File &quot;/usr/lib/python2.7/dist-packages/openerp/models.py&quot;, line 1272, in _validate_fields
    raise ValidationError(&#39;\n&#39;.join(errors))
ParseError: &quot;ValidateError
Field(s) `res_model, src_model` failed against a constraint: Invalid model name in the action definition.&quot; while parsing /etc/odoo/addons/openacademy/views/openacademy.xml:9, near
&lt;record model=&quot;ir.actions.act_window&quot; id=&quot;course_list_action&quot;&gt;
            &lt;field name=&quot;name&quot;&gt;Courses&lt;/field&gt;
            &lt;field name=&quot;res_model&quot;&gt;openacademy.course&lt;/field&gt;
            &lt;field name=&quot;view_type&quot;&gt;form&lt;/field&gt;
            &lt;field name=&quot;view_mode&quot;&gt;tree,form&lt;/field&gt;
            &lt;field name=&quot;help&quot; type=&quot;html&quot;&gt;
                &lt;p class=&quot;oe_view_nocontent_create&quot;&gt;Create the first course
                &lt;/p&gt;
            &lt;/field&gt;
        &lt;/record&gt;

**Comment by andreparames** [comment]
(Note: I'm not an official Odoo dev, just an occasional contributor)

The guide seems fine. Are you sure you didn't miss adding the `__init__.py` or the `models.py` files?

**Comment by readikus** [comment]
When you say "The guide seems fine", have you followed it to create a module in v8 or v9? If so, do you have the full code for that module that I could have a look at?


__init__.py:

 coding: utf-8 -*-

import models
import openacademy
import controllers
import models



models.py:


from openerp import models, fields, api

class Course(models.Model):
    _name = 'openacademy.course'

    name = fields.Char(string="Title", required=True)
    description = fields.Text()

**Comment by andreparames** [comment]
I don't have the code, I was just looking at the guide. Your files seem fine.

Have you restarted Odoo after adding the Course class to `models.py`? I'm not sure the guide says so, but you need to restart Odoo every time you edit a `.py` file.

**Comment by mart-e** [comment]
Hi,

I have been using the tutorial for a training a few weeks ago and got no issues. Make sure you follow correctly each steps.
- When you modify python files you will need to restart your server.
- If you modify something linked to the database, update your module
- Don't forget to import your files in `__init__.py` files

**Comment by Greentash** [comment]
Hi all
I have odoo8 installed on ubuntu 16.04.
It will be helpfull to edit **/etc/odoo/openerp-server.conf** and set this parameter **auto_reload = True**.
I join idea of great @mart-e 
Thanks
