### ISSUE TITLE
[8.0][account_anglo_saxon]average price use wrong account when invoice has exchange rate 

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#10868]
Impacted Versions
- 8.0

Steps to reproduce
- Create product with average price
- Create Purchase Order  **100 USD** at date **02/08/2016** 
- Transfer reception
- Create invoice also by **100 USD** at date **07/01/2016**

Current Behavior
The journal entry from invoice use the account **Price Difference Account** and this different is about different by exchange rate and not by different price between purchase order and invoice

Expected Behavior
The account to use should be **Exchange Rate Account**  

I made video,
https://www.youtube.com/watch?v=0Jbe15zbwwA&feature=youtu.be

**Comment by hbto** [comment]
I have followed same steps than Julio, 

I have found same issue

https://drive.google.com/a/vauxoo.com/file/d/0B1w9gokcJL9hYUIxdU1rSHBxQ1E/view

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
