### ISSUE TITLE
[8.0] 'false' text when emptying translatable fields

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#10862]
Steps to reproduce
------------------
* Go to runbot and launch a 8.0 instance.
* Change language to one different from English (for example, Spanish).
* Open a product, change _Description_ translatable field to any text and save.
* Edit the product again, empty the _Description_ field, and save.

Expected result
---------------
The field is emptied.

Obtained result
---------------
The system writes the word 'false' in the field, which is for sure the JavaScript boolean value that is converted to string instead of being interpreted as the python False.

**Comment by tafaRU** [comment]
@pedro, seems equal to mine: https://github.com/odoo/odoo/issues/10196
Anyway, it's ok to me close that one, considering yours is better explained :wink:

**Comment by pedrobaeza** [comment]
Indeed it's the same. Let's hope this can be solved, as it's on the JS side, I'm less experienced in solving these bugs, but if nobody answer, I'll try for OCB.

**Comment by yannprada** [comment]
Any idea if they will fix it any day soon ? @xmo-odoo

**Comment by pedrobaeza** [comment]
@mart-e, maybe you can help here as this involves translations.

**Comment by mart-e** [comment]
Actually it's the `false` from postgres, not javascript. Made a try for an ORM fix at #11774 but need to be sure there is no side effect.

**Comment by pedrobaeza** [comment]
Thank you very much! I will try and tell you.
