### ISSUE TITLE
[8.0][stock]quant moved wrong location from MO

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#10869]
Impacted Versions
- 8.0

Steps to reproduce
- Create product to manufacturing
- Create sale order and validate
- Force availability and transfer
- Create MO and produce

Current Behavior
The MO to finished product create quant in **customer location**

Expected Behavior
Create quant in **stock location**

I made video,
https://youtu.be/QTR0Wg4MgaI

I think this issue is related with this another [issue](https://github.com/odoo/odoo/issues/10782)

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
