### ISSUE TITLE
Managing multiple values within a single XML attribute (attrs) -Odoo 

### ISSUE THREAD

**Issue by samica31** [odoo/odoo#10867]
Hi y'all,

What is the syntax in attrs for two values? Here's how i do it but didn't work. 
is it possible to have invisible and readonly in an attrs attribute. 

Thank you!

**attrs="{'invisible': [('stage_id', 'in', (24,25))]},{'readonly': [('stage_id', 'in', (26))]}"/>**

**Comment by Yenthe666** [comment]
@samica31,

Github issues are made for **issues**, not questions.
As to how to use readonly and invisible in attrs:
attrs="{'invisible':[('stage_id', 'in', (24,25))],'readonly':[('stage_id', 'in', (26)]}"

@mart-e locky-lock.

**Comment by VIRALPATEL7777** [comment]
attrs="{'invisible': ['|', ('age', '&lt;', 10), ('age', '&gt;', 20), '|', ('age', '&lt;', 50), ('age', '&gt;', 60)]}"
find the bugg
