### ISSUE TITLE
[16.0] print sale order

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#108799]
Impacted versions:

- [ ] 16.0

Steps to reproduce:
1. install odoo 16
2. load demo data
3. install sale
4. try to print the sale order

Current behavior:
500
\nCompiled code:\ncode = None\ntemplate = 'account.document_tax_totals'\ntemplate_functions = {}\ndef template_691_t_call_0(self, values):\n    yield ''\ndef template_691_content(self, values):\n        # element: '/t' , ''\n        attrs = values['__qweb_attrs__'] = {}\n        # element: '/t/t[1]' , ''\n        yield '\\n            '\n        template_691_t_foreach_1 = ((values.get('tax_totals')['subtotals'])) or []\n        if isinstance(template_691_t_foreach_1, Sized):\n            values['subtotal_size'] = template_691_size_2 = len(template_691_t_foreach_1)\n        elif (template_691_t_foreach_1).__class__ == int:\n            values['subtotal_size'] = template_691_size_2 = template_691_t_foreach_1\n            template_691_t_foreach_1 = range(template_691_size_2)\n        else:\n            template_691_size_2 = None\n        template_691_has_value_3 = False\n        if isinstance(template_691_t_foreach_1, Mapping):\n            template_691_t_foreach_1 = template_691_t_foreach_1.items()\n            template_691_has_value_3 = True\n        for index, item in enumerate(template_691_t_foreach_1):\n            values['subtotal_index'] = index\n            if template_691_has_value_3:\n                values['subtotal'], values['subtotal_value'] = item\n            else:\n                values['subtotal'] = values['subtotal_value'] = item\n            values['subtotal_first'] = values['subtotal_index'] == 0\n            if template_691_size_2 is not None:\n                values['subtotal_last'] = index + 1 == template_691_size_2\n            values['subtotal_odd'] = index % 2\n            values['subtotal_even'] = not values['subtotal_odd']\n            values['subtotal_parity'] = 'odd' if values['subtotal_odd'] else 'even'\n            attrs = values['__qweb_attrs__'] = {}\n            # element: '/t/t[1]/tr/td[1]/strong' , ''\n            attrs = values['__qweb_attrs__'] = {}\n            yield '\\n                \\n                    '\n            content = ((values.get('subtotal')['name']))\n            if content is not None and content is not False:\n                yield ''\n                yield str(escape(content))\n                yield ''\n            # element: '/t/t[1]/tr/td[2]/span' , ''\n            attrs = values['__qweb_attrs__'] = {}\n            attrs['class'] = ((values.get('oe_subtotal_footer_separator')))\n            yield '\\n\\n                    \\n                        '\n            content = ((values.get('subtotal')['formatted_amount']))\n            if content is not None and content is not False:\n                yield ''\n                yield str(escape(content))\n                yield ''\n            # element: '/t/t[1]/t[1]' , ''\n            attrs = values['__qweb_attrs__'] = {}\n            yield '\\n                    \\n                \\n'\n            values['subtotal_to_show'] = ((values.get('subtotal')['name']))\n            # element: '/t/t[1]/t[2]' , ''\n            attrs = values['__qweb_attrs__'] = {}\n            yield ''\n            t_call_options = values.pop('__qweb_options__', {})\n            t_call_values = values.copy()\n            t_call_values[0] = list(template_691_t_call_0(self, t_call_values))\n            irQweb = self.with_context(**t_call_options)\n            template = 'account.tax_groups_totals'\n            if template.isnumeric():\n                template = int(template)\n            t_call_template_functions, def_name = irQweb._compile(template)\n            render_template = t_call_template_functions[def_name]\n            yield from render_template(irQweb, t_call_values)\n            yield ''\n        # element: '/t/tr/td[2]/span' , ''\n        attrs = values['__qweb_attrs__'] = {}\n        yield '\\n\\n            \\n            \\n                Totale\\n                \\n                    '\n        content = ((values.get('tax_totals')['formatted_amount_total']))\n        if content is not None and content is not False:\n            yield ''\n            yield str(escape(content))\n            yield ''\n        # element: '/t/t[2]' , ''\n        yield '\\n                \\n            '\n        if ((values['o'].withholding_tax_in_print and values['o'].withholding_tax)):\n            attrs = values['__qweb_attrs__'] = {}\n            # element: '/t/t[2]/tr[1]/td[2]/span' , ''\n            values['__qweb_options__'] = (({'widget': 'monetary', 'display_currency': values['o'].currency_id}))\n            attrs = values['__qweb_attrs__'] = {}\n            yield '\\n                    \\n                        \\n                            Ritenuta d\\'acconto\\n                        \\n                        \\n                            '\n            field_attrs, content, force_display = self._get_field(((values['o'])), 'withholding_tax_amount', 'o.withholding_tax_amount', 'span', values.pop('__qweb_options__', {}), values)\n            if values.get('__qweb_attrs__') is None:\n                values['__qweb_attrs__'] = field_attrs\n            else:\n                values['__qweb_attrs__'].update(field_attrs)\n            if content is not None and content is not False:\n                content = self._compile_to_str(content)\n            if content is not None and content is not False:\n                yield ''\n                yield str(escape(content))\n                yield ''\n            elif force_display:\n                yield ''\n                yield '
                                    '\n            values['__qweb_options__'] = (({'widget': 'monetary', 'display_currency': values['o'].currency_id}))\n            attrs = values['__qweb_attrs__'] = {}\n            yield '\\n                        \\n                    \\n                    \\n                        \\n                            Netto da pagare\\n                        \\n                        \\n                            '\n            field_attrs, content, force_display = self._get_field(((values['o'])), 'amount_net_pay', 'o.amount_net_pay', 'span', values.pop('__qweb_options__', {}), values)\n            if values.get('__qweb_attrs__') is None:\n                values['__qweb_attrs__'] = field_attrs\n            else:\n                values['__qweb_attrs__'].update(field_attrs)\n            if content is not None and content is not False:\n                content = self._compile_to_str(content)\n            if content is not None and content is not False:\n                yield ''\n                yield str(escape(content))\n                yield '
The above server error caused the following client error:
RPC_ERROR: Arbitrary Uncaught Python Exception
    at makeErrorFromResponse (http://0.0.0.0:8069/web/assets/1227-0e94b22/web.assets_backend.min.js:974:163)
    at decoder.onload (http://0.0.0.0:8069/web/assets/1227-0e94b22/web.assets_backend.min.js:962:7)

Expected behavior:

no traceback, and print report of sale order

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Hi,
upon testing the same in v16 with new database and installing sale modules, seems the print out coming correctly without any issues for me

**Comment by matteoopenf** [comment]
I find the problem is that module from OCA:
![image](https://user-images.githubusercontent.com/43987335/209990320-51c44bfd-8782-43bf-a13b-2405bd357b87.png)


I will open an issue on l10n-italy
