### ISSUE TITLE
when executing my site dont show my pictures including in the same

### ISSUE THREAD

**Issue by perezarrieu** [odoo/odoo#10877]
when executing my site dont show my pictures including in the same.
i have included my pictures in format png.
when i  am loging in my site and i test my site i can see the pictures

**Comment by JKE-be** [comment]
Please take a look here: https://github.com/odoo/odoo/wiki/Contributing#reporting-issues

what is your issue ? 
how to reproduce ? 

If it's just in your instance, use https://forum.odoo.com ...
