### ISSUE TITLE
[9.0] Webiste sale incorrect tx data: amount

### ISSUE THREAD

**Issue by aleksandar-irvas** [odoo/odoo#10879]
**Incorrect td data: amount**

Impacted versions:
- 9.0

Steps to reproduce:
1. Add to cart item
2. Click + or - sign to increase - decrease qty, couple of times (fast)
3. Process checkout
4. Shipping & Billing click next
5. Pay order

Current behavior:
- order is not created
  - log `openerp.addons.payment.models.payment_acquirer: transfer: incorrect tx data:
    amount: received 34.74 instead of 23.16`

Expected behavior:
- Order is created

**Comment by phoenixsampras** [comment]
Any update on this Critical Issue?

**Comment by aleksandar-irvas** [comment]
I think I solve this with the downloading new version of odoo. **Version 9.0c-20151215**

**Comment by Yenthe666** [comment]
Hey all,

I can no longer reproduce this issue, it should have been fixed in the meanwhile.
Please update your Odoo to the latest source code to fix this.

Regards,
Yenthe
