### ISSUE TITLE
In addon purchase italian translation of string "Deliveries & Invoices" does not display & but entity (&amp;)

### ISSUE THREAD

**Issue by iceseyes** [odoo/odoo#10875]
When I open purchase order, using italian localization,  tab title  

`Deliveries & Invoices`

which is correctly traslated as 

`Consegne & Fatture`

it's displayed not with `&` symbol but with its entity `&amp;`.  In other words it appers so:

`Consegne &amp; Fatture`

I don't try using en localization.

**Comment by mart-e** [comment]
Hello,

It has been fixed at 669b6f7b3def8af10e68d320f120236c96d582b4
