### ISSUE TITLE
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#108748]
self._cnx = pool.borrow(dsn)
  File "/stander/stander-server/odoo/sql_db.py", line 561, in _locked
    return fun(self, *args, **kwargs)
  File "/stander/stander-server/odoo/sql_db.py", line 627, in borrow
    result = psycopg2.connect(
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

odoo-14
postgres 12
Ubuntu 20.4

**Comment by dyntaos** [comment]
This is not an Odoo issue. The Postgres server isn't running on your machine. Check if it is running with `systemctl status postgres`.
If it is not running you can try to manually start it with: `sudo systemctl start postgresql`. It can be set to start automatically with `sudo systemctl enable postgresql`

If it fails to start, authenticate as root and look at the most recent log in `/var/lib/postgresql/12/main/log`
