### ISSUE TITLE
apt-get update shows 404 on odoo source

### ISSUE THREAD

**Issue by ajayver** [odoo/odoo#10886]
I'm following the debian installation steps from [here](https://www.odoo.com/documentation/9.0/setup/install.html):
`wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/9.0/nightly/deb/ ./" >> /etc/apt/sources.list
apt-get update && apt-get install odoo`

And on the apt-get update stage i get this:

> Hit http://nightly.odoo.com ./ Release.gpg
> Ign http://nightly.odoo.com/9.0/nightly/deb/ ./ Translation-en
> Ign http://nightly.odoo.com/9.0/nightly/deb/ ./ Translation-en_US
> Ign http://nightly.odoo.com/9.0/nightly/deb/ ./ Translation-ru
> Hit http://nightly.odoo.com ./ Release
> Ign http://nightly.odoo.com ./ Packages
> Ign http://nightly.odoo.com ./ Packages
> Err http://nightly.odoo.com ./ Packages
>   404  Not Found
> W: Failed to fetch http://nightly.odoo.com/9.0/nightly/deb/./Packages.gz  404  Not Found
> 
> E: Some index files failed to download, they have been ignored, or old ones used instead.

Then if i try to run apt-get install odoo, the response looks like this:

> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package odoo is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'odoo' has no installation candidate
> 
> 

I tried using apt-get clean and retry, but nothing changes.

Is it a bug or am I doing something wrong?

Thank you!

**Comment by sle-odoo** [comment]
could you type

        sudo apt-get clean

and retry?

**Comment by ajayver** [comment]
Thank you for the fast response!
I do everything under root on that machine. I know it is a bad practice, but anyway, tried
`sudo apt-get clean
sudo apt-get update`
and got the same result :(
I'm not a linux pro, but it looks like file http://nightly.odoo.com/9.0/nightly/deb/Packages.gz is not available but needed.

**Comment by gdgellatly** [comment]
It is correct the file Packages.gz is not available, but apt should be
downloading the file Packages.  If I had to guess Packages is failing a
checksum check or something like that, in which case the next step would be
to check for existence of Packages.gz to try and rebuild Packages.  The 404
is not the error, the error is the failing to download Packages, which is
the previous line.

**Comment by sle-odoo** [comment]
Well if i type 

        apt-get update
        apt-cache policy odoo

i have this output
```
11:32 $ apt-cache policy odoo
odoo:
  Installed: (none)
  Candidate: 9.0c.20160212
  Version table:
     9.0c.20160212 500
        500 http://nightly.odoo.com/9.0/nightly/deb ./ Packages
```

Everything seems to be working fine on my side.

**Comment by ajayver** [comment]
Thank you for your effort. 

Is odoo compatible with Debian 5? I just tried to install it on latest Debian and there were no issues...

**Comment by sle-odoo** [comment]
I'm not sure that even if you manage to make the repository comptible with debian lenny, all the dependencies will be present in the repositories :(

There is no plan to support this version of Debian as it is an obsolete stable. Sorry about that.

Regards

**Comment by gdgellatly** [comment]
It's a Debian bug. Google it and you might find a solution.

**Comment by sle-odoo** [comment]
Closing as the issue does not appear in the Debian releases we are supporting.
Regards
