### ISSUE TITLE
Human Resources not creating employee records correctly

### ISSUE THREAD

**Issue by ethanfurman** [odoo/odoo#1088]
In 7.0, The 'hr' module creates the employees private data (home phone, home address, etc) as a res.partner record, but does not set the 'employee' field to True, and defaults the 'customer' field to True.  Anyone with access to customer records therefore also has access to private employee data.

If the person entering the records remembers to turn off the 'customer' setting, there is still no way to turn on the 'employee' setting, and either way the forms that access res.partner will display 'employee' records unless extra care is taken to exclude them using domain filters.

I suggest adding the private data fields directly to hr.employee so there is no chance of accidently displaying them in a res.partner view.

**Comment by Yenthe666** [comment]
Hi @ethanfurman,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
