### ISSUE TITLE
[16.0] any user can edit discussion channels settings

### ISSUE THREAD

**Issue by bosaeed** [odoo/odoo#108861]
Impacted versions: ODOO 16

Current behavior: any user can change channels settings and remove members and add members

Expected behavior: admin need to do this

**Comment by RiteshSerpentCS** [comment]
![image](https://user-images.githubusercontent.com/76728462/210200287-fc660baa-72e4-45bd-b41f-b4893fedb029.png)


![image](https://user-images.githubusercontent.com/76728462/210200448-72306e0f-542c-45d7-b0d5-df2b4f437381.png)



There is a difference between public channels and private channels.

Any user can create and update public channels.

**Comment by RiteshSerpentCS** [comment]
![image](https://user-images.githubusercontent.com/76728462/210201082-ae4acea9-606b-4e69-85d5-eac408ab6312.png)

**Comment by RiteshSerpentCS** [comment]
In Private channels, users can update their own channels.

**Comment by bosaeed** [comment]
OK thanks I did not know that
