### ISSUE TITLE
[9.0] Frontend field changes were not correct saved when the website default language is not english

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#10883]
Hi all,
#### Impacted Versions:
- 9.0
#### Steps to reproduce
1. Open a runbot v9 instance
2. Install a second language
3. Go to Website Admin -> Configuration
4. Change the default language from english to the second language
5. Open any blog post page in the frontend, switch to the second language, click on edit, change the blog post title / subtitle and save
#### Current behavior

It seems that the changes weren't saved. But if you switch to the english language you will see that the changes were applied to the english blog post title / subtitle.
#### Expected behavior

The blog post title / subtitle changes should be applied to the second language.

**Comment by rruebner** [comment]
Hi @Gorash, please have a look at it because I know a fix for it but I don't know if this fix is valid because it reverts one of your fixes.
If I revert commit https://github.com/odoo/odoo/commit/6ebcc061523b60bb81aa837f93ce2f2a03f6d37f the problem is gone.
What do you mean?

**Comment by Gorash** [comment]
I'll watch it, but the language should be removed during editing due to changes in the framework. There was even a warning from the front when the language was in the context.

**Comment by Yenthe666** [comment]
Hi @rruebner,

Thanks a lot for your bug report.
This is actually still the case in the latest V9. @JKE-be for your interest!

Regards,
Yenthe

**Comment by rdeodoo** [comment]
Fix landed [here](https://github.com/odoo/odoo/commit/b2b71efb365b08677fb6fa0cd83f4adec28c8da8)
