### ISSUE TITLE
This field invoice_line_tax_ids doesn't exist anymore on odoo14

### ISSUE THREAD

**Issue by lorenzoallegrucci** [odoo/odoo#108866]
This field invoice_line_tax_ids doesn't exist anymore on odoo14, but it's still used here:
https://github.com/odoo/odoo/blob/14.0/addons/web/static/tests/core/py_utils_tests.js#L978

Impacted versions:
odoo14

Steps to reproduce:
run tests on the web module

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by matteoopenf** [comment]
@Yenthe666  what do you think about that?

**Comment by Yenthe666** [comment]
@qdp-odoo @smetl I think you guys might want to take a look 😄

**Comment by matteoopenf** [comment]
> @qdp-odoo @smetl I think you guys might want to take a look smile

thank you @Yenthe666

**Comment by smetl** [comment]
The web unit tests are not triggering any rpc. This test doesn't need to be a valid orm model. Btw, the test is in `web` and not in the `account` module. I ran the test to be sure of that.
