### ISSUE TITLE
[9.0] Portal user does not always see Quotations in 'Quotation Sent' stage

### ISSUE THREAD

**Issue by antonybrugger** [odoo/odoo#10888]
**Impacted Versions:**
9.0e

**Steps to reproduce**

Open a runbot v9e instance
Logging in as Admin
Go to Sales/Quotation
Create a new Quotation with Customer=Demo Portal User and One product like iPod
Click on 'Print' Button => Quotation stage is automatically put in 'QUOTATION SENT' stage 

**Current behavior**
Logging in as Demo Portal User (portal/portal)
-> Here there is no direct access to th portal backend interface ! Only via Claims menu but Claims module has to be installed! So acces via direct URL
Demo user is not seeing the new Quotation made!
If with user Admin I go to the quotation ans click on the button 'SEN BY EMAIL' and send it, the Demo user Portal see his new quotation!

**Expected behavior**

Portal users should see all Quotations in 'QUOTATION SENT' stage , either we have send it by mail or click on the 'Print' button

**Comment by Yenthe666** [comment]
Hi @antonybrugger,

Thanks a lot for your bug report.
I've just tested this and it is actually still the case.
The example quote:
![image](https://user-images.githubusercontent.com/6352350/34984450-4f3f70b6-fab1-11e7-81cb-9c68c5f076f4.png)

The portal user his portal:
![image](https://user-images.githubusercontent.com/6352350/34984394-1cabfde0-fab1-11e7-9249-f82a29b68963.png)

The backend portal:
![image](https://user-images.githubusercontent.com/6352350/34984433-3c22db4e-fab1-11e7-82a8-5296fc4834df.png)

@JKE-be can you check please?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Portal in backend is deprecated for the new portal when you install website_portal_sale

To be visible in 'My quotations": the conditions are:
    - Be in 'Sent Quotation'  stage
    - **AND** be follower of the sale_order (what is done eg when you create send the sale order to a partner, the partner become followers)

It is the expected behaviour from what I see in the code if you want, you are free to change it in your own code, simply adding the partner_id from sale order into the follower with an automated action or ... or you can also do a simple custom in the python controller ...
