### ISSUE TITLE
[9.0] Mutli Company + Partners Rules

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#10890]
User A is part of Company A (allowed companies is just Company A) and Company A has many partners.

User B is part of Company B (allowed companies is just Company B) and Company B has many partners.

User A sees all the partners from Company A and B.
User B sees all the partners from Company A and B.

Upon closer inspection, [this rule](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/security/base_security.xml#L94) does not get loaded into the database for some weird reason.

**Comment by adekock11** [comment]
Tested this on Odoo 9.0 Runbot as well. Same result. A user from a different company can see all the partners. If I add the rule manually, I get expected behaviour.

**Comment by gdgellatly** [comment]
I'd say the rule gets loaded, it just needs to be activated, but then
whenever you update it, it will change back.

see this line
<field name="active" eval="False"/>

Means the rule is not active, so if you do a search it will be there if
your advanced search condition contains active = False.  Of course why that
is the case I have no idea.

**Comment by gdgellatly** [comment]
Actually it is here

https://github.com/odoo/odoo/commit/275234c06796ababf5bfb5356e8d216c8aea81c7

Thats a pretty major behaviourial change for a stable version.

**Comment by adekock11** [comment]
Thanks for you feedback! Based off what you said I saw that the commit you are referring to adds a Shared Resources checkbox on the General Settings view, which will activate/deactivate the Partner and Product company rules based on whether the Shared Resources checkbox is checked or not. 

You have to be in the "Multi Company" group to see the checkbox though. [Link](https://github.com/odoo/odoo/blob/9.0/addons/base_setup/res_config_view.xml#L74). Take a look at the screen shots below:

Without Multi Company enabled
![screen 1](https://cloud.githubusercontent.com/assets/1809451/12999866/702a61e4-d15c-11e5-9bdf-88862bc9b67e.JPG)
With Multi Company enabled
![screen 2](https://cloud.githubusercontent.com/assets/1809451/12999867/74945d70-d15c-11e5-9245-91dfe56918ca.JPG)

**Comment by adekock11** [comment]
PS: The [rule](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/security/base_security.xml#L94) will not change back to inactive if you update the server, since it is in a noupdate="1" [data tag](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/security/base_security.xml#L86)
