### ISSUE TITLE
[16.0] point_of_sale frontend: no auto-scroll down when adding many products

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#108967]
Impacted versions: 16.0

Steps to reproduce:
1) connect to runbot v16
2) start a POS session
3) in the POS frontend, on a POS order, add many products ; when the POS order lines take all the screen, it doesn't auto-scroll down ; so the cashier doesn't see the products he is adding in the order !

This video illustrates the bug:

![bug_pos_v16](https://user-images.githubusercontent.com/1157917/210262980-a6e9bd01-b37a-4708-a566-5a110afe31b1.gif)

On 14.0 and 15.0, the cashier is always able to see the last POS order line he added.

**Comment by alexis-via** [comment]
The bug happens both on Firefox and Chromium.

**Comment by alexis-via** [comment]
Code analysis:
in Odoo 15.0, the auto scroll down is managed by the variable scrollToBottom in Screens/ProductScreen/OrderWidget.js, which is set to true on this line of code:
https://github.com/odoo/odoo/blob/15.0/addons/point_of_sale/static/src/js/Screens/ProductScreen/OrderWidget.js#L79

in Odoo 16.0, the variable scrollToBottom still exists, cf
https://github.com/odoo/odoo/blob/16.0/addons/point_of_sale/static/src/js/Screens/ProductScreen/OrderWidget.js#L16
but it is never set to true!

**Comment by pedrambiria** [comment]
Hello,

Thanks for reporting this bug. I've created a fix for it.

Regards,

**Comment by alexis-via** [comment]
@pedrambiria Thanks ! It works well. To apply your patch on v16, I just had to change the first line of the diff with:
```
const { useEffect } = require('@odoo/owl');
```

**Comment by alexis-via** [comment]
The fix has landed in 16.0.
