### ISSUE TITLE
The margin of the invoices hides part of the information from the header when printing

### ISSUE THREAD

**Issue by pablohmontenegro** [odoo/odoo#108994]
Impacted versions: 15.0

Steps to reproduce: 

1) Install argentine localization (l10n_ar_edi module) in runbot enterprise 15.0 .
2) Print an existing customer invoice or vendor bill, for example: vendor bill with number FA-C 00001-00000008 (this bill is created by demo).

Current behavior:
When printing the invoice, part of the information from the header is hidden. For example: if the invoice number is FA-C 00001-00000008 then when printing the invoice the letter C is briefly hidden on the top of the page.

Expected behavior:
When printing the invoice the information should not be hidden by the margin. For example, if the invoice number is FA-C 00001-00000008, the letter C should not be hidden on the top of the invoice and that letter should be shown completely.

Video/Screenshot link (optional):
![Captura desde 2023-01-03 09-18-43](https://user-images.githubusercontent.com/89547436/210356661-070ebee0-d8a6-4646-ae23-2ebb994c459d.png)
![Captura desde 2023-01-03 09-19-05](https://user-images.githubusercontent.com/89547436/210356686-281bc2c6-e113-4d1d-95c2-a790769718ac.png)
  Video:
  https://drive.google.com/file/d/1g9Y6hTw7qw5OrwvWQ4C5kVzkinWmVDfG/view

Support ticket number submitted via odoo.com/help (optional):

**Comment by pablohmontenegro** [comment]
@vbe-odoo Hi Valentino! I submitted task #3117373 on https://www.odoo.com/ .

**Comment by vbe-odoo** [comment]
@pablohmontenegro Hi Pablo! Thanks for opening the ticket in Odoo and the issue here.
I will add this as a reference in the ticket, thanks!

**Comment by pablohmontenegro** [comment]
@vbe-odoo hi Valen, this pr solves the problem mentioned in this issue:
https://github.com/odoo/odoo/pull/112549

**Comment by qdp-odoo** [comment]
It seems a very small part of the letter is still missing

current:
![image](https://user-images.githubusercontent.com/7628598/218710213-14ef63de-6d5b-41c2-8b4c-414fab3d4ef6.png)

proposed: 
![image](https://user-images.githubusercontent.com/7628598/218710436-41c4d566-6bf2-4c5c-9991-38d0329eaff8.png)

with 35px:
![image](https://user-images.githubusercontent.com/7628598/218710630-a651ec60-3235-4812-9ab0-512c6fa5294d.png)

**Comment by vbe-odoo** [comment]
This was already resolved in this PR: https://github.com/odoo/odoo/pull/112549
