### ISSUE TITLE
Many2one default - strange behaviour

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#10906]
I use in my module:

```
company_id = fields.Many2one('res.company', string='Company', change_default=True,
    required=True, readonly=True, states={'draft': [('readonly', False)]},
    default=lambda self: self.env['res.company']._company_default_get('stock.picking.wave'))
```

This code I copy!!! from account_invoice  

When I update module from web backend - no problems  (and no errors in log)

When I update all modules from command line - system crash with error:

...
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 286, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2585, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2401, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 429, in <lambda>
    lambda recs: self.convert_to_write(value(recs))
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 1594, in convert_to_write
    return value.id
**AttributeError: 'int' object has no attribute 'id'**

After this I set 

```
  default=3         # 3 = ID of my children company
```

and update all modules from command line - no problems.

Consternation!?!  In my module not works, in account_invoice works?!? after one update works after other no?!?! both is int type?!?! where problem?!

I found this discussion: https://github.com/odoo/odoo/issues/4384 

quote: "I confirm that default values for relational fields must return a recordset."

Finally my code:

```
company_id = fields.Many2one('res.company', string='Company', change_default=True, required=True, readonly=True, states={'draft': [('readonly', False)]},
    default=lambda self: self.env['res.company'].browse(self.env['res.company']._company_default_get('stock.picking.wave')))
```

works without problems.

Questions:
1) Why in my module first code durning "update all" crash, but account_invoice no?
2) Why, at the same time, works default=3
3) Is my finally code right or not?  

PS. Field company_id should be defined in standard in stock.picking.wave

**Comment by andreparames** [comment]
(Note: I'm not an official Odoo dev, just an occasional contributor)

(1) is probably because all Invoices already have company_ids, therefore no default is needed, therefore the bug isn't triggered.

(2) is because Odoo auto-detects if the default is a regular value or a function, and expects an ID in the first case but a recordset in the latter case.

**Comment by zbik2607** [comment]
@andreparames  (1)  After next update, when all company_ids are set in my model (for example after first setting default=3), error is still reported. (2) It is possible but unexpected and confused in this case.

**Comment by adekock11** [comment]
@andreparames +1

**Comment by cinxgler** [comment]
My issue is related, I have a Many2one field where I get a default value from the context:

    default=lambda self: self._context.get('edt_id', None),

I have several fields like that but strangely just some fail when i'm installing my custom module, not when i'm updating it.

They work when change the openerp/fields.py:1700

    def convert_to_write(self, value):
        return value.id

to 

    def convert_to_write(self, value):
        if value:
            return value.id
        return False

To no modify the odoo core code i've opted to do this, in the fields that fail:

    default=lambda self: self._context.get('edt_id', type('',(object,),{'id': False})()),

**Comment by andreparames** [comment]
@cinxgler since the API is expecting a recordset, you can probably return an empty one, e.g. `self.env['other.object'].browse()`.

**Comment by cinxgler** [comment]
@andreparames definitely better, thanks

**Comment by JKE-be** [comment]
@andreparames 
FYI: 
    self.env['other.object'].browse() == self.env['other.object']

**Comment by pedrobaeza** [comment]
Closing as this is an old/new API compatibility glitch, which is no more on >=v10, and there are published workarounds.
