### ISSUE TITLE
[all Version] When admin without adding customer add a product in order line  unit price should be add in order line 

### ISSUE THREAD

**Issue by lakhantester** [odoo/odoo#109037]
Impacted versions: All version 

Steps to reproduce:

 1. Add any  product in order line without adding any customer 
 2. Then add any customer and then click on save button 
 3.  Unit price showing is 0 in order line 
 
Current behavior:

Product Unit price is showing is **zero** in order line 

Expected behavior:

product unit price should be showing in order line 

Video/Screenshot link (optional):
https://prnt.sc/5XyuOJ11bLq_

https://user-images.githubusercontent.com/112851713/210504854-f844c8a8-04fe-498f-b8bb-c3d93c3a6636.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by badbole** [comment]
Technical answer:
onchange partner, sets the currency, pricelist, fiscal position and other data relevant for price calculation.... 
so... price of 0 is not a surprise... 

Practical answer:
Did you ever created an sale order, or been present while someone does it?
It ALWAYS start with partner data... it is regular process flow for any document.. 
First you fill the relevant data on main document,
then you add document lines... 
And this applies to sale order, purchase orders, pickings and most of other documents in any erp :)

So this is more an RTFM problem than a real issue :)

**Comment by lakhantester** [comment]
@badbole Odoo17 solve this

**Comment by vava-odoo** [comment]
Hi @lakhantester 
I agree with @badbole, this is not a bug.
Cheers.
