### ISSUE TITLE
[9.0c] Accounting Dashboard - Journals in foreign currency express balance in company currency but using foreign currency sign

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#10912]
In Odoo 9C, 

Steps to reproduce:
- Set up a company with base currency HK$.
- Create a new Journal 'Cash USD' that uses foreign currency USD
- Enter a journal entry and express 5  USD as currency amount, and 3 in HK$
- Go to the accounting dashboard and display the dashboard for 'Cash USD'. 

Expected result:
-  Balance should be expressed as 5 USD

Actual result:
- Balance is expressed as 3 USD

**Comment by alpseber** [comment]
I have the same issue.

**Comment by csnauwaert** [comment]
Hello,

Sorry for the delay to answer this issue, I've tried reproducing your use case in the latest 9.0 community and I face no problem. The balance on the journal is expressed as 5 USD. 

Seems like the bug has been fixed, therefore I'm closing this issue.

Best regards
