### ISSUE TITLE
Request feature: Chatter box in forms must be editable for a limited time

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#10913]
Basecamp allows user to edit their comments to discussions for up to 15 minutes after posting. I think you should also implement this feature to the chatter box in form views. Thanks!

**Comment by jholze** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@JKE-be are you still considering this as a good feature? It's complicated when the sent mails are involved.

I think there are other better features like auto-save drafts (for not losing what is written when losing connection or accidentally refreshing browser), or delay a bit the sending for allowing to cancel the sending.
