### ISSUE TITLE
Account type missing in v16

### ISSUE THREAD

**Issue by PsKs** [odoo/odoo#109140]
I need to bring Account Types menu back to v16 it possible? Because i need to add more account type. 

And why they remove on v16?

**Comment by netfxtech** [comment]
![image](https://user-images.githubusercontent.com/62037189/210849906-695c5016-accf-4217-9ed4-5980800640ba.png)
Is there account type here? I got to this easily by just clicking "create" or "setup" via the chart of accounts.

**Comment by PsKs** [comment]
Sorry for my poor English.
I mean add new type of account type.
As you see in red box.
I need add new type in red box.
<img width="1506" alt="Screen Shot 2023-01-06 at 10 14 58" src="https://user-images.githubusercontent.com/7805237/210923275-9bb73a8d-9b24-4275-b44f-958bb7a4aeed.png">

**Comment by niyasraphy** [comment]
hi @PsKs ,
from 16 the account type field has been changed to selection from many2one field from this commit:  https://github.com/odoo/odoo/commit/26b2472f4977ccedbb0b5ed5f08be2c04313fd21

thanks

**Comment by PsKs** [comment]
Thank.
