### ISSUE TITLE
General Settings menu unclickable

### ISSUE THREAD

**Issue by Gorkygd** [odoo/odoo#10923]
When I try to add a submenu below the General Settings in Settings, the General Settings menu becomes unclickable on v9 

		<menuitem id="open_custom_settings" name="Custom"
			parent="base.menu_config" action="open_custom_settings_menu" />

My menu is indeed inserted below General Settings but the General Settings (although still there) are unclickable

**Comment by Yenthe666** [comment]
Hi @Gorkygd,

The code that you show is custom development and this is not handled in the Odoo issues.
If you still face this problem I'd suggest you to post this question on the official Odoo help forum (help.odoo.com).

Regards,
Yenthe
