### ISSUE TITLE
[9.0 & 9.0E] Invalid EAN13 barcodes are ignored and there is no more support to generate custom EAN13 barcodes

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10921]
**Invalid EAN13 barcodes are ignored and there is no more support to generate custom EAN13 barcodes**

Impacted versions:

 - 9.0 and 9.0 Enterprise

Steps to reproduce:

 1. Create a new product with the barcode '1234567891234' then click on save.
 Result in V8:
![image](https://cloud.githubusercontent.com/assets/6352350/13042180/712f2980-d3be-11e5-9ce1-2c74eab81b4b.png)
Result in V9:
![image](https://cloud.githubusercontent.com/assets/6352350/13042204/ab2dd0e6-d3be-11e5-8b0d-d2d873eb94eb.png)

The barcode is not validated in Odoo 9 / Odoo Enteprise and there is no longer an option to generate a custom EAN13 barcode.
![image](https://cloud.githubusercontent.com/assets/6352350/13042254/1dff6d78-d3bf-11e5-9a50-60597465f016.png)

Current behavior:
 - No validation of barcodes and no possibility to generate custom barcodes.

Expected behavior:
 - Automatic validation of barcodes and the possibility to generate custom barcodes, just as in V8.

**Comment by Yenthe666** [comment]
@xmo-odoo and @odony could somebody have a look at this? I also have an enteprise support contract so where should I leave a reference/number to get this escalated?

**Comment by JKE-be** [comment]
Hello @Yenthe666 
We decided to support other codes than ean13... so the code has been removed https://github.com/odoo/odoo/commit/32fcfa6. 
You can always do it easily in a custo.

**Comment by Yenthe666** [comment]
@JKE-be thanks for the feedback.
Why hasn't the choice been made to split this up? Two options under settings: 'EAN13 validation' and another option 'Free barcode format' or something? This would give Odoo both usecases and flexibility to the end customer.

**Comment by mart-e** [comment]
@Yenthe666 if you want to use your support contract (which is obviously fine), just open a ticket directly. As stated in the [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing) issues have a much lower priority, especially if not critical.
This code has been removed at 809144f8a205520b85edffe12adf0f4fe1b8945a and 46652b0ba512e41fc8a3c5996931dd23a27d0c2e so it is definitely intentional to no longer check it and will not fall in the "bug" category. Adding a selection for the format is another level of customisation and will add more complexity. #FeatureRequest

**Comment by Yenthe666** [comment]
@mart-e I was already afraid that this wouldn't fall under the bug category.. Is there any way to label this as a feature request and to keep this 'issue' open?
Perhaps this is something we can add in Odoo 10? I think that both EAN13 checks and other barcodes would give the wanted behaviour/options for everyone.

**Comment by mart-e** [comment]
@Yenthe666 don't you think we already have too many open issues? There is already a "wishlist" label for new features (but used as a reason to close an issue).

I don't say that Odoo SA makes always the good choice and sometime we may go back but from time to time we remove some features between version to simplify the process/interface and we know it won't satisfy everyone but it's a choice that has been made. If you don't understand the reason or disagree, you may contact the support.
[Myth #12: More choices and features result in higher satisfaction](http://uxmyths.com/post/712569752/myth-more-choices-and-features-result-in-higher-satisfac)

**Comment by JKE-be** [comment]
Hello, 
Odoo try to provide a generic solution.

EAN13 = European Article Numbering 
What about Out of EU people ? 
Why not use UPC instead ... Universal Product Code ?

You can easily and quickly create a module which add ean13 feature for your usecases.
But we cannot impose to everybody to use it.
