### ISSUE TITLE
Unable to change EUR currency

### ISSUE THREAD

**Issue by martin-bailey** [odoo/odoo#10938]
With a fresh 9.0c Odoo setup and the CRM app installed, changing EUR to another currency such as GBP has no effect. Logging out and trying again produces the following message : 
Odoo Warning - Validation Error
The currency code must be unique!

**Comment by lukebranch** [comment]
@martin-bailey ,

I'm just another Odoo user like yourself, however i'll give you my suggestions no how to fix your issue.

If you setup a fresh database you'll need to define the currency rates yourself for each currency.

By default the base currency is EUR, and the base currency rate is 1.0 from what I understand.

To modify the currency you need to enable technical features/debug mode. To do this click on your Username in the top right of the backend (in my case it was 'Administrator') then do the following:

1) Click: About
2) Click: Activate the developer mode
3) Go to: Accounting > Multi Currencies > Currencies
4) Find your currency (eg. HKD), edit it and tick the 'Active' box, then save and click the 'View Rates' button on the top of the page.
5) Here you'll be able to specify the rate for that currency from a particular date to the decimal accuracy of six digits, for example:
1.000000

This had me stumped when I first started playing around with 9.0 when the documentation didn't exist.

As a side note, make sure to also specify your base currency in:

Accounting >> Settings

this is what all your other accounting will be based on so it's important you define whatever currency your company operates in or does their accounting in (in my case this was HKD as my business is located in Hong Kong).

For future reference though please note that the github issues are for reporting bugs/issues with the code itself and therefore should not be used for general questions.

For questions i'd recommend hitting the forums here:

http://help.odoo.com

and joining the community mailing lists to ask the question there:

https://www.odoo.com/page/odoo-community

For better visibility for actual bugs with Odoo i'd ask that you close this issue and ask any future questions in one or both of these two places instead.

**Comment by martin-bailey** [comment]
Luke, that was very helpful! Thank you so much.
