### ISSUE TITLE
[8.0] - Apps down

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#10933]
Steps to reproduce;
Go to Settings -> Modules -> Apps -> then search for a certain app and click on the title/name of this app. The following message is raised: 

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Apps/Manager
- Apps/Manager
- Apps/User

(Document model: loempia.module.purchase)

**Comment by Yenthe666** [comment]
@jdegoy thay model (loempia.module.purchase) is not a default Odoo module so it is likely that you've added some code that triggers this behaviour. Either way, this is an access right issue.
@mart-e locky-lock?

**Comment by jdegoy** [comment]
@Yenthe666 please try first on your own runbots or clean instances before assuming...

**Comment by Yenthe666** [comment]
@jdegoy I revert my statement. I was testing this on a V9 which didn't have this issue.What a strange issue..
@odony where is this coming from? I've never seen this before.

**Comment by dmo-odoo** [comment]
Hello,
In 8.0, Settings > Modules > Apps is the appstore, which has this loempia.module.purchase model.
@Yenthe666 In 9.0, Apps > Apps (without Technical Features) corresponds to the Settings > Modules > Local Modules of 8.0 which is not the appstore, this is why you didn't see it in 9.0 (even though you would have seen it with the Technical Features).

I have fixed the issue at the appstore level, it was my mistake, thank you for your report.

**Comment by Yenthe666** [comment]
:+1 and sorry for my mistake @jdegoy
