### ISSUE TITLE
Pricelist in Point of Sale and Ecommerce

### ISSUE THREAD

**Issue by kihiuho** [odoo/odoo#1093]
Pricelist of promotion with min. quality > 1 is not working in Point of Sale and Ecommerce

**Comment by SBollatti** [comment]
+1

**Comment by jholze** [comment]
:+1:

**Comment by jholze** [comment]
@kihiu2003 do you have tested it on master branch too ?

**Comment by ah-taktik** [comment]
For the POS you can tru this module : https://github.com/OCA/pos/tree/8.0/pos_pricelist

**Comment by glenerik** [comment]
Any Solution?

**Comment by wainaze** [comment]
+1

**Comment by irfanshk80** [comment]
@AdilHoumadi 

doesnt pick the price when used with module "Point Of Sale - Product Template"

**Comment by moleculezz** [comment]
Has this been solved in Odoo 10?

**Comment by yostashiro** [comment]
@moleculezz It seems the issue has been solved with this fix https://github.com/odoo/odoo/commit/c8a434306f110bfb5e5ce71609e8e096a850d309 for eCommerce.  Haven't checked the behavior with POS.

**Comment by deltammx** [comment]
I'm using 8.0-20170517. Similar bug.
When you make an order in the back-office  - discount price list works, when you buying  through the website  - discount price list does'nt work.
The fix [c8a4343](https://github.com/odoo/odoo/commit/c8a434306f110bfb5e5ce71609e8e096a850d309) was did not help.

Need more information / video / help in solving this bug?

**Comment by Yenthe666** [comment]
Hi @kihiuho ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: It should be fixed in newer versions.

Regards,
Yenthe
