### ISSUE TITLE
[v8] ORM error: @api.depends does not recognize computed fields of one2many fields

### ISSUE THREAD

**Issue by forvas** [odoo/odoo#10943]
`@api.depends` does not trigger a compute method if it depends on a computed field of a one2many field.

Example:

`@api.depends('child_ids', 'child_ids.computed_field')`
`def compute_other_field(self):`

`child_ids` triggers the method rightly, but not `child_ids.computed_field`.

**Comment by intero-chz** [comment]
Just for information: The computed field is stored to database or not?

**Comment by forvas** [comment]
I tried both ways, with store=True and store=False, and the problem always happen.

Note: the model in which I did the tests (account.asset.asset) has an one2many field `childs_ids` pointing to itself (an asset can have several assets children).

**Comment by dlsuarez** [comment]
I have just faced the same problem.

Any solution??

**Comment by PeterA-OpusVL** [comment]
I am also coming across this problem today.

**Comment by slimit** [comment]
I think I have the same issue on v10

**Comment by Yenthe666** [comment]
Hi @forvas ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
