### ISSUE TITLE
[8.0] Search inactive product with internal reference impossible

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#10944]
Hi,

We notice it's impossible to search a product based on its internal reference if it's inactive.

Please see related video recorded on runbot: https://youtu.be/pM2Wkrpc2cc

Regards

**Comment by Cedric-Pigeon** [comment]
OPW-669624

**Comment by avw-odoo** [comment]
Hi,
Internal reference is a related field from Product Variants. If you have more than 1 variant the field disappear. If you try the same search by the variante menu you'll find your inactive product with the internal reference.

**Comment by Cedric-Pigeon** [comment]
OK but the product variants menu is only accessible with Thechnical
features right.
If you want to reactivate a product and you only have the internal
reference. How do you that ?

**Comment by avw-odoo** [comment]
If you want to use "internal reference" in this way (for template), maybe you can use the "description" field in addition to do that (description is only for internal informations). In addition you can change search view to add description; Like this your flow is like you want.

**Comment by Cedric-Pigeon** [comment]
This is too tricky and really disturbing for the end user. He will not understand why he can't use the internal reference field.

I only have one variant for each product and I don't understand why it works when the product is active and why It don't work if the product is inactive, even if I active=False in my search.

For me this is a bug.

**Comment by intero-chz** [comment]
I would say deactivating the variant would lose the relation between template and variant (client side) from the point of the template. So Odoo just does not find a variant to get the internal reference from.

I don't think that is a bug, just a big conceptual problem with the active mechanism.

**Comment by beledouxdenis** [comment]
Hello Cédric,

We do not consider this issue as a bug.

The internal reference of the product template field will be filled when the template as one, and only one, variant.

If a product has only one variant, and this variant is disabled (without disabling the product itself), you will see that the internal reference is not filled as well. As the variant is disabled, the product is considered as having no variants, and therefore no internal reference could be displayed. In addition, when you disable the product itself, its variant is disabled as well, and, therefore, a disabled product is considered having no variant, and therefore no internal reference.

Even though we would consider this as a bug (and we are not), attempting to solve it would remain in the fact to compute the related field while passing `{`active_test`: False}` in the context, so disabled variants are considered in the computation of the internal reference. This would lead to a change of behavior: If you have a product with multiple variants, but only one activated, the internal reference is displayed, currently. If we compute this related field while disabling the active test, this will no longer be the case. Such a change of behavior is not accepted in a stable release. For more information about our stable policy, you can read the below documentation:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

I hope you will understand.

Regards,
