### ISSUE TITLE
[9.0 & 9.0E] Ability to set default project stages is removed

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#10959]
**Ability to set default project stages is removed**

Impacted versions:
- 9.0 & 9.0 Enterprise

Steps to reproduce:
1. Go to project > settings > Stages and open up a stage:
   ![image](https://cloud.githubusercontent.com/assets/6352350/13106428/74ba05b0-d568-11e5-9a96-a4440c0d8ff5.png)

There is no longer an option 'Default for New Projects' as there was in Odoo 8:
![image](https://cloud.githubusercontent.com/assets/6352350/13106459/ad7b58ea-d568-11e5-861a-187bb420cef6.png)

Current behavior:
- No option to set a default for new projects stage as in Odoo V8.

Expected behavior:
- Ability to define default stages for projects.

**Comment by JurreCl** [comment]
Its still missing in odoo 10. Is there any reason this is removed?

**Comment by Yenthe666** [comment]
Hi @JurreCl,

This was actually a decision made by Odoo and I don't think they want to change it again..
@mart-e could you give an official statement though?

**Comment by mart-e** [comment]
Hello,

Indeed, the default was removed at 8c1d1f5ce1ad1a1d85c2286b5e5a220a8d609321.
We have changed the way the stages works and rely on the sequence to specify the first stage.

**Comment by dreispt** [comment]
@JurreCl there is an OCA module restoring that feature: 
https://www.odoo.com/apps/modules/9.0/project_task_default_stage/
