### ISSUE TITLE
Taxes Dropdown Problem in Purchase Order Line, Sale Order Line, Customer Invoices and Vendor Bills

### ISSUE THREAD

**Issue by iju-odoo** [odoo/odoo#10955]
![screenshot from 2016-02-17 10 19 27](https://cloud.githubusercontent.com/assets/11677925/13100171/06395314-d560-11e5-9c0c-698fcb651ae7.png)

**Comment by flotho** [comment]
Hi @iju-odoo I have exactly the same issue,
Impossible to change/delete the taxes

**Comment by ovnicraft** [comment]
I confirm this bug.

**Comment by Yenthe666** [comment]
Hi @iju-odoo,

Thanks a lot for your report.
This is actually still the case in V9. While it is not a breaking bug it could be improved.
![image](https://user-images.githubusercontent.com/6352350/34983967-8ecc791a-faaf-11e7-99b0-75e47cdb3903.png)


@mart-e could we improve this? (not sure who to ping for this one)

Regards,
Yenthe

**Comment by mart-e** [comment]
It seems it is no longer the case in the newer versions. Sorry but this is minor, we are not going to modify the CSS of the end of life version for something like this.
