### ISSUE TITLE
Bank Statement: cannot reconcile lines where Resifual Amount is less than debit minus credit (typical when doing account netting)

### ISSUE THREAD

**Issue by okuryan** [odoo/odoo#10950]
Dear Odoo,

Recently we faced issue that doesn't allow to Reconcile Bank statement with partically reconciled line.
It is caused by the code https://github.com/odoo/odoo/blob/8.0/addons/account/account_bank_statement.py#L669

Specifically caused by the check:
abs(line.debit - line.credit) < abs(line.amount_residual)

Why we need this check? I do not see any logic behind it. What it says is: 

If left to pay amount is less than debit-credit on this line, than skip this line. I do not see the reason of this. It is quite often case when, for example, you do account netting (pay only difference between payables and receivables for same partner). 

If removing this line of code, reconciliation starts working fine.

Please, advise

**Comment by Yenthe666** [comment]
Hi @okuryan ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
