### ISSUE TITLE
Payment -> journal entry -> Reconciled Items button Traceback.

### ISSUE THREAD

**Issue by miteshsa-onnet** [odoo/odoo#109590]
Impacted versions: 16.0

Steps to reproduce: Create Payment (Accounting -> vendor -> payment)
set any amount and confirm payment.
click on journal item.

in journal item we have "Reconciled Items" smart button.
click on "Reconciled Items" smart button and traceback appears.

Current behavior: Gives Traceback

Expected behavior: Should open reconciled items.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/36949590/211646212-2720ed4b-4851-4483-8fb2-c161bdee7e1f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Fix is on the way:  https://github.com/odoo/odoo/pull/109276

**Comment by niyasraphy** [comment]
@miteshsa-onnet feel free to close the ticket
