### ISSUE TITLE
Odoo UI Hack - Can Visible UI Elements that have been Invisible  

### ISSUE THREAD

**Issue by SanathT** [odoo/odoo#10956]
When we want to create a view with having conditionally invisible elements, we are using domains for attributes.
eg:
`<field name="relationship_id" attrs="{'invisible':[('marital_status','not in',['1','2'])]}">`
When we see the implementation that functionality done by adding `oe_form_invisible` css class. We are making those fields invisible because they are confidential data. But we can simply bypass that invisible logic by removing `oe_form_invisible` css class, using browser "inspect element" feature. Any solution for that?

**Comment by JKE-be** [comment]
Hello, 
"We are making those fields invisible because they are confidential data." => It' a bad practice.
Invisible is just for comfort and clean screen (use for display/hide), and not for security. 
You can always use groups if you don't want the content in the dom ! But don't forget that the user can always access these data in rpc or from others views...

**Comment by SanathT** [comment]
Here consider a scenario like this. I want to invisible some details of for others. If I logged in only I can see them. If another user logged in they should not be able to see. Now all are in same group. Then only way I have is use domain for attrs right?

**Comment by JKE-be** [comment]
Yes, you can use attr invisible for it ... But, you just need to remember that your hide the value ... it's not a security... it's a visual effect. As you said, in one line of js, the user can read the infos using rpc.

**Comment by SanathT** [comment]
Do we have any other way to accomplish such requirements? I mean handle the security of a field conditionally?

**Comment by mart-e** [comment]
I advise you to check the following thread on mailing list: [Field security in odoo v8?](https://www.odoo.com/groups/community-59/community-16574796) (and [my answer](https://www.odoo.com/groups/community-59/community-16575168?mode=thread&date_begin=&date_end=)).
There is a very basic field level security but if you have highly confidential data, the best is to either put it on a different model or to implement hack as we did for passwords.

**Comment by SanathT** [comment]
Yes, As mart-e and others says, using group is the best way here. But my requirement is conditionally handle the security of a field for users in a same group. 
Like colleagues cannot see my GPA of my profile, but HR can view.
Here now we have two groups "Employee" and "HR" Me and  colleagues are in same group ("Employee") Now If I configured field as 
x_gpa :fields.integer('GPA',groups="base.group_hr_user")
only HR can access. Do we have a solution for such scenarios?
'name': fields.char('Comment', size=64),

**Comment by JKE-be** [comment]
you can set a groups that nobody have on your field.
An after, you add a new computed field which return the value according your own conditions.
Take a look here: https://www.odoo.com/documentation/9.0/reference/orm.html#field-computed

**Comment by SanathT** [comment]
Ah right. Then Who can enter the data to the field first?

**Comment by mart-e** [comment]
@SanathT Github issues are to report bugs. If you have problems with your dev, please ask on the forum, mailing list or ask support from Odoo SA or a partner.

**Comment by JKE-be** [comment]
You can use _inverse_function and check your security condition.
