### ISSUE TITLE
Auto fiscal positions not working

### ISSUE THREAD

**Issue by Nickske157** [odoo/odoo#10964]
Installed Odoo 9 and Odoo 8 with belgian accounting module. Company vat and country set to belgium
1. Enable automatic detection in Intra-Communautair and confirmed that country group is Europe and taxes are correct
2. I create a customer with correct vat id from netherlands 
3. I create an invoice with customer and random product with default tax 21%
4. When I select, save or validate invoice, the tax stays 21% -> needs to be 0%

Kind Regards

Nick
![fiscal positions](https://cloud.githubusercontent.com/assets/6742601/13109656/0d062d50-d57b-11e5-9269-fb8d7b0daa97.PNG)
![invoice](https://cloud.githubusercontent.com/assets/6742601/13109655/0d04e68e-d57b-11e5-91fa-3bd627c20e71.PNG)

**Comment by pedrobaeza** [comment]
This doesn't work with VAT numbers, but with the country set on the partner. Closing as probably not a real bug.
