### ISSUE TITLE
[9.0] navbar: active class is not added to all entries

### ISSUE THREAD

**Issue by Fl0rianFischer** [odoo/odoo#10966]
## Affects Versions
- v9
- runbot
## Steps to reproduce
1. Go to homepage -> menu entry "home" in navbar gets class active
2. Create a new page
3. Go to page
## Current behavior

Currently the active class is only added to the default odoo pages. When adding new pages through the frontend or by using templates, the active class is not added and menu entries cannot be styled accordingly.
## Expected behavior

Add active class to the 'li' element if the page is currently selected.

**Comment by JKE-be** [comment]
@Fl0rianFischer Cannot reproduce

![menu-active](https://cloud.githubusercontent.com/assets/4848797/13171316/62fcf2c0-d6f2-11e5-9f0d-2c4ad6a8dcfe.gif)

**Comment by Yenthe666** [comment]
Closing as we both cannot reproduce it and as there has been no response.
