### ISSUE TITLE
[16.0] Page speed slower when using non-english profile 

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#109723]
Impacted versions: [odoo 16.0]

Steps to reproduce:
・Change the profile's language to Japanese Language (or other languages)
・Go to Purchase, click Orders -> Purchase Orders
・Click Orders -> Request for Quotation
*You may try to access back to Orders -> Purchase Orders
*This issue happens when the records approximately more than 100 records, instead, the speed difference could not be detected
*The page speed is slower compared to Odoo V15

Current behavior:
If we use English profile, the page speed is faster when we access to the pages.
but when using other languages, the speed is slow.

Recording on runbot:
https://drive.google.com/file/d/1-F822jKg5-uCJNvqQkTrMYME_sePdKmt/view

Support ticket number submitted via odoo.com/help (optional):

@qrtl

**Comment by yostashiro** [comment]
@rinaldifirdaus I suppose the issue is not specific to purchase orders.  Can you confirm this and perhaps update the title to avoid confusion.

**Comment by rinaldifirdaus** [comment]
> @rinaldifirdaus I suppose the issue is not specific to purchase orders. Can you confirm this and perhaps update the title to avoid confusion.

Yes, this issue is not only specific to purchase orders.

**Comment by kanda999** [comment]
@rinaldifirdaus 
We cannot realize this problem without some records (about 100 records). Can you please add that it is slower compared to V15?

**Comment by Yenthe666** [comment]
@JKE-be who could verify this?

**Comment by kanda999** [comment]
Checks and unchecks also seem much slower compared to V15.  
Here is a video comparing V15 and V16 of odoo runbot. 
https://user-images.githubusercontent.com/101688144/212269114-b7039f66-cc75-4db4-a53c-9f3995138f65.mp4

**Comment by JKE-be** [comment]
maybe @HydrionBurst will have an idea ?

**Comment by JKE-be** [comment]
After check internally, @aab-odoo and @sdegueldre is aware and will take a look.

Thanks for reporting
