### ISSUE TITLE
[16.0 E] [Critical] Traceback: whole dashboard app breaks/down  

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#109715]
Impacted versions: [odoo 16.0 E]

Steps to reproduce:
- Create a Filter based on any date between from search view of any model  (e.g Sales order)
- Save it in the dashboard now by giving any name
- Reload the browser, Go to Dashboards > My Dashboard.
- Just do any action (e.g hide/show some columns) and reload

Current behavior:
- its breaking down the whole dashboard app, we can't get back into the dashboard in any way.
- all existing dashboards are also not opening due to that. and throwing traceback.
- 
Expected behavior:
- It should not show any traceback.
- 
Video/Screenshot link (optional):
[Recording of Runbot 16.0 E] (https://drive.google.com/file/d/1d1Kcm0BOKKuqAh8esF6DFssJXGcIvz4P/view?usp=share_link)

![image](https://user-images.githubusercontent.com/36708909/211913708-06d405c0-0d71-4206-bc45-13c5e26ea291.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by rrahir** [comment]
Fixed in https://github.com/odoo/odoo/pull/110662
