### ISSUE TITLE
Crm Lead - probability default - notification problem

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#10977]
The default value in model crm.lead for field **probability**  should be set to **0.0**
In other case the _track:

'crm.mt_lead_create': lambda self, cr, uid, obj, ctx=None: **obj.probability == 0** and obj.stage_id and obj.stage_id.sequence <= 1,

is not triggered when Lead is created, when email is fetched from server (in this case probability = NULL)

**Comment by pedrobaeza** [comment]
This was modified some time ago and it's now working, so I close:

https://github.com/odoo/odoo/commit/b27333919ad5deb464093f72554d82d080c35ed3

Regards.
