### ISSUE TITLE
Run Schedulers does not finish

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#1098]
The procurement scheduler does not complete most of the time.

**_Impacted versions:**_
- 7.0 at least

**_Steps to reproduce:**_
1. Populate a database with many orderpoints and procurements. The scheduler takes 30 to 40 minutes to complete when it completes. (without `mrp_jit`)
2. Go to Warehouse > Run Schedulers
3. Run the scheduler without Automatic orderpoint

**_Current behavior:**_
- The scheduler often stops after some minutes. The logs show: 

```
openerp.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.

openerp.sql_db: ConnectionPool(used=0/count=3/max=16): Free leaked connection to 'host=192.168.0.71 user=xxxxx
password=xxxxxxxxxxxxxxxx dbname=xxxxx'
```

The fact that it sometimes finish and sometimes not is worrying. Also, I observed that it completes on my dev server or more generally when one or only a few users are connected. My suspicion is that, as the scheduler is threaded, another request is interfering with the thread (but only an idea).

**_Expected behavior:**_
- The scheduler completes.

**Comment by fred0716** [comment]
There is the same error message - openerp.sql_db: Cursor not closed explicitly
When Run Schedulers in My Odoo 8 MRP.
Does anyone know how to fix the problem?

**Comment by talespadua** [comment]
cr.close()

**Comment by Yenthe666** [comment]
Hi @guewen ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
