### ISSUE TITLE
[7.0] Missing requirements.txt

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#10988]
Version 7.0 is missing a requirements.txt file, this is very helpful when using `virtualenv`.

Can you please add it?

**Comment by sle-odoo** [comment]
Hello,
We don't plan to add it. We tend not to add that kind of changes in v7.

Regards

**Comment by aristobulo-eezee** [comment]
@sle-odoo why not? Is not a code change, just a simple requirements.txt with packages and supported versions
