### ISSUE TITLE
[9.0] separate purchase order(created by procurements) error [because of vendor is out of stock]

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#10981]
Impacted versions:
- 9.0

Steps to reproduce:
1. create a new product (with two vendors)
2. create a new sale order (3 units)
3. confirm sale order
4. generate purchase order by running schedulers [Inventory => Report => Run Schedulers] 
5. A vendor only has 1 unit of product, so change qty to 1, plan to create a new purchase order (B vendor) manually
6. Finish A purchase order with 1 unit of product
7. create another purchase order with 2 unit of products and finish it 
8. create a new sale order again (10 units)
9. Run Schedulers

Current behavior:
![qq 20160218154940](https://cloud.githubusercontent.com/assets/11750796/13136772/540493e0-d657-11e5-8f1c-123e5e55c5a7.png)
- procurement order (WH: Input -> Stock) is done, In fact,its purchase order [PO00074] only buy 1 unit of product
  - another procurment order (Procurement Location is WH/Stock) can't be done or canceled. raise exception (You cannot cancel a stock move that has been set to 'Done'.)
  - After step 7. the computed qty of purchasing is always less 2 units than expectation

![qq 20160218155716](https://cloud.githubusercontent.com/assets/11750796/13136892/4ee3588c-d658-11e5-914c-66880993e286.png)
- always lost 2 units, can't generate procurement order  by running schedulers

![qq 20160218155757](https://cloud.githubusercontent.com/assets/11750796/13136929/8b813728-d658-11e5-9953-b86af9e3a3f5.png)

Expected behavior:
- when the product qty of purchase order line is same as procurement order line, set stock_move  and procurment_order record done

**Comment by pedrobaeza** [comment]
I consider that this kind of tricks for you to get the proper stock are not correct, as links are not preserved. Any way, all the procurement stuff has been simplified on v11, and maybe your flow is now covered. Please check on that version, and report back about that. I'm closing meanwhile.
