### ISSUE TITLE
Pos Load all remaining partners in the background

### ISSUE THREAD

**Issue by composercodes** [odoo/odoo#109892]
Impacted versions:
v 16
Steps to reproduce:
Load all remaining partners in the background 3000000 customers
Current behavior:
pos hang while Loading all remaining partners in the background
Expected behavior:
no hang
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @composercodes ,
seems this has been fixed by this commit:  https://github.com/odoo/odoo/commit/23ea63fd9771a899427e41869cceedec64b883be

can you confirm and if this okay now, can you close the ticket.
thanks
