### ISSUE TITLE
CSS mt/mb class is ignored in PDF report

### ISSUE THREAD

**Issue by komsas** [odoo/odoo#10987]
Lets take an example sale order report. I've attached two example, [sale_with_wkhtmltopdf.pdf](https://github.com/odoo/odoo/files/135976/sale_with_wkhtmltopdf.pdf) was rendered directly to PDF, [sale_without_wkhtmltopdf.pdf](https://github.com/odoo/odoo/files/135977/sale_without_wkhtmltopdf.pdf) printed to HTML (added like PDF).

Tested with 9.0, wkhtmltopdf 0.12.1

**Comment by efarias** [comment]
I have the same problem, class mt/mb is ignored. Any news?

**Comment by GillPotter** [comment]
I have got around the problem by using "margin-top" and "margin-bottom".

**Comment by efarias** [comment]
@GillPotter can you show me an example? i have this:
```
<div class="page">
    <div class="col-xs-2 col-xs-offset-9 mt32"><p>date</p></div>
...
```

the _"col-xs-2 col-xs-offset-9"_ works fine, but the _mt32_ it's not working. How can i use the "margin-top" in this situation?
Thanks for share

**Comment by efarias** [comment]
OK, i got it in this way and working fine:

```
<div class="page">
     <div style="margin-top:100px;" class="col-xs-2 col-xs-offset-9"><p>date</p></div>
...
```

**Comment by GillPotter** [comment]
Glad you found it, an example I used: 
`<div class="row" style="margin-top:32px; margin-bottom:16px;">`

**Comment by Khwunchai** [comment]
@efarias You can also do it using custom css/less file so you don't have to do it repeatedly. Still, it just a work around the issue. The problem still exists and has to be fixed.

**Comment by sle-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/8703d8c11d810a39f14426d9d34a49a9fcdf4b1c

Regards
