### ISSUE TITLE
[16.0] Duplicate Contact Tag: New tag assigned to partners with the original tag

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#109906]
Impacted versions: [Odoo 15.0 & 16.0]

Steps to reproduce:
・On Contact apps -> Open partner that have Contact Tags is set (Example in runbot: Azure Interior, tags: Services)
・On the other tab, open configuration -> Contact Tags -> open Services
・Click Action -> Duplicate, then change the name of the Tags (e.g. Headquarter)
・Refresh Azure Interior page. 

Current behavior:
When we duplicate a contact tags record, the new tag is automatically assigned to the partners with the original tag.
It will become problematic when the Users duplicate a tag which assigned to many contact records.

Expected behavior:
When duplicate a contact tags record, it should not be assigned to any contact. (Treated as a new Contact Tag)

Recording on Runbot:
https://drive.google.com/file/d/1LUKqPDCxz-L5WVG5jETzPsl6zsA85T3s/view?usp=sharing

Support ticket number submitted via odoo.com/help (optional):

@qrtl

**Comment by niyasraphy** [comment]
hi @rinaldifirdaus ,
fixed by:  https://github.com/odoo/odoo/commit/1ffc047127be174399beafd79bd470bf50f3e4e1

feel free to close the ticket.
thanks
