### ISSUE TITLE
[9.0] purchase order line selects vendor bug

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#10991]
Impacted versions:
- 8.0
- 9.0

Steps to reproduce:
1. create a new product (with two vendors)
2. sale one
3. run scheduler to create purchase order

Current behavior:
- new purchase order line always choose first vendor

purchase.py line:814

``` python
@api.multi
def make_po(self):
    cache = {}
    res = []
    for procurement in self:
        suppliers = procurement.product_id.seller_ids.filtered(lambda r: not r.product_id or r.product_id == procurement.product_id)
        if not suppliers:
            procurement.message_post(body=_('No vendor associated to product %s. Please set one to fix this procurement.') % (procurement.product_id.name))
            continue
        supplier = suppliers[0]
```

The first supplier is default, and there isn't purchase order created now, so there isn't order line

``` python
if not po_line:
    vals = procurement._prepare_purchase_order_line(po, supplier)
    self.env['purchase.order.line'].create(vals)
```

``` python
@api.multi
def _prepare_purchase_order_line(self, po, supplier):
    self.ensure_one()

    seller = self.product_id._select_seller(
        self.product_id,
        partner_id=supplier.name,
        quantity=self.product_qty,
        date=po.date_order and po.date_order[:10],
        uom_id=self.product_uom)
```

the supplier name is same as default supplier(the first supplier) will be  choosed

Then if others procurement orders want to create purchase order line in this purchase order, the supplier must be same as purchase order's partner

``` python
for line in po.order_line:
        if line.product_id == procurement.product_id and line.product_uom == procurement.product_uom:
            seller = self.product_id._select_seller(
                self.product_id,
                partner_id=partner,
                quantity=line.product_qty + procurement.product_qty,
                date=po.date_order and po.date_order[:10],
                uom_id=self.product_uom)
```

and  not seller , not price

``` python
price_unit = self.env['account.tax']._fix_tax_included_price(seller.price, self.product_id.supplier_taxes_id, taxes_id) if seller else 0.0
```

my purchase order

![qq 20160218193418](https://cloud.githubusercontent.com/assets/11750796/13142331/42f5ee6c-d677-11e5-8401-66f6c592d1b8.png)

my product

![qq 20160218193517](https://cloud.githubusercontent.com/assets/11750796/13142332/430d4346-d677-11e5-8039-c3cc29ce49c8.png)

Thanks

**Comment by sle-odoo** [comment]
Hi,
It selects according to the sequence, so the create_date does not matter. You can reorder the supplier info in the purchase tab.

Regards
