### ISSUE TITLE
9.0 - Missing menu for configuring Tags on Analytic Account (account.analytic.account.tag_ids)

### ISSUE THREAD

**Issue by Damnet** [odoo/odoo#10993]
Hello,

I can't access any menu entry to configure tags on analytic account.

Tx.

**Comment by stephaniemillet** [comment]
This field can be access only through TImesheet > Configuration
Or Accounting > Configuration > Analytic account
Then you select an analytic account and 
 you can see this field for a tag on the form of analytic account
But there is nowhere / no menu, to configure theses values for tags , especially delete one.

![account analytic account_tags_ids](https://cloud.githubusercontent.com/assets/12233420/13213063/85731af4-d946-11e5-9cf9-17fab0c8384c.png)

**Comment by pedrobaeza** [comment]
On latest Odoo version (v11), you find the menu entry in Invoicing / Configuration / Analytic Accounting / Analytic Tags, so we can consider this solved, although not in the version 9. You can always add the menu yourself in your DB from models form view.
