### ISSUE TITLE
Sale Order Line: Move Note or Section

### ISSUE THREAD

**Issue by DieterReinert** [odoo/odoo#109934]
Impacted versions:
16.0

Steps to reproduce:
Try move Note or Section on Sales Order

Current behavior:
Error:
Cannot read properties of undefined (reading 'style')

Expected behavior:
Move the note / section to where i drag it

Video/Screenshot link (optional):
https://i.imgur.com/LgLqK71.png

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
@h4818 Could you take a look please ? :pray: 
Moving a section or note with the handle widget in an Account Move (or Sales Order ofc) raises a strange traceback.
![image](https://user-images.githubusercontent.com/19364378/212714595-3ea96615-0e52-4230-87bc-f97fa8e841df.png)

**Comment by h4818** [comment]
No issue in master (16.0 only)

**Comment by h4818** [comment]
@Feyensv 👆
