### ISSUE TITLE
No reporting on the state of the Scheduler

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#1099]
When a user launches the procurement scheduler, it has no mean to know:
- if it completes
- if it fails
- when it is complete

This is especially inconvenient when the user suffers from bugs such as #1098 
Previous versions creates a report (res.requests) so this is perceived as a regression for users. BTW the feature has been badly removed because we can still see traces: https://github.com/odoo/odoo/blob/7.0/addons/procurement/schedulers.py#L112

**_Impacted versions:**_
- 7.0+

**_Steps to reproduce:**_
1.  Go to Warehouse > Run Schedulers
2.  Run the scheduler

**_Current behavior:**_
- No reporting on the state of the scheduler. Users are really stressed about that.

**_Expected behavior:**_
- Have a way to know at least:
  - if it completes
  - if it fails
  - when it is complete

**Comment by Yenthe666** [comment]
@sle-odoo I believe this is still accurate and is in fact the case for all schedulers. There is no way to know if one succeeded or failed, if I'm not mistaking you can only see this from the logfiles (if you add log statements to the scheduler).
Is there anything planned for this?

**Comment by sle-odoo** [comment]
@Yenthe666 there's no plan to change that at the moment

**Comment by Yenthe666** [comment]
Hi @guewen,

As this bug report is against a very old version that is no longer supported and as there is no plan to change it at the moment (see comment above me) I'm closing this bug report.
As it is labelled wishlist it will keep popping up every once in a while though!

Regards,
Yenthe
