### ISSUE TITLE
OdooRPC unable browse record in V16

### ISSUE THREAD

**Issue by mehdihj** [odoo/odoo#109938]
Impacted versions:
16.0
Steps to reproduce:
- Exemple -
`
```
import odoorpc

odoo = odoorpc.ODOO('localhost', port=8069)
odoo.login('my_database', 'admin', 'admin')

exemple = odoo.env["account.move"]
x= exemple.search([("id", "=",1)])
y = exemple.browse(x)
```

`
Current behavior:

**raise error.RPCError(
odoorpc.error.RPCError: keys must be str, int, float, bool or None, not frozendict**

Expected behavior:

Get record

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by abdelghani-khalidi** [comment]
any one can resolve that ?

**Comment by RLeeOSI** [comment]
I encountered the same problem. It's coming from http.py make_json_response(), where it tries to call json.dumps() on a frozendict (probably self.env.context). You might fix this with a patch to http.py that looks for frozendicts and converts them to str.

I was able to get around this by calling the method through execute_kw:
```python
import odoorpc
odoo = odoorpc.ODOO('localhost', port=8069)
odoo.login('my_database', 'admin', 'admin')
example = odoo.env['account.move'].browse(1).action_post() # Fails because browse returns error
example = odoo.execute_kw('account.move', 'action_post', [[1]], {'context': odoo.env.context})
```

**Comment by vava-odoo** [comment]
From what I understand, it looks related to https://github.com/odoo/odoo/issues/129494, solved by https://github.com/odoo/odoo/commit/cc61b926f4daff26fb577e2f700d013ec15f4b4f
Don't hesitate to open the issue again if it is not the case.
Cheers
