### ISSUE TITLE
[9.0]New procurement requests creating new moves in backorder instead of creating a new stock picking

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11008]
**Impacted versions:**
9.0
Multi company an multi warehouse configuration
WHA (compA)
WHB (CompB) this one resupply from WHA

**Steps to reproduce:**
- Create multiple procurements orders from WHB. 
- Check that both delivery and incoming shipments are correctly set
- Deliver partially in WHA => create backorder
- Recieve partially in WHB => create backorder
- Create a new procurement Order from WHB

**Current behavior:**
The new procurement generate a move placed in the initial demand of a backorder. So it's impossible to reserve it

**Expected behavior:**

The move has to be placed in a new stockpicking as the backorder should be considered as an "already validated" tarnsaction

**Comment by flotho** [comment]
Hi @odony ,

Do you think it could be a bug.

regards

**Comment by odony** [comment]
@flotho that sounds like a bug, but you probably want @jco-odoo to reproduce/confirm it :-)

**Comment by flotho** [comment]
@odony thanks

Hi @jco-odoo , I have many little bugs on warehouse resupplying in multi company mode and this one is really annoying and I don't know where to patch.
This bug causes move to be inserted in picking and they do'nt appearing as new moves in nw stock picking.
regards

**Comment by jco-odoo** [comment]
Multi-company or not, lines can always be added to a picking, so to a backorder too.  In v9 to the point where you printed the picking.  (in v8, until at least something is assigned)

**Comment by flotho** [comment]
Hi @jco-odoo 

(To precise the context I was talking about automatic procedure thanks to routes etc..)
So if I understand well, adding a new line in initial demand should be always available from your point of view. 
As far I could test I think we have another problem. I'll try to explain it correctly, correct me if I'm wrong.
Once a backorder is generated, operations are defined and it's no more possible to edit the initial demand. So if the scheduler/route add a product on the initial demand of a backorder, it will never be possible to reserve it and make it appears on the operations. 
The only way to do this is to to force reservation and in this case too many lines are appearing in the operations to validate and some have already been delivered in the original demand.
That's really confusing to see moves added to original demand without appearing on the operations.

Did I miss something?

regards

**Comment by flotho** [comment]
Hi @jco-odoo , Hi @odony 

I think that #11021 will partiallly solve the problem but not at all and I would like to have your point of view on this.
My point is that a delivery/picking is a kind of "coherent set of operations", for example once your order 100 ref in a PO, you'll have 100 lines in the receipt. I you receive partially the goods, you'll create a backorder. I would be _really really_ difficult for operators to track the origin if the scheduler add moves in initial demands, in this case, backorder that have been created could still opened because of new moves etc...
I totally understand that technically it could be possible to add some goods **by hand** in the initial demand (even if I'm not recommend it to my customers), yet it shouldn't be the same with automatic process. The scheduler and other routing tool _mustn't_ add moves in picking that are backorders.
It's really confusing for the end user to see his pickings never ending....

Please give us your advice and point of view, it's a really hard day for interwarehouse users...

**Comment by pedrobaeza** [comment]
@flotho did you get this?

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
