### ISSUE TITLE
selection field with integer stored values defined in a function don't work

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#11015]
Impacted versions: 9.0 at least

Steps to reproduce:

In code define a field like this:

```
class MyModel(models.Model):
    _name = "my.model"

    @api.model
    def _market_state_get(self):
        return [(0, _('Writing')),
                (10, _('Signed')),
                (1, _('Done')),
                (20, _('Abandoned')),
                ]

    market_state = fields.Selection('_market_state_get')

```

install the module in database

Current behavior:

the field market_state in the my_model table is of type character varying

Expected behavior:

the field market_state in the my_model table is of type integer, as if I had defined the field like this:

```
    market_state = fields.Selection(
               [(0, _('Writing')),
                (10, _('Signed')),
                (1, _('Done')),
                (20, _('Abandoned')),
                ])
```

**Comment by pedrobaeza** [comment]
Seeing code, it seems that this is still happening due to the way it's performed:

https://github.com/odoo/odoo/blob/6fb59b23378d05ad59621cf5094dfbe02a311ba5/odoo/fields.py#L1738-L1744

But I'm not sure that this can be achieved, as for calling the selection method, you need the full environment loaded, and in this stage is still not available.

@rco-odoo can you confirm this? Maybe you can add an extra parameter that can be used in the `else` part for forcing the PG type?

**Comment by gurneyalex** [comment]
also 0 in these fields conflicts with "unset" which is a real pain when dealing with external systems which have enums for states.

**Comment by elgow** [comment]
The check whether self.selection is a list can lead to confusion if one tries to define the selection list as an immutable tuple and use integers as the codes stored in the DB. It would be nice if tuple were supported in addition to list. This presumes that there's no thought of providing a single tuple for a one-item selection list, but that seems not so useful.

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
