### ISSUE TITLE
Project Managers can delete Stages by accident

### ISSUE THREAD

**Issue by dumblob** [odoo/odoo#11016]
Impacted versions:
8.x

Steps to reproduce:
Create few Odoo projects with each having few tasks in each of it's stages. Then select arbitrary project, make sure you're switched to Kanban view of tasks (it's a default view) and by clicking next to an arbitrary stage label on the _down arrow_ and selecting "Delete" from the drop-down list remove the stage.

This bug has been reported already on https://bugs.launchpad.net/openobject-addons/+bug/1221124 , but I didn't find it here on Github :(

Current behavior:
This actually removed the stage from all existing projects and without asking all tasks in this stage in all projects disappeared.

Expected behavior:
Removal of only the stage in this particular project. Also it would be nice if there was a confirmation dialog (with preselected "No") in case there are some tasks in the stage.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @dumblob,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@sseerrggii can you please create a new report with the steps on how to reproduce the issue.
