### ISSUE TITLE
Relational fields problem : res.users and res.partner.

### ISSUE THREAD

**Issue by ZiedHf** [odoo/odoo#11011]
Hi there,

I have a problem when I try to add Relational fields in this Tuto : https://www.odoo.com/documentation/9.0/howtos/backend.html 
It's an official documentation. 

Until the section of "Relational fields" I have no problem, everything's looking fine.
Then, in the exercice of "Relational fields", Many2one res.users don't works, I mean this line : 
`responsible_id = fields.Many2one('res.users',
        ondelete='set null', string="Responsible", index=True)`

It show me 500 Internal Server Error and I have the same error with : 

`instructor_id = fields.Many2one('res.partner', string="Instructor")`

Otherwise, in the same exercice, when I add only this code in session class and remove the two lines above : 
`course_id = fields.Many2one('openacademy.course',
        ondelete='cascade', string="Course", required=True)`

That's works well. I didn't find any good solution on net. Any help please ?

Those two file show me the error written above :
My Models.py file : 
> from openerp import models, fields, api
> class Course(models.Model):
>     _name = 'openacademy.course'
>     name = fields.Char(string="Titre de cours", required=True)
>     description = fields.Text()
>
> 	```
responsible_id = fields.Many2one('res.users',
>         ondelete='set null', string="Responsible", index=True)
```
>
> class Session(models.Model):
>     _name = 'openacademy.session'
>     name = fields.Char(required=True)
>     start_date = fields.Date()
>     duration = fields.Float(digits=(6, 2), help="Duration in days")
>     seats = fields.Integer(string="Number of seats")

For openacademy.xml, see attached file.
[openacademy.txt](https://github.com/odoo/odoo/files/137688/openacademy.txt)

**Comment by Yenthe666** [comment]
@ZiedHf this is not really an Odoo issue, but a question. Please ask it on the Odoo help forums so people like us can help you there :smile: 
The Github issues are really created for bugs and problems in Odoo itself.
@mart-e locky-lock.

**Comment by ZiedHf** [comment]
Well, sorry :)

**Comment by Yenthe666** [comment]
@ZiedHf no problem. Create a question on the official Help forums, try to add the __openerp__.py code etc too and you should have a response within hours!
Best of luck.

**Comment by madux** [comment]
Yenthe666 this issue is an odoo problem

**Comment by Yenthe666** [comment]
Not really, if you update your module from the command line it'll work just fine (`-u your_module`)
