### ISSUE TITLE
[8.0, 9.0] POS customers list does not scroll on firefox

### ISSUE THREAD

**Issue by haroldtamo** [odoo/odoo#11020]
Impacted versions: 8.0, 9.0

Steps to reproduce: launch Point of sale interface on firefox (tested on runbot 8 and 9 and firefox 44.0.2)

Current behavior: customers list doesn't scroll

Expected behavior: we should be able to scroll on customers list like on chrome

Video/Screenshot link (optional):

**Comment by gaelTorrecillas** [comment]
You did'nt change the css of this list? because if you change the value of a CSS attribute with an incorrect value, chrome ignores this value, and save the old value (if it's correct) while firefox save your new value, if it's false, the attribute is ignore.

the css attribute is overflow

**Comment by haroldtamo** [comment]
Thanks for your answer,

I check it also on runbot. Since i could not change css on runbot (in code) i think it's not related with my code. anyway, i'll check again.

**Comment by gaelTorrecillas** [comment]
hello, 

I use 44.0.2 and I work on odoo but I test my dev on firefox

**Comment by haroldtamo** [comment]
And you don't have the problem mentioned above ?

**Comment by gaelTorrecillas** [comment]
no, but I had the opposite problem, I described it above.

**Comment by sibuxiang** [comment]
Same bug is happening in Odoo v10 with latest Firefox 50
