### ISSUE TITLE
[8.0] Bug on reservation and reserve/unreserve lot.

### ISSUE THREAD

**Issue by lbellier** [odoo/odoo#11028]
Impacted versions: V8

Steps to reproduce:
- Create delivery order
- Change delivery method to "Partial" if necessary
- Clic on "Check Availability" (you need to have 1 product missing or with not enough stock)
- Clic on barcode interface
- Close barcode interface and return on the delivery order
- Change delivery method to "All at once"
- Clic on "Check Availability"

Current behavior:
- Wrong quantity of product is reserved each time you clic on "Check Availability".
- because odoo unreserve quants, the production lot and source location of product can be different between 2 clic on "Check Availability". (not on video). 

Expected behavior:
Must reserve only missing products (quantity), and keep reserved production lot and source location.

Video link (optional):
https://youtu.be/SFAO_Cyu4yA

**Comment by josemoralesp** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @lbellier ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
