### ISSUE TITLE
[9.0] Fancifull translation on main Wizard

### ISSUE THREAD

**Issue by laurentmeuwly** [odoo/odoo#11024]
Impacted versions: 9.0 enterprise

Steps to reproduce:
1. go to "settings"
2. from the dashboard, go to "implementation", and click on "Accounting"
3. you receive the "Welcome" wizard
4. click on Your Company on left menu

Current behavior:
For all options, you have the possibility to edit them, via the "Change" link.
On the same view, but in German, the link is named "Wechselgeld".
This also mean "change", but in a financial point of view (Exchange money)

Expected behavior:
In German, the link should be named "Ändern" (with the meaning "modify")

Video/Screenshot link (optional):
![traductions](https://cloud.githubusercontent.com/assets/8449115/13176179/58f7eb4a-d710-11e5-8ff7-ec15f1d5f605.png)

**Comment by mart-e** [comment]
Hello,

For the discussion of the translations, please check on Transifex (see [translation guidelines](https://github.com/odoo/odoo/wiki/Translations)) or see the discussion on #10500 with @wtaferner and @treviser
