### ISSUE TITLE
[IMP]allow to add char as  a column in pivot views

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11032]
Hi,

Is there a way to add string/char as a column in pivot view ?
The documentation seems to allow that with type="col" yet it doesn't work.

regards

**Comment by pedrobaeza** [comment]
@flotho are you sure this is not allowed? Please put an example.

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
