### ISSUE TITLE
No real ip in log behind Nginx proxy

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#11035]
Impacted versions: 8.0, 9.0

for more detail see this https://www.odoo.com/forum/help-1/question/howto-show-real-ip-in-werkzeug-log-if-openerp-serve-behind-reverse-proxy-61450

**Comment by dek-odoo** [comment]
This is not an odoo issue.

But doing this may help:

     1. Start odoo Server with --proxy-mode
     2. Edit your "nginx reverse proxy" configuration file with something like:
              proxy_set_header HTTP_X_FORWARDED_HOST $remote_addr;

For more see:
https://github.com/odoo/odoo/blob/9.0/openerp/service/wsgi_server.py#L181

**Comment by jl2035** [comment]
Still open, after one year?

**Comment by xmo-odoo** [comment]
@dek-odoo's answer seems correct, you need to start Odoo in proxy mode and ensure your proxy sends the relevant proxying headers. Odoo simply applies wraps the application in [Werkzeug's ProxyFix](http://werkzeug.pocoo.org/docs/0.11/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix).

**Comment by jl2035** [comment]
Damn! The solution doesn't work for me. :(

I always run Odoo in proxy mode and I have set every possible header in nginx configuration. IPs still missing in log file :(

**Comment by piqoni** [comment]
In my case I had to add to make it work:
``` proxy_set_header X-Forwarded-Host $host; ```

**Comment by miro-igov** [comment]
@xmo-odoo @dek-odoo Did you tested this solution? It does not work in Odoo 8.
I have set proxy_mode = True in config and proxy_set_header HTTP_X_FORWARDED_HOST $remote_addr;
Logs still show 127.0.0.1
2020-10-29 12:21:30,859 12760 INFO my_db werkzeug: 127.0.0.1 - - [29/Oct/2020 12:21:30] "GET / HTTP/1.0" 200 -

If i edit openerp/service/wsgi_server.py and change the code to:
`    if config['proxy_mode'] and 'HTTP_X_FORWARDED_HOST' in environ:
        _logger.info('ProxyFix OK')
        return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)`

I see in the log it prints ProxyFix OK so the condition is satisfied.

**Comment by penieldev** [comment]
> In my case I had to add to make it work:
> `proxy_set_header X-Forwarded-Host $host;`

This worked for me. Thanks.
