### ISSUE TITLE
[9.0] "Recommended" inventory valuation method is not the default

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#11038]
Impacted versions: Odoo Server 9.0c-20160220

Steps to reproduce:
1. Install Odoo server
2. Install Inventory Management
3. Go to Inventory | Setting
4. Look for Inventory Valuation section

Current behavior:
The 2 options are
"Periodic inventory valuation (recommended)" and "Perpetual inventory valuation (stock move generates accounting entries)"

however the recommend setting is not the default.

**NB** It is not cleat to me why the Periodic Inventory setting is recommended. Clearly there are pros and cons to both, and Odoo does not make recommendation for any of the other settings. Implicitly the default setting is the 'recommended' simpler setting, unless there is a compelling case for the improved functionality

Expected behavior:
- Recommend settind is the default
- Odoo either consistently makes recommendations about the settings or does not

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
Indeed these labels were a little misleading. This was changed in v11 to "manual" and "automated".

Regards
