### ISSUE TITLE
Display of wrong price decimal separator for product variants in frontend product detail page

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#1103]
Hi all,
#### Impacted Versions:
- 8.0
#### Steps to reproduce
1. If only one language is installed go to Settings -> Translations -> Load a Translation and load another language (e.g. German / Deutsch)
2. Check the settings for the decimal separator in Settings -> Translations -> Languages -> German / Deutsch (it should be ',')
3. If you have demo data installed check the product detail page of "iPad Retina Display" (otherwise create a product variant and check this product) in frontend
4. You will see a price in the format "100.00" instead of "100,00" - the problem is caused by website_sale/static/src/js/website_sale.js. There are some transformation like adding '.0' to the price which will overwrite the correct price format. Only the frontend product detail page is affected.

**Comment by tv-openbig** [comment]
@jholze @Yenthe666: This critical issue still exists.

**Another impacted version :** V9.

**Expected (correct decimal separator):**
<img width="507" alt="bildschirmfoto 2016-11-22 um 18 14 53" src="https://cloud.githubusercontent.com/assets/8348598/20534000/e0b1b1e8-b0df-11e6-81d1-1772fe467f6f.png">

**Currently the separator is wrong:**
<img width="474" alt="bildschirmfoto 2016-11-22 um 18 14 33" src="https://cloud.githubusercontent.com/assets/8348598/20534098/286b62d6-b0e0-11e6-84de-4f5c0efbe4f7.png">
