### ISSUE TITLE
Unable to use inter company in ODOO 9C

### ISSUE THREAD

**Issue by DidierLACOMBE** [odoo/odoo#11034]
Impacted versions:
9C
Steps to reproduce:

after installing intercompany and inter_compan_rules (from Master) 
SO in B never created after PO creation from A to vendor B

Current behavior:

SO/PO not created after PO/SO

Expected behavior:

SO/PO Created in A after PO/SO creation i n B

Video/Screenshot link (optional):

**Comment by flotho** [comment]
Hi @DidierLACOMBE ,

Obviously the intercompany is now an enterprise edition feature.

**Comment by DidierLACOMBE** [comment]
Hello
so why this parameters still exist in ODOO V9C ?

And they are not identified as entreprise edition feature at all 

Why ?

(They were available in ODoo 8)

Thanks

**Comment by DidierLACOMBE** [comment]
hello

so why the V9C has still the parameters to install this option ?



Didier Lacombe



didier.lacombe303@gmail.com

Tél  : 00 33 (0) 6 20 57 32 20
Fax : 00 33 (0) 4 78 42 11 58



2016-02-23 8:58 GMT+01:00 Florent THOMAS <notifications@github.com>:
