### ISSUE TITLE
[9.0] Sales team member removal removes system user

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#11040]
**Impacted versions:**
9.0

**Steps to reproduce:**
1) With demo data installed, go to Sales -> Configuration -> Sales Teams
2) Go to "Direct Sales" where Administrator and Demo are members of the sales team
3) Edit the record and remove Demo as a member of this team

**Current behavior:**
Upon saving the record, Odoo attempts to not only remove the Demo user from the sales team, but to completely delete the user from the system.

**Expected behavior:**
Only break the link between res.users and crm.team - do not remove the res.users record completely.

**Video/Screenshot link:**
![sales team](https://cloud.githubusercontent.com/assets/1809451/13210288/55adf2f4-d936-11e5-86a3-ac1d17fdc2d5.JPG)

**Comment by adekock11** [comment]
I see there is already a [pull request](https://github.com/odoo/odoo/pull/11023) regarding this issue.

**Comment by simongoffin** [comment]
Closed with 2a5be43
