### ISSUE TITLE
 Error Send A Email In Quotation

### ISSUE THREAD

**Issue by Anhlq87** [odoo/odoo#11045]
Hi everyone,

I have create a new Quotation in Odoo (Use root code of odoo). But when I click "send a email" the system show the error:

![image](https://cloud.githubusercontent.com/assets/9975164/13215546/0f1a5908-d991-11e5-95d1-f8e34817f3c3.png)

Please help me to solve it. Thank you very much.
(I installed wkhtmltopdf 0.12.1)

**Comment by Anhlq87** [comment]
Please help me to solve it. Thanks

**Comment by joolsr** [comment]
I would guess you have a problem with your wkhtmltopdf application on your windows box. I dont think this is a bug, you may do better on the forums to get help with this.

**Comment by Yenthe666** [comment]
Hi @Anhlq87,

As stated by @joolsr this is not an Odoo issue but you're facing problems with your wkhtmltopdf application. It looks like Odoo cannot find your Wkhtmltopdf.
Github issues are only for problems with Odoo itself though, not installations and configurations of dependencies.
If you still face this issue your best option is to post this on the official Odoo help forums (help.odoo.com) where other people can help you.

Regards,
Yenthe

**Comment by Anhlq87** [comment]
Thank you for your support to me. Your answer help me to solved it. thank you so much. :)

**Comment by Yenthe666** [comment]
Great to hear you've maneged to solve it! You're welcome.
