### ISSUE TITLE
Website payment: order could not be cancel if payment.transaction cancel

### ISSUE THREAD

**Issue by webgourou** [odoo/odoo#11059]
Impacted versions: 8.0

Steps to reproduce: on payment.transaction feedback if transaction is set to cancel, the order is not cancelled on route /shop/payment/validate because the function sale_get_transaction don't select the cancel transactions.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @webgourou,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
