### ISSUE TITLE
[8.0] [9.0] Odoo can't spawn workers in multiprocess mode in a virtual environment

### ISSUE THREAD

**Issue by funbaker** [odoo/odoo#11052]
Impacted versions:
9.0, 8.0

Steps to reproduce:
Install odoo into a python virtual environment, using a config with workers variable other than 1 (the default)

Current behavior:
Odoo loops with this error message:

> Expected behavior:ERROR ? openerp.service.server: Worker (6275) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/home/odoo/odoo_alive/odoo/openerp/service/server.py", line 708, in run
>     self.process_limit()
>   File "/home/odoo/odoo_alive/odoo/openerp/service/server.py", line 663, in process_limit
>     rss, vms = memory_info(psutil.Process(os.getpid()))
> ValueError: too many values to unpack

Video/Screenshot link (optional):

**Comment by funbaker** [comment]
Maybe is has to do with the behaviour of memory_info in a forked instance, instead of the virtual environment.

**Comment by NL66278** [comment]
It seems to impact 8.0 as well. I encountered the same problem.

**Comment by NL66278** [comment]
And actually I have to set workers = 0 to stop the problem. Having workers =1 makes no difference.

**Comment by stephen144** [comment]
This is an issue when using psutils >= 4.0. In 4.0 they added more values to the namedtuple that returns process memory information. The error is caused by lines that assume the tuple has exactly 2 values.
