### ISSUE TITLE
[9.0] odoo.py scaffold fails to create required __init__.py

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#11050]
Impacted versions:
9.0c-20160220

Steps to reproduce:

 1. Create a new module 'test' in the addons directory using 'scaffold' command: `odoo.py scaffold test /var/lib/odoo/addons/9.0/`
 2. Update the module list
 3. Search for module 'test'
 4. Install the module

Current behavior:

Odoo server error complaining about missing module 'test'

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 896, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
>     return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>   File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
>     registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 385, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
>     loaded_modules, update_module)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 123, in load_module_graph
>     load_openerp_module(package.name)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 324, in load_openerp_module
>     __import__('openerp.addons.' + module_name)
>   File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 60, in load_module
>     f, path, descr = imp.find_module(module_part, ad_paths)
> ImportError: No module named test

Expected behavior:

I expect the 'scaffold' command to create an installable dummy module.

Moving to the 'test' addon directory and creating an empty `__init__.py` (e.g. `touch __init__.py`) creates a module which can be installed in odoo.

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
Works for me using git checkout, how did you get/install odoo?

**Comment by Yenthe666** [comment]
@pjmcdermott works fine at my side too:
<img src="http://i.imgur.com/nc26uqg.png" alt="Scaffold"/>

**Comment by xmo-odoo** [comment]
@Yenthe666 seems to be a packaging problem, indeed when downloading tarballs from nightly (and I expect debs or rpms) the files are missing.

**Comment by pjmcdermott** [comment]
@xmo-odoo I am using a gentoo ebuild, which could of course be the problem. It was based on the nightly tarball from 20160202. I am downloading the current git version to do a check on that. But can you confirm your check was on 9.0c-20160220?

@Yenthe666 Was that using 9.0c-20160220?

**Comment by xmo-odoo** [comment]
> But can you confirm your check was on 9.0c-20160220?

Check was on git checkout, the tarballs are indeed missing the relevant files.

**Comment by Yenthe666** [comment]
@pjmcdermott I tested with 9.0c-20160222.
