### ISSUE TITLE
[9.0]Interwarehouse summary of issues - Global push rules are not reserving the quants + Access level issue

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11062]
# **Impacted versions:**

Latest v9 from git
Multi company and multi warehouse resupplying
tested with 2 companies (with or without link /dependences between them)
# **Steps to reproduce:**
### Configuration of the locations

Create a stockable product with stocks
Create 2 locations "out of stock"
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246059/95ab8188-da11-11e5-8974-a174cc589128.jpeg)
And : 
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246092/cafd9150-da11-11e5-9ef6-7d3a4d6e953e.jpeg)

Also create a transit location not affected to any company
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246144/1916b308-da12-11e5-92bc-58360c0feca0.jpeg)
### Configuration of the global push rules

Create a first push rule that will push in transit location
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246258/c4d5602c-da12-11e5-8ad3-997990a14779.jpeg)
Create a second one that wil receipt from the transit location:
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246338/535afbe0-da13-11e5-9345-a6fffd09bb2e.jpeg)

Please note the company on this latest rule

here is the summary :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246691/6fc71488-da15-11e5-87aa-33c0ea912f5c.jpeg)
### Process from source

Initiate the process with the creation of an internal move in MEX :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246432/d0d728f0-da13-11e5-8b60-e3e8676b32db.jpeg)
Once it's created the delivery is immediately planed in MEX and it's OK :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246456/031e6710-da14-11e5-9dbf-d9e79159881a.jpeg)
Once the internal is reserved, the delivery become available and it's Ok.
# **Current behavior 1 :**

No receipt are available in the BRI company, whatever and however the schedulers are ran , with our without jit.
# **Current behavior 2 :**

Change the company of the second push rule so that the new conf is as follow :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246737/c338ff8c-da15-11e5-9428-562039d60895.jpeg)
Rerun the process of internal transfer and you'll have this problem :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13246768/de9ce46e-da15-11e5-9c44-246573bffc71.jpeg)

Of course, doing all this this with admin works perfectly.
# **Expected behavior:**

No access level error OR a reservation that works with user restricted rights
# **My interpretation of warehouse issues**

From now a few issues are linked to this one and there is probably a big problem or a bad way of configuring but this is really not clear for us. @zbik2607 had also many issues of this kind in warehouse.

My point of view is that :
- There is some issues with access level ( #10572, #4956)
- There are some issues with the reservation of quant in multi company environment (#4627, #4837)
- There are some uncomfortable choice regarding moves affectations (#11008)

**Comment by flotho** [comment]
Hi @odony , @jco-odoo 

Please have a look to this summary, there is some general issues

**Comment by flotho** [comment]
Hi @zbik2607, 
what do you think of this?

**Comment by zbik2607** [comment]
In my opinion this is a general problem with access rights (between multicompany) during propagation requirements and moves. Several of these problems (in V8) I solved by adding a conditions like (location_id, in, (...)) or (rule_id,in,(...)) in settings ir.rules, and with modification standard default transit routes (for example parameter "Warehouse to propagate" and "Company"). Cron Mrp scheduler I copy  and execute with setting User with max rights per company. Now, I see next general problem: quants value propagation (for example when I invoicing intercompany transit).

**Comment by flotho** [comment]
@zbik2607 , thanks fro your feedback, very interesting workaround, but really really hard to configure when you have multiple locations...

**Comment by flotho** [comment]
@zbik2607 did you have any example of what you have implemented?

regards

**Comment by flotho** [comment]
Hi @jco-odoo , @nim-odoo 

Is there a chance to have an official position on this? Is there any bad conf from our side or is it a bug

**Comment by flotho** [comment]
Personnaly, 

I changed 2 things :
On this part of code : https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L476 I turned it into 
```
if move.location_id.company_id :
       domain += [('company_id', '=', move.company_id.id)]
```
So that for transit location without company set it becomes possible to reserve

Additionnaly, I set a SUPERUSER_ID on https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L2344
```
self._push_apply(cr, SUPERUSER_ID, moves, context=context)
```
So that push rule could be interpreted even when picking is validated by a restricted user

**Comment by zbik2607** [comment]
Push as SUPERUSER is probably not a good solution, in the general case. SUPERUSER.company_id = initial company A, but for example product price, move or quants values should be fetched from the other company B (user.company_id != SUPERUSER.company_id).

PS. My solutions are related to PULL methods, not PUSH as you need. There are also very specific and difficult for me to specify overall solution other than previously described.

**Comment by flotho** [comment]
Here is a proposal from karstenk on the IRC. It deals with multi company environment and MRP

```
class PlustronMrpProduction(models.Model):
    _inherit = 'mrp.production'

    location_src_id = fields.Many2one('stock.location', 'Raw Materials Location', required=True, readonly=True,
                                      states={'draft': [('readonly', False)]},
                                      help='Location where the system will look for components.',
                                      defaults=None)
    location_dest_id = fields.Many2one('stock.location', 'Finished Products Location', required=True, readonly=True,
                                       states={'draft': [('readonly', False)]},
                                       help='Location where the system will stock the finished products.',
                                       defaults=None)

    def get_prod_push(self, product):
        for route in product.route_ids:
            for push in route.push_ids:
                if push.location_from_id:
                    if 'production' in push.location_from_id.usage:
                        return push
                    else:
                        raise UserError(_(
                            "At least one production source location could not be find in product route!\nPlease create or activate one."))

    def _make_production_produce_line(self, cr, uid, production, context=None):
        stock_move = self.pool.get('stock.move')
        proc_obj = self.pool.get('procurement.order')
        destination_location_id = production.location_dest_id.id
        source_location_id = False
        picking_type_id = False
        procs = proc_obj.search(cr, uid, [('production_id', '=', production.id)], context=context)
        procurement = procs and proc_obj.browse(cr, uid, procs[0], context=context) or False
        if production.bom_id:
            push = self.get_prod_push(production.product_id)
            if push:
                source_location_id = push.location_from_id.id
                destination_location_id = push.location_dest_id.id
                picking_type_id = push.picking_type_id.id
        data = {
            'name': production.name,
            'date': production.date_planned,
            'product_id': production.product_id.id,
            'product_uom': production.product_uom.id,
            'product_uom_qty': production.product_qty,
            'product_uos_qty': production.product_uos and production.product_uos_qty or False,
            'product_uos': production.product_uos and production.product_uos.id or False,
            'location_id': source_location_id,
            'location_dest_id': destination_location_id,
            'move_dest_id': production.move_prod_id.id,
            'picking_type_id': picking_type_id or None,
            'procurement_id': procurement and procurement.id,
            'company_id': production.company_id.id,
            'production_id': production.id,
            'origin': production.name,
            'group_id': procurement and procurement.group_id.id,
        }
        move_id = stock_move.create(cr, uid, data, context=context)
        return stock_move.action_confirm(cr, uid, [move_id], context=context)[0]

    def _make_consume_line_from_data(self, cr, uid, production, product, uom_id, qty, uos_id, uos_qty, context=None):
        stock_move = self.pool.get('stock.move')
        loc_obj = self.pool.get('stock.location')
        source_location_id = False
        picking_type_id = False
        # Internal shipment is created for Stockable and Consumer Products
        if product.type not in ('product', 'consu'):
            return False
        # Take routing location as a Source Location.
        source_location_id = production.location_src_id.id
        destination_location_id = production.location_dest_id.id
        if production.bom_id:
            push = self.get_prod_push(product)
            if push:
                source_location_id = push.location_from_id.id
                destination_location_id = push.location_dest_id.id
                picking_type_id = push.picking_type_id.id
            else:
                push = self.get_prod_push(production.product_id)
                if push:
                    source_location_id = push.location_dest_id.id
                    destination_location_id = push.location_from_id.id
                    picking_type_id = push.picking_type_id.id
        prod_location_id = source_location_id
        prev_move = False
        if production.bom_id.routing_id and production.bom_id.routing_id.location_id and production.bom_id.routing_id.location_id.id != source_location_id:
            source_location_id = production.bom_id.routing_id.location_id.id
            prev_move = True
        move_id = stock_move.create(cr, uid, {
            'name': production.name,
            'date': production.date_planned,
            'product_id': product.id,
            'product_uom_qty': qty,
            'product_uom': uom_id,
            'product_uos_qty': uos_id and uos_qty or False,
            'product_uos': uos_id or False,
            'location_id': source_location_id,
            'location_dest_id': destination_location_id,
            'picking_type_id': picking_type_id or None,
            'company_id': production.company_id.id,
            'procure_method': prev_move and 'make_to_stock' or self._get_raw_material_procure_method(cr, uid, product,
                                                                                                     location_id=source_location_id,
                                                                                                     location_dest_id=destination_location_id,
                                                                                                     context=context),
            # Make_to_stock avoids creating procurement
            'raw_material_production_id': production.id,
            # this saves us a browse in create()
            'price_unit': product.standard_price,
            'origin': production.name,
            'warehouse_id': loc_obj.get_warehouse(cr, uid, production.location_src_id, context=context),
            'group_id': production.move_prod_id.group_id.id,
        }, context=context)

        if prev_move:
            prev_move = self._create_previous_move(cr, uid, move_id, product, prod_location_id, source_location_id,
                                                   context=context)
            stock_move.action_confirm(cr, uid, [prev_move], context=context)
        return move_id
```

**Comment by Karsten-77** [comment]
Additional: I solved this behavior with a configured route for production product and one for consumed products. All route and rules are referencing with company_id. All companys have own Rules, there is no rule across companys. 

Sincerly,
Karsten

**Comment by jco-odoo** [comment]
It is something rather specific which is interpreting push rules differently and I even don't know if it will be ok for multi-company.  (2-step production can be done differently)

For intercompany, in order to avoid these problems, the best thing still is the intercompany module (enterprise).  Sale orders that create purchase orders in the other company and vice versa.  Also, one product is not valued in the same way in one company as in the other.  

On the other hand, the multi-company stock process can be improved.  In v9, the quants moved are those of the company of the move.  The quants can only belong to one company and makes it more difficult.  (costing purposes)

In terms of push/procurement rules and access rights: it is always better to think in terms of procurement rules first and if you work with orderpoints, it can be handled by the admin.

**Comment by flotho** [comment]
Hi @jco-odoo ,
Thanks for your position, for the intercompany I understand your point of view, I just hope that this is not fully based on the community ;-) you should have the same problems.
Additionally, resupplying and push rules in intercompany has always been part of the standard, so  you're probably talking about the financial part that are linked to intercompany. I understand this financial part.

anyway, I would appreciate your recommendation for resupplying interwarehouse in community edition. It's supposed to work out of the box and there are many acess level issues.

regards

**Comment by Yenthe666** [comment]
Hi all,

As Odoo 9 is no longer officially supported (end of life) I'm closing this issue.

Regards,
Yenthe
