### ISSUE TITLE
when leads convert to issue, the attachment  in message history cannot go to new issue.

### ISSUE THREAD

**Issue by fausthuang** [odoo/odoo#11061]
Impacted versions: V9.0 enterprise

Steps to reproduce: receive a lead from email with attachment. need convert it to issue. but in new issue the attachment will be lost in history message.

Current behavior: user have to download and upload manually.

Expected behavior: whole message history(include the attachement file) could show on new issue. at least user should have the choice:  convert with attachment or not. 

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi
Thank You for reporting
It has been fixed by online!

Please don't duplicate opw and issue !!!
Just open opw...

**Comment by JKE-be** [comment]
Please, Can You close your issues that have been accepted/fixed by online ?
That Will avoid others users to reproduce an already fixed issue;)
