### ISSUE TITLE
[16] When register payment, default account_id is used instead of journal account_id

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#110645]
Bank Journal Settings

![01_journal_settings](https://user-images.githubusercontent.com/61056242/213925874-280bc0eb-2147-4445-87b9-dfbe9a869da0.jpeg)

Register payment for any invoice.

![02_register_payment](https://user-images.githubusercontent.com/61056242/213925890-467a2367-6369-4f4c-b5d9-2f2d8cd5a38f.jpeg)

Check journal entiries for payment.

![03_payment_journal_items](https://user-images.githubusercontent.com/61056242/213925920-f05c1ab5-22d4-444d-bade-af8f8eff87a2.jpeg)

Default accounting accounts.

![03_payment_journal_items](https://user-images.githubusercontent.com/61056242/213926175-3ca5127a-2b61-42c6-9613-3ba911eb5ae1.jpeg)

Odoo skiping journal account when payment posting, also i cleared default "Outstanding Receipts Account",  then giving following error:

![04_error](https://user-images.githubusercontent.com/61056242/213926083-902c2578-311c-43b1-bcce-e2901f303f31.jpeg)

**It is a bug that needs to be fixed urgently, we started using v16 in live environment, but this bug opened up more work for us.**

**Comment by larshalvoraam** [comment]
The outstanding accounts are used in Bank reconciliation.  If you don't use that, the put in the  journal account in all places. 
![bilde](https://user-images.githubusercontent.com/58386404/217168547-834eeb86-6b20-47e1-b474-6749af1b9028.png)

**Comment by esakarya** [comment]
Are u kidding ? Check images again. its skip journal account

**Comment by MihranThalhath** [comment]
@esakarya This is not a bug. The Outstanding receipts account is being used for bank reconciliation purposes. You can set it to bank account in the journal itself like in the image attached.

![image](https://user-images.githubusercontent.com/22158587/217184532-fab22342-9dd7-4976-a8df-8500e2083cdf.png)

**Comment by esakarya** [comment]
it's done now, thanks!
