### ISSUE TITLE
[9.0 & 9.0E] No ability to directly import database template on clean install

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11079]
Impacted versions:
9.0 and 9.0 Enteprise

Steps to reproduce:
  1. Install Odoo 9
  2. Go to http://www.yoururl.com:8069/web/database/manager. You will get the following screen:
  <img src="http://i.imgur.com/GLgTT1d.png" alt="Clean install"/>
  There is no option to import a dump/template database here!
  After creating one database from this screen I can import new databases:
![image](https://cloud.githubusercontent.com/assets/6352350/13279616/718ad696-dad9-11e5-9c74-6276df963f01.png)

Current behavior:
No ability to restory / import a database on a clean install

Expected behavior:
The restore database button is always visible.

**Comment by odony** [comment]
@Yenthe666: please [avoid creating an issue *and* a PR](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues) for the same thing, you can simply put the description of the issue in your PR :-)  (to avoid extra noise in our issues)

**Comment by Yenthe666** [comment]
@odony my apologies. I initally only created an issue and then I decided to write a fix / addition for it since that is better then only creating an issue right :smile:
