### ISSUE TITLE
[14.0] XSD validation failed

### ISSUE THREAD

**Issue by desdelinux** [odoo/odoo#110739]
Impacted versions: 14.0

Steps to reproduce:

- Install l10n_pe_edi
- Create a non-administrator user with billing permission 
![image](https://user-images.githubusercontent.com/50924836/214090557-b2d1061c-1d93-4822-9374-69a9e39c2159.png)
- Create an invoice and send now
![image](https://user-images.githubusercontent.com/50924836/214092236-f9240871-6c1e-4e82-8d1a-65d592be339a.png)

- Signing error: 
XSD validation failed:
Sorry, you are not allowed to access this document.

Example:

user: prueba@gmail.com
password: prueba2022

https://23060550-14-0-all.runbot122.odoo.com/web#id=93&action=449&model=account.move&view_type=form&cids=6&menu_id=579

**Comment by desdelinux** [comment]
@tde-banana-odoo I think this error is related to this commit https://github.com/odoo/odoo/commit/d3a6a20788c78ddaaff0919ea627e7b10c7ab81c

cc @jco-odoo @ren-odoo @vbe-odoo @fvz-odoo @luistorresm

**Comment by jco-odoo** [comment]
@tde-banana-odoo It is not the first time that the logic for the attachments changes.  But we need to store our XSD files somewhere.

**Comment by tde-banana-odoo** [comment]
I did not do it, this kind of false commit is generally done by an internal team.

@odony @mart-e I let you deal with it, you already broke attachments management several times in my name, maybe this is the continuation.

Cheers,

**Comment by jco-odoo** [comment]
@odony I find it counterintuitive not to be able to have attachments for all internal users by default...  And if it is secret then you could unflag that.  But if you agree with the above PR and backport, let's continue with that tomorrow.
