### ISSUE TITLE
[8.0] Public User can create Quotations - probably spamers try to access the site

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#11082]
Impacted versions: 8.0

Steps to reproduce: I've got my Odoo 8.0 online on this url http://aramis-paris.fr; Your Odoo instance must be online accessible to everyone,

Current behavior: Time to time empty Quotations are created by some Public User, I see in  column "Client" Public User. 

Expected behavior: Public User should not be able to create Quotations or Sale Orders

Video/Screenshot link (optional):

May be it's just configuration issue, have to modify some access rules ?

Regards.

**Comment by Yenthe666** [comment]
@sergueikp I believe this is the 'wanted' behaviour, since this is used to store all data from a customer and to keep track of everything related to him.
@xmo-odoo could you verify this is the case?

**Comment by JKE-be** [comment]
Hi,
Shop (website_sale) is installed... So users can create sale_order... I didn't see where is the issue !
