### ISSUE TITLE
[9.0] Quotation order line Form layout issue

### ISSUE THREAD

**Issue by GillPotter** [odoo/odoo#11081]
Impacted versions: 9

Steps to reproduce:
User has Properties on Lines Checked on their user profile so that the order line is edited in **form** view.

Create a new Quotation, click on "add an item" the first group of fields on the order line form are right justified and reduced in size.

Create a new Sales Order, click on "add an item" the first group of fields on the order line form are aligned properly.

Current behaviour:
Screen shot from Quotation:

![image](https://cloud.githubusercontent.com/assets/10741187/13280894/88dbe174-dad8-11e5-9e97-296207eceac0.png)

Expected behavior:

Screen shot from Sale Order:
![image](https://cloud.githubusercontent.com/assets/10741187/13280927/bae742b2-dad8-11e5-83e0-ae2d7bc4182a.png)

It looks like the code :  invisible="not context.get('show_sale')"  in addons/sale/sale_view.xml 
which makes the Delivered Quantity and Invoiced Quantity invisible on the form for Quotations is impacting the Layout of the fields on the form. Is this a bug or by design? If it is by design is it possible to change it?

**Comment by JKE-be** [comment]
Thanks for the reporting

**Comment by GillPotter** [comment]
Hi JKE-be
Thank you for looking at this. I've just looked at it in Runbot and the Quotation form view is great now. However it seems to have upset how the Delivered Quantity and Invoiced Quantity appears in the Sale form view ...
![image](https://cloud.githubusercontent.com/assets/10741187/13401517/51989574-df04-11e5-89f0-b3e625d05a7c.png)

Kind regards
Gill

**Comment by JKE-be** [comment]
thank. It should be fixed since yesterday

**Comment by GillPotter** [comment]
Thank you so much for the rapid fix.
