### ISSUE TITLE
datetime, timezone and email templates

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#1108]
According to my tests and to this thread https://www.odoo.com/forum/Help-1/question/how-to-change-email-templates-date-format-15885, when we display a datetime field in the "body_html" of an email.template, this datetime field is always rendered in UTC timezone, and not in the timezone of the user that runs the function "send_mail(cr, uid, template_id, object.id, context=context)".

So it's a major problem for the insertion of datetime fields in email templates.

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
