### ISSUE TITLE
[8.0] My Current Timesheet, details tab losing journal_id

### ISSUE THREAD

**Issue by benrolsen** [odoo/odoo#1109]
When using hr_timesheet_sheet, on the HR->My Current Timesheet page, if the user tries to enter time in the details tab instead of the summary tab, the invisible field "journal_id" somehow doesn't get populated.

**_Impacted versions:**_

 8.0

**_Steps to reproduce:**_
1. From fresh DB, install account_accountant, enable analytic accounting, create at least one contract/analytic account.
2. Install hr_timesheet_sheet module.
3. Under HR main menu, click on My Current Timesheet. Click "Save" to set the initial timesheet. Click "Edit" to begin adding lines.
4. On the details tab, add a new line, select analytic, description, etc. Note that when trying to leave the line, or save the form, the user gets an error: "Invalid field: journal_id" 
5. On the summary tab, add a new line, add an analytic, click add, add some hours, click save. Note that this does not give an error.

**_Current behavior:**_

 For some reason, the details tab is losing the journal_id that gets initially set as a default. This does not happen on the summary tab. I used a custom view to show the journal_id field and confirmed that it remains blank when adding lines on the detail tab, but is automatically filled in when adding lines on the summary tab.

Also, I stepped through _getAnalyticJournal in hr_timesheet/hr_timesheet.py (around line 142) and confirmed that the function does get called in both cases, and returns a correct value in both cases. For the details tab, something somewhere is resetting this value back to nothing after _getAnalyticJournal has been called.

**_Expected behavior:**_

 The default journal_id value should be set (and stay set) when adding lines in the details tab of My Current Timesheet.

**Comment by Yenthe666** [comment]
Hi @benrolsen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
