### ISSUE TITLE
[16.0] not possible create a method payments

### ISSUE THREAD

**Issue by JoseAcosta0312** [odoo/odoo#111029]
Impacted versions: 16

Steps to reproduce:
create within a datafile a new record for the model "account.payment.method"
example:
<?xml version="1.0" encoding="utf-8"?>
<odoo>
   <data>
     <record id="test_payment_method_bank" model="account.payment.method">
         <field name="name">Incoming Payments - Bank</field>
         <field name="code">bank</field>
         <field name="payment_type">inbound</field>
     </record>
   </data>
</odoo>

Current behavior:
triggers an error in the create method of the payment method, indicating that AttributeError: 'NoneType' object has no attribute 'get'

Expected behavior:
that the payment method is created correctly

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/116648729/214681517-39376c05-d218-421d-b1a0-e4587fcca3c7.png)
![imagen](https://user-images.githubusercontent.com/116648729/214681734-97f413f8-a8e2-4b59-9cd4-b1f52c6bf5fe.png)
![imagen](https://user-images.githubusercontent.com/116648729/214681881-dca83139-de66-4b64-92e8-ebed115ee040.png)

**Comment by niyasraphy** [comment]
hi @JoseAcosta0312 ,
fixed in this commit:  https://github.com/odoo/odoo/commit/f8918c9ea14fc35a5baf0824bd320c749d881fc6

feel free to close the ticket.
thanks
