### ISSUE TITLE
[9.0e] @api.onchange ignored if a parent module define a v7 on_change on the same field

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#11109]
### Impacted versions:
9.0e

### Steps to reproduce:
Create a module that inherit stock.picking and put a on change event on partner_id.

    class StockPicking(models.Model):
        _inherit = 'stock.picking'
       
        @api.onchange('partner_id')
        def onchange_partner_id_unique_function_name(self):
            pass  # This code isn't reached

### Current behavior:
The code from def onchange_partner_id_unique_function_name(self) isn't called

### Expected behavior:
The code from def onchange_partner_id_unique_function_name(self) is called

### Workaround:
If I override onchange_picking_type from stock.picking, it will work, but I need to code in v7 witch I don't like. Is there an easy way to call v8 methods from a v7 method?

**Comment by beledouxdenis** [comment]
I do not believe this is an expected behavior. Raphaël can probably answer you better.

**Comment by krueger80** [comment]
If the @api.onchange decorator isn't working in this case, the other choice is to make a v7 function (overriding the base onchange function, or create a new one) and I have to duplicate and back port a few methods that are called. They use dot notation to set and get values in occurrence. Hope this could be supported to avoid that.

**Comment by lem8r** [comment]
You have to define your function in both v7 and v8 style with the same name. And v7 should be on first place. It was stated somewhere in orm documentation.

**Comment by krueger80** [comment]
@lem8r where is that documentation? So for that onchange, I cannot use dot notation to set values in the form... I will need to duplicate code that was setting values to other fields and return "value" in dictionary instead (v7 style). Going to be messy code... I don't understand the reason behind this limitation.

**Comment by lem8r** [comment]
https://www.odoo.com/documentation/9.0/reference/orm.html#module-openerp.api

**Comment by krueger80** [comment]
This is expected behaviour as you say... but frustrating :/ Thanks for the information.
