### ISSUE TITLE
[16.0]  Website form builder subscribe to newsletter throws group access error

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#111170]
[16.0] Website Form builder subscribe to newsletter

Create form to subscribe to newsletter

User gets error message:
 **You are not allowed to access 'Mailing List' (mailing.list) records. This operation is allowed for the following groups: - Email Marketing/User Contact your administrator to request access if necessary.** 

User is able to subscribe and is redirected to a message page.

Video/Screenshot link (optional):

![Screenshot (165)](https://user-images.githubusercontent.com/14188201/214987752-12ea6d68-a7a1-40c4-ab92-f6c4a3796071.png)

**Comment by niyasraphy** [comment]
Fixed by: https://github.com/odoo/odoo/commit/3631643e0d6294d3fa6c8e1b3bb087c08bbabb4a
