### ISSUE TITLE
[9.0e] #Channel is not removed from side after deleted and cannot be removed (missing record)

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#11113]
Impacted versions:9.0

Steps to reproduce: Create then delete channel in Discuss app.  

Current behavior: Channel not removed, clicking 'x' results in missing record error

Expected behavior: no channel displayed in Discuss home view after deletion.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @elevationO,

Thanks a lot for your bug report.
I've just tested this with the latest Odoo 9.0 and it works fine out of the box.
Please update your Odoo to the latest source code in order to fix this.

Regards,
Yenthe
