### ISSUE TITLE
[V9.0] web_analytics code doesnt show

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#11127]
Impacted versions: V9.0

Steps to reproduce: Install addon web_analytics, enter UA code in the website configuration

Current behavior: both front and back end dont show the google tracking code

Expected behavior: show tracking code in html

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,
web_analytics is only an old module which provide statistics for Odoo in the past.

About the UA in website configuration (from module website).
It works only in website == on the front end. That will not track the backend by default (but you can always update the webclient template if you want this)

The tracking code is only loaded when user don't have rights to edit the website to avoid to have too many fake stats coming from yourself.
