### ISSUE TITLE
[14.0] product: can not change product company when the product only exist in quant in single company

### ISSUE THREAD

**Issue by paimonchan** [odoo/odoo#111290]
Impacted versions: 14.0

Steps to reproduce:
1. have one company (company A)
2. create new product without company
3. create transaction from sale/purchase until the transaction is completed on company A
4. create another company (company B) ==> don't do any transaction in this company
5. set the the product company to company A
6. will get error message `This product's company cannot be changed as long as there are quantities of it belonging to another company.`

Current behavior:
- verification for changing product company was included for quant in vendor location and customer location

Expected behavior:
- verification for changing product company should be exclude vendor location and customer location, because this virtual location don't have company

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by paimonchan** [comment]
this problem is related to this PR: https://github.com/odoo/odoo/pull/108066

**Comment by ticodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/111293
