### ISSUE TITLE
Wrong vobject version: error: python-dateutil 1.5 is installed but python-dateutil>=2.4.0 is required by set(['vobject'])

### ISSUE THREAD

**Issue by edouard-lopez** [odoo/odoo#11122]
Impacted versions: `7.0.20160226`
Steps to reproduce:

```
wget -c http://nightly.odoo.com/7.0/nightly/deb/openerp_7.0.20160226.tar.gz
tar -xzf openerp_7.0.latest.tar.gz
cd openerp-7.*
sudo apt-get install --yes \
        python-dev \
        libldap2-dev \
        libsasl2-dev \
        libssl-dev \
        python-dateutil \
        python-docutils \
        python-feedparser \
        python-jinja2 \
        python-ldap \
        python-libxslt1 \
        python-lxml \
        python-mako \
        python-mock \
        python-openid \
        python-psycopg2 \
        python-psutil \
        python-pybabel \
        python-pychart \
        python-pydot \
        python-pyparsing \
        python-reportlab \
        python-simplejson \
        python-tz \
        python-unittest2 \
        python-vatnumber \
        python-vobject \
        python-webdav \
        python-werkzeug \
        python-xlwt \
        python-yaml \
        python-zsi \
        poppler-utils \
        python2.7-pil \
        libxml2-dev \
        libxslt1-dev
pip install linecache2 Pillow PyChart
easy_install --find-links http://www.pythonware.com/products/pil/ Imaging
python setup.py install
```

Current behavior:

```
Installed ~/projects/my-project/env/lib/python2.7/site-packages/python_dateutil-1.5-py2.7.egg
error: python-dateutil 1.5 is installed but python-dateutil>=2.4.0 is required by set(['vobject'])
```

Expected behavior:

Set correct version of `vobject` which **["recently" updated version of dateutil (2.4.0 and above)](https://pypi.python.org/pypi/vobject)**.

This has been added since vobject [0.9.0](https://eventable.github.io/vobject/#release-history).

Video/Screenshot link (optional):

**Comment by bodedra** [comment]
It's give you error because of system refer `python-dateutil 1.5` version. Try with uninstall it and remove `.egg`.

For example:

 1. uninstall package 

        sudo pip uninstall python-dateutil

 2. remove `.egg` file 

        sudo rm -rf /usr/lib/python2.7/site-packages/python_dateutil-1.5-py2.7.egg

 3. reinstall it

        sudo easy_install python-dateutil

**For Ubuntu:**

 1. uninstall python-dateutil and it's dependencies

        sudo apt-get remove --auto-remove python-dateutil

 2. purging your config/data too

        sudo apt-get purge --auto-remove python-dateutil

 3. reinstall it 

        sudo apt-get install python-dateutil

You may download from here: [python-dateutil 2.4.2][1]


  [1]: https://pypi.python.org/pypi/python-dateutil/2.4.2

**Comment by Yenthe666** [comment]
Hi @edouard-lopez,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
