### ISSUE TITLE
fields.Selection: can't use 0 as a value

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#11120]
Impacted versions: bitten by this in 9.0, but probably there since long

Steps to reproduce: create a fields.Selection with values [(0, '0-3'), (4, '4-6')], add the field to a form view. 

Current behavior: When you set the field to 0, no value is displayed in the form

Expected behavior: I want to see '0-3' in the form.

**Comment by gurneyalex** [comment]
this really is painful when interfacing with enum fields in external systems.

**Comment by gurneyalex** [comment]
And I have the impression that 0 is not stored in database and I get a NULL instead... :angry:

**Comment by lem8r** [comment]
try to use string ```'0'```

**Comment by gurneyalex** [comment]
@lem8r well this is an ugly workaround at best, because you need to convert the integer to a string and the string back to an integer when interfacing the with the externa

**Comment by Yenthe666** [comment]
@mart-e and @odony this is an issue that I've faced before too. Is there anything we can do about this to fix it?

**Comment by gfcapalbo** [comment]
I had a evening of debugging to figure out your problem:
https://github.com/nbessi/odoo_new_api_guideline/pull/38

As you can see in models.py Just add size=-1 to your field definition and the ORM will interpret it .

It is now in the unofficial Odoo documentation of N.Bessi.

**Comment by lem8r** [comment]
What if function is passed into selection instead of list? 

def _get_my_list(self)
    return [(0, '0-3'), (4, '4-6')]

fields.Selection(_get_my_list)

**Comment by gfcapalbo** [comment]
Should work the same, test.    the function will return your selection. when the ORM interprets it, if it finds attribute SIZE =-1 it will correctly interpret integer selections.
should still work. I believe that was exactly my case.

**Comment by Yenthe666** [comment]
Alright so starting from Odoo V10 it'll be fixed then? :+1:

**Comment by gfcapalbo** [comment]
don't know. There is no particular reason to believe so. possibly.

**Comment by Yenthe666** [comment]
@mart-e I believe this is still valid & across all versions.

**Comment by pedrobaeza** [comment]
Do you know if this is still happening with newest JS views in v11?

**Comment by sswapnesh** [comment]
Added field with values `[(0, '0-3'), (4, '4-6')]`

In Odoo v9/10 Saving record with 0 is not saved.(Does not display Anything)

But in v11 Making it blank still displays '0-3'. (Blank vales is treated as 0)
