### ISSUE TITLE
[14.0][OE] account_asset : wrong rate in asset report

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#111363]
Impacted versions: 14.0

**Steps to reproduce:**
Create an asset with this datas:
![image](https://user-images.githubusercontent.com/16716992/215515991-20b40003-c499-443f-a052-4bdd1d0faabb.png)
The rate is wrong : 
![image](https://user-images.githubusercontent.com/16716992/215516119-ee6f0151-cf9d-437c-8735-fc748d08397e.png)
it should be 20%

**Current behavior:**
Rate is 20,34%

**Expected behavior:**
Rate should be 20%

Because the last move 60/60 doesn't exist, because amount is zero.
In total there are 60 moves (59 + 1 prorata), but here in the SQL report 1 is substract, and 100/(59/12) => 20,34.

**Video/Screenshot link (optional):**
https://user-images.githubusercontent.com/16716992/215524562-4c8d9088-f078-47ec-ae2d-71e13eee95fe.mov

**Support ticket number submitted via odoo.com/help (optional):**
#3162846

@oco-odoo @william-andre

**Comment by william-andre** [comment]
@gawa-odoo If the prorata date is equal to the first day of month/year, we should not remove one depreciation from the SQL query.

**Comment by fmdl** [comment]
@william-andre @gawa-odoo 
here -1 is added : https://github.com/odoo/enterprise/blob/14.0/account_asset/report/account_assets_report.py#L299
but it not the issue.

The issues is, depending of amount (and computing rounding), and if the prorata date is the start of the month/year, there are 60 or 61 moves.
here there are 61 moves https://23331260-14-0-all.runbot128.odoo.com/web?#id=8&action=1165&model=account.asset&view_type=form&cids=6&menu_id=579
and here only 60 moves https://23331260-14-0-all.runbot128.odoo.com/web?#id=5&action=1165&model=account.asset&view_type=form&cids=6&menu_id=579

It doesn't make sens to prorata=True if prorata_date it is start of month/year.

**Comment by william-andre** [comment]
Sorry, I was in the mindset of version 16 where this has been entirely reworked and everything is more homogeneous.
Setting prorata to False when computing the board if it is the start of the period might be the easiest fix then

**Comment by fmdl** [comment]
Please find fix here : https://github.com/odoo/enterprise/pull/36489
