### ISSUE TITLE
[8.0/9.0] base_geolocalize depends on crm

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#11132]
While the name suggests that this is a base module, the truth is different. 
`base_geolocalize` adds a nice feature to get geolocation data from Google Maps API using a `res.partner` address.

Problem? well it's depending on `crm`, which means you get all the unnecessary features if you only need this geolocation or want to develop some extra features using odoo's base geolocation.

Why? there's is no obvious reason, as neither the model or the view depends on `crm` models or views. It inherits from `res.partner` only, so depending on `crm` doesn't seem logical.

Is it possible to modify this dependency and make `base_geolocalize` a real base module?

**Comment by JKE-be** [comment]
Thanks for the reporting, it has been fixed in 8.0 and will be forwarded asap.

**Comment by aristobulo-eezee** [comment]
@JKE-be we will need this very soon on v9.0, any news about this forwarding?

**Comment by JKE-be** [comment]
Hello, it is done :) odoo/odoo@e46f65ab265176e035bfce95f48b1f52423c71d9
Have a good week end...

**Comment by aristobulo-eezee** [comment]
@JKE-be Thank you very much.
