### ISSUE TITLE
[BUG] Odoo stays in the loading screen after invoice is generated

### ISSUE THREAD

**Issue by Tscunami** [odoo/odoo#111340]
Impacted versions: 16.0 Enterprise

Steps to reproduce: 

* Open application **Accounting**  
* Create a new **Customer Invoice**  
* Fill in all required information and click **Confirm**  
* Click on the button **Send & Print**  
* Click on generated PDF from the section Attachments in the email  
* It will open PDF in a new tab  
* When you close this tab and return to the previous screen, you'll see, that there is a loading screen and it stay like this until you hard refresh the webpage  

Current behavior:

* Webpage is stuck on the loading screen

Expected behavior:

* Webpage should not be stuck on the loading screen

Video/Screenshot link (optional):

![obrazek](https://user-images.githubusercontent.com/66170274/215483917-0423a06d-c5b5-4255-8ecc-4296ee96ce76.png)  
![obrazek](https://user-images.githubusercontent.com/66170274/215485788-c427619f-490f-4d9b-b101-72fc59c74156.png)  

Support ticket number submitted via odoo.com/help (optional): #3162536

**Comment by jcdrubay** [comment]
This defect might be fixed by this commit:

https://github.com/odoo/odoo/commit/3d7f91c7da58c0246adaf30f772b3530b8c6a642
