### ISSUE TITLE
Can't create new Individual Customer working at Company Customer

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#11137]
Impacted versions: Odoo 9.0

Steps to reproduce: Go to Accounting tab > Sales > Customers. Create a Company Customer with Account Receivable and Account Payable values. Then create an Individual Customer and set its company to Company Customer you created. Try to save. It will show error that Account Receivable and Account Payable are invalid fields.

Current behavior: Account Receivable and Account Payable are invalid fields.

Expected behavior: Account Receivable and Account Payable must be valid since this Individual Customer inherits these values from Company Customer.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @macdelacruz,

Thanks a lot for your bug report.
I've just tried to reproduce it but it works fine.
The company:
![image](https://user-images.githubusercontent.com/6352350/34982848-f450736c-faab-11e7-85b8-612463d65e1b.png)
The user I added to the company:
![image](https://user-images.githubusercontent.com/6352350/34982891-0e629cbc-faac-11e7-9991-755033abda14.png)


Please update your Odoo source code to the latest version if you still face this issue and it'll be resolved.

Regards,
Yenthe
