### ISSUE TITLE
Hide database-manager

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#11149]
Why is not added in version 9 such a useful option ["--no-database-manager"](https://github.com/odoo-dev/odoo/commit/598752acdcf6eab3375044e59c6e65a530ac95a6)?

Please, include this option.
Thanks in advance.

**Comment by Yenthe666** [comment]
Actually I'd like this option too. Adding it to the odoo-server.conf would be another great option.

**Comment by satriani-vai** [comment]
I would limit the acces by subdomain or domain. e.g.
www.site.com should not show database manager etc. only website content.
odoo.site.com or IP (xxx.xxx.xxx.xxx:8069) should have a full access

I think it's a very important security feature and must be included by default!

**Comment by satriani-vai** [comment]
When do you plan to add this feature? If soon, then I will wait, otherwise I'll patch it myself :)
Thanks in advance.

**Comment by Yenthe666** [comment]
This won't be in Odoo before V10 and might even be for V11.
The earliest possible time this is added is after october this year.

**Comment by satriani-vai** [comment]
is this option included in v10?

**Comment by Yenthe666** [comment]
@satriani-vai it is not in V10. 😭

**Comment by satriani-vai** [comment]
Sorry but I can't understand. Such important security feature is still not included. :(

**Comment by satriani-vai** [comment]
Guys, will you be able to patch this security bug until the next release? :roll_eyes:

**Comment by fmdl** [comment]
See a solution here : https://github.com/OCA/web/tree/10.0/web_hide_db_manager_link

**Comment by Yenthe666** [comment]
@odony or @mart-e could one of you two give feedback on this one? Will it be done, will we close it and keep it in the internal backlog, ?

**Comment by mart-e** [comment]
Hi,

We never backport never features to older versions:

To quote the [deployment documentation](https://www.odoo.com/documentation/10.0/setup/deploy.html#db-manager-security):

> 
> If the management screens must not be accessible, or must only be accessible from a selected set of machines, use the proxy server's features to block access to all routes starting with `/web/database` except (maybe) `/web/database/selector` which displays the database-selection screen.
> 
> If the database-management screen should be left accessible, the `admin_passwd` setting must be changed from its admin default: this password is checked before allowing database-alteration operations.

In v11, you can use the `list_db=False` configuration parameters.
