### ISSUE TITLE
Bug odoo-9: Can't Print Documents

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11157]
Impacted versions: 9.0

Steps to reproduce: Create Product, then print label

Current behavior:
Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display 

Expected behavior:
Printed PDF

Video/Screenshot link (optional):
![2016-03-01-115443_1600x900_scrot](https://cloud.githubusercontent.com/assets/311413/13419482/8fc05ee0-dfa4-11e5-91c2-b3db1b994705.png)

**Comment by JKE-be** [comment]
Hi,

Take a look here: https://www.odoo.com/documentation/9.0/setup/install.html#packaged-installers
You are using the bad version of wkhtml... And you need the qt patched version.

**Comment by mckaygerhard** [comment]
this its stupid, pretent to compile all the qt and then the program? pufff

**Comment by nerv55** [comment]
Yes, buy enterprice and all your depency problems desapear in a blink. Comunity is hook they use to get you to Enterprice Edition

**Comment by mckaygerhard** [comment]
seems nerv55 have right, odoo its a fake FOSS to make guindoser like software

**Comment by tejastank** [comment]
`ODOO ONE OF MOST BUGGY ERP SINCE BEGINING`, 
`ALSO ENTERPRISE EDITION IS BUGFUL TOO`.

**Comment by Yenthe666** [comment]
@tejastank what I don't understand is how you've complained for severaly years straight about Odoo.. yet you're still using it. If you do not like it then leave it.
That wkhtmltopdf version wouldn't work in community and enterprise, there is no difference in how wkhtmltopdf is used and called. Just switch to the right wkhtmltopdf version and it'll work 😄

**Comment by mckaygerhard** [comment]
@tejastank has right! i'll explain to you @Yenthe666 why some people using odoo

its like mocosoft formula.. firts propagate the plague, and one time the plague are installed we cannot erradicate, it's living with us in symbiotic mode!

odoo now are just a Mocosoft like ...

**Comment by mart-e** [comment]
Thank you guys for the constructive discussion we are having here (irony intended).
We said very explicitly you need a specific version of wkhtmltopdf. If you don't have it will not work and that has **nothing** to do with enterprise or community.
Thank you to stop spreading FUD.

If you don't like this restriction, you are more than welcome to contribute to wkhtmltopdf to get it working smoothly with Odoo. Just an head up: we have tried for years.
