### ISSUE TITLE
Using Extended Editor keeps edit mode after Sending message to Contact

### ISSUE THREAD

**Issue by joolsr** [odoo/odoo#11166]
Impacted versions:
9.0 Enterprise and Community

Steps to reproduce:

1. Create a message from the chatter ie to a Contact via the Contact menu on top bar (note other operations sending mail with Ext Editor appear to be working fine), 
2. Type in some text, then change to the Extended editor. 
3. Then press 'Send'- the message is sent, but the page returns to an open Editor window  still in Edit mode, and the Send button showing. The mail was sent the first time, so the page isn't returning to the chatter messages correctly in this case.

Current behavior:

The Editor window is left open after message is sent and the message is correctly shown in the chatter.

Expected behavior:

The Editor window is removed after sending the message, just showing the chatter with the message that was just sent.

Video/Screenshot link (optional):

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (53/50 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:51253 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarkM-00088M-Fz
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:22:22 -0500
Date: Tue, 01 Mar 2016 10:52:44 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456858364;
	bh=UJ4bF6F5TB1wKzjqeIK8hys6ozfCPz274gp+YuSMIw4=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=2LhdxA9XDtG050SVQ5dW/miHETPuPDMBigM6q27s4rg+y3m+L16yaZ28yMroX6/8J
	 2rAd+UxNVrB4m4cBTBFYaN+/+4lhLk0NInepQH7m121Nt40rp8UG84vvmJL41zibMV
	 JmMS+sldxDlVMZ6LdNhfmQ4QhWIzxHNb1OpySEJ0=

**Comment by joolsr** [comment]
fixed with recent commit
