### ISSUE TITLE
[Security Vulnerability]Users list should not be accessible by non-authorized users groups

### ISSUE THREAD

**Issue by sandip-at-fictiv** [odoo/odoo#111785]
Impacted versions:

- 15.0

Steps to reproduce:

- Go to Settings > Technical > User Interface > Menu Items and search menu item called "Users" (i.e. full path: Settings/Users & Companies/Users)
- Set Access Rights for Group Name "Administration / Settings" as shown below
- 
![Screenshot 2023-02-02 at 11 26 24 AM](https://user-images.githubusercontent.com/107966501/216415526-40c2a936-2b66-416a-ad3a-34c5a208b859.png)

- Go to Settings > Technical > Actions > Window Actions and search action name called "Users" (i.e. external id: base.action_res_users)
- In that form view, navigate to Security tab and set security for Group Name "Administration / Settings" as shown below
- 
![Screenshot 2023-02-02 at 11 30 30 AM](https://user-images.githubusercontent.com/107966501/216416906-49d6dbad-0239-43f1-95d6-6795a9946f89.png)

- Now, log in as any user who is not part of "Administration / Settings" users group. And try accessing users list via direct url having mentioned of above menu/view/action. For example from runbot: 
- https://23479114-15-0-all.runbot171.odoo.com/web?#cids=1&menu_id=4&**action**=72&model=res.users&view_type=list
- In case above link gets expired, to generate above url is simple, go to Settings > Users & Companies > Users menu and copy URL which gets generated in browser (as shown below) and use that same url after re-login as non administration/settings user.
- 
![Screenshot 2023-02-02 at 11 38 05 AM](https://user-images.githubusercontent.com/107966501/216419589-6832df92-d766-4bb3-b87a-b475e89d7d74.png)

Current behavior:

- Any user who is not part of "Administration / Settings" users can access this sensitive information. This seems security vulnerability. See below screenshot for the same where non admin user can still access it.
![Screenshot 2023-02-02 at 11 47 45 AM](https://user-images.githubusercontent.com/107966501/216421335-6393538d-c0b8-4795-81a3-8e6a7d975d7e.png)

Expected behavior:

- Non authorized users (in this case non administration/settings user group) should not be allowed to access data using menu/views/actions which are configured as non-accessible.

**Comment by Feyensv** [comment]
Security vulnerabilities must be reported privately through the [dedicated channel](https://www.odoo.com/security-report).

**Comment by sandip-at-fictiv** [comment]
> Security vulnerabilities must be reported privately through the [dedicated channel](https://www.odoo.com/security-report).

Thank you, it's reported to dedicated channel.
