### ISSUE TITLE
9.0 - Availability status of Delivery orders NOT updated after Shipment confirmation

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#11178]
Impacted versions: 9.0 

Steps to reproduce: Create a sales order for a product with NO stock
Delivery order line = Waiting for availability
Create Purchase order for the same product
Validate incoming product in the PO shipment

Current behavior:
Delivery order line STILL in "Waiting for availability"

Expected behavior:
Delivery order line must be now AVAILABLE

Video/Screenshot link (optional):

**Comment by JanarthananDeveloper** [comment]
did you find solution for this

**Comment by pedrobaeza** [comment]
If you want the new quantity to be auto-assigned, you have to install the module procurement_jit. Closing as no real issue, but false expectation without the proper module installed.
