### ISSUE TITLE
Odoo Performance

### ISSUE THREAD

**Issue by stephenbiit** [odoo/odoo#11175]
Impacted versions: 
Odoo V8 and Odoo V9

Steps to reproduce: 
1. Click www.demo.cristolive.org
2. Use the creds - username: demo  password: demo
3. Note the time taken for the landing page to appear

Current behavior:
Logs in (25 seconds on an average)

Expected behavior:
1. Must log in faster
2. Insert a Splash screen until the system logs in 

Video/Screenshot link (optional):
https://drive.google.com/file/d/0B07RdLGCeMuQcVFCT0kxRkNXeVE/view?usp=sharing

**Comment by jar-odoo** [comment]
steps 2. Invalid creds - username: demo password: demo

**Comment by stephenbiit** [comment]
Please check it now.

On Wed, Mar 2, 2016 at 12:33 PM, Jaydeep Barot <notifications@github.com>
wrote:

> steps 2. Invalid creds - username: demo password: demo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/11175#issuecomment-191098607>.
>



-- 

Thanking you,
Stephen Raj D,
Ph: 8870312211,
      9543949458.

**Comment by Yenthe666** [comment]
@stephenbiit Github issues are made for bugs and problems in the Odoo code, your problem seems to be more related to either your server configuration / specs.. I don't think that anybody from Odoo will even bother with this 'issue'.
What specs does your server have and how many users use it?

**Comment by stephenbiit** [comment]
I've configured odoo in ubuntu 14.04 and cent os 7. 
**Server Specification:**
   RAM : 8Gb
   HDD : 1 TB
   Processor : Intel(R) Xeon(R) CPU X3440 @ 2.53GHz
   Bandwidth : 100mbps

Odoo is faster in Local Area Network(LAN). It's too slow in Wide Area Network(WAN).
I'm getting following issues from all my clients.

1. Login takes long time.
2. Kanban view takes long time to load.

Some of my clients doesn't like odoo because of this performance issue.

**Comment by Yenthe666** [comment]
@stephenbiit those specifications should be more than enough to get things going smoothly.
Since you're saying that it is faster in the LAN then on the WAN I'm going to assume you're facing a delay because of firewalls, routings, ... so that is a really hard problem to solve / troubleshoot.
Is the difference between LAN and WAN very big?

**Comment by stephenbiit** [comment]
Yes,
Average loading time in LAN  : 6 seconds
Average loading time in WAN : 32 seconds
My Bandwidth : 4mbps
Client's Bandwidth : 2mbps/4mbps

**Comment by joolsr** [comment]
Have you any reverse proxying in place?. I use nginx with http2 on a fairly small scale server (smaller than yours and it's way faster even with a low speed wan adsl line as yours). There's lots of good guides for Odoo 8/9 about proxying with apache (or even better nginx) around. You may want to look at your postgresql db config too, theres quite a bit of info around about optimising perf.

**Comment by flotho** [comment]
Hi @stephenbiit ,

here is a good info : http://fr.slideshare.net/openobject/performance2014-35689113
without orders :
- add a reverse proxy
- change the worker number
- optimize your Pgsql

Do you use an external authentication source like ldap or google?

**Comment by stephenbiit** [comment]
No, I'm not using any external authentication sources.

**Comment by mart-e** [comment]
Hello,

As Yenthe said, github is to report issues on Odoo. Here it looks like a network issue, not a bug in Odoo.
If you need to investigate performance and/or configuration issues, check on the mailing list, with a partner or support.

**Comment by tejastank** [comment]
I use odoo since verion 5.0 and works with all version, odoo is very much slow because of its ORM & architecutre, also its not optimized by postgresql parameters. Its point of research. Now odoo no more free version as commited, so less interested to openly share it correction, for performance ERPNext had huge benchpass passed.
