### ISSUE TITLE
[8.0] signup_url: emailaddress missing in URL for new user

### ISSUE THREAD

**Issue by mgielissen** [odoo/odoo#11180]
Sending a saleorder by mail to a new client with portal access:

Generated signup URL: 

/web/signup?redirect=%2Fweb%23action%3Dmail.action_mail_redirect%26model%3Dsale.order%26id%3D6&token=MsXiwxwJpf7agRF9NQWR&db=test

Problem: When accessing the URL, the emailadress field is empty at signupscreen

Edit: Solved with this fix: https://github.com/grzekru/odoo/commit/951bfa09488ab7f0cee29486b932d22e04464792

**Comment by odony** [comment]
Hi, this appears to be a duplicate of #9367 indeed, which also comes with a possible fix. I hope you won't mind closing it :-)

**Comment by odony** [comment]
For the record, it was fixed in 8.0 by 40fdb84
