### ISSUE TITLE
[9.0] payroll_account: journal_id is not taken from contract

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#11188]
**Impacted versions:**
9.0

**Steps to reproduce:**
install `hr_payroll`, `hr_payroll_account`
Create employee's Contract with Journal: Misc Operations
Create employee's Payslip
Select employee
Journal field should be set to: Misc Operations but it is set to Currency Exchange Journal

**Current behavior:**
When payslip is created and no employee/contract is provided yet journal field is filled with first journal with `type = 'general'` found in database
(see https://github.com/odoo/odoo/blob/9.0/addons/hr_payroll_account/hr_payroll_account.py#L48)

When contract is provided `onchange_contract_id` from `hr_payroll_account` should be called to set `journal_id` from contract but this function is never called because original function from `hr_payroll` is never called due this commit https://github.com/odoo/odoo/commit/0a7ee85c18b9f847e0d0f1f9b54e4f43b2e046a9

**Expected behavior:**
Journal on payslip should be taken from employee's contract if it is set.

**Comment by jaredkipe** [comment]
I agree, I was looking at the code today thinking, "how would the journal on the contract even affect the payslip/move at all??"

**Comment by jaredkipe** [comment]
@simongoffin What do you think?

**Comment by lem8r** [comment]
Cool, thanks for the fix!
Can you look at this https://github.com/odoo/odoo/issues/10758 too?
