### ISSUE TITLE
[16.0]Helpdesk Ticket: Singleton Traceback during processing on REFUND button!

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#111935]
Impacted versions: [16.0 E]

Steps to reproduce:
- Create helpdesk ticket and select customer having already SO's created,delivered,invoice posted.
- Now in this ticket of helpdesk give refund 2 times, 1 by 1.
- Now Click again on REFUND 3rd time.

Current behavior:
- BUG/Traceback
Expected behavior:
 -  It should not throw traceback and work smoothly.
 
Video/Screenshot link (optional):

Screenshot
![image](https://user-images.githubusercontent.com/36708909/216750820-65384ebc-cd47-4049-9e4a-341ad4042009.png)

Video:

https://user-images.githubusercontent.com/36708909/216750996-5db8782d-e46a-4a81-9d49-908ad4bce743.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by ppr-odoo** [comment]
@dipak-shah  my team already fixed this issue. So. I close this one.happy weekend.

cc@xbo

**Comment by ppr-odoo** [comment]
@xavierbol

**Comment by ppr-odoo** [comment]
@dipak-shah  I have fixed  in this [PR](https://github.com/odoo/enterprise/pull/36762).thank you

**Comment by niyasraphy** [comment]
hi @dipak-shah ,
feel free to close the issue as it has been resolved.
thanks

cc: @ppr-odoo
