### ISSUE TITLE
[ 16.0 ] [ BUG ] psycopg2.errors.UndefinedFunction    jsonb_path_query_array(jsonb, unknown)

### ISSUE THREAD

**Issue by jinjieSpring** [odoo/odoo#111937]
Impacted versions: 16.0

Steps to reproduce: use index='trigram', translate=True install hr

Current behavior: cr.execute(f'CREATE INDEX "{indexname}" ON "{tablename}" USING {method} ({args}){where}')
                            psycopg2.errors.UndefinedFunction  jsonb_path_query_array(jsonb, unknown)

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
You must have PostgreSQL version 12 minimum for Odoo 16.0+.

**Comment by jinjieSpring** [comment]
@Feyensv  Thank you for you answer
