### ISSUE TITLE
[8.0] @api.depends('order_id.partner_id') works as if it were @api.depends('order_id', 'order_id.partner_id')

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#11213]
When some stored computed field of a Sale Order Line depends on the Partner of the Order:
    `@api.depends('order_id.partner_id')`
the stored field gets recomputed not only on `order_id.partner_id` changes, but on any change of the `order_id`.

Is it a bug or a feature?
### Example

``` python
class sale_order_line(...):
   @api.depends('order_id.partner_id')
   def _expensive_computation()
      ...
   field_expensive = fields.<Smth>(compute=_expensive_computation, store=1)
```

You have an SO with 10 lines.
You change the first 2 lines:

``` Python
order.write({'order_line': [(1, id_1, vals_1), (1, id_2, vals_2)]})
```

Although you didn't change the partner of the order, `expensive_computation()` is triggered (because [`openerp/fields.py#setup_triggers()`](https://github.com/odoo/odoo/blob/8.0/openerp/fields.py#L612) makes so_lines depend on `order_id`, not on `order_id.partner_id` as requested).
And moreover -- `expensive_computation()` is triggered for all 10 lines, not even for just the 2 changed ones.
Now, if we imagine changing a single line in an order of 1000 lines... :)
Or 5000 lines... Or 10K lines...

**Comment by LeartS** [comment]
Maybe not in this specific case, but I think generally it's a feature. If a field depends on a field of a related record, obviously it must depend also on the related record itself.

For example if I have a computed field on product.template that depends on the name of its category and on the name of its brand, it would also obviously depend also on the category of brand itself: if I change category or brand (as opposed to just modify their name) we generally want the field to be recomputed.

**Comment by rco-odoo** [comment]
When a field depends on `order_id.partner_id`, it will be recomputed on `record` when
 - `order_id` is modified on `record`, or
 - `partner_id` is modified on `record.order_id`.

It is exactly how it was intended to work.
