### ISSUE TITLE
Wrapping popup submenus don't translate in o_spreadsheet.js

### ISSUE THREAD

**Issue by peterromao** [odoo/odoo#112235]
Impacted versions:16.0 CE

Steps to reproduce: edit spreadsheet in a dashboard

Current behavior: Wrapping popup submenu strings don't translate (Overflow, Wrap, Clip)

Expected behavior: These terms should translate

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

The Lines associated to this issue are in:
odoo/addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js at lines 6198 - 6212 :

```
        .addChild("format_wrapping_overflow", ["format", "format_wrapping"], {
        name: "Overflow",
        sequence: 10,
        action: (env) => setStyle(env, { wrapping: "overflow" }),
    })
        .addChild("format_wrapping_wrap", ["format", "format_wrapping"], {
        name: "Wrap",
        sequence: 20,
        action: (env) => setStyle(env, { wrapping: "wrap" }),
    })
        .addChild("format_wrapping_clip", ["format", "format_wrapping"], {
        name: "Clip",
        sequence: 30,
        action: (env) => setStyle(env, { wrapping: "clip" }),
    })
```

Also the 3 terms are not part of language file template spreadsheet.pot in the module's i18n folder.

Whenever _lt(string) is used and the terms exist in the .pot file and individual language files the translations work ok.

The culprit seems to be the lines:
`action: (env) => setStyle(env, { wrapping: "yourtermhere" }),`
which I don't know where is executed.

**Comment by rrahir** [comment]
Thank you for reporting this issue!
