### ISSUE TITLE
[16.0][bug] point_of_sale: issue with refund order qty

### ISSUE THREAD

**Issue by sagar-dms** [odoo/odoo#112291]
@andrewdhastings

Impacted versions:
git branch 16.0

Steps to reproduce:
 1) Create POS order with any product -> Qty = 1.0
 2) Go to the refund page -> Select Order -> Update Qty to 0.5 -> Click on the 'Refund' button

Current behavior:
It is creating a refund order with Qty = 1.0
If the Original order qty is more or less than 1 -> It's working fine

Expected behavior:
It should create a refund order with Qty = 0.5

Video/Screenshot link (optional):
![Selection_141](https://user-images.githubusercontent.com/104374654/217795539-4caf792c-2dc2-4d66-85da-7063aff131c6.png)
![Selection_142](https://user-images.githubusercontent.com/104374654/217795533-30969920-d324-46c7-a3cb-8e530ab29a34.png)
![Selection_143](https://user-images.githubusercontent.com/104374654/217795526-e8728c9b-8167-499e-aa93-d2d5c2400639.png)
![Selection_144](https://user-images.githubusercontent.com/104374654/217795519-65ddce5f-6d21-4215-8575-4765b10ed981.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @sagar-dms .
issue has been resolved, feel free to close the ticket.
thanks
