### ISSUE TITLE
[9.0e] new field "sort" on ir.filter is not working in V9 enterprise

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#11222]
Impacted versions: 9:0 enterprise

Steps to reproduce: 

About the new field "sort" on "ir.filter"
On v9 (non enterprise) in the module web/static/src/js/views/search_menu.js line 234
If you compare this file with the add ons of the Enterprise version, some lines are missing: 

// Load sort settings on view
        if (!_.isUndefined(filter.sort)){
            var sort_items = JSON.parse('["email"]');
            this.searchview.dataset.set_sort(sort_items);
        }
which will apply the sorting defined in the filter.

2nd Issue about that;  if you complete the field sort as the following:
- ['email'] => it doesn't work
- ["email"] => it works

Expected behavior: same behaviour as in the non enterprise

**Comment by beledouxdenis** [comment]
Closed with the port of 3071ef1 in Odoo Enterprise.
