### ISSUE TITLE
[8.0] odoo mrp production order update product_qty.....stock move update qty error

### ISSUE THREAD

**Issue by OSSTWJason** [odoo/odoo#11227]
Impacted versions: 8.0

Test step:

1、Manufacture Order Confirm (product_qty 3) and use routing production_location (WH1/PPP)

2、Raw material location  is WH1/Stock, finshed Location is WH1/Stock

3、Update Product_qty number ..3 to 10 

4、stock move only change  WH1/PPP --> WH1/Production  qty number  3 to 10

5、stock move WH1/Stock --> WH1/PPP  qty number still is 3 ....not 10...

so...this need fix..

**Comment by Yenthe666** [comment]
Hi @OSSTWJason,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
