### ISSUE TITLE
[9.0e] Calculated fields broken behaviour for new records

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#11239]
### Impacted versions:
[9.0e]

### Steps to reproduce:
Very important to not access any other records as this will change the behaviour. Do those steps as they are indicated.

1) Create a new database with demo data
2) Go in Apps and install test_module
res_partner.py:
```
from openerp import models, fields, api


class ResPartner(models.Model):
    _inherit = "res.partner"

    # country_id = fields.Many2one(domain="[('id', 'in', available_country_ids and available_country_ids[0] and available_country_ids[0][2] or False)]")
    available_country_ids = fields.Many2many('res.country', compute='_compute_available_country_ids')

    @api.depends('street')
    def _compute_available_country_ids(self):
        for x in self:
            if x.street and x.street[0:1] == '1':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1,))])
            elif x.street and x.street[0:1] == '2':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2))])
            elif x.street and x.street[0:1] == '3':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2, 3))])
            else:
                x.available_country_ids = self.env["res.country"].search([])
```

res_partner.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="view_partner_form_test" model="ir.ui.view">
            <field name="name">view.partner.form.test</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="arch" type="xml">
                <field name="category_id" position="after">
                    <field name="available_country_ids"/>
                </field>
                <field name="country_id" position="attributes">
                    <attribute name="domain">[('id', 'in', available_country_ids and available_country_ids[0] and available_country_ids[0][2] or False)]</attribute>
                </field>

            </field>
        </record>
    </data>
</openerp>
```
3) Go in Contacts app
4) Click Create
5) Click on the Country field

### Current behavior:
JS error:
```
Uncaught Error: No conversion for undefined
```
```
http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:3103
Traceback:
Error: No conversion for undefined
    at wrap (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:3103:44)
    at Object.py.type.__getitem__ (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:3108:293)
    at Object.py.PY_getItem (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2889:11)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2972:74)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2967:123)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2967:204)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2968:43)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2971:111)
    at Object.py.evaluate (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2973:99)
    at Object.py.eval (http://localhost:8069/web/content/367-52bc39d/web.assets_backend.js:2978:284)
```

### Expected behavior:
Even if for method _compute_available_country_ids is executed twice after clicking the country field, the information isn't transferred to the client correctly (or not at all maybe). 

When editing existing records, that works fine. When you edit existing record, discard changes and create a new record, the data in available_country_ids is also set (maybe from the previous edit) and the Odoo doesn't crash. But when the first thing you do after getting in the Contacts app is create a new record, that won't work.

As you can see I also tried to set the domain on the model itself (commented line) instead of the view. The behaviour remained the same...

My goal as you can see is to define custom domain filter on a field that will be computed and recomputed on another field change (in this case street field is triggering changes). It must work immediately after:
 - Creating new record
 - Editing of existing record

### Code:
[test_module.zip](https://github.com/odoo/odoo/files/161946/test_module.zip)

**Comment by beledouxdenis** [comment]
@rco-odoo 
This issue seems to be a regression of the revision 09397384795f440b5924d9b325988e9cc6eb4d09.
Indeed, before this revision, for new records, the values of a *2many field was an empty recordset
Now, if the values passed to the `convert_to_cache` method is an empty list (`[]`), the values returned are all the ids (while, if the `values` parameter is a `6` tuple command with an empty list, `[(6, 0, [])]`, it behaves correctly (empty recordset).

See my proposal in branch https://github.com/odoo-dev/odoo/tree/9.0-fix-11239-dle

**Comment by krueger80** [comment]
@beledouxdenis I just tried the patch and it seems to work for this issue. Thanks
