### ISSUE TITLE
[9.0] Display of selection fro object_id not complete

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#11232]
Impacted versions: 9 

Steps to reproduce: On marketing.campaign, when I want to select a object_id from the 'search more'

Current behavior: it only displays the 160 first. To find more I have to use the search bar. 

Expected behavior: it should display all the possibilities, not only by using the search bar

Video/Screenshot link (optional):
![display 160](https://cloud.githubusercontent.com/assets/12964307/13564376/7d697af2-e449-11e5-8937-2796b17cc137.png)

**Comment by Yenthe666** [comment]
Hi @bene1505,

Thanks a lot for your bug report.
This is however default (and intended) behaviour. If you would want to see all the result you should first do a search, then remove it and then you'll see all records.
The reason why this is done is for performance, so only the very first 160 records are shown.

Regards,
Yenthe
