### ISSUE TITLE
Feature Request:  Sales UOM in the Product Settings

### ISSUE THREAD

**Issue by yipster222** [odoo/odoo#112479]
Impacted versions:
All

Steps to reproduce:
Inventory - Product - General Information Tab

Current behavior: 
Sales UOM is derived from UOM from Default UOM used for all stock operations

Expected behavior:
Would like an added feature to set the Sales UOM in different UOM while keeping the Default UOM different

Just like there is a setting for Purchase UOM, all needed to be done is a setting for Sales UOM that defaults to the defined UOM instead of manually chaning the UOM during Quote / Sales Order entry.

Video/Screenshot link (optional):
https://imgur.com/a/P5GEzZ1

Support ticket number submitted via odoo.com/help (optional):

**Comment by dalaOdoo** [comment]
Hello @yipster222 can you explain why you need this and what problem does it solve ?

**Comment by yipster222** [comment]
Allowing distributors to sell in different units while keeping the default base units throughout the system. 

I understand packaging takes care of selling in different uom but the person need to know how many units in a pack.  It’s easier for the person enter the quantity of the defined uom set in the product general tab.

basically allows a user to quickly enter a sales order without changing the UOM during SO entry.  This allow us to sell in different UOM and keeping the UOM in the lowest base units for the reporting and financials.

**Comment by dalaOdoo** [comment]
There are not enough use cases and added value in compare of the complexity it will add.

**Comment by yipster222** [comment]
How complex will this be?
It’s the same as having the purchase uom setting.
All needs to be done is set the Sales UOM per product for Sales.

**Comment by yipster222** [comment]
The purchase uom setting just set the desire uom from the default system uom in purchase.

Ex. If the system uom is set to Units and sales uom is set to 2doz.  Once a SO is crested and that product is entered it will pull the uom the defined sales uom instead of the inventory uom.

**Comment by dalaOdoo** [comment]
This is a change with impacts everywhere: sales, PoS, ecom, reports, price computation, discounts, Loyalty, ... 
Then it will require to analyse everywhere which uoM we should use
It may help some companies but it will add a useless information for the big majority of users.

**Comment by yipster222** [comment]
I think there is some confusion.
My main goal is for the SO entry for the product UOM to be default to another UOM instead of manually changing it every time.
See image below.

![image](https://user-images.githubusercontent.com/125202696/218756986-43f0b482-f193-4c0c-99ff-c2c503ffb156.png)

its just like how the PO UoM is set, but just need a SO UoM.  Everything else defaults to the Unit of Measure.
See image below.

![image](https://user-images.githubusercontent.com/125202696/218757502-691c30c1-135e-4a07-bf8c-818cb1c8e2bb.png)

**Comment by yipster222** [comment]
What is the difference if we can defined the default SAles UOM vs manually changing it during sales order entry?Sent from my iPhoneOn Feb 14, 2023, at 4:26 AM, dalaOdoo ***@***.***> wrote:﻿
This is a change with impacts everywhere: sales, PoS, ecom, reports, price computation, discounts, Loyalty, ...
Then it will require to analyse everywhere which uoM we should use
It may help some companies but it will add a useless information for the big majority of users.
