### ISSUE TITLE
[CRITICAL | Traceback | Accounting Reports] :-  While expanding "Check Register" Report!

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#112480]
Impacted versions: [16.0 E]

Steps to reproduce:
- Go to Accounting, Reporting, Audit Reports, and Open 'Check Register'
- Try to expand any 'Account' here which having Data. 

Current behavior:
- Throwing Traceback

Expected behavior:
- It should not raise 'Traceback' instead should open the related captured Transactions.
Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/36708909/218334698-a8318757-d90d-4728-81d8-0e6d89469a46.png)

[db2f640a-aa7b-4aac-bfc4-f04f56e07efc.webm](https://user-images.githubusercontent.com/36708909/218334665-c0560971-4111-4e31-b37d-81a45ef0bc03.webm)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Fixed: https://github.com/odoo/enterprise/commit/80f278ebdda7093002ba7c013db63fb51000c4c6
