### ISSUE TITLE
How to apply domain filter on Many2One field Using Odoo JS?

### ISSUE THREAD

**Issue by ayazmansuri** [odoo/odoo#11243]
Hello Community...!!!

Currently, I am Working on POS Customization. I've done almost but stuck in this issue. 

**Py File:**

`class prescription(osv.osv):

_name = 'res.prescriptions'

_columns={

'prescription_id':fields.many2one('res.partner',"customer"),

}

class prescription_res_partner(osv.osv):

_inherit = 'res.partner'

_columns = {

'prescriptions_ids': fields.one2many('res.prescriptions','prescription_id','Prescriptions'),

}`

What I would like to do, is that when the user **select customer** in POS, and click on*\* Prescription Button,*\* it shows only prescriptions that are related to **particular selected customer**.. For now, it displays all prescriptions as I am not able to set correctly the **filter domain**. Also.....

i've tried to solve my problem using **.query()**, .**filter()** in **JS**. but getting some errors, while if i put static partner_id then it will display prescriptions for given static partner_id. I want to solve this for dynamic partners. it shows only selected partner's prescriptions...!!!

**In JS File:**

var def = new $.Deferred();

console.log("deffffffffffffff", def);

var fields = _.find(this.models,function(model){ return model.model === '**res.prescriptions'**; });

new instance.web.Model(**'res.prescriptions**')

**.query**(fields)

**.filter**([['**prescription_id**', '=', 51]]) **// Here i pass static partner_id instead of this i want to pass dynamic partner_id**

.limit(1000)

.all()

.then(function(prescriptions){

if (self.render_list_prescription(prescriptions)) { // Render selected partner's Prescription

def.resolve();

} else {

def.reject();

}

}, function(err,event){ event.preventDefault(); def.reject(); });

return def;

i've spend almost 3 days to overcome this problem but failed to Deliver it. please help me out from this. Again Many Thanks for your help..!!!

**Comment by krueger80** [comment]
First you should ask the question on the forum, not on github: https://www.odoo.com/fr_FR/forum/aide-1
Second, please format your post so it is readable. Not cool to read. Check all the cool formatting buttons right there for you :)
Last, I can certainly help answer your question... no need to change the JS code... it's all in the domain... either on the model, or on the view...

**Comment by ayazmansuri** [comment]
i aready posted this issue on odoo community.
[https://www.odoo.com/forum/help-1/question/how-to-apply-domain-filter-on-many2one-field-using-odoo-js-98882](url)

**Comment by Yenthe666** [comment]
Hi all,

As mentioned by @krueger80 these kind of questions are for the help forum (and I see you did post it there too).
The Github bug tracker is only for bugs in the official Odoo code and nothing else.

Regards,
Yenthe
