### ISSUE TITLE
[9.0e] Late server call when changing a dependency of field used in a domain expression and immediately click the many2one field where the domain is apply

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#11240]
### Impacted versions:
[9.0e]

### Steps to reproduce:
1) Create a new DB with demo data
2) Go in Apps and install test_module
res_partner.py:
```
from openerp import models, fields, api


class ResPartner(models.Model):
    _inherit = "res.partner"

    # country_id = fields.Many2one(domain="[('id', 'in', available_country_ids and available_country_ids[0] and available_country_ids[0][2] or False)]")
    available_country_ids = fields.Many2many('res.country', compute='_compute_available_country_ids')

    @api.depends('street')
    def _compute_available_country_ids(self):
        for x in self:
            if x.street and x.street[0:1] == '1':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1,))])
            elif x.street and x.street[0:1] == '2':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2))])
            elif x.street and x.street[0:1] == '3':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2, 3))])
            else:
                x.available_country_ids = self.env["res.country"].search([])
```
res_partner.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="view_partner_form_test" model="ir.ui.view">
            <field name="name">view.partner.form.test</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="arch" type="xml">
                <field name="category_id" position="after">
                    <field name="available_country_ids"/>
                </field>
                <field name="country_id" position="attributes">
                    <attribute name="domain">[('id', 'in', available_country_ids and available_country_ids[0] and available_country_ids[0][2] or False)]</attribute>
                </field>
            </field>
        </record>
    </data>
</openerp>
```
3) Go in Contacts app
4) Open Agrolait contact and click edit
5) Replace street field by "1 rue Laurier"
6) Click on country field to reveal the list of country

### Current behavior:
All countries are listed.

### Expected behavior:
Only one country should be listing since the country domain filter is based on available_country_ids and available_country_ids is dependent on street field. 

When clicking the country field a second time, the domain is applied correctly. Whenever the user change a dependency of field used in a domain expression and immediately click the many2one field where the domain is apply, the list of value seems always one step behind. Two clicks are therefore necessary to show the correct domain.

### Code:
[test_module.zip](https://github.com/odoo/odoo/files/161965/test_module.zip)

**Comment by beledouxdenis** [comment]
Solved as well with PR #11252.

**Comment by krueger80** [comment]
@beledouxdenis the patch works for #11239, but it doesn't help for this issue unfortunately.

**Comment by rco-odoo** [comment]
@krueger80 I tried the given scenario with PR #11335, and the issue is fixed:
 - open "Agrolait", click "Edit"
 - set field "Street" to "1 rue Laurier"
 - click on field "Country": only one country is listed

**Comment by rco-odoo** [comment]
@krueger80 using domains with x2many fields does not work well, because the value of those fields is not a list of **ids**, but a list of **commands**. Your domain assumes explicitly that the list of commands is something like `[(6, 0, ids)]`. But nothing guarantees that it will always have this form...

In such a situation, we recommend to set a domain in an onchange method instead:

    @api.onchange('available_country_ids')
    def _onchange_available_countries(self):
        return {'domain': {
            'country_id': [('id', 'in', self.available_country_ids.ids)],
        }}

**Comment by krueger80** [comment]
As of #11335, onchange doesn't trigger when opening existing record. Unless there is a magic trick to force the on change right when opening a record, this is not an acceptable solution to me.
