### ISSUE TITLE
Odoo load all python modules even modules that aren't installed.

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#11245]
Impacted versions:

All

Steps to reproduce:
1. Install a fresh odoo setup with some addons.
2. remove all pyc files with rm *_/_.pyc 
3. Start odoo, load odoo in a browser to start the boot process
4. Check in any addons folder there should be .pyc files

Current behavior:

All possible python modules are loaded.

Expected behavior:

Only python modules of installed addons should be loaded.

---

To explain more the problem is that as any module can be loaded at memory time, it is enough to put a folder with bad imports in the addons folder to prevent odoo to boot correctly. For example, if we want to install odoo with OCA repository, we have to make sure that all python dependencies are met even though the dependencies might not be needed by the modules that we plan to use.

On other quite _terrible_ thing that I realized is that the connector module is actually monkey patching the openerp models like this during import.

```
models.BaseModel.write = write
```

The result is that it will lunch a ConnectorSession for create/write/unlink even though the Connector module isn't installed!!!!!!! really!!!! The only thing that is required is that the connector is in the addons paths. In other words, any module could monkey patch itself inside odoo as long as it's in the odoo's addons path. No need to install modules! You can load them yourself.

It would make more sense for odoo to rely only on the **openerp**.py manifest to manage module dependencies without loading python modules unless the module is installed.

**Comment by krueger80** [comment]
If there is a way to only read the __openerp__.py file and not all the other files, that's be great. I also ran in issues couple times because a module had something bad in them. Like invalid character ub comment or something on top of a py file

**Comment by llacroix** [comment]
As for the Connector module, I realized later that it does actually check if the module is installed first. But this doesn't make it any nicer... the modules shouldn't have to check if they are installed or not. As far as I know the connector module has to be in the addons path in one project because one other module requires it directly with `from addons.... import ....` which raises an Error while loading odoo even though both modules aren't installed. It is just required to prevent import errors.

**Comment by kkinateder** [comment]
Confirm, that this a terrible behavior. Iam monkeypatching in some of my custom modul and that is loaded on every odoo instance even there the modul isnt installed. Thats more as vulnerable and should be set as high priority.

**Comment by pedrobaeza** [comment]
You should monkey patch in `_register_hook` method and using `_patch_method` instead.

**Comment by kkinateder** [comment]
Connector then too?!   Thanks pedrobaeza, when I can do better you are welcome. But at least that not protects odoo from executing not installed moduls. so my recommendation to change that behavior and set this issue with high priority remains.

**Comment by pedrobaeza** [comment]
Closing as no more relevant information.
