### ISSUE TITLE
Account Invoice Email - AttributeError: 'Environment' object has no attribute res

### ISSUE THREAD

**Issue by holdenrehg** [odoo/odoo#11257]
This appears to be caused by the commit https://github.com/odoo/odoo/commit/9a56bf5fe46bb198c48a7e6b6547310a3c2c755f because self.env does not have an attribute called `res`.

Impacted versions:
- Odoo 9 Enterprise

Steps to reproduce:
- Send an email from an invoice using the "Send By Email" button

Current behavior:
- Throws the following exception:

`AttributeError: 'Environment' object has no attribute res`

This is happening for the file `addons/account/modules/account_invoice.py`, line 992
    `group_user = self.env.res('base.group_user')`

Expected behavior:
- An exception should not be thrown

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @holdenrehg,

This bug has been fixed quite a while ago but your bug report was never closed. 
If you haven't updated your source code then please do so.
P.S: Hi again! 😉 

Regards,
Yenthe

**Comment by bluestingray** [comment]
Ah hey thanks @Yenthe666 .

And hi again :) long time no talk.

Holden
