### ISSUE TITLE
[9.0] Payment paypal method not load button "Pay now" in email.

### ISSUE THREAD

**Issue by kurkop** [odoo/odoo#11259]
Impacted versions: Community and enterprise 9. And runbot.

Steps to reproduce:
- Install payment_paypal
- Configure with data dummy
- Create and validate Invoice 
- Click in button "Send by email"

Current behavior:
- The email template and email set not load the paypal button

Expected behavior:
- The email template and email set should load the paypal button

**Comment by nicholas-itpedia** [comment]
We are also experiencing this behavior on our Odoo 9 Enterprise AND Odoo 9 Community Edition databases.

We confirmed this on Odoo Runbot as well.

**Comment by gustavovalverde** [comment]
Confirmed in our Odoo 9 Community Edition.

**Comment by Yenthe666** [comment]
@mart-e and @nim-odoo that is the third person talking about this issue. Looks like it it time to do something about this. :smile:

**Comment by dmheller** [comment]
Also Confirmed in our Odoo 9 Community Edition.

**Comment by mart-e** [comment]
Hello,

Indeed, we stopped having the "pay now" button in the emails, it was not very flexible. The idea is to use the `website_quote` module to pay on the website.
So sorry but we do not intend to reintroduce this.

**Comment by elevationO** [comment]
As a user of Odoo in production for my business I don't understand why you would move to the quote phase only to collect payments.  We don't ask for payment until the invoice is sent, after the delivery has been made.  I understand that this module is more flexible as it actually works when adding fees (based on payment acquirers) but it should also be an option to click and pay an invoice like you can with a quote.  Thoughts?
