### ISSUE TITLE
Pos install permission issues

### ISSUE THREAD

**Issue by PeregrineSpur** [odoo/odoo#11250]
Impacted versions:Odoo V9 posboxless installation

Steps to reproduce: Installation as per instructions on website

Current behavior:Pos not connecting to scanner

Expected behavior:Expect the system to work?

Video/Screenshot link (optional):
error received 
openerp.addons.hw_escpos.controllers.main: error : [Errno 13] Access denied (insufficient permissions)

**Comment by jorenvo** [comment]
Please read the 'access rights' section in the [official documentation](https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html#posboxless-guide-advanced).

**Comment by PeregrineSpur** [comment]
I have been busy for 5 days and still no luck, one of the most difficult installations I have had to do. Documentation is grossly incomplete. I have had to piece together the installation from information from various websites. If only the installation was as good as the sales pitch. I still can't get the POS to talk to the postbox software on linux.

**Comment by jorenvo** [comment]
I'm sorry to hear that. The issue you're describing has little to do with Odoo however. It has to do with how your operating system is managing access to devices. By default a lot of Linux distributions do not allow applications to access certain USB devices. For this reason we provide some udev rules (the same ones we use on the official POSBox image) to allow Odoo to access these devices. These rules have been tested on Raspbian Wheezy and Ubuntu LTS 14.04. If you are using another distribution then there is a possibility that they do not work. If that is the case then consult your distribution's documentation on how to resolve this.

Do keep in mind that setting up your own POSBox is something we don't officially support, and is something that we generally only recommend to people with some experience with GNU/Linux systems.

**Comment by PeregrineSpur** [comment]
Hi Jorenvo,

I reinstalled the system, works out the permission issue was to do with missing python dependencies which I found in other documentation on another site. I am now at a point where I have no more permission errors, but the pos does is still not linking to the posbox software.

Your website portrays this as a viable solution, and as such I gave it preference over Ofbiz. Your site also portrays an easy installation process which it is far from. I have 20 years commercial programming experience and have never encountered such a problem before. 

There is a difference between help and support. I would suggest that if odoo are not prepared to help with at least explaining the implementation process correctly you should not offer the solution on your website. As I said the documentation is extremely poor missing many steps.

I am in a serious disposition as i have promoted your product to my client. The reason we did not install the enterprise solution is because it is an African country with poor internet connectivity and the reason we did not install posbox’s is because there was existing hardware we could use.

What do you suggest I do at this point. Who can help?

P.s the installation of the server side went ok, but only after the 3rd time when I decided to not follow the documentation on your site.

**Comment by jorenvo** [comment]
I understand, we should make it clearer in the documentation that setting up your own POSBox is not very straightforward.

Could you describe to me the overall setup you're trying to use? Is the Odoo server and the "POSBox" supposed to run on the same machine, or on different machines? Are you connecting from a remote client like a tablet or are you running a browser on the same system as is running Odoo?

**Comment by PeregrineSpur** [comment]
The plan is to have 6 cashiers linked to a server.

I am currently trying to just get 1 pos up on 1 machine. i.e the odoo instance and posbox software on a single machine. I read in another installation guide that you need to set up a db named posbox with just the “driver/proxy apps” loaded and a second to run the pos app, not sure if it is true as the odoo documentation does not mention this. I have tried both routes. 
I have followed the installation down to the last full stop. And although the permission file for usbusers was created i am still getting the following error
Barcode Scanner Error: [Errno 13] Permission denied: '/dev/input/by-id/usb-04f3_0103-event-kbd’ 

I think this the last issue

**Comment by jorenvo** [comment]
>  I read in another installation guide that you need to set up a db named posbox with just the “driver/proxy apps” loaded and a second to run the pos app, not sure if it is true as the odoo documentation does not mention this. I have tried both routes.

You could, but if you're just testing you can just run everything in the same db. It shouldn't make a difference.

> Barcode Scanner Error: [Errno 13] Permission denied: '/dev/input/by-id/usb-04f3_0103-event-kbd’

Please ensure that you have created the usbusers group and have added the user the odoo server will be running as to it. If that is the case then you need to inspect the permissions of that particular file and ensure that the user you use for odoo can open it. If I had to guess, the file is probably owned by root and not readable by anyone else, the udev rule is supposed to fix that (provided ofcourse you are part of the usbusers group).

In a correct setup you should see this:

```
pi@raspberrypi ~ $ ls -alh /dev/input/by-id/
total 0
drwxr-xr-x 2 root root  60 Mar  9 12:04 .
drwxr-xr-x 4 root root 120 Mar  9 12:04 ..
lrwxrwxrwx 1 root root   9 Mar  9 12:04 usb-Honeywell_Scanning_and_Mobility_Honeywell_Scanning_and_Mobility_Scanner-event-kbd -> ../event0
```

Which as you can see is a symbolic link readable by everyone, which links to event0:

```
pi@raspberrypi ~ $ ls -alh /dev/input/
total 0
drwxr-xr-x  4 root root        120 Mar  9 12:04 .
drwxr-xr-x 13 root root       3.2K Mar  9 12:04 ..
drwxr-xr-x  2 root root         60 Mar  9 12:04 by-id
drwxr-xr-x  2 root root         60 Mar  9 12:04 by-path
crw-rw---T  1 root usbusers 13, 64 Mar  9 12:04 event0
crw-rw---T  1 root input    13, 63 Jan  1  1970 mice
```

Which as you can see is a file readable by everyone in the usbusers group so when running odoo.py as a user that is part of the usbusers group it will have permission to read it.

**Comment by PeregrineSpur** [comment]
This is what I have 
The difference I see is that your event 0 has owner as usbusers with write access. Am I correct in saying that this what the dev rule is supposed to sort out?

Below are my settings

odoo@pos2-desktop:~$ ls -alh /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 120 Mar  9 11:11 .
drwxr-xr-x 4 root root 320 Mar  9 11:11 ..
lrwxrwxrwx 1 root root   9 Mar  9 11:11 usb-04f3_0103-event-if01 -> ../event8
lrwxrwxrwx 1 root root   9 Mar  9 11:11 usb-04f3_0103-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Mar  9 11:11 usb-Logitech_USB_Optical_Mouse-event-mouse -> ../event9
lrwxrwxrwx 1 root root   9 Mar  9 11:11 usb-Logitech_USB_Optical_Mouse-mouse -> ../mouse0
odoo@pos2-desktop:~$ ls -alh /dev/input/
total 0
drwxr-xr-x  4 root root    320 Mar  9 11:11 .
drwxr-xr-x 17 root root   4.2K Mar  9 12:06 ..
drwxr-xr-x  2 root root    120 Mar  9 11:11 by-id
drwxr-xr-x  2 root root    120 Mar  9 11:11 by-path
crw-r-----  1 root root 13, 64 Mar  9 11:11 event0
crw-r-----  1 root root 13, 65 Mar  9 11:11 event1
crw-r-----  1 root root 13, 66 Mar  9 11:11 event2
crw-r-----  1 root root 13, 67 Mar  9 11:11 event3
crw-r-----  1 root root 13, 68 Mar  9 11:11 event4
crw-r-----  1 root root 13, 69 Mar  9 11:11 event5
crw-r-----  1 root root 13, 70 Mar  9 11:11 event6
crw-r-----  1 root root 13, 71 Mar  9 11:11 event7
crw-r-----  1 root root 13, 72 Mar  9 11:11 event8
crw-r-----  1 root root 13, 73 Mar  9 11:11 event9
crw-r-----  1 root root 13, 63 Mar  9 11:11 mice
crw-r-----  1 root root 13, 32 Mar  9 11:11 mouse0

One more thing, does odoo support scanner over serial port?

**Comment by jorenvo** [comment]
>  Am I correct in saying that this what the dev rule is supposed to sort out?

Yes that's exactly what it's there for. In your case only the root user can read the devices in /dev/input.

> One more thing, does odoo support scanner over serial port?

No, hw_scanner only supports USB barcode scanners that act as a keyboard (i've never come across a USB one that doesn't act as a keyboard).

**Comment by PeregrineSpur** [comment]
Thanks for the help, I have checked the group and users again and all is correct. I have to go hunt the problem down.
one more thing last I promise. The user running odoo needs write access to odoo-server.pid in var/run but after reboot permissions are set back to root.  How did you work around this issue?

When I am done I am going to document the complete installation, you are welcome to update your site with the instructions.

Regards
Perry Spurway

**Comment by jorenvo** [comment]
> one more thing last I promise. The user running odoo needs write access to odoo-server.pid in var/run but after reboot permissions are set back to root.  How did you work around this issue?

The reason it needs permissions in /var/run is because we specify it in the [configuration file on the POSBox](https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/tools/posbox/configuration/odoo.conf). So you could modify the paths in that configuration file to somewhere you have write access.

You could also opt to automatically set permissions on /var/run at boot, this is what we do on the POSBox. This is done in our [rc.local file](https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/tools/posbox/overwrite_after_init/etc/rc.local) (/etc/rc.local gets run automatically at boot).

**Comment by PeregrineSpur** [comment]
Thank you

**Comment by jorenvo** [comment]
No problem. By the way, don't forget to reboot after you add a user to a group, it'll only take effect after you've completely logged in and out (rebooting is the easiest way).

**Comment by grexe** [comment]
I sadly had similar problems with the otherwise very usefull Odoo+POSboxless setup, in my case the stumbling blocks were:
* I had setup the rules a bit differently than mentioned in the docs (don't know how I ended up with that), udev was fine with them, but the Python-scripts in POSbox seem to access the hardware exactly by the path given in the docs, changing that solved my issues and I could scan+print out of the (POS;)box...
* just in case: for testing udev rules, you don't have to reboot, you can reload udev rules with

> udevadm control --reload
* obvious in hindsight, but you have to start posbox with a different port than the odoo server, I created a separate init script for the posbox server
* I didn't setup a separate db, just reused the settings from odoo
* you don't need to start odoo server with any special modules, just leave the default settings - this is all handled by posbox

Now if there was only a way to configure the template used for printing receipts... want to get rid of the useless "stock" line...

All in all I'm quite happy with Odoo 9 and hope it will mature over time, but there are some unexpected bumps and lack of decent documentation (heck, even some basic tutorial videos are only available with paid subscriptions!) that make me feel pushed a little too blatantly to the enterprise version...,-)
