### ISSUE TITLE
[9.0] creating a refund creates an invoice

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#11269]
Impacted versions:

9.0 enterprise and community

Steps to reproduce:

* go to the accounting dashboard
* click more in the kanban block of Vendor Bills or Customer Invoice
* click Refunds -> refunds are displayed, ok, although the Title says Vendor Bills or Customer Invoices
* click Create -> an invoice is created instead of a refund

Current behavior:

An invoice is created while in the refund view. This is confusing for the user.

Expected behavior:

A refund should be created.

Video/Screenshot link (optional):

**Comment by sbidoul** [comment]
@qdp-odoo this one is till present in latest 9.0 enterprise. Can you check? This very annoying not being able to create a credit note. Thanks in advance.

**Comment by qdp-odoo** [comment]
Sorry, but I'm not able to reproduce... It seems that either I'm missing a step in the use case or you are being confused by the fact that the refunds now, by default, share the same numbering as the invoices within the same journal.
