### ISSUE TITLE
[9.0] [BUG] Can't create a mailing list 

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#11268]
Impacted versions:9

Steps to reproduce: 
1. Go to mass mailing
2. Create a mailing list
3. give a name and save

Current behavior: error message "The following fields are invalid: Website Popup Content"

Expected behavior: No error message :-) and be able to select the recipients

Video/Screenshot link (optional):
<img width="1406" alt="mailing list" src="https://cloud.githubusercontent.com/assets/12964307/13631717/77ee414a-e5e6-11e5-909b-05bb03042d69.png">

**Comment by mak5** [comment]
I had the same issue but after several times it worked, you have to fill the mailing list name first

**Comment by rafaelDelgado** [comment]
I was getting this error many times, I just wait till the page is loaded, then the error is gone..
