### ISSUE TITLE
Calendar error: [9.0]TypeError: self.get_all_filters_ordered is not a function

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#11261]
Impacted versions: Enterprise 9.0
Module: Calendar
File: base_calendar.js

Seems to be related to this fix: https://github.com/odoo/odoo/commit/924c2dee21fffec7eb2df68cbe703238afc9b438

**Comment by JKE-be** [comment]
Can you confirm that it is always present ? 
Please provide a "How to reproduce"...

**Comment by Yenthe666** [comment]
I'm closing this bug report as there has been no response on the questions.

Regards,
Yenthe
