### ISSUE TITLE
[7.0] The link to add new records isn't show (one2many)

### ISSUE THREAD

**Issue by johnsh** [odoo/odoo#11263]
Hi everybody, 

I use OpenERP ( Versión 7.0-20160211 ).
I have one form that is very long, the form has 300 fields include one2many fields.

**Impacted versions:** OpenERP ( Versión 7.0-20160211 )

**Steps to reproduce:** 
- This bahavior sometimes ocurrs
-  I use the user admin to test

**Current behavior:** Sometimes when I create a new record the field one2many isn't render completely, then I press f5 and I try again then the field one2many load perfectly.

_The link to add new records isn't show_

![no_tiene](https://cloud.githubusercontent.com/assets/1112534/13618770/f9b4861e-e553-11e5-90df-feb59bce608b.JPG)

**Expected behavior:** all the fields (one2many) are loaded completely

![si_tiene](https://cloud.githubusercontent.com/assets/1112534/13618840/31d8463e-e554-11e5-99e5-d28dd3e88429.JPG)

Video/Screenshot link (optional):

(Sorry my english isn't very good yet)

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @johnsh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
