### ISSUE TITLE
[16] calendar filters not displaying the filter value

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#112689]
Impacted versions: 16.0

Steps to reproduce:
1. open sale order calendar view
2. see the state filters
3. currently displaying as undefined

Current behavior:
label is showing as undefined

Expected behavior:
display selection field label correctly

Video/Screenshot link (optional):

![Screenshot from 2023-02-14 16-56-18](https://user-images.githubusercontent.com/27989791/218759234-c7bd6665-e764-40dc-99ed-3beac5a69efe.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @Feyensv ,
if you have time, can you notify this to the corresponding team. 
thanks

**Comment by Feyensv** [comment]
cc @bouvyd ?
