### ISSUE TITLE
How to add extra worker in odoo.sh 

### ISSUE THREAD

**Issue by AltapeteSolutions** [odoo/odoo#112750]
Impacted versions:14

Steps to reproduce:

Current behavior:pos working very slow

Expected behavior:need to boost pos speed

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
if you are looking to increase the worker in odoo sh, you can do it from the project settings page

![Screenshot from 2023-02-15 08-48-17](https://user-images.githubusercontent.com/27989791/218943595-0c3d3052-7a0e-4ddb-9103-750f5cc11fe6.png)

**Comment by AltapeteSolutions** [comment]
@niyasraphy thanks for your helpful reply is there any other way to increase/boost pos speed?
