### ISSUE TITLE
Odoo 9 bug security issues.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11273]
Impacted versions:
9

Steps to reproduce:
create new user, app permission including administrator as access right.

Current behavior:
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Administration/Settings
  (Document model: ir.module.category)

Expected behavior:
Should access things, not wired as working.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Not enough information.
We already asked you countless time to provide us information to be able to reproduce an issue on a standard Odoo...
