### ISSUE TITLE
Reccurying events - time change

### ISSUE THREAD

**Issue by Robx64** [odoo/odoo#11289]
Impacted versions:8.0

Steps to reproduce:Creating recurring events time is changing while time change from Winter to Summer

Current behavior:If I create recurring event (for 52 weeks) time of the event start is changing plus 1 hour if time change occurred but it shouldn't. If meeting start time is set to 9:00 even if time switch to Summer, meeting time shouldn't be changed, 9:00 is 9:00 regardless.
(of course I understand that for example current 9:00  will become 10:00 but in calendar meeting time shouldn't be changed) For us time might be shifted forward but it shouldn't affect calendar and time of the meeting.

Expected behavior:Not change meeting time
![tissue](https://cloud.githubusercontent.com/assets/6826063/13667495/89885ec2-e6ae-11e5-90c0-f4a4cd9327a2.png)
As on the attached picture, meeting time before "time change" is 8, after it is 9 while it should be 8.
Video/Screenshot link (optional):

Any ideas or if i'm wrong, would someone explain why odoo is doing it ?

**Comment by schmidtwastl** [comment]
I can confirm this problem. See #9268

**Comment by spadae22** [comment]
Yes v8 also

**Comment by JKE-be** [comment]
Thanks for the reporting.
I close this one because duplicated of #9268
