### ISSUE TITLE
[9.0e] Reply-to email address not using template field value on SO/PO/DO

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#11286]
Impacted versions: [9.0e]

Steps to reproduce: Create template or edit existing.  Fill in value to the 'reply to' field.

Current behavior: Reply email goes to the sales rep or user that created the SO/PO/DO

Expected behavior: Should use the email address provided in template 'reply to' field

Video/Screenshot link (optional):

**Comment by houssine78** [comment]
any news on this problem I'm facing the same issue

this seems to be related to https://github.com/odoo/odoo/issues/16635

**Comment by houssine78** [comment]
This issue could be related to the problem and give some hints to understand that the mail composer could be the problem.

**Comment by houssine78** [comment]
Hi @odony does this problem is known by Odoo SA? In that case any workaround to suggest so fare?

thanks for your time

**Comment by odony** [comment]
It's the expected behavior. When posting a message on a SO/PO/.., replies should go to the document, nowhere else, otherwise you lose history and tracking. "Reply-To" on mail templates is meant to be used for mass-mailing purposes, not for direct posting on documents.

**Comment by houssine78** [comment]
ok thanks I'll find another way then as I don't need to pass by the mail composer.

**Comment by janbec** [comment]
@houssine78 Have you found another way? I'm looking at the same problem...

**Comment by houssine78** [comment]
@janbec as odony said this not the purpose of the mail composer. 

Knowing that you could add a new button or overidding the existing one to by pass the mail composer and directly sent the email through the mail template function.
