### ISSUE TITLE
[8.0] Computed fields without  store option, doesn't work

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#11283]
Impacted versions:
8.0
Steps to reproduce:
- Create new field in res.partner with compute option
- Create a new record in res.partner

``` python

from openerp import fields, models, api


class ResPartner(models.Model):
    _inherit = 'res.partner'

    @api.multi
    def _get_new_field_method(self):
        print "##"

    new_field = fields.Many2one(
        comodel_name='delivery.carrier',
        compute=_get_new_field_method,
        store=True)

Current behavior:
The function `_get_new_field_method` never triggers, and the print stament doesn't works

Expected behavior:
Trigger the `_get_new_field_method` when create/wirte events occurs over the record

```

**Comment by Yenthe666** [comment]
Hi @hugho-ad,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
