### ISSUE TITLE
Omnisearch on stock moves doesn't find products properly

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1128]
Hello:
Testing on runbot
http://06083-8-0-0a6d63.runbot.odoo.com/

Made this test:
Try to look for "1" on search box. Select product -->It finds ice cream
Try to look for "12". select product --> Finds nothing
Try to look for "a1232" select product --> Finds nothing
Try to look for A1232 -->Finds correct [A1232] iPad Mini 
Try to look for ipad or iPad Mini or iPad -->Finds nothing

It seems that it's only looking for code key sentitive. 
I could reproduce in other instances but runbot. 

Thank you:
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
