### ISSUE TITLE
Gamification bug on display granted users

### ISSUE THREAD

**Issue by baba75** [odoo/odoo#11288]
Impacted versions: 8.0

Steps to reproduce: Install gamification module without hr_gamification

Current behavior: in the badge.xml view there is call to function get_granted_employees that does not exist in module. That function is present on hr_gamification. 

Expected behavior: When only gamification is installed the function should be get_granted_users

Video/Screenshot link (optional):
![snapshot](https://cloud.githubusercontent.com/assets/17760908/13665043/c6dabfd0-e6aa-11e5-928d-e1d9a366104f.png)

**Comment by Yenthe666** [comment]
Hi @baba75,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
