### ISSUE TITLE
[16.0] [BUG] Can't pring reliable report while in developper mode

### ISSUE THREAD

**Issue by pierre-pizzetta** [odoo/odoo#112946]
Impacted versions:
16.0

Steps to reproduce:
Open any runbot on 16.0, switch to developper mode, print a report (like invoice), header/footer will randomly disappear.

Current behavior:
PDF generated by wkhtmltopdf are randomly broken

Expected behavior:
PDF are generated reliably

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by chrisdilbert** [comment]
Hi, I'm having the same issue footer is missing and the header isn't the same.

**Comment by vava-odoo** [comment]
Hi @pierre-pizzetta 
That is unfortunately one (of the) limitation(s) with wkhtmltopdf. You _need_ to turn off developer mode.
Cheers

**Comment by pierre-pizzetta** [comment]
Understood, too bad it took so long just to get that answer. Since you NEED to be in developer mode to have access to the XML editor while editing a template in studio, but that you lose the ability to realiably print to check your changes it's really a miss~ Maybe it's time to stop using wkhtmltopdf, since it's not even maintained anymore (even the repo was set to read-only in January)
