### ISSUE TITLE
Couldn't find pickings group by or filtered by supplier or customer

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1129]
Test:
Go to pickings
Select delivery or reception type ones
Try to group by supplier or customer / Try to filter by supplier or customer

Field is missing in both options. 
This could be considered a blueprint instead a bug, but IMHO is a big issue that this small feature is not included by default.

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
