### ISSUE TITLE
POS Fiscal Position not working properly

### ISSUE THREAD

**Issue by mvercruysse** [odoo/odoo#11299]
Impacted versions:
8.0

Steps to reproduce:
1. Go to a runbot instance
2. Configure your accouting with the Belgian PCMN
3. Add a fiscal position "Intra-Com" to one customer (ex: Agrolait)
4. Add a customer taxe ( VAT-OUT-21-L) to one product (ex: Lays Natural Light 170g)
5. Open a POS session and select the customer Agrolait
6. Add the product Lays Natural Light 170g in you "ticket"
7. Choose the cash journal and ask an Invoice

Current behavior:
- Taxes are shown in the POS
- Odoo ask to pay in cash the amount with taxes
- The invoice is generated without taxes
- Pos order is created with taxes

Expected behavior:
- Taxes should be at 0 in this case in the POS
- Odoo should ask to pay in cash the right amount (with taxes = 0)
- POS order shoudl be coherent

Video/Screenshot link (optional):
![capture d ecran 2016-03-11 a 10 43 47](https://cloud.githubusercontent.com/assets/8557179/13698763/72eeb88c-e776-11e5-9f52-c68b8d8fdb2b.png)
![capture d ecran 2016-03-11 a 10 45 05](https://cloud.githubusercontent.com/assets/8557179/13698762/72eeade2-e776-11e5-89dc-0e5df869e338.png)
![capture d ecran 2016-03-11 a 10 47 01](https://cloud.githubusercontent.com/assets/8557179/13698768/7e39bc82-e776-11e5-91e3-7be08277c2b4.png)

**Comment by mvercruysse** [comment]
OPW 671743

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/43445db7e432c46252339d2aed4f284fb7b30746
Fiscal positions on PoS frontend was introduced in v9.0 in https://github.com/odoo/odoo/commit/358e285
