### ISSUE TITLE
[9.0] Field filtered with a domain pointing to a *2many field gives error when that *2many field has no record

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#11295]
### Impacted versions:
[9.0]

### Steps to reproduce:
1) Create a new database with demo data
2) Go in Apps and install test_module
res_partner.py:
```
from openerp import models, fields, api


class ResPartner(models.Model):
    _inherit = "res.partner"

    country_id = fields.Many2one(domain="[('id', 'in', available_country_ids and available_country_ids[0] and "
                                        "available_country_ids[0][2] or False)]")
    state_id = fields.Many2one(domain="[('id', 'in', available_state_ids and available_state_ids[0] and "
                                      "available_state_ids[0][2] or False)]")
    available_country_ids = fields.Many2many(comodel_name='res.country', compute='_compute_available_country_ids',
                                             help="Control the list of available country by having 0, 1, 2, 3 or "
                                                  "anything else at the beginning of the address line 1.")
    available_state_ids = fields.Many2many(comodel_name='res.country.state',
                                           help="Add and remove available states here. When there is no state and user "
                                                "try to select a state, an error occurs.")

    @api.depends('street')
    def _compute_available_country_ids(self):
        for x in self:
            if x.street and x.street[0:1] == '0':
                x.available_country_ids = self.env["res.country"]
            elif x.street and x.street[0:1] == '1':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1,))])
            elif x.street and x.street[0:1] == '2':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2))])
            elif x.street and x.street[0:1] == '3':
                x.available_country_ids = self.env["res.country"].search([("id", "in", (1, 2, 3))])
            else:
                x.available_country_ids = self.env["res.country"].search([])
```

res_partner.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="view_partner_form_test" model="ir.ui.view">
            <field name="name">view.partner.form.test</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="arch" type="xml">
                <field name="category_id" position="after">
                    <field name="available_country_ids"/>
                    <field name="available_state_ids"/>
                </field>
                <!-- Domain in the view doesn't change the behaviour -->
                <!--<field name="country_id" position="attributes">
                    <attribute name="domain">[('id', 'in', available_country_ids and available_country_ids[0] and available_country_ids[0][2] or False)]</attribute>
                </field>-->
            </field>
        </record>
    </data>
</openerp>
```
3) Go in Contacts app
4) Click on Agrolait
5) Click on the State field

### Current behavior:
JS error:
```
Uncaught Error: No conversion for undefined
```
```
http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:3103
Traceback:
Error: No conversion for undefined
    at wrap (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:3103:44)
    at Object.py.type.__getitem__ (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:3108:293)
    at Object.py.PY_getItem (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2889:11)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2972:74)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2967:123)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2967:204)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2968:43)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2971:111)
    at Object.py.evaluate (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2973:99)
    at Object.py.eval (http://localhost:8069/web/content/367-27cb252/web.assets_backend.js:2978:284)
```
### Expected behavior:
I'm expecting this code to work since the same thing works when that *2many field is computed. Make the test with the equivalent on the Country field which is controlled with the street field (type 0, 1, 2 or 3 and that number of countries will be available to select).

[EDIT]
Just to make sure it's clear, when you add any records in available_state_ids, the domain computation on state_id works fine. Remove all the records and the computation fails. For the equivalent on a computed field on country_id, it works in all cases.

### Code:
[test_module.zip](https://github.com/odoo/odoo/files/168268/test_module.zip)

### Reference
#11239 - same error message
#11240 - @beledouxdenis was thinking it was related and expected the same fix as #11239, but after testing, it didn't solve it.

**Comment by beledouxdenis** [comment]
and the proposal in #11239 doesn't work for this neither ?

**Comment by krueger80** [comment]
@beledouxdenis no it didn't work with the patch and without the patch.

**Comment by krueger80** [comment]
@beledouxdenis by the way I took this code from https://github.com/odoo/odoo/blob/9.0/addons/crm/base_partner_merge_view.xml#L62. After installing crm module and testing this with code from @rco-odoo (https://github.com/odoo/odoo/pull/11252#issuecomment-196381112), it gives the same error. 

Access this in Contacts app, select one partner, go in Actions->Merge Selected Contacts, remove the only record from the list, then click on the Destination Contact field.

**Comment by rco-odoo** [comment]
@krueger80 like in #11240, we recommend to set a domain in an onchange method instead:

    @api.onchange('available_country_ids')
    def _onchange_available_countries(self):
        return {'domain': {
            'country_id': [('id', 'in', self.available_country_ids.ids)],
        }}

Using x2many fields in client-side domains is not reliable at all, as it may be *any* list of commands...

**Comment by krueger80** [comment]
@rco-odoo I was using an onchange method first before realizing that this was not thiggering when opening an existing record! So the domain is not aleays applied. At that moment I thought I could do that. And that type of code is used in the crm application to merge partner!

So what should I do? Both option has flaws.

**Comment by scosist** [comment]
Why was this closed? I have the same issue trying to apply a domain on a x2many field--onchange only takes effect after the field is changed--the domain however is not applied on the initial form view load. This is a problem. I've tested a module on v9.0 and v8.0 and I remember them behaving differently with onchange. In v8.0 the onchange was triggered on form view load **_and_** on a field change but in v9.0 it seems onchange is **_only_** triggered on a field change. @rco-odoo Is this a regression or is there another method for applying a domain on form view load?

@krueger80 have you found a workaround?

**Comment by krueger80** [comment]
@scosist it should work fine. They fixed #11343 and that fixed that one.

**Comment by scosist** [comment]
@krueger80 I haven't had a chance to test this in v9.0 recently so I can't say whether I would still experience the same behavior there but this is not working for me in master. Perhaps this fix has not yet been applied to master?

I had to resort to the workaround described by @pedrobaeza [here](https://www.odoo.com/fr_FR/groups/community-59/community-13935621) to resolve the behavior you described on [Mar 15](https://github.com/odoo/odoo/issues/11295#issuecomment-196810854).

My resulting compute method can be found [here](https://github.com/asphaltzipper/azi-odoo-modules/blob/master/sales_team_region/models/crm_team_region.py#L37).

**Comment by yk2kus** [comment]
having the same issue in V10 as well. onchange isn't the solution since it is not called always (i.e opening a form view where value of a field is already set)

**Comment by ovnicraft** [comment]
@rco-odoo its possible in next versions something like:
 `<field name="country_id" domain=[('id', 'in', eval([i.id for i in available_country_ids]))]/>`
IDK if write an onchange (just for domain) has impact in performance

BTW i am working fine with your suggestion.

**Comment by kpaipl** [comment]
Hey everyone, do you have any solution of this domain like
-------------------------------------------------------------------------------
@api.onchange('status')
    def _onchange_load_section(self):
        res = {}
        lst = []
        if self.status == False:
            self.section_id == False
        elif self.status != 'company':
            self.env.cr.execute("select id from rate_chart where states='other'")
            temp = self.env.cr.fetchall()
            if temp:
                for val in temp:
                    if val[0] not in lst:
                        lst.append(val[0])
        elif self.status == 'company':
            self.env.cr.execute("select id from rate_chart where states='company'")
            temp = self.env.cr.fetchall()
            if temp:
                for val in temp:
                    if val[0] not in lst:
                        lst.append(val[0])
        res['domain'] = ({'section_id': [('id', 'in', lst)]})
        return res

this code raise the warring like this
-------------------------------------------
WARNING test2 odoo.models: onchange method ResPartner._onchange_load_section returned a domain, this is deprecated
