### ISSUE TITLE
"Could not get content for /base/static/src/css/modules.css defined in bundle 'web.asset_backend'.

### ISSUE THREAD

**Issue by khaledhammad** [odoo/odoo#11313]
hello
after installing odoo 8 in ubuntu 14.04 using postgress database it gives me that error directly can some one help me to solve that problem :)

**Comment by atchuthan** [comment]
Install lessc compiler 
https://apps.openerp.com/apps/themes/8.0/theme_clean/#doc  (View Documentation page)

**Comment by sle-odoo** [comment]
Closing as the bug report is incomplete. Feel free to comment with more steps to reproduce your issue.
Regards
