### ISSUE TITLE
need user defined destination for database backup

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11315]
Using latest nightly 9.0.c as of today, Odoo database manager always wants to write backups to /tmp, only then, the browser's download dialog opens and allows me to change the directory.

This is a bad idea, since databases can become quite large (I imported some customer data and meetings and the DB is now ~17GB).
Also, on many systems (e.g. my default Debian 8.3 install), /tmp is not ment for files that large, and installers tend to leave more space for /home, so space is an issue.

In my case, I wondered why backups suddenly didn't work anymore, only to find out later that a hidden system error dialog showed that /tmp was full.

I'd prefer to first select the destination path, and Odoo backups my database right there.

**Comment by lukebranch** [comment]
@grexe ,

Have you seen this module?:

https://github.com/Yenthe666/auto_backup

I believe this community module may do what you need. There a PR here:

https://github.com/OCA/server-tools/pull/203

for submission of the module to the OCA/server-tools repo as well.

**Comment by odony** [comment]
Indeed, the database manager screen simply uses the `pg_dump` command to take a backup of the database, putting the file in the system's temporary directory, which is the correct temporary location.
However, this is intended as a very basic interface for taking backups, but definitely **not** meant for large production deployments. In fact, our deployment guide explicitly recommends to [block the whole database management interface](https://www.odoo.com/documentation/10.0/setup/deploy.html#security), as an important security measure.

For real production deployments you should schedule automated backups using `pg_dump` directly, and also take corresponding backups of the filestore directory where attachment files are stored (with filesystem backup tools such as rsnapshot)
