### ISSUE TITLE
[v9][POS] Tax are not set on account move lines correctly

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11319]
**Impacted versions:**

V9 on runbot : http://136630-9-0-41c94f.runbot9.odoo.com/web?debug=#id=120&view_type=form&model=account.move

**Steps to reproduce:**

1 - Create a product with tax :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13741393/4fbdd1c4-e9d6-11e5-8721-dcea5e68b469.jpeg)
2 - Sell it through the POS
3 - Validate your session

**Current behavior:**

Go to the account.move associated :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/13741409/74034730-e9d6-11e5-925b-38a8f8dfff7e.jpeg)
The lines have no tax set.

**Expected behavior:**

Same process as in invoices, all the lines must have the TAX

**Comment by flotho** [comment]
Hi @nim-odoo ,

I think we got another issue with taxes and POS here.
Do you confirm that it's a bug ?

**Comment by yuntux** [comment]
This issue seams to be a duplicate of this one : https://github.com/odoo/odoo/issues/10855

**Comment by flotho** [comment]
@yuntux , obviously it is a duplicate
