### ISSUE TITLE
account_report_id never shown on account report form

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#1132]
menu: account-setting-acount report - account report

see the last line with value = report value

account_report_id is in the notebook control, but 

``` xml
<notebook attrs="{'invisible': [('type','not in',['accounts','account_type'])]}">
```

so even user choose "account report" in the type field, this field(in the hidden notebook) will not shown.

**Comment by Yenthe666** [comment]
Hi @GoodERPJeff,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
