### ISSUE TITLE
Odoo8, onchange on o2m

### ISSUE THREAD

**Issue by Shephiroth** [odoo/odoo#11336]
Strange behaviour.

Impacted versions:
Im working on Odoo v8.20151103 (old, i know)
Steps to reproduce:
Create a custom module with a o2m -> account.move.line
Set an onchange on that field, that change the last line to sum the same (debit and credit) (This is an example, do whatever change you want)
And one more thing, remove the lines (5962-5964) from model.py, that prevent to result the changes to the form.

```
        if field_name and not isinstance(field_name, list) and \
                self._fields[field_name].type in ('one2many', 'many2many'):
            result['value'].pop(field_name, None)
```

Current behavior:
When the data is new (not write on db yet) it work correctly, the data updated in the ochange is correctly updated in the form, and the changes made by the user remains.
But, if you are editing existing data, the data updated by the onchange us updated, but the data changed by the user is lost

Just wondering, why is this happening?

**Comment by Yenthe666** [comment]
Hi @Shephiroth,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
