### ISSUE TITLE
Scaffold is neither unicode-aware nor 8-bit clean

### ISSUE THREAD

**Issue by atchuthan** [odoo/odoo#11331]
#### Impacted versions:
8.0, 9.0

#### Steps to reproduce:
Use a non-ascii character in a template, then try scaffolding with it.

For example, we tried to create [a template with a © character for OCA](https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L1-L3) (codepoint `U+00A9`, `0xC2A9` as UTF-8)

#### Current behavior:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 26: ordinal not in range(128)`

#### Expected behavior:
Create a new module with skeleton of scaffold, either pass raw bytes through directly or correctly decode the template before processing and re-encoding

**Comment by xmo-odoo** [comment]
Should be fixed by c824e50, currently in 8, will be in 9 next forward-port.

**Comment by atchuthan** [comment]
thanks for quick fix
