### ISSUE TITLE
[9.0] website_blog: next post bg image is overlapping footer on mobile

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#11337]
**Impacted versions:** 9.0

**Steps to reproduce:** Create blog post with backgroud image on title. Scroll down to next post section. Reduce width of a page to minimum or simply browse it on mobile device.

**Current behavior:** Next post background image is overlapping footer.

**Expected behavior:** Footer should be under next post section.

**Video/Screenshot link (optional):**
![blog_bug](https://cloud.githubusercontent.com/assets/5942291/13775914/e5087bf6-eaaf-11e5-897a-3740621e0bb9.png)

**Comment by lem8r** [comment]
Looks like bg image's property ```min-height``` is taken from next post's bg image property but it should be taken from parent div
see https://github.com/odoo/odoo/blob/9.0/addons/website_blog/views/website_blog_templates.xml#L231

**Comment by qsm-odoo** [comment]
Hello,
Sorry for the delay, I will try to fix this once I can. Know that this bug is already fixed in 10.0 though as blog covers have been entirely reviewed.

**Comment by JKE-be** [comment]
Seems fixed meanwhile.
![image](https://user-images.githubusercontent.com/4848797/35050338-dd439620-fba2-11e7-9018-caf78c81e847.png)

Could you confirm @lem8r ?

**Comment by lem8r** [comment]
@JKE-be yes, I do :+1:
