### ISSUE TITLE
word false on payroll slip. 

### ISSUE THREAD

**Issue by ozel1978** [odoo/odoo#11346]
Impacted versions:odoo version 9

Steps to reproduce:

Current behavior: 
1)when i generate payslip on odoo, it come out false word at each of salary amount.
i am not sure if i am configure currency with wrong way other config was not right. 
2)why it print twice for each of line. 

Picture below as a references.  

Expected behavior:

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/17262653/13803715/d932e3b6-eb81-11e5-8582-a38496cde1f6.png)

**Comment by mart-e** [comment]
Hello,

Thank you for the report. The problem is that you have removed the symbol of your currency (or added a new currency without symbol).
I have fixed the False issue at 1dbd0857430401464cab11c41b24bb44724dcf7f but ideally, I will make the symbol mandatory on a currency (for v10).
