### ISSUE TITLE
domain m2o to same model doesnt work

### ISSUE THREAD

**Issue by Shephiroth** [odoo/odoo#11348]
Impacted versions: odoo8.20151103

Steps to reproduce: 
Create a form with select = fields.Selection(selection=[('a',''), ('b','')])
Add a field m2o pointing to same model, with domain="[('select','!=','a')]"
If you edit your data with select=a, your m2o dont list the data. If you change the select to 'b', the m2o field still empty. If you save and edit again, now you can see data on m2o. If you change select to 'a' and check m2o, you can still see the data. If you save and edit again, now m2o works good. 

Current behavior:
Domain is calculated on data.read, but is not evaluated when the user change data. 

Expected behavior:
If the select field change, the m2o field should reevaluate and show/hide the data correctly

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Shephiroth,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
