### ISSUE TITLE
Sales: Entries are multiplied in the line dropdown product name

### ISSUE THREAD

**Issue by smogol** [odoo/odoo#11355]
Impacted versions: 8.0

Steps to reproduce: 
- import some products for two different languages ( by changing the admin language).
  the import csv file has the same generated external_id  for both files.
- ensure that the current user does not have the same language as the customer
- create a new quotation for this customer
- adding a product with more than one language. 

Current behavior:
You will see the product name twice ( presumed as many times as translations) in the proposed dropdown menu

Expected behavior:
The dropdown should only propose the unique reference for the language

Video/Screenshot link (optional):
![firefox_2016-03-16_13-32-00](https://cloud.githubusercontent.com/assets/2664534/13812285/983bb8ca-eb7b-11e5-97f9-e41bfaa2b79b.png)

**Comment by Yenthe666** [comment]
Hi @smogol ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
