### ISSUE TITLE
[16.0] Error message when using trigram index

### ISSUE THREAD

**Issue by tranngocson1996** [odoo/odoo#113589]
Impacted versions: 16.0

Steps to reproduce:
The trigram index creates a unique constraint index for the field. In the account.move model, the 'name' field has the 'index=trigram' option, so creating a record with a duplicate name will raise an error.

Current behavior:
When error messages are not user-friendly, users may not know how to fix the issue and may perceive it as a problem with the system.

Expected behavior:
User-friendly notification/message.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/26604325/221117324-3d5f2cdf-a6dc-4a5f-b8e3-abc38fd7e14b.png)

**Comment by tranngocson1996** [comment]
@HydrionBurst if you have time, can you notify this to the corresponding team. Thank

**Comment by HydrionBurst** [comment]
Hi, I don't know why you ping me, but I still do some researches 😃 
1. the `index='trigram'` only creates index `account_move_name_index` for `search` and won't create unique constraint
2. I cannot reproduce your problem. I can see the correct error popover. Could you check if the index `account_move_unique_name` in the `ir_model_constraint`? `SELECT * FROM ir_model_constraint WHERE name = 'account_move_unique_name'`. The ORM should use the name in the `ir_model_constraint` to translate PG error message to the Odoo error message.
3. It would be better to report your problem to our support team with a video or maybe @odoo/rd-accounting can help.

**Comment by tranngocson1996** [comment]
@HydrionBurst Sorry to bother you, but I noticed you were doing PR related to trigram index.
I found that constraint in the table 'ir_model_constraint', but I couldn't find the code that creates that constraint
![image](https://user-images.githubusercontent.com/26604325/221526590-56a4be05-42a8-4b1e-aa0e-9ab7f146e467.png)
When I searched in pgAdmin, I found that it was actually in an index instead of a constraint
![image](https://user-images.githubusercontent.com/26604325/221526910-2b42fe73-5ca5-4d5a-99ea-5a3c0a806a8a.png)
For me, it's really confusing and I guessed and researched that it's because of the trigram, but it seems to be wrong?
Once again, thank you so much for your enthusiasm 💯

**Comment by HydrionBurst** [comment]
Hi, 
Could you make a video to reproduce everything in a new database?
Odoo version: ??
Modules installed: ??
We need to know which action/actions trigger the problem.

BTW, I only touched the index for translated fields.

**Comment by tranngocson1996** [comment]
@HydrionBurst thank you, i may have given up by the time I inquired. I will add improvements to this constraint more friendly

**Comment by william-andre** [comment]
That constraint does indeed not have anything to do with the trigram index.
It is there because in most countries of the world, this is a legal requirement.

The error message should be nice already, here is a screenshot from Runbot
![image](https://user-images.githubusercontent.com/44770049/221542607-f78c791f-98a7-497f-aa3a-1b9201137291.png)

There error message is coming from here, because it matches the name of the SQL constraint set manually
https://github.com/odoo/odoo/blob/c04c05a3ea60cb2175289370523962db65516af9/addons/account_sequence/models/account_move.py#L9
https://github.com/odoo/odoo/blob/c04c05a3ea60cb2175289370523962db65516af9/addons/account_sequence/models/account_move.py#L48-L51

**Comment by tranngocson1996** [comment]
@william-andre thank.
