### ISSUE TITLE
[9.0C & 9.0E] can't adapt type 'account.tax' when creating a repair order with taxes and invoiceable lines

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11351]
Impacted versions:
9.0 community, 9.0 Enterprise

Steps to reproduce:
  - Open up a 9.0 Enterprise Runbot and go to Repairs.
  - Create a new repair order for the product iMac
  - Add an operation for the product iMac and add some taxes on this line, also check on the option "To invoice".
  The repair order should now look like this:
  ![image](https://cloud.githubusercontent.com/assets/6352350/13809772/98ad0f02-eb6c-11e5-9c6a-04203e5ce043.png)
 - Click on save.

Current behavior:
ProgrammingError: can't adapt type 'account.tax' dialog:
![image](https://cloud.githubusercontent.com/assets/6352350/13809723/5dd527b6-eb6c-11e5-84cb-98b77f4a41a3.png)
When you don't check on the option "To invoice" it will work fine.

Expected behavior:
The record is saved and both the taxes and the invoice state are saved without issues.

**Comment by Yenthe666** [comment]
Update: seems to be on both the default V9 and the V9 Enterprise.

**Comment by mart-e** [comment]
@Yenthe666 have you tested after the today fixes from @beledouxdenis ?

**Comment by Yenthe666** [comment]
@mart-e yep but this did not fix the issue. Tested on the latest runbot (V9 Enterprise). Result:
![image](https://cloud.githubusercontent.com/assets/6352350/13880937/ed52532e-ed1e-11e5-9454-419e31360827.png)

**Comment by mart-e** [comment]
@Yenthe666 no this is still with the code before Denis's fix (`tax_obj.compute_all(cr, uid, line.tax_id.ids,...` in `mrp_repair`, notice the `.ids`)
Rebuild in progress !

**Comment by Yenthe666** [comment]
Sorry I didn't even notice that. I will give it a new test tommorow or on monday and I'll let you know if it is fixed.

**Comment by Yenthe666** [comment]
@mart-e and @beledouxdenis it is fixed and is working fine now. :+1:
