### ISSUE TITLE
[9.0CE] website_blog: dash symbol is not shown

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#11353]
Impacted versions: 9.0 C/E

Steps to reproduce: 
install website_blog
create some blog posts
go to` _website.com_/blog/1` url to see posts overview

Current behavior:
dash is not renderred in some browsers.
screenshot made on https://www.odoo.com/blog/1 with chrome on win10 (same on android/chrome)
![blog-dash](https://cloud.githubusercontent.com/assets/5942291/13810190/26f3fa1e-eb77-11e5-95a1-cbd88c9567cd.png)

Expected behavior:
dash is renderred ok

FIX
https://github.com/odoo/odoo/blob/9.0/addons/website_blog/views/website_blog_templates.xml#L151
ATM long dash is drawn with unicode symbol &#5760; called Ogham space mark
apparently regular long or short dash (&mdash; or &ndash;) would be better choice

**Comment by JKE-be** [comment]
Fixed in odoo/odoo@a4d8cf9ead31a8e2160229672ae89ff7485fe753
thanks for the reporting
