### ISSUE TITLE
O365 calendar sync issue (error: AADSTS50011)

### ISSUE THREAD

**Issue by lightsabata** [odoo/odoo#113673]
![azure](https://user-images.githubusercontent.com/43295382/221230633-340b1e4e-e163-4839-b4a8-707276f269c1.jpg)
**Impacted versions:**
_ODOO 16.0 (Docker)_

**Steps to reproduce:**
_Set odoo behinde NGIX PROXY MANAGER with SSL
Start ODOO with `--proxy-mode`
folowing [the odoo steps](https://www.odoo.com/documentation/16.0/applications/general/calendars/outlook/outlook_calendar.html) to enable outlook calendar sync
Set outlook client ID and secret ID from AZURE AD in settings_

**Current behavior:**
_When trying to sync calendar, microsoft auth encounter an issue (AADSTS50011):_

_" 'http://xxxxxxx/microsoft_account/authentication' specified in the request does not match the redirect URIs configured for the application 'xxxxxxx'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. "_

The URL set in the AZURE AD app is in HTTPS and ODOO seems to give an HTTP one
is anyone know why ?

**Thanks**

**Comment by lightsabata** [comment]
i have maaged to sove the issue by change the website key in database

**Comment by nassoor** [comment]
@lightsabata can you please clarify what you mean by "website key in database"? did you mean "web.base.url"? If so, I tried changing it and that had no effect.

**Comment by lightsabata** [comment]
Did you enable developper mode as a superuser ?

**Comment by lightsabata** [comment]
Do you use https protocol on you website ? And does microsoft prompt show the same website entry ?

**Comment by nassoor** [comment]
Yes I used https on the website, but the microsoft prompt and button shows http not https.

If I modify the url to be https then I can login fine.

**Comment by lightsabata** [comment]
So you modify the key web.base.url  with https on your database entry and it still prompt you an http adress on microsoft login ?

**Comment by lightsabata** [comment]
Could you verify on azure side that you’ve type an https adress ?
It work without any problems on few odoo instances that i have, so it might be a mistyping issue, you should doublecheck everywere that you type ssl adresses

**Comment by nassoor** [comment]
I checked.

It looks like I am dealing with another part of odoo. I am trying to login with Azure AD not sync calenders.
