### ISSUE TITLE
[8.0] Employee Public Field

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#1136]
The team page doesn't appear on website unless at least one employee is set to public.

When creating a new blank database, there's no field in the backend nor the front end to set an employee public, thus the Team Page remains invisible.

Had to edit the database directly to make the administrator account public, Only then, the Team Page was displayed.

**Comment by Yenthe666** [comment]
Hi @mrawi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
