### ISSUE TITLE
Error: Odoo XMLRPC cannot marshal <class 'decimal.Decimal'> objects

### ISSUE THREAD

**Issue by mhashirhassan22** [odoo/odoo#113638]
Impacted versions: 15

Steps to reproduce: call odoo xmlrpc API in python environment (django) and pass price value as Decimal object

Current behavior: gives error: cannot marshal <class 'decimal.Decimal'> objects

Expected behavior: It should support decimal values similar to float, str

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
XMLRPC is basically deprecated. Just use JsonRPC. But Odoo doesn't use decimal objects anyway.

**Comment by mhashirhassan22** [comment]
yet there seems to be no proper (official) documentation for JsonRPC
