### ISSUE TITLE
[9.0C & 9.0E] Unable to use serial numbers on transfers

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11360]
Impacted versions:
9.0 Community and 9.0 Enterprise

Steps to reproduce:
Follow the guide at https://www.odoo.com/documentation/user/9.0//inventory/management/lots_serial_numbers/serial_numbers.html on a new Runbot.
 - In the Inventory application, go to Configuration ‣ Settings, select Track lots or serial numbers:
![image](https://cloud.githubusercontent.com/assets/6352350/13813771/a2df74c6-eb83-11e5-8d34-2aa07a6184fc.png)

 - Create a new product and check on "By unique serial number" under the inventory tab:
![image](https://cloud.githubusercontent.com/assets/6352350/13813815/c7413d90-eb83-11e5-8f37-93c03c22d007.png)

 - Create a new transfer for your just created project:
![image](https://cloud.githubusercontent.com/assets/6352350/13813837/e5f4584e-eb83-11e5-975b-dc271769c272.png)

Current behavior:
There is no field / ability to specify the serial number, while this is available (and explained) in the documentation?

Expected behavior:
A field becomes available to specify the serial number of the product:
![image](https://cloud.githubusercontent.com/assets/6352350/13813870/0ca42f14-eb84-11e5-938c-d68ed30ca7ca.png)

**Comment by jni-odoo** [comment]
In the incoming shipment just click on the button "Mark as TO DO" , 
field for the serial number will come :)

Thanks,

Nikunj Jani (Odoo India)

**Comment by Yenthe666** [comment]
@jni-odoo thanks for letting me know, this wasn't mentioned in the documentation.
@mart-e I've expanded the documentation (see https://github.com/odoo/documentation-user/pull/150) could you add this in please? This took me 2 hours.
