### ISSUE TITLE
[16.0-CE/EE] Calendar view -> Undefined with the Selection Field

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#113698]
Impacted versions: 16.0 CE - can check on runbot

Steps to reproduce: 
1. Go to the menu Sales -> Order -> Quotation -> Open Calendar view

Current behavior:

Status shows Undefined

Expected behavior:

Show the name label of the Selection field 
Ex: Quotation/Sale Order/Lock/ Cancel

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7898318/221369170-6595293c-37aa-4b9f-8204-6765bfe4650b.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
fixed by:  https://github.com/odoo/odoo/commit/edf838d791ee02f41af2bff32dc20b5657ef0d81

**Comment by anhvu-sg** [comment]
that's great, thanks @niyasraphy

**Comment by niyasraphy** [comment]
as it is resolved please close the ticket @anhvu-sg

**Comment by vava-odoo** [comment]
Thanks @anhvu-sg  for reporting and thank you very much @niyasraphy for the fix!
