### ISSUE TITLE
Odoo as a platform for Videos

### ISSUE THREAD

**Issue by Maralai** [odoo/odoo#113695]
Impacted versions: 16.0

Steps to reproduce:

If I have a file stored in Odoo Documents or web/content, why can I not add the video URL to products? 

Current behavior:

Review `addons/web_editor/tools.py` After tracing the behavior from the interface to the code; there is no support for Odoo hosting of videos. Only some platforms are supported despite having a video player in Documents that works with mp4 files. 

Expected behavior:

Native video hosting would be supported.

Supporting information:
https://www.odoo.com/forum/help-1/how-to-upload-video-s-into-odoo-website-200512

**Comment by JKE-be** [comment]
Thanks for feedback
We have some tasks related to it, but it is not a priority.
We keep it in mind in our todo list, no warranty for v17.
