### ISSUE TITLE
[8.0] Website event sale : Can not change the payment method after a rejected payment

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#11364]
# Impacted versions:

8.0
# Steps to reproduce:

The ogone payment method must be configured on Settings/Payments/Payment Acquirers.

https://youtu.be/TejbGmc4Cqk
# Current behavior:

Impossible to click on Pay now button after a rejected paiement
# Expected behavior:

It should be possible to select another payment method and a click on Pay Now
# Video/Screenshot link (optional):

https://youtu.be/TejbGmc4Cqk

**Comment by adrienpeiffer** [comment]
OPW 672191

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
