### ISSUE TITLE
[9.0] When holding the left mouse button on the x2many drop down item, change item and release, it doesn't work

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#11372]
#### Impacted versions:

[9.0]
#### Steps to reproduce:

1) Click on any x2many field with selected value A
2) Mouse Down on a different item B
3) Mouse Up on another item C
#### Current behavior:

The value A remains in the field.
#### Expected behavior:

The value C should be selected.

Really not a big deal... but that would just just be better imo.

**Comment by pedrobaeza** [comment]
The widgets are not programmed to work the way you intend, with MouseDown and MouseUp events, so you have to get used to the expected behavior. Closing this.
