### ISSUE TITLE
[16.0]Sale order's invoice quantity incorrect(imprecise) due to decimal accuracy

### ISSUE THREAD

**Issue by evanomnisoft** [odoo/odoo#113714]
Impacted versions:

What are the steps to reproduce your issue?
Set decimal accuracy for quantity to 3
make a sale order with quantity of 3 decimal (eg.4.446)
Confirm SO
Create invoice
Go back to Sale Order
BUG: Invoiced quantity is only in 2 decimal. This leads to an issue where the SO can never be in "Fully Invoiced" state.

What is the current behavior that you observe?
Invoiced quantity is only in 2 decimal. This leads to an issue where the SO can never be in "Fully Invoiced" state.

What would be your expected behavior in this case?
Invoiced quantity has same precision as product uom qty

Video/Screenshot link (optional):
https://drive.google.com/file/d/1OdmdSa1G0hYzS06_-oFwUiUzbgx8YCX9/view?usp=share_link

Support ticket number submitted via odoo.com/help (optional):
3207821

**Comment by gdgellatly** [comment]
No that isn't quite right. I am very sure I have seen this before. The issue is nothing to do with decimal accuracy, and indeed the invoice and sale have the same decimal accuracy. The issue is sale allows you to have a qty which is beyond the specific UOM rounding, so when you change decimal accuracy you also need to check all your UOM rounding settings. Otherwise when you create the invoice, it is rounded to your UoM rounding.

**Comment by evanomnisoft** [comment]
The reason why the sale order line lets me have that precision is because i set decimal accuracy to 3. The fact that this also changes the number of decimals on the invoiced quantity leads me to think that the bug lies in the compute. Looking at the video provided, the invoiced quantity in the invoice is correct (4.446) while the value back in the sale order is incorrect(4.450).

**Comment by gdgellatly** [comment]
I've spent days inside this code. It is worse in automated invoicing as you can get 1000's of invoices for a sale in a few minutes. It will be the UoM settings, guarantee. Decimal accuracy has never been the primary cause, it is only when you set it higher than the UoM settings and then enter something outside the UoM rounding.
