### ISSUE TITLE
onchange manager lost track of self.env.dirty flag

### ISSUE THREAD

**Issue by Shephiroth** [odoo/odoo#11375]
Impacted versions: odoo 8.20151103

Steps to reproduce:
go to openerp/models.py:5891

```
        with env.do_in_onchange():
            record = self.new(values)
            values = dict(record._cache)
            # attach ``self`` with a different context (for cache consistency)
            record._origin = self.with_context(__onchange=True)
```

Current behavior:
As we can see in the code, a new record is created with the new values,  where the system evaluates wich fields are updated. But on the last line, when we set record._origin, a new env is created, and we lost track of record.env.dirty flags.

Expected behavior:
When a new env is created, dirty flag should stay, or at least give an option to keep it (could be a flag, record._origin = self.with_context(keep_dirty=True))

**Comment by Shephiroth** [comment]
After some coding, i have realized that env.do_in_onchange() clear the dirty flag some times. I have the code working now, but its a dirty trick....copy the flag, and update the dirty flag later on when needed. Not sure if its the correct way to do it.

**Comment by Yenthe666** [comment]
Hi @Shephiroth,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
