### ISSUE TITLE
[website_slides] Replies from subscribers get to all subscribers

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#11376]
Impacted versions: 9.0

Steps to reproduce:
1. Install website_slides.
2. Log out.
3. Go to presentations.
4. Subscribe with 2 personal emails (let's say a@example.com and b@example.com).
5. Log in.
6. Go to presentations.
7. Publish a new presentation.
8. Go to your mail client for a@example.com. You have a notification of a new presentation.
9. Answer to that notification.
10. Go to your mail client for b@example.com.

Current behavior:

You find 2 mails: the new presentation notification (good), and a@example.com's answer (bad).

Expected behavior:

Replies from followers create a lead, not a message in the thread that gets delivered to all followers.

@Tecnativa

**Comment by Yajo** [comment]
FTR, [OCA's mailing list discussion](https://odoo-community.org/groups/contributors-15/contributors-38033?mode=thread&date_begin=&date_end=).

**Comment by rafaelbn** [comment]
:+1: 
Please @odony this is a Comercial Security Bug that you must at least read about it. Thanks
cc @pedrobaeza @antespi @sergioteruel @carlosdauden

**Comment by rafaelbn** [comment]
:+1: 
Please @odony this is a Comercial Security Privacy Bug that you must at least read about it. Thanks
cc @pedrobaeza @antespi @sergioteruel @carlosdauden

**Comment by Yajo** [comment]
Another problem implied in current design is that if there are subscribers with several languages, subscribers will get the email in the publisher's language (when you merge https://github.com/odoo/odoo/pull/15017, of course).

**Comment by pedrobaeza** [comment]
@mart-e, should we at least propose a solution for master?

**Comment by rafaelbn** [comment]
Hi, is there any kind of solution for this privacy problem? IMHO this is critical and lots of Odoo community user has report it in many threads of Odoo distributions lists.... any opinion @mart-e ? Thanks

@Tecnativa

**Comment by pedrobaeza** [comment]
@Yenthe666 I'm reviewing old PRs and this is still applying. Who would check this?

**Comment by Yenthe666** [comment]
Hmm, the best fit is @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello,

>Expected behavior:
>Replies from followers create a lead, not a message in the thread that gets delivered to all followers.

Whut ? I bet there is some configuration that I miss. I don't understand why it should create a lead. Is it linked to aliases and/or default values for fetchmail ?

**Comment by Yajo** [comment]
Well, that's just one thing that I'd expect. Maybe it's better that there is another. What I'd **never** expect is that anybody can notify anybody in that subscription list.

I mean: If I randomly browse your site and subscribe to [any of your slide channels](https://www.odoo.com/slides), I'd expect to get notifications when a new document is published, but _I wouldn't expect to receive email answers from other random subscribers_. Spammers love these things.

**Comment by tde-banana-odoo** [comment]
There is some code that tries to do that. Maybe it is not working correctly as it seems quite strange. See commit https://github.com/odoo/odoo/commit/f83e7067868870aa1f1779b35768ac38b6468983 . I don't remember doing it (I am becoming old), but maybe I did it wrong (bad parent_id for example).

**Comment by tde-banana-odoo** [comment]
Surprise: this commit has been done in 10, not 9. As your report targets 9, maybe it is related to that fix not present in 9 .

**Comment by Yenthe666** [comment]
You can do this @tde-banana-odoo! Backports for the win! 😉

**Comment by pedrobaeza** [comment]
Well, it's good that this is already patched in v10, and we have most of our DBs now in that version, but if it's easy to backport to v9, a lot of people can benefit from this also.

**Comment by pedrobaeza** [comment]
Closing as the fix is in v10.
