### ISSUE TITLE
[16.0][CRITICAL][TRACEBACK] Error when reload "Forecasted Report"

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#113707]
Impacted versions:  16.0

Steps to reproduce:
- Open any storable Product having forecasted stock
- Click on 'Forecasted' smart button.
- Change the Warehouse from Filter. and Reload the page.(browser)

Current behavior:
- Traceback
Expected behavior:
- Should show Warehouse specific result.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/36708909/221437272-73eab252-3be1-40fd-9a5c-825dfe374d82.png)

[2023-02-26T21-04-42D0-47.webm](https://user-images.githubusercontent.com/36708909/221437255-f8cb58ab-c3d3-4953-9d90-2cbc6d613871.webm)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @dipak-shah ,
it seems it has been resolved and couldn't reproduce now.
can you confirm and if it is not happening again, please close the ticket.
thanks
