### ISSUE TITLE
Tax partner_id cannot simply be assumed to be invoice's partner_id. Read on...

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#11386]
Impacted versions:
v9 - stable (maybe master)

Steps to reproduce:
Variant A:
- Create a tax which has a counterparty (a counterparty is hereby understood as a reversive tax which neutralizes completely the actual tax item, but pushes it's value on a different account). This is often used for taxes due on invoices, which are not passed onto the customer, but have to be entirely assumed by the company. This not necessarily need to be a "tax" but can rather be a "levy" as well. Make sure that the counterparty is charged on a non-payable, non-receivable account, while the causing tax is charged on a payable/receivable account dedicated to a fictive tax authority (not the customer)

Variant B:
- Create a tax of character withholding, which is due not to the partner, but to a third party (e.g. a tax authority). The due amount of the withholding is on a receivable/payable account with that tax authority

Current behavior:
- The Amount Due will include this item as payable to the customer
- The reconcile logic will include this item for reconciliation and fail, because, if constructed as above, two or more different accounts are involved which brakes a recon-validation.

Extra comments:
- There might be the suggestion not to make the accounts associated with the tax authority receivable/payable yet maintaining them reconcilable. I cannot judge right now on the implications, yet it might have unexpected implications on some reports, such as partner balance which might rely on the receivable/payable bit. Furthermore, judging on their nature, those are receivable/payable accounts.

Expected behavior:
- Amount due and reconciliation only take into account payments due to the actual partner. Therefore introduce a tax partner which can be defined on taxes or tax groups. This tax partner resides on the partner_id of the move line and as a positive side effect helps at the moment of tax payment reconciliation (you know what I mean here, right?). Amount Due (residual) and invoice reconciliation would be made partner aware to exclude tax items which are defined in this way.

Video/Screenshot link (optional):

n/a

@kurkop

Pull Request to follow... @qdp-odoo  Would you accept to discuss on such?

**Comment by qdp-odoo** [comment]
I don't get the use case, sorry buddy... 

Would you mind sharing a screencast?

**Comment by blaggacao** [comment]
Side Note: The extra field amount due is ours. It's important to have withholdings separated fromt the invoice total, because invoice total represents exactly this: the total value of the transaction. So we made this a two-step calculus.

Does this help?

**Still Good**
<img width="656" alt="stillgood" src="https://cloud.githubusercontent.com/assets/7548295/13853813/8b723b62-ec36-11e5-9375-2b8681a8279c.PNG">

**Now Bad**
<img width="662" alt="nowbad" src="https://cloud.githubusercontent.com/assets/7548295/13853827/9ba2d6ae-ec36-11e5-809d-f362bacc3a11.PNG">

**Comment by blaggacao** [comment]
The "bad" line:
https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L89
But a tax partner is missing to differentiate, we'll push a PR to make this clear tonight.

**Comment by pedrobaeza** [comment]
Closing as there are several PRs/commits
