### ISSUE TITLE
base_import: one2many import is not working

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#113869]
Impacted versions: 16.1 and above

Steps to reproduce:
Try importing a purchase with order lines with product, quantity and unit price using Favorites -> import records

Current behavior:
couldn't successfully import

![Screenshot from 2023-02-28 16-35-05](https://user-images.githubusercontent.com/27989791/221869629-c6e43c32-ab94-40d9-aa13-c5cbe18afb77.png)

Expected behavior: import without any issues

cc: @Iucapad  may be after this refactoring: https://github.com/odoo/odoo/pull/106265

**Comment by Iucapad** [comment]
Hello, thanks for your comment. We are aware of this bug with relational fields, and @BastienFafchamps is working on a fix that should be merged soon -> https://github.com/odoo/odoo/pull/113674

**Comment by niyasraphy** [comment]
thanks for the update @lucapad
