### ISSUE TITLE
[9.0C & 9.0E] Contact onchange is ignored when creating new project issue

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11395]
Impacted versions:
9.0 Community & 9.0 Enterprise

Steps to reproduce:
 - Open up a V9 Enteprise Runbot
 - Go to projects and open up the issues for the project 'Data Import/Export Plugin'
 - Click on 'Create' to create a new issue. You will see the following form:
![image](https://cloud.githubusercontent.com/assets/6352350/13873556/8f826fbc-ecf2-11e5-95aa-e5cd7965b976.png)
  Notice how the Contact is filled in with the name 'Delta PC' and that no e-mail is filled in. When you open up this contact its form you will see he has an e-mail filled in:
![image](https://cloud.githubusercontent.com/assets/6352350/13873580/afd81f0a-ecf2-11e5-960f-91e14a999578.png)
 - Remove the contact on the issue, click somewhere else and now fill in the contact again. The moment you add the contact again the onchange function goes off and the e-mail is filled in automatically:
![image](https://cloud.githubusercontent.com/assets/6352350/13873605/d0884068-ecf2-11e5-8892-5fcd0fc692b2.png)

Current behavior:
When clicking on 'Create' for creating a new issue on a project the customer its e-mail is not automatically filled in because the onchange does not seem to have an effect on the record.

Expected behavior:
When click on 'Create' for creating a new issue on a project the customer his e-mail is filled in automatically (provided there is one).

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/1d0b9da3f0cc5a639b4997d19f31d8abf765db0c
(will be ported to 9.0 soon)
