### ISSUE TITLE
[9.0C & 9.0E] Opening project issues randomly opens project tasks view

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11396]
Impacted versions:
9.0 Community & 9.0 Enterprise

Steps to reproduce:
 - Open up a V9 runbot
 - Go to projects and click on the issues item, for example for the project 'Research & Development':
  ![image](https://cloud.githubusercontent.com/assets/6352350/13873686/65f2c31c-ecf3-11e5-917a-38df2832bd00.png)
 - The project tasks view is opened in place of the project issues. (notice that this only happens every once in a while, about once in five attempts) Example:
![image](https://cloud.githubusercontent.com/assets/6352350/13873789/14798b64-ecf4-11e5-9b77-f2ad5d3a8adc.png)

Current behavior:
Every once in a while (about one out of five attempts) after clicking on the issues button it will open up the project tasks, not the issues.

Expected behavior:
When you click on the issues the view with all issues opens, not the view for all tasks.

**Comment by zeliklil** [comment]
I found the pattern.

If click on the text `3 Bugs` you open the issues.
If you click outside the text (but still inside the box) you open the project. It's like clicking on the main box.

**Comment by Yenthe666** [comment]
@zeliklil good catch, you're correct!
