### ISSUE TITLE
Company registry field is too short

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#11390]
Impacted versions: All

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

The field company_registry in model res.company is too short. At present is 64 characters long and at least 128 are needed to fit the registers of many companies. As an example Spanish companies' registers are about 120 characters long.

**Comment by Yenthe666** [comment]
Hi @jalzaga,

Thanks for the report.
This is already fixed in V10 and up atleast:
https://github.com/odoo/odoo/blob/ef8cd11a6be25cbb5288e8ab88b4aafa2fa0119c/odoo/addons/base/res/res_company.py#L166

Regards,
Yenthe
