### ISSUE TITLE
[8.0]Multi company, Access Denied Document type: Partner, Operation: read

### ISSUE THREAD

**Issue by miihir9898** [odoo/odoo#1139]
## Steps to produce.

login with admin
install sale,account

create two company [companyA] and [companyB] under main company .

create [usera for comapanya] with all managerial rights and [userb for companyb] hr officer right.
Here both users's Allowed Companies = companyA, companyB.

login via userb and create new employee empb.

login via usera and try to create new [customer invoice]/SO for employee empb. Getting access error, even usera is manager?

Access Denied
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: Partner, Operation: read)

It should not happen here, "OpenERPhave somethings wrong configuration with access rights."

Thanks.
Mihir

**Comment by Yenthe666** [comment]
Hi @miihir9898,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
