### ISSUE TITLE
[BUG] [16.0] [sale_loyalty] reward lines amount was not deducted during the computation of getting the loyalty point from the current order

### ISSUE THREAD

**Issue by yash3051** [odoo/odoo#114004]
Impacted versions: 16.0

Steps to reproduce:
1). Add any product to the sale order
2). claim the reward(which is loyalty type)
3). Confirm the sale order
4). Check the loyalty point for that customer

Current behavior: calculate the wrong loyalty points because not deducted the rewards lines amount from the total amount in the sale order

Expected behavior: claimed reward line amount must be deducted from the computing the getting loyalty points from the current order.

Video/Screenshot link (optional):
![screenshot-localhost_8016-2023 03 01-17_28_56](https://user-images.githubusercontent.com/91586195/222136501-6178ac32-75cd-45be-bebf-3c826156a7d4.png)

![2](https://user-images.githubusercontent.com/91586195/222136557-1ff823cc-6c4d-4be2-88d3-0b3b1dbf8ba3.png)

![3](https://user-images.githubusercontent.com/91586195/222136581-6f60551a-91cc-4caa-97ef-0840004d9963.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by dalaOdoo** [comment]
@yash3051 it is not a bug, we made the choice to grant points before the claim. 
If you do a purchase of $100 with a program that grants you 6 points per $, you will receive 600 points. 
If you use points to get a free product, you will still receive the same number of points and we will remove the points used for the free product. 
We decided to the the same logic for any type of reward. Using point to get a reduction will not reduce the number of granted points
