### ISSUE TITLE
unit test broken due to tag_selector.py

### ISSUE THREAD

**Issue by Rojodev69** [odoo/odoo#114015]
Impacted versions:
Odoo 16.0
Steps to reproduce:
launch unit test after commit : 5aff8cf22ab0cbac7a9a3cebf39860f55617f79e

see file: https://github.com/odoo/odoo/blob/16.0/odoo/tests/tag_selector.py
line 54: test_module = test.test_module
and error on unit test: AttributeError: 'CLASS_HERE' object has no attribute 'test_module'

 @Xavier-Do

**Comment by niyasraphy** [comment]
Fixed: https://github.com/odoo/odoo/commit/85ca6961cf7795d98abf6d1ae655e123b0e073e9

**Comment by Xavier-Do** [comment]
#114027 was erged in 16.0 to fix this issue in stable

For future version you will need to inherit from BaseCase to ensure everything works as expected
