### ISSUE TITLE
[9.0] Cron Run Manually

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#11402]
**Impacted versions:**
9.0

**Steps to reproduce:**
1) Go to any cron job at Settings -> Technical -> Automation -> Scheduled Actions
2) Click on the "Run Manually"

**Current behavior:**
The following error is thrown:

```
  File "/odoo/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/odoo/openerp/models.py", line 4741, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/odoo/openerp/models.py", line 3536, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/odoo/openerp/addons/base/ir/ir_model.py", line 810, in check
    , (model_name, uid,)

ProgrammingError: can't adapt type 'res.users'
```

**Expected behavior:**
There shouldn't be an error.

**Proposed solution:**
The following [commit](https://github.com/odoo/odoo/commit/b78a64a2ccd91e15cb67b9c3fafb3c4efc8a9e8) changed `uid` to `cron_obj.user_id` where `uid` is an integer and `cron_obj.user_id` is a record. So from the get go the user's ID is not sent through but rather the whole record. The commit should've been `cron_obj.user_id.id`.

**Comment by Yenthe666** [comment]
@adekock11 I just tested on the latest runbot and I don't get this, perhaps you have an older code base for your Odoo?

**Comment by adekock11** [comment]
@Yenthe666 the commit which breaks the cron job is only two days old and I tested on latest code. The error is thrown in the logs and not in the interface, so unless you have access to Runbot's running logs, you won't see the error.

In either case, do take a look at the commit I am referring to. It is quite obvious that the commit was incorrect, since `uid` was an integer and `cron_obj.user_id` is a record set.

**Comment by adekock11** [comment]
I see a commit to fix this, was just created: b6847a0537b892d521264c672388241acfe86237

**Comment by Yenthe666** [comment]
@adekock11 I see, I wasn't looking to far there. Looks like an error.

**Comment by tivisse** [comment]
Hello, 

Fixed at https://github.com/odoo/odoo/commit/b6847a0537b892d521264c672388241acfe86237

Thank you for the feedback.

**Comment by adekock11** [comment]
@Yenthe666 :)
@tivisse Thanks
