### ISSUE TITLE
Buggy Odoo 9.0 CE, Access Rights Issues HRMS

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#11401]
Impacted versions:
9.0

Steps to reproduce:
Install hr, recruitment modules.
modify security for officer group, only allow to create,read to applicant model.
then login via officer grouped, user.
then try to create applicant, it not allow todo so, security issue raise.

Current behavior:
Not working, security bugs of odoo

Expected behavior:
If create, read permission their, it should, allow to create new applicant.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as @tejastank has been blocked from the Odoo repository and as I was no longer able to reproduce this bug report.
An official response can be found on the thread https://github.com/odoo/odoo/issues/7466#issuecomment-378920731, to quote @mart-e:

> Due to the repeated aggressive tone (#16056 (comment), #8514 (comment), #1880 (comment), #7019 (comment), #7085 (comment)...) with the one that are trying to help you or just failing to give useful information to a point beyond bad faith (#10931 (comment), #3443 (comment), #4544 (comment),...), @tejastank is now blocked on the Odoo repository.
I was hoping we could manage a solution but, after almost 4 years, it seems sadly that we can not discuss constructively with him.
