### ISSUE TITLE
[16.0] Responsiveness missing [Notebook-pages(tabs)] messing up the view/UI, 

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#114101]
Impacted versions: [16.0]

Steps to reproduce:
- Add multiple pages(tabs) (technically 'Notebook' -> 'Pages') in the form view. 
- Here in the attached video I added those dummy pages just to reproduce the issue easily. you can also do the same in order to reproduce this unless you have some other way.

Current behavior:
- When adding more pages that crossed the page or form's sheet it's messing up and doesn't respect that UI.

Expected behavior:
- Same as the earlier version it should go to the next line, which means more pages(Tabs) you add will start from the 2nd row/line.

Video/Screenshot link (optional):

[5032daa7-dc16-4af3-92a7-17f261138272.webm](https://user-images.githubusercontent.com/36708909/222251702-1f003cdf-522c-4423-bb30-7bfb6c25fc00.webm)

![image](https://user-images.githubusercontent.com/36708909/222251830-360ae6e8-6565-4e4a-b59c-ecad701b38f9.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
thanks for the bug report, seems it is already reported in:  https://github.com/odoo/odoo/issues/108406

**Comment by dipak-shah** [comment]
> thanks for the bug report, seems it is already reported in #108406

@niyasraphy Appreciated your response here. when this is going to fix? as **#108406** posted from DEC 21. It's been almost 2+ Months.  Thank you!

**Comment by niyasraphy** [comment]
Fixed in:  https://github.com/odoo/odoo/commit/19c03accdb5754a6c223bce8ce2cc142e9b2be08
