### ISSUE TITLE
define custom_widgets can't work

### ISSUE THREAD

**Issue by wwwsec** [odoo/odoo#11415]
help !
https://www.odoo.com/documentation/9.0/howtos/web.html 
The Form View Custom Widgets

`instance.web.form.custom_widgets.add('multiplication', 'instance.oepetstore.WidgetMultiplication');`
does'nt work
and the value of "instance.web.form.custom_widgets“ is undefine

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.
