### ISSUE TITLE
RFE: enduser configuration for default calendar/CRM meetings view

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11416]
I really think Odoo needs a simple way for end users to configure the default view (including columns to show) for modules, in this concrete case, the calendar.

It cannot be a solution to require technical knowledge of Odoo's internal structure and manipulate XML files by hand for such a simple and common usecase, like in:
https://www.odoo.com/de_DE/forum/hilfe-1/question/how-to-show-week-by-default-in-a-calendar-view-75211

In my case, I want to go from contact to a custom meetings view by clicking on "meetings", e.g. switch to listview and don't show unneeded or even inappropriate columns like "stock location" (?!), but always show the meeting description.

This is particularly striking if you have many past meetings with a contact and the default view is always empty because it only shows you the current week...

Using Odoo 9.0c.20160319 on Debian Linux 8.3 testing (stretch) with PostgreSQL 9.5.

**Comment by JKE-be** [comment]
@grexe 

> It cannot be a solution to require technical knowledge of Odoo's internal structure and manipulate XML

- It is the standard way to customize view... using the inheritance of xml view: 
https://www.odoo.com/documentation/8.0/reference/views.html
- For v10, we are working on a UI to update view... but it is a new feature... 

>Don't show unneeded ... but always show the meeting description.

- So you can just create a inherited view which remove unneeded fields, and add new fields...
- https://www.odoo.com/documentation/8.0/reference/views.html#inheritance

>This is particularly striking if you have many past meetings with a contact and the default view is always empty because it only shows you the current week...

- Take a look on this response: https://www.odoo.com/forum/hilfe-1/question/how-to-show-week-by-default-in-a-calendar-view-75211#answer_87488
