### ISSUE TITLE
[9.0c/e] HR Salary Rule python with result_rate = 0 ALWAYS means rate = 100.0

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#11420]
Impacted versions:
9.0c and 9.0e

Steps to reproduce:
Create a salary rule, with python rate.

```
result_rate = 0
result = 333
```

Current behavior:
After computing the sheet, the payslip line will have {'total': 333, 'rate': 100.0, 'amount': 333.0}

Expected behavior:
{'total': 0.0, 'rate': 0.0, 'amount': 333.0}

Video/Screenshot link (optional):
n/a

I realized this while converting my US localization to use rates and amounts to be prettier in some circumstances. (thank you unit tests)

**Comment by Khwunchai** [comment]
Just to be sure, do you mean setting Amount Type to percentage (%) in salary rule?

**Comment by jaredkipe** [comment]
No I'm speaking of python calcuations.  Amount Type = Python Code

**Comment by pedrobaeza** [comment]
Is this still happening in latest code version?

**Comment by jaredkipe** [comment]
@pedrobaeza Yes, or at least on 11.0

**Comment by pedrobaeza** [comment]
Do you have possible code fixing this?

**Comment by Yenthe666** [comment]
Hi @jaredkipe,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
