### ISSUE TITLE
leads,opportunity,issue cann't inherit all  To and Cc list from incoming email.

### ISSUE THREAD

**Issue by fausthuang** [odoo/odoo#11436]
Impacted versions:
Odoo V9 enterprise
Steps to reproduce:
if the customer(A) send a email to Odoo user(B) and also to/cc another person(C)-not Odoo user.
when Odoo receive it as a leads or opportunity,issue. that only show the sender(A) in follower, if A already register in Odoo.
but there is no information about another person(C), no matter C was register in Odoo or not.
if that, when Odoo user(B) reply this leads or opportunity,issue in Odoo,  C will not receive the reply
message and missing in this loop. because the Odoo user(B) have not any information about C.
Current behavior:
will missing all related person in mail list add by customer except the sender.
Expected behavior:
if the mail loop have other receiver(s):C(maybe 2 or above ),no matter in original mail or cut in later.
1.) If C is a new custact who not register in Odoo, system should show the email address about C. 
    so Odoo user can create it as the new contact and add to follower.
2.)if C is an exsiting contact, Odoo should add it to follower automatically accroding to the email address(maybe duplicate,user will remove unnecessary from follower list)
Video/Screenshot link (optional):

**Comment by goranskular** [comment]
Is there any progress on that issue? It is really mandatory to have information on all emails included in email thread.

**Comment by pedrobaeza** [comment]
This is the expected behavior when you don't have any res.partner record with that email for matching them. If you don't like this behavior, you can make a custom module for storing or auto-creating partners that fills this gap.
