### ISSUE TITLE
RFE: UI configuration for listview columns

### ISSUE THREAD

**Issue by grexe** [odoo/odoo#11434]
relates to #11416 but is a separate RFE

I'm really surprised that Odoo 9 (tried with latest nightly) doesn't offer a way to configure which columns should be shown in listview mode (and in which order), across all modules I looked at (contacts, calendar, iirc transactions).

This is one of the basic features of tables/listviews and really useful for many reasons, including culture/localisation, different fields needed depending on business/area/user level.

There is even a [commercially developed](http://openies.com/portfolio/odoo-dymamic-list/) module for this, so I wonder if there's a way to integrate the work into the main branch of Odoo, because this feature should really be commonly available for all users, as it's not a specialised need, and the web UI would benefit greatly from it.

**Comment by Yenthe666** [comment]
@grexe your link gives me a 404, can you fix it? You made me curious about what exactly you mean.

**Comment by grexe** [comment]
done, was only the Markdown link syntax that got mixed up, fixed, but you could simply have tried the link text,-)

**Comment by JKE-be** [comment]
@grexe Thank you for your suggestion.
As discussed in a previous issue, an internal team are working on it (Odoo Studio) and we hope that a first version will be available for v10.
