### ISSUE TITLE
[16.0]Unable to print image attachment from attachment viewer

### ISSUE THREAD

**Issue by micheledic** [odoo/odoo#114426]
Hello,
there is an issue on attachment viewer. If you click on print on ad image, the new popup is empty because of an error on the javascript code. 
I have also found the soultion
on  this line
https://github.com/odoo/odoo/blob/16.0/addons/mail/static/src/models/attachment_viewer.js#L172
this.imageUrl is wrong and should be ${this.attachmentViewerViewable.imageUrl}
I have tried on my local code changing this and it works

I created pull request #114547

**Comment by vava-odoo** [comment]
Linked PR https://github.com/odoo/odoo/pull/114547 has been merged
