### ISSUE TITLE
Creating a new project from a template with private project setting fails

### ISSUE THREAD

**Issue by bennals** [odoo/odoo#11446]
Impacted versions: 8

Steps to reproduce: 
1. Log in as user with Project Manager permissions (the issue does not occur when logged in as Admin)
2. Create a project  
3. Set Privacy / Visibility to 'Private project : followers Only' and save
4. Set project to template  
5. Click 'New project based on Template'

Current behavior:
The following error occurs
"ValidateError

Field(s) `project_escalation_id` failed against a constraint: Error! You cannot assign escalation to the same project!

Error details:

AccessError

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: project.project, Operation: read)"

Expected behavior:
A new project based on the template is created

Note: If the Privacy / Visibility setting is 'Public' or 'Internal' then the project is created as expected. 

There are two issues here:
1.  The error message is not helpful in diagnosing the problem
2.  I don't see any reason why a template set to Private Project should not allow the creation of a new project.

**Comment by Yenthe666** [comment]
Hi @bennals,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
