### ISSUE TITLE
[16.0] l10n_fr_pos_cert: cash "AttributeError: 'account.bank.statement' object has no attribute 'state'"

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#114514]
Impacted versions: 16.0

Steps to reproduce : delete a bank statement

In l10n_fr_pos_cert, file models/account_bank_statement.py, in the method _unlink_except_created_by_pos, the code uses the field "state" on account.bank.statement, but this field was removed in v16 !

cf https://github.com/odoo/odoo/blob/16.0/addons/l10n_fr_pos_cert/models/account_bank_statement.py#L16

**Comment by Yenthe666** [comment]
@smetl uh-oh 👀
