### ISSUE TITLE
[9.0] summernote shift click outside the editor throws error

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#11452]
Impacted versions: 9.0c master

Steps to reproduce: 
1) Open any view with the summernote editor (html field) 
   e.g. in user preferenes
2) shift+mouseup anywhere out of the editor

```
Uncaught TypeError: Cannot read property 'left' of undefined
http://138565-9-0-193636.runbot8.odoo.com/web/content/1770-7d4757a/web.assets_backend.js:6612
Traceback:
TypeError: Cannot read property 'left' of undefined
    at HTMLDocument.summernote_mouseup (http://138565-9-0-193636.runbot8.odoo.com/web/content/1770-7d4757a/web.assets_backend.js:6612:78)
    at HTMLDocument.jQuery.event.dispatch (http://138565-9-0-193636.runbot8.odoo.com/web/content/1766-4d4c5bb/web.assets_common.js:740:451)
    at HTMLDocument.elemData.handle (http://138565-9-0-193636.runbot8.odoo.com/web/content/1766-4d4c5bb/web.assets_common.js:713:173)
```

rte.summernote.js
`summernote_mousedown` doesn't set `initial_data.rect` if the event target isn't .o_editable, .note-editor
`summernote_mouseup` checks for `initial_data.rect` if shift was pressed.

Locally I added check to see if `rect` was set.

```
function summernote_mouseup (event) {
...le = $(event.target).closest(".o_editable, .note-editor");
    if (initial_data.event) {
            var dx = event.clientX - (event.shiftKey && initial_data.rect ? initial_data.rect.left : initial_data.event.clientX);
            var dy = event.clientY - (event.shiftKey && initial_data.rect ? initial_data.rect.top : initial_data.event.clientY);
...
}
```

 I don't know how to go about making pull request. But it would be nice to see this fixed in master.

**Comment by Yenthe666** [comment]
Hi @InfernalLV,

Thanks a lot for your bug report and sorry for the late reply.
I've just tried to reproduce this on the latest Odoo 9.0 and it seems to work fine out of the box in the meanwhile.
Please update your local Odoo instance if you still face this problem.

Regards,
Yenthe
