### ISSUE TITLE
Odoo 9.0 empty pdf file.

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#11450]
Impacted versions: Odoo 9.0

Steps to reproduce: Purchases -> RFQ -> print RFQ

Current behavior: download a file but the size is 0 bytes and can not be open.

Expected behavior: Can be normal use

Video/Screenshot link (optional):

OS : Centos 7.0 

Hello,
The wkhtmltopdf is can be used in the command line.

**Comment by Yenthe666** [comment]
Hi @renjunfu,

Could you test this again on the latest source code? I don't have this problem on a new CentOS with Odoo 9.0

**Comment by mhtran** [comment]
I am getting the same using latest Ubuntu version 16.04.01

I got a internal error 500 which I think was related to an expectation with the display

I installed xvfb, created a shell script that would call it and wkhtmltopdf but I then get a 0 byte file.

Just wondering if this is a known issue and if odoo or someone in the community has built .dev or .rpm ( For those running Fedora/CentOS) packages that would work without needing to spending time to compile them.

**Comment by Yenthe666** [comment]
@sle-odoo any update here? (cc @d-fence as this might be OS/package related)

**Comment by sle-odoo** [comment]
You have ton install the wkhtmltopdf with patched qt from wkhtmltopdf.org

The package versiosn from centos and debian won't work
