### ISSUE TITLE
ERROR ? openerp.service.server: Failed to load server-wide module `web`.

### ISSUE THREAD

**Issue by xclam** [odoo/odoo#11456]
Impacted versions: 8.0

Steps to reproduce: odoo.py --addons-path=/opt/odoo/odoo/addons 

Hello, 

odoo crash tonight and when I trying to restart it I get this error :

> 2016-03-23 13:04:41,304 17320 INFO ? openerp: OpenERP version 8.0alpha1
> 2016-03-23 13:04:41,304 17320 INFO ? openerp: addons paths: ['/home/rjoli/.local/share/OpenERP/addons/8.0', u'/opt/odoo/odoo/openerp/addons', u'/opt/odoo/odoo/addons', '/usr/local/lib/python2.7/dist-packages/openerp-8.0alpha1-py2.7.egg/openerp/addons']
> 2016-03-23 13:04:41,304 17320 INFO ? openerp: database hostname: localhost
> 2016-03-23 13:04:41,304 17320 INFO ? openerp: database port: 5432
> 2016-03-23 13:04:41,304 17320 INFO ? openerp: database user: odoo
> 2016-03-23 13:04:41,363 17320 CRITICAL ? openerp.modules.module: Couldn't load module web
> 2016-03-23 13:04:41,363 17320 CRITICAL ? openerp.modules.module: No module named api
> 2016-03-23 13:04:41,364 17320 ERROR ? openerp.service.server: Failed to load server-wide module `web`.
> The `web` module is provided by the addons found in the `openerp-web` project.
> Maybe you forgot to add those addons in your addons_path configuration.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/openerp-8.0alpha1-py2.7.egg/openerp/service/server.py", line 842, in load_server_wide_modules
>     openerp.modules.module.load_openerp_module(m)
>   File "/usr/local/lib/python2.7/dist-packages/openerp-8.0alpha1-py2.7.egg/openerp/modules/module.py", line 301, in load_openerp_module
>     __import__('openerp.addons.' + module_name)
>   File "/usr/local/lib/python2.7/dist-packages/openerp-8.0alpha1-py2.7.egg/openerp/modules/module.py", line 76, in load_module
>     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
>   File "/opt/odoo/odoo/addons/web/__init__.py", line 8, in <module>
>     import controllers
>   File "/opt/odoo/odoo/addons/web/controllers/__init__.py", line 1, in <module>
>     from . import main, pivot
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 25, in <module>
>     from openerp.api import Environment
> ImportError: No module named api
> 2016-03-23 13:04:41,366 17320 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
> ^C2016-03-23 13:04:45,864 17320 INFO ? openerp.service.server: Initiating shutdown
> 2016-03-23 13:04:45,864 17320 INFO ? openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

I don't have web addons path thanks it's in directory odoo/addons ?
I do nothing on odoo or postgres for 2 weeks or more.

When I launch 
> odoo.py -c=/etc/odoo-server.conf 
it doesn't load the configuration.

When I do 
> odoo.py --help
I get OpenERP version 8.0alpha1

Postgres log :

> 2016-03-22 18:29:31 CET LOG:  invalid length of startup packet
> 2016-03-22 18:29:32 CET LOG:  invalid length of startup packet
> 2016-03-22 18:29:33 CET FATAL:  unsupported frontend protocol 65363.19778: server supports 1.0 to 3.0
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection
> 2016-03-22 18:40:59 CET LOG:  unexpected EOF on client connection

Nothing in odoo's log

**Comment by xclam** [comment]
Ok so, I have reinstall odoo 8.
When I launch thanks to 
> odoo.py --addons-path=/opt/odoo/odoo/addons
log are fine but web module doesn't load

sometime I have 
> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

sometime i have a redirect loop:

> 2016-03-23 18:24:17,529 4787 INFO None werkzeug: 78.221.207.189 - - [23/Mar/2016 18:24:17] "GET /web HTTP/1.1" 302 -
> 2016-03-23 18:24:17,674 4787 INFO pitayacom openerp.modules.loading: loading 1 modules...
> 2016-03-23 18:24:17,692 4787 INFO pitayacom openerp.modules.loading: 1 modules loaded in 0.02s, 0 queries
> 2016-03-23 18:24:17,757 4787 INFO pitayacom openerp.modules.loading: loading 68 modules...
> 2016-03-23 18:24:17,781 4787 INFO pitayacom openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
> 2016-03-23 18:24:17,782 4787 CRITICAL pitayacom openerp.modules.module: Couldn't load module report
> 2016-03-23 18:24:17,783 4787 CRITICAL pitayacom openerp.modules.module: 'NoneType' object has no attribute 'group'

Chrome error :
> GET http://www.mypitaya.fr:8069/web net::ERR_TOO_MANY_REDIRECTS

**Comment by paolovalier** [comment]
this isn't an odoo bug but an installation issue
check twice the addons path, I should be at least /opt/odoo/odoo/addons **and** /opt/odoo/addons
there's plenty of material in the web about installation, check there

**Comment by xclam** [comment]
The first installation worked fine for about 1 year and suddenly bug with this error without modification.

My path for web ressources is /opt/odoo/odoo/addons/

The odoo script is in version 8.0alpha1, it doesn't take the config file in /etc/odoo-server.conf nor ~/.openerp_serverrc

**Comment by xclam** [comment]
ok i don't get the web error anymore but i still have the redirection loop error.

I don't understand 
> None werkzeug: 78.248.240.161

This is my internet provider 

> python openerp-server -w ****** -r ****** --addons-path=/opt/odoo/odoo/openerp/addons,/opt/odoo/odoo/addons --xmlrpc-interface=92.222.21.62
> /usr/lib/python2.7/dist-packages/pygments/plugin.py:39: UserWarning: Module openerp was already imported from /opt/odoo/odoo/openerp/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/openerp-8.0alpha1-py2.7.egg is being added to sys.path
>   import pkg_resources
> 2016-03-28 10:09:29,506 7305 INFO ? openerp: OpenERP version 8.0
> 2016-03-28 10:09:29,507 7305 INFO ? openerp: addons paths: ['/home/rjoli/.local/share/Odoo/addons/8.0', u'/opt/odoo/odoo/openerp/addons', u'/opt/odoo/odoo/addons']
> 2016-03-28 10:09:29,507 7305 INFO ? openerp: database hostname: localhost
> 2016-03-28 10:09:29,507 7305 INFO ? openerp: database port: ****
> 2016-03-28 10:09:29,507 7305 INFO ? openerp: database user: ******
> 2016-03-28 10:09:29,691 7305 INFO ? openerp.service.server: HTTP service (werkzeug) running on 92.222.21.62:8069
> 2016-03-28 10:09:38,704 7305 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
> 2016-03-28 10:09:39,180 7305 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
> 2016-03-28 10:09:39,190 7305 INFO ? werkzeug: 78.248.240.161 - - [28/Mar/2016 10:09:39] "GET /web HTTP/1.1" 500 -
> 2016-03-28 10:09:39,195 7305 ERROR ? werkzeug: Error on request:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.6-py2.7.egg/werkzeug/serving.py", line 177, in run_wsgi
>     execute(self.server.app)
>   File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.6-py2.7.egg/werkzeug/serving.py", line 165, in execute
>     application_iter = app(environ, start_response)
>   File "/opt/odoo/odoo/openerp/service/server.py", line 290, in app
>     return self.app(e, s)
>   File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
>     return application_unproxied(environ, start_response)
>   File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
>     result = handler(environ, start_response)
>   File "/opt/odoo/odoo/openerp/http.py", line 1291, in __call__
>     self.load_addons()
>   File "/opt/odoo/odoo/openerp/http.py", line 1312, in load_addons
>     m = __import__('openerp.addons.' + module)
>   File "/opt/odoo/odoo/openerp/modules/module.py", line 80, in load_module
>     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
>   File "/opt/odoo/odoo/addons/report/__init__.py", line 2, in <module>
>     import models
>   File "/opt/odoo/odoo/addons/report/models/__init__.py", line 1, in <module>
>     import report
>   File "/opt/odoo/odoo/addons/report/models/report.py", line 72, in <module>
>     version = re.search('([0-9.]+)', out).group(0)
> AttributeError: 'NoneType' object has no attribute 'group'
> 2016-03-28 10:09:40,715 7305 INFO pitayacom openerp.modules.loading: loading 1 modules...
> 2016-03-28 10:09:40,730 7305 INFO pitayacom openerp.modules.loading: 1 modules loaded in 0.02s, 0 queries
> 2016-03-28 10:09:40,782 7305 INFO pitayacom openerp.modules.loading: loading 68 modules...
> 2016-03-28 10:09:40,855 7305 INFO pitayacom openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
> 2016-03-28 10:09:40,856 7305 CRITICAL pitayacom openerp.modules.module: Couldn't load module report
> 2016-03-28 10:09:40,857 7305 CRITICAL pitayacom openerp.modules.module: 'NoneType' object has no attribute 'group'
> 2016-03-28 10:09:40,858 7305 INFO pitayacom openerp.http: Generating nondb routing
> 2016-03-28 10:09:40,904 7305 INFO None werkzeug: 78.248.240.161 - - [28/Mar/2016 10:09:40] "GET /web HTTP/1.1" 302 -
> ...
> ...
> ...

**Comment by xclam** [comment]
The problem was with wkhtmltopdf.
I don't know why, odoo can't get the verion

> 2016-03-28 10:09:39,180 7305 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
...
...
> File "/opt/odoo/odoo/addons/report/models/report.py", line 72, in
> version = re.search('([0-9.]+)', out).group(0)
> AttributeError: 'NoneType' object has no attribute 'group'

so i reinstalled it and now it's work 

The true interogation is why there was a problem with it ?
Odoo running well and it shuting down with no reason and then get this error.
I do nothing on the server.
