### ISSUE TITLE
Longpolling 502 error

### ISSUE THREAD

**Issue by jl2035** [odoo/odoo#11468]
Impacted versions: 9.0
Steps to reproduce: No idea
Current behavior: Longpolling not working
Expected behavior: Longpolling should work
Video/Screenshot link (optional): https://www.odoo.com/forum/help-1/question/why-am-i-getting-502-error-with-longpolling-99683

Please check the above link. Nobody is responding on Odoo forums.

I'm learning Odoo for over a month now, and I see their support is just terrible. :(

**Comment by adekock11** [comment]
Hi @jl2035. I read the link. There is one answer noted there in the lines of: check that you run Odoo with more than one worker.

To do this, you should either specify the `workers` parameter in the config file or specify the `--workers` parameter when running Odoo.

**Comment by adekock11** [comment]
To add to my previous answer, check your config file. You will see that you currently have a `workers = 0` parameter which is there by default. Change this to `workers = 2`.

**Comment by jl2035** [comment]
Thank you for your kind answer, but after setting workers to 2 or 4 I'm still getting 502 error. Do I need to change anything else?

**Comment by andre-oa** [comment]
Hi @jl2035. Just to make 100% sure, did you restart your Odoo server after you changed the parameter?

**Comment by adekock11** [comment]
Hi @jl2035. Just to confirm: after you changed the workers setting, did you restart the server?

**Comment by jl2035** [comment]
@adekock11 I did. Many times.

**Comment by adekock11** [comment]
Hi @jl2035. Okay, the other thing I can think of is that your routing setting may be wrong. I use Nginx to manage that. If you also use Nginx I may be able to assist.

**Comment by jl2035** [comment]
I do. Here is my configuration:

```
server {
    listen      443;
    server_name fhisa.tabla.si;

    access_log  /var/log/nginx/fhisa.access.log;
    error_log   /var/log/nginx/fhisa.error.log;

    ssl on;
    ssl_certificate     /etc/nginx/ssl/fhisa.crt;
    ssl_certificate_key /etc/nginx/ssl/fhisa.key;
    keepalive_timeout   90;

    ssl_ciphers             HIGH:!ADH:!MD5;
    ssl_protocols           SSLv3 TLSv1;
    ssl_prefer_server_ciphers on;

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    location /longpolling {
        proxy_pass http://odoo-lp;
    }

    location / {
        proxy_pass  http://odoo;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
    }

    location ~* /web/static/ {
        proxy_cache_valid 100 30m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }
}

server {
    listen      80;
    server_name fhisa.tabla.si;
    add_header Strict-Transport-Security max-age=2592000;
    rewrite ^/.*$ https://$host$request_uri? permanent;
}
```

And this is my nginx.conf file:

```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";
        include /etc/nginx/conf.d/*.conf;
        upstream odoo {
                server 127.0.0.1:8069;
        }
        upstream odoo-lp {
                server 127.0.0.1:8072;
        }
        include /etc/nginx/sites-enabled/*;
        client_max_body_size 20M;
}

```

**Comment by joolsr** [comment]
Hi, just a thought, in your main odoo conf file, you do have the proxy enabled - otherwise you will get some bad errors.

proxy_mode = True in /etc/odoo-server.conf

This might hopefully be your problem - let me know if this helps

**Comment by jl2035** [comment]
Nope. Proxy mode was already set to True.

**Comment by joolsr** [comment]
Hi again

I had this problem where my long polling was working then stopped working suddenly. I made some notes which i will post below in case they are of use.

_Update2 Finally Odoo support helped solve this problem. The problem was quite simple, but yet disguised. It was missing python package psycogreen. But it was not mentioned as dependency and when installing im_chat it didn't require such package. So if you were running Odoo with –workers=0, then installed im_chat and later switched to for example –workers=2, Odoo would not throw any error and longpolling port would never be opened. Installing this solved it: pip install psycogreen==1.0 Installing psycogreen as above worked, and now the service on 8072 is seen_

The original answer is buried here … https://github.com/odoo/odoo/issues/3793

I note you installed psycogreen already but note it needs to be version 1.0, and is best installed with pip install psycogreen==1.0 . 

I hope some of the above may give you a clue ... it kept me guessing for a while when mine broke

**Comment by jl2035** [comment]
user@odooserver:/opt/odoo$ sudo pip install --upgrade psycogreen==1.0
Requirement already up-to-date: psycogreen==1.0 in /usr/local/lib/python2.7/dist-packages
Cleaning up...

I also tried removing and installing again. But with no luck. Longpooling still not works.

**Comment by jl2035** [comment]
I just noticed the error in odoo.py output. This could be connected to my issue, right?

127.0.0.1 - - [2016-04-13 07:28:47] "POST /longpolling/poll HTTP/1.0" 200 330 50.016353
2016-04-13 07:28:48,931 16330 ERROR ? openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 1624, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by aristobulo-eezee** [comment]
You need to add a second upstream for port 8072, and then add a location /longpolling/ and proxy_pass it to your new upstream.

**Comment by jl2035** [comment]
@aristobulo-eezee can you find anything wrong with my configuration, that I pasted above.

**Comment by gustavovalverde** [comment]
I'm having this error in a new installation were I had some workers configured in the beggining, then removed:

2016-07-20 12:32:07,209 5594 INFO <database> werkzeug: <IP> - - [20/Jul/2016 12:32:07] "POST /longpolling/poll HTTP/1.1" 200 -
2016-07-20 12:32:21,201 5594 ERROR <database> openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 164, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 75, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/odoo/odoo-server/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found

How can I fix this?

**Comment by jl2035** [comment]
Damn! It's Odoo10, some time has passed, and here I find myself back here at the issue I opened :(
Still very frustrating problem!

This is deeply connected to dbfilter logout bug: https://github.com/odoo/odoo/issues/11740

/longpolling still doesn't work out of the box, if you don't enable proxy_mode and add workers. But when I do that I'm constantly getting a logout and these errors start poping up:

127.0.0.1 - - [2017-05-24 06:31:36] "POST /longpolling/poll HTTP/1.0" 200 1003 0.022701
2017-05-24 06:31:39,966 28608 ERROR ? odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/odoo10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo10/odoo/http.py", line 1450, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/home/odoo/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1563, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by NicolasWebDev** [comment]
I had the same problem, but I found out that I had to write
```
location /longpolling {
    proxy_pass http://odoo_host:8072/longpolling;
}
```
(note the trailing longpolling).

It seems that the request has to be http://odoo_host:8072/longpolling/poll, while in my apache configuration, it was done to http://odoo_host:8072/poll.

Now I don't have the 404 error anymore, and this line `2017-07-31 22:29:56,907 17 DEBUG test2 openerp.http.rpc.request: poll: None None: time:50.011s mem: 506840k -> 506840k (diff: 0k)` appears in the odoo logs (with log_level = debug_rpc).
So I guess that it is the indication that the polling is now working.

In all the tests I have done, the odoo server did not send any response to the request, maybe because I am not using the chat.

Could someone confirm/infirm my thoughts?

**Comment by lmstephenson** [comment]
@NicolasWebDev Thank you for sharing. Adding the location in the .conf file fixed the issue for me as well. I used the upstream syntax for readability. E.g. at the top of `/etc/nginx/conf.d/mydomain.com.conf` I now have two upstream definitions.

```
upstream odoo {
    server 127.0.0.1:8069;  
}

## Added upstream odoolp to resolve JSON exception error in log file
## (ERROR ? openerp.http: Exception during JSON request handling.)
##

upstream odoolp {  
    server 127.0.0.1:8072;  
}
```

Then lower in the .conf file, near the rest of the location blocks, I added:

```
...
    location ~* /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }
    location ~* /xmlrpc/ {
        #proxy_cache_valid 200 60m;
        #proxy_buffering on;
        #expires 864000;
        proxy_pass http://odoo;
    }

   ## Added upstream odoolp to resolve JSON exception
    location /longpolling {
        proxy_pass http://odoolp/longpolling;
    }
...
```

**Comment by Yenthe666** [comment]
@sle-odoo any update? Since you've assigned yourself quite a while ago.

**Comment by sle-odoo** [comment]
Hi,

It all seems like configuration issues. Please make a backup of your configuration files and be sure to follow [this guide](https://www.odoo.com/documentation/10.0/setup/deploy.html#id7) with the mentionnent configuration files and it should work. Then you can add your own configuration on top.

Please answer on this ticket if you've followed exactly the steps of the guide and it doesn't work for you. Don't forget to mention if you've installed all the python libraries and the traceback you got, along with your odoo configuration files.

Regards

**Comment by rhifat** [comment]
hi odoo 13 ce the solution to the problem is as follows.

Open /etc/nginx/sites-enabled/odoo.conf

  # Redirect longpoll requests to odoo longpolling port
  location / longpolling {
  proxy_pass http: // odoo / longpolling;
  }

edit as the problem will be solved

**Comment by weasam** [comment]
> hi odoo 13 ce the solution to the problem is as follows.
> 
> Open /etc/nginx/sites-enabled/odoo.conf
> 
> location / longpolling {
> proxy_pass http: // odoo / longpolling;
> }
> 
> edit as the problem will be solved

I am on Odoo 14   my configuration like this below
sudo nano /etc/nginx/sites-available/my_domain.conf
sudo nano /etc/nginx/sites-enabled/my_domain.conf
after added proxy_pass http://odoo/**longpolling**; restart nginx, still not work

# Odoo servers
upstream odoo {
 server 127.0.0.1:8069;
}

upstream odoochat {
 server 127.0.0.1:8072;
}

# HTTP -> HTTPS
server {
    listen 80;
    server_name www.my_domain.com my_domain.com;

    include snippets/letsencrypt.conf;
    return 301 https://my_domain.com$request_uri;
}

# WWW -> NON WWW
server {
    listen 443 ssl http2;
    server_name www.my_domain.com;

    ssl_certificate /etc/letsencrypt/live/my_domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my_domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/my_domain.com/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;

    return 301 https://my_domain.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name my_domain.com;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    # Proxy headers
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # SSL parameters
    ssl_certificate /etc/letsencrypt/live/my_domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my_domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/my_domain.com/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;

    # log files
    access_log /var/log/nginx/odoo.access.log;
    error_log /var/log/nginx/odoo.error.log;

    # Handle longpoll requests
    location /longpolling {
        proxy_pass http://odoochat/longpolling;
    }

    # Handle / requests
    location / {
       proxy_redirect off;
       proxy_pass http://odoo;
    }

    # Cache static files
    location ~* /web/static/ {
        proxy_cache_valid 200 90m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }

    # Gzip
    gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
    gzip on;
}

**Comment by weasam** [comment]
@rhifat 

I am on Odoo 14   my configuration like this below
sudo nano /etc/nginx/sites-available/my_domain.conf
sudo nano /etc/nginx/sites-enabled/my_domain.conf
after added proxy_pass http://odoo/**longpolling**; restart nginx, still not work

# Odoo servers
upstream odoo {
 server 127.0.0.1:8069;
}

upstream odoochat {
 server 127.0.0.1:8072;
}

# HTTP -> HTTPS
server {
    listen 80;
    server_name www.my_domain.com my_domain.com;

    include snippets/letsencrypt.conf;
    return 301 https://my_domain.com$request_uri;
}

# WWW -> NON WWW
server {
    listen 443 ssl http2;
    server_name www.my_domain.com;

    ssl_certificate /etc/letsencrypt/live/my_domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my_domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/my_domain.com/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;

    return 301 https://my_domain.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name my_domain.com;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    # Proxy headers
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    # SSL parameters
    ssl_certificate /etc/letsencrypt/live/my_domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my_domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/my_domain.com/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;

    # log files
    access_log /var/log/nginx/odoo.access.log;
    error_log /var/log/nginx/odoo.error.log;

    # Handle longpoll requests
    location /longpolling {
        proxy_pass http://odoochat/longpolling;
    }

    # Handle / requests
    location / {
       proxy_redirect off;
       proxy_pass http://odoo;
    }

    # Cache static files
    location ~* /web/static/ {
        proxy_cache_valid 200 90m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo;
    }

    # Gzip
    gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
    gzip on;
}

**Comment by YefersonGallo** [comment]
@weasam I am on Odoo 14 too, i've try your config in nginx and odoo but still not work. My files config are:
nginx/sites-available/mydomain.com.conf
```
 upstream odoo {
  server 127.0.0.1:8069;
 }
 
 upstream odoochat {
  server 127.0.0.1:8072;
 }
 
 server {
  listen 80;
  server_name www.my_domain.com my_domain.com;
  proxy_read_timeout 720s;
  proxy_connect_timeout 720s;
  proxy_send_timeout 720s;
 
 # Proxy headers
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Real-IP $remote_addr;
  access_log /var/log/nginx/odoo.access.log;
  error_log /var/log/nginx/odoo.error.log;
 
  location /longpolling {
    proxy_pass http://odoochat/longpolling;
  }
 
 # Handle / requests
  location / {
    proxy_redirect off;
    proxy_pass http://odoo;
  }
 
 # Cache static files
  location ~* /web/static/ {
     proxy_cache_valid 200 90m;
     proxy_buffering on;
     expires 864000;
     proxy_pass http://odoo;
  }
 
 # Gzip
  gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
  gzip on;
 }
```
/odoo/odoo.conf:

```
[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons
admin_passwd = password-admin
csv_internal_sep = ,
data_dir = /var/lib/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 240
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
max_cron_threads = 2
osv_memory_age_limit = False
osv_memory_count_limit = False
pg_path =
pidfile =
proxy_mode = True
reportgz = False
screencasts =
screenshots = /tmp/odoo_tests
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = False
longpolling_port = 8072
xmlrpc_port = 8069
workers = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
```

is there an error in the configuration files?
 Help

**Comment by weasam** [comment]
@YefersonGallo 
In my case my odoo.config as below or maybe I missed something. Almost forgot how I fixed it
admin_passwd = MyPassword
db_host = False
db_port = False
db_user = odoo
db_password = False
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo.log
addons_path = /opt/odoo/odoo/addons,/opt/odoo/odoo/custom-addons

proxy_mode = True

longpolling_port = 8072
# xmlrpc_port = 8069
workers = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
Try to simplify your config file make it without conflix, This was made me headeche for a while
double check /etc/nginx/sites-enabled/my_domain.conf same or not.
waiting your good news back

**Comment by jes-ale** [comment]
```
  location /longpolling {
    proxy_pass http://odoochat/longpolling/;
  }
```
