### ISSUE TITLE
[9.0] Use down arrow in a many2one/many2many_tags field inside a one2many list triggers 2 events

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#11465]
Impacted versions: 9.0

Steps to reproduce:

* Go to Accounting > Sales > Customer Invoices
* Create a new invoice
* Select a partner
* Create a line and select a product
* Create another line and select another product
* Go again to the first line, and put the focus on the Taxes field of the first line.
* Click the down arrow

Current behavior:
The focus is passed to the second invoice line, and the many2many_tags widget is unfolded.

Expected behavior:
Only the many2many_tags widget should be unfolded, without losing the focus on the first invoice line.

**Comment by qsm-odoo** [comment]
Hello, this issue had been fixed in 9.0c with commit https://github.com/odoo/odoo/commit/324dbcde573a65081b59932bcdc023cb5878d2bb
Other versions will get the fix in the upcoming days.

**Comment by pedrobaeza** [comment]
Thank you very much!
