### ISSUE TITLE
[8.0] can't build html docs

### ISSUE THREAD

**Issue by cundi** [odoo/odoo#11478]
I use the command `make html`, and then I got this error.  

```
sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html

Extension error:
Could not import extension patchqueue (exception: No module named mercurial.patch)
```

**Comment by xmo-odoo** [comment]
Not sure what version of mercurial you have, try downgrading your install to mercurial 3.5, sphinx-patchqueue should be compatible with that but may not be compatible with 3.6 or 3.7

**Comment by cundi** [comment]
As you guess previous , I'm using mercurial's version is 3.7.  

```
(.odoo-8.0)m-l@m-ldeMacBook-Pro ~> pip list | grep mercurial 
mercurial (3.7.2)
```

uninstall the old one and reinstall the 3.5 version of mercurial and then run `make html`, there is no error any more.  

Many thanks for @xmo-odoo . If without you I don't kwon how can I to fix it.

**Comment by xmo-odoo** [comment]
No worries. I'll have to check if I can fix sphinx-patchqueue.

**Comment by jhonlen** [comment]
install the package
$ sudo apt-get install python-sphinx-patchqueue
