### ISSUE TITLE
[8.0]product_margin: doesn't works with pos orders (but should be). 

### ISSUE THREAD

**Issue by effelle** [odoo/odoo#11472]
Impacted versions: 8.0

Steps to reproduce: Create an order on POS then check margins.

Current behavior: On 'product_margin' module seems just the cost proposed on a sale order is considered, but since a POS order doesn't pass trough a quotation, the cost field is always 0, then the margin result is wrong.

Expected behavior: Opening the product margin tree view the fields.function 'total_margin' should compute as reported on help hint (help="Turnover - Standard price") 

To sumarize, Odoo needs to select the standard_cost field of product.product as fallback when using POS.

**Comment by effelle** [comment]
@xmo-odoo: is Odoo 8 still open to bug track or you are just focused on 9.0? I've resolved with some lines on one of mine external py module for now, but I prefer all embeded on Odoo and not in my external console.

**Comment by Yenthe666** [comment]
Hi @effelle ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@effelle a PR is still welcome against V9 and up.

Regards,
Yenthe

**Comment by effelle** [comment]
Completely forget this bug, since I'm on V10 now using a new whole custom module for POS.
I need some spare time to have a look on a VM.
> a PR is still welcome against V9 and up.
I'm not sure what you mean @Yenthe666.

**Comment by Yenthe666** [comment]
@effelle,

I was talking about this:

> I've resolved with some lines on one of mine external py module for now

In case you've got a fix you're welcome to make a PR to fix it in V9 😉

**Comment by effelle** [comment]
I don't share "dirty-bad-formatted" code. :P 
Not because I don't want to share, but because this is part of a huge setup that is becoming a full app and would be complicated pull out just the snippet to be submitted. 
I'll send you a mail from the test machine just to see what I'm doing right now.
