### ISSUE TITLE
[BUG][16.0] base: Do not display the correct translation language

### ISSUE THREAD

**Issue by diamondnguyenkc** [odoo/odoo#114748]
Impacted versions: 16.0

Steps to reproduce:

1. Setting => Translations => Languages => Search 'vi' => Activate => Add => Switch Languages
2. Employees => Configuration => Tags
3. Create an Employee Tags with the same name as the already available name
4. Save => Show error message

Current behavior: Do not display the correct translation language

Expected behavior: Showing the correct translation language

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/107665841/223978498-5d78c8e0-9f7d-47d5-8037-697c767faf6a.mp4

https://user-images.githubusercontent.com/107665841/223978767-ec89a9d1-2839-4d37-925a-05fd954c2b50.mp4

**Comment by niyasraphy** [comment]
hi @diamondnguyenkc  ,
are you saying that the translation added for the wording "The operation cannot be completed" in Vietnamese is wrong ?

Không thể hoàn tất thao tác

**Comment by diamondnguyenkc** [comment]
hi @niyasraphy,
No, I don't mean that when translated the Vietnamese language, it still displays the English language while the i18n file has been translated.

**Comment by royleviindoo** [comment]
@diamondnguyenkc fixed at https://github.com/odoo/odoo/pull/115999
CC @niyasraphy @tranngocson1996
