### ISSUE TITLE
[16.0] web: impossible to translate Shortcuts menu

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#114711]
Impacted versions: 16.0

Steps to reproduce: on any language, click on your user on top right, you get Shortcuts menu which is not translated
![image](https://user-images.githubusercontent.com/30716308/223756416-65eed39d-4481-4e97-8c07-65fb22216257.png)

Current behavior: shortcuts menu is not translated, and the field does not come up in Transifex (at least for French language) but I cannot find it in .po files for other languages neither (except for bs, el, km, gu and lb but these are not pointing to the correct path so probably old po files).
![image](https://user-images.githubusercontent.com/30716308/223756605-a86d15d3-b148-4d1e-b416-8190d6c2db5d.png)

Expected behavior: Get Shortcuts translated

**Comment by mart-e** [comment]
@remi-filament sorry not my area of exprtise but I see there is a PR that tries to fix that at #114720 so I let the JS framework team review it.

**Comment by niyasraphy** [comment]
hi @remi-filament ,
fixed in:  https://github.com/odoo/odoo/commit/9d34d2c362864b3345c353d636dcf4f3ed2ccb10

feel free to close the ticket.
thanks

**Comment by remi-filament** [comment]
Thanks @niyasraphy  !
