### ISSUE TITLE
[9.0] POS can't read weight or price barecodes

### ISSUE THREAD

**Issue by yuntux** [odoo/odoo#11477]
Impacted versions: 9.0

Steps to reproduce:
- create a product sold by weight, 10€/kg and a 5 digits default_code : 12345
- verify the barecode nomenclature has the default configuration (weight barecode  = 21.....{NNDDD}) and the POS is linked to this nomenclature
- start a POS session and load the POS module

Current behavior:
When you scan the 2342345106664 barecode, nothing append

Expected behavior:
When you scan the 2342345106664 barecode, a product line is added with the weight = 10,666kg.

The following pull request fixes this issue : 
https://github.com/odoo/odoo/pull/11445

**Comment by sle-odoo** [comment]
Closing as the bug was solver in https://github.com/odoo/odoo/commit/526c38cdb145143407cc0e5504574e72f7e720a0.
