### ISSUE TITLE
[9.0] translations: i don't understand why only "derivated" languages translations are overwritten after a PO update

### ISSUE THREAD

**Issue by bplancher** [odoo/odoo#11481]
Impacted versions: 6.1, 9.0

**Steps to reproduce:**
- Install fr_FR language
- modify a translation (from code) in the fr.po file
- restart Odoo server (with -u ... and -d.... to udpate the module)

**Current behavior:**
The modification is not taken in account for fr_FR language

**Expected behavior:**
The modification from PO file must update existing ir.translation records in fr_FR language

**EDIT**:
For V 6.1, i locally fixed the following line of code of openerp/modules.loading.py, to take --i18n-overwrite in account:
FROM
`modobj.update_translations(cr, 1, [module_id], None)`
TO
`modobj.update_translations(cr, 1, [module_id], None, {'overwrite': tools.config["overwrite_existing_translations"]})`

**Further explanations:**

Greetings,

I know there is already plentiful of translations issues, but after reading the code handling translations through PO files, i need an explanation to understand one thing (without setting --i18n-overwrite option):
- Why "derivated" languages (fr_BE for example) are always overwritten, and not "base" languages (fr_FR for example) ?

If i do not mistake, it means that (when updating a module) Belgium translation will ALWAYS be updated, but France translations WON'T be applied (once a record on ir.translations already exists).Am i correct ?

If yes, i need to understand **why** ORM do that, what is the philosophy behind this.

Is there a relation between languages ?
For example, if a translation is missing in Belgium, does ORM will search for translation in its "base" language (French) ? Or not at all ?

Thanks in advance four your reply,

Regards,

**Comment by mart-e** [comment]
Hello,

I know it may sounds surprising but there is a reason for this behaviour.
The point of the regional languages is to specify variants of a "main" language. So, for the exemple of fr_BE, Odoo will mostly be translated in French (`fr`) but the few differences between the French from France and Belgium will be stored in `fr_BE` translations.

When loading the terms of a module, the ORM will go as follow:

1. load the terms from `fr.po` (overwrite is set by the server configuration or the wizard)
2. load the terms from `fr_BE.po` with forced overwrite

As we want the terms from fr_BE to have the priority over the terms from fr, we need to force an overwrite. This is why we will always keep the one from the regional language.
The point is that `fr_BE.po` should only contains terms that have already been translated in `fr.po` and are different (and where the overwrite makes sense).
