### ISSUE TITLE
[8.0] Uncaught SecurityError with Chrome and third-party cookies disabled

### ISSUE THREAD

**Issue by paolovalier** [odoo/odoo#11490]
**Impacted versions**: 8.0, on runbot too 

**Steps to reproduce**: fresh Odoo 8.0 install, take Chrome browser for Mac (version 49) with third-party cookies disabled and go the the page Configuration -> Modules -> Apps : I get stuck, black screen. 
But with third-party cookies enabled everything is fine (I found the solution [here](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document))

**Current behavior**: the page keeps loading forever while in the background I see this error: `Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` Safari doesn't work either (keep saying Odoo session expired). Firefox works

**Expected behavior**: some more user-friendly warning

**Screenshot**: 
![screenshot](https://cloud.githubusercontent.com/assets/11443924/14060557/9bff5800-f368-11e5-9239-cbc7b8177461.jpg)

**Comment by odoouser2** [comment]
Same error, Please assist. Odoo 9.

**Comment by Yenthe666** [comment]
Hi @paolovalier ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@odoouser2 if you can still reproduce it on the latest Odoo 9 then please do create a new bug report. 😉 

Regards,
Yenthe
