### ISSUE TITLE
Detect Odoo 9.0 page has finished loading ?

### ISSUE THREAD

**Issue by ahmed-taj** [odoo/odoo#11497]
Hi, there

**Sorry** if it's not the right place to ask questions

I'm trying to apply acceptance test Odoo v9.0 based module using [Selenium](http://www.seleniumhq.org/). Unfortunately I couldn't check if the page is fully loaded and rendered using the old way, which do:

```python
driver.execute_script("return (window.jQuery != null) && (window.jQuery.active === 0)")
```
then check if `body.oe_wait` presents. 
The above code works fine for v7 but fails on v9 because jQuery is always active 

Any suggestions for how to solve the problem ?

Thanks.

**Comment by Yenthe666** [comment]
@ahmed-taj this is really for bugs / issues in Odoo, not for asking questions, so I'm afraid you won't get any reaction here..
Just post this question on https://www.odoo.com/forum/help-1 I'm sure somebody can help you there!
