### ISSUE TITLE
Unable to delete manually created field from manually created model

### ISSUE THREAD

**Issue by dmitriypaulov** [odoo/odoo#115015]
Impacted versions: 16

Steps to reproduce:
1. Create model manually (Property: x_property in my case).
2. Create Many2one field for this model (Owner: x_partner_id, Relation - res.partner)
3. Try to delete this field.

Current behavior: Odoo raises an exception

Expected behavior: Odoo lets delete field immediately

Screenshots link (optional): https://imgur.com/a/ziRpIOJ

**UPD**: Exact Odoo version: 16.0-20230109

**Comment by niyasraphy** [comment]
@dmitriypaulov checking the same in runbot is not raising any trace back and successfully the field is getting deleted.
can you confirm it in runbot

**Comment by dmitriypaulov** [comment]
@niyasraphy it isn't reproducing in runbot. Maybe it's specific version issue, cuz I have old label for 'Create' button in my system, not 'New'. Will update this issue with exact version I have

**Comment by dmitriypaulov** [comment]
@niyasraphy Just realized that this error only reproduces when there is at least one record of this module is present in the database. It wasn't a bug. Anyways, thanks for your comment.
