### ISSUE TITLE
arabic langauge issue

### ISSUE THREAD

**Issue by seradev01** [odoo/odoo#115014]
when change language to arabic odoo does not load 
odoo community version

**Comment by AbdelAzizMohamedMousa** [comment]
If you are experiencing an issue where Odoo does not load when you change the language to Arabic, there are a few things you can try:

Check that the language is installed: Ensure that the Arabic language is installed and activated in your Odoo instance. You can check this by going to the Settings menu, selecting Translations, and checking that Arabic is listed and installed.

Clear cache: Clear your browser's cache and try again. Sometimes, the browser cache can cause issues with loading pages, especially when switching languages.

Check Odoo configuration: Verify that the Odoo configuration is set up correctly to support the Arabic language. You can do this by going to the Settings menu and selecting Translations. In the Languages section, ensure that Arabic is enabled and that the direction is set to RTL (right-to-left).

Check server logs: Check the server logs to see if there are any errors or warnings related to the Arabic language. This can help identify any issues that may be preventing Odoo from loading.

Try a different browser: Try accessing Odoo in a different browser. Sometimes, certain browsers can have issues with displaying certain languages or character sets.

Upgrade Odoo: If you are using an older version of Odoo, try upgrading to a newer version. Newer versions of Odoo may have better support for the Arabic language.

If none of these steps resolve the issue, you may need to seek further assistance from the Odoo community or a support provider.

**Comment by seradev01** [comment]
figure this error because OHRMS modulues

**Comment by niyasraphy** [comment]
@seradev01 feel free to close as it third party app.
thanks
