### ISSUE TITLE
Hi how do i add barcodes to my timesheets when I am making them a pdf 

### ISSUE THREAD

**Issue by TiaraPillay** [odoo/odoo#115074]
Impacted versions:16

**Comment by vava-odoo** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
