### ISSUE TITLE
Change in SO for warehouse is not reflected in warehouse

### ISSUE THREAD

**Issue by chand3040** [odoo/odoo#11501]
Impacted versions:
8.0
Steps to reproduce:
Go to sales order -> Create sales order -> Select any warehouse, Select Product and save the SO -> Confirm sales order -> Now edit and change the warehouse. 
Warehouse is changed in SO but the Delivery order remains in same warehouse which should have changed for any good or bad reason.

Current behavior:
SO warehouse changes but DO is not moved to changed warehouse.

Expected behavior:
Delivery order should move to changed warehouse.

**Comment by Yenthe666** [comment]
Hi @chand3040,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
