### ISSUE TITLE
Validation message is not displayed properly

### ISSUE THREAD

**Issue by stephenbiit** [odoo/odoo#11509]
Impacted versions:
     Not able to see the validated message.

Steps to reproduce:
    1). Sales-->Quotations
    2). Create new quotation.
    3). Create new customer from quotation window.

Current behavior:
     Message is shown at the back of the wizard.

Expected behavior:
     Message should be displayed in front of the wizard.

Video/Screenshot link (optional):

![error](https://cloud.githubusercontent.com/assets/8004560/14076846/fceafec6-f502-11e5-9c76-33a0da9091df.png)

**Comment by Yenthe666** [comment]
Hi @stephenbiit,

Thanks a lot for your bug report.
I've just tested this and the behaviour of this view has changes slightly. Now you won't get any error behind your dialog if you're creating a new customer on the fly.
Please update your Odoo code to the latest source if you haven't fixed this yet.

Regards,
Yenthe
