### ISSUE TITLE
Bounced Errors in Mass Mailing

### ISSUE THREAD

**Issue by rafaelDelgado** [odoo/odoo#11514]
Impacted versions:
9.0

Steps to reproduce:
Create a Mass Mailing Email -> Create a Mailing List (With 2 email on it, 1 existing email and 1 does not exist email to get bounced email) -> Send email

Current behavior:
I can send email without any problem, but never get the bounced emails.

Expected behavior:
Get Bounced % on the Mass Mailing Campaing.

Video/Screenshot link (optional):
http://prntscr.com/alc24w

**Comment by treviser** [comment]
Did you properly set up your catchall email address?

**Comment by rafaelDelgado** [comment]
Yes, 
<img width="1027" alt="bounced emails github" src="https://cloud.githubusercontent.com/assets/3718830/14120576/382cda18-f5a8-11e5-86f7-d37777d2e1ad.png">

**Comment by pedrobaeza** [comment]
The bounce notification is not always provided by the recipient mail server, due to the spam, so you need to use a verified mail provider, but it's not Odoo guilty. Closing this.
