### ISSUE TITLE
CSV import error

### ISSUE THREAD

**Issue by bluestingray** [odoo/odoo#11512]
Impacted versions: version 9 - Most recent commit pulled: [84b45515bd2ce47446b4b9e0ac2631e1de6cdebd](https://github.com/odoo/odoo/commit/84b45515bd2ce47446b4b9e0ac2631e1de6cdebd)

Steps to reproduce:
Attempt to import csv with several hundred rows to contacts. 

Current behavior:
When trying to import csv file with several hundred rows, clicking the button to validate the csv yields "Uncaught TypeError: Cannot read property '1' of undefined". We have looked over the data being imported and it does appear valid (only two columns for external ID, and customer boolean). Creating new individual records (partners, products, etc.) works without TypeError. Also, importing only the first 100 rows of test csvs also validates and successfully imports.

Expected behavior:
Expected successful validation of csv for import.

Video/Screenshot link (optional):

**Comment by wtaferner** [comment]
@bluestingray 
Are you running Odoo behind a proxy? If so, you need to increase the request timeout if you want a proper response (actually the import is continuing to run in the background until it is finished and most probably raises an error which you can't see) otherwise the data will be correctly imported...besides you need to take care of the Odoo worker processes timeout if you run in multiprocessing mode.

So, it is not a bug but your responsibility in setting Odooup correctly.

Maybe you will be helped [here](https://www.odoo.com/documentation/8.0/setup/deploy.html) or [Google](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Cannot+read+property+'1'+of+undefined+csv+import+odoo) most definitely has an answer for you ;-)

**Comment by xmo-odoo** [comment]
Having a full traceback of the error and a reproducible test case (files exposing the issue) would also help.

**Comment by Yenthe666** [comment]
@bluestingray is this issue still relevant or can you still reproduce it?
It would be great if you could give us more information and/or an example CSV.

**Comment by ruuter** [comment]
@Yenthe666 it is still pretty relevant to me and I can reproduce it easily. Just import CSV with one2many relations and 500+ rows.

@wtaferner You are right, I am running Odoo behind proxy. I did increase apache `ProxyTimeout` to 600s from default 60s, but this did not change anything. Problem remains. 
You are right about the fact that import continues to run in the background. Postgres process continues with cpu at ~99%. 

Import seems to work if you wait long enough, even after the error, but same thing happens with **Validate**. So it is inherently impossible to validate CSV with more than few hundred rows.

Everything works fine when I split the csv into smaller chunks (pretty annoying).

Also, I just scaled my box to have 2GB RAM and 2CPU's, but this did not help either.
I'm running latest Odoo 9.0c.20160811 on Ubuntu 14.04.5 with kernel 3.13.0-79-generic.

The error itself:

> Uncaught TypeError: Cannot read property '1' of undefined
> 
> https://odoo.domain.com/web/content/312-eff7884/web.assets_backend.js:4247
> 
> Traceback:
> TypeError: Cannot read property '1' of undefined
>     at Object.<anonymous> (https://odoo.domain.com/web/content/312-eff7884/web.assets_backend.js:4247:71)
>     at Object.<anonymous> (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:650:681)
>     at fire (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:644:299)
>     at Object.fireWith [as rejectWith] (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:649:198)
>     at Object.deferred.(anonymous function) (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:651:56)
>     at fire (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:644:299)
>     at Object.fireWith [as rejectWith] (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:649:198)
>     at Object.deferred.(anonymous function) (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:651:56)
>     at fire (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:644:299)
>     at Object.add [as fail] (https://odoo.domain.com/web/content/295-4fba39c/web.assets_common.js:645:467)

**Comment by dreispt** [comment]
@ruuter Are you using workers? Can you post the relevant Odoo log messages?

**Comment by ruuter** [comment]
@dreispt no, I am not using workers. There is nothing in the log. Only relevant line is:

> 2016-08-11 16:41:57,747 1162 INFO production openerp.addons.base_import.models: importing 759 rows...

**Comment by bistaray** [comment]
What is the list of Python packages you have installed?  Also, do you get the same error when importing an XLS file?

**Comment by dreispt** [comment]
Are you using a reverse proxy on top of the Odoo server (Nginx, Apache)?
My guess is that is is a response timeout from the reverse proxy.
You can tweak it's configurations to increase the timeout limit.

**Comment by bmart** [comment]
I'm hitting the same issue. Tried setting longer timeouts after seeing the nginx timeout errors and then I decided to try running the import direct to port 8069 to circumvent nginx. Still seeing the issue.   In any case, I read somewhere that you can only increase those timeouts to a max of 75 seconds  ( http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout)

**Comment by bmart** [comment]
Got my import working. Did 2 more things beyond the nginx configuration steps noted above. 

1. Iincrease the odoo worker timeout by specifying in the server config:
`limit_time_real = 300 `

2. Broke up the file into smaller chunks. I wanted to avoid this, but at 2000 records it was barfing no matter what.

**Comment by dreispt** [comment]
@bmart You might be interested in using the `base_import_async` module: 
https://github.com/OCA/connector-interfaces/tree/9.0/base_import_async

**Comment by bmart** [comment]
Thanks @dreispt  . I've got my own mule/rabbit system working right now but I'm curious to learn more about this Odoo Connector framework. Async would be a great help for these tasks.

**Comment by anassahmed** [comment]
The import functionality really needs to rewritten to handle such frequent stuff.

The javascript web client waits for JSON response that confirms the import task has been completed, but if nginx (in my case) returned HTML page (Gatway Timeout), it gives me this error while the import process is still working in the background!!

In Odoo 8.0, if the import process didn't complete from the web interface, and you refreshed it. All imported data will be rolled-back. You need to split your CSV file, or raise `proxy_read_timeout` and `proxy_connect_timout`, or use werkzeug directly through a port for such tasks.

We need Odoo web client to handle this thing more properly, like starting a background process (thread) for the import, but the main process can check on it periodically to track its progress and report back to the web client Ajax (it may also add a progress bar for these long tasks). If possible, it can also split the task into more threads to handle it faster.

**Comment by dreispt** [comment]
@anassahmed Agree, but strictly speaking it's not a bug.

**Comment by anassahmed** [comment]
@dreispt Right, it's not a bug, call it a feature request/proposal.

The bug here though, is the ambiguous error message. I'm supporter of the _Fail Fast_ approach. Give me a clear message (or even raise the Nginx HTML error like what happens with `XMLHttpRequest` error). Just handle the JSON parse error to stop me fiddling with the logs on server + debug tools in browser (normal users won't do that for sure!!).

**Comment by medianeclick** [comment]
> The import functionality really needs to rewritten to handle such frequent stuff.
> 
> The javascript web client waits for JSON response that confirms the import task has been completed, but if nginx (in my case) returned HTML page (Gateway Timeout), it gives me this error while the import process is still working in the background!!
> 
> In Odoo 8.0, if the import process didn't complete from the web interface, and you refreshed it. All imported data will be rolled-back. You need to split your CSV file, or raise `proxy_read_timeout` and `proxy_connect_timout`, or use werkzeug directly through a port for such tasks.
> 
> We need Odoo web client to handle this thing more properly, like starting a background process (thread) for the import, but the main process can check on it periodically to track its progress and report back to the web client Ajax (it may also add a progress bar for these long tasks). If possible, it can also split the task into more threads to handle it faster.

Totally agree. Do you know if this import process have been re-written?
