### ISSUE TITLE
[13.0] ERROR al validar facturas de compras por permisos

### ISSUE THREAD

**Issue by francisrubio06** [odoo/odoo#115115]
Impacted versions: 13.0

Steps to reproduce: 

Dentro de una empresa con contabilidad anglosajona activada:
- Creamos una orden de compra de un producto almacenable y configurado con valoración de inventario automática, confirmamos la orden y realizamos el ingreso de inventario del producto.
- Con un usuario que tenga únicamente los permisos de “Usuario” en Compras y “Facturación” en Contabilidad, creamos la factura de la orden de compra y damos clic al botón publicar

Current behavior:

Aparece un mensaje de error indicando que nuestro usuario no tiene los permisos necesarios para realizar la acción

Lo sentimos, no tiene permiso para acceder a documentos de tipo 'Capa de valoración de stock' (stock.valuation.layer). Esta operación está permitida para los grupos: - Inventory/Administrator - (Operación: read, Usuario: 7)

Expected behavior:

La factura debería publicarse a pesar de no tener el permiso de "Administrador" en Inventario

Observation:

Es posible que el error esté dentro en el método `_get_valuation_price_and_qty()` de addons/purchase_stock/models/stock.py en donde faltaría agregar `sudo()` al obtener las capas de valoración de inventario

**Comment by vava-odoo** [comment]
Only last 3 stable versions of Odoo are supported (14, 15 and 16). This version is not supported anymore.
