### ISSUE TITLE
[9.0 CE] website: spacebar symbol is missing when compress html is enabled

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#11541]
Impacted versions: 9.0 C, 9.0 E

Steps to reproduce: install website, website_event modules
enable dev mode
go to website admin
enable: Compress rendered HTML for a better Google PageSpeed result
go to website

Current behavior: some text fields are missing spacebar between fa icons and text

Expected behavior: spacebar symbol shouldn't be removed

Video/Screenshot link (optional):
![compress_bug](https://cloud.githubusercontent.com/assets/5942291/14141014/1ee4529c-f685-11e5-8ae7-6f66ab61e844.png)

**Comment by odony** [comment]
Thanks for reporting. By the way, this option is less useful than simply deploying Odoo behind a web server implementing gzip compression (e.g. nginx). You can safely disable it, too.

**Comment by lem8r** [comment]
Thank for the tip

**Comment by Yenthe666** [comment]
@Gorash did you ever get around to this?

**Comment by JKE-be** [comment]
Thanks for reporting, 

Seems that @Gorash merge a fix about it in V9 (128656f6ea56f200c7e7e0c8f80aa2bb11d7882c) without referring this issue. 

But as explains by the master Odony, the best solution (to avoid potential other bugs) is to disable the feature and use the gzip compression. This feature has been removed in next versions.
