### ISSUE TITLE
Vendor bill does not fetch qty from PO

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#11551]
Impacted versions: 9.0e

Steps to reproduce: Create PO, select invoices, create invoice.

Current behavior: qty is 0 instead of PO amount

Expected behavior: invoice should reflect PO

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @elevationO,

Thanks a lot for your report.
I've just tested this and it works fine now. An example purchase order:
![image](https://user-images.githubusercontent.com/6352350/34950107-7abecdc6-fa12-11e7-9131-01ea0f0ee701.png)
The result after making the bill from the PO:
![image](https://user-images.githubusercontent.com/6352350/34950134-8d0287ac-fa12-11e7-9006-319d9aca1d58.png)
P.S: Notice that you should have confirmed your shipment before the quantities are taken over!

Regards,
Yenthe
