### ISSUE TITLE
[9.0] core :  Field specified in view could not be found when it is custom

### ISSUE THREAD

**Issue by chermed** [odoo/odoo#11564]
Impacted versions:
9.0

Steps to reproduce:
1. Create a custom field from the interface, of course it will begin with `x_`. (e.g. `x_field`)
2. Inherit the method `fields_view_get` and add the field `x_field` to the xml architecture (in this case is the form)

Current behavior:
Error: Field `x_field` specified in view could not be found.

Expected behavior:
1. Display the form with the field.

Video/Screenshot link (optional):
http://monosnap.com/image/G4pqI0poqAc4MY690Rm8g2cfnAQFK8

**Comment by ahefni** [comment]
the same problem in odoo 10 if you have any solution please send it here

**Comment by PCatinean** [comment]
I think the most likely cause is that the fields themselves are not being sent to the web client via fields_view_get method.

Make sure to put a breakpoint just before returning the super() call to fields_view_get and inspect the 'fields' key of the result.

If your field is missing from that list, try doing an update with the result from fields_get.

Something like this:
```
        res = super(ClassName, self).fields_get(
            allfields=allfields, write_access=write_access,
            attributes=attributes
        )
        res['fields'].update(self.fields_get())
        return res
```

Hope this helps

**Comment by pedrobaeza** [comment]
Closing as answered.
