### ISSUE TITLE
[8.0][9.0]Unable to boot Posbox image with Raspberry Pi 3, need to implement the new image. 

### ISSUE THREAD

**Issue by 09520454** [odoo/odoo#11562]
Impacted versions: [8.0][9.0]

Steps to reproduce:
### PosBox image and RPI 3:
 - download latest posbox image from: http://nightly.odoo.com/trunk/posbox/
 - unzip the downloaded image on windows
 - format the SD card using diskpart
 - use Win32DiskImager to write the img to an 8 GB SD card
 - ensure the printer is powered on, and connected to the RPI 3
 - insert the SD card in the RPI 3 and power on the RPI 3
 - The RPI 3 does not boot. 

### Build new Posbox Image 
 - https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox
 - Run sh in terminal
 - sudo ./posbox_create_image.sh
 - Have an error 

```
wget  https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu

Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-31 22:26:25 ERROR 404: Not Found.
```
Current behavior:

Expected behavior:
- Can posbox image compatible with Raspberry Pi 3 ?

Video/Screenshot link (optional):

**Comment by jorenvo** [comment]
Hi,

v13 of the POSBox image does not support the Raspberry Pi 3. We are currently in the process of creating a new image (will be released as v14 probably) which will work on the new Raspberry Pi.


Kind regards,
Joren

**Comment by jujes** [comment]
Hi, I have the same issue.. 
have a release day for v14?
thanks in advance,

**Comment by jorenvo** [comment]
The image was released last week. You can find v14 on http://nightly.odoo.com/master/posbox/.

**Comment by russellnonis** [comment]
Hi I have managed to write the v14 on my sd but I realized the wifi had problem searching for wifi networks. As the SSID field was empty. You can check on your end about this wifi issue?

**Comment by jorenvo** [comment]
The Wi-Fi has been tested and works here. Are you booting up the POSBox without a network cable attached?

**Comment by 09520454** [comment]
Hello,

The v14 worked, but I have problem with wifi. I cannot find the network too. I connect with HDMI but it just command line screen. 

After that I tried this one https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md.

But all configuration(in `wpa_supplicant.conf` ) had been removed after I reboot POSbox.

Can you help ?, I'm using Raspberry Pi 3.

**Comment by jorenvo** [comment]
Could you explain exactly what you're doing? The correct way to do Wi-Fi on the POSBox is to boot it without a network cable, connect to the POSBox Wi-Fi network it creates and then select your Wi-Fi network through the Wi-Fi configuration page on the POSBox homepage. Are you doing that?

**Comment by 09520454** [comment]
Hello,

Thanks for your help.

- I have a RPI3 with posbox image v14, receipt printer, monitor
![image](https://cloud.githubusercontent.com/assets/15643898/15018529/23dd421a-1244-11e6-8511-e4e5b27ef396.png)

- I start POSbox without a network cable.
- This is what I see in the monitor:

![img_0095](https://cloud.githubusercontent.com/assets/15643898/15018487/e68c4b22-1243-11e6-8349-391b1e92f816.JPG)

- I login with `pi/raspberry`
 - sudo nano /etc/wpa_supplicant/wpa_supplicant.conf.
 - Go to the bottom of the file and add the following:

```
network={
    ssid="MyWifi"
    psk="My_wifi_password"
}
```
- wait a min -> it's connected to the Wifi
- I print the receipt ->** it work**
- After that I reboot the POSBox
 - sudo reboot
- all the configuration inside `wpa_supplicant.conf` had been removed.

Actually I dont know where i'm wrong.
BTW you said that `connect to the POSBox Wi-Fi network it creates and then select your Wi-Fi network through the Wi-Fi configuration page on the POSBox homepage`. I dont get it, could you please help me in the details ?

Thanks in advance.

**Comment by jorenvo** [comment]
Hi,

What you're doing is fine, but doing it like that is not really supported by us. For more information about how WiFi is meant to be used please take a look at the official documentation [1].

The reason your files get overwritten is because the POSBox image is mounted read-only. What you're writing to (/etc/) is actually a ramdisk. To bypass it you have to remount / and /root_bypass_ramdisks and then write to /root_bypass_ramdisks/etc/... But once again, that's not supported and you shouldn't have to do that as you can use the WiFi configuration.

[1] https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html#wi-fi-configuration


Kind regards,
Joren

**Comment by vassu008** [comment]
How do i install new hardware modules into posbox? can some one guide me how to install this module in posbox https://www.odoo.com/apps/modules/8.0/hw_customer_display/

**Comment by kenyong3671** [comment]
Hi Jerenvo,

I have flash the V14 img to Pi3 B. Barcode scanner (Argox, China Brand), rfid reader(China Brand) and wifi works perfectly. However, for the escpos printer, at the hardware status it is able to detect the ESCPOS printer (Gprinter, device Id:0571:0055 Philips (or NXP)) but apparently it will not print. i understand that i need to add to device Id to the supported_device.py in order to have it to be printed. But browsing through the /home/pi/odoo/addons/hw_escpos/escpos/, i wasnt able to find the file. Can you guide me how to add additional printer to the posbox.

Thanks

**Comment by jorenvo** [comment]
@kenyong3671 actually the supported devices concept was removed in v13. Right now the POSBox will attempt to auto-detect printers by examining their USB class. Unfortunately printer manufacturers don't always set these correctly. We have some safeguards in place that will take the first Epson or Star device in case this auto-detection fails. You can examine the code [1] to figure out how exactly it works. Perhaps you need to add a small extra if test using the vendorID of your printer?

[1] https://github.com/odoo/odoo/blob/8.0/addons/hw_escpos/controllers/main.py#L55

**Comment by marcel1981** [comment]
Hi, I've installed posbox version 14 and 15 on raspberry pi 3. The raspberry boot and recognize the printer (epson T88 and bixolom 350), I can print 2 or 3 tickets. Next I have an error on lockedstart posbox method; I probed on odoo 8, 9 and 10. Is raspberry 3 compatible? Do I need raspberry 2?

2017-01-24 05:22:15,786 9580 ERROR None werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/pi/odoo/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/home/pi/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/pi/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/pi/odoo/openerp/http.py", line 1297, in __call__
    return self.dispatch(environ, start_response)
  File "/home/pi/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/pi/odoo/openerp/http.py", line 1447, in dispatch
    result = _dispatch_nodb()
  File "/home/pi/odoo/openerp/http.py", line 1426, in _dispatch_nodb
    result = request.dispatch()
  File "/home/pi/odoo/openerp/http.py", line 691, in dispatch
    r = self._call_function(**self.params)
  File "/home/pi/odoo/openerp/http.py", line 318, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/pi/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/pi/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 84, in status_http
    statuses = self.get_status()
  File "/home/pi/odoo/addons/hw_proxy/controllers/main.py", line 45, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 118, in get_status
    self.push_task('status')
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 197, in push_task
    self.lockedstart()
  File "/home/pi/odoo/addons/hw_escpos/controllers/main.py", line 100, in lockedstart
    self.daemon = True
  File "/usr/lib/python2.7/threading.py", line 1029, in daemon
    raise RuntimeError("cannot set daemon status of active thread");
RuntimeError: cannot set daemon status of active thread

**Comment by SborealisS** [comment]
I installed the POSBox image (v15) on a raspberry pi3, everything worked great, now I would like to use that rp as a graphic POS and connect some HDMI screen and a printer to it..

I could see that there is no graphic interface installed by default in the POSBox image. shoulod I install a graphic interface on the raspberry pi3?

**Comment by MaitreDede** [comment]
Hi,
I have Odoo v10 (fresh install on Raspbian Stretch, on a pi 2).
I have tried the Posbox image 15 : no gui, but printer dumps the ip address, and there is a web page on port 8069.
I have tried the Posbox image 16 : the gui says it need Odoo v11. Does it work with Odoo  10 ? Is there a tutorial that shows how to configure the posbox in odoo and demonstrate a "daily usage" ?
Thanks.
