### ISSUE TITLE
Odoo 9 : Followers Issue During Module Re-Insatllation

### ISSUE THREAD

**Issue by Nilim** [odoo/odoo#11568]
**Impacted versions:**Odoo 9 

**Steps to reproduce:**

**Note :- This issue is received when we re-install Purchase Module along with/without demo data.**

a) Install module Purchase Management with demo data on Odoo 9

b) Now, if we go to menu Settings>Technical>Email>Followers, and set filter we will see that for various Purchase orders corresponding Followers are mentioned.

c) Now, when we uninstall the module then corresponding Related Document ID and Related Partner  must also be uninstalled/removed automatically when the module is installed, but it doesn't happen

d) Problem arises when we reinstall the same module onthe same Database, we get an error message **"ERROR, A PARTNER CANNOT FOLLOW TWICE THE SAME OBJECT"** which depicts that the Document ID and Related Partner which were installed during the initial module installation were not uninstalled during module un installation and hence when re installation of module is done it finds duplicate/already existing data and interrupts module installation process.

**Current behavior:**
a) While re-installing the module we face the error **"ERROR, A PARTNER CANNOT FOLLOW TWICE THE SAME OBJECT"**

**Expected behavior**
The followers which gets installed while module installation should get uninstalled along with the module when the module is uninstalled.

**Video/Screenshot link (optional)**:1) Screen Shot 1:-   http://prntscr.com/amp4c8
                                                   2) Screen Shot 2 :-  http://prntscr.com/amp53e

**Comment by learningnewthings** [comment]
It's been half a year and it's NOT solved yet ....

**Comment by jlzhou** [comment]
Still face the issue. :(

**Comment by jffz** [comment]
Also facing it

**Comment by Yenthe666** [comment]
@mart-e could you have a look at this one? Not sure who to ping.

**Comment by mart-e** [comment]
Hello,
It's a limitation of the follower model. You may get conflicts of ids when reinstalling a model.
I have created a task to change that in master (it requires a change of model) but for now we have no other solution than forcing to delete manually the followers before reinstalling a module.

**Comment by mart-e** [comment]
Fixed at #14152

**Comment by tde-banana-odoo** [comment]
Related branch landed in community at https://github.com/odoo/odoo/commit/94d2b97da4af28c551d246f14347f7674c4d50f5 .
