### ISSUE TITLE
[8.0] Journal Search bug the dataset.context

### ISSUE THREAD

**Issue by Shephiroth** [odoo/odoo#11578]
Impacted versions:
Developing under Version 8.0-20151103
Steps to reproduce:
Create any account.move using any journal.
Go into the journal and use "More -> Journal Items".
Try to edit any changes to fire a write event.

Current behavior:
Not sure why but the search have added a context compound with {'journal_id': '{name of the journal}'} and it prevents the normal function of the system.

Expected behavior:
Remove the problematic context compount or add a logic for searchs to avoid this context compound if its needed somewhere else

**Comment by Yenthe666** [comment]
Hi @Shephiroth,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
