### ISSUE TITLE
The problem of misprinting the mobile number in wkhtmltopdf 

### ISSUE THREAD

**Issue by fardinmardani** [odoo/odoo#115787]
Impacted versions:
Odoo 16.0
Current behavior:
Wrong printing of mobile number in the right to the left mode in PDF output (4654646+)
Expected behavior:
That the mobile number is entered correctly (+094111)
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Could you provide the steps to reproduce?

**Comment by flotho** [comment]
did you check the country of the partner
and the setup of the country ?

**Comment by vava-odoo** [comment]
@fardinmardani Feel free to re-open the issue if you have more information to provide
