### ISSUE TITLE
How to get  all variants of a product in sales order invoice template(Odoo) ?

### ISSUE THREAD

**Issue by Jassentha** [odoo/odoo#11580]
Impacted versions:odoo 9

Steps to reproduce:In my sales order invoice template I get only one variant attribute of a product.I want to print all variants of a product in my    invoice template.I  tried this below code in report_invoice_document
`<t t-set="itr" t-value="0"/> 
                      <tr t-foreach="o.invoice_line_ids" t-as="l">
                                    
                        <t t-set="itr" t-value="itr+1"/>
                        <td><t t-esc="itr"/></td>
<td><span t-field="l.name"/>||<span t-field="l.product_id.product_variant_ids"/>
<span t-field="l.product_id.is_product_variant"/>||<span t-field="l.product_id.attribute_line_ids"/>||
<span t-field="l.product_id.attribute_value_ids"/></td>
`
                 
Current behavior:and I get the output
                      [456] pants (Blue, Small)||product.product(2,)True||product.attribute.line(10, 11)||product.attribute.value(1, 4)

Is there any solution to solve this ??

Expected behavior:I want variant in my invoice template.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. Try to share it in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
