### ISSUE TITLE
product.supplierinfo not showing image of an image field using Inheritance.

### ISSUE THREAD

**Issue by Smit296** [odoo/odoo#115858]
Impacted versions: 15.0

Steps to reproduce: Inherit product.supplierinfo -> add image field -> unable to preview Image

Current behavior: Not showing image

Expected behavior: Show Image

Video/Screenshot link (optional): https://ibb.co/H2nysS9

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
Hello

Need more info.
It is not a problem related to the model but just your image field.
Check the network request that failed (since this message is display by the `onError` attribute from your image field. Or maybe your image is just corrupted ?

**Comment by 126296** [comment]
My image field is correct and image is not corrupted.

**Comment by niyasraphy** [comment]
hi @126296 ,
seems working without any issues.

![Screenshot from 2023-05-17 09-28-01](https://github.com/odoo/odoo/assets/27989791/a82da06b-92ab-48c5-9aa4-a3340ebc0472)

thanks

**Comment by vava-odoo** [comment]
@Smit296 Seems to work fine, but feel free to re-open the issue if you have more information to provide
