### ISSUE TITLE
EU data residency and access

### ISSUE THREAD

**Issue by federicommro** [odoo/odoo#115908]
Impacted versions:
Every Odoo online and .sh

Steps to reproduce:
It's just not supported, as stated in the privacy policy.

Current behavior:
The data are aviable in different continent. It's not clear if those backup are encrypted. 
Support team from all around the world can access an Odoo instance

Expected behavior:
A data residency option like "Microsoft EU data boundary" that's already included in Dynamics (free of additional charge).

Video/Screenshot link (optional):
https://blogs.microsoft.com/eupolicy/2022/12/15/eu-data-boundary-cloud-rollout/

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
> The data are aviable in different continent. It's not clear if those backup are encrypted.
yes, it is

> Support team from all around the world can access an Odoo instance
You can request to validate the access to your db one by one 'on support request'

Not an issue with odoo Code base, but hosting...  so I close this one. 

Maybe @odony or @amigrave could give more details / info.
