### ISSUE TITLE
DIN report is broken

### ISSUE THREAD

**Issue by TadeuszKarpinski** [odoo/odoo#116043]
Impacted versions:
16.0
Steps to reproduce:
Install din module, set din as company document layout, print i.e. delivery slip
Current behavior:
Shitty pdf
Expected behavior:
Pretty pdf
Video/Screenshot link (o
[odoo_demo.pdf](https://github.com/odoo/odoo/files/11028806/odoo_demo.pdf)
ptional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @TadeuszKarpinski ,
can you confirm whether this happens in the odoo runbot ? upon checking the same in runbot seems the print out coming fine.
thanks

**Comment by TadeuszKarpinski** [comment]
@niyasraphy Ah wait.. When odoo 16.0 was released? Nice you serve fully functional product. Anyway. I can see that your developers could fix it after few months https://github.com/odoo/odoo/pull/114181
