### ISSUE TITLE
V16 formula based on other pricelist not working

### ISSUE THREAD

**Issue by elmeriniemela** [odoo/odoo#116009]
Impacted versions:
v16

Steps to reproduce:
Make more than one pricelist items that are based on other pricelists.

Current behavior:
If the product is applicable to multiple lines that reference other pricelists, only the first product list item is considered.

![image](https://user-images.githubusercontent.com/36383311/226594643-27eee7b3-01b8-46d3-98e4-dba9016c45ae.png)

**Comment by elmeriniemela** [comment]
@Feyensv Can you help me with this issue? Our customer needs complex pricelist logic, and this used to work in V15.

**Comment by Feyensv** [comment]
If a rule is based on a pricelist (recursive logic), it will call `_get_product_price` on it, which will call `_compute_price_rule` (cf `_compute_base_price` method) :thinking:.

Edit: considering your screenshot, indeed we only consider the first applicable rule.
The only change from v15 i have in mind is maybe if the first rule gives a zero amount as price, in which case the second rule was maybe considered in v15, but it was quite a strange and complex logic.

**Comment by elmeriniemela** [comment]
@Feyensv Yeah you're right, I just re-did the test in V15 and got the same results when the pricelist has multiple matching items.

I take it that if we want to find the lowest matching product-based rule, it requires customization?

**Comment by Feyensv** [comment]
Well, why would you? the ordering is there for a reason, from the more specific to the less specific rule (and if everything is the same, ordering the rules by decreasing id, which means the latest rule created will take precedence).

So yes, we won't change that behavior in a stable version, and I doubt we plan to change that specific ordering logic anytime soon.  I wouldn't recommend customizing this logic honestly, but it's your choice :D.

**Comment by elmeriniemela** [comment]
We'll have to think about it. Thank you very much for your help! I will close the issue now as this seems to work as intended.
