### ISSUE TITLE
Web Sale and Web Portal Contact form Incorrectly Display Company on street input field

### ISSUE THREAD

**Issue by slevenhagen** [odoo/odoo#11619]
Impacted versions:
9.0
Steps to reproduce:

on web site interface Q-web template error

Opens web URL   shop>>shopingcart click process checkout  
web page url extension   /shop/checkout    page "Your Address"

or similar problem from portal template is at

got to My Account>> click Details

opens web page URL extension /my/account    page  "Contact Details"

Current behavior:

street field  is labeled as Company and not in correct location

Expected behavior:

label field as Street and add  Company field with proper company label

Video/Screenshot link (optional):

Qweb templates effecting these views are at  
website_portal/views/templates.xml at line 90
website_sale/views/templates.xml at line1065

**Comment by odony** [comment]
Closing, this seems to be a duplicate/consequence of #2541, #12541 and many other similar issues.
There is work-in-progress by @JKE-be to improve this in Odoo 10, but it's not a trivial change.

**Comment by eLBati** [comment]
@slevenhagen @odony please see https://github.com/odoo/odoo/pull/14473
