### ISSUE TITLE
[9.0]Pricelist per quantity not applied in Point of Sale

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#11617]
Impacted versions: 

Latest runbot Odoo  point of sale

** Steps to reproduce:

Add pricelist :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/14320033/d1e9a9f8-fc13-11e5-84e8-1f0a784f3b04.jpeg)
Go in the point of sale and ad products

Current behavior:

Price not adapted :
![odoo_v10](https://cloud.githubusercontent.com/assets/1043935/14320150/43363630-fc14-11e5-9a52-2d9ff4c3171e.jpeg)

Expected Behavior:

Price changed accordingly to the quantities

**Comment by jorenvo** [comment]
Hi,

Pricelist features that depend on quantities (or anything else) are not supported by the POS in Odoo 9. When the POS loads it simply loads the products with their price and then uses that, it does not load or use the actual pricelist rules.

Supporting this is something that is on the roadmap for Odoo 10.


Kind regards,
Joren

**Comment by flotho** [comment]
Hi @jorenvo,

really sad news...

Thanks

**Comment by bwilmus** [comment]
Hi Flotho,

On odoo 8 I am using a module to do that. You shoud ask OCA to know if they think upgrade this module to the 9th version or maybe do that job by yourself.

[pos_pricelist](https://www.odoo.com/apps/modules/8.0/pos_pricelist/)

Regards,

Bernard

**Comment by flotho** [comment]
Hi @bwilmus 

Thanks for your feedback, yet pos_pricelist from OCA don't really do what I'm looking for.
I personally financed the port to v9 but the behaviour still the same as Odoo core one in POS, it takes the first rule applied for a product.
As written by @jorenvo :

> Pricelist features that depend on quantities (or anything else) are not supported by the POS in Odoo 9

it's not fully functionnal as in the back office

**Comment by flotho** [comment]
My bad, after multiple tests, it works as expected on runbot for the OCA module
Something wrong should happen in my local conf!
