### ISSUE TITLE
[mrp]: Cost calculation of finished product when real price

### ISSUE THREAD

**Issue by jas-odoo** [odoo/odoo#11614]
Impacted versions: 9.0

Steps to reproduce:
1. Create Manufacture Order and assign routing with work center operation.
2. It will create Work Order.
3. Now finished Manufacture Order by completing all Work Order.
4. See Inventory valuation.

Current behavior:
When Manufacture Order ends on completion of all its related work order, the MO is set to 'done' stage, but inventory valuation is not real time.
If MO ends through wizard of 'Produce' button, Inventory valuation is real time.

Expected behavior:
When all Work Order ends, the MO which is going to be finished have real time inventory value.

**Comment by invitu** [comment]
in v10c, we have real time valuation = zero for products made from BoM

**Comment by Yenthe666** [comment]
Hi @jas-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
