### ISSUE TITLE
When 'group_by'-ing, object's order_by field is ignored 

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#11610]
##### Impacted versions:

8.0 + 9.0
##### Steps to reproduce:
- Navigate to Sales Order / [Quotations (runbot)](http://140664-9-0-20ea4e.runbot8.odoo.com/web#page=0&limit=80&view_type=list&model=sale.order&menu_id=419&action=576)
- See SOs naturally ordered by descending date
  ![so_natural_ordering](https://cloud.githubusercontent.com/assets/5583352/14312371/a65bf846-fbf4-11e5-8e86-19e8250451c1.png)
- Group SOs by Order Month
- See SOs no longer ordered by descending date
  ![so_grouped_ordering](https://cloud.githubusercontent.com/assets/5583352/14312379/ae873e18-fbf4-11e5-83c4-0dce667276f9.png)
##### Expected behavior:

April, then March. As if you clicked twice on Order Date column to sort by Order Date:
![so_correct_ordering](https://cloud.githubusercontent.com/assets/5583352/14312409/e1ef80d0-fbf4-11e5-9fa3-d2b19b68ab2d.png)
##### Quick Fix:
- Add `order_by` to the context of filter declaration:

``` xml
<filter string="Order Month" domain="[]" context="{'group_by':'date_order','order_by':'date_order desc'}"/>
```
- Read `order_by` from the context in `data.js`:

``` diff
diff --git a/addons/web/static/src/js/data.js b/addons/web/static/src/js/data.js
index 95cbf06..0219288 100644
--- a/addons/web/static/src/js/data.js
+++ b/addons/web/static/src/js/data.js
@@ -159,7 +159,7 @@ instance.web.Query = instance.web.Class.extend({
             offset: this._offset,
             lazy: this._lazy,
             limit: this._limit,
-            orderby: instance.web.serialize_sort(this._order_by) || false
+            orderby: instance.web.serialize_sort(this._order_by) || ctx['order_by'] || false
         }).then(function (results) {
             return _(results).map(function (result) {
                 // FIX: querygroup initialization
```

**Comment by pedrobaeza** [comment]
This is a proposal for changing the behavior, so please make a pull request instead of opening an issue.
