### ISSUE TITLE
Shop wrong product prices decimal after quantity change

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#11630]
Impacted versions:
8.0 / 9.0
Steps to reproduce:
1. Change decimal precision of EUR to 0.0001 (or any other different from 0.01)
2. Go to the website shop
3. Click on any product
4. Click + to change product quantity

Current behavior:
- Before click, price is correctyle displayed (for eg. 28.0505 €)
- After de click wrong decimals are displayed (for eg. 28.05 €)

Expected behavior:
- After de click same decimals should be used (for eg. 28.0505 €)

Aditional information:
- Be sure that the currency of the pricelist used on website is EUR or is the one you change precision for
- On v8, it also happens on shop/cart

Video/Screenshot link (optional):
Before click:
![before click](https://cloud.githubusercontent.com/assets/3016656/14357681/163ac072-fcc0-11e5-83d3-ba457db87d1a.png)

After click:
![after click](https://cloud.githubusercontent.com/assets/3016656/14357685/19e7064a-fcc0-11e5-91ac-7f950e3e2bd3.png)

**Comment by JKE-be** [comment]
fixed a long time ago.
