### ISSUE TITLE
Paypal acquirer in multi-website / e-commerce configurations

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#11638]
Impacted versions: 9c and Enterprise

Steps to reproduce:
Using multi-website / e-commerce configurations and Paypal paiement acquirer in a single database.

Current behavior:
The return URL is linked to the web.base.url.
Therefore, despite using different Paypal accounts, the return URL from Paypal is "forced" to the web.base.url root and not the actual website domain.
Eg.: 3 domains web1.com, web2.com, web3.com - when doing a Paypal payment from web3.com, if the web.base.url is web1.com, the return URL will be web1.com/payment/paypal/dpn/ which is obviously raising an error.

Expected behavior:
The return URL should respect the original website domain URL.

**Comment by lem8r** [comment]
This is true for other payment acquirers too

**Comment by aristobulo-eezee** [comment]
@avanzella take a look on this issue https://github.com/odoo/odoo/issues/12429

**Comment by lukebranch** [comment]
@Yenthe666 ,

Would you mind taking a look at this?

I am getting the same paypal issue on a single domain, single database setup.

I've just received an email back from PayPal regarding the issue, and here's their reply:

```
Hi,
This is an issue with your return url. I have looked at the given transaction ID #XXXXXXXXXXXXXXXXX and I could see that once the payment is completed, PayPal should redirect buyer to this url http://yourdomain.com/payment/paypal/dpn/ 

However, this url does not seem valid and working. I would suggest you to reach out to your web developer to further check on your return url.
```

**Comment by lukebranch** [comment]
@Yenthe666 ,

Would you mind taking a look at this?

I am getting the same paypal issue on a single domain, single database setup.

I've just received an email back from PayPal regarding the issue, and here's their reply:

```
Hi,
This is an issue with your return url. I have looked at the given transaction ID #XXXXXXXXXXXXXXXXX and I could see that once the payment is completed, PayPal should redirect buyer to this url http://yourdomain.com/payment/paypal/dpn/ 

However, this url does not seem valid and working. I would suggest you to reach out to your web developer to further check on your return url.
```

The return URL results in a 'Method Not Allowed' error page as shown in the screenshot below:

<img src="https://cloud.githubusercontent.com/assets/2337666/16537868/8ef6c9fe-4043-11e6-889d-9501de4324cd.png"/>

I will try later today and see if I can reproduce this on the runbots.

**Comment by Yenthe666** [comment]
@mart-e looks like another PayPal issue. Can you assign somebody on this please? Not sure who is responsible for PayPal.

**Comment by mart-e** [comment]
The multi-domain is not something supported as it is known to get this kind of issues. It's something we have to work on but now a lot of modules uses indeed the web.base.url.

@lukebranch your issues looks different so please open another issue with the given steps to reproduce. And the request `/payment/paypal/dpn/` will only work in POST request, so it's paypal that must make this request in POST when the transaction is completed. Accessing directly the URL (GET) will not work.

**Comment by lukebranch** [comment]
@mart-e ,

Thanks. In that case once i've got clear steps to reproduce i'll open a new issue.

**Comment by lolziac** [comment]
@lukebranch 
I think your issue is related with this one https://github.com/odoo/odoo/issues/13834 
This makes paypal unusable ... Is paypal working for anybody on v10

**Comment by jl2035** [comment]
@lukebranch 

"Is paypal working for anybody on v10"

+1 to this question!

**Comment by lukebranch** [comment]
@jl2035 @lolziac ,

I would suggest pulling the latest code and trying again. See @Yenthe666 's comment here for the related commit:

https://github.com/odoo/odoo/issues/14727#issuecomment-303730269

**Comment by mr-module** [comment]
Is it possible to use different payment gateway for multi websites
suppose I have 4 websites I want 2 websites have - Wire Transfer and other 2 have - Paypal ??
Can we do that?

**Comment by JKE-be** [comment]
@mr-module 
Yes since v12 you can do it
Please use forum for functionnal question and not thé issue tracker.
