### ISSUE TITLE
Contacts Name Field is too short.

### ISSUE THREAD

**Issue by selmanfarukyilmaz** [odoo/odoo#116320]
Impacted versions: odoo 16

Steps to reproduce: Go to Contacts

Current behavior: Name Field is too short

Expected behavior: It should be long

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/96119894/227177645-31a52fb7-b3fd-464a-86df-daf68682a269.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
Hi,
It is fixed by this commit: https://github.com/odoo/odoo/commit/b9788544b7101e5a202cf87989bc3f5fc0495249

You may have to pull the latest source code
