### ISSUE TITLE
[15.0][16.0] purchase_stock: purchase order line quantity decrease & unit price increase/decrease in multi-currency: return is created

### ISSUE THREAD

**Issue by vincent-cowboy** [odoo/odoo#116350]
Impacted versions: 15.0, 16.0

Steps to reproduce:
1. On a demo database with company currency set as USD, activate currency EUR
2. Create a new RFQ and set the currency as EUR
3. Add a product with _q_ quantity (arbitrarily chosen 20)
4. Confirm Order
5. Decrease quantity and increase (or decrease) Unit Price 
6. Save
7. An additional Transfer/ `stock.picking` (Type of Operation: Delivery) is created

Current behavior:
An additional Delivery transfer is created when decreasing quantity and increasing (or decreasing) unit price on a Purchase Order.
The Receipt Demand quantity doesn't change.

Expected behavior:
The Receipt quantity should be decreased to the quantity set on the purchase order line.
No additional Transfer/`stock.picking` should be created

Video/Screenshot link (optional):
- 15.0, local database with demo data and `purchase_stock` installed: 

https://user-images.githubusercontent.com/92734094/227199861-765eb506-ce2f-4be1-a4ef-1b0373eab984.mov

- 16.0, on a demo.odoo.com database: 

https://user-images.githubusercontent.com/92734094/227200068-9af01d3a-1c62-4e9c-988c-dec66df5d29f.mov

Support ticket number submitted via odoo.com/help (optional):
N/A

Commit that introduced this behaviour: https://github.com/odoo/odoo/commit/98984cf92c99534117cfbbac99e5ca2110221217 

I am unsure if it is a use case and behaviour that is wanted, but I'm just assuming a user would want to be able to decrease quantity and increase (or decrease) unit price on a purchase order line (let's say a supplier pricelist impact the unit price when decreasing the quantity) without having a return created

(cc @HANNICHE-Walid, @adwid, @Whenrow)

**Comment by HANNICHE-Walid** [comment]
hi @vincent-cowboy thanks for reporting this issue I will look into it
