### ISSUE TITLE
Installing "Theme Support Engine (website_less) module" results in "invalid option: --clean-css"

### ISSUE THREAD

**Issue by rosnk** [odoo/odoo#11649]
Impacted versions: Odoo 8.0 in Mac OS (Yosemite)

Steps to reproduce:  Installing "Theme Support Engine (website_less) module" in odoo 8.0 results in error: "invalid option: --clean-css". 

I have tried installing "less" and "less-plugin-clean-css" using this command: 
 sudo npm install -g less less-plugin-clean-css

Current behavior:   

It seems like system is somehow looking into " rbenv gem" instead into "globally installed using npm" 

`/Users/roshankarki/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/less-2.6.0/bin/lessc:83:in `<top (required)>': invalid option: --clean-css (OptionParser::InvalidOption)\A from /Users/roshankarki/.rbenv/versions/2.2.2/bin/lessc:23:in `load'\A from /Users/roshankarki/.rbenv/versions/2.2.2/bin/lessc:23:in `<main>'\A This error occured while compiling the bundle 'website.assets_frontend' containing:\A - /website_less/static/src/less/import_bootstrap.less\A - /website_less/static/src/less/colors.less\A - /website_less/static/src/less/website.less";`

Expected behavior:

It should not be showing this error. 

Video/Screenshot link (optional): N/A

**Comment by sle-odoo** [comment]
The default lessc in your path is not the nodejs one. You have to fix that either by removing the ruby one or by changing the path priority.

Regards
