### ISSUE TITLE
[9.0C & 9.0E] Unable to create projects that are available to portal users

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11643]
Impacted versions: 9.0 community and Odoo 9 Enterprise

Steps to reproduce:
 - Create a new user 'ExampleUser', with the settings 'Contact Creation', 'Public' and 'Portal' on:
![image](https://cloud.githubusercontent.com/assets/6352350/14385954/1c394f8c-fda3-11e5-874f-d382f55bb59f.png)

 - Create a new project 'Demo project' and apply the option "Customer Project: visible in portal if the customer is a follower":
![image](https://cloud.githubusercontent.com/assets/6352350/14385970/37ad2e3c-fda3-11e5-9056-2805fe532b3e.png)

 - Add this user as a follower on the project
 - Create a new task on the project, that is defined in stage, for example "Example Task" and add the same customer as a follower:
![image](https://cloud.githubusercontent.com/assets/6352350/14386036/71846f26-fda3-11e5-9dcd-089849a77841.png)

 - Login with the user "ExampleUser" and go to "My Account". You won't see project tasks anywhere:
![image](https://cloud.githubusercontent.com/assets/6352350/14386074/9b7e3cb2-fda3-11e5-8469-ce2b508c4464.png)

Current behavior:
The public projects are not shown in the portal, they are only accessible through the menuitem "Claims" in place of "My Account".

Expected behavior:
All project tasks show up under "My Account".

**Comment by Yenthe666** [comment]
@mart-e could you give your feedback on this? I might be wrong with this one.

**Comment by mart-e** [comment]
Hello,

It looks like you are mixing portal and public users. Portal are the one that connect on the `/web` url with a very restricted access while public is for the frontend website ("My Account" page).

**Comment by Yenthe666** [comment]
@mart-e I was just under the impressions that a customer attached to a project could see all the tasks of this project on his portal. This doesn't seem to be the case? Just like you can see all project issues as a customer.

**Comment by mart-e** [comment]
We don't have a public project page (we have `website_project_issue` for the "Your issues" section).
We had a crappy `website_project` in 8.0 not really usable but then https://github.com/odoo/odoo/commit/60514d0d0d7254c17ecebad99423f26fd4138d8e happened and we no longer have this.
Maybe it will be back in the future but we don't have this now. Tagging as wishlist.

So what you are looking for is the portal access, not the public.
![screenshot from 2016-06-01 15-15-24](https://cloud.githubusercontent.com/assets/564822/15710776/b1d902ca-280b-11e6-834c-fdfae662d6ae.png)

**Comment by Yenthe666** [comment]
Ahh yes, I was talking about `website_project ` from 8.0.
Alright thanks for the information. It would be very neat to have this in the website too though, just like project issues but then for tasks.
