### ISSUE TITLE
Consultation supplier invoices

### ISSUE THREAD

**Issue by vipvalen** [odoo/odoo#11640]
**Impacted versions:**
8.0

**Steps to reproduce:**
When we entered the Provider tab to view your bills, we enter through the button "Supplier Invoice"

**Current behavior:**
does not show the corrective invoices
**
Expected behavior:**
Show sales invoices and corrective invoices

**Comment by Yenthe666** [comment]
Hi @vipvalen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
