### ISSUE TITLE
[9.0"]Menu "Order Date"shoule be  "Order Month"

### ISSUE THREAD

**Issue by fenshuajiang** [odoo/odoo#11650]
Impacted versions:
Odoo9.0
Steps to reproduce:
See Picture
Current behavior:
Order Date
Expected behavior:
Order Month
![e9k2h 1 z 5h2w06lu8 df](https://cloud.githubusercontent.com/assets/7471985/14413799/9faad94c-ffb7-11e5-9080-8014fc77186b.jpg)

**Comment by Yenthe666** [comment]
Hi @fenshuajiang,

Thank you for the suggestion.
In the formview this same field however is shown and there you input the exact date. In the form we're showing the datetime including day and hours, minutes, seconds. If this behaviour would be changed all the formviews would be messed up so the current option is the better of the both.

Regards,
Yenthe
