### ISSUE TITLE
Leaf with 2many element has unexpected and limitating behaviour

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#11661]
Impacted versions:
v9

Steps to reproduce:
Evaluate two domains:
Pseudocode...
- `dom1 = ('model.2manyfield', 'in', ['whatever list is appropriate'])`
- `dom2 = ('model.2manyfield', 'not in', ['whatever list is appropriate'])` which is strictly equivalent to `dom2 = '!', ('model.2manyfield', 'in', ['whatever list is appropriate'])` - I think the latter get's internally transformed into the former, IIRC.

Current behavior:

You may see that in the case, in which `model` has more records in `2manyfield` you will obtain (mathematical) set A from the first domain but you will not obtain (mathematical) set !A from the second domain. This is because the interpretation of '!' or 'not' in the case of a `2manyfield` reads as follows:
" Result true if **any** of the values in `2manyfield` satisfies the condition. "
In order to be able to construct mathematical set !A we would need the following:
" Result true if **all** of the values in `2manyfield` satisfies the condition. "

The use case is the domain evaluation for accounting formula. It is quite easy to construct a case where you need to have a set !A, for example if you want to capture a residual value, which has not been taken into account by any previous (more detailed) rules.

Expected behavior:
see above.

Video/Screenshot link (optional):

@rco-odoo (for ORM related issue)
@qdp-odoo (for accounting/reports related issue, use case)

@kurkop (fyi)

**Comment by blaggacao** [comment]
@rco-odoo I'm still hitting this on V10, actually.

**Comment by blaggacao** [comment]
By adding a single tag to the corresponding account, I would break https://github.com/odoo/enterprise/blob/10.0/account_reports/data/account_financial_report_data.xml#L485 because of this...

**Comment by gdgellatly** [comment]
Funnily enough I ran into exactly this issue in reverse in blogs. I just
broke the domain up into individual items.

**Comment by blaggacao** [comment]
@gdgellatly I was think to do this, but I cannot, because there is no way to construct !A (as in "negation of set A")
Any of 
```xml
('account_id.tag_ids', 'not in', [ref('account.account_tag_financing')]),
('account_id.tag_ids', 'not in', [ref('account.account_tag_investing'))])
```
 
```xml
'!', ('account_id.tag_ids', 'in', [ref('account.account_tag_financing')]),
'!', ('account_id.tag_ids', 'in', [ref('account.account_tag_investing'))])
```
does not construct !A (['!' is normalized, anyhow](https://github.com/odoo/odoo/blob/10.0/odoo/osv/expression.py#L249))

**Comment by mart-e** [comment]
Hello,

This is an old issue in the way the ' not in' operator is computed.
As you showed in your example, a simple `('country_id.state', 'not in', ['California'])` is not expected to return USA but it does.

It would probably be a good change to do what you expect but it is a non-trivial change. It will also most likely break backward compatibility on some domains (so definitely master).

To be discussed with @rco-odoo, @odony and @antonylesuisse

**Comment by blaggacao** [comment]
Hi this is pretty annoying for the account reporting, as it leads implicitly to **pretty** awkward UX.

As a result of this limitation I can not genuinely construct two sets, but rather need to create one set and then derive the other one by substraction... So far so good.
Then again, if I use groupby let's say `partner_id`, the user will see all move lines constituting a specific row (the ones that add *and* the ones that substract).

This is pretty confusing and cannot really be worked around... This is a **huge** limitation for the account reports feature...
/cc @qdp-odoo

**Comment by blaggacao** [comment]
Ticket: 1818857

**Comment by blaggacao** [comment]
@mart-e The issue might be different...

Look how: 
```
('tax_ids.tag_ids', 'not in', [1,2,3,4])
```
Translates into: 
```
WHERE ("account_move_line"."id" in (SELECT "account_move_line_id" FROM "account_move_line_account_tax_rel" WHERE "account_tax_id" IN (LIST OF TAXES THAT DO NOT HAVE THE TAGS))))'
```

While the 2nd step in the hierarchy returns relates correctly a list of taxes that do no have the tag (except None, see: #15668) the first hierarchy level just mixes things up (only if 2many hierarchy) as it does not implement the negation in any way...

**Comment by blaggacao** [comment]
@pedrobaeza As far as I know this (and related issues) is still a long standing limitation.
You can imagine the lift it would provide for current reporting constraints. So far that it might even affect end customer happiness positively...

**Comment by mart-e** [comment]
Hello,

The feedback is still present and no decision was taken yet, I can't tell you if/when we will do it but it is still pending.
Changes in the ORM are never easy...

**Comment by pedrobaeza** [comment]
OK, then I keep it opened for now until there's a decision.

**Comment by Yenthe666** [comment]
@mart-e has any decision been made in the meanwhile?
