### ISSUE TITLE
[16.0] analytic_distribution only can be accessed by Technical / Analytic Accounting group

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#116684]
Impacted versions: 16.0

Steps to reproduce:
- Create new group, and set access right to analytic_distribution model (e.g. only read and write)
- analytic_distribution field couldn't be displayed for users of the new group

Current behavior:
with current design, analytic_distribution fields in sales order, purchase order, invoices, etc., is only can be accessed by users who registered as a member of Technical / Analytic Accounting group's member. 
In some case, there's some users which in daily operations is in charge to assign analytic account on the analytic_distribution field, but should not have create access to save the analytic distribution.  
<img width="696" alt="create access" src="https://user-images.githubusercontent.com/122415281/227941604-70892bbb-62a6-4875-ba25-5bee8c00b41d.png">

in this case, we cannot add a new group to have access only to read and write the field. because in the views, analytic_distribution is set to  Technical / Analytic Accounting only.
<img width="576" alt="analytic_distribution in views" src="https://user-images.githubusercontent.com/122415281/227940785-9d77dd07-fd5c-45cf-b097-5f5827b46dcc.png">

Expected behavior:
analytic_distribution field can be access by another group so that we can specify which users could have full access to the field and which users who could only have few access according to the business needs.

Video/Screenshot link (optional):
1. assign users who only have read & write access to analytic_distribution by create another group:
https://drive.google.com/file/d/1Ub1MmTZDnuy-8O3325Snpm5pEHWW4YxI/view?usp=sharing

2. This also can prevent users to unintentionally set some analytic distribution as default value of some partner:
https://drive.google.com/file/d/1YhFkzZFTtJfwLSprs1cP4phlIBIpsNXH/view?usp=sharing

@qrtl 

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
Once you start to customize the access rights, you need sometimes to customize view too.

You can easily add a inherited view that remove the group
```xml
<field name="analytic_distribution" position='attributes'>
   <attribute name='groups'>xxx</attribute>
</field>
```

or
```xml
<field name="analytic_distribution" position='attributes'>
   <attribute name='groups' add="yournewgroup"/>
</field>
```

If you need more help, don't hesitate to ask to community https://www.odoo.com/forum/aide-1
It is not considered as a bug.
