### ISSUE TITLE
When we are doing transactions between web browser and OpenERP server probably it can exist internet disconnection or intermittent service of internet, this can produce inconsistency troubles on the data because the “on_change” method doesn’t return the correct information, this means the method doesn’t return any value because of the disconnection with the server.

### ISSUE THREAD

**Issue by patriciorangles** [odoo/odoo#11678]
Impacted versions:
7.0

Steps to reproduce:
[problema intermitencia.pdf](https://github.com/odoo/odoo/files/215621/problema.intermitencia.pdf)

Current behavior:
The form leave the old data and the user can save it, this produce inconsistency of data

Expected behavior:
The web client should show a message saying: The connection from the server was lost also the last request too, Please retry the last request or refresh the page.

Video/Screenshot link (optional):

**Comment by pepetreshere** [comment]
I should add that the error is severe, as it affects the integrity of the data, for instance imagine the big inconsistency that might happen if the onchange method of a list price is not returned, it could cause you to be selling with incorrect prices!.

I have thinked of 2 solutions:
- Use javascript to capture the error and cause a click on the "discard" button, which will force the user to redo everything but will keep the data integrity
- Use javascript to keep the last onchange call in memory, if it raises an error then the user should be allowed to either retry the method or discard the changes (as discarded in option 1).

I would appreciate any advice on other approaches or on a suggestion on ways to implement it.

Best Regards

Andres Calle
TRESCLOUD

**Comment by phoenixsampras** [comment]
This problem has to do with usability and with the nature of asynchrony in Web Browsers technology, since the internet is down, the user should REFRESH the window to get the complete information. Would be nice if in the error popup, clicking 'OK' the window refreshes automatically, ensuring the consistency of the information.

On change, depends on Javascript, then again, its asynchronous. It's not a desktop app.

**Comment by Yenthe666** [comment]
Hi @patriciorangles ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
