### ISSUE TITLE
[9.0] payroll_account: wrong partner_id on move line

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#11675]
Impacted versions: 9.0

Steps to reproduce:

Define two salary rules:
1. Salary wage which will debit expense account and credit salary payable account
2. Tax deductible rule which will debit salary payable account and credit tax payable account. Contribution register with proper partner_id should be set.

Try to compute payslip and make account move.

Current behavior:

Let's say wage is 1000 and tax deducted is 10%

| Line | Account | Debit | Credit | partner_id | Origin |
| --- | --- | --- | --- | --- | --- |
| 1 | expense account | 1000 |  | False | salary rule |
| 2 | salary payable |  | 1000 | employee_id.address_home_id | salary rule |
| 3 | salary payable | 100 |  | register_id.partner_id | tax rule |
| 4 | tax payable |  | 100 | register_id.partner_id | tax rule |

The problem is with line 2 and 3. Same account has two moves with different partner_id which can't be properly reconciled with bank statement when actual amount of 900 will be payed to employee.

Expected behavior:

| Line | Account | Debit | Credit | partner_id | Origin |
| --- | --- | --- | --- | --- | --- |
| 1 | expense account | 1000 |  | False | salary rule |
| 2 | salary payable |  | 1000 | employee_id.address_home_id | salary rule |
| 3 | salary payable | 100 |  | employee_id.address_home_id | tax rule |
| 4 | tax payable |  | 100 | register_id.partner_id | tax rule |

This issue can be addressed by modifying `_get_partner_id` function https://github.com/odoo/odoo/blob/9.0/addons/hr_payroll_account/hr_payroll_account.py#L18

from this

``` python
    def _get_partner_id(self, cr, uid, payslip_line, credit_account, context=None):
        """
        Get partner_id of slip line to use in account_move_line
        """
        # use partner of salary rule or fallback on employee's address
        partner_id = payslip_line.salary_rule_id.register_id.partner_id.id or \
            payslip_line.slip_id.employee_id.address_home_id.id
        if credit_account:
            if payslip_line.salary_rule_id.register_id.partner_id or \
                    payslip_line.salary_rule_id.account_credit.internal_type in ('receivable', 'payable'):
                return partner_id
        else:
            if payslip_line.salary_rule_id.register_id.partner_id or \
                    payslip_line.salary_rule_id.account_debit.internal_type in ('receivable', 'payable'):
                return partner_id
        return False
```

to this (else block changed)

``` python
    def _get_partner_id(self, cr, uid, payslip_line, credit_account, context=None):
        """
        Get partner_id of slip line to use in account_move_line
        """
        # use partner of salary rule or fallback on employee's address
        partner_id = payslip_line.salary_rule_id.register_id.partner_id.id or \
            payslip_line.slip_id.employee_id.address_home_id.id
        if credit_account:
            if payslip_line.salary_rule_id.register_id.partner_id or \
                    payslip_line.salary_rule_id.account_credit.internal_type in ('receivable', 'payable'):
                return partner_id
        else:    # if debit, set employee id if any
            if payslip_line.slip_id.employee_id.address_home_id and \
                    payslip_line.salary_rule_id.account_debit.internal_type in ('receivable', 'payable'):
                return payslip_line.slip_id.employee_id.address_home_id.id
        return False
```

**Comment by lem8r** [comment]
Yes, same as issue with analytic accounts on both lines.

https://github.com/odoo/odoo/blame/9.0/addons/hr_payroll_account/hr_payroll_account.py#L10-L31

![default](https://user-images.githubusercontent.com/5942291/39246285-c7168e36-489e-11e8-972c-d47c99f169ee.png)

**Comment by Yenthe666** [comment]
Hi @lem8r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
