### ISSUE TITLE
[9.0] hr_timesheet - unable to add timesheet for other employee

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#11677]
**Impacted versions:** 9.0

**Steps to reproduce:**
1. open timesheet app
2. new timesheet
3. select Employee
4. select analytic account and add line
5. enter hours worked for employee
6. Save timesheet  
7. After the save the hours are not displayed for the employee, nor are they recorded.

have tried this with users that are HR manager, admin and direct manager

**Current behavior:**
the problem is that I (or anyone else who is HR-Manager or direct manager) can not add timesheet for the workers. 
when doing that it results in 0 hours (like in the screenshots attached)
the user alejandro is attached to an odoo user. But i (arjan) am his direct manager in odoo, as well as i have the HR manager rights.

ps: adding my own hours working as intended

**Expected behavior:**
So i would asume, i could enter his timesheets into the system. (i can think of many situations in which a manager should/could do that)

**Video/Screenshot link (optional):**
![2016-04-11_15-35-16](https://cloud.githubusercontent.com/assets/7501203/14471264/4f9ac60e-00b3-11e6-9b5f-5364d6b1374c.png)
![2016-04-11_15-33-16](https://cloud.githubusercontent.com/assets/7501203/14471265/4fa168ce-00b3-11e6-8cb8-85337f5df211.png)
![2016-04-11_15-33-43](https://cloud.githubusercontent.com/assets/7501203/14471266/4fa7842a-00b3-11e6-9ccc-b5809a284cda.png)

**Comment by aduijs** [comment]
Tested this in clean install with DEMO data installed - Same behavior
Tested this in clean install with just timesheet installed - Same behaviour

observation:  when hitting the save button it seems to register right. 
But when the pages refreshes it does show there has been added a timesheet, but there arent any hours attached to it (thus showing 0)
However, the hours are recorded since the analytic account is showing them.

Hope this can help locate the issue

**Comment by Yenthe666** [comment]
Hi @aduijs,

Thanks a lot for your report.
I've just tried this on the latest Odoo 9 with an user named "Yenthe". I've booked timesheets for both my own user (Yenthe) and for a second user (James) and it all works fine:
![image](https://user-images.githubusercontent.com/6352350/34949155-970f705a-fa0f-11e7-9ce3-e323854746d7.png)
Please update your Odoo source code to fix this.

Regards,
Yenthe
