### ISSUE TITLE
[8.0] Evaluation mode: empty database generated, no Module / Demo Data

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#11680]
**Impacted versions:** 8.0

**Steps to reproduce:** generate database with demo data (check evaluation mark in DB-Manager)

**Current behavior:** empty database generated, no Module / Demo Data installed

**Expected behavior:** generation of database with modules + demo data

**OS:** Ubuntu 14.04 Server

Both methods of odoo-installation show the current behavior as described above:
**Method 1:** Installation via Install-Script for [v8](https://github.com/aschenkels-ictstudio/odoo-install-scripts/blob/8.0/ubuntu-14-04/odoo_install.sh), as well as for [v9](https://github.com/aschenkels-ictstudio/odoo-install-scripts/blob/9.0/ubuntu-14-04/odoo_install.sh) with `OE_VERSION="8.0"`.
**Method 2:** Installation via [odoo repository](https://nightly.odoo.com/), steps as root: `echo "deb http://nightly.odoo.com/8.0/nightly/deb/ ./" >> /etc/apt/sources.list && apt-get update &&  apt-get install libjpeg-dev odoo` _(libjpeg-dev is a missing dependency producing dpkg-error on install if missed)_

output of /var/log/odoo/\* does not show any helping messages.

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
This issue should have been fixed quite a while before I made this comment though.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
