### ISSUE TITLE
[9.0]an error occurred when group the purchase order with 'Expected Date' 

### ISSUE THREAD

**Issue by fenshuajiang** [odoo/odoo#11687]
Impacted versions:
Odoo9.0c

Steps to reproduce:
![qq 1](https://cloud.githubusercontent.com/assets/7471985/14492874/c0709bd6-01b4-11e6-96cf-1d82cf3852d8.png)

Current behavior:
![qq 2](https://cloud.githubusercontent.com/assets/7471985/14492884/cf13bc54-01b4-11e6-9b17-06fd645b7bd7.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @fenshuajiang,

Thank you for your report.
This issue has been fixed in the meanwhile as this field was removed from the `groupby` options:
![image](https://user-images.githubusercontent.com/6352350/34948584-dfaeef7c-fa0d-11e7-8731-fe05380402f2.png)

Regards,
Yenthe
