### ISSUE TITLE
[Odoo][8.0] Number of leave requests to validate is not refreshed after validation 

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#11683]
Impacted versions:

At least 8.0

Steps to reproduce:

See https://youtu.be/V-69GCEtkWI

Current behavior:

Currently, the number of leave requests to validate is not refreshed immediately after validation on the related menu item.

Expected behavior:

As it works on other menu item like Application (at the end of https://youtu.be/V-69GCEtkWI), the number of leave requests to validate should be immediately refreshed after validation.

Video/Screenshot link (optional):

https://youtu.be/V-69GCEtkWI

**Comment by adrienpeiffer** [comment]
OPW 674550

**Comment by beledouxdenis** [comment]
Hello Adrien,

The difference between the applications and the requests to approve is the fact the need action for the first is based on the unread messages in the thread, while the second is a needaction based on a search (with a specfic domain) query.

For the first case, for the needaction based on the messages thread, the update of the notification number is implemented, while it's not for the second.

However, we do not consider this issue as a blocking bug, preventing a user to perform his business. We therefore won't solve it in a stable release such as 8.0, as the risk to introduce a regression is much higher than the added value this correction would bring.
To know more about our stable policy, you can read the below documentation:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

We hope you will understand.

Regards,
