### ISSUE TITLE
[9.0] kanban List view , show only per page max records, can't click on next page button

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#11690]
Impacted versions: 9.0c-20160412 

Steps to reproduce:
- click in sale >> clients
- create more than 40 records
- load page again or go to another place and return.

Current behavior:
-Example, if i have 70 records, list view says 1-40/40.
- if click on list, shows all 70 records.
- if i click on kanban again, shows 1-40/70 
- now i can click on next page button

Expected behavior:
-In a example with 70 records.
- If first load clients must be 1-40 /70 records
- Button enabled

Video/Screenshot link (optional):

**Comment by aab-odoo** [comment]
Introduced by https://github.com/odoo/odoo/commit/6859c8dacb4adeb24fdeab619a8f6e4fd48481a0

**Comment by ged-odoo** [comment]
this bug should be fixed by commit: https://github.com/odoo/odoo/commit/9b54b042a03564b8f808b0fff292573a73ef3044

Thank you for your help.
