### ISSUE TITLE
v16 SH rife with issues, Odoo tells you to pay for a fix

### ISSUE THREAD

**Issue by cub-nick** [odoo/odoo#116915]
Odoo v16 is rife with issues.  Been trying to upgrade since they released in mid-January and still can't do it because of all the issues.

Now, Odoo's M/O is to tell customers to pay for a Success Pack to fix it.

To be clear, I have no custom modules or integrations. The only customization done is through the Studio app— which is supposed to be supported.  I just moved over to SH for this v16 testing.  I was able to upgrade from v14 to v15 Online with virtually no problem.  So, not sure if this is an SH thing or v16...

But being told over and over again that I need to pay for a Success Pack to fix an issue that is clearly an issue with the updated code/version— is beyond frustrating. This policy needs to stop immediately.  Take responsibility for your code and support your customers.

**Comment by WeronikaBorsukowska** [comment]
@cub-nick cause odoo is shitty. When I write them on LinkedIn that having 3k reported bugs is not acceptable, they literally say that they only fix bugs reported by paying users.

**Comment by cub-nick** [comment]
@WeronikaBorsukowska well I am a paying customer and they still tell me to pay for a fix!

**Comment by Primary-Pineapple** [comment]
@cub-nick - Here, let me outline step by step how to replicate the issue, only for Odoo "Support" to not follow the replication steps. When pointing this out the reply is complete dismissed lol. #cantreplicate because didn't follow the steps. 

*banging my head against the wall*

![image](https://user-images.githubusercontent.com/36147901/228691911-0602622d-ee55-4d7e-b9d1-e2133a1e397b.png)

**Comment by Primary-Pineapple** [comment]
@cub-nick - Or this beauty, where in v16 you can no longer rename Bank Statements for some reason? and now when you could do it V12/13/14/15 and not in 16 they have to 'evaluate' if its a new feature?

![image](https://user-images.githubusercontent.com/36147901/228692225-c073ff71-bb72-449d-9305-8dd85ff03555.png)

Don't worry though, buy a success pack and we will fix it.

![image](https://user-images.githubusercontent.com/36147901/228692272-5457c2af-3109-4fc8-b4fa-977f0c3d264c.png)

**Comment by Primary-Pineapple** [comment]
@cub-nick - Completely dismisses the issue, until we ask "Why" it's the standard behaviour, then suddenly we log a bug?

![image](https://user-images.githubusercontent.com/36147901/228692686-47dee3f5-b4d6-4a6c-b4db-85d12e44ed00.png)

**Comment by WeronikaBorsukowska** [comment]
@Primary-Pineapple thank you for showing how idiotics they are

**Comment by mart-e** [comment]
Thanks guys for the constructive discussion. The support is doing the best it can, thank you to stay polite.
