### ISSUE TITLE
[9.0]Global discount is not applying because of category based discount.

### ISSUE THREAD

**Issue by dev6intellial** [odoo/odoo#11696]
**Impacted versions:**9.0

**Steps to reproduce:**
I have created an discount rule is pricelist for all product like shown below.
![4-14-2016 3-47-58 pm](https://cloud.githubusercontent.com/assets/10939916/14525032/34d247b4-0259-11e6-817e-f5ce92364cae.png)

After that a created a rule for category based product like this way.
![4-14-2016 3-48-24 pm](https://cloud.githubusercontent.com/assets/10939916/14525033/34d83e62-0259-11e6-93b4-6e1631c93580.png)

Now global discount is not applying on above category product, only category discount is applied.

I want 5% discount on product then 60 % discount.

for example if price is 10 then price should be 3.8, but it is not working.

So suggest me how to do so?

**Current behavior:**

Global Discount is not applying.

**Expected behavior:**

Global Discount should apply

**Video/Screenshot link (optional):**

![4-14-2016 3-47-58 pm](https://cloud.githubusercontent.com/assets/10939916/14525032/34d247b4-0259-11e6-817e-f5ce92364cae.png)
![4-14-2016 3-48-24 pm](https://cloud.githubusercontent.com/assets/10939916/14525033/34d83e62-0259-11e6-93b4-6e1631c93580.png)

**Comment by masuagt** [comment]
Did you find a solution ?

**Comment by pedrobaeza** [comment]
Category or product discounts have more priority than global one, and they are not accumulative. Closing as no real issue, but misunderstanding on how this works.
