### ISSUE TITLE
Filter on Many2many fields (not contains, is not equal to) does not work well

### ISSUE THREAD

**Issue by mh-manatec** [odoo/odoo#11706]
Impacted versions: 8.0

Steps to reproduce:
1. Add in res.partner two tags "test" and "duck" -save
2. add advanced filter: Tags doesnt't contains 'duck' - apply the filter
3. the partner with the two tags "test" and "duck" is listed

**Comment by Yenthe666** [comment]
Hi @mh-manatec,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
