### ISSUE TITLE
[8.0] onchange of date returns date in wrong format

### ISSUE THREAD

**Issue by stijnh92** [odoo/odoo#11709]
Impacted versions: 
Tested on runbot 8.0 (commit dc3f1e22117aafbc1342a2ea1a8902072edaeb4e)

Steps to reproduce: 
Set the language to dutch (nl_BE).
In any date-field that has an onchange listener, fill in the date manually in Belgian format (DAY,MONTH,YEAR).
You can try this for the date_due field on customer invoices.
For example: 04062016 (=June 4, 2016) . In the onchange, the value returned will be 2016-04-06.
This will return the date in the format YEAR-DAY-MONTH.
Next, fill in the date 13062016 (=June 13, 2016). In the onchange, the value return will be 2016-06-13.
So now the date format is YEAR-MONTH-DAY.

When I am trying to do something with dates in my code, I can not format it to a python date format because I do not know what the format of this date is.

Current behavior: 
Date in onchange is returned in different date formats.

Expected behavior: 
Always the same date format.

Video/Screenshot link (optional):
Scenario 1: 06042016 (April 6, 2016)
![selection_001](https://cloud.githubusercontent.com/assets/8638753/14552986/3e0327ba-02e3-11e6-9007-48ade28fa39d.png)

Scenario 2: 14042016 (April 14, 2016)
![selection_002](https://cloud.githubusercontent.com/assets/8638753/14552988/4338eb70-02e3-11e6-9548-4e98681f7b43.png)

**Comment by Yenthe666** [comment]
Hi @stijnh92 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
