### ISSUE TITLE
DHL Integration Issue: When we checked all the Delivery Integration ( DHL, FedEx, USPS, UPS) at that time DHL is showing IndexError: Index out of range.

### ISSUE THREAD

**Issue by GetOdoo** [odoo/odoo#11702]
Impacted versions: Odoo Enterprise Version 9

Steps to reproduce: Checked all the Delivery Integration (DHL, FedEx, USPS, UPS) and then use DHL for delivering a product.

Current behavior: IndexError

Expected behavior: It should work without any error.

Video/Screenshot link (optional):
![odoo_dhl error](https://cloud.githubusercontent.com/assets/15212642/14527573/8e9f5b38-0268-11e6-919b-528d53c1f933.png)

**Comment by rim-odoo** [comment]
@GetOdoo In order to troubleshoot properly delivery carriers, you must add the shipper/recipient addresses you used for testing. DHL integration may fail with some adresses, and work with some others.
