### ISSUE TITLE
[8.0] Does not work with Chrome 50.0.2661.75

### ISSUE THREAD

**Issue by bartekwojcicki** [odoo/odoo#11712]
Impacted versions: 8.0

Steps to reproduce: open odoo 8.0 instance in Chrome 50.0.2661.75

Current behavior: page is not rendered properly
![selection_071](https://cloud.githubusercontent.com/assets/5853558/14555732/5cf87c68-02f4-11e6-80b4-98b90ef2d5fa.png)

Expected behavior: like in Firefox
![selection_072](https://cloud.githubusercontent.com/assets/5853558/14555776/99f90a74-02f4-11e6-9657-65d4335c9a6e.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@bartekwojcicki fixed with this one: https://github.com/odoo/odoo/commit/00ead29c7c1877de94be8c28bd587fa7acedcc69

**Comment by Yenthe666** [comment]
Possible related to this one: https://github.com/odoo/odoo/issues/11629

**Comment by wtaferner** [comment]
@Yenthe666 
I tried to forward port it but it is a larger issue than just v8. Even the Enterprise version is having issues b/c of Chrome 50.

**Comment by bartekwojcicki** [comment]
Thanks a lot, this one can be closed as duplicate.
