### ISSUE TITLE
Company contacts are lost when changing company address

### ISSUE THREAD

**Issue by lannex-alex** [odoo/odoo#11724]
Impacted versions: http://142672-9-0-42e3a8.runbot8.odoo.com

Steps to reproduce: Create a company with 41+ Contacts and Change the company address

Current behavior: When Changing the address you loose all the contacts over the first 40, the first 40 contacts remain in the database but the rest disappeared. This bug seems to be directly related to the default Kanban view filter showing only the first 40 items.

Expected behavior: Change Company Address and all contacts are updated and remain visible under the same company

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo did you ever come around to this? Is this bug report still relevant?

**Comment by ged-odoo** [comment]
@Yenthe666 Oh yes, I remember that one.  It was a critical bug, which could cause data loss.  It was fixed.
