### ISSUE TITLE
[8.0, 9.0, 9.0E] Unable to export introduction.html translations

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11721]
Impacted versions:
8.0, 9.0, 9.0 Enterprise

Steps to reproduce:
1. Create a custom module
2. Add an index.html for the homepage of your app (for example such as: https://www.odoo.com/apps/modules/9.0/auto_backup/)
3. Go to Settings > Translations > Export translation. Choose your wanted language, file format and choose your module. For example:
![image](https://cloud.githubusercontent.com/assets/6352350/14563476/7c7e244c-0322-11e6-907e-32e3229d3f3f.png)
4. Open up the `.po` file and search for any text you've added to index.html, it is nowhere to be found in your `.po` file

Current behavior:
You're unable to export text made in `index.html` by exporting the values with the Export translations option.

Expected behavior:
Export translation also looks at the HTML files and exports the texts so you can translate them.

**Comment by Yenthe666** [comment]
@mart-e could you give me some insight on this? I'm wondering if this was done with a reason or not.

**Comment by mart-e** [comment]
Hi,
I confirm, it is not possible to translate content put in HTML content.
The problem is that we do not look at the content on the file system but only on content stored in the database (except a few exception like executed code).
The views are translated as stored in a `ir.ui.view` with translatable `arch` field, the field labels are in `ir.model.fields`, etc.
So this kind of static files are ignored it's true but I don't really see how and when we would process them.

**Comment by Yenthe666** [comment]
@mart-e couldn't we just check all files in the addons for some specific extension? For example check for `xx.html`, when it is found we'll parse out the content from the HTML to export it in the `.po` file?

**Comment by mart-e** [comment]
That could be done (not trivial but not impossible) but it's only the first part. The second part will be to make sure the processing will be done correctly, the HTML file needs to be processed server side (using the language of the current user), not just rendered as static content.
This is why I added the tag wishlist, it will require some implementation.

**Comment by GoodERPJeff** [comment]
Same issue on database_manager.html

normally potential customer can stand on english module descriptions (ref this issue and #626 )

but they will unhappy when first view after installation (database creation) is english ONLY

**Comment by Yenthe666** [comment]
@mart-e any update on this one? I still miss this feature and it would be neat for the Odoo app store too.

**Comment by mart-e** [comment]
No that's not something we will implement. You need to add your content inside a view to be processed by Odoo
