### ISSUE TITLE
 /web/webclient/version_info: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

### ISSUE THREAD

**Issue by saravanan10393** [odoo/odoo#11739]
Impacted versions: 9.0

Steps to reproduce: call the odoo web api services using this https://github.com/akretion/angular-odoo/blob/master/dist/odoo.js. and call login method with needed credential

Current behavior:  /web/webclient/version_info: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

Expected behavior:

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
You better ask suppor for the angular-odo library ont he angular-odo bug tracker.

Regards

**Comment by bistaray** [comment]
@thomaspaulb can you specify how this would be done? "allow CORS requests"

**Comment by thomaspaulb** [comment]
Configure Odoo to allow CORS requests: use NGINX to host Odoo and follow configuration as indicated in the last comment here: https://github.com/akretion/odoo-ionic-picker/issues/1

Start Chrome without CORS detection: http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by mustafal** [comment]
I had same error when I call this method from ionic in ios device. it runs fine in android please help me out.
