### ISSUE TITLE
[9.0] Chart of accounting for Saudi Arabia is using wrong currency

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#11741]
Impacted versions: 9.0

Steps to reproduce:
1) Install chart of accounting for Saudi Arabia (https://www.odoo.com/apps/modules/9.0/l10n_sa/)

2) Edit Company data

3) Change the currency to SAR since this is the currency for Saudi Arabia

<img width="467" alt="screen shot 2016-08-28 at 1 39 43 pm" src="https://cloud.githubusercontent.com/assets/1232772/18033206/8e68e40e-6d25-11e6-97e9-228b3809dc0d.png">

Current behavior:
The list doesn't include SAR (Saudi Riyal) and the default is set to EGP (Egyptian Pound) which is the currency for another country

Expected behavior:
SAR should be added to the list of currencies and the default should be SAR not EGP

Video/Screenshot link (optional):

**Comment by alaa9jo** [comment]
@Yenthe666 , can you let someone have a look into this issue? I understand that we can't remove EGP because this would be a breaking change (correct??) , but adding SAR and to be the default currency is a safe change :)

**Comment by heshamfm** [comment]
Same issue in Odoo 10

**Comment by Yenthe666** [comment]
@mart-e this is perhaps one for you? And indeed removing a record in a stable won't be allowed @alaa9jo.

**Comment by mart-e** [comment]
Hello,

We do not remove a currency, just the specified currency was indeed wrong (I assume bad copy-paste).
I have fixed it in 9.0 at 1a1b0e238aa093abb77815cb5d6bdfc3489ad4d2, it will land in 10 soon

**Comment by azawawi** [comment]
@mart-e Thanks for the fix. Can you fix it please in 10's [account_chart_template_data.xml](https://github.com/odoo/odoo/blob/10.0/addons/l10n_sa/data/account_chart_template_data.xml#L15)?

**Comment by mart-e** [comment]
@azawawi my message was

 > I have fixed it in 9.0 at 1a1b0e2, it will land in 10 soon.

so yes, it is going in v10, just need to wait a bit to port it to upper version :)

**Comment by azawawi** [comment]
My bad. Thanks for all your work 👍
