### ISSUE TITLE
Logout problem with "^%d$" dbfilter

### ISSUE THREAD

**Issue by jl2035** [odoo/odoo#11740]
There is this problem: https://www.odoo.com/forum/help-1/question/v9-menu-disappears-and-logout-after-activating-developer-mode-95289

So if:
dbfilter = .*
Odoo works ok.

If
dbfilter = ^%d$
I'm experiencing strange behaviour. I can't login for example.

But I need dbfilter to be "^%d$", because this is the only way I can have databases with subdomains.

So please, can somebody look into this? This is a serious problem!

**Comment by jjscarafia** [comment]
:+1: I have same problem...

**Comment by treviser** [comment]
Have you set proxy_mode = True ?

**Comment by jl2035** [comment]
@treviser thanks for your response. I've just tested with and without proxy mode but it makes no difference.. :(

**Comment by mike3288** [comment]
Experiencing the same issue. Tried to set proxy_mode = True without difference.

**Comment by frankmiao2015** [comment]
I confirm I have the same issue which almost driver to crazy!

**Comment by frankmiao2015** [comment]
Is there any fix on this issue? I really need the dbfilter to work normal. I reinstalled many many times and encountered the same problem with jl2035. Why there is so few people reporting it?

**Comment by jl2035** [comment]
Still nothing goin' on here..?

**Comment by frankmiao2015** [comment]
Can't believe no one fix it for such a long time. The odoo official really abandoned the community users!

**Comment by Yenthe666** [comment]
@sle-odoo can you give an update on this? Quite some people seem to have this problem.

**Comment by pimodoo** [comment]
Hi all,
I've made some tests with the dbfilter = ^%d$ in a config file for last 9.0 odoo on Ubuntu 14.4 and didn't find any problems.
So here is my scenario, I used http://xip.io/, which allow you to work locally with sub-domains, to make my tests:
1: I launched my local odoo server (with the config file containing dbfilter = ^%d$)
2: I went on: http://test.127.0.0.1.xip.io:8069
3: Because I haven't any database called "test" yet, I filled the form to create database with the value 'test' in the database field. (Because if the database name is different from the sub-domain name the database won't pas the filter '^%d$'.
4: Then I used log in, install modules,  activate dev mode, log out,... without any problems.

Can you tell me what are the scenarios that are causing you some troubles to reproduce them on my side and fix them.

Thanks for having reported this issue.

**Comment by jl2035** [comment]
@pimodoo can you use developer mode?

On Aug 31, 2016 2:53 PM, "pimodoo" <notifications@github.com> wrote:

Hi all,
I've made some tests with the dbfilter = ^%d$ in a config file for last 9.0
odoo on Ubuntu 14.4 and didn't find any problems.
So here is my scenario, I used http://xip.io/, which allow you to work
locally with sub-domains, to make my tests:
1: I launched my local odoo server (with the config file containing
dbfilter = ^%d$)
2: I went on: http://test.127.0.0.1.xip.io:8069
3: Because I haven't any database called "test" yet, I filled the form to
create database with the value 'test' in the database field. (Because if
the database name is different from the sub-domain name the database won't
pas the filter '^%d$'.
4: Then I used log in, install modules, activate dev mode, log out,...
without any problems.

Can you tell me what are the scenarios that are causing you some troubles
to reproduce them on my side and fix them.

Thanks for having reported this issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/11740#issuecomment-243754064>, or mute
the thread

**Comment by pimodoo** [comment]
What are you calling 'use' developer mode? Activate it?
Which action in developer doesn't work for you?

**Comment by jl2035** [comment]
@pimodoo Yeah, I get logged out when I activate it.

**Comment by jl2035** [comment]
@pimodoo I tried the steps you've described with xip.io and I get the same results as you. Apparently things only break in real life environment.

**Comment by pimodoo** [comment]
Can you tell me if you can reach the page 'http://yoursubdomain.yourdomain.com/web?debug' ? It's the same as activating the developer mode. If it doesn't work, can you give me your odoo server logs, and your apache/nginx logs after having tried to activate developer mode.

Thanks

**Comment by juanbaez** [comment]
I have same problem... 
![captura de pantalla de 2016-09-04 01-24-45](https://cloud.githubusercontent.com/assets/12465491/18257126/d4634464-738c-11e6-8564-85e9f19e2865.png)
I work with Ubuntu 16.04, and Odoo 9.
I change the parameters of the DBFILTER, but does not work.
In my version of Odoo, did not come with DBFILTER in the openerp-server.conf, it's weird.

**Comment by pimodoo** [comment]
HI @juanbaez in your log, it says that you're trying to log into the database named 'odoodata', can you confirm me that your domain name is 'odoodata.your-domain.com'?

**Comment by frankmiao2015** [comment]
I can not reach the page 'http://yoursubdomain.yourdomain.com/web?debug' ?. It display a blank page with black menu bar like this:
![blank](https://cloud.githubusercontent.com/assets/10336015/18295653/0e065dde-7458-11e6-9438-95f110ace219.png)
And here is the odoo server error log:
![error log](https://cloud.githubusercontent.com/assets/10336015/18295673/31742878-7458-11e6-8b65-a78c8dcedeee.png)

And there is only one line Nginx error log which I do not think have any relevant:

2016/09/07 06:11:52 [notice] 1403#1403: signal process started

Tks

**Comment by jl2035** [comment]
@pimodoo here are my relevant logs. Nginx access and Odoo output. Database name is 'comcrm'.

[logs.zip](https://github.com/odoo/odoo/files/458449/logs.zip)

**Comment by pimodoo** [comment]
@jl2035 Hi,

When I try to reach your server on https://comcrm.tabla.si, I'm redirected to the url: https://comcrm.tabla.si/web/database/selector, because there is not any database existing on your server with the name comcrm, if you set dbfilter = ^%d$.

Could you try to create a new database, and eventually delete your cookies before trying to reach the url. If the problem persists, could you  send me your nginx config to let us try to reproduce it.

Thanks in advance

**Comment by jl2035** [comment]
@pimodoo sorry.. I deleted the database yeah. Can you try now (i don't have the ssl cert ready, but it should work without it) ?

**Comment by pimodoo** [comment]
@jl2035 can you send me access to your database at email pim@odoo.com to try it. And, is there a reason for using https without valid certificate? Does it still buggy in http?

**Comment by jl2035** [comment]
@pimodoo if you need access to postgresql, I'm not sure if my sysadmin would allow that. Also we don't have SSH opened to the outside world. I can only access the servers when I'm at work.

But if you really won't be able to reproduce the problem, I guess we could arrange something in the next week. Let's stay in touch.

The certificate is valid now. I only know how to configure nginx for odoo using https (all tutorials were like that, when I was learning).

**Comment by jl2035** [comment]
SOLVED!

Let me just leave this here: https://bugs.launchpad.net/openobject-server/+bug/940439

**Comment by jl2035** [comment]
It's a workaround actually, but I closed the issue as I don't believe anybody will be looking into this..

**Comment by jl2035** [comment]
Unbelievable! It only worked one time now I'm back at the beginning. I think I've searched the entire internet, but can't find solution to this!

**Comment by jl2035** [comment]
https://www.odoo.com/forum/help-1/question/domain-based-db-filter-6583

* I even tried to use dbfilter = %h 
* I tried with dbfilter = ^(domain1|domain2)$

all was unsuccessful of course..

My solution for now was to hack the code:

    def setup_db(self, httprequest):
        db = httprequest.session.db
        # Check if session.db is legit
        if db:
            if db not in db_filter([db], httprequest=httprequest):
                _logger.warn("Logged into database '%s', but dbfilter "
                             "rejects it; logging session out.", db)
                #httprequest.session.logout()   #COMMENT OUT THESE TWO LINES
                #db = None

        if not db:
            httprequest.session.db = db_monodb(httprequest)

But this is probably bad, right?

**Comment by max3903** [comment]
I had the same problem and the problem was that the longpolling request was not coming to the host name but the one I had in my nginx config file:
```
upstream im {
    [...]
}
```

So I patched Odoo temporarily (odoo/http.py):
```
        if db:
            # Authorize im
            h = httprequest.environ.get('HTTP_HOST', '').split(':')[0]
            if db not in db_filter([db], httprequest=httprequest) and h != 'im':
                _logger.warn("Logged into database '%s', but dbfilter "
                             "rejects it; logging session out.", db)
                httprequest.session.logout()
                db = None
```

**Comment by gdgellatly** [comment]
Hmm I had this issue. All I remember doing was adding the database name as
an alias for localhost in /etc/hosts .

**Comment by gustavovalverde** [comment]
@Yenthe666 this seems to be a real issue, this happens to me in a server configured with `dbfilter = ^%d$`. It logs out every time I print a document or try to send an email with attachment (in v11). Mainly, when the PDF is generated it logs out the user and the document is generated without css.

**Comment by gustavovalverde** [comment]
The log:

```
2018-01-28 18:21:13,521 1063 WARNING ? odoo.http: Logged into database 'preconfigurada', but dbfilter rejects it; logging session out.
2018-01-28 18:21:13,521 1056 WARNING ? odoo.http: Logged into database 'preconfigurada', but dbfilter rejects it; logging session out.
2018-01-28 18:21:13,521 1062 WARNING ? odoo.http: Logged into database 'preconfigurada', but dbfilter rejects it; logging session out.
2018-01-28 18:21:13,525 1062 INFO ? odoo.http: Generating nondb routing
2018-01-28 18:21:13,752 1058 INFO ? odoo.http: Generating nondb routing
2018-01-28 18:21:13,752 1057 INFO ? odoo.http: Generating nondb routing
```

**Comment by gustavovalverde** [comment]
Maybe you guys @sle-odoo and @pimodoo could have another look at this.

**Comment by gustavovalverde** [comment]
Just an **FYI**

In v11, making `list_db = False`, have the same behavior as `dbfilter = ^%d$` (sending to each database, based on subdomain).

This is also a workaround for the logouts, but I'm not sure of the _side effects_ (or is this the new way to use it?)

**Comment by gustavovalverde** [comment]
After testing with @pimodoo, his solution worked for me:
- set the key '**report.url**' to 'http://`{dbname}`.`{domain}`:8069'
- add a line to your file **/etc/hosts** -> '127.0.0.1 `{dbname}`.`{domain}`'

For others, as @gdgellatly suggested https://github.com/odoo/odoo/issues/11740#issuecomment-326710662 the /etc/hosts part might be enough

**Comment by pimodoo** [comment]
As replied to the OPW opened for that issue, the report.url was the problem, because configured as '0.0.0.0:8069', so when a report was requested, the request didn't pass the dbfilter as called through '0.0.0.0' instead of 'sub.domain.com' where 'sub is the db name.

By removing the report.url there were not any db-filter rejection, but issue of css in the report. To fix that issue, we changed the file /etc/hosts to add a line '127.0.0.1 sub.domain.com' which will let the redirection of call to sub.domain.com to the localhost.

I'm not sure that the ir_config_parameter still required after having modified the /etc/hosts

**Comment by jl2035** [comment]
Interesting. I don't think I've ever set that line in hosts file..

**Comment by adekock11** [comment]
@pimodoo I had to add an entry to `/etc/hosts` as well as set my ir_config_parameter to `http://sub.domain.com:8069` in order for CSS to load *and* for the session not to expire. That's too bad because it makes deployment a tiny bit more complex.

Thanks @gustavovalverde for your suggestionsthat helped me find a solution for my situation.

@jl2035 I've never had to do this as well, but while setting up a new server today, this problem came up. I'm going to do some further investigation to see what differences are in all our other servers that work without the `/etc/hosts` entry and this particular server. There must be *something* different 👍

**Comment by pimodoo** [comment]
@adekock11 Hello,
The problem is not on the odoo side, but on you dns resolver side. Your server is not able to resolve its own dns entry and adding your subdomain in /etc/hosts resolves your domain before trying to resolve it through the dns server as your file '/etc/nsswitch.conf' must have the attribute 'files' before the 'dns' one for the entry 'hosts'.

If your server can properly resolve its own dns entry, it should not be needed to modify the report url and/or the /etc/hosts file.

Best regards

**Comment by gdgellatly** [comment]
For others who might stumble across this. I usually only get this issue on 2 platforms.  Ubuntu desktop w/ networkmanager as the DNS often times out for no reason and when running containers across a CoreOS cluster where CoreOS is responsible for the internal DNS of the Docker machines.  For Docker builds you can automate the entries using a simple psql script and https://github.com/hiteshjasani/nim-mungehosts.

**Comment by ChienDesEnfers** [comment]
Hello everybody,

I had exactly the same issue. I edit my `/etc/hosts` file to add my domain, I edit my `dbfilter `from the `odoo.conf` file, I also edit my nginx configuration file but nothing fix this issue.
I have 2 databases
- 1 for example.com (db = example)
- 1 for demo.example.com (db = demo)
When I log in, I'm directly disconnected because my session expired... Into the logs, I have the message who say that my current db (demo or example) doesn't match with the filter.

My db filter:
`dbfilter = ^%d$`


Please, someone can help me about this issue?

Thank you!

**Comment by tpa-odoo** [comment]
If we use dbfilter = ^%d$

and we are running two domains abc.com and abc.in  same issue happens. 

even if both are in different version abc.com is on v9 and abc.in on v11

**Comment by ChienDesEnfers** [comment]
@tpa-odoo If you have 2 different versions of Odoo, you must have 2 instances.
The way to fix this issue (with 2 instances) is to use a different Postgres user on your `odoo.conf`
But if you have 1 instance and 2 Databases (in the same Odoo version of course), we have the same issue =/

**Comment by ChienDesEnfers** [comment]
I fix this problem.
It was my Nginx configuration.
I didn't include some `set-headers` into the `odoo-chat` (with the port 8072).
I did it for statics files but not for this chatter.

**Comment by tpa-odoo** [comment]
@ChienDesEnfers we have two different instances. but same Db user. will try ith 2 different db users also if it helps.

**Comment by tpa-odoo** [comment]
Hello Eeryone,

I tried all option but seems that long-polling port was causing an issue. using different port solved my issue.

**Comment by xabispacebiker** [comment]
I had the same problem on a production server that was working for long time. Suddenly I started to get the logout issue and after trying every solution I found here and in other forums, nothing worked. 

Then I decided to check the logs and I found this:

```
2018-06-13 20:48:52,798 13774 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 244, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1325, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/usr/lib/python2.7/dist-packages/odoo/addons_extra/target_achievement_invoice/__init__.py", line 22, in <module>
    import models
  File "/usr/lib/python2.7/dist-packages/odoo/addons_extra/target_achievement_invoice/models/__init__.py", line 22, in <module>
    import find_user_target
File "/usr/lib/python2.7/dist-packages/odoo/addons_extra/target_achievement_invoice/models/find_user_target.py", line 119
    'percent': round( ((target>0)? (target_bal / target) : 0) * 100, 1),
```

This addon was not installed on any of my instances but the code was returning the error !. I just moved that addon from the addons folder, restarted odoo and it worked again.

Hope this helps someone

**Comment by eragroup** [comment]
I had the same issue and I solve it in nginx setting as follow:
location / {
        proxy_pass  http://127.0.0.1:8069;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;

        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $http_host;
        proxy_set_header    X-Forwarded-Proto https;
    }

    location /longpolling {
        proxy_pass http://127.0.0.1:8072;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $http_host;
    }

**Comment by carlo-github** [comment]
Odoo 12.0-20190807 (Community Edition)
Ubuntu 18.04
In odoo.conf I had:
dbfilter = ^%d$

I had the same problem after "Activate the developer mode" when I try to "Update Apps List" or try to search modules..
Is it a bug?
Is there a solution?

**Comment by haederliphilip** [comment]
i have the same Problem

my odoo.conf
`db_name = False
db-filter = '^%h$'
proxy_mode = True`

appache conf
`<VirtualHost *:80>
    ServerName test-deko-gardina.xxxx.ch
    ServerAlias test-deko-gardina.xxxx.ch

    LogLevel warn
    ErrorLog     /var/log/apache2/test-deko-gardina.error.log
    CustomLog    /var/log/apache2/test-deko-gardina.access.log combined

    ProxyPass        / http://192.168.5.9:8069/
    ProxyPassReverse / http://192.168.5.9:8069/

    Header add X-ODOO_DBFILTER "lena"
    RequestHeader add X-ODOO_DBFILTER "lena"
</VirtualHost>`

`<VirtualHost *:80>
    ServerName CreativAnastasiaArt.xxxx.ch
    ServerAlias CreativAnastasiaArt.xxxx.ch

    LogLevel warn
    ErrorLog     /var/log/apache2/CreativAnastasiaArt.error.log
    CustomLog    /var/log/apache2/CreativAnastasiaArt.access.log combined

    ProxyPass        / http://192.168.5.9:8069/
    ProxyPassReverse / http://192.168.5.9:8069/

    Header add X-ODOO_DBFILTER "anastasia"
    RequestHeader add X-ODOO_DBFILTER "anastasia"
</VirtualHost>`

thank you for you help

Philip

**Comment by tpa-odoo** [comment]
Hello,

Make sure if you are running multiple odoo services on diff ports each have
diff longpolling port also.

Same Longpolling port causes such issue normally else it works fine with DB
filter.



Thanks & Regards,

Turkesh Patel

Mob: +91 9033584086

Skype: turkesh4friends

www.almightycs.com
