### ISSUE TITLE
Translate bot has translated code and causes syntax error.

### ISSUE THREAD

**Issue by Gizmozator** [odoo/odoo#117475]
Impacted versions: 16.0

Steps to reproduce: Install clean docker image and set languate Finnish

Current behavior: Try to send new invoice.  inline_template mallia : invalid syntax (, line 1))

Expected behavior: Sending invoice works

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/17762602/229494447-dc8295de-a9ae-4055-8150-f4aa63a19dc2.png)

Support ticket number submitted via odoo.com/help (optional):

Bot has translated template code part "or" to finnish "tai" and causes syntax error. Could affect other language packages and multiple places. Didn't look through to find all the issues.

Example:
16.0/addons/account/i18n/fi.po
Line 8096: Invoice_{{ (object.name tai '').replace('/','_') }}{{{ object.state == "

Line 4873: "Credit_note_{{ (object.name tai '').replace('/','_') }}{{{ object.state == "
Line 4874: "'draft' and '_draft' tai '' }}"

Git blame shows @C3POdoo - @mart-e

**Comment by mart-e** [comment]
Hello,

Thank you for the report, the translations are handled on Transifex.
More specifically https://app.transifex.com/odoo/odoo-16/translate/#fi/account/437927465?q=text%3AInvoice_
I have made the correction (it will be imported in github in the next weekly synchronisation) but don't hesitate to contribute the if you notice other issues.
Best,
