### ISSUE TITLE
Paypal requires state code, not state name for USA orders

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#11748]
The field 'state' in the payment_paypal model currently grabs the state name field (i.e. California) not the state code (i.e. CA).  This causes an error on the paypal payment page asking the user to update the address to a suggested one. 

The fix seems simple, in the paypal.py model,   just change 
`'state': values.get('partner_state') and values.get('partner_state').name or '',`
to
`'state': values.get('partner_state') and values.get('partner_state').code or '',`

Perhaps there is a good reason for this?  Are there countries with states that have no code, only name?

**Comment by Yenthe666** [comment]
@nim-odoo could you have a look at this one? I'm not sure if I'm pinging the right guy here though. :smile:

**Comment by Yenthe666** [comment]
Hi @rowemoore,

This has actually been changed/fixed in the meanwhile. It now first looks at the code and if it cannot find the code it will look at the name:
https://github.com/odoo/odoo/blob/91ca846447628084f5a089e986319ef18581ddf2/addons/payment_paypal/models/payment.py#L106

Regards,
Yenthe
