### ISSUE TITLE
Odoo 9  POS Development 

### ISSUE THREAD

**Issue by aliabdelmonem** [odoo/odoo#11747]
Hello ,

I got this error while developing new module on POS 

Uncaught TypeError: Cannot read property 'show_screen' of undefined

 this.gui.show_screen('bill');

i just crated screen and call it in add_product function  of POS order

thanks

**Comment by mart-e** [comment]
Hello,

Github issues is to report bugs on Odoo core. Please don't ask help for custom dev here, check the mailing lists or forum instead
