### ISSUE TITLE
[16.0] Can't connect to odoo, first try (at localhost:8069)

### ISSUE THREAD

**Issue by Gal-Noy** [odoo/odoo#117490]
Impacted versions: 16.0

Steps to reproduce: reinstall everything

Current behavior: trying to start odoo for the first time, when trying to access localhost:8069, get this terminal error and couldn't connect to it.

Expected behavior: seeing the login page of odoo...

Video/Screenshot link (optional):
![odoo-error](https://user-images.githubusercontent.com/109943831/229520952-0062d3a3-5874-4bfa-9240-45b570747c59.jpg)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
@Gal-Noy ,
can you try to access odoo in private window/incognito mode and see how it comes

**Comment by Gal-Noy** [comment]
> @Gal-Noy , can you try to access odoo in private window/incognito mode and see how it comes

Jesus, it worked.
I looked for an answer online for over three days before coming here.
Thank you very much! can you explain?
