### ISSUE TITLE
Fail to find newly created module until create a new database

### ISSUE THREAD

**Issue by xiasun** [odoo/odoo#11749]
Impacted versions: Odoo 8.0 latest

Steps to reproduce: Create a new module at addons dir.

Current behavior: Cannot find the newly created module in setting module until logout from current account and create a new database.

Expected behavior: Should be able to find the module with current database logged in.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Sorry but we don't rescan all modules all the time as it would be too costly. Adding a new module is not something very frequent.
Instead, to force the rescan of modules you can use the menu Apps > Update Apps List (you need to be in debug mode to see it)

![screenshot from 2016-04-20 10-27-03](https://cloud.githubusercontent.com/assets/564822/14668065/90301324-06e2-11e6-8534-1e4cac56dfd3.png)

**Comment by xiasun** [comment]
Thanks i got it now.

**Comment by yucer** [comment]
Nevertheless, i think that this option should be available via command line.

For CI tools, sometimes the upstream code contains new modules and the update of the modules that include this new dependency fail complaining a missing module dependency although the module is still there.

I did open an issue describing the context where this can be useful:

https://github.com/odoo/odoo/issues/11802
