### ISSUE TITLE
Sort rule

### ISSUE THREAD

**Issue by anhnguyen0712** [odoo/odoo#117564]
Impacted versions: 13

Steps to reproduce: 

Current behavior: Sort "Project" ascending

Expected behavior: Project name is sorted from A - Z

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/129836666/229725969-09ad792d-695c-44d4-b559-17099cab6e67.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hello,

Thank you for your contribution but the version 13 is no longer supported. We only support the last 3 stable versions so we no longer accept patches into this branch.
We apology if we could not look at your request in time.

If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards
