### ISSUE TITLE
Adding new product category does not automatically create external identifier

### ISSUE THREAD

**Issue by s2d4theworld** [odoo/odoo#11760]
Impacted versions: 9.0 CE

Steps to reproduce: Create new product category

Current behavior: Creating new product category does not yield any record in the external identifier table (ir_model_date)

Expected behavior: Creating new product category add a new record in ir_model_date table

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's not the intended behavior. Only ir_model_data records are created on exported records.
