### ISSUE TITLE
Odoo Security Advisories Restricted

### ISSUE THREAD

**Issue by aebeck80** [odoo/odoo#117739]
Impacted versions: 
16.0

Steps to reproduce:
Access https://www.odoo.com/security-advisories

Current behavior:
Security Advisories page requires enterprise subscription

Expected behavior:
Security Advisories page publicly available, so that even community users know when a vulnerability
is disclosed

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
You can see the published/live ones at https://github.com/odoo/odoo/issues?q=is%3Aissue+label%3ASecurity

**Comment by niyasraphy** [comment]
i think previously the page was public and may be it get changed recently. may be @mart-e can give more insights about this

**Comment by mart-e** [comment]
Hello,

Indeed the security advisories are available at https://github.com/odoo/odoo/issues/labels/security
The https://www.odoo.com/security-advisories is a private page for subscribers who may not be very familiar with github but you will find all the released advisories on github too.

Closing this issue as not a software bug.
