### ISSUE TITLE
Ubuntu 16.04, TypeError: CleanCSS is not a function

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#11783]
Impacted versions: 9.0

Steps to reproduce: Ubuntu 16.04 + default packages from repositories

Current behavior: "TypeError: CleanCSS is not a function\A at Object.toCSS (/usr/lib/nodejs/less/lib/less/parser.js:620:32)\A at /usr/lib/nodejs/less/bin/lessc:357:32\A at Object.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)\A at Object.tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)\A at /usr/lib/nodejs/less/lib/less/import-visitor.js:72:38\A at fileParsedFunc (/usr/lib/nodejs/less/lib/less/parser.js:83:17)\A at /usr/lib/nodejs/less/lib/less/parser.js:106:29\A This error occured while compiling the bundle 'web.assets_backend' containing:\A - /website/static/src/less/import_bootstrap.less\A - /web/static/src/less/variables.less\A - /web/static/src/less/enterprise_compatibility.less\A - /web/static/src/less/utils.less\A - /web/static/src/less/modal.less\A - /web/static/src/less/notification.less\A - /base_import/static/src/less/import.less\A - /web_tip/static/src/less/tip.less\A - /web_calendar/static/src/less/web_calendar.less\A - /web_diagram/static/src/less/diagram_view.less\A - /web_kanban/static/src/less/kanban_dashboard.less\A - /web_kanban/static/src/less/kanban_view.less\A - /web_settings_dashboard/static/src/less/dashboard.less";

**Comment by denics** [comment]
why is this issue closed? I still get the same error on ubuntu, same configuration:

```
TypeError: CleanCSS is not a function
    at Object.toCSS (/usr/lib/nodejs/less/lib/less/parser.js:620:32)
    at /usr/lib/nodejs/less/bin/lessc:357:32
    at Object.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)
    at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
    at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
    at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
    at Object.tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)
    at /usr/lib/nodejs/less/lib/less/import-visitor.js:72:38
    at fileParsedFunc (/usr/lib/nodejs/less/lib/less/parser.js:83:17)
    at /usr/lib/nodejs/less/lib/less/parser.js:106:29
```

**Comment by sle-odoo** [comment]
clean css is not used anymore, please update your code base

**Comment by superwebdeveloper** [comment]
someone tell the less folks that clean css isnt in use anymore.
