### ISSUE TITLE
One2many field does not honour being 'required' 

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#11782]
Impacted versions: 8.0 at least 

Steps to reproduce:
- Go to the Sales / Quotations form, and edit the from XML to add `required="1"` to the `name="order_line"`field.
- Click again on the Quotations menu to reload the form, create a new quotation with no lines and save.

Current behavior:
- It saves without error

Expected behavior:
- Show an error because the order lines field is empty. In many2many fields this works correctly.

**Comment by dreispt** [comment]
Ping!

**Comment by dansanti** [comment]
you must, click in upgrade on Sales  plugin

**Comment by dreispt** [comment]
This is not a SO specific issue - that was just an example. The issue is generically with One2many fields.

**Comment by dansanti** [comment]
well, i modify addons/sale/sale_view.xml  line 182 and add required="1" then reload with f5 and works fine 
<field name="order_line" required="1" mode="tree,kanban"

**Comment by dreispt** [comment]
I just tested on Runbot 8.0: edited the Sales Order view to make order lines mandatory, F5, created a new SO without lines, and it didn't error as expected.

**Comment by Gorash** [comment]
The fix has been merged

**Comment by dreispt** [comment]
But the #12248 is still open...
