### ISSUE TITLE
Short upgrade error message: "You try to upgrade a module that depends on the module..."

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#11796]
Impacted versions: 8.0 9.0

Steps to reproduce: 

Try to upgrade a module that depends on another not available on the system.

Current behavior:

Odoo raises an upgrade error:

> "You try to upgrade a module that depends on the module: %s.\nBut this module is not available in your system."

In the case that you are missing the module, this is OK. But if one of your list of modules has a wrong dependency then you need to know the exact name of the failing module. Specially if the module changes come from one of your upstream branches.

Expected behavior:

> You try to upgrade the module(s): %s that depends on the module: %s.\nBut this module is not available in your system.

Video/Screenshot link (optional):

**Comment by adekock11** [comment]
+1

**Comment by Yenthe666** [comment]
@JKE-be was this ever added in? I don't see any commit in Odoo itself but see plenty of odoo-dev commits.

**Comment by JKE-be** [comment]
https://github.com/odoo/odoo/commit/6defad0340c921325cee5a96b154cac0fee171af ;)

**Comment by Yenthe666** [comment]
Hero! 😉
