### ISSUE TITLE
URL of website_published is wrong when using next/previous into the form view

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#11800]
Impacted versions: 8.0

Steps to reproduce:
* go to runbot 8.0 and connect
* go into human ressources/job positions
* pass into list view and click on the first item
* click on the url to open this record into the website (website_published)
* go back (back into the browser)
* you're now into the form view again and then next step is to click on the button "next" to access the following record
* click on the url of website_published

Current behavior:

wrong record, this is the previous one that is into the href

Expected behavior:

correct record with the correct id into the href

Notes:

into the file website/static/src/js/website.backend.js: the change is made into the render_value that is called only when somthing changed. maybe a good track...

**Comment by JonathanNEMRY** [comment]
OPW 675832

**Comment by JonathanNEMRY** [comment]
@dbo-odoo  any new about this issue???

**Comment by dbo-odoo** [comment]
@JonathanNEMRY 
Hello,
This issue will be treated by our bug-fix team (which I'm not part of); I'm afraid I can't give you any time estimate since this is not a blocking issue... But it will be treated, naturally!

**Comment by JonathanNEMRY** [comment]
fyi @Olivier-LAURENT
