### ISSUE TITLE
[9.0] Picking date behaviour when 'pick+pack+ship' feature enabled

### ISSUE THREAD

**Issue by jas-odoo** [odoo/odoo#11801]
Impacted versions:9.0

Steps to reproduce:
Enable 'pick+pack+ship' from warehouse.
Create sale order and confirm that order.
It will create 3 picking
Now validating any 1 picking will set rest picking of sale order to today's date
rest of picking will take minimum stock move date

Expected behavior:
Stock move date doesn't affect picking date.

**Comment by sle-odoo** [comment]
Hi,

This should have been fixed by https://github.com/odoo/odoo/pull/21445

Regards
