### ISSUE TITLE
"update module list" not available via command line

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#11802]
Impacted versions: all

Steps to reproduce:

When:

1) The addons code is updated from upstream
2) An existing module contains a new dependency
3) This module dependency was not previously in the code
4) Odoo database is updated via command line by automated scripts

Current behavior:

Odoo raises the error:

> You try to upgrade a module that depends on the module: %s.\nBut this module is not
> available in your system.

Nevertheless the module is available although the module list is missing an updated 

Expected behavior:

Either the module list automatically updated by the **upgrade module** and **install module** features (this was rejected: https://github.com/odoo/odoo/issues/11749)

or we have the feature **update the module list via command line** so we can call it on step 3.5 

The procedure of automatically upgrading the database after getting the latests upstream code from our addons providers should not depend of human interaction via the odoo user interface.  

A solution can be adding a new module for updating (as proposed here: https://www.odoo.com/es_ES/forum/ayuda-1/question/how-to-update-module-list-from-command-line-84385)

Video/Screenshot link (optional):

**Comment by nedaszilinskas** [comment]
+1

**Comment by tebanep** [comment]
+1

**Comment by pedrobaeza** [comment]
An update of the module list happens each time you update or install a module. You can use the trick of trying to update a non existing module for getting the same result.

**Comment by yucer** [comment]
Sorry for the late feed-back.

That's not the behavior that I see in  v8.0 nor in v10.0. The trick doesn't work neither. Where have you seen those behaviors? It is from a community version ?

It is easy to verify. Just log a message at the begin of the [update_list](https://github.com/odoo/odoo/blob/dece72d010e23c88bdf5b2a1ace6ff0df2b2732f/odoo/addons/base/module/module.py#L597) method, like this:

```python
_logger.info("--------- MODULES LIST UPDATED !!! --------------")
```

The log is written only when the `Update Module List` menu action is invoked from the user interface.

**Comment by yucer** [comment]
Mmm... I see the problem. You are right, the method is called every time the user try to upgrade a module. But only if the user interface is used, because the method is called from [button_upgrade](https://github.com/odoo/odoo/blob/dece72d010e23c88bdf5b2a1ace6ff0df2b2732f/odoo/addons/base/module/module.py#L532) 

When the command line is used the method is called [directly](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/odoo/modules/loading.py#L294), but under a condition:

```python
            if ('base' in tools.config['init']) or ('base' in tools.config['update']):
                _logger.info('updating modules list')
                Module.update_list()
```

So that means... only if the `base` module is included into the list. The problem is that the base module will trigger the update of all the modules. That means in English: 

> Only when all modules are going to be updated, new modules will be recognized

Do you see a reason for that restriction ? Maybe in the oder direction:

> If new modules are recognized, then all modules are updated

or better:

> If new modules are recognized, then all dependent modules are updated

**Comment by Ark74** [comment]
This would very valuable when you hit a 500 Internal Server Error state.

**Comment by naglis** [comment]
As a workaround I do this:
```sh
odoo-bin --addons-path=<addons_path> shell -d <db>
```

Inside the shell:
```python
env['ir.module.module'].update_list(); env.cr.commit(); quit()
```

**Comment by pedrobaeza** [comment]
Although there's still no command line argument for this, the list is updated before updating or installing anything, so this is enough IMO, and thus I'm closing this.

**Comment by pedrobaeza** [comment]
This is in from v11, or in OCB in all versions.
