### ISSUE TITLE
Small usability issue on BOM and MO 

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1180]
Tested on runbot http://06344-8-0-f98c61.runbot.odoo.com/

Case of use:
Take product case computer
Add 2 color variants "red" and "black"

I want to configure a BOM for case computer(red) and another one for case computer(black)

If I go to case computer template I see 2 bom on shorcut button --> It's correct
        Computer Case   Computer Case (black)   20.00   Case Black  Normal  
    Computer Case   Computer Case (red) 20.00   Case red            Normal  
If I go to case computer red product I also see 2 bom on shortcut button --> it's incorrect there is only one related to red product. If I push button is correctly filtered showing only the correct single bom for red product.

About BOM name, it's disapeared from view on this version but I think value is set somewhere. The name it's taken from template and not from product it self. This causes this error:
MO: 
Create a new MO
Select a product  Computer Case (black) --> his BOM is automatically selected but the name shown on MO is computer case (not bom reference or variant name or something but just the template name) 

Now change the product on same MO selecting Computer Case (red) --> the bom remains the same. There is no onchange to select the correct bom for changed product.

I think, the bom selection on MO is made using template Id instead product Id. This would be wrong. 
On the other side the name shown on combo is bom name that is automatically filled from system, and it's not bom reference or something that could allow knowing if the correct bom is selected before launching the MO.

Small usability on MO would be:
1. Include template_id on MO, so user could first select template, and after product_id field where domain could be set depending on template_id
2. Select correct bom on product_id change
3. Show any bom field/parameter/name to identify it properly (let changing name on bom as it was before, for instance) 
4. Domain on bom field depending on product_id.

Thank you:
Ana
P.D: We could help on building patches to cover this functionality if needed.

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your (very detailed!) bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
