### ISSUE TITLE
ValueError: Invalid field account.analytic.line.project_id in leaf ('project_id', '=', False)

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#118149]
Impacted versions: 16.0 

Steps to reproduce: Post an sales invoice and then click reset to draft button

Current behavior: Unable to reset to draft

Expected behavior: Should be able to reset to draft

Video/Screenshot link (optional):
**addons/account/models/account_move.py", line 3679, in button_draft
    move.mapped('line_ids.analytic_line_ids').unlink()**

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @shazzwazz20 
Could you explain a bit more how this happens (with screenshot if possible)? I'm not able to reproduce the problem. 
Please also try to reproduce on https://runbot.odoo.com/ (blue door icon of the version row - admin/admin). If not, then it is probably linked to your configuration.
Regards

**Comment by vava-odoo** [comment]
@shazzwazz20 Feel free to re-open the issue if you have more information to provide
