### ISSUE TITLE
No link to product.product in POS

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#11810]
Impacted versions:9.0e
![pos product](https://cloud.githubusercontent.com/assets/12964307/14778814/599aee78-0ad5-11e6-9833-53e967ed2db9.png)
![pos variantes](https://cloud.githubusercontent.com/assets/12964307/14778844/7c2cda3c-0ad5-11e6-9c04-64af86b53e6f.png)

Steps to reproduce: Go to POS, click on Orders, 

Current behavior: only display Products (product.template)

Expected behavior:should display Products (product.template) and Products variants (Product.product) such as in the modules sales

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

This has been done by design and intentionally. If you wish to see/change variables you should go to the sales menu and access them from there.

Regards,
Yenthe
