### ISSUE TITLE
Calendar invite notifications (for attendee Accepted/Rejected etc) do not get sent to invite Originator

### ISSUE THREAD

**Issue by joolsr** [odoo/odoo#11822]
Impacted versions: 9.0 community (and Enterprise I guess) (up to date as of 23/04/)

Steps to reproduce: Create Calendar entry
Add attendee
Attendee gets sent an email with invitation. They click the 'accept' button. 
This updates the calendar entry in odoo with the attendee status as required. But the Organiser does not actually get a notification /email or anything indicating that the request has been accepted. Likewise, if attendee rejects the invite, the calendar entry is updated fine, but no notification is sent to Originator of entry updating them of the situation

Current behavior: No update is received on change to calendar invite

Expected behavior: Notification with Odoo (or email if configure this way) to show that attendee has accepted, declined etc the event.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Thanks for the reporting.
I tag this issue 'Wishlist' but it will not added in actual version...
