### ISSUE TITLE
Button "Scrap Products" doesn't work, when the field 'lot_ids' was inserted into the tree view of stock.move

### ISSUE THREAD

**Issue by yweng8111** [odoo/odoo#11833]
Impacted versions: 8.0

Steps to reproduce:
Extends the tree-view of "stock.move" with field "lot_ids"
Click button "Scrap Products"

Current behavior:
It show me the "Odoo Client Error"

Expected behavior:
It should open a new window of "Scrap Move"

Video/Screenshot link (optional):

![screenshot from 2016-04-26 15 08 33](https://cloud.githubusercontent.com/assets/17932277/14819607/423faefa-0bc3-11e6-831b-10a515de19c2.png)

![screenshot from 2016-04-26 15 07 39](https://cloud.githubusercontent.com/assets/17932277/14819353/16edfd98-0bc2-11e6-9480-39aedd171bc4.png)

After some debug I have found the incorrect function "wrap_context" in JavaScript "addons/web/static/src/js/pyeval.js"

```
   var wrap_context = function (context) {

        for (var k in context) {
            if (!context.hasOwnProperty(k)) { continue; }
            var val = context[k];
            if (val === null) { continue; }
            if (val.constructor === Array) {
                context[k] = wrapping_list.fromJSON(val);
            } else if (val.constructor === Object
                       && !py.PY_isInstance(val, py.object)) {
                context[k] = wrapping_dict.fromJSON(val);
            }
        }
        return context;
    };
```

in line:
`if (val === null) { continue; }`
Perhaps this line should be replaced with 
`if (val === null || val === undefined) { continue; }`
Is this the correct Solution?

**Comment by Yenthe666** [comment]
Hi @yweng8111,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
