### ISSUE TITLE
How change date type to Jalali?

### ISSUE THREAD

**Issue by alisaeed** [odoo/odoo#118311]
Hi
I need to change my date type to Jalali in all forms and reports in Odoo 16.
Can anyone advise where I should start? For example which Java or Python modules can be changed to change the date in all forms and reports?

**Comment by vava-odoo** [comment]
Hello @alisaeed,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
