### ISSUE TITLE
Odoo9 POS user group can not start a session

### ISSUE THREAD

**Issue by yuchuan99** [odoo/odoo#11838]
Odoo9

POS user group can not start a session,and show the info as follow,

Odoo Warning - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: account.bank.statement, Operation: read)

add user group Accountant can be start.

**Comment by Yenthe666** [comment]
Hi @yuchuan99,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 9 and this has been fixed in the meanwhile. Please update your Odoo to the latest source code in order to fix this locally.

Regards,
Yenthe
