### ISSUE TITLE
ALIEXPRESS CONNECTOR for odoo (Fabien Pinckaers CEO, Antony Lesuisse CTO please)

### ISSUE THREAD

**Issue by frenchwish** [odoo/odoo#118399]
Hello, my name is Joel from France (I'm French so sorry if my English is bad), I'm 25 years old and I'm the CEO of "FRENCHWISH" frenchwish.fr

I'm here to ask you if you can call all your developers, programmers and engineers to create for future versions of odoo: AN ALIEXPRESS CONNECTOR for Standard Subscription (24€90/month)

Seriously, you can't imagine the power of having an aliexpress connector on my Odoo website. Just imagine:

- Upload products very quickly (in 1 click)
- Know if the product is out of stock
- Automate sales: if someone makes a purchase on the Odoo store, an Aliexpress order is triggered to send the product directly to the customer!

I'm sure it's possible because an application for ODOO SH exists: Odoo aliexpress dropshipping in OdooAppStore
But PLEASE: make this app public with standard subscription just like Ebay connector or Amazon connector.

For God's sake, please, I can make millions € with this power. Hope you can do this for the love of dropshipping. I challenge FABIEN PINCKAERS AND ANTONY LESUISSE and all the DEV STAFF to create this aliexpress application. Thanks if you can. I love you.

Just a lost Frenchman: Joel

**Comment by WeeskyBDW** [comment]
Hello
they is https://apps.odoo.com/apps/modules/16.0/odoo_aliexpress_dropshipping/, that prob what do you want. If your desire is more specific, you can contact an odoo integrator for doing the module you exactly want (they are french integrators)

- A baguette

**Comment by frenchwish** [comment]
Hello, it's nice but I mentioned that app, so I would like to you put the
app in the standard subscription. Because this app is for odoo.sh only and
you must pay 100€/mounth for use odoo.sh I don't have enough money for now
x) make it public and official for normal subscription WOW XD

A baguette too.

**Comment by frenchwish** [comment]
@WeeskyBDW How can I contact an odoo integrator, I don't know how please ^^'

**Comment by WeeskyBDW** [comment]
Oups sorry for late responce
> Hello, it's nice but I mentioned that app, so I would like to you put the
app in the standard subscription. Because this app is for odoo.sh only and
you must pay 100€/mounth for use odoo.sh I don't have enough money for now
x) make it public and official for normal subscription WOW XD

> A baguette too.

Odoo.sh is a service where you can easly host your odoo instance but you can install in on a machine you have or you rent (search for VPS or dedicated server provider on google, "hébergeurs" in french).
They is a guide [here](https://www.odoo.com/documentation/16.0/fr/administration/install/install.html#packaged-installers)

**Comment by WeeskyBDW** [comment]
If you have no further questions/problems about that issue, feel free to close it (the issue)

**Comment by vava-odoo** [comment]
Hi @frenchwish AliExpress is not a planned development in standard Odoo.
Thanks for your suggestion @WeeskyBDW.
