### ISSUE TITLE
[16.0] Javascript Error while opening calendar app

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#118380]
Impacted versions:
16.0

Steps to reproduce:
With specific user when he tries to click and open the calendar app. 
This issue only happens with this specific user.
If I have a specific, let's say opportunity with meeting it opens well the calendar but opening directly the calendar give error

Current behavior:

Give the following javascript error.
UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: "attendees is not iterable"
OwlError: The following error occurred in onWillStart: "attendees is not iterable"
    OwlError@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:16257:5 (/web/static/lib/owl/owl.js:87)
    wrapError@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18703:23 (/web/static/lib/owl/owl.js:2533)
    onWillStart@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18746:29 (/web/static/lib/owl/owl.js:2576)
    useModel@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:47728:16 (/web/static/src/views/model.js:141)
    setup@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:25973:22 (/web/static/src/views/calendar/calendar_controller.js:43)
    setup@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:175453:15 (/calendar/static/src/views/attendee_calendar/attendee_calendar_controller.js:8)
    ComponentNode@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18483:28 (/web/static/lib/owl/owl.js:2313)
    createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21835:28 (/web/static/lib/owl/owl.js:5665)
    slot1@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:15:36 (/web/static/lib/owl/owl.js:5436)
    callSlot@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:19053:37 (/web/static/lib/owl/owl.js:2883)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:8:12 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:22:12 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:11:27 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:16:43 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18549:23 (/web/static/lib/owl/owl.js:2379)
    async*render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18817:26 (/web/static/lib/owl/owl.js:2647)
    setup/this.onActionManagerUpdate@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:57419:18 (/web/static/src/webclient/actions/action_container.js:15)
    trigger@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18368:18 (/web/static/lib/owl/owl.js:2198)
    _updateUI@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58509:17 (/web/static/src/webclient/actions/action_service.js:800)
    _executeActWindowAction@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58643:16 (/web/static/src/webclient/actions/action_service.js:934)
    async*doAction@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58927:24 (/web/static/src/webclient/actions/action_service.js:1218)
    async*selectMenu@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:60455:39 (/web/static/src/webclient/menus/menu_service.js:56)
    _openMenu@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:188750:27 (/web_enterprise/static/src/webclient/home_menu/home_menu.js:120)
    _onAppClick@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:188841:14 (/web_enterprise/static/src/webclient/home_menu/home_menu.js:211)
    template/hdlr4<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:49:42 (/web/static/lib/owl/owl.js:5436)
    mainEventHandler@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21648:25 (/web/static/lib/owl/owl.js:5478)
    listener@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:16504:20 (/web/static/lib/owl/owl.js:334)

Caused by: TypeError: attendees is not iterable
    updateAttendeeData@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:175606:40 (/calendar/static/src/views/attendee_calendar/attendee_calendar_model.js:91)
    async*updateData@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:175570:20 (/calendar/static/src/views/attendee_calendar/attendee_calendar_model.js:55)
    async*load@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:26216:38 (/web/static/src/views/calendar/calendar_model.js:53)
    load@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:47708:21 (/web/static/src/views/model.js:121)
    useModel/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:47739:15 (/web/static/src/views/model.js:152)
    wrapError/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18718:34 (/web/static/lib/owl/owl.js:2548)
    initiateRender/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18498:63 (/web/static/lib/owl/owl.js:2328)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18498:50 (/web/static/lib/owl/owl.js:2328)
    createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    slot1@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:15:36 (/web/static/lib/owl/owl.js:5436)
    callSlot@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:19053:37 (/web/static/lib/owl/owl.js:2883)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:8:12 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:22:12 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:11:27 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    initiateRender@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18505:23 (/web/static/lib/owl/owl.js:2335)
    async*createComponent/<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21837:36 (/web/static/lib/owl/owl.js:5667)
    template@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:16:43 (/web/static/lib/owl/owl.js:5436)
    _render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17791:38 (/web/static/lib/owl/owl.js:1621)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:17783:18 (/web/static/lib/owl/owl.js:1613)
    render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18549:23 (/web/static/lib/owl/owl.js:2379)
    async*render@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18817:26 (/web/static/lib/owl/owl.js:2647)
    setup/this.onActionManagerUpdate@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:57419:18 (/web/static/src/webclient/actions/action_container.js:15)
    trigger@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:18368:18 (/web/static/lib/owl/owl.js:2198)
    _updateUI@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58509:17 (/web/static/src/webclient/actions/action_service.js:800)
    _executeActWindowAction@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58643:16 (/web/static/src/webclient/actions/action_service.js:934)
    async*doAction@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:58927:24 (/web/static/src/webclient/actions/action_service.js:1218)
    async*selectMenu@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:60455:39 (/web/static/src/webclient/menus/menu_service.js:56)
    _openMenu@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:188750:27 (/web_enterprise/static/src/webclient/home_menu/home_menu.js:120)
    _onAppClick@https://kaeso16.n360.ao/web/assets/debug/web.assets_backend.js:188841:14 (/web_enterprise/static/src/webclient/home_menu/home_menu.js:211)
    template/hdlr4<@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js line 21606 > Function:49:42 (/web/static/lib/owl/owl.js:5436)
    mainEventHandler@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:21648:25 (/web/static/lib/owl/owl.js:5478)
    listener@https://kaeso16.n360.ao/web/assets/debug/web.assets_common.js:16504:20 (/web/static/lib/owl/owl.js:334)
Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10322162/231527199-d7218093-2938-4f1a-b161-4bbc73e51f66.png)
In this line attendees has a integer value only  and it's not a list so it gives an error.

Support ticket number submitted via odoo.com/help (optional):
3271854

**Comment by vava-odoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/d0bc61a2e2419c28c11e57804329697386d2c61f
