### ISSUE TITLE
[BUG] [16],[15] Problem in invoice template 

### ISSUE THREAD

**Issue by alisaeed** [odoo/odoo#118309]
HI
I see a problem in print invoice on odoo 15 and 16. Template is not working in invoice module.
I attached invoice file.
[Sales-Order-S00007.pdf](https://github.com/odoo/odoo/files/11210572/Sales-Order-S00007.pdf)

**Comment by niyasraphy** [comment]
hi @alisaeed ,
this is due to something wrong your odoo installation.

for debugging it:

* add report.url with value as url of your instance to system parameters
* see the wkhtmltopdf is installed and set up correctly

thanks

**Comment by vava-odoo** [comment]
Hi @alisaeed please re-open the issue it the problem is still there and provide more information
