### ISSUE TITLE
[9.0c] notifications mails is not translated and transifex template and default data_mail.xml template mismatch

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#11847]
Impacted versions: 9.0c

Steps to reproduce:

if you set your language ie. Spanish, set receive all notifications

Current behavior:
 All notifications was sended in English.  If you try to modify or preview mail in configuration/technical/mail/templates/ Notification Email , gets : Failed to render template <Template memory:7f2938eac150>

There:
 https://github.com/odoo/odoo/blob/9.0/addons/mail/data/mail_data.xml#L76
was added some condition that is not present in *.po files and transifex

Adding those lines to template, makes previews works , but mails still not translated and in the panel preview is on Spanish

Expected behavior:

Notification coming in Spanish.

**Comment by mart-e** [comment]
Fixed at d1cdb4f4b8e6f2f655bfa52c501b2079fbb86989, linked to 1320ad8cfebf39ce15eef43d597d9bc2ff3008a5
