### ISSUE TITLE
[Bug] Sale addon: confirmation email's "Expires on" isn't translated

### ISSUE THREAD

**Issue by WeeskyBDW** [odoo/odoo#118431]
Impacted versions: 16.0

Steps to reproduce:
     - Change your odoo language to any other than english (i personally tried French and German)
     - Add a working SMTP server on Odoo settings
     - Create a new quotation **with a validity date**
     - Click on "send by email" button and confirm
     In your smtp you will see the quotation confirmation email who contains  "Expires on" that isn't translated

Current behavior: email header is "Expires on" 

Expected behavior: should be the translation of "Expires on" based on odoo's language (or user one)

Video/Screenshot link (optional): ![image](https://user-images.githubusercontent.com/36575072/231709960-33daa57f-19c9-4f36-b229-d67b32653be5.png) 
![image](https://user-images.githubusercontent.com/36575072/231710999-5300a38d-f813-4409-9b50-ab058ea023d9.png)

Support ticket number submitted via odoo.com/help (optional):

additional information: it's a clean odoo 16 instance with only sale module installed. DB and filestore are clean too

**Comment by WeeskyBDW** [comment]
When i delete the weird character (NBSP) in sale/i18n/sale.pot and in sale/i18n/fr.po it work so idk if it's due to Transifex or anything else 
![image](https://user-images.githubusercontent.com/36575072/231779395-5c77cdac-f6c8-4832-aa9f-fd6445d1384a.png)

edit: the translation dont work even if i stop my IDE, reset HEAD to origin/16.0 and launch odoo from cli

**Comment by vava-odoo** [comment]
But ... there is no non-breakable space in that string :thinking:

**Comment by WeeskyBDW** [comment]
I tried on a clean docker env [here is my docker-compose](https://gist.github.com/WeeskyBDW/bbe8de8e8679bb0c6823d30e39178f68) and i builded odoo image for using today's release 20230413 and i can reproduct the problem so it's really not an issue due to my fault

**Comment by vava-odoo** [comment]
> But ... there is no non-breakable space in that string thinking

Apparently there was... Don't know how it happened. Will be corrected soon: https://github.com/odoo/odoo/pull/118563. Sorry about that

**Comment by WeeskyBDW** [comment]
np, is they a way to override that translation as a workaround until Monday ?
