### ISSUE TITLE
Odoo Enterprise Warning flanker not found, email validation disabled.

### ISSUE THREAD

**Issue by rafi16jan** [odoo/odoo#11840]
Impacted versions: Odoo Enterprise 9

Steps to reproduce: Run odoo.py

Current behavior: WARNING ? openerp.addons.website_crm_score.models.sales_team: flanker not found, email validation disabled.

Expected behavior: No warning

Video/Screenshot link (optional):

![screenshot 2016-04-27 at 17 32 10](https://cloud.githubusercontent.com/assets/7939687/14849593/06b21108-0c9e-11e6-9f80-a82036486583.png)

**Comment by sle-odoo** [comment]
Hi,
Flanker is an optional python library allowing to validate email addresses. If you don't need this feature, you can ignore this message.

**Comment by JKE-be** [comment]
Fixed in https://github.com/odoo/enterprise/commit/a7a61dcc9d07a65bd0bc41d5c555977e051b3cd3
