### ISSUE TITLE
[9.0c] Invoice sequence incorrect

### ISSUE THREAD

**Issue by Nickske157** [odoo/odoo#11859]
Impacted versions:All versions (updates to latest nightly does not fix the issue)

Steps to reproduce: unknown

Current behavior: Sometimes the next invoice number is incorrect
Seems to be that the numbers are skipped when a day passes
See screenshot
VF/2016/10306 -> 26/04/2016
GAP!!!
VF/2016/10309 -> 27/04/2016
GAP!!!
VF/2016/10311 -> 28/04/2016
VF/2016/10312 -> 28/04/2016
VF/2016/10313 -> 28/04/2016
VF/2016/10314 -> 28/04/2016
VF/2016/10315 -> 28/04/2016
As you can see in the screenshot, the next number is going to be 318 but needs to be 316

Expected behavior: Invoice number needs to be without gaps

![invoice_sequence](https://cloud.githubusercontent.com/assets/6742601/14898766/d7f83176-0d88-11e6-915a-a8a92f83c727.PNG)
![invoices](https://cloud.githubusercontent.com/assets/6742601/14898767/d80f8506-0d88-11e6-9ab6-c043efffcec5.PNG)

**Comment by csnauwaert** [comment]
Hello,

Actually when the sequence is no_gap there should not be any hole between the numbering, the reason behind that is that everything is inside the same transaction and if an error occurs everything is rollback which means the number that should have been assigned to the invoice as well. So the problem does not come from there. Most probably that you've used the account_cancel module and cancel or reset to draft some invoices which means that you don't see them, but if you validate them again, their number will fill the gap.

Best regards
