### ISSUE TITLE
[16.0]Wrong Default company for Portal user registration in multi website multi company environment.

### ISSUE THREAD

**Issue by eversatis** [odoo/odoo#118560]
Portal user registration in multi websites multi company settings not get the right default company.

I can reproduce the error on any V16 runbot.
Impacted versions: V16

Steps to reproduce:

Create website www.A.com with company A. www.B.com with company B.
Register a portal user on www.A.com, See the default company for the portal user in backend is company A which is correct.
Register another portal user on **www.B.com**, See the default company for the portal user in backend is still company A which is **not correct.**

Actually all portal users registered on any website with any company, the user default company all goes to the default company A. Any other companies is not working.

Thanks to anyone who will debug it and fix it.

Best regards

**Comment by vava-odoo** [comment]
Hi @eversatis 
Isn't it same issue as https://github.com/odoo/odoo/issues/118146?

**Comment by eversatis** [comment]
Hi @vava-odoo 
Actually, it is not the same. I checked the odoo15 portal registration. The wrong default company also exists in odoo15, but odoo15 do not have the shop restriction issue.

**Comment by sswapnesh** [comment]
Hey @eversatis 

I just checked on latest v16 and It seems working well.
Can you please verify if you have correct settings for "Shared Customer Accounts" for both of the Website. ?
![Screenshot (3)](https://user-images.githubusercontent.com/16624719/235320432-d9e31db4-d801-4f58-a688-261b94008d0b.png)

It should be Unchecked for both of the website if you want different company for both website.

**Comment by eversatis** [comment]
@sswapnesh You are right on this. Shared Customer Accounts must be unchecked to have the corrected company selected for multi-company-multiwebsite setting. And shop restriction issue will be also gone in such condition for issue [118146](https://github.com/odoo/odoo/issues/118146). But shop restriction issue still exist if Shared Customer Accounts is checked. You can close this ticket now. Thank you!

**Comment by vava-odoo** [comment]
Hi @eversatis I did the feedback. I'll let you know when I'm notified on a fix for this. In the meantime, I re-opened the issue

**Comment by sswapnesh** [comment]
> Why can not it selects the right company in condition Shared Customer Accounts is checked? 

@eversatis  If the User is shared across multiple website (which will have different company), It makes on sense to select the company in User. Adding comapny in the new user will block the access to other websites where the company is other than default one.

**Comment by eversatis** [comment]
@sswapnesh You are right on this. Default company user is working for every other company, but every other companies would not work for each other. It is logically contradictory.  Unless odoo changes its architecture to make an universal company, the Shared Customer Accounts unchecked setting seems necessary. @vava-odoo I think you can close the ticket again. Lol...
