### ISSUE TITLE
[9.0] account.move.line create method attempts to write to related fields

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#11850]
**Impacted versions:**
9.0

**Steps to reproduce:**
create payment for a sale order or do any other accounting transaction

**Current behavior:**
Related fields from account.move like ref, date, journal etc are written to, causing unneeded updates on account.move records. See create method of account.move.line

**Expected behavior:**
Related fields are already written to account.move record, no need to write them again.
Since the fields are also stored there will be no easy fix

**Comment by pedrobaeza** [comment]
This has to do with the way ORM handles this, so no easy solution. A workaround is to put the fields as readonly. Closing as no possible solution right now.
