### ISSUE TITLE
[16] NL translation for industry_fsm_sale portal template

### ISSUE THREAD

**Issue by razvanioan** [odoo/odoo#118570]
Impacted versions:
- 16

Steps to reproduce:
- create a FSM task
- add at least one product
- go to portal view
- change language to NL

Current behavior:
- Time & Material section link in sidebar shows up as "Tijd & amp; Materiaal"

Expected behavior:
- To be "Tijd & Materiaal"

The problem is that in [NL translation](https://github.com/odoo/enterprise/blob/16.0/industry_fsm_sale/i18n/nl.po#L647) there is a space between & and amp;

**Comment by niyasraphy** [comment]
hi @razvanioan ,
thanks for report. 

i tried updating the same in transifex and not able to save the change in Dutch language. may be @Yenthe666 can help us :eyes:

**Comment by Yenthe666** [comment]
It looks ok and as it should be in the sources though. Ref https://app.transifex.com/odoo/odoo-16/translate/#nl/$/437944304?q=text%3A'%26+Material'. I confirmed the term again.

**Comment by vava-odoo** [comment]
Hi @razvanioan could you confirm it is solved?
Thanks @niyasraphy and @Yenthe666 for the help.

**Comment by razvanioan** [comment]
I confirm that's ok now, thx
