### ISSUE TITLE
[Latest revision of V15 Enterprise] Errors manually raise in Python Layer doesn’t trigger an Error popup in POS

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [odoo/odoo#118621]
Impacted versions: 
- 15 Enterprise Latest Revision

Steps to reproduce:
- Write a small pos module that raises a User Error on python layer

Current behavior:
- Logs an uncaught promise error at console
- Does nothing on the UI

Expected behavior:
- Display an Error popup

Video/Screenshot link (optional):
- To be provided later today or tomorrow

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hello @EwetoyeIbrahim 
Can you provide more information/context?
Can you reproduce your error on the [runbot](http://runbot.odoo.com/runbot)? (blue door icon of the version row (15) with login/pwd as admin/admin)
Thanks,

**Comment by EwetoyeIbrahim** [comment]
I have not had the time but its a silly issue.

**Comment by vava-odoo** [comment]
@EwetoyeIbrahim Please re-open if you have steps to reproduce in _standard_ Odoo
