### ISSUE TITLE
Reference res_id in mako <'openerp.report.report_sxw._int_format'>

### ISSUE THREAD

**Issue by jorgenaranjoVauxoo** [odoo/odoo#1186]
Impacted versions:
7.0 and above

Steps to reproduce:

1.- Install module "ir_attachment_report_webkit" this module was created for reply  the error.
2.- Run  yaml test 
2.1 Configure Lang EN in field grouping [[1,1,1,1,1,1,1,1,1,1,-2]]   ( yaml test)
2.2 Create report.  (yaml test)
3.- In the server log you can see the error when report send res_id value  without formatlang, but the formatlang is still applied. The formatlang is a persistent format
4.- Runbot of test:
http://runbot-nosticky.vauxoo.com/#ir_attachment_res_id_bug_vauxoo_jorge

5.- Branch module:
bzr branch lp:~vauxoo/addons-vauxoo/report_ir_attachment_test_bug_dev_jorge

Current behavior:

For example:

o.res_id = 2,5               real value = 25

${get_res_name(o.res_model, o.res_id.val, "Test of o.res_id.val")}     This is correct
                                                             25

${get_res_name(o.res_model, int(o.res_id), "Test of int(o.res_id))")}   This is correct
                                                             25

${get_res_name(o.res_model, o.res_id, "Test of o.res_id")}    ERROR <'openerp.report.report_sxw._int_format'>
                                                           2,5

o.id = 30
${get_res_name(o._name, o.id, "Test of o.id")}   This is correct
                                                30

${get_res_name(o.res_model, 27, "Test of res_id 27")}     This is correct
                                                      27

![error class openerp report report_sxw _int_format](https://cloud.githubusercontent.com/assets/6587022/3587517/e569a094-0c39-11e4-9de0-0ede07c923dc.png)

Report result:

![ir_attachment_report_webkitpdf_003](https://cloud.githubusercontent.com/assets/6587022/3587617/c03e1d58-0c3a-11e4-859c-c347da63fd29.png)

Expected behavior:

Unless i specify that i want in formatlang the number, must be grouping

**Comment by Yenthe666** [comment]
Dear @jorgenaranjoVauxoo,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
