### ISSUE TITLE
The data source for the reset user's passwd through an email

### ISSUE THREAD

**Issue by huskier** [odoo/odoo#11861]
Impacted versions: 8.0

Steps to reproduce:  N/A

Current behavior: N/A

Expected behavior: N/A

Video/Screenshot link (optional): N/A

In Setting ->Users->a user form (e.g. foo) -> Button (reset user's passwd through an email)

After click the Button, there is a link with an IP address included. I wonder where is the data source for the IP address info? I want to change it manually.

Thanks.

**Comment by Yenthe666** [comment]
@huskier it takes the value from the parameter `web.base.url`, which you can find under settings > Parameters > System parameters.
@mart-e not a real issue, locky-lock.

**Comment by huskier** [comment]
Thanks @Yenthe666.

It works wonderful.

**Comment by Yenthe666** [comment]
@huskier no problem, best of luck!
