### ISSUE TITLE
[survey] can't save if multiple_choice question id start with id of other questions

### ISSUE THREAD

**Issue by aetna-softwares** [odoo/odoo#11873]
Impacted versions:
8.0, 9.0

Steps to reproduce:
I have a question of type "multiple_choice" with id = 1 and another question of type "freetext" with id 11

Current behavior:
Saving is not working because the code look at all values starting with 1_1* so including the answer of the question 11 which is a text so failed to insert in database

```
2016-05-02 08:52:31,577 1023 ERROR bayrol openerp.sql_db: bad query: INSERT INTO "survey_user_input_line" ("id", "skipped", "value_suggested", "quizz_mark", "date_create", "answer_type", "survey_id", "user
_input_id", "question_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('survey_user_input_line_id_seq'), false, 'test@test.com', 0.0, '2016-04-23 08:24:14', 'suggestion', 1, 199,
 1, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "test@test.com"
LINE 1: ...(nextval('survey_user_input_line_id_seq'), false, 'test@test...
```

Expected behavior:
We should filter the post dict only on 1_1_* (adding the underscore) to make sure we get only choices of question 1 (1_1_2 for example) and not answer of question 11 (1_11)

in survey.py, changing the line : 
`ca = dict_keys_startswith(post, answer_tag)`
by 
`ca = dict_keys_startswith(post, answer_tag+"_")`

solved the problem

**Comment by rim-odoo** [comment]
Please make a branch for Odoo 8.0 and I will review&merge it

**Comment by aetna-softwares** [comment]
Hi,

I just created the pull request on branch 8

**Comment by rim-odoo** [comment]
Finally merged in v8 https://github.com/odoo/odoo/commit/9fe930e6ba95a223fc56163d675e8d5a6485a6fc . Thanks for your patch & your patience :)
(it will be forward ported soon to v9)
