### ISSUE TITLE
[9.0C & 9.0E] Date format for specific languages is fully ignored in searches

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#11876]
Impacted versions: 9.0 Community & 9.0 Enterprise.

Steps to reproduce:
 - Install the Dutch language
 - Change the user its active language to Dutch
 - Go to a search view and search for the current date (02/05/2016 in Dutch)
 Example supplier invoices:
![image](https://cloud.githubusercontent.com/assets/6352350/14952859/889475fc-1064-11e6-8b4e-c45dfad103f2.png)
The date is the second of may, 2016. The system converts this to the 5th of february 2016.

 This problem is found all across Odoo: at supplier invoices, customer invoices, journal entries, ...:
 ![image](https://cloud.githubusercontent.com/assets/6352350/14952900/061befdc-1065-11e6-8f98-30924ba515f5.png)

Current behavior:
Date formats are not converting to the active language its date format.

Expected behavior:
Date formats convert to the active language its date format, not the native format.

**Comment by Yenthe666** [comment]
@nim-odoo something still seems off though. I now no longer get the option to search for the period and to search by date. For example:
Newest Odoo V9 ENT:
![image](https://cloud.githubusercontent.com/assets/6352350/15145632/0efea010-16b7-11e6-9da8-e79ff7ee06b4.png)

Before: 
![image](https://cloud.githubusercontent.com/assets/6352350/15145637/16f3519e-16b7-11e6-8ff1-60ca330b0494.png)

The option 'Zoek Datum bij' is gone.

**Comment by nim-odoo** [comment]
Hum, that's weird. How it behaves in French: https://youtu.be/ZcwB-hRSGGs
As soon as the format is correct (in this case, DD/MM/YYY), the option appears.

What is your date format definition?

**Comment by Yenthe666** [comment]
@nim-odoo the format for Dutch is `%d-%m-%Y`, so searching for 02-05-2015 works.
Wouldn't it be better to write a converter for this though? For example: when I do 02/05/2015 I should also be able to find them. By default in Belgium we tend to search for either 02-05-2015 or 02/05/2015 and both are probably used equally..
Wouldn't it be better to have some way around this?

**Comment by nim-odoo** [comment]
@Yenthe666 : I don't think a converter is such a good idea, for the same reason that moment is making this feature deprecated: https://github.com/moment/moment/issues/1407

> using `Date` to create a moment from string, passed from the user is extremely unpredictable, and it turns out to work somewhat and then bite you in an edge case when you're not careful
