### ISSUE TITLE
[16.0] An error occurs when upgrading l10n_jp module and account module

### ISSUE THREAD

**Issue by Ryoko04** [odoo/odoo#118867]
Impacted versions: 
V16.0

Steps to reproduce:
Upgrade l10n_jp module and account module in an environment where l10n_jp was already installed

Current behavior:
Error occurs and can't upgrade

Expected behavior:
No error

Video/Screenshot link (optional):
When upgrading l10n_jp, the following error occurs.
![image](https://user-images.githubusercontent.com/70553601/232665029-c46d66e7-972e-47f2-aeb9-c23e948e3bb0.png)
And when upgrading account module, the system stopped.

https://github.com/odoo/odoo/pull/112278 could be the reason.

@qrtl

**Comment by tong-odoo** [comment]
Hi @Ryoko04, May I ask which page will show this Validation Error? A video link will be better if possible. Since I tried the upgrade script on my end and could not reproduce this error.

**Comment by rinaldifirdaus** [comment]
Hi @tong-odoo , the validation error will be shown when we upgrade the l10n_jp or the invoice module on apps menu.
here is the video link for your reference:
https://drive.google.com/file/d/1WqRYg3HZxhqAvf36rGBNpe8eFv4AX9ud/view?usp=sharing

**Comment by tong-odoo** [comment]
Hi @rinaldifirdaus, the reason of this error showing is because the tax group id changed but the taxes are still referencing the tax group records. However, if the upgrade script should put all account.tax.group into noupdate so no tax group should be deleted.
May I ask how do you upgrade Odoo from 15.0 to 16.0? I might need more information to troubleshoot your issue.

**Comment by tong-odoo** [comment]
@rinaldifirdaus The below screenshot is for your reference after I upgrade the database to Odoo 16. 
![image](https://user-images.githubusercontent.com/85471608/233244945-266db279-19e1-4dc0-9c74-2ae829b6cd6e.png)

**Comment by yostashiro** [comment]
@tong-odoo The issue we raise is not about upgrading from 15.0 to 16.0, but about upgrading the account module of an existing 16.0 database (which was created before https://github.com/odoo/odoo/pull/112278) after updating the Odoo code.

Why did you change the xml ids of the records? These are breaking changes, aren't they?

**Comment by tong-odoo** [comment]
@yostashiro In this case, you are right. They are not breaking if for upgrade or new database. I will make a commit to include both xmlid for 16.0 in this case

**Comment by yostashiro** [comment]
@tong-odoo Does that mean that upgrading the account module will generate a whole bunch of new account and tax records?

**Comment by tong-odoo** [comment]
@yostashiro For account and tax, since they are using template, so the original record will use the old one. But for new company, when it initialize the account and tax, they will use the new template to generate them.

**Comment by tong-odoo** [comment]
@yostashiro You could follow the status in #119139 for this issue
