### ISSUE TITLE
The account move (OPEJ/2014/001) for centralisation has been confirmed.

### ISSUE THREAD

**Issue by atuljain** [odoo/odoo#1188]
this is the bug in opening balance entries.
i created opening entries for supplier with credit amount 25000 and posted the entry.
as on 1-apr-2014 (starting financial year). 

and in july 1 i have make the payment of that supplier and when i created the payment it produces error The account move (OPEJ/2014/001) for centralisation has been confirmed.
screen shoot is attached. 
![screen shot 2014-07-15 at 9 53 14 pm](https://cloud.githubusercontent.com/assets/4609643/3587811/b9a2db12-0c3c-11e4-9a71-0f80a059fccc.png)

**Comment by Samba-Odoo-Apps** [comment]
Hi atuljain, Do you got solution for this?

**Comment by Yenthe666** [comment]
Dear @atuljain,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by lefas** [comment]
I have the same problem on Odoo 8
