### ISSUE TITLE
iframe video in form HTML fields not saved

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#11899]
Impacted version: Odoo 9.0c-20160413 Community Edition

On a form view with HTML field, click on the Insert Media button on the RTE, choose Video, type in Youtube URL, then Save. This will add the video on to the editor as an iframe. It works while in the editor but when saving the form, the iFrame is stripped out. When editing the form again, in the editor when I open the source, the iframe is gone.

**Comment by JKE-be** [comment]
That can arrive if the field is defined with sanitize=True in code.
So you can override the field with a sanitize=False in custom module.

I let the issues open in 'wishlist'. Because it could be interesting to add a new feature (in next version) to update it via the setting ir.model.field.

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report. This does not mean it will not be handled but we close them to keep a good and structured overview of the Github issues. If at some point we still want to change this behaviour we'll come back to this.
P.S: As mentioned, you could work around it with `sanitize=False` for now.

Regards,
Yenthe
