### ISSUE TITLE
Project -> Task should have filter on custom properties

### ISSUE THREAD

**Issue by hoanghai123** [odoo/odoo#119008]
Impacted versions: 16

Steps to reproduce:

Current behavior: When search tasks, there's no filter for custom properties

Expected behavior: When search tasks, there should have filter for custom properties

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/20239021/232964338-6d335e9c-8f04-4f65-8374-4aa3df42ca84.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @hoanghai123 ,
please see the response for: https://github.com/odoo/odoo/issues/116284

**Comment by hoanghai123** [comment]
Thank you @niyasraphy
