### ISSUE TITLE
[9.0e] Unable to xpath to field with attribute 'nolabel=1'

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/odoo#11914]
**Impacted versions:**
9.0e

**Steps to reproduce:**
Create xpath to field with attribute nolabel="1"

**Example of a field:**
`<field name="purchase_warn" nolabel="1" />`

**Example of the xpath expression:**
```
<record model="ir.ui.view" id="ravago_customer_model">
            <field name="name">ravago.customer.extension</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="warning.view_partner_warning_form"/>
            <field name="arch" type="xml">
                <xpath expr="//field[@name='purchase_warn']" position="before">
		                    <h3>test</h3>
                </xpath>
            </field>
        </record>
```
When I removed the attribute 'nolabel="1"' in the xml view, the xpath expression did work.

**Current behavior:**
Creates odoo server error. The xpath expression does not find the related field.

**Expected behavior:**
Xpath to the related field

**Comment by Yenthe666** [comment]
@mart-e this is something that we ran in to today. Is there a clear reason / purpose why we cannot xpath to a field with `nolabel="1"` in the field or is this a true bug?
It is almost impossible to xpath easily into the contact view for the warning part.

**Comment by Yenthe666** [comment]
@mart-e sorry to bug you again, could you give us some feedback on this?

**Comment by mart-e** [comment]
![warning](https://cloud.githubusercontent.com/assets/564822/15115285/8d422474-15fe-11e6-81a3-06d943ae0f4e.png)

hmm it seems to work (copy paste of above example)

**Comment by Yenthe666** [comment]
@mart-e thanks for the response. So you copied the above example code in an empty (new) module and everything worked out of the box?

**Comment by mart-e** [comment]
@Yenthe666 I did it in a existing module for a quick test (if you believe this is related, it should already gives you a good hint - `depends` - :wink: ).
Giving the traceback would already be a good first step to debug.
