### ISSUE TITLE
Time zone display problem

### ISSUE THREAD

**Issue by xiasun** [odoo/odoo#11918]
Impacted versions: 8.0

Steps to reproduce: 
Use `<td><t t-esc="diagnosis.create_date"/></td>` in template.xml to display create date on a customized page. 
User preference timezone has already been set.
`create_date` here is automatically generated by odoo.

Current behavior: Datetime shown is not at current timezone.

Expected behavior: Datetime shown should be at current timezone.

Video/Screenshot link (optional): N/A

**Comment by krutarthbuch** [comment]
Hello,

You may try *|<td><t 
t-esc="formatLang(diagnosis.create_date,date_time=True)"/></td>|*|

Hope this will help you.

Thanks.

Regards,
Krutarth Buch
Team Leader,
Serpent Consulting Services PVT LTD.
website : www.serpentcs.com <http://www.serpentcs.com/>
skype : krutarth.buch
|

**Comment by xiasun** [comment]
Thank you so much but i got error `"'NoneType' object is not callable" while evaluating
'formatLang(diagnosis.create_date,date_time=True)',`. The `diagnosis.create_date` is certainly a record, Do you have any idea?

**Comment by Yenthe666** [comment]
Hi @xiasun,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
