### ISSUE TITLE
messaging recipients are not notified of each other

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1191]
When sending a message to multiple of recipients (via messaging or through a project task, po, etc), emailed recipients are not notified of each other. Causes problems when including groups of contacts (no one knows who got the message) and reply-all does not have the intended result (the reply only goes to the original sender).

***Impacted versions:***
Version 7.0-20140709-231246

***Steps to reproduce:***

 1. Send a message from any module
 2. Select multiple recipients, that will receive via email
 3. Send message

***Current behavior:***

 - Recipients don't know who's received the message, and cannot "reply all".

***Expected behavior:***

 - Recipients see each other in the cc, and can "reply all".

**Comment by Yenthe666** [comment]
Dear @rolandwells,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
