### ISSUE TITLE
Overlap on date widget when chrome autofill is enabled

### ISSUE THREAD

**Issue by ssaid** [odoo/odoo#119280]
Impacted versions: 12.0

Steps to reproduce: Open a datepicker selector

Current behavior: Overlapping occurs and visibility is obstructed

Expected behavior: No overlap must occur

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/9728965/233453240-e91e228c-dae5-40df-a091-35c7f3c7e091.png)

Support ticket number submitted via odoo.com/help (optional): n/a

**Comment by ssaid** [comment]
The issue is when autofill form data is enabled in chrome

**Comment by vava-odoo** [comment]
Hi @ssaid 
This version is not supported anymore, so I'm not sure the PR will be taken into account. 
Closing the issue, but leaving the PR for the assigned team to review.
Regards

**Comment by dipak-shah** [comment]
> Hi @ssaid This version is not supported anymore, so I'm not sure the PR will be taken into account. Closing the issue, but leaving the PR for the assigned team to review. Regards

Same issue in V16 too. please have someone to fix. Thank you so much!

**Comment by niyasraphy** [comment]
there is PR fixing the same: https://github.com/odoo/odoo/pull/123606

**Comment by niyasraphy** [comment]
Fixed in 16 and above in this commit:  https://github.com/odoo/odoo/commit/e0ccfc9160ff7f3f367c3f0e4ace579c0486eb73
