### ISSUE TITLE
[Bug][Spreadsheet][16.0][Critical] : When reloading, the spreadsheet.

### ISSUE THREAD

**Issue by dipak-shah** [odoo/odoo#119290]
Impacted versions: [16.0 E]

Steps to reproduce:
- Open any listview (e.g  Sales order listview)
- select records from the listview, go to **Favorites**, and click on **'Insert list in spreadsheet'** option
- Once the spreadsheet is created, Reload your browser.

Current behavior:
- Spreadsheet goes to an infinite loading.

Expected behavior:
- It should refresh the result of data contained under the spreadsheet with no error, no loading issue.

Video/Screenshot link (optional):
**Video Recording :** [Spreadsheet_Loading_issue.webm](https://user-images.githubusercontent.com/36708909/233527037-4877f2da-6015-4e90-adde-30dfaa378c4b.webm)

![image](https://user-images.githubusercontent.com/36708909/233527139-92151574-4cc6-4a8f-b864-51fdf7bd6ee8.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by LucasLefevre** [comment]
https://github.com/odoo/odoo/pull/119488
