### ISSUE TITLE
Wish: datetime interval support hour

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#11936]
Impacted versions:
- 9.0

Steps to reproduce:

Current behavior:

Expected behavior:

_read_group_process_groupby just support 'day', 'week', 'month','quarter','year',

if i hava many records in one day, there is no way to show each record in graph view

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e could you give your input on this one? I honestly think it would be neat if we could make an hour interval. It may improve usability for some people / companies and it is not much extra code.

**Comment by mart-e** [comment]
I agree, it could be useful and it shouldn't be too hard to implement.
Submitting request to R&D

**Comment by yelizariev** [comment]
FYI
I've created a module that implement hourly grouping
https://github.com/it-projects-llc/misc-addons/blob/10.0/base_groupby_extra/models.py#L21-L28

**Comment by Yenthe666** [comment]
@mart-e could you tell us what happend with the R&D request?

**Comment by pedrobaeza** [comment]
This has been merged in latest master version, so closing.
