### ISSUE TITLE
[account] Generate Opening Entry Wizard does not filter posted entries from unposted  ones when creating Opening Entries in next Fiscal Year

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#1193]
[account] Generate Opening Entry Wizard does not filter posted entries from unposted  ones when creating Opening Entries in next Fiscal Year

0.) Blank demo DB with account installed
1.) Create a 2015 FY and its periods.
2.) Menu Accounting >> Periodic Processing >> End of Period >> Generate Opening Entries.
3.) Fill with appropriate data,
4.) Hit Create,
5.)  You should only see Entry Lines that comes from posted entries, It is not the case.

Best Regards.

**Comment by bsphil** [comment]
Seconding this.  The balance calculation just doesn't care if the entries are posted or not.  This should be an easy fix, too:

https://github.com/odoo/odoo/blob/8.0/addons/account/wizard/account_fiscalyear_close.py#L228

Just set the context to also include 'state': 'posted' and the balance should be accurate.

**Comment by snusken** [comment]
@bsphil: The status booked from an accounting point of view is the status where somebody has reviewed the ítem and validated it. Especially supplier invoices or credit memos, which can be also posted from people outside of accounting or Banks are very often subject to those entries. It doesn't makes sense to allow the system to transfer saldos from one fiscal year into the next one when the status of those entries is unbooked as the evidence of those entries could be false and the sense of the status is transferred to ad absurdum.

**Comment by Yenthe666** [comment]
Hi @hbto,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by hbto** [comment]
Oh thanks for your reply

Quien suscribe,

*Hbto*
