### ISSUE TITLE
Debug/Developer Mode Not Working In Latest Nightly

### ISSUE THREAD

**Issue by OptrixAU** [odoo/odoo#11935]
**Impacted versions:**
Odoo 9.0c-20160505 (Community Edition)
Note that I only very recently installed another version on a different system which did not have this issue, indicating it's a problem with the new nightly build. 

**Steps to reproduce:**
Click on the arrow next to your username in the top right corner, press 'About' in the drop-down menu, and click on 'Activate The Developer Mode'

Alternatively, you can just add the '?debug=' before the hash in any valid odoo URL.

**Current behavior:**
The following page is empty (no matter _which_ page you try to open). You get the black bar across the top of the screen, but no odoo sidebar and no page content. The basic framework HTML is present, but no content from the modules requested.

There are no entries in the log file that indicate a specific problem - just regular access logs.

**Expected behavior:**
I'd expect to see the page as normal, plus (in some cases) the additional content for the developer mode.

As I'm trying to activate a newly-installed addon, I **need** access to the developer mode to reload the addin list.

**Comment by JKE-be** [comment]
Could you make a 'clear cache' refresh (ctrl + F5 under chrome) once in you are in debug mode ! And take a look in console JS, maybe a warning ? Can you still reproduce the problem now ?

**Comment by OptrixAU** [comment]
A full cache-clear (done via the Settings menu) fixed the issue, which must have been a residual problem from an accidental installation of Odoo 8. Odd that Chrome didn't refresh the cached copy though. 

Thanks.
