### ISSUE TITLE
Ipad/Iphone google chrome not opening pdf in ibooks

### ISSUE THREAD

**Issue by salishaukat** [odoo/odoo#11938]
Impacted versions:
9.0e and 9.0c

Steps to reproduce:
print pdf in ipad/iphone google chrome a report will open in new tab next try it to open in ibooks

Current behavior:
Wrong or corrupted file is downloading when open in ibooks through google chrome ipad/iphone

Expected behavior:
Should open correct pdf file through google chrome in ibooks

Video/Screenshot link (optional):

**Comment by jorenvo** [comment]
From where exactly are you printing the report?

**Comment by Yenthe666** [comment]
I'm closing this bug report as there has never been any feedback.
