### ISSUE TITLE
Odoo 9 Too Slow on Windows

### ISSUE THREAD

**Issue by Cywaithaka** [odoo/odoo#11932]
Impacted versions: 9.0

Steps to reproduce: I have deployed odoo 9 POS on a windows PC with the following specs. 

`------------------
System Information
------------------
      Time of this report: 5/4/2016, 18:53:13
             Machine name: POS
         Operating System: Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release_sec.160328-1908)
                 Language: English (Regional Setting: English)
      System Manufacturer: POSIFLEX
             System Model: XT-3015
                     BIOS: Default System BIOS
                Processor: Intel(R) Atom(TM) CPU D525   @ 1.80GHz (4 CPUs), ~1.8GHz
                   Memory: 2048MB RAM
      Available OS Memory: 2038MB RAM
                Page File: 1960MB used, 716MB available
              Windows Dir: C:\Windows
          DirectX Version: 9Ex
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10586.0000 64bit Unicode
`
Unfortunately, everything is loading very slowly, even though I am accessing the POS from the same PC on which it is installed. Some orders, especially the first order made from the touch screen in a session is also not getting uploaded to the server. Report printing, is also taking very long.
Is there anything I can do to speed up the system?

Current behavior:

Expected behavior: The expected behavior is that odoo should be faster when used in a localhost setup. The POS touch screen should upload the orders immediately.

Video/Screenshot link (optional):

**Comment by tesserB** [comment]
Cywaithaka:
     Are you still having issues with this? If so, just let me know and I will do what I can to help. In the meantime, try some of the following as a hold over:

Disabling unnecessary services (e.g., "iPod Helper") and Startup items, via Windows-Logo+R>"msconfig". You can google for guides on this if need be.

Adjusting "Performance: Visual Effects, processor scheduling..." Settings, via Windows-Logo+R >"sysdm.cpl,3", which will bring you to the "Advanced" tab of the "System Properties" menu. Here, you will want to configure "Visual effects" to favor performance.

Adjusting the "Process Priority" of Odoo and PostgreSQL to "High", via the "Details" tab within Task Manager (Right Click them). You may also wish to "End Process" Explorer.exe, via the Task Manager, if you're not using the desktop, menus, etc. If you should need it back, Ctrl+Alt+Delete > Task Manager > File > Run new task> explorer.exe

Sincerely,
Cody K.
ckitterm@gmail.com

**Comment by tesserB** [comment]
@mart-e I was going to spin him up on multi-threading and the limit_'s, too, but I think we're good here. Care to close?

**Comment by mart-e** [comment]
Thanks for your reply Cody.
Indeed the github issues is to reports bugs, not to search for help (for that you may want to check [mailing lists](http://odoo.com/groups), [forums](https://www.odoo.com/forum/help-1/), support, etc.)

**Comment by tesserB** [comment]
@mart-e sorry, man... If you would like to close again...
