### ISSUE TITLE
[sale/sale.order] bug : update_prices method reset discount 

### ISSUE THREAD

**Issue by WeeskyBDW** [odoo/odoo#119316]
Impacted versions: 15.0

Steps to reproduce:
    - Install sale module
    - Enable discount in Settings -> Sale
    - Go to Sale module and create a quotation 
    - Add a product to the quotation and set it a discount
    - Save the quotation
    - call the update_prices method of sale.order model (with XML RPC for example, i tried with "Odoo terminal" extension but it's equal to first solution)
    - reload the page

Current behavior: discount is reset

Expected behavior: discount should stay if not equal to 0

Video/Screenshot link (optional): [1FbH0uAl.webm](https://user-images.githubusercontent.com/36575072/233580677-feacdcc0-8ef4-45bf-b4d9-677a36667ea8.webm)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @WeeskyBDW 
Thanks for the report. Is is a standard flow, or do you call the method from a separate module?
Thanks

**Comment by WeeskyBDW** [comment]
yes i call it from another module but as i stated before it's the same issue if i call the method manually

**Comment by vava-odoo** [comment]
Hi @WeeskyBDW 
I wouldn't call it a bug, it seems like you try a different (non-standard) flow and it does not work.
The fact that discounts are reset to 0 is hard-coded in the method: https://github.com/odoo/odoo/blob/15.0/addons/sale/models/sale_order.py#L528
This will not be changed in a stable version.
Regards
