### ISSUE TITLE
[>8.0] Accesing values through several NewId objects

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#11930]
Impacted versions: 8.0, 9.0 and master

Steps to reproduce:
- Program an onchange for a field in product.pricelist.item object.
- Go to Sales > Configuration > Pricelists > Pricelists.
- Create one pricelist
- Without saving, create a pricelist version.
- Without saving, create a pricelist item.
- Change the value for triggering the onchange.
- Query the value in `self.price_version_id.pricelist_id.type`.

Current behavior:

The returned value is `False`.

Expected behavior:

The returned value should be `'sale'`.

Inspecting progressively the values, `self.price_version_id` contains a reference to a NewId class. `self.price_version_id.pricelist_id` points to an empty recordset instead of pointing to another NewId class that corresponds to the on-memory created pricelist.

@rco-odoo, please check this one.

**Comment by andrius-preimantas** [comment]
I confirm this one is still not solved. At least not for the product.pricelist.item

**Comment by Yenthe666** [comment]
@pedrobaeza could you check if it is relevant for V10/V11 too? If this is I'll make sure it gets the attention it never got.

**Comment by Yenthe666** [comment]
@pedrobaeza can you give an update please?

**Comment by pedrobaeza** [comment]
Closing as I can't reproduce it right now (taking into account that there are no 3 level now in pricelists).
