### ISSUE TITLE
 wkhtmltopdf is no longer maintained

### ISSUE THREAD

**Issue by DieterReinert** [odoo/odoo#119455]
Impacted versions:
14.0, 15.0, 16.0

Are there any plans to drop wkhtmltopdf since the project has ended?

**Comment by gdgellatly** [comment]
try searching the issues first, also twitter more recently, there is plenty on this topic and been discussed for years, including the current plans. But in short, the answer is yes/no/maybe

**Comment by niyasraphy** [comment]
@DieterReinert https://twitter.com/bouvyd/status/1631574855198941184
