### ISSUE TITLE
wkhtmltopdf version support ? ( latest is public archive now.)

### ISSUE THREAD

**Issue by zhephirothz** [odoo/odoo#119451]
Since wkhtmltopdf on their repository (https://github.com/wkhtmltopdf/wkhtmltopdf)
show as Public archive and ODOO still require this library to generate a qweb report to PDF.

There are alternative libraries to replace wkhtlmtopdf for now ?
Are there any plan on future approach ? 

Do we use the wkhtmltopdf library or we can work with a new one ? and which one ?

**Comment by vava-odoo** [comment]
Hi @zhephirothz 
Here is the answer: https://twitter.com/bouvyd/status/1631574855198941184
So in short: we continue with it until ... 
Regards
