### ISSUE TITLE
Wrong ID after save in a One2many field inside a model which _inherits res.partner

### ISSUE THREAD

**Issue by mepsteinj** [odoo/odoo#119443]
Impacted versions: 16.0

Steps to reproduce:
I have a model "healthcare.patient" (Patient) which inherits "res.partner" and this model have a One2many field with the Patient family members (family members are Patients to), and here is the problem.
In the dopdown list I can select other patients to add as a family member, but every time I add a new family member and save, the stored family member is always the patient to which I am adding the family member.

Code:
```
# Patient Management
class HealthcarePatient(models.Model):
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many('healthcare.family', 'patient_id', string='Family')


# Family Management
class HealthcareFamily(models.Model):
    _name = 'healthcare.family'
    _description = 'Family Information'
    _rec_name = 'patient_id'
    _order = 'sequence, patient_id'

    patient_id = fields.Many2one(
        'healthcare.patient',
        string='Patient',
        required=True,
        ondelete='cascade',
        index=True
    )
    sequence = fields.Integer(string='Sequence', index=True)
```
Current behavior:
The stored ID in "healthcare.family" is always the patient to which I am adding the family member even if you select another patient.

Expected behavior:
Store the correct id for the selected family member.

Video/Screenshot link (optional):
Before save I have selected "Jose Blanco Machado" as a family member:
![1-before](https://user-images.githubusercontent.com/1680209/233744025-e72f6517-6cbb-451d-9dc6-68a83afc5d04.png)
After save, "Ana Luisa Roble Nada" is the stores family member:
![2-after](https://user-images.githubusercontent.com/1680209/233744150-cc84a0d0-52be-446a-9359-b5ba96b4d951.png)

**Comment by Zmiklu** [comment]
One way to achieve this is by adding a widget to the One2many field "family_ids" in the "healthcare.patient" model. The widget should allow you to select other patients as family members and store their IDs correctly

**Comment by Zmiklu** [comment]
``# Patient Management
class HealthcarePatient(models.Model):
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many(
        'healthcare.family',
        'patient_id',
        string='Family',
        widget='many2many',
    )

**Comment by Zmiklu** [comment]
`# Patient Management
class HealthcarePatient(models.Model):
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many(
        'healthcare.family',
        'patient_id',
        string='Family',
        widget='many2many',
    )
`

**Comment by Zmiklu** [comment]
`
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many(
        'healthcare.family',
        'patient_id',
        string='Family',
        widget='many2many',
    )
`

**Comment by Zmiklu** [comment]
`class HealthcarePatient(models.Model):
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many(
        'healthcare.family',
        'patient_id',
        string='Family',
        widget='many2many',
    )`

**Comment by Zmiklu** [comment]
class HealthcarePatient(models.Model):
    _name = 'healthcare.patient'
    _description = 'Patient information'
    _inherits = {
        'res.partner': 'partner_id',
    }

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='restrict',
        index=True
    )
    family_ids = fields.One2many(
        'healthcare.family',
        'patient_id',
        string='Family',
        widget='many2many',
    )

**Comment by mepsteinj** [comment]
> One way to achieve this is by adding a widget to the One2many field "family_ids" in the "healthcare.patient" model. The widget should allow you to select other patients as family members and store their IDs correctly

Thank you for your reply @Zmiklu
Tested but it doesn't work. Same results.
I think this is a problem with "res.partner" because "product.product" uses the same implementation for "product.packaging"

**Comment by mepsteinj** [comment]
Well, I feel really dumb about this right now... The solution is simple.
The field patient_id is the relational field between 'healthcare.patient' and 'healthcare.family', of course the id in this field must be the id of the patient I'm editing.
I just added a new field to 'healthcare.family':

```
    family_id = fields.Many2one(
        'healthcare.patient',
        string='Family',
        required=True,
        index=True
    )
```
and... problem solved.

Thank you guys for this great software.
