### ISSUE TITLE
What's the different between /web/database/selector and /web/database/create  ?

### ISSUE THREAD

**Issue by luochen1990** [odoo/odoo#119447]
Impacted versions:

`odoo-15.0.20230317`

Steps to reproduce:

Just enter `http://127.0.0.1:8069/` in web browser.

Current behavior:

When inside `/web/database/selector`, there is two button, `Create database` and `restore a database`

![image](https://user-images.githubusercontent.com/2309868/233771763-12ef8e18-f424-4784-84e4-7bb2148a3a90.png)

Expected behavior:

I'm not sure, but, when inside `/web/database/selector`, I'm expecting a database list, and I just choose an existing one.  

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @luochen1990 
Just tried on the [runbot](http://runbot.odoo.com/runbot) (blue door icon of the version row (15) with login/pwd as admin/admin) but the problem seems solved (_selector_ gives a list and _create_ is unavailable).
Feel free to re-open the ticket if it is not the case.
Regards
