### ISSUE TITLE
[account] A FiscalYear is allowed to be closed without Generating Opening Entries in the next FiscalYear

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#1195]
A fiscalyea can be selected to be closed and not prior Opening Entries are been generated to the next fiscalyear,

This is prone to error due to the fact that after it is not possible to create Opening Entries at the next fiscalyear.

Steps to reproduce:
0.) Blank demo DB with account installed
1.) Never Generate Opening Entries for the next FiscalYear.
2.) Menu Accounting >> Periodic Processing >> End of Period >> Close a FiscalYear.
3.) Fill with appropriate data,
4.) Hit Close a FiscalYear.

Thanks in advance for your cooperation

Best Regards.

**Comment by Yenthe666** [comment]
Hi @hbto,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
