### ISSUE TITLE
Hidden content menu in website on selected other language 

### ISSUE THREAD

**Issue by Develoman** [odoo/odoo#11965]
Impacted versions:9.0c

Steps to reproduce:choose other language like french or Arabic language in website footer  

Current behavior: content menu still existing

Expected behavior:content menu will be hidden

Video/Screenshot link (optional):
![ar_content_menu](https://cloud.githubusercontent.com/assets/12783685/15110504/40e727fc-15d9-11e6-8ee4-fb85ec95f890.png)
![fr_content_menu](https://cloud.githubusercontent.com/assets/12783685/15110503/40e60caa-15d9-11e6-8a7d-33b66f2af798.png)
![en_content_menu](https://cloud.githubusercontent.com/assets/12783685/15110502/40e57466-15d9-11e6-837a-8c43b2f8db6a.png)

**Comment by treviser** [comment]
I don't know what you expect. The content menu is only available in the website's default language and this makes sense.

**Comment by Develoman** [comment]
I choose French language for example for a user, then the user don't found the content menu! Why!
i think that,The Manager content Menu is independent from the website's language. 
I can select any language from website other than my default language , and the content menu must still available!

**Comment by treviser** [comment]
No. The default language website is the master for website editing, the other sites must only be translated. If a user who has a preference language other than the website's default language wants to edit the website, he has to choose the default language on the website's language selector.

**Comment by Develoman** [comment]
Ok That's Now  :+1: 
Just Must Edit the Default website Language in odoo 9 : website Administration >setting>default language.
Thx
