### ISSUE TITLE
9.0 ir.attachment: force_storage brakes mimetype

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#11978]
Impacted versions:
9.0+

Steps to reproduce:

call ``ir.attachment``'s method ``force_storage``
Current behavior:

mimetype becomes application/octet-stream instead of text/css and other. It brakes debug mode.

```
 Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "https://portal.seattlecannabisexchange.com/web_kanban/static/src/less/web.assets_backend/kanban_view.less.css".
```

Expected behavior:

mimetype must not be changed after force_storage call

**Comment by Yenthe666** [comment]
@yelizariev Odoo asks not to create issues when you make a PR, just to prevent noise in the issues / PR's, so perhaps this is best to close this issue?
@odony I like the idea of this. What do you think about this?
P.S: After your e-mail from yesterday I thought why not right away dive in. :wink:

**Comment by yelizariev** [comment]
@Yenthe666 I haven't made a PR to odoo repository. My commits are for the my module ir_attachment_force_storage

**Comment by pedrobaeza** [comment]
Is this still happening on latest versions? Do you plan to make any PR?

**Comment by yelizariev** [comment]
I believe it's still there. I made the PR https://github.com/odoo/odoo/pull/24397

**Comment by pedrobaeza** [comment]
Cool, then we can close this issue as it's referenced in the PR.
