### ISSUE TITLE
[8.0] Odoo ignores _order option in QWeb reports

### ISSUE THREAD

**Issue by Josecanalla** [odoo/odoo#11998]
Impacted versions: 8.0 (I try in nightly versions 2015-03-31 and 2016-04-27)

Steps to reproduce: develop a QWeb report or edit any existing modifying _order attribute of Python class associated with QWeb report.

Current behavior: Odoo sorts the report ascending in function of the "row" value.

Expected behavior: Odoo sorts the report in function of the "_order" attribute in Python class. I also try to sort the report in "descending" mode of the row value mentioned in the "Current behavior", but not works.

Video/Screenshot link (optional): portion of code: http://prntscr.com/b2goth

**Comment by Yenthe666** [comment]
@Gorash and @sle-odoo could you guys have a look at this please?

**Comment by Gorash** [comment]
The QWeb don't change the order of the browse record. May be an other order define in the search, context or controller.
@rco-odoo you have another idea that could alter the order?

**Comment by dreispt** [comment]
> Odoo sorts the report ascending in function of the "row" value.

@Josecanalla what is the "row" value?

**Comment by Josecanalla** [comment]
@dreispt I refer to this: http://prntscr.com/bh8scs in the xml file

**Comment by spadae22** [comment]
@Josecanalla I had this issue last week, we needed to print invoices in alpha order, so I used the sorted method. I am sure there is a better way, but works.
```
 def _get_invoice(self, docs):
        invoice_obj = self.pool.get('account.invoice')              
        invoices=invoice_obj.browse(self.cr,self.uid,docs)
        invoices=(invoices.sorted(key=lambda r: r.commercial_partner_id.name).ids)
        return invoices
```

**Comment by Josecanalla** [comment]
@spadae22 in the qweb reports the records are returned by a cr.execute command. How can I implement the sorted method in that case?

**Comment by Yenthe666** [comment]
Hi @Josecanalla,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
