### ISSUE TITLE
Project set_template vs setActive

### ISSUE THREAD

**Issue by gooofy** [odoo/odoo#11997]
I was wondering what the reasoning is behind project.py's set_template implementation which calls setActive directly:

```
    def set_template(self, cr, uid, ids, context=None):
        return self.setActive(cr, uid, ids, value=False, context=context)

```

setActive then does a lot of things (e.g. setting all tasks to inactive and setting the project state to 'template'), however it does not set the project itself to inactive, despite its name and comment:

```
    # set active value for a project, its sub projects and its tasks
    def setActive(self, cr, uid, ids, value=True, context=None):
        task_obj = self.pool.get('project.task')
        for proj in self.browse(cr, uid, ids, context=None):
            self.write(cr, uid, [proj.id], {'state': value and 'open'
or 'template'}, context)
            cr.execute('select id from project_task where
project_id=%s', (proj.id,))
            tasks_id = [x[0] for x in cr.fetchall()]
            if tasks_id:
                task_obj.write(cr, uid, tasks_id, {'active': value},
context=context)
            child_ids = self.search(cr, uid, [('parent_id','=',
proj.analytic_account_id.id)])
            if child_ids:
                self.setActive(cr, uid, child_ids, value, context=None)
        return True

```

what is the reason for this mix of template states and setting inactive flags? the current code will (for example) render project delegations invisible / uneditable for project templates (tasks will be marked inactive and hence be invisible).

if there is no deeper reason for this code, I suggest changing the set_template function to something along the lines of:

```
    def set_template(self, cr, uid, ids, context=None):
        for proj in self.browse(cr, uid, ids, context=None):
            self.write(cr, uid, [proj.id], {'state': 'template'}, context)
            child_ids = self.search(cr, uid, [('parent_id','=', proj.analytic_account_id.id)])
            if child_ids:
                self.set_template(cr, uid, child_ids, context=None)
        return True

```

Impacted versions:8

Steps to reproduce:
set project to template

Current behavior:
 -> tasks will disappear because they're set to inactive (e.g. affect delegation which is no longer visible/editable)

Expected behavior:
set project to template state, leave tasks active

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

Thanks a lot for your report / question and sorry for the late reply.
The Github issue tracker is only for bugs in the official code though, its not really the place to ask questions. You can do that on the official help forums at help.odoo.com.
As Odoo 8 is now end of life and as all the code has changed quite a bit I'm closing this bug report. I hope you understand.

Regards,
Yenthe
