### ISSUE TITLE
[Wishlist] Ability to configure search more limit of 160 records.

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12001]
Impacted versions:
9.0, 10.0, 11.0, master

Steps to reproduce:
- Create a many2one to a model that has more than 160 records.
- Click on "search more..". The hardcoded limit from Odoo in this search is 160 records, while there are more on the table. (in my example 2820 records)
  ![image](https://cloud.githubusercontent.com/assets/6352350/15173105/65492e6a-175a-11e6-965f-311a4e3d129d.png)

Current behavior:
Search views are hard code limited to 160 records.

In Odoo 9 under /web/static/src/js/views.js like this:

```
            // search more... if more results that max
            if (values.length > self.limit) {
                values = values.slice(0, self.limit);
                values.push({
                    label: _t("Search More..."),
                    action: function() {
                        dataset.name_search(search_val, self.build_domain(), 'ilike', 160).done(function(data) {
                            self._search_create_popup("search", data);
                        });
                    },
                    classname: 'oe_m2o_dropdown_option'
                });
            }
```

Expected behavior:
The harcoded search limit is configurable in the settings, in order to define your own limit in the whole Odoo database.

**Comment by Yenthe666** [comment]
@mart-e I'd like your input on this. Is this something that would be accepted as a PR on Odoo 10?
In case it would be accepted: where should the setting be stored in the Odoo database and how can I call the setting from a record in the database via the JS?
If this would be accepted and if I get a little bit of help I'll add this functionality.

**Comment by mart-e** [comment]
It is possible to access more than 160, it is just that, by default you get the first 160 but as soon as you make a new search, you will get the remaining ones.
It was done for performance reasons. We could do something smarter but not sure why.

**Comment by wtaferner** [comment]
@mart-e 
Are you sure? At least in version 8 the search within the modal was done on the filtered 160 records found before.

**Comment by Yenthe666** [comment]
@mart-e I know this is just the default that is only shown when the dialog opens, not when doing any other search. I do think that it would be great if you could configure this somewhere in the database for people that want to see "40" or "500" by default for example. 
@wtaferner: in Odoo 9 it does exactly what @mart-e says, not sure about 8 though.

**Comment by wtaferner** [comment]
@Yenthe666 
Ok, thx, did not test it or investigated in v9 but great that at least this was properly fixed.

**Comment by mart-e** [comment]
It was the case already in 7.0.

![screenshot from 2016-05-11 10-13-26](https://cloud.githubusercontent.com/assets/564822/15174274/12b4f574-1761-11e6-88ca-6182748cd66d.png)

![screenshot from 2016-05-11 10-13-42](https://cloud.githubusercontent.com/assets/564822/15174282/1ad469b0-1761-11e6-8b59-d47d0e0b0d27.png)

**Comment by wtaferner** [comment]
Ok, so my memory seems to have mixed it up ;-) I guess that was the reason why I did not fix it and told my users to search again...sorry :-)

**Comment by Yenthe666** [comment]
@mart-e thanks for adding the wishlist label. Now, let us go for a concept!
Where should this setting be configured / stored and would this be accepted with a PR against Odoo 10?

**Comment by mart-e** [comment]
@Yenthe666 I don't think it is something we want to configure as it is very low level. I would really prefer a proper fix that allow us to remove this hardcoded 160 (like not sending a huge list of ids but a domain or something).

**Comment by wtaferner** [comment]
What about getting a full set of records when the modal is opened?
This would be imho usability-wise and performance-wise a good trade-off.

**Comment by Yenthe666** [comment]
So this is still relevant up to today - @mart-e is there anything in the pipeline for this? 
CC @ged-odoo he might be able to answer as our main JS guy!

**Comment by mart-e** [comment]
We have discussed this some time ago internally. It is still not something we can do easily and requires some changes on how we manage this view.
So kind reminder for @ged-odoo, but nothing is the pipe as far as I know.

**Comment by pedrobaeza** [comment]
@mart-e I think this can be closed as there's nothing in the roadmap.

**Comment by ged-odoo** [comment]
for info, an (internal) task was created to solve this issue.  It is in the framework project, and may or may not be done in the future.  But it is still possible :)

**Comment by Yenthe666** [comment]
Good to know that there is a task for it. Thanks for the feedback!

**Comment by xiliaolong** [comment]
It working,thanks.

**Comment by titouanbrauchli** [comment]
Is it possible to change this limit in Odoo V12?

**Comment by asnetbeat** [comment]
> Is it possible to change this limit in Odoo V12?

odoo/addons/web/static/src/js/fields/relational_fields.js

```
// search more... if more results than limit
                if (values.length > self.limit) {
                    values = values.slice(0, self.limit);
                    values.push({
                        label: _t("Search More..."),
                        action: function () {
                            self._rpc({
                                    model: self.field.relation,
                                    method: 'name_search',
                                    kwargs: {
                                        name: search_val,
                                        args: domain,
                                        operator: "ilike",
                                        limit: 160,
                                        context: context,
                                    },
                                })
                                .then(self._searchCreatePopup.bind(self, "search"));
                        },
                        classname: 'o_m2o_dropdown_option',
                    });
                }
```

**Comment by Kashifaziz123** [comment]
Download this module it will increase record limits from 160 https://apps.odoo.com/apps/modules/10.0/fix_searchmany2one_limit/
