### ISSUE TITLE
[saas-16.2] When a quote is shared but not "sent" users get a "No suitable payment options could be found" error.

### ISSUE THREAD

**Issue by ngist** [odoo/odoo#120197]
Impacted versions: saas-16.2, possibly others

Steps to reproduce: 
1. Install sales plugin, enable online payment in the settings, and configure payment options.
2. Create a quote.
    a. Under "Other Info" ensure for "Online Confirmation" only "Payment" is selected.
    b. Create a non-zero amount on one of the quote lines.
    c. Save the quote but do not send it(once the quote is sent everything works as expected).
4. Click action->share to generate a share link for the quote.
5. Goto the share link  using incognito or when logged out of odoo. Click "Accept and Pay"

Current behavior:
Regardless of what payment methods are configured the site will display the error, "No suitable payment option could be found"
Once the quote is marked as sent, then the configured payment options are displayed.

If a payment link is sent rather than a share link, the payment link displays all payment options correctly.

Expected behavior:
This is a pretty minor issue as normally the quote will be marked "sent" and this won't happen often, but it is confusing when it does as there isn't a clear explanation of what's going on. I think there are several options for improving user experience. 

Do one of the following(roughly in order of preference):
1. Don't allow an unlogged in user to view the quote, and provide a useful message like. "This quote hasn't yet been approved please contact your point of contact to resolve this" or something similar.
2. Don't display the accept and pay button, and somehow indicate the quote is a draft or not yet approved.
3. Properly display the payment options,  in the theoretical sense this may cause issues if a quote link is accidentally shared with the customer before it is intended and a customer executes the order, but in practice it's probably not likely to be an issue.
4. Don't allow generation of a sharing link unless the quote is marked as sent, this may confuse users or cause problems with internal sharing. 
5. Automatically mark the quote as sent once a sharing link is generated, this may also disrupt existing workflows.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

I encountered this because I'm still standing up odoo for my business, and hadn't customized the email templates yet so I was sending share links instead of using the built in email feature. Now that I've setup the quote email template, I'm planning to use it, and shouldn't see this anymore.  I was tearing my hair out for hours  trying to figure out what was wrong.

**Comment by Feyensv** [comment]
cc @dalaOdoo

**Comment by Feyensv** [comment]
Thanks for the feedback :+1:.

We've added a clear message in the payment popup for future versions, to clearly explain that orders cannot be paid for when in `draft` state.
We'll consider your other ideas (mark the SO as sent when the link is generated, ...) as well.
