### ISSUE TITLE
Bug on eCommerce, searching rental products

### ISSUE THREAD

**Issue by alexeirivera87** [odoo/odoo#120145]
Impacted versions: 16.0

Steps to reproduce:

- Create a rental product with Time based pricing
![Screenshot from 2023-04-28 11-20-31](https://user-images.githubusercontent.com/9451625/235188197-58612e90-975f-4ff3-a96f-03e5c1c85017.png)

- Publish this product

- Create a contact and grant portal access

- login using this portal user, go to the Shop, try to search the rental product previously created

Current behavior:

We see an error message related to access right issues.

![image](https://user-images.githubusercontent.com/9451625/235188974-725e5081-eb0e-42fd-9ac5-8addfecae585.png)

If we refresh the page, we may see the same error displayed in a different way:

![image](https://user-images.githubusercontent.com/9451625/235189225-55704a1d-d1c0-471a-a8ba-0500d19b8f3a.png)

Expected behavior:

Be able to filter rental products with time based products, using portal users

regards

**Comment by alexeirivera87** [comment]
fix typo:

Expected behavior:

Be able to filter rental products with time based pricing, using portal users

**Comment by sswapnesh** [comment]
@alexeirivera87 Added Fix on https://github.com/odoo/enterprise/pull/40572

**Comment by vava-odoo** [comment]
Hi @alexeirivera87 
Thanks for reporting and sorry for the delay.
Issue has now been fixed in https://github.com/odoo/enterprise/pull/49479
@sswapnesh I wasn't aware of the PR, sorry about that!
Cheers
