### ISSUE TITLE
Advanced filter by date don't work with custom date format with spanish language (default is english).

### ISSUE THREAD

**Issue by ansoldado** [odoo/odoo#12020]
Impacted versions: Odoo8

Steps to reproduce: Modify the date format in the language and try to add the advanced filter by date.

Current behavior: One filter is added with date = ""

Expected behavior: One filter is added with date that we select in the calendar.

Video/Screenshot link (optional):
![seleccion_013](https://cloud.githubusercontent.com/assets/8133167/15209007/ffa884fe-182e-11e6-9c18-1d80ed7dbe4b.png)
![seleccion_012](https://cloud.githubusercontent.com/assets/8133167/15209009/02078290-182f-11e6-9b60-caad83ff3a7f.png)
![seleccion_014](https://cloud.githubusercontent.com/assets/8133167/15209037/247dc596-182f-11e6-8952-69e1de4566c0.png)
![seleccion_015](https://cloud.githubusercontent.com/assets/8133167/15209039/26f91550-182f-11e6-9b0a-5bcce4c99217.png)

**Comment by Yenthe666** [comment]
@nim-odoo possibly related to my report? https://github.com/odoo/odoo/issues/11876
Looks a bit in the same direction.

**Comment by Yenthe666** [comment]
Hi @ansoldado ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
