### ISSUE TITLE
[Full mail composer] Full mail composer doesn't send and log message in mail history

### ISSUE THREAD

**Issue by tasa87** [odoo/odoo#1202]
Using full mail composer from chatter (ie. from partner form) doesn't send mail and doesn't log message in message and communication history.

**Comment by Yenthe666** [comment]
Hi @tasa87,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
