### ISSUE TITLE
Re: UncaughtPromiseError

### ISSUE THREAD

**Issue by kazire** [odoo/odoo#120214]
Impacted versions: saas~16.1+e

Steps to reproduce:Login to https://erp.kaziregroup.com/ and click on settings 

Current behavior: Uncaught Promise > Missing field string information for the field 'documents_payroll_folder_id' from the 'res.config.settings' model
Error: Missing field string information for the field 'documents_payroll_folder_id' from the 'res.config.settings' model

 
Expected behavior: That the settings module should be opening as expected

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hello @kazire 
Could you provide the steps to reproduce on [runbot](http://runbot.odoo.com/runbot)? (blue door icon of the version row (16.1) with login/pwd as admin/admin)
I couldn't reproduce the error on last 16.1 runbot.
Also, please consider opening a ticket on the [support page](https://www.odoo.com/help) if you need help with your database.
Regards

**Comment by kazire** [comment]
Hello ,
This issue was resolved ,thanks .

regards,
Ivan
