### ISSUE TITLE
on_change does not work when implemented using fields_view_get

### ISSUE THREAD

**Issue by tthicham** [odoo/odoo#12026]
Impacted versions:
i'm in Odoo 8
Steps to reproduce:
-override the **fields_view_get** method in order to add a field dynamically
-set the **on_change** attribute for the recently added field
-define the on_change methode in .py file
Current behavior:
-on_change method does not get fired
Expected behavior:
-on_change method to be triggered

**Comment by Yenthe666** [comment]
Hi @tthicham,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
