### ISSUE TITLE
[8.0] Unable to deliver a MTO order due to negative quant

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#12037]
## Steps to reproduce:

In Settings/Sales, check option "Choose MTO, drop shipping,... on sales order lines"
In Warehouse/Configuration/Routes, set Make To Order available on sale order lines

Choose a product A without stock.
Imagine an inventory mistake and sell product A through the point of sale -> you get a negative quant.
Create a sale Order with product A (route Make To Order)
Confirm the Sale Order.
A Purchase Order has been created for product A, confirm it and receive product A.

See linked video for more details.

## Current behavior:
Impossible to deliver Product A, the move stays in "Waiting another move" state and the negative quant disappeared.

## Expected behavior:
As the receipt is dedicated to another move, the negative quant shoud remain and a new one should be created in order to fulfill the delivery move.

## Video/Screenshot link (optional):

https://youtu.be/hZ8heuENV4M

**Comment by Cedric-Pigeon** [comment]
OPW-677582

**Comment by jco-odoo** [comment]
It was like that initially, but it would lead to too many negative quants that keep hanging around in the system.  The purpose of negative quants is to solve them asap (the logic would really get overcomplicated if you compensate for negative quant behaviour).  If you sell something from the PoS and it is not in the system's stock, you either create the purchase you forgot to encode after it or do an inventory adjustment.  That way, the purchase order that was meant for the mto, will have the link with the delivery.  (The initial domain was like: if the move has a move_dest_id, check that the negative quant reconciled had move_dest_id in its history)
