### ISSUE TITLE
Purchase Price rates Odoo 8

### ISSUE THREAD

**Issue by Bilbonet** [odoo/odoo#1203]
I set two sequences for purchase rates.
1. Supplier price on the product form. 
2. Pricing cost on the product form.

 It ignores the second sequence. If you have no price for the supplier, does not pass the second sequence for the cost.

**Comment by Yenthe666** [comment]
Hi @Bilbonet ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
