### ISSUE TITLE
[14.0] Display optional collumns ··· selection annoying UI bug

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#120397]
Impacted versions: 14c

Steps to reproduce: This seems to be firefox specific

Current behavior: trying to add more info columns the ··· menu are avoiding my mouse pointer...
(not really seen in the video but adding pointer to it shows just the scroll bar ontop.)
Expected behavior: being able to select the menu.

Video/Screenshot link (optional):

[Screencast from 2023-05-03 11-40-58.webm](https://user-images.githubusercontent.com/13152668/235870596-cdb6c639-be70-4f51-a29c-f8b26b4819e8.webm)

**Comment by vava-odoo** [comment]
Hi @kimasplund 
Just tried on the [runbot](http://runbot.odoo.com/runbot) and it works fine. Yes, there is an overlap, but you can click a bit on the left and see the other fields.
Cheers,

**Comment by kimasplund** [comment]
This was on ubuntu. and there it seemed impossble. il give it a try. but still very annoying "feature" :D maybe it would be possible to flip the dots on the side? That would anyway make more sense as you add stuff horizontally

**Comment by vava-odoo** [comment]
This button has been changed in 16. I don't think there is any plan to backport that.
