### ISSUE TITLE
Incorrect tax calculation with "round per line" method

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#12039]
## Impacted versions:
Tested on runbot for Odoo 8.0 and 9.0

## Steps to reproduce:
1. Make sure that in accounting options rounding method is "Round per line" and decimal precision is 2
2. Create a tax 22% (like Italian IVA)
3. Create a sale quotation for a product with unit price 5.63€, quantity 4 and tax defined in the step before

## Current behavior:
Taxes are **4.95€**, which is what one would expect with "total" rounding method:
`5.63 * 0.22 = 1.2386 * 4 = 4.9544 --(round)--> 4.95`

## Expected behavior:
Taxes should be **4.96€**, which is what one would expect with "per line" rounding method:
`5.63 * 0.22 = 1.2386 --(round)--> 1.24 * 4 = 4.96`

**Comment by zeroincombenze** [comment]
I am not sure I did understand.
Current behavior seems correct to me.
The method should be:
5.63 (unit price) * 4 (quantity) = 22.52 (line total) * 0.22 (tax) = 4.9544 -(round)-> 4.95

In my mind tax will be applied after line total evaluation.

**Comment by gdgellatly** [comment]
Yeah sounds like you want round per item. Not supported but I imagine not
hard to develop. But it is not correct to do that in many circumstances.
Imagine your scenario was kg instead of pieces. It is a nonsense to
arbitrarily round each kilo.

There are other ways anyway with pricelist and inclusive taxes to achieve
that.

**Comment by LeartS** [comment]
You guys are right, I confused "round per line" with "round per single item".

Is there a way to round per unit quantity? I want this because I want to show the price, tax included, in the frontend ecommerce, with 2 decimal digits. If I do not round per single piece, it's possible that the unit price * quantity seen by the customer and the line total does not match (like in example).
