### ISSUE TITLE
[9.0][website_slides] Behind nginx with ssl return http mixed content on redirect

### ISSUE THREAD

**Issue by eneldoserrata** [odoo/odoo#12049]
Impacted versions: 9.0 c

Steps to reproduce: setup nginx with ssl certificate files an open slide preview

Current behavior: return error with mixed content because pdf return on http url

Expected behavior: return pdf url on https url

Video/Screenshot link (optional):

@Yajo have a pull request with working fix #10363

**Comment by Yajo** [comment]
Hi, thanks for your interest. If you like my patch, it's more effective to add a review to it than to open a new issue.

Please see the review guidelines too: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#review

Thanks! (And please somebody close this)

**Comment by Yajo** [comment]
Oh sorry I missed the point that your issue was for v9 and core odoo addon. Then this is the right place. My failure

**Comment by joolsr** [comment]
I'm having the same exact issue with v9, ie with slides and live chat with some files being blocked as they are http and not https. I'm using nginx and ssl. I've asked @Yenthe666 to have a look at this as AFAIK the v8 patch referenced should be the same as for v9. But others far more knowledgeable than I need to push for this fix as you cant use the slides properly and live chat without a fix.

**Comment by mart-e** [comment]
@eneldoserrata could you check my comment at [10363#223286990](https://github.com/odoo/odoo/pull/10363#issuecomment-223286990)? We are using NGINX with a proxy on [our own website](https://www.odoo.com/slides) and don't have this mixed content errors.

**Comment by treviser** [comment]
I don't know if it helps, but I remember that in addition to properly forwarding the scheme as pointed out by mart-e I had to reload some images/PDFs in the website which I had moved by dump backup from the unsecured test server to the secured production server.

**Comment by joolsr** [comment]
I'm still having same issues even with trying other setups with NGINX. Its quite important to get this right as otherwise the browsers ban/do not show the content ie slides that you expect.

@mart-e How do you have your nginx set-up? I also use http2, but I dont believe this is affecting things

**Comment by joolsr** [comment]
@mart-e, I have got the headers you describe all correct.

**Comment by mart-e** [comment]
@joolsr  check my comment at [10363#223286990] with details on the configuration.
Closing this one to focus the discussion on one topic.

**Comment by joolsr** [comment]
ok
