### ISSUE TITLE
TypeError: MailTemplate.send_mail() got an unexpected keyword argument 'email_values'

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#120406]
Impacted versions: 16

Steps to reproduce: Invite user on odoo for password reset or Two factor auth

Current behavior: Getting error
    **invite_template.send_mail(user.id, force_send=True, email_values=email_values,
TypeError: MailTemplate.send_mail() got an unexpected keyword argument 'email_values'**

Expected behavior: Mail should be sent to user 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by jp-22** [comment]
@shazzwazz20 I think you should check for the method "send_mail" in your custom addons. From there maybe while extending the functionality the parameter "email_values" is not passed and you are getting this error !!

Thanks
