### ISSUE TITLE
[16.0] web: fields are not aligned

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#120461]
Impacted versions: 16.0

V14:
![image](https://user-images.githubusercontent.com/16716992/235945403-c63111f8-13ec-4cdf-a27f-ba5cc96fa839.png)

V16:
![image](https://user-images.githubusercontent.com/16716992/235945127-e644d108-389c-45a7-840e-491e94a36dbb.png)

Support ticket number submitted via odoo.com/help (optional):
#3299825

@xmo-odoo

**Comment by fmdl** [comment]
@fpodoo it is the SAP theme ? :-)

**Comment by bouvyd** [comment]
Hello

As of v16, labels are only aligned _within_ a group node, and not throughout the whole document (responsive labels vs fixed labels before); the goal is to leave more place for content whenever possible.

This behaviour is the expected one :)

Have a good day

**Comment by bouvyd** [comment]
Not that this will be corrected for future version for this particular view
See #122089
