### ISSUE TITLE
[16.0] mail: search bar is disapear

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#120502]
Impacted versions: 16.0

In the discuss app the search bar is disapear.

If you manage email by odoo, it is not possible to search in message. In V14 it is possible.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16716992/236119471-84b946e9-ea86-4e44-b41f-c297820e2f3e.png">

@tde-banana-odoo

**Comment by fmdl** [comment]
OPW #3300592

**Comment by tde-banana-odoo** [comment]
@odoo/rd-discuss decision, I was not involved in it :) As a personal note, as a rare user of Odoo Inbox, I agree it is annoying. But not sure much people use Odoo Inbox...

**Comment by fmdl** [comment]
In call center it is used.

**Comment by seb-odoo** [comment]
Hello, it's not going to be added back in 15 or 16, but hopefully it should be in 17.
