### ISSUE TITLE
Drag & drop image to email, and you will not be able to see it when sent

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12050]
Impacted versions:
8, 9

Steps to reproduce:
- Open runbot.
- Enter any mail.thread document.
- Send a new message.
- Open in the extended compose wizard.
- Drag & drop an image from your local computer to the mail composer.
- Image appears there.
- Send the message.

Current behavior:

Image is lost.

Expected behavior:

Image is attached inline, like it appears in the WYSIWYG editor.

Video/Screenshot link (optional):

v8:
![captura de pantalla de 2016-05-16 10-12-22](https://cloud.githubusercontent.com/assets/973709/15284003/e88a61c0-1b4e-11e6-9d68-3bc102b8f218.png)

v9:
![captura de pantalla de 2016-05-16 10-15-50](https://cloud.githubusercontent.com/assets/973709/15284046/32955efa-1b4f-11e6-93a0-3e4c68bcc414.png)

**Comment by Yenthe666** [comment]
Hi @Yajo,

Could you make me a GIF / vid for this? I'm not sure what you mean with the extended compose wizard and drag and drop. If I see this I can simulate this and when it is a bug I can assign somebody on the issue. :smile: 

Regards,
Yenthe

**Comment by Yajo** [comment]
https://youtu.be/qA6gTojOQ78

**Comment by Yenthe666** [comment]
Thanks a lot for the video, this is indeed a bug!
@JKE-be another one for you, CRM functionalities.

**Comment by JKE-be** [comment]
Maybe not a bug...
Not sure that we support base64 img in message, there are sanitized proabably.
Even if the scren 'drag an image here' let suppose it...

**Comment by Yajo** [comment]
If it says "drag here" and you drag and it does not work, then it's a bug, without any kind of doubt: Either the message is wrong or the functionality is missing.

Probably removing that sanitizing would work just fine.

**Comment by joolsr** [comment]
Hi

I also noticed on a similar note that if you go to pictogram and add one
icon to your signature that tge puctogram icon isnt saved. This may not be
related but could be.

Julian

**Comment by Yenthe666** [comment]
I agree with @Yajo, this is clearly a bug. Either the ability to drag and drop in the view is fully removed or it is fixed so you can drag and drop. Either way, something has to change regarding this functionality.

**Comment by tde-banana-odoo** [comment]
What does it do ? CIDs or inlined base64 content ?

**Comment by JKE-be** [comment]
@tde-banana-odoo base64 content

**Comment by moylop260** [comment]
Same issue here:
https://youtu.be/32vqfsrSQ5w

FYI If you use the preview of the template it works 😃 ! but from the wizard not works 😢 

We don't want a support for base64 from `send_email` method.
We want that don't delete the image from the wizard.

We are processing the base64 image here:
https://github.com/OCA/server-tools/pull/441/files#diff-03bc4849ad186489620f60927ff919d0R72

```bash
 def build_email(self, ...):
        new_body, image_attachments = self.get_b64_images(body)
        msg = super(IrMailServer, self).build_email(new_body, ...)
        self.image2attach(msg, image_attachments)
        return msg
```


This worked with old sha of odoo but now is not working, because the method `build_email` receive a body without b64 images from wizard.

**Comment by intero-chz** [comment]
Maybe there is a correlation to https://github.com/odoo/odoo/issues/4047 ?

**Comment by moylop260** [comment]
Do you have a news about this issue?

**Comment by JKE-be** [comment]
Hello
It is confirmed but not already fixed.

Fix should be to upload attachment when user past base64 img into the éditor (like github) and replace with the new attachment created.

PR is welcome :)

**Comment by moylop260** [comment]
I have a confirmed issue 680023 OPW from 2 months ago.
What is wrong here?

**Comment by paulius-sladkevicius** [comment]
v10 is effected too

**Comment by 10537** [comment]
@Yenthe666 @JKE-be v11 is affected too, Do you have some solution?, 2 years and this issue still alive.

**Comment by Yenthe666** [comment]
@moylop260 what happend to your OPW? @jke-be can you check this maybe?

**Comment by JKE-be** [comment]
From what I remember, we simply disabled the feature, it was a security issue to allow the image:data/

**Comment by pedrobaeza** [comment]
Yes, it was disabled, at least on v11, although not the ideal solution. Odoo messaging system still lacks the option to embed images in the middle of the content. This reduces a lot the possibilities and this is a strong argument from some of our customer for not abandoning their email clients. Is there anything in the roadmap for this?

**Comment by JKE-be** [comment]
from what I know, not...
But since we have improved the attachment viewer in v12, it is maybe in the continuity...

//cc @bst-odoo (the product owner)

**Comment by bst-odoo** [comment]
@est is the product owner of it but I'm aware of the feature, a task is in progress for the drag and drop. We hope it will be released for V12.

**Comment by est** [comment]
Hmmm, why am I been notified by this thread?

**Comment by Yenthe666** [comment]
@est judging by the edit of bst-odoo and that his message starts with "est" I'm going to guess this was as accident 😉
