### ISSUE TITLE
Internal Server Error  The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by mohamedelouafi** [odoo/odoo#12055]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by mohamedelouafi** [comment]
when i install odoo version-- 8

**Comment by Yenthe666** [comment]
@mohamedelouafi you should provide a traceback or more details, otherwise we have no idea what might be wrong. You can find the log under `/var/log/odoo`.
@mart-e locky-lock. :+1:

**Comment by amynous** [comment]
im trying to install odoo in windows and i got that error message first download and install was successful then i uninstalled it and deleted the postgresql too but the install of the second time didnt work and show that msg and also the service of postgresql can not be activated  , any one have a solution for that ?
