### ISSUE TITLE
[15.0] Not possible to print Purchase Order in Odoo with German Language

### ISSUE THREAD

**Issue by adebuhr** [odoo/odoo#120689]
**Impacted versions:** 15.0

**Error:** Not possible to print Purchase Order in Odoo with German Language

**Problem**:
Wrong Translation in  15.0/addons/purchase/i18n)/de.po

Get Invalid Syntax Error because of "und" and "oder\"

**Affected Code:**
File: 15.0/addons/purchase/i18n)/de.po
Line: 26-35

#. module: purchase
#: model:ir.actions.report,print_report_name:purchase.action_report_purchase_order
msgid ""
"\n"
"                (object.state in ('draft', 'sent') and 'Request for Quotation - %s' % (object.name) or\n"
"                'Purchase Order - %s' % (object.name))"
msgstr ""
"\n"
"                (object.state in ('draft', 'sent') und 'Angebotsanfrage - %s' % (object.name) oder\n"
"                'Kaufauftrag - %s' % (object.name))"

**Solution:**
Change translation to

" (object.state in ('draft', 'sent') and 'Angebotsanfrage - %s' % (object.name) or\n"
" 'Kaufauftrag - %s' % (object.name))"

**Comment by niyasraphy** [comment]
hi @adebuhr ,
thanks for reporting the issue, updated the translation in the transifex: https://app.transifex.com/odoo/odoo-15/translate/#de/purchase/333326874
