### ISSUE TITLE
Only one of the multiple fields with conditional visibility become visible upon fulfilling the criteria

### ISSUE THREAD

**Issue by abrar39** [odoo/odoo#120631]
**Impacted versions:** 16.2

**Steps to reproduce:**

1. Create a form with a `Multiple Checkbox` field having at least two choices.
2. Set the visibility of at least two other `text` fields to conditional based on a selection from the `Multiple Checkbox`. 
3. Save and refresh the page.
![overall form design](https://user-images.githubusercontent.com/7902534/236416852-297777a9-4415-4797-ab12-4dc9691a1e18.png)

4. Select a choice from the `Multiple Checkbox` and its field becomes visible. ![Visible field with one selection](https://user-images.githubusercontent.com/7902534/236416927-61d3a74e-bf46-4a28-9bb6-6a0c0eb500ef.png)

5. The second and/ or third selection does not make the corresponding fields visible.
![visible field with two selections](https://user-images.githubusercontent.com/7902534/236416998-8baf1a58-4eeb-48b1-bb4a-2de0c8549a2a.png)
 
**Current behavior:**
When multiple choices are selected, the corresponding fields do not become visible.
**Expected behavior:**
The fields should become visible based on the selection from multiple choice.

**Video/Screenshot link (optional):**
Attached in Description
**Support ticket number submitted via odoo.com/help (optional):**
Nil

**Comment by R55555** [comment]
Can I pick this up?

**Comment by R55555** [comment]
I have created a PR. Please verify if the issue could be solved.

Thank you

**Comment by R55555** [comment]
I see that the issue was caused by formData.get. Replaced it with formData.getAll in #124137

**Comment by R55555** [comment]
I found that issue was with formData.get. Replaced it with formData.getAll in  #124163
