### ISSUE TITLE
Paypal with Odoo 8 (Customer Invoice should be paid when Paid amount from Paypal)

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#12060]
Impacted versions:  Odoo 8.0

Steps to reproduce:

- Install payment_payment,  Configure receptive.

- Create a Sale Quotation. Confirm Sales Quotation and Create Customer Invoice. 

- Open related Customer Invoice and validate it. 

- Send email using "Send by Email' button. 

- Customer receive email with Invoice details and Paypal link.

- Customer pay amount from Paypal link as given email. 

- Open a Customer Invoice. It's still on Open state while Customer already paid it.

Current behavior:

Following is server trace-back

    {'address_city': u'*********************',
     'address_country': u'****************',
     'address_country_code': u'******',
     'address_name': u'**************',
     'address_state': u'*************',
     'address_status': u'confirmed',
     'address_street': u'***************',
     'address_zip': u'**********',
     'business': u'*********************',
     'charset': u'UTF-8',
     'custom': u'',                                 <==== custom is empty
     'first_name': u'************',
     'handling_amount': u'0.00',
     'invoice': u'SO519',                           <=====  'invoice': u'SO519'
     'ipn_track_id': '****************',
     'item_name': u'Test Order SO519',            
     'item_number': u'',                            <==== item_number is empty                        
     'last_name': u'***********',
     'mc_currency': u'USD',
     'mc_fee': u'0.33',
     'mc_gross': u'1.00',
     'notify_version': u'3.8',
     'payer_business_name': u'************',
     'payer_email': u'****************',
     'payer_id': u'*********************',
     'payer_status': u'verified',
     'payment_date': u'*********',
     'payment_fee': u'0.33',
     'payment_gross': u'1.00',
     'payment_status': u'Completed',
     'payment_type': u'instant',
     'protection_eligibility': u'Eligible',
     'quantity': u'1',
     'receiver_email': u'***********************',
     'receiver_id': u'****************',
     'residence_country': u'************',
     'shipping': u'0.00',
     'tax': u'0.00',
     'transaction_subject': u'',                        <==== transaction_subject is empty 
     'txn_id': u'******************',
     'txn_type': u'*************',
     'verify_sign': u'*************************'}
     
    2016-05-16 12:31:18,901 1319 INFO iknowpc werkzeug: 127.0.0.1 - - [16/May/2016 12:31:18] "POST /web/dataset/call_kw/mail.notification/get_message_notification HTTP/1.1" 200 -
    2016-05-16 12:31:19,122 1319 INFO iknowpc openerp.addons.payment_paypal.controllers.main: Paypal: validated data
    2016-05-16 12:31:19,123 1319 ERROR iknowpc openerp.addons.payment_paypal.models.paypal: Paypal: received data with missing reference () or txn_id (*********************)

Expected behavior:

Customer Invoice should be gone to paid state.

Configuration on Paypal account:

I have done with same as mention in [https://www.odoo.com/documentation/user/9.0/accounting/receivables/customer_payments/paypal.html](url) 

Also tried with _return_url = https://company_url/shop/comformation_ and _return_url = https://company_url/shop/payment/validate_

**Comment by spadae22** [comment]
Yes, please fix this..

**Comment by Yenthe666** [comment]
@nim-odoo could you have a look at this one? I don't know this part of Odoo well enough.

**Comment by bodedra** [comment]
@Yenthe666 Thanks for you comment. May you please give insight on these, where something missing ?

I have followed Odoo documentation as mentioned in question.

Which might the case to not getting Customer invoice paid ?

**Comment by Yenthe666** [comment]
Hi @bodedra,

No problem. I'm not sure about this one, I don't ever work with the PayPal module myself but the issue looks correct to me and since @spadae22 also reports this I'd love somebody from Odoo to look at this.
I hope @nim-odoo can give an answer on this one. :+1:

**Comment by spadae22** [comment]
Any word on this @mart-e ?

**Comment by spadae22** [comment]
@Yenthe666 @mart-e Based upon the answer from support, this should be closed. 
Here it is: This is not expected to mark the invoice as paid when paying an invoice with the Paypal link included in the email sent. This must be done manually.

The only thing which is done automatically is confirming the sale order coming from the ecommerce when the paypal payment is received.

Regards,

Denis Ledoux

Odoo.com
R&D Developer

SAAS Tech

**Comment by bodedra** [comment]
@spadae22  Thanks for your information.

How about we don't have E-commerce website ? 

Is there any way to handle it ? It would be great.

**Comment by spadae22** [comment]
@bodedra We do not use odoo for our ecommerce, we use Volusion. I created a connector the imports all the orders as sales orders in odoo, we also import (create in odoo) the voucher for type of payment with a reference to the SO and customer as well as the REF from Paypal. So after the transfer and invoice creation. We run the auto reconsiliation and it pays all of the invoices. 

We only use "PayPal" in odoo for a limited number of invoices, but odoo will pass the invoice number to paypal, we filter the email from paypal and manually apply the payment.

**Comment by bodedra** [comment]
@spadae22 that's what currently I am doing but in another way. I have made a scheduler which will run once in a day and check mentioned process.

Good to know about that.
