### ISSUE TITLE
[9.0] Database Lock during module installation

### ISSUE THREAD

**Issue by PaulLiang1** [odoo/odoo#12061]
## Impacted versions:
9.0, with commit 610d4627405ab0c5479007164d9e11bbe44d5f00

## Steps to reproduce:

- Install fresh database.
    
        docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=admin -e POSTGRES_DB=postgis -d mdillon/postgis

- Run Odoo.

        python ./odoo.py --addons-path=addons  -r admin -w admin --db_host=`docker-machine ip default` --log-level=debug --db-template=postgis  --debug -u=all

- Go to `localhost:8069`, Create a fresh database called `test`, then install `account` Module. 

- After `account` module is installed, click to install `purchase` module. 

## Current behavior:

Purchase module installation is hanged. 

## Expected behavior:

Purchase module can be installed. 

----

- Connect to psql 

        psql postgresql://admin:admin@`docker-machine ip default`:5432/test

- Using the query from https://wiki.postgresql.org/wiki/Lock_Monitoring, it shows a locking transaction. 

        -[ RECORD 1 ]-------------------------+--------------------------------------------------------------------------------------------------------
        blocked_pid                           | 116
        blocked_user                          | admin
        blocking_pid                          | 115
        blocking_user                         | admin
        blocked_statement                     | delete from ir_attachment where id IN (271, 270, 269, 268, 267, 266, 265, 264, 263, 262, 261, 260, 259)
        current_statement_in_blocking_process | SAVEPOINT test_cursor

        Time: 2.943 ms

-----

Full log trace can be seen at: https://gist.github.com/PaulLiang1/803fd2763d1e8547dc75689cbc8a3898

**Comment by PaulLiang1** [comment]
Can not reproduce after #12062

**Comment by Yenthe666** [comment]
@PaulLiang1 if you can't reproduce it you can close it? :smile:

**Comment by PaulLiang1** [comment]
@Yenthe666  

It can't be reproduced after fix #12062. I will close this one.
