### ISSUE TITLE
Danish translations missing in base and enterprise

### ISSUE THREAD

**Issue by mschou** [odoo/odoo#12076]
Impacted versions: 9.0

We have made serveral translation to Odoo 9 please commit from transifex

**Comment by Yenthe666** [comment]
@mschou all translations can be managed from Transifex and will be synchronised every few days (I believe once a week).
So give it a few days and those translations will be in Odoo.
@mart-e this can be closed.

**Comment by mart-e** [comment]
[When will my translations appear in the software (or in GitHub)?](https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github)
