### ISSUE TITLE
CSV export gives access to "invisible" data

### ISSUE THREAD

**Issue by dannyadair** [odoo/odoo#12077]
Impacted versions: at least 8.0

Steps to reproduce:
Log in as a user with HR "Employee" role. You can only see the "Public Information" tab of other employees. However, switch to list mode and export employees, with Export type "Export all data", select all fields incl. fields from personal and HR tab.

Current behavior: Not only are these fields selectable, the CSV file will contain their values.

Expected behavior: Don't export values that a user can't "access". Subsequently, don't offer these fields for selection.

Hiding fields cosmetically is not sufficient for confidential information like personal/HR information about employees. NB I assume XMLRPC calls would have the same issue.
I suspect Odoo is missing something like https://github.com/OCA/server-tools/pull/396

**Comment by dannyadair** [comment]
NB sorry but together with https://github.com/odoo/odoo/issues/6052 we're forced to disable CSV import/export which is unfortunate.

**Comment by dreispt** [comment]
Disabling CSV is not enough. For example, an Email Template can access and display data in those fields, or an RPC call (like using erppeek).

This is an old issue with the HR module.
My advice is to disable read access to `hr.employee` to the Employee group.

@odony This a design issue, and a bomb waiting to explode: there are strong privacy regulations on the employee personal data, so this issue has significant legal risk.

**Comment by odony** [comment]
@dreispt thanks for the heads up, I agree that something has to be done.
The thing is, regulations vary a lot from country to country, and the employee directory is a valuable tool for all employees in most companies. So globally blocking access to it sounds too drastic to me. I'd rather let admins selectively choose to restrict this feature in their company specific ACLs if they want to fully block it.
But short of blocking access completely, we should at least block the most sensitive fields properly.

@dannyadair Odoo has built-in support field-level restrictions at the model level, so I'd suggest to enforce field-level restrictions on all sensitive employee fields, and only allow HR Officers to access them. This is what PR #12160 accomplishes: it will block access at the model level, automatically restricting CSV exports, direct RPC access, etc. 

Does that solution work for you?

**Comment by dannyadair** [comment]
@odony thank you. How could I allow an employee to maintain some fields for their own Employee instance but not access these fields at all on others? For example they might want to update their personal phone number.

**Comment by Yenthe666** [comment]
Hi @dannyadair ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
I believe this is handled though. 😉 

Regards,
Yenthe
