### ISSUE TITLE
Bug after commit 59dcd17: Decimal seperators that are not "." are not being recognized anymore. 

### ISSUE THREAD

**Issue by Matthias-Raes** [odoo/odoo#120784]
Impacted versions:  16.0_20230508

Steps to reproduce: Change decimal seperator to a comma (',') and try to change the cost price or sale price of an item. 

Current behavior: Odoo removes the ',' and puts the number as if there was no decimal seperator 
e.g. 2,53 changes to 253. 

Expected behavior: The number gets accepted. 

My assumption is the functionality added in commit 59dcd17, replaces the decimal seperator with a '.' to ensure correct parsing and uniformity. However, after the regex, the decimal seperator does not get put back. So Odoo handles '2.53' instead of "2,53". 
Fix would be to assign the replaced value to a new variable, rather than the same variable given in the parameters. 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by hubvd** [comment]
Hi, there will indeed be a revert at https://github.com/odoo/odoo/pull/120807
It should be merged soon

**Comment by vava-odoo** [comment]
Solved by https://github.com/odoo/odoo/pull/120807
