### ISSUE TITLE
ProgrammingError: column account_invoice.is_oi_generated does not exist LINE 1: ...ND  ("account_invoice"."state" = 'draft'))  AND  ("acco

### ISSUE THREAD

**Issue by hindbenessy** [odoo/odoo#12087]
hello, I'm deploying Odoo 8 when i want to create a new customer invoice i get this error  i didn't know how to solve it 
thanks for u helps 
Impacted versions:8
![capture du 2016-05-18 10 15 24](https://cloud.githubusercontent.com/assets/17640313/15355219/5acc6274-1ce9-11e6-915d-b4a35d045973.png)

**Comment by Yenthe666** [comment]
@hindbenessy the field `is_oi_generated` is not a default field in Odoo, have you added custom code to this Odoo environment?

**Comment by mart-e** [comment]
This is indeed a custom field, so check the module that added it (not an official Odoo module so should not be reported here)

**Comment by hindbenessy** [comment]
thanks for all , i had uninstall this module , it's working now

**Comment by Yenthe666** [comment]
@hindbenessy good to hear you found your problem. Best of luck with Odoo. :)

**Comment by hindbenessy** [comment]
thanks :)

2016-05-20 16:39 GMT+01:00 Yenthe <notifications@github.com>:
