### ISSUE TITLE
Origin field is not set on confirming purchase order

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1208]
Tested in runbot http://06496-8-0-bff521.runbot.odoo.com/

Create a purchase order against a Warehouse with reception in 3 steps (chicago wharehouse)
3 pickings are correctly created but the IN type one Origin field is null, so it's quite complicated searching 3 related pickings on list. 

Here the example, where the INT type pickings have got the origin field correctly set and the IN one, has got it empty

Chic/IN/00006   Chic/Input  07/16/2014 12:54:27 Ready to Transfer  
Chic/INT/00001 Chic/Quality Control 07/16/2014 12:54:28 PO00007 Waiting Another Operation  
Chic/INT/00002 Chic/Stock 07/16/2014 12:54:28 PO00007 Waiting Another Operation

Thank you!!
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
