### ISSUE TITLE
Odoo Forum Notification: Missing subject and link to the question

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12096]
Impacted versions:
Latest Odoo Forum

Steps to reproduce:
Get a nofitication from the Odoo forum (by subscription or by a comment to your posting)

Current behavior:
The notification email contain the subject: "Re: False" and contains no link to the forum post.
Expected behavior:
The notification email contains the title of the forum post and a link to the forum post.
Video/Screenshot link (optional):

![selection_195](https://cloud.githubusercontent.com/assets/1814941/15383579/60b554b0-1d94-11e6-8b1b-875a11e3d82b.png)

**Comment by treviser** [comment]
@Yenthe666 As you seem to have miraculous contacts and as a regular supporter in the forum too, could you give this some attention at the right place. It is cumbersome if you try to help people and you have to search through the forum in order to find out for which thread you have got this notification :-)

**Comment by Yenthe666** [comment]
@treviser I haven't seem to have gotten an e-mail like this yet. I always get another e-mail template.. i'll try to get one tommorow and if I get this too I can label it as confirmed and forward it to somebody. :)

**Comment by treviser** [comment]
Thanks, I have observed this only since the last forum software change. It was correct before.

**Comment by Yenthe666** [comment]
@treviser thanks, I've posted on your topic! Let me know when you made a reply on my post, then I can verify this. :+1:

**Comment by treviser** [comment]
Done!

**Comment by treviser** [comment]
Your answer got notified properly:

![selection_196](https://cloud.githubusercontent.com/assets/1814941/15447513/327e909a-1f45-11e6-9424-665db40ca3e9.png)

**Comment by Yenthe666** [comment]
@treviser so you mean the first e-mail from my screenshot?
![image](https://cloud.githubusercontent.com/assets/6352350/15447615/cbfa5152-1f48-11e6-9672-0760add28214.png)
The first one does indeed not show any URL or anything to the topic but the second one does.

**Comment by treviser** [comment]
Yes, the first one. As it looks like, this issue happens with comments only.

**Comment by Yenthe666** [comment]
Alright this is indeed a bug. When a comment is placed there is no way for the user to find a link to the topic. A new answer on the same topic works fine and will give a clickable link.
@mart-e could you forward this to somebody please?

**Comment by treviser** [comment]
While we are at it, a proper subject is also missing when getting notified about a badge received by the admin (observed with Version 9.0c-20160505):

![selection_197](https://cloud.githubusercontent.com/assets/1814941/15448048/5a2b9dd0-1f55-11e6-8e24-67faca97e316.png)

**Comment by bassaminfotech** [comment]
Our expert team has been working with Dynamics odoo erp customization for years and is recognized as a leader in the digital world. We already have support team to monitor our clients’ Dynamics instances pro actively, providing insight into potential issues before they arise, feel free please contact us : sales@bassaminfotech.com
