### ISSUE TITLE
[8.0] Buying a product with a coupon will let you buy all other products for free

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12094]
Impacted versions: 8.0

Steps to reproduce:
 - Activate pricelists
 - Create a pricelist with a promotional code (coupon code):
  ![image](https://cloud.githubusercontent.com/assets/6352350/15362333/3a55d08a-1d15-11e6-8dec-b6b2db33daab.png)
 ![image](https://cloud.githubusercontent.com/assets/6352350/15362553/d8539600-1d15-11e6-84e6-6a21fabd9427.png)

 - Go to the webshop and order a product that is in the pricelist, then add the coupon code:
  ![image](https://cloud.githubusercontent.com/assets/6352350/15362438/67dbf1b0-1d15-11e6-8975-28b0804c5f8b.png)
 - Continue shopping and add another product that is in the pricelist:
 ![image](https://cloud.githubusercontent.com/assets/6352350/15362516/adaada1c-1d15-11e6-955d-d7186b0e0613.png)

Current behavior:
A user can buy all products for free after applying a coupon code, no matter what product is selected.

Expected behavior:
The coupon code is only active on the current product and does not set all other products to 0.00 as price.

**Comment by Yenthe666** [comment]
@mart-e and @odony can this one be handled as soon as possible? This is quite a big one.

**Comment by mart-e** [comment]
@Yenthe666 sorry but the pricelist is not properly configured. Try on a classic sale order, you would get the same behaviour (but this time with a better alert message).
No line matches the new product you give, no price. You always need to specify a fallback line.

When you spot bug that big in a version stable for more than 2 years, check again that you haven't missed something ;-)

**Comment by Yenthe666** [comment]
@mart-e my excuses, I rarely ever use pricelists. I was just absolutely sure that there was something wrong, guess I jumped in too fast for assumptions here.
I'll let one of the functional guys look at this, they probably know this more in to detail than me. Sorry :wink:
