### ISSUE TITLE
Missing functions when using Internet Explorer

### ISSUE THREAD

**Issue by krmagnaye** [odoo/odoo#12104]
Impacted versions: Latest version 7

Steps to reproduce:

Current behavior:

Expected behavior:  

Video/Screenshot link (optional):

![bug](https://cloud.githubusercontent.com/assets/19465728/15389224/608a064e-1de8-11e6-9384-39da75be05bb.jpg)

**Comment by Yenthe666** [comment]
@mart-e this looks like a simple CSS issue.
I'm wondering though: which Internet Explorer version are you using @krmagnaye?
I can't reproduce this on IE 11.

**Comment by krmagnaye** [comment]
Im using version 11. but i dont have an idea where to edit it. im using odoo open source.

**Comment by mart-e** [comment]
Just checked on ie11, latest openerp 7.0, no issue there

**Comment by Yenthe666** [comment]
Same from my side..

**Comment by krmagnaye** [comment]
Hello!

Im using IE11 but still having this issue.

**Comment by tesserB** [comment]
Do you have plugins/add-ons installed within IE11, krmagnaye?

**Comment by krmagnaye** [comment]
Hello!
Yes have. Which plugin/add-ons are you talking to?See attached photo that I have in the list.

 
 

Thank you for the assistance!
Best Regards,
Kayley Magnaye

 

    On Saturday, 21 May 2016, 2:18, Cody K. <notifications@github.com> wrote:
 

 Do you have plugins/add-ons installed within IE11, krmagnaye?—

**Comment by tesserB** [comment]
@krmagnaye I'm asking because some add-ons—such as "Stylish" and "Color that site"—inject JS and CSS.  I can't see the attached photo, but it's possible that one of them is to blame. 

Can you try reproducing the error with the add-ons disabled?

**Comment by Yenthe666** [comment]
@tesserB that is correct, I'm trying to handle the huge influx of bugs when I have some spare time.
Added this one to my 'to check up on' list.
@krmagnaye please disable all add-ons and check again, I bet it is one of those.

**Comment by krmagnaye** [comment]
Hello! 
This case has been resolved by myself after I change the IE version 11 to 9. 

Thank you!
