### ISSUE TITLE
[8.0] test: Using the parameter --test-file=myfile run all phantomjs tests

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#12114]
Impacted versions: 8.0

Steps to reproduce:
1. Create a database: `createdb testing`
2. Install a module: `~/odoo-8.0/odoo.py -d testing --stop-after-init -i account,website`
3. Run the tests of a python file: `~/odoo-8.0/odoo.py -d testing --stop-after-init --test-file=~/odoo-8.0/addons/account/tests/test_search.py`

Current behavior:
1. It ran all phantomjs tests from web\* modules.

Expected behavior:
1. It ran just the tests from file used in test-file parameter.

Video:

[![asciicast](https://asciinema.org/a/46115.png)](https://asciinema.org/a/46115)

**Comment by Yenthe666** [comment]
@rco-odoo could you have a look at this?

**Comment by charyorde** [comment]
I ran some simple tests and here is my findings:
```
openerp/cli/server.py:151:    if config["test_file"]:
openerp/cli/server.py-152-        config["test_enable"] = True
```
`config["test_file"]` is dependent on `config["test_file"]`. On server run, when `config["test_enable"] = False`, an Odoo module test directory is not loaded.

If we can make `config[test_file]` to be non-dependent on `config["test_enable"]`, then load the test directory of the module when `config["test_file"] = True`, that'll fix it.

**Comment by charyorde** [comment]
Nevermind. This is unrelated. 

Running in non-worker mode runs a single test file.

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
