### ISSUE TITLE
[8.0] Time-out while sending multiple concomitent emails

### ISSUE THREAD

**Issue by shmuly007** [odoo/odoo#12112]
Impacted versions: 8.0

Steps to reproduce: Create a Project Issue, press Save.

Current behavior: Pressing save a loading circle appears and stays there until the http server times out. proxy_read_timeout = 90. The users get the email notification but after some time. 

Expected behavior: The created ticket being saved and all the followers  to get a mail notification almost  instantly

Debugging ir.mail.server - when the email is sent there is output, when not (still loading)there's nothing,  like nothing happens and after some time the log appears and the mail is being sent.
Is like waiting for the queue to clear out.

Why this happens?
Here are the specs of the server:
CPU: 2x vCPU
RAM: 2GB

```workers = 3 ```
```max_cron_threads = 2 ```

**Comment by Yenthe666** [comment]
Hi @shmuly007,

This issue can't be reproduced on a runbot (runbot.odoo.com), which is an official instance of Odoo with the latest code.
These problems will have to do with your server configuration OR with custom development that you've added.
@mart-e locky-lock?

**Comment by mart-e** [comment]
That looks indeed like either a problem of deployment or a problem linked to the installed modules/data.
If you can show there is a bug in odoo/odoo source code, we can look at it but we create many issue everyday and it works fine in standard scenario.
Closing as missing info/out of scope

**Comment by shmuly007** [comment]
Hi @Yenthe666 , @mart-e 
Thank you for your responses.

Outgoing mail security was set to SSL/TLS, port 465 and now we've changed it to TLS(STARTTLS), port 587.

In OpenERP 7 we used TLS(STARTTLS), port 587 with absolutely no problem.
I'll keep you updated if this fixes the problem.
