### ISSUE TITLE
[14.0, 15.0, 16.0] purchase: error setting currency_id from context value

### ISSUE THREAD

**Issue by JesusValdez96** [odoo/odoo#121232]
Impacted versions:
14.0, 15.0, 16.0

Steps to reproduce:
In an account move, if the partner_id is changed to one that does not have a value assigned in the property_purchase_currency_id field and with a value in the context for default_currency_id, 
when passing through the _onchange_partner_id function of the purchase module,
the variable currency_id will take the value in the context as second option causing an error when trying to get the value in currency_id.id because currency_id will be an integer and not a record.

https://github.com/odoo/odoo/blob/e4d1a9e0c770d0c6de3119cd24bb890363e8c459/addons/purchase/models/account_invoice.py#LL85

Current behavior:
Error message "AttributeError: 'int' object has no attribute 'id' "  when changing the partner_id.

Expected behavior:

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/108701886/f4a2b344-dbae-48e0-ac47-c4a1bf5e42c2)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
@yosa-odoo Could you check this, please?

**Comment by niyasraphy** [comment]
https://github.com/odoo/odoo/pull/121620

**Comment by niyasraphy** [comment]
hi @JesusValdez96 ,
fixed by:  https://github.com/odoo/odoo/commit/e04d4a0b4d604927252a44a8472fcade300b5f6f

feel free to close the ticket.
thanks
