### ISSUE TITLE
SEO: Tags on Odoo Website Blog should be excluded from indexing of search engines

### ISSUE THREAD

**Issue by fczaja** [odoo/odoo#12128]
## Impacted versions:
- 9.0
## Goal:

All tags of Odoo site should be excluded from indexing of search engines.

Two states:
indexing allows
Indexing not allowed.
## Steps to reproduce:
1. Go to your Odoo the frontend
2. Click in the tag cloud on any tag
3. Pretend your tag a URL site:
4. Example: site: bloopark.de/blog/the-bloopark-times-1/tag/frontend-192
5. Go to Google Search and paste
6. Now you can see that the tag is indexed
## Current behavior:

Currently, all tags can be indexed by the search engines because no Meta Robots statement like "noindex, follow" can be inserted.
## Expected behavior:

In the backend of Odoo a plugin should be involved, which makes it possible to set all the tags to a meta robots instructions in the Head of the site:

The following meta Robots statement should be possible

```
<meta name = "robots" content = "index, follow">
<meta name = "robots" content = "noindex, follow">
```

**Comment by Yenthe666** [comment]
Hi @mart-e and @odony could you two have a look at this please? I'm not sure if this is something that Odoo would want to implement or not, but this one deserves some attention / feedback. :smile:

**Comment by mart-e** [comment]
Hello,

I agree the SEO can be improved and we should probably working on that in the future. The easy fix is to add the `nofollow` attribute on your qweb views.

**Comment by jholze** [comment]
We have done a lot of fixes and improvements, except this :) but maybe we
can talk about to overtake all the Seo fixes we did forces pages, blogs and
website sale. Who is the responsible ?

Regards,Jena

Am Dienstag, 31. Mai 2016 schrieb Martin Trigaux :

> Hello,
>
> I agree the SEO can be improved and we should probably working on that in
> the future. The easy fix is to add the nofollow attribute on your qweb
> views.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/issues/12128#issuecomment-222711170>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGiMAqCdnRrKujOJkMo9AlLyxxtC5pJDks5qHEmngaJpZM4IkQbh>
> .
>


-- 
Jens Holze
CEO & Founder

bloopark systems GmbH & Co. KG

Sternstraße 8, 39104 Magdeburg

Telefon   +49 391 563069-10
Email      jholze@bloopark.com
Website  www.bloopark.de

**Comment by JKE-be** [comment]
Hello @fczaja 

Technically, you can do it with a inherited view of 'blog posts' 

```xml
<data>
    <xpath expr="//t/link[@type='application/atom+xml']" position="after">
            <t t-if="request.endpoint_arguments and 'tag' in request.endpoint_arguments.keys()">
                <meta name="robots" content="noindex" />
            </t>
    </xpath>
</data>
```

**Comment by KurtHaselwimmer** [comment]
I found that the easiest way to stop Google from trying to index hundreds of thousands of blog/tag pages (which it WILL do if you don't do something to stop it) is to have the following section in the robots.txt file (available as view 'robots')

User-agent: *
Disallow: /blog/*/tag/*

To be honest this should be a standard restriction applied by Odoo.

**Comment by Yenthe666** [comment]
@JKE-be perhaps this can be of inspirtation to you to add in the default Odoo for V12?

**Comment by KurtHaselwimmer** [comment]
I would like to edit my comment so that it is not wrong - github has messed about with what I actually wrote

**Comment by JKE-be** [comment]
Not bad for everybody.
It depends of their usages...

https://www.seroundtable.com/google-tag-pages-index-20211.html
https://yoast.com/category-seo/
...
