### ISSUE TITLE
Cannot get wkhtmltopdf working

### ISSUE THREAD

**Issue by jl2035** [odoo/odoo#12137]
I'm running an instance of Odoo 9 and I'm having huge problems with wkhtmltopdf package. First it needed a higher version than my ubuntu box was able to install. Then I downloaded from official website and installed 0.12.1 version, as required by Odoo. That went fine.

user@ubuntu: wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)

But now the problem with pdf continues. I'm getting this stupid js error that does not tell much:

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  https://erp.example.com/web/content/921-3b7313d/web.assets_common.js:2553 Traceback: get_file/$target<@https://erp.example.com/web/content/921-3b7313d/web.assets_common.js:2553:374 jQuery.event.dispatch@https://erp.example.com/web/content/921-3b7313d/web.assets_common.js:740:378 jQuery.event.add/elemData.handle@https://erp.example.com/web/content/921-3b7313d/web.assets_common.js:713:151

I'm reading on the forums that this issue has been around since Odoo 8. How come this was never fixed. Printing PDFs is an important part of an erp sistem and these problems and version confusions are just annoying.

**Comment by sle-odoo** [comment]
Hi,
What's your browser?

**Comment by jl2035** [comment]
Firefox and Chrome

**Comment by tesserB** [comment]
@jl2035 Can you give me a little more context and tell me what you were attempting to print?

"How come this was never fixed[?]"

["Then saith he unto his disciples, The harvest truly is plenteous, but the labourers are few; Pray ye therefore the Lord of the harvest, that he will send forth [more programmers]" ](https://www.biblegateway.com/passage/?search=Matthew%209:37-38)

**Comment by jl2035** [comment]
Basically anything that I want to print causes that json/jquery error.

In point of sale app for example: I go to an Order and click Print -> Receipt. It looks like "Loading" for quite some time, and then the error.

**Comment by gdgellatly** [comment]
1 check logs, that js error is useless.
2 you probably have 2 versions of wkhtml2pdf installed. Normally you need
to symlink the new version on Ubuntu to make it work. Do a search you'll
find it.

**Comment by tesserB** [comment]
Yeah... I was looking for it using grep and wasn't sure that was the actual traceback...
@jl2035 can you check your logs?

"2 you probably have 2 versions of wkhtml2pdf installed. Normally you need
to symlink the new version on Ubuntu to make it work. Do a search you'll
find it."

I know you said you ran "wkhtmltopdf --version", but check and make sure there's only one reference for:
$ whereis wkhtmltopdf

If so, use that or "which wkhtmltopdf" and:
http://askubuntu.com/questions/56339/how-to-create-a-soft-or-symbolic-link

**Comment by jl2035** [comment]
That must be weird, but there's nothing in the logs.

@tesserB you might be on to something. I'm getting this:

```
userl@serverodoo:~$ wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
userl@serverodoo:~$ which wkhtmltopdf
/usr/local/bin/wkhtmltopdf
userl@serverodoo:~$ whereis wkhtmltopdf
wkhtmltopdf: /usr/bin/wkhtmltopdf /usr/bin/X11/wkhtmltopdf /usr/local/bin/wkhtmltopdf
userl@serverodoo:~$ /usr/bin/wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
userl@serverodoo:~$ /usr/bin/X11/wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
userl@serverodoo:~$ /usr/local/bin/wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)
```

**Comment by tesserB** [comment]
This is why I [use /opt/] (https://www.centos.org/docs/5/html/5.1/Deployment_Guide/s3-filesystem-opt.html), per the LSB standard lmao

@jl2035 Can you give me the output for:
$ file /usr/local/bin/wkhtmltopdf
$ file /urs/bin/wkhtmltopdf

And confirm /usr/bin/X11/wkhtmltopdf is just a symbolic link
$ file /usr/bin/X11/wkhtmltopdf

@Yenthe666 I use RHEL distros and I'm thinking this is easy points for you... What would you suggest? (I've seem some jokers say to put it in /usr/bin, which is against the standard, and so I'm a bit confused...)

**Comment by jl2035** [comment]
@tesserB Looks like all three are identical.

```
/usr/local/bin/wkhtmltopdf: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=b1768848fb27bf39691115d9ca8f1cc11b28b7c6, stripped

/usr/bin/wkhtmltopdf:       ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=b1768848fb27bf39691115d9ca8f1cc11b28b7c6, stripped

/usr/bin/X11/wkhtmltopdf:   ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=b1768848fb27bf39691115d9ca8f1cc11b28b7c6, stripped
```

**Comment by tesserB** [comment]
@jl2035  I know this might sound silly, but this is an installation issue and the GitHub "issues section is reserved for bugs". Still, if you don't mind doing me a favor and closing this issue, I would be more than happy to help you get sorted through email.

You can also try to reinstall wkhtmltopdf and see if that works for you:

1. Uninstall wkhtmltopdf.

2. Confirm it's been removed using the whereis command.
(I don't use Ubuntu/Debian and I install my packages differently. That said, I'm probably being overly cautious here...)

3. Entering the following command, `$ sudo ls -Al /etc/apt/sources.list.d/`, and ensure you don't see anything related to wkhtmltox.  If you do, remove it: `sudo rm /etc/apt/sources.list.d/[wkhtmlto?].list*`

4. Follow the instructions provided by another community member through the mailing list:

4a. sudo apt-get install xvfb

4b. wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb

4c. sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
4d. sudo apt-get -f install

Respectfully,
Cody K.
ckitterm@gmail.com

Mailing Lists:
https://www.odoo.com/groups

Help Forum:
https://www.odoo.com/forum/help-1


@Yenthe666/@sle-odoo Gentlemen...

**Comment by jl2035** [comment]
I think I successfully reinstalled using your instructions.

I can close the issue, but I'm still getting that same error..

**Comment by jl2035** [comment]
It's been a while. I still cannot print pdfs. :(
Reopening.

**Comment by dreispt** [comment]
Other people seem to be able to print to PDF correctly, so chances are that it's not a product issue.
Can you reproduce the error in then Runbot? The issue here is that the issue is not reproducible, and seems to be specific to your installation. 

Since the only thing you have is a JS error, I suggest you to reproduce the error while having the Developer mode enabled. Maybe that can give a more useful error message. And please detail the action you are performing that generates that error.

**Comment by jl2035** [comment]
Damnit, I just set up new odoo instance on a new server and it seems you are right. After taking the following steps it actually works.

sudo apt-get install xvfb
wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
sudo apt-get install fontconfig libxrender1 xfonts-75dpi
sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
sudo apt-get -f install
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bit/wkhtmltopdf

@dreispt running with developer mode doesn't help in getting any clue from the error

I really hate myself. Why did I have to mess this up on the production server!

**Comment by jl2035** [comment]
Also tried uninstalling wkhtmltopdf and following the above steps again. No luck!

**Comment by dreispt** [comment]
@jl2035 In DevModel web assets are not minified (and obfuscated), so it's easier to see what is going on JS-wise...

**Comment by jl2035** [comment]
As of June 2017 the download link is broken. Releases are available here: https://downloads.wkhtmltopdf.org/0.12/0.12.2.1/

**Comment by YasminMostafa** [comment]
I installed Odoo Bitnami version 10 i have error in printing it give me this error (Unable to find Wkhtmltopdf on this system. The report will be shown in html.)
(Unable to find Wkhtmltopdf on this system. The PDF can not be created.)

I Done the following : 
1-sudo wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb
2-sudo apt-get -f install 
3-sudo apt-get install libjpeg8 libpng12-0 xfonts-base xfonts-75dpi
4-sudo dpkg -i wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb
5-sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/        Error No such a bath
6-sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/    Error No such a bath
7-sudo /opt/bitnami/ctlscript.sh restart apache 

Is There something messing please advise

**Comment by jl2035** [comment]
@YasminMostafa yeah this is fucked up. I always had to create a new server and install everything again from scratch.

**Comment by mozzee** [comment]
facing same issue with Odoo 17 on CentOS 7, can not print anything

**Comment by bhiggin** [comment]
I had the same issue, and resolved it by changing the system parameter "web.base.url" back to "http://localhost:80".

Unfortunately, this leaves my auto-generated emails (password resets, invitations, etc.) containing incorrect domain links.

Hope this works for you,

Brad

**Comment by AngelCamacho** [comment]
You could try the parameter report.url to http://127.0.0.1 , not the web.base.url to aviod the password, invitations problems. 



----- Missatge original -----

De: "bhiggin" <notifications@github.com> 
Per: "odoo/odoo" <odoo@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Enviats: Dimarts, 19 de Setembre 2017 23:56:23 
Assumpte: Re: [odoo/odoo] Cannot get wkhtmltopdf working (#12137) 



I had the same issue, and resolved it by changing the system parameter "web.base.url" back to " http://localhost:80 ". 

Unfortunately, this leaves my auto-generated emails (password resets, invitations, etc.) containing incorrect domain links. 

Hope this works for you, 

Brad 

— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 




-- 

__________ 

Angel Camacho Perez 
Responsable de proyecto 
angel.camacho@minorisa.net | 93 874 86 86 


minorisa.net | facebook | linkedlin | google maps | Privacitat 
T. 93 874 86 86 | F. 93 874 08 59 | 
Pica d���Estats, 77-95 (Pol. Ind. Sant Isidre) 08272 Sant Fruit��s de Bages
