### ISSUE TITLE
[9.0][BUG] Client Returns wrong sequence order in onchange calls and breaks sequence sensitive tax calculation

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#12142]
**Impacted versions:**
9.0c

**Steps to reproduce:**
Create an invoice with a product which has following configuration:
1. has a tax with low sequence and starts with "X" (don't know if that's relevant, but I observed this alphabetical pattern in my setup)
2. has a second tax which has a high sequence and starts with "A"
3. has the second tax configured to be incorporated in the in the base value of the "next" tax

**Current behavior:**
The first iteration of calculation shows the correct values, yet the second iteration launched by the client passes a jason request where taxes are in the wrong order (first to be observed in _call_function of http.py arround line 316) this is passed on through wrappers without further sorting and is resulting in the wrong order of calculation. You obtain a base value, which is altered by the second tax "A" and then the first tax "X" will be applied on this altered value.

**Expected behavior:**
Sequence is respected. Either client respects it, or server validates it.

Video/Screenshot link (optional):

**Comment by blaggacao** [comment]
strange thing at the client server interface, so
cc/ @KangOl @odony 

fyi @kurkop

**Comment by blaggacao** [comment]
@qsm-odoo maybe this relates to you, too as of 3abe93715af1

**Comment by pedrobaeza** [comment]
This is something not controlled at client level, and the computations are done on server side. I'm not sure what do you intend to do with onchanges in this case, but I appreciate no real issue here, so I close it. Feel free to open a new issue being more specific if you consider.

**Comment by blaggacao** [comment]
@pedrobaeza Thanks for cleaning this. It's too old to remember... :wink:
