### ISSUE TITLE
[9.0] List View - if editable and create="0" - Save/Cancel buttons are missing

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#12157]
Impacted versions: 9

Steps to reproduce: create a tree view with editable="top" create="0"

Current behavior: while editing a line, there is no Save/Cancel buttons

Expected behavior: having a Save/Cancel buttons but no Create/Import ones.

Video/Screenshot link (optional):

**Comment by be-cloud-js** [comment]
I think there is an issue here, the t-if should only apply to the create button

https://github.com/odoo/odoo/blob/3b234a23cb3cf8b659f849c231fa3b2e160213b5/addons/web/static/src/xml/base.xml#L414

Jerome

**Comment by be-cloud-js** [comment]
And then here, the extension should be done another way.

https://github.com/odoo/odoo/blob/3b234a23cb3cf8b659f849c231fa3b2e160213b5/addons/web/static/src/xml/base.xml#L456

I will try to make a Pull Request as soon as I have got some time.

Jerome

**Comment by Yenthe666** [comment]
@mart-e can you give your input on this? I don't think this is something Odoo wants to change or am I wrong here?

**Comment by be-cloud-js** [comment]
The Fix is not difficult,

<t t-name="ListView.buttons">
    <div class="oe_list_buttons">
        <t t-if="!widget.no_leaf and widget.options.action_buttons !== false and widget.options.addable and widget.is_action_enabled('create')">
        <button type="button" class="btn btn-sm btn-primary o_list_button_add" accesskey="C">
            <t t-esc="widget.options.addable"/>
        </button>
        </t>
    </div>
</t>

and

<t t-extend="ListView.buttons">
    <t t-jquery="div.oe_list_buttons" t-operation="inner">
        <button type="button" class="btn btn-primary btn-sm o_list_button_save" accesskey="S">
            Save
        </button>
        <button type="button" class="btn btn-default btn-sm o_list_button_discard" accesskey="D">
            Discard
        </button>
    </t>
</t>

Jerome

**Comment by adr-odoo** [comment]
This issue has been fixed.
See:
https://github.com/odoo/odoo/commit/0afe5d4af52448c2dcaca7b8537c2c6c08c7fbb5
https://github.com/odoo/enterprise/commit/8a77abcbb2ad00528a9e9ac28d06db4cb6c4d621

**Comment by be-cloud-js** [comment]
Thanks

Jerome
