### ISSUE TITLE
module web_studio can't install, if you install it got crash

### ISSUE THREAD

**Issue by Sotatek-TrungPham** [odoo/odoo#121589]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Sotatek-TrungPham** [comment]
![image](https://github.com/odoo/odoo/assets/133617788/59680862-581a-407f-bf35-1a4dda830423)

**Comment by niyasraphy** [comment]
hi @Sotatek-TrungPham ,
please update the ticket with more information like which version and also provide log details, as per my knowledge there is no such installation issue with studio module, you may have to try installing the same module in a fresh db and see.

also make sure that yo are using the latest source code of the corresponding version.
thanks

**Comment by vava-odoo** [comment]
@Sotatek-TrungPham feel free to open again if you have steps to reproduce
