### ISSUE TITLE
Odoo9: Checkboxes are not checked, but seem to have Value

### ISSUE THREAD

**Issue by Niklas1994** [odoo/odoo#12150]
Impacted versions: Version 9.0e-20160524 (Enterprise Edition), on Windows 7 x64

Steps to reproduce: I login into Odoo and go for example to Configuration -> General Settings. I change a setting somewhere, which is changed by a checkbox.

Current behavior: The "check" is not showing. The Value seems to be changing, but there is no check visible. In Google Chrome (Console) I dont see a 404 Error - the "checked.svg" file is in the Folder C:\Program Files(x86)\Odoo 9.0-20160524\server\openerp\addons\web\static\src\img

Expected behavior: A check should show up.

Video/Screenshot link (optional): https://vid.me/oF8h

**Comment by Yenthe666** [comment]
Hi @Niklas1994,

This might actually be the same report as https://github.com/odoo/odoo/issues/9061. (Which I actually closed a minute ago).
@mart-e could you let somebody check this out?

Regards,
Yenthe

**Comment by Niklas1994** [comment]
Im not sure, because i just downloaded the newset Odoo Version 2 hours ago... Or was there a new release in between?

**Comment by Yenthe666** [comment]
@Niklas1994,

The other report is from october 2015, but they seem to be talking about the same thing so it might be the same issue.

**Comment by Niklas1994** [comment]
Is it possible to say when there is a solution available?

**Comment by JKE-be** [comment]
Hello @Niklas1994 

I have just tested with a win7 x64 (runbot version) and I cannot reproduce your bug.

Do you have the bug on the runbot ? Can you reproduce the problem here: http://runbot.odoo.com/runbot/7/9.0

I don't say that it is not Odoo the problem, i'm just tying to understand if the problem is in Code Odoo, or in the packaging of Odoo for Windows or maybe fixed meanwhile ?

Thank for your reporting

**Comment by Niklas1994** [comment]
The Problem still occurs on my system. 

I cant reproduce the problem on the runbot - its working fine there. I will download the newest build from today and install it again! :)

**Comment by JKE-be** [comment]
We don't change anything meanwhile (I think) concerning the packaging.
So I have some doubts that reinstall will fix the problem.

I ping you when I have more news about this issue.
I will test and fwd if needed to the packaging responsible.

Thanks

**Comment by Niklas1994** [comment]
I dont have this problem with a community version by the way. I downloaded the community version to another Server one week ago - i didnt have the problem there.

**Comment by JKE-be** [comment]
Community version dont use new webclient and new checkbox.

I have installed an Odoo 9 on new windows and I don't have the problem.
So it's seems that it is a problem in your installation :(

Could you check that you can load in your browser: yourname:8069/web/static/img/checked.svg
And what is the dom of your checkebox. it should appear in the clostest span below the input.
Can you check that it is load backgounrd-image on the span?

Have you try with IE or other browser to be sure that it's not a restriction in your chrome version ? which version of chrome do you have ? I have tested with IE 11.0.9600.18015 & Chrome 50.0.2661.102 m without any problem.

**Comment by Niklas1994** [comment]
The ressource cant be found! I get a 404 Error...
I had ta closer look on the path, where my checked.svg is saved. The path is:

C:\Program Files (X86)\Odoo 9.0-20160524\server\openerp\addons\web\static\src\img

There is an extra "src" folder... is that correct?

Interesting fact: If i change the background PNG File. The change is shown in Firefox, but not in Chrome. But the checked.svg is not showing up in both browsers.

**Comment by JKE-be** [comment]
hello, 
yes sorry It is a typo, you should have yourname:8069/web/static/src/img/checked.svg
It is very strange behavior...

Maybe you could change the less to load a red square in png just to test...
Have you updated recently your chrome ? which version do you have ?

**Comment by Niklas1994** [comment]
If i call the URL from the SVG File, it shows me this:
`<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="15px" height="15px" viewBox="0 0 15 15" enable-background="new 0 0 15 15" xml:space="preserve">
<g>
	<path fill="#666766" d="M12.385,5.578L7.65,10.313l-0.89,0.888c-0.119,0.119-0.281,0.184-0.444,0.184
		c-0.162,0-0.328-0.064-0.445-0.184l-0.89-0.888L2.615,7.944C2.497,7.828,2.432,7.664,2.432,7.5c0-0.163,0.065-0.325,0.183-0.444
		l0.89-0.89c0.118-0.117,0.281-0.183,0.444-0.183c0.164,0,0.327,0.065,0.445,0.183l1.923,1.929l4.289-4.296
		c0.119-0.118,0.282-0.183,0.445-0.183c0.164,0,0.327,0.065,0.445,0.183l0.889,0.89c0.118,0.118,0.184,0.281,0.184,0.445
		C12.568,5.296,12.503,5.46,12.385,5.578z"/>
</g>
</svg>
`

**Comment by Niklas1994** [comment]
There seems to be a problem rendering SVG Files.
I tried exchanging the SVG File, to make sure, the given SVG File is not broken. It didnt help anything. Then I downloaded a checked PNG Image and replaced "checked.svg" with "checked.png" In Chrome developer Tools --> A wonder, the checked Icon is showing up.

**Comment by Niklas1994** [comment]
Funny Fact - Ans sorry for those many Posts, but If i have a look at the header from the response of getting the checked.svg, I see following:

Content-Type:text/plain

Shouldn't that be

Content-Type:image/svg+xml

When its used in a background-image or img Tag context?

**Comment by tesserB** [comment]
@Niklas1994
"Shouldn't that be... Content-Type: image/svg+xml"
That's 100% correct, sir, and explains why replacing the file works within Chrome's dev tools...

And can you save me some typing and upload "checked.svg" for me?

**Comment by JKE-be** [comment]
Hello, yes it should be svg+xml and it wwhy you see xml code instead of icon when you specify the static url in your browser.

Can you force you server to serve these files as image/svg+xml ?

Eg: 

> /etc/nginx/mime.types  

```image/svg+xml svg svgz;```

**Comment by Niklas1994** [comment]
Hey Guys, 
Thanks very much. I would know where to place htaccess File on linux - but I have it Installed on Windows - where is the folder on Windows to place the .htaccess file?
Cheers

**Comment by JKE-be** [comment]
If you have just installed the package, static file should be serve directly by odoo.

Can you 'temporarily' patch the file /openerp/http.py 
    Add at line 1379
    ```mimetypes.add_type('image/svg+xml', '.svg')```

And restart the service Odoo-9 please.

Let us know.

**Comment by Niklas1994** [comment]
Wonderfull - its working now!

**Comment by Yenthe666** [comment]
Seems like we have a fix that can be made by @JKE-be then? :smile:
