### ISSUE TITLE
Error while installing pip requirements.txt step

### ISSUE THREAD

**Issue by ahmedsliman** [odoo/odoo#12168]
Impacted versions:  9.0 source version, install on windows

Current behavior:
While this step in installing docs.
`C:\YourOdooPath> C:\Python27\Scripts\pip.exe install -r requirements.txt`

i get message in log file after a lot of warning:

> Cleaning up...
>   Removing temporary dir c:\users\ahmed\appdata\local\temp\pip_build_ahmed...
> Exception:
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "C:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "C:\Python27\lib\site-packages\pip\req.py", line 1435, in install
>     requirement.install(install_options, global_options, *args, **kwargs)
>   File "C:\Python27\lib\site-packages\pip\req.py", line 671, in install
>     self.move_wheel_files(self.source_dir, root=root)
>   File "C:\Python27\lib\site-packages\pip\req.py", line 901, in move_wheel_files
>     pycompile=self.pycompile,
>   File "C:\Python27\lib\site-packages\pip\wheel.py", line 215, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "C:\Python27\lib\site-packages\pip\wheel.py", line 209, in clobber
>     shutil.copy2(srcfile, destfile)
>   File "C:\Python27\lib\shutil.py", line 130, in copy2
>     copyfile(src, dst)
>   File "C:\Python27\lib\shutil.py", line 83, in copyfile
>     with open(dst, 'wb') as fdst:
> IOError: [Errno 13] Permission denied: 'C:\\Python27\\Lib\\site-packages\\win32\\win32api.pyd'

Expected behavior:
installing all packages in requirements.txt

**Comment by tesserB** [comment]
Good Afternoon Ahmed:
     I assume you've added "pypiwin32" to the requirements.txt. Try re-running the above command―pip install -r requirements.txt―as an administrator: 
right click "Command Prompt" icon > "Run as administrator" > "cd C:\Python27\Scripts\"...

Also, as a friendly reminder, don't forget to:
"remove psycopg2 as you already have it.
remove the optional python-ldap, gevent and psutil because they require compilation.
add pypiwin32 because it's needed under windows."

R/S
Cody

@Yenthe666 We're good here, sir.

**Comment by Yenthe666** [comment]
@tesserB Loving your input and help, thanks man!
@ahmedsliman can you let me know if this got you going please?

**Comment by ahmedsliman** [comment]
@tesserB  @Yenthe666 

I remove the temp files and reinstall after installing psycopg2 manually "windows installer" and it works right now

Thanks

**Comment by Yenthe666** [comment]
Alright closing this since you've fixed it. Thanks!
