### ISSUE TITLE
[7.0] Sale and purchase taxes are not get from account.accout default tax

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#1217]
Default taxes defined in product's income or expense account (product_template.property_income_account and product_template.property_expense_account) does not work in sale orders or purchase orders.

The situation can be generated like this:

1) create product. Define income account bot does not define any taxes direct to the product.
2) Define default tax to income- and expense accounts related to the product
3) Create SO and select the product you created. There is on taxes on that SO.

Expected behavior would be that if there is no taxes defined in product, default taxes from income account should be used.

There is same situation with purchase orders as well.

This is a tricky situation when you are working with multi-company database since product tax definition is not property.

Bug source: https://bugs.launchpad.net/openobject-addons/+bug/796570

**Comment by Yenthe666** [comment]
Hi @kenvac,

Thank you for your report and sorry for the late reply. Odoo only supports three versions back, meaning that Odoo V7 is no longer supported.
I don't believe this is a bug in the latest V7 anymore though. If you still face this issue please update your source code and try again.
If you can reproduce this issue in V8, V9 or V10 you're free to create a new bug report so we can handle it.

Regards,
Yenthe
