### ISSUE TITLE
Unable to remove the Create button on Many2Many Popup Listview

### ISSUE THREAD

**Issue by app-cedric** [odoo/odoo#1218]
The attribute create="false" has no effect on a Many2Many ListView opened in Popup.

**_Impacted versions:**_
- 8 alpha

**_Steps to reproduce:**_
1. Add create="false" on the Account Tax Template list view (addons/account/account_view.xml, record id="view_account_tax_template_tree"
2. Go to Invoicing > Configuration > Accounts > Templates > Accounts > Account Template
3. Pick one and Edit
4. Add an item on Default Taxes

**_Current behavior:**_
- The [Create] button is visible on the footer of the Popup

**_Expected behavior:**_
- The [Create] button should not be available.
  
  I tried to put the create="false" wherever I could, but the create button is always available in popup views.

**Comment by tgr-odoo** [comment]
+1

**Comment by spadae22** [comment]
Yes, need to solve that. I removed permissions from UOM. If you goto config UOM you can view but not create or add, but the when in the sales order line, it will show create and edit.

**Comment by Yenthe666** [comment]
Hi @app-cedric,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
