### ISSUE TITLE
[8.0] Website sale order change price unit on confirm

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#12187]
### Impacted versions:
8.0

### Steps to reproduce:

- on the website, add some products to the cart
- on the backend, change the unit price of one sale.order.line
- back on the website, at /shop/confirm_order, confirm the order

### Current behavior:
Unit price reverted to product price

### Expected behavior:
Unit price should not change

### Notes:
Not entirely sure if this is a feature or a bug. If this is a feature, how would one make an order.line with a random price, depending on user input ? (Donation)

**Comment by JKE-be** [comment]
Hello, like you specify in your 'Notes', it's not a bug ... but a whihlist...
We force to recompute price on confirm order to be sure to apply the right fiscal position and co.
Best way to do it is to do a product Donation with unit price 1 and change the quantity !
1 x 99$ or 99 x1$... it's the same :)

**Comment by yannprada** [comment]
I though of the qty trick. But it's very ugly IMO. Oh well,  thanks ^^
