### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': '[ng:cloak]' is not a valid selector.

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#12196]
Impacted versions:
V9.0c

Steps to reproduce:
Clicked on Preference button for user

Current behavior:
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': '[ng:cloak]' is not a valid selector.

Expected behavior:
User preference tab should open

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sharkutz,

Thank you for this report. Are ou talking about this preferences button?
![image](https://cloud.githubusercontent.com/assets/6352350/15578095/70e6b6fa-235f-11e6-98a8-960753fcfb0e.png)

This no longer gives an issue on the latest codebase. If this is the menu you're talking about you should an update from your local Odoo installation.

**Comment by JKE-be** [comment]
Hello @sharkutz 
It sound like a bug of AngularJS which one is not used in Odoo v9c in standard.
Don't hesitate to reopen an issue if you arrive to reproduce this bug in the runbot version (without any extra module) and with a browser without extra addons which could try to bind your click and co...

**Comment by sharkutz** [comment]
Yes you ar right, an update fixed the issue
