### ISSUE TITLE
[9.0] Issue: Odoo allows deleting recurring type even it's used in recurring document

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#12208]
Impacted versions:
9.0

Steps to reproduce:
1) Create a new recurring type and name it anything you want,set it's type as invoice
2) Create a new recurring document and name it anything,set source document to the recurring type you created earlier then choose an invoice from the list,save your changes
3) Delete recurring type
4) Go back to the recurring document you created earlier and click on edit,notice that value of Source document is "UNKNOWN"

Current behavior:
Go back to the recurring document you created earlier and click on edit,notice that value of Source document is "UNKNOWN"

Expected behavior:
Odoo shouldn't allow deleting related data (recurring type) if it's used in recurring documents

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This module is deprecated and 9.0 in its end of life cycle, so this is will be hardly fixed, so I close.
