### ISSUE TITLE
[9.0e] Search More on carrier_id field gives error and shows no result

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#12203]
### Impacted versions:
9.0e

### Steps to reproduce:
1) Start a new DB with demo data
2) Create a new sale order
3) Select "Pizza Inn" as Customer
4) Select "[A1232] iPad Mini" as product
5) Save
6) Edit
7) Click the Delivery Method drop down field and select "Search More..."

### Current behavior:
An error occurs and no results are shown:
> 3021: The destination country IN location postal code 607308 or City New Delhi TN is invalid. Please check the destination country location details.

If you search for one or many specific carriers you know work like "Fedex Int", results with prices are returned.

It happens because when any carrier gives an error when calculating the price, the error is thrown and shown to user, and furthermore prevent showing any result.

### Expected behavior:
Errors are silent. All carriers are shown with calculated price. Price is empty when an error occurs while calculating a carrier price.

**Comment by Yenthe666** [comment]
Hi @krueger80,

I've just tested this case and I can confirm this is a bug:
![image](https://cloud.githubusercontent.com/assets/6352350/15626550/7a6e0a66-24c7-11e6-897f-31736f6f8994.png)
On a sidenote: your issue says it is for 9.0, but it is only the case for 9.0 Enterprise, not community.
@nim-odoo this one is for you.

**Comment by nim-odoo** [comment]
@Yenthe666 :  @rim-odoo has a better knowledge on that topic.

That said, I don't think we want to mute the error, otherwise the user is not aware that something is going wrong.

**Comment by rim-odoo** [comment]
It is a well known bug, but hard to fix in a clean way...

**Comment by krueger80** [comment]
Maybe have always the error message written in a new field "estimate_error" (store=False) on delivery.carrier model. This field could be shown in the search more view.

In the get_price method, first remove the @api.one to allow looping in all carriers. Now every error can be catch and be saved in "estimate_error" field. The function get_price shouldn't throw any error from my understanding, otherwize that prevent showing any record. I see that there is an "available" fields that isn't used anywhere else. It should be use to know if carrier has a price available or not and prevent confirming the sale in this case.

So here the the change I would make to get_price. Also change "view_delivery_carrier_tree" to add "estimate_error" field. Now this fix doesn't solve the problem of #12204.

```
    def get_price(self):
        SaleOrder = self.env['sale.order']

        order_id = self.env.context.get('order_id')

        if order_id:
            order = SaleOrder.browse(order_id)

            for carrier in self:
                carrier.available = False
                carrier.price = False

                if carrier.delivery_type not in ['fixed', 'base_on_rule']:
                    try:
                        carrier.price = carrier.get_shipping_price_from_so(order)[0]
                        carrier.available = True
                    except Exception as e:
                        carrier.estimate_error = e
                else:
                    carrier = carrier.verify_carrier(order.partner_shipping_id)
                    if carrier:
                        try:
                            carrier.price = carrier.get_price_available(order)
                            carrier.available = True
                        except Exception as e:
                            carrier.estimate_error = e
                    else:
                        carrier.price = 0.0
```

**Comment by rim-odoo** [comment]
Actually, I don't think it is a good idea to display this "search more" (in stable at least).
(The original plan was to disallow the "search more", I don't know why it is still there.)

-> With this "search more", you can get the price of every shipping according to your current sale order. 
-> If you have an integration with an external shipper (like Fedex or UPS), it means that displaying the list of shippers+price will cost lots of seconds to poll every shipper...

**Comment by rim-odoo** [comment]
I agree that all the code could be refactored and cleaned in a next version. Feel free to submit a PR against odoo/odoo:master branch.

**Comment by krueger80** [comment]
In our use case we can have tens of delivery carriers. Not being able to show the entire list is kind of extreme. At least, you should show the list with the name only.
