### ISSUE TITLE
Error on Point of sale odoo16 after installing a custom module

### ISSUE THREAD

**Issue by addyaddy22** [odoo/odoo#122046]
Impacted versions: odoo 16

Steps to reproduce:

Current behavior:TypeError: Cannot read properties of undefined (reading 'el')
    at customReceiptScreen.printReceipt (http://154.119.80.8:8010/web/assets/522-7bf4ed1/point_of_sale.assets.min.js:5324:187)
    at customReceiptScreen.handle
![Screenshot from 2023-05-23 11-02-09](https://github.com/odoo/odoo/assets/88889744/0d7e7eb4-4f73-4c7d-a716-0b615df21d4b)
AutoPrint (http://154.119.80.8:8010/web/assets/522-7bf4ed1/point_of_sale.assets.min.js:5319:232)
    at http://154.119.80.8:8010/web/assets/522-7bf4ed1/point_of_sale.assets.min.js:1433:12

Expected behavior: to print the receipt

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @addyaddy22 ,
as you said, it is due to the third party app, please cross check the written code or contact the app author for the support. as it is not an issue inside odoo core, feel free to close the issue.

thanks

**Comment by vava-odoo** [comment]
Hello @addyaddy22,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
