### ISSUE TITLE
Move type check in domain 

### ISSUE THREAD

**Issue by jadiribnahasan** [odoo/odoo#122032]
https://github.com/odoo/odoo/blob/e542c4a01fc19b98b4a47e40e4d15c2afc987dee/addons/account/controllers/portal.py#L47

Shouldn't the domain be ('move_type', 'in', ('out_invoice', 'out_refund')) instead of ('move_type', '=', ('out_invoice', 'out_refund')) ?

**Comment by niyasraphy** [comment]
hi @vava-odoo ,
the same seems to be existing from 14.0 , but somehow it is getting worked as expected without any issues.

**Comment by jadir-bs** [comment]
@niyasraphy, I already gave one.

**Comment by niyasraphy** [comment]
@jadir-bs can you retarget the PR to 14.0

**Comment by jadir-bs** [comment]
@niyasraphy didn't you already target 14.0?

**Comment by niyasraphy** [comment]
yes, if you need your PR to be accepted(i will close my PR, as you reported the issue) it has to target the lowest support version and then it will forward ported to the higher version

**Comment by jadir-bs** [comment]
@niyasraphy, Sure then.

**Comment by william-andre** [comment]
Already closing as the related PR has been approved :+1:
