### ISSUE TITLE
[9.0] POS: Priced barcodes and Weight barcodes from Barcode Nomenclatures not working

### ISSUE THREAD

**Issue by douwma** [odoo/odoo#12205]
**Impacted versions:**
9.0
**Steps to reproduce:**
Use the following instruction from the manual:
Let us now assume that we want to write a barcode for a given Weighted Product, say oranges. We first have to define in product oranges a barcode that will match the Weighted Product rule. This barcode must start with '21' and be a correct EAN-13 barcode (i.e. the 13th digit must be a correct checksum). Moreover, all the numerical content must be set to a '0'. For instance, let us set the barcode to '2100001000004'.

We now want to write a barcode for 2.75kg of oranges. This barcode should be '2100001027506' (the numerical content of this barcode is '02750', and the correct checksum is '6'). When scanned, this barcode matches the Weighted Product rule (since is starts with '21'). The numerical content is extracted, and replaced by a sequence of '0's. The correct checksum is then computed for the obtained barcode ('2100001000004') and the corresponding product (oranges) qgit is retrieved from product table.

**Current behavior:**
When scanning the barcode 2100001027506 in POS it throws an error saying that no product is found.
**Expected behavior:**
When scanning the barcode 2100001027506 it should use the product linked to 2100001000004 times weight 2.75.
**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment]
@jorenvo I think this might be something for you. Is this not implemented / working for a reason or?

**Comment by douwma** [comment]
The issue was solved in the following commit:

https://github.com/odoo/odoo/commit/526c38cdb145143407cc0e5504574e72f7e720a0

I've tested and it's working now!

**Comment by Yenthe666** [comment]
:+1: thanks for pointing that out yourself @douwma!
