### ISSUE TITLE
[9.0] website_hr_recruitment public user can't view job list

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#12210]
Impacted versions: 9.0

Steps to reproduce:
1.- make a new recruitment process 
2.- set as public
3.- Set not required login
4.- log out , an go to /jobs 
5.- list is empty
6.- login
7.- now you can see new entries 

Current behavior:
 Public user can't see new recruitment entries

Expected behavior:

Public user can see it

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,
I cannot reproduce your bug ... I hae just tested on v9 now.
What do you mean by step 3: '3.- Set not required login' ???

Else when you specify '2.- set as public', be sure that you are redirect on website and need to click again on the red button "not published'.

Could you confirm that when you are connected as admin you see the button green 'Published' and that when you are unlogged, you dont see the job... ?
If yes, please provide video !

**Comment by dansanti** [comment]
Hello! here the video:
https://dl.dropboxusercontent.com/u/15378442/out-5.ogv

**Comment by JKE-be** [comment]
Ok, So the post is well published. You got a 403 and not a 404.
It seems to be a access right error, could you check in your log and give us the traceback ? 
Thank you for the reporting

**Comment by JKE-be** [comment]
Can you reproduce the bug on runbot ? 
http://150450-9-0-be91fa-base.runbot.odoo.com/ admin/admin

Do you have some customization (custom model) in your instance? 

Sorry, I cannot reproduce your bug on a fresh db and without log that not easy to guess the model which have access right misconfigured.

**Comment by dansanti** [comment]
Seems, that only admin user can create a new recruitment process, my demo was create without admin account,  today i create a new recruitment called demo2  with admin account, and  i can see only demo2 , demo1 still hidden for public, 

This is the log when try to access with public to demo1 http://pastebin.com/2NJGgP9T

**Comment by dansanti** [comment]
Ok, i found the problem, if you ave activated multicompany,  and ie. 2 company, every time take jobs from last company in list, on link1, and link2 show the same result, and if i manual change company_id in hr.job on db, and put the id of last company, jobs was showed in both links.
 In website_admin i have 2 sites configs with those links

**Comment by dansanti** [comment]
https://github.com/odoo/odoo/issues/12229

**Comment by JKE-be** [comment]
Thank you for your analyze and you new issue !
