### ISSUE TITLE
Error in adding Outlook Incoming Mail Server 

### ISSUE THREAD

**Issue by wm-cortex** [odoo/odoo#122193]
Impacted versions:
15.0, 16.0

Steps to reproduce:
Try to the configure the Incoming Mail Server for Outlook once you click on **connect to you outlook account** link, getting the below error:

AttributeError: 'fetchmail.server' object has no attribute 'smtp_user'

I think the error related to this commit #121526 

Current behavior:
Can't configure the outlook incoming mail server.

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by yboujraf** [comment]
I am confirming same issue [#44943](https://github.com/odoo/odoo/issues/44943#issuecomment-1559501622)

**Comment by yboujraf** [comment]
FYI, the fix is merged on odoo 14,15,16, ... https://github.com/odoo/odoo/pull/122483

With Odoo 15 CE, the fix works and I am able to get the 'Outlook Token Valid' and fetch email again.

**Comment by vava-odoo** [comment]
Thanks @wm-cortex for reporting, @niyasraphy for fixing and @yboujraf for following up!
