### ISSUE TITLE
Wrong domain for account type regular for Reconcile Payment Balance

### ISSUE THREAD

**Issue by aek** [odoo/odoo#12227]
Impacted versions: Tested in v8

Steps to reproduce: Create an invoice, validate it and register a Payment with more than the expected total of the Invoice. Select "Reconcile Payment Balance" in the field "Payment Difference" and you could only select an account of type Regular in the field "Counterpart Account". 

Current behavior: This cause that you couldn't directly use the difference of the payment in another payment without make a move from the previous account to a Receivable or Payable account depending of the type of Payment that you wanna make using the menu Customer Payments or Provider Payments. If you make a manual move from the Regular account you could use the amount that exceed the Invoice Payment to pay others Invoices 

Expected behavior: When you select "Reconcile Payment Balance" in the field "Payment Difference" and you should be able to select an account of type Receivable or Payable in the field "Counterpart Account". Depending of the Invoice type in-invoice or out-invoice for Customers or Provider Invoices. After that you will be able to use that amount that exceed to pay others invoices

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @aek,

What exactly do you mean with "Select "Reconcile Payment Balance" in the field "Payment Difference" and you could only select an account of type Regular in the field "Counterpart Account"."?
I can select any value in the field "Counterpart Account"?
![image](https://cloud.githubusercontent.com/assets/6352350/15664761/bb9df7c6-2706-11e6-9a2c-01cf83c1885d.png)

**Comment by aek** [comment]
Hi @Yenthe666 
After select the value "Reconcile Payment Balance" in the field "Payment Difference", the field "Counterpart Account" have a domain to only allow you to select  accounts of type "Regular". You cannot select any Payable or Receivable accounts to be able to do the described behavior. Exactly this code in 3 different places(views: view_vendor_payment_form, view_vendor_receipt_dialog_form, view_vendor_receipt_form):

```xml
<field name="writeoff_acc_id" attrs="{'invisible':[('payment_option','!=','with_writeoff')], 'required':[('payment_option','=','with_writeoff')]}" domain="[('type','=','other')]"/>
```

**Comment by Yenthe666** [comment]
Hi @aek,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
