### ISSUE TITLE
[9.0] point_of_sale cash.box _compute_values_for_statement_line renamed in 9.0

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#12224]
Impacted versions:
9.0

Steps to reproduce:
method _compute_values_for_statement_line has been renamed to 
_calculate_values_for_statement_line so overloads in point_of_sale module are not applied.

**Comment by Yenthe666** [comment]
@JKE-be could you have a look at this one please?

**Comment by JKE-be** [comment]
Maybe @mart-e which one is familiar with the POS

**Comment by Yenthe666** [comment]
@jorenvo pinging you too for this one.
