### ISSUE TITLE
[KNOWLEDGE] PyPy Support

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#12221]
Not a bug, just an attempt to gather knowledge, info:

Having scanned: http://packages.pypy.org/, the following packages are the only ones, which are not listed as "explicitly compatible".

`psycopg2==2.5.4`, use of https://pypi.python.org/pypi/psycopg2cffi is recommended which comes with a nice compatibility patch:
```
from psycopg2cffi import compat
compat.register()
```
`gevent==1.0.2` -> version 1.1 is tagged as compatible, a bump could be considered.

The following python packages are not listed, which does not mean they are incompatible, by default.
```
jcconv==0.2.3
ofxparse==0.14
Python-Chart==1.39
vatnumber==1.2
vobject==0.6.6
```

Furthermore there has been a PR to save_eval in order to achieve PyPy Support:
https://github.com/odoo/odoo/pull/7839

**Comment by tesserB** [comment]
@Yenthe666 Hate to take you away but do you have any thoughts on this, sir?

**Comment by Yenthe666** [comment]
Well I like the idea of adding the PyPy support in and bumping gevent up too.
The thing is that I'm not allowed to decide on such topics so all I can do for now is ping @mart-e and @odony.
If this topic doesn't get a response within a few days just ping me again and I'll see what I can do for you guys.

**Comment by mart-e** [comment]
That kind of decision would be @antonylesuisse's call.

**Comment by antonylesuisse** [comment]
ok to accept non intrusive patches to make odoo run under pypy, such as #7839 however it's low priority.

**Comment by bealdav** [comment]
In v11:

```
gevent==1.1.2
ofxparse==0.16
vobject==0.9.3
```

Is it a topic that'll be considered after v12 ?

Thanks
