### ISSUE TITLE
Odoo Help Forum: Force english language if the forum rules demand english language only

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12235]
More and more people post in different languages in the Odoo help forum. I suppose this is also propagated by the fact that the Odoo forum website and related content such as the forum guidelines etc. itself is displayed in different languages. 

As a first step: Please add an additional remark when posting a new question about using english language only.
Otherwise moderators are forced to strictly close all posts in non-english language which is an annoying and unnecessary task.

**Comment by Yenthe666** [comment]
Hey @treviser,

I agree that this is bit of an issue at the moment, I've seen a lot of new help topics in other languages these days.. 
@mart-e can you throw in your opinion on this one? It is indeed a bit annoying. People don't seem to read the rules. :+1:

**Comment by treviser** [comment]
This leads to a suggestion for improvement of website_forum: It should be possible to define a default language for a particular forum independent of other languages settings for the rest of the website.

**Comment by JKE-be** [comment]
Hello,
I'm agree that 'additional remark when posting a new question about using English language only.' can help to avoid this behavior.
Moderator should not accept post in moderation_queue that are in another lang that English. But it's a fact, that if the user have karma, he bypass the moderation_queue.
