### ISSUE TITLE
HttpCase test cursor is not shared with the created session's test

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12237]
Impacted versions: 9.0

Steps to reproduce:

Create this test for `auth_signup` module:

```
from lxml.html import document_fromstring
from openerp.tests.common import HttpCase
class UICase(HttpCase):
    def setUp(self):
        super(UICase, self).setUp()
        self.icp = self.env["ir.config_parameter"]
        self.icp.set_param("auth_signup.allow_uninvited", "True")

    def tests_url_open(self):
        doc = document_fromstring(self.url_open("/web/signup").read())
        self.assertEqual(
            len(doc.xpath("//title[contains('404 Not Found')]")), 0)
 ```

Run the test.

Current behavior: Test fails because the cursor is not the same in the running test and in the request that gets opened with `self.url_open`, and thus `auth_signup.allow_uninvited` still remains `False` and the `/web/signup` controller raises a 404 error.

Expected behavior: The cursor for a test case should be the same, no matter if it opens sub-requests. It could be appended to the underlying `self.session`.

Workaround: commit at `setUp`, and manually undo your changes and commit at `tearDown`. But this is ugly and error-prone: **tests should never commit.**

**Comment by mart-e** [comment]
Well the ugly and error-prone is what was done at c64a762d06de76ee47356922479eea70694712d9 in auth_signup.
@KangOl an idea to avoid it?

**Comment by Yajo** [comment]
FTR I had to remove tests in https://github.com/OCA/server-tools/issues/442 because of this.

**Comment by sle-odoo** [comment]
Hello,
I did not carefully read your test but you can see [here](https://github.com/odoo/odoo/blob/9.0/openerp/addons/test_assetsbundle/tests/test_assetsbundle.py#L289) that i made an httpcase sharing its cursor with the one in the phantomjs session.

Hope it helps,
Regards

**Comment by Yajo** [comment]
Can the problem be that I'm using self.env while you use self.registry?

**Comment by sle-odoo** [comment]
No, the problem is that in the HttpCase class, self.cr is a normal cursor (that is rollbacked at the end of the test) and that phantomjs tests are using another type of cursor, a TestCursor that keeps a transaction open during all the test but simulate the commit/rollback via savepoint. This cursor also serialises concurrent requests with the help of an rlock. This cursor is activated when you execute `enter_test_mode` on a registry object, which is done in the setUp of the HttpCase, however this setUp first calls the setUp of TransactionCase that set self.cr to an instance of a normal cursor.

```
In [1]: self.cr
Out[1]: <openerp.sql_db.Cursor at 0x111304b90>

In [2]: self.registry.cursor()
Out[2]: <openerp.sql_db.TestCursor at 0x1113b7450>
```

That's why i use a test cursors to create an ir.ui.view in my test, this way it's visible to the phantomjs test. So you should ask for a testCursor and then use it to set your ir config parameters and it'll work fine.

**Comment by Yajo** [comment]
Sorry, but could you please provide an example of how to make https://github.com/odoo/odoo/issues/12237#issue-157614789 work? I don't fully understand what you are saying... :confused:

**Comment by sle-odoo** [comment]
Just don't use self.cr or self.env if you want your modifications to be visibles for phantomjs, [ask for a new cursor](https://github.com/odoo/odoo/blob/9.0/openerp/addons/test_assetsbundle/tests/test_assetsbundle.py#L292). The new cursor will be a TestCursor, just as the ones created for the requests in the phatomjs test.

**Comment by Yajo** [comment]
OK, clear, thanks!

However, one more question: wouldn't it make sense to use such cursor by default on `self.env`?

**Comment by Yajo** [comment]
Sorry, there's still one more thing I don't understand. Isn't it exactly what Odoo does by default with [the `self.cursor` method](https://github.com/odoo/odoo/blob/14fdabb4bc478f2b96f478dfe287f5cb916f938f/openerp/tests/common.py#L90-L91) and when creating [`self.cr`](https://github.com/odoo/odoo/blob/14fdabb4bc478f2b96f478dfe287f5cb916f938f/openerp/tests/common.py#L148) and [`self.env`](https://github.com/odoo/odoo/blob/14fdabb4bc478f2b96f478dfe287f5cb916f938f/openerp/tests/common.py#L151) :confused: :question:

**Comment by Yajo** [comment]
Please reopen this, today I tried your suggestion and it results on phantomjs not seeing the record, no way to use environments, and created/modified records are persisted after the tour fails.

**Comment by sle-odoo** [comment]
i can have a look at your updated test case if you want

**Comment by Yajo** [comment]
Thanks, it's in https://github.com/OCA/website/pull/211/commits/8a85e3e737ddc999c1d090cb9ac22f612a86fbaa (remember you'll have to merge https://github.com/OCA/website/pull/202 too to make this module work).

Since I cannot make it work after trying some workarounds, I changed it to what I think it *should* be if this bug never existed. Please give me advice, thanks.

**Comment by sle-odoo** [comment]
well i merged PR 202 and 211 and i only got the commit you're pointing out, adding ```<script src="/website_portal_purchase_product/static/src/js/tour.js"/>``` to website_portal_purchase_product/views/assets.xml but this file (tour.js) is not in the repository and you have no tests folder nor any python test at all in website_portal_purchase_product. please provide clearer steps or push the needed files.

**Comment by Yajo** [comment]
It seems I forgot to commit that, please update your branches, it's in https://github.com/OCA/website/pull/211/commits/175cffaacc5fd1d7a392451a2bea2e176b310375 now.

**Comment by sle-odoo** [comment]
ok, i don't have too much time at the moment to fix your test but i stumbled over it again and here's the idea

```
    def setUp(self):
        super(TestUi, self).setUp()
        test_cursor = self.registry.cursor()
        test_cursor_env = Environment(test_cursor, self.uid, {})
        # do your stuff with test_cursor_env
        test_cursor.commit()
        test_cursor.close()

```

**Comment by Yajo** [comment]
Today I was able to check that your solution works fine, @sle-odoo. You can even simplify it further by [using the cursor as a context manager and calling your previous env to create the new one](https://github.com/OCA/website/pull/266/commits/81458b83aeaf2fc7552793c7f11319f8feccae6b#diff-a831253534f1fa77b482fd96b925ce98R12):

```
class UICase(HttpCase):
    def setUp(self):
        super(UICase, self).setUp()
        with self.registry.cursor() as test_cursor:
            env = self.env(test_cursor)
            # Do things here with `env`, they'll get committed later
```

**Comment by Yajo** [comment]
It turns out [the fix is 1 line long](https://github.com/odoo/odoo/pull/13890/commits/ed5ad0fd0fd4a19118639c11faa90a57a571bf0a#diff-c55d7a278cc5bb578427c134c8a0e161R260).
