### ISSUE TITLE
Odoo8 Shop Email sending when confirm order , not working.

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#12234]
Hi, I try to send an email to the user when he order a product from the odoo shop. The Email is working normal with smtp, but when a user buy a product, he doesn't get an email.
I try to do this with automatic workflows, but then the user get4 emails after ordered an product.

How can I fix that? and why is there not a standard way to send a normal email when a user buy a product in the website shop.

An oder poblem is the email format in the email templates:

How Can I make here an if statement:

Sehr  geehrter ${object.partner_id.title.name} ${object.partner_id.name},

So that when the partner_id.title is == Herr it should take this:

Sehr geehrter Herr

and when it's Frau, this:

Sehr geehrte Frau

Is this possible???

**Comment by JKE-be** [comment]
Hello @diezcode , 
It is not an issue, please use the forum for this kind of question... (And yes it should be possible to do it...)
https://www.odoo.com/forum/help-1
