### ISSUE TITLE
[9.0] Qweb report not rendering with multiple barcodes in threaded mode

### ISSUE THREAD

**Issue by joshbindels** [odoo/odoo#12236]
When printing a report with multiple barcodes Odoo freezes seemingly on a GET call for assets, but this varies 

Qweb used for the barcodes is:
`    <img t-att-src="'/report/barcode?type=Code128&amp;value=%s&amp;width=325&amp;height=130&amp;humanreadable=1'%(barcode_data)" />`

The /report/barcode  route function is called twice back to back (before any return value).

this function is called once per barcode, but never gets a return value
`
barcode = request.registry['report'].barcode(type, value, width=wi|~                                                                                                         
dth, height=height, humanreadable=humanreadable)  
`

even though the barcode function does return a barcode (eventually)
`
 barcode = createBarcodeDrawing(
       barcode_type, value=value, format='png', width=width, height=height, humanReadable=humanreadable)
`

**Comment by Yenthe666** [comment]
@Gorash and @sle-odoo could you guys have a look at this one?

**Comment by sle-odoo** [comment]
It looks like you are running your Odoo in worker mode, is this the case?

**Comment by joshbindels** [comment]
I am running Odoo with 0 workers

**Comment by sle-odoo** [comment]
Well i can't reproduce this at all...
Could you detail your setup (OS, are you using a reverse proxy, ...)

**Comment by joshbindels** [comment]
I'm running on Ubunut 14.04 

Here's a copy of my config file: [git.txt](https://github.com/odoo/odoo/files/297237/git.txt)

Here's a copy of the report I've been testing it with:

```
<!-- sale.order report -->
<t t-call="report.html_container">
<t t-foreach="docs" t-as="o">
<div class="page">
    <div class="row">
        <img t-att-src="'/report/barcode?  type=Code128&amp;value=%s&amp;width=325&amp;height=130&amp;humanreadable=1'%(o.name)" />
    </div>
    <div class="row">
        <img t-att-src="'/report/barcode?type=Code128&amp;value=%s&amp;width=325&amp;height=130&amp;humanreadable=1'%(o.picking_policy)" />
    </div>
</div>
</t>
</t>
```

Once in a while the issue won't occur, (when the stars align and the first barcode is returned before the second one is called). 
Also the issue doesn't seem to occur when you're creating the same barcode twice, (used o.name twice in report above to test)

**Comment by sle-odoo** [comment]
Ok i reproduced it. I'll investigate.
FYI i made the test with 4 barcodes and with 3 workers it's not locked, so you can start your Odoo in workers mode to workaround this issue at the moment.

**Comment by sle-odoo** [comment]
@joshbindels could you apply the patch and see if it fixes the issue? It seems to be the only workaround.

**Comment by joshbindels** [comment]
This works!

Tested it with 4 different barcodes on a report after restarting my odoo server multiple times

**Comment by sle-odoo** [comment]
@joshbindels we made a better patch (without explicit lock) at rev 6aba3a6f94d99d0e00791ca3a3d9deb44e69fd1d, can you please try it and see if it fixes your issue too?

Also, is it possible for you not to restart your server for a few hours and see if it's still working? We don't know when reportlab decide to invalid its fonts cache and it's possible that the initial issue occurs again when it does. However, so far so good during my tests.
