### ISSUE TITLE
[WISHLIST] Make date group by formats extendable/overridable

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#12245]
Could you guys please make it easier to extend/override the [date formats](https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L1927) for "new" group by date feature?

I don't see problems with extending the [intervals](https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L1943), too.

**Comment by mart-e** [comment]
Closing as in favour of #11936 instead.
Allow to override the formats is quite technical and not enough as you will probably need to change `_read_group_format_result` (so you can already override `_read_group_process_groupby`).

**Comment by intero-chz** [comment]
I don't see why `_read_group_format_result` has to be changed, too. I just want an easy possibility to change date formats and add some new intervals. Perhaps it is already possible by overriding `_read_group_process_groupby`, but i think thats "too much" for just adding intervals or changing date formats. Where is the problem to instead of assigning a dictionary just to get the dictionary from overridable methods?

**Comment by mart-e** [comment]
We have already a lot of hook method to allow to extend and change the behaviour, it usually adds little interest for a few people while making it harder to maintain and debug. The method `_read_group_process_groupby` is not very long here so it could be overriden in your custom module.
My point with `_read_group_format_result` was if you try something like grouping by hour, you will see that you need to change that one too.

**Comment by intero-chz** [comment]
OK, I'm fine with that.
