### ISSUE TITLE
[9.0c][9.0e] [BUG] all stages for new job position not displayed

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#12246]
Impacted versions:9 e

Steps to reproduce:go to recruitment, create a new job offer, click on applications
![screenshot at may 31 15-41-21](https://cloud.githubusercontent.com/assets/12964307/15676755/cf143748-2747-11e6-90a9-4786b4d307ed.png)

Current behavior: the different stages does not appear for new created job position, but appear for the others

Expected behavior:it should display all the different stages as it does for the other 

Video/Screenshot link (optional):
![allstages](https://cloud.githubusercontent.com/assets/12964307/15677756/f685d058-274b-11e6-8d53-9e93baacf798.png)

**Comment by JKE-be** [comment]
Hello @bene1505 
Thank you for the reporting.

In V9, the stage are not shared by default.
So you need to specify for the new job positions, the stages available.
(in V10, it has been updated to be common by default)

The only problem, ... the field ("stage_ids") is not displayed in form view :/
I just add this field in v9, but it will require to make an update of your module to have the new view.
Else you can update yourself the view, respectively to my commit.

odoo/odoo@d1073f8
