### ISSUE TITLE
[8.0] functions fields in tests are not computed with new api

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#12254]
After this [commit](https://github.com/odoo/odoo/commit/6f29bfc181d23d70d29776d96b4318e9ee2c93a9) some of our tests that are validating the distinct values of the functions fields into process are failing

Impacted versions:
* 8.0

Steps to reproduce:
* Create functions field with new api like this [invioced2](https://github.com/odoo/odoo/blob/8.0/addons/sale/sale.py#L107)
* Create tests to validate value for this field before and after the pay invoice

Current behavior:
* The function fields only is calculated the first time, the second time is not calculated

Expected behavior:
* The field function must be calculated in all test

Video/Screenshot link (optional):
https://youtu.be/KgHeE3rVXs8

I create this module to test,
https://github.com/JulioSerna/module_test

**Comment by rim-odoo** [comment]
@rco-odoo Can you have a look at this issue?

**Comment by nim-odoo** [comment]
Hello,

Your field is not correctly defined. For a computed field, you should define the dependencies thanks to `@api.depends`. In your case, this should probably be the solution:
```python
@api.depends('state', 'invoice_ids')
def _invoiced2(self):
....
```

Please read https://www.odoo.com/documentation/9.0/reference/orm.html#computed-fields

Regards,
