### ISSUE TITLE
Website Language Translate

### ISSUE THREAD

**Issue by mayankvara** [odoo/odoo#12251]
Impacted versions: `8.0`, `9.0`, `master`

Steps to reproduce: 
- Load Arabic language in website
- Enable Product's Attribute Filter in which we got Color filters

Current behavior:
- In English language the color property is proper - Black & White
- But in other language it also translate its color property.

Expected behavior:
- In other language (for ex. here Arabic) It should not translate its color property. Its should be Black & White.
- CSS Style is not translatable.

Video/Screenshot link (optional):
- Behavior in English Language...
![screenshot from 2016-06-01 11 42 04](https://cloud.githubusercontent.com/assets/12167731/15700267/a1ba4e8c-27f0-11e6-83a6-624a5fd30b6e.png)

- Behavior in Arabic Language...
![screenshot from 2016-06-01 11 47 20](https://cloud.githubusercontent.com/assets/12167731/15700270/a8e30a00-27f0-11e6-8289-20af0aa3b2e3.png)

ping @mart-e @bst-odoo

**Comment by Yenthe666** [comment]
@JKE-be since you're all about the website, this might be something for you.

**Comment by JKE-be** [comment]
Fixed in odoo/odoo@b49818e1ee03205cbef1cc70c21c424ca1a9b436

**Comment by usama255** [comment]
Thanks for sharing such a beautiful information with us please keep it up!
<a href="https://www.nordtranslation.com/">English to Icelandic Translation</a>
