### ISSUE TITLE
[8.0] Uncorrect payment line name in invoice form view

### ISSUE THREAD

**Issue by n1b0r** [odoo/odoo#12252]
Impacted versions:
- 8.0

Steps to reproduce:
- go to runbot 8.0 odoo instance
- validate a draft invoice using **Validate** button
- register a full payment using **Register Payment** button
- go to "Payments" tab in invoice form

Current behavior:
The related payment line is named "/"

Expected behavior:
The related payment line is named with the invoice number

Other information:

In odoo 7.0 the payment line is correctly named with the related invoice number.
Whereas in odoo 8.0 the payment line is always named "/".

The `account.move.line` instance related to the payment is created by module `account_voucher` : [here](https://github.com/odoo/odoo/blob/8.0/addons/account_voucher/account_voucher.py#L1228)

The code looks good : 

```
    'name': line.name or '/',
```

where line is a account.voucher.line instance

The account voucher lines are created during **Register Payment** wizard using the `recompute_voucher_lines()` method [here](https://github.com/odoo/odoo/blob/8.0/addons/account_voucher/account_voucher.py#L785)

After some debugging, I found that `recompute_voucher_lines()` correctly returns the right name (invoice number) for the voucher lines. But the name is never forwarded to the `create()` method of the `account_voucher_line` model.

Hence, the `account.move.line` instance has the wrong name.

Can someone confirm me this is a bug, and provide me tips to correct it ?

Best regards,
nib

**Comment by Yenthe666** [comment]
Hi @n1b0r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
