### ISSUE TITLE
[16.0][CE/EE] Cannot regenerate work entries

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#122591]
Impacted versions: 16.0 CE/EE (reproduced on Runbot)

Steps to reproduce:
1. Open the Employee form view, click the button Work Entries
2. Click the button REGENERATE WORK ENTRIES

Current behavior:
Error popup 

```
UncaughtPromiseError > InvalidButtonParamsError
Uncaught Promise > Missing type for doActionButton request
InvalidButtonParamsError: Missing type for doActionButton request
    at Object.doActionButton (https://40775072-16-0-all.runbot136.odoo.com/web/assets/1855-620e7fa/web.assets_backend.min.js:5860:508)
    at execute (https://40775072-16-0-all.runbot136.odoo.com/web/assets/1855-620e7fa/web.assets_backend.min.js:5521:329)
```

Expected behavior:

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/7898318/50508169-9cc5-45b1-8624-2b5433116022)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @anhvu-sg ,
i tried to reproduce the same with provided steps in the runbot and seems the trace back is not coming, can you confirm the same once again and see if it still happens.
thanks

**Comment by anhvu-sg** [comment]
hi @niyasraphy , it's Ok now, thank you

**Comment by niyasraphy** [comment]
thanks for confirming @anhvu-sg ,
so i believe you can close the ticket now.
thanks
