### ISSUE TITLE
OpenERP Warning: Erreur 131

### ISSUE THREAD

**Issue by krmagnaye** [odoo/odoo#12266]
Impacted versions: version 7

Steps to reproduce: Create patients information

Current behavior: cannot open the patients record recently even if i didnt make any changes. Its not working in webpage (any browser) but its working properly to localhost 

Expected behavior: View the list of the patients record

Video/Screenshot link (optional):

![erreur131](https://cloud.githubusercontent.com/assets/19465728/15741894/53b2f80c-28ee-11e6-9b2f-8da706ca7027.JPG)

**Comment by Yenthe666** [comment]
Hi @krmagnaye,

What do you mean with patient? There is no such thing as patient in Odoo.
Is this custom development or? We'll need more info and it has to be reproducable on a runbot (v7).

**Comment by krmagnaye** [comment]
Yes this is a custom development. I just wanna know why I get that error even if i didnt change anything. its working before and then after an hour there's an error already. Only happened in webpage but in using the localhost its working properly

**Comment by Yenthe666** [comment]
Hi @krmagnaye,

The Github issues for Odoo are limited to the default Odoo code, so custom development is not accepted as a bug.
I'd suggest you to post a new topic on the official Odoo help forums (help.odoo.com) and add in the code so users can have a look at it. You should get help quite fast there!

Regards,
Yenthe
