### ISSUE TITLE
Error auth Microsoft Outlook Incoming IMAP

### ISSUE THREAD

**Issue by rigo1985** [odoo/odoo#122625]
Impacted versions: 15.0

Steps to reproduce:
Go to Settings/Emails/Incoming Mail Server
Next auth with Outlook and try button "Connect your Outlook account"

Error in log:

" .... AttributeError: 'fetchmail.server' object has no attribute 'smtp_user' ... "

this error was introduce in May 20 ( https://github.com/odoo/odoo/commit/45e4be17f3f73d6e4122a43383afd774f4cbc926 )

Current behavior:
@jorv-odoo Could you tell me if I need to update any module or dependency?

Expected behavior:
.

Video/Screenshot link (optional):
Try:
![image](https://github.com/odoo/odoo/assets/10016548/dcd84f8e-0898-48b0-8fda-f9b86943171e)

Error:
![image](https://github.com/odoo/odoo/assets/10016548/fd3e486d-03a7-444e-b092-8721dc32bd09)

Support ticket number submitted via odoo.com/help (optional):

**Comment by jorv-odoo** [comment]
We are working on a fix in this [PR](https://github.com/odoo/odoo/pull/122222). Once all forward ports are resolved, it will be merged.
