### ISSUE TITLE
[8.0][BUG]Multiple document attached for the same report

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#12272]
Impacted versions: 8.0

Steps to reproduce: 
1. Create a fresh database with sale and document modules installed
2. Change the "save as attachment prefix" of the sale order report to have something in it:
![image](https://cloud.githubusercontent.com/assets/7678583/15748513/83b39d90-28df-11e6-9409-32e17e32fd13.png)
3. Create a QWeb heriting the original sale order qweb to add a page after the sale order page:
![image](https://cloud.githubusercontent.com/assets/7678583/15748788/7561df94-28e0-11e6-9ca5-1dc0eebe72e3.png)
4. Create a quotation and print it
![image](https://cloud.githubusercontent.com/assets/7678583/15749105/88d36fb0-28e1-11e6-9b51-e619ec2b20a7.png)

Current behavior:
You have 2 attached documents
![image](https://cloud.githubusercontent.com/assets/7678583/15749117/9c526c4e-28e1-11e6-85b9-a1e4a342214a.png)
because it splits the document depending on the class "page"

Expected behavior:
I should have only one attached document

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hello,
You should not use the "page" class because it is used internally to split the pages. What you want to do is add a page-break-after css rule to force a page-break.
