### ISSUE TITLE
missing modules web.planner.com

### ISSUE THREAD

**Issue by KyleRobins** [odoo/odoo#122793]
Impacted versions: 16

Steps to reproduce: install version 16 of odoo then activate the module hr_leave_request_aliasing

Current behavior: the page loads after login and maintains a blank page

Expected behavior: js files not loading 

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/61718572/3a92859b-22f6-40ab-b48a-0651cb76707e)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @KyleRobins ,
as hr_leave_request_aliasing is a third party app, you have to report the issue to the author through their support channel.
feel free to close the ticket, as this is not issue inside the odoo core.
thanks
