### ISSUE TITLE
[9.0] Wrong plural form of "active users" in Vietnamese language

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#12286]
**Steps to reproduce**:
Navigate to Settings and look at Active User panel:

1. When Only one user:
English string: "1 Active User"
Vietnamese string: "1 Người dùng tích cực"

2. When more than one user:
English string: "1 active user**s**"
Vietnamese string: "1 Người dùng tích cực**s**"

**Expected behavior** when there are 2 users or more:
- Vietnamese string: "1 Người dùng tích cực". There is no difference between the single and the plural form of a word in Vietnamese language

**Comment by Yenthe666** [comment]
Hi @davidtranhp,

Thanks a lot for your report!
Translations do not fall under Odoo issues though, these should be made on Transifex, the online translation platform used for Odoo. You can find all the information regarding this on the wiki (https://github.com/odoo/odoo/wiki/Translations)
When you've translated this on Transifex it will be available in the official Odoo within 7 days.

Regards,
Yenthe

**Comment by davidtranhp** [comment]
This can not be solved by translation. It's coding problem. Here is the orginal code in addons/web_settings_dashboard/static/src/xml/dashboard.xml
`<t t-if="active_users">
                    <t t-esc="active_users"></t> Active User<t t-if="active_users > 1">s</t>
                </t>`
This does not respect the nature of language. In English, plural form of 'Active User' is 'Active Users'. But in Vietnamese, it must not add **s** to the plural form.
The above code should be revised as below:
`<t t-if="active_users">
                    <t t-esc="active_users and active_users > 1"></t> Active Users</t>
                    <t t-esc="active_users and not active_users > 1"></t> Active User</t>
                </t>`
So, there should be two strings in the translation files.
