### ISSUE TITLE
default argument missing 

### ISSUE THREAD

**Issue by SarathkumarJ** [odoo/odoo#12280]
Impacted versions: Present revision in git 

Steps to reproduce: creating   PO the  draft purchase lines ,the newly created PO's won't have the requestion reference  

Current behavior: As  explained above 

Expected behavior: Newly created  PO's will have requisition reference set properly 

The reason for this overriding  of copy method is not done properly  Screenshot Attached 
![odoo 2016-06-03 15-42-41](https://cloud.githubusercontent.com/assets/10898379/15775874/fb167732-29a1-11e6-8db3-518707480334.png)

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
Thanks for the report, although a link to the source code (click on the line number in github) or even just the name of the file is really more convenient than a screenshot.
