### ISSUE TITLE
[9] Please add link from /web/database/backup page to other pages.

### ISSUE THREAD

**Issue by medined** [odoo/odoo#12287]
Impacted versions:

9

Steps to reproduce:

Visit /web/database/backup

Current behavior:

There are no links to provide options

Expected behavior:

Provide link back to login page. Provide links to Help pages.

Video/Screenshot link (optional):

<img width="302" alt="database-management" src="https://cloud.githubusercontent.com/assets/43589/15806352/73b2b430-2b0f-11e6-9624-fa9852cb6bab.PNG">

**Comment by Yenthe666** [comment]
Thank you for your report @medined.
This sounds like a wishlist item to me. @mart-e what do you think about this?

**Comment by mart-e** [comment]
Hello,

To go back on the login page, just click on the database you want to access, I am not sure what you want more (keep in mind that you can get many databases).
