### ISSUE TITLE
[8.0]  stock barcode interface could not find picking with number contains ' \'

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#12291]
Impacted versions:

odoo 8.0

Steps to reproduce:

setup the sequence of picking type contain '\' in prefix, like this 'WH\INT\ '

Current behavior:

input int\00037  in search box of barcode interface, it can not find the picking, 
if input 00037, it can find it.

Expected behavior:

need to search picking use barcode that contains any code.

Video/Screenshot link (optional):

![animation](https://cloud.githubusercontent.com/assets/1404460/15813453/bbb81aee-2bf1-11e6-82a5-de9f4482fbba.gif)

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look at this one?

**Comment by JKE-be** [comment]
@jco-odoo should help :8ball:  https://github.com/odoo/odoo/commit/599355e#diff-bfe8870b62ee8d50866944d2dd8a4666R459

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
