### ISSUE TITLE
img tag replaced with href making email servers block the image

### ISSUE THREAD

**Issue by Gorkygd** [odoo/odoo#12297]
**Impacted versions:**
9.0
**Steps to reproduce:**
Attach an image to an email and try to send it.
**Current behavior:**
The image is not shown to the client. Tested with gmail.
**Expected behavior:**
The image should be shown
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Need more details about step to reproduce.
From which screen, which method...

I have just tested by:
 - partner
 - send a message
 - use composer
 - add image

and it works...

**Comment by Gorkygd** [comment]
Edit the Sales Order - Send by Email (Portal) template. Upload a png image from your local machine. Mine is 670x280 pixels but I do not think it changes anything. Attach it to your template.

Go to Sales -> Quotations, open a quotation and click Send by email.

Send the email as it it on a gmail account.

On the gmail account the image does not appear.

**Comment by JKE-be** [comment]
Can you post the source of email.
or can you sent your email (directly form odoo) to jke@odoo.com ?
What is the link in url ... What is your base url ? Is is right ? You need to use a public url...

**Comment by Gorkygd** [comment]
The src attribute of the img tag had the wrong host address. I fixed that by changing the url under Settings -> System parameters

**Comment by JKE-be** [comment]
Thanks for the feedback...

That confirm my previous comment ``` You need to use a public url... ``` :8ball:
