### ISSUE TITLE
Configuration – User Access Constraint Mismatch

### ISSUE THREAD

**Issue by enzoberger** [odoo/odoo#123]
There are constraints between the Configuration of Sales, Purchase, Warehouse, ... and the Access Rights of a user. But for some reasons this constraints behave very strange and illogical.
For example:
•	I have all the Access Rights for the Admin activated
•	I go to Configuration, Sales
•	I activate "Generate invoices based on the sales order lines" and save.
Now the system deactivates following Access Rights for the Admin:
•	Sales Pricelists
•	Manage Multiple Units of Measure
•	Discount on lines

The same happen when I activate/deactivate other features!
So let me get that straight.
•	If I activate features, I expect that hidden Access Right would appear. But what happens is that I lose some of my Access Rights.
•	If I deactivate features, I expect that the Access Right belonging to that feature would be inactive or hidden!
The current system behavior is very strange. That confuses customer and potential customer and it makes the customizing process more time consuming!
My system Setting: Version 7.0-20130226-002110 with sample data.

**Comment by Yenthe666** [comment]
Dear @enzoberger,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
