### ISSUE TITLE
Attributes in links not rendered in mass mailing

### ISSUE THREAD

**Issue by florimond83** [odoo/odoo#12304]
Impacted versions:9.0

Steps to reproduce: Within a mail template in mass mailing, insert an object attribute such as a user website:
 `<a href="${object.website}">Your website</a>`

Current behavior: When sent, Odoo won't transform the objet and the link will transform to 
http://www.mywebiste.com/$%7Bobject.website%7D?&

Expected behavior: Odoo should generate the given website set in the user's data.

**Comment by Yenthe666** [comment]
Thanks for your report @florimond83. I'm not exactly sure what you try to say with the problem though. Could you give a bit more details please? What is wrong with the URL?

**Comment by florimond83** [comment]
Hi @Yenthe666, 
I've got a list of contacts (partners as you call them). 
I'm using mass mailing to send them information in which I use standard attributes from odoo:
`Hi ${object.name}, your account is still active, please go to <a href="${object.website}">your website</a> to complete your information`

The issue is that when it is sent, ${object.name} shows up perfectly within the text.
But ${object.website} is not converted by odoo (within the link tracker I assume).

The result mail will give me:
Hi John Doe, your account is still active, please go to your website.
The link given for 'your website' being:
http://odoo.example.com/r/hmM/m/6437

Following that link you arrive on  http://odoo.example.com/$%7Bobject.website_url%7D?&
Resulting to a 404 error.

**Comment by florimond83** [comment]
FYI, just in case I have tried to escape as described in some thread, the issue stays:
Within the template:
```
  <a href="\${object.website}">your website</a><br>
  <a href="\${object.website}\">your website</a><br>
  <a href="\${object.website}"\>your website</a><br>
```
Results with:
http://odoo.example.com/%5C$%7Bobject.website%7D?&
http://odoo.example.com/%5C$%7Bobject.website%7D%5C?&
http://odoo.example.com/%5C$%7Bobject.website%7D?&

**Comment by pedrobaeza** [comment]
@JKE-be did you check this one?

**Comment by JKE-be** [comment]
Still reproducible.
I have tagged the right team.

**Comment by pedrobaeza** [comment]
OK, thanks.

**Comment by popama** [comment]
Hello,

I fixed this situation by creating a new class that inherits the "link.tracker" and in the method "convert_links", I added a new condition which looks for "${" in "long_url" and if it finds it then skips the code that replace the "long_url" with "shorten_url".

The resulted code:
```
class link_tracker(models.Model):
    _inherit = "link.tracker"

    @api.model
    def convert_links(self, html, vals, blacklist=None):
        for match in re.findall(URL_REGEX, html):

            short_schema = self.env['ir.config_parameter'].get_param('web.base.url') + '/r/'

            href = match[0]
            long_url = match[1]

            vals['url'] = unescape(long_url)
            if not '${' in long_url:
                if not blacklist or not [s for s in blacklist if s in long_url] and not long_url.startswith(short_schema):
                    link = self.create(vals)
                    shorten_url = self.browse(link.id)[0].short_url
                    if shorten_url:
                        new_href = href.replace(long_url, shorten_url)
                        html = html.replace(href, new_href)

        return html
```

**Comment by Yenthe666** [comment]
Hi @florimond83,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
