### ISSUE TITLE
Design broken by recent commits

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#12308]
Impacted versions:

9.0

Steps to reproduce:

Navigate to any list view / form view

Current behavior:

Fonts enlarged and design disrupted

Expected behavior:

Video/Screenshot link (optional):

Screenshots taken from runbot latest build at the time of posting

![Odoo Bug](http://i.imgur.com/obZh9di.png)

![Odoo Bug 2](http://i.imgur.com/F3A1krn.png)

**Comment by Yenthe666** [comment]
Hi @PCatinean,

Thank you for your report. There is another bug report for this issue (https://github.com/odoo/odoo/issues/12312) which contains more information.
I'll keep them both open for now but keep a look on the other one, since this will probably be used to comment on etc.

**Comment by JKE-be** [comment]
#12312 has been fixed / closed
