### ISSUE TITLE
JPY: Can Not Edit Decimal Places

### ISSUE THREAD

**Issue by poing** [odoo/odoo#12311]
Impacted versions: 9

Steps to reproduce: 
Install Japanese Currency
Accounting/Settings/Currency

Current behavior: Decimal Places = 2

Expected behavior: Decimal Places Should be editable

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @poing,

You can configure the decimal places under `Settings > Technical > Database Structure > Decimal Acurrancy` (you need to have developer mode enabled), they are splitted up per part in the application there:
![image](https://cloud.githubusercontent.com/assets/6352350/15847591/7e196792-2c87-11e6-8fc4-171467e5065f.png)
Is this what you're looking for?

**Comment by poing** [comment]
No, I want to change the currency specific setting.
JPY = ¥10,000
USD = $1,000.00


![Company Currency](https://cloud.githubusercontent.com/assets/11417007/15849968/44ef141e-2cd0-11e6-885e-be5a11409b4a.png)
![Account Currency](https://cloud.githubusercontent.com/assets/11417007/15849969/44f21fb0-2cd0-11e6-9b9c-103d5d5e556e.png)

**Comment by poing** [comment]
<img width="1216" alt="odoo01" src="https://cloud.githubusercontent.com/assets/11417007/15850179/ab5dc960-2cd1-11e6-9079-3a286d6380e2.png">
<img width="1266" alt="odoo02" src="https://cloud.githubusercontent.com/assets/11417007/15850191/b8b5cb58-2cd1-11e6-80d2-4dbe4a71acb0.png">

**Comment by Yenthe666** [comment]
Hi @poing,

This is a calculated field with the following formula behind it: `int(math.ceil(math.log10(1/currency.rounding)))` as you can see here: https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_currency.py#L51
Depending on the rounding on the settings (that I've previously explained) it should also look at the rounding on the currency, based on the formula.

**Comment by poing** [comment]
Ah, I see the problem.  The field name was changed to something misleading.  In version 8, it was called 'Computational Accuracy'    I suggest you change it back!

<img width="909" alt="odoo3" src="https://cloud.githubusercontent.com/assets/11417007/15851553/34fa3ac2-2cd8-11e6-8bc2-3403eaa03aa3.png">

The expected behavior of a field named 'decimal places' would control the decimal places shown for the specified currency.  Just like the symbol and symbol position settings, decimal places SHOULD control how many decimal places are shown for a currency.

Because some currencies have cent values, like USD:  $20.75
Others do not, like JPY: ¥2075

Doing business in both USD and JPY, the system wide decimal setting forces one to look wrong.

**Comment by Yenthe666** [comment]
Hmm it might be a bit confusing yes. @mart-e could you give your feedback on this? Since it concerns usability / translations. Is this something we should change back in V10?
@poing is it fine to close this issue since it is answered now?

**Comment by poing** [comment]
Yes, you can close it.  Thanks!

**Comment by elicoidal** [comment]
@poing you might want to try this: https://github.com/OCA/account-financial-tools/pull/337

**Comment by mart-e** [comment]
Hmm was the 'Computational Accuracy' accuracy doing anything back them? It is not the same as 'Decimal Places' as in the above screenshot you see it's 4 while it should be 2 with a rouding of 0.01.

As said Yenthe, it's computed based on the rounding where you can set the precision.

By the way setting the rounding factor is useful to match the coins of a currency, for instance setting 0.05 if you have a 5 cents coin but not a 1 cent.

**Comment by george-mengelberg** [comment]
The v9 implementation of moving the decimal placement to res.currency is an important and welcome move.  Implementing 'Decimal Accuracy' for different models (e.g. Product Price, Account, etc.) was an acceptable short-term design decision, but defining how a currency is displayed/managed should be defined on the currency itself.  This is especially important where multiple currencies are used as you would not want to enforce a JPY currency standard for products listed in a USD-based pricelist.

Decimal handling for currency is the primary issue which has stymied Japanese localization efforts to date.

@poing you need to be in 'debug-mode' to edit the decimal placement for currency.
