### ISSUE TITLE
[8.0] stock barcode interface need to use exists package

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#12313]
Impacted versions:
odoo-8

Steps to reproduce:

Current behavior:

we can create new package in barcode interface, but can not use the existing one.

Expected behavior:

need to use existed package.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look at this one too? I'm not sure if there is a reason why Odoo didn't make this available?

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
