### ISSUE TITLE
[8.0, 9.0C, 9.0E] track_visibility does not respect datetime formats

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12327]
Impacted versions: 8.0, 9.0 community, 9.0 Enterprise

Steps to reproduce:
 1. Go to Calendar > Meetings and open a calendar appointment in the form view.
 2. Change the start date of an appointment. The field has track_visibility set to True so it posts in the chatter.
 3. Look at the chatter:
  ![image](https://cloud.githubusercontent.com/assets/6352350/15886165/b853653c-2d5b-11e6-8ff7-a1f9438aab94.png)

Current behavior:
The `track_visibility` its output is not formatted in the date format from the current user. No matter to which language you switch, it will always print the incorrect date format.

Expected behavior:
Depending on the user his language (and thus datetime format) the correct format should be shown in the chatter.

**Comment by Yenthe666** [comment]
@rco-odoo I'm pinging you since I think this is something for you. Correct me if I'm wrong.
@JKE-be since this is CRM it might belong to you too.

**Comment by Yenthe666** [comment]
The latest commit from @JKE-be handles this perfectly. An example in English:
![image](https://cloud.githubusercontent.com/assets/6352350/15896881/7beb4380-2d92-11e6-996c-8839ad247eac.png)

In Dutch:
![image](https://cloud.githubusercontent.com/assets/6352350/15896949/ba259e52-2d92-11e6-8113-720849dad292.png)

Will be available in Odoo 10.

**Comment by JKE-be** [comment]
:postal_horn:

**Comment by JordiToledo** [comment]
I know it is solved, but has anyone any idea of how to do it in Odoo 8? Without using tack_visibility.
