### ISSUE TITLE
[9.0C & 9.0E] Legally binding fiscal position notes are not printed on reports

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12330]
Impacted versions: 9.0C & 9.0E

Steps to reproduce:
 1. Create a sales order with a fiscal position that is intra-community.
 2. Print the report out.
At this point the report prints to message from the fiscal position, while this is legally binding in Belgium.
It is in the royal decree for Belgium, see http://www.ejustice.just.fgov.be/cgi_loi/change_lg.pl?language=nl&la=N&table_name=wet&cn=2012121903 (or [french version](http://www.ejustice.just.fgov.be/cgi_loi/change_lg.pl?language=fr&la=F&cn=2012121903&table_name=loi) ).
Quoting the most important parts from this text:

>  Art. 22. In artikel 20 van hetzelfde besluit wordt paragraaf 3, vervangen bij het koninklijk besluit van 29 december 1992 en gewijzigd bij het koninklijk besluit van 6 april 2008, vervangen als volgt :
  " § 3. De belastingplichtige die handelingen verricht bedoeld in paragraaf 2, vermeldt op de facturen die hij voor die handelingen uitreikt, noch het tarief, noch het bedrag van de verschuldigde belasting, maar brengt er de vermelding op aan " Btw verlegd ". ".

> Art. 23. In artikel 20bis van hetzelfde besluit wordt paragraaf 3, ingevoegd bij het koninklijk besluit van 30 december 1999 en gewijzigd bij het koninklijk besluit van 6 april 2008, vervangen als volgt :
  " § 3. De belastingplichtige die handelingen verricht bedoeld in paragraaf 2, vermeldt op de facturen die hij voor die handelingen uitreikt, noch het tarief, noch het bedrag van de verschuldigde belasting, maar brengt er de vermelding op aan " Btw verlegd ". ".

> Art. 24. In artikel 20ter van hetzelfde besluit wordt het derde lid, ingevoegd bij het koninklijk besluit van 10 januari 2010, vervangen als volgt :
  " De belastingplichtige die handelingen verricht bedoeld in het tweede lid, vermeldt op de facturen die hij voor die handelingen uitreikt, noch het tarief, noch het bedrag van de verschuldigde belasting, maar brengt er de vermelding op aan " Btw verlegd ". ".

> Wanneer de belasting verschuldigd is door de medecontractant, vervangt de vermelding " Btw verlegd " de vermelding " Belasting te voldoen door de medecontractant " die vroeger in België verplicht was. Wanneer de medecontractant de factuur uitreikt in naam en voor rekening van de leverancier of de dienstverrichter, moet de vermelding " factuur uitgereikt door de afnemer " worden aangebracht.

**Current behaviour:** 
Fiscal positions no longer have the notes field and are no longer printed on the report, while this is a legal requirement in Belgium.

**Expected behaviour:**
Fiscal positions have the field 'note' again in the view, which is also printed on the report when the position is applied on the order..
In Odoo 8 this behaviour was present by default, it has been partially removed in V9.
The field for the note however still exists in the model: https://github.com/odoo/odoo/blob/9.0/addons/l10n_multilang/account.py#L50
The field should be shown in the view for the fiscal position(s) again and should then be printed on the report.
The report implementation (from V8) can be found here: https://github.com/odoo/odoo/blob/4cc01a34e4c56939992ab9ceee21e295d54273e1/addons/l10n_multilang/account.py#L50.

**Comment by Yenthe666** [comment]
@qdp-odoo I've already discussed this with @mart-e and he asked me to ping you. Could you look in to this please?

**Comment by qdp-odoo** [comment]
Hello,

I've fixed that in revision 09bf8b4.

Actually, the note was still printed on invoices, so I just made it visible again in fiscal position form view. Thanks for pointing us that issue.

best regards

**Comment by Yenthe666** [comment]
Thanks a lot, great job! :tada:
