### ISSUE TITLE
[15.0] : Email Marketing app - new links that Odoo creates are not public

### ISSUE THREAD

**Issue by yboujraf** [odoo/odoo#123302]
Impacted versions:
15.0 CE - Email Marketing app, Survey

Steps to reproduce:

When sending links in mass emails (Email Marketing app) or Survey, the new links that Odoo creates are not public.
They only work if the recipient is logged into Odoo.

e.g. if I insert this url: https://erp.me.be, Odoo generates a new non-public
url like this: https://erp.me.be/r/sjI

![image](https://github.com/odoo/odoo/assets/6151258/5838f7bd-021b-4e51-b66c-046e931669ee)

Current behavior:

This is the error message I have when trying to reach the link

![image](https://github.com/odoo/odoo/assets/6151258/a5c873cc-faf5-4d79-8d7d-88337489acf8)

Expected behavior:

Opening the links

We are using NGINX

Best Regards

**Comment by niyasraphy** [comment]
hi @yboujraf ,
it seems it has been resolved in your end from this forum post:  https://www.odoo.com/forum/help-1/odoo15-ce-email-marketing-app-new-links-that-odoo-creates-are-not-public-225541

feel free to close.
thanks
