### ISSUE TITLE
[9.0] Date in mrp production order is not formatted right

### ISSUE THREAD

**Issue by leemannd** [odoo/odoo#12341]
Impacted versions: 
[9.0]
Steps to reproduce: 
Print a "Production Order"

Current behavior:
The date 'Printing date:' is hardcoded. So it cannot fits to the user's formatting.
Second point, this date is not like the "Scheduled Date:"

Expected behavior:
- The date should be formatted following the user's formatting.
- To be more consistent, 'Scheduled Date' & 'Printing date' should be the same type (date or datetime)
- Labels could be more consitent also => 'Printing **D**ate:

**Comment by sle-odoo** [comment]
It seems you are right, [this](https://github.com/odoo/odoo/blob/9.0/addons/mrp/views/report_mrporder.xml#L36) should use the context_timestamp like in the [report_layout](https://github.com/odoo/odoo/blob/9.0/addons/report/views/layouts.xml#L144)

**Comment by sle-odoo** [comment]
Actually my comment is wrong, this will only fix the timestamp and not the format. The only option you have is to hardcode the format in the report with datetime.format. In v10, t-esc will have a format value that will solve this kind of issue more elegantly.

**Comment by leemannd** [comment]
@sle-odoo Hello, so is there no plan to change this behavior in V9 & Enterprise version?

**Comment by leemannd** [comment]
@mart-e Thank you.
