### ISSUE TITLE
UPS OAuth API change breaks delivery provider

### ISSUE THREAD

**Issue by Appel-flappen** [odoo/odoo#123446]
[UPS recently (June 2023) moved their api access to OAuth](https://www.ups.com/upsdeveloperkit?loc=en_GB), and I think this breaks current usage of the UPS shipping provider, there is no way that I can see in the UI to provide the correct OAuth credentials (client ID and client Secret)

From link above:

> If you were sent here by a software provider to obtain an access key, please share the below with them as they will need to update their integration to OAuth auth-code grant type in order to continue to enable their services.
> 
> By June 2023, UPS will no longer issue new API access keys.
> 
> UPS has implemented an OAuth 2.0 security model for all APIs to enhance the overall security for our customers, reduce fraud and provide enhanced API capabilities. OAuth replaces access keys with a client ID and client secret for authentication. New OAuth credentials must be created on the [UPS Developer Portal](http://developer.ups.com/).

**Impacted versions:** 
saas-16+e probably others

**Steps to reproduce:**
1. Add UPS shipping provider
2. put in the details that it is possible to
3. add products to cart and checkout on ecommerce website. 
4. attempt to select UPS shipping method.

**Current behavior:**
"Error: Access License number is invalid for this delivery provider"

**Expected behavior:**
shipping proceeds 
Shipping account work and allows to schedule shipping.

**Comment by vava-odoo** [comment]
Hi @Appel-flappen 
Thanks for pointing that out. The R&D Logistics Team is on it.
Cheers,

**Comment by pdemil** [comment]
Looking forward to use the new UPS OAuth module asap (Odoo 16.0 Enterprise on-premise)

**Comment by goeko** [comment]
This App is broke. "UPS Shipping By Odoo S.A."

"By June 2023, UPS will no longer issue new API access keys."

Did oAuth2 implement in the App?

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/enterprise/pull/43538
