### ISSUE TITLE
OpenERP Report Designer Cannot download the existing report 

### ISSUE THREAD

**Issue by krmagnaye** [odoo/odoo#12353]
Impacted versions: Odoo Version 7.0-20140804-231303
OpenOffice Report Designer Version 1.0
OpenOffice 4.1.2 on Windows 7 64Bit

I cannot modify some existing report. but other reports are working properly.

ERROR:
The report could not be downloaded
Details: URL seems to be an unsupported one.

![test](https://cloud.githubusercontent.com/assets/19465728/15927419/2e661ea4-2e74-11e6-94cb-6502092772e7.JPG)

**Comment by JKE-be** [comment]
Hello,

"URL seems to be an unsupported one" is an OpenOffice error when it cannot be find the file (eg: special char, space in url, ...).

Can you check that your file is always present.
Delete all reports (*.swx) from your cache (local/temp) and do an update of the report list.

Can you reproduce it on another computer? Seems to be an error with your install and not with Odoo code.

**Comment by JKE-be** [comment]
Cannot reproduce on runbot. 
Please use https://help.odoo.com for this kind of question.

If you can reproduce it, don't hesitate to re-open an issue with the step 'how to reproduce'...
