### ISSUE TITLE
[IMP] loyalty: add the coupon to the printed order.

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#123629]
Description of the issue/feature this PR addresses:

If we make a loyalty program , like next order coupon, when we confirm the order only have the option to auto send an email with the coupon information.

Current behavior before PR:

Make an order and confirm it, if apply for loyalty program, Odoo send an email with the coupon.

Desired behavior after PR is merged:

When we confirm an order, the coupon will apear in the printed order (pdf), this will help selling more in a lower time, because maybe the email coupon can go to the draft email, maybe the customer don't gonna open the email, maybe can't go again to the store, etc.

**Comment by chapital** [comment]
@AntoineVDV

**Comment by chapital** [comment]
@Feyensv

**Comment by Feyensv** [comment]
cc: @dalaOdoo

**Comment by dalaOdoo** [comment]
This is a good idea, I'll think about that.

**Comment by vava-odoo** [comment]
Hi @chapital
Thanks for the feedback. 
This will be discussed internally with the experts and product owner.
I will try to keep you posted here. In the meantime, I close the issue as it is neither a bug nor an issue.
Also, may I ask you not to randomly ping people next time?
Best,

**Comment by chapital** [comment]
Done in 17.4
