### ISSUE TITLE
website_slides download_security always == 'user'

### ISSUE THREAD

**Issue by lslaz1** [odoo/odoo#12364]
Impacted versions: I'm on V9.0

Steps to reproduce: Download website_slide, upload a document to a public channel, try to download while not logged in.

Current behavior: When a slide is uploaded and there is a 'public' user, the download button prompts the user to log in. 

Expected behavior: Since the if statement says:
`if slide.download_security == 'public' or (slide.download_security == 'user' and request.session.uid):`
One would think that a public user or logged in user should be able to download. In either situation my pdb says slide.download_security == 'user'.

**Comment by JKE-be** [comment]
It's not because the channel is public that the slide is public...
![image](https://cloud.githubusercontent.com/assets/4848797/15963950/02b2901a-2f16-11e6-8938-d2e4ecaa8763.png)

**Comment by lslaz1** [comment]
😮 you just blew my mind. I don't understand why that's basically impossible to search for.
