### ISSUE TITLE
lessc not installed when running HEAD on Ubuntu 14.10

### ISSUE THREAD

**Issue by oddbjornkvalsund** [odoo/odoo#12365]
Impacted versions: HEAD

Steps to reproduce: run "wget -O- https://raw.githubusercontent.com/odoo/odoo/9.0/odoo.py | python", start "odoo.py", browse to http://localhost:8069 and create new database.

Current behavior: DIsplays http://localhost:8069/web with garbled layout and top of page says "Could not execute command 'lessc'.

Fix: Installing node-less and python-lesscpy manually resolves the problem.

**Comment by eronlloyd** [comment]
Thanks for the notes here. Could you elaborate a bit more on your workaround? I've installed nodejs-less and python-lesscpy but still nothing. Issue #7951 seems to be part of the issue.

**Comment by JKE-be** [comment]
@sle-odoo fixed ? closable ?

**Comment by Yenthe666** [comment]
@sle-odoo friendly reminder. Can it be closed?

**Comment by sle-odoo** [comment]
ubuntu 14.10 is no longer supported. just make sure you have lessc available in the path and it'll work.
