### ISSUE TITLE
Porting a module to Odoo 9 API

### ISSUE THREAD

**Issue by TheNiceGuy** [odoo/odoo#12363]
Hi, this isn't much of an issue and I'm not sure where to discuss this.

I need to extend the `Membership` module, but it uses the old API and the code is a mess. I'm thinking about porting it to Odoo 9 API (shouldn't be complicated) and cleaning the code. In order to maintain my own modifications easier, I'd like to pull request the ported version first. Would it be a great thing that I port the Membership module to APIv9? Would it be merged in master? I'm ready to give some time to it. 

Thanks!

**Comment by JKE-be** [comment]
Hello @TheNiceGuy 

It seems that this task has been already done by Odoo but not already merged.
Eg: https://github.com/odoo/odoo/pull/8141/files and https://github.com/odoo/odoo/pull/11811/files

In any case, we should/try to drop the old api in V10, so all modules will be converted (or are currently migrating) 

Thanks for your proposition, I close this issue... And you should be able to extend with new api an module in old api (I think... to confirm ... @mart-e ?).

**Comment by Yenthe666** [comment]
@JKE-be and @TheNiceGuy yes you can extend a module that is written in old API with the new API.

**Comment by TheNiceGuy** [comment]
Thanks for replying. Do you know when theses pull requests are going to get merged in master?

**Comment by JKE-be** [comment]
no idea... The last limit is the V10...
