### ISSUE TITLE
Validating an invoice without the field "Invoice date" triggers an error:

### ISSUE THREAD

**Issue by hokkaido** [odoo/odoo#1236]
The version in question from a couple of days ago (commit bcfa4c8e7ca4f8fb3b577e32eca9f3c0e8f99190 / master branch)

When I want to validate an invoice whose Invoice Date is not set, odoo throws a typical python error:

```
ValueError: "null value in column "date" violates not-null constraint
DETAIL:  Failing row contains (4, 2014-07-17 09:33:17.135856, 3, 1, 2014-07-17     09:33:17.135856, null, 1, null, Service, 1, 3200.00, 20, null, 576, 1, null, 3, 1, 5, null, , null, null).
" while evaluating
u'action_move_create()'
```

Shouldn't this field be set to "required" so that a nicer error message can be displayed to the end user instead?

**Comment by Yenthe666** [comment]
Hi @hokkaido,

This bug has been fixed quite a while back but nobody gave feedback here or closed this issue.
It has been solved in the mean time so if you update your Odoo source code you won't have this problem anymore.

Regards,
Yenthe
