### ISSUE TITLE
[BUG] STOCK :: Terribly Erroneous Stock Calculation in Edge Case

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#12380]
**Impacted versions:**
9.0

**Steps to reproduce:**

I think it can be reproduced by doing a no-operation, that is accidentally validating an internal move within the same stock location, for example MY/Stock -> MY/Stock.

**Current behavior:**
Source and Destination Calculation does show different value (actually it is just the double of the above mentioned no-operation.) Please see attached PDFs, where the difference is 158 and the no-op has just been 79. The fist two show the difference, whereas the third proves the stock to be 0.

**Expected behavior:**
I would expect, that source and destination calculation must equal when effective stock equals 0 (in other words, is not shown)

**Video/Screenshot link (optional):**

[Movimientos de Existencias - Felicity.pdf](https://github.com/odoo/odoo/files/310533/Movimientos.de.Existencias.-.Felicity.pdf)
[Movimientos de Existencias - Felicity2.pdf](https://github.com/odoo/odoo/files/310534/Movimientos.de.Existencias.-.Felicity2.pdf)
[Cants - Felicity.pdf](https://github.com/odoo/odoo/files/310535/Cants.-.Felicity.pdf)

**Comment by blaggacao** [comment]
2nd proof:
[Proof2 Cants - Felicity.pdf](https://github.com/odoo/odoo/files/310546/Proof2.Cants.-.Felicity.pdf)
Stock Valuation: 607
[Poof2 Movimientos de Existencias - Felicity1.pdf](https://github.com/odoo/odoo/files/310544/Poof2.Movimientos.de.Existencias.-.Felicity1.pdf)
Outgoing: 1653
[Proof2 Movimientos de Existencias - Felicity2.pdf](https://github.com/odoo/odoo/files/310545/Proof2.Movimientos.de.Existencias.-.Felicity2.pdf)
Incoming: 2339

----------
607 != 2339 - 1653 = 686
686-607 = 79 VOILA, the erroneous no-operation

**Comment by Yenthe666** [comment]
@jco-odoo could you look at this one please?

**Comment by jco-odoo** [comment]
I doubt this has to do with moves from and to the same location.  I did a same scenario with a picking just to be sure and it did not give any problem.

**Comment by blaggacao** [comment]
I still have this on my todo-list, will need further digging...

**Comment by blaggacao** [comment]
I'm investigating further and I verified that a move within a location seems not to be harmful. I'm not that intimate with the module, so it's quite hard for me to debug and understand what's going on (any hint are welcome). I'm now trying to relate the error to a move from a parent to a child location (which happen to be qty 79 as well) , maybe I can get any further there.

**Comment by blaggacao** [comment]
@jco-odoo 
I think I've found a hit, please give feedback:

**Situation:**

- I have `stock.location` A with children AA and AB
- I do a `stock.operation` in the form of A >> A of a product which is not directly available at the A level, but has existence in AA and AB
- Odoo does not complain in the `stock.operation` of non existing stock yet automatically picks from AA in the `stock.picking`
- Now I repeat the transaction A >> A exceeding the combined disponibility of AA and A (without exceeding A + AA + AB), but only what's available in A + AA is processed, the remaining is put on reservation.

**Comment by blaggacao** [comment]
Gotcha:

Based on the previous finding, I did the following:

1. I accumulated all of A and AA in A via `stock.picking`
2. I shifted the accumulated amount X to AA
3. I shifted the accumulated amount X from AA to AB. Remember, that on AB there is already an amount Y, summing now to X + Y.
4. I try to make a `stock.picking` A >> A (as in the previous analysis) by the value Z = X + a, where a < Y

**Result:**

- The picking from AB is only made up to the amount X, the amount a is not drawn from AB although (as Y>a), AB would have sufficient availability.

This affirms the suspicion of the previous intermediate research question, that `stock.picking` are not supposed to draw from child location via their `stock.pack.operation`.

If this suspicion can be confirmed, under what constellation, this restriction is violated? As we can see, the amount X is a magic value. What makes X different from Y while being identical (same product id) in kind?

**Comment by blaggacao** [comment]
On A DB-Level,
we have the following suspicious quants (those with relevant write_date):
```
| id  | create_date                | write_uid | propagated_from_id | package_id | cost             | lot_id | reservation_id | create_uid | location_id | company_id | owner_id | write_date                | qty | product_id | packaging_type_id | negative_move_id | in_date             |
|-----|----------------------------|-----------|--------------------|------------|------------------|--------|----------------|------------|-------------|------------|----------|---------------------------|-----|------------|-------------------|------------------|---------------------|
| 413 | 2016-07-10 22:51:18.469926 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 4   | 20         |                   |                  | 2016-06-01 22:45:15 |
| 411 | 2016-07-10 21:17:00.899386 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 5   | 20         |                   |                  | 2016-05-24 21:34:56 |
| 339 | 2016-06-01 22:51:39.382256 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 1   | 20         |                   |                  | 2016-05-24 21:34:56 |
| 337 | 2016-06-01 22:47:43.573674 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 11  | 20         |                   |                  | 2016-06-01 22:45:15 |
| 414 | 2016-07-10 23:11:31.236774 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 9   | 20         |                   |                  | 2016-05-24 21:34:56 |
| 412 | 2016-07-10 22:46:05.474383 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 12  | 20         |                   |                  | 2016-05-24 21:34:56 |
| 415 | 2016-07-10 23:17:57.914682 | 1         |                    |            | 110.095729511111 |        | 453            | 1          | 19          | 1          |          | 2016-07-10 23:46:41.88206 | 12  | 20         |                   |                  | 2016-05-24 21:34:56 |
```

I only can find a pattern in `in_date` and `reservation_id`, both of which do not speak to me as of now.

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by jco-odoo** [comment]
It has nothing to do with solving the negative quants.  (there it can take child location)

**Comment by pedrobaeza** [comment]
Thus I deduce that this can be closed.

**Comment by blaggacao** [comment]
@pedrobaeza perfectly so, thanks.
