### ISSUE TITLE
[IMP] l10_mx changes for mexico

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#123840]
I gonna list 3 changes that will help Mexican business but also other regions.

1.-if we have the option "lock confirmed sales" in settings/sales/quotation & order, also add an option: only can print confirmed orders, this gonna enable the option to print, if we try to print a quoatation we don't gonna appear the print button.

A lot of retail in mexico have a sign that says: "if the sales person don't give a receipt please notify to admin personal/cellphone or by email, and you will recive a free product or your purchase will be free. This is because some times the sales person don't report that sales and the money of the sales they keeps it, to avoid this kind of theft if important to print the order, but to avoid the sales person give a quoatation instead of the confirmed sale we need this option to have more control of our sales.

2.- block change price depending the rol established.

If the sales person have the rol "user" in sales, when they make a order don't gonna have the option to change price or maybe can but in a controlled way to avoid change the price lower that the cost or put a higher price Than 100% of the cost.

Also this if to avoid the theft in other way also common in mexico.

3.-have an option to don't allow change the price list, to avoid give especial prices to a one visit customer.

Thanks

**Comment by chapital** [comment]
@mart-e

**Comment by mart-e** [comment]
@chapital why do you ping me? I don't work on localisations

**Comment by vava-odoo** [comment]
Hi @chapital 
Thanks for the feedback. I transfer it internally and will try to keep you posted here.
In the meantime, I close the issue as it is neither a bug nor an issue.
Also, may I ask you _not_ to ping random people next time? 
Best,
