### ISSUE TITLE
[IMP] l10_mx set by default UNSPSC category

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#123832]
Before this commit when we create a product we need to stabling a UNSPSC category in the contability tap of the product

By default you can create a product and save it without put this information, but if you don't establish this info, when you make an invoice you can certificate this because the missing UNSPSC category.

To improve this I recommend 2 changes.

1.-By default when we create a product put the UNSPSC default category for not stablished category (01010101 no existe en el catalogo), or let the user define the default category by default, I recommend stablish this in sales setting an not in the product, because if we import products and not import the category this gonna keep blank.

2.-in product category (inventory/product/products category), add a tap (EDI MX), and have the option to establish the UNSPC category for that category of product.

This is a example:

We gonna establish or default UNSPSC Category for all the product in my case we gonna use (01010101 not defined)

Also gonna create a product category named OILS with default UNSPC category "12181600 oil"

So when we create a product by default if we don't establish the UNSPSC category in this product will use the (01010101 not established), but If we establish a UNSPSC category this gonna use the establish by the product.

But if we also establish the product category OILS in the product, the default category will be 12181600 oil.

So instead of keep blank by default we can create a option named: establish by default product/category.

**Comment by chapital** [comment]
@mart-e

**Comment by vava-odoo** [comment]
Hi @chapital
Thanks for the feedback. I transfer it internally and will try to keep you posted here.
In the meantime, I close the issue as it is neither a bug nor an issue.
Best,
