### ISSUE TITLE
[IMP] l10_mx set by default invoice info

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#123829]
Before this commit you can not set by default the "uso del cfdi" and "forma de pago" by customer

So every time we need to change this info, but with concurrent customer, this is annoying and if we forget change this info need to cancel invoices.

So we recommend add in the EDI MX tap in the customer info, the option to set by default this paramenters.

With this change we gonna reduce time to invoce and reduce errors.

**Comment by chapital** [comment]
@mart-e

**Comment by vava-odoo** [comment]
Hi @chapital
Thanks for the feedback. I transfer it internally and will try to keep you posted here.
In the meantime, I close the issue as it is neither a bug nor an issue.
Best,

**Comment by chapital** [comment]
Done
