### ISSUE TITLE
a question about build  module in odoo 9.0c

### ISSUE THREAD

**Issue by 474416133** [odoo/odoo#12382]
Impacted versions:odoo 9.0c

Steps to reproduce:thanks @JKE-be , @Yenthe666 again,I run odoo complete with their help,now I do step by step from document https://www.odoo.com/documentation/9.0/howtos/website.html.
firstly，i run command ./odoo.py  scaffold academy  my-modules[the server had stoped]
then  i run the server, ./odoo.py --addons-path addons,openerp/addons,my-modules.in my odoo account, i can not find the module i build[academy] in the app page.

what's wrong with me?
for help.......

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![app](https://cloud.githubusercontent.com/assets/17959465/15990492/46059b62-30c6-11e6-9683-ccb6bf15f6d1.png)
![app2](https://cloud.githubusercontent.com/assets/17959465/15990493/52b7e0b8-30c6-11e6-9a79-a0315f9ab5fb.png)
![app3](https://cloud.githubusercontent.com/assets/17959465/15990497/59a1e02c-30c6-11e6-8257-fdd709af2f78.png)

**Comment by 474416133** [comment]
in my table ir_module_module had no record about academy, someone can help me?

**Comment by JKE-be** [comment]
You néed to activate the developer mode and you Will have a menu 'update module list'.
Next you will see your app in the list!

But for this kind of question, please use the forum. (Forum.odoo.com)
