### ISSUE TITLE
Binary field: custom filename is ignored

### ISSUE THREAD

**Issue by andreparames** [odoo/odoo#1239]
I have a wizard with the following fields:

``` python
    result_file = fields.Binary('Result', default=_generate_xml)
    filename = fields.Char('Filename', default=_filename)
```

``` xml
<field name="filename" invisible="1"/>
<field name="result_file" readonly="1" filename="filename"/>
```

Both fields get auto-generated by their respective functions, so when the wizard is open, the user can download the file immediately. But if (s)he does, the download will have an auto-generated filename, not the value of the `filename` field.

The problem is in the web controller, in the `saveas_ajax` method; it's supposed to fetch the file data and filename from the first available source: first, it tries the data sent by the caller, if it's empty it tries reading the record's data, and if it doesn't have a record it tries to fetch the default. The problem is that since the JS caller sends the file data, but not the `filename` field value, the method simply "forgets" that it's supposed to get the filename as well, and assumes there's no filename field.

**Comment by nono6677** [comment]
I'm concerned too.
when i'm in tree or form view of object it works but when i test in one2many view i download the file with no name

**Comment by samuellefever** [comment]
Affected too!

**Comment by lbaldi** [comment]
+1

In Tree View or Form View download file with name.
In One2many tree inside another view download file without name.

**Comment by Yenthe666** [comment]
Hi @andreparames,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
