### ISSUE TITLE
Accounting - Transactions are not fetched from Mashreq Neobiz account

### ISSUE THREAD

**Issue by new-kirte** [odoo/odoo#123955]
Impacted versions: SAAS-16

Steps to reproduce:
1. Create a bank account. The account is added and the balance is shown correctly
2. In the accounting dashboard click on Fetch Transactions
3. No transactions have been fetched

Current behavior:
No transactions are fetched, no errors shown

Expected behavior:
Transactions are fetched

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 3355570

**Comment by vava-odoo** [comment]
Misconfiguration issue
