### ISSUE TITLE
openerp.service.web_services: Exception: tostring() has been removed. Please call tobytes() instead.

### ISSUE THREAD

**Issue by brauers** [odoo/odoo#12390]
Impacted versions: openERP 7

Steps to reproduce: dump database from affected system and restore it on a differenten Synology DS
as well as on a VM running in Docker Environment on DS716+II
Current behavior: Newly created customer bills can't be emailed or printed out 

Expected behavior: customer bill's should be able to print (export to pdf) or send by email

Video/Screenshot link (optional):
![bildschirmfoto 2016-06-13 um 10 51 09](https://cloud.githubusercontent.com/assets/16855015/16004091/24faac1a-3160-11e6-9026-974693f96065.png)

**Comment by JKE-be** [comment]
Hello, 
Same answer than on the forum...
What is the version of your pillow library ? 
thanks

**Comment by brauers** [comment]
Hi, 
Metadata-Version: 1.1
Name: Pillow
Version: 3.2.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org

thanks, sorry for double opened

**Comment by JKE-be** [comment]
you can remove it or downgrade it ... 
Thanks for the reporting

**Comment by JKE-be** [comment]
https://github.com/python-pillow/Pillow/pull/71
https://github.com/python-pillow/Pillow/issues/63

**Comment by brauers** [comment]
how to remove/downgrade pillow from Syno NAS

**Comment by sle-odoo** [comment]
Hello,
You are asking questions about Synology on the Odoo bug tracker. Anyway AFAIK python is not installed by default on synology so if you have pillow installed either you installed it manually or another application installed it. If you don't care about the other applications then open a shell to your synology and make a source install. There is an installation guide on the [odoo documentation here](https://www.odoo.com/documentation/9.0/setup/install.html#source-install). There is also the option of virtualenv to support multiple version of python library simultaneously.
Regards

**Comment by brauers** [comment]
Hi guys,

I apologize asking this question in Odoo bug tracker. 
However, installing OpenERP 7.0 will automatically include python module installation - at least on a Syno DS. There is no way using the GUI to remove  python modules keeping OpenERP 7.0  installed. 

dpkg -r pillow is returning pillow is not installed on Syno (not your problem, correct)

Conclusion: After automatic update happened to python modules last Wednesday my openERP is not working anymore as of issues with pillow. And currently I learned what’s the reason but I don’t see a way out.

thanks and best regards

**Comment by hadd0ck** [comment]
Hi guys, 
Did you find a solution yet ? Same error had occured on my NAS. Should we talk directly to Synology ?

Best,

**Comment by JKE-be** [comment]
hello @hadd0ck 
Which verison are you using ?

**Comment by hadd0ck** [comment]
Hi JKE-be,

I have my own NAS with this infos below

DS214 with DSM 6.0.1-7393  
openERP Version 7.0-20130226-002110

thanks for your interest

**Comment by brauers** [comment]
the Solution needs to be provided by Synology afai

**Comment by JKE-be** [comment]
@sle-odoo (@The_package_manager) I know your affection for this issue ... Could you confirm that it should be fixed in the package from Synology directly ? And so by Synology themselves... ?

**Comment by hadd0ck** [comment]
Thanks @JKE-be and hello @sle-odoo , glad if you can help to solve our common problem ;-)

**Comment by cycleuzb** [comment]
Hi,

i have same problem may some people help me how to resolve it ?

**Comment by ctrlaltdelete007** [comment]
Hi,
same problem here, is there any solution?

**Comment by JKE-be** [comment]
@brauers Any news from Synology ?

**Comment by brauers** [comment]
not yet, I ll keep u up

Mit freundlichen Grüßen
Stephan Brauer
015164619440

**Comment by ramsodev** [comment]
For me the only solution is downgrade pythonmodules and OperEpr7 to 106. Review this  https://forum.synology.com/enu/viewtopic.php?t=105036#p397451

**Comment by jappie11** [comment]
@brauers  @JKE-be Just to let you know I had the same issue and resolved it as follows:

Steps to take:
1. **Download the previous version (0106) of the "Python Modules" package** from the Synology download repository ([](http://download.synology.com/download/spk/PythonModule/0106/)) as per your box' processor (login to your box using SSH and type "`uname -m`" on the CLI to find the processor of your machine. In my case response is "armv5tel", i.e. the package for my processor is: [](http://download.synology.com/download/spk/PythonModule/0106/PythonModule-armv5-0106.spk)
2. Upload the package from step 1 onto your box (I did this via the Web interface) and move to a directory of your choice
3. Move to the directory where you moved the package (i.e. /volume1/downloads/PythonPackage) and unpack the package using `tar -xvf PythonModule-armv5-0106.spk `. If you want to list the unpacked contents using `ls -la`. Note that there is still an unpacked file called "package.tgz"
4. Extract "package.tgz" using `tar -xvf package.tgz `. f you want to list the unpacked contents using `ls -la`.
5. Notice how in the contents of following path `ls -la ./usr/lib/python2.7/site-packages/` you can see a sub-directory called "PIL" `(ls -la ./usr/lib/python2.7/site-packages/PIL/`). This directory ("PIL") was deleted from package 0107 of the PythonModules package and needs to be copied back in the correct location on your box.
6. ` cp -R ./usr/lib/python2.7/site-packages/PIL /usr/lib/python2.7/site-packages/`
7. Restart OpenERP7.x `synoservice --restart pkgctl-OpenERP7.x`

You should now be good to go again and not have any issues with the print function in OpenERP7.x

HTH, JP

P.S. I have logged a ticket with Synology related to this issue but have not seen a response yet.

**Comment by brauers** [comment]
@jappie11
can u share the Ticket ID, I have a direct contact and might be able to escalate the issue
thanks for the WA I will try it out :)

**Comment by jappie11** [comment]
@brauers Synology Support Ticket: #851229

**Comment by soleluna** [comment]
My OpenERP7 on DS716+ showed the same error on printing.
This was the second time, SYNOLOGY broke OpenERP7 by Update.
I am very scared, using Update furthermore.
It is a pitty, that there is no UNDO / RESTORE via DSM User Interface.
SYNOLOGY should think on BACKUP and RESTORE the station installation.
With the new filesystem BTRFS, it should be easy.

The described 7 steps worked for me - I can print again PDFs.
Thank you very much!

I was logged via terminal with admin account.
To succeed, I had to add for commands Step 6 and 7 SUDO:

`sudo cp -R ./usr/lib/python2.7/site-packages/PIL /usr/lib/python2.7/site-packages/`
`sudo synoservice --restart pkgctl-OpenERP7.x`

**Comment by fadedglory** [comment]
@jappie11 I think your links are dead. Is that correct ?

**Comment by jappie11** [comment]
@fadedglory 
It seems that Synology has changed the URL to access the files I referenced and more importantly have disable the browsing of the various directories. I've been able to verify though that the following link does work to download the previous version of the Python Module package. 

**Version 01.06:** [https://global.download.synology.com/download/Package/spk/PythonModule/0106/PythonModule-armv5-0106.spk](https://global.download.synology.com/download/Package/spk/PythonModule/0106/PythonModule-armv5-0106.spk)

Cheers JP
