### ISSUE TITLE
Message Composition Wizard in Portal shows annoying dialog when clicking Send

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#12407]
Impacted versions: Odoo 9 latest version

Steps to reproduce: Install _portal_ and _project_ modules. Then create a portal user and add this user to a project. Then log in as portal and open the project's form view. In the project's thread, start a new message by clicking on the new composition icon (next to paperclip and insert emoticon icons). Type in a message and click Send.

Current behavior: Clicking Send shows this dialog: "The record has been modified, your changes will be discarded..." When you click Cancel, you'll get redirected to the front-end website, you need to click Yes or close the dialog using its X icon on the upper right corner before you can send the message by clicking Send again. 

Expected behavior: This does not occur if you are logged in as an ordinary user. It only occurs in portal.

**Comment by JKE-be** [comment]
Thank you for the reporting. 
@ged-odoo will take a look asap...

**Comment by Yenthe666** [comment]
@JKE-be and @ged-odoo any update?

**Comment by pedrobaeza** [comment]
Do you have any news about this?

**Comment by Yenthe666** [comment]
I'm not sure if we should close this one off now. V9 is no longer supported.
