### ISSUE TITLE
[IMP] Sales: catalog view with alternatives

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#124052]
Before this commit when you configure a product, an add alternatives products you can only see this products in website.

So we recommend add a button in the new catalog view (16.3->), that show the alternative products.

This will reduce the time searching products, move low movement stock, don't lost sales for out of stock products, increase sales amount, etc

Also can be implemented in POS, to work together with all the apps.

**Comment by dalaOdoo** [comment]
@chapital thanks for your feedback we will take it into account for future improvement

**Comment by chapital** [comment]
#131642
