### ISSUE TITLE
Readonly & Invisible fields are checked by client

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#1240]
In version 8.0 a field that is set to readonly and invisible on the view is being checked by the client for values.The previous behaviour ignored readonly fields in the view and did not send them to the server nor did it check the values in the web-client.Has this changed with version 8?

This has been discussed here:
https://www.odoo.com/forum/help-1/question/how-to-handle-reading-and-writing-to-read-only-fields-2247

and here:

https://bugs.launchpad.net/openobject-client/+bug/378824

**Comment by Yenthe666** [comment]
Hi @PCatinean,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
