### ISSUE TITLE
Fail to sudo -H pip3 install -r /opt/openhrms/requirements.txt

### ISSUE THREAD

**Issue by beaconho** [odoo/odoo#124050]
Impacted versions: 16.0

Steps to reproduce: studied the requirements.txt, seems its the problem of feedparser

Current behavior: 
Collecting feedparser==5.2.1 (from -r /opt/openhrms/requirements.txt (line 5))
  Using cached feedparser-5.2.1.zip (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

Expected behavior: Install Feedparser

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by beaconho** [comment]
My python is 3.10.6, on Ubuntu

**Comment by gdgellatly** [comment]
openhrms is not created or supported by Odoo, best contact the developers in their own repo.
