### ISSUE TITLE
[9.0] website: /logo.png displays wrong company logo

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12419]
Impacted versions:
9.0e

Steps to reproduce:
- Create two companies: Company A, Company B (they are not related)
- Set different logos for Company A and Company B
- Go to users, select inactive users and duplicate Public user. Set login as public2, set company to Company B and allowed companies only to Company B.
- Now public user has access to company A, and public 2 to company B
- Go to website admin and activate versioning option.
- Create a second website with a different domain, call this website Site B.
- On Site B, set user to public2 and set company to Company B.
- Apply changes.

Current behavior:
- Go to domain of Site B, it will load the website with all info related to Company B (name, address, etc..) but the logo displayed at the menu shows Company A logo.
  (Yes, I tried cleaning my browser cache and tested it on Incognito and private mode, in Chrome and Mozilla)

Expected behavior:
Going to Site B should display Company B logo.

**Comment by aristobulo-eezee** [comment]
@mart-e could you check this one?

**Comment by treviser** [comment]
FYI: this is an old issue, concerning also 8.0 and 9.0c, see this for a possible solution:
https://github.com/it-projects-llc/misc-addons/issues/194
