### ISSUE TITLE
Odoo 16 translations lines marked as "code - JS and XML file" not imported

### ISSUE THREAD

**Issue by Ranamiu** [odoo/odoo#124124]
UPDATE 070623 18:39 Madrid time title changed: some "code" XML file are also being affected. Other "code" XML files are not. Me not able to find out a logical pattern for this bug.

Hi dears,

This bug is probably similar to #115876 (bug for JS files translations), please check "code" translations line for "JS" files on Odoo 16:

Translations lines marked as "code" and addressing a XML file are OK.
Translations lines marked as "code" and addressing a JS file are NOT OK.

Never happened this on older Odoo (15, 14, etc.)

How do we work with Odoo16 without being able to fully translate?

Kindly find here attached screenshot.
Thanks in advance

Impacted version: 
 
- 16.0 (last checked 070623) .
 
 
Steps to reproduce:
 
1. Settings > Translations > Export a translation for a single or all modules.
2. Donwload a .PO (same on CSV) and open using POEDIT or just a simple TXT editor (does not matter).
3. Modify any translations line **marked as "code" and addressing a JS file**.
4. Import .PO file once modified locally and saved.

 
 
Current behavior:
 
- **Translations lines marked as "code" and addressing a JS file** are not being translated. No error message, neither log error, no trace of this error. 

Expected behavior:
 
- **Translations lines marked as "code" and addressing a JS file** are expected to be effectively imported and translations to be applied as on e.g. Odoo 15
 

UPDATE by correct screen shot, changed title and body text.
Apologies me

![16-translation-2](https://github.com/odoo/odoo/assets/29396762/c10b3396-c624-47b5-8db1-a0ee9eb477ce)

**Comment by Ranamiu** [comment]
ADDENDA:

Kindky apologies me to stress this out.

As reported here, it seems even not related with JS or XML file, probably does not matter depending on a 3th  unknow cause.

Please check this thread and also pasted screen shot:

https://www.odoo.com/es_ES/forum/ayuda-1/odoo-16-import-translations-marked-as-code-not-working-221378

Copy and paste here:

I will have a try in order to confirm the following XML  term also.

Appreciate your attention.

![image](https://github.com/odoo/odoo/assets/29396762/866e32e2-e53e-4fd1-90ec-3119257a44bf)

**Comment by Ranamiu** [comment]
Apologies again, not to offend anyone.

All my respect to those involved in this development.

I am just astonished how this could still happen after 9 month since Odoo 16 has been launched.

Odoo 16 is honestly a superb machine, would say magnificent.

Never seen a Odoo so fast, so efficient as Odoo 16.

BUT: is the current trade-off losing core funcionalities as a simple and crucial translation?

Our users (end users) tell us NO, cannot use Odoo 16 this way.

Kindly confirm bug is also on XML, just tried out on https://demo.odoo.com/ - Odoo saas~16.3+e (Enterprise Edition) today 070623 18:19 Madrid time

Also confirmed on latest Odoo 16 CE - version 070623

Please, find here attached screen-shot:

Thanks in advance

1. Prior
![bug-16-1](https://github.com/odoo/odoo/assets/29396762/a9b955d5-f9e8-48a5-a7db-128430284777)
 to upload

2. Following upload: translations line "code" XML not being imported
![bug-16-2](https://github.com/odoo/odoo/assets/29396762/c3bb4298-2f6e-4ca3-886d-3dbdea9ced15)


From Odoo saas~16.3+e (Enterprise Edition) today 070623 18:19 Madrid time:
![bug-16-5](https://github.com/odoo/odoo/assets/29396762/a7f799a0-9710-4388-a67c-4412cf86f512)

**Comment by vava-odoo** [comment]
Hi @Ranamiu 
Asking the input from @odoo/rd-framework-py but, as you mentioned, this seems related to  https://github.com/odoo/odoo/issues/115876
Best

**Comment by Yenthe666** [comment]
I can confirm we see similar issues on multiple of our customers. It's been a very unpleasant experience so far.
See also my OPW `3340717` where an Odoo functional consultant dismissed it as no longer possible and that we should buy success packs to get things like this sorted. 

I'm sorry but I don't get how such a big company as Odoo SA f*cked up such a big things. What's the solution/timetable here? It is really difficult to explain to our customers and having to bill time to change something as stupid as translation terms.

**Comment by MeetKD** [comment]
We are facing similar issue where customer requested to change the terms and it is impossible to change the terms coming from js. As stated in https://github.com/odoo/odoo/pull/124790 it will be targeted on master, what will be the possible solution for v16 ? @mart-e

**Comment by Ranamiu** [comment]
Kindly, need this to be fixed also on 16.

Cannot actually work on Odoo 16 translations because some "code translations" cannot be translated, other seems to be buggy, or probably just not well structured.

All our respect to those involved in this development and desired fix.

Appreciate

**Comment by HydrionBurst** [comment]
As explained here
https://github.com/odoo/odoo/pull/124790#issuecomment-1695666888
code translation is designed to be non-customizable in the runtime

**Comment by mart-e** [comment]
Hello,

As explained in #115876 the JS translations (everything in `/static/`) are no longer stored in the database and there is no plan to change that as far as I know.
I belive my colleague has tried alternative in #124790 but without success so these code translations are not customisable I am afraid.

**Comment by Yenthe666** [comment]
😢 That's a pity. Have you considered rendering an UI based on the JSON?

**Comment by Ranamiu** [comment]
Disappointed. 

Cannot honestly understand how such a important issue is not going to be fixed.

Does it mean that hereafter Odoo can be used by a default "centralized translation criterion" only?

¿What about differences, languages nuances, multicultural and local business facets?

Language accuracy is a crucial part of business.

I have been teach that marketing is listen to customers.

Apologies, not to be offensive.

Just disappointed

**Comment by habib08-netlinks** [comment]
I have the same issue in Odoo 16 community version. It does not translates texts from ValidationError or UserError.

**Comment by matteoopenf** [comment]
I Have similar problem in Odoo 16EE
