### ISSUE TITLE
[V9] Product status (state) can't be filled.

### ISSUE THREAD

**Issue by cyrilgdn** [odoo/odoo#12418]
In product.template tree view, there is a [Status (field name: state) field displayed](https://github.com/odoo/odoo/blob/9.0/addons/product/product_view.xml#L62) but this  field was removed in form view in [this commit](https://github.com/odoo/odoo/commit/af9d21b379f1dd42e83dcfa164af489c9261542d#diff-ff82cb73c72dabaf570b0e9bad939b0eL110)

So the product state can't be filled.

Expected behavior: Either the field is completely deleted or it is editable...

**Comment by mart-e** [comment]
Thanks for the report, indeed the field state is deprecated and we chose to remove it from the standard views. The tree view was forgotten.
