### ISSUE TITLE
[9.0] website: not able to remove a created website

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12415]
Impacted versions:
9.0

Steps to reproduce:
Go to website admin and create a new website.

There is no way for an user to delete a website, either because is not needed anymore or if it was created by mistake.

Please provide a standard way to delete a website.

**Comment by aristobulo-eezee** [comment]
Only when A/B versioning is activated Websites are accesible in a list view. A/B versioning is only available in 9.0e, while `website` is a standard object included in 9.0c

It should be better to move 'Website Domain' menu to Website > Configuration

Also, it doesn't make much sense having Website Domain only after installing versioning.

**Comment by Yenthe666** [comment]
@mart-e what do you think about this?

**Comment by mart-e** [comment]
Hello,

Sorry but in 9.0 the multi-website is not supported for website alone. Adding a menu for website configuration would give a false sense of giving this feature while it would not work (e.g. trying to configure one website per company and getting issues with static files).
In case you created an extra website by mistake, you will need to create a new menu to delete it.

**Comment by aristobulo-eezee** [comment]
@mart-e are you 100% sure? 

In 9.0e you can create as many domains as you want without installing `website_version` and they will work as different websites.

**Comment by mart-e** [comment]
Sure you can create multiple website, the system allows you to do so but we don't recommend it, it's still experimental. #12429 is an example of problem that occurs.

**Comment by aristobulo-eezee** [comment]
@mart-e wait a minute, having multiple domains doesn't imply having multi-company websites. 
Scenario:

1. A 9.0e user installs website builder.
2. Goes to Website admin, clicks on create and edit.
3. Oops, I have changed my mind.
4. How the hell do I delete it?

Of course you can recommend to install website_version but isn't really necessary. 

Is just an usability issue. An user can create many domains, if a mistake is made, you can't delete the website domain from odoo. That's a basic operation. 

Not even once have I mentioned to have the extra things from `website_version` only to have the menu allowing an user to see a website domain list and be able to select and delete.

If the feature is experimental, why did it landed on stable? Really, you use the word stable at your convenience.

You should reconsider this one
