### ISSUE TITLE
[8.0] Accounting, Create Account, Possible parent accounts list not populated

### ISSUE THREAD

**Issue by greanie** [odoo/odoo#12422]
Impacted versions:
8.0
Steps to reproduce:
Accounts->Accounts->Create : Set the parent
Current behavior:
Upon selecting the 'Parent' edit box, no list of existing analytical accounts comes up, only 'Create & Edit'
Expected behavior:
Upon selecting the 'Parent' edit box, a list of existing analytical accounts comes up as well as 'Create & Edit'
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @greanie,

I'm not sure what you mean. I get to see them all right away?
![image](https://cloud.githubusercontent.com/assets/6352350/16191592/51efae0c-36e5-11e6-9f50-f2d2a2e1961c.png)

**Comment by greanie** [comment]
Ni, that list is not coming up for me so I can't set a hierarchy.

**Comment by greanie** [comment]
I tried updating the parent_id in the database table but that cause the chart of accounts to crash so that isn't a viable work around in and of itself.  Anyone have any ideas?

**Comment by greanie** [comment]
When I tail -f the log file, edit an account and click on the pull down arrow inside "Parent Id" box, in the log I see

POST /web/dataset/call_kw/account.account/name_search HTTP/1.1" 200

But no list comes up.

When I try to edit or create a record that requires an account reference and click to pull down the list of available accounts, the log file also shows

POST /web/dataset/call_kw/account.account/name_search HTTP/1.1" 200

But the field list is properly populated.  It seems this may be more of a javascript error.
