### ISSUE TITLE
Odoo GitHub branch 6.1 diferent content than Launchpad

### ISSUE THREAD

**Issue by jpges** [odoo/odoo#1242]
For example, purchase addon code in launchpad is:

http://bazaar.launchpad.net/~openerp/openobject-addons/6.1/files/head:/purchase/

In GitHub:

https://github.com/odoo/odoo/tree/6.1/addons/purchase

It is easy to check than "images" folder isn't in GitHub version.

Is this an error?

More similar cases: stock, hr, account, knowledge

I have fixed the issue copying again this folders from Launchpad version.

**Comment by mart-e** [comment]
As mentioned on [GitHub Transition](https://github.com/odoo/odoo/wiki/GitHub-Transition) page, everything has been migrated now
