### ISSUE TITLE
addon delivery action_confirm @api.multi

### ISSUE THREAD

**Issue by Ben17000** [odoo/odoo#12427]
Impacted versions: all

Steps to reproduce: 

in file  odoo/addons/delivery/models/sale_order.py
we have

1    @api.multi
2   def action_confirm(self):
3        res = super(SaleOrder, self).action_confirm()
4       for so in self:
5            self.invoice_shipping_on_delivery = all([not line.is_delivery for line in so.order_line])
6    return res

as action_confirm is @api.multi decorated we should have :
so.invoice_shipping_on_delivery = all([not line.is_delivery for line in so.order_line]) on line 5

**Comment by JKE-be** [comment]
Hello @Ben17000 
Could you make one pr with this fix. ? 
thanks

**Comment by rim-odoo** [comment]
Fixed by #12503
