### ISSUE TITLE
[9.0] website_sale: Multi website + multi company shows wrong payment methods

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12429]
**Impacted versions:**
9.0, probably 8.0 also.

**Steps to reproduce:**

1. Create two companies: Company A, Company B (they are not related)
2. Go to Invoicing > Configuration and activate Paypal and Ogone acquirers.
3. Go to Invoicing > Configuration > Payment Acquirers and set PayPal's company to Company B, set Ogone's company to Company A. 
4. Set both acquirers to be published on website, set wire transfer to not be published on website.
5. Go to Settings > Users, activate Inactive Users, select Public User and duplicate it. Set new user's login to public2, set name to Public user (site 2), set company to Company B and allowed companies only to Company B
6. Create a new website domain and call it Site2, set company = Company B, set Public User to Public user (site2)

**Current behavior:**
Go to site2 shop, add a product to cart, Process Checkout, fill your billing information and Confirm.
Next page will show you Ogone as payment method, although you are on Company B's website. 
You can verify you are in company B's website checking the company info displayed. 

**Expected behavior:**
Go to site2 shop, add a product to cart, Process Checkout, fill your billing information and Confirm.
Next page should show you Paypal as payment method

Problem is that, by default when a product is added to cart, Odoo will generate a new Quotation (sale.order in draft state) with customer = Public User (for current website) but it's created using company as default company (Company A), not current public user's company (Company B).

Of course, after the quotation is confirmed with the wrong company, the following invoicing process will also use the wrong company.

**Comment by aristobulo-eezee** [comment]
This also affects customer creation.

New eCommerce customers will be created for the wrong company if using the configuration described before.

**Comment by aristobulo-eezee** [comment]
I have found a fix for wrong payment methods and wrong company in quotation.

Check here: https://github.com/eezee-it/odoo/commit/9def13bd97a9a0184f48850e4461fb8d5eba7b18

**Comment by aristobulo-eezee** [comment]
@Yenthe666 you might wanna have fun with this one

**Comment by Yenthe666** [comment]
@aristobulo-eezee what a nicely detailed report, thanks!
@fwi-odoo, @mart-e and @odony could you guys look at this one? There is indeed something wrong there.

**Comment by aristobulo-eezee** [comment]
And a fix for the wrong company at customer creation: https://github.com/eezee-it/odoo/commit/ef94d887095bb1c977130b0d36f8974b1c4285ed

**Comment by Yenthe666** [comment]
@aristobulo-eezee maybe you could make a PR for this? :smile: 
I can't promise you it'll be accepted though, that is not my call.

**Comment by treviser** [comment]
@aristobulo-eezee Are you talking about the Enterprise Edition?

**Comment by aristobulo-eezee** [comment]
@treviser to have multiple website, yes. But it will also the case on 9.0c if you hack it a little to show the fields at `website` object

**Comment by dansanti** [comment]
well, i thinks there are many troubles with multi company + multi website, because, public user is only one for all new instances and then ie, recruitment process , when search for jobs, search width public user company domain , and that user is associated to first company created.
https://github.com/odoo/odoo/issues/12229

**Comment by antonylesuisse** [comment]
Multi website is not supported and we wont fix bug related to it.

We have technical layer (in ir http) to select a website based on the domain and to attach different public users to the different website but that feature is hidden and unsupported. We laid those technical fundation as we plan to support it in the future, but it's still need a lot of work (i.e. one user logged on the 2 website will force their company_id and pricelist_id, ir.ui.view inherit_id is not cross website etc...).

So if you use it, use it at your own risks.

**Comment by aristobulo-eezee** [comment]
@antonylesuisse what you say is not completely true, why? because after you activate website versioning the fields to change websites company/user are there, so no, it's not hidden.

**Comment by antonybrugger** [comment]
@antonylesuisse I can understand that if the multi-website feature is not supported officially, so bug related to this functionality are not fixed. 

Could be good to have an official list of supported functionality, especially for Odoo Enterprise, cause when you see in the official 'stable' version following menu entries:
![image](https://cloud.githubusercontent.com/assets/2707881/16112272/eecd96c6-33b6-11e6-8af5-3ded5a7dc1ce.png)
where you can manage 'Website Domains' (strange also that this is in the Versioning Menu? it's not for managing versioning, isn't it?), so 'a priori' this is multi website functionality and it's not hidden, so if you don't hide it you are exposed to questions and bug fixing (especially with an Odoo Enterprise contract)

"The devil is in the detail"

**Comment by aristobulo-eezee** [comment]
You should decide if multi-website is supported or not, saying that is not supported and will not be fixed and then pushing fixes to 9.0e, is the complete opposite.
