### ISSUE TITLE
[9.0] Multi domain websites are not working as expected

### ISSUE THREAD

**Issue by kenneth-vkd** [odoo/odoo#12437]
Impacted versions:
9.0
Steps to reproduce:
Create a new Odoo installation with the website module enabled and only one database.
Enable multi company and create a second company.
Assign website localhost to the first company and change the domain name to match the domain name of this site. Fx. domain1.com
Create a second website and assign domain2.com to this and assign the website to the second company.
Visit the website and customize the frontpage for the first website and add some menu entries and pages.
Visit the second domain name and log in. Add some pages and menu entries and set one of the pages as the homepage.
Change the theme in domain2.com

Current behavior:
Both domain1.com and domain2.com share the same frontpage, but other pages are not shared.
Changing the contents of the frontpage or changing the theme applies to both websites and not just the one currently being edited

Expected behavior:
domain1.com and domain2.com should have seperate unique frontpages and should be able to have individual themes in order to have a true multi website functionality like seen with other website CMS applications.

**Comment by jholze** [comment]
Because of the multiple themes stuff. This will be a big change. We already tried it. But i think you can manage different layout themes within one with some tricks, even if this isn't a clean way.

**Comment by kenneth-vkd** [comment]
What about just the issue with a unique frontpage per website? The theme issue might hopefully get fixed at some point or maybe be an enterprise subscription only feature.

**Comment by JKE-be** [comment]
Hello @kenneth-vkd 

I do not often play with multi website, and I know that all is not possible/working 100% and sometime it is painful to set it in place...

All page (and so view) create before the setup of the 2th website are shared between all websites.

So your homepage is share by default, if you go on the form ir.ui.view you should be able to limited this view to One website and create a new homepage for the other website.

About the theme, you can try to add also the website_id on all views of concerned theme but it is without guarantee, I never try it... (You shloud maybe try on dev instance before :) )

But keep in mind that if you have common view to all website, you may need to change some xpath to find a common way to specify the place where you want insert your current node.

**Comment by eronlloyd** [comment]
It would be great to clear this up. I have client use cases around this that I'm stuck on because of uncertainty on how to implement multiple sites.

**Comment by aristobulo-eezee** [comment]
Just FYI, the official Odoo response for bugs on Multi-domain-website related issues is: won't fix, unsupported
Read it by yourself: https://github.com/odoo/odoo/issues/12429#issuecomment-226418351

**Comment by Yenthe666** [comment]
Indeed, this should have been closed a while back.

Quoting @sle-odoo from the original topic:

> Multi website is not supported and we wont fix bug related to it.
We have technical layer (in ir http) to select a website based on the domain and to attach different public users to the different website but that feature is hidden and unsupported. We laid those technical fundation as we plan to support it in the future, but it's still need a lot of work (i.e. one user logged on the 2 website will force their company_id and pricelist_id, ir.ui.view inherit_id is not cross website etc...).
So if you use it, use it at your own risks.
