### ISSUE TITLE
[8.0/9.0/10.0/Master] website_livechat, im_livechat

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#12431]
<h1>Impacted versions:</h1>
8.0/9.0/10.0/Master

<h1>Steps to reproduce:</h1>
<ol>
<li>Settings >> Website Live Chat >> How to use the Website Live Chat widget? >> [your head tags code here]</li>
<li>Copy and paste this into the header of a website including the jQuery library. Many functions will be broken due to the fact it is being included twice.</li>
<li>Create an empty HTML file and include the livechat code provided by Odoo live chat, and include the jQuery library. I've added a block of example code below so that you can reproduce (you will need to use your own odoo instance to do this, as it does not seem possible to include the livechat code from the runbots).</li>
</ol>

```
<HTML>
<HEAD>
<link href="http://www.exampledomain.com/im_livechat/external_lib.css" rel="stylesheet"/>
            <script src="http://www.exampledomain.com/im_livechat/external_lib.js" type="text/javascript"></script>
            <script src="http://www.exampledomain.com/im_livechat/loader/1" type="text/javascript"></script>
<script   src="https://code.jquery.com/jquery-3.0.0.min.js"   integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="   crossorigin="anonymous"></script>
</HEAD>
<BODY></BODY>
</HTML>
```

Here's the same code without the jQuery library included.
```
<HTML>
<HEAD>
<link href="http://www.exampledomain.com/im_livechat/external_lib.css" rel="stylesheet"/>
            <script src="http://www.exampledomain.com/im_livechat/external_lib.js" type="text/javascript"></script>
            <script src="http://www.exampledomain.com/im_livechat/loader/1" type="text/javascript"></script></script>
</HEAD>
<BODY></BODY>
</HTML>
```
<h1>Current behavior:</h1>
Website livechat widget (for pasting into the head tags of other websites - not odoo) includes the jquery library. 

If the target website also includes the jquery library, this will conflict with the target website's jquery functionality, causing unwanted behaviour.

<h1>Expected behavior:</h1>
My opinion is that it would be best to provide some sort of mechanism to not include the jQuery library, in order to allow people to use this widget with websites that include the jQuery library in them already. This option could perhaps be included as visible in the developer mode only to keep things clean for regular end users.

**Comment by Yenthe666** [comment]
@aab-odoo and @jem-odoo could you guys have a look at this one?

**Comment by lukebranch** [comment]
@Yenthe666 ,

Thanks for taking a look at this.

I will post back a bit later with clear steps to reproduce with another framework.

**Comment by lukebranch** [comment]
@Yenthe666 ,

I've updated the issue to include an example HTML file to allow you to reproduce the issue with your own odoo instance.

If the livechat widget is included along with the jQuery library, it breaks both the jQuery functions on the target website, and the live chat widget itself.

**Comment by Yenthe666** [comment]
@JKE-be this sounds like something for you!

**Comment by lukebranch** [comment]
@Yenthe666 ,

Just wanted to ping you on this one to see if there was any possibility of a fix/workaround. I think this feature would be useful for those who want to embed Odoo live chat in other platforms like Magento/Wordpress, etc. using themes that already include jQuery.

If it's a won't fix i'll just close it.

**Comment by Yenthe666** [comment]
@aab-odoo @jem-odoo and @JKE-be some feedback on this one please? 😄

**Comment by JKE-be** [comment]
Simply replace de jquery script by something like should work:
```js

<link href="http://www.exampledomain.com/im_livechat/external_lib.css" rel="stylesheet"/>
<script src="http://www.exampledomain.com/im_livechat/external_lib.js" type="text/javascript"></script>
<script src="http://www.exampledomain.com/im_livechat/loader/1" type="text/javascript"></script>
<script type="text/javascript">
    if(typeof jQuery == 'undefined'){
        var oScriptElem = document.createElement("script");
        oScriptElem.type = "text/javascript";
        oScriptElem.src = "https://code.jquery.com/jquery-3.0.0.min.js";
        document.head.insertBefore(oScriptElem, document.head.getElementsByTagName("script")[0])
    }
</script>
```

But that open the door to news bugs... Eg, uncompatible jquery...

**Comment by lukebranch** [comment]
@JKE-be ,

Thanks for the tip! I had previously tried to play around with Odoo live chat on Magento websites using jQuery and ran into this issue. I'll give it a go with your workaround.

I'll close this one for now.
