### ISSUE TITLE
[9.0] Incorrected plural form of the word "Active Users" in Settings, resulting in wrong translation

### ISSUE THREAD

**Issue by Khwunchai** [odoo/odoo#12469]
Impacted versions: 9.0

Steps to reproduce:
1. Load a translation, choose Thai language for example
2. Switch to the new language from User Preferences menu
3. Navigate to Settings Dashboard

Current behavior: 
In case of multiple active users, The word "Active Users" is translated into "ผู้เข้าใช้งานs" (with an extra letter "s") in Active User panel. This issue also persist with almost all languages.

Expected behavior:
In case of multiple active users, The word "Active Users" should be translated into "ผู้เข้าใช้งาน", the same word as the singular form due to some languages do not have plural forms.

This is caused by adding "s" at the end of the word directly from the template. This prohibits translators from translating the plural form in any language. Translators instead, have to translate "Active User" and "s" which makes no sense. The plural form and singular forms should be translate separately.

**Comment by Yenthe666** [comment]
@mart-e since you're all about languages and translations, this is something for you. If I understand this correctly we should have the ability to translate in a plural and singular form for Thai.

**Comment by elicoidal** [comment]
I have seen a similar report days ago.
Current implementation is not correct. In Chinese we have the same issue: adding a "s" does not make sense at all in many languages.

**Comment by Khwunchai** [comment]
#12470 This pull request should fix the problem.

**Comment by elicoidal** [comment]
Indeed

**Comment by mart-e** [comment]
Hello,

You are right, making these plurals is wrong. Thanks for the report and the patch, it has been fixed at a9ea4e7cab244f2a6527b9ea5bef4aefa4e486cf
The new translation will soon be available on Transifex
