### ISSUE TITLE
Odoo 9C: "Add an item" of One2Many behaviour is crazy. [BUG] 

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#12461]
Impacted versions:  Odoo 9 Community version

One2Many record gets created only when a value to any of M2O field is set. Until unless it is not set then odoo doesn't allow you to create that record.

For Instance: Consider the below example:

Line Object has only 3 fields (plus link to its parent object)

1. name (text - non mandatory)
2. qty (float - non mandatory)
3. comment (text - non mandatory)

Odoo did not allow me create this record. Hence, now I brought another field to this view,

4. uom_id (M2O - non mandatory)

Now after I brought this new field into the view, the minute I supplied a value to this uom_id which happened to a M2O, a record got created.

So by looking at these scenarios,  unless until you set any value to  any M2O field present in the O2M, odoo does not create that record.

So what if my lines doesn't have any M2O type field? then I can never create a record, which is utterly nuisance.

I don't understand why this kind of behaviour is implied, Anybody faced same kind of situation, How do we handle this.

**Comment by mart-e** [comment]
Hello,

Sorry but I am not sure to get your issue. I just tested and it works fine.

the model:
```python
from openerp import models, fields

class test(models.Model):
    _name = 'test.test'

    name = fields.Char()
    lines = fields.One2many('test.line', 'test_id')

class test(models.Model):
    _name = 'test.line'

    test_id = fields.Many2one('test.test')
    name = fields.Char()
    quantity = fields.Float()
    comment = fields.Text()
```
and the view
```xml
    <record model="ir.ui.view" id="test.list">
      <field name="name">test list</field>
      <field name="model">test.test</field>
      <field name="arch" type="xml">
        <form>
          <group>
            <field name="name"/>
            <field name="lines">
              <tree editable="top">
                <field name="name"/>
                <field name="quantity"/>
                <field name="comment"/>
              </tree>
            </field>
          </group>
        </form>
      </field>
    </record>
```

As you can see, I have no many2one in my view (I have one on the model obviously to have a working o2m) but if you test, you can add records.

**Comment by deepa4lok** [comment]
@mart-e Well you had understood my issue correctly, indeed I was unable to save the record in the version which I was working last week. However couple of days back I have pulled the latest version from Github, now it seems to work fine. Anyways appreciate your effort, Thanks.
