### ISSUE TITLE
[16] Issues with large attachments

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#124646]
**Impacted versions:**

16, 15

**Steps to reproduce:**

Add very big attachment to chatter or field with many2many_binary widget.

**Current behavior:**

- No information that file is being processed by server. User can leave page and than upload breaks.
- Upload fails when using many2many_binary widget.
- Huge CPU usage.

**Expected behavior:**

- Information that file is still being uploaded/processed.
- Block user from leaving current page while file uploads.
- No error with many2many_binary
- Lower CPU usage

**Error:**

```
2023-06-12 11:20:45,908 16093 ERROR odoo16 odoo.addons.web.controllers.binary: Fail to upload attachment file.7z 
Traceback (most recent call last):
  File "/home/gk/Software/odoo16/addons/web/controllers/binary.py", line 190, in upload_attachment
    'datas': base64.encodebytes(ufile.read()),
  File "/usr/lib/python3.9/base64.py", line 531, in encodebytes
    pieces.append(binascii.b2a_base64(chunk))
MemoryError
```

**Comment by vava-odoo** [comment]
Hi @grzekru 
Asking the help from @Julien00859 for this one.
Cheers,

**Comment by Julien00859** [comment]
I'll look into it, usually we suggest people to host their file using dedicated file-hosting services and then save them within Odoo via an url.
