### ISSUE TITLE
[8.0][stock] Only show products serial numbers availables for sale related to the stock location

### ISSUE THREAD

**Issue by lescobarvx** [odoo/odoo#12464]
**Impacted versions:**
- 8.0

**Steps to reproduce:**

**1.-** Create stockable product with Full Lots Traceability
![issue_01](https://cloud.githubusercontent.com/assets/16093067/16124095/857cb904-33bb-11e6-9978-58c5f707b435.png)
![issue_02](https://cloud.githubusercontent.com/assets/16093067/16124099/89552840-33bb-11e6-82d8-4fbf20015f89.png)

**2.-** Add a serial number in WH/Stock Location
![issue_03](https://cloud.githubusercontent.com/assets/16093067/16124139/ac681a2c-33bb-11e6-8c07-e51a4fc8234c.png)

**3.-** Create a sale order with this product and confirm sale

**4.-** VIew delivery order
![issue_04](https://cloud.githubusercontent.com/assets/16093067/16124231/1d1260d4-33bc-11e6-8ed0-fb2cb4a60a23.png)

**5.-** Check availability and Transfer
![issue_05](https://cloud.githubusercontent.com/assets/16093067/16124286/5f9e8cfc-33bc-11e6-80ff-091a1be3eb27.png)

**6.-** Add other serial number in WH/Stock Location
![issue_06](https://cloud.githubusercontent.com/assets/16093067/16124709/09d2252a-33be-11e6-9278-4c4ffa3a5a3a.png)

**7.-** Create another sale order with this product and confirm sale

**8.-** VIew delivery order, Check availability and Transfer

**9.-** Modified the Lot/Serial Number to check the proposed serial

**Current behavior:**
- Proposes a serial numbers found in the Customer Location

![issue_07](https://cloud.githubusercontent.com/assets/16093067/16124696/fcf46598-33bd-11e6-9adf-d2f72419b151.png)
![issue_08](https://cloud.githubusercontent.com/assets/16093067/16124811/a0ae62f6-33be-11e6-9fee-12f524d30a25.png)

**Expected behavior:**
- Only propose serial numbers availables for sale from Stock Location

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @lescobarvx,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
