### ISSUE TITLE
[9.0] All files in .tar.gz and .deb packages aren't up-to-date

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#12468]
Impacted versions: 9.0

Steps to reproduce: Install Odoo later than 9c007ac375f5ac34c911030bbedfe6f8a2a57a48 (June 3, 2016) from .tar.gz or .deb. Or [download them](http://nightly.odoo.com/9.0/nightly/deb/) and check their contents.

Current behavior: Not all files are up to date. For example [openerp/tools/misc.py](https://github.com/odoo/odoo/blob/9.0/openerp/tools/misc.py) isn't. I found this out by trying to install the 20160616 9.0 enterprise. Got the following stack trace:
```
2016-06-16 21:22:51,244 1 ERROR ? openerp.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 832, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo_addons_enterprise/web/__init__.py", line 8, in <module>
    import controllers
  File "/opt/odoo_addons_enterprise/web/controllers/__init__.py", line 1, in <module>
    from . import main, pivot
  File "/opt/odoo_addons_enterprise/web/controllers/main.py", line 40, in <module>
    from openerp.tools.misc import str2bool
ImportError: cannot import name str2bool
```

Expected behavior: All files in 9.0 branch should be in that installation and `openerp.tools.misc` should contain a `str2bool` function.

**Comment by Yenthe666** [comment]
@mart-e could you have somebody that creates the .tar.gz and .deb packages have a look at this?

**Comment by JKE-be** [comment]
@sle-odoo
Could you take a look asap?
It is not the first people... 
Same issue on the forum about login redirect ...
Thanks

**Comment by sle-odoo** [comment]
I just downloaded the latest 9.0c zip, tgz and deb and extracted them: str2bool is in place, line 569 of every misc.py.

**Comment by sle-odoo** [comment]
@mlaitinen you're pointing to the author date of rev 9c007ac375f5ac34c911030bbedfe6f8a2a57a48, but this patch was committed yesterday:
```
commit 9c007ac375f5ac34c911030bbedfe6f8a2a57a48
Refs: [9.0], {odoo/9.0}, {odoo/HEAD}
Author:     Damien Bouvy <dbo@odoo.com>
AuthorDate: Fri Jun 3 14:52:11 2016 +0200
Commit:     Damien Bouvy <dbo@odoo.com>
CommitDate: Thu Jun 16 17:29:41 2016 +0200
```

Also your bug report is from 10 hours ago, when today's packages were not build yet, so this change was not part of the builds. I checked that these changes are in the today's packages and they are, so i don't see any issue here.

Regards

**Comment by mlaitinen** [comment]
@sle-odoo If you download this: http://nightly.odoo.com/9.0/nightly/deb/odoo_9.0c.20160616.tar.gz and see `openerp/tools/misc.py`, line 569 is empty.
![screenshot from 2016-06-17 10 17 19](https://cloud.githubusercontent.com/assets/1525066/16143348/cead66aa-3474-11e6-8bf9-6297a926172a.png)

**Comment by sle-odoo** [comment]
@mlaitinen see my last message, the packaging are build the night so the changes in rev 9c007ac375f5ac34c911030bbedfe6f8a2a57a48 could not possibly be part of the package from yesterday (16) but they are in the packages from today (17).

**Comment by mlaitinen** [comment]
Ok. Thanks for the clarification.

**Comment by sdu-odoo** [comment]
ImportError: cannot import name content_disposition

after installing str2bool
