### ISSUE TITLE
The Manufacturing Order got stuck in Awating for Raw Materials state when the products in the bom have procure method make to order and buy and Propose a call for tenders			

### ISSUE THREAD

**Issue by SarathkumarJ** [odoo/odoo#12465]
Impacted versions:
currently running demo versions
Steps to reproduce:
Place an order with procure method MTO manufacture,
The bom should be of procure method make to order ,buy and Propose a call for tenders enabled 
Current behavior:
Mo is generated , Even if the entire process of tendering purchase, and reception of product get completed the Mo got stuck in a Awaiting for raw material state even if we click reserve button

Expected behavior:
state should be  ready to produce

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this still happening?
