### ISSUE TITLE
Error shown when using back button on iOS

### ISSUE THREAD

**Issue by cloudpepperio** [odoo/odoo#124658]
Impacted versions:

16.0

Steps to reproduce:

On iOS, using either Safari or Chrome
Visit odoo.com
Click on one of the links that stay on the same domain (eg we tested with Tutorials link in the footer)
Click on the browser back button

Current behavior:

Error shown
```
Unknown CORS error

An unknown CORS error occured.
The error probably originates from a JavaScript file served from a different origin.
(Opening your browser console might give you a hint on the error.)
```

Expected behavior:

previous page is shown

Video/Screenshot link (optional):

![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-12 at 14 14 59](https://github.com/odoo/odoo/assets/130058379/4f36adca-906a-415e-b034-7c157ca39cc1)

Support ticket number submitted via odoo.com/help (optional):

**Comment by cloudpepperio** [comment]
I think the error is misleading
https://github.com/odoo/odoo/blob/16.0/addons/web/static/src/core/errors/error_service.js#L86
Odoo shows a "CORS error" whenever there is no file/line number, but no clue what the actual error is

**Comment by netfxtech** [comment]
I’m also receiving this when browsing the help forums. 

https://github.com/odoo/odoo/assets/62037189/71e8fb59-cac5-4805-a0b2-df50c418d98a

**Comment by vava-odoo** [comment]
Hi @cloudpepperio 
Thanks for reporting. Seems like it is more related to iOS than Odoo.
Please find more information here: https://github.com/odoo/odoo/pull/124828
Best

**Comment by netfxtech** [comment]
I haven't tested the patches but it appears they should work. This is just my opinion, but in the future, it's probably not going to go over well suggesting this is an Apple problem unless it's easy to point to a multitude of other projects experiencing the same problem. Until they fix it, it's the responsibility of individual projects to deliver a good experience for iOS users. Unless users are getting the same error on google or any other high ranking site, the user will 100% blame the project. 

That's just my opinion. Easier to push a small patch than blame Goliath for any errors. I appreciate the link you provided because it helps me better understand the issue.

**Comment by cloudpepperio** [comment]
In my opinion, the fact that this is happening on iOS shouldn't be relevant. The issue is rather that Odoo is showing an intrusive error box whenever it detects an error on the page. But the error could have other causes than an iOS navigation error, eg it could also be caused by one of the third party trackers configured on the website, just to name one example.

Another issue is that Odoo has no clue what the error is about, and is just arbitrarily showing "CORS error" which is both irrelevant (the end user doesn't care) and misleading.

**Comment by netfxtech** [comment]
> In my opinion, the fact that this is happening on iOS shouldn't be relevant. The issue is rather that Odoo is showing an intrusive error box whenever it detects an error on the page. But the error could have other causes than an iOS navigation error, eg it could also be caused by one of the third party trackers configured on the website, just to name one example.
> 
> 
> 
> Another issue is that Odoo has no clue what the error is about, and is just arbitrarily showing "CORS error" which is both irrelevant (the end user doesn't care) and misleading.

100% - this is what I was thinking but had difficulty articulating. Thanks @cloudpepperio

**Comment by vava-odoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/124828

Thanks @cloudpepperio and @netfxtech for your inputs.
