### ISSUE TITLE
[hr_payroll]: Print menu not visible for PDF reports in list and form view

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#124745]
Impacted versions: Odoo enterprise version 16

Steps to reproduce: Install module hr_payroll (Payroll) and go to Payroll > Payslips > All Payslips, go to list view and select records, now you cant see print menu to print PDF reports from list view.

Current behavior: Not able to see print menu in list and form view to print base PDF report and custom PDF reports

Expected behavior: Print menu must always visible on list and form if any reports available for print

Video/Screenshot link (optional): https://www.awesomescreenshot.com/video/18260858?key=6948563af28cabd1c499cca1ed9e1f13

Support ticket number submitted via odoo.com/help (optional):

NOTE: I have tested everywhere in runbot,localhost,odoo.sh etc with and without demo data and without any custom addons. I have double checked with latest code and i am sure that its due to som bug in odoo enterprise code.

**Comment by kba-odoo** [comment]
Hi @hareshkansara 

This is not a bug, it's done on purpose [here](https://github.com/odoo/enterprise/blob/7cdc7b02a1fe7ca2bb264bfd3f01727ca6168e85/hr_payroll/models/hr_payslip.py#L895). This way we can use a different report template based on the report configured on the Salary Structure: 
![image](https://github.com/odoo/odoo/assets/50135801/c936d721-8d37-43f4-a5e5-c92d954138c2)


Instead to print you should use the PRINT button here - next to NEW:
![image](https://github.com/odoo/odoo/assets/50135801/7ccd60c1-fdf6-4d61-8f2f-eab73ee4dea0)

or here: 
![image](https://github.com/odoo/odoo/assets/50135801/5a73f3a3-02e4-4cb9-b579-484d8b29d721)

**Comment by hareshkansara** [comment]
Hello,

Thanks for your explanation. But what actually i posted is, when we add any new custom reports then it must show print menu near action menu. But its not showing. 

And the print button added near refund/new is only able to print 1 default report.

So whats the solution if added new PDF reports for payslip and want to print?

**Comment by hareshkansara** [comment]
@kba-odoo so can you reopen this issue plz and discuss more.

**Comment by kba-odoo** [comment]
@hareshkansara can you explain what is your use case that would require multiple reports for the same payslip?

There are many reports bound to hr.payslip and each for a specific structure, by showing all the reports it gets confusing for the users and will lead to errors.

Here's what it looks with the Belgian localization installed for example :-) 

![image](https://github.com/odoo/odoo/assets/50135801/cb182a03-0725-415a-9765-be1231633a78)

(cc @Geoffrey-GMF)

**Comment by hareshkansara** [comment]
Hi @kba-odoo 

Thanks for your message.

Actually i am checking for odoo version 16 enterprise and i have created custom report for payslip which is just for our internal usage and i want to print it from Print menu. That's the actual issue i am facing. because odoo should not block printing functionality.

I can understand that in payslip odoo added some condition to hide print menu and added separate print button but what i want is normal print menu for custom report.

That's why i consider this as a bug, because odoo dont block normal functionality like report menu. Now i am facing this issue

Could you help me to visible print menu same like you send V17 screenshot for belgium localisation?

Thanks

**Comment by gquilarque** [comment]
Hi @hareshkansara @kba-odoo 

I have the same error, the print button is not displayed on the payroll.

In odoo enterprise version 16, I need to print custom reports in payroll but the print button is not showing in the view.

I also enabled custom reports in Settings->Technical->Reports-> look for the custom reports and press the smart button: Add in the 'Print' Menu, I return to the payroll view and refresh, and the reports are still not displayed.

NOTE: I have tested everywhere in runbot,localhost,odoo.sh. Odoo version 16 enterprise.

**Comment by Abdulhai-Mohamed** [comment]
@kbapt seriously are you closing the issue just like this, dude told you he needed his custom report absed on his company requiremnets and you just say we have to hide all the prints.!!
why you didn't simply try to add boolean value to conditionally show the print in print menu depending on is is custom or from your default reports?

**Comment by Abdulhai-Mohamed** [comment]
@kbapt Seriously are you closing the issue just like this,
Dude told you he needed his custom report based on his company requirements and you just say we have to hide all the prints.!!
why you didn't simply try to add a boolean value to conditionally show the print in the print menu depending on whether it is custom or from your default reports?

**Comment by hareshkansara** [comment]
Thanks Niyas. Will try.

But @kbapt what are the possibility to add condition or something to display custom reports in print menu?

As @Abdulhai-Mohamed explain why we cant add condition or something to show print menu.

Thanks

**Comment by hareshkansara** [comment]
And please reopen as we need solution from odoo base.

Thanks
