### ISSUE TITLE
[9.0]Several Major Issues with Tenders

### ISSUE THREAD

**Issue by roadtripguy** [odoo/odoo#12477]
There are several pretty major issues with tenders.   

Reproduced this in several different configurations using both 9 Enterprise installed on my server and using your demo server at https://demo2.odoo.com

This is a very confusing bug, because the Tender DOES ultimately create incoming delivery orders.  However those Delivery Orders do not work.  I don’t know what would cause this.

Video: https://www.youtube.com/watch?v=7v14qgjMsMg

Impacted versions:
9.0 Enterprise
9.0sas

Steps to reproduce:
I have outlined several bugs below, but they may all be interrelated 

```
1.  Configuration:

   a.   Allow call for tender
   b.   Enable advanced call for tender
   c.   Enable Work Orders
   d.   Enable Advanced Routing of Work Orders
2.  Create an Assembly “Assembly 1”
   a.   Can be sold
   b.   Stockable
   c.   Manufacture
   d.   Make to order
3.  Create “Part A”
   a.   Can be bought
   b.   Stockable 
   c.   Buy
   d.   Make to order
   e.   Propose Call for Tender
4.  Create “Part B”
   a.   Can be bought
   b.   Stockable 
   c.   Buy
   d.   Make to order
   e.   Propose Call for Tender
5.  Create “Part C”
   a.   Can be bought
   b.   Stockable 
   c.   Buy
   d.   Make to order
   e.   Propose Call for Tender
6.  Create BoM for “Assembly 1”
   a.   Bom Lines:
      i.    QTY 1 – Part A
      ii.   QTY 1 – Part B
      iii.  QTY 1 – Part C
   b.   Create Routing with 3 steps
7.  Generate Sales order for 100 of assembly 1
8.  Confirm sale
9.  Run schedulers
10. Look at tenders
   a.   Possible Bug 1
      i.    Expected result:  One Call for tender with three items.  
      ii.   Actual Result: one call for tender for each item (three total)
      iii.  Explanation of problem: If a BoM consists of 100 parts.  When we send it out to bid to 15             different vendors that would result in 1,500 one line RFQ’s.  Does not seem logical to do it this way
11. Open Tender
12. Confirm Call
13. Possible Bug 2: (not in video)
   a.   Step:  Close Call for tender (Before selecting vendors)
   b.   Expected Result:  It should not allow you to close a call for tender before you have sent it for bid
   c.   Actual Result:  It closes call for tender with no warning.  There is also no way to reverse this
   d.   Explanation of problem:  Since there is no way to reverse this, you need to create an entire new tender since a call for tender without related RFQ’s is worthless.
14. Send Quote to multiple vendors
15. Close call for tender
16. Choose Product Lines
17. Select various amounts and generate POs
18. Repeat for all Tenders
19. Receive all Items
20. Possible bug 3:
   a.   Step: Look at Manufacturing order
   b.   Expected result:  Manufacturing order should say “Ready to produce”
   c.   Actual result: Manufacturing order still shows “Awaiting raw materials”
   d.   Explanation: Self explanatory
21. Open manufacturing order
   a.   Possible bug 4:
      i.    Expected Result: Inventory Items should not show in red
   b.   Possible bug 5:
   i.   Steps: Click Reserve
   ii.  Expected result: Inventory items should be reserved / moved from stock
   iii. Actual result: Nothing happens
22. Click on Work Orders tab of Manufacturing Order
23. Possible bug 6 (not in video):
   a.   Click on “Play” button next work order step
   b.   Click “Finish” on work order step
   c.   Repeat for all steps
   d.   Expected Result: Should not be able to start work orders if inventory is not reserved for manufacturing order
   e.   Actual Result: Work orders are able to be started and completed.  Resulting in completed assembly but no inventory consumed

```

**Comment by pedrobaeza** [comment]
Sorry, but the starting point is incorrect, as tenders don't create incoming shipments. Purchase orders do. Analyzing the rest of the things:

> Possible Bug 1
>       i.    Expected result:  One Call for tender with three items.  
>       ii.   Actual Result: one call for tender for each item (three total)

Well, this can be considered an improvement or an undesired behavior when you don't want to bid to everything together. I would go more for the possibility of adding the RfQ to an existing one.

> Possible Bug 2: (not in video)
>    a.   Step:  Close Call for tender (Before selecting vendors)
>    b.   Expected Result:  It should not allow you to close a call for tender before you have sent it for bid
>    c.   Actual Result:  It closes call for tender with no warning.  There is also no way to reverse this

This has been improved meanwhile. I invite you to check now the flow

> Possible bug 3:
>    a.   Step: Look at Manufacturing order
>    b.   Expected result:  Manufacturing order should say “Ready to produce”
>    c.   Actual result: Manufacturing order still shows “Awaiting raw materials”

Install procurement_jit for this.

The rest is working on my side, so I close this. If you still experiments some problems, please be more concise opening a new issue and going to the specific thing.
