### ISSUE TITLE
[8.0] Accessing request.env in ir_http.dispatch method seems to break environment

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#12474]
**Impacted versions:**
At least current 8.0, probably others. Website module installed and public user enabled.

**Steps to reproduce:**
Add `print request.env` in the `_dispatch` method of `ir_http` in `addons/website/models/ir_http.py`
I assume it actually happens everytime one evaluates `request.env`

**Current behavior:**
The environment "breaks" and never has an user attached (doing `request.env.user` returns empty recordset  `res.users()`) in any python method.

**Expected behavior:**
The environment works normally and has an user attached (at least it should be the public user)

**Comment by Yenthe666** [comment]
Hi @LeartS ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by popama** [comment]
> **Impacted versions:**
> At least current 8.0, probably others. Website module installed and public user enabled.
> 
> **Steps to reproduce:**
> Add `print request.env` in the `_dispatch` method of `ir_http` in `addons/website/models/ir_http.py`
> I assume it actually happens everytime one evaluates `request.env`
> 
> **Current behavior:**
> The environment "breaks" and never has an user attached (doing `request.env.user` returns empty recordset `res.users()`) in any python method.
> 
> **Expected behavior:**
> The environment works normally and has an user attached (at least it should be the public user)

I use Odoo 9.0 and I had same issue because I lost part of translations in public interface after I extended `_dispatch` method. I discovered that this issue is produced by request.env.

I found an interesting way to use request.env in the `_dispatch` method of `ir_http` from `addons/website/models/ir_http.py` as example in an existing module website_seo_redirection.

```
class ir_http(orm.AbstractModel):
    _inherit = 'ir.http'

    def _dispatch(self):
        obj = request.env['my.model'].sudo().search([])
        .....
        del request.env

        return super(ir_http, self)._dispatch()
```
