### ISSUE TITLE
Language setting not properly applied on email notification

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#12479]
Impacted versions: 9 Enterprise

Steps to reproduce:
Send a message via basic composer

Current behavior:
The language setting defined in the advanced tab (using an ISO code) is not properly working with the notification email template.
If an email is sent via the basic composer, the translation is not applied to the`record_name`.
If the email is sent via the full composer, the translation is properly applied to the`record_name`.

Expected behavior:
Translations should be applied to the`record_name` on both the basic composer and the full composer.

**Comment by Yenthe666** [comment]
@mart-e what do you think about this?

**Comment by mart-e** [comment]
I am thinking that I don't understand the issue. What do you call basic and full composer ?
I guess by "basic composer" you mean the chatter on a record but I don't see how email templates come into the picture.
Please elaborate.

**Comment by Yenthe666** [comment]
@avanzella could you give some more input please? Just to be sure we're talking about the same thing here.
