### ISSUE TITLE
[9.0E] Unable to archive contacts without developer mode activated

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12482]
Impacted versions: 9.0 Enterprise

Steps to reproduce:
1. Go to Contacts and open up a contact (without having developer mode on.) There is no "Archive" option available:
   ![image](https://cloud.githubusercontent.com/assets/6352350/16170641/ac072316-355a-11e6-8a1e-2ef1a88648cb.png)
2. Now activate developer mode and look at the exact same form:
   ![image](https://cloud.githubusercontent.com/assets/6352350/16170659/24f2fb4c-355b-11e6-9e8c-327c3a4ea5ef.png)

Current behavior:
You can't archive a contact without having developer mode activated, while you can archive all other items (such as projects) without developer mode activated.

Expected behavior:
You can archive a contact without having developer mode activated.

**Comment by Yenthe666** [comment]
@mart-e pinging you for this one, nothing to major.

**Comment by JKE-be** [comment]
@Yenthe666 
It has been already discuss in internal.
I don't remember the arguments... but when I got it, I ping you with more details.

**Comment by Yenthe666** [comment]
@JKE-be alright let me know when you know more. I'd find it a bit strange but I'm sure there is a good reason.

**Comment by Yenthe666** [comment]
@JKE-be any update?

**Comment by JKE-be** [comment]
For usability question, @apr-odoo could probably help you better than me ...

**Comment by mart-e** [comment]
The technical group was removed in 10.0 at 1fa6788.
