### ISSUE TITLE
patched hw_escpos/escpos/printer.py to support escpos printers with embedded thumb drives

### ISSUE THREAD

**Issue by royaladmin** [odoo/odoo#12485]
Impacted versions: 9.0

Steps to reproduce: posbox

Current behavior:

hw_escpos/escpos/printer.py correctly detaches any current kernel driver from the interface before claiming the device.  On our printer, vendor 0x6868 product 0x0600, there is an embedded thumb drive which holds the product windows driver and documentation.  The thumbdrive uses interface 1 while the printer uses interface 0.  From http://libusb.sourceforge.net/api-1.0/group__dev.html:

"You cannot change/reset configuration if other applications or drivers have claimed interfaces."

so I changed the code like this:

            # if self.device.is_kernel_driver_active(self.interface):
            #     self.device.detach_kernel_driver(self.interface)

            cfg = self.get_active_configuration(self.device)
            for intf in cfg:
                if self.device.is_kernel_driver_active(intf.bInterfaceNumber):
                    self.device.detach_kernel_driver(intf.bInterfaceNumber)

And then I could connect.  Also, the endpoint ID is #3 in my case, so added this hack:

            for intf in cfg:
                if intf.bInterfaceNumber == self.interface:
                    for ep in intf:
                        if ep.bEndpointAddress < 0x80:
                            self.out_ep = ep.bEndpointAddress   # change out_ep, calling sequence to be improved....

Now I am still hardcoded to interface 0, but I get whatever output endpoint is there.  Should likely do a whole scan for the correct Printer interface and then its output endpoint id.  Could change the calling sequence from main.py or auto-find the interface from a loop.  Interface 0 is working for me for now.

Expected behavior:

Video/Screenshot link (optional):

**Comment by royaladmin** [comment]
The EscPosDriver.connected_usb_devices.FindUsbClass() already does much of what is necessary to auto-detect the interface, just a question of passing it reasonably into printer.Usb().  I'm satisifed with my workaround for now and am not trying to be involved with changing calling sequences....
Gratitude again for your excellent software.

**Comment by Yenthe666** [comment]
@jorenvo what do you think about this?

**Comment by jorenvo** [comment]
Hi,

I'm glad you where able to make your particular hardware work with our driver. However, we currently only officially support the printers listed on the Odoo POS page [1]. We are forced to limit what printers we support because unfortunately there are quite a lot of differences between them, as demonstrated by the behavior of your printer. Currently none of the officially supported printers behave the way you describe (with an embedded thumb drive) which explains why you've run into this issue.

[1] https://www.odoo.com/page/point-of-sale-hardware


Kind regards,
Joren

/cc @mart-e

**Comment by royaladmin** [comment]
Makes sense to me.  As a final note in case others return here, I had to change my patch so it would function with both kinds of printers, standard ones or the one I found with the storage drive:
    try:
        cfg = self.get_active_configuration(self.device)
        for intf in cfg:
            if self.device.is_kernel_driver_active(intf.bInterfaceNumber):
                self.device.detach_kernel_driver(intf.bInterfaceNumber)
    except:
         self.device.detach_kernel_driver(self.interface)

Gratitude for building and making available such excellent software.

**Comment by gwasky** [comment]
Thanks Royal for the crack.. worked for me
