### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'context' in Odoo 16

### ISSUE THREAD

**Issue by pedro172023** [odoo/odoo#124888]
Impacted versions:
Odoo 16
Steps to reproduce:
Update module website from console
./odoo-bin -u website 
Update a custom module from the console that has the website dependency
./odoo-bin -u custom_module 
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/29467839/2f43a661-a553-44d9-8180-3a59077aeb9d)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @pedro172023 ,
i tried to reproduce the same as you have specified but didn't get the same trace back. only difference is i have passed the db name using -d , do you think that will make any difference.

thanks
