### ISSUE TITLE
Provide option to display company name of contact in parentheses or hide altogether

### ISSUE THREAD

**Issue by eronlloyd** [odoo/odoo#12483]
Impacted versions: 9.0c

Steps to reproduce: Add a contact/customer as an individual, then add them to a company.

Current behavior: The contact will have their name displayed many places as "Company, Individual" (see screenshots below).

Expected behavior: The contact would be more readable having either the format "Individual (Company)" or hiding the company name when possible, especially when it is shown elsewhere on the page, such as the contact view.

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/197778/16173566/f684962c-3572-11e6-9ba0-1d72a3798efa.png)

![image](https://cloud.githubusercontent.com/assets/197778/16173567/010e151e-3573-11e6-88e8-97189938797b.png)

**Comment by JKE-be** [comment]
Thank you for the reporting.
Because it is not really an issue, I tag this 'issue' as a wishlist and close this issue.

We will review later wishlist requests... and take the good idea for the next versions.

**Comment by eronlloyd** [comment]
I will try to provide a patch for this in the near future, once I'm more familiar with the codebase. It looks like it might be in a view template somewhere.
