### ISSUE TITLE
[17] l10n_es: improving and making all taxes more understable

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#124942]
Talked with @jco-odoo @omar7r @acysos in Valencia @chklop ( ping @HaraldPanten @pedrobaeza )

**Note: Don't create more taxes, update and fix existing ones.**

_Tip: ALL "Exento" are always "Sujeto" but "Sujeto" could be "No Exento" & "Exento" this issue we will talk about "Exento"_

### 1. Exento Article 20

`l10n_es.account_tax_template_s_iva0_ns` | "IVA Exento Repercutido No Sujeto"

- [ ] The new name for this TAX should be "**IVA Exento sin derecho a deducción**" (Art. 20), this tax is used in "Casilla 83" (special use)

@omar7r opinion is that we should keep this tax in the same way we are using in https://github.com/OCA/l10n-spain/blob/f9d1c3063d761a8e563987752de59ca85b58138b/l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml#LL832C1-L832C125 

> 83 Operaciones exentas sin derecho a deducción: se hará constar el importe de las operaciones exentas sin derecho a deducción, como las mencionadas en el artículo 20 de la Ley del IVA.

https://sede.agenciatributaria.gob.es/Sede/todas-gestiones/impuestos-tasas/iva/modelo-303-iva-autoliquidacion_/instrucciones.html

How to field the "Casilla 83"? (only in one case)

```
If "no exonerado 390" (ex. not in sii) then the amount of the whole year in "Casilla 83" will be in modelo 390 (a never in 303)

Else "exonerado 390" (ex. in sii) then, in the last period (only in the last one) of the year (12) the "Casilla 83" should be in 303
```

- [ ] Any case renaming this tax is critical because actualy say "no sujeto" which is a big mistake.
- [ ] All the taxes should have a "note" to print in the PDF of the invoice, is mandatory, saying that the invoice or some products of the invoice are "Taxes: Operation exempt from VAT by Article 20 of Spanish Law 37/1992, of December 28"

As Odoo SA have the "Article" of Exento in the tax, you need mandatory a tax per article, so if we already have Art. 20, where are the others? Let's go...

### 2. Exento Art. 21

Basically this tax is `l10n_es._account_tax_template_s_iva0_e` | "IVA 0% Exportaciones"

The name is confusion and in my opinion should be "**IVA Exento Exportaciones**" (Art.21) this tax is "Casilla 60"

- [ ] This sale invoices also need mandatory a note in the invoices (PDF) that says "Deberá incluir una referencia al artículo 21 de la Ley 37/1992 y/o indicar que la operación está exenta (art. 6.1.j) del Real Decreto 1619/2012, de 30 de noviembre)."

- La entrega está sujeta en el territorio de aplicación del IVA español pero exenta por ser una exportación, sin perjuicio de su sujeción al IGIC en Canarias de acuerdo con la Ley 20/1991 o al IPSI en Ceuta y Melilla según la Ley 8/1991.
- El exportador deberá presentar en la Aduana española la Declaración aduanera. Para ello, deberá disponer de un número de registro e identificación de los operadores económicos (número EORI) asignado por la autoridad aduanera.
- Asimismo, debe declarar la base imponible del impuesto en la casilla 60 del modelo 303, casilla 72 del modelo 322.
- La factura emitida no lleva IVA. Deberá incluir una referencia al artículo 21 de la Ley 37/1992 y/o indicar que la operación está exenta (art. 6.1.j) del Real Decreto 1619/2012, de 30 de noviembre).

### 3. Exento Art. 22

Well here is the disappointment because we have a Tax named:

`l10n_es.account_tax_template_s_iva0` | "IVA Exento Repercutido Sujeto"

And this tax could be used like a "Joker" (🃏)... so the only truth is:

- This tax is mapped to "Casilla 60" so for sure is not Art.20 and obviously also not Art.25.
- This tax cannot be also Art. 21 because then the tax is duplicated with the previous one.
- So the only options are Art. 22 ( @omar7r and me used as Art. 22) or Art. 23 or Art. 24. This 2 last art. are not very often (I have all cases 😄 ).

More...

- La entrega está sujeta pero exenta en el territorio de aplicación del IVA español, en los términos y condiciones del artículo 22.Uno.1º de la Ley 37/1992 y 148 de la Directiva 2006/112/CE, por ser una operación asimilada a una exportación.
- El proveedor debe declarar la base imponible del impuesto en la casilla 60 del modelo 303, casilla 72 del modelo 322, por lo que, si no está identificado en dicho territorio, tendrá que obtener un número de identificación fiscal español (NIF).
- La factura emitida con el NIF español no lleva IVA. Deberá incluir una referencia al artículo 22.Uno.1º de la Ley 37/1992 y/o indicar que la operación está exenta (art. 6.1.j) del Real Decreto 1619/2012, de 30 de noviembre).

Been diplomatic I would say:

- [ ] Rename "IVA Exento Repercutido Sujeto" for "IVA Exento" , general use with Exempt reason "Otros" (E6)
   - [ ] FIX `l10n_es_type is set` to "Exento"
- [ ] Create a new "IVA Exento Art. 22" for the ones need it like @omar7r and me.
- [ ] Spanish localization will need to decide how to use this tax as actually is for all articles i think except 20 and 25.

In my personal opinión this tax was created duplicated because the name of "IVA 0% Exportaciones" was incorrect. In accounting language and AEAT language use is Sujeto, Exento, No sujeto, Inversión del sujeto pasivo, etc...

### 4. Exento Art. 23

As said, every invoice exempt "Exento" is mandatory to include a note in the PDF explaining why is "Exento" so Art. 23 and Art. 24 have diferent notes. For this reason I would say

- [ ] Create a new tax "IVA Exento Art. 23"

### 5. Exento Art. 24

- [ ] Create a new tax "IVA Exento Art. 24"

### 6. Exento Art. 25

This is the case of Intracomunitary (Goods)

`l10n_es.account_tax_template_s_iva0_ic` | IVA 0% Entregas Intracomunitarias **exentas**

I talked with @pedrobaeza and he disagree in creating more taxes but Odoo SA don't have any option and will have to, because they need to identify the art. in the tax which in my opinion and the @omar7r opinion is the best way. As you see many PoV 😄 I usually take care only in Accountants, fiscal and auditors opinions like we are in Moduon and external auditor companies.

### Actually how i solved the situation?

I've created in private fiscal positions for Art. 20, Art. 22, Art. 24 and Art. 24. Nota: Art. 21 not needed is "Régimen Extracomunitario" and Art. 25 is not needed is "Régimen Intracomunitario"

@moduon MT-1616

### Other improvements or fixes:

- [ ] Fiscal position `l10n_es.1_fp_not_subject_tai` -> RENAME to "**Régimen No sujeto por reglas de localización (TAI)**"
- [ ] All taxes named with "Bienes the inversion" make `l10n_es_bien_inversion` TRUE
- [ ] For DUA and other stuff create a new tax "IVA No aplicable" which is not mapped anywhere and field `l10n_es_type is set` to "Ignore even the base amount"
- [ ] Odoo SA was wrong the tax grid of `l10n_es.account_tax_template_s_iva_e` should be 120 and not 122: la prestación de servicios extracomunitaria is "no sujeta" and 122 is for sujetas con Inversión del sujeto pasivo
   - La operación no está sujeta en el territorio de aplicación del IVA español.
   - El prestador del servicio debe declarar la operación como no sujeta al IVA por reglas de localización, consignando la base imponible en la casilla 120 del modelo 303 o modelo 322.
   - La factura emitida no lleva IVA.
- [ ] Duplicated taxes, both are the same "No sujeto (servicios)" por reglas de localización.
   - `l10n_es.account_tax_template_s_iva_e` | "IVA 0% Prestación de servicios extracomunitaria"
      - Used in fiscal position `l10n_es.fp_extra`
   - `l10n_es.account_tax_template_s_iva_ns` | "No sujeto Repercutido (Servicios)"
      - Used in fiscal position `l10n_es.fp_not_subject_tai`
   - https://github.com/OCA/l10n-spain/issues/3011
![imagen](https://github.com/odoo/odoo/assets/8736623/cfffab32-167c-49d9-b09b-33db91632581)

This is just an issue, up to you! After hours and hours this could be the last effort to make Odoo Accountderstable 😄 

Regards

**Comment by chklop** [comment]
Hello @rafaelbn? I plan to this following your feedback, do we agree ?

1. Tax l10n_es.account_tax_template_s_iva0_ns | "IVA Exento Repercutido No Sujeto"
	​=> Rename to IVA Exento sin derecho a deducción

2. Tax l10n_es._account_tax_template_s_iva0_e | "IVA 0% Exportaciones"
	​=> Rename to IVA Exento Exportaciones

3. Tax l10n_es.account_tax_template_s_iva0 | "IVA Exento Repercutido Sujeto"
	​=> Rename to IVA Exento (Otros)
	=> l10n_es_type : Exento
	=> l10n_es_exempt_reason : [E6] Otros

4. Create new tax, copy l10n_es.account_tax_template_s_iva0, with these changes :
	​=> Name: IVA Exento (Art. 22)
	=> l10n_es_type : Exento
	=> l10n_es_exempt_reason : Art. 22
	​=> Active = false

5. Create new tax, copy l10n_es.account_tax_template_s_iva0, with these changes :
	=> Name: IVA Exento (Art. 23)
	=> l10n_es_type : Exento
	=> l10n_es_exempt_reason : Art. 23 y 24
	​=> Active = false

6. Create new tax, copy l10n_es.account_tax_template_s_iva0, with these changes :
	=> Name: IVA Exento (Art. 24)
	=> l10n_es_type : Exento
	=> l10n_es_exempt_reason : Art. 23 y 24
	​=> Active = false​

7. All those taxes should have l10n_es_bien_inversion = true, the others should be false
![image](https://github.com/odoo/odoo/assets/93644924/47cbaec8-3795-4846-b047-9e8f78be20bf)

8. Tax l10n_es.account_tax_template_s_iva_e | "IVA 0% Prestación de servicios extracomunitaria"
	​=> Tax grid is incorrect and should be mod303[120]

9. Delete tax l10n_es.account_tax_template_s_iva_ns | "No sujeto Repercutido (Servicios)" and replace any reference to it in Fiscal Positions to l10n_es.account_tax_template_s_iva_e | "IVA 0% Prestación de servicios extracomunitaria"

10. Change Fiscal position l10n_es.1_fp_not_subject_tai name to Régimen No sujeto por reglas de localización (TAI)

Furthermore :
- I'm currently working on a task to add a "Note" field on Taxes that would add notes to Invoices, not only on Fiscal Positions (which is the only thing you can do now). This would allow doing what you suggest above on some taxes, we'll to it afterwards.
- I let the DUA part on the side for now

**Comment by pedrobaeza** [comment]
Just one quick remark. Sometimes "IVA 0%" is not the same than "IVA exento". Spanish AEAT distinguishes 3 types of lack of VAT: not subjected, exempt, or null (0%). Not sure if it's the case, but just for your knowledge.

**Comment by chklop** [comment]
Hello @pedrobaeza yes we were discussing that with @jco-odoo this morning, so we are leaning towards not doing point 9. above, I'll update my comment.

**Comment by rafaelbn** [comment]
Hello @chklop , back from holidays

> Hello @rafaelbn? I plan to this following your feedback, do we agree ?

I agree

**Comment by jco-odoo** [comment]
Working on it in https://github.com/odoo/odoo/pull/139514

**Comment by rafaelbn** [comment]
Then, ¡closing issue!
