### ISSUE TITLE
Unit price in Suggested products tab doesn't take the customer pricelist

### ISSUE THREAD

**Issue by PagliucaElisa** [odoo/odoo#12492]
Impacted versions: Odoo 8.0

Steps to reproduce:
1) Create a sale pricelist based on product cost price ;
2) link the pricelist to the customer; 
3) create a quotation; 
4) insert a product into "order lines "tab
5) insert the same product into "suggested products"tab 

Current behavior:
 Product Unit price into "suggest products" tab doesn't take customer pricelist rule.
Expected behavior:
Product Unit price into "suggest products" tab takes customer pricelist rule.
Video/Screenshot link (optional):
**Pricelist creation:** 
![image](https://cloud.githubusercontent.com/assets/19547990/16191773/2db3ea34-36e6-11e6-81dd-9093b74d13cd.png)

**Link the pricelist to a customer:** 
![image](https://cloud.githubusercontent.com/assets/19547990/16191842/80b72b56-36e6-11e6-957f-f813583e14a7.png)

**Create the quotation**
Insert product into "order lines" tab
![image](https://cloud.githubusercontent.com/assets/19547990/16191926/f2d27eb6-36e6-11e6-8ac9-1b70afbc1113.png)

Insert product into "suggested product"

![image](https://cloud.githubusercontent.com/assets/19547990/16191964/1c6f1ce8-36e7-11e6-97d8-ad1af35a8792.png)

The same product has two different unit prices beacause in "order lines" takes the 25% of discount setted into customer pricelist, while into "suggested products" no.

**Comment by Yenthe666** [comment]
Hi @PagliucaElisa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
