### ISSUE TITLE
[8.0] Impossible to change stage of an hr.applicant coming from hr.job 

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#12494]
Impacted versions:
8.0
Steps to reproduce:
* Go to runbot and connect as admin user
* Into Human Resources/Recruitment/Stages assure that stage has an associated template. For this exemple, take "First Interview"
* Into Human Resources/Applications delete all job Applications
* Click on Job Positions and click on the first hr.job and create an hr.applicant for it (+ keep in mind the related hr.job for the next steps)
* Change access rights of demo
 user from hr user to hr manager
* Connect now with demo user
* Go into human resources/job positions and click on the hr.job concerned into the previous points
* Now try to move this applicant from "Initial Qualification" to "First Interview"

Current behavior:
![selection_019](https://cloud.githubusercontent.com/assets/7601731/16193654/c2099b52-36f0-11e6-9a19-6bb19437908c.png)

Expected behavior:
The hr.applicant is correctly set into "First Interview" without any errors

Tips:
It is due to the fact that the active_id is propagated into the click from the hr.job kanban to the hr.applicant and then the mail.compose.message that actually is mail.message failed to confirm the check access rule because no res_id found into the database: the search is made with model=='hr.applicant' && res_id from 'hr.job'. I think it is a more global issue of the active_id passed  from models to models

Thanks for the fix!

Jonathan

**Comment by JonathanNEMRY** [comment]
OPW 681349

**Comment by JonathanNEMRY** [comment]
Any news about this issue?

**Comment by JonathanNEMRY** [comment]
Any news about this issue?

**Comment by Yenthe666** [comment]
@mart-e and @JKE-be can you guys give some feedback to @JonathanNEMRY please?

**Comment by JonathanNEMRY** [comment]
Is there something done about this one? sadly I have no feedback at all

**Comment by Yenthe666** [comment]
@JonathanNEMRY usually when nobody replied on and nobody is being assigned there is nothing done with the issue, so I'm afraid not.. I can't do much more either, sorry.

**Comment by JKE-be** [comment]
If you have an OPW that is open, you will have an answer from the Support Team... don't worry about it.

**Comment by mart-e** [comment]
Hello,

The issue is not with the propagation of the active_id (which is correct I think, it represent the record you were coming from, the hr.job).
The problem was that it was not taken care of during the composer, where we already did something for active_id**s** but not active_id.
Done at 64b0e67a3869df3ffd112c2bcbc40d69b3f03c35

Thanks for the detailed report and analysis

**Comment by JonathanNEMRY** [comment]
Thank you all
