### ISSUE TITLE
[IMP] Sale: Track products to Sales order

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#124949]
Step to reproduce:

Make a quotation of a product, confirm order, go to products, select the product used in the quotation, then select the tap "x units sold", select the date, open the sale info, click in the sales order number (S0xxx).

Current behavior:

Don't do nothing (because it's only text), I need to copy the order number and search it manually.

Expected behavior:

Redirect to the sales order.(like a link)

PD: the same was happening with the purchases (X units purchased) in V15, in V16 works like expected.

**Comment by vava-odoo** [comment]
Hi @chapital 
When you are on the sale analysis and click on the SO, you see a detailed view of the information of it. On the bottom right, you get the 'Order #' as a clickable link (see screenshot).
![image](https://github.com/odoo/odoo/assets/112173839/0a49b6f4-b501-4e41-9af4-44bfa2614d9e)
Cheers,

**Comment by chapital** [comment]
Thanks, only a recommendation its change the position, at the start of the document and maybe in bold letter (**Order #**).

Before the order reference.

Because the easy access to traceability.

@vava-odoo
