### ISSUE TITLE
UncaughtPromiseError > TypeError Uncaught Promise > Cannot read properties of null (reading 'reject')

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#125086]
Impacted versions: v16

Steps to reproduce:
- Create a order and typing a product name on the order line

Current behavior:
- Randomly throws the error
![image003](https://github.com/odoo/odoo/assets/14229503/297f563d-0b96-41e4-ab81-deabecd1f759)

Expected behavior:
- It should search record without any issue.

Support ticket number submitted via odoo.com/help: #3372451

May be this commit affect: https://github.com/odoo/odoo/pull/122143

**Comment by bodedra** [comment]
PR Ref: https://github.com/odoo/odoo/pull/124700

**Comment by niyasraphy** [comment]
fixed in: https://github.com/odoo/odoo/commit/a750e61544138a9d533f3391fbd2a179697fd7b4

**Comment by bodedra** [comment]
> fixed in: [a750e61](https://github.com/odoo/odoo/commit/a750e61544138a9d533f3391fbd2a179697fd7b4)

Thanks for your fix.

**Comment by spadae22** [comment]
I have these same errors on V14 still, on sales order line found on forum here: https://www.odoo.com/forum/help-1/getting-js-javascript-error-while-editing-sale-order-line-quickly-207256
