### ISSUE TITLE
nightly.odoo.com SSL cert expired

### ISSUE THREAD

**Issue by alambike** [odoo/odoo#12505]
Impacted versions:
all

Steps to reproduce:
visit https://nightly.odoo.com

Current behavior:
Certificate expired

Expected behavior:

Video/Screenshot link (optional):
![captura de pantalla de 2016-06-20 21 09 11](https://cloud.githubusercontent.com/assets/1025564/16207008/59655fe2-372b-11e6-86c0-c870d2d1fcd9.png)

**Comment by JKE-be** [comment]
Hello,

Thanks for the reporting
I have just updated the certificate.
