### ISSUE TITLE
Treeview on Accounting Customer Invoices shows total including cancelled invoices

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#12506]
Impacted versions:
9.0e
Steps to reproduce:
Accounting-> customer invoices-> group by (partner)
Current behavior:
Total for customer includes invoices that have been cancelled
Expected behavior:
Cancelled invoices should not be counted in total for the customer
Video/Screenshot link (optional):
![screen shot 2016-06-20 at 4 09 12 pm 2](https://cloud.githubusercontent.com/assets/8355352/16213063/715fc27e-3701-11e6-96d7-0120e00367b1.png)

**Comment by fpodoo** [comment]
We think it's normal that the "group by" feature analyse all lines according to the filter you applied on the screen or not. If you do not want the cancelled invoices, add a filter to not include invoices having state==cancelled. (you can even set this filter as a default for all users if you prefer working like this)
