### ISSUE TITLE
Quant value does not change when invoice is different than SO.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#12504]
Impacted versions:
9.0e
Steps to reproduce:
Create PO, receive invoice for PO at higher price than PO.  Receive products, check inventory valuation.
Current behavior:
Quant value is generated from PO.
Expected behavior:
Quant value should be what the invoice states.
Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
This is a duplicate of #16441, please see my answer on this issue.

Regards
