### ISSUE TITLE
[15.0] Salary contract simulation is broken if BE payroll localization is not installed

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#125065]
Impacted versions: 15.0

Steps to reproduce: Install `hr_contract_salary_payroll` without `l10n_be_hr_payroll`

Current behavior: There is an error that `standard_calendar_id` field is not available on a contract when opening contract simulation on a portal

After commit https://github.com/odoo/enterprise/commit/624f137ae77cfc12ff23e0c1a82bc8d2ee1f6d96 `standard_calendar_id` field is supposed to be on a contract model however it is added only in [l10n_be_hr_payroll module]( https://github.com/odoo/enterprise/blob/15.0/l10n_be_hr_payroll/models/hr_contract.py#L89)

Expected behavior: no error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mehjabinfarsana** [comment]
Hi @lem8r ,
Thanks for reporting the issue, fixed by https://github.com/odoo/enterprise/commit/86cd6fa0eee0c20e470abe3d64492ad6f68470b0
