### ISSUE TITLE
Salary Package dialog has € sign hardcoded

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#125171]
Impacted versions: 15.0, 16.0

Steps to reproduce: Install hr_contract_salary_payroll. Open contract simulation link. Click on details on salary sidebar.

Current behavior: Dialog window has [EUR sign hardcoded](https://github.com/odoo/enterprise/blob/16.0/hr_contract_salary_payroll/static/src/xml/brut2net_modal.xml#L22).

Expected behavior: Dialog window should respect company currency.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @lem8r ,
thanks for reporting and it has been fixed with this commit:  https://github.com/odoo/enterprise/commit/58ea78104ed669a84636f6be83ca49401800e57d

**Comment by lem8r** [comment]
Thank you!
