### ISSUE TITLE
error with odoo13 not running 

### ISSUE THREAD

**Issue by murayajoe** [odoo/odoo#125213]
Impacted versions: odoo13

Steps to reproduce: i moved an odoo 13 server file to my local pc to modify

Current behavior: still not running on pycharm or terminal

Expected behavior:

Video/Screenshot link (optional): the error i am getting is: psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket? - - -
 
Support ticket number submitted via odoo.com/help (optional):12
[README.md](https://github.com/odoo/odoo/files/11757783/README.md)

**Comment by niyasraphy** [comment]
hi @murayajoe ,
as it is a configuration issue and not a bug in odoo, you have to use help forums: https://www.odoo.com/forum/help-1
see if you have PostgreSQL installed and running in your machine.

thanks
