### ISSUE TITLE
[8.0, 9.0] Impossible to apply non-deductible taxes

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#12526]
Impacted versions: 8.0, 9.0 community, 9.0 Enterprise

Steps to reproduce:
At this point there is no option in Odoo to create an invoice that has non-deductible taxes on the product lines. I'll try to explain this in a usecase.
Let us say we buy a product for 100€ without taxes and that there are 21% taxes that need to be applied on the product. This means the product will cost 121€ (100€ without taxes + 21€ in taxes = 121€).
In Belgium however you can have products that have non-deductible taxes and it is a legal requirement to be able to record this in the accounting.
Imagine that the taxes are only 50% deductible for this product. You should get the following accounting entries:
- €110.50 on the 600000 ledger. (product price without taxes plus the non deductable part of the taxes)
- €10.50 for the taxes on the 411000 ledger.
- €121,00, the total amount, on the 440000 ledger.

At this point there is no way to do this in Odoo at the moment while this is mandatory by belgian law.
Documentation explaining this: http://www.taxexpert.be/bestand/Beperking%20aftrekbaarheid%20BTW%20-%206.pdf
Official government statements: http://ccff02.minfin.fgov.be/KMWeb/document.do?method=view&id=e154233d-dc0e-4c0f-9bbf-afc79e797448#findHighlighted

Current behavior:
There is no way to apply non-deductible taxes in Odoo.

Expected behavior:
You're able to apply non-deductible taxes on products and seperate entries are done on the correct journals.

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look at this?
@mart-e FYI. This is the issue I was talking about yesterday.

**Comment by sbidoul** [comment]
@Yenthe666 in my experience it is possible to have non-deductible taxes in 8.0 and 9.0.

But in 9.0 there is a nasty bug that appear when you have complex invoices: #12561

**Comment by Yenthe666** [comment]
@sbidoul could you explain me how to create non-deduductible taxes? Up untill now we haven't found a way to do it properly.

**Comment by sbidoul** [comment]
@Yenthe666 Just leave the tax account empty in the tax configuration. Such as this:

![image](https://cloud.githubusercontent.com/assets/692075/16329779/e6e5352a-39e4-11e6-8312-cc12d6060a3c.png)

**Comment by treviser** [comment]
In Switzerland we do have flat tax regimes for companies with particular qualifications. This means that a company has to pay a flat VAT rate on all sales, but is not allowed to deduct any VAT on purchases, which is more or less the same issue.
I do not leave the tax acount empty in this case, instead I assign the corresponding base expense account. I did not investigate it indepthly,  but wouldn't that maybe solve the issue?

**Comment by qdp-odoo** [comment]
yes it's totally possible to do that in Odoo, v8 or v9. Just install l10n_be and look at the tax "Frais de voiture - VAT 50% Non Deductible"

```xml
 870         <record id="attn_VAT-IN-V82-CAR-EXC-C1" model="account.tax.template">
 871             <field name="sequence">721</field>
 872             <field name="description">VAT-IN-V82-CAR-EXC-C1</field>
 873             <field name="name">Frais de voiture - TVA 50% Non Deductible</field>
 874             <field name="refund_account_id" ref="a64012"/>
 875             <field name="account_id" ref="a64012"/>
 876             <field name="price_include" eval="0"/>
 877             <field name="amount">10.5</field>
 878             <field name="amount_type">percent</field>
 879             <field name="type_tax_use">none</field>
 880             <field name="chart_template_id" ref="l10nbe_chart_template"/>
 881             <field name="tag_ids" eval="[(6,0,[ref('tax_tag_82_not_deductible'), ref('tax_tag_85_not_deductible')])]"/>
 882         </record>
 883         <record id="attn_VAT-IN-V82-CAR-EXC-C2" model="account.tax.template">
 884             <field name="sequence">722</field>
 885             <field name="description">VAT-IN-V82-CAR-EXC-C2</field>
 886             <field name="name">Frais de voiture - TVA 50% Deductible (Prix Excl.)</field>
 887             <field name="refund_account_id" ref="a411059"/>
 888             <field name="account_id" ref="a411059"/>
 889             <field name="price_include" eval="0"/>
 890             <field name="amount">10.5</field>
 891             <field name="amount_type">percent</field>
 892             <field name="type_tax_use">none</field>
 893             <field name="chart_template_id" ref="l10nbe_chart_template"/>
 894             <field name="tag_ids" eval="[(6,0,[ref('tax_tag_63'), ref('tax_tag_59')])]"/>
 895         </record>
 896         <record id="attn_VAT-IN-V82-CAR-EXC" model="account.tax.template">
 897             <field name="sequence">720</field>
 898             <field name="description">VAT-IN-V82-CAR-EXC</field>
 899             <field name="name">TVA Entrant - Frais de voiture - VAT 50% Non Deductible (Price Excl.)</field>
 900             <field name="price_include" eval="0"/>
 901             <field name="amount">1</field>
 902             <field name="amount_type">group</field>
 903             <field name="type_tax_use">purchase</field>
 904             <field name="children_tax_ids" eval="[(6, 0, [ref('attn_VAT-IN-V82-CAR-EXC-C1'), ref('attn_VAT-IN-V82-CAR-EXC-C2')])]"/>
 905             <field name="chart_template_id" ref="l10nbe_chart_template"/>
 906             <field name="tag_ids" eval="[(6,0,[ref('tax_tag_82'), ref('tax_tag_85'), ref('tax_tag_63'), ref('tax_tag_59')])]"/>
 907         </record>

```
