### ISSUE TITLE
SEO: Separating H1 and URL

### ISSUE THREAD

**Issue by fczaja** [odoo/odoo#12529]
## Impacted versions
- 9.0
## Goal

Independent work of H1 and URL must be possible.
Both elements must not be influenced by changes.
## Reason

It is normal that changes the H1 for various reasons.
The change of H1 but may not lead to change in the URL because it is very important for search engine optimization. Changes have a 404 error or a 301 Redirect result. Both should be avoided if possible.
The URL can sometimes from SEO reasons a different name than the H1.
## Current behavior Odoo 9

If the H1 changed then the URL changes. Conversely, the H1 is changed when changing the URL.
## Expected behavior

If you change the H1, the original URL not changed.
Inserting an additional field for changing the URL.
When changing the URL does not change the H1.
## This information is available

https://github.com/odoo/odoo/issues/12527
https://github.com/blooparksystems/website/tree/9.0/website_seo
https://github.com/odoo/odoo/issues/9774

**Comment by rafaelbn** [comment]
:+1:

**Comment by zeroheure** [comment]
The [website_seo_redirection](https://github.com/OCA/website/tree/10.0/website_seo_redirection) module from OCA can be used to do that.

**Comment by jholze** [comment]
@zeroheure sure but its really unsexy for the user who manages the website. We try to add all of this stuff to the promote panel.

**Comment by pedrobaeza** [comment]
I think the terminology used in this issue is not correct: instead of talking of page title, it's talking about H1. Any way, on Odoo v11, you can change the title of the page, but preserving previous URL, so this can be considered as done, and thus I'm closing this issue.
