### ISSUE TITLE
SEO: Insert Robots meta-tag

### ISSUE THREAD

**Issue by fczaja** [odoo/odoo#12528]
## Impacted versions
- 9.0
## Goal

Each side must individually via meta-tags as "noindex, follow" and "index, follow" to control his at the search engines to index the permit or prohibit.
## Reason

The most important reason for the manual change the meta-tags is that unimportant pages are not intended to enter the index of search engines. Furthermore, so difficult subject can also be excluded from indexing.
## Current behavior

Currently there is no standard way to prevent the indexing of pages.
## Expected behavior

Inserting an additional field in the "Optimize SEO" panel.
The following meta Robots statement should be possible

```
<meta name = "robots" content = "index, follow">
<meta name = "robots" content = "index, nofollow">
<meta name = "robots" content = "noindex, follow">
<meta name = "robots" content = "noindex, nofollow">
```
## This information is available

https://github.com/odoo/odoo/issues/12527
https://github.com/odoo/odoo/issues/12128
https://github.com/odoo/odoo/issues/8246

**Comment by pedrobaeza** [comment]
@JKE-be is there something in the roadmap for having the possibility of robot meta-tags?

**Comment by JKE-be** [comment]
It has been partialy done in v11.

You can now specify on a page if if you want a "noindex, nofollow" automatically.
That is the most frequent case, others are more technical choice than end user choice.

**Comment by pedrobaeza** [comment]
Right, I see the indexed one.

![seleccion_006](https://user-images.githubusercontent.com/7165771/39294687-a24eec08-493c-11e8-8f09-2a3040c9aafc.png)

But I don't see the no follow one. Where is it?

**Comment by JKE-be** [comment]
implicit: if not indexed, no-index, no-follow

**Comment by Yenthe666** [comment]
Or make it one more option in this view? "Followed"

**Comment by JKE-be** [comment]
nofollow is probably obvious for most of user.
We prefer to dont make the ui complex.

Don't display a page in google is easy to understand for all users.
No-Follow is technical and in most case, you want "index,follow" (default)
or "nonindex,nonfollow".

Let me know 1 page on your website where you do no-index, follow ;)
