### ISSUE TITLE
Feature Request: Ability to customize invoices and purchase orders

### ISSUE THREAD

**Issue by c0fe** [odoo/odoo#125224]
A good feature to add is for users to be able to import/create their own templates for Invoices and Purchase Orders. This can be done to some degree on Quickbooks Desktop and much greater ability in their Quickbooks Online version. Currently there are 4 templates to pick but very little in terms of moving fields around, importing background fields that could be prefilled.

The suggestion is to permit the importation of PDF to use as the background template and have fields that can be moved around the user to setup the invoice and purchase order documents as they want to. This can be expanded to other documents like request for quote.

**Comment by gdgellatly** [comment]
It is a feature in enterprise in terms of moving/adding fields etc to reports/views. Backgrounds in odoo are just png files, which presents limitations.  For PDF backgrounds - this may help https://github.com/OCA/reporting-engine/tree/16.0/report_qweb_pdf_watermark. 

The 4 report templates are easily modified/enhanced added to in code, either dev or through UI, not sure about enterprise options here. From memory, layouts consist of a main template which calls a header/footer for one of the 4 as well as loading a specific css file (which can be custom per company and edited per company)

**Comment by c0fe** [comment]
> It is a feature in enterprise in terms of moving/adding fields etc to reports/views. Backgrounds in odoo are just png files, which presents limitations. For PDF backgrounds - this may help https://github.com/OCA/reporting-engine/tree/16.0/report_qweb_pdf_watermark.
> 
> The 4 report templates are easily modified/enhanced added to in code, either dev or through UI, not sure about enterprise options here. From memory, layouts consist of a main template which calls a header/footer for one of the 4 as well as loading a specific css file (which can be custom per company and edited per company)

that's a basic feature, strange that they would push into enterprise. I could issue a PR with that added in.

**Comment by gdgellatly** [comment]
Well only if you want to do in a UI, drag/drop styles. Honestly, all this stuff is simple without enterprise. I mean, you could import templates, just through a standard import mechanism in community. But report layouts are just views with css applied, and often inherited by other modules etc, not like a quickbooks where there is a fixed data model. In general, this stuff is best done in code, and most Odoo implementations have a custom layout. It's not exactly rocket surgery and to be honest, by the time you get 10 templates deep in inherited sale order layouts, it is generally easier to start from scratch anyway.

**Comment by c0fe** [comment]
@gdgellatly do you have a tutorial on the code method handy by chance?

**Comment by gdgellatly** [comment]
https://www.odoo.com/documentation/16.0/developer/tutorials/pdf_reports.html
https://www.odoo.com/documentation/16.0/developer/reference/backend/reports.html#reference-reports-report

To be honest I never read them. I've been doing this since the entire Odoo documentation was 2 (great) pages of printed A4. But generally anything in Odoo which is in an xml file (except in static dir) can be done manually in UI, not that I recommend it, but XML Records are just database records.

Layouts are copied and attached per company and applied using a weird t-attf-class or something when report.layout is called, essentially the CSS is company specific per template class.

**Comment by vava-odoo** [comment]
Hi @c0fe 
Did you get the answer you were looking for from @gdgellatly (thanks!) ?
Cheers,
