### ISSUE TITLE
[8.0]How to set all fields in form view to read-only after setting state to confirmed [WORKFLOW]

### ISSUE THREAD

**Issue by blutec-ma** [odoo/odoo#12537]
Hello all,

I need to know what command to add to the transition of DRAFT > CONFIRMED state of a document in ODOO-8 to make all fields READ ONLY.
I've attached an image below to see the fields that can be edited even though the state is confirmed.

I'm new to GITHUB, thanks alot and i await replies 

Impacted versions:8.0

Steps to reproduce:

Current behavior:

![capture22-06-2016](https://cloud.githubusercontent.com/assets/19782436/16265457/f88d3b14-386e-11e6-823f-cd0f5904adf3.PNG)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @blutec-ma,

Github is only used for issues with the source code from Odoo, this is not considered the place to ask questions regarding development. If you have such questions in the future please post them on help.odoo.com, where a lot of people can help you!
To answer your question: you can do this with attributes on a field. A raw example:
`<field name="example_field" attrs="{'readonly': [('type', '=', 'confirmed')]}"/>`

**Comment by blutec-ma** [comment]
Thanks a lot @Yenthe666 ,

**Comment by blutec-ma** [comment]
By the way: the correct code is: (state instead of type)

<field name="field_name" attrs="{'readonly': [('state', '=', 'confirmed')]}"/>

**Comment by blutec-ma** [comment]
`<field name="field_name" attrs="{'readonly': [('state', '=', 'confirmed')]}"/>`
