### ISSUE TITLE
SEO: Short URLs

### ISSUE THREAD

**Issue by fczaja** [odoo/odoo#12531]
## Impacted versions
- 9.0
## Goal

Directories in the URL as (shop/product/) or (page/) there should not be.
Second directory as (help-1) or (our-blog-1) should not exist:
forum/help-1
blog/our-blog-1

> Note: It should still remain the possibility that a website operator can insert an additional directory level.
## Reason

URLs should never contain unnecessary directories.
Sites that are deeper in the directory level appear unimportant for search engines.
The important URL should be visible in the search results pages of search engines like Google.
## Current behavior Odoo 9

Odoo Online Shop Product URL
domain.de/shop/product/imac

Odoo Online Shop Category URL
domain.de/shop/category/computers-12

Odoo URL normal pages
domain.de/page/first-site

Odoo Blog URL
domain.de/blog/our-blog-1
domain.de/blog/our-blog-1/post/

Odoo Forum
domain.de/forum/help-1
## Expected behavior

All URLs should be reduced to the bare minimum.

Odoo Online Shop Product URL
domain.de/imac

Odoo Online Shop Category URL
domain.de/computers
domain.de/tablets

Odoo URL normal pages
domain.de/first-site

Odoo Blog URL
domain.de/blog
domain.de/news-blog

Odoo Forum
domain.de/forum
domain.de/forum-help
## This information is available

https://github.com/odoo/odoo/issues/12527

**Comment by zeroheure** [comment]
The [website_seo_redirection](https://github.com/OCA/website/tree/10.0/website_seo_redirection) module from OCA can be used to do that.

**Comment by pedrobaeza** [comment]
I also don't agree with this. There's no direct relation on the URL subpaths and the positioning. Any way, you can create as many alias as you want with latest v11 or use website_seo_redirection module in previous versions.
