### ISSUE TITLE
[15.0] Error when I press the bug button in Form view with developer mode.

### ISSUE THREAD

**Issue by kanda999** [odoo/odoo#125366]
Impacted versions:
15.0c 15.0e

Steps to reproduce:
1, Change to developer mode.
2, Open form view of the record. (eg. res.partner)
3, Change the URL id=nuber and move to another record. 
![2023-06-16_19h10_04](https://github.com/odoo/odoo/assets/101688144/388200f8-449d-4da1-acda-c46d4edb71b1)

4, Press the bug button
![2023-06-16_19h10_19](https://github.com/odoo/odoo/assets/101688144/a33268ad-3f72-4b70-bc86-30aba38d5b4f)

Current behavior:
Get error.
![2023-06-16_19h10_35](https://github.com/odoo/odoo/assets/101688144/4d3e5b81-31b4-400f-9c30-23e7608c3fdc)

This error occurs in 15.0 and not in 14.0 and 16.0.

Support ticket number submitted via odoo.com/help (optional):
OPW: 3374835

@qrtl

**Comment by vava-odoo** [comment]
Should be fixed by https://github.com/odoo/odoo/pull/126264

**Comment by kanda999** [comment]
I have checked that the issue has been fixed
