### ISSUE TITLE
Theme howto javascript function not updated

### ISSUE THREAD

**Issue by lslaz1** [odoo/odoo#12543]
Hey guys, I've got another one for you in the docs.

In the "Javascript Options" section of the theme howto it seems that the function is outdated. It seems that the openerp global has been removed to the console spits out a ReferenceError. I'm pretty sure that odoo.define should be used here but I can't make it work. if I adapt the old function to the odoo.define the console gives me this error: `error: Some modules could not be started 
Failed modules:          ["theme_tutorial"] `.

I've tried it many different ways and nothing seems to work.

**Comment by JKE-be** [comment]
Thanks for the reporting. The js documentation is not already updated...
But don't hesitate to open an existing module in github to see the changes and adapt the code.
https://github.com/odoo/odoo/blob/7682760dcad232829fbb5d4221f66a1ebb9d6c91/addons/website/static/src/js/website.snippets.gallery.js

**Comment by lslaz1** [comment]
Thanks for the quick response. I have actually looked at other modules to adapt my function. The problem comes when I add the `options.registry.snippet_testimonial_options = options.Class.extend` line. When I add it the console gives me this error: `error: Some modules could not be started Failed modules: ["theme_tutorial"]`

**Comment by JKE-be** [comment]
Uses forum for this kind of question ...
But without your code, not easy to help you...
Probably a dépends in __openerp__.py from this module, but this module is not loaded...
