### ISSUE TITLE
[8.0] No wizard pop up for invoicing after installing stock_invoice_directly

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#12545]
Impacted versions: 
8.0 (latest as of today @runbot)

Steps to reproduce: 
1. Enable Invoice Picking Directly(stock_invoice_directly)
2. Book a sales order with invoice based on delivery
3. Transfer the delivery order generated from this SO

Current behavior:
No Wizard for invoicing

Expected behavior:
Wizard pop up for invoicing

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @oliverzgy ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
