### ISSUE TITLE
Checkout's Company name write on wrong field

### ISSUE THREAD

**Issue by hurrinico** [odoo/odoo#12541]
Impacted versions: 8.0, 9.0

Steps to reproduce: Create a user,
                                In user's related partner associate a parent_id and set street and street2,
                                 Make an order on website with created user,
                                 On Checkout as Company's name i see parent_id name,
                                 Validate Checkout
                                 Go check partner's value

Current behavior: What you set in Checkout's Company Name is in partner's street field

Expected behavior: What you set in Checkout's Company Name will not be in partner's street field
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be can you give @hurrinico a little bit more information about why it won't be fixed?
Also, if it is not fixed we can probably close the issue too?

**Comment by JKE-be** [comment]
Because it is a duplicate of https://github.com/odoo/odoo/issues/2541
