### ISSUE TITLE
Request for assistance: Enabling the database manager in Odoo

### ISSUE THREAD

**Issue by discapacidad5** [odoo/odoo#125503]
Dear Odoo Support Team,

I hope this message finds you well. I am writing to seek your assistance regarding an issue I am experiencing with the database manager in Odoo.

When I attempt to access the database manager to create database backups, I encounter the following error message: "The database manager has been disabled by the administrator." I believe this issue is related to a configuration setting within Odoo, but I am unable to locate the specific configuration to rectify the problem.

I have thoroughly reviewed the available documentation and forums, but I have not found a solution that addresses this particular issue. I would greatly appreciate it if you could provide guidance on how to enable the database manager functionality in Odoo.

I understand that your team has deep expertise in Odoo, and I am confident that your insights and assistance will be instrumental in resolving this matter. Any instructions or suggestions you can provide to help me overcome this issue would be highly appreciated.

Please let me know if there are any specific details or logs that I can provide to further assist you in diagnosing and resolving this problem. I am committed to working collaboratively with you to ensure a swift resolution.

Thank you very much for your attention to this matter. I look forward to your prompt response and guidance.

Best regards,
cergio monasterio

vercion odoo 16

**Comment by niyasraphy** [comment]
Hi @discapacidad5 ,
in your odoo configuration file, list_db is set as False and thus you are not able to access the database manager page.
list_db = False

you may have to remove this line of code from the conf file or set is as True to access the db manager page
list_db = True

thanks

**Comment by discapacidad5** [comment]
> Hola@discapacidad5, en su archivo de configuración de odoo, list_db está configurado como False y, por lo tanto, no puede acceder a la página del administrador de la base de datos. list_db = Falso
> 
> es posible que deba eliminar esta línea de código del archivo conf o configurarla como True para acceder a la página del administrador de db list_db = True
> 
> el rastreador de problemas de GitHub es para informar los errores dentro de odoo, para este tipo de dudas/ayuda, siéntase libre de usar el foro la próxima vez: https://www.odoo.com/forum/help-1
> 
> gracias


"I have read about the configuration setting 'list_db = False.' My problem is that there is no configuration file in the main folder, and the one in the 'debian' folder does not respond when I add the line with the value 'true.' Based on my research, it seems that the configuration file in the 'debian' folder is not the correct one. The configuration file that should exist in the main folder is missing, and I don't know where else in the code I can modify this setting or how to make it take effect. I have searched for all the '.conf' files in the Odoo folder, but the mentioned line doesn't work in any of them."

I reviewed the repository available on GitHub, and I couldn't find the configuration file there either. It seems that the required configuration file is missing from the repository, which is why I'm opening this support ticket. There seems to be an issue or something is going wrong within the code. As a troubleshooting step, I even created the file with the specified name in the main folder and added the mentioned line, but I'm still encountering the same problem.

**Comment by niyasraphy** [comment]
so how you run your odoo instance

**Comment by discapacidad5** [comment]
> so how you run your odoo instance

It is installed on a virtual machine and I can access everything without any issues and configure all other aspects. However, I cannot view the databases or download backups of the databases because I encounter that message in a red banner. This is the only problem I am facing.

**Comment by discapacidad5** [comment]
> > so how you run your odoo instance
> 
> It is installed on a virtual machine and I can access everything without any issues and configure all other aspects. However, I cannot view the databases or download backups of the databases because I encounter that message in a red banner. This is the only problem I am facing.

I have read about that line that should be in a configuration file with the .comf extension, but in that configuration file there are a lot of lines in the examples I have seen, and neither in this repository nor in my installation is there such a configuration file. That's why I'm wondering how the system takes that configuration in another way or from where it takes the configurations if that file doesn't exist. There must be another way or another file from which the configurations are taken when that file doesn't exist, because if not, the installation wouldn't be working, and the installation is working fine. The only issue is that I can't create backups or restore backups.

**Comment by discapacidad5** [comment]
I have found the solution to my issue. I found the file I was looking for in a different location. Nowhere did I see that this file was stored in a folder with this path or name: /etc/libreerp/main.conf. I apologize for any inconvenience caused and I appreciate everyone's attention and assistance.
