### ISSUE TITLE
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints

### ISSUE THREAD

**Issue by yangxingluNdit** [odoo/odoo#125557]
Impacted versions:
16.0

Steps to reproduce:
In the management setting page,Fill in the contents of consumer kye and consumer secret key on top of twitter Developer Account,
An internal server error occurred after clicking the twitter account cooperation button.
An error occurred after clicking the twitter account cooperation button.
  →You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level
Twitter's official website formula has abandoned version v1.1 and used version v2.
Public website:https://twittercommunity.com/t/reminder-to-migrate-to-the-new-free-basic-or-enterprise-plans-of-the-twitter-api/189737

Current behavior:
The Twitter feature is currently unavailable. Could you please help resolve it

Expected behavior:
The Twitter feature can continue to be used

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pieterdemil** [comment]
I recently came across this error that I'm experiencing as well. I understand that maintaining a project like this takes significant time and effort, and I appreciate all the work done so far. New Twitter (or X) API was announced on March 29 2023.

Would you happen to have any updates on this issue or guidance on a possible workaround? 
@vava-odoo  If there's anything I can do to assist or provide more information, please let me know. We are using the Free plan of the Twitter / X. API.

**Comment by vava-odoo** [comment]
Hi @pieterdemil 
There is PR about it (https://github.com/odoo/enterprise/pull/44625), in reviewing process.
Cheers.

**Comment by vava-odoo** [comment]
Hi @yangxingluNdit and @pieterdemil 
The new API of X (Twitter) is now integrated in all stable versions.
Cheers
