### ISSUE TITLE
Automated actions can't trigger on all writes to a record

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#12550]
Impacted versions: all

Last autumn when v9 was released and the sale order / purchase order workflows, @fpodoo advocated the use of Automated Actions to implement workflow customization (the thread is https://www.odoo.com/groups/community-59/community-13922152?mode=thread&date_begin=&date_end=)

I tried that approach does not work. 

The problem is that a given automated actions can only trigger once in a transaction (apparently to avoid recursion). However, a single write on a record can trigger many other writes (because computed fields are updated for instance, or because). The consequence of this can be hard to track down inconsistencies because the action fired when the first write was made but was not called again when the dependent field was updated.

There is no way to define a action which triggers when a given field is updated, so you naturally end up writing a generic action which triggers on any write, and do the filtering based on self.env.context['old_values'] to perform stuff only if some fields have changed. This approach will silently fail in the case I described in the previous paragraph. 

To reproduce: 
1. declare an automated action to trigger on update of a model
2. on that model define a method called by a button in the user interface which updates 2 fields using: 
   
   record.field1 = val1
   record.field2 = val2
3. click the button in the UI

Expected result : the action is called twice (or just once but with both values modified)

Actual result: the action is only called once for the update of field1, and we get no notification for the update of field2.

**Comment by Yenthe666** [comment]
@odony could you give your opinion / feedback on this one please?

**Comment by gurneyalex** [comment]
@odony @antonylesuisse Hello, is this going to be fixed in v10?

**Comment by Yenthe666** [comment]
@mart-e also pinging you on this one. This should be landing in V10 before it is frozen.

**Comment by gurneyalex** [comment]
@dreispt @max3903 this is the issue I mentioned to you yesterday evening.

**Comment by dreispt** [comment]
@gurneyalex Well, Automated Actions have a safeguard to avoid retriggering the same action on further writes. This is necessary, and I don't see how it could be removed.
For example, it is frequent for an Action, once triggered, to write again on the record, to change the Responsible, add Followers, change the Priority, etc.

I feel that the real problem here is the impossibility to have Action filters with Python expressions having available the new and old values. We should fix that. There is some useful code available in https://github.com/OCA/server-tools/pull/296

**Comment by gurneyalex** [comment]
@dreispt yes but if you use these to trigger change notifications to external systems, you're fscked as you will miss some changes. It's a far better idea imo to only trigger the action IFF the call to write actually changed the value to break recursive calls.

**Comment by dreispt** [comment]
I guess that's a particular use case not suitable for Automated Actions then.
Yes, a post commit hook would be a good fit for this, if you want to do it in process.

**Comment by gurneyalex** [comment]
There it is, in v10: https://github.com/odoo/odoo/blob/10.0/odoo/sql_db.py#L338

**Comment by dreispt** [comment]
Still, probably not available for Automated Actions.

**Comment by mart-e** [comment]
Hello,

After some discussion with @antonylesuisse it is quite tricky. It is definitely not something we will change in stable as too risky and even in master, we are a bit afraid of the side effects and performances.
Pinging @rco-odoo, how difficult/risky would that be?

**Comment by flyingL123** [comment]
Is there currently any way to access the 'dirty' fields when filtering an automated update action. In other words, if I only wanted to trigger an automated action if fieldA or fieldB has changed, is that possible to set up? I know that I can use the before and after filters to check if the fields have specific values, but what about just wanting to know if they have changed at all?

**Comment by Yenthe666** [comment]
@rco-odoo could you have a look at the question from (@)mart-e and still give feedback please?

**Comment by bhaskarreddyg** [comment]
I am writting qweb reports while writting i got this error
can anyone help



Odoo Server Error
Traceback (most recent call last):
  File "D:\odoo-9.0\openerp\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo-9.0\openerp\http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo-9.0\openerp\http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo-9.0\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo-9.0\openerp\http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo-9.0\openerp\http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "D:\odoo-9.0\openerp\http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "D:\odoo-9.0\addons\web\controllers\main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\odoo-9.0\addons\web\controllers\main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\odoo-9.0\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: print_report() takes at least 6 arguments (5 given)

**Comment by pedrobaeza** [comment]
Removed last comment as has nothing to do with current issue as it's a deployment problem.

About the topic, now that the new base_automation is out in v11, @gurneyalex is the problem still there?

**Comment by gurneyalex** [comment]
@pedrobaeza a quick test shows this is fixed in v11.

**Comment by pedrobaeza** [comment]
Although it would be good to have it solved on previous versions then, we can consider this fixed. If you see that a patch can be integrated on v10 or v9 stable branches, please make the PR.
