### ISSUE TITLE
  French amount letter report invoice 

### ISSUE THREAD

**Issue by hindbenessy** [odoo/odoo#12562]
Odoo version 8 
i want to display amout total text with french like this 
3600: trois mille six cent 
this 's my code 
// __openerp__.py

{
    'name': 'Recu facture',
    'version': '1.0.0',
    'category': '',
    'sequence': 1,
    'author': '',
    'website': 'http://www.openerp.com',
    'depends': ['base','account','report'],
    'data': ['recu_facture.xml',
    'recu_facture_views.xml',
    
    ],
   
    
    'installable': True,
    'application': True,
    'auto_install': False,
}
//__init__.py
import facture
//facture.py
# coding: utf-8
import datetime
import time
from itertools import groupby
from operator import itemgetter

import math
from openerp import netsvc
from openerp import tools
from openerp.osv import fields, osv
from openerp import models, api,_
from openerp.tools.translate import _
from openerp.report import report_sxw
from openerp.tools import amount_to_text

class account_invoice(models.Model):
	_name = 'account.invoice'
	_inherit = 'account.invoice'

	@api.multi
	def amount_to_text(self, amount, currency='Dirhams'):
		return amount_to_text(amount,currency)
//recu_facture.xml
<div class="row" style="padding: 0px; min-height: 1cm; text-align: center; padding: 5px">
                         
                            <t t-esc="o.amount_to_text(o.amount_total,'Dirhams')"/>
                             </div>
=============
i  had amout text in english thanks to help me

**Comment by Yenthe666** [comment]
Hi @hindbenessy,

Github issues are used for tracking bugs that are found in the official code. Custom development and questions regarding this should be posted on the official Odoo help forums (help.odoo.com).
I'm sure somebody can help you there!
Closing this since it is not an issue but a question.

Regards,
Yenthe
