### ISSUE TITLE
[9.0] non-deductible taxes not going to the correct account in some cases

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#12561]
Impacted versions: 9.0 (this bug is not present in 8.0)

Steps to reproduce:

On runbot 9.0.

Create a non-deductible taxe:

![image](https://cloud.githubusercontent.com/assets/692075/16307329/23afbef0-3961-11e6-8bb1-f841470dd306.png)

(this is a simple case of a fully non-deductible tax, the same applies to partially deductible taxes such as the car taxes in Belgium)

Create an invoice with two lines on different expense accounts:

![image](https://cloud.githubusercontent.com/assets/692075/16307371/4406e016-3961-11e6-8570-7c39d3800008.png)

Current behavior:

There is only one tax line going to the expense account of the first invoice line.

Expected behavior:

There must be a different tax line for each key (tax, account, analytic account)

Code analysis:

In `account/account_invoice.py`, method `get_taxes_values()` uses the tax id as key to group tax lines. It must use a more elaborate key to group tax lines.

Moreover it would be great to have prepare methods for the key and the tax lines so we can propagate additional analytic dimensions that we would have on our invoice lines in custom modules.

**Comment by sbidoul** [comment]
@qdp-odoo can you please have a look into this one?

cc/ @chrisdec @adrienpeiffer

**Comment by sbidoul** [comment]
@qdp-odoo thanks a lot for the fast reaction. 

Can you add the analytic account in the key too, and put that in a method that we can override, similar to `inv_line_characteristic_hashcode()` that is used for invoice line grouping?

**Comment by qdp-odoo** [comment]
@sbidoul here you are fb6a05d

**Comment by sbidoul** [comment]
@qdp-odoo thanks a lot!

Now I'll need a prepare method for the tax lines themselves. Would you accept a 9.0 PR for that? It's necessary to add analytic dimensions on move lines.

**Comment by qdp-odoo** [comment]
I don't know what you're talking about ^^ you can make a PR to let me see what exactly you have in mind, and then I'll tell if it can be in v9 or not :stuck_out_tongue: 

But it's best to continue the discussion on that PR rather than on this closed issue.
