### ISSUE TITLE
[v8] Delivery Grid Calculations Fail when Unit Of Sale not active

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#1256]
When Unit of Sale is NOT being used, the sale order line is (correctly) not being updated with a unit of sale figure.

When the delivery calculation is activated from the quote, it runs code in "delivery / delivery.py" in get_price for the model "delivery.grid".

The calculation of quantities (and hence weight and volume) use "line.product_uos_qty" which has not been set.

This is true for products which have no uos_id on the product.template.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
