### ISSUE TITLE
[8.0][mrp] Propagate restrict_lot_id when consuming lines

### ISSUE THREAD

**Issue by zamberjo** [odoo/odoo#12568]
Impacted versions: 8.0

Steps to reproduce: Create MO with restrict_lot_id set on - at least - one move line and call `do_produce` with partial product_qty.

Current behavior: The created move line does not have the value restrict_lot_id set.

Expected behavior: The process should propagate the value to any created move line.

Video/Screenshot link (optional): -

[On this line](https://github.com/odoo/odoo/blob/8.0/addons/mrp/stock.py#L194)
Current:

```
new_mov = self.split(cr, uid, move, quantity_rest, context=context)
```

Proposed

```
new_mov = self.split(cr, uid, move, quantity_rest, restrict_lot_id=restrict_lot_id, context=context)
```

**Comment by s2d4theworld** [comment]
This also should impact v9.0

**Comment by spadae22** [comment]
Agreed

**Comment by Yenthe666** [comment]
Hi @zamberjo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
