### ISSUE TITLE
[9.0] web: lessc gives a "ParseError" while compiling web.assets_backend

### ISSUE THREAD

**Issue by mlatre** [odoo/odoo#12560]
Impacted versions: Odoo9 - Ubuntu 12.04 - Python 2.7.3

Steps to reproduce:
Hi, I just installed Odoo9 and to enter for the first time after putting my username and password , the following error appears

ParseError: Syntax Error on line 460 in -:460:33
459              .o-caret-right;
460              .o-position-absolute(@top: 50%, @left: 12px);
461               margin-top: (-@caret-width-base);[0m

Any ideas? 
thanks for your help

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/1537934/16306186/3f4b5968-3933-11e6-98d5-4e971b38479e.png)

**Comment by JKE-be** [comment]
Are you sure that you correctly install all required packages (less, ....) ?https://www.odoo.com/documentation/9.0/setup/install.html#installing-dependencies

**Comment by sle-odoo** [comment]
Could you type ```lessc --version``` ?
Also, the "[0m" at the line 461 looks suspicious. How did you setup your Odoo?

**Comment by Yenthe666** [comment]
Closing as there has been no answer/feedback on the questions.

Regards,
Yenthe
