### ISSUE TITLE
[16.0] Custom values in options are not being saved

### ISSUE THREAD

**Issue by john-herholz-dt** [odoo/odoo#125792]
Impacted versions:
16.0

Steps to reproduce:
- Create a product attribute with variant creation mode: never (option) and a value with is_custom
- Add this attribute and value to a product
- Create a sales order and add this product
- Enter something in the product configurator for the is_custom field

Current behavior:
- Custom value is not saved

Expected behavior:
- Custom value is saved and can be re-edited when opening the sale order again

Video/Screenshot link (optional):
[Bildschirmaufzeichnung vom 20.06.2023, 15:41:23.webm](https://github.com/odoo/odoo/assets/102949895/b15b6c8b-075e-486c-919c-5a82e66b6433)

Additional note:
This was working on Odoo 15.0
I testet it on runbot and it will create also an issue with the new UI for future versions (OWL lifecycle stuff)
Cause of this issue is maybe _compute_custom_attribute_values on sale/models/sale_order_line.py
or even further the property for valid_product_template_attribute_line_ids on the product template

**Comment by vava-odoo** [comment]
Hi @john-herholz-dt 
Thanks for reporting. The fix has been merged in 16.0.
Cheers,
