### ISSUE TITLE
iframe same origin issue on chrome

### ISSUE THREAD

**Issue by hassoon3** [odoo/odoo#12575]
Impacted versions:
8.0.20160617 on Chrome Version 51.0.2704.103 m

Steps to reproduce:
Using HTTPS and Using a demo database, generate the General Ledger PDF report

Current behavior:
Error from Odoo Client : Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://www.###.com" from accessing a cross-origin frame.

Error browser console: b1356b1:2968 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Sandbox access violation: Blocked a frame at "https://www.###.com" from accessing a frame at "https://www.###.com".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.

Expected behavior:
No error occurs

Video/Screenshot link (optional):

**Comment by hassoon3** [comment]
Solved! Turned out I had set the X-Frame-Options header to DENY in my NGINX reverse proxy. I had to reset it to SAMEORIGIN instead.

**Comment by arafatx** [comment]
Hai, how do you reset the this in nginx. Having the same problem. Can you show the steps?
