### ISSUE TITLE
Email case-sensitive for user authentication

### ISSUE THREAD

**Issue by eronlloyd** [odoo/odoo#12574]
Impacted versions: 9.0

Steps to reproduce: Attempt to log in using your user email, but in a different case.

Current behavior: With the correct email, but in a different case, and the correct password, the login will fail.

Expected behavior: Odoo compares the email in a case insensitive way, since this is true generally with email, and accepts the authentication if the characters and password otherwise match.

Video/Screenshot link (optional):

**Comment by eronlloyd** [comment]
After some further research, I came across PR #9378, which seems like it's solving a similar issue, but not in authentication. I'm not familiar enough with the code yet to know where to look, but I'll keep exploring. This should be a relatively easy, obvious fix for something that can trip up and confuse new users right from the start. The first sign-in experience should be as positive as possible.

**Comment by pedrobaeza** [comment]
The linked PR and issue is for other thing (mail aliases), but for login, strict case should be followed, as it's your identification (and it's not always an email, but a user name). Closing this as not appropriated.
