### ISSUE TITLE
Odoo v8 bugview One2many (tree view editable mode in One2many only)

### ISSUE THREAD

**Issue by vuducnamcs** [odoo/odoo#12577]
Impacted versions: Odoo v8

Steps to reproduce: When click to edit item on One2many field with tree view (editable on). Content is broken and duplicate information. 

Current behavior:

Expected behavior: No broken line when select item (select to edit)

Video/Screenshot link (optional):
<img width="1173" alt="screen shot 2016-06-26 at 7 10 24 am" src="https://cloud.githubusercontent.com/assets/18390204/16359808/04799d76-3b6e-11e6-8723-a20c4d32a806.png">

**Comment by Yenthe666** [comment]
Hi @vuducnamcs,

I can't reproduce this on any runbot. Which browser and which version of the browser are you using?

**Comment by Yenthe666** [comment]
Hi @vuducnamcs,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
