### ISSUE TITLE
Readonly button on Field one2many field wizard

### ISSUE THREAD

**Issue by aryaadiputra** [odoo/odoo#12579]
Impacted versions: 9.0

I got issue when create one2many wizard with button, the button not able to click.

Anyone help?

**Comment by Yenthe666** [comment]
Hi @aryaadiputra,

The Github issues are only for official bugs in Odoo, not for asking questions.
Please post a question on help.odoo.com, I'm sure somebody can help you there!

Regards,
Yenthe
