### ISSUE TITLE
Signup link for portal fails on multidatabase installations

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12594]
Impacted versions: 8, 9.

Steps to reproduce:

0. Log in any runbot.
0. Go to your customers and pick one.
0. Manage portal access and grant portal access to him.
0. Go to settings > users, pick that user.
0. You see the login link? Right button > Open in new private window.

Current behavior:

```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

Expected behavior: User goes to password reset page.

Additional information: If you go to the root of the runbot's domain in the private window, select the right database, and then go to the login link again, it works. So, it seems it is only using the session/cookie-based database, and not the `db` GET parameter it gets (remember the URL is like `http://155848-9-0-322962.runbot8.odoo.com/web/signup?token=gxJT6SrW6WD0psVyq8C7&db=155848-9-0-322962-all`).

@Tecnativa

**Comment by Yenthe666** [comment]
I've seen this issue in Odoo for ages, probably over 1.5 year.
@mart-e any input on this? I bet you'll say this is handled with `--db-filter`.

**Comment by mart-e** [comment]
@Yenthe666 you know me well! Indeed, you can reproduce this on runbot because you are on a multi db instance with no filter based on the domain.
So you will get this in dev mode but in production you are supposed to use [`db-filter`](https://www.odoo.com/documentation/9.0/reference/cmdline.html#cmdoption-odoo.py--db-filter)

**Comment by Yajo** [comment]
But then the `&db=155848-9-0-322962-all` part of the URL what's for?

**Comment by mart-e** [comment]
Probably could be dropped. The point is that in v8 we stopped trying to guess the db (there were a lot of issues/hack with that) and made the db-filter mandatory for multidb environment.
See #2039 for the whole debate, 2 years ago.

**Comment by Yajo** [comment]
Ah nice, that's what was misleading me.
