### ISSUE TITLE
[16.0] Method not found: _get_reconciled_vals 

### ISSUE THREAD

**Issue by nikul-serpentcs** [odoo/odoo#125933]
Impacted versions: 16.0

**_get_reconciled_vals** This method is used in `point_of_sale` module.

https://github.com/odoo/odoo/blob/e460930902ed4b08539688871612410fcdf40818/addons/point_of_sale/models/account_move.py#L46

Super call not found in any module list. https://github.com/odoo/odoo/blob/e460930902ed4b08539688871612410fcdf40818/addons/point_of_sale/models/account_move.py#L48

**Comment by niyasraphy** [comment]
hi,
it seems its left over/not changed after this commit:  https://github.com/odoo/odoo/commit/785d49f3f0a21720d8c929d597d4041918ab7f41

**Comment by nikul-serpentcs** [comment]
@niyasraphy Thank you for your quick response.

**Comment by william-andre** [comment]
Please link the issue to the PR when possible :wink:

**Comment by william-andre** [comment]
However, that just seems to be dead code; I don't see it being used anywhere.

Why did you mention that PR @niyasraphy ?

And @nikul-serpentcs when do you encounter an issue? That function should actually be removed.

**Comment by nikul-serpentcs** [comment]
@niyasraphy I checked PR and you removed the payment method name in the invoice function.
So it's working as per the image, Right?

![image](https://github.com/odoo/odoo/assets/17664321/c6d7f48d-f4ca-45d5-8f54-03918ccad366)

**Comment by niyasraphy** [comment]
@nikul-serpentcs 
it is decided not to have this functionality any more, you can see this comment:  https://github.com/odoo/odoo/pull/125995#issuecomment-1643938775

and the fn specified in the issue is removed from master in: https://github.com/odoo/odoo/commit/b4c828622b5122e27c3d0bc37012105bd746f458

i believe you can close the ticket.
thanks

**Comment by nikul-serpentcs** [comment]
Yes, I checked all your comments, Do You mean this functionally removed in the latest version?

**Comment by niyasraphy** [comment]
yes
