### ISSUE TITLE
BUG: Company Name goes in street name in backend when Checkout from shop

### ISSUE THREAD

**Issue by vijayant1234** [odoo/odoo#12590]
Impacted versions: 8.0 , 9.0, Master

Steps to reproduce: 

- add to cart and checkout from shop page

https://drive.google.com/file/d/0ByGXYBRKsz2laFpkRTdyekYxbkU/view?usp=sharing

Current behavior: 

- Company name fill up in street field

https://drive.google.com/open?id=0ByGXYBRKsz2lVm5SQlR0SUZacHM

Expected behavior:
- That Should not Fill in Street field Company field is already there in Partner Form
 
@mart-e @bst-odoo @tde-banana-odoo

**Comment by bst-odoo** [comment]
Might be fixed with the new e-commerce refactoring but very touchy because of the migrations.

**Comment by vijayant1234** [comment]
@bst-odoo  
What about 8.0 and 9.0 it should also fix in older versions ?

**Comment by bst-odoo** [comment]
We decided not to fix it because it is not a blocking bug and it could break all our customers e-commerces.

**Comment by odony** [comment]
Closing, this seems to be a duplicate/consequence of #2541, #12541 and many other similar issues.
There is work-in-progress by @JKE-be to improve this in Odoo 10, but it's not a trivial change.
