### ISSUE TITLE
[9.0] l10n_nz and l10n_au cannot be installed at the same time

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#12600]
Impacted versions: 9.0

Steps to reproduce: install both modules. No need to install the COA on a company.

Current behavior: 

```
  File "/home/odoo/runbot/extra/runbot/static/build/156008-9-0-cc4f8d/openerp/tools/convert.py", line 913, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_nz failed: file l10n_nz/data/account.tax.template.csv could not be processed:
 Line 3 : duplicate key value violates unique constraint "account_tax_template_name_company_uniq"
DETAIL:  Key (name, company_id, type_tax_use)=(Zero (Export) Sale, 1, sale) already exists.
```

Expected behavior: Installation succeeds.

cc @richard-willowit, @nim-odoo (as per https://github.com/odoo/odoo/pull/12244)

**Comment by StefanRijnhart** [comment]
This breaks tests over at https://github.com/oca/ocb because our Travis setup installs all localizations.

**Comment by nim-odoo** [comment]
@richard-willowit : Could you suggest a fix? Thanks!

**Comment by gdgellatly** [comment]
Hmmm a couple of comments.

Having multiple localizations for a single company is not really a real
world use case is it? And if it is then surely it is the constraint, not
the localizations issue.

But anyway there is no such tax rate as zero (export) sale in NZ. There is
zero rated supplies, however it covers more than just exports, although not
a lot more. That is the question on your tax return which strangely enough
was due today. No mention of exports and no requirement to report exports
seperately from other zero rated supplies.

**Comment by richard-willowit** [comment]
Ooh, I will definitely look in to it one way or another.  I am on holidays
at the moment and it is hard to look at / sort out on a smart phone :S

I will be back in the office on the 11th July.

On 28 June 2016 at 18:34, Graeme Gellatly <notifications@github.com> wrote:

> Hmmm a couple of comments.
>
> Having multiple localizations for a single company is not really a real
> world use case is it? And if it is then surely it is the constraint, not
> the localizations issue.
>
> But anyway there is no such tax rate as zero (export) sale in NZ. There is
> zero rated supplies, however it covers more than just exports, although not
> a lot more. That is the question on your tax return which strangely enough
> was due today. No mention of exports and no requirement to report exports
> seperately from other zero rated supplies.
>
> On Tue, 28 Jun 2016 8:09 PM Nicolas Martinelli <notifications@github.com>
> wrote:
>
> > @richard-willowit <https://github.com/richard-willowit> : Could you
> > suggest a fix? Thanks!
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/odoo/odoo/issues/12600#issuecomment-228981155>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AE23kLSbP7D855z7ELxecaY3bgx__OR3ks5qQNbXgaJpZM4I_10c
> >
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/odoo/odoo/issues/12600#issuecomment-229000062>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA9tnGjKkBxfj5QmuA6A5q2KOQNhkjZfks5qQOq3gaJpZM4I_10c>
> .
>



-- 
Richard deMeester
www.willowit.com.au
ph: +61 3 8506 0393
mob: +61 403 76 76 76
*2013, 2015 Odoo Best Partner Asia/Pacific*

**Comment by richard-willowit** [comment]
@nim-odoo They can now both be installed.
