### ISSUE TITLE
Portal many2many field

### ISSUE THREAD

**Issue by selmanfarukyilmaz** [odoo/odoo#126057]
Hi,
i have a new field on res.partner,
its'a many2many field.
I need the add this field to portal.portal_my_details.

Its not working ?

    <template id="santex_contact_view_portal_inherit" inherit_id="portal.portal_my_details">
        <xpath expr="//div[label[@for='street']]"
               position="after">
            <div t-attf-class="form-group #{error.get('company_skills_id') and 'o_has_error' or ''} col-xl-6">
                <label class="col-form-label" for="company_skills">Company Skills</label>
                <select name="company_skills_id"
                        t-attf-class="form-control #{error.get('company_skills_id') and 'is-invalid' or ''}">
                    <option value="">Company Skills...</option>
                    <t t-foreach="company_skills or []" t-as="company_skill">
                        <option t-att-value="company_skill.id"
                                t-att-selected="company_skill.id == int(company_skill_id) if company_skill_id else company_skill.id == partner.company_skill.id">
                            <t t-esc="company_skill.id"/>
                        </option>
                    </t>
                </select>
            </div>

        </xpath>
    </template>

**Comment by niyasraphy** [comment]
hi @selmanfarukyilmaz ,
this is to track the bugs inside the odoo code, for such development doubts/question, use forums.
official forum: https://www.odoo.com/forum/help-1

thanks
