### ISSUE TITLE
How can I overwrite the function of save button in the Point of Sale Odoo 15

### ISSUE THREAD

**Issue by Paulguzhnay** [odoo/odoo#126134]
Hi Odoo, I want to overwrite the function of the save button, when you will create a new client but I get the next error:
Missing dependencies:     (3) ['point_of_sale.Chrome', 'point_of_sale.Registries', 'point_of_sale.Gui']
Non loaded modules:       (2) ['@point_of_sale/js/chrome_adapter', '@point_of_sale/js/main']

My script is this:

### **_Custom_OrderLine.js_**
from web import Button
odoo.define('sc_pos_offline_order.custom_script', function (require) {
    "use strict";
    console.log("metodo custom")
    var core = require('web.core');
    var _t = core._t;

    var Widget = require('web.Widget');

    var CustomButton = Widget.extend({
        events: {
            'click .button i.fa-floppy-o': 'customMethod',
        },

        customMethod: function (ev) {
            console.log('Se hizo clic en el botón personalizado');
            // Tu lógica personalizada aquí
        },
    });

    return CustomButton;
});

### **_custom_assets.xml_**
<odoo>
    <data>
        <template id="assets_backend" name="pwaOffline_order custom_assets" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <script type="text/javascript" src="/pwaOffline/static/src/js/Custom_OrderLine.js"></script>
            </xpath>
        </template>
    </data>
</odoo>

*### *__manifest.py__**
        'point_of_sale.assets': [
                '/sc_pos_offline_order/static/src/css/pos.css',
                '/sc_pos_offline_order/static/src/js/Custom_OrderLine.js'
        ],
        'web.assets_qweb': [
            '/sc_pos_offline_order/views/custom_assets.xml',
            
        ],

**Comment by niyasraphy** [comment]
hi @Paulguzhnay  ,
this is to track the bugs inside the odoo code, for such development doubts/question, use forums.
official forum: https://www.odoo.com/forum/help-1

thanks
