### ISSUE TITLE
how can i change "Batches" Field name?

### ISSUE THREAD

**Issue by Nayan12** [odoo/odoo#12622]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Nayan12,

Github issues are used for tracking issues within the official code, not for asking questions.
Please post a new topic on help.odoo.com, where I'm sure somebody can help you!

Regards,
Yenthe
