### ISSUE TITLE
Allow to use SVG images like bitmap ones

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12627]
Impacted versions: 8, 9.

Steps to reproduce:
1. Go to any partner, company, product.
2. Edit.
3. Press pencil on image.
4. Choose an SVG image from your drive.

Current behavior:
![captura de pantalla de 2016-06-29 17-19-57](https://cloud.githubusercontent.com/assets/973709/16458028/f41e4b0e-3e1d-11e6-9d3e-4013f6b5550e.png)

Expected behavior:
SVG attached like normal image.

Especially useful for companies, where the logo is displayed in the website, and for website images manager wizard.

**Comment by lukebranch** [comment]
+1

This would be a very useful feature.

**Comment by pedrobaeza** [comment]
@odony any plans to support SVG in next Odoo version? Should you accept if we add this support and propose it to master?

**Comment by pedrobaeza** [comment]
@mart-e I summon you to know if there's any plans about this.

**Comment by mart-e** [comment]
@pedrobaeza nothing AFAIK. Have you investigated why it failed? Should it be easy to add the support?

**Comment by pedrobaeza** [comment]
I think so. I will put someone to investigate this.

**Comment by pedrobaeza** [comment]
The SVG support has been proposed in #26635

**Comment by pedrobaeza** [comment]
We can close this one as implemented.
