### ISSUE TITLE
7.0 sale_mrp using a field defined in project_mrp, but it doesn't depend on it !

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#12631]
Impacted versions: 7.0

On an up-to-date Odoo v7, in the sale_mrp module, the code writes on the sale_line_id field of procurement.order :
https://github.com/odoo/odoo/blob/7.0/addons/sale_mrp/sale_mrp.py#L82

But the sale_line_id field of procurement.order is defined in the module project_mrp, cf https://github.com/odoo/odoo/blob/7.0/addons/project_mrp/project_procurement.py#L30

and the sale_mrp module only depends on sale_stock and mrp modules, but not on project_mrp.

So the consequence is that we get these scary lines in the logs:

```
2016-06-30 07:15:38,035 31155 WARNING test_160616 openerp.osv.orm: No such field(s) in model procurement.order: sale_line_id.
```

This bug had already been reported on LP by @hbrunn , cf https://bugs.launchpad.net/openobject-addons/+bug/1248068

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @farinoire ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
