### ISSUE TITLE
[16.0] Translations not updated in multi-website

### ISSUE THREAD

**Issue by imanie383** [odoo/odoo#126325]
https://github.com/odoo/odoo/blob/27ba86323ff5d57887a6901ffc997ba17a559262/odoo/tools/translate.py#L1348

Impacted versions: 16:

Steps to reproduce:
update any .po file

Current behavior:
the translation is not update

Expected behavior:
the translation would be updated

Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/35231827/0ecf5b4c-e4e5-480c-98c3-3d6027fd303f

And if you select `force_overwrite`, only the template translations without website is updated
![image](https://github.com/odoo/odoo/assets/35231827/4a9b9c8f-a83c-4059-854d-8f66d3e75eac)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @imanie383 
Not sure to understand the issue, but maybe @HydrionBurst could help explain here?

**Comment by HydrionBurst** [comment]
Each translation importable ir.ui.view record has an external id (you can find the mapping in ir.model.data) which can be found in the po/pot files.
In your use case only the view without website_id has external id and get translation update after import.

Usually importing po files for translations are only for internal resources. E.g. module data and demo data. But as a workaround, you can create a record in ir.model.data (specifying module, model, resource id and external id) for these views with website_id. Export the po file for the module. Translate. Import the po file.
