### ISSUE TITLE
[9.0] Access problem when creating action.base.rule

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#12640]
Impacted versions: 9.0 (not tested on other versions)

**Steps to reproduce:**

1. Login as Admin and create a base.action.rule for sale.order
    On tab "Conditions" choose "On Update", for Filter create a new one with default values
2. Login as Demo and try to create a sale.order

**Current behavior:**

Access Error on ir.filters, read

**Expected behavior:**

No Access Error and creation of sale.order

**Extra Info:** 

Default user in ir.filters seems to be the problem for this case, but i think either the creation of this filters (for base.action.rule) should be forced to never set a user, or the user should be ignored. Plus there is an ir.rule on ir.filters which is connected to this problem, too.

**Comment by dreispt** [comment]
In the `ir.filter`, make sure you leave the `User` field blank.

**Comment by intero-chz** [comment]
I'm aware of that, now, as i wrote under "Extra Info". But i don't think that others will be aware of this, too. So creating an `ir.filter` within an `action.base.rule` should set the `User` blank as default.

**Comment by dreispt** [comment]
@intero-chz It's a little worse than that, because those "user-less" filters will show up in model's Serach view area (at the top of the Kanban or List view). 
If you make heavy use of Automated Actions, the Search filters can become a nightmare for end users 😢

**Comment by intero-chz** [comment]
Why did you close the issue (just for info)?

These filters are created as inactive, so they shouldn't become a nightmare for end users.

**Comment by dreispt** [comment]
AFAICS your issue was solved.
