### ISSUE TITLE
[15.0][16.0] calendar: Duplicated entries when multiple attendees

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#126479]
**Impacted versions:** 15.0, 16.0

**Steps to reproduce:**

- Go to Calendar.
- Create a new event.
- Add "Marc Demo" to the attendees.

** Current behavior:**

Two calendar entries for the same event are shown, one per attendee:

**Expected behavior:**

Only one entry should be shown, as they are the same event.

**Video/Screenshot link (optional):**

v15
![Selección_052](https://github.com/odoo/odoo/assets/7165771/922a13b1-21f4-4e8d-85a8-49fd403574de)

v16
![Selección_053](https://github.com/odoo/odoo/assets/7165771/3873a430-c826-4e14-9729-0bd3339dbeff)

**Comment by dalaOdoo** [comment]
Hi @pedrobaeza this is expected. 
When you are displaying the calendar of several users you will see common events several times as these events are in their calendar. This is exactly the same behavior in google calendar for example. 

![image](https://github.com/odoo/odoo/assets/100136841/c40f3889-a56a-4dc4-b0ed-7a92fa124b84)

**Comment by pedrobaeza** [comment]
Thanks for answering, @dalaOdoo 

It wasn't this way on v13, and the screenshot you put from Google seems a bit forced, as you are importing other calendars, so there's a separation between them and seems more logical that they are repeated due to this.

With the steps I describe, you don't have to do anything or import something else: they appear duplicated as soon as you save the event with multiple attendees that are internal users. That doesn't happen when the attendee is an external one.

Please reconsider the issue.

**Comment by dalaOdoo** [comment]
Regardless how you have to configure it, the idea both in Odoo and google is to display the calendar of other persons. We do believe it is more clear and more efficient to do it like this as you will see directly who is free and when. 
If events with several attendees for which you are browsing the calendar are "merged" then you will have to click on each event to see who is attending or not.

FYI with google it is the same if you use the "attendee" feature without having to import calendar and you can test on outlook it is the same also. 

Can I ask you what is the problem you are facing exactly ?
