### ISSUE TITLE
Problemas con Zxpath> EN ODOO V8, USADO EN WINDOW 7.

### ISSUE THREAD

**Issue by carrasquel2016** [odoo/odoo#12649]
Impacted versions: ODOO V8

Steps to reproduce:
Mi código acá no quiere generar la vista de mi reportes report_pickorder.xml 

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
    <plantilla id="external_layout_header" inherit_id="report.external_layout_header">
            <xpath expr="//div[@class='header']" position="replace">
            </xpath>
        </template>
    </data>
</openerp>

Current behavior:

Me arroja un error el cual es el siguiente:

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
El elemento '<xpath expr="//div[@class='header']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `external_layout_header`
[view_id: 997, xml_id: formats.external_layout_header, model: n/a, parent_id: 181]" while parsing None:4, near
<data inherit_id="report.external_layout_header">
            <xpath expr="//div[@class='header']" position="replace">
            </xpath>
        </data>

Expected behavior:
Reguiero que me genere la vista correcta del reporte ya que depende de eso para realizar todas las operaciones que necesito 
Video/Screenshot link (optional):
el error que me arroja el odoo v8 al actualizarlo es el siguiente 

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
El elemento '<xpath expr="//div[@class='header']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `external_layout_header`
[view_id: 997, xml_id: formats.external_layout_header, model: n/a, parent_id: 181]" while parsing None:4, near
<data inherit_id="report.external_layout_header">
            <xpath expr="//div[@class='header']" position="replace">
            </xpath>
        </data>

MI .XML ES:

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <report 
            id="action_report_liberacion"
            string="Liberación"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.report_liberacion"
            name="formats.report_liberacion"
        />
        <report 
            id="action_report_poliza"
            string="Poliza"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.report_poliza"
            name="formats.report_poliza"
        />
        <report 
            id="action_report_factura_tipo1"
            string="EIR Serie A"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.report_factura_tipo1"
            name="formats.report_factura_tipo1"
        />
        <report 
            id="action_report_factura_tipo2"
            string="EIR Serie B"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.report_factura_tipo2"
            name="formats.report_factura_tipo2"
        />
        <report 
            id="action_report_factura_tipo3"
            string="EIR Serie C"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.report_factura_tipo3"
            name="formats.report_factura_tipo3"
        />
		 <report 
            id="action_report_MARKS1"
            string="Maersk1"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.FACTURA_MARKS1"
            name="formats.FACTURA_MARKS1"
        />
		  <report 
            id="action_report_MARKS2"
            string="Maersk2"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.FACTURA_MARKS2"
            name="formats.FACTURA_MARKS2"
        />
		  <report 
            id="action_report_GLOBAL1"
            string="GLOBAL SERIE BB"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.GLOBAL1"
            name="formats.GLOBAL1"
        />
		  <report 
            id="action_report_GLOBAL2"
            string="GLOBAL SERIE E "
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.GLOBAL2"
            name="formats.GLOBAL2"
        />
		  <report 
            id="action_report_GLOBAL3"
            string="GLOBAL SERIE B"
            model="account.invoice" 
            report_type="qweb-html"
            file="formats.GLOBAL3"
            name="formats.GLOBAL3"
        />
        <record id="paperformat_format1" model="report.paperformat">
            <field name="name">Format 1</field>
            <field name="default" eval="True"/>
            <field name="orientation">Portrait</field>
            <field name="margin_top">22</field>
            <field name="margin_bottom">3</field>
            <field name="margin_left">3</field>
            <field name="margin_right">3</field>
            <field name="header_line" eval="False"/>
            <field name="header_spacing">20</field>
            <field name="dpi">96</field>
        </record>
        <record id="paperformat_format2" model="report.paperformat">
            <field name="name">Format 2</field>
            <field name="default" eval="True"/>
            <field name="orientation">Portrait</field>
            <field name="margin_top">5</field>
            <field name="margin_bottom">3</field>
            <field name="margin_left">3</field>
            <field name="margin_right">3</field>
            <field name="header_line" eval="False"/>
            <field name="header_spacing">3</field>
            <field name="dpi">96</field>
        </record>
        <record id="paperformat_format3" model="report.paperformat">
            <field name="name">Format 3</field>
            <field name="default" eval="True"/>
            <field name="orientation">Portrait</field>
            <field name="margin_top">24</field>
            <field name="margin_bottom">18</field>
            <field name="margin_left">3</field>
            <field name="margin_right">3</field>
            <field name="header_line" eval="False"/>
            <field name="header_spacing">22</field>
            <field name="dpi">96</field>
        </record>
        <record id="formats.action_report_liberacion" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format1" />
        </record>
        <record id="formats.action_report_poliza" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format2" />
        </record>
        <record id="formats.action_report_factura_tipo1" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
        <record id="formats.action_report_factura_tipo2" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
        <record id="formats.action_report_factura_tipo3" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		 <record id="formats.action_report_MARKS2" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		<record id="formats.action_report_MARKS1" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		<record id="formats.action_report_GLOBAL1" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		<record id="formats.action_report_GLOBAL2" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		<record id="formats.action_report_GLOBAL3" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="formats.paperformat_format3" />
        </record>
		<menuitem name="csm" id="menu_naviero_main" sequence="25" />
    </data>
</openerp>

**Comment by JKE-be** [comment]
Use help.odoo.com for your question ... and in English
It is a tracker issue... And your error seems to be a customization ...

**Comment by carrasquel2016** [comment]
Excuse me I did not realize my practice not translated to English what happens is I'm a little desperate first time working with this tool and my job depends on the result you get with it:

My question is this: I require to get a PDF PickupOrder which will be a report that will contain all the data load travez .xml views which store information in databases Odoo therefore this report is diseñano in Dreamweaver for faster and save time, after that copy the code that generated the dreamweaver incrusté herrameinta and reports in a format Odoo respecting all parameters to generate the reports.

EL error que me genera es el siguiente
Current behavior:

The error that generates me is the following

ParseError: "ValidateError
Field(s) ´arch´  failed against a constraint: Invalid view definition

Error details:
The element '' can not be located in the parent view

Error de contexto:
Vista external_layout_header
[view_id: 997, xml_id: formats.external_layout_header, model: n/a, parent_id: 181]" while parsing None:4, near

## **The code  xml is the following: 
reportes_pickuporder.xml**

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <template id="report_factura_pickuporder">
            <t t-call="report.external_layout">
                <div class="header">
                    <t t-call="formats.css"/>
                    <div class="row fs_8px">
          <table  width="982" border="1">
              <tr>
                    <td width="622"><strong>GLOBAL SHIPPING AGENTES NAVIEROS CORP</strong></td>
                    <td colspan="2"><div align="center"><strong>Pickup Order</strong></div></td>
                  </tr>
                  <tr>
                    <td><h5><strong>RIF.:J-31201156-4</strong></h5></td>
                    <td width="114"><strong>Pickup Number:</strong></td>
                    <td width="224"></td>
                  </tr>
                  <tr>
                    <td><h5><strong>DOMICILIO FISCAL:</strong> Av. Domingo del Rosario C.C Empresarila Puerta del Sol, Nivel Planta 6, Of 13 Y 15  Sector Maiquetia, Edo. Vargas Telf.:(+58 212)332.17.30(+58 212)332.15.91(+58 212)332.21.89 (+58 212)332.18.71</h5></td>
                    <td><strong>Creation Date/Time:</strong></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td><h5><strong>DIRECCION SUCURSAL :</strong>Calle Bolívar c/Calle Regeneración, Edif. Simón Rodríguez, Piso 2, Ofic 9 Pto. Cabello Edo. Carabobo Telf.:(0242)361.39.38 Fax.: (0242)361.66.20</h5></td>
                    <td><strong>Pickup Date/Time:</strong></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td><h5><strong>DIRECCION COMERCIAL: </strong>Av. Venezuela, El Rosal, Municipio Chacao, Torre Oriental de Seguros, Piso 1, Caracas Venezuela Telf.Máster:(+58 212)951.34.56 Telf.Fax.: (+58 212)951.65.23</h5></td>
                    <td><strong>Delivery Date:</strong></td>
                    <td></td>
                  </tr>
                  <tr>
                    <td><h5><strong>DIRECCION  MARGARITA:</strong> Carretera Puerto Internacional el Guamache, Isla de Margarita, Edo. Nueva Esparta Telefax.:(0295)263.50.76</h5></td>
                    <td><strong>Employe :</strong></td>
                    <td></td>
                  </tr>
                </table>
<table width="986" border="1">
  <tr>
    <td colspan="2"><strong>Pickup Information </strong></td>
    <td colspan="2"><strong>Delivery Information</strong></td>
  </tr>
  <tr>
    <td colspan="2"><p></p>
    <p></p>
    <p></p></td>
    <td colspan="2"></td>
  </tr>
  <tr>
    <td width="90"><strong>Shipper</strong></td>
    <td width="221"></td>
    <td width="215"><strong>Consignee</strong></td>
    <td width="642"></td>
  </tr>
</table>
<blockquote>
  <blockquote>
    <blockquote>
      <blockquote>
        <blockquote>
          <blockquote>
            <blockquote>
              <blockquote>
                <p><strong>Inland Carrier and Supplier Information</strong></p>
              </blockquote>
            </blockquote>
          </blockquote>
        </blockquote>
      </blockquote>
    </blockquote>
  </blockquote>
</blockquote>
<table width="978" border="1">
  <tr>
    <td width="151"><strong>Carrier Name</strong></td>
    <td width="291"></td>
    <td width="141"><strong>Driver Licence</strong></td>
    <td width="367"></td>
  </tr>
  <tr>
    <td><strong>PRO Number</strong></td>
    <td></td>
    <td><strong>Supplier Name</strong></td>
    <td></td>
  </tr>
  <tr>
    <td><strong>Tracking Number</strong></td>
    <td></td>
    <td><strong>Invoice Number</strong></td>
    <td></td>
  </tr>
  <tr>
    <td><strong>Driver Name</strong></td>
    <td></td>
    <td><strong>P.O Number</strong></td>
    <td></td>
  </tr>
  <tr>
    <td><strong>Notes</strong></td>
    <td></td>
    <td><strong>Applicable Charges</strong></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="2"><p></p>
    <p></p>
    <p></p></td>
    <td colspan="2"></td>
  </tr>
</table>
<table width="978" height="395" border="1">
  <tr>
    <td width="91" height="26"><strong>PCS</strong></td>
    <td width="106"><strong>Package</strong></td>
    <td width="152"><strong>Dimensions</strong></td>
    <td colspan="2"><strong>Description</strong></td>
    <td width="101"><strong>Weight</strong></td>
    <td width="114"><strong>Volume</strong></td>
  </tr>
  <tr>
    <td height="25" colspan="2"><strong>PRO Number</strong></td>
    <td><strong>Invoice Number</strong></td>
    <td colspan="2"><strong>Notes</strong></td>
    <td><strong>Peso Weight</strong></td>
    <td><strong>Volume Weight</strong></td>
  </tr>
  <tr>
    <td height="224" colspan="2"></td>
    <td></td>
    <td colspan="2"><p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="4" rowspan="2">Signature:</td>
    <td height="37"><strong>Pieces</strong></td>
    <td><strong>Weight</strong></td>
    <td><strong>Volume</strong></td>
  </tr>
									<tr>
								<td width="72" height="37"></td>
							</tr>
					</table>
				</div>
			</t>
      </template>
        <template id="pickuporder">
            <t t-call="report.html_container">
                <t t-foreach="doc_ids" t-as="doc_id">
                    <t t-raw="translate_doc(doc_id, doc_model, 'partner_id.lang', 'formats.report_factura_pickuporder')"/>
                </t>
            </t>
        </template>
    </data>
</openerp>


SUPPLEMENTARY FILES ARE TO GENERATE PDF: 

nombre : _openerp_.py

# -*- coding: utf-8 -*-
{
    'name': "formats",
    'version' : '9',
    'summary': """
        Simple module to test some functionalities and make some examples related to the
        QWeb reporting facilities of Odoo V8""",

    'description': """
Qweb Report Examples
====================
Simple module to test some functionalities and make some examples related to the QWeb reporting facilities of Odoo V8

Tener en cuenta:
----------------
* Leer bootstrap: http://getbootstrap.com/css/
* Ver qweb en https://doc.openerp.com/trunk/web/qweb especialmente las directivas de q-web en https://doc.openerp.com/trunk/web/qweb/#defining-templates
* Probar css http://jsfiddle.net/h8SBh/1/
* Para reportes y css!!! http://ksesocss.blogspot.com/2012/05/estilos-css-para-imprimir-la-regla-page.html 
* Los reportes constan basicamente de:
    * Un registro en la clase de reportes (ir.actions.report.xml) que se puede crear con el atajo "<report". Se suelen crear todos los reportes de un modulo en el archivo "[nombre_de_modulo]_report.xml"
    * Cada reporte qweb tiene además vistas definidas, dichas vistas se suelen guardar en la carpeta views. Se crea un archivo para cada reporte
    * Si se requieren funcionalidades avanzadas, se pueden crear archivos .py que modifican el funcionamiento por defecto de los reportes, eso suele ir en la carpeta "reports" (solo archivos .py). En dicha carpeta se suelen almacenar también los cubos (su corresndiente .py y .xml)
    * Si se requiere de un wizard, tanto el .py como el .xml irían en la carpeta "wizard"
* Respecto a las vistas de reportes
    * Se pueden heradar como cualquier vista. Es recomendable probarlo desde la interfaz de odoo ya que al querer guardar el registor nos va a validar si la vista es correcta o no. Luego lo llevamos al modulo.
* Respecto a los reportes:
    * Resulta muy practico empezarlos con tipo html, al pedir una vez el reporte se abre una nueva ventana, pero podemos copiar la url y llevarla a nuestro explorador. Luego simplemente refrezcando podemos tener actualizaciones del reporte.
    """,

    'author': "edbin",
    'website': "",

    # Categories can be used to filter modules in modules listing
    # Check <odoo>/addons/base/module/module_data.xml of the full list
    'category': 'Uncategorized',

    # Agregamos estas dependencias para el ejemplo, website lo ponemos para que sea editable en interfaz web
    'depends': ['base','account'],
    'data': [
        # cargamos las vistas de los reportes        
        'views/report_liberacion.xml',
        'views/report_poliza.xml',
        'views/report_factura_tipo1.xml',
        'views/report_factura_tipo2.xml',
        'views/report_factura_tipo3.xml',
        'views/report_factura_marks1.xml',
        'views/report_factura_marks2.xml',
        'views/GLOBAL1.XML',
        'views/GLOBAL2.XML',
        'views/GLOBAL3.XML',

                
        # Mostramos herencia de reportes, modificamos el header y footer por defecto
        'views/report_external_layout_header.xml',
        'views/report_external_layout_footer.xml',
        # cargamos los reportes
        'views/report_pickuporder.xml',
        'format_report.xml',
        'views/templates.xml',
    ],
    "images":['img/laempresa.jpg',],
    'demo': [
    ],

    'tests': [
    ],
}

Similarly thanks for your suggestions I leave the code if you could help me and montare in helpodoo.com to verify some suggestions
Happy day..

**Comment by lukebranch** [comment]
@carrasquel2016 ,

Github issues are not the place for getting help, they are for reporting bugs and issues with the core platform. I'd highly recommend asking for advice in the community mailing list here:

https://www.odoo.com/groups

specifically the 'Community' mailing list, and also try the help forums as suggested above (help.odoo.com).

I'd suggest closing this issue and trying in the mailing list and forums.

**Comment by carrasquel2016** [comment]
Thanks
