### ISSUE TITLE
[8.0][9.0] Kernel modules not loaded when run posbox create image script

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#12650]
Impacted versions: [8.0][9.0] 

Steps to reproduce:
- Dowload posbox tools from:
https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox
- Open posbox directory in terminal
- Run script: `sudo ./posbox_create_image.sh`
- When finish script, [write the image](http://elinux.org/RPi_Easy_SD_Card_Setup) **posbox.img** to the SD card
- Connect a Ethernet cable to the Raspberry­.
- Ensure the printer is powered on, and connected to the Raspberry
-  Connect a barcode scanner to the Raspberry
- Insert the SD card in the Raspberry and power on
- After +/- 1 minute the printer would print the IP address of the Raspberry
- Open a browser and go to the IP address given

Current behavior:

- Once in the PosBox Homepage, select hardware status page link. The barcode scanner mark an error:

![2_odoo_s_posbox](https://cloud.githubusercontent.com/assets/5335402/16504062/a36415e0-3edb-11e6-9c4f-f82d1ce30732.png)

- Looking for the source of the problem, connected by ssh to the Raspberry-PI ran the command lsmod who shows which loadable kernel modules are currently loaded, and then: No modules loaded... I try to add manually usblp module but i figured out that path ` /lib/modules/$(uname -r)` not exist

![1__pi_raspberrypi_____ssh_](https://cloud.githubusercontent.com/assets/5335402/16504787/57af1b1e-3edf-11e6-8468-4b7c2934af49.png)

- Consequently, kernel modules that allow me to recognize when i connect the scanner is not loaded. When connect a barcode scanner should be loaded the file `/dev/input/event*`

Expected behavior:
- Kernel modules should be loaded, like this:
![2_pi_raspberrypi___lsmod](https://cloud.githubusercontent.com/assets/5335402/16504940/382afadc-3ee0-11e6-837b-11ec84b6fc1d.png)
- Barcode scanner should be appear connected, like this
![1_odoo_s_posbox](https://cloud.githubusercontent.com/assets/5335402/16504372/441f8dd8-3edd-11e6-88de-017fa6af978d.png)
- **NOTE:** I download and installed the latest posbox image from: http://nightly.odoo.com/trunk/posbox/ to reproduce the expected behaviour

### Pseudo-FIX:
- In another attempt, i had to change the script [posbox_download_image.sh]
(https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/tools/posbox/posbox_download_images.sh) to download the [same raspbian version](https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2016-03-18/) used for [posbox_image_v14](http://nightly.odoo.com/master/posbox/) and reproduce the steps described initially

- But, problem still persists, kernel modules not loaded because the path `/lib/modules/$(uname -r)` not exist.
![4__pi_raspberrypi_____ssh_](https://cloud.githubusercontent.com/assets/5335402/16506738/05499a88-3eea-11e6-9cd0-7fee2965b542.png)

- Now, having the same raspbian version (uname -r), i solved the problem copying the path `/lib/modules/4.1.19-v7+` from SD card with [posbox_image_v14](http://nightly.odoo.com/master/posbox/), and paste in `/lib/modules` in SD card with the image create with `./posbox_create_image.sh`
![3__pi_raspberrypi___root_bypass_ramdisks_lib_modules__ssh_](https://cloud.githubusercontent.com/assets/5335402/16506824/c23eae58-3eea-11e6-90a9-f64463324a9b.png)

- Wait a moment while restarting, and open a browser and go to the IP address given by the printer
![3_odoo_s_posbox](https://cloud.githubusercontent.com/assets/5335402/16507076/b4bb0b94-3eec-11e6-8ad5-091608212c2f.png)

- This solution is not the right way, the ideal case is when run the script, the kernel modules should be loaded

**P.D:**  I am using a Raspberry Pi 3

**Comment by jorenvo** [comment]
Fixed in 8.0 at 75dbd545c85182feeaf138f0155a82aa203fcf7c.
