### ISSUE TITLE
[16.0] AccessError when trying to import contact for current company without invoicing groups

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#126567]
Impacted versions: 16.0

Steps to reproduce:
On runbot :
1. Connect as admin / admin
2. Remove invoicing access rights from Marc Demo
3. Disconnect and reconnect as demo / demo
4. Check that active company = My Company (San Francisco)
5. Go to contacts, Favorites > Import records
6. Select a CSV file with the following content :
```csv
id,is_company,name,type,parent_id,email
test,0,Test contact,Contact,My Company (San Francisco),test@mycompany.com
```
7. Click on import

Current behavior:
Access error is raised because you are not allowed to access credit.limit field.
```
Unknown error during import: <class 'odoo.exceptions.AccessError'>: The requested operation can not be completed due to security restrictions. Document type: Contact (res.partner) Operation: write User: 6 Fields: - credit_limit (allowed for groups 'Technical / Show Accounting Features - Readonly', 'Invoicing / Billing') at row 2 (Test contact)
Resolve other errors first
```

Expected behavior:
Import should be performed without error
credit.limit should not be set from this import (it is not set when creating contact manually from web interface)

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/30716308/8438e383-a08e-4930-8902-1d2b601be574)

**Comment by remi-filament** [comment]
@epictete would you mind having a look at this issue (since credit_limit on res.partner was introduced by https://github.com/odoo/odoo/commit/ff0275be6b937487f22b672f5d29f20ac439fefc) ?

**Comment by william-andre** [comment]
@epictete `<res.partner>._update_fields_values` shouldn't be updating the records (injecting the value in `values`) if the value didn't change.
It might cause issues because the field won't be protected anymore though...

**Comment by epictete** [comment]
Hello @remi-filament 
Thanks for the feedback :+1: 
The PR with the fix has been created here : https://github.com/odoo/odoo/pull/129587
