### ISSUE TITLE
[9.0][IMP] optimize workflow execution

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#12660]
Impacted versions:
9.0 (and versions before this too probably)

Steps to reproduce:
* craete any model instance

Current behavior:
1. On create: A new workflow query is executed every time even if that model has no workflows. Cache is being ignored due to incorrect null check (null/empty check is used insted).
2. On write: A query for existing workflow instances is executed on each write even if there are no workflows for the model. This is very intimidating since ORM generates lots of updates and some of them are couple with that workflow check.

Expected behavior:
No need to create/execute workflow if it is not active for a model.

Some one could create a PR with a solution like this:
`

    def create(self):
        wkf_ids = self.get_wkf_ids()

        for (wkf_id, ) in wkf_ids:
            WorkflowInstance.create(self.session, self.record, wkf_id)

    def get_wkf_ids(self):
        WorkflowService.CACHE.setdefault(self.cr.dbname, {})

        wkf_ids = WorkflowService.CACHE[self.cr.dbname].get(self.record.model, None)
        #should only check for None, otherwise cache does not make sense here...
        if wkf_ids == None:
            self.cr.execute('select id from wkf where osv=%s and on_create=True', (self.record.model,))
            wkf_ids = self.cr.fetchall()
            WorkflowService.CACHE[self.cr.dbname][self.record.model] = wkf_ids
        return wkf_ids

    def write(self):
        wkf_ids = self.get_wkf_ids()
        if not wkf_ids:
            return
        self.cr.execute("select id from wkf_instance where res_id=%s and res_type=%s and state=%s",
            (self.record.id or None, self.record.model or None, 'active')
        )
        for (instance_id,) in self.cr.fetchall():
            WorkflowInstance(self.session, self.record, {'id': instance_id}).update()

`

**Comment by odony** [comment]
Every deployment is different, with different architectures, different users, different workloads.
For any bug report / enhancement request regarding performance, it is important to show real life numbers (times befores, times after, size of the sample records, etc.), and detailed information for testing/reproducing. 

You're suggesting patch, so it's important to know on what grounds.

For the record, a transaction that updates the database (such as `create()`) executes hundreds of queries, and the workflow definition table is very small. So the few workflow-related queries will be very fast. Caching them would presumably have no impact on the performance, but cause more cache invalidation burden.

If you have specific numbers to confirm that caching workflows does make a difference, we'll be glad to reopen this issue.

**Comment by ke-real** [comment]
You don't usually create workflows on the fly, so no cache problems as I see it.
"So the few workflow-related queries will be very fast" is not an excuse of doing meaningless queries...
