### ISSUE TITLE
XmlRcp error: dictionary key must be string

### ISSUE THREAD

**Issue by MatthiasVets** [odoo/odoo#12667]
Hi,

when fetching lunch.order via XmlRcp I get this error:

File "C:\Program Files (x86)\Odoo 9.0-20160629\server\.\openerp\service\wsgi_server.py", line 57, in xmlrpc_return
  File "xmlrpclib.pyc", line 1091, in dumps
  File "xmlrpclib.pyc", line 638, in dumps
  File "xmlrpclib.pyc", line 660, in __dump
  File "xmlrpclib.pyc", line 741, in dump_struct
  File "xmlrpclib.pyc", line 660, in __dump
  File "xmlrpclib.pyc", line 741, in dump_struct
  File "xmlrpclib.pyc", line 660, in __dump
  File "xmlrpclib.pyc", line 739, in dump_struct
TypeError: dictionary key must be string

Is there anything I can do to fix this?
As I understand is this a problem of the xmlrpclib about the key not being a string.

**Comment by MatthiasVets** [comment]
Hi all, 

I quickfixed it with this piece of code in wsgi_server.py
If anyone has a better solution I'm all ears!

```python
def fix(res):
	"""
	This fix is a minor hook to avoid xmlrpclib to raise TypeError exception: 
	- To respect the XML-RPC protocol, all "int" and "float" keys must be cast to string to avoid
	  TypeError, "dictionary key must be string"
	- And since "allow_none" is disabled, we replace all None values with a False boolean to avoid
	  TypeError, "cannot marshal None unless allow_none is enabled"
	"""
	if res is None:
		return False
	elif type(res) == dict:
		return dict((str(key), fix(value)) for key, value in res.items())
	else:
		return res

""" Then use this def to set/modify result """

result = fix(openerp.http.dispatch_rpc(service, method, params))

```

**Comment by Tek-Nitin** [comment]
Hi,

I am facing a similar error when running 

models.execute_kw(db, uid, password, f'{model_name}', func_name, [[]])

for model account.move.line on function search_read. Is there a way to resolve this?

**Comment by Ciangi** [comment]
> Hi,
> 
> I am facing a similar error when running
> 
> models.execute_kw(db, uid, password, f'{model_name}', func_name, [[]])
> 
> for model account.move.line on function search_read. Is there a way to resolve this?

Same problem.

**Comment by Tek-Nitin** [comment]
> > Hi,
> > I am facing a similar error when running
> > models.execute_kw(db, uid, password, f'{model_name}', func_name, [[]])
> > for model account.move.line on function search_read. Is there a way to resolve this?
> 
> Same problem.

I just found out that the issue was due to 1-2 fields. I just presented the list of fields as parameter and ignored the ones causing this. For now this is how i made my code work.
