### ISSUE TITLE
No https in sitemap after 24 hours

### ISSUE THREAD

**Issue by yogurtnaturalny** [odoo/odoo#12666]
Impacted versions:
odoo community 9 02/06/2016 ( EU date stamp so 2nd July )
Steps to reproduce:
Nginx with TLS 1.2 as a proxy to separate server on port with 8069 where I set up proxy_set_header X-Forwarded-Proto https, also I enable web.base.url with https and remove old site map. Nginx got "if" config to redirect to https and that slow down whole odoo and performance. 

Current behavior:
site map with http link
Expected behavior:
site map with https links 
Video/Screenshot link (optional):
https://www.posesja-on.com/sitemap.xml

**Comment by JKE-be** [comment]
Hello,

Sitemap don't use web.base.url but `request.httprequest.url_root`.

I have just checked, and the redirection from http to https is done with a 301, so it should work.
Can you check the content of the attachment in db and be sure that it is not the cache of CF which are not updated... ?

**Comment by yogurtnaturalny** [comment]
Hi, thank you for quick response. `web.base.url ` I found after some googleing. I would like to know where i can  find `request.httprequest.url_root` in ui or do I have to get look into code? This looks a little like a Django framework so this might be easier to find for me.

**Comment by JKE-be** [comment]
**request.httprequest.url_root** is a werkzeug variable... not computed/configured by Odoo... 
(http://werkzeug.pocoo.org/docs/0.11/wrappers/)
https://www.posesja-on.com/ in your case...
Have you checked your sitemap content in the attachment directly ?

**Comment by JKE-be** [comment]
If you add a new page, and delete ir.attachment with name sitemap*.xml...

Is the new page in your sitemap ?

**Comment by yogurtnaturalny** [comment]
Hello 

Thx, mate. Just give me a few sec, I'm just new with odoo and werkzeug so that is little bit harder for me.

**Comment by yogurtnaturalny** [comment]
Hi

Yes, I can confirm that I remove from database line about site map, I removed flush memory, restart server and still nothing... still http, and test page show up in in sitemap... :-( :-1:

**Comment by JKE-be** [comment]
Semmes that your alternate languag is wrong also... (use http and not https)

What is the output of : <t t-esc='request.httprequest.url_root'/> ?

**Comment by JKE-be** [comment]
Have you launched your server with **--proxy_mode** ?

**Comment by yogurtnaturalny** [comment]
Hey 

I set up proxy mode in odoo .conf on true ( before that I had internal IP in site map), is something what I missing here ? 

Website is build in Polish ( and I do not set up other lang on frontend ) and for my employees back end is in polish too, but for me as admin I keep back end in English.

**Comment by yogurtnaturalny** [comment]
Hi

Nginx, is setup to support a little bit more then this tutorial 

location / {	
	#root /var/www;
	#index index.php index.html;	

	
        proxy_pass http://my_lxc_internal_ip:8069;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
	proxy_set_header HTTP_X_FORWARDED_HOST $remote_addr;
	proxy_redirect off;
	#proxy_cache my_zone;
	#proxy_cache_revalidate on;
	#proxy_cache_min_uses 3;
	#proxy_cache_lock on;
	#error_page 404 errors/404.html;
	#error_page   500 502 503 504  errors/50x.html
	access_log /var/log/nginx/posesja.log;

I comment out cache for now

**Comment by yogurtnaturalny** [comment]
I thing this might be related to this issue sort of... https://github.com/odoo/odoo/pull/10363

**Comment by joolsr** [comment]
Hi. I had some issues same as #10363. I had my nginx config same as yours ie proxy_set_header    X-Forwarded-Proto https; but mart-e actually has his as proxy_set_header    X-Forwarded-Proto $scheme

In the end to get it to work (and my sitemap does show https links), i used mart-e's 3 proxy-set headers, and no others and ensured that the web.base.url did have https://webaddress as before (for reasons I dont remember) it didnt. The syntax for the proxy-set lines is easily put in incorrectly, as you do not receive errors until you find pages ie slides with non https content. Good luck, it kept me guessing for quite a while. I can share my nginx config if its useful

**Comment by yogurtnaturalny** [comment]
Hi

Thx, mate. I will try with $scheme and we will see. Also Can you post how do you redirect to https please on nginx ?

**Comment by yogurtnaturalny** [comment]
Hello 

Thank you for all your help, this is fantastic that we can share our knowledge in community. I notice that my sitemap is for some rezon odd. Till now is not https also test page what I have delete more then 12 hours ago is till there, so I would like to say is very odd. Or my system is caching some were files, or is a bug, or I cant turn proxy mod in right way. When I turn on odoo in conf file to use proxy mode in sitemap internal IP change to domain name what is good but when I check logs they are will show nginx internal ip. So... I would like to ask for official way to turn on odoo in to proxy mode, a official way to refresh sitemap ( I'm not a programmer so some helpful steps might be appreciated ), because I'm loosing faith in this product if I can't provide a full encryption for my clients, and my google rank is going down for errors on my website. This is a real problem and keep me back from purchase the licence. If someone would like to help me I can give a line of beer because I like how odoo is really powerful program to fit all my needs. If someone can help me, please do.

**Comment by joolsr** [comment]
I used this
http://www.schenkels.nl/2014/12/reverse-proxy-with-odoo-8-nginx-ubuntu-14-04-lts/

There are also now versions for Odoo v 9 but in terms of nginx etc its not
changed much.

Julian

**Comment by yogurtnaturalny** [comment]
Hello 

Thank you, all of you. I thing we cross a line where I change all setup from odoo to nginx and I feel I lost a battle. There is something broken in odoo and maybe is because I don't use English as a main language or maybe because #Brexit but till now this is still a thing and "should work"  is not good where money are involved. I thing I will design a website with Django or CakePhp and in a future I will come back to odoo when problem with https will be solved! Last thing what I might to try is wsgi, but I might loose some features.

**Comment by mart-e** [comment]
Some users had issues with the sitemap in http but it was due to the configuration of CloudFlare (which they used to be able to have their own SSL certificate). Not sure if it is the case but worth checking if you are using it.
We have also noticed to get issues with `proxy_set_header X-Forwarded-Proto $scheme` behind a load balancer (but again I don't think it's the case for you).

We will work on our [deployment doc](https://www.odoo.com/documentation/9.0/setup/deploy.html) to improve it but I can unfortunately only say "it should [work](https://www.odoo.com/sitemap.xml)" :-/

**Comment by JKE-be** [comment]
The doc has been updated: https://www.odoo.com/documentation/9.0/setup/deploy.html#https
Maybe it could help you ;)

**Comment by v-garcies** [comment]
Hello ! I had the same problem today with an odoo website and I solved it with this rule in my Nginx vhost :
    
    proxy_set_header Accept-Encoding "";

(replace all ``proxy_set_header`` rules with the rule above)

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#headers
