### ISSUE TITLE
Feature Request:  Add sub-task count (shown only in Kanban View) to the tab label of the Project Task view

### ISSUE THREAD

**Issue by ianbmacdonald** [odoo/odoo#126891]
Impacted versions:15.0

Steps to reproduce: When looking at Kanban view the team can see which Tasks are more complex, by observing their sub-task count, which is shown in the minimized task view, shown below in an example with 10 sub tasks

![image](https://github.com/odoo/odoo/assets/6287157/cf61420e-c6e3-42a3-b5b0-c9cba24d509a)

When you click on that task, perhaps in a collaborative session with stakeholders,  the fact that there is 10 sub tasks is not shown anywhere in the Task view.  In the situation where simple tasks have no sub-tasks, and more complex ones have many,  there is no way to determine if the task you are looking at has any sub-tasks or not from the default task view.    This holds true for the people you may be showing the task too .. if they see 15 sub tasks, they might ask you what those are, instead of assuming the description is the body of work you are talking about. 

It would be really helpful to take the sub-task count, which we know is an available variable or function from its use in the Kanban view, and put that value into the the Sub-Tasks tab as a dynamic tab label.

Current behavior:

In the tasks view, the sub-tasks tab shows the title "Sub-tasks" without any indication of how many (if any) are present

Expected behavior:

In the tasks view, show the sub-tasks counter used in the Kanban task minimized view to show a title "Sub-tasks (10)" to indicate there are 10 sub-tasks.   This way anyone reviewing a task with the stakeholder knows to go review them after going through the description without having to do some extra clicks to confirm there are none, or some there.   it also provides a birds eye view of the task complexity or maturity for anyone that is looking at the task view on their screen. 

ChatGPT Brainstorming link (optional):
https://chat.openai.com/share/5b5a8f3e-e899-4859-823c-710e018fd96e

No idea if these model fields and objects are accurate but the approach sounds viable for a more experienced Odoo developer;  If the QWeb template change is that simple, this could be dead easy if the value is available from the model already as shown in the current Kanban view.  

Support ticket number submitted via odoo.com/help (optional):

**Comment by MissingNoShiny** [comment]
Hello, as far as I know, this is not easily doable, and the solution given by ChatGPT will not work. :confused: 
However, in version 16+, there is a sub-tasks stat button in the task form view displaying this information.

Have a nice day! :slightly_smiling_face:
