### ISSUE TITLE
PyParsing < 2 required for Odoo but  PyParsing > 2.1.4 required for pydot

### ISSUE THREAD

**Issue by scigghia** [odoo/odoo#12693]
Impacted versions: odoo > 8.0

https://github.com/odoo/odoo/blob/8.0/setup.py#L148 
why pyparsing < 2 is still required ?
when i install pydot it uses pyparsing > 2.1.4

**Comment by Yenthe666** [comment]
@mart-e what do you think about this one?

**Comment by mart-e** [comment]
@sle-odoo can we backport 6ceb0a2b1b922e2a1289baecc1c46d661f9a6a70 to 8.0?

**Comment by sle-odoo** [comment]
yes we can

**Comment by scigghia** [comment]
thank you :)
