### ISSUE TITLE
[9.0] point_of_sale: Missing simplejson and unittest2 in posbox image

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#12694]
Impacted versions: [9.0]

Steps to reproduce:

- Dowload posbox tools from: https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox
- Open posbox directory in terminal
- Run script: sudo ./posbox_create_image.sh
- When finish script, write the image posbox.img to the SD card
- Connect a Ethernet cable to the Raspberry­.
- Ensure the printer is powered on, and connected to the Raspberry
- Connect a barcode scanner to the Raspberry
- Insert the SD card in the Raspberry and power on
- After +/- 1 minute the printer would print the IP address of the Raspberry
- Open a browser and go to the IP address given

Current behavior:
- Odoo server does not start automatically
- When i try to start manually:
```
ImportError: No module named simplejson
```
- Current packages to install: [init_posbox_image.sh] (https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh#L17) _- without simplejson and unittest2 -_
```
PKGS_TO_INSTALL="adduser postgresql-client python python-dateutil python-decorator python-docutils python-feedparser python-imaging python-jinja2 python-ldap python-libxslt1 python-lxml python-mako python-mock python-openid python-passlib python-psutil python-psycopg2 python-pybabel python-pychart python-pydot python-pyparsing python-pypdf python-reportlab python-requests python-tz python-vatnumber python-vobject python-werkzeug python-xlwt python-yaml postgresql python-gevent python-serial python-pip python-dev localepurge vim mc mg screen iw hostapd isc-dhcp-server git rsync console-data"
```

Expected behavior:
- Odoo server should start automatically
- Packages to install: _- including simplejson and unittest2 -_
```
PKGS_TO_INSTALL="adduser postgresql-client python python-dateutil python-decorator python-docutils python-feedparser python-imaging python-jinja2 python-ldap python-libxslt1 python-lxml python-mako python-mock python-openid python-passlib python-psutil python-psycopg2 python-pybabel python-pychart python-pydot python-pyparsing python-pypdf python-reportlab python-simplejson python-tz python-unittest2 python-tz python-vatnumber python-vobject python-werkzeug python-xlwt python-yaml postgresql python-gevent python-serial python-pip python-dev localepurge vim mc mg screen iw hostapd isc-dhcp-server git rsync console-data"
```

**Comment by jorenvo** [comment]
Hi José,

Thank you for your detailed report but the scripts we publish and maintain are used to build our official POSBox image which currently runs Odoo 8 (see [1] for more information). Generating a POSBox image running Odoo v9 is not something we currently support.

[1] https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html#posbox-technical-documentation

/cc @mart-e 


Kind regards,
Joren
