### ISSUE TITLE
Website Builder SEO Promote Keywords: unable to delete keyword, when it is too long

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12703]
Impacted versions:
9.0 CE 2016-06-29

Steps to reproduce:
Create a keyword which has more characters than allowed

Current behavior:
Keyword is cut to appropriate length, but the x-handle to delete it disappears.

Expected behavior:
x-handle to delete is still shown and remains visible.

Video/Screenshot link (optional):

![selection_220](https://cloud.githubusercontent.com/assets/1814941/16621280/fcdc31fc-4395-11e6-8045-657d56fe325f.png)

**Comment by Yenthe666** [comment]
Hah, that is an hilarious one.
@JKE-be can you make this a bit more user friendly?

**Comment by treviser** [comment]
It is still possible to delete the keyword by clicking on the place where one supposes the x-handle to be, but only as long as the SEO promote window is not saved. After the window is saved, it is not possible to delete the keyword anymore.

**Comment by JKE-be** [comment]
Thanks for the reporting.
It has been fixed ...
