### ISSUE TITLE
Uncaught TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by liquidleds** [odoo/odoo#12702]
Impacted versions: Version 9.0e (Enterprise Edition)

Steps to reproduce: 
Go to sales dashboard
Click on  Invoiced button in Performance it gives me trace back 

Video/Screenshot link (optional):
https://drive.google.com/file/d/0B32trVtlgr0rcFZHTFVNbkU1Ykk/view?usp=sharing

**Comment by Yenthe666** [comment]
Hi @liquidleds,

I've just tested this on a runbot and the view opens without any issues. You're talking about this button right:
![image](https://cloud.githubusercontent.com/assets/6352350/16620015/107d9c14-4391-11e6-95f7-cd6cdaea114f.png)
Can you please test this on the latest 9.0 runbot?

**Comment by Yenthe666** [comment]
Closing as there has been no response and as it should be fixed.
