### ISSUE TITLE
No report file attached after created a new report in Open ERP Report Designer

### ISSUE THREAD

**Issue by krmagnaye** [odoo/odoo#12708]
Impacted versions:
Version 7

Steps to reproduce:

```
Open Office Writer Menu - > OpenErp Report Designer
Server Parameter> Add Loop >Add field
Send to the Server>> Send report to Server
```

![2](https://cloud.githubusercontent.com/assets/19465728/16643967/cb1ca6c2-444b-11e6-8871-5995a81242a6.JPG)

Current behavior:

Open Erp (Odoo)
No report file attached after created a new report in Open ERP Report Designer

Reports>>test_report_m3

![1](https://cloud.githubusercontent.com/assets/19465728/16643944/a570c82c-444b-11e6-86c8-db1c49c7c9d8.JPG)
![3](https://cloud.githubusercontent.com/assets/19465728/16643987/fff55740-444b-11e6-9376-278f32820e69.JPG)

Expected behavior:

Expecting there's a path file for the report file added

**Comment by Yenthe666** [comment]
Hi @krmagnaye,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
