### ISSUE TITLE
select invoice at point of sale client is loading

### ISSUE THREAD

**Issue by melvinmartinez** [odoo/odoo#1270]
when a customer is selected at the point of sale invoice with the option gets the status "loading" and does not go ...

![image](https://cloud.githubusercontent.com/assets/8202051/3627780/41fe33b0-0e8d-11e4-8b6c-e6202e374bbf.png)

**Comment by Yenthe666** [comment]
Hi @melvinmartinez ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: This should have been fixed ages ago in V8.

Regards,
Yenthe
