### ISSUE TITLE
Infinite creation of recurrent events when number of repetitions equals 0

### ISSUE THREAD

**Issue by venisse-a** [odoo/odoo#12715]
Impacted versions: 8.0

Steps to reproduce: create a recurrent event with repeat every day and number of repetitions 0 (same with a space in the field)

Current behavior: Infinite creation of events that causes an endless loading page

Expected behavior: Send an error message the same as when you enter a char in the same field

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Fixed in commit odoo/odoo@3418b9f8aa052ae0aabf940d6332cc0aa77d409d
Thanks for the reporting
