### ISSUE TITLE
Error al momento de generar upgrade del módulo l10n_ec

### ISSUE THREAD

**Issue by OpenAlliance-EC** [odoo/odoo#127181]
Impacted versions: 16

Steps to reproduce:

1) Ejecutar el asistente de upgrade de odoo sh desde una base de datos en la version 15

Current behavior: Se presenta el siguiente error 

For external id l10n_ec.ec110502 when trying to create/update a record of model account.group.template found record of different model account.account.template (23392)

Expected behavior: Que el proceso de migracion se realice de forma exitosa

Video/Screenshot link (optional): 
![imagen](https://github.com/odoo/odoo/assets/137905141/28c03a72-a48d-4c9e-8122-e951c180443e)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @OpenAlliance-EC 
As the error message states, please contact the [support](https://www.odoo.com/help) for such an error in the upgrade process.
Cheers.
