### ISSUE TITLE
Traceback when sending an invoice to a finish customer

### ISSUE THREAD

**Issue by AntoineSadzot** [odoo/odoo#127277]
Impacted versions:
15.0, 16.0

Steps to reproduce:
On an invoice to a Finnish customer (configured with Finnish language) click on "Send & print" (action_sent_mail).

Current behavior:
An error appears when odoo tries to generate the email (cfr linked image)

Expected behavior:
Display the wizard to send & print invoices.

Origin:
See link for v15 below. There is a "{" too much in the Finnish translation of field mail_template.report_name
https://github.com/odoo/odoo/blob/112827a083160e41b7b5c7d0d9bf52deaf627963/addons/account/i18n/fi.po#L7409

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/32466900/f98ee6ee-866d-48b3-8c7c-71b31fbf8981)
![image](https://github.com/odoo/odoo/assets/32466900/b8b5fee4-4708-4386-ba5f-11f5a194619c)

**Comment by vava-odoo** [comment]
Hello @AntoineSadzot,

Thanks for the contribution but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github.

Please submit your changes there and let me know if you have issues.

Thanks
