### ISSUE TITLE
Improper Error Message

### ISSUE THREAD

**Issue by vgo-dev** [odoo/odoo#12731]
Current behavior:
Open foram in website without login and open any Question/Answer and do action like up-voting,Down-voting etc.. at that time given error message like you require xxx karma but if user not login then why gives information about karma,

Expected behavior:
As expected behavior is gives simple error please login to do this action

Video/Screenshot link (optional):
![foram-issue](https://cloud.githubusercontent.com/assets/12181723/16682894/6df137a4-451a-11e6-9fa4-7f19136833e7.jpg)

**Comment by mart-e** [comment]
Well it's not really wrong either. You do need 5 karma to post the message.
Pull request welcome for master but not a bug.

**Comment by vgo-dev** [comment]
Its not bug that i understand but the error message is wrong if you are not login then what is the need to preset about our requirement(karma) ??
if i am wrong then please correct me,
Thank you

**Comment by mart-e** [comment]
It's an improvement to make the forum more user friendly but it's not wrong (let say the public user has already 5 karma). As said above, don't hesitate to submit a pull request for master to improve it

**Comment by vgo-dev** [comment]
thank you so much for this about pull request :+1:
