### ISSUE TITLE
[8.0] Too dark font color in main menu

### ISSUE THREAD

**Issue by dskarataev** [odoo/odoo#1274]
Hi! It becomes difficult to see main menu, please make brighter letters.

![darkmenu_odoo](https://cloud.githubusercontent.com/assets/1011632/3634220/f54e2f94-0f1c-11e4-9645-58c1060101f6.png)

**Comment by isometriq** [comment]
Agreed, had the same complaint from others many time

**Comment by fclementic2c** [comment]
+1

**Comment by alejandrosantana** [comment]
Agreed.

**Comment by matthieuchoplin** [comment]
I think that module does that: https://github.com/Smile-SA/odoo_addons/tree/8.0/smile_menu_contrast

**Comment by Yenthe666** [comment]
@sle-odoo any update on this? I still think the contrast should be a bit bigger so it is easier to read. 😉

**Comment by sle-odoo** [comment]
@Yenthe666 it's very unlikely that we change the colour in v8, and you can change the color easily in later version by changing a less variable, and in the latest version you can edit it with the less editor

You can make a pr to slightly adapt the colours for master if you want :)

Regards
