### ISSUE TITLE
Chinese Translation Issue In the DateTimeField

### ISSUE THREAD

**Issue by deyun-zeng** [odoo/odoo#1275]
I install odoo v8 with ubuntu14.04 & pg9.3 in Vagrant , I load the chinese translation , but got a error when I creat a Logged Call , The time is "xx/xx/xxxx xx:xx:xx 上午" , **_The datetimefield can't save!**_ I change the value of  "amDesignator" at odoo/addons/web/static/lib/datejs/globalzation/zh-CN.js(zh-TW.js),But still errors!

**Comment by Yenthe666** [comment]
Hi @deyun-zeng,

Sorry for the late reply. I just tried this on the latest Odoo 8.0 without any problems. If you still face this please update your source code and try again. 😄 
If you still face this issue please look at Transifex (transifex.com/odoo/) where the Odoo translations are handled. There is most likely an error in one of the translations that is causing this.

Regards,
Yenthe
