### ISSUE TITLE
[9.0] Mixing oranges with potatoes, debug vs. group access evaluation on BaseModel

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#12753]
Please check this piece of code:
https://github.com/odoo/odoo/blame/9.0/openerp/models.py#L1374

What's the idea of doing a check if debug mode is active at `BaseModel` level?

This should be done at `ir_ui_view`, which is the model handling this kind of operation, to be more precise at:
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_ui_view.py#L700

**Comment by aristobulo-eezee** [comment]
@odony when you have some time, please check this out

**Comment by odony** [comment]
As of 9.0 every user is a member of `base.group_no_one` but this group only becomes effective in developer/debug mode. This is where we kind of "mix" both concepts, for a functional reason.
So the idea behind this code is to make `user_has_group()` behave consistently with this logic everywhere, not just for views. In particular the "technical features" group affects the menus as well. 
For more information you can have a look at [the original commit](31518bc09b1ae2be37c3555799e2c122f0a4dbcd).

**Comment by aristobulo-eezee** [comment]
@odony Ok, but you did it on `ir.ui.menu` for the menu items instead of `BaseModel`. The root problem is that in fact, your hide many visual elements for `group_no_one` unless users activate developer mode, but these hidden elements (menus, fields, tabs, etc.) were displayed without activating it on v8 and prior.

If you look for `group_no_one` on xml files, you will find almost 300 hundred elements and they are not just technical elements, I'm talking about simple fields containing relevant information for functional users (i.e: date_due on `account.invoice` or . 

Right now we have to inherit every one of these elements to get them back, because our customers had it on v8 and now they don't see it.

Having this on `ir.ui.view` level, like on `ir.ui.menu` provides a cleaner way to inherit the model and avoid hiding so many UI elements and having to monkey patch it to "fix" it.

BTW, the link on your previous comment is broken.

**Comment by aristobulo-eezee** [comment]
And don't forget the fact of having a group_**no_one** but actually is **everyone**. Because you just mentioned "consistency" as an argument 😕

**Comment by wtaferner** [comment]
@aristobulo-eezee 
Have you already seen this contribution to OCA?
https://github.com/OCA/server-tools/tree/9.0/base_technical_features

It basically helps to get what it was like in v8 w/o the need for entering debug mode for v9 users who have activated the "technical features"

**Comment by aristobulo-eezee** [comment]
@wtaferner thank you, we basically did the same, although our solution has less lines of code. Maybe I did miss some details.

**Comment by odony** [comment]
> @odony Ok, but you did it on ir.ui.menu for the menu items instead of BaseModel. The root problem is that in fact, your hide many visual elements for group_no_one unless users activate developer mode, but these hidden elements (menus, fields, tabs, etc.) were displayed without activating it on v8 and prior.

Yes, it's a functional/business decision, for usability reasons. You and your customers may or may not like it, just like every single change that happens between major versions of Odoo ;-)
We can discuss the rationale if you're interested, but this is not going away in a stable version. (The main point is that you generally don't want to permanently switch to "technical features" mode, and many people were encouraged to do so with the previous UI.)

> If you look for group_no_one on xml files, you will find almost 300 elements and they are not just technical elements, I'm talking about simple fields containing relevant information for functional users (i.e: date_due on account.invoice ).

The fields that are hidden by default (this was true pre-9.0 too) include technical fields but also complicated or advanced features, any generally any field that could be considered confusing or redundant for newcomers. The main goal is to simplify an overly complicated UI.

> Right now we have to inherit every one of these elements to get them back, because our customers had it on v8 and now they don't see it.
> Having this on ir.ui.view level, like on ir.ui.menu provides a cleaner way to inherit the model and avoid hiding so many UI elements and having to monkey patch it to "fix" it.

You'll be happy to hear that as of Odoo 10 (see [this commit](https://github.com/odoo/odoo/commit/53572ba4c6b678656aa34bc7a2db26481b38dff3)) there will be a generic `base` model that can be inherited to modify `Model` methods.

In the mean time the simplest solution would be to monkey-patch `user_has_group` indeed, like [base_technical_features](https://github.com/OCA/server-tools/tree/9.0/base_technical_features) does.

Note that permanently displaying all "technical/advanced" fields to users might not be a recommended move. You might want to use subtler techniques and display only the few fields that users **really** need.

> BTW, the link on your previous comment is broken.

Fixed, thanks.

> And don't forget the fact of having a group_no_one but actually is everyone. Because you just mentioned "consistency" as an argument :confused:

Well, this group should already have been renamed "technical_features" a long time ago, but that would have broken many existing modules for no good reason. Same thing here.
Consistency is more about treating similar cases in the same fashion (here _menus and views_) as much as possible. Congruity is another thing.

**Comment by aristobulo-eezee** [comment]
Thank you for taking the time to clarifying @odony, although is extremely disappointing how common is the answer we will not touch this "stable" version it's like you all became bots. Well, like many other issues I know this is not going anywhere, but I prefer to leave these little discussions on the record.

Thank you and farewell, remember customers of odoo partners buy support contracts for odoo, ergo, they are also your customers, you should pay attention to that as-well.

Next time I post an issue I will post also the comment "Will not be fixed on stable" that way you can just close the issues faster and save time by upvoting it! 

Regards.

**Comment by odony** [comment]
It's much simpler than that: in stable [we only fix bugs](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean). It's something that all customers rely on, and the people who complain about our policy are often the same ones that complain about "regressions" whenever a change is done to fix another customer issue.
By being very careful with every stable patch we make sure the benefit of the patch is more important than the inherent risk that comes with every change.

In the current case, what would you have preferred?
  - completely revert our usability change and make it behave like 8.0
  - or change the implementation of `user_has_group()` and move the logic elsewhere

I think it is very obvious that either of these changes would have had very invasive consequences on the way users and developers expect version 9.0 to behave, and caused a lot of "stable regression" complains. And this would be done for what benefit? To save **you** the trouble of a monkey-patch? ...

**Comment by aristobulo-eezee** [comment]
Well, if you believe that checking the content of a web request to bypass group access rules on a low-level ORM object it's a good piece of code..

![cheers](https://cloud.githubusercontent.com/assets/8862626/16768756/de688a68-4845-11e6-97d4-86cbae0d7eb5.gif)

I'm glad you have it all figured out.
