### ISSUE TITLE
[14.0][purchase] wrong trasnaltion

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#127545]
Impacted versions:

- [ ] 14.o

Steps to reproduce:
print PO in German language

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 2123, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 329, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 185, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    (object.state in ('draft', 'sent') und 'Angebotsanfrage - %s' % (object.name) oder
                                       ^
SyntaxError: invalid syntax

Expected behavior:
 print without error

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/43987335/a4009d00-386a-4dda-b3fd-cc9ed20e3e29)

Support ticket number submitted via odoo.com/help (optional):
#3414236

**Comment by matteoopenf** [comment]
https://github.com/odoo/odoo/blob/8b4c4a2cbedeb9831810ed0440c19821945e98cd/addons/purchase/i18n/de.po#L50

![image](https://github.com/odoo/odoo/assets/43987335/995c2bac-ad43-486e-b170-c3134dc07a85)


I think there the translation is 'and' because the logic operator must not translate

**Comment by niyasraphy** [comment]
hi @matteoopenf ,
thanks for the bug report, as translations are managed using transifex, feel free to correct it in:  https://app.transifex.com/odoo/odoo-14/translate/#de

w.r.t: https://github.com/odoo/odoo/issues/127277#issuecomment-1620334509

thanks

**Comment by niyasraphy** [comment]
@matteoopenf https://github.com/odoo/odoo/wiki/Translations

**Comment by matteoopenf** [comment]
https://github.com/odoo/odoo/commit/e7cb5105d471ede6a9e8c361596e8558a2c6f7a7 fixed
