### ISSUE TITLE
Shop doesn't show the basic price when the global discount is applied

### ISSUE THREAD

**Issue by Hadron4biz** [odoo/odoo#12760]
Impacted versions:  9.0

Steps to reproduce: Set website pricelist as Public pricelist,  global discount to 10 %, set product price to 1,00 EUR. Go to shop and find product. Next set set product price to 1,01 EUR or higher and again check product  in the shop.
Current behavior:
When basic price is lower than 1,01 EUR, there is no basic price on product card.  It seems to me that this situation exists when pricelist is reduces the price by less than 0,10 EUR. 
For example when we set the 20 % discount, on product card are not displayed basic price when we set the price of product lower than 0,51 EUR. e.g. -> 0,50 EUR 

Expected behavior:
On Website shop should be crossed the basic price and new price after discount.  When discount is set to 10 %. price is higher than 1,00 EUR- for example 1,1 EUR , both prices are displayed. Crossed basic price(color red) and new price after discount. 

The screenshots showed how it's work. 

Video/Screenshot link (optional):

![051eur](https://cloud.githubusercontent.com/assets/14541904/16759815/11321f4a-4819-11e6-9530-94fee92805d1.png)
![050eur](https://cloud.githubusercontent.com/assets/14541904/16759820/1612530e-4819-11e6-88f0-44b63fe03bdd.png)

**Comment by deepakpatkumar** [comment]
Function Indentation solve this problem so give space for final call

**Comment by Hadron4biz** [comment]
Thanks for reply, but still I do not know where is the problem.
I should look for the cause in which file?

**Comment by JKE-be** [comment]
Limit has been updated from 0.1 to 0.01 to display the cross price a long time ago.
