### ISSUE TITLE
purchase draft date fields shows the wrong date 

### ISSUE THREAD

**Issue by exippy** [odoo/odoo#1276]
On odoo v7-saas5:
When I try to set a purchase draft date to 06/10/2009 (june the 10th), odoo displays 05/10/2009 instead.
It only happens on the purchase drafts for this date only and affects the following fields:
      - purchase.order.date_order
      - purchase.order_line.date_planned
      - purchase.order.minimum_planned_date
This bug seems to affect the display on the website only since reading those fields using the erppeek client yields the expected dates for those same fields.

purchase.order.date_order is not affected on odoo v8, but the other fields are

**Comment by Yenthe666** [comment]
Hi @exippy,

Thank you for your report and sorry for the late reply.
Odoo 7 is no longer supported by Odoo (the support goes three versions back). Don't hesitate to resubmit an issue against V8, V9 or V10 if you can still reproduce this.

Regards,
Yenthe
