### ISSUE TITLE
Omniseach key sensitive and not searching by substring

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1277]
Hello:
In some moment during last updates, we have lost an incredibly usefull functionality where we could search anything on omnisearch box looking for substring and not being key sensitive. 

Tested on runbot http://07013-8-0-869b64.runbot.odoo.com/

Go to tasks, Look Res for projects in omnisearch --> looks for nothing
Now look for Research & Development and tasks are correctly shown

Functionality has been lost in several other objects like stock moves, quants, pickings and so on, so I think it's a general issue on omnisearch

Thank you:
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
