### ISSUE TITLE
odoo 16 exporting hidden columns in tree view

### ISSUE THREAD

**Issue by nrome-n** [odoo/odoo#127861]
Impacted versions:
- odoo 16
- tested on runbot

Steps to reproduce:
- hide a column in tree view
- click on the export button next to the New button

Current behavior:
- the export function will export all columns including hidden columns

Expected behavior:
- only export the visible columns in the tree view 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @nrome-n 
The tooltip is mentioning "Export All", so all fields (including hidden ones) are exported.
Best,
