### ISSUE TITLE
Calendar Event Not show If you change language as Persian [9.0]

### ISSUE THREAD

**Issue by Hk005** [odoo/odoo#12780]
Impacted versions:9.0
Steps to reproduce:create event in calendar as English language selected. Than select persian language from preference and goto calendar. you can not see any event there. 

Current behavior:Can not see events in Persian language

Expected behavior: Should see events in persian language

Video/Screenshot link (optional):

**Comment by fshahy** [comment]
@Hk005 I think it is related to MomentJS library, trying to display Persian numbers. I fixed it by replacing them with Latin numbers.

**Comment by Hk005** [comment]
@fshahy thanks for suggesting way to fixed it but actually I have not much idea about MomentJS lib so can you guide me how can i do it OR any other reference/example?

Regards.

**Comment by mart-e** [comment]
@csnauwaert could you take a look please?
`moment(date_start).format('YYYY-MM-DD HH:mm:ss')` gives something like `۲۰۱۶-۰۷-۲۱ ۰۰:۰۰:۰۰` which can not be parsed by fullcalendar.

**Comment by Yenthe666** [comment]
Hey all,

This issue has been fixed and seems to work fine in the meanwhile. An example of a calendar item I made in English and I then switched to Persian:
![image](https://user-images.githubusercontent.com/6352350/38663837-468c8e34-3e38-11e8-9417-1ea6012e6208.png)


Regards,
Yenthe
