### ISSUE TITLE
[saas-12]  check resupply warehouse raise  " 'set' object does not support indexing "

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#12781]
Impacted versions:
saas-12

Steps to reproduce:

check option `Manage several Warehouses, each one composed by several stock locations` 

create new warehouse

and option `resupply warehouse`  check `your company` , and then save, it should raise error.

Current behavior:

report error '

```
  File "/opt/odoo/odoo/addons/mrp/models/stock_warehouse.py", line 112, in write
    return super(StockWarehouse, self).write(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/stock/models/stock_warehouse.py", line 158, in write
    to_add = new_resupply_whs - old_resupply_whs[warehouse.id]
TypeError: 'set' object does not support indexing
```

Expected behavior:

no error raised.

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
This was solved by rev 36359f8d3e0b7cca7ec2c94e58372131e521af43

Thanks for the report
