### ISSUE TITLE
[saas-12] generate invoice in subscription raise error  'account.tax' object has no attribute 'filter'

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#12798]
Impacted versions:

[saas-12]

Steps to reproduce:

create a subscription.

create a new sale order, and assign to the created subscription.

click `generate invoice `

Current behavior:

it raise Attribution Error, said.  'account.tax' object has no attribute 'filter'

Expected behavior:

generate the invoice.

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/1404460/16844043/2bc1813a-4a16-11e6-8a50-5aadc7e393b3.png)

**Comment by mart-e** [comment]
I belive this is already fixed as this code is no longer present (now using `filtered` instead of `filter`).

By the way, I don' t advise to use saas-12 except for test purpose as we don't support these versions (used only a limited time).
