### ISSUE TITLE
Forum Spam Attacks: Do not allow new users to post new questions as long as (a) question(s) are awaiting validation by a moderator.

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12803]
Impacted versions:
9.0CE, Odoo.com
Steps to reproduce:
I can't reproduce it as I'm not a spammer :-) but check user name "arman" who tried to spam www.odoo.com/forum a couple of minutes before.
Current behavior:
Obviously a new user is allowed to post as many questions as he likes and all posts are then waiting for validation. This makes fighting a spam attack very cumbersome
Expected behavior:
A new user should not be allowed to post further questions as long as there are non-validated questions of the same user in the queue waiting for validation.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @treviser,

I like the idea. It might be a bit annoying for a new person who wants to ask two questions at once but this doesn't happen a lot and I'm sure we have a lot more spammers that keep trying.
@mart-e can we label this wishlist? :smile:

**Comment by treviser** [comment]
In Odoo's forum itself the reaction time for moderation is quite fast. Also this behaviour can be observed in other forums too.
However the moderation of spam attacks is not really moderator-friendly. 
1. The moderator has to close the question.
2. He has to downvote the closed question in order to stop the spammer from posting new questions.
3. He has to delete the question.
I remember times when south-korean spammers were attacking the Odoo forum and there was no immediate reaction by a moderator and the queue had about 30 post waiting for validation.

**Comment by Yenthe666** [comment]
@treviser I remember a time where I had to manage queue lists with over 120 posts waiting.. god that was a pain in the ...
I've labelled wishlist for now, I'm sure somebody from Odoo will give an official response on this.

**Comment by mart-e** [comment]
Looks like a good idea, I will submit it for R&D team

**Comment by JKE-be** [comment]
A task has been create in R&D (27554)
Draft: https://github.com/odoo-dev/odoo/commit/fd559412fdfc9bf4903a5cc6095b22536d628d4e

**Comment by Yenthe666** [comment]
@jke-be please rewrite those sentences, some don't make a lot of sense. If you want to I can make suggestions :)

**Comment by mart-e** [comment]
@Yenthe666 this was just a draft to give an idea but it will be more formally in another branch (still at the spec stage so no branch to give you yet, watch [R&D PR](https://github.com/odoo/odoo/labels/RD))

**Comment by Yenthe666** [comment]
No worries, I've made suggestions on the draft, it was just a tip. We'll see where this ends. :+1:

**Comment by Yenthe666** [comment]
Ugh I could've used this feature so hard now @treviser.. The newest spam flooding:
![image](https://cloud.githubusercontent.com/assets/6352350/17284736/b942bf24-57bd-11e6-8a06-955747b527fe.png)
@mart-e and @odony can one of you guys clean this up from the database perhaps?

**Comment by treviser** [comment]
And counting! I'm not doing that manually...

![selection_235](https://cloud.githubusercontent.com/assets/1814941/17284957/ab9a53ee-57bf-11e6-84b9-a140789d0be5.png)

**Comment by Yenthe666** [comment]
Neither am I, I downvoted some of those users but they keep coming so.. this is why we need good anti spam features :+1:

**Comment by treviser** [comment]
We should make that an urgent need instead of wishlist only.

**Comment by treviser** [comment]
I believe they pay hundreds of slaves to spam any forum out there in the whole internet world. Unbelievable! (do a Google search for this website).

**Comment by treviser** [comment]
We should definitely not allow more than 1 post waiting for validation (not 3 not any other number, just one!). It should also be possible to flag closed posts (gives -100 karma at once), so that in the aftermath of an attack it is maybe possible to act against IP addresses.

**Comment by Yenthe666** [comment]
@mart-e @JKE-be and @odony I'd like to get more things going for this. Sometimes the spam amounts get so high it isn't easy to handle anymore. Think we could tackle down some more problems?

**Comment by JKE-be** [comment]
It has been cleaned.

**Comment by odony** [comment]
Limiting the queue at 1 post per user is probably a good idea but don't get your hopes too high, that won't stop spammers. They can just create more accounts, and CAPTCHAs won't stop them there either.
The best thing to stop them is what we have now: first posts are not published until they are reviewed. This really removes the incentive for them spending energy or money on our forums.

Then it's our job to improve the tools to make life easier for moderators (mass deletion, etc,), while still ensuring a decent quality of moderation and avoiding mistakes.

Have you used StackOverflow lately? Their moderation system has gotten pretty complex, with fake posts just designed to test moderators' attention, etc. It shows how difficult the this is to get right, especially when communities grow.

**Comment by treviser** [comment]
@odony IMHO it's not about completely stopping spammers by 1 measure only, it's about several measures with 2 goals: 
- making life for spammers harder (and opening new accounts makes it definitely harder, especially if a new validated email address is necessary to post a question) AND
- making life easier for moderators. 
Restricting unvalidated posts to 1 does not harm legit users and is easy and fast to realize, so it's a good first step in my opinion. It would enhance the situation remarkably as I do see only one kind of spam so far since more than a year, it's always the same as this morning.

**Comment by treviser** [comment]
Another measure could be that it is possible for moderators to mark certain URLs (such as S­T­3­３­9­.­C­O­M) and then all messages containing this URL will be automatically deleted and new messages containing such URLs are blocked by default.

**Comment by Yenthe666** [comment]
@treviser I don't agree with you on that one. Sometimes genuine people create a topic with an URL in the topic title and one or more URL's in the content, those would be automatically deleted. That is not very user friendly. A better alternative is to automatically add them in the flagged section so it pops up for administrators right away.

@odony I do agree with you that fighting spammers is very complex and a never ending battle but the Odoo forum makes it a bit too easy at this point. One new question at a time would be a great improvement, it'll require them to try a lot harder in order to get new questions created.

**Comment by treviser** [comment]
@Yenthe666 I do not agree with you on this one, as long as a post contains an illegit URL, the complete post is illegit, no matter what and how many other URLs are in the same post. And I'm talking about illegit URLs identified and manually marked by a human moderator (such as the URL spread this morning).

**Comment by treviser** [comment]
Example: Take the situation this morning: There is no doubt and it is clear for any human moderator, that the URL S­T­3­３­9­.­C­O­M is illegit. I as a moderator would then mark this URL as illegit. All 584 posts containing this URL are now automatically deleted at once. If the spammer uses a new account and tries to post new messages containing the same URL, the messages are blocked/deleted. 
How would a genuine poster post a question containing this particular URL pointing to a online gaming site? It can not be legit and therefore also the poster can not be genuine.

And I believe that they start to be more clever, they copy/paste text from genuine posts of other users so they do look like genuine questions and then place the illegit URL in it. A couple a days ago I did delete such a post after investigating and wondering alot.

**Comment by Yenthe666** [comment]
@treviser well let us imagine that I'm the person that wants to advertise. If I see that my topics are automatically deleted / closed / ... because of the URL I would create a script that randomly changes the URL for every new topic. For example:
<ul>
  <li>S­T­3­３­9­.­C­O­M</li>
  <li>S­T­3_３­9­.­C­O­M</li>
  <li>S­T­3­３_­9­.­C­O­M</li>
  <li>S­T­3­_３_­9­.­C­O­M</li>
</ul>

That would perfectly bypass your idea anyways.

**Comment by treviser** [comment]
Yes, of course, but it is again something that makes it definitely much harder for spammers and easier for moderators (it is not supposed to solve the spamming problem competely by its own). Just another valuable piece of the puzzle in my opinion. As a human moderator I can easily identify such scripted URL changes and mark any of them. Together with the other also relatively simple measures already discussed in this thread, it makes perfectly sense to me.

**Comment by JKE-be** [comment]
We will test with these 2 new rules to start...
1. Now, close the first post of a user for spam, remove 10x karma, so down vote become useless ...
2. And only one post in pending simultaneously...

@treviser @Yenthe666 : Thanks for you suggestions ;)

**Comment by Yenthe666** [comment]
Alright, let us see how that affects spammers and the usability. Thank you @JKE-be.

**Comment by treviser** [comment]
Thank you. Can somebody please inform our beloved spammer to try it again so we can see if he gets pissed off ;-)

**Comment by JKE-be** [comment]
![image](https://cloud.githubusercontent.com/assets/4848797/17294067/9e12a066-57f4-11e6-8f5a-d432f6ad6831.png)

**Comment by treviser** [comment]
@Yenthe666 @JKE-be Again:

![selection_236](https://cloud.githubusercontent.com/assets/1814941/17317940/d20c0914-5882-11e6-95ef-3cf190afc392.png)

**Comment by Yenthe666** [comment]
Yup and counting.. can any of you guys clean that up again? :frowning:

**Comment by treviser** [comment]
Not counting, I stopped the guy who so in love with his wife :-)

**Comment by JKE-be** [comment]
Hello, it is done.
The patch from yesterday is not already on the production server.

**Comment by treviser** [comment]
@Yenthe666 @JKE-be 103 spam messages again. Obviously they put more effort now in their spam strategies. Can anybody delete the messages?

**Comment by JKE-be** [comment]
@treviser Thanks for the feedback...
It has been cleaned...

**Comment by treviser** [comment]
These stupid spammers are really annoying and still give not up...and it is always the same spam and in my opinion it is easy to identify them and automatically delete the spam messages.
My new suggestion: 
The mandatory language in the Odoo help forum is english, therefore all messages which are composed in japanese, chinese, arabic, korean whatsoever character sets are automatically not legit. 

Obviously these spammers do not change their behaviour and they always use the same character set and the same way of composing their posts. If they do not know that their messages are automatically deleted because of the character sets used, this could work for a long time.

**Comment by JKE-be** [comment]
Hello,

> The mandatory language in the Odoo help forum is english
Yes, it is True... but it's is not because the guy post the question in english and sign in Chinese, that it is spam :/

But actually I have blacklisted automatically the messages which contains one substring from their posts.

Thanks for your prompt report ;)
