### ISSUE TITLE
wkhtmltopdf header overlapping with page content

### ISSUE THREAD

**Issue by dummyltpl** [odoo/odoo#12805]
Hi,

We are facing issues while generating invoice report in odoo 9.0. Header content overlapping with page content.

**Comment by sle-odoo** [comment]
Hi,
Wkhtmltopdf cannot compute the height of your header to adapt the paper format. You have to do it manually by enabling the debug mode and tweaking the paper format in the company form.

Regards

**Comment by bodedra** [comment]
Yes. I am agree with @sle-odoo 

You need to tweaking the paper format. Specially with following two.

* Top Margin and
* Header spacing
