### ISSUE TITLE
"Apps" menu is visible to all user groups.

### ISSUE THREAD

**Issue by huyleict** [odoo/odoo#128042]
Impacted versions: 16.0

Steps to reproduce: 
`<menuitem id="menu_management" name="Apps" sequence="500" web_icon="base,static/description/modules.png" groups="base.group_system"/>`

I noticed that even though in the xml file, at the menuitem "Apps" in Odoo 16 there is a tag groups="base.group_system" 

I did a quick investigation, I noticed that even though in the xml file, at the menuitem "Apps" in Odoo 16 there is a tag groups="base.group_system"  but when Odoo 16 initializes it seems to have ignored this tag.
Odoo 15 has an xml file with the same content but is not affected. 
(Screenshot below)

Current behavior: "Apps" menu is visible to all user groups.

Expected behavior:  "Apps" menu is only visible to "base.group_system" group.

Video/Screenshot link (optional):
![Screenshot 2023-07-11 135339-15](https://github.com/odoo/odoo/assets/9417624/21b8aef0-b104-4ea8-9239-ca6236ef8cf5)
![Screenshot 2023-07-11 135310](https://github.com/odoo/odoo/assets/9417624/8850919d-aa81-4b3c-9032-3680b3eb917d)

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @huyleict ,
this is a new feature introduced in 16, module named: base_install_request , where users can make request admin to install the module they needed.

Thanks

**Comment by huyleict** [comment]
hi @niyasraphy ,
thanks for your information. Can I delete it?

**Comment by niyasraphy** [comment]
hi,
yes if you don't need this functionality, you can uninstall the base_install_request module.
feel free to close the ticket, as this is not a bug.
thanks
