### ISSUE TITLE
Issue sale order cancel

### ISSUE THREAD

**Issue by shahidtechultra** [odoo/odoo#128088]
Impacted versions: 16.0

Steps to reproduce: 

1. Active Finnish / Suomi language
2. Set Finnish / Suomi language in the customer.
3. Create a sale order with Finnish / Suomi language customer, products and confirm.
4. After confirming cancel the sale order.
5. User gets the error.

Current behavior: Getting errors.

Expected behavior: open mail template pop-up

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Solution: 

1. Go to the Mail template
2. open Sales: Order Cancellation mail template
3. open multi-language pop-up of Subject
4. change in Finnish / Suomi language {{ object.company_id.name }} {{ object.type_name }} Peruutettu (viite {{ object.name or 'n/a' }}) field

![imgpsh_fullsize_anim](https://github.com/odoo/odoo/assets/125870943/529b7aaf-b41c-4984-ba08-c0d9d533c756)

![Screenshot from 2023-07-11 16-54-37](https://github.com/odoo/odoo/assets/125870943/a31dd5b2-340b-4750-89d2-b72a776a60bc)

**Comment by niyasraphy** [comment]
hi @shahidtechultra ,
translations are managed through transifex, feel free to login the transifex and correct the wrongly translated values:  https://explore.transifex.com/odoo/odoo-16/

thanks
