### ISSUE TITLE
Shop tab of Ecommerce Error 403 when adding products to the ecommerce

### ISSUE THREAD

**Issue by Xpiva** [odoo/odoo#1280]
whether you add an item from the ecommerce page or the back end and publish it then log out, you get error 403: Forbidden 
The page you were looking for could not be authorized.

Maybe you were looking for one of these popular pages ?
•Homepage
•Contact Us

If you log in, the item views properly, then you log out once again you get error 403: Forbidden 

If you un-publish the item then the shop section of the site displays correctly even when logged out, however will not allow you to publish any items including the default service item to the shop section of the site.

**Comment by lapagept** [comment]
I have this error now. I have pulled Odoo branch 8 from github. Still the same error.

**Comment by lukebranch** [comment]
@lapagept ,

Did you make any changes to the default public user? I found that if I changed access rights, or switched this to another user I created I would have this error.

**Comment by lukebranch** [comment]
@lapagept ,

Have you made any changes to the public user? I ran into the same issue due to changing the public user settings, or switching to another user.

**Comment by ddfs** [comment]
google indexer reporting that  product pages have 403 permission error. 

turns out that these are unpublished products and included in sitemap.  
not sure how relevant to this ticket. i think it all could be solved here.

**Comment by Yenthe666** [comment]
Hi @Xpiva,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
