### ISSUE TITLE
[8.0] Translations are not reflected from mail.group.name to its generated ir.ui.menu

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#12807]
Impacted versions:
8.0

Steps to reproduce:
* Install social media module (mail)
* Install french translations
* Set french langugage just installed as current language
* GO into "Messagerie" top menu

Current behavior:
the generated menu are not translated

![selection_042](https://cloud.githubusercontent.com/assets/7601731/16871136/754e4e0e-4a85-11e6-8a6d-34076de80c42.png)

Expected behavior:

Menu should have the same translation as the source translated responsible of their generation

**Comment by JonathanNEMRY** [comment]
OPW 683409

**Comment by beledouxdenis** [comment]
Dear Jonathan,

This issue has already been reported in the past.

Unfortunately, it cannot be solved in Odoo 8.0, for technical reasons and given the fact this is a stable branch.

However, this issue no longer happens in Odoo 9.0.

In addition, we do not consider this issue as critical: It doesn't prevent a user to perform his daily tasks.

I hope you will understand.
