### ISSUE TITLE
Reseller Partner Level: Make Field Partner Level Translatable

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12819]
Impacted versions: 9.0 CE

Steps to reproduce:
Define a partner-level under Sales/Configuration/Contacts/Localization
Current behavior:
The field Partner-Level is not translatable
Expected behavior:
The field must be translatable by default.
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Done in master at 33fe066cbb9ba71c410f6df22739577649ecadba
Thanks for the suggestion
