### ISSUE TITLE
Bug when reloading the page on the Odoo Inbox Online

### ISSUE THREAD

**Issue by aek** [odoo/odoo#12817]
Impacted versions: Online

Steps to reproduce: login into odoo online, not any specific database. Just go to your inbox by clicking on the @ button like in the image
![inbox1](https://cloud.githubusercontent.com/assets/404966/16898566/f954e4c0-4b92-11e6-86a3-6a0bef9edc3e.png)

The url should be something like this one
https://www.odoo.com/web#menu_id=5200
Just reload the page

Current behavior: You will see an error related to the context like:
![screenshot from 2016-07-16 20 15 17](https://cloud.githubusercontent.com/assets/404966/16898570/24fb6144-4b93-11e6-8699-fd8cab706a0c.png)

Expected behavior:
![screenshot from 2016-07-16 20 23 54](https://cloud.githubusercontent.com/assets/404966/16898576/4d0304ee-4b93-11e6-9cef-cadd9394dc82.png)

**Comment by joolsr** [comment]
If you're using odoo's online offering it would be better to a raise a bug directly with them via their support channels.

**Comment by aek** [comment]
Hi @joolsr 
I'm not using odoo online for anything, I'm just reporting a bug that could be happening everywhere.

**Comment by mart-e** [comment]
Hello,

As said joolsr, our odoo.com server is quite particular. We are not using the stable 9.0 version but a latest saas version and some customization as well. Since last week, we upgrade to saas-11 version so it may be a recent bug. It seems fixed as I don't have it now.

If you can reproduce in main 9.0 version, I will reopen this issue but otherwise, I advise you to contact the support at https://www.odoo.com/help for requests not linked to standard version.

Regards

**Comment by aek** [comment]
So? I think that it's not a valid reason to close an active and reproducible bug. All is related to Odoo and this is where Odoo issues are reported by community. The support or help channel should be used by customers of Odoo. I just take my time to write a detailed issue here just to see how it's closed with a deliberated clic. That's my point of view, but no problem, it's up to you. 
Issues shouldn't get closed by Odoo personals without first get confirmed that's it's solved in any way. This is the second continue issue that I see it closed without being resolved

**Comment by mart-e** [comment]
Github issues are to report bugs on supported versions (7, 8 & 9). Here you have a problem that is linked to Odoo Online, not the standard Odoo. saas-x versions are not supported as used internally. I tired also on a [runbot saas-11](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7?search=saas-11) but didn't get any issue either so it looks like an issue only on odoo.com, this is why it is not the proper place to report it.
