### ISSUE TITLE
[sale_stock] Quantities in "Picking Information" warning not showing enough decimal places

### ISSUE THREAD

**Issue by Nick-OpusVL** [odoo/odoo#12827]
We have a customer whose base unit for selling stuff is in thousands. However stock can be as low as 0.001 thousands, but that last decimal place isn't displayed in the Picking Information warning.

Impacted versions:

* 8.0

## Steps to reproduce:

* New database
* Edit admin user: Enable Technical Features 
* Install 'stock' and 'sale'
* UK accounting chart with defaults (though probably doesn't matter)
* Settings -> Configuration -> Warehouse, tick:
  * Use packages: pallets, boxes, ...
  * Manage different units of measure for products
  * Allow to define several packaging methods on products
* Create a unit of measure with:
  * Name: Thousand(s)
  * Product Category: Unit
  * Type: Bigger than the reference Unit of Measure
  * Bigger Ratio: 1000
  * Rounding Precision: 0.00100

* Create product:
  * Name: Widget
  * Product Type: Stockable Product
  * Unit of Measure: Thousand(s)

  * Inventory tab:
    * Packaging / Configurations: Add new item:
      * Quantity by Package: 1
      * Package Logistic unit: Create and Edit... :
        * Name: Pack of 1000
        * Type: Pack
        * Height: 10
        * Width: 10
        * Length: 10
        * Empty package weight: 0.5
  * Save

* Edit product
  * Inventory Tab:
    * Quantity On Hand -> Update
    * 10
    * Apply

* Sales -> Quotations -> Create:
  * Customer: Create and Edit
    * Is a company: ticked
    * Name: Acme
  * Order Lines: Add an item
    * Product: Widget
    * Quantity: 0.5 Thousand(s)
    * Packaging: Pack of 1000

## Current behavior:

Warning message strips out decimal places and appears to use wrong UoM name:

```
Picking Information ! : You selected a quantity of 0 Units.
But it's not compatible with the selected packaging.
Here is a proposition of quantities according to the packaging:
EAN: (n/a) Quantity: 1.0 Type of ul: Pack of 1000
```

## Expected behavior

Use the chosen UoM name, and the number of decimal places specified in that
UoM's "Rounding Precision" field (which as 0.00100, so should have three d.p.)

```
Picking Information ! : You selected a quantity of 0.500 Thousand(s).
But it's not compatible with the selected packaging.
Here is a proposition of quantities according to the packaging:
EAN: (n/a) Quantity: 1.000 Type of ul: Pack of 1000
```

**Comment by nim-odoo** [comment]
Hello,

I agree with the right UoM name/quantity. However, the number of decimals places seems too much. That would imply some unnecessary processing for a simple warning message. In other places, the number of decimals is simply hardcoded, e.g. https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock.py#L356
