### ISSUE TITLE
Cant Backup or install newmodules

### ISSUE THREAD

**Issue by SeanHardyOdoo** [odoo/odoo#12821]
Impacted versions: 9 enterprise

Steps to reproduce: Try to Backup Database

Current behavior: Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpYxuUEV/dump.sql', u'2016_production') error 1

Expected behavior: Want to be able to use

Video/Screenshot link (optional):
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpYxuUEV/dump.sql', u'2016_production') error 1

**Comment by dreispt** [comment]
Probably there's something wrong with your install.
Try running that `pg_dump` command on a terminal to see the actual error message.

**Comment by mart-e** [comment]
This is an issue in the configuration of your postgresql server, not on the side of odoo.
As said Daniel, check the command manually but you should probably give more rights to your postgres user.

**Comment by SeanHardyOdoo** [comment]
I used Docker and Digital Ocean to Host these

 

Is there anyone who will do this for a fee?  I will pay for the support

**Comment by dreispt** [comment]
> Is there anyone who will do this for a fee? I will pay for the support

Certainly there is.
You can ask for help on the community mailing list.
Please people remember answer you privately.

**Comment by SeanHardyOdoo** [comment]
How do I ask this?

**Comment by dreispt** [comment]
You can join the Mailing list at: https://www.odoo.com/page/odoo-community
Or find an Odoo Partner near you: https://www.odoo.com/partners

**Comment by aek** [comment]
This is definitely an issue in Odoo 9, I face it today and check it against Odoo 8 and it's ok in that version. @SeanHardyOdoo I could provide you support on this
