### ISSUE TITLE
hstore field type and write_audit field

### ISSUE THREAD

**Issue by george-mengelberg** [odoo/odoo#12820]
Impacted versions: future

Steps to reproduce: NA

Current behavior: Odoo does not maintain revisions of a record.

Expected behavior:  NA

Video/Screenshot link (optional):

Request Odoo incorporate a *hstore* field type and include a *write_audit* attribute (based on *hstore*) if *_log_access=True* so that the full lifecycle of a record can be reviewed and/or audited.

**Comment by mart-e** [comment]
Hello,

Thanks for your suggestion. We used to have such feature with the auditrail module but we have removed it as it was not our focus (and it wasn't working very well).
Maybe we will reintroduce in the future but nothing is planned at the moment.
