### ISSUE TITLE
sale order line method is referencing vaues from product module w/o reference to it

### ISSUE THREAD

**Issue by jerzyk** [odoo/odoo#128211]
Impacted versions:
R14-R16

Steps to reproduce:
method _update_line_quantity of addons/sale/models/sale.py line 1341: 
```
                if line.product_id.type in ('consu', 'product'):
```

product_id.type has only 'consu'  and 'service'

'product' is added in product module, but this module is not in sale module dependency

**Comment by xavierbol** [comment]
Hello @jerzyk ,

`sale` module implicitly has `product` module thanks to `payment` module in 14-15, because `payment` has `account` in their dependencies and `account` has `product` in their dependencies. From 16, the dependencies of `sale` module have changed but `product` is still in the dependencies, so there is no issue. 🙂 

I think we can close that issue since there is no bug. 🙂 

Have a nice day!

**Comment by jerzyk** [comment]
you're right! my bad - I've missed this

**Comment by xavierbol** [comment]
No problem. 🙂

**Comment by jerzyk** [comment]
@xavierbol 
just have a look again:

product definition is:

```
    type = fields.Selection([
        ('consu', 'Consumable'),
        ('service', 'Service')],...
```

and this is done in stock

```
    type = fields.Selection(selection_add=[
        ('product', 'Storable Product')
    ], tracking=True, ondelete={'product': 'set default'})
```

so it looks like this problem is valid but my description sucks :)

**Comment by niyasraphy** [comment]
@jerzyk ,
i think its still fine, it may written by considering the flow to keep working once the product type(stock is installed)

**Comment by jerzyk** [comment]
it is "semi" fine - because you do not assigning this value to a field, but at this moment sale module does not know about type 'product'

**Comment by vava-odoo** [comment]
Hi @jerzyk
Thanks for reporting.
You're right, there is an inconsistency. However, as mentioned by @niyasraphy, this won't lead to any bug as is. 
For this reason, we won't change it in stable versions, but we'll consider it for master.
If you feel like it, don't hesitate to suggest a fix targeting master (if it is your first contribution, please follow [the steps here](https://www.odoo.com/documentation/master/contributing/development.html#make-your-first-contribution))
Cheers,
