### ISSUE TITLE
Rating module names don't conform to conventions

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#12837]
Impacted versions: 
master

Steps to reproduce: 
n/a

Current behavior:
We have the new modules "rating_project" and "rating_project_issue".

Expected behavior:
Project related modules are expected to begin with `project_`.
To conform to conventions whey should be renamed to `project_rating` and `project_rating_issue`.
I can make a PR if R&D agrees on the change.

Video/Screenshot link (optional):

**Comment by antonylesuisse** [comment]
Rating is a generic framework to rate any object and is not tied to project. You could have rating_mrp rating_lunch etc... It follow the same naming convetion as website_* or portal_*.

**Comment by dreispt** [comment]
Oh, I see now that we do have a `rating` module.
Thanks for explaining.
