### ISSUE TITLE
Messages should show up in history of contact / partner

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1283]
When I view a a contact, it does not show all messages related to that contact. For many reasons, contact should display all message activity to/from that contact.

**_Impacted versions:**_
- Version 7.0-20140709-231246

**_Steps to reproduce:**_
1. Use messaging to send message to contact (create contact during message process), or respond to an email received through messaging (and create contract in the process of sending the message)
2. Check that new contact's record

**_Current behavior:**_
- No messaging history is displayed in the contact record, and no function to look at message history from the contact record.

**_Expected behavior:**_
- Either show messages in the activity log, or have a messaging screen that shows messages to/from the contact.

**Comment by Yenthe666** [comment]
Hi @rolandwells,

Thank you for your report and sorry for the late reply.
Odoo 7 is no longer supported by Odoo, as they only support three versions back (at the moment of writing V8, V9 and V10).
I've tried this on a V7 though and had no problems to see everything that I posted in the history chatter. If you still face this issue please update your source code to the latest version and try again.
if you can reproduce this in 8.0, 9.0 or 10.0 you can create a new bug report and we'll look into it again.

Regards,
Yenthe
