### ISSUE TITLE
[16.0][BUG] Error when calculating reserves when split production if conversion from grams to kilograms is made in BOM

### ISSUE THREAD

**Issue by Segui-S73** [odoo/odoo#128499]
Impacted versions: 16

Steps to reproduce:
  1. Create a product in kg as consumable.
  2. Add it into the BOM of another as grams.
  3. Create production with the bill of materials with more than 1 quantity to be produced.
  4. Confirm and check availability.
  5. Set the quantity to be produced from the first backorder to 1, validate and create backorder.

Current behavior:
Now when trying to create the backorder the following error is thrown:
`It is not possible to reserve more products of test kg than you have in stock.`
The error began to appear after adding this commit and if the modifications are removed, the error does not appear.
https://github.com/odoo/odoo/commit/c39256ba6df257ee79fb66eab61617f5fec166b9

Expected behavior:
Being able to continue creating backorders with bills of materials that convert from grams to kilograms.

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/26328725/e9b3f191-a784-49d7-9a80-7d770fd71b6b)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @Segui-S73 
Thanks for reporting.
Maybe @HANNICHE-Walid could help here.
Cheers,

**Comment by HANNICHE-Walid** [comment]
@Segui-S73 Sorry about that didn't correctly account for the units of measures
it's fixed now
