### ISSUE TITLE
Cannot find and modify default configuration file 

### ISSUE THREAD

**Issue by KaydenHo1006** [odoo/odoo#128578]
Impacted versions: 13.0

Hi everyone,

My problem is that I tried to find and modify the default configuration file of Odoo. I found some files that they are seemly the configuration of Odoo. There are /debian/odoo.conf, /etc/odoo-server.conf, and some code in postinstall.sh

When I try to modify db_host, db_name,.... them and run Odoo again then, there is no change occurs and it run  as user 'root'. I don't know the reason.

It returns like this:
<img width="636" alt="error" src="https://github.com/odoo/odoo/assets/137304828/d1097f02-5fa5-4999-bbd0-f699c426e640">

And when I run Odoo with my customized file.conf. It can connect to my PostgreSQL db but it raises an Error that "Couldn't load module web' like this:
<img width="630" alt="image" src="https://github.com/odoo/odoo/assets/137304828/c1bcdf75-f054-436a-b11b-80b3dd340a5b">

Someone please help me to solve my problem! Thank you very much :))

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @KaydenHo1006 ,
for such configuration issue please use help forums, the github issue tracker is track the issues inside the odoo core.
odoo official forum: https://www.odoo.com/forum/help-1

thanks
