### ISSUE TITLE
Writing code quickly in base.automation causes code field to delete

### ISSUE THREAD

**Issue by pexheat-support** [odoo/odoo#128661]
Impacted versions:
16.X
Steps to reproduce: 
1. Go to the automated actions page
2. Select 'Execute Python Code' on the 'Action To Do' field.
3. Start typing gibberish quickly in the code 'field'
Current behavior:
It highlights the entire text prompt randomly and you will overwrite anything you have typed thus far
Expected behavior:
Be able to write code without deleting all previous lines
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

https://github.com/odoo/odoo/assets/91975580/8811fdbf

https://github.com/odoo/odoo/assets/91975580/519dcbcd-a85a-44da-9790-71eabe4b6f0d

-8c13-40fc-b73a-6415b5e4149c

**Comment by vava-odoo** [comment]
Hi @pexheat-support 
This seems to be fixed already, as I can't reproduce on the runbot. Please re-open if it is not the case.
Cheers,
