### ISSUE TITLE
odoo 16 : Error when you click bank from invoicing dashboard

### ISSUE THREAD

**Issue by bigmachini** [odoo/odoo#128648]
Impacted versions: 16

Steps to reproduce: Invoicing --> Dashboad --> Click on bank account

Current behavior: Throws the below error
[odoo_error.txt](https://github.com/odoo/odoo/files/12060826/odoo_error.txt)

Expected behavior: Open journal entries

Video/Screenshot link (optional):
[Screencast from 15-07-23 10:16:43.webm](https://github.com/odoo/odoo/assets/5182869/0717f2b1-7d36-4dc6-9a1e-12ffd1920070)

This seems to have been introduced by this change: https://github.com/odoo/odoo/commit/4e612d5434d8254c3ba44b8a00d7d71bc0ab4084

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Thanks @bigmachini for the report,
And thanks @niyasraphy for the fix!
