### ISSUE TITLE
odoo nginx filter

### ISSUE THREAD

**Issue by medosobh** [odoo/odoo#128651]
Impacted versions: odoo ce 15

Steps to reproduce:
how to configure nginx-odoo to make domain see all db while each subdomain call its db?

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @medosobh ,
this is to track the issue in the odoo core, for such support/questions, please use official forum.
official forum: https://www.odoo.com/forum/help-1

feel free to close this
thanks

**Comment by medosobh** [comment]
ok thanks
