### ISSUE TITLE
[9] Employee [Address Field] Creates New Contact Record as Customer 

### ISSUE THREAD

**Issue by NovaStarGX** [odoo/odoo#12869]
Impacted versions:
Odoo 9.0 , Ubuntu 16.04

Steps to reproduce:
- Employee --> Create
- Fill out standard information, Must include "**Personal Address**"
- Save

Current behavior:
Once Employee record is saved, go to **Contact** tab
You will notice a new contact card created with the "**Employee's Home Address**" information only
No other association is present.
In the Contact Card the following is always present;
On the "**Sales & Purchases**" tab - "_**Is a Customer**_" is always checked
If the contact card is deleted, then the address field in the Employees personal information is also deleted

Expected behavior:

Video/Screenshot link (optional):
![capture3](https://cloud.githubusercontent.com/assets/20577378/17021182/ca8cf080-4f78-11e6-84f4-0121763f0842.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20577378/17021183/cafb92c4-4f78-11e6-8d4e-94d1025f9671.PNG)
![capture1](https://cloud.githubusercontent.com/assets/20577378/17021194/e3b2eea2-4f78-11e6-8af6-5096c99f438d.PNG)

**Comment by pedrobaeza** [comment]
@tde-banana-odoo I think we can add an `ondelete='restrict'` on field `address_home_id` for hr.employee, isn't it?

**Comment by Yenthe666** [comment]
Hi @NovaStarGX,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
