### ISSUE TITLE
Adding a user but user has no permissions

### ISSUE THREAD

**Issue by Tlah1** [odoo/odoo#12873]
Impacted versions:8

Steps to reproduce:

Current behavior:  We added a user, gave permissions, yet when user logs in no permissions and cannot link any other user to tasks or issues

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Could you please give in detail the permissions you gave to the user.
Which app are installed, what do you see exactly? Which error?

**Comment by Tlah1** [comment]
Odoo Warning
	
Access Denied

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: Partner, Operation: create)

Ok

**Comment by Tlah1** [comment]
the user was given all permissions we have 10 applications installed, project,accounting, hr,

**Comment by mart-e** [comment]
Sorry but this is still not enough.
Your error shows that you are trying to create a partner but you are telling me that you have this when the use logs in.
Do you have a traceback server side?
Can you reproduce it on a [runbot](http://runbot.odoo.com/runbot)? I need a way to reproduce it on a new instance with only standard modules.

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
