### ISSUE TITLE
Wrong error message on view updating.

### ISSUE THREAD

**Issue by dsmerghetto** [odoo/odoo#12879]
Impacted versions: 9 enterprise (not tested in 9 community)

Steps to reproduce: 
Create a field in .py file and then create an inherited view (in my case on object mrp.bom) and add the new field. 
Be careful that the priority of this view has to be grater than inherited view priority.

Current behavior:
Error message given to me is that "myNewFieldName" is not present.
In my database mrp.bom table the field was correctly inserted.
Expected behavior:
A message that tell that may be a view sequence or priority error.
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi,
The message is clear, when we are parsing the view, the field 'myNewFieldName' is not present in the current state of the view.
