### ISSUE TITLE
Pricelist report rounding issue - V8.

### ISSUE THREAD

**Issue by purnendu03** [odoo/odoo#12875]
Hello Team,

Impacted versions: v8

Steps to reproduce: 
* Set product cost price to 16.50
* Update the **Default Purchase Pricelist** and set value on **Default Purchase Pricelist Line** as below.
      Price Computation should be as below:
      Based on: Cost Price
      New Price = Base Price * ( 1 + 0.25) + 0.00

Current behavior:
* Now try to create a Purchase order for this product and check the Unit Price calculated is 20.63
     
![purchase_order_line](https://cloud.githubusercontent.com/assets/7599739/17047986/117869fc-5000-11e6-94bf-26a47b6c5e80.png)

* Now Open the product and print Price List, Select  Default Purchase Pricelist, Set Quantity-1 field with 1 and clear all other quantity fields and print the report the value calculated is 20.62 which is wrong!

![product report_pricelist](https://cloud.githubusercontent.com/assets/7599739/17047987/117a40ba-5000-11e6-9e07-cccf6af705c9.png)

Expected behavior:
* Rounding should be same at both location. In my example it should be 20.63 $

To Fix the problem Update _get_price method in product/report/product_pricelist.py

    def _get_price(self, pricelist_id, product_id, qty):
        sale_price_digits = self.get_digits(dp='Product Price')
        pricelist = self.pool.get('product.pricelist').browse(self.cr, self.uid, [pricelist_id], context=self.localcontext)[0]
        price_dict = self.pool.get('product.pricelist').price_get(self.cr, self.uid, [pricelist_id], product_id, qty, context=self.localcontext)        
        if price_dict[pricelist_id]:
            price = round(price_dict[pricelist_id], sale_price_digits)
        else:
            res = pool.get('product.product').read(self.cr, self.uid, [product_id])
            price = round(res[0]['list_price'], sale_price_digits)
        price =  self.formatLang(price, digits=sale_price_digits, currency_obj=pricelist.currency_id)
        return price

Thanks
Purnendu Singh
**Geminate Consultancy Services**

**Comment by Yenthe666** [comment]
@nim-odoo another one of those roundings..

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/aa1c3946daa08bc948c0e423554c603aa8cc67a2

**Comment by nim-odoo** [comment]
Thanks for reporting!
