### ISSUE TITLE
[9.0] Error in template when prefetch empty compute field

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#12889]
Impacted versions:9.0

Steps to reproduce:
1.- Create  a module
2.- Create a model inherited to account.invoice  with compute field 
```
 new_compute_filed = fields.many2one('relation",string="name" compute=_getcompute)

def _getcompute(self):
   self.new_compute_field = compute_id

```

3.- create a template:
``
<template id="dte_external_layout_header" inherit_id="report.external_layout_header">
        <xpath expr="//div[@class='header']" position="inside">
               <t t-if="'new_compute_field' on o and o.new_compute_filed"><span t-field="o.new_compute_field"/></t>
   </xpath>
</template>
``
4.- create an invoice and fill field
5.- click on print invoice, works fine 
6.- click on send email : get error
Current behavior:

Error get : 
openerp/models.py", line 3295, in _prefetch_field
    assert self in records and field in fs
QWebException: "" while evaluating
'o.new_compute_field'

This happens  too if you go to stock and click on print pdf some picking move

Expected behavior:

can use if to print when field is false

**Comment by mart-e** [comment]
Hello,

Please check again your custom code, it's missing comma, uses undefined variable, missing capitalized M for new api, etc.
Before trying to display it in a report, try to display the value in a form.

**Comment by dansanti** [comment]
HI! ok, a real example:
1.- Model:

``

class Invoice(model.Models):
        _inherit="account.invoice"

        @api.model
        def _get_available_issuer_turns(self):
            for rec in self:
                if rec.company_id:
                    available_turn_ids = rec.company_id.company_activities_ids
                    for turn in available_turn_ids:
                        rec.turn_issuer = turn.id

        turn_issuer = fields.Many2one(
            'partner.activities',
            'Company's Turn', readonly=True, store=True, required=False,
            states={'draft': [('readonly', False)]},
            compute=_get_available_issuer_turns
            )

``

2.- VIew:

``

<record id="view_invoice_form" model="ir.ui.view">
            <field name="name">l10n_cl.invoice.form</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
                <field name="journal_id" position="after">
                    <field name="turn_issuer"
                           domain="[('journal_ids', '=', journal_id)]"
                           options="{'no_create': True}"/>
                    </field>
               </field>
           </field>
</record>

``


3.- Template external layout:

``
<template id="dte_external_layout_header" inherit_id="report.external_layout_header">
        <xpath expr="//div[@class='header']" position="inside">
          <span t-if="'turn_issuer' in o and o.turn_issuer" t-field="o.turn_issuer.name" style="color:black;"/>
       </xpath>
</template>

``



Case 1 company have turn:
- In view we can select turn
- On layout pdf, we can see companys' turn,
- On click send email (invoice) we can't see mail composer get error 

Case 2  company have'nt turn:
- In view we can't select turn ( no error)
- On layout pdf we can't see empty (no error)
- ON click send email (invoice) we can't see mail composer, get error

Case 3 create a stock picking move:

- Create a stock picking,
- Click on Print picking operation, get error

**Comment by mart-e** [comment]
Thank you for the complete example, I think I understand the problem.
The expression `<span t-if="'turn_issuer' in o and o.turn_issuer" t-field="o.turn_issuer.name" style="color:black;"/>` is not correct. Try instead something like:

```xml
<t t-if="'turn_issuer' in o and o.turn_issuer">
          <span t-field="o.turn_issuer.name" style="color:black;"/>
</t>
```

Anyway, closing as it doesn't seem an issue in ORM but in the template customisation (I advise you to go to the forum for that).

PS: I assume this is only a partial example but the decorator `api.model` is wrong and missing `api.depends`.

**Comment by dansanti** [comment]
HI! thanks for tips, but i already tried with that method and get the same error :

``
models.py", line 3295, in _prefetch_field
    assert self in records and field in fs
QWebException: "" while evaluating

``

 , well I'll try to find more info about it thanks
