### ISSUE TITLE
[9.0] JS: unable to call query() - not a function

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#12884]
Impacted versions: 9.0

Steps to reproduce:
There is example in  [documentation](https://www.odoo.com/documentation/9.0/reference/javascript.html#high-level-api-calling-into-odoo-models) how to make **call()** and **query()** in js:
```js
var Model = require('web.Model');
var Users = new Model('res.users');
Users.query(['name', 'login', 'user_email', 'signature'])
     .filter([['active', '=', true], ['company_id', '=', main_company]])
     .limit(15)
     .all().then(function (users) {
    // do work with users records
});
```
I was trying to run this example but got error: **query()** is not a function.
Indeed, query is defined in **web.DataModel** not in **web.Model** but when I do this:
```js
odoo.define('my_module.service', function (require) {
"use strict";
var Model = require('web.DataModel');
});
```
I got unmet dependency  **web.DataModel**.

**Comment by mart-e** [comment]
Hello,

You are trying to execute this code on the backend of Odoo right? Not the website?

**Comment by lem8r** [comment]
Hi,
I'm trying to execute it on checkout page of website. Looks like it is intended for backend?

I'm doing shipping integration for ukrainian shipping provider. On checkout page I have to autocomplete City, Street, Warehouse etc while user is typing. There are thousands of records in database so I can't pass them as list selection. I have do query records from backend with domain filtering and pass couple variants as autocomplete suggestion.

I've managed to do what I need with lowlevel rpc search_read call.

**Comment by mart-e** [comment]
Indeed, this documentation page is the framework in backend. It should probably be specified somewhere...

**Comment by lem8r** [comment]
Oh, not an issue in this case)

**Comment by mart-e** [comment]
FYI I have clarified the doc at 880df4e8b67b408c390d9a24b0dfcfcd1494632b
`web.Model` (provides `call`) is available in both side while `web.DataModel` (provides `query`) is only available in the backend.

**Comment by lem8r** [comment]
Thanks!
BTW, what is proper way (in js on website) to check if there is valid session?

**Comment by mart-e** [comment]
Try with `session.session_is_valid()` (to check, not sure)

**Comment by lem8r** [comment]
In my case session.session_is_valid() was always falsy.
Looks like session object was new instance not the current one used by the system.
So I was checking if user was logged in backend's controller. I'm not sure if it is best way around.

**Comment by lem8r** [comment]
Any way, thanks for your support!
