### ISSUE TITLE
Missing dependency for xlwt in RPM package

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12897]
Impacted versions: 8.0

Steps to reproduce: install RPM package, open python console, execute `import xlwt`

Current behavior: `ImportError`

Expected behavior: works.

Video/Screenshot link (optional):

**Comment by Yajo** [comment]
@kutyel this was the bug you hit last week, fixed in https://bitbucket.org/yajo/docker-odoo/commits/4694dcf323bd222549118a3a9f66955977665094. Repull image and it will work (after rebuilt).

**Comment by mart-e** [comment]
Hello,

xlwt is an optional dependency and Odoo should not crash if you don't have installed (we have [some checks](https://github.com/odoo/odoo/blob/01acb8a497317162770df1a29e0236ae7d8f58bc/addons/web/controllers/pivot.py#L14) to verify if the module is present or not.
However for consistency (it is included in the deb package), it would make sense to add it also in rpm.
If you have a patch for master, would gladly accept it.

**Comment by Yajo** [comment]
xlwt comes in the v9 RPM AFAIK, maybe just backport that commit (wherever it is), not?

**Comment by mart-e** [comment]
Oh sorry I missed your issue was for 8.0 but anyway, if Odoo do work without xlwt (no error during use, all Excel-related options are hidden), I want to avoid changing the packaging. It would be an improvement, not a bug fix.

**Comment by Yajo** [comment]
OK no problem, fixing downstream at https://github.com/OCA/reporting-engine/pull/62
