### ISSUE TITLE
[9.0] bug in recurrent event 

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#12892]
Impacted versions:
9.0
Steps to reproduce:
1. Create a meeting follow this data:
Recurrent: True
Repeat Every: 1 days,
Until: **Number of repetitions** **0**
2. Save. 
3. Open meeting`s list or calendar view.

Current behavior:

Error raise and the system create million virtual event record.

Expected behavior:

not create any virtual event record.

Video/Screenshot link (optional):

**Comment by joshuajan** [comment]
This bug will block the calendar event.

**Comment by JKE-be** [comment]
Hello, cannot reproduce on runbot 9.0
Do you have some custo ?

**Comment by JKE-be** [comment]
![jke-2016-07-25_123858](https://cloud.githubusercontent.com/assets/4848797/17098877/08d3e4b8-5265-11e6-9619-099954ece803.gif)

**Comment by JKE-be** [comment]
Maybe Related to  : https://github.com/odoo/odoo/issues/12715
The infinite loop with 0 as count

**Comment by joshuajan** [comment]
@JKE-be Thanks. It`s the same as #12715. when the count is 0.
