### ISSUE TITLE
how to let float numbers in "tree" to be center?

### ISSUE THREAD

**Issue by vx0532** [odoo/odoo#12900]
Impacted versions: 
v9.0

Steps to reproduce:
I want all texts and numbers in tree to be in center; I write below codes:
.openerp .oe_list_content td , .openerp .oe_list_content th {
    background-color: #99ccff;
    text-align: center;
}

Current behavior:
only text in center rather than numbers;
Expected behavior:
I want all to be in center; or even I can control which column is left, right or center. or is there more convenient method to control this?
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,
Please use the forum for this kind of question. (https://help.odoo.com)
Here, it is the issue tracker.

Thanks
