### ISSUE TITLE
view_ids in python method

### ISSUE THREAD

**Issue by tchigy** [odoo/odoo#12908]
Impacted versions:
odoo 8.0 or 9.0
Steps to reproduce:
i opend a model from a python method with to mode_view  form,tree 
i used the view_ids syntax to define witch views should it shows 
Current behavior:
not working at all but when i use only one mode_view like form or tree view_id work fine
Expected behavior:
show me the views that i want not any views  if view_id work why not view_ids? 

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

You should use `views`, not `view_ids` in your python code.
[Example](https://github.com/odoo/odoo/blob/0da7184b67199e6944945558db63f55577ee5dbc/addons/crm/crm_lead.py#L837)

**Comment by tchigy** [comment]
Thank you mart-e
