### ISSUE TITLE
No Warning if you leave HR Timesheet widget page during modification 

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#12905]
Impacted versions:

8.0/9.0

Steps to reproduce:

See https://youtu.be/T_JUSs83IjE

Current behavior:

Currently if you add some lines in HR Timesheet with the JS widget avalaible on Summary tab of timesheet, no warning message is displayed to alert users that they may lose their changes if they try to leave the page by clicking another menu.

Expected behavior:

It's necessary to have an warning message  to alert users that they may lose their changes if they are changing their timesheet  as is done in the details tab and all the other places in Odoo

Video/Screenshot link (optional):

See https://youtu.be/T_JUSs83IjE

**Comment by adrienpeiffer** [comment]
OPW 684276

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

Thanks a lot for your report (and thank you for making a video, that makes things so much easier).
I agree there should be a warning that notifies the user that the changes will be lost.
@mart-e can you assign somebody on this one?

Regards,
Yenthe

**Comment by dmo-odoo** [comment]
Fixed at 7f86272b94b26b68aa1be3933d042efd9fd53008.
