### ISSUE TITLE
SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#12909]
Impacted versions: 8.0

Steps to reproduce: Some actions in our modules are giving this error.

Current behavior: Javascript exception

Expected behavior: We can use our screens.

Video/Screenshot link (optional):

The problem occurs because of commit 77eea3325 which does things with statusbar colors. reverting the commit resolves the error.

**Comment by JKE-be** [comment]
Seems like you have a wrong `self.node.attrs.statusbar_colors` value...
Could you check that cause of this exception ? What is the value of statusbar_colors before the json parse ?

**Comment by NL66278** [comment]
The value was indeed wrong:
{'rejected':'red','rejected_done':'red','cancel':'red'}

In json all properties should be in double quotes, not in single quotes. This is more strict then in xml where we have a choice. Exchanging the double quotes in the view xml will solve the problem.
This will work:
statusbar_colors='{"rejected":"red","rejected_done":"red","cancel":"red"}'
It would help to have a more precise error in the code, one that includes the parsed data. I found this by adding a try catch block to the code:
```
        try {
            var statusbar_colors = JSON.parse((self.node.attrs || {}).statusbar_colors || "{}");
        }
        catch(err) {
            statusbar_string = '' + (self.node.attrs || {}).statusbar_colors;
            window.alert(
                'Unexpected error ' + err.message + ' in JSON.parse of:\n' +
                statusbar_string
            );
```

**Comment by JKE-be** [comment]
Thank you for the feedback.

I close the issue now that it is fixed in you instance

> SyntaxError: JSON.parse: expected property name or '}' 

This error occurs most frequent when the json is badly formatted. (or by end user, or because a traceback is raised in the response)

**Comment by NL66278** [comment]
On the hand you might say that the single quotes in the xml attribute are sloppy code. On the other hand demanding the use of double quotes within the attribute value is an extra constraint that does not exist for other view element attributes in the system. Should be simple to replace the single quotes with double quotes before parsing the json data.

Will create a PR with proposed change.

PR will be on OCA version. I now realize the commit that caused the problem is only there.

**Comment by JKE-be** [comment]
Related to odoo/odoo#5987

**Comment by Vigneshwaran97** [comment]
I got an error from mainfest.json file,I don't know how to fix it 

Error:-JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data
[mainfest.docx](https://github.com/odoo/odoo/files/2052456/mainfest.docx)
