### ISSUE TITLE
how to make users in group A "readonly" for "field_x" and group B "editable" for the same "field_x"?

### ISSUE THREAD

**Issue by vx0532** [odoo/odoo#12901]
Impacted versions:
v9.0
.py file:

....

field_x=fields.Char("Name")

....

in xml file:

....

<name="field_x" groups="A" readonly="1"/>

<name="field_x" groups="B" />  

....

I have tried to set it like this, but group A will see nothing forever even if group B has changed the "field_x";

in the fact I just want to group A can read the "field_x" rather than write it and group B can both read and write it; shall I ?

in addition, I also want to get this effect: once  the "field_x" is filled by something, nobody can edit again. shall I?

**Comment by JKE-be** [comment]
Hello,
Please use forum for this kind of question.
Here, it is the issue tracker.

Thanks
