### ISSUE TITLE
Javascript Mime Type

### ISSUE THREAD

**Issue by saleembdr** [odoo/odoo#12902]
Impacted versions: 9.0

Steps to reproduce: 

- Install Odoo
- Open Odoo using Chrome

Current behavior:

Javascript files are not executing because the returned Mime Type is 'text/plain'. The page opens showing only the logo.

Expected behavior:

The page should open and execute javascript files. The Mime Types of javascript files should be 'application/javascript'.

**Comment by JKE-be** [comment]
Seems like a problem during your installation.
By default, it should works :)

Can we have more details about the way you installed Odoo ?

**Comment by saleembdr** [comment]
I installed Odoo using odoo_9.0c.latest.exe from http://nightly.odoo.com. It is working find on FireFox. IE and Chrome are showing 'text/plain' for the following files in the response header:

- web/content/246-6b457dc/web.assets_common.js
- web/content/249-2378441/web.assets_backend.js

**Comment by saleembdr** [comment]
Static files like '/web/static/lib/es5-shim/es5-shim.min.js' are returning a correct Mime Type. The issue is apparently encountered in Javascript bundles.

**Comment by JKE-be** [comment]
Can you check if the  mime type in your ir.attachments table ?  Is there correctly setted ?

**Comment by saleembdr** [comment]
The Mime Type for the following JavaScript bundles was incorrect in the ir_attachment table in the database:

web/content/246-6b457dc/web.assets_common.js
web/content/249-2378441/web.assets_backend.js

I have used the information in the issue with the URL 'http://github.com/odoo/odoo/issues/2595' before to modify the Mime Type for '.js' files in the registry. The Mime Type probably remained incorrect after reinstalling Odoo because I did not uninstall PostgreSQL in the process.

I have fixed this issue based of JKE-be's hint for checking the 'ir_attachment' table's 'mimetype' field for the concerned JavaScript files. The 'mimetype' field is now populated correctly after updating the registry records for '.js' files, uninstalling both Odoo and PostgreSQL and then installing Odoo.

**Comment by JKE-be** [comment]
@saleembdr Thank for the feedback.
I have some doubts about the uninstallation of Psql :/
but if it works for your... It is the most important :)

**Comment by saleembdr** [comment]
You may be right about not having to uninstall PostgreSQL. The issue might have been solved after restarting the machine multiple times and not because of uninstalling PostgreSQL. Thank you @JKE-be .

**Comment by wbison3** [comment]
this is still a problem on v11.

**Comment by js-landoo** [comment]
Same problem with v10 and v11.
Solved for v11 with this patch
https://github.com/odoo/odoo/commit/77ca51f0892ec62d357e099d5c2a91e580e35383
By now, for v10 I have backported manually. I hope Odoo includes patch in base odoo v10 as soon as possible.

**Comment by Shebhi** [comment]
> Same problem with v10 and v11.
> Solved for v11 with this patch
> [77ca51f](https://github.com/odoo/odoo/commit/77ca51f0892ec62d357e099d5c2a91e580e35383)
> By now, for v10 I have backported manually. I hope Odoo includes patch in base odoo v10 as soon as possible.
> Edited: in my case, server and client are windows 7 laptop.
> With ubuntu servers, we have not this problem.

Dear,
I have the same issue in my Odoo 11 which is running on Windows 10 Laptop. Do you have an easy fix for the issue ?
