### ISSUE TITLE
Analytics Plans - context error when journal is not set

### ISSUE THREAD

**Issue by pepetreshere** [odoo/odoo#1290]
In OpenERP 7.0, when using the account_analytic_plans module.

When creating an account_analytic_plan_instance, the create method attemps to receive the jorunal_id from the context, but it doesn't handle the escenario where the context is not set, that is the journal_id is false.

Please help confirm this issue, and accept my correction.

BR

Andres Calle
TRESCLOUD

**Comment by jeffery9** [comment]
related with #6473

**Comment by beledouxdenis** [comment]
Solved with revision e9e376a6de83abc18d21711b1f85572703be1e46.
