### ISSUE TITLE
[9.0c] When filter is applied not all records show

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#12915]
**Impacted versions:** 9.0c

**Steps to reproduce:** In a DB with many records, contacts for example, filter the contacts.

**Current behavior:** In a DB with approx. 30k contacts, when a user filters the list with a "Last Updated by" not all contacts that were last updated by that user show. 

Also doing it with additional filters applied so it doesn't have to pick from all 30k the contacts, it shows as Vendor but when the Last Updated by is applied it doesn't show anymore.

When checking the Contact's log for the Last Updated by it is indeed the user applied in the filter. 

Odoo log seems normal when the filter is applied.

**Expected behavior:** For registry to show when filter is applied.

**Video/Screenshot link (optional):**

**Comment by JKE-be** [comment]
Hello @edsersolis ,
What do you mean by  `Contact's log for the Last Updated` ? in view metadata ? 
Are you sure that the number of reacord has an impact ? 

Can you provide a screen cast ? because I never see an issue about it.
What are you typing exactly in filter ?
What is the network request generated ?

**Comment by edsersolis** [comment]
Hello @JKE-be what I mean for the log is Odoo's log (odoo.log) when the filter is applied.
Can't tell if the issue is with the amount of contacts, this has never happened to me before and this is maybe the DB with most contacts I've dealt with.

I got you the screencast here: https://youtu.be/ss6ba-xzmMY
I first search for the contact "Tinoco", the only result shown I opened it to show you that the Last update was made by Brian. After that I apply the filter "Last Updated by" contains "Brian". Other results show but not Tinoco.

**Comment by edsersolis** [comment]
Now I noticed something even worse. If I search for the last name (Bergman) instead of Brian, the searched contact shows. I retyped the name to make sure no special character or un-seen spaces were there and still the issue persists.

**Comment by JKE-be** [comment]
Hello @edsersolis 
'Last Updated by' is the field write_uid in the database.
It is updated only when you update field on this table.

![image](https://cloud.githubusercontent.com/assets/4848797/17167315/bce7e68e-53dc-11e6-9bde-09a53ba0c37e.png)


Now if a updated the name...
![image](https://cloud.githubusercontent.com/assets/4848797/17167369/f6fd186c-53dc-11e6-94a7-6cc5c204fa3b.png)

The last update is...
![image](https://cloud.githubusercontent.com/assets/4848797/17167380/0f7e91fe-53dd-11e6-93ce-c7e67600ff9b.png)

When you search...
![image](https://cloud.githubusercontent.com/assets/4848797/17167509/dec6b8e2-53dd-11e6-8b2b-5af17d731e8f.png)
![image](https://cloud.githubusercontent.com/assets/4848797/17167518/e517973e-53dd-11e6-88f1-466dcb4bd47a.png)
