### ISSUE TITLE
Can't Save Product Variants After Editing The record has been modified, your changes will be discarded. Are you sure you want to leave this page ?

### ISSUE THREAD

**Issue by AMEKCapital** [odoo/odoo#12914]
Can't save product variants .

https://drive.google.com/file/d/0B5CUfVV4TZAlZXNiWU9WeDAtTTg/view?usp=sharing

**Comment by JKE-be** [comment]
Need more info.
Please, use the default template ;)

Can you reproduce on runbot ?
Because I have just tested on 9.0e and it works ...
