### ISSUE TITLE
'"URL to" must start with a leading slash.

### ISSUE THREAD

**Issue by jasonribble** [odoo/odoo#129290]
Impacted versions: 16

Steps to reproduce: It's in the [code](https://github.com/odoo/odoo/blob/462c1eed41ecd975a511f7430e1fc303e449e869/addons/website/models/website_rewrite.py#L89) 

Current behavior: Validation Error when someone doesn't include a / for URL to in the Rewrites modules
  
Expected behavior: Unable to redirect to external websites. Super helpful for tracking and simplified. This validation should be removed

**Comment by trinhanhngoc** [comment]
This issue is caused by #122878

**Comment by jasonribble** [comment]
Thanks for linking them! I think removing that validation would allow for a new feature, not prevent a bug.
