### ISSUE TITLE
[Firefox] Website Builder: past text in translation doesn't work

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12934]
Impacted versions: 9.0c, 8.0

Steps to reproduce:

Current behavior:
The company text in the automatic footer is a never ending source for numerous erratic, nasty and truly annoying errors, not only, but especially for multi-language websites.
Anything else than a single unformatted string can break the footer any time and make the website unsaveable. Even if you replace the default text inside the default 2 < p > tags with truly unformatted text copy/pasted from a notepad or similar editor, it might break, and it breaks the latest when translating the website. The HTML Editor is of no help, because it contains only the text in the website default language. 
Newest joke: I did install the website contact form, it resulted in a 500 Server Error and I had to reset the automatic footer to default.
[TracebackAutomaticFooter.txt](https://github.com/odoo/odoo/files/386384/TracebackAutomaticFooter.txt)

This is a veritable PITA.

Expected behavior:

Please please please make it a field of type "text" or "html" in the backend company settings and immediate relief is provided to anyone.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be can you shed some light on this please.

**Comment by Yenthe666** [comment]
@treviser we both tried this but couldn't break it directly. Could you make a little GIF or give some more details about what exactly to edit please?

**Comment by treviser** [comment]
It is really difficult, because it seems an erratic behaviour.
I try to give you examples:

1. This is the footer text in the website default language (German):
![selection_224](https://cloud.githubusercontent.com/assets/1814941/17211563/7a1e3260-54ca-11e6-919d-7032fb6b5e63.png)

Then I change the website language to english and try to translate the footer text by copy/pasting some text. The text box gets a red frame and a white empty (error) message appears:
![selection_223](https://cloud.githubusercontent.com/assets/1814941/17211617/cf2dff10-54ca-11e6-89a5-354c4c8938c4.png)
It is not possible to save the changes, I have to discard what I did.
Now I did manually type in the english text and I was able to save it, everything is ok.

2. I added a new paragraph with a sentence in German (the default website language) manually (no copy/paste), it worked.
![selection_225](https://cloud.githubusercontent.com/assets/1814941/17211984/b43b6632-54cc-11e6-8325-9f380d3b4721.png)

I changed to english and did manually translate the new sentence (no copy/paste) and it worked.

3. I added a new sentence in the first paragraph of the default website language again by manually typing it, this works.
![selection_226](https://cloud.githubusercontent.com/assets/1814941/17212090/53814586-54cd-11e6-89e8-93f6083d3a0e.png)

Then I try to translate it and I see that the english text of the first paragraph is completely replaced by the german text:
![selection_227](https://cloud.githubusercontent.com/assets/1814941/17212128/ce4fe0b0-54cd-11e6-9089-891f87700605.png)
Clever as I am I did save the original text in notepad and try to replace the german text by copy/paste, it won't work, some error again:
![selection_228](https://cloud.githubusercontent.com/assets/1814941/17212323/c0f24506-54ce-11e6-8ca4-0775d06d87a7.png)
So I have to type the english text again manually.

- to be continued...

**Comment by treviser** [comment]
Conclusion:

There seems to be a logic behind, it is not erratic.

1. In the company text you can create one or more paragraphs and the same number of paragraphs is also created in other website languages.
2. You can not copy/paste any text, even if it is unformatted other than in the default website language.
3. If you change any text in the default website language, the complete translated text of the paragraph in the translated website is lost and replaced by the original text again.

**Comment by JKE-be** [comment]
Hello @treviser 

1. normal... The translation system work paragraph by paragraph...
2. If you past text withtout paragraph it works... but if you translate one paragaph by 2, it fails.
3. Have you tested ctrl + shift + v to avoid the formatting, because i can do it without error.
4. In v8, and v9, it has been always like that. If you add  even  one comma, the translation will be resetted. The matching with the source was strict (100%). In v10, a new version of translation has been done. And the old translation is marked as 'to update' but is no more ignored while the old source and new source stay x% similary.

About the empty popup, you should see `Translation is not valid:`

Maybe, @Gorash can give you more info if you want. He was implied in the dev of this new system of translation.

**Comment by treviser** [comment]
@JKE-be Thank you very much for your patience. After I was forced to invest some time, I think now I really understood how it works. However, Step 3 does not work for me on an Ubuntu Desktop16.04 client using the latest Firefox, no matter if I'm using ctrl + shift + v or ctrl + right-shift + v, it always creates a new paragraph which consecutively leads to an error when copy/pasting into the translated text, even if I'm deleting the line break afterwards.
The blank error popup might be related to the theme ("Real Estate" in this case), as I remember to have seen messages in other themes, but with another text (not understandable, but always related to something with "alternate.languages"..., it looked like something with the website language selector broke).

Newest finding:
Using the latest Google Chrome in the same environment, everything works fine. Changing the text in the default language does not reset the translated text in other languages! And copy/pasting text does not create a new paragraph and therefore works flawlessly.

**Comment by JKE-be** [comment]
> Changing the text in the default language does not reset the translated text in other languages! 

Sorry, you have right...  I have just retested... In v8 it is resetted... in v9, it is already 'fixed'

> And copy/pasting text does not create a new paragraph and therefore works flawlessly. (in chrome)

Glad to hear that...

---

About and the 'paste' which add paragraph, I have just tested, and it is really a bug. @qsm-odoo  can you take a look ???? 

About the empty popup in themes, @qsm-odoo can maybe take a look in low priority.

About the ctrl + shift + V for past unformatting text, seems like it is broken in FireFox/Adblock, but even with simple text from notepad, the paragraph is added so the translation impossible.
https://support.mozilla.org/en-US/questions/1071649

**Comment by Yenthe666** [comment]
@qsm-odoo any update on this?

**Comment by qsm-odoo** [comment]
Hello,
First of all, sorry for the very late fix of this issue.
This had just been fixed in 9.0 with commit https://github.com/odoo/odoo/commit/b836e00d70d723f74c56d40505a583f7fe9454be. The solution is not very elegant but should fix the reported problem while waiting for a better solution.
Again, sorry for the delay.
I am closing the issue, feel free to reopen it if any problem with the fix occurs.
