### ISSUE TITLE
Pricelist Onchange

### ISSUE THREAD

**Issue by 12e1121** [odoo/odoo#12939]
Impacted versions: 8.0

Steps to reproduce:

Current behavior:

Could anyone advise on how to pass the order_line's fields instead of ids?

For instance:

The Sales Order Line have 3 items (sale_order_line table have records). The order_lines's that pass during onchange are [6, 0, ids].

Is there anyway that during the on_change, i can pass the order_line like this:

[0, 0, [object object]], [0, 0, [object object]], [0, 0, [object object]]

Expected behavior:

Video/Screenshot link (optional):

**Comment by dbo-odoo** [comment]
Hello,

For advice please use our forum; Github should be reserved for issues (i.e. bugs or wrong behaviours, not advices on coding).

To reply to your question, no that is not possible; the commands that the form view sends and receive to/from the server for onchanges are coded that way and won't work like that. I'm not sure why you would want to do that in the first place.

Unless you can convince me that this is a real issue, I will close this issue.
