### ISSUE TITLE
[XmlRcp] TypeError: dictionary key must be string (account.move -> needed_terms)

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#129493]
# Impacted versions: 16

# Steps to reproduce:
Use Odoo Docker official image and run it with this options :

```shell
docker run -p 8069:8069 --env HOST=host.docker.internal --name odoo_16 --pull missing -t odoo:16 -- --database odoo-master-v16 --init "l10n_fr,account_accountant,sale_management"
```

Make an XMLRPC call "search_read" on the model `account.move` requesting all fields.

# Current behavior:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 148, in xmlrpc_2
    except Exception as error:
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 129, in _xmlrpc
  File "/usr/lib/python3.9/xmlrpc/client.py", line 975, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 508, in dumps
    dump(v, write)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 530, in __dump
    f(self, value, write)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 583, in dump_array
    dump(v, write)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 530, in __dump
    f(self, value, write)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 601, in dump_struct
    dump(v, write)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 530, in __dump
    f(self, value, write)

    raise TypeError("dictionary key must be string")
TypeError: dictionary key must be string
```

# Expected behavior: No error

I found the related field causing this error it's the field : `needed_terms`, if I remove it from the list of requested fields, then another error occured see #129494

**Comment by gdgellatly** [comment]
To be honest, XMLRPC is pretty much deprecated in Odoo and those new Binary fields / view domain things are pretty new. Who knows, maybe it is an oversight and they fix, but don't hold your breath. XMLRPC support for external connections, to the best of my knowledge was a side effect of the old GTK client and early webclients using XMLRPC. So Odoo themesleves I don't think need it anymore.

Most everyone moved to JsonRPC already.

**Comment by Prometee** [comment]
I would love to switch to JsonRPC but it needs a proper documentation and the fact that XML-RPC is deprecated needs to be explicitly written down here https://www.odoo.com/documentation/master/developer/reference/external_api.html

**Comment by gdgellatly** [comment]
Hmm, that is quite interesting, you should write a PR with a failing test for frozendict JSON returns.  Maybe the same as the the test for xmlrpc marshalling is enough to fail.  Then propose it. But that looks like an out and out bug. That will likely get attention. For the rest of XMLRPC it is much more likely to get sorted reporting under your enterprise contract than here, but sometimes for these kinds of issues they get dealt with, more than functional ones anyway.

**Comment by PeteKraft** [comment]
I'm facing the exact same issue, fetching all fields from 'account.move' throws the error mentioned above.

@gdgellatly do you have a source where odoo states that xmlrpc is being deprecated ? We are building a connector between our current ERP software and odoo with the xmlrpc api... as per odoo's instructions. 
If this is in any state of deprecation, I think we will want to exchange a few words with our contacts at odoo.

**Comment by gdgellatly** [comment]
I don't have any specific statement, more a summary of conversations over the years with Odoo dev's after they switched web client to JSONRpc. There is a lot in writing, I would search back through issues around functions returning None and xmlrpc failing particularly back around the time when JSONrpc became web client standard. Also back on this project when they switched and why https://github.com/OCA/odoorpc

**Comment by monty241** [comment]
This problem is occurring besides on `account.move` also on `sales.order`.

See:

- https://www.odoo.com/es_ES/forum/ayuda-1/odoorpc-keys-must-be-str-int-float-bool-or-none-not-frozendict-227142
- https://forums.invantive.com/t/odoo-v16-itgenodo047-odoo-server-error-keys-must-be-str-int-float-bool-or-none-not-frozendict-200/3671

In GitHub it is also already registered as #109938.
