### ISSUE TITLE
Reload Custom view type on click each time-Odoo8

### ISSUE THREAD

**Issue by mostafaic** [odoo/odoo#12943]
i have created a new view type like form view and when i create new thing from the form view and switch to my custom view i see no update till i refresh the whole site.i want to know how to reload this custom view to be able to retrieve the data each time i click on my custom view.
i have created the view on java script and everything work good except reloading the data each time i click the view.
i found this code and i have called a function in the views.js i inherit from the core web module var 
```javascript
zoser_book = new openerp.Model('zoser.book');
zoser_book.call('reload_controller'[view_type]).then(function(reload_ok){
    console.log(reload_ok);
    });
```
then in python i did that 

```python
def reload_controller(self, cr, uid, view_type, context=None):
    model_obj = self.pool.get('ir.model.data')
    print model_obj
    data_id = model_obj._get_id(cr, uid, 'zoser_book', 'zoser_book_views')
    print data_id
    view_id = model_obj.browse(cr, uid, data_id).res_id
    print view_id
    return {
        'type': 'ir.actions.act_window',
        'name': _('String'),
        'res_model': 'zoser.book',
        'view_type': 'bookview',
        'view_mode': 'bookview',
        'view_id': view_id,
        'target': 'current',
        'nodestroy': True,
    }
```
but i still see no update if i add new book from form view and switch to my custom view no update till i refresh the whole site.

**Comment by mart-e** [comment]
Hello,

Sorry but github is to report bugs on Odoo, not to ask advises on development. Check existing `web_*` modules that add new view type for examples.

For development help, you can try on the forum or mailing list or contact a partner
https://www.odoo.com/page/community
