### ISSUE TITLE
UX BUG - Invalidate Message on invoice lines

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#12955]
### Impacted versions:

9.0
### Steps to reproduce:

Create a Invoice with several lines and one of them missing an required field.
### Current behavior:

There is popping up a warning red popup, indicating "the following fields are invalid: Invoice Line".
Customer goes up the wall, because he has just registered a very long invoice and doesn't understand. And why is this read? "Am I going to loose all work??"
### Expected behavior:
1. It should show a hint in a less dangerous, more friendly colour. Could be orange, for example.
2. It should be more specific, because understandably the customer will not understand a word about the warning. If you do not agree on this point step back one step and try to understand this warning from the perspective of a non technical person: "Invalid Field" & Red Color = Catastrophy. "Invoice Line" = Whaat? All of them? One of them? Which one? What's happening? - while it's just a missing field WITHIN one specific invoice line.

@fpodoo

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thanks a lot for your report. I partially agree with you, the message could be better and more detailed in order to give the user a good sense of what is wrong. On the other hand, the red draws good attention so I don't think that should be removed.
@mart-e can I ask your input for this? I bet you'll say that this is expected / wanted behaviour and that it will not be changed.

**Comment by Yenthe666** [comment]
@mart-e could you give feedback please?

**Comment by mart-e** [comment]
Hi,

You are not supposed to be able to add a line without all the required field. You can not use the "add a line" button if the previous line is not correct. This was already true in v9.

Regarding the message, it should be an error and not a warning as it is blocking (warning = non-blocking).
The message "The following fields are invalid" is generic, this happens not only when a value is missing but also when you have an invalid number (e.g. a string in an integer field).

The idea would be to differentiate the "invalid" state for empty required fields but it is not as easy as it sounds (probably to hack around [here](https://github.com/odoo/odoo/blob/7671e0c30d2cbe6b91937858318ec205502a59ec/addons/web/static/src/js/views/basic/basic_renderer.js#L48) if somebody wish to give it a try).

**Comment by blaggacao** [comment]
For better per field UX: https://openui5.hana.ondemand.com/#/sample/sap.m.sample.MaskInput/preview
For better general invalid messages: The problem of long lists still exists in some context, for the moment it would be probably sufficient to just keep that in mind...
