### ISSUE TITLE
Account_edi: No Module named 'PyPDF2.utils' Pypdf 2.12.1

### ISSUE THREAD

**Issue by joshkreud** [odoo/odoo#129532]
Impacted versions:

16.0 on Python 3.11

Steps to reproduce:

1. Start Odoo on python 3.11 install requirements with ` pip install -r requirements.txt` 
2. This installs `PyPDF2==2.12.1`
3. Install `account_edi` Module in Odoo  

Current behavior:

Python throws `ModuleNotFoundError: No module named 'PyPDF2.utils'` in `account_edi.account.edi.format` 

Expected behavior:

No Error thrown on python module import. 

Error was introduced in https://github.com/odoo/odoo/commit/fb1c37de5e7d2941bd7523ca50f274720143a7fb

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by madisvain** [comment]
I can confirm the same issue when using Python 3.11

```shell
  File "/Users/konstruktor/Documents/erp/odoo/addons/account_edi/__init__.py", line 3, in <module>
    from . import models
  File "/Users/konstruktor/Documents/erp/odoo/addons/account_edi/models/__init__.py", line 5, in <module>
    from . import account_edi_format
  File "/Users/konstruktor/Documents/erp/odoo/addons/account_edi/models/account_edi_format.py", line 9, in <module>
    from PyPDF2.utils import PdfReadError
ModuleNotFoundError: No module named 'PyPDF2.utils'
```

**Comment by hafizhlf** [comment]
change

`from PyPDF2.utils import PdfReadError`

to

`from PyPDF2.errors import PdfReadError`

should fix this issue

references:
https://pypdf2.readthedocs.io/en/3.0.0/_modules/PyPDF2/_reader.html

**Comment by raghav24agarwal** [comment]
Have raised one PR for this issue. Please check
https://github.com/odoo/odoo/pull/130136

**Comment by niyasraphy** [comment]
fixed in: https://github.com/odoo/odoo/commit/bf426c9aa566601e7f113f1f05f355456034b81a
