### ISSUE TITLE
translation parameter error in 8.0 nl

### ISSUE THREAD

**Issue by gevaerts** [odoo/odoo#12950]
Impacted versions: 8.0

openerp/addons/base/i18n/nl.po has:

```
#. module: base
#: code:addons/models.py:3382
#, python-format
msgid ""
"Database fetch misses ids ({}) and has extra ids ({}), may be caused by a "
"type incoherence in a previous request"
msgstr "Databank ophalen mist ids ([]) en heeft extra ids ([]), kan zich voordoen door een type incoherentie in een vorige aanvraag"
```

Note that ({}) has been translated as ([]). This means that the parameters are not shown in translated error messages.

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on Transifex, not Github.

Anyway I have fixed it on Transifex but you know for next time

Thanks

cc @Yenthe666

**Comment by Yenthe666** [comment]
This one must've slipped through.. Sorry guys.
Thank you for reporting it and @mart-e thanks for fixing it :+1:
