### ISSUE TITLE
DataError: invalid input syntax for type timestamp: "٢٠١٦-١٠-٣١ 00:00:00" forecast tasks menu project module

### ISSUE THREAD

**Issue by Develoman** [odoo/odoo#12960]
Impacted versions: entreprise

Steps to reproduce: load arabic language and affect it to administrator

Current behavior: forecast tasks using Gantt chart in project module

Expected behavior: 
```
DataError: invalid input syntax for type timestamp: "٢٠١٦-١٠-٣١ 00:00:00"
LINE 4: ...        WHERE (("project_forecast"."start_date" < '٢٠١٦-١٠-٣...
                                                             ^
```

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Develoman,

Thanks a lot for your report. I've just tested this and can confirm this is a bug. The result:
![image](https://cloud.githubusercontent.com/assets/6352350/17251384/e1e90b70-55a8-11e6-8a9d-78bb244a0432.png)
@mart-e this is language related, so probably something for you!

**Comment by mart-e** [comment]
Thanks for the report, I have fixed it at 33a2607dd4c41877cd777e2ef25ba019b2391b80

**Comment by Develoman** [comment]
@mart-e  the commit link not found !  https://github.com/odoo/enterprise/commit/33a2607dd4c41877cd777e2ef25ba019b2391b80

**Comment by mart-e** [comment]
@Develoman the bug report was for an enterprise module so I have fixed it in enterprise repository which is private except for the partners with enterprise contract. So just update your enterprise code to get the fix :)
