### ISSUE TITLE
[9.0c] Safari won't print PDF reports and screen width is wrong

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#12967]
Impacted versions: 9.0

Steps to reproduce: Open an instance in Safari browser. Try to print. Open a dashboard screen, ie. Accounting Dashboard.

Current behavior: When trying to print an error pops up and doesn't print the PDF even having the wkhtmltopdf installed. Also the Dashboards don't fit the screen and you'd have to scroll the page to the right to see other dashboards.
On Chrome it shows fine and prints the PDF without any troubles.

Expected behavior: Show the dashboards fitted correctly to the screen (no need for horizontal scroll). Print the PDF correctly.

Video/Screenshot link (optional):

**Comment by edsersolis** [comment]
For the screen width issue is the same behavior as shown in this report: #12929

**Comment by sle-odoo** [comment]
Which version of safari are you using? What's the error message displayed when you're printing a report?
