### ISSUE TITLE
How to see all records from all companys

### ISSUE THREAD

**Issue by johnsh** [odoo/odoo#12965]
hi everybody,

I have a Odoo 9 Installation where I have active multicompany, but some users needs to see all records from all companys, What is the best way to do it ? I know that is possible modify the rules access, but it is correct ?

( I know that is possible switch the company from the user settings  )

Thanks

**Comment by JKE-be** [comment]
This tracker is for issue only.
Please, use https://help.odoo.com to this kind of question...

**Comment by johnsh** [comment]
Sorry
