### ISSUE TITLE
PhantomJS tests submit forms in loop

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#12961]
Impacted versions: 9

Steps to reproduce:

Assuming you have something like this in your home page:

```
<form>
  <input name="something"/>
  <button type="submit"/>
</form>
```

A test similar to this would send the form twice:

```
Tour.register({
    id: "form_submit_twice",
    name: "Test if tour submits twice",
    path: "/",
    mode: "test",
    steps: [
        {
            title: "Set some name",
            element: "form input",
            waitFor: "form input",
            sampleText: "Some input text.",
        },
        {
            // This step does get triggered twice
            title: "Send form",
            element: "form button[type=submit]",
            waitFor: "form button[type=submit]",
        },
    ]
});
```

Current behavior: Sends form twice.

Expected behavior: Send form once, then continue to next step.

**Comment by Yajo** [comment]
Real-life example: https://github.com/OCA/website/pull/239/files#diff-928c151b24bf60cecfc381508bdd72deR61

**Comment by sle-odoo** [comment]
How do you know it's submitted twice? Do you have two entries in the log for the same request?

**Comment by Yajo** [comment]
Indeed. [I made them](https://github.com/OCA/website/pull/239/files#diff-be4206399e191bfe53c175df5afc0070R152) just because of this bug.

You'd have to remove the workarounds from the tour to see the bug if you pull that module.

**Comment by Yajo** [comment]
In fact, it's not only twice. It's like the tour does not know it filled the step, and then when page reloads after submitting the form, it starts again by the same step instead of starting from the next one.

What [my workaround](https://github.com/OCA/website/pull/239/files#diff-928c151b24bf60cecfc381508bdd72deR13) does is monkey-patch to know if we are in the already-submitted page and force the tour to advance one step.

**Comment by sle-odoo** [comment]
It seems weird that in your tour you have a lot of times the same selector in your element and on wait keys. However i always forget what are the semantics of these keys. Let me check...

**Comment by Yajo** [comment]
Is it not required?

**Comment by Yajo** [comment]
Finally travis is working. You can see that lines like this should not appear in the logs if this bug was fixed: https://travis-ci.org/OCA/website/jobs/148327125#L937

**Comment by rafaelbn** [comment]
:+1:

**Comment by sle-odoo** [comment]
@Yajo it seems that the tour system in v9 is not so smart and if a ```waitFor``` or a ```waitNot``` condition is honored for multiple consecutive steps and that the page is reloading between the steps, the tour will not understand that it should go to the next one and still run the same step if the condition are still matching.

It looks like it's your issue, as you always have to use your workaround function after a save or a search (does it trigger a refresh?). So you have to make your wait* conditions more strict.

This "issue" (it's more a limitation of the way the tour mechanism is implemented) is fixed with the new tour mechanism in v10 (web_tip) because the steps done are now really marked as done.

**Comment by Yajo** [comment]
I can't find `web_tip`. Do you mean [`web_tour`](https://github.com/odoo/odoo/tree/master/addons/web_tour)?

**Comment by sle-odoo** [comment]
yes

**Comment by pedrobaeza** [comment]
@Yajo is this still happening in v10? Is it relevant for you?

**Comment by Yajo** [comment]
I didn't find this problem on v10 tours so far.
