### ISSUE TITLE
Website_forum: do not allow user to post an empty answer

### ISSUE THREAD

**Issue by abdounasser202** [odoo/odoo#12962]
Impacted versions: odoo.com

Steps to reproduce: 
Try to post an empty answer of a question in the forum

Current behavior: 
The empty answer is published

Expected behavior: 
Raise a message telling user he can't post an empty answer

Video/Screenshot link:
https://www.odoo.com/fr_FR/forum/aide-1/question/radio-button-105403

**Comment by Yenthe666** [comment]
@JKE-be would be a nice little addition? :smile:

**Comment by abdounasser202** [comment]
Cool! @Yenthe666  @JKE-be

**Comment by Yenthe666** [comment]
@abdounasser202 thanks a lot for the suggestion by the way, good idea.
