### ISSUE TITLE
Make project name (field "name" in "project.project") translatable

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#12968]
Impacted versions: 9.0c

Steps to reproduce:

Current behavior:
The project name is not translatable. I can't see any reason why it shouldn't be.

Expected behavior:
The project name should be translatable as any other names too.
Video/Screenshot link (optional):

**Comment by wtaferner** [comment]
@treviser 
Why would you translate a project or a task name? Do you have a specific use case in mind?
It is imho not like a product, a website or similar which you want to perfectly present to multiple target groups. If you have a multilingual team you probably would use English or any other common language as a project language and therefore work in this language as a means of communication based on the scope of the project.
And who would do all the work to translate this stuff? Pretty much overhead imho. I doubt this is common sense as distributed teams are here to save time and not to prepare translations for every person in the team.

But as always, if it is needed it is easily done by extending the core with a little module and add the ```translate=True``` to each field you want to translate specifically on a user/company scope.

My 2 cents :-)

**Comment by treviser** [comment]
@wtaferner It does not create any additional work or overhead for nobody, as long as he does not want to use it. It also does not create any hassle for the Odoo codebase. Deciding if a name field of a core entity should be translatable or not (if that was a decision at all and not only just a neglect) takes more effort than just to do it if for consistency reason at all. But there are several reasons why it might have a benefit:
- internal projects for tracking internal employee hours in a multilingual company
- project customers prefering another language than the company's internal language
- project templates to be used in a multilingual environment.
Don't forget, Switzerland is not much bigger than Austria, but we have 4 official languages :-)

**Comment by wtaferner** [comment]
You have a point and as long translation framework improves it will be easy to maintain in the future as well.
I know that it was improved for master/10, so let's see if your desire is heard and shared by Odoo SA ;-)

**Comment by treviser** [comment]
@wtaferner I'm not sure if we are talking about the same, I do not see any relation to a translation framework, this is what I mean:
![selection_234](https://cloud.githubusercontent.com/assets/1814941/17271349/6f14fe84-5679-11e6-80bf-df3460c8260d.png)

**Comment by wtaferner** [comment]
I know, and this is/was usability wise so far not soo nice especially duplicating stuff, so I was asking for the rational behind, but it should be better for v10 and why not make it able to translate for templates/projects/analytic.

**Comment by pedrobaeza** [comment]
@JKE-be I see that in v11, the project name is still not translatable, but it should be? I'm not sure it's a desired behavior. Please close it if you feel the same.
