### ISSUE TITLE
Crash with search block (s_searchbar) in website

### ISSUE THREAD

**Issue by bvneodiensis** [odoo/odoo#129728]
**Impacted versions**: 16.0

**Steps to reproduce:** 
- Drag and drop a search block in a new website page
- Save
- Type something in the search bar -> Crash
- Submit your search -> Crash

**Current behavior:**
The search crashes for both autocomplete and when clicking on the search button.

**Expected behavior:**
The search block should work normally.

**Video/Screenshot link (optional):** /

**Support ticket number submitted via odoo.com/help (optional):** /

![Capture1](https://github.com/odoo/odoo/assets/128726777/d6dbe9af-4df4-49ee-8b3e-85bade8558b2)
![Capture2](https://github.com/odoo/odoo/assets/128726777/90d5d3c1-c562-47d5-8cbd-b1805da6a85e)

**Comment by rdeodoo** [comment]
Hello

Thank you for the report.
Is this flow what you describe? https://watch.screencastify.com/v/FqhEBtWgztdkeLMxlJRU
I can't reproduce the error on a fresh 16.0

**Comment by bvneodiensis** [comment]
Hello, 

Thank you for your answer and for taking the time to try to reproduce the issue.

After searching in our databse, we noticed in the table **website_page** some entries were NULL for the column "**url**". After changing the values to a default one (such as "-"), the search started working normally.

I don't know why these entries had a NULL value for their "url" column since we got the database from one of our partners. But it would be preferable to set this column as not null, or to add additional checks in the code in order to avoid this issue in the future.

Regards,

Bastien

**Comment by rdeodoo** [comment]
As there is a legit way in each version to create a page without an URL, I'll make a quick fix for that in Odoo 15 where the bug was introduced.
We will see in master if we can simply make this URL field required.

**Comment by bvneodiensis** [comment]
Thanks a lot.

Just as a side note, since adding a default value led to another issue :  I just noticed that having a default value for these "ghost" pages isn't maybe the best solution since they will appear in the search. We can of course delete these pages, but I'm not sure why they remained there in the first place. We have to make sure these "ghost" pages are not stored in the database.

![Capture3](https://github.com/odoo/odoo/assets/128726777/ea86bfeb-6134-442e-b63d-df12ee2f10ff)
