### ISSUE TITLE
[8.0]Promote This Page 

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#12976]
Impacted versions:8.0

The "Promote This Page" function works only for the homepage, the mask to enter keywords only appears for the homepage

Steps to reproduce:
trying to promote a different page from the homepage, promotion mask appears
Current behavior:
currently pressing on the link should promote comaprire the promotion of the mask mask
Expected behavior:
The "Promote This Page" screen should appear for all menu items displayed

**Comment by JKE-be** [comment]
Hello @roccocesetti 
Thank you for the reporting but can you provide a screen cast ? 
We don't understand your error...

We have just re-tested in V8, and all seems to work fine.

**Comment by Yenthe666** [comment]
Hi @roccocesetti ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
