### ISSUE TITLE
Create Invoice From picking

### ISSUE THREAD

**Issue by milan-thakkar** [odoo/odoo#12980]
Impacted versions: 8.0

Right now in version 8 when we create invoice from picking(change the destination location to supplier) at that time create only customer invoice instead of supplier invoice.

![transfers odoo](https://cloud.githubusercontent.com/assets/13216534/17294886/0c68c5d2-5817-11e6-91db-90fd4cf97e1f.png)
![transfers odoo_2](https://cloud.githubusercontent.com/assets/13216534/17294887/0c69831e-5817-11e6-8c4c-fd6e09dc274c.png)

**Comment by vgo-dev** [comment]
@milan-acespritech , You are right some where , i check what you want to present, 
As per my view need improvement ,
there is two way to resolve: 1.give domain in location.
2.need to be create supplier invoice. 
if i am wrong then please correct me...

**Comment by milan-acespritech** [comment]
@vgo-dev Needs to improvement and i believe no needs to define domain...
for invoice based on location type you can easily find out way of creating invoice for supplier or not.

**Comment by vgo-dev** [comment]
@milan-acespritech lets pull it

**Comment by Yenthe666** [comment]
Hi @milan-thakkar,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
