### ISSUE TITLE
Create contact shows wrong form coming from a company sheet.

### ISSUE THREAD

**Issue by jlsuarez7** [odoo/odoo#12998]
Impacted versions:
9.0c

Steps to reproduce:
1. Go into module Contacts
2. Select a company
 You should see the company in Form view
3. Click on List View
4. Click on Create

Current behavior:
The form will have Company radio button as active, but shows the form as if Individual radio button is selected. (When you select Individual and then Company again, then you will get the correct form)

Expected behavior:
Either the radio buttons should be on Individual or the form should be showing the Company form.

Video/Screenshot link (optional):
the wrong form:
![schermafbeelding_080316_104433_am](https://cloud.githubusercontent.com/assets/20810856/17359551/5f0736ec-5967-11e6-8998-ce94cfc61ba5.jpg)

how it should look:
![schermafbeelding_080316_104510_am](https://cloud.githubusercontent.com/assets/20810856/17359564/6eeaeda6-5967-11e6-9701-61ff9daf4715.jpg)

**Comment by Yenthe666** [comment]
Hi @jlsuarez7,

Thanks a lot for your report. I can confirm that this is not correct behaviour and that this should be fixed.
@mart-e can you look at this please?

Regards,
Yenthe

**Comment by mart-e** [comment]
@ged-odoo could you take a look? It seems that the `default_get` is not correctly applied on the `FieldRadio` widget. You have the same bug with the "Email Messages and Notifications" field, the value is not properly reset.

**Comment by jlsuarez7** [comment]
This commit https://github.com/odoo/odoo/commit/414ad99a922deac45aaaf8ee3da9b1bea3341d29 fixed the issue.
