### ISSUE TITLE
Odoo POS - print receipt only when needed

### ISSUE THREAD

**Issue by gwasky** [odoo/odoo#13008]
Impacted versions:
8.
Steps to reproduce:
Add Items to a bill, enter amount paid by customer. Validate transaction.

Current behavior:
Receipt is printed on validation.

Expected behavior:
Need an option to either choose to print a receipt or not on validation
Any ideas?
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Sorry but it is not possible for now (there is the pos_reprint module to manually print again an order but still need to print it the first time).
It is actually wanted on most POS (must be fast, want to press the min number of buttons) so sorry but we don't provide it so far.
