### ISSUE TITLE
Advance search Favorite filter checkboxes acts like radiobuttons

### ISSUE THREAD

**Issue by jlsuarez7** [odoo/odoo#13000]
Impacted versions:
9.0c

Steps to reproduce:
1. Click on module Contacts (or other modules with advance search like e.g. Sales or Apps)
2. Show the advance search bar by clicking on the little triangle, on the right side of the search bar.
3. Click on Favorites
4. Click on Save current search
5. Select `Use by default`
6. Select `Share with all users`

Current behavior:
When you select either one the other one will be deselected as if they are radio buttons.

Expected behavior:
You should be able to select them both. To share your default favorite filter with other users.

Video/Screenshot link (optional):
![schermafbeelding_080316_105744_am](https://cloud.githubusercontent.com/assets/20810856/17359916/207bd19c-5969-11e6-8b7e-1fb7dd6bcc30.jpg)

**Comment by Yenthe666** [comment]
@mart-e I've noticed this before too and I too would love the ability to be able to do both.
Is this perhaps something we could change or implement by V10?

**Comment by jlsuarez7** [comment]
Use this workaround if you want to able to set them both now:
1. Save a new filter with 'Share with all users' selected
2. Go into Developer Mode
3. Go to Settings
4. Click in the menu on 'User Interface' under 'Technical'
5. Click on 'User-defined Filters'
6. Select the filter you created in the 1st step
7. Click on Edit
8. Check 'Default Filter'
9. Click on Save

**Comment by mart-e** [comment]
@amigrave I believe you added this at f20c884cf5227052f368352c9dc7664ed7831e21 which I am sure you recall the reason

**Comment by fpodoo** [comment]
We removed it for usability reasons. We had too much issues with customers
in production with it.

**Comment by mart-e** [comment]
Thanks for the info @fpodoo.
So as said, it's actually wanted because users did not understood the implication of "set by default for all" (which was odd, I don't want other people messing with my default filters).
