### ISSUE TITLE
[9.0] html_frame widget saves empty value in 'code view' mode

### ISSUE THREAD

**Issue by gordonzola** [odoo/odoo#13018]
Impacted versions:
- 9.0
- My browser is Firefox-45.2.0 on a Gentoo GNU/Linux system

Steps to reproduce:
- activate developper mode (by adding `?debug=1` at the end of the URI)
- open a form containing an `html_frame` widget (for example, edit a `mass_mailing` object) in editing mode
- click the *code view* button
- save the form

Current behavior:
- The saved value is empty.

Expected behavior:
- The HTML content should be saved as seen in the widget
- The developper mode requirement does not, in my opinion, invalidate this issue, given that everyone can activate it.

**Comment by Yenthe666** [comment]
Hi @gordonzola,

Thanks a lot for you report.
I've just tested this and I can confirm this is a bug. They are rendered correctly if you're no in the code view, they don't render correctly when you save while being in the code view mode though. An example:
![image](https://cloud.githubusercontent.com/assets/6352350/17398986/06aa2f98-5a40-11e6-9a4b-8a66c1e0ac7e.png)
@sle-odoo and @mart-e this is something for you guys.

**Comment by mart-e** [comment]
@Gorash @qsm-odoo any idea on this?

**Comment by Gorash** [comment]
Yes don't save in code view: because the content must be converter by in-liner to save it and if the user want to save the code view directly, it's wrong. The code view is in debug mode for knowledgeable person.

**Comment by mart-e** [comment]
So while we confirm the preview is not working in debug mode + code view, it is an advanced feature only available in debug mode still experimental. We will try to improve that but it is not a priority, sorry.
