### ISSUE TITLE
NameError: global name 'f' is not defined

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#13010]
Hi,
Just a reminder in case this bug lands in v10 final...
See here https://github.com/odoo/odoo/blob/master/openerp/models.py#L2841
(cc @rco-odoo )

**Comment by Yenthe666** [comment]
Hi @ccomb,

Thanks for the report, that indeed looks like a bug right there. Strange that the automated tests didn't fail on this :smile: 
@mart-e and @odony putting you guys in CC too, as this is quite important. (even though it is the master)

**Comment by odony** [comment]
Thanks for the heads up, fixed in `saas-12`, to be forward-ported soon in master.
