### ISSUE TITLE
[8.0] l10n_de: why bank account allows reconciliation?

### ISSUE THREAD

**Issue by kaerdsar** [odoo/odoo#13036]
Impacted versions: 8.0

I'm doing reconciliation for creditors accounts. When I request to find operations to reconcile I get operations with account of type bank. Usually the accounts that should be reconciled are debtors, creditors or other with similar purposes. In the Germany localization module, bank accounts has the attribute Allow Reconciliation set to True. I would like to know the reason in order to check if I should modify the chart of account or take into account other behavior.

**Comment by qdp-odoo** [comment]
yep, indeed they shouldn't be set to True by default.

Can you name those accounts and specify which chart template of Germany you're talking about?

thanks

**Comment by kaerdsar** [comment]
@qdp-odoo thanks for your answer. Here the details

In the branch 8.0, module l10n_de: https://github.com/odoo/odoo/blob/8.0/addons/l10n_de/account_chart_skr03.xml

An example you can see in line 1533:

```xml
<record model="account.account.template" id="account_1120">
            <field name="name">Postbank 2</field>
            <field name="code">1120</field>
            <field name="reconcile" eval="True"/>
            <field name="type">liquidity</field>
            <field name="user_type" ref="account_type_asset_de"/>
            <field name="parent_id" ref="view_balance_1660"/>
  </record>
```

You can check other accounts of type liquidity. I can help in the fixing in case you confirm there is problem.

**Comment by qdp-odoo** [comment]
yes, I confirm and will gladly merge any PR related :)

**Comment by kaerdsar** [comment]
@qdp-odoo PR created -> https://github.com/odoo/odoo/pull/13520

**Comment by qdp-odoo** [comment]
PR merged
