### ISSUE TITLE
[R&D] Implement num2words python library and deprecate amount_to_text methods

### ISSUE THREAD

**Issue by grottas** [odoo/odoo#13049]
Hi All:

There is a method for converting numbers to words, useful in many cases, e.g. fro writing checks, expresing the invoices in words, etc. The actual method in the file openerp/tools/amount_to_text.py and amount_to_text_en.py  doesn't have many languages implemented, seems to be  an unmaintainable and horrible code (see closed PR [#2650 comment](https://github.com/odoo/odoo/pull/2650#issuecomment-56531888) by @sle-odoo ).

The idea with this issue is to continue the discussion started on this PR: [#12546](https://github.com/odoo/odoo/pull/12542), as it is a generic discussion, and it seems that the path is to deprecate the **amount_to_text** method and instead of that, implement the python library [num2words](https://pypi.python.org/pypi/num2words), published by Virgil Dupras @hsoft and maintained by @savoirfairelinux .

If it is of Odoo SA interest and if is considered the best way improve this functionality, this could end in closing the Issues and PR mentioned before and also this ones: [#1562](https://github.com/odoo/odoo/issues/1562) and [#9396](https://github.com/odoo/odoo/pull/9396), and keep this idea going here for having a more ideal solution for this requirement.

cc to the other people who have been knowing about this, and thanks for your attention (@dreispt @mart-e @antonylesuisse @gurneyalex @mbcosta @sasprilla @lepistone).

cc to my teammate @elmonitor

Regards,

**Comment by antonylesuisse** [comment]
Yes we will use num2word with a fall back to empty string if the lib cannot be located. PR are weclomed.
 Show all checks

**Comment by dreispt** [comment]
Anyone wants to pick this up?

**Comment by elmonitor** [comment]
It would be great odoo to consider this improvement, this solution could be implemented not just for check writing but for invoices and others accounting reports. Num2words python library supports languages (taken from https://github.com/savoirfairelinux/num2words):
    en (English, default)
    fr (French)
    de (German)
    es (Spanish)
    lt (Lithuanian)
    lv (Latvian)
    en_GB (British English)
    en_IN (Indian English)
    no (Norwegian)
    pl (Polish)
    ru (Russian)
    dk (Danish)
    pt_BR (Brazilian Portuguese)

This project is on github, so it can be included other languages to support.

**Comment by mbcosta** [comment]
Hi all,
    I just found one problem to use in Brazilian Localization is the package on https://pypi.python.org/pypi/num2words is outdated, https://github.com/savoirfairelinux/num2words/issues/50

**Comment by mbcosta** [comment]
Thanks all,
I make a PR in Brazilian Localization https://github.com/OCA/l10n-brazil/pull/456 to use num2word lib, until this lib become required by odoo

**Comment by mart-e** [comment]
Hello

Good news, num2words [has been added into Odoo](https://github.com/odoo/odoo/commit/e0be5bb11cd857708d57cc757a54eed044b76a4b) (since saas-14) !

Pull requests welcome to clean the remaining calls to the bad amount_to_text to convert them to num2words.
