### ISSUE TITLE
Creation of Ticket Helpdesk from an email

### ISSUE THREAD

**Issue by LCPesaro** [odoo/odoo#130415]
Impacted versions: 16.00

Steps to reproduce: Configure incoming mail server with POP protocol and the action "create Ticket Helpdesk" (OCA HELPDESK MODULE), build a form with odoo website module that send email to the incoming email server

Current behavior: after sending the email the ticket is not created end odoo logged this error "Ignored mail from "email_from" to "mail_to" with Message-Id <669578707956406.1690539133.964545011520386-openerp-private@host.info>: found duplicated Message-Id during processing
""
Expected behavior: I expected ticket will be reated after email sent

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by intero-chz** [comment]
Can't you just let Odoo create the ticket by submitting the form? Why bypassing that by creating a mail?

Oh and the log is already telling you what's happening. Odoo is sending the mail, every mail also creates a message with a message-id. Odoo won't process mails with a message-id already in system.

**Comment by pedrobaeza** [comment]
Problem not related to the module, so closing.
