### ISSUE TITLE
Multiple email/phone handling for contacts

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1304]
Contacts should have the ability to store multiple email addresses and phone numbers

**_Impacted versions:**_
- 7.0-20140709-231246

**_Steps to reproduce:**_
1. Open a contact
2. Edit
3. Only one email/phone per contact is possible

**_Current behavior:**_
- Only one email/phone per contact is possible, there is no way to enter additional email addresses / phone numbers associated with the contact. (There is both "phone" and "mobile", but one is not able to enter multiple "mobile" numbers for example).

**_Expected behavior:**_
- Email addresses and phone numbers can be added as a label/data pair, with an open quantity of pairs allowed. Primary record is selectable.

**Comment by dskarataev** [comment]
+1

**Comment by rruebner** [comment]
Although it is a topic with different opinions we want to start to create a new module to add the possibility to handle multiple addresses, emails and phones per partner. If you are still interested feel free to participate at https://github.com/blooparksystems/partner/issues/1. Ideas, approaches, solutions are welcome.

**Comment by antonylesuisse** [comment]
You can create sub contacts.
