### ISSUE TITLE
[8.0] [9.0] inner page menu

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#13040]
any plans to add inner page menus for website ?

https://ps.w.org/inner-page-menu/assets/screenshot-1.png?rev=1169403

**Comment by JKE-be** [comment]
Technically, it should be possible to do it...
It is a question of design...

Maybe, a theme already use it ...

**Comment by ddfs** [comment]
i agree, technically a lot of things are possible.

**Comment by JKE-be** [comment]
lol :+1: 
When I say technically, i should say:
   Probably without external module ...
  Just with html / js / base menu model...

That should not require any extra `complicated` dev :package:

**Comment by JKE-be** [comment]
For example:
   

```
 <div id="wrap" class="oe_structure oe_empty container">
      <div class="row">
        <div>
          <h3>Left menu</h3>
          <div>
            <ul class="nav nav-pills nav-stacked col-md-3">
              <li class="active">
                <a href="#a" data-toggle="tab" aria-expanded="true">One</a>
              </li>
              <li>
                <a href="#b" data-toggle="tab" aria-expanded="false">Two</a>
              </li>
              <li>
                <a href="#c" data-toggle="tab" aria-expanded="false">Twee</a>
              </li>
            </ul>
            <div class="tab-content col-md-9">
              <div class="tab-pane active" id="a">My first text</div>
              <div class="tab-pane" id="b">My second text</div>
              <div class="tab-pane" id="c">My 3th text&amp;nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>
```

Will make the job (http://164357-9-0-72479c-all.runbot.odoo.com/page/menu-in)

**Comment by ddfs** [comment]
thanks, i was thinking more like using model used in top_navigation. create and call them from them. 

i will work on this and hopefully will get it working :)
