### ISSUE TITLE
Small change to form.common.js

### ISSUE THREAD

**Issue by ossvn** [odoo/odoo#13046]
Impacted versions: 9.0

Current behavior:
`if(multi_select) {
                    options.buttons.splice(1, 0, {text: _t("Save & New"), classes: "btn-primary", click: function() {
                        $.when(self.view_form.save()).done(function() {
                            self.view_form.reload_mutex.exec(function() {
                                self.view_form.on_button_new();
                            });
                        });
                    }});
                }`
Expected behavior:

`if(multi_select) {
                    options.buttons.splice(1, 0, {text: _t("Save & New"), classes: "btn-primary o_formdialog_save_more", click: function() {
                        $.when(self.view_form.save()).done(function() {
                            self.view_form.reload_mutex.exec(function() {
                                self.view_form.on_button_new();
                            });
                        });
                    }});
                }`

Video/Screenshot link (optional):

I'm doing some shortcut for Odoo, but I can't find the ID of "Save & More" button when you're on sale order line modal.

I think it would be great if we can add more specific classes to buttons, even for others, it would be easier to customize than all the button on the same classes.

**Comment by pedrobaeza** [comment]
This is not really an issue. If you want a change in code, please submit a PR.
