### ISSUE TITLE
Blog post background_image bug

### ISSUE THREAD

**Issue by thomas-willdooit** [odoo/odoo#1305]
Short description of the issue

8.0 

**_Steps to reproduce:**_
1. Create a blog post
2. Set background image
3. Save

**_Current behaviour:**_
Image does not appear to save. The cause is the line 179 in website_blog_templates.xml:  

`<div class="cover js_fullheight" id="title" t-attf-style="background-image: url(#{blog_post.background_image})" t-ignore="True">`

As you can see, it is trying to create a url using the field background_image, which is the binary representation of the image, not a url. 

**_Expected behavior:**_
The background image showing up.
Changing the line to the following corrects this bug.

`<div class="cover js_fullheight" id="title" t-attf-style="background-image:url(/website/image?field=background_image&amp;model=blog.post&amp;id=#{blog_post.id}) " t-ignore="True">`

**Comment by Yenthe666** [comment]
Hi @thomas-willdooit,

Thank you for your report.
This bug has been handled and fixed before but nobody ever closed this issue.
Closing this one. 😉 

Regards,
Yenthe
