### ISSUE TITLE
account_edi_ubl_cii: UBL Bis 3 add support Denmark

### ISSUE THREAD

**Issue by OriolMForgeFlow** [odoo/odoo#130519]
Denmark is comprised in the EAS list but is not currently supported in Odoo ('0184' - DIGSTORG).

Impacted versions: All

Current behavior: Not able to import/export invoices for Danish companies.

Expected behavior: Be able to import/export invoices for Danish companies.

**Comment by OriolMForgeFlow** [comment]
Hello, @JulienVR . I am unsure if you would be able to take a look at this matter. It appears to require similar attention as the work mentioned under reference https://github.com/odoo/odoo/pull/113410 .

**Comment by JulienVR** [comment]
Hello @OriolMForgeFlow. Actually the EAS code for Denmark was added in 16.3 but not backported (see https://github.com/odoo/odoo/commit/be00ef8e37445738684cebb8b25d4bf226ae8f41#diff-a7b4b3c8fc94f16935d43a6c299387c190865558f5c4caaa79ade26c77a0a216R55). The EAS code picked was "0198" and not "0184" (but in 16.3, it's only a default value and it can be changed manually). Would you now which one we should use ?

**Comment by OriolMForgeFlow** [comment]
Hello @JulienVR, thank you for your quick response.

I am not entirely certain, but I believe the EAS code for Denmark should be "0184". One example of a rule, for Peppol BIS 3.0 Billing, is to specify the schemeID as "0184" in certain cases (DK-R-014). You can find more details here: https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-peppol/DK-R-014/.

Would it be possible to backport these changes to version 16.0?

**Comment by JulienVR** [comment]
Hello @OriolMForgeFlow,
I just opened a PR in 14.0 and will fw-port it until master: https://github.com/odoo/odoo/pull/130564.
Thank you for letting us know !

**Comment by OriolMForgeFlow** [comment]
Thank you so much @JulienVR ! 🚀
