### ISSUE TITLE
Blank screen after login as Admin or Demo user, after building odoo 9.0 

### ISSUE THREAD

**Issue by ramganesh19** [odoo/odoo#13057]
Impacted versions: 9.0

Steps to reproduce: Follow Source install instruction from https://www.odoo.com/documentation/9.0/setup/install.html#setup-install-source for windows platform
at the last step to "Running Odoo"

python odoo.py -w odoo -r odoo --addons-path=addons,../mymodules --db-filter=mydb$

I want to try the POS app and test it.

Current behavior:
Received error message
odoo.py: error: option --addons-path: no such directory: '../mymodules'

Expected behavior:
odoo to start without error
Removed mymodules from the addon path and odoo was started. 
type http://localhost:8069 and logged in as both administrator as well as demo user. Couldn't find any app and attached blank screen is what all I got

Video/Screenshot link (optional):

![odoo demo user blank screen](https://cloud.githubusercontent.com/assets/12521269/17472118/b497c124-5d51-11e6-91aa-abbdd6f9a772.png)

**Comment by treviser** [comment]
The documentation says:

> Under Windows a typical way to execute odoo would be:
> 
> C:\YourOdooPath> python odoo.py -w odoo -r odoo --addons-path=addons,../mymodules --db-filter=mydb$
> 
> Where odoo, odoo are the postgresql login and password, ../mymodules a directory with additional addons and mydb the default db to serve on localhost:8069

So check and make sure:
- you are on the proper Odoo path when invoking Odoo: "C:\YourOdooPath", otherwise you have to specify the full path to Odoo's and your addons folders
- "../mymodules" is a placeholder for your actual location of your addons modules (if the directory does not exist, create it first).

**Comment by lukebranch** [comment]
@ramganesh19 ,

Do you have any community modules (ie. not written by Odoo SA) in your addons_path?

Sometimes if there's a community module not functioning as it should you'll see this kind of issue.

Try looking at the following URL on that machine and you should be able to see the interface in debug mode:

http://localhost:8069/web?debug

If it's a community module causing the issue you'll need to find it and either fix it or remove it from the addons_path.

**Comment by tomaspworld2017** [comment]
The answer is here https://github.com/odoo/odoo/issues/14581#issuecomment-329473903

**Comment by Yenthe666** [comment]
As there has been no feedback on all the suggested answers and questions I'm closing this one. Thanks for all the answers and suggestions guys!
