### ISSUE TITLE
Employee Appraisal

### ISSUE THREAD

**Issue by chinesteves** [odoo/odoo#13058]
Impacted versions: 9.0

Hi,
I would just like to ask if Employee Appraisal is already available in version 9. In version 8.0 there's a module named 'hr_evaluation' which I can't find in v9. I already googled it but I can't find one.

Hoping for your positive response.
Thanks

**Comment by jni-odoo** [comment]
It is there in the enterprise version , not in the community version..

module name is hr_appraisal..


Thanks

Nikunj Jani (Odoo India)

**Comment by chinesteves** [comment]
I tried cloning it using this command "sudo git clone --depth 1 --branch 9.0 https://github.com/odoo/enterprise /odoo/enterprise/addons". But, it seems like repository doesn't exist anymore.

It says "fatal: repository 'https://github.com/odoo/enterprise/' not found"

**Comment by dreispt** [comment]
@chinesteves You need a valid Enterprise contract before you can do that 😉

**Comment by dreispt** [comment]
@chinesteves The 8.0 module can be ported to 9.0. You can consider hiring a developer for that, or sponsoring an OCA migration team to do it.

**Comment by chinesteves** [comment]
Thanks @dreispt  for the info

**Comment by dreispt** [comment]
🎯 For the record, work: has been started to port the 8.0 module to 9.0:
https://github.com/OCA/hr/pull/345
