### ISSUE TITLE
Downloaded modules not shown up at the apps list.

### ISSUE THREAD

**Issue by v3ss0n** [odoo/odoo#13052]
I downloaded United Backend Admin modules and added to all addon folders but it is not appearing in  module install interface of apps.

How do to it?

odoo 9.0 nightly build.
python odoo.py --addons-path=addons

**Comment by Yenthe666** [comment]
Hi @v3ss0n,

Thanks a lot for your report but Github issues are only for bugs in the official code, not for unofficial modules.
You should go to settings and click on 'Update modules list' and then search for the module again.
If you are still stuck please post a question on the official help forum (help.odoo.com) and I'm sure somebody else can help you there!

Regards,
Yenthe

**Comment by v3ss0n** [comment]
I can't ask question there because of Karma thats why i came here.
Found out the way to do :
it have to enable Developermode from About page.

**Comment by treviser** [comment]
@v3ss0n If you validate your email address you get enough karma to post a question.
