### ISSUE TITLE
[14.0] - Wrong field / value in rule domain_force

### ISSUE THREAD

**Issue by patrickt-oforce** [odoo/odoo#130563]
The field / value `company_ids` used in this [rule domain](https://github.com/odoo/odoo/blob/8b5e693757fd72af90bd62cbf6ae75149907984b/odoo/addons/base/security/base_security.xml#L23) is not present in `res.partner` model; and when this rule is evaluated raise following execption:
```
  File "/opt/odoo/odoo/odoo/tools/safe_eval.py", line 347, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'NameError'>: "name 'company_ids' is not defined" while evaluating
```

I found this rule in 16.0 and as for 14.0 the field / value company_ids is not present in `res.partner`

**Comment by SirTakobi** [comment]
The `domain_force` of `ir.rule` is evaluated in https://github.com/odoo/odoo/blob/06a8c5264eb6e87c29ad1d23a14e12dd45aa281c/odoo/addons/base/models/ir_rule.py#L148 the values available for the evaluation are defined in https://github.com/odoo/odoo/blob/06a8c5264eb6e87c29ad1d23a14e12dd45aa281c/odoo/addons/base/models/ir_rule.py#L44-L58
there you can see that `company_ids` actually comes from `self.env.companies` so it is always there.

From the exception stack I can see that `safe_eval` is being used but it is not clear _where_ it is being used.
How do you know it came from `base.res_partner_rule`?
Maybe `safe_eval` is being used somewhere where `company_ids` is not passed to `safe_eval`.

What are the steps that led you to this error?
Are you able to reproduce this error in runbot?

**Comment by patrickt-oforce** [comment]
@SirTakobi this error came up when import an xml of e-invoice; i've discovered it during porting of your PR #3100 in OCA/l10n-italy and the exception is thrown when load xml file and the system try to find the partner associated with that xml. The safe_evale is used in method `get_partner_domains_by_vat_fc`
The snippet of code where safe_eval is used is here:
```python
        if att and res_partner_rule and res_partner_rule.active:
            partner_rule_domain = res_partner_rule.domain_force
            partner_rule_domain = partner_rule_domain.replace(
                'user.company_id', 'company_id',
            )
            partner_rule_domain = safe_eval(
                partner_rule_domain,
                locals_dict={
                    'company_id': att.company_id,
                },
            )
```

**Comment by SirTakobi** [comment]
Looks like something that has to be fixed in that migration then, not in `odoo` itself.
I'd start with populating `locals_dict` with `self.env['ir.rule']._eval_context()` and maybe substituting its `company_id[s]` values with `att.company_id.id[s]`

**Comment by patrickt-oforce** [comment]
> Looks like something that has to be fixed in that migration then, not in `odoo` itself. I'd start with populating `locals_dict` with `self.env['ir.rule']._eval_context()` and maybe substituting its `company_id[s]` values with `att.company_id.id[s]`

Thank you for suggestion, i'll try this way
