### ISSUE TITLE
(9.0) Leave Request (hr_holidays) number of days calculation wrong

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#13062]
Impacted versions: 9.0 - 10.0

Steps to reproduce: Modify date_from or date_to in Leave Request form (hr_holidays.edit_holiday_new) and watch the field days (number_of_days_temp) 

Current behavior: The days on leave (number_of_days_temp) is not correct calculated according the Working Time (calendar_id) and the timezone

Expected behavior: The days of leave must take account the timezone and the employees Working Time

Video/Screenshot link (optional):

**Comment by bst-odoo** [comment]
Having "The days of leave must take account the timezone and the employees Working Time" is a new feature that has been implemented later.
