### ISSUE TITLE
Update Product Type/Stock Valuation for multiple products

### ISSUE THREAD

**Issue by gwasky** [odoo/odoo#13065]
Impacted versions:
8
Steps to reproduce:
Multiple update

Current behavior:
Manual update
Expected behavior:
All products are set to the default "Consumable" Product type as i imported these from a a different application.
Because of my automated stock valuation needs, i need to have the product type set to "Stockable Product"
I have 1000+ products, cant do this manually, have looked through the DB cant find which field to update for both.

Any ideas how i can mass update both :
Product Type 
Inventory Valuation 

Video/Screenshot link (optional):

**Comment by gwasky** [comment]
Found Product Type in the Product_Template table

**Comment by Yenthe666** [comment]
Hi @gwasky,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
