### ISSUE TITLE
[8.0][9.0] IMP to the new api: Remove automatically the _id or _ids from the label of the relational fields without the attribute string

### ISSUE THREAD

**Issue by KarenKawaii** [odoo/odoo#13068]
**Impacted versions: 8.0 and 9.0 (new api)**

**Steps to reproduce:**

Considering the documentation, examples and the [guideline] (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#field) for the [relational fields] (https://www.odoo.com/documentation/8.0/howtos/backend.html#relational-fields)
e.g.
If I have a Many2one field (following the example in open-academy module):

```python
    responsible_id = fields.Many2one('res.users',
        ondelete='set null', string="Responsible", index=True)
```
Is necessary the use of the attribute `string` to set the label of the field in the UI like "Responsible".

Now imagine that I add a new field like the above called `new_responsible_id` but without the attribute `string`:

```python
    new_responsible_id = fields.Many2one('res.users',
        ondelete='set null', index=True)
```

**Current behavior:**

In the UI the label says `New responsible id`

![responsible_id_new_responsible_id](https://cloud.githubusercontent.com/assets/11741384/17502404/35d3a78e-5dad-11e6-8a4e-bde6b8787c9f.png)

**Expected behavior:**

So, why not consider to remove the `_id` and `_ids` from the label of this kind of fields automatically, leaving the possibility of using the following code, without `string`:

```python
    responsible_id = fields.Many2one('res.users',
        ondelete='set null', st, index=True)
```

It will be a nice behaviour in the new api :) .

**Comment by moylop260** [comment]
I have a PR to fix it
https://github.com/odoo/odoo/pull/12769

**Comment by intero-chz** [comment]
What about the translations? Would there be translations for those fields?

**Comment by rco-odoo** [comment]
Sorry, this is not a bug.
This may not be changed on a [stable version](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).
