### ISSUE TITLE
Inverse methods not called in NewId records

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#13076]
Impacted versions: 9

Steps to reproduce:

Create a field with an inverse record, such as:

```
class BugTest(models.Model):
    _name = "bug.test"
    something = fields.Char(compute="_compute_something", inverse="_inverse_something")
    something_else = fields.Char()

    @api.multi
    @api.depends("something_else")
    def _compute_something(self):
        for s in self:
            s.something = s.something_else

    @api.multi
    def _inverse_something(self):
        for s in self:
            s.something_else = s.something

    @api.model
    def _test_inverse_new(self):
        a = self.new({"something": "Will you find me?"})
        if a.something != a.something_else:
            raise ValidationError("Bugged!")
```

Now execute the `_test_inverse_new` method.

Current behavior: Bugged!

Expected behavior: Should not raise an exception.

@Tecnativa @pedrobaeza

**Comment by pedrobaeza** [comment]
@rco-odoo can you please check this one?

**Comment by pedrobaeza** [comment]
@Yajo, maybe you can build a test that exercises this bug as well as the other PR.

**Comment by pedrobaeza** [comment]
Is this still applying, @Yajo?

**Comment by Yajo** [comment]
I guess yes. The workarounds are [still there](https://github.com/OCA/server-tools/blob/ea10cd17e32c5e843f1c1c20ff7a097f4f04c1b5/base_custom_info/models/custom_info.py#L63-L65). Since I still haven't migrated that addon to v10/11, I can't say if it's fixed there, but I guess not, since this one is still open...

**Comment by pedrobaeza** [comment]
@Yajo I have now understood that this is the intended behavior, as inverse are only called on write/create when dumping to DB due to their possible code inside the inverse method. Check #23891 for more details.

The workaround you mention is actually the way to get the inverse calculations done on new (only if these inverse methods modify fields from the same model).
