### ISSUE TITLE
many2onebutton in list view does not differentiate

### ISSUE THREAD

**Issue by boolit-eivydas** [odoo/odoo#13099]
**Impacted versions:**
8.0 for sure
**Steps to reproduce:**
Create a list view with a one2many field having `widget="one2manybutton"`.
**Current behavior:**
Regardless of the line having a record in the one2many field, the circle is green.
**Expected behavior:**
Circle is green when there are records in one2many field, red when not.

There might be a bug in `view_list.js#2380`:
`this.has_value = !!row_data[this.id].value;`

In JS (Chrome 52 console):
`![] == false` and `!![] == true`. 
`![1] == false` and `!![1] == true`. There is no difference whether there are elements in the array or not.

Suggestion to use this:
`this.has_value = row_data[this.id].value.length > 0;`

**Comment by Yenthe666** [comment]
Hi @boolit-eivydas,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
