### ISSUE TITLE
incorrect translation breaks functionality of printing delivery slips

### ISSUE THREAD

**Issue by jerzyk** [odoo/odoo#131013]
Impacted versions:
16.0

Steps to reproduce:
switch to polish (pl) locale
try to print Delivery Slip

Current behavior:
crash

Expected behavior:
prints document

problem is that someone translated keyword "or" to "lub" in addons/stock/i18n/pl.po line 224 in translated text

**Comment by jerzyk** [comment]
updated translation on transifex

**Comment by vava-odoo** [comment]
Hi @jerzyk 
Thanks for reporting and fixing it on transifex. Is it ok now?
Cheers

**Comment by jerzyk** [comment]
working for R14 and R16, R15 still has an error

**Comment by mateusz-leja** [comment]
This kind of problems is related to all polish translation. There are more errors in the code. It is unusable. I thought that I can just repair some email templates, but the problem is so big that even the button on event website isn't working.
Full revision of polish translation is urgently needed.

**Comment by mateusz-leja** [comment]
Not just logic operators like "or" to "lub" was translated but even fields like "object.user_id.company_id.website" to "object.user_id.company_id.strona WWW".

**Comment by jerzyk** [comment]
> Not just logic operators like "or" to "lub" was translated but even fields like "object.user_id.company_id.website" to "object.user_id.company_id.strona WWW".

point me to the wring translations - so I'll update them on transifex

**Comment by mart-e** [comment]
Fixed at https://github.com/odoo/odoo/commit/182a98d5a98380754de7d67741149f37bd10259a#diff-41c884bcada8f0a3853da73cc1c09cc5da4d495260a7b0e6dabe1ed917969b61R257
