### ISSUE TITLE
[8.0] Product variants: price increments of variants aren't added 

### ISSUE THREAD

**Issue by wtebbens** [odoo/odoo#1310]
I've defined a product with a number of variants with their individual price increments. However, these price increments don't show up when adding the variant to a Sales Order. 

In the Products > Product Variants list view all variants show up with the same base price, so not adding the price increments for the attributes.

(Also in the product view on the variants tab for variants prices there are no price values shown)

This is on an instance cloned from v8.

**Comment by Yenthe666** [comment]
Hi @wtebbens,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
