### ISSUE TITLE
summernote  editor can not paste pic

### ISSUE THREAD

**Issue by ethanleellj** [odoo/odoo#13119]
Impacted versions:odoo-9.0c-20160811

Steps to reproduce: while edit task detail , on Description , paste pic from picture tool, then save. but pic is does saved.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by qsm-odoo** [comment]
Hello,
I tried on current 9.0c version and the version you mentioned but I was not able to reproduce the problem. Is this still an issue on your side ?
