### ISSUE TITLE
Incorrect State Code for KwaZulu-Natal

### ISSUE THREAD

**Issue by Row042** [odoo/odoo#131211]
**Incorrect State Code for KwaZulu-Natal**

The correct ISO 3166 code for KwaZulu-Natal is "KZN"

Impacted versions:
 
 - 16.0

Current behaviour:
 
 - State Code: NL
 
Expected behaviour:
 
 - State Code: KZN

https://github.com/odoo/odoo/blob/eda483bd3c3bdc42b95f17a5278c1a9eb83adb05/odoo/addons/base/data/res.country.state.csv?plain=1#L301

**Comment by WonderM** [comment]
Hi.

Also, in line 300: state_za_gt,za,"Gauteng","GT" is incorrect

it should be
state_za_gp,za,"Gauteng","GP"

**Comment by vava-odoo** [comment]
Hi @Row042 and @WonderM 
Looks like typos, indeed. Could you create a PR targeting 14.0? (If it is your first contribution, please follow [the steps here](https://www.odoo.com/documentation/master/contributing/development.html#make-your-first-contribution).
Thanks!

**Comment by vava-odoo** [comment]
Hi @Row042 
I saw that you tried a PR but closed it for an unknown reason, so I decided to do it myself. So it is corrected in all supported versions (>= 15.0).
Cheers

**Comment by Row042** [comment]
Thanks, I did try but I haven’t got the hang of git yet and when it looked like I was making this worse I closed it to be safe.

 

Kind Regards

 

Roland van Eeden – Director

Easy Ascent (PTY) Ltd

 ***@***.***> ***@***.***

+27646592800
