### ISSUE TITLE
Odoo Server Error! DataError: invalid input syntax for integer: ""

### ISSUE THREAD

**Issue by Peis7** [odoo/odoo#13123]
**Impacted versions:**
     Im using odoo 8

**Current behavio**r:
   Every time i validate an invoice, or use account_voucher module, this error mesagge is Show, but    after clicking in Ok button to close this error message, everything else we expected to happend works fine,  i mean, journal items are created if needed, invoices states change, clients and supplier  invoices get pay in vouchers module, but this message error still appears.

Dont know whats going on.
    We Expect everything works good as alway!
   Seems to be something in odoo, because if you look at the end of the screenshot, in a query it tries to compare **id** field with other fields value, like name; and this value seems to be different in each module, sometimes  just empty string and sometimes another char fields value. I've Update my odoo but nothing happend!
![captura de pantalla de 2016-08-11 17 07 30](https://cloud.githubusercontent.com/assets/17111559/17607900/1f3a29cc-5fe6-11e6-8786-c5be424f5977.png)

![captura de pantalla de 2016-08-11 16 59 56](https://cloud.githubusercontent.com/assets/17111559/17607777/2cd4ba44-5fe5-11e6-82d0-ccebcfc0ca41.png)
 odoo.
Video/Screenshot link (optional):
![captura de pantalla de 2016-08-11 16 49 32](https://cloud.githubusercontent.com/assets/17111559/17607568/c253b0d6-5fe3-11e6-8c4e-4f0d8f794da0.png)
![captura de pantalla de 2016-08-11 16 50 10](https://cloud.githubusercontent.com/assets/17111559/17607569/c2550c42-5fe3-11e6-807a-b2245de7d750.png)

**Comment by Yenthe666** [comment]
Hi @Peis7,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
