### ISSUE TITLE
how could i add this code into saleline order ?

### ISSUE THREAD

**Issue by tuananhphucthanh** [odoo/odoo#13124]
hello everyone,  im new on odoo and would like  to add a feature that support for particular business issue. could you guy please help me to add this filed to the class SaleLine that will be showed as following part:

    @api.depends('lng', 'quantity_extra')   
    @api.multi
           def _compute_product_uom_qty(self):    
                                      for line in self:                 line.quantity_sum = line.lng * line.quantity_extra

and this is the part of file sale.py of my module

class SaleLine(models.Model):

    _inherit = "sale.order.line"

    width_id = fields.Many2one('sale.order.line.width', u'Kiểu tính')
    lng = fields.Float(u'Dài', default=1)
    formula = fields.Char(compute='_get_formula', string=u'Công thức')
    unit_id = fields.Many2one('product.uom', string=u'Đơn vị')
    quantity_extra = fields.Float(u'Tấm', default=1)
    quantity_sum = fields.Float(compute='_compute_quantity', string=u'Số lượng mở rộng', store=True)
    is_copy = fields.Boolean('Is Copy')
    
    @api.depends('width_id', 'lng', 'quantity_extra')
    @api.multi
    def _compute_quantity(self):
        for line in self:
            if line.width_id:
                line.quantity_sum = line.lng * line.width_id.rate * line.quantity_extra

**Comment by lukebranch** [comment]
@tuananhphucthanh ,

The odoo issues are for reporting bugs and issues with the core code. I am only another odoo user like yourself, however i'd suggest asking this question on the community mailing list:

https://www.odoo.com/groups

as well as the community forum here:

https://www.odoo.com/forum/help-1

I'd suggest closing this issue and asking your question in one or both of those places, as you will likely get some great feedback from other community members on your question in those two places.

**Comment by tuananhphucthanh** [comment]
i got it thank for replying. closed

**Comment by tuananhphucthanh** [comment]
i got it thank for replying. closed
