### ISSUE TITLE
how to build a mobile app?

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#13130]
9.0 enterprises

i see module"project_timesheet_synchro" unpack to  a mobile app(android,iOS ect) by cordova.
but i can't search any document for build a app.
i want to know how to unpack to a mobile app by cordova.

**Comment by dreispt** [comment]
I don't see that module in the Odoo codebase.
Can you share a pointer?

**Comment by sum1201** [comment]
it's in 9.0 enterprises ,not in community.

**Comment by sle-odoo** [comment]
there are two bash scripts at the root of the addons, @tac-odoo may help you more.
however i'm closing this as it is not an issue.
