### ISSUE TITLE
Navigation through next/previous Tasks can cause accidental Stage changes

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#13136]
### Impacted versions:

master, 9.0, 8.0
### Steps to reproduce:

Open the Project Tasks in form view.
Make your browser window sufficiently smaller in width, and edit the Task tile making large enough so that it doesn't fit in the available width.
Navigate to  the Next task, and the back to the original one.

![2016-08-12 14_26_24-internal testing software install - odoo - firefox developer edition](https://cloud.githubusercontent.com/assets/1246629/17623854/1e5f430c-609a-11e6-8433-248efb2f2504.png)
### Current behavior:

Your mouse pointer could now be over the States widget, and a second click on the same place can cause the Stage to be (accidentally) changed, causing much pain, grief, and dead kittens.

![2016-08-12 14_26_59-c__users_danielgr_downloads_2016-08-12 14_14_50-amazon odoo essentials at duckdu](https://cloud.githubusercontent.com/assets/1246629/17623899/4a3fe562-609a-11e6-914f-2d835b2445ae.png)
### Expected behavior:

Keep the Previous/Next record navigation buttons on the same position, regardless of the length of the current document's title.
### Video/Screenshot link (optional):

Screenshots above were taken from Runbot using the default demo data.

**Comment by dreispt** [comment]
Ping!

**Comment by JKE-be** [comment]
Hello @dreispt 

What is your expected behavior if breadcrumb become very long... Customer / Sale / Partner / contacts / my very long name .... ?
The desired behavior (actually) is to be displayed on several lines...

What are you suggest to keep this behavior and avoid your problem ?
It seems to be more a problem of usability that a issue really ...

@bst-odoo An idea ?

**Comment by bst-odoo** [comment]
We will improve the breadcrumb in the short term. We will take this remark into account. Thank you.

**Comment by dreispt** [comment]
There are several ways to tackle this problem: 
a) Use ellipsis to keep the breadcrumb to a single line. I agree that this is not the best solution.
b) CSS your way so that the record nav buttons are in a fixed position, even if the breadcrumb grows to 2 or more lines. Probably this would the the ideal solution.

Also nice to have is to add shortcut keys for the next/previous actions (please please!... 🙏 ).

**Comment by bst-odoo** [comment]
alt-n (next record) and alt-p (previous record) have been implemented for Saas12 :)

**Comment by dreispt** [comment]
@bst-odoo Thanks. I must admit I'm quite lost regarding on saas versions: saas-12 is not in v9 but will be in v10, right?

**Comment by bst-odoo** [comment]
Yes indeed, it will be in V10 :)

**Comment by Yenthe666** [comment]
@dreispt think we could close this one?

**Comment by dreispt** [comment]
@Yenthe666 We have a workaround for 10, but I feel that it is not a fix.

Can R&D comment on my two suggested solutions? If not a technical challenge, b) would be a great solution.

**Comment by Yenthe666** [comment]
@mart-e and @antonylesuisse  can you give your input here?

**Comment by mart-e** [comment]
I tend to see CSS as a mystical way to fix all the layout isses ([mandatory commitstrip](http://www.commitstrip.com/en/2016/10/10/a-story-about-css-units/)).
We should make sure the switcher always stays on the same place but there is also the problem of a too long breadcrumb, even on short names (a max depth for the new breadcrumb? cc @bst-odoo )

![screenshot from 2016-10-12 09-27-16](https://cloud.githubusercontent.com/assets/564822/19301120/1719c754-905e-11e6-8124-658c843dc36b.png)

**Comment by dreispt** [comment]
@mart-e CSS is also like an ancient rune-like language for me, but can't the nav buttons be in a floating DIV, positioned at the top right corner of the content area? 
With that the breadcrumb could grow as much as you like, since the the nav button would be sticked to the top right corner regardeless of their size.

**Comment by Yenthe666** [comment]
@mart-e any update on this one or are we closing it? I believe this is better in new versions.

**Comment by dreispt** [comment]
Not perfect, but it is much improved in v11.
