### ISSUE TITLE
date and time widget - RTL

### ISSUE THREAD

**Issue by hedshefer** [odoo/odoo#131398]
Impacted versions:
16.0
Steps to reproduce and current behavior:
When we switch the user language from English to Hebrew, a right-to-left language, the orientation of the date and time widget in the attendance list is also reversed (the hours appear on the right instead of the left).
Please note that the clock itself does not need to change its direction.

Expected behavior:
The time in the clock should be from left to right same as it's appear in the english language.
Video/Screenshot link (optional):
https://watch.screencastify.com/v/NF9eUN2fytGuVIxmSNIR
Support ticket number submitted via odoo.com/help (optional):
3410503

**Comment by hedshefer** [comment]
@mart-e Can you have a look on that issue?

**Comment by niyasraphy** [comment]
@hedshefer may related to this:   https://github.com/odoo/odoo/pull/130636

**Comment by hedshefer** [comment]
Thanks @niyasraphy 
merged also in V16?

**Comment by niyasraphy** [comment]
@hedshefer once it is merged in 15.0 and if the issue persists in higher versions, it will be forwarded to higher versions.

**Comment by vava-odoo** [comment]
Solved in 15.0 with https://github.com/odoo/odoo/pull/130636, and forward-port up to master.
Thanks @hedshefer for reporting!

**Comment by hedshefer** [comment]
@vava-odoo Great, Thanks!
