### ISSUE TITLE
customers.xls not found

### ISSUE THREAD

**Issue by katelynsills** [odoo/odoo#13140]
Impacted versions: 9.0

Steps to reproduce: Begin the Inventory tutorial. On step two, click the link "Download the Excel template". The relative url for this link is "base_import/static/csv/customers.xls", which returns a 404. 

Current behavior: 404 not found

Expected behavior: an excel template for customer imports. 

Video/Screenshot link (optional):

**Comment by bistaray** [comment]
Unable to replicate on http://165911-9-0-c8331c.runbot.odoo.com/

1. Begin the Inventory Tutorial.
2. Click "Your Vendors"
3. Click "Excel Template"

customers.xls is downloaded

If you have your own installation, perhaps there are some other issues?

**Comment by hendysg** [comment]
I bumped into the exact same issue as @katelynsills 

I deployed Version 9.0c-20160620 (Community Edition) on [Google Cloud using Bitnami](https://console.cloud.google.com/launcher/details/bitnami-launchpad/odoo)

**Comment by urquilla** [comment]
+1
Same issue here with odoo from docker image v9.

Loaded with demo data and just the inventory installed.

Clicked the link on the implementation assistant for inventory at "Plantilla Excel"
![Uploading odoo.png…]()

**Comment by captnbp** [comment]
+1, same issue with Odoo9 and Odoo10 from Docker images.

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one?

**Comment by sle-odoo** [comment]
@Yenthe666 the [MANIFEST.in](https://github.com/odoo/odoo/blob/9.0/MANIFEST.in) is just missing a ```recursive-include openerp *.xls```. I'll fix this soon.

**Comment by Yenthe666** [comment]
@sle-odoo I made a PR to fix this in 9.0, so it can also be forwarded to 10.0
See https://github.com/odoo/odoo/pull/14558

**Comment by sle-odoo** [comment]
fixed in 4aed1e1747591a2218005837f99b2cf8d8e21343
thanks for the reporting *and* the fix :)
