### ISSUE TITLE
Can't override web.TreeView

### ISSUE THREAD

**Issue by mdwatkins** [odoo/odoo#13141]
**Impacted versions:** 9

**Steps to reproduce:** 

When I try to create an instance of TreeView, the program hangs. I'm using the following code:

```
openerp.foo = function(instance){

var QWeb = openerp.web.qweb;
    _t = instance.web._t;

    var bar = instance.web.TreeView.include({
        // do something 
    });
};
```

**Current behavior:**

I can put anything inside the curly brackets and it hangs. 

It's just TreeView that causes problems. I can change it to ListView, ViewManager or anything else and it works just fine.

**Error in the JS console:**

`web.assets_common.js:2523 error: Some modules could not be started `

**Expected behavior:**

The module overrides web.TreeView

Video/Screenshot link (optional):

**Comment by aab-odoo** [comment]
Hello,

Even if it doesn't seem to be the origin of your problem, the use of `openerp` has been deprecated in 9.0. A [JS module system](https://www.odoo.com/documentation/9.0/reference/javascript.html#javascript-module-system-overview) has been introduced instead. Here is the way to include a widget:

```
odoo.define("web_custom.TreeView", function (require) {
"use strict";

var TreeView = require("web.TreeView");

TreeView.include({
     // do something 
});

});
```
Regards
