### ISSUE TITLE
Enabling of Paypal not possible. View Error

### ISSUE THREAD

**Issue by Stephan-ch** [odoo/odoo#13145]
Impacted versions: 9.0

Steps to reproduce: Enable Paypal -> Error 500 after adress input in cart

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://www.odoo.com/forum/help-1/question/paypal-enable-causes-error-500-cart-106891

**Comment by JKE-be** [comment]
Hello,
Like already discuss in the forum, from what i see in the traceback, it's like if the template for your paypal button has no xml_id. Can you check it ? 
![image](https://cloud.githubusercontent.com/assets/4848797/17649116/3569eb72-622c-11e6-8058-81a443f2b04f.png)
![image](https://cloud.githubusercontent.com/assets/4848797/17649119/49fbf5c6-622c-11e6-943a-63048c07b1b8.png)


If you go in the payment acquirer, you can the the view name for the button. 
Then go in settings / technical user / User interface / views ... search the view (filter top right), then click on the checkbox -> more -> export... That will generate a external id (xml_id) '\_\_export\_\_.xxx'.

**Comment by Stephan-ch** [comment]
Hi

Thanks for your help. Here is the export file


Cheers

Stephan


Am 14.08.2016 um 14:36 schrieb JKE-be:

**Comment by JKE-be** [comment]
can you reproduce this bug on last runbot ?

**Comment by Stephan-ch** [comment]
Hi

Solved the problem. It was a view error. The paypal button was linked to a non existing view, but a second view with the same name existed. Deactivated the "unknown" view and the paypal button worked.
