### ISSUE TITLE
[9.0]Creating invoice fail when multiple property_account_receivable_id available in DB

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#13148]
Impacted versions: 9

Steps to reproduce:
Create multiple customers/suppliers with dedicated account_id so that you'lll have multiple property_account_receivable_id with different res_id in the ir_property

Current behavior:
fail because multiple values are returned here : https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L473

Expected behavior:
A single propery should be returned with the one by default.

**Comment by flotho** [comment]
Here is my patch proposal :
```

--- a/addons/account/models/account_invoice.py
+++ b/addons/account/models/account_invoice.py
@@ -469,8 +469,9 @@
                     rec_dom = [('name', '=', 'property_account_receivable_id'), ('company_id', '=', company_id)]
                     pay_dom = [('name', '=', 'property_account_payable_id'), ('company_id', '=', company_id)]
                     res_dom = [('res_id', '=', 'res.partner,%s' % partner_id)]
-                    rec_prop = prop.search(rec_dom + res_dom) or prop.search(rec_dom)
-                    pay_prop = prop.search(pay_dom + res_dom) or prop.search(pay_dom)
+                    res_dom_empty = [('res_id', '=', False)]                    
+                    rec_prop = prop.search(rec_dom + res_dom) or prop.search(rec_dom + res_dom_empty)
+                    pay_prop = prop.search(pay_dom + res_dom) or prop.search(pay_dom + res_dom_empty)
                     rec_account = rec_prop.get_by_record(rec_prop)
                     pay_account = pay_prop.get_by_record(pay_prop)
                     if not rec_account and not pay_account:```

```

**Comment by flotho** [comment]
Hi @sle-odoo , any chance to be read on this ?

**Comment by Yenthe666** [comment]
@sle-odoo did you ever get around to this?

**Comment by sle-odoo** [comment]
nope, ping @csnauwaert

**Comment by csnauwaert** [comment]
Hello,

Seems to me that this commit might solve the issue: https://github.com/odoo/odoo/commit/ebf3b3d7a8b807ef3ad8aa50217f110001fcebfa

Therefore I'm closing this issue, feel free to reopen it if you still have the problem.

Best regards
