### ISSUE TITLE
[Translation] .po files not updated with the latest source strings

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#13149]
Impacted versions:
At least 9.0 (probably all)

Steps to reproduce:
N/A

Current behavior:
.po files do not seem to be updated when source strings are changed in Odoo.

For example, this commit https://github.com/odoo/odoo/commit/901a3e030c4b11a219abf391839a471025bab4b3 has changed `Generate Single Accounting Entry` to `Generate Accounting Entries`.
![image](https://cloud.githubusercontent.com/assets/7766939/17662830/f9467a4e-631a-11e6-915f-50a2821c682f.png)

But the old string `Generate Single Accounting Entry` still persists in .po file.
![image](https://cloud.githubusercontent.com/assets/7766939/17662762/8fa68ebc-631a-11e6-9149-a6ea7f39b7ae.png)

And the new string `Generate Accounting Entries` cannot be found.

Expected behavior:
When the source string is changed in Odoo code, it should be reflected in .po files.

**Comment by yostashiro** [comment]
@mart-e can you please take a look.

**Comment by fenshuajiang** [comment]
You should export pot file through the web interface，and update the items of the po file with this pot file.

**Comment by yostashiro** [comment]
@fenshuajiang this is not the kind of issue that should be fixed locally.  I think all the .po and .pot files should be updated automatically when there is any change to the master term, or it won't be covered by Transifex.

**Comment by yostashiro** [comment]
Another example - `Less Cost of Revenue` in COA.

Odoo screen:
![image](https://cloud.githubusercontent.com/assets/7766939/17727866/98d249ca-648e-11e6-99bf-d0e9a3bd8f24.png)

Transifex for "Less Cost of Revenue":
![image](https://cloud.githubusercontent.com/assets/7766939/17727885/ba79e79a-648e-11e6-941f-f26a7172538b.png)

Commit https://github.com/odoo/odoo/commit/6f5acf6001d1c99e9eb1f2eef349149ff40656a0:
![image](https://cloud.githubusercontent.com/assets/7766939/17727929/f890ce4a-648e-11e6-9e1f-ab6905583448.png)

Transifex for "Less Cost of Sales":
![image](https://cloud.githubusercontent.com/assets/7766939/17727943/183302ae-648f-11e6-9eaa-c3ea881f9066.png)
