### ISSUE TITLE
[master][mrp] routing production location not create previous move for raw materials

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#13153]
Impacted versions:
master, saas-12

Steps to reproduce:

create database with demo data, install mrp application.

edit routing 'Assemble Furniture',   add  Production Location  as new stock location called '   WH/workshop'

create MO for 'Computer Desk', keep the raw materials location and finished product location, and then confirm the MO.

Current behavior:

production should consume raw materials from   'WH/workshop'.  this is right. 

operator should create picking from  'WH/Stock' to   'WH/workshop' manually, or create pull rule + op rule for  location   'WH/workshop'.

Expected behavior:

should  create picking from  'WH/Stock' to   'WH/workshop' automatically like odoo 8 & 9  doing now.

```
 def _create_previous_move(self, cr, uid, move_id, product, source_location_id, dest_location_id, context=None):
        '''
        When the routing gives a different location than the raw material location of the production order, 
        we should create an extra move from the raw material location to the location of the routing, which 
        precedes the consumption line (chained).  The picking type depends on the warehouse in which this happens
        and the type of locations. 
        '''
```

Video/Screenshot link (optional):

**Comment by jalzaga** [comment]
This issue is not solved yet in version 10. There is no creation of previous move from the raw material stock location  to the workshop location. This is very important when you subcontract an operation. You have to manually create a stock move to the supplier location.

**Comment by pedrobaeza** [comment]
Is this still happening in v11?
