### ISSUE TITLE
BUG in invoice report name

### ISSUE THREAD

**Issue by krupesh10** [odoo/odoo#13157]
Impacted versions:8.0

Steps to reproduce:Go to Customer Invoice, validate the invoice, Click on Send by Invoice button in that popup of mail send template you can see the extra underscore in the attachment name of report. 

Current behavior: Invoice_VK_2016_0004_.pdf

Expected behavior: Invoice_VK_2016_0004.pdf

Video/Screenshot link (optional):
![selection_010](https://cloud.githubusercontent.com/assets/21057089/17695830/01bcc6e4-63c8-11e6-8fd8-76bbd5dc40bc.png)

**Comment by Yenthe666** [comment]
@mart-e not a major improvement and it is rather usability wise, but I do agree that the "_" shouldn't be there.

**Comment by krupesh10** [comment]
@JKE-be @Yenthe666 @fpodoo These things always happen we are using report in any email template.

**Comment by Yenthe666** [comment]
Hi @krupesh10,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
