### ISSUE TITLE
Ignored values in email template

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#1315]
Impacted versions:
- 7.0 and above

Steps to reproduce:
- Context action added in email template
  ![templates openerp](https://cloud.githubusercontent.com/assets/7595505/3661282/18665dd6-11bf-11e4-8bf5-f348d00d69f7.png)
- Create a new sale order and execute wizard
  ![sales orders wizard template openerp](https://cloud.githubusercontent.com/assets/7595505/3661308/4aba0ec2-11bf-11e4-8867-889bc579fbe9.png)

Current behavior:
- Values like email_from or attachment are ignored
  ![sales orders wizard template send openerp](https://cloud.githubusercontent.com/assets/7595505/3661320/667ef906-11bf-11e4-87d2-d246f136afaf.png)

Expected behavior:
- should work like this:

![sales orders send by mail openerp](https://cloud.githubusercontent.com/assets/7595505/3661377/27151114-11c0-11e4-827b-22a658b5ac8d.png)
![sales orders send by email wizard openerp](https://cloud.githubusercontent.com/assets/7595505/3661385/2c28abfc-11c0-11e4-8877-0ba03c2c09ee.png)

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your report.
It looks like nobody has looked into this issue before but it shouldn't be here anymore in the newer versions (8.0, 9.0, 10.0).
Do feel free to create a new bug report if you can reproduce it in newer versions though!

Regards,
Yenthe
