### ISSUE TITLE
[IMP]SALES: only allow print confirmed orders.

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#131653]
What are the steps to reproduce your issue?
have installed the sales module, also have the option "Lock Confirmed Sales", create a sales quotation.

What is the current behavior that you observe?
the sales quotation its saved but it could be printed.

What would be your expected behavior in this case?

if the sales its a quotation you don't have the option to print, only can be printed if is confirmed.

Cause: some time the workers forget to confirm the sales order and print the quotation like an order.
also if the worker have bad practice can keep the money of this sales order. (stole).

The customer don't say nothing because have a printed sheet with the information of the sale.

**Comment by gdgellatly** [comment]
The idea that no company wants to print a quote is laughable. It is one of the most common workflows in the world. I think you would be much better off finding a partner, and paying for the customisations you want rather than polluting an issue tracker with things that aren't bugs.
