### ISSUE TITLE
[IMP] General: Odoo code

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#131647]
What are the steps to reproduce your issue?

Go to products, create a product, save.

What is the current behavior that you observe?

Odoo don't create a unique code for the product.

What would be your expected behavior in this case?

Odoo create a code for that product, apart from the internal reference.

This code need to be unique, so other product don't gonna have this code.

For example sap have this function:https://blogs.sap.com/2016/04/13/create-unique-and-consistent-codes-for-master-data-records/

In my case I need to remove from the printed order the internal reference to don't show it to the customers.

**Comment by dalaOdoo** [comment]
@chapital what would be the usage of this code exactly ? Why not using the "id" of the product ?

**Comment by gdgellatly** [comment]
He just wants a unique default code. Most of us just use the barcode reference, or a code generator. There are loads of free ones for Odoo, OCA product-attribute repo has 4 modules that approach this differently (sequential, formula, unique or not, etc). He just thinks SAP way is only way, not realising that most of us use Odoo precisely because it isn't like SAP and can choose how we make it work as we need.

**Comment by chapital** [comment]
Hi @dalaOdoo 

I put the sap as a sample only.

why do we need this and dont use id, internal reference o barcode:

we sell product in eccomerce, and we need to put a sku of the product, so we can use the Intel reference code but its not the best way to increase the sales, because a lot of please search product and then found the internal reference and buy this product in a local store or use the sku to find a better price of other vendor.

So we need only a unique code for our internal use, to avoid only use our eccomerce product like a catalog and the customer buy it in other part.

id its not visible in the product, and we use the internal reference field with the sku of the vendor, and we dont use the bar code because not all the products have bar code in our inventory.
