### ISSUE TITLE
[IMP]Accounting: payment date in invoice 

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#131641]
What are the steps to reproduce your issue?
Create and invoice with a vendor that have payment terms without discount.

What is the current behavior that you observe?

When we print the invoice only print the name of the payment terms, for example 30 days.

What would be your expected behavior in this case?

When we print the invoice print the name of the payment terms and also print the payment date for example: 30 days / pay until 09/09/2023

PD. the payment date only appear if I enable a discount, but not all the vendor offer discount, so if I put a fake 0.01% discount at 1 day, the payment date appear but appear 2 dates: 1.- the normal date of the payment and date of the payment with a fake discount.

This happen in purchase and sales invoices.

Its important to show the end date of the payment for my Odoo customers.

**Comment by vava-odoo** [comment]
Hi @chapital 

Just checked on [runbot](http://runbot.odoo.com/runbot), and the due date is displayed.

![image](https://github.com/odoo/odoo/assets/112173839/dda11a83-b2dc-4324-a8ae-ce29c830b212)

Cheers
