### ISSUE TITLE
PoS price for cashier

### ISSUE THREAD

**Issue by onorua** [odoo/odoo#13164]
Impacted versions: At least 9

Steps to reproduce: 
Login as non-admin user with PoS rights as "user" and "HR" and employee. When you open PoS GUI, the price of the product is taken from `base_price` while user is able to see the `cost` from the Products menu. 

Current behavior:
Currently in PoS products cashier can see `cost` price, but the product is selling by the `base_price`

Expected behavior:
I believe cashier should not know the price product was bought, but rather final cost which seems to be `base_price` or catalog price. Otherwise it is misleading and bad for the business.

**Comment by Gyuri77** [comment]
Inherit the current view to a new one, modify it for your taste, and use that on that menu.

**Comment by pedrobaeza** [comment]
This is something that can be customized on your end, but not a real issue, and thus I close it.
