### ISSUE TITLE
[IMP] Inventory: Auto process ready orders.

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#131648]
What are the steps to reproduce your issue?
Make a order and confirm it.

What is the current behavior that you observe?
To process the inventory need to do a lot of clicks, I know two ways to do this:
1.-After confirm the order, go to delivery, then assign quantity, then validate to process the inventory.
2.-Go to inventory module, then delivery orders, then select all the order that have the status ready, the click in action, then click validate.

What would be your expected behavior in this case?

When we make an order an confirm it and the product have stock, automatically validate this, this will automatically update product quantity of the product.

it could be enable in the warehouse configuration.

**Comment by chapital** [comment]
Hi @amoyaux, can you please validate this for future improvements.

this still the biggest challenge when we migrate to odoo, or if you have a solution to automate this will be perfect.

**Comment by amoyaux** [comment]
@thomasdeleval
