### ISSUE TITLE
[10.0] Compute sheet in payslip form issues

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#13168]
Impacted versions: 10.0

Steps to reproduce: Press compute button in hr_payroll.view_hr_payslip_form

Current behavior: 1) Worked Days won't be not updated after changing Period (date_from, date_to)

2) If there are Salary Rules defined as "Appears on Payslip = False", they won't be deleted after pressing compute button due to the function only delete the Rules defined as "Appears on Payslip = True".  The old lines remains in hr.payslip.line undeleted
Lines affected in hr_payroll.py
    line_ids = fields.One2many('hr.payslip.line', 'slip_id', string='Payslip Lines', readonly=True,
        states={'draft': [('readonly', False)]}, domain=[('appears_on_payslip', '=', True)])

In  def compute_sheet(self):
            payslip.line_ids.unlink()

Expected behavior:

Video/Screenshot link (optional):

**Comment by elperrofarelo** [comment]
Proposed solution:
Add following lines after:  payslip.line_ids.unlink()
old_slipline_ids = self.env['hr.payslip.line'].search([('slip_id', '=', payslip.id)])
 if old_slipline_ids:
          old_slipline_ids.unlink()

**Comment by pedrobaeza** [comment]
Please make a PR with the proposed code is this still applies.
