### ISSUE TITLE
wkhtmltopdf on Docked Odoo version 16 (Debian 10, Buster) result as "results timeout (504)"

### ISSUE THREAD

**Issue by gimlou** [odoo/odoo#131633]
### Impacted versions: 
Odoo 16.0-20230807 (Edition Community)
_Installed on Docker_
_Image_ : odoo:latest
_DB_ : postgres:latest

### Steps to reproduce: 
Generate a pdf

### Current behavior:
The process hangs and results with a timeout after long waiting time
```504
504 Gateway Time-out
                                    
The above server error caused the following client error:
RPC_ERROR: Arbitrary Uncaught Python Exception
    at makeErrorFromResponse (https://odoo.gimlou.fr/web/assets/159-989a0a2/web.assets_backend.min.js:985:163)
    at decoder.onload (https://odoo.gimlou.fr/web/assets/159-989a0a2/web.assets_backend.min.js:973:7)
```

I've manually remove **wkhtmltopdf** and reinstall version **0.12.6 (with patched qt)** with correct package.
**wkhtmltopdf** can be manually called in term, no error returning.

I can see the POST request :
```
2023-08-10 17:31:18,851 1 INFO USER werkzeug: XXX.XXX.XXX.XXX - - [10/Aug/2023 17:31:18] "POST /report/check_wkhtmltopdf HTTP/1.1" 200 - 1 0.001 0.005
```

And the wkhtmltopdf process launched with correct args in term.

If you've any idea of how to better debug nor save this issue,
Thanks in advance.

### Expected behavior: 
Generate PDF

**Comment by mfarahats** [comment]
I have the same problem. Have you found a solution?

**Comment by vava-odoo** [comment]
@sleepy-monax Could you have a look here?

**Comment by sleepy-monax** [comment]
This is commonly caused by large HTML documents being processed by wkhtml2pdf. You can try the nightly version [1], which includes some resource usage improvements. Or backport this hack [2] from odoo 17 onto your database.

[1] https://github.com/odoo/wkhtmltopdf/releases/tag/nightly
[2] https://github.com/odoo/odoo/pull/131933

**Comment by gimlou** [comment]
Actually I've done something quite simple : 
 - Activate Dev-Mode
 - Go to System - > Technical -> System Param
 - Change your web.base.url, mine was http://, switched to https:// and works like a charm.

**Comment by gimlou** [comment]
> This is commonly caused by large HTML documents being processed by wkhtml2pdf. You can try the nightly version [1], which includes some resource usage improvements. Or backport this hack [2] from odoo 17 onto your database.
> 
> [1] https://github.com/odoo/wkhtmltopdf/releases/tag/nightly [2] #131933

Thanks for the help !
