### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by lucasrabelo** [odoo/odoo#13165]
Impacted versions: 8.0

Steps to reproduce: Create a quotation, press print, a pdf file starts to dowload. This file is not possible to to opened

Current behavior: it is impossible to open the file

Expected behavior:the file should open

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @lucasrabelo,

I've just tested this on the latest Odoo 8.0 (runbot.odoo.com) and this works fine.
Can you test this on a runbot again please? In case you face this problem locally make sure that you've got the latest Odoo version and that you've got a PDF reader installed.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @lucasrabelo,

Since I can not reproduce this issue anymore and there has been no response since august I'm closing this issue.
If it is still reproducable or if you have a problem just post a message on this again and I'll have a look at it again!

Regards,
Yenthe
