### ISSUE TITLE
Security alert: Data is not deleted

### ISSUE THREAD

**Issue by smileBeda** [odoo/odoo#131658]
Lol guys.

I played around on a free testing account. I got tired and deleted all setup databases, companies. I finally deleted my own account.
I then navigated (after success full deletion) to the url that Odoo had assigned me. And I was back in. Could see all users, databases, companies. And the user is marked as "deleted user". But I am in as that user!!
<img width="1792" alt="Screenshot 2023-08-11 at 13 16 01" src="https://github.com/odoo/odoo/assets/11800236/091eb483-fd79-4a5a-917f-4d198da440a1">

I am shocked. And I think 99% this is not something I can use. How could something that says it deleted your user, but then still lets you see that data of the supposedly deleted user and company and database... no, this seems _extremely_ unsafe!

And even after deleting other users, and this database, and my own account... the domain odoo had assigned me still exists!
Meaning they retain the data, indefinitely!? Comon!

**Comment by mart-e** [comment]
Hi,

I see you have opened this issue github just right after (minutes) the request for deletion. Once you request the deletion, it still takes some time for the request to be processed and effectively remove the databases. If you check them now, they are no longer present.

You can check [our Data Retention policy](https://www.odoo.com/privacy#part_11) for more details on what and how long we keep it.
