### ISSUE TITLE
Losing module subcategories in left frame

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#1317]
- While using Master, commit 869b647, the left frame is losing module selections after applying a change. Info: Ubuntu 14.04, Chrome Version 36.0.1985.125.

**_Impacted versions:**_
 8.0rc1

**_Steps to reproduce:**_
1. Choose Settings
2. Choose module subcategory on left
3. Select and Apply new setting(s)

**_Current behavior:**_
- After new selection apply finishes, left frame loses all module selections and just allows 'Edit Company Data'

![image](https://cloud.githubusercontent.com/assets/8029250/3662651/42c532a2-11cc-11e4-9b19-614a13e858ff.png)

**_Expected behavior:**_
To be able to select more subcategories for continued settings modification.
![image](https://cloud.githubusercontent.com/assets/8029250/3662871/ec265c44-11cd-11e4-8f6d-2483fd5bf211.png)

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your report.
This bug cannot be reproduced anymore and has probably been fixed ages ago, just nobody closed it.
Closing as this is no longer the case.

Regards,
Yenthe
