### ISSUE TITLE
Error after confirm a payment with checks

### ISSUE THREAD

**Issue by pablohmontenegro** [odoo/odoo#131757]
Impacted versions: 16.0

**Steps to reproduce**:

1) Go to runbot Odoo 16 enterprise and install "l10n_latam_check" module (Third Party and Deferred/Electronic Checks Management).

2) Create a journal on "Accounting / Configuration / Accounting / Journals" with type "Cash", add "New Third Party Checks" payment method on "Incoming Payments", set "Short Code" and save.

3) Create a new payment on "Accounting / Customers / Payments", select a customer, set an amount higher than 0.00, select the journal created on step 2, select payment method "
New Third Party Checks", set "Check Number" **with letters** for example "dfg", set Check Cash In date the same date you are creating the payment. Confirm the payment.

4) Select "Bank" journal on "Accounting / Configuration / Accounting / Journals" and set "Use electronic and deferred checks" on "Outgoing Payments".

5) Create a new payment on "Accounting / Vendors / Payments". Select a vendor, set the same amount as step 3, set Date with the same date you are creating the payment. Select "Bank" journal (the same as step 4). Select Payment Method "Checks". Set Check Number with numbers for example "123", set "Check Cash-In Date" with the same date you are creating the payment.

6) Confirm the payment.

**Current behavior:**
After confirm the payment on step 6 there is a bug with traceback.

**Expected behavior:**
After confirm the payment on step 6 there is not a bug.

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/1zqthmkJZIa7zvG8actKAcvhSL2n7UZH4/view

**Bug traceback**
https://gist.github.com/pablohmontenegro/7b71ce8143dd84bc8b10d386566c2837

Support ticket number submitted via odoo.com/help (optional):
https://www.odoo.com/es_ES/my/tasks/3464012

**Comment by pablohmontenegro** [comment]
@vava-odoo @mehjabinfarsana hi! do you have news about this issue? thanks!

**Comment by pablohmontenegro** [comment]
@vbe-odoo hi Valen, could you please check if this pr solves this issue https://github.com/odoo/odoo/pull/137890? thanks!

**Comment by vbe-odoo** [comment]
> @vbe-odoo hi Valen, could you please check if this pr solves this issue #137890? thanks!

Hey @pablohmontenegro I've done a FUN test and it works. Feel free if you want to do a test on your end.
I left my comment on the PR.
Thanks!

**Comment by vava-odoo** [comment]
Thanks @pablohmontenegro for reporting it. Solved with https://github.com/odoo/odoo/pull/137890
