### ISSUE TITLE
Bug in Product in Sales 

### ISSUE THREAD

**Issue by SarathkumarJ** [odoo/odoo#13185]
Impacted versions: Enterprise edition Released today 

Steps to reproduce: Open Sales Dashboard > Product 

Current behavior: Showing Sales dash board on background , the buttons in Dashboard weary and whole page looks bad 
![products - odoo 2016-08-17 16-39-05](https://cloud.githubusercontent.com/assets/10898379/17734402/a1a7b5f2-6499-11e6-9cdf-e9c7805ffafa.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @SarathkumarJ,

I've just tested this on the latest Odoo 9 Enterprise and I can no longer produce this issue.
Can you test it again on the latest runbots please?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no response and as this was fixed.
