### ISSUE TITLE
Version Key should be unique, because of duplication migration is not be called.

### ISSUE THREAD

**Issue by agent-z28** [odoo/odoo#131854]
https://github.com/odoo/odoo/blob/88cb916c9f303dd2beb34b35362b9a70a9ea7c98/addons/l10n_de/__manifest__.py#L8

**Comment by niyasraphy** [comment]
https://github.com/odoo/odoo/pull/132219

**Comment by vava-odoo** [comment]
Thanks @agent-z28 for reporting.
Solved with https://github.com/odoo/odoo/pull/132219
