### ISSUE TITLE
[16.0][BUG] Error occurs when selecting sub field during export

### ISSUE THREAD

**Issue by kanda999** [odoo/odoo#131976]
Impacted versions: 
16.0
Steps to reproduce:
1, Open the export wizard
2, Open a sub field of a field (eg. Account Paytable)
![2023-08-15_12h13_59](https://github.com/odoo/odoo/assets/101688144/d0fe065f-8797-4d2b-a65c-92481ad8bdef)
3, Enable the I want to update data (import-compatible export)
4, Open a sub field of the same field that was open before enable import-compatible export opiton. (eg. Account Paytable)
![2023-08-15_12h14_49](https://github.com/odoo/odoo/assets/101688144/59b188c9-6293-4d0a-b9ac-c45617a88f16)
5, Client error occurs.
![2023-08-15_12h15_03](https://github.com/odoo/odoo/assets/101688144/f3cc797d-813e-44d2-8eec-3e04f07700a9)

Expected behavior:
Subfields can be opened without error.

Support ticket number submitted via odoo.com/help (optional):
OPW: #3466865

@qrtl

**Comment by BastienFafchamps** [comment]
Fixed in https://github.com/odoo/odoo/pull/145901 :thumbsup:

**Comment by kanda999** [comment]
@BastienFafchamps Thank you very much, I hope it will be merged to the `16.0`.
