### ISSUE TITLE
[14.0] Blank sceen after login in server 

### ISSUE THREAD

**Issue by erlan1234** [odoo/odoo#131977]
Impacted versions:
14.0

Steps to reproduce:
1. login user dan password
2. odoo will show blank page
![Screenshot from 2023-08-15 14-12-17](https://github.com/odoo/odoo/assets/30716872/455889cb-7740-4a6e-84a1-1ed966c4c2fe)
Current behavior:

Expected behavior:
show view of my menu not blank page

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @erlan1234 ,
i believe this is not a bug to report and more of a configuration issue.
feel free to use official forums in such cases: https://www.odoo.com/forum/help-1

thanks
