### ISSUE TITLE
How to get change product quantity?

### ISSUE THREAD

**Issue by Ramil001** [odoo/odoo#131962]
Odoo v16
How can I programmatically track the change in the quantity  in  product and output to the log.
I need to track any change in the number of products, and update it on the API of another system, how can I catch this event?

**Comment by niyasraphy** [comment]
hi @Ramil001 ,
this issue tracker is to track issues inside Odoo. for such questions, feel free to use forums:  https://www.odoo.com/forum/help-1

thanks
