### ISSUE TITLE
Custom css to the template

### ISSUE THREAD

**Issue by soxepo** [odoo/odoo#13197]
Impacted versions: 8

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Hey!
I have install odoo 8 and try to develop the themes. But have some problem :
i have been install eCommerce plugin and try to change some style - but my style is connected before the plugin style. What i do wrong?

Here is how I connect styles my style to the template
http://codepen.io/anon/pen/jAJjAp

(sorry for my bad english)

**Comment by JKE-be** [comment]
"but my style is connected before the plugin style." ???

Please use forum for this kind of question...
https://help.odoo.com

This tracker is for bug only

**Comment by soxepo** [comment]
Thx ))

**Comment by JKE-be** [comment]
but what do you means by "but my style is connected before the plugin style."

if you inspect source, your link is at right place ? 
If no, you can change the sequence/priority of your view... to interprete the xpath later

If it is in the right place... be sure that no override css with !important even in previous file.

**Comment by soxepo** [comment]
no, my style connected before eCommerce style
i have something similar to http://imgur.com/a/H4ug5
my openerp.py  http://imgur.com/a/QLGls
and my style do not want to work without !important 

I just learn odoo and in docs i could not find anything ((

**Comment by JKE-be** [comment]
If you depend of website_sale... you can add 'website_sale' in depend of openerp.py

![image](https://cloud.githubusercontent.com/assets/4848797/17806212/7cb4b400-6603-11e6-96b0-35a9c4795d71.png)

That can impact the order ...

Else add a priority to be apply later ... with

&lt;template id="mystyle" name="My style" inherit_id="website.assets_frontend" **priority="100"**>

**Comment by soxepo** [comment]
Thats it - THANKS!!)))
Its work))
