### ISSUE TITLE
SVGs not completely usable as company logos

### ISSUE THREAD

**Issue by LinuxSpielKind** [odoo/odoo#132057]
Impacted versions: 16.0

Steps to reproduce:  Upload a SVG picture as a company logo via the settings dialog.

Current behavior: The preview of the logo is not shown at all and the icons for editing and deleting move to the upper right corner of the dialog. When using a document preview in web mode (non PDF) the the logo is shown correctly. All PDF renderings a missing the logo.
Workaround: Use a non SVG picture as logo, e.g. PNG.

Expected behavior: Logo is shown correctly in settings dialog with a predefined height. All PDF renderings (invoices, etc.) show the company logo as expected.

Video/Screenshot link (optional): [https://nextcloud.dc-ing.de/s/ZRCtyDqQEB6dfyP](https://nextcloud.dc-ing.de/s/ZRCtyDqQEB6dfyP)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
wkhtmltopdf doesn't render all existing SVGs. Try to simplify it to see if it's able to render it. But the limitation is on the library used for rendering PDFs. While this doesn't change, there's nothing to do.

**Comment by vava-odoo** [comment]
Hi @LinuxSpielKind 
Thanks for reporting, but as @pedrobaeza explained, this is a known issue, not related to Odoo standard.
