### ISSUE TITLE
[master] login takes all users to website no matter if they have a different home action

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13203]
Impacted versions:
master

**Steps to reproduce:**
1. Activate developer mode
2. Create a new user: test
3. Set user's HR group to Employee, set user's Sales group to: manager
4. Set user's Home Action to: Discussions
5. Set user's password
6. Logout and login with new user.

**Current behavior:**
After user is logged, is sent directly to the website `/`

**Expected behavior:**
Like in previous versions: 8.0, 9.0; user should be sent to `/web` and automatically open discussions (because it belongs to `base.group_user` and has a Home Action defined)

**Possible reasons:**
Here: https://github.com/odoo/odoo/blob/master/addons/website/controllers/main.py#L85 is being used `has_group` method on `env.user` which is `public` and not the user trying to log in.

**Comment by aristobulo-eezee** [comment]
@dreispt you were talking about this, maybe you want to take a look.

**Comment by antonylesuisse** [comment]
Yes it's regression due to the new api conversion.

**Comment by aristobulo-eezee** [comment]
FYI: @antonybrugger @eezeefho

**Comment by mart-e** [comment]
Fixed at 814eae1fbd27aad056694b2c303dca398025f39d, thank you for the report
