### ISSUE TITLE
[9.0] HR Manager should have visibility of everyone's PaySlips

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#13211]
Impacted versions:
9.0c/e

Steps to reproduce:
Create a user who has the highest HR level of permissions (Manager).  (though in US English, generally an Officer is higher than Manager)

Current behavior:
This user will not be able to see other employee's Payslips (to approve).  (unless they are the manager of the department of the user, but the same would be true for the Officer Level).

Expected behavior:
There should be a way for a user (Officer) to be able to see their direct subordinates Payslips to approve, but there should be some sort of 'Payroll Admin' kind of level that can see all Payslips for filling out reports/forms and stepping in to correct errors or approvals.

**Comment by dreispt** [comment]
AFAICT "HR Officer" is someone working at an HR Department, and frequently would have access to all Payslips. "HR Manager" is an HR Department user with setup permissions.
Both of these are different from an "Employee Manager" role, that does not exist explicitly in Odoo.

**Comment by jaredkipe** [comment]
Its a bit confusing.  The dropdown options mappings to groups goes:

"Employee" -> base.group_user
-> the user will be able to manage his own HR stuff like leave requests, timesheet...

"Office" -> base.group_hr_user
-> the user will be able to approve document created by employees.
^ this is where the current domain to be able to see other employees payslips only if they are the manager of the department the employee is in.

"Manager" -> base.group_hr_manager
-> the user will have an access to the human resources configuration as well as statistic reports.
^ is a 'group_hr_user' so they pickup the same domain filter

This leaves hole where you cannot have someone who processes payroll for a whole company.

**Comment by beledouxdenis** [comment]
Dear,

Such a change of behavior cannot happen in a stable release:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Indeed, users might be used to the current behavior and expect it. Suddenly changing the access rules without warning is not tolerated, as it might obviously upset users that are used to this behavior, and rely on it.

This can be considered as a change for master, but not for a stable release such as 9.0.

You can apply this record rule manually in your database if this is the internal policy of your company.

I hope you will understand.
