### ISSUE TITLE
[10.0 enterprise master] Bank Statement Reconciliation problem with Batch Deposit

### ISSUE THREAD

**Issue by hieubloopark** [odoo/odoo#13216]
**Impacted versions:** Odoo 8, 9, master

**Steps to reproduce and Current behavior:**
(For screenshots, see my blog post at the end of this page)
- Step 1: create 2 Sales Order, generate 2 Customer Invoices and validate them.
- Step 2: receive customer checks by manually creating a Payment and confirm it.
_One important note here is that if I register payment on the Invoice with Payment Method Type ‘Batch Deposit’, the Journal Items will be auto reconciled immediately although Odoo said that payments can be registered from the menu Sales > Payments, or directly on the related invoice, using the Register Payment button. Maybe this is a bug. This is not what I am expecting that I will reconcile it later with Bank Statement. So, I will create a Payment manually._ 
- Step 3: prepare a Batch Deposit
From the Accounting application, go to the menu Sales > Batch Deposit, and create a new Batch Deposit.
- Step 4: reconcile the Deposit with the Bank Statement
When reconciling, the Batch Deposit is suggested based on the Reference DEPOSIT/2016/0001 I put in the Bank Statement. I select it and click Reconcile and close the statement.

_The Journal Items should be reconciled. But it was strange that they were not, and the Journal Items that should have been generated for the Bank Statement were not there. Maybe because this is not the final release of Odoo 10, it is still buggy?_

**Expected behavior:**
I think it should be something like this
![image](https://cloud.githubusercontent.com/assets/20577945/17801745/396b2326-65ec-11e6-9395-e952ca93cda2.png)

**Video/Screenshot link:**
Please see my article about it here, chapter E_xample (2) matched with a previously recorded payment_
https://docs.google.com/document/d/1RgEIL54lGwIjmHonTl-tw56UJoUsOAqaOXKJ1Z2qedc/edit?usp=sharing

**Comment by Yenthe666** [comment]
Hi @hieubloopark,

Thanks a lot for your report! Do notice that reports against V10 (which is actually the master and not stable yet) aren't really adviced. The Odoo environments change quite often and fast in this stage, which causes these kind of issues.
@qdp-odoo could you have a look at this though?

**Comment by jholze** [comment]
@hieubloopark @Yenthe666 this also occurs as i know in 8 and 9.

**Comment by hieubloopark** [comment]
hi @Yenthe666 @qdp-odoo thanks for your prompt response!
in version 8, I am also facing a similar issue. At the beginning I thought the cause is from here [[8.0] l10n_de: why bank account allows reconciliation?](https://github.com/odoo/odoo/issues/13036)

but it's not. sometimes the Accountants click on button OK, sometimes, they use the hotkey Ctrl+Enter to reconcile batch records. The issue is that Journal Items were generated but NOT reconciled (missing Reconcile Ref). This does not happens all the time. I cannot reproduce it.

**Comment by Yenthe666** [comment]
Alright good to know! Then is is a great issue report, thanks guys.
@mart-e putting you in CC here too.

**Comment by qdp-odoo** [comment]
what you described is actually not a bug, it is the exact intended behavior. 

* You must register payments on the invoices by click on 'register payment' button, otherwise if you create manually the payment, as in your use case, it won't be linked to the invoice and won't be reconciled with it... sounds quite logical, isn't it?

* Secondly, when you select a batch deposit in the bank statement reconciliation widget it will select only already validated payments (already posted in the accounting), you can notice it because the payment lines are blue, so at that time the system must not create new accounting entries or you'll end up with the same payment counted twice in your accounting.... 

* Finally, the behavior you're talking about is when you use clearing accounts to hold the temporary operations out of the bank account until you receive the money. This is something we can also do, but there's no real need since that is the reason of being of the blue lines in the bank statement reconciliation widget. You could acheive that, though, but it looks a bit sub-optimal to me.

**Comment by hieubloopark** [comment]
@qdp-odoo thanks for your explanation.

1. indeed, it's correct if I register payment on the Invoice form. But I think Odoo should update the documentation [How to manage batch deposits of checks?](https://www.odoo.com/documentation/user/9.0/accounting/bank/misc/batch.html), in chapter Receive customer checks, they created a Payment manually, and said that 'payments can be registered from the menu Sales ‣ Payments, or directly on the related invoice, using the Register Payment button.'
2. Can you please have a look at  [[8.0] l10n_de: why bank account allows reconciliation?](https://github.com/odoo/odoo/issues/13036) I think it's wrong configuration for Accounts with type 'Liquidity' (bank, cash)
3. Do you have any idea about the issue that sometimes when doing the Bank Statement Reconciliation (click button OK, or use Ctrl+Enter), Journal Items were generated but NOT reconciled (missing Reconcile Ref). My client is currently facing this problem in Odoo version 8. Maybe I will create another issue for this.

**Comment by qdp-odoo** [comment]
1. documentation is not wrong: you can encode payments separately but in that case it's normal it's not related to any invoice (like a prepayment or an payment for an invoice you don't have encoded yet or you don't know the reference...)

2. commented on that same issue

3. No idea, but yes it's better to create a new issue and give a use case to reproduce it.

Thanks for your contribution

**Comment by hieubloopark** [comment]
it's clear now, thanks for your explanation
