### ISSUE TITLE
Skills resume date validation not working

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#132158]
Impacted versions:
Odoo 16
Steps to reproduce:
Install hr_skills module
Current behavior:
https://github.com/odoo/odoo/blob/16.0/addons/hr_skills/data/hr.resume.line.csv
End date will after start date not before start date

Expected behavior:
Start date and End date validation will work, but currently not working

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by ppr-odoo** [comment]
Hello @prakashjain  

For your information 
We fixed this issue this PR- https://github.com/odoo/odoo/pull/127351

cc @sofiagvaladze 
thanks

**Comment by vava-odoo** [comment]
Hi @prakashjain 
Thanks for reporting. The issue has been solved in all LTS versions, including 16.
Cheers
