### ISSUE TITLE
access values of one2many fields on kanban view odoo 0.8.

### ISSUE THREAD

**Issue by mostafaic** [odoo/odoo#13224]
Why i can't access values of one2many field on kanabn view Odoo 8 i need to loop over them to access them but it only return the number of records that's it.
`<t t-foreach="o2m_field" t-as"record">
    <t t-esc="record.name"/>
</t>`

**Comment by dreispt** [comment]
That snippet should work. 
In fact there are standard kanbans using that to display a list of follower avatars. 
Check project Tasks.

**Comment by mostafaic** [comment]
template['kanban-box']: No enumerator given to foreach
THAT'S WHAT I GOT using this structure.
`<kanban>
                    <templates>
                        <t t-name="kanban-box">`

**Comment by mostafaic** [comment]
It's Done and fixed now. issue closed

**Comment by asctarek** [comment]
inherit from the origin kanban view and set 
          <xpath expr="//templates" position="before">
                <field name="o2m_field"/>
            </xpath>
then you can do 
    <t t-foreach="o2m_field" t-as"record"> <t t-esc="record.name"/> </t>

**Comment by asctarek** [comment]
<xpath expr="//templates" position="before">
                <field name="sector_ids"/>
            </xpath>

**Comment by asctarek** [comment]
<xpath expr="//templates" position="before"><field name="o2m_field"/></xpath>
