### ISSUE TITLE
Creation of product variant overrides values of template

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#13229]
Impacted versions: 9.0

Steps to reproduce:

On runbot.odoo.com:

Preparation:
- Go to Sales > Products
- Create a product with a `name` "Warranty"
- Untick the `sale_ok` ("Can be Sold") checkbox (which defaults to True)
- Change the `type` to "Product" (which defaults to Consumable)
- In the Variants tab, add the "Duration" attribute with the values "1 year" and "2 years"
- Save. You should have 2 variants

Reproduce the issue:
- On the new "Warranty" product,  click on the smart button which shows "2 variants"
- Click on create to manually create a new variant
- Set the name to "3 years" (field is empty, shouldn't it be the name of the template?)
- Set an attribute (not important)
- Save the variant

Current behavior:
- The name of the template is now "3 years"
- The `sale_ok` field has been reset to True
- The `type` field has been reset to Consumable

Expected behavior:
- The name of the template should still be "Warranty"
- The `sale_ok` field does not change
- The `type` field does not change

Analysis:

When a new variant is created, the `product_tmpl_id` field is not in the view, so the `name` cannot be initialized with the template's name. 
The `product_tmpl_id` field is then not in the `vals` of the `ProductProduct.create` method, but in the context, in the `default_product_tmpl_id` key, which is added in the `vals`, with the side effect that all the other values of the product template are forced to their default value.

The default values issue can be prevented with the following code in the `create` method of `ProductProduct`:

``` python
        if self.env.context.get('default_product_tmpl_id'):
            vals['product_tmpl_id'] = self.env.context['default_product_tmpl_id']
```

But I have no clue how you'd want to fix the name issue, as I don't get why we have to fill this field on a variant.

**Comment by guewen** [comment]
On a side note, the 2 lines of code I wrote above is a quick fix which prevent one of the issue for the particular case of the product variants, but the same issue might appear on any model and is related to the following lines: https://github.com/odoo/odoo/blob/ea4e4e3eac7cda0ab5c0027204af1a23bd790831/openerp/models.py#L1338-L1340

**Comment by nim-odoo** [comment]
At a first glance, your fix seems ok. I'll test it more deeply to make sure it doesn't cause any trouble.

Regarding the name, it doesn't look that weird to keep it empty, and leave it to the user. Usually, you don't create a variant directly: you just add an attribute value at the level of the product template, and the variant is created automatically. When you create the variant manually, you might want to set specific information on it.

Finally, about the more general behavior, I will leave it to @rco-odoo .

**Comment by pedrobaeza** [comment]
This seems to be fixed on the linked PR, so I close. If this is not case, please comment.
