### ISSUE TITLE
[9.0/master] web and website_slides have different maximum upload size

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13223]
**Impacted versions:**
- 9.0
- master

**Steps to reproduce:**
1. Create a new odoo instance, install `website_slides`

**Current behavior:**
If you go to any record allowing internal notes (or send mail as well) you are able to upload files up to 25 Mb (https://github.com/odoo/odoo/blob/master/addons/web/static/src/js/views/form_widgets.js#L1062), but at when trying to upload new pdf slide the limit is set to 15 Mb (https://github.com/odoo/odoo/blob/9.0/addons/website_slides/controllers/main.py#L298).

**Expected behavior:**
At least to have the same behavior on both sides, if back-end uses size limit at 25 Mb, front-end should use the same limit.

Besides the fact of this limits being hard-coded at different places (Js and Python controller), could we have the same limits all around?

**To consider:**
Do you think it could be feasible for upcoming releases to move this limit to `fields.Binary` class by adding an attribute `size_limit` set by default to `25` ?

_E.g.  Declaring a Binary field with 50Mb file size limit_
`user_guide = fields.Binary('User Guide', size_limit=50)`

What do you think @odony  @antonylesuisse ?

**Comment by antonylesuisse** [comment]
Yes it should be consistent, change slides to allow 25MB

**Comment by aristobulo-eezee** [comment]
FYI @antonybrugger @eezeefho

**Comment by JKE-be** [comment]
Limit for website_slide will be updated to 25Mo.

But I tag **wishlist** for the `To consider:` part !

**Comment by aristobulo-eezee** [comment]
@JKE-be we are going to need this fix very soon, I already made a PR with it. Could you please check it? Also, could you not label it as wishlist. Somehow (IMO) @antonylesuisse confirmed that it should be consistent with `web`

**Comment by JKE-be** [comment]
@aristobulo-eezee 

Thanks for the PR

about tag:
> But I tag wishlist for the To consider: part !

**Comment by aristobulo-eezee** [comment]
@JKE-be yes, I missed your tag explanation the first time, sorry about that.

**Comment by aristobulo-eezee** [comment]
@JKE-be can you re-open this one please, as it's back after https://github.com/odoo/odoo/commit/402379a48a31bc486145e81d8dae2910ae446b48

**Comment by Yenthe666** [comment]
@JKE-be this should be fixed now as the limit is removed in the other parts too.

**Comment by seancallahan88** [comment]
Just checked: the error message displays a warning for 25MB (for slides) but the pdf being uploaded is only 20MB.

Using V10e

**Comment by pedrobaeza** [comment]
As this is now something you can define as a parameter, this shouldn't be stay opened. About the real limit, it depends on header overhead and the compute about 1024 multiple instead of 1000.
