### ISSUE TITLE
Recalculates the data even though I have the attribute store = True [Many2One - Related]

### ISSUE THREAD

**Issue by sagastume** [odoo/odoo#13231]
**Impacted versions:** 9.0c

**Steps to reproduce:**

`class fleet_travel(models.Model):`

`vehicle = fields.Many2one(string="Vehiculo", comodel_name='fleet.vehicle', store=True)`
`driver_id = fields.Many2one(string="Piloto", related='vehicle.driver_id', store=True)`

**Current behavior:**
Not save the driver data when the attribute store exists. Recalculates the driver always should not recalculate.

**Expected behavior:**
You should store the data without recalculating the driver when there is a change in vehicle because the attribute store exists as true.

**Comment by pedrobaeza** [comment]
Recomputes are triggered for keeping the better consistency. Maybe there are some duplicates computation, but the goal is that one. This has been improved any way version per version. I invite you to check on latest version to see.
