### ISSUE TITLE
Export for grouped entries not exporting ONLY selected items

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#13233]
Impacted versions: 9.0e

Steps to reproduce: Accounting>Adviser>Journal Entries>Group by "month"> select 1 month worth of items>export

Current behavior:
exports all transactions, not just selected ones
Expected behavior:
Exports selected items
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,

Can you confirm that you have uncheck / rechecked one checkbox visible from the 'group by' result.

The first time that you click on the 'select all', it select all the record resulting from your search.
![image](https://cloud.githubusercontent.com/assets/4848797/17847195/06c88f0e-684d-11e6-80f8-179cfdcc3539.png)

If you want just select all the visible result, you need to uncheck one visible checkbox from the list to specify that you don't want really ALL the results, but all visibles, and recheck it to get it in the export.

Can you confirm that it works for you.
I have just tested on last runbot 9e and it works for me...

**Comment by JKE-be** [comment]
I close, don't hesitate to comment and re-open if you can reproduce
