### ISSUE TITLE
Filter by date not working in Journal Entries Odoo 9e

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#13232]
Impacted versions:9.0e

Steps to reproduce:
Accounting>adviser>journal entries>Filter by "date greater than 1/1/16, less than 1/31/16"
Current behavior:
Does not only show requested filter range
Expected behavior:
Showing all entries
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,

Can you give more info about your context and how to reproduce it? 

I have just retested now, on last runbot 9e and it works :/

**BEFORE FILTER**
![image](https://cloud.githubusercontent.com/assets/4848797/17847367/e8d18e0a-684d-11e6-9f85-578132f431cf.png)



**AFTER FILTER**
![image](https://cloud.githubusercontent.com/assets/4848797/17847353/d5d6a268-684d-11e6-94ad-c4d68617d576.png)

**Comment by JKE-be** [comment]
I close, don't hesitate to comment and re-open if you can reproduce
