### ISSUE TITLE
[8.0] Bank Statement not reconciled

### ISSUE THREAD

**Issue by hieubloopark** [odoo/odoo#13240]
**Impacted versions:** 8.0

**Steps to reproduce & Current behavior:**
- step 1: import a bank statement file. on the reconciliation form, click button OK to reconcile one by one OR use Ctrl+Enter to reconcile multi records
<img width="1267" alt="step1 1_import_bank_statement" src="https://cloud.githubusercontent.com/assets/20577945/17846776/a343e548-684a-11e6-92b5-2b4504bf8295.png">

- step 2: check the Journal Items after the import was done
<img width="1173" alt="step1 2_import_done" src="https://cloud.githubusercontent.com/assets/20577945/17846888/6a130096-684b-11e6-909b-180fdd5c735e.png">

sometimes, somehow, there are several Journal Items were NOT reconciled (missing Reconcile Ref)
![step2 1_missing_recicile_ref](https://cloud.githubusercontent.com/assets/20577945/17846891/6ea28d7a-684b-11e6-9053-401bbae6e07b.png)

- step 3: the Accountants had to manually do the reconciliation for those items
<img width="1290" alt="step2 2_manually_reconciliation" src="https://cloud.githubusercontent.com/assets/20577945/17846940/b3de2ef8-684b-11e6-8001-a1a981cf5cd3.png">

**Expected behavior:**
ALL balanced Journal Items should be reconciled using the Reconciliation feature in Bank Statement.

Do you have any idea why it sometimes happened?

**Comment by hieubloopark** [comment]
@qdp-odoo @Yenthe666 @kaerdsar can you please have a look?

**Comment by Yenthe666** [comment]
I've got to pass for this one, haven't worked with it personally so I'll leave this one for @qdp-odoo and @mart-e  :smile:

**Comment by qdp-odoo** [comment]
**ultra short version:** I don't see any bug in the description.

**short an almost accurate version:** 'reconcile ref' is only filled when the line is reconciled with an existing invoice/entry on a receivable/payable account... 

long version: maybe the naming of the bank statement 'reconciliation process' is unfortunate but it's not the same as depicted by the 'reconcile ref' field. The first could be replaced by 'bank statement processing', and the second with "common reference written on all the lines that cancel each other completly". So, you'd understand easily that while doing a bank statement reconciliation, you will create some 'reconcile ref' when you pay entirely invoices (for example) but won't when you register bank fees or whatsoever...

Hoping this is more clear now, I'm closing the bug

Thanks

**Comment by hieubloopark** [comment]
@qdp-odoo in the description, **'sometimes, somehow, there are several Journal Items were NOT reconciled (missing Reconcile Ref)'**. in the screenshot, I highlighted with the question mark where the Reconcile Ref was missing, compared to other similar lines having Reconcile Ref. That's a bug I think. And in my case, those are lines being reconciled with an existing invoice/entry on a receivable/payable account.
Thank you anyway, a dev in my company is still working on fixing the bug.

**Comment by qdp-odoo** [comment]
ok then let me suggest another possibility: the payment is not exactly equal to the remaining amount on the invoice? 

My use cases: 
1) invoice of 100€, payment of 50€ on it
2) invoice of 50€, payment of 100€ on it
Those won't create a reconcile ref, because they don't totally cancel each other (the invoice in (1) and the payment in (2) are still open), which is totally normal.

If it's not that then I dunno ^^

**Comment by hieubloopark** [comment]
@qdp-odoo yeah that's also I case. :) My case is to use Bank Statements to make full payment for the Invoice in status Open (validated, and not paid yet).
