### ISSUE TITLE
[9.0] Payment term is not propagated from Purchase Order to Supplier Invoice

### ISSUE THREAD

**Issue by mdietrichc2c** [odoo/odoo#13249]
Impacted versions: 9.0

Steps to reproduce:
1) create a PO with a supplier, which has no supplier payment term set,
2) add a payment term to the PO,
3) create the invoice from the PO.

Current behavior:
The payment term is not present on the supplier invoice (or, if it is present on the supplier, this one will be selected).

Expected behavior:
Same payment term between PO and supplier invoice (it can be modified in the PO before creating the invoice).

Video/Screenshot link (optional):

**Comment by bistaray** [comment]
Was able to replicate this via http://167994-9-0-c578fb.runbot.odoo.com/web/login

1. Create a PO for "China Export" (this Vendor has no Payment Term set).
2. Add Payment Term "30 Net Days" to PO.
3. Validate.  Receive Products.
4. Create Invoice.  

Observed:
* Due Date is False. 
* Payment Term is invisible on Form view (because it also is False).

**Comment by Yenthe666** [comment]
Hi guys,

I've just tested this and the due date is indeed not set through this flow.
@sle-odoo this is still the case - can you change it?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@sle-odoo yes it does. The final call for this is up to you. If you don't wish to fix it then we should close it. I don't see an issue in adding/fixing this though?

**Comment by sle-odoo** [comment]
I prefer to wait for an official ticket. Even simple changes could broke other stuff users are really relying on. Hope you understand.

**Comment by Yenthe666** [comment]
Okay. @bistaray or @mdietrichc2c if you have an enterprise license and want to get it fixed then please make an official ticket at odoo.com/help referring to this bug report.
