### ISSUE TITLE
[16.0][IMP] account_payment: create payment with amount equal 0

### ISSUE THREAD

**Issue by ngochung207** [odoo/odoo#132450]
Impacted versions:
Should the system block the creation of zero-value transactions?

![image](https://github.com/odoo/odoo/assets/11542778/e6b34525-17dd-4942-95eb-a7cfc8d79f2a)

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Levizar** [comment]
No:
1. other data could be added on other fields
2. display line are "zero valued"
3. It doesn't cause any arm
