### ISSUE TITLE
[7.0] Python constraint will fire when any change

### ISSUE THREAD

**Issue by dnt83** [odoo/odoo#13253]
Impacted versions:
7.0
Steps to reproduce: A model
```python
def _check_length(self, cr, uid, ids, context=None):
    record = self.browse(cr, uid, ids, context=context)
    for data in record:
        if data.length < 0:
           return False
    return True
	
_columns = {
			'name': fields.char("Name", size = 32)
			'length': fields.integer('Length'),
			}

_constraints = [(_check_length, 'Error: Length must be Positive', ['length'])]`
```
Current behavior:
_check_length (Constraint) run with any change
Expected behavior:
_check_length run when length change
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Thank you for the report but changing this would be a change the way constraints works. Somebody that used to have a constraint triggered (and was relying on it) not longer has it and it could be problematic.
I believe this was changed in 8.0 but we can't change it in 7.0, too risky
