### ISSUE TITLE
[8.0] Measure of type char in report not works?

### ISSUE THREAD

**Issue by Josecanalla** [odoo/odoo#13252]
Impacted versions: 8.0

Steps to reproduce: Create a report with a field of char type, then in the xml file for the report display that field with type="measure".

Current behavior: The field in the report is empty.

Expected behavior: The field displays the correspondent value for that row.

More details: my case is a report which shows for every partner the balance and the date of the last receipt. I have one row per customer and in a column the balance. So I need another "measure" with the date, but when I put that the column is empty. I tried with "date" and "char" date (with conversion). If I put it in integer value (for example showing the day of the month of the date) it works OK, so the problem is because I can't show a measure of type "char" or "date".

**Comment by Yenthe666** [comment]
Hi @Josecanalla,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
