### ISSUE TITLE
[9.0]  mail: displayed date and datetime in tracking value are displayed as Invalid

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#13258]
### Impacted versions:
9.0 

### Steps to reproduce:
* track changes on a Date field,
* Use fr as locale
* modify the date value
* check the displayed messages into the mail thread

### Current behavior: 
The new value in the thread is displayed as Invalid date

![image](https://cloud.githubusercontent.com/assets/544090/17887202/b1378098-6925-11e6-8362-a983eb9a441b.png)

### Expected behavior:
The new value in the thread is displayed without error
![image](https://cloud.githubusercontent.com/assets/544090/17887257/e9f68686-6925-11e6-9e61-5eff8c1368ec.png)

**Comment by JKE-be** [comment]
Thank you for the reporting.
It has been fixed just with commit odoo/odoo@1b2dab3f506d51b399625dba614dd3689e95bdc9

**Comment by lmignon** [comment]
@JKE-be  @aab-odoo Thank you for the quick fix
