### ISSUE TITLE
[16.4][BUG][Payroll module] HTML code seen instead of actual formatted text

### ISSUE THREAD

**Issue by Jencya** [odoo/odoo#132609]
Impacted versions: Odoo saas~16.4+e (Enterprise Edition)

Steps to reproduce: 1. Login as administrator or payroll admin
2. If there is drop pointer under 'Payroll' module, hover the mouse over it
3. Click on "Payroll" module
4. If there is drop pointer under "Contracts" menu, hover over it

Current behavior: The help tip shows HTML code instead of formatted text

Expected behavior: Formatted text should be shown

Video/Screenshot link [(optional):]
<img width="956" alt="Drop Pointer" src="https://github.com/odoo/odoo/assets/17890113/72fadf42-1761-44a3-9167-e09ec3d8872b">

<img width="943" alt="Contracts html error" src="https://github.com/odoo/odoo/assets/17890113/48b96e28-eeaa-4f37-bc5c-b612bf40e828">

<img width="607" alt="Apps screen" src="https://github.com/odoo/odoo/assets/17890113/15f5c9c2-1846-4186-afe0-c5459dee9dbb">

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Thanks @Jencya for reporting.
This has been fixed by https://github.com/odoo/enterprise/pull/45840
