### ISSUE TITLE
spelling, vue should be view

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#1326]
addons/stock/wizard/make_procurement_product.py:117:                raise orm.except_orm(_('Warning'), _('Please use the Product Variant vue to request a procurement.'))

addons/stock/wizard/stock_change_product_qty.py:58:                raise orm.except_orm(_('Warning'), _('Please use the Product Variant vue to update the product quantity.'))

**Comment by mart-e** [comment]
Thanks, fixed in master (to avoid messing existing translations) at df07ec1
