### ISSUE TITLE
[9.0]Qweb css fialed and isconnect user when used with dbfilter

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#13267]
Impacted versions:
latest v9

Steps to reproduce:
deploy odoo behind a reverse proxy with a dbfilter on hostname

Current behavior:
user is disconneted each time he try to print a pdf

Expected behavior:
Print the document

Video/Screenshot link (optional):

**Comment by flotho** [comment]
related to https://github.com/odoo/odoo/issues/2934
I succeed to make it work without dbfilter

**Comment by JKE-be** [comment]
@sle-odoo

**Comment by dansanti** [comment]
Hi! that is because, report.url != web.base.url  if you have in one of they, a url ie. 127.0.01:8069, that make that urlfilter try to make a query with a wrong urlbase.

**Comment by rubiagatra** [comment]
@dansanti I really need db filter, I am using mikrotik could you help me with your setting

**Comment by pedrobaeza** [comment]
This seems to be explained and with the related issue closed, so I'm closing this one as well.
