### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by fatinishrak** [odoo/odoo#13272]
pls give me a best tutorial for installing odoo

**Comment by JKE-be** [comment]
Please uses https://help.odoo.com for help !
This tracker is for issue only ! 

About the install, you can take a look in our official documentation:
https://www.odoo.com/documentation/9.0/setup/install.html

**Comment by fatinishrak** [comment]
![screenshot from 2016-08-24 13 40 18](https://cloud.githubusercontent.com/assets/20151422/17922341/50f9afcc-6a00-11e6-8023-30289de6b08f.png)
see this

**Comment by JKE-be** [comment]
Ye,s but i see nothing ! 
What is the error in the log ? 
Maybe you have no access to databases, or missing dependencies, ... there are many factors that can happens to have internal server error 500 ! 
Take a look in the log, and ask on https://help.odoo.com if you need some help !
