### ISSUE TITLE
xpath on v9 community - issue with name/string

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#13273]
Impacted versions: v9 community

Steps to reproduce: creating an xpath with name instead of string

Current behavior: can't inherit a page with string

Expected behavior: it should inherit it anyways, as per new API, string is deprecated, so, if I use name it should do the job, or, the parent item should have name instead of string then

I'm trying to add a page to a form, besides another page, which is located on this parent view, specifically on account.invoice_supplier_form

`<page string="Bill">`

I need to inherit this item, to place another page beside of it, actually, after it, I'm doing it this way:
`
<xpath expr="//page[@name='Bill']" position="after">`

But, obviously, the item isn't found, because it is not a name but a string, but if I put string, then it crashes and doesn't work, can't install my module, so, is there a clean way to accomplish this?

Video/Screenshot link (optional):

Thanks in advance!

**Comment by JKE-be** [comment]
Hello,

The inherit on string are not allowed, because translation can be already applied before the inherit... 
> View inheritance may not use attribute 'string' as a selector.

You can instead, use something like

```xml
<xpath expr="//sheet/notebook/page/field[@name='invoice_line_ids']/.." position="after">
    <page string="My new page"/>
</xpath>
```

This tracker is for issue/bug only, uses https://help.odoo.com for this kind of question :)

**Comment by kkoci** [comment]
Thank You @JKE-be so sorry about that, from now on I'll use [https://help.odoo.com/](url) :)

Thanks again!

**Comment by Yenthe666** [comment]
@JKE-be and @kkoci,

I'd like to add a note on this. The xpath expression example that you give JKE is very long and has a lot of risk to break. Better alternative:
```
<xpath expr="//field[@name='invoice_line_ids']/.." position="after">
    <page string="My new page"/>
</xpath>
```

**Comment by JKE-be** [comment]
@Yenthe666 Thank you for your feedback...
But you could have the same field several time defined on a same view (form, tree, kanban, ...)
So your xpath risk to fail... 
I prefere to have a xpath that make exactly what i want and so if during an update the structure change, update it... that have my code display at a bad position without know why...

**Comment by Yenthe666** [comment]
@JKE-be I tend to use the index when there are multiple items. Imagine in your example that you remove the notebook, the sheet or alle pages. It would ruin your xpath for sure..
I'm personally in favor of using `<xpath expr="//field[@name='invoice_line_ids'][1]" position="after">` then. But you're right that both have positive and negative sides.

**Comment by JKE-be** [comment]
@Yenthe666 
If someone remove the notebook, sheet, or page... that is because the view form has been completely revamped... So I prefer to have the view that crash and choose what I want really, that let the magic applied randomly the xpath :100:

**Comment by shamilithiru** [comment]
sir,
 i want to know the xpath method for adding a new field into  existing one2many field on (sale -> quotations) . please answer me...
