### ISSUE TITLE
[7.0] multi company: cid should be an argument to prop creation

### ISSUE THREAD

**Issue by mdraheim** [odoo/odoo#1327]
Situation:

We are migrating data to odoo in a multi company setup. Each company has different partners and its own chart of accounts. So, for each company and each partner there is the need to assign accounts to partners via property fields.

Problem:

Migration is done using the admin user. However, fields.py does not take a company_id argument and uses user_id.cid via _company_default_get. That leads to odd situations where res_1.cid_2 == res_2.cid_2 but prop.cid_1 and thus the property is not accessible to users of company 2.

Workaround:

Change user_admin.cid to target cid. This feels awkward and slows down migration because we need to check res cids and then switch user.

Quickfix:

At least, extend the heuristic of "assume prop.cid should be uid.cid" to something like "if admin and res1.cid == res2.cid then prop.cid = res1.cid". That would be two lines of one additional test.

Real Fix:

cid should be an arg to property creation with the current/extended logic as fallback default in case of None or permission denied.

**Comment by Yenthe666** [comment]
Hi @mdraheim ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
