### ISSUE TITLE
Login to empty screen with Odoo Logo after adding module to odoo 9

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#13279]
Link Action=Blank
![image](https://cloud.githubusercontent.com/assets/21218238/17928356/06a12ee0-6a1a-11e6-97dd-e913bc3a155e.png)
![Uploading image.png…]()

**Comment by JKE-be** [comment]
need more details ! 

Thanks to keep the template...
If not in default install, use https://help.odoo.com

**Comment by odoouser2** [comment]
I deleted all the copied module and the problem is fixed.
