### ISSUE TITLE
"measure_label" variable is not defined

### ISSUE THREAD

**Issue by baimo** [odoo/odoo#13288]
Impacted versions: 8.0

Steps to reproduce:
path :  \odoo-8.0\addons\web_graph\static\src\js\graph_widget.js:823

Current behavior:
Display a string to be translated
Expected behavior:
Assign a string can be translated

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/13926643/17953335/3804e644-6aa5-11e6-862c-d8e32d76f546.png)

**Comment by mart-e** [comment]
Hello,

Thank you for the report, I have fixed it at 4cb2dc6d71c940dbc4c23e68f8692abd4596dd1d
Regards

**Comment by baimo** [comment]
ok
