### ISSUE TITLE
Currency terminology

### ISSUE THREAD

**Issue by artaf** [odoo/odoo#13298]
Impacted versions: 9.0 and probably all others

Steps to reproduce: N/A

Current behavior:
A term 'Company default currency' is used now.

Expected behavior:
Suggestions how to change terminology:
Instead of 'default currency' a term 'functional currency' should be used.
Additional field with 'Presentation currency' or 'Reporting currency' can be added to set a currency of financial statements.

**Comment by JKE-be** [comment]
Thanks for the suggestion. 
That has been added to the wishlist !
But it will be not threat now...  Our priority (until next release) is the existing issue and v10 release.
