### ISSUE TITLE
[9.0] Odoo not loads developer mode

### ISSUE THREAD

**Issue by Josecanalla** [odoo/odoo#13301]
Impacted versions: 9.0

Steps to reproduce: In Windows 7 64 bits, go to About... and "Activate developer mode". Then the page refreshes but loads only the top black bar. **The problem is only in Google Chrome 52.0.2743.116, in Firefox (in the same PC) it works OK.**

Video/Screenshot link (optional): http://prntscr.com/caci0t

**Comment by mart-e** [comment]
Hello,

Could you open the developer console (ctrl-shift-j) when loading the page to check in the console and in the network tab what may fail?

**Comment by Josecanalla** [comment]
Well, now it works. Yes, I have Odoo 8 and Odoo 9 installed in the same PC, but when I am running one, I stop the other service.

**Comment by mart-e** [comment]
Thanks for the reply.
Your browser keeps the file in cache so make sure to correctly clean the cache when in developer mode.
