### ISSUE TITLE
ODOO V9 bug:  partial delivery of kit BOM products is not updated on SO

### ISSUE THREAD

**Issue by pvoo** [odoo/odoo#13309]
Impacted versions: V9.0

The delivered quantity on the SO is not updated for the direct sale of products which have a Kit (phantom) BOM.  Can be reproduced as follows:

**Product A:**
Stockable,  Buy,  available qty:  20

**Product B:**
Stockable, Buy, available qty: 5

**Product AB:**
Stockable, Buy,  Phantom BOM(kit) :
1x  product A  +  1 x product B   

Issue:
For a partial delivery of the product AB, the delivered quantity is not updated to the sales order.  For example we have an order of **7x product AB**,  only 5 are available so we deliver  5x productA + 5x productB   for a total delivery of **5x product AB**.  Now after confirming the delivery, the SO should show an **ordered qty: 7**  and  a **delivered qty: 5,**  instead the delivered qty on the sales order is not updated and **stays on zero**. 

No change in delivered quantities is updated to the Sales order for a partial delivery.

**Comment by mrparadies** [comment]
Is this being addressed?  I am seeing the same issue.

**Comment by nim-odoo** [comment]
This is on purpose. The policy for this situation is "all or nothing": https://github.com/odoo/odoo/blob/9.0/addons/sale_mrp/sale_mrp.py#L37

**Comment by ray-odoo** [comment]
1. Deliver all items.

2. Switch to Developer Mode. Return the items you didn't ship. Make sure to uncheck "update quantities on SO/PO". 

3. Validate the Return Transfer.
