### ISSUE TITLE
services sold through the point of sale don't create project tasks

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#1330]
install sale_service, set up a service that creates a task in a project, sell it through a regular sales order and observe the task is added to the project. Sell the same service through the point of sale interface and observe no task is added to the project.

**Comment by Yenthe666** [comment]
Hi @AlanBell,

First of all, thank you for the report and sorry for the (very) late reply.
This is actually the intended behaviour, project tasks are only made from sale orders, not from the POS.
As a matter of fact, if you would have this in the POS you would break the offline mode of the POS or you would need to add a lot of code to keep it in memory.
Anyway, this is desired behaviour and Odoo does not want to implement this in the POS.

Regards,
Yenthe
