### ISSUE TITLE
[7.0] can not stop running cron on Windows 7 using Eclipse

### ISSUE THREAD

**Issue by farinoire** [odoo/odoo#13305]
Hi,
I do not know how to stop the **cron** when it is running in background on _Windows 7_.
I am using **Eclipse** (with **PyDev** installed).

Thank you in advance!

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @farinoire ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
