### ISSUE TITLE
Bug Odoo 9: Purchase order ID doesn't link with Vendor Bill

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#13313]
Impacted versions: Odoo 9

Steps to reproduce:

- Create Purchase order
- Click on _"Invoices"_ button in PO form. It will redirect Vendor Bills
- Click on _"Create"_ button
- Field _"Add Purchase Order"_ show up with PO temporary. When other data loaded,  field _"Add Purchase Order"_ update with NULL/empty.

Current behavior:

- In Vendor Bill form, field _"Add Purchase Order"_ value show up temporary.

Expected behavior:

- Field _"Add Purchase Order"_ value should store.

From which module it's effected:

In _Purchase_ module, open _invoice.py_ file and check line number 75.

     self.purchase_id = False

What is the logic behind make it False ?

**Comment by bistaray** [comment]
The help for this field is "When selected, the associated purchase order lines are added to the vendor bill.".

I believe (my suggestion only) that this field will be False before and after lines are added to the vendor bill.  Once False, another PO can be selected.  So it needs to be set to False to allow the user to select another PO.

**origin** stores the PO(s) used to create the Invoice.  If there are more than one, each is separated by a space then a comma.

**purchase_line_id** on account_invoice_line links each Invoice line with a Purchase Order.

**Comment by bodedra** [comment]
Hi Ray,

Appreciate your comment. 

Thanks for your clarification.
