### ISSUE TITLE
Feature Request: Assign Attribute Image or Icon With Text for use on CMS/E-commerce Product Pages

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#1331]
Currently you can select attribute types as follows:

Radio
Select
Color
Hidden

![image](https://cloud.githubusercontent.com/assets/2337666/3671804/21c2d936-1255-11e4-9a1c-a557d300cbda.png)

It would be extremely useful to be able to assign attribute images (eg. pattern) or tiles with an icon/image + text or value for use on the frontend E-commerce/CMS pages.

An basic example of what I am suggesting can be found at the bottom of the page at the following link:

http://oneplus.net/hk/one#features

**Comment by carlazitroc** [comment]
@lukebranch is there any lead on this? Do you know how to achive this?

**Comment by lukebranch** [comment]
@carlazitroc ,

Unfortunately I have not had time to build these features yet. If there is enough interest in this feature i'll work on a module to achieve this, however there are no image tiles for variants in the Odoo core yet. Perhaps this may be introduced in Odoo 10, we'll have to wait and see.

**Comment by carlazitroc** [comment]
@lukebranch After searching for module I achieved this last night using this module: 

https://apps.openerp.com/apps/modules/8.0/product_attribute_value_image/

You can use this module to upload image on attribute, although this module only show the image in the  backend not in the product web page, you can achieved that buy customizing the qWeb variant view.

Under color type add on the color label the background url like this: 
```
 <label t-attf-style="**background-image:url('data:image/png;base64,#{value_id.image}') !important; background-size: cover; background-repeat:no-repeat; background-position: center center;** background-color:#{value_id.color or value_id.name}" t-attf-class="css_attribute_color #{'active' if not inc else ''}">

```
This is the sample output:


![icon](https://cloud.githubusercontent.com/assets/4166892/13449645/81bb16d8-e025-11e5-9cec-f68a3c78c3bf.png)

I hope in the future they will include a feature like, for now this is a simple solution I could think of. 

Cheers.

**Comment by lukebranch** [comment]
@carlazitroc ,

Awesome! Thanks for the info, I did not notice this module in the apps store!

I may work on a port to version 9.0, as this is what I will be using for all new projects.

**Comment by carlazitroc** [comment]
@lukebranch Tell me if you have it on version 9? maybe you could give me a copy haha :) 

Thanks Luke. 

Cheers.

**Comment by lukebranch** [comment]
@carlazitroc ,

No worries! If I decide to work on a port to version 9.0 i'll definitely comment back in this thread with a link to the dev version so you can test.

**Comment by carlazitroc** [comment]
@lukebranch Awesome! Thanks Luke :)

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sorry to ping you so much today, i'm just cleaning up my open issues. If this one is a won't fix i'll close it.

Is this something that Odoo SA might consider for master though? Swatch images are already available on Magento 1.9 core, and I think would be a valuable addition to master/v11.

Here's a link to a brief rundown on Magento's incredibly sloppy/unfriendly implementation:

http://docs.magento.com/m1/ce/user_guide/catalog/product-configurable-swatch.html

Their implementation in the core requires uploading image swatches in a media directory and then adding paths into a textarea to allow assigning an image swatch to a variant which is obviously not very friendly for the end-user who might be creating new products without much technical know-how.

I believe just adding the option of a swatch image as an extra option next to the HTML colour hex and allowing the swatch to inherit the entire product picture of the variant (in case you just want swatches to display thumbnails of product pictures) would be incredibly useful and allow for a better visual representation for displaying variations like sizes (eg. S, M, L, XL, etc.), patterns, or even entire product pictures.

The swatch image option could perhaps open up the default media manager ('Select a Media': Image, Document, Pictogram, etc.) to allow for use of normal images, as well as SVG's or the built-in icons/pictograms to represent an attribute.

Here's an example of a Magento implementation for the concept:

<img src="https://cloud.githubusercontent.com/assets/2337666/19407266/39062b0a-92cf-11e6-83bb-9f1f396f4d32.png"/>

It's not difficult to achieve by building a community module with those features, however I personally think it would be useful to have this as a core feature like the multi-image support that is now in core v10. It would make things far more intuitive and user-friendly for end-users when adding product variants.

**Comment by Yenthe666** [comment]
Hi @lukebranch,

Thanks a lot for adding further information on this.
I really like the concept and the idea, the implementation of Magento is very sloppy however.
I'll label this wishlist for now and let me ping some more guys too. @mart-e and @JKE-be we should get this for V11? 😉

**Comment by JKE-be** [comment]
@fgi-odoo Good idea ! What do you think to add this feature in ecom task...?

**Comment by lukebranch** [comment]
@JKE-be ,

Thanks for considering the suggestion!

**Comment by Yenthe666** [comment]
Hey all,

I'm closing this issue as this is no longer relevant for V8 (as Odoo 8.0 reached the end of life).
This will keep popping up as it is labeled wishlist though!

Regards,
Yenthe
