### ISSUE TITLE
extra single quotes on the date

### ISSUE THREAD

**Issue by baimo** [odoo/odoo#13315]
Impacted versions:8.0

Steps to reproduce:
1.switch to Chinese Language
2.open the Messaging menu
3.you can find the single quotes on the date
code path: \addons\web\static\lib\datejs\globalization\zh-CN.js: 46 -- 54

Current behavior:
I hope that you can get rid of the single quotes on the date!
Expected behavior:
![image](https://cloud.githubusercontent.com/assets/13926643/18038418/7d9c594e-6dca-11e6-9f73-8a6fc372a233.png)

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/13926643/18038341/7659eb2a-6dc9-11e6-85da-bf6ed0c7b007.png)

**Comment by baimo** [comment]
Before removing：
`formatPatterns: {
        shortDate: "yyyy/M/d",
        longDate: "yyyy'年'M'月'd'日'",
        shortTime: "H:mm",
        longTime: "H:mm:ss",
        fullDateTime: "yyyy'年'M'月'd'日' H:mm:ss",
        sortableDateTime: "yyyy-MM-ddTHH:mm:ss",
        universalSortableDateTime: "yyyy-MM-dd HH:mm:ssZ",
        rfc1123: "ddd, dd MMM yyyy HH:mm:ss GMT",
        monthDay: "M'月'd'日'",
        yearMonth: "yyyy'年'M'月'"
    },`
After removing：
`formatPatterns: {
        shortDate: "yyyy/M/d",
        longDate: "yyyy年M月d日",
        shortTime: "H:mm",
        longTime: "H:mm:ss",
        fullDateTime: "yyyy年M月d日 H:mm:ss",
        sortableDateTime: "yyyy-MM-ddTHH:mm:ss",
        universalSortableDateTime: "yyyy-MM-dd HH:mm:ssZ",
        rfc1123: "ddd, dd MMM yyyy HH:mm:ss GMT",
        monthDay: "M月d日",
        yearMonth: "yyyy年M月"
    },`

**Comment by JKE-be** [comment]
Hi, @baimo 

This file come from the datejs library...: https://github.com/datejs/Datejs/blob/master/src/globalization/zh-CN.js#L46

Maybe you can try to open an issue/PR on this project.

Once done, don't hesitate to reopen a PR to update the datejs library in Odoo.
