### ISSUE TITLE
[8.0] Quote use on 't-field-options'

### ISSUE THREAD

**Issue by alexdgs** [odoo/odoo#13314]
**Impacted versions:**
Tested in 8.0 commit c55c15aef39e9780cf48d2bc967b4e8357f31402 (latest when reporting). Executing server in Linux Debian Jessie (up-to-date) with all Python dependencies from requirements.txt installed inside a virtualenv.

**Steps to reproduce:**
1. Inside a printable report template (XML file), locate/declare a field using `'t-field'` and add the attribute 't-field-options' for additional formatting. Make sure that **double quotes** (") are used for delimiting the attribute value and **single quotes** (') for inner strings.
e.g. `<span t-field="detail.piece" t-field-options="{'widget': 'monetary', 'display_currency': 'detail.currency_id'}"/>`
2. Update the module containing the report.
3. Print the report.

**Current behavior:**
An exception is launched. This is the error at the end of the traceback:
`QWebException: Expecting property name: line 1 column 2 (char 1)`
Here the [full traceback](https://github.com/odoo/odoo/files/440642/traceback.txt)

But **swapping** single and double quotes like in:
`<span t-field="detail.piece" t-field-options='{"widget": "monetary", "display_currency": "detail.currency_id"}'/>`
And updating the module, makes report printing successful.

**Expected behavior:**
Report should print regardless of which quotation style is used for XML attribute values, as using either single or double quotes for delimiting them is legal syntax.

This issue seems don't occur with similar Odoo XML dictionary-like attribute values, like `attrs` and `options` in views.

**Comment by JKE-be** [comment]
hi @alexdgs 

It is because it is parsed as json... and the json RFC require a " as 'quotation mark'. (https://tools.ietf.org/html/rfc7158#section-7)
It has been improved in v10 since odoo compile template in ast and so use ast.literal_eval on it. 
So in v8/9 " is require, in v10 we will support the '
