### ISSUE TITLE
LESS doesn't work on login page.

### ISSUE THREAD

**Issue by DanielGasperoni** [odoo/odoo#13324]
Impacted versions: V9.0

Issue:
On login page, if I link a less, Odoo is not generating the css on the fly, but on backend and website's frontend the less is working fine. The issue is only on login page.

example:
`<link rel="stylesheet" type="text/less" href="/mymodule/static/src/less/style.less"/>`
		
I call this line in "web.assets_backend" template and works
but this same line in  web.login_layout doesn't

**Comment by Yenthe666** [comment]
Hi @DanielGasperoni,

Thanks for your report but Github issues are only for reporting issues in the official Odoo code.
However, I see you're talking about web.assets_backed while you're trying to add less to the front-end. If I'm not mistaking you should add an import for `web.assets_frontend`, since you're working in the website.

P.S: It is best to ask these kind of questions on the official Odoo help forum (help.odoo.com).

Regards,
Yenthe

**Comment by rafaeljuzwiak** [comment]
Actually I had the same issue also a while back. I was trying to edit the login page css, and I couldn't figure out why my .less css wasn't imported by just extending the login template page. Latter I figure out the layout was actually the website layout, and I just added there.

However, it would make sense this .xml that contains the login page layout declaration be capable of parsing the .less files, wouldn't?

Thanks

**Comment by Yenthe666** [comment]
Hi @rafaeljuzwiak,

The back-end (read everything not website related) and the front-end (website related) are cleanly separated. This means you'll have to call the right asset (`web.assets_backend` or `web.assets_frontend`), this was a clear choise by the developers.

**Comment by DanielGasperoni** [comment]
@Yenthe666 
The Login Page is not calling neither web.assets_backed nor web.assets_frontend when you haven't install any website app (blog, website, etc)

Actually, there are two login pages:
one inside the website (this one is calling the web.assets_frontend
and the another is just the login page (that one with "manage database below the form)
just is one that it's not working.

Sorry, I didn't post on forum because I assumed this was a bug.

**Comment by Yenthe666** [comment]
Hmm I see,  @JKE-be can you shed some extra light on this please?
I bet you've got more info.

**Comment by mah007** [comment]
any solution for that ?
