### ISSUE TITLE
[odoo 15]how to hide by user_type (sel_groups_1_9_10) generated by base

### ISSUE THREAD

**Issue by huydoba** [odoo/odoo#133285]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
This is literally everywhere in the code base. Domain rules, access rules, views, menus, everywhere. You obviously don't hide by the group of groups, but by the individual group selected within that group.
