### ISSUE TITLE
[9.0] Page number cannot be used in Body of QWeb report

### ISSUE THREAD

**Issue by atchuthan** [odoo/odoo#13332]
Impacted versions:
9.0
Steps to reproduce:
the page number can be added in the footer but not in the body of QWeb report

**Comment by naitikvithlani** [comment]
This issue also impact in version 10c.

**Comment by pedrobaeza** [comment]
This is something inherent of wkhtmltopdf PDF engine. We should wait for a change in that engine (it seems in v12 is going to happen) for solving it.
