### ISSUE TITLE
[16.0] Issues with Polish Translation

### ISSUE THREAD

**Issue by mateusz-leja** [odoo/odoo#133310]
Impacted versions:
16.0

Steps to reproduce:
- Change Odoo language to Polish.
- Check the preview of Polish email templates.
- Create an event in the event module and try to register for the event from the website.

Current behavior:
- Trying to preview the Polish version of emails causes QWeb errors.
- The event registration button on the website, in the Polish version, is faded and inactive.
- This behavior is only seen in the Polish version. The English version works normally.

Expected behavior:
- No QWeb errors should occur when sending emails.
- The registration button should be functional.

Additional Information:
- There are more errors in the Polish version of Odoo that have not yet been identified.
- **Full revision of polish translation is urgently needed.**

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hello,

Thanks for your report but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github.

Please submit your changes there and let me know if you have issues.

Thanks
