### ISSUE TITLE
Not showing Attribute Price Extra field

### ISSUE THREAD

**Issue by innovo3d** [odoo/odoo#13340]
Impacted versions: 9c (and 8 also)

Steps to reproduce:

Current behavior: Does not show **Attribute Price Extra** field in Sales -> Products -> Attribute Values.  This is with Sales Manager privileges enabled for an Admin user.

Expected behavior:
Should show **Attribute Price Extra** field

Video/Screenshot link (optional):
<img width="1236" alt="screen shot 2016-08-31 at 12 46 58 am" src="https://cloud.githubusercontent.com/assets/7477099/18117515/f31e5a3c-6f14-11e6-918b-7c9489adc824.png">

**Comment by pedrobaeza** [comment]
This is because you need to enable developer mode for seeing some "technical" fields. Closing as no real issue.
