### ISSUE TITLE
Error while validating constraint  'sale.order' object has no attribute 'fiscal_position'

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#13348]
Impacted versions: SAAS 12

Steps to reproduce:
Create blank database, sales, sock, accounting module, spain chart account

Current behavior:
Few consumable products
create sale order, on save error raise.

Error while validating constraint  'sale.order' object has no attribute 'fiscal_position'

Expected behavior:
Create sale order and work proper

Video/Screenshot link (optional):
![screenshot from 2016-08-31 18-47-27](https://cloud.githubusercontent.com/assets/311413/18130125/6b17f5de-6fab-11e6-957b-90066d2422c1.png)

**Comment by Yenthe666** [comment]
Hi @tejastank,

Thanks a lot for the bug report.
I was no longer able to reproduce this issue in the newer Odoo versions. Don't hesitate to respond back if you can still reproduce it though!

Regards,
Yenthe
