### ISSUE TITLE
onchange_qty in purchase order line does not work at all [8.0]

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#1334]
When you set a product in a purchase line, it sets qty and price, if you change the price and then you change the qty, when you tab the first price is setted again. I don't know why, but onchange_qty triggers onchange_product_id again.

**Comment by Yenthe666** [comment]
Hi @javierjcf,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
