### ISSUE TITLE
Disable field translations for anything other than "en_US" (pull request possible)

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#13346]
I understand that the "en_US" language cannot be disabled, however if I want to run Odoo in only Dutch and German, where Dutch is the ONLY language for all users ("en_US" will never be used). Right now this results in 2 translation records for each term. 

The original term will never be updated or changed, since the users threat the Dutch language as their primary language. Translating everything in German (for our customers) becomes tricky, since the original terms have never changed (this happens when duplicating or changing models).

Looking at res.lang I see a "translatable" flag, I didn't see it do anything. I expected it to prevent user translations. So once I disable the translatable flag for the "nl_NL" lang, I would expect Odoo to only create 1 translation record for each term (the german language). So if a user ("nl_NL") changes a translatable field, the original db field get's changed.

For now I made a small patch to models.py and ir_translation.py to account for the "translatable" flag on res.lang. 

I can make a pull request for this feature.

**Comment by daemonblade** [comment]
@adaptivdesign Could you please share the patch? This issue has aggravated me (and customers) for ages.

**Comment by Yenthe666** [comment]
Hmm I'm quite sure that won't work out nicely. The translations system is built to use `en_US` as default to build everything else on top of this.
@mart-e is the expert in translations so he can answer this better though. Either way, I'm 99% sure that a PR to change this behaviour won't be accepted.

Regards,
Yenthe

**Comment by adaptivdesign** [comment]
Hi @daemonblade 

It's part of a private repo currently, but here are the 3 changes made. Just create a module for them

## Implementation

models/ir_translation.py
```
from odoo import api, models

class IrTranslation(models.Model):

    _inherit = 'ir.translation'

    @api.model
    def _set_ids(self, name, tt, lc, ids, value, src=None):
        result = super(IrTranslation, self)._set_ids(name, tt, lc, ids, value, src)
        lang = self.env['res.lang'].search([('code', '=', lc)])
        if lang and lang[0].primary_input and tt == 'model':
            model_name, field_name = name.split(',')
            model = self.env[model_name]
            field = model._fields[field_name]
            if not callable(field.translate):
                # Make a context without language information, because we want
                # to write on the value stored in db and not on the one
                # associated with the current language. Also not removing lang
                # from context trigger an error when lang is different.
                model.browse(ids).with_context(lang=None).write({field_name: value})
        return result
```

models/res_lang.py

```
from odoo import fields, models


class ResLang(models.Model):

    _inherit = 'res.lang'
    primary_input = fields.Boolean()
```

views/res_lang.xml

```
<?xml version="1.0"?>
<odoo>
  <data>

    <record id="res_lang_tree" model="ir.ui.view">
      <field name="name">res.lang.tree.inherit</field>
      <field name="model">res.lang</field>
      <field name="inherit_id" ref="base.res_lang_tree" />
      <field name="arch" type="xml">
        <xpath expr="//field[@name='active']" position="after">
           <field name="primary_input" />
        </xpath>
      </field>
    </record>

    <record id="res_lang_form" model="ir.ui.view">
      <field name="name">res.lang.form.inherit</field>
      <field name="model">res.lang</field>
      <field name="inherit_id" ref="base.res_lang_form" />
      <field name="arch" type="xml">
        <xpath expr="//field[@name='translatable']" position="after">
           <field name="primary_input" />
        </xpath>
      </field>
    </record>

  </data>
</odoo>
```

## How to use

- Enable developer mode, go to languages. Now for your primary input language, (anything besides en_US) check "primary input". NOTE: this should only be one language ofcourse!!

- In case of an existing database. Delete all ir_translations records for your models.


## How it will work

Upon saving, Odoo will no longer create a translation record and will directly change the db value. This works perfectly for single language installations.

This also works for multiple languages:

- nl_NL = primary_input
- de_DE
- fr_FR

In this case Odoo translations will still work for de_DE and fr_FR. 

## Currently not working (can be fixed)

@daemonblade @Yenthe666 @mart-e 
In the case of multiple languages inlcuding en_US:

- nl_NL = primary_input
- en_US
- de_DE

In this case Odoo will save the db value for en_US because this language is hardcoded into it. How to fix this:

at https://github.com/odoo/odoo/blob/10.0/odoo/models.py:

line 3613:
```
has_trans = self.env.lang and self.env.lang != 'en_US'
```

Could become something like this:

```
has_trans = self.env['res.lang'].get_primary_input() == self.env.lang
```

Same goes for line 3927:

```
if self.env.lang and self.env.lang != 'en_US':
```

## Pull request

If there is a 99% chance that this won't be accepted. I won't create a pull request for this. However I know this is absolutely possible. 

## Alternatives

@daemonblade 

If you are in need for en_US, take a look at https://odooku.github.io/odooku/

Create an issue for me there. I will implement a patched models.py for this. I have done this for another unfixed core issue as well (https://github.com/odoo/odoo/issues/14938).

**Comment by mart-e** [comment]
Hello,

Actually, since v10, you can create a database in only one language (with en_US disabled).
Did I misunderstood your issue or is it already fixed :)

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as (@)mart-e gave an answer (and asked if this was okay) and there was no feedback in a long time.

Regards,
Yenthe
