### ISSUE TITLE
Incorrect duration bar on Gantt views using date_delay option

### ISSUE THREAD

**Issue by xava3000** [odoo/odoo#1335]
Impacted versions:
Odoo/master

Steps to reproduce:
I think this is a wrong behavior of the Gantt view, but can be validated on the calendar app:
- With the Calendar app with demo data installed do the following:
  - go to Messaging/Calendar
  - create a new event that expands some days (to better see the effect)
  - go to the Gantt view: Nothing is shown. 

The code of the gantt view is:
<record id="view_calendar_event_gantt" model="ir.ui.view">
        <field name="name">CRM - Meetings Gantt</field>
        <field name="model">calendar.event</field>
        <field name="arch" type="xml">
            <gantt date_delay="duration" date_start="date" string="Meetings"/>
        </field>
    </record>

If you modify the view to use the "date_stop" parameter, instead of "date_delay"
<record id="view_calendar_event_gantt" model="ir.ui.view">
        <field name="name">CRM - Meetings Gantt</field>
        <field name="model">calendar.event</field>
        <field name="arch" type="xml">
            <gantt date_stop="stop_date" date_start="start_date" string="Meetings"/>
        </field>
    </record>

You will see the bar correct. Even the duration that says the view is not correct.

Expected behavior:
The gantt view with date_delay works ok, showing the events related. I tried with a custom module and I saw that the problem is the behavior of this view type with this specific parameter (date_delay). With date_stop, is working.

**Comment by Yenthe666** [comment]
Hi @xava3000,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
