### ISSUE TITLE
Compute function can't be override

### ISSUE THREAD

**Issue by siyuancn** [odoo/odoo#13359]
Impacted versions: 9c

Steps to reproduce:

I inherited the module sale.order.line and rewrote the invoice_status to remove the compute function: '_compute_invoice_status' 

```
    invoice_status = fields.Selection([
        ('upselling', 'Upselling Opportunity'),
        ('invoiced', 'Fully Invoiced'),
        ('to invoice', 'To Invoice'),
        ('no', 'Nothing to Invoice')
        ], string='Invoice Status', store=True, readonly=True, default='no')
```

Current behavior:

I restarted the service and installed the inherited module.

But the compute function still works. 

Expected behavior:

The compute function "invoice_status" will not be called.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Indeed, when overwriting a field, you only change the new attributes, not redefine all.
```python
# origin
foo = fields.Char(string="Old name", required=True)

# overwrite
foo = fields.Char(string="New name")  # still required=True
```
you must explicitely disable the attribute you want to remove

closing as github is not the proper place to ask développement advises, it is to report bugs
