### ISSUE TITLE
Problem with LDAP Module

### ISSUE THREAD

**Issue by LeDistordu** [odoo/odoo#13358]
Already post this problem but the issue was closed > https://github.com/odoo/odoo/issues/12883

I'm stuck with a module that bug and i cant remove it for reinstall

How can I remove this module manually to return to a normal situation ?

**Comment by Yenthe666** [comment]
Hi @LeDistordu,

I'll re-open the other issue and close this one, there is more history on the other one. 
My apologies!

Regards,
Yenthe
