### ISSUE TITLE
[16.0] Missing Website B2B / B2C setting

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#133649]
Impacted versions: 16 

Steps to reproduce: cant select multi website is b2b or b2c

in website_sale/views/res_config_settings_views.xml following inherit removed settingsin website settings. 
i think its a mistake.

```
<record id="res_config_settings_view_form_inherit_sale" model="ir.ui.view">
        <field name="name">res.config.settings.view.form.inherit.sale</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="sale.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <!-- Remove customer accounts setting from sales settings tab -->
            <!-- It must not be in the view at all to make sure settings can be saved
                (because auth_signup_uninvited is specified as required) -->
            <xpath expr="//div[@id='auth_signup_documents']" position="replace"></xpath>
        </field>
    </record>
```

**Comment by vava-odoo** [comment]
Hi @esakarya 
All settings in 16 are applied to all websites, which will not be the case in 17 where all settings will be website-dependent (including tax included/excluded setting).
Not sure what the code you show has to do with the issue though.
Cheers
