### ISSUE TITLE
Sequence doesnot follow sequence size

### ISSUE THREAD

**Issue by elicoidal** [odoo/odoo#13364]
Impacted versions:
v9 (c/e)

Steps to reproduce:
In demo data, modify the sequence of the SO and set the next number to 999 and Sequence Size to 3
Current behavior:
When generating a new SO, next number is 1000

Expected behavior:
When generating a new SO, next number is 000
(as the size is 3)

Video/Screenshot link (optional):

![screenshot from 2016-09-01 19-24-07](https://cloud.githubusercontent.com/assets/7600613/18165750/aefa8a5e-7079-11e6-8021-99c7d02d431b.png)

**Comment by xmo-odoo** [comment]
The "sequence size" label is somewhat misleading, that field actually specifies the padding of the generated string (to *at least* n characters) there is no way to set a maximum width, which is clearly noted in the field's help. The previous ("Number padding") wasn't exactly self-explanatory but wasn't outright misleading either, not sure why @mart-e changed it.

**Comment by mart-e** [comment]
My guess is that it was a report from translator not understanding technical terms like "padding".
Anyway the help message on the field explains quite well what it means.
I am closing the bug as it's workings as expected but if you have better name suggestion, please let me know.

**Comment by elicoidal** [comment]
Naming is misleading (all the more with the change of behavior from v8).
So for what I understand we dont have anymore the idea of padding and fix width sequence number (before the number would always be maximum 3 char wide).
Text message would fit the definition of padding: 
> Extraneous text added to a message for the purpose of concealing its beginning, ending, or length.

Problem is probably that previous behavior was that the padding would complete up to the number specified while now the number specified is not a padding but a minimum character size.

Not sure of the rationale in the change of behavior but it is annoying not to have the possibility of fixed width sequence number.
If not a bug per se, I really consider it a strong regression.
Please note as well that padding of 3 while number is > 1000 doesnot make any sense.

Suggested name: "Minimum Sequence Size"
Suggested help message: "...to get at least the minimum padding size"

**Comment by elicoidal** [comment]
thanks for your quick reply anyway :)
