### ISSUE TITLE
lastest odoo 9.0 can not create new database

### ISSUE THREAD

**Issue by joyinfo** [odoo/odoo#13362]
Impacted versions: 
9.0

Steps to reproduce:
Create Database

Current behavior:
![2016-09-01 5 21 55](https://cloud.githubusercontent.com/assets/20535391/18162347/9bb8557c-7068-11e6-8dc9-a6e70f259ec5.png)

Database creation error: relation "res_users_log" does not exist LINE 1: INSERT INTO "res_users_log" ("id", "create_uid", "write_uid"... ^

Expected behavior:
Creating database succeeded.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Could you post your server logs to see the full error?
Do you have other databases from other versions on the server?

**Comment by joyinfo** [comment]
I got the reason, because of an invalid third module,

**Comment by LeartS** [comment]
I can confirm that creating a new database fails with that error if in one of the addons path there is an invalid module (e.g. a directory which is not an odoo module).

IMO the module should be skipped and an error/warning message logged; and it definitely shouldn't try to add a record in a table that doesn't exist yet. @mart-e what do you think?
