### ISSUE TITLE
[stock] The picking type of the picking created by procurement does not match with the picking type defined in pull rule

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#13360]
Impacted versions:
- 8.0

Steps to reproduce:
- Create **warehouse a**
- Create **warehouse b**
- Resupply **warehouse a** from warehouse **YourCompany**
- Resupply **warehouse b** from warehouse **YourCompany**
- Create product **test**
- Create orderpoint rule in **warehouse a**
- Create orderpoint rule in **warehouse b**
- Check the routes of resupply from warehouse **YourCompany** in procurement tab into product
- Create new picking type **Delivery warehouse a**
- Create new picking type **Delivery warehouse b**
- replace picking type of pull rules created into routes of resupply by the new
- Run procurement

Current behavior:
The pickings from **Stock** -> **inter company transit** are into the same picking type and this is not the expected behavior
The picking from **inter company transit** -> **warehouse a** has the expected picking type
The picking from **inter company transit** -> **warehouse b** has the expected picking type

Expected behavior:
The pickings from **Stock** -> **inter compnay transit** must be each one into respective picking type
e.g
The pickings created by orderpoint rule  **warehouse a: resupply from YourCopamy**
it should be created:
**Stock** -> **inter compnay transit** into picking type **Delivery warehouse a**
**inter compnay transit** -> **warehouse a** into picking type **reception warehouse a**

The pickings created by orderpoint rule  **warehouse b: resupply from YourCopamy**
it should be created:
**Stock** -> **inter compnay transit** into picking type **Delivery warehouse b**
**inter compnay transit** -> **warehouse b** into picking type **reception warehouse b**

in each case only the second picking is created like expected

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=8Yx8to0zTnY&feature=youtu.be

**Comment by Yenthe666** [comment]
Hi @JulioSerna ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
