### ISSUE TITLE
Label tag assigned to wrong field on website sale checkout template

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#13374]
Impacted versions:
9.0 community
Steps to reproduce:
Navigate to website_sale/views/templates.xml on the checkout template, where the email input field is declared. On top of it there is a label 

`<label class="control-label" for="contact_name">Email</label>`

From what I understand the for on this label the for attribute should be equal to email and not contact_name.

![issue](https://cloud.githubusercontent.com/assets/3503159/18197781/b6acca04-7101-11e6-86ed-99a41d63a43d.png)

**Comment by JKE-be** [comment]
Thank for reporting, 

Commit in staging
