### ISSUE TITLE
Website snippets are not translated

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#13378]
Impacted versions: 8, 9, 10

Steps to reproduce:
1. Add an additional language to your website.
2. Drag and drop any snippet to any page in 1st language.
3. Switch to 2nd language.

Current behavior:

Snippet stays in 1st language.

Yes, most snippets are there as placeholders to replace stuff, but there are others that have attached logic or hidden parts, such as the one to subscribe to a mass mailing list, that will just become impossible to translate ~~(at least by a end user)~~.

Expected behavior: Snippet gets translated if it has unchanged parts and an available translation into 2nd language.

@Tecnativa

Video/Screenshot link (optional):

![captura de pantalla de 2016-09-02 12-06-55](https://cloud.githubusercontent.com/assets/973709/18200649/2133615e-7106-11e6-8c73-36f442f9f3ff.png)

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I think the problem is with multi_website, so I close for the moment.

**Comment by Yajo** [comment]
Screenshots are from Odoo runbot...

**Comment by Yajo** [comment]
It seems there is a workaround:

0. Set your website's primary language as English and edit there the website at your will.
0. Go to *Settings > Translations > Application Terms > Synchronize terms* and sync other languages.

Website snippets get translated in all languages.

But there's still one problem... What if you don't know/need/want English?

**Comment by treviser** [comment]
@Yajo Did you try to just untick english after you have finished the website design?

**Comment by rafaelbn** [comment]
Another opinion it apreciated @Yenthe666 please

**Comment by Yajo** [comment]
@treviser Then how do you translate into new main language? Translating would mean changing the view structure and thus getting hit by the bug again. It seems your idea is not feasible.

**Comment by Yenthe666** [comment]
Hi @rafaelbn,

Sorry this one got burried in my pile of notifications..
While you can use the workaround I don't think that we can label it as a bug, it is however an improvement (and a quite good one).
If you're using Odoo in multi language you should have this ability so I'll label this wishlist.
@JKE-be since you're the website guy, what do you think?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Not user friendly, but you can translate it like that:

![ezgif com-6f766b90b1](https://cloud.githubusercontent.com/assets/4848797/20501946/4ce551fc-b03c-11e6-8127-4f2c9a642b19.gif)

**Comment by JKE-be** [comment]
@Gorash Maybe an idea for new/next translation algo...

When you drop a snippet ( translated ), translation is not copy on the current page...

**Comment by Yajo** [comment]
That workaround is :hankey:, are you planning a real fix?

**Comment by Yenthe666** [comment]
Hmm @Yajo,

While it isn't the best way (it is a quite big workaround) it does work.
On the other hand @JKE-be is there any chance it can get a slight improvement in usability? It is not ideal.

**Comment by JKE-be** [comment]
@Yajo, IMHO, No (not 'fix', but 'imp' in future version) ! The translation system in front end is based on the "Wysiwyg" concept.

You ask a workaround, I give it to you...
You can also use the back end, or duplicate the terms in page, translate it and remove term from page...

I'm not saying that it is the best way to do it, I just propose you a workaround while we improve the way to do it ( I don't really see proper way) !

**Comment by Yajo** [comment]
Yes, thanks for the workaround. But really it's very hard to train end users to do those kind of things. Chances are they will simply forget about it.

I think the engine should be a little bit "smarter" when translating qweb views: if a chunk of text matches another one found in a snippet, then use that translation by default.

In the moment you change a block's text, no smartypants features, but if you don't change it (like probably will happen in this very case), then reusing the translation efforts from upstream seems most sensible.

**Comment by pedrobaeza** [comment]
Another workaround is to synchronize translations after inserting the snippet and it will get translated, but I think we are losing the focus on this...

The real problem is that all of these workarounds don't work when the website base language is not English. @Yajo, do you remember that it was what we faced?

**Comment by Yajo** [comment]
I think that is only a problem in v8, if I don't remember bad.

**Comment by pedrobaeza** [comment]
Yeah, that's true.
