### ISSUE TITLE
I lost kanban view of leads

### ISSUE THREAD

**Issue by LeDistordu** [odoo/odoo#13371]
Impacted versions:
Version 9.0e-20160901

Current behavior:
![chrome_2016-09-02_00-04-24](https://cloud.githubusercontent.com/assets/7805145/18186084/04c3ce92-70a1-11e6-9f64-fc23d5961493.jpg)

Expected behavior (Screenshot in pipeline) :
![chrome_2016-09-02_00-06-43](https://cloud.githubusercontent.com/assets/7805145/18186108/21f7f128-70a1-11e6-9a0c-a48a882504d9.jpg)

I have not been back in leads long but a month ago I could have seen the kanban before. My team spent two updated since and have certainly touched something ^^

**Comment by mart-e** [comment]
Hello,

It's actually wanted, the kanban view was removed at 4f7d0da94204dc6685c87cbfc675a7c38039aee5 because the stage grouping was confusing.
The kanban is still present on the opportunities though.
