### ISSUE TITLE
[9.0] Wrong tax calculation width discount +rounded=0+globally tax method

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#13386]
Impacted versions:
[9.0]

Steps to reproduce:

1.- Set globally tax method
2.- Set tax amount 19% not included
3. - Create an invoice with 2 lines:
 item 1 , qty = 160 , price unit 1363 discount 3%
ITEM 2 , qty = 84 , price unit   429 discount 3%

Current behavior:

gets : base amount 101723
      tax 19328
     Total 121051

Expected behavior:

gets : base amount 101723
      tax 19327
     Total 121050

that make a trouble with my tax country office's API

**Comment by treviser** [comment]
Would you mind to make an example with figures easier to calculate? And also, how do you calculate a base amount of 101'273, I get an amount of almost 300'000? Can you provide a screenshot?

**Comment by dansanti** [comment]
101723*0.19 = 19327
101723*1.19 = 121050

**Comment by treviser** [comment]
Does it work using rounding per line?

**Comment by dansanti** [comment]
Screenshoot

<img src="https://dl.dropboxusercontent.com/u/15378442/tax.png" />

**Comment by dansanti** [comment]
per line make more rounding problems:

ie : 
line1  tax = 25.4
line2 tax = 25.4
* odoo way with rounding
 tax_amount = 50
* Tax office way with rounding:
tax_amount = 51

**Comment by treviser** [comment]
Well the correct result using a decimal accuracy of 2 digits is:
- base amount 101'723.9
- tax amount 19'327.541 (which means 19'328 when rounded to 0 digits).

**Comment by dansanti** [comment]
well, then there are a bad rounding with base amount

**Comment by treviser** [comment]
I believe you should check your different settings for decimal accuracies, see this discussion for hints: https://github.com/odoo/odoo/issues/2594

**Comment by dansanti** [comment]
a temporally fix is install python_tax_method and add

``

 result = round(base_amount) * 0.19

``

**Comment by dansanti** [comment]
Hi! i can fix for non include tax method , with logic, tax must be roundglobally, but line_price_subtotal must be round per line then  in line : 

https://github.com/odoo/odoo/blob/9.0/addons/account/models/account.py#L674

`
prec = currency.decimal_places

        total_excluded = total_included = base = round(price_unit * quantity, prec)

        if company_id.tax_calculation_rounding_method == 'round_globally' or not bool(self.env.context.get("round", True)):
            prec += 5
`

with this change works for non included, for reverse mode, still happens

**Comment by pedrobaeza** [comment]
I think this is not happening anymore, and thus I'm closing. If not, feel free to comment.
