### ISSUE TITLE
[master] Double popup on Sales App when teardrop shown

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#13383]
![image](https://cloud.githubusercontent.com/assets/13910162/18219858/d97e6504-7121-11e6-92e8-ed9d779a7723.png)

Discovered on runbot today: http://170139-master-c5d5e8.runbot8.odoo.com/

**Comment by bistaray** [comment]
I just realized this is because there are TWO teardrops for this App.

The one beneath is this:

![image](https://cloud.githubusercontent.com/assets/13910162/18219903/23705f6e-7122-11e6-94ec-388c54164516.png)

**Comment by qsm-odoo** [comment]
Hello,
We are aware that some of tips may overlap (even though I think this is the only case which exists). However, as you said, you discovered the problem on runbot, which is not a typical user case. The tip system was designed thinking about users which grow their odoo discovering the apps one at a time. The two tips which are overlapping here come from two different apps and would thus never overlap during a typical user onboarding.
