### ISSUE TITLE
hr_payroll : Subtotal in payslip

### ISSUE THREAD

**Issue by ericzen** [odoo/odoo#13391]
Impacted versions: 9

Steps to reproduce: I use the french payroll. I've a subtotal "Total charges patronales" and a other "Total retenues".

Current behavior: When you make manually the cumul of "Total charges patronales" with the salaries rules CSG and CRDS, you find an different amount compared with "Total retenues" calculated by odoo. There is an impact on the due of the payslip.
In the database, amounts are correct for all salary rules with 2 decimal round. So when you confirm the payslip, the accounting entry is correct to with the same amount as the database. So we have, 0.01 euros gap with the edited payslip.

Expected behavior: Have the right subtotal and the right net on the payslip.

Video/Screenshot link (optional):
[Payroll mistake.pdf](https://github.com/odoo/odoo/files/454537/Payroll.mistake.pdf)

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yenthe666** [comment]
Hi @ericzen ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
