### ISSUE TITLE
ht_payroll_account : account details

### ISSUE THREAD

**Issue by ericzen** [odoo/odoo#13390]
Impacted versions: 9

Steps to reproduce: if you have some salary rules for the same contributions register, when you confirm the payslip, there are as much debit and credit line than salary rules. 

It will be better that we have only total line per account even if we have multiple salary rules with the same account.

**Comment by pedrobaeza** [comment]
This is how this works, and there are reasons for that about the way it's generated, so this is not a real bug, but a "wishlist". There are now works in progress for improving this, so I'm closing this in expectation to have better things in v12.
