### ISSUE TITLE
evaluate/help/reuse grapesjs

### ISSUE THREAD

**Issue by pierreozoux** [odoo/odoo#13405]
We need to let user be able to create nice website/pages, without technical knowledge. A lot of project are reinventing the wheel, and I really think we should mutualize effort around a nice library and reuse that library.

Please see this issue:
https://github.com/artf/grapesjs/issues/20

**Comment by Yenthe666** [comment]
Hi @pierreozoux,

Thanks a lot for the suggestion.
As Odoo has their own framework + ORM and the own website builder this is not something Odoo is planning on doing.

Regards,
Yenthe
