### ISSUE TITLE
[9.0] Long product names cause error on Delivery slip for wkhtmltopdf 0.12.1.2

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#13400]
#### Impacted versions:

9.0, at least nightly build for `20160824`.
#### Steps to reproduce:

This was tested with a picking containing 23 lines. Line 14 contained a product with a `default_code` 14 characters long, a `name` 69 characters long and a variant attribute name 19 characters long. In total, the displayed (and printed) name becomes 108 characters with added spaces and brackets.

So 

```
[XXXXXXXXXXXXXX] YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY (ZZZZZZZZZZZZZZZZZZZ)
```
#### Current behavior:

Attempting to print the Delivery slip for this picking causes an error to pop up containing the message 

```
UserError: (u'Wkhtmltopdf failed (error code: -11). Message: ', None)
```

Shortening the product name or updating `wkhtmltopdf` (see below) caused the report to print without problems.
#### Expected behavior:

The report should print, or at least should warn about the product name being too long. Whether it looks good with extremely long product names is not the point of this issue.
#### Additional information:

This appears to point to a segmentation fault while rendering the report. 

We run our Odoo in a custom Docker image, so there may be some other cause, but updating the `wkhtmltopdf` binary to the latest version `0.12.2.1` provided by Odoo fixed this problem:

```
curl -o wkhtmltox.deb -SL http://nightly.odoo.com/extra/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb
```

However, it seems there are some other issues with using `0.12.2.1` with Odoo, and it is suggested in issues #4806 and #5177 to stick to `0.12.1.2`. So updating `wkhtmltopdf` isn't really a solution for us until the newer version is officially supported.

**Comment by aisopuro** [comment]
It seems like @sle-odoo has done a lot of work with `wkhtmltopdf` issues, maybe you have some insight into this?

**Comment by aisopuro** [comment]
Strangely, this has now also happened with the `Picking Oerations` report. However, for that picking the `Delivery slip` printed without problems. The longest product name in this order was 80 characters, roughly like this (spaces included):
```
[XXX00000000000] XXX Xaaaaaaaaaaaaa Xaaaa Xaaaaaaaaaaaaaaaa (00aa Xaaaaaaaaaaaa)
```

**Comment by aisopuro** [comment]
Has this moved forward at all @sle-odoo?

**Comment by sle-odoo** [comment]
Hello,
Sadly, not. Did you customise this report?

**Comment by aisopuro** [comment]
No, as far as I remember it was unmodified.

**Comment by pedrobaeza** [comment]
I haven't experimented this problem since a lot, so I think it's solved, and thus I'm closing. If not, feel free to reopen it.
