### ISSUE TITLE
[9.0e] web: phone field trying to behave like FieldEmail

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13401]
**Impacted versions:**
9.0 Enterprise

**Steps to reproduce:**
1. Create a new instance
2. Go to Contacts
3. Open any contact in edit mode
4. Click or double click on phone or mobile field.

**Current behavior:**
An error is raised "Can't send email to invalid e-mail address" and it opens system's default mail client

**Expected behavior:**
Being able to edit the field without this error message.

**Video/Screenshot link (optional):**
![screen shot 2016-09-05 at 16 31 29 3](https://cloud.githubusercontent.com/assets/8862626/18250966/b82fe0dc-7386-11e6-9017-b041dc1d7346.png)

**Note**

This commit https://github.com/odoo/enterprise/commit/1f5957a38f6bb3cadab80aaf7f25a0b2d8314364 added this error message at `FieldEmail` definition.
`PhoneField` and `UrlField` are inheriting from `FieldEmail`, this shouldn't be the case.

opw: 687766

**Comment by aristobulo-eezee** [comment]
Hello @simongoffin, could you take a look of this, please.

**Comment by sbidoul** [comment]
@simongoffin how was this resolved? We are facing the same issue.

cc/ @chrisdec @JonathanNEMRY

**Comment by JonathanNEMRY** [comment]
cc @Olivier-LAURENT

**Comment by simongoffin** [comment]
@sbidoul 

https://github.com/odoo/enterprise/commit/2d49b40181e48aa84338ecc7e5bf4a49f882272b
