### ISSUE TITLE
[FEAT]: use @property for sale order states modifiers instead of constants

### ISSUE THREAD

**Issue by razvanioan** [odoo/odoo#134012]
Impacted versions: v16

I see that for Sale Order states modifiers you've used constants, but maybe using property methods would be easier to override

**Comment by vava-odoo** [comment]
Hi @razvanioan 
Thanks for your feedback.
I don't see why there is a need for that. All the logic in sale is based on this list of states, so it would not be easy to change it.
Furthermore, you can always add states in a custom inherited module with `selection_add`, and/or re-define the field as you wish.
Cheers

**Comment by razvanioan** [comment]
Hi @vava-odoo 

I know I can add new states (which I did) and I also wanted to add my new state in the READONLY_FIELD_STATES
How can I do this easily ?
Using model @property would be much more easy to override than a constant

**Comment by vava-odoo** [comment]
You can probably extend the dictionary by importing `READONLY_FIELD_STATES` in your module.
I agree it would be cleaner with a property, but this won't be changed in stable versions. 
Also, this variable was dropped for 17, so I don't think we'll do anything here.
