### ISSUE TITLE
Odoo Chain location not working | fail core route

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#13411]
Impacted versions: 9, saas 12

Steps to reproduce:
3 warehouse
I had configured routes locations
A -> B
B -> C
C -> Customer location 
than set route in a product
create sale order and generate delivery
Its generate default one, not use custom or chain location(not automated)

even route on sale order not effective working.

Current behavior:
Chain location, custom route not working

Expected behavior:
Delivery order should be created with each moves as define in route

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
This configuration is working fine. And applying pull rule on SO line is also working fine. Please review your data.

Regards

**Comment by tejastank** [comment]
@sle-odoo thank for quick response, its really 2018 ;) You guys awesome...

**Comment by Yenthe666** [comment]
@tejastank it was a pleasure helping you, you're welcome!
