### ISSUE TITLE
[9.0] Wrong amount due with taxes included

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#13422]
**Impacted versions:** 9.0c

**Steps to reproduce:** 
- Create a product and assign a tax to would be included in price.
- Create an invoice.
- Validate it.

**Current behavior:**
- The invoice shows the total price right. However when you click on validate it will show the amount due and it shows without the taxes.
- When you click to pay the invoice it picks this wrong amount due.

**Expected behavior:**
- Amount due should show the the total price.
- When you do a payment to the invoice it should pick the real amount due.

**Comment by juniorkid** [comment]
My problem occurs by set account type of tax to be payable.
My solution is change account type of tax to be current liabilities, cancel wrong invoice and validate it again. I think u will get correct amount due.

**Comment by edsersolis** [comment]
This is no the behavior anymore. Closing.
