### ISSUE TITLE
The latest two Odoo nightlies are missing

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#13424]
There are no new builds available after 6th September 2016.

Impacted versions: 8.0 & 9.0

Steps to reproduce: Go to http://nightly.odoo.com/9.0/nightly/deb/ and try to find `odoo_9.0c.20160908_all.deb` to download. Same with rpm, exe, tar.gz, and version 8.0.

Current behavior: The file doesn't exist.

Expected behavior: The file, along with `odoo_9.0c.20160907_all.deb` should exist.

**Comment by aab-odoo** [comment]
Hello,
Thanks for your feedback, there was an issue with our building script.
The packages are being built at the moment.
Regards
