### ISSUE TITLE
[8.0] Report Sales Analysis Bug

### ISSUE THREAD

**Issue by JordyRitzen** [odoo/odoo#13425]
**Impacted versions:**
V8

**Steps to reproduce:**

1. - Open Reporting/Sales Analysis
2. - Select "Shipped" as filter of "Undefined"
3. - Click on the download button

**Current behavior:**
JSON Error

on _Chrome_:
![image](https://cloud.githubusercontent.com/assets/15804808/18340244/34f01640-75a4-11e6-8286-f65b7a43612f.png)

on _Firefox_:
![image](https://cloud.githubusercontent.com/assets/15804808/18340219/0c06bd88-75a4-11e6-95d8-396c3ea307ff.png)

**Expected behavior:**
Download from the export file

**Comment by JKE-be** [comment]
T probably like **T**raceback...

Please provide logs with detail of the traceback.

thanks

**Comment by JKE-be** [comment]
Thanks for the reporting...
It has been fixed.

**Comment by JordyRitzen** [comment]
Thanks for the fix in the Odoo codebase.
We've applied the patch a day after you've made the commit and it's working.
