### ISSUE TITLE
[9.0e] UTM : click count failing behind reverse proxy

### ISSUE THREAD

**Issue by cdavbb** [odoo/odoo#13423]
**Impacted versions:**
9.0e

**Steps to reproduce:**
Create a tracked link, open it from several public IPs when serving behind a reverse proxy.
Check click count result.

**Current behavior:**
Count is stucked to 1 and the IP associated to the click is the one of the reverse proxy. I think this is the problem. No error could be seen in logs.
Tracked link form :
![image](https://cloud.githubusercontent.com/assets/12343017/18338797/be0c8854-759b-11e6-99f6-78332e1194c5.png)
Number of clicks stats :
![click count](https://cloud.githubusercontent.com/assets/12343017/18338729/55fea3a0-759b-11e6-8985-6348bff64967.png)

**Expected behavior:**
I suppose it should not use the reverse proxy IP in order to count correctly.

**In addition:**
Proxy_mode is set to True in openerp.conf. Here is the part of the nginx conf file for the reverse proxy

```
server {
        listen 443;
        server_name example.com;

        error_log /var/log/nginx/example/errorgcup.log;
        access_log /var/log/nginx/example/accessgcup.log;

        add_header Strict-Transport-Security "max-age=31536000";

        ssl on;
        ssl_certificate /etc/nginx/ssl/example.pem;
        ssl_certificate_key /etc/nginx/ssl/example.key;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;keepalive_timeout 60;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
        proxy_buffers 16 64k;
        proxy_buffer_size 128k;
        client_max_body_size 25M;

        include /etc/nginx/global/*;



        location / {
                proxy_pass http://192.168.1.8:8069;
                client_max_body_size 25M;
        }
```

Cannot figure out where lies the problem. I have seen a lot of problems regarding the logs not showing real IP when using a reverse proxy. But I already solved this problem and it has no effect on utm tracking.

Thanks

**Comment by cdavbb** [comment]
Ok, finally found the solution, system parameters were not set properly. Those should be set to point the appserver addres, not the domain pointing to the reverse proxy : 

- 	web.base.url set to address or odoo server domain http://example.com:8069
-	web.base.url.freeze to True, in order to make sure it will not be overiwritten (not shure if it is usefull in 9.0e)

**Comment by lukebranch** [comment]
@cdavbb ,

I am still experiencing this issue in Odoo 9.0c with Nginx reverse proxy. Link tracking and click tracking for mass mailing and link tracker is only showing either a 1 or a 0, there is no click count as there should be.

web.base.url for me is set to:

http://mydomain.com

and web.base.url.freeze is set to:

True

and link and click tracking are only showing a 1 or a 0 value, no matter the number of different subscribers, behind different IP's have clicked a link it seems to only show either clicked (1) or unclicked (0).

@Yenthe666 

Sorry to bother you with this, I think perhaps this is a deployment issue on my end, however I am unable to confirm this on the runbots as they are not behind a reverse proxy. Have you encountered any other reports with link tracking/click tracking not functioning as intended behind a reverse proxy (specifically behind Nginx)?

**Comment by cdavbb** [comment]
@lukebranch 

I know this is not completly satisfying, but for me the issue was solved using the adress of the odoo server itself as web.base.url (in my case a domain name, for instance http://example.com:8069). Not the one one of the reverse proxy.

Without doing this, I was not able to make UTM click count working properly as it was detecting all incoming request with the same IP. IP of my reverse proxy.

I tried everything I think possible in Nginx conf file without succeeding to change this behaviour. That is why I finally changed web.base.url.

I know that Nginx is capable of forwarding final client's IP, and in theory, that odoo is capable to read it with proxy mode on, but it does not seem to work for UTM.

**Comment by lasley** [comment]
Did you set the following in your Nginx configs? You may have to alter some for your env, but this should set you on the right track

```
        port_in_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Front-End-Https On;
        proxy_set_header X-Real-IP $remote_addr;
```

**Comment by cdavbb** [comment]
Considering my degree of comprehension, the key line is
`proxy_set_header X-Real-IP $remote_addr;`

But even with this enabled, it did not work for me (assuming odoo's proxy mode activated)

**Comment by lukebranch** [comment]
@lasley ,

Thanks for the help, I really appreciate it mate!

I've tried this, but i'm in the same boat as @cdavbb i'm only getting 1's or 0's (either clicked or unclicked, no click counts). In my environment it's worth noting that i'm using this OCA module for dbfiltering:

https://github.com/OCA/server-tools/tree/9.0/dbfilter_from_header

Here's my nginx configuration:
https://gist.github.com/lukebranch/24ce7710feda5d1c78b0821d86edd38e

Here's my odoo configuration:
https://gist.github.com/lukebranch/27e28805e3cadc138571353e2e701c17

I've been scratching my head with this issue for awhile now, and while i'm pretty sure it's down to a deployment issue, I cannot for the life of me figure out what i'm doing wrong.

**Comment by lukebranch** [comment]
@lasley @cdavbb ,

I am able to reproduce this behaviour on the runbots, as the runbots are only producing either a 1 or a 0 for the link tracker and are tracking only localhost (127.0.0.1) IP address. I believe this is because the X-Forwarded-For header directive is not there as there is no proxy in front of it.

Regardless I have never been able to get this feature working, however perhaps I am fundamentally misunderstanding the way it works, or perhaps the deployment method I am using is wrong in some way. My setup is proxied to port 80 so instead of mydomain.com:8069 it is just mydomain.com.

I am using proxy_mode = True and have all the proxy_set_header nginx directives setup correctly and I do not believe using dbfilter_from_header is causing this issue.

I will review the deployment docs on Odoo 9.0 again just to make sure I am not missing something and then create a new issue for this if I still have this issue.

**Comment by lukebranch** [comment]
@lasley @cdavbb ,

Thank you both for your patience with me. I finally figured out the cause of the issue was a missing nginx directive:

proxy_redirect off;

inside:

    location / {
    <i>proxy_redirect off;</i>
    proxy_pass http://odoo8swi;
    }

    location /longpolling {
    proxy_pass http://odoo8swi-im;
    }

**Comment by cdavbb** [comment]
@lukebranch ,

Thanks for sharing your solution, but moving `proxy_redirect off` did not help in my case. Could you please share your full nginx conf file ?

**Comment by lukebranch** [comment]
@cdavbb ,

Sure, I will update this thread with my full nginx config later today.

Are you only seeing your reverse proxy IP (ie. 127.0.0.1)?

**Comment by cdavbb** [comment]
@lukebranch , thanks. Yes I see the local IP of my reverse proxy (in my case 192.168.1.4)

**Comment by davidberardozzi** [comment]
@lukebranch ? Could you share your conf file ? thanks

**Comment by lukebranch** [comment]
@davidberardozzi ,

Sorry i've taken so long to reply on this thread!

I'll post all my nginx config files shortly in gists and come back here with some links so you can check it out.

What I would suggest as well is perhaps you should also share your nginx config here as well in gists or similar. This might help us to compare notes and troubleshoot more effectively.

Looking at your config excerpt in the opening post of this issue is there a reason you are not using localhost (ie. 127.0.0.1) in place of your 192.168.1.4? Do you have Odoo and Nginx running on different machines/IP's?

**Comment by lukebranch** [comment]
@davidberardozzi ,

Here's a gist for my nginx config file (/etc/nginx/sites-available/example.com):
https://gist.github.com/lukebranch/d6e81fb484f2eb5642084d30fc7f707b

Here's a gist for my nginx config file (/etc/nginx/nginx.conf):
https://gist.github.com/lukebranch/4f1c3687877b500c2fe9e2e4cc5a909a

It's worth noting that in my setup i'm using the OCA module dbfilter_from_header in my odoo-server.conf file:
https://github.com/OCA/server-tools/tree/10.0/dbfilter_from_header

This needs to be added as an extra line in your odoo-server.conf file or equivalent:
server_wide_modules=dbfilter_from_header

I believe in your case you may just need to make use of the following extra directives in your example.com config:

```
upstream odoo8example {
server localhost:8069 weight=1 fail_timeout=3000;
}

upstream odoo8example-im {
server localhost:8072 weight=1 fail_timeout=0;
}

    location / {
    proxy_redirect off;
    proxy_pass http://odoo8example;
    }

    location /longpolling {
    proxy_pass http://odoo8example-im;
    }
```

and delete:
```
        location / {
                proxy_pass http://192.168.1.8:8069;
                client_max_body_size 25M;
        }
```

to get things working as intended. Please feel free to ping me if you're still running into issues after these changes.
