### ISSUE TITLE
[9.0]website editor does only work in developer mode (?debug) anymore, I'm lost!

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#13434]
Impacted versions: Version 9.0c-20160629 (Community Edition) 

Steps to reproduce:

Current behavior:

I have a database with the Odoo theme "Real estate" installed, where since a couple of weeks I'm only able to edit the website when having activated the developer mode. But the developer mode gets deactivated everytime when changing the website page and it is not possible to activate it for certain pages (edit blog posts for example).
Without activated developer mode the website customize menu is restricted to the first 3 entries (see screenshot below) and clicking on any menu item on the website has no effect.
I have no log entries and nothing in the browser console which would give the slightest hint, just nothing.
I did update all website related modules, I did uninstall all website related modules to no avail. I did even uninstall the website builder itself and reinstall it. After that I got an empty website with the default theme installed, but still the same behaviour. I'm not able to identify the start of the problem and meanwhile the business in the backoffice was going on, so I can not go backwards with restoring backups so far (several weeks).
Other databases are working flawlessly.
How can I identify the problem? How can I find a solution without loosing the complete database?

Expected behavior:

Video/Screenshot link (optional):

![selection_310](https://cloud.githubusercontent.com/assets/1814941/18352188/ad6114c4-75dd-11e6-9540-b22527973b02.png)

**Comment by dansanti** [comment]
are you on child language? , because if you are on child language, you can't edit template, only on default language seted

**Comment by treviser** [comment]
It does not matter which language I've selected nor which default language I have defined in the browser.

**Comment by JKE-be** [comment]
@treviser can you check the rpc done to see the customize_show view... there are maybe one hint inside ?

**Comment by treviser** [comment]
@JKE-be Thanks for your reply. How can I do that?

**Comment by JKE-be** [comment]
Under chrome, open network console (F12 or inspect element), filter on customize_template

![image](https://cloud.githubusercontent.com/assets/4848797/18514388/ba22f9da-7a91-11e6-8841-ebbdad5d1a37.png)

You see in the result all the submenu that should be available...

If you don't have it, it probably due to a crash in JS code, but if it is the case, you will have an error message in the console.

**Comment by treviser** [comment]
I have no results for customize and also no errors in the console...
![selection_311](https://cloud.githubusercontent.com/assets/1814941/18515213/dc5a5306-7a94-11e6-9e24-8da845c995de.png)
![selection_312](https://cloud.githubusercontent.com/assets/1814941/18515218/e017aa16-7a94-11e6-8251-bdf83b0c86e8.png)

**Comment by JKE-be** [comment]
strange, can you check that you have the website.editor.js file loaded in the assets ...
Because this code should be there: 

```javascript
website.TopBarCustomize = Widget.extend({
    events: {
        'mousedown a.dropdown-toggle': 'load_menu',
        'click ul a[data-view-id]': 'do_customize',
    },
```

Is you website available from outside ?

**Comment by treviser** [comment]
https://www.flohmarkt-zug.ch

**Comment by treviser** [comment]
![selection_313](https://cloud.githubusercontent.com/assets/1814941/18515682/70b759c6-7a96-11e6-9c5a-95f000f1ab17.png)
Do you mean this?

**Comment by JKE-be** [comment]
Can you temporary disable cloudflare cdn to test that it not just th version in cache that is wrong ?

And Yes inside this file,  could you check that the code TopBarCustomize=Widget.extend({events is present

**Comment by treviser** [comment]
I already did deactivate Cloudflare and did a CTRL R in the browser, to no avail.

**Comment by treviser** [comment]
![selection_314](https://cloud.githubusercontent.com/assets/1814941/18516094/f780a3c6-7a97-11e6-84ea-1ecf428d8156.png)

**Comment by JKE-be** [comment]
Can you confirm, que this theme with a clean database work like a charm ?

**Comment by treviser** [comment]
NO! I can not confirm it. I did change the theme of another database on the same server, at first it worked, after an update of the theme real estate and theme common and a few clicks on the editor, it stopped working.

**Comment by treviser** [comment]
I did restore a backup of the database on my test server dated 21.07.2016 and this one works, if that helps.

**Comment by treviser** [comment]
On the other database I did uninstall theme real estate, theme monglia and then did reinstall the original theme, and now this website is also corrupt and does not work anymore!

**Comment by JKE-be** [comment]
can you provide editor access on a copy  ?

**Comment by treviser** [comment]
yes, no problem, how could I send it to you?

**Comment by JKE-be** [comment]
jke at odoo dot com

**Comment by treviser** [comment]
Email sent.

**Comment by JKE-be** [comment]
For poeple who have the same issues...
For information, it has been fixed by...
 removing rocketjs option from cloudfare -> Load js in async and don't display error
 Once JS load by browser, we see that error was in the minify of one JS file.
 Once Cloudflare disabled, there was no more error.

 Don't forget to clear cloudflare cache, and regenerate the assets (update of a module which one touch assets) or delete attachment ...assets_...

Treviser, if all is ok for you now, can we close the issue ?

**Comment by treviser** [comment]
Yes, thank you very much for your efforts and help.
Just to be clear on your 3rd point: it is not necessary to disable cloudflare completely, but to disable the minify option in the "Speed" section.
