### ISSUE TITLE
Replace float type for money with decimal (with explanations)

### ISSUE THREAD

**Issue by artaf** [odoo/odoo#13438]
Impacted versions: at least 9.0
Steps to reproduce: n/a
Current behavior: float type is used for monetary units
s=0
for i in range(0,1000000): s+=float(0.1)
print s
The code gives slightly higher than 1,000,000. The explanation is given here Floating Point Arithmetic: Issues and Limitations https://docs.python.org/2/tutorial/floatingpoint.html

I understand that there is almost no case when imprecise float is material but still it can be material. As for me it is really strange idea to use in accounting software imprecise float type for money.

Expected behavior: decimal type must be used
Video/Screenshot link (optional): n/a

**Comment by pedrobaeza** [comment]
This change in the data types has been discussed a lot of times and there are no intentions for now in changing it. Any way, this is constantly being considered and your comments are taken into account for sure. Closing this for triaging things.
