### ISSUE TITLE
[BUG][web_gantt] Gantt chart does not sort cells by date within a single grid tile

### ISSUE THREAD

**Issue by Sibert-Aerts** [odoo/odoo#134345]
Impacted versions: 15.0 and 16.0, possibly earlier.

Steps to reproduce: Create two tasks on the same day, but starting on different hours. Then zoom out to week view so they both take up the same grid space. 

Current behavior: Regardless of how you change the starting times, they'll always keep the default task order within the grid square.

Expected behavior: The task that's earlier on the day should always show up above the other.

**Link to impacted code:**
https://github.com/odoo/enterprise/blob/16.0/web_gantt/static/src/js/gantt_row.js#L225
(This line is unchanged since v13.0)
The line sorts the cells by property "startDate", which is of type Moment and does not work with regular comparison operators, so this sortBy has no effect on the list of cells.

**Comment by hubvd** [comment]
The issue has been fixed
