### ISSUE TITLE
context_today incorrectly calculate the date if user's preference timezone is set?

### ISSUE THREAD

**Issue by niecw** [odoo/odoo#13440]
Impacted versions: 7.0, 8.0, 9.0, master

Steps to reproduce:
The following is the code of context_today for new API (from https://github.com/odoo/odoo/blob/master/odoo/fields.py#L1423).  The old API code is very similar:

```
    def context_today(record, timestamp=None):
        today = timestamp or datetime.now()
        context_today = None
        tz_name = record._context.get('tz') or record.env.user.tz
        if tz_name:
            try:
                today_utc = pytz.timezone('UTC').localize(today, is_dst=False)  # UTC = no DST
                context_today = today_utc.astimezone(pytz.timezone(tz_name))
            except Exception:
                _logger.debug("failed to compute context/client-specific today date, using UTC value for `today`",
                              exc_info=True)
                return (context_today or today).strftime(DATE_FORMAT)
```

IMHO, if `timestamp` is not given - which is the case most of the time since `context_today` is used a lot in defaults - the code `today = timestamp or datetime.now()` will set `today` to current timestamp at the server's timezone (for example, 'Asia/Bangkok' (GMT+8)).

If the user has her/his timezone set (say to 'Asia/Bangkok' (GMT+8) - or any other timezone, I used the same timezone to simplify the example), then the code block within `if tz_name` will be executed.  The part `today_utc = pytz.timezone('UTC').localize(today, is_dst=False)` will set `today_utc` to the same timestamp as `today` but with the timezone removed and changed to 'UTC'.  Meaning that if `today` is 9 Sep 2016 17:00, then `today_utc` will be 9 Sep 2016 17:00 at UTC (although it should be 9 Sep 2016 10:00 AM UTC in actuality).

The code `context_today = today_utc.astimezone(pytz.timezone(tz_name))` will make `context_today` to be 10 Sep 2016 00:00 AM and returned as 10 Sep 2016, whereas the actual timestamp is 9 Sep 2016 17:00 or 9 Sep 2016.

Current behavior:

A user that has Timezone set in the Preference will have context_today set to the server's timezone + user's Preference Timezone instead of the user's Preference Timezone only.

Expected behavior:

context_today should be set as per user's Preference Timezone only

Question in Odoo Forum: https://www.odoo.com/forum/help-1/question/is-something-strange-with-context-today-or-i-misunderstood-something-108024

Video/Screenshot link (optional): N/A

**Comment by pedrobaeza** [comment]
The problem is that you have to configure your server always with UTC. It's a deployment question.

**Comment by yostashiro** [comment]
> you have to configure your server always with UTC.

I'm curious to know if it is a widely known practice.  I wasn't able to find the relevant documentation to state this.

**Comment by pedrobaeza** [comment]
I don't know if there's documentation, but I have only worked that way.
