### ISSUE TITLE
Online Bidding feature like Online Proposals in sales Quotation

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#1344]
Online Proposals in sales quotation is really a nice feature and its implemented perfectly.
if the same concept using for purchase bidding also, then many big companies will implement odoo in their procurement division only for this feature.

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thanks for the feedback and suggestion and my apoligies for the very late response.
As this is labelled wishlist it will keep popping up, even after closing it.

Regards,
Yenthe
