### ISSUE TITLE
Nightly builds are down since 2/September

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#13442]
Check http://nightly.odoo.com/master/nightly/src/

**Comment by JKE-be** [comment]
@sle-odoo

**Comment by Yenthe666** [comment]
@sle-odoo and @odony the nightly is still down.

**Comment by sle-odoo** [comment]
[we are working on it](https://github.com/odoo-dev/odoo/commits/saas-13-packaging-sle)
