### ISSUE TITLE
[10.0] Fleet Vehicle Costs delete problem

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#13441]
Impacted versions: 10

Steps to reproduce: Fleet Vehicle Costs are not deleted after deleting the linked cost: Fuel or Service.

Current behavior:

Expected behavior: After deleting a fuel or service, the cost linked to it should be deleted automatically

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @elperrofarelo,

Thanks a lot for your report! I've just tested this and the costs related to the fuel or service are not deleted.
This is also the case in Odoo V9 however.

Example before deleting anything:
![image](https://cloud.githubusercontent.com/assets/6352350/19034223/a6302b5c-8962-11e6-9728-6784c946ed86.png)

After deleting the fuel costs:
![image](https://cloud.githubusercontent.com/assets/6352350/19034240/bebfa346-8962-11e6-93ed-87b5abe57acc.png)

@mart-e could you verify if this is a bug or not? I'm not completely sure. If so, can you assign somebody please?

Regards,
Yenthe

**Comment by mart-e** [comment]
Actually it's the inverse relation, if you delete a cost, you will delete the fuel log. Not sure if we should delete this way too (or restrict the delete)
@csnauwaert what do you think?

> Impacted versions: 10

allow me to doubt that, it is not released yet and definitely was not 24 days ago :wink:

**Comment by elperrofarelo** [comment]
Hi,
According to my opinion it should go in both ways to avoid rest of logs without relation to the costs. If you delete the cost, the fuel log must be deleted and the opposite as well if you delete the fuel log, the cost should be erased to have a clean cost calculation 
Regards

**Comment by Yenthe666** [comment]
@csnauwaert could you answer the question from @mart-e? It is still relevant.

**Comment by elperrofarelo** [comment]
Same üroblem as well in Odoo V11

**Comment by mart-e** [comment]
The fuel logs are already deleted when you delete a costs.
I do not think we should delete it the other way around, it is good to keep the history of the costs.
