### ISSUE TITLE
[9.0/8.0/saas-6]BUG in filter recurrent event

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#13447]
Impacted versions:
saas-6
Steps to reproduce:
1. create a recurrent event.
![image](https://cloud.githubusercontent.com/assets/1176173/18407506/095318f0-7745-11e6-9fa2-d6e17621ce8f.png)

![image](https://cloud.githubusercontent.com/assets/1176173/18407505/02e39472-7745-11e6-9903-91cbf13e7a4f.png)
2. add a filter, filter by stop_datetime less then a dattime.
![image](https://cloud.githubusercontent.com/assets/1176173/18407524/4fcbb756-7745-11e6-97ed-0d0289b5a7e5.png)

Current behavior:
The result is wrong.

Expected behavior:
The result should follow the filter. 
P.S When I use stop field instead of stop_datetime to filter. The result is currect

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
hello, thanks for the reporting

stop_date, stop_datetime are technical field to compute stop date.

```python
    def get_recurrent_ids(self, domain, order=None):
        ...
        for arg in domain:
            if str(arg[0]) in ('start', 'stop', 'final_date'):
```

Stop field is the right alternative until a fix is proposed ... PR is welcome :)

**Comment by joshuajan** [comment]
I afraid `Stop` field does not work also. It will make current event cant`t be search.
```python
        for arg in args:
            new_arg = arg
            if arg[0] in ('stop_date', 'stop_datetime', 'stop',) and arg[1] == ">=":
                if self._context.get('virtual_id', True):
                    new_args += ['|', '&', ('recurrency', '=', 1), ('final_date', arg[1], arg[2])]
            elif arg[0] == "id":
                new_arg = (arg[0], arg[1], get_real_ids(arg[2]))
            new_args.append(new_arg)

        if not self._context.get('virtual_id', True):
            return super(Meeting, self).search(new_args, offset=offset, limit=limit, order=order, count=count)

        # offset, limit, order and count must be treated separately as we may need to deal with virtual ids
        events = super(Meeting, self).search(new_args, offset=0, limit=0, order=None, count=False)
        events = self.browse(events.get_recurrent_ids(args, order=order))
```

1. It is only work for `stop` or `stop_datetime` or `stop_date` in the domain, and the operation is `>=`,  how about `<` or `<=`,  `>`?

```python
                for arg in domain:
                    if str(arg[0]) in ('start', 'stop', 'final_date'):
                        if (arg[1] == '='):
                            ok = r_date.strftime('%Y-%m-%d') == arg[2]
                        if (arg[1] == '>'):
                            ok = r_date.strftime('%Y-%m-%d') > arg[2]
                        if (arg[1] == '<'):
                            ok = r_date.strftime('%Y-%m-%d') < arg[2]
                        if (arg[1] == '>='):
                            ok = r_date.strftime('%Y-%m-%d') >= arg[2]
                        if (arg[1] == '<='):
                            ok = r_date.strftime('%Y-%m-%d') <= arg[2]
                        pile.append(ok)
                    elif str(arg) == str('&') or str(arg) == str('|'):
                        pile.append(arg)
                    else:
                        pile.append(True)
```
2. I think it is an mistake. The `strfitime('%Y-%m-%d')` will drop the time, only compare the day

**Comment by Yenthe666** [comment]
Hi @joshuajan ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). I believe this was handled in V9 now too.
If you can still reproduce this issue on Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
