### ISSUE TITLE
[8.0] 0,00 price shown on /shop if variants and pricelist

### ISSUE THREAD

**Issue by paolovalier** [odoo/odoo#13459]
**Impacted versions**: 8.0 on runbot

**Steps to reproduce**: take a product and set at least a variant, make a pricelist and set price fot that variant, assign this pricelist to yourselfe

**Current behavior**: log in the website, go to the page domain.com/shop and you'll see the default price strikethrough and the current price that is 0,00 and not the one you setted on pricelist.
(in the single-product page the price is the one assinged with the pricelist so the problem is just on /shop )

**Expected behavior**: it should be shown the price for the first variant (this is the default behaviour without pricelist) and not 0,00 

**Screenshot link** (optional): ![cattura](https://cloud.githubusercontent.com/assets/11443924/18463534/26edac02-798b-11e6-89da-94f21c519af1.PNG)

**Comment by Yenthe666** [comment]
Hi @paolovalier,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
