### ISSUE TITLE
[8.0] Can't directly navigate to selected customer form web page

### ISSUE THREAD

**Issue by kodemi** [odoo/odoo#1346]
How to reproduce:
1. Go to Sales -> Customers and open form view for any (but first) customer.
2. Copy page url and navigate to it in new browser tab.

*What is expected:*
The same customer page. 

*What is in reality:*
Page for first customer is opened.

This wrong behavior I can see only for Customer model.

**Comment by sle-odoo** [comment]
This is working in >= 8.0 so i'm closing.
Regards.
