### ISSUE TITLE
[odoo website] Cannot view the previously submitted issue tickets

### ISSUE THREAD

**Issue by atchuthan** [odoo/odoo#13460]
Impacted versions:
https://www.odoo.com/

Steps to reproduce:
Login with the previously submitted user and view the issues section.  It says "There are currently no issues for your account."
My Account -> Your issues

**Comment by JKE-be** [comment]
I have just now, and I see your 3 previous tickets.

Somes fixes has been applies yesterday....

**Comment by atchuthan** [comment]
thanks
