### ISSUE TITLE
Odoo Quotations Template Layout Issues

### ISSUE THREAD

**Issue by Soyuz-Tec** [odoo/odoo#13475]
Impacted versions:
V9 Enterprise
Steps to reproduce:
![issue1](https://cloud.githubusercontent.com/assets/20989718/18512254/deaf9ede-7aa5-11e6-8cbb-136f05168235.png)

Create multiple quotations with multiple lines of data

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
PDF's attached in this report

**Comment by Yenthe666** [comment]
Hi @Soyuz-Tec,

Thanks a lot for your bug report.
I've just tried this but it works fine (now). I'm closing this as I cannot reproduce it anymore.
If you can still reproduce it on the latest Odoo code then don't hesitate to reopen this bug report and give more feedback.

Regards,
Yenthe
