### ISSUE TITLE
Cannot change crm.segmentation’s state field

### ISSUE THREAD

**Issue by jianjian001** [odoo/odoo#1347]
The header of contacts segmentation's  form view (sales - configuration-  contacts segmentation) which is named crm.segmentation.form may be a problem.
when i click the button to ’Compute Segmentation‘, the function process_start set {'state':'running'}， and then this function Call another function process_continue，process_continue set 'state':'not running' back. state‘s  default value is 'not running'.
the problem is : how can I set the state to ’running‘.

**Comment by Yenthe666** [comment]
Hi @jianjian001,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
