### ISSUE TITLE
[8.0] Right click on any Menu => Open Link in New Tab => all Odoo tabs painfully slow

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#13486]
### Impacted versions:
8.0
Firefox
### Steps to reproduce:
Use non-local Odoo installation (non-localhost). Use one over the web.
- Navigate to Sales menu > Sales Orders. [tab 1]
- Using Right click, open Product Variants twice in 2 new tabs. [tab 2] + [tab 3]
- In one of the new tabs (2 or 3), use Right click to open Sales Orders in a new tab. [tab 4]
- While this 2nd Sales Order tab is loading, in [tab 1] click on Sales Order menu.

### Current behavior:
Since [tab 4] both Sales Order tabs ([tab 1] + [tab 4]) are working slow, showing Loading for every small action, including data loading with AJAX. Try opening different Sales Orders in [tab 1] and [tab 4] at the same time, and switching back to Sales Orders list, then open other Sales Orders, and switch back to SO list etc. If you do this in different tabs simultaneously ([tab 1] + [tab 4]), you see Loading on both tabs, just if the tabs were conflicting with each other.

I cannot reproduce this behaviour on [runbot 8.0](http://171853-8-0-1da79b.runbot5.odoo.com/?db=171853-8-0-1da79b-all), but I do observe it on our 2 different production instances w/ different modules installed. So maybe the 5x SOs of the test runbot is too small of a data for this effect to reveal itself. Note that it is not a problem of a slow server/connection/module: any number of tabs work fast as long as we start with a blank tab and navigate to the menus naturally, not using the right-click=>open_in_new_tab. So it is definitely the right-click=>open_in_new_tab that causes the performance drop down.

**Performance comes back to norm** once we close the tabs opened by right-clicking=>new_tab.
### Expected behavior:
Should work as fast as if we open new empty tabs and navigate to the required menus manually, not by right-clicking on menu in the current tab.
______________________________________________
Same [question](https://www.odoo.com/forum/help-1/question/8-0-right-click-on-any-menu-open-link-in-new-tab-makes-all-odoo-tabs-painfully-slow-108334) on Odoo Help Forum.

**Comment by JKE-be** [comment]
Hello, 

Not really a bug, but one limitation in v8, that has been improved/removed in v9.

It was due to restriction in the browser to make more than x  connections simultaneous (http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/)

In V9, the pooling (live chat) has been completely rewritten to use local-storage between all tabs instead of 1 connection by tab.
