### ISSUE TITLE
[8.0] Run Schedulers error  'Registry' object has no attribute 'db'

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#1348]
create a product with supplier, orderpoints defined.
run sched.
**Error:**

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/oerp/openerp/addons/procurement/wizard/schedulers_all.py", line 48, 
in _procure_calculation_all
    new_cr = self.pool.db.cursor()
AttributeError: 'Registry' object has no attribute 'db'

```

**Comment by Yenthe666** [comment]
Hi @mohamedhagag,

I tried to reproduce it too (just like jco-odoo) and couldn't reproduce it either.
I'm closing this issue as there has been no response in almost three years. If you still face this on the latest source code please reply back here and I'll reopen it.

Regards,
Yenthe
