### ISSUE TITLE
[9.0] Label on Invoices not showing when option Group of Taxes is selected

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#13482]
Impacted versions: 9.0

Steps to reproduce:
1. Go to Accounting -> Configuration -> Accounting -> Taxes
2. Open or Create any tax.
3. Change field Tax Computation to Group of Taxes
4. Click on Advanced Options tab
5. No field for Label on Invoices is shown

Current behavior:
When printing, the value that the localization has on this field is the one that is going to show, some localizations have a coding there which end customer may not understand.

Also options to change this value are not open to accountants and customer, who at the end, are the ones that are going to manage this part of the platform.

To change the value in this field you either have to:
- Select any other value on Tax Computation field, input the label text in the Label on Invoices field, go back and change the Tax Computation to Group of Taxes.
- Edit the form and create of copy of the line that contains the description field, remove the invisible attribute and comment the original line with the description field.
- Or simply edit the original line containing the description field and delete the invisible attribute.

Expected behavior:
- Show the Label for Invoices field at all times.

Video/Screenshot link (optional):

**Comment by shashishekhar1001** [comment]
Same thing happening in Odoo v 11.0. I hope this bug is fixed.
