### ISSUE TITLE
[BUG][I18N] base: field state_id string State

### ISSUE THREAD

**Issue by ngochung207** [odoo/odoo#134945]
Impacted versions:

![image](https://github.com/odoo/odoo/assets/11542778/b204f99d-862e-4ae8-bfea-f8c4efd2cee1)

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @ngochung207 
I don't understand your issue. Is that a translation issue? If yes, please correct it on [Transifex](https://explore.transifex.com/odoo/) as translations are handled there.
Cheers

**Comment by vava-odoo** [comment]
Perfect, thank you for your help on this.
