### ISSUE TITLE
Empty screen in clean installation on windows 10

### ISSUE THREAD

**Issue by vvenegasv** [odoo/odoo#13498]
Impacted versions:
9.0

Steps to reproduce:
1.- Have a WIndows 10 enviroment
2.- Create an empty database in AWS RDS
3.- Download source code from GitHub
4.- Install Python 2.7.12
5.- Run this command Python odoo.py --db_host VALIDURL.us-east-1.rds.amazonaws.com -r USER -w PASSWORD -d DATABASE --addons-path=addons

Current behavior: 
Show an empty screen, with no menu

Expected behavior:
Show lateral and superior menu

Video/Screenshot link (optional):
![odoo-empty](https://cloud.githubusercontent.com/assets/9702936/18565954/4ef506d0-7b68-11e6-861b-2b2a198e407d.png)
http://stackoverflow.com/questions/39519530/how-run-odoo-9-0-from-source-code-in-windows-10

**Comment by nicknomo** [comment]
You need to install Nodejs and use npm to install less

https://nodejs.org/en/

**Comment by Haven1999** [comment]
can any one solve this, please?

**Comment by VR-Architect** [comment]
I install v11 packaged on Windows 10 with the same ending issue.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions (and don't install it on Windows if you want to be serious with this). Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
