### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [odoo/odoo#134948]
Impacted versions:

Steps to reproduce: Scroll to footer section and see twitter old logo

Current behavior: Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Expected behavior: Twitter logo should be changed to X

Video/Screenshot link (optional):

<img width="960" alt="Screenshot 2023-09-10 081225" src="https://github.com/odoo/odoo/assets/91591901/f9298690-2093-4e43-b127-713b12118ded">

Support ticket number submitted via odoo.com/help (optional):

@gdrius 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by kevin11andrew** [comment]
@lalitkumawat1m  Are you currently working on this? If not, could I take this up?

**Comment by neoneddy** [comment]
@kevin11andrew  I'd say go for it.  At the very least I'd love a short term solution.

**Comment by vava-odoo** [comment]
Icon was changed in all stable versions
