### ISSUE TITLE
[9.0] stock_move missing  picking_type_id on extra received amounts on PO shipment

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#13504]
Impacted versions: 9.0  #others not tested

Steps to reproduce:
  make a PO with at least one product.
  Confirm this order
  click shipment
  edit record with pencil
      set the done amount bigger then ToDo (some extra received)
  Validate

Current behavior:
  2 rows generated at stock_move: 1 for original amount and 1 for extra amount
  On the row for extra amount: picking_type_id, origin and warehouse_id fields are empty
Expected behavior:
  picking_type_id,  and  maybe origin and warehouse_id fields filled as the move of the normal ordered amount

original code here where fields are prepared:
stock/stock.py: _prepare_values_extra_move(self, cr, uid, op, product, remaining_qty, context=None):

```
    res = {
        'picking_id': picking.id,
        'location_id': picking.location_id.id,
        'location_dest_id': picking.location_dest_id.id,
        'product_id': product.id,
        'procurement_id': proc_id,
        'product_uom': uom_id,
        'product_uom_qty': qty,
        'name': _('Extra Move: ') + name,
        'state': 'draft',
        'restrict_partner_id': op.owner_id.id,
        'group_id': picking.group_id.id,
        }
    return res
```

**Comment by pedrobaeza** [comment]
That's the normal behavior: the extra quantity should be allocated in a new extra move for tracking purposes. If you want this behavior, change the qty in the PO instead.
