### ISSUE TITLE
[8] ir_mail_server.py update to correct problem with SMTP connections

### ISSUE THREAD

**Issue by tkontogi** [odoo/odoo#13505]
Impacted versions:

8.x

Steps to reproduce:

Create an outgoing SMTP SSL/TLS mail server with credentials for user `a@example.com`
Configure `catch_all_domain` = `example.com` (either from company configuration or from global parameters)
Create odoo user `a-user` (just any username)
Configure his e-mail address as `a@example.com`
Try to send an outgoing e-mail.

Current behavior:

Mail sending fails with error similar to:  

`2016-09-16 15:37:55,024 14221 ERROR productions openerp.addons.base.ir.ir_mail_server: Mail delivery failed via SMTP server 'smtp.zoho.com'.
SMTPServerDisconnected: please run connect() first
2016-09-16 15:37:55,025 14221 ERROR productions openerp.addons.mail.mail_mail: failed sending mail.mail 45
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/addons/mail/mail_mail.py", line 306, in send
    context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_mail_server.py", line 503, in send_email
    raise MailDeliveryException(_("Mail Delivery Failed"), msg)
MailDeliveryException: (u'Mail Delivery Failed', u"Mail delivery failed via SMTP server 'smtp.zoho.com'.\nSMTPServerDisconnected: please run connect() first")`

Expected behavior:

The email should be sent.

Video/Screenshot link (optional):

Notes:

Yes I have used modules like `tko_mail_smtp_per_user`  or  `ir_mail_server_per_user` . The problem is code related, not configuration related as you see bellow.

**Comment by tkontogi** [comment]
According to this forum post, there is a solution related to ammending the code" 

[https://www.odoo.com/es_ES/forum/ayuda-1/question/zoho-com-connection-unexpectedly-closed-51162]

I manually made the changes and it works (adding module to configure server per user or not is irrelevant).

It is my strong believe that we must make the suggested changes permanent. 

Regards,

Theo

**Comment by alexsandrohaag** [comment]
I confirm the same problem on trying to use my zoho account.

**Comment by Yenthe666** [comment]
Hi @tkontogi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by younismahsud** [comment]
Hi @Yenthe666 ,
I am facing the same issue when I assign the ticket to a user in Helpdesk module in Odoo enterprise v11. My outgoing and incoming mail servers are configured with zoho mail. Can you please tell me the solution of this problem. What could be the issue?

**Comment by Yenthe666** [comment]
@younismahsud sounds like misconfiguration of your mail servers honestly. If you can send out other e-mails etc and have a reproducable case then you can create a new bug report.

**Comment by younismahsud** [comment]
@Yenthe666 Thank you for you quick response.
I tried now and successfully sent an email for reset password. Here you can see the screenshot (https://prnt.sc/io0hj2) and see here (https://prnt.sc/io0hr9) I successfully received an email from odoo in my zoho mail server. If it is mis-configured then why sending email for reset password.
Thank you. Any help will be appreciated.

**Comment by Yenthe666** [comment]
Hmm, odd, is your Odoo running on the latest Odoo source code?

**Comment by younismahsud** [comment]
Yes.
I am using latest code.
