### ISSUE TITLE
Bug report:Contact Form(website_form by Odoo SA) don't sent email notification when it create new leads

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#13509]
Hi:

I am using odoo 9 nightly,and i use contact form(which name is website_form by Odoo SA) for website communication.

The problem is,i want to get an email notifications when it create the new leads,But it don't.

I have already following the sales team,and accept lead created notifications,when i create leads manually,i can get notification normally.

Thanks

**Comment by JKE-be** [comment]
Please us the forum for this kind of question. https://forum.odoo.com
This tracker is for issue only...

You can do it easily with an automated action on crm.lead - on_create - send_mail

**Comment by ed29** [comment]
OK,thank you
