### ISSUE TITLE
write function one2many on odoo v8 

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#13507]
Impacted versions:v8

Steps to reproduce:http://stackoverflow.com/questions/39546019/odoo-write-function-save-old-data/39550815#39550815

Current behavior: 
when using (6,_,ids) for affecting ids to a one2many field  odoo execute (2,ids,_) then (4,ids,_) 

Expected behavior:
affect  (3,ids,_) then (4,ids,_) to the field

**Comment by Yenthe666** [comment]
Hi @m3asmi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
