### ISSUE TITLE
no_create option for search view is not working

### ISSUE THREAD

**Issue by angloz** [odoo/odoo#13512]
Impacted versions: V8, V9

Steps to reproduce:  trying to disable Create Button from the Search Form view <field name="xxxx" options="{'no_create':True}"/>  , it does not work, the Create button is always there. 

Chedk this link: 
http://stackoverflow.com/questions/37781636/how-to-remove-create-option-in-search-view-opened-after-clicking-search-view-i

**Comment by pedrobaeza** [comment]
You can't do that in a regular view. You can only do it on one2many/many2many fields. Please check documentation to know more about this.
