### ISSUE TITLE
Create product from Search View won't keep the defaults and won't call the inherited views

### ISSUE THREAD

**Issue by angloz** [odoo/odoo#13511]
Impacted versions: V9

Steps to reproduce:  Create Purchase Order, Insert Line, Select "Search More", Press Create

Current behavior: The product form is opened but it doesn't keep the default settings for the form and it won't call to the inherited views!

Expected behavior: it should be identical to the action of creating a product through inventory--> create product, keeping defaults and calling the inherited views

**Comment by pedrobaeza** [comment]
That's something inherent on the way you are doing things: defaults comes from the action window (in this case, Inventory > Products). They are different also if for example you create the product from Sales > Products. As the search is agnostic, it doesn't provide that defaults that are passed through the action context.
