### ISSUE TITLE
[9.0][BUG] Multicompany rules are not being applied correctly

### ISSUE THREAD

**Issue by analisacn** [odoo/odoo#13521]
**Impacted versions:**
- 9.0 

**Steps to reproduce:**
- Activate Inter company: Settings -> General Settings -> Check: 
  - Manage multiple companies.
  - Manage Inter Company.
- Go to companies and check on Inter-Company Rules, for "YourCompany" and "My Company, Chicago" the following options:
  - Create Sale Orders when buying to this company.
  - Create Purchase Orders when selling to this company.
  - Sale/Purchase Orders Auto Validation.
- Create a new individual customer "Chicago Individual" with parent company "My Company, Chicago" and mark it as vendor (on  Sale & Purchases tab).
- Create a new purchase order with at least one product, where the vendor is "Chicago Individual".
- Confirm the purchase order

**Current behavior:**
The purchase order from "YourCompany" to "Chicago Individual" is confirmed and picking is created, but the Sale order from "Chicago Individual" to "YourCompany" isn't created. 

**Expected behavior:**
The purchase order from "YourCompany" to "Chicago Individual" is confirmed and picking is created, and the Sale order from "Chicago Individual" to "YourCompany" is created, the SO must be confirmed and the picking associate must be created. It must have the same behavior that when seller in the purchase order is directly the parent company of "Chicago Individual" (My Company, Chicago)

**Comment by pedrobaeza** [comment]
Inter company is an enterprise module. If the problem still continues, please open there the issue.
