### ISSUE TITLE
enhancement - decimal precision on tax (percentage)

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1352]
This is a very old issue. Some jurisdiction need this feature instead of a fixed +3 correlation with the decimal precistion of amount.
- https://github.com/odoo/odoo/pull/178
- https://bugs.launchpad.net/openobject-addons/+bug/868839

@qdp-odoo , a friendly ping, if you were not aware before

Colombia:
- Smallest physical monetary unit = 50
- Smallest monetary unit in accounting = 1
- Smallest monetary unit on bank statments = 0.12
- Smallest tax ration = 0.12345

If it hasn't been fixed yet in the development branches, the issue persits more than 3 years. And it's supposed to be an easier one... So please consider cleaning up this corner as well... :+1:

**Comment by blaggacao** [comment]
partly solved (tax now are very precise) . managing different precision on statements and general accounting is not.

**Comment by Yenthe666** [comment]
Hi @blaggacao,

If I am not mistaking this can be closed now? It looks ok to me?

**Comment by Yenthe666** [comment]
Thank you!
