### ISSUE TITLE
[16][Bug] Project invite email missing href

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#135304]
Impacted versions:

16

Steps to reproduce:

1. Create new project
2. Create new partner (company)
3. Create new contact to partner from point 3
4. Don't use Grant portal access
5. Go to project -> share -> edit -> Invite partner from point 3
6. Invitation email is sent without href.

Current behavior:

Invitation email is sent without href.

Expected behavior:

Working invitation email

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/5862658/1bbda60d-eef6-475c-9013-5d95427d9d2a)

**Comment by grzekru** [comment]
Hi, its probably connected with polish translation of email template.
I turned off polish language.

**Comment by vava-odoo** [comment]
Hi @grzekru 
Closing the ticket as it is not reproducible. 
Was it related to polish translation? There were a few typos in that language...
Cheers
