### ISSUE TITLE
[16.0] [Bug]  Sale: Total & Subtotal amount mismatch

### ISSUE THREAD

**Issue by nikul-serpentcs** [odoo/odoo#135312]
Impacted versions: **16.0**

Steps to reproduce:
1. Create SO with SOL, 
2. Select Any storable product.
3. 3000 Qty
4. Unit Price is **47.833**.

The Sub Total Price is **143499**
Total Price is **143490**

Current behavior: **Wrong Sub Total amount. Impact on sales analysis report too.**

Expected behavior: **Sub Total amount It should be **143490**. Both amounts are match.**

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/17664321/aee2fff8-f7d4-4b17-8768-40df15d94b31)

![image](https://github.com/odoo/odoo/assets/17664321/aeed8ac2-3adb-4441-8dc9-079055ae4fee)

Support ticket number submitted via odoo.com/help (optional):

**Comment by nikul-serpentcs** [comment]
@niyasraphy I already mentioned Steps to reproduce, but anyway I share the video for your reference.
When you add 3000 Qty and Unit Price set as a 47.333, That time mismatch.

![diff price](https://github.com/odoo/odoo/assets/17664321/073e0d66-427f-4007-b0fc-409d6faeae13)

**Comment by ppr-odoo** [comment]
@niyasraphy and @nikul-serpentcs  

This is based on decimal precision. If you do it 3 instead of 2 in the product price, this will be solved
[link](https://www.awesomescreenshot.com/video/20750929?key=f9a787702671d1883703d800f7c347fb)

thanks

**Comment by nikul-serpentcs** [comment]
@ppr-odoo Yes, but **Total** rounding automatically with 2 decimal precision. So it should also depend on **product price**.

**Comment by ppr-odoo** [comment]
> @ppr-odoo Yes, but **Total** rounding automatically with 2 decimal precision. So it should also depend on **product price**.

We fixed in saas-16.3-https://github.com/odoo/odoo/commit/87c91139c615bdbf18cca24a6f02a809d97bce9d

**Comment by nikul-serpentcs** [comment]
@ppr-odoo Thank you for your quick reply, Is it update/d in **16 odoo.sh**?

**Comment by ppr-odoo** [comment]
> @ppr-odoo Thank you for your quick reply, Is it update/d in **16 odoo.sh**?

No possibility. Because the above commit is fixed in saas-16.3 and odoo.sh uses 16.thanks
