### ISSUE TITLE
[16][bug] Error while setting password for portal user

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#135340]
**Impacted versions:**

16

**Steps to reproduce:**

1. Create new partner
2. Set partner language to Polish
3. Give access to portal
4. Go to href in email (in incognito tab)
5. Error caused by translation of python keyword "or"

**Current behavior:**

Error during setting password for portal user
```
odoo.addons.base.models.ir_qweb.QWebException: Error when compiling xml template
SyntaxError: invalid syntax (<>, line 1)
Template: <Element div at 0x7f255e1d7630>
Path: /div/table/tr[1]/td/table/tbody/tr[2]/td/table/tr[1]/td/div/strong/t
Node: <t t-out="object.email lub ''"/>
```

**Expected behavior:**

No errors

**Video/Screenshot link (optional):**

![image](https://github.com/odoo/odoo/assets/5862658/a460c475-b040-42b8-96c6-468b2bd66f46)

![image](https://github.com/odoo/odoo/assets/5862658/99093ecd-78df-4c3f-aada-5780994eefde)

**Comment by vava-odoo** [comment]
Hi @grzekru

Thanks for the contribution but please check the [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github.

The translation seems to have been updated in the meantime, but please submit your changes there and let me know if you have issues.

Thanks for reporting. 
Cheers

**Comment by grzekru** [comment]
@vava-odoo In this case, the Polish translation completely crashed the Polish version of Odoo. It may be a error in the translating process.
