### ISSUE TITLE
[9.0] Sale email templates generates empty paragraphs tags

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#13537]
Impacted versions:
- Edition: enterprise
- Version: 9.0

Steps to reproduce:
- Go to runbot Enterprise: http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7
- Run a v9 version and login as admin
- Go to sales -> Sales -> Quotations -> Click in one quotation
- Send by email

Current behavior:
- If you check the email which is going to send Odoo, is broken (see attachment)

Expected behavior:
- In the pop-up of send mail you can open the email template and check that the template is OK but the email you send is broken (see attachment)

Video/Screenshot link (optional):

![2016-09-15_15-43-58](https://cloud.githubusercontent.com/assets/8736623/18670821/ed35fad4-7f41-11e6-9185-d580d9412e74.png)

@Tecnativa

**Comment by Yajo** [comment]
This affects community edition too.
So, combined with #10954 this proves IMHO mail editor needs a massive refactoring if it wants to compete with the big ones like Mailgun, etc...

**Comment by mart-e** [comment]
Hello,

No this is the mako code, it's the conditional logic to have dynamic template.
In your send message you see the actual email that will be sent, when you open the template it is not linked to a record so you can not render it yet.
We display it in html but it won't look very good as you may have broken content but it's just preview of the "raw" template.

**Comment by Yajo** [comment]
But I still don't understand why does the red line disappear...

**Comment by mart-e** [comment]
oh ok you are talking about the red line (please be more explicit in your issues, don't use words like "broken"). Indeed I confirm the issue.
The generated block is something like
```html
    <p style="border-left: 1px solid #8e0000; margin-left: 30px;">
       &nbsp;&nbsp;<strong>REFERENCES</strong><br></p><p>
       &nbsp;&nbsp;Order number: <strong>Test/001</strong><br></p><p>
       &nbsp;&nbsp;Order total: <strong>7315.0 USD</strong><br></p><p>
       &nbsp;&nbsp;Order date:  September-28-2016 10-31 am (Europe/Brussels)<br></p><p>
       &nbsp;&nbsp;Your contact: <a href="mailto:demo@yourcompany.example.com?subject=Order Test/001">Demo User</a>
    </p>
```
with new `<p></p>` tags

**Comment by rafaelbn** [comment]
This issue has been solve by Odoo. I don't know were but it is solved
