### ISSUE TITLE
[9.0][POS] products sold with receipt without any record saved to db

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#13538]
Impacted versions: 9.0, test others

Steps to reproduce:

create a pos order
put on some products
payment
validate
instead of next record: close & confirm session
Resume to previous session : The last pos.order opened for MODIFY!
empty it
put new products
payment
validate
And voila! New receipt content aand date with prevoius number, and not even a bit of data saved to pos.order or pos.order.line
And it's repetable infinitely! all of your stock can be stolen, meanwhile customers got their receipt.

Current behavior:
   finished pos.order loaded for edit after session resume, if no next order clicked before close.
Expected behavior:
  finished pos.orders never be modified, an automatic forced  "next order" is needed, when order finished.

**Comment by jorenvo** [comment]
Thank you for the report, the issue is fixed starting from saas-6 at 8e720a9319317217fa39c3be982b41072fcd479a. This fix will be forward-ported to all later versions of Odoo.
