### ISSUE TITLE
[DEB][9.0] package installation not creating /var/lib/odoo

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#13533]
Impacted versions: 
9.0

Steps to reproduce:
On clean install of ubuntu or debian try install from nightly repos

Current behavior:

installation breaks and can't be completed ( chown can't find /var/lib/odoo).
 we must do mkdir /var/lib/odoo manually , and then apt-get install -f 

Expected behavior:
Make /var/lib/odoo default

**Comment by sle-odoo** [comment]
Did you already have an "odoo" user?

**Comment by clemensmach** [comment]
same with 11.0.20171027 (and debian 9.2.1)
yes, there was an odoo user created before install

**Comment by sle-odoo** [comment]
The package will create a system user and set its home into /var/lib/odoo, that's why it doesn't work for you. Remove the odoo user and reinstall the package.

**Comment by Yenthe666** [comment]
Closing as this was answered by (@)sle-odoo way back and as there was no feedback.
