### ISSUE TITLE
gantt translate

### ISSUE THREAD

**Issue by baimo** [odoo/odoo#13549]
Impacted versions:8.0

Steps to reproduce:
odoo-8.0\addons\web_gantt\static\src\js\gantt.js:87
Current behavior:
code: el._pseudo_group_by = "Gantt View";
Expected behavior:
code: el._pseudo_group_by = _t("Gantt View");
Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/13926643/18711560/21df65d0-803d-11e6-9f2b-8ff080f3a6d8.png)

**Comment by Yenthe666** [comment]
Hi @baimo,

Thanks a lot for your report. This bug has been fixed in the meanwhile (as you can see at https://github.com/odoo/odoo/blob/cf8577b9d0bbe6f02ed4e88e47ab3097683d519d/addons/web_gantt/static/src/js/gantt.js#L87)

Regards,
Yenthe
