### ISSUE TITLE
Please obfuscate the mailmap

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#13547]
The `.mailmap` file contains all the contributor emails and it's trivial to be harvested by spammers.
Please obfuscate them in some way.

**Comment by Yenthe666** [comment]
Hmm :+1 I agree with you on this one.
@mart-e and @odony, any feedback on this one?

**Comment by wtaferner** [comment]
@dreispt @Yenthe666 
Useless as the CLA are almost as easy to harvest. Funny though that spammers still have "success" with their methods. 
Github let you check the keep email address private in settings...this is what I did...based on this you need to rely on your name that others will contact you any other way than mail, but at least it helps to fight spam.
https://github.com/odoo/odoo/blob/9.0/doc/cla/individual/wtaferner.md

**Comment by dreispt** [comment]
Well, I guess the CLA files would also need the same kind of love.
It could be as simple as replacing the `@` with `(at)`, and then adding the inverse transformation to the code that uses this data.

**Comment by wtaferner** [comment]
True and then they just take the git history as a source...soo, it is trying to hide something you just can't hide in case you made it publicly available in the first place, but you are right, making it more difficult might stop some spammers.

**Comment by dreispt** [comment]
This still worries me.
I'm, considering adding my CLA as part of an eventual PR, and then submit a PR removing it right if it's merged...

**Comment by mart-e** [comment]
Hello,

Indeed there is tons of ways to harvest the emails, just using the commit history for instance.
If you are worry about it, you can specify some specific email to sign your CLA and makes the commit. It doesn't have to be your main email or the one linked to your github account, just the one you are making commits with (`git config user.email`)

**Comment by pedrobaeza** [comment]
Closing as there's no better solution.
