### ISSUE TITLE
Barcode (ean13) field on res_partner is not defined in the correct module (point of sale instead of base)

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#13544]
Impacted versions:
7.0, 8.0, 9.0, master

Current behavior:
To set a barcode on a partner, we have to install point of sale module.
ref : https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/res_partner_view.xml#L5
That is quite annoying if we want to use this field without point of sale module installed. (Point of  

Expected behavior:
the barcode field should defined in the base module view. (like the field is)
ref : https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_partner.py#L205

Solution proposed:
- move 'barcode' xml definition in the base.view_partner_form view.
-  optionaly, set the group invisible, and set it visible if point of sale is installed. (to keep the current behaviour).

I'll do a PR against master (future v10), if you're agree with this bug.

kind regards.

**Comment by Yenthe666** [comment]
Hi @legalsylvian,

Thanks a lot for your issue! I personally think that you're correct and that it isn't really ideal behaviour.
Your first option (move it from XML) would be against the rules regarding stable fixes, so could only be done against the master version (V10 soon) though.
@mart-e what do you think about this?

**Comment by legalsylvain** [comment]
yes my proposal was to do it against master. Thanks for your review.

**Comment by bealdav** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@legalsylvain please make the proposal in master. Any way, it's defined in POS because it's used there and not in any other place. Any way, you can redefine the field wherever you want without problems, and more now in v12 that there is not going to be side effects with the field XML-ID.

**Comment by legalsylvain** [comment]
Hi, 
@Yenthe666 : I don't understand why the bug is flagged as 9.0.
On V12 (master) : 
The field is defined in the model in ```base``` : https://github.com/odoo/odoo/blob/master/odoo/addons/base/models/res_partner.py#L168
The field is defined in the view in ```point_of_sale``` : https://github.com/odoo/odoo/blob/master/addons/point_of_sale/views/res_partner_view.xml#L19

so it is still inconsistent.

@pedrobaeza

> Any way, it's defined in POS because it's used there and not in any other place

I don't understand what you say. Well, partners are not only PoS customers. Can be employees, suppliers. So this field should be set even if point_of_sale is not installed.

> Any way, you can redefine the field wherever you want without problems

Yes. What I do in custom module. But it's a pity.

> please make the proposal in master

I'll do it if odoo team is OK with this issue.

This issue should be reopened IMO.

**Comment by mart-e** [comment]
Hi,

No problem for me to move the barcode field on the base interface in master as it is defined on the model at base and it is kind of redundant to redefine it in pos again.

**Comment by mart-e** [comment]
Merged in master at https://github.com/odoo/odoo/commit/5a6f6edb17eaaa9937d298cdeea0f35e0a4d29a7, thanks for the report and patch
