### ISSUE TITLE
[9.0] invalid access rule rule_pos_cashbox_line_user in point_of_sale module

### ISSUE THREAD

**Issue by ke-real** [odoo/odoo#13550]
Impacted versions:
9.0

An old point_of_sale rule is not valid anymore, since the field 'bank_statement_id' has been removed:

```
<record id="rule_pos_cashbox_line_user" model="ir.rule">
        <field name="name">Point Of Sale Cashbox Line POS User</field>
        <field name="model_id" ref="account.model_account_cashbox_line" />
	    <field name="groups" eval="[(4, ref('group_pos_user'))]"/>
        <field name="domain_force">[('bank_statement_id.pos_session_id', '!=', False)]</field>
    </record>
```

It should be removed.

**Comment by Yenthe666** [comment]
@mart-e can you have a look at this?
A quick Github search returns 3 results but none are the creation for the field on the Python side..
https://github.com/odoo/odoo/search?utf8=%E2%9C%93&q=bank_statement_id

Regards,
Yenthe
