### ISSUE TITLE
[9.0]Purchase Invoices causing major permorfance issues when line number is important

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#13569]
Impacted versions: 
Latest from github

Steps to reproduce:
Create a PO with 300 lines
validate multiple picking in multiple times thanks to backorders
create an invoice for this PO

Current behavior:
The invoice creation takes about 3.5 minutes
Unlinking a line in the Invoice create some exclusivelocks on DB that causes all the instance freezing
25 Users are running in the same time on the db and some are using the POS , other the inventory and also some are using the accounting part.
Each time a user create such an invoice and unlink lines, the server load is 2.5 and the I got 4 CPU at 100% which is the worker number.

Expected behavior:
Better lock and faster validations

**Comment by flotho** [comment]
Hi @rco-odoo ,

I made some little analysis and here is what I observe once the invoice is being created and lines unlinked :
 - Until This part everything is fast : https://github.com/odoo/odoo/blob/9.0/addons/purchase/invoice.py#L74
- This part seems to be very slow
What I also observe is that field_name and field values passed are representing all the object and all the fields. Maybe this could cause a performance issue?
Instead of making @api.onchange('invoice_line_ids') wouuldn't it be preferable to do @api.onchange('invoice_line_ids.ids') ?
Thanks in advance.

@mart-e any chance to be read on this part?

**Comment by flotho** [comment]
Hi @rco-odoo , any chance to be read on this?
Regards

**Comment by flotho** [comment]
Hi and ping @rco-odoo , @mart-e , 
Any chance to have a feedback on this? Do you need additionnal infos?

**Comment by pedrobaeza** [comment]
You have worked on this several times and as there are opened PRs to improve this situation and a study in progress to get it at framework level, I close it.
