### ISSUE TITLE
odoo.com Price Configurator

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [odoo/odoo#135690]
Impacted versions: Latest Web page

Steps to reproduce:
1. Go to https://www.odoo.com/pricing-configurator
2. Input any number of users
3. Click `Buy Now`

Current behavior:
```
Oops! Something went wrong.
Take a look at the error message below.

Error message:

The operation cannot be completed: Missing required fields on accountable sale order line.
```

Expected behavior: Display a checkout screen

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mart-e** [comment]
Hello,

It looks like solved but if you still are able to reproduce the issue, please report it to https://www.odoo.com/help
We try to keep github only for bugs reporting on the standard Odoo.
Regards
