### ISSUE TITLE
css and js files under /web/content/ not found

### ISSUE THREAD

**Issue by woei66** [odoo/odoo#13560]
Impacted versions:
9.0
Steps to reproduce:
yum install gcc-c++ libxml2-devel libxslt-devel postgresql94-devel openldap-devel
yum install nodejs npm --enablerepo=epel
/usr/local/bin/pip install --upgrade pip
/usr/local/bin/pip install -r requirements.txt
npm install -g less
git clone https://github.com/odoo/odoo.git --branch 9.0

Current behavior:
css and js file not found 304

Expected behavior:
css and js file should be loaded correctly.

Video/Screenshot link (optional):
![2016-09-22 2 43 23](https://cloud.githubusercontent.com/assets/5770807/18738983/f148e28e-80d2-11e6-87ce-980b09d3db2e.png)

![2016-09-22 2 43 58](https://cloud.githubusercontent.com/assets/5770807/18738998/0435733a-80d3-11e6-97e6-448a9dde8d55.png)

![2016-09-22 3 07 21](https://cloud.githubusercontent.com/assets/5770807/18739449/4f17e556-80d6-11e6-9d80-476c4f5c9bd4.png)

**Comment by woei66** [comment]
looks like the issue is caused by the wrong owner
I installed with root first and odoo will create /root/.local/share/... folder for file and session
then, I tried to execute as odoo user and it will access the /home/odoo/.local/share/ folder and it's not exist

I tried to fix it and I copied the /root/.local/ to /home/odoo/ and change owner to odoo:odoo
next, I tried to visit my site http://mysite:8069/ and the css still not there
I am a little confused.
I added "?debug" at the end of the url http://mysite:8069/?debug and it works correct
If I didn't add the "?debug" and it won't display correctly.
Why?

![2016-09-22 3 49 51](https://cloud.githubusercontent.com/assets/5770807/18740439/465c35c4-80dc-11e6-87a6-c248a210b3a5.png)

**Comment by JKE-be** [comment]
@sle-odoo

**Comment by woei66** [comment]
it works now but I don't know the real reason, it may be fixed by
1. the cache expire
2. add "--update=all " at the end

**Comment by woei66** [comment]
sorry, it doesn't work on others' pc

**Comment by woei66** [comment]
it fixed after I reinstalled

**Comment by tiennguyen2009** [comment]
Dear @woei66 
It fixed after you reinstall? 
What did you reinstalled? I also is occurred this error but I can't fix it now.
Thanks

**Comment by JKE-be** [comment]
@tiennguyen2009

psql your_db_name
Delete from ir_attachment where name ilike ‘/web/content/%’

It will force the regeneration of assets

**Comment by tiennguyen2009** [comment]
Yes, In this case. I only deploy code and DATA NOT EXISTS but it still can not get css, js.
web/static/lib/jquery/jquery.js `(404)`

This is my issue when run: `{domain}/web/database/selector?debug=true`
![2019-03-01_013524](https://user-images.githubusercontent.com/368266/53589799-eb5dd480-3bc2-11e9-983b-4c8294f5974d.png)

And 

![2019-03-01_014239](https://user-images.githubusercontent.com/368266/53590049-7a6aec80-3bc3-11e9-9d41-fc8bb17cb88b.png)

Please help advise
