### ISSUE TITLE
[9.0] Bug on adding private channel to followers

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#13578]
Impacted versions: 

9.0+

Steps to reproduce:
- Login as admin
- Create private channel
- add the channel to follower of some record (e.g. ASUSTeK partner)
- Login as demo
- open the record (e.g. ASUSTeK partner)

Current behavior:

Demo user is not able to see\modify subscription (no access to Followers button, button Following\Unfollow is not visible)

Expected behavior:

Following buttons has to be work

Video/Screenshot link (optional):
![followers](https://cloud.githubusercontent.com/assets/186131/18786810/353fd5ec-81b9-11e6-82a9-9276b2397ce0.png)

Error message from browser console:

`Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 648, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 685, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 321, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/service/model.py\", line 118, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 314, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 964, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/http.py\", line 514, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/addons/mail/controllers/main.py\", line 47, in read_followers\n    'name': follower.partner_id.name or follower.channel_id.name,\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/fields.py\", line 829, in __get__\n    self.determine_value(record)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/fields.py\", line 927, in determine_value\n    record._prefetch_field(self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/api.py\", line 248, in wrapper\n    return new_api(self, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/models.py\", line 3301, in _prefetch_field\n    result = self.read([f.name for f in fs], load='_classic_write')\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/api.py\", line 248, in wrapper\n    return new_api(self, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/models.py\", line 3239, in read\n    values[name] = field.convert_to_read(record[name], use_name_get)\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/models.py\", line 5752, in __getitem__\n    return self._fields[key].__get__(self, type(self))\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/fields.py\", line 822, in __get__\n    return record._cache[self]\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/models.py\", line 6132, in __getitem__\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/extra/runbot/static/build/173285-9-0-e98091/openerp/fields.py\", line 39, in get\n    raise self.exception\nAccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\\n\\n(Document type: mail.channel, Operation: read)', None)\n","exception_type":"access_error","message":"The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: mail.channel, Operation: read)\nNone","name":"openerp.exceptions.AccessError","arguments":["The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: mail.channel, Operation: read)",null]}}`

**Comment by yelizariev** [comment]
Probably, new ``ir.rule`` has to be added for ``mail.followers`` to hide followers with private channel for non participants

@tde-banana-odoo you work on this update https://github.com/odoo/odoo/commit/e6f038a8216c249a3ce7d9f490010d9f666f3375
, could you check this issue

**Comment by Yenthe666** [comment]
Hey @yelizariev,

Unless I'm doing something wrong it looks fixed. Could you try again please?

Regards,
Yenthe

**Comment by yelizariev** [comment]
@Yenthe666 it's still there. You need to select in **Who can follow the group's activities?** value  ``Invited people only``

**Comment by Yenthe666** [comment]
@yelizariev do you have a spare minute to make a little video for it? I'm sure I'll be faster in reproducing then. 😉

**Comment by yelizariev** [comment]
![bug](https://user-images.githubusercontent.com/186131/36164907-aa802f00-110f-11e8-953a-496c937edc4f.png)
![channel](https://user-images.githubusercontent.com/186131/36164993-eb3a2636-110f-11e8-964b-d33a227e6e7f.png)

**Comment by yelizariev** [comment]
@Yenthe666 I read you message after preparing the screenshots. I promise to make video on next issue :wink:

**Comment by Yenthe666** [comment]
Aha, yes gotcha! @tde-banana-odoo this is probably relevant for you 😄

**Comment by Yenthe666** [comment]
@tde-banana-odoo friendly reminder for this issue.

**Comment by pedrobaeza** [comment]
But is this still happening on latest versions (v10 and v11)?

**Comment by yelizariev** [comment]
It's fixed in v11
https://github.com/odoo/odoo/commit/b795d69ce8aca2e88182c6d6d6b7af54d536f9dd

**Comment by pedrobaeza** [comment]
Great!

**Comment by yelizariev** [comment]
It's fixed in v11 only and not in 9, 10, which are still supported and this is a bug, not a feature request. @pedrobaeza are you sure that the issue should be closed?

**Comment by yelizariev** [comment]
Let's try this one https://github.com/odoo/odoo/pull/24505

**Comment by Yenthe666** [comment]
Thanks a lot for the PR @yelizariev!

**Comment by yelizariev** [comment]
Fixed in https://github.com/odoo/odoo/commit/cb3e415a7cbaa169deb46711858d16a90ca1c89e
