### ISSUE TITLE
Better product search in POS

### ISSUE THREAD

**Issue by gpothier** [odoo/odoo#13585]
I have implemented an improved search feature for the POS, based on the Lunr full-text indexer (http://lunrjs.com/). The advantages over the current search functionality are:
- Ignores diacritics (eg. é, è, ê, etc. are considered the same as plain e)
- Ignores word ordering (eg. searching for "powder coffee" yields the same results as "coffee powder")
- It can be easily refined even more (eg. using a stemmer, boosting the relevance of some fields over others), as Lunr has pretty neat fetures, if required. Presently I actually disabled the stemmer, as it is language specific.

I can provide a pull request if there is interest. This is a very concise patch. You guys just tell me, otherwise just close this issue.

**Comment by gpothier** [comment]
Here is the diff, for reference.
[1661c8a59194fb8452ae2c5e963f1b3e1e3dc0e8.txt](https://github.com/odoo/odoo/files/491293/1661c8a59194fb8452ae2c5e963f1b3e1e3dc0e8.txt)

**Comment by Yenthe666** [comment]
Hi @gpothier,

First of all, thanks a lot for the suggestion! I personally do not think this will be accepted, because it uses another library and Odoo already has a lot of dependencies.
However, improving search abilities is always nice, so I'll leave the decision to somebody else. @mart-e and @jorenvo. Can you guys give feedback please?

Regards,
Yenthe

**Comment by jorenvo** [comment]
Hi,

As @Yenthe666 already mentioned we prefer to not add extra dependencies if possible. I don't disagree with the functionality, but only if it can be added without introducing too much extra complexity in the code. In master we actually have a fuzzy search library that has recently been added called fuzzy [1]. Perhaps we could reuse that in the POS to achieve something similar?

[1] https://github.com/odoo/odoo/blob/master/addons/web/static/lib/fuzzy-master/fuzzy.js


Kind regards,
Joren

**Comment by gpothier** [comment]
Hi, I just had a look to the Fuzzy library's demo (
http://htmlpreview.github.io/?https://github.com/mattyork/fuzzy/blob/master/examples/disney.html),
and as far as I am concerned it doesn't fit the bill, as it is sensitive
both to diacritics and to word order, which are the two main limitations I
had to eliminate.
I perfectly understand that you don't want to add extra dependencies, but
just to put things in perspective, this is only 25kb of Javascript
libraries, plus a hundred or so lines patch to one js file. The diacritics
removal alone is essential for non-English users (eg. coffee is correctly
spelled café, but sometimes the cashier forgets the diacritic when
searching, or somebody forgot it when adding the product itself).
Regards,
g

**Comment by pedrobaeza** [comment]
Closing as comments about extra dependencies.
