### ISSUE TITLE
No validation on the email entered by external users when sign up occurs.

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#13589]
Impacted versions:
9.0c (possibly others)

Steps to reproduce:
Install website_sale, activate debug mode and go to settings -> General Settings and tick Allow external users to sign up. On a new incognito window sign up as an external user type any email you want, there is no regular expression evaluation happening on the email address typed.

Current behavior:
User can enter invalid emails

Expected behavior:
Validation of the email address should happen.

Video/Screenshot link (optional):

**Comment by lasley** [comment]
This is expected behavior. I recommend the OCA module [auth_signup_verify_email](https://www.odoo.com/apps/modules/9.0/auth_signup_verify_email/)

**Comment by Yenthe666** [comment]
@mart-e what do you think about this one?

**Comment by daramousk** [comment]
Thank you for your replies, one question though,

The field specifically requests an email address, shouldn't there be a validation out of the box for the input given there? Why do I have to install a different module and why is this expected behaviour (since the field indirectly maps to the `email` field of the `res.partner` model?

**Comment by mart-e** [comment]
Hello,

Checking email address via regex [kind of sucks](http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html) and [should be avoided](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/).
IMHO, the only acceptable verification is to send a confirmation email. I believe it's what the auth_signup_verify_email does (I did not fully check the code). It is good but it requires a properly configured email server so it makes the external signup a bit less straightforward. Sometimes, you just want to provide an easy way to allow external users to signup and don't care about invalid emails.

I will mark it as a wishlist. It could be improved in the future but not something we will accept as a bug.

**Comment by lukebranch** [comment]
Out of interest for anyone else reading this thread I came across this the other day:

https://github.com/mailgun/validator-demo

http://mailgun.github.io/validator-demo/

It works rather well for email validation.

**Comment by lukebranch** [comment]
@daramousk ,

Out of interest you may want to check out this:

http://mailgun.github.io/validator-demo/
https://github.com/mailgun/validator-demo

It sounds like it might be useful in your case.

**Comment by daramousk** [comment]
@mart-e Thank you for the clarification Martin.

@lukebranch Thank you for the resources Luke.

Have a nice day.
