### ISSUE TITLE
delivery slip status not correct

### ISSUE THREAD

**Issue by sitimawaddah** [odoo/odoo#13583]
Impacted versions:
v9
Steps to reproduce:
- create a delivery order with several state is partial available
- reserve, so you have operations list
- print deliver slip

Current behavior:
- status of each line is taken from state of move lines sequentially, so if for example there 3 lines operations and 7 initial demands (move lines) with 2nd line state is waiting available, the dliver slip will print status 
  avaiable
  waiting avaiability
  available 

Expected behavior:
- the status should be same as related move
- and because Operations means ready to transfer, it should be Available

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/12973701/18807600/8f742a10-8275-11e6-8e3c-48ea5a3568e1.png)
![image](https://cloud.githubusercontent.com/assets/12973701/18807604/a184e51e-8275-11e6-8ff3-1b3297446f94.png)
![image](https://cloud.githubusercontent.com/assets/12973701/18807605/a7815e0c-8275-11e6-812d-796d22ff0e5e.png)

i check the code
![image](https://cloud.githubusercontent.com/assets/12973701/18807606/b836bbde-8275-11e6-9c30-e8047ab55e53.png)
i think it just should be <span>Available</span>

**Comment by pedrobaeza** [comment]
This has been already fixed meanwhile, so I'm closing. Please check latest code.
