### ISSUE TITLE
Journal Items are reconciled the most recent due date first.

### ISSUE THREAD

**Issue by amrnegm** [odoo/odoo#13588]
Impacted versions: 
Docker version odoo:9.0
Image ID: 2765898f2e47

Steps to reproduce:
- Create Invoice with any payment terms, and add some services
- Make a payment(s) that reconciles at least one journal item

Current behavior:
The most recent due-date journal item is reconciled

Expected behavior:
The earliest due-date journal item is reconciled

Video/Screenshot link (optional):
![screenshot from 2016-09-25 12-10-40](https://cloud.githubusercontent.com/assets/1026008/18814605/2cb90d74-8319-11e6-8efc-60f4ef0a1f15.png)

![screenshot from 2016-09-25 12-14-25](https://cloud.githubusercontent.com/assets/1026008/18814624/a7dc78a6-8319-11e6-83e1-c22345464090.png)

**Comment by Yenthe666** [comment]
@nim-odoo could you give feedback on this one? I'm not sure if this is expected behaviour.

**Comment by csnauwaert** [comment]
Hello,

Sorry for the delay to answer this issue. This has already been fixed in v9.0 so I'm closing this issue.

Best regards
