### ISSUE TITLE
[9.0] Graph view popup remains

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#13596]
**Impacted versions:**
9.0 Community and Enterprise

**Steps to reproduce:**
1) Open Sales -> My Pipeline
2) Go to the graph view
3) Click on the tree view and immediately hover over the graph view so that it shows the small popup window with the value inside
4) By the time the tree view loads, the small popup window with the value inside is still showing and it won't go away

**Current behavior:**
The small popup window with the value inside isn't destroyed.

**Expected behavior:**
The small popup window with the value inside should be destroyed.

**Video/Screenshot link (optional):**
![screen shot 2016-09-26 at 4 02 48 pm](https://cloud.githubusercontent.com/assets/1809451/18837072/bf01f4ae-8402-11e6-8363-d0f04c009bce.png)

**Comment by Yenthe666** [comment]
Hi @adekock11,

Thanks a lot for your report. I've just tested this and this is indeed the case.
While it is not a major bug or problem it should be fixed. @nim-odoo this might be something for you?

Regards,
Yenthe

**Comment by qsm-odoo** [comment]
@nim-odoo I will handle this.

**Comment by qsm-odoo** [comment]
This issue has been fixed with commits:
- 9.0c: https://github.com/odoo/odoo/commit/86252428846607cd5f4b18cef8de49a8cd0b151a
- 9.0e: https://github.com/odoo/enterprise/commit/28e1fe5b8727762e53beb69fe98699b426bfdf09
