### ISSUE TITLE
[9.0] Purchases order currency is not propagated to supplier invoice

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#13591]
What are the steps to reproduce your issue? 
- set your company to use currency = EUR 
- create a PO using a pricelist set in USD 

What is the current behavior that you observe? 
- the invoice created from that PO has a currency = EUR 

What would be your expected behavior in this case? 
- the invoice created from that PO should use a currency = USD

**Comment by fclementic2c** [comment]
Frederic Clementi just now
coding... For us it is feasible but for your saas customers... 
ok we'll do a module then... as usual. 


Nicolas Martinelli (nim) on 09/26/2016 11:46:20
The different behavior lies in the different point of view when creating an invoice. When you create an invoice from sale, the invoice is created and saved. In purchase, the invoice is only "pre-filled", and expects potential manual modifications or checks from the user. The reason behind this is that the purchase invoices have been though so that several PO can be added to the same invoice.

> no, it is far too dangerous for accounting consistency. 
What would be the reason? If this is because of currency conversion, it should be fine since we do the conversion by using the PO line price: https://github.com/odoo/odoo/blob/9.0/addons/purchase/invoice.py#L82
If the currencies are identical, no conversion is performed: https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_currency.py#L228
Note that this is the exact same thing that we do at creation: https://github.com/odoo/odoo/blob/9.0/addons/purchase/invoice.py#L61

> think about automated actions (when invoice is validated automatically due to high volumetry)
If there is indeed an automated action, what would be the problem to change the currency and manually call "_onchange_currency_id"? By the way, I don't think an automated action would work fine in this case, since we only pre-fill the invoice. I don't think that triggering an invoice confirmation upon clicking on "Save" would be something you expect/want.
A custom action which creates and saves the invoice (and doesn't rely on onchanges) seems more appropriate.


Camptocamp SA, Frederic Clementi on 09/26/2016 11:05:48
Ok, I that it works fine on the sales side...so what is the point of having something different for purchases ?


Camptocamp SA, Frederic Clementi on 09/26/2016 10:50:00
think about automated actions (when invoice is validated automatically due to high volumetry)


Camptocamp SA, Frederic Clementi on 09/26/2016 10:49:08
no, it is far too dangerous for accounting consistency. 
Do it work the same way for Sales orders - customer invoices flow ? If yes, it is a real issue.


Nicolas Martinelli (nim) on 09/26/2016 10:42:43
Hello,

This choice was made to keep the journal currency and the invoice currency consistent. I don't think this is such a big deal, since changing the invoice currency manually will recalculate the various amounts automatically: https://drive.google.com/file/d/0BwqtJFE-javCUHBLWkZNaDNLNkk/view?usp=sharing

Regards,
Nicolas


Camptocamp SA, Frederic Clementi on 09/26/2016 10:08:03
Hello Nicolas, 

1 - We have customers using a long list of currencies and it would be mad to create so many journals. 
2 - Every time that a purchaser will create a new PO with a new currency, it will be wrong in the accounting ledger unless the accountant create a new journal with this new currency upfront... 

Would you be kind to ask Quentin to explain me why this change ? I really do not get the point ? 

Many thanks 

Frederic Clementi 




Nicolas Martinelli (nim) on 09/15/2016 13:28:48
Hello,

This should work as long as you have defined a purchase journal in the currency of the PO. If the system cannot find such a journal, it falls back on a journal with the company currency.

Regards,
Nicolas

**Comment by sbidoul** [comment]
@fclementic2c have you done something for this?

**Comment by csnauwaert** [comment]
Hello,

This has been fixed and improved in master at rev: https://github.com/odoo/odoo/commit/03b8c10262076d717f5d8db2dd8b125a3ffac34f

Therefore I'm closing this issue.

Best regards
