### ISSUE TITLE
[15.0][16.0] Time off duration days compute issue

### ISSUE THREAD

**Issue by stanleykao72** [odoo/odoo#135964]
Impacted versions:
V15.0 V16.0

Steps to reproduce:
1. install hr_holidays_public from OCA (https://github.com/OCA/hr-holidays)
2. When just install time off module, the time off duration days computed is right
3. After install Payroll module (it installed depends module hr_work_entry_holidays), the time off duration compute is wrong.

Video/Screenshot link (optional):
1. set public holidays
<img width="1278" alt="255052910-0325042b-2406-476f-b0ad-09e4a4c339c7" src="https://github.com/odoo/odoo/assets/7038973/623b5d18-269d-42a1-b8a0-41227548686c">

2. request a new time off (the fresh db just install time off and hr_holidays_public modules)，the duration days is right
<img width="981" alt="255053384-ef1b4fb3-a6e8-49a2-92bc-1fe0061597d3" src="https://github.com/odoo/odoo/assets/7038973/08818423-aa9b-4846-b63b-413997e4514e">

3. install hr_work_entry_holidays
<img width="1280" alt="255054273-dd4290b7-7f34-46a1-b40e-72cffc565618" src="https://github.com/odoo/odoo/assets/7038973/4c335539-cd0a-4de5-9124-8cb835adb605">

4. request another new time off after install hr_work_entry_holidays, the duration days is not the same as step2
<img width="979" alt="255054480-bfed7f59-bd3d-459f-b8af-3f7d0131763c" src="https://github.com/odoo/odoo/assets/7038973/7f940e8c-de40-4274-ac55-95b3bcb23f2d">

I debug into hr_work_entry_holidays module, the function _get_number_of_days is override duration days directly.
If the compute function move to _get_number_of_days_batch function can also consider employee's contact and have flexible for inherit.

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @stanleykao72 
Closing as, as described [in the PR](https://github.com/odoo/odoo/pull/136098#issuecomment-1746330006), this is an OCA issue.
Cheers
