### ISSUE TITLE
what is 'stored' attribute for state field in purchase.py file of purchase module

### ISSUE THREAD

**Issue by anaghjose** [odoo/odoo#13593]
Impacted versions: odoo:9.0
Current behaviour: 'state' field of purchase order line is not getting stored in database.

 odoo/addons/purchase/purchase.py     **line538**
 state = fields.Selection(related='order_id.state', **stored**=True)

isn’t it supposed to be **store**=True instead of **stored**=True ????

**Comment by xmo-odoo** [comment]
Yes it should be and was fixed in 3451ac525475dafbae96fe62861499e4d096832c but as noted in #12260 changing this in 9.0 would mean a (postgres) model change which is not considered acceptable.
