### ISSUE TITLE
Analytic account not imported with journal entries

### ISSUE THREAD

**Issue by Leif0** [odoo/odoo#13603]
Impacted versions: 8

Steps to reproduce:
- Import a journal entry which contains items with analytic account.

Current behavior: Does not import the analytic account for the journal items

Expected behavior: Import the analytic account for the journal items

Here is the .CSV I'm trying to import into the journal entries which contains all the analytics informations :
http://pastebin.com/3tu6p7dW

**Comment by Yenthe666** [comment]
Hi @Leif0,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
