### ISSUE TITLE
[16.0][BUG] Raw component partial reserves when full reserves are possible when creating a backorder

### ISSUE THREAD

**Issue by hildickethan-S73** [odoo/odoo#136059]
Impacted versions:

16.0 Enterprise with mrp_workorder installed, others untested

Steps to reproduce:

1. Create storable product we are going to build (Product A)
2. Create raw product (Product B)
3. Add high amount of stock to Product B in order to guarantee we have enough (1000)
4. Create BoM for the first product. For 1000 of Product A we need 1.1 of Product B. Add an operation to have a workorder. Use "When components for 1st operation are available" option
5. Create Manufacturing Order for Product A, 1000 quantity.
6. Confirm MO and open tablet view for the workorder
7. Manufacture 750 quantity for this workorder, this is in order to be left with 250. Validate and mark as done to proceed to the next backorder

Current behavior:

- It sends us back to the tablet list view since the next backorder is "waiting for components"
- If we look at the backorder, it only reserved 0.27 of the 0.28 required of the raw product and hence left the workorder waiting
- Manually reserving after this works fine, it goes to 0.28

Expected behavior:

- It should fully reserve since we have the stock and proceed to the next workorder as it would be ready

Video/Screenshot link (optional):

Component 3 in this picture, the others were for testing the full bom
![image](https://github.com/odoo/odoo/assets/47854752/36512f63-d017-4482-8909-fefec6770462)

I imagine this is due to some specific rounding case in the code somewhere, but I haven't identified it. I'm not sure how long this has been around since it was likely masked by the code before [this change (enterprise repo)](https://github.com/odoo/enterprise/commit/45245dd4c01622a6df8578f8f470e15c0a926c0a) that wouldn't throw you back to the list view if its still waiting.

Test:

I wrote this self contained test that fails multiple `asserts` due to this issue. It shows that backorders work fine in some cases, but when in specific cases like the 2nd backorder it reserves less than it should

```python3
def test_backorders(self):
    component = self.env["product.product"].create(
        {"name": "Component", "type": "product"}
    )
    self.env["stock.quant"]._update_available_quantity(
        component, self.env.ref("stock.stock_location_stock"), 1000000
    )
    product = self.env["product.product"].create(
        {"name": "Product to build", "type": "product"}
    )
    bom = self.env["mrp.bom"].create(
        {
            "product_tmpl_id": product.product_tmpl_id.id,
            "product_qty": 1000,
            "type": "normal",
            "bom_line_ids": [
                Command.create(
                    {
                        "product_id": component.id,
                        "product_qty": 1.1,
                        "product_uom_id": component.uom_id.id,
                    }
                )
            ],
            "operation_ids": [
                Command.create(
                    {
                        "name": "Operation",
                        "workcenter_id": (
                            self.env["mrp.workcenter"]
                            .create({"name": "Workcenter"})
                            .id
                        ),
                    }
                )
            ],
            "ready_to_produce": "asap",
        }
    )
    production = self.env["mrp.production"].create(
        {"product_id": product.id, "bom_id": bom.id, "product_qty": 1000}
    )
    production.action_confirm()
    workorder = production.workorder_ids
    self.assertEqual(workorder.state, "ready")
    workorder.button_start()
    workorder.qty_producing = 100  # 900 left
    backorder_action = workorder.do_finish()
    self.assertEqual(
        backorder_action["xml_id"], "mrp_workorder.tablet_client_action"
    )
    backorder = self.env["mrp.workorder"].browse(backorder_action["res_id"])
    self.assertEqual(backorder.state, "progress")
    backorder.button_start()
    backorder.qty_producing = 650  # 250 left
    backorder_action = backorder.do_finish()
    all_backorders = production.procurement_group_id.mrp_production_ids
    self.assertEqual(len(all_backorders), 3)
    last_backorder = all_backorders[-1]
    self.assertEqual(last_backorder.move_raw_ids.product_uom_qty, 0.28)
    # Only reserves 0.27 despite having stock
    self.assertEqual(last_backorder.move_raw_ids.reserved_availability, 0.28)
    # Returns 'partially_available' because it reserved 0.27
    self.assertEqual(last_backorder.move_raw_ids.state, "available")
    # Returns 'waiting' because the move is only partially available
    self.assertIn(last_backorder.workorder_ids.state, ["ready", "progress"])
    # Returns 'mrp_workorder.mrp_workorder_action_tablet' because it thinks the backorder is "waiting"
    self.assertEqual(
        backorder_action["xml_id"], "mrp_workorder.tablet_client_action"
    )
    backorder = self.env["mrp.workorder"].browse(backorder_action["res_id"])
    self.assertEqual(backorder.state, "progress")
```

**Comment by hildickethan-S73** [comment]
pinging @yhu-odoo @svs-odoo @ticodoo since you were involved in the commit that unmasked this issue

**Comment by hildickethan-S73** [comment]
@ticodoo Thanks for the reply, we will see what we can do on our end to get around this edge case then. Maybe the best approach would be using smaller measurements to make the component numbers bigger

**Comment by ticodoo** [comment]
@hildickethan-S73 Indeed, another possible option is to use a more/less precise unit of measure (e.g. _cm_ instead of _m_ or create a new one) for your components/product to produce so the values are larger
