### ISSUE TITLE
One2many search null performance

### ISSUE THREAD

**Issue by psevertson** [odoo/odoo#136088]
Impacted versions:
14, 15, 16

Steps to reproduce:
In a large database (19,000 project_project rows, 250,000 project_task rows), make a search on `project_project` where domain is `[('task_ids','=',False)]`. Query performance is very slow

Current behavior:
Currently, Odoo is producing a SQL query using `NOT IN`, which has very slow performance, because SQL ends up performing a sequential search on the table, even though it is indexed:
```
SELECT count(1) FROM "project_project" WHERE (("project_project"."id" not in (SELECT "project_id" FROM "project_task" WHERE "project_id" IS NOT NULL)));
Time: 46709.188 ms (00:46.709)
```

Expected behavior:
If Odoo could produce a query using `NOT EXISTS` instead, the query executes much faster:
```
SELECT count(1) FROM "project_project" WHERE NOT EXISTS (SELECT 1 FROM "project_task" WHERE "project_id" = "project_project"."id");
Time: 55.452 ms
```

**Comment by psevertson** [comment]
The code that generates the `NOT IN` SQL appears to be here:
https://github.com/odoo/odoo/blob/16.0/odoo/osv/expression.py#L809

If this could return a `NOT EXISTS` instead like other places in the code, I believe that would fix the issue.
```
exists = 'NOT EXISTS' if operator in NEGATIVE_TERM_OPERATORS else 'EXISTS'
push_result(f'{exists} (SELECT 1 FROM "{comodel._table}" WHERE "{inverse_field.name}" = "{alias}".id)', [])
```

**Comment by vava-odoo** [comment]
Hi @psevertson 
Thanks for reporting. Asking some help from @odoo/rd-framework-py
Cheers

**Comment by ryv-odoo** [comment]
Hello @psevertson ,

We are aware of the issue and we already try it, but it was revert in https://github.com/odoo/odoo/pull/88882 for legit reason (some query was actually slower). IMO, we may change (/fix) in master one day, but the change is very touchy and we should battle test it in order to ensure that it is better in average.
