### ISSUE TITLE
Decimal Places Not proper on Purchase and Sales

### ISSUE THREAD

**Issue by purnendu03** [odoo/odoo#13617]
**Impacted versions:** 
V9 and Enterprise

**Steps to reproduce:**
Update Currency Rounding factor to 0.00100 it will update the Declimal Places to 3.

![eur _odoo](https://cloud.githubusercontent.com/assets/7599739/18902863/5601769c-8573-11e6-9855-8eee21f50f65.png)

It will update decimal places of all the **fields.Monetary** fields where this currency is used.
eg. Total Fields on Invoice, sales and Purchase

**Current behavior:**
On Invoice Tree view as well as Invoice lines it is working fine but on purchase and sales same is not working fine.

![po00020_odoo](https://cloud.githubusercontent.com/assets/7599739/18903057/82492924-8574-11e6-8446-1fd8250f2b80.png)

![requests_for_quotation](https://cloud.githubusercontent.com/assets/7599739/18903088/c52961d2-8574-11e6-8476-b3e165c03bf9.png)

**Expected behavior:**

![po00020_odoo_1](https://cloud.githubusercontent.com/assets/7599739/18903258/ae8ca406-8575-11e6-9ae4-6f020b2f6810.png)

![requests_odoo](https://cloud.githubusercontent.com/assets/7599739/18903266/b5c126ac-8575-11e6-9246-5aecda3ad8ec.png)

**How to Fix this:**

Add currency_id with invisible attribute if you don't want to display the currency. But my finding says that on fields.Monetary decimal places works only when **currency_id** field is there in the view. Either that is a form view or tree view.

`<field name="currency_id" invisible="1"/>`

**Purnendu Singh**

**Comment by purnendu03** [comment]
@nim-odoo @Yenthe666 another rounding issue for you guys.

**Comment by nim-odoo** [comment]
If we solve this, we probably also want to clean-up the demo data, otherwise that doesn't look good...
![screenshot-area-2016-09-28-151106](https://cloud.githubusercontent.com/assets/11041725/18914617/26add744-858e-11e6-853a-cac4b71af891.png)

**Comment by gustavovalverde** [comment]
Shouldn't this be closed by https://github.com/odoo/odoo/commit/0df9a6cc2a39e86f4e12f6da9c38ef128a5a2497 ?

**Comment by Yenthe666** [comment]
Indeed that should solve it - although that commit was made against 10.0 and the report is against 9.0

**Comment by Yenthe666** [comment]
I believe this can be closed as it is handled in V10 and up and as such a change won't be made in V9 anymore.
