### ISSUE TITLE
external links "a href" target, better to be "blank"

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1361]
Clicking on a link that is received in messaging opens that link in the "self" (default) target. This results in the user leaving OpenERP

**_Impacted versions:**_
- Version 7.0-20140722-231204

**_Steps to reproduce:**_
1. Receive an html email with a link into messaging
2. left click on that link

**_Current behavior:**_
- Opens the link in the existing window/tab (aka "self" target)

**_Expected behavior:**_
- Opens the link in a new tab/window (aka "blank" target), leaving OpenERP present on the original tab/window

**Comment by pedrobaeza** [comment]
Closing this as very old and probably already handled.
