### ISSUE TITLE
One2many  onchange

### ISSUE THREAD

**Issue by kingxjs** [odoo/odoo#13618]
Onchange事件里，获取其他行修改后的数据

**Comment by Yenthe666** [comment]
Hi @kingxjs,

Can you please add more information and in English?
Without more information we cannot give a good response on your issue or fix it..

Regards,
Yenthe

**Comment by kingxjs** [comment]
在one2many的onchange时间中，
![qq 20161008170402](https://cloud.githubusercontent.com/assets/17718227/19211876/60982a70-8d79-11e6-9306-e270b9ff00af.png)
修改图中的值，上面相应的改变。这样可以吗？

**Comment by kingxjs** [comment]
In the One2many onchange event,
![qq 20161008170402](https://cloud.githubusercontent.com/assets/17718227/19211888/a48c6e80-8d79-11e6-8a10-55ff1e24509c.png)
Modify the value in the above figure, the corresponding change. Is this ok?

**Comment by pedrobaeza** [comment]
Closing as not enough information, but I suppose it's about changing another line of the one2many in an onchange of one field of the one2many, and that's a limitation of current framework that can be avoided. There are works for getting this to work on future versions, but nothing yet.
