### ISSUE TITLE
New time sheet item not saved in hr_timesheet_sheet.sheet view

### ISSUE THREAD

**Issue by scosist** [odoo/odoo#13616]
Impacted versions:
9.0

Steps to reproduce:
1. Edit an `hr_timesheet_sheet.sheet` view that has at least one or more tasks
2. Click `Add an item`
3. Choose an `Analytic Account`
4. Press Tab until you hit the `Hours` field or just click on the `Hours` field to select it
5. Press Shift+Tab to return to the `Description` field (although it seems this may not be the intended shortcut in Odoo for this action as Shift+Tab will delete the whole row of a new item if one has not selected an Analytic Account at this point, it is common practice to use Shift+Tab to move between fields in an HTML form view)
6. At this point you get a `Warning` dialog with the message: `The line has been modified, your changes will be discarded. Are you sure you want to discard the changes ?`
7. Click `Cancel` or press ESC
8. Select the `Description` field and enter a description
9. Click on any other editable field not in this new item line (in conjunction with the warning dialog this is what seems to trigger the issue, for example one might add a new item in this manner and then decide to update a piece of information on another item before saving)
10. Click `Save`

Current behavior:
The new item is not saved, the record is lost; it disappears from the interface when you click save and is nowhere to be found in the database.

Expected behavior:
The new item should be saved regardless of what other changes might be made to existing timesheet line items.

**Comment by nemanja-d** [comment]
Have problems with that too.....

**Comment by TonyKandex** [comment]
I'm facing this issue too when a try to make a certain field required depending on an other field it don't give me any warning and when i hit save the record dissapear.

**Comment by pedrobaeza** [comment]
JS views have been totally refactored in v11, so I invite you to check. I haven't experimented this in that version as it's more consistent. Any possible rough edge, feel free to open a new issue.
