### ISSUE TITLE
Different journal entries Credit and Debit for Foreign Currency operation

### ISSUE THREAD

**Issue by VojtechPCI** [odoo/odoo#13629]
**Impacted versions:**
Version 9.0c (Community Edition)
**Steps to reproduce:**
Default currency is IDR. Exchange rate for EUR is 0.000068 for today and 0.000069 for day + 1.
1 - Create PO for 10 EUR. A "product category" settings of purchased product is:
Price Difference Account: 7 Gain (Loss) On Foreign Exchange
Stock input account: 2 Clearing Account
Stock Valuation Account: 1 Raw Material
2 - Validate and receive shipment. Check Journal Entries:
Debit (1 Raw Material) = 147,058.82 IDR
Credit (2 GR IR Clearing Account) = 147,058.82 IDR
3 - Create Vendor Bill for 10EUR, set Bill Date for next day (day + 1 with different exchange rate)
Debit (2 Clearing Account) = 147,101.45 IDR
Credit (7 Gain (Loss) On Foreign Exchange) = 2,173.91 IDR
Credit (2 Trade Payable) = 144,927.54 IDR

**Current behavior:**
Debit of the Clearing Account in step 3 (open Vendor Bill) does not equal to a Credit of Clearing Account when receive order (Step 2) => Difference is 42.63 IDR

**Expected behavior:**
Debit of the Clearing Account in step 3 (open Vendor Bill) equals to a Credit of Clearing Account when receive order (Step 2) = there is no difference

**Comment by bimajatiwijaya** [comment]
i got wrong value too..

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yenthe666** [comment]
Hi @VojtechPCI,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
