### ISSUE TITLE
Inherint a view where you need to use xpath but the element has no name is potentially dangerous

### ISSUE THREAD

**Issue by claudiostevanatocylix** [odoo/odoo#136307]
Impacted versions:
All versions of odoo

Steps to reproduce:
As the title says, when I inherit a view where there is no name in the element I want to override, the only option is to use the positional xpath expression, which is ugly and potentially dangerous

Current behavior:
Odoo does not force you to use a name for notebook, groups etc

Expected behavior:
The name argument is the only one that can be used to identify specifically an element in a view, shouldn't it be mandatory?

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @claudiostevanatocylix 
Indeed, the name is not required as there are many ways to override elements in a view.
Cheers
