### ISSUE TITLE
[9.0] procurement_jit : mto move is assigned to any quant on sale order validation

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#13634]
Impacted versions:
9.0
Steps to reproduce:
Create a sale order with a product configured with make to order and buy routes.Make sure there is stock available for this product. Validate the sale order

Current behavior:
After validation, the delivery order will be assigned but the purchase order created with the mto product will still be at draft state.
Expected behavior:
The Delivery order should still be at 'waiting another move' state

I guess this bug was introduced here : 
https://github.com/odoo/odoo/pull/13160

I think the move lose its 'waiting' state here : 
https://github.com/OCA/OCB/blob/9.0/addons/procurement_jit/sale.py#L16
because of https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L2083

opw : M120827738-pgalprlg

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yenthe666** [comment]
Hi @florian-dacosta,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
