### ISSUE TITLE
[master] mrp: Manufacturing Order Expected Dates are always readonly

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#13637]
Impacted versions: master / 10.0

Steps to reproduce: Create Manufacturing Order

Current behavior: Expected Dates are readonly

Expected behavior: Expected Dates should be writable

Video/Screenshot link (optional):

![issue_screenshot](https://cloud.githubusercontent.com/assets/7604932/18964255/5523c3b6-8635-11e6-89d7-4e8c7544dbc7.png)

There is no state at which the user can edit the Expected Date.  When creating a new Manufacturing Order, the following domains for readonly attribute should allow the user to edit `date_planned_start` and `date_planned_finished`.

``` python
states={'confirmed': [('readonly', False)]}

attrs="{'readonly': [('move_raw_ids', '!=', False)]}"
```

Changing to the following seems to fix the problem:

``` python
attrs="{'readonly': [('move_raw_ids', '!=', [])]}"
```

https://github.com/odoo/odoo/blob/master/addons/mrp/models/mrp_production.py

``` python
date_planned_start = fields.Datetime(
    'Expected Start Date', copy=False, default=fields.Datetime.now,
    index=True, required=True, readonly=True,
    states={'confirmed': [('readonly', False)]}, oldname="date_planned")
date_planned_finished = fields.Datetime(
    'Expected End Date', copy=False, default=fields.Datetime.now,
    index=True, readonly=True,
    states={'confirmed': [('readonly', False)]})
```

https://github.com/odoo/odoo/blob/master/addons/mrp/views/mrp_production_views.xml

``` xml
<group>
    <label for="date_planned_start_wo" string="Expected Date"/>
    <div name="date_planned" class="o_row">
        <field name="date_planned_start" attrs="{'readonly': [('move_raw_ids', '!=', False)]}"/>
        <label string="to" attrs="{'invisible': [('date_planned_finished', '=', False)]}"/>
        <field name="date_planned_finished" attrs="{'readonly': [('move_raw_ids', '!=', False)]}"/>
    </div>

```

**Comment by Yenthe666** [comment]
Hi @matt454357,

Thanks a lot for your report. I personally agree that this should be editable but I'm not sure if this is wanted behaviour.
@jco-odoo could you give feedback on this please?

Regards,
Yenthe

**Comment by matt454357** [comment]
If @jco-odoo decides to make the dates editable, then he will also need to fix issue #13638 .

If he wants the dates NOT editable, a change is still needed.  In that case, the domains should be removed.

**Comment by jco-odoo** [comment]
If you change on the moves of the production order, what do you do with the
further moves?  (as you should change that of the finished product)

**Comment by Yenthe666** [comment]
Hey @matt454357,

In the meanwhile this has been changed in the meanwhile so it is not so unlogical:
![image](https://user-images.githubusercontent.com/6352350/34934867-41e7d050-f9dc-11e7-92c8-b545a0d8a002.png)
I believe this should be good?

Regards,
Yenthe
