### ISSUE TITLE
[15.0][16.0] _get_reward_values_free_shipping() expects only one delivery line

### ISSUE THREAD

**Issue by t-sq1** [odoo/odoo#136395]
Impacted versions: 15.0 16.0

Steps to reproduce: 

Current behavior: Error when more than one delivery_line is set in order
`def _get_reward_values_free_shipping(self, reward, coupon, **kwargs):
        delivery_line = self.order_line.filtered(lambda l: l.is_delivery)
        taxes = delivery_line.product_id.taxes_id.filtered(lambda t: t.company_id.id == self.company_id.id)
        taxes = self.fiscal_position_id.map_tax(taxes)`
When there is more than one delivery added with another tax, this method will fail. In Germany it is possible to split the taxes for the delivery proportionally to the amounts of the specific taxes in the order.

Expected behavior: this method should expect more than one delivery line

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hello @t-sq1 
Could you provide the usecase / steps to reproduce your issue?
Thanks

**Comment by t-sq1** [comment]
Hi @vava-odoo ,
I can give you an example from another odoo method, where more than one shipping line is taken into account:

`def _add_delivery_cost_to_so(self):
        self.ensure_one()
        sale_order = self.sale_id
        if sale_order and self.carrier_id.invoice_policy == 'real' and self.carrier_price:
            delivery_lines = sale_order.order_line.filtered(lambda l: l.is_delivery and l.currency_id.is_zero(l.price_unit) and l.product_id == self.carrier_id.product_id)
            if not delivery_lines:
                delivery_lines = [sale_order._create_delivery_line(self.carrier_id, self.carrier_price)]
            **delivery_line = delivery_lines[0]**
            delivery_line[0].write({
                'price_unit': self.carrier_price,
                # remove the estimated price from the description
                'name': self.carrier_id.with_context(lang=self.partner_id.lang).name,
            })`
As you can see in this example, it is possible that more than one shipping line is added to the order.
In the function in my first post, there will be an error when more than one shipping line is added.

As a usecase I think about a possibility in german accounting. You can calculate the taxes of shipping depending on the amount  depending on the tax (7% or 19%). So you have two shipping lines with 7% tax and one with 19% tax if you have corresponding taxes in the order.

**Comment by vava-odoo** [comment]
Hi @t-sq1 
Thanks for the answer.
What would be the expected behaviour then? Add one reward line for each delivery line, with the linked tax? Which one is preferred if the reward value is not sufficient?
Also, how do you configure your db to have multiple delivery lines? Any time I touch the shipping button down the sale order, there is only one delivery line left.

**Comment by t-sq1** [comment]
Hi @vava-odoo,
thanks for your quick reply! :)
For me it would be enough that this method is not resolving in an error because of several delivery lines. 
I would suggest to add delivery_line[0] in this method. 

The db needs no special configuration - it allows more than one delivery line. Many functions in odoo allow multiple lines as you can see in my example in my second post.

**Comment by t-sq1** [comment]
Great, thanks a lot @vava-odoo !

**Comment by t-sq1** [comment]
@vava-odoo have you checked the issue and have a workaround possibly?

**Comment by vava-odoo** [comment]
Hi @t-sq1
Sorry for the delay. I must admit I kind of forgot about your issue.
And last fix I did in 15;0 broke some custom modules :-/ So I'm less favorable in such a change in stable.
Adding a restriction on the first line _looks_ safe, but I'd prefer handle that more carefully. 
Unless you provide a clear strategy on how to handle erroneous flows with taxes, I'm afraid I can't change this.

**Comment by vava-odoo** [comment]
I made a PR to discuss the matter with the team (https://github.com/odoo/odoo/pull/159584). Let's see where it leads to.

**Comment by t-sq1** [comment]
Hi @vava-odoo,
thanks for your support! I will think about the issue as well. Perhaps we should directly do it in v17.

**Comment by vava-odoo** [comment]
Hi @t-sq1 
The fix was merged in 17.0. Thanks for the report and help on this.
Cheers!
