### ISSUE TITLE
[master] mrp: MO raw material stock moves get wrong Expected Date

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#13638]
Impacted versions: **master / 10.0**

Steps to reproduce: **create MO for future date**

Current behavior: **raw material stock move expected date = today**

Expected behavior: **expected date should equal MO date_planned_start**

The `date` field on stock.move gets the correct date (same as the MO date_planned_start).  But, the `date_expected` is wrong (today)

In order to reproduce, you need to create the MO for a future date, which depends on the fix described in issue #13637.

**Comment by pedrobaeza** [comment]
As said in the other issue, this has been improved meanwhile, so I close this. If you still feel there's still something to do, please comment.
