### ISSUE TITLE
[9.0] Currency column is not shown in Partner Ledger report

### ISSUE THREAD

**Issue by dharmasaputro** [odoo/odoo#13639]
**Impacted versions:**
9.0 Community

**Steps to reproduce:**
Activate multi currency. 
Create several Journals with different currencies. 
Create some Customer Invoices or Vendor Bills with different currencies. 
Print a Partner Ledger report with option 'With Currency' checked in the wizard

**Current behavior:**
With the 'With Currency' boolean checked, in the generated Partner Ledger report, the Currency column is not shown.
![screenshot from 2016-09-30 10 13 28](https://cloud.githubusercontent.com/assets/6903347/18979597/a220e4b6-86f6-11e6-8c84-66f73e88a217.png)

**Expected behavior:**
In Openerp 7, it can shows the Currency column
![screenshot from 2016-09-30 10 09 07](https://cloud.githubusercontent.com/assets/6903347/18979548/2b3f17fa-86f6-11e6-838f-38c5b487c3c1.png)

**Comment by Yenthe666** [comment]
@qdp-odoo was this intentionally removed?

**Comment by qdp-odoo** [comment]
nope, but as I can see in the code it's still supposed to be there... 

and as I just tested, I can confirm: it's there in v9

**Comment by Yenthe666** [comment]
Apologies, I was not sure how to test this correctly and if it should be shown or not. That's why. Thanks a lot for the feedback!

**Comment by qdp-odoo** [comment]
no need to apology ;-) You're doing tremendously

keep up the good work, Yenthe

**Comment by Yenthe666** [comment]
Thanks a lot! You're going to make me blush hah! 😊
You're doing great too, thanks for all the feedback you give it helps a lot.
