### ISSUE TITLE
Internal Server Error on calendar

### ISSUE THREAD

**Issue by LordRatte** [odoo/odoo#13646]
**Impacted versions:**
Version 9.0 Enterprise Edition

**Steps to reproduce:**
1. Install Google Calendar module
2. Create an event
3. Invite a non-user email address
4. Click on the accept button

**Current behavior:**
Internal server error on a new window.
```
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1490, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1464, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 582, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1654, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/addons/utm/models/ir_http.py", line 19, in _dispatch
    response.set_cookie(cook, request.params[var], domain=self.get_utm_domain_cookies())
AttributeError: 'BadRequest' object has no attribute 'set_cookie'
```
**Expected behavior:**
![Expected behaviour](http://i.imgur.com/zglxYHV.jpg)

**Comment by JKE-be** [comment]
Thanks for the reporting.
It has been catched.

Best regards

JKE

**Comment by LordRatte** [comment]
Thank you. That seems to work but if I do it in an Incognito window, I get:

```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by JKE-be** [comment]
About which URL ?

**Comment by LordRatte** [comment]
https://<server domain>/calendar/meeting/accept?db=<database>&token=c1a1f19e962346b0bee7d7163a187f23&action=114&id=994

**Comment by JKE-be** [comment]
I suppose that you removed the base_url and db yourself in the url that you provide ? 

Can you reproduce on runbot ? 
Because without more context, not easy to debug...

Do you have a dbfilter configured on your server ?

**Comment by LordRatte** [comment]
Yes, I replaced them. How do I use runbot? There is no db filter on this specific server. Another one giving problems as well has a filter, though.

**Comment by JKE-be** [comment]
you can connect to runbot with : http://runbot.odoo.com/runbot/7/9.0
You will arrive on the last build version of v9 enterprise.

Could you send me the new log ? The root cause of the bad request...

(http://runbot.odoo.com)

**Comment by JKE-be** [comment]
But about the initial problem, the bad request.

At first view, 2 reasons possible:
   - You are logged with a user A, and try to validate the invitation for user B
   - The attendee on the event has been deleted meanwhile

Here the code:
```python
 attendee_id = attendee_pool.search(cr, openerp.SUPERUSER_ID, [('access_token', '=', token)])
            if not attendee_id:
                error_message = """Invalid Invitation Token."""
            elif request.session.uid and request.session.login != 'anonymous':
                 # if valid session but user is not match
                attendee = attendee_pool.browse(cr, openerp.SUPERUSER_ID, attendee_id[0])
                user = registry.get('res.users').browse(cr, openerp.SUPERUSER_ID, request.session.uid)
                if attendee.partner_id.id != user.partner_id.id:
                    error_message = """Invitation cannot be forwarded via email. This event/meeting belongs to %s and you are logged in as %s. Please ask organizer to add you.""" % (attendee.email, user.email)
        if error_message:
            raise BadRequest(error_message)
```

**Comment by LordRatte** [comment]
I couldn't recreate it on runbot but when I get the not-found error on my server, all that's printed to the log is:
`2016-10-17 09:06:04,445 1267 INFO ? werkzeug: 197.189.239.34 - - [17/Oct/2016 09:06:04] "GET /calendar/meeting/accept?db=demo&token=bc5b8907a3df46fd9a42d9abfd86af41&action=107&id=3 HTTP/1.0" 404 -`

**Comment by JKE-be** [comment]
You need to set a db filter...
Seems like the request cannot be dispatched because no db has been selected.
97.189.239.34 [**- -** ]()[17/Oct


See here more info: https://www.odoo.com/documentation/9.0/setup/deploy.html#dbfilter

> This is not an issue when working with the backend (web client) as a logged-in company user: the database can be selected when logging in, and customizations loaded afterwards.
> 
> However it is an issue for non-logged users (portal, website) which aren't bound to a database: Odoo need to know which database should be used for the operations or to get the data. If multi-tenancy is not used that is not an issue, there's only one database to use, but if there are multiple databases accessible Odoo needs a rule to know which one it should use.

**Comment by LordRatte** [comment]
Right. That makes sense for the second issue. I'm going to put the change you made on the production server and get back to you about the first issue if that doesn't resolve it. Thank you for your help so far.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/odoo/odoo/pull/15762
