### ISSUE TITLE
[9.0 Enterprise] Qweb report format is not proper for Landscape Orientation.

### ISSUE THREAD

**Issue by jariwala-divyang** [odoo/odoo#13644]
Impacted versions: 9.0 Enterprise

Steps to reproduce: Qweb report format is not proper when Orientation is Landscape

Current behavior: While printing report with orientation landscape. report is print on the area that is covered by Portrait format remaining space is empty. content is not scale upto landscape size.

Expected behavior: Expectation is report should print in efficient space provided by landscape size. 

Video/Screenshot link (optional): 
![account_invoice_report](https://cloud.githubusercontent.com/assets/22541983/18989425/8a7021fa-8729-11e6-8d1a-d50d23882a12.png)

I am attaching sample report of account invoice.
Report is developed by Odoo itself. I did not modified any thing just add a paperformat with orientation=Landscape.

**Comment by pedrobaeza** [comment]
That depends on the margins and sizes you have defined, so it's a configuration problem for sure, and thus I'm closing as no real issue.
