### ISSUE TITLE
[16.0] Proposed down payment amount calculated with SO total amount (including tax)

### ISSUE THREAD

**Issue by rinaldifirdaus** [odoo/odoo#136426]
Impacted versions: 16.0

Steps to reproduce:
- create sales order, set product on the so line with tax then confirm the SO.
- create an invoice with % (percentage)

Current behavior:
- The proposed down payment amount on the invoice is calculated using the total sales order amount, including taxes.

Expected behavior:
- the proposed down payment amount should be calculated with the total amount of SO untaxed amount.

Support ticket number submitted via odoo.com/help (optional):

OPW : 3520151

@qrtl

**Comment by dalaOdoo** [comment]
@rinaldifirdaus why exactly you want this ? 
I don't know your context but most of the time (in most country) tax must be paid also on a downpayment. 

Can you explain the problem of having it taxed ?

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo . Thanks for your response.
I understand that the tax should be paid on a downpayment invoice. but this is not the case.
what i want to say is the down payment amount before taxed in the invoice, is calculated from Sales Order total taxed amount not from Sales Order total untaxed amount. what i am thinking is the proposed down payment by percentage amount should be calculated based on the Sale order total untaxed amount, and we can add the tax on the invoice.

lets say in the sales order products total order before tax is USD 1000. and tax is 10%.
so the total untaxed amount is USD 1000 and the total taxed amount is USD 1100.

when we create the down payment invoice with 50%, isn't the down payment amount before tax should be USD 500?
currently if we create the down payment invoice with 50%, the down payment amount before tax is USD 550. and if we set the tax in the invoice of the down payment, the total amount after tax become USD 605. 
<img width="901" alt="image" src="https://github.com/odoo/odoo/assets/122415281/58d39fc7-52e1-4bac-9c7e-882c89df9eb2">

then when the user create the remaining amount invoice, the amount before taxed in invoice will be USD 450 and USD 495 for amount after tax.

with above behavior, the final amount of both invoice are okay (match with the sales order total taxed amount), but i think if using 50% down payment, both of the invoice (down payment invoice and the final/remaining amount invoice) should have total amount after tax USD 550, isn't it? 

Please CMIIW

**Comment by dalaOdoo** [comment]
Hi @rinaldifirdaus, I have a few questions: 
- Where are you located ? 
- When you are creating your downpayment invoice, are taxes applied or do you have to add it manually ?

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo .

>Where are you located ?
Im located in Indonesia, but my clients are in Japan.

>When you are creating your downpayment invoice, are taxes applied or do you have to add it manually ?
taxes applied automatically by set the tax on down payment product master.

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo .
I edited my previous comment, after recheck the database.
when i report this issue, the tax was applied manually on the invoice.
by seeing your question, i retest the behavior and add the tax on down payment product master. 
when the downpayment's invoice created and tax applied by the system, the proposed downpayment amount was set as what i expected.
thank you for the hint!

**Comment by dalaOdoo** [comment]
There is a limitation on Odoo 16 regarding down payment. 
The only way to apply tax automatically on down payment is to put a the tax on the down payment product which is not good if you have to deal with different taxes on your products.

Unfortunately we can not change that anymore in Odoo 16. 

FYI in Odoo 17 it has been improved. Now taxes are applied automatically on down payment based on the taxes of the order.

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo ,
After i re-confirm with my team in Japan, down payment is not taxable in Japan.
so that both in odoo v16 and the new feature in v17 cannot handle Japan down payment scenario unless the users change manually the invoice which is not convenience for users i think.
is there any way to handle this in both version? it would be great if in odoo v17 can handle the condition whether the down payment is taxable or not. :)

**Comment by dalaOdoo** [comment]
@rinaldifirdaus
if you don't put tax on the down payment product in V16 it should work as expected.
For v17 I'll mention it to our accounting team so they can take into account this

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo .
Sorry for late response on your previous comment.

>if you don't put tax on the down payment product in V16 it should work as expected.
I think this cannot fix the situation. because even if we don't set tax on downpayment product, when the down payment invoice created, the unit price(before taxed) of the downpayment product will calculate the **sales order total amount after taxed**. which in japan, down payment should calculate the percentage based on the **sales order total amount before taxed**.
This current behavior is not applicable for Japan market.
Since our existing client is still using the v16, I hope that Odoo would provide a solution for this matter on v16. Thank you!

**Comment by rinaldifirdaus** [comment]
Hi @dalaOdoo , no, the used tax is excluded in sales price.

**Comment by dalaOdoo** [comment]
I can not reproduce your problem. 
Here is a video in 16 first with no tax on the down payment product, then with a tax on it, both cases are working fine.

https://drive.google.com/file/d/1nkxSGMCQsn7F7tH6oyzUcz0kRbLwvr07/view?usp=drivesdk

**Comment by yostashiro** [comment]
@dalaOdoo The first case in your video (i.e. down payment amount of USD575) looks wrong to me (why calculate based on the amount with tax, and then not apply tax on the down payment?). It is at least incorrect in our country (Japan) where we would just expect USD500 (and no tax applied) as the down payment, calculating based on the amount without tax (i.e. USD1000).
