### ISSUE TITLE
suggested improvement in claim management

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#13643]
Impacted versions:
9.0
Steps to reproduce:
vendor claim with PO as reference document
Current behavior:
no possibility to access to claim data from PO form
Expected behavior:
icon to access claim data related to the concerned PO (as already implemented for goods receipts and vendor invoices)
Video/Screenshot link (optional):

**Comment by ccandito** [comment]
dear All, 
the same feature should be available for sales order also.
So claim having as document reference PO/SO can be viewed from the PO/SO also.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
Meanwhile, the module has been removed from official addons, so this has not anymore sense, and thus I'm closing. Any way, what you ask for is a new module like the one you are describing (claim_from_delivery).
