### ISSUE TITLE
[9.0]get list of db

### ISSUE THREAD

**Issue by hparfr** [odoo/odoo#13651]
Impacted versions: 9.0

Steps to reproduce:
issue a request to route /web/database/get_list

Current behavior:
missing method

Expected behavior:
a list of db

The code was here https://github.com/odoo/odoo/blob/a0c64bebe673050fe5b9e32afb740a30ff1ec749/addons/web/controllers/main.py#L704

I didn't find the commit where it has been removed.
Having the list of db is needed for doing auth from external systems, like mobile applications. 
Is there any workaround ?

**Comment by JKE-be** [comment]
Hello,

Please uses forum for this kind of question.
This tracker is for issues only.

One workaround:
`ajax.jsonRpc('/jsonrpc', 'call',  { method : 'list' , service : 'db', args : []})`

Here the commit that you are looking for: https://github.com/odoo/odoo/commit/3cba55d7a7e1f01150f87f806546e10526b10219

Best regards

JKE
