### ISSUE TITLE
Updating/fixing base module in 16+

### ISSUE THREAD

**Issue by woodholly** [odoo/odoo#136595]
Since -u base does not work anymore, how can one fix/update base module nowadays?
PS: I tried to fix currency sign inside odoo/addons/base/data/res_currency_data.xml and failed ...

**Comment by intero-chz** [comment]
Did i miss something? Since when it's not possible to update `base` anymore?

**Comment by vava-odoo** [comment]
Hi @woodholly 
There is no reason you can't update a module, base included.
Maybe it is more a problem of currency rate that you need to update manually in the db.
Cheers
