### ISSUE TITLE
[9.0] Cannot export products because of cross origin error

### ISSUE THREAD

**Issue by w-vi** [odoo/odoo#13658]
Impacted versions:
9.0

Steps to reproduce:
Install odoo from rpm package n CentOS 7 with nginx as a proxy with `add_header X-Frame-Options "SAMEORIGIN";` set. Populate product database and then try to export products in CSV. I am using Chrome on Linux. With Firefox the result is very similar.

Current behavior:
Results in pop up reading:
`Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://myodoo.mydomain.com" from accessing a cross-origin frame.`
In JS Console I see : 

```
Refused to frame 'https://myodoo.mydomain.com' because it violates the following Content Security Policy directive: "frame-src https://assets.zendesk.com https://www.facebook.com https://s-static.ak.facebook.com https://tautt.zendesk.com".`

web.assets_common.js:2554 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Sandbox access violation: Blocked a frame at "https://myodoo.mydomain.com" from accessing a frame at "null".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.
```

Expected behavior:
I don't get the Uncaugth Seciurity Error.

**Comment by Yenthe666** [comment]
@xmo-odoo and @odony could you guys have a look at this one?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment in the proxy, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
