### ISSUE TITLE
Do not show irrelevant states when creating a new res.partner 

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#13657]
**Impacted versions:**
9.0c Possibly others
**Steps to reproduce:**
Create a new customer.
**Current behavior:**
The state_id field does not filter the states based on the country selected (when a country is selected)
**Expected behavior:**
When selecting a country different than United States, the state_id field should not show the US states and should rather filter on the country selected (since there is a country_id field already existing on the res_country_state table. Users might add states of their countries as well.

**Comment by Yenthe666** [comment]
Hi @daramousk,

Thank you for the suggestion! I've labelled it wishlist, this will make sure this idea comes up every now and then for the Odoo team to check.
I personally would like this, it is a nice little extra feature for usability.
@mart-e this might be something for you.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Before it was not an issue as we only had the USA states but now we have many more in the base data so it makes sense to add such domain.
Done at 24aba6014c55206fb0bf18e2239ab3167a9d3cac

**Comment by Yenthe666** [comment]
Yes, yes, yes! Thank you @mart-e, great addition.

**Comment by wtaferner** [comment]
Wouldn't it make more sense to hide the state_id field in case country_id is False? And I think based on this domain you won't be able to choose a state_id anyway before choosing a country, right?

**Comment by fpodoo** [comment]
For information, I just reverted this fix.
This commit introduces a serious usability issue. We got several customers complaining from it.

You can not set a state field when you fill a form (you have to skip the state, go on country, set the country and come back to the state, which is weird)

Screenshot of a livechat session I did today: https://drive.google.com/file/d/0B5BDHVRYo-q5WmNGRnVxUlN2akE/view?usp=sharing (and it annoyed me just before I did this chat session too)

**Comment by fpodoo** [comment]
To continue my comment, we did another patch to: select all states if no country, select country's state if a country is set. (in master)

**Comment by Yenthe666** [comment]
Hi @fpodoo,

Thank you for your comment.
I've just tested this in the master version and this behaviour is so much better, the logic is easier to follow. 
Would default data be allowed for a country? If so I could make a PR for Belgium.
A screenshot for other people:
![image](https://cloud.githubusercontent.com/assets/6352350/21560935/4dc3bada-ce66-11e6-97cf-317b1f22ab7f.png)

**Comment by fpodoo** [comment]
what do you mean default data? note that the commit  44685b595b sort the result of the name search according to the code of the state. So, if you search CA, you get California as the first one as it's the CA code (but not for cal as it's ordered by name)

**Comment by pedrobaeza** [comment]
Isn't better to use @api.onchange?:
```
@api.onchange('country_id'):
def _onchange_country_id(self):
    if self.country_id:
        return {'domain': {'state_id': [('country_id', '=', self.country_id.id)]}}
    else:
        return {'domain': {'state_id': []}}
```

**Comment by fpodoo** [comment]
@pedrobaeza No, I think we should deprecate this feature (onchange that impacts a domain).

**Comment by Yenthe666** [comment]
@fpodoo I'm talking about adding default cities (states) on the table `res.country.state` for specific countries.

**Comment by pedrobaeza** [comment]
OK, @fpodoo, but I think it's cleaner than the obscure context key passed through the view and processed on `name_search` method. Remember all the problems that `context` argument gives in the inheritance chain: you have to overwrite full context argument - there's no possibility of adding a key to existing context.

**Comment by fpodoo** [comment]
no, there is no state in Belgium (in the sense: needed on an address)

**Comment by Yenthe666** [comment]
@fpodoo not legally but there are plenty of companies that want to select / print it 😉

**Comment by fpodoo** [comment]
@Yenthe666 to print the state in the address  in Belgium? It's weird, it's not the postal format. I prefer not to put that in standard.

**Comment by Yenthe666** [comment]
@fpodoo no worries, just so I know it. Thanks for the improvement.

**Comment by mylbco** [comment]
I agree with @fpodoo, nobody uses it for print purposes, but it is used as @Yenthe666 says for filtering purposes. If everything depends on the country, why not putting first the country when entering the address, it know it looks a little bit contra intuitive.

**Comment by fpodoo** [comment]
With the latest patch, the fastest way to record an address is to start
with the ZIP.
If you write CA in the state, Odoo sets the State to California AND the
country to U.S.

On Thu, Dec 29, 2016 at 11:50 PM, Peter Langenberg <notifications@github.com

**Comment by mart-e** [comment]
The commit was only reverted in master, not in 10.0. I agree it is not good to force to select a country first.
I have reverted and made the minimal change at ec5d696cf7edb904bbad610b974ce7347daa9ef9.
In master we can try to make something smarter.

**Comment by saif1-creator** [comment]
i want to add this feature in website and facing the errors so how can i overcome this
