### ISSUE TITLE
 In case of 2 step receiving, the stock level forecast doesn't show the expected date of arrival

### ISSUE THREAD

**Issue by bistakedar** [odoo/odoo#13652]
Impacted versions:
9.0 
Steps to reproduce:
-> Set Warehouse For 2 Steps Receiving
-> Create a Purchase order with a product and set schedule date of 2 weeks later
-> Now confirm the order, So you will have 2 Pickings(1st is Vendor->Input and 2nd is Input->Stock)
-> Now Process the 1st picking, and click on Forecast tab of product which is in Picking, You will find correct date in Forecast Table
-> Now Process the 2nd Picking, and click on Forecast tab of product which is in Picking, You will find date is changed in Forecast Table.
Current behavior:
If order is placed on 9/28/2016, and expected date from Input to stock location is 10/7/2016 then stock gets added to current weeks forecasted quantity instead of week of 10/3/2016.
Expected behavior:
If order is placed on 9/28/2016, and expected date from Input to stock location is 10/7/2016 then stock should get added to current weeks quantity instead of week of 10/3/2016
Video/Screenshot link (optional):
[Stock level forecast - steps to replicate.docx](https://github.com/odoo/odoo/files/503419/Stock.level.forecast.-.steps.to.replicate.docx)

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yenthe666** [comment]
Hi @bistakedar,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
