### ISSUE TITLE
The attribute values are hidden behind search on Products > Product Variants tab on Mac in Safari, and Chrome

### ISSUE THREAD

**Issue by cbjesse** [odoo/odoo#13655]
Impacted versions: 9.0

Steps to reproduce: Go to Sales > Products > iPad Mini. Select Variants tab attempt to add attribute, and then an attribute value. Next add another attribute value you will see the current values are hidden behind the search box as shown in the included screenshot.

Current behavior: Attribute values are hidden behind attribute value search.

Expected behavior: Attribute search should be below or next to the values so they are visible and not hidden behind.

Video/Screenshot link (optional):
<img width="1266" alt="screen shot 2016-09-30 at 9 20 39 am" src="https://cloud.githubusercontent.com/assets/19474309/19005856/ab67b782-8711-11e6-9589-53b381417eaa.png">

Note: This appears to only be an issue on Mac.

**Comment by Yenthe666** [comment]
Hi @cbjesse,

Thank you for your report, I've just tested this and can confirm this as a bug.
@JKE-be this might be something for you?

Regards,
Yenthe

**Comment by ParokshaX** [comment]
This bug is reproducible in the chrome browser version (53.0.2785.143)

## Additional Info:

| Platform | Browser | Version | Reproducible |
|----|---|----|---|
|Linux|Chrome| 50.0.2661.102| N|
|Linux|Chrome|53.0.2785.143| **Y**|
|Linux|Firefox|48.0|N|
|Linux|Firefox|49.0|N|

**Comment by 8cells** [comment]
Can be fixed with this line:

![fix](https://cloud.githubusercontent.com/assets/7283980/19220263/a3ad965a-8e29-11e6-8df4-c47297410376.png)

**Comment by JKE-be** [comment]
Thanks for the reporting.

It has been tested, and it fixes 53.0.2785.* and don't seems to break IE (IE11 tested)

Merged in 9.0

**Comment by cbjesse** [comment]
@8cells Thanks for identifying the solution!
