### ISSUE TITLE
Wrong credit or debit value in accounting entry !

### ISSUE THREAD

**Issue by ydaniels** [odoo/odoo#13666]
Impacted versions: odoo 9 enterprise and community edition

Steps to reproduce: Creating new journal items would always bring out Wrong credit or debit value in accounting entry ! as long as the debit and credit amount is greater than 0.
I think line 384 in account.move contradict itself
`_sql_constraints = [
        ('credit_debit1', 'CHECK (credit*debit=0)', 'Wrong credit or debit value in accounting entry !'),
        ('credit_debit2', 'CHECK (credit+debit>=0)', 'Wrong credit or debit value in accounting entry !'),
    ]`

Current behavior:
it keeps popping out 'Wrong credit or debit value in accounting entry !
Expected behavior:
It should save since the debit is equal to credit side
Video/Screenshot link (optional):

**Comment by bistaray** [comment]
Can you share the example Journal Entry you are creating (screenshot) showing what you are entering?

**Comment by gdgellatly** [comment]
You can only have debit OR credit on a journal item. You can't have both.

**Comment by Yenthe666** [comment]
Hi there,

As there has been no feedback to Ray and as gdgellatly most likely answered your issue I'm closing this.

Regards,
Yenthe
