### ISSUE TITLE
Unit price is reset when the quantity is changed

### ISSUE THREAD

**Issue by adebuhr** [odoo/odoo#136605]
**Impacted versions:** 15,16

**Steps to reproduce:**
1. Go to Sales
2. Click "Create"
3. Select a Customer
4. Add Product to Order Lines
5. Change Unit Price 
6. Change Quantity

**Current behavior:**
The unit price is set to the default unit price again. The unit price must be adjusted again.

**Expected behavior:**
The adjusted unit price is used and the total price is calculated based on the quantity.

If no customer has been set before, the price is not reset and the adjusted price is used.
This behavior should be the same if a customer is selected before. 

The current behaviour can unknowingly lead to the creation of wrong quotations.

**Comment by ajjayymahato** [comment]
Hi @adebuhr ! I would like to work on this issue. Is this issue still open? Can you please assign this issue to me!

**Comment by adebuhr** [comment]
Hi @ajjayymahato The Issue is still open.

**Comment by pedrobaeza** [comment]
This is on purpose, as you can have escalated prices depending on the quantity. Check https://odoo-community.org/shop/sale-order-qty-change-no-recompute-6448#attr=25838 for avoiding it.

**Comment by ajjayymahato** [comment]
@adebuhr @pedrobaeza So is this issue still open?

**Comment by pedrobaeza** [comment]
1 piece - unit price: 5
5 pieces - unit price: 4,5

**Comment by chapital** [comment]
I also hate when this happens, I need to change the price again, normally I change the price to a higher price an then change the quantity, but changes the price changes again, I understand the price rules but if I manually change the price its for a reason, maybe I could have a rule when the price its changed manually dont get modified when the quantity is changed.

**Comment by chapital** [comment]
I also agree to add a minimum price to sell a product or % minimum of the price stablished, because the seller can have an error changing the price and sell the product under the cost.

For example 

Cost 100
product price 200
% Mínimum to give the product: 10% ($20)

If I put 180 I can change the price
but if I put 170 I can't change the price because the minimum its $20 off (10% = 180),


in this way if I put the price of 80 (lower than cost), I cant change the price.

**Comment by vava-odoo** [comment]
Hi @adebuhr 
It is indeed expected in standard, as kindly explained by @pedrobaeza and @gdgellatly.
Cheers

**Comment by cvinh** [comment]
Fixed in https://github.com/odoo/odoo/commit/c584a61697e
