### ISSUE TITLE
Cannot start session point of sale - v9

### ISSUE THREAD

**Issue by duongduong** [odoo/odoo#13667]
Hi,
I create a new database and install module point of sale. I cannot start session POS, system appeared "Unable to open the session. You have to assign a sale journal to your point of sale.", i find but cannot create sale journal? Help me, pls.

**Comment by Yenthe666** [comment]
Hi @duongduong,

Thank you for your report but Github is only used for bugs in Odoo itself, not to answer questions.
It is best that you create such questions on odoo.com/help, there are plenty of people there who can help you.
As for your question: you can create a sale journal on a POS under Point of Sale > Dashboard > More > Settings:
![image](https://cloud.githubusercontent.com/assets/6352350/19065563/87b6801a-8a14-11e6-953b-54050ebfe391.png)
After clicking on settings you can see the current one and you can create new ones:
![image](https://cloud.githubusercontent.com/assets/6352350/19065592/a60a5e88-8a14-11e6-9382-3015fc3f8051.png)


Regards,
Yenthe

**Comment by duongduong** [comment]
Thanks for advance.
I mean how to create selections of field Sale Journal. If you create new database by /web/database/manager, the system not show "Customer Invoice (USD).
But i solved my problem. Tks.
