### ISSUE TITLE
[9.0] Is PostgreSQL 9.6 supported?

### ISSUE THREAD

**Issue by prasanthsd** [odoo/odoo#13661]
I guess unless you try it yourself there are no ways to know at this point since it too early. But looking at the list of changes in the below link, can anyone predict if it would break any features in Odoo?

https://www.postgresql.org/docs/9.6/static/release-9-6.html

**Comment by Yenthe666** [comment]
Hi @prasanthsd,

Thank you for your question, usually these questions belong on the Odoo forum though. The Github issues are only used for bugs in stable Odoo versions and to report problems, not to ask questions.
I'd advice you to ask this question on the official forums (help.odoo.com).
Now, to answer your question, postgreSQL 9.6 shouldn't give any problems with Odoo. The most changes are made on the indexing and scanning, there are little changes to methods and data.
So Odoo should work out of the box on Odoo 10, just test is heavily before using it in production.

P.S: This is no official statement from Odoo, just my personal feedback.

Regards,
Yenthe
