### ISSUE TITLE
Typo/ Spelling Errors in Variable Names

### ISSUE THREAD

**Issue by tenxor105** [odoo/odoo#13663]
Impacted versions: 10.0

Hi,

Will typo/ errors in variables or xml ids be eventually corrected?

Ex 1.

name="%(mrp_production_action_picking_deshboard)d"

deshboard should definitely be dashboard. It feels uncomfortable to extend the code and use the same misspelled name,

Ex. 2:

group name="statistisc"

That's from odoo 10 enterprise.

Thanks!

**Comment by Yenthe666** [comment]
Hi @tenxor105,

Thanks a lot for your report!
Please feel free to create a PR to fix these issues against 10.0, then we can merge it quite fast.
Otherwise you will need to wait until somebody from Odoo has time to fix these issues I'm afraid..
@mart-e 

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

We usually prefer to avoid fixing code for cosmetic reasons. Even if you have incorrect values (e.g. [datas](https://github.com/odoo/odoo/blob/886751e2c1445d01e2f913eabbab0af657617411/openerp/addons/base/ir/ir_attachment.py#L255)).
So we can fix a bit but it is usually bug-prone changes, forces to modify customisations or community modules.
So we accept some cosmetic changes but if it's low risk only (no field renaming, methods that are often called,...)

**Comment by Yenthe666** [comment]
Hi there,

This was fully answered but never closed.
Don't forget that if you do make a PR for these kind of improvements that it should be against the master version.

Regards,
Yenthe
