### ISSUE TITLE
XPATH Selectors will not work with a "." dot in attribute values!

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#13672]
Any clue why on some platforms "." is not a valid character in xpath attribute values? lxml version is 3.3.5 (but will still fail with 3.6.4 also)

Impacted versions: 
8.0, 9.0 
Tested on MacOSX and some Linux distros with lxml 3.3.5 up to 3.6.4 and python 2.7.6 up to 2.7.12

Steps to reproduce:
Create an XPATH Selector with a dot "." in an attribute value e.g.: "res_company.name"
`<xpath expr="//footer//div/span[@t-field='res_company.name']" position="after">``

Current behavior:
`AttributeError: Element '<xpath expr="//footer//div/span[@t-field='res_company.name']">'`

Expected behavior:
Should just work on any platform.

**Comment by michaelkarrer81** [comment]
After changing the selector to this:

```<xpath expr="//footer//span[contains(@t-field, 'res_company.name')]" position="after">```

it works perfectly.

But still the problem and the cause of the problem persists.

**Comment by JKE-be** [comment]
Hello @michaelkarrer81 , 
could you check with a console python that the bug is well in Odoo and not in Lxml lib ? 
Thanks you...

**Comment by Yenthe666** [comment]
Hi @michaelkarrer81,

Can you give feedback? Is this bug still relevant?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in a few months.
