### ISSUE TITLE
Crash when adding custom field

### ISSUE THREAD

**Issue by xclam** [odoo/odoo#13675]
Impacted versions: 9

Steps to reproduce: 
I've add a new field throug database structure > field
name = x_name
model = Partner
type = many2many
related model = *custom model*

When I restarted the server I get this error :

> 2016-10-04 14:04:38,565 8533 ERROR odoo-v9 openerp.modules.registry: Failed to load registry
> Traceback (most recent call last):
>   File "/opt/odoo/openerp/modules/registry.py", line 386, in new
>     openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/odoo/openerp/modules/loading.py", line 334, in load_modules
>     force, status, report, loaded_modules, update_module)
>   File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/opt/odoo/openerp/tools/convert.py", line 851, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/opt/odoo/openerp/tools/convert.py", line 921, in convert_xml_import
>     doc = etree.parse(xmlfile)
>   File "lxml.etree.pyx", line 3299, in lxml.etree.parse (src/lxml/lxml.etree.c:72421)
>   File "parser.pxi", line 1812, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106108)
>   File "parser.pxi", line 1832, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:106368)
>   File "parser.pxi", line 1727, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:105258)
>   File "parser.pxi", line 1146, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:100385)
>   File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
>   File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
>   File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94757)
> XMLSyntaxError: Opening and ending tag mismatch: field line 278 and record, line 280, column 11
>

So i've deleted my field in ir_model_fields but I still have the problem.

**Comment by bistaray** [comment]
Opening and ending tag mismatch: field line 278 and record, line 280, column 11

This error is telling you that there is an XML file with a tag opening something but not being closed.  I don't think it is because you added a custom field - perhaps you added the field to a VIEW via XML but there is a problem with your XML? (in your CUSTOM MODEL module)

**Comment by Yenthe666** [comment]
Hi @xclam,

As @bistaray pointed out you didn't close a tag properly, which is causing this error. Nothing in the stacktrace is referring to the new field and model. Have a look at the XML again and find the tag that is not closed properly 😉.

Regards,
Yenthe
