### ISSUE TITLE
10.0 setup_dev.py checks out 9.0

### ISSUE THREAD

**Issue by dieck** [odoo/odoo#13670]
Impacted versions: 10.0

Steps to reproduce:
Use "wget -O- https://raw.githubusercontent.com/odoo/odoo/10.0/setup/setup_dev.py | python" as noted in the Getting started section of https://github.com/odoo/odoo/tree/10.0 Readme.md

Current behavior:
Checks out 9.0

Expected behavior:
Should check out 10.0

Video/Screenshot link (optional):
output of "wget -O- https://raw.githubusercontent.com/odoo/odoo/10.0/setup/setup_dev.py | python"
[..]
odoo:running git config branch.9.0.remote odoo
odoo:running git config branch.9.0.merge refs/heads/9.0
odoo:running git checkout 9.0
Checking out files: 100% (21637/21637), done.
Branch 9.0 set up to track remote branch 9.0 from odoo.
Switched to a new branch '9.0'
Your branch is up-to-date with 'odoo/9.0'.

**Comment by sle-odoo** [comment]
Hello,
This was fixed in rev f4715350549568003d5015fe87e6520e4797d465

Regards
