### ISSUE TITLE
[9.0] Different Tax Computation for Sales Order and Invoice

### ISSUE THREAD

**Issue by ronniescs** [odoo/odoo#13687]
Impacted versions:

[9.0]
Tested in runbot http://174550-9-0-10dcec.runbot10.odoo.com/

Steps to reproduce:

Set the Tax Calculation Rounding Method to "Round Globally" 
Create a Sales Order with the following lines with 7% taxes

1) 5,095.20 
2) 523.20 
3) 80.64 
4) 54.12 
5) 182.00 
6) 186.20 
![image](https://cloud.githubusercontent.com/assets/16055718/19144073/309aa082-8bda-11e6-81d0-2461c4e9a467.png)

Create a Sales Invoice with the same lines with 7% taxes
![image](https://cloud.githubusercontent.com/assets/16055718/19144078/38048b58-8bda-11e6-9c2b-4b501cfa1e12.png)

Current behavior:

The total taxes in Sales Order are $477.48 

The total taxes in Sales Invoice are $477.50 

Expected behavior:

Both the total taxes in Sales Order and Sales Invoice should be 477.50 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo this might be for you. Another rounding thing?

**Comment by qdp-odoo** [comment]
@nim-odoo Can you check pleaaase?

**Comment by nim-odoo** [comment]
@qdp-odoo : yep I confirm... I'll have a look

**Comment by mart-e** [comment]
Fixed in master at 4dcf54e23f8b796396660fd7d4ab33897ef40e12
