### ISSUE TITLE
[10.0] stock product: produce_delay field only visible for sold products

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#13684]
Impacted versions: **10.0**

Steps to reproduce: **Uncheck Can be Sold**

Current behavior: **Sales tab, and therefore Manufacturing Lead Time disappears**

Expected behavior: **Manufacturing Lead Time field should be placed on Inventory tab**
We need to set the produce delay on subassembly products that are not for sale.

Video/Screenshot link (optional):
![screenshot_ 2016-10-05_10 15_am](https://cloud.githubusercontent.com/assets/7604932/19121923/85be6580-8ae5-11e6-915e-a50d760528f6.PNG)
![screenshot_ 2016-10-05_10 16_am](https://cloud.githubusercontent.com/assets/7604932/19121922/82f3f82e-8ae5-11e6-9d5f-7c585c6ef232.PNG)

**Comment by JKE-be** [comment]
Thanks for the reporting

@bst-odoo  for usability

**Comment by bst-odoo** [comment]
Agreed. We will improve it. Thanks for your input.
