### ISSUE TITLE
[Q] Why is there no odoo.py in 10.0 branch?

### ISSUE THREAD

**Issue by omerfirmak** [odoo/odoo#13682]
9.0 branch has its odoo.py but 10.0 does not?
How am i supposed to run odoo without installing it?
I have a version 9 already running on my server. I want to run version 10 on the same server for testing purposes?

**Comment by bistaray** [comment]
odoo-bin is now used in place of odoo.py

ie: `./odoo-bin -c /etc/odoo/odoo.conf`

**Comment by donghd** [comment]
Thanks you for both question and answer! It worked!

**Comment by Yenthe666** [comment]
Hi @omerfirmak,

Thank you for your report. This is actually done with purpose! The file was renamed from odoo.py to odoo-bin.py because it gives us the ability to package the Odoo installer better and it is more complaint with rules.
As bistaray said, you can now access it from `./odoo-bin`
