### ISSUE TITLE
Current cost line on a Landed Cost is very different from the quant cost.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#13696]
Impacted versions:
9.0e
Steps to reproduce:
Landed cost> choose split method "by current cost"> calculate> display valuation lines
Current behavior:
Former Cost(per unit) shows a different cost than the quant value.
Expected behavior:
This value should match the quant value.
Video/Screenshot link (optional):

**Comment by elevationO** [comment]
Bump

**Comment by sle-odoo** [comment]
Hi,
I don't get it. Can you explain a little more? Is it still reproducible on runbot? Where do you read the cost of the quant?

Regards
