### ISSUE TITLE
Create & Edit button not shown/hidden when user's group changed

### ISSUE THREAD

**Issue by vak0160** [odoo/odoo#13690]
Impacted versions: 8.0 (git 8d9b309f9a79cf9a5c48037d7c099ef50c928707)

Steps to reproduce:
1. Have 2 group, staff and manager.
2. Group staff have readonly access.
3. Group manager have full access. (No inheritance and rule, only ACL).
4. Give user either staff or manager group.
5. Let user see the menu.
6. Change user's group from staff to manager, or manager to staff.

Current behavior:
1. When a user is a staff, he doesn't have create / edit button, but his group changed into manager, he still doesn't have create / edit button.
2. The reverse is also true, when his group changed into staff, he still can see create / edit button, although odoo would block him from saving.
3. After I restart the server, the button show / hide correctly.

Expected behavior:
1. Create / Edit button should be shown / hidden after group change and refresh page, without server restart.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @vak0160,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
