### ISSUE TITLE
odoo 10.0 print report to pdf is very slow ...

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#13698]
Impacted versions: 10.0

Steps to reproduce:
1.install wkhtmltopdf version 12.1
2. cp -a /usr/local/bin/wkhtmltopdf /usr/bin/. && cp -a /usr/local/bin/wkhtmltoimage /usr/bin/.
3. sudo shutdown -r now
4.login odoo with admin
5. go Purchase module ---> click  demo purchase order --> click print 
6. generate pdf  need  3 min ....

Hardware 16G ram, 8 core cpu , postgresql 9.5 

Video/Screenshot link (optional):
monitor ubuntu system job...
![image](https://cloud.githubusercontent.com/assets/8476734/19181128/80ea75a8-8c9d-11e6-8574-71a086650d10.png)

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Thanks a lot for your report. It sounds like Odoo has trouble finding your Wkhtmltopdf and that you haven't configured a `report.url` parameter. Can you make sure you have the parameter `report.url` under Technical parameters? (This is under Settings > Technical > Parameters > System parameters:
![image](https://cloud.githubusercontent.com/assets/6352350/19182053/3e9f029e-8c71-11e6-90b5-953da4ecf2e4.png)
This should fix your issue.

Regards,
Yenthe

**Comment by jaronemo** [comment]
Hi @Yenthe666 

Thanks!
if report.url set value ==> http://127.0.0.1  is very fast
if report.url set value ==> http://external ip is very slow !!!
odoo with  nginx use proxy mode ....

**Comment by Yenthe666** [comment]
Hi @jaronemo,

No problem, happy your issue is solved. This is because without the `report.url` the Odoo tries to find wkhtmltopdf on the website URL, which usally points in another way and results in this problem.
Closing this issue since it is fixed. 😄 

Regards,
Yenthe

**Comment by fhrancis** [comment]
Hi @Yenthe666 , and anyone who can help me with this
I have this same problem but with a variation. 
Already configured my report.url to: 
http://127.0.0.1:8069 
and 
http://0.0.0.0:8069
The slow generation of the PDF, only occurs when there is NO internet . When I have connection it works perfect.
I need to generate it even if there is no Internet in the Server.
Testing on:
Ubuntu Server 16.04
Odoo 11
wkhtmltopdf 0.12.4 with patched qt

**Comment by Yenthe666** [comment]
@fhrancis having internet or not should make no difference (locally) as far as I know. It should work just as fine if you've set the `report.url` to `0.0.0.0:8069` or `127.0.0.1:8069`.
