### ISSUE TITLE
Odoo sends email that is not compliant with RFC2822

### ISSUE THREAD

**Issue by kgoderis** [odoo/odoo#13697]
Impacted versions: Enterprise 9.0

Steps to reproduce: 
- Fill in company ("Configure company data") details with a company name that contains an &, for example "Johnson & Johnson"
  - Send an automatically generated email, for example, "send an invitation email" to a user

Current behavior:
- the email generated by Odoo will contain in the "From" field something like "Johnson, ,Johnson odoo@jnj.com", e.g. the & is converted into ", ," , which is the mailbox-list separator according to RFC2822

Expected behavior:
The From field should contain "Johnson & Johnson odoo@jnj.com"

**Comment by chris001** [comment]
According to RFC2822 (Internet message format, reference: http://www.faqs.org/rfcs/rfc2822.html ), the email address should be quoted real name followed by email in angle brackets, like `"Johnson & Johnson" <odoo@jnj.com>` or bare email address followed by real name in parentheses, such as `odoo@jnj.com (Johnson & Johnson)`.

**Comment by kgoderis** [comment]
As far as I can see in the odoo logs, it is not using " or ( ) at all. The " in my post here above were just to delimit them for the purpose of clarity

**Comment by chris001** [comment]
@kgoderis  I agree so I feel this is truly a bug and needs to be fixed.  Have you searched and found which code file is the one which composes the email incorrectly - without the double quotes or parenthesis?

**Comment by kgoderis** [comment]
Nope as I am new to odoo (and python )

**Comment by chris001** [comment]
Found it.
https://github.com/odoo/odoo/blob/59710faa0aaef6e8952a70e7405bbc92143a49ef/openerp/addons/base/ir/ir_mail_server.py
functions build_email (line 241) and send_email (around line 350).

**Comment by chris001** [comment]
This is the one for version 10: https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_mail.py
Version 9: https://github.com/odoo/odoo/blob/9.0/addons/mail/models/mail_mail.py
They're different.  Maybe version 10 has fixed this bug?

**Comment by Yenthe666** [comment]
Hi @kgoderis ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
