### ISSUE TITLE
The value of system parameter web.base.url changes automatically.

### ISSUE THREAD

**Issue by iguixa** [odoo/odoo#137061]
Impacted versions:15, 16

Steps to reproduce:

Suppose the URL to access from the web is A and the URL to access from the organization's network is B.
1. The web.base.url system parameter is set to http:\\A:port to inform users of the web portal how to establish the connection.
2. A user in the organization logs into Odoo from the organization's network using the URL http:\\B:port

Current behavior:

The value of the web.base.url parameter automatically changes to http:\\B.port, causing future registrations in the web portal to receive http:\\B:port as the connection url, which is incorrect and cannot use the web portal.

Expected behavior:

The web.base.url system parameter should not change automatically in any case.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
Well all versions really if you choose not to set the freeze parameter.

**Comment by iguixa** [comment]
Sorry. I didn't know the freeze parameter.
