### ISSUE TITLE
Image variant show in the website module

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#13702]
Impacted versions:8.0

Steps to reproduce:
to view the image does not change variants, remains that of the model
Current behavior:

website_sale form:
in the shop of the items in the first screen displays the model
when you select a product
odoo displays attributes of the variants and the relative prices
but it does not change the picture that is always that of the model
is there?

Expected behavior:
in view variant if they change the attributes and change the price must also change the image
Video/Screenshot link (optional):
Thanks for your attention, Rocco Cesetti

**Comment by JKE-be** [comment]
Hi @roccocesetti 

I have just tested on runbot and it works. Except if i don't understand your problem.

So you have one picture on the product template ("Product" in odoo) which one is visible in /shop
And you have one picture on the product product ("Variant" in Odoo) which one is visible on the product page /product/<id>

If you don't specify a picture for the variant, the picture on the template is used...

Can you confirm that all is ok for you ? 

Thanks

JKE
