### ISSUE TITLE
branch: 8.0: german account template SKR3/SKR4 not loaded

### ISSUE THREAD

**Issue by martin-hermann** [odoo/odoo#1370]
related to: branch 8.0
during account installation, after selecting template from Germany, the second view about SKR3/SKR4 fails. it shows default sales/purchase taxes values: 15.00 but without the values of 19UST / 19VST to be selected.
At the end, the pre-settings for SKR3/SKR4 are not visible.
result: even if 19% is entered, the installation is not completed and fails.

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this issue as you've stated it is working fine yourself.
Sorry for the late reply!

Regards,
Yenthe
