### ISSUE TITLE
ODOO 10 : CODA file not supported - Bank statement

### ISSUE THREAD

**Issue by yboujraf** [odoo/odoo#13711]
Impacted versions: ODOO 10

Steps to reproduce: import COD file from Belgian bank. We used the Coda file from Odoo at https://drive.google.com/file/d/0B5BDHVRYo-q5UVVMbGRxUmtpVDg/view 

Current behavior: format not recognized

Expected behavior: import all the bank statement to reconcille 
The same CODA file is supported by Odoo 8 and Odoo 9.

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/6151258/19224330/23bc9be8-8e84-11e6-9419-832cd62861e6.png)

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
Hi @yboujraf,

Thanks a lot for your report! The file you've attached is a .txt file and not a .QFX or .QIF file though. Could you attach this here so I can check it? At this point it gives the same warnings in Odoo 9:
![image](https://cloud.githubusercontent.com/assets/6352350/19228380/ff239304-8ec4-11e6-9ee7-bc0e293e03cf.png)

**Comment by yboujraf** [comment]
Dear Yenthe,

 

If you want I can send you by mail one of my coda file but don’t know which information couldn’t affect if I remove some sensitive information.

 

Best Regards,

 

BOUJRAF Youssef

**Comment by yboujraf** [comment]
Dear Yenthe, 

the coda file in text format was the CODA provided by Odoo for testing the import CODA bank statement.

Link to download the sample :

https://www.dropbox.com/s/o6fc7ys3gm5xy5p/BE54001591120197_EUR_Full_20160808.COD?dl=0

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
Hmm I have the same issue with Odoo 9.0 though.
@qdp-odoo could you give your insight on this? I'm not really familiar with this.

**Comment by yboujraf** [comment]
Dear Yenthe,

 

It is true but when I installed the module “Belgium – Import Bank CODA Statements” I will be able to import my bank statements.

 



 

When trying to find the same module for Odoo 10, this module is missing.

 

I hope it will help you.

 

 

Best Regrads,

 

BOUJRAF Youssef

**Comment by Yenthe666** [comment]
Hi @yboujraf,

It is available for V10. See:
![image](https://cloud.githubusercontent.com/assets/6352350/19300189/335cedec-9059-11e6-8219-47ad701d6db9.png)
And let us wait for the response of @qdp-odoo, he is the accounting wizard.

**Comment by yboujraf** [comment]
Dear Yenthe,
Great but please which version of Odoo 10 free or enterprise.
I got a phonecall to the Odoo support and the answer I have received is  on Odoo 10 enterprise but not in free version.
But let me know if anything else

Best Regards,
Boujraf Youssef




On Wed, Oct 12, 2016 at 8:53 AM +0200, "Yenthe V.G" <notifications@github.com> wrote:












Hi @yboujraf,



It is available for V10. See:



And let us wait for the response of @qdp-odoo, he is the accounting wizard.

**Comment by Yenthe666** [comment]
@yboujraf 
The CODA app is Enterprise only, it is not available for the communtiy.

**Comment by yboujraf** [comment]
Dear Yenthe,

 

Bad news.

Thanks a lot, we can close the issue.

 

Best Regards, 

Youssef
