### ISSUE TITLE
Debug maps for LESS/SASS

### ISSUE THREAD

**Issue by antespi** [odoo/odoo#13710]
We have been working in OCA Sprint in Brussels 2016, just before Odoo Experience 2016, to allow developers to have debug maps for LESS/SASS assets out-of-the-box (just setting debug=assets flag at URL).

After several tries we have realized that this is not possible. This is the full history in order allow other ones to debate around this matter. Maybe someone have a brilliant idea for fixing this.

You can check the code related with this matter here: https://github.com/odoo/odoo/blob/0dc03fae2c659990ec2b22255dbc51dc959437e4/odoo/addons/base/ir/ir_qweb/assetsbundle.py

**First approach**: Add a switch to lessc command line (--source-map) for generating debug map files

This is not possible because assets are compiled from stdin. There are several AssetBundle objects, each one have several Stylesheet objects. Odoo gets LESS from all Stylesheet object together adding a comment with the LESS file at the beginning of each LESS portion (https://github.com/odoo/odoo/blob/0dc03fae2c659990ec2b22255dbc51dc959437e4/odoo/addons/base/ir/ir_qweb/assetsbundle.py#L584), compile it and split the result (https://github.com/odoo/odoo/blob/0dc03fae2c659990ec2b22255dbc51dc959437e4/odoo/addons/base/ir/ir_qweb/assetsbundle.py#L321) using that comment.

**Second approach**: Add a switch to lessc command line (--source-map-map-inline) for generating debug map files

This is not possible because the inline map will be in the last portion. Browser will receive several CSS files, but only the last one will have the debug map inline. Debug maps are line and order dependent.

**Third approach**: Use another debug flag, like ?debug=maps

Then in this mode, go to the same execution path that no-debug, but add debug map inline.
This fails because in a AssetBundle we have several kind of assets (CSS, LESS, SASS) but we compile LESS together and then SASS together, getting two debug maps.

**Fourth approach**: When ?debug=maps, not split assets by AssetBundle but asset kind (CSS, LESS or SASS)

This fails because CSS is order dependent. Image this scenario:

```
AssetBundle 1:
   - CSS_A
   - LESS_B
   - LESS_C
   - CSS_D
   - LESS_E
```

CSS_A and CSS_D will be output as it in a file
LESS_B, LESS_C and LESS_E will be compile, debug map added at the end and output in a file

If LESS_E has a rule with the same match than CSS_D then it works well, because the order is not changed. But if CSS_D has a rule with the same match than CSS_C, then it works different that in no-debug mode. This is not acceptable.

This scenario is common in Odoo, because we have optional views that adds a little portion os LESS in other to change the color, make design wide fixed or make header fixed to top.

**Conclusion**: If we want debug maps we will lose some Odoo website features

We didn't find a way to have debug maps without losing current Odoo website features, even refactoring AssetBundle classes. But maybe someone have a brilliant idea to achieve this with another approach.

Please @odony feel free to share this issue to any partner related with web/website team. And thanks for your time in Odoo Experience when we talk about this matter.

cc @Yajo, @lasley

**Comment by Yajo** [comment]
You forgot one point: you can convert .css to .less just by changing the file suffix, as well as changing .css to .scss using the same technique.

Problem is that 4th approach still could fail when there are mixed .less and .scss/.sass files. So, if Odoo would use only 1 of those systems, it could work, but using 3 of them makes it this hard, if not impossible.

However supporting several systems is good, having in mind [Bootstrap 3 is in LESS (although there's an official Sass port), but v4 will be in Sass and v5 in PostCSS](https://twitter.com/mdo/status/591364406816079873).

This is hard man :confused:

**Comment by odony** [comment]
Thanks for the summary! We'll discuss it and see what we can come up with :-)

**Comment by amigrave** [comment]
Hi there,

I've already tough about how to improve the web assets management in Odoo and I think that using [DukPy](https://github.com/amol-/dukpy) for assets compilation would provide more flexibility (and future proof) for all the transcoding processes. As a bonus this would allow some developper teams to use their in-house favorite javascript transcoding language (Transcrypt, TypeScript, CoffeeScript, ...)

I mentioned that to @antonylesuisse some time ago and I think he told me he actually read the [duktape](http://duktape.org/) source code so I guess he could tell us if he agrees with the principle to add the duktape dependency in Odoo ?

Please note that I still haven't tried to integrate dukpy in Odoo yet, so I still don't know if the solution would work flawlessly, I'd be glad to work on this tough.

**Comment by Yajo** [comment]
Yes, allowing ES transpilers would be awesome, but again without debug maps it would not be feasible.

Thinking on this, just adding an interesting note: PhantomJS currently uses a very old version of nodejs. If you write any ES>=5 syntax, automated tests would fail, and since all js assets are minified and joined, a new syntax in 1 module would raise a syntax error for the whole Odoo JS.

So, until PhantomJS evolves in this sense, it would be required to have some transpiler(s) to old-style JS (or stick to it). Or help PhantomJS get fixed. Or change it for another thing. Just points you will probably like to have into account.

**Comment by amigrave** [comment]
> Yes, allowing ES transpilers would be awesome, but again without debug maps it would not be feasible.

Indeed. And this is where using duktape would *theoretically* bring more flexibility than the current cli tools because we could,  *again theoretically*, get rid of the lessc cli tool and in place use directly the javascript api in order to generate the source maps without being forced to have the resource on the filesystem:
https://github.com/amol-/dukpy/blob/master/dukpy/jsmodules/less/less/source-map-output.js

> So, until PhantomJS evolves in this sense, it would be required to have some transpiler(s) to old-style JS (or stick to it). 

Of course. Transcoding to javascript/css is going to stay for a while in the front-end landscape, not only for PhantomJS so I don't see a problem here but again, I don't know if dukpy/duktape is the solution to all those problems, I've just the feeling it's worth checking.

**Comment by pedrobaeza** [comment]
@odony (or maybe @qsm-odoo ) do you know if there is something new about this? It would be very useful now that you are working on less to scss conversion and Bootstrap 4 compatibility.

**Comment by Yajo** [comment]
I'm migrating a complex theme from Less to Scss and the situation is definitely worse than ever. It's being very frustrating. Are there any docs on the matter, at least?

**Comment by qsm-odoo** [comment]
@Yajo 

You can find some information about the way assets are split for scss generation here: https://github.com/odoo/odoo/wiki/SCSS-coding-guidelines#styling (which is basically what is explained and done by my commit https://github.com/odoo/odoo/commit/6e4db7d13a926845bf82f5b035afede42d6d5a89). This should definitely have some more detailed doc.

Basic migration was done here https://github.com/odoo/odoo/commit/97aa0a8dec384ad75eb66045f43384b6e54f1d6e, and the whole conversion through the merge commit here: https://github.com/odoo/odoo/commit/e41bcb0e311bfa67c78a13e377ae5c4931ecf24e

Note that for version 13.0, I reviewed the assets structure a little bit more with: https://github.com/odoo/odoo/commit/52ec536cef2ec84af0b36746f19a8cdf9f23fe2a

Adding debug maps would still be a cool addition but it is not a priority at the moment, I hope it will be at some point (cc @JKE-be @rdeodoo)

**Comment by Yajo** [comment]
Thanks for the tips @qsm-odoo!

I think that wiki should be linked in the docs at least. It would have saved me some hours and hairs...

Also thanks for the improvements in v13. Definitely `!default` should be used everywhere in Odoo (and BTW `!important` should be avoided).

Looking forward for the source maps... They keep becoming more important as assets keep getting more complex.
