### ISSUE TITLE
psycopg2.errors.NotNullViolation: null value in column "projection" violates not-null constraint

### ISSUE THREAD

**Issue by gianmichele-siano** [odoo/odoo#137131]
Impacted versions: 16

Steps to reproduce: 
1) ./odoo-bin scaffold test_gm ./my-addons/
remove comments from models and views
#models.py
from odoo import models, fields, api

class test_gm(models.Model):
    _name = 'test_gm.test_gm'
    _description = 'test_gm.test_gm'

    name = fields.Char()
    value = fields.Integer()
    value2 = fields.Float(compute="_value_pc", store=True)
    description = fields.Text()

    @api.depends('value')
    def _value_pc(self):
        for record in self:
            record.value2 = float(record.value) / 100

#views.xml
<odoo>
  <data>
    

    <record model="ir.ui.view" id="test_gm.list">
      <field name="name">test_gm list</field>
      <field name="model">test_gm.test_gm</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="value"/>
          <field name="value2"/>
        </tree>
      </field>
    </record>

    

    <record model="ir.actions.act_window" id="test_gm.action_window">
      <field name="name">test_gm window</field>
      <field name="res_model">test_gm.test_gm</field>
      <field name="view_mode">tree,form</field>
    </record>

    

    <record model="ir.actions.server" id="test_gm.action_server">
      <field name="name">test_gm server</field>
      <field name="model_id" ref="model_test_gm_test_gm"/>
      <field name="state">code</field>
      <field name="code">
        action = {
          "type": "ir.actions.act_window",
          "view_mode": "tree,form",
          "res_model": model._name,
        }
      </field>
    </record>

    

    <menuitem name="test_gm" id="test_gm.menu_root"/>

    

    <menuitem name="Menu 1" id="test_gm.menu_1" parent="test_gm.menu_root"/>
    <menuitem name="Menu 2" id="test_gm.menu_2" parent="test_gm.menu_root"/>

    

    <menuitem name="List" id="test_gm.menu_1_list" parent="test_gm.menu_1"
              action="test_gm.action_window"/>
    <menuitem name="Server to list" id="test_gm" parent="test_gm.menu_2"
              action="test_gm.action_server"/>

  </data>
</odoo>

If I comment out "explicit list view" with id= test_gm.list, all is ok but if I put in have this error:

psycopg2.errors.NotNullViolation: null value in column "projection" violates not-null constraint
DETAIL:  Failing row contains (2486, 16, null, 1, 1, test_gm list, test_gm.test_gm, null, tree, test_gm/views/views.xml, null, primary, {"en_US": "<tree>\n          <field name=\"name\"/>\n          <..., <?xml version="1.0"?
......
odoo.tools.convert.ParseError: while parsing /home/gio/odoo/my-addons/test_gm/views/views.xml:5, somewhere inside
<record model="ir.ui.view" id="test_gm.list">
      <field name="name">test_gm list</field>
      <field name="model">test_gm.test_gm</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="value"/>
          <field name="value2"/>
        </tree>
      </field>
    </record>

**Comment by vava-odoo** [comment]
Hello @gianmichele-siano,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards,
