### ISSUE TITLE
[16.0][BUG] sale_loyalty: Applying the actual number of free products does not update used points in sale loyalty 

### ISSUE THREAD

**Issue by Hung-Elsh** [odoo/odoo#137189]
Impacted versions: 16.0

Steps to reproduce:

- Create Loyalty Program with a reward is free product applying in Sale Order. The rule give 10 point for each bought specific  product. Reward is exchange 4 point for free product.

![image](https://github.com/odoo/odoo/assets/106657372/0b809692-2a35-4fdd-bdf5-c099c8b155a6)

- Create a Confirmed Sale Order with order line is buying 1 the specific product in loyalty rule, then add free product by using Promotions button.
- Change quantity of free product line to 1 then check remaining points

![image](https://github.com/odoo/odoo/assets/106657372/5b23ee8e-55b1-4b4f-a371-72a98b771673)

Current behavior:

- When Changing free product quantity, the points_cost fields is not update with new consumed point  -> remaing point in coupon will not update
- If the Program have more than one free product reward and the Sale order have enough point to exchange both reward, use still cannot choose other reward than the first chosen one. The reason is the linked coupon now does not have enough point to exchange other reward line.

Expected behavior:

- User can change number of free product and keep remain point in coupon for next order
- User can add more than one free product in Sale order like PoS order.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by dalaOdoo** [comment]
@Hung-Elsh thanks for the feedback. I created a bugfix ticket internally regarding this. 
I'll keep you posted

**Comment by Hung-Elsh** [comment]
> @Hung-Elsh thanks for the feedback. I created a bugfix ticket internally regarding this. I'll keep you posted

@dalaOdoo Thank you so much
