### ISSUE TITLE
Calendar recurrent error

### ISSUE THREAD

**Issue by luienper** [odoo/odoo#13727]
Impacted versions:

Steps to reproduce:

Current behavior:there are an error when we try to create a new record in calendar event, when select recurrent event and notifications

File "/home/luis/odoo_projects/odoo_10/addons/calendar/models/calendar.py", line 379, in get_next_notif
    for one_date in meeting.get_recurrent_date_by_event():
AttributeError: 'calendar.event' object has no attribute 'get_recurrent_date_by_event'

I fixed this putting an underscore at the beginning of the method's name

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @luienper,

Thank you for your report.
I've just tested this on the latest Odoo 10 and could not reproduce this issue.
Could you please try this again on a runbot (runbot.odoo.com) or give me more details on how to reproduce this?

Regards,
Yenthe

**Comment by luienper** [comment]
![screenshot from 2016-10-11 07-37-57](https://cloud.githubusercontent.com/assets/11526274/19270519/11e0b87a-8f86-11e6-8e74-818b38d1e126.png)
I recreate the issue on an runbot instance
