### ISSUE TITLE
Problem with Thousand sep in language: Polish

### ISSUE THREAD

**Issue by BartlomiejChojnackiSolvti** [odoo/odoo#137221]
Impacted versions:
16.0.20230210
Revision: 3a6736f642ee19a3e2786276d61e7b7b673eeafe

Steps to reproduce:
Set language to Polish (in Poland thousand sep should be empty)
Click at "Menu główne" (In English: 
![image](https://github.com/odoo/odoo/assets/135115665/bb7aef6e-7f12-4a26-8772-98e02e52b7b4)

Current behavior:
Internal Server Error
![image](https://github.com/odoo/odoo/assets/135115665/538839ad-334c-4840-9ac5-8d3caf136d6b)

Log:
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 240, in get_translations_for_webclient

    "thousands_sep": langs.thousands_sep.replace(' ', '\xa0'),

Expected behavior:
Odoo is working properly :)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
Commit that produced problem: https://github.com/odoo/odoo/commit/73bc3e9e7b1c2878a9d65f0b7bef5a5e1da17346

**Comment by vava-odoo** [comment]
Thansk for reporting, @BartlomiejChojnackiSolvti 
Fixed by https://github.com/odoo/odoo/pull/137254
Cheers
