### ISSUE TITLE
When clicking on button "Quotations and sales" from partner form, it shows sales of all the partners whose names contain the name of activated partner

### ISSUE THREAD

**Issue by Wided1** [odoo/odoo#13720]
Impacted versions: 7

Steps to reproduce: 
1. Create two partners:
            Partner 1 name: "abc"
            Partner 2 name: "abcde"
2. Create a quotation for each partner.
3. Open partner 1 form.
4. Click on button "Quotations and sales"

Current behavior: The two quotations appear

Expected behavior: Only partner 1 quotation appears.

Video/Screenshot link (optional):

**Comment by Wided1** [comment]
To correct this, in the sale module, file res_partner_view.xml, add in the record act_res_partner_2_sale_order  a domain:  <field name="domain">[('partner_id','=',active_id)]</field>

**Comment by JKE-be** [comment]
Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs. Anymore you have a fix for your own instance...
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,

JKE
