### ISSUE TITLE
Email with helo error (with hosttech.ch=error, with digitalocean.com = OK)

### ISSUE THREAD

**Issue by businessplus** [odoo/odoo#13725]
Impacted versions: 9

Steps to reproduce: Send Mail

Current behavior:
Mail doesn't come to receiver. But error message as follows: 
Der E-Mail-Versand ist gescheitert E-Mailversand schlug via SMTP Server
'smtp.mailbox.org' fehl. SMTPRecipientsRefused:
{'my.client@hispeed.ch': (501, '5.5.2 <[0.0.120.91]>: Helo command
rejected: invalid ip address')}

Expected behavior: Outgoing Mail should be working.  

Video/Screenshot link (optional):

> set type=mx
> mydomain.ch
> Server:  ns10.cablecom.net
> Address:  62.2.17.60

Nicht autorisierende Antwort:
mydomain.ch MX preference = 10, mail exchanger = mxext1.mailbox.org
mydomain.ch MX preference = 20, mail exchanger = mxext3.mailbox.org
mydomain.ch MX preference = 10, mail exchanger = mxext2.mailbox.org

**Comment by JKE-be** [comment]
Seems to be a problem with  smtp and not Odoo...
Please try to get help on help.odoo.com

This tracker is for Odoo issue only. If it is a problem of configuration, please uses help.odoo.com

Can you reproduce it on Runbot ?

**Comment by businessplus** [comment]
Here is the description of your further causes:

*) Your Odoo system (sp?) Sends in the SMTP protocol the information that it has the IP address "0.0.120.91". There is no IP address of this kind anywhere in the world and can not exist.

*) Well-placed mail servers will reject this information in the SMTP protocol and reject the connection setup. So with you.

*) The question is now, from where your Odoo software comes on the idea, it would be the system 0.0.120.91 - somehow it must also come to the funnel to report. Your screenshot actually showed that your virtual server does not have this IP address at all - otherwise it would be clear why Odo has this IP address and you would have to ask why the virtual server is equipped with it.

So the question is:

-Where is Odoo this information and how is this to influence?
- Is this a bug in Odoo or does your system have some crazy hidden broken IP addresses that I just could not see in the screenshot?

I would therefore turn to the question with Odoo.

*** German original
hier noch die Beschreibung zu Ihrer weiteren Ursachenforschung:

*) Ihr Odo-System (sp?) sendet im SMTP-Protokoll die Information, daß es die IP-Adresse "0.0.120.91" besitzt. Eine solche IP-Adresse gibt es nirgendwo auf der Welt und kann/darf es gar nicht geben.

*) Gut aufgesetzte Mailserver werden diese Information darum im SMTP-Protokoll zurückweisen und den Verbindungsaufbau ablehnen. So auch bei Ihnen.

*) Die Frage ist jetzt, woher Ihre Odo-Software auf die Idee kommt, es wäre das System 0.0.120.91 -- irgendwie muß es ja auch den Trichter kommen, sich damit zu melden. Ihr Screenshot hat eigentlich gezeigt, daß Ihr virtueller Server diese IP-Adresse gar nicht hat -- ansonsten wäre ja erklärlich, woher Odo diese IP-Adresse hat und man müßte sich fragen, wieso der virtuelle Server damit ausgestattet ist.

Die Frage ist also:

-Woher hat Odo diese Information udn wie ist diese ggf. zu beeinflussen? 
-Ist das ein Bug in Odo oder hat Ihr System doch noch verrückte versteckte kaputte IP-Adressen, die ich gerade im Screenshot nicht sehen konnte?

Ich würde mich mit der Frage also an Odo wenden.

**Comment by pedrobaeza** [comment]
This seems to be a deployment problem. I have been using this system for years without that problem. Check your web.base.url parameter, proxy and firewalls for solving the problem.
