### ISSUE TITLE
[10.0] work order kanbans indistinguishable

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13728]
Impacted versions: V10 (tested on saas and runbot 174780-10-0-c60e43.runbot10.odoo.com)

Steps to reproduce: place an MO where routing has several operations in several work centers. Go to manufacturing > Work orders > kanban view, remove filter

Current behavior: The kanbans show product and MO-number only. The user can distinguish neither operations nor work centers. All kanbans look the same. User has to open form view to read the breadcrumb to distinguish the kanbans.

Expected behavior: The kanbans display the operation and the work center.

**Comment by Yenthe666** [comment]
@jco-odoo this is another one for you regarding MRP.

**Comment by sle-odoo** [comment]
Hello,
This is not the case anymore, the vignettes do have their workcenters names in their title.

Regards
