### ISSUE TITLE
requirements.txt have not been updated for 10.0

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#13721]
Impacted versions: 10.0

Current behavior: requirements.txt have not been updated for a long time, many packages in that list have newer versions. If requirements.txt are to be considered as the known good configuration that works well with Odoo 10 it would good to refresh it?

@sle-odoo what do you think?

**Comment by Yenthe666** [comment]
Hmm good suggestion. I summon you @odony and @mart-e!

**Comment by JKE-be** [comment]
@sle-odoo a pip freeze on your packaging image should be easy... no ?

**Comment by sle-odoo** [comment]
The docker images are either using the current requirements.txt or the debian packages, so that would not do the trick. The easiest way would be to pip install every packages from the requirements without the pinned version and then do a ```pip freeze```.

**Comment by sbidoul** [comment]
FWIW, here is what I get from a pip freeze after a fresh pip install of odoo and odoo enterprise 10.0 (pulling all external python dependencies).

```
Babel==2.3.4
beautifulsoup4==4.5.1
decorator==4.0.10
docutils==0.12
ebaysdk==2.1.4
feedparser==5.2.1
funcsigs==1.0.2
gevent==1.1.2
greenlet==0.4.10
Jinja2==2.8
lxml==3.6.4
Mako==1.0.4
MarkupSafe==0.23
mock==2.0.0
ofxparse==0.15
passlib==1.6.5
pbr==1.10.0
Pillow==3.4.1
pkg-resources==0.0.0
psutil==4.3.1
psycogreen==1.0
psycopg2==2.6.2
pydot==1.2.3
pyparsing==2.1.10
pyPdf==1.13
pyserial==3.1.1
Python-Chart==1.39
python-dateutil==2.5.3
python-ldap==2.4.27
python-openid==2.2.5
python-stdnum==1.4
pytz==2016.7
pyusb==1.0.0
PyYAML==3.12
qrcode==5.3
reportlab==3.3.0
requests==2.11.1
six==1.10.0
suds-jurko==0.6
vatnumber==1.2
vobject==0.9.3
Werkzeug==0.11.11
XlsxWriter==0.9.3
xlwt==1.1.2
```
