### ISSUE TITLE
System parameter web.base.url.freeze with any value, freezes system parameter web.base.url

### ISSUE THREAD

**Issue by iguixa** [odoo/odoo#137209]
Impacted versions: 15, 16

Steps to reproduce: 
1. Set system parameter web.base.url.freeze with any value distinct of True (False, xxx,...)
2. Open session with admin user using a IP different from the value web.base.url

Current behavior:
The system parameter web.base.url not change

Expected behavior:
If value is not True and not False, should generate error
If value is False, should change web.base.url

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is not how it works. If present with any value, is evaluated as True.
