### ISSUE TITLE
[10.0] MRP, MPS - delete product from MPS

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13730]
Impacted versions: 10.0 enterprise (saas demo.odoo.com)

Steps to reproduce: Manufactoring > Reporting > Master Production Shedule > Add a product

Current behavior: user has no way to remove a product from MPS

Expected behavior: user has a way to remove a product from MPS

P.S. I would have placed MPS under menu Planning, not Reporting.

**Comment by Yenthe666** [comment]
@jco-odoo this looks like something for you.

**Comment by jco-odoo** [comment]
Just need to uncheck mps active field

**Comment by roedeorm** [comment]
Do you suggest turning off the entire mps in settings? Wouldn't that result in loosing the planning for all products?

**Comment by jco-odoo** [comment]
No, it is on the product form (if you open it from the constraints on the
mps)

**Comment by roedeorm** [comment]
OK, now I got it. set target > MPS active. wrote solution to help.odoo.com. Thank you.
