### ISSUE TITLE
[10.0] MRP, MPS - change in planning period without effect

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13731]
Impacted versions: 10.0 (saas)

Steps to reproduce: 
Manufacture > Settings > Use Master Production Schedule = true
Manufacture > Settings > Manufacturing Period = Monthly
Manufacture > Reporting > Master productions schedule > Add a product
Manufacture > Settings > Manufacturing Period = Weekly
Manufacture > Reporting > Master productions schedule > Add a product

Current behavior: Product added to MPS does not change period from monthly to weekly neither for the allready added product nor for a product added after changing the settings. The period that was selected in the setting when the first product was added to MPS is used until the final thermal death of the universe.

Expected behavior: When period is changed in settings, then the planning horizon in MPS changes as well.

**Comment by Yenthe666** [comment]
@jco-odoo another one for you.

**Comment by jco-odoo** [comment]
Something is to be fixed: the goal is to see the report by default in the period given.  But for all products it will be the same period.  (Need to find a way to interpret the constraints following the period set if you change period in the report)

**Comment by pedrobaeza** [comment]
@jco-odoo any news about this?

**Comment by jco-odoo** [comment]
It is not meant in the report to change periods as e.g. for the min/max/security level, they will need to be interpreted differently.  There have been fixes after, so this is not relevant anymore.  I close.
