### ISSUE TITLE
[10.0] mrp - planning by work center

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13735]
Impacted versions: 10.0 saas

Steps to reproduce: 
place several MOs of the same product which has several operations in the same work center.
place several MOs of an other product which has the same routing as the first product.
open Planning > Planning by work center
Try do some planning of the operations

Current behavior: it is impossible to know which gnatt line represents the operation of a particular MO or particular product. They all look the same. This renders the view literally useless for planning purposes.

Expected behavior: The gnatt row description displays: product, MO-number. Mouse over info wouldn't be bad either.

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback on this?

**Comment by jco-odoo** [comment]
That is more for improvement.  If you click on it, the form view of the work order pops up

**Comment by roedeorm** [comment]
@jco-odoo Hi  Josse. Thank you. What's the purpose of this view if nonot for planning operations?

**Comment by roedeorm** [comment]
It can be solved by the standard group by functionality for MO-number. It would be great to add product to the fiedls for which group by is possible.

**Comment by pedrobaeza** [comment]
@jco-odoo is this improvement planned or should we discard it?

**Comment by jco-odoo** [comment]
I remember thinking about a way to add it to the current Gantt view (by changing its xml), but somehow it was not that straightforward.
