### ISSUE TITLE
[10.0] mrp - gnatt planning: moving MO does not move operations

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13734]
Impacted versions: 10.0 (saas), on firefox and safari on osx as well as on firefox on linux mint.

Steps to reproduce: 
create a MO with at least two operations.
Planning > Planning by production
try changing the position of the blue MO line to the left and to the right

Current behavior: changing the blue MO backwards in time works, changing blue MO line forward in time does not work. When moving the blue MO line, the greenish work orders lines do not move.

Expected behavior: When moving the blue MO line in time, the greenish work order operations lines move with it without changing the position relative to each other.

**Comment by Yenthe666** [comment]
@jco-odoo this looks like something for you.

**Comment by jco-odoo** [comment]
It was never meant like that: you plan work orders, not production orders (which are the result of planning work orders).  But then you should not be able to move the line either maybe.

**Comment by roedeorm** [comment]
Hi jco-odoo,  thanks for looking into it. Assume you have a production order with 20 operations. How do you move all work orders by 3 hours? Each one individually?

**Comment by pedrobaeza** [comment]
This is answered assuming that yes: there's no batch re-planning.
