### ISSUE TITLE
[10.0] mrp - work orders: planned date contradicts expected duration

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13732]
Impacted versions: 10.0 (saas)

Steps to reproduce: create a manufacturing order with work order. Open form view of work order. Edit Expected Duration and observe the "to" date of Planned Date. Edit the two dates of Planned Date and observer Expected Duration.

Current behavior: Expected Duration and the two date fields in Planned date are independent. They do not influence each other.  The implied duration between from and to date of field Planned date can contradict the value in field Expected duration.

Expected behavior: When Expected Duration is changed, the to date of Planned Date is changed. When to or from date of Planned date are changed, then Expected Duration is changed.

The above is also true when changing start and stop date via draggin in the calender view.

**Comment by Yenthe666** [comment]
@jco-odoo this looks like something for you.

**Comment by jco-odoo** [comment]
It is good that the dates and the expected duration don't influence each other as it is the most flexible this way.  You can not also subtract them as they take the calendar into account, ...  The expected duration is meant to be fixed (but can be altered if what is given by the routing would not match somehow)
