### ISSUE TITLE
[10.0] mrp - chained operations ignored in planning

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13733]
Impacted versions: 10.0

Steps to reproduce: place an MO with at least two operations. Set Next Operation=Once all products are processed in the first operation.

Current behavior: second operation can be planned before the first operation. When the to-date of Planned date of the first operation is moved in time, the from date of Planned date of the second date is not changed.

Expected behavior: The sequence of the operation is not changed by planning when next operation is set to "Once all products are processed in the first operation". When to date of operation 1 is changed, then from date of the folling chained operation is changed by the same delta time.

**Comment by Yenthe666** [comment]
@jco-odoo this looks like something for you.

**Comment by jco-odoo** [comment]
The "Once all products are processed" is only for the planning algo as later you might decide to plan work orders in parallel or in an entire different order (based on what is possible)

**Comment by roedeorm** [comment]
@jco-odoo I see. That makes changing time of operation that depend on each other difficult as each operation has to be moved separately and manually placed conjoined.

**Comment by jco-odoo** [comment]
You can still unplan/plan again

**Comment by roedeorm** [comment]
Which places the operations at the earliest possible slot, right? And from there I want to move it by 3 hours.

**Comment by pedrobaeza** [comment]
This seems answered, so I close.
