### ISSUE TITLE
[10.0]It is weird to enable auto_install with utm module.

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#13739]
Impacted versions:
10.0
Steps to reproduce:
Create a new database and change to debug mode.
Current behavior:
utm module auto installed and shows Link Tracker top menu in debug mode.
Expected behavior:
do not install it automatically. set 'auto_install': False in __manifest__.py file.
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Thanks for the reporting.
It has been fixed in v8: https://github.com/odoo/odoo/commit/4ca06e02558b202183592f4d7c67f76f302bc0d1 & https://github.com/odoo/odoo/commit/633780a00c33089a5bd6fbbd9388ed37d46d59b9

That will be forward-ported to next version asap.
