### ISSUE TITLE
Invoice mail template does not format currency decimals

### ISSUE THREAD

**Issue by dieck** [odoo/odoo#13736]
Impacted versions: 10.0

Steps to reproduce: send yourself an invoice via mail, with default template

Current behavior: shows 4.7 EUR

Expected behavior: should show 4.70 EUR

Video/Screenshot link (optional):
![odoo-invoice-mail](https://cloud.githubusercontent.com/assets/670562/19261094/2db8329a-8f8f-11e6-9824-13436421aebd.png)

**Comment by JKE-be** [comment]
Hello,

All templates are not already converted to Qweb.
For old template using Jinja, it can be the case... But it should be fixed in the next month updating the template to Qweb.

Some collegua's are currently working on it.
