### ISSUE TITLE
[10.0] mrp - wo: Planned date accepts end date-time before start date-time

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13752]
Impacted versions: 10.0 saas

Steps to reproduce: place a MO with WO. Open WO. Set to-date in Planned date before from-date.

Current behavior: a to-date earlier than from-date is accepted.

Expected behavior: a to-date earlier than from-date is prevented

**Comment by Yenthe666** [comment]
@jco-odoo another one for you.

**Comment by Yenthe666** [comment]
@lap-odoo could you have a look please?

**Comment by lap-odoo** [comment]
@roedeorm I agree this could be improved, I'll add this in our backlog for the master version. Thanks for your feedback.

(backlog: 36031)
