### ISSUE TITLE
[10.0] import data report raise error "Unknown error during import: <type 'exceptions.TypeError'>: 'bool' object is not iterable at row 2"

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#13759]
Impacted versions:
10.0

Steps to reproduce:

export some data from model 'product.template' as data import template.

modify the template to add the your own data.

switch to product list view, and import data from the template file.

Current behavior:

even just import one field into the model. it should report  Type Error

Expected behavior:

import data correctly.

Video/Screenshot link (optional):

![qq 20161012154221](https://cloud.githubusercontent.com/assets/1404460/19301513/80076472-9092-11e6-8a6b-6a46d18b4eec.png)

**Comment by JKE-be** [comment]
hello

Thanks for the reporting.
I have just tested now on last runbot, and I cannot reproduce.

Could you just post your csv content ?
You can also check that you don't have an empty line at the end ? 


Here, my file:

> "id","name"
> ,"Apple In-Ear Headphones JKE"
> ,"Apple Wireless Keyboard JKE"

**Comment by jeffery9** [comment]
CSV file encoding is GB18030

**Comment by jeffery9** [comment]
test in another database is ok.  sorry, this maybe is not a bug.

**Comment by Yenthe666** [comment]
Thank you for the feedback and closing it. 👍
