### ISSUE TITLE
Odoo 8: The editing line is above the correct postion of one2many field

### ISSUE THREAD

**Issue by yueming** [odoo/odoo#1375]
impacted versions:
8.0

Steps to reproduce:
1. Login on Chrome (Firefox is okay)
2. Try to Create an object, enter into the creation form.
3. There is an one2many field in this creation form.
4. Scroll the form to see the "Add an item" link of the one2many field.
5. Click the "Add an item" link.

Current behavior:
The editing line is above the correct postion.
Please look at picture in
https://www.evernote.com/shard/s188/sh/8a61da7b-bbf2-4086-9d5a-a7948781d563/ed811f11c564fe5ecea344663b2eafca

Expected behavior:
The editing line is at the correct postion.

**Comment by cysnake4713** [comment]
have this problem too, did this bug is offical fixed @yueming  ?

**Comment by mlaitinen** [comment]
We also have a workaround for this. Add this to a custom css:
```
.oe_formview {
	position: relative;
}
```
So far we haven't seen anything else break due to this fix.

**Comment by cysnake4713** [comment]
@mlaitinen your fix is working great, have you pulled a request yet?

**Comment by mlaitinen** [comment]
Here it goes, @cysnake4713

**Comment by Yenthe666** [comment]
Hi @yueming,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
