### ISSUE TITLE
[10.0] mrp - planning: gnatt/calender view of finished MO/WO show planned date not effective date

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13754]
Impacted versions: 10.0 saas

Steps to reproduce: place a mo with wo and finish it. Planning > Planning by production or Planning by Workcenter > gnatt view / calender view

Current behavior: all mo/wo are shown as planned date independent of their state.

Expected behavior: mo/wo in state finished are shown as effective dates and not planned dates. mo/wo with states other than finished are shown as planned dates. Lets assume you planned for 6 hours but finised in 2 hours. Now the remaining 4 hours should be shown as open to be used in the gnatt/calender view so that other operations can be placed there.

Suggestion: mark finished mo/wo in gnatt/calender view by colour, for example a greyish blue and greyish green respectively. That prevents user from having to open each wo to check if it is finished. This would help the purose of the view a lot.

**Comment by Yenthe666** [comment]
@jco-odoo another one for you.

**Comment by Yenthe666** [comment]
@lap-odoo could you look at this one too?

**Comment by jco-odoo** [comment]
I understand the logic, but we should not change this in v10.0, but think about how we can adapt it later on.  @lap-odoo   We could easily create a computed field as the combination of effective and planned dates depending on the state.

**Comment by lap-odoo** [comment]
@roedeorm I agree it's a good feedback, I've also added this in our backlog (36031)
