### ISSUE TITLE
[10.0] invisible attrs not working in tree views

### ISSUE THREAD

**Issue by eLBati** [odoo/odoo#13751]
Impacted versions:

10.0

Steps to reproduce:

Go to **Manufacturing Orders**, open a **done** MO

Current behavior:

**Quantity Available** field is visible

Expected behavior:

**Quantity Available** field should be invisible because defined as
```
<field name="quantity_available" attrs="{'invisible': [('is_done', '=', True)]}"/>
```

**Comment by Yenthe666** [comment]
@jco-odoo another one for you.

**Comment by JKE-be** [comment]
Hello @eLBati 

the attrs invisible, hide the cell, not the column.
Here, you are in a case where all is hide, or all is shown... so it seems to be strange... But you could have some row where the info is shown, and others that hide the info.

**With attrs invisible**
![image](https://cloud.githubusercontent.com/assets/4848797/19306443/02e3ee28-9076-11e6-9dfa-83059ce1e65c.png)

**Without attrs invisible**
![image](https://cloud.githubusercontent.com/assets/4848797/19306481/2921b1ce-9076-11e6-80ae-ecae5a4ee708.png)

**Comment by JKE-be** [comment]
Here, a duplicated post: https://www.odoo.com/forum/help-1/question/hide-column-tree-view-31040#answer_31060

**Comment by eLBati** [comment]
@JKE-be thanks
