### ISSUE TITLE
[10.0] mrp - Planning by Production: No filter by production

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#13753]
Impacted versions: 10.0

Steps to reproduce: Manufacturing > Planning > Planning by production. 

Current behavior: No filter by MO-number in any of the view.

Expected behavior: When planning "by production", user expects filter by production

**Comment by Yenthe666** [comment]
@jco-odoo another one for you.

**Comment by roedeorm** [comment]
@jco-odoo May be I'm getting this wrong. Does "Planning by Production" mean "Planning by Manufactoring Order"? If yes, I suggest renaming for concistency reasons.

However, in my opinion the destingishing between "Planning by Workcenter" and "Planning by Production" is unneeded and confusing. It is just two different group by effective only in gantt view. All other views are identical except for "Planning by Production" not showing operations in state cancelled. It doesn't belong in menu but should be solved by standard odoo features of "save current search" in favourites. Simpler.

**Comment by amoyaux** [comment]
@lap-odoo

**Comment by jco-odoo** [comment]
Indeed, it is just to group by in the gantt by production order, so you would see which steps happen when for the production order.  I think the filter for not done/cancel should be there in both cases, but maybe also shown in the search view.  Need to compare with v11 too.

**Comment by pedrobaeza** [comment]
@jco-odoo any news on this?

**Comment by jco-odoo** [comment]
You can search on manufacturing order in the gantt view.
