### ISSUE TITLE
Issue when sending mail and open the attached file 

### ISSUE THREAD

**Issue by atuljain** [odoo/odoo#1376]
Hello 

I have an issue when i try to send mail  in Odoo-saas5 

![screenshot from 2014-07-25 17 19 32](https://cloud.githubusercontent.com/assets/4609643/3701436/0fc8196e-13f2-11e4-87ad-ef52652fd46e.png)

 i am reproducing it here 

![screenshot from 2014-07-25 17 19 50](https://cloud.githubusercontent.com/assets/4609643/3701452/3b6fba54-13f2-11e4-8830-e63ef3078840.png)

then when i click on attached quotation(SO008_.pdf) it raise the internal error 

![screenshot from 2014-07-25 17 20 19](https://cloud.githubusercontent.com/assets/4609643/3701455/4e02df52-13f2-11e4-9d92-3dfa7508a928.png)

**Comment by Yenthe666** [comment]
Hi @atuljain,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
