### ISSUE TITLE
[WEB] [Courses] Partner onboarding - review section - has leaked private email addresses

### ISSUE THREAD

**Issue by tudorion** [odoo/odoo#137640]
Impacted versions: web

Steps to reproduce: 
1. go to https://www.odoo.com/slides/partner-onboarding-project-leader-64
2. go to "reviews" section

Current behavior:
A lot of apparently leaked private emails are listed there in plaintext. It seems that comments are added automatically when users respond to an automated email address (notifications{AT}mail.odoo.com)

Expected behavior:
Only comments and reviews should be displayed, not entire email threads with private email addresses 

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/4848797/4b0b9e28-f71d-42fc-8dd9-9ab13f7811c7)

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
It has been unpublished.
Thank you for reporting
