### ISSUE TITLE
invalid syntax in xml 

### ISSUE THREAD

**Issue by jerzyk** [odoo/odoo#137659]
in 
https://github.com/odoo/odoo/blame/fec898d148de163af49c1d1cdd4022f17bfdcb9e/addons/account/static/src/components/tax_totals/tax_totals.xml#L89

attribute style has two apostrophes (') at the begininng and end of the "style"attribute - this is incorrect

apostrophe should be removed or t-attr-attribute should be used for computation

**Comment by PallaviSrivastavaa** [comment]
Hi @jerzyk, I'm just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by jerzyk** [comment]
I'm not an admin here

**Comment by PallaviSrivastavaa** [comment]
@jerzyk ohh understood

**Comment by vava-odoo** [comment]
Thanks @jerzyk for reporting and @PallaviSrivastavaa for fixing it (with https://github.com/odoo/odoo/pull/138456)
