### ISSUE TITLE
[9.0] List view editable - delete previous line in quotation raise "Cannot read property 'id' of null" 

### ISSUE THREAD

**Issue by aspitrine** [odoo/odoo#13778]
Impacted versions:
9.0

Steps to reproduce:
Create a quotation, 
Add one product
Add another product and when you are in update line mode click on delete line button for the first product.

Current behavior:
Error

Expected behavior:
Success

Video/Screenshot link (optional):
![action](https://cloud.githubusercontent.com/assets/3731837/19317639/f18f6dc0-90a5-11e6-9363-aa5b38b3fa6e.png)

![result](https://cloud.githubusercontent.com/assets/3731837/19317643/f6c9940a-90a5-11e6-98bf-8652b652ea60.png)

**Comment by JKE-be** [comment]
@ged-odoo @aab-odoo 

`self.editor.save().then(function (attrs) {`
list_view_editable.js, attrs is undefined, so attrs.id failed

**Comment by aab-odoo** [comment]
@JKE-be @ged-odoo i take it
