### ISSUE TITLE
[9][10.0] Product's Decimal precision, pushe on weight and pushed/pull flow can't be saved 

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#13784]
Impacted versions: odoo 10.0 nightly

Steps to reproduce:

![20161013133731](https://cloud.githubusercontent.com/assets/3096827/19337891/a1249846-914b-11e6-9f71-f0158248d78f.jpg)

Product's Decimal precision on weight can't be saved

**Comment by pedrobaeza** [comment]
@JKE-be is this still unfixed?

**Comment by JKE-be** [comment]
It has been fixed meanwhile. (by PR #19979)

Thanks for reporting.
