### ISSUE TITLE
[10.0] Import error on datetime field

### ISSUE THREAD

**Issue by sajinaziz** [odoo/odoo#13783]
Impacted versions: 10c

Steps to reproduce: Try to import quotation with customer  , Expiration Date and Order Datetime

Current behavior: Error (value: 21-10-2016 11:00:00 does not match date format)
if  date format changed to DD-MM-YYYY HH:mm  then Error on Expiration Date

Expected behavior: Separate format for date and datetime fields 

Video/Screenshot link (optional): 
![error 1](https://cloud.githubusercontent.com/assets/15812167/19337528/f2165c5a-9126-11e6-8609-91c006d93481.jpg)
![error 2](https://cloud.githubusercontent.com/assets/15812167/19337527/f214eb54-9126-11e6-99c5-d0a0daa404de.jpg)

**Comment by JKE-be** [comment]
Related PR #13803
