### ISSUE TITLE
[10.0] Editable list of many2one does not display correctly

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#13780]
Impacted versions: 10 (pulled 10 minutes ago)
This is probably related to this old v7 bug which got closed but was never really fixed https://github.com/odoo/odoo/issues/3964 . 

Steps to reproduce:
While this can be reproduced many ways, the common theme is that you have an editable tree view, inside of an editable tree view.

Setup (or just install testo2m from https://github.com/gdgellatly/odoo_bug_demos.git)
- Add an m2o field to sale_order_line call testm2o
- Add an o2m field to testm2o called testo2m
- Add testm2o to sale order form view
- Add an editable tree view to testm2o for testo2m

Reproduction
- Create a sale order and add a line, click create and edit for the m2o relation, 
- Try and enter data in the editable tree

Current behavior:
Everything works as expected except -
The values just disappear as you enter them.
Upon save the values are there.
On edit, changes are not reflected.

Expected behavior:
Values are reflected correctly

Video/Screenshot link (optional):
![What it looks like entering](https://cloud.githubusercontent.com/assets/5093264/19325095/14371604-9121-11e6-8399-a8d034e95529.png)
![What it looks like after opening after save](https://cloud.githubusercontent.com/assets/5093264/19325049/dcc8f2aa-9120-11e6-9dd8-b7e44f908772.png)

**Comment by JKE-be** [comment]
@ged-odoo You have probably already spotted the bug in #3964... Can you take a look ?

**Comment by gdgellatly** [comment]
@JKE-be are you sure that commit closes this issue.  I'm pretty sure it doesn't.

**Comment by gdgellatly** [comment]
@ged-odoo @JKE-be This is partly holding up a rather large enterprise agreement.  Customer is on v7 without updates since this regression.  It is literally the most important thing.  If I get the agreement done, would it get fixed under opw?  Or is there any way to work around it?

**Comment by gdgellatly** [comment]
@ged-odoo after some more research, it is most definitely that commit that introduces it, see below from mailing list

All I did as a test in frustration is revert line 473 of list_view.js such that it read (essentially reverting the commit identified in issue 3964
```javascript
_(_.keys(values)).each(function(key){
    record.set(key, values[key], {silent: true});
// _.each(values, function (value, key) {
//     if (fields[key] && fields[key].type === 'many2many')
//         record.set(key + '__display', false, {silent: true});
//     record.set(key, value, {silent: true});
```
and everything worked perfectly as expected.  So I guess my questions are now:

What exactly is this piece of code doing, i.e. how do they differ?
The commented code was introduced, so that m2m tags did not display upon deletion, is there another way of approaching this, such that the original issue is fixed without regression?

To me it looks like a simple oversight, the code looks roughly equivelant if we reduce it (assuming the if statement fails), but in the case of new records it is not displaying a value.

```javascript
_(_.keys(values)).each(function(key){
    record.set(key, values[key], {silent: true});

.each(values, function (value, key) {
    
    record.set(key, value, {silent: true});
```

**Comment by hbrunn** [comment]
any possibility this is fixed by this commit? https://github.com/OCA/OCB/commit/25616b9f2bbca3f03dbde1dc81a57986241c1aab

**Comment by gdgellatly** [comment]
@hbrunn thanks for your work here, I confirm this fixes the issue

**Comment by pedrobaeza** [comment]
Should this be backported in OCB for any of the prior versions?

**Comment by hbrunn** [comment]
sure. But on the other hand, we might better fix  the root cause and patch underscore. But on the other hand, the problem is known and documented: http://underscorejs.org/#each, so fixing this might not be as simple.

**Comment by hbrunn** [comment]
how about a warning (maybe even error) in mtq that fields called `length` can have unintended side effects (think of all the addons in the web repo that might produce garbage here), and that the field should better be called extent, size, duration or whatever else fits?

**Comment by pedrobaeza** [comment]
The problem is in the JS linter, that I'm not sure which are the possibilities with it. Maybe @moylop260 can answer us. About the patches, can you please make them?

**Comment by hbrunn** [comment]
I leave the honors to @gdgellatly

**Comment by moylop260** [comment]
@hbrunn could you create a issue in mqt of what is the new lint required, please?
