### ISSUE TITLE
[10.0] Changing Standard Cost Produces Error

### ISSUE THREAD

**Issue by tenxor105** [odoo/odoo#13785]
Impacted versions: 10

There is something wrong with the logic of the below code in stock_account module inside product.py file:

```
diff = product.standard_price - new_price
    if diff:
        raise UserError(_("No difference between standard price and new price!"))
```

I believe the condition should be 'if not diff.' Otherwise, user cannot change the standard price at all.

**Comment by Yenthe666** [comment]
@jco-odoo this looks like a bug indeed. Could you look at it? 👍
