### ISSUE TITLE
master - 16 - Wrong tax amount in a vendor bill

### ISSUE THREAD

**Issue by pablohmontenegro** [odoo/odoo#137925]
Impacted versions: master, 16

Steps to reproduce:
Create a vendor bill like the bill in the image:
![image](https://github.com/odoo/odoo/assets/89547436/dee5de40-46b7-48a3-88c2-49c989eea891)
The total tax amount is wrong, if the untaxed amount is 7.02 and the aliquot is 22% then the tax amount must be 1.54 and not 1.55

Current behavior:
If the untaxed amount is 7.02 and the aliquot is 22% then the tax amount is 1.55.

Expected behavior:
If the untaxed amount is 7.02 and the aliquot is 22% then the tax amount is 1.54.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
https://www.odoo.com/es_ES/my/tasks/3543610
Task Adhoc: 34023

**Comment by gdgellatly** [comment]
Only if rounding is set to global and not per line. I don't know if it is or not, but pretty important missing information.
