### ISSUE TITLE
Website_sale dublicate of method website_publish_button

### ISSUE THREAD

**Issue by kkinateder** [odoo/odoo#13795]
Method is in there twice!

https://github.com/odoo/odoo/blob/9.0/addons/website_sale/models/product.py#L165

https://github.com/odoo/odoo/blob/9.0/addons/website_sale/models/product.py#L169

regards,
Karsten

**Comment by Yenthe666** [comment]
Hi @kkinateder,

Thanks a lot for your report, the method does indeed exist twice.
I've just created a PR to remove one of both functions. @mart-e could you merge that?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @kkinateder,

This issue has been fixed here: https://github.com/odoo/odoo/commit/cfe0dc6d3442f31ffb1638595daf330dc225b34c

Regards,
Yenthe
