### ISSUE TITLE
[10.0] eCommerce checkout fails with Firefox

### ISSUE THREAD

**Issue by saulih** [odoo/odoo#13805]
Impacted versions: 10.0

Steps to reproduce: attempt to complete checkout process using Firefox browser
Current behavior: after selecting payment method and clicking "Pay Now" nothing happens
Expected behavior: should redirect to PayPal or whichever payment method was selected

Tested on latest nightly build of Odoo 10 community edition and free trial of hosted enterprise edition, same behaviour occurs with current version of Firefox browser. No errors are reported on server or browser logs. 

Checkout with MS Edge and Chrome browsers works normally. Firefox tested on 3 separate workstations and mobile (android).

**Comment by Yenthe666** [comment]
Hi @saulih,

Thanks a lot for your report!
I've just tested this on the latest Odoo 10 and can confirm that this is a bug:
![image](https://cloud.githubusercontent.com/assets/6352350/19377035/253049ae-91e3-11e6-9230-3abb4d561702.png)
@JKE-be can you look at this please?
