### ISSUE TITLE
[10.0] delivery module overrides stock.picking put_in_pack function and changes return value

### ISSUE THREAD

**Issue by emorris00** [odoo/odoo#13804]
Impacted versions: 10

The put_in_pack function returns the created package unless you install the delivery module which makes it return either false or an act_window action.

**Comment by JKE-be** [comment]
Hello,

Please, follow the template...

> 
> Impacted versions:
> Steps to reproduce:
> Current behavior:
> Expected behavior:
> Video/Screenshot link (optional):

Until now, I m just reading somebody that write what the code do !

**Comment by emorris00** [comment]
Impacted versions: 10
Steps to reproduce: Use put_in_pack function while delivery module is installed
Current behavior: False or action is returned
Expected behavior: Package is returned

**Comment by emorris00** [comment]
Why was this closed?

**Comment by JKE-be** [comment]
We always don't know how to reproduce it . 

Read guide lines: https://github.com/odoo/odoo/wiki/Contributing

> 
> Steps to reproduce:
> 
>  1. create a new sale order
>  2. add a line with product 'Service', quantity 2, unit price 10.0
>  3. validate the sale order
> 

I understand that the function is not clean and the return can be altered according the module installed... But you don't specify in which case it is a problem in the use of Odoo... ?

**Comment by emorris00** [comment]
I don't think you understand, the mere fact that it changes the return value is the bug. I have code I wrote for Odoo 9 that uses the stock.picking put_in_pack function and relies on it returning the package it created. In Odoo 10 the delivery module breaks it because it changes the put_in_pack function to not return the package. That is a bug. I far as I can tell it doesn't break anything in the Odoo source because there is never a place that relies on the put_in_pack function returning a package except (ironically) for the place that introduces the bug.

**Comment by sle-odoo** [comment]
This is kind of fixed by d744f8d912bfac96591f0c2d66e4f9d0ee046dfb.
`_put_in_pack` always return and does the same thing, however there's a behavior change when delivery is installed and it is expected.

Regards
