### ISSUE TITLE
[10.0] filestore contents deleted by gc while creating first database

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#13808]
Impacted versions:
10.0

Steps to reproduce:

1.fresh install ubuntu 16.04.1 and odoo 10.0 latest source code and depends libs.
2.start odoo by run 
`/home/odoo/odoo-dev/odoo-server/odoo-bin -c /home/odoo/odoo-dev/community.conf`
3.open web browser, http://localhost:8069
enter new database options
- Database Name: demo, 
- Email: admin
- Password: as you want
- Language: English
- Country: United States (This is very important otherwise you cannot re-produce the issue)
- Check "Load demo data" checkbox
  click continue button

Current behavior:
Command line reported error during generating new database:

```
2016-10-14 06:32:46,817 2361 INFO demo odoo.addons.base.ir.ir_http: Generating routing map
2016-10-14 06:32:52,291 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/ HTTP/1.1" 200 -
2016-10-14 06:32:52,336 2361 INFO demo odoo.addons.base.ir.ir_attachment: filestore gc 349 checked, 9 removed
2016-10-14 06:32:52,357 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/2e/2ef882f84c89c3634d210d011ec61b9144cddc13
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/2e/2ef882f84c89c3634d210d011ec61b9144cddc13'
2016-10-14 06:32:52,383 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/342-825761c/web.assets_common.0.css HTTP/1.1" 200 -
2016-10-14 06:32:52,401 2361 INFO demo odoo.addons.base.ir.ir_autovacuum: GC'd 0 user log entries
2016-10-14 06:32:52,416 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/ef/ef90a0c13bc75a6927d4dc43a6997051168f2287
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/ef/ef90a0c13bc75a6927d4dc43a6997051168f2287'
2016-10-14 06:32:52,419 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/51/514b7968142c494c569d209d184985ae5babac45
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/51/514b7968142c494c569d209d184985ae5babac45'
2016-10-14 06:32:52,436 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/343-a7d549d/web.assets_backend.0.css HTTP/1.1" 200 -
2016-10-14 06:32:52,440 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/37/37e8b0675e0d2722861b1bbbf31d1ca8f0816605
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/37/37e8b0675e0d2722861b1bbbf31d1ca8f0816605'
2016-10-14 06:32:52,447 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/344-a7d549d/web.assets_backend.1.css HTTP/1.1" 200 -
2016-10-14 06:32:52,447 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/cf/cf7435f9c0959a8ff500c5d8b1e82de480ca731d
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/cf/cf7435f9c0959a8ff500c5d8b1e82de480ca731d'
2016-10-14 06:32:52,468 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/347-825761c/web.assets_common.js HTTP/1.1" 200 -
2016-10-14 06:32:52,477 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/345-ce848ff/web_editor.summernote.0.css HTTP/1.1" 200 -
2016-10-14 06:32:52,479 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/b3/b34488fd73a751b68cc014731e625e10130f8d02
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/b3/b34488fd73a751b68cc014731e625e10130f8d02'
2016-10-14 06:32:52,497 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/346-cbe0fa6/web_editor.assets_editor.0.css HTTP/1.1" 200 -
2016-10-14 06:32:52,497 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/e1/e1bf7b2e69460e68f9e6fb61fece8fa83f7bc96b
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/e1/e1bf7b2e69460e68f9e6fb61fece8fa83f7bc96b'
2016-10-14 06:32:52,498 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/38/38b74389d6dfab413e09aedfb39028afdada5725
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/38/38b74389d6dfab413e09aedfb39028afdada5725'
2016-10-14 06:32:52,503 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/349-ce848ff/web_editor.summernote.js HTTP/1.1" 200 -
2016-10-14 06:32:52,505 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/348-a7d549d/web.assets_backend.js HTTP/1.1" 200 -
2016-10-14 06:32:52,508 2361 INFO demo odoo.addons.base.ir.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/demo/77/77ba38750ee153d70e633e7fd93aa60af588fe76
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/odoo/.local/share/Odoo/filestore/demo/77/77ba38750ee153d70e633e7fd93aa60af588fe76'
2016-10-14 06:32:52,509 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/content/350-cbe0fa6/web_editor.assets_editor.js HTTP/1.1" 200 -
2016-10-14 06:32:52,518 2361 INFO demo werkzeug: 127.0.0.1 - - [14/Oct/2016 06:32:52] "GET /web/binary/company_logo HTTP/1.1" 200 -
```

<img width="455" alt="reportbug1" src="https://cloud.githubusercontent.com/assets/1243299/19380336/7157f282-9229-11e6-8ecc-4067a7e210b6.png">
The web page is abnormal.
After checking the code, I found the issue may cause by -- odoo.addons.base.ir.ir_attachment: filestore gc.
The "_file_gc" function in ir_attachment.py deleted these useful 9 files, such as filestore/demo/2e/2ef882f84c89c3634d210d011ec61b9144cddc13 ......
Note: this bug only happened in the first time we create new database with above options in a new install environment. 
I guess maybe "_file_gc" does not get correct parameters during the process.
It be invoked too early, and these 9 files has not been added in gc checklist yet.

Expected behavior:
The "_file_gc" function does not deleted these useful 9 files.
Video/Screenshot link (optional):

**Comment by fdelapena** [comment]
> Note: this bug only happened in the first time we create new database with above options in a new install environment. 

Also fails for me the first time but also without including demo assets.

As you point, a workaround is going to /web/database/manager, delete the existing and then creating it again, and these assets won't be deleted this time.

**Comment by helen5106** [comment]
anyone solved this issue?

**Comment by alexis-via** [comment]
It seems I've been hit by this bug too. This is independant from the demo data parameter (False here) and from the Country of course (France here).

**Comment by sbidoul** [comment]
I've sen that too. I did not investigate so far.

**Comment by wilbyang** [comment]
I have the same issue. It appears on Chrome, but looks fine with Firefox Browser

**Comment by Yenthe666** [comment]
I've just tested this and face the same issues. @KangOl any update on this? Quite an annoying problem..

**Comment by fdelapena** [comment]
> I have the same issue. It appears on Chrome, but looks fine with Firefox Browser

I guess it is not browser related, it happened to me with Firefox here. The point is once you remove the first database created before trying again, it won't fail in the second attempt.

**Comment by websiteduck** [comment]
I ran into the same problem except deleting the database (using /web/database/manager) and creating a new one does not fix the issue for me.

**Comment by jupiterkenji** [comment]
I applied the fix to my odoo folder but doesn't seem to work. 

But I notice that my troubled-database doesn't exist in /var/lib/odoo/filestore, so I copied other database folder in there and named it my folder and it works.

**Comment by sadque** [comment]
i think its bcz of cached data, clean it and try again,

**Comment by piqoni** [comment]
I faced this issue when I enabled Developer Mode with Assets.

**Comment by falinwa** [comment]
@sadque What cached data do you mean? And how can I clean it?

**Comment by diezcode** [comment]
I have a nearly same issue. I have a backup .zip from a odoo10 database. I restore it in an other odoo10. When I try to debug it now on an other port I get the same screen as above and this error:

2017-05-23 08:47:56,558 18119 INFO odoo_debug_init odoo.addons.base.ir.ir_attachment: _read_file reading /home/stee/.local/share/Odoo/filestore/odoo_debug_init/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61
Traceback (most recent call last):
  File "/odoo10/odoo10-server/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = open(full_path,'rb').read().encode('base64')
IOError: [Errno 2] No such file or directory: u'/home/stee/.local/share/Odoo/filestore/odoo_debug_init/f3/f3f11e52a3ead336749157f46e1c8d8a07de8b61'

It seems like after a restore there is missing something...
![restore_problem_1](https://cloud.githubusercontent.com/assets/7522882/26346382/4fd3743a-3fa6-11e7-8f22-c2f9ace71ce9.PNG)
![restore_problem_2](https://cloud.githubusercontent.com/assets/7522882/26346389/53c0c912-3fa6-11e7-8892-f5f85e415668.PNG)

I have no idea why the restore is a problem when you try to debug odoo10 ..

**Comment by matteocanella** [comment]
I have exactly the same problem as described by diezcode above.
If I import my  Odoo 10 database in a freshly installed Odoo 10, I have the missing file error in the "filestore" folder and the broken white-blank screen in the web interface.

I tried to export the database in both ZIP file (includes filestore) and pg_dump custom format (without filestore), but when I reimport it, I have the problem.

Anyone knows how to fix the database?

Thank you

Matteo

**Comment by nilshamerlinck** [comment]
@matteocanella quick fix: `DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';`

**Comment by matteocanella** [comment]
Tahank you for the quick fix, it worked!
Matteo

**Comment by dasmedium** [comment]
I have the same problem running Odoo 10 in a docker environment.  

Uncaught TypeError: odoo.define is not a function
    at web.assets_frontend.js:3
website.assets_editor.js:3 
Uncaught TypeError: odoo.define is not a function
    at website.assets_editor.js:3

**Comment by Cicciodev** [comment]
@dasmedium 
After running the query suggested by @nilshamerlinck (thank you a lot by the way) you have to clean cache about the site (at least in my case it worked), i.e. on firefox go in history select an instance of your site, right-click and chose "Forget abour this site".

**Comment by zhangshunrao** [comment]
_web.assets_frontend.js:3 Uncaught TypeError: odoo.define is not a function
    at web.assets_frontend.js:3
web.assets_backend.js:18 Uncaught ReferenceError: jQuery is not defined
    at web.assets_backend.js:18
    at web.assets_backend.js:3
    at web.assets_backend.js:18
(anonymous) @ web.assets_backend.js:18
(anonymous) @ web.assets_backend.js:3
(anonymous) @ web.assets_backend.js:18
web:49 Uncaught TypeError: odoo.define is not a function
    at web:49_


**Execute the statement DELETE FROM ir_attachment WHERE url LIKE '/web/content/%'; After normal, but the above problem occurs again every few days.**

**Comment by yung-wang** [comment]
Same problem here. I try to restore the dumpfile of a production DB (with filestore it is too big). I have to delete using the above statement **DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';**
Is there a permanent solution, will there be a bugfix available?

**Comment by fuck-usa-restrictions** [comment]
Same problem in Odoo 12, but **DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';** did not work for me. 
Still no permanent solution?

**Comment by asiamatrix** [comment]
I have the same issue in Odoo12.

**Comment by tengusantoso** [comment]
Me too
EC2 Instances - with docker and docker-compose. Several kind of docker-compose.yml (incl 
https://gist.github.com/byk0t/a9644fd2360a9662702568459df289fc/revisions). 

Everything seems good, until restoring my backup (2 days ago) using web database manager, select the database. And freezes. 

In fact I've been facing these web freezing in last 2 days. 

Pls help.

**Comment by tengusantoso** [comment]
> Me too
> EC2 Instances - with docker and docker-compose. Several kind of docker-compose.yml (incl
> https://gist.github.com/byk0t/a9644fd2360a9662702568459df289fc/revisions).
> 
> Everything seems good, until restoring my backup (2 days ago) using web database manager, select the database. And freezes.
> 
> In fact I've been facing these web freezing in last 2 days.
> 
> Pls help.

![image](https://user-images.githubusercontent.com/52650980/63451971-68ca1980-c46f-11e9-9a16-1952f63adbbb.png)

attached is snapshot on an EC2 instance:
- after docker system prune -a
- docker-compose up

`version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data:
    driver: local
  web-data:
    driver: local`

the yaml conf.

**Comment by tengusantoso** [comment]
> > Me too
> > EC2 Instances - with docker and docker-compose. Several kind of docker-compose.yml (incl
> > https://gist.github.com/byk0t/a9644fd2360a9662702568459df289fc/revisions).
> > Everything seems good, until restoring my backup (2 days ago) using web database manager, select the database. And freezes.
> > In fact I've been facing these web freezing in last 2 days.
> > Pls help.
> 
> ![image](https://user-images.githubusercontent.com/52650980/63451971-68ca1980-c46f-11e9-9a16-1952f63adbbb.png)
> 
> attached is snapshot on an EC2 instance:
> 
> * after docker system prune -a
> * docker-compose up
> 
> `version: '3' services: db: image: postgres:10 volumes: - db-data:/var/lib/postgresql/data/pgdata ports: - 5432:5432/tcp environment: - POSTGRES_PASSWORD=odoo - POSTGRES_USER=odoo - POSTGRES_DB=postgres - PGDATA=/var/lib/postgresql/data/pgdata web: image: odoo:12.0 depends_on: - db ports: - "8069:8069/tcp" volumes: - web-data:/var/lib/odoo - ./config:/etc/odoo - ./addons:/mnt/extra-addons volumes: db-data: driver: local web-data: driver: local`
> 
> the yaml conf.

Attached are the logs:
[db_log.txt](https://github.com/odoo/odoo/files/3526461/db_log.txt)
[web_log.txt](https://github.com/odoo/odoo/files/3526462/web_log.txt)

**Comment by tengusantoso** [comment]
> > > Me too
> > > EC2 Instances - with docker and docker-compose. Several kind of docker-compose.yml (incl
> > > https://gist.github.com/byk0t/a9644fd2360a9662702568459df289fc/revisions).
> > > Everything seems good, until restoring my backup (2 days ago) using web database manager, select the database. And freezes.
> > > In fact I've been facing these web freezing in last 2 days.
> > > Pls help.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/52650980/63451971-68ca1980-c46f-11e9-9a16-1952f63adbbb.png)
> > attached is snapshot on an EC2 instance:
> > 
> > * after docker system prune -a
> > * docker-compose up
> > 
> > `version: '3' services: db: image: postgres:10 volumes: - db-data:/var/lib/postgresql/data/pgdata ports: - 5432:5432/tcp environment: - POSTGRES_PASSWORD=odoo - POSTGRES_USER=odoo - POSTGRES_DB=postgres - PGDATA=/var/lib/postgresql/data/pgdata web: image: odoo:12.0 depends_on: - db ports: - "8069:8069/tcp" volumes: - web-data:/var/lib/odoo - ./config:/etc/odoo - ./addons:/mnt/extra-addons volumes: db-data: driver: local web-data: driver: local`
> > the yaml conf.
> 
> Attached are the logs:
> [db_log.txt](https://github.com/odoo/odoo/files/3526461/db_log.txt)
> [web_log.txt](https://github.com/odoo/odoo/files/3526462/web_log.txt)

refer to web_log.txt, the most recent:
![image](https://user-images.githubusercontent.com/52650980/63453501-ffe4a080-c472-11e9-94f1-4fd405926c66.png)

checking container files:
![image](https://user-images.githubusercontent.com/52650980/63453558-1ee33280-c473-11e9-9b47-a6bab8ce445a.png)

Hope could help to get some resolution.

Big thanks in advance.

**Comment by bsurfing** [comment]
We are also experiencing this in Odoo 12 (Oct 2019 build) I guess there is no real solution at this point?

**Comment by bupscale** [comment]
@Odoo S.A, Please it's a shame not to be able to solve this issue once and for all. Any lasting solution you recommend or this is intentional and on purpose?

**Comment by diezcode** [comment]
@bupscale try to restore your DB direct in the postgres, not from the odoo web restore.
this fixes my issue with big databases and with the filestore problem.

**Comment by Greko2017** [comment]
Still having the same error till today, frusrating one, just did a "DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';" (Don't do that ) i is going to wipe allcss and ks from your instance
Please for a solution

**Comment by mfhm95** [comment]
> @matteocanella quick fix: `DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';`

Thanks Too much , it works well

**Comment by BurningNacho** [comment]
I'm having this problem in Odoo V14 too, started happening when I set up the nginx configuration.
I'm trying to solve it [here](https://stackoverflow.com/questions/66879894/setting-up-odoo-14-https-through-nginx)

**Comment by BurningNacho** [comment]
I'm having this problem in Odoo V14 too, started happening when I set up the nginx configuration.
I'm trying to solve it [here](https://stackoverflow.com/questions/66879894/setting-up-odoo-14-https-through-nginx)

**Comment by rrebollo** [comment]
I'm having this problem in Odoo V13 too, nginx configuration. Amazon Instances. Docker odoo, remote postgres 13.
I'm trying to solve it here

**Comment by AmroYasser** [comment]
I'm having this problem in Odoo V11, using Docker

**Comment by edisanch** [comment]
Same issue, Odoo V14, enterprise, 2022. 
We found a workaround by chance. 
> DELETE FROM ir_attachment WHERE url LIKE '/web/content/%'; 
was not working for us. 

The issue presented itself at random computers. Out of the 30 something laptops in my team, 5 had this issue. 

We have an aditional Odoo v14, comunity server up for testing and developing. This  server does not present the issue. 
So we cleared the cache and cookies from the browser.
Then we logged in to the community server . 
Then we logged in to the enterprise server  and it suddently works.
Hope this helps someone.

**Comment by thetrebelcc** [comment]
Seeing the same issue, Odoo V15, enterprise, local instance NGINX. 

Have tried the above workarounds, still facing the same problem randomly. I will update if I find something that works.

**Comment by edisanch** [comment]
@thetrebelcc sometimes when desperate I change the odoo.conf worker to 0, thing suddently works, then I restart back to normal worker count. I have no idea why this works.

**Comment by ZedayKayo** [comment]
i hate odoo i swear a god, i have odoo 15 .
i tried all the solutions but the problems still remain
unstyled login page and when login showed blanket page im trying to solve this problem two months 
it seems that the problem in odoo they didnt create it as it should be

**Comment by markoppp** [comment]
Odoo 16 - same problem
