### ISSUE TITLE
Can't installed Odoo 10 on CentOS because of missing repo on nightly builts

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#13806]
Hi 

can anyone solv the issue for RPM as nightly builts  **odoo.repo** having problem when update.. 404 can't find . Even i have gone through the browser all is setup but when update odoo 10 **odoo.repo** installing odoo 9 noarch 

Anyone can you please solve it.

Thanks
Sandeep

**Comment by sle-odoo** [comment]
i'll have a look today

**Comment by sle-odoo** [comment]
I just tried on Fedora 24 and it is working as expected.

```
dnf config-manager --add-repo https://nightly.odoo.com/10.0/nightly/rpm/odoo.repo
dnf update
# install postgres
dnf install postgresql-server postgresql-contrib
postgresql-setup --initdb --unit postgresql
systemctl start postgresql.service
# install odoo
dnf install odoo
systemctl start odoo
```
And it is running Odoo 10.0-20161022 (Community Edition).
Could you try again?
