### ISSUE TITLE
[9.0] account_asset: wrong state on depreciation line after journal entry removal

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13801]
**Impacted versions:**
9.0 (probably 10.0)

**Steps to reproduce:**
1.  Install `account_asset` module
2. Create a new asset.
3. Confirm asset
4. Click on generate entry button on any depreciation line. It generates an 'Unposted' journal entry (account.move)
5. Check line state, should be green = Posted.
6. Go to entries and delete the entry.
7. Check again the line state, still green = Posted, but the journal entry doesn't exists.

At `account.move.unlink()`, https://github.com/odoo/odoo/blob/9.0/addons/account_asset/account_asset.py#L402 is not called, then `move_check` remains = True

opw: 691084

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/65878a5b85f30ecdfe0e55d57c7f8e77034cb191

**Comment by aristobulo-eezee** [comment]
FYI @antonybrugger
