### ISSUE TITLE
[10.0][account_tax_cash_basis] Wrong entries in tax journal for cash based taxes

### ISSUE THREAD

**Issue by eburghar** [odoo/odoo#13828]
Impacted versions: 10.0

Steps to reproduce:
- Install `account_accountant`, `l10n_generic_coa` and `account_tax_cash_basis` modules
- Configure the sale taxe `Tax 15%` to `Use Cash Basis` on `Tax Paid` account
- Create a client invoice with single line at `1000.00` and a `Tax 15%` and reconcile

Current behavior: the tax journal has 2 contradictory useless move lines which cancel one another

Expected behavior: only the move lines linked to the cash based tax should appear in the tax journal

Video/Screenshot link (optional):

![screenshot_20161015_084928](https://cloud.githubusercontent.com/assets/118589/19408429/93c89a98-92b4-11e6-8b73-03909660f560.png)

![dd513e1e-92b3-11e6-9919-2a59caca7a68](https://cloud.githubusercontent.com/assets/118589/19718665/30268574-9b5e-11e6-9a47-6dfc798704a0.png)

**Comment by gurneyalex** [comment]
@eburghar  I asked the question to Odoo's technical support, here's the answer I got from @lap-odoo :

> This is the expected behavior, as you can see in our documentation : https://www.odoo.com/documentation/user/11.0/accounting/others/taxes/cash_basis_taxes.html
> 
> This entry is there for technical reason (it is used the calculate the base amount of the tax which is used in the tax reports). 
> 
> Kind regards,
