### ISSUE TITLE
Odoo   AccessError No value found for account.payment.term(3,).note

### ISSUE THREAD

**Issue by premjawariya** [odoo/odoo#13826]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello

Please, fill in template !

Which version ?
How to reproduce ? 

Without it, we cannot help you !

**Comment by premjawariya** [comment]
Odoo 8.0 version and this error occurring  when a customer login and wants to print his invoice its working with one customer but occurring error with another one

**Comment by JKE-be** [comment]
What it the full traceback ?
Can you reproduce on runbot ? If not, it seems more a bug of installation, and so, you should ask on help.odoo.com...

What is the value of note for the 'payment Term' with id = 3 ?
Do you have some custo on access right ? acl ? ...

**Comment by premjawariya** [comment]
I have attached the traceback





![2](https://cloud.githubusercontent.com/assets/3235509/19441771/8b86b274-94a4-11e6-979e-78c7e5a74047.PNG)
![1](https://cloud.githubusercontent.com/assets/3235509/19441772/8b94c0d0-94a4-11e6-8b43-60133681d819.PNG)

**Comment by JKE-be** [comment]
> when a customer login and wants to print his invoice its working with one customer but occurring error with another one

So just need to find the disintct between these 2 users :)
AccessError, do probably an access rules...

But are you sure that the real difference is not a payment term on one invoice and not on another one !?

**Comment by premjawariya** [comment]
Thanks it's a acl problem I have give the permission to portal user to access payment term and problem solve again thanks for reply
