### ISSUE TITLE
POS screen distorted

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#13831]
Impacted versions: - 10.0

Steps to reproduce:
1. Open any pos session.

Current behavior: The Num-pad and payment options are not in order, so the ordering product list  is not visible

Expected behavior: Num-pad and payment options should be organized properly in the screen, the POS ordering product list should be visible in the screen

Video/Screenshot link (optional):

<img width="1275" alt="screen shot 2016-10-15 at 10 34 01 pm" src="https://cloud.githubusercontent.com/assets/7326014/19412450/94a5ca58-9327-11e6-89a3-02afc9335196.png">

**Comment by bistaray** [comment]
Is this browser related?  

I could not replicate using Chrome Version 53.0.2785.143 m:


![](http://i.imgur.com/40LzOtq.png)


![](http://i.imgur.com/40LzOtq.png)

**Comment by lithint** [comment]
Thank you Ray,
It looks like some browser issues..
The same is working fine with my Safari - Version 10.0 (12602.1.50.0.10)

With My Firefox version i have, I am having the same issue.
<img width="1225" alt="screen shot 2016-10-16 at 11 25 08 pm" src="https://cloud.githubusercontent.com/assets/7326014/19420250/5a96b45e-93f8-11e6-842b-07f03eae9ce6.png">


With Chrome same version(Version 53.0.2785.143 (64-bit)) in macOS Sierra version 10.12, 
it is giving the following error on opening and closing of a session.. but the POS screen is loading fine. 

<img width="1041" alt="screen shot 2016-10-16 at 11 27 32 pm" src="https://cloud.githubusercontent.com/assets/7326014/19420279/1d98e544-93f9-11e6-836a-85a22ab993f9.png">

With my Safari browser.. it looks all fine.
<img width="1276" alt="screen shot 2016-10-16 at 11 35 24 pm" src="https://cloud.githubusercontent.com/assets/7326014/19420287/44340602-93f9-11e6-880c-726d2ef8f33e.png">

**Comment by nilshamerlinck** [comment]
Same layout issue confirmed on:
- Firefox 49.0 and 50.1.0 for Android
- Firefox 50.0 for Desktop (Linux)

No issue on Chrome.

**Comment by Yenthe666** [comment]
All these issues with scrambled layout have been fixed quite a while ago. Nobody closed this though.
