### ISSUE TITLE
Invoice Based on Delivered Quantity is not working for same product with different sale price

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#13832]
Impacted versions: - 10.0

Steps to reproduce:
1. Create a new product.
2. Set the product settings as Stockable and Invoicing policy based on delivered quantity.
3. Purchase the product 100 qty.
4. Create a sale order for the same product with two lines
          - i)  5 Qty at sale price  $350
          - ii) 5 Qty at  sale price $400
5. Conform the sale order.
6. Deliver only 5 Qty.
7. Create invoice for invoiceable lines.
 
Current behavior:
Invoice is created for two lines of product with out considering the delivered Qty. 

Expected behavior:
Invoice should be get created for only 5 Qty of the same product.
(in this case it should be for 5Qty at sale price $350)
Video/Screenshot link (optional):

<img width="1249" alt="screen shot 2016-10-15 at 10 57 43 pm" src="https://cloud.githubusercontent.com/assets/7326014/19412613/eb0def4e-932a-11e6-872c-c1bc0fc7a952.png">

<img width="1260" alt="screen shot 2016-10-15 at 10 58 19 pm" src="https://cloud.githubusercontent.com/assets/7326014/19412615/fc85b306-932a-11e6-903a-c248201c08a3.png">

**Comment by bistaray** [comment]
I was unable to replicate.  The quantities are merged on the Delivery Order, showing 10 units.  However when I created the Invoice it showed 5 units at 350€ for a total of 1,750€.

**Comment by lithint** [comment]
With latest runbot version this is working fine. Thank you Ray.
