### ISSUE TITLE
Portal access in Odoo multibase is not correct

### ISSUE THREAD

**Issue by iguixa** [odoo/odoo#138450]
Impacted versions: V16

Steps to reproduce:

I have two databases BD1 and BD2 on the same Odoo server.
Same web.base.url = 10.2.72.148:8069 in two databases.
Customer C1 in BD1 with email: iguixa@gmail.com
Customer C2 in BD2 with email: iguixa@infomila.info

BD1 administrator gives portal access to C1.
C1 receives invitatioin email with link:
http://10.2.72.148:8069/web/signup?db=BD1&token=1mB00OzRvuKNKjtn6PUP
This link not connect. Error: The requested URL was not found on the server.

BD2 administrator gives portal access to C2.
C2 receives invitation email with link:
http://10.2.72.148:8069/web/signup?db=BD2&token=eCUABbuSepyiUYF6tMmR
This link not connect. Error: The requested URL was not found on the server.

If I delete BD1, link of customer C2 it's ok and C2 can to register
C2 receive a welcome message with link:
http://10.2.72.148:8069/web/login?auth_login=iguixa@infomila.info
When C2 tries to connect, the database selector appears; does not connect with BD2

If I delete BD2, link of customer C1 it's ok and C1 can to register
C1 receive a welcome message with link:
http://localhost:8069/web/login?auth_login=iguixa@gmail.com
When C1 tries to connect, the database selector appears; does not connect with BD1

TWO ERRORS:
1. Link to signup not connect if there are more than 1 database in the server
2. Link to login not has the parameter db=DATABASE

**Comment by gdgellatly** [comment]
It is probably just your setup. All localhost, browser cookies, sessions, using dbparams in urls etc messing it up. Testing portal has always sucked locally for multi db to point where all our dev environments run wildcard ssl certs and full proxies.

Ordinarily you would be behind a proxy, using a dbfilter and specific domains.

**Comment by vava-odoo** [comment]
Hi @iguixa 
Closing the ticket which looks more like a misconfiguration than a bug. 
If you think it should be more clear in the documentation, please open a ticket [in the documentation repository](https://github.com/odoo/documentation/issues).
if you need help, please use the [forum](https://www.odoo.com/forum/help-1).
Cheers
