### ISSUE TITLE
[10.0] all modules - uninstalled error 

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#13848]
Impacted versions: V10.0

Steps to reproduce:
1.install website_contract  module
2.uninstall website_contract  module

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/8476734/19441174/4b27c4a8-94b7-11e6-90d3-6c45d1fa1af5.png)

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Thanks a lot for your report. I've just checked this and this is indeed a bug.
@mart-e can you assign this to somebody? Not sure for who it is.

Regards,
Yenthe
