### ISSUE TITLE
[8.0] Reconciliation on Bank Statements - Partner concurrent update

### ISSUE THREAD

**Issue by angelmoya** [odoo/odoo#13846]
Impacted versions:

8.0

Steps to reproduce:

Create more than one invoice to pay with bank statetment, and create a bank statement to pay them.

Go to /Accounting/Periodic Processing/Reconciliation/Reconciliation on Bank Statements or run assistant on bank statement.

Click OK button quickly to reconcile invoices from same partner with bank statement.

Current behavior:

Updating quickly partner balance raise an interal error due concurrent update, but it's not shown on user interface, then assistant finish and says that all is OK, but really one or more reconciliation is not been created.

Expected behavior:

Prevent this concurrent update or show this error.

**Comment by Yenthe666** [comment]
@hbrunn thanks for the fix. Can you link the Odoo commit that fixed this too? Then I can double check & close this report.

**Comment by hbrunn** [comment]
@Yenthe666 https://github.com/odoo/odoo/pull/17470

**Comment by Yenthe666** [comment]
Hi @angelmoya,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
