### ISSUE TITLE
[10.0]Association top menu should not be for account users only

### ISSUE THREAD

**Issue by Yakulu** [odoo/odoo#13842]
Impacted version: 10

Steps to reproduce: Install membership module

Current behavior: after association/membership module installation, top menu and then all features are reserved to accounting users only.

Expected behavior: membership features, at least members creation and listing, should be more widely available. In v9, salesmen group was able to see them.

Relevant files :
- v9 old behavior : https://github.com/odoo/odoo/blob/9.0/addons/association/profile_association.xml
- v10 current one : https://github.com/odoo/odoo/blob/10.0/addons/association/views/association_views.xml

**Comment by pedrobaeza** [comment]
This is because current dependency hierarchy. An improvement can be done having a special group, but neither salesman nor accountant are the right one. Any way, this can't be done on a stable branch.

@tivisse you were the one that makes this move. Any plans to change to an specific group?
