### ISSUE TITLE
[8.0] Problem with order by in list view

### ISSUE THREAD

**Issue by averdecia** [odoo/odoo#13850]
# Impacted versions: **8.0**
# Steps to reproduce:
- Create a model(model_1), that heritage from other(model_2), and at the same time model_2 inherit \* from a third model(model_3)
- So.. when you create list view in model_1 using a field from model_3, its not sortable
# Current behavior:
- Error when you click on th element form list view table
# Expected behavior:
- Sort the list
# Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @averdecia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
