### ISSUE TITLE
POS customer table not updated at run time need to reload the pos

### ISSUE THREAD

**Issue by sunny-kumar38** [odoo/odoo#13856]
Impacted versions: 9.0 c and 10.0 

Steps to reproduce: simple choose a customer in  POS and edit customer's information and save it, then you can see updated information not visible in customer screen (customer details table view)
Current behavior:

Expected behavior: 

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

> Video/Screenshot link (optional):

Please give some because I am not sure to understand your issue

**Comment by sunny-kumar38** [comment]
You can find the **video zip** from here from here..please check...
[pos_customer_error.mp4.zip](https://github.com/odoo/odoo/files/538139/pos_customer_error.mp4.zip)

Thanks

**Comment by mart-e** [comment]
Ok thanks for the info, when you said table view, I understood the table layout in the restaurant.
I confirm the bug.

**Comment by Yenthe666** [comment]
@mart-e or @sle-odoo or @jorenvo (I'm totally not sure who is the main guy for POS now), could one of you guys look at this and fix it? It is apparently in V11 now too.

**Comment by BlueStoneSolution** [comment]
Please replace with render_list by using following for ClientListScreenWidget as  Temporary Solution:

render_list: function(partners){
            var contents = this.$el[0].querySelector('.client-list-contents');
            contents.innerHTML = "";
            for(var i = 0, len = Math.min(partners.length,1000); i < len; i++){
                var partner    = partners[i];
                var clientline_html = QWeb.render('ClientLine',{widget: this, partner:partners[i]});
                var clientline = document.createElement('tbody');
                clientline.innerHTML = clientline_html;
                clientline = clientline.childNodes[1];

                if( partners === this.new_client ){
                    clientline.classList.add('highlight');
                }else{
                    clientline.classList.remove('highlight');
                }

                contents.appendChild(clientline);
            }
        },


Hopefully it will work! But for current issue, it was modified code from v8 because of performance issue.

**Comment by aditya-sharma185** [comment]
This was not found in Odoo 8 because Odoo started maintaining partner cache from Odoo 9 onward.
When a customer's record is edited, it updates the record at backend but does not clear the node in the cache. Now since the view is created from the cached data, the updated information does not reflect unless you refresh the POS.

Solution that worked for me:
File: **point_of_sale/static/src/js/screens.js**
**ClientListScreen**

You need to modify the **saved_client_details** method as follows:
NOTE: LINES IN BOLD HAVE BEEN INSERTED
After this, the client list will be updated as when the actual modification is done.

`saved_client_details: function(partner_id){
        var self = this;
        **self.partner_cache.clear_node(partner_id);**  
        this.reload_partners().then(function(){
            var partner = self.pos.db.get_partner_by_id(partner_id);
            if (partner) {
                self.new_client = partner;
                self.toggle_save_button();
                self.display_client_details('show',partner);
            } else {
                // should never happen, because create_from_ui must return the id of the partner it
                // has created, and reload_partner() must have loaded the newly created partner. 
                self.display_client_details('hide');
            }
            **self.pos.chrome.screens.clientlist.render_list(self.pos.db.get_partners_sorted(1000))**
        });
    },`

Thanks.

**Comment by Yenthe666** [comment]
@pimodoo any update here or could you answer this?

**Comment by pedrobaeza** [comment]
@pimodoo please tell us if there's any plan to fix this?

**Comment by aditya-sharma185** [comment]
The same issue is still present in Odoo 11 and even in the Odoo 12(master branch)..  I just checked..

![odoo pos](https://user-images.githubusercontent.com/38282092/43625653-cbf3933e-970b-11e8-8293-9cda60664493.jpg)

Please check my last thread. This can easily fix the issue.

**Comment by Highcooley** [comment]
Same problem here in V10. Additionally, when adding a new user, pressing the save button doesn't result in any response. But in the background, a new customer gets added, every time I press save. After exiting the customer selection and entering again, the new customer is displayed in the list and can be selected. Sales to this customer get registered, but the customer cannot be handed over to third party modules like gift card modules for exemple.

**Comment by Yenthe666** [comment]
Hi there,

This should have been fixed in https://github.com/odoo/odoo/commit/9609f79cad50613049dc20b0d7eb9cad012fdbf4 from V10 onwards.

Regards,
Yenthe
