### ISSUE TITLE
[V10] New Dutch COA can't be set on 4 digits

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#13853]
Impacted versions:
- V10

Steps to reproduce:
- Go to the accounting settings and set the number of digits on 4 (like a lot of small companies do in NL)

Current behavior:
- The COA is set to 4 ditgits, but that creates duplicated codes and so some accounts stay on 6 digits.

Expected behavior:
- All account codes must be unique, also in the 4 digit setting, like we had in previous Odoo versions

Video/Screenshot link (optional):
- COA in 4 digits attached. See the yellow accounts
  [dutch_nl_coa.xlsx](https://github.com/odoo/odoo/files/535374/dutch_nl_coa.xlsx)

**Comment by Yenthe666** [comment]
@qdp-odoo could you look at this?

**Comment by ploegvde** [comment]
Hi, we are staring on new Odoo V10 implementations. What can we expect of this issue? Can someone have a look. We now have new COA and if there is some problems, i hope it can be solved quickly.

**Comment by Yenthe666** [comment]
@mart-e @qdp-odoo and @odony this is an important one.

**Comment by ploegvde** [comment]
Hello. Is a good char of accounts no priority of Odoo anymore? 

Don't push for a new COA in V10 and then don't solve the problems!

**Comment by ploegvde** [comment]
@astirpe Hi Andrea, can you also have a look?

**Comment by astirpe** [comment]
@ploegvde thank you for notifying me. I was not aware of this issue.

I'm going to propose a PR to change the code of the tax accounts that you already highlighted, making them compatible with a coa set to 4 digits.

**Comment by ploegvde** [comment]
Can this be merged please?
