### ISSUE TITLE
Odoo v8.0 branch / User portal: Unable to activate a user portal (field not editable in portal management view)

### ISSUE THREAD

**Issue by NicolasRigo** [odoo/odoo#1385]
It's not possible to activate a portal user from the Customer view.

Select a customer -> more option -> Portal management, the field are no more editable

**Comment by goodconcepts** [comment]
Thx, I'm on the public version of ODOO SAAS on odoo.com though.

**Comment by Yenthe666** [comment]
Hi @NicolasRigo,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
