### ISSUE TITLE
web service error following the documentation for python

### ISSUE THREAD

**Issue by albertoferna** [odoo/odoo#13857]
Impacted versions:10

Steps to reproduce:
Following the code in https://www.odoo.com/documentation/10.0/api_integration.html both in a fresh install and against 'https://demo.odoo.com/start' trows a type error

Current behavior:
Now I get an error when executing:

```
ids = models.execute_kw(db, uid, password,  'res.partner', 'search',
    [[['is_company', '=', True], ['customer', '=', True]]],
    {'limit': 1})
[record] = models.execute_kw(db, uid, password,
    'res.partner', 'read', [ids])
# count the number of fields fetched by default
len(record)
```

In particular it seems to be a type error (cannot marshal class odoo.tools.float_utils.float_precision)

Expected behavior:
I would expect it to behave as in the documentation

**Comment by xmo-odoo** [comment]
It would be convenient to have a full traceback...

**Comment by albertoferna** [comment]
Is this what you need?:

`Fault: <Fault cannot marshal <class 'odoo.tools.float_utils.float_precision'> objects: 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 57, in xmlrpc_return\n    response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps\n    data = m.dumps(params)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps\n    dump(v, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump\n    f(self, value, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 719, in dump_array\n    dump(v, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump\n    f(self, value, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 741, in dump_struct\n    dump(v, write)\n  File "/usr/lib/python2.7/xmlrpclib.py", line 652, in __dump\n    raise TypeError, "cannot marshal %s objects" % type(value)\nTypeError: cannot marshal <class \'odoo.tools.float_utils.float_precision\'> objects\n'>`

**Comment by wtaferner** [comment]
OPW-692373

**Comment by dbo-odoo** [comment]
Discussion continues in opw-692373, but a fix is coming.
