### ISSUE TITLE
UsersView.fields_get doesn't honor filter parameters

### ISSUE THREAD

**Issue by lbeopennet** [odoo/odoo#13859]
Filters, namely `all_fields` and `attributes`, when passed, allow one to get only a subset of all the data that `fields_get` is able to return. However, even though the `fields_get` overload for `res.users` passes on those parameters to the normal `fields_get` correctly, it adds data ('reified groups') to the return value and doesn't take the filters into account.
Impacted versions:
7.0, 8.0, 9.0, 10.0
Steps to reproduce:
call said method on `res.users` (possibly through xmlrpc), passing non-empty `all_fields` and `attributes`.
Current behavior:
all reified groups show up in the resulting dictionary as fields, and they exibit all their attributes.
Expected behavior:
group fields shouldn't show up if they weren't requested, and their attributes should be filtered.
Video/Screenshot link (optional):
https://gist.github.com/lbeopennet/a7a88d5da9a417844908e12958097412
Code:
https://github.com/odoo/odoo/blob/7.0/openerp/addons/base/res/res_users.py#L945
https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_users.py#L945
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_users.py#L942
https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_users.py#L877

**Comment by pedrobaeza** [comment]
This is on purpose by design to add the permission system. If you don't want these fields, please strip them out after calling super in your customization.
