### ISSUE TITLE
[9.0 ENT] Original invoice keeps irrelevant reference after refund

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#13870]
Impacted versions: 9.0 ENT

Steps to reproduce:
1. Create an invoice and validate it
2. Click on refund payment and select option 3: 'Modify: create refund, reconcile and create a new draft invoice' and give it a reason:
![image](https://cloud.githubusercontent.com/assets/6352350/19481609/c322a06c-954e-11e6-9032-f17aec1d997b.png)
3. Click on 'Create refund':
![image](https://cloud.githubusercontent.com/assets/6352350/19481631/dc6fcb6c-954e-11e6-986c-c65f6a61c6ea.png)
4. Check out the refund:
![image](https://cloud.githubusercontent.com/assets/6352350/19481678/0c666484-954f-11e6-92b2-4aa0160d34a1.png)

Current behavior: The reference/description from the dialog is filled in on both the newly created invoice and on the refund. 

Expected behavior: Only the refund should show this reference, not the newly created invoice.

**Comment by JKE-be** [comment]
Already reported and fixed in v10, I think

**Comment by Yenthe666** [comment]
@JKE-be then a backport to V9 is in order. 😉 Our customer complains about this.

**Comment by Yenthe666** [comment]
@JKE-be any chance this can be backported?
