### ISSUE TITLE
pos_cache 10.0 returns empty product list

### ISSUE THREAD

**Issue by jbeltranarens** [odoo/odoo#13878]
Impacted versions:10.0

Steps to reproduce:
  - install pos_cache module

Current behavior:
 - Once pos_cache installed, no more product available

Expected behavior:
 - See all products like without pos_cache

**Comment by JKE-be** [comment]
@jbeltranarens Thanks for the reporting, but please, next time fill in the template :)

**Comment by jbeltranarens** [comment]
Thanks a lot.   Im sorry :)
