### ISSUE TITLE
Add support for python 3.12

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#138728]
Python 3.12 requires lxml module version 4.9.3, odoo only support 4.9.2

If you upgrade to python 3.12, you will recibe xml errors trying render the site

**Comment by ahaly-compass** [comment]
Is there any update here?
I know that Odoo is trying to use versions from ubuntu lts (22.04) and debian (11 - bookworm), but there are cool things in python 3.12, including performance improvements.

**Comment by john-herholz-dt** [comment]
I thought 3.12 was confirmed to be supported? What is the offical statement regarding python version on Odoo 17.0

**Comment by ahaly-compass** [comment]
I can tell you that the package versions for lxml, Pillow and greenlet are not compatible with python 3.12 

These Versions are needed for installation.
lxml==5.0.0
Pillow==10.2.0
greenlet==3.0.3

**Comment by cengelha** [comment]
Even if you install the newer package versions, there is at least one other issue regarding the [opcodes](https://github.com/odoo/odoo/blob/17.0/odoo/tools/safe_eval.py#L99) as there are some [new in 3.12](https://docs.python.org/3.12/library/dis.html) that are not yet added.

**Comment by mgite** [comment]
Any update on this?

**Comment by mgite** [comment]
> @mgite what error do you have?

Code is simply not written for 3.12. From release day nothing is changed to support 3.12. Sadly no hope to run odoo 17 on 3.12

**Comment by fi-ecavc** [comment]
It would be nice if Odoo 17 could support Python 3.12 as soon as possible

**Comment by mohamedamara1** [comment]
I'm running into this issue while trying to install Odoo 17 on my fresh Fedora 39 installation, there are the errors I'm running into:

`user@fedora:~$ sudo dnf install -y odoo
[sudo] password for user: 
Last metadata expiration check: 0:55:54 ago on Fri 01 Mar 2024 10:06:48 AM CET.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.11 needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(babel) >= 1 needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(psycopg2) >= 2.2 needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pyusb) >= 1~b1 needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(chardet) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(cryptography) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(decorator) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(docutils) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(geoip2) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(gevent) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(greenlet) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(idna) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(jinja2) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(libsass) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(lxml) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(markupsafe) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(num2words) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(ofxparse) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(passlib) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pillow) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(polib) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(psutil) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pydot) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pyopenssl) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pypdf2) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pyserial) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(python-dateutil) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(python-stdnum) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(pytz) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(qrcode) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(reportlab) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(requests) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(rjsmin) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(urllib3) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(vobject) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(werkzeug) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(xlrd) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(xlsxwriter) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(xlwt) needed by odoo-17.0-1.noarch from odoo-nightly
  - nothing provides python3.11dist(zeep) needed by odoo-17.0-1.noarch from odoo-nightly
(try to add '--skip-broken' to skip uninstallable packages)
`

and my python version is 3.12

user@fedora:~$ python --version
Python 3.12.2

**Comment by chapital** [comment]
I now working with python 3.12, you need to install also lxml_html_clean_split, thanks for @Xavier-Do

**Comment by ravijoshi2** [comment]
pip3 install lxml-html-clean worked for me on python 3.12.3

**Comment by mgite** [comment]
> pip3 install lxml-html-clean worked for me on python 3.12.3

3.12 is already supported by odoo.
