### ISSUE TITLE
create customer error without install a l10n

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#13880]
Impacted versions: 
10.0
Steps to reproduce:
1. install account and sale module without any l10n
2. create a customer

Current behavior:
The following fields are invalid:
Account Receivable
Account Payable
Expected behavior:
don't Throw out error
Video/Screenshot link (optional):

**Comment by yueqin** [comment]
I can  create a new customer by  shortcut

**Comment by intero-chz** [comment]
IIRC it's the same in Odoo 9.0

**Comment by JKE-be** [comment]
Odoo don' t suuport accounting without a l10n...

You need to install one localization

**Comment by JKE-be** [comment]
@qdp-odoo @mart-e  your opinion ?

**Comment by mart-e** [comment]
Indeed, you need to have at least some basic sale and purchase accounts. The easiest is to create them via a l10n module but if you wish to create them differently (csv import,...) it's not an issue.

So once you have installed account, you need to have some accounts to create partners. It's the way we expect it to work and don't plan to change that.
