### ISSUE TITLE
[enterprise] l10n_be_reports: wrong values at TOTAL DU PASSIF

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13884]
Impacted versions:
(9.0 & 10.0) enterprise edition

Steps to reproduce:
1. Setup a new odoo
2. Set the country as Belgium
3. Install Accounting app
4. Verify that `l10n_be_reports` is installed
5. Activate developer mode, go to users and set `Administrator` to have `Advisor` rights for accounting
6. Go back to the dashboard and refresh
7. Open Invoicing > Reporting > Bilan

Current behavior:
1. Verify the values of `Total du actif` and `Total du passif`, they are the same
2. Go to Invoicing > Configuration > Financial Reports
3. Open `Bilan`
4. Open `ACTIF`, see `TOTAL DU ACTIF` code, is `BE_ACTIF`
5. Open `PASSIF`, see `TOTAL DU PASSIF` code, is again `BE_ACTIF`

As both totals have the same `code` whatever the formula is for `TOTAL DU PASSIF` is completely ignored and the same values calculated for `TOTAL DU ACTIF` are set.

Without changing `TOTAL DU PASSIF` code, modify the formula to `balance = 100; debit = 200; credit = 100`, in theory by doing this you are forcing odoo to display fixed values on the report. Save and go back to Bilan report, reload, nothing changes. Still, it takes the values from `BE_ACTIF` corresponding `TOTAL DU ACTIF`
(https://github.com/odoo/enterprise/blob/9.0/l10n_be_reports/account_financial_report.xml#L266)

Now, go again and edit `TOTAL DU PASSIF`, set code = `BE_PASSIF` and set the original formula (`balance = BE_UNAFFECTED_EARNINGS.balance + BE_10_15.balance + BE_16.balance + BE_17_49.balance; credit = BE_UNAFFECTED_EARNINGS.credit + BE_10_15.credit + BE_16.credit + BE_17_49.credit; debit = BE_UNAFFECTED_EARNINGS.debit + BE_10_15.debit + BE_16.debit + BE_17_49.debit`)

Go back to Bilan report, and refresh. Now the values change, but still, using the given debit and credit values to calculate balance (with a calculator) will not match the values displayed by odoo.

This is a big mismatch on balance calculation, at least for this report.

Video/Screenshot link (optional):
[![Youtube](http://img.youtube.com/vi/soh2C71P5e4/0.jpg)](http://www.youtube.com/watch?v=soh2C71P5e4)

**Comment by aristobulo-eezee** [comment]
cc/ @antonybrugger

**Comment by Yenthe666** [comment]
@qdp-odoo an accounting related on for you.

**Comment by qdp-odoo** [comment]
fixes made on dde1e52 and e63974d

**Comment by aristobulo-eezee** [comment]
@qdp-odoo thank you for your commit, but by just changing the code you don't fix the issue with the mismatching values. 
See https://youtu.be/soh2C71P5e4?t=340

I just tried your commit and the amounts are still wrong
![bilan](https://cloud.githubusercontent.com/assets/8862626/19518882/b187853c-9609-11e6-97e3-00073c565c8e.png)

Please, try again.

**Comment by qdp-odoo** [comment]
with both the 2 commits?

**Comment by qdp-odoo** [comment]
@aristobulo-eezee I think you didn't check the second commit... Please confirm

**Comment by aristobulo-eezee** [comment]
@qdp-odoo ok I will double check, please don't close this one until you also fix it on v10.

**Comment by aristobulo-eezee** [comment]
@qdp-odoo ok, I confirm that with both commits and demo data, it works as expected. I guess you can merge this fix into v10.0 as well.

**Comment by qdp-odoo** [comment]
forward ported to 10.0 in revision https://github.com/odoo/enterprise/commit/96db72970547da440cf50b74da72ac05619dd33c
