### ISSUE TITLE
Invoiced smart button in res.partner view is not working as expected.

### ISSUE THREAD

**Issue by mikeross6233m** [odoo/odoo#13883]
Impacted versions: Odoo 10 Oct 15 Version

Steps to reproduce: 
After creating and validating invoices for the customers,
Go to Customer view in Sales and click "Invoiced" Smart button(stat button) on the top.

Current behavior:
After clicking "Invoiced" Smart Button, no customer invoices are seen it tree view.
The filter for Partner is also visible.

Expected behavior:
The Customer invoices must be shown.

Video/Screenshot link (optional):
![odoo_invoice_empty](https://cloud.githubusercontent.com/assets/14011478/19510877/8efe457a-9602-11e6-83d1-e3680878b9ea.png)

**Comment by Yenthe666** [comment]
Hi @mikeross6233m,

Thanks a lot for your report.
I've just tested this and this is indeed a bug. The partner form:
![image](https://cloud.githubusercontent.com/assets/6352350/19511413/79074c0a-95e7-11e6-8fdf-0ee67ff1b466.png)

The view that opens after clicking on the smart button:
![image](https://cloud.githubusercontent.com/assets/6352350/19511442/84d6f63e-95e7-11e6-8fe5-cfb3ff52914d.png)

After removing the filter:
![image](https://cloud.githubusercontent.com/assets/6352350/19511473/a9d78d36-95e7-11e6-949a-7898dd24af68.png)
@nim-odoo can you look at this?
