### ISSUE TITLE
An error occurs with the "free_qty" field.

### ISSUE THREAD

**Issue by hari1119** [odoo/odoo#138924]
Impacted versions: v16

Steps to reproduce: added store=True in field declaration 

Current behavior:  ValueError: Compute method failed to assign product.product(4,).free_qty

Expected behavior:  assign the values

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![MicrosoftTeams-image](https://github.com/odoo/odoo/assets/35575433/4de7154e-ace0-4d2b-9623-77cf80701b81)

**Comment by vava-odoo** [comment]
Hi @hari1119 
You can't modify the database without an upgrade script.
Cheers
