### ISSUE TITLE
[8.0] undefined get method error when override computed stored field

### ISSUE THREAD

**Issue by lescobarvx** [odoo/odoo#13899]
**Impacted versions:** 
8.0

**Steps to reproduce:**
1.- Create a new module to override computed stored field

```
  from openerp import api, models, fields                                         


  class StockPicking(models.Model):                                               
      _inherit = 'stock.picking'                                                  

      state = fields.Selection(compute='_compute_state')                          

      @api.multi                                                                  
      @api.depends('move_type', 'move_lines.state', 'move_lines.picking_id',      
                   'move_lines.partially_available',                              
                   'group_id.procurement_ids.sale_line_id.order_id.state')        
      def _compute_state(self):                                                   
         res = super(StockPicking, self)._state_get('state', [])                 
        for pick in self:                                                       
              state = res and pick.id and res[pick.id] or ''                      
              if pick.sale_id:                                                    
                  if pick.sale_id.invoiced is False and \                         
                          pick.sale_id.state not in ['done', 'cancel']:                   
                      state = 'waiting'                                           
              pick.state = state 
```

2.- Install new module 

3.- Create a simple sale order with any customer and any product
![seleccion_061](https://cloud.githubusercontent.com/assets/16093067/19538945/9f8a054c-9624-11e6-803b-82060f4645fe.png)
4.- press "Confirm Sale" button

**Current behavior:**
Show this error:

```
  File "/.repo_requirements/odoo/openerp/models.py", line 4450, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/.repo_requirements/odoo/openerp/osv/fields.py", line 228, in get
    raise Exception(_('undefined get method !'))
ValueError: "undefined get method !" while evaluating
u'action_ship_create()'
```

**Expected behavior:**
Confirm sale order without error

**Comment by christophlsa** [comment]
@lescobarvx I have the same problem here. Could you solve it?

**Comment by lescobarvx** [comment]
@christophlsa 

The problem is that I could not override the 'state' field to new API because it is originally in old API, when trying to do it causes confilct and throws that error, I had to refactor my code so I did not have to do that overwriting in the 'state' field

**Comment by christophlsa** [comment]
@lescobarvx Thanks for the fast answer.

I found this workarround and it seems to work (currently testing): https://github.com/odoo/odoo/issues/3922#issuecomment-262014118

**Comment by Yenthe666** [comment]
Hi @lescobarvx,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
