### ISSUE TITLE
[10.0 EE] Missing access right setting for quality.point

### ISSUE THREAD

**Issue by karsteneb** [odoo/odoo#13893]
Impacted versions: Odoo 10.0+e (Enterprise Edition)

Steps to reproduce:
New database with mrp and quality installed

Current behavior:
Regular user with role Quality / Manager cannot create Quality Control Points. Reason is the access rights setting for the model "quality.point". It only defines read access right for Quality / User, but none for Quality / Manager.

Expected behavior:
Full access for Quality / Manager for all quality control options

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/3011785/19520403/72e1129c-9610-11e6-8144-339f23d5050a.png)

**Comment by JKE-be** [comment]
Thank for the reporting. 

It has been fixed in first version where missing right appear. 
It will be available in v10 asap.
