### ISSUE TITLE
placeholder {object.email} does not work correclty in massive mailing template

### ISSUE THREAD

**Issue by crosani** [odoo/odoo#13896]
Impacted versions: 9.0 ( community and Enterprise both)
Steps to reproduce:
I create a new template 
It contains a link and a normal text
Both use the placeholder {object.email}
![immagine1](https://cloud.githubusercontent.com/assets/22937444/19522302/f1cf4a5a-9616-11e6-8a0b-47ba6fd90bc7.jpg)
in the next picture you can see how the link has been set
![immagine2](https://cloud.githubusercontent.com/assets/22937444/19522448/88ea8d28-9617-11e6-89d4-5bb1cc79c1fd.jpg)
Then the template created has been scheduled to be delivered to a mailing list 

Current behavior:
the mail has been received with the placeholder in the normal text replaced correctly with the email address of the receiver
![immagine3](https://cloud.githubusercontent.com/assets/22937444/19523256/430fb7e4-961a-11e6-84d8-78953bc09740.JPG)
but the placehorder in the link does not work correctly
![immagine4](https://cloud.githubusercontent.com/assets/22937444/19523376/9ae50c94-961a-11e6-867c-7c32c97189da.JPG)

Expected behavior:
the right behavior should exchange the placeholder parameter with the email address of the receiver
![immagine5](https://cloud.githubusercontent.com/assets/22937444/19523554/2e59d5c2-961b-11e6-92f9-485e511f69f8.JPG)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You can't put placeholders using the editor. You have to make it by editing HTML code. It's a know limitation of the editor.
