### ISSUE TITLE
[BUG] search product which qty_available larger than zero not return any result.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#13907]
Impacted versions:
10.0

Steps to reproduce:
Odoo 10 community edition installed  with demo data.
go to product variants list, and set the filter to 'quantity on hand' larger than zero, it return nothing.  if change the condition to larger or equal than zero, it worked.

do those in Odoo shell, the same problem.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/1404460/19555566/ef35e61c-96ef-11e6-85fa-c078457eb1f3.png)

**Comment by JKE-be** [comment]
Hello,

Probably linked to[ this fix](https://github.com/odoo/odoo/commit/feffa2efced0142529e5ddef023600d9a9ab8509) that are not already ported to v10.
Can you check that it solve your problem ?

**Comment by jeffery9** [comment]
not worked

**Comment by jeffery9** [comment]
testing with the latest odoo10 code via Odoo shell, the result is not order by the order keyword specificed. 

> 
> In [28]: for p in env['product.product'].search([('qty_available','>',0)],limit=
>     ...: 20,order='qty_available'):
>     ...:     print p.id, p.name, p.qty_available
>     ...:
> 18 Bose Mini Bluetooth Speaker 8.0
> 20 iPad Mini 500.0
> 9 Computer SC234 50.0
> 21 Apple In-Ear Headphones 18.0
> 23 Apple Wireless Keyboard 22.0
> 24 Mouse, Optical 8.0
> 35 Laptop Customized 84.0
> 52 Laptop Keypad 45.0
> 30 HDD SH-1 39.0
> 25 iPod 26.0
> 33 Graphics Card 16.0
> 34 Laptop E5023 16.0
> 4 Switch, 24 ports 180.0
> 27 Mouse, Wireless 340.0
> 28 RAM SR5 2.0
> 51 Laptop Charger 45.0
> 
![image](https://cloud.githubusercontent.com/assets/1404460/19587447/fc1fd1b6-9790-11e6-85b2-f5b6aa219f42.png)

**Comment by n37r06u3** [comment]
666

**Comment by JKE-be** [comment]
> this fix that are **not already** ported to v10.


Have you cherry pick the fix before your test ? Else, that normal...

**Comment by jeffery9** [comment]
not applied this commit

**Comment by Yenthe666** [comment]
@jeffery9 could you give feedback after testing the commit? Are you still facing this issue?

**Comment by Yenthe666** [comment]
Hi @jeffery9,

I'm considering this fixed as there has been no response in a while. If you still face it then reply back and I'll reopen it.
