### ISSUE TITLE
could not able to uninstall a module, getting an error "UnboundLocalError: local variable 'undeletable' referenced before assignment". in odoo/addons/base/ir/ir_model.py file

### ISSUE THREAD

**Issue by hemnanikalpana** [odoo/odoo#13901]
Impacted versions: version 10, last commit was : a9abce09c066df2a04d1c49ae719b7881ac7e175

Steps to reproduce: just try to uninstall any module.

Current behavior: not able to uninstall module

Expected behavior: module should be uninstalled without giving traceback

Video/Screenshot link (optional):
![uninstall1](https://cloud.githubusercontent.com/assets/18456283/19547773/e53a4118-96b7-11e6-8e69-efac2ad9d21b.png)
![uninstall2](https://cloud.githubusercontent.com/assets/18456283/19547780/f168949e-96b7-11e6-8939-173649cfc2ae.png)

**Comment by wtaferner** [comment]
@hemnanikalpana 
It was fixed here https://github.com/odoo/odoo/commit/23c3bc1a5982bd92fa80b112b259f949edb5f024

**Comment by hemnanikalpana** [comment]
@wtaferner it working. Thanks

**Comment by wtaferner** [comment]
@hemnanikalpana 
Great...may I ask you to close the issue as it is already resolved?
