### ISSUE TITLE
please remove all stuff of im_odoo_support

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#13900]
Impacted versions:
10.0
Steps to reproduce:
see the repo
Current behavior:
im_odoo_support in addons directory without any python code, only i18n in it
Expected behavior:
remove it
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @GoodERPJeff,

Thanks for your report. This module however is used to hold the translations so I don't think Odoo would want to remove them.
@mart-e can I ask you for feedback?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
I guess I was wrong there. Removed & fixed @GoodERPJeff!
Thank you for the report.

**Comment by mart-e** [comment]
Yes, indeed it was a mistake to keep it, some leftovers of previous module kept during forward ports.
Thanks for the notice !
