### ISSUE TITLE
[10.0] 404 Not Found : import FAQ

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#13903]
Impacted versions:

10.0

Steps to reproduce:

- Go on an import windows
- Click on help button (https://www.odoo.com/documentation/user/10/general/base_import/import_faq.html)

Current behavior:

Ningx return a 404 error.

Expected behavior:

Display the FAQ page about import

BTW, I hope that there is some information about the new feature of date formatting on this page because the standard Odoo date format does'nt work as long as it's that moment.js is used. So we need to put YYYY-MM-DD instead of %Y-%m-%d.

**Comment by adrienpeiffer** [comment]
OPW 691733

**Comment by JKE-be** [comment]
Hello @adrienpeiffer 

Thanks for the reporting.

Here the right link...: https://www.odoo.com/documentation/user/10.0/general/base_import/import_faq.html#where-can-i-change-the-date-import-format

**Comment by adrienpeiffer** [comment]
Thanks for the fix @JKE-be :smile:
