### ISSUE TITLE
The filter's add button beyond the firefox window

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#13917]
Impacted versions:
［10.0］
Steps to reproduce:
add some filter to any model
Current behavior:
if the number of filter bigger than one num, the filter's add button will beyond the window and can't be clicked.
Expected behavior:
When the filters added too many, the window can be moved up and down
Video/Screenshot link (optional):

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi,

A screenshot will be really Welcome ;)

**Comment by yueqin** [comment]
<img width="672" alt="uibug" src="https://cloud.githubusercontent.com/assets/11083821/19591260/a971be58-97a8-11e6-8a4e-2f59ac548943.png">

**Comment by JKE-be** [comment]
@yueqin 

ctrl - ?

**Comment by yueqin** [comment]
? sorry,I can't understand.
