### ISSUE TITLE
[10.0] Broken index page design in module page.

### ISSUE THREAD

**Issue by siddharth-techreceptives** [odoo/odoo#13910]
Impacted versions: [10.0]

Steps to reproduce: Apps -> Sales

Current behavior: Content goes out of page

Expected behavior: There should be proper layout design.

Video/Screenshot link (optional):
![sales_module_index_page](https://cloud.githubusercontent.com/assets/12948934/19558015/ca98a9c0-96e5-11e6-8982-a0209f64d1d4.png)

**Comment by Yenthe666** [comment]
Hi @siddharth-techreceptives,

Thank you for your report.
I've just checked this in the latest Odoo 10 (on runbot.odoo.com) and the lay-out is no longer broken?
Can you please double check and verify that it is no problem anymore?

Regards,
Yenthe

**Comment by siddharth-techreceptives** [comment]
Hi @Yenthe666 

I have checked on runbot.odoo.com with 10.0 community version
with commit 73b18964ea1766b2745897b2e8e5d0ac75d71106
Please check.

**Comment by Yenthe666** [comment]
Fixed in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/34934468-da588034-f9da-11e7-900b-b8767c3b0fea.png)
