### ISSUE TITLE
Add to Compare button

### ISSUE THREAD

**Issue by dhavalb-emipro** [odoo/odoo#139175]
Impacted versions: 16.0

Steps to reproduce: 

1. Go to Shop page and and check for any product without variant

![image](https://github.com/odoo/odoo/assets/26497773/f1008345-0fa8-4465-a921-982ec8d721ac)

Here, you will not able to see "**Add to compare**" option because it does not have any variants

2. Now, Add this Product to the wishlist and check in the wishlist page.

Here, you will be able to see "Add to Compare" Option even thoush it doesn't have variant

![image](https://github.com/odoo/odoo/assets/26497773/42478631-2861-4ef2-a5aa-085fbfad1f46)

Current behavior :

"Add to Compare" Option is visible to Wishlist page in product which doesn't have any variant

Expected behavior :

"Add to Compare" Option is should not visible to wishlist page if product doesn't have variants

**Comment by vava-odoo** [comment]
Hi @dhavalb-emipro 
Thanks for reporting. I created a PR to solve it.
Next time, don't hesitate to create a PR yourself (If it is your first contribution, please follow [the steps here](https://www.odoo.com/documentation/master/contributing/development.html#make-your-first-contribution)).
Cheers!

**Comment by vava-odoo** [comment]
Hi @dhavalb-emipro 
Issue was solved with https://github.com/odoo/odoo/pull/140174
Cheers
