### ISSUE TITLE
[9.0] account: improve usability, add sum of total/amount on invoice and payments list views

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#13914]
By standard, when you install Account if you go to **Account > Adviser > Journal Entries**
you have sum of amount and the bottom, like this:

![sum_of_amount](https://cloud.githubusercontent.com/assets/8862626/19561302/68083986-96d8-11e6-9c21-d90d539f4ee2.png)

But is not the case at Account > Sales > Customer Invoices, Account > Purchases > Vendor Bills and Account > Sales (Purchases) > Payments

![no_sum](https://cloud.githubusercontent.com/assets/8862626/19561395/d721b2d4-96d8-11e6-8ceb-1463e14bd566.png)

It could be a nice improvement to add these totals.

Like:
![totals](https://cloud.githubusercontent.com/assets/8862626/19561570/7f44e3a0-96d9-11e6-9cba-7317e2a23b3c.png)

**Comment by Yenthe666** [comment]
Hi @aristobulo-eezee,

Thanks a lot for your suggestions and improvements.
Is there a specific reason why you create a PR and an issue though? I believe Odoo (@mart-e) is not a big fan of that, since it creates some noise in Github and all the information could be added on the PR.

**Comment by aristobulo-eezee** [comment]
@Yenthe666 not really, I wasn't aware of it.

**Comment by Yenthe666** [comment]
@aristobulo-eezee,

The idea is to keep the whole conversation in one place in order to keep everything organized.
It is also written in the guidelines (https://github.com/odoo/odoo/wiki/Contributing#reporting-issues):

> No need to create an issue if you're making a PR to fix it. Describe the issue in the PR, it's the same as an issue, but with higher priority!

So if you can, please keep it to one? 😉 
Is it OK if I close this one?

Regards,
Yenthe

**Comment by nhomar** [comment]
2016-10-20 8:40 GMT-05:00 Yenthe V.G <notifications@github.com>:

> The idea is to keep the whole conversation in one place in order to keep
> everything organized.
> It is also written in the guidelines (https://github.com/odoo/odoo/
> wiki/Contributing#reporting-issues):
>
> No need to create an issue if you're making a PR to fix it. Describe the
> issue in the PR, it's the same as an issue, but with higher priority!
>
> So if you can, please keep it to one? 😉
> Is it OK if I close this one?
>

AFAICR.

- That was intentionally removed for the fact of not be able to sum
properly multi-currency operations.
- The sum is gotten with 1 click on group by currency.


-- 
--------------------
Saludos Cordiales

CEO at Vauxoo <https://www.vauxoo.com> Odoo's Gold Partner.


[image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
<http://about.me/nhomar?promo=email_sig>
