### ISSUE TITLE
Attendence calculation wrong when attendence passes day

### ISSUE THREAD

**Issue by dmi3san** [odoo/odoo#13924]
Impacted versions: 10

Steps to reproduce: Check in before day passes (let's say 23:55):, check out when day just passed (lets say next day 0:05)

Current behavior: Timesheet - Attendence shows negative attendance. Attendence is -24 hours + attendence. In the above example it says -23:50 

Expected behavior: Calculate properly ;)

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello @dmi3san 

Thank you for the reporting.

@Icallhimtest Maybe you will be interested to fix it if you can reproduce ?

**Comment by Icallhimtest** [comment]
You're absolutely right @dmi3san. 

It appears the timesheet reporting line computes the time difference regardless of the date difference.

Thanks for reporting this, I'll see to it it gets fixed.

**Comment by Icallhimtest** [comment]
Issue fixed at https://github.com/odoo/odoo/commit/8133f6492142fe172d03e6f9fe58ba2b7791c053 .

From now on, an attendance with 8 hours recorded from 20:00 to 04:00 the next day will be recorded as 8 hours on the first day. Same as in the attendance app reports.
