### ISSUE TITLE
Incorrect Inheritance

### ISSUE THREAD

**Issue by ninos-apk** [odoo/odoo#139213]
https://github.com/odoo/odoo/blame/9b5b3e5aef17fefc88d19eec7effa6eab62b9d4f/addons/sale/views/product_views.xml#L75
https://github.com/odoo/odoo/blame/9b5b3e5aef17fefc88d19eec7effa6eab62b9d4f/addons/sale/views/product_views.xml#L93
Consider Direct Inheritance from product.product_template_form_view Due to Missing 'description' Group Name in product_template_only_form_view"

**Comment by vava-odoo** [comment]
As explained on the PR, this change was not done in stable, but in master.
Cheers
