### ISSUE TITLE
[10.0] Payroll payslip lines duplicated on each compute

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#13925]
Impacted versions:
10.0 + e

Steps to reproduce:
1) Create a salary rule that has 'appears_on_payslip' = False.
- An example would be a company contribution that the employee does not need to see.
  2) Add it to a salary structure
  3) run a payroll/payslip calculation

Current behavior:
Numerous thing.
1) Every time you compute sheet, you will duplicate these 'hidden' lines
2) details_by_salary_rule_category no longer has any of the hidden lines, though they certainly contribute to categories (e.g. tests will fail, and bad things)
3) when using hr_payroll_account, lines with contribution registers and accounts that SHOULD be on the journal entry are not !!

Expected behavior:
1) every time you compute the sheet, the lines should be deleted and recalculated
2) details_by_salary_rule_category should have all categories (to be able to make complex rules and tests)
3) journal entry should have a line for every line with an account

Pull Request eminent.

**Comment by eburghar** [comment]
saw this bug after filling  #13987

**Comment by jaredkipe** [comment]
Yes, they are the same thing, and you came to the same conclusions as I did. Now we just wait for the pull request to be accepted.

**Comment by eburghar** [comment]
Yes thanks a lot. I confirm that your PR resolved the issue #13987
