### ISSUE TITLE
[10.0] Payroll calculations that use payslip.sum() are broken

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#13921]
Impacted versions:
10.0 + e

Steps to reproduce:
Create a payslip rule like 'result = 100.0 - payslip.sum('MY_RULE', '2016-01-01', '2017-01-01')'

Current behavior:
UserError(_('Wrong python code defined for salary rule %s (%s).')
  If you raise the actual error you'll get
(float) has no member 'cr'

Expected behavior:
The appropriate sum.

I'll have a PR very shortly for this.

**Comment by qdp-odoo** [comment]
fixed in 10 at revision bbe0731

thanks jaredkipe
