### ISSUE TITLE
[8.0] on form views button states are affected by whitespace

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#13927]
Impacted versions:
8.0

Steps to reproduce:
* When there is a whitespace between states in a form view only is showing the first of them. 

_e.g._
`<button string="Open Till" name="action_open" type="object" states="closing, opening" />`

Current behavior:

* The button is only showed in _'closing'_ state

Expected behavior:

* The whitespace between states should be ignored. The button should show in _'closing'_  and _'opening'_ states

**Comment by JKE-be** [comment]
Thank for the reporting.

but it is not an issue.
