### ISSUE TITLE
[10.0] Lot selection in work order shows unavailable serial numbers

### ISSUE THREAD

**Issue by karsteneb** [odoo/odoo#13923]
Impacted versions: 10.0 CE and EE

Steps to reproduce:
- create MO with word orders and with products to consume using serial number
- plan work orders for MO
- check lot selection in MO vs WO

Current behavior:
- lot selection in MO is done by lot symbol, shows only available lots, and + / - button to select (screen 1)
- lot selection in WO is done by select field, showing all lots/serial numbers for selected products, also those already used and unavailable. If multiple units of the same product are required to consume, each product can be selected with the same lot / serial number.

Expected behavior:
- lot selection in WO should be restricted to available lots. If lots are selected in MO, only those should be selectable in WO. If unique serial number is used, each lot selection must be enforced to be different.

This issue may be related to #13700 

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/3011785/19577248/afc3c6a8-9716-11e6-8c06-9c8236b464b6.png)
![image](https://cloud.githubusercontent.com/assets/3011785/19577333/38ca4a44-9717-11e6-966c-c306a2a78fa7.png)

**Comment by jco-odoo** [comment]
This is a feature for later on.  I am just afraid that if we put a domain just like that, it will be too restrictive.  And you can easily avoid the problem by barcode scanning.  (then putting warning colors when it is not available, ... might make more sense.  Need to see)

**Comment by karsteneb** [comment]
Best would be to use the same UI as for lot selection in MO, with + and - symbols. The lots default to available products, but you can override it. And it's consistent between MO and WO.

**Comment by jco-odoo** [comment]
We did not want to confuse the worker with a lot of serial numbers to
choose from.

**Comment by pedrobaeza** [comment]
@jco-odoo any news about this? Can we close it?

**Comment by jco-odoo** [comment]
Should have been closed years ago.  If you suggest lots in wos, the risk of selecting the wrong one is greater.  It undermines the concept of tracking.  The lots on the mo are about reservation...

**Comment by bunhin** [comment]
I found that the lots listed for selection in WO should be limited only to the ones which stock is available at manufacturing location, current behavior is listing all lots history as well, it make some sort of difficulties when the lot # of the item is already big in number.

The other issue is when the qty of a lot# is about to finish (not enough qty to complete all wo qty) therefore 2 different lot should be consumed, but the current field only possible to select one lot# only.  Splitting wo qty is just not practical or not possible (because other item in bom may have same situation but vary in term of qty)  please to consider it again to : allow only lot no# with available qty and to allow at least 2 lot no# on a component item of the WO.

**Comment by jco-odoo** [comment]
It is possible with barcode scanning.  Avoid errors.

**Comment by ray-odoo** [comment]
@bunhin - I believe the statement was meant to reflect that you can't scan something in the real world that you don't have - so you can't select a lot with no available stock, unless the real world doesn't match Odoo.  I just tried this in Odoo v12 and if a second Lot is required, users are prompted to select a second lot for the remaining quantity - and this continues until all quantity are planned to consume

Check https://www.odoo.com/forum/help-1/question/lot-numbers-inventory-can-odoo-autoincrement-skip-to-the-next-lot-automatically-140736 to see an example Automated Action that validates Lot number selection for Work Orders - if required - it doesn't change which Lots are made available to the User, it just validated they are selecting ones that meet specific rules (which could be company specific).
