### ISSUE TITLE
l10n_ma Issue

### ISSUE THREAD

**Issue by Imoujib** [odoo/odoo#13934]
Impacted versions: all

Steps to reproduce: Install the module, some accounts are missing in the accounting chart.
Accounting reports are not in the official format. Default accounts in the product category  and currency symbol are incorrect. 
Current behavior:

Expected behavior: We can provide you the patch for odoo 8.0.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Imoujib,

Thank you for your report.
In order to maintain these kind of issues we've made specific bug reports to bundle all knowledge and issues. Please provide feedback/info on https://github.com/odoo/odoo/issues/20287

Regards,
Yenthe
