### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by kishan-chotaliya** [odoo/odoo#13936]
while opening https://doc.odoo.com/trunk/mail/mail_message/ this link it gives me error

**Comment by Yenthe666** [comment]
Hi @kishan-chotaliya,

Thank you for the issue report.
That documentation is outdated either way, you should look at the new documentation, which is here: https://www.odoo.com/page/docs
@JKE-be nevertheless, can you fix the internal?

**Comment by JKE-be** [comment]
This doc is really outdated now...
And fix it is a low priority.

Please use www.odoo.com/documentation instead !
