### ISSUE TITLE
[9.0?] Incorrect Documentation on odoo.com

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#13941]
Impacted versions:
Odoo website
Steps to reproduce:
visit https://www.odoo.com/documentation/user/9.0/inventory/management/reporting/valuation_methods_anglo_saxon.html
Current behavior:
Refers to deferred tax assets and liabilities when processing sales and purchases.  These accounts refer to the temporary differences that arise between financial accounting standards and tax accounting.  They have absolutely nothing to do with sales taxes or invoices, but rather the temporary differences between allowed deductions. (e.g. insurance is typically prorated across applicable periods in financial accounting, in tax accounting the full amount is deductible immediately)
Expected behavior:
Refer to sales tax collected (liability, as you owe that to tax dept), purchase tax paid (asset, as tax dept owes you), at least in a typical VAT regime.
In fact tax should be removed entirely, it just serves to confuse the example.
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
@mart-e

**Comment by gdgellatly** [comment]
@mart-e This issue is still valid, Deferred Tax has absolutely nothing to do with inventory accounting.  It is a financial accounting term to account for the taxable portion of the value used for taxation purposes and the carrying value of assets and also the timing differences between when expenses can be recognized from differing accounting and tax regime requirements.

http://www.investopedia.com/terms/d/deferredtaxliability.asp
http://www.investopedia.com/terms/d/deferredtaxasset.asp

**Comment by gdgellatly** [comment]
Yep still wrong in 11.0

**Comment by pedrobaeza** [comment]
@mart-e any news about correcting the documentation?

**Comment by mart-e** [comment]
If somebody wants to give a try to correct the content, I can review the form but not the content.

**Comment by pedrobaeza** [comment]
@gdgellatly I can't help on anglo-saxon questions, so maybe you are the best suited for making that correction.

**Comment by moylop260** [comment]
@hbto I think you are the man

**Comment by hbto** [comment]
I think you are too the man @gdgellatly 
You are best suited for that.

Regards.

**Comment by Yenthe666** [comment]
@gdgellatly any chance you can make a PR & fix this? ;)

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no response in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information or with a PR to resolve this.

Regards,
Yenthe
