### ISSUE TITLE
Salesman access  bugged id?

### ISSUE THREAD

**Issue by matheo** [odoo/odoo#13940]
Impacted versions: 10.0

Just checking around I saw that calendar.event.type model access have the same ID for user and saleman roles. I think that's a bug right?

```
access_calendar_event_type_sale_user,calendar.event.type.user,...
access_calendar_event_type_sale_user,calendar.event.type.salesman,...
```

last line should be:

```
access_calendar_event_type_sale_salesman,calendar.event.type.salesman,...
```

https://github.com/odoo/odoo/blob/10.0/addons/crm/security/ir.model.access.csv#L29

**Comment by Yenthe666** [comment]
Hi @matheo,

Thanks a lot for your bug report.
I've just checked this and this is indeed incorrect. I've made a fix at https://github.com/odoo/odoo/pull/22544

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @matheo,

It was handled in https://github.com/odoo/odoo/commit/85a3e1e38593609086889654749589f633d924bf and will be kept as is in the old versions for stability.
Thanks for the report!

Regards,
Yenthe
