### ISSUE TITLE
This cron task is currently being executed, command line switch preventing this on test environments

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#13958]
**Impacted versions:**
9.0c possibly others
**Steps to reproduce:**
Can be tricky to reproduce, basically have a cron job run every 1 minute and user -d database_name -u all to update every module
**Current behavior:**
The update process is halted with a ParseError:
ParseError: "Record cannot be modified right now: This cron task is currently being executed and may not be modified Please try again in a few minutes
**Expected behavior:**
There should possibly be a command line argument that I can pass on ./odoo.py that will stop all the schedulers (for similar testing purposes)
Video/Screenshot link (optional):

**Comment by houssine78** [comment]
Hi @daramousk 

how did you manage to solve your error setting the cron to false in postgres doesn't seem to be sufficient. there is a lock on the table/record that need to be removed.

**Comment by daramousk** [comment]
Find which locks are in place with by searching the pg_stat_activity table. (refer to http://chrismiles.info/systemsadmin/databases/articles/viewing-current-postgresql-queries/)

You should get the output (see screenshot)
![query_start](https://cloud.githubusercontent.com/assets/3503159/26054329/d21eac9e-3974-11e7-920f-302e7fac3ecd.png)

You can solve this by moving the cron's nextcall date to a date > now() and restart the odoo-server.

**Comment by houssine78** [comment]
thanks just saw your response!

**Comment by pedrobaeza** [comment]
This is a question on how you deploy your updates, and this obviously can't be done in parallel with the cron jobs, so it's not a real Odoo problem. Any way, most of the cron jobs XML data are noupdate records, so it's even more difficult to find the problem.

Closing as no actual issue.
