### ISSUE TITLE
10.0 base_import doesn't autodetect columns with "External ID"

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#13955]
Impacted versions: 10.0

Steps to reproduce:
1) Follow the official documentation about base_import, in particular the section "What's the difference between Database ID and External ID?"
https://www.odoo.com/documentation/user/10.0/general/base_import/import_faq.html#what-s-the-difference-between-database-id-and-external-id

Download the sample files provided in the documentation "External_id_3rd_party_application_product_categories.csv"

2) Go to Sales > Configuration > Product > Product Categories. Click on "Import" and load the sample file "External_id_3rd_party_application_product_categories.csv"

Current behavior:

The last column "Parent Category/External ID" is not auto-detected.

Expected behavior:

The last column "Parent Category/External ID" should automatically be mapped to "Parent Category/External ID"

**Comment by alexis-via** [comment]
Short code analysis: in addons/base_import/models/base_import.py, in the method parse_preview(), the result of the method is a dict and the 'matches' key returns:
```
{0: [u'id'], 1: [u'name'], 2: [u'parent_id', u'id']}
```

So this seems OK. The problem seems to be after that code, so it's probably somewhere is the JS code.

**Comment by bistaray** [comment]
![](http://i.imgur.com/oel3pOJ.png)

With this checked, it will detect.

**Comment by pedrobaeza** [comment]
Closing as answered
