### ISSUE TITLE
[15.0] [Docker] Taking backup fails with Postgres subprocess error

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#139687]
Impacted versions: 15.0

Steps to reproduce:

1. Run a postgres database image:
   ```
   docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:13
   ```
2. Run the Odoo 15 Docker image:
   ```
   docker run -p 8069:8069 --name odoo --link db:db -t odoo:15.0
   ```
3. Go to `localhost:8069`
4. Save the generated master password
5. Create a new database with demo data
6. In the new database, install some module, I installed CRM (this may not be necessary but I played it safe)
7. Go to `localhost:8069/web/database/manager`
8. Backup the database you created in the previous steps

Current behavior:

The backup fails to an error. On the page it says
```
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmp96l_bs4n/dump.sql', 'test') error 1
```

In the logs the following can be seen:

```
2023-10-25 08:28:40,682 1 INFO test odoo.addons.base.models.ir_cron: Job `Snailmail: process letters queue` done. 
2023-10-25 08:28:58,474 1 WARNING test odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller. 
2023-10-25 08:28:58,488 1 INFO test odoo.sql_db: ConnectionPool(used=3/count=9/max=64): Free leaked connection to 'user=odoo password=xxx dbname=test host=172.17.0.2 port=5432 sslmode=prefer' 
2023-10-25 08:28:58,503 1 INFO test werkzeug: 172.17.0.1 - - [25/Oct/2023 08:28:58] "GET /web/database/manager HTTP/1.1" 200 - 5 0.002 0.029
2023-10-25 08:29:13,534 1 INFO test odoo.service.db: DUMP DB: test format zip 
2023-10-25 08:29:13,578 1 ERROR test odoo.addons.web.controllers.main: Database.backup 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1134, in backup
    dump_stream = odoo.service.db.dump_db(name, None, backup_format)
  File "<decorator-gen-19>", line 2, in dump_db
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 41, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 245, in dump_db
    odoo.tools.exec_pg_command(*cmd)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 133, in exec_pg_command
    raise Exception('Postgres subprocess %s error %s' % (args2, rc))
Exception: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmp96l_bs4n/dump.sql', 'test') error 1
2023-10-25 08:29:13,609 1 INFO test werkzeug: 172.17.0.1 - - [25/Oct/2023 08:29:13] "POST /web/database/backup HTTP/1.1" 200 - 5 0.003 0.098
```

Expected behavior:

Taking the backup should succeed.

Video/Screenshot link (optional):

The error when trying to take the backup:

![image](https://github.com/odoo/odoo/assets/2587901/f06b7496-73c8-458e-a37a-ff3298f3a3af)

Support ticket number submitted via odoo.com/help (optional):

[none]

Further investigation:

This issue seems to appear when using a recent image, as the new 16.0 version of the `postgresql-client` (and therefore `pg_dump`) was released in september.

We have experimented in a debugger and determined the error most likely is due to [`exec_pg_command`](https://github.com/odoo/odoo/blob/71fc52dfb8ab27ba6e4766e33993ce1716d28726/odoo/tools/misc.py#L129) opening `dev/null` for reading instead of writing, and then using that as `stdout`:

```
with open(os.devnull) as dn:  # note no "w" flag
        args2 = (prog,) + args
        rc = subprocess.call(args2, env=env, stdout=dn, stderr=subprocess.STDOUT)
```

When we run this code in the debugger and provide the `"w"` flag to `open`, the error does not repeat.

We have checked that the command does not actually seem to want to write anything into the provided `stdout`: possibly the new version of `pg_dump` simply opens the file for writing regardless of whether it needs to, unlike previous versions?

**Comment by aisopuro** [comment]
The relevant lines seem to have been most recently changed in 806648d611ceef5f12c812832118d8f6677012a0 by @KangOl

**Comment by vaab** [comment]
This bogus line of code on odoo's side is on all recent version on my end I could find them on `12.0`, `14.0`. And ok version for `pg_dump` are `14.1`, `15.1`. The culprit seems to be `pg_dump` version `16.0`.

**Comment by diego-guerrero** [comment]
Hi there! Anybody found a solution for this? I had an image downloaded from 10 months ago and I tried to recreate my instance using a Compose file but didn't work, I had to save & import my old Docker Odoo 15 image because currently available now did not work properly...

**Comment by aisopuro** [comment]
For now the only workaround I've managed to come up with is to fork this Dockerfile, pin the `postgresql-client` version to 15 and using that to build the image you use. Alternatively, if you use the official Odoo image as a base image in your own Dockerfile, perhaps you can force-reinstall `postgresql-client` at 15 in your child image?

**Comment by m-chingis** [comment]
Another workaround is to use older Dockerfile commit and build your local image. This one from 13th June is ok:
https://github.com/odoo/docker/blob/7a7169250712b280c009e6e507f0c97a68e9c5c0/15.0/Dockerfile 

 but you may try newer ones as well, 20230925 - is broken, you need to find one in between these dates.
 
 p.s. this is very strange, that this already happened earlier, and here we go again. Moreover already 1.5 month has passed and still not fixed.

**Comment by droidosergioh** [comment]
Me sigue dando el mismo error con los nuevos contenedores
![image](https://github.com/odoo/odoo/assets/15266734/7557e533-10e7-4350-b824-fc92d5ac44c1)

**Comment by droidosergioh** [comment]
> Hi there! Anybody found a solution for this? I had an image downloaded from 10 months ago and I tried to recreate my instance using a Compose file but didn't work, I had to save & import my old Docker Odoo 15 image because currently available now did not work properly...

I am actually facing the same problem, the code of the container looks updated but still it is impossible to make a backup or restore it

**Comment by aisopuro** [comment]
@droidosergioh are you seeing any traceback in you container logs from Odoo?

If the error causes no traceback in the Odoo logs, it may be a different error coming postgres, which might then be a separate issue.

**Comment by droidosergioh** [comment]
> @droidosergioh are you seeing any traceback in you container logs from Odoo?
> 
> If the error causes no traceback in the Odoo logs, it may be a different error coming postgres, which might then be a separate issue.

Yes, I am also getting the error in the logs
![image](https://github.com/odoo/odoo/assets/15266734/ef85dcc4-216d-4799-b359-2326c7d10063)
