### ISSUE TITLE
[9.0][10.0][purchase] Domain not applied until selecting a vendor when creating a vendor bill

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#13968]
Impacted versions: 9, 10

Steps to reproduce:
1. Create some purchase orders and requests for quotation, for asustek and delta pc.
2. Go to vendor bills, edit the camptocamp draft one that comes by default.
3. Open the _add purchase order_ selector.

Current behavior: you can choose draft POs, and from any supplier.

Expected behavior: you can choose only camptocamp's, ready to invoice, POs.

Video/Screenshot link (optional): [recording.zip](https://github.com/odoo/odoo/files/550208/out.ogv.zip)

@Tecnativa

**Comment by bistaray** [comment]
I would suggest Vendor Bills are created by the vast majority of users by clicking NEW (in which case PO's are filtered as soon as you select the Vendor).

I have not see anyone create a new document by editing a draft document that has already been created.

**Comment by Yajo** [comment]
Sorry, I would suggest that Odoo works fine instead. That field has no default domain, so either add a sane default to it or call its onchange as soon as the form is loaded.

**Comment by pedrobaeza** [comment]
Ray, as a possibility you have in the system, it should work correctly although you barely use it. There can be other person that uses a lot this option.

**Comment by pedrobaeza** [comment]
@Yenthe666 this is still a problem. Can you ping the proper person?

**Comment by Yenthe666** [comment]
Sure thing! @sle-odoo could you have a look please?

**Comment by pedrobaeza** [comment]
@sle-odoo any news on this?

**Comment by pedrobaeza** [comment]
@sle-odoo do you have any solution for this? A similar problem has arisen recently in #24507 with another field with an incorrect initial domain.

**Comment by sle-odoo** [comment]
@pedrobaeza i consider this issue not really pressing since the statement of @bistaray is still valid two years later

but yeah we still need to improve that part somehow

**Comment by pedrobaeza** [comment]
Yeah, in this case is not critical.

**Comment by pedrobaeza** [comment]
@avw-odoo was there any feedback on this?

**Comment by pedrobaeza** [comment]
Closing this one, as solved in later versions.
