### ISSUE TITLE
[10.0][hr_employee]when create a new user,it should be create an associated hr.employee

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#13979]
Impacted versions:
[10.0]
Steps to reproduce:
1. create a user
2. set the res.users.sel_groups_3_42_43
Current behavior:
did't create an associated hr.employee
Expected behavior:
create an associated hr.employee
Video/Screenshot link (optional):

**Comment by intero-chz** [comment]
What group have you set in your example? A name would be very nice. It is hard to discuss this issue, without knowing the group.

But generally i don't see any case where every Odoo user will be an employee.

**Comment by yueqin** [comment]
1. the group Employees
2. if I set the employees group,no matter which one i selected,the user will be an employee,so it should be create an associated emlpoyee when I create a user.

**Comment by intero-chz** [comment]
The Employee group is somewhat a special group. It will be used in Odoo without even installing any human resource module/app. I'm not a big fan of this concept, but it is as it is.

**Comment by yueqin** [comment]
Oh, I see, thanks very much. but I always Keep my opinion.
thanks again.

**Comment by yueqin** [comment]
Oh, I see, thanks very much. but I still keep my opinion.
Thanks again.
