### ISSUE TITLE
[10.0] «FATAL ERROR: v8::Context New() V8 is no longer usable» (debian nightly since 20101014)

### ISSUE THREAD

**Issue by voland-666** [odoo/odoo#13975]
Impacted versions: 10 - From nightly Debian repo, since build 10.0.20161014 up to today (20161025)

Steps to reproduce: Just open the instance base url to log in

Current behavior: FATAL ERROR: v8::Context New() V8 is no longer usable
The application throws out the following error message: 

<inline asset> defined in bundle 'web.assets_frontend' */
                body:before {
                background: #ffc;
                width: 100%;
                font-size: 14px;
                font-family: monospace;
                white-space: pre;
                content: "FATAL ERROR: v8::Context::New() V8 is no longer usable\A This error occured while compiling the bundle 'web.assets_frontend' containing:\A     - /web/static/lib/bootstrap/less/variables.less\A     - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less\A     - /web/static/lib/bootstrap/less/mixins/buttons.less\A     - /web/static/src/less/variables.less\A     - /web/static/src/less/utils.less\A     - /web_editor/static/src/less/web_editor.variables.less\A     - /web/static/src/less/import_bootstrap.less\A     - /web_editor/static/src/less/web_editor.common.less";
            }

Expected behavior: Until build 10.0.20161013 from the nightly Debian repository everything was working fine. dpkg -i that build cures the problem and everything seems to be back to normal. 

I am testing odoo on a plain Debian Jessie instance (no third party repos apart from odoo's) with nginx, postresql (listening on a unix socket) , and uwsgi (on a unix socket too, managed as a systemd socket/service).
I am available for further details and/or testing patches, if this is determined to be an actual regression with odoo. Thank you.

![schermata da 2016-10-25 14 44 13](https://cloud.githubusercontent.com/assets/23054211/19686564/f9348ff8-9ac1-11e6-884b-9044c583be43.png)

**Comment by voland-666** [comment]
Answering my own question after some weeks. Running odoo as a uwsgi app, you may need to raise memory limits. The relevant parameters I set were

limit-as        = 512
reload-on-as    = 384
reload-on-rss   = 192

Setting them as follows happily fixes the problem:

limit-as        = 768
reload-on-as    = 512
reload-on-rss   = 256

Thanks to everyone who helped with this

**Comment by Yenthe666** [comment]
Thank you for answering and closing your own report!

**Comment by sylnsr** [comment]
I think this ticket is still valid. The problem is poorly handled and gives no clue that the issue is related to not having enough memory.  Should there be a separate ticket for handling this error in a more intuitive way?
