### ISSUE TITLE
[ saas4,saas5,8.0,master ]website snippets editor not working in Firefox

### ISSUE THREAD

**Issue by vilder** [odoo/odoo#1397]
website snippets editor with firefox only works in saas3

how to reproduce:
-- on website click on edit
-- insert banner snippet
(Customize button is working)
-- save
-- edit 
(Customize button NOT working)

**Comment by sle-odoo** [comment]
The base edition is correctly working on Firefox. If you're still facing this issue with an updated codebase feel free te comment and i'll reopen.
Regards
