### ISSUE TITLE
Chrome Version 54.0.2840.71 (64-bit)  Invalid CSRF Token

### ISSUE THREAD

**Issue by vernichon** [odoo/odoo#13984]
Steps to reproduce: login

With the last chrome version Version 54.0.2840.71 (6 4-bit)  when I try to connect I received this error

```
Bad Request

Invalid CSRF Token
```

No problem with firefox or Safari

**Comment by JKE-be** [comment]
@vernichon Cannot reproduce ! 

Please provide more details...

Can you reproduce it on runbot ?

**Comment by vernichon** [comment]
Which details you want ?

**Comment by vernichon** [comment]
I can't reproduce it on runbot

I don't understand why  if work with safari, ie and firefox and not with chrome.

The problem seems in the function consteq, with safari, ie and firefox   no problem result = 0 but not with chrome always 95

For information it's working fine with old version of chrome

But I understand that if I can't reproduce in runbot is not your problem.

Thank You

**Comment by JKE-be** [comment]
The only check at first view that I can see,  is to be sure that csrf is sent to server and available in the dispatch method.

Because after it, it seems to be independent of the browser...

**Comment by vernichon** [comment]
I don't know how but I know why
With chrome the session.sid change between page, not with safari, ie and firefox. 
So when odoo validate csrf is not valid, it's normal the session.sid has changed

But I don't understand why the session sid change.

**Comment by JKE-be** [comment]
@vernichon Are you sure that you have not a module which block cookies ?

**Comment by vernichon** [comment]
But why for chrome and not for firefox ou ie ?

**Comment by JKE-be** [comment]
Because if, on your chrome, you have something that block the cookies...
Your session is not saved in the cookies, so at each request you get a new session !

On Firefox, if you have the cookies saved, it will work.... because the session is saved inside and each request retrieve the session...

**Comment by vernichon** [comment]
Ok chrome module, I have understand Odoo module :=)

 I have try with several computer and operating system, same result, so I think is not a module chrome problem

**Comment by JKE-be** [comment]
do you have a public link or temp link (proxy ngrok eg) to allow me to test
if request is normal ?

**Comment by jubbon** [comment]
I have the same bug with Chrome 55.0.2883.87 (64-bit) on Linux Mint 17. But if you open the private tab (Ctrl-Shift-N) and login again, the error does not occur. Conversely, if the error in the private tab, there is no error in a regular tab.

**Comment by Yenthe666** [comment]
Hi @vernichon ,

I'm closing this report as there has been no feedback or further information in months.
If you still face this issue please provide us with more information, in that case I will reopen the bug report.
At this point we do not have enough information to further debug this issue.

Regards,
Yenthe
