### ISSUE TITLE
Email field in e-commerce 

### ISSUE THREAD

**Issue by alfieqashwa** [odoo/odoo#13981]

**Comment by alfieqashwa** [comment]
Email field at e-commerce shop is integer that it should be string. Just try order some product with smartphone, go to chart and when you fill the email field on customer required information, your smartphone keyboard will set to numpad instead alphabet.

**Comment by alfieqashwa** [comment]
Odoo 10

**Comment by JKE-be** [comment]
Thanks for the reporting

Fixed by https://github.com/odoo/odoo/commit/651738303a06b8c24b0d4334e4a62343884b305b
