### ISSUE TITLE
required_if_provider not working with payment acquirer class

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#1398]
required_if_provider in payment acquirer class implement a special way of making field required if certain provider is set, but it seems to be broken as even if fields marked with "required_if_provider" are set blank, system is accepting the input which is not the desired way. 

Check in Paypal payment acquirer, I have checked with current 8.0 branch.

Regards,
Parthiv

**Comment by Yenthe666** [comment]
Hi @parthivgls,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
