### ISSUE TITLE
This should have return keyword?

### ISSUE THREAD

**Issue by dtorreskaertech** [odoo/odoo#140043]
https://github.com/odoo/odoo/blob/ab3c5cb7f5ff4a4484675fa501a432d643bd4f10/addons/hr_expense/models/hr_expense.py#L1337

**Comment by kalungia** [comment]
Hey @dtorreskaertech, there is no need as `self._do_approve()` is the last function, and when it is called `def _do_approve(self):` it will do the return. Therefore `self_.do_approve()` under `def approve_expense_sheets(self):` is okay.
