### ISSUE TITLE
[17.0] project_todo - Drag and drop - Uncaught promise > value is not iterable

### ISSUE THREAD

**Issue by MaarvynS** [odoo/odoo#140117]
Impacted versions: 17.0

Steps to reproduce:

Drag and drop any cards in the Kanban view

Current behavior:

Uncaught promise > value is not iterable

Expected behavior:

The card should move between the differents stages

Video/Screenshot link (optional):
https://gyazo.com/28e028b5e91eb3bf48fd4ca29db11cf1

Support ticket number submitted via odoo.com/help (optional):

In my opinion, that is because of this line : 
            <kanban default_group_by="personal_stage_type_ids"
on this path : 17.0\addons\project_todo\views\project_task_views.xml
line : 10

**Comment by vava-odoo** [comment]
Hi @MaarvynS 
Thanks for reporting. This was fixed with https://github.com/odoo/odoo/pull/140050.
Cheers
