### ISSUE TITLE
Adding optional products to quotation not possible when different order lines already are using that product

### ISSUE THREAD

**Issue by w4Odoo** [odoo/odoo#140161]
Impacted versions: Odoo v16

Steps to reproduce:
1. Create a quotation
2. add a sepcific product (product x) to sales order lines
3. add the same product (product x) to optional products of quotation
4. they system doesn't recognise it as a separate order line. It thinks that the product is already added to quotation and the optional products turn green.

Expected behavior:
The system should be able to differentiate that the product added to optional products is a separate sales order line. It should be handled separately and it should be possible to add it to the quotation.

Video/Screenshot link (optional): https://drive.google.com/file/d/1UV6n6e4QdOxOK7NtdeOKNZ6mnmWoRxSc/view?usp=drive_link

Support ticket number submitted via odoo.com/help (optional): #3573799

**Comment by vava-odoo** [comment]
Hi @w4Odoo 
As mentioned in the ticket, this is not a bug but more a limitation. A feedback was done internally, so I close the ticket.
Cheers!

**Comment by RaceCarEngineer** [comment]
I have exactly the same problem. Is there any solution or setting? 
I have a general product "workshop hours" which i adjust the description. 
for optional work I use the same product, but have another description (of work to be done).
Unfortunately, in the Portal, it just makes the amount freely user adjustable. 

It should be handled as a usual optional product and be added as a separate line if the customer adds it to the quotation. 
Freely user adjustable amount should be a checkbox field and not related to optional product!

Please let me know if there is any known solution?
