### ISSUE TITLE
auth_signup: auto-delete can't be set via GUI in password reset

### ISSUE THREAD

**Issue by FrancescoBallerini** [odoo/odoo#140227]
### Impacted versions:

- [ ] 14.0 

### Steps to reproduce:

- Settings/Technical/Email/Templates
- Open template "Auth Signup: Reset Password"
- Open TAB "Advanced Settings" and remove flag auto-delete
- Use "Send Password Reset Instructions" on a user

Reproduce it on "Auth Signup: Odoo Connection": same steps, just remove auto-delete flag on this template, then use "Send an invitation Email" in the User form-view instead of password reset action.

### Current behavior:

`auto_delete` field will be overridden along with other fields so we're not able to track Invitation (from User Form) and Reset Password emails.

https://github.com/odoo/odoo/blob/453f575a4c0de1b9556922d8255e2a31f1cf7eac/addons/auth_signup/models/res_users.py#L190-L197 

### Expected behavior:

Odoo user must be able to set `auto_delete` field via GUI and track "reset password" emails

**Comment by mart-e** [comment]
Hello,

Thank you for the report and the PR but it's forced on purpose. We don't want to allow changing that as the reset password template is something sensitive, you don't want other people than the user to be able to read it's content.
Why do you want to change that value?

**Comment by FrancescoBallerini** [comment]
@mart-e Hi Martin,

Thanks for this feedback! Our requirement was to perform a massive password reset on all DB users after a migration. 
I see that we can natively set a Password Reset for multiple users in odoo14, in this scenario it would be a good thing to keep email records, in order to check if everything was sent from Odoo to SMTP. 

As far as I know backend users by default must have full "Administration Access" to be able to read email, so I thaught at least a "full admin user" could have been able to read those records. But I suspect that access rules to those models are rarely left unchanged and it's easy to broke this rule by leaving "standard user" having access to sensible data, so I definitely get your point. 

Thanks for explaining!

**Comment by mart-e** [comment]
Indeed a lot of different configurations are possible. We want to ensure that, even in the scenario where an admin gave too many access by mistake, malicious users won't be able to read generated reset emails :)
