### ISSUE TITLE
[8.0] Bad currency conversion for taxes on invoices (Again)

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#14024]
Impacted versions:

At least 8.0

Steps to reproduce:

See https://youtu.be/kmXVzf3ApaM

Current behavior:

Currently if you validate an invoice (even with an invoice date) after the initial conversion rate has changed
(if the rate is changed between creation and validation). The tax amount and the credit/debit amount is not computed from the same rate.

This one is responsible for several production issues for tax reporting for the fiscal administration.

Expected behavior:

The tax amount and the credit/debit amount must be computed from the same rate.

Video/Screenshot link (optional):

https://youtu.be/kmXVzf3ApaM

Related issue : https://github.com/odoo/odoo/issues/13473

My proposal to fix this one : https://github.com/odoo/odoo/pull/13621

**Comment by adrienpeiffer** [comment]
OPW 692430

**Comment by nim-odoo** [comment]
I've made a PR based on yours, but somehow slightly safer: https://github.com/odoo/odoo/pull/14156
- use of `math.copysign`, no need of complicated logic to do such (and avoid division)
- only recompute if the currency of the invoice is different from the currency of the company 

However, I'm not convinced we should support this corner case. I agree that at the moment, it silently introduces accounting errors. But that only appears when you start modifying the exchange rate after an invoice creation at this date (or later). This is definitely not common.

If we introduce the suggested fix (either yours or mine), it implies we will recompute the tax amount for every invoice in a foreign currency. My fear is that this will cause more troubles than it solves...

@qdp-odoo 
@beledouxdenis

**Comment by nim-odoo** [comment]
Solved in https://github.com/odoo/odoo/commit/0a17be70e0b99cae0d87abc83f615af9e54900af
