### ISSUE TITLE
transifex community is hard to join

### ISSUE THREAD

**Issue by phohomi** [odoo/odoo#140302]
Impacted versions: all

Steps to reproduce: send join request on transifex to the odoo community

Current behavior: no response, even after a week

Expected behavior: being able to participate in the project

**Comment by mart-e** [comment]
Hello,

Which community are you trying to join? The projects are open for anyone to translate.

**Comment by phohomi** [comment]
Hi, Bonjour Martin,

The odoo community on transifex, I'd like to participate: we've been working with odoo for a couple of years now and feel that some translations could be better.

The problem is that it is open, but only a little bit open; you need to apply, which I've done, but the request is not yet approved.

I was able to send you a message on the transifex platform a couple of days ago (I've asked for help on the transifex forum, and they told me how to find and message the person in charge of a project :-) )

Best regards

**Comment by mart-e** [comment]
Hi,

Sorry I only see now you message on Transifex :)
I see you want to join  the Dutch team but you should not need to apply, you can just join it :thinking: 
![Screenshot 2023-11-02 at 12-09-04 Teams Overview](https://github.com/odoo/odoo/assets/564822/5e1c3335-a342-406f-9650-99bc4be0b8cb)

Can you add a screenshot of what you see?
