### ISSUE TITLE
Do not round the subtotal in Saleorder

### ISSUE THREAD

**Issue by falconsoft3d** [odoo/odoo#14035]
Impacted versions: 9.0

Steps to reproduce:  rounding 0

Current behavior: 
Do not round the subtotal

Expected behavior:
Do round the subtotal

Video/Screenshot link (optional):
https://www.dropbox.com/s/jd07qzh89uvqw48/odoo-error.jpg?dl=0

**Comment by dansanti** [comment]
Hi! This happends only with sale order price_subtotal if was configured decimal precision  0, on invoice subtotal round fine and no decimal place was showed.

**Comment by Yenthe666** [comment]
Indeed - this looks like a lack of configuration.
