### ISSUE TITLE
16.0 Spurious SVL Being Created

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#140410]
Impacted versions: 16.0

What are the steps to reproduce your issue?
Price Decimal Precision set at 5, currency at 2. Anglosaxon enabled.
Have a product with a unit / purchase cost of 3.30125
Create Purchase for 1500.00 and receipt in.
This creates an SVL and AML for 4951.88
Create Bill with unit cost of 3.30125 and total amount of 4951.88
Confirm Invoice

What is the current behavior that you observe?
The layer unit price value is calculated unrounded (line 304, purchase_stock/models/account_move_line.py) - so 4951.88 / 1500 = 3.30125333333. 
This is then subtracted from the Invoice unit price leaving a difference of 0.00000333333
Despite the price_unit difference being less than the precision this then multiplies out to be 0.005 that gets rounded to 0.01.
A new SVL layer is created, and a new move valued at 0.01 and remaining value on existing correct layer is reduced by 1c.
When anglosaxon attempts to reconcile the various moves, it is unable to because there is now a 1c difference in the sum of the relevant AML's.

What would be your expected behavior in this case?
Round line 304 to unit cost precision.
Not to create useless SVL that is wrong 
Reconcile anglosaxon records normally.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 3576593

**Comment by gdgellatly** [comment]
Note there are no nice insertion points to resolve this on the svl side, however if I override the aml unit price get, all automated tests now pass - not ideal, but those numbers get rounded on way through elsewhere anyway.

```python
    def _get_gross_unit_price(self):
        price_unit = super()._get_gross_unit_price()
        if self.quantity:
            price_unit = float_round(price_unit * self.quantity, precision_digits=self.currency_id.decimal_places) / self.quantity
        return price_unit
```

**Comment by fpodoo** [comment]
Rounding is not the solution, and will lead to other issues.

Have to check code but my feeling is that price unit should not be used, but total value of layer instead (prorata the quantity moved).

**Comment by gdgellatly** [comment]
@fpodoo Well you aren't wrong. It is just the current design makes rounding the issue. You round a price unit for the invoice aml, then don't round it for the determination of an extra SVL when comparing with the rounded price unit, then compare them. As you can see my current workaround is to unround the price unit.

We have a pretty extensive test suite around this issue, and unrounding price unit sees them all pass.

**Comment by gdgellatly** [comment]
> Rounding is not the solution, and will lead to other issues.
> 
> Have to check code but my feeling is that price unit should not be used, but remaining value of layer instead (prorata the quantity moved).

Well I disagree on remaining value. Unless you are going to prorate difference straight to P&L (which would be awesome btw and the missing link in the new removal of PPV accounts). I think the correct comparison is actually what I did (although probably not in the right way or the right place) which basically equated to abs(aml.balance) == svl.value.

**Comment by fpodoo** [comment]
`_get_gross_unit_price` method should be removed, and never used in purchase_stock, or elsewhere. Instead, purchase_stock should be rewritten to use the total value of the layer (prorated on quantities if needed)

If you don't work with total values, there is no way you can guarantee the equivalence with all the multiplications applied: UoM, discount, taxes, ... You might think you solved the issue, but you fixed a very specific use case and probably broked others.

Just try this:
- price_unit: 0.01
- quantity: 3
- discount 80%
-> price_total: 0.01

There is no way that `ANY_2_DECIMAL_NUMBER * 3 = 0.01`. It's the algorythm that is invalid, not the rounding; it should use total values, rather than unit costs.

**Comment by gdgellatly** [comment]
@fpodoo First let me say. as I prepare to leave Odoo and move on to other matters, I genuinely appreciate your interest here and it is something special about odoo that you still get involved in the detail from time to time.

Maybe you are right, but I only showed a little taste of what we need to do for IAS2 compliance with Odoo under Anglosaxon, and that method is quite useful (I think). Giving the ability to provide a price unit that differs from the invoices price unit. Honestly I would love to sit down with your PM's and show the lengths we need to go to for IAS2 compliance under odoo. 

The actual scenario that failed was a replica real world scenario with a po line for say 3.66472 with a 10% rebate at invoice on price and a 0.003 levy per unit qty invoiced later, all of which must be accounted for in determining stock cost under IAS2.

**Comment by gdgellatly** [comment]
> `_get_gross_unit_price` method should be removed, and never used in purchase_stock, or elsewhere. Instead, purchase_stock should be rewritten to use the total value of the layer (prorated on quantities if needed)
> 
> If you don't work with total values, there is no way you can guarantee the equivalence with all the multiplications applied: UoM, discount, taxes, the 1e6 rounding, ... You might think you solved the issue, but you fixed a very specific use case and probably broked others.
> 

btw - I'm pretty sure I broke nothing. I've been deep in the detail of Odoo stock accounting for a little while now and that function is used nowhere near any calculations that matter. It is literally only used in 2 inconsequential places for comparisons.

**Comment by kalungia** [comment]
Hey @gdgellatly, do you get the error when tax is applied or when tax is not applied?

**Comment by gdgellatly** [comment]
Tax should be irrelevant for this issue, there is no point in the 2 functions in question that looks at taxes. But as it happens these tests are without included taxes.

**Comment by Elftortom** [comment]
@gdgellatly as inventory PM I would be happy to discuss the topic with you

**Comment by gdgellatly** [comment]
@Elftortom I will take you up on that, but lets let you get through Odoo XP and me through a horror migration first. When I have time I will try and record a couple of quick videos to initially outline the main gaps than we can set something up.

**Comment by Elftortom** [comment]
Hi GraemeIndeed let’s talk about that after OXP. Best regardsEnvoyé de mon iPhoneLe 2 nov. 2023 à 09:35, Graeme Gellatly ***@***.***> a écrit :﻿
@Elftortom I will take you up on that, but lets let you get through Odoo XP and me through a horror migration first. When I have time I will try and record a couple of quick videos to initially outline the main gaps than we can set something up.

**Comment by gdgellatly** [comment]
@Elftortom Fun, a similar related bug with anglosaxon rounding. I will report separately when I have the time. If we don't do this we get quite large rounding errors (in the dollars)

```
    def _stock_account_prepare_anglo_saxon_out_lines_vals(self):
        """
        Note this method has nothing to do with rebates, but seeing we do all the
        COGS types adjustments here and issue discovered while doing this module
        we fix it here. The issue here is we end up with round(price_unit, 2) * quantity
        instead of round(price_unit * quantity, 2) which is what we want.
        """
        # TODO: Report this upstream
        # TODO: Move to works in Belgium along with price unit fix
        line_vals_list = super()._stock_account_prepare_anglo_saxon_out_lines_vals()
        for line_vals in line_vals_list:
            line_vals["price_subtotal"] = (
                line_vals["price_unit"] * line_vals["quantity"]
            )
            if line_vals["amount_currency"] < 0:
                line_vals["credit"] = abs(line_vals["price_subtotal"])
            else:
                line_vals["debit"] = abs(line_vals["price_subtotal"])
        return line_vals_list
```

**Comment by amoyaux** [comment]
Hello @gdgellatly 

Thanks for reporting, I prepared the PR to fix it.
Sorry for the inconveniences.

Best regards

**Comment by gdgellatly** [comment]
thanks @amoyaux
