### ISSUE TITLE
[11.0/Master] Feature Request: Unsubscribe Smart Button On Sent Newsletters

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#14041]
<H1>Impacted versions:</H1>

11.0/Master

<H1>Steps to reproduce:</H1>

N/A

<H1>Current behavior:</H1>

There is current no way to track the number of un-subscriptions from a mass mailing email that has been sent out.

<H1>Expected behavior:</H1>

It would be very useful to have a smart button that includes numbers of unsubscribers and a list view of all of the people that have unsubscribed by clicking the unsubscribe button on a mass mailing email.

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sorry to ping you, I know you're busy. Do you have any thoughts on this feature request?

I have found it a little cumbersome to move through the mailing list and filter by date to look for unsubscribed dates on lists, and even then if I have multiple mail outs going from the same list I have found there is no easy way of seeing from which campaign un-subscriptions have been triggered.

I believe it would be useful from a reporting standpoint to see where people are unsubscribing from the list and perhaps even give them an option to choose an unsubscription reason a bit like mailchimp.

**Comment by Yenthe666** [comment]
Hi @lukebranch,

I personally think that it would be a nice benefit, both for the user and the person that sends out the e-mail. An unsubscription button is legally required in quite some countries so having statistics of that for the sender is neat. It gives you more insight on your traffic and the behaviour of your (possible) customers so 👍 for me.
@mart-e and @JKE-be pinging you guys for this one too. Perhaps we can add this for V11? 😉

**Comment by pedrobaeza** [comment]
I still don't know v10 unsubscriptions possibilities, but we developed this for v8: https://github.com/OCA/social/tree/8.0/mass_mailing_custom_unsubscribe

**Comment by lukebranch** [comment]
@pedrobaeza ,

Thanks for the link, that looks like exactly what I need. I would assume that a similar mechanism is involved with v9/v10, but that perhaps there are some slight view or model changes involved.

I think it would be really great to have these as core features as well.

**Comment by pedrobaeza** [comment]
For having the unsubscription link, you have to include a footer in your mass mailing, so no real issue, but an unkown change of behavior, and thus I close.
