### ISSUE TITLE
Odoo 9 doesn't work after activating developer mode

### ISSUE THREAD

**Issue by SubodhDahal** [odoo/odoo#14056]
Impacted versions: Version 9.0c (Community Edition)

Steps to reproduce: Go to website admin. Click on the About menu, press the `Activate the developer mode` button.

Current behavior: The site can't be loaded. Chrome displays:

```
This site can’t be reached

sitename.com took too long to respond.
```

Expected behavior: Site should work

**UPDATE:** More information
I'm running Odoo 9.0c on Centos 6 server by executing the `odoo.py` file. After running `odoo.py`, following output is shown in the console. Previously also I was running Odoo the same way, and output of the console would display information about assets being loaded and such when going to `website.com:8069`. Currently it doesn't cause any change in the console output.

    (odoo) ➜  odoo_new git:(9.0) ./odoo.py                   
    Running as user 'root' is a security risk.
    2016-11-02 12:02:06,295 29408 INFO ? openerp: OpenERP version 9.0c
    2016-11-02 12:02:06,295 29408 INFO ? openerp: addons paths: ['/root/.local/share/Odoo/addons/9.0', u'/home/python_projects/odoo_new/openerp/addons', u'/home/python_projects/odoo_new/addons']
    2016-11-02 12:02:06,296 29408 INFO ? openerp: database: default@default:default
    2016-11-02 12:02:06,472 29408 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069

**Comment by lukebranch** [comment]
@SubodhDahal ,

I am only another odoo user like yourself, however i'd suggest posting a short video clip or GIF demonstrating the issue.

I'd suggest using a screencapture program like licecap:

http://www.cockos.com/licecap/

and update your issue with a screencapture demonstrating the issue in a short clip.

**Comment by SubodhDahal** [comment]
I found out that the issue was occurring because all the Odoo files were owned by `root` user, instead of the normal user. I don't know if this was the case before activating the developer options or not. But for me, activating the developer options caused the issue to appear and owning all the files as the normal user made it working again.
