### ISSUE TITLE
[15.0][16.0] Invoices with archived contacts are excluded in searches

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#140528]
Impacted versions:
15.0, 16.0

Steps to reproduce:

1. Create a contact linked to a company and assign it as an [Invoice Address] type
2. Create sale order and assign company above and contact from 1 as the invoice contact
3. Generate invoice, confirm and post then mark as paid
4. Go to Accounting > Customers > Invoices. Search for company name i.e Azure Interior, note that the invoice is visible in the search
5. Go to the contact created in step 1 and archive it
6. Repeat the search in step 4 and note that even when searching for the company name that there is no result found

Current behavior:

- No search results showing for any invoices where the archived contact was assigned
- Searching by invoice number works
- This was confirmed in Odoo V15 and V16 and also on the latest Runbot versions. It was found that in V17 this is NOT the case and it works correctly

Expected behavior:

- Searches should always show all invoices regardless of the status of the contact

Support ticket number submitted via odoo.com/help (optional):

#3577364

**Comment by vava-odoo** [comment]
Hi @chrisandrewmann 
Closing as ticket ended up with a "limitation of previous versions" :man_shrugging:
Cheers
