### ISSUE TITLE
[10.0] Website Mass Mailing Campaigns - Website>Shop>Product page>Edit>Newsletter>Save -not display web form

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#14069]
Impacted versions:10

Steps to reproduce: Website > Shop > Product page > Edit > Newsletter > Save
Website > Blog > Blog page > Edit > Newsletter > Save

Current behavior:
It does not display the Mass Mailing Campaigns web form

Expected behavior:
Mass Mailing Campaigns web form

Video/Screenshot link (optional): https://youtu.be/_8k_gN2umII

**Comment by qsm-odoo** [comment]
Same as https://github.com/odoo/odoo/issues/14299 (the blog bug has been fixed, the other one is still in discussion).
