### ISSUE TITLE
[QUESTION]: Odoo V16 - wkhtmltopdf version

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#140667]
Hello, which version is suitable for Odoo 16? According to the documentation, it should be 0.12.5-1, but in the Docker version 16, it's different.

https://github.com/odoo/odoo/wiki/Wkhtmltopdf
Recommended for Odoo 10 and later.
Wkhtmltopdf 0.12.5-1

For Docker V16:
https://github.com/odoo/docker/blob/master/16.0/Dockerfile#L48 with version 0.12.6.1-3

Which one is valid?

https://github.com/odoo/docker/issues/474

**Comment by gdgellatly** [comment]
Either can work, each has its own issues. Most people choose 12.5. We use 12.5-1 in all our projects incl v16.

Refs.
https://github.com/acsone/kwkhtmltopdf
https://github.com/Tecnativa/doodba/blob/f83cf41e3237c0545e3425e04d12cbe655e4d2f4/16.0.Dockerfile#L6

**Comment by igallart** [comment]
Thank you, @gdgellatly, but beyond whether one has no problems or each one has its own, I believe that it is appropriate for Odoo to officially indicate the correct version or at least the one they recommend. However, using a different version in the official Docker image than the one indicated in the documentation doesn't make sense; it's confusing.

**Comment by gdgellatly** [comment]
Honestly, not a hill to die on. Use what gives you best output in your own situation, while we await a replacement for this dead software.

**Comment by igallart** [comment]
Yes, thank you very much. In any case, it is always a good idea to standardize criteria in the documentation. I will wait a while before closing the issue in case someone from odoo wants to say something, thanks again.

**Comment by d-fence** [comment]
There is no big changes between 0.12.5 and 0.12.6 ut 0.12.6 but we [changed in the Docker](https://github.com/odoo/docker/commit/d98cfdf610867e4d01487913112f12722f3f0513) image because 0.16.6 now supports [ppc64le and 64 bits arm](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.6).

**Comment by igallart** [comment]
Thanks!

**Comment by amh-mw** [comment]
> Honestly, not a hill to die on. Use what gives you best output in your own situation, while we await a replacement for this dead software.

In one of the key notes at OXP 2023, @fpodoo stated that Odoo is going to take over maintenance of wkhtmltopdf, rather than replace it.

**Comment by vava-odoo** [comment]
It is the plan, yes: https://github.com/odoo/wkhtmltopdf

**Comment by amh-mw** [comment]
It looks like https://github.com/odoo/wkhtmltopdf has been archived and https://github.com/odoo/paper-muncher created, so there may be a rip and replace on the horizon.
