### ISSUE TITLE
Manufacture routo can not produce manufacture order correctly ,when using muti-warehose manufacture

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#14061]
Impacted versions: odoo_10.0rc1c.latest 
Steps to reproduce:
1. Creat 3 warehouse named 1WH、2WH、3WH ，setup and select both  two" Manufacture in this Warehouse " "Purchase to resupply this warehouse " check boxes.
2. Create product1、semi-manufactures1、row matrial1,Setup product1 manufacture in warehouse1,semi-manufactures1 manufacture in warehouse 2, product1 transfer to warehouse 3 and delivery to customers
   route
   3、Creat Bom Product1 using semi-manufactures1, setup BOM operation " manufacture in warehose1 and creat semi-manufactures1 BOM using row matrial1, setup BOM operation " manufacture in warehose2, 
   4、Creat sales order, only product1 manufacture order creted both in warehouse 1 and warehouse 2 but have not semi-manufactures1 , and row matrial1 procuement order could not created.

Current behavior:
Muti-warehouse was setup manufacture, but only one route manufacture route with muti-warehouse procuement rule.
Expected behavior:
Muti-warehouse manufacture can using itself manufacture route, and all procuement order craet correctly.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something in your configuration, as MRP relies on procurement rules behavior, and this is something that is working in my end. Closing the issue, but feel free to comment if you still think there's a problem.
