### ISSUE TITLE
HTML Markup in web_view_editor all versions

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#14063]
Impacted versions: all versions

Steps to reproduce: look into html source code of view_web_editor, 

Current behavior: there are multiple elements with same id, thats not valid

Expected behavior: elements should be identified by class insteat by id

https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/xml/view_editor.xml#L27
https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/xml/view_editor.xml#L30
https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/xml/view_editor.xml#L34
https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/xml/view_editor.xml#L38
https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/xml/view_editor.xml#L42

should be changed to:

`<t t-name="view_editor.row">
        <tr  t-att-id="'viewedit-' + rec.id"  t-att-level="rec.level" t-foreach="data" t-as="rec">
            <td width="90%">
                <table class="oe_view_editor_field">
                    <tr>
                        <td width="16px" t-att-style="'background-position: ' + 20*rec.level + 'px; padding-left: ' + 20*rec.level + 'px'">
                            <img t-if="rec.child_id.length" t-att-id="'parentimg-' + rec.id"
                                t-att-src='_s + "/web/static/src/img/collapse.gif"' width="16" height="16" border="0"/>
                        </td>
                        <td style="cursor: pointer;">
                            <a style="text-decoration:none" href="javascript:void(0);">
                                <t t-esc="rec.name"/>
                            </a>
                        </td>
                    </tr>
                </table>
            </td>
            <td width="2%">
                <img t-if="rec.att_list.length"
                    class="side-add" t-att-src='_s + "/web/static/src/img/icons/gtk-add.png"' style="cursor: pointer;"/>
            </td>
            <td width="2%">
                <img  class="side-remove" t-att-src='_s + "/web/static/src/img/icons/gtk-remove.png"' style="cursor: pointer;"/>
            </td>
            <td width="2%">
                <img t-if="rec.att_list.length and !_.include(no_properties, rec.att_list[0])"
                    class="side-edit" t-att-src='_s + "/web/static/src/img/icons/gtk-edit.png"' style="cursor: pointer;"/>
            </td>
            <td width="2%">
                <img t-if="rec.att_list.length"
                    class="side-up" t-att-src='_s + "/web/static/src/img/icons/gtk-go-up.png"' style="cursor: pointer;"/>
            </td>
            <td width="2%">
                <img t-if="rec.att_list.length"
                    class="side-down" t-att-src='_s + "/web/static/src/img/icons/gtk-go-down.png"' style="cursor: pointer;"/>
            </td>
            <t t-if="rec.child_id.length">
                <t t-set="data" t-value="rec.child_id"/>
                <t t-call="view_editor.row"/>
            </t>
        </tr>
    </t>`

and https://github.com/odoo/odoo/blob/9.0/addons/web_view_editor/static/src/js/view_editor.js
as follows:

`edit_view: function(one_object) {
        var self = this;
        this.one_object = one_object;
        this.edit_xml_dialog = new Dialog(this, {
            title: _.str.sprintf(_t("View Editor %d - %s"), self.main_view_id, self.model),
            buttons: [
                {text: _t("Inherited View"), click: function(){
                    var selected_row = self.edit_xml_dialog.$el.find('.ui-selected');
                    if (selected_row.length) {
                        if(selected_row.find('a').text().search("field") != -1){
                            if (confirm(_t("Do you really wants to create an inherited view here?"))) {
                                self.inherited_view(selected_row);
                            }
                        }else{
                            alert(_t("Can't Update View"));
                        }
                    }else{
                        alert(_t("Select an element"));
                    }
                }},
                {text: _t("Preview"), click: function() {
                    var action = {
                        context: self.session.user_context,
                        res_model: self.model,
                        views: [[self.main_view_id, self.main_view_type]],
                        type: 'ir.actions.act_window',
                        target: "new",
                        auto_search: true,
                        flags: {
                            sidebar: false,
                            views_switcher: false,
                            action_buttons: false
                        }
                    };
                    var action_manager = new ActionManager(self);
                    action_manager.do_action(action);
                }},
                {text: _t("Close"), click: function(){
                    self.action_manager.inner_widget.active_view.controller.reload_content();
                    self.edit_xml_dialog.close();
                }}
            ]
        }).open();
        var no_property_att = [];
        _.each(_PROPERTIES, function(val, key) {
            if (! val.length) no_property_att.push(key);
        });
        this.edit_xml_dialog.$el.html(QWeb.render('view_editor', {'data': one_object.main_object, 'no_properties': no_property_att}));
        this.edit_xml_dialog.$el.find("tr[id^='viewedit-']").click(function() {
            self.do_select_row(this.id.split('-')[1]);
        });
        this.edit_xml_dialog.$el.find("img[id^='parentimg-']").click(function() {
            self.do_parent_img_hide_show(this);
        });
        this.edit_xml_dialog.$el.find("img[class^='side-']").click(function() {
            self.on_select_img(this);
        });
    },`

`on_select_img: function(element_img) {
        var self = this;
        var side = $(element_img).closest("tr[id^='viewedit-']");
        this.one_object.clicked_tr_id = parseInt((side.attr('id')).split('-')[1]);
        this.one_object.clicked_tr_level = parseInt(side.attr('level'));
        var img = side.find("img[id='parentimg-" + this.one_object.clicked_tr_id + "']").attr('src');
        var view_id = 0, view_xml_id = 0, view_find = side;
        //for view id finding
        var min_level = this.one_object.clicked_tr_id;
        if (($(side).find('a').text()).search("view_id") != -1) {
            view_id = parseInt(($(view_find).find('a').text()).replace(/[^0-9]+/g, ''));
            view_xml_id = (view_find.attr('id')).split('-')[1];
            this.one_object.clicked_tr_id  += 1;
            this.one_object.clicked_tr_level += 1;
        }else{
            while (1) {
                view_find = view_find.prev();
                if (view_find.length === 0 ||
                    (self.edit_xml_dialog.$el.find(view_find).find('a').text()).search("view_id") !== -1
                        && parseInt(view_find.attr('level')) < min_level ) {
                    view_id = parseInt(($(view_find).find('a').text()).replace(/[^0-9]+/g, ''));
                    view_xml_id = parseInt((view_find.attr('id')).split('-')[1]);
                    break;
                }
                if (view_find.attr('level') < min_level) {
                    min_level = parseInt(view_find.attr('level'));
                }
            }
        }
        this.one_object.clicked_tr_view = [view_id, view_xml_id];
        switch ($(element_img).attr('class')) {
            case "side-add":
                self.do_node_add(side);
                break;
            case "side-remove":
                if (confirm(_t("Do you really want to remove this node?"))) {
                    self.do_save_update_arch("remove_node");
                }
                break;
            case "side-edit":
                self.do_node_edit(side);
                break;
            case "side-up":
                self.do_node_up(side, img);
                break;
            case "side-down":
                self.do_node_down(side, img);
                break;
        }
    },`

`create_clone: function(clone, new_node_obj){
        var self = this;
        clone.find('a').text(new_node_obj.name);
        ($(clone.find('a').parent()).siblings('td')).css( "padding-left", 20 * new_node_obj.level);
        clone.attr("id", "viewedit-" + new_node_obj.id);
        clone.attr("level", new_node_obj.level);
        clone.find("img[id^='parentimg-']").remove();
        clone.bind("click",function(){
            self.do_select_row(this.id.split('-')[1]);
        });
        clone.find("img[class^='side-']").click(function() {
            self.on_select_img(this);
        });
        return clone;
    },`

works as expected.

regards,
Karsten

**Comment by Yenthe666** [comment]
Hi,

This has been fixed in the meanwhile!
https://github.com/odoo/odoo/blob/26d3b77a1de2472a7ce69210dc6aef7f7a615e69/addons/web_view_editor/static/src/xml/view_editor.xml#L27-L42

Regards,
Yenthe
