### ISSUE TITLE
[8.0] account.move.line write(): TypeError write got unexpected keyword argument 'check'

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#14060]
Impacted versions: 8.0

Steps to reproduce:

Possibly can just try to write on `account.move.line` record using `check` keyword argument.
I got this error, when trying to create balanced move.

I got it by using this (ids of course depend on database):

```python
self.env['account.move'].create({'date': '2016-10-29', 'line_id': [(0, 0, {'analytic_account_id': 14, 'name': 'foo', 'account_id': 28, 'debit': 10}), (0, 0, {'credit': 10, 'name': 'bar', 'account_id': 20})], 'period_id': 1, 'name': '/', 'journal_id': 1})
```
 Specifically for me it was caused in this part of code (in account/account.py:1583):

```python
            ...
            if round(abs(amount), prec) < 10 ** (-max(5, prec)):
                # If the move is balanced
                # Add to the list of valid moves
                # (analytic lines will be created later for valid moves)
                valid_moves.append(move)

                # Check whether the move lines are confirmed

                if not line_draft_ids:
                    continue
                # Update the move lines (set them as valid)

                obj_move_line.write(cr, uid, line_draft_ids, {
                    'state': 'valid'
                }, context=context, check=False)

                account = {}
                account2 = {}
             ...
```

If you would try to create not balanced move (when debit/credit do not match), then it will pass.
Current behavior:

`TypeError: write() got an unexpected keyword argument 'check'`

Expected behavior:

Now I did not find `check` keyword argument for `account.move.line` `write` method defined anywhere. So it looks like either someone forgot that there is no such keyword argument and it is using it or forgot to override/extend write with that keyword argument.

Screenshots (it can be reproduced from user interface too):
![screenshot from 2016-10-29 16 36 49](https://cloud.githubusercontent.com/assets/7812986/19829941/779a29ac-9df6-11e6-88e1-aacbfa4a77a6.png)

![screenshot from 2016-10-29 16 37 06](https://cloud.githubusercontent.com/assets/7812986/19829942/79bf3470-9df6-11e6-8923-3f7867b18156.png)

**Comment by stundzia** [comment]
Got the same error, while installing Sale module (on a db with demo data=True)
![screenshot from 2016-10-29 19-16-50](https://cloud.githubusercontent.com/assets/13452494/19831186/88339148-9e0c-11e6-9c38-48f62004e9d3.png)

**Comment by oerp-odoo** [comment]
It was my mistake, I accidentally overridden write method without realizing it had those additional keyword arguments and thats why they stopped existing. 

Disregard this issue.
