### ISSUE TITLE
How to stop odoo from auto creating pack_operation_lot in picking stock for sales order 

### ISSUE THREAD

**Issue by leetingkam** [odoo/odoo#14068]
I am using odoo 9. In the current odoo 9 implementation, odoo automatically pick an inventory lot from the stock in view_pack_operation_lot_form. This does not match the need of our company. We prefer to manually pick all the lot ourselves. I looked at the code but cannot find which part of the code does the auto picking. Also, I worry that if I change something without knowing what the code does, it will break something elsewhere. Can someone give me some pointer of how to do this?

Here's my scenario:

Track lot or serial number = enabled
Define Expiration Date on serial numbers = enabled

---

I have the following in my inventory:

Product A, Lot name=20170202, Qty=30
Product A, Lor name=20170303, Qty=12

---

I have a sales order of Product A, Qty=24.

After entering the SO and clicking confirmed order, I clicked on the Delivery button that brought me to stock.view_picking_form. I clicked on the "split_lot" button that opened the stock.view_pack_operation_lot_form. Under the pack_lot_ids tree, odoo already creates the following:
## Lot                                     Qty

20170202                        18.00
20170303                        6.00

I don't want the auto-created record(s). I want to leave the pack_lot_ids tree empty and have the user added the record himself by clicking "Add an item".

Any idea??? Thanks

**Comment by sle-odoo** [comment]
Hi,
This is not possible in version 9, you have to wipe the pack operation. However, this is possible in version 11 by a setting on the picking type, "use reservation" i think.

Regards
