### ISSUE TITLE
LDAP on odoo 10

### ISSUE THREAD

**Issue by yogurtnaturalny** [odoo/odoo#14064]
Impacted versions:
10
Steps to reproduce:
install ldap plugin on odoo night build  / debian 8 / 
Current behavior:

After sucessful installation and adding LDAP server there is no sign in logs to validate user and user is not authenticated [ i have only information "odoo.addons.base.res.res_users: Login failed for db:"]

Expected behavior:

validate user by ldap server

Video/Screenshot link (optional):

**Comment by odony** [comment]
Sorry, that's not nearly enough information for us to do anything. The LDAP module is used by many people with 10.0 in production, so there must be something wrong with your setup. If you're still interested in solving this, please reopen and add as much info as possible: type of LDAP server, configuration parameters in odoo, logs, etc. A video showing your setup might help too.
Thanks!
