### ISSUE TITLE
[10.0] auth_ldap documentation isn't up-to-date

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#14071]
Currently auth_ldap documentation isn't up-to-date.
For instance, in https://github.com/odoo/odoo/blob/10.0/addons/auth_ldap/README.rst, it's written ```configure the LDAP parameters in the Configuration tab of the Company details``` and configuration is now in the general settings and not in the company parameters.

**Comment by adrienpeiffer** [comment]
OPW 692645

**Comment by mart-e** [comment]
Hello,

Thanks for the notice, we have indeed changed recently the configuration window.
I have updated the view but don't hesitate to tell me (or submit PR) other outdated doc
