### ISSUE TITLE
Odoo 9 filter messages in “Internal note”

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#14075]
I'm add message over "Log an internal note" in module lead.

Example: http://postimg.org/image/i23mdo7rz/

I'm add message "TEST" and choose activity "EMAIL".

Is it possible add custom filter and get lead where is messages test or activity email.

**Comment by bistaray** [comment]
Adding image:

![](https://s11.postimg.org/84slkm06b/test.png)

**Comment by manisho2b** [comment]
do anyone have update on this

**Comment by Yenthe666** [comment]
Nothing for doing this by default no. @manisho2b no update here.

**Comment by pedrobaeza** [comment]
Closing as even the image is not valid anymore and feature request not very clear.
