### ISSUE TITLE
Yodlee returns wrong country code

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#14078]
Impacted versions: V10 (did not check V9)

Steps to reproduce:
1. Go to the accounting settings and set "Bank Interface - Sync your bank feeds automatically"
2. Go to the bank journal and click on "Online Synchronisation"
3. Add a new bank and typ "RAB"
4. Select "Rabobank" with country code "AN"

Current behavior:
5. The for opens and shows the Dutch Rabobank, yeah!!!, but

The country code AN is of the "dutch antilles" and shout be country code "NL"

Expected behavior:
Country code NL

See also image
![bank](https://cloud.githubusercontent.com/assets/7593317/19851370/e2dcf164-9f5d-11e6-86ad-6ffd2cdab740.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e and @qdp-odoo could you guys look into this one?

**Comment by JKE-be** [comment]
Maybe... @csnauwaert, the king of Yodlee ?

**Comment by mart-e** [comment]
These bank data are handled on Yodlee, not Odoo. We only provide the integration with the service but do not manage the list of banks. The only thing we can do is forward the issue to the Yodlee. It is unfortunately the same when the integration with one bank is broken, we have no impact on them,

**Comment by ploegvde** [comment]
Closing is a bit quick and easy. This is a Enterprise module and customer pay for this. At least you can keep it open until you have gotten information that problem is solved and inform us. Also Odoo should do is best to get it solved to keep their customers happy.

**Comment by csnauwaert** [comment]
We have opened a ticket at Yodlee to ask them to change the country code from AN to NL. When they change this, it will be automatically changed in Odoo as well.

Best regards
