### ISSUE TITLE
[9.0] Rule domain filter with or is not properly showing results

### ISSUE THREAD

**Issue by andrealexandrewangliu** [odoo/odoo#14077]
Impacted versions: 9.0

Steps to reproduce:
```
<record id="partner_account_client_supplier_see_restricted_or_without_client" model="ir.rule">
            <field name="name">See only Account Analytic Account where supplier is customer</field>
            <field ref="analytic.model_account_analytic_account" name="model_id"/>        
            <field name="domain_force">['|',['partner_id.customer','=',True],['partner_id','=',False]]</field>   
            <field name="groups" eval="[(4, ref('base.group_hr_user'))]"/>
            <field name="perm_read" eval="1"/>
</record>

```
Current behavior:
Shows only results for ['partner_id.customer','=',True]

Expected behavior:
Show results for ['partner_id.customer','=',True] + ['partner_id','=',False]

PS:
using only ['partner_id','=',False] or only ['partner_id.customer','=',True] works properly, it's just that ['partner_id.customer','=',True] filters out ['partner_id','=',False] even in separate rules...

The intentions is: The manager can only see partners that are customers, however that can cause exceptions (for example the analytic lines) when viewing certain models. But it should also be safe if there is not partner. Unfortunally it doesn't show the partnerless models when the customer restriction is placed.

**Comment by pedrobaeza** [comment]
This is working in my side with latest code. Please re-check and comment back if not working. I'm closing this meanwhile.
