### ISSUE TITLE
[8.0] Analytic Distribution not working for multicompany

### ISSUE THREAD

**Issue by dannyadair** [odoo/odoo#14070]
Impacted versions:
8.0

Steps to reproduce:
1. Install account_analytic_plans and set up multiple companies.
2. Set up an analytic distribution that is specific to a particular company.
3. Use that analytic distribution for a product.
4. Create an invoice and select this product in an invoice line.

Current behavior:
The "Analytic Distribution" field is not populated.

Expected behavior:
The "Analytic Distribution" field is populated.

The issue is
https://github.com/odoo/odoo/blob/8.0/addons/account_analytic_plans/account_analytic_plans.py#L307

where the call to account_get() is lacking the company_id parameter:

`rec = self.pool.get('account.analytic.default').account_get(cr, uid, product, partner_id, uid, time.strftime('%Y-%m-%d'), context=context)
`

needs to say

`rec = self.pool.get('account.analytic.default').account_get(cr, uid, product, partner_id, uid, time.strftime('%Y-%m-%d'), company_id=company_id, context=context)`

**Comment by zbik2607** [comment]
Related to:  #7746

**Comment by Yenthe666** [comment]
Hi @dannyadair,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
