### ISSUE TITLE
[10.0] Can't import jsonschema from a module, import hook does not correctly follow PEP302

### ISSUE THREAD

**Issue by Angelfentanez** [odoo/odoo#14087]
Impacted versions:
10.0

Steps to reproduce:  

1. Install jsonschema:  
    pip install jsonschema

2. Import jsonschema in any module:  
    import jsonschema
3. Update module list  

Current behavior:
An error occurs when odoo tries to load the module:  
![image](https://cloud.githubusercontent.com/assets/12100691/19871987/29eaaeba-9f7d-11e6-9274-c3db0c614f88.png)

Expected behavior:  
The update finishes without errors

I noticed that the problem seems to be because the [import hook](https://github.com/odoo/odoo/blob/10.0/odoo/modules/module.py#L42) in odoo 10.0 does not completely follow the [PEP302](https://www.python.org/dev/peps/pep-0302/#specification-part-1-the-importer-protocol) by not having path = False, because jsonschema uses pkgutil.find_module and only passes one parameter it crashes.

**Comment by mart-e** [comment]
Hello,

I am not familiar with jsonschema but shouldn't it be fixed there?

**Comment by Angelfentanez** [comment]
Hi, 

The problem is that jsonschema uses pkgutil.find_loader which iterates over all the package loaders and passes only one parameter, it does this because it expects that all the loaders follow the PEP302, when it tries to call odoo's find_module method it crashes because that method expects two parameters, this happened to me with jsonschema but might be a problem with any library that uses pkgutil.find_loader.
I found out that this was an issue in other versions of odoo as well, it was also reported here: https://github.com/odoo/odoo/issues/10670

and the error was explained in this comment:  
https://github.com/odoo/odoo/issues/10670#issuecomment-176660556
