### ISSUE TITLE
[10.0] Byproduct Producted Qty is not Updated when MO has Routing

### ISSUE THREAD

**Issue by tenxor105** [odoo/odoo#14089]
Impacted versions: 10

Steps to reproduce: Create a BOM with byproduct and Routing with at least one operation. Create MO with such, plan MO, process workorders.

Current behavior: Only the finished good produced qty gets updated. The byproduct quantities are 0.

Expected behavior: Byproduct produced qty should be equal to qty to produce

Video/Screenshot link (optional):

**Comment by amoyaux** [comment]
Duplicate of issue https://github.com/odoo/odoo/issues/14126
