### ISSUE TITLE
patch to mail/controllers/main.py for single white pixel avatar defaults

### ISSUE THREAD

**Issue by royaladmin** [odoo/odoo#14095]
Impacted versions:
9.0
Steps to reproduce:
view comments on a blog by users who are avatar free
Current behavior:
browser supplies its own placeholders 
Expected behavior:
single white pixels
Video/Screenshot link (optional):

I found a way to make the pixels serve, and since sharing is caring:

        #13.0.3.16.11-t11 jrook so the single white pixel default serves correctly...
        # response.status = str(status)
        response.status = str(status) + ' OK'

I started by back-porting the entire def avatar from the master branch to my 9.0
to pick up the other fixes for [[()]] and default status at the top and for _content in the middle.

I still had to add the + ' OK' to see the white pixels.

Have fun.

**Comment by pedrobaeza** [comment]
See https://github.com/odoo/odoo/pull/13952 that it's even a better solution (applied to a similar thing)

**Comment by Yenthe666** [comment]
Hi there,

Closing as there is a PR for this (and it has feedback from Odoo employees)
