### ISSUE TITLE
[7.0] - procurement make_to_stock  works each 2 times by product

### ISSUE THREAD

**Issue by gzampeze** [odoo/odoo#1409]
Version 7.0-20140727-231133
module install : sale  mrp mrp_jit

I create product Sculpture (make_to_stock, Manufacture) for MO 
this product have 1 components Bois (make_to_stock, buy)  in bill of materials
no Reordering Rules set
no stock at start

on 1er sale order :  1 scheduler + orderpoint create MO 
                                   2 scheduler + orderpoint create PO 
on 2 sale order : scheduler + orderpoint do nothing no MO create 
on 3 sale order : scheduler(s) + orderpoint(s) create PO and MO of second

The problem seem to be with stock_move and virtual_available of product sculpture
(see 0 or will be -1)
the condition line 170 in create_automatic_op procurement/scheduler.py

In data base lines to calcul the  virtual_available of product sculpture seem no good and
seem equals to 0 due to (2,3) :
id;orgin;name;location_id;location_dst_id;product_qty
6;"SO002";"Sculpture";12;9;1.000
3;"";"MO/00001";7;12;1.000
2;"";"OP automatique : Sculpture";6;12;1.000
1;"SO001";"Sculpture";12;9;1.000

**Comment by Yenthe666** [comment]
Hi @gzampeze,

Thank you for your report and my apoligies for the late reply.
Odoo 7 is no longer supported by Odoo itself, as the support goes back three version (so at this point there is support for V8, V9 and V10).
I'm closing this issue as we no longer handle them for old Odoo versions. If you can still reproduce this on V8, V9 or V10 feel free to create a new issue though! We'll look into it as soon as possible then.

Regards,
Yenthe
