### ISSUE TITLE
[10.0c] Cannot fetch the Product price based on Pricelists for a specific Partner

### ISSUE THREAD

**Issue by matheo** [odoo/odoo#14090]
Trying to build a custom action to build an invoice for a specific Product and Partner, it seems that it's impossible to get the price for a Partner without a user setted up.

Looking on the source code:
https://github.com/odoo/odoo/blob/10.0/addons/website_sale/models/product.py#L190
it seems that get the current user' parnet_id, and also its pricelist based on the current website too, but then it's impossible to pass any partner/pricelist through context to resolve the product price specified for any partner.

This missing feature seems related to the Invoice create form, where the partner selected doesn't affect the price of the selected products on the invoice lines. The onchange only fetches the current user price I guess...

**Comment by yostashiro** [comment]
@matheo I think the function works fine for the case you report although I also had to investigate a bit to understand how it was designed.

You may want to check the following points:
* If the pricelist is available for your website (i.e. website is selected in "Allow to use on" in pricelist setting)
* If your last SO from online shop is not in draft state - if you have one in draft state, the pricelist of that SO is applied no matter what the current pricelist of the part is.

See https://github.com/odoo/odoo/blob/53b5c48bc620561fd78bcd8e6c8d740daed91906/addons/website_sale/models/sale_order.py#L273-L310.

**Comment by Yenthe666** [comment]
Thanks for answering this @yostashiro!
I believe you're correct with your answer and that this is intended behaviour.
