### ISSUE TITLE
[10.0] Unable to close a POS session while Cash Control is enabled

### ISSUE THREAD

**Issue by smartupdo** [odoo/odoo#14098]
Impacted versions:
Odoo 10.0

Steps to reproduce:
- Install Odoo 10.0, start a new database
- Install POS module, enable Cash Control
- Open a POS session and attempt to close it (Validate Closing and Post Entries)

Current behavior:
- Brief Loading is shown and the screen remains on the session summary window with no change, warning or error log.

Expected behavior:
- Session is processed and closed.

**Comment by Yenthe666** [comment]
Hi @smartupdo,

Thank you for your report!
This is indeed a bug and you're unable to validate closing and post entries at the moment.
@jorenvo might be one for you.

Regards,
Yenthe

**Comment by jorenvo** [comment]
@simongoffin is already on it: https://github.com/odoo/odoo/pull/14032

**Comment by smartupdo** [comment]
I can confirm that pull #14032 fixes this issue.
