### ISSUE TITLE
Accounting - l10n_be - Statutory P&L / Compte de résultats / Resultatenrekening

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#14108]
Impacted versions: 9 and 10

Steps to reproduce: install accounting with l10n_be and generate entries on 69 and/or 79 accounts

Current behavior: the values in these accounts are not reported because the current report stops at section 4 of the official report.

Expected behavior: Complete the report so it would include Vol/section 4.

Video/Screenshot link (optional):
![2016-11-02 15_47_13-jaarrekening](https://cloud.githubusercontent.com/assets/11032154/19934446/ef181520-a116-11e6-9174-c677355f4244.png)

**Comment by jdegoy** [comment]
Refer to Support Ticket 692885.

**Comment by pedrobaeza** [comment]
Is this still happening?
