### ISSUE TITLE
Web Site language change always redirect from https to http

### ISSUE THREAD

**Issue by KTKwok** [odoo/odoo#14101]
Impacted versions: V9

When user access web site via https://www.example.com/page/faq

Odoo will redirect to http://www.example.com/zh_TW/page/faq

As we set apache server to redirect http to https, it then redirect again to https://www.example.com/zh_TW/page/faq

We already set the web.base.url to https://www.example.com but still it redirect to http

**Comment by yostashiro** [comment]
It is also the case with 10.0.

**Comment by Yenthe666** [comment]
@JKE-be can I ask you for feedback on this one please?

**Comment by JKE-be** [comment]
I can't reproduce with Nginx, so it is probably a misconfiguration in Apache.
you can try to print more info in the dispatch function from website/ir_http  and url_for to have more information.

Waiting for your feedback

**Comment by yostashiro** [comment]
@JKE-be While I have yet to follow your advice, my customer on Enterprise sees it as a security issue pertaining to Odoo itself rather than something to be handle on the web server side.

I detailed the issue in ticket 757234 and here is an excerpt:
> There are two issues coming from this behavior: 
> 1) It seems that the redirection from http to https is not possible using Azure's Application Gateway with SSL offloading settings (according to the report by the user) 
> 2) Although enforcing redirection from http to https using Apache/Nginx makes it appear OK, it could be a security threat when Odoo redirect the connection to http even for a moment as the cookie content could be exposed with no encryption (according to a security expert). 

2) is the security issue I mention above.  I'm personally not very sure if it really is a threat (I just don't have enough knowledge around this topic to judge).

1) is some practical issue that the customer is facing in their implementation.  They opt not to use Nginx/Apache in favor of Azure Application Gateway for now.

Would be good to get your opinions on both points.

**Comment by JKE-be** [comment]
Hi Yostashiro,

Are you sure that you add header X-Forwarded-Proto in your apache config... as specified in the documentation: https://www.odoo.com/documentation/10.0/setup/deploy.html.

Since version 0.8 of Werkzeug, it uses it to transform the relative redirect to the absolute.
https://github.com/pallets/werkzeug/blob/master/CHANGES#L706

**Comment by yostashiro** [comment]
@JKE-be Yes, we do have X-Forwarded-Proto in Apache config in normal cases when we use Apache, but that is not the point of this issue here.

The point is that there is allegation from a security expert that Odoo, WITHOUT relying on Nginx/Apache,  should not be routing what is already https to http when links are clicked on website (again, I'm not sure about the validity of the claim myself).  Please read my above comment again.

**Comment by yostashiro** [comment]
@JKE-be In fact, in the environment I reproduced the issue had X-Forwarded-Proto in Apache config, but just had the part that redirects http to https deleted.

**Comment by JKE-be** [comment]
If you don't use a nginx/apache as proxy, werkzeug will respect the scheme

**Comment by yostashiro** [comment]
@JKE-be Can you please elaborate what exactly you mean by "werkzeug will respect the scheme"?

The issue still persists when Apache config has `RequestHeader set X-Forwarded-Proto "https"`.

**Comment by JKE-be** [comment]
respect the scheme = will be redirected to https directly and not in http.

**Comment by yostashiro** [comment]
Thanks, but then, it sounds like what you explain contradicts with the actual behavior of Odoo.  So should I expect a follow-up on the Enterprise ticket I created?

**Comment by odony** [comment]
Here is a relevant part of my answer to @yostashiro's ticket, for the record:

> Odoo never uses redirects with a specific protocol. Instead, we always redirect to relative URLs, and we let the various network components do the necessary translation.
> The first such component is werkzeug, the library that implements the WSGI layer for Odoo.
> This library will translate relative URLs into absolute URLs, so an Odoo redirect to /en_US/page/foo will become https://www.example.com/en_US/page/foo
> To guess the proper "host" and "protocol", werkzeug uses the information from the original web request. This information may be altered/incorrect when proxies/SSL offloading are in use, because the final request entering Odoo is not the original request coming from the browser. In that case the system has no way to determine the correct protocol, unless the "proxy" setup is 100% correct. This means:
>    - Odoo must be started with --proxy mode enabled  (this activates the werkzeug proxy mode, which is necessary)
>    - The proxies/SSL offloader must set appropriate X-Forwarded-* headers, so that the werkzeug proxy mode can correctly determine the original URL:
>          - X-Forwarded-Host
>          - X-Forwarded-Proto
>          - X-Forwarded-For
>      The Odoo documentation provides a sample nginx config for this: https://www.odoo.com/documentation/10.0/setup/deploy.html#id7
>    - Other proxies between the browser and Odoo must not alter the redirected URLs!
> 
> Note: contrary to common beliefs, the 'web.base.url' config has absolutely nothing to do with any of this, and is never used for redirects (it's used mainly for links inside emails)
> 
> We understand that setting this up properly can be complicated and requires technical skills, but it is inevitable because Odoo is only the last part of the request processing chain, and the previous components do their own alterations and rewriting of the requests. To limit the complexity we strongly recommend keeping simple setups with only nginx + Odoo, and our sample configuration (linked above).
> 
> If you think you have properly setup everything as explained above, and are still experiencing trouble with redirects, you will need to verify and prove your setup by using a network packet analyzer (e.g. wireshark/tcpdump) to view the HTTP packets really entering and leaving Odoo. Every time we've asked this to a customer it turned out there was indeed a problem in their config/setup!

**Comment by yostashiro** [comment]
@odony Thanks a lot for your detailed explanation.   I stand corrected - I indeed forgot to set `proxy_mode = True` in my test environment.  Apologies for the confusion, and thanks again!

**Comment by senamo** [comment]
@odony  hi facing the same issue have gone through several forums trying to find a solution;
1. My proxy_mode = True
I am using odoo 13 it keeps reverting to unecrypted on language  change. I am only using nginx and odoo for a server hosted on aws. I have verified that my nginx config is similar to the one on the site

**Comment by rrebollo** [comment]
> @odony  hi facing the same issue have gone through several forums trying to find a solution;
> 1. My proxy_mode = True
> I am using odoo 13 it keeps reverting to unecrypted on language  change. I am only using nginx and odoo for a server hosted on aws. I have verified that my nginx config is similar to the one on the site

Same here, although am using traefik2
