### ISSUE TITLE
[10.0] Enterprise - Graphene theme wont install

### ISSUE THREAD

**Issue by thegunshow** [odoo/odoo#14111]
Impacted versions: 10

Steps to reproduce: Dev mode>Apps>App Store>Graphene

Current behavior: 
![image](https://cloud.githubusercontent.com/assets/16087167/19944067/d2ecaa2e-a142-11e6-9787-a56cdcff4871.png)

The theme "graphene theme blog" appears to be unavailable. Please try again later

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be could somebody of you guys look at it? I don't have the Graphene theme and it should be bought 🙈

**Comment by JKE-be** [comment]
@qsm-odoo the master of Theme ... An idea about the availability of this module ?

**Comment by qsm-odoo** [comment]
The module is there https://www.odoo.com/apps/themes/10.0/theme_graphene_blog/ so I am not sure where the error comes from... maybe ask the master of Odoo apps @dmo-odoo, an idea ?

**Comment by dmo-odoo** [comment]
@qsm-odoo Is theme_graphene_blog a dependency of theme_graphene ? Seems like there is something amiss. If it is not a dependency, I don't understand why this message would be shown. If it is, then it should be zipped with graphene when you download it from Odoo Apps.

@thegunshow Are you are encountering this issue when migrating from 9.0 to 10.0 ? If yes: @qsm-odoo

**Comment by qsm-odoo** [comment]
@dmo-odoo That's what I do not understand, theme_graphene is a dependency of theme_graphene_blog, not the other way around. Upgrading theme_graphene should not even know there is a theme_graphene_blog module. theme_graphene_blog is supposed to autoinstall with theme_graphene and website_blog but if the module is not present in the filesystem, I don't see why it is trying to find it. In any case, maybe we should update theme_graphene description to inform of this module existence.

**Comment by dmo-odoo** [comment]
@qsm-odoo Yes, it needs to be stated in the module description, just like the ecommerce plugins.

**Comment by thegunshow** [comment]
Hi

Just reinstalled Odoo and it worked...

Thanks
