### ISSUE TITLE
[17.0]purchase_stock bug: this._super is undefined

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#141112]
Impacted versions:
Odoo17.0
Steps to reproduce:

Current behavior:
purchase_stock js display an error: Can't load service 'tour_service' because: TypeError: can't access property "apply", this._super is undefined
Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @Bonainifo 
Thanks for your report. 
It seems to originate from the changes in this PR https://github.com/odoo/odoo/pull/137116.
@mcm-odoo Could you help here?
Thanks
