### ISSUE TITLE
[10.0]strange translation strings

### ISSUE THREAD

**Issue by nonofpy** [odoo/odoo#14112]
Impacted versions:10

Steps to reproduce: After switching from English to Japanese in language settings, strange translation strings shown in vendor bills

Current behavior:

"Account" is shown strange strings in the line view.

![image](https://cloud.githubusercontent.com/assets/20656150/19957743/552ccb18-a1d4-11e6-9088-7342258bb1d0.png)

Expected behavior:
It should be shown "Account" in Japanese -アカウント

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello @nonofpy 

Could you submit the fix in transifex Odoo Project ? 

As you can imagine, We don't speak Japanese , so the translation is done by the community/partner/...
That arrive that some translation is out of context.

Thank you

**Comment by yostashiro** [comment]
@JKE-be currently there is no Japanese for 10.0 in Transifex.  When will you have it ready?

**Comment by JKE-be** [comment]
@mart-e ...

**Comment by mart-e** [comment]
@yostashiro why haven't you made a request on Transifex to add it? I can not guess which language people want if nobody asks for it...

![selection_044](https://cloud.githubusercontent.com/assets/564822/19967086/fe958a38-a1ce-11e6-90d3-aedd8cb4132c.png)

now I have added it

**Comment by yostashiro** [comment]
@mart-e 

> now I have added it

I missed this comment and made a redundant request.  Please ignore that.

I don't think the communication was done in such a clear way for people to understand that you need to make a request for a language to be added, which is different to how it was for 9.0.  Anyway, I know it now.  Thanks for the quick action.

**Comment by mart-e** [comment]
> which is different to how it was for 9.0

I don't think so :confused: It has always been like that since we are on Transifex as I recall. We are thinking about removing unactive languages after some time but we accept new one if people ask us to add it.

**Comment by yostashiro** [comment]
@mart-e OK, maybe that was misunderstanding on my side then.  Thanks for the clarification.
