### ISSUE TITLE
MRP BYPRODUCTS qty is not updated on manufacturing via workcenters

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#14126]
Impacted versions:10.0

Steps to reproduce:
Create 3 Products A,B,C
Create a BOM to produce 1Qty of A with 1Qty of B as raw material and 1Qty C as byproduct
Create a routing with one or more work-centers

Current behavior: 1Qty A is produced by consuming 1Qty of B, 1Qty of C is not getting updated to stock.

Expected behavior: 1Qty of A and 1Qty of C should be updated to stock by consuming 1Qty of B.

Video/Screenshot link (optional):

[mrp_bug_with_buyproduct_1.zip](https://github.com/odoo/odoo/files/569032/mrp_bug_with_buyproduct_1.zip)

**Comment by ki1022** [comment]
Having the same problem, will not work no matter how I have it configured.

**Comment by hardidarjoto** [comment]
Yes, I have the same problem.
If the BoM / MO not using routing, the behavior is OK. Problem occurs when using routing.

**Comment by hardidarjoto** [comment]
After discussion with ID community, the solution is to fill manually qty Produced (as stated in BOM) in tab Finished Product in MO, before clik "Mark Done".

But still don't know, whether this is the expected behavior, or just work around.

**Comment by Yenthe666** [comment]
@jco-odoo could you say if this is expected behavior?

**Comment by jco-odoo** [comment]
Of course, you can still change it on the MO, but the goal was at least to set it after the last WO. (we were even thinking about doing it WO specific)

**Comment by amoyaux** [comment]
Hello guys, it has been fixed last week by commit d7fdb636b81a99519d1e186edaf42d36ecee3b5f
