### ISSUE TITLE
Limitd Vehicle Type in fleet vehicle model

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#141381]
Impacted versions:
v16, v17
Steps to reproduce:
There is only Car and Bike in fleet model.

Current behavior:
There is only Car and Bike in fleet model.

Expected behavior:
Fleet consist of all types of vehicles and either all types of vehicles should include or need option to add manually

Video/Screenshot link (optional):
![Vehicle Model](https://github.com/odoo/odoo/assets/45730318/434e077e-a142-425c-8854-23f8046cc74a)

Support ticket number submitted via odoo.com/help (optional):
3586036

**Comment by vava-odoo** [comment]
Hi @jabirmisnedtech 
Thanks for your message. But this is not an issue, more a feedback to add more options (will do it internally).
In the meantime, you can easily extend the selection field `vehicle_type` from `fleet.vehicle.model` in a custom module.
Cheers!
