### ISSUE TITLE
Click one time payment method in pos screen

### ISSUE THREAD

**Issue by duongduong** [odoo/odoo#14133]
#How do click button method payment (Cash or anything) that only show one payment line? this image description my bug. help me. 

image description error
![capture](https://cloud.githubusercontent.com/assets/13607737/19974146/0993069a-a21a-11e6-905f-ef537e27d447.PNG)

**Comment by ankur1367** [comment]
Hi,
After validating you can see the check out option with Payment cards(if you have setup already).
Regards

**Comment by duongduong** [comment]
Hi,
I resolved my bug. I execute check variable count after click payment method and it worked.
Thanks reply.
