### ISSUE TITLE
[9.0e] Odoo won't send or receive e-mails

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#14135]
**Impacted versions:** 
9.0 Enterprise

**Steps to reproduce:** 
Configure any e-mail server (Gmail, Outlook, Office 365, SendGrid). Odoo still doesn't have a license, it's on trial period (don't know if this may be a new constraint for trial).

User's e-mail is set, contact's e-mail is set. All third-party e-mail apps were uninstalled. Outgoing and Incoming e-mail servers get validated.

**Current behavior:** 
E-mail is not sent or fetched from server. Shows failure reason: "_Error without exception. Probably due do sending an email without computed recipients._"

**Expected behavior:** 
E-mails be sent.

Video/Screenshot link (optional):

**Comment by ankur1367** [comment]
Hi Edsersolis,
AFAIK the mail server works fine. Let me know the STMP settings you are using.
Regards

**Comment by edsersolis** [comment]
Ok I noticed that on the log it says:
WARNING dbname openerp.addons.base.ir.ir_mail_server: Email sending not enabled

I have never seen this error before. Odoo has always been able to send e-mails as soon as you provide a SMTP server.

Any ideas?

**Comment by ankur1367** [comment]
@edsersolis 
Did you set your STMP server in settings? Please let me know if issue still persist.
Regards

**Comment by edsersolis** [comment]
@ankur1367 No, the issue was with a module that was getting auto-installed in our instances by some reason. It is fixed now. Thanks!

**Comment by germanbarrientosmora** [comment]
Hey edersolis which one was that module being auto-installed?

**Comment by edsersolis** [comment]
@germanbarrientosmora hello German. We have set our scripts to download some repositories from some of the big Odoo developers, and we had included the one from Smile, and if I don't bad recall it was called smile_base which was forcing French language by default and also blocking all the e-mails.

**Comment by Yajo** [comment]
This should be closed then.

**Comment by kortibu** [comment]
Hello, I've the same error to send end receive mail on Odoo 10. The SMTP runs well. Please help me. Tks.
