### ISSUE TITLE
Odoo 8 : l10n_be_coda - Coda import - missing items

### ISSUE THREAD

**Issue by yboujraf** [odoo/odoo#14139]
Impacted versions: 8.0.2.1

Steps to reproduce: import coda file

Current behavior: some items are not imported

Expected behavior: all items in the bank statement need to be imported

Video/Screenshot link (optional):

I have an issue with coda import from one specific partner.
When Imported the coda file we have a red color and when opening the coda file a part of the entries are available

![image](https://cloud.githubusercontent.com/assets/6151258/19982238/93a9f420-a205-11e6-8ef0-854e6e8721af.png)

All entries from ACERTA aren’t imported.

![image](https://cloud.githubusercontent.com/assets/6151258/19982264/b0ff739c-a205-11e6-982f-572bdd5c8749.png)

coda file

[BE54001591120197_EUR_Full_20161006.zip](https://github.com/odoo/odoo/files/569962/BE54001591120197_EUR_Full_20161006.zip)

Thanks in advance 
@yboujraf

FYI : @qdp-odoo

**Comment by Yenthe666** [comment]
@qdp-odoo any clue?

**Comment by yboujraf** [comment]
Dear,

Again,

We imported the new coda statement and again a part of the items are missing.

Anybody could help us for that?

Best Regards,
Youssef
[BE54001591120197_EUR_Full_20161107.zip](https://github.com/odoo/odoo/files/584106/BE54001591120197_EUR_Full_20161107.zip)

**Comment by Yenthe666** [comment]
Hi @yboujraf,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
