### ISSUE TITLE
Website Submenus in OpenERP

### ISSUE THREAD

**Issue by chandrakumarm** [odoo/odoo#1414]
While designing website using OpenERP Version8 and when working on the menus we have created the following format

Menu-> Submenu1-> Submenu2.

While Submenu1 works fine, Submenu2 is not working as expected. Kindly let us know how the expected results can be achieved.

**Comment by Yenthe666** [comment]
There is indeed only one sub-level at the moment. This is desired behaviour (in V8) 😉
