### ISSUE TITLE
[10][9] free shipping for product

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#14157]
Impacted versions:
10, 9, 8

Current behavior:
Rule Based or Fixed 

Expected behavior:
Product specific free shipping. not allow to be added in cart with another item has shipping cost or calculate shipping cost for that item.

**Comment by pedrobaeza** [comment]
Can you add all the detailed steps to reproduce the problem?

**Comment by ddfs** [comment]
@pedrobaeza not sure if there is any available steps to produce this problem. this is more like a missing feature.

**Comment by pedrobaeza** [comment]
But you can already have free delivery costs with the module website_sale_delivery... Please ask on the forums how to do it. Closing this.
