### ISSUE TITLE
Complete product list not displayed in Sales Order Line

### ISSUE THREAD

**Issue by chandrakumarm** [odoo/odoo#1415]
Create a Sales order in Version 8 when selecting a product in the Sales order line click on search more option. We had added around 4000 products but only 160 products were listed. Though no filters are applied, until the filter is cleared the 4000 products are not listed.

**Comment by Yenthe666** [comment]
Hi @chandrakumarm,

Thank you for your report.
This is however a default implementation in the framework of Odoo, made for consistency and performance. There is no intention to change this behaviour and it is wanted. The reason behind this is that if you need something you'll search at the top, which will bring up the results you want.
For more information see https://github.com/odoo/odoo/issues/17490

Regards,
Yenthe

**Comment by chandrakumarm** [comment]
Thanks @Yenthe666
