### ISSUE TITLE
State is getting changed to "Wyoming" on Billing Information Page.

### ISSUE THREAD

**Issue by bista-amitd** [odoo/odoo#14150]
Impacted versions: 9.0 + Enterprise + Website

Steps to reproduce:
-> login on runbot : http://178510-9-0-34359a.runbot9.odoo.com/
-> Set full address on admin user with state "Florida"
-> Now add some product on cart 
-> And click on "Process Checkout"

Current behavior:
State / Province getting changed to "Wyoming"

Expected behavior:
It should be "Florida"

Video/Screenshot link (optional):

[out-13.ogv.tar.gz](https://github.com/odoo/odoo/files/571500/out-13.ogv.tar.gz)

**Comment by bistaray** [comment]
I can replicate this on runbot for v9 Enterprise - http://178554-9-0-b7bd57.runbot5.odoo.com/

**Comment by bistaray** [comment]
We have logged this with Odoo Support - ticket #693127

**Comment by bista-amitd** [comment]
adding @bistakedar

**Comment by simongoffin** [comment]
closed with 57f320aa99f57fd560e2a5f242dd9f5824e76435

**Comment by bista-amitd** [comment]
Above commit says it's fixed for v10.
Can you please improve this on v9 ?

**Comment by bista-amitd** [comment]
Still reproducible on runbot v9 instance.

**Comment by simongoffin** [comment]
closed with 164b8ed01a96c860cf758514abfd50ba349e990c
