### ISSUE TITLE
POS missing invoices

### ISSUE THREAD

**Issue by LordRatte** [odoo/odoo#14151]
Impacted versions:
Version 8.0-467968b

Steps to reproduce:
Generate a sale in a point of sale session and click validate.

Current behavior:
The orders occasionally go missing. They are sent to the server because they aren't in the local storage and the counter at the top right is green but there is no trace of them in Odoo. They are also not in the session summary.

Expected behavior:
The expected behaviour is that they get generated in the database or throw an error as to why it can't.

**Comment by Yenthe666** [comment]
Hi @LordRatte ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
