### ISSUE TITLE
ir_attachment URL index choice can cause high load

### ISSUE THREAD

**Issue by theangryangel** [odoo/odoo#141633]
When database caches are invalidated the asset bundles are regenerated. On a large-ish install the ir_attachment url index choice can result in relatively high load.

Adding a Trigram index reduces the query cost significantly. I reached for a tgrm index this morning purely because I had an issue to resolve on a production installation. 

I have not yet evaluated if other indexes perform better/differently.

```
create index concurrently ir_attachment_url_trigram_karl_FIXME on ir_attachment using gin(url gin_trgm_ops);
```

Before:

```
devel=# explain select max(id) from ir_attachment where create_uid = 1 AND url like '/web/assets/%-a62d2f9%';
                                                     QUERY PLAN
--------------------------------------------------------------------------------------------------------------------
 Result  (cost=149339.70..149339.71 rows=1 width=4)
   InitPlan 1 (returns $0)
     ->  Limit  (cost=0.43..149339.70 rows=1 width=4)
           ->  Index Scan Backward using ir_attachment_pkey on ir_attachment  (cost=0.43..448018.24 rows=3 width=4)
                 Index Cond: (id IS NOT NULL)
                 Filter: (((url)::text ~~ '/web/assets/%-a62d2f9%'::text) AND (create_uid = 1))
(6 rows)
```

After:

```
devel=# explain select max(id) from ir_attachment where create_uid = 1 AND url like '/web/assets/%-a62d2f9%';
                                                QUERY PLAN
----------------------------------------------------------------------------------------------------------
 Aggregate  (cost=70.48..70.49 rows=1 width=4)
   ->  Bitmap Heap Scan on ir_attachment  (cost=67.12..70.47 rows=3 width=4)
         Recheck Cond: ((url)::text ~~ '/web/assets/%-a62d2f9%'::text)
         Filter: (create_uid = 1)
         ->  Bitmap Index Scan on ir_attachment_url_trigram_karl_fixme  (cost=0.00..67.12 rows=3 width=0)
               Index Cond: ((url)::text ~~ '/web/assets/%-a62d2f9%'::text)
(6 rows)
```

Impacted versions:

At least 15.0

Steps to reproduce:

1. Have a large-ish number of attachments (~8million)
2. Have website enabled
3. Invalidate caches
4. Observe PostgreSQL running high-cost query as it regenerates asset bundles

Current behavior:

High CPU load.

Expected behavior:

Lower CPU upload.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
@theangryangel There should be zero need for a trigram index as a like query which is effectively a startswith should be more performant with a standard btree.

Something like `CREATE index test ON ir_attachment (url) WHERE url is NOT NULL;`

I actually tried to reproduce on a much larger database and couldn't until I found that index is actually present by default in v16.

**Comment by theangryangel** [comment]
I’ve not had time to revisit this but I’m 99% sure that index is present on the db already, which is why I was surprised. 

I’ll dedicate some time over the weekend to take a look (curious now)

**Comment by theangryangel** [comment]
The btree index is present on the DB in question. A quick drop, anaylze and explain and without the tgrm index its a very high cost still. 

Out of interest @gdgellatly how many records in ir_attachment have create_uid = 1 on your test DB? We seem to have quite a large number (relates to EDI orders being picked up and consumed as OdooBot). Is yours perhaps more reasonable, therefore there’s a larger amount of pre-filtering happening?

**Comment by theangryangel** [comment]
Proving that I cannot just let things go, it’s a collation issue it seems. In short PostgreSQL won’t use the btree 

For ref if anyone stumbles across a similar issue in future here’s some previous discussion- 

https://github.com/odoo/odoo/pull/25196#issuecomment-396683972

https://github.com/camptocamp/docker-odoo-project/issues/100

**Comment by gdgellatly** [comment]
Ah, of course, I always use `POSTGRES_INITDB_ARGS: "--data-checksums --locale=C --encoding=UTF8"` for that very reason. For me it makes no sense in English world to do otherwise.

**Comment by gdgellatly** [comment]
> The btree index is present on the DB in question. A quick drop, anaylze and explain and without the tgrm index its a very high cost still.
> 
> Out of interest @gdgellatly how many records in ir_attachment have create_uid = 1 on your test DB? We seem to have quite a large number (relates to historical EDI orders being picked up and consumed as OdooBot). Is yours perhaps more reasonable, therefore there’s a larger amount of pre-filtering happening?

As it happens this database has some 20 million attachments. Nearly all invoices arrive via pdf from supplier and unfortunately due to the way many people set their email signatures, a single email can have 4 or 5 attachments. Of those 20 million 10 million are uid 1.
