### ISSUE TITLE
[v10] Wrong default taxes in Dutch new COA

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#14166]
Impacted versions: V10

The default taxes of the new v10 Dutch COA are wrong. See image attached.

The sale tax is set on a servive tax and that is not the default situation
The purchase tax is set as an including tax and that is not the default setting

![wrong-default-taxes](https://cloud.githubusercontent.com/assets/7593317/20037800/127357aa-a428-11e6-98a7-cbe3abcfe36e.png)

**Comment by ploegvde** [comment]
@astirpe Andrea can you also have a look?

**Comment by gustavovalverde** [comment]
Is that default even configurable in a CoA installation? I tried that on my country install and I was not able to do it.

**Comment by ploegvde** [comment]
Not on installation. The defults are set in the module code. You can change them in the accounting settings

**Comment by gustavovalverde** [comment]
I'll be following this issue, as I've not seen a localization in Odoo core that sets the default taxes.

**Comment by wtaferner** [comment]
@ploegvde @gustavovalverde 
As far as I know the default taxes are taken from the CoA and they are taken from the first tax (by sequence) of a type (sale, purchase), so the only way afaik to get it right on installation from the template to set the sequence correctly there. Otherwise you could just fix it in the settings as you already know.

**Comment by astirpe** [comment]
@wtaferner is right, Odoo retrieves by default the first tax based on its sequence.
The fix seems easy, just updating the sequences.
I will propose a PR tomorrow.

Thank you!

**Comment by ploegvde** [comment]
Can this be merged please?

**Comment by Yenthe666** [comment]
@mart-e can you look at this please?

**Comment by ploegvde** [comment]
Can this be merged please?

**Comment by gustavovalverde** [comment]
I can't understand why simple localization fixes takes so long to be merged.

**Comment by Yenthe666** [comment]
@mart-e another ping 💎

**Comment by mart-e** [comment]
Thanks, fixed at b431e1822620d2c32a9342e78f5408c9771e7549
