### ISSUE TITLE
website module unexpectedly appears uninstalled and webpages are lost

### ISSUE THREAD

**Issue by Danisan** [odoo/odoo#14168]
Impacted versions: Odoo 10 Community

Steps to reproduce: just wait for some days. Missing website menu at backend, and pages at the frontend.

Current behavior: all website related addons uninstalled as if you uninstall them.

Expected behavior: website remains

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello,

IMHO, there no random unlink of website module in Odoo... :hammer: 

So without more information, not easy to help you.
You probably trigger the uninstall removing a dependent module... Eg: 'web_editor' or 'web_planner'

What do you see in your log ? When it has been uninstalled ? what has been done just before... ?
write_date from other module can help you to detect the lists of modules affected...

**Comment by Danisan** [comment]
Till now, I can give you just an hypothesis, is that there happenned an update to the database someway. It seems that the website data files does not have the <data> tag, consequently, that "no update" is in false, ant this could be the cause of the website being reset badly.
Anyway I will try to reproduce, but this is just a part of the problem.. still have to justify the uninstall of some apps.

**Comment by Danisan** [comment]
Another clue, is that in (another) develop instance, when trying to install a badly set chart of account, it caused the uninstallation of "project" module. when trying to reinstall get an error that prevents the installation.
Seems to me, something about that when a dependency of something caused an exception, make it go away, instead of raising an error.

**Comment by JKE-be** [comment]
> Regarding the log, I can't yet establish the exact moment 

A grep of `Deleting.*website` should help you to find the exact time.

> It seems that the website data files does not have the tag, consequently, that "no update" is in false, ant this could be the cause of the website being reset badly.

When you update view via editor, their should be automatically set to 'no updatable'.
If you edit view custom view, you probably use inheritance and so view without reflink to website module.

> when trying to install a badly set chart of account, it caused the uninstallation of "project" module. when trying to reinstall get an error that prevents the installation.

It is a really bug if it is true :/  I will be very interested if you can reproduce it ...

Let me know when you find more informations.

Best regards

Jeremy

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in quite a while.
If you can still reproduce it then please post back here and I'll reopen it.

Regards,
Yenthe
