### ISSUE TITLE
GEOIP_EMPTY_COUNTRY not declared

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#141657]
Impacted versions: 17.0 (yay, second issue on 17.0 it seems)

Steps to reproduce:
1. Odoo 17.0 branch checked out from git. Clean database.
2. Install website.
3. Go to localhost:8069 in your browser

Current behavior:

Error while render the template
NameError: name 'GEOIP_EMPTY_COUNTRY' is not defined
Template: website.layout
Path: /t/html/head/script[2]/t
Node: <t t-out="json.dumps(request.env[\'ir.http\'].get_frontend_session_info())"/>
Compiled code:
code = None
template = 'website.layout'
template_functions = {}
def template_504_t_set_1(self, values):
    # element: '/t/html/head/t[1]/t[2]/t[1]' , '<t t-if="additional_title"/>'
    yield ' '
    if ((values.get('additional_title'))):
        attrs = values['__qweb_attrs__'] = {}
        # element: '/t/html/head/t[1]/t[2]/t[1]/t' , '<t t-out="additional_title"/>'
        attrs = values['__qweb_attrs__'] = {}
        content = ((values.get('additional_title')))
        if content is not None and content is not False:
            yield str(escape(content))...
The error occurred while rendering the template website.layout and evaluating the following expression: <t t-out="json.dumps(request.env[\'ir.http\'].get_frontend_session_info())"/>

Expected behavior:
Should show Odoo main menu (this is Odoo 17.0 CE). Also the geoip2 module is not installed, seems odoo/http.py happily ignores that in a try except block.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by bigboss97lnt** [comment]
+1

The same error happened in both incognito and regular browser, after I clicked the check-in button in the main nav-bar it asked for location permissions and I allowed it but it showed the error anyway.

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "///odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "///odoo/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/addons/hr_attendance/controllers/main.py", line 143, in systray_attendance
    geo_ip_response = self._get_geoip_response(mode='systray',
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "///odoo/addons/hr_attendance/controllers/main.py", line 44, in _get_geoip_response
    'city': request.geoip.city.name or _('Unknown'),
            ^^^^^^^^^^^^^^^^^^
  File "///odoo/odoo/http.py", line 1110, in __getattr__
    if hasattr(GEOIP_EMPTY_COUNTRY, attr):
               ^^^^^^^^^^^^^^^^^^^
NameError: name 'GEOIP_EMPTY_COUNTRY' is not defined

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://127.0.0.1:8069/web/assets/1a8bbe8/web.assets_web.min.js:2866:163)
    at XMLHttpRequest.<anonymous> (http://127.0.0.1:8069/web/assets/1a8bbe8/web.assets_web.min.js:2870:13)
```

**Comment by rdeodoo** [comment]
A fix is being investigated and should be available soon

**Comment by rdeodoo** [comment]
Have you correctly added the new `geoip2` python dependency, required since Odoo 16.2?
https://github.com/odoo/odoo/commit/c59750d8244068e191a78631f8e0fd3d09067e3d#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R9

**Comment by rdeodoo** [comment]
@d-fence had a look and the windows installer seems fine and should install the requirements (including geoip2): `Successfully installed geoip2-2.9.0 maxminddb-2.5.1 setuptools-68.2.2`

Should anyone face this `geoip2` issue, please make sure that you correctly installed the packages through the `requirements.txt`.
And for OS installer, should this error appear, could you give us a full description of the error and the flow you used?

**Comment by Levi-Bensley** [comment]
For OS Installer, i installed using the installer (16 was also present on the computer). No error untill website module was installed. Once website was installed the error started occuring whenever i would go to a webpage. Also session expired and signed me out, at this point had no access to the website because of an Internal server error.

Error from log:

```
2023-11-13 15:19:01,054 8988 ERROR test_17 odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 17.0\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 1758, in _serve_ir_http
    ir_http._pre_dispatch(rule, args)
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\website\models\ir_http.py", line 179, in _pre_dispatch
    super()._pre_dispatch(rule, arguments)
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\auth_signup\models\ir_http.py", line 13, in _pre_dispatch
    super()._pre_dispatch(rule, args)
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\web_editor\models\ir_http.py", line 24, in _pre_dispatch
    super()._pre_dispatch(rule, args)
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\http_routing\models\ir_http.py", line 543, in _pre_dispatch
    cls._frontend_pre_dispatch()
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\website\models\ir_http.py", line 206, in _frontend_pre_dispatch
    request.update_context(tz=pytz.timezone(request.geoip.location.time_zone).zone)
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 1110, in __getattr__
    if hasattr(GEOIP_EMPTY_COUNTRY, attr):
NameError: name 'GEOIP_EMPTY_COUNTRY' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 2157, in __call__
    response = request._serve_db()
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 1736, in _serve_db
    exc.error_response = self.registry['ir.http']._handle_error(exc)
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\http_routing\models\ir_http.py", line 636, in _handle_error
    cls._frontend_pre_dispatch()
  File "C:\Program Files\Odoo 17.0\server\odoo\addons\website\models\ir_http.py", line 206, in _frontend_pre_dispatch
    request.update_context(tz=pytz.timezone(request.geoip.location.time_zone).zone)
  File "C:\Program Files\Odoo 17.0\server\odoo\http.py", line 1110, in __getattr__
    if hasattr(GEOIP_EMPTY_COUNTRY, attr):
NameError: name 'GEOIP_EMPTY_COUNTRY' is not defined
```

**Comment by bringsvor** [comment]
I dont have the geoip2  module, as I stated when I created the ticket. But
the import in http.py is surrounded with an if... Else so it is dilently
ignoref. So instead of fall at startup it falls at use.

Also 16 works fine on the same setup.

man. 13. nov. 2023, 16:36 skrev Levi Bensley ***@***.***>:

**Comment by rdeodoo** [comment]
It's expected to fail at use and not at startup, the `if` does look as it's actually making the `geoip2` not required but **it is required**, as stated in the `requirements.txt`.
Don't mind this weird-at-first-look `if` condition, it was introduced as a fix for the IOT box, but it's an exception.

**Comment by d-fence** [comment]
I was not able to reproduce with the latest 17.0 windows installer.

**Comment by bigboss97lnt** [comment]
This error used to happen with me with the following config:

Environment:
- Mac OS
- Python 3.9
- All dependencies in requirements.txt installed
- Running Odoo using the source code using the following command (python3 odoo-bin -d db -w a --addons-path='')

After I noticed that I needed to use Python 3.10, I re-installed the requirements.txt and Python 3.10, and the error is gone and the check-in/out button from the navigation bar is now working error-free.

**Comment by rdeodoo** [comment]
Indeed, python 3.10 is required in Odoo 17.
See [this commit](https://github.com/odoo/odoo/commit/163fb3ae618bf993e60f8c1276e09a5b85565fa5#diff-be4a9ebf32c3cc50ef58fd567c76980f729a54dec64cd46ccaa12bf8db112e0aR19) and [this documentation](https://github.com/odoo/documentation/commit/4f531cf1f19ee14c3b2112193408ecf9be1a9a1f)

**Comment by FabioMT99** [comment]
Tengo el mismo problema en odoo 17 al instalar el modulo de website me da ese error, en odoo 16 eso no me pasaba

**Comment by 4minds-araman** [comment]
Just Again run the requirement.txt file and it will works as expected.

**Comment by sasindran-nits** [comment]
**solution:**  pip install geoip2

**Comment by ihzaputra** [comment]
yes im encountered this issue also and pip instal geoip2 fix the problem

**Comment by killdiotxx** [comment]
> Have you correctly added the new `geoip2` python dependency, required since Odoo 16.2? [c59750d#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R9](https://github.com/odoo/odoo/commit/c59750d8244068e191a78631f8e0fd3d09067e3d#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R9) Other relevant commit: [5f251f7](https://github.com/odoo/odoo/commit/5f251f7c95adf9b67ef1c81ee0084b0b5c396cc3)

this worked for me! thanks!

**Comment by yvann225** [comment]
> Versions impactées : 17.0 (ouais, deuxième problème sur 17.0 apparemment)
> 
> Étapes à suivre pour reproduire :
> 
> 1. Branche Odoo 17.0 extraite de git. Base de données propre.
> 2. Installer le site Web.
> 3. Accédez à localhost:8069 dans votre navigateur
> 
> Comportement actuel :
> 
> Erreur lors du rendu du modèle NameError: le nom 'GEOIP_EMPTY_COUNTRY' n'est pas défini Template: website.layout Path: /t/html/head/script[2]/t Node: Code compilé: code = None template = 'website.layout' template_functions = {} def template_504_t_set_1(self, values): # element: '/t/html/head/t[1]/t[2]/t[1]' , '' yield ' ' if ((values.get('additional_title'))): attrs = values[' **qweb_attrs** '] = {} # element: '/t/html/head/t[1]/t[2]/t[1]/t' , '' attrs = values[' **qweb_attrs** '] = {} content = ((values.get('additional_title'))) si le contenu ne l'est pas Aucun et le contenu n'est pas faux : yield str(escape(content))... L'erreur s'est produite lors du rendu du modèle website.layout et de l'évaluation de l'expression suivante :
> 
> Comportement attendu : doit afficher le menu principal d'Odoo (il s'agit d'Odoo 17.0 CE). De plus, le module geoip2 n'est pas installé, il semble qu'odoo/http.py l'ignore volontiers dans un bloc try except.
> 
> Lien vidéo/capture d'écran (facultatif) :
> 
> Numéro de ticket d'assistance soumis via odoo.com/help (facultatif) :

**Comment by atifcs67** [comment]
facing the same issue with odoo 17 

after installing the website app error appears;

Error while render the template
NameError: name 'GEOIP_EMPTY_COUNTRY' is not defined
Template: website.layout
Path: /t/html/head/script[2]/t
Node: <t t-out="json.dumps(request.env[\'ir.http\'].get_frontend_session_info())"/>

**Comment by huzaifaasaad2345** [comment]
in my case this is not working "solution: pip install geoip2"
