### ISSUE TITLE
[10.0 & PG 9.6] Create New Database with UI = Database creation error: column res_lang.active does not exist LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =... ^

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#14160]
<h1>Impacted versions:</h1>
Odoo 10.0

<h1>Environment:</h1>
<ul>
<li>Odoo 10.0 (Latest Pull as of 5th of November, 2016)</li>
<li>PostgreSQL 9.6</li>
<li>Ubuntu 14.04</li>
</ul>
<h1>Steps to reproduce:</h1>
I have two versions of PostgreSQL running on my machine in order to do testing in a development environment. These are PostgreSQL 9.5 and PostgreSQL 9.6.

I have thrown together a quick gist with an SH script (modified slightly from Yenthe's script for 10.0) to allow you to quickly/easily replicate the issue.

<ul>
<li>Install on a clean Ubuntu 14.04 server edition using sh script found here: <a href="https://gist.github.com/lukebranch/aeff913f554f3a2f8469965e8e82f2ea">https://gist.github.com/lukebranch/aeff913f554f3a2f8469965e8e82f2ea</a></li>
<li>Once you've installed create a single database using the Odoo /web/database/manager, this I initially had no issue with.</li>
<li>Now create a second database</li>
</ul>

<h1>Current behaviour:</h1>
Red dialog box in /web/database/manager with the following error message:

```
Database creation error: column res_lang.active does not exist LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =... ^
```

The full traceback in the logs is here:

```
2016-11-05 02:18:53,668 21666 ERROR WE123 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo10/odoo10-server/odoo/modules/loading.py", line 411, in load_modules
    model._register_hook()
  File "/odoo10/odoo10-server/odoo/addons/base/res/res_lang.py", line 80, in _register_hook
    if not self.search_count([]):
  File "/odoo10/odoo10-server/odoo/models.py", line 1481, in search_count
    res = self.search(args, count=True)
  File "/odoo10/odoo10-server/odoo/models.py", line 1504, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo10/odoo10-server/odoo/models.py", line 4202, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/odoo10/odoo10-server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_lang.active does not exist
LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =...
                                               ^

2016-11-05 02:18:53,670 21666 ERROR WE123 odoo.http: column res_lang.active does not exist
LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =...
                                               ^
Traceback (most recent call last):
  File "/odoo10/odoo10-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/odoo10/odoo10-server/odoo/service/common.py", line 57, in dispatch
    return g[exp_method_name](*params)
  File "/odoo10/odoo10-server/odoo/service/common.py", line 29, in exp_authenticate
    res_users = odoo.registry(db)['res.users']
  File "/odoo10/odoo10-server/odoo/__init__.py", line 55, in registry
    return modules.registry.Registry(database_name)
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 55, in __new__
    return cls.new(db_name)
  File "/odoo10/odoo10-server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo10/odoo10-server/odoo/modules/loading.py", line 411, in load_modules
    model._register_hook()
  File "/odoo10/odoo10-server/odoo/addons/base/res/res_lang.py", line 80, in _register_hook
    if not self.search_count([]):
  File "/odoo10/odoo10-server/odoo/models.py", line 1481, in search_count
    res = self.search(args, count=True)
  File "/odoo10/odoo10-server/odoo/models.py", line 1504, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo10/odoo10-server/odoo/models.py", line 4202, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/odoo10/odoo10-server/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_lang.active does not exist
LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =...
                                               ^

2016-11-05 02:18:53,732 21666 INFO WE123 werkzeug: 127.0.0.1 - - [05/Nov/2016 02:18:53] "POST /web/database/create HTTP/1.0" 200 -
```

<h1>Expected behaviour:</h1>
Create a new database with no error message.

<h1>Video/Screenshot link (optional):</h1>
<img src="https://cloud.githubusercontent.com/assets/2337666/20026973/dcb2819a-a341-11e6-8776-a3fdc1213897.gif" />

**Comment by DipaliKhatri** [comment]
@lukebranch 
First checkout the branch in 10.0 than pull in that branch and than clear the cookies and than make a new DB.

**Comment by lukebranch** [comment]
@DipaliKhatri ,

Thank you for your suggestion, however unfortunately in my case this does not resolve the issue. Actually to add further to this anything in /web/database/manager relating to database backup or duplication results in a PG error.

I will investigate further to see if this is related to my own setup and update this thread accordingly.

**Comment by tarteo** [comment]
@DipaliKhatri I had the same issue, do you have an empty __manifest__.py file somewhere (addons/{module_name}/__manifest__.py)?

**Comment by DipaliKhatri** [comment]
@tarteo,
In addons 10.0 no one empty __manifest__.py file in any modules.

**Comment by tarteo** [comment]
@DipaliKhatri meant to ask @lukebranch

**Comment by DipaliKhatri** [comment]
First checkout the branch in 10.0 than pull in that branch and than clear the cookies and than make a new DB.

**Comment by tarteo** [comment]
@DipaliKhatri Yes, but that did not resolve @lukebranch issue. I **_had_** the same issue he has and resolved it by removing an empty \_\_.manifest\_\_.py file. So that's what I'm suggesting to @lukebranch to do.

**Comment by lukebranch** [comment]
@tarteo @DipaliKhatri ,

Thanks for all your comments. The issue is now resolved. It seems your suggestions were both correct to resolve my issue.

@tarteo ,

It seems you were right. I've removed all but the default addons from my addons path, so it's obviously something in my own custom addons directories that is causing this behaviour. I have not had time to single out the exact one causing the issue, however I will attempt this later.

I'm going to close this thread as resolved for now, however @Yenthe666 , i'm wondering whether this is the intended behaviour, or if perhaps a more graceful/informative fallback/error is possible?

It is after all due to some unfinished code sitting in a directory somewhere, however it would seem strange that a module only installed on one database could affect the backup of all databases in that instance.

**Comment by Yenthe666** [comment]
Hi @lukebranch,

Thanks for notifying me about this. I've actually encountered something like this a few weeks ago too and it had to do with the manifest.py file too. 
@mart-e I'm not sure if we can handle this better/cleaner? 👍

**Comment by rossigee** [comment]
FTR, I've just got to the bottom of a problem with the exact same symptom (res_lang table missing 'active' field). It turned out to be that I had restored a live database backup to my local machine, but the owner of the db/tables in the backup file from the live server did not match any users/roles in my local machine's postgres container, so the 'res_lang' table got truncated (somehow!) and appears to have been created with just 'name', 'code' and one other field, but none of the rest of the fields from the CREATE TABLE section of the db dump.

**Comment by PeterAlabaster** [comment]
I just came across this exact issue. Turns out it was due to a module containing an accented e character in the` __manifest__.py`: `é`. Took it out and db was happy to be created again.

**Comment by AlaGarali** [comment]
I have the same problem:
_______________________________________________________________________________________________________________
Database creation error: ERREUR: la colonne res_lang.active n'existe pas LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =... ^
_______________________________________________________________________________________________________________
But I didn't resolve it. Please help me to resolve this problem.
Thanks.

**Comment by igloo** [comment]
Hi,
I also have the same problem. For me it was an empty __manifest__.py file in one of my addons module which was added but never developped. Adding a correct { 'name' : 'blabla'  } in the manifest file and all is OK. I can generate another base.
Hope it will help.

**Comment by ivanporras** [comment]
Check answer of @tarteo

**Comment by TarikIbrahim** [comment]
Unfortunately mentioned solutions did not work for me , simply i modified the "odoo.conf" file to remove the custom modules path , then i created my database and login into it,back to modify the "odoo.conf" and get the custom modules path , save and close the files
restart odoo server and it worked properly
