### ISSUE TITLE
[9.0] Enterprise bug because of meory leak commit

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#14161]
Impacted versions:
[9.0] Did not test 10

After this memory leak commit we have constantly javascript error

https://github.com/odoo/enterprise/commit/eaec2ed83f4ca0cae3b0164ccc04029628a5860f

problem is from the view_manager.js

enterprise/web/static/src/js/view_manager.js

Cannot read property '$multi' of undefined
from the this.switch_buttons.$multi
line no. 464

**Comment by Yenthe666** [comment]
@ged-odoo perhaps something for you?

**Comment by ged-odoo** [comment]
definitely for me :(

**Comment by ged-odoo** [comment]
should be fixed by https://github.com/odoo/enterprise/commit/423aae779091e7cbc707f30ae2780c3b63045670
