### ISSUE TITLE
[17.0] base: Typo error in Spanish (Latin America) of module

### ISSUE THREAD

**Issue by luiseevaquer** [odoo/odoo#141697]
Impacted versions:

**17.0** 

Steps to reproduce:

**Enter in Contact and trying create a new contact**

Current behavior:

**Show this message:
Caused by: EvalError: Can not evaluate python expression: (bool(no is_company))
Error: Name 'no' is not defined**

Typo Error Line https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/i18n/es_419.po#L11666

**Comment by vava-odoo** [comment]
Hi @luiseevaquer 
Thanks for reporting. It will be fixed by https://github.com/odoo/odoo/pull/141704 very soon.
Cheers
