### ISSUE TITLE
[10.0 Community]  the email field in the form, must be text type.

### ISSUE THREAD

**Issue by nuelgoz** [odoo/odoo#14163]
Impacted versions: [10.0 Community] docker ODOO_RELEASE 20161103

in the registration form after the purchase in the ecommerce; in the email field the field is numeric and tablet or smartphone activates the keypad and it is difficult to write an email.

the email field in the form, must be text type

![8077288068134742288 account_id 0](https://cloud.githubusercontent.com/assets/9434922/20036861/9a601306-a414-11e6-9373-a2aae4b849e1.png)

**Comment by JKE-be** [comment]
Hi @nuelgoz,

It should be fixed 13 day ago with commit: https://github.com/odoo/odoo/commit/651738303a06b8c24b0d4334e4a62343884b305b

Can you check that your views is updated ...

Best regards

JKE

**Comment by nuelgoz** [comment]
Solved updating the views, ok thanks.

**Comment by JKE-be** [comment]
Thanks for feedback
