### ISSUE TITLE
[17.0] Web module LazyTranslatedString error maybe due to missing moment.js

### ISSUE THREAD

**Issue by TrungMC** [odoo/odoo#141733]
Impacted versions: 17.0 Community

Steps to reproduce: Create a new database with language other than English (Vietnamese for example)

Current behavior: An error popup appears with LazyTranslatedString error on the login screen and all the website pages.

Expected behavior: No error popup screen

Other info:
- moment folder not found in the source code. 
- moment.js not included in the source code
- sometimes you don't see the error because the moment folder is missing and the /webclient/locale return an empty file which will not have any javascript error.

Temporary fix:
- copy moment folder from other version (16) to /web/static/lib/moment
- add reference to moment.js in web/__manifest.py

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by TrungMC** [comment]
Thank you @vava-odoo  for your feedback and your insight about luxon. It is standard module but the localization. In my case vi-VN. So I guess that the localization of odoo17 ce hasn't fully move to luxon because the code still refers to moment. 

Specifically, the moment is still used in this code of https://github.com/odoo/odoo/blob/17.0/addons/web/controllers/webclient.py. I don't know the conditions when it is called (possibly some pages only, not all the pages) but when it does, it can not find the file since you said moment was dropped. 

```python
class WebClient(http.Controller):

    @http.route('/web/webclient/locale/<string:lang>', type='http', auth="none")
    def load_locale(self, lang):
        lang = MOMENTJS_LANG_CODES_MAP.get(lang, lang)
        magic_file_finding = [lang.replace("_", '-').lower(), lang.split('_')[0]]
        for code in magic_file_finding:
            try:
                return http.Response(
                    werkzeug.wsgi.wrap_file(
                        request.httprequest.environ,
                        file_open(f'web/static/lib/moment/locale/{code}.js', 'rb')
```

**Comment by chapital** [comment]
another solution for this?

**Comment by chapital** [comment]
#148507 similar troubles with this, I testing the upgrade from odoo 16 to 17, with es_MX localization

**Comment by vava-odoo** [comment]
@TrungMC Looks like it was solved with https://github.com/odoo/odoo/commit/6633a1102f6f9264d2da9a394945e4a49a23efd7
Thanks for reporting.
