### ISSUE TITLE
   reservations.pop() IndexError: pop from empty list

### ISSUE THREAD

**Issue by libukoshy** [odoo/odoo#14173]
Impacted versions:odoo 10 community

Steps to reproduce:Create BOM

BoM Type	Ship this product as a set of components (kit)	

Create a Manufacturing order then will get below error 

  preferred_domain_list=preferred_domain_list)
  File "/home/libu/Odoo/odoo-10c/Addons-10c/stock/models/stock_quant.py", line 421, in quants_get_reservation
    reservations.pop()
IndexError: pop from empty list

Current behavior:

Expected behavior:

Video/Screenshot link (optional): http://prnt.sc/d42u0l

**Comment by jco-odoo** [comment]
It is not a good idea to produce something that is a kit, but I think this problem is because of something else and should have been solved in the meantime.
