### ISSUE TITLE
Odoo upgrade from 9.0 to 10.0 community error

### ISSUE THREAD

**Issue by nadirlc** [odoo/odoo#14172]
Impacted versions: 9.0

Steps to reproduce: Add the debian repository deb http://nightly.odoo.com/10.0/nightly/deb to /etc/apt/sources.list. Run apt-get update and then apt-get dist-upgrade.

Current behavior: The Odoo is updated to version 10.0, but it gives an error when accessed from web browser. The error is: ProgrammingError: column website.favicon does not exist.

Expected behavior: It should upgrade from 9.0 to 10.0 without errors. It seems the database was not updated.

Video/Screenshot link (optional):

**Comment by kkinateder** [comment]
start your instance with parameter  -u all

**Comment by nadirlc** [comment]
I am using the command service odoo start. It does not accept the parameter -u all.

I removed 9.0 installation and installed the 10.0. Its working now.
