### ISSUE TITLE
[17.0] should not check version format of addons that are not installable

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#141747]
Impacted versions: 17.0

Steps to reproduce:

Add an addon with `"version": "16.0.1.0.0"` and `"installable": False` in addons path.

Current behavior:

Odoo does not start, with error `Invalid version '16.0.1.0.0'. Modules should have a version in format `x.y`, `x.y.z`, `17.0.x.y` or `17.0.x.y.z`.`

Expected behavior:

Modules which are not installable should not be checked for version format.
Indeed, this is a common workflow in migration projects to mark all modules installable=False, then migrate them one by one.
This error breaks that workflow.

Additional context:

This is due to https://github.com/odoo/odoo/pull/118420. Summoning @KangOl.

**Comment by sbidoul** [comment]
@KangOl gentle nudge here. I'm totally fine with #118420, but can it be adapted to not check the version of modules with installable=False?

**Comment by KangOl** [comment]
Yes, we can convert this error to a warning for uninstallable modules.

Mind you create a PR?

**Comment by sbidoul** [comment]
> Yes, we can convert this error to a warning for uninstallable modules.

@KangOl I can look into it, but then you merge https://github.com/odoo/odoo/pull/44001. Deal?

**Comment by sbidoul** [comment]
@KangOl the PR with the fix is at #157657. Let me know if you have any question.

**Comment by sbidoul** [comment]
Fixed in #157657
