### ISSUE TITLE
Print quotation/sale order - KeyError

### ISSUE THREAD

**Issue by walterwor** [odoo/odoo#141859]
Impacted versions: 16

Steps to reproduce: When intented print the quotation/sale order from printer option

Current behavior: 

```
Error while generating report sale.report_ saleorder 

odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/tr/td[2]/span
Node: <span t-esc="o.amount_total"

```
Expected behavior:  print qweb report

Video/Screenshot link (optional): 
![Captura desde 2023-11-13 12-38-40](https://github.com/odoo/odoo/assets/1504901/ac4fb748-96ba-425e-9ae9-f7d739687efc)
![Captura desde 2023-11-13 12-39-14](https://github.com/odoo/odoo/assets/1504901/d9df0cab-fc2a-4492-a278-ed35a9b68866)

Can help me?

**Comment by vava-odoo** [comment]
Hi @walterwor 
I can't find the occurrence you mention, so I guess it either has been fixed, either comes from a custom module.
Please re-open if it is not the case.
Cheers
