### ISSUE TITLE
[9.0] language not works correctly when copy records

### ISSUE THREAD

**Issue by kkinateder** [odoo/odoo#14189]
Impacted versions: v9

Steps to reproduce: Setup odoo/psql server with system language en_UK

Current behavior: When a user with language en_UK copy a record as example product.template, then only the translated label for en_UK is written, not the record.name . That has the side-effect, that all products have the same record.name . 

Expected behavior: All new name stored in record.name and not in ir_translation

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

It is actually the intended behaviour. When duplicating a record, we keep the translations/original values.
The point is that, after duplicating a translated record, you MUST look at the translations (we added a warning about that in v10). We prefer to keep the same (and let the user adapt them) than losing everything and forcing to make a new translation.
