### ISSUE TITLE
[10.0c] Meeting don`t appear in Arabic language

### ISSUE THREAD

**Issue by abdallamohamed1992** [odoo/odoo#14182]
Impacted versions:
 I use version number "7cfbdd57b4c94b7ea44c93829de72337113d5dfe" Community Edition

Steps to reproduce:
 1. Activate Developer mode.
 2. Install Arabic Language from "Setting --> Translations -->Load a Translation".
 3. Change user language from "Preferences" to use Arabic.
 3. Open Calendar menu.

Current behavior:
I can`t find any record when using Arabic language in "Calendar view"
 
Expected behavior:
  As when using English language records appear in "Calendar view"

Screenshot:
![arabic calender](https://cloud.githubusercontent.com/assets/13385546/20056423/b4525208-a4ee-11e6-8ac0-fe55a2d3ec61.PNG)
![english calender](https://cloud.githubusercontent.com/assets/13385546/20056424/b45b8a58-a4ee-11e6-9b89-1916a64c8e9c.PNG)

**Comment by hanyelbanna** [comment]
I have the same problem!

**Comment by mart-e** [comment]
It should be solved now 

![screenshot-2017-10-26 - odoo](https://user-images.githubusercontent.com/564822/32055177-55a1d54c-ba61-11e7-8c77-7c886d57121f.png)
