### ISSUE TITLE
Change stage in CRM module  (odoo 9)

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#14190]
I can't change lead or opportunity stage, after click on stage in form view nothing happens. 

Video > http://sendvid.com/ubz3qnki

In Sale Configuration > Lead and Opportunities > Stage (3 stages is added)

In Sales Team (Direct Sales), stages and user (administrator) is added. 

https://postimg.org/image/kyvh88391/

Only in Kanban view opportunity is it possible change stage.

**Comment by JKE-be** [comment]
I cannot reproduce: 
Juste tested now: http://178874-9-0-af865c-all.runbot5.odoo.com/web?debug=1&reload#id=45&view_type=form&model=crm.lead&menu_id=341&action=456

Are you sure that you set the stage for both lead/opp (at creation, you have a select input) ?

Please uses the default template when you post an issue.

**Comment by aspcsharp9** [comment]
My stage is set to both  https://postimg.org/image/p3lawg4z5/

On your link work fine. I don't know where is problem on my side.

**Comment by JKE-be** [comment]
If we cannot reproduce it, it is not easy for us to help you... 
You can maybe check in your log if you have not an error during the "switching of stages", or ...

If you have more info, don't hesitate to reply to open this issue again.
