### ISSUE TITLE
Action not Creating Mass Mailing Contact

### ISSUE THREAD

**Issue by GenericUK** [odoo/odoo#14193]
Impacted versions: 
9.0c-20160620 (Community Edition)

Steps to reproduce: 
Incoming Mail Servers >  Actions to Perform on Incoming Mails >
Create a New Record > Mass Mailing Contact

Current behavior:
Not creating a new Mass Mailing Contact.

Expected behavior:
Create new Mass Mailing Contact

Video/Screenshot link (optional):

**Comment by ankur1367** [comment]
@GenericUK Can you post the screenshot?

**Comment by GenericUK** [comment]
Hi, thanks for your reply. What do you want a screenshot of? All I have is the Mass Mailing Contact action selected in the incoming mail settings, but when an email is received no mailing list contact is created. My guess is I need to tell the action to select a mailing list so this maybe more of a help question than  and issue. However my expected behaviour would still be for a new mailing list contact to be created which could then be assigned a mailing list.

**Comment by pedrobaeza** [comment]
This is a misuse of the "Create a New Record" feature of the incoming server. You can't add a record which doesn't have a chatter (inherits from mail.thread), so there's no real issue, and thus I'm closing.
