### ISSUE TITLE
[17.0] Error when installing demo data for PoS: Proxy IP cannot be empty

### ISSUE THREAD

**Issue by chrisb-c01** [odoo/odoo#141964]
Impacted versions: 
17.0

Steps to reproduce:
1. Install a clean db with PoS module. 
2. Load demo data from settings screen

Current behavior:
Error is shown: Proxy IP cannot be empty.
In the code this is triggered by 'addons/point_of_sale/models/pos_printer.py:19'

Expected behavior:
No error is shown, demo data is installed.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @chrisb-c01 
Thanks for reporting. It was fixed with https://github.com/odoo/odoo/commit/bde8ac75055d9fb53fb8b989a01f3e865afdfb27.
Cheers!
