### ISSUE TITLE
when i clone the repo, i found the size is over 7G. the pack file in .git\objects\pack is bigger than 6G.  can i delete it ? 

### ISSUE THREAD

**Issue by Leo1piece** [odoo/odoo#141987]
Impacted versions:16.0

Steps to reproduce:

Current behavior:when i clone the repo, i found the size is over 7G. the pack file in .git\objects\pack is bigger than 6G.  can i delete it ? 

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Leo1piece** [comment]
![image](https://github.com/odoo/odoo/assets/120457532/5f9c728a-02ec-46a7-a43a-f63718cc9b4a)

**Comment by gdgellatly** [comment]
You are cloning the entire history? Literally noone needs to do that, what are you going to do with 10+ years of history. This is a standard v16 single branch pull with a depth of 100 for development. In production depth is 1, but actually we delete all those artifacts and unnecessary translation for prod builds and all of Odoo takes 233MB.

Development
```
graemeg@graeme-z590visiong ~/p/v/o/s/o/.git (GIT_DIR!)> du -h -d 1
373M    ./objects
8.0K    ./info
60K     ./logs
64K     ./hooks
4.0K    ./branches
48K     ./refs
377M    .
```

prod
```
odoo@2d4839eef64e:~/src/odoo$ du -h -d 1
16M     ./odoo
8.0K    ./__pycache__
60K     ./odoo.egg-info
700K    ./setup
128K    ./debian
3.0M    ./doc
44K     ./.tx
204M    ./addons
223M    .
```

**Comment by Leo1piece** [comment]
Thanks a lot ,i got it .

**Comment by Leo1piece** [comment]
i use the commonad: 
git clone --depth 1 https://github.com/odoo/odoo.git 
and found the size is also 1 GB.

```
/odoo(17.0)$ du  -h -d 1
161M    ./.git
0       ./.github
100K    ./.tx
764M    ./addons
88K     ./debian
292K    ./doc
89M     ./odoo
616K    ./setup
1014M   .
```

**Comment by Leo1piece** [comment]
Thanks a lot for your information.
i use the commonad:
`git clone --depth 1 https://github.com/odoo/odoo.git`
and found the size is also 1 GB.

```
/odoo(17.0)$ du  -h -d 1
161M    ./.git
0       ./.github
100K    ./.tx
764M    ./addons
88K     ./debian
292K    ./doc
89M     ./odoo
616K    ./setup
1014M   .

```

> You are cloning the entire history? Literally noone needs to do that, what are you going to do with 10+ years of history. This is a standard v16 single branch pull with a depth of 100 for development. In production depth is 1, but actually we delete all those artifacts and unnecessary translation for prod builds and all of Odoo takes 233MB.
> 
> Development
> 
> ```
> graemeg@graeme-z590visiong ~/p/v/o/s/o/.git (GIT_DIR!)> du -h -d 1
> 373M    ./objects
> 8.0K    ./info
> 60K     ./logs
> 64K     ./hooks
> 4.0K    ./branches
> 48K     ./refs
> 377M    .
> ```
> 
> prod
> 
> ```
> odoo@2d4839eef64e:~/src/odoo$ du -h -d 1
> 16M     ./odoo
> 8.0K    ./__pycache__
> 60K     ./odoo.egg-info
> 700K    ./setup
> 128K    ./debian
> 3.0M    ./doc
> 44K     ./.tx
> 204M    ./addons
> 223M    .
> ```

**Comment by Leo1piece** [comment]
and also i foudn only 17.0 branch,  i want use 16.0 branch . 
```
  git branch
* 17.0
```

**Comment by gdgellatly** [comment]
You are comparing apples and oranges. Your git directory is only 161Mb now, compared to many gigabytes before.

Yes a standard Odoo clone will take about a gig just in files, 85% of those are translation files. For our production installs we delete all languages that we do not need in order to make deployment images much smaller.

**Comment by Yenthe666** [comment]
As answered by @gdgellatly :) This is more about Github knowledge than Odoo too.

**Comment by usamabfdpc** [comment]
git clone <repo> --single-branch --branch 16.0 --depth 1
when i clone by this command there is no proper UI.
I think some css file missed.
Have any solution
