### ISSUE TITLE
Odoo10: Wizard buttons are not disabled after printing a Report/performing any action.

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#14205]
**_Impacted versions:_**
Odoo 10E

**_Steps to reproduce:_**
Create a Wizard, which has button to perform some action, say to print a report.
Print the Report, once after the report is printed, the same print-button will be still in active mode.

**_Current behavior:_**
Once the button is clicked to trigger the action, the button is not disabled after performing the action, seemingly making it look like the wizard/button is active. Hence User tries to click again, triggering the same action twice.

**_Expected behavior:_**
In Version 9 or Below, after printing the report/ the target button becomes inactive, though the Wizard box stays.
Certainly it would be great, if the Wizard dialogue box closes after printing the report, However disabling the button seemed to keep things at bay.

**Comment by sle-odoo** [comment]
Well printing a report is done by returning an ir.actions.report.xml action when clicking on a button. When you do that, the weblcient is blocked until the download of the report is started. Isn't that enough? I mean if you have a wizard ton print a button, it means that you give some choice to the user. Keeping the wizard open allows the user to change some data and print again, doesn't that make sense?

**Comment by deepa4lok** [comment]
Well that could work out in some places while some it is not, especially when action is triggered twice, for printing I can agree with you, consider am using wizard to update things, 
For example say am updating qty in BOM, (custom update), after the qty is updated, it would be good if the button is deactivated, that way I will be assured I had updated, but without knowing/or accidentally I pressed the button again,then twice update activity is triggered, which is incorrect.

**Comment by Yenthe666** [comment]
@sle-odoo any update? 😉

**Comment by sle-odoo** [comment]
@Yenthe666 I'm pretty sure we won't change that in 10/11 as in our core apps these kind of buttons are always in a wizard, where it make sense to not disable the button to allow the user updating the values and re-render the report. I also don't think making the button inactive only if the form view has no inputs is clean nor user friendly (the user won't understand why sometimes the button is changing), so i don't think we'll change this in master too. I suggest @deepa4lok to make a little widget on the form view button to customise it as needed.

Regards
