### ISSUE TITLE
[10.0] <a type="edit"> not work on kanban view

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#14204]
Impacted versions:
[10.0]
Steps to reproduce:

on task kanban

click "edit Task" in the small dropdown button

Current behavior:

open task form, in read-mode

Expected behavior:

open task form in edit mode

Video/Screenshot link (optional):

**Comment by qsm-odoo** [comment]
The issue has been fixed in saas-11 with commit https://github.com/odoo/odoo/commit/2e0a30001691eb8608b99881c9cee3d2073d9373. It will be forward-ported for 10.0 in the upcoming days.
