### ISSUE TITLE
POS duplicating ticket sequence

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#14214]
**Impacted versions:**
9.0 (Test not done on others)

**Steps to reproduce:**
1 - Open a POS session
2- Put X quantity of products on the order
3- Go to payment and pay
4- Click **Validate**
5- Print the Receipt
6- **_Do not_** click _Next Order_
7- Close the POS session.
8- Open it again

> Here, the order from the last closed session will still be open and it will be editable

9- Add more products to the Order
8 - Repeat from step 3 to 9 as much as you like.

**Current behavior:**
The last order is Open, I can edit it and change it. Then print it, and it will have the same number in the ticket. I can repeat the steps above as many times as I want. 

This  causes a lot of awkwards situations, including fraud, as a seller can print a lot of receipts (as if a sell was done, when its not even being registered in the backend). Then the client can come with his ticket and ask for a refund of things he never paid.

**Expected behavior:**
When **Validate** is clicked, the order must be closed and the sequence must be reserved in the background; this button should the something similar as **Next Order** code, just withouth showing the next order. This way the ticket is sent to the printer just if the order is closed.

**Video/Screenshot link (optional):**
![odoo fraud](https://cloud.githubusercontent.com/assets/16890942/20097700/37f930bc-a586-11e6-8385-26de8c9bd571.png)

**Comment by gustavovalverde** [comment]
This might be related: 
#14151

**Comment by jorenvo** [comment]
Is it possible that your code is outdated? Normally this issue should have been solved a little while ago with https://github.com/odoo/odoo/commit/8e720a9319317217fa39c3be982b41072fcd479a.

If updating the code doesn't fix the problem then let me know and I will reopen the issue.
