### ISSUE TITLE
[10.0] Invoice and sale workflow still being used?

### ISSUE THREAD

**Issue by danimaribeiro** [odoo/odoo#14215]
Steps to reproduce:
I've made a sales order with 10 items, confirmed and invoiced it.

When I run the report for the queries executed, I see a huge number of queries executed against wkf_instance. (632 to be precisely)

Wasn't removed the workflow in sales order and invoice?

![workflow](https://cloud.githubusercontent.com/assets/854781/20098293/3f823f36-a59a-11e6-9132-800732a4583d.png)

**Comment by Yenthe666** [comment]
Hi @danimaribeiro,

Workflows have been fully removed in Odoo yes, they're not used anymore. As for the queries: I guess they where still triggered somewhere along the line by the ORM.

Regards,
Yenthe
