### ISSUE TITLE
Unable to join to a course due to js error: slide.course.join.popupContent' contains multiple root nodes ...

### ISSUE THREAD

**Issue by ssaid** [odoo/odoo#142109]
Impacted versions: 17.0

Steps to reproduce: Go to runbot -> odoo 17.0 -> go to courses -> enter basics of gardening -> click on join the course

Current behavior: 
```UncaughtPromiseError
Uncaught Promise > The rendered template 'slide.course.join.popupContent' contains multiple root nodes that will be ignored using renderToElement, you should consider using renderToFragment or refactoring the template.
Error: The rendered template 'slide.course.join.popupContent' contains multiple root nodes that will be ignored using renderToElement, you should consider using renderToFragment or refactoring the template.
    at renderToElement (https://53688330-17-0-all.runbot166.odoo.com/web/assets/1/fe25807/web.assets_frontend_lazy.min.js:5887:472)
    at https://53688330-17-0-all.runbot166.odoo.com/web/assets/1/fe25807/web.assets_frontend_lazy.min.js:7921:477
```

Expected behavior: Be joined to the course (if i create an account and then i join to the course there are not problems)

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/9728965/aff50f23-dbd9-46e3-bdab-deb242f6dd3b)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @ssaid 
Thanks for reporting. This was fixed with https://github.com/odoo/odoo/pull/143280
Cheers
