### ISSUE TITLE
Update UBL / XRechnung "Specification identifier" (BT-24)  to current Version "2.3.1"

### ISSUE THREAD

**Issue by teha75** [odoo/odoo#142127]
Impacted versions: 16.x

Steps to reproduce: create UBL Invoice (German XRechnung) and validate it against current standard e.g. here https://erechnungsvalidator.service-bw.de

Current behavior: A Warning ist shown because odoo produces a "xrechnung_2.2" XML and since August 2023 the "2.3.1" Version of the standard is recommended. 

Expected behavior: update the UBL module so that a fully compliant invoice is created

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
@smetl @qdp-odoo FYI

**Comment by smetl** [comment]
@JulienVR Can you have a look plz?

**Comment by JulienVR** [comment]
I opened a PR to fix this: https://github.com/odoo/odoo/pull/142374

**Comment by vava-odoo** [comment]
Thanks for reporting @teha75 
Solved with https://github.com/odoo/odoo/pull/142374, forward-ported to all supported versions.
Cheers!
