### ISSUE TITLE
Deduplicating by email/name/vat is error prone

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#14239]
Impacted versions: v8-10
Steps to reproduce:

While deduplicating contacts by email it includes and partner that have empty emails.

https://github.com/odoo/odoo/blob/10.0/addons/crm/wizard/base_partner_merge.py#L361 Here should be included and statement that `email != ''` too.

**Comment by Yenthe666** [comment]
Hmm this might be risky yes. @mart-e what do you think about this?

**Comment by pedrobaeza** [comment]
I agree that "NOT NULL" value is not valid for varchar fields. We should check for them also for empty values, that is the default value when you assign False.

And this is still happening on v11.

@mart-e can you please check this one?
