### ISSUE TITLE
Database manager should not show incompatible databases

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#14237]
**Impacted versions:**
9.0c possibly others
**Steps to reproduce:**
In a system that has different versions of Odoo, create one database with version A and another with version B, go to /web/database/manager
**Current behavior:**
All the databases are shown, even if the incompatible ones
**Expected behavior:**
Since Odoo can identify whether it can use the database from it's version, it should not show them on the Database Manager
(I can see statements such as:  

> Skipping database X as its base version is not X.

**Comment by bistaray** [comment]
You can also create a separate PostgreSQL user "db9" and "db10" and only the databases created in each version will show.

**Comment by daramousk** [comment]
#14396 Made a pull request on this.
