### ISSUE TITLE
Error when open My Current Timesheet function

### ISSUE THREAD

**Issue by minhyk** [odoo/odoo#14230]
Impacted versions: Odoo 10

Steps to reproduce:
Go to Timesheet menu then click on My Current Timesheet function, the error will appear

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @minhyk,

Thank you for your report.
I've just tested this and I can confirm that this is a bug. Result:
![image](https://cloud.githubusercontent.com/assets/6352350/20133336/75349dea-a667-11e6-9243-639be56fc64c.png)

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@JKE-be simple change in the function 😉

**Comment by minhyk** [comment]
@Yenthe666

**Comment by Yenthe666** [comment]
@minhyk any reason why you've closed this report?

**Comment by minhyk** [comment]
Sorry. I did wrong :) . Thanks for your supporting.

**Comment by JKE-be** [comment]
ok @Icallhimtest will kindly take a look on it asap ;)

**Comment by Icallhimtest** [comment]
fixed in 10.0 at https://github.com/odoo/odoo/commit/5a45ed00facef46c3099400ffe5d6dc9b0c47845
