### ISSUE TITLE
Module's page gone.

### ISSUE THREAD

**Issue by Rasmusvoll** [odoo/odoo#14233]
Impacted versions: 9.0c
Hello i am new to odoo and ran into this problem, hope you can help
I cannot find the module page under settings, i do have developer mode on. Under the Apps page there are no mention of modules either.

Hope you can help
![udklip](https://cloud.githubusercontent.com/assets/11584833/20135321/72476ab0-a66f-11e6-83f3-7053e5bc20e8.PNG)

**Comment by JKE-be** [comment]
Please, use forum for this kind of question ! 

Here, you are on the bug tracker  !

![image](https://cloud.githubusercontent.com/assets/4848797/20135395/951b0b6c-a680-11e6-863d-b469e3da1bc9.png)
