### ISSUE TITLE
Odoo 10E: Limit of Records set in the Action seems to be incorrectly working.

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#14249]
**_Impacted versions:_**
Odoo 10 E

**_Steps to reproduce:_**
BOM, set the limit of records to 2, i.e set limit to 2 in its Action

**_Current behavior:_**
All the records are shown, which is 4 in my case, but data are been displayed only to 2 records.

**_Expected behavior:_**
Should show just 2 records with data.

**_Video/Screenshot link (optional):_**
  
![image](https://cloud.githubusercontent.com/assets/8802906/20167080/10b48988-a73f-11e6-96fa-ab61364fcd26.png)

**Comment by aab-odoo** [comment]
Hello,

The limit isn't set to 2 on your screenshot (see the pager). How did you try to change it?

Regards
