### ISSUE TITLE
APPS stuck in Module Update Loop

### ISSUE THREAD

**Issue by VIPKaiser** [odoo/odoo#142495]
Impacted versions: 17.0

Steps to reproduce: 

Apps > Select Filter 'Not Installed' > Click ACTIVATE on 'Task Logs'

Current behavior: 

When clicking APPS the left hand main menu you can never access the APPS. You prompted 'Module Update' Click on Update below to start the process... in a never ending loop.

Expected behavior:

The Apps should show.

Notes: I now realise that this particular module depends on hr_timesheet which requires an enterprise license. However it should not break core application like this and should be allowed to be uninstalled or have a warning or option disabled unless enterprise.

**Comment by vava-odoo** [comment]
Hello @VIPKaiser 

Task logs (hr_timesheet) is a community apps. 
About the problem you raise, Apps view will load as soon as the module and its dependencies are installed.

Cheers
