### ISSUE TITLE
Odoo should apply databases changes when all modules are loaded

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#14240]
Impacted versions:

All

Steps to reproduce:

Start odoo to update all modules.

Current behavior:

It will make changes to tables for each module.. Like reapplying contraint and recreating foreingkeys and possibly other kind of alter table.

Expected behavior:

All modules should be loaded and compile a set of changes that are required to the database. Then apply once what's really needed.

**Comment by llacroix** [comment]
I'm aware that module loading in its current form makes any kind of fix impossible most probably. The problem that I had related to this is that if one module changes a constraint or a foreign key to point to a different model. When updating the module that created the relation in the first place, it will try to add a new foreign key with the old constraint... This in return will raise a constraint error if the ids of the foreign key point to ids that don't exist in the old module relation... This prevent the update to successfully complete even though the data is correct when all modules are actually loaded.

The problem is that we shouldn't expect the database to be consistent when not all modules are loaded. Currently it seems to update the database after each module is loaded. 

What should happen is this:
Load all modules: record database changes
Make database changes.
Update data in order that modules are usually loaded (some data could be excluded if it is changed later in a different module)

**Comment by pedrobaeza** [comment]
As you self-answered, this is barely impossible to be achieved without a heavy refactorization of all the ORM. Some things are in mind for reducing some impact in SQL things like constraints (not making required fields in inherited models), but the general thing is difficult to get it. I will try to speak with framework guys about this in the next time we meet (Odoo experience mostly) to see.

Meanwhile, closing this.
