### ISSUE TITLE
"View sales order" button not showing inside the email sent from odoo

### ISSUE THREAD

**Issue by jaclark083** [odoo/odoo#142435]
Impacted versions: v16

Steps to reproduce:

Current behavior: There should be a button "view sales order" inside the email when u send a quotation to a customer and then the customer can click it and it will show the quotation via web but it isn't showing.

Expected behavior: that the button shows

Video/Screenshot link (optional):
https://drive.google.com/file/d/1RPBEOwEWK1QQXrYFCKhyk24cESY2fbWn/view?usp=drive_link

Support ticket number submitted via odoo.com/help (optional):

**Comment by jaclark083** [comment]
It is in the sales module in v16 odoo

**Comment by vava-odoo** [comment]
Hi @jaclark083 
It looks like the button works perfectly on my side.
Feel free to re-open with steps to reproduce if the issue is still there.
Cheers
