### ISSUE TITLE
[7.0][8.0] multi company addons has too many unnecessary dependency

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#1425]
Module multi-company forces you to install sale_stock and project in order to add some views. That not correct and not enough modular especially regarding new pricing.

Nothing is affected in project it only adds demo data and on sale stock only some inventory view modification are added. 

Logic of the addons should be split in corresponding addons and the demo data should me split accordingly too.

Regards

Nicolas

**Comment by Yenthe666** [comment]
Hi @nbessi,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: A lot changed in 9.0, 10.0 and 11.0 so I assume this is now better 😉 

Regards,
Yenthe
