### ISSUE TITLE
error in importing Odoo standard "base import module" 

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14254]
Impacted versions:
10

Steps to reproduce:

Current behavior:
short dump corrupted the whole system
Uncaught TypeError: Cannot read property 'widgets' of undefined

Expected behavior:

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Missing info to reproduce

**Comment by ccandito** [comment]
I've created another issue with more details
Regards
claudio candito
