### ISSUE TITLE
[master][web] Proposal: ES npm module loader

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#14258]
Hi @ged-odoo, we are planning to create a module loader based on npm. Our proposal is to include this functionality in Odoo CE master, in `web` addon, if it is of your interest. Otherwise we will do it in an external addon by ourselves.

**Our main goal is to stop adding the source code of external libraries in addons**. This can lead to an awful amount of code that you really don't need. For instance, you have a 50k+ lines PR here https://github.com/OCA/web/pull/281, that would become a lot easier to maintain without all the source code of the library. Yes, I know you're not @OCA, but this would probably benefit everybody.

The same way as we use `pip` for including python dependencies instead of copying their sources/binaries, we can make the same with `npm` for the other main logic language that is currently used in Odoo: ES.

# Details

## Using it in submodules

We will assume you add a module called `my_old`, that depends on Backbone 1.0.0, and another one called `my_new` that depends on Backbone 1.3.0. Both depend on `web` and want to do some fancy JS things.

### How to add a dependency to your addon

For example, for `my_new`:

```
<record id="backbone" model="web.library">
  <field name="name">backbone-1.3.0</field>
  <field name="location">assets_frontend</field>
  <field name="amd" eval="False"/>
</record>
```

### How to use that dependency in your addon

In your ES module, you'd do this:

#### Async mode

```
odoo.define(`my_new`, function(require) {
  var dependency = require("web.library");
  dependency.load_async("my_new.backbone") // XMLID of the dependency you declared
  .done(function(Backbone) {
    Backbone.Model.extend({...
```

#### Sync mode

```
odoo.define(`my_new`, function(require) {
  var Backbone = require("web.library").load_sync("my_new.backbone");
  Backbone.Model.extend({...
```

#### `web.library`

Fields:

- name: name of the library and its version, i.e. `backbone-1.3.0`.
- amd: Indicate if the addon is an AMD module, it will require a [shim configuration](http://requirejs.org/docs/api.html#config-shim) if it is not. I still have to define the way to add this, this is not defined 100% in this blueprint.
- location: any of `assets_frontend`, `assets_backend`, `assets_common`, `assets_editor`, etc.
- source_id: m20 to web.library.source with the same name. delete=cascade.

#### `web.library.source`

Fields:

- name: same as in `web.library`.
- minified: minified source for this addon.
- library_ids: counterpart to `web.library.source_id`.

### Behavior

When you declare a new dependency in your submodule, if it exists already in `web.library.source`, its `source_id` field gets filled. Otherwise, npm is used to download the minified source for the library and a new `web.library.source` record is created and linked to that `web.library` one.

Then the `web.library` JS module (the one you get from `require("web.library")` will expose those 2 methods to load in sync or async mode; sync returns the namespace for the library, while async returns a promise that resolves with that namespace as an argument.

Both loading methods ask the backend by XMLRPC to get the `minified` field from its `web.library.source` related record, which gets cached to avoid repeated loads for the same library if declared in more than one addon.

Since all libraries get namespaced, then no conflicts would happen in case different addons require the same library in different versions, like `my_new` and `my_old` do. Obviously AMD libraries would be much easier with that, but the shim config would make all of them work.

Any thoughts? :blush: 

@Tecnativa

**Comment by ged-odoo** [comment]
Dear @Yajo,

Thank you for your proposition.  I already tried to integrate npm with odoo, but I didn't find a nice way to do it, and it looks like you have a pretty good idea on how to do it.

But before going into specifics, I'll tell you my (personal) opinion: I like it, but I expect that the higher-ups will not approve such changes (when something kind of works, we are really opposed to change, for some reason).

Here is what I like:
- library code stays out of addons (I suppose that they will all be in /node_modules/, right?)
- we don't bundle libraries in repo => smaller "code size", and better diffs
- nice integration with the JS side, via the module 'web.library'
- it solves a problem we have sometimes: two different unrelated addons that needs the same library. In that case, we can either package two versions of the library, or put the library in a 'common' addon, such as 'web'.  Both solution sucks
- it allows us to serve minified files 


Not sure about this:
- library name and version in same field => why not an extra "version" field?
- load_sync: I assume that this will do a synchronous rpc, which will block the js engine.  Seems like a bad idea to do it in the root of a js addon, and if it is needed in a odoo widget, there is the method willStart
- need more details on how it would integrate with the bundle system.

Also, and this is a more generic comment, but I personally am not really happy with our "bundle system", for various reasons, but I did not really think about what the best alternative would look like.  Maybe this proposition will help me.


I will need to talk about this with al, and I'll come back to this issue when I have more feedback.  Feel free to add more comments if you can think of anything.

**Comment by Yajo** [comment]
Hi, thanks for your comments. About some of your points:

> library code stays out of addons (I suppose that they will all be in /node_modules/, right?)

I was thinking more in saving the minified source inside the `minified` field of `web.library.source` records. The main reason is that we'd need Odoo to have write access to a folder to execute npm behind the scenes, but I think that if we just trigger that in a [`@api.onwrite`](https://github.com/odoo/odoo/pull/11042) (I abuse this chance to promote that PR :laughing:) or equivalent, at the end we just need a minified chunk of letters to spit out to the browser, and then we could use a temporary folder for npm and delete all garbage when finished.

All of this departs from the point that we don't always have write access to the addons path.

Another option would be to store npm things in the filestore, somewhere, or to have `web.library` point to several `ir.attachment` records, containing the sources.

By speaking on this, I'm starting to think that some external libraries might include CSS/Less/Sass, so maybe we need also a `type` field into `web.library.source` or whatever implementation we choose. :open_mouth:

Or maybe you prefer to leverage the current assets bundling facility in Odoo, somehow combining it with this implementation, maybe by using an additional controller for this. We could require devs to add something like this in their addons to include the libraries:

```
<template id="assets_frontend" inherit_id="website.assets_frontend">
    <xpath expr=".">
        <link rel="stylesheet"
              href="/web/library/bootstrap-4.0.0.scss"/>
        <script type="text/javascript"
                src="/web/library/bootstrap-4.0.0.js"/>
    </xpath>
</template>
```

> - library name and version in same field => why not an extra "version" field?

I like the idea, as long as both fields are required and form a combined unique key.

> - load_sync: I assume that this will do a synchronous rpc, which will block the js engine. Seems like a bad idea to do it in the root of a js addon, and if it is needed in a odoo widget, there is the method willStart
> - need more details on how it would integrate with the bundle system.

I did not know about `willStart`, but it is not a bad idea. Maybe we could implement somehting like that, but not just for widgets, but for Odoo modules in general.

I know [currently Odoo does black magic to make those `var core = require("web.core");` lines become async](https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/boot.js#L103-L105), but code actually looks sync. To make plain evident that it is async, it should be something like:

```
$.when(require("web.core"), require("web.Model")).done(function(core, Model) {
   _t = core._t;
   new Model(.......
```

... but I guess you did not want devs to write those things, just to avoid confusion for people that are more used to sequential coding. If then we add the external libraries in a plain async way, we'd be confusing new devs, like "why is this sync and this another is async and I need to use promises in one place and not in the other?".

So, to allow pro JS devs to use async but let newbies still write sequential code, I think providing both methods would be best.

Of course my main idea comes from the assumption Odoo would reject this and I'd need to use an external module loader like RequireJS to do this stuff, but now that I have your attention, if we bundle this into core, we could extend current module system to the special external library case. Or maybe it's time to start using something like RequireJS directly into Odoo and start teaching our JS devs how to define AMD modules instead of mocking them about how this works behind the scenes... Not sure, I guess you are more expert than me in this regard, and have a cleaner vision on what does Odoo really want to achieve in the JS world, so I'd appreciate your thoughts on this.

As a side, more personal, note, I think you agree with me in the point that current JS usage in Odoo is very... let's say _old fashioned_. I'm not saying we have to follow all trends in this regard, [because they tend to change every 2 weeks :laughing:](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f), but I think embracing modern standards (you know, ES2016+, (which [includes module loading](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and [async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/async_function)-[await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await), BTW), [allowing metalanguages like Babel, CS, TS, etc.](https://github.com/odoo/odoo/issues/13710#issuecomment-252575830)) would make it a more interesting platform for the growing ES community, and as a side effect, this would ease the task at hand in this issue. Maybe I'm simply daydreaming :see_no_evil:.

**Comment by ged-odoo** [comment]
On the location of minified code: 
yep, you are right, it sounds better

On new controller for web/library:
worth thinking about it...  makes it kind of simple, but extra complexity with some magic. not really sure

On async modules:
the black magic you mention is only to fetch the dependencies (also, note that this is the same regexp used by requirejs). The module system makes sure the dependencies are fetched before actually loading the current module.   Another idea may be to add an extra argument in the module system, something like
odoo.define('mymodule', function(require, requireLibrary) {
  var something = require('web.something');

 var Backbone = requireLibrary('Backbone');
...
});

In this situation, the code would still stay synchronous, but the module system would guarantee that the library was loaded. Downside is that it is such a low level change that it needs to be done in web addon.

Anyway, our module system is indeed a custom one, trying to solve a problem that has already been solved by other more mature solutions with more support.  The only point in favor of a custom system is that we have a product where addons change stuff 'from the outside', and we need to be able to change the bundles dynamically.  So, on that regard, Odoo is more complex than most 'simple' project.

Also, on a personal note, you are talking about a topic I really love: JS in general and in Odoo.  I really wish we (internally) would have a serious discussion about that topic, but sadly, it looks like most people here behave like everything is fine and dandy.  I would love to find a way to modernize our JS framework (and we are actually working on it, currently on the sad mess that are the views).  If this is a topic that interests you, I suggest that you open an issue and rant a little bit on it.  Also, ping me so I can add my opinions.  Maybe it will help shift some opinions here.

Finally, two last points: 
- our JS team in Odoo is not really big, and is quite busy with two large projects, so things cannot move quickly for the next few months.  
- you are right that this will still most likely be rejected, I just hope that this discussion will steer us in a better direction in the future.

**Comment by Yajo** [comment]
>  The only point in favor of a custom system is that we have a product where addons change stuff 'from the outside', and we need to be able to change the bundles dynamically. So, on that regard, Odoo is more complex than most 'simple' project.

I understand you are talking about the things a module exports, that can be modified by another module. AFAIK that's the common notion of an `exports` in any module system, so not really a conflict here (if I understood).

> Another idea may be to add an extra argument in the module system

I think we could simply drop all that regexp stuff if we declared addons like this:

```
odoo.define(
  "module.name",
  ["web.core", "web.Model"], // Odoo modules
  ["jQuery-1.0.0", "Backbone-1.0.0"], // External libraries
  function(core, Model, $, Backbone) { // Method executed when those load
   ...
})
```

> we are actually working on it, currently on the sad mess that are the views

Many thanks for that! I'm wishing that since v8 :blush: 

> our JS team in Odoo is not really big, and is quite busy with two large projects, so things cannot move quickly for the next few months.

I personally am not going to be able to dig into this until about a month from now, but my proposal includes an offer to do the dirty job and let your team simply review & merge. I'd backport that for v9+ under @OCA.

In such case, I'd like some clear theory guidelines on implementation before starting, and a confirmation that merge is actually "possible" (I know it fights with that Odoo mindset) before starting. Otherwise I'll do this in an @OCA addon probably, but I think it is more interesting as an upstream improvement.

>  I would love to find a way to modernize our JS framework (and we are actually working on it, currently on the sad mess that are the views). If this is a topic that interests you, I suggest that you open an issue and rant a little bit on it. Also, ping me so I can add my opinions. Maybe it will help shift some opinions here.

I'll do, let's see if it helps :wink:

**Comment by ged-odoo** [comment]
for the record, 

odoo.define(
  "module.name",
  ["web.core", "web.Model"], // Odoo modules
  ["jQuery-1.0.0", "Backbone-1.0.0"], // External libraries
  function(core, Model, $, Backbone) { // Method executed when those load
   ...
})

already works (at least the odoo modules part).

I'll get back to this issue later, after some internal discussions.  Don't hesitate to ping me if this rots for too long

**Comment by ged-odoo** [comment]
well, the discussion was not really long... 

This proposition cannot be accepted.  This is not something we want to do. So, I have to close this. Sorry

Thank you anyway for trying.

**Comment by Yajo** [comment]
Thanks for your attention, I guess we'll need to do this for @OCA then :disappointed:
