### ISSUE TITLE
[10e] Error invoicing PO with multi currency 

### ISSUE THREAD

**Issue by abdallamohamed1992** [odoo/odoo#14257]
Impacted versions:
10c

Steps to reproduce:
Create vendor invoice from PO with USD and company currency EUR
 
Current behavior:
Odoo appear EUR when invoice PO

Expected behavior:
Invoice should appear USD instead of EUR

**Comment by augustosamame** [comment]
+1

**Comment by csnauwaert** [comment]
Hello,

This has been fixed and improved in master at rev: https://github.com/odoo/odoo/commit/03b8c10262076d717f5d8db2dd8b125a3ffac34f

Therefore I'm closing this issue.

Best regards
