### ISSUE TITLE
[16.0] The community version has a module with an enterprise license

### ISSUE THREAD

**Issue by vlyubimov** [odoo/odoo#142518]
Impacted versions:
16.0
Steps to reproduce:
Search for 
'license' files: 'OEEL-1' 
in the community version

Current behavior:
In the community version there is a module with an enterprise license

# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Poland - JPK_VAT Community',
    'version': '1.0',
    'description': """
        All the fields needed for the JPK_VAT Export in Poland are available in Community
    """,
    'category': 'Accounting/Localizations/Reporting',
    'depends': [
        'l10n_pl',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/l10n_pl_tax_office.csv',
        'views/account_move_views.xml',
        'views/product_views.xml',
        'views/report_invoice.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
    ],
    'auto_install': True,
    'installable': True,
    'website': 'https://www.odoo.com/app/accounting',
    'license': 'OEEL-1',
}

I would also like to clarify what is the way to make sure that the project does not use modules from Enterprise?
The idea is to write a test that will check the ir_module_module table to see if it contains entries with the 'OEEL-1' license

Thanks in advance for your answer!

**Comment by vava-odoo** [comment]
Hi @vlyubimov 
Thanks for reporting. @gawa-odoo could you have a look?
Cheers

**Comment by gawa-odoo** [comment]
Hello!
Thanks for the report!
Fixed in https://github.com/odoo/odoo/pull/147941
