### ISSUE TITLE
Odoo v17: POS Invoice

### ISSUE THREAD

**Issue by muhammadfaizalns** [odoo/odoo#142646]
Impacted versions: `17.0`

Steps to reproduce:

Begin by installing the `l10n_sa_pos` module in your system. Once the module is installed, create a standard Point of Sale (POS) order using your POS system. This typically involves selecting products, adding them to the order, and configuring any relevant details such as quantities and discounts. You can just navigate through the POS order creation process until you reach the final stage where the payment is made. This may involve selecting a payment method, entering payment details, and confirming the transaction. After the payment is made, the system typically generates an invoice preview screen. This screen summarizes the transaction, including details such as items purchased, quantities, prices, and the total amount due. At this point, you have identified an issue where, during the final stage of making the payment, the invoice preview screen goes blank and displays a white screen. This behavior indicates a potential problem in the system's processing or rendering of the invoice preview.

Current behavior:

During the final stage of making the payment, the invoice preview screen goes blank and displays a white screen.

Expected behavior:

During the final stage of making the payment, the invoice preview screen should show the preview of the invoices and the user could able to go to the next order after the actions.

Video/Screenshot link (optional):

[Screencast from 20-11-23 01:02:31 PM +03.webm](https://github.com/odoo/odoo/assets/48276007/5814af79-c318-432c-8401-2d91c1f04c7a)

Support ticket number submitted via odoo.com/help (optional):

`#3604447`

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/odoo/pull/142510
