### ISSUE TITLE
Daterange widget "UncaughtPromiseError > OwlError" in 17.0

### ISSUE THREAD

**Issue by jefftamcw** [odoo/odoo#142658]
Impacted versions: 
17.0

Steps to reproduce: 
Open any form view and click a field with daterange widget (example with calendar.event)

Current behavior:
UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'DateTimePickerPopover': 'pickerProps' doesn't have the correct shape ('range' is not a boolean)

**Comment by ppr-odoo** [comment]
Hello @jefftamcw  this issue will be fixed in this  [PR](https://github.com/odoo/odoo/pull/135735/files) Thanks
