### ISSUE TITLE
[10.0] No options for Advanced Calls for Tenders

### ISSUE THREAD

**Issue by sajadkk** [odoo/odoo#14260]
**Impacted versions:** 
10.0

**Steps to reproduce:**
go into the _Purchases_ module, open the _Configuration_ menu and click on _Settings_.

**Current behavior:**
No options for 'Advanced Calls for Tenders'

**Expected behavior:**
There should be an option for 'Advanced Calls for Tenders'
![partial_purchase01](https://cloud.githubusercontent.com/assets/1268273/20176093/91daca5c-a75f-11e6-9df3-335cbe26b11e.png)

**Comment by Yenthe666** [comment]
@sajadkk this is working fine in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/34881008-9609d510-f7b2-11e7-963b-325e0225b398.png)
