### ISSUE TITLE
MRP Issue with Serial Numbers

### ISSUE THREAD

**Issue by Smart-IT-Kirkham** [odoo/odoo#14278]
Impacted versions:
Odoo 9 and 10

Steps to reproduce:
Turn on serial numbers
Create Product A with components 1 and 2. 
Components one and two are stockable with unique serial number.
Create Product A which is stockable with unique serial number and manufactured.
Associate a BOM with Product A which has one component 1 and one component 2 in.
Purchase in 2 each of component 1 and 2. Each will have a unique serial number. e.g. Component 1 - 0001, Component 1 - 0002, Component 2 - 0001, Component 2 - 0002.
Manufacture 1 of Product A, serial number Product A - 0001. Using Component 1 - 0001 and Component 2 - 0001.
Create a sales order for Component 1.
Select which lot to go out on the delivery order. 
Remove Component 1 - 0002.
Add Component 1 - 0001.
Validate.
You have now shipped out the none existent Component 1 - 0001 which is sat inside Product A.

Current behavior:
You are able to SELL components that are currently sat inside fully built items.

Expected behavior:
Lots that have no items available, either because they are built up into actual items like engines/computers, or as i've just thought may be empty?(because they have been sold) etc should not be select able!  System should either say lot is empty cannot use or not display them.
 
Video/Screenshot link (optional):
See screen shots of the manufacturing order, trace ability and the delivery order telling me to take the item out of lot Component 1 - 0001  (currently sat inside Product A)!

![image](https://cloud.githubusercontent.com/assets/14975616/20222013/a6b1b266-a82b-11e6-8604-cf093d2bcf5c.png)

![image](https://cloud.githubusercontent.com/assets/14975616/20221975/7f82badc-a82b-11e6-9559-0d01f11a8dcf.png)

![image](https://cloud.githubusercontent.com/assets/14975616/20222050/cfd4f34c-a82b-11e6-9a0b-9fd4a1d51a6e.png)

**Comment by Smart-IT-Kirkham** [comment]
Hi all,
Any updates on this?

**Comment by pedrobaeza** [comment]
You are mixing manufacturing with your real concern that is to deliver some products with lots. Any way, this is inherent to the design of the picking, where you can put the lot you want. If you don't want this behavior, just let the system to assign things or make sure there is enough material.

Closing as this is the normal behavior.
