### ISSUE TITLE
NEW API: Call to invalidate_cache breaks computed and related fields + onchange

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#14275]
## Impacted versions:
 8.0 / 9.0 / 10.0
## Steps to reproduce:
* see https://github.com/odoo/odoo/issues/11841
* in a shell
  1. create an in memory record `order = self.env['purcahse.order'].new({....})`
  2. create an in memory record with a reference to the first one `order_line = self.env['purchase.order.line'].new({'order_id': order, ....})`
  3. order_line.order_id is an in memory recordset
  4. create a record for a model that inherits from mail.thread `self.env['product.product'].create({....})`
  5. At this stage order_line.order_id is an empty recordset

## Current behavior:
 In memory records are dropped when a call is done to self.invalidate_cache
## Expected behavior:
In memory records are preserved when a call is done to self.invalidate_cache

There are lot of places where the method `invalidate_cache` is called and the silent removal of the in memory records from all environments has unpredictable effects on fields modified by a computed method or an onchange or even related fields .... Moreover since all caches are invalidated each time you create / write / unlink  (https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_followers.py#L111) an instance of a model that inherits from 'mail.thread', the performances of the server are severely penalized.

OPW703903

**Comment by lmignon** [comment]
IMO it's a major issue. @rco-odoo @odony

**Comment by Yenthe666** [comment]
@mart-e pinging you for this one too.

**Comment by rco-odoo** [comment]
@lmignon I will try to make all those calls to `invalidate_cache` more specific (invalidate some fields/records only).

**Comment by lmignon** [comment]
@rco-odoo Thank you for taking care of this one. It's really an annoying bug.

**Comment by rco-odoo** [comment]
It just has been fixed in 8.0, and the fix will be forward-ported to 9.0 and 10.0 soon.
