### ISSUE TITLE
[10.0] Field compute is re-calculated with store=True when opening the sending mail invoice Wizard

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#14279]
Impacted versions:
10.0

Steps to reproduce:
- create a computed field into `account.invoice` model:
```python
class AccountInvoice(models.Model):
    _inherit = 'account.invoice'
    report_name = fields.Char(compute='_compute_report_name', store=True)

    @api.depends('state')
    def _compute_report_name(self):
        for record in self:
            record.report_name = 'dummy_%s' % record.id
```
- Then, modify the report `account.account_invoices` in `ir.actions.report.xml` in order to set new expresion :
`attachment="(object.state in ('open','paid')) and '%s.pdf' % object.report_name"`
The report will generate an attachment with that expresion
 ```xml
<report
    id="account.account_invoices"
    model="account.invoice"
    string="Invoices"
    report_type="qweb-pdf"
    name="account.report_invoice"
    file="account.report_invoice"
    attachment_use="True"
    attachment="(object.state in ('open','paid')) and '%s.pdf' % object.report_name"
        />
```

With the above changes at the moment the invoice is validated, `report_name` field will take its value

Finaly open the sendig mail invoice wizard
![image](https://cloud.githubusercontent.com/assets/10233975/20225628/fd9dde0a-a809-11e6-9951-37da50e905fa.png)

Current behavior:

**At the moment to opening the wizard, the `report_name` field is recomputed**
Expected behavior:
Load the wizard and report attachment without recomputing any computed field, and instead of recompute the field, read the value from database:

Additional information:
While debugging I found the next clue:
```python
  /root/odoo-10.0/addons/mail/wizard/mail_compose_message.py(362)onchange_template_id()
-> values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  /root/odoo-10.0/addons/mail/wizard/mail_compose_message.py(499)generate_email_for_composer()
-> template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  /root/odoo-10.0/addons/mail/models/mail_template.py(494)generate_email()
-> report_name = self.render_template(template.report_name, template.model, res_id)
  /root/odoo-10.0/addons/mail/models/mail_template.py(360)render_template()
-> render_result = template.render(variables)
  /usr/local/lib/python2.7/dist-packages/jinja2/environment.py(986)render()
-> return concat(self.root_render_func(self.new_context(vars)))
  <template>(8)root()
  /usr/local/lib/python2.7/dist-packages/jinja2/sandbox.py(329)getattr()
-> value = getattr(obj, attribute)
  /.repo_requirements/odoo/odoo/fields.py(868)__get__()
-> self.determine_value(record)
  /.repo_requirements/odoo/odoo/fields.py(979)determine_value()
-> self.compute_value(recs)
  /.repo_requirements/odoo/odoo/fields.py(934)compute_value()
-> self._compute_value(records)
  /.repo_requirements/odoo/odoo/fields.py(926)_compute_value()
-> getattr(records, self.compute)()
> /root/build/Vauxoo/my_repo/my_module/models/account_invoice.py(505)_compute_report_name()
-> for invoice in self:
(Pdb) 
```

Apparently the jinja2 is the problem, trying to get the value, and ignoring the store=True of the field
![image](https://cloud.githubusercontent.com/assets/10233975/20225965/ac393490-a80b-11e6-85bb-6464fb07c0d8.png)

**Comment by pedrobaeza** [comment]
This is inherent on how the ORM works. Continuous improvements are done over the ORM layer for optimizing the number of queries, but the most important is to have a reliable value, so this can be an effect of that.

Closing as no real issue more than the possibility of optimization without side effects, which is continuously evaluated.

**Comment by yostashiro** [comment]
Had a corner-case issue due to this behavior and I had to turn a stored computed field into a non-computed field: https://github.com/rfhk/cip-custom/pull/119
