### ISSUE TITLE
Standard_price field in the product is updated when real price is used

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#14276]
Impacted versions: 8, 9, 10

Steps to reproduce: 
As an example, you have a cost (standard_price)  of 100 EUR in the product record. 
1. You buy 10 units at 100 EUR.  standard price remains at 100 EUR
2. You buy 10 units at 50 EUR, Standard price remains at 100 EUR 
3. You sell 15 units, so it takes 10 units at 100 EUR (First quant) and 5 units at 50 EUR (second quant). At this stage the standard price is updated to 83,33 EUR 

Current behavior: The systema updates standard_price when the cost method is real_price

Expected behavior: The system should not update standard_price when the cost_method is real price, it should only update it when average cost is used.

I don´t find any advantage of updating this field at delivery. In fact, the figures are wrong, in the example it shows 5 units at 83.33 EUR each, when the real valuation at real price is 5 units at 50 EUR each. 

Video/Screenshot link (optional):

**Comment by elevationO** [comment]
I am impacted by this as well.  Not using the actual quant value is causing problems across the system for us.  Most recently Odoo is using the avg when allocating a landed cost by value.

https://github.com/odoo/odoo/issues/13696

**Comment by pedrobaeza** [comment]
See https://github.com/odoo/odoo/issues/17503#issuecomment-363488222 for an answer on this.
