### ISSUE TITLE
Apparent float issue keeps POS order from validating

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#14284]
#### Impacted versions:
27413fe

#### Description:
The issue apparently (see debugging screenshot) goes around the machine arithmetic floating limitations as https://docs.python.org/2/tutorial/floatingpoint.html
##### The culprit line seems to be:  
https://github.com/odoo/odoo/blob/7bb6b329271c20404c706224d4a1e3414038c0ae/addons/point_of_sale/models/pos_order.py#L376 (here taken from version 10.0) - this becomes kind of evident reading the above linked limitations on floats and looking at the screenshot.

#### Steps to reproduce:
I guess: Pipe any number through the culprit line that does imply an approximate result in the float arithmetic, such as a `0.1 + 0.2`

![image](https://cloud.githubusercontent.com/assets/7548295/20238208/18a227a6-a8b4-11e6-9eb1-05a942606c52.png)

The base values to the screenshot values oddly did not reproduce the flaw when executed in the debugging environment:
![image](https://cloud.githubusercontent.com/assets/7548295/20238257/050843d2-a8b5-11e6-8b07-a8d75cb11399.png)

**Comment by blaggacao** [comment]
@mart-e beeing you the last one who touched this line in 9.0, although I guess this is present already way back. This instance is on google compute hardware, I don't know their floating point arithmetics, put as we can see in my local debugging session it's not reproducible. In any case the line `order.amount_total = order.amount_tax + amount_untaxed` is a floating point time bomb and it seems it has just exploded in our instances... 😄

**Comment by mart-e** [comment]
Hello,

Sorry but what is the bug exactly? I mean, is there somewhere a wrong behaviour for the customer?
What you show me is floating points approximations for the developer but the solution is usually to use methods as `float_compare` in the code.

**Comment by blaggacao** [comment]
@mart-e I'm sorry for my faulty communication. This goes quite deep down the stack (and brain)... 😄 

The problem occurs when a client-side properly closed POS order is replicatad falsely (as depicted above) server side. The pos session cannot be closed as infected orders cannot be validated. I guess because as there is a real difference at some floating point position, this explodes somwhere arround https://github.com/odoo/odoo/blob/e91ecc89de782ff0d37f43b38acf82852d93e2ef/addons/account/models/account_bank_statement.py#L380, which on manual validation attempts effectively rose.

**Comment by mart-e** [comment]
Thanks for the precision. Indeed, checking `== 0` may be an issue for some floats.
If you have a scenario when you can reproduce this issue, I can accept a patch changing the compare to `float_is_zero`.

**Comment by blaggacao** [comment]
@mart-e Ui, that's quite something you are asking for in this context. The problem is I could not even replicate it on the same infrastructure (google cloud) after a timely limited occurrence. I suppose they temporarily switched to another hardware with different floating point arithmetic (legacy processing power in peak hours?)... So this would end up looking fo a hardware with floating point arithmetics where this fails... Wouldn't a patch be sufficiently harmless to validate a preemptive measure?

**Comment by mart-e** [comment]
Well, a patch like 4cfe3e0178db470344054ff503f492a6964b6c5b (not merged) could theoretically do the trick but this line is there for 1.5 year so my guess is that it is not so frequent issue. Also maybe changing this line is not enough or the rounding could be fixed more efficiently somewhere else.
I am not very keen about merging patches for theoretical issues without being able to make sure it actually fixes a bug.
I hope you see my point.
I don't think the hardware really matters for the python floating issues. Sending a copy of a db with the issue is fine for me too :)

**Comment by blaggacao** [comment]
Ok, that's what I will do! Can you initiate email contact at dar@devco.co? (I guess you not keen to publish your's)

**Comment by blaggacao** [comment]
Quite right to question my analysis, I digged into it again, and it seems the issue comes from the currency round.
![image](https://cloud.githubusercontent.com/assets/7548295/20938815/7498916c-bbba-11e6-8b0e-993bd7e52280.png)

And here is the ultimate proof on `float_round`:
![image](https://cloud.githubusercontent.com/assets/7548295/20938843/8f8b6166-bbba-11e6-9d0d-095cf91ffc65.png)

**Comment by blaggacao** [comment]
I'm preparing the database today and will send it to you.

**Comment by blaggacao** [comment]
I haven't seen this again. I think there has been done some improvements on the floating point issues...
