### ISSUE TITLE
Point of sale receipt printing (preview before print)

### ISSUE THREAD

**Issue by loukrath** [odoo/odoo#142834]
Impacted versions: 17

Steps to reproduce: Process payment after success order -> Validate -> Print receipt -> Pop-up Print preview

Current behavior: It seems like duplicate images to print.

Expected behavior: Should have only one image to print.

Video/Screenshot link (optional):
<img width="1675" alt="image" src="https://github.com/odoo/odoo/assets/6636772/07b2ebb0-37c7-40b1-81fe-c3bb81665d64">

Support ticket number submitted via odoo.com/help (optional): 
#3606889

**Comment by pedrambiria** [comment]
Hello,
Thanks for reporting this issue.
It will be fixed with this commit: https://github.com/odoo/odoo/commit/126e5a835483637255603749d5bab131dfe02cb8
