### ISSUE TITLE
[10.0-sale/account] Taxes should be float in order to fix rendering in reports

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#14280]
Impacted versions: 10.0

Steps to reproduce:
- Setup a company with a currency that has zero decimals
- Print a sale order or an invoice

Current behavior:
- Formatting taxes with currency is not possible

Expected behavior:
- Taxes should be formatted with currency format

**Comment by invitu** [comment]
I did a PR #14282

**Comment by Yenthe666** [comment]
@qdp-odoo could you look at this? Is this wanted behaviour?

**Comment by Yenthe666** [comment]
This should have been handled in https://github.com/odoo/odoo/commit/f47b3543ee50e64f155c9dec655c624a4b084c6f
