### ISSUE TITLE
[8.0] Many2many record selection loose for previous page

### ISSUE THREAD

**Issue by krupesh10** [odoo/odoo#14292]
Impacted versions: 8.0

Steps to reproduce: Open m2m field in popup and select(tick) few records from first page of m2m and then goto next page of m2m field records and again select some records from second page when you hit select button the only record added to the m2m which are on second page it will not add selected records from the first page.

Current behavior: Only add selected records which are on current page. 

Expected behavior: Also able to add all the records which are selected on any page when we click on select button.

Video/Screenshot link (optional):
![selection_014](https://cloud.githubusercontent.com/assets/21057089/20262369/f2b73812-aa87-11e6-820d-d5c29833249a.png)

@Yenthe666 @fpodoo @msh-odoo

**Comment by Yenthe666** [comment]
Hi @krupesh10,

Thanks a lot for your report. I agree that this would be a neat improvement but I wouldn't label it as a bug.
@mart-e I've labelled this wishlist. What do you think about it? It might get confusing for exporting if you don't get records from the previous 'page'.

**Comment by mart-e** [comment]
Due to the fact that you can modify the number of displayed record from 80 to unlimited, yes I don't consider this as a bug.
Also we won't be modifying this in 8.0. Please check in version 10 where the web client has changed quite a bit under the hood.
