### ISSUE TITLE
neither products nor activities can be added in MO

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14302]
Impacted versions:
10
Steps to reproduce:
create a MO 
Current behavior:
it is not possible to add/remove products from the list of consumption material
it is not possible to add/remove activities (Work Orders) 

in this way the MO has to be as planned in BOM and Routing without any chance to change it

Expected behavior:
flexibility to modify MO in both materials and activities

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
No, that's not possible by design. You should modify the BoM/routing and recompute. You can modify quantities though.
