### ISSUE TITLE
cancelled WOs haven't be displayed in planning by workcenter GANTT report

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14305]
Impacted versions:
10
Steps to reproduce:
cancel MO and its related WO

Current behavior:
the GANTT planning by workcenter displaying the WO cancelled

Expected behavior:
no cancelled WOs should be taken into account in planning by workcenter GANTT report

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As this is something related to an enterprise module, please open the corresponding OPW ticket for this.
