### ISSUE TITLE
&nbsp; shown in email preview on mobile phone and other email client previews

### ISSUE THREAD

**Issue by MrMacca** [odoo/odoo#143188]
Impacted versions: 16.4

Steps to reproduce:
Send a Sales Order or a quotation using the default template and observe the email notification on a phone or desktop
Current behavior:
An &nbsp; is displayed in the email preview notification on multiple types of email client across different devices. Tested on iPhone (iOS, Gmail and Outlook clients) and Macbook (iOS) Outlook client

Expected behavior:
&nbsp is not displayed

Video/Screenshot link (optional):
![WhatsApp Image 2023-11-22 at 11 57 27](https://github.com/odoo/odoo/assets/79686209/6dc47ed1-666c-4e31-9284-eaacb8917650)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/odoo/commit/0a0cbe90413f1fcb32f6e12c73b47ab78a5e86aa
