### ISSUE TITLE
Bugs in many reports : measures

### ISSUE THREAD

**Issue by Yakulu** [odoo/odoo#14316]
**Impacted versions**: 10.0 CE

**Steps to reproduce**: Just use standard community version reports and default filters

**Current behavior**: When you choose filters, measures never change

**Expected behavior**: Measures should follow defined measures in context

Here is [an example](https://github.com/odoo/odoo/blob/11812b0b9e82b2b1b9041d8250ce01e7b4a5f7ee/addons/purchase/report/purchase_report_views.xml#L34) of a defined filter. As you can see :

` <field name="context">{'group_by': ['category_id'], 'col_group_by': ['date_order:month'], 'measures': ['unit_quantity']}</field>`

**Proposed solution** : After the JavaScript source code for pivot views, I guess the right context key should be `pivot_measures` instead of `measures` :

 `<field name="context">{'group_by': ['category_id'], 'col_group_by': ['date_order:month'], 'pivot_measures': ['unit_quantity']}</field>`

I can create a PR if needed, but not before a few days.

**Comment by Yenthe666** [comment]
Should be handled at https://github.com/odoo/odoo/commit/d88dcde4f055ff3e89d4440f53ea1f36d9817b6d

**Comment by Yakulu** [comment]
You're right @Yenthe666 but this commit refers to v11 branch. I guess it have not been applied on v10.

**Comment by Yenthe666** [comment]
@Yakulu no indeed, this was only done against V11.
