### ISSUE TITLE
[8.0] Default picking_type_id on purchase does not work in multi company mode

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#14338]
The purchase module includes a puchase_data.yml which occurs security warning.

`!python {model: ir.values}: |
    whr = self.pool.get('stock.warehouse').browse(cr, uid, ref('stock.warehouse0'), context=context)
    self.set_default(cr, uid, 'purchase.order', 'picking_type_id', whr.in_type_id.id, for_all_users=True, company_id=True, condition=False)`

This code put the same picking_type_id for all companies.

Example:

- stock.warehouse0 is on company A.
- Define another company B with its own warehouse.
- Update the purchase module -> a new default value for picking_type_id on purchase order for company B is created by wtih the value of company A
- Create a purchase order on company B, Odoo tries to get the picking_type_id from company A. If user doesn't have any rights on company A, it occurs a security warning. Otherwise the purchase order is linked to a picking operation of another company.

**Comment by Cedric-Pigeon** [comment]
OPW 694059

**Comment by simongoffin** [comment]
Closed with a433ae65cb2c31a278980588c865d4f351612878

**Comment by Cedric-Pigeon** [comment]
@simongoffin Thanks
