### ISSUE TITLE
Product extension module doesn't work out with variants

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#14331]
Impacted versions:
10

Steps to reproduce:
create two materials: one w/out and another one with variants
for both of them create BOMs and Routings

rCurrent behavior:
the feature "compute from BOM" is active for simple materials
the same feature is not shown for matirial variant at variant level

Expected behavior:
the feature "compute from BOM" should be available for variant materials at variant level

Video/Screenshot link (optional):

**Comment by lap-odoo** [comment]
@ccandito Thank you for reporting this. The feature has not been built to be compatible with the use of variants. However, I agree that it would make sense. I've added this in our backlog. Thanks
