### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by luienper** [odoo/odoo#14332]
Impacted versions:
10
Steps to reproduce:
Create a Calendar recurrent event by year
Current behavior:
 Doesn't create the events automatic for the next year

Expected behavior:
create the events automatic

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @luienper,

Thanks a lot for your report. I've just tested this on the latest runbot (V10) and this works fine out of the box?
The settings that I've made:
![image](https://cloud.githubusercontent.com/assets/6352350/20422293/ca77d19c-ad69-11e6-8b78-53eadc32c267.png)
After clicking on save:
![image](https://cloud.githubusercontent.com/assets/6352350/20422322/eab48aa4-ad69-11e6-8573-d6ecd9acf909.png)

So I get one for every single year. Can you try again and reproduce this on a runbot (runbot.odoo.com)?

Regards,
Yenthe

**Comment by luienper** [comment]
Thanks for your answerOn November 18, 2016 at 2:35 AM "Yenthe V.G" <notifications@github.com> wrote:Hi @luienper,Thanks a lot for your report. I've just tested this on the latest runbot (V10) and this works fine out of the box? The settings that I've made:  After clicking on save: So I get one for every single year. Can you try again and reproduce this on a runbot (runbot.odoo.com)?Regards, Yenthe—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by luienper** [comment]
Thank you for your soonish reply.
I have run the test just as you said and I have not had any problems with the list, everything works fine. The problem is when I set it to "Calendar" view, I cannot see all the events I have programmed with that amount of repetitions. i.e. I create an a yearly event for 5 years, which I can see in the list view like you showed me but I cannot see it in the Calendar view during those 5 years. I tested the recurrence using days and weeks and it works fine but when I use months and years I cannot see it.
Can you help me with that?
Regards,
Luis Perez

**Comment by Yenthe666** [comment]
Hi @luienper,

Thanks a lot for the extra information. This indeed looks like an issue..
This year in the calendar:
![image](https://cloud.githubusercontent.com/assets/6352350/20435776/ab9b2ea6-adad-11e6-87ce-b32ff6ef2a6e.png)


Next year in the calendar:
![image](https://cloud.githubusercontent.com/assets/6352350/20435755/9b728b78-adad-11e6-9922-88d30a08ab03.png)

@JKE-be and @mart-e could you guys look at this?

**Comment by luienper** [comment]
thanks

**Comment by isluismarlon** [comment]
Thank you @luienper for putting this out. Same thing happened to me. I cannot see all the future events I have planned for 6 years ahead. Please let us know as soon as you have found something. Thanks

**Comment by luienper** [comment]
???

**Comment by JKE-be** [comment]
Hi @luienper 

I have just fixed the bug now in v8, that will be forwardported to v10 in the next days.
Meanwhile, you can already apply this patch: https://github.com/odoo-dev/odoo/commit/dc75c512864ea13dd93a7a83d0c491ca684ff833.patch
