### ISSUE TITLE
Odoo Session Expired (version 9)

### ISSUE THREAD

**Issue by woei66** [odoo/odoo#14335]
Impacted versions: 9.0

Steps to reproduce:
visit the homepage and input the account and password
Current behavior:
can't login and display exception on the chrome console
Expected behavior:
can login 
Video/Screenshot link (optional):
<img width="1247" alt="2016-11-16 12 52 12" src="https://cloud.githubusercontent.com/assets/5770807/20335205/95b0799c-abfb-11e6-9592-3898e5145cb0.png">

web.assets_common.js:2544 
Server application error {
"message":"Odoo Session Expired",
"code":100,
"data":{
"debug":"Traceback (most recent call last):
	File \"/odoo/openerp/http.py\", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
    File \"/odoo/openerp/addons/base/ir/ir_http.py\", line 172, in _dispatch
    auth_method = self._authenticate(func.routing[\"auth\"])
    File \"/odoo/openerp/addons/base/ir/ir_http.py\", line 105, in _authenticate
    getattr(self, \"_auth_method_%s\" % auth_method)()
    File \"/odoo/openerp/addons/base/ir/ir_http.py\", line 81, in _auth_method_user
    raise http.SessionExpiredException(\"Session expired\")
    SessionExpiredException: Session expired\n",
    "exception_type":"internal_error",
    "message":"Session expired",
    "name":"openerp.http.SessionExpiredException",
    "arguments":["Session expired"]
    }
}

**Comment by Yenthe666** [comment]
Hi @woei66,

Thanks a lot for your report!
I've just tested this on the latest Odoo 9 but cannot reproduce this issue. Can you please try it again on a runbot (runbot.odoo.com) or update your Odoo to the latest source code?
If you can still reproduce it then please comment again and ping me, then we'll look further.

Regards,
Yenthe

**Comment by palkesh-baraiya** [comment]
Same Issue 


![screenshot from 2017-12-12 18-16-57](https://user-images.githubusercontent.com/27768935/33885233-d3795036-df68-11e7-9cec-5c2f12accb5a.png)

**Comment by nagwagabr** [comment]
This error is due to openerp-server.conf 
in path C:\Program Files (x86)\Odoo 9.0-20190415\server\openerp-server.conf 

settings: edit the value of this parameter as:
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120

then restart the service from computer manage for odoo and for postgresql
