### ISSUE TITLE
Import csv file from another DB.

### ISSUE THREAD

**Issue by marcelompz** [odoo/odoo#14352]
Impacted versions:
9.0
Steps to reproduce:
Import csv file from another DB.
Current behavior:
Can't even showme the page to upload file.
Expected behavior:
Upload file to validate fields of the DB.
Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/17249379/20356205/8c927124-ac02-11e6-96be-aa0d58304abe.png)

**Comment by Yenthe666** [comment]
Hi @marcelompz,

Could you try this again please? I was not able to reproduce this anymore.

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
