### ISSUE TITLE
[10.0] Selling a service thru POS creates an empty stock operation

### ISSUE THREAD

**Issue by smartupdo** [odoo/odoo#14353]
Impacted versions:
10.0

Steps to reproduce:
Start a new demo database, sell any service product thru POS.

Current behavior:
An stock operation is created with no product, which shows as a picking error on the POS session closing screen and as a To Do transfer on Inventory.

**Comment by invitu** [comment]
Confirmed in commit 3ad1867ea4d7fcda4ccfeb0a7f3d3860b16d389e (2017-03-31)

**Comment by sle-odoo** [comment]
fixed by https://github.com/odoo/odoo/commit/c6b4154fa6e7d18dc3ddf7fa19a96663a727b6b4
