### ISSUE TITLE
9.0 WYSIWYG fields broken, causing dataloss !!

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#14351]
Impacted versions:

9.0, since commit 897290dd3ff218ddc12dcdc6c936a8725813cefe

Steps to reproduce:

Method 1:
- Change project task description (without pads enabled)
- Field is cleared upon clicking save

Method 2:
- Tried this at runbot.odoo.com,
- send invoice by mail
- As soon as you press send, the wysiwyg field is cleared, before being send.

Current behavior:

wysiwyg fields are cleared upon submitting

Expected behavior:

...

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @adaptivdesign,

Thanks a lot for your report. I've just tested this in the latest 9.0 and I can confirm this is a bug.
@mart-e could you assign somebody and add somebody for the project module on the wiki? (https://github.com/odoo/odoo/wiki/BugManagement)

Regards,
Yenthe

**Comment by nle-odoo** [comment]
hello

#14339 was reverted with https://github.com/odoo/odoo/commit/a6e3ae6b8c

**Comment by danimaribeiro** [comment]
What about version 10.0?  Any timeline to be ported this fix?

**Comment by nle-odoo** [comment]
to solve the issue directly, you could get back to this point in community  https://github.com/odoo/odoo/commit/25888f41952e9b9f78fa493b906dfe458a410210 or if you don't use git applying the revert like this from odoo community root directory:

```bash
patch -p1 < <(curl 'https://github.com/odoo/odoo/commit/a6e3ae6b8c')
```

**Comment by micson1** [comment]
The patch works - here is the correct command to run:

patch -p1 < <(curl 'https://github.com/odoo/odoo/commit/a6e3ae6b8c.patch')

**Comment by 7hunderbug** [comment]
The above patch doesn't work for 10.0 branch (or on my nightly 10.0-20161121 (Community Edition)) so I made a gist. A bit of a hack I know however, it can be applied from the odoo root directory with:
`patch -p0 < <(curl 'https://gist.githubusercontent.com/7hunderbug/0d100ce4e703dcbe9527dd2c468b0e64/raw/b46a8d9104e875c7e408a76b8a52d95f43f40c8c/Patch%2520for%2520Odoo%252010.0-20161121%2520%28Community%2520Edition%29%2520to%2520revert%2520commit%2520897290dd3f%2520-%2520fixes%2520disappearing%2520task%2520descriptions')`

**Comment by nickaceph** [comment]
Thanks @7hunderbug this works for me. Ubuntu 16.04 Odoo 10 community
