### ISSUE TITLE
deadline / date to issue in project manager

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1436]
In project manager, dates can be added to tasks via the deadline (regardless of what view the task is created from), but when creating an issue, no date field is available. You can however create an issue from the calendar view, and the issue will show on the calendar (but no date field is available to edit or view in the issue itself).

**_Impacted versions:**_
- Version 7.0-20140722-231204

**_Steps to reproduce:**_
1. Open project
2. Click issues
3. Create issue

**_Current behavior:**_
- No date / deadline field available

**_Expected behavior:**_
- Date / deadline field available, similar to tasks.

**Comment by yelizariev** [comment]
[service_desk_issue](https://github.com/OCA/project-service/tree/8.0/service_desk_issue) fixes this issue

**Comment by Yenthe666** [comment]
Hi @rolandwells,

Thank you for your report / suggestion.
This is where we have the durations etc for on the issue, which can be configured. It is correct that there is no date / deadline field though, if you'd like this you could develop this your own or use the module linked by yelizariev.

Regards,
Yenthe
