### ISSUE TITLE
V10 EE+CE Properties on SO lines + BoM not functioning

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#14363]
**Impacted versions:**  V10 EE +CE

**Steps to reproduce:** 
Enable the 2 settings in the user profile and 1 setting in Sales config
![image](https://cloud.githubusercontent.com/assets/7501203/20388952/3a3fd874-ac95-11e6-86c9-a4c3c0a54a34.png)
![image](https://cloud.githubusercontent.com/assets/7501203/20388966/46199dec-ac95-11e6-8333-a3e41001a020.png)

**Current behavior:** 
nothing happens, property fields arent displayed in the sales order lines, nor in the BoM
![image](https://cloud.githubusercontent.com/assets/7501203/20389120/0d626050-ac96-11e6-9787-fa65ad9f2e4f.png)

BOM
![image](https://cloud.githubusercontent.com/assets/7501203/20389207/7a39c664-ac96-11e6-9e53-b4898fff95f3.png)

**Expected behavior:**
Have a field shown on the sales order line to select/create properties of an product to load the BoM with the same property
![image](https://cloud.githubusercontent.com/assets/7501203/20389079/cd5f3596-ac95-11e6-830e-9750cd00d437.png)

BOM
![image](https://cloud.githubusercontent.com/assets/7501203/20389231/9e1ec70a-ac96-11e6-8001-c2057298b9ed.png)

**Video/Screenshot link (optional):**

**Comment by aduijs** [comment]
functionality is removed by Odoo

**Comment by pedrobaeza** [comment]
Yes, this has been deprecated and removed on Odoo, so I close the issue.
