### ISSUE TITLE
Get notification on email from Task > Timesheets

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#14360]
Impacted versions: Odoo 9

Steps to reproduce: Project > Task > Timesheets tab

Current behavior:

Expected behavior: Is it possible send  notification to follower after add line to Timesheets for example after change stage or Task ready (email subtypes)

Video/Screenshot link (optional): https://postimg.org/image/g5g65olqr/

**Comment by Yenthe666** [comment]
Hi there,

This is not supported by default but could be done through custom development.
It is not something that we want to implement by default in Odoo though.

Regards,
Yenthe
