### ISSUE TITLE
[10.0] Bad display of binary field

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#14362]
Impacted versions:

At least 10.0

Steps to reproduce:

See https://youtu.be/ZEW4Ge1EeVg

Current behavior:

Bad display of binary field

Expected behavior:

Have a correct display of binary field

Video/Screenshot link (optional):

https://youtu.be/ZEW4Ge1EeVg

**Comment by adrienpeiffer** [comment]
OPW 694196

**Comment by Yenthe666** [comment]
@adrienpeiffer can you give an update & official statement from 694196?

**Comment by Yenthe666** [comment]
@adrienpeiffer was this ever resolved or? @nim-odoo could you give feedback?

**Comment by adrienpeiffer** [comment]
Hi Yenthe,
Odoo does not consider this a bug and does not want to fix it.
A duplicate of this one with an Odoo feedback : https://github.com/odoo/odoo/pull/20997

**Comment by Yenthe666** [comment]
I see, thanks for the feedback!
