### ISSUE TITLE
[bug] Same french translation for "Picking Preparation" and "Delivery Slip"

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#14369]
Impacted versions: 9

**Steps to reproduce:**
1. switch language to french
2. go to a picking
3. open print menu

**Current behavior:**
you see duplicated entries for "Bon de preparation"
Current translations for [Picking Preparations](https://github.com/OCA/OCB/blob/9.0/addons/stock/i18n/fr.po#L4186-L4189) and for [Delivery Slip](https://github.com/OCA/OCB/blob/9.0/addons/stock/i18n/fr.po#L1755-L1758)

**Expected behavior:**
Have different labels to recognize reports

**Video/Screenshot link:**
![screenshot from 2016-11-17 17-54-29](https://cloud.githubusercontent.com/assets/347149/20398794/12f0d1ec-acef-11e6-8598-fe9ff218f468.png)
![screenshot from 2016-11-17 17-55-24](https://cloud.githubusercontent.com/assets/347149/20398795/12f2db72-acef-11e6-851b-b5900c5f1771.png)

I updated the [translation on transifex](https://www.transifex.com/odoo/odoo-9/translate/#fr/stock/59115199?q=Picking%20Operations) but I'm not sure is the correct way to go.

/cc @fclementic2c @mart-e

**Comment by mart-e** [comment]
Hello,

Thank you for the correction on Transifex. If you have correct it on transifex, you have nothing to do, it is [already on github](https://github.com/odoo/odoo/blob/a6e3ae6b8c08b3e2abfda248b5f77a1781244683/addons/stock/i18n/fr.po#L4189).
It is [synchronized every week](https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github).
