### ISSUE TITLE
Add a bank account

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#143716]
Close

Script to https://production.odoofin.com/proxy/v1/odoofin_link was blocked. whitelisted it and fine now

**Comment by malandro0** [comment]
Dinero

**Comment by werkwolk** [comment]
this is still a problem in the latest runbot. I cant believe no one needs a bank account in odoo????

![image](https://github.com/odoo/odoo/assets/69362083/b9fb8957-9e69-48de-ac82-0aa90791c944)
