### ISSUE TITLE
[10.0] Malformed translations to es_MX lang

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#14373]
Impacted versions:
10.0
Load es.po translations

https://github.com/odoo/odoo/blob/10.0/addons/account/i18n/es.po#L183-L188
![image](https://cloud.githubusercontent.com/assets/10233975/20416252/505ca664-ad03-11e6-8c82-312cfe4b12ac.png)

![image](https://cloud.githubusercontent.com/assets/10233975/20416254/5370f350-ad03-11e6-99bd-dc7b27882794.png)

**Comment by moylop260** [comment]
@pedrobaeza 
Dp you have allowed create change from es.po translations of transifex?

**Comment by mart-e** [comment]
Thanks for the report.
I have corrected the translation but for the future, please refer to the [Translations guidelines](https://github.com/odoo/odoo/wiki/Translations) to correct the translations on Transifex and not on Github

**Comment by hugho-ad** [comment]
@mart-e 
There are more Malformed translations staments

https://github.com/odoo/odoo/blob/10.0/addons/account/i18n/es.po#L5393-L5394

**Comment by mart-e** [comment]
@hugho-ad thanks for the correction !
