### ISSUE TITLE
[8.0] XmlHttpRequestError when clicked on the link of attached file in email form

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#14387]
Impacted versions: 8.0 community
I've reproduced it on runbot : http://183915-8-0-efdeb6.runbot10.odoo.com/web
see the attached screenshot

Steps to reproduce:
Use Firefox browser. 
In Firefox > Tools > Options > General:
Configure the browser to Always Ask where to Save downloaded file. 

- Go to "Quotations", 
- Click on any "Quotation line", 
- In the Quotation form click on "Send by Email"
- In email form click on Attached file link
(Notice that error happens randomly, so you have to execute this several times: close the email form, then click again on "Send by Email" and click again on the attached file link).

Current behavior:
When clicked on the Attached file link, you have error popup with the message "XmlHttpRequestError"

Expected behavior:
When clicked on the Attached file, attached file must be opened with no error messages. 

Video/Screenshot link (optional):
![odoo_8 0_xmlhttprequesterror-2](https://cloud.githubusercontent.com/assets/9844780/20430136/e56a2c24-ad92-11e6-861e-7c8265bd3ad9.PNG)
![xmlhttprequesterror_on_runbot](https://cloud.githubusercontent.com/assets/9844780/20882267/5ecf7164-bae0-11e6-92fd-b40563e5fec1.PNG)

**Comment by Yenthe666** [comment]
Hi @sergueikp,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
