### ISSUE TITLE
Content field gets cleared on Email Template when user tried to update value on template

### ISSUE THREAD

**Issue by bista-amitd** [odoo/odoo#14381]
Impacted versions:
9.0 + Enterprise
Reproducible on Runbot instance: http://180654-9-0-28e1fe.runbot10.odoo.com/

Steps to reproduce:
-> Goto : Settings->Technical->Email->Templates
-> Open any template
-> And try to update context

Current behavior:
Content field gets cleared

Expected behavior:
Content should not be cleared

Video/Screenshot link (optional):
[out-15.ogv.tar.gz](https://github.com/odoo/odoo/files/599374/out-15.ogv.tar.gz)

**Comment by bista-amitd** [comment]
adding @raycarnes

**Comment by bista-amitd** [comment]
OPW: 694309

**Comment by Yenthe666** [comment]
Hi @bista-amitd,

Thanks a lot for your report. I've just tested this and I can confirm this is a bug.
@tde-banana-odoo this might be one for you?

Regards,
Yenthe

**Comment by lukebranch** [comment]
I've just been able to reproduce this on 9.0 Community as well.

**Comment by Yenthe666** [comment]
@lukebranch yep it is in the community version too.

**Comment by lukebranch** [comment]
@Yenthe666 ,

Yeah, not that that's unexpected, just thought i'd mention it.

I did a routine upgrade recently (roughly the same date as this issue thread was opened) and have had someone report this was an issue this afternoon.

It seems like this one is a pretty big deal though, if it affects discuss/mail it will affect pretty much everyone using Odoo 9.0/10.0 who's done an update or downloaded Odoo in the past week or so.

**Comment by Yenthe666** [comment]
@mart-e could you assign somebody on this one? 😉

**Comment by mart-e** [comment]
@tivisse you were talking about this I think. Is there a branch somewhere?

**Comment by qsm-odoo** [comment]
Hello, I think this issue is related to the bug that was recently introduced with this issue fix https://github.com/odoo/odoo/pull/14339
People are working on it.

**Comment by nle-odoo** [comment]
hello

#14339 was reverted with https://github.com/odoo/odoo/commit/a6e3ae6b8c

**Comment by lukebranch** [comment]
brilliant. That's fixed it, thanks!

**Comment by davidtranhp** [comment]
Great! Will this fix come to Odoo 10, @nle-odoo ?
