### ISSUE TITLE
[10] Azure oauth2 error - <winhost-url> isn't using a secure scheme

### ISSUE THREAD

**Issue by jokr0815** [odoo/odoo#14383]
Impacted versions: 10

Steps to reproduce: Create oauth2 provider Azure and try to Login.

Current behavior: Not working - Azure is responding with error: AADSTS50011: The reply address 'http://<windows-host>/auth_oauth/signin' isn't using a secure scheme.

Expected behavior: Need to configure the Redirect somewhere

Video/Screenshot link (optional):
<img width="832" alt="2016-11-18 11_08_34-error und 6 weitere seiten - microsoft edge" src="https://cloud.githubusercontent.com/assets/23552003/20426485/960585f6-ad7f-11e6-8b43-4dcc09286a16.png">

**Comment by Yenthe666** [comment]
Hi there,

Azure has nothing to do with Odoo. This is a problem/issue on the Azure side.

Regards,
Yenthe

**Comment by nassoor** [comment]
I am facing the same issue. It looks like the link in the sign in page is not built right.

The redirect_uri segment of the URL should be HTTPS but Odoo is presenting the link with HTTP. So, if I copy the link and add an "s" I can login successfully.

I have web.base.url.freeze set to true and web.base.url set to an HTTPS URL.

I followed the instructions here: https://www.odoo.com/documentation/16.0/applications/general/auth/azure.html
