### ISSUE TITLE
[9.0c] Switching from kanban to form view goes into creation

### ISSUE THREAD

**Issue by zorkek** [odoo/odoo#14382]
**Impacted versions:** 9.0

**Steps to reproduce:** in any section that has a kanban view; go in kanban view mode then switch to Form view mode by clicking the appropriate switch button placed in the top-right corner.

**Current behavior:** clicking on the form view switch button you get the same behavior as of clicking the Create button (in other words, odoo does not fetch a record to show and goes into creation mode)

**Expected behavior:** clicking on the form view switch button it should be shown the first record of the interested model. _This happens only if you go from list view mode to form view mode._

**Comment by Yenthe666** [comment]
Hi there,

Thanks for the feedback and sorry for the late reply.
This is actually the desired behaviour and not something we'd like to change.

Regards,
Yenthe
