### ISSUE TITLE
[8.0]mapped get wrong value at Reference field

### ISSUE THREAD

**Issue by Mellcap** [odoo/odoo#14399]
Impacted versions: 8.0

Steps to reproduce: 
I have a reference field named "target" which reference models in
```python
 [('res.country', 'Country'),
    ('res.country.state', 'State'),
    ('res.city', 'City'),
    ('res.medical.hospital', 'Hospital'),
    ('res.medical.hospital.department.line', 'Department'),
    ('res.medical.doctor', 'Doctor')],
```
When I use `rec.mapped('target')`, I should get 
```python
[res.country(49,),
 res.country.state(61,),
 res.city(3251,),
 res.medical.hospital(101982,),
 res.medical.hospital(101983,),
 res.medical.hospital(101984,),
 res.medical.hospital.department.line(502,),
 res.medical.doctor(239343,)]
```
But I got ```res.country(101984, 239343, 49, 3251, 502, 61, 101982, 101983)```

Current behavior:
```python
res.country(101984, 239343, 49, 3251, 502, 61, 101982, 101983)
```
Expected behavior:
```python
[res.country(49,),
 res.country.state(61,),
 res.city(3251,),
 res.medical.hospital(101982,),
 res.medical.hospital(101983,),
 res.medical.hospital(101984,),
 res.medical.hospital.department.line(502,),
 res.medical.doctor(239343,)]
```

**Comment**:
I found that the point is at 
```python
def _mapped_func(self, func):
        """ Apply function ``func`` on all records in ``self``, and return the
            result as a list or a recordset (if ``func`` returns recordsets).
        """
        if self:
            vals = [func(rec) for rec in self]
            if isinstance(vals[0], BaseModel):
                # return the union of all recordsets in O(n)
                ids = set(itertools.chain(*[rec._ids for rec in vals]))
                return vals[0].browse(ids)
            return vals
        else:
            vals = func(self)
            return vals if isinstance(vals, BaseModel) else []
```
```python
return vals[0].browse(ids)
```
But I have no idea how to fix it.

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/11872712/20461314/ea734720-af34-11e6-8264-132b07b89493.png)

**Comment by Yenthe666** [comment]
Hi @Mellcap ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
