### ISSUE TITLE
[10.0] mail: Mail Composer form removes all content upon pressing Send button 

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#14398]
Impacted versions: 10.0

Steps to reproduce: in OpenChatter, open Full Composer from, type something and press Send

Current behavior: Message content is removed completely and and empty content message is sent to recipients

Expected behavior: Message content must remain

**Comment by bista-amitd** [comment]
duplicate of #14381

**Comment by Yenthe666** [comment]
Hi @davidtranhp,

Thanks a lot for your report! This is indeed & duplicate of 14381, so I'm closing this one.

Regards,
Yenthe
