### ISSUE TITLE
fleet management /Report/costs error

### ISSUE THREAD

**Issue by luienper** [odoo/odoo#14392]
Impacted versions:
10
Steps to reproduce:
- in Fleet module
   -we choose "costs" in the Report section
   From Costs Analysis we choose one of the total prices
Current behavior:
 -When we choose one item in the pivot, it shows error
Expected behavior:
 - We get to see the records from the item we chose
Video/Screenshot link (optional):
![screenshot from 2016-11-18 13-05-02](https://cloud.githubusercontent.com/assets/11526274/20440831/abfbc806-ad8f-11e6-98a9-6731db15697e.png)
I clicked on one of the costs in the "Total Price" column and then it shows the following error...
![screenshot from 2016-11-18 13-05-40](https://cloud.githubusercontent.com/assets/11526274/20440851/bee88bac-ad8f-11e6-8049-92afeade46b8.png)

**Comment by qsm-odoo** [comment]
Hello, commit https://github.com/odoo/odoo/commit/131a16525e11edb2b9c64731fd014357abcd6f0f fixed the issue in the saas-11 version. This will be merged in 10.0 in the upcoming days.

**Comment by luienper** [comment]
thanks
