### ISSUE TITLE
[10.0] Menu dissapeared - no assets common

### ISSUE THREAD

**Issue by nikosg5** [odoo/odoo#14401]
Impacted versions: 10.0

Steps to reproduce: open my instance from chrome in adroid phone

Current behavior: doesn't appear any menu

Expected behavior: 

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/8676956/20464484/de189acc-af50-11e6-8c96-754abe3fe8d8.png)

I have install odoo and I installed 2 modules to see if everything works. Then I tried to access my instance from chrome on my adroid phone. Only the menu button appeared (the three horizontal lines) without functionality. I then tried to access the instance from my laptop and everything had dissapeared.

**Comment by JKE-be** [comment]
Hello, your asset common js is empty.
Try to install another module/upgrade a module or touch a file to regenerate it.

**Comment by nikosg5** [comment]
How can I install or upgrade a module without menu? Can it be done from command line?
Sorry if it is stupid question but I am new to odoo
Thank you in advance

**Comment by JKE-be** [comment]
`./odoo-bin -d office --db-filter=^office$ -u website`

**Comment by nikosg5** [comment]
![image](https://cloud.githubusercontent.com/assets/8676956/20525814/daa26682-b0c9-11e6-864b-c55ca98c2d18.png)

 I run the command as odoo user. Still empty screen :/

**Comment by JKE-be** [comment]
what are the 2 modules installed ? Custom modules ? seems like it crash the asset generation...
You can load the webclient withtout the asset via:  grispos.gr:8069/web/login?debug=assets

**Comment by JKE-be** [comment]
try ` -u web` , because website is not installed ... so no update :)

**Comment by nikosg5** [comment]
![image](https://cloud.githubusercontent.com/assets/8676956/20526346/53fb3e08-b0cc-11e6-90d1-ad94c12c78ba.png)

With the -u web seemed to work but at the end a get this error above. And it stucked at the database selection. The modules I have installed was Project. Nothing custom
Becasuse me setup is fresh maybe its easier to reinstall it? I have to delete files and databases?

**Comment by JKE-be** [comment]
yes, seems a problem of privilege with your databases now ! (https://www.odoo.com/documentation/10.0/setup/install.html#installing-dependencies)
Better is to follow the **tutorial** on the website [odoo.com/**documentation**](https://www.odoo.com/documentation/10.0/setup/install.html)


And if you have any questions about the installation, ask on the forum, this tracker is for issue only :/
