### ISSUE TITLE
[8.0] Access to res.partner in multi company

### ISSUE THREAD

**Issue by drl9319** [odoo/odoo#14408]
**Impacted versions:**
Version: 8.0

**Steps to reproduce:**
I have three companies:
1- consolidate company (parent)
2- company A (child)
3- company B (child)

I enter with Admin in consolidate company and after enter with some user I can view the share res.user, but when I enter with Admin user for example un company A and after I enter with other user only can enter the same previos res.user in company A and consolidate but not in company B when previusly I can view this res.partner when I enter with Admin in consolidate company.

**Current behavior:**
AccessError

**Expected behavior:**
Enter to view partner

**Comment by Yenthe666** [comment]
Hi @drl9319 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
