### ISSUE TITLE
Enable option send, print, confirm in quotations

### ISSUE THREAD

**Issue by odoo01234** [odoo/odoo#14407]
Impacted versions: odoo 9

Steps to reproduce: In my version option  send, print, confirm in quotations is not visible, how enable that?

Current behavior:

Expected behavior:

Video/Screenshot link (optional): https://postimg.org/image/xealgcn6l/

**Comment by Yenthe666** [comment]
Hi @odoo01234,

Can you please update your Odoo to the latest code base and then do a `-u all`? 
This issue is not reproducable and it looks like your Odoo just didn't render it for once.

Regards,
Yenthe
