### ISSUE TITLE
[10.0] Validation for search view - Bad code leads to unhelpful traceback on search views

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#14423]
Impacted versions: 10.0

Steps to reproduce:
Create/edit a search view type
 ```
<field code="name" />
```
 as part of the search view.

Current behavior:
Module will be loaded without error (if in a module).
When accessing corresponding model - impossible to understand traceback for normal human.
![image](https://cloud.githubusercontent.com/assets/5093264/20510824/463b8dc0-b0d8-11e6-8aad-40ff48cff06e.png)

(Thats one example, there is actually two different tracebacks that occur depending on weather)

Expected behavior:
Module refuses to install by failing validation with helpful message like other views and/or
Helpful Error Message and/or
Developer validation tools.

Video/Screenshot link (optional):

Obviously I know about it now, but you know what its like when trying to track down errors right in front of your eyes.  Not even a clue where to look.

**Comment by pedrobaeza** [comment]
@JKE-be is this still pending?

**Comment by JKE-be** [comment]
Hello

We agree that the error message should be improved and become helpful :cloud: 
But it is the expected behaviour to crash and show you that your customization failed.

I ping framework team to let them do what they think good to do.

//cc @aab-odoo
