### ISSUE TITLE
Cannot validate closing & post entries (POS)

### ISSUE THREAD

**Issue by tony-elico** [odoo/odoo#14427]
Impacted versions: version 10

Steps to reproduce:
Enable cash control

Current behavior:
After set closing balance, cannot validate closing & post entries 

Expected behavior:
After set closing balance, need to able validate closing & post entries 

Video/Screenshot link (optional):
![cannot validate closing post entries](https://cloud.githubusercontent.com/assets/20697345/20515944/dd744df8-b0ce-11e6-9867-14e2a8c14b41.png)

**Comment by mart-e** [comment]
What do you mean you cannot? The button is top left on your screenshot.

**Comment by tony-elico** [comment]
Dear Martin Trigaux

         The problem is when i  click the button of top left,  there is no response. 



------------------
TONG LIN YUN [ERP                                               Functional consultant]
                              Skype: tonglinyun2016. Phone: + 86 139 1895 0128(Cell), + 86 21 6211 8017 (Office)             
             Elico Shanghai (Hong Kong/Shenzhen/Singapore) 
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016 

 
 
 
------------------ Original ------------------

**Comment by Yenthe666** [comment]
Hi @tony-elico,

I've just tested this on the latest Odoo 10 and it works without any problems.
Can you try reproducing the issue on an official Odoo instance please? (runbot.odoo.com)

Regards,
Yenthe

**Comment by mart-e** [comment]
I tested it too, it requires you to configure a gain or loss account on the POS cash journal (error message if not configured) but it works well in v10.
Please update your code and check il nothing could catch this error.
Closing as can not reproduce but if you have proper steps to reproduce, let me know and we can reopen.

**Comment by tony-elico** [comment]
Dear ODOO

          What's you mean ''configure a gain or loss account on the POS cash journal''?
I tested it on runbot10, it can close the session, but it also not set gain or loss account
please refer the attachment.



------------------
TONG LIN YUN [ERP                                               Functional consultant]
                              Skype: tonglinyun2016. Phone: + 86 139 1895 0128(Cell), + 86 21 6211 8017 (Office)             
             Elico Shanghai (Hong Kong/Shenzhen/Singapore) 
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016 

 
 
 
------------------ Original ------------------

**Comment by mart-e** [comment]
@tony-elico the attachment do not work when replying by email, you should do it using github interface.

I am talking about these accounts on the cash journal
![screenshot from 2016-11-23 10-02-52](https://cloud.githubusercontent.com/assets/564822/20555786/1962cbf6-b164-11e6-8422-00cb6438e34a.png)

**Comment by tony-elico** [comment]
Dear 
          
         We are mention the same that Profit account and loss account,  both i assign value to Profit account and loss account or keep NULL for Profit account and loss account, i cannot close my session.   but it can close the session on runbot10. may be some other settings is wrong of my own environment? 
 


------------------
TONG LIN YUN [ERP                                               Functional consultant]
                              Skype: tonglinyun2016. Phone: + 86 139 1895 0128(Cell), + 86 21 6211 8017 (Office)             
             Elico Shanghai (Hong Kong/Shenzhen/Singapore) 
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016 

 
 
 
------------------ Original ------------------

**Comment by mart-e** [comment]
Yes, check your logs. make sure you are using up to date source code and do not have custom modules that may disturb the closing

**Comment by Yenthe666** [comment]
and if you still face an issue then please make an help topic on the official help forums (help.odoo.com), there are plenty of people who can help you there.

**Comment by Imranmasroor** [comment]
![image](https://user-images.githubusercontent.com/55685126/65435955-c40a7580-de3a-11e9-8bd1-49e8773b7f3b.png)


I got the same error after pressing the button on the right corner
