### ISSUE TITLE
upgrade fullcalendar to 3.x version

### ISSUE THREAD

**Issue by smorele** [odoo/odoo#14425]
In odoo 10, fullcalendar is still in 1.x while the fullcalendar library exists in 2.x and 3.x.
Is there a wish to upgrade to 2.x or 3.x to get new functionnalities ? (ie. [scheduler](https://fullcalendar.io/scheduler/))

**Comment by JKE-be** [comment]
Hello @smorele 

We speak about, in the past, to migrate in v2...
But that required to rewrite all the web_calendar since v1/v2 was not compatible.

datejs -> momentjs, jqueryUI dropped, ...

So the task is probably already existing, but no resources now to do it :rage:

**Comment by smorele** [comment]
to me, the most important project is to upgrade to jQuery 2.x which is a prerequisite.
