### ISSUE TITLE
[9.0]About class named ir.actions.act_window and it's field named groups_id

### ISSUE THREAD

**Issue by lonelysun** [odoo/odoo#14445]
Hi,
recently，i want to control the url's action, and i find that the action is the most important point.
i find a class named 'ir_actions_act_window',it have a field named 'groups_id'.i google a lot to find the effect about the 'groups_ids',but i don't have any result.
hope someone can answer.
thx.

**Comment by Yenthe666** [comment]
Hi @lonelysun,

Sorry for the late reply on this one.
The Github tracker is only for bugs in the official code and not the place to ask questions. You can do this on the official help forums at help.odoo.com
`group_ids` are used to set groups there ids on an action for example.

Regards,
Yenthe
