### ISSUE TITLE
odoo-bin file is not available in odoo 10 community when downloading from odoo.com.

### ISSUE THREAD

**Issue by lapagept** [odoo/odoo#14441]
Impacted versions: 10

Steps to reproduce:

Download Odoo 10 community (source files) from one of these two places : 
https://nightly.odoo.com/10.0/nightly/src/
https://www.odoo.com/fr_FR/page/download
Decompress the archive

Current behavior:
The file **odoo-bin** is not in the unarchived directory.

Expected behavior:
When I download Odoo 10 community from this address : https://github.com/odoo/odoo in a zip file, the **odoo-bin** file is in the directory. 

I have lost many hours to find this odoo-bin file before to download the zip from github.

**Comment by sle-odoo** [comment]
```odoo-bin``` is only present at the root dir for convenience when working with a clone of the repository. If you download the source package and you run ```python setup.py install```, it'll create a ```odoo``` executable in your path. It's the only thing we want for packages.

If you don't want to install it but still run it from the source package, just execute ```python setup/odoo```.
