### ISSUE TITLE
[10.0] Inherit model doesn't override field definition

### ISSUE THREAD

**Issue by cmayo** [odoo/odoo#14449]
Impacted versions: 10

Steps to reproduce: 
I've created a module with the following code to inherit the `product.product` model and override the existing `standard_price` field definition to set it as a compute field:

    class ProductProduct(models.Model):
        _inherit = 'product.product'

        standard_price = fields.Float(
            'Cost', company_dependent=True,
            digits=dp.get_precision('Product Price'),
            groups="base.group_user",
            compute='_compute_set_standard_price')

        def _compute_set_standard_price(self):
             # calculation for the value
             self.standard_price = 121 #this value is an example

Current behavior:
The `standard_price` field is set to 0 and don't trigger the compute method.

Expected behavior:
The `standard_price` would be set to 121 because I've override the field definition to a compute field. This code in Odoo v8 works fine.

**Comment by ddfs** [comment]
did u check if there is another module overrides the same field?

**Comment by cmayo** [comment]
No other module override this field. I've tried it also in a new installation

**Comment by JKE-be** [comment]
why use company_dependent=True ? 

That will search the value in another model !

**Comment by cmayo** [comment]
I've tried to change the field definition like this `standard_price = fields.Float('Cost', compute='_compute_set_standard_price')` and still doesn't work.

**Comment by cmayo** [comment]
If I set the field definition `standard_price = fields.Float('Cost', compute='_compute_set_standard_price', company_dependent=False)` it works fine. Thanks
