### ISSUE TITLE
XML code from "building a module" causes module installation to fail

### ISSUE THREAD

**Issue by SAFAD** [odoo/odoo#14451]
Impacted versions:
10.0
Steps to reproduce:
Follow the "Building a Module" Documentation until ["View inheritance"](https://www.odoo.com/documentation/10.0/howtos/backend.html#view-inheritance)
Current behavior:
Module crashes on installation with the following error :

> File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:182399)
AssertionError: Element odoo has extra content: data, line 2

I tracked the issue down to this part of code from views/partner.xml
```
		<record model="ir.ui.view" name="partner_instructor_form_view">
			<field name="name">partner.instructor</field>
			<field name="model">res.partner</field>
			<field name="inherit_id" ref="base_view_partner_form"/>
			<field name="arch" type="xml">
				<notebook position="inside">
					<page string="Sessions">
						<group>
							<field name="instructor"/>
							<field name="session_ids"/>
						</group>
					</page>
				</notebook>
			</field>
		</record>

```

Expected behavior:
The module to be installed properly

**Comment by JKE-be** [comment]
hello @SAFAD 

Can you provide your complete xml.
Seems like the bug is on the second line :/

**Comment by SAFAD** [comment]
The first and second lines are simply odoo and data tags, all the other codes is just for window actions and menu links which would *work* if i remove the code above.
As i said I isolated the issue with the code above

**Comment by SAFAD** [comment]
it appears the fault is on my hands
odoo sometimes has mixed use between *id* and *name* in records, I have switched `name="partner..."` to `id="partner..."` and the bug disappeared
Silly me!
