### ISSUE TITLE
[IMP][master] The web.Dialog API should use a form in its widgets to have native HTML5 validation

### ISSUE THREAD

**Issue by yajo** [odoo/odoo#14458]
Impacted versions: 9, 10

Current behavior: If you try to extend any dialog widget to have a form that includes native validation, you need to subscribe your resolution methods to the form's `submit` event, that will only get fired when form is valid. However all core implementations are [inputs outside a form](https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/xml/base_common.xml#L6-L17), with [`<button type='button'>`](https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/xml/base_common.xml#L20) being used for submission.

Expected behavior: 

- the web.Dialog object should have a default qweb template where the modal contains a form. 
- Buttons should be able to get a `type=submit` to trigger validation. 
- It should include a direct way to subscribe to inner form's submit event. 
- BTW, if we could have a [not so hardcoded qcontext](https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/framework/dialog.js#L48), then we could extend base qweb templates and make real use of it.

cc @ged-odoo

**Comment by pedrobaeza** [comment]
@Yajo have you investigated in latest v11 JS views rewritting if this still happens?
