### ISSUE TITLE
Error in parameters to action_pack

### ISSUE THREAD

**Issue by gpothier** [odoo/odoo#14453]
Impacted versions: v8

In the stock addon, in static/src/js/widgets.js, the action_pack method is called with an incorrect ids parameter (it gets a list whose first element is the list of ids, instead of just the list of ids): 

Current:

                    .call('action_pack',[[[self.picking.id]], pack_op_ids])

Should be:

                    .call('action_pack',[[self.picking.id], pack_op_ids])

Fortunately, this only causes a warning in the server (it says the domain operator should be "in" instead of "="), but it gave me a huge headache when trying to override the action_pack method using the v8 api.

**Comment by Yenthe666** [comment]
Hi @gpothier,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
