### ISSUE TITLE
[www.odoo.com]Forum moderation: Unable to delete/close post waiting for validation

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#14462]
Impacted versions:

Actual instance www.odoo.com after the update this afternoon

Steps to reproduce:
Try to delete posts waiting in the validation queue 

Current behavior:

When deleting a post waiting in the validation queue, the post seems to be deleted directly, but the windows for closing posts and specifying a closing reason does not appear. After a refresh, the post reappears in the validation queue.

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @treviser,

Thanks a lot for your report! I've just tested this and this is indeed a bug.
@JKE-be could you fix it please?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Meaculpa,

Broken by my commit #5c11310

I fix it asap...

**Comment by JKE-be** [comment]
Fixed by commit odoo/odoo@4fa39c0e1994ffeffb8937f935634aa29e523da8

Thanks for reporting

Will be deployed today

**Comment by treviser** [comment]
@JKE-be  It happens again.

**Comment by Yenthe666** [comment]
Yup, same behaviour as before.

**Comment by JKE-be** [comment]
Cannot reproduce... are you sure ?

**Comment by JKE-be** [comment]
?

**Comment by Yenthe666** [comment]
The validation process doesn't work anymore. You cannot delete/close a topic anymore on the forums.

**Comment by JKE-be** [comment]
I have just try now, and without problem :/

can you chec network to see if you got a 500 or smthing else?

**Comment by Yenthe666** [comment]
Hi @JKE-be,

I've just double checked this and it is still not fixed. The page returns 200 (OK) and no issues bubble up.
![image](https://cloud.githubusercontent.com/assets/6352350/20762242/06ce9ef8-b726-11e6-8383-9ecfbc301fb2.png)

**Comment by JKE-be** [comment]
Code always not updated on the prod :) That can explain why ;)

**Comment by treviser** [comment]
Bump...
