### ISSUE TITLE
The required version of setuptools (>=1.4) is not available

### ISSUE THREAD

**Issue by Jmvc2406** [odoo/odoo#14466]
Impacted versions: install odoo 10 

Steps to reproduce:
$ pip install -r requirements.txt

Current behavior:
    Complete output from command python setup.py egg_info:
    The required version of setuptools (>=1.4) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.
    
    (Currently using setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /private/var/folders/9r/0ddq17696sj3227zbfbr390c0000gn/T/pip-build-zsTLaT/suds-jurko/

Expected behavior:
install odoo in OS X EL CAPITAN

THANKS

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
@sle-odoo

**Comment by sle-odoo** [comment]
It seems that suds-jurko has a dependency to setuptools and setuptools cannot be installed in this context by pip.
There's not much we can do, you can open a ticket on their bug tracker or just upgrade your version of setuptools (debian jessie packaged one is the 5.5 version, yours seems outdated).
