### ISSUE TITLE
[8.0] Error while choosing optional products from the shop.

### ISSUE THREAD

**Issue by Bonwon88** [odoo/odoo#1446]
Hi,

As I choose optional products and attempt to 'Proceed to checkout', the window (in the picture below) closes, but I am not being redirected to the "Preview order" section. Instead I remain on the 'product' page as nothing happens. (In this case Proceed to chekcout = close)

If I don't choose any optional products it works just fine.

Also if I buy those optional products separately "as main/initial products", I am able to proceed to checkout.

![shopcarterror](https://cloud.githubusercontent.com/assets/8299406/3747233/b0644ef6-17cb-11e4-9940-6d0171ca1b31.jpg)

**Comment by Yenthe666** [comment]
Hii @Bonwon88 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
