### ISSUE TITLE
Uninstall one2many field

### ISSUE THREAD

**Issue by LoicAlba** [odoo/odoo#14479]
Impacted versions: 9.0

Steps to reproduce:
Create a new module with 2 classes : 
- First class ("project.link") created in module. This class contains a Many2one field to "project.project"
- Second class inherited on existing class "project.project" and got a One2Many field to "project.link"

Current behavior:
On uninstall of module, an error occurs : 
"The field 'project.link.from_project_id' cannot be removed because the field 'project.project.successor_ids' depends on it.".
And the "project_link" table is not dropped.

Expected behavior:
The "project_link" table have to be dropped.

**Comment by mocak** [comment]
+1

**Comment by teeling** [comment]
Any news on this? I'm seeing the same issue. On top of this, the module gets half way uninstalled, but leaves the models behind in the database. So now an install of the same module won't work since the models are already there.

**Comment by Yenthe666** [comment]
@mart-e can you give your opinion / feedback? I've been bitten by simular things too.

**Comment by mart-e** [comment]
Hello,

The one2many field is a virtual relation field, it has no impact of the database. So removing a one2many should not do anything.
Could you be a more explicit on what is not removed but should? If you have a few errors in an uninstall it does not mean it fails, it may just mean that we can not remove it yet and will fully remove it when the many2one field is removed.

**Comment by LoicAlba** [comment]
Hi mart-e,
The problem is that the one2many field is declared in the same module than the many2one.
When the uninstall process has an error, it stop, so the many2one is not remove, so the module will never be removed.
The solution can be to remove first many2one fields and after one2many fields.
regards

**Comment by Yenthe666** [comment]
@mart-e could you look into this one again?

**Comment by aheficent** [comment]
Hi @LoicAlba How can I make sure to remove the Manyone field first? Thanks in advance

**Comment by LoicAlba** [comment]
Hi @aheficent, Unfortunately, I don't know how to do this. I think the standard uninstall function have to be updated but I don't now how.

**Comment by aheficent** [comment]
@LoicAlba I'll try to figure it out. Thanks. In my case the isue is happening here: https://github.com/OCA/reporting-engine/pull/148 the many2one field is deleted anyway but the message is still appearing.

**Comment by mart-e** [comment]
Please share code or a least a traceback. Failing to remove a field will not crash as [the error is catched](https://github.com/odoo/odoo/blob/7cd2f63705f8c4ddfd05c70d79aa6261ae191d18/odoo/addons/base/ir/ir_model.py#L1330-L1338). Maybe it will fail later but that is what needs to be investigated.
