### ISSUE TITLE
[8.0] Delay between Date of Stock Move and Datetime of Product Price History

### ISSUE THREAD

**Issue by mbcosta** [odoo/odoo#14474]
Impacted versions: 8.0

Steps to reproduce: 
    There is a possible problem related to delay between field Date in Stock Move and the field Datetime in Product Price History, in mostly time the two dates are equals but on production server could happen an delay. For example:
        The stock move has the date 2016-10-10 14:21:53
        and this stock move create the Product Price History in
        datetime 2016-10-10 14:21:56

Just 3 senconds the difference, but when we use the function get_history_price of Product Template or even an SQL Query to create an function or Report to show the price at a period by using the date of
stock move the program don't find anything because of delay.

Expected behavior:
    Maybe the solution is use the date date of Stock Move as the Datetime of Product Price History.

**Comment by Yenthe666** [comment]
Hi @mbcosta,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
