### ISSUE TITLE
[17.0] Field property_valuation for product_category not show in view

### ISSUE THREAD

**Issue by ocandoe** [odoo/odoo#144866]
Impacted versions: 17.0

Steps to reproduce:
1.- Install account_accountant module 
2.- The user must be in the group "account.group_account_manager "
3.- Go to inventory -> Product Category  

Current behavior:
The property_valuation field is not shown in the view, which makes it impossible to configure an automatic cost process by product category.
![image](https://github.com/odoo/odoo/assets/44589940/0fe65597-15d0-4784-9a7b-716836d45aaa)

Expected behavior:
![image](https://github.com/odoo/odoo/assets/44589940/c1518ff3-5b75-4f1a-9540-cdb81613380c)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): #3624767

**Comment by ctringham** [comment]
Need to enable it in Accounting settings: 
![image](https://github.com/odoo/odoo/assets/38899643/8e0936b7-bc3e-42c3-b781-08f60ab4c1aa)
