### ISSUE TITLE
[17.0] Bad design by having a partner with a long name at the point of sale

### ISSUE THREAD

**Issue by cmayon** [odoo/odoo#144851]
Impacted versions: 17.0

Steps to reproduce:
 * Add a partner with long name at the point of sale

Current behavior:

![image](https://github.com/odoo/odoo/assets/72407361/2308d17a-7f57-46b7-a5f4-e5a4f71853ab)

**Comment by kushdiatoz** [comment]
Hi @cmayon  can you help to fix the odoo Scss file issue i am not able to fix it.
[
![Uploading Screenshot from 2023-12-04 17-16-02.png…]()
](url)

**Comment by cmayon** [comment]
@kushdiatoz Your image has not loaded.
