### ISSUE TITLE
Unknown field product_variant_count in domain [["product_variant_count","<=",1]]

### ISSUE THREAD

**Issue by konstantinkonstantinovbgo** [odoo/odoo#14481]
Impacted versions:
- 9.0
Steps to reproduce:

1. Inventory -> Settings 

Products and check 
Products can have several attributes, defining variants (Example: size, color,...)

Click on "Engeneering infos"

2. Create a new product from menu Inventory -> Products

Current behavior:

Uncaught Error: Unknown field product_variant_count in domain [["product_variant_count","<=",1]]

Expected behavior:

Open "Engeneering infos" section

Video/Screenshot link (optional):

**Comment by pimodoo** [comment]
Hello,

We were unable to reproduce your bug in last 9.0 of Odoo, could you confirm that it's solved on your side or send a video with the steps to reproduce.

Best regards
