### ISSUE TITLE
8.0 - [base] Groups XML ID shouldn't consider for translations

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#14497]
Impacted versions:
8.0

Steps to reproduce:
1. Connect to last odoo 8.0 runbot build http://runbot.odoo.com/runbot/1/8.0
2. Go to Menu -> Settings -> Translations -> Import/Export -> Export Translation
3. Choose english language, PO file format, Sales Management in modules to export and press Export button.
4. Open the file generated and search
```po
...

#. module: sale
#: view:res.partner:sale.res_partner_address_type
msgid "sale.group_delivery_invoice_address"
msgstr ""
```

Current behavior:
The sentences [`<attribute name="groups">sale.group_delivery_invoice_address</attribute>`](https://github.com/odoo/odoo/blob/8d724924f76a943035a8aa2d1b446418fd6b4034/addons/sale/res_partner_view.xml#L67) is considered for translations.

Expected behavior:
Shouldn't be considered for translations because this is a `xml_id` (technical data) and a change in this translation could be a fail in the system. E.g. [xml_id_translated](https://github.com/odoo/odoo/blob/8d724924f76a943035a8aa2d1b446418fd6b4034/addons/sale/i18n/es.po#L2152-L2155)

(I used this way because is a error with base module to export translation I'm not reporting a real problem with a particular translation)

**Comment by moylop260** [comment]
FYI @mart-e

**Comment by mart-e** [comment]
Hello,

This has already been changed in 9.0 (starting at 2eb257ff944abc4d170275102b6be15300f2b3a6) but it is not trivial at all (implied other changes) so we can not simply backport this to 8.0, it is too risky and would break existing view translations.

The solution in 8.0 is to put `translation="off"` on every attribute where a term should not be translated.
I have removed the terms at adb12f95ea9e0453c4abccb1bf66ac83f461cb6b

**Comment by moylop260** [comment]
Thanks for reply
I got it
