### ISSUE TITLE
Importing CSV file : database ID

### ISSUE THREAD

**Issue by Leif0** [odoo/odoo#14494]
Hi,

I have an issue with Odoo 8. I'd like to use the database ID when importing, and it's working fine BUT it doesn't detect the column automatically.

When using "line_id/account_id/id" as the column header, it selects "Entries / Account / External ID", and I'd like to select Database ID instead.

Is there any way to do so? I've tried multiple column headers but can't find the solution

Thank you

**Comment by JKE-be** [comment]
Hi @Leif0,

This tracker is for bugs with Odoo, please use forum.odoo.com for this kind of question...

About your question, you should be able to use "invoice_line/account_id/.id" to force to use the database_id instead of external_id.

Best regards

JKE
