### ISSUE TITLE
[10.0][9.0] Checks can't be Cancelled or Voided - Journal Items are not reverted

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#14502]
Impacted versions:
9.0 and 10.0
Steps to reproduce:
1. Create a Payment with the "Check" option
2. Print the Check
3. Cancel it

Current behavior:
After a check being cancelled, it's supposed to be VOIDED, and it should not be reused. And additionally its Journal Items should be reverted, not just disappear.

Expected behavior:
Have a Voided/Cancel state for Check payments. As some checks might be printed by error, returned or any other type of situation that can cause a check cancellation.

**Comment by edsersolis** [comment]
Current behavior with this is that when canceling it moves the check back to draft. This can be right but after a 'void' stage as @gustavovalverde says and only possible if the check was never printed out.

**Comment by gustavovalverde** [comment]
@Yenthe666 Are we missing something or is this actually an issue?

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

Thanks a lot for your report and for pinging me. I however have very little knowledge about the check part, I never use it personally.
@qdp-odoo can answer this one for you.

**Comment by qdp-odoo** [comment]
no, I can't :-s

**Comment by Yenthe666** [comment]
Okay, I revert my statement. Who can we ping good man? 😉

**Comment by qdp-odoo** [comment]
@fhe-odoo maybe?

**Comment by fhe-odoo** [comment]
Yes, I have a task open for this among other few improvements to checks. The ball is on my side.

**Comment by gustavovalverde** [comment]
Oh, that's good news. 

Is there an estimate time to completion of this fix? It is just to know if we can wait for it or if we'll have to hire a developer for this, as this is behavior is illegal in some LATAM Countries and can also generate frauds as the Journal Entries just disappear instead of being reverted when a check is cancelled.

**Comment by fhe-odoo** [comment]
There is no set time to completion.

**Comment by gustavovalverde** [comment]
Thanks for the answer. We'll do the needed effort to solve this issue.

Is there any guidance that you can provide us so we can also give you a hand with a  PR? And with "guidance" I mean, point us to the modules or methods that need to be changed, or the (general) recommended approach to fix this.

**Comment by fhe-odoo** [comment]
Almost done.

Community:
Branch: https://github.com/odoo-dev/odoo/tree/master-account-check-printing-hbh
Compare: https://github.com/odoo/odoo/compare/master...odoo-dev:master-account-check-printing-hbh
PR: https://github.com/odoo/odoo/pull/14492/files

Enterprise:
Branch: https://github.com/odoo-dev/enterprise/tree/master-account-check-printing-hbh
Compare: https://github.com/odoo/enterprise/compare/master...odoo-dev:master-account-check-printing-hbh
PR: https://github.com/odoo/enterprise/pull/599/files

**Comment by gustavovalverde** [comment]
Great!, Thanks @fhe-odoo ;)

**Comment by gustavovalverde** [comment]
Will this be backported to v10 when merged?

**Comment by qdp-odoo** [comment]
no, this targets master.  It is considered as improvements (missing features) and therefore not as bugs. I'm closing this issue for the same reason.

Thanks

**Comment by gustavovalverde** [comment]
It seems something was forgotten here. Even though this is being seen as an usability thing, and it's a part of it. There's also a huge issue as I pointed out in the issue:

> And additionally its Journal Items should be reverted, not just disappear.

Disappearing the journal items without further logging or tracking could cause serious fraud and auditing problems. I don't even know how this is being handled right now.

**Comment by vcloud9ray** [comment]
In v11 the Journal Entry is removed, but the cancelled Check document remains.

Shows VOID when printed:

![image](https://user-images.githubusercontent.com/31354495/31416784-4c04ba14-ade0-11e7-8ae7-d316e44458b8.png)

I just showed this to a client.  No issues with the removal of the Journal Entry - if you allow cancelling in the first place, you are allowing the GL to be written in pencil anyway.

**Comment by edsersolis** [comment]
The entry shouldn't be removed but instead a reversal entry should be generated. 

This is a step which we're happy of and better than it was, but thinking on the accounting audit side the entry shouldn't be removed but reversed with another entry when voided. Although most customers that don't aren't much into accounting and don't think on the auditing side will be OK with this approach.

**Comment by vcloud9ray** [comment]
If you take the position that the entry shouldn't be removed, then you could also take the position that you should not allow cancelling of the payment, but should refund the payment by creating a Refund Invoice and reconcile it with the payment.

The way most of my Customers see it is (1) either you are allowed to edit a posted entry or (2) you are not.  If you are, then deleting is an edit.  If you are not, then you shouldn't be allowed to cancel the payment in the first place.

The only way to make auditors happy is to not allow editing or cancelling of anything, but instead to create reversal documents with reversal entries under them.
