### ISSUE TITLE
[9.0] model method calls itself

### ISSUE THREAD

**Issue by thomas15v** [odoo/odoo#14508]
Impacted versions:
9.0

Steps to reproduce:
Create a method like this in any model:

```python
@api.model
def create(self, vals):
   print 'test'
   return super(SuperClassName, self).create(vals)
```

Current behavior:
The create method gets executed 2 times.

Expected behavior:
It would be more performant that it only get called once.

Video/Screenshot link:
https://youtu.be/JbP_JnHQOHM

**Comment by JKE-be** [comment]
Cannot reproduce...
