### ISSUE TITLE
[IMP] P&L reporting enterprise version

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#14506]
Impacted versions:
- v19
Steps to reproduce:
- This is not a bug, but a question how we can best propose a improvement on the Dutch Enterprise reporting app (l10n_nl_reports). 

Since version 10 we have a new COA (see https://github.com/odoo/odoo/commit/2eecf81a0e1c5b0dac224125abe9d1c8f0164ff9#diff-9055a672f7201a3a7f0a708edc6b30e7)

In this new COA are tags set on the P&L accounts. Those are perfect and can be used to make a more detailed P&L report. But there reporting of the enterprise version is not adapted to the new tags on the accounts.

So i want to propose a PR to the l10n_nl_reports module if that is ok by you guys. But if you say it will not get merged in V10, then i will do it another way.

So please let me know.

CC @Yenthe666

**Comment by Yenthe666** [comment]
Hi @ploegvde,

It is always positive to see somebody trying to change and improve things, so thank you for that!
If I understand this correctly you want to make a PR that makes the COA tags and the PL accounts match up with eachother? Could you give us a bit more details?
@qdp-odoo think we could start a little discussion about this here?

Regards,
Yenthe

**Comment by ploegvde** [comment]
What i mean is this.

In the P&L report we have a cost section. The sub of the cost can be split by the group of cost per tag.

See the image, where you can see that the Cost (Kosten) has a sub of Employee cost (Personeelskosten). That employee cost is now a tag set on de Dutch default COA on several accounts, but are not used in reporting.

The goal is to make sub totals on the account tag, so that you have more detail.

![29-11-2016 11-32-41](https://cloud.githubusercontent.com/assets/7593317/20706782/3336a7f4-b629-11e6-9597-13b353e326af.png)

**Comment by Yenthe666** [comment]
Thanks for the extra info. Sounds like a really good idea to me, who doesn't like more detailed accounting reports. @qdp-odoo would you consider accepting this or not?

**Comment by ploegvde** [comment]
Thanks. If we do not do it, then there is no use in adding tags to the accounts. The are there to do reporting ;)

**Comment by qdp-odoo** [comment]
looks ok to me :-) 

my only concern is that it should be able to display a correct PL if not tag are set on accounts (something like a section to display the accounts with no tags set?).

**Comment by Yenthe666** [comment]
@ploegvde looks like you've got your approval. I hope you come up with a neat PR 😉

**Comment by Yenthe666** [comment]
@ploegvde any update on this one? 👍

**Comment by ploegvde** [comment]
Still important, but lack of time. We will do it for sure.

**Comment by Yenthe666** [comment]
Ahh that is always the same problem, no? Keep me updated.

**Comment by ploegvde** [comment]
See work done on #18572
