### ISSUE TITLE
[10.0] account_tax_cash_basis: Amount set to 0

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#14501]
Impacted versions:

10.0

Steps to reproduce:

- Set properly the taxes to use tax cash basis
- Set a different account for paid and received tax (not sure if related).
- Make an invoice and pay it (one for customer and one for supplier both have the problem).

Current behavior:

- Tax cash basis journal Items in 0.

Expected behavior:

- Properly set the journal items with the expected amounts.

[Video](https://youtu.be/cENl1YBcexo)

**Comment by nhomar** [comment]
as an extra information, those are the only modules installed the one in the video.

**Comment by nhomar** [comment]
I am paying invoices from the payment button.

Reproduced in runbot:

![](http://screenshots.vauxoo.com/nhomar/Selection_077.png)

**Comment by nhomar** [comment]
Paying with bank statements achieve the same result:

![](http://screenshots.vauxoo.com/nhomar/Selection_078.png)

**Comment by qdp-odoo** [comment]
based on the vido, I confirm this is a bug. I'll check that

**Comment by qdp-odoo** [comment]
bugfixed in 9 and forward ported to 10 earlier this day
