### ISSUE TITLE
POS ticket printing problems

### ISSUE THREAD

**Issue by davidabsenta** [odoo/odoo#145113]
Impacted versions: 17

I have two problems with printing the POS ticket. The first is that when you enable the automatic printing of the ticket nothing happens, when you confirm the payment it does not automatically print the ticket and the second problem is that when I press print, the ticket and a second blank sheet appear.

**Comment by nimdasx** [comment]
Yes, that’s correct. This problem still exists until now

**Comment by nimdasx** [comment]
update : fixed in lastest source code
