### ISSUE TITLE
currency amount and currency symbol are wrong in account journal dashboard

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#14513]
Impacted versions:9.0

Steps to reproduce:create a new bank/cash journal with currency other than company currency. Then receive any payment in that currency. 

Current behavior:In the  journal dashboard, for that new journal, amount will be showed in company currency but the currency symbol will be showed in journal currency

Expected behavior: should show amount in journal currency.

Video/Screenshot link (optional):

**Comment by csnauwaert** [comment]
Hello,

This should be fixed in the latest 9.0 version.

Best regards
