### ISSUE TITLE
[10.0] Error on validate customer invoice

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#14539]
**Impacted versions:** 10.0

**Steps to reproduce:**
Using product [E-COM12] Self Build:
1. Set Product Type = Stockable Product
1. Set Invoicing Policy = Delivered Quantities
1. BOM Type = phantom
1. Set Product Category Costing Method = Real Price
1. Set Product Category Inventory Valuation = Perpetual
1. Create Sales Order for product [E-COM12] Self Build
1. Validate delivery
1. Create Invoice
1. Validate Invoice

**Current behavior:**
Odoo Server Error:
AttributeError: 'sale.order.line' object has no attribute '_get_bom_component_qty'

**Expected behavior:**
Invoice should validate

**Video/Screenshot link (optional):**

![image](https://cloud.githubusercontent.com/assets/7604932/20780681/199f1148-b73a-11e6-8eac-6e8c22fa0222.png)

![image](https://cloud.githubusercontent.com/assets/7604932/20780692/3050ccf6-b73a-11e6-9a51-70c06657a268.png)

![image](https://cloud.githubusercontent.com/assets/7604932/20780714/71f2f166-b73a-11e6-93f0-eb1f40fed55b.png)

![image](https://cloud.githubusercontent.com/assets/7604932/20781014/ecedfc6a-b73c-11e6-8abe-eba8da30c5b4.png)

![image](https://cloud.githubusercontent.com/assets/7604932/20780788/1a9bd256-b73b-11e6-804a-20e1fcb1f567.png)

**Comment by matt454357** [comment]
This is an obvious bug.  The method _get_bom_component_qty() is called once, but never defined.  Just try searching this repository:

![image](https://cloud.githubusercontent.com/assets/7604932/21064911/d8e92a7a-be1a-11e6-9de4-62f0a76621a1.png)

**Comment by archerdx** [comment]
The code does exist in version 11. No guarantees here, but I pasted the missing function in and it worked. (Added this code to the SaleOrderLine class under the _get_delivery_method function.)

```    @api.multi
    def _get_bom_component_qty(self, bom):
        bom_quantity = self.product_uom._compute_quantity(self.product_uom_qty, bom.product_uom_id)
        boms, lines = bom.explode(self.product_id, bom_quantity)
        components = {}
        for line, line_data in lines:
            product = line.product_id.id
            uom = line.product_uom_id
            qty = line.product_qty
            if components.get(product, False):
                if uom.id != components[product]['uom']:
                    from_uom = uom
                    to_uom = self.env['product.uom'].browse(components[product]['uom'])
                    qty = from_uom._compute_quantity(qty, to_uom)
                components[product]['qty'] += qty
            else:
                # To be in the uom reference of the product
                to_uom = self.env['product.product'].browse(product).uom_id
                if uom.id != to_uom.id:
                    from_uom = uom
                    qty = from_uom._compute_quantity(qty, to_uom)
                components[product] = {'qty': qty, 'uom': to_uom.id}
        return components```

**Comment by Yenthe666** [comment]
This has been fixed in the meanwhile:
https://github.com/odoo/odoo/blob/d76237e038ac379ae96e2c72848a013731c3de03/addons/sale_mrp/sale_mrp.py#L108

Function:
https://github.com/odoo/odoo/blob/10.0/addons/sale_mrp/sale_mrp.py#L60-L81

Regards,
Yenthe
