### ISSUE TITLE
nothing provides python3.11dist needed by odoo17.0-1.noarch

### ISSUE THREAD

**Issue by wuxiao-ling197** [odoo/odoo#145375]
Impacted versions: odoo 17.0

Steps to reproduce: https://nightly.odoo.com/17.0/nightly/rpm/odoo.repo

Current behavior: running the comond "sudo dnf install -y odoo" .

Expected behavior: running this commond successfully .

Video/Screenshot link (optional): 
![1](https://github.com/odoo/odoo/assets/77096395/e617d656-e313-4f09-99b2-40f59f51a781)

Support ticket number submitted via odoo.com/help (optional):

**Comment by TrungMC** [comment]
Though i never try to install Odoo with dnf install, I assume that that command will only install odoo after all the other prerequisites are ready. I guess you still have to follow the step by step guide to install odoo 17. Simply google you'll see a lot of results and youtube video. Nowadays, I'd just ask Bing
