### ISSUE TITLE
Business intelligence report does not list months in order 9.0e

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#14536]
Impacted versions:
9.0e
Steps to reproduce:
Accounting>reporting>business intelligence>invoices
Current behavior:
Lists group by months out of order, tested in runbot
Expected behavior:
List month in order
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

This has been changed in the meanwhile.

Regards,
Yenthe
