### ISSUE TITLE
[16.0] Error upon confirming purchase invoice for valued products

### ISSUE THREAD

**Issue by rDelaye** [odoo/odoo#145398]
Impacted versions: 16

Steps to reproduce:
- Setup a product to use a FIFO costing method (and maybe set tracking as serial number)
- Purchase the product and create the invoice
- Keep invoice data as is, confirm

Current behavior: A traceback appear because Odoo cannot convert a price in given currency. Caused by lack of date.
This does not happens if invoice date is filled.
Traceback:

```
  File "/data/build/odoo/addons/purchase_stock/models/account_invoice.py", line 159, in _post
    svls, _amls = valued_lines._apply_price_difference()
  File "/data/build/odoo/addons/purchase_stock/models/account_move_line.py", line 152, in _apply_price_difference
    new_svl_vals_list, new_aml_vals_list = line._generate_price_difference_vals(layers)
  File "/data/build/odoo/addons/purchase_stock/models/account_move_line.py", line 308, in _generate_price_difference_vals
    aml_price_unit = aml.currency_id._convert(aml_gross_price_unit, aml.company_id.currency_id, aml.company_id, aml.move_id.invoice_date, round=False)
  File "/data/build/odoo/odoo/addons/base/models/res_currency.py", line 268, in _convert
    assert date, "convert amount from unknown date"
AssertionError: convert amount from unknown date
```

Expected behavior: No traceback should happen, but we should be prompted by a message indicating that "You must set a invoice date" (because invoice from purchase orders does not set them automatically).

**Comment by chrisandrewmann** [comment]
I'm seeing example the same behaviour. 
16.0 Enterprise running on Odoo.SH, product category set to FIFO.
Keen to get this fixed ASAP as it's affecting a client.

**Comment by chrisandrewmann** [comment]
I've just tested runbot V17 and V15 which both provide a proper user error and not a traceback.
The message should read:

The Bill/Refund date is required to validate this document.

**Comment by thayifkabir** [comment]
I'm facing the same issue in odoo sh v16. Are any fixes available?

**Comment by chrisandrewmann** [comment]
Looks like this has been solved:
https://github.com/odoo/odoo/commit/03436a006f31f4bf42336fe31514161562c9b180
https://github.com/odoo/odoo/pull/145592
