### ISSUE TITLE
[10] Adding default stages to project is removed

### ISSUE THREAD

**Issue by JurreCl** [odoo/odoo#14530]
Impacted versions: 9, 9E, 10

Steps to reproduce: Go to project --> Settings --> Stages --> Stage

Current behavior: The option to make a stage default in a new project is removed

Expected behavior: Expected the button to be there.

Video/Screenshot link (optional):
See issue #10959 

Main concern is that the project module will keep adding new (and possible duplicate stages) when defining a new project. This results in confusion for the users.

**Comment by mart-e** [comment]
Hello,

Why do you create a duplicate? Please let's keep the discussion on one issue if it is the same

**Comment by Yenthe666** [comment]
For those who should ever find this topic and want to know what the 'original' topic was.. you can find it here: https://github.com/odoo/odoo/issues/10959
