### ISSUE TITLE
Messages under projectform are missing [10.0]

### ISSUE THREAD

**Issue by mgielissen** [odoo/odoo#14538]
message_ids field in project form is removed in version 10.0? 

Code below is from v9, using this code restores the messages under projectform

                <div class="oe_chatter">
                    <field name="message_follower_ids" widget="mail_followers" help="Follow this project to automatically track the events associated to tasks and issues of this project." groups="base.group_user"/>
                    <field name="message_ids" widget="mail_thread"/>
                </div>

**Comment by Yenthe666** [comment]
Hi @mgielissen,

Thanks for the report! Quite a good catch there.
@mart-e I don't think this was intended on purpose. Can we add it again?

**Comment by mart-e** [comment]
No it is intended, I already answered on the mailing list where the question was asked :)

https://www.odoo.com/groups/community-59/community-21697041?mode=thread&date_begin=&date_end=

> Hello,
>
> Indeed, it was removed (https://github.com/odoo/odoo/commit/ff4cffd5) 
> because we want to focus the discussion to happen on the tasks. It was 
> not clear who was receiving the messages.
> 
> You can add the message_ids back via a inherited view, the feature is 
> still there but it was a usability decision to remove it from the view 
> in standard.
> 
> Martin

**Comment by Yenthe666** [comment]
Oh, now that is a shocker.. I actually liked it. Okay thanks.
