### ISSUE TITLE
[10.0] Traceback with email template including a report and wkhtmltopdf not installed

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#14535]
**Impacted versions:**
10.0

**Steps to reproduce:**
Odoo js enviroment, has  kind of [global var](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/report/static/src/js/qwebactionmanager.js#L14) which is updated when the page is refreshed or only one time when a `ir_actions_report_xml` event is triggered, that var contains the wkhtmltopdf status

To reproduce the error, a demo invoice record was taken to make the tests

### The first scenario:
- wkhtmltopdf => installed
- Print the report => success
- Load email wizard (No attachments related to invoice) => Success

### The second scenario:
![image](https://cloud.githubusercontent.com/assets/10233975/20764489/0824a16c-b6f4-11e6-9fc2-45c45852b954.png)

**For the second scenario is necessary to restart the server after unistall wkhtmltopdf (Stop the server and start the server normally) and Refresh the page (F5)**
- wkhtmltopdf => Not installed
- Print the report => HTML VIEW ready to be printed by web browser
- Load email wizard (No attachments related to invoice) => Fail (Trace back Reported)

### The third scenario:

**Trigger the trace back when printing the report: with the button Print Invoice**
![image](https://cloud.githubusercontent.com/assets/10233975/20764538/3967f03a-b6f4-11e6-9702-f5eb5dc62023.png)

For the second scenario is necessary to restart the server after unistall wkhtmltopdf (Stop the server and start the server normally)
**NOTE: NOT REFRESH THE PAGE**

- wkhtmltopdf => Not installed
- Print the report => Fail (Trace back Reported)
- Load email wizard (No attachments related to invoice) => Fail (Trace back Reported)

Current behavior:
A raise error is triggered
Expected behavior:
Trigger the div modal instead of the traceback error
Video/Screenshot link (optional):

https://drive.google.com/file/d/0B_jQX2tloXM7Y3owWFBjczYyaGc/view

**Comment by JKE-be** [comment]
Yes, but in which use case you saoule uninstall wk, and continue to use an existing session ?

I think that when you uninstall postresql, that will be the same... à traceback... 

Wont fix

@sle-odoo :)

**Comment by moylop260** [comment]
@JKE-be 
I think that you are mixing apples and oranges.
If you uninstall postgresql you don't have a traceback from UX. In fact, you won't start odoo server.

If you uninstall wkhtmltopdf you can start odoo server and you won't have a traceback from UX if you print the report. Good!

But if you use `send email` button you will see a traceback from UX

[![IMAGE ALT TEXT](http://img.youtube.com/vi/IMNnGDFH3JE/0.jpg)](http://www.youtube.com/watch?v=IMNnGDFH3JE "Video Title")

**Comment by mart-e** [comment]
Hello,

When you uninstall a required dependency, I think it is expected to get a traceback, especially if you have some very specific steps like "not refresh the page".
I am not sure what you expect to get, it simply can not work.

**Comment by moylop260** [comment]
Hello @mart-e 
Thanks for reply

I have a video where if I print a report a traceback is not raised.
But if I try send email with this report attached we have a raised error.

Is this a expected behaviour?

http://www.youtube.com/watch?v=IMNnGDFH3JE

**Comment by mart-e** [comment]
Ok, I just tried, this real issue is that you get a traceback if you do not have wkhtmltopdf installed. There is not the requirement uninstall+donotrefresh.

My comment and the one from jke was that we do not support the fact of needing to uninstall a dependency that was previously installed if you have the issue only for the users with the window currently opened.

Obviously, you can not generate pdf attachment if you do not have wkhtmltopdf installed (and can not attach an html page).
Maybe, as an improvement, we could show a warning message to the user explaining why we are unable to generate the email.

**Comment by Yenthe666** [comment]
@mart-e I think that an informative warning to the end user would be neat. Perhaps we should label this wishlist?

**Comment by mart-e** [comment]
Done at 3642f1194244c66faa8dabb4be6abcfff789cda4 (and merged 7ccf4e60c86d80ce38e8e7f33d1d42940384306c by the way)
Thanks for the report
