### ISSUE TITLE
Wrong relationship between external IDs and product model.

### ISSUE THREAD

**Issue by oHigelin** [odoo/odoo#14534]
Impacted versions: 9.0c-20161117

Steps to reproduce: 
After importing all my products from csv file, I need to import inventory using external IDs of the products I have imported.
Import return Missing Error exception on last external IDs of my products (not the one from beginning).

Current behavior:
After investigation in model, and mostly in ir_model_data table where all external ID are stored, it appears that import module is not looking for product id in **product_template** table like mentionned in ir_model_data.model field, but in **product_product**.

Expected behavior:

Video/Screenshot link (optional):
Here is my request in ir_model_data table
![image](https://cloud.githubusercontent.com/assets/22914051/20762670/784934de-b727-11e6-8e1a-8d95755b2a56.png)

which exists in **product_template**...
![image](https://cloud.githubusercontent.com/assets/22914051/20762939/7068ee20-b728-11e6-835f-b36f607291a0.png)

...but error message say it is not present in **product_product**.
![image](https://cloud.githubusercontent.com/assets/22914051/20762839/0df50e68-b728-11e6-8b95-ebb0112ddbd5.png)

**Comment by gdgellatly** [comment]
Try SELECT * FROM product_product WHERE product_tmpl_id=20664, although if
you decided not to import your product.product csv that could also be a
problem.

It is a bit confusing since product templates got renamed products and
products got renamed variants or some such name, but importing products is
actually product templates.  Probably your best bet is to just export your
actual products (variants) to get a new xml id and then use that for import.

**Comment by oHigelin** [comment]
Many thank for your answer.

I can hear you about your query: **SELECT * FROM product_product WHERE product_tmpl_id=20664**
This is the query that should be in import module linked to the product, but obviously it is not !
I will find a solution by "cheating" on IDs. I will certainly use a mapping between external IDs and internal IDs and create import files using internal IDS which will be safer.
I don't know about variants -> product in model. Is it in release 10 of Odoo ?
Is there any chance to have this bug fixed in release 9 of Odoo ?

**Comment by gdgellatly** [comment]
It's not a bug. The model relation hasn't changed since v5. It's just your
understanding of it. It's a bit confusing but nothing is actually wrong.

**Comment by Yenthe666** [comment]
Indeed, there is no bug here. This is the way it is intended to work.
