### ISSUE TITLE
Odoo Community /Entreprise

### ISSUE THREAD

**Issue by AEK-BKF** [odoo/odoo#14549]
Hi all,

I'm working at a company over 400 employees, and I've a mission to install Odoo. So, I've some questions before I start the development : 
1 - Which version should I use ?
2 - Community or Enterprise ? 
3 - Is Enterprise Edition source code easy to edit ?
4 - Can I use Odoo Entreprise for free without non-free apps ?

Thanks.

**Comment by Yenthe666** [comment]
Hi @AEK-BKF,

Thanks a lot for your report. The Github tracker however is for bugs, not for asking questions or anything that is not bug related.
The best thing to do is to create a new topic on the help forums (help.odoo.com), where there are plenty of partners and people that can help you answer this! 

1 - Which version should I use ?
=> The best is to probably use Odoo 10, this is the newest version and has the longest support (and the most features)
2 - Community or Enterprise ?
=> This depends a lot on your requirements and which functionalities you need. This would require more information.
3 - Is Enterprise Edition source code easy to edit ?
=> It edits as easily as the community, so yes.
4 - Can I use Odoo Entreprise for free without non-free apps ?
=> You can't use Odoo Enterprise for free, you will always need to pay the monthly fee.

Regards,
Yenthe


Regards,
Yenthe

**Comment by AEK-BKF** [comment]
Thanks a lot @Yenthe666  and sorry for the bad place of my question, you can delete it :)

**Comment by Yenthe666** [comment]
Hi @AEK-BKF,

No problem, you're welcome. Closing the issue is enough, best of luck with Odoo!

Regards,
Yenthe

**Comment by dreispt** [comment]
@AEK-BKF I strongly advise you to find experts in your country and discuss your needs with them. Even if you decide to implement it yourself, you will have a plan B.
