### ISSUE TITLE
Any idea to do this in MEAN stack?

### ISSUE THREAD

**Issue by suriyaJaay** [odoo/odoo#14547]
hi team,

have any ideas to create this app in MEAN stack in future.?

as per documentation it really hard to understand. 

Thank you

**Comment by Yenthe666** [comment]
Hi @suriyaJaay,

What are you actually asking? It is not clear to me what you want. If you're talking about mean.io and to integrate Odoo in FullStack: nope, that will not happen.

Regards,
Yenthe

**Comment by suriyaJaay** [comment]
thanks for the response. what am trying to asking is that you have any  idea about recreate this same app on node and angular ? thats it. now confirmed. there is no idea from your side. 

but onething need to say. its really damn awesome man. this is what am trying to create personally. !!
 all the best
thanks man

**Comment by Yenthe666** [comment]
Hi @suriyaJaay,

Making the shift from the current system to the FullStack would be quite a big change and quite a lot of work. @mart-e can you confirm it will not be done?

Regards,
Yenthe

**Comment by mart-e** [comment]
Yes I confirm we won't rewrite Odoo in node (I want to ask, why would you want to do that? :scream: )
And keep in mind that the value of Odoo is not only on its framework (maybe you can make it again in a different tech) but in the business code which would take an enormous amount of work.
