### ISSUE TITLE
Save attachment to system folder along with database

### ISSUE THREAD

**Issue by anandgodavarma** [odoo/odoo#14546]
Impacted versions:
7
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @anandgodavarma,

Please create an issue with a detailed description, otherwise we cannot help you.
Also note that Odoo V7 is no longer supported for bug fixing.

Regards,
Yenthe

**Comment by anandgodavarma** [comment]
I have created system parameter with 'ir_attachment.location' and value 'file"///filestore' 
but when I am adding an attachment it does not saving to system folder

**Comment by anandgodavarma** [comment]
I used this link http://snippetbucket.com/2014/06/webdav-openerp/

**Comment by anandgodavarma** [comment]
Please dont close the issue

**Comment by Yenthe666** [comment]
Hi @anandgodavarma,

The Github tracker is for bugs in the official code. You're having questions about how to use the filestore and store images, that is something for the Odoo help forums (help.odoo.com).
Please post your question there, there are plenty of people to help you there.

Regards,
Yenthe
