### ISSUE TITLE
Can't create Inventory Adjustments under multi-company

### ISSUE THREAD

**Issue by mycobraking** [odoo/odoo#14542]
Impacted versions:
v10
Steps to reproduce:
add Inventory 
add new company COM1 , COM2 
add users u1@ under COM1 , u2@ under COM2 
Current behavior:
u2@ can't create Inventory Adjustments 
if u2@ change to default company My Company will can. 
Expected behavior:
Create Inventory Adjustments 
Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
It sounds like lack of configuration on second company like inventory
accounts, locations etc. You really need to give more detail.

**Comment by mycobraking** [comment]
1. Create new db ,
2. Add new companies name is COM1 , COM2
3. Add new users , user one under COM1 , user two under COM2
4. Add INVENTORY app and apply for tow users
5. login user one or two , then go into Inventory Control -> Inventory Adjustments
6. CREATE : 

> Odoo Warning - Access Error
> The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
> 
> (Document type: stock.warehouse, Operation: read)
7. when change one user under to My company (default) then is ok

**Comment by gdgellatly** [comment]
Multi company generally needs a bit of config. Installing modules and just
working is really just single company although even then only at a basic
level.

Your error indicates you haven't configured the second company warehouse.

**Comment by mycobraking** [comment]
I think program default  warehouse to WH , and I can't find and edit it within setup . so I want any one try it. thanks.

**Comment by mlaitinen** [comment]
Does 8955d15e9d92faa0e691fd432c0a644c246cf7ba fix your problem?

**Comment by sle-odoo** [comment]
as @mlaitinen said, the mentioned revision should have fixed your issue
feel free to comment if it didn't
