### ISSUE TITLE
Odoo 10 Creation new module

### ISSUE THREAD

**Issue by AEK-BKF** [odoo/odoo#14552]
I tried to create new module via this command :
`odoo-bin scaffold mylodule addons`
but I got ths error :
_bash: odoo-bin: command not found..._

I can't find odoo-bin !

**Comment by Yenthe666** [comment]
Hi @AEK-BKF,

This question should be for the help forum too. 😉 
Are you in the correct location? You should be in the folder where the odoo-bin.py file can be found.
You can then trigger the scaffold with:
`./odoo-bin scaffold mymodule addons`

Regards,
Yenthe

**Comment by grexe** [comment]
For me (using Arch/Manjaro Linux and Odoo 10) it was just `odoo`, but the scaffold template used outdated XML tags `openerp` instead of `odoo`, which is a separate issue.

**Comment by Yenthe666** [comment]
@grexe are you sure of that? I've fixed that issue months ago. See https://github.com/odoo/odoo/pull/14129

**Comment by grexe** [comment]
just tried yesterday with Odoo version 10.0-20161028 (latest package of AUR, sadly) and got "openerp" tags in some of the files:
```
odoo scaffold template test
[grexe@grexbox addons]$ odoo --version
Odoo Server 10.0-20161028
[grexe@grexbox addons]$ grep -R openerp test
test/template/demo/demo.xml:<openerp>
test/template/demo/demo.xml:</openerp>
test/template/__manifest__.py:        subtitle on modules listing or apps.openerp.com""",
test/template/__manifest__.py:    # Check https://github.com/odoo/odoo/blob/master/openerp/addons/base/module/module_data.xml
test/template/views/views.xml:<openerp>
test/template/views/views.xml:</openerp>
test/template/views/templates.xml:<openerp>
test/template/views/templates.xml:</openerp>
```

**Comment by Yenthe666** [comment]
@grexe that is why you don't see it 😉 The fix was added on 14/11/2016, after your Odoo version.

**Comment by Mahmoud-Alaa-Eldeen** [comment]
For me it solved when using root user on terminal.
