### ISSUE TITLE
Typo Dutch ToDo

### ISSUE THREAD

**Issue by HouseK** [odoo/odoo#145695]
Impacted versions: at least 17.0

Steps to reproduce: Install new instance.

Current behavior: word used: To-so

Expected behavior: word used: To-do

Video/Screenshot link (optional): no

Support ticket number submitted via odoo.com/help (optional): no

exact location: https://github.com/odoo/odoo/blob/39eaf87b1b9d4720d850cd70ddcd390f63522bbd/addons/project_todo/i18n/nl.po#L31

**Comment by avdb13** [comment]
Not a big fan of correcting small typos with PRs. It would be nice if there was a step in actions that did typo checking on the i18n folder. Something like hunspell would do the job.

**Comment by ossimantylahti** [comment]
@HouseK You should fix this error in Transiflex. https://app.transifex.com/odoo/odoo-17/language/nl. It can be edited there and gets automatically pulled to Odoo branches.

**Comment by HouseK** [comment]
Oh thanks!

I created a suggestion.
