### ISSUE TITLE
[9.0, 10.0] Bcc email address visible

### ISSUE THREAD

**Issue by matthieujoossen** [odoo/odoo#14567]
Impacted versions: 9.0, 10.0

It seems that there is a problem Python smtp librairy with Bcc in sending email (http://stackoverflow.com/questions/31065998/python-smtplib-bcc-issue).
I tested the proposed solution replacing in addons/base/ir/ir_mail_server.py file line: 
`smtp.sendmail(smtp_from, smtp_to_list, message.as_string())`
by:
`message_str = '\n'.join([l for l in message.as_string().split('\n') if not l.startswith("Bcc: ")])`
`smtp.sendmail(smtp_from, smtp_to_list, message_str)`

This solution is working.

**Comment by pedrobaeza** [comment]
Handled in 2445f9e, so I close.
