### ISSUE TITLE
[10.0] Decimal separator option in CSV import doesn't work

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#14572]
Impacted versions:

10.0

Steps to reproduce:

See https://youtu.be/riU6rg0ANHQ

Current behavior:

During an import on product and supplierinfo, the decimal separator option in CSV import doesn't work

Expected behavior:

Decimal separator on CSV import should work.

Video/Screenshot link (optional):

https://youtu.be/riU6rg0ANHQ

**Comment by adrienpeiffer** [comment]
OPW 695837

**Comment by JKE-be** [comment]
Until now, the parsing is only done on float from the current model.
That need to be fixed/improved.

Thanks for the reporting

**Comment by JKE-be** [comment]
Hi @adrienpeiffer,

Can you confirm that with this patch https://github.com/odoo-dev/odoo/commit/10ad62c00452a9bd12d20bef588995280afad7e7, the import works for you ? 

Thank you 

JKE
