### ISSUE TITLE
[17][Sales] Headers and Footers do not work

### ISSUE THREAD

**Issue by eric-it6** [odoo/odoo#145894]
Impacted versions: (newest) 17.x under Ubuntu 22.04

We would like to create offers in Odoo, but this does not work because the headers and footers do not work. The wkhtmltox dependency is installed in the latest version, as described in the following documents:
[1]: https://github.com/odoo/odoo/wiki/Wkhtmltopdf
[2]: https://www.odoo.com/documentation/17.0/administration/install/source.html

I am surprised that dependencies have to be installed independently here, whose repo is not up-to-date and is no longer maintained. In the odoo-server.log I do not get an error message, which can be used to investigate the problem.

Are there any other solutions to solve the problem? Can you say when there will be an alternative to this tool?

Best regards

**Comment by eric-it6** [comment]
Hello, I was able to locate the problem after a long search in the log. The following line is conspicuous:
<pre>
2023-12-12 10:47:07,787 5754 INFO dev werkzeug: 127.0.0.1 - - [12/Dec/2023 10:47:07] "GET /websocket HTTP/1.1" 400 - 1 0.000 0.002
</pre>

After changing the proxy for processing requests to a websocket and emptying the cache, the document generation works without any problems.

Therefore, the first part of my request is superfluous and I would like to know if there is an alternative in sight.

Best regards

**Comment by gdgellatly** [comment]
If you look at other issues (copious), or Odoo XP recent updates the plans are all laid out. Yet another issue asking the same thing probably isn't helpful.

**Comment by eric-it6** [comment]
Then it would probably be useful to include this in the Odoo documentation. I haven't found anything current on the subject and initially thought there was a connection to version 17. It's really extremely frustrating when you pay a lot of money for the software and set it up elaborately to be slowed down because of such a problem. I would still like to thank you for your help and close the ticket.

Best wishes for success
