### ISSUE TITLE
Odoo9 Community Manual Reconicliation

### ISSUE THREAD

**Issue by armbakri** [odoo/odoo#14583]
Impacted versions: 9

Steps to reproduce: When i entry my partner open balances though jounal entry , i cann't reconcile those open balances with customer payments

Current behavior: there is no manual reconcilition menue

Expected behavior: Reconcile The Partner payment with it's balances from journal entries like invoices

Video/Screenshot link (optional):

**Comment by csnauwaert** [comment]
Hello,

You can reconcile in Odoo in 2 different ways:

1) reconcile your bank statement with already existing move lines or payment. To do so, either go to the bank statement and click on the "reconcile" button or from the Accounting dashboard, click on the more menu of a bank/cash journal and select "reconcile"
2) reconcile your payment with existing move or invoice. To do so, go to accounting dashboard, click on the more menu of a sale/purchase journal and select "payment matching".

Those two use case should be enough to reconcile most entries. In last ressort you can also select multiple entries in the journal items menu and then click on the "more" menu on top and select "reconcile".

Best regards
