### ISSUE TITLE
Odoo 10 : blank page on localhost:8069 

### ISSUE THREAD

**Issue by AEK-BKF** [odoo/odoo#14581]
I've installed Odoo 10 on Centos7, created database and logged in successfully.
But no thing displayed !! just blank page ! what's the mistake ?

**Comment by AEK-BKF** [comment]
Ok I found the problem, just clear firefox history !

**Comment by tienhieuD** [comment]
Go to PGAdmin and run this script.
```SQL
UPDATE ir_attachment 
SET mimetype = 'text/javascript' 
WHERE mimetype ='text/plain' 
and datas_fname like '%.js';
```
Then F5 your browser.
![temp](https://user-images.githubusercontent.com/16768170/29199376-a671c288-7e76-11e7-9e92-b5343f34095c.png)

![temp](https://user-images.githubusercontent.com/16768170/29199413-04edacb4-7e77-11e7-8871-55ab028105a6.png)

**Comment by saadis01** [comment]
Thank you! Thanks worked for me!!

**Comment by tomaspworld2017** [comment]
It work just few minutes. 
When I tried to install a new application blank page came again.
Any suggestion

**Comment by tomaspworld2017** [comment]
It works for a while, but when I tried to install applications the Blank Page came back again.
Any suggestion

**Comment by edper** [comment]
@tomaspworld2017: In my case I just redo what @tienhieuD every time I installed a new App (e.g. Manufacturing, CRM etc) and voila you will see it again.

**Comment by Yenthe666** [comment]
@ged-odoo a lot of these reports are popping up again. Could it be we have another / new assets compilation issue?

**Comment by tomaspworld2017** [comment]
Well, it works. It's a little disgusting to have to do the same every time but it works.

**Comment by ibrahim08** [comment]
what is the solution in case of linux? it's happens to me when installing a custom module, it's work normally in local network but when i try to access from a different  network i see a blank gray screen.

**Comment by alexbnk** [comment]
Thanks so much !!!!

**Comment by inspireaman** [comment]
@tienhieuD , @tomaspworld2017  First,Thank you for your solutions.

We installed odoo 10 on ubuntu 16.04.
when we login in to demo db as admin from remote system, page  was loading ...........but, nothing comes to view.

kindly help us to resolve this..

Thanks in Advance.

**Comment by tienhieuD** [comment]
@inspireaman you should try this https://m.facebook.com/story.php?story_fbid=1927479740907670&id=1858655611123417

**Comment by baschelik** [comment]
> what is the solution in case of linux? it's happens to me when installing a custom module, it's work normally in local network but when i try to access from a different network i see a blank gray screen.

blank screen after login means you go to ir_attachments table of your odoo database, find all the entry with value 'web/content' in column name and delete them, odoo will regenerate them and voila, you got your odoo back

**Comment by Yemeni** [comment]
I am using Linux, so I just directly used the console 
After logging in to your system, switch to postgres user
`sudo su - postgres`
go to your odoo databse, in my case it's odoo_db
`psql odoo_db`
write the query mentioned by @tienhieuD 
```
UPDATE ir_attachment 
SET mimetype = 'text/javascript' 
WHERE mimetype ='text/plain' 
and datas_fname like '%.js';
```

**Comment by kraken-a** [comment]
you have been perhaps messing with a js file/code lines so just comment everything (inside the js file only) and reload
