### ISSUE TITLE
odoo no supporter <javascript async

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#14595]
Impacted versions:8.0

Steps to reproduce:
insert into qweb MAin Layout tag <head> the javascript code:
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-xxxxxxxxxxxxxxxxxxx"
     data-ad-slot="2444412900"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
Current behavior:

Expected behavior:
Malformed XML document:
This page contains the following errors:error on line 28 at column 15: Specification mandate value for attribute async Below is a rendering of the page up to the first error.
Close

Video/Screenshot link (optional):

best regards Rocco Cesetti

**Comment by adekock11** [comment]
@roccocesetti try: async="async" instead

**Comment by roccocesetti** [comment]
thanks ,is ok!

**Comment by rajeshkushwahsironj** [comment]
Sir please help.

This page contains the following errors: error on line 2 at column 15: Specification mandates value for attribute async Below is a rendering of the page up to the first error.

My blogs site https://www.shayari.tech/
