### ISSUE TITLE
odoo10 new issue by incoming email

### ISSUE THREAD

**Issue by myworking82** [odoo/odoo#14594]
Impacted versions: 10

Steps to reproduce:
1. I need automated create new issue from incoming email on specific project
2. Which template of in email i have to used, which tags?

Current behavior:
When i put "Fetch Now" on my Setting -> Email -> "Incoming Mail Server" i got only new email and odoo admin change tags him self

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

Sorry but this bug report is way to vague and has not enough information.
The Github tracker is only for bugs in the official Odoo code anyways so closing this bug report for those two reasons. You can always ask these kind of questions on the official help forum (help.odoo.com)

Regards,
Yenthe
