### ISSUE TITLE
[v8.0] Ecommerce Search Bar no width when only 1 page of products.

### ISSUE THREAD

**Issue by grayousious** [odoo/odoo#1461]
Could not find this already reported. When using the shop search bar. If there is only one page of results the search bar has minimum width which ends up hiding any text already typed in there.
![1page](https://cloud.githubusercontent.com/assets/8126069/3753740/e69f0698-1814-11e4-84ae-50f0dddf28cf.jpg)

**Comment by Yenthe666** [comment]
Hi @grayousious,

Thank you for your report.
This issue has been fixed in the meanwhile. An example on the latest V8 source code:
![image](https://user-images.githubusercontent.com/6352350/27577774-334addc0-5b22-11e7-90a0-decbd8e4275d.png)

Regards,
Yenthe
