### ISSUE TITLE
[9.0+] Cannot add view to a specific dashboard

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#14612]
**Impacted versions:**
9.0, 9.0e, 10.0, 10.0e

**Steps to reproduce:**
1) Open up a Runbot instance on Odoo 9.0
2) Go to Reporting (`board` module)
3) Click on `Configuration` -> `Create Board`
4) Create a new Dashboard and call it "Test" for example
5) Go to `Sales` -> `Your Pipeline` for example
6) Open up `Favorites` and click on `Add to Dashboard`

**Current behavior:**
There is no option to choose which dashboard to add the current view to.

**Expected behavior:**
Like in Odoo 8.0, there should be a dropdown with the values `Dashboard / My Dashboard` and `Dashboard / Test` which allows the user the freedom to add the view to a dashboard of their choice.

**Video/Screenshot link (optional):**

Odoo 8.0 "Add to Dashboard"
![screen shot 2016-12-06 at 7 38 58 pm](https://cloud.githubusercontent.com/assets/1809451/20936628/f699fd78-bbeb-11e6-9d3b-5ada1348b73c.png)

Odoo 9.0 "Add to Dashboard"
![screen shot 2016-12-06 at 7 40 40 pm](https://cloud.githubusercontent.com/assets/1809451/20936635/fecca81a-bbeb-11e6-9b5a-06d6890d819d.png)

**Comment by jar-odoo** [comment]
@adekock11 
Agree with you.

I've attached video link for better knowledge.
[https://youtu.be/TgRsf_6-txM](url)

**Comment by Yenthe666** [comment]
@jar-odoo your URL is invalid. The correct URL is https://www.youtube.com/watch?v=TgRsf_6-txM 😉

**Comment by Yenthe666** [comment]
@mart-e perhaps we should reintroduce this?

**Comment by mart-e** [comment]
Hello,

Not really, we have removed all existing dashboards on purpose. We keep this feature as it is still useful for some people but do not want to push it so we kept only one dashboard.
Sorry
