### ISSUE TITLE
New Products are not visible in POS after installing pos_cache

### ISSUE THREAD

**Issue by skshivammahajan** [odoo/odoo#14620]
Impacted versions: 10

Steps to reproduce: After the pos_cache is installed and if we will create new products the new products are not visible in POS ?Why?

Current behavior: Kind of bug or issue 

Expected behavior: The new product should be visible even after installing  pos_cache
 
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @skshivammahajan,

Thank you for your report. I've just tested this on the latest code from Odoo and it works fine out of the box.
I simply created a new product named 'aNewProduct' and when I open the POS and search for it I can find it:
![image](https://cloud.githubusercontent.com/assets/6352350/20961706/89ab6d7a-bc66-11e6-9fa0-a056dfd6230c.png)
Are you sure that you've restarted the POS in order te load all the products in again?

Regards,
Yenthe

**Comment by skshivammahajan** [comment]
Have you installed the pos
_cache. ?

**Comment by skshivammahajan** [comment]
It work fine with pos .But it is causing problems when i installed pos_cache .
Can you please test the new product with pos_cache ?

**Comment by Yenthe666** [comment]
@skshivammahajan this is tested before having the pos_cache module installed and after having it installed, both work fine out of the box.
Could you try reproducing the issue on a runbot? (runbot.odoo.com)

**Comment by skshivammahajan** [comment]
@Yenthe666 as per your suggestion .I tried runbot and i found the same issue there ?
Check the runbot url  
http://184579-10-0-09b3a5.runbot8.odoo.com
I created three products 
1. One product before pos_cache - Works fine
2.Second  product after pos_cache  - Works fine
3.Third product again after pos_cache - Issue found (Product was not visible in  POS)
![pos product](https://cloud.githubusercontent.com/assets/22074370/20965147/6c8fb8fc-bc9a-11e6-9786-2de7da85fa4c.png)
![pos screen](https://cloud.githubusercontent.com/assets/22074370/20965148/6c9e3206-bc9a-11e6-9bef-a9f51a6579ef.png)

**Comment by Yenthe666** [comment]
Hi @skshivammahajan,

Thanks for the extra feedback. When I look at the runbot environment you've tested this on I can see that this product (test prod 03) is not found in the POS.
I've just tested this with a new product and I face the problem now too.
@jorenvo something for you?

Regards,
Yenthe

**Comment by skshivammahajan** [comment]
@Yenthe666 
@jorenvo 
Can you please look into this issue and help me to fix it ASAP ?
Thanks in advance .

**Comment by jorenvo** [comment]
The pos_cache module is very basic. Cache isn't automatically invalidated or recomputed. You have to do so either manually through the button on the pos.config form view, or by using the provided [Refresh POS Cache](https://github.com/odoo/odoo/blob/10.0/addons/pos_cache/data/pos_cache_data.xml) cron. This is also the reason we have the module blacklisted on runbot, because it causes too much confusion.

**Comment by Yenthe666** [comment]
@jorenvo is this documented somewhere? This sounds like a typical thing to add in the documentation. I didn't know anything about it either. :)

**Comment by skshivammahajan** [comment]
@jorenvo Thanks a lot .Hope it will work .

**Comment by jorenvo** [comment]
@Yenthe666 currently we have no user documentation for pos_cache I think. Maybe we should add some, but the module is not really meant to be used by a large amount of users, it's only for users with a relatively large amount of products. It's a stopgap measure to reduce the loading time of the POS frontend.

**Comment by skshivammahajan** [comment]
@jorenvo I tried the Refresh POS Cache cron but it didn't work .Can you also help me to find the button on the pos.config form view because i am unable to find any such button that page ?

So what's the final solution do you suggest to resolve this issue since this corn is not working fine ?

**Comment by agusddt** [comment]
Hello, I'm having the same problem. Any solution? Should I uninstall and install pos_cache to get POS updated? Or where is that pos.config option? 
Thanks!!

**Comment by xabispacebiker** [comment]
I have the same problem. The button is located at the POS Configuration > Point of sale.

![captura de pantalla 2018-04-15 a las 17 46 04](https://user-images.githubusercontent.com/1733884/38780330-1c5c4ad8-40d5-11e8-8b5a-08f6c3a7374b.png)

The fact is that it should be automatically refreshed upon adding new product to the point of sale.
