### ISSUE TITLE
Mass Mailing module allways spam

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#14623]
Impacted versions:8.0

Steps to reproduce:
Test or send Mass mailing 

Current behavior:
produce 
from --> bounce-xxxx@mydoamin.com
to     --> existing pippo@alterdomain.com

this mail finish to go allways in spam ,because the sender not exist,
because odoo generate bounce-xxxx@mydoamin.com for sender

Expected behavior:
from --> exsiting rocco@mydoamin.com
to     --> existing pippo@alterdomain.com

Video/Screenshot link (optional):
best regards Rocco Cesetti

**Comment by Yenthe666** [comment]
Hi @roccocesetti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
