### ISSUE TITLE
Incomplete product labels Odoo v8

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#14621]
**Impacted versions:** 

8.0

**Steps to reproduce:**

1. Install POS module on database.
2. Follow all the steps to finish pos installation.
3. Enable technical features on admin user
4. Import whatever test product db (test data should work too).
5. Go to Sales » Product variants, then select 80 products.
6. Click Print » Product labels.

**Current behavior:**

It will print/create a PDF file, with only 60 labels, if selected 16 products it will generate/print 12 labels (12 labels per page). In other words the labels are incomplete, something about a 75% are printed.
I'm using page size Letter, in case it matters.

**Expected behavior:**

It prints the selected number of products, 16, 80, 500, etc.

**Video/Screenshot link (optional):**

[incomplete-product-labels-odoov8.m4v.tar.gz](https://github.com/odoo/odoo/files/635868/incomplete-product-labels-odoov8.m4v.tar.gz)

**Comment by Ark74** [comment]
Hi again, i've found the missing labels generated at the system.
They are right there but out of the page, so that's why they can't be seen.
I found out trying to analize the output (pdf file) with inkscape, and there i could notice this.

Here the proof.
![inkscape-label](https://cloud.githubusercontent.com/assets/7444518/21747548/711a161c-d52f-11e6-8a3f-9494718f3b57.png)

To fix/change this go to `../addons/product/report/product_label.xsl` and change the **height_increment** to something like: 2.8 , test it out and set your preferred value.

I'll let this open for awhile for any comments or close it at your best interest.
Cheers & happy late new year!

**Comment by Yenthe666** [comment]
Hi @Ark74,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by Ark74** [comment]
Ohh, I guess I forgot about it. :smile: 
I'll test again sometime in the future.

Thanks for closing this down.
Cheers! :beers:
