### ISSUE TITLE
[10.0] base_geolocalization urllib issues

### ISSUE THREAD

**Issue by BzJB** [odoo/odoo#14636]
On one of our dev environments we encountered an issue where urllib would not open the link for the geolocalization.

We found that changing it to use urllib2 fixed this issue and think this might be better for compatibility.

**Comment by BzMB** [comment]
Hi,
I'm a colleague of BzJB.

We saw the label "need informations", but to be honest we struggle a little bit to give you more informations, let me try to explain why.

Into a server with a different hosting provider and potentially a different setup of python environment, the module works well with the urllib library.

But for some reason into a different server, same sourcecode (odoo base version), the call get refused and the raise exception executed (the call will not be executed and the following exception will be raise).

This how we fix (in bold what we change)
```

import json
import **urllib2**

from odoo import api, fields, models, tools, _
from odoo.exceptions import UserError


def geo_find(addr):
    url = 'https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address='
    url += **urllib2**.quote(addr.encode('utf8'))

    try:
        result = json.load(**urllib2**.urlopen(url))
    except Exception as e:
        raise UserError(_('Cannot contact geolocation servers. Please make sure that your Internet connection is up and running (%s).') % e)
    if result['status'] != 'OK':
        return None
```
Could provide a quick way to compare differences between urllib version into a server, maybe our bottleneck is there?

Thank you in advance.

**Comment by BzMB** [comment]
Hi @JKE-be , any chance to review our comments?
I attach a list of the python library installed on the server in which urllib is raising the exception.

`attrs (15.2.0)
Babel (2.3.4)
beautifulsoup4 (4.4.1)
bzr (2.7.0)
cchardet (1.0.0)
cffi (1.6.0)
chardet (2.3.0)
configobj (5.0.6)
cryptography (1.3.2)
cssutils (1.0.1)
cycler (0.10.0)
Cython (0.24)
decorator (4.0.10)
defusedxml (0.4.1)
Delorean (0.6.0)
dnspython (1.13.0)
dnsq (1.1.6)
docopt (0.6.2)
docutils (0.12)
ebaysdk (2.1.4)
ecdsa (0.13)
enum34 (1.1.5)
expiringdict (1.1.3)
feedparser (5.2.1)
flanker (0.4.38)
funcsigs (1.0.2)
gdata (2.0.18)
gevent (1.1.2)
greenlet (0.4.10)
gyp (0.1)
html5lib (0.999)
httplib2 (0.9.1)
humanize (0.5.1)
idna (2.1)
ipaddress (1.0.16)
jcconv (0.2.3)
Jinja2 (2.8)
keyring (7.3)
Landscape-Client (16.3+bzr834)
lasso (0.0.5)
launchpadlib (1.10.3)
lazr.restfulclient (0.13.4)
lazr.uri (1.0.3)
lxml (3.5.0)
M2Crypto (0.22.6rc4)
Mako (1.0.4)
MarkupSafe (0.23)
matplotlib (1.5.3)
mercurial (3.2.2)
messagebird (1.2.0)
mock (2.0.0)
ndg-httpsclient (0.4.0)
num2words (0.5.4)
numpy (1.11.2)
oauth (1.0.1)
ofxparse (0.15)
PAM (0.4.2)
pandas (0.19.1)
paramiko (2.0.2)
passlib (1.6.5)
pbr (1.10.0)
Pillow (3.4.1)
pip (9.0.1)
pipreqs (0.4.4)
psutil (4.3.1)
psycogreen (1.0)
psycopg2 (2.5.4)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0)
pydot (1.2.3)
Pygments (2.1.3)
pygobject (3.20.0)
pygpgme (0.3)
pyOpenSSL (0.15.1)
pyparsing (2.1.10)
pyPdf (1.13)
pyserial (3.1.1)
pysftp (0.2.9)
python-apt (1.1.0b1)
Python-Chart (1.39)
python-dateutil (2.5.3)
python-debian (0.1.27)
python-ldap (2.4.27)
python-openid (2.2.5)
python-stdnum (1.3)
pytils (0.3)
pytz (2016.7)
pyusb (1.0.0)
PyYAML (3.12)
qrcode (5.3)
redis (2.10.5)
regex (2016.4.25)
reportlab (3.3.0)
requests (2.11.1)
schema (0.3.1)
SecretStorage (2.1.3)
service-identity (16.0.0)
setuptools (21.0.0)
simplejson (3.5.3)
six (1.10.0)
SOAPpy (0.12.22)
Sphinx (1.2.3)
sphinx-patchqueue (0.4.0)
suds-jurko (0.6)
Twisted (16.0.0)
typing (3.5.2.2)
tzlocal (1.3)
unicodecsv (0.14.1)
unittest2 (0.5.1)
vatnumber (1.2)
vobject (0.9.3)
wadllib (1.3.2)
WebOb (1.6.0)
Werkzeug (0.11.11)
wheel (0.29.0)
wstools (0.4.3)
xlrd (1.0.0)
XlsxWriter (0.9.3)
xlwt (1.1.2)
xmltodict (0.10.2)
yarg (0.1.9)
zope.interface (4.1.3)
`


Thanks.

**Comment by JKE-be** [comment]
An esay way to compare the version, is to ask to python the current version...
```python
odoo@jke:~$ python
>>> import urllib
>>> print urllib.__version__
1.17

```

Do you have a traceback... because I dont see the UserError raised in your previous message (with the exception message).
Anyway, that will be easier if you could print the complete exception with traceback...

Thanks

**Comment by BzMB** [comment]
Hi,

Sorry for the late reply. 

1) version comparison results
thanks for the command 
the version are the same

2) traceback
Odoo keep loading and the end raise the following warning
Odoo Warning - Warning
Cannot contact geolocation servers. Please make sure that your Internet connection is up and running (Extra data: line 1 column 2 - line 70 column 1 (char 1 - 1994)).


Any feedback would be much appreciated.

At the moment we've created a new branch from 10.0 using the urlib2 on the servers affected as a workaround.

Thanks.

**Comment by JKE-be** [comment]
@KangOl an idea about this strange behavior ? 
Ok for you to use urlib2 instead of urlib ? should not have negative impact...

**Comment by KangOl** [comment]
Really weird situation...

If using `urllib2` solves the problem, go for it.

**Comment by Yenthe666** [comment]
Hi @BzJB,

Could you try this again with `urllib2` please? Is the issue then fixed?

**Comment by JKE-be** [comment]
IMHO, it can be merged

**Comment by BzMB** [comment]
Hi @Yenthe666 ,

Not sure what you've asked for, we're currently using urllib2(instead of the urllib) to solve the issue.

@JKE-be: "IMHO, it can be merged!

It means that you are thinking of merging into the core?

Thanks

**Comment by Yenthe666** [comment]
@JKE-be then let us go and merge that in. Can you fix it?

**Comment by BzMB** [comment]
Many Thanks.
