### ISSUE TITLE
[10.0] Account Cash Basis Movements without amount

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#14637]
### Impacted versions:
10.0

### Steps to reproduce:
1.- Configure company journal to Use Cash Basis
2.- Configure the purchase tax Tax 15% to Use Cash Basis on Tax Paid account
3.- Generate a new supplier invoice
4.- Validate the invoice created in step 3
5.- Generate the payment to invoice in step 3

### Current behavior:
The journal entry to tax paid have the correct lines but with amount in debit and credit in 0
![efp 2016 0002 odoo](https://cloud.githubusercontent.com/assets/7606656/20982247/560ee5b6-bc7d-11e6-8b8b-53148bdf8732.png)

### Expected behavior:
The movements in journal entry have the corresponding amount that is indicate on the invoice

### Video/Screenshot link (optional):
https://youtu.be/BZMV2auvUHs

**Comment by moylop260** [comment]
FYI @qdp-odoo

**Comment by qdp-odoo** [comment]
it has been fixed in 9.0 at revision https://github.com/odoo/odoo/commit/0f63b2cce0f024ddfc5a3d3b1a31c91e20c16039
