### ISSUE TITLE
[8.0] Severe regression on product pricelist in multicompany mode

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#14631]
Impacted versions:
8.0

A recent commit introduce a severe regression. 

No company_id are set on product_pricelist_version and product_pricelist_item on creation.

Commit : https://github.com/odoo/odoo/commit/295b96c0b39959d053c3b74edd515879c873c722

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis

**Comment by beledouxdenis** [comment]
and then I am asked why we have such a strict policy regarding bugs in stable releases... I will look into it right now.

**Comment by beledouxdenis** [comment]
I just solved the regression with the revision
36c6edf4bc1aba8a829e91aed40fd21b3c48dc17

I am truly sorry for the inconvenience

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis Thanks for your quick react.

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis have a look at https://github.com/odoo/odoo/commit/456d7b38f1f6c889ab24e391154dbe1d21f34371
I think the same bug is present, wrong dictionary in store attribute.

**Comment by beledouxdenis** [comment]
Are you stalking me ? :D 
I indeed just solved this other similar case in 
82a07d10724d262096a61a1a3318069d17e86115

**Comment by Cedric-Pigeon** [comment]
No I just have a tests suite on my project that crached because of these commits ;-)
