### ISSUE TITLE
404 throughout the application after a night update

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#14639]
Impacted versions:10.0

Steps to reproduce: updated 12/07/2016

Current behavior: throughout the application I get an error 404
http://prntscr.com/dgm00o  
http://prntscr.com/dgm0a6
http://prntscr.com/dgm0iz

Expected behavior:
that the application would work as it should.

Video/Screenshot link (optional):
---------------------------------------
For the second time already this error when updating. 1 time was 1 month ago. I reinstalled from scratch odoo.
Tell me why this happens?

**Comment by JKE-be** [comment]
Your statics files are not loaded.
Are you sure that you don't pull code with another user ? 
check the permission on your files...

Maybe linked to https://github.com/odoo/odoo/issues/4755

**Comment by collex100** [comment]
I have given the maximum access rights:
http://prntscr.com/dhf3xv

but it did not help.
http://prntscr.com/dhf5n1

I had root right before. Everything worked. After the upgrade, all stopped working.
Where can I see how to check?

**Comment by alexanderahlsen** [comment]
Happening to me too after nightly update.

**Comment by collex100** [comment]
@alexanderahlsen I wanted to ask, before the problem occurred is not installed 
https://www.odoo.com/apps/modules/10.0/auto_backup/
There had to install the script pysftp.

It did not correctament established. I have corrected the installation script pysftp and updated odoo, all working again.

**Comment by qupro** [comment]
same issue after Odoo 9 nightly update affecting web_responsive module:

![image](https://cloud.githubusercontent.com/assets/5942916/25910550/fae20a30-35b0-11e7-8afe-455471191e24.png)
