### ISSUE TITLE
SetLang not taken into accout in webkit report on some objects

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#1463]
Here are the steps to reproduce the bug on OpenERP 7.0:
1) install the module "test_bug_translation_webkit" that you can get from lp:~akretion-team/+junk/test-bug-translation-webkit-70
This module only depends on "report_webkit" and "product" modules.
This module adds 3 webkit reports:
- 1 on product.product (with an additionnal translated field "storage_conditions")
- 1 on res.partner (with an additionnal translated field "storage_conditions")
- 1 on res.partner.title (no need for an additionnal translated field ; there are already 2 translated fields on that object)
  Those 3 reports contain setLang('en_US').

2) Install a second language (French for example)

3) On the product 'USB Adapter", give a value to the field storage_conditions and a French translation to this field. You can also give a French translation to the name of the product.

4) On the form view of the "USB Adapter", go to "Print > Report test bug WEBKIT"
- if the user has language "English" in it's preferences, the fields "name" and "storage_conditions" and will be displayed in English in the PDF report
- if the user has language "French" in it's preferences, the fields "name" and "storage_conditions" will be displayed in French in the PDF report, although the report has setLang('en_US') !!! -> that's the bug

5) Do the same on the form view of Partners -> you have the same bug

6) Go to the form view of res.partner.title (menu Sales > Configuration > Address Book > Contact Title) -> the bug is NOT present !

So this bug depends on the object:
- the bug is present with res.partner and product.product
- the bug is NOT present in res.partner.title

I initially found this bug when working on Aeroo reports (cf https://bugs.launchpad.net/aeroo/+bug/1344124), but I then found that it was the same with report_webkit, so this bug seems to be independant from the reporting engine. I tried to reproduce the bug with RML, but I always have an error, I didn't achive to generated the report with RML.

**Comment by diggy128** [comment]
Did you ever find a solution to this?
I've migrated all my reports from pentaho and rml to webkit and just found out translation isn't working as it should!

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
