### ISSUE TITLE
[9.0] POS Order time does not match with time in Order Receipt Printed

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#14635]
### Impacted versions:
9.0

### Steps to reproduce:

1. Open a Pos.Order session, wait a minutes before create a Pos Order
2. Create a Pos Order
3. Print Pos Order Receipt
4. Go to Pos Orders tree view, and compare time between Receipt and Order related

### Current behavior:
Order time is the same on the tab at the top of the POS screen, instead the time when was printed the Receipt. 

### Expected behavior:
Order time should be the same of the Receipt

### Video/Screenshot link (optional):

_Tab at the top of the POS screen_
![captura de pantalla de 2016-12-07 17-31-41](https://cloud.githubusercontent.com/assets/5335402/20978071/7f7715ca-bc75-11e6-8887-ef434809a21c.png)

_Time at Order Receipt (current)_
![5965535124241161498-account_id 1](https://cloud.githubusercontent.com/assets/5335402/20978073/7f8d5a56-bc75-11e6-88f9-67eeca897b2b.jpg)

_Time at Order view  (when POS screen was open)_
![6710199250182305156-account_id 1](https://cloud.githubusercontent.com/assets/5335402/20978072/7f75a604-bc75-11e6-9856-ce0858f107da.png)

### Additional information:

This issue was reported on #11933 and was fixed in e9b1254, but only for version 10.0. In my case i need support for 9.0

**Comment by Icallhimtest** [comment]
Hello Jose,

The commit you're referring to (e9b1254a5c4ea008c13d0636fec87bc0f8d42245) is already in 9.0.

It was committed in May, a few months before 10.0 was even released, you can't trust Github's branch tags, they're rarely accurate.

Are you sure the version you're using is up to date? I've made a quick test and every date looks fine on my end.

**Comment by suniagajose** [comment]
You're rigth! is already in 9.0, i got carried away by the github tag.

The problem was found on a webkul's module, that overrides `validate_order` function.

Sorry by the mistake

Regards
