### ISSUE TITLE
[8.0] Similar Expenses get grouped on Invoice with wrong values but correct total

### ISSUE THREAD

**Issue by tkontogi** [odoo/odoo#14644]
**Impacted versions:**
8

**Steps to reproduce:**
Create an expense sheet.

Two lines

Line one is Air Ticket/Date 01-01-16/300USD

Line two is Air Ticket/Date 01-02-16/600USD

Submit, approve, post journal entries, go to analytic journal entries, select both expenses, create invoice.

Both air tickets, are shown in a single invoice line as "Air Ticket" with the correct total value, total items two and calculated value per item the total value divided by 2.

Two tickets costing 300+600=900USD, will be re-invoiced to the customer as two tickets each at 450USDx2=900USD total.

**Current behavior:**

All same category/product ID expenses, are grouped in the same invoice line.

**Expected behavior:**

Create one line per individual expense with correct amounts.

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment]
Hi @tkontogi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
