### ISSUE TITLE
Weird calculation on hr.holidays and hr.holidays.status

### ISSUE THREAD

**Issue by randyraharjo93** [odoo/odoo#14643]
Impacted versions:
9, Enterprise, 184508-9-0-c5186b

Steps to reproduce:
1. Create new hr.holiday.status
2. Create 8 allocation request for an employee with days value (0.83, 0.83, 0.83, 0.83, 0.83, 0.83, 1, 0.02) total 6.
3. Create 6 leave request for that employee with days value 1. total also 6.

Current behavior:
Can't create the last leave request saying doens't have enough allocation request. When in the many2one holiday type selection it says (1/6)

Expected behavior:
Can create the last leave request

Video/Screenshot link (optional):
![screenshot from 2016-12-08 12 02 01](https://cloud.githubusercontent.com/assets/17263218/20998137/4b2c5644-bd3e-11e6-9bbd-9be31d5bb274.png)
![screenshot from 2016-12-08 12 02 25](https://cloud.githubusercontent.com/assets/17263218/20998139/4d16ec26-bd3e-11e6-98d8-44ff978b33ea.png)
![screenshot from 2016-12-08 12 02 58](https://cloud.githubusercontent.com/assets/17263218/20998141/4f806a46-bd3e-11e6-9ca2-b7a6fd6c54ed.png)

**Comment by Yenthe666** [comment]
@mart-e can you have somebody look at this? Perhaps @nim-odoo?

**Comment by mart-e** [comment]
The patch is easy, it is something like 277f474 but I am wondering @randyraharjo93, these example are clearly made up to provoke a float imprecision.
Is it something that you get on production? I don't see allocation of 0.02 days as realistic.

**Comment by tde-banana-odoo** [comment]
This is not really a use case.

**Comment by mart-e** [comment]
Closing in favor of #14643
