### ISSUE TITLE
Duplicate database: timeout stops filesystem copy

### ISSUE THREAD

**Issue by dannyadair** [odoo/odoo#14641]
Impacted versions: 8.0, possibly later

Steps to reproduce: Duplicate a database with a filestore holding a relatively large amount of files, in our case 40k+

Current behavior: The web interface times out and the copying of the filestore is interrupted.

Expected behavior: Even when the web interface times out, the filestore copy should be finished. Maybe use ir_cron in source database?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @dannyadair ,

Thank you for the bug report.
This is however not really a bug as it depends on the deployment/configuration.
As Odoo 8 is no longer a long term stable version either I'm closing this report.

Regards,
Yenthe
