### ISSUE TITLE
[15.0][16.0][17.0] Inventory adjustment with Excel file increase Counted Quantity, not set Counted Quantity

### ISSUE THREAD

**Issue by ossimantylahti** [odoo/odoo#146595]
Odoo has a strange error when loading inventory adjustments using an Excel file. When setting inventory adjustments Counted Quantity in an Excel file and loading that file to Odoo, the Counted Quantity is not applied correctly. Instead of setting the inventory level to the new amount set in the Excel file, the quantity is increased by this amount, not set.
When setting the inventory levels manually without Excel file, the amount is set correctly to new Counted Quantity level.
When setting the inventory levels with an Excel file, the amount is not set correctly. Instead, it just increases by the number written in the Counted Quantity column.

This procedure cannot be tested on Runbot as there is an error stating that loading Excel files is not supported from the current location.

I've tested this on Odoo 15, 16 and 17. Works the same way in all versions.

Impacted versions:
15.0, 16.0 and 17.0

Steps to reproduce:
1.	Create two storable products, test1 and test2
2.	Set their inventory levels to 100 each
3.	Go to inventory adjustments, export the products to Excel file
4.	In the Excel file to make things simple remove all other columns than Counted Quantity and product name
5.	Set product test1 to have inventory level 250 and product test2 to have inventory level 2.
6.	Load the Excel to Odoo
7.	Apply the changes

Current behavior:
 test1 has inventory level 350 and test2 has inventory level 102.

Expected behavior:
 test1 should have inventory level of 250 and test2 should have 2.

Video/Screenshot link (optional):
 https://youtu.be/Q6EIy0bvBCY

Support ticket number submitted via odoo.com/help (optional):
 #3643611

**Comment by ossimantylahti** [comment]
All right, someone else might stumble upon this, so here is some documentation: this functionality is a known error. But fortunately there is an easy workaround for this: when doing the product export, be sure to export the external_id as well and import using that. This way the inventory adjustment does not only increase amounts, but sets them correctly.

**Comment by lushkah911** [comment]
Hi @ossimantylahti thanks for raising the issue. We noticed the same past months. 

"Stock.quant" model only list products with a quantity in stock, and this explain why we export products for inventory adjustments.

For products with no records in stock.quant model (inventory adjustments), importing an excel file with product model, location and quantity counted works correctly.

**Comment by ossimantylahti** [comment]
To make matters more complex, this feature is reworked in Odoo 17 in a significant manner.

**Comment by wguerram** [comment]
> All right, someone else might stumble upon this, so here is some documentation: this functionality is a known error. But fortunately there is an easy workaround for this: when doing the product export, be sure to export the external_id as well and import using that. This way the inventory adjustment does not only increase amounts, but sets them correctly.

Trying with v18 importing id is not allowed. What field should be mapped to external_id when importing?
