### ISSUE TITLE
[v7.0] Cancelling Physical inventory doesn't cancel related journal entries? Bug or Missing Configuration??

### ISSUE THREAD

**Issue by dvdhinesh** [odoo/odoo#1466]
In Configuration -> Warehouse -> Accounting -> Enabled Generate accounting entries per stock movement .

I created a physical inventory. It creates a new journal entries.

I installed account_cancel module and enabled Allow cancelling entries on journal.

But when I cancel that inventory, the related journal is not cancelled! Am I missing any configuration or is it a bug??

There is already a bug reported for this issue and fix has been released, but it is not been merged.

Bug in mailing List: https://www.mail-archive.com/openerp-india@lists.launchpad.net/msg26453.html

Bug description in Launchpad: https://bugs.launchpad.net/openobject-addons/+bug/1244368

Related Fix: https://code.launchpad.net/~openerp-dev/openobject-addons/trunk-bug-1244368-cod

Code Diff: https://code.launchpad.net/~openerp-dev/openobject-addons/trunk-bug-1244368-cod/+merge/199772/+preview-diff/462164/+files/preview.diff

I changed the code in stock.py related to fix. If we try to cancel the inventory means, it shows error like "In order to cancel this inventory, you 
must first unpost related journal entries."

What I am missing here??

**Comment by Yenthe666** [comment]
Hi @dvdhinesh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
