### ISSUE TITLE
wkhtmltopdf will not display html properly

### ISSUE THREAD

**Issue by fractalf** [odoo/odoo#146601]
I've tried to figure out this for days now...

Odoo 17 just won't generate proper PDFs from HTML. This works fine in Odoo 12 which I'm migrating from..

Running version 17 in a docker container using the deb here:
https://download.odoo.com/17.0/nightly/deb/odoo_17.0.20231127_all.deb

I've tried with wkhtmltopdf versions `0.12.5`, `0.12.6` and `0.13.0`.
I've also tried the Odoo fork found here:  https://github.com/odoo/wkhtmltopdf/releases/

HTML
https://localhost:8001/report/html/sale.report_saleorder/1

![image](https://github.com/odoo/odoo/assets/5707457/18eb6382-acde-45b5-ae76-cb2a242c8a4e)

PDF
https://localhost:8001/report/pdf/sale.report_saleorder/1

![image](https://github.com/odoo/odoo/assets/5707457/df23130f-1aae-44fd-8d1b-4f17a86302b9)

This seems to work on the Odoo runbot servers, so why doesn't it work in the official docker images?

https://55165772-master-all.runbot167.odoo.com/report/pdf/sale.report_saleorder/1

I've noticed this warning in the log which might be related

```
2023-12-18 08:24:17,530 40 WARNING ff odoo.addons.base.models.ir_actions_report: wkhtmltopdf: Exit with code 1 due to network error: ConnectionRefusedError
```

**Comment by jeevan-smartltd** [comment]
sounds similar to [this ](https://stackoverflow.com/questions/60907754/exit-with-code-1-due-to-network-error-connectionrefusederror-when-generating-pd)problem, hope it gives you an idea
wkhtmltopdf is not an active project anymore, the repo is already archived. Odoo cloned this [here](https://github.com/odoo/wkhtmltopdf), posting issues there may help.

**Comment by bennals** [comment]
I just encountered this problem on V17 enterprise running in Docker as well but the solution referenced [here](https://github.com/odoo/docker/issues/238#issuecomment-457216876) fixed the issue straight away.

You basically add a new record in System Parameters with key [report.url] and value [http://0.0.0.0:8069].

**Comment by fractalf** [comment]
@bennals **THANK YOU** from the bottom of my heart :)

This problem has caused me an insane amount of worry and work! It has basically blocked a huge application from being upgraded..

**Comment by bennals** [comment]
You're welcome @fractalf :)

**Comment by peterromao** [comment]
@bennals Here's a second **HUGE THANX** ;-)

I've been going on this for about 3 days now and your input saved me. This was almost like a detective job to understand that it could have something to do with communications.

**Comment by sadmiral98** [comment]
@bennals thanks!
