### ISSUE TITLE
[10.0] Manufacturing Can "produce" products without raw materials available

### ISSUE THREAD

**Issue by Ajroo** [odoo/odoo#14661]
Impacted versions: 10.0

Steps to reproduce: 
- Make BoM with raw materials
- Create Workorders
- Start workorders without checking availability of raw products
- Start your workorder and then push the done button
- All your products will be confirmed as manufactured without the move for the raw products being done

Current behavior:
You can produce products without assigning and moving the necessary raw products to the manufacturing location

Expected behavior:
1) Check when you start your workorder if at least a quantity of your raw materials is available to produce 1 product

2) Check if raw materials are available when confirming the produced products
This shouldn't be possible because you always should have the required raw materials before you can produce a piece 

Video/Screenshot link (optional):

After confirming the first work order which consumes the raw materials, the raw materials are consumed but where not available
![image](https://cloud.githubusercontent.com/assets/9432816/21043211/a0b1376c-bdaa-11e6-9843-26a69c3d6664.png)

The stock moves which show that the raw materials for WorkOrder 1 are still in status Waiting availability 
![image](https://cloud.githubusercontent.com/assets/9432816/21043239/c05e6de6-bdaa-11e6-8042-0357d14fe4c8.png)

Overview of the workorders which show that workorder 1 is finished (= consumed the raw materials)
![image](https://cloud.githubusercontent.com/assets/9432816/21043269/e3ab87fc-bdaa-11e6-96f7-e4ddbb2d78c4.png)

**Comment by jco-odoo** [comment]
The idea with v10 was to make it possible to start a production without all the materials being available.  So, it was done like that on purpose.
