### ISSUE TITLE
Upload translations for Odoo Enterprise

### ISSUE THREAD

**Issue by leemannd** [odoo/odoo#14668]
Impacted versions: Odoo Enterprise 10 and 9

@qdp-odoo 
Hello, I want to upload German translations to l10n_ch_reports that are in Odoo Enterprise ' l10n_ch_reports/account_financial_report.xml '. I cannot see the module in transifex. Should I do direcly a PR to the repo, so that you can upload the translations?

**Comment by leemannd** [comment]
Note: This is related to https://github.com/odoo/enterprise/pull/590

**Comment by mart-e** [comment]
Hello,

That would be me for the translation related questions :)
The l10n modules are not published on Transifex as we do not want to get Chinese translators to translate the Spanish chart of account.
The Swiss is a specif cases as it is multilingual so it makes sense to translate in a different language.
You can create a pull request on enterprise to translate the l10n_ch_report module and I will merge it. The translations must be in a i18n_extra folder (as it is the case for the l10n_ch translations)
[How to translate my chart of account into multiple languages?](https://github.com/odoo/odoo/wiki/Translations#how-to-translate-my-chart-of-account-into-multiple-languages)
