### ISSUE TITLE
Due Payment Report

### ISSUE THREAD

**Issue by irfan-isi** [odoo/odoo#14663]
Impacted versions: Version 10.0 

Steps to reproduce: Go to Partner form and Print Report Due Payment

Current behavior: Error

Expected behavior: Download due payment report

Video/Screenshot link (optional):
![due payment](https://cloud.githubusercontent.com/assets/22587784/21047749/ab1ea50e-be31-11e6-81de-894a8b24c144.png)

**Comment by Yenthe666** [comment]
Hi @irfan-isi,

Thanks a lot for your report!
I've just tested this on the latest Odoo 10 and can confirm that this is a bug.
@mart-e can you look at this one? It is in the SQL query.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Thank you for the report. It was fixed at a9b0af7
