### ISSUE TITLE
Due Payment Report Issue

### ISSUE THREAD

**Issue by iju-odoo** [odoo/odoo#14664]
Impacted versions:10.0

Steps to reproduce:Go To partner and Download Due payment report

Current behavior:Error !

Expected behavior:Download PDF for Due payment
![due payment](https://cloud.githubusercontent.com/assets/11677925/21047827/17ad0580-be32-11e6-9f4b-fc3ec2524691.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @iju-odoo,

You where slightly slower as somebody else. 
I'll close this one in favour of https://github.com/odoo/odoo/issues/14663 (the bug is confirmed).

Regards,
Yenthe
