### ISSUE TITLE
[17.0][POS] Reprint Receipt Duplicated when Reprinted

### ISSUE THREAD

**Issue by Senpaixyz** [odoo/odoo#146612]
**Impacted versions: Odoo 17**

**Steps to reproduce:**
POS ->  Orders -> Paid -> (select one) -> Print Receipt -> Print receipt
**Current behavior:**
When the button trigger was reprinted, the receipts were duplicated. that causing overlaps 
**Expected behavior:**
Only 1 receipt copy should be printed
**Video/Screenshot link (optional):**
_Step 1_
<img width="233" alt="button-reprint" src="https://github.com/odoo/odoo/assets/64669453/52f81349-85e6-42ab-856c-763355e46020">
_Step 2_
<img width="115" alt="2-printed-receipts" src="https://github.com/odoo/odoo/assets/64669453/0846e78d-09dd-49f2-bd59-7f8f7ad4f08a">

**Comment by MohdAlmosawy** [comment]
Hi @Senpaixyz,

I couldn't replicate the duplicate receipt issue in a standard Odoo 17 POS setup, which suggests it might be related to specific configurations or modules in your environment.

Could you provide details on any such configuration, customizations, or localizations? This information will help pinpoint the cause.

Thanks!

**Comment by Senpaixyz** [comment]
It was fixed already, thanks
