### ISSUE TITLE
Units of measure not localized in reports

### ISSUE THREAD

**Issue by waltersteinlein** [odoo/odoo#14674]
Impacted versions:
10.0

Steps to reproduce:
1. Activate 'Some products may be sold/purchased in different units of measure (advanced)' in Inventory / Configuration / Settings
2. Create Invoice with products that have hour(s) as UoM (I used 'GAP Analysis Service' from the demo data here)
3. Print invoice to html though Accounting / Sales / Customer Invoices / ... / Print
4. Change language (e.g. to Spanish), logout, login
5. Recreate invoice

Current behavior:
Invoice shows 'x Hour(s)' no matter what language the user has selected. The localization in account.invoice.form is properly localized though.

Expected behavior:
Unit of measure is properly localized in account.report_invoice_document

**Comment by pedrobaeza** [comment]
That's because the name of the unit of measure are translatable, and you don't have that translations loaded. Please check properly in latest runbot version and you will find that there's no actual issue.

Closing this.
