### ISSUE TITLE
Page keep loading after install a custom module

### ISSUE THREAD

**Issue by basebasket** [odoo/odoo#14678]
Impacted versions: 10.0 (Enterprise Edition )

Steps to reproduce:
1.Upload custom module into addons folder
2.Update module list then install custom module

Current behavior:Page keep loading very long time without timeout or error in log file(last line in log file is `.... INFO my-db-username openerp.addons.base.ir.ir_http: Generating routing map`)

Expected behavior:

Video/Screenshot link (optional):

![screenshot from 2016-12-12 09 58 16](https://cloud.githubusercontent.com/assets/12761212/21086731/b92e154a-c051-11e6-8f7b-46639dde345d.png)

log file 
![screenshot from 2016-12-12 09 57 18](https://cloud.githubusercontent.com/assets/12761212/21086732/b9368496-c051-11e6-8940-d3dfa3e74727.png)

ps aux | grep odoo
![screenshot from 2016-12-12 10 25 03](https://cloud.githubusercontent.com/assets/12761212/21087109/7479407e-c055-11e6-9e54-455ecc7bfb18.png)

**Comment by basebasket** [comment]
I resolved it by killing odoo process by command line and start odoo-server, but this error always appear when I install new module

**Comment by Yenthe666** [comment]
Hi @basebasket,

Thank you for your report.
This looks like a server / deployment issue though. Perhaps your server doesn't have enough RAM/CPU in order to quickly perform these actions?
You could try updating your Odoo code source and updating your database with the `-u all` parameter.

Regards,
Yenthe

**Comment by Mahmoud-Alaa-Eldeen** [comment]
This worked for me.
sudo service odoo stop
sudo service postgresql restart
sudo service odoo start
