### ISSUE TITLE
[v9.0] Payments are not not being reconciled with invoices after POS closing

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#14671]
**Impacted versions:**
8.0, 9.0

**Steps to reproduce:**
1. Create a Pos Order
2. Pay the Order
3. Close the POS
4. Validate Closing & Post Entries

**Current behavior:**
All the payments made are not reconciled with their respective invoices generated by the POS.

**Expected behavior:**
The whole reason of the POS is a simpler way of selling and invoicing, but if payments have to be manually reconciled, this causes additional uneeded complexity. If this is an "expected" behaviour for some, it should, at least, have an Option in the POS to make automatic reconciliation of the payments.

**Comment by Yenthe666** [comment]
@jorenvo could you give feedback on this one?

**Comment by jorenvo** [comment]
I agree with your feedback, but it is currently not a feature of the POS. A stopgap measure was implemented in 9.0 (f40e9ecfc30ba93a2b931a485565660f819436ad) to allow for easier reconciliation. Automatically reconcilation is a feature we will consider for future versions of Odoo. Thank you for your report.

**Comment by jorenvo** [comment]
Done in master at a2319b431b3d4f12a932ac8cda1ce62ecd6b6d2f.

**Comment by gustavovalverde** [comment]
Great work @jorenvo 👍

**Comment by gustavovalverde** [comment]
Just to understand a bit, I've overwritten this in 10.0 and I can't see it actually does something, should I do something extra to make this work correctly?

As far as I understand, this should automatically reconcile payments with invoices when closing and validating the POS
