### ISSUE TITLE
[9.0] Can't close pos if round globally and pricision 0 is activated

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#14672]
Impacted versions:
9.0

Steps to reproduce:
1.- configure currency and decimal precision to 0.
2.- configure globally tax calculation
3.- Set tax to 19% included
4.- open  a POS session.
5.- Make some movements.
6.- then close the pos.
Current behavior:
can't close session because :

debugin the problem, is because when odoo create account move, group taxes globally, but take per line tax calculation.

ie:
order 1:
1 line product  $1
order total $1, tax $0
order 2
1 line product $2
order total $2 tax $0
on odoo close way:
product total $3
tax $1
then debit and credit mismatch $3 and $4

Expected behavior:

per order round and then globally sum all taxes

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jorenvo one for you.
