### ISSUE TITLE
[8.0] Field Many2many with tree defined is not populated in wizard

### ISSUE THREAD

**Issue by chiticariu** [odoo/odoo#14677]
Impacted versions: 8.0

Steps to reproduce:
- create a module with a wizard
- add in wizard 2 fields: a selector (is an example), and the many2many field which is a computed field based on option selected in selector
- install it on a clean database, execute wizard, select a option in selector field

Current behavior:
- records set in compute method not visible on UI

Expected behavior:
- records set in compute method should be visible on UI

Video/Screenshot link (optional):
- example module attached
[bug_wizard_many2many_tree.zip](https://github.com/odoo/odoo/files/644796/bug_wizard_many2many_tree.zip)
- demo video attached
[demo.zip](https://github.com/odoo/odoo/files/644798/demo.zip)

**Comment by Yenthe666** [comment]
Hi @chiticariu,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
