### ISSUE TITLE
[9.0] Wrong subtotal on POS with round globally tax , and decimal precision 0 

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#14673]
Impacted versions:
9.0
Steps to reproduce:
1.- set all precision to 0.
2.- set round globally round tax calculation.
3.- Set tax to 19% included
4.- make that order:
line1 qty 90 x 300
line 2 qty 13 x 840

Current behavior:
line1 subtotal 27000
line2 subtotal 10920
total  37919
Expected behavior:
total 37920

I temporally fix the bug  replacing get_total_with_tax with :

get_total_with_tax: function() {
      _super_order.get_total_with_tax.apply(this,arguments);
      return round_pr(this.orderlines.reduce((function(sum, orderLine) {
          return sum + orderLine.get_price_with_tax();
      }), 0), this.pos.currency.rounding);
    },

**Comment by Yenthe666** [comment]
@jorenvo another one. 😉
