### ISSUE TITLE
Unlink analytic line on tasks does not force qty delivered to be recomputed.

### ISSUE THREAD

**Issue by open-net-sarl** [odoo/odoo#14685]
Impacted versions: 9.0

Steps to reproduce:
Create a sale order with a "service" product.
This creates a task.
Try adding a line. 
This increase the delivered quantity into the sale order.
Then remove this line.
And then the delivered quantity remains the same. 
odoo/addons/sale/models/sale_analytic.py
In this file i think you omitted to implement the method _compute_analytic for the unlink case.

**Comment by pedrobaeza** [comment]
Is this still happening in latest code version?

**Comment by Yenthe666** [comment]
Hi @open-net-sarl,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
