### ISSUE TITLE
[V10] Edit Consumed Materials in Manufacturing Order

### ISSUE THREAD

**Issue by rlaurinavicius** [odoo/odoo#14689]
Impacted versions:
V10 Community, V10 Enterprise
Steps to reproduce:

1. Go to Manufacturing>Operations>Manufacturing Orders
2. Create a Manufacturing Order for a Product e.g. Computer Desk and Click Save
3. Click Edit

Current behavior:
Consumed Materials are filled in according to Product's Bill of Material.
The system doesn't let you Edit the Consumed Materials, neither add or delete lines.

Expected behavior:
Once you click Edit, it should be possible to add more lines to Consumed Materials or Delete Existing Ones.

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/21221578/21097529/93d31edc-c06d-11e6-9d62-7be662e27061.png)

**Comment by jco-odoo** [comment]
For v10, it is not possible.  Next version probably.

**Comment by jco-odoo** [comment]
Of course there is no problem if you would create extra moves by removing the create="0", but the views are not setting the right values automatically, ... yet, which you could also adapt in the view normally (default_location to location_src_id, ...) .  (you could also play with unit_factor which replaces the scheduled products, ...)

**Comment by gediminasvenc** [comment]
Hi jco-odoo, thanks for your comment. We did remove the create="0" and added the stock locations as you have mentioned, which allowed us to add new moves. However we are not able to make the system consider the newly added moves when you click "Check Availability" and also we didn't quite understand what you said about the unit_factor, can you elaborate on this?

**Comment by Billolha** [comment]
Hi @jco-odoo,

Any news about bringing back the functionnality in the V11?
Many (entreprise) clients are stuck with the v9 because of this regression.

Thank you.

**Comment by Jerther** [comment]
Looks like it did not make it to 11.0. Same as 10.0: no add, no delete, no nothing :(

![image](https://user-images.githubusercontent.com/5856745/31284312-2dfc1b50-aa86-11e7-93d6-ab0ef2f2ce69.png)

**Comment by jco-odoo** [comment]
You can do it when you unlock.  (by default without reserving as the To Consume is 0)

**Comment by Jerther** [comment]
Yes! FInally :') Thank you!!!

And to remove, I guess we just set the quantity to 0?

![image](https://user-images.githubusercontent.com/5856745/31297022-6fbdd124-aab2-11e7-9b7f-f0bdc3144588.png)

**Comment by Troublicious** [comment]
Can someone explain how to automatically add the stock locations ?
(I removed the create="0" so i now can add more lines, but i cannot save because of the above :/ )
