### ISSUE TITLE
Wrong translation on odoo neutralized ribbon

### ISSUE THREAD

**Issue by CesarSant2000** [odoo/odoo#146820]
Impacted versions: 16

Steps to reproduce: Neutralized any backup that has the language set to spanish

Current behavior: the translation right now is Neutralisado

Expected behavior: Neutralizado

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/55715914/44840842-f950-42fe-acce-3c7876918515)

Support ticket number submitted via odoo.com/help (optional):

**Comment by ossimantylahti** [comment]
@CesarSant2000 Translation errors are not handled as Github issue tickets. You would be a lot faster by going to Transiflex and do the fix there.
https://app.transifex.com/odoo/odoo-16/languages/

Additionally, Odoo has several Spanish languages. You'd need to select the right variant.
