### ISSUE TITLE
[10.0] Ecommerce product can not swiped down in image area

### ISSUE THREAD

**Issue by BetaUliansyah** [odoo/odoo#14681]
Impacted versions: 10

Steps to reproduce: open ecommerce in mobile browser

Current behavior: the page can not swiped down in image area, you have to use non-image area to swipe down

Expected behavior: swipe can be use in all area of the page

**Comment by JKE-be** [comment]
Hello,

Should be fixed by https://github.com/odoo/odoo/commit/4edbd158455f7249bf9c36207148047c11ad270a

If not, don't hesitate to open a new ticket or ping on this one.
