### ISSUE TITLE
many2many create method error: unhashable type: 'list' Odoo 17.0

### ISSUE THREAD

**Issue by maliraza-techloyce** [odoo/odoo#146955]
Hi. I'm trying to import slack channels into odoo but the above mentioned error arises. I am trying to populate a many2many field. I tried to pass tuple into it but got no luck. If anyone has any suggestions,do reply. While debugging, I realized that the error occurs when the ORM methods like write or create gets triggered.
Following is my line of code which I believe is the reason behind this error:

`'channel_partner_ids': [(6, 0, tuple(total_partner_ids))]`

**Comment by maliraza-techloyce** [comment]
`odoo_channel = self.env['discuss.channel'].search([('name', '=', channel['name'])])
                    c_data = {
                        'sl_slack_channel_id': channel.get('id'),
                        'name': channel.get('name'),
                        'id': self.env.user.id,
                        'is_member': True,
                        'is_chat': False,
                        # 'message_ids': [[6, 0, messages_ids]],
                        # 'channel_partner_ids': [(6, 0, tuple(partner_id)) for partner_id in tuple(total_partner_ids)]
                        'channel_partner_ids': [(6, 0, tuple(total_partner_ids))]
                        # 'channel_partner_ids': [(6, 0, tuple(total_partner_ids))]
                        # 'channel_partner_ids':total_partner_ids
                    }
                    if not odoo_channel:
                        self.env['discuss.channel'].create(c_data)
                        self.env.cr.commit()
                    else:
                        odoo_channel.write(c_data)
                        self.env.cr.commit()`

**Comment by SamekaTV** [comment]
Are you sure the structure of the tuple you're passing is correct?

**Comment by maliraza-techloyce** [comment]
@SamekaTV  I have tried your suggestion but got the following Validation error: unhashable type: 'list'

**Comment by vava-odoo** [comment]
Hi @maliraza-techloyce 
I think what you need is to change it to `'channel_partner_ids': [(6, 0, total_partner_ids.ids)]`. There are many examples in the codebase.
Please keep the github issues for real issues, and ask for help on the forum.
Cheers
