### ISSUE TITLE
 500 Internal Server Error

### ISSUE THREAD

**Issue by rajeshbk042** [odoo/odoo#14695]
Impacted versions:Odoo 10

Steps to reproduce:Run the odoo 10 source package on windows , Please run odoo in cmd and enter http://localhost:8069 on browser. cmd doesn't accessing while I browse http://localhost:8069, its in same stage not updating with no lines of execution.

Current behavior:No connection between browser and cmd while running

Expected behavior: Should show the odoo page on browser and update cmd running states.

Video/Screenshot link (optional):

**Comment by edsersolis** [comment]
Have you made sure the service is running?

**Comment by WhitleyStriber** [comment]
Have you ensured your Windows Firewall isn't blocking anything through localhost?

**Comment by daramousk** [comment]
Check your server logs. The issue is probably reported over there. This error is reported as `CRITICAL` in odoo logs.

**Comment by Yenthe666** [comment]
Closing as there was never any feedback.
