### ISSUE TITLE
save button still displayed in wizard form field readonly

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#14697]
Impacted versions:10

I have a wizard which have one2many field and set readonly but when i click item in that field, the new wizard (detail wizard) appear but still displaying "Save & New" "Save & Close" and "Discard".
How to hidden the button?

![ss1](https://cloud.githubusercontent.com/assets/7473166/21134827/28c0f840-c152-11e6-96db-4fb863ce7302.jpg)
![ss2](https://cloud.githubusercontent.com/assets/7473166/21134832/2da8b190-c152-11e6-8570-2ee88d9efe02.jpg)

**Comment by pedrobaeza** [comment]
That's not possible, as if a form is opened in edit mode, all popup windows will inherit that mode. Any way, for you is harmless as there's no possible fields to change.

Closing as no real issue.
