### ISSUE TITLE
[trunk] Gender and birthdate missing on contact form

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#147]
Hello, 

Birthdate and gender fields are commonly use information on partner/contact management.

It would be great to add those fields by default on contact form

Regards

Nicolas

**Comment by jholze** [comment]
:+1:

**Comment by jholze** [comment]
https://apps.openerp.com/apps/modules/5.0/base_partner_gender/ found. Does someone know why it wasn't updated ?

**Comment by jholze** [comment]
We are working on it next week. Will be released as an OCA addon.
