### ISSUE TITLE
Attendances: Kiosk Mode (500: Internal Server Error) 

### ISSUE THREAD

**Issue by Fahad-2001** [odoo/odoo#147049]
Impacted versions: 17

Steps to reproduce: Go to -> Attendance (app), click on "Kiosk Mode" menu.

Current behavior: When we try to open Kiosk Mode, it gives us (500: Internal Server Error) due to multi-companies, 

Expected behavior: It should redirect us to the "Kiosk Mode" of the respective company.

Video/Screenshot link (optional): 
![image](https://github.com/odoo/odoo/assets/83023749/d9aa6e2d-a97a-4eb5-b818-7826e022f5d3)

Support ticket number submitted via odoo.com/help (optional):

**Comment by vava-odoo** [comment]
Hi @Fahad-2001 
Thanks for reporting. This was fixed by https://github.com/odoo/odoo/pull/145382
Cheers
