### ISSUE TITLE
Advanced Search: Incorrect Sorting of Fields

### ISSUE THREAD

**Issue by mnehls** [odoo/odoo#14700]
Tested for 8.0
The Sorting of Fields in the Advanced Search is different than expected

Steps to reproduce:

Add 3 fields to product.product. String for Field 1 starts with a Uppercase letter (O). Field 2 starts with a lowercase Letter (o). Fields 3 begin with a Umlaut (Ö). Open the Advanced Search View and check the Order.

Current behavior:
...
Net Weight
O_field
Optional Product
...
o_field
Ö_field

Expected behavior:
...
Net Weight
O_field
o_field
Ö_field
...

Is there any Solution to sort the fields according to the localization?

**Comment by Yenthe666** [comment]
Hi @mnehls,

Thanks for the report. By default in V8 it will order in English and as you describe.
If you'd still want this changed you will need to do custom development (and you can ask help on the official help forums at help.odoo.com).

Regards,
Yenthe
