### ISSUE TITLE
Wrong Result show in BI report (when self created filter save) in odoo 10c

### ISSUE THREAD

**Issue by odoogit** [odoo/odoo#14712]
Impacted versions:
odoo 10c
Steps to reproduce:
go to point of sale then open report for and then orders try to save my self created filter base report (from plus and minus sing) its giving alway wrong result of my filter when ever i refresh or come back it's giving wrong result..can't save my filter
Current behavior:
wrong result 

Expected behavior:
corrent result as per odoo v 8

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @odoogit,

Thanks a lot for your report.
Can you please add more steps on how to reproduce this or add some screenshots? We need more info.

**Comment by pedrobaeza** [comment]
No answer, so closing this.
