### ISSUE TITLE
[10.0] RedirectWarning in onchange do not correctly catched by crash_manager in client

### ISSUE THREAD

**Issue by suvit** [odoo/odoo#14722]
Impacted versions: 10.0

Steps to reproduce:

RedirectWarning in onchange do not correctly catched by crash_manager in client
see https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/framework/crash_manager.js#L178
need to change to ``odoo.exceptions.RedirectWarning``

Current behavior: Simple Warning Dialog is open

Expected behavior: Needed RedirectWarning dialog

Some more features
1. RedirectWarning need accept action dict, not only action_id (for example for action with res_id to fixed object form)
2. When clicked to 'Accept' button, Warning "The record has been modified, your changes will be discarded. Are you sure you want to leave this page ?" is showed, but this is not the expected behavior.
3. Abbility to change 'Cancel' button name, for example to 'No'

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Comment by suvit** [comment]
No, error was not in my code. But already fixed in https://github.com/odoo/odoo/commit/c0ec09e9d56485f3c6a24593bbc0240f54e433c3#diff-838a52ff8928e181c867a6e09156495cL208

And features in end of issue description was not realised. So skip it
