### ISSUE TITLE
odoo.com - missing images for payments, 500 error after purchasing via Ogone

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#14729]
I just attempted a purchase through the Apps Store today.

**First**, no images for the payment options:

![](http://i.imgur.com/7WJam61.png)

URL's for these images:
https://www.odoo.com/web/image/payment.acquirer/8/image_small?unique=22c462e
https://www.odoo.com/web/image/payment.acquirer/2/image_small?unique=5cba628

**Second**, 500 Error after completing Ogone and being redirected back to www.odoo.com:

URL https://www.odoo.com/payment/ogone/test/accept?orderID=SO2016%2F146747-2&currency=USD&amount=10%2E54&ACCEPTANCE=02245J&STATUS=9&CARDNO={redacted}&ALIAS=ODOO-NEW-ALIAS-1481747828%2E26&ED=1019&TRXDATE=12%2F14%2F16&PAYID={redacted}&NCERROR=0&BRAND=MasterCard&ECI=6&IP=71%2E80%2E187%2E222&return_url=%2Fshop%2Fpayment%2Fvalidate&SHASIGN=2B9B81A4827DE73291DEA34FFB438298647A454B

Message:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

After clicking F5, I see this:

![](http://i.imgur.com/PvqPIcP.png)

I also got a confirmation email - so ultimately successful, but problematic in the process.

**Comment by Yenthe666** [comment]
@JKE-be and @mart-e Odoo S.A related.

**Comment by mart-e** [comment]
We will look at it thanks but github is not the place to report issues on odoo.com (for bugs on the odoo software), the support should be contacted for such reports.
