### ISSUE TITLE
[10.0] VAT/TIN term in different places

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#14726]
I suggest to keep consistency everywhere using VAT or TIN term.

For example in the [sale report you're using VAT](https://github.com/odoo/odoo/blob/10.0/addons/sale/report/sale_report_templates.xml#L14), but In the [invoice report TIN](https://github.com/odoo/odoo/blob/10.0/addons/account/views/report_invoice.xml#L12).

**Comment by JKE-be** [comment]
@bst-odoo

**Comment by JKE-be** [comment]
Thanks for your suggestion...
