### ISSUE TITLE
[10.0] PayPal payment acquirer in eCommerce does not show order confirmation, leaves items in cart after payment

### ISSUE THREAD

**Issue by saulih** [odoo/odoo#14727]
Impacted versions: 10.0

Steps to reproduce: enable and configure PayPal payment acquirer, make a purchase thru eCommerce website using production PayPal

Current behavior: payment works as expected, sales order goes into paid state but user is returned to website front page rather than shown an order confirmation and ordered items remain in cart (until user tries to check out again, so double ordering is not possible)

Expected behavior: after completing payment user should be shown an order confirmation and cart should be empty

Tested with 20161213 nightly build

PayPal settings are as in docs:
 - encoding set to UTF-8
 - IPN url set to https://www.mydomain.com/payment/paypal/ipn
 - website return enabled, url set to https://www.mydomain.com/shop/confirmation

Odoo 10 payment acquirer settings: 
 - "Authorize & capture the amount, confirm the SO and auto-validate the invoice on acquirer confirmation"  
 - IPN is enabled

**Comment by lew-tolstoi** [comment]
can confirm this on Odoo 10.0-20170116 (Community Edition)
Please fix this ASAP

**Comment by Yenthe666** [comment]
@JKE-be could you have a look at this? I'm not sure if this is one for you though!

**Comment by Peluko** [comment]
I've solved this by editing ```addons/payment_paypal/controllers/main.py``` and setting ```_return_url``` on ```PaypalController``` to ```'/shop/payment/validate'```. For me it's working now.  The problem was that the return url submitted to Paypal was incorrect. I think that this is the correct behaviour. If someone confirms this I coul do a PR.

Also, by checking the payment validation code, I've seen that it's insecure, it doesn't meet the Paypal guidelines for payment verification, so Odoo is exposed to a series of fraudulent payments.  That's serious. The good part is that it's not hard to implement, I will try on the next days.

**Comment by reinka** [comment]
Has anybody looked into @Peluko's solution in the meanwhile?

**Comment by jholze** [comment]
@Yenthe666 can we push this ? because its a major issue to use paypal in odoo

**Comment by jholze** [comment]
By the way, i got also the problem that the redirect from the paypal sandbox generated a link like payment/paypal/dpn/?amt=192.46&cc=EUR&cm=%7B"return_url"%3A%20"%2Fshop%2Fpayment%2Fvalidate"%7D&item_name=YourCompany%3A%20SO054&item_number=SO054&st=Completed&tx=8WG94320WR9430808 which ends in an 500 Server error. But maybe its only a runbot issue

**Comment by jholze** [comment]
Another issue beside that the product stays in the cart that the order / quotation is not displayed in my account section after the orders was created.

**Comment by jholze** [comment]
Found the issue with the wrong url, it was because the Payment Data Transfer should be was activated. Now no 500 server error are triggered. Paypal redirects to the website homepage which is also bad, because it should be the shop/confirmation.

**Comment by Yenthe666** [comment]
@jke-be another friendly ping. Multiple things seem to bubble up here.

**Comment by jholze** [comment]
Hi @Yenthe666, we also checked this in odoo saas and the redirection doesn't not work as well.

**Comment by JKE-be** [comment]
Hi, 

2 days that I'm trying to reproduce with Paypal Sandbox, but is don't seems to work from their side...
Error 500 and co from their Hermes UI.

The solution will be to use the PDT key provided by Paypal.
Their change their API and now you need to send the request with this key to check the payment.

Because Odoo 10 model is non-updatable, the only way to add this key is to use the ir config parameter (with a group like admin setting to secure it !!!).
So if you copy your PDT key in a key 'payment_paypal.pdt_token' icp, and activate PDT it should works ! 

Change the _return_url from paypal controller directly is tha wrong fix  ! You need to validate it with the call to dpn route.

Here the related commit which add the icp feature for PDT: 205b5542ca274c2c7dc501b4f30e82e53b45a7bf

**Comment by yostashiro** [comment]
I get `ValueError: No JSON object could be decoded` at https://github.com/odoo/odoo/blob/205b5542ca274c2c7dc501b4f30e82e53b45a7bf/addons/payment_paypal/controllers/main.py#L27

There is a preceding plus sign (`+`) in front of the "return_url" value in post['cm'] and it seems to be causing the error.

**Comment by JKE-be** [comment]
Could you paste your full url here... to see the exact format...

Thanks

**Comment by yostashiro** [comment]
@JKE-be Please see below image:
![image](https://cloud.githubusercontent.com/assets/7766939/24752163/43d31634-1aff-11e7-91ab-1c7a5a3b3ef0.png)

**Comment by saulih** [comment]
Created the config parameter as described by @JKE-be and tested paypal payment, seems to work after one minor change to payment_paypal/controllers/main.py:
changed the line @yostashiro highlighted in his screenshot to 

custom = json.loads(**urllib.unquote_plus**(post.pop('custom', False) or post.pop('cm', False) or '{}'**)**)

**Comment by jl2035** [comment]
Why is this issue closed? Was there a PR? Should I update my code? I don't understand... can somebody explain to me what's the solution to this painful problem?

**Comment by Yenthe666** [comment]
@jl2035 JKE closed this with the following fix: https://github.com/odoo/odoo/commit/8544b5ce822455a1e1a15bc4f588f0314b8a41f4

**Comment by jl2035** [comment]
@Yanthe666 so if people changed this one line it worked for them?

I think my problem is mostly that **post parameters are empty dict, so dpn fails and doesn't empty the cart doesn't redirect to /shop/confirmation. Sadly [8544b5c](https://github.com/odoo/odoo/commit/8544b5ce822455a1e1a15bc4f588f0314b8a41f4) does not fix the problem for me :(

**Comment by jl2035** [comment]
@lukebranch @lolziac @Yenthe666 

I'm not detecting any changes. Using the latest git pull I still get redirected to /shop instead of /shop/confirmation and cart is not cleared. I checked the the main.py file and the fix is applied:

    custom = json.loads(urllib.unquote_plus(post.pop('custom', False) or post.pop('cm', False) or '{}'))

One more thing.. is it possible that I'm pulling the wrong branch? I did:

    git pull origin 10.0

This is a reply to a comment here: https://github.com/odoo/odoo/issues/11638

**Comment by Yenthe666** [comment]
@JKE-be could you double check perhaps?

**Comment by JKE-be** [comment]
### Check your paypal configuration: 
https://www.odoo.com/documentation/user/10.0/ecommerce/shopper_experience/paypal.html

We use it in production on several databases withtout any customizations and it works as expected...

### Frequently issues: 
    - Payment Data Transfer (PDT) not activated
    - PDT token not set in Odoo (ir config parameter)
    - Custom domain where the return url is not the same browser that origin url (web.Sase.url is used a return url)

### Check that the redirect from paypal is correct:
Check into the network console that the return url is correct when you come back from paypal: in the network, you should have a hit on /shop/payment/validate, and it is this request that redirect to:
     /shop (if no transaction or bad amount or ...) 
     /shop/confirmation (if tx is not in draft, and so payment has been validated by paypal (via PDT or return params)

**Comment by jl2035** [comment]
@JKE-be thanks! PDT was not activated, so I just moved one step further!

Now dpn and ipn were successful. The user gets back to /shop/confirmation and the order is finalized in Odoo backend. The only remaining problem is that the cart doesn't get cleared. Do you have any idea on that?

**Comment by JKE-be** [comment]
It strange, because you pass in before to be redirected to /shop/confirmation :/

```
        request.website.sale_reset()
        if tx and tx.state == 'draft':
            return request.redirect('/shop')

        return request.redirect('/shop/confirmation')
```

```
    def sale_reset(self):
        request.session.update({
            'sale_order_id': False,
            'sale_transaction_id': False,
            'website_sale_current_pl': False,
        })
```

Have you checked your logs for a traceback in sale_reset ?

**Comment by jl2035** [comment]
I don't get any traceback errors. Let me test a couple more times and I'll report back what exactly happens..

**Comment by jl2035** [comment]
Strange for sure. After a few attempts it started working fine. Might be a session problem, or Firefox private window not working as expected.. Thanks @JKE-be

**Comment by BzMB** [comment]
Hi there, 
Thanks for all you work on this crucial part.

I can confirm that using the latest updated doc:
https://www.odoo.com/documentation/user/10.0/ecommerce/shopper_experience/paypal.html
and testing a transaction using a paypal business production account **all works as expected**.

We are struggling instead when we want to try against a sandbox account, is there any way to test successfully a paypal transaction using a sandbox account (back in time there was).

Is there any missing steps or additional steps that we are not taking into consideration?

Many Thanks.

**Comment by xiumingxiuming** [comment]
@BzMB did you already find the way to test PayPal using sandbox account? Is everything working, e.g. go to confirmation page instead of Home after payment.  

Thanks!

**Comment by BzMB** [comment]
@xiumingxiuming 
The production setup is working. On the Sandbox side is still tricky but maybe is on the PayPal side.
We didn't have a chance to perform any new tests so far.
