### ISSUE TITLE
[8.0] property field not working properly with field that uses `related` option

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#14732]
Impacted versions:
8.0

Steps to reproduce:

for example:

```python

from openerp import fields, models

class SomeModel(models.Model):
    _name = 'some.model'
    
    some_type = fields.Selection([('a', 'A',), ('b', 'B')], string='Some Type', company_dependent=True)

class SaleOrder(models.Model):
    _inherit = 'sale.order'

    some_model_id = fields.Many2one('some.model', 'Some Model')
    related_model_type = fields.Selection(related="some_model_id.some_type")

```

Now admin (and specifically 'admin' user) need to set for example value `b` on field `some_type` on record for `some.model`, using let say company `B`. Another user with company `A`, opens same record and selects value for `some_type` to be `A`. Now he needs to open any draft sale order or create new one and select same `some.model` record that was modified by `admin` using company `B` (and modified by him using company `A`).

Current behavior:

When another user (let say Demo User), selects same record admin modified on sale order (field on sale order will be `some_model_id`), he will see that `related_model_type` has value `B`.

Additionally if related field would also use option `store=True`, then some other weird things will start happening: if non admin user tries to change `some_model_id` field, then it looks that write method is called to all sale orders that has same `some_model_id` value (record) set and if there is sale order in different company, than that user will get access error for writing (even though he was modifying sale order for company he was representing).

It looks that in this case related field is somehow connected to `admin` user company, because if admin would switch to company `A`, then Demo user would see same related field value for company `A` (if he would switch back to company `B`, then same related value on all sale orders would be showed what is set on company `B` even though Demo user uses company `A`).

Expected behavior:
It should see value `A`, because company dependent field should show value that was selected using company user is representing.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
