### ISSUE TITLE
[8.0] Bad currency conversion for taxes on invoices (3)

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#14734]
Impacted versions:

8.0

Steps to reproduce:

See https://youtu.be/aWyI9RVQ9HM

Current behavior:

Bad currency convertion when I change the currency from GBP to EUR on invoices

Expected behavior:

Correct convertion

Video/Screenshot link (optional):

https://youtu.be/aWyI9RVQ9HM

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
