### ISSUE TITLE
blog.blog.subtitle: make it editable and translateable

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#14746]
Impacted versions:
9.0, most probably 10.0 too

Steps to reproduce:

Current behavior:
The field is not editable and not translateable. This makes no sense at all.

Expected behavior:
Make the field "translate=True" and add it to the view blog.blog.form (in the group after the field name).

I'm not a developer and it would take me hours to do a proper pull request, which is a matter of 2 minutes for a regular developer.

**Comment by treviser** [comment]
@Yenthe666 This could be a very small finger exercise for your next coffee break ;-)

**Comment by Yenthe666** [comment]
Hi @treviser,

Not sure what you mean, there is a `translate=True` tag on this field in both Odoo 9 and Odoo 10?
Odoo 9: https://github.com/odoo/odoo/blob/9.0/addons/website_blog/models/website_blog.py#L22
Odoo 10: https://github.com/odoo/odoo/blob/10.0/addons/website_blog/models/website_blog.py#L20

Am I wrong here? ;-)

Regards,
Yenthe

**Comment by treviser** [comment]
@Yenthe666 probably not ;-) But it does probably not help because it is not editable? In any case, the field behaves very strange. It is not possible to edit and translate it in the backend. In the frontend (website) it somehow seems to be editable, but not translateable (it has no yellow background), it is weird.

**Comment by Yenthe666** [comment]
@treviser it actually seems to work all fine out of the box.
Could you try again on a latest runbot and add screenshots if something doesn't work? :-)

**Comment by treviser** [comment]
@Yenthe666 No, it does not work fine. I did update my blog module and test it on runbot and I can observe the following behaviour on both instances:
- It is possible to edit the subtitleon the website in one language, if it is not the master language, the field is even on a yellow background.
- After translation, the field has the same value in all languages and is not editable in other languages.

See this picture (master language German, subtitle is editable):
![selection_365](https://cloud.githubusercontent.com/assets/1814941/21260441/345e1120-c386-11e6-8c92-83406a34e291.png)


See this picture (secondary language english, subtitle is in German and not editable):
![selection_364](https://cloud.githubusercontent.com/assets/1814941/21260449/3c6bc6dc-c386-11e6-9fb6-0742a23106e9.png)

**Comment by treviser** [comment]
@Yenthe666 Now I have seen your picture in your post. In this picture your are seeing the field blog.post.subtitle, not the field blog.blog.subtitle! And my issue is that the field blog.blog.subtitle should be exactly like blog.post.subtitle.

**Comment by Yenthe666** [comment]
Hi @treviser,

I've set the master lang on Dutch for the website.

The original blogpost (in English):
![image](https://cloud.githubusercontent.com/assets/6352350/21262048/63d28ed2-c38f-11e6-9a4d-e09249c7e587.png)

The blogpost in Dutch (edited):
![image](https://cloud.githubusercontent.com/assets/6352350/21262054/71689c4e-c38f-11e6-8923-ee32ad21b8c5.png)

The blogpost in Chinese (edited):
![image](https://cloud.githubusercontent.com/assets/6352350/21262103/b8f0c686-c38f-11e6-88be-ca4d3bd13f66.png)

Am I still missing something? All those fields are translate=True in the Python code too.

**Comment by treviser** [comment]
@Yenthe666 Yes, I'm not talking about blog posts, I'm talking about blogs! See

![selection_366](https://cloud.githubusercontent.com/assets/1814941/21265119/2c78b176-c3a0-11e6-9f6f-4481079c8d4f.png)
 and here in the backend:

![selection_362](https://cloud.githubusercontent.com/assets/1814941/21265127/34aaaaa2-c3a0-11e6-943a-039892ae0d6c.png)

**Comment by Yenthe666** [comment]
@treviser forgive me if I'm slow, I'm sick in the office 🐑 
So, you're talking about the model blog.blog about the field name and the field subtitle, correct?
In the code they're both translateable:
https://github.com/odoo/odoo/blob/9.0/addons/website_blog/models/website_blog.py#L21-L22
In the runbot you can translate them too:
![image](https://cloud.githubusercontent.com/assets/6352350/21265506/0f34e416-c3a2-11e6-8c1c-8270908f5769.png)
And from the website:
![image](https://cloud.githubusercontent.com/assets/6352350/21265533/32032944-c3a2-11e6-9c5e-b5f8ed4edda5.png)

I can also translate the field subtitle in the website.
So this all works fine. I however now get what you mean. You would like the subtitle to be available in the back-end so you can see **and** translate it there too, right?

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/pull/14747

**Comment by treviser** [comment]
I'm on runbot and there is no way to translate the blog subtitle (blog.blog.subtitle) on the website. There is also no way to translate the blog name on the website, this is very unpleasant, but at least you can translate it in the backend, which is not possible for the subtitle before your pull request 14747

**Comment by treviser** [comment]
![selection_367](https://cloud.githubusercontent.com/assets/1814941/21266422/77380594-c3a6-11e6-844f-f78ec0500123.png)

**Comment by Yenthe666** [comment]
@treviser interesting, it doesn't work on your runbot but it does on mine (http://186347-9-0-1246a4.runbot10.odoo.com/fr_BE/blog/notre-blog-1?&edit_translations) which is a V9 community I took. Can you try it here? The colors do not always look to be correct either.
@JKE-be adding you here too

**Comment by treviser** [comment]
@Yenthe666 @JKE-be 
It does not work on your runbot either. I have done the following on your runbot as user Admin without changing the user language:
- I went to WebsiteAdmin and changed the website's default language to Français-BE
- on WebsiteAdmin I have added a new blog called "NouveauBlogPourYenthe"
- I went to the website blog and opened the new blog (website language now is french)
- On the website I have added the subtitle "C'est possible de faire un soustitre dans la langue originaire de la site du web (en ce cas c'est français-BE)" to the blog named NouveauBlogPourYenthe 

Now go to the blog on your runbot, change the website language to english and try to translate the subtitle your the blog NouveauBlogPourYenthe

**Comment by treviser** [comment]
@Yenthe666 @JKE-be Maybe this is also related to "sanitize=False" like here: https://github.com/odoo/odoo/issues/9510 ?

**Comment by Yenthe666** [comment]
Djezus this is one annoying bug to reproduce/find hah. Yeah I can confirm that this is not okay.
Anyway if my PR is merged you can also translate it in the backend, that would still be an improvement in my opinion (while this should be fixed too ofcourse).
@JKE-be I'll leave the second part to you buddy 😉

**Comment by treviser** [comment]
@Yenthe666 @JKE-be Yenthe, your pull request allows to translate the subtitle properly, and that's very good for a workaround as long as the user knows about it.
Thank you very much for that and now look to get healthy again, take care :-)

**Comment by JKE-be** [comment]
for translation since the front end, @Gorash could probably help you :)

**Comment by treviser** [comment]
Thanks to all for fixing this!
