### ISSUE TITLE
[Bug] Button still disabled after click cancel on js alert (confirmation alert)

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#14745]
Impacted versions: 10

Current behavior: Button still disabled after click cancel on js alert (confirmation alert)

Expected behavior: Make button enable to click again

**Comment by Yenthe666** [comment]
Hi @CakJuice,

Thanks for your report but we really need more information. Can you be more specific please?
On which alert, where is it, how do you trigger it, ..?

Regards,
Yenthe

**Comment by CakJuice** [comment]
@Yenthe666 
in my view.xml i have button like:
<tree>
<button name="some_action" icon="fa-times-circle" string="Some String" type="object" confirm="Are you sure?"/>
</tree>

**Comment by CakJuice** [comment]
@Yenthe666 
in my view.xml, i have button like:
`<tree>
<button name="action_button" icon="fa-times-circle" string="Button String" type="object" confirm="Are you sure?"/>
</tree>`

**Comment by Yenthe666** [comment]
@CakJuice so this is custom development and you've made a button in a treeview? Am I correct on these assumptions?

**Comment by CakJuice** [comment]
@Yenthe666 yes, you are right. i build custom module

**Comment by Yenthe666** [comment]
As this was about custom development and not in the Odoo source code itself I'm closing this.
Please do ask these questions on the official help forums (help.odoo.com) where plenty of people can help you!

**Comment by CakJuice** [comment]
ok, thanks for your attention
