### ISSUE TITLE
Odoo 10 Bank Statements Reconciliation UI Error (bugged, because of overflow: hidden;)

### ISSUE THREAD

**Issue by rafi16jan** [odoo/odoo#14743]
Impacted versions: 10 Community

Steps to reproduce: Reconcile Bank Statement

Current behavior: Bugged (some kind of broken CSS)

Expected behavior: Normal Success Reconciliation

Video/Screenshot link (optional): 
![odoo-bug](https://cloud.githubusercontent.com/assets/7939687/21255343/f676c95c-c39d-11e6-93d6-c1a7835947be.png)

![image](https://cloud.githubusercontent.com/assets/7939687/21255364/0c527316-c39e-11e6-9d97-72c178f21924.png)

**Comment by rafi16jan** [comment]
@Yenthe666

**Comment by rafi16jan** [comment]
@JKE-be @Yenthe666

**Comment by rafi16jan** [comment]
Hello? no one responds?

**Comment by Yenthe666** [comment]
Hmm this one got lost in the message pile so it seems, sorry! 😉 
@nle-odoo perhaps you could look at this?

**Comment by nle-odoo** [comment]
Hello,


It should be solved with https://github.com/odoo/odoo/commit/983237a53

Regards,
