### ISSUE TITLE
[FIX] Sales: Pricelist round method problems

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#147417]
What are the steps to reproduce your issue?
Go to sales, product, pricelist, and generate a formula rule with round method of 5, and have the option extra fee 

What is the current behavior that you observe?

If you have product with cost of 1000,discount of -20% (1200), and extra fee of 92 (1292), and the round method of 5, give the final price of 1292

What would be your expected behavior in this case?

The round rule need to be the last rule to apply in the formula, the correct price of the product need to be 1295, and every product should be have price of 5 or 0  at the end of the price.

The option of rounding method will help for payment in cash, the only option to apply the extra fee option at final is to generate a visual strategy to put price like 99.99 instead of 100 (with a negative extra fee of -0.01).

**Comment by vava-odoo** [comment]
Hi @chapital 

> the only option to apply the extra fee option at final is to generate a visual strategy to put price like 99.99 instead of 100 (with a negative extra fee of -0.01).

This is exactly how it was designed. It is therefore always apply after the rounding.

Cheers
