### ISSUE TITLE
Domain with .shop can not be used with odoo

### ISSUE THREAD

**Issue by lew-tolstoi** [odoo/odoo#14756]
Impacted versions: Odoo 10.0-20161211 (Community Edition)

Steps to reproduce: use odoo with  any *.shop domain. Then go to your shop url www.you.shop/shop and click to any produkt. Then click to "Add to cart" und you will get "404 Not found" because you will be forwardend to www.you.shop/card and not to www.you.shop/shop/card 

Current behavior: whily and any product to cart you will be forwarded to wrong URL which ends in 404.

Expected behavior: you should be forwarded to overview of your cart  (www.you.shop/shop/cart)

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Thanks for the reporting.

It will be fixed in previous version today, so it should be merge in 10 this week.

Best regards

JKE
