### ISSUE TITLE
Accounting - Customer Invoice - Advanced Prices - does not fetch price from pricelist

### ISSUE THREAD

**Issue by cs1982** [odoo/odoo#14751]
Impacted versions: 10.0 Community Edition

**Steps to reproduce:**
Activate 'Advanced Pricing' (3rd option)
Define Test-Product: price 1 €, saleable
Define Price for Test-Product in Public Pricelist: Price 2 €
Define Pricelist 'Resellers': rule '10% discount for all products' without begin-/ enddate
Define Test-Customer: pricelist 'Resellers'
Create Customer Invoice in Accounting:  Test-Customer, Test-Product -> price 1 € is fetched instead the price from Pricelist 'Resellers' (1,8 € = 2 € - 10%)!

**Current behavior:**
Wrong price when using Customer Invoice.
Right price when using Sales Order and creating Invoice from SO

**Expected behavior:**
Fetching correct price from the pricelist which is allocated to customer

**Video/Screenshot link (optional):**
<img width="1370" alt="odoo 1 test-product" src="https://cloud.githubusercontent.com/assets/3968448/21286587/6151a278-c40d-11e6-8658-b2c47c9cadfa.png">
<img width="981" alt="odoo 2 publice price" src="https://cloud.githubusercontent.com/assets/3968448/21286588/68edecd0-c40d-11e6-909a-6669f9b22d78.png">
<img width="977" alt="odoo 3 reseller price" src="https://cloud.githubusercontent.com/assets/3968448/21286589/6b2fd9c2-c40d-11e6-8c90-23e380d05695.png">
<img width="1374" alt="odoo 4 customer invoice" src="https://cloud.githubusercontent.com/assets/3968448/21286590/70964cb6-c40d-11e6-8f30-6dc6619e1227.png">
<img width="1370" alt="odoo 5 sales order" src="https://cloud.githubusercontent.com/assets/3968448/21286591/733c3f98-c40d-11e6-9a05-cf9a12129ab7.png">

**Comment by bistaray** [comment]
Odoo Invoices have no knowledge of (and do not use) pricelists.  The only way Odoo will charge a price in a pricelist on an Invoice is when the Invoice is generated from the Sales Order.

So the experience you are having is by design, not a bug.

Community developers have added this functionality via modules such as [https://www.odoo.com/apps/modules/8.0/account_invoice_line_pricelist/](https://www.odoo.com/apps/modules/8.0/account_invoice_line_pricelist/)

**Comment by Yenthe666** [comment]
Hi @cs1982,

As stated by @bistaray this is not a bug or issue, this is done by design.
There are no plans on adding this functionality in at this point either, so you'd have to code it your own or add the module that Ray has provided in the comment above me.

Regards,
Yenthe
