### ISSUE TITLE
Missing menu entries

### ISSUE THREAD

**Issue by lucasrabelo** [odoo/odoo#14752]
Impacted versions: 8.0

Steps to reproduce: Install Odoo from scratch with git clone, then running: 
$ ./odoo.py setup_deps
$ ./odoo.py setup_pg
$ createdb mydb
$ ./odoo.py -d mydb
# Stop the server with Ctrl-c
$ createdb mydbdev
$ ./odoo.py -d mydbdev

Current behavior: After these steps the menu entries for Technical do not show

Expected behavior: The menu entries should appear

Video/Screenshot link (optional):
![captura de tela de 2016-12-17 11-00-57](https://cloud.githubusercontent.com/assets/5579942/21290268/842279a0-c492-11e6-9623-8e7a1feadc56.png)

**Comment by daramousk** [comment]
Does your administrator user have the appropriate rights?

**Comment by lucasrabelo** [comment]
That's right what! Thanks a lot. Just another question: shouldn't be standard have that marked with the demo data?
