### ISSUE TITLE
[10.0][9.0] l10n_*: Localization Constraints won't allow standardized localizations

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#14763]
**Impacted versions:**
9.0, 10.0, maybe others

**Steps to reproduce:**
Make a new PR for localization, some changes are not possible.

**Current behavior:**
1. No possibility to append legally required sequences with predefined prefixes, steps (and other information)
3. There's no way to pre-assign tax groups to taxes in the data xml
4. The whole Latin America depends on third modules for localization, because a single journal won't allow to use multiple sequences (but that's a bigger issue: https://github.com/odoo/odoo/issues/14059) 

**Expected behavior:**
Change the framework or actual constraints to allow this changes.

**Comment by pedrobaeza** [comment]
This has been handled through multiples later issues, so I close this general one.
