### ISSUE TITLE
[8.0] Sale/Purchase receipt amounts not rounded

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#14765]
Impacted versions: 8.0

Steps to reproduce:
1. set currency rounding factor to 0.05
2. create tax with eg. 8%, set tax included
3. create purchase receipt with one line and amount of 22.50
4. select tax previously created 
5. press update button/link

Current behavior:
in purchase receipt line, amount will be calculated based on selected taxes, but not rounded
tax amount will be calculated, but not rounded
total amount is keep correct
![odoo_8_receipt_not_rounded](https://cloud.githubusercontent.com/assets/4398840/21315855/5861b1ec-c5fe-11e6-8bd6-3c4bf7e55c62.png)

Expected behavior:
purchase line amount should be rounded
tax amount should be rounded

thanks for checking, confirming and fixing... at least this is issue number 2'322

**Comment by thomich** [comment]
Would be nice to get any feedback about this...

Thanks

**Comment by Yenthe666** [comment]
Hi @thomich,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
