### ISSUE TITLE
[10.0] Cannot Change Warehouse code with same warehouse name !

### ISSUE THREAD

**Issue by Elghard** [odoo/odoo#14766]
Impacted versions:
10.0
Steps to reproduce:
1. Edit Warehouse
2.  Change Warehouse Code without change name
3. Save

Current behavior:
Odoo Server Error TypeError: coercing to Unicode: need string or buffer, NoneType found
Error found when replacing warehouse.name with NoneType (varible new_name because it is null). 

Found on module:
stock/models/stock_warehouse.py line 617
mrp/models/stock_warehouse.py line 126
purchase/models/stock.py line 132

Expected behavior:
Success to save without error.

Video/Screenshot link (optional):
![untitled](https://cloud.githubusercontent.com/assets/9044676/21316151/74b8af8a-c63a-11e6-9f6b-5fcf30214f5c.jpg)

**Comment by mart-e** [comment]
Hello,

Thanks for the report, I confirm the bug.
I have fixed it at 51e6bb4
