### ISSUE TITLE
Report Details of sales on Point of sale not filter by date from wizard

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#14789]
**Impacted versions:**
10
**Steps to reproduce:**
Generate report report_saledetails from wizard and filter by dates, report not show data because dates not pass by context, are pass by variable data.

![image](https://cloud.githubusercontent.com/assets/7775116/21364379/9929c442-c6be-11e6-8d9b-08475f4dd4ef.png)

DB has order from 13 to 18 december, filter on wizard from 01 to 20 december

![image](https://cloud.githubusercontent.com/assets/7775116/21364446/ea85dbaa-c6be-11e6-96ec-adb417a6b420.png)

Report is empty, because filter today, dates on wizard not are passed to report by context

![image](https://cloud.githubusercontent.com/assets/7775116/21364480/0dd5a0cc-c6bf-11e6-9aff-6610362a6baf.png)

**Current behavior:**
Report not filter by dates on wizard, every filter today

**Expected behavior:**
Reprot filter by dates specified on wizard

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Thank you for the report, I agree with it.
It was fixed at eca8a08710ef16b17780e917740c268b61bf11e6
Let us know if there is another issue

**Comment by celm1990** [comment]
Thank you very much.

On report Fields type numeric(Quantity, Price unit, payment  amount) have not align, must be **class="text-right"**, you can fix it?.

**Comment by mart-e** [comment]
I am not sure to understand to which view you are referring to. If you have a fix, do not hesitate to create another request or to point me to the one fixing it.

**Comment by celm1990** [comment]
**Before**

![antes del cambio](https://cloud.githubusercontent.com/assets/7775116/21426680/373231dc-c81e-11e6-9b04-e47f0277e217.png)

**After**
![despues de cambio](https://cloud.githubusercontent.com/assets/7775116/21426688/3d6d2430-c81e-11e6-9f1b-d36556ae6e72.png)


FIX [here](https://github.com/InSisComp/odoo/commit/2c27f549204a48cc35572e18628b6510b9a1a887)

**Comment by mart-e** [comment]
But with your patch the numbers are no longer under the column title which is odd.
But please, let's keep one issue for one bug and open another if you want to discuss another issue.
