### ISSUE TITLE
[8.0] Modal windows not resizing correctly

### ISSUE THREAD

**Issue by pedrorgil** [odoo/odoo#1479]
Modal windows in Odoo v8 are created as a DIV that contains the whole content (header, inner content and footer) and that adapts its height to the height of the content, so scrolling up and down a window with large content makes it impposible to see the header and footer (and thus the action buttons in footer) at the same time. So when opening a modal window which height is bigger than the screen height the footer is hidden and you have to scroll down to get to it.
Case:
Knowledge -> Directories -> CREATE -> Security tab -> Group name: ADD AN ITEM:
![captura de pantalla 2014-07-31 a la s 13 46 43](https://cloud.githubusercontent.com/assets/1769379/3763806/70e4c21e-18a8-11e4-8a39-baec6ccff7ff.png)
Actions buttons in footer are hidden below, you have to scroll to see them:
![additem2](https://cloud.githubusercontent.com/assets/1769379/3763698/aff42564-18a6-11e4-9756-b365f6bab44b.png)
But then you can not see the header.

This happens when the size of the list is meant to be known before opening the modal window. When you dynamically add items to a list it happens that the height of the window grows (as much as the list does) and if it reaches the botton of the navigator window the footer is lost "forever" and you can't even get to see it scrolling down.
Case:
Knowledge -> Directories -> SELECT "Admin Folder" -> EDIT -> LINK TO "Parent Directory" (modal window opens):
![captura de pantalla 2014-07-31 a la s 13 41 05](https://cloud.githubusercontent.com/assets/1769379/3763748/ae106e50-18a7-11e4-970a-bb72eecb45a3.png)
Now go to  Security Tab -> Group name: ADD AN ITEM
![captura de pantalla 2014-07-31 a la s 13 42 40](https://cloud.githubusercontent.com/assets/1769379/3763763/d8694140-18a7-11e4-9d3e-6a1d2e163107.png)
Select all groups, scroll down (neccesary as the footer is hidden) and click SELECT button:
![captura de pantalla 2014-07-31 a la s 13 44 26](https://cloud.githubusercontent.com/assets/1769379/3763786/1ff1eb52-18a8-11e4-9932-4b6f545e4963.png)
Now footer is hidden and you can't get to see it even scrolling down, so you can't finish the action the window is supposed to do. We have noticed that this last behaviour that makes it impossible to reach the footer appeared when updating bootstrap to version 3.2.0 in the web module (about 20 days ago), we don't know if it could be directly related to this bug or not.

**Comment by Yenthe666** [comment]
Hi @pedrorgil ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: As it is labeled wishlist it will keep popping up though - don't worry.

Regards,
Yenthe
