### ISSUE TITLE
[10.0] Helpdesk Workflow

### ISSUE THREAD

**Issue by Yotouille** [odoo/odoo#14791]
Hi,

I have been trying to setup a workflow for `helpdesk` tickets but I can't manage to change the ticket stage automatically inside an Activity. Maybe I'm not doing it the right way.

### Steps to reproduce:
Trying to change "stage" of ticket with Python Action: `write({'stage_id': <integer>})`
But I can't find the `<integer>` linked to a "stage".

### Current behavior:
Exemple with a random integer:
> Odoo Warning - Missing Record
> Record does not exist or has been deleted.

Thanks !

Y.

**Comment by Yenthe666** [comment]
Hi @Yotouille,

Thanks a lot for your report but the Github issues tracker is only for bugs in the official code. It isn't used for asking questions and we try to keep the issue tracker clean.
I'd suggest you to create a new question on the official help forums, where a lot of people can help you. You can do this are Odoo.com/help

Regards,
Yenthe
