### ISSUE TITLE
HTTP tests not working with PreforkServer

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#14802]
Impacted versions: 8, 9, 10

Steps to reproduce:

1. Try to run PhantomJS tests setting some workers: `odoo.py --database demo --init website --test-enable --update website --workers 4 --config /etc/odoo/openerp-server.conf` [to make Odoo use `PreforkServer`](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L961-L962).
2. Now do it [setting `--workers 0` to use the `ThreadedServer`](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L963-L964), which [includes support for HTTP tests](https://github.com/odoo/odoo/blob/8245c1d1d87b443701b161d8d4a42df2b4d13aec/openerp/service/server.py#L314-L317).

Current behavior:

On step 1, you'll get `phantomjs: <phantomLog>error Timeout`.

Expected behavior:

Test should get executed correctly, like on step 2.

@Tecnativa @odony

**Comment by odony** [comment]
Indeed, running the testsuite is not supported in multi-process (worker/pre-fork) mode, for multiple reasons: no multiple/concurrent execution of tests, necessity for in-memory cross-request statefulness (test cursor), etc.

We have no plan to work around these issues, as there seems to be no strong use case.
Our testsuite is mainly focused on the business/framework aspects, and not scalability/deployment aspects - which would require a much more complicated test infrastructure.

(Closing as wishlist)

**Comment by pedrobaeza** [comment]
It would then desirable to document this. Is there any section about that?

**Comment by Yenthe666** [comment]
Hmm I agree with @pedrobaeza, this should be atleast documented somewhere.

**Comment by Yajo** [comment]
I have a better idea: do not use prefork server in test mode. 1-line patch. Let me open it.
