### ISSUE TITLE
l10n_DK changes to manifest files

### ISSUE THREAD

**Issue by alyngsoe** [odoo/odoo#148085]
Impacted versions: 16 17

Steps to reproduce:

Current behavior:
Authors of l10n_dk are not complete
Expected behavior:
Please change authors to include "FlexERP ApS"
We have contributed quite a lot on the functional and administrative part of l10n_DK modules on v17.
@Olivier-olma

**Comment by Olivier-olma** [comment]
I agree

**Comment by FlorianGilbert** [comment]
Hello, 

The PR is made: https://github.com/odoo/odoo/pull/149006
Thank you again for your help!
