### ISSUE TITLE
How use Project 

### ISSUE THREAD

**Issue by user998877** [odoo/odoo#14803]
Impacted versions: 9

Steps to reproduce: In Project Managment module when create new project we have 3 option. First is Customer Project: visible in portal if the customer is a follower.

Current behavior:

Expected behavior: How use that?
Video/Screenshot link (optional): https://postimg.org/image/tw871f8xd/

**Comment by Yenthe666** [comment]
Hi @user998877,

Thanks a lot for your report. However, Github issues are only for bugs in the official Odoo code, not for asking questions.
Please post this question on the official Help forums (odoo.com/help), there are plenty of people who can help you there.

Regards,
Yenthe
