### ISSUE TITLE
Tours do not trigger delegated events

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#14808]
Impacted versions: 9.0

Steps to reproduce:

Imagine you want to add a onchange to inputs inside a form, and you bind events in a [delegated](http://api.jquery.com/on/#direct-and-delegated-events) manner:

```
$("#my_form").on("change", "input", mymethod)
```

And now you want to test it in a tour, so you add a step like this to it:

```
{
  title: "test mymethod gets triggered",
  element: "#my_form input:first",
  sampleText: "foo",
}
```

Current behavior:

`mymethod()` will not get triggered in the tour, unless you bind the event directly:

```
$("#my_form input").on("change", mymethod)
```

Expected behavior:

Tours should trigger delegated events in the same fashion as they do with direct ones.

@Tecnativa @ged-odoo

**Comment by pedrobaeza** [comment]
@Yajo is the problem still present? Any workaround?

**Comment by Yajo** [comment]
v10 tours seem to work fine, v9 still need the workarounds.

**Comment by pedrobaeza** [comment]
Well, then I think we can forget about this one as we tend to go to newer versions.

**Comment by Yenthe666** [comment]
Hmm, should we close it then?

**Comment by Yajo** [comment]
I suppose the official fix is "upgrade to v10". Closing.
