### ISSUE TITLE
MRP Repair: duplicated moves after confirming previously cancelled repairs

### ISSUE THREAD

**Issue by andreparames** [odoo/odoo#14813]
Impacted versions: 9.0 (at least)

Steps to reproduce:
1. Create new repair order
2. Confirm the order, Start it, then Cancel it, Set to Draft
3. Follow the complete flow (Confirm, Start, End)

Current behavior: All stock moves are generated in duplicate. 

Expected behavior: Non duplicated moves.

==================================================

From what can tell, this is because the `action_cancel_draft` method (called by the Set to Draft button) calls `create_workflow()`, while the previous workflow remains. Calling `delete_workflow()` before (like the `account.invoice` class does in its equivalent method) seems to fix it.

**Comment by pedrobaeza** [comment]
Is this still happening in latest code version?

**Comment by andreparames** [comment]
@pedrobaeza they've removed the workflow wholesale, so probably not.

**Comment by hmrodrigues** [comment]
@andreparames @pedrobaeza this still happens on the latest code, I was able to reproduce it on runbot

**Comment by pedrobaeza** [comment]
@hmrodrigues please open a new issue with the steps to reproduce the problem.

**Comment by hmrodrigues** [comment]
@pedrobaeza new issue is #25542
