### ISSUE TITLE
mrp: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by leio** [odoo/odoo#14812]
Impacted versions: 10.0 git

Steps to reproduce: Upgrade mrp module or any other module inheriting mrp.bom model

Current behavior: Spews warning in terminal in development mode:
/path/to/odoo/models.py:362: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif not all(cols[field.name][key] == vals[key] for key in vals):

with unknown consequences thereafter.

Expected behavior:
Proper unicode handling in core Odoo code.

Please handle things in unicode properly or work towards finally upgrading to have Odoo usable with python3 where proper unicode is the default. I would suggest just always using unicode strings with python2 as well via u"" or u'' strings for non-technical strings that get translated.
Meanwhile, please fix this instance of it at
https://github.com/odoo/odoo/blob/81a4830c738b3c601a3aae7f7bcdcd7a4f7abb1f/addons/mrp/models/mrp_bom.py#L55
where there are fancy non-latin1 quote arguments around 'produce' for the help string of picking_type_id of mrp.bom model by either making it unicode or using non-fancy quoting.

**Comment by yelizariev** [comment]
mrp_bom.py was fixed at https://github.com/odoo/odoo/commit/c0ec09e9d56485f3c6a24593bbc0240f54e433c3

One who faced the same problem without understanding what is going on (like I did), here is quick tip:
use ``u`` prefix before strings with none-ascii characters, e.g. https://github.com/it-projects-llc/misc-addons/pull/453/commits/3ca4fcdc021099e4fce4aa93fa8cac0ab59afa27
```

-    family = fields.Text(string='Family', help="Notes on family members – wife and kids")		
+    family = fields.Text(string='Family', help=u"Notes on family members – wife and kids")

```
(dash is non-assci here)

**Comment by pedrobaeza** [comment]
One clarification:

`-` is an ASCII char
`–` isn't (I think it's called stylish dash or similar)

**Comment by Yenthe666** [comment]
Yep exactly, this can be closed. Good catch guys!
