### ISSUE TITLE
[7.0] Missing french translation for error message

### ISSUE THREAD

**Issue by ptombez** [odoo/odoo#1482]
The error message 

> The requested operation cannot be completed due to security restrictions. 
> Please contact your system administrator.\n
> \n
> (Document type: %s, Operation: %s)
> is not translated in french.

Affected file : `odoo/openerp/addons/base/i18n/fr.po`
Proposed translation :

> L'opération demandée ne peut pas être effectuée en raison de la politique de sécurité. 
> Veuillez contacter votre administrateur système.\n
> \n
> (Type de document: %s, Opération: %s)

**Comment by Yenthe666** [comment]
This should be handled by now. You can now follow-up and manage translations on Transifex (transifex.com/odoo/).
It is working fine from V8 and up now too. 

Regards,
Yenthe
