### ISSUE TITLE
[10.0] analytic tags not present when invoicing down payments

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#14847]
**Impacted versions:**
10.0

**Note: You need a database with analytic accounting activate to reproduce this issue.**

**Steps to reproduce:**
1. Create a quotation
2. Add a line, to this line add analytic tags
3. Confirm quotation
4. Hit Create invoice and choose down payment (percentage)

**Current behavior:**
1. New invoice is generated based on the down payment line added to the sale order.
2. At the new invoice line of the down payment, there are no analytic tags.

When you invoice an invoice-able product and create the invoice choosing "invoice lines" , all tags used on the sale.order.line are present after on the new invoice lines.

**Expected behavior:**
* New invoice line for down payment should include analytic tags from sale.order lines.

**opw:** 
702901

**Comment by nim-odoo** [comment]
Hello,

I'm not sure I understand your issue. When a down payment is created on the SO, there is no analytic tags added to it. Therefore, the corresponding invoice line doesn't contain any analytic tag. I don't see what is the problem here.

Are you asking that the down payment line automatically contains the analytic tags of all others SO lines?

**Comment by pasgou** [comment]
Hello,
I understand that yes an invoice should be attached to the same analytic tags than SO, even if this invoice is a down payment.

**Comment by nim-odoo** [comment]
Indeed, that makes sense. When there is only one analytic tag used amongst all order lines, that's straightforward. But when several tags are used, things are not that obvious anymore. Let's say we have 2 order lines:
- Product 1, 100 €, Tag1
- Product 2, 250 €, Tag2

If I make a down payment of 75 €, and I associate both tags to it, that would mean that the amount will appear in both Tag1 and Tag2 reporting. This is obviously not correct...

**Comment by pasgou** [comment]
Or you have to make a prorata which is complicated.
In french accountancy, a down payment isn't a product as there isn't a service or a product delivered yet. So a down payment hasn't to be attached to an analytic account or tag.
But @aristobulo-eezee seems to need something else and in his case, the down payment needs to be attached to the tags. 
Odoo seems to follow a method which is normal, however.

Two things are really missing in SO and Quotations:
- a start and end date and/or a deadline date on each line for services, information which could be used in task creation, or a delivery date for products
- a means to create BOM for services (without MRP) that could be modified in SO or Quotations (quantities must be adapted for each client but the tasks could be the same). In this configuration, lines of BOM should have to be visible for vendor but invisible for client who only see the bom product.

**Comment by nim-odoo** [comment]
> Or you have to make a prorata which is complicated.
> In french accountancy, a down payment isn't a product as there isn't a service or a product delivered yet. So a down payment hasn't to be attached to an analytic account or tag.

That indeed makes sense. Anyway, when the SO is invoiced, the down payment is deduced from the total, and analytic tags are correctly copied from others SO lines. In the end, the reporting is fine, so I'm not convinced we need to change the current behavior..

**Comment by fpodoo** [comment]
Hello,

We should not change the current behavior.

In accounting, a down payment is not a revenue. As you want your analytic
accounting to reflect your costs and revenues, most companies will probably
not want to apply the tags of the revenues to the down payment.

It seems correct to me to have different tags on a down payment than the
product lines, for the same reason you have different products and taxes.


-- 
Fabien

**Comment by nim-odoo** [comment]
@fpodoo : thanks for the clarification
