### ISSUE TITLE
[hr_holidays] Department managers and other followers of the department are not notified and added as followers on new leave requests in their department

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#14848]
**Impacted versions:**
Surely v10, probably others.

**Steps to reproduce:**
* Install `hr` and `hr_holidays` module
* Create user "IT Manager"
* As IT Manager, create a new department "IT" and assign yourself as manager
* Create user and employee ("IT employee") and put him in the "IT Department"
* As IT employee, create a new leave request

**Current behavior:**
The only follower of the leave request is the employee. The manager is not added to the followers,
he doesn't receive any notification of the new leave request to approve.

**Expected behavior:**
All the followers of the department subscribed to the "Leaves/Allocations confirmed" subtype (which is selected by default), including the manager, should be added as a follower to the leave request, should receive a notification in their inbox of the new leave request to approve, and should see the needaction counter in the "Leaves" section.

Result: managers have to check periodically if there are new leaves requests, instead of the system alerting them when they have new leaves requests to act on.

**Problem:**
There are various bugs in the [`create method of hr_holidays`](https://github.com/odoo/odoo/blob/85160f8da2b2097ab9dfee8909bd4977eb133a2d/addons/hr_holidays/models/hr_holidays.py#L346):
* In most cases, there is no `'state'` key in the create values. The value, most of the times, comes from the defaults and is not passed by the web client.
* `self` in `self.subscribe_followers(` is an empty recordset; it should be replaced with `holiday` returned from the super `create`
* The call to `subscribe_followers` is after the creation which creates the first message ("Request created and waiting confirmation"), so even if the previous two problems are fixed, the manager would not receive a notification for the first message; but only for subsequent ones.

cc @Icallhimtest

**Comment by Icallhimtest** [comment]
Indeed, in create, after the creation it should read:
```
if holiday.state == 'confirm':
    holiday.subscribe_followers()
```
It was probably blindly copied from the write, and indeed even with this fix you're subscribed after the creation, so you don't get notified. 
For the write, it can be fixed by doing the check before writing, but I don't see a quick fix for the create.

@tde-banana-odoo is there a way to add the followers before the notifications are sent during the creation ?

**Comment by Icallhimtest** [comment]
This could be a potential fix: https://github.com/odoo-dev/odoo/commit/03514e0644e22101e09dd5b86687b5558a3b4a37

Thought it's not very clean

**Comment by tde-banana-odoo** [comment]
@Icallhimtest You may have a look at _add_follower_command method in mail_followers.py .

**Comment by LeartS** [comment]
Is it not possible to remove the `mail_create_nosubscribe` from the context when calling create and add the followers in the `message_follower_ids` values?

**Comment by Icallhimtest** [comment]
Sadly it will not work as expected due to the department_id being a related field, as explained in the subscribe_followers method.
I do not know why `mail_create_nosubscribe=True` was added in the first place but I can only assume there was a reason (leave creator doesn't need to follow maybe).

@tde-banana-odoo Can I have LGTM on this fix ? https://github.com/odoo-dev/odoo/commit/080941f267ab6ffc51675302adfaf1da376eedbe

**Comment by ritsute** [comment]
I applied the Patch on commit 1879964 but it seems to throw error in odoo.

http://pastebin.com/T67ddjyY

**Comment by Icallhimtest** [comment]
Hello @ritsute,

Did you modify odoo\addons\hr_holidays\models\hr_holidays.py ?

Your logs are telling you there is an indentation error at line 351. So your server is not loading hr_holidays.py, and it cannot load data associated to that model. (and it keeps on retrying and failing)

What you should have around line 351 is 
```    @api.model
    def create(self, values):
        """ Override to avoid automatic logging of creation """
        employee_id = values.get('employee_id', False)
        if not self._check_state_access_right(values):
            raise AccessError(_('You cannot set a leave request as \'%s\'. Contact a human resource manager.') % values.get('state'))
        if not values.get('department_id'):
            values.update({'department_id': self.env['hr.employee'].browse(employee_id).department_id.id})
        holiday = super(Holidays, self.with_context(mail_create_nolog=True, mail_create_nosubscribe=True)).create(values)
        holiday.add_follower(employee_id)
        return holiday```

There's no reason to have an indentation error if you have the same code there.

**Comment by ritsute** [comment]
Hey Icallhimtest,

Sorry about that. Wasn't familiar with python quirks. Somehow the spaces got converted to tabs resulting in the error. Thanks for the heads up! :smile:

**Comment by Burtonsnow82** [comment]
Sorry but I've the same .py file mentioned on commit 1879964, but the problem still remaining.
When employe insert new leave request, his manager don't receive any notification...please help me 
Odoo 10
