### ISSUE TITLE
Stripe Payment Provider does not accept Pay Pal and other common payment methods

### ISSUE THREAD

**Issue by AquaMCU** [odoo/odoo#148491]
Impacted versions:
V17

Steps to reproduce:
Install Stripe and test ... 

Current behavior:
Only Card and Giropay is offered by stipe ( As ODOO requests - see below )

Expected behavior:
All payment methods should be available ( Paypal & Others)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Hello hello.

I try to setup stripe so that the useres can pay via paypal using stripe. To be clear, I do not want to integrate paypal directly.

So I added the paypal icon in ODOO and the paypal method in stripe. In the stripe preview, I can see paypal, but during checkout, I can not see it.

I have debugged a little and it seems, that ODOO is only requesting "Giropay" and "Cards" ( see JSON ). I think it is a bug in ODOO, right? Can I fix that?

The request from ODOO to stripe lookss like:

[...] 

"payment_intent_data": {

    "description": "S00025-1",

    "capture_method": "automatic"

  },

  "mode": "payment",

  "success_url": "https://.../payment/stripe/checkout_return?reference=S00025-1",

  "payment_method_types": {

    "0": "card",

    "1": "giropay"

  }

}

In the ODOO stripe configuration, ONLY the following payments are implemented:

DEFAULT_PAYMENT_METHODS_CODES = [
    # Primary payment methods.
    'card',
    'bancontact',
    'eps',
    'giropay',
    'ideal',
    'p24',
    # Brand payment methods.
    'visa',
    'mastercard',
    'amex',
    'discover',
]

**Comment by AntoineVDV** [comment]
Hi @AquaMCU, I tested making a payment with Stripe in Odoo 17 through the `/payment/pay?amount=12` route and it seems to work fine:
![image](https://github.com/odoo/odoo/assets/15896813/5b253648-9857-4a51-973b-7f55715e4934)

The payload of the `payment_intent` request was:
```json
{
    "amount": 1200, 
    "capture_method": "automatic", 
    "currency": "USD", 
    "description": "tx-20240109083537", 
    "expand[]": "payment_method", 
    "payment_method_types[]": "paypal"
}
```
Please check that:
1. PayPal is enabled on your Odoo database (from the Stripe payment provider: Configuration > Enable Payment Methods > toggle the Active field for PayPal). The `DEFAULT_PAYMENT_METHODS_CODES` constant defines which payment methods are enabled by default, but others are supported.
2. PayPal is enabled on Stripe, and you have configured the website domain.

**Comment by AquaMCU** [comment]
Hi.

Thank you for the fast replay. I can confirm that is correct. But that is not my usecase. 

My client ONLY wants to pay via stripe. And there he wants to use Paypal.

As far as I can see, you do not have stripe enabled ( or is it the cards method? )  If you would, you would see something like "general payment methods" that is basically the stripe payment method. If you chose that, you are rederected to stripe. There Paypal and wire transfer is missing!

**Comment by AntoineVDV** [comment]
Starting with Odoo 17, you don't see Stripe anymore on the payment form, you see its payment methods (Cards, PayPal...) directly. Also, since Odoo 16.4 Stripe does not redirect anymore; you pay directly from the Odoo payment page.

If you wish to offer only PayPal through Stripe in Odoo 17, you must disable all payment methods but PayPal.

**Comment by AquaMCU** [comment]
I will try to update to 17.0 and check again. Thanks for all the info!

**Comment by AntoineVDV** [comment]
I'm closing the issue since it works as expected, but feel free to reopen ;)
