### ISSUE TITLE
Inbox message counter in 'Discuss' module

### ISSUE THREAD

**Issue by PieterPaulussen** [odoo/odoo#14858]
Impacted versions:
V9 Community, V9 Enterprise

Steps to reproduce:
1. Open a new runbot instance and login with admin. 
2. Go to discuss app and a mail to demo user.
3. Login as Demo user
4. Open Inbox
5. Mark all messages as read

Current behavior:
The counter for unread messages keeps a remaining number of messages as read but does not display these messages.

Expected behavior:
The counter should be set to 0 or the remaining messages should be displayed.

**Comment by PieterPaulussen** [comment]
Problem:
in chat_manager.js the function fetch_from_channel there is a call to 'add_message' which includes an array of channel ids. Sometimes msg.channel_ids is empty. In this case, no messages are displayed.

**Comment by Yenthe666** [comment]
@JKE-be can you have a look? It is rather a cosmetic fix but I agree that it should update.
Also, hi @PieterPaulussen 😉

**Comment by PieterPaulussen** [comment]
@mart-e Is there any feedback on this issue?
@Yenthe666 Hello!

**Comment by PieterPaulussen** [comment]
@JKE-be @mart-e 
Is it possible to provide some feedback on this issue? Thx!

**Comment by angelmoya** [comment]
This problem affect also in version 10, if you check "Mark as read" nothing happends

**Comment by Yenthe666** [comment]
As an update: it now kind off does this. If you click "Mark all read" they're all removed from the view but the counter isn't fully cleared:
![image](https://user-images.githubusercontent.com/6352350/34878240-ceee4a04-f7a9-11e7-8287-658ae80c7697.png)
I'm totally annoyed by these bugs and so are the customers so I made an OPW with number 805185

**Comment by Yenthe666** [comment]
There was a final fix at https://github.com/odoo/odoo/commit/ea700016d

**Comment by intero-chz** [comment]
@Yenthe666 what about the 10.0 issue? Or will it be forwarded?

**Comment by TelmoSenseFly** [comment]
@Yenthe666 i subscribe the question done by @intero-chz . There is any fix for this bug in 10.0?

**Comment by Yenthe666** [comment]
@intero-chz and @TelmoSenseFly there has been some improvements/fixes for V10 but not everything is done in the stable 10.0

**Comment by grivalta** [comment]
This trouble is really bothering also in Odoo 11 CE. In my case, in addition to this problem, all the unread messages are no longer displayed in the queue. Here is a simple workaround for me: after many attempts I noticed that the issue acts only if the "Public" flag on the user is selected. By unchecking that flag all these problems disappear: the message cnt reprises to work and all unread messages are listed correctly.
