### ISSUE TITLE
[8.0] Many2Many tree create/edit attributes are ignored

### ISSUE THREAD

**Issue by IBSNA** [odoo/odoo#14864]
Impacted versions: **8.0**

Steps to reproduce:

- Create a form with a tree view for a **Many2Many** field
- Add attributes create="false" or edit="false"

Current behavior:

- **Always considered true**
- Affected code: **web/static/src/js/view_form.js**
Specifically this method must be removed:

`is_action_enabled: function () { return true; },`

We believe this was fixed before and was reintroduced, probably due to some merge operation.

Expected behavior: **true/false depending on what the developer specified.**

**Comment by rayer91** [comment]
I can turn off the sale count with the code above and the error disappear.

``` class product_product(models.Model):
    _inherit = 'product.product'

    def _sales_count_override(self, cr, uid, ids, field_name, arg, context=None):
        #r = dict.fromkeys(ids, 0)
        #domain = [
        #    ('state', 'in', ['confirmed', 'done']),
        #    ('product_id', 'in', ids),
        #]
        # I think there are the issue
        #for group in self.pool['sale.report'].read_group(cr, uid, domain, ['product_id', 'product_uom_qty'], ['product_id'], context=context):
            #r[group['product_id'][0]] = group['product_uom_qty']
        r = 0
        return r

    _columns = {
        'sales_count': fields.function(_sales_count_override, string='# Sales', type='integer'),

    }
```

**Comment by Yenthe666** [comment]
Hi @IBSNA,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
