### ISSUE TITLE
Traceback on mass reconciliation of payments and invoices

### ISSUE THREAD

**Issue by funcurv** [odoo/odoo#14866]
Impacted versions:
10.0
Steps to reproduce:
1. Create Customer Invoice and Validate
2. Make Payments on Payments screen and confirm
3. Open Manual Payments and Invocies and try to reconcile hitting CTRL-Enter for mass reconciliation

Current behavior:
Odoo server error raised with traceback
File "/home/odoo/runbot/extra/runbot/static/build/188623-10-0-347494/odoo/addons/account/models/account_move.py", line 729, in process_reconciliations
    self.process_reconciliation(datum['mv_line_ids'], datum['new_mv_line_dicts'])
TypeError: process_reconciliation() takes exactly 2 arguments (3 given)

Expected behavior:

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/17149532/21532189/3596954a-cd4e-11e6-94fa-be2195bd9f7b.png)

**Comment by SBC-MvS** [comment]
Hello

we have the same problem with supplier invoices.

**Comment by alexis-via** [comment]
I confirm this bug on an up-to-date odoo 10. It can be reproduced on runbot.

**Comment by alexis-via** [comment]
@SBC-MvS @funcurv Could you check out my PR #16149 and approve it if it works fine for you ?

**Comment by funcurv** [comment]
Will do a check next week as I out of office currently.

 

Von: Alexis de Lattre [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. März 2017 22:12
An: odoo/odoo <odoo@noreply.github.com>
Cc: Werner <werner.wagner@drei.at>; Mention <mention@noreply.github.com>
Betreff: Re: [odoo/odoo] Traceback on mass reconciliation of payments and invoices (#14866)

 

@SBC-MvS <https://github.com/SBC-MvS>  @funcurv <https://github.com/funcurv>  Could you check out my PR #16149 <https://github.com/odoo/odoo/pull/16149>  and approve it if it works fine for you ?

**Comment by Yenthe666** [comment]
Hi guys,

This one was already fixed with PR https://github.com/odoo/odoo/commit/91470a37fefd4cae55179e9f7986fe3205baa70b but not yet closed.
Closing as it is fixed.

Regards,
Yenthe
