### ISSUE TITLE
[8.0] Stock valuation journal entry should use current date (when doing transfer) instead of move date.

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#14872]
Impacted versions: 8.0

Steps to reproduce: Activate realtime stock valuation. Create a delivery order. Try to transfer in a new period.

Current behavior: Validation Error: 'The date of your Journal Entry is not in the defined period! You should change the date or remove this constraint from the journal     .'

Expected behavior: Valuation journal entry is created with current date, like the period is taken from the current date

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @NL66278 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
