### ISSUE TITLE
[9.0]  Vulnerability : someone scanned using accunix and then it creates a new account + multiple contacts

### ISSUE THREAD

**Issue by v3ss0n** [odoo/odoo#14884]
Impacted versions: 9.0 stable

Steps to reproduce: Seems Accunix can detect vulnerability

Current behavior:

Expected behavior:

Video/Screenshot link (optional): 
![screenshot_20161230_172724](https://cloud.githubusercontent.com/assets/419606/21563929/8ac0bc86-ceb5-11e6-9095-6303fac470da.png)

**Comment by Yenthe666** [comment]
Hi @v3ss0n,

Did you reproduce this your own or was it an external attempt?
Please try to give as much information as you can so that we can identify this.

**Comment by wtaferner** [comment]
@v3ss0n 
https://www.odoo.com/page/responsible-disclosure

**Comment by Yenthe666** [comment]
Hmm @wtaferner I agree that he should report it at security@odoo.com.
There is nothing that tells the public people about how to do it or what the leak is though, so this topic being here is fine. It is not like he found a way to hack into several Odoo environments and posted the methods here.
@v3ss0n could you please send an e-mail to security@odoo.com about this? I'd rather not keep this thread ongoing here, somebody from Odoo will look further into it.

Regards,
Yenthe
