### ISSUE TITLE
Need unicity constraint on stock.inventory.line

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#1488]
I am in big trouble at a customer site because, for some very stange reasons that we don't explain for the moment, he has several inventory lines of the same product and same stock location in the same inventory. Thus, when you validate the inventory, it generate several stock moves for that product, and the stock level is wrong !

So I think we really need to add a unicity constraint on stock.inventory.line such as this one:

_sql_constraints = [(
        'inventory_location_product_uniq',
        'unique(inventory_id, location_id, product_id)',
        'On this inventory, you have several lines with the same product '
        'and the same stock location!'
        )]

**Comment by dreispt** [comment]
Possibly related to https://github.com/odoo/odoo/issues/7391 ?

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
