### ISSUE TITLE
[10.0] Invalid product price history breaks stock valuation (fixed valuation)

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#14889]
**Impacted versions:** 10.0

**Steps to reproduce:**

1. Create a new Stockable Product
2. Set cost price to `2.00`
3. Adjust stock to 10 pcs
4. Enable developer mode
5. Go to Inventory > Reports > Inventory at Date
6. Select current time and retrieve the inventory value

**Current behavior:**
The stock valuation for the product is `0.0`.

**Expected behavior:**
The stock valuation for the product should be `20.0`

**Workaround:**
So, to overcome this issue currently we need to restart odoo and import and export the cost prices for every product.

**Other observations:**
- It seems that `product.price.history` uses [current date without lambda](https://github.com/odoo/odoo/blob/10.0/addons/product/models/product.py#L99) as `datetime`, so the history entry always gets the `datetime` when Odoo was last started up. 
- The second problem is that when product is first created, Odoo creates **two** price history entries with the same `datetime`, `write_date` and `create_date`, but different `cost`. The stock valuation report only takes one of them into account.

**Video/Screenshot link (optional):**
![valuation_issue_workaround](https://cloud.githubusercontent.com/assets/1525066/21567016/63508536-ceb1-11e6-9e1a-0be500f656b9.gif)

.. and the price history in the database:

| id | create_uid | product_id | company_id | datetime                   | cost | write_date                 | create_date                | write_uid | 
|----|------------|------------|------------|----------------------------|------|----------------------------|----------------------------|-----------| 
| 11 | 1          | 5          | 1          | 2016-12-30 10:48:16.000000 | 0    | 2016-12-30 14:52:39.668846 | 2016-12-30 14:52:39.668846 | 1         | 
| 12 | 1          | 5          | 1          | 2016-12-30 10:48:16.000000 | 2    | 2016-12-30 14:52:39.668846 | 2016-12-30 14:52:39.668846 | 1         | 
| 13 | 1          | 5          | 1          | 2016-12-30 10:48:16.000000 | 3    | 2016-12-30 14:53:05.303394 | 2016-12-30 14:53:05.303394 | 1         | 
| 14 | 1          | 5          | 1          | 2016-12-30 14:53:26.000000 | 2    | 2016-12-30 14:53:36.890684 | 2016-12-30 14:53:36.890684 | 1         | 

As you can see, ID's 11 and 12 were created on the exact same millisecond. I changed the price in ID 13 but the `datetime` is still the same. The `datetime` only changes when I restart Odoo.

**Comment by mlaitinen** [comment]
Suggested fix for problem No1: Change the default `datetime` value from `fields.Datetime.now()` to `fields.Datetime.now`.

It's still a mystery why two almost identical price history entries are generated upon product creation.

**Comment by mlaitinen** [comment]
Doesn't exactly relate to this issue, but I think it's worth mentioning that there's a typo in `product.product._set_standard_price`. `force_compay` should be `force_company`.

Also, I think there are two price history entries because `product.template` is created first, then `product.product` and the template doesn't pass `standard_price` to the variant in the `product.template.create_variant_ids()` method. There's the zero price (ID 11) and in `product.template.create()` the `product.product.write()` is called and that's the real price (ID 12).

**Comment by yostashiro** [comment]
@mlaitinen Thanks a lot for the detailed report.  I just came across this issue and created an Enterprise ticket for resolution.
