### ISSUE TITLE
Chatbot blank after refreshing or changing site page

### ISSUE THREAD

**Issue by sduponch** [odoo/odoo#148941]
Impacted versions: 16

Steps to reproduce:
go on https://www.halluneed.com
On the fisrt try it display chats FAQ but they disapear when refreshing or navigating to another page.

Current behavior:
chatbot box get blank on refresh.

Expected behavior:
FAQ questions still displayed on refresh

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by chapital** [comment]
Hi, its community or enterprise version?

**Comment by sduponch** [comment]
Entreprise

**Comment by chapital** [comment]
onpremise, saas or sh?

**Comment by sduponch** [comment]
I think it is "sh", the Odoo main site is accessible on 'myhun.halluneed.com' that is a CNAME to a odoo domain. Maybe it is a saas... it was setup by an external partner.

**Comment by chapital** [comment]
You need to contact your partner to validate if this is something wrong with the configuration, if you have saas or SH, you can also upload a ticket in the site: https://www.odoo.com/help, a consultant gonna check if this its and error, and they gonna try to give you a fix, but if the problem its configuration you need to contact your partner, this its the better way and faster way to fix it, with the GitHub gonna take weeks to validate this.

**Comment by sduponch** [comment]
The partner is not longer working with us, it took about 1 year to have this setup... we have tried everyting in the configuration panel with no luck. 

We will get another but gold certified partner soon i hope. I will take a look at the odoo help center.

**Comment by vava-odoo** [comment]
Not a standard bug
