### ISSUE TITLE
[v8] "Tab key" doesn't work as expected when inserting lines in "sales orders", "invoices", ...

### ISSUE THREAD

**Issue by antoniocanovas** [odoo/odoo#1489]
After completing the product line, if you press TAB the focus goes to the main menu of odoo.

This action must be create a new line in the document to go on with a new product.

**Comment by Yenthe666** [comment]
Hi @antoniocanovas,

Thank you for your report and sorry for the late reply.
This has been fixed in the meanwhile, if you tab now you can start a new product line and it no longer jumps to the main menu.

Regards,
Yenthe
