### ISSUE TITLE
"Payslips" string is missing on employee form view smart button

### ISSUE THREAD

**Issue by bista-amitd** [odoo/odoo#14898]
Impacted versions:
10.0
![payslip button](https://cloud.githubusercontent.com/assets/16350025/21585177/59c74716-d0e1-11e6-9392-a7600c92ae7d.png)

Steps to reproduce:
-> Open any employee form view

Current behavior:
-> You will find the smart button which redirect us to payslips doesn't have label.

Expected behavior:
-> There should be "Payslips" label on it.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @bista-amitd,

Thanks a lot for your report.
I've just checked this on the latest Odoo source and it is working fine as expected:
![image](https://cloud.githubusercontent.com/assets/6352350/21589366/48951986-d0f1-11e6-9bdb-3f27e5d96089.png)
Can you please update your Odoo codebase or try to reproduce this on a runbot?

Regards,
Yenthe
