### ISSUE TITLE
[IMP] Inventory: Reordering rules with moves.

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#148990]
What are the steps to reproduce your issue?
In this video explain how to put reordering rules based on previews sales volume, many business use this technique to establish the min and maximum quantity, from minute 9:00 to 15:00 explain all the common process to do it.
video: https://www.youtube.com/watch?v=kDgltkmt9pA&list=PLSk3SHSymptb5vbVUDlsAFxheDTfYEl3C&index=6&t=48s

The step to reproduce this are a lot, but basically its export stock moves, export reordering rules, use filter, user formulas like Vlookup establish the minimum and maximum quantity, import.

What is the current behavior that you observe?

To do this its a little bit complex and maybe can do something wrong in the process.

What would be your expected behavior in this case?

Add a better way to establish reordering rules based on previews sales.

example:
In inventory-configuration-reodering rules:

Add the option to see all the product(right now you can see only product with reordering rules established)
Add the option to see the stock moves in a column.
Add the option to filter the stock moves to show only product that have X moves, for example to hide product without moves or with low moves.
Add the option to filter moves by a period. (example: move of last 12 months).

<img width="1552" alt="stock moves" src="https://github.com/odoo/odoo/assets/21046957/d69faf36-aa8c-4ca9-97c4-c3d5ce69576b">

**Comment by chapital** [comment]
Hello @amoyaux 

Also please consider this to odoo 18

**Comment by amoyaux** [comment]
It seems a bit too specific. We try to have light interface to avoid confusing users.
However, we plan to do a report with slow and fast mover and with safety stock computation.
