### ISSUE TITLE
[9.0 10.0] shouldn't project_id and task_id be show on account.analytic.line form view? wrong view mode?

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#14893]
Impacted versions:
[9.0]
[10.0]

Steps to reproduce:
1. Use runbot
2. Navigate to **Accounting --> Adviser --> Analytic Entries**
3. Open an Entry

Current behavior:
Notice that project_id and task_id are not shown

Expected behavior:
project_id and task_id should be shown.

Discussion:
A view called **account.analytic.line.form.inherit.hr_timesheet** exists with the following architecture:
```
<field name="account_id" position="after">
    <field name="project_id" required="1"/>
    <field name="task_id" domain="[('project_id', '=', project_id)]"/>
</field>
```
See [https://github.com/odoo/odoo/blob/10.0/addons/hr_timesheet/hr_timesheet_view.xml#L32](https://github.com/odoo/odoo/blob/10.0/addons/hr_timesheet/hr_timesheet_view.xml#L32)

This view is overriding:
`<field name="inherit_id" ref="analytic.view_account_analytic_line_form"/>`

but has this mode:
`<field name="mode">primary</field>`

So it is inheriting, yet the mode is **primary**.

If the mode is changed to **extension**, then the fields show as expected.

**_Shouldn't it be an extension view?_**

If it should not be extension, what purpose does this view serve?  I can't see any other form views for account.analytic.line that would be overridden by this one in primary mode.

**Comment by Yenthe666** [comment]
Hi @bistaray,

Thank you for the report.
I've just checked and tested this and to me this looks logically. In fact, it would be handy to see both the project and task as you cannot see it anywhere else.
Looks like a bug when the person made the inherit that he set the mode to `primary`.
@mart-e can you confirm? If you confirm it I'll quickly make a PR to fix it.

**Comment by mart-e** [comment]
Hello,

We have the following inheritance graph:
```
- analytic.view_account_analytic_line_form (primary)
|- account.view_account_analytic_line_form_inherit_account (extended)
|- hr_timesheet.hr_timesheet_line_form (primary)
```

That means that if you load the view `analytic.view_account_analytic_line_form` (what is done when you click on **Accounting --> Adviser --> Analytic Entries**), you will resolve only the `analytic` view and its extensions (the one from `account`).

If you load the view `hr_timesheet.hr_timesheet_line_form` (what is done when you click on **Timesheet --> My Timesheet --> Detailed Activities**), you will resolve all extensions.

The justification is that you do **not** display the timesheet related information (project, task) on the accounting menus. If you change to extended, you will see it everywhere and it is not what we want.

**Comment by SalahAdDin** [comment]
@mart-e, thank you, you did give me a good clue.
