### ISSUE TITLE
Record dose not exist or has been deleted when i register a new user

### ISSUE THREAD

**Issue by wizmoori** [odoo/odoo#14894]
Impacted versions:
9
Steps to reproduce:
2
Current behavior:
shows alert "Record dose not exist or has been deleted"
Expected behavior:
create a new user
Video/Screenshot link (optional):
![error](https://cloud.githubusercontent.com/assets/17106146/21579165/68a5c086-cfb1-11e6-84a9-131d08562449.PNG)

**Comment by Yenthe666** [comment]
Hi @wizmoori,

Thank you for your report.
I've just tested the exact same scenario on the latest runbot and I can't reproduce this issue:
![image](https://cloud.githubusercontent.com/assets/6352350/21589398/8eab11fa-d0f1-11e6-9d4c-9f55ea93b6e1.png)
I just opened the view, clicked on create and filled in the exact same details as you.
Please update your Odoo to the latest codebase or try reproducing it on a runbot (runbot.odoo.com)

Regards,
Yenthe
