### ISSUE TITLE
[17.0] Date Widget

### ISSUE THREAD

**Issue by pgmakwana** [odoo/odoo#149019]
Impacted versions: 17.0

Steps to reproduce: Apply the date widget on datetime field

Current behavior: Entirely Date widget is not working. 

Expected behavior: It needs to be shown only the date, not the date and time

Screenshot:
 
![Date Widget Issue](https://github.com/odoo/odoo/assets/46151846/4cbbc491-9bc1-4c55-bc23-1a219725f90d)

**Comment by michaelhofer-slg** [comment]
Same here

**Comment by vava-odoo** [comment]
Hi @pgmakwana 
Thanks for reporting. I was not aware of this change in the odoo framework, but since 16.3, the widget is only valid/applied to Date, not Datetime, due to timezone issues.
The solution would be to display a computed non-stored Date field (in the computer timezone?) instead. I'll see with the team if it could be applied here (and to all occurrences?).
Cheers.

**Comment by vava-odoo** [comment]
This PR removed the uasge of the widget in master https://github.com/odoo/odoo/pull/151381

**Comment by seppe-willems** [comment]
@vava-odoo Is there a plan for introducing a replacement or an alternative method to conceal the hour notation on datetime fields in the date widget?

**Comment by vava-odoo** [comment]
@seppe-willems Not that I am aware of, no.

**Comment by michaelhofer** [comment]
Hmm this is not so good to hear. There are many places in Odoo where we now have the time, even though it's not required.

**Comment by pgmakwana** [comment]
Hello @vava-odoo 

Did you or your technical team find any replacement for this?

**Comment by vava-odoo** [comment]
Hi @pgmakwana 
As I said, I'm not aware of any plan to have it back, but I also gave a workaround. 
Default behaviour is that if it is a datetime, it will show the time as well...

**Comment by EmilioSanJose** [comment]
Default behavior makes sense: Datetime shows date and time. But why not keeping a widget to hide the time part? Creating a bunch of non-stored date fields just for this purpose is a pretty ugly solution

**Comment by michaelhofer-slg** [comment]
@vava-odoo Is there any news on this? We are looking for a way to hide the time too.

**Comment by vava-odoo** [comment]
@michaelhofer-slg Yes, there is [a work in progress](https://github.com/odoo/odoo/pull/161705) that will probably be backported in 17.

**Comment by Tscunami** [comment]
@vava-odoo, do you still think it will be backported to Odoo 17? The pull request is closed now. Do you know of any temporary solution to fix that when I use Odoo.sh?

**Comment by Tscunami** [comment]
Hello @vava-odoo. Thank you for your quick reply. For me, it still doesn't work. I have a new Development branch for Odoo version 17 latest, and when I try to do this approach:

`<record id="sd_view_sale_order_form" model="ir.ui.view">
        <field name="name">sd.view.sale.order.form</field>
        <field name="model">sale.order</field>
        <field name="inherit_id" ref="sale.view_order_form" />
        <field name="arch" type="xml">            
            <xpath expr="//group[@name='partner_details']" position="inside">
                <field name="commitment_date" readonly="state == 'cancel' or locked" widget="datetime" options="{'show_time': false}"/>
            </xpath>
        </field>
    </record>`
    
It still shows me the time when I open any sale order.  The time part remains even when I save this record. As you can see on the attached screenshot 
![image](https://github.com/user-attachments/assets/9a392c21-22ab-4a5d-98c1-16da88d18a37)

I don't want to abuse this thread to solve this issue, so I am only letting you know that it doesn't work as it should.

**Comment by pgmakwana** [comment]
Hello @all

As I have tested it, now it's working in both (List and Form) view.

If you want to hide the time in form view then you need to make that field readonly.

I'm closing this ticket as it's resolved.

USE: **widget="datetime" options="{'show_time': false}"** [WITH READONLY]
