### ISSUE TITLE
Invalid link on date change notifications (for Google Calendar generated attendees)

### ISSUE THREAD

**Issue by arraintxo** [odoo/odoo#14918]
**Impacted versions:**
Verified on Odoo 8.0

**Steps to reproduce:**
1. Sync Google Calendar account
2. Create an event on Google Calendar and invite internal users
3. Modify event date on Odoo

**Current behavior:**
Attendee receives date change notification with invalid URL's. No token present.

Example Accept Link: https://odoo/calendar/meeting/accept?db=odooDB&token=False&action=320&id=47

If link is clicked, server responds with:

---
### Bad Request
Invalid Invitation Token.

-----

**Expected behavior:**
Attendee should receive date change notification with valid URL's.

**Own guess:**
When attendees are received from Google Calendar, Odoo does not generate access_token for them, so generated URL's send "False" as token.

**Comment by tivisse** [comment]
Note to @tde-banana-odoo 

Don't always create a token but create a token when needed, i.e. when sending an email to an attendee.

**Comment by Yenthe666** [comment]
Hi @arraintxo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
