### ISSUE TITLE
unbound method _dispatch() must be called with ir.http instance

### ISSUE THREAD

**Issue by captivea-ylb** [odoo/odoo#14910]
I try to import migrate database ( V9 > V10 by odoo)

Impacted versions: V10

When i start my server, i've this traceback : 

> 
> File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
>     execute(self.server.app)
>   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
>     application_iter = app(environ, start_response)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/service/server.py", line 246, in app
>     return self.app(e, s)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/service/wsgi_server.py", line 184, in application
>     return application_unproxied(environ, start_response)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/service/wsgi_server.py", line 170, in application_unproxied
>     result = handler(environ, start_response)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/http.py", line 1306, in __call__
>     return self.dispatch(environ, start_response)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/http.py", line 1280, in __call__
>     return self.app(environ, start_wrapped)
>   File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
>     return self.app(environ, start_response)
>   File "/home/XXX/workspace/rh_XXXV10/odoo/http.py", line 1474, in dispatch
>     result = ir_http._dispatch()
>   File "/home/XXX/workspace/rh_XXXV10/odoo/addons/website_sale/models/ir_http.py", line 17, in _dispatch
>     return super(IrHttp, cls)._dispatch()
>  TypeError: unbound method _dispatch() must be called with ir.http instance as first argument (got nothing instead)

This error result to this function in odoo/addons.website_sale/models/ir_http.py

```
@classmethod
    def _dispatch(cls):
        affiliate_id = request.httprequest.args.get('affiliate_id')
        if affiliate_id:
            request.session['affiliate_id'] = int(affiliate_id)
        return super(IrHttp, cls)._dispatch()
```

call by this line : `result = ir_http._dispatch()` in odoo/http.py

When i print cls i have this : `<class 'odoo.api.ir.http'>`

Everybody have same problem ? How can i bypass this bug ?

**Comment by Yenthe666** [comment]
Hi @captivea-ylb,

Thanks for the report.
If you have these kind of issues after migrating a database with Odoo (with your enterprise license) you should respond on the migration itself.
The migration team will then check the issue and figure out how to fix it.

Regards,
Yenthe
