### ISSUE TITLE
Can not create graphically new user in V10

### ISSUE THREAD

**Issue by EBII** [odoo/odoo#14927]
Impacted versions: 10.0 community

Steps to reproduce: create user without image

Current behavior:
stack trace with : "cannot determine region size; use 4-item box"

image.paste(color) need one more arg..
like image.paste(color, mask=original)

Expected behavior:
new image profile for the new user 
https://github.com/odoo/odoo/blob/10.0/odoo/tools/image.py#L217

**Comment by Yenthe666** [comment]
Hi @EBII,

Thank you for your report!
I've just created a new user without image on the latest Odoo 10 without any problems:
![image](https://cloud.githubusercontent.com/assets/6352350/21676272/4f06a4c4-d335-11e6-8416-66cb8fc48526.png)
Could you try reproducing this on an official runbot or after updating your local Odoo to the latest Odoo codebase? You can find official test instances at runbot.odoo.com.

Regards,
Yenthe

**Comment by RafWolf** [comment]
Hi, I got the same problem and exactly the same stack trace message just after installing Oddo 10 in a Mac running El Captain.
I've installed Odoo using a buildout recipe (anybox.recipe.odoo).
Then I tried installing Odoo the "normal" way, but inside a python virtualenv and the problem seems to be solved. Now I can create a user without a photo/image. 
I'm a newbie in Odoo, as I actually work with firmware development, so I don't have much knowledge about the Odoo system structure, but I think the problem may be related to some library conflict/version.

**Comment by maljac** [comment]
I experience same problems in a fresh odoo 8.0 (20170102):

```
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/res/res_partner.py", line 325, in _get_default_image
    image = tools.image_colorize(image)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/image.py", line 186, in image_colorize
    image.paste(color)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1319, in paste
    "cannot determine region size; use 4-item box"
ParseError: "cannot determine region size; use 4-item box" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/auth_signup/auth_signup_data.xml:6, near
<record id="default_template_user" model="res.users">
            <field name="name">Template User</field>
            <field name="login">portaltemplate</field>
            <field name="active" eval="False"/>
            <!-- Avoid auto-including this user in any default group, just like a typical portal member -->
            <field name="groups_id" eval="[(6, 0,  [ref('base.group_portal')])]"/>
            <!-- allow signuped users to have a alias -->
            <field name="alias_name">_usertemplate</field>
        </record>
```

**Comment by maljac** [comment]
It seems that the version of `Pillow` was the cause: in the failing installation the Odoo debian package installed `Pillow==4.0.0`.

**Comment by Yenthe666** [comment]
Thank you for the update @maljac 
@sle-odoo might have to do with the LIB packaging. Something for you perhaps?

**Comment by Derter** [comment]
We are also facing the same issue on a CentOs

Odoo 10 Enterprise, installed yesterday.

![bildschirmfoto 2017-01-13 um 15 24 38](https://cloud.githubusercontent.com/assets/14194754/21933252/ec0078ac-d9a4-11e6-91e2-339652fbf46e.png)

**Comment by stijnh92** [comment]
error is caused by v4.0.0 of Pillow. uninstall it and install v3.4.2
pip install Pillow==3.4.2

**Comment by Yenthe666** [comment]
@sle-odoo

**Comment by mart-e** [comment]
Hello,

Indeed pillow 4.0 broke default avatar computation.
I have fixed it at 254afc6c9d4d8582df8248b6a3e51a3180f83f11 in 8.0. It will soon be ported to upper versions.
Thanks for the report

**Comment by JakubSs** [comment]
I had same issue today. Thanks

**Comment by carmenates09** [comment]
@stijnh92 Thanks, it worked for me, Im using Odoo v10 and I have pillow 4.0. 
I did it steps in my server with ubuntu:
1- `# pip uninstall pillow`
2- `# pip install Pillow==3.4.2`
3- `# pip install Pillow==3.4.2`
4- `# /etc/init.d/odoo restart`
