### ISSUE TITLE
[RFC][10] add deadline in each SO Lines

### ISSUE THREAD

**Issue by pasgou** [odoo/odoo#14921]
Impacted versions: 10, all

Steps to reproduce:
Have services with "create task and follow timesheet" enabled
Make SO with this services
Accept SO

Current behavior:
Task is created in SO analytic account or analytic account which is indicated in Service description
Deadline isn't indicate or it's the expected date of the all SO (if option is activated) and is the same for all tasks.

Expected behavior:
Two things are really missing in SO and Quotations:

- a start and end date and/or a deadline date on each line for services, information which could be used in task creation, or a delivery date for products
- a tool to create BOM for services (without MRP) that could be modified in SO or Quotations (quantities must be adapted for each client but the tasks could be the same or modified). In this configuration, lines of BOM should have to be visible for vendor but invisible (optionnaly) for client who only see the bom product. That could permit to create tasks with different deadlines date for each task in the BOM and give to client only what he want to know : the global service he buys, not the procedure. 

For example : your chartered accountant, you have to write accountancy each month so you have a BOM named "Accountancy" with 12 tasks, one per month, that you can invoice separately, but customer see in SO only that you write Accountancy for the year. In a such example, it would be simplier to write a deadline in SO for each line of BOM.

**Comment by pedrobaeza** [comment]
These are things IMO that should be implemented in community modules, not on the core, as it responds to custom user cases that are not standard one.

Closing as no real issue.
