### ISSUE TITLE
[9.0] Field property On Delete not set when setting Cascade

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#14936]
### Impacted versions:
9.0

### Steps to reproduce:
Go in:
Settings-->Technical-->User Interface-->Fields
Search for fields having "On Delete = Cascade"

### Current behavior:
None of the fields has Cascade set. CASCADE is set at database level, but not in the field properties in Odoo.

### Expected behavior:
A bunch of field should show up.

### Video/Screenshot link (optional):
![screen shot 01-04-17 at 05 39 pm](https://cloud.githubusercontent.com/assets/6699827/21661977/179549b8-d2a5-11e6-951a-eb2a0fd73e1c.PNG)

**Comment by pedrobaeza** [comment]
This has been reported also on #24464, and as it contains more conversation, I close this one in favor of the other.
