### ISSUE TITLE
[IMP] POS: UBER EATS

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#149326]
In Mexico, one of the most common business it's restaurants, during covid-19, a lot of it closed because the customer not go out of their houses, but other keep his business because delivery platforms like Uber eats.

The most common platform used in Mexico it's RESTAURANT SOFT, it have integrated Uber eats and other common delivery platforms in Mexico.

I try to implement odoo in restaurants but they don't wanna change because don't have this integration and install in an onpremise with custom modules are out of their budget.

**Comment by chapital** [comment]
#144976

**Comment by qle-odoo** [comment]
Odoo has chosen Urban Piper as its aggregator, which offers a suite of platforms that you want to use.

https://www.urbanpiper.com/
https://github.com/odoo/enterprise/pull/66733
