### ISSUE TITLE
[IMP] ecommerce: ElasticSearch or similar function

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#149327]
When I try odoo for first time compared to magento, everything feel faster, but only website search it's slower.

I test magento for 2 years with a database of 400k products.

Magento instance tested have elastic search enabled.

Implementing search engine like elastic search, odoo gonna feel much faster in the ecommerce.

Elastic search make a real time searching, odoo takes around 2-3 seconds to show results.

**Comment by zeroheure** [comment]
weanwhile you can add it yourself, using these Odoo Community Association modules
https://github.com/OCA/search-engine

**Comment by esakarya** [comment]
Odoo have to use complete elastic search for website_sale catalog and product detail. 
Currenly we have 3k product 50k variant. 
Product TTFB is 5 sec, categories TTFB is 8sec, amazing blazing slow.

**Comment by chapital** [comment]
Maybe in 19.0, odoo need to improve alot the eccomerce app, have disavantage compared to Spotify, magento, etc.

I close this ticket, but i have open tickets related With Ecomm:
-show Inter al referencial.
-brands
-PRICE list /comparation
-etc
