### ISSUE TITLE
Question: How does one contribute to this project?

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#14932]
I want to contribute to Odoo, but I certainly do not know on which tickets to work on. Are there some tickets of lower priority that we (independent contributors) can work upon? Is there going to be a cleanup of the ticket queue? Can we possibly work on issues tagged with the `wishlist` tag? Because all the confirmed tickets get immediately resolved.

Thanks for your time.

**Comment by Yenthe666** [comment]
Hi @daramousk,

Thanks a lot for your interest in contributing!
In theory you can work on any issue and create a PR for any of the issues to fix it. It is very important however to follow the guidelines that we've setup for contributing to Odoo (see https://github.com/odoo/odoo/wiki/Contributing).
The cleanup of the ticket queue is on a best effort basis. At this point there is nobody dedicated on the Github issue tracker and the people that work at Odoo try to handle issues when they have some spare time. I for example do not work at Odoo but try to keep track of the issue tracker and try to keep the amount as small as I can, just like you could. 😉 
If you should run stuck or if you're not sure you can ping me or @mart-e, we'll try to help you as much as we can.
Hope to see you contribute and again, thank you for the interest!

Regards,
Yenthe
