### ISSUE TITLE
[master/8.0] Localized application terms not displayed in module 'account' (invoice)

### ISSUE THREAD

**Issue by chrisludwig** [odoo/odoo#1495]
I solved my problem with untranslated invoices described here: https://www.odoo.com/forum/help-1/question/localized-terms-not-displayed-in-accounting-module-58889

However, the issue still remains I don't get a localized form when working with invoices (incoming/outgoing) at the backend. No big deal for me and I expect it's not a general issue as more users would have complained otherwise, but still I'm confused why only part of the module is always displayed in English (also tried French, Spanish, ...).

Here is how it looks like with an installation of odoo from GitHub ('8.0' and 'master') on a fresh Ubuntu 12.04 server.

![locale](https://cloud.githubusercontent.com/assets/8324562/3773007/29a2fb96-1907-11e4-959f-d9d7e21a7aae.PNG)

Only created a new database (default language English and German tested) and installed the module 'account' (also tried 'account_voucher' instead). After installing the German language and switching the admins' language to German (same if creating a new user instead) I logged out and in again. Unfortunately I have not been able to find a solution to this issue no matter how often I re-installed the language or synced the application terms. The exported .po file for the German language seems fine to me and contains the translated values for the terms in question, so apparently they just don't get fetched on page load?!
- Chris

**Comment by Yenthe666** [comment]
Hi @chrisludwig ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
