### ISSUE TITLE
Missing python 3.11 opcodes in safe_eval.py

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#149524]
Impacted versions: 16.0

Steps to reproduce: 

This came up from Odoo support working on OPW 3646533, presumably when creating server actions:
forbidden opcode(s) in 'lambda': POP_JUMP_FORWARD_IF_NOT_NONE, POP_JUMP_FORWARD_IF_NONE

Expected behavior:

It seems https://github.com/odoo/odoo/pull/136943 did not land on 16.0 ?

Support ticket number submitted via odoo.com/help (optional):

**Comment by flotho** [comment]
experiencing the same issue on v16 while loading addons/stock/data/stock_data.xml:16 which looks like what you described : https://github.com/odoo/odoo/blob/16.0/addons/stock/data/stock_data.xml#L18C46-L18C69

**Comment by BT-nfrancisco** [comment]
> experiencing the same issue on v16 while loading addons/stock/data/stock_data.xml:16 which looks like what you described : https://github.com/odoo/odoo/blob/16.0/addons/stock/data/stock_data.xml#L18C46-L18C69

Same here!

**Comment by joshkreud** [comment]
Since #156438 seems to work, a quick oneliner to Apply it locally: 

`curl -sSL https://github.com/odoo/odoo/commit/ba7b449a09b1643218c85e5b4913b2bfc425cb74.patch | git apply` 

Just execute in the local Odoo repo or add `-C <path_to_repo>` to `git apply`

**Comment by sconetto** [comment]
> Since #156438 seems to work, a quick oneliner to Apply it locally:
> 
> `curl -sSL https://github.com/odoo/odoo/commit/ba7b449a09b1643218c85e5b4913b2bfc425cb74.patch | git apply`
> 
> Just execute in the local Odoo repo or add `-C <path_to_repo>` to `git apply`

This one fix worked for me 😄

**Comment by BT-anieto** [comment]
Why are all PR closed?

**Comment by hugosantosred** [comment]
> Why are all PR closed?

They are merged already in [16.0](https://github.com/odoo/odoo/commit/22ad0a386a7d8d88ce3569e91d5a5c3e7fff71ba) and saas-16.1
