### ISSUE TITLE
[8.0]Calendar filter drop down button misalign

### ISSUE THREAD

**Issue by youring** [odoo/odoo#1496]
**_Impacted versions:**_

only tested on v8.0 latest 
runbot f643660

**_Steps to reproduce:**_

Messaging - Organizer - Calendar
Drop down button in the upper right corner of the mini calendar/ date picker

**_Current behavior:**_

![drpd-btn](https://cloud.githubusercontent.com/assets/4132418/3774434/ec007f60-192a-11e4-8099-b5ce81248c29.png)

**_Expected behavior:**_
The drop down button should be on filter box

**Comment by Yenthe666** [comment]
Hi @youring,

Thank you for your report.
This has been fixed quite a while ago though! It now looks like this:
![image](https://user-images.githubusercontent.com/6352350/27577261-4d76ea10-5b20-11e7-829b-a4d011165c8b.png)
I'm closing this report as it has been fixed already.

Regards,
Yenthe
