### ISSUE TITLE
[7.0] entry_ids added in account_move_line is never used and gives performance issue

### ISSUE THREAD

**Issue by joeribelis** [odoo/odoo#14969]
Impacted versions: 7.0

Steps to reproduce: copy or read account_move_line and you will see a query that does a full table scan

Current behavior:

Expected behavior: 

Video/Screenshot link (optional):

I can't find any reason why the field is added to account_move_line

class account_move_line(osv.osv):
    _inherit = 'account.move.line'
    _columns = {
        'asset_id': fields.many2one('account.asset.asset', 'Asset', ondelete="restrict"),
        'entry_ids': fields.one2many('account.move.line', 'asset_id', 'Entries', readonly=True, states={'draft':[('readonly',False)]}),

    }
account_move_line()

Can this be savely be removed

**Comment by Yenthe666** [comment]
Hi @joeribelis,

Thank you for your bug report.
At this point however Odoo 7 is no longer supported as Odoo only supports three versions (8.0, 9.0, 10.0).
You can ask help on the official Odoo help forums though (see help.odoo.com).

Regards,
Yenthe
