### ISSUE TITLE
[master] City field show twice in Sales >> customers  form view

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#14960]
Impacted versions:
master

Steps to reproduce:
1. Open a master branch on http://runbot.odoo.com (enterprise or community)
2. Go to Sale >> Customers
3. Open a Customer

Current behavior:
The field 'city' is duplicated in form view

Expected behavior:
The field 'city' should be show one time

Video/Screenshot link (optional):

![captura de pantalla de 2017-01-05 12-29-52](https://cloud.githubusercontent.com/assets/5335402/21692762/f83df070-d343-11e6-85fe-7a9f66245a17.png)

![captura de pantalla de 2017-01-05 12-30-15](https://cloud.githubusercontent.com/assets/5335402/21692763/f8417ede-d343-11e6-85b0-ee1bef8923e5.png)

Possible fix:
Remove this line?
https://github.com/odoo/odoo/blob/master/addons/base_address_extended/views/base_address_extended.xml#L24

**Comment by nhomar** [comment]
Hello @Yenthe666 

This work is part of the localization part (which include what you called "experiment" ;-)).

As you can see it was included in saas-14 also, and is part of the revisions we are doing for the next localized saas.

@qdp-odoo Your feedback is welcome here.

Do you prefer a PR?¿
