### ISSUE TITLE
Recursive Validation on constraints during import/loading

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#14961]
#### Impacted versions:
9.0, not tested on 10. but a look on the code suggests this is persistent.

#### Steps to reproduce:

- Have a model which satisfies the following constraint check
- Load some data for, see example below

```python
@api.constrains('code', 'validity_from', 'validity_until')
def _check_value(self):
    for val in self:
        # Breakpoint set here for the analysis below
        if self.search([
            ('code', '=', val.code),
            ('validity_until', '>=', val.validity_from),
            ('validity_from', '<=', val.validity_until)
        ]):
            raise "Ughs"
```
```
<record id="test_me" model="your.model">
        <field name="code">CODE</field>
        <field name="validity_from">2016-01-01</field>
        <field name="validity_until">2016-12-31</field>
</record>
```

#### Current behavior:

- At loading `self` is a recordset of len 1
- At the breakpoint:
-- `self.search(...)` returns the just about to be loaded record, hence it raises.
-- `self.env.cr.execute('SELECT * FROM your_model')`
-- `self.env.cr.fetchall()` suggests that the value is already in your transaction.
- Having a look at the code confirms that validation (https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L3968) is done after database interaction (https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L3895).
- This renders a constraint of this type impossible, as long as I didn't oversee how to do it via sql constraints, but searching up and down the net, does not yield anything useful for the validity range problem. Or I'm just stupid, can be also true.

#### Expected behavior:
- Import runs smoothly, same for subsequent updates (where the case is probably even a bit more tricky)

---------------------------------

EDIT2: This paragraph was bluntly wrong. The error also occurs on normal validation through the client. It seems that this kind of validation is generally not supported. Remains the problem of checking validity ranges on create/upload.

EDIT: I have a reference field (`fields.Reference()`) in use, maybe this is not compatible as barely used?

**Comment by blaggacao** [comment]
OK, including `('id', '!=', val.id),` did the trick, but this is so awkward it cost me half a day to figure out. If there can be done something about it at acceptable risk, it should be done so.

**Comment by pedrobaeza** [comment]
Closing as no real issue, but something about how to put the constraint itself.
