### ISSUE TITLE
 Is there any sticky header module for odoo7??? 

### ISSUE THREAD

**Issue by anandgodavarma** [odoo/odoo#14964]
Impacted versions:7

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I am using odoo7. While scrolling a tree view down, the header is not visible till the end. I got a module web_list_view_sticky foe odoo8. Is there any sticky header module for odoo7???

**Comment by Yenthe666** [comment]
Hi @anandgodavarma,

Thank you for your report but this is not an issue nor is it a bug.
The Github issue tracker is only for bugs and/or issues in the official Odoo code.
Please ask this question on the official help forum (help.odoo.com) where plenty of people can help you!

Regards,
Yenthe
