### ISSUE TITLE
NEW API: Call to `sudo` in onchange reset in memory record

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#14970]
## Impacted versions:
8.0 9.0 10.0
## Steps to reproduce:
In an Odoo shell:

```python
>>> demo_user = self.browse(2)
>>> inv = demo_user.env['account.invoice.line'].new({'name': 'line name'})
>>> inv.name
u'line name'
>>> # in a shell the environment already exists for sudo ...
>>> inv.sudo().name
u'line name'
>>> # in an onchange no environment exists for sudo
>>> # reset env to be in the same context as in an onchange
>>> demo_user.env.reset()
>>> inv.name
u'line name'
>>> inv.sudo().name
False
```

## Current behavior:
Attributes of an in memory record are emptied after a call to `sudo`

## Expected behavior:
Attributes of an in memory record are preserved after a call to `sudo`

This bug has been difficult to isolate but this case always occurs if you call sudo() in an onchange method called by the UI on a new record. For example if an onchange method is declared on `purchase.order.line` and in this onchange method you must do some process on the new record as sudo `self.sudo().do_xyz` or call super with sudo to bypass some RR/ACL  self is empty in the called method. Indeed:
* the method `sudo` call `self.with_env`. https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L4842 
* And the error occurs since a new env is created because no env exists with the same parameters....
https://github.com/odoo/odoo/blob/10.0/odoo/api.py#L725
https://github.com/odoo/odoo/blob/10.0/odoo/api.py#L731

OPW703904

**Comment by lmignon** [comment]
@rco-odoo A new one for you....

**Comment by pedrobaeza** [comment]
Maybe this explanation is related: https://github.com/odoo/odoo/issues/6276#issuecomment-93304343

**Comment by lmignon** [comment]
@pedrobaeza The problem here is that we are on an in memory record created by `onchange`and the context contains a lot of value from the UI. Therefore if you call self.sudo() Odoo will create a new env but it's not what we want, we just want to apply some logic as sudo... This bug is annoying in a lot of cases and  prevent the use of sudo/suspend_security in onchange....

**Comment by lmignon** [comment]
I close the issue since it seems a little bit more complex that the current explanation...

**Comment by lmignon** [comment]
I reopen the issue since the issue is now properly explained...

**Comment by rco-odoo** [comment]
If you want to invoke a method on a new record as sudo(), you should (1) copy the data from record's cache to record.sudo()'s cache; (2) invoke the method; (3) possibly copy back data from record.sudo()'s cache to record's cache. Something like:
```python
record_sudo = record.sudo()
# step (1) - note that this does not copy records accessible through relational fields
for key, val in record._cache.iteritems():
    record_sudo[key] = val
# step (2)
record_sudo.method()
# step (3) is the same as step(1), except that record and record_sudo are permuted
```

**Comment by lmignon** [comment]
Thank you @rco-odoo for the provided solution. It works fine!

**Comment by blaggacao** [comment]
Sorry it is not directly related, but out of all the other stuf, probably my question best fits in this thread:

I'm observing that in an onchange call `sudo()` does not seem to work:
the method:
```python
def _compute_related(self, records):
        """ Compute the related field ``self`` on ``records``. """
        others = records.sudo() if self.related_sudo else records
        if records.env != others.env:
            copy_cache(records - records.filtered('id'), others.env)
        values = list(others)
        for name in self.related[:-1]:
            values = [first(value[name]) for value in values]
        for record, value in zip(records, values):
            record[self.name] = value[self.related_field.name]
```
the environment:
```python
self = account.move.line.accounting_company_id
self.related_sudo = True
self.related_field.name = res.company.accounting_company_id
```
`value[self.related_field.name]` returns an access error but there should be no reason for it.
Yes, `res.company.accounting_company_id` is ultimately a parent company which the current user has not access to, but isn't that what sudo is for?

I need a helping hand, I guess...

**Comment by blaggacao** [comment]
@rco-odoo Damn it, what should we do? Enforce strictly sequencial onchange calls in the web client??? Make the onchange logic itself threadsafe (as to cache)??? Its a bit brainf*** but I see some light, could you chime in?
