### ISSUE TITLE
Server internal error when sharing project with portal users

### ISSUE THREAD

**Issue by SonoDavid** [odoo/odoo#149773]
Impacted versions: from 17.0

Related to: [Server Internal error](https://github.com/odoo/odoo/issues/142372)

Steps to reproduce:

1. Disable the module 'partner_autocomplete'
2. Create a test project in the projects app and share it with a portal user
3. Log in as the portal user with the shared project
4. Go to 'projects'
5. Open the project

Current behavior:
Results in an 'internal server error'

Expected behavior:
It should be possible to uninstall the module partner_autocomplete and get no errors since this is not a direct dependency of the module 'project'

Suggestion:

Remove these dependencies from project module:
```
            'partner_autocomplete/static/src/js/partner_autocomplete_core.js',
            'partner_autocomplete/static/src/js/partner_autocomplete_many2one.js',
            'partner_autocomplete/static/src/xml/partner_autocomplete.xml',
```

Video/Screenshot link (optional):
![Peek 2024-01-17 14-57](https://github.com/odoo/odoo/assets/4289743/a14578ae-7bbc-45b1-ad32-d8e1ac61992a)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Nerevar-de** [comment]
Can confirm current behaviour on my local instance.
Also not using partner_autocompletly (which results in auto uninstall of module).

**Comment by jjoe64** [comment]
we have the same issue on odoo Enterprise project hosed on Odoo.sh

**Comment by vava-odoo** [comment]
Thanks @SonoDavid for reporting. This was fixed with https://github.com/odoo/odoo/commit/ba649fbc9c12eaa247979f8dcb4147e3c5257dea
