### ISSUE TITLE
[10.0] lt translation message_ids is not representing in view

### ISSUE THREAD

**Issue by varzgalys** [odoo/odoo#14987]
Impacted versions:
10.0
Steps to reproduce:
Try to translate into Lithuanian language message_ids field (Log An Internal Note, New Message) at the bottom of most forms (for example: partner, task.
Current behavior:
Loads to system, shows in translations, but not representing i view (only shows in English)
Video/Screenshot link (optional):
![selection_009](https://cloud.githubusercontent.com/assets/18685810/21759944/04207f88-d651-11e6-8569-d25484090306.png)
![selection_010](https://cloud.githubusercontent.com/assets/18685810/21759945/04265e1c-d651-11e6-9854-e22e14b01526.png)

**Comment by Yenthe666** [comment]
Hi @varzgalys,

Thank you for your report.
This actually does work (partially) as you can here:
![image](https://user-images.githubusercontent.com/6352350/34877714-7abbca76-f7a7-11e7-8beb-00154fc84956.png)
The other source term (Log an internal note) doesn't seem to show up though. @mart-e could you have a look? Filtering on the runbot:
![image](https://user-images.githubusercontent.com/6352350/34877801-d605cbc0-f7a7-11e7-9b6b-166cc86d5084.png)


Regards,
Yenthe

**Comment by mart-e** [comment]
Hmm no it is translated.
![screenshot-2018-1-12 agrolait - odoo](https://user-images.githubusercontent.com/564822/34878403-5bbec094-f7aa-11e7-9d6d-2378f9781391.png)

I guess, at that time the translations were not reloaded but no longer the case

![screenshot-2018-1-12 vertaalde uitdrukkingen - odoo](https://user-images.githubusercontent.com/564822/34878469-912431ec-f7aa-11e7-8919-10f02bbd8dbe.png)

**Comment by Yenthe666** [comment]
@mart-e yes it works fine in Dutch etc. I totally forgot that if it is not translated that you would need to add the term manually or translate it on Transifex.
So, yes, fully handled.
