### ISSUE TITLE
Improve request: Leaves per hour

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#14985]
Impacted versions: All
Improvement request for V11. Be able to do the leave request per hour. The request per day is undo-able. At least in the Netherlands. We have employees who are working part-time and all have a different amount of leaves. When 1 hour leave for a 8 day job, the leave request is now 0,125. For a 6 hour job it is 0,166.

It just don't make sense for employees. Leave request per hour would be much more easy.

Hope this request can be done for Odoo V11.

**Comment by njeudy** [comment]
👍 for this request

**Comment by ploegvde** [comment]
Hi, you can contact me, i think i have a mole somewhere that you can use. erwin@odooexperts.nl

**Comment by Yenthe666** [comment]
@mart-e nevertheless we should totally look at this for the upcoming V12.

**Comment by pedrobaeza** [comment]
I personally don't see this interesting, and more with latest improvements that computes automatically this interval (plus not letting user to modify the leave time), but see https://github.com/OCA/hr/pull/350 for this feature.

My rationale here is that in Spain we are also requesting some leave hours, but the employee request from hour X to hour Y. If there are 3 hours, 5:30 or 1 it's not the most needed data. Well, you can put the equivalent according working calendar as reference, but computation should be still done in fraction of days for knowing how many days you rest for the holiday type.

**Comment by ploegvde** [comment]
In the Netherlands you basically get leave per hour. The amount is based on the time you work in a month. So every employee can have different time. In days it is to hard to get it right. 1h = 0,125 days, for someone who works 8hr a day. For someone who works 7hr a day, a 1hr leave = 0.142. Not very employee friendly.

**Comment by pedrobaeza** [comment]
But again, employee don't need to know that data (or should know it). They are requesting a leave from hour X to hour Y.

**Comment by ploegvde** [comment]
But a leave from the same day from 8:00 until 10:00 is for Odoo 1 day and that is not correct. It is 2hr.

**Comment by TimvM** [comment]
In Odoo 11 it does calculate but only in quarters.
So leave from 8:00-9:00 calculates 0,25 day, but
8:00-10:00 calculates 0,25 day too. (based on 8 hour working day)

1 hour should be 0,125 in this case.

**Comment by pedrobaeza** [comment]
Check them my improvement for an OCA v10 module that is being migrated to v11 that computes exactly the amount: https://github.com/OCA/hr/pull/420

**Comment by ploegvde** [comment]
Ok, i checkt in V10. But also a quarter day is incorrect. 1h is 1h and i the Netherlands people are very precise in that.

**Comment by ploegvde** [comment]
Ok, maybe Odoo can include it in V12.

**Comment by TimvM** [comment]
@pedrobaeza when do you expect those improvements will be released for Odoo v11?

**Comment by pedrobaeza** [comment]
There's a WIP in https://github.com/OCA/hr/pull/401, but this is not in my hands.

**Comment by TimvM** [comment]
Same issue applies to "leaves allocation". 
If an employee worked overtime for 1 hour, he should apply 1 hour. Not 0,25 day.

Please consider do this the same way.

**Comment by astirpe** [comment]
Maybe I'm too late: https://github.com/OCA/hr/pull/350

**Comment by feketemihai** [comment]
@TimvM @ploegvde @njeudy @astirpe @pedrobaeza Can you check and review [OCA/hr#401](https://github.com/OCA/hr/pull/401) with the latest updates, added the number of hours just like days, (probably a rounding method to hours should be implemented, not yet).

**Comment by TimvM** [comment]
How can I get/install this module on my Odoo v11 server?

**Comment by mart-e** [comment]
By the way, we are working to refactor the leave management in v12. I have reported the feedback and hopefully, it will be possible.

**Comment by ploegvde** [comment]
It is possible in v12. Case closed.
