### ISSUE TITLE
[10.0] Impossible to change some field values in duplicated MO

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#14983]
## Impacted versions:
10.0

## Steps to reproduce:
Duplicate an existing MO

## Current behavior:
It is not possible to change some field values such as product and BOM

## Expected behavior:
It should be possible to change these above mentioned field values.  Duplicate function cannot be used when want to change the BOM (there are cases where there is more than one BOM for a product).

## Additional info:
MO is currently designed to generate moves upon creation, which prevents changes to above mentioned fields with `attrs="{'readonly': [('has_moves', '=', True)]}"`.

This appears to me a design flaw.  Following changes may be needed to fix the problem:
- revive `draft` state in MO (in 10.0 MO starts with `confirmed` state, which I think is a bit strange)
- generate moves when MO is "confirmed" (not when MO is created).

## Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/7766939/21748539/6da408d8-d5c2-11e6-9ce2-d27fa7140ffe.png)

**Comment by jco-odoo** [comment]
The removal of the draft state was done on purpose to make it simpler.  There seems little difference between creating a new one and duplicating in terms of re-entering the fields.

**Comment by yostashiro** [comment]
> There seems little difference between creating a new one and duplicating in terms of re-entering the fields.

@jco-odoo , I wasn't sure what you meant by this.

> The removal of the draft state was done on purpose to make it simpler.

I can imagine how the design decision was made but I don't think there has been much gain for this design change compared to the loss of flexibility.

**Comment by pedrobaeza** [comment]
I don't see any advantage in duplicating an MO, as now everything is computed from BoM, so there's no sense for that option you ask for. An interesting thing would be to allow to add components manually, and then the duplicate record option would be again interesting, but it's not the case. Closing then.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
