### ISSUE TITLE
[9.0] [10.0] Field date_approve not set on purchase.order when approve purchase

### ISSUE THREAD

**Issue by tj612** [odoo/odoo#14988]
**Impacted versions:** 
9, 10

**Steps to reproduce:**

- Setup two levels of approbation on Purchases -> Settings.
- Create a purchase order with an amount superior of the validation amount.
- Confirm the purchase order.
- Approve the purchase order

**Current behavior:**
The field date_approve is not set.

**Expected behavior:**
The field date_approve should be set at the today date.

If multiple users validate the expected behavior, I'll make a pull request implementing it.

**Comment by lap-odoo** [comment]
@tj612 : The field you are referring to is an old field that is not used anymore, it should not be displayed and will be fixed in the next versions of Odoo. Thanks for reporting this.
