### ISSUE TITLE
Aged Payable report does not reflect payments made with a credit card.

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#14997]
Impacted versions: 9.0e

Steps to reproduce: Record payment with credit card and view aged payable report

Current behavior: Balance still shows in the report

Expected behavior:  Payment should not show on aged payables report

Video/Screenshot link (optional): https://www.youtube.com/watch?v=Hm6rO1TMIu8

**Comment by Yenthe666** [comment]
@qdp-odoo could you give feedback on this?

**Comment by qdp-odoo** [comment]
I don't think it is related to the "credit card" payment method... but most likely because the aged payable report does not include 'unposted entries', which is what your payment is....

**Comment by elevationO** [comment]
One of the payments shown in the screenshot says "reconciled".  Is this the same as posted?
![screen shot 2017-01-18 at 11 24 42 am](https://cloud.githubusercontent.com/assets/8355352/22079538/1d0f32ec-dd71-11e6-9956-7967c86403f0.png)

**Comment by qdp-odoo** [comment]
no, 'posted' means that the journal entry received a number and cannot be modified anymore. 

In your screenshot, it is the case: your journal entry is posted and has the number BNK2/2016/0002. But in your video, the payment you're showing is not posted. You have a button to manually do it (by default, all journal entries created by the system are posted automatically at creation, only the manual ones have to be posted manually)

I hope this helps
