### ISSUE TITLE
[8.0] inherited onchange_partner_id isn't called when partner_id is not True

### ISSUE THREAD

**Issue by dskarataev** [odoo/odoo#1499]
Hello, I inherit onchange_partner_id function in sale.order:

``` python
def onchange_partner_id(self, cr, uid, ids, partner_id, context=None):
        result = super(sale_order, self).onchange_partner_id(cr, uid, ids, partner_id, context=context)
        if partner_id:
            partner = self.pool.get('res.partner').browse(cr, uid, partner_id, context=context)
            result['value']['company_bank'] = partner.company_bank.id if partner and partner.company_bank else False
        else:
            result['value']['company_bank'] = False
        return result
```

It works ok when partner_id is equal to True. BUT where I clean the partner_id field on the form, this metod even isn't called at all. Only original (not inherited) method called but  my method that inherits original one isn't called. I check it in debugger, breakpoint doesn't work in case of clearance the partner_id field.

**Comment by Yenthe666** [comment]
Hi @dskarataev,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
