### ISSUE TITLE
[master][9.0][10.0] account type for some account template of china is wrong.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#14999]
Impacted versions:
9.0, 10.0, master 

Steps to reproduce:
like  `1401 材料采购` is on the side of  `assets`,  but this is the wrong type as `expense`  in both l10n_cn_standard and l10n_cn_small_business.

Current behavior:
wrong account type

Expected behavior:
need to correct all the wrong account type/

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
@GoodERPJeff      what do you think about this issue.

**Comment by jeffery9** [comment]
should change data from XML format to CSV.

**Comment by yueqin** [comment]
I think so, 1401材料采购 is on the type of current asset.
