### ISSUE TITLE
how can i let a salesperson see all the leads he/she folllows?

### ISSUE THREAD

**Issue by Priyanshi1010** [odoo/odoo#14990]
Impacted versions:9.0

Steps to reproduce:domain rule for see own leads

Current behavior: only leads assigned or created by a user can be seen under "see own leads" option

Expected behavior:i want salesperson to even see the leads he/she follows.

Video/Screenshot link (optional):

**Comment by dvdhinesh** [comment]
@Priyanshi1010 This is not an issue, but a functional change. I suggest you ask these type of questions on https://www.odoo.com/forum/help-1 or the community mailing list https://www.odoo.com/groups

**Comment by Priyanshi1010** [comment]
ya i know, but still if anyone can help.

**Comment by Yenthe666** [comment]
Hi @Priyanshi1010,

As stated by @dvdhinesh this is not a bug or issue, it is a function question.
We'd like to keep Github issues only for bugs in the official code and nothing else. Please ask this question on the official help forums 😉 

Regards,
Yenthe
