### ISSUE TITLE
Nginx SSL proxy causes chat not to work due to 502

### ISSUE THREAD

**Issue by chrissound** [odoo/odoo#15007]
Impacted versions: 10

Hello, I'm trying to setup Odoo in docker with a nginx SSL proxy infront.

I've enabled proxy mode and set the necessary nginx config:
```
#odoo server
upstream odooproxy {
 server odoo:8069;
}
upstream odoochatproxy {
 server odoo:8072;
}

# http -> https
server {
   listen 80;
   server_name _;
   rewrite ^(.*) https://$host$1 permanent;
}

server {
 listen 443;
 server_name _;
 proxy_read_timeout 720s;
 proxy_connect_timeout 720s;
 proxy_send_timeout 720s;

 # Add Headers for odoo proxy mode
 proxy_set_header X-Forwarded-Host $host;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-Real-IP $remote_addr;

 # SSL parameters
 ssl on;
 ssl_certificate /etc/ssl/nginx/ssl.public.pem;
 ssl_certificate_key /etc/ssl/nginx/ssl.private.pem;
 ssl_session_timeout 30m;
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
 ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
 ssl_prefer_server_ciphers on;

# log
 access_log /dev/stdout;
 error_log stderr;

 # Redirect requests to odoo backend server
 location / {
   proxy_redirect off;
   proxy_pass http://odooproxy;
 }
 location /longpolling {
     proxy_pass http://odoochatproxy;
 }

 # common gzip
 gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
 gzip on;
}
```

I'm having issues with the chat, the request to `/longpolling/poll` returns a 502 response.

I get the following in nginx
```
nginx_1  | 2017/01/10 13:29:06 [error] 7#7: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://172.20.0.4:8072/longpolling/poll", host: "odoo.mycompany.com", referrer: "https://odoo.mycompany.com/web"
nginx_1  | 172.20.0.1 - - [10/Jan/2017:13:29:06 +0000] "POST /longpolling/poll HTTP/1.1" 502 575 "https://odoo.mycompany.com/web" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
```

----

It works correctly if I do not access it from the Nginx proxy, so essentially on the 8069 port.

**Comment by chrissound** [comment]
Add I've fixed it by adding `workers = 1` to my odoo config `/etc/odoo/odoo.config`. 

I'm not sure why it works fine without the proxy though? Is this information that should be added in the documintation? https://www.odoo.com/documentation/10.0/setup/deploy.html#https?

**Comment by AyaYousef** [comment]
I had the same issue, I solved it by adding `workers = 1` too. As in my case I have only 1 CPU according to Oddo official docs https://www.odoo.com/documentation/10.0/setup/deploy.html#https

> Odoo includes built-in HTTP servers, using either multithreading or multiprocessing.
> 
> For production use, it is recommended to use the multiprocessing server as it increases stability, makes somewhat better use of computing resources and can be better monitored and resource-restricted.
> 
> Multiprocessing is enabled by configuring a non-zero number of worker processes, the number of workers should be based on the number of cores in the machine (possibly with some room for cron workers depending on how much cron work is predicted)
> Worker limits can be configured based on the hardware configuration to avoid resources exhaustion
