### ISSUE TITLE
Odoo still uses SHA1 on the gpg key?

### ISSUE THREAD

**Issue by rafi16jan** [odoo/odoo#15002]
Impacted versions: All (I think)

Steps to reproduce: Install Odoo from the deb repositories on Ubuntu

Current behavior: APT refuse to use repositories with SHA1 unless --allow-unauthenticated flag is used

Expected behavior: Use SHA256 or something

Video/Screenshot link (optional):

**Comment by rafi16jan** [comment]
@Yenthe666 @JKE-be @nle-odoo can you guys commit about this? This is a repository problem though

**Comment by odony** [comment]
@rafi16jan It should be fixed now, could you test again?

**Comment by rafi16jan** [comment]
Yes its fixed now
