### ISSUE TITLE
[v9][v10][Account] Invoice Payment Difference mix up debit and credit

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#15000]
Impacted versions:
9, 10

Steps to reproduce:
1. Find a v9 or v10 runbot on runbot.odoo.com and login
2. Go to Accounting->Vendor Bills
3. Create a vendor bill, amount $10, Validate, like this
![image](https://cloud.githubusercontent.com/assets/8391358/21797733/cb955e76-d74b-11e6-80de-7484cb10eb50.png)
4. Register payment, assume that there is bank fee of $1. That means we pay total $11 and want to fully reconcile the invoice.
![image](https://cloud.githubusercontent.com/assets/8391358/21797797/114672c0-d74c-11e6-931d-5e05a69e0dc3.png)
5. Go to Accounting->Advisor->Journal Entries to check the newly created entry
![image](https://cloud.githubusercontent.com/assets/8391358/21797849/6acabb80-d74c-11e6-8c4d-03edd194e193.png)

Current behavior:
1. (Correct) Odoo credit Bank $11
2. (Wrong) Odoo debit AP $12
3. (Wrong) Odoo credit Bank Fees $1
4. In this case, bank fee expense is wrongly booked as income.

Expected behavior:
1. Odoo credit Bank $11
2. Odoo debit AP $10
3. Odoo debit Bank Fees $1

**Comment by auyeung112002** [comment]
Commit related this issue: https://github.com/odoo/odoo/commit/20935462a0cabeb45480ce70114ff2f4e91eaf79

**Comment by beledouxdenis** [comment]
Hi @auyeung112002 

Thank you very much for the report.

As Github probably notified you, we just solved this issue in Odoo 9.0 from the below revision:
https://github.com/odoo/odoo/commit/fc813847d8cf3242a0202cff813c3466cd0a5e1f

and in Odoo 10.0 from the below revision:
https://github.com/odoo/odoo/commit/909ce5175f2816ec732b1205fecf03c29dbed3d2

We sincerely apologize. Such an issue should not occur in stable releases such as Odoo 9.0 and 10.0. We will write tests so this can no longer happen.

Again, thank you for your report

**Comment by auyeung112002** [comment]
Thank you very much for the quick fix!
