### ISSUE TITLE
[10.0] MOs are shown on all production kanbans

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#15008]
Impacted versions: Odoo 10

Steps to reproduce: Create two warehouses. There will be two manufacturing kanbans for each WH on the Dashboard. Create MO on any WH. That MO will be shown on both kanbans.

Current behavior: Manufacturing orders related to specific warehouse are shown on all manufacturing kanbans (dashboard).

Expected behavior: MOs are shown on manufacturing kanban of related warehouse.

Video/Screenshot link (optional):
All manufacturings were on YourCompany WH only
![2wh-manufacture](https://cloud.githubusercontent.com/assets/5942291/21810815/fc245ee8-d755-11e6-8934-d96316877a54.png)

**Comment by jco-odoo** [comment]
Indeed, forgot to filter on the picking type itself.
