### ISSUE TITLE
[8.0] pack_operations in wizard get multiplied on raised error

### ISSUE THREAD

**Issue by engelant** [odoo/odoo#15015]
Steps to reproduce:
If there is reserved and availible move for a product with full lot tracability, the transfer wizzard appears. There you can add a product to the wizard. Important thing is that the first product with full lot tracebility does get the lot removed in the wizard. This will rises an error trying to transfer. You raise the error a few times and after that you put in a lot in the first articel.

Current behavior:
The transfer will succeed, but the qty of the product added in the wizzard will get multiplied by the times the exception raised.

Expected behavior:
Only ammounts that are entered into the wizard should get transferred.

The cause for this seems to be a write call from the wizard, without returning the ID of the created pack_operation to the wizard. So next time instead of updating the qty a new pack_operation is created.

**Comment by Yenthe666** [comment]
Hi @engelant,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
