### ISSUE TITLE
Bug: typo in context parameter in addons/product/models/product.py, line 551

### ISSUE THREAD

**Issue by JosefKaser** [odoo/odoo#15028]
Impacted versions:
10.0

Steps to reproduce:
see line 551 in addons/product/models/product.py

Current behavior:
the line is
`'company_id': self._context.get('force_compay', self.env.user.company_id.id),`

Expected behavior:
the line should be
`'company_id': self._context.get('force_company', self.env.user.company_id.id),`

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @JosefKaser,

Thank you for your report.
This is indeed invalid, I made a PR for it here: https://github.com/odoo/odoo/pull/15033

Regards,
Yenthe
