### ISSUE TITLE
Duplicate Error report_saleorder_document when language on

### ISSUE THREAD

**Issue by saitam1** [odoo/odoo#15039]
Impacted versions: 10

**Steps to reproduce:** 
Go to: 
`settings / reports / reports / sale.order / view as QWeb / sale_order_document `

Then click `action` and `duplicate`

**Current behavior:**
It shows me an error and tells me, that it is not possible to duplicate the file. If I deactivate German as language duplication works fine

**Expected behavior:**
It should duplicate the file

Video/Screenshot link (optional):

**Comment by daramousk** [comment]
I can confirm this, attaching a screenshot for reference.

The exception occurs in `odoo/addons/base/ir/ir_translation.py` on `_check_value` method 

                    `if value2 != value0:
                        raise ValidationError(_("Translation is not valid:\n%s") % trans.value)`

![screen shot 2017-01-22 at 21 40 53](https://cloud.githubusercontent.com/assets/3503159/22185298/a842f510-e0eb-11e6-847b-e6e6f017e61e.png)

**Comment by Yenthe666** [comment]
@mart-e looks like one for you 😉

**Comment by Yenthe666** [comment]
@mart-e second ping (sorry)

**Comment by Yenthe666** [comment]
This was fixed at https://github.com/odoo/odoo/commit/457b2725feecd7d2b50084bf4a14527762c919be
