### ISSUE TITLE
[9][10][Account] Can create/duplicate entry before Account Lock Date

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#15034]
Impacted versions:
9,10

Steps to reproduce:
1. Login to v9 or v10 runbot

2. Set the Lock Date to 2016-12-31
![image](https://cloud.githubusercontent.com/assets/8391358/21881035/0f7a6554-d8dd-11e6-8d65-911078af8215.png)

3. Create entry dated before lock date.
![image](https://cloud.githubusercontent.com/assets/8391358/21881090/51720606-d8dd-11e6-8283-f09299f222ac.png)

4. The entry is created with no problem
![image](https://cloud.githubusercontent.com/assets/8391358/21881152/aa5b9fd4-d8dd-11e6-9b50-44388f30f51a.png)

5. Duplicate the newly created entry

Current behavior:
The journal entry can be created.

Expected behavior:
The journal entry can't be created becuase all finanical data should be locked before specified lock date.

**Comment by Yenthe666** [comment]
@qdp-odoo could you give feedback on this one?

**Comment by auyeung112002** [comment]
It seems this bug exists since version 9.
https://github.com/odoo/odoo/commit/c04065abd8f62c9a211c8fa824f5eecf68e61b73

**Comment by qdp-odoo** [comment]
You can indeed create or duplicate an accounting entry prior to this date, but you won't be able to post it.

Seems fair enough to me, so I close this bug report

**Comment by auyeung112002** [comment]
From a user point of view, this behavior is not consistent with the warning message "You cannot add/modify entries prior to and inclusive of the lock date". Now user can add entries prior to lock date.

**Comment by hengsoheak** [comment]
You cannot add/modify entries prior to and inclusive of the lock date 2018-12-31
