### ISSUE TITLE
@api.constrains on pop up wizards

### ISSUE THREAD

**Issue by PeterSchwarzHPI** [odoo/odoo#15035]
Impacted versions: 10.0

Assuming you are having a one2many field in your model. The model represented by the field has a @api.constrains function for a field:
```python
@api.one
@api.constrains('stage_id')
def _check_stage_id(self):
    _logger.debug(self.stage_id)
    if self.is_duration_or_controller_missing():
        raise ValidationError(self.DURATION_CONTROLLER_NOT_SET_ERROR)
    elif self.is_user_not_approver():
        raise ValidationError(self.APPROVAL_DENIED_ERROR)
```
Let's say the pop up wizard of the one2many field uses a statusbar widget on the constrains field.

Steps to reproduce:
Try to edit an EXISTING record in that one2many field (newly created records to whatever reason are not affected) - so don't miss out to save the whole parent record first. Change the stage (let's say it should be in stage x after that change). And change it another time (let's say it should be in stage y after that change).

Current behavior:
Reading the logger messages it turns out that the first change does not change the self.stage_id value which of course also affects the constrains function as it is not triggered. The second change triggers the constrains function with the value self.stage_id == x.

Expected behavior:
I think that's obvious.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@rco-odoo I see you're assigned. Any news/feedback on this?

**Comment by Yenthe666** [comment]
@rco-odoo could you give feedback please?

**Comment by pedrobaeza** [comment]
The constraints are not executed until the whole saving of the parent record, so this is not really a bug, but a misunderstanding of the way ORM works, and thus I close.
