### ISSUE TITLE
Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached.

### ISSUE THREAD

**Issue by trinanda** [odoo/odoo#150336]
Impacted versions: Odoo 16, wkhtmltopdf 0.12.6.1

Steps to reproduce: Print a pdf with more than 500 pages, for example Journals Audit

Current behavior: `Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : `

Expected behavior: It should be possible to print a pdf with no limit on the number of pages, even if it is hundreds or thousands of pages.

Screenshot:
![image](https://github.com/odoo/odoo/assets/25479663/d7978151-e782-458d-9d78-6c16bb645049)

**Comment by gdgellatly** [comment]
Then increase your memory limits. Not rocket science.

Or use a dedicated wkhtmltopdf report server.

Odoo has memory limits, default wkhtmltopdf calls in Odoo are subject to those limits, if you need higher limits, you need to accommodate for them.
