### ISSUE TITLE
How do you guys install jcconv? pip install -r requirements.txt fails on Ubuntu 16.4.1

### ISSUE THREAD

**Issue by jl2035** [odoo/odoo#15043]
Impacted versions: Only tried Odoo 10
Steps to reproduce: Try to install Odoo 10 on Ubuntu 16.4.1
Current behavior: Installation of requirements fails
Expected behavior: Requirements should install correctly

I wonder if it's possible to somehow skip this requirement. I don't need anything Japanese related!
This is the output from pip install -r:

Collecting Babel==2.3.4 (from -r requirements.txt (line 1))
  Using cached Babel-2.3.4-py2.py3-none-any.whl
Collecting decorator==4.0.10 (from -r requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting docutils==0.12 (from -r requirements.txt (line 3))
  Using cached docutils-0.12-py3-none-any.whl
Collecting ebaysdk==2.1.4 (from -r requirements.txt (line 4))
  Using cached ebaysdk-2.1.4.tar.gz
Collecting feedparser==5.2.1 (from -r requirements.txt (line 5))
  Using cached feedparser-5.2.1.zip
Collecting gevent==1.1.2 (from -r requirements.txt (line 6))
  Using cached gevent-1.1.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting greenlet==0.4.10 (from -r requirements.txt (line 7))
  Using cached greenlet-0.4.10-cp35-cp35m-manylinux1_x86_64.whl
Collecting jcconv==0.2.3 (from -r requirements.txt (line 8))
  Using cached jcconv-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rdzva5xr/jcconv/setup.py", line 17
        print "unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rdzva5xr/jcconv/

**Comment by jl2035** [comment]
I think I know what my problem was. My virtualenv was using the wrong python. It has to be 2.7.

**Comment by mayur200** [comment]
How did you solved this issue?

**Comment by The-macharia** [comment]
clone this repository instead : $ git clone https://www.github.com/odoo/odoo --depth 1 --branch 12.0

i followed the tutorial at https://linuxize.com/post/install-odoo-12-on-centos-7/#install-and-configure-odoo-12 and the error was gone
