### ISSUE TITLE
odoo server error while opening lead as user,odoo9

### ISSUE THREAD

**Issue by Priyanshi1010** [odoo/odoo#15056]
Impacted versions:9

Steps to reproduce:

Current behavior: ['|',('user_id','=',user.id),('message_partner_ids','child_of',[user.commercial_partner_id.id])]

i used this domain rule in record rule "Personal lead" under object "Lead/Opportunity" but on opening the (lead as user) i get odoo server error as: raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf))) ValueError: Invalid field 'user_id' in leaf "<osv.ExtendedLeaf: ('user_id', '=', 10) on mail_followers (ctx: )>"

suggest me a solution!
Expected behavior: how can i solve this error?

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/24772560/21922024/0ce8ec9c-d992-11e6-8c32-0941b8e4fac7.png)

**Comment by Yenthe666** [comment]
Hi @Priyanshi1010,

Thank you for your report however this is not a bug or issue in the official Odoo code.
We only use Github for issues in the default Odoo, this is not the place to ask questions or help.
Please ask this on the official help forums at help.odoo.com.

Regards,
Yenthe

**Comment by Priyanshi1010** [comment]
okay , sorry
