### ISSUE TITLE
[BUG][16.0] base: I want to fix wrong translation vietnamese language

### ISSUE THREAD

**Issue by phamduytam** [odoo/odoo#150594]
Display the wrong message in the Vietnamese language
```
msgid "Today Activities"
msgstr "Các oạt động hôm nay"
```
![image](https://github.com/odoo/odoo/assets/12709895/fc69912a-fce5-40f3-9212-71278ce6fe55)

Expected: "Các hoạt động hôm nay"

**Comment by duong77476-viindoo** [comment]
Ô lên https://explore.transifex.com/odoo/odoo-16/ dịch cho nó hoặc chơi kiểu tự fork về mà dịch theo ý mình chứ nhiều khi người dịch cũng lởm
