### ISSUE TITLE
Expense account entries generation does not validate employee address_home when payment is by company

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#15052]
Impacted versions: 10

Steps to reproduce:
Create expense for an employee whose address_home_id is empty. Select payment mode=by company. validate and generate account entries.

Current behavior:
The system creates a payment record and an account entry. Those records are not assigned to any partner. If you try to see the account entries from the payment, the system complains because there is no partner associated.

Expected behavior:
The expense account entries creation should validate the employee has an address_home, as it does when payment mode = by employee

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this still happening in latest code?

**Comment by tivisse** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.

Regards
