### ISSUE TITLE
[10.0] Allow to import products with a given product_template ID

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#15053]
This wish is related to keeping SEO while migrate from another shop engine. One of the things that holds most e-shop with their current e-commerce system is the fear of throw away all their work on SEO for their products. 
AFAIK the usual solution is to write 301 redirections for each URL referenced in Google. At least one per product and often one per image of product. It is a pain to build, and it can slow down the web server.

By allowing  to import products with a given primary key for product_template ID, you will help them to keep their SEO with  a far easier and quicker strategy. Because with Odoo one can request products with IDs in the URLs. 

With IDs in the URL one can forget all 301 for products and related images :
1. First, prepare the migration by adding IDs in URLs at his current e-commerce system. Then request the shop engine to do automatic redirections. In a few weeks the new URLs with IDs are registered in major search engines. 
1. Second, when you open your new Odoo web store, as long as you keep the same IDs (those are the pKey of product_template) a simple regex does the job to redirect old URLs containing IDs to Odoo URLs with IDs.

Impacted versions:
All versions, until Odoo 10 at least.

Steps to reproduce:
Import products through Odoo import screen.
Current behavior:
There is no way to fix product_template ID for each product, apart from importing directly in Postgresql tables.
Expected behavior:
Give us an option to do that or, at the minimum, instructions and/or module to import directly in Postgreql tables.

**Comment by pedrobaeza** [comment]
Sorry, but this is something custom due to your import conditions, but not something that Odoo core should take into account IMO. But it's very easy to develop a custom module for making what you want. That's the magic of Odoo, that it's extensible.

Closing as no real issue, but an implementation need that should be covered by anyone with Odoo development skills.

**Comment by zeroheure** [comment]
@pedrobaeza I disagree a little bit :-) 
Is is a serious SEO problem for website migration from another ecommerce solution. Without this feature one will quickly get lost in cyberspace without page rank anymore! 
But yes, it can be done with a module.

**Comment by pedrobaeza** [comment]
I don't disagree on the feature need. I disagree on having this in Odoo core. Any way, we can both agree as this is not an issue. :wink:
