### ISSUE TITLE
How to update odoo after doing git pull?

### ISSUE THREAD

**Issue by fahhadalsubaie** [odoo/odoo#150547]
Impacted versions: Odoo 17

Steps to reproduce: How to update odoo after doing a git pull and getting the latest commits?

Current behavior: N/A

Expected behavior: N/A

**Comment by gdgellatly** [comment]
Not appropriate here as not an issue, but as a general rule, on a stable release with only Odoo code, a simple restart will be safe, running a -u all will ensure any xml changes are loaded.
