### ISSUE TITLE
odoo v9 v10 Requests for Quotation lines tax...can't select.....

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#15065]
Impacted versions: V9 V10 ...

Steps to reproduce:
1.create Requests for Quotation
2.add item on order lines..
3.select tax......is null ....can't use mouse select

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/8476734/21932683/caf2efa4-d9dc-11e6-8017-6094e2d302a2.png)
![image](https://cloud.githubusercontent.com/assets/8476734/21932724/f3460c66-d9dc-11e6-888b-ce8583e0a9a0.png)

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Thank you for your report.
This has been resolved in the meantime. You can now use the dropdown to show all taxes and you can click to select one.

Regards,
Yenthe
