### ISSUE TITLE
transifex language request declined

### ISSUE THREAD

**Issue by eneldoserrata** [odoo/odoo#15074]
Hello @mart-e  why request to add Spanish (Dominican Republic) to the project Odoo 10.0 was declined.

**Comment by mart-e** [comment]
Hello,

This was already explained on [the translator mailing list](https://www.odoo.com/groups/community-translators-63/community-translators-20325962), we no longer accept regional languages on transifex.
Also please, let's keep the transifex discussions on transifex.
