### ISSUE TITLE
[8.0]: Failed field compute function after commit https://github.com/odoo/odoo/commit/a1be7ca551f9f042878f6458bf5b789e62d0b68f

### ISSUE THREAD

**Issue by shepilov-vladislav** [odoo/odoo#15072]
Impacted versions:
[8.0]

Steps to reproduce:
8.0 branch with commit https://github.com/odoo/odoo/commit/a1be7ca551f9f042878f6458bf5b789e62d0b68f

Current behavior:
return cache for compute function(with store=False)

Expected behavior:
return calculated value without cache

I think function `_invalidate_documents` is bad

**Comment by rco-odoo** [comment]
Can you please be more specific on how to reproduce the issue?

**Comment by rco-odoo** [comment]
By the way, have you tried with 94410c83e18729db6942f2b2190df9a50cd3c19d (latest fix on mail invalidation) ?

**Comment by Yenthe666** [comment]
Hi @shepilov-vladislav ,

There has been no response in a few months.
I'm closing this report as this is (no longer) reproducable.
If you can still reproduce this on the latest source code or on a runbot then please provide us with more information and I'll reopen this issue.

Regards,
Yenthe
