### ISSUE TITLE
[BUG][16.0] Project: Error with subtask's "View Task" button on the frontend

### ISSUE THREAD

**Issue by liuhehe1995** [odoo/odoo#150809]
Impacted versions: 
16.0

Steps to reproduce: 
1.Log in from the portal.
2.My Account to Projects.
3. Open a task and add a record to the subtasks tab.
4.Clicks the "View Task" button

Current behavior: 
When the user clicks the "View Task" button, an error message appears with the following text: "UncaughtPromiseError: Uncaught Promise - Missing field string information for the field 'state' from the 'project.task' model."

Expected behavior: The user should be directed to the subtasks page directly.

Support ticket number submitted via odoo.com/help (optional): [#3700053](https://www.odoo.com/my/tasks/3700053)

Video/Screenshot link (optional): 
![2024-01-24](https://github.com/odoo/odoo/assets/147494891/320af404-99ae-4730-8cc3-560fe200c40f)

@qrtl

**Comment by yostashiro** [comment]
@liuhehe1995 Please close this issue.  I have checked and this issue does not occur in vanilla Odoo.  The issue seems to be related to having the OCA module project_task_stage_state installed.
