### ISSUE TITLE
printing bill opens the cash drawe

### ISSUE THREAD

**Issue by docmind** [odoo/odoo#15081]
Impacted versions: 10

Steps to reproduce:
Click on "bill" button in the pos restaurant interface

Current behavior:
The cash drawer opens when I click on the "bill" button after the bill is printed

Expected behavior:
The cash drawer shoudn't open.

Video/Screenshot link (optional): No

**Comment by sle-odoo** [comment]
@fgi-odoo is it expected?

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Ark74** [comment]
> The cash drawer opens ... after the bill is printed

Isn't this normal behavior from the printer / cash drawer?

AFAIK, most if not all receipt printers will send a signal to the cash drawer to open just after you print anything, hopefully a ticket.

Did I get it wrong?

**Comment by Yenthe666** [comment]
Indeed, I believe that is normal behaviour. A signal is sent to the cash drawer that then opens up the cash drawer, so I see no issue here really.
