### ISSUE TITLE
[10.0]problem with workflow in odoo 10

### ISSUE THREAD

**Issue by asdfsx** [odoo/odoo#15113]
Impacted versions:
10.0
Steps to reproduce:
create a new record
Current behavior:
ValueError: <type 'exceptions.TypeError'>: "draft() takes at least 4 arguments (1 given)" while evaluating
Expected behavior:
create a new record
Video/Screenshot link (optional):

I'm new to odoo community. And I wanna create a simple module with workflow for odoo 10.
The project`s address: https://github.com/asdfsx/qingjia
I install the module on odoo 10.
Then I try to create a new record, but everytime I save the record, it raise the exception "draft() takes at least 4 arguments..."

in data file `data/workflow.xml`，the config is
```
<record id="act_draft" model="workflow.activity">
            <field name="wkf_id" ref="wkf_qingjia"/>
            <field name="name">draft</field>
            <field name="flow_start" eval="True"/>
            <field name="kind">function</field>
            <field name="action">draft()</field>
        </record>
```

and the `draft()` method defined in model`model/models.py` looks like 
```
def draft(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        self.write(cr, uid, ids, {'state':'draft'}, context=context)
        return True
```
Is there sth wrong with my code?
And I'm also very interestes with how `safe_eval` executed function like `draft()`. I thought it need some parameters.

**Comment by Yenthe666** [comment]
Hi @asdfsx,

Thank you for your report.
Bug reports however should only be about the official code in Odoo, this isn't the place for asking questions and/or custom development.
Please ask this question on the official forums (help.odoo.com).
As to your bug: you're using `cr`, `uid`, `ids` etc, which are no longer used. Most of your code is in old API, which is not longer supported in Odoo 10.
for example:
`self.write({'state':'draft'}, context=context)`

Regards,
Yenthe

**Comment by asdfsx** [comment]
However! Thx a lot~~~

**Comment by Yenthe666** [comment]
That is correct. Best of luck :)

**Comment by ChaiyKroem** [comment]
def restore(self, cr, uid, ids, context=None):
        pool_cpp = self.pool.get("cpp.parent")

        for emp in pool_cpp.browse(cr, uid, context.get("active_ids"), context=context):
            pool_cpp.write(cr, uid, [emp.id], {"is_delete": 1})

        return True

what wrong this my code in odoo10? please help me
