### ISSUE TITLE
[9.0] Project -> Reports -> Issues Analysis

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#15110]
**Impacted versions:**
9.0

**Steps to reproduce:**
1) Go to Projects -> Reports -> Issues Analysis
2) Click on the "-" on the pivot column
3) Click on the "+" on the pivot column and select Date of Closing -> Day

**Current behavior:**
The following error is raised:

File "/home/odoo/runbot/extra/runbot/static/build/192805-9-0-16fa61/openerp/models.py", line 1988, in _read_group_prepare_data
    value =  pytz.timezone(context['tz']).localize(value)
File "/usr/local/lib/python2.7/dist-packages/pytz/tzinfo.py", line 304, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

**Expected behavior:**
See issues sorted by their closing date day.

**Video/Screenshot link (optional):**

![shot 1](https://cloud.githubusercontent.com/assets/1809451/22053564/2f9f29f6-dd5a-11e6-84f4-916691eebec9.PNG)

![shot 2](https://cloud.githubusercontent.com/assets/1809451/22053567/331de108-dd5a-11e6-8dc3-94e6641a2294.PNG)

**Comment by Yenthe666** [comment]
Hi @adekock11,

Thank you for your report.
I've just tested this on the latest Odoo 9 and I can confirm that this is a bug.
![image](https://cloud.githubusercontent.com/assets/6352350/22056745/e0ea7182-dd61-11e6-821d-c11c2ec7ae0c.png)
@JKE-be and @nim-odoo could you guys look at this one?

Regards,
Yenthe

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/2e5b58a3dabedf6ff452ae170829362a60d6e1aa
