### ISSUE TITLE
[10.0] @api.onchange does not write if field is twice in the same view

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#15111]
Impacted versions: 10.0 but probably any version.

Steps to reproduce:
Imagine the following flow:
- You inherit a model:
```
# -*- coding: utf-8 -*-
from odoo import models, fields, api

class product(models.Model):
    _inherit = 'product.template'
```
- You add a new field on the model:
```
    is_bed = fields.Boolean(string='Is bed')
```
- You add this new field to the view through an `xpath`
- You add another, already existing and added field, to the view again (obviously by mistake).
```
    <record model="ir.ui.view" id="product_details_bed">
      <field name="name">product.template.slg</field>
      <field name="model">product.template</field>
      <field name="priority">501</field>
      <field name="inherit_id" ref="product.product_template_only_form_view"/>
      <field name="arch" type="xml">
        <xpath expr="//div[@name='options']" position="inside">
            <field name="is_bed"/>
            <label for="is_bed"/>
            <field name="recurring_invoice" />
        </xpath>
      </field>
    </record>
```
In this view I've added in the field `recurring_invoice` but this field was already shown in the original view, so this field will be in the view two times now.
- You add an `@api.onchange` on the newly created field and do a write on the field that you've accidentally added for a second time on the view:
```
    @api.onchange('is_bed')
    def on_change_bed(self):
        print self.is_bed
        if self.is_bed is True:
            self.recurring_invoice = True
        else:
            self.recurring_invoice = False
```

In this case the write in the `@api.onchange ` will not be triggered since the field is in the view twice, which Odoo cannot handle.

Current behavior: There is no warning that tells the user that his new view, that inherits an existing one, already shows the field and that you're showing it twice now. Adding a field twice to a view will give unwanted behaviour and causes strange bugs, like this one.
Quite a lot of new developers get confused by this and get stuck.

Expected behavior: There is a warning telling the user that the field(s) that he added to the existing view are already on the view and that this may cause issues. This warning should probably be a `warning` in the Odoo logfile as it shouldn't be blocking but may cause a developer to search after issues for quite some time.

We might want to look at the functions `postprocess_and_fields` and `postprocess_and_fields` to see if the nodes already exist. If there is a second match we can print a warning in the `logger`.
Another thing to watch out for is that we do this on the fully rendered view. We can have multiple inherited views that show the same field again, so we have to look at the final result.

**Comment by Yenthe666** [comment]
Hi @mart-e,

I've written out the flow that we've discussed and what happens. I believe a warning in the logger would be a neat start. You can search quite a while for this error and especially newer developers run into this quite often.
All feedback and/or PR's are welcome 😉

**Comment by Yenthe666** [comment]
Some mock-up / prototype for future reference in the `postprocess..`
```
        for f in node:
            if children or (node.tag == 'field' and f.tag in ('filter', 'separator')):
                postprocess_fields = self.postprocess(model, f, view_id, in_tree_view, model_fields)
                union = list(set(fields) & set(postprocess_fields))
                if union:
                    _logger.warning("Fields %s alread present in the view definition (view %s, %s, tag %s)", union, view_id, model, f.tag)
                fields.update(postprocess_fields)
```

**Comment by gdgellatly** [comment]
6.1 use to raise an Error if a field was defined twice in a view,
osv.Exception style when you opened it.

**Comment by Yenthe666** [comment]
Hi @mart-e,

I made a PR here: https://github.com/odoo/odoo/pull/15366
I'm not 100% confident if it is perfect yet. Why? I've been looking at the logs and there are multiple log statements printed for other views now too. An example:
```
2017-02-06 10:51:02,191 7526 WARNING myDatabase odoo.addons.base.ir.ir_ui_view: The fields ['name', 'summary'] are already present in the view definition (view name: Apps Kanban, view id: 101 model: ir.module.module, tag in the view: templates).

```

Although my own module, that I made to intentionally trigger this, works fine. The issue is found and logged:
```
2017-02-06 10:51:04,113 7526 WARNING myDatabase odoo.addons.base.ir.ir_ui_view: The fields ['barcode'] are already present in the view definition (view name: product.template.example, view id: 545 model: product.template, tag in the view: notebook).
```

What do you think about this?

Regards,
Yenthe

**Comment by mart-e** [comment]
> P.S: If you want to I can link you an example module to test this with. :wink:

@Yenthe666 if you test is correct, you will get enough examples with standard code :wink:

**Comment by Yenthe666** [comment]
@mart-e yes you can easily add a field to an existing view again too.. I know 😉
I wanted to be sure that it works fine with multiple inherits & views too though.

**Comment by pedrobaeza** [comment]
@Yenthe666 This is fixed with latest v11 JS rewriting, although the idea is to not have the same field several times, as it can lead to other unexpected things.

**Comment by Yenthe666** [comment]
Oh really? Didn't know that, that is a good fact.
