### ISSUE TITLE
[8.0] website_crm : declared required field name doesn't exist in the contact_us form

### ISSUE THREAD

**Issue by houssine78** [odoo/odoo#1512]
there is an error in the contact us form that doesn't allow the lead creation

this bug was introduced on the Merge pull request #886 from odoo-dev/master-contactus-jke 

"name" is in the list of the _REQUIRED fields while it should be "partner_name" which is in the form
https://github.com/odoo/odoo/blob/master/addons/website_crm/controllers/main.py#L51

so the following code always return to the contact_us form without creating the lead and without displaying an error message

https://github.com/odoo/odoo/blob/master/addons/website_crm/controllers/main.py#L68

you should replace the required field in the list of the _REQUIRED by partner_name

or change the partner_name to name in the form
https://github.com/odoo/odoo/blob/master/addons/website_crm/views/website_crm.xml#L55

**Comment by Yenthe666** [comment]
@JKE-be this still looks relevant? See https://github.com/odoo/odoo/blob/8.0/addons/website_crm/controllers/main.py#L57

**Comment by Yenthe666** [comment]
Hi @houssine78 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by houssine78** [comment]
Hi @Yenthe666 

I won't still losing my time make a new bug report for an issue that hasn't been takled for 3 years. And that won't be toke into account neither.

Thanks for closing this.

**Comment by JKE-be** [comment]
Hi @houssine78 

I have just tested again and it seems to work as expected.

![image](https://user-images.githubusercontent.com/4848797/31332225-c5ef08da-ace5-11e7-8d36-d0ca3e827b05.png)


Problem with this old thread of 3 years old is that:
    you don't explain really a step to reproduce it.
    you propose a fix, without providing a PR

So for me, there are no bugs, and so nothing to do while we don't have more pieces of information.

In any case, thanks for your reporting.
And thanks to @Yenthe666 to filter v8 PR/Issue
