### ISSUE TITLE
[BUG] [17.0] Invoice pdf file is not updated when terms and conditions is changed.

### ISSUE THREAD

**Issue by pablohmontenegro** [odoo/odoo#151402]
**Impacted versions**: 17.0

**Steps to reproduce**:
1) Go to runbot odoo enterprise version 17.0 instance and activate development mode.

2) Go to "Accounting / Customers / Invoices" and create and post a new invoice with one invoice line.
![image](https://github.com/odoo/odoo/assets/89547436/0eeaaee4-6542-4770-b88c-9f1aef9cb2c1)

3) Click on the button "Send & Print". Select only the checkbox "Download" and then click on the button "Send & Print".
![image](https://github.com/odoo/odoo/assets/89547436/6ce9c63e-4411-4323-aa7d-d904e30de4eb)
The invoice pdf file is automatically downloaded and attached to the invoice.

4) Change the terms and conditions of the invoice. For example: from "Terms & Conditions: https://57139686-17-0-all.runbot166.odoo.com/terms" to "Terms & Conditions: None".

5) Go to "Settings / Technical / Reporting / Reports", search reports with action name "Invoices" and "Invoices without Payment" and check that on "Advanced Properties" page of both reports is not selected the checkbox "Reload from Attachment".
![image](https://github.com/odoo/odoo/assets/89547436/76c3219d-93ca-4a8e-9430-f4408ed7f3f5)

6) Repeat step 3.

7) The attached invoice pdf file is not replaced with the new one with updated terms and conditions and also the invoice pdf file downloaded is not the updated one.
![image](https://github.com/odoo/odoo/assets/89547436/b207fa93-30c2-40d7-aee6-f5dfc983a600)

**Current behavior**:
The invoice pdf file is not being updated if invoice terms and conditions are changed.

**Expected behavior**:
The invoice pdf file is being updated if invoice terms and conditions are changed.

**Video/Screenshot link (optional)**:
https://drive.google.com/file/d/1Qrr5jn74ytRzs8fChWDhvPG6D7ipfidv/view

**Support ticket number submitted via odoo.com/help (optional)**:
https://www.odoo.com/es_ES/my/tasks/3705410

Task Adhoc side: 
36601

**Comment by gdgellatly** [comment]
That is standard behaviour. At the time you issued the invoice, the terms and conditions applied. If you wish to change them then you need to delete the saved attachment to create a new one. Or change the report (inadvisable) to not reload from attachment. 

This should be relatively obvious, you can't change what you sent a customer after the fact. e.g. If the customer address changed, you still want original on invoice attachment for record keeping purposes.

**Comment by john-herholz-dt** [comment]
Additional note: Some countries have restriction that an invoice must not be changed after it's creation.
So I would consider this also not a bug.

If you want it, check the invoice report settings. There might be a checkbox that says "load from attachment", which indicates if this report (the invoice) will be re-generated.

**Comment by karlgezer** [comment]
This is most certainly a bug - when an error in an invoice is noticed, and corrected by resetting the invoices to draft, making changes, and then reissuing the invoice - the system re-generates the old, uncorrected, invoice. This makes no sense.
