### ISSUE TITLE
[8.0] Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by yannickbh** [odoo/odoo#15160]
Hello great community!

I'm constantly receiving in odoo logs the following message:

2017-01-19 13:58:38,439 3427 ERROR db01 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/bus/bus.py", line 188, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable 

- I'm running under Ubuntu 14.04, nginx as reverse proxy and Odoo 8
- I'm running under digital ocean and I have 2 Gb RAM,2 Cores, and 30TB
- Another information is that the database and odoo run on the same server.

**I'm running 2 IMAP accounts (which often stops receiving emails) and a backup tool which doesn't work anymore, neither the Instant Messaging - all these situations generated the error I described abo**ve

My guess is this is due a bad worker or nginx configuration.

I'm trying to find a documentation that explains workers implementation best practices. May anyone of you share a material with this content?

here follows my odoo-config file

> logfile = /var/log/odoo/odoo-server.log 
> logrotate=True
> addons_path=/opt/odoo/odoo-server/addons,/opt/odoo/custom/addons/OCB,/opt/odoo/custom/addons/server-tools,/opt/odoo/custom/addons/odoo-brazil-eletronic-documents
> db_name=db01
> dbfilter=db01
> list_db=False
> xmlrpc_interface = server ip
> netrpc_interface = server ip
> workers = 2
> proxy_mode = True
> longpolling_port = 8072
> xmlrpc_port = 8069

I've followed schenkels nginx [example](http://www.schenkels.nl/2014/12/reverse-proxy-with-odoo-8-nginx-ubuntu-14-04-lts/): 

here follows my nginx config file

> upstream odoo8 {
> server server_ip:8069 weight=1 fail_timeout=0;
> }
> 
> upstream odoo8-im {
> server server_ip:8072 weight=1 fail_timeout=0;
> }
> 
> server {
> listen 80;
> server_name server_name;
> 
> add_header Strict-Transport-Security max-age=2592000;
> rewrite ^/.*$ https://$server_name$request_uri? permanent;
> 
> 
> }
> 
> server {
> listen 443 ssl;
> server_name server_ip;
> 
> 
> client_max_body_size 200m;
> 
> keepalive_timeout 60;
> ssl on;
> ssl_certificate /etc/ssl/nginx/server.crt;
> ssl_certificate_key /etc/ssl/nginx/server.key;
> ssl_ciphers HIGH:!ADH:!MD5;
> ssl_protocols SSLv3 TLSv1;
> ssl_prefer_server_ciphers on;
> 
> proxy_buffers 16 64k;
> proxy_buffer_size 128k;
> 
> proxy_connect_timeout 600s;
> proxy_send_timeout 600s;
> proxy_read_timeout 600s;
> proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
> 
> proxy_set_header Host $host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
> 
> proxy_set_header X-Forwarded-Proto https;
> 
> proxy_redirect off;
> proxy_buffering off;
> 
> location / {
> proxy_pass http://odoo8;
> }
> 
> location /longpolling {
> proxy_pass http://odoo8-im;
> }
> location /web/static/ {
> proxy_cache_valid 200 60m;
> proxy_buffering on;
> expires 864000;
> proxy_pass http://odoo8;
> }
> }

**Can anyone help me please? :-)**

**Comment by jl2035** [comment]
Something similar here, but Odoo9.

**Comment by CakJuice** [comment]
Odoo 10 have this bug too

**Comment by Yenthe666** [comment]
Hi @yannickbh ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@jl2035 or @CakJuice feel free to create a new bug report with as many details as you can.

Regards,
Yenthe
