### ISSUE TITLE
[10.0] Can not pass previous context to Action when select multiple record in Tree View

### ISSUE THREAD

**Issue by kittiu** [odoo/odoo#15161]
Impacted versions: ALL

Steps to reproduce:

  * Passing a context value in Menu Action which open up a tree view (any model)
  * Select multiple record on the list, and select More > some Action (wizard)

Current behavior:

  * From the tree view, opening up the Action (wizard), we can't get the previous value context
  * But if we open the record in form view first, opening up the same action can get the value context

Expected behavior:

  * From the tree view, opening up the Action, should also pass the previous value context too

Video/Screenshot link (optional):

**Comment by windedge** [comment]
I have also encountered this bug/issue.

**Comment by gabrielo77** [comment]
I'm having the same issue with v8.0.

I've been reading the v11.0 web addon code and it seems they've fixed it in that version.

Do you have an alternative way of fixing this issue ?

**Comment by ejabu** [comment]
> I'm having the same issue with v8.0.
> 
> I've been reading the v11.0 web addon code and it seems they've fixed it in that version.
> 
> Do you have an alternative way of fixing this issue ?

Wow it sounds great, can you show me which part of code indicates this feature?

**Comment by pedroslopez** [comment]
Was this fixed in later versions then? If so, where would that fix be located? I'm still having this issue on v9

@kittiu since you created and closed the issue, maybe you could chime in. Did you find a fix?

**Comment by kittiu** [comment]
Sorry nop. I don't just think issue has been open too long.
