### ISSUE TITLE
Manufacturing with average cost does not create correct journal entries

### ISSUE THREAD

**Issue by Mohamedsharawy** [odoo/odoo#15172]
Impacted versions:
V10
Steps to reproduce:
Create product A (Material) & B (finished product ), set stock valuation account (Material)for Product A & output account (Wip) and for product B set WIP as input account and stock valuation account (Finish) and set average cost as costing method for A &B
Current behavior:
Odoo create only one journal entry  that debit WIP and credit material stock valuation

Expected behavior:
should create the second journal entry that credit WIP and debit Finish stock valuation
Video/Screenshot link (optional):

**Comment by bistaray** [comment]
WIP should not be the input account, WIP should be set on the PRODUCTION location as the input and output accounts.  

Input account means = 'when item is moves INTO in the company (is received from a Vendor or returned by a Customer)'

Output account means = 'when item moved OUT of the company (is delivered to a Customer or returned to a Vendor)'

Input and output accounts on the PRODUCTION location = 'when moved into and out of production (but staying in the company)'
