### ISSUE TITLE
Use of widget="selection" on relational field makes the domain not applied.

### ISSUE THREAD

**Issue by NicolasWebDev** [odoo/odoo#1517]
With openerp 7, if I have a many2one field for example with a domain defined, and in the object view I use the attribute widget="selection", then in the form the field choices are not filtered by the domain.

If I remove this attribute widget, then the domain gets applied (but then I have no way of removing the "Create and edit..." entry).

**_Impacted versions:**_
Versión 7.0-20140603-231034

**_Steps to reproduce:**_
1. Create a many2one field with a domain attribute.
2. Display it in its form view using the widget="selection attribute.

**_Current behavior:**_
The domain isn't applied, so the records are not filtered.

**_Expected behavior:**_
That the records got filtered following the domain.

**Comment by Yenthe666** [comment]
Hi @NicolasWebDev ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
