### ISSUE TITLE
No way to delete created pages, no way to recover from bad mistakes

### ISSUE THREAD

**Issue by mgrigajtis** [odoo/odoo#15175]
Impacted versions: 10.0

Steps to reproduce: 

Go into any page and customize.  Remove or comment out <t t-call="web.layout"> and it's closing tag.

Current behavior:

No way to recover from this error.  It should not let you make this error in the first place.  Can't find anyway in interface to remove page and create a new one.  This is especially bad if it's the home page.

Expected behavior:

The opposite of what it does.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @mgrigajtis,

Thank you for your report.
Could you be a little more specific to where you get this and how that you trigger it? I just tried with a simple `<p>Test</p>` element where I then removed `</p>` from and it works fine:
![image](https://cloud.githubusercontent.com/assets/6352350/22194590/c76abbc8-e143-11e6-9bf4-8c59ba7f181c.png)

Regards,
Yenthe

**Comment by mgrigajtis** [comment]
My mistake, it looks like I forgot an important piece of information.  I'm talking about removing both the opening AND closing tag of a `<t>` and `</t>` tag, specifically the one that called the layout.  I didn't actually remove them, I commented them out and saved it.

**Comment by Yenthe666** [comment]
Hi @mgrigajtis,

Thanks for the extra info.
Could you provide me with a screenshot of where exactly you've commented out a `<t>` element? I've tried a few but it works fine here.

Regards,
Yenthe

**Comment by bistaray** [comment]
To View, Edit, and Delete Odoo's Website Pages from the Backend

- Log in as an Administrator.
- Make sure you have Developer Mode activated.
- Navigate to Settings --> Technical --> User Interface --> Views.
- Add a Custom Filter "Whether this view is a web page template (complete) is true"

**Comment by mgrigajtis** [comment]
Is there a developer mode in Odoo 10?

**Comment by bistaray** [comment]
@mgrigajtis Yes. Enable via the bottom right of the Settings App dashboard

**Comment by Yenthe666** [comment]
Alright closing this as @bistaray has shared an answered from where you can recover if something really goes wrong. 😄 (thanks!)
