### ISSUE TITLE
Double journal entry at close sesion with orders invoiced

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#15170]
**Impacted versions:**
10, tested today on runbot 
**Steps to reproduce:**
Open Session, create one order and pay, after create new order(but invoiced) and pay.
Close session and review journal entries for first order is OK(entry for payment and entry for order), for second order is incorrect(one entry on invoice, one entry on payment and one entry for order(it is incorrect)).

The error is origin on [this commit](https://github.com/odoo/odoo/pull/13095/commits/77f1a75d2e0ec3b2a3bca20d77bb936a8784e573). At remove workflow, on function _confirm_orders of pos_session.py call to function order.action_pos_order_done() creating journal entries for orders invoiced. Before this commit, workflow signal is executed, but transition of pos.order is from act_paid to act_done and this orders not execute action_done of workflow.

**Current behavior:**
Orders  invoiced must create journal entry on account.invoice, but order on pos.order not must create again journal entry

**Expected behavior:**
Orders are invoiced not must be create journal entry on pos.order(it is create on invoice).

**Solution:**
Remove function action_pos_order_done, is unnecesary on orders

**Comment by Icallhimtest** [comment]
Fix landed in 10.0 at https://github.com/odoo/odoo/commit/bcc517b6eb7c288021b399dadab2437db1f3f7db

Thanks for reporting the issue @celm1990

**Comment by wtaferner** [comment]
@Icallhimtest 
It would have been nice if you could have taken my PR into consideration as it was done before you self assigned this issue. And over the top I think my PR is more elaborated than yours...sorry to say that...maybe @mart-e or @jorenvo  can give their opinion on that.

**Comment by Icallhimtest** [comment]
Sure @wtaferner but I wasn't aware of your PR as it wasn't linked to the issue. I don't follow the whole Odoo repo.

Indeed it's slightly cleaner and it fixes another issue too, that of linking invoiced orders to their journal entries.

I'll add it. I just hope I don't break anything relying on the behaviour of not having it linked.

**Comment by wtaferner** [comment]
Ok, great, I have quite some experience with PoS so I guess it should be safe, but if you are keen enough, add a test ;-) I was sparing this one again as I think you guys should start constantly doing it that you can easily demand it from contributors :-)
