### ISSUE TITLE
Odoo not creating database for my module

### ISSUE THREAD

**Issue by Truuezz** [odoo/odoo#151882]
Impacted versions:
Odoo 17.0
Steps to reproduce:
Follow the odoo tutorial till part 4 
Current behavior:
When I launch odoo with this command : 'python odoo-bin -r odoo -w  odoo  -d rd-demo -u estate'. All modules gets loaded and I get no error. Estate is the module I'm creating, I follow all the steps like specified in the tutorial and it doesn't create a database. The module is visible in the web interface
Expected behavior:
It's supposed to create a database but it doesn't. I get no error and I don't know what to do.
Video/Screenshot link (optional):
the logs : 
<img width="553" alt="image" src="https://github.com/odoo/odoo/assets/92547004/c4976f66-9458-4565-931b-1ffeed2b4d43">
the database : 
<img width="503" alt="image" src="https://github.com/odoo/odoo/assets/92547004/2a3d8e91-210f-4f7c-a005-a2c1affdd7bb">
the module name is 'estate' so it should be after 'decimal_precision'.
Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
-i is install, -u is upgrade
