### ISSUE TITLE
Odoo 9: Multi Website does not work

### ISSUE THREAD

**Issue by Derter** [odoo/odoo#15180]
**Impacted versions:** 9 (from July 2016, might be fixed already!?)

**Steps to reproduce:**
-Create two domains and put A-Record to point at your odoo server.
-Create two Companies
-Create two websites with the created domain names, assign each to one company.

**Current behavior:**
-It seems like both domains only take the information given in the first website-configuration you created. 

Inspecting with browser shows: both domains have only the company assigned for the first website configuration, if you change company on the first configuration, both domains will change the entry: data-oe-company-name="Company_Name"
If you change the second configuration the entry data-oe-company-name="Company_Name" will not change.

Expected behavior:
-Each website configuration should apply to the given domain names in the configuration.

-- Its possible that this problem is already solved in newer Odoo code, this is taken from source code date: **20.July.2016**
but I can not find any indication that it is, so I want to hear an answer on this directly from the source before upgrading the version. 

+ I cant reproduce it on runbot since two domains have to point at the IP to test.

**Comment by Yenthe666** [comment]
Hi @Derter,

Thank you for your report. You say " so I want to hear an answer on this directly from the source before upgrading the version." why is this the case? Why would you want to wait / refrain from updating your Odoo?
The fact is that upgrading an Odoo does not take a lot of time and then you can test against the latest version. On the other hand if Odoo needs to reproduce this it will take a lot of time to test and configur and to be honest you might have to wait quite a while for feedback.

Regards,
Yenthe

**Comment by Derter** [comment]
Hi @Yenthe666,

Thanks for the fast answer. Will try if updating will solve the issue now and update here.

**Comment by Derter** [comment]
Hi @Yenthe666,

just for info:

Upgrade did not help. Multi Website is not working in odoo version 9.

Furthermore I crashed the whole Odoo Server with trying around with multi website parameters. We split database now and created a second odoo instance to get to websites on different urls on the same server.

**Comment by Yenthe666** [comment]
@JKE-be perhaps you could supply us with more feedback?

**Comment by JKE-be** [comment]
IMHO, there are no fix in v9 after july about it.
But to have multi domain detect current website via header, so you need to add some headers in nginx config eg.

If you follow the documentation it should work...
Can you confirm that you have this header... X-Forwarded-Host ...?

https://www.odoo.com/documentation/9.0/setup/deploy.html#id7


> I crashed the whole Odoo Server with trying around with multi website parameters.

Strange, curious to see your log... it should not break anything in a perfect world.

> We split database now and created a second odoo instance to get two websites on different urls on the same server with nginx webserver.

If your website are completely independent (not the same products, same customesr db and co...), yes it is the best to do. Multi website is no more really supported in v10, only in advanced mode ... And if you want to use distinct template between your databases, that simplify everything.


About your upgrade, don't forget that some upgrade are 'security fix' ! 
The migration is only needed for new version, but if you continue to uses v9 eg, you can update the code without touch anything in your database.

**Comment by Derter** [comment]
> About your upgrade, don't forget that some upgrade are 'security fix' !
The migration is only needed for new version, but if you continue to uses v9 eg, you can update the code without touch anything in your database.

I was not about to upgrade but to update v9 to newest code. And about not touching database: isnt it necesarry to uprgade database after updating the code?

eg. python odoo-bin -c /etc/odoo.conf -d XXXXX  -u all --stop-after-init

which would remove your changes that were not uprgade 'safe'?



I somehow managed to set a wrong public user (not from the company) for the website which I couldnt remove since Odoo was down after that and I didnt know which table and wasted some hours on this when i realised I have to reset everything.

Heres the error:

> ERROR:
> 2017-01-23 15:55:52,008 9563 ERROR Source_Echtdatenbank_20160324 werkzeug: Error on request:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
>     execute(self.server.app)
>   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
>     application_iter = app(environ, start_response)
>   File "/home/odoo9/odoo/openerp/service/wsgi_server.py", line 184, in application
>     return application_unproxied(environ, start_response)
>   File "/home/odoo9/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
>     result = handler(environ, start_response)
>   File "/home/odoo9/odoo/openerp/http.py", line 1495, in __call__
>     return self.dispatch(environ, start_response)
>   File "/home/odoo9/odoo/openerp/http.py", line 1469, in __call__
>     return self.app(environ, start_wrapped)
>   File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
>     return self.app(environ, start_response)
>   File "/home/odoo9/odoo/openerp/http.py", line 1659, in dispatch
>     result = ir_http._dispatch()
>   File "/home/odoo9/odoo/addons/website_sale/models/ir_http.py", line 12, in _dispatch
>     return super(IrHttp, self)._dispatch()
>   File "/home/odoo9/enterprise/website_crm_score/models/ir.py", line 11, in _dispatch
>     response = super(ir_http, self)._dispatch()
>   File "/home/odoo9/enterprise/website_version/models/ir_http.py", line 11, in _dispatch
>     x = super(ir_http, self)._dispatch()
>   File "/home/odoo9/odoo/addons/utm/models/ir_http.py", line 15, in _dispatch
>     response = super(ir_http, self)._dispatch()
>   File "/home/odoo9/odoo/addons/website/models/ir_http.py", line 130, in _dispatch
>     request.website = request.registry['website'].get_current_website(request.cr, request.uid, context=request.context)
>   File "/home/odoo9/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/odoo9/odoo/openerp/api.py", line 354, in old_api
>     result = method(recs, *args, **kwargs)
>   File "/home/odoo9/enterprise/website_version/models/website.py", line 34, in get_current_website
>     exps = self.env["website_version.experiment"].search([('state', '=', 'running'), ('website_id.id', '=', website.id), ('google_id', 'not in', EXP.keys())])
>   File "/home/odoo9/odoo/openerp/api.py", line 248, in wrapper
>     return new_api(self, *args, **kwargs)
>   File "/home/odoo9/odoo/openerp/api.py", line 490, in new_api
>     result = method(self._model, cr, uid, *args, **old_kwargs)
>   File "/home/odoo9/odoo/openerp/models.py", line 1668, in search
>     return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
>   File "/home/odoo9/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/odoo9/odoo/openerp/models.py", line 4779, in _search
>     self.check_access_rights(cr, access_rights_uid or user, 'read')
>   File "/home/odoo9/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "/home/odoo9/odoo/openerp/models.py", line 3562, in check_access_rights
>     return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
>   File "/home/odoo9/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, *args, **kwargs)
>   File "<string>", line 2, in check
>     
>   File "/home/odoo9/odoo/openerp/tools/cache.py", line 85, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/home/odoo9/odoo/openerp/addons/base/ir/ir_model.py", line 836, in check
>     , (model_name, uid,)
>   File "/home/odoo9/odoo/openerp/sql_db.py", line 141, in wrapper
>     return f(self, *args, **kwargs)
>   File "/home/odoo9/odoo/openerp/sql_db.py", line 220, in execute
>     res = self._obj.execute(query, params)
> ProgrammingError: operator does not exist: integer = boolean
> LINE 1: ...odel = 'website_version.experiment'    AND gu.uid = false   ...
>                                                              ^
> HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by JKE-be** [comment]
Hi,

No, -u all is not required. You can just pull your code **and** restart your server.
All commits are retro compatible and need to work without the update of the view.

Some fix, when we have no other way, can need to update a view to have the fix, but if you don't update the view, you don't have the fix but it continue to works like before ! 

https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean


> About the "changes that were not upgrade 'safe'?"

it is rarely a good idea ;) ... 
or just for some quick patch waiting the update including the patch.

But for xml, it is easy to create via inherited view in the backend, even if a copy in data is better... That allow you dont loose your data when you update the module, and also you can easily disable it if it broke something...
For python, a extra module with your python updated code is the best ;) You keep an eye on all your custos like that.


About the traceback, the user_id is stored in table website
```
9=# \d website
        Column        |
----------------------+
 id                   |
 domain               |
 create_date          |
 social_linkedin      |
 cdn_filters          |
 social_facebook      |
 write_uid            |
 google_analytics_key |
 default_lang_id      |
 social_twitter       |
 cdn_url              |
 create_uid           |
 user_id              |
 default_lang_code    |
 social_googleplus    |
 company_id           |
 social_github        |
 compress_html        |
 social_youtube       |
 write_date           |
 cdn_activated        |
 name                 |


```

Probably the public user has been disabled, deleted or moved in a wrong company.

`get_current_website` should be only called from frontend, so if you call <yourdomain>/web you should be able to fix it from the back-end.

multi_version and website_version are not the same :) Both module together ... will be probably become quickly unmanageable.  You probably do the good choice splitting the 2 website with 2 databases.

**Comment by Derter** [comment]
> No, -u all is not required. You can just pull your code and restart your server.
All commits are retro compatible and need to work without the update of the view.

This information is worth a lot. Thanks.


I know about inheritance and that it is update safe but customers tend to use the update unsafe method.

Quintessence I take from this: dont use multi website in odoo.

**Comment by JKE-be** [comment]
@pedrobaeza 

For more information about the 'Advanced mode', 
It is just that by default you can too easily break your website with this feature. 
Another actual problem is that all models are not really multi website ready.
It is difficult for a new user to use it, if he don't understand all the fine details !

Eg:
- An inherit that could break the inherit from another website
- It is difficult to implement 2 eCommerces with multi website
- We don't support until now to have 2 themes simultaneously
- ...

This feature is not removed, it has been just hidden meanwhile we improve models to support it.
(In Website admin menu, website_id field is simply in 'invisible=1' !
So... Noooo, it has been not moved to Enterprise ;) 

That is always in the pipe of Odoo to make it available... ASAP.

**Comment by pedrobaeza** [comment]
Thank you very much for your explanations, @JKE-be !

This makes everything clearer. I'm with you that is not very easy to hack into multi-websites with Odoo, but hey, we have a 5 sites Odoo with 2 different themes in v8 running with your alpha version in odoo-extra hacked for getting all the CSS-them in a sub-namespace as a trick to separate totally styles. Header and footer was shared between all of them, but another hacky t-if shows the part we want for each site.

If you start to work on multi-theme support and want help, we are delighted to aid.

**Comment by lasley** [comment]
We have a ticket coming this sprint to make a module that will tidy some of this up too, so I will make sure to drop a line here when done. One of the big things I remember as part of the scope was remembering which domain a user belongs to & altering the `_compute_signup_url` against it.

**Comment by pedrobaeza** [comment]
@JKE-be are you going to work for v12 in this topic? Do you know our work about this?

**Comment by JKE-be** [comment]
We are trying to fix the website, e-commerce and editor to start. But maybe that we could start this feature for V12... 

No, I didn't see your work about this feature... Do you have something that works?

**Comment by lasley** [comment]
@JKE-be - Yup, [`website_multi_theme`](https://github.com/OCA/website/tree/11.0/website_multi_theme) works quite well

**Comment by pedrobaeza** [comment]
There are some tricks we needed to do for making it work due to the base (like creating some views on the fly and disabling others), but if it's included in core, there are more chances to go straight.

I thank you any way your help for making it work in v10 with the PRs we proposed and you merged:

* https://github.com/odoo/odoo/pull/18462
* https://github.com/odoo/odoo/pull/17970
* https://github.com/odoo/odoo/pull/17635

If you want us to collaborate when you start with the work, please ping us.
