### ISSUE TITLE
[odoo 9] [Blocking BUG] Unable to post journal entries in Expense Tacker 

### ISSUE THREAD

**Issue by ericzen** [odoo/odoo#15181]
Impacted versions: 9.0c-20170122

Steps to reproduce: Create an expense product with vat. Create an expense. Post entry. 

Current behavior: You have this message : Cannot create unbalanced journal entry. 
If you use an expense product without vat you have no message and the entry is post.

Expected behavior: The entry is posted

Video/Screenshot link (optional):

**Comment by ericzen** [comment]
I've made a test on demo and have the same error.

Help, it's really important because accountancy is blocked and re-invoicing too.

**Comment by ericzen** [comment]
Sorry @qdp-odoo 
Can you look this problem ? 

It's really a big problem because I can't enter my expenses and i need them to re-invoicing my customer.

**Comment by qdp-odoo** [comment]
bug fixed at revision https://github.com/odoo/odoo/commit/602d04117aa8544ed1313fc288dbfb43c0466136

thanks for the contribution
