### ISSUE TITLE
[Feature Request] Support for Turbolinks

### ISSUE THREAD

**Issue by kirantpatil** [odoo/odoo#15197]
Hi,

Please add support for [Turbolinks](https://www.npmjs.com/package/turbolinks) "Turbolinks makes navigating your web application faster".

Thanks.

**Comment by Yenthe666** [comment]
Hi @mart-e could you give an official statement on this one?
I don't believe this is something we'd like to implement and use. Above the changes / rewrites etc it also adds new dependencies and complexity.

**Comment by mart-e** [comment]
Hello,

Thanks for the suggestion but this is a nodejs package. We are a python application.
That doesn't seem compatible.
