### ISSUE TITLE
Multicompany in system parameters 

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#1520]
Hello,
we are considering the option of adding multiple companies processes to system parameters as an improvement, them comment the reasons which would be useful:

It would be useful to have parameters that depend on the company that the user has.

![syste_parameters](https://cloud.githubusercontent.com/assets/7605672/3783552/ecacea06-19ad-11e4-8887-42c46535f7c7.png)

**Comment by Yenthe666** [comment]
Hi @ernesto-gm,

Thank you for your report / suggestion.
This is not really something that Odoo would want or would change though, the current behaviour is working fine.
You're always welcome to make a PR and discuss on it there but changes are quite high that this would be refused.

Regards,
Yenthe
