### ISSUE TITLE
 Standard price on product update all depending product of the same template ?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#15200]
Impacted versions:8.0
 
The field **standard_price** is on the object **product.template** it must be on the object **product.product** 
so when changing the price of **a specific product** the value will not be **changed for all the product **  depend on the same template !!

**Comment by JKE-be** [comment]
Thanks for the reporting

It is by design.
You can use extra_price to change the price.

Best regards

JKE

**Comment by m3asmi** [comment]
there is no extra_price field on product.product object !
ps:version 8.0

**Comment by JKE-be** [comment]
You have right ! 

Extra price is configured on product.attribute.value... ;)

Go in  "product template" form vieww, client on tab 'variants', and at top right, you have the "variants prices" button

![image](https://cloud.githubusercontent.com/assets/4848797/22641777/5ab497cc-ec58-11e6-82f6-5ccc8237f9ac.png)

![image](https://cloud.githubusercontent.com/assets/4848797/22641804/75ab477e-ec58-11e6-9e2f-59bff4c08f9d.png)


Best regards

JKE

**Comment by m3asmi** [comment]
Hello,
the price_extra is used as **price** field for _sale_  not for **standard_price** used on _purchase_ ?
