### ISSUE TITLE
Warehouse route doest work normally

### ISSUE THREAD

**Issue by Mohamedsharawy** [odoo/odoo#15219]
Impacted versions:
Odoo V 10

Steps to reproduce:

Product A produced from product B and we need to make automatic internal transfer from location semi to finish every time product A are sold in sales order
create product A with Manufacturing &Make to order Route
Create product B with new route (procurement rule (move from anther location)) & Make to order

Current behavior:

when creating sale order with product A odoo , odoo make delivery order & Manufacturing order & (internal transfer based on the new route) which is right but when we cancel the sales order , only delivery order and manufacturing order got cancelled and internal transfer kept without getting  cancel

Expected behavior:
Internal transfer should to be cancelled as the related sales order canceled ,manufacturing order &delivery order they all cancelled automatically after cancelling the sales order

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
There was code foreseen for that, but it is not working as it should.  It is better to fix it like you said: when consume moves are mto, it should cancel the procurements before, so it will cancel everything else before too.

**Comment by Yenthe666** [comment]
Hi @Mohamedsharawy,

This has been fixed in the meanwhile as you can see in the latest 10.0 code:
https://github.com/odoo/odoo/blob/d0dbd570b628cc82183ddec6b78a49c88d4f12ef/addons/mrp/models/mrp_production.py#L486-L495
Please update your Odoo source code to the latest version in order to fix this.

Regards,
Yenthe
