### ISSUE TITLE
[10.0] Paid invoices from website are still waiting payment

### ISSUE THREAD

**Issue by Fenkiou** [odoo/odoo#15220]
We're working on an implementation of [Payzen](http://payzen.io/) as payment acquirer. It would be great if you were interested in integrates it to odoo addons.

I think the problem would appear with paypal but we don't have a Paypal test account to try.

**Impacted versions:** 10.0

**Steps to reproduce:**
- Select the right acquirer as default acquirer in the accounting config otherwise it will use payment transfer
- Go to your invoices on the website, pay it.
- You are redirected to acquirer website, you pay, it works well, you see that transaction is correctly created in odoo.
- Go back to your odoo account with the link provided by the acquirer
- Your notified that your payment was successful but not validated (see [here](https://github.com/odoo/odoo/blob/10.0/addons/website_payment/controllers/main.py#L82))

**Current behavior:**
- When you go to your invoices, the same invoice you paid isn't paid at all in odoo so you can pay it again and again.

**Expected behavior:**
1. Ok, the invoice isn't paid, but there was a successful transaction, so it shouldn't be payable anymore, don't know how to do it.

or

2. You create a payment and reconcile the invoice automatically. I did it by adding a method to payment.transaction in `website_portal_sale` (This should be moved in `website_payment` module IMHO):
```
    @api.multi
    def _pay_invoice(self):
        self.ensure_one()

        if not (self.state == 'done' and
                self.acquirer_id.auto_confirm == 'generate_and_pay_invoice'):
            return

        reference = self.reference.split('-')[0]
        invoice = self.env['account.invoice'].search([('number', '=', reference)])

        if not invoice or (invoice and invoice.state != 'open'):
            return

        invoice.pay_and_reconcile(self.acquirer_id.journal_id, pay_amount=invoice.residual)

        if invoice.payment_ids:
            invoice.payment_ids[0].payment_transaction_id = self
```

and call it after this [line](https://github.com/odoo/odoo/blob/10.0/addons/website_portal_sale/models/payment.py#L57)

**Comment by Fenkiou** [comment]
@nim-odoo sorry to ping you but I saw you worked on this, maybe you have an idea.

**Comment by MTantin** [comment]
Same issue for me with **paypal as payment acquirer**.

# Configuration
Fully configured on two sides Odoo and Paypal with IPN and DPN.

![paypal-1](https://cloud.githubusercontent.com/assets/4457345/25220202/56d4d990-25b1-11e7-8181-0600140d68e7.PNG)

Select fourth configuration to auto-validate the invoice and Bank as default journal:
![paypal-2](https://cloud.githubusercontent.com/assets/4457345/25220207/59a872a8-25b1-11e7-9ce6-352a6d0c4283.PNG)

Select Paypal as default acquirer to pay invoices: 
![default_paypal](https://cloud.githubusercontent.com/assets/4457345/25220294/a7e42426-25b1-11e7-91a9-119a61b460bc.PNG)

# Payment
After that configuration, i will pay my invoices
![invoices-front-before-payment](https://cloud.githubusercontent.com/assets/4457345/25221334/0dcd17c2-25b5-11e7-8dc0-85ea1e7d8450.PNG)
![payment-confirmed-by-paypal](https://cloud.githubusercontent.com/assets/4457345/25221342/14403684-25b5-11e7-9b41-72f327e8f114.PNG)
![odoo-confirmation-payment](https://cloud.githubusercontent.com/assets/4457345/25221347/1745a652-25b5-11e7-80e0-b49f080ffc3d.PNG)

In the Odoo log, Paypal IPN is validated
![valide-ipn-com](https://cloud.githubusercontent.com/assets/4457345/25221711/650dc774-25b6-11e7-8ee1-16c9ad7474a9.PNG)

My transaction is completed in backend
![payment-transaction-done](https://cloud.githubusercontent.com/assets/4457345/25221616/048437a8-25b6-11e7-929d-54f9842b1f02.PNG)

**But, finally, my invoices still waiting for payment...**

# Solution
I tried @Fenkiou code and it's working
![invoices-paid](https://cloud.githubusercontent.com/assets/4457345/25223880/fd88ab26-25bc-11e7-84a5-9f0d4e059789.PNG)

**Comment by Yenthe666** [comment]
@nim-odoo can you look at this?

**Comment by robindierckx** [comment]
+1 Same issue with Stripe in odoo 10.0

**Comment by yasii1991** [comment]
I'm getting the following error while trying stripe payment in enterprise 10:

22] "GET /payment_stripe/static/src/js/stripe.js?_=1514526130959 HTTP/1.1" 200 -
2017-12-29 05:42:24,542 7843 ERROR walkintours_data_import odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/www/odoo/odoo/Walkintours/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/www/odoo/odoo/Walkintours/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/www/odoo/odoo/Walkintours/odoo/addons/http_routing/models/ir_http.py", line 325, in _dispatch
    rule, arguments = cls._find_handler(return_rule=True)
  File "/home/www/odoo/odoo/Walkintours/odoo/addons/base/ir/ir_http.py", line 84, in _find_handler
    return cls.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/home/www/odoo/.local/lib/python2.7/site-packages/werkzeug/routing.py", line 1563, in match
    raise NotFound()
NotFound: 404: Not Found

**Comment by smetl** [comment]
I didn't test this issue. However, if you take a look at https://github.com/odoo/odoo/blob/10.0/addons/website_portal_sale/models/payment.py#L32

... there is a little condition that could prevent the payment creation/reconciliation:

`if tx.acquirer_id.journal_id:`

Are you sure your acquirer has a journal set?

**Comment by JKE-be** [comment]
@smetl you don't arrive until this line since you don't  have a sale_order_id in  https://github.com/odoo/odoo/blob/10.0/addons/website_portal_sale/models/payment.py#L65 

Purpose of website_payment is only to make the payment (payment.transaction), and as the message explains need to be encoded/validated at the hand by the sale/accounting team.
There is no process in V9/10 to automatically reconcile what has been paid with the payment.transaction. 

The code proposed is partially wrong and risky, the reference is arbitrary given in the URL and could be another thing that an order or invoice ... the amount can be easily altered via the URL and don't match the invoice amount. You are mixing method dedicated to validation of SO with your use case: methods _confirm_so, mode 'generate_and_pay_invoice' and ...  are used once we pay a sale_order (website_quote, website_sale, ... )

A task has been created in the past to add this feature and improve it, so it is not possible to have this in v12 (if not already in v11)
