### ISSUE TITLE
[8.0,9.0] Inconsistent field street on website checkout and backend

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#15221]
### Impacted versions:
- 8.0, 9.0
### Steps to reproduce:
- Go to website checkout and compleate the form, using  a company name

- Go to res.partner of the new customer and see the field street 

### Current behavior:
- Field Street is used to capture the company name
![image](https://cloud.githubusercontent.com/assets/10233975/22302042/cd86915c-e2f2-11e6-8fec-fddc7248f94a.png)

![image](https://cloud.githubusercontent.com/assets/10233975/22302051/d11be4f2-e2f2-11e6-900d-9e88f2a41948.png)

### Expected behavior:
- Have a special field to capture the company name like in odoo v10.0

![image](https://cloud.githubusercontent.com/assets/10233975/22302216/64e76350-e2f3-11e6-90f3-b1ca5b83d440.png)

**Comment by JKE-be** [comment]
Thanks for the reporting.

Duplicated of:
#2541
#11619
#12541
#12590
#13198
#15354
...

It has been by design, until v10, to avoid the duplication of res_partner.

In v10 it has been updated, using a real field company_name instead of street2 and a button to create the real res_partner.

Thanks
