### ISSUE TITLE
The one-click deployment of Odoo Apps should be controllable by sysadmins

### ISSUE THREAD

**Issue by odony** [odoo/odoo#15225]
## Summary
Odoo includes a one-click install feature, for easy deployment of Apps coming from the Odoo Apps Store.
This feature is exposed directly in version 8, and located in dev mode in Odoo 9 and 10.

However at the moment we cannot guarantee that all Apps published on the Odoo Apps Store are safe. And it is a security risk to let end-users deploy Python code on their Odoo servers without requiring any review/deployment by a competent system administrator.

So we plan to disable the feature by default, and instead make it relatively easy to turn on when it is explicitly desired. End-users will receive a message when they attempt to use the feature, and will have to contact the sysadmin to enable it.
This will also allow sysadmins to permanently disable the feature on sensitive environments, even if it was previously enabled by default.

This will be done in all supported stable versions:

- 8.0: PR #15249
- 9.0: PR #15248
- 10.0: PR #15246 

## Rationale
1. We cannot guarantee that all Apps published on the Odoo Apps Store are safe. And it is a security risk to let end-users deploy Python code on their Odoo servers without requiring any review/deployment by a competent system administrator.
We will work on improving the validation process of the Store, but this will require time, and won't probably be a 100% safe process in any case.
2. The one-click install feature is however really useful to help non-technical users install Apps, as long as the feature has been explicitly allowed by the system administrator. This is a common feature in other software suites as well. So we'd like to keep it as an opt-in feature.
3. Administrators of multi-tenant servers, cloud hosting services, etc. understandably expect to be able to turn off the feature for security/control reasons.
4. By turning off the feature by default, but still exposing it in the UI, we keep it *discoverable* for users. The error message should be helpful to direct users to their sysadmins.
5. By using the permissions of the download folder as a flag for turning off the feature, we avoid introducing an extra server parameter. The folder is still created (read-only) by default, for the sole purpose of making it easier to locate.

Note: please discuss the patches on the relevant PRs or on separate issues.

**Comment by Yenthe666** [comment]
Hi @odony,

Just to be sure. Does this mean that an end user will never have the ability to install an app from the app store? It has to be added to the modules list of the Odoo server by an administrators?

**Comment by Targa-consult** [comment]
We rely on this to allow our non technical team to install modules in the field with ssh from the trusted store. Why do you need to deactivate it ?

**Comment by odony** [comment]
@Yenthe666 @Targa-consult  sorry for the misleading original description, I've clarified the description, and will link relevant PRs. If you don't mind I'd like to delete your early comments as they might bring confusion to the discussion. :confused:

**Comment by odony** [comment]
The relevant pull requests have been merged - installation packages will be updated shortly.
