### ISSUE TITLE
[10.0] Wrong Selected Field when Press Arrow Down Button on List View Editable

### ISSUE THREAD

**Issue by Elghard** [odoo/odoo#15238]
Impacted versions:
10.0 or maybe also 8.0 and 9.0
Steps to reproduce:
1. Create minimum 2 O2M Record on Tree List View
2. Press arrow down button on first record at any editable field
3. The focus cursor will be change to next record with same field focus
Current behavior:
- The next record field focus always the first field

Expected behavior:
- The next record field focus must be same as the last edited record field 

Please change code on web/static/src/js/views/list_view_editable.js:644

From: var options = { wraparound: !self.is_action_enabled('create') };
to: options.wraparound = !self.is_action_enabled('create');

because the new variable removed the focus_field key

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is working now the way you describe in latest v11 version (but maybe before), so it has been fixed meanwhile. I close this considering it fixed.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
