### ISSUE TITLE
Broken link for Documentation drop down item from profile picture in main screen

### ISSUE THREAD

**Issue by irwanambak** [odoo/odoo#152530]
Impacted versions: Latest free version

Steps to reproduce: Select Documentation in drop down menu from profile picture (top right) in main screen

Current behavior: Opens https://www.odoo.com/documentation/saas-17.1 - 404 Not Found

Expected behavior: Should open https://www.odoo.com/documentation/17.0/

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
Indeed, the link is right, but the documentation is not currently built for 17.1 right now. 
We'll make sure it is available in the coming days, thanks for reporting :-1:.

**Comment by irwanambak** [comment]
Link seems to be working now.
