### ISSUE TITLE
Qweb view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#15265]
Impacted versions:
odoo 10

Hi 
why this info raise when updating odoo 10 qweb views. first raise in this view in side report/website_layout.xml

`<template id="show_sign_in" customize_show="True" inherit_id="website.layout" name="Show Sign In">
    <xpath expr="//ul[@id='top_menu']" position="inside">
        <li class="divider" groups="base.group_public"/>
        <li groups="base.group_public">
            <a t-attf-href="/web/login">
                <b>Sign in</b>
            </a>
        </li>
    </xpath>
</template>`

```
@api.constrains('type', 'groups_id')
    def _check_groups(self):
        for view in self:
            if view.type == 'qweb' and view.groups_id:
                raise ValidationError(_("Qweb view cannot have 'Groups' define on the record. Use 'groups' attributes inside the view definition"))
```

constrains method in view.py 

can anyone please describe this why this happen, and what we need to do. as we are upgrading odoo 10 qweb views.

Thanks in advance

**Comment by JKE-be** [comment]
Please, check that you don't have any view of type qweb with a group ! Probably website.layout or an inherited view. It is no supported in v10 !

**Comment by bnisevic** [comment]
@JKE-be what to use instead? How to have groups working with website.layout?

**Comment by JKE-be** [comment]
@bnisevic

Using group on node directly :)
