### ISSUE TITLE
[9.0] Project demo data always installs

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#15262]
**Impacted versions:**
9.0

**Steps to reproduce:**
- The demo project called "Start here to discover Odoo" (xml_id: project.project_project_data) is currently located in the `project_data.xml` file
- Every time we update a client's server, the demo project reappears and we have to manually go to delete it
- Instead of the demo project being in `project_data.xml`, could you not move it into the `project_demo.xml` file?

**Current behavior:**
Demo project will always install even though the "Install demo data" checkbox is not ticked

**Expected behavior:**
Demo project should only install if "Install demo data" checkbox is ticked.

PS: I know it is a very small bug, but it is not correct behavior. One would not pick it up on Odoo Runbot, since demo data does indeed install on those instances.

**Comment by Yenthe666** [comment]
@mart-e could you give feedback please? I'm experiencing the same issue but I thought you commented somewhere else that there was a reason for this or am I wrong?

**Comment by mart-e** [comment]
Hello,

The project "Start here to discover Odoo" is a data, not a demo data, it is intended to help people starting to use Odoo.
To hide it, you need to archive it (`active=False`), this way it will not appear at the next update.

**Comment by adekock11** [comment]
Hi @mart-e. Thanks for the explanation

**Comment by guewen** [comment]
@mart-e wouldn't it be easier for end-users to add `forcecreate="0"` on the record so it isn't created again when deleted? I mean, this record is added to help users who start to use Odoo, the first reflex of any of them will be to delete it and be surprised when it comes back, to use the active flag is not an obvious action.

**Comment by mart-e** [comment]
@guewen oh look at that, I did not know about this attribute :smile: 
I have used it at 59a700c8e6c

**Comment by Yenthe666** [comment]
This really calls for  🎆.
Great improvement! @guewen thanks for the tip & @mart-e thank you for the merge.

**Comment by adekock11** [comment]
Great!!! Thank you guys 😃
