### ISSUE TITLE
Is it possible to print in kitchen by clicking order without POSBOX hardware ?

### ISSUE THREAD

**Issue by sajjidakr** [odoo/odoo#15271]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

We replied already on odoo/documentation-user#174
No it is not possible, we do not support ethernet printers.

**Comment by Yenthe666** [comment]
Hi @sajjidakr,

Thanks for your report. Please do fill in a more detailed report in the future.
Because this issue tracker is only for official bugs in the code and not questions I'm closing this. You can ask these questions on the official Help forums though (help.odoo.com).
P.S: I believe you need a PosBox.


Regards,
Yenthe

**Comment by alfieqashwa** [comment]
Hello @mart-e
I've read your comment about issue PoS order printer on https://github.com/odoo/documentation-user/issues/174

So, really, we need one posbox per printer? Is that means if I want to configure the ip address on order printer each for kitchen and bar, so i need one posbox for one printer ?

i am questioning again just for make sure. Thanks.

Regards,
Alfie Qashwa

**Comment by mart-e** [comment]
> So, really, we need one posbox per printer?

Yes. We may add support for different printers in the future but it is not the case so far.

I remind you that, if you want to make it yourself, a posbox is way [cheaper](http://uk.rs-online.com/web/p/processor-microcontroller-development-kits/8968660/) than a printer (and you could even reduce the price with a rpi 2).

**Comment by lukebranch** [comment]
@sajjidakr ,

Just a thought, although it is a community repo and nothing to do with the Odoo core you may want to take a look at the CUPS-based printing modules in this repo:

https://github.com/oca/report-print-send

I haven't tried them myself so I cannot vouch for their performance personally, so it would be best to test them extensively before putting them into a production kitchen/bar environment, however they should allow you to configure a CUPS server for printing directly to IP-based printers like you'd see in many of the current restaurant POS offerings out there.

If you're hosting Odoo off of a desktop computer in the restaurant's internal network I believe you could host the CUPS server on that machine and connect to the printers through the local network.

**Comment by TheCloneMaster** [comment]
We installed two PosBox instances in one PC , and played around with USB
printer selection on hw_escpos module...

And used an USB to Ethernet converter to be able to place the second
printer away in the kitchen...

Then, you just configure the receipt printer to one instance and the
kitchen printer to the other one...

Regards
Mario

El 27 feb. 2017 9:18 PM, "Luke Branch" <notifications@github.com> escribió:

@sajjidakr <https://github.com/sajjidakr> ,

Just a thought, although it is a community repo and nothing to do with the
Odoo core you may want to take a look at the CUPS-based printing modules in
this repo:

https://github.com/oca/report-print-send

I haven't tried them myself so I cannot vouch for their performance
personally, so it would be best to test them extensively before putting
them into a production kitchen/bar environment, however they should allow
you to configure a CUPS server for printing directly to IP-based printers
like you'd see in many of the current restaurant POS offerings out there.

If you're hosting Odoo off of a desktop computer in the restaurant's
internal network I believe you could host the CUPS server on that machine
and connect to the printers through the local network.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/15271#issuecomment-282930169>, or mute
the thread

**Comment by alfieqashwa** [comment]
@mart-e : I see. I have tried setting order printer with two printers with raspi2 and succeed. one question? have you tried with PiZero? 

thank you

Regards,
Alfie Qashwa

**Comment by mart-e** [comment]
> have you tried with PiZero?

No I haven't played with it. Maybe I will with the [new update](https://arstechnica.com/information-technology/2017/02/new-10-raspberry-pi-zero-comes-with-wi-fi-and-bluetooth/)

**Comment by alfieqashwa** [comment]
@mart-e, have you tried [the new update](https://arstechnica.com/information-technology/2017/02/new-10-raspberry-pi-zero-comes-with-wi-fi-and-bluetooth/) yet?

**Comment by mart-e** [comment]
@alfieqashwa no, no plan at the moment. The zero actually is not very suitable as will require more adapters.

**Comment by buddhiramsharma** [comment]
@mart-e its seeems like odoo dont want to provide this feature and to let the hardware POSBOX to be purchased. Its so simple option to enable this from your side BUT being open source its verysad BUG created by odoo.

Guys you can switch to Floreant POS its had this free feature.

Best.
Jerry

**Comment by mart-e** [comment]
@buddhiramsharma if it is so easy to enable network printers, please do submit a PR to change that, I would gladly look at it.

**Comment by JKirega** [comment]
Hi, i am more interested on adding names of the cashier on the order printout sent to the Kitchen Printers.
I need help in locating the template of the orders printout.
I have examined the point_of_sale>static>xml>pos.xml  but i have only managed to format the ones on the PosTicket receipt.
Kindly assist.

**Comment by chafarleston** [comment]
yes is possible there a program call Jposbox and not need a POSBOX

**Comment by chafarleston** [comment]
I use in the production client in kitchen mode and print order and invoice :)
http://jposbox.org/

**Comment by chafarleston** [comment]
@buddhiramsharma is a fake the odoo don't produce a rasperry. and you can make if you want your own POSBOX buying the product separatly

**Comment by aimejules** [comment]
Hi, it is possible to print receipt in Odoo Point of Sale without PosBox using these modules

https://apps.odoo.com/apps/modules/12.0/pos_network_printer for Pos retail and https://apps.odoo.com/apps/modules/12.0/pos_restaurant_network_printer for Pos restaurant

These modules (availaible for Odoo 10 - Odoo 11 - Odoo 12) lets you to connect directly your ESC/POS Network Printer to Pos and print receipt without PosBox. You can print from PC, smart phone or tablet to network printer. Follow the link for more details.

**Comment by chafarleston** [comment]
I use jposbox it is totally free. visit www.jposbox.org, don't pay anything

**Comment by chafarleston** [comment]
you can print , in a cell phone, tablet or any device. the jposbox use java, configure the printer using this modules of https://github.com/it-projects-llc/pos-addons. and working good, using  in more than 50 client, without problems.

**Comment by koz01** [comment]
No need to use posbox for this module: https://github.com/it-projects-llc/pos-addons?

**Comment by groupgloval** [comment]
I have a point of sale with pos_restaurant_network_printer and I need to modify the information printed on the ticket, for example I want the name of the product and the quantity to be centered, could someone tell me where I can find the file that contains that information? I imagine it is an .xml that is somewhere but I can not find it. Thank you.

**Comment by aimejules** [comment]
The module https://apps.odoo.com/apps/modules/12.0/pos_restaurant_network_printer don't cover the customisation of ticket. It's use to manage the network printer with Odoo. I think that you should use other module to customise it like this for example https://apps.odoo.com/apps/modules/12.0/pos_receipt_custom/

**Comment by arifmarias** [comment]
Hello, 
I need some good souls of Odoo community people, to help on Odoo printer issues. 
I have installed Odoo POS (for Restaurant) v12 on windows. 

Now, I have 3 printers. 
1 Connected with USB for Invoice Printing. Meaning when customer pay cash. Also Bill printer. 
2 Connected with network (IP) printer; one for Kitchen, one for Outside (Drinks). This two printers using for Order ticket printing.

Now, I am using JPosBox as suggested here 
But failed to do. If you can please give a step by step guideline to setup, that would be great. 
I am truly appreciate for response. 

Thank you in anticipation.

**Comment by arifmarias** [comment]
> you can print , in a cell phone, tablet or any device. the jposbox use java, configure the printer using this modules of https://github.com/it-projects-llc/pos-addons. and working good, using in more than 50 client, without problems.

Can you please give a step by guideline for 3 Printers setup. 
1 Connected with USB for Invoice Printing. Meaning when customer pay cash. Also Bill printer.
2 Connected with network (IP) printer; one for Kitchen, one for Outside (Drinks). This two printers using for Order ticket printing

Please help on this.

**Comment by Yenthe666** [comment]
@arifmarias this is not an issue, you just don't know how to implement it so it seems. You can ask these kind of questions on the official help forums (https://www.odoo.com/forum/help-1)

**Comment by arifmarias** [comment]
> @arifmarias this is not an issue, you just don't know how to implement it so it seems. You can ask these kind of questions on the official help forums (https://www.odoo.com/forum/help-1)

@Yenthe666  I have tried to post the same question in forum but there is an issue with Karma thing. Verified my email couple of time but didn't go through. 
And, Yes, I don't know how to implement this. That's why I am asking for you guys help. Otherwise, I shouldn't be posting here. if you can help please help. If you can't, then tell, we don't want to help you. Simple. 
Thanks Mate. .

**Comment by pedrobaeza** [comment]
@arifmarias this issue tracker is not for answering questions, but for reporting issues, so it's not a question of will, which Yenthe has a lot and answer thousand of questions in the forum. It's a question of where to do it.

The karma thing is a protection anti-spam, also for the good of all the users of the forum, so you are not doing correctly the verification if you still don't have karma.

You can also write on the mailing lists (https://odoo.com/groups) as an alternative.

**Comment by junmin** [comment]
@mart-e 

We are a Odoo SaaS customer, still no sign of supporting ethernet(network) printer? 

For us, it's important because we have multiple printers (ticket, bar, kitchen etc), as you said earlier in this thread, one posbox per printer, we really don't want to maintain so many posbox ...

it's better to keep things simple.

**Comment by aimejules** [comment]
@arifmarias  and @junmin 
I think that you can use theses modules and don't need PosBox. You can use UNLIMITED network printer
Pos retail : https://www.odoo.com/apps/modules/12.0/pos_network_printer
Pos restaurant : https://www.odoo.com/apps/modules/12.0/pos_restaurant_network_printer

If you want to use theses modules with Odoo Saas, you add theses :
Pos retail : https://www.odoo.com/apps/modules/12.0/pos_network_printer_online
Pos restaurant : https://www.odoo.com/apps/modules/12.0/pos_restaurant_online

Please email me aimejules1@gmail.com or skype aimejules01 and I send you documentation and vidéo for demo.  You have free support also to implement it.

Thanks

**Comment by junmin** [comment]
@aimejules 

Thanks. We saw it before, and we have some concerns about the module

1. It's not official, how well will its support in next versions of Odoo. Cause we use Odoo in real production environment, we don't want to have problems later.
2. Can we test it before buying it?

**Comment by aimejules** [comment]
@junmin 

I support it for next version. Theses modules are already available for Odoo 9,10,11,12 Community or Enterprise edition. You can test of course. Join me on Skype (aimejules01) or email me (aimejules1@gmail.com) for details.

Thanks

**Comment by mart-e** [comment]
@junmin I am not in the pos team so did not follow the development very closely but I think this feature has been implemented in the new [IoT Box](https://www.odoo.com/page/iot) (the replacement of the posbox). Maybe @qle-odoo can confirm that?
As you are a SaaS customer, feel free to [get in touch](https://www.odoo.com/help) with the support to have more information.

**Comment by elblasy33** [comment]
> you can print , in a cell phone, tablet or any device. the jposbox use java, configure the printer using this modules of https://github.com/it-projects-llc/pos-addons. and working good, using in more than 50 client, without problems.
dose  jposbox work on odoo 12 ?
if yes how?
do you have selution
thanks

**Comment by qle-odoo** [comment]
@junmin 
In the next version of Odoo you will be able to use all the printers present in the network with only one IoT Box.
All printers will be installed automatically but configurable if you want. (if you need specific driver for a printer)

**Comment by Mustafa-Jumma** [comment]
@qle-odoo 
Is it going to support Arabic language , because as for now kitchen ticket which printed through POSBOX.

**Comment by qle-odoo** [comment]
@Mustafa-Jumma 
So yes all languages supported by Odoo will also be on the IoT Box.
(The IoT box is only the new name of the POSBOX)
