### ISSUE TITLE
Error on confirm sale website_delivery module

### ISSUE THREAD

**Issue by idncom** [odoo/odoo#15278]
Impacted versions:
10 Enterprise
Steps to reproduce:
1. Create a subscription contract template
2. Create a subscription product
3. Create a quote
4. Remove Quotation Template and select contract template
5. Confirm sale

Current behavior:
Error as shown in attachment, no delivery order.

Expected behavior:
No error, and delivery order created.

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/5899297/22443775/bf8be748-e705-11e6-9dfd-58557abd90fc.png)

**Comment by idncom** [comment]
This is another developers module, sorry I thought it was part of Odoo

**Comment by Yenthe666** [comment]
Thank you for identifying this yourself. 👍
