### ISSUE TITLE
Related stored fields not updated

### ISSUE THREAD

**Issue by JonathanStein** [odoo/odoo#15289]
Impacted versions:
8 and 9 (works in 10, not tested with earlier versions)

Steps to reproduce:
1). Log in to a fresh install with demo data. Find a res.partner that also has a res.company (e.g. "Odoo BE" in 8 or "YourCompany" in 9).
2). Change address, phone and email and save the data.
3). Look up the corresponding res.company.

Current behavior:
The related, but not stored address fields will show the changed data. The related and stored fields "phone" and "email" are not updated.

Expected behavior:
The related fields should have been updated.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @JonathanStein,

Thanks a lot for your bug report.
As you've mentioned this has been fixed in 10 and up and as V9 is quite far towards the end of life this wouldn't be changed anymore as it can change custom development on instances.

Regards,
Yenthe
