### ISSUE TITLE
Wkhtmltox does not install on Ubuntu 14.04

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#15282]
Following the advice in the docs, I tried installing the wkhtmltox 0.12.1.2 deb package at http://nightly.odoo.com/extra/, but it is missing a `libjpeg62-turbo` dependency:

```
$ sudo dpkg -i wkhtmltox-0.12.1.2_linux-jessie-amd64.deb
(Reading database ... 73848 files and directories currently installed.)
Preparing to unpack wkhtmltox-0.12.1.2_linux-jessie-amd64.deb ...
Unpacking wkhtmltox (0.12.1.2) over (0.12.1.2) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on libjpeg62-turbo; however:
  Package libjpeg62-turbo is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 wkhtmltox
```

It this package outdated?
What do you advise?

**Comment by Yenthe666** [comment]
@sle-odoo could you give feedback?

**Comment by leangjia** [comment]
@dreispt 
Try this URL：http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/

**Comment by dreispt** [comment]
@leangjia Thanks, that works. My main point is that the official documentation / Odoo "extra" repo are outdated or misleading.

**Comment by Yenthe666** [comment]
@dreispt could you link to the docs? Is this still the case? Otherwise I'll fix it.

**Comment by dreispt** [comment]
I think the instructions at http://www.odoo.com/documentation/10.0/setup/install.html#setup-install-source are correct now.
