### ISSUE TITLE
Add POS modifiers for products

### ISSUE THREAD

**Issue by multiwebinc** [odoo/odoo#15280]
This is a feature request. Allow modifiers for restaurant products. 

For example, some items have different ways to be prepared, like the type of sauce on your chicken wings, choice of salad dressing, how cooked you want your meat, how you want your eggs done, pizza toppings, etc. 

Another example would be where the client is able to pick any 3 out of a list of 10 options.

In these cases, adding a note on the ticket would be impractical, and even impossible if inventory needs to be depleted.

Another example would be allowing the server to modify ingredients, like "extra ..." or "no ...", however in this case it might be better to simply add a note, unless this is something that happens frequently.

A minimum and maximum number of modifiers should also be specified. So if the server needs to choose exactly 3 modifiers from the list, the system should disallow anything other than 3.

**Comment by multiwebinc** [comment]
Someone apparently created this for version 7, however it doesn't appear they ever released the source code. You can see an example here: https://www.youtube.com/watch?v=vXeETb_f8Ws (at 3 minutes)

**Comment by jorenvo** [comment]
@multiwebinc thank you for your input. I can't tell from your message if you're aware already or not, but we do have a note feature for items that are sent to the kitchen (with the order button). This would probably be the best way to handle the following things you mention:

> For example, some items have different ways to be prepared, like the type of sauce on your chicken wings, choice of salad dressing, how cooked you want your meat, how you want your eggs done, pizza toppings, etc.

But indeed, handling modfiers is something that we currently don't support. We will consider it for the future versions of Odoo.

**Comment by multiwebinc** [comment]
@jorenvo That's what I meant by:

> In these cases, adding a note on the ticket would be impractical, and even impossible if inventory needs to be depleted.

For example, a bar that has a 2 beers for $5 special, but the bar has 10 types of beer. Right now you could add a "Beer special" product and the server could choose that product and add a note which beers are in each order by manually typing in a note, however this would be very time consuming, error prone, and would not deplete the inventory for the beers actually ordered.

**Comment by wtaferner** [comment]
@multiwebinc 
Why would you do such a thing...instead I would just change the price of the correct beer ordered and the inventory would be perfectly fine and no note would be neede...but maybe I don't get your requirement and besides that a note is of course a good thing for future versions anyway.

**Comment by multiwebinc** [comment]
@wtaferner You're right. You could add a product for each option. But take for example a bar sells 1 beer for $3.50 or 2 for $5. I'm assuming the most common way to do that would be to add a "Beer special" product with a price of $5 and then for each type of beer you would have a $3.50 item to be used when sold individually and a $0 item to go with the special. What prevents a server from punching in a $0 beer without the "Beer special" product and therefore giving away free beer? Or maybe they punch in 3 free beers instead of 2.

Please keep in mind I'm definitely NOT recommending getting rid of the notes.

**Comment by wtaferner** [comment]
@multiwebinc 
Well, it is all about configuration and the knowledge what a configuration or use case implies for the rest of the ERP applications. There are plenty of solutions which would be correct for your use cases stated...you just need to thoroughly think about the implications. And for sure your suggestion for modifiers has its legitimate point of view. Let's see if Odoo will take it into new versions or maybe you can even contribute them your own to the master branch (be sure that it is going to be accepted as a concept first or that you are determined about your actions to contribute no matter what)

**Comment by pedrobaeza** [comment]
Closing this as answered with several options.

**Comment by neozeed** [comment]
modifiers go in stacks. plain coffee set price, add specialized milk, add a price.  Just as alacarte pizza is pay per topping, so you need modifiers.
