### ISSUE TITLE
No active in advange search in module HRM v8

### ISSUE THREAD

**Issue by witowito** [odoo/odoo#1528]
When you make  a employee inactive in the HRM module, there is no active is true or untrue anymore in the advange search to show them, and to make them active again.

**Comment by Yenthe666** [comment]
Hi @witowito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
