### ISSUE TITLE
[9.0c/9.0e] Sales > Products > Filters >> Products - Displays Consumable Products Only *Behaviour differs from 8.0 and 10.0

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#15296]
<h1>Environment:</h1>
Latest Runbots

<h1>Impacted versions:</h1>
9.0 Community<br/>
9.0 Enterprise

<h1>Steps to reproduce:</h1>
<ol>
<li>Login to latest 9.0c or 9.0e runbot build.</li>
<li>Sales > Products > Filters >> Products</li>
</ol>

<h1>Current behavior:</h1>
Displays 'Consumable' product type only

<h1>Expected behavior:</h1>
Should display Consumable & Stockable products as was the behaviour prior to 9.0 (see 8.0 runbots for example) and after 9.0 (see 10.0 runbots for example).

<h1>Video/Screenshot link (optional):</h1>
<img src="https://cloud.githubusercontent.com/assets/2337666/22494521/1caa9190-e873-11e6-870d-c3ec76817243.png"/>

<h1>Extra Info:</h1>
As far as I can tell here's the affected line in the view for version 9.0:
<a href="https://github.com/odoo/odoo/blob/9.0/addons/product/product_view.xml#L40">https://github.com/odoo/odoo/blob/9.0/addons/product/product_view.xml#L40</a>

and here's the line in version 10.0 with what is in my mind the correct behaviour:
<a href="https://github.com/odoo/odoo/blob/10.0/addons/product/views/product_views.xml#L107">https://github.com/odoo/odoo/blob/10.0/addons/product/views/product_views.xml#L107</a>

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sorry to ping you on this. We've had a number of enterprise customers complain about this issue, and I believe this is not the intended behaviour and should therefore be classified as a bug only present in the 9.0 community and enterprise branches.

**Comment by mart-e** [comment]
Hello,

In 8.0, the filter was also [on consumable only](https://github.com/odoo/odoo/blob/8.0/addons/product/product_view.xml#L15).
We changed that in 10.0 but I think the patch e64fb376798244419fe87f076d5c103ff51c747c is not correct either. If you want to change the filter, to include stockable products, it should be done via an xpath in the stock module, not product.

PR welcome

**Comment by lukebranch** [comment]
@mart-e ,

Thank you for taking the time to look into this. 

Yes, the filters in 8.0 are separated by Product, and Consumable, my apologies for the oversight there.

Regarding a PR should I target both 9.0 and Master?

**Comment by mart-e** [comment]
Adding an xpath in stock to modify the filter could be done in 9.0 I think

**Comment by Yenthe666** [comment]
@mart-e shouldn't we change this in 9.0 ourselves then?

**Comment by pedrobaeza** [comment]
@mart-e any news about this?

**Comment by mart-e** [comment]
Sorry but the 9.0 is now in end of life, we no longer accept changes for non-critical bug fixes.
