### ISSUE TITLE
Not everyone should be able to access debug mode

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#15294]
**Impacted versions:**
v10_community, possibly more

**Steps to reproduce:**
Create a user with minimum rights, log in and put `debug=assets` on the url. You will be able to enter debug mode.

**Current behavior:**
A user that does not belong to Administration / Settings group is able to access the debug mode.

**Expected behavior:**
Only users that belong to the Administration / Settings group should be able to access the debug mode since the Enter Debug Mode is shown on the Settings Dashboard.

**Comment by gdgellatly** [comment]
I'm not convinced. It is nice for ui bugs when doing user support and also
last I checked was the only way a regular user can set their own defaults.
So such a change would remove 2 useful features.
