### ISSUE TITLE
Clicking on Upgrade redirects to Discuss [odoo 10]

### ISSUE THREAD

**Issue by ydaniels** [odoo/odoo#15295]
Impacted versions:
Odoo Server 10.0-20170126 
Steps to reproduce:
Developing a module and clicking on upgrade 
Current behavior:
it redirects to discuss page
Expected behavior:
It should not redirect to discuss page . It should stay on the same page so i can keep working on module and easily upgrade anytime, since odoo is not  nice when it comes to automatically detecting file changes on the fly.
 Previous versions odoo 9 ,8 does not have this problem. It is stressful to click on app and look for  the module you are currently working on. 

Video/Screenshot link (optional):

**Comment by dvdhinesh** [comment]
I have faced this issue also. But not sure whether it is an intended behavior or not.

**Comment by Yenthe666** [comment]
@mart-e any feedback from your side? 😉

**Comment by mart-e** [comment]
Hello,

> since odoo is not nice when it comes to automatically detecting file changes on the fly

You know we have a [--dev option](https://www.odoo.com/documentation/10.0/reference/cmdline.html#cmdoption-odoo-bin--dev) for that, right? Or you can also just upgrade using `-u`.

> Previous versions odoo 9 ,8 does not have this problem. 

No it did but a bit different..

> But not sure whether it is an intended behavior or not.

Yes it is.

When you upgrade a module, you need to reload the full web client (to get new actions, new assets,...) and we go to `/web` page. If you are in community, it is the first app (probably Discuss), in enterprise, it is the app switcher.

In v9, it executed an `ir.actions.todo` (e.g. redirecting to project menu if you upgrade project) and, reloaded the page and going back to the module page if no todo was defined.
In v10, the `ir.actions.todo` have been removed and you are redirected to the home page.

Sorry but the scenario of the developer upgrading the module all the time is not the targeted scenario. What we want, is to make it easy for the users, which rarely need to install/upgrade many time the same module.

As a developer, you should use dev mode or upgrade command.
