### ISSUE TITLE
Access computed field in decoration-{} on temporary record

### ISSUE THREAD

**Issue by lonavera** [odoo/odoo#15300]
Impacted versions:
odoo 10

Steps to reproduce:
Happens in my custom addon and I currently have no example in a standard addon.

Current behavior:
I use a computed field in a decoration-{} attribute of an tree of model B. The tree is displayed embedded in the form of model A. If I edit a record of type A and add a new entry of type B to the list, I got the exception 

Error: NameError: name 'is_ok' is not defined

http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:1326
Zurückverfolgung
PY_ensurepy@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:1326:65
py.evaluate@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:1441:8
py.evaluate@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:1442:102
ListView<.compute_decoration_classnames/<@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:2024:604
_.forEach@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:12:650
ListView<.compute_decoration_classnames@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:2024:539
anonymous@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js line 2949 > Function:8:56
._render@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2948:262
QWeb2.tools.call@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2918:8
anonymous/<@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js line 2949 > Function:8:10
QWeb2.tools.foreach@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2919:18
QWeb2.tools.foreach@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2920:1
anonymous@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js line 2949 > Function:6:25
._render@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2948:262
.render@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:2948:146
ListView.List<.render@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:2070:144
ListView.Groups<.render_dataset/</<@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:2087:41
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:542:467
.Deferred/promise.then/</<@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:547:631
.each@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:370:758
.Deferred/promise.then/<@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:547:553
.Deferred@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:548:189
.Deferred/promise.then@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:547:518
ListView.Groups<.render_dataset/<@http://localhost:8069/web/content/721-197eeb1/web.assets_backend.js:2085:1294
.Deferred/promise.then/</</<@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:548:31
async_when/</action@http://localhost:8069/web/content/251-36cc43f/web.assets_common.js:3223:143

That is because in that new record, that is not currently saved the context of the python evaluation does not contain that computed field.

Expected behavior:
No exception and handling of the computed field as None.

Video/Screenshot link (optional):

**Comment by bokbokan** [comment]
Since **display_name** for new record is False, currently I'm using this workaround
`decoration-{} ="display_name and computed_field oper value"`.
This works for me, hope this help in your case.

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
