### ISSUE TITLE
CRM Stages - Type is missing in 10

### ISSUE THREAD

**Issue by gokhanerdogdu** [odoo/odoo#15316]
Hi,

In V9, it was possible to define different stages for Leads and Opportunities by using the Type field on stage creation form. Now, this field does not exist in V10 and it is not possible to define different stages for Leads and Opportunitities. Why was this functionality removed in V10? What is the thought behind it?

Impacted versions:V10

Steps to reproduce: Check the Stages on CRM Settings

Current behavior: Type does not exist on the Crm stage form.

Expected behavior: In order to define different stages for leads and opportunities, there should be Type field as it was in V9.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello @gokhanerdogdu 

A lead is a first contact, once you get in touch or decide to make something with this lead it should become an opportunity.

So in V10, it has been decided to remove the stage notion in Lead.
So all the stage that you create are only for opportunity.

Lead has no more the notion of stage.

Best regards

**Comment by gokhanerdogdu** [comment]
According to our experience with our CRM customers and ourselves, sometimes it is needed to define process for lead followup. For example, all leads are assigned to someone and the first stage is new. When he/she contacts the lead with no result yet, the stage should be Contacted, No Result Yet.  After first real contact, the lead may say to call/email next week, then the stage should be Recontact. This process can be extended according to the needs of the users. We can do this by adding new property to the lead card, but I think this functionality should be available as a standard and users may/may not use the functionality as in V9.
