### ISSUE TITLE
binary field attachment=True breaks deletion of content for portal user

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#15311]
**Impacted versions:**

v9 (tested) and very likely v10

**Steps to reproduce:**

* create a model "MyModel" and provide CRUD permissions to portal user
* add a binary field (like an image) to it
```
image = fields.Binary(
    "My image",
    attachment=True,
)
```
* login w/ a portal user
* create a record of MyModel **w/out an image**
* delete the record: it works
* create another record **w/ an image**
* delete the record:  BAM! 403!

**Current behavior:**

The employee check added in [this fix](https://github.com/odoo/odoo/commit/eb9113c04d66627fbe04b473b9010e5de973c6aa)  prevents the deletion if you are not an employee. The `requires_employee` is activated because the main object is deleted before the attachment.

**Expected behavior:**

Since the user has all the permission to manage the content I'd expect the attachment field to behave in the same way. Right now the only solution I found to this is to flush the binary field content before deletion, like:

```
@api.multi
def unlink(self):
    # drop image attachments before deletion
    self.write({'image': False})
    res = super(MyModel, self).unlink()
    return res
```

**Comment by pedrobaeza** [comment]
@simahawk is this still happening?

**Comment by simahawk** [comment]
@pedrobaeza sadly, yes (I had to report on this again).
Here's my current hack
https://github.com/OCA/website-cms/pull/41/files#diff-04cbabe706a0745ca346ccf51dfbeb0eR138
If I remove it this test will fail
https://github.com/OCA/website-cms/pull/41/files#diff-b537567d957198635b927bd11511b824R83

**Comment by pedrobaeza** [comment]
@beledouxdenis you were the one that made the fix. Can you check this side effect?

**Comment by Yenthe666** [comment]
Hi @simahawk,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by simahawk** [comment]
@Yenthe666 hi, as I reported on https://github.com/odoo/odoo/issues/15311#issuecomment-387646620 the answers is: yes, it's still happening. I have to check on v12 tho.
