### ISSUE TITLE
[10.0][google_spreadsheet] Google Spreadsheet unnecessarily slow (getScriptProperty bug)

### ISSUE THREAD

**Issue by NeoPolus** [odoo/odoo#15329]
Impacted versions: 10.0 (and previous)

Steps to reproduce:
- Install google_spreadsheet module on Odoo 10.
- Go to partners list (or any list).
- Create a new search view (i.e. filter the list by "Customer")
- Use the "Add to Google Spreadsheet" action of the search view (in the Favourites drop down menu).
- It creates a new Google Docs SpreadSheet, for the current search view, based on this template: https://docs.google.com/spreadsheet/ccc?key=1KUlSSzZMzkEEzyroyZ2NerRt1RVCspkG9VQIh2V6dnM

Current behavior:
- The created spreadsheet script code uses the _getScriptProperty_ function on several places to ensure that the property we want to get is already available.
- Currently _getScriptProperty_ always halts the execution, waiting for a random time up to 2.95 seconds, each time it is called to get a property value, even if the property was already available.

Expected behavior:
- _getScriptProperty_ should only wait if the property we want to read is not available.

**Comment by NeoPolus** [comment]
Currently the getScriptProperty code looks like this:

```
function getScriptProperty(key) {
  var FailLimit = 100;
  var RetryInterval = 50;
  var ScriptPropertyValue = "";
  var Retries=0;
  var randomnumber = 0;
  var TryAgain=true;
  while (TryAgain)
  {
    Retries++;
    randomnumber=Math.floor(Math.random()*59);
    Utilities.sleep(randomnumber*RetryInterval);
    Logger.log(randomnumber*RetryInterval);
    try
    {
      TryAgain=false;
      ScriptPropertyValue = ScriptProperties.getProperty(key);
    }
    catch(err)
    {
      TryAgain = (Retries<FailLimit);
```

It should be completely rewritten (as it is a mess), but meanwhile it at least needs this change (to increment the retry counter and sleep *only* if the __try__ failed)

```
function getScriptProperty(key) {
  var FailLimit = 100;
  var RetryInterval = 50;
  var ScriptPropertyValue = "";
  var Retries=0;
  var randomnumber = 0;
  var TryAgain=true;
  while (TryAgain)
  {
    try
    {
      TryAgain=false;
      ScriptPropertyValue = ScriptProperties.getProperty(key);
    }
    catch(err)
    {
      TryAgain = (Retries<FailLimit);
      Retries++;
      randomnumber=Math.floor(Math.random()*59);
      Utilities.sleep(randomnumber*RetryInterval);  // We only sleep when retrying
      Logger.log(randomnumber*RetryInterval);
```

**Comment by Yenthe666** [comment]
@KangOl and @beledouxdenis since you guys made some PR's on this module. Can one of you two look at this perhaps?

**Comment by Yenthe666** [comment]
Hi @NeoPolus,

Are you talking about the JS file? As you can see it is no longer there:
https://github.com/odoo/odoo/blob/d0dbd570b628cc82183ddec6b78a49c88d4f12ef/addons/google_spreadsheet/static/src/js/search.js#L1-L49

If I'm wrong then please do add more information.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in quite a while.

Regards,
Yenthe
