### ISSUE TITLE
Inconsistency between Products and POS (Lot No doesn't work correctly for Decimal quantities)

### ISSUE THREAD

**Issue by kunalgoel1** [odoo/odoo#15325]
Impacted versions: v.10

Steps to reproduce:

1. Create a new Product and tick the tracking by lots option under the inventory tab.
2. Select UOM as kg in the product master.
3. Add some quantity for this product by entering a Goods Receipt Entry and also mentioning the lot number.
4. Open the Point of Sale App and start a new session.
5. Select this product and enter quantity in Decimal points as 1.5kg
6. Now it will ask "Lot/Serial No. Required" with two single line boxes.
7. Once you enter the Lot numbers in both the boxes and select "OK".
8. Quantity changes to 2.0kg.

Current behavior:
When lot numbers are entered, the quantity changes from decimal quantity to the closest Whole number quantity. In the above instance it changes to 2.0kg.

Expected behavior: 
There should be different manner for tackling serial numbers and Lot numbers. The current system is good for Serial Numbers. But when the tracking is enabled "By Lots" in the product page, then it should have a different mechanism.

When a product is selected which has tracking by lots, then it should ask for Lot No. at once and the same lot number be applied to the total quantity in that invoice item line. If two lots of a product are to be billed then they can be done in two separate billing lines. Also I would suggest that Lot No. drop-down list should be shown with lot nos having quantity available for that particular product.

Video/Screenshot link (optional):
[odoo pos qty lot.zip](https://github.com/odoo/odoo/files/749689/odoo.pos.qty.lot.zip)

**Comment by HerrKorn** [comment]
+1

**Comment by kunalgoel1** [comment]
@Yenthe666 
Can you help resolve this issue.

**Comment by Yenthe666** [comment]
@jorenvo could you look at this? It looks like an inconsistency between products / POS.

**Comment by Karyfars** [comment]
+1

**Comment by Yenthe666** [comment]
Hi,

This should have been handled in https://github.com/odoo/odoo/commit/025d9432a1dfc1db484e9e65d2748ed91d67ca26, https://github.com/odoo/odoo/commit/99deebe0154311a254141c54a8336b4a3f4add26, https://github.com/odoo/odoo/commit/283f8df95bf5d63dbbf5b8c109c996bbb7ed0f42 and https://github.com/odoo/odoo/commit/d5908083b4c4cdfb34bbdd8e381c1e419c094702
Please update your Odoo source code to the latest version in order to fix this.

Regards,
Yenthe
