### ISSUE TITLE
[17.0] Wrong Lot is consumed in the Picking Generated from POS

### ISSUE THREAD

**Issue by burhan-aktivsoftware** [odoo/odoo#153393]
Impacted versions: 17.0  Community and Enterprise

Steps to reproduce:
**Purchase a Lot tracked Product. I created 3 Lots in the system for a Product called "Charger".**
![image](https://github.com/odoo/odoo/assets/39292897/dabae793-fbf3-4f67-863b-15ced7fbebb2)

**Go to POS and select Charger to sell. I entered LOT0003 to sell.**
![image](https://github.com/odoo/odoo/assets/39292897/bb741319-aec5-4082-8d10-b21527f4bd28)

![image](https://github.com/odoo/odoo/assets/39292897/1043979c-4547-4770-9847-654d8d05f104)

**Process the Order Successfully and Close the POS Session.**

**Go to the session in the backend and View the Order. LOT0003 is successfully registered in the Order line.**
![image](https://github.com/odoo/odoo/assets/39292897/c88ef608-6411-4a3c-a859-a9e5d5e268d0)

**Now Check the Picking which is generated on the session,**
![image](https://github.com/odoo/odoo/assets/39292897/6477f41b-80fa-4e06-8c69-1f686a419787)

**On the Picking Check the Stock move Line. It consumed wrong LOT0001 which must be LOT0003 actually.**
![image](https://github.com/odoo/odoo/assets/39292897/eecce858-e6e5-468f-bf87-aa302dca2ec1)

Current behavior:
When the User selected LOT0003 in POS, Odoo is automatically changing the lot to LOT0001 during inventory posting.

Expected behavior:
LOT0003 must be posted in the inventory. Odoo v16 is not having this issue. 

@yoba-odoo @robinengels If you can check and kindly help on this.

**Comment by robinengels** [comment]
Hello, could you create a ticket about this in Odoo ? Thanks

**Comment by burhan-aktivsoftware** [comment]
Hey @pedrambiria, Will it be possible for you to get a look into this issue?

**Comment by burhan-aktivsoftware** [comment]
This issue is fixed using the below Pull Request:
https://github.com/odoo/odoo/pull/148517
