### ISSUE TITLE
[10.0][google_spreadsheet] Google Spreadsheet script deprecated code (Utilities.json*)

### ISSUE THREAD

**Issue by NeoPolus** [odoo/odoo#15330]
**Impacted versions:** 10.0 (and previous)

**Steps to reproduce:** 
- Install _google_spreadsheet_ module on Odoo 10.
- Go to partners list (or any list).
- Create a new search view (i.e. filter the list by "Customer") 
- Use the "Add to Google Spreadsheet" action of the search view (in the Favourites drop down menu).
- It creates a new Google Docs SpreadSheet, for the current search view, based on this template: https://docs.google.com/spreadsheet/ccc?key=1KUlSSzZMzkEEzyroyZ2NerRt1RVCspkG9VQIh2V6dnM 
- Go to the script code editor

**Current behavior:**
- The created spreadsheet script code uses several deprecated (json) functions. Like _Utilities.jsonParse_ and _Utilities.jsonStringify_

Expected behavior:
- It should use the new recommended alternative (_JSON.stringify_, _JSON.parse_).

**Comment by pedrobaeza** [comment]
@odony any news about this?

**Comment by odony** [comment]
Should be fixed now, we can close it, thanks!
