### ISSUE TITLE
Migrate modules to 17 version (odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.)

### ISSUE THREAD

**Issue by xFingerlinKx** [odoo/odoo#153384]
Impacted versions:17

Steps to reproduce: Odoo.sh -> Upgrade button

Current behavior: Got errors in process of automatic migration from odoo 14 to odoo 17:
`2024-02-09 07:57:58,944 20946 ERROR db_1326679 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('purchase.menu_procurement_management_supplier_name', 363, 'Purchase > Orders > Vendors', 290) to the failing menus 
Traceback (most recent call last):
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 424, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3538, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1156, in __get__
    return self.convert_to_record(value, record)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 4235, in convert_to_record
    corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6101, in <lambda>
    func = lambda rec: any(rec.mapped(name))
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6079, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1281, in mapped
    self.__get__(first(remaining), type(remaining))
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Admin (id=2) doesn't have 'read' access to:
- Attachment (ir.attachment)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.`

`2024-02-09 07:57:44,398 20946 ERROR db_1326679 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('sale_crm.sale_order_menu_quotations_crm', 418, 'CRM > Sales > My Quotations', 552) to the failing menus 
Traceback (most recent call last):
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 424, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3538, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1156, in __get__
    return self.convert_to_record(value, record)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 4235, in convert_to_record
    corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6101, in <lambda>
    func = lambda rec: any(rec.mapped(name))
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6079, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1281, in mapped
    self.__get__(first(remaining), type(remaining))
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field
    self.fetch(fnames)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.

Sorry, Admin (id=2) doesn't have 'read' access to:
- Attachment (ir.attachment)

If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.`

Expected behavior:

Video/Screenshot link (optional):
I assume the problem is the use of multiple groups in the parent menus.
![Screenshot from 2024-02-09 12-20-14](https://github.com/odoo/odoo/assets/43288702/385f9f7e-0aeb-4507-8399-f88ce5ed12d3)
![Screenshot from 2024-02-09 12-20-35](https://github.com/odoo/odoo/assets/43288702/852796a6-8f30-4250-a7fb-aed5c3e6a8b1)

Support ticket number submitted via odoo.com/help (optional):

**Comment by mikhail-trunks-silao** [comment]
How did you fix this? I'm having the same problem right now with but with "product.product" model.

**Comment by xFingerlinKx** [comment]
@mikhail-trunks-silao I think the issue with multiple groups in the parent menus is not the reason. In my case it were thr attachments that had `res_id` but hadn't `res_model`.

**Comment by adolfoyanes** [comment]
hello @xFingerlinKx , thanks for sharing. I am having the same issue with product.product model. How did you found out that it was attachments that had res_id but did not have res_model ?

**Comment by anil-pattel136** [comment]
> Impacted versions:17
> 
> Steps to reproduce: Odoo.sh -> Upgrade button
> 
> Current behavior: Got errors in process of automatic migration from odoo 14 to odoo 17: `2024-02-09 07:57:58,944 20946 ERROR db_1326679 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('purchase.menu_procurement_management_supplier_name', 363, 'Purchase > Orders > Vendors', 290) to the failing menus Traceback (most recent call last): File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu self.mock_action(action_vals) File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action mock_method(model, view, fields_list, domain, group_by) File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 424, in mock_view_form [data] = record.read(fields_list) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3538, in read return self._read_format(fnames=fields, load=load) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format vals[name] = convert(record[name], record, use_display_name) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in **getitem** return self._fields[key].**get**(self, self.env.registry[self._name]) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in **get** return super().**get**(records, owner) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1156, in **get** return self.convert_to_record(value, record) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 4235, in convert_to_record corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in filtered return self.browse([rec.id for rec in self if func(rec)]) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in return self.browse([rec.id for rec in self if func(rec)]) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6101, in func = lambda rec: any(rec.mapped(name)) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6079, in mapped recs = recs._fields[name].mapped(recs) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1281, in mapped self.**get**(first(remaining), type(remaining)) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in **get** recs._fetch_field(self) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field self.fetch(fnames) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch raise self.env['ir.rule']._make_access_error('read', forbidden) odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.
> 
> Sorry, Admin (id=2) doesn't have 'read' access to:
> 
> * Attachment (ir.attachment)
> 
> If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.`
> 
> `2024-02-09 07:57:44,398 20946 ERROR db_1326679 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('sale_crm.sale_order_menu_quotations_crm', 418, 'CRM > Sales > My Quotations', 552) to the failing menus Traceback (most recent call last): File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu self.mock_action(action_vals) File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 395, in mock_action mock_method(model, view, fields_list, domain, group_by) File "/tmp/tmpatsfopkp/migrations/base/tests/test_mock_crawl.py", line 424, in mock_view_form [data] = record.read(fields_list) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3538, in read return self._read_format(fnames=fields, load=load) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3749, in _read_format vals[name] = convert(record[name], record, use_display_name) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6590, in **getitem** return self._fields[key].**get**(self, self.env.registry[self._name]) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2893, in **get** return super().**get**(records, owner) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1156, in **get** return self.convert_to_record(value, record) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 4235, in convert_to_record corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in filtered return self.browse([rec.id for rec in self if func(rec)]) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6102, in return self.browse([rec.id for rec in self if func(rec)]) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6101, in func = lambda rec: any(rec.mapped(name)) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6079, in mapped recs = recs._fields[name].mapped(recs) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1281, in mapped self.**get**(first(remaining), type(remaining)) File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1182, in **get** recs._fetch_field(self) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3775, in _fetch_field self.fetch(fnames) File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3831, in fetch raise self.env['ir.rule']._make_access_error('read', forbidden) odoo.exceptions.AccessError: Uh-oh! Looks like you have stumbled upon some top-secret records.
> 
> Sorry, Admin (id=2) doesn't have 'read' access to:
> 
> * Attachment (ir.attachment)
> 
> If you really, really need access, perhaps you can win over your friendly administrator with a batch of freshly baked cookies.`
> 
> Expected behavior:
> 
> Video/Screenshot link (optional): I assume the problem is the use of multiple groups in the parent menus. ![Screenshot from 2024-02-09 12-20-14](https://github.com/odoo/odoo/assets/43288702/385f9f7e-0aeb-4507-8399-f88ce5ed12d3) ![Screenshot from 2024-02-09 12-20-35](https://github.com/odoo/odoo/assets/43288702/852796a6-8f30-4250-a7fb-aed5c3e6a8b1)
> 
> Support ticket number submitted via odoo.com/help (optional):

Are you able to fix this issue?
