### ISSUE TITLE
Odoo Crash from mail_message failed to backup database too.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15339]
Impacted versions: 9.0, 10.0

Steps to reproduce: Noramal CRM and Mail to lead configured 

Current behavior: Failed even when dump for backup
Error:pg_dump: Dumping the contents of table "mail_message" failed: PQgetResult() failed.pg_dump: Error message from server: ERROR:  missing chunk number 0 for toast value 148458 in pg_toast_18366pg_dump: The command was: COPY public.mail_message (id, create_date, write_date, mail_server_id, write_uid, subject, create_uid, parent_id, subtype_id, res_id, message_id, body, model, record_name, no_auto_thread, date, author_id, type, reply_to, email_from, link_ebf, guid, type_email) TO stdout;

Expected behavior: Stability

I had backup with different commands and restored database, but normal backup failed.

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as @tejastank has been blocked from the Odoo repository.
An official response can be found on the thread https://github.com/odoo/odoo/issues/7466#issuecomment-378920731, to quote @mart-e:

> Due to the repeated aggressive tone (#16056 (comment), #8514 (comment), #1880 (comment), #7019 (comment), #7085 (comment)...) with the one that are trying to help you or just failing to give useful information to a point beyond bad faith (#10931 (comment), #3443 (comment), #4544 (comment),...), @tejastank is now blocked on the Odoo repository.
I was hoping we could manage a solution but, after almost 4 years, it seems sadly that we can not discuss constructively with him.
