### ISSUE TITLE
Price Type for Expenses

### ISSUE THREAD

**Issue by luanaduarte** [odoo/odoo#15345]
Impacted versions:  7.0 and 8.0

Steps to reproduce:

1. Install hr_expense

2. Create a _Product Category_ to be used for the _Expense Categories_ 

3. Create a _Expense Category_ using the above _Product Category_

4. Create 2 _Price Types_ of _Product Field_ "Cost", in two **different currencies** (BRL and USD, for example)
 >>> Create USD in first position, BRL in second position

5. Use the BRL _Price Type_ in a price list which applies for _Product Category_ Expense

6. Create a _Expense_ using the _Expense Category_ previously created

Current behavior: 

It considers the Price Type USD

It happens because the code is limited to the Price Type in the first position

price_type_id = pricetype_obj.search(cr, uid, [('field','=',ptype)])[0]

Expected behavior:

It should consider the Price Type defined in the price list

**Comment by luanaduarte** [comment]
@sadamo

**Comment by Yenthe666** [comment]
Hi @luanaduarte ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
