### ISSUE TITLE
project_timesheet makes imposible inheritance of project.task

### ISSUE THREAD

**Issue by ilyasProgrammer** [odoo/odoo#15349]
Impacted versions: 9.0

Steps to reproduce: 

    1. install project_timesheet module
    2. Create custom module
    3. Create models.py file with task inheritance like this:
        class Problem(models.Model):
           _name = 'problem'
           _inherit = 'project.task'
   4. Install that custom module
   5. Create new task using odoo interface. You will get error: Odoo Warning - Missing Record Record does not exist or has been deleted.

Current behavior: Error wont appear if you install project module. Then your custom module. And then project_timesheet

Expected behavior: Errors must absent

**Comment by dynapps** [comment]
Did you include project and project_timesheet in your custom module depencies?

**Comment by ilyasProgrammer** [comment]
yes

**Comment by Yenthe666** [comment]
Hi @ilyasProgrammer,

Thank you for your issue.
The Github issue tracker is however meant for bugs in the official code, not for questions or custom development. You can ask these questions on help.odoo.com
I've just tested with a minimal module that does what you explained and it works fine. Could you try to reproduce this on the latest codebase? If you can still reproduce it then please provide us with an example module, I'll have a double look then.

Regards,
Yenthe
