### ISSUE TITLE
Xpath error when updating modules due to html with &#39;

### ISSUE THREAD

**Issue by bennals** [odoo/odoo#153413]
Impacted versions: 17.0 Enterprise

I updated source code for 17.0 Enterprise just now and got the following error during the following '-u all':

      `Element '<xpath expr="//t[@t-if=&#39;website_sale_order.amount_total&#39;]">' cannot be located in parent view
      
      View error context:
      {'file': '/usr/lib/python3/dist-packages/odoo/addons/website_sale/views/templates.xml',
       'line': 1,
       'name': 'Delivery Costs',
       'view': ir.ui.view(3380,),
       'view.model': False,
       'view.parent': ir.ui.view(3335,),
       'xmlid': 'payment'}`

It seems the apostrophes are being rendered as their html code.

It didn't stop the odoo server running, but trying to update one of my own custom modules with a single addition of a new field via xpath resulted in the same error.

        `Element '<xpath expr="//field[@name=&#39;label_tasks&#39;]">' cannot be located in parent view`

This is in an on-premise installation in docker with a freshly updated Ubuntu server 22.04.

**Comment by bennals** [comment]
Found a probably related issue for 15 here:

https://github.com/odoo/odoo/issues/93841

**Comment by chapital** [comment]
Yo fix this you need to reset the view, probably this error appear after upgrading.

**Comment by gdgellatly** [comment]
It is unlikely to do with the ampersand escape code. That just means `'`. I get this kind of error all the time, and it is never the fault of the escaping. Just standard view errors.

**Comment by bennals** [comment]
Fair enough.  Just thought it was strange to see it after a source code update, though I guess Odoo's developers get things wrong as well.
