### ISSUE TITLE
[8.0] jQuery UI 'draggable' behaviour broken on front-end views

### ISSUE THREAD

**Issue by alexdgs** [odoo/odoo#15346]
Impacted versions: Verified on 8.0 only

Steps to reproduce:
Try to make some element 'draggable' by using jQuery.UI included functionality (8.0 comes with jQuery.UI 1.9.1) in some front-end view (like the Point Of Ssale one)
e.g for Point of Sale
1. Enter to the front-end interface by starting or resuming a session and pick any page element
e.g. Pick the brand header with class `pos-branding`.
2. Make it draggable by editing the `widgets.js` file, selecting it and calling the jQuery.UI `draggable()` function on this element.
e.g. Insert this code at the `start()` function of the main widget after it is rendered
`self.$('.pos-branding').draggable();`
3. Save and reload

Current behavior:
The element is draggable the first time only. If the element is clicked first then it is not draggable anymore.

Expected behavior:
The element must remain draggable regardless of how many times it is clicked and/or dragged.

We are working on a front-end interface similar to the one in POS with drag-and-drop functionality and found the same issue: unable to make any element draggable.

**Comment by alexdgs** [comment]
As an additional hint `draggable()` seems to work as expected in "back-end" views (`ir.ui.view`). e.g. field labels are draggable by adding `$new_label.draggable();` at the end of the `process_label()` function in the `static/src/js/view_form.js` file of the `web` module.

**Comment by alexdgs** [comment]
OK, removing this single line:
`$(document).off();`
from the main widget's `start()` function in the `widgets.js` file of the POS module restores the desired functionality. Above such line this comment is found:
`// remove default webclient handlers that induce click delay`
So, removing this line will generate any undesirable consequences beyond some 'click delay'?

**Comment by Yenthe666** [comment]
Hi @alexdgs ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
