### ISSUE TITLE
[10] Can not connect to my databases anymore (but still all there) -- Please help  

### ISSUE THREAD

**Issue by clxadmin** [odoo/odoo#15348]
Impacted versions: Odoo10/Ubuntu 16

Steps to reproduce: set once system parameter: dbfilter = ^maltherapie.*$  --and then try to switch back to dbfilter= True

Current behavior: databases does not load anymore

i made this setup in conf to try out loading only databse with 'maltherapie'.. 
dbfilter = ^maltherapie.*$

since then I can not switch back to:
dbfilter = True   
I see in browser -- Internal Server Error 
Odoo starts with some default database

2017-02-04 11:07:56,435 12139 INFO ? odoo: database: odoo@default:default
2017-02-04 11:07:56,442 12139 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2017-02-04 11:08:24,094 3215 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres

I can not connect to Odoo with calling the normal URL, but this is working:
http://domain.com/web?db=dbname

Can someone help me out of this issue?

**Comment by dvdhinesh** [comment]
@clxadmin 
Since the log is not showing any errors and the direct URL http://domain.com/web?db=dbname stuff is working, I suspect this could be a cache issue on the browser.

Can you try it out in a private window, just to be sure?

**Comment by clxadmin** [comment]
@dvdhinesh 

Thanks for your informations,

I do try with incognito window and also deleted all browser cookies etc... still the same problem.

My db_user is 'odoo' and the owner is 'odoo', also all of the /odoo-server files have this correct owner/user --- odoo
I'm running out of ideas how to solve this issue.

If I start odoo service I see that odoo is starting up a default Database (odoo@default) which is not in my system

2017-02-06 08:21:21,860 30050 INFO ? odoo: database: odoo@default:default2017-02-06 08:21:21,865 30050 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069. 

Then I delete the 'dbfilter=..' line in my odoo-server.config --- still the same issue

I can connet to my current databases only with: domain/web?db=mydatabases   -- that works perfect

**Comment by clxadmin** [comment]
I solved this problem by deleting second/third .... database. How ever I think there is still a problem in Odoo 10.0. After using once this attribut: dbfilter = ^yourdatabase.*$ you run in weird redirect ploblems and can not call /database/manager anymore.
