### ISSUE TITLE
[17.0] [BUG] Global discount messes up the taxes

### ISSUE THREAD

**Issue by yediel** [odoo/odoo#153570]
**Impacted versions:**
17.0

**Steps to reproduce:**
1. Create Sales Order and add some lines with taxes (like VAT)
2. Click the Discount button and apply a fixed amount discount

**Current behavior:**
The discount line is entered without a tax (even if the "Discount" product is configured to have Customer Taxes.

**Expected behavior:**
Add the tax according to the product definition

**Comment by yediel** [comment]
Critical in some countries - it can mess up the VAT reports for accounting

**Comment by dalaOdoo** [comment]
@yediel can you be more specific about the problems you are facing ?

**Comment by yediel** [comment]
@dalaOdoo What more details are needed?

1. Create an order in Odoo
2. Add items with tax
3. Add global discount

The discount is added without a **tax_id**. Even if the **discount** product is configured with one

**Comment by yediel** [comment]
We have 17% VAT in our country.
And let's assume the Tax is defined as "Included in price".

Let's say the user creates an invoice with one line, product at cost of 117$. VAT is added so untaxed amount is 100$.
Now he adds global discount of 20$.
Discount line is added, 20$, no tax.

In the invoice summary, this is what Odoo will produce:
**Total untaxed:** 80$
**Total tax:** 17$
**Total amount:** 97$

This is illegal, since the *Total tax* should always be 17% of **Total untaxed**.

The correct result should have been:
**Total untaxed:** 82.91$
**Total tax:** 14.09$ (now its exactly 17% of total untaxed)
**Total amount:** 97$

**Comment by dalaOdoo** [comment]
@yediel thanks for the explanation. 
In which country are you ?

**Comment by dalaOdoo** [comment]
I'm not aware of the tax regulation in Israel sorry. 
In most countries discounts can be applied before or after VAT computation (as you will pay more taxes).

We decided to apply fixed amount discount on order after VAT for the reasons explained before.
We do not plan to change the standard behavior because of the specific case of Israel. 

The only workaround I can suggest you (without customization) is to use a "discount product" and add an order line with this product instead of using the discount wizard.

**Comment by yediel** [comment]
@dalaOdoo Didn't ask to change specifically for Israel, just to make it configurable

I am trying to understand the line here:
https://github.com/odoo/odoo/blob/dd408679491d6074241d80c5cb26099806169cf7/addons/sale/wizard/sale_order_discount.py#L58

What is **taxes.ids** in this case?

**Comment by dalaOdoo** [comment]
@shag-odoo can you help regarding the question here above ?

**Comment by shag-odoo** [comment]
@dalaOdoo taxes.ids is used to fetch ids of the tax that are associated with the product
if suppose a product has a tax of 15% than taxes.ids (if multiple) will get me the id of the tax i.e. 15%

Thanks for reaching out to me and have a great day ahead :innocent:

**Comment by yediel** [comment]
@shag-odoo so this means that if the Discount product was defined with a tax, it will also be added to the Sale Order with the same tax, right?
because it doesn't happen

**Comment by shag-odoo** [comment]
@yediel Discount will take that discount which is been associated with the product suppose if product has 15% tax then global discount will be applied with 15% tax, if product has 20% tax then discount will be applied with 20% tax

for reference : https://ibb.co/j8DV3N8
I hope this explains it better, Thanks and have a great day ahead :innocent:

**Comment by dalaOdoo** [comment]
@shag-odoo this is only for % discount, not for fixed amount discount.

**Comment by shag-odoo** [comment]
@dalaOdoo yes correct we include tax only for % discount not for fixed amount
This is the standard behavior that we follow here :slightly_smiling_face:
