### ISSUE TITLE
One2many onchange in Odoo 9

### ISSUE THREAD

**Issue by khoapn102** [odoo/odoo#15353]
Impacted versions: Odoo 9.x

Steps to reproduce:
1. This is my one2many field: `offer_course_ids=fields.One2many('offer.course','semester_id',string='Offer Courses')`
2. This is my onchange method:
```
@api.onchange('semester_id')
    def _onchange_semester_id(self):
        res_ids = []
        if self.semester_id:
            course_ids = self.env['offer.course'].search_read([('semester_id','=',self.semester_id.id)])
        print '++++++++++++', course_ids
        for course in course_ids:
            res_ids.append((0,0,course))
#         self.offer_course_ids = res_ids
        res = {'value':{'offer_course_ids':res_ids}}
        return res
```
Current behavior: After onchange is added, all the one2many fields are empty, No records are shown. After delete this onchange method, the whole Database is messed up some like that I am not sure. 
Due to there are more than 20 fields for each record in offer_course so that i used search_read to return the record as a dict for updating. 
Expected behavior: When i change semester_id (many2one), all the course belong to this semester will updated in offer_course_ids and the old courses will be unlinked. Please help me. Its urgent. Thanks

Video/Screenshot link (optional):

**Comment by dynapps** [comment]
Don't really think this is an issue. Perhaps you should refer to the odoo community help forum.
I believe this is also some recommended reading for you: [How to insert values into a one2many field](https://www.odoo.com/forum/help-1/question/how-to-insert-value-to-a-one2many-field-in-table-with-create-method-28714)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
