### ISSUE TITLE
forecast icon, (red-purple), not functional colors.

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#153568]
Impacted versions:
17.0

Steps to reproduce:
go to sales modules and check stock availability by using the color scheme of the forecast icon.

Current behavior:
the current color based on milk scheme generate doubts when the products its available because the color are similar (red-purple), in odoo 16 dont have this problem because the color scheme are a contrasted red-green.

Expected behavior:

change the color of the forecast icon to avoid loosing time validating stock availability.

see the image attached to understand what do I try to explain.

odoo 17 use analogous colors.

odoo 16 use complementary colors.

![secondary](https://github.com/odoo/odoo/assets/21046957/af431cf9-920e-48a8-88e9-13bf66441e21)

@vava-odoo

**Comment by chgo-odoo** [comment]
Good evening @chapital , thank you for your report !

This icon is indeed supposed to use the default link color rather than the primary one. I will take care of this issue since I already have an ongoing PR that aims to fix the color of this specific forecast icon.

Cheers !

**Comment by chapital** [comment]
Hi @chgo-odoo 

Can you please share the PR number to stay tuned when it will be fixed, to update my on premise installation to validated that.

Thanks

**Comment by chgo-odoo** [comment]
Closed via https://github.com/odoo/odoo/pull/140959 merged in 17.0 in https://github.com/odoo/odoo/pull/153618

**Comment by chapital** [comment]
Thanks
