### ISSUE TITLE
Cash basis create journal entry when is exchange gain/loss

### ISSUE THREAD

**Issue by alan196** [odoo/odoo#15354]
Impacted versions:
- 9.0

Configuration:
- Company Currency: MXN
- Multicurrency and cash basis activated.
- Exchange rates for USD.
- Tax Received Account configured.

Steps to reproduce:
- Create an invoice in USD and validate it.
- Pay the invoice with different date (In order to get exchange difference).

Current behavior:
- Odoo create several journal entries:
    - Jornal entry for the payment.
    - Journal entry for the exchange Gain/Loss.
    - 2 Journal entries for cash basis. 
        - one for the tax of the invoice.
        - one for the percentage of the tax of the exchange gain or loss.  (This is not correct).

Expected behavior:
There must be only one journal entry for the tax of the invoice.

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=KAGQbVuB1E0

**Comment by alan196** [comment]
@moylop260 @luistorresm @nhomar do you realize of this issue?

**Comment by nhomar** [comment]
On Sun, Feb 5, 2017 at 11:06 AM, Jesús Alan Ramos Rodríguez <
notifications@github.com> wrote:

> @moylop260 <https://github.com/moylop260> @luistorresm
> <https://github.com/luistorresm> @nhomar <https://github.com/nhomar> do
> you realize of this issue?
>
>
Yes we do, but for us it is not "ideal" but it is correct AFAICU.



Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by alan196** [comment]
The problem of this behaviour is the tax effectively paid is more than the invoiced.

**Comment by nhomar** [comment]
http://www.fiscalia.com/modules.php?name=Foros&sop=verTopico&idTema=33849&idCat=10

Can you check that.

The good point of have it separated is that you can comply with all user cases this post mentioned with legal fundaments.

But I can be wrong can you analyze please and give us feedback.?

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
