### ISSUE TITLE
[10.0][website_sale]cart can't be clear after payed

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#15358]
Impacted versions:
[10.0]
Steps to reproduce:
1. start /shop
2. add product to cart
3.check out and payed
Current behavior:
sometimes the product payed is always in the cart
Expected behavior:
clear the cart by delete session  sale_order_id
Video/Screenshot link (optional):

**Comment by yueqin** [comment]
when visit the cart  /shop/cart, it will call the func:   sale_get_order(),
this method  read sale_order_id from session,but after payed,the session(sale_order_id) haven't cleared.

**Comment by Yenthe666** [comment]
Hi @yueqin,

I've just followed your steps on the latest Odoo 10.0 and this issue has been handled in the meanwhile.
Please update your Odoo instance to the latest code and it should be fixed.

Regards,
Yenthe
