### ISSUE TITLE
[10.0] Do not add/create a tag in frontend Forum

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#15368]
Impacted versions: 10

Steps to reproduce:
Forum - > Ask a question -> Add tag

Current behavior:
Loading failed

Expected behavior:
What would tag added / created

Video/Screenshot link (optional):
https://youtu.be/9GqXdKbM5Dc

**Comment by Yenthe666** [comment]
Hi @collex100,

Thanks a lot for your report!
This bug has been fixed in the meanwhile. Please update your Odoo instance and it'll work fine.

Regards,
Yenthe
