### ISSUE TITLE
PoS order date doesn't match system date and timezone

### ISSUE THREAD

**Issue by clengmann** [odoo/odoo#153636]
Impacted versions: Odoo 17

Steps to reproduce:

Current behavior: Order date displaying different dates and time for Point of sales in the same time zone. Wrong dates and time on POS order date. Employee timezones have been set to Africa/Accra, computer date and times are also correct yet some PoS orders have different dates and time. Sales on a particular date have order dates set to the next day. For examples sales on Feb 12, 2024, have dates of Feb 13, 2024, which doesn't help for accurate daily sales reporting.

Expected behavior: Order dates should match system dates and timezone.

Video/Screenshot link (optional):

Uploading Screen Recording 2024-02-12 at 12.39.45 PM.mov…

Support ticket number submitted via odoo.com/help (optional): #3741877

**Comment by vava-odoo** [comment]
Linked ticket is closed
