### ISSUE TITLE
[base]web.base.url error when deploy a https website

### ISSUE THREAD

**Issue by yueqin** [odoo/odoo#15365]
Impacted versions:
[10.0]
Steps to reproduce:
create a new database,use the https
Current behavior:
the default web.base.url is http://url
Expected behavior:
if we deploy a https website,i think the web.base.url set to https:// is better,is will reduce the 301,and some times the client didn't suppot the 301
Video/Screenshot link (optional):

**Comment by m3dbedb** [comment]
[Try](https://github.com/odoo/odoo/issues/4382) adding this parameter to the odoo-server.conf:
proxy_mode = True

**Comment by Yenthe666** [comment]
Hi,

This is because of misconfiguration.
Please see the docs at https://www.odoo.com/documentation/11.0/setup/install.html and https://www.odoo.com/documentation/11.0/setup/deploy.html

Regards,
Yenthe
