### ISSUE TITLE
[9, 10] models: Inappropriate checking of dirty fields in onchange

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#15360]
Impacted versions:
9, maybe 10

Steps to reproduce:
https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L6088
```
if newval != oldval or (
    field.type in ('one2many', 'many2many') and newval._is_dirty()
):
    todo.append(name)
    dirty.add(name)
```
Current behavior:
If the field type is not string(char,text) or integer, this simple checking is inappropriate.
For example, float will almost always be dirty even if the value is actually not dirty.
Not sure the behavior of binary field with attachment=True.

Expected behavior:
Should be able to use different check according to field type

**Comment by auyeung112002** [comment]
@rco-odoo Would you please comment on this issue?

**Comment by pedrobaeza** [comment]
I can tell you that ORM has been continuously improved over versions, but the main goal is to preserve consistency, so the issue you are mentioning (if not yet using another strategy), is for that goal, and thus there's not to much to discuss I think, unless you have a concrete proposal that can be apply to master branch (not 9.0), as stability policy doesn't allow this kind of dangerous changes.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
