### ISSUE TITLE
[10.0] Why do we need the button "Upload" in the slides for the public user?

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#15369]
Impacted versions:10

Steps to reproduce:
Public user (front end) - Presentations

Current behavior:
Displaying the button "Upload"

Expected behavior:
All materials are unloaded by users who have access to certain functions.
According to this, this button should not be shown to the public user.

Video/Screenshot link (optional):
https://youtu.be/OJF0Nljesfs

**Comment by Yenthe666** [comment]
Hi @collex100,

Thank you for the bug report.
@JKE-be can we add a `t-if` around the button to only show it if you're a logged in user in order to improve this behaviour?

Regards,
Yenthe

**Comment by JKE-be** [comment]
By design, but yes it could be removed.

Waiting for @fgi-odoo, the product owner of Website, validate it!

**Comment by Yenthe666** [comment]
Thanks a lot @JKE-be! Fixed in https://github.com/odoo/odoo/commit/74b564cf8d1a192cee784997a6fb9da5b030c794
