### ISSUE TITLE
not possible save template Mass Mailings odoo 10

### ISSUE THREAD

**Issue by developeropensoft** [odoo/odoo#15377]
Impacted versions:
odoo 10

Steps to reproduce:
odoo > Mass Mailings > Mass Mailings > Create 

not possible save template Mass Mailings odoo 10

Video/Screenshot link (optional):
![mass mailings](https://cloud.githubusercontent.com/assets/24612504/22661641/49c89cda-ec8d-11e6-8839-787a71fd0521.jpg)

**Comment by Yenthe666** [comment]
Hi @developeropensoft,

Thank you for your report.
I've just tested this but it works without any issue. I went to Mass mailing > Mass mailings > Create, simply added some blocks in, added a subject and saved.
Can you reproduce this issue on the latest Odoo runbot? (runbot.odoo.com)

Regards,
Yenthe

**Comment by developeropensoft** [comment]
Hi Yenthe666 

sorry my bad english
The campaign saves perfectly
The problem is saving the tamplate used in the campaign
Tks
![untitled-1](https://cloud.githubusercontent.com/assets/24612504/22704262/380d2ee0-ed4e-11e6-8a7f-d439463f2ff1.jpg)

![untitled-2](https://cloud.githubusercontent.com/assets/24612504/22704268/3dcdb99e-ed4e-11e6-9660-01bf8135d8f2.jpg)

tks
