### ISSUE TITLE
hr_contract multicompany

### ISSUE THREAD

**Issue by veryberry** [odoo/odoo#15380]
Could you please explain why multicompany rules are not initially defined for model hr.contract? Is there some reason?

**Comment by Yenthe666** [comment]
Hi @veryberry,

Thank you for your report.
The Github issue tracker is only for bugs in the official Odoo code however, this is not the place to ask questions. There are plenty of people who can help you on the official help forums (help.odoo.com).
The security rules are applied on the user and are followed throughout the system depending on the user configuration.

Regards,
Yenthe
