### ISSUE TITLE
[10.0] Too permissive ACL on analytic objects

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#15387]
Impacted versions:

At least 10.0

Current behavior:

If analytic accounting is enable, It's possible for a simple user to create, write and delete analytic account, analytic line and analytic tags.

If the user has no menu to access to these objects, RPC protocol make the job.

Expected behavior:

This kind of simple users should'nt have a full access on these object.

https://github.com/odoo/odoo/blob/10.0/addons/analytic/security/ir.model.access.csv

**Comment by adrienpeiffer** [comment]
OPW 707684

**Comment by Yenthe666** [comment]
@adrienpeiffer what was the feedback on 707684? Has this been handled?

**Comment by Yenthe666** [comment]
Closing as no feedback. I'm going to assume it has been handled.
