### ISSUE TITLE
[17.0] stock picking, dont validate

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#153983]
Impacted versions:
17.0
Steps to reproduce:

make a sale, add a storable product, this product dont gonna have stock, then make a purchase of that item.

Current behavior:
if you try to validate delivery, says AVAILABLE in ORANGE, I dont know what does it mean, if you try to VALIDATE, says: "You cannot validate a transfer if no quantities are reserved. To force the transfer, encode quantities.".

to validate you need to put manually the "pick from" or change the quantity manually.

Expected behavior:
In odoo 16, when you click in validate, and if you dont establish quantity appear dialog to auto set quantity or cancel.
Also in odoo 16 have a button to establish quantity (set quantity).

If this is a bug and have a PR open, please share the PR number.

<img width="1229" alt="Captura de pantalla 2024-02-13 a la(s) 10 24 58 p m" src="https://github.com/odoo/odoo/assets/21046957/a6abf777-7f1d-4c6e-a6b8-65602322d8a4">

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by intero-chz** [comment]
Your picking is "Waiting" and not "Ready". That looks like a chained Picking waiting for another.

**Comment by intero-chz** [comment]
Sorry but it's hard to figure out what type of operation you're doing there, but "ordenes de entrega" translates to "delivery orders" what i interpret as an outgoing delivery.

So my guess: The used Operation Type (`stock.picking.type`) is configured wrong. When you have the settings like in my following screenshot, you will have to reserve "manually" as you're describing:

![image](https://github.com/odoo/odoo/assets/8614174/e760a939-9975-4f33-af44-cd77e29fe972)

Set it to "At Confirmation" and you will have automatic reservation.

**Comment by chapital** [comment]
Yes, delivery orders is "ordenes de entrega" in Spanish.

An its reservation method its "At confirmation".

I migrate from 16 to 17.

In 16 everything work ok, but in 17 have this issue.

**Comment by chapital** [comment]
#137452

**Comment by chapital** [comment]
I submit a ticket, the number is #3755731.

I think the problem only appear when we received the product  2-3 days or more after the sale order its make it.

@amoyaux can you validate this?

**Comment by amoyaux** [comment]
Hey. Could you check if the picked checkbox is active or not
![image](https://github.com/odoo/odoo/assets/5512395/2385e267-9cd2-49bb-bc5c-45e3cbb82cf8)

In 17.0 we mixed the quantity done and the quantity reserved (more explanation in https://github.com/odoo/odoo/commit/7dda6bb92715ea25b2818a62fec5e646f3678b81) replaced it by a check to know if it's already pick or not. If it's pick, he won't suggest reserving it because it assumes that you don't want to pick it anymore.

**Comment by chapital** [comment]
The ticket it's answered:

Hello,

Thank you for contacting Odoo Support. I understand that you are having problems reserving products on a specific delivery order. I would be happy to assist you with this issue.

The operation type "Delivery Order" has its reservation method set to "On Confirmation". This means that the products will be reserved automatically when the delivery order is confirmed. If there are no units available in stock, then they will not be reserved for the order, even after they are replenished to have adequate stock to fulfill the order.

You can view and edit these operation types by navigating to Inventory > Configuration > Operation Types.

The reason the delivery order still says "Available" is because this is a read-only field that takes the value of the "on-hand" quantity of each product. On-hand quantity is the amount of stock that is stored in a physical location within the warehouse and is not reserved.

In order to reserve these products, you will need to remove the existing stock lines and add them back. I have attached a video of this process below:

https://drive.google.com/file/d/1soNPxs319Y7hdaoWURUvzrovGjDAf6g3/view?usp=sharing

Please let me know if you have any other questions regarding this behavior.

Kind regards,


But the solution if even more complex, at the end if we have the button check availability and works like odoo 16, it will be the best solution.

@amoyaux

**Comment by amoyaux** [comment]
> "If it's pick, he won't suggest reserving it because it assumes that you don't want to pick it anymore.": why? its have a time?
> 
> In my case:
> 
> I make a sale, normally the products we dont have in stock, I request this products to my vendors, an make my purchase order and received in the system 2-3 days later,
> 
> There its a way to put it like odoo 16?

No there is no way.

However it should never be pick by default. I checked and the box is not ticked automatically and should not. Do you have extra step that could explain it?

**Comment by chapital** [comment]
Hi @amoyaux 

I found what its happening.

in my case I when I process the inventory I use the "WAITING" order instead of "TO PROCESS", because I wanna process partial orders and create a "BACKORDERS" to deliver, to know what do I have in hand.

So I go to inventory, delivery order, waiting, and select ALL the order (in the list view), click in the ACTION button, and then VALIDATE.

If some order dont have the required stock, odoo ask to create a partial order, an click in CREATE BACKORDER.

And this its when the ISSUE appear, the same order automatically activate the PICKED box.

Here are the video:


https://github.com/odoo/odoo/assets/21046957/5e15fd1d-c78c-4205-b3a3-06a746bdb2c3


Also please consider Implementing this in odoo 18, this will help to process automatically the order instead to do validation manually:

https://github.com/odoo/odoo/issues/131648


Thanks

**Comment by amoyaux** [comment]
Aaah we got the issue there. The backorder shouldn't be picked. I will fix this

**Comment by amoyaux** [comment]
@chapital thanks for the investigation :+1:
