### ISSUE TITLE
[7.0/8.0]opening o2m must open as popup

### ISSUE THREAD

**Issue by youring** [odoo/odoo#1539]
This bug is reported by Ferdinand on 2013-02-07 on launchpad.

https://bugs.launchpad.net/openerp-web/+bug/1118181

https://www.odoo.com/forum/help-1/question/open-product-in-sale-order-line-popup-window-19947

Steps to reproduce:
Settings-Configeration-Sale with "Product properties on order lines" ticked.
Then open a quotation or sale order, click the line item; In the pop-up window, click product name, the product inform opened in the background window, But the pop-up window stay unclosed.

Expected:
Open a pop up window when clicking a o2m item. Or open in the main window with current pop up closed, Just like the behavior in OpenERP v6.1.

**Comment by Yenthe666** [comment]
Hi @youring,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
