### ISSUE TITLE
[8.0] Server error when using deferred constraints

### ISSUE THREAD

**Issue by PeterAlabaster** [odoo/odoo#15395]
Impacted versions:
8.0 (May be 9.0, 10.0 too, but I don't use them sorry). Ran from source, pulled down today.

Steps to reproduce:
This should work on any model with a one2many relation. In this example i will use res.partner and contacts as it needs minimal code to try out.

1. Create a module, and add a standard SQL constraint to the table:
```python
from openerp import models, fields, api

class ResPartner(models.Model):
	_inherit = "res.partner"

	_sql_constraints = [
		('contact_name_uniq', 'unique (parent_id,name)',
		'A contact related to this partner already has this name!')
	]
```
2. Install the module
3. Create a company `Company A`
4. Create a new contact named `Contact A`
5. Save the company record
6. Edit the company record again
7. Unlink `Contact A` from `Company A`
8. Create a new contact named `Contact A`
9. Click Save

Current behavior:
False positive in SQL constraint is hit, and message `A contact related to this partner already has this name!` is displayed as an Odoo warning.

Expected behavior:
No error to be raised

I then  proceeded to try something different, which actually resolves the above issue. However - when the deferred constraint is hit, we get other issues:
Steps to reproduce:
1. Create a module, and add a deeferred SQL constraint to the table. This works, and you can see by `\d`ing the table in psql. Hook into `write()` on the `parent` object (in this case it is still res.partner, but could differ) and defer the constraint before anything is done - then simply return like normal:
```python
from openerp import models, fields, api

class ResPartner(models.Model):
	_inherit = "res.partner"

	@api.multi
	def write(self, vals):
		self.env.cr.execute("SET CONSTRAINTS res_partner_contact_name_uniq DEFERRED")
		return super(ResPartner, self).write(vals)

	_sql_constraints = [
		('contact_name_uniq', 'unique (parent_id,name) DEFERRABLE',
		'A contact related to this partner already has this name!')
	]
```
2. Install the module
3. Create a company `Company A`
4. Create a new contact named `Contact A`
7. Create a new contact named `Contact A`
8. Click Save

Current behavior:
Logs show:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/home/peter/src/repos/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 1297, in __call__
    return self.dispatch(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 1271, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 1449, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/home/peter/src/repos/odoo/openerp/http.py", line 264, in __exit__
    self._cr.commit()
  File "/home/peter/src/repos/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/peter/src/repos/odoo/openerp/sql_db.py", line 363, in commit
    return self._cnx.commit()
IntegrityError: duplicate key value violates unique constraint "res_partner_contact_name_uniq"
DETAIL:  Key (parent_id, name)=(6, Contact A) already exists.
```
GUI shows:
```
XmlHttpRequestError INTERNAL SERVER ERROR
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Expected behavior:
GUI should show error message defined in `_sql_constraints` list, like it does when a non-deferred constraint is used.

Other information:
This is a bug which occurs as a side effect of working around https://bugs.launchpad.net/openerp-web/+bug/984985. (as described in the first run-through of this issue) Deferring constraints would be a very useful way of handling such cases, and as far as  I know - there is no known _sensible_ way of doing so.

**Comment by PeterA-OpusVL** [comment]
After some more digging and help from colleagues - it appears there is a way to catch the exception before Odoo throws out the error.

By forcing a `commit()` in the parent objects `write()` function we are able to preserve the deferred constraint whilst still catching properly when it is hit. To make this a little safer we only do so if changes are made to the child.

We also move the block which marks the constraint as deferred into the child objects `create()`.

In the above example - this would look like so:
```python
from openerp import models, fields, api

class ResPartner(models.Model):
	_inherit = "res.partner"

        @api.model
        def create(self, vals):
            self.env.cr.execute("SET CONSTRAINTS res_partner_contact_name_uniq DEFERRED")
            return super(ResPartner, self).create(vals)

        @api.multi
        def write(self, vals):
            if vals.get('child_ids'):
                self.env.cr.commit()
            return super(ResPartner, self).write(vals)

	_sql_constraints = [
		('contact_name_uniq', 'unique (parent_id,name) DEFERRABLE',
		'A contact related to this partner already has this name!')
	]
```

Doing this appears to fully work round the issue - but in more complex scenarios I have a feeling this would blow up, as it's a pretty sketchy workaround

**Comment by Yenthe666** [comment]
Hi @PeterAlabaster ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report (or I can alternitavely open this one again if you'd like).

Regards,
Yenthe

**Comment by elgow** [comment]
@Yenthe666 I have reproduced this bug in Odoo 11.0.  

It seems obscure, but actually this bug is very serious when using the handle widget to manipulate a sequence field in a model. If a normal unique constraint is applied to the sequence field then moving with a handle will always fail. If the constraint is marked DEFERRED as in the example from @PeterAlabaster then the exception thrown by psycopg2 at commit time is swallowed by Odoo code. The client cannot save the record and they see a popup message saying that the connection has dropped followed by a reconnect popup message. 

Because it is crucial for the handle widget to function with a unique constraint, could you please reopen this bug for 11.0. 

The exception that I'm seeing in the logs from Odoo 11.0 looks like this:

```  
File ".../odoo/odoo/http.py", line 282, in __exit__
    self._cr.commit()
  File ".../odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File ".../odoo/odoo/sql_db.py", line 375, in commit
    result = self._cnx.commit()
psycopg2.IntegrityError: duplicate key value violates unique constraint "tidb_run_sample_run_well_uk"
DETAIL:  Key (run, sequence)=(2, 3) already exists.
```

**Comment by elgow** [comment]
@Yenthe666  
I tried the work-around shown by @PeterAlabaster and I find that it does not work and results in  no change in the error at transaction commit time in 11.0.   

I should note that in my code the user can explicitly set the sequence field via a computed field that has an inverse to set the sequence.  A constraint cannot be used with a field that can be set by either handle or explicit values unless psycopg2 exceptions at commit time are handled properly. Ideally the user would see the same ValidationError as they see with a unique constraint that is not deferred.

**Comment by elgow** [comment]
Note that the correct syntax for the deferred constraint in postgresql is

`unique(run, sequence) deferrable initially deferred`

**Comment by PeterAlabaster** [comment]
@elgow If using my example, it may be necessary to move the `create()` block into the `One2many` relational model. In my example the relational model is `res.partner` (same model which the o2m is declared on). May solve the problem for you, but it's been a while since i looked at this.
