### ISSUE TITLE
hr_payroll miscalculation in no of work days and hours.

### ISSUE THREAD

**Issue by mikeross6233m** [odoo/odoo#15404]
Impacted versions: Odoo 10

Steps to reproduce: 
1. Create a contract for the Employee and select the Working Schedule as Day shift.

2. Go to Payroll -> Employee Payslips -> Create. Select Employee and the Contract, Period must be automatically selected. In Worked days, the WORK100 shows no of days and hours by calculating the period and Working schedule.

3. Now try selecting the previous month(1st day to last day). And the worked Days will miscalculate the no of days and hours.(Check Screenshots).

Current behavior: Miscalculation in Worked Days( No of days and Hours) if the period is change e.g. Select a last month

Expected behavior: No of days and hours must be calculated properly after changing the period.

Video/Screenshot link (optional):
![payroll_period](https://cloud.githubusercontent.com/assets/14011478/22732830/a449a954-ee15-11e6-8909-9d714d306bdb.png)
![payroll_hours](https://cloud.githubusercontent.com/assets/14011478/22732819/9e7c34e2-ee15-11e6-9924-a8dc42ce9a5a.png)

**Comment by egrivero** [comment]
Hello, I have a similar error that must be related to this issue

Error calculating leaves days in Payroll module

Steps to reproduce the error:

1) Create employee’s contract as follow
![contract_pieter](https://cloud.githubusercontent.com/assets/7115776/22740804/6923685c-ede7-11e6-96f4-af6c276d1db7.png)

2) I use this work schedule
![working_time](https://cloud.githubusercontent.com/assets/7115776/22740834/8b0add9c-ede7-11e6-8447-1132cd5be0a5.png)

3) Create a leaves type




4) Create a leave for the employee and approve it

5) Create a second leave for this employee out of time of his work schedule and approve it, it means, in the same same day (one day), but with more hours than configurated in his work schedule for this day


6) See the Leaves summary and notice the number of days shown


7) Compute sheet for this employee in the objetive period where the leave days were approved


ERROR: the expected and exact amount of sick leaves days is 4.62, or if we could consider a rounded amount of it, it should be 5.0. but 6.0  is shown as a rounded amount of this days

**Comment by jordanvrtanoski** [comment]
The issue with the Work Schedule is addressed with the pool request #17252
