### ISSUE TITLE
Can you please imporve the documentations?

### ISSUE THREAD

**Issue by umarmughal824** [odoo/odoo#154041]
**First of all thanks for the great work. I appreciate your work and want to be a contributor but I am unable to understand the documentation.**

Can you please improve your documentation like images are not being shown in the documentation.

But I am sorry to say that your documentation is not beginner-friendly at all. It's very confusing and complicated. Can you please make it more friendly like how to design the menu and view etc? I might be wrong but that's my first experience after reading the Getting Started tutorial at least twice or so.

For example, you can see on these pages

- https://www.odoo.com/documentation/17.0/developer/tutorials/getting_started/07_basicviews.html

   List, Form, and Search section images not working here
 

- https://www.odoo.com/documentation/17.0/developer/tutorials/getting_started/06_firstui.html  
  - Fields and Menu section images are not loading here

So, most of the pages are like this.

**Comment by gdgellatly** [comment]
I clicked the links, all the images are there

**Comment by umarmughal824** [comment]
On this page, 
here is what its looking on both of my mac and ubuntu OS showing same


https://www.odoo.com/documentation/17.0/developer/tutorials/getting_started/07_basicviews.html

<img width="1167" alt="Screenshot 2024-02-27 at 21 56 06" src="https://github.com/odoo/odoo/assets/4043989/823c3048-e491-402c-b7c0-3161c2d6dfda">
<img width="1149" alt="Screenshot 2024-02-27 at 21 56 13" src="https://github.com/odoo/odoo/assets/4043989/5efc9980-2592-40b4-a64c-1dc80dbf6875">
<img width="1077" alt="Screenshot 2024-02-27 at 21 56 21" src="https://github.com/odoo/odoo/assets/4043989/ca22b8df-41d4-4a1e-8bc1-493bae1831ac">


https://www.odoo.com/documentation/17.0/developer/tutorials/getting_started/06_firstui.html

<img width="1117" alt="Screenshot 2024-02-27 at 21 57 42" src="https://github.com/odoo/odoo/assets/4043989/df2b0a4b-f3fa-4be9-a7ae-47d382001820">
<img width="1026" alt="Screenshot 2024-02-27 at 21 57 49" src="https://github.com/odoo/odoo/assets/4043989/37211c29-c49c-4c0c-905a-87fb2111545d">

**Comment by umarmughal824** [comment]
@gdgellatly I am using Chrome browser. It doesn't show any images.

**Comment by gdgellatly** [comment]
Well I use Ubuntu and Chrome so would seem to be a specific issue to you

![image](https://github.com/odoo/odoo/assets/5093264/25246076-5afa-4e96-870c-7fdcdde91ec4)

**Comment by umarmughal824** [comment]
Mac OS Chrome View


<img width="1800" alt="Screenshot 2024-03-02 at 17 27 26" src="https://github.com/odoo/odoo/assets/4043989/ccb884db-d40f-4924-8f3a-65bbbdddbae9">

<img width="1800" alt="Screenshot 2024-03-02 at 17 28 20" src="https://github.com/odoo/odoo/assets/4043989/30e322d4-9380-49bb-a36b-ef90a846c26d">

**Comment by umarmughal824** [comment]
Ubuntu Chrome View

![Screenshot from 2024-03-02 17-32-45](https://github.com/odoo/odoo/assets/4043989/fa946378-599c-4305-8acb-81350dce5f2d)
![Screenshot from 2024-03-02 17-32-57](https://github.com/odoo/odoo/assets/4043989/3c2afcc3-b297-4a23-873f-eec9123f6af8)

**Comment by vava-odoo** [comment]
Hi @umarmughal824 
Thanks for your nice message.
But as @gdgellatly is saying, there is no issue with the images, I'm afraid it should be something from your side.
Cheers
