### ISSUE TITLE
[9.0] Group by hour

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#15400]
**Impacted versions:**
9.0

**Current behavior:**
Currently, one can group by day, week, month and year in a search view. For example: `<filter string="Day" domain="[ ]" context="{'group_by': 'create_date:day'}" />`. It is however not possible to group by hour, although there is a sort of hack around it, as can be seen here: [im_livechat/report/im_livechat_report_channel.py](https://github.com/odoo/odoo/blob/9.0/addons/im_livechat/report/im_livechat_report_channel.py#L38)

**Expected behavior:**
Able to group by hour using `<filter string="Day" domain="[ ]" context="{'group_by': 'create_date:hour'}" />`.

**Comment by Yenthe666** [comment]
Hi @adekock11,

Thank you for your report.
Just wondering, where would you ever want to group per hour? I couldn't directly think of a case where this would be handy. I'll label it wishlist for now.

Regards,
Yenthe

**Comment by adekock11** [comment]
Thanks @Yenthe666

I can think of a large company wanting to see which time of the day the sales people create the most quotes. Think of a line graph grouped by hour on the x-axis and the amount of quotes on the y-axis for example.

Kind regards

**Comment by adekock11** [comment]
Another one off the top of my head: using the CRM Voip app, managers might want to see what time of the day the most phone calls were made. Using a "Today" or "Yesterday" filter together with a group by hour.

**Comment by Ark74** [comment]
Hey! So, is it possible?
I'm using exporting and complex macros to group sales date/time but since it's not an organic solution it's not really functional. :disappointed: 

Interesting, @adekock11 were you able to work this around?

**Comment by yelizariev** [comment]
PR and link to workaround is here: https://github.com/odoo/odoo/pull/22419

**Comment by yelizariev** [comment]
@Yenthe666 with regards to 

> Just wondering, where would you ever want to group per hour? I couldn't directly think of a case where this would be handy. I'll label it wishlist for now.

Grouping by hour is already used in [im_livechat](https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/im_livechat/report/im_livechat_report_channel.py#L21-L41), but via workaround

**Comment by adekock11** [comment]
@yelizariev great!!!

**Comment by pedrobaeza** [comment]
This has been recently included in master branch, so congratulations for having the new feature.

Closing this.

**Comment by KothiyaRajeshEnvertis** [comment]
**[15.0] Group by hour**
In V15 group by we got only [Year,Quarter,Month,Week,Day] selection on datetime fields
So how we can get group by hour in V15


Help me please @pedrobaeza @steync027 @Yenthe666 @yelizariev @Ark74
