### ISSUE TITLE
A possible typo in template ChatGPTPromptDialog. It should be "web_editor" instead of "web_edior"

### ISSUE THREAD

**Issue by SnowyVit** [odoo/odoo#154064]
https://github.com/odoo/odoo/blame/ef1d087efd0d869e0cd2c304b7a691fe05460d78/addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_prompt_dialog.xml#L4

**Comment by SnowyVit** [comment]
It also occurs in a few other places, guess those were copied

**Comment by dmo-odoo** [comment]
Thanks for the report! It will be fixed with https://github.com/odoo/odoo/pull/159438
