### ISSUE TITLE
[10.0] Quick-create of at least notes and project tasks does not respect the state (lane)

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#15415]
##### Impacted versions: 
10.0

##### Steps to reproduce:
1. In either the notes module or projects, open a kanban view
2. Use the quick-create link at the top of the lane to create a new record
3. Refresh the page

##### Current behavior:
The ticket jumps back to the leftmost lane. It has in fact been created with the default state.
##### Expected behavior:
The created record should be created with the state corresponding to the lane it was created in.

This was tested in our own builds of Odoo from January 16th, and on demo.odoo.com.

##### Speculation
Since this appears in both the note view and in the project view, it seems the problem may be a more general problem with the frontend framework. I'm not sure how the record is meant to be able to know what state it should be created in, but that seems like a good place to start looking. Does @Yenthe666 know who would be knowleadgeable about the JavaScript side of things, perhaps especially relating to kanban views?

**Comment by Yenthe666** [comment]
Hi @aisopuro,

Thank you for your report.
I've just tested this on the latest runbot (the newest Odoo codebase) and I cannot reproduce this.
Can you try this again on runbot.odoo.com and perhaps make a video from it?

Regards,
Yenthe

**Comment by aisopuro** [comment]
OK, I tested it myself on the latest 10.0 runbot and was also unable to reproduce this issue. We will update our images and see if that helps.
