### ISSUE TITLE
Documentation for POSBoxless is incomplete

### ISSUE THREAD

**Issue by multiwebinc** [odoo/odoo#15420]
I have been trying to get the POSBoxless running following the [guide](https://www.odoo.com/documentation/user/10.0/point_of_sale/overview/setup.html#posboxless-guide-advanced), but so far I have been unsuccessful.

> We generate the official POSBox images using the scripts in https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox. More specifically, we run posbox_create_image.sh. This builds an image called posbox.img, which we zip and upload to nightly.odoo.com for users to download.

When I saw that I thought, "Build? Don't think so. I'll just download the binary". So I download the image file from [here](https://nightly.odoo.com/master/posbox/). Now what? The documentation mentioned something about qemu. Ok. Maybe I need to use that.

So after installing qemu, reading documentation, looking up examples, I finally came up with:

    /usr/bin/qemu-system-x86_64 -machine accel=kvm -m 1024 -drive file=/path/to/posboxv15.img,media=disk,format=raw,index=0

Well that was a big fat failure!

A QEMU window pops up and it hangs indefinitely on "Booting from Hard Disk..." while simultaneously consuming 100% of my CPU.

Then I read that this could be because there are no bootable partitions, also tried adding the "bootable flag to each of the partitions in the image using fdisk, but that had no effect either.

I then after 2% more of my hair had fallen out I thought, "well, maybe I'll try that 'build' thing the documentation was talking about". So I download [the tools](https://github.com/odoo/odoo/tree/8.0/addons/point_of_sale/tools/posbox), `chmod +x` all the bash scripts. Execute `posbox_create_image.sh` and POOF. There's this QEMU window open with a login prompt. It works! So how do I get back here after I turn it off?

Looking at the source code, I see:

```
QEMU_OPTS=(-kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append 'root=/dev/sda2 rootfstype=ext4 rw' -hda posbox.img -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::18069-:8069 -net nic)
if [ -z ${DISPLAY:-} ] ; then
    QEMU_OPTS+=(-nographic)
fi
qemu-system-arm "${QEMU_OPTS[@]}"
```

OK, so I was using `qemu-system-x86_64` instead of `qemu-system-arm`. I'm new to this stuff. So trying to extrapolate what was going on there, I just execute:

    qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append 'root=/dev/sda2 rootfstype=ext4 rw' -hda posbox.img -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::18069-:8069 -net nic

Now, for some reason I get a Kernel panic and I have no idea how to get back to that login prompt without re-executing the script and downloading everything over again.

http://imgur.com/a/EbJIE

Anyway, the documentation should be updated so people know what to do with the image. And the fact that you need a kernel file from somewhere.

**Comment by mart-e** [comment]
Hello,

I am sorry you got in so many troubles but, no you do not need to care about qemu or other virtual tool. We use it in the image build process, not to boot the image.

To get your hardware working with the POS, you got two choices : 
- you flash a sd card with our images (or your custom one) and plug it into a rasberry pi
- you run a mini odoo on your laptop that will talk to your hardware
The posboxless is the second option.

Did you tried the [step by step](https://www.odoo.com/documentation/user/10.0/point_of_sale/overview/setup.html#id2) doc and got issue ?

By the way, the documentation repository is [odoo/documentation-user](https://github.com/odoo/documentation-user/), so do not hesitate to clarify and correct points that are not clear.

**Comment by multiwebinc** [comment]
@mart-e Thank you for the reply. I am talking about the second option. See the above pull request. Did I make any mistakes?

**Comment by mart-e** [comment]
Thanks for the pull request.
Closing this issue as not an odoo bug, lets's keep the discussion on the other repository.
