### ISSUE TITLE
Hide status bar in Task for some user group

### ISSUE THREAD

**Issue by user998877** [odoo/odoo#15427]
Impacted versions: odoo 9

Steps to reproduce:  

Current behavior: Now, I create group and add all user (Can see status bar) and in view form add **groups="__export__.res_groups_61"** 

Expected behavior: Is it possible create new user group, and that all user in this group can't change Task status (New, Current, Complete) hide or set to read only without add line in view **groups="__export__.res_groups_61"**.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @user998877,

Thank you for your report.
The Odoo bug tracker however is only for bugs in the official code, it is not the place to ask questions for custom development.
There are plenty of people who can help you with that on the official help forums (http://odoo.com/help).
P.S: Also add more information / code if you'd like good feedback, it is hard to help you with such a limited issue.

Regards,
Yenthe
