### ISSUE TITLE
[9] pivot view added in dashboard crash

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#15425]
Impacted versions:
9

Steps to reproduce:
1. Login to one of odoo 9 runbot
2. Go to Sales->Lead, change to pivot view
![image](https://cloud.githubusercontent.com/assets/8391358/22777111/28bdcdb4-eeed-11e6-961a-99952a8fdac2.png)

3.  Add to my dashboard
4. Go to Dashboard and see the error
![image](https://cloud.githubusercontent.com/assets/8391358/22777146/45a513ba-eeed-11e6-9ca6-dcdccbece62c.png)

Current behavior:
After the commit https://github.com/odoo/odoo/commit/b8922c964cfcf836be2c1afde3cf0bb4cd817ead, the above action will raise error.

Expected behavior:
No error.

**Comment by Yenthe666** [comment]
Hi @auyeung112002,

Thank you for your report.
I've just tested this on the latest Odoo 9 without any problems. Result:
![image](https://cloud.githubusercontent.com/assets/6352350/22880604/11bd7a1c-f1e3-11e6-83a4-1979457a4007.png)
Can you try again on the latest runbots please?

Regards,
Yenthe

**Comment by auyeung112002** [comment]
Yes, it is fixed a few days ago
