### ISSUE TITLE
[V9] website_forum module is reformating the text when I insert a link! 

### ISSUE THREAD

**Issue by lucode** [odoo/odoo#15429]
Impacted versions: V9/V10/SAAS

**Steps to reproduce:**
If I post an answer for a forum question and insert a link, in the edit mode it looks fine. When I save the post/answer the link will be replaced by a normal text again with a previous backslash "\Corda" instead [Corda](https://www.corda.net) for instance. Sometime every word in the text will be joined with a backslash. The server runs on Ubuntu 16.4 with nginx. 
**Current behavior:**
see above the same behavious in Odoo Forum: [Odoo Forum post](https://www.odoo.com/forum/help-1/question/odoo-forum-module-is-reformating-the-text-when-i-insert-a-link-114476)
does not depend on browser!
**Expected behavior:**
Storing the link in the correct format:
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @lucode,

Thank you for your report.
As Ermin said on the forums it seems to work fine.
Can you please add more information and a video or step-by-step info on how to reproduce this?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @lucode ,

There has been no response in a few months.
I'm closing this report as this is (no longer) reproducable.
If you can still reproduce this on the latest source code or on a runbot then please provide us with more information and I'll reopen this issue.

Regards,
Yenthe
