### ISSUE TITLE
[v8] Error in "products to move" wizard (stock.transfer.details)

### ISSUE THREAD

**Issue by JGarcia-Panach** [odoo/odoo#15440]
# Impacted versions: 8.0

# Steps to reproduce:

I have tried it in my own instance and on runbot (first stock related instance I have found in v8)

1.- Don´t log in with admin (the error does not appear)
2.- Go to purchases
3.- Create a new RfQ
4.- Add more than 1 unit of a product with Full lots traceability
![image](https://cloud.githubusercontent.com/assets/13234598/22823415/cf664542-ef83-11e6-9bea-9cfcb638001e.png)
5.- Confirm Order / Receive Order and Transfer
6.- Split the product in 2 lines
![image](https://cloud.githubusercontent.com/assets/13234598/22823454/02d12b5e-ef84-11e6-9183-26630d33efa3.png)
7.- Delete the second line and press Apply button
![image](https://cloud.githubusercontent.com/assets/13234598/22823485/3518c4f0-ef84-11e6-83b7-a8b95b3d3aab.png)
8.- Now appears "assign serial number" error
![image](https://cloud.githubusercontent.com/assets/13234598/22823512/4c755186-ef84-11e6-9046-aeada94ea795.png)
9.- Press ok, select lot and press apply again
![image](https://cloud.githubusercontent.com/assets/13234598/22823541/6639e14a-ef84-11e6-91fe-9085a345032a.png)

# Current behavior:

10.- And here is the error I was talking about
![image](https://cloud.githubusercontent.com/assets/13234598/22823560/797f3ee4-ef84-11e6-8e39-a15f57e3b384.png)

# Expected behavior:

It should transfer the line 

# Possible solution

It seems that when the first warning appears ("assign serial number" error), the wizard does not run again through "do_detailed_transfer" function (stock/wizard/stock_transfer_details.py)
But it only happens when you split and delete the line.

Sorry but we don't know how to fix it

Cheers

**Comment by Yenthe666** [comment]
Hi @JGarcia-Panach ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
