### ISSUE TITLE
[9.0,10.0] cache invalidation in onchange model creation with tracked fields

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#15449]
**Impacted versions:** 9.0 and 10.0

**Steps to reproduce:** in onchange mode create a record of a model inheriting `mail.thread` and having tracked fields

**Current behavior:** same behaviour mentioned in #14275; cache will be emptied and onchange will produce the creation and maybe the assignment to a many2one field

**Expected behavior:** cache won't be emptied and all assignments will be done

**Affected Code**: https://github.com/odoo/odoo/blob/9.0/addons/mail/models/mail_message.py#L959

**Comment by intero-chz** [comment]
ping @rco-odoo. As mentioned in my mail.

**Comment by pedrobaeza** [comment]
Closing as the fix mentioned in the other issue should apply here as well.
