### ISSUE TITLE
[UI] POS Ledgers in Accounting Dashboard

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#15451]
Current behavior: (9.0)

- POS ledgers are commonly defined as the store's physical sales vault
- Therefore one POS ledger can be used by several Cashiers/POS stations
- Therefore, there are several Cash Statements in place.
- Those cash statements do not have any sequential order nor do their corresponding initial and ending balances necessarily match.
- Therefore the dashboard view does show confusing information:
While the general ledger entries are OK after closing the POS Sessions, the **line chart arbitrarily shows a value that happens to be the last opening or closing balance of any arbitrary cash statement**.
- As a result the line chart is to no value and you start to mistrust the whole dashboard.

Expected behavior:

- POS Ledgers do have a different representation in accounting dashboard, for example showing aggregated statement data instead.

**Comment by pedrobaeza** [comment]
@jorenvo what do you think about this wishlist?

**Comment by jorenvo** [comment]
This is more an accounting question than a POS one, but isn't the solution to have separate journals per bank account (= physical POS in this case)? This way each graph contains only information for one bank account, which seems to be the way it's intended to be used.

**Comment by pedrobaeza** [comment]
Thanks for the answer, @jorenvo. I relabel this and waiting for more feedback.

**Comment by blaggacao** [comment]
@jorenvo You propose, in you answer a level of detail to he user, that is not always needed and does not always simplify operations. But technically it's a solution.

**Comment by qdp-odoo** [comment]
That's totally related to point of sale, as the problem never occurs when you're doing only accounting. 

Still, I recon this is a valuable feedback and, as such, someone from the PO team should handle that for a future improvement. (ping @lap-odoo )

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
