### ISSUE TITLE
Incorrect incomming email to lead/opportunity with 4 letter 1st level domain name

### ISSUE THREAD

**Issue by robertkein** [odoo/odoo#15456]
Impacted versions:
10.0

Steps to reproduce:
register alias domain in .mobi (dot mobi) zone
add catchall email or email alias
send email to that address

Current behavior:
nothing happen

Expected behavior:
lead or opportunity should be generated in pipeline

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Odoo is agnostic about the domain having 3, 4 or whatever letters, so the problem should be in your side: deployment, mail gateway, firewalls...

Closing as no trace of real issue.

**Comment by Yenthe666** [comment]
@robertkein Pedro is doing this on a voluntary basis and is in no way affliated with Odoo S.A. This also means he is not being paid and does this to help other people, just like I do. 
I guess you cannot complain a lot then, can you?
