### ISSUE TITLE
[10.0] sale.order action_cancel not @api.multi ready

### ISSUE THREAD

**Issue by boolit-eivydas** [odoo/odoo#15466]
**Impacted versions:**
10.0

**Steps to reproduce:**
Create an action that is callable from list (set `key2="client_action_multi"` in action) for `sale.order`. 
Try to cancel via method that calls `super(Model, self).action_cancel()` on selected `action_ids`.

**Current behavior:**
Throws `ValueError: Expected singleton: sale.order(4, 3)` in 
```
File "/opt/odoo/odoo-server10/addons/sale_stock/models/sale_order.py", line 66, in action_cancel
    self.order_line.mapped('procurement_ids').cancel()
```

**Expected behavior:**
Cancels all entries correctly.

**Comment by Yenthe666** [comment]
Hi there,

This has been handled in the meanwhile:
https://github.com/odoo/odoo/blob/4eaef03df3b324e6b51aa205309b280536fc74e0/addons/sale_stock/models/sale_order.py#L64-L67

Regards,
Yenthe
