### ISSUE TITLE
V[9]Backup from database manager fails / connection closed

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#15469]
Impacted versions: V9

Steps to reproduce:
1.Have 2 large databases (3 gb each)
2. Try to backup from database manager

Current behavior:
Connection is closed( after 1.2/1.3 GB dump)  even if memory and cpu limit parameters are set very high.

Expected behavior:
Backup should work.

Video/Screenshot link (optional):
Server config: 
CPU: 16 cores
Ram: 54 GB
Server odoo configuration file
admin_passwd = ********
csv_internal_sep = ,
data_dir = /opt/odoo/.local/share/Odoo
;data_dir = /opt/odooshare
db_host = False
db_maxconn = 64
db_name = False
db_password = **********
db_port = False
db_template = template1
db_user = odoo
dbfilter = .*
debug_mode = False
demo = {}
dev_mode = False
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
import_partial =
lang = en_US
limit_memory_hard = 6000000000
limit_memory_soft = 6942177280
limit_request = 8192
limit_time_cpu = 10800
limit_time_real = 14400
list_db = True
log_db = False
log_db_level = warning
log_handler = :DEBUG
log_level = debug
logfile = /var/log/odoo/odoo-server.log
logrotate = True
longpolling_port = 8072
max_cron_threads = 3
osv_memory_age_limit = 12.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
;server_wide_modules = None
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 17
xmlrpc = True
xmlrpc_port = 8069
xmlrpc_interface =
netrpc_port = 8070
netrpc_interface =

**Comment by lem8r** [comment]
Check your proxy server settings too

**Comment by sharkutz** [comment]
I used IP:8069 and closes connection. 
I used https://www.odoo.com/apps/modules/9.0/auto_backup/ and closes connection. 
I used Lynx :127.0.0.1:8069 and closes connection.
With pg dump from postgresql it dumps the full db. 

I tried multiple variations with 
limit_memory_hard = 6000000000
limit_memory_soft = 6942177280
limit_request = 8192
limit_time_cpu = 10800
limit_time_real = 14400
max_cron_threads = 3
and I can't get it to dump more that half of the db.

**Comment by sharkutz** [comment]
New logs from posgresql:

2017-02-13 16:49:20 EET STATEMENT:  UPDATE "bus_presence" SET "last_poll"='2017-02-13 14:49:18' WHERE id IN (1)
2017-02-13 16:49:29 EET ERROR:  could not obtain lock on row in relation "ir_cron"
2017-02-13 16:49:29 EET STATEMENT:  SELECT *
                                           FROM ir_cron
                                           WHERE numbercall != 0
                                              AND active
                                              AND nextcall <= (now() at time zone 'UTC')
                                              AND id=2
                                           FOR UPDATE NOWAIT
2017-02-13 16:49:29 EET ERROR:  could not obtain lock on row in relation "ir_cron"
2017-02-13 16:49:29 EET STATEMENT:  SELECT *
                                           FROM ir_cron
                                           WHERE numbercall != 0
                                              AND active
                                              AND nextcall <= (now() at time zone 'UTC')
                                              AND id=4
                                           FOR UPDATE NOWAIT
2017-02-13 16:59:22 EET ERROR:  could not obtain lock on row in relation "ir_cron"
2017-02-13 16:59:22 EET STATEMENT:  SELECT *
                                           FROM ir_cron
                                           WHERE numbercall != 0
                                              AND active
                                              AND nextcall <= (now() at time zone 'UTC')
                                              AND id=4
                                           FOR UPDATE NOWAIT
2017-02-13 16:59:23 EET ERROR:  could not obtain lock on row in relation "ir_cron"
2017-02-13 16:59:23 EET STATEMENT:  SELECT *
                                           FROM ir_cron
                                           WHERE numbercall != 0
                                              AND active
                                              AND nextcall <= (now() at time zone 'UTC')
                                              AND id=4
                                           FOR UPDATE NOWAIT
2017-02-13 17:01:53 EET ERROR:  could not serialize access due to concurrent update
2017-02-13 17:01:53 EET STATEMENT:  UPDATE "bus_presence" SET "last_poll"='2017-02-13 15:01:52' WHERE id IN (1)

**Comment by sharkutz** [comment]
Fix abode issue removing cron for featchmail

**Comment by Yenthe666** [comment]
@sharkutz so your problem is fixed? (judging by your last comment)
