### ISSUE TITLE
New compiled templates are impossible to debug

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15468]
Impacted versions: 10

Steps to reproduce: Run odoo with `--dev all` and add `<t t-debug="wdb"/>` to a template, then render it (and have a wdb server running and connected).

Current behavior: See https://github.com/Kozea/wdb/issues/92#issue-203643038

![](https://cloud.githubusercontent.com/assets/973709/22373362/c43fd044-e4a1-11e6-8740-d8beb0383e16.png)

Empty, completely.

Expected behavior: See the template source

wdb developer [suggested](https://github.com/Kozea/wdb/issues/92#issuecomment-279149949) to [take a look into jinja](https://github.com/pallets/jinja/blob/master/jinja2/debug.py) to provide sane template debugging.

@Tecnativa

**Comment by Gorash** [comment]
Hi,

It's not a bug, it is working as intended. You can see the template source in the views settings menu or in psql. Your debugger is called inside the compiled code (inside the generated python function), you have only access to "values" and "options" dict.

You can use advanced debug tools (install "astor" lib) and add "profile" kwargs options on the render py method to show the generated code inside your console. It's an internal feature, I added this in order to profile the performance of odoo (it allows me to see which line, field, record are slow).

* "profile" kwargs is a number: the qweb profile only the line who take more milliseconds of this number

I wish you good fix and optimization ;)

**Comment by Yajo** [comment]
Sorry, could you explain a little bit further where to add the profiling options?

**Comment by Gorash** [comment]
in python as kwargs (this feature use print, however if this feature passes for lambda users, we will probably change the functioning):

self.env['ir.qweb'].render('base.contact', {key:val}, profile=0)

PS: In all logic it should work also with the context but I did not test => .with_context(profile=0)

**Comment by Yajo** [comment]
Why was this not added as a `--dev` option? It makes not much sense to do it as you say... (although thanks for the info)

**Comment by Gorash** [comment]
No, this feature was not meant for the user or developer lambda. I put it in the code because it's useful that's all. I created features that I do not necessarily put in the code. However, given your request, we will consider converting it to make a clean log and put it in the option.

**Comment by Yajo** [comment]
My point was that, as a developer, I expect `--dev qweb` to let me debug views, and having empty screens is not much useful. It gives the impression that feature is actually broken. But you already got my point, so thank you very much, I hope we can get it working in future releases 😉

**Comment by nhomar** [comment]
On Tue, Feb 21, 2017 at 3:56 AM, Christophe Matthieu <
notifications@github.com> wrote:

> Hi,
>
> It's not a bug, it is working as intended. You can see the template source
> in the views settings menu or in psql. Your debugger is called inside the
> compiled code (inside the generated python function), you have only access
> to "values" and "options" dict.
>
> You can use advanced debug tools (install "astor" lib) and add "profile"
> kwargs options on the render py method to show the generated code inside
> your console. It's an internal feature, I added this in order to profile
> the performance of odoo (it allows me to see which line, field, record are
> slow).
>
>    - "profile" kwargs is a number: the qweb profile only the line who
>    take more milliseconds of this number
>
> I wish you good fix and optimization ;)
>

If something is broken, then silence it "Nice 'import this'" following! ;-)

IMHO following very simple good practices, a very explicit view should be
shown **at least** on debug mode, a blank view is simply crazy.

**Comment by Gorash** [comment]
The empty screen ... will remain empty ^^ it is normal... and I do not think profiling will be useful. For debugging, I use only the debugger to display options and values. Wanting to see the compiler code is useless, to debug it would be more interesting to have the template with its applied heritages, it seems to me.
The profiling only serves me for the optimizations for the speed of the framework. I hope it will be useful to you although I doubt it.

I wish you good optimizations ;)

**Comment by nhomar** [comment]
@Gorash 

If you read the original issue, it is not about performance (the deviation of the topic was in the middle of the thread).

the main request is "instad a blank document an uncompiled source with the error explícit".

Regards.

PS: Save the world, If you make more programming powerful options then you save millions of computing time....
