### ISSUE TITLE
Why does _validate_fields force the raise of validation errors? It makes debugging in @api.constrains function complicated.

### ISSUE THREAD

**Issue by jcdrubay** [odoo/odoo#15479]
Impacted versions: 10.0

Steps to reproduce: Code an api.constrains function that raises a serious technical exception.
```
@api.one
@api.constrains('name', 'description')
def _check_description(self):
    if self.name == self.description_oups_i_typed_it_wrong:
        raise ValidationError("Fields name and description must be different")
```

Current behavior: The output is a nice ValidationError message in the WUI, and nothing in logs.

Expected behavior: Technical Exception should be raised as Exception with stacktrace and should be visible in the logs as Exception.

Or a trade-off could be found...

Current code:
```
                try:
                    check(self)
                except ValidationError, e:
                    raise
                except Exception, e:
                    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
```

Expected code:
```
                check(self)
```

Expected code with trade-off (raise a ValidationError, but logs the error stacktrace):
```
                try:
                    check(self)
                except ValidationError, e:
                    raise
                except Exception, e:
                    logging.error(e)
                    import traceback
                    logging.error(traceback.format_exc())
                    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
```

Extra Note: I believe that similar patterns should be added to the Access Controls. I think that debugging access control issues (using complex ir.rule) is the most painful thing when coding in Odoo.

**Comment by pedrobaeza** [comment]
@jcdrubay if you have any possible improvement, please make a PR (for master branch). Take into account that the system is designed this way as it's a server/client architecture, so raising exceptions in server side will make the system to not work as expected on the client side (as the code execution is interrupted).

Closing this waiting for a possible PR.
