### ISSUE TITLE
[16.0] migration: x.y.z migration folder not working as expected

### ISSUE THREAD

**Issue by MartinAavastik** [odoo/odoo#154743]
Impacted versions:
16.0

Steps to reproduce:
create a migration script in the path
<module-name>/migrations/3.7.0/post-migrate.py

using semver change the manifest version to "3.7.0" and upgrade module

Current behavior:
migration script is not run

Expected behavior:
migration script should be run, since it should be 16.0.3.7.0

Additional Info:
This happens mostly because:
https://github.com/odoo/odoo/blob/396e0e276aacd76a659690c34cb80a182ab0120d/odoo/modules/migration.py#L112
where
```python
def convert_version(version):
    if version.count('.') >= 2:
        return version  # the version number already contains the server version
    return "%s.%s" % (release.major_version, version)
```
line 2 should be `if version.count('.') > 2:`

This is fixed in v17 and master
https://github.com/odoo/odoo/pull/118420

Commit that fixed v17
https://github.com/odoo/odoo/commit/6c2a487ef9cc7efef65abb04780a236da6521eb4#diff-4f4d1294e4370c88e155c98b6227e7a7991a9f2ea656e1df569fa78a16091518R156

**Comment by dansanti** [comment]
yoy must name yor folder wit odoo version like , migrations/16.0.3.7.0

**Comment by vava-odoo** [comment]
Hi @MartinAavastik 
I don't see any standard odoo issue here, and the commit you cite won't be backported.
Cheers
