### ISSUE TITLE
qweb2 error report "Error evaluating template" doesn't include template name

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#15476]
Impacted versions: All

Steps to reproduce: Make a wrong template in order to get an "Error evaluating template"

Current behavior: The error context doesn't include the name of the template.
 
In this [line](https://github.com/odoo/odoo/blob/10.0/addons/web/static/lib/qweb/qweb2.js#L464) stays:

```python
this.tools.exception("Error evaluating template: " + error, { template: name });
```

I was debugging an error in the template and noted that name is always missing there. 

I suspect that two lines bellow the sames happen:

```python
 this.tools.exception("Error evaluating template: (IE?)" + error, { template: name });
```

Expected behavior:

Eight lines bellow we have:

```python
 return this.tools.exception("Template '" + template + "' not found");
```

and in that point the **template** variable has the name of the template. So I suppose that the code should be something like:

 ```python
 this.tools.exception("Error evaluating template: (IE?)" + error, { template: template });
```

The code [here](https://github.com/odoo/odoo/blob/10.0/addons/web/static/lib/qweb/qweb2.js#L45) stays:

```python
if (context.template) {
  prefix += " - template['" + context.template + "']";
}
```

so I suppose that once the problem is corrected we will have the template name also in the error message, which is very useful when receiving errors from templates.

Maybe it just happen to me, because that code is 6 years old and nobody has complains.

**Comment by pedrobaeza** [comment]
Can you please make a PR to master branch for improving this?

**Comment by pedrobaeza** [comment]
Closing this as no answer.
