### ISSUE TITLE
 Error creating database in Odoo 9

### ISSUE THREAD

**Issue by Jefferson16Jb** [odoo/odoo#15478]
Impacted versions:
9.0
Steps to reproduce:

Current behavior:

Hello, I am doing a system in odoo 9 but creating a database indicates an error, according to other forums indicate to me that it is the version. Error: openerp.addons.base.ir.ir_cron: Skipping the electronic database as its base version is not 9.0.1.3. Thanks for your help.

**Comment by Yenthe666** [comment]
Hi there,

Not really a bug but a way of deploying / updating. The module does not match up with your base Odoo version.
