### ISSUE TITLE
[10.0] product.template: default_code is not cleared when creating variants

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#15475]
Impacted versions: 10.0 (maybe previous too)

Steps to reproduce:
1. Start creating product.template.
2. Type name and default code.
3. Add product's attribute with couple variants.
4. Press Save.
Trick is to enter everything before first save.

Current behavior: Product template is saved with default code provided but default code is hidden from form (unable to delete it).

Expected behavior: default_code on product.template should be cleared. And probably moved to first product variant.

Video/Screenshot link (optional):
![product-template-with variants](https://cloud.githubusercontent.com/assets/5942291/22885426/15005f68-f202-11e6-90f2-156c69b93e24.png)

**Comment by pedrobaeza** [comment]
Well, the only issue is visual, showing the internal reference between brackets on the name_get of the template, but it can be improved indeed.

@mart-e who can attend this?

**Comment by mart-e** [comment]
Hi,

If I am not mistaken, this happens only when you create the product. As soon as you set a reference on one of the variant, everything goes back to normal.

You are however right we have a different behaviour (which I can not explain) when you create everything in one step or add the variants afterwards.

**Comment by pedrobaeza** [comment]
Yeah, it only happens on that case. I think we can add a check on create overwriting to avoid this inconsistent situation.

**Comment by pedrobaeza** [comment]
@mart-e any news about this?

**Comment by mart-e** [comment]
I suspect some framework weird cache non-invalidation (as the code is supposed to handle this) but I was not able to identify it clearly.
Maybe @rco-odoo has a better idea?
