### ISSUE TITLE
Website and ERP security.

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#15472]
I am having the following issue.

Let's say you want to setup odoo were website and the whole ERP story is separate. It is simply impossible to separate ERP modules from the website.

I have a few suggestions to solve this problem:

- The website calls should go through a different url. Something like `/website` at this moment it uses a combination of `/web` and `/website` what makes it impossible to properly separate it. If everything goes trough `/website`, we could just proxy `/website` for the actual website.

- Another possibility is a custom core module that only loads the website (and modules depending on it). I messed around with the load flag and the survey module. And it does work to load the survey module only. However it kinda messes up the icons. So we could have 2 odoo instances. 1 for the ERP and 1 for the website. And the only difference would be the way they are run. `--load=web_website` or `--load=web`.

**Comment by thomassomko** [comment]
Atm I think I solved this with nginx with this location rule:
```
location ~* ^/web/(?!(content|static)).*$ {
    deny all;
 }
```

I still think its far from optimal tho.

**Comment by Yenthe666** [comment]
Hi,

Thank you for your report.
At the moment there is no default option to separate the website / back-end from eachother as you ask.
I don't really think it is on the roadmap or wishlist either but I've labelled it wishlist. Every once in a while somebody from Odoo goes over all wishlist items and check if they'd like to add them.
Thank you for your suggestion.

Regards,
Yenthe
