### ISSUE TITLE
[17.0][Accounting] ACL error on menu Amounts to Settle with Billing group

### ISSUE THREAD

**Issue by qpeyramale** [odoo/odoo#154752]
Impacted versions: 
17.0

Steps to reproduce: 
- Log with a user with only Billing access
- Go to Accounting/Customers or Vendors/Amount to Settle

Current behavior:
ACL error (might need a second web browser refresh to get it)
`You are not allowed to access 'View' (ir.ui.view) records.`

Expected behavior:
Open the view with no restriction.

On further notice, it mays be related to this piece of code in account/account_move_line.py
https://github.com/odoo/odoo/blob/0751d887e6d4f810d779183d3bf17806cccaf97e/addons/account/models/account_move_line.py#L452C5-L458C19

I think it missing a `sudo().browse...` for global access.

Thank you

Edit: The ACL error occurs with all accounting's groups. It expects to have Administration/Settings group to read the view.

**Comment by vava-odoo** [comment]
Hi @qpeyramale 
Indeed, it was fixed in https://github.com/odoo/odoo/commit/034137d25b8933f57b8da598ca7a20ec34305092
Thanks for reporting!
Cheers
