### ISSUE TITLE
odoo rtf html field auto clear when click save button

### ISSUE THREAD

**Issue by cosbeta** [odoo/odoo#15481]
Impacted versions:9.0

Steps to reproduce:
`content = fields.Text(required=True)`
or
`content = fields.Html(required=True)`
` <field String="Content" name="content" widget="html"/>`

Current behavior: in editform ,when click save button , content in field will be cleared ,and the popup content is invalid error.
then I paste content in the field again, and click save button ,this time , field will not be cleared

Expected behavior: do not clear the field when click save button

Video/Screenshot link (optional):
<img width="517" alt="screen shot 2017-02-14 at 12 01 52 pm" src="https://cloud.githubusercontent.com/assets/2989276/22914777/80f114a0-f2ad-11e6-9fce-67a38b027b7a.png">

**Comment by intero-chz** [comment]
Hi, do you use the current version? I thought this bug was fixed a month or two ago.

**Comment by cosbeta** [comment]
9.0c-20161117 community version

**Comment by intero-chz** [comment]
That version seems to be too old. The first issue on that topic can be found here: #14648. It was fixed in early january.

**Comment by Yenthe666** [comment]
Hi @cosbeta,

Please update your Odoo code base, it should work without any issues on the newest versions.
Can you please update and try again?

Regards,
Yenthe

**Comment by cosbeta** [comment]
I have fixed this issue via this #14648.
and I have not update to version 10 yet

thanks
