### ISSUE TITLE
active=False的产品点击销售和追溯提示错误

### ISSUE THREAD

**Issue by itrojan** [odoo/odoo#15480]
File "/Users/lanyun/python/odoo10/addons/stock/models/product.py", line 531, in action_view_stock_moves
    action['context'] = {'default_product_id': products.ids[0]}

**Comment by Icallhimtest** [comment]
How on earth are we supposed to know what the problem is from such a message ?

`active = False` means something is archived, maybe you've archived something that you shouldn't have ?

**Comment by Yenthe666** [comment]
Hi @itrojan,

I'm closing this report as it has no context, information or anything to reproduce this.
Please create a new issue in which you give more information and a testing scenario.
We really have no clue what you're talking about as there is not even a version in your topic.

Regards,
Yenthe
