### ISSUE TITLE
[i18n] use pluralized instead of (s)

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#154960]
https://github.com/odoo/odoo/blob/954497195d0dfa022d0075f8978f39025bb0d2cd/addons/website_slides/static/src/xml/website_slides_share.xml#L70

transfix report error "The translation does not contain the same number of 左圆括号 '(' as the original phrase"

![image](https://github.com/odoo/odoo/assets/1404460/00d47712-5945-4c14-b052-aa74f5dfdb5a)

@mart-e

There are over 100 similar situations in the codebase. It causes the Chinese translation to fail the check on the Transifex platform.

**Comment by jeffery9** [comment]
when translate those into Chinese, we should grid of (s), as Chinese has not pluralized

**Comment by mart-e** [comment]
The settings in global to every language unfortuantly. As it's not an error but only a warning that can be ignored, I suggest we keep it.
