### ISSUE TITLE
HIGH VULNERABILITY: Moment.js 2.18.x < 2.29.4 Regular Expression Denial of Service

### ISSUE THREAD

**Issue by HafedhRahmani** [odoo/odoo#155008]
Hello,
In light of recent security audits conducted by our clients, various vulnerabilities and concerns have been brought to our attention. Our clients rely on us for robust and secure solutions, and it is through their diligent assessments that a specific issue has been identified, necessitating immediate attention and action. The vulnerability in question pertains to Moment.js, specifically versions 2.18.x prior to 2.29.4, which are susceptible to a regular expression denial of service (ReDoS) vulnerability via the preprocessRFC2822() function in from-string.js.
This issue is about: https://github.com/odoo/odoo/blob/16.0/addons/web/static/lib/moment/moment.js#L2

**Description:**
According to its self-reported version number, Moment.js is 2.18.x prior to 2.29.4. Therefore, it may be affected by a regular
expression denial of service vulnerability via the preprocessRFC2822() function in from-string.js, when processing a very long
crafted string.
Note that the scanner has not tested for these issues but has instead relied only on the application's self-reported version
number.

**Solution**
Upgrade to Moment.js version 2.29.4 or later.
https://github.com/moment/moment/issues/6012

![2024-02-22_12-28-35](https://github.com/odoo/odoo/assets/36736035/bc2124fa-8812-40c7-bbe6-32a201a225da)

**Comment by ray-odoo** [comment]
The recommended method to report suspected vulnerabilities is via https://www.odoo.com/security-report

That team are not regular participants here
