### ISSUE TITLE
[10.0] Unable to edit webpages when having multi-lang website without automatic footer

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#15503]
Impacted versions: 10.0 (community and enterprise)

Steps to reproduce: 
- Install a new Odoo and enable the website
- Add another language to the website
- Disable the automatic footer on the website
- Try to edit the master version of the website

Current behavior: You're unable to edit webpages with all this criteria checked. The source of the problem is coming from the Javascript (https://github.com/odoo/odoo/blob/10.0/addons/website/static/src/js/website.translator.js#L43):
```
 $link[0].search += ($link[0].search ? '&' : '?') + 'enable_editor=1';
```
This line will be undefined if the automatic footer is disabled on the website. Because this is undefined an editable link cannot be build and this makes it unable to edit the website, which throws a JavaScript error in the console that is not shown to the user:
![image](https://cloud.githubusercontent.com/assets/6352350/22970991/70ac72b6-f374-11e6-905b-ffa0bcbf6321.png)

Expected behavior: You can edit the website in multiple languages, even if the footer is disabled.

**Comment by JKE-be** [comment]
WIP: https://github.com/odoo-dev/odoo/commit/7bdec51d799e96ef22a51a3b7fe71c464b73d3f2

**Comment by JKE-be** [comment]
Hello Yenth,

Could you confirm that this commit fixes your issue ? 

https://github.com/odoo-dev/odoo/commit/608652c699c667c05e5db796e7a17bad51eb9303

Thanks

**Comment by Yenthe666** [comment]
Hi @JKE-be seems to work fine on my side. Can you make a PR on this repository (don't merge it yet) so I can test it a second time on a runbot too?

**Comment by JKE-be** [comment]
I have no really doubt that it works... 
but if you want you can test it here :http://runbot.odoo.com/runbot/2/10.0-nethys-jke (in 15min, it is building).

Except if you report a bug, it will be merged this week.

**Comment by Yenthe666** [comment]
Hi @JKE-be,

I've double checked it but it is still a problem:
![image](https://cloud.githubusercontent.com/assets/6352350/23274225/27f38f0c-fa02-11e6-80f4-6b5c7d3ccb70.png)
coming from here:
```
        if ($link.length()) {
            $link[0].search += ($link[0].search ? '&' : '?') + 'enable_editor=1';
            $link.click();
        }
```

regards,
Yenthe

**Comment by JKE-be** [comment]
sorry


let 20 min to runbot to build the right branch :/ And ll will be ready ;)

**Comment by Yenthe666** [comment]
@JKE-be can you link me the new runbot? Is the PR already merged in Odoo? Thanks.
