### ISSUE TITLE
Can't update Sales Order Send by Email Template

### ISSUE THREAD

**Issue by safecoms** [odoo/odoo#15501]
Impacted versions: odoo 10

Steps to reproduce:

Current behavior:
I can't update Sales Order Send by email Template!
Expected behavior:
I would like to update sales order send by email template. how to update send by email template desigin layout?
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @safecoms,

You can both edit a sale order and an e-mail template. You can edit the template from settings > Technical > E-mail > templates:
![image](https://cloud.githubusercontent.com/assets/6352350/26624080/152fd18e-45f0-11e7-8925-337adb4244f8.png)
Closing as this is not a bug but a question.

Regards,
Yenthe

**Comment by safecoms** [comment]
Thank you Yenthe,

I actually forgot about this.
You are right more of a question.
Thank you for the follow up.
