### ISSUE TITLE
Module translation issue : works randomly

### ISSUE THREAD

**Issue by tandrieuxx** [odoo/odoo#15505]
Impacted versions: 10.0 Community & Enterprise

Steps to reproduce: Create a module inheriting existing models, form views and reports (in my case the expense form view, expense report form view, and expenses report), create new fields and make them appear in views and reports. Follow the internationalization guides provided by Odoo (Odoo's developer documentation, "Build a module/Internationalization" or "Translate a module") to translate your module, and see what happens.

Current behavior: I've strictly followed the i18n tutorial by Odoo. Half of my terms are correctly translated into french, the other half stays in english (in form views and report). I had to give a first version of my module to the people I was doing it for (people of my own organization), it didn't matter if it was in english. Surprise, my translation was perfectly working on their environment. Problem, I had to improve my module, add some fields and put them in the report, so I had to update the translation. But I still have the problem on my environment, so I can't predict if it will work for them. I asked someone in my team to see what happens for him, and he have the same problem. However, the terms translated and not translated for him are not the same than for me ! Both of our Odoo installations are updated from last week... I've tried everything, corrected the translations hundreds of times, synchronized terms, reloaded the translation, tried on a new base, deleted and updated translations... Nothing works.

Expected behavior: Every term should be translated no matter the environment the module is installed on.

Video/Screenshot link (optional):
https://i.imgur.com/3XqUDSY.png
Here "Montant HT" is translated, "Recoverable taxes" is not, both are fields created by my module.
https://i.imgur.com/EW8N9Sw.png
Here nothing is translated !

**Comment by mpamped** [comment]
Are you running in devmode (i.e. do you start `odoo.py` with `--dev=all` or similar?)

I have the same problem, everything works when I remove devmode flag.

**Comment by tandrieuxx** [comment]
Thank you ! Removing `--dev=all` has resolved the problem 👍

**Comment by mpamped** [comment]
I do think you should leave this issue open. I think it's a bug in devmode. Would be nice if translations worked normally there.

**Comment by pedrobaeza** [comment]
@mart-e can you confirm this problem using `--dev=all` mode?

**Comment by mart-e** [comment]
Hello,

The option `-- dev xml` is:

> xml: read template qweb from xml file directly instead of database. Once a template has been modified in database, it will be not be read from the xml file until the next update/init.

So it means, you are not working with the database for the views. As the translations are stored in the database, it actually make sense.
This option is to be used when you are actually developping on your views, to see the result directly.
