### ISSUE TITLE
IM livechat on external site

### ISSUE THREAD

**Issue by fiddler0305** [odoo/odoo#15518]
## Impacted versions:
**10 (Proxy mode)**

## Steps to reproduce:
Include links from IM livechat on an external website

```html
<link rel="stylesheet" href="http://internal_url/im_livechat/external_lib.css"/>
<script src="https://internal_url/im_livechat/external_lib.js" type="text/javascript"></script>
<script src="https://internal_url/im_livechat/loader/1" type="text/javascript"></script>
```

## Current behavior:
live chat works on all internal url

BUT
external site get nothing, and I saw these 404 errors on console

```
http://external_url/web/webclient/qweb?mods=
404 (Not Found)  external_lib.js:951
http://external_url/web/webclient/bootstrap_translations
404 (Not Found) external_lib.js:951
http://external_url/im_livechat/init
404 (Not Found) external_lib.js:951
```

## Expected behavior:
**requests should access internal_url**
do I have to setting CORS?

## Video/Screenshot link (optional):
N/A

**Comment by htetard** [comment]
same probleme

**Comment by gokhanerdogdu** [comment]
Similar problem also exists on our system.

external_lib.js:951 GET https://..../index.php/404-error net::ERR_TOO_MANY_REDIRECTS
