### ISSUE TITLE
[8.0] List View - if editable and create="False" - Save/Cancel buttons are missing

### ISSUE THREAD

**Issue by kevink8888** [odoo/odoo#15519]
Impacted versions: 8 

Steps to reproduce: create a tree view with editable="bottom" create="false"

Current behavior: while editing a line, there is no Save/Cancel buttons

Expected behavior: having a Save/Cancel buttons but no Create/Import ones.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @kevink8888 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
