### ISSUE TITLE
Attchement URLs have access to anyone without user login. 

### ISSUE THREAD

**Issue by amitv9493** [odoo/odoo#155369]
Impacted versions: 17.0

Steps to reproduce:
Visit the link: localhost:8069/web/content/3920?model=ir.attachment

Current behavior:
An anonymous user can easily access this url and can download the file without login to the backend. 

Expected behavior:
User without login should not have the access to the attachment links and should prompt to the login screen.

**Comment by intero-chz** [comment]
Are you sure the the Attachment with ID 3920 isn't public or you're in a session as user (after login)?

**Comment by intero-chz** [comment]
Try to open [this](https://58875592-17-0-all.runbot146.odoo.com/web/content/3096?model=ir.attachment) and you should get a  Not Found.

[This one](https://58875592-17-0-all.runbot146.odoo.com/web/content/3071?model=ir.attachment) i made public, you should see a pdf.

**Comment by amitv9493** [comment]
Right. I looked into the documentation of odoo but I wasnt able to find the solution. Thanks a lot.
