### ISSUE TITLE
[10.0c] (Logged in as Admin) Can't Click 'Website' on iPhone (Safari & Chrome)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#15551]
<h1>Impacted Versions:</h1>
10.0c

<h1>Environment:</h1>
<ul>
<li>Runbot 10.0c Latest Branch</li>
<li>iPhone (have not tested other Mobile OS's but assume it's the same story)</li>
<li>Safari or Chrome Browser</li>
</ul>

<h1>Steps to Reproduce:</h1>
<ul>
<li>Go to runbot 10.0c branch</li>
<li>Login as admin and then go back to the website frontend</li>
<li>Try to click on the 'Website' item in the nav (top left with four square icon) and it will not dropdown with a menu</li>
<li>Try to click the 'hamburger' menu (ie. the three horizontal lines icon for deploying the menu in mobile mode). This menu is the one containing: Content, Customize, Promote menu items</li>
<li>With the 'hamburger' menu active (dropped down displaying menu items), now click the 'website' menu item (top left with four square icon)</li>
</ul>
<h1>Current Behaviour:</h1>
With the mobile ('hamburger' style) menu not active the 'website' menu item (top left four square icon) will not deploy when clicked on iPhones in the browser.

With the mobile menu active (ie. deployed and displaying Content, Customize, and Promote menu items), clicking the 'website' menu item will successfully deploy the website menu (including discuss, sales, inventory, etc.).

See screenshots of the behaviour for a clear understanding of what's going on.

<h1>Expected Behaviour:</h1>
The 'website' menu item (top left) should be able to be deployed independently of the mobile menu (top right), and you should be able to use one or the other independently.

<h1>Video/Screenshot Link (optional):</h1>
<h2>Click on website menu item (top left) without clicking mobile menu (top right 'hamburger' icon) - no website menu deploys</h2>
<img src="https://cloud.githubusercontent.com/assets/2337666/23090640/9973db2e-f5dd-11e6-991c-d425239888e8.jpeg"/>

<br/><br/>
<h2>Click on mobile menu (top right) to deploy, and then click top left 'website' menu - successfully deploys</h2>
<img src="https://cloud.githubusercontent.com/assets/2337666/23090641/9a3cc0e8-f5dd-11e6-9230-0668ac6c3d88.jpeg"/>

**Comment by lukebranch** [comment]
@Yenthe666 ,

This is a low priority issue, but an annoying one nonetheless. Please take a quick look when you have a second.

I believe this should be a pretty quick fix and may be related to z-index or something similar, as the menu appears to deploy hidden inside the mobile (top right) menu item for some reason.

**Comment by lukebranch** [comment]
@JKE-be ,

Thanks for the confirmation, actually this does not seem to be OS or browser specific, it's happening on desktop's in mobile sized browser windows as well.

**Comment by JKE-be** [comment]
Thanks for the detailled report and feedback.
@cocographique is Working on it ...

Probably a one line patch of css to fix it :)

**Comment by lukebranch** [comment]
@JKE-be ,

Thanks for looking into it! I haven't looked at the CSS, but I believe you're probably right, I think this is probably z-index related or something similar.

**Comment by lukebranch** [comment]
@JKE-be ,

Sorry to ping you, I know you guys are very busy. 

Would you mind checking on this issue again when you have a moment?

It still seems to be an issue in the latest runbots.

**Comment by Yenthe666** [comment]
As we're in a code sprint & some of the guys of Odoo are here too.
@Cocographique can you give an update? (CC @mart-e )

**Comment by lukebranch** [comment]
@Yenthe666 ,

Thanks for the prompt reply! Sorry, I didn't realise you guys were in Barcelona.

**Comment by Yenthe666** [comment]
@lukebranch no problem, we're here to fix as many issues as possible so this fits in.
@JKE-be thanks man! Another +1 for you.

**Comment by lukebranch** [comment]
Awesome, thanks guys!
