### ISSUE TITLE
[Odoo 10] Is Documentation up to date?

### ISSUE THREAD

**Issue by franckysolo** [odoo/odoo#15555]
Hello,
i'm trying to create a JavaScript interface extension but the documentation seems to be not up to date
I had tested two implementation :
```js
openerp.my_custom_module = function(instance, local) {
local.CustomWidget = instance.Widget.extend({}) ///...
})
```
this version work!
if i take a look at default module implementation, the module is just define but where can we require it
```js
odoo.define('my_custom_module', function (require) {
  var CustomWidget = require('web.Widget'); //...
})
```
This one don't work!
The documentation is very confused, what the good implementation, can you clarify that?
Thanks

**Comment by ged-odoo** [comment]
Could you tell us what version you are using?  The first version is the old style, and the second version is the new style.  The second one should work, and the first one will be broken soon (it is deprecated)

**Comment by franckysolo** [comment]
hello,
I'm using the last version 10.0
So i managed to make it work with define like this : 
```js
odoo.define('my_custom_module', function (require) {
  var Widget = require('web.Widget'); //...
  require('website.website'); // for jquery ready to use
  var CustomWidget = Widget.exend({ // ... });
  // then make an instance 
  var widget = new CustomWigdet();
  widget.start();
  return widget;
});
```
If i don't create an instance and don't start the custom widget, the module is never loaded
Is is the good way to implement module js?
 or is there an another way to achieve this?

**Comment by ged-odoo** [comment]
Without seeing your code, it is difficult to be sure.  I can tell you that it is extremely rare to have to call the start method directly, it should be up to the framework to call it when you append your widget in the dom.  

So, assuming that you really need a widget (that is, something that is represented in the DOM), then I think that you should slightly change your code like this:

odoo.define('CustomWidget', function (require) {
  var Widget = require('web.Widget'); //...
  var CustomWidget = Widget.exend({ // ... });
  return CustomWidget;
});

odoo.define('my_custom_module', function (require) {
  var CustomWidget = require('CustomWidgetWidget'); //...
  require('website.website'); // for jquery ready to use

  var widget = new CustomWigdet();
  widget.appendTo($('body'));

  return widget;
});

The first module is just a definition, it is reusable and can be extended.  The second module just import the definition and instantiate it.  Note that widgets are supposed to be added to the dom by a method such as appendTo.  This will correctly prepare the root of the widget, and call the start method.

**Comment by franckysolo** [comment]
ok thanks, it's more clear for me now i'm going to test this implementation
i'm writing a widget extension for website_sale module
my js code was 
```js
odoo.debug = true;

odoo.define('website_sale_custom', function (require) {
  'use strict';
  var Widget = require('web.Widget');
  var core = require('web.core');
  require('website.website');

  var TexturePicker = Widget.extend({
    template: 'website_sale_custom.index',
    init: function () {
      this.eventType = 'click touchstart';
    },
    start: function () {
      this.menu_dropdown();
      this.action_select();
    },
    menu_dropdown: function () {
      $('.texture-dropdown').on(this.eventType, function (e) {
        e.stopImmediatePropagation();
        if (!$(this).next().hasClass('is-open')) {
          $(this).addClass('is-active');
          $(this).next().addClass('is-open');
        } else {
          $(this).removeClass('is-active');
          $(this).next().removeClass('is-open');
        }
      });
    },
    action_select: function () {
      $('.texture-row').on(this.eventType, function (e) {
        // e.stopImmediatePropagation();
        var link = $(this);
        var icon = link.find('.status:first');
        var value = link.attr('data-value')
        var css = link.attr('data-class')
        $('#texture-text').html(value)
        $('#texture-preview').removeAttr('class').addClass(css)
        $('.texture-row').removeClass('is-selected');
        $('.status').addClass('hide');
        link.addClass('is-selected');
        icon.removeClass('hide')
      });
    }
  });

  var t = new TexturePicker();
  t.start();
  return t;
});
```
