### ISSUE TITLE
[10.0E] MRP work center capacity bug

### ISSUE THREAD

**Issue by thegunshow** [odoo/odoo#15554]
Impacted versions: Odoo 10.0e+e-20170213 (Enterprise Edition)

Steps to reproduce: Create 2 MRP MOs that both use the same work center. Start both WOs at the same time.

Current behavior: Both can be started

Expected behavior: The 2nd should not start until the 1st has been completed

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/16087167/23102087/2349dd94-f6ab-11e6-8547-8be47d526c0e.png)

![image](https://cloud.githubusercontent.com/assets/16087167/23102091/39d3ce44-f6ab-11e6-9e07-b41d2ecd3cb4.png)

**Comment by jco-odoo** [comment]
This capacity was done for planning purposes not as a constraint to avoid someone to do something.
