### ISSUE TITLE
Register Salesperson into Multiple Teams

### ISSUE THREAD

**Issue by gokhanerdogdu** [odoo/odoo#15557]
In a company, it may be required to register the same salesperson into multiple salesteams. At current version of Odoo, if you try to register the same salesperson into multiple salesteams, only the latest salesteam registrations becomes valid and the prior registrations to other salesteams are cleared. Is this as desired or a bug?

According to our CRM experience, it should be possible to register same salesperson into multiple salesteams.

**Comment by JKE-be** [comment]
Please use forum for this kind of question.

This tracker is for bug only.

https://www.odoo.com/forum/help-1/question/odoo-10-how-to-assign-a-user-in-two-sales-teams-simultaneously-114971

**Comment by gokhanerdogdu** [comment]
I asked the question here because I am not sure whether it is bug or as design. If it is as design, then this problem can be evaluated as a feature request. We have customers that need this functionality.
