### ISSUE TITLE
[16.0] website_sale : discount is not the same 

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#155648]
Impacted versions: 16.0 and maybe other

Steps to reproduce:
- activate advanced pricelist
- create a product A with sale price 300 €
- create a pricelist A : with a fixed price 199 € for product A
- create a public pricelist with "Show public price & discount to the customer", with an item with discount 25% based on other pricelist A
- create an order with the public pricelist, select the product A. You show unit price 199€, discount 25%, subtotal 149.25
- go to website show product A, you show price before discount 300€, after 149.25
--> Issue the base price is not the same (199 <-> 300)
<img width="1138" alt="image" src="https://github.com/odoo/odoo/assets/16716992/3ded2c1a-96cb-48bf-b6a1-5d1116a7f65b">
<img width="674" alt="image" src="https://github.com/odoo/odoo/assets/16716992/03e0b772-92f3-43d8-89b3-ef9b59a98f3d">

Note: in case in multi currency on website the base price can be only the sale price on product. It is impossible to have a different base price for each currency.

Because website and sale don't use the same computation.

Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/16716992/732819fd-795f-43d0-ab1a-f5a36458541a

Support ticket number submitted via odoo.com/help (optional):
#3771990

**Comment by fmdl** [comment]
@tde-banana-odoo @Feyensv

**Comment by Feyensv** [comment]
Indeed, the behavior is different between Sale & Ecommerce, but it's been the case for years now and that's not something we will change in stable.
The pricelist logic will be heavily refactored for v18, and this will be improved.
