### ISSUE TITLE
Bug (V10) - Dashboard App Layout

### ISSUE THREAD

**Issue by gokhanerdogdu** [odoo/odoo#15563]
If the added report is somebit big, the borders are exceeding the dashboard as shown below.

![screen shot 2017-02-20 at 15 45 58](https://cloud.githubusercontent.com/assets/20369981/23125649/86745cc0-f77b-11e6-9344-d7a9f39be1b6.png)

**Comment by pedrobaeza** [comment]
With the screenshot I'm not able to identify the problem. Can you please be more specific?

**Comment by pedrobaeza** [comment]
Closing as no answer.
