### ISSUE TITLE
[9.0] Unable to return products when using different payment method

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#15567]
Impacted versions: 9.0 enterprise

Steps to reproduce:
- Open the point of sale and create an order for a product, choose the payment method 'Cash (USD)':
![image](https://cloud.githubusercontent.com/assets/6352350/23130545/2f8aaf52-f787-11e6-9bea-02e0d227a196.png)
- Close your point of sale, open up the order that you've just made in the PoS:
![image](https://cloud.githubusercontent.com/assets/6352350/23130584/510812aa-f787-11e6-9df0-cb29642c0c37.png)
- Refund the products by clicking on 'Return Product'
- Add a payment on it that is not the same payment method as used in the PoS:
![image](https://cloud.githubusercontent.com/assets/6352350/23130656/9b3f5892-f787-11e6-9fc3-cdc94183f820.png)
- Click on 'Make payment' and you'll get the following error:
![image](https://cloud.githubusercontent.com/assets/6352350/23130687/ae04bdfa-f787-11e6-8faa-adaa09ecdb4c.png)
https://github.com/odoo/odoo/blob/2f66e77fe8f46ace6eee1bcf306c453c1b3ce949/addons/point_of_sale/point_of_sale.py#L1131
This exact same behaviour will work fine if you use the same payment method (Cash (USD)) though.

Current behavior: You can't return products on another payment method then the payment method on which the order is made.
Imagine the following case: You've sold a product to the customer, however, after two days the customer comes back because he wants to return this product. You open up the orders from the PoS, find the order and return the product. You however do not want to give the customer his money back and would like to use a cheque. This will need another payment method, which is not possible now in Odoo.

Expected behavior: You're unable to return products with another payment method then where it is initially created in.

**Comment by Yenthe666** [comment]
Hi @mart-e, @qdp-odoo, @jorenvo and @JKE-be could one of you guys look at this and give feedback as fast as possible?
I'm sorry for pinging you and urging this but we have a dry-run tommorow for a huge customer and just found this out.. Is there a specific reason why this is made or can we change this?

**Comment by Yenthe666** [comment]
Cc @cyhexy

**Comment by mart-e** [comment]
Hello Yenthe,

We try to group payments per payment method to only create one global statement.

> You're unable to return products with another payment method then where it is initially created in.

Not exactly, you can not create a payment in a method not used during the session. In you example you made only one sale but on a sale session, you should use multiple.
Do you confirm?

**Comment by Yenthe666** [comment]
Hi @mart-e,

Indeed you cannot create a payment for a payment method that was not used in the POS session. However, imagine having two customers that both paid with Cash (USD). You'll have two sales but in this case I still can't do a return of my products on another payment method. 

Shouldn't it be possible to return products with another payment method than the one it was made in?
For example: I have a customer that has to pay 50€. The customer pays it in cash in the POS. The next day he comes back to the shop and he wishes to return his products. The shop allows the returning of products but does not return cash (which most shops don't do anymore) and instead wants to give a voucher. This voucher however is another payment method, a new one created in the payment methods on another debit & credit account. If I'm not mistaking this is not possible in the POS at the moment?

**Comment by mart-e** [comment]
Actually, I checked again and the pos [creates a bank statement](https://github.com/odoo/odoo/blob/f3491a27a594e2ea3503c6210242cf80b22c6db0/addons/point_of_sale/point_of_sale.py#L528-L537) at the session creation for each available payment method.

So either you are making a refund with a method not available with the pos (and we are probably lacking of a domain on the dropdown here), either you added a method after the session creation.
This is linked on the crappy way the PoS handles payment. It could definitely be improved but I wouldn't risk changing it in stable.

cc @qdp-odoo

**Comment by Yenthe666** [comment]
@mart-e agreed, this should be against the master, not in a stable but it would be nice for the V11 perhaps. 😄
Alright I'm curious about your feedback, thank you for the update.

**Comment by Yenthe666** [comment]
I guess we can close this because of the commits + the feedback.

**Comment by mart-e** [comment]
Yes, it would have been closed automatically when we release the version 11 😉

**Comment by Yenthe666** [comment]
I'm always to impatient hmm? 😉
