### ISSUE TITLE
Odoo v10 bugs, x_field can't use in reports , tested in Italy Preference.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15578]
Impacted versions: 10

Steps to reproduce:
add x_field in model via web browser than add field in reports and failed to work.
PDF not comes with data fielled in x_fp_twt_rmvd_crme

![codice fiscale res partner - odoo](https://cloud.githubusercontent.com/assets/311413/23162619/f0c18c0e-f854-11e6-94ad-c518072e6e57.png)

Current behavior:  not show any data, even field had data and reload properly.
![codice fiscale res partner - odoo](https://cloud.githubusercontent.com/assets/311413/23162638/0f62a86e-f855-11e6-906a-7355904d53cf.png)
![report_invoice_document - odoo](https://cloud.githubusercontent.com/assets/311413/23162641/132f4790-f855-11e6-80b3-e1e34faf13ab.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Are you sure your inheritance is correct? Give at least the full code you are using to modify the report.

**Comment by tejastank** [comment]
I am not sure, kinldy you guide here what wrong, in case you really know.

**Comment by mart-e** [comment]
> than add field in reports and failed to work.

Please explain this part.
- how did you add the field into the report? using an inheritance?
- do you have an error?
- is it missing the value for the field or is not showing the inheritance?

> kinldy you guide here what wrong, in case you really know.

I don't know what is wrong but if you want us to be able to help you, add screenshots, ways to reproduce, etc.

**Comment by Yenthe666** [comment]
Hi @tejastank,

There has been no response in months.
I'm closing this report as we really can't reproduce it or help you without further information.
Please provide us with more information and I'll reopen this issue and look into it.

Regards,
Yenthe
