### ISSUE TITLE
[8.0][Usability] Website Fields Place holder

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#1560]
Public website fields are hard to spot when they are blank, specially for a newbie. I would suggest adding a place holder or adding these fields to the back end views.

Examples:
Product Description
Partner Short Description

**Comment by Yenthe666** [comment]
Hi @mrawi,

Thank you for your suggestion.
It has been quite a while though and in the meanwhile almost the whole framework has been rewritten, including the website client.
I believe it has been improved 😉 

Regards,
Yenthe
