### ISSUE TITLE
standard_price Field:if update product variant  price cost ,this updating update the price cost product template 

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#15609]
Impacted versions:
8.0
Steps to reproduce:
update price cost in the product variant,
Current behavior:
this updating, update even price cost product template
Expected behavior:
the update of the price cost variant  should not modify price cost product_template
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @roccocesetti ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
