### ISSUE TITLE
error while installing/upgrading odoo 10

### ISSUE THREAD

**Issue by remz1337** [odoo/odoo#15601]
Impacted versions:
10

Steps to reproduce:
Brand new Ubuntu Server 16.04.1 x64
Follow the Deb Community package installation steps from here:
https://www.odoo.com/documentation/10.0/setup/install.html#setup-install-packaged

sudo apt-get update
sudo apt-get upgrade

Current behavior:
Console output:
chown: cannot access '/var/lib/odoo': No such file or directory
dpkg: error processing package odoo (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 odoo
E: Sub-process /usr/bin/dpkg returned an error code (1)

Expected behavior:
successful installation/upgrade without error messages

It still works, but everytime I restart the machine I have to restart the service with
sudo systemctl restart odoo
for the authentication page to appear

**Comment by clemensmach** [comment]
duplicate of #13533 ?

**Comment by Yenthe666** [comment]
@d-fence perhaps you can run through the official deb installation? Maybe we're missing something?

**Comment by remz1337** [comment]
Indeed my ubuntu server was installed with hostname odoo and user odoo, so it might be the cause.

**Comment by Yenthe666** [comment]
Oh.. Yes I'm quite sure that will give troubles. Can you try again on a server with another hostname and let us know what that gives @remz1337?
@d-fence if this is the cause we might add a little warning to the docs mentioning this.

**Comment by d-fence** [comment]
Sure, I'm curious.

**Comment by remz1337** [comment]
I'm sorry I don't have much time at work to do this. However, we did manage to have odoo running on that machine by cloning the repo and running a buildout script

**Comment by Yenthe666** [comment]
I guess we can close it then? @d-fence if you'd still feel like testing it feel free though..

**Comment by mybengui** [comment]
I had the same issue and solved like this:

# mkdir /var/lib/odoo
# chmod -R 777 /var/lib/odoo
# apt-get -f install

That should solve your problem.
