### ISSUE TITLE
Report language context for monetary fields is not overriden

### ISSUE THREAD

**Issue by bfig** [odoo/odoo#15605]
Impacted versions:
tested on Odoo 10.0+e-20161208
Steps to reproduce:
1) create a sale order
2) set the customer language to something different than the current user (let's call it lang-c)
3) set lang-c's comma and thousand separators to something different than user lang.
4) print said report
Current behavior:
The monetary fields behave inconsistently. The sale order has it's language overriden by lang-c (since it is a document that you would want to send to the customer), but if we look at the monetary fields, they still use the language of the user. This is inconsistent because the floats (non monetary) behave as you would expect, rendering in the client's language, but the monetary fields don't, even though they are understood and the dollar sign or whatever works as intended.

Expected behavior:
Print the monetary fields using the client language separators

What I think it is:
The language override is not catching the totality of the template or the totality of the language calls. Somewhere, instead of using the context['lang'], they are using the language in the user context.

**Comment by pedrobaeza** [comment]
Can you please illustrate with screenshots the current behavior against expected behavior?

**Comment by pedrobaeza** [comment]
Closing as no answer.
