### ISSUE TITLE
top-right email icon absent

### ISSUE THREAD

**Issue by NeoGenesis1986** [odoo/odoo#15613]
Impacted versions: 10
I can't find anywhere how can I compose a new email.

**Comment by Yenthe666** [comment]
Hi @NeoGenesis1986,

There are a few ways to do this.
You could send a new email from settings > Technical > Email > Emails or from the mass mailing module.

Regards,
Yenthe

**Comment by NeoGenesis1986** [comment]
That menu is only accessible to Admins. Are you suggesting to give administrator rights to users just so they can send a email?!

**Comment by Yenthe666** [comment]
@NeoGenesis1986 nope, then you can use the mass mail alternative for example. 😉 
There are a lot of ways to send mails. You can also open the contact and add a message in the chatter - which will be e-mailed if you have an outgoing e-mail server.

**Comment by NeoGenesis1986** [comment]
I should be able to a simple email. Not a mass mail and not an email to one of my contacts.
I'm aware of the alternatives. I think this issue should be addressed and fixed instead of offering inadequate suggestions and closing it.

**Comment by mart-e** [comment]
Hello,

Sorry but we have dropped this feature. We want that the users discuss on specific documents.
We do not consider Odoo as a mail client.

**Comment by str** [comment]
I also was looking for this feature. Is there a plugin for Odoo 10/11 to restore this feature?
