### ISSUE TITLE
[9.0] Product cost is not updated with REAL method cost

### ISSUE THREAD

**Issue by rodoo9** [odoo/odoo#15618]
I enabled the switch “Use a 'Fixed', 'Real' or 'Average' price costing method” in Purchase App settings , the option “Manage Inventory Valuation and Costing Methods” is selected. 

On product's template --> Inventory Valuation
Costing Method = Real Price
Inventory Valuation = Perpetual (automated)

Its just that if I enter a PO and receive those products in:

Purchasing > Receive Products > Receive Products ... it doesnt update the unit cost.  It only updates the qty.

if I receive those new products via:

Warehouse > Products Moves > Receive Products ... it doesnt update the unit cost.  It only updates the qty.

It only works if I receive those products via:

Purchasing > Receive Products > Incoming Shipments

Why is not working this way Purchasing > Receive Products > Receive Products ??

Thank you and regards

**Comment by sle-odoo** [comment]
I was not able to reproduce the behaviour you describe, but anyways the unit_cost ont he product does not matter if you're in real price ; it's the unit_cost on the quants. Please see my comment in the linked issue.
