### ISSUE TITLE
Cannot translate mass mailing templates

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15622]
Impacted versions: 9, 10

Steps to reproduce:

As well explained in https://github.com/odoo/odoo/pull/15583#issuecomment-281625789, templates display the language dropdown but do not let users translate them. The easiest way to remove this pseudo-bug would be removing that dropdown.

![captura de pantalla de 2017-02-22 11-03-09](https://cloud.githubusercontent.com/assets/973709/23206701/e6edde04-f8ee-11e6-888f-17b79c974e36.png)

However, https://github.com/odoo/odoo/pull/15414#issuecomment-280597920 reveals a different problem. The fact itself that templates cannot be translated.

Current behavior: You cannot translate mass mailing templates, and if you get to use one of those that come with a built-in translation, the translation is not applied when you apply the template to a mass mailing.

Expected behavior: User should be able to translate mass mailing templates, and then to receive those translations applied to the mass mailing itself in sections where no change happened between the template and the mailing. 

Video/Screenshot link (optional): See https://github.com/odoo/odoo/pull/15414#issuecomment-280597920.

@Tecnativa @nle-odoo

**Comment by pedrobaeza** [comment]
@Yajo, is this fixed?

**Comment by Yajo** [comment]
AFAIK, since it does not work perfectly, it is disabled. I hope that's not the final fix. 😕

**Comment by Yajo** [comment]
New related issue: https://github.com/odoo/odoo/issues/16165

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thanks for your report.
I believe everything is answered and handled in https://github.com/odoo/odoo/pull/16255 though.
Closing as this has been answered and slightly altered. Correct me if I'm wrong. 😄 

Regards,
Yenthe
