### ISSUE TITLE
[10] Modifying one item while doing large stock inventory blocks the UI for a long time

### ISSUE THREAD

**Issue by lahdekorpi** [odoo/odoo#15628]
**Impacted versions:**
10.0.20170224

**Steps to reproduce:**
1.  Use a large inventory.
2. Do stock inventory on all products.
3. Modify the amount of one product.

**Current behavior:**
Loading screen appears and loads for 1 minute.

**Expected behavior:**
Quicker loading or doing it in the background without blocking UI.

**More:**
We are doing inventory for our 3500 items where we do it for all products at once.

The problem is that every time a new amount is modified to a product in the inline field it appears to be saved correctly.
But after a second or two a dark loading screen appears for around a minute waiting for

`/web/dataset/call_kw/stock.inventory/onchange`

Having to wait 1 minute to enter each product amount will take roughly 3 months for us...
Any ideas on how to debug this? What is Odoo doing while loading?

There is nothing obvious in log files...

**Comment by mart-e** [comment]
Hello,

When you say a large inventory are you talking about around how many products? Hundreds? Thousands?

It seems that when modifying one line, the onchange is triggered, resending all lines. That may be the reason of slowing down.
What modules do you have installed?

**Comment by lahdekorpi** [comment]
@mart-e I'm having problems with just some basic modules installed that are required by Inventory Management and POS.

Inventory of 3500 products.
@Yenthe666 said in his comment that 2000 products in their case.

I actually just tested with a new server and installation and could replicate.

**Comment by mart-e** [comment]
@lahdekorpi but are you using the barcode scanner too (enterprise feature)? I think this is the issue from yenthe but let's stick to your problem on this issue.

If you check the result of the onchange in your browser developer console, what is the result?

![1488363269](https://cloud.githubusercontent.com/assets/564822/23457156/02ce30c8-fe77-11e6-9142-9b8afb563b55.png)

**Comment by Jerther** [comment]
Hi, I just wanted to say we're experiencing the same Issue. 852 items. "barcodes" module is installed but we don't use a scanner. It's a dependency I guess?

`onchange` call occurs twice for a single change. Both calls send pretty large and identical jsons, except for the final ID ( see [here](https://pastebin.com/MTaDLSSr) )

 Both take around 20 seconds to resolve, and both return very similar json result:

`{"jsonrpc": "2.0", "id": 661433363, "result": {"value": {}}}`

Form what I understand the web interface sends ALL lines in the onchange call, but should send only the changed line. And only once. Right?

**Comment by livinglasnubes** [comment]
Hi,

  We are experiencing the same issue. Around 400 items.

  I have gathered some facts:

  1. If I use the treeview 2 or 3 onchange events are fired every time I change a field but if I shrink the window so it uses the Kanban interface only one event is fired. It takes 4 to 7 seconds per call so it makes a difference.

  2. I have logged SQL queries during one qty update for a 400 lines inventory. Around 1659 queries. 438 related to quants. 360 product_template. 219 product_product. 202 ir_translation. Other related custom attributes form product_product and product_template.

  3.   I thought  this line  theoretical_qty = sum([x.quantity for x in self._get_quants()]) could be improved with  self._cr.execute("""SELECT SUM(qty)
                    FROM stock_quant
                   WHERE company_id = %s
                     AND location_id = %s
                     AND product_id = %s
              """, (self.company_id.id, self.location_id.id, self.product_id.id))

       But it did't make a huge difference.

I don't know what could be improved in oder to reduce (or completly remove) the UI block. You can not use this feature this way and it is a very important one.

**Comment by Jerther** [comment]
The trick is to create a list view dedicated to the inventory adjustment lines, and use that view to make the adjustments. This is how Odoo fixed it in 11.0; there's a "Details" button in the inventory adjustment form view that leads to said view.
