### ISSUE TITLE
[16.0] web: widget domain allow bad domain

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#156224]
Impacted versions: 16.0

Steps to reproduce:
On automated action, add a domain like this `[('state','=','new')]toto` or `[('state','=','new')]]`.
--> Issue the widget doesn't show any error.
--> When the domain is evalued by the server an error raise.

<img width="711" alt="image" src="https://github.com/odoo/odoo/assets/16716992/e2444174-236e-4e80-94a3-11e959047ddb">

Server fix : https://github.com/odoo/odoo/pull/156223

Video/Screen shot link (optional):

https://github.com/odoo/odoo/assets/16716992/78d8c122-ae95-48de-a1c3-fde374c08f17

Support ticket number submitted via odoo.com/help (optional):
#3781584

**Comment by fmdl** [comment]
ping @rco-odoo

**Comment by vava-odoo** [comment]
Thanks @fmdl for the feedback. This check has been merged in saas-17.1
