### ISSUE TITLE
errors in amount_to_text (in french)

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#1562]
see discussion on https://github.com/odoo/odoo/commit/91bf583b1c52f15f11c299ca5c914126d2e8d01b: 
- capitalized strings which should not be there
- use of a mix of strings and unicode objects
- errors in handling the 's' at the end of 'vingt'
- errors in handling hyphens.

**Comment by mart-e** [comment]
Hello

Good news, num2words [has been added into Odoo](https://github.com/odoo/odoo/commit/e0be5bb11cd857708d57cc757a54eed044b76a4b) (since saas-14) !

Pull requests welcome to clean the remaining calls to the bad amount_to_text to convert them to num2words.
