### ISSUE TITLE
Replying Internal Note from Discussion sends messages to followers

### ISSUE THREAD

**Issue by gokhanerdogdu** [odoo/odoo#15621]
When you are mentioned in a Note at any model, for example, Opportunity, you are getting notification in your inbox. There is option to directly reply from Inbox to the internal note. Anybody replying from Inbox to Internal Note thinks that he/she is replying as an internal note, but this is not the case at the current version of Odoo. Thus, when somebody replies internal note from Inbox, that message is directly sent to the followers, not as an internal note. This is a very important problem in discussion. People can send messages to followers wrongly.

**Comment by bistaray** [comment]
I just discovered this also.  

Internal Note was sent to a SINGLE USER.

They replied from their email client (completely outside of Odoo) and the reply went to all followers.

Internal Notes are meant to be internal.  

In my case the Followers were internal users.  I worry if they were external partners (like a Customer) what they would receive?

What if the internal note was "Are we making enough of a margin on this Sale?" and the user replied from their external email client "No, this Customer is very high maintenance and always asks for heavy discounts - [other bad things a Customer should never see]".

Would the Customer see this?

**Comment by Yenthe666** [comment]
Hi @gokhanerdogdu,

Thank you for your report.
Actually, I've just tested this with the latest Odoo 10 and this is not a problem at all. Neither by doing the whole flow inside Odoo and outside of Odoo.
First I created a lead with an user and added an internal note saying "Yenthe what do you think?" The Yenthe links to my second user (with my second e-mail attached to it):
![image](https://cloud.githubusercontent.com/assets/6352350/26621929/da0ec620-45e8-11e7-88cd-50ebef0bc442.png)
I then got an e-mail on my second accounts its e-mail account:
![image](https://cloud.githubusercontent.com/assets/6352350/26621954/f09c5416-45e8-11e7-9127-9581db690e45.png)
I did a reply from my mailclient on this email:
![image](https://cloud.githubusercontent.com/assets/6352350/26621960/fabcf7ac-45e8-11e7-8dae-62aacbbf95da.png)
After a minute of waiting it is now loaded in Odoo, as an internal message (as it should be):
![image](https://cloud.githubusercontent.com/assets/6352350/26621997/1d6ef28c-45e9-11e7-8089-a886376fcd8c.png)

So, no, you can't send any internal messages to the customer by accident. If you respond from within Odoo in the discussion app:
![image](https://cloud.githubusercontent.com/assets/6352350/26622048/5d116712-45e9-11e7-862f-5989917fa425.png)
When going back to the lead it is also an internal note:
![image](https://cloud.githubusercontent.com/assets/6352350/26622126/a392221c-45e9-11e7-958f-e469f1d73bd1.png)


Closing as this is no problem or bug. 😉 

Regads,
Yenthe

**Comment by auyeung112002** [comment]
@Yenthe666 Can you please verify this issue again?
I have tested on version 12, both community and enterprise version, this bug still exists.
