### ISSUE TITLE
[RFC][master] Use part of the new domain widget on "Add Custom Filter"

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#15634]
The new domain widget is amazing, and also solves in a better way the current functionality of the community module _web_advanced_search_x2x_, but it only serves for certain parts like mass mailing where you need to select some records. 

It's a pity to not use the codebase made for this widget in other parts of Odoo, mainly on the "Add Custom Filter" for applying these advanced domains directly in any search view.

A visual draft of this idea would be:

![imagen](https://cloud.githubusercontent.com/assets/7165771/23310202/fbad5102-fab1-11e6-80c2-4544b48cfc54.png) ![imagen](https://cloud.githubusercontent.com/assets/7165771/23310172/e6e0c696-fab1-11e6-954a-f74bc63f9430.png)

Have you thought about this? Is this planned to be landed on master? We can work on this if not, but we don't want to duplicate effort. Do you want us to make it?

@fpodoo, I ping you directly as I'm not sure who can decide this.

cc @Yajo

**Comment by Yenthe666** [comment]
@mart-e this might be something for your interest. 😄

**Comment by mart-e** [comment]
That would be @ged-odoo

**Comment by pedrobaeza** [comment]
Géry, can you confirm us the plans?

**Comment by ged-odoo** [comment]
Yes, we are thinking about it.  We will most likely rework and massively simplify the viewmanager/actionmanager/searchview classes soon, and this will be an obvious change.  Just not sure yet about the UI, but this would simplify our codebase :)

**Comment by pedrobaeza** [comment]
Thanks for the clarification. Please ping me if you want me to try these changes, although I scan regularly your interesting branches :wink:

**Comment by ged-odoo** [comment]
I'll try to keep that in mind :)

**Comment by pedrobaeza** [comment]
Hi, @ged-odoo, have you made any advance in this?

**Comment by ged-odoo** [comment]
@pedrobaeza sadly not yet. Finishing the new views+training new team members+vacations+random stuff takes a lot of time.  Also, I have a sad news on this: when we will finally refactor the controlpanel+friends, it looks like some people above me want to keep the 'simple' look of the current searchview. So, we may be able to add an 'advanced' mode to open the domain editor, but we need some work done, and some mockups before being able to advance on this.

**Comment by pedrobaeza** [comment]
Thanks for the update, Géry. Then it seems that the feature will not land on v11 for sure. As sadly my current target is v10 for now, I will replan things to do. The  possibilities are:

*  (more immediate) Backport widget_domain before views refactoring (easy to do I think) for having the widget on v10 for mass mailings.
* Based on this widget, add in v10 advanced search the new domain possibility instead of web_advanced_search_x2x.
* Rework the whole thing for new JS architecture for having the advanced search on v11 (which maybe can be used by you). In this last one, if you want to share any mockup or to be fedback by us, I can let you know.

Let see in what we can work for now.

Thanks again.

**Comment by pedrobaeza** [comment]
For references, we have got the first 2 points in https://github.com/OCA/web/pull/672.
