### ISSUE TITLE
double reference in Invoice/Accounting wizard

### ISSUE THREAD

**Issue by remz1337** [odoo/odoo#15632]
Impacted versions:
10

Steps to reproduce:
Fresh new Odoo 10 Community installed from Deb package on Ubuntu Server 16.04.1 x64
Install Invoice app

Current behavior:
While following the Invoice/Accounting wizard (or getting started guide), in the multi currency section the Accounting Settings is displayed twice (see picture)

Expected behavior:
Should be written 'Accounting Settings' once

Video/Screenshot link (optional):
![bug accounting](https://cloud.githubusercontent.com/assets/9980037/23310125/690eede2-fa7f-11e6-9715-a33a3f2636ab.png)

**Comment by Yenthe666** [comment]
Hi @remz1337,

Thank you for the report.
This is indeed a little bug in Odoo. I've just made a PR to fix this so this should be fixed very soon. 😉 

Regards,
Yenthe

**Comment by Yenthe666** [comment]
This has been fixed in https://github.com/odoo/odoo/commit/13a3e76a48be833a681863e3982c11a47fd40863
