### ISSUE TITLE
Odoo 10, problem with submenus

### ISSUE THREAD

**Issue by Cubillosxy** [odoo/odoo#15642]
Impacted versions:
odoo 10
Steps to reproduce:
``` 
on  ; __manifest__.py
    'data': [
        # 'security/ir.model.access.csv',
        #'views/views.xml',
        'views/v1.xml',
        'views/v2.xml',
        'views/v3.xml',
        'views/templates.xml',
```
in each .xml
``` 
   menu_root
     v1      parent=menu_root     list ->  parent= v1
     v2      parent=menu_root     list ->  parent= v2
    v2       parent=menu_root      list -> parent= v3

```
Current behavior:

Only i can show two submenus,  or v1 and v2, or v1 and v3, I dont know why this behavior, 

I need show all submenus. 

Expected behavior:
``` 
v1
--    list
v2
--    list
v3 
--    list

``` 
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Cubillosxy,

Thanks for your report.
Having three submenus is no problem at all, there are plenty of examples in Odoo that have this in fact.
As this is a question about custom development (and without the full code) I'm closing this issue. The Github tracker is not the place for asking question about custom development, it is only for bugs in the source code.
I'd suggest you to ask this on the official help forums (http://odoo.com/help) if you still face this issue, there are a lot of people there that can help you.

Regards,
Yenthe
