### ISSUE TITLE
bug payment mercado pago error 400 Bad Request Mercado Pago: Received data with missing reference.

### ISSUE THREAD

**Issue by hamelinmultimedia** [odoo/odoo#156428]
Impacted versions:16

Steps to reproduce:After activating and configuring the Mercado Pago payment method
![image](https://github.com/odoo/odoo/assets/53911390/3c737ca5-46df-4838-9a26-2eca9ff0e110) Make a purchase and pay with the PSE option, fill in all the fields and accept the payment 
![image](https://github.com/odoo/odoo/assets/53911390/0adc61e2-3f33-41e9-ac47-a5f95e1c46b3) then Fill out the form by clicking on the Pay button 
![image](https://github.com/odoo/odoo/assets/53911390/a4359c0e-ae22-4ff6-bb97-f050fa123052)
 
wait a little  
![image](https://github.com/odoo/odoo/assets/53911390/702c365f-6655-4a5a-b9c9-b96c0eaeff8b)
clic Approve 
![image](https://github.com/odoo/odoo/assets/53911390/68321c8c-0fd9-441d-b5ec-509a9937436f)

and... 
![image](https://github.com/odoo/odoo/assets/53911390/a53d1bf9-94a5-4ce0-a3fc-a718b53462ea)

![image](https://github.com/odoo/odoo/assets/53911390/6ccde752-cee4-40f1-8734-519dc0779be2)
In any case, the data and payment are created satisfactorily.
it only happens if they choose PSE and from experience this is the preferred one of buyers.

Current behavior:https://59275221-16-0-all.runbot112.odoo.com/payment/mercado_pago/return?payment_id=1317319510

I reproduced this test in Runbot https://59275221-16-0-all.runbot112.odoo.com/

Expected behavior: Thank you very much for your help

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by klzdeportes** [comment]
Hi @hamelinmultimedia, could you let me know why the issue was closed? I'm encountering the same behavior.
Thanks

**Comment by hamelinmultimedia** [comment]
Yes, of course I did, I closed it basically because I think it has little priority because it is a community version.

**Comment by YazanHabib** [comment]
ما هاذا

في الأحد، ٢٩ أيلول ٢٠٢٤ ١:٤٨ ص hamelinmultimedia ***@***.***>
كتب:
