### ISSUE TITLE
Odoo makes you choose between usability and optimization

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15656]
Hello, I'm currently trying to optimize Odoo as much as possible.

One of the basic steps in all Python app optimizations is to pycompile code with the maximum PYTHOMOPTIMIZE value possible (hopefully 2):

    PYTHONOPTIMIZE=2 python -m compileall -q /opt/odoo

One of the things this does is that it strips out any assert commands found in code. [Assertions are expected on places where production code should never get to a certain situation](https://wiki.python.org/moin/UsingAssertionsEffectively).

However, dealing with Odoo code, you find places like signup where assertions are being used under a security-critical context. Some examples:

- [When checking forms CSRF protection, under optimized environments, all secret keys would be "None" (as a string)](https://github.com/odoo/odoo/blob/44276dfdc3b69cd9b834bfa7037671558e6d0078/odoo/http.py#L389).
 - [A user that fails to write his password equally on both fields when signing up would continue with the signup process, and maybe lose chance to log in next time](https://github.com/odoo/odoo/blob/18456b9d42769a522adf86183746b49735e9d8b3/addons/auth_signup/controllers/main.py#L98).

~~Both assertions fall into a context that can easily be cracked with `curl`. IMHO, there's obviously a **big security bug** here~~. Odoo needs to choose among:

1. Fix all assertions used under security-critical contexts, and use them only where one should use them.
2. Document no support for high levels of optimizations and that enabling those is a security hole.

My vote goes for option 1, of course. Otherwise [we'd be yet again in the situation where Odoo works a different way from the rest of the world](https://github.com/odoo/odoo/issues/14942) and your previously-known sysadmin optimization skills are useless. That would be sad for this app we all love so much.

For the time being, I'm disabling optimizations everywhere (falling back to `PYTHONOPTIMIZE=1`) for the sake of ~~security~~ usability. I recommend everyone to do the same until this gets fixed.

Regards.

@Tecnativa @odony

**Comment by odony** [comment]
@Yajo If you consider that there is a security problem, then please show your concern for the security of Odoo users and follow the [responsible disclosure process](https://www.odoo.com/page/responsible-disclosure) properly.

However as far as I can tell you sentence _"Both assertions fall into a context that can easily be cracked with curl. IMHO, there's obviously a big security bug here."_ is quite inaccurate.

**Comment by Yajo** [comment]
Hmm thanks for pointing me to the procedure link, I did not know it. Hmm maybe I got misled by the attack surface of this. Indeed it does not seem a big security hole. Sorry for the noise there 😅, I'm removing the security sentences all around the report. Next time I'll follow the procedure (I hope there's no next time :wink:).

However, still there's the problem of optimized production instances losing features such as password match validation at sign up. Is optimization supported, or is it a bug?

**Comment by odony** [comment]
A common use case for assertions outside the testsuite is to serve as comments. It is the case for the CSRF line you linked to, because the presence of the required key is ensured [by construction](https://github.com/odoo/odoo/blob/c21354666d4299cf9f12b88a56cb28043ca825fa/odoo/addons/base/ir/ir_config_parameter.py#L19).
It may sometimes happen that developers use assertions instead of doing proper error handling, in which case we would probably consider changing it, as an improvement/cleanup (PR welcome ;-))
That said, we do not claim to officially support Python optimization levels, because we do not properly test it, for lack of interest. Those optimizations are unlikely to yield any measurable speedup, so it's actually surprising that you would want to use them except as a one-shot experiment.

Quoting the last sentence of the page you linked to: 
> _But don't do this unless it's really necessary. It's been scientifically proven that some bugs only show up when a customer uses the machine and we want assertions to help there too. :-)_

**Comment by pedrobaeza** [comment]
@Yajo, is everything clear? Can we close?

**Comment by xmo-odoo** [comment]
> One of the basic steps in all Python app optimizations is to pycompile code with the maximum PYTHOMOPTIMIZE value possible (hopefully 2)

That doesn't really make sense given what it does: it breaks assertions and docstrings and it removes `if __debug__` which Odoo doesn't use. So for Odoo, all it does is break stuff and very slightly obfuscate the source code.
