### ISSUE TITLE
odoo 10 bugs | odoo failed on basic operation for restore.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15659]
Impacted versions: 10

Steps to reproduce: odoo multi worker configured with 6
retore 6MB database

Current behavior:
ERROR None odoo.http: Postgres subprocess ('/usr/bin/pg_restore', u'--dbname=fake_twt_fp_it', '--no-owner', '/tmp/tmpGAKdIw') error 1

Expected behavior: Must restore small database and their should not ownership issues
In multi subdomain configuration must need to works.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @tejastank,

Could you add more information about how to reproduce it or how you've gotten this please?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in quite a while and we cannot reproduce it without more information.

Regards,
Yenthe

**Comment by tejastank** [comment]
Mr. @Yenthe666 over internet never found issue on github.com especially for odoo.  ;)
