### ISSUE TITLE
Cron threads crash when PostgreSQL is down and won't recover in multithreading mode

### ISSUE THREAD

**Issue by nilshamerlinck** [odoo/odoo#15666]
Impacted versions: 10.0

If the PostgreSQL server is down, cron threads will crash when trying to connect to the db. When Odoo is running in multithreading mode, they won't properly recover once the PostgreSQL is back up. The consequence is that the Odoo instance will seem to be working fine after the downtime, while actually none of the Scheduled Actions are being processed (the Email Queue Manager for example).

The impact is not as big in multiprocessing mode because new WorkerCrons are spawned after crash.

**Steps to reproduce**:

- start Odoo in multithreading mode (`workers=0`)
- wait a few minutes
- notice how scheduled actions are running properly:

```
2017-02-28 05:40:10,944 23155 DEBUG ? odoo.service.server: cron0 polling for jobs
2017-02-28 05:40:10,947 23155 DEBUG xp_10_test_pg_downtime odoo.addons.base.ir.ir_cron: Starting job `Test`.
```

- stop PostgreSQL server (make sure that all connections are closed: `sudo pkill -9 postgres`)
- notice the cron threads crashing:

```
Exception in thread odoo.service.cron.cron0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/service/server.py", line 238, in target
    self.cron_thread(i)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/service/server.py", line 220, in cron_thread
    acquired = odoo.addons.base.ir.ir_cron.ir_cron._acquire_job(db_name)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/addons/base/ir/ir_cron.py", line 185, in _acquire_job
    cr = db.cursor()
  File "/opt/openerp/code/xp/10.0/odoo/odoo/sql_db.py", line 623, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/sql_db.py", line 506, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/openerp/code/xp/10.0/odoo/odoo/sql_db.py", line 574, in borrow
    **connection_info)
  File "/opt/openerp/.local/share/virtualenvs/odoo-10.0/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

- restart PostgreSQL server
- notice that Odoo is working again
- BUT scheduled actions are not: no trace of crons "polling for jobs" in the logs anymore.

A spontaneous fix for multithreading-mode is to catch the Exception and let the cron thread retry to connect later, here:

https://github.com/odoo/odoo/blob/10.0/odoo/service/server.py#L220

```
                    try:
                        acquired = odoo.addons.base.ir.ir_cron.ir_cron._acquire_job(db_name)
                    except Exception as e:
                        _logger.debug('cron%d encountered an Exception: %s', number, e)
                        break
```

But you might want to fix this issue at `ir_cron` level ;)

**Comment by Yenthe666** [comment]
@mart-e and @odony  what do you think about this one? 😃

**Comment by odony** [comment]
I'd vote for handling it in the Cron worker/thread, and not in `_acquire_job()` itself. The method could be called from other business code and it would be surprising to have it silently catch all exceptions. At least that would be a change of behavior. OTOH it is the responsibility of the worker/thread to gracefully recover from any exception that is raised by the jobs themselves.

**Comment by odony** [comment]
Or seeing that `_acquire_job` already blocks a lot of other exceptions, we could catch it in both places. But the thread/worker should be resilient, no matter what.

**Comment by mart-e** [comment]
Hello,

Thanks for the report, indeed this was an unexpected failure.
Two fixes are required:
- one to handle gracefully your scenario
- one to properly handle any failure (as said Olivier, the thread should never die)

@nilshamerlinck could you check #15671 to confirm it fixes your issue?

**Comment by nilshamerlinck** [comment]
@mart-e Confirmed. Thanks for this blazing fast fix!
