### ISSUE TITLE
Not correctly Receipt Printer

### ISSUE THREAD

**Issue by sapetrov** [odoo/odoo#15679]
Impacted versions:
Odoo 10.0-20170223 
POSBox 15 (Raspberry Pi3)
Epson TM-T20II (code page - Russian). 

Current behavior:
Language changed to Russian.
Point of Sale Odoo - ок. 
Receipt Printer - not Russia, prints different characters

Expected behavior:
Receipt Printer - Russia correctly

**Comment by mart-e** [comment]
Hello,

This is a known issue. The ESC/POS printers do not handle well unicode.
We are looking to add support for better modern printers but it is very unlikely that we will manage the support for unicode  on the TM-T20.
Sorry but no solution at the moment.

**Comment by sapetrov** [comment]
Извините.
Указано, что одоо поддерживает кирилицу. Какой язык возможно использовать с кирилическими символами? Польский? Словацкий?

**Comment by mart-e** [comment]
English please, I don't speak Russian

**Comment by sapetrov** [comment]
Excuse me.
It is indicated that one supports the Cyrillic. What language can be used with cyrillic symbols? Polish? Slovak?
Can a workaround?

**Comment by mart-e** [comment]
At the moment, the tickets in the receipt printer are known to have some chars not printing well (not sure which one, you need to try).

The workaround is to to disable the automatic printing via the posbox and print using the printer of your browser (but printing a ticket is now a manual process)
![selection_022](https://cloud.githubusercontent.com/assets/564822/23949604/2d879234-0988-11e7-9b3a-b36ed145121a.png)

**Comment by sapetrov** [comment]
![Alt text](https://monosnap.com/file/k4lWxhovT2jTSBNWy7HS35z53Grikh.png)
How can this be achieved / obtained?

**Comment by sapetrov** [comment]
How did you do that?
Do I need to change the language to English for the seller's account?

**Comment by mart-e** [comment]
No, as stated above, you need to disable the automatic printing

![selection_027](https://cloud.githubusercontent.com/assets/564822/24203197/5596a566-0f15-11e7-86eb-239529920c39.png)

**Comment by sapetrov** [comment]
I know)))
Like on the screenshot turned Russian?

**Comment by mart-e** [comment]
I put some russian in the product name :)

**Comment by sapetrov** [comment]
I thought, you can print on the Epson TM-T20II

**Comment by lem8r** [comment]
@mart-e I think I have fix for this issue
