### ISSUE TITLE
[16.0][sale_timesheet] Timesheet total rounding always round to integer

### ISSUE THREAD

**Issue by alessandro-fiorino** [odoo/odoo#156899]
Impacted versions:
16.0

Steps to reproduce:
Create and confirm a sale order with a service with invoicing policy based on timesheets, add a timesheet line with a fractional part (i.e. half an hour)

Current behavior:
The sale order smartbutton showing the total hours of the timesheets display zero, it seems that there aren't timesheets linked to the sale order

Expected behavior:
The sale order smartbutton showing the total hours of the timesheets should display 0,5

The problem is in this line of code, the round function is used without precision so it always rounds to integer, it should round to the precision specified in the UoM
https://github.com/odoo/odoo/blob/57ad9c05014ca0219d7892c1ff8a2e949fab3c49/addons/sale_timesheet/models/sale_order.py#L55

**Comment by vava-odoo** [comment]
Hi @alessandro-fiorino 
I understand your point, and it makes sense to me, but `timesheet_total_duration` is an integer, so this can't be changed in stable versions.
The help message also says that the field is "computed with the uom, and rounded to the unit", so it seems to be done on purpose. 
Cheers

**Comment by vava-odoo** [comment]
@intero-chz thanks for jumping in into the discussion. I was only answering on why it would not display 0.5 as it can be changed to a float in stable versions.
@xavierbol would you mind having a look at how this field is computed? And maybe consider changing the type of the field in master?
Cheers

**Comment by intero-chz** [comment]
@vava-odoo that it won't be changed in stable is clear. But you've written that the help message probably leads to a purpose. As I understand it, the help message and the implementation contradict each other.

And the features are there too. So they should also be used.
