### ISSUE TITLE
Question: Is there a command line option for removing modules?

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#15687]
As I can see there is a -i flag that actually installs the module given, is there possibly another option that I am missing that removes modules ? (assuming dependencies are taken care of and the user has been warned?

**Comment by mart-e** [comment]
Hello,

No, we do not have this feature. We considered adding it at one point but the uninstall is too sensitive for the data to be done in one command.

Thank you to keep github for bug reporting only and not questions

**Comment by sukumar335** [comment]
I can't able to uninstall odoo
