### ISSUE TITLE
[16.0][web]The icons over the tree view overlapped when there are more than 40 records

### ISSUE THREAD

**Issue by audele5555** [odoo/odoo#156923]
Impacted versions: 16.0

Steps to reproduce: Create a sales order, add more than 40 sales lines under "Order Lines" tab

Current behavior: The buttons "<>" and the button to show/hide columns in the tree view overlapped. I checked and saw that the th has a class "position-static." This class causes problems with the button in the show/hide columns. Try with class position-sticky, and it works well.

Expected behavior: The button to show/hide columns in the tree view should be on the same line as the column headers instead of on the same line with the button "<>".

Video/Screenshot link (optional): https://59474801-16-0-all.runbot134.odoo.com/web#cids=1&menu_id=874&action=1279&model=sale.order&view_type=form&id=80.

Support ticket number submitted via odoo.com/help (optional):

**Comment by audele5555** [comment]
I think that the problem might come from here: https://github.com/odoo/odoo/blob/16.0/addons/web/static/src/legacy/js/views/list/list_renderer.js#L1030
[list_renderer.js](https://github.com/odoo/odoo/blob/16.0/addons/web/static/src/legacy/js/views/list/list_renderer.js)

**Comment by pedrobaeza** [comment]
This is not something of any OCA module in this repository. In fact, you are showing a enterprise runbot. Please report it to Odoo S. A. via enterprise ticket.
