### ISSUE TITLE
[10.0] Recurring meeting start end stop time are changed by summer or winter time

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#15694]
Impacted versions: 10

Steps to reproduce:
- Create a new recurring event that recurs every week. Make sure it passes a winter or summer time change. I've made a recurring meeting starting at `01/28/2019 11:00:00` with a duration of 1 hour, which recurs 100 weeks:
![image](https://cloud.githubusercontent.com/assets/6352350/23502703/01a82ea2-ff39-11e6-9a34-6f9060dbd6f5.png)
![image](https://cloud.githubusercontent.com/assets/6352350/23502713/09acf02e-ff39-11e6-9b0b-dad87c121a6f.png)

Current behavior: When there is a winter/summer time change the start and end time are changed. In my example we'll go from winter to summer time and the starttime changes from `11:00:00` to `12:00:00`:
![image](https://cloud.githubusercontent.com/assets/6352350/23502878/ba84a81a-ff39-11e6-8bfc-ab0e1d2106cf.png)

Expected behavior: The start and endtime are not changed when the winter or summer time changes.

**Comment by Yenthe666** [comment]
@nim-odoo could you look at this perhaps?

**Comment by mart-e** [comment]
Hello,

This actually an old bug, already reported at #9268
We have no solution for it so far, sorry.

**Comment by Yenthe666** [comment]
Oh I'm sorry about this. I didn't look far enough, my apoligies for the duplicate.

**Comment by reinaldoramosarxi** [comment]
Hello @Yenthe666,

Do you know if this issue has been brought up since this issue was closed?

Because the hour changed and the calendar/chronjobs also changed in our servers, so it's still not fixed.

Thank you.

**Comment by Yenthe666** [comment]
Hi @reinaldoramosarxi it should have been handled in https://github.com/odoo/odoo/commit/eeae211176dfc2a373db0a46c2a554c82c585c98 and I haven't heard from anyone after this. If you can still reproduce it on a V11/V12/V13 I guess you could create a new ticket :) Be sure to be on the latest code that includes this fix.

**Comment by reinaldoramosarxi** [comment]
@Yenthe666 We are having this issue in our company's own server, which is V12 (and updated regularly). 

Because of the time change on Sunday, the server adapted to minus one hour, and the calendar and cronjobs all changed to minus one hour. It's a hard thing to test, but we'll try to do it locally and submit a ticket if it still happens.

Thank you!
