### ISSUE TITLE
Error: cannot call methods on sortable prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by dfpena** [odoo/odoo#15706]
Impacted versions: 10

Steps to reproduce:
install mass mailing then attempt to access it on mobile after a template email has been generated. The error also seems to occur at random to desktop users

Current behavior:
does not open for some users

Expected behavior:
open
Video/Screenshot link (optional):

![screeny](http://go.pluricorp.com/websitemedia/Clipboard.png "Screenshot")

**Comment by Yenthe666** [comment]
Hi @dfpena,

Thanks for your report.
I've just tried to reproduce this on the newest Odoo codebase but I can't reproduce it.
Can you please update your Odoo and try again? Can you try reproducing it on a runbot? (runbot.odoo.com)

Thanks,
Yenthe

**Comment by Yenthe666** [comment]
Hi @dfpena,

There has been no response in over a month.
I'm closing this report as this is (no longer) reproducable.
If you can still reproduce this on the latest source code or on a runbot then please provide us with more information and I'll reopen this issue.

Regards,
Yenthe
