### ISSUE TITLE
[10.0]535 error when trying to configure outgoing email server with sendgrid

### ISSUE THREAD

**Issue by cgaffney099** [odoo/odoo#15702]
Impacted versions:10.0

using ubuntu 16.04 O/S

Steps to reproduce:
create an smtp connection to sendgrid using an apikey, port 465 and ssl connection.
smtp.sendgrid.net (smtp server)

Current behavior: 535 authentication error

Expected behavior: successful connection

Video/Screenshot link (optional):

![screen shot 2017-03-02 at 3 20 08 pm](https://cloud.githubusercontent.com/assets/17072476/23525243/c6333754-ff5b-11e6-88a2-4d31d6e3bcf1.png)

**Comment by Yenthe666** [comment]
Hi @cgaffney099,

Thanks for your report.
The Github tracker is however only for bugs in the official Odoo code and not for questions / implementation.
Please try asking this on the official Help forums where plenty of people can help you (odoo.com/help). I'm going to guess that the config isn't valid.

Thanks,
Yenthe
