### ISSUE TITLE
Unable to install Inventory Management module after failed removal

### ISSUE THREAD

**Issue by bigmillz** [odoo/odoo#15701]
Impacted versions: 9.0c-20170302 (and prior)

Steps to reproduce:
1. Had Inventory Management ("IM") module installed
2. Removed IM module
3. Odoo froze up while removing, restarted `odoo` service on server
4. Unable to edit products or open sales reports because of missing IM module
5. Tried to reinstall IM module, getting this error:
```
Odoo Warning - Validation Error
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: stock_picking - stock.picking]
```

Current behavior: IM module cannot be reinstall, leaving sales reports and product editing functionality broken. Additionally, noticed that other modules that depend on the IM module produce the exact same error when an install is attempted.

Expected behavior: IM module should be able to be reinstalled

**Comment by Man-1980** [comment]
Same problem. Have you solved it?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment. Try to restart the server.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
