### ISSUE TITLE
Odoo failed to remove draft invoices

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#15700]
Impacted versions: 10.0

Steps to reproduce:
create invoice, validated, cancel it, make them draft and remove invoices.
Note: I had removed all lines for invoice even it can't allow me to remove.

Current behavior:
See attached screenshot.

Expected behavior:
Should be deleted immidate
Also suggest solution or tips, in case right now able to direct remove from database.

Video/Screenshot link (optio
![invoice - odoo](https://cloud.githubusercontent.com/assets/311413/23511370/db257614-ff82-11e6-962d-1417c1e5bfa2.png)
nal):

**Comment by flotho** [comment]
Hi,
deleting an accounting move is not legal in many country especially for the sale ledger.
This is a normal behaviour, it's not a a bug.

**Comment by Yenthe666** [comment]
Hi,

This is indeed expected behaviour.
Both because booked invoices should never be deleted accounting wise and because invoice sequences are not allowed to have gaps in them. If you would delete an invoice you would get a gap.

**Comment by tejastank** [comment]
@flotho what if I had legal it for our client and they needed, odoo allow cancel journal module already their to cancel invoice. But not removed invocies !!!

I had checked, their odoo failed to do this operation becuase of journal or other document linked their. 

I consider it's odoo personal mindset ! Me and lots other people looking flexibility here.

Thank you

**Comment by Yenthe666** [comment]
@tejastank,

If you want to have the ability to cancel and remove booked lines you'll need to do custom development.
Odoo has all the flexibility you need to add the code to add custom logic on top of the default code.
