### ISSUE TITLE
[8.0] Total computed in point_of_sale is different in backend

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#15727]
Impacted versions:
8.0
Steps to reproduce:
Create a ticket in point of sale with 2 lines:

- 1 PC (13.95€) with 90% discount
- 3 PC (5.99€) with 90% discount

Current behavior:

The total computed in the point of sale interface is 3.20 € but when the order is created in backend, the total is 3.19 €. So the order is not marked as paid as the payment is higher than the total.

Expected behavior:
Total in backend should be 3.20 and order should be paid.

Video/Screenshot link (optional):
https://youtu.be/wW50viT2d6Q

**Comment by Cedric-Pigeon** [comment]
OPW-715506

**Comment by Yenthe666** [comment]
Tested & confirmed.
@jorenvo this one might be for you? 😄

**Comment by mart-e** [comment]
Fixed at 7f260ab517e

**Comment by Cedric-Pigeon** [comment]
:+1:  tested
