### ISSUE TITLE
Auto subscription of message ignores user settings

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#15728]
Impacted versions: 10.0 (could be and 9.0)

Steps to reproduce: 
Create a lead and assign Demo user. Demo user have "Email Messages and Notifications" set to "Never".

Current behavior: 
Demo get an email about new lead

Expected behavior: 
Demo don't get an email about new lead

Technical notes:
Looks partners should be filtered here https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_thread.py#L2066

**Comment by Yenthe666** [comment]
@mart-e this doesn't seem to look at the setting indeed.  Can I confirm this one and can you assign somebody?

**Comment by mart-e** [comment]
Not exactly, this option on the user will only have effect when posting a message on a document (I think it was removed in master as confusing).

In the case of the assignation, it was a decision to always send an email when assigning somebody to a lead, an issue,... is an important action, that the user should not ignore (expected to reply to the customer).

**Comment by paulius-sladkevicius** [comment]
@marte-e thanks for feedback, however in such case "Never" loose it's idea and there is exception that user won't understand if they don't want to get any message by email. In such case would be need additional configuration per user/partner for auto-messages what is now spam, because in all cases you get message in the internal Messaging app.

Look in such case we have only option to make own addon that will overwrite this part and contribute to community.
