### ISSUE TITLE
[10.0] Wrong calculation on work100 @payslip

### ISSUE THREAD

**Issue by raditv** [odoo/odoo#15736]
Impacted versions:
10.0
Steps to reproduce:
Adding working time with starting and ending date for single days
Current behavior:
work100 calculation error
Expected behavior:
work100 calculation must be the same with working time
Video/Screenshot link (optional):
First step:

![1](https://cloud.githubusercontent.com/assets/1745955/23644224/d301d52c-0338-11e7-976c-6d0cbfceb5e8.png)
![1-1](https://cloud.githubusercontent.com/assets/1745955/23644233/e0d8d772-0338-11e7-89c1-79279ce2278f.png)

Second Step:
![2](https://cloud.githubusercontent.com/assets/1745955/23644236/e82b8e98-0338-11e7-9061-71ad6fc24b4a.png)
![2-2](https://cloud.githubusercontent.com/assets/1745955/23644239/eec64e50-0338-11e7-9a4d-75e4c7f8620b.png)

Last Step:
![3](https://cloud.githubusercontent.com/assets/1745955/23644244/f89c7c1a-0338-11e7-8562-00ab4d6a0102.png)
![3-3](https://cloud.githubusercontent.com/assets/1745955/23644254/0036c7dc-0339-11e7-9d80-886a76c07b6d.png)

**Comment by nim-odoo** [comment]
This was solved partially in 73bd7ef0e0889b109d679a2465e4f1f0d7acaa3e, and the decision was taken to improve the behavior for upcoming version. See #15565
You can also try to apply these commits:
https://github.com/odoo/odoo/commit/56a6befb2f982612b6a3e8398e20c5eb5bc5f74b
https://github.com/odoo/odoo/commit/4bacffd124559d60ca8ea9dd80b4c6110a9648c7

**Comment by raditv** [comment]
ok thank you

**Comment by raditv** [comment]
I updated with your latest commit, now the problem became more strange
I've set the working time for 20 days in February, some of them has day overlap ex. from 17.00 evening to 01.00 midnight.

here is the result 
![bildschirmfoto 2017-03-10 um 17 54 19](https://cloud.githubusercontent.com/assets/1745955/23792813/1e51af0a-05bb-11e7-85ef-71681d9f165b.png)
![bildschirmfoto 2017-03-10 um 17 54 19](https://cloud.githubusercontent.com/assets/1745955/23792847/3f53c148-05bb-11e7-8dae-97c2f645c646.png)

number of days should be 20 days and number of hours should be 163, but it only count number of days is 13.38 and number of hours 107
