### ISSUE TITLE
[10.0] Website event tickets shows wrong ticket type and price

### ISSUE THREAD

**Issue by wardm95** [odoo/odoo#15739]
Impacted versions: 10.0, 9.0

Steps to reproduce: Uninstall app 'eCommerce'

Current behavior: Event ticket shows wrong ticket type and price.

Expected behavior: Event ticket shows the price and a ticket type correctly.

Video/Screenshot link (optional):
When the app 'eCommerce' is removed, event tickets contain wrong data.
In screenshot below, ticket is displayed uncorrectly:
![image](https://cloud.githubusercontent.com/assets/17778757/23650652/2550ffda-0323-11e7-86bd-f295e2c3c91a.png)
When the app 'eCommerce' is installed, ticket is displayed with the correct values:
![image](https://cloud.githubusercontent.com/assets/17778757/23650744/791c272a-0323-11e7-9e34-e07b7a799072.png)

**Comment by Yenthe666** [comment]
@mart-e could you let somebody look at this? Tested & confirmed on both 9.0 and 10.0.

**Comment by mart-e** [comment]
Hello,

This is actually kind of intended. The ecommerce (website_sale) is the module necessary to be able to sell goods (products, services,...) on your website. Without this, you don't have the payment features, so the price is set to free. Having just the website_event is to be able to manage online registrations but not sell them.

So if you want to sell, you need the ecommerce. What is the reason to uninstall it?

**Comment by Yenthe666** [comment]
Hi @mart-e,

We actually had it the other way around.
We installed the event module but didn't manually install the website_sale module. It took us quite a while to figure out that this was the problem why it was showing odd behaviour.
