### ISSUE TITLE
Don't delete timesheets affected to a task when deleting 'My timesheet'

### ISSUE THREAD

**Issue by jacob-y** [odoo/odoo#15741]
Impacted versions: 
10.0

Steps to reproduce:
- Write timesheets in project tasks
- Go in "my timesheets" and click "create" (select a time interval including the timesheets) to get a visualization of time spent per day
- Click "delete"

Current behavior:
- Deletes all the timesheets for the time interval without warning (tasks lose their timesheets)

Expected behavior:
- As a user, when I click delete, I want to remove only the visualization (of time spent per day) offered by "My timesheets". I don't want to remove the timesheets themselves, and I find the current behaviour confusing.

The new behaviour could be one of these options:

- Remove only timesheets thats are not affected to a task
- Display a warning to make the user understand that it will delete all the timesheets
- Offer to select which behaviour do you want (delete all timesheets OR only those not affected to a task)

**Comment by Yenthe666** [comment]
@mart-e this is usability related. What do you think?

**Comment by mart-e** [comment]
Hello,

The removal was done at 5f45e7ca96f34fa8e904cdaa46576b60ffcfb477, linked to #5326
However, this was in version 8 and I believe the model has changed in version 10 that may produce an issue that was not present before.
