### ISSUE TITLE
 [I18N] product : Translation term issue

### ISSUE THREAD

**Issue by abhishekspellbound** [odoo/odoo#157418]
I am not able to open product view on Swedish language

https://github.com/odoo/odoo/blob/065b6632b133d780543c9f40beb536c2ff37ff52/addons/product/i18n/sv.po#L163

**Comment by lathama** [comment]
So the translated string is not escaping the " ouch

**Comment by lathama** [comment]
@abhishekspellbound can you update the title to have [I18N] at the start.

**Comment by vava-odoo** [comment]
Hello @abhishekspellbound 
Thanks for reporting, but translations are handled on [Transifex](https://explore.transifex.com/odoo/), not Github (see the [translation documentation](https://github.com/odoo/odoo/wiki/Translations)).
It seems like it was updated lately, at least in 17.0 (https://github.com/odoo/odoo/blame/17.0/addons/product/i18n/sv.po#L227). 
I'm closing the issue but please don't hesitate to contribute directly on transifex.
Cheers
