### ISSUE TITLE
Error After regis Payment ( Customer invoice) branch 8.0

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#1574]
-  Today i have issue
-  When I regis payment for my customer --> Show wizard account.voucher regis payment but this done form view account payment not loading again, button regis payment do not active.
-  I hava invoice 1,000,000. The first i regis invoice 500,000, the second regis 300,000 but Balance this invoice have is 1,000,000.

![screen shot 2014-08-05 at 9 15 32 am](https://cloud.githubusercontent.com/assets/3313064/3806216/ee193aca-1c46-11e4-89d2-a2503a6d82fd.png)
![screen shot 2014-08-05 at 9 06 10 am](https://cloud.githubusercontent.com/assets/3313064/3806219/f2b60022-1c46-11e4-93dc-b844d2d676f9.png)

**Comment by Yenthe666** [comment]
Hi @thanhchatvn,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
