### ISSUE TITLE
[10.0] mrp - Consumed raw materials

### ISSUE THREAD

**Issue by ig-landoo** [odoo/odoo#15748]
**Impacted versions:**
10.0

**Steps to reproduce:**
1)Create a Manufacture Order with two raw materials:
1 raw material with LOT tracking.
1 raw material with NO tracking.
2)Click on "Produce" button.

**Current behavior:**
At the "Produce" wizard:
- "NO tracking" products are not shown. Only LOT tracked products appear.
- Quantity "Done" of components is not filled, always remains as 0 and user needs to manually enter this info.
- If produce quantity is changed, it does not recalculate the quantity of raw materials.

**Expected behavior:**
- It is expected the same behavior as v9.
- All raw materials should appear in the wizard.
- The estimated quantities of raw materials should be recalculated in proportion to produced quantity.

**Video/Screenshot link (optional):**
![image](https://cloud.githubusercontent.com/assets/22503846/23662518/26bf7aae-0350-11e7-8d86-188666cf96fd.png)

![image](https://cloud.githubusercontent.com/assets/22503846/23662539/3f6c2f20-0350-11e7-94f5-591f2308c104.png)

**Comment by js-landoo** [comment]
Hi everyone.
I just write to notice that what my colleage Ignacio explains is a MISSING V9 FEATURE.
And as a consecuence, this screen has turned a 30% less productive.
It impacts only when we have raw materials with tracking.

Nobody has detected similar behaviour?

Thanks.

**Comment by sle-odoo** [comment]
Hi,

That's how v10 works. Sadly it's not possible to introduce this behaviour back again in a stable release. V11 is now more like v9.

Regards
