### ISSUE TITLE
[10.0] Purchase: PO lines add refunded qty to invoiced quantity

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#15757]
Impacted versions:
- At last 10.0

Steps to reproduce:
1. Install the purchase module
1. Create a purchase order for 10 pcs of a product
1. Confirm the order
1. Receive the order
1. Create a Vendor Bill from the order
1. Return 3 of the products
1. Open the original bill and click "Ask refund"
1. Set 3 pcs on the Vendor Refund and confirm

Current behavior:
- On the purchase order line, it says we have 
  - Ordered Qty 10 pcs (correct)
  - Received Qty 10 pcs (incorrect but in another issue #13974)
  - Billed Qty 13 pcs (incorrect)

Expected behavior:
- On the purchase order line, it should say we have been billed for 7 pcs, to reflect the fact that we have not in fact been billed for more products than we have received.

Details:
- The problem stems from the fact the computation method for the billed quantity on the line does not take into account the type of invoice when calculating the sum, unlike the `sale.order.line` equivalent. Compare

[`purchase.order.line,_compute_qty_invoiced`](https://github.com/odoo/odoo/blob/10.0/addons/purchase/models/purchase.py#L523)

vs

[`sale.order.line,_get_invoice_qty`](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L584)

The solution would seem to be to take the invoice type into consideration when calculating the billed amount. The function was originally committed by @nim-odoo, please feel free to comment if there is a reason not to count the billed quantity in the way I've described.

**Comment by bistaray** [comment]
Same feedback as on the linked issue.

My customers already have the Invoice for 10 units.  They need to process an Invoice for 10 units, even if they turn them back at the dock and never take delivery.

Once that Invoice for 10 units is created by the Vendor, it is a legal document that can't be changed.  There must be a subsequent invoice created by the Vendor.

Think of it this way.

YOU sell 10 units and create an Invoice for 10 units.  Your Customer refuses delivery of 5.  You can cancel and reissue the Invoice, but you can't change it to five units, can you?  

(AGAIN, if this is different where you work, I've read the responses from the linked issue.  Just posting that my customers have not asked for Odoo to work this way, and would want the option to

**Comment by pedrobaeza** [comment]
That's when a flag "To refund" enters in the play: for letting any of the 2 scenarios, but both are needed.

**Comment by aisopuro** [comment]
@bistaray, as I understand it the received quantity is used to determine the default amounts to be invoiced when you create a new Vendor Bill from the order. So as I understand you scenario, what you need is:
1. You have ordered 10 pcs.
2. You have received only 4 pcs.
3. When you create the vendor bill, it should default to 10 pcs, not 4.

Am I correct?

This seems a bit like the Invoice Policy on the sale side: products determine whether they should be invoiced based on delivered or ordered quantities. Would something similar work here, a Billing Policy field on the product? And a default setting for it, like the Invoice Policy has?

**Comment by nim-odoo** [comment]
Actually, this is a known issue. The flag "To Refund" is handled in Sales, but not in Purchase. Unfortunately, the model doesn't allow us to do something clean in Purchase since:
- getting all stock moves originating from a given stock move is not straightforward (no `parent_id`/`child_ids` fields)
- the procurement group is not always used in Purchase.

We could maybe handle simple returns, but once there are multiple receipts/returns, that's a mess. Hopefully we will be able to solve this for next release.

See another related issue: https://github.com/odoo/odoo/blob/10.0/addons/purchase/models/purchase.py#L88

**Comment by pedrobaeza** [comment]
We have finally taken another approach on purchase returns invoicing in the OCA module, not including the flag and letting the user decides at purchase order with all the proper information displayed (quantity received, quantity returned and so on). Maybe you can be interested: https://github.com/OCA/account-invoicing/tree/9.0/purchase_stock_picking_return_invoicing

**Comment by Yenthe666** [comment]
@nim-odoo could you give feedback about how this changed in V11? It would take me ages to figure out while you most likely know it out of your head. 😆

**Comment by pedrobaeza** [comment]
This has been done on v11 (the flag "To refund" is now used for both sales and purchase) and for v10 you have the mentioned OCA module, so closing this.
