### ISSUE TITLE
[10.0] User with [Inventory - User] access rights cannot create pickings

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#15769]
Impacted versions:
- At least 10.0, tested on 40 minute old runbot at time of writing

Steps to reproduce:
1. Install Inventory module (`stock`)
1. Create a user who has the access right level "User" in the Inventory app.
1. Log in as that new user.
1. Go to the Inventory app and create a new picking: the form will displayed normally, and you will be able to freely modify it
1. Add a product and choose a picking type
1. Press "Save"

Current behavior:
- The user is given an access error and is unable to save the picking:
```
Sorry, you are not allowed to modify this document. Only users with the following access level are currently allowed to do that:
- Inventory/Manager

(Document model: stock.picking.type)
```

Expected behavior:
- The user should be able to save and process a picking with the lowest inventory user rights

Speculation:

Debugging in my local environment shows that the problem seems to be caused by a `write` triggered by the field `stock.picking,picking_type_code`, defined [here](https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_picking.py#L245). It is a `related` field to `stock.picking.type,code`. I am not sure why it is triggering a write operation, as I understood that related fields weren't normally supposed to do that. Could it have something to do with the fact that the related field has a (seemingly redundant) second definition of possible selections (the original field [already defines the same options](https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_picking.py#L30))?

**Comment by aisopuro** [comment]
@Yenthe666, this seems to me like a fairly major bug, since it means users have to be Inventory Managers to be able to do basic stock operations. Do you know who might be best suited to this? It seems @tde-banana-odoo was the one who migrated the code to the new API, but the migration wasn't supposed to change any functionality.

**Comment by bistaray** [comment]
The line causing this error (which I can verify) is in stock_picking.py:

https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_picking.py#L405

`vals[name] = self.env['stock.picking.type'].browse(vals.get('picking_type_id', defaults.get('picking_type_id'))).sequence_id.next_by_id()`

vals['name'] is being assigned the next available sequence.

One potential fix is to add sudo() to the call like this:

`vals['name'] = self.env['stock.picking.type'].browse(vals.get('picking_type_id', defaults.get('picking_type_id'))).sequence_id**.sudo()**.next_by_id()`

**Comment by Yenthe666** [comment]
@mart-e can you look at this? 
@bistaray usually a .Sudo() is a drastic measure. Don't forget that this executes the call as if it is done by an admin. You're ignoring every single security rule without identifying the problem then.

**Comment by sle-odoo** [comment]
I stumbled over it some times ago and the rationale was that a basic stock user should only work on already created pickings. Indeed, a basic stock user should only fulfil pickings created by procurement according to the routes/reording rules/etc. These are the "basic stock operations".
@jco-odoo am i right?

**Comment by bistaray** [comment]
This is a fair point. Regular users perhaps should not have permission to move items unless a process or a manager has created a picking first.

**Comment by aisopuro** [comment]
I think that moving stock in the warehouse seems like the most basic kind of activity that anyone working in a warehouse needs to be able to do @sle-odoo. This kind of "managers must approve everything" approach makes managing a warehouse very stiff and is hugely harmful to smaller operations.

Also, if the inventory user is not supposed to create pickings, maybe that should be by design, so that they cannot even see the Create-button on pickings. @bistaray's finding suggests that this is an oversight: the user has rights to create a picking, it's some other part of the process that is blocking the creation.

But just to be clear: I think that Inventory Users should have the rights to create pickings, or at very least there needs to be a third middle tier for access rights (e.g. "User - Create pickings"). If you remove this basic functionality from the User tier, that just means that everyone is going to need to be a Warehouse manager, which allows them to see a huge amount of settings and data that is irrelevant to them.

**Comment by mart-e** [comment]
Thanks @aisopuro for the analysis. I agree, it is due to a related field written.
When you create a record providing a value for a related field, the ORM will follow the relation and update the linked record, it is a ORM feature.
In this case, I believe these fields are only informative (e.g. `picking_type_code` is hidden, to be used in domains and other `attrs`). It is a side effect to have a value written at the create (for the ORM it is the same if the field was displayed or not).
The fix is pretty easy: make the field read-only for the user (does not change much as was not displayed anyway)

https://github.com/odoo-dev/odoo/commit/a654a9bfc3d

@sle-odoo @jco-odoo ok for you
