### ISSUE TITLE
[9.0]"Search More..." search tree for accounts also shows deprecated accounts

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#15767]
Impacted versions: 9.0 (did not check 10.0)

Steps to reproduce:
Create an customer/vendor invoice line and add an account using the "Search more..." drop down line or by typing and autofill.

Current behavior:
The search tree / autofill shows all accounts, also deprecated accounts.

Expected behavior:
The search tree / autofill in such contexts should only show active accounts.

Video/Screenshot link (optional):

**Comment by raycarnes** [comment]
How are you defining an inactive account?  There is no active field with standard Odoo, so if you are working with a module that adds one, then perhaps that module didn't update the search function to exclude them?

**Comment by treviser** [comment]
Sorry for being not 100% accurate, I meant "deprecated" accounts of course (wasn't it inactive in version 8?).

**Comment by bistaray** [comment]
It makes sense to me now - thanks for the additional information.  

I can confirm this on runbot ALTHOUGH if you try to post that Invoice, you will get an error:

![image](https://cloud.githubusercontent.com/assets/13910162/23816291/e043b1fa-05a0-11e7-9df6-2d3d9006e87a.png)

**Comment by treviser** [comment]
That's true, but this error message is not really user friendly, but even worse, it can be difficult for user to identify the exact cause, especially if you have several invoice lines.

**Comment by Yenthe666** [comment]
@qdp-odoo perhaps this is something we can slightly change? I don't think we should see the 'depracated' accounts here?

**Comment by qdp-odoo** [comment]
I confirm this as a bug

**Comment by qdp-odoo** [comment]
fixed in master at revision https://github.com/odoo/odoo/commit/b9a9daca17b0f71961d226c85b4f67892932bd92, for saas 17
