### ISSUE TITLE
[10.0]Cannot see custom pages in Quotation -> Order Lines -> Product Page Popup View.

### ISSUE THREAD

**Issue by mikeross6233m** [odoo/odoo#15760]
Impacted versions:
10.0

Steps to reproduce:
1. Create a custom page in product form view using xpath.(Code for reference)

          <record model="ir.ui.view" id="product_template_form_view_sample_fields">
            <field name="name">product.template.sample.fields</field>
            <field name="model">product.template</field>
            <field name="inherit_id" ref="product.product_template_only_form_view"/>
            <field name="arch" type="xml">
                <xpath expr="//page[@name='general_information']" position="before" >
                    <page string = "Product Specs" name="product_item_specs">
                           <group>
                                <field name="product_sale_unit" colspan="2" />

2. Create new Quotation, select product and go to product page by clicking small button on the right.
3. Check if the newly created custom page can be accessed or not from the popup product view.

Current behavior:
Only custom fields placed above the pages can be accessed but not the pages inside the notebook.
Product Specs and Product Details Pages are not visible(see screenshots).

Expected behavior:
The Pages should be accessible from the popup view described above.

Note:
Please feel free to correct me if I am implementing it in a wrong way.

Video/Screenshot link (optional):
Expected Pages View:
![product pages](https://cloud.githubusercontent.com/assets/14011478/23701543/39ffa918-041d-11e7-9b50-1262b189ceb6.png)

Current View:
![product popup](https://cloud.githubusercontent.com/assets/14011478/23701831/7e9ff824-041e-11e7-864f-e8aa8be07702.png)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
