### ISSUE TITLE
[10.0] Product name not changed in product_template.name when changed

### ISSUE THREAD

**Issue by Floggedhorse** [odoo/odoo#15771]
Impacted versions: Odoo 10.0 (Community Edition) 

Steps to reproduce:
1) Create a product
2) Call it say "product name 1" - save
3) View db product_template.name =  "product name 1 ... all good :)
4) Rename "product name 1" to say "product name 2" - save
5) View db product_template.name =  "product name 1 ... erhhh ?:)
6) But "product name 1" is still called  "product name 2" ... where is the value coming from ... I do not know

Current behaviour:
Affects purchase orders, where the name value is inherited.
Cannot see a way to change this value

Expected behavior:
"product name 1" to become  "product name 2" and the value to be stored in product_template.name

Video/Screenshot link (optional):

**Comment by raycarnes** [comment]
I tried to replicate this on runbot but could not.

I exported the product (template) between step 3 and 4 and the value of name changed both times in both the user interface and the export file.

I then created a Purchase Order, there was no "product name 1" to add to it.

I then requested procurement for this project, a draft Purchase Order was created, with "product name 2" in both the name and description.

**Comment by Floggedhorse** [comment]
Cheers Ray for taking the time to check. 
I have repeated the process and taken some screen shots, PgAdmin 4 used to access and view the database.

1. Create a product
2. Call it say "product name 1" - save
![1](https://cloud.githubusercontent.com/assets/25161454/23791983/0fa7225c-057d-11e7-985a-c0f09a9805cd.JPG)
3. View db product_template.name = "product name 1 ... all good :)
![2](https://cloud.githubusercontent.com/assets/25161454/23792023/341a7abc-057d-11e7-8a27-39084eb3fd6c.JPG)
![3](https://cloud.githubusercontent.com/assets/25161454/23792035/3f34bea8-057d-11e7-91cc-3ab4e858c6b6.JPG)
4. Rename "product name 1" to say "product name 2" - save
![4](https://cloud.githubusercontent.com/assets/25161454/23792051/4dcf6404-057d-11e7-832d-720cd7153589.JPG)
5. View db product_template.name = "product name 1 ... erhhh ?:)
![5](https://cloud.githubusercontent.com/assets/25161454/23792056/5407bbb4-057d-11e7-82f8-cf77a5c60c19.JPG)
6. But "product name 1" is still called "product name 2" ... where is the value coming from ... I do not know
7. Create a RFQ
![6](https://cloud.githubusercontent.com/assets/25161454/23792084/6d53423c-057d-11e7-887c-868cbcf436c6.JPG)

Still dont know where "name(Product Name 2)" is stored...At a loss :(

**Comment by gdgellatly** [comment]
Translation would be my guess.

**Comment by Yenthe666** [comment]
@Floggedhorse are you testing this in English or in another language? What @gdgellatly is saying makes sense. Can you double check?

**Comment by Floggedhorse** [comment]
Sorry gents, got distracted with work :(

Yes, native language is English, although you may have doubts if you heard me speak with my ["Lancashire dialect" ](https://en.wikipedia.org/wiki/Lancashire_dialect) .

Looking at Settings>Translations>Languages ... I have two set US and UK.

![capture](https://cloud.githubusercontent.com/assets/25161454/23893538/c3954480-0896-11e7-8ef8-0dfbd47de8d8.JPG)

Could this be a translation error from pretend English to proper English [NÖ](http://idioms.thefreedictionary.com/no+offense)

**Comment by gdgellatly** [comment]
@floggedhorse provide some evidence that this is not the case. I know that
I had so many issues with product names between UK English and us English
that eventually we had to switch off translation for product name and email
templates because it was just unmanageable.

You instead just outright say it is not the case when a us English user
cannot reproduce it and most definitely I cannot reproduce when set to us
English on a fresh install.

**Comment by Floggedhorse** [comment]
"Whoa, take 'er easy there, Pilgrim."

I cannot provide the evidence that its not the case because - it appears to be the case :(

I have turned every user to a English US speaker and "G! the proBLEM appears to have GoNe.

"Wow boy!" it appears to have solved some other issues tooo! such as notes that appear on sales orders from nowhere!

What a load of "garbage" - it luCKs lIke odoo "left a boy out there to do a man's job!"

This is going to be a real problem when we get to the word "Alooominuuummm"

**Comment by Floggedhorse** [comment]
Issue closed - put down to translation issues

Thanks to all
