### ISSUE TITLE
GraphQL endpoint for Odoo

### ISSUE THREAD

**Issue by kapaspeter** [odoo/odoo#15774]
Impacted versions: 11

Steps to reproduce:

Current behavior:

Expected behavior:
GraphQL interface for all odoo models data, and for model methods.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @kapaspeter,

Thanks for your report.
There is however no Odoo 11, our latest release is Odoo 10. The 11 that you're talking about is the master version and it is still under heavy development so it has no point to create reports against this version.
Besides of those points your issue has barely any information so we can't have any idea what you want or are talking about. So, please, if you create a new topic add more information. This way we can help you too.

Regards,
Yenthe
