### ISSUE TITLE
[9.0] When i put new content in a web page sometimes i lose the content

### ISSUE THREAD

**Issue by johnsh** [odoo/odoo#15770]
Web editor

Impacted versions: 9.0

Steps to reproduce: sometimes happens

Current behavior: When i put new content in a web page sometimes i lose the content

Expected behavior: Save the content always when i put new or edit the content

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Steps to reproduce: sometimes happens

:-1: 


Impossible to reproduce !
Thank for the reporting

**Comment by mart-e** [comment]
Hello,

Sorry but we will need more information than that.

> Video/Screenshot link (optional):

Here it would have been a good idea to put one.

**Comment by johnsh** [comment]
Hi, 
I have 3 videos

https://www.dropbox.com/s/jpfq3dsvbb55nvy/VID-20170224-WA0007.mp4?dl=0

https://www.dropbox.com/s/gl7ac032fzz334t/VID-20170308-WA0001.mp4?dl=0

https://www.dropbox.com/s/053q7c3fqughtat/VID-20170308-WA0002.mp4?dl=0

**Comment by mart-e** [comment]
I am wondering if you really want us to solve your issue. You need to give us a way to reproduce your issue. Filming vaguely your screen with your phone while you make some unclear operations is not helping us very much (we know you are working with the website, that is a start).

- which theme are you using?
- which snippet are you dropping?
- where do you put the content?

We need **precise** information to reproduce the bug.

**Comment by johnsh** [comment]
yes, i have some problems to reproduce the problem,  is very difficult
