### ISSUE TITLE
[10.0] Cannot contact geolocation servers.

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#15784]
Impacted versions: 10

Steps to reproduce:
We go to the partner's card on the Partner Assignment tab and click on Geolocation

Current behavior:
![screenshot_6](https://cloud.githubusercontent.com/assets/11208423/23747409/988ff0ce-04d0-11e7-9e2d-df0849139386.jpg)

Expected behavior:
What would be assignment partner.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@collex100,

Thank you for your report.
I've just tested this but the geolocation service works fine. Could you try again? Perhaps you didn't have internet access or the geolocation servers where down at the moment.

Regards,
Yenthe

**Comment by collex100** [comment]
My version of Odoo is installed on CenOS 7. For a whole month I'm trying to launch this function and every time I get a response about which you reported.
Maybe I need something to install on the server additionally?

**Comment by JKE-be** [comment]
can you test with a browser to see:
https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=xxx

If this first step works, can you try in python with urlib
if it works, odoo should be ok...

Else, can you test with urllib2 ... 


Thanks

**Comment by collex100** [comment]
The problem is on my server with the python-package 'urllib'.

The problem was solved by replacing the 'urllib' package with 'urllib2' in the code of the standard module Odoo 'base_geolocalize'.

Tnanks
