### ISSUE TITLE
[10] l10n_fr_fec : Compliance with law and french accounting expert software.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#15781]
author of l10n_fr_fec : @alexis-via 

Bonjour, Dear

Après l'intervention de notre expert comptable, il est apparu quelques questions problèmes autour du FEC, dans le but d'être en accord avec la loi et en accord avec les logiciels des experts comptables. https://www.legifrance.gouv.fr/eli/arrete/2013/7/29/BUDE1315492A/jo/texte

_Following the intervention of our expert accountant there appeared some questions, improvements, in order to be in compliance with the law and software of accountant expert._

- L'article 2, impose de fournir une description incluant :
`« 1° Le nom, la nature et la signification de chaque zone ;
« 2° La signification des codes utilisés comme valeurs de zone ;
« 3° Toutes les informations techniques nécessaires au traitement des fichiers, et notamment le jeu de caractères utilisé, le type de structure, la longueur des enregistrements, les caractères séparateur de zone et séparateur d'enregistrement.`
La creation d'un PDF incluant notamment la ligne 3°, à télécharger depuis le wizard serait un début de solution.

_- Article 2 requires a description including:
`(1) The name, nature and meaning of each zone;
"(2) The meaning of the codes used as zone values;
"(3) All the technical information necessary for the processing of the files, in particular the character set used, the type of structure, the length of the records, the separator characters and the record separator.` 
The creation of a PDF including the line 3 °, with the description of structure of FEC, to be downloaded from the wizard could be a solution._

- Les expert-comptables ont un nouveau logiciel de verification de FEC sous la forme de macro VBA, qui a des problèmes de lecture si il y a des tabulations dans les champs, (le logiciel doit prendre en compte les deux délimiteurs tab et pipe sur le même fichier lors de sa lecture, d'où le problème). Dans le script Odoo est-il possible de faire en sorte que les tabulations soient supprimées ?

_-Accountants have a new FEC verification software (Excel VBA macro), which has problems reading if there are tabs in the fields, (the software use the two delimiters : tab and pipe to parse the file, and generate an issue). In the Odoo script is it possible to remove the tabs ?_

- Notre experts comptable ne peut pas importer le FEC dans son logiciel d'analyse, car les comptes auxiliaires sont indiqués sur tout les comptes, alors que d'après notre expert, il ne devrait être que sur les 401, 411. D'après la loi il n'est explicitement indiqué les comptes à exclure (ou à inclure) d'avoir un compte auxiliaire. Afin de faciliter le travail de ces derniers, est-il possible d'avoir le compte auxiliaires uniquement sur les 401, 411 ? Dans l'exemple de ce document seul les comptes 401,411 sont montrés : http://bofip.impots.gouv.fr/bofip/ext/pdf/createPdfWithAnnexePermalien/BOI-CF-IOR-60-40-20-20131213.pdf?doc=9028-PGP&identifiant=BOI-CF-IOR-60-40-20-20131213

_- Our accounting expert can not import the FEC into its analysis software, because the auxiliary accounts are indicated on all accounts, whereas according to our expert, it should only be on the 401xxx, 411xxx (payable/receivable account). According to The law does not explicitly specify the accounts to exclude (or to include) to have an auxiliary account. To facilitate the work of these, is it possible to have the auxiliary account only on the 401, 411? This example in this document show only the accounts 401,411 :
http://bofip.impots.gouv.fr/bofip/ext/pdf/createPdfWithAnnexePermalien/BOI-CF-IOR-60-40-20-20131213.pdf?doc=9028-PGP&identifiant=BOI-CF-IOR-60-40-20-20131213_

- La date de lettrage indiqué dans Odoo est celle du jour où est réalisé le lettrage. Or cette note http://www.suiteexpert.fr/public/documents/awcompta/A47_AnnexeTechnique.pdf, serait plutôt d'avis a indiquer la date du plus vieux mouvement. Qu'en pensez-vous ?

_- The matching date indicated in Odoo is the create date of matching. This note http://www.suiteexpert.fr/public/documents/awcompta/A47_AnnexeTechnique.pdf, would rather indicate the date of the oldest movement link to the same matching. What do you think ?_

Ce ne sont pas de gros problèmes, mais cela ne facilite pas le travail de notre expert comptable (j'ai du faire un script pour rendre le FEC utilisable).

_These are not big problems, but it does not facilitate the work of our accountant (I had to make a script to make the FEC usable)._

Regards

**Comment by Yenthe666** [comment]
Hi @fmdl,

Thank you for your report.
Please always try to write issues in English. It is really hard for non French people to handle this and not everybody talks french.
As to the report itself: @mart-e and @qdp-odoo could you look at this? My french in combination with the accounting is a bit too much 🌵

**Comment by fmdl** [comment]
Please find the issues in French/English.

**Comment by Yenthe666** [comment]
@fmdl thank you for translating and updating your issue! 👍  One of the Odoo guys will try to look at it as soon as they have time.

**Comment by fmdl** [comment]
thank for you feedback.

**Comment by qdp-odoo** [comment]
Indeed, this need to be carefully checked.

> - Article 2 requires a description including:
(1) The name, nature and meaning of each zone; "(2) The meaning of the codes used as zone values; "(3) All the technical information necessary for the processing of the files, in particular the character set used, the type of structure, the length of the records, the separator characters and the record separator.
The creation of a PDF including the line 3 °, with the description of structure of FEC, to be downloaded from the wizard could be a solution.
Maybe just adding these information in the module description or the export wizard would be enough. Don't you think?

> -Accountants have a new FEC verification software (Excel VBA macro), which has problems reading if there are tabs in the fields, (the software use the two delimiters : tab and pipe to parse the file, and generate an issue). In the Odoo script is it possible to remove the tabs ?
We need to check that: seems like an easy issue to fix

> - Our accounting expert can not import the FEC into its analysis software, because the auxiliary accounts are indicated on all accounts, whereas according to our expert, it should only be on the 401xxx, 411xxx (payable/receivable account). According to The law does not explicitly specify the accounts to exclude (or to include) to have an auxiliary account. To facilitate the work of these, is it possible to have the auxiliary account only on the 401, 411? This example in this document show only the accounts 401,411 :
http://bofip.impots.gouv.fr/bofip/ext/pdf/createPdfWithAnnexePermalien/BOI-CF-IOR-60-40-20-20131213.pdf?doc=9028-PGP&identifiant=BOI-CF-IOR-60-40-20-20131213
@alexis-via Can you give me a clue? Is it a good idea or not?

> - The matching date indicated in Odoo is the create date of matching. This note http://www.suiteexpert.fr/public/documents/awcompta/A47_AnnexeTechnique.pdf, would rather indicate the date of the oldest movement link to the same matching. What do you think ?
The topic is currently being discussed internally. We might change that in a very near future in order to be less confusing

**Comment by fmdl** [comment]
> Maybe just adding these information in the module description or the export wizard would be enough. Don't you think?
It is a solution, but my accountant have no acces to see the description in Apps menu.

About the topic of matching number :
Generally when you stard a new fiscal year, you add in initial balance the un-matching payement. Odoo use a contuing accounting (with no closing systel), is not an issue, but when an entrie is matched, it is matched for all fiscal year, and Odoo do not make the diffrence an entrie matched with payment during the fiscal year or a futur fiscal year.

I have re-write the all accounting report : https://github.com/fmdl/account_standard_report
And you can see https://github.com/fmdl/account_standard_report/blob/master/wizard/account_standard_report.py#L559 the methode to find the matching number in the future (for each entrie link with a matching if the oldest is in the future, else this matching is considered in the future).
This module use this methode.

Regards

**Comment by fmdl** [comment]
Dear @qdp-odoo and @Yenthe666 have you see the two PR to fix the issue with the FEC ?

Regards

**Comment by fmdl** [comment]
Dear @qdp-odoo have you see the two PR to fix the issue with the FEC ?

Regards

**Comment by qdp-odoo** [comment]
Hello Florent, these 2 PR being now merged, I suppose we can close the issue.

Thanks again for the contribution

**Comment by fmdl** [comment]
Yes we can close. Thank, my account expert will be happy.
