### ISSUE TITLE
Product Import Case Sensitivity

### ISSUE THREAD

**Issue by kaptainkommie** [odoo/odoo#15793]
Impacted versions:
Odoo 10.0-20170308 (Community Edition)

Steps to reproduce:
Create Vendor entry with normal capitalization such as: JH Miller
Import excel file where Vendor is specified as: JH MILLER (in all caps).
Click Validate.

Current behavior:
Odoo complains that there is no match. Matching appears to be case sensitive. Is this the desired behavior? I can't think of a case where I would have two different vendors with the same name, but with different case. Is this a byproduct of Unicode support?

Expected behavior:
Vendor matching should not be case sensitive? Unless this is required for proper Unicode support?

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hello

thanks for the reporting.
But it is the desired behavior.

Best regards

JKE
