### ISSUE TITLE
No Back Order for kit product showing wrong delivered qty

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#158054]
Impacted versions:
17.0

Steps to reproduce:
Create a kit product
Do partial delivery for kit components
Select No Back order option
Do the delivery and check in sales order delivered quantity
Delivered quantity in sales order will show full quantity

Current behavior:
On doing partial delivery for kit bom product with no back order showing fully delivered in sales order. This is causing error in invoicing.

Expected behavior:
Need to show correct delivered quantity for with back order and without back order.

Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/45730318/faa13269-5d14-4f5a-a007-1c84121e38a2

Support ticket number submitted via odoo.com/help (optional):
3,815,357

**Comment by vava-odoo** [comment]
Hi @jabirmisnedtech 
Thanks for reporting.
Handled in https://github.com/odoo/odoo/pull/160330
Cheers

**Comment by HANNICHE-Walid** [comment]
Hello @jabirmisnedtech ,
I am glad to inform you it has been fixed.
