### ISSUE TITLE
Setting default currency doesn't change quote from USD default after install

### ISSUE THREAD

**Issue by digitalarchitects** [odoo/odoo#15803]
Impacted versions: 10.0

Steps to reproduce: Install and change currency (ZAR) enter a test quote

Current behavior: had to switch on multi currency and disable all other currencies

Expected behavior: quote in ZAR, menu option to configure symbol placement as before

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @digitalarchitects,

Thank you for your report.
If I understand this correctly you did the following things?
1) You've activated the currency ZAR:
![image](https://cloud.githubusercontent.com/assets/6352350/23938886/7d8ee3a6-095e-11e7-8924-98065e1408b1.png)
2) You changed the main currency of the company:
![image](https://cloud.githubusercontent.com/assets/6352350/23938900/8ee1de1a-095e-11e7-8f2f-3dc1c50c37f1.png)
3) You've made a quotation for a company by just selecting the company & adding products:
![image](https://cloud.githubusercontent.com/assets/6352350/23938941/c32411d4-095e-11e7-86d3-00cb143ee06e.png)


Did you change the currency for the customer (the pricelist) though? An example:
![image](https://cloud.githubusercontent.com/assets/6352350/23938981/f9b2e450-095e-11e7-8abb-64c0052964b5.png)


Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @digitalarchitects,

There has been no response in over a month.
I'm closing this report as this is (no longer) reproducable.
If you can still reproduce this on the latest source code or on a runbot then please provide us with more information and I'll reopen this issue.

Regards,
Yenthe
