### ISSUE TITLE
[14.0-17.0][BUG] Website sale configurator does not issue proper Google Analytics tracking info

### ISSUE THREAD

**Issue by Sibert-Aerts** [odoo/odoo#158052]
In eCommerce, for a product added to cart via the "product configurator" pop-up (e.g. when the product is added to cart from the grid view, and it has one or more configurable attributes,) the information sent to the `add_to_cart_event` event that goes to Google Analytics is inconsistent compared to other methods of adding it to cart.

e.g. in the case of adding a product to cart via the product page itself, the data that's passed to this event is the result of the product.template `get_google_analytics_data` method.

The product configurator however uses its own logic for composing this data, and in doing so introduces inconsistencies and even bugs, putting string values in both the "quantity" and "price" fields, causing the total "value" to become `NaN` when your website's number formatting uses commas instead of points.

The code in question:
https://github.com/odoo/odoo/blob/49d4f20242c48964b4f367a0d9ce1cdc964b6460/addons/website_sale_product_configurator/static/src/js/website_sale_options.js#L90-L96

**Comment by Sibert-Aerts** [comment]
Tagging @rdeodoo and @tdecaluwe as this code was co-authored by them, thank you for looking into this.

**Comment by rdeodoo** [comment]
Hello, we are not in charge of the ecommerce module anymore, this is something for the @odoo/rd-ecommerce team :+1:

**Comment by ltinel** [comment]
Hi @Sibert-Aerts, thanks for reporting this issue! This will be fixed as part of a revamp of the product configurator in version 17.3. I'll backport the fix to older versions afterwards.

Cheers.
