### ISSUE TITLE
Error sending mail, with template "Simple Challenge Report Progress"

### ISSUE THREAD

**Issue by egrivero** [odoo/odoo#15823]
**Impacted versions:** 10.0

**Steps to reproduce:**
Trying to send a report from the challenge "Monthly Sales Targets".

**Current behavior:**
This does not send the mail and shows me the following error in the log.
![screenshot from 2017-03-10 10 30 36](https://cloud.githubusercontent.com/assets/7115776/23815417/c0e8a86c-05ad-11e7-9dc0-ac3a51aa99fd.png)

Checking the template, I see the following error.
![screenshot from 2017-03-10 11 11 40](https://cloud.githubusercontent.com/assets/7115776/23815431/cfa9f090-05ad-11e7-8087-3dc03e3f4e73.png)

And it does not look like the template that should be loaded according to the code
[template email gamification](https://github.com/odoo/odoo/blob/10.0/addons/gamification/data/goal_base.xml#L23)

But in the template is disorganized.

**Expected behavior:**
Sending the mail without problems

**Comment by Yenthe666** [comment]
@mart-e might be for you. 😄

**Comment by mart-e** [comment]
Have you modified the template somehow ? What you show in the template viewer is a bug in the code editor but the standard template should work fine.

**Comment by mart-e** [comment]
After discussion with @tde-banana-odoo, it is an known issue with the couple summernote/chrome that is not able to render properly for loop inside a table.

So, unfortunately there is not much we can do about it. Our goal is to drop the jinja rendering to replace with QWeb (hopefully for v11).
I am afraid your best bet is to disable the web editor when modifying email templates.

**Comment by egrivero** [comment]
Hi Martin

I have not made a modification of the template, this is the default in
odoo, what I wanted to imply is that what is in the code is not the same
thing that is seen in the backend, and it is not working. I do not need to
modify it, only that it works as it comes. Now how do I disable the web
editor?

2017-03-13 7:39 GMT-06:00 Martin Trigaux <notifications@github.com>:
