### ISSUE TITLE
[7.0] Error when warehouse user confirms delivery

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#15820]
Impacted versions: 7.0

This error occurs when:

- real time stock accounting is used

- by a user that has no authority to finance (account.period, account.move ..)

When that user goes into an outgoing delivery (probably the same for incoming) and tries the button Deliver, and then Deliver, a window with an error message appears.

This is the error text:

Access Denied

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Purchases/User
- Accounting & Finance/Financial Manager
- Accounting & Finance/Invoicing & Payments

(Document model: account.period)

The problem is that the method _create_product_valuation_moves in stock.py tries to write records to account.move. Normally a warehouse user does not have any authorizations to account.move.

This might be solved be granting the warehouse users authority to Finance, but that would defeat the whole purpose of authorization.

I think the best solution will be to use the SUPERUSER_ID within the method _create_product_valuation_moves to create the actual moves.

Expected behavior: Warehouse user can confirm delivery

Bug was originally registered on launchpad. Proposed solution was never adopted:
https://bugs.launchpad.net/openobject-addons/+bug/1266480

**Comment by bistaray** [comment]
Support for Odoo 7.0 ended in 2016

https://www.odoo.com/page/odoo-long-term-support

![image](https://cloud.githubusercontent.com/assets/13910162/23815158/a5cb3688-059b-11e7-91e3-4a6b6e50e972.png)

**Comment by Yenthe666** [comment]
Hi @NL66278,

Thank you for your report.
I'm afraid that the official support for Odoo 7 is indeed dropped, which means we no longer fix bugs/issues in this version.
Feel free to ping me if you can reproduce this on another (newer) version though, I'd be happy to open this again if this is the case.
P.S: Thank you for writing out such a detailed report!

Regards,
Yenthe
