### ISSUE TITLE
odoo 10 fleet is inaccurate for accounting 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#15833]
Impacted versions:
10

Steps to reproduce:
1 install fleet
2 try to add a real values

Current behavior:
4 digits decimal value is rounded to 2

Expected behavior:
this type of expenditures come use 4 decimal digits so it should keep the 4 decimal digits

Video/Screenshot link (optional):

**Comment by bistaray** [comment]
This is a display issue only.

The actual values stored and used in calculating report totals and subtotals match what you enter.

Use the digits parameter in the view (which you can inherit and override) to show you what you entered if you need that:

![image](https://cloud.githubusercontent.com/assets/13910162/23837138/df8f2af4-0740-11e7-8ce8-2ce9dea93d25.png)

**Comment by Yenthe666** [comment]
This is indeed a displaying issue.
The database will store and calculate with the whole number, not just rounded to two digits.
P.S: Rounding is configurable under technical settings too.

Regards,
Yenthe

**Comment by icf20** [comment]
i will reinstall to test this

**Comment by Yenthe666** [comment]
@icf20 under the settings app you can configure the rounding I mean.

**Comment by icf20** [comment]
@Yenthe666 on the configuration option there is nothing related to rounding, there are users, company(under company can select currency and nothing more), general option with the login and so on, printing format

under fleet config there is only vehicle state

**Comment by icf20** [comment]
@Yenthe666 can you provide any help on this ?
