### ISSUE TITLE
[10.0] Crashed JS when `Close` modal window from one2many corresponding form

### ISSUE THREAD

**Issue by shepilov-vladislav** [odoo/odoo#15849]
Impacted versions:
    - [x] 8.0
    - [x] 9.0
    - [x] 10.0
Steps to reproduce:
1) Create form with one2many tree(for ex. line1_ids)
2) Create form for model(from 1 step) contains another one2many field like <field name="line2_ids"/>
3) Open line from line1_ids
4) Click `Close` button
Current behavior:
Crashed JS with error
```
Uncaught Error: QWeb2 - template['ViewManager']: Runtime Error: TypeError: Cannot read property 'view' of undefined
```
Expected behavior:
Nothing, only close window

**Comment by Yenthe666** [comment]
@ged-odoo this one is for you? 😉

**Comment by ged-odoo** [comment]
This one is interesting, but I couldn't reproduce it in 10.0.  Could you give me more info? it looks like the step 2 is incomplete.

**Comment by Yenthe666** [comment]
@shepilov-vladislav could you give more information please? Then @ged-odoo can look into it.

**Comment by Yenthe666** [comment]
Closing as there has been no feedback in a few months.
