### ISSUE TITLE
I can't find l10n_chart_china_standard_business_chart_data.xml in module "l10n_cn_standard". why?

### ISSUE THREAD

**Issue by sunjie20081001** [odoo/odoo#15840]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sunjie20081001** [comment]
'l10n_chart_china_standard_business_chart_data.xml' not found, it should be 'l10n_cn_standard_chart_data.xml'

**Comment by Yenthe666** [comment]
Hi @sunjie20081001,

Thank you for your report.
I believe this is the fix that is needed and that you're talking about https://github.com/odoo/odoo/pull/15841 ?

Regards,
Yenthe

**Comment by sunjie20081001** [comment]
下次我写详细点!修复及时. @ #:wink:

**Comment by mart-e** [comment]
> 下次我写详细点!修复及时. @ #😉

and next time, please keep the English for github ;-)
