### ISSUE TITLE
Error "Document does not comply with schema" should name the faulty XML file.

### ISSUE THREAD

**Issue by sylnsr** [odoo/odoo#15869]
Impacted versions: 10

Steps to reproduce: Create a module with at least one view XML file that has a non compliant schema

Current behavior: Produces error with Traceback (limited) showing at the end "AssertionError: Document does not comply with schema"

Expected behavior: It should indicate the document which caused the AssertionError, for example: "
AssertionError: Document does not comply with schema: `<path-to-add-on>/views/foo.xml`"

**Comment by sylnsr** [comment]
In order to promote a useful development environment Odoo error messages should always be intuitive and useful by being as specific as possible rather than being ambiguous and vague.

**Comment by mart-e** [comment]
But you do have file. The server logs something like

```
2017-06-19 12:20:56,097 30577 INFO 10c odoo.modules.loading: loading my_module/views/good_view.xml
2017-06-19 12:20:56,505 30577 INFO 10c odoo.modules.loading: loading my_module/views/bad_view.xml
2017-06-19 12:20:56,506 30577 INFO 10c odoo.tools.convert: The XML file does not fit the required schema !
...
```

**Comment by Yenthe666** [comment]
Martin made a minor improvement for this at https://github.com/odoo/odoo/commit/3553c555e03a6828a1d58b5ef7096e747e5b7f72 so this can be closed now.

Regards,
Yenthe
