### ISSUE TITLE
Setting disable_favorites on Search View causes Exception

### ISSUE THREAD

**Issue by aldiga** [odoo/odoo#15860]
Impacted versions: 10

Steps to reproduce: 

   favorite_menu is never created when disable_favorites is set. The line "this.$buttons && this.**favorite_menu**.get_default_filter" fails when set_default_filters is called.

```javascript
            }
            if (!this.options.**disable_favorites**) {
                **this.favorite_menu** = new FavoriteMenu(this, this.query, this.dataset.model, this.action_id, this.favorite_filters);
                menu_defs.push(this.favorite_menu.appendTo(this.$buttons));
            }
        }
        return $.when.apply($, menu_defs).then(this.set_default_filters.bind(this));
    },
    set_default_filters: function () {
        var self = this,
            default_custom_filter = this.$buttons && this.**favorite_menu**.get_default_filter();
```

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by ruter** [comment]
Related pr #21432

**Comment by Yenthe666** [comment]
This was fixed & handled at https://github.com/odoo/odoo/commit/fe8668e509d36b48a6be0c82f46a44a0f553cbb6
