### ISSUE TITLE
Event mails sent even if disabled

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#15889]
Impacted versions: 9.0e/c (did not check on 10)

Steps to reproduce:

0. Go to events > Configuration and disable event emails.
0. Create an event.
0. Create an attendee for that event.
0. Save

Current behavior: Attendee is confirmed and it gets emailed!

Expected behavior: Attendee not emailed (and not confirmed, BTW, but that could be another issue).

Video/Screenshot link (optional): [Screencast_15-03-17_14:51:51.zip](https://github.com/odoo/odoo/files/844707/Screencast_15-03-17_14.51.51.zip)

@Tecnativa

**Comment by mart-e** [comment]
Hello,

Thanks for the report but you misunderstood the point of the option. The name is "**Schedule** emails to attendees and subscribers". It is to enable this page to **schedule** emails

![selection_023](https://cloud.githubusercontent.com/assets/564822/23958296/f9262c98-09a1-11e7-81a9-0372754170bb.png)

**Comment by pedrobaeza** [comment]
Although you are right, Martin, I think that default behavior is very dangerous, as you are not seeing without the permission that something is going to be sent.

As we know, this can't be changed on stable, but for master, can you consider to disable this automatic mailing by default (or when the tab is not visible)?

**Comment by mart-e** [comment]
Hello,

Actually it is possible to disable it in stable !
The emails are only sent when the event is confirmed. The events are confirmed by default but it is possible to disable that.
There is an ir.value `event.config.settings` - `auto_confirm`. You can change it or remove it if you wish to change that.

**Comment by pedrobaeza** [comment]
Wow, I didn't know that. Then that is a good solution. @Yajo please check this discover.

**Comment by pedrobaeza** [comment]
Thanks as always for your valuable information, Martin.

**Comment by mart-e** [comment]
Also, in master it is better (not a hidden parameter you only see when reading the code), it is a parameter on the event type :)

**Comment by Yajo** [comment]
Master's approach is great! 😊 

![captura de pantalla de 2017-03-16 10-04-43](https://cloud.githubusercontent.com/assets/973709/23988775/03c1ec62-0a30-11e7-8390-0f21821923ea.png)

I understand that when the check box is unchecked, no mail is sent in any case, right?
