### ISSUE TITLE
[10.0] Wrong context for manually executed cron

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#15887]
Impacted versions: 10.0

Steps to reproduce: Manually execute a cron and check the context

Current behavior: 'active_test': False is present in context

Expected behavior: 'active_test': False should not be present (it is not in previous version)

It seems to come from the action window 'ir_cron_act' because the context active_test is set.
But the same is done in version 9 and I can't reproduce the bug, so I guess it impacts version 10 only.

**Comment by pedrobaeza** [comment]
Is this still happening in latest code and in v11?

**Comment by pedrobaeza** [comment]
Closing as no answer.
