### ISSUE TITLE
Wishlist: Group by one2many fields

### ISSUE THREAD

**Issue by technicomp** [odoo/odoo#15885]
Impacted versions: 10

Current behavior:
As far as I understand, it is not possible right now to group by one2many fields. 

Expected behavior:
We are selling ink for printers - every ink is compatible with a bunch of different printers, it would be great if on the one hand i could define in the product the compatibility (printer model) via a one2many field and when creating a quotation or sales order I could simply group by printer model and be able to select the corresponding inks.

**Comment by pedrobaeza** [comment]
This is something impossible, as this will change the cardinality of the records and lead to more confusions than benefit.

Closing as this is not something feasible.
