### ISSUE TITLE
[V10 EE + CE] Product variant cost price not 'copied' to purchase order

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#15894]
Impacted versions: V10 Enterprise and Community Edition

Steps to reproduce:
Create product with 2 variants
![image](https://cloud.githubusercontent.com/assets/7501203/23977562/f172185c-09bc-11e7-867b-7fdee9467b62.png)

![image](https://cloud.githubusercontent.com/assets/7501203/23977609/fe18aeae-09bc-11e7-9843-64d808068570.png)

add costprice to variants
![image](https://cloud.githubusercontent.com/assets/7501203/23977618/1024f67a-09bd-11e7-9483-7a84875070d6.png)

create purchase order with the product variant
![image](https://cloud.githubusercontent.com/assets/7501203/23977626/23ce23b8-09bd-11e7-8f4c-2a41e6544ae8.png)

Current behavior:  
the cost price is 0.00

Expected behavior: 
like the help text says: Cost of the product template used for standard stock valuation in accounting and **used as a base price on purchase orders**

So the purchase order line in this case should say 30.00 instead of 0.00

**Comment by Yenthe666** [comment]
Hi @aduijs,

Thank you for your report.
The idea is that you handle the costprice based on the variant as variant X may have another purchase price as variant Y. You can set the costprice on the variant:
![image](https://user-images.githubusercontent.com/6352350/34780923-bf0be578-f624-11e7-8244-c26405d0f0af.png)
However, on the purchase order it doesn't seem to take the price from the product though:
![image](https://user-images.githubusercontent.com/6352350/34780986-ea975786-f624-11e7-85f5-0fe9f3ad27fc.png)

![image](https://user-images.githubusercontent.com/6352350/34781134-54cf5c3e-f625-11e7-978c-0ce68740a9f5.png)

@mart-e and @sle-odoo shouldn't it take the price from the product variant and fill it in as unit price in the PO?

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
This is because Odoo has changed the meaning of the field. The cost price is only used for registering back the average cost valuation price, but not for purchase quotations, where the suppliers list must be used. I know that in v8 this price was used as a fallback for the purchases if no supplierinfo is found, but this was confusing for some users, and thus it was removed.

Closing as no real issue.
