### ISSUE TITLE
Odoo 10 quantity not updating

### ISSUE THREAD

**Issue by pytechqudra** [odoo/odoo#15897]
**Impacted versions:**
Odoo 10
**Steps to reproduce:**
Create "Request for quotation" purchase module -> add items,quantity -> confirm order -> receive products.
**Current behavior:**
Quantity not updating in inventory
**Expected behavior:**
Quantity to be updated in inventory.. tried both the steps mentioned below in screenshot
**Video/Screenshot link (optional):**
![screenshot from 2017-03-16 12 10 56](https://cloud.githubusercontent.com/assets/26219400/23985318/6baae9be-0a44-11e7-9e2a-2348931c8ea0.png)

**Comment by jco-odoo** [comment]
?

**Comment by Yenthe666** [comment]
Hi @pytechqudra,

Thanks for your report.
I'm not really sure what you're trying to ask or what the issue is though. Can you add more information or screenshots?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @pytechqudra,

I'm closing this issue as there has been no response in months.
Don't hesitate to reopen or comment if you still face this issue and can reproduce it on a runbot.

Regards,
Yenthe
