### ISSUE TITLE
Create custom filters on Invoice List (account.move)

### ISSUE THREAD

**Issue by dieptang** [odoo/odoo#159024]
I aim to craft a bespoke filter applicable to all users within Odoo 17. Below is the code I've assembled:

`class AccountMove(models.Model):
    _inherit = 'account.move'
   
  
     @api.model
     def get_views(self, views, options=None):
         res = super().get_views(views, options)
         if res['views'].get('list'):
             print("=====================")
             # Construct the default domain
             res['views']['filters']=[
                     ('create_date', '>=', (datetime.now() - relativedelta(day=1)).strftime('%Y-%m-%d')),
                     ('create_date', '<=', datetime.now().strftime('%Y-%m-%d')),
                     ('payment_state', 'in', ['paid', 'partial']),
                     ('user_id', '=', self.env.user.id)
                 ]
             print(res['views'].get('filters'))

         return res`

However, it appears to be ineffective. Could someone kindly lend their expertise to resolve this issue?

**Comment by kalungia** [comment]
Which error are you getting?

**Comment by vava-odoo** [comment]
Closing as no answer + custom code should be discussed on the [forum](https://www.odoo.com/forum/help-1)
