### ISSUE TITLE
Odoo advertising

### ISSUE THREAD

**Issue by Werner0** [odoo/odoo#159034]
I've attached a screenshot of what I see on my Microsoft Edge browser's Discover tab. I'm looking at this page from Hong Kong with my region and language set to Malaysian English. I do not have an immediate need for business apps, but I might need it in future. I got your message, so you don't have to spend any more money advertising to me.

Impacted versions: NA

Steps to reproduce: NA

Current behavior: NA

Expected behavior: NA

Video/Screenshot link (optional):
![Screenshot 2024-03-24 205520](https://github.com/odoo/odoo/assets/11156694/6645687f-83e7-4167-a4d8-55584f7d1e0e)

Support ticket number submitted via odoo.com/help (optional): NA

**Comment by kalungia** [comment]
These adds may show  in your browser because you may have visited any of the website in this case Odoo website. Kindly close this.

**Comment by kalungia** [comment]
This is not Odoo problem rather your browser, just go clear cache.

**Comment by Werner0** [comment]
Clearing the cache doesn’t solve the problem. Odoo ads also appear at the top of search engine results, and on multiple devices. I reported the Odoo ads in the Microsoft Edge Discover tab using the report function, but the ads just reappear in other panels. Since these are Odoo ads, Odoo should investigate how it happens that the Odoo brand is a nuisance to users who are not within Odoo’s target market. An audit might help.

**Comment by kalungia** [comment]
Again it is not about Odoo but search engine and your browser

**Comment by Werner0** [comment]
It’s about Odoo. And I’ll make a complaint against your fly-by-night business with the Hong Kong consumer complaints board.

**Comment by OpenCode** [comment]
> It’s about Odoo. And I’ll make a complaint against your fly-by-night business with the Hong Kong consumer complaints board.

Please, keep us updated. We want to know more.

**Comment by Werner0** [comment]
> > It’s about Odoo. And I’ll make a complaint against your fly-by-night business with the Hong Kong consumer complaints board.
> 
> Please, keep us updated. We want to know more.

Here’s a link to more information about [consumer rights in Hong Kong](https://www.consumer.org.hk/en/complaints-and-services).
