### ISSUE TITLE
A purchase manager cannot create a new vendor bill when a previous vendor bill for this PO is already paid

### ISSUE THREAD

**Issue by gva-acsone** [odoo/odoo#15900]
Impacted versions: V10

Steps to reproduce: 
1. With your purchase manager, create a new Purchase Order and order 10 quantities of a same article
2. Confirm the Purchase Order
3. Create a draft vendor bill, but only receive a part of the ordered quantity (5 for instance, a second bill will be sent by the supplier later)
4. With your accounting user, validate and pay your first vendor bill
5. Go again on your purchase manager and try to create a new vendor bill to receive the remaining 5 quantities you ordered.

Current behavior:
Odoo warning, because we are not allowed to access the paid invoices.
Message shown: Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Inventory/Manager
- Accounting & Finance/Billing
- Accounting & Finance/Accountant

(Document model: account.partial.reconcile)

Expected behavior: You are not allowed to access the paid bills (or in read only state), but, as a purchase manager, you are allowed to create new vendor bills on this PO to receive the remaining quantity.

Video/Screenshot link (optional):

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
OPW 725360

**Comment by Yenthe666** [comment]
@adrienpeiffer could you give feedback about OPW 725360 please? Is this indeed considered a bug or not?

**Comment by adrienpeiffer** [comment]
@benwillig Could you check ? 🎁
