### ISSUE TITLE
[Proposal] Outgrowing SME Accounting

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#15915]
Odoo has actually a rather poor support for multinational accounting. I guess that's nothing in need for further detail, if we are really frank to ourselves.

Therefore, I would welcome on behalf of many erratic localization attempts to adopt the mickey mouse aproach detailed in this link: http://www.risktech-forum.com/opinion/multi-gaap-2.0-nickname-mickey-mouse-accounting

@qdp-odoo @fpodoo  the sooner, the better, the brighter and bigger! 😄

**Comment by blaggacao** [comment]
What I need to know for now is:
When you implement this, will it be rather 
a) a Many2one tag on the account move (similar to a journal) or
b) a separate (and possibly greatly simplified) separate model

NO, journals are no alternative, as I would need this generic feature in (almost) any report just as globally situated as company is handled throughout, whereas journals and their types are a significant part of the report details itselves.

**Comment by blaggacao** [comment]
Step 1: https://github.com/odoo/enterprise/pull/871

**Comment by pedrobaeza** [comment]
Closing as this has been discussed somehow in other points more unfolded.

**Comment by blaggacao** [comment]
Thanks @pedrobaeza for your work! I wish I would find the time soon to cleanup my Issue/PR inventory myself...
