### ISSUE TITLE
Database restore error

### ISSUE THREAD

**Issue by PrabinGyawali** [odoo/odoo#15917]
Impacted **versions:** V10 Community

Steps to reproduce: When I try to restore database but i receive following error.

Current behavior:"Database restore error: Too much data for base64 line"

I am using linux ubuntu 16 as OS and database size is 1.3 GB.

**Comment by odoouser2** [comment]
I too have the same error, any update on this issue?

**Comment by Yenthe666** [comment]
Hi guys,

This means one of the attachments that is added to your database was so big that the base64 line exeeded the data limit.
If you do a restore of your database from the command it should work fine though.

Regards,
Yenthe
