### ISSUE TITLE
How to set MOQ(Minimum Order Quantity)

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#15931]
Hi:
I am using odoo 10 to wholesale products,in my case i want to set MOQ to some products,how to do it?

**Comment by Yenthe666** [comment]
Hi @ed29,

The Github issue tracker is only for bugs in the official code, not for asking question.
You can ask this on the official help forums (help.odoo.com) where plenty of people can help you or have a look at the official docs at https://www.odoo.com/documentation/user/10.0/index.html

Regards,
Yenthe
