### ISSUE TITLE
[10.0] hide columns in list view based on set context in a filter not working

### ISSUE THREAD

**Issue by goreki** [odoo/odoo#15951]
Impacted versions: 10.0

Steps to reproduce:
1. create a list view with a search view
2. define a filter like so:
`<filter string="Test" name="filter_test" domain="[]" context="{'test_ctx':True}"/>`
3. define the list view with a field like so:
`<field name="field_name" invisible="context.get('test_ctx', False)"/>`
4. try to hide the column by using the created filter "Test"

Current behavior:
It doesn't do anything. column still shows as if there is no context set at all

Expected behavior:
The column of the field "field_name" should be hidden after selecting the filter, which sets the context.
It was working in Odoo8 as expected. I dont have experiences with other versions.

**Comment by pedrobaeza** [comment]
@ged-odoo I have also experimented this in the module https://github.com/OCA/account-financial-tools/tree/10.0/account_balance_line. Is this has been fixed meanwhile?

**Comment by intero-chz** [comment]
I had opened an enterprise ticket and quoted the answers here: #20854

**Comment by pedrobaeza** [comment]
Then the answer seems clear:

> I went to talk with the framework guys, and they told me it may return in v12.
But they're still unsure because they have a lot of work to do, while trying to make the frontend more stable.

Closing this.
