### ISSUE TITLE
RPC call with TimeZone problem

### ISSUE THREAD

**Issue by mrgaolei** [odoo/odoo#15954]
Impacted versions:
`v9`

Steps to reproduce:
```json
{
"jsonrpc":"2.0",
"method":"call",
"params":{
"model":"sale.order",
"fields": ["name", "date_order"],
"context": {"timezone":"Asia/Shanghai"}
}
}
```

Current behavior:
The returned `date_order` is `2017-03-20 12:00:00`, the same as database's data.

Expected behavior:
But It will be `GMT+8`: `2017-03-20 20:00:00`

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@xmo-odoo perhaps this one is for you? I believe you're the XML-RPC pro? 😄

**Comment by mrgaolei** [comment]
@Yenthe666 Thanks, but I'm using Json-RPC.
Is XML-RPC work same like Json-RPC?

**Comment by Yenthe666** [comment]
@mrgaolei sorry I intended to type JSON-RPC. Corrected my comment.

**Comment by mrgaolei** [comment]
OK, @Yenthe666 . I looking forward to your answer. Thanks.

**Comment by pedrobaeza** [comment]
Datetimes are presented in UTC if no tz context key is passes, so this not an actual issue, but misunderstanding on how to work with this, and thus I'm closing it.
