### ISSUE TITLE
[15.0] hr_work_entry_contract: issue with term translation

### ISSUE THREAD

**Issue by andreagidaltig** [odoo/odoo#159771]
Impacted versions: 15.0

Steps to reproduce: 
1. Go to Payroll 
2. Go to Configuration > Work Entry Types
3. Open "Annual Time Off 2024" work entry type
4. Change user language to Spanish

Current behavior:
When changing the language to Spanish the translation of "Annual Time Off 2024" since it takes the current year [[1]](https://github.com/odoo/odoo/blob/15.0/addons/hr_work_entry_contract/data/hr_work_entry_data.xml#L42) but the translation is  "Permisos legales 2022" [[2]](https://github.com/odoo/odoo/blob/15.0/addons/hr_work_entry_contract/i18n/es.po#L205)

Expected behavior:
- Translation must be  "Permisos legales 2024"
- Another option is to change "Annual Time Off 2024" to "Annual Time Off" and "Permisos legales 2022" to "Permisos legales"

[1] https://github.com/odoo/odoo/blob/15.0/addons/hr_work_entry_contract/data/hr_work_entry_data.xml#L42
[2] https://github.com/odoo/odoo/blob/15.0/addons/hr_work_entry_contract/i18n/es.po#L205

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/130611250/13bb989d-358e-4673-9839-e8e77ee18281)

![image](https://github.com/odoo/odoo/assets/130611250/71fc624a-0d4f-4940-8f37-18a6f66803cd)

**Comment by luistorresm** [comment]
Hello @mart-e 

What do you think about this ticket?

Regards

**Comment by mart-e** [comment]
@luistorresm I forwarded to the appropriate team and they are fixing it at https://github.com/odoo/odoo/pull/159847
