### ISSUE TITLE
No difference between automatic and manual 'Automatic moves' on push rules

### ISSUE THREAD

**Issue by gva-acsone** [odoo/odoo#15970]
Impacted versions: V9/V10

Steps to reproduce:

Whether you select 'Manual Operation' or 'Automatic no step added' on your push rule (automatic move list), in both cases, you need to validate your stock moves manually. 

Current behavior:

In V8, there were three options for the 'Automatic move' field on your pursh rule:
- Manual: manual validation was needed (still the case in V10)
- Automatic: The validation of the stock move was automatically done when the push rule was used (this option doesn't exist anymore)
- Automatic no step added: The destination location defined on your existing stock move was automatically modified according to your source and destination locations defined on your push rule.

In V9, the three options were still present, but none of the two last ones worked properly. They all worked the same way as the manual validation.

In V10, only two options are present: Manual and 'Automatic no step added'. There is no difference between these two options.

Hence, it is currently impossible to define automatic push rules. Manual validations are always requested.

Expected behavior:

The three options should be present as they are all necessary. 

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
Actually, automated push rules should not be used in picking since v9. I don't know why these options were still available. We'll have a look to clean them in master.

Thank you

Regards
