### ISSUE TITLE
shop order not working as expected

### ISSUE THREAD

**Issue by vkanev** [odoo/odoo#15974]
Impacted versions:10

Steps to reproduce:just use order and see there is no difference in product order

Current behavior:not working at all

Expected behavior:should reorder products by given criteria

Video/Screenshot link (optional):

As I need it working I have found the problem:
[line 234] odoo/addons/website_sale/controllers/main.py
`products = Product.search(domain, limit=ppg, offset=pager['offset'], order=self._get_search_order(post))`
should be like this:
`products = Product.search(domain, limit=ppg, offset=pager['offset'], order=post.get('order'))`.

Parameter is looked for in POST not in GET parameters of the HTTP request. After making the change everything is now working as expected.

**Comment by JKE-be** [comment]
You are wrong. _get_search_order should do the job. Please, describe what seems wrong for you in the order !

**Comment by vkanev** [comment]
The thread is really old. I forgot to close it as it's not relevant anymore.

Anyway, thanks for the answer!
