### ISSUE TITLE
Windows could not start the odoo-server10.0 10.0 service on local Computer. Error 1053: The service did not respond to the start or control request in a timely fashion.

### ISSUE THREAD

**Issue by mayurvartak74** [odoo/odoo#15988]
Impacted versions: Odoo 10.0

Steps to reproduce: Run -> Services -> Right click on odoo-server-10.0 -> Start

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by yeremia-rainier** [comment]
i have this problem also, any help available?

**Comment by Yenthe666** [comment]
Hi @mayurvartak74,

Can you please try the latest installer and try this again? Alternatively @yeremia-rainier can you try this?
CC @d-fence it is not about the packages but related to the OS, so might be of interest for you to double check.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.

**Comment by oJamie** [comment]
The problem could be that the  Odoo-server and the PostgreSQL are both disabled. So set the server to automatic as well as the PostgreSQL and then try restarting your server.

**Comment by kchikech** [comment]
I have the same issue on Win Server 2012 . PostgreSQL is running and the Odoo 13.0 is paused .

**Comment by PromoBrick** [comment]
Both PostgreSQL and Odoo 10 Services unable to run
