### ISSUE TITLE
odoo 10 / 11 on synology

### ISSUE THREAD

**Issue by marindumont** [odoo/odoo#15981]
They are no more update since odoo 8 for synology?
They are any infos to install odoo 10 ?

**Comment by Yenthe666** [comment]
Hi @marindumont,

Thank you for your report.
The Github issue tracker however is only for bugs in the official code and is not used for questions (about implementations)
You're probably best of asking this question on the help forums where plenty of people can help you (see help.odoo.com).

Regards,
Yenthe
