### ISSUE TITLE
[9e, 10e]: Financial Reports Cash Basis - payment date is not taken into account

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#15993]
Impacted versions: 9e 10e

Steps to reproduce:
1. Create Invoice in December
2. Partially pay it in December
3. Pay remaining amount in Jan next year
4. Open P&L cash basis in Dec and Jan:

Current behavior:
Both payments are reporting some part of revenue in Dec.

Expected behavior:
Revenue in cash basis should be recognized in Dec and Jan
P&L in cash basis should take into account payment(reconciliation) date in same way as Cash Flow report does.

**Comment by pedrobaeza** [comment]
Is this still happening with latest code?

**Comment by lem8r** [comment]
According to commits it was fixed.

**Comment by pedrobaeza** [comment]
Thanks for following-up this. I close then.
