### ISSUE TITLE
[Youtube] How to reflect youtube subtitle translation ?

### ISSUE THREAD

**Issue by keiichiroy** [odoo/odoo#16005]
Hi, I've translated odoo manufacturing subtitle to Japanese: https://www.youtube.com/watch?v=QtIU0p8daAo

I've directly sent the strings through youtube translation UI, but I'm not sure It's right way to work.
Is there some transifex part for video subtitle or prepared workplace?

**Comment by Yenthe666** [comment]
Hi @keiichiroy,

Thank you for your bug report.
The Github tracker however is only for bugs in the official code and not the place for asking questions.
I suggest you to ask this question on the help forums (help.odoo.com) where plenty of people can help you.
Also, the translations shown on Youtube videos are managed and handled by Youtube, this has nothing to do with Odoo. The translations are also uploaded on Youtube so I'm not sure how you'd expect them to be on Transifex or anywhere else.

Regards,
Yenthe
