### ISSUE TITLE
The `data-tooltip` attribute is not translatable

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#160040]
Impacted versions: 17.0

Steps to reproduce: 
There are `data-tooltip` attributes of tags, like: `<span data-tooltip="Use this filter by default when opening this view">Default filter</span>`, where the data-tooltip should be translatable.

Current behavior: Those texts are missing from the pot file, so they are not translatable.

**Comment by vava-odoo** [comment]
Hi @tsabi 
Thanks for reporting. You're totally right, `data-tooltip` should be translatable: https://github.com/odoo/odoo/blob/17.0/odoo/tools/translate.py#L160
But for some reason, this one is not. Colleagues are on it: https://github.com/odoo/odoo/pull/162079
Cheers

**Comment by seb-odoo** [comment]
This should be resolved (see related links above).
