### ISSUE TITLE
Invoices missing headers, footers and CSS layout (i.e. are ugly). Docker Odoo v10 behind jwilder/nginx-proxy.

### ISSUE THREAD

**Issue by jpstaub** [odoo/odoo#16003]
**Impacted versions:**
Docker Odoo v10 behind jwilder/nginx-proxy.

**Steps to reproduce:**
Print PDF invoice.

**Current behavior:**
Invoices missing headers, footers and CSS layout (i.e. are ugly).

**Expected behavior:**
Invoices match preview.

**Corrective action:**
  * Activate developer mode
  * Settings >> Parameters >> System Parameters
  * Create: report.url == http://127.0.0.1:8069
![pdf report parameter](https://cloud.githubusercontent.com/assets/4706043/24225229/ba37bb20-0f35-11e7-99d9-7ec4e76edd9c.PNG)

**Comments:**
[This has been going on for quite some time](https://github.com/odoo/odoo/issues/1105). Why not fix the problem?

**Comment by Yenthe666** [comment]
@sle-odoo docker related so perhaps for you?

**Comment by LeartS** [comment]
Just encountered the same issue and solved it using these steps. Pheraps it should be reported in the https://github.com/odoo/docker project?

**Comment by Yenthe666** [comment]
@sle-odoo friendly reminder 😊

**Comment by sle-odoo** [comment]
using report.url fixes the issue, right? i guess we should just adapt the documentation

**Comment by Yenthe666** [comment]
Yeah the reminder was for updating the documentation on https://github.com/odoo/docker really 😉

**Comment by gigidn** [comment]
@sle-odoo it's partialy fix the issue, we can't set db_filter becouse it is incomplatible whit report.url, any advice how fix it??

BTW until now on v11 work fine, report.url is not necessary

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Comment by pyxise** [comment]
Hi @gdgellatly ,

I am in the case where I have 3 docker containers, 1 odoo with dbfilter, 1 nginx and 1 postgres. 
My dbs name matches my subdomains. I am having troubles to get the report print with header, footer and css.

Any clue on how to solve this please? 

Thanks.

**Comment by gdgellatly** [comment]
To test just edit /etc/hosts localhost line on the odoo instance

127.0.0.1  localhost <dbname>

Then set report url to <dbname>:8069

**Comment by pyxise** [comment]
@gdgellatly 

That worked great. Thanks a lot !

**Comment by Podridor** [comment]
You give me the live!!
Thx sooooo much.

**Comment by Podridor** [comment]
You give me the live!!
Thx sooooo much.
