### ISSUE TITLE
messaging fails with capitalization in address

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1601]
Mail sent to EMAIL@DOMAIN.COM do not get imported to messaging inbox, while email@domain.com do

**_Impacted versions:**_

 -Version 7.0-20140722-231204

**_Steps to reproduce:**_
1. Set-up email importing for email@domain.com
2. Receive email @ EMAIL@DOMAIN.COM

**_Current behavior:**_
- Message is not imported to messaging inbox

**_Expected behavior:**_
- Emails are imported regardless of capitalization

**Comment by Yenthe666** [comment]
Hi @rolandwells,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
