### ISSUE TITLE
Odoo Addon no module found module_boot

### ISSUE THREAD

**Issue by blpraveen** [odoo/odoo#160122]
I am getting an error when try to install calc addon

`module_boot` no module  in `odoo.addons.web.controllers.main`

```python
import logging
import json as simplejson
from odoo.http import Controller, route
from odoo.http import request
from odoo.addons.web.controllers.main import module_boot, login_redirect

logger = logging.getLogger(__name__)

class CalcController(Controller):
    @route('/calc/main', type='http', auth='user')
    def a(self, **kwargs):
        cr, session, context, uid = request.cr, request.session, request.context, request.uid
        modules = simplejson.dumps(module_boot(request.db))
        init = """
                var wc = new s.web.WebClient();
                wc._title_changed = function(){}
                wc.show_application = function(){
                    wc.action_manager.do_action("calc.ui");
                };
                wc.setElement($(document.body));
                wc.start();
               """

        html = request.registry.get('ir.ui.view').render(cr, session.uid, 'calc.home', {
            'modules': modules,
            'init': init,
        })
        return html
```

**Comment by praful-nexscend** [comment]
Which odoo version are you used

**Comment by blpraveen** [comment]
I am using Odoo 16

**Comment by praful-nexscend** [comment]
module_boot  not found in odoo16

**Comment by praful-nexscend** [comment]
def session_info(self):
        user = request.env.user
        version_info = odoo.service.common.exp_version()

        user_context = request.session.get_context() if request.session.uid else {}

        session_info = {
            "uid": request.session.uid,
            "is_system": user._is_system() if request.session.uid else False,
            "is_admin": user._is_admin() if request.session.uid else False,
            "user_context": request.session.get_context() if request.session.uid else {},
            "db": request.session.db,
            "server_version": version_info.get('server_version'),
            "server_version_info": version_info.get('server_version_info'),
            "name": user.name,
            "username": user.login,
            "partner_display_name": user.partner_id.display_name,
            "company_id": user.company_id.id if request.session.uid else None,  # YTI TODO: Remove this from the user context
            "partner_id": user.partner_id.id if request.session.uid and user.partner_id else None,
            "web.base.url": self.env['ir.config_parameter'].sudo().get_param('web.base.url', default=''),
        }
        if self.env.user.has_group('base.group_user'):
            # the following is only useful in the context of a webclient bootstrapping
            # but is still included in some other calls (e.g. '/web/session/authenticate')
            # to avoid access errors and unnecessary information, it is only included for users
            # with access to the backend ('internal'-type users)
            mods = module_boot()
            qweb_checksum = HomeStaticTemplateHelpers.get_qweb_templates_checksum(addons=mods, debug=request.session.debug)
            lang = user_context.get("lang")
            translation_hash = request.env['ir.translation'].get_web_translations_hash(mods, lang)
            menu_json_utf8 = json.dumps(request.env['ir.ui.menu'].load_menus(request.session.debug), default=ustr, sort_keys=True).encode()
            cache_hashes = {
                "load_menus": hashlib.sha1(menu_json_utf8).hexdigest(),
                "qweb": qweb_checksum,
                "translations": translation_hash,
            }
            session_info.update({
                # current_company should be default_company
                "user_companies": {'current_company': (user.company_id.id, user.company_id.name), 'allowed_companies': [(comp.id, comp.name) for comp in user.company_ids]},
                "currencies": self.get_currencies(),
                "show_effect": True,
                "display_switch_company_menu": user.has_group('base.group_multi_company') and len(user.company_ids) > 1,
                "cache_hashes": cache_hashes,
            })
        return session_info
