### ISSUE TITLE
[7.0] OpenERP 7 missing openerp-server.conf

### ISSUE THREAD

**Issue by faezabdulkarem** [odoo/odoo#16013]
Impacted versions:
OpenERP 7.0
Steps to reproduce:
Installation of the latest version of nightly OpenERP 7 (March 22nd)
Current behavior:
no openerp-server.conf file after installation
Expected behavior:
to have openerp-server.conf in /opt/openerp/server/

I have an ubuntu 12.04 server that is running OpenERP 7 and I would like to create an ubuntu 16.04 backup server to run the same database in case of failures
After installing the latest version of OpenERP 7 available on nightly (March 22nd) I cannot find the openerp-server.conf file. it is a mandatory file to get the server running

is the installation not complete or the installation doesn't provide the file? Should I download it from the internet? 

Note: I am new to ubuntu so if i am missing something kindly tell me

**Comment by Yenthe666** [comment]
Hi @faezabdulkarem,

Thank you for your report.
Odoo 7 is however no longer supported by Odoo, as it is too old.
Please ask this question on the official help forums (help.odoo.com), this is about implementation.

Regards,
Yenthe
