### ISSUE TITLE
 sass fails  with error  Inconsistent indentation

### ISSUE THREAD

**Issue by danielmwai** [odoo/odoo#16024]
Impacted versions:
Master
Steps to reproduce:
   Run  make  in odoo  currect  directory    

Current behavior:
 make  
sass -t expanded --compass --unix-newlines --sourcemap=none addons/website_sale/static/src/css/website_sale.sass addons/website_sale/static/src/css/website_sale.css
Error: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 4 spaces.
        on line 558 of addons/website_sale/static/src/css/website_sale.sass
  Use --trace for backtrace.
Makefile:7: recipe for target 'addons/website_sale/static/src/css/website_sale.css' failed
make: *** [addons/website_sale/static/src/css/website_sale.css] Error 65
(odoo11) [nzaniela@nzaniela odoo]$ sass -t expanded --compass --unix-newlines --sourcemap=none addons/website_sale/static/src/css/website_sale.sass addons/website_sale/static/src/css/website_sale.css
Error: Inconsistent indentation: 2 spaces were used for indentation, but the rest of the document was indented using 4 spaces.
        on line 558 of addons/website_sale/static/src/css/website_sale.sass
  Use --trace for backtrace.
(odoo11) [nzaniela@nzaniela odoo]$ subl  addons/website_sale/static/src/css/website_sale.sass

Expected behavior:
 Correct  the identicationto 4 spaces and sass  compiles fine .

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
It has been fixed a long time ago.
Thanks for reporting
