### ISSUE TITLE
VAT included in ecommerce - fiscal position

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#16022]
Impacted versions: 10, 9, 8

module: website_sale

Steps to reproduce: Set a product with 21% vat included, set customer A with a fiscal position that maps vat included to a vat 0 for instance extracommunitaire customer .
Set the price in the product file to 121  (vat included) 
Register as customer A and go to shop
If you look at the product price it takes 121 but it should take 100

Current behavior:
When the price is taken it takes directly the price without deducting the VAT. It take 121 in this case

Expected behavior:
When the price is taken it it should deduct the VAT since in the product the vat is included. It should take 100 in this case. 
Note: In sales orders it works perfect as expected. It deducts the vat first and then it applies the corresponding VAT according to de fiscal position.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be are fiscal positions applied in the website? Can you give more feedback about this one?

**Comment by JKE-be** [comment]
Fiscal position is well apply, but price unit is overrided ignoring taxes included

**Comment by jalzaga** [comment]
The problem is that it behaves differently from the backend. As an example, if you create a sales order for a product of 100€ plus 21€ vat, (121 €  vat included) for a extracommnuitaire customer, and you have y a price list with 121€ as price for it,  you get a unit price of 100€ + 0% vat and the invoice is correct. BUT if you do it in ecommerce you get a unit price of 121 € + 0% vat and the invoice is incorrect. You can try it to check.
