### ISSUE TITLE
paypal odoo 17

### ISSUE THREAD

**Issue by kochanA** [odoo/odoo#160256]
Hello, all
Impacted versions: odoo17

Steps to reproduce: try to implement paypal to odoo17 community wersion. I make all in my paypal account like it is show in odoo documentation: https://www.odoo.com/documentation/17.0/applications/finance/payment_providers/paypal.html , after that i install payPal in odoo and enter email and PDT number. Paypal payment method is set to  on and visible all seams to be good but stil new payments method is not available in my ecommerce.
<img width="322" alt="Zrzut ekranu 2024-04-2 o 22 30 33" src="https://github.com/odoo/odoo/assets/99121757/3a59e588-745e-44ea-9694-9bddee9bd7a7">

Current behavior: not show button to chose in payment method in ecomerce 

Expected behavior: display button and let customers pay with paypal method

**Comment by vava-odoo** [comment]
Hi @kochanA 
Did you have a look at https://www.odoo.com/documentation/17.0/applications/finance/payment_providers.html#payment-providers-add-new ?
Please open a support ticket for such a question and leave github issues for real bugs.
Cheers
