### ISSUE TITLE
Fixing typo in hr_leave

### ISSUE THREAD

**Issue by panzli** [odoo/odoo#160287]
There is a typo in the translation file:

https://github.com/odoo/odoo/blob/8f0154c47e872fb35e46dced2c6ee219ab46d842/addons/hr_holidays/i18n/de.po#L2802C1-L2802C62

Instead of :

`msgstr "Neue Antrag auf %(leave_type)s erstellt von %(user)s"`

it should be :

msgstr "Neuer Antrag auf %(leave_type)s erstellt von %(user)s"

an additional *r* at the and of the word `Neue` is required for a correct sentence.

**Comment by lathama** [comment]
@panzli can you update the title to have `[I18N]` at the start.

**Comment by lathama** [comment]
@panzli the process for translation corrections is at https://github.com/odoo/odoo/wiki/Translations which I guess I had not checked.

**Comment by vava-odoo** [comment]
Hi @panzli 
Thanks for reporting. I forwarded your feedback internally and it was fixed (see https://github.com/odoo/odoo/blame/17.0/addons/hr_holidays/i18n/de.po#L2802).
As @lathama suggested, translations are handled in [Transifex](https://explore.transifex.com/odoo/). Don't hesitate to contribute directly there.
Cheers
