### ISSUE TITLE
Tags "apps" is not available in registry.category("actions")

### ISSUE THREAD

**Issue by nguyenminhchien** [odoo/odoo#160293]
Impacted versions: 17.0

Steps to reproduce: i did migrate the module [intrastat_product_hscodes_import](https://github.com/OCA/intrastat-extrastat/tree/16.0/intrastat_product_hscodes_import), but face an error.

Current behavior: error message: `KeyNotFoundError: Cannot find apps in this registry!`

Expected behavior: no error message

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/8724793/fb0cc6d9-c12c-4130-8df0-b2289af74d23)

**Comment by vava-odoo** [comment]
Hi @nguyenminhchien 
This is a problem with an OCA module, not Odoo. Please report that to the OCA or use the [forum](https://www.odoo.com/forum/help-1) to get some help.
Cheers

**Comment by nguyenminhchien** [comment]
@vava-odoo , i did not explain the issue clearly enough. The issue comes from this line https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/models/res_config.py#L317
![image](https://github.com/odoo/odoo/assets/8724793/c4912ca6-c8a9-4296-9f23-011417b26536)

Because the "apps" is not found in the registry anymore.

**Comment by vava-odoo** [comment]
Right, thanks for pointing that out. I made a PR to solve this #162228
