### ISSUE TITLE
[Feature Request] Re-use Odoo Sign concept for building templates

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#16029]
Creating a template is difficult for most people as they need to have at least some basic programming knowledge and current ways limit the look of the invoices.

It would be great if users could upload a .PDF file with the desired design and in Odoo drag and drop where fields should show. This would open endless options for users to create template and efortlessly.

For the page counting it would only need a counter field.

**Comment by Yenthe666** [comment]
Hmm @mart-e can we label this wishlist or? I do like the concept but it would ask a lot of development.

**Comment by mart-e** [comment]
Yes indeed, creating templates is currently hard but we are looking to make it easier. The way we are going is to extend studio to allow the drag and drop on any view. Hopefully, reports will also be editable through studio one day.
Upload a PDF is not something that we are going to do, sorry (and by the way a PDF is not editable so not a good source for a template).

**Comment by edsersolis** [comment]
PDF is just an idea of reusing Odoo Sign but could be anything. For example
I remember that Xero uses DOC and DOCX to design the templates.

The idea is to have something more easier and intuitive to get a great
design and just use tags to put where each field is going to show.

Atentamente,


Edser G. Solís


Ingeniero en Tecnologías de la Información y Comunicación | MDETI(c)

Móvil: 829.920.2009


: : Mensaje enviado desde dispositivo móvil. : :
