### ISSUE TITLE
bcc and list traffic not imported by messaging

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1602]
Emails sent to an openerp imported email address via bcc (with another to: address), or received from a list server with similar addressing are not imported to messaging inbox

**_Impacted versions:**_

Version 7.0-20140722-231204

**_Steps to reproduce:**_
1. Receive email via bcc addressing or indirect list server

**_Current behavior:**_
- Email is not imported into messaging inbox

**_Expected behavior:**_
- Email is imported to messaging inbox

**Comment by Yenthe666** [comment]
Hi @rolandwells ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by WillyKaze** [comment]
This is still the case in Odoo 11.

Oddo tries to match the `To:` header but fails to find the correct alias set in Odoo
Maybe it could try to match the `Delivered-To:` as a fallback ?
