### ISSUE TITLE
[10.0] many2many_tags for an one2many field in a line of a form shows ID instead of name

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#16033]
**Impacted versions**: 10.0 

**Steps to reproduce**:
_Models:_
1. model: stock.picking
`address_line_id = fields.Many2one('address.line')`

2. model: address.line
```
name = fields.Char()
trip_id = fields.Many2one('trip.trip')
picking_ids = fields.One2many('stock.picking')
```

3. model: trip.trip
```
name = fields.Char()
address_line_ids = fields.One2many('address.line')
```
_Views:_
trip form view:
```
<field name="name" />
<field name="address_line_ids">
    <field name="name" />
    <field name="picking_ids" widget="many2many_tags" />
</field>
```

**Current behavior:**
The picking_ids field shows IDs.
![selection_038](https://cloud.githubusercontent.com/assets/7938973/24278312/99cacbd4-1075-11e7-80e9-efa6b1201359.png)

**Expected behavior:**
They are expected to show in tags

**Comment by leotran** [comment]
I also have the same problem but with a Many2one field. After restart the service and upgrade the module a few times, sometime it work sometime don't. I don't know why?

**Comment by pedrobaeza** [comment]
You have to define a `name_get` method for achieving what you want. Closing as no real issue.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
