### ISSUE TITLE
How to achieve high availability in Odoo 10.

### ISSUE THREAD

**Issue by CodeCraX** [odoo/odoo#16037]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @CodeCraX,

Please create an issue with a full description.
Besides, this is used for bugs in the official Odoo code, not for asking questions.
Please do this on the official forums (help.odoo.com)

Regards,
Yenthe
