### ISSUE TITLE
[10.0] can't install new module from custom addon folder without recreating the database

### ISSUE THREAD

**Issue by clavelm** [odoo/odoo#16043]
# Impacted versions:
10.0

# Steps to reproduce:
File "/home/odoo/.odoorc":
```
[options]
addons_path = /home/odoo/odoo-dev/custom-addons,/home/odoo/odoo-dev/odoo/addons
...
```
In "/home/odoo/odoo-dev/custom-addons":
```
dropdb oa
odoo-bin -d oa --db-filter ^oa$
Ctrl+C
odoo-bin scaffold oa
odoo-bin -d oa --db-filter ^oa$ -i oa
```

# Current behavior:

> WARNING oa odoo.modules.loading: invalid module names, ignored: oa

Also, oa module can't be found in app.

# Expected behavior:
oa module is installed.

If I drop the db after having created the new module folder (or renaming an existing folder), the module is found.
```
odoo-bin scaffold oa
dropdb oa
odoo-bin -d oa --db-filter ^oa$ -i oa
```

**Comment by Ahmad-Hawwash** [comment]
Hi, Any updates?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/10.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
