### ISSUE TITLE
V10 answer to field in email template is aoverriden by the catchall parameter

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#16041]
Impacted versions:
V10 Enterprise

Steps to reproduce:
Create an email template for the object you want, define the reply-to filed on this template
Use it in the object, send the mail

Current behavior:
The reply to is the catchall mail

Expected behavior:
The reply to field shoudl be the reply-to from the template

Video/Screenshot link (optional):

**Comment by vostokbike** [comment]
Confirming this.

**Comment by Yenthe666** [comment]
@tde-banana-odoo could you check? Not sure if it is desired behaviour for Odoo or not.

**Comment by pedrobaeza** [comment]
Is this still happening in latest code?

**Comment by tde-banana-odoo** [comment]
It depends on how you use the template. If you use it to post on a document it does not take the reply-to from the template. It considers you are using the template mainly for the body and recipients computation, not for redirection.

You may have a look at the "no_auto_thread" field and how it is used through the composer. It controls that behavior. By default when posting on a document it is set to False, meaning it forces replies to go on the current document.

When you are using the template in an advanced action and/or in mass mailing behavior is different and reply-to is taken from the template.

**Comment by pedrobaeza** [comment]
Then this can be considered as answered.
