### ISSUE TITLE
[17.0+e] PoS IoT device report not working

### ISSUE THREAD

**Issue by razvanioan** [odoo/odoo#160423]
Impacted versions:

- 17.0

Steps to reproduce:

- add Gift Card report (Loyalty programs) to a printer (device) attached to a configured iot box (to be automatically printed)
- enable iot on the pos
- sell a gift card

Current behavior:

- error shown
- gift card not printed
- gift card not opened as PDF to manually print

Expected behavior:

- to have gift card printed

Enterprise ticket id: 3850149

Video/Screenshot link (optional):

- here is a video with error reproduced on runbot (I've attached the report from ir.actions.report as couldn't from iot device because it's not online)

https://github.com/odoo/odoo/assets/2914226/07d9f374-b769-422c-966d-fded25ea4c9c

**Comment by razvanioan** [comment]
Apparently, the `env` parameter sent to [iotReportActionHandler](https://github.com/odoo/enterprise/blob/1720b5578998b28c91c6820a63ecbd397297c47f/iot/static/src/iot_report_action.js#L20) method doesn't have `action` service nor `iot_websocket` if it's a PoS session (and not a back-end)

**Comment by lse-odoo** [comment]
Hello @razvanioan I am from Odoo's technical support team.

I did try to reproduce your issue, but I don't have any errors. Would you mind retrying and let me know if you can still reproduce the issue ?

Regards,

**Comment by razvanioan** [comment]
Helo @lse-odoo,

I think this has been fixed already, thx
