### ISSUE TITLE
Hide footer in shopping cart

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#16058]
Is it possible to hide footer content (exc. copyright) during checkout process.

I have tried to add the following code to checkout templates but no luck

`<xpath expr="//footer" position="attributes">
        <attribute name="style">display: none;</attribute>
</xpath>`

another alternative solution might be extending 'website.layout' to new 'website_sale.layout' make these blocks visibility configurable. which might brake the general structure when installing a new module etc. 

any thoughts? 

Impacted versions:
8.0, 9.0, 10.0

Steps to reproduce:
- add a product to cart
- go to cart
- proceed to checkout

Current behavior:
Footer is visible in checkout

Expected behavior:
Footer should be invisible for buyers in order not to destruct them

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your report.
The Github tracker is however for bugs in the official Odoo code, not for asking (development) questions.
I'd suggest you to ask this question on the official help forum (odoo.com/help) where plenty of people can help you.
P.S: You could also use JS here, see on which page you are and hide the elements you want.

Regards,
Yenthe
