### ISSUE TITLE
Odoo web interface drag&drop doesn't work on Touchscreens

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#1605]
Hi:
We are testing odoo in a manufacturing company where they need using drag&drop functionality to plan orders and they had the idea of using a touchscreen. 

So, after configuring a set of simple Mo's and trying to plan on calendar view, we realized that we could not make drag&drop to move an order from one day to another. We tested also kanban view on CRM and it also did not work. 

After realizing about this issue, we tested on 2 different notebooks, one Ipad and 1 samsung android mobile phone using different browsers on then. 

We could make work drag & drop on none of them.  

On the other side, In one of the notebooks we could not use native browser (white page), nor firefox but only chrome was showing correct pages. 

Thank you:
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: The wishlist will keep popping up too!

Regards,
Yenthe
