### ISSUE TITLE
Odoo access issue (same object, two tabs)

### ISSUE THREAD

**Issue by sidwise** [odoo/odoo#16057]
Impacted versions: 8.0

Steps to reproduce: 

1. Open quotation on two different tabs within the same browser
2. Open stock and execute stock valuation
3. Change the value of the quantity and save on one tab

Current behavior:
The unit of sale quantity does not change according to the newly entered value, for instance, the UoS ratio here is  24: 
Expected behavior: 
The unit of sale quantity must be recalculated according to the UoS ratio

The same category of problem can be for other odoo models

Video/Screenshot link (optional):
![capture du 2017-03-25 11 02 01](https://cloud.githubusercontent.com/assets/4213032/24321342/8c2dfb1a-114a-11e7-992e-c2d888a7f920.png)

**Comment by Yenthe666** [comment]
Hi @sidwise,

Thank you for your report.
This isn't considered a bug though. When you do part of the operations in one tab and other parts of the operations in another tab Odoo does not know what did or did not happen. If you would refresh the tab before doing the final step, or if you would work from one tab, you wouldn't have this issue.

Regards,
Yenthe
