### ISSUE TITLE
Email Editor : Image automatically removed from content when adding a link and saving

### ISSUE THREAD

**Issue by support-skillreso** [odoo/odoo#160579]
Impacted versions: 15.0

Steps to reproduce:
- Go to Email Marketing application, and create a new Mailing.
- Choose a template that contains an image or add a block with an image.
- Select the image
- In image properties, click on the chain icon to insert a link on the image (see screenshot)
- Try to save the Mailing > The image is automatically removed.

Current behavior:
The image is automatically removed when saving after adding a link. Tested in runbot on community version and entreprise version of the branch 15.0

Expected behavior:
The image should remain in the content and not be removed.

Video/Screenshot link (optional):
<img width="305" alt="screenshot 1" src="https://github.com/odoo/odoo/assets/98042042/1bc22624-c149-4f06-9853-1d263de80a0c">
<img width="833" alt="screenshot 2" src="https://github.com/odoo/odoo/assets/98042042/facd9593-6484-468a-893e-67da954b4e9a">
<img width="834" alt="screenshot 3" src="https://github.com/odoo/odoo/assets/98042042/2317a71b-9f46-4b8a-91fc-285ae79c41ff">

Support ticket number submitted via odoo.com/help (optional):

**Comment by rdeodoo** [comment]
This should have been fixed with https://github.com/odoo/odoo/pull/160718
It was introduced with https://github.com/odoo/odoo/pull/157200
