### ISSUE TITLE
Update UBL / XRechnung for Version "3.0.1" - active since 01 Feb 2024

### ISSUE THREAD

**Issue by teha75** [odoo/odoo#160644]
Impacted versions: 16.x

Steps to reproduce: create UBL Invoice (German XRechnung) and validate it against current standard e.g. here https://erechnungsvalidator.service-bw.de/

Current behavior: For a "normal" Invoice a Warning ist shown because odoo produces a "xrechnung_2.3" XML and since Feb 2024 the "3.0.1" Version of the standard is active.

In addition it seems no longer conform that a VAT-ID is "/" which is currently used in odoo if a customer has no VAT-ID. Now a country-prefix like "DE" is expected. odoo does not allow to put just "DE" in the VAT field since it is not a valid VAT-ID.  

Expected behavior: produce fully compliant XRechnung invoices.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by teha75** [comment]
here some Details about changes in V3 (in german) - https://www.e-rechnung-bund.de/standard-xrechnung-3-0-1/

**Comment by teha75** [comment]
seems to me that you should emit the whole 

```
     <cac:PartyTaxScheme>
        <cbc:CompanyID>/</cbc:CompanyID>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:PartyTaxScheme>
```
in case of a customer without VAT-ID ("/" in VAT-ID)

and the Spec-Identifier should look like this:
  `<cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</cbc:CustomizationID>`

**Comment by teha75** [comment]
@smetl @qdp-odoo FYI

**Comment by smetl** [comment]
@JulienVR Can you have a look at this issue plz? :pray:

**Comment by JulienVR** [comment]
Hello @teha75,

Thanks for the feedback.

You're right, we will open a PR to change the CustomizationID. On the other hand, I'm not sure what should be produced for a partner without VAT. It seems that the validator accepts `<cbc:EndpointID schemeID="9930">/</cbc:EndpointID>` as well as `<cbc:EndpointID schemeID="9930">DE</cbc:EndpointID>`, but it seems hacky.
Regarding your suggestion about `PartyTaxScheme`, if it doesn't even raise a warning on the validator, I suggest not changing anything in the code.

Regards,

**Comment by JulienVR** [comment]
shouldn't we use the company registry ? Anyway, from saas-16.2, one can set the EAS and endpoint on the partner form view, so the fix for the partner without vat is only need for previous versions.

**Comment by teha75** [comment]
> Hello @teha75,
>On the other hand, I'm not sure what should be produced for a partner without VAT. It seems that the validator accepts `<cbc:EndpointID schemeID="9930">/</cbc:EndpointID>` as well as `<cbc:EndpointID schemeID="9930">DE</cbc:EndpointID>`, but it seems hacky.

For us it did raise an error: 
![image](https://github.com/odoo/odoo/assets/284139/b26b10c4-bd6b-47dd-9780-725894351324)

A country identifier is expected.

**Comment by JulienVR** [comment]
I was able to reproduce the error by filling (through the sql, because the ORM prevents it) "/" as the VAT of the partner. Since there's a VAT, we build the PartyTaxScheme with this dubious VAT and the validator complains.

You wouldn't be getting this error if the VAT was just empty (you actually only get the warning "Buyer electronic address MUST be provided, Pfad: /Invoice/cac:AccountingCustomerParty[1]/cac:Party[1]" because the Endpoint is not filled).

I am still unsure what we should fill the endpoint with in that case. If it is not blocking, we can wait until we now more. In the meantime, customers will migrate progressively to a version >= 16.2 where they are free to set the EAS and endpoint.

**Comment by JulienVR** [comment]
Updated the customizationID in https://github.com/odoo/odoo/pull/162187
