### ISSUE TITLE
[v10] how to use Odoo webservice read method to call one2many and many2many field?

### ISSUE THREAD

**Issue by hengkyz** [odoo/odoo#16070]
hi guys want to know is it possible to read (webservice) the one2many2 field?
for now its just return the list of ids, if i want to get other field how to do that instead send 2 request

**Comment by Yenthe666** [comment]
Hi @hengkyz,

Thank you for your report.
The Github issue tracker however is only for bugs, not for questions about development.
I'd suggest you to create a new question on the official help forums of Odoo, there are plenty of people who can help you there! (help.odoo.com).
Closing as this is not a bug.

Regards,
Yenthe

**Comment by hengkyz** [comment]
@Yenthe666 ok sorry wrong place,
thank you @Yenthe666 for the guidance
i did as you suggest
