### ISSUE TITLE
Make related fields act like mapped function

### ISSUE THREAD

**Issue by kmagusiak** [odoo/odoo#160851]
Impacted versions: all

Current behavior:
The current definition for `rel = field(related='x.y.z')` is to follow the first object of the relationship.
If x or y are x2many fields, then only the first x or y is taken.

Expected behavior:
`records.mapped('x.y.z') == records.rel`

**Comment by ryv-odoo** [comment]
Our current idea was to actually forbidden related field with X2many in the path.  Now it is mainly used as syntactic sugar to automatically implement a search method. IMO, if there are X2many in the related path definition, the semantic is too confusing. 

Also, mimicking the semantics of mapped changes the nature of the returned and cached values (e.g. for a related char field, which now returns a list of str, and that's weird IMO).

**Comment by kmagusiak** [comment]
> Our current idea was to actually forbidden related field with X2many in the path. Now it is mainly used as syntactic sugar to automatically implement a search method. IMO, if there are X2many in the related path definition, the semantic is too confusing.
> 
> Also, mimicking the semantics of mapped changes the nature of the returned and cached values (e.g. for a related char field, which now returns a list of str, and that's weird IMO).

Raising an error in x2many is also a good solution :)
