### ISSUE TITLE
Maximum Qty current_variants_to_create

### ISSUE THREAD

**Issue by Maralai** [odoo/odoo#160860]
See: https://github.com/odoo/odoo/blob/9c54753474b00c7ad539bba140551ac9231713db/addons/product/models/product_template.py#L663

There are many practical reasons a business may have a number of variants that exceed this limit. Setting to dynamic or none is not always an option.

I suggest moving this value to System Parameters or Inventory Settings so that the customer can determine the acceptable limit and adjust it if it is reached.

**Comment by Feyensv** [comment]
Has been fixed with #137783 for 17.0+, and we won't change that in previous versions.
