### ISSUE TITLE
opportunity with more star shows lower in Kanban

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#1608]
Both on 8.0 and master

when we have demo data loaded, show the opportunity kanban view

the more star it has, the lower it shown in same stage

IMHO it's a bug, we will star important things 4 star and leave usual things no star

Agree ?

**Comment by Yenthe666** [comment]
Hi @GoodERPJeff,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
