### ISSUE TITLE
[BUG][17.0] sale_subscription - Test "test_change_recurrence_plan_with_option" is failing

### ISSUE THREAD

**Issue by pnajman-modoolar** [odoo/odoo#160862]
Hi guys,

We've noticed that for the last 6 days test **test_change_recurrence_plan_with_option** from **sale_subscription** is failing. 
As I don't know if you guys are aware of it or not, so I'll just leave the issue here.

Below are parameters used to run the tests:
-d odoo --stop-after-init -i sale_subscription --test-tags .test_change_recurrence_plan_with_option

Odoo commits used:
CE: [a1b8cfe](https://github.com/odoo/odoo/commit/a1b8cfec431fe2393ae19719f886fb03c0a8b5e8)
EE: [6ae1046](https://github.com/odoo/enterprise/commit/6ae10468bd618e871d6d70545e8937d245f9d78b)

Error log: [unit_test_log.txt](https://github.com/odoo/odoo/files/14900368/unit_test_log.txt)

Test are failing with the latest stable commits as well ...

I've raised the issue with the support as well.
Here's the ticket number: 3855935

Kind Regards,
Petar

**Comment by jorv-odoo** [comment]
The related change that spawned this issue was reverted here https://github.com/odoo/odoo/pull/161868#event-12526261572 . Closing it as the test should not fail anymore.
