### ISSUE TITLE
[17.0] [hr_holidays] incorrect message after Confirm time off request

### ISSUE THREAD

**Issue by Bartii** [odoo/odoo#160831]
Impacted versions: 17.0

Steps to reproduce:

1. Create time off type where Approval = No Validation [leave_validation_type = no_validation]
2. log as standard user (simple employee who only can create his own requests)
3. Navigate: Time Off -> My Time -> My Time Off [view: hr_holidays.hr_leave_view_form]
4. Use "New" button to create a Time Off request
5. Set "Time Off Type" [holiday_status_id] to type created in step no. 1 
6. Button "Confirm" [action_confirm] appears because status is already set to **draft** by hr_leave._compute_state(self)

`leave.state = 'confirm' if leave.validation_type != 'no_validation' else 'draft'`

7. Use "Confirm" button. 
It will trigger hr_leave.create(self, vals_list) function where state is set to '**confirm**'. Status is changed by below code

```
# Handle no_validation
    if mapped_validation_type[leave_type_id] == 'no_validation':
        values.update({'state': 'confirm'})
```

Later, while run through the create it goes to action_validate(self)  and changes state to **'validate'**:

`self.write({'state': 'validate'})`

 code will run out of action_validate(self) with this status and after it successfully ends create (record is already saved) it triggers function action_confirm(self). In first line of this function it checks current state to raise user error:
 
```
if self.filtered(lambda holiday: holiday.state != 'draft'):
            raise UserError(_('Time off request must be in Draft state ("To Submit") in order to confirm it.'))
```

because status is already set to **'validate'** system raises user error which incorrect here

Current behavior:
When user clicks "Confirm" button for new Time Off request with Time Off Type where no validation is required, systems raises user error: "Time off request must be in Draft state ("To Submit") in order to confirm it."

Expected behavior:
No error is triggered in this case since record is correctly processed and saved.

I think the potential solution could be to not trigger status change at the beginning by hr_leave._compute_state(self), then Confirm button is not visible and standard save record will trigger full acceptance path. 
In action_confirm() there is action_validate() called but, in this scenario it was already called before in 'create' also in sudo mode. No need to call it again

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/16710874/f3447d98-a87f-4734-aa67-c59d17bde531)

Support ticket number submitted via odoo.com/help (optional): --

Thanks for your time.

**Comment by 0xSaltyHash** [comment]
I tested this issue on runbot and it seems to be a valid issue. I can work on it if no one is

**Comment by 0xSaltyHash** [comment]
btw the request is validated and saved after the UserError is raised.

**Comment by 0xSaltyHash** [comment]
The issue will affect V17 because in prior versions `action_confirm` was invisible if the record was not created in DB hence `id` id `False`. but in V17 the button will always be visible if the `state` is `draft`.

**Comment by vava-odoo** [comment]
Thanks @Bartii for reporting and @0xSaltyHash for resolving the issue
