### ISSUE TITLE
[v9c] Calendar module incorrectly display stop time

### ISSUE THREAD

**Issue by snapter** [odoo/odoo#16087]
Impacted versions: 9.0c-20170306 (Community Edition)

Steps to reproduce:
Create a meeting in your calendar and set a duration: between 00:31 to 00:37 hours

Current behavior:
Incorrectly display stop time

Expected behavior:
Show stop time correctly

Video/Screenshot link (optional): 
![capture](https://cloud.githubusercontent.com/assets/414468/24357561/4c688ca4-1328-11e7-8dc3-1a825da91703.JPG)

**Comment by Yenthe666** [comment]
Hi @snapter,

Thanks for your report.
I've just tested this without any problems? The form:
![image](https://cloud.githubusercontent.com/assets/6352350/24362435/147ab9ea-130d-11e7-9c23-3c1a1487c9bd.png)
The treeview:
![image](https://cloud.githubusercontent.com/assets/6352350/24362450/1d48f276-130d-11e7-91dd-d42a016650b7.png)

**Comment by snapter** [comment]
Hi, @Yenthe666 
Thank you for your prompt reply. It happen in the Calendar view. Could you please check if it's the same as mine or not.

Regards,

**Comment by snapter** [comment]
Hi, @Yenthe666 
Any update on this issue?

Regards,

**Comment by Yenthe666** [comment]
Hi @snapter haven't had time yet and I don't have a computer with me. Will try to check next week

**Comment by edsersolis** [comment]
Not the same but related: https://github.com/odoo/odoo/issues/16027

**Comment by Yenthe666** [comment]
Hmm there is indeed something very odd with the calendar here.
@JKE-be can you have a look perhaps?

**Comment by gustavovalverde** [comment]
There are multiples issues related to this:
https://github.com/odoo/odoo/issues/16363
https://github.com/odoo/odoo/issues/16027
https://github.com/odoo/odoo/issues/15540

This is also causing a lot of confusion with customers that rely on the Calendar to keep up with meetings, as they have to be calculating the differences manually.

**Comment by JKE-be** [comment]
@gustavovalverde 

IMHO, all bugs related to this has been fixed.
Except for model where you create datetime event on a date field.
But a patch is WIP by @nle-odoo 

Please wait this patch, pull the last code and test again.
