### ISSUE TITLE
/doc/setup/enterprise.rst does not mention web_enterprise needs to be installed as well

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#16084]
/doc/setup/enterprise.rst does not mention web_enterprise needs to be installed as well.

When a community version is ported to enterprise the `web_enterprise` module needs to be installed as well.

**Comment by Yenthe666** [comment]
Hi @daramousk,

In the meantime this has been added in the docs (at https://www.odoo.com/documentation/11.0/setup/enterprise.html)
![image](https://user-images.githubusercontent.com/6352350/34779414-66c865f2-f620-11e7-8a67-a8c365ed2b63.png)

Regards,
Yenthe
