### ISSUE TITLE
[Regression][10.0] Pricelist pricing in Product tree views

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#16094]
Impacted versions: 10.0

Steps to reproduce:

1. Go to runbot
2. Enable variants and advanced pricelists
3. Go to product variants list
4. In search bar type USD and select USD pricelist (or any other pricelist)

Current behavior:
Nothing happens (visibly)

Expected behavior:
A column should appear with the pricing

Note the error is in
```xml
<field name="price" invisible="not context.get('pricelist',False)"/>
```
removing the invisible tag and the pricing part functions as expected. 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thank you for your report.
It is a fact that nothing happens when you follow your case.
@mart-e would you agree with the change? If this is the case I'll create a PR for it.

Regards,
Yenthe

**Comment by gdgellatly** [comment]
Closing in favour of the more generalised duplicate report in #20071
