### ISSUE TITLE
Workorder could not use different prefix for multi manufacture operation

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#16091]
Impacted versions:
10.0 20170327
Steps to reproduce:
Creat another sequence for a cutting workorder and use CMO/ prefix, after JIT run, all workerorder created by prefix MO.
Current behavior:
Workorder could use only MO/ assigned by code named mrp.production, but many times we need use different prefix to identify manufacture operation between workcenter.
Steps to reproduce:
Expected behavior:

Video/Screenshot link (optional):

![qq 20170327235031](https://cloud.githubusercontent.com/assets/22065407/24366604/2f6ca42c-134c-11e7-8441-ad705dd36929.png)

**Comment by amoyaux** [comment]
Since commit ca486ebe1888ccba8afb105281a78b94212c2a17 you can define different picking type in order to use different prefix.
