### ISSUE TITLE
[7.0] Disable manual date entry

### ISSUE THREAD

**Issue by faezabdulkarem** [odoo/odoo#16102]
I understand that OpenERP 7 is outdated and no longer has any support

but as this question is important I need to ask it here
I am new to OpenERP 7 and we hired a freelancer to do some work for us

we needed the date of the entry to be limited to today, yesterday and the day before it

The freelancer did limit it though the selection but if the user types the date manually, it will still accept the entry

I mentioned to him this loophole and how it would make problems for us, but he claims that he would need to change a js file and it would be hard to accomplish

I took his word but my manager wants to confirm that I have not been tricked hence, this question

So, how possible is it to accomplish the mentioned above?

**Comment by mart-e** [comment]
Hello,

As you say, 7.0 is outdated and will not receive new patches.
Please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
