### ISSUE TITLE
[16.0 - 17.0] web: Extensions of qweb templates are not propagated to primary templates

### ISSUE THREAD

**Issue by CarlosRoca13** [odoo/odoo#161074]
Impacted versions:
At least 16.0 and 17.0

Steps to reproduce:
Havig a qweb template defined (template_1):
1. Extend it with `t-inherit_mode="extension"` (template_1_1)
2. Create a new qweb template (template_2) using template_1 and `t-inherit_mode="primary"` 

Current behavior:
The template_2 will not have the changes set on template_1 by the extension template_1_1

Expected behavior:
The template_2 has the changes set by tamplate_1_1 and the changes set by itself

Example:
Having this extension:
```
    <t
        t-name="web_refresher.ControlPanel.Regular"
        t-inherit="web.ControlPanel.Regular"
        t-inherit-mode="extension"
        owl="1"
    >
        <xpath expr="//div[hasclass('o_cp_pager')]" position="before">
            <div class="oe_cp_refresher" role="search" t-ref="refresher">
                <Refresher t-props="refresherProps" />
            </div>
        </xpath>
        <xpath expr="//div[hasclass('o_cp_bottom_right')]" position="before">
            <div
                t-if="!display['bottom-right']"
                class="o_cp_bottom_right d-flex flex-row-reverse"
            >
                <div class="oe_cp_refresher" role="search" t-ref="refresher">
                    <Refresher refresherReport="true" />
                </div>
            </div>
        </xpath>
    </t>
```
And the module project has this other for `project.task` views:
```
    <t t-name="project.ProjectControlPanel.Regular" t-inherit="web.ControlPanel.Regular" t-inherit-mode="primary" owl="1">
        <xpath expr="//t[@t-call='web.Breadcrumbs']" position="replace">
            <t t-call="project.Breadcrumbs"/>
        </xpath>
    </t>
```
When going to `project.task` views the new control panel is not getting the changes set on the main control panel:

Outside project task:
![image](https://github.com/odoo/odoo/assets/35952655/91b7df4b-7dca-4683-875a-3e767b0c2580)

Inside project task:
![image](https://github.com/odoo/odoo/assets/35952655/4d5d945c-bdf4-4690-9af5-f6c25a9cfda3)

As you can see in the first image, the new component is added but in the second one as it has t-inherit-mode="primary" is not having the changes set on the first extension

cc @Tecnativa TT48551

ping @chienandalu @sergio-teruel

**Comment by pedrobaeza** [comment]
@ged-odoo is this something expected?

**Comment by CarlosRoca13** [comment]
Please @ged-odoo, Is there any way to inherit the base template and have it applied to all those who extend from it?

**Comment by Polymorphe57** [comment]
> Please @ged-odoo, Is there any way to inherit the base template and have it applied to all those who extend from it?

You need to make your primary extension appear after the extensions (t-inherit_mode="extension") you intend to have applied on the parents. This can be achieved via a proper directive like https://www.odoo.com/documentation/17.0/developer/reference/frontend/assets.html?highlight=bundle#after

Actually, the behavior you mention is known and is sometimes useful. For instance, the settings form view is expected to inherit only from the basic template with no extensions applied  and this is obtained via the order of files in the bundle web.assets_backend.
For now, we do not plan to introduce new template attributes to control the template inheritance.

**Comment by CarlosRoca13** [comment]
Thanks a lot for your response! I will take a look
