### ISSUE TITLE
[10.0] Trivial edit of HTML template messes up Jinja2 rendering

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#16109]
Impacted versions: 10.0

Steps to reproduce: Edit a line in an email template containing a jinja % directive through Settings -> Email -> Email templates -> Pick any template -> Edit. In the wysiwyg editor, just add a letter to such a paragraph and save the template.

Current behavior: the html layout is formatted so that the jinja % directives are no longer placed after a line end. This prevents the correct rendering of the template.

Expected behavior: the whitespace layout of the template is preserved so that the jinja % directives are still preceded by a line end for correct parsing by the ninja template engine.

Video/Screenshot link (optional):

Body contents before editing:
![email_template_before](https://cloud.githubusercontent.com/assets/1033124/24404311/347ed834-13c1-11e7-970f-e52b8b9d72e2.png)

Body contents after editing
![email_template_after](https://cloud.githubusercontent.com/assets/1033124/24404310/347abe20-13c1-11e7-8d28-0f348fd64e73.png)

Resulting template preview:
![template_preview_after](https://cloud.githubusercontent.com/assets/1033124/24404312/34802d42-13c1-11e7-855d-58ae19afc81d.png)

**Comment by odony** [comment]
Jinja-aware WYSIWYG editing is a non-trivial matter, especially with the control structures in MAKO compatibility mode. In 9.0 you could modify other parts of the templates but inserting those control structures required switching to the source view of the template.

10.0 has a similar problem, and it is recommended to switch to the source code to modify templates with `% if` or `% for` control structures. (The source code toolbar button is available in dev mode).

Switching to `widget="text"` is another temporary workaround, at least while you're editing dynamic templates. But we'd rather find a way to fix the WYSIWYG editor than permanently force a text widget, though (wrt your PR).

**Comment by lem8r** [comment]
Short notice
After editing in "Source Code mode" it's required to switch back to WYSIWYG mode before saving.
