### ISSUE TITLE
Not tabbing over readonly field in odoo 12

### ISSUE THREAD

**Issue by manhkv** [odoo/odoo#161026]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by manhkhuat83** [comment]
Anyone help me please !!!

**Comment by duong77476-viindoo** [comment]
odoo 12 no longer support by odoo,cheer friend

**Comment by vava-odoo** [comment]
Sorry @manhkv but we only support the last 3 stable versions.
