### ISSUE TITLE
[15.0] [16.0] [17.0] Odoo cookie banner not accepted by Google Cookie Concent

### ISSUE THREAD

**Issue by ossimantylahti** [odoo/odoo#161106]
Impacted versions: [15.0] [16.0] [17.0]

Steps to reproduce: Install Odoo cookie bar. Expect Google cookie consent mode v2 to accept the site.

Current behavior: Google cookie consent mode v2 does not accept Odoo's cookie bar.

Expected behavior: Google cookie consent mode v2 is expected to accept Odoo's cookie bar.

Google cookie concent mode is mandatory for Google Ads and Analytics to work on Odoo hosted websites from march 2024.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by rdeodoo** [comment]
Thank you, we have ongoing discussion about that.
It might take some time but we will surely come back to you about what we decide to do.

cc @odoo/rd-website

**Comment by ossimantylahti** [comment]
Sounds good @rdeodoo . This is a real problem and right now the Cookie banner feature is not compatible with Google's cookie concent v2 requirements. The only remedy would be to purchase external service from a company like Cookiebot.

**Comment by MeetKD** [comment]
@rdeodoo Any plan to work on the issue. One of our customer is facing the same issue.

**Comment by ossimantylahti** [comment]
Confirming that the problem is still active here as well.

**Comment by janbyrtek** [comment]
We are also facing this issue. I'm not sure, if there is possibility to integrate Cookiebot solution into Odoo website?

**Comment by ossimantylahti** [comment]
Cookiebot can be used instead of Odoo’s cookie bar. However, Cookiebot is quite expensive.

Lähetetty sovelluksesta Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Lähettäjä: janbyrtek ***@***.***>
Lähetetty: Wednesday, June 26, 2024 5:47:33 PM
Vastaanottaja: odoo/odoo ***@***.***>
Kopio: Ossi Mäntylahti ***@***.***>; Author ***@***.***>
Aihe: Re: [odoo/odoo] [15.0] [16.0] [17.0] Odoo cookie banner not accepted by Google Cookie Concent (Issue #161106)


We are also facing this issue. I'm not sure, if there is possibility to integrate Cookiebot solution into Odoo website?

**Comment by rdeodoo** [comment]
Is cookiebot compliant with google consent mode v2?

Anyway, about Odoo's cookie bar, you should got some news soon from our R&D, I just made sure it's not forgotten and raised priority.

**Comment by MeetKD** [comment]
thank you for the heads up @rdeodoo

**Comment by hispeed88** [comment]
@rdeodoo 
Do you have already some news?
Yes, Cookiebot is Consent V2 compatible and they make a lot of marketing now. For a small company this is not a good solution because you have to pay for subpages. It would be nice if Odoo implements a solution at least for enterprise customer.

**Comment by qsm-odoo** [comment]
Hello :wave: 

We will soon add something about this (soon like this week or the next one). At the moment, this is targeting the next version, but we are still considering things.

I will let you know here :pray:

**Comment by qsm-odoo** [comment]
> soon like this week or the next one

I did not lie, it's Sunday 13 days later :smile: 

We now have added our solution to 16.0 and above versions. It is already available on GitHub and will soon be everywhere else. The 17.0 version is this one: https://github.com/odoo/odoo/commit/5b19c9072e0cb646874e03f8225b0a937ccbea10, notice that it will require you to update the website app, or apply the patch yourself.
It will allow you to comply to Google's policy using our cookie bar, provided you don't use third party services on your website. If you do, you have the possibility to extend the code we added to comply accordingly using custom code.

In the next version soon to be released (18.0), we improved the cookie bar possibilities with work such as https://github.com/odoo/odoo/commit/958b41c4acec7e1700ca4d6e0b25ee0ad2aac9f1. It will allow you to register any 3rd party service you could use and have the cookie bar block it accordingly and automatically comply to Google's policy. Of course, should you do more advanced things (or simply choose to not use our full cookie bar), the code is still made to be possible to extend as you may see fit.

I hope this helps. I am closing the issue, but: should you experience issues with what we implemented, tell us. We can of course bug fix / improve if possible :+1:
