### ISSUE TITLE
[Wizard interface improvement Request] Wizard save/cancel button on TOP

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#1611]
Hi,

Don't you think it could be great to have the save/cancel button on TOP instead of bottom Because when you have the chatter on the botton, you'll have to scroll a long time before finally see the save/cancel button...

**Comment by Yenthe666** [comment]
Hi @tfossoul,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
