### ISSUE TITLE
Single variant & ingle attribute  value creation in odoo 10 community create multiple products, not unlink the same products

### ISSUE THREAD

**Issue by Nikhilkrishnan0101** [odoo/odoo#16113]
Impacted versions: odoo 10

Steps to reproduce:
when we create a product in odoo10, with out any variants. and save it, after that we add a single attribute and single attribute  value, then odoo automatically create 2 variants with same name
Current behavior:
create 2 variants with same name
Expected behavior:
automatically unlink the duplicates
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Nikhilkrishnan0101,

I've just tried this but it works as expected. I did the following:
- Create a product ExampleProduct
- Save the product
- Edit the product
- Create an attribute 'Color' and set two attribute values on it (White and Black in my example)
This is the wanted & desired behaviour:
![image](https://user-images.githubusercontent.com/6352350/34779313-2064405e-f620-11e7-89fe-4441e01db45e.png)

Regards,
Yenthe

**Comment by Nikhilkrishnan0101** [comment]
Hai Yenthe.,
You create a product with out any variants. then add only one attribute with one value.
like color : red,
please try ones more for me. do not two values like red and black.

**Comment by Yenthe666** [comment]
@Nikhilkrishnan0101,

Result:
![image](https://user-images.githubusercontent.com/6352350/34813412-42b763f4-f6aa-11e7-8192-26b005a08955.png)
I don't see any issue?

**Comment by Nikhilkrishnan0101** [comment]
OK thanks, now its work fine. Thanks for your time.

**Comment by Yenthe666** [comment]
No problem, best of luck.

**Comment by devam120** [comment]
Hi @Yenthe666 ,
When I add only one product variant, it doesn't show attributes in it's variant in Odoo 15, can you please guide me.
I created a product without any variants and then added only one attribute with a value - color : Black

![Screenshot from 2023-01-07 11-18-57](https://user-images.githubusercontent.com/74402854/211133442-77ceed25-779a-4d25-945d-54b68f05c77f.png)
![Screenshot from 2023-01-07 11-19-45](https://user-images.githubusercontent.com/74402854/211133445-bbe31c42-7d19-406c-8497-e89045c02bcc.png)
