### ISSUE TITLE
[UX] Email links do not open in Odoo Mobile App

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#16115]
#### Impacted versions:
10.0-ee

#### Steps to reproduce:

- A notification is sent (eg. assignation to a Lead) by mail to my mobile fone
- I click on the link to open the related document (Lead)

#### Current behavior:

- Mobile browser opens

#### Expected behavior:

- For a seamless experience, Odoo Mobile App should open

**Comment by Yenthe666** [comment]
@adr-odoo this might be of interest for you?

**Comment by adr-odoo** [comment]
Hello,

We have already looked at doing this but many of our users are using their own domain.
It's hard to know if it's an Odoo link or not.

I know YouTube is doing something similar but the domain name is always the same.

So, sorry but we don't plan to do this.
