### ISSUE TITLE
Odoo doesn't show header- and footer-images on every page

### ISSUE THREAD

**Issue by RafNeff** [odoo/odoo#16114]
Impacted versions: 9.0

Steps to reproduce: System-requirements:
- Debian 8
- wkhtmltopdf  0.12.2.1 (as in wkhtmltox-0.12.1.2_linux-jessie-amd64.deb form 27-Feb-2015 18:04            available at http://nightly.odoo.com/extra/)
- put 10.000 more words in the view of report_purchaseorder
-print the report from the purchase module.

Current behavior: header and footer only showing on page 1, 9 and 10
[Purchase Order.pdf](https://github.com/odoo/odoo/files/875822/Purchase.Order.pdf)

Expected behavior: header and footer shown on each page

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @RafNeff ,

Thank you for your report.
While this is the case in Odoo 9 it seems to work fine in V10.
@sle-odoo perhaps you can have a look at it or give feedback on this?

Regards,
Yenthe

**Comment by RafNeff** [comment]
unfortunatelly my Company has no plans to switch to Odoo10. Is there any workaround or a known html-to-pdf-converter which is not based on wkhtmltopdf?

**Comment by Yenthe666** [comment]
Sorry for the late reply. No, there is no good alternative for wkhtmltopdf that works out of the box.
