### ISSUE TITLE
Products season

### ISSUE THREAD

**Issue by sergiocloud** [odoo/odoo#16125]
I want to organize the products in seasons but I haven't seen any way to do it. Any suggestion?

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

PS: for your question, you may look at product categories to have custom classifications
