### ISSUE TITLE
[Security] Hard-coded private key

### ISSUE THREAD

**Issue by peiyangL** [odoo/odoo#161238]
It appears that the project included a hard-coded private key. I want to know if this would pose security risk under certain conditions?

https://github.com/odoo/odoo/blob/master/addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ssl/private/nginx-cert.key

**Comment by pimodoo** [comment]
Hello, it is just a self-signed certificate that is probably outdated, so no security issues.

Thanks for repport
