### ISSUE TITLE
[9][10][graph] No way to group by date intervals other than month

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#16135]
Impacted versions:
9,10

Steps to reproduce:
1. Login to v9/10 runbot
2. Go to Sales/Report/Leads
3. In pivot view, set the close date group by quarter
![image](https://cloud.githubusercontent.com/assets/8391358/24451045/d712533e-14af-11e7-865f-92f31e82dbd7.png)
4. Change to graph view

Current behavior:
No way to group by option other than month.
![image](https://cloud.githubusercontent.com/assets/8391358/24451057/e96e3778-14af-11e7-97d8-95556d85502a.png)

Expected behavior:
The pivot view is group according to the setting in pivot view. See below version 8 screen cap.
![image](https://cloud.githubusercontent.com/assets/8391358/24450916/5aa17b90-14af-11e7-84c5-ea951ba9bf61.png)

**Comment by Guenzn** [comment]
vote up

**Comment by auyeung112002** [comment]
Any change to implement this feature in v12?

**Comment by auyeung112002** [comment]
Available in v12

**Comment by Guenzn** [comment]
Available for v10 and v11:
https://apps.odoo.com/apps/modules/11.0/sewi_web_search_group_by_date_intervals/
