### ISSUE TITLE
l10n_no: wrong tax accounts

### ISSUE THREAD

**Issue by norlinhenrik** [odoo/odoo#161396]
I just started a free accounting subscription for Norway, and I found errors in the taxes.
I downloaded [account.tax-no.csv from master](https://github.com/odoo/odoo/blob/master/addons/l10n_no/data/template/account.tax-no.csv) and did 5 corrections in the first 30 lines.

Here is the file with the corrections: [account.tax-no.csv](https://github.com/odoo/odoo/files/14936231/account.tax-no.csv)

Impacted versions: saas-17.2, master (17.0 is ok)

@mega-odoo @sovi-odoo I see that you have made PRs for accounting. Would you like to follow up this issue?

**Comment by norlinhenrik** [comment]
Please replace the phrase "average rate" with "**middle rate**". (Here is the [list](https://github.com/Skatteetaten/saf-t/blob/master/Standard%20Tax%20Codes/CSV/Standard_Tax_Codes.csv) from the tax office.)

**Comment by norlinhenrik** [comment]
**MEDIUM RATE** is better English according to what I read [here](https://hinative.com/questions/87132). And it is used 16 times [here](https://github.com/Skatteetaten/saf-t/blob/master/General%20Ledger%20Standard%20Accounts/CSV/General_Ledger_Standard_Accounts_4_character.csv) by the tax office.

**Comment by norlinhenrik** [comment]
Here is an updated file:
[account.tax-no.csv](https://github.com/odoo/odoo/files/14971219/account.tax-no.csv)

**Comment by sovi-odoo** [comment]
Thank you for your help! Could you tell me why "Services purchased from abroad [...] VAT low rate 12%" should go into the "high rate" accounts rather than the "low rate" ones and if you have any resources on this? It's my first time with Norwegian accounting so I'm probably missing something

Relevant parts of the chart of accounts:

|id       |code|name                                                    |account_type     |tag_ids|reconcile|name@nb_NO                                                           |
|---------|----|--------------------------------------------------------|-----------------|-------|---------|---------------------------------------------------------------------|
|chart2704|2704|Output VAT, purchases of services from abroad, high rate|liability_current|       |False    |Utgående merverdiavgift ved kjøp av tjenester fra utlandet, høy sats |
|chart2709|2709|Output VAT purchase of services from abroad, low rate   |liability_current|       |False    |Utgående merverdiavgift ved kjøp av tjenester fra utlandet, lav sats |
|chart2714|2714|Input VAT, purchases of services from abroad, high rate |liability_current|       |False    |Inngående merverdiavgift ved kjøp tjenester fra utlandet, høy sats   |
|chart2718|2718|Input VAT purchase of services from abroad, low rate    |liability_current|       |False    |Inngående merverdiavgift ved kjøp av tjenester fra utlandet, lav sats|

**Comment by norlinhenrik** [comment]
I see that my previous file was useless since all double-quotes were removed. 

Here is a diff file: [master-diff-account.tax-no.csv](https://github.com/odoo/odoo/files/14983717/master-diff-account.tax-no.csv)

There are 3 important changes (Compare with the accounts [here](https://github.com/odoo/odoo/blob/master/addons/l10n_no/data/template/account.account-no.csv#L274)):

- chart2710 for "1 Input VAT high rate 25%"
- chart2700 for "3 Output VAT high rate 25%" (this was correct, so no change here)
- chart2711 for "11 Input VAT medium rate 15%"
- chart2701 for "31 Output VAT medium rate 15%"

I also renamed "average" to "medium" rate.

**Comment by sovi-odoo** [comment]
>I see that my previous file was useless since all double-quotes were removed.

No don't worry! I made a tool to put them back :)

>Here is a diff file: master-diff-account.tax-no.csv

Oh I think we both misunderstood each other. I was comparing your file to the file I edited: https://github.com/odoo-dev/odoo/blob/6cd5f637fc90591c63b7922a6859a0c0dc5a0341/addons/l10n_no/data/template/account.tax-no.csv

Here's the diff:

```diff
--- norlinhenrik-account.tax-no.csv   2024-04-16 09:37:04.170658989 +0200
+++ sovi-account.tax-no.csv           2024-04-11 15:46:57.459855446 +0200
@@ -110,15 +110,15 @@
 "","","","","","","","","","base","refund","","","-87 Base","",""
 "","","","","","","","","","tax","refund","chart2714","","-87 Tax","",""
 "tax27","12% EX S D","","88 Services purchased from abroad with deduction for VAT low rate 12%","Services purchased from abroad with deduction of VAT","12.0","percent","purchase","tax_group_12","base","invoice","","","+88 Base","88 Tjenester kjøpt fra utlandet med fradrag for mva lav sats 12%","Tjenester kjøpt fra utlandet med fradrag for mva"
-"","","","","","","","","","tax","invoice","chart2714","","+88 Tax","",""
-"","","","","","","","","","tax","invoice","chart2704","-100","+88 Tax","",""
+"","","","","","","","","","tax","invoice","chart2718","","+88 Tax","",""
+"","","","","","","","","","tax","invoice","chart2709","-100","+88 Tax","",""
 "","","","","","","","","","base","refund","","","-88 Base","",""
-"","","","","","","","","","tax","refund","chart2714","","-88 Tax","",""
-"","","","","","","","","","tax","refund","chart2704","-100","-88 Tax","",""
+"","","","","","","","","","tax","refund","chart2718","","-88 Tax","",""
+"","","","","","","","","","tax","refund","chart2709","-100","-88 Tax","",""
 "tax28","12% EX S ND","","89 Services purchased from abroad without deduction for VAT low rate 12%","Services purchased from abroad without VAT deduction","12.0","percent","purchase","tax_group_12","base","invoice","","","+89 Base","89 Tjenester kjøpt fra utlandet uten fradrag for mva lav sats 12%","Tjenester kjøpt fra utlandet uten fradrag for mva"
-"","","","","","","","","","tax","invoice","chart2714","","+89 Tax","",""
+"","","","","","","","","","tax","invoice","chart2718","","+89 Tax","",""
 "","","","","","","","","","base","refund","","","-89 Base","",""
-"","","","","","","","","","tax","refund","chart2714","","-89 Tax","",""
+"","","","","","","","","","tax","refund","chart2718","","-89 Tax","",""
 "tax29","25% C G D","","91 Purchase of carbon quotas or gold with deduction for VAT high rate 25%","Purchase of climate quotas or gold with VAT deduction","25.0","percent","purchase","tax_group_25","base","invoice","","","+91 Base","91 Kjøp av klimakvoter eller gull med fradrag for mva høy sats 25%","Kjøp av klimakvoter eller gull med fradrag for mva"
 "","","","","","","","","","tax","invoice","chart2715","","+91 Tax","",""
 "","","","","","","","","","tax","invoice","chart2700","-100","+91 Tax","",""
```

We agree on pretty much everything except for the handling of "Services purchased from abroad [...] VAT low rate 12%". In my case, I think this should logically go into the "low rate" accounts (`chart2718` & `chart2709`) but in your CSV this goes into the "high rate" accounts (`chart2714` & `chart2704`)

By the way, this is how these accounts are defined in the chart of account:

|id       |code|name                                                    |name@nb_NO                                                           |
|---------|----|--------------------------------------------------------|---------------------------------------------------------------------|
|chart2704|2704|Output VAT, purchases of services from abroad, high rate|Utgående merverdiavgift ved kjøp av tjenester fra utlandet, høy sats |
|chart2709|2709|Output VAT purchase of services from abroad, low rate   |Utgående merverdiavgift ved kjøp av tjenester fra utlandet, lav sats |
|chart2714|2714|Input VAT, purchases of services from abroad, high rate |Inngående merverdiavgift ved kjøp tjenester fra utlandet, høy sats   |
|chart2718|2718|Input VAT purchase of services from abroad, low rate    |Inngående merverdiavgift ved kjøp av tjenester fra utlandet, lav sats|

Was this on purpose meaning `chart2718` & `chart2709` should not be used here or was it just a misunderstanding?

**Comment by norlinhenrik** [comment]
Yes I agree with you, account 2709 and 2718 should be used for services purchased from abroad with low rate 12%.

---

I just tested tax codes WITHOUT deduction for import VAT, and I think they are all wrong.

1) WITH deduction, there are 2 tax lines, e.g. Input (chart2718) and Output (-100 chart2709). 
WITHOUT deduction there should be only the Output line (not the Input line).
So the last part of the diff above should replace twice (chart2714) with (-100 chart2709).

2) WITHOUT deduction, the VAT should add to the cost, not to the supplier bill.
E.g. supplier bill 1000 NOK without VAT. Adding "12% EX S ND" to the invoice line should give this result:
Kr 1120 Untaxed amount
Kr -120 VAT*
Kr 1000 Total.
*"In most cases, you must pay VAT when you import goods into Norway. If you are registered in the VAT Register, you must calculate the VAT yourself." [Reference](https://www.skatteetaten.no/en/business-and-organisation/vat-and-duties/abroad/goods/) [This also applies for services.](https://www.skatteetaten.no/en/business-and-organisation/vat-and-duties/vat/foreign/value-added-tax-vat-on-services-the-enterprise-has-purchased-from-other-countries/?277083=277102)

**Comment by sovi-odoo** [comment]
Sorry for the delay. The "without deduction" lines are definitely fishy, thank you for telling us!

>WITHOUT deduction there should be only the Output line (not the Input line).

After talking with some colleagues, to make it truly nondeductible, it'd apparently be better to register these taxes as part of the product's cost. Meaning the taxes would go into the same account as the one specified for the product. Of course, they'd still appear in the tax report properly

Would you be okay with that?

>Kr 1120 Untaxed amount
>Kr -120 VAT*
>Kr 1000 Total.

Odoo doesn't do these calculations. After asking around, it's apparently because customs will often tax your products under a base price different from the one you paid

I believe what they did in the Spanish localization is a special tax that will remove the product's base price and only leave the VAT. That way, users can invoice the customs for whatever base price and get their product's VAT back

**Comment by norlinhenrik** [comment]
> I believe what they did in the Spanish localization is a special tax that will remove the product's base price and only leave the VAT. That way, users can invoice the customs for whatever base price and get their product's VAT back

I see that this is how it is also implemented in the Norwegian localization. So this is good for products, except we need to update the rules WITHOUT tax deduction.

For **REMOTE DELIVERABLE SERVICES** ("fjernleverbare tjenester"), the normal procedure is to handle the tax with a tax code on the invoice line. Please encourage Odoo to find a way to do this. Meanwhile, I suggest to handle these services "the same way" as the products:

Kr 1000 invoice line
Kr   120 invoice line **with a tax code**
Kr  -120 computed outgoing VAT
Kr 1000 Total

**Comment by sovi-odoo** [comment]
Oh, in that case you can already do that with fiscal positions:

![Bill Intra-Europe](https://github.com/odoo/odoo/assets/163829053/c4e8ae1a-4ac5-4651-8458-09777e26fdcb)

You can get that by going to one of your partner's page (client/supplier/etc.), then click on the "Sales & Purchases" tab and then set "Fiscal Position" to whatever is appropriate. Then, everything that you create for that partner (be it bills/invoices/etc.) should have the products' default taxes replaced by the proper taxes. Would that solve this issue?

**Comment by norlinhenrik** [comment]
The example above seems to have both output and input VAT. Our question (in regards to import of remote deliverable services without vat deduction, saf-t codes 87 and 89) is how to handle the case where there is only output VAT - and this VAT should be added to the cost.

A) Odoo could make a new VAT feature for this.

B) Configure "input VAT" with a cost account and no VAT reporting (the first of the two csv lines below). Technically this would work in regards to both accounting and VAT reporting. But (assuming 1000 cost + 120 vat cost, saf-t code 89): 
* The 120 would come on a fixed cost account. I suggest account `chart7798` "Other expenses, deductible".
* The Invoice Lines Summary would show 1000 untaxed, and 0 tax, when it is really 1120 untaxed, and -120 tax. But the Journal Items would show that everything is correct (except the 120 is not on the same cost account as the 1000).
```
"","","","","","","","","","tax","invoice","chart7798","","","",""
"","","","","","","","","","tax","invoice","chart2709","-100","+89 Tax","",""
```

C) The accountant could make 2 invoice lines (12% VAT: 1000 kr with no vat code, 120 kr with vat code 89). The accountant wouldn't expect to do this, therefore I think option B) is better, even though option C) is more flexible for the cost account.

**Comment by chklop** [comment]
@norlinhenrik We're trying to follow here but we are probably missing the point. Are we talking about non-EU Import cases where you have:
- on one hand, an invoice without VAT (let's say 1000kr)
- on the second hand, a pure "VAT invoice" coming from the customs, with the VAT amount not always being calculated based on the first invoice, but on an amount determined by the customs ? (let's say 25% on 1250kr evaluated by customs, so 312,5kr).

If that's the use case we're discussing, for now, we usually don't include how to tackle that in our base localisation package, but it can be done using specific taxes that are groups removing the base amount.

So for the first invoice, you just do this, registering the invoice with no tax:
![image](https://github.com/odoo/odoo/assets/93644924/811e1bb2-98cc-46d7-a977-27841a3c01da)

Then, for the second "VAT invoice", you specify first a grouped tax that removes the base:
Import Tax config:
![image](https://github.com/odoo/odoo/assets/93644924/93e68dae-f898-4e46-8a60-577090ba1f52)
Remove base tax config:
![image](https://github.com/odoo/odoo/assets/93644924/d2e4976a-32cd-44ac-ad13-e3011217e324)
Result on the Customs Invoice:
![image](https://github.com/odoo/odoo/assets/93644924/f1bfe1c1-2f25-43ee-8e0c-c17a7a8f98fc)
![image](https://github.com/odoo/odoo/assets/93644924/5902cb2f-3258-401a-b829-99d985dea7c5)

Is that what you're looking for ?

**Comment by norlinhenrik** [comment]
![image](https://github.com/odoo/odoo/assets/11876900/3a43e525-b876-4efd-bfc1-a06f029dc24f)
I was not aware of the possibility to show "Remove base". I like this.

Norway is not in the EU. For `"remote deliverable **services**"`, there is no _pure "VAT invoice" coming from the customs_. The accountant is the only person dealing with the VAT. So the optimal solution is to handle all the VAT on one invoice line with one account.tax configuration.
* When there is both output and input VAT, Odoo may handle this well.
* When there is only output VAT, Odoo may handle this fairly well. But the VAT will be an extra cost, and the account.tax configuration will hard code the cost account. The optimal solution would be not to hard code this, but to add it to the cost account of the invoice line.

**Comment by norlinhenrik** [comment]
Very close. Importing services with 12% VAT without deduction with tax rule [89](https://github.com/odoo/odoo/blob/master/addons/l10n_no/data/template/account.tax-no.csv#L118), there should be output VAT `chart2709` with credit amount, and `chart4000` debit amount **adding** to the cost.

86 Services purchased from abroad with deduction for VAT high rate 25%: `chart2704` and `chart2714`
87 Services purchased from abroad without deduction for VAT high rate 25%: `chart2704`
88 Services purchased from abroad with deduction for VAT low rate 12%: `chart2709` and `chart2718`
89 Services purchased from abroad without deduction for VAT low rate 12%: `chart2709`

**Comment by sovi-odoo** [comment]
I think I've understood this time. Here's how it looks like now:

![Norway Fixed](https://github.com/odoo/odoo/assets/163829053/fa187cca-f3db-4b01-8e8d-dd69dbd04889)

Is that okay?

(New corrected file: https://github.com/odoo-dev/odoo/blob/5aa2ea0cb38d89e738e6484e6c17a7664c4d9171/addons/l10n_no/data/template/account.tax-no.csv)

**Comment by norlinhenrik** [comment]
The tax grid `+89 Tax` should be removed from the expense account. The rest is good.

I looked in the corrected file, and the same goes for rule 82, 84, 87 and 89.

**Comment by sovi-odoo** [comment]
Done! https://github.com/odoo-dev/odoo/blob/6bcf0abfda169a92bc6bab7365bb2c1073622f4b/addons/l10n_no/data/template/account.tax-no.csv :)

I've also added you as a co-author to these changes. Thanks a lot for your help!
