### ISSUE TITLE
Closing POS sessions with open orders needs to be handled

### ISSUE THREAD

**Issue by multiwebinc** [odoo/odoo#16151]
**Impacted versions:** 10

**Steps to reproduce:** 

- Open a POS session and add an order with a few items on it, but don't submit a payment for that order.
- Exit, close and validate/post the POS session
- Open another POS session

**Current behavior:**

The unpaid order vanished into Never Never Land, never to be found again.

**Expected behavior:**

Either an error should be displayed when trying to close a session with outstanding orders, or any open orders should be automatically moved to the next open session. If I had the choice, I would much prefer the second option, plus a warning message when closing the session.

**Comment by Yenthe666** [comment]
@jorenvo this looks like one for you.

**Comment by jorenvo** [comment]
Could you explain the use case in which this would happen? Normally in a shop people pay their order immediately after it is created. Normally in a restaurant you wouldn't close the session while there are still customers in your restaurant.

**Comment by multiwebinc** [comment]
Some restaurants have multiple shifts per day. A customer could place an order during the first shift and pay on the second shift. We use a separate session for each shift to keep track of overs and shorts in the till.

**Comment by setterlee** [comment]
Maybe this is very important not Only for shifts, if there is a unexpected power cut on the restaurant at the middle of the Day? where is the all orders? only in papers printed at the kitchen? very very scary :S

**Comment by setterlee** [comment]
This is very important not only for the shifts. If there is an unexpected power cut? Where is the all Order? printed on the kitchen full of grease? LOL. I'm using the odoo 9, I'll be to glad if the Solutions is implemented in that versión too please!!!

**Comment by jorenvo** [comment]
@setterlee If there is a power cut your orders would be fine. You would open the POS again by clicking on 'Resume session' and all open orders would be there. This issue is about open orders being discarded when someone closes the POS session.

**Comment by fsalomon** [comment]
Version 12.0 has the same issue. 

I would like to add that allowing a session to close without paying all orders would leave an opportunity for employee fraud. E.g. restaurant staff create order, send order to kitchen, collect cash from customer, close session without payment, staff keeps the cash. Usually restaurants that want to prevent employee fraud implement a "no item shall be produced in the kitchen without a printed order" policy. This software flaw makes such a policy ineffectual. Correct me if I'm wrong.

**Comment by switch87** [comment]
@setterlee 
The loss of open orders whit a power outage could be because the open orders are stored in local storage of the browser and not on the Odoo server. To solve this a change in workflow should be implemented and therefore it cannot be implemented in Odoo stable. I do think there are free extensions that solve this problem though for community and .sh users. For instance the multisession addon by it project llc adds instant synchronisation with the server: https://github.com/it-projects-llc/pos-addons/tree/12.0/pos_multi_session please note that I point to this addon without testing it myself, so it could not do the trick at all. On the field, I also always recommend to place a ups power backup before your PoS installation, a good one protects not only against power outages, but also against other irregularities in the supply.

**Comment by switch87** [comment]
@multiwebinc thank you for reporting this issue, I did a pull request to fix it. #29574

**Comment by hamzaaboufirass** [comment]
@switch87 For some reason I am still losing orders and they are not being pushed to new pos session. Was the fix pushed to the 12.0 branch or not yet? Thanks for all your help!

**Comment by switch87** [comment]
@hamzaaboufirass The pr for 12.0 is still being reviewed (see the reference higher in this threat). At the moment Odoo does not support this use-case, all orders should be closed in their original session.

**Comment by switch87** [comment]
the issue will only be fixed in master, but it can easily be cherry-picked on own branches in older versions.
https://github.com/odoo/odoo/pull/33395
