### ISSUE TITLE
[8.0] quant cost is different than price of purchase

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#16153]
Impacted versions:
8.0

Steps to reproduce:
1,create new tax with tax include in price, and name called  17%
2,create test product with average costing method
3,create purchase order to buy 40 pce test product, with purchase price 5.99 [ untax price should be 
![image](https://cloud.githubusercontent.com/assets/1404460/24485405/d7502d44-1536-11e7-8f6b-8f69f7539054.png) ]
4, confirm the purchase order, and received the product.
5, check the stock move and quant, found that the cost of quant is  5.12, and price unit of stock move is 5.12  too,  the cost should be  5.12 * 40 = 204.800

6, create  invoice base received product quantity, the invoice should be 204.786 

Current behavior:

the cost of inventory is different than invoice..

Expected behavior:

should be the same value.

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
debug the tax computation, found that the existing error

 +++++ tax is {'total': 5.12, 'taxes': [{'ref_base_code_id': False, 'ref_base_sign': 1.0, 'name': u'\u589e\u503c\u7a0e17%\u8fdb\u9879\u7a0e', 'ref_tax_code_id': False, 'account_collected_id': 49, 'price_unit': 5.119658119658119, 'sequence': 1, 'account_analytic_collected_id': False, 'base_code_id': False, 'base_sign': 1.0, 'amount': 0.87, 'account_analytic_paid_id': False, 'tax_code_id': False, 'tax_sign': 1.0, 'ref_tax_sign': 1.0, 'todo': 0, 'id': 2, 'account_paid_id': 49}], 'total_included': 5.99}

tax precision should follow the `account`. so if `account` digits is 3, then `total` of tax should be the same as  3

**Comment by Yenthe666** [comment]
Hi @jeffery9 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
