### ISSUE TITLE
Cannot edit mass mailing templates after they have been created if user is not in en_US context

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#16165]
Impacted versions: 9, did not try 10

Steps to reproduce:

1. Set your user's lang to Spanish.
2. Create a mass mailing template.
3. Save it.
4. Edit it again.
5. Change something in edit mode (english).
6. Save.

Current behavior:

- Changes saved to Spanish version of the template.
- Changes not saved to any other version (including English, which is the one I was editing).
- Cannot use updated template because when creating a mass mailing, templates are always used in English.

Expected behavior:

- Changes saved in English.
- Missing parts added to Spanish (and other languages) version.

  (This is actually not really a requirement, since it is supposed that those templates cannot be translated, and if they were, cannot be used translated, as per https://github.com/odoo/odoo/pull/15583.)
- Able to use the new template for a new mass mailing.

Video/Screenshot link (optional):
[Screencast_30-03-17_14:35:17.zip](https://github.com/odoo/odoo/files/882295/Screencast_30-03-17_14.35.17.zip)

@Tecnativa @nle-odoo https://github.com/odoo/odoo/issues/15622

**Comment by nle-odoo** [comment]
I don't see an easy way to fix this.

If we change the language on the action (with `'lang': 'en_US'` in window action context), the interface would be in english, if we change the widget to `html` we lose the snippets :thinking:

The issue happen because we use the widget `html_frame` for a incompatible field (with `translate=True` instead of `translate=html_translate`).

If we want to keep the snippets the only way I currently see is disabling the edition if the user is not in english (but I'm not sure how to do this in form view) :confused:

**Comment by Yajo** [comment]
I think the main problem here is that this model is used for 2 different purposes:

1. General email templates, where translations are desired because they get shipped by addons.
2. Mass mailing templates, where translations are not desired because they create a lot of problems.

Maybe, for master, one solution would be to use different models for each purpose. Or maybe the fix is what you say about `translate=html_translate`, but this is something undocumented that I don't really know what it does... 🤔 

But for stable versions I'm thinking on adding a context to the action (like `mass_mailing=True`) and overloading the `write()` method to force him to write in `en_US` context and then remove all translations if `self.env.context["mass_mailing"] == True`.

What do you think?

**Comment by nle-odoo** [comment]
> Maybe, for master, one solution would be to use different models for each purpose. Or maybe the fix is what you say about translate=html_translate, but this is something undocumented that I don't really know what it does... :thinking:

From what I see in 10.0 `mail.template` are not used (the templates are added directly by qweb template inheritances). 

> But for stable versions I'm thinking on adding a context to the action (like mass_mailing=True) and overloading the write() method to force him to write in en_US context and then remove all translations if self.env.context["mass_mailing"] == True.

Yes, I did not want to change `mail.template` but I don't see a better way.

**Comment by Yajo** [comment]
Ah sorry, still not tested v10 much, I thought it was the same.
Then at least for v9 we need a fix, otherwise this feature is simply not usable. 😞

**Comment by nle-odoo** [comment]
I have a PR with the change there: https://github.com/odoo/odoo/pull/16255

**Comment by nle-odoo** [comment]
PR #16255 where there is been some discussions has been merged.
