### ISSUE TITLE
[10.0] Admin's Access Rights Page is not correclty rendered with xml developer mode enabled

### ISSUE THREAD

**Issue by jbofill** [odoo/odoo#16179]
Impacted versions: 10.0 (Community Edition) 

Steps to reproduce:

1) Start instance with xml developer mode enable, or all enabled.
odoo-bin --dev=xml
odoo-bin --dev=all

2) Create database

Current behavior: Admin's Access Rights Page is not correclty rendered

![incorrect-view](https://cloud.githubusercontent.com/assets/1204089/24546678/adf4471a-160c-11e7-885b-8156d413a6aa.png)

Expected behavior: Admin's Access Rights Page  correctly rendered

![correct-view](https://cloud.githubusercontent.com/assets/1204089/24546685/b53f0fa0-160c-11e7-9b2a-a180c929b655.png)

**Comment by JKE-be** [comment]
Thanks for the reporting...
It has been fixed in 9.0, it shoul dbe fwported to 10 in a few days...
