### ISSUE TITLE
Add links to 17 on `Translating Odoo` wiki page.

### ISSUE THREAD

**Issue by lathama** [odoo/odoo#161769]
## Impacted versions:

- https://github.com/odoo/odoo/wiki/Translations/27beb903220455f4dc914d196da6c6d4aefec7be

## Steps to reproduce:

Visit https://github.com/odoo/odoo/wiki/Translations and notice there are no links to Odoo 17 

## Current behavior:

Showing the Transifex links for Odoo 14, 15, and 16

## Expected behavior:

See links for:
- https://explore.transifex.com/odoo/odoo-17/
- https://explore.transifex.com/odoo/odoo-17-doc/

## Video/Screenshot link (optional):

- NA

## Support ticket number submitted via odoo.com/help (optional):

- NA

## Other notes

- I looked and could not find how to do a PR for a wiki page.
- @mart-e was the last editor of the wiki page so that may help.

**Comment by lathama** [comment]
@mart-e as the last editor is this something you can do?

**Comment by mart-e** [comment]
Thanks, I have just addede the links to 17 :+1: 
cc @oomsveta
