### ISSUE TITLE
issue in upload file: entreprise 9.0

### ISSUE THREAD

**Issue by esmairi** [odoo/odoo#16177]
Impacted versions: entreprise 9.0

Steps to reproduce: upload file then clear this file then upload the same file

Current behavior: the upload didn't happen

Expected behavior: the file must be uploaded and the current view must change

Video/Screenshot link (optional):  it seems the problem is in FieldBinary widget located in "enterprise/web/static/src/js/views/form_widgets.js"

**Comment by Yenthe666** [comment]
Hi @esmairi,

Thank you for your report.
I've just tested this on the latest Odoo 9.0 (ENT) and can no longer reproduce this issue.
If you can still reproduce this on the latest Odoo source code, or on a runbot, please let me know with the steps you've done and I'll reopen this.
Closing this report as it seems fixed.

Regards,
Yenthe

**Comment by esmairi** [comment]
Hi @Yenthe666 

As i said before, the senario is:
In the form view of attachment:
upload a file then deleted then upload the same file. 
you can look at this video: https://youtu.be/i3ogcDSPiqQ

Regards,
Esmairi
