### ISSUE TITLE
Odoo goes in infinite loop with App Switcher as home action of user

### ISSUE THREAD

**Issue by purnendu03** [odoo/odoo#16180]
Impacted versions:
Version 10 Community and Enterprise.
May be same with 9 Community and Enterprise

Steps to reproduce:
Activate developer mode.
Open any user
assign 'App Switcher' in his home action.

![app_switcher](https://cloud.githubusercontent.com/assets/7599739/24547890/bb2e38dc-162f-11e7-95b4-d901aeefd882.png)

Current behavior:

See the magic. System goes in loop and keep reloading

Expected behavior:

It Should open the app view for at least in enterprise as app switcher may not be available for community version

Video/Screenshot link (optional):

**Comment by Mohamed-Alaa** [comment]
The Same Issue with me and I need help please.

**Comment by Yenthe666** [comment]
Hi @purnendu03,

Thank you for your bug report.
I've just tested this and I can reproduce this on V10 too. On V11 the behaviour is even worse as the whole UI is blocked so there is no way of getting out of it:
![image](https://user-images.githubusercontent.com/6352350/34097049-ef88b99c-e3d7-11e7-880c-4d0a61491f72.png)
I've made an enterprise ticket for this. 
OPW 800323

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @purnendu03,

The bug has been fixed in https://github.com/odoo/odoo/commit/2aa3132d09656f90520aaa89fdb0220823c3bd46 - it will be soon forward to 11.0 so it is fixed there too!

Regards,
Yenthe
