### ISSUE TITLE
[v10] Public, Template and Default Users shouldn't show within archived contacts

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#16198]
Impacted versions: v10

Steps to reproduce:
Apply filter to contacts to see archived ones. (Archived)

Current behavior:
Public, Template and Default users show.

Expected behavior:
Public, Template and Default users shouldn't show. At least not for non-power users, as these currently are able to change the information on those contacts and may affect their behavior.

Could be fixed with a Record Rule.

**Comment by edsersolis** [comment]
@odony @JKE-be could you guys please take a look at this?

**Comment by Yenthe666** [comment]
Hmm not sure if this is really a big issue though.. @mart-e is probably the best to give feedback on this.
P.S: (@)odony is not really the person to ping in these ones - he is really busy and is only for core bugs.

**Comment by mart-e** [comment]
Hello,

Sorry but I disagree. The public and template _are_ archived users. They are not active, meaning you can not use them as regular user to log in but they do exists.
