### ISSUE TITLE
[17] account: Wrong currency conversion

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#161998]
Impacted versions:
17

Steps to reproduce:
In shell, enter the following commands:

```
>>> USD = self.env.ref('base.USD')
>>> EUR = self.env.ref('base.EUR')
>>> EUR.write({'rate_ids': [(0, 0, {'name': '2024-01-01', 'rate': 1.2})]})
True
>>> (USD + EUR).rate_ids  # Confirm that only 1 rate exists
res.currency.rate(5,)
>>> EUR.rate_string
'1 USD = 0.833333 EUR'
>>> USD._convert(1, to_currency=EUR)
1.2
```

Current behavior:
res.currency._convert return correct result
res.currency.rate is inversed compared to version 16.0
res.currency.rate_string is wrong

**Comment by ray-odoo** [comment]
Fixed in https://github.com/odoo/odoo/pull/160882
