### ISSUE TITLE
Odoo 9 onchange one2many field value data loss after parent record edit

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#16195]
Impacted versions:
Odoo Version 9

Steps to reproduce:
Custom Module One2many (kanban view) field  auto fill applied. 
Its working fine after auto fill One2many field value and save record. 
Issue after auto fill One2many field value and edit parent field value and save record.

Current behavior:
 The below issue shows after edit parent field value and click one2many form:-
Uncaught Error: Qweb -template['kanban-box'] Runtime Error

Based on these issue openerp\fields.py file below changes applied:
 
def convert_to_onchange(self, value, fnames=None):
        fnames = set(fnames or ())
        fnames.discard(self.inverse_name)
        return super(One2many, self).convert_to_onchange(value, fnames)

 The above changes fixed error but one2many data value loss.

 def convert_to_onchange(self, value, fnames=None):
        fnames = set(fnames or value.fields_view_get()['fields'])        
        fnames.discard(self.inverse_name)
        return super(One2many, self).convert_to_onchange(value, fnames)

 The above changes sometimes error fixed and save record without  one2many value data loss.
Sometimes facing error DataError: invalid input syntax for integer: "{'record_id': [6,'test']}"
"record_id" many2one field try to insert list of values instead of id.
Expected behavior:
How to fix about issue? What are the changes apply in web core module?
Video/Screenshot link (optional):

**Comment by prakashjain** [comment]
I overridden create method and many2one field value passed id instead of list of value.  "{'record_id': [6,'test']}" and fixed issue.

And  openerp\fields.py file below changes applied:
def convert_to_onchange(self, value, fnames=None):
    fnames = set(fnames or value.fields_view_get()['fields'])
    fnames.discard(self.inverse_name)
    return super(One2many, self).convert_to_onchange(value, fnames)

I would like know if any other possible solutions and want to confirm the above changes will not give any other issue.

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported I'm closing this issue.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe
