### ISSUE TITLE
[v10c] Custom filter view is not scrollable

### ISSUE THREAD

**Issue by Troublicious** [odoo/odoo#16219]
Impacted versions: 10 community

Steps to reproduce: anywhere, go in "Advanced search" and try to add more filters than your screen resolution can handle

Current behavior: filters are out of screen, no scrolling bar appears and mouse wheel is useless (only keyboard with tab or down arrow)

Expected behavior: in other version (v9c, v10e) you can scroll with mouse wheel and add as many filters as you want

Video/Screenshot link (optional):
In v10c, no scrolling bar and new filters are out of screen:
![filter scroll bug v10](https://cloud.githubusercontent.com/assets/2540295/24616282/f02fe1c6-1890-11e7-96c3-1c052e0f53d5.png)

In v9c, you can scroll easily to add as many filters as wanted:
![filter scroll bug v9](https://cloud.githubusercontent.com/assets/2540295/24616281/f02d0cb2-1890-11e7-8aca-b4c5523fb9a4.png)

**Comment by Troublicious** [comment]
Thank you auyeung112002, it works perfectly =)

**Comment by auyeung112002** [comment]
Created another PR https://github.com/auyeung112002/odoo/pull/4

**Comment by Yenthe666** [comment]
Handled in https://github.com/odoo/odoo/commit/d847a664157738fe896dc5636977489f2da2a7ff
