### ISSUE TITLE
Hi, i got error "The company hierarchy cannot be changed" when i try to set parent company for sub company

### ISSUE THREAD

**Issue by DaoThang3797** [odoo/odoo#162192]
I got error "The company hierarchy cannot be changed" when I try to set the parent company for a sub company

ref code: base/model/res_company.py
![image](https://github.com/odoo/odoo/assets/37305734/b7f73f2d-a0f4-4450-932c-a77d0e8d8230)
![image](https://github.com/odoo/odoo/assets/37305734/08489516-3576-46bc-8d86-a014eabc86d5)

https://github.com/odoo/odoo/blob/07f6d71e4dd3fac7b4cacc545819430aa48823cd/odoo/addons/base/models/res_company.py#L303
![image](https://github.com/odoo/odoo/assets/37305734/2e0dbd54-973d-425c-ae6d-4470583ceb1d)

Anyone can explain the purpose of this code.
Setup parent company still works in other versions, 14,15,16 , but only 17 we can do that

**Comment by lathama** [comment]
I was able to reproduce this.

Maybe related  https://github.com/odoo/odoo/issues/86237

**Comment by DaoThang3797** [comment]
Hi @lathama , please check my video reproduce this 
<iframe title="vimeo-player" src="https://player.vimeo.com/video/936335983?h=8ec0bd2e52" width="640" height="360" frameborder="0"    allowfullscreen></iframe>

**Comment by DaoThang3797** [comment]
Hi Andrew Latham

I just updated video for reproduce this here
https://github.com/odoo/odoo/issues/162192#issuecomment-2064412809
Please review it
Thanks!

Vào Th 5, 18 thg 4, 2024 vào lúc 01:47 Andrew Latham <
***@***.***> đã viết:

**Comment by lathama** [comment]
https://github.com/odoo/odoo/pull/147912#issuecomment-1893563895 found the why

**Comment by lathama** [comment]
So maybe that field in the view needs to be read-only

**Comment by Rakoun** [comment]
Hello,

I notice this error also on Odoo 17.
When will it be fixed?

Regards

**Comment by lathama** [comment]
@Rakoun it is working as designed as noted at https://github.com/odoo/odoo/pull/147912#pullrequestreview-1823021355

**Comment by Rakoun** [comment]
@lathama it is weird because the notion of branches don't allow to create own chart of account. So if I want to create an holding that have children with their own chart of account I can't with this way. I mean that there is no way to understand that there are children companies. I will need to add a new field with odoo studio for example.
