### ISSUE TITLE
HttpOnly cookie with Odoo

### ISSUE THREAD

**Issue by StephanRozendaal** [odoo/odoo#16214]
Hi,

I would like to configure Odoo with the HttpOnly flag set on cookies.
I have Odoo running behind a Apache 2.4 proxy, in the config of my site I have the following line:
`Header edit Set-Cookie "(?i)^((?:(?!;\s?HttpOnly).)+)$" "$1; HttpOnly"`
When I configure this Odoo does not work correctly, for example printing something to PDF causes the client screen to stay grey and in waiting mode indefinitely.
My conclusion is that Odoo does not work well with this cookie setting, it's probably because of the JavaScript code that is run in the webclient.

Is it possible to run Odoo with the HttpOnly flag set on cookies?

**Comment by Yenthe666** [comment]
Hi @StephanRozendaal,

Thank you for your report.
The Github issue tracker however is only for bugs in the official code, it is not the place for asking questions.
I'd advise you to ask this question on the official Help forums (http://odoo.com/help) where plenty of people can help you!

Regards,
Yenthe
