### ISSUE TITLE
[All] Have a domain for each company.

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#16223]
Impacted versions: All

Steps to reproduce:
Create a company and set all the e-mail configuration.

Current behavior:
E-mails are sent through the same domain. If I have a multi-company environment I can't set an specific domain to a company so that Odoo sends e-mails using that domain.

Expected behavior:
Be able to set a domain/server to each company.
If a user has 3 e-mails, one with each domain, that the e-mail goes with that domain.

**Comment by edsersolis** [comment]
See: https://github.com/odoo/odoo/issues/7028

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Thanks for your report.
However, as you've stated this yourself, this is a duplicate report.
I'll close this one in favour of the other one, since it has a bigger history and more comments. I'll label the other one wishlist.

Regards,
Yenthe
