### ISSUE TITLE
Schedule throw error in log files odoo 10 buy same as old versions

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#16225]
Impacted versions: 10

Steps to reproduce: Scheduler log check.
Too many issues comes, but need to monitor 2 days than it show.

odoo scheduler buggy.

Current behavior:
  File "/home/sb/erp/odoo/models.py", line 3550, in write
    self._write(old_vals)
  File "/homesb/erp/odoo/models.py", line 3631, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/sb/erp/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sb/erp/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

Expected behavior:
least should work in linux platform.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @tejastank,

Thanks for your report.
I however see no issue/bug here? The TransactionRollbackError can happen if an order can't be handled at the time for example. Odoo will automatically retry this though.

Regards,
Yenthe

**Comment by tejastank** [comment]
I detected in latest too, 

@Yenthe666 thank for close without fix it. as odoo some benifit for close it.

Reported bugs never responsed in few week or day. but your kind of exta package do this dirty job.

Its better @Yenthe666 you ask to odoo why they not quick repsonse to community, community biggest give success to born tiny to openerp and to odoo.
