### ISSUE TITLE
[10] Can't adapt type 'account.tax' error when I click on 'New Quotation' button on Purchase Agreements

### ISSUE THREAD

**Issue by ig-landoo** [odoo/odoo#16222]
Impacted versions:
10e & 10c
Steps to reproduce:
1) You have to go to Purchases > Purchase > Purchase Agreements

2) Create a new agreement with the following:
   - Agreement type: Blanket order (it does not matter really)
   - A vendor with a valid fiscal position.
   - A product with vendor taxes.
Click on Confirm. 

3) Then you have to click on 'New Quotation' button.

Current behavior:
We get the following error traceback:
![image](https://cloud.githubusercontent.com/assets/22503846/24619776/790ef892-189b-11e7-967f-2cef4a7735e2.png)

We have seen a similar issue in v9 but unfortunately is not very helpful in this case.
https://github.com/odoo/odoo/issues/11351

**Comment by Yenthe666** [comment]
Hi @ig-landoo,

Thank you for your report.
I've just tested this and I can confirm that this is a bug.
@nim-odoo could you have a look? (sorry if I shouldn't ping you 😄)

Regards,
Yenthe

**Comment by tde-banana-odoo** [comment]
Actually there is a place in purchase_requisition where we create taxes_id with a recordset instead of ids. I am waiting for the runbot.

**Comment by Yenthe666** [comment]
@tde-banana-odoo you're ahead of me. I was just debugging this 😆

**Comment by tde-banana-odoo** [comment]
Done in 10 at https://github.com/odoo/odoo/commit/084967754870735ab75f9266e6ae9b8189385ab2 .
