### ISSUE TITLE
[9.0] [BUG] Invoice from PO: wrong tax amounts when currency changes

### ISSUE THREAD

**Issue by ThomasBinsfeld** [odoo/odoo#16231]
### Impacted versions: 
* 9.0

### Steps to reproduce:
1. Install Accounting and Finance and Purchase Management
1. Set the company currency in EUR and allow multi currencies
1. Create a purchase order in USD with at least one tax
1. Confirm the purchase order and receive products
1. Create a journal in USD
1. Create a new vendor bill
1. Select the new purchase order in "Add Purchase Order"
1. Select the USD journal

### Current behavior:
* Taxes amounts are not recomputed when selecting the journal which changes the currency of the invoice

### Expected behavior:
* When selecting a journal that changes the currency of the invoice, taxes amounts should be recomputed.

### Video link:
https://www.youtube.com/watch?v=fUV3aK7eKkI

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported I'm closing this issue. Sorry that nobody came around to looking into this.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe
