### ISSUE TITLE
[10.0] Premature Customer saving + Popup is not showing

### ISSUE THREAD

**Issue by SiviBu** [odoo/odoo#16262]
Impacted versions:
10.0

Steps to reproduce:

1. Click to create a new Opportunity.
2. Try to create a New Customer from 'Search More...':
![image](https://cloud.githubusercontent.com/assets/16593341/24706913/4386c616-1a1a-11e7-80b6-793da98348d0.png)

![image](https://cloud.githubusercontent.com/assets/16593341/24706952/66ac6c40-1a1a-11e7-9cc6-63f0d4590da7.png)

3. Click on '(edit)' button which should open a new popup to change Address element.

![image](https://cloud.githubusercontent.com/assets/16593341/24707085/f32f8f12-1a1a-11e7-84a4-0d4085411f18.png)

Current behavior:

1. Popup is not showing.
2. New Customer is automatically created (on the 3rd step) and 'Discard' doesn't work (no rollback available).

![image](https://cloud.githubusercontent.com/assets/16593341/24707389/0e2094be-1a1c-11e7-8296-b79c3e863513.png)

Expected behavior:

Form to edit Address should be opened in a popup in current window + New Customer should not be saved before (on the 3rd step).

Video/Screenshot link (optional):

https://demo3.odoo.com/web#home

**Comment by Yenthe666** [comment]
Hi @SiviBu,

This bug seems to be resolved already.
Please update your Odoo to the latest source code and try again.

Regards,
Yenthe
