### ISSUE TITLE
[10.0] Premature Customer saving

### ISSUE THREAD

**Issue by SiviBu** [odoo/odoo#16261]
Impacted versions:
10.0

Steps to reproduce:

We are trying to create a new Customer but it is saved in the database before:

1. /Sales/Sales/Customers
2. Press 'Create'
3. Fill in required fields.
4. Set Individual == True and select parent Company (parent_id).
5. Click on '(edit)' button which opens a new popup to change Address element.

Current behavior:

New Customer is automatically saved (on the 5th step) and 'Discard' doesn't work (no rollback available).

Expected behavior:

New Customer should not be saved in the database on the 5th step.

Video/Screenshot link (optional):

https://demo3.odoo.com/web#home

![image](https://cloud.githubusercontent.com/assets/16593341/24706442/55da74d6-1a18-11e7-970a-8229d4c30d54.png)

**Comment by Yenthe666** [comment]
Hi @SiviBu,

Thanks for your report.
I'm closing this one in favour of your other (https://github.com/odoo/odoo/issues/16262) as the other one contains more information.

Regards,
Yenthe
