### ISSUE TITLE
Filesize limits break database anonymization

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#16267]
Impacted versions:
9.0 & 9.0e, latest sources (05.04.2017 19:23 GMT+1)

Steps to reproduce:
Install Odoos anonymization module (anonymization), anonymize a bigger database. After successful anonymization, you obtain the file to revert the anonymization.

Current behavior:
As soon as you try to load the file to revert the anonymization, you get the error that the maximum upload limit of 25 MB is exceeded. As result you cannot de-anonymize your by Odoo (migrated) database.

Expected behavior:
No file-size limits for such uploads.

**Comment by Yenthe666** [comment]
@mart-e could this be one for you?

**Comment by mart-e** [comment]
Hello,

It would make sense to have, for this wizard, the a file upload similar to the one in the database manager without file size limit (well, only the one set on the web server configuration).

@ged-odoo should we extend the file upload widget or is there another we can use?

**Comment by xmo-odoo** [comment]
@mart-e maybe just backport 402379a48a31bc486145e81d8dae2910ae446b48 ?

**Comment by btredback** [comment]
@xmo-odoo hi，when upload large file,my browsers would crash. i use chrome and file size is 50MB.how to settle？

**Comment by xmo-odoo** [comment]
@btredback that I can't help with. If the browser itself crashes it's either an issue with Chrome itself or with e.g. anti-virus software messing with chrome and crashing it. Either way you want to report this to the Chrome project.

**Comment by Yenthe666** [comment]
@mart-e and @xmo-odoo I believe this is handled all fine in V10 and up so I believe we can close this?

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported I'm closing this issue.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe
