### ISSUE TITLE
Returning domain from server action applies to all rows in tree view

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#16272]
I am returning a dynamic domain from a server action in Odoo with the following code. Please note I am using a hosted version of Odoo online, so I am doing this through the Odoo UI. Actions are returned by assigning `action = {...}`.

    action = {
        'domain': {
            'route_id': [('id', 'in', record.x_all_route_ids.ids)]
        }
    }

This server action is triggered when the `product_id` field changes for a `sales.order.line`. When viewing a sales order, if I change the product_id for one of the sales order lines, the domain for the `route_id` field is updated as expected.

However, the domain is changed for all of the `route_id` fields in the sale order line tree view. In other words, if there are 3 lines in the order, and I change the product_id for one of them, I expected the domain to change for just that line's route_id field, not every route_id field in the sale order.

Is this a bug or expected behavior?

**Comment by dhannyz** [comment]
Hello @flyingL123 
I recently reported this issue as part of a larger problem with domains in odoo.
Read through https://github.com/odoo/odoo/issues/16072

The best way to achieve the functionality you want is to use @lmignon 's web_domain_field module as discussed in the above issue

**Comment by flyingL123** [comment]
Thanks so much. That thread was describing the exact issue that led me to post here. I wouldn't have found it without your help. I thought I was going crazy because my dynamic domain using the `[0][2]` method stopped working all of a sudden. And we are using Odoo SaaS, so I found it hard to believe that they would release a code change to cause this issue, but it looks like they did.

**Comment by Yenthe666** [comment]
Yep that did change & everything is answered so I guess a close is fine. 👍
