### ISSUE TITLE
invalid method signature in sale.order (R16)

### ISSUE THREAD

**Issue by jerzyk** [odoo/odoo#162742]
Impacted versions:
16.0

method `_notify_by_email_prepare_rendering_context` in `addons/sale/models/sale_order.py`

has `msg_vals` without default value, but method signature has it (and was changed in 3eb96806022705f5b667e149ffa2240760097278)

**Comment by Feyensv** [comment]
cc: @tde-banana-odoo 
Is it an issue if some overrides do not handle the case where `msg_vals` is not given ? (at least sale, purchase & account overrides AFAICS)

**Comment by tde-banana-odoo** [comment]
Don't know, easy to fix anyway ...
