### ISSUE TITLE
[10.0] Stock Inventory Line method _generate_moves returns empty object

### ISSUE THREAD

**Issue by SiviBu** [odoo/odoo#16280]
Impacted versions:
10.0

Why method _generate_moves() (from stock.inventory.line) returns empty stock.move object but not the list of objects (list of stock.move objects generated)?

![image](https://cloud.githubusercontent.com/assets/16593341/24751978/710a1092-1ad4-11e7-8946-c407dd233449.png)

**Comment by sle-odoo** [comment]
Hi,
Changing this now could lead to side effects, so we won't do it.
This is fixed in v11 though.

Regards
