### ISSUE TITLE
[9.0] Report empty picking bug on POS returns

### ISSUE THREAD

**Issue by glizek** [odoo/odoo#16292]
**Impacted versions:**
9.0
**Steps to reproduce:**
1. Have two stockables products.
2. Open new POS session.
3. Buy two stockables products.
4. To delete a product line you need to double clicking on delete button and if you only click one time it leaves the quantity on zero
![step10](https://cloud.githubusercontent.com/assets/25072045/24779448/3ce5cf1e-1af6-11e7-86b7-013069282aff.png)
5. Pay the sale order
![step13](https://cloud.githubusercontent.com/assets/25072045/24779465/51c56d40-1af6-11e7-821c-8271516fa8f3.png)
6. Open The POS order, and in the extra info tab I can see the Picking of the order where the product 1 moved.
![step17](https://cloud.githubusercontent.com/assets/25072045/24779493/7ab04838-1af6-11e7-96e3-ad29485034b2.png)
![step18](https://cloud.githubusercontent.com/assets/25072045/24779496/7e8be034-1af6-11e7-98b9-a4c72961502c.png)
![step19](https://cloud.githubusercontent.com/assets/25072045/24779504/8da42180-1af6-11e7-9a6b-ef4d245e3aae.png)
7. When the product is returned, it generates a new POS sale order of return type.
![step18](https://cloud.githubusercontent.com/assets/25072045/24810013/5265048c-1b86-11e7-8338-5070ceb88844.png)
![step20](https://cloud.githubusercontent.com/assets/25072045/24810048/7524897a-1b86-11e7-8a18-5b2a6489888e.png)
8. When the order is paid, it generates a return picking so it returns the moved product.
![step20](https://cloud.githubusercontent.com/assets/25072045/24779525/ad8997aa-1af6-11e7-85f2-e2c1fba0db6d.png)
![step23](https://cloud.githubusercontent.com/assets/25072045/24779542/cf4ee25a-1af6-11e7-9e99-43c7013615b7.png)
9. The return picking that is linked to the sale order is empty.
![step24](https://cloud.githubusercontent.com/assets/25072045/24779546/d4b4cd22-1af6-11e7-9595-1c4f88605635.png)
10. On warehouse stock moves, grouping by product, we can see that a new picking was also created for the same POS order (the one for the devolution) this one is not related on the POS order, but this actually is the one with the correct movements (stock moves).
![step25](https://cloud.githubusercontent.com/assets/25072045/24779576/ef30a5b8-1af6-11e7-9c30-0aeebcceb970.png)
![step27](https://cloud.githubusercontent.com/assets/25072045/24779578/f1e6e40c-1af6-11e7-85ef-2c3ceee07d18.png)

**Current behavior:**
Two pickings are being created.
The picking related to the POS sale order is empty, while the extra created picking which has the return product is not linked.

**Expected behavior:**
One picking created and linked to the sale order (with the correct stock moves).

**Comment by nim-odoo** [comment]
Is there any reason why you would like to keep the quantity of Product 2 to zero? To me, it seems more logical to not have the "Product 2" line on the pos order.

**Comment by nim-odoo** [comment]
Fixed in https://github.com/odoo/odoo/commit/eb9b888c5ab7dd9f7e6d7abec4c9b406b57ae798
