### ISSUE TITLE
Sale order lines 'related' fields are not updated after sale order changes

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#1629]
## Reproduce issue
1. Create sale order and sale order line. 
2. Change sale order partner. 
## Excepted results

Sale order partner is equal to sale order line partner.
## Got results

Sale order partner is not equal to sale order line partner.
E.g. select so.id, so.partner_id, sol.order_partner_id from sale_order as so join sale_order_line as sol on (so.id = sol.order_id) where so.partner_id != sol.order_partner_id;

This happens because related field are stored and is not triggered after sale order changes. It brings inconsistency in database, so it should be fixed with HIGH priority.

**Comment by cysnake4713** [comment]
have this one fixed?

**Comment by x2nie** [comment]
I did solve this similar situation. But I don't understand the sale order things,

So, , let say I have model "Sell" and there is a field Sell.Discount = Field.Float()
And the related and stored field is Sell_Lines.Discount = Field.Float( related= "sell_id.dicount", stored=True)
When I change the Sell.Discount, you may expect the Sell_Lines.discount should be reflected.

Here the solution: rewrite the sell_lines.sell_id will trigger the related fields to be reflected.
```
class SELL(odoo.Model)
   @api.multi
    def write(self, vals):
        if vals.get('Discount',False): # when discount changed
            for line in self.line_ids:
                line.sell_id = self.id #update related fields

```

**Comment by Yenthe666** [comment]
Hi @paulius-sladkevicius,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
