### ISSUE TITLE
Specify sheet for XLS and XLSX imports

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#16291]
Since Spreadsheets support multiple Sheets (tab) can Odoo support selecting the one to import from when an XLS or XLSX file is selected for import?

Impacted versions:

v10

Steps to reproduce:

Model / Import a File

Current behavior:

Defaults to first sheet in Spreadsheet

Expected behavior:

Dropdown with all sheets in the Spreadsheet

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
The bug tracker isn't really for external suggestions, you may want to submit it to https://www.odoo.com/help instead.

**Comment by bistaray** [comment]
@xmo-odoo - OK - that page makes it seem like it is for 'problems'.  I guess I can use the option 'OTHER'?

**Comment by xmo-odoo** [comment]
@bistaray yup
