### ISSUE TITLE
many2one fields too slow

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#1630]
Version used : commit d71a21bfdb25b6db942d82830788cc165db7c844

When I enter a value in a many2one, if I type the value (for example for a country, if I type 'France') and press 'Tab' key, the system is too slow to select the good value and select the first value (in my case, for the country 'France' it selects 'Afghanistan, Islamic Republic…').

In v6.0 of OpenERP, the system opens the list view in a dialog box to select between the possible choices. It will be good to have the same behavior here.

Screencast of the issue : https://cloud.theuret.net/public.php?service=files&t=355f1cf5fcbc976a2f79fcb90ee50172

**Comment by tesserB** [comment]
@mart-e Dead link and so there isn't enough context to try and reproduce the issue, let alone a solution.

**Comment by mart-e** [comment]
Indeed, if you press tab before receiving the answer, you will get the previous result (in this case the first without filter) but not much we can do to prevent people to go too fast.
