### ISSUE TITLE
Apps for odoo v10 CE

### ISSUE THREAD

**Issue by Kenau** [odoo/odoo#16317]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Kenau** [comment]
I have odoo v10 community edition. Do I have to pay anything for the apps, such as manufacturing?

**Comment by jashjacob** [comment]
Odoo Community edition is free. If you're looking for more information please check the website - https://www.odoo.com/page/editions

**Comment by Yenthe666** [comment]
Hi @Kenau,

Please create an issue which describes your problem into detail, otherwise it is hard to help.
If you have the Odoo hosted at your own and if it is a community version you can install as many apps as you'd like.

Regards,
Yenthe

**Comment by Kenau** [comment]
I have the v10 community edition on my laptop.I tried to download apps such as manufacturing and purchasing from the apps page showing on my community edition and they all say that they are free for 15 days but then you have to pay for them.  How do I get them for free.
