### ISSUE TITLE
[10.0] partner_shipping_id error invoicing from POS

### ISSUE THREAD

**Issue by ovnicraft** [odoo/odoo#16312]
Impacted versions: 10.0

Steps to reproduce:

1. create a fresh db with latest code, install, point_of_sale, pos_restaurant, configure
2. Create an order, add items, continue to payment
3. select a payment, active Invoice, validate
4. Get the error

Current behavior:

system raise an error: https://gist.github.com/ovnicraft/975a5c8c2e6f4eb5f8493ec92419988a

Expected behavior: Generate the invoice
I check the code in error, i found method try to read partner_shipping_id field [account/models/account_invoice.py L487](https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_invoice.py#L487) but this field is added in `sale` module: [sale/models/account_invoice.py L22](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/account_invoice.py#L22)

The bug was introduced here: https://github.com/odoo/odoo/commit/1452a9903cf47b39d7fdb9bb788e99550ee943d2#diff-f3712147f4b25231caa371bd83265dbe

**Comment by jorenvo** [comment]
Thank you for the bug report. It should have been fixed at https://github.com/odoo/odoo/commit/a3778ceada62ebb7935bbdf1ff19e5aeb12251b9.
