### ISSUE TITLE
Bank :: Address :: Country must be choosen before state

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#1631]
On bank definition, when you define the address of your bank, the field 'State' is displayed before the field 'Country' but the 'State' are filtered according to the choosen country.

I raise this issue on bank, but I think there is the same ergonomic issue on other addresses form.

**_Impacted versions:**_
- Latest trunk (d71a21bfdb25b6db942d82830788cc165db7c844)

**_Steps to reproduce:**_
1. Go to 'Sales / Address Book / Banks'
2. Create a new bank
3. Define address of the new bank

**_Current behavior:**_
- Field 'State' is displayed before the field 'Country'

**_Expected behavior:**_
- The field 'Country' must be displayed and set before the field 'State' to allow possibility to filter the states according to choosen country.

**Comment by Yenthe666** [comment]
Hi @qtheuret,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
