### ISSUE TITLE
[10.0]Bug:Shopping cart don't apply the Pricelist Formula

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#16323]
Hi:
I am using odoo 10,it has a bug,that is Shopping cart don't apply the Pricelist Formula.

1. I add a price list rule of 50% discount on 10pcs order. 
![2](https://cloud.githubusercontent.com/assets/3096827/24827674/1dc8f4c6-1c81-11e7-9c04-03934333391f.PNG)

2. On product page the price calculated correctly once the order quantity reach 10pcs.
![default](https://cloud.githubusercontent.com/assets/3096827/24827672/1dc43c88-1c81-11e7-9716-e66680d42fec.PNG)

3. But on shopping cart page, the price still not change and did not add the discount once the quantity reach 10pcs. 
![1](https://cloud.githubusercontent.com/assets/3096827/24827673/1dc4f588-1c81-11e7-9674-0fcdbf16b592.PNG)

I have updated to the latest version of odoo 10 and test in both local and web server condition. The problem is the same.

**Comment by Yenthe666** [comment]
@JKE-be?

**Comment by amoyaux** [comment]
I'm on it.

**Comment by RocWu** [comment]
@amoyaux @JKE-be any news?

**Comment by amoyaux** [comment]
@RocWu It should be fixed now by this commit c5f2200a76fd5bfa5f335ec57a155d961ae91e3f but it seems that the bug appears again 2 days ago. The bug fix team is on it.

**Comment by ed29** [comment]
It works now,so i should close this issue,thank you all.
