### ISSUE TITLE
Feature require:MOQ for e-commerce

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#16324]
Hi:

We use odoo 10 's e-commerce to wholesale  products,and we need to set MOQ(Minimum Order Quantity),for an example,i want to wholesale shirt no less than 100 pcs,but in odoo 10,there is not way to achieve it.

I believe the MOQ is necessary for odoo to wholesale products for merchants.So,would you please consider to add this feature to odoo?

Thanks.

**Comment by Yenthe666** [comment]
@mart-e perhaps we could label this wishlist?

**Comment by ed29** [comment]
@JKE-be Hi,does it get ready?

**Comment by JKE-be** [comment]
Hi @ed29 

Until now, it has not been yet added.
But it don't seems a priority for v11.

Maybe @fgi-odoo can confirm if we want it or not for v11.

Thanks

JKE-be

**Comment by wtaferner** [comment]
:+1: 

I vote for having it as it is quite common that you do not offer to sell only one piece of an item online...of course it would be ideal for consumers/customers but very often it does not pay off to start an online shop based on this, so let's give this option for e-commerce in v11 a priority and even more shops will work out of the box :-)

**Comment by JKE-be** [comment]
@wtaferner 
If you are talking e.g. about 'screws' that you only want to sell by pack of 4... it is not MOQ that will help you... What you need is a BillOfMaterial with 4x 1 screw...

IMHO, MOQ is an advanced feature, that most people will not use... 
The main use (I can see) will be when you use the unit as weght,... E.G. you sell coffee by 1 unit = 100g => but don't want to sold <500g

**Comment by wtaferner** [comment]
@JKE-be 
No, not really, but certainly this is somehow a workaround which would work to a certain extend.

It is just that the handling would not pay of for some companies if they sell less than 10 pieces for example...11 pieces would be ok, so you would not bundle it as an own product but only allow a minimum of 10 pieces for a certain product :-)

But [this link](https://www.salehoo.com/glossary/minimum-order-quantity-moq) does explain it very well imho :-)

**Comment by ed29** [comment]
As an ecommerce tool,these two function MOQ and Sell By Pack mentioned by @JKE-be will make odoo more complete,less pain for merchants,more popular,in my opinion.These two function's relationship is a little bit complicated for me,but,if you can make it,why no?

**Comment by lukebranch** [comment]
@ed29 ,

Regarding 'Sell by pack' this feature is already available out of the box with a bit of configuration, you just need to define a BoM (Bill of Materials) on a product, or product variant for example.

I believe it would be useful to have a Many2One on the variants for UoM for the variant.

I have used Odoo for B2B e-commerce projects before, and have always thought it might be useful to have an option in the core for listing the available UoM's or Packaging that can be sold to the customer in a similar method to variants. In fact I believe if there was the option out of the box to specify different UoM's on variants of a product.template this might achieve the sort of functionality that would be useful in this scenario.

For example you could have an variant attribute - 'Packaging' with the following options:

Unit = 1 x Unit (UoM)
Carton (1x24) = 24 x Unit (UoM)
Pallet (24x24) = 576 x Unit (UoM)
Container (24x24x24) = 13824 x Unit (UoM)

This way you could allow the e-commerce user to select the variant/packaging they want to purchase.

In this case though i'm not sure whether it would be useful to have a QTY field for each of the variants, to allow the user to purchase for example, 5 single units, 1 carton, 2 pallets, etc. together in the same page.

In your scenario would you like the user to be able to purchase only in increments of 100 units? For example: 100, 200, 300, ...

Or would you like to restrict them to ordering a minimum of 100, but perhaps 101, 105, 109, ...?

For B2B scenarios it would also be useful to have a sort of tiered pricing displayed on the product page if possible as well.

For example:

1 x Unit = $XX
10 x Unit = $YY
100 x Unit = $ZZ

or

Unit = $XX
Carton (1x24) = $YY
Pallet (24x24) = $ZZ

**Comment by ed29** [comment]
@lukebranch I am not much good at odoo yet,thank you for the info of Sell by pack,and,your comment hits my point.
