### ISSUE TITLE
Refresh odoo module on production

### ISSUE THREAD

**Issue by unrealsolver** [odoo/odoo#16342]
Impacted versions: not specific, 10.0

Steps to reproduce: N/A

Current behavior: N/A

Expected behavior: I'd like to have an ability to refresh odoo module without restarting odoo in production. I'm building zero deployment time system and this is an issue. Currently, I use `./odoo-bin shell < script.py` approach to install the module, but I cannot refresh the python code this way.

Video/Screenshot link (optional): N/A

**Comment by Yenthe666** [comment]
Hi @unrealsolver,

Not sure what you're looking for then though.
You can either update the modules list from within Odoo (under settings) or you can do a `sudo service odoo-server -u yourmodule`.
Not sure what else you're looking for?

Regards,
Yenthe

**Comment by iurii2017** [comment]
Hi @Yenthe666 ,

The issue that that @unrealsolver  and myself are trying to resolve is the following:
* There is a custom Odoo installed on a "production" instance of Odoo which is up an running. And a critical bug has been found in code of the module
* The question is how to update the module's code on a running Odoo instance without restarting it

Regards
Iurii

**Comment by Yenthe666** [comment]
Well those questions are not for the Github issue tracker as it is a question about implementation/configuration. 
Have a look at the docs (https://www.odoo.com/page/docs) or ask this question on the help forums (help.odoo.com).
In short: You'll always have a very minor downtime unless you create advanced systems for this.
