### ISSUE TITLE
lxml error when run odoo17 in pycharm on macbookpro

### ISSUE THREAD

**Issue by liujichao2017** [odoo/odoo#163429]
downloaded odoo17 , development env include python 3.10, postgresql 15.5,  pycharm 2024.1 ,mac-book-pro,  interpreter is ok. But when i run the odoo17, it showed error as followed:
![error](https://github.com/odoo/odoo/assets/29662008/db92d992-0665-4869-97d5-bcb4114298cc)
i tried several times , but the error still exists, please help me solve this issue

**Comment by lathama** [comment]
TL;DR;
Install https://tracker.debian.org/pkg/lxml-html-clean or https://pypi.org/project/lxml-html-clean/
