### ISSUE TITLE
Error in Yearly Salary by Employee

### ISSUE THREAD

**Issue by ShivaGuntuku** [odoo/odoo#16345]
Impacted versions:
Odoo10

Steps to reproduce:
Employees Module-->Reports-->Error in Yearly Salary by Employee-->print
Note: install Indian payroll Module(l10n_in_hr_payroll)

Current behavior:
ProgrammingError: relation "payroll_emp_rel" does not exist
LINE 1:  DELETE FROM payroll_emp_rel USING "hr_employee"

Expected behavior:
Yearly Salary Report

Video/Screenshot link (optional):
![selection_011](https://cloud.githubusercontent.com/assets/13907310/24861182/6433ad80-1e15-11e7-9918-0367cb846f2c.png)

**Comment by Yenthe666** [comment]
Hi @ShivaGuntuku,

Thank you for your report.
I just tested this on the latest Odoo 10 without any problem. Can you reproduce this on an official instance? (runbot.odoo.com). Can you please try and update your Odoo to the latest codebase?

Regards,
Yenthe

**Comment by ShivaGuntuku** [comment]
Hi @Yenthe666 
In runbot.odoo.com did not getting any error but in my local getting error, I updated all addons modules in my system still cause error while printing report. is any suggestion to get rid of that problem.

Thanks&Regards,
Shiva

**Comment by Yenthe666** [comment]
Hi @ShivaGuntuku,
If you can't reproduce it on the runbot it is no longer a bug in the official Odoo. With updating all addon modules I believe you mean a `git fetch origin` in which you got the latest code from Github or?

Regards,
Yenthe
