### ISSUE TITLE
V10 - BOM Cost report doesnt show product variant (solution included)

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#16355]
Impacted versions: V10

Steps to reproduce:
Got to a BOM and choose "BOM Cost" from the print menu.
Unlike the BOM structure, the BOM cost does not show the product variant

Current behavior:
When printing the BOM Cost, it is not showing the product variant like the BOM structure print.

Expected behavior:
Shows the product variant the same when printing the BOM structure.

Solution
in view: mrp_bom_cost_report
change on line 35 
t-esc="bom_line['product_id'].name"
to
t-esc="bom_line['product_id'].display_name"

**Comment by sle-odoo** [comment]
Fixed in https://github.com/odoo/enterprise/commit/8b66e937d0a245864f671fda4e89095e37c04b70

Thank you
