### ISSUE TITLE
[10.0] Bug: CRM calendar event jumps to other time

### ISSUE THREAD

**Issue by MuliuolisA** [odoo/odoo#16363]
Impacted versions: 10.0

Steps to reproduce: 
1. Open calendar app and create any event (my time zone is Europe/Vilnius)
2. The event jumps 3 hours earlier. If you create an event starting at 10:15 it represents as 7:15
![calendar_jump](https://cloud.githubusercontent.com/assets/27268862/24896509/eca6ff86-1e9d-11e7-9637-4f5445d6c1af.png)
Even worse happens when you mark as all day event. It jumps to previous day...
![calendar_allday](https://cloud.githubusercontent.com/assets/27268862/24896768/14e6f360-1e9f-11e7-991b-3a17647790bc.png)

I updated my version to the latest one and even tested it Odoo demo and the problem is the same.

**Comment by gustavovalverde** [comment]
Same as https://github.com/odoo/odoo/issues/16027

I can also confirm this

**Comment by Yenthe666** [comment]
Hi @MuliuolisA,

Thanks for your report.
I'm closing this one in favour of the older one which is the same issue. (#16027)

Regards,
Yenthe
