### ISSUE TITLE
Extra downpayment line with price zero auto generated when remove the tax on first downpayment invoice.

### ISSUE THREAD

**Issue by jellyfrank** [odoo/odoo#163699]
Impacted versions:17.0

Steps to reproduce:
1. create an SO, then create downpayment with 30% percent, remove the tax in generated INV and post the invoice.
2. go back to SO create another downpayment with 30%

Current behavior:
the second invoice has two downpayment lines with one of them witch price is 0, just like the image below:

Expected behavior:
It was supposed to be only one line is invoice lines

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/6907475/4749d6cb-9c65-4740-a695-f69b31685f5a)

![image](https://github.com/odoo/odoo/assets/6907475/668267e7-85e7-4a69-9059-18c82da04305)

Support ticket number submitted via odoo.com/help (optional):

**Comment by gkfz-odoo** [comment]
Client uploaded ticket with id 3897099 regarding this issue:
https://www.odoo.com/web#id=3897099&cids=17&menu_id=4720&action=3530&model=project.task&view_type=form

It has been forwarded to bugfix.
