### ISSUE TITLE
[10.0] Normal delivery charges (not integrated) not properly set in order if "Set Price" isn't clicked

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#16379]
### Impacted versions:
10.0 (possibly 9.0 too)

### Steps to reproduce:
1. Go on runbot instance, Odoo 10.0, all module installed, demo data.
2. Create a new sale order
3. Select Agrolait as customer
4. Keep Normal Delivery Charge as carrier, don't press "Set Price"
5. Add an iPad to the line items
6. Confirm Sale
7. Jump to the delivery order
8. Validate the delivery order without making any change

### Current behavior:
In the sale order, Normal Delivery Charge has been added, that's ok. But the price isn't set properly. It's still à 0.00

### Expected behavior:
The price of Normal Delivery Charge should be 7.79, the same as if I pressed "Set Price" in the sale. Seems like the normal basic charges aren't working properly as opposed to integrated carriers who seem fine. I didn't test, but maybe just installing "delivery" module is breaking the normal delivery charge behaviour.

My understanding of "Set Price" is to fix the delivery cost when the order is taken. If set price isn't clicked, the real delivery cost is taken. This is perfect!

**Comment by sle-odoo** [comment]
10.0 is no longer supported
