### ISSUE TITLE
[9.0] print uncrypted passorld

### ISSUE THREAD

**Issue by gaelTorrecillas** [odoo/odoo#16374]
Impacted versions: 9.0

Hello,
I add "print" on "domain" in openerp / models.py line 5446 (in _where_calc) and I see the unencrypted password when launching Odoo.

Is this normal?

**Comment by Yenthe666** [comment]
Hi @gaelTorrecillas,

Thanks for your report.
The Github tracker is however only for bugs, not for changes or custom development.
Please ask this on the official help forums (help.odoo.com).
P.S: Yes it is not yet encrypted there.

Regards,
Yenthe
