### ISSUE TITLE
Change the daily backup time in Odoo.sh

### ISSUE THREAD

**Issue by sst-smart** [odoo/odoo#163700]
Hello everyone,

I need to change the daily backup time on Odoo.sh because it currently occurs in the middle of my working day. For example, my working hours are from 8:00 AM to 11:00 PM, so I would prefer the daily backup to take place at 1:00 AM, after my workday has ended.

regards,
Mohamed

**Comment by ossimantylahti** [comment]
@sst-smart Unfortunately that feature is not available in Odoo.sh. Your only option would be to run Odoo on a different environment.
