### ISSUE TITLE
Domain on one2many field on the xml view not working

### ISSUE THREAD

**Issue by tchigy** [odoo/odoo#16398]
Impacted versions:

Odoo 9.0

Steps to reproduce:

 `<field name="one2many_field_name" readonly="1" nolabel="1" domain="[('id', '=', False)]">`

Current behavior:
one2many field is not empty

Expected behavior:
one2many should not load the record that don't match the given domain this is usefull when i try to load some data only for readonly mode so i don't have to create multiple one2many in the model code.
i can put the same field multiple time to show the same one2many field in three or more pages in the view for example

sorry for my english.

**Comment by Yenthe666** [comment]
Hi @tchigy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by mathben** [comment]
Hi @Yenthe666 , I have the same problem with Odoo 10.
I set a domain to a one2many field and the result is the same without the domain.

**Comment by mathben** [comment]
It works when I add the domain in the fields definition in Python. The domain in the xml tree view not works.
Works :
test_ids = fields.One2many(comodel_name="test.lines",
                                          inverse_name="test_id",
                                          domain=[('test_enable', '=', True)])

Not works :
<field name="test_ids" domain="[('test_enable', '==', True)]" />

**Comment by batazor** [comment]
+1

**Comment by Otgontugs** [comment]
The same for Odoo 10.
+1

**Comment by elgow** [comment]
Same problem in Odoo 11.  Can this be re-opened, since it seems to affect supported versions?

**Comment by Yenthe666** [comment]
Please create a new issue for V11 which shows this behaviour on a runbot instance :)

**Comment by elgow** [comment]
The new issue is already in place https://github.com/odoo/odoo/issues/55712   
I do not seem to have the ability to load my my own module code into runbot, but if I'm missing something please point me to the relevant procedure.

**Comment by Yenthe666** [comment]
You can use Studio to demonstrate it? :)

**Comment by elgow** [comment]
Thanks Yenthe, I'll try that. It will be a new experience for me as I've always coded my modules the old fashioned way.

**Comment by yeisondoitwiser** [comment]
More than two years and this stills and issue on odoo 15, the field does not get filtered

**Comment by ivanporras** [comment]
odoo 15 does't work
