### ISSUE TITLE
[10.0] IMPORTANT: Automatic Push Rules do not move quants and break location stock levels!

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#16407]
_Impacted versions:_
10.0  + possibly others.

_Steps to reproduce:_
Create a push with an automatic move, trigger this with a move into the source location.
Check original, and desired destination stock levels (these are computed based on the sum of quant qty's)
Only the move destination is changed, open a view of the quant at it is still in the original location, despite the history correctly showing the move with a destination of that set in the push rule.

Current behavior:
```python
    def _apply(self, move):
        new_date = (datetime.strptime(move.date_expected, DEFAULT_SERVER_DATETIME_FORMAT) + relativedelta.relativedelta(days=self.delay)).strftime(DEFAULT_SERVER_DATETIME_FORMAT)
        if self.auto == 'transparent':
            move.write({
                'date': new_date,
                'date_expected': new_date,
                'location_dest_id': self.location_dest_id.id})
            # avoid looping if a push rule is not well configured; otherwise call again push_apply to see if a next step is defined
            if self.location_dest_id != move.location_dest_id:
                # TDE FIXME: should probably be done in the move model IMO
                move._push_apply()
        else: # manual step logic here which works correctly because a new picking is created
```
There is no logic to change the quant's location, and this is set via the pack operation lines in the picking, which is never updated to match the push rule.

_Expected behavior:_
Surely the quant should also be moved to reflect the push, otherwise stock levels are all messed up.
IMO this is a fairly major oversight in a crucial area of Odoo. The move is showing a destination that the quant never gets to

**Comment by sle-odoo** [comment]
Hi,
I don't get it ; maybe you're mistaking push rules for putaway strategies?
Push rules are working properly, it creates another (chained) move.

If you understand the putaway strategies and it is not what you're looking for, please describe what you want to do and how you're implementing it (in terms of routes and push rule(s) used + locations, etc).

Regards
