### ISSUE TITLE
Unable to lock fiscal period due to newly added validation

### ISSUE THREAD

**Issue by tebanep** [odoo/odoo#16403]
Impacted versions: 10.0

Steps to reproduce:
Set an account move in draft state. When trying to lock the fiscal period the account move is in, a new validation introduced in commit 925440b7a0dbde85ec9b7a4474f205da0ef96f94 on march 28 of 2017 prevents the process. 

Current behavior:
The lock of fiscal periods can't be fulfilled through the accounting configuration due to a new validation introduced. 

Expected behavior:
The fiscal period locking should be allowed as there are multiple reasons to have draft Journal Entries in closed periods. 

We have posted the following comment in the github commit: 

Hello.

Could you please explain to us what is the rationale to enforce this behaviour? Right now this is causing huge issues in some of our production systems as new periods can be blocked if the have cancel some entries for example and don't want to delete them due to auditing concerns. 

Could you please revert this commit? This is new business logic that shouldn't be ported to stable branches such as 9.0 or 10.0. 

Thanks!

**Comment by fclementic2c** [comment]
It is important to have 2 different period locking:
One permanent (fy closing)
One that you can modify
