### ISSUE TITLE
[v8] Menu structure becomes corrupt when install is "partial".

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#1641]
If I attempt to install module A, and module A depends on module B, and B is not installed, the system attempts to install B, then A. (Correct)

If B successfully installs, and A fails due to some error, then the install process never completes the compute parent left / parent right for ui_menu.  The menus now never display.

**Comment by LeartS** [comment]
Just encountered this issue. Do you have any workaround? Is there a way to explicitly recompute menu parent_left and parent_right?

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
