### ISSUE TITLE
Cannot create stock_move got security exception

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#16414]
**Impacted versions:** v8.0

**Steps to reproduce:**
I would like to create an inventory using a user with stock_manager privileges 

**Current behavior:**
cannot create security exception
ValidationError: ('ValidateError', u"field(s) product_uomcontrainte error : You try to move a product using a UoM that is not compatible with the UoM of the product moved. Please use an UoM in the same UoM category.
AccessError The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: stock.move, Operation: read) ")

**Expected behavior:**
create the line because the user have the all rights

**Comment by m3asmi** [comment]
how can I debug this error ?

**Comment by Yenthe666** [comment]
Hi @m3asmi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
