### ISSUE TITLE
Time Off cronjob error when employees have different working hours

### ISSUE THREAD

**Issue by m-melis** [odoo/odoo#164259]
When employees are set to different working hours the time off cronjob is failing with `ValueError: Expected singleton: resource.calendar(1, 2)`.

I think the source of the problem is here, where `self.employee_id` instead of `allocation.employee_id`

https://github.com/odoo/odoo/blob/17.0/addons/hr_holidays/models/hr_leave_allocation.py#L466

Odoo version 17.0-20240312

**Comment by vava-odoo** [comment]
Hello @m-melis 
Thanks for reporting. The bug is now fixed.
Cheers
