### ISSUE TITLE
Print report issue

### ISSUE THREAD

**Issue by lygtmxbtc** [odoo/odoo#16425]
Impacted versions:
Odoo 10.0
Steps to reproduce:

Current behavior:
For example, normally in the tree view of Sale Order, click several records and then click print report button. It will generate corresponding several reports for these SO records.
Expected behavior:
Now how can I do to put the fields in these SO records into JUST ONE report template. That means the just print one page which includes several SO records field.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @lygtmxbtc,

Thanks for your report.
The Github issue tracker is only for bugs in the official code though, not to ask questions.
Please do this on the official help forums (odoo.com/help).
By default it will generate every sale order on a new page. If you don't want this you'll need to add custom code.

Regards,
Yenthe
