### ISSUE TITLE
Error while upgrade base module after create new DB : View `workflow.activity.form` [view_id: 85, xml_id: base.view_workflow_activity_form, model: workflow.activity, parent_id: n/a]"

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#1644]
Step to reproduce : Create new DB
Before install any module upgrade base module.
then you will get the following error....

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `sequence` does not exist

Error context:
View `workflow.activity.form`
[view_id: 85, xml_id: base.view_workflow_activity_form, model: workflow.activity, parent_id: n/a]" while parsing /opt/orchiderp/test/odoo/openerp/addons/base/workflow/workflow_view.xml:86, near
<record id="view_workflow_activity_form" model="ir.ui.view">
      <field name="name">workflow.activity.form</field>
      <field name="model">workflow.activity</field>
      <field name="arch" type="xml">
        <form string="Activity">
           <sheet>
            <group>
                <group>
                    <field name="name"/>
                    <field name="wkf_id"/>
                    <field name="kind"/>
                </group>
                <group>
                    <field name="flow_start"/>
                    <field name="flow_stop"/>
                </group>
            </group>
            <notebook>
            <page string="Properties">
              <group>
                <group string="Subflow">
                  <field name="subflow_id" attrs="{'readonly':[('kind','&lt;&gt;','subflow')]}"/>
                  <field name="signal_send"/>
                </group>
                <group string="Conditions">
                  <field name="split_mode"/>
                  <field name="join_mode"/>
                </group>
                <group string="Actions">
                  <field name="action_id"/>
                  <field name="action" attrs="{'readonly':[('kind','=','dummy')]}"/>
                </group>
              </group>
            </page>
            <page string="Transitions">
                <field name="in_transitions">
                  <tree string="Incoming Transitions">
                    <field name="sequence" widget="handle"/>
                    <field name="act_from"/>
                    <field name="signal"/>
                    <field name="condition"/>
                  </tree>
                </field>
                <field name="out_transitions">
                  <tree string="Outgoing Transitions">
                    <field name="sequence" widget="handle"/>
                    <field name="act_to"/>
                    <field name="signal"/>
                    <field name="condition"/>
                  </tree>
                </field>
            </page>
          </notebook>
         </sheet> 
        </form>
      </field>
    </record>

**Comment by Yenthe666** [comment]
Hi @orchidinfosys ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
