### ISSUE TITLE
Ecommerce product variant price update doesn't work with 0 decimal currencies (i.e. XOF)

### ISSUE THREAD

**Issue by sdaguet** [odoo/odoo#16447]
Impacted versions: 9.0, 10.0, saas-15

Steps to reproduce: currency with no decimal (i.e. XOF), product variants published on website, selection a new variant

Current behavior: doesn't update price, adding it to basket doesn't work. In javascript console:
>Error: [_.sprintf] huh?  web.assets_common.js:96:12

        
Expected behavior: update price, add right variant to backed

Video/Screenshot link (optional):

See my comment on commit : https://github.com/odoo/odoo/commit/fee60159640206558e98d5103c8a883412419f5a#diff-48c3d3bd5deb68fe268e5d6b29efff9b

To be checked:

-Is it normal qweb doesn't add the attribute if value of product.currency_id.decimal_places value is 0 (0 decimals) ?
Template: <template id="product_price"> in website_sale/views/templates.xml

>t-att-data-precision="product.currency_id.decimal_places"

-To temporary solve, added a isNan tests in the fprice_to_str unction 
>website_sale/static/src/js/website_sale.js

` function price_to_str(price) {
            var l10n = _t.database.parameters;
           var precision = 2;

            if ($(".decimal_precision").length) {
                precision = parseInt($(".decimal_precision").last().data('precision'));
                console.log(precision);
            }

            if ( isNaN (precision) ) {
                precision = 0;
            }

            var formatted = _.str.sprintf('%.' + precision + 'f', price).split('.');
            formatted[0] = utils.insert_thousand_seps(formatted[0]);
            return formatted.join(l10n.decimal_point);
        }`

**Comment by yostashiro** [comment]
I have confirmed the issue and created an Enterprise ticket.

**Comment by Yenthe666** [comment]
@JKE-be for you? 😉

**Comment by JKE-be** [comment]
Hello,

It has been already fixed.

best regards

https://github.com/odoo/odoo/commit/87d12bb27c1cac6510fc6b9b3ad74374489ac0e8
