### ISSUE TITLE
odoo10.0 push rule issue, the picking orders generated by push rule linked to the manufacturing order 

### ISSUE THREAD

**Issue by EvanWang2016** [odoo/odoo#16448]
Impacted versions:10.0

Steps to reproduce:
1,new a finish good
2,new a material 
3,new a bill of material for the finish good and the component is the material from step 2
4,new a route for the finish good to generate 2 picking order automatically after create the manufacturing order
5,the new route use push rule: workshop->quality area, quality area->inventory
6,create a manufacturing order for the finish good
7,the 2 picking orders generated correctly 
8,but when i try to finish that MO, the error occurred
9,check the MO, found that the two picking orders linked to the MO and display on the finished products(this is wrong and in odoo version 9.0 it will not display on this tab)

Current behavior:

Expected behavior:

Part of the error information:
```
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mrp/models/mrp_workorder.py", line 316, in record_production
    if production_move.product_id.tracking != 'none':
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 863, in __get__
    record.ensure_one()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4813, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.move(79, 81, 80)
```

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
please more detail for how to setup the push route.

**Comment by EvanWang2016** [comment]
@jeffery9 It work now, thanks!

**Comment by EvanWang2016** [comment]
For test case

**Comment by jeffery9** [comment]
#16449  try to fix this, but not passed the Unit test case.    @mart-e

**Comment by jeffery9** [comment]
how to replay this issue. please refer.  http://shine-it.net/topic/4504/odoo10-0%E7%94%9F%E4%BA%A7push-rule-%E6%8E%A8%E5%BC%8F%E8%A7%84%E5%88%99-%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98

**Comment by digitalsatori** [comment]
@jeffery9 Your fix creates regression.
in the `move_validate` method on mrp/models/stock_move.py  around line 256:
```
                qty_split = move.product_uom._compute_quantity(move.product_uom_qty - move.quantity_done, move.product_id.uom_id)
                new_move = move.split(qty_split)
```
That is used to creating new move  for the remaining produce quantity. The above code will expect the product_id to be copied to the new move.

**Comment by jeffery9** [comment]
so, should overwrite push flow which copy the origin move to avoid to copy `production_id`.

**Comment by EvanWang2016** [comment]
@digitalsatori Thanks Tony, i will test it again for the split case.

and ,what is the best solution? i don't know the code  :  )  i just test odoo application

**Comment by EvanWang2016** [comment]
@jeffery9  i have test again with the latest code, and it works, though i don't know which part will be effected by the last code(not modify the push flow), but still thanks!

**Comment by digitalsatori** [comment]
> so, should overwrite push flow which copy the origin move to avoid to copy production_id.
@jeffery9 or, maybe the other way around. make the `production_id` un-copiable, and assign the `production_id` explicitly after the stock move split.

@mart-e Please kindly advise.

**Comment by pimodoo** [comment]
Hello,
Could you be more specific on how did you configure your route and your picking types. Did you disable other routes such as 'Manufacturing'.

Best regards

**Comment by EvanWang2016** [comment]
@pimodoo thanks for your reply. i didn't disable the route generated by system itself.
blow is my setup for product/route/push rules: 
**Finish good :** 
Product Type:	Stockable Product
Routes: push(created by myself)   Manufacture(created by system)

**Material:**
Product Type:	Stockable Product
Routes: Buy(created by system) 

**BOM:**
Product: Finish good  quantity :  1
Bom Type: Manufacture this product
Components: Material   quantity: 10

**Route:**
Name: push
Applicable On: Products

**Push rule created by myself:**
Operation Name:push
Source location: WH/stock
Destination Location : WH/Quality Control
Automatic Move : Manual Operation
Picking Type: My Company: Internal Transfers

Procurement Rules: Null


After created a manufacturing order for Finish good manually , there are two stock move on the Finished Products tab, and in the right case, it should be only one: Virtual Locations/Production  -> WH/Stock

anther stock move is WH/Stock->WH/Quality Control, it generated by the push rule correctly , but it should not display on the Finished Products tab on the manufacturing order, and in this case, when i press the button [Produce] and try to finish this MO, it show error:

  File "C:\Program Files\Odoo 10.0\server\odoo\fields.py", line 864, in __get__
  File "C:\Program Files\Odoo 10.0\server\odoo\models.py", line 4814, in ensure_one
ValueError: Expected singleton: stock.move(17, 18)


Also i found the source document and the Procurement Group of this stock move are the name of the manufacturing order...

So.please do useful help

if you have any concern or further information ,please let me know

**Comment by pimodoo** [comment]
@EvanWang2016 Hello, I've made a fix that should fix your problem, could you confirm me that it works well for your use case before to merge it in stable. Here is the PR: https://github.com/odoo/odoo/pull/16521

Best Regards

**Comment by EvanWang2016** [comment]
@pimodoo Hello, i have test again this issue with your fixed code
and it works! Now the picking order generated by the push rules not display on the Finished Products tab and it also support split the MO quantity with no errors!
@jeffery9 @digitalsatori This issue has been solved, appreciate for both of your help.thanks

Appreciate for your kindly help and Best regards!

**Comment by EvanWang2016** [comment]
Done

**Comment by pimodoo** [comment]
pushed in rev: https://github.com/odoo/odoo/commit/93714790c1286568002ec5fbcb95540e0f27f824
