### ISSUE TITLE
[IMP]Show corresponding account in error message "You cannot use deprecated account."

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#16453]
Impacted versions: 
9.0 observed, others possible

Steps to reproduce:
Do something which involves a deprecated account.

Current behavior:
The error message does not indicate the corresponding account. But this error can happen in situations where you really have no clue which account could be meant.

Expected behavior:
Indicate the account which is involved and deprecated.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @treviser,

Thank you for your report.
I agree this could be an improvement, I've been searching for this one a few times before too.
@qdp-odoo what do you think?

Regards,
Yenthe

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/pull/19392

**Comment by qdp-odoo** [comment]
closed with https://github.com/odoo/odoo/commit/93d4da977a2ad41dd0547977f3faace55df2cc76

Thanks for the suggestion
