### ISSUE TITLE
Leave management app -> upgrade fails silently (See video demo)

### ISSUE THREAD

**Issue by vikaskedia** [odoo/odoo#16454]
Impacted versions: 10.0

Video/Screenshot link (optional): https://youtu.be/rMYSupw_Hd0

**Comment by Yenthe666** [comment]
Hi @vikaskedia,

Thank you for your report.
This is however default behaviour of Odoo. This is used by the Odoo developers to update (custom made) modules and it will always show upgrade, no matter what.

Regards,
Yenthe
