### ISSUE TITLE
Password displayed in clear in POS GUI with Firefox

### ISSUE THREAD

**Issue by yuntux** [odoo/odoo#16458]
Impacted versions: v9 at least

Steps to reproduce:
Launch Firefox 52 (and probably many other versions)
Launch a POS session and the POS GUI. Clic on the cashier name, select another cashier in the list.
The pinpad is displayed. Enter your pincode.

Current behavior:
=> this pincode is displayed in clear. Someone can read it over your shoulder.

Expected behavior:
=> big dots should be displayed instead of the pin value.

Actually we can found webkit-text-security CSS property in addons/point_of_sale/static/src/css/pos.css instead of a old and regular input type="password"

Video/Screenshot link (optional):
![image](https://cloud.githubusercontent.com/assets/8105921/25078285/c0be8950-2331-11e7-932e-91373ba4e7d8.png)

**Comment by Yenthe666** [comment]
Hi @yuntux,

Thank you for your report.
I've just tested this on the latest Odoo 9 (and FF 53) and I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/27131590-9b6567f2-510b-11e7-9db5-8e30734a7da6.png)
@jorenvo looks like one for you.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Thank you @jorenvo !
