### ISSUE TITLE
Leave management app -> Set user as employee -> fails silently (See video demo)

### ISSUE THREAD

**Issue by vikaskedia** [odoo/odoo#16455]
Impacted versions: 10.0

Video/Screenshot link: https://youtu.be/WpO0nzlV9z8

**Comment by Yenthe666** [comment]
Hi @vikaskedia,

Thank you for your report.
I've just tested this and the rights are indeed set back to the previous configured settings.
@mart-e I believe this is a bug. Can you have a look?

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Thank you for the report but it is not a bug.
Your user is already holidays manager. To be able to be holidays manager, you need to be holidays officer. And to be holidays officer, you need to be HR officer.

![screenshot from 2017-05-08 13-58-20](https://cloud.githubusercontent.com/assets/564822/25803291/6f7991ea-33f6-11e7-9c61-91c4160bb47a.png)

You can not be one without the order.
