### ISSUE TITLE
Bug on receipt of multiple AVCO valued items

### ISSUE THREAD

**Issue by jchaedles** [odoo/odoo#164651]
This last PR creates a bug. change 'self.uom_id' to 'product.uom_id' in _run_fifo_vaccum

            # if product.cost_method == 'average' and not float_is_zero(product.quantity_svl, precision_rounding=self.uom_id.rounding): <--------------------------

_Originally posted by @jchaedles in https://github.com/odoo/odoo/issues/157558#issuecomment-2096957075_

**Comment by vava-odoo** [comment]
Thanks @jchaedles it was fixed with https://github.com/odoo/odoo/commit/42f5e84eeb1d649feed5e032d65ff74d148b49b8
