### ISSUE TITLE
[10.0] mail.thread: Mixin on creation vals injection inheritance

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#16468]
**Impacted versions:** 9.0 and later

**Steps to reproduce:**

We have a model which is inheriting the mixin ```mail.thread``` and we try to inherit the model somewhere else.

```python
    @api.model
    def create(self, vals):
        print vals.get('message_follower_ids') # False
        res = super(ModelClass, self).create(vals)
        print vals.get('message_follower_ids') # Now we have these injected data in our vals
        # Why is this needed or let's call it injected in case of inheritance?
        del vals['message_follower_ids']
        # Only if you delete the injected vals you will be able to avoid the sql constraint
        # It is not important that we do write the object we have just created ;-)
        res.write(vals)
        return res
```

**Current behavior:**
An injection of the ```message_follower_ids``` in the vals

**Expected behavior:**
Do we really need to remove it manually or should the mechanism avoid such a magical injection?
I would expect that the variable ```vals``` stays unmodified locally and is not changed by any other mechanism.

@rco-odoo @tde-banana-odoo 
Are you aware of this behavior? 
Do I miss something why this behavior is wanted and expected?

@mart-e @nim-odoo 
https://github.com/odoo/odoo/issues/15589 is probably a different issue but as you said that you will investigate...this is what I mentioned and did not yet receive an answer to.

**Comment by mart-e** [comment]
Hello,

The dicts are mutable, so if the `create` method of `mail.thread` do something like:
```python
@api.model
def create(self, values):
    values['message_follower_ids'] = ...
    return super(MailThread, self).create(values)
```

You will get a `message_follower_ids` key outside of the create method. Most of the `create` and `write` override do the same ([account](https://github.com/odoo/odoo/blob/7591f59c5e769c78d55dc0336b1b4b5c700ea315/addons/account/models/account.py#L416), [crm](https://github.com/odoo/odoo/blob/7591f59c5e769c78d55dc0336b1b4b5c700ea315/addons/crm/crm_lead.py#L891), [project](https://github.com/odoo/odoo/blob/7591f59c5e769c78d55dc0336b1b4b5c700ea315/addons/project/project.py#L330),...).

I don't think this should have any impact and I think I have already even seen code using this mechanism (but not very clean, I agree on that).

A simple way to change that is via `values = dict(values)` as the first line of the create method but it means it should be done in every method, so a bit cumbersome.

**Comment by wtaferner** [comment]
**Thank you Martin for the explanation.** 

**Could this be done on a framework level what you suggest on the first line of each create, write method?** The issue obviously only happend in create as the ```Many2many``` value field syntax does not care if I create the object or write it with the ```vals``` given as it will always try to create the followers.

**Maybe there is another rationale why it must be like that?**

I am just curious as this issue can easily occur while inheriting and not taking care of this extra line one way or the other and feels as said a bit like magic and we only do love magic if we own it or completely understand the rationale :rofl:

**Comment by mart-e** [comment]
> Could this be done on a framework level what you suggest on the first line of each create, write method? 

You could do it but it the ORM is called the last so you don't catch all the overrride where you can do, pretty much whatever you want.
In the old-new API transfer period, we had wrapper methods between each calls where you could do things like this (we turned `context` into `frozendict` for instance) but I don't see how to do so in master.
Maybe @rco-odoo has an idea?

**Comment by wtaferner** [comment]
@rco-odoo 
Just found this issue where @mart-e was asking for you input. It is still appreciated and maybe @Yenthe666 can tag this as framework and wishlist? As it is about mixins I also ping @tde-banana-odoo :-) Mention party for everyone ;-)

**Comment by Yenthe666** [comment]
Ofcourse I can! Let us wait what on what @rco-odoo suggests.
