### ISSUE TITLE
[10.0] User privileges with errors

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#16471]
Impacted versions: v10 Enterprise and v10 Community

Steps to reproduce:
1. Create a user (or use any non-superadmin)
2. Assign any role / privilege. ie.: Have it as an employee or even a manager in Human Resources.
3. Double check that you really are in that group.
4. Go to Calendar.
5. Create a meeting and invite external partners (any non-internal user) and set a reminder.

To go even further:
1. Create a rule in Access List.
2. Try again.

Current behavior:
Odoo shows an error saying that only Employees/Employee has the ability to do that action.

If we do it in Multi-Company the behavior is even worse as it gives more errors on more objects.

This isn't happening only to us, other users in different instances are also experiencing the same issue on different objects. Some of them in CRM, others in Accounting, etc...

Expected behavior:
Allow the user to perform the action for which he has privileges.

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Where you able to reproduce this on a runbot too?
Could you perhaps make a little video simulating it? Couldn't get this right away.

Regards,
Yenthe

**Comment by edsersolis** [comment]
This seems to have been fixed in later updates. Tried to reproduce it but was everything working good.

If anything will open it again. Thanks.
