### ISSUE TITLE
L10n_ma acoount model name

### ISSUE THREAD

**Issue by abenzbiria** [odoo/odoo#165]
Hi ,
Please can you change account model name :+1: 
l10n_ma/l10n_ma_tax.xml:741:        <field name="name">compta Kazacube</field>

best regards

**Comment by Yenthe666** [comment]
Dear @abenzbiria,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
