### ISSUE TITLE
[17.0][SEC] CVSS 7.5 SBOM Dep. werkzeug 2.0.2 vulnerabilities

### ISSUE THREAD

**Issue by wilsonmar** [odoo/odoo#165044]
After obtaining dependency SBOM from odoo v17.0 at 6f6763b
Run of 
osv-scanner scan -S odoo_odoo_6f6763b6728335b0728645806d77a0cb7453ffc7.json
reported vulnerabilities identified at:
╭─────────────────────────────────────┬──────┬
│ OSV URL                             │ CVSS │
├─────────────────────────────────────┼──────┼
│ https://osv.dev/GHSA-2g68-c3qc-8985 │ 7.5  │
│ https://osv.dev/GHSA-hrfv-mqp8-q5rw │ 7.5  │
│ https://osv.dev/PYSEC-2023-221      │      │
│ https://osv.dev/GHSA-px8h-6qxv-m22q │ 2.6  │
│ https://osv.dev/PYSEC-2023-57       │      │
│ https://osv.dev/GHSA-xg9f-g7g7-2323 │ 7.5  │
│ https://osv.dev/PYSEC-2023-58       │      │
│ https://osv.dev/PYSEC-2022-203      │      │

**Comment by mart-e** [comment]
Same as https://github.com/odoo/odoo/issues/165042#issuecomment-2107180760, need proof it is applicable and not the proper report channel.
