### ISSUE TITLE
Wrong Content-Type in calendar email

### ISSUE THREAD

**Issue by fohnbit** [odoo/odoo#16502]
When a meeting in the calendar is set and saved, a Email with the inviting is send. The Attachment "invitation.ics" did Thundbird not recognized as Calendar Event, because I guess the Mimetyp is wrong.
Another Email from another system work, and there is the attachemt as "text/calendar" set.

**Impacted versions:**
odoo 10

**Steps to reproduce:**
setup a new meeting in the calendar and save. Let the system send the Email for inviting

**Current behavior:**
In the Email the Attachement "invitation.ics" has the following Content-Type:
MIME-Version: 1.0
Content-Type: application/octet-stream; name="invitation.ics"
Content-Disposition: attachment; filename="invitation.ics"
Content-Transfer-Encoding: base64

**Expected behavior:**
MIME-Version: 1.0
Content-Type: **text/calendar**; name="invitation.ics"
Content-Disposition: attachment; filename="invitation.ics"
Content-Transfer-Encoding: base64

**Comment by fohnbit** [comment]
done:
https://github.com/odoo/odoo/commit/b6c4fbcc010583b8632f864344e02f3310e7791f#diff-44a85c08f66fadc8c3adbd83cac3b666

:-)

**Comment by Yenthe666** [comment]
This has been handled & fixed in upper versions so this should have been closed.
