### ISSUE TITLE
[17.0][SEC] CVSS 8.1 SBOM Dep. urllib3 1.26.5 vulnerabilities

### ISSUE THREAD

**Issue by wilsonmar** [odoo/odoo#165045]
After obtaining dependency SBOM from odoo v17.0 at 6f6763b
Run of 
osv-scanner scan -S odoo_odoo_6f6763b6728335b0728645806d77a0cb7453ffc7.json
reported vulnerabilities identified at:
╭─────────────────────────────────────┬──────┬
│ OSV URL                             │ CVSS │
├─────────────────────────────────────┼──────┼
│ https://osv.dev/GHSA-g4mx-q9vg-27p4 │ 4.2  │
│ https://osv.dev/PYSEC-2023-212      │      │
│ https://osv.dev/GHSA-v845-jxx5-vc9f │ 8.1  │
│ https://osv.dev/PYSEC-2023-192      │      │

**Comment by mart-e** [comment]
Same as https://github.com/odoo/odoo/issues/165042#issuecomment-2107180760, need proof it is applicable and not the proper report channel.
