### ISSUE TITLE
[17.0][SEC] CVSS 6.2 SBOM Dep. Dependency idna 2.10 could consume significant resources, leading to a denial-of-service

### ISSUE THREAD

**Issue by wilsonmar** [odoo/odoo#165051]
After obtaining dependency SBOM from odoo v17.0 at 6f6763b
Run of 
osv-scanner scan -S odoo_odoo_6f6763b6728335b0728645806d77a0cb7453ffc7.json
reported vulnerabilities identified at:
```
╭─────────────────────────────────────┬──────┬──────────────┬────────
│ OSV URL                             │ CVSS │ PACKAGE      │ VERSION
├─────────────────────────────────────┼──────┼──────────────┼────────
│ https://osv.dev/GHSA-jjg7-2v4v-x38h │ 6.2  │ idna         │ 2.10   
```

**Comment by mart-e** [comment]
Same as https://github.com/odoo/odoo/issues/165042#issuecomment-2107180760, need proof it is applicable and not the proper report channel.
