### ISSUE TITLE
Inability to update data records in inherited module

### ISSUE THREAD

**Issue by gohigh19** [odoo/odoo#165080]
Impacted versions: 16.0

Steps to reproduce:
1. Inherit the Recruitment Module in a Custom Module.
2. Try to updating the xml records by defining now one with the XML ID.
3. Also Try updating the xml security group data by defining a new one with the same XML ID.

Current behavior:
It refuse to update.

Expected behavior:
You suppose to see change in the data

**Comment by Ngquang** [comment]
It will depend on the `noupdate="1"` is set on the target xml that you want to update.

**Comment by gohigh19** [comment]
> It will depend on the `noupdate="1"` is set on the target xml that you want to update.

I set noupdate="0" in the target xml just to see but it still wouldn't update.

**Comment by vava-odoo** [comment]
Hello @gohigh19 
If the parent record was declared as noupdate, you need to change that in the `ir_model_data` table (see 
https://github.com/odoo/upgrade-util/blob/d4a608c0accd70f1eefa1760f5ea2811d9ff61c8/src/util/records.py#L733-L758)
Cheers
