### ISSUE TITLE
[10.0] Error when printing financial reports

### ISSUE THREAD

**Issue by mpamped** [odoo/odoo#16515]
**Impacted versions:** 10.0 Community from Git fbbe9b54d4bcf2113efeeb189f616837df1d3367

**Steps to reproduce:**
Go to Accounting -> Configuration -> Account Reports -> Account Reports
Select "Balance sheet" (or any other report) and click on "Print" -> "Account report"
(The labels of buttons and menu items may be slightly off since I've translated them from my Dutch installation).

**Current behavior:**

The following error shows up:
```
Odoo Server Error

Traceback (most recent call last):
  File "/srv/odoo-dev/odoo-10.0/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/srv/odoo-dev/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo-dev/odoo-10.0/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/srv/odoo-dev/odoo-10.0/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/srv/odoo-dev/odoo-10.0/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/srv/odoo-dev/odoo-10.0/addons/account/report/account_report_financial.py", line 148, in render_html
    docs = self.env[self.model].browse(self.env.context.get('active_id'))
  File "/srv/odoo-dev/odoo-10.0/odoo/api.py", line 752, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/srv/odoo-dev/odoo-10.0/odoo/modules/registry.py", line 170, in __getitem__
    return self.models[model_name]
KeyError: None
```

**Expected behavior:**

PDF download with balance sheet.

**Comment by Yenthe666** [comment]
Hi @mpamped,

Thank you for your report.
I've just tested this on the latest Odoo 10.0 but cannot reproduce this issue? Example:
![image](https://cloud.githubusercontent.com/assets/6352350/25653647/23d3c2b2-2fee-11e7-9110-5f1f641ccf99.png)
The report:
![image](https://cloud.githubusercontent.com/assets/6352350/25653651/2e28b3a8-2fee-11e7-904f-61d96b51b112.png)

Could you add some more information or screenshots on how to reproduce this please?
Can you reproduce it on an official runbot? (runbot.odoo.com)

Regards,
Yenthe

**Comment by mpamped** [comment]
Hi Yenthe,

Thanks for looking into this issue!

I'm referring to the balance sheet from another menu option, see screenshot:
![print_balance_sheet1](https://cloud.githubusercontent.com/assets/26384590/25654260/b6498ba2-2ff0-11e7-8f4a-41195d4ecbdc.png)

When clicking the button marked red, I get the following error:
![print_balance_sheet2](https://cloud.githubusercontent.com/assets/26384590/25654447/4f7a0360-2ff1-11e7-8799-1128ea89e256.png)

This is with Git commit 4a0f9da2e10b4ad6ead202b964f4607ef4343975.

Let me know if you want me to reproduce this on runbot, I will figure out how to do it there.

Kind regards,
- Matthias

**Comment by Yenthe666** [comment]
Hi @mpamped,

Alright, thank you for the extra information!
This is indeed a bug in the latest Odoo 10:
![image](https://cloud.githubusercontent.com/assets/6352350/25655156/320d26b0-2ff4-11e7-98b4-11b174aa5c96.png)
@nim-odoo could you have a look at this?

Regards,
Yenthe

**Comment by alfaser123** [comment]
hi. Any solution so far?

**Comment by eyonatan** [comment]
@Yenthe666 @nim-odoo any updates on this? 
@alfaser123 Did you find a solution for this problem?
Thanks.

**Comment by Yenthe666** [comment]
No update yet - I'll create a new bug report under https://www.odoo.com/nl_NL/help with an enterprise license to try and speed this up.

**Comment by alfaser123** [comment]
I found that printing in the mentioned option  is not the way: 
![image](https://user-images.githubusercontent.com/29344513/28394768-0d1dfe08-6cb5-11e7-81c5-1cac4b221a37.png)

nevertheless we can get printed reports made in the same view. this is the work around:

1-set the report as you desire on the view (my address)
http://192.168.0.130:8094/web?debug=1#min=1&limit=80&view_type=list&model=account.financial.report&menu_id=342&action=175
2-Once you have set parents, views, etc for your report structure you can visualize it and print them in the menu inside of accounting/ reports /pdf reports

![image](https://user-images.githubusercontent.com/29344513/28394939-0d6edf84-6cb6-11e7-8d60-322283f5ea68.png)

hope it helps

**Comment by eyonatan** [comment]
Thanks for info, much appreciated. Quick questions:

1. I created the new report by going to Configuration --> Financial Reports --> Account Reports and by setting the right parents, views, etc. But, when I go to Accounting --> Reports --> PDF Reports, I don't see the newly created report as you indicted in your screen shot(see the last screen shot below). I am not sure what I am doing wrong.

![image](https://user-images.githubusercontent.com/30110083/28410150-71e8d5de-6d45-11e7-9e22-d57aa5b78a01.png)

![image](https://user-images.githubusercontent.com/30110083/28410079-3abfd36e-6d45-11e7-9980-dc0182c62645.png)

![image](https://user-images.githubusercontent.com/30110083/28410193-8da943e4-6d45-11e7-9b89-5ba43ffb6f36.png)

2. Also, I am assuming you are generating PDF reports using this method. Have you found a way to generate Excel format?

Thanks again for your help.

**Comment by Yenthe666** [comment]
Hi @mpamped,

The error and traceback itself are fixed at https://github.com/odoo/odoo/commit/7a1d2d1c4caebba5bd69d63cff3d7824dfd5a7a6 and https://github.com/odoo/odoo/commit/df135166799ccafd49c2aa684bb0ff845af31b09
To get the data / report you need you should probably use accounting > reports > pdf report > balance sheet.

Regards,
Yenthe
