### ISSUE TITLE
Payment Refund Functionality Issue

### ISSUE THREAD

**Issue by victoria-havi** [odoo/odoo#165184]
Impacted versions: 17

Steps to reproduce:
By default, the Type of Refund Supported field is empty this prevents the refund button from appearing.
1. Pay the invoices via Payment Providers (such as Stripe)
2. Navigate to Customer > Payments and select the successful payment
3. The refund button is missing.

Current behavior: When attempting to process a refund through a Payment Provider (e.g., Stripe) for an invoice, the system currently requires a payment method to have a specific refund type ("Partial" or "Fully Only") from the "Type of Refund Supported" field before the refund button becomes available.

This functionality is incorrect because leaving the field empty should allow users to process both full and partial refunds.

Expected behavior: The system should allow users to leave the "Type of Refund Supported" field blank. When empty, the system should understand that both full and partial refunds are possible.

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/142771724/2b3a479b-305d-4bcb-b998-a36b6b68ed83)

Support ticket number submitted via odoo.com/help (optional):

**Comment by halecorp** [comment]
Also noticed this. Can’t process a refund from odoo with stripe
