### ISSUE TITLE
Convert datePicker UI to jalali in Odoo 8

### ISSUE THREAD

**Issue by MortezaAghili** [odoo/odoo#16510]
i'm using odoo 8 for our team and we need to implement Jalali(Persian) calendar for our customers, we've added one module that converts picked gregorian date to jalali, but in the UI we see Gregorian Calendar but in the input we see Persian date.

* This is the datePicker UI  
[![enter image description here][1]][1]

 
* This is selected date (Persian)  
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/ZRwH7.png
  [2]: https://i.stack.imgur.com/MeT9h.png

**Comment by Yenthe666** [comment]
Hi @MortezaAghili,

Thank you for your report.
The Github issue tracker however is only for bugs in the official code and not for custom development or questions.
Please post your question on the official help forums (http://odoo.com/help).

Regards,
Yenthe

**Comment by saeed-raeisi** [comment]
https://github.com/odoo/odoo/issues/73599
