### ISSUE TITLE
Custom Module not loaded 

### ISSUE THREAD

**Issue by Valentin-Go-Flow** [odoo/odoo#165188]
Hello dear Odooers, 

Please have mercy for a newbie. 

I'm following the a dev. path to become a Odoo developer. But I ran in a small issue, when I run my Odoo 16 localhost I get this; 

2024-05-13 07:18:24,247 8248 WARNING mylibrary odoo.modules.graph: module my_library: not installable, skipped
2024-05-13 07:18:24,299 8248 ERROR mylibrary odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['my_library']

I have checked 
1. The manifest, "depends" has "base" 
2. The init of the module has "from . import models"
3. The init in the directory "models" has "from import xxx_model"
4. Every model has "from odoo import models, fields" and "xxx_model(mpdels.Model)

I hope it's clear and thanks for your help

**Comment by Ngquang** [comment]
> 2024-05-13 07:18:24,247 8248 WARNING mylibrary odoo.modules.graph: module my_library: not installable, skipped

I think you missing `'installable': True` in manifest

> 2024-05-13 07:18:24,299 8248 ERROR mylibrary odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['my_library']

This probably cause by `"from import xxx_model"` while it should be `"from . import xxx_model"`

It's better if you can screenshot your extension modules structure.

**Comment by Valentin-Go-Flow** [comment]
![capture_240513_105223](https://github.com/odoo/odoo/assets/157354643/042783c1-dbdc-4fd1-8f11-7e933bbe4868)
![capture_240513_105239](https://github.com/odoo/odoo/assets/157354643/7ca65aca-e2c8-4252-9510-3ecc39be0f91)
![capture_240513_105305](https://github.com/odoo/odoo/assets/157354643/3463e8a5-1af4-42cc-964c-7281a3163ca0)
