### ISSUE TITLE
[8.0] Improvement: act_window add option to make Searchview sticky in Tree/Kanban Views

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#1652]
Hello,

I'd like to suggest to add an option to act_window which makes the Searchview sticky (like in Graph Views) in Tree/Kanban Views, so the User doesn't have to click the Search "drilldown" Arrow each time the View is opened.

with kind regards,
Sven

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: As it is labelled wishlist it will keep popping up.

Regards,
Yenthe
