### ISSUE TITLE
Digits ignored on overriden function field of float type

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#16526]
Impacted versions:
At least v8

Steps to reproduce:
Set the digits or digits_compute to something like (3, 6) on the volume field in a new module for product.product and product.template

Current behavior:
Precision is taken into account in the form and a onchange event will return and modify the value correctly in the form. When saving the form, the volume of a product_template will be rounded to two digits. For example, if you set 0.005, it will save 0.01

Expected behavior:
The value saved should be exactly as in the form.

My observations:

The problem is caused because volume is a function field. In Odoo8 if I set a field like this:

    fields.Float(
        digits_compute=dp.get_precision("Product Volume"),
        digits=dp.get_precision("Product Volume")
    )

It will correctly compute the value for the float field, but for some reasons when it gets into the function method and then try to store the value, it gets the precision of the function field and not from the field instance with the V8 API. By default, odoo seems to round with these digits (16, 2). 

It seems like the function field should reuse the digits from _inherited models.

**Comment by Yenthe666** [comment]
Hi @llacroix,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
