### ISSUE TITLE
Download button missing from messages with more than one attachment

### ISSUE THREAD

**Issue by jacobaul** [odoo/odoo#165301]
Impacted versions:17.0

Steps to reproduce: Create a chatter message with multiple attachments in a single message

Current behavior: Other users see only the delete button on the chatter messages. A CSS class is missing on the attachment card to show both the download button and the delete button together. The result is that even the the user should be able to download the attachment, there is no way to do so without using the browser's dev tools to see the hidden HTML.

Expected behavior: The download button appears on the attachment card in the chatter message, including for messages with more than one attachment.

The offending commit appears to be [this one](https://github.com/odoo/odoo/commit/32a80a3ce1b2cbc46b1fc20f96b82256639beb9f). 

 [The issue is that the attachment.isDeletable disagrees with showDelete in this div.](https://github.com/odoo/odoo/blob/d22f38ece7fd70181e28513f7f4d7678e7809f70/addons/mail/static/src/core/common/attachment_list.xml#L73)

The result is that it does not add the 'o-hasMultipleActions d-flex flex-column' classes, even thought the delete button is rendered. This breaks the HTML and overlays the delete button on top of the download button. This is only true for multiple attachments due to the check in showDelete on the number of attachments

**Comment by chgo-odoo** [comment]
Hello @jacobaul, thanks for reporting this issue !

I've linked a pull request that will solve the problem once deployed. It should be available on Monday.

Have a nice day ! 🙂

**Comment by chgo-odoo** [comment]
Hello @jacobaul, sorry for the late follow up !

I linked a pull request that was merged yesterday and fixes the encountered issue. The fix will be available on Monday on your database.

Thanks for your patience and I wish you a great weekend 🙂

**Comment by reth-odoo** [comment]
Original linked PR also merged, to fix in JS in case updating the views is an issue.
Cheers
