### ISSUE TITLE
[17.0 16.0 15.0] Vimeo samples used by Odoo are not working

### ISSUE THREAD

**Issue by kanda999** [odoo/odoo#165322]
Impacted versions: 17.0 16.0 15.0

Steps to reproduce:
1, Put a snippet in Edit Website 
2, Select video as background 
3, Select vimeo used by odoo as a sample

Current behavior:
Most of the videos are set to require signing in to view them.
Previously, these sample videos suggested by Odoo were used on the website, but they are no longer functioning.

It is possible to view the videos by signing in, but it is unacceptable for all customers visiting the website to have to sign in to Vimeo

The sample seems to be determined in the following code, but most of them do not work.
https://github.com/odoo/odoo/blob/0d1399d06bd5ab30918b1a84abccb0f44504a508/addons/web_editor/static/src/js/editor/snippets.options.js#L1960-L1961

Expected behavior:
We can use the video Odoo is using as a sample on our website.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1X1njH_LMsdhVQ80TVvXJ5b-D8xH3BWPc/view?usp=drive_link

Support ticket number submitted via odoo.com/help (optional):
OPW3926711

@qrtl QT4050

**Comment by chgo-odoo** [comment]
Hello @kanda999 thanks for the report and providing that much context !

The preview seems indeed broken as the videos look like private now. I've linked a pull request that should fix the issue by adding new videos ids.

Have a good day ! 🙂

**Comment by chgo-odoo** [comment]
Just landed on Master 🚀

The preview samples are now fixed starting from Odoo 15 to Master.

Thanks again for reporting this issue and have a nice day 🙂
