### ISSUE TITLE
[10.0] Translations for email templates not fully loading

### ISSUE THREAD

**Issue by I7Soltys** [odoo/odoo#16543]
In email templates translation files (.po) dont change dynamically calculated parts, for example in purchase order rfq email template we have part like this 
${object.state in ('draft', 'sent') and 'request for quotation' or 'purchase order confirmation'}
and if we change it in .po file to for something like this 
${object.state in ('draft', 'sent') and 'zamowienie' or 'potwierdzenie'} 
then it wont change. No matter what language you choose the request for quotation wont change and always will be the same.
It seems like parts in ${} are not translatable but should.

**Comment by mart-e** [comment]
Hello,

You are talking about changing in .po file but this is only the static files. You need to reload the translations after making your change.
When updating your translations, you need to make sure you check the "override terms" option (visible only in debug mode).

I am closing this issue as github is to report bugs on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
