### ISSUE TITLE
[10]TypeError: Model 'ir.qweb.widget.precision' and AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context'

### ISSUE THREAD

**Issue by Grfokpr** [odoo/odoo#16548]
Starting new database on brandnew Odoo10 installation , all requirements are up to date. getting first error then second but instance is still running but i can't access it trough localhost.
Running server with ./odoo-bin  

2017-04-20 21:23:13,417 18610 ERROR new_10 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 131, in load_module_graph
    model_names = registry.load(cr, package)
  File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 261, in load
    model = cls._build_model(self, cr)
  File "/home/grf/vcs/odoo/odoo/models.py", line 540, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
TypeError: Model 'ir.qweb.widget.precision' inherits from non-existing model 'ir.qweb.widget'.
2017-04-20 21:23:13,418 18610 ERROR new_10 odoo.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/home/grf/vcs/odoo/odoo/service/db.py", line 49, in _initialize_db
    registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
  File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 131, in load_module_graph
    model_names = registry.load(cr, package)
  File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 261, in load
    model = cls._build_model(self, cr)
  File "/home/grf/vcs/odoo/odoo/models.py", line 540, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
TypeError: Model 'ir.qweb.widget.precision' inherits from non-existing model 'ir.qweb.widget'.

2017-04-20 21:23:26,526 18610 ERROR new_10 werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/grf/vcs/odoo/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/grf/vcs/odoo/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/grf/vcs/odoo/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/grf/vcs/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/home/grf/vcs/odoo/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/grf/vcs/odoo/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/home/grf/vcs/odoo/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/home/grf/vcs/odoo/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/home/grf/vcs/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/grf/vcs/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/grf/vcs/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/grf/vcs/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/grf/vcs/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/grf/vcs/odoo/addons/web/controllers/main.py", line 440, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context'

**Comment by diwap** [comment]
this happens when you initialize two database at once by running the server with two different port.

**Comment by Yenthe666** [comment]
Hi @Grfokpr,

I was no longer able to reproduce this issue.
If you still face this issue then please update to the latest Odoo source code and try again.

Regards,
Yenthe

**Comment by Septiembre19** [comment]
![imagen](https://user-images.githubusercontent.com/10567541/73298668-bc3d5200-41db-11ea-881d-8138867921b0.png)

I have that same error

**Comment by Septiembre19** [comment]
I have that error.
Odoo.sh, Version 13, development branch.

**Comment by isgmthazin** [comment]
I found that error v12.0c and v13.0c :( on mach

**Comment by yondion** [comment]
any update on this?

**Comment by yondion** [comment]
> Starting new database on brandnew Odoo10 installation , all requirements are up to date. getting first error then second but instance is still running but i can't access it trough localhost.
> Running server with ./odoo-bin
> 
> 2017-04-20 21:23:13,417 18610 ERROR new_10 odoo.modules.registry: Failed to load registry
> Traceback (most recent call last):
> File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 78, in new
> odoo.modules.load_modules(registry._db, force_demo, status, update_module)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 339, in load_modules
> loaded_modules, update_module)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
> loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 131, in load_module_graph
> model_names = registry.load(cr, package)
> File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 261, in load
> model = cls._build_model(self, cr)
> File "/home/grf/vcs/odoo/odoo/models.py", line 540, in _build_model
> raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
> TypeError: Model 'ir.qweb.widget.precision' inherits from non-existing model 'ir.qweb.widget'.
> 2017-04-20 21:23:13,418 18610 ERROR new_10 odoo.service.db: CREATE DATABASE failed:
> Traceback (most recent call last):
> File "/home/grf/vcs/odoo/odoo/service/db.py", line 49, in _initialize_db
> registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
> File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 78, in new
> odoo.modules.load_modules(registry._db, force_demo, status, update_module)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 339, in load_modules
> loaded_modules, update_module)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
> loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
> File "/home/grf/vcs/odoo/odoo/modules/loading.py", line 131, in load_module_graph
> model_names = registry.load(cr, package)
> File "/home/grf/vcs/odoo/odoo/modules/registry.py", line 261, in load
> model = cls._build_model(self, cr)
> File "/home/grf/vcs/odoo/odoo/models.py", line 540, in _build_model
> raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
> TypeError: Model 'ir.qweb.widget.precision' inherits from non-existing model 'ir.qweb.widget'.
> 
> 2017-04-20 21:23:26,526 18610 ERROR new_10 werkzeug: Error on request:
> Traceback (most recent call last):
> File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
> execute(self.server.app)
> File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
> application_iter = app(environ, start_response)
> File "/home/grf/vcs/odoo/odoo/service/server.py", line 246, in app
> return self.app(e, s)
> File "/home/grf/vcs/odoo/odoo/service/wsgi_server.py", line 184, in application
> return application_unproxied(environ, start_response)
> File "/home/grf/vcs/odoo/odoo/service/wsgi_server.py", line 170, in application_unproxied
> result = handler(environ, start_response)
> File "/home/grf/vcs/odoo/odoo/http.py", line 1306, in **call**
> return self.dispatch(environ, start_response)
> File "/home/grf/vcs/odoo/odoo/http.py", line 1280, in **call**
> return self.app(environ, start_wrapped)
> File "/home/grf/virtualenv/odoo/10.0/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in **call**
> return self.app(environ, start_response)
> File "/home/grf/vcs/odoo/odoo/http.py", line 1471, in dispatch
> result = ir_http._dispatch()
> File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
> return cls._handle_exception(e)
> File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
> return request._handle_exception(exception)
> File "/home/grf/vcs/odoo/odoo/http.py", line 766, in _handle_exception
> return super(HttpRequest, self)._handle_exception(exception)
> File "/home/grf/vcs/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
> result = request.dispatch()
> File "/home/grf/vcs/odoo/odoo/http.py", line 825, in dispatch
> r = self._call_function(**self.params)
> File "/home/grf/vcs/odoo/odoo/http.py", line 331, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "/home/grf/vcs/odoo/odoo/service/model.py", line 119, in wrapper
> return f(dbname, *args, **kwargs)
> File "/home/grf/vcs/odoo/odoo/http.py", line 324, in checked_call
> result = self.endpoint(*a, **kw)
> File "/home/grf/vcs/odoo/odoo/http.py", line 933, in **call**
> return self.method(*args, **kw)
> File "/home/grf/vcs/odoo/odoo/http.py", line 504, in response_wrap
> response = f(*args, **kw)
> File "/home/grf/vcs/odoo/addons/web/controllers/main.py", line 440, in web_client
> context = request.env['ir.http'].webclient_rendering_context()
> AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context'

hello, are you solve on this issues?

**Comment by willmakenoise** [comment]
I'm getting the same error trying to install Odoo 13.
I have two postgres clusters running on the server, and have configured Odoo to use Postgres 13 by specifying db_port.

**Comment by Yenthe666** [comment]
@willmakenoise hmm I'd suggest creating an official ticket for it as I think you have an enterprise license probably? :) If you can reproduce it on a runbot too then do make a new ticket please.

**Comment by AmarZaya** [comment]
This is a issue with Python3.8.5. I solved this issue using python3.7.

**Comment by lethuthao2403** [comment]
> this happens when you initialize two database at once by running the server with two different port.

how to fix it. plz help me
