### ISSUE TITLE
[8.0] Search one2many and selection Fields

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#1654]
Hello,

In 6.1 it was possible to select one of the values from a one2many Field directly in the Search bar.
Example "Sales Team":
![image](https://cloud.githubusercontent.com/assets/3729082/3842225/812e71e6-1e35-11e4-95fd-6c5fb10b21c8.png)
Same for Tags (previous Categories), ...
1. This is now only possible with selection fields, but not anymore with one2many fields.
   You are forced to type something in the search box to filter, but you don't see the actual available records or values of the one2many Fields.
2. Additionally in 6.1 you could select one of those filters directly from the search bar without opening the advanced Filter which is the case for 8.0 and master.
   ![image](https://cloud.githubusercontent.com/assets/3729082/3877926/6b720484-216a-11e4-9eb9-006c939839e8.png)
   As far as I know it's not possible to put a selection Filter in the Filter space (red)...?

Regression?

with kind regards,
Sven

**Comment by Yenthe666** [comment]
Hi @svenpetersen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo Odoo 6, Odoo7 and Odoo 8 are no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
