### ISSUE TITLE
`ValueError` when attempting to calculate refundable amount for multiple payments

### ISSUE THREAD

**Issue by flexadecimal** [odoo/odoo#165537]
https://github.com/odoo/odoo/blob/c7d420b077490108794f513e9ff21b0d850f57af/addons/payment/models/account_payment.py#L54

RecordSet usage error - should be `payment.id` in domain used for search.

**Comment by vava-odoo** [comment]
Hi @flexadecimal 
Thanks for reporting. Issue was fixed with referenced PR.
Cheers
