### ISSUE TITLE
Cant Install app/modules

### ISSUE THREAD

**Issue by zsange** [odoo/odoo#16555]
Ive downloaded Odoo Web Login:
https://apps.odoo.com/apps/modules/9.0/odoo_web_login/#comments
Cant install it to my local server, Im using ubuntu 14.4 running in Eclipse IDE,
Tried to add to path: sudo nano /etc/openerp-server.conf
addons_path = /home/odoo/odoo9/addons,/home/odoo/odoo9/customaddons
Also paste the module in new create customaddons folder But still cant see in my module apps, Update list and in dev mode Need advise please

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
