### ISSUE TITLE
Order taxes not updated on partner change

### ISSUE THREAD

**Issue by gloaec** [odoo/odoo#16561]
Impacted versions:

8.0-20170228

Steps to reproduce:

1. Create a new order (purchase/sale)
2. Select partner (supplier/customer) that is subject to VAT
3. Add a new order_line
4. Change the partner (supplier/customer) to one that is not subject to VAT (or has a different taxation scheme)
5. Change the current or add a new order_line

Current behavior:

The taxes applied to the current/new order_line are not updated according to the selected partner (even though clicking "refresh").

Expected behavior:

The taxes should be updated on each and every order_line.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @gloaec,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
