### ISSUE TITLE
[8.0] Logrotate seems to miss a lot of lines when rotating

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#16566]
Impacted versions: seen on an 8.0 instance

Steps to reproduce: have odoo run with multiple workers and use log rotation

Current behavior: When closing one log and starting e new one, hours of loglines can go missing.

Expected behavior: All lines are properly logged.

Might be related to this problem noted here: http://stackoverflow.com/questions/34186774/why-doesnt-timedrotatingfilehandler-work-properly-and-how-to-solve-this-issuer

**Comment by StefanRijnhart** [comment]
See also https://www.odoo.com/nl_NL/forum/help-1/question/is-logging-safe-when-using-multiple-workers-43562. This should at least be documented.

**Comment by Yenthe666** [comment]
Hi @NL66278,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by agyamuta** [comment]
Hi Yenthe,
It looks like this issue exists on  Odoo v10.0 Enterprise version.
See image below. Thanks.

![image](https://user-images.githubusercontent.com/14207366/39065538-f5564726-4486-11e8-8515-b544224ac659.png)

**Comment by Yenthe666** [comment]
Hmm, interesting. Could you please make a new bug report for this with a step by step reproducible flow? I'll label it and then we can take it from there on with a clean bug report for a supported Odoo version.

**Comment by agyamuta** [comment]
Got this bug report. 
https://www.odoo.com/my/task/1838339

**Comment by Yenthe666** [comment]
Ah so you made an official Odoo ticket? Nice. It'll be handled there then.
