### ISSUE TITLE
[16.0] ValidationError don't apply translate using _

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [odoo/odoo#165676]
Impacted versions: 16.0

Steps to reproduce: Develop any ValidationError using _ to translate (i18n)

Current behavior: The translate is not applied, unless I use UserError

Expected behavior: Translation of the string after _

Video/Screenshot link (optional):
![image](https://github.com/odoo/odoo/assets/101650554/f03c6a25-b691-4510-9e2e-70cfb4bb07ba)

Support ticket number submitted via odoo.com/help (optional):

**Comment by ossimantylahti** [comment]
With all respecrt @igoroliveira-ax4b , this does not sound like Odoo defect. There are literally hundreds of raise ValidationErrors in Odoo code and their errors _are_ translated.

For example, in [addons/account/models/product.py](https://github.com/odoo/odoo/blob/76101bcfb36135b392e83e69f237154fbb84e1b9/addons/account/models/product.py#L4) a snippet:

```
raise ValidationError(_(
--
117 | "This product is already being used in posted Journal Entries.\n"

```

Is the module ax4b_budget developed by yourself? If so, it is at least located in incorrect location - the `addons` folder is for Odoo's own modules. Your custom modules should go to `custom` folder.
