### ISSUE TITLE
[10.0] Automated tests for sale failing if running them independently

### ISSUE THREAD

**Issue by akshayjain1996** [odoo/odoo#16579]
Impacted versions: 10.0, maybe others

Steps to reproduce:
Try running the automated tests for sale module independently, without any other modules installed. There is one failure for a tour.
./odoo-bin -d testdb --stop-after-init --test-enable --init sale.

Current behavior:
Tests have one failure.

Expected behavior:
Tests should pass

Stack Trace:
2017-04-23 05:48:03,766 31100 ERROR newtestdb odoo.addons.sale.tests.test_sale_ui: FAIL
2017-04-23 05:48:03,770 31100 ERROR newtestdb odoo.addons.sale.tests.test_sale_ui: FAIL: test_01_sale_tour (odoo.addons.sale.tests.test_sale_ui.TestUi)
2017-04-23 05:48:03,771 31100 ERROR newtestdb odoo.addons.sale.tests.test_sale_ui: FAILED

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e could you give feedback here?

**Comment by mart-e** [comment]
Hello,

Sorry but you did not show a bug in Odoo. The tests are written to work in a new database with demo data and no other user data. We run it on the [Odoo runbot](http://runbot.odoo.com/runbot) where you see that all tests are passed on all version.
Maybe your code is not up to date, maybe there is other data in your db, maybe it is a false positive (it happens with phantomjs that timesout from time to time).

Also, when reporting such errors, please give more context, past the full error to see what fails.

So don't worry, we see when the tests are failing, it is even on the wall of our office 😉

**Comment by akshayjain1996** [comment]
@mart-e Thanks for the reply. I have had a really hard time getting the automated tests to run, but now I finally have then running!

The tests are passing for me when I run it for ALL the modules (with all the configuration required like database with demo data and stuff). However, they fail when I try to run them for one module in isolation like sale.

**Comment by kurkop** [comment]
@akshayjain1996 I also have this error, I suspect the phantomjs version, in https://www.odoo.com/documentation/10.0/reference/javascript.html#running-through-python says that used 1.7, but in the npm packages are not avalaible. Do you have clues?

**Comment by akshayjain1996** [comment]
@kurkop I am using 2.1.1.

The problem I was facing was that the tests passes when I tried to run them for ALL modules, but failed when I only ran it for sales. Phantomjs issue should cause them to fail no matter what.

Did you try running all the tests?

**Comment by kurkop** [comment]
@akshayjain1996 fails when run all test and when only run sales test"
