### ISSUE TITLE
Extra_move not transfert to delivery

### ISSUE THREAD

**Issue by XtremXpert** [odoo/odoo#16577]
Impacted versions:10

Steps to reproduce:
create a sale (with pick/pack setting on)
go in inventory and in the pick, add a product not on the sale order and validate the picking.
you can see the extra move create to the picking

Current behavior:
the delivery picking show modify qty from original move but no trace of the product add at pick time

Expected behavior:
extra_move should also be created for delivery pick

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
I'm not sure i understand well the issue. If you have some chained move and in one of the picking you add some extra suff, you have to configure some push rules to propagate them downstream.

Regards
