### ISSUE TITLE
Odoo 10: Error with depreciation journal entry posting of asset in foreign currency

### ISSUE THREAD

**Issue by rajeeshknambiar** [odoo/odoo#16580]
Impacted versions:
Odoo CE 10
Steps to reproduce:
Install Asset management.
Create an asset with foreign currency (USD) while company currency is INR.
Compute depreciation entries.
Post the first deprecation entry.
Current behavior:
Error: The amount expressed in the secondary currency must be positive when account is debited and negative when account is credited.

Expected behavior:
Journal entry created
Video/Screenshot link (optional):
Not sure if this is related with https://github.com/odoo/odoo/issues/2294
This is my Asset type configuration:
![image](https://cloud.githubusercontent.com/assets/424259/25312803/5a858cda-2811-11e7-8152-240bf6efbbd4.png)

**Comment by Yenthe666** [comment]
@qdp-odoo this is probably for you?

**Comment by rajeeshknambiar** [comment]
I did some investigation — the category_id.journal_id is ‘Assets’ and category_id.journal_id.type is ‘general’. If the type is neither ‘purchase’ nor ‘sale’, then ‘sign’ is set as -ve. The depreciation account move lines are prepared as follows:

{'analytic_account_id': False, 'credit': 1726.23, 'name': u'SanDisk SSD 120GB SDSSDEXT\xad-120G\xad-G25 (1/6)', 'debit': 0.0, 'amount_currency': 25.65, 'currency_id': 3, 'partner_id': 32, 'journal_id': 11, 'account_id': 58}

{'analytic_account_id': False, 'credit': 0.0, 'name': u'SanDisk SSD 120GB SDSSDEXT\xad-120G\xad-G25 (1/6)', 'debit': 1726.23, 'amount_currency': -25.65, 'currency_id': 3, 'partner_id': 32, 'journal_id': 11, 'account_id': 86}

This of course, results in the account_move error.
So, what is the correct process to follow here?

**Comment by rajeeshknambiar** [comment]
Any update on this?

**Comment by pedrobaeza** [comment]
@qdp-odoo can you tell us about this?

**Comment by qdp-odoo** [comment]
well, probably fixed by this commit, since the 29th of March 2017 https://github.com/odoo/odoo/commit/989d7068e9fc210350cc4531e8f757364363d40d
