### ISSUE TITLE
Work Orders are not scheduled by allowed Working Time

### ISSUE THREAD

**Issue by traviswaelbro** [odoo/odoo#16583]
**Impacted versions:** 

- 9 community/enterprise
- 10 community/enterprise

**Steps to reproduce:** 

- Configure at least one Working Time entry
- Assign the Working Time entry to each Workcenter
- Configure product(s) with the following:
    - Use Manufacture and Make to Order Routes
    - Set at least 1 day for Manufacturing Lead Time
    - Create a Bill of Materials with a Routing which uses operation(s) at a workcenter that has Working Time set up
- Create and Confirm a Sales Order for the product(s)
- Review *Deadline Start* date/time on the Manufacturing Order that was automatically created

**Current behavior:** 

Manufacturing Orders are scheduled for any day (including weekends and off-hours) based on the lead times and due dates.

**Expected behavior:** 

Manufacturing/Work Orders should only be scheduled for days/hours which are set on the Working Time for the given workcenter.

**Comment by Yenthe666** [comment]
@sle-odoo and @jco-odoo any update on this one?

**Comment by travs-w** [comment]
@jco-odoo Then, I guess my biggest question is: what are Working Days used for? It doesn't seem to have any real functionality other than a reference for a user to look at.

**Comment by pedrobaeza** [comment]
Reading comments, we can close this as not focused, but partially answered. If you want to go for something more specific, please open a new issue.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
