### ISSUE TITLE
[10.0] Reference fields and union.

### ISSUE THREAD

**Issue by thomas15v** [odoo/odoo#16590]
Impacted versions:
10.0
Steps to reproduce:
Add a reference field to sale.order.line. And try to fill in these fields in a tree view.

Current behavior:
Odoo is trying to validate the model of Reference fields so it can pack everything in a single array. However the union method validates the model of these elements. Causing "TypeError: Mixing apples and oranges"

Expected behaviour:
I am not sure. But I guess a Reference fields shouldn't be handled as a Secondary field.

Picture:
![image](https://cloud.githubusercontent.com/assets/2163941/25328083/c4ccff2c-28d6-11e7-8f44-2646b809a258.png)
As you can see here as soon you got 2 different models in your Reference field. The error will occur.

**Comment by pedrobaeza** [comment]
This is a know limitation for reference fields for not being used in one2many tree views, so nothing to do here, except not using that. You can put in a the one2many form, or use it directly in the header.

Closing as won't fix for the low impact of this thing and the changes that will be needed to be done for having this working.
