### ISSUE TITLE
[master,8.0,7.0] missing tax on fees_lines in mrp_repair

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#1660]
addon : mrp_repair
1.Set a product with a tax (on its form)
2.Create a repair
3.In "Invoicing tab", on fees tree:
add a line, choose the product that you have set, the tax is not added.

Expected : the tax must be auto-filled when you add the product.

**Comment by Yenthe666** [comment]
Hi @rdeheele ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
