### ISSUE TITLE
[17.0] pos_hr: Impossible to login point of sale when 'Multi Employees per Session' is set

### ISSUE THREAD

**Issue by okelekemike** [odoo/odoo#166067]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Login as Admin
Go to point of sale (Dashboard)
Select the more options three dots and select Edit
Set 'Multi Employees per Session' to True and Save
Start a New Session
You will not be able to select a cashier to login to the session

**Comment by vava-odoo** [comment]
Hi @okelekemike 
Thanks for your report. It was solved with https://github.com/odoo/odoo/commit/27620deacdac027e333afb95e0a963cee9c5f3c4
Cheers
