### ISSUE TITLE
Portal users are not able to see About Us page in website

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#16616]
**Impacted versions:**
saas-14

**Steps to reproduce:**
1. Get inside website of the instance
2. Sign in as portal user
3. Click on the About us link to go to the About us page.

**Current behavior:**

![image](https://cloud.githubusercontent.com/assets/7593953/25362046/9f11640a-291f-11e7-8e68-2b5a160c2e99.png)

**Expected behavior:**

Be able to see the about us page as the non-logged-user does

![image](https://cloud.githubusercontent.com/assets/7593953/25362095/e98ea100-291f-11e7-8841-3d34eb35d715.png)

**Video/Screenshot link (optional):**

Here is a [video demonstration](https://youtu.be/FloO1IOqtUM) about what happen with portal user and also with: not logged users, internal user and admin user

**Comment by zaoral** [comment]
This issue is related to OPW 741077
Best Regards

**Comment by JKE-be** [comment]
update of website_hr is required to install the new permissions.

Thanks for the reporting.

**Comment by zaoral** [comment]
Thank you very much @JKE-be
This fix will be applied also to saas-14 branch?

**Comment by JKE-be** [comment]
Hello,

Yes, all commits from v10 are ported to other newest branch.
It will be probably done this week.

@zaoral 
But if you are on saas-14, you are probably on our saas, so if you provide me your domain, I can patch it manually inside your database meanwhile.

Best regards

**Comment by zaoral** [comment]
Hi @JKE-be 

We have a saas-14 instance, but I am afraid that this one is not running in your saas service.
I will apply the patch manually in our instance taking into account your words and waiting this fix be available for ssas-14 branch.

Thank you very much for your help.

Best Regards
