### ISSUE TITLE
[10.0] Allow users to sign in with Google - setting according to the instruction does not work

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#16613]
**Impacted versions:** 10

**Steps to reproduce:**
As written in the instructions Odoo.

**Current behavior:**
![screenshot_9](https://cloud.githubusercontent.com/assets/11208423/25359260/27868d2e-294d-11e7-9329-a06173a2cca4.png)

**Expected behavior:**
That everything would work.

Video/Screenshot link (optional):

I repeated it several times. Ten times I checked everything. Authorization does not work. All services from Google work, only this function does not work. Who connected this function, please write. Thanks for the help!

P.S. And yet I have the protocol https and everywhere in the settings https, in the screenshot why then http ?

**Comment by fmdl** [comment]
Dear,
Test this configuration
![image](https://cloud.githubusercontent.com/assets/16716992/25585873/f115e500-2e9c-11e7-881e-da823e9753e4.png)

**Comment by collex100** [comment]
Thank you so much! This setting is working.
