### ISSUE TITLE
[10.0] Inventory Adjustments does not respect product tracking setting

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#16627]
### Impacted versions:

Checked 10.0

### Steps to reproduce:

- Select either "By Unique Serial Number" or "By Lots" for Tracking field in product form
- In Inventory Adjustments, select the product try adjusting the quantity without entering Lot/Serial Number

### Current behavior:

Stock move is processed without Lot/Serial Number

### Expected behavior:

Error message should show to prompt Lot/Serial Number selection when "Validate Inventory" is pressed

### Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/7766939/25378202/4edf439a-29dc-11e7-8be0-4d8d1d723f35.png)

![image](https://cloud.githubusercontent.com/assets/7766939/25378422/a75b7a0c-29dc-11e7-96e8-9a5e9ba6f60d.png)

**Comment by Yenthe666** [comment]
Hi @yostashiro,

Thank you for your report.
This does indeed look like a bug to me. @mart-e should we add a check on the Lot/Serial numbers here?

Regards,
Yenthe

**Comment by janbec** [comment]
Hi @yostashiro,

I had the same issue while testing. Then checked SaaS16 and it seems the issue has been solved there. So maybe you can get an idea on how to solve hits for v10.

Best,
Jan

**Comment by sle-odoo** [comment]
Hi,
We support to have untracked quants for tracked products in your stock. It's done to solve the following usecases:
- only set the lot number on delivery (traceability only at stock output) and handling the returns of these products
- decide to track a products after multiple receipts

Regards

**Comment by yostashiro** [comment]
@sle-odoo 

> We support to have untracked quants for tracked products in your stock. It's done to solve the following usecases:
>
> * only set the lot number on delivery (traceability only at stock output) and handling the returns of these products
> * decide to track a products after multiple receipts

These sound to me like scenarios to create a mess in quants.  Thought it would be nice to at least make the described behavior optional. 


@janbec 

Thanks for your input, however I didn't get to witness the lot/serial enforcement in SaaS16 Runbot.  I might be missing something.

**Comment by sle-odoo** [comment]
@jco-odoo what's your opinion about this?

**Comment by janbec** [comment]
@yostashiro Sorry, you didn't miss anything. I was to quick with my testing..Behavior is like you described. With a unique serial number product, you can create stock for that product without entering a serial number (Runbot SaaS16).

In our case scenario, we don't want to look at serial numbers during inventory count. We are only checking if theoretical qty = real qty. Considering that you only get the theoretical qty when you enter a serial number, this might become a problem for us.

**Comment by jco-odoo** [comment]
I think we have the correct behaviour right now.  That way, an inventory adjustment can correct anything.  The case of @janbec is more specific.
