### ISSUE TITLE
[10.0] Access error when trying to set Demand Forecast in Master Production Schedule

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#16629]
### Impacted versions:

10.0

### Steps to reproduce:

- Enable MPS
- Add a product in MPS
- Try to update Demand Forecast when logged in with a user with Manufacturing Manager group

### Current behavior:

Access Error:

>Sorry, you are not allowed to create this kind of document. Please contact your system administrator if you think this is an error.
> 
> (Document model: sale.forecast)

### Expected behavior:

No such error.

### Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/7766939/25379720/958ac9f0-29e0-11e7-9c76-8a3697f57bd2.png)

There is only one access control record for `sale.forecast` which only grants read access.

![image](https://cloud.githubusercontent.com/assets/7766939/25379678/6d9beab4-29e0-11e7-8a82-29902a402907.png)

**Comment by Yenthe666** [comment]
@mart-e looks like we need another security rule? :)

**Comment by mart-e** [comment]
Or disable the edition if the required access rights are not present?

**Comment by jco-odoo** [comment]
I suppose this solves it: https://github.com/odoo/enterprise/commit/095dcea3a9b80c011ee2d14cdb693026e0a20b65
