### ISSUE TITLE
[10.0] Automated email template reply-to field not parsing anything other then global catchall address

### ISSUE THREAD

**Issue by vostokbike** [odoo/odoo#16635]
Impacted versions:
10 Enterprise
Steps to reproduce:
Edit the reply-to field of an automated email template: define a specific email address different from a global catchall email address. 
Define an outgoing smtp server. Send the automated email to the intended recipient. 
Check the reply-to field as a recipient. 
Current behavior:
The reply-to field on the recipient's side will show a global catchall address. 
Expected behavior:
The reply-to field must show a specific reply-to email address specified in the reply-to filed in the email template. 
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
As stated by Olivier this was not a bug but default behaviour:

> It's the expected behavior. When posting a message on a SO/PO/.., replies should go to the document, nowhere else, otherwise you lose history and tracking. "Reply-To" on mail templates is meant to be used for mass-mailing purposes, not for direct posting on documents.

**Comment by mlaitinen** [comment]
> As stated by Olivier this was not a bug but default behaviour:
> 
> > It's the expected behavior. When posting a message on a SO/PO/.., replies should go to the document, nowhere else, otherwise you lose history and tracking. "Reply-To" on mail templates is meant to be used for mass-mailing purposes, not for direct posting on documents.

Took me way too long to find this explanation. Seems like the behavior was only documented in version 15.0, in the help description of the field `mail.template.reply_to`.

```
reply_to = fields.Char('Reply To', help="Email address to which replies will be redirected when sending emails in mass; only used when the reply is not logged in the original discussion thread.")
```
