### ISSUE TITLE
[7.0] Expense analysis report showing wrong value

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#1664]
Hi Odoo Team,

Expense analysis report doesn't show correct value. 

[Prerequisite]
- Multi-currency
- HR module

[Steps to reproduce bug]
- Create new HR expense Human Resources -> Expenses -> Expenses
- Select different currency than base company currency ($)
- Go to Analysis report Reporting -> Human Resources -> Expenses Analysis
- The report will show values in currency selected on expenses and not in company account.

People might debate that this is a feature and not a bug. In that case it makes no sense in summing up values of different currency expenses into one. Its useless and meaningless. 

E.g 
Company base currency: GBP
Expense 1:
USD: 50

Expense 2: 
GBP:50

Expense analysis:
Total : 100 (Makes not sense)

Two possible fixes:
1. Convert all values into base company and show expenses data
2. add two new columns A· Currency  B. Currency/Base Value and provide group by based on currency.

**Comment by Nowheresly** [comment]
This bug is still here in version 8.0 and 9.0.

**Comment by adrienpeiffer** [comment]
Video link :
https://youtu.be/LqUqRsVlY98

**Comment by Yenthe666** [comment]
Hi @kenvac,

Thank you for your report (and thank you for the recording @adrienpeiffer).
This does look invalid (also in 8.0).  @qdp-odoo can you look into this when you've got time?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @kenvac ,

Thank you for your bug report.
At this point Odoo 7 & 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
