### ISSUE TITLE
project management issue

### ISSUE THREAD

**Issue by itshenryall** [odoo/odoo#16649]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional): 
![screenshot from 2017-04-26 12-43-07](https://cloud.githubusercontent.com/assets/17426441/25424479/a93cb294-2a92-11e7-862d-0ee20ef8b0ca.png)

**Comment by mart-e** [comment]
> Impacted versions:
> 
> Steps to reproduce:
> 
> Current behavior:
> 
> Expected behavior:

Please give the minimum information to reproduce the bug

**Comment by pedrobaeza** [comment]
Closing as no answer
