### ISSUE TITLE
[v10] t-call with template name in variable broken

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#16641]
**Impacted versions:** 10 (and judging from the code, master too).

**Steps to reproduce:**

Define a custom template and use `t-call` with a variable:

```xml
<t t-call="#{ form.form_fields_template }" />
```
whereas `form.form_fields_template` contains the xmlid of the template to render.

**Current behavior:**
it breaks complaining that
```
load could not load template
Template: #{ form.form_fields_template }
```
see full traceback below.

**Expected behavior:**

It should evaluate the variable and call the xmlid in it instead of calling `'#{ form.form_fields_template }'`.
In v9 it works perfectly.

In v9 it used to [eval_format](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_qweb.py#L452). In v10 I guess that `eval_format` became [_compile_format](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/ir/ir_qweb/qweb.py#L1429) but is not used by [_compile_directive_call](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/ir/ir_qweb/qweb.py#L1236) which replaced `render_tag_call`.

**Full traceback:**

```
Traceback (most recent call last):
  File "/opt/odoo/src/addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/src/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/src/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/src/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/odoo/http.py", line 327, in checked_call
    result.flatten()
  File "/opt/odoo/src/odoo/http.py", line 1257, in flatten
    self.response.append(self.render())
  File "/opt/odoo/src/odoo/http.py", line 1250, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/src/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/opt/odoo/src/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/src/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: None
Traceback (most recent call last):
  File "/opt/odoo/src/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in get_template
    document = options.get('load', self.load)(template, options)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/opt/odoo/src/odoo/addons/base/ir/ir_ui_view.py", line 924, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<string>", line 2, in get_view_id
  File "/opt/odoo/src/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/src/addons/website/models/ir_ui_view.py", line 80, in get_view_id
    raise ValueError('View %r in website %r not found' % (xml_id, self._context['website_id']))
ValueError: View '#{ form.form_fields_template }' in website 1 not found

load could not load template
Template: #{ form.form_fields_template }
```

**Comment by Gorash** [comment]
Hi,

Thanks for your intervention. The behavior described is due to the randomness of implementation, undocumented and not tested (see tests of qweb javascript).
I will see to add and document this feature.

Regards

**Comment by daramousk** [comment]
I might be missing something here but is <t t-call="#{ form.form_fields_template }" /> the correct syntax to load template?

As I am aware, you can load a template with <t t-call="form.form_fields_template" /> as in 
<t t-call="module.template_id" />

**Comment by simahawk** [comment]
nope `form.form_fields_template` is not a template name. `form` is an object holding the attribute `form_fields_template` that returns the xmlid of a template, as explained in the steps to reproduce above :)

This is extremely useful when you want to render template dynamically. I'd say that probably, to stay consistent w/ other `t-attf` attrs (w/ the final "F") we could have `t-callf`.

**Comment by Gorash** [comment]
Hello,

Here is the commit with the new feature: https://github.com/odoo/odoo/commit/27ff895dfd92619d496f67c8b11cb76277bf62d2

Since this is a new feature and not a fix, it is available from saas-16 and will be present in the next release.

Welcome

**Comment by simahawk** [comment]
@Gorash 1st of all: thanks for the work :)

2nd: are you sure is a feature? To me it sounds more like a v10 regression as this was supported since ages.

**Comment by Gorash** [comment]
I discussed it internally, it was an implementation consequence. Internally it was not used / known some colleagues even made work around (and would have liked to know that it worked). After discussion the decision was to put it for the next version.
(If you have a local repository, you can apply the change.)

**Comment by MaxEvron** [comment]
@Gorash I'm quite new to Odoo and expected @simahawk example to be working too. I'm implementing an addon to allow users to set a custom invoice template as a partner property and use this property to render a custom report when calling the Print > Invoice action.

I'm not very keen on applying a kind of patch on Odoo as it may be overwritten on next update.

Could you please explain me what is the said turnaround some of your colleagues used? 

Thanks.

**Comment by simahawk** [comment]
I left this issue aside for a while. Now that I need to migrate modules to v10 this is a PITA because for 1 line change I have to override a whole huge method which is not modular at all...
@Gorash since this is a very little change I ask you to change your mind about not including it in 10.0.
It's one line change, is tested and I can confirm it works smoothly...

Or at least move that line to a separated method so that ppl can easily override it.

**Comment by guewen** [comment]
Seems like you'd liked to have it in 10.0 internally as well. Is there really any chance to get this merged in 10.0? :)

**Comment by Yajo** [comment]
Maybe OCB accepts this backport...

**Comment by simahawk** [comment]
@Yajo there we go https://github.com/OCA/OCB/pull/654

**Comment by simahawk** [comment]
@gorash any chance we can talk about this at OdooExperience ? :)

**Comment by Gorash** [comment]
I discussed it again, and the decision made by the manager is that the commit will not apply in v10

**Comment by f4kh** [comment]
any news about this ?

**Comment by simahawk** [comment]
@f4kh use OCB if you need this. It got merged here a long time ago https://github.com/OCA/OCB/pull/654
