### ISSUE TITLE
[17.0] website: if there is invisble element in a page editor throwing the error in translation

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#166514]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [] Other (specify)

### Steps to Reproduce

if there is an invisible element (in this case cookie bar) in a page editor throwing the error in translation
https://www.awesomescreenshot.com/video/27952475?key=570e1cabacef09766125acfb8a9b7902

**Comment by Ngquang** [comment]
@kig-odoo Seems like they fixed it. Check out https://github.com/odoo/odoo/pull/166380
