### ISSUE TITLE
[15.0] documents : related model link dropped on replace - regression issue

### ISSUE THREAD

**Issue by jwaes** [odoo/odoo#166852]
### Odoo Version

- [X] 15.0
- [ ] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Tested on runbot 15.0 Enterprise.

Go to Settings/Documents - Enable documents for 'Product'

Go to Inventory / Products.
Choose a product.
Add a document to the Product.

Go to Documents. Go to the Products workspace.
The Document shows up, and is correctly related to a Product Template or Product Variant.
Add a few tags to the document. And a contact

Now, 'replace' the document with a newer version.

Issue: The new document has lost its link to the Product instance ... but the tags and contact did get transfered to the new version of the document. 
The product still links to the 'old' (archived) document

This worked before (about a month ago -- cant really pinpoint when this changed) and this regression issue showed up recently.

### Support Ticket

3932497

**Comment by jwaes** [comment]
I would like to dive into this, but i have no access to the enterprise repo. 
Support claims this is expected/desired behaviour since the beginning of 15.0 
But i am sure this worked a month ago ....

**Comment by vava-odoo** [comment]
Hi @jwaes 
Thanks for the report. It was fixed with https://github.com/odoo/enterprise/pull/64530
Cheers
