### ISSUE TITLE
[10.0] Accounting: Error when importing Chart of Accounts

### ISSUE THREAD

**Issue by repodevs** [odoo/odoo#16709]
**Impacted versions:**
- odoo 10 CE 

**Steps to reproduce:**
- Install Accounting Apps on fresh database
- Create Chart of Accounts for template
- Export Chart of Accounts template
- Update exported csv data [this gist for example ](https://gist.github.com/repodevs/c2973c29c65c695db6594bc82009ae78)
- Import Chart of Accounts -> Select file -> import

**Current behavior:**
**ERROR**
`duplicate key value violates unique constraint "account_account_code_company_uniq" DETAIL: Key (code, company_id)=(1.01.01.03, 1) already exists. at row 6`

I have checked that code of COA is not exist. but when I try import always show error like that

**Expected behavior:**
Chart of Accounts must imported after button import clicked

**Video/Screenshot link (optional):**

![import a file odoo](https://cloud.githubusercontent.com/assets/13567128/25538094/8447f400-2c6b-11e7-8cd7-753383cacf46.png)

**Comment by pundush** [comment]
Hi... did you resolve the issue? Thanks

**Comment by repodevs** [comment]
Yes, I have solve this issue. but I don't remember clearly, looks like the problem there is any duplicate Account Code. try removing account code when importing the csv file may solving the issue.
