### ISSUE TITLE
[V10] Manufactured product not calculate cost from component cost even costing method = Real price

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#16721]
Impacted versions: V10
For manufactured item with costing = real price,  stock valuation = perpetual, removal not set or set to fifo, with or without tracking,  the manufactured item is not taking cost  from the component cost on the BOM or from added consumed component.  Instead it is only take the cost from field cost in product form no matter the cost is not set ( 0 ) or set to a value.

Expected behavior :  The cost need to be taken from respected component cost used.
in V9 this behavior is ok although only work when costing method  = real price,  when changed to average not work anymore.

Steps to reproduce:

Set category product with:  all/saleable as parent category.
Set costing method = real cost
set stock valuation method = perpetual
set or not set the "force removal method" to fifo  or keep empty
set respected account for stock move in this category

Create product   A   route  = buy     fill in product price dan cost with a value
Create product   B  route = buy        fill in product price and cost with a value
Create product C route = buy, manufacture is checked   fill in product price with a value, keep cost field = 0
Create a BOM  for product C  with A and B as component set usage = 1 each for A and B
Purchase product A and B for some quanity eg 5 each and confirm, then receive and validate the receipt
Create MO for Product C set qty eg = 2 and used the created BOM as above.
confirm the MO and start the work order, finish it, mark as Done the MO

Go to inventory valuation
we will find the qty of manufactured product C is added for 2 pcs (as MO qty) but the cost is 0
while product A and B qty already reduced by 2 pcs each with respected purchase cost. (same with filled cost in product form if it is not changed during PO creation)

Current behavior:
Cost of manufactured product  C is not calculated from component cost

Expected behavior:
Cost of manufactured product C is calculated from component cost consumed.  at least same as V9

Video/Screenshot link (optional):

**Comment by jco-odoo** [comment]
Are your components also in real cost?  Because it also takes into account the costing method of those components.

**Comment by bunhin** [comment]
yes component already in real cost, actually i tried all but same the manufactured item cost only respect std cost

**Comment by bunhin** [comment]
Hi, any further info on this?,  i hope v10 community is not getting less than v9 on this very basic feature.  Please restore the feature back, as in v9 manufactured item cost can be calculated from its component cost (although only work when the costing method = Real price),  without this feature the inventory value will up and down (or look like lost) with no reason

**Comment by Yenthe666** [comment]
@bunhin I believe this topic https://www.odoo.com/groups/community-59/community-28876213?mode=thread answers your questions?

**Comment by sle-odoo** [comment]
I just tested this scenario today to compare with v11 and it is working properly.
Make sure the costing method are correctly configured on both components and finihed products. Also, in v10 this part of the code was moved in mrp_account which is an enterprise module...
