### ISSUE TITLE
[10.0] Point of Sale Receipts can't be linked to invoices sequences

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#16727]
**Impacted versions:**
8.0, 9.0, 10.0

**Steps to reproduce:**

1. Assign an invoice journal to the Point of Sale
2. Open the Point of Sale and make an Order
3. Select the invoice option
4. Validate the Order to Print the receipt

**Current behavior:**
The receipt is not printed with the invoice sequence, and there's no way assign the invoice sequence to the receipt.

**Expected behavior:**
A way to have the invoice sequence into the receipt, this way we don't have to print 2 things (a receipt and an invoice), but the receipt can also serve as an invoice.

**Comment by jorenvo** [comment]
I'm not familiar with the legal differences between a receipt and an invoice. I assume that will also differ from country to country so I will not comment on that.

But `pos.order` already has an `invoice_id` m2o. So there is already a 1 to 1 correspondence between a POS receipt and its invoice. If a customer gives his receipt reference (printed on top of the receipt) you can link that number to the invoice through the `pos_reference` field on `pos.order`.

**Comment by gustavovalverde** [comment]
@jorenvo, thanks for the answer, but maybe I did not explain the issue the right way.

What Odoo does not allow us to do is use the same invoice sequence (INV/2017/001) into the receipt. In North and South America this is the most common requirement as each receipt must have the sequence of the invoice linked to it. There's actually not a difference between the receipt and the invoice concepts, just it's printing format: US Letter or 4''.

Because of this segregation of concepts is that in The Americas, where anglo-saxon accounting is the common rule, the POS can't comply in some aspects, as anglo-saxon accounting is mostly accomplished by the invoice, and for most of the countries a sell always has to be invoiced (even if the invoice is not delivered to the customer).

I know I have the facility to search the invoice using the order reference, but that's different.

**Comment by jorenvo** [comment]
I'm assuming you have to use the same sequence for > 1 POS?

The easiest solution in that case would be to always print an invoice and use that instead of the receipt. It could be accomplished by a small module that automatically sets a default customer and automatically selects the invoice option. Of course it would no longer be printable by the POSBox in that case...

Including the sequence in the receipt by default is not ideal for standard Odoo because we would have to do RPC every time we print a receipt. It would break the offline functionality we have right now.

**Comment by gustavovalverde** [comment]
Actually, each POS will have a different sequence, but it has to match the invoice. Obviously, this can't be a default, just as anglo-saxon is not. But just as the anglo-saxon accounting, this should be an option to fix the a lot of headaches that this is causing in North and South America. 

I know this would break the offline mode, but caching the Journal Sequence could also be an option. As each POS would have a different journal, this should not be an issue. 

Just to be clear, this is not a specific issue of 1 Country, this is how is being done in almost in the whole Continent.

**Comment by wtaferner** [comment]
@gustavovalverde 
The only way to guarantee a sequence in Odoo PoS is to use the PosBox and provide a module or logic there or within the local browser database (although it is certainly not manipulation safe imho) to assign a proper ticket id which will be communicated back to the server with the whole order. Manipulation security and chaining needs to be provided on a local level (we did such work in Austria as you know) and can't be provided easily by Odoo itself yet.

As you are talking about invoices...this is not available in offline mode, so you only can create an invoice in the conventional way if you are online and communication to the server is possible. But, in case you pay an invoice with a ticket you will most likely reference the invoice number on the ticket and the proper account moves will be or already have been done via the invoice flow.

**Comment by gustavovalverde** [comment]
I do agree that this _could_ be handled by the PosBox, but the only _caching_ method that I've seen so far working similar to what I'm stating is this one in OCA (v8 though) https://github.com/OCA/pos/pull/91/files#diff-853552adc5f8d9088a8c78bb99fd52e3R14

What I'm not seeing is why can't we do the invoice Offline (in the POS or PosBox) and then send it to the backend when online. All the information needed to do an invoice is already on the Order.

I couldn't decipher by myself how Austria is doing it, I'll seat this weekend to try that out.

**Comment by wtaferner** [comment]
Right, for example this OCA module does already do what you are asking for...I just described it on a general level what is possible and not.

About the offline invoice...you can not use the logic which is normally executed on the server, offline if you can not provide all the logic locally and have it in sync (code-wise you have to do redundant implementations in different frameworks, Dart is doing a great job on this dilemma by providing a dart2js transformation, so basically let a bot right your redundant JavaScript code)...so, PoS is not yet perfect but will provide more and more integrations I guess in future versions (like the [pricelists](https://github.com/odoo/odoo/pull/16549), etc.)

**Comment by gustavovalverde** [comment]
Just as reconciliation happens when closing the session, maybe a firs-step approach could be to create the invoices and reconcile payments in session closing. We would already have the receipt with the right sequence from the caching. The only thing to think is _timing_, as the receipts and invoices should have the same time for consistency.

**Comment by wtaferner** [comment]
IMHO all this is already possible, at least on my side...the invoice is confirmed directly on creation and has only an invoice date so the time matching is not needed...reconciliation is done on session closing (user responsibility). You could eventually create an invoice after you have done the transaction as ticket only (for this I recommend to provide the ticket number on the invoice for reference) BEFORE session closing.

But I am certainly talking about stable 10.0 not 8.0. Let us talk in private if you want to have some insights...I guess this ticket could be closed if you do not want to keep it open as a reminder that this could be improved in CORE.

**Comment by gustavovalverde** [comment]
I have to take a time and sit with @wtaferner to see how this works, but in the meanwhile is nonsense having this issue open.
