### ISSUE TITLE
[odoo-forum]: Lower Karma to edit own question and make comments

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#16744]
Impacted versions:

Odoo Website

Steps to reproduce:
Try to edit the own question or make a comment

Current behavior:
New users obviously have not enough Karma to edit their own questions or comment.

Expected behavior:
This does not make too much sense. Many new user need to edit their questions and make comments in order to follow the forum guidelines, but do not have enough karma to do so. Instead they must post answers to react.
The karma necessary to edit its own question or post a comment should be the same as for posting a new question.

Video/Screenshot link (optional):

See as an example: https://www.odoo.com/forum/help-1/question/odoo-10-thinking-about-odoo-migration-118093

**Comment by Yenthe666** [comment]
Hi @treviser,

Thanks for your report.
I personally agree, it seems to be annoying new users and it adds comments while an edit would've been better.
@JKE-be what do you think?

Regards,
Yenthe

**Comment by treviser** [comment]
A big part of questions should be edited in order to follow the forum guidelines, when the author does not follow the advise we could delete all these garbage messages and the forum would look a bit better.

**Comment by gustavovalverde** [comment]
I've never used the forum for that reason, that karma thing is just keeping people on the mailing list and creating issues that are supposed to be in the forum.

**Comment by JKE-be** [comment]
Hello @treviser,

As you now (thank for your job on the forum) If you have not enough karma, your question is reviewed before to be published to avoid the spam.
So if you ask a fake question, wait that this fix question is published, and update it to display some spam, that will remove the "karma security" to avoid spam.

@gustavovalverde Thank for your feedback... But that is why I'm not on the mailing list, to avoid the spam into my mailbox! On the forum, you can choose really what you need and what you want to follow....

**Comment by treviser** [comment]
@JKE-be I'm not sure if I understand you correctly. Editing my own question after it has been validated and published by a moderator should not interfere with the antispam measures taken at the moment? Or do they?

**Comment by treviser** [comment]
@gustavovalverde I think we have much more idiotic useless questions in the forum than in the mailing list. But there are no guidelines and no moderation available in the mailing list.

**Comment by JKE-be** [comment]
If you edit your first question (that has been already validated) and replace the question by an advertising... 
IMHO you break the antispam measures... no ?

**Comment by treviser** [comment]
@JKE-be Not really. Before I validate a question, I do check if this is a legit Odoo-related question (we have many Outlook-related spam for example, which I do not validate). In this case the user has proven a relationship to Odoo and the probability that he is a real spammer is very low. If this may happen some few times it is easy to close the question.

**Comment by Yenthe666** [comment]
@JKE-be in theory yes you can bypass the antispam kind off. It would however involve you making an account, getting it verified, creating a topic, waiting on getting it approved and then editing the original topic (which you had to make look legit).
I don't really think that many people would go that far to spam and those that do could be closed by people like me and @treviser 😄

**Comment by treviser** [comment]
@JKE-be If we add https://github.com/odoo/odoo/issues/16793 to the picture, we can block fake Odoo questions by almost 100%

**Comment by treviser** [comment]
@JKE-be Any news on this? A substantial part of the questions posted in the forum should be edited, but it is an unbearable situation if people are not allowed to edit their own questions.

**Comment by JKE-be** [comment]
@treviser 

I have just tested again with a new user.

So you start with 0 Karma...
You register email => 3 of karma
You can now post your question (while you keep your 3 points (no downvote))
While you have 1 of karma you can edit question/comment

So I don't see any issue...

**Comment by treviser** [comment]
Ok, good to know, because many users report back that they are not able to edit or comment. But in this case it could be one of the numerous http 40x error messages which do happen all the time erraneously.

**Comment by JKE-be** [comment]
Never really arbitrarily:
    403 if you try to post link or img but you can not. (ok, it should be caught with a better way)
    400 if csrf token expired

do you meet other errors?

**Comment by treviser** [comment]
I regularly get errors when trying to delete a comment or a posting, when trying to convert a comment to a post or vice versa, less frequently when trying to edit a posting.

**Comment by JKE-be** [comment]
@treviser 
Any news about the step to reproduce it? 

I close it, but don't hesitate to re-ping me or re-open it if you still have the bug.

**Comment by treviser** [comment]
I always get a 400 if I try to delete my own comment for example.

**Comment by JKE-be** [comment]
Sorry, I just try again with your own user, and I cannot reproduce it :/
https://youtu.be/KPjLzCdFULk

**Comment by treviser** [comment]
This is what happens when I do it (I have activated the web console for more output):

![selection_085](https://user-images.githubusercontent.com/1814941/35621877-2af0e1dc-0686-11e8-9ac9-8512075346cf.png)

**Comment by JKE-be** [comment]
are you using the same flow than in my video? 
Which browser are you using?

**Comment by treviser** [comment]
@JKE-be Firefox is the culprit! It works with Google Chrome.
I'm using the following version of Firefox:

![selection_086](https://user-images.githubusercontent.com/1814941/35622001-a160f9d8-0686-11e8-8ed6-70e2bb224b3b.png)
