### ISSUE TITLE
Send mail error in spanish lang

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#16749]
Impacted versions:
saas-14

Steps to reproduce:
1.- Create a new customer invoice
2.- Validate the invoice
3.- Try send by email the record

Current behavior:
![captura de pantalla 2017 05 02 a la s 12 49 44](https://cloud.githubusercontent.com/assets/7606656/25631479/3320b5d0-2f36-11e7-9b31-2baa9a06a512.png)

Expected behavior:
On english is correct.
![captura de pantalla 2017-05-02 a la s 12 51 50](https://cloud.githubusercontent.com/assets/7606656/25631455/25946fc4-2f36-11e7-9bde-965a936a1ede.png)

Video/Screenshot link (optional):
https://youtu.be/pRh89PO-_Cw

**Comment by pedrobaeza** [comment]
Check the translation if it's incorrect.
