### ISSUE TITLE
No translation for SaaS-14 in Transifex

### ISSUE THREAD

**Issue by oscarolar** [odoo/odoo#16748]
Impacted versions: SaaS-14

Steps to reproduce: Go to https://www.transifex.com/odoo/

Current behavior: No saas-14 branch displayed to translate

Expected behavior: A SaaS-14 branch displayed to be able to translate

Video/Screenshot link (optional):
what I see
![proyectos_de_organization_odoo_s___vista_general](https://cloud.githubusercontent.com/assets/3836433/25637590/230343ce-2f4b-11e7-95aa-27d009681394.png)

**Comment by Yenthe666** [comment]
Hi @oscarolar,

Thank you for your report.
@mart-e which translations do you guys use for the SaaS-X versions? Should he translate version 9.0 or 10.0?

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Until a few days ago, "Odoo Master" was saas-14.
Now "Odoo Master" is saas-15. We only translate the latest saas.

**Comment by oscarolar** [comment]
so, If I want a translation to be done in saas-14 I have to open a PR?

**Comment by mart-e** [comment]
Yes, opening a PR would be accepted.

**Comment by oscarolar** [comment]
Thanks a lot!
