### ISSUE TITLE
'New Mail' Filter is not working properly in v9 and v10

### ISSUE THREAD

**Issue by lreficent** [odoo/odoo#16763]
**Impacted versions:** v9 and v10

**Steps to reproduce:**
1. Go to purchase.
2. Click on the on the rounded button with the number of unreaded messages for purchase orders for instance or go to purchase orders and add the filter *New Mail*.

**Current behavior:** 
* The filter is not filtering correctly, it show all the records.
* Clinking in the round button with the number does not add the filter.

**Expected behavior:** 
As it was in v8, this is, to only show the unread messages and clicking in the round button adds the filter.

**Video/Screenshot link (optional):** Screenshoots in runbot
* v8:
![image](https://cloud.githubusercontent.com/assets/23449160/25652673/aedf4b92-2fe9-11e7-9ce9-622f95bbc7d7.png)

* v9:
![image](https://cloud.githubusercontent.com/assets/23449160/25652757/0fedce18-2fea-11e7-8222-7ccf783fabf1.png)

* v10:
![image](https://cloud.githubusercontent.com/assets/23449160/25652894/b2b79692-2fea-11e7-95fa-60246d126265.png)

**Comment by Yenthe666** [comment]
This was fixed at https://github.com/odoo/odoo/commit/8761cf57bbaced20170a720b523b7166cef502af
