### ISSUE TITLE
No CSS/layout when report is called from button

### ISSUE THREAD

**Issue by tandrieuxx** [odoo/odoo#16768]
Impacted versions: 10.0

Steps to reproduce: 

Create a new report and an action associated. Make a button print this report by calling a function returning this kind of action : 
```
{
      'type': 'ir.actions.report.xml',
      'report_name': 'my_custom_report',
      'context': dict(self.env.context, active_ids=[1,2,3]),
}
```

Current behavior:

The report is downloaded but is not properly layouted, like wkhtmltopdf were not installed. The company logo doesn't appear and CSS seems to be ignored.

Expected behavior:

My wonderful custom report should be layouted with CSS and images.

**Comment by adekock11** [comment]
Could you try and set the `report.url` to `http://127.0.0.0:8069` in the System Parameters? I think this issue relates to some other issues I saw earlier.

**Comment by Yenthe666** [comment]
This does look like an issue with either the `report.url` parameter or because you're missing `Wkhtmtopdf` or have an invalid version.
Do the default reports work fine in Odoo?

**Comment by tandrieuxx** [comment]
I tried to call a standard report, same problem.

````
{
      'type': 'ir.actions.report.xml',
      'report_name': 'sale.report_saleorder',
      'context': dict(self.env.context, active_ids=[1,2,3]),
}
````

Then I tried to set the `report.url` system parameter to `http://127.0.0.0:8069` then `http://127.0.0.1:8069` (which seems more logical), both don't change anything.

I'm not missing Wkhtmltopdf since reports are working perfectly when I use the print menu.

**Comment by gdgellatly** [comment]
Ah. Sometimes I find the report url isn't localhost. At least not for me.
Proxies or docker etc or if using a dbfilter and running multiple databases
you can get an auth fail on the path. Personally what I do is put aĺl my
database names as aliases to localhost in /etc/hosts then use that as the
report url e.g. http://mydb:8069 . There are automated tools to do it but
try manually first.

**Comment by Vartkat** [comment]
I’m quite in the same situation, running Odoo 10 on Ubuntu 16 and I tried many things but as @tandrieuxx I have a wonderful HTML but styles  (in my case fonts) are not rendered in the pdf.

I’m building a custom module just to customize the invoices or sale orders.


So far I tried :
- adding report.url http://127.0.0.1:8069/ <http://127.0.0.1:8069/> or http://0.0.0.0:8069/ <http://0.0.0.0:8069/> to system parameters
- update the report module (and mine of course)
- added the depends on report in my manifest file
- adding the css by inheriting the dot in the invoice template with reference to googlefonts
- adding the same by inheriting the header template
- tried the same with base64 encoded fonts inside header 
- tried the same by inheriting report.common
- tried with wkhtml 0.12.1 then with 0.12.4

Result looks like this in html :


 and then to this in pdf :



Not really the same.

I’m running it on a vagrant virtual machine so I suspected the vagrant box so I also tried on a (virtual) Ubuntu server box.

None of these attempts succeeded.

If someone has an idea, something I missed, a way to debug this some advices would be greatly appreciated.

Thanks 

V.

**Comment by novawish** [comment]
Did you try to set **report.url** parameters with value: `http:://<_xmlrpc_interface_>:<_xmlrpc_port_>` with _xmlrpc_interface_ and _xmlrpc_port_ in file `*.conf` of `config` directory?

**Comment by ecino** [comment]
@gdgellatly It seems your answer is the problem I am facing (same as described in issue).

I tried to add this line in my /etc/hosts file : `127.0.0.1       test`
Where test is the name of my database. I have the report.url parameter set to `http://test:8069`. But I can still see in the console when running wkhtmltopdf :
```
2017-11-23 12:55:04,377 22646 INFO ? werkzeug: 127.0.0.1 - - [23/Nov/2017 12:55:04] "GET /web/content/287974-ba9a5a6/report.assets_common.1.css HTTP/1.1" 404 -
2017-11-23 12:55:04,379 22646 INFO ? werkzeug: 127.0.0.1 - - [23/Nov/2017 12:55:04] "GET /web/content/287414-3336544/report.assets_pdf.0.css HTTP/1.1" 404 -
2017-11-23 12:55:04,380 22646 INFO ? werkzeug: 127.0.0.1 - - [23/Nov/2017 12:55:04] "GET /web/content/287973-ba9a5a6/report.assets_common.0.css HTTP/1.1" 404 -
```

The `?` denotes to me that it is not connected to the database test. I cannot find the solution to make it work.

**Comment by ecino** [comment]
I noticed as well that reports are working fine when executed from the user interface, but it's as well not working when generated in a CRON task.

**Comment by ecino** [comment]
@tandrieuxx @Vartkat I found the solution for me:
I added the following line in my odoo configuration file :
```
dbfilter = <name_of_my_db>
```
It seems that wkhtmltopdf was not connecting to the database when running the report and that's why it couldn't load some assets. Now it's working. However this prevents to use different databases.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment. In concrete, with a multi-DB without dbfilter by domain or similar, which is forbidden for this kind of things.

Closing the issue.

**Comment by sopizet** [comment]
@adekock11 Thanks !
Worked for me with a ovh dynhost : adding the value localhost to report url key
And it's faster than ever !
odoo v11
