### ISSUE TITLE
Upgrade Module List doesn't delete modules that are not present any more

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1677]
V8 - unexpected behaviour of "update module list"

1. Have a Moule named `X`
2. update module list
3. rename this module to `Y`
4. update module list

now you will have two modules regiustered: `X` and `Y` although X doen't exist any more.

I would expect, that the module list is in sync with the present folders...

**Comment by blaggacao** [comment]
i experienced this repeatedly, as odoo doen't seem to strive for excellence, closing seems viable action.

**Comment by jl2035** [comment]
@blaggacao I don't understand..

If you physically remove the module, one would expect that it will also be gone from the app list (at least after running Update Apps List). Which is not the case, so this looks like a bug to me.. why did you close this, sir?

**Comment by blaggacao** [comment]
@jl2035 Have you experienced this behaviour again? It is somewhat an edge cas. I didn't stumble over it again, so for me, personally, at the moment it is not an issue and doing follow up on too man issues is bad for personal health :smile: - I'll reopen it, but please confirm that it still exists.

**Comment by jl2035** [comment]
@blaggacao Not sure.. at the moment I do experience it, but I plan to wipe the server and start from scratch. I lost too many nerves yesterday.

But it's totally weird. I reinstalled postgresql, removed cluster, created a new one, even deleted odoo files and cloned the repo again, but none of that fixed this. I think I messed up real bad, so starting from scratch is the only way out I see.

**Comment by dreispt** [comment]
It's an hazard to automatically remove modules missing in the addons paths:
If you restart a server and get the addons path wrong, you would lose the info on what modules were installed and would have a hard time recovering from that mistake.

Having said that, a module "purge" option would be a good addition, allowing for a manual clean-up of non existent modules. 
@sle-odoo I noticed you assigned your self to this - what do you plan to do?

**Comment by jl2035** [comment]
Yeah, I totally fucked the server. Getting errors like this now:

File "/path/to/odoo/openerp/addons/base/ir/ir_model.py", line 973, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))

I can't even create databases.

Nothing to do, but wipe everything and setup a new server. Let's leave this issue open for now, and I'll report back, ok?

**Comment by dreispt** [comment]
@jl2035 No need, just drop the database and create a new one; or upgrade the `base` module (`-u base`)

**Comment by jl2035** [comment]
@dreispt that was not possible. I couldn't create new databases due to many different errors as I pasted in my previous comment. After setting up a new instance on a new server everything works as expected.

I still don't quite understand why I was experiencing this even after removing postgre cluster and cloning odoo sources again. It could have also been my browser cache.

however, @blaggacao please close this and sorry for the drama

**Comment by gustavovalverde** [comment]
@Yenthe666, I see this as a real issue that should be reopened.

**Comment by Yenthe666** [comment]
Hmm all these options / issues are fixable by command though? So I don't see huge problems?

**Comment by blaggacao** [comment]
As Odoo aims at usability, something like a purge option (@dreispt) would drastically reduce cost of confusion on an average of let's say 100.000 odoo admins (20users / admin, 2M users).

Add to that, that unpurged modules give WARNING log messages, and may cause false positive push alerts by your favorite log analysis solution.

@Yenthe666 Fixing by command implies eg remote session, which is more costly on the support channels than just saying: "click the purge button carefully".

Ceterum censeo: Odoo should strive for excellence. Always.

There are some arguments in favor of reopening this, aren't there?

**Comment by Garibaldy** [comment]
There is a workaround for this ?

**Comment by NobodyIII** [comment]
This issue still exists. Why is it closed?

**Comment by dreispt** [comment]
Not sure it this should be done by the "update module list".
It could be improved to set the non-existing not-installed modules to inactive.

Beyond this I do feel that Odoo should be a technical solution to rename a module.
There are cases where we would like to rename a custom module, and right now this very hard to do.

**Comment by pedrobaeza** [comment]
@dreispt use this from the shell command:

https://github.com/OCA/openupgradelib/blob/fedf87f1d1506820109450797098038b13a68cb3/openupgradelib/openupgrade.py#L1133

**Comment by dreispt** [comment]
Thank you @pedrobaeza : 
More specifically, seemthing like this:

```
$ git clone https://github.com/OCA/openupgradelib.git
$ pip3 install -e openupgradelib
$ odoo shell -c my.conf

>>> from openupgradelib import openupgrade
>>> openupgrade.update_module_names(self.env.cr, [('old_module', 'new_module')])
```

**Comment by blaggacao** [comment]
@dreispt you can also have a look at https://github.com/xoe-labs/dodoo-migrator/blob/bb0cecd406b571362db40678b70b2386375ec47b/odoo/migration/migration.py#L313 Whatever fits your need best.

**Comment by pedrobaeza** [comment]
@blaggacao you are basically duplicating all the code in openupgradelib, so I don't get the point of doing that.

**Comment by dreispt** [comment]
Pedro is right - you would be better off leveraging the `openupgradelib` library.

**Comment by KetkiPatil** [comment]
This worked for me.
https://www.odoo.com/forum/help-1/question/delete-module-from-module-list-69259
