### ISSUE TITLE
[QWeb] t-foreach loop not working inside called templates

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#16772]
THIS IS ONLY AFFECTS ODOO v9! Works in Odoo v10.

Impacted versions: v9

**Steps to reproduce:**
Create a report. In my case I have the content
```
<template id="external_layout_base">
    <t t-if="show_header_footer" t-call="module.template_header"/>
    <t t-raw="0"/>
    <t t-if="show_header_footer" t-call="module.template_footer"/>
 </template>
```

The template footer looks like this:
```
  <template id="template_footer">
    <div class="footer">
      <div class="row">
        <table>
          <tr>
            <td t-foreach="[1,2,3]" t-as="val">
              <t t-esc="val"/>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </template>
```

**Current behavior:**
The foreach variable `val` is always None.

**Expected behavior:**
As in Odoo 10 or as if not in t-call, `val` should contain the actual looped value (1, 2, 3..)

**Comment by Armitxes** [comment]
Okay my bad, found the solution.

While in Odoo 10 you can do:
```<td t-foreach="[1,2,3]" t-as="val"></td>```

In Odoo 9 you must do:
```<t t-foreach="[1,2,3]" t-as="val"><td></td></t>```

which is my backport didn't work. 
Solved & Closed.

**Comment by sehrishnaz** [comment]
hope this will helps: https://learnopenerp.blogspot.com/2020/08/create-custom-report-in-odoo-using-qweb.html
