### ISSUE TITLE
Fleet In Arabic Language Creation Error 

### ISSUE THREAD

**Issue by mokamo** [odoo/odoo#16770]
Impacted versions: 8.0

Steps to reproduce: Change the user language to Arabic then Fleet / Vehicles Then Try to create new Vehicle Gives Error

Current behavior: When creating new Vehicle in the Arabic language Gives Error Even If I didn't input Any value in Arabic 

Expected behavior: Should Accept The creation of Vehicle in the Arabic Language (I think The Error in PO file)

Video/Screenshot link (optional):
![errorodoov8](https://cloud.githubusercontent.com/assets/15362132/25659310/731a7672-3007-11e7-8b7c-39bcb828d7d8.png)

**Comment by Yenthe666** [comment]
Hi @mokamo,

Thanks for your report.
@mart-e can you look at this? It is translation related.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Indeed the translation is incorrect. If you speak Arabic, could you correct it [on Transifex](https://www.transifex.com/odoo/odoo-8/)?
The term is the following 
https://www.transifex.com/odoo/odoo-8/translate/#ar/fleet/49571194

Closing as the translations are handled on Transifex, not github

**Comment by mokamo** [comment]
@mart-e Sorry this url is not working

**Comment by mart-e** [comment]
Which one? Both seems to work on my side?
Did you create a Transifex account and joined the Arabic team?
