### ISSUE TITLE
Error install any modules

### ISSUE THREAD

**Issue by RafaelSoaresCosta** [odoo/odoo#16778]
Impacted versions: 10

Steps to reproduce:  menu Aplication > Choice Any Module > Click Install

Current behavior: Show me message error attached

Expected behavior: Install module chose

Video/Screenshot link (optional):in attached
![step_3](https://cloud.githubusercontent.com/assets/8698814/25667118/ee3d897a-2ff8-11e7-836e-61cfb0e0daf4.png)
![step_2](https://cloud.githubusercontent.com/assets/8698814/25667117/ee38a9d2-2ff8-11e7-8e96-5f2ab7da2529.png)
![step_1](https://cloud.githubusercontent.com/assets/8698814/25667119/ee402b8a-2ff8-11e7-8eeb-f2ccb5ffe6a5.png)

**Comment by Yenthe666** [comment]
Hi @RafaelSoaresCosta,

Thanks for your report.
Can you try reproducing this error on an official Odoo (runbot.odoo.com)?
I believe your Odoo is older and that you should update your local Odoo. Can you update your local Odoo and try again?

Regards,
Yenthe

**Comment by FreduxR** [comment]
try create a new database

**Comment by RafaelSoaresCosta** [comment]
Hey Guys! @Yenthe666  and @FreduxR , thanks for help. I resolved this problem with a new instalation. Don't ask me how, haha.

But now, I have another problem. My modules of "Point of Sale" has an error when I try to complete a sales. attached.

Thanks!
![image](https://cloud.githubusercontent.com/assets/8698814/25749578/6757eb9c-3185-11e7-8f7d-7a21b7b131e3.png)

**Comment by Yenthe666** [comment]
Hi @RafaelSoaresCosta,

Happy to see it is fixed, thanks for the feedback.
As for this new issue: this is wkhtmltopdf related. Please check if you have the correct Wkhtmltopdf version installed and if it is working fine.

Regards,
Yenthe
