### ISSUE TITLE
[15.0] Stock: transfer sequence resets to default after warehouse name update

### ISSUE THREAD

**Issue by AungKoKoLin1997** [odoo/odoo#167713]
### Odoo Version

- [X] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

I have just tested for 15.0 and 16.0. I am not sure about other versions.

### Steps to Reproduce

- Adjust the reference sequence of the picking type as needed.
- Change the name of the related warehouse.

### Current Behavior:
The prefix of the related sequence is reset to the default, e.g., WH/IN.

### Expected Behavior:
The prefix of the related sequence should not be updated, as changing the warehouse name should not affect the prefix.

### Support Ticket
#3963840

### Video/Screenshot link (optional):

https://github.com/odoo/odoo/assets/45355704/77cf7b51-9b4b-49f7-ba99-fc4630c01a9a

@qrtl

**Comment by yostashiro** [comment]
https://github.com/odoo/odoo/pull/169720#issuecomment-2284802745

Odoo has decided not to fix this as the costs outweigh the benefits according to their judgment.
