### ISSUE TITLE
[8.0] safe_eval fails to evaluate 'datetime' on action domains when _needaction is True

### ISSUE THREAD

**Issue by gabrielo77** [odoo/odoo#16783]
Impacted versions: 8.0

Steps to reproduce:

I tried to use a domain like this on the *sale.order's* action (_sale.action_orders_):

[('date_order', '>=', datetime.datetime.combine(context_today(), datetime.time(0, 0, 0)))]

Current behavior:
```
It raises the following error:
  File "~/.buildout/odoo8/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
ValueError: "name 'datetime' is not defined" while evaluating
u"[('date_order', '>=', datetime.datetime.combine(context_today()+datetime.timedelta(days=3), datetime.time(0, 0, 0)))]"
```
Expected behavior:

I'm using a similar domain on a *stock.picking* tree view and it works. I've read the code and it looks that the problem is raised when a model has the class variable _needaction set to True: https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_ui_menu.py#L339

I can make a PR to fix this but first I want to ask you if you think that passing _datetime_ module to safe_eval locals dict is unsafe in this case.

Thank you. 

**Update**: I've seen that it is already fixed this on version 9.0 (https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_actions.py#L75)

**Comment by mart-e** [comment]
Hello,

Thank you for the report but I will have to reject this.
The 8.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues.
In this case, it is not supported in 8.0 to use datetime in the domain and we are not going to change that now. Sorry

Regards
