### ISSUE TITLE
Odoo does only support http protocol 1.0

### ISSUE THREAD

**Issue by ikzent** [odoo/odoo#16789]
Odoo does not support clients working only with newer http protocol version directly.

mpacted versions:

Odoo 8,0, 9.0, 10.0

Steps to reproduce:

Browse or request information via http

Current behavior:

Forces the http protocol to 1.0

Expected behavior:

Supports newer http protocol version like 1.1 (1999) or even 2.0 protocol
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ikzent,

Thank you for your report!
I'm not the person to decide on this but I think that 2.0 support would be great though.
@mart-e can you give feedback? I will label it wishlist for now.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Actually you should configure that on your webserver if you want to force an http version.
