### ISSUE TITLE
POS same receipt Reference generated

### ISSUE THREAD

**Issue by gitdrcsystems** [odoo/odoo#16781]
Impacted versions: 8.0 (Not test in other versions for now)

Steps to reproduce: One have login to same session using same credentials in multiple browsers.

Current behavior: Same Order Reference is generated in POS which leads to data loss of orders.

Expected behavior: Same Order Reference should not be generated and even if that is generated there should be any data loss 

Video/Screenshot link (optional):
Screenshot of the bill that got printed:-
![dadijanloaihkllh](https://cloud.githubusercontent.com/assets/15217731/25681499/1d66373c-3072-11e7-9f58-8f4315224f6b.png)

Above order is missing in database because the Order - Order 00591-006-0018 is already exist in database. Same order is created at time 06:43:55 while above order is created at 6:45:32.
![chfijnlohdfpokcp](https://cloud.githubusercontent.com/assets/15217731/25681582/6f574db0-3072-11e7-9501-7112888b1fc0.png)

In below image if you see all the products are different:-
![hbengpbddmoppkfi](https://cloud.githubusercontent.com/assets/15217731/25681649/a4f91c64-3072-11e7-8594-43de8eb20f73.png)

Explaining that more from code point of view below is the code in POS:-
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/models.js#L1046-L1057
Though this functions says it creates unique id but it does not.
This function calculates unique id from POS Session ID, POS session login number and sequence number and their combination in function results in same unique id.

Accepting that above code creates same Receipt number.
The code that saves data to database is quite more surprising:-
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/point_of_sale.py#L657-L686
Above function pop those records which receipt reference is already exist in database resulting into 100% data loss when receipt reference already exists.
We think that even if we would been getting duplicate records we should have considered saving them in another model just to make sure no data loss happens even if Javascript code fails to generate unique id as data is very important here because it keeps no track of what is sold and what has not been sold.

We are not sure if anyone has faced such issue but this is one of the biggest issue of its kind which breaks the reliability of odoo POS.

**Comment by janbec** [comment]
@gitdrcsystems Thanks a lot for describing a way to reproduce! We have issues with this for months and now I was able to reproduce on our v10 database. However, I hardly doubt that we run two browsers at the same time, so I suppose there might be another way to reproduce which I was not able to find.

I totally agree with your assessment of the POS. We are having cash differences >1000 Euro and we are lucky enough if we have a printed receipt to recover the sale and re-register it to get the goods out of stock. Most of the times we are not and that is a pretty serious issue.

**Comment by kalmenchia** [comment]
@janbec , i faced the same issues and are thinking to work out a fix on the above to resolve the issue ,

1. For the Order which has the same order no that is not posted , need to work out a way to
    change the order no and to ask the user to post it again ( perhaps with the number ref 
    similar to the one posted ) and get the user the pay and validate it again. as the customer
    may use the receipt no. which as printed to come back and refer to it , if we are unable to
    locate his receipt / order , it post another issues.

2. for the above case when happen , cashier may "purposely" choose NOT to post it and 
    cause potential
    issue of theft here , therefore must work out a way that during the 1st submit, it save to another
    local db , such as sqlite db and keep track the total . ( it works by keep tracking 
    all SALES and the total in this separate audit db ,the sales total of the day should be 
    having the same as the POS daily sales, anything that is not tally show that Cashier has
    not POST the order when the  above case happen )

it looks like , Odoo POS has this really BIG ISSUE ,not sure this can solve the issue/ idea , 
any feedback ?

**Comment by janbec** [comment]
@kalmenchia 
I received a solution from @nim-odoo that adds three digits corresponding to the milliseconds at order creation. I haven't tested it yet as we need to update our core to make it work properly first but I believe it is an option. The milliseconds should be random enough to avoid double ids.

If you have the opportunity to test it, I'd appreciate your feedback:

[
![grafik](https://user-images.githubusercontent.com/28890800/31446083-f40d0c38-ae9f-11e7-806c-a0c7bb20a246.png)
](url)

**Comment by airitos** [comment]
Dear users

This issue/BUG is severe, old, stills open here and in real live keeps providing a lock of awkward moments close to my customers because the true is this happens even today!!!

Can anyone say if this got solved so fat in official build coming from Odoo?
Can anyone tell if solution above provided by @kalmenchia (received from @nim-odoo ) works and could really overcome the issue?

Kind regards

**Comment by airitos** [comment]
Hi again
Dears @janbec @janbec and @nim-odoo is there any knows solution to deal with this issue???
This this issue got solved in any nightly build in the meanwhile?

**Comment by Yenthe666** [comment]
Hi @gitdrcsystems ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by airitos** [comment]
HI @Yenthe666 
Thank you for get in touch. Actually my customers use V9 and I wrote to community just asking people to share opinion and yes, there is people using v10 and also complaining of the same issue. And it is very normal because the code that generates the supposed "unique reference" remains unchanged.

So, if you want I can reopen another bug report for version V9, no problem.
Once again, @gitdrcsystems @janbec and @nim-odoo can you please share if this has been solved. Can anyone tell if workaround provided by @nim-odoo works?

Regards
Aires

**Comment by Yenthe666** [comment]
Hmm let us wait for feedback from @nim-odoo for a bit. Feel free to ping me if there has been no response in 7 das.

**Comment by nim-odoo** [comment]
Thanks to @janbec who could reproduce without two browsers. A description is given in PR #21669, and implies a barcode scanner.

**Comment by airitos** [comment]
HI everyone, could reproduce :) Oh God hope this to be the only cause and get the nightmare over. I'll wait the pull request to me merged.

Thanks @nim-odoo @janbec
