### ISSUE TITLE
[odoo-forum]: Add a new reason for closing posts: "Not enough information given to provide help"

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#16793]
Another small step to make moderation easier and to improve forum quality.

**Comment by Yenthe666** [comment]
Hmm @mart-e and @JKE-be what do you two think?

**Comment by JKE-be** [comment]
Thanks, I added this new reason on our forum ;)

![image](https://cloud.githubusercontent.com/assets/4848797/25696202/8fe34590-30b6-11e7-9f61-c0b8334acaeb.png)

**Comment by Yenthe666** [comment]
Woooh! The improvement of the day batch goes to you @JKE-be 😉 thanks.

**Comment by treviser** [comment]
Cool! I believe it is now safe to lower the karma in https://github.com/odoo/odoo/issues/16744
