### ISSUE TITLE
[10.0] Stock operations lost after creating new product attributes

### ISSUE THREAD

**Issue by wardm95** [odoo/odoo#16806]
Impacted versions:
10.0, 10.0 enterprise, 9.0, 9.0 enterprise

Steps to reproduce:
- Enable product variants in Sales > Configuration > Settings.
![image](https://cloud.githubusercontent.com/assets/17778757/25703989/20786560-30d8-11e7-9665-6e46c91cdc0e.png)

- Create new stockable product with one attribute (color) with two values (black and white).
![image](https://cloud.githubusercontent.com/assets/17778757/25704183/b7fe1704-30d8-11e7-88bb-3652f5c2e3ba.png)

- Add barcode and cost price to product variants.

- Update qty on hand for each variant.
![image](https://cloud.githubusercontent.com/assets/17778757/25704234/e465e7f4-30d8-11e7-8518-0eef8dc3397d.png)
![image](https://cloud.githubusercontent.com/assets/17778757/25704277/10e10764-30d9-11e7-8b79-57a4af68deae.png)

- Create new sale order and order some of the created variants.
![image](https://cloud.githubusercontent.com/assets/17778757/25704325/4850bc26-30d9-11e7-899f-17bf3dba0397.png)

- Confirm sale
- Create invoice
- Validate
- Register payment

- Go back to product and you can see the stock change (8 instead of 10 in screenshot).
![image](https://cloud.githubusercontent.com/assets/17778757/25704437/b9093790-30d9-11e7-84f1-f02ec39544b4.png)

- Edit product and add another attribute.
![image](https://cloud.githubusercontent.com/assets/17778757/25704500/f8014c76-30d9-11e7-99fd-245c82e14b7a.png)

- The stock of the product is gone.
![image](https://cloud.githubusercontent.com/assets/17778757/25704553/2eacc624-30da-11e7-9352-75834c91f040.png)

- Cost price of variants have been reset.
- Barcodes of variants have been reset.

Current behavior:

Stock of product is lost.
Cost price and barcodes of variants are reset.

Expected behavior:

Stock should not be lost.
Cost price and barcodes shouldn't be reset.

**Comment by wardm95** [comment]
Database ID's of product variants before adding second attribute:
![issue before](https://cloud.githubusercontent.com/assets/17778757/25706717/86a95584-30e1-11e7-8fc3-312f9a528e64.png)

Database ID's of product variants after adding second attribute:
![issue after](https://cloud.githubusercontent.com/assets/17778757/25706716/868d67a2-30e1-11e7-957c-054a2dec378a.png)

**Comment by jco-odoo** [comment]
It is true it tries to delete them, but as when there is stock, there are related objects like quants/moves, it will not be able to delete them and will just archive them. (active=False, tested in v10)

**Comment by Yenthe666** [comment]
Hi @jco-odoo

Perhaps the record it not dropped when there are related objects like moves but the records are dropped when you do the following case:
<ul>
<li>Create a product</li>
<li>Create an attribute with multiple attribute values</li>
<li>Add prices and quantities on the variants</li>
You will now have this:
<img src="https://cloud.githubusercontent.com/assets/6352350/26572288/a9796f44-4519-11e7-944e-fc98adeed344.png"/>

![image](https://cloud.githubusercontent.com/assets/6352350/26572206/6a4f5d38-4519-11e7-91e0-30041ffbbb13.png)

<li>Add a new attribute with an attribute values and save</li>
The old values are fully whiped now. The main product:
<img src="https://cloud.githubusercontent.com/assets/6352350/26572374/f3e23142-4519-11e7-8487-7274fa6627bc.png"/>
The variants:
<img src="https://cloud.githubusercontent.com/assets/6352350/26572413/213f69c0-451a-11e7-81c1-5cf32fd78c70.png"/>


Which means you now lost your references, stock, prices, ... of all variants when you add a new attribute value at any time on a product. This comes from this line: https://github.com/odoo/odoo/blob/10.0/addons/product/models/product_template.py#L407

CC @mart-e if I'm not mistaking we've been talking about this one a while back too.

**Comment by Yenthe666** [comment]
As discussed with @wardm95 we're closing this one off.
