### ISSUE TITLE
Only admin can create company

### ISSUE THREAD

**Issue by aario** [odoo/odoo#16807]
Impacted versions:
10
Steps to reproduce:
Login as admin
Create another user
Give the user all permissions just as the administrator user
User cannot create a company.
Current behavior:
User cannot create a company in settings > companies.
Expected behavior:
Users with just same permissions as the administrator user should be able to create companies
Video/Screenshot link (optional):

**Comment by aario** [comment]
Here is the log i get when the user tries to create a company:
```
odoo-webserver  | 2017-05-03 14:36:10,251 1 INFO hunterstone-odoo odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [359]
odoo-webserver  | 2017-05-03 14:36:10,257 1 INFO hunterstone-odoo odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [360]
odoo-webserver  | 2017-05-03 14:36:10,263 1 INFO hunterstone-odoo odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [361]
odoo-webserver  | 2017-05-03 14:36:10,336 1 INFO hunterstone-odoo odoo.models: Access Denied by record rules for operation: create on record ids: [30], uid: 5, model: ir.property
odoo-webserver  | 2017-05-03 14:36:10,339 1 INFO hunterstone-odoo werkzeug: 172.17.0.10 - - [03/May/2017 14:36:10] "POST /web/dataset/call_kw/res.company/create HTTP/1.1" 200 -
main-webserver  | 213.61.95.74 - - [03/May/2017:14:36:10 +0000] "POST /web/dataset/call_kw/res.company/create HTTP/1.1" 200 3326 "http://erp.hunterstone.com.au/web" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" "-"
```

**Comment by gustavovalverde** [comment]
Can't find it, but I know this issue was previously discussed here, maybe @Yenthe666 know where it is

**Comment by bistaray** [comment]
I was able to replicate this on the latest runbot for Odoo 10 Community Edition:

![image](https://cloud.githubusercontent.com/assets/13910162/25788486/525130c0-335e-11e7-94e5-81fe3beb83a1.png)

(I gave the DEMO user "Settings" permission for Administration)

This happened even when "Multi Companies" was checked in the user record.

**Comment by Yenthe666** [comment]
@gustavovalverde hmm I remember something about this too but no idea where it is.
I can indeed reproduce this issue:
![image](https://cloud.githubusercontent.com/assets/6352350/25792551/8221a3ac-33c7-11e7-93a5-c672b1c2606d.png)

@mart-e was there a reason it is this way or is it really a bug? Just to be sure.

**Comment by mart-e** [comment]
Hello,

Thanks for the report, it was fixed at https://github.com/odoo/odoo/commit/5c009b5f3149b3221caa088605437b3c4debc726
