### ISSUE TITLE
[10.0] Searching by quantity fails if all variants have less quantity

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#16802]
#### Impacted versions:
10.0, 9.0

Tested on demo.odoo.com (10.0) and a customer installation of 9.0.

#### Steps to reproduce:
1. Install stock module
2. Create a product and give it attributes so that it has 2 variants (two different colors for example)
3. Go to each of the variants and set their stock values to be 75 each.
4. Go back out to the main product template view: the product you created should show a quantity on hand of 150 (75 + 75)
5. Search for products such that their Quantity on Hand is greater than or equal to 100.

#### Current behavior:
The created product does not show up in the list of products.

#### Expected behavior:
The created product should show up in the list, as it's Quantity on Hand is 150, which is greater than 100.

**Comment by aisopuro** [comment]
There was a sizable change and simplification to the way the search function the product template worked in commit https://github.com/odoo/odoo/commit/acbef5552dc05b70e5097b9a9176c87d68e07cab, committed by Denis Michiels and @jco-odoo. Might they be able to comment on this?

The problem seems to stem from the fact that the product template basically defers the search to the variant. This works so long as one variant holds all the stock associated with a template. But if there are multiple variants, deferring the search means that each variant is individually checked for whether they pass the search criteria (in the above example, 75 is less than 100, so both variants fail the check). But the search should instead take into consideration the sum of the variants' stock values, since that is the value assigned to the template.

It seems to me that the template has to do the same kind of check as the variants do: look up all templates and then check each one for whether the stock data fits the domain. I don't think it would be a lot slower than the current approach, since the variant search does the same thing, only with variants.

**Comment by Yenthe666** [comment]
Hi @aisopuro,

Shouldn't you just simply search on the quantity on hand in this case?
![image](https://user-images.githubusercontent.com/6352350/34441389-c9e7733a-ecbb-11e7-86a0-ba2c1059cb84.png)

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @aisopuro,

The official response from Odoo S.A:

> Hello,
In this case, the behavior that you have mentioned is expected within Odoo. When using variants in some business cases, it would be important to know the quantity on hand based on different attributes. For example, search for stock of specifically the black iPhone X. Additionally, you can use the Product Variants listing for searching for different attributes as well.
Please let me know if I can provide any additional clarification on this explanation. Thank you and I hope you are having a great day!
Best,

**Comment by aisopuro** [comment]
@Yenthe666 note that in the picture you posted earlier, you have searched for quantities greater than 70, not 100. This means that it will find the template, because at least one of it's variants has more stock than 70 (they both have 75 in my example). With a 100, it will not find it.

The main problem here is that there is a mismatch between what the UI tells the user and how the search works. The UI tells the user "there are 150 pieces of this product template in stock". However, if the user filters the templates so that only products that have more than 100 pieces in stock are shown, the product suddenly is not visible. The information given by the UI and the information given by the filtering function do not agree.

The official response does not in my opinion address this. I agree that if you want to find out the stock on a per-variant basis, you should use the variant list instead of the template list. However, the product template seems to have assigned to it a number, called Quantity on Hand, which combines all of the variants' stocks into a single number. Therefore, I as a user would expect to be able to filter based on the  combined stock of all the variants. Do you see the problem?
