### ISSUE TITLE
Error odoo 10

### ISSUE THREAD

**Issue by FreduxR** [odoo/odoo#16814]
![image](https://cloud.githubusercontent.com/assets/22806823/25720005/9391088c-30c8-11e7-8fa1-063d36bcd665.png)

**Comment by FreduxR** [comment]
i have an error when start odoo, the modules not begin

**Comment by Yenthe666** [comment]
Hi @FreduxR,

Please add more information, details on how to reproduce this, ..
With only a screenshot and no information we really can't help you.

Regards,
Yenthe
