### ISSUE TITLE
[10.0] res_partner: commercial_partner_id in blank

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#16845]
**Impacted versions:**
10.0

**Steps to reproduce:**
I haven't been able to identify how to reproduce this

**Current behavior:**
One the partners is not being linked to the account moves. If an invoice is validated for Partner X, all the account moves are generated but the partner column is blank. If I go to the partner the invoiced amount is 0, but if I click on it it shows the invoices.

Edit: I realized that the commercial_partner_id was blank for some users. There's no other information that would relate those users to the issue. 

**Expected behavior:**
Account moves should be linked to the partner.

Old and new partners don't have this behavior. Is there something that can be done in the front-end to fix this kind of behavior?

**Comment by gustavovalverde** [comment]
@odony I'm not sure, but maybe you could have an idea on this.

**Comment by odony** [comment]
Not sure where to start from if we can't reproduce it ;-) What do you mean with "old and new partners don't have this behavior"? Which partners have it, then? Why would you want to change the front-end to fix this?

**Comment by gustavovalverde** [comment]
I've been creating contacts randomly to reproduce it, no success. Old partners (imported by csv), New partners (created using the front end). After further investigating, just 3 of 20 partners have this field in blank. I wanted to change the front-end to add this information, as it can't be added in importation.

In the mean while, is there a way to "rebuild" this field?

**Comment by gustavovalverde** [comment]
It was a third party module that caused the issue, I'll be doing some additional tests to validate if I can recover the `commercial_partner_id` of this entries.
