### ISSUE TITLE
populate dict  with no_string key should cause error 

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#16847]
Impacted versions:
10c

Steps to reproduce:

debug odoo, and watch method _compiled_fn defined in  odoo\addons\base\ir\ir_qweb\qweb.py  

Current behavior:

found the values have key is not string, this is worked for python2.7, but not worked for pypy or cython

{'format': <bound method ir.qweb.format of ir.qweb()>, 'request': <odoo.http.HttpRequest object at 0x00000000096651a0>, 'cache_assets': 8300663.0, 'true': True, 'false': False, 'get_modules_order': <function get_modules_order at 0x0000000008e40cc8>, 0: []}

Expected behavior:

should not use no-string as dict key, when use dict() or dict.update() method to populate dict.

Video/Screenshot link (optional):

refer to the different of pypy and python    https://bitbucket.org/pypy/pypy/issues/2554/pypy-dict-cannot-create-dict-with-dict-has

**Comment by gdgellatly** [comment]
@xmo-odoo Also does not work in Python 3. I know you are doing some migration work.

**Comment by xmo-odoo** [comment]
Probably fixed (in saas-17/master) due to Python 3 compatibility work.
