### ISSUE TITLE
Error in menu section of update apps

### ISSUE THREAD

**Issue by Pelirrojo** [odoo/odoo#16846]
Impacted versions:
v10 Community

Steps to reproduce:
Got to Update Apps link in backoffice:
https://www.yourweb.com/web#menu_id=54&action=39

Current behavior:
JS error:
```javascript Uncaught TypeError: Cannot read property '$el' of undefined
https://apps.odoo.com/web/content/1443101-3f91498/web.assets_backend.js:1719
Traceback:
TypeError: Cannot read property '$el' of undefined
    at https://apps.odoo.com/web/content/1443101-3f91498/web.assets_backend.js:1719:1100
    at https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:547:681
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:547:874
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at deferred.(anonymous function) (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:548:56)
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.add [as done] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:542:467)
```

Expected behavior:
List of apps to be updated

**Comment by bistaray** [comment]
I tried this in the latest version of Odoo 10 Community Edition and did not get the error:

[http://226054-10-0-8f2722.runbot9.odoo.com/web?#menu_id=54&action=39](http://226054-10-0-8f2722.runbot9.odoo.com/web?#menu_id=54&action=39)

**Comment by Yenthe666** [comment]
Hi @Pelirrojo,

Thank you for your report.
I just tried to reproduce this, just like @bistaray, without any problems.
Can you try reproducing this on an official runbot (runbot.odoo.com) or try again after updating your Odoo?

Regards,
Yenthe

**Comment by arojo22** [comment]
Impacted versions:
v10 Community

Steps to reproduce:
Got to Update Apps link in backoffice:
https://www.yourweb.com/web#menu_id=54&action=39

Hello
When you press the refresh button the client gives the next error


Uncaught TypeError: Cannot read property '$el' of undefined

https://apps.odoo.com/web/content/1443101-3f91498/web.assets_backend.js:1719
Traceback:
TypeError: Cannot read property '$el' of undefined
    at https://apps.odoo.com/web/content/1443101-3f91498/web.assets_backend.js:1719:1100
    at https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:547:681
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:547:874
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:546:198)
    at deferred.(anonymous function) (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:548:56)
    at fire (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:541:299)
    at Object.add [as done] (https://apps.odoo.com/web/content/1442937-ea2658f/web.assets_common.js:542:467)

thx

**Comment by allmani** [comment]
hello me too i have a same error in odoo v8
thanks

**Comment by MarcP9** [comment]
Hello , i have same problem whit Odoo 9 Comunity (Bitnami Installation)

The bug appears in 2 conditions:

1 Section Apps -> Updates  

2 In Development mode: Section Apps -> Apps (to show external modules)

It seems that bug is caused when trying to get external infromation from Odoo Webservice 

For what i readed its happening in Odoo 8, 9 and 10 Comunity & Enterprise.

**Comment by bistaray** [comment]
Tried on http://226557-10-0-8d9f0c.runbot9.odoo.com/

- Clicked REFRESH button on Google Chrome - no errror.

- Clicked Apps -> Updates - no error

- Activated Developer Mode, clicked Apps --> Apps - no error.

- Activated Developer Mode, clicked Apps --> Apps Store - no error.

**Comment by Akhil-Suresh** [comment]
I too experienced the same issue. On clicking update button. Recently everything was working fine for me. I got this issue on doing this:

- I created a module by scaffold command
- Then i uncommented the line on view
`<menuitem name="projectname" id="projectname.menu_root"/>`
-then I try Update Apps List.
-then Updates.
upon the last action I hit with this issue.
When I have gone to console I found error in this line
`self.app_switcher.$el.on('scroll', core.bus.trigger.bind(core.bus, 'scroll'));`

- under  web_client.js
` start: function () {

        var self = this;
        this.$el.toggleClass('o_touch_device', config.device.touch);
        core.bus.on('change_menu_section', this, function (menu_id) {
            this.do_push_state(_.extend($.bbq.getState(), {
                menu_id: menu_id,
            }));
        });

        return this._super.apply(this, arguments).then(function () {
            // Listen to 'scroll' event in app_switcher and propagate it on main bus
            self.app_switcher.$el.on('scroll', core.bus.trigger.bind(core.bus, 'scroll'));
        });
    },`

**Comment by 7Kronos** [comment]
Installed a docker version yesterday.
Everything works except this exactly same isssue.

Version 10 Community, official docker image

**Comment by Yenthe666** [comment]
@mart-e this issue seems to be happening to quite some people. I've tried reproducing this but without any luck. Do you have an idea what might be the problem?

**Comment by MarcP9** [comment]
Installed again trying Odoo 10 Comunity manual installation.

Same error again, maybe some Hosting incompatibilities or missconfiguration?

**Comment by Pelirrojo** [comment]
Hi,

I'm using this [AMI](https://aws.amazon.com/marketplace/pp/B016I5MD00) at AWS. 
Code is untouched, I've been working to add https certs to webserver, some server restart through service, one manual execution through binary, enabling debug mode,... and trying to install one commercial theme with addons, snippets and plugins but not installed yet.

The steps to reproduce it's restart changing /etc/odoo/odoo.conf to add new folders for the addons. After this restart, the error start to appear. This view it's an iframe, doesn't? So the error appears to be at server side. 

Thanks,
Manuel

**Comment by 7Kronos** [comment]
I have 2 addons folders configured in the conf file to keep plugins out of the docker container.

Maybe the issue is related to conf/env/hosting/permission/folder existence...

**Comment by Pelirrojo** [comment]
Hi, finally the error disappear.

1. check /etc/odoo/odoo.conf folders
2. Restart service with force-reload
3. Enter debug mode through uri param ?debug
4. Update apps list
and... *fixed*, the error dissapears.

Thanks to anybody for asking and helping.
Manuel

**Comment by JKE-be** [comment]
Hello
The bug has Been fixed this morning.

Bug was on apps Embed only.
