### ISSUE TITLE
feedback for log file creation problems

### ISSUE THREAD

**Issue by guaka** [odoo/odoo#1687]
When I try to set a log file in my configuration through `logfile = /Users...` I don't get any feedback and the server doesn't start. Would be good to add some feedback to the user here.

**Comment by Yenthe666** [comment]
Hi @guaka ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
