### ISSUE TITLE
[10.0] Chained pickings do not correctly set following moves as assigned

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#16893]
#### Impacted versions:
- 10.0 (tested on demo.odoo.com and runbot: http://226801-10-0-7e98e3.runbot5.odoo.com)

#### Steps to reproduce:
1. Install sale and stock
1. Enable multiple warehouses, complex routing and selecting routes on sale order lines
1. Create wrehouses A and B
2. Create a route that
    - When procuring to Customer location, creates a procurement to warehouse A
    - When procuring to warehouse A, takes stock from warehouse B
    - Is selectable on sale order lines
3. Sell some stockable product from warehouse A. Select the route created above on the line.
4. Confirm the sale. There should be 2 associated pickings: one should be available, the other Waiting for another operation
5. Process the picking that is not Waiting for another operation.

#### Current behavior:
- The second picking remains in a state "Waiting for another move"
- Even if the user tries to reserve the picking, the state does not change, even though opening the move shows that it's availability is the required amount.

#### Expected behavior:
- The picking should be marked Available

**Comment by aisopuro** [comment]
Some code speculation: it seems like the code concerning the assigning of the following picking hasn't been touched since the migration to the new api, and even then it apparently was not changed functionally. Does @Yenthe666 know who might be able to pinpoint this problem?

Right now the best workaround I can think of is to open the procurement that created the "Waiting for another operation"-picking, cancel it, change the route and rule so that it isn't chained to anything anymore and then re-running the procurement. This is a bit clunky, but forcing the availability creates a negative quant that I don't want either. If anyone has a better idea I'm all ears...

**Comment by Yenthe666** [comment]
Hmm most likely @jce-odoo :)
Could you have a look buddy?

**Comment by jco-odoo** [comment]
@Yenthe666 This should work normally and from this, I can not understand where the error is.  (no multi-company either)

**Comment by Yenthe666** [comment]
@aisopuro could you give more feedback for jco?

**Comment by aisopuro** [comment]
If you cannot replicate this @jco-odoo then I suppose it has been fixed, or was never really a problem in the first place.

One problem that I have encountered is that if you after step 7 create another picking that moves the same products from warehouse A somewhere else, and force availability on it, the original picking will return to "Waiting for another Operation", even though that operation has already been completed, which means the user will be unable to process it. I have however made pull request #19590 regarding that functionality, maybe you'd care to take a look at it?

Either way, I suppose this one is no longer valid, so I'll close it.

**Comment by lukebranch** [comment]
@aisopuro ,

I was experiencing something very similar in 10.0 here:
https://github.com/odoo/odoo/issues/21932

It is still happening once every now and then, however I have not yet been able to find the steps to reproduce.

Out of interest did you happen to be using OCA/server-tools/dbfilter_from_header and loading it by means of server_wide_modules = dbfilter_from_header?

**Comment by aisopuro** [comment]
No @lukebranch, to my knowledge we did not have anything like that in use.

**Comment by lukebranch** [comment]
@aisopuro ,

Good to know, thanks.
