### ISSUE TITLE
[10] email template not rendered correctly

### ISSUE THREAD

**Issue by JordyRitzen** [odoo/odoo#16891]
Impacted versions: 10.0 community and enterprise

Steps to reproduce:
create a mail template (in this case a task)
```
<div style="display:table;">
    <div style="display:table-header-group;">
        <div style="display:table-row;">
            <div style="display:table-cell; width:65px">Date</div>
            <div style="display:table-cell;  width:135px">Name</div>
            <div style="display:table-cell; width:65px">Quantity</div>
        </div>
    </div>
    <div style="display:table-row-group;">
        % for line in object.timesheet_ids:
        <div style="display:table-row;">
            <div style="display:table-cell;">${line.date.split('-')[2] + '-' + line.date.split('-')[1] + '-' + line.date.split('-')[0]}</div>
            <div style="display:table-cell;">${line.name}</div>
            <div style="display:table-cell;">${line.unit_amount}</div>
        </div>
        % endfor
    </div>
</div>
```
click on preview and it should look as the image below
![preview mode](https://cloud.githubusercontent.com/assets/15804808/25856344/ff7e6182-34d5-11e7-8045-009f422920eb.png)

When you open the object (in this case a task with timesheet lines)
Then click New Message and open the detailed editor and select the template you've just created. You'll notice it sums up to contents as shown in the image below.
![mail output](https://cloud.githubusercontent.com/assets/15804808/25856391/23378a7c-34d6-11e7-8614-af0f68a72410.png)

Current behavior:
It sums up the contents of the table without any styling.

Expected behavior:
A render of the table just as in the preview on the template itself.

**Comment by adekock11** [comment]
Will it not work if you just use `<table>`, `<tr>` and `<td>` instead of `<div>` tags? That is generally the best way to create tables.

**Comment by JordyRitzen** [comment]
@adekock11 That's what I tried first. This won't work at all with a for loop. When you save the template it moves the for loop outside the table.

**Comment by Yenthe666** [comment]
Yeah - this is absolutely about custom development and not a bug in Odoo. You can ask these questions on the official help forum at help.odoo.com.
