### ISSUE TITLE
[9.0]  Incorrect results when running 'Inventory at Date' report

### ISSUE THREAD

**Issue by Clandy17** [odoo/odoo#16902]
Impacted versions: 9.0

Steps to reproduce: Reproduced in http://226711-9-0-c40121.runbot10.odoo.com
1. Created sales order SO048 with product [A1232] iPad Mini.
2. Created a delivery and change the default source location from 'WH/Stock' to 'WH/Stock/Shelf 1'
3. Confirmed the delivery, ending with status 'Done'.

Current behavior:
1. Before performing the steps above, the inventory level, as shown in report '**Inventory Valuation**' was 1 for WH/Stock , and 499 for WH/Stock/Shelf 1.
2. After performing the steps above, the inventory level as shown in report '**Inventory Valuation**' was 1 for WH/Stock , and 498 for WH/Stock/Shelf 1. Which is correct.
3. However when checking the inventory level for today, as shown in report '**Inventory at Date**‘ was ' -1 for WH/Stock and 500 for WH/Stock/Shelf 1.

Expected behavior:
‘Inventory Valuation' seems to display the correct data. 'Inventory at Date' should be consistent with 'Inventory Valuation'. But maybe the design intentions of these 2 reports are different?

Video/Screenshot link (optional):

**Comment by jco-odoo** [comment]
Inventory at Date takes into location zones not specific locations in the case of pickings.
