### ISSUE TITLE
[17.0] module: website preview can't surport https. for frame bugs!

### ISSUE THREAD

**Issue by metahelix** [odoo/odoo#169014]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

under https by nginx ; when click menu -website or website editor, it shows the circle allround. by check in chrome debug mode. the error belows. 

### Log Output

```shell
Mixed Content: The page at 'https://**.com#action=539&cids=1&menu_id=391' was loaded over HTTPS, but requested an insecure frame 'http://**.com/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by MeetKD** [comment]
We are also facing the same issue.

CCing @qsm-odoo may be your are the right person to tag here ?

**Comment by MeetKD** [comment]
@metahelix Issue was due to ssl configuration. We are using cloudflare and ssl configuration needs to be set as full.

![SSL](https://github.com/user-attachments/assets/f568b9a4-7384-4f63-896b-937e3c731e2b)

**Comment by qsm-odoo** [comment]
Sorry, I was unavailable for the past month.
Thanks for the provided solution, indeed this kind of problem has always been fixed by checking the configuration on the domain provider side (although I can't remember what each time I am asked about it... :flushed:).
