### ISSUE TITLE
[web] o2m line is not getting deleted.

### ISSUE THREAD

**Issue by MeetSCS** [odoo/odoo#16911]
Impacted versions:
This is produced in v9,v10
Steps to reproduce:
    1. Install Survey Module.
    2. Create a new survey in draft stage with one page ( p1 )and one question(q1) and save record.
    3. Edit newly created survey and click on p1, delete the question q1 and create a new question q2 save 
        save current page ( Note:- do not save main survey page) and again click on page p1 and without  doing any operation again save the page.
    4. Save main survey record and click on edit button.
    5. Click on page p1. You will be able to see deleted record p1 and p2 in lines.  
Current behavior:

Deleted line is visible.

Expected behavior:

Deleted line should not be visible.

Video/Screenshot link (optional):

Please find attached screenshots.

1. Create a question q1.
![create_question](https://cloud.githubusercontent.com/assets/11327998/25898292/2ec997b2-35a9-11e7-8a86-fb5b72489748.png)

2. save page with question q1

![save_page](https://cloud.githubusercontent.com/assets/11327998/25898332/55ed4320-35a9-11e7-8b26-234cce52190c.png)

3. Save Record.

![save_record](https://cloud.githubusercontent.com/assets/11327998/25898401/a46420a0-35a9-11e7-9621-695cb29ae01f.png)

4. Edit newly created record and click on page p1 it will open a new dialog delete that question.

![delete_record](https://cloud.githubusercontent.com/assets/11327998/25898474/ea957790-35a9-11e7-9d22-0ca5939cd3e7.png)

5. Add new question q2 and save current question with saving main record.

![new_line](https://cloud.githubusercontent.com/assets/11327998/25898500/fb2b8856-35a9-11e7-8d3b-a84fce9646d8.png)

6. Again click on page p1 and save the record withour doing any operation.

![save_wo_edit](https://cloud.githubusercontent.com/assets/11327998/25899053/fb170370-35ab-11e7-8474-3772a0960f52.png)

7. Click on edit button and click on page p1 button, it will display deleted line q1 as displayed in screen shot.
![edit_line](https://cloud.githubusercontent.com/assets/11327998/25898994/c878ac20-35ab-11e7-8518-e352525353d3.png)

![deleted_line_visible](https://cloud.githubusercontent.com/assets/11327998/25899022/def99b08-35ab-11e7-8960-34d0d05e7f46.png)

**Comment by MeetSCS** [comment]
cccc @Yenthe666 @pedrobaeza @dreispt Can you please assist me, whom to assign or point out from odoo team ?

**Comment by Yenthe666** [comment]
Hmm @mart-e who's responsible for survey? To be checked what is up here. 😄

**Comment by MeetSCS** [comment]
@Yenthe666 @mart-e Thank you for your prompt response. 

This issue is replicated in whole system when there is one2many field inside one2many field.

**Comment by rim-odoo** [comment]
I confirm this behaviour exists and seems buggy.

Simple workaround: save when you delete stuff.

**Comment by ged-odoo** [comment]
It is indeed a bug. Relational fields are hard... For your information, I just tested in saas-16 (with the new views), and this bug has been fixed (well, by rewriting totally the new views, we at least did something right).

As a bug in 9.0->saas-15, it should go to the bugfix team first.  It may be easy (but I suspect that it is a hard bug... in that case I guess it will be escalated to framework team)

**Comment by rim-odoo** [comment]
As we suspect this bugfix is risky and this issue is not blocking, I'd suggest we don't fix it

**Comment by mart-e** [comment]
As there is a workaround and not critical (no traceback, not blocking), I approve the "not fixing in v9".
Thanks for the review

**Comment by MeetSCS** [comment]
@Yenthe666 @rim-odoo @ged-odoo Thank you for your valuable time.
