### ISSUE TITLE
Monetary field does not show currency on creating a new record

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#16910]
**Impacted versions:**
v10 enterprise (possibly more)
**Steps to reproduce:**
Sales -> Sales -> My Pipeline -> Create a new Opportunity. The Expected Revenue field should have the currency symbol set appropriately. (attaching screenshot)
**Current behavior:**
The currency symbol for a monetary field is not shown on Creating a new record
**Expected behavior:**
The currency symbol on monetary fields should be shown at all times.
Video/Screenshot link (optional):

![screen shot 2017-05-10 at 15 36 15](https://cloud.githubusercontent.com/assets/3503159/25898890/7a34d26a-3596-11e7-8e00-7302a83830b5.png)

**Comment by MohsenWaleed** [comment]
@daramousk Did you find a solution for this?
