### ISSUE TITLE
[10] Accounting: initial balance do not show the unreconcillied entries of the last years.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#16925]
**Impacted versions:**
9, 10.

**Steps to reproduce:**
Generate an invoice in 2016, dot not reconcille then.
Generate a Ledger in 2017.
You see initial balance without detail :
![image](https://cloud.githubusercontent.com/assets/16716992/25916520/31144b40-35c5-11e7-8207-e524f12a0d47.png)
But french accounter demand to see the unreconcillied entrie of the last year (like SAGE, CEGID, EBP, ... : when you start a new year, the soft add in the initial entries all the unreconcielled entries (for payable recevable accounts)). 
But in Odoo 9+, there are no more initial entries.

I have rebuild the accounting report (general ledger/partner ledger/journal ledger/openning ledger) in this module : https://github.com/fmdl/account_standard_report

**Exemple**
![image](https://cloud.githubusercontent.com/assets/16716992/25917016/ff930d8e-35c6-11e7-9418-732650084641.png)
In this case the entries of 31/12/2016 (red line) is not reconcillied in 2016 (but it is reconccilied in 2017 with the line blue), that why this line is not include in the initial balance (green line).

If you have question about this technical issue, I can help you.

Regards

**Comment by Yenthe666** [comment]
@qdp-odoo another accounting related one. Can you have a look please? (sorry for pinging you so often)

**Comment by qdp-odoo** [comment]
It's not a bug but rather a missing feature.

**Comment by fmdl** [comment]
Thank you for your answer, effectively is not a real bug, but in V8 this feature is not missing (because Odoo generate the opening entries). 
And regardless of that, and despite your efforts, the reports provided by Odoo do not live up to the other accounting software.
The module provided contains this feature, indispensable for any accountant.

Have a good day.
