### ISSUE TITLE
[9.0] Accouting - Widget monetory does not round 0.05

### ISSUE THREAD

**Issue by citronpower** [odoo/odoo#16932]
This error append while trying to generate reports that use the monetory widget with a currency which has a rounding factor 0.05. When using a currency with 0.01, there is no problem. The problem does not append in reports in Sales App. For sure, it appends in the case below.

Example: In Accouting App -> Reporting -> Sale/Purchased Journal. In the generated Journal, the numerical values (credit, debit, totals) have only 1 decimal even if the original value is 4.15.
Below is the value rounded with 0.05 factor:
![capture d ecran 2017-05-11 a 09 38 49](https://cloud.githubusercontent.com/assets/9839114/25937896/b59408e8-362d-11e7-9327-5785ea4dfc9b.png)
And here with 0.01 factor (original values):
![capture d ecran 2017-05-11 a 09 42 47](https://cloud.githubusercontent.com/assets/9839114/25938054/473d8fe4-362e-11e7-8920-63f7c3e749c2.png)

This error occurs since the last update of the Accounting app we made 2 weeks ago.

Has anyone an idea how i may solve this problem?

Thanks in advance for your time.

**Comment by citronpower** [comment]
This problem seams to also appear in invoices... but only in one part, see below:
![capture d ecran 2017-06-01 a 15 20 42](https://cloud.githubusercontent.com/assets/9839114/26681594/f1fd939c-46dd-11e7-9f4f-5221e88a1c83.png)
The column "Amount" has the same problem (3,75 =>3,8) but the total act correctly.

**Comment by Yenthe666** [comment]
@qdp-odoo something you've changed perhaps?

**Comment by pedrobaeza** [comment]
But why a 0.5 as rounding factor? CHF rounding factor is 0.01. Do you have a real case where a currency has that rounding factor. Maybe you are trying to force some way to get a business case using that unreal rounding, but this should stick to actual cases with currencies in the world.

**Comment by Yenthe666** [comment]
Hi @citronpower,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
