### ISSUE TITLE
[Error] Empty adress email recipeints Odoo 10

### ISSUE THREAD

**Issue by kortibu** [odoo/odoo#16949]
Hello, I'm using Odoo Community Editions 10 and having a probleme with outgoing email: there are nothing on ever outgoing email such as adress amail of recipient, title and content.

For example: 

On Auth Signup: Reset Password template
To (emails): ${object.email|safe}

Content:

Dear ${object.name},

A password reset was requested for the Odoo account linked to this email.

You may change your password by following this link which will remain valid during 24 hours:

Change password
If you do not expect this, you can safely ignore this email.

Best regards,

${user.signature | safe}
Sent by ${user.company_id.name} using Odoo

But, email is failed to send with the error "Error without exception. Probably due do sending an email without computed recipients."

The configuration of outgoing email server run well.

Somebody could help me to resolve this probleme? Tks.

**Comment by Yenthe666** [comment]
Hi @kortibu,

Thanks for your report.
Could you first try updating your Odoo codebase to the latest version?
It looks like your e-mail template for the reset password is syntactically incorrect. Did you change anything in it?

Regards,
Yenthe

**Comment by kortibu** [comment]
Hi there,

I've update the lastest version (10.0-20170509). I didn't change nothing, every e-mail template are default and anyone can be sent (always empty the recipeints email). Please help me, tks.

**Comment by kortibu** [comment]
Needing somebody to help me. I tried to update the last version but nothing changed: every automatic e-mail without adress email of recipeints and body content.

**Comment by wayhi** [comment]
the same problem occurs to me! after checking the log file, I found the following output:

> File "/usr/lib/python2.7/site-packages/odoo/addons/mail/models/mail_template.py", line 373, in render_template
>     mako_env = mako_safe_template_env if self.env.context.get('safe') else mako_template_env
> NameError: global name 'mako_template_env' is not defined

Anybody can fix this?

**Comment by jigar1859** [comment]
Failure Reason: Error without exception. Probably due do sending an email without computed recipients.

When using GMail SMTP server... any help or ideas?

**Comment by RealJaJaAdmin** [comment]
This issue still exists in the latest odoo 10

**Comment by RealJaJaAdmin** [comment]
Fixed it by running `pip install Jinja2` and restart the odoo server

**Comment by Yenthe666** [comment]
Hi @kortibu and @RealJaJaAdmin,

Which OS are you using? Is this a preconfigured installer? The dependency is in the `requirements.txt` so if you install it yourself it is your responsibility.
CC @d-fence

**Comment by RealJaJaAdmin** [comment]
@Yenthe666 this is a preconfigured installer, followed the installation instruction on the odoo website

**Comment by RealJaJaAdmin** [comment]
followed this intallation: https://www.odoo.com/documentation/10.0/setup/install.html#packaged-installers

used `yum-config-manager --add-repo=https://nightly.odoo.com/10.0/nightly/rpm/odoo.repo`

**Comment by d-fence** [comment]
The rpm package comes with Jinja2:
https://github.com/odoo/odoo/blob/98072f1ad069943e432385bf26926bc951297a7e/setup.cfg#L17

I tested it and "python-jinja2" is installed correctly.

Can you try this :
```bash
$ yum list installed | egrep -i jinja
```
It should output something that contains 'python-jinja2.noarch ...'

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
