### ISSUE TITLE
Odoo v9 vs v10 changes - Setting analytic account (project_id) in sale

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#16950]
Impacted versions: v10

**Steps to reproduce & current behavior:**
Open sale order form view in V9, set project_id (analytic account), works.
Open sale order form view in V10, project_id (analytic account) is missing.

This is bad for migrated databases, if you display the field via XML Code the field shows as set BUT it's value can't be displayed. If you try to set the project_id manually, it shows you that the changes were successfully applied until you refresh the page and all is gone.

**Expected behavior:**
Same behaviour as in V9 or migration/backwards compability

**Code changes between V9 & V10:**

v9
```
project_id = fields.Many2one('account.analytic.account', 'Analytic Account', readonly=True, states={'draft': [('readonly', False)], 'sent': [('readonly', False)]}, help="The analytic account related to a sales order.", copy=False, domain=[('account_type', '=', 'normal')])
```

v10 (Module sale, sale.py)
```
    project_id = fields.Many2one('account.analytic.account', 'Analytic Account',
                                 readonly=True,
                                 states={'draft': [('readonly', False)],
                                         'sent': [('readonly', False)]},
                                 help="The analytic account related to a sales order.",
                                 copy=False)
    related_project_id = fields.Many2one('account.analytic.account',
                                         inverse='_inverse_project_id',
                                         related='project_id',
                                         string='Analytic Account',
                                         help="The analytic account related to a sales order.")

    def _inverse_project_id(self):
        self.project_id = self.related_project_id
```

Could someone explain me how to get this fixed / what's the point of the new code?

**Comment by mart-e** [comment]
>  Open sale order form view in V10, project_id (analytic account) is missing.

No it is not, it is here. You can set a value until you have confirmed the order.

![b7eabd3b-4cb0-4acb-9d44-bb77fa37bebb](https://cloud.githubusercontent.com/assets/564822/25995353/3a0b1ae6-3712-11e7-9bc4-d5f822a14e55.png)

>  If you try to set the project_id manually, it shows you that the changes were successfully applied until you refresh the page and all is gone.

This is because you have twice the same field in the view, it is not supported by the view framework.

> Could someone explain me [...] what's the point of the new code?

Was changed at 8149d1422d46e4d622470239accc3166b927aaa4, I think the commit message explain the reason of the two fields.

>  Same behaviour as in V9

Sorry but between versions, the model and behaviour change. Even if, in this specific scenario, it should not change much for the user.
