### ISSUE TITLE
Creating a new view from the Settings -> User Interface -> Views does not assign to the view an external id

### ISSUE THREAD

**Issue by daramousk** [odoo/odoo#16957]
**Impacted versions:**
v10e
**Steps to reproduce:**
Create a View (record in ir_ui_view), save it. The **external id** and **model data** fields will not be calculated.
**Current behavior:**
The external id and model data fields will not be calculated.
**Expected behavior:**
These fields should be calculated. When they are not, one is not able to create a report from the web interface and has to create a module.

![screen shot 2017-05-12 at 18 48 17](https://cloud.githubusercontent.com/assets/3503159/26006021/a2d1ddb8-3743-11e7-9840-f55a21483120.png)

**Comment by bistaray** [comment]
External ID's are not created for any record created in Odoo via the User Interface. 

They are assigned only during import and export. 

Once you export the view it will be assigned an External ID.

**Comment by Yenthe666** [comment]
As @bistaray pointed out (thanks!) this is the default behaviour, so no bug here. 😉
