### ISSUE TITLE
[16.0][17.0] website: Error neutralizing database

### ISSUE THREAD

**Issue by koles-smarttek** [odoo/odoo#169593]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

In Odoo.sh rebuild stage branch, import database, restore database

Current behaviour:
Error neutralizing database, see ~/logs/neutralize.log.

Expected behaviour:
stage branch rebuild properly.

What to do:
Just add ";" at the end of latest sql query
https://github.com/odoo/odoo/blob/17.0/addons/website/data/neutralize.sql
https://github.com/odoo/odoo/blob/16.0/addons/website/data/neutralize.sql

### Log Output

```shell
ERROR:  syntax error at or near "DELETE"
LINE 4: DELETE FROM ir_config_parameter WHERE key = 'hr_recruitment_...
        ^
STATEMENT:  UPDATE website
   SET robots_txt = E'User-agent: *\nDisallow: /'

DELETE FROM ir_config_parameter WHERE key = 'hr_recruitment_extract_endpoint';
```

**Comment by serenefemme** [comment]
It looks like they caught and fixed this in 2c9676e (for 17.0), and d3a3ea4 (for 16.0) :+1:
