### ISSUE TITLE
[10.0] campaign_id is not related between CRM and Marketing

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#16974]
**Impacted versions:**
10.0, maybe others

**Steps to reproduce:**
_Approach 1:_
1. Create a CRM Lead, activate debug mode to show the campaign_id field (as is not visible otherwise).
2. Crate a Campaign with the name "Social Media"
2. Go to Marketing module
3. Search for the "Social Media" campaign created in the CRM

_Approach 2:_
1. Create a Marketing Campaign with the name "Social Media", in the Marketing Module
2. Go to CRM Module
3. Create a new Lead and activate debug mode to show the campaign_id field (as is not visible otherwise).
4. Search for the Social Media campaign previously created in the Marketing Module

**Current behavior:**
The campaign_id is not related between both modules, they both exist independently

**Expected behavior:**
A campaign created in the CRM Module should be visualized in the Marketing Module and vice versa, as campaigns for marketing are commonly related to CRM customer acquisition or follow-up. Otherwise, having the same field for both modules with the same name is pointless and confusing. 

Also, the campaign_id should be visualized without recurring to developer mode.

**Comment by gustavovalverde** [comment]
@Yenthe666 this one has some months here, seems like an easy one to fix, but don't know who manage this cases.

**Comment by Yenthe666** [comment]
Hmm, most likely @JKE-be - could you have a look buddy?

**Comment by bst-odoo** [comment]
Thank you for the feedback.
We will take it into account for the improvement of our Marketing automation app.
