### ISSUE TITLE
Buckaroo: How to configure link results in 404 (not found)

### ISSUE THREAD

**Issue by bobslee** [odoo/odoo#16987]
Impacted versions: 10

Steps to reproduce:
- Install Buckaroo addon
- Go to Accounting / Configure / Payment Acquirer
- Click the link "How to configure your Buckaroo account?"
- The link opens an URL to Buckaroo and results in a 404 Not Found

**Comment by Yenthe666** [comment]
Hi @bobslee,

Thank you for your report.
This URL is indeed no longer available on the website. @csnauwaert perhaps this is something for you? As you did Yodlee/Plaid. @mart-e cc for you.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@csnauwaert this one is still open. @nim-odoo can I bother you with this?

**Comment by mart-e** [comment]
Hello,

The link is indeed not working anymore (and it [was not providing](https://web.archive.org/web/20160608025556/http://www.buckaroo-payments.com:80/business/customers/online-payment/) very useful information anyway).

So I remove it at 50a6f50df1b.
If you have proper documentation on Buckaroo website (I did not find one), please let me know so I can add it back with a better link.
