### ISSUE TITLE
[17.0] delivery_starshipit: Can't get rate and create shipments for some Couriers

### ISSUE THREAD

**Issue by victoria-havi** [odoo/odoo#169931]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

## Bug Ticket

**Courier:** Aramex

**Title:** Incomplete list of carrier options sent to Starshipit

**Description:**

The request sent to Starshipit does not include all the available carrier options for Aramex.

**How to Reproduce:**

1. Attempt to create a shipment on a platform that integrates with Starshipit.
2. Select Aramex as the carrier.
3. Observe the available service options.

**Current Behaviour:**

Only a limited number of Aramex services are available for selection. These include:

* Australia Post Parcel Post (7C55)
* Australia Post Express Post (3J05)
* EXPRESS (EXP)
* 1,3 & 5KG FIXED PRICE PREMIUM (FPP)

**Expected Behaviour:**

The request sent to Starshipit should include all available Aramex services for the selected country and shipment characteristics. This may include additional options  beyond those currently listed.

**Additional Information:**

* The expected behaviour can be confirmed by manually checking the available Aramex services on the Starshipit platform or by contacting Aramex directly.

**Impact:** This issue limits the user's ability to choose the most appropriate and cost-effective Aramex service for their shipment.

Current Rules at Starshipit:
![image](https://github.com/odoo/odoo/assets/142771724/999fa9e6-5497-4211-8b92-abbca307a063)
Error:
![image](https://github.com/odoo/odoo/assets/142771724/d85a93ba-74c9-4a6e-998c-29eca128452b)

**Comment by victoria-havi** [comment]
Upon checking with Starshipit, it has been noted that they need suburb information to provide services. Presently, Odoo lacks this field and is not including it in the request.

**Comment by victoria-havi** [comment]
@vava-odoo Please review this issue as it is critical to us. Thank you.

**Comment by vava-odoo** [comment]
Hi @victoria-havi 
I'm afraid I can't help here. You should open an [official ticket](https://www.odoo.com/help) as it is an enterprise feature.
Cheers

**Comment by victoria-havi** [comment]
Thanks @vava-odoo. Appreciate your response.
