### ISSUE TITLE
hr_expense usability issue

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#16996]
Impacted versions:

10.0

Steps to reproduce:

Create an expense report, possibly by submitting expense lines.

Click Add an item, the system presents expense lines in "To submit state" this is correct.

![image](https://cloud.githubusercontent.com/assets/692075/26065537/94469718-3994-11e7-8545-4a8bf8bea12c.png)

However in the screenshot above, you see that the Create button is present. This buttons leads to this screen which is very confusing in the top part, where the "Submit to manager" and "Documents" button do not work and do not make sense in this context:

![image](https://cloud.githubusercontent.com/assets/692075/26065609/cefd5a68-3994-11e7-8fde-ba397a4476fd.png)

Current behavior:

Creating new expense lines from an expense report leads to a confusing screen.

This behaviour is very confusing for users, especially users that are used to the version 8 where all expense lines are created from the expense report..

Expected behavior:

I propose to either
- hide the create button, so users understand they must must go somewhere else to create expense lines
- or have the create button display a less confusing screen

**Comment by sbidoul** [comment]
OPW 743690

**Comment by Yenthe666** [comment]
@sbidoul what was the response on 743690?

**Comment by sbidoul** [comment]
@Yenthe666 *Since it is not blocking point at the moment, it is considered to be improved in future release*

**Comment by Yenthe666** [comment]
I guess that handles everything and that this can be closed. Thanks for the feedback!

**Comment by sbidoul** [comment]
@Yenthe666 why closing? I've not been informed about a solution on any version.

**Comment by Yenthe666** [comment]
@sbidoul well, if you prefer I can keep it open but I already know how this will end. The bug will be kept open and if somebody from Odoo ever picks this one up and improves it they won't bother looking back at this bug report so it'll stay open.
If it is on the OPW then there is a task for it in the main Odoo database so they should handle it from there.
Do you really want me to keep it open?

**Comment by sbidoul** [comment]
OPW has closed it, I've not been given any pointer to track resolution on any version.

This scenario happens all too often:
- An issue is reported on stable. 
- It's acknowledged but not considered bad enough to warrant a fix on stable
- It's closed and forgotten until someones rediscovers it...

So yes unless it's resoved in a later version, it should be kept open, IMHO.

**Comment by Yenthe666** [comment]
Yep, I agree that this happens way too often.. I'll be discussing these things with some of the Odoo guys in february too.
@mart-e for now, perhaps you could introduce a quick fix in the master for this? Its not something big but let us be honest it is a neat improvement.

**Comment by jem-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/2cd74cdd0da1c4403e73ef5f1f2a666684fbe467
It will required a module update to have the fixed applied.
Regards

**Comment by sbidoul** [comment]
Thanks!

Le ven. 19 janv. 2018 à 15:40, Jérome Maes <notifications@github.com> a
écrit :
