### ISSUE TITLE
Can't reinstall livechat module after uninstalling it

### ISSUE THREAD

**Issue by tarpediem** [odoo/odoo#17006]
Impacted versions:10.0

Steps to reproduce:
install fresh odoo, install livechat module from apps
use livechat on website, 
uninstall livechat module from apps
reinstall livechat module

Current behavior:
I get a popup telling me 
Odoo Warning - Validation Error
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: im_livechat_channel - im.livechat.channel]

Expected behavior:
livechat should reinstall correctly

Video/Screenshot link (optional):
![capture](https://cloud.githubusercontent.com/assets/1893451/26094325/bf5f5f34-3a43-11e7-80b4-1fc2dd1be997.PNG)

**Comment by Yenthe666** [comment]
Hi @tarpediem,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 10 and it works fine out of the box.
Can you please update your Odoo codebase and database and try again? If you can still reproduce it on an official runbot (runbot.odoo.com) then please respond back here.

Regards,
Yenthe
