### ISSUE TITLE
[17.0] spreadsheet_edition: when you download the file it is not the last version

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#170073]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to runbot enterprise
- Crate a new dashbord
- Make some edit
- Download the file
---> Issue the file include the first version (and not the last)

<img width="959" alt="image" src="https://github.com/odoo/odoo/assets/16716992/fbc2fdcd-31eb-4038-981a-7bc7f101e08b">

### Support Ticket

#4000870

**Comment by fmdl** [comment]
ping @LucasLefevre

**Comment by LucasLefevre** [comment]
Hello @fmdl 

As answered on the ticket, it's the expected behavior.
If you want the current version: open the spreadsheet in debug mode, then use the menu File > Download as Json
