### ISSUE TITLE
Package broken on Debian Stretch (9.0) and Ubuntu Zesty (17.04): python-pypdf not installable 

### ISSUE THREAD

**Issue by pksadiq** [odoo/odoo#17002]
Impacted versions: 10.0 nightly Debian package

Odoo fails to install on Debian testing due to missing dependency python-pypdf. This isn't
present in Debian testing, python-pypdf2 is available instead, which is a python2 module.
If this is what Odoo is using, the package may add a dependency on either
python-pydf or python-pypdf2, so it shall get installed fine on both new and older systems.

Thanks

**Comment by Yenthe666** [comment]
@sle-odoo most likely for you as it is requirement related.

**Comment by pksadiq** [comment]
Seems like the module name has been changed to `PyPDF2` from `pyPdf`. So a conditional import of the module may also be required.

**Comment by quantentunnels** [comment]
Since Debian 9 aka Stretch is officially out, this should definitely be fixed.

**Comment by kurtjcu** [comment]
I seem to be having the same problem on Ubuntu server 17.04.
https://github.com/odoo/odoo/issues/17948

**Comment by odony** [comment]
@sle-odoo We'll probably need conditional imports and updated packages for debian 9 and ubuntu 17.04. Last time I checked python-pypdf2 was a drop-in replacement for python-pypdf as far as we care (pending the conditional imports).

**Comment by AlexisArnal** [comment]
Hello I hope you are well. Is there any progress with this problem ???
I have the same problem on Ubuntu 17.04. I did install python-pypdf with pip and It shows me the same error.

**Comment by cpipero** [comment]
I did install Stretch too (I should have read carefully before) and now I'm stuck too...

**Comment by jj3666** [comment]
Coming up on two months. Also with the wkhtmltopdf issue on the new platforms. Please state LTS support only if you do not plan on intermediaries for Ubuntu. But Debian is a NEW release. Please, give this some attention.

**Comment by gdgellatly** [comment]
IMHO the issue with wkhtmltopdf is more old/safe documentation for issues
that never affected or now no longer affect Linux. Lots of community have
used stretch for a long time with 12.4.

Wkhtmltopdf 12.4 is just fine, however for it to produce exact same output
as 12.1 or whatever the recommended version is you need to disable smart
shrinking, due to a bug in old version of wkhtmltopdf.

**Comment by Yenthe666** [comment]
@sle-odoo any update?

**Comment by dhiru1602** [comment]
Why not maintain separate packages for distributions? dists/zesty and dists/stretch

**Comment by zeroheure** [comment]
@dhiru1602 it is not that simple, Odoo code still depends on te old unmaintained python-pypdf

However, there is an easy workaround : create a fake python-pdf package and install python-pyPdf from Pipy (Python repository). All of this will be done as root.

- install `equivs` to create fake packages and `python-pip`to install package from Python repository
- run `equivs-control python-pypdf`, this will create and populate the file python-pypdf
- edit the file (dot and space under Description are mandatory) like below :
```deb
Section: python
Package: python-pypdf
Version: 1.13
Description: fake package to provide python-pypdf
 python-pypdf will need to be installed with pip
 .
 python-pypdf2  does not provide python-pypdf
```
- run `equivs-build python-pypdf` this will create the fake package python-pypdf_1.13_all.deb 
- install the package with `dpkg -i python-pypdf_1.13_all.deb`
- run `pip install pyPdf`
- restart Odoo

**Comment by Yenthe666** [comment]
@sle-odoo any update here? (cc @d-fence as it is packaging  / dependency related)

**Comment by pedrobaeza** [comment]
Don't we have still news?

**Comment by mhadiahmed** [comment]
am on Debian and this work for me 
download the package from this site 
https://debian.pkgs.org
download python-pypdf and it Depends on python-support so download that one two
after that install  odoo 10 and it will work
