### ISSUE TITLE
[8.0] tax not recomputed after copy invoice

### ISSUE THREAD

**Issue by colmeirin** [odoo/odoo#17018]
Impacted versions:
8.0

Steps to reproduce: 
Create an invoice with the Tax calculation rounding method=Round per line:
line 1 263.44 and apply a 21% tax 
line 2 28.92 and apply a 21% tax
Subtotal = 292.56
Taxes = 61.43
Total = 353.99

Now, change the Tax calculation rouding method to Round globally
Copy the past invoice and validate it, the total will be 353.99
Copy again the past invoice, edit it, force tax recompute and the total will be 354.00.

Current behavior:
Not recomputing taxes after a copy and the rounding method has changed

Expected behavior:
Recompute taxes properly

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @colmeirin,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
