### ISSUE TITLE
Monetary fields can't format numbers without currency

### ISSUE THREAD

**Issue by Saftsack** [odoo/odoo#17014]
Impacted versions: 10.0

Steps to reproduce: 
Set language settings with a ' as seperator and change the number of digits after the decimal to 2. 
Create a new report with QWeb. 
Add price_subtotal field to the report.
Remove the currency.
Print the report.

Current behavior:
Instead of " ' " as seperator, you will get "," . And there will be only one digit after the decimal point.

Expected behavior:
" ' " as seperator for thousands, and 2 digits after the decimal point.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The conditions you are using for reproducing the error leads irremediably to it, as you are forcing things that mustn't happen:

* Field with currency
* Decimal separator that is for language, not for currencies

and you are also omitting a lot of information like the report, the model, and so on, so we can't consider this as a real issue, and thus I'm closing it.

Feel free to open a new one with more details and with real conditions that leads to an error, but not removing some of the requirements (like having a currency field when displaying monetary fields).

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
