### ISSUE TITLE
[17.0] website_sale: dropdown arrow is invisible after selection when using a darker theme

### ISSUE THREAD

**Issue by rmau-odoo** [odoo/odoo#170173]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to website(eCommerce) 
- Click on the STORE tab.
- Once you are in the store tab, click on the 'Edit' option to edit the website and select Categories: Left and Collapse Categories: enable.
- Go to the theme, in the light and dark themes select a darker version like black or gray for the first option.
- The drop down appears for categories which are not selected but when selected this disappears.

It works when using the following theme:
![image](https://github.com/odoo/odoo/assets/143412006/8328c1b4-5ddc-4925-a4dc-e8393c355f55)
![image](https://github.com/odoo/odoo/assets/143412006/258f4096-ab73-46d9-8645-141c54f8bb0d)

It doesnt work when the drop down is selected as in this case:

![image](https://github.com/odoo/odoo/assets/143412006/e6c5d814-519c-4db5-915f-0cc507e2b315)
![image](https://github.com/odoo/odoo/assets/143412006/11a2a42a-0fb9-47d8-9271-88989380775f)

**Comment by arslan-f** [comment]
@rmau-odoo I would like to work on this issue. Can this be assigned to me and I will start working today.

**Comment by Mit2561** [comment]
Hi @rmau-odoo, can i resolve this issue?
