### ISSUE TITLE
[10.0] Fields using <label for...> tag do not transform string name correctly

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#17021]
### Impacted versions:
At least 10.0

### Steps to reproduce:
1. Create relational field without `string` parameter, i.e.:
```python
server_id = fields.Many2one('some.model')
```

2. create a form view where you use the `<label>` tag, i.e:
```xml
....
    <div>
        <label for="server_id" class="oe_edit_only"/>
        <field name="server_id"/>
    </div>
....
```

### Current behavior:

The field is shown in the view with the name "Server id"

### Expected behavior:

The name of the field should be shown as "Server"

### Video/Screenshot link (optional):

![seleccion_078](https://cloud.githubusercontent.com/assets/442938/26119159/545d9cae-3a3a-11e7-99a6-ed836e6bfff2.jpg)

**Comment by Yenthe666** [comment]
Hi @ebirbe,

Thank you for your report.
While this is no bug or real issue I do think it would be an improvement. Almost nobody likes to have id in a title.
@mart-e perhaps something for V11? I'll label it wishlist for now.

Regards,
Yenthe

**Comment by adekock11** [comment]
The exact point where this happens is [here in fields.py](https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L471-L473).
```
            if not self.string and not self.related:
                # related fields get their string from their parent field
                self.string = name.replace('_', ' ').capitalize()
```

It will then be necessary to change it to:
```
            if not self.string and not self.related:
                # related fields get their string from their parent field
                self.string = name.replace('_id', '').replace('_', ' ').capitalize()
```

Perhaps there should also be a check if the field is a One2many or Many2many, then only do the `replace('_id', '')`. Seems like a cool feature if it is well documented in Odoo docs that this is the behaviour.

**Comment by mart-e** [comment]
Hello,

It was already done at f507fc95c7b6c8e347aca61307c90238d385a106
Will be in v11
