### ISSUE TITLE
Images from new modules can't be accessed unless restart

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#17079]
Impacted versions:
10
Steps to reproduce:
Find a module with images in its /static directory (for example snippet_google_map). Copy that module to the addons directory (/var/lib/odoo/addons/10.0 on RedHat). Update the application list. Open the module Information tab.

Current behavior:
Odoo display the HTML description but without images. Trying to display image only result on a 404.
Need to restart Odoo in order to display images.

**Comment by Yenthe666** [comment]
@d-fence this might be something for you to check on RedHat?

**Comment by pedrobaeza** [comment]
IMO this is something expected, as you are modifying the contents of a static directory that is only loaded at the start. Reloading everything on module list update would mean a greater load time with not too much benefit.

Closing then by the reasons above.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Comment by zeroheure** [comment]
@pedrobaeza I understand your point. 
But the problem is very much from an end user point of view on the module documentation or description :
- the end user doesn't understand why the images are visible if the module is not yet installed, but not after the install.
- how the user can configure or understand the module if the images are not visibles ?
- you can't easily restart Odoo if the ecommerce features are installed.

IMHO this should be considered again.

**Comment by pedrobaeza** [comment]
But as said, the problem doesn't happen with modules that are already there in addons directory when starting Odoo, so it's not a big problem most of the time. What is a use case where this doesn't happen?

**Comment by gdgellatly** [comment]
Any OCA pip install.

Besides does one really need to reload everything.  Surely the main concern is just the new modules found in the update.

**Comment by zeroheure** [comment]
@pedrobaeza You're right. I fully agree.

**Comment by pedrobaeza** [comment]
@gdgellatly if you are manipulating pip, then you can restart Odoo service without problem.

**Comment by gdgellatly** [comment]
@pedrobaeza it is still annoying. And personally to me it is a ui bug.
Update Modules  list should Update Modules List. Aside from images why else
would you need to restart the server?
