### ISSUE TITLE
Define default settings for follower notifications

### ISSUE THREAD

**Issue by LeDistordu** [odoo/odoo#17073]
If we add a follower to a partner/contact or anything else the follower can define be himself when he will get mail notifications. In default setting none of the options is active. We want to predefine some situations where automatically  notifications are set and the follower can manually disable this option.

We could notfind where to make such a setting.

**Comment by Yenthe666** [comment]
Hi @LeDistordu,

You can create a custom module to achieve this.

Regards,
Yenthe
