### ISSUE TITLE
[master] Cascade One2many failing when adding record to the leaf model

### ISSUE THREAD

**Issue by bokbokan** [odoo/odoo#17086]
**Impacted versions:**
master

**Steps to reproduce:**
Sample code:
```
class Many2(models.Model):
    _name = 'many2'

    name = fields.Char('Name')
    many_id = fields.Many2one('many')

class Many(models.Model):
    _name = 'many'

    name = fields.Char('Name')
    one_id = fields.Many2one('one')
    many2_ids = fields.One2many('many2', 'many_id')

class One(models.Model):
    _name = 'one'

    name = fields.Char('Name')
    many_ids = fields.One2many('many', 'one_id')
```
Sample view:
```
<record id="one_view" model="ir.ui.view">
    <field name="model">one</field>
    <field name="arch" type="xml">
        <form>
            <field name="name"/>
            <field name="many_ids">
                <form>
                    <field name="name"/>
                    <field name="many2_ids">
                        <form>
                            <field name="name"/>
                        </form>
                    </field>
                </form>
            </field>
        </form>
    </field>
</record>
```
Creating new cascading records works fine but after saving, adding new outer record (many2 model) from existing inner records (many model) always fails.
Working in V10.

**Current behavior:**

Failing: Uncaught TypeError: Cannot read property 'views' of undefined

> http://127.0.0.1:8069/web/content/281-6e9555a/web.assets_backend.js:2267
> Traceback:
> TypeError: Cannot read property 'views' of undefined
>     at Class._applyX2ManyChange (http://127.0.0.1:8069/web/content/281-6e9555a/web.assets_backend.js:2267:838)
>     at Class._applyChange (http://127.0.0.1:8069/web/content/281-6e9555a/web.assets_backend.js:2257:356)
>     at Object.<anonymous> (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:3975:295)
>     at Object.<anonymous> (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:802:681)
>     at fire (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:796:299)
>     at Object.add [as done] (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:797:467)
>     at Array.<anonymous> (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:802:649)
>     at Function.each (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:625:767)
>     at Object.<anonymous> (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:802:560)
>     at Function.Deferred (http://127.0.0.1:8069/web/content/248-fa66080/web.assets_common.js:803:194)

**Expected behavior:**

New outer record (many2 model) should be added without problem

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment]
Hi @bokbokan,

Thanks a lot for your bug report.
In the meanwhile this issue seems to be fixed in V11.
P.S: Master versions contain bugs all the time as it is actively developed on.

Regards,
Yenthe
