### ISSUE TITLE
Can not edit the forum module's about block or guidelines

### ISSUE THREAD

**Issue by watermelonjuice** [odoo/odoo#1708]
The guidelines provided by the forums module is very specific to the Odoo community. Site owners would probably want an easy way to change them.
![screenshot from 2014-08-10 00 55 06](https://cloud.githubusercontent.com/assets/5452111/3868541/67aedd1e-204c-11e4-9349-dcbe72e51a9c.png)
![screenshot from 2014-08-10 00 55 11](https://cloud.githubusercontent.com/assets/5452111/3868542/67cbb646-204c-11e4-8a98-7be07265fedf.png)

**Comment by Yenthe666** [comment]
Hi @watermelonjuice,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
