### ISSUE TITLE
[8.0][9.0c] Month view calendar create event in wrong day

### ISSUE THREAD

**Issue by sadamo** [odoo/odoo#17080]
Impacted versions:
- 8.0
- 9.0c

Steps to reproduce:
- With any user set the timezone to America/Sao_Paulo
- In calendar month view click in some day to create new event
- Click in edit to see the wrong date
 
Current behavior:
- The form view shown date is the day before the selected day

Expected behavior:
- The form view shown date should be the selected day 

Video/Screenshot link (optional):
Clicked in day 31
![calendar1](https://cloud.githubusercontent.com/assets/8259094/26210380/c2c82ef2-3bc5-11e7-9a6a-d73483871b7a.png)

Show day 30
![calendar2](https://cloud.githubusercontent.com/assets/8259094/26210390/cfa3129a-3bc5-11e7-93e9-532042a9327d.png)

**Comment by Yenthe666** [comment]
Hi @sadamo,

Thank you for your report!
This is however not a bug in Odoo, you can configure this yourself. You can do this under Settings > Translations > Languages (requires you to have developer mode on):
![image](https://cloud.githubusercontent.com/assets/6352350/26213878/d900f32c-3bfa-11e7-8b8d-662762bcfd6e.png)

Regards,
Yenthe

**Comment by sadamo** [comment]
Hi @Yenthe666!

Thanks for the quickly answer, but maybe I was not clear in the report.
The problem is if you click in day 10 to create a new event and then in edit to open the form view, the event date goes to day 9.
