### ISSUE TITLE
In Odoo 10 Community version, the attribute price extra does not get updated if we enter any new values and sets back to 0.00. What is the fix?

### ISSUE THREAD

**Issue by manpreetdash** [odoo/odoo#17097]
Impacted versions: 10

Steps to reproduce:

Current behavior: attribute price extra does not get updated

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @manpreetdash,

Thanks for your report.
I've just tested this and it works fine without any problems:
![image](https://cloud.githubusercontent.com/assets/6352350/26348665/b60f11f8-3fad-11e7-8550-94acd7741f42.png)

Can you please try to reproduce this on an official Odoo instance (runbot.odoo.com) or after updating your whole Odoo environment?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in almost a year.

Regards,
Yenthe
