### ISSUE TITLE
sale_stock:  company_id is not saved after changing warehouse

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#171]
at file
 odoo / addons / sale_stock / sale_stock_view.xml 
we have: 

```
                    <field name="company_id" position="replace">
                        <field name="company_id" readonly="True"/>
                    </field>
                    <field name="client_order_ref" position="after">
                         <field name="warehouse_id" on_change="onchange_warehouse_id(warehouse_id)" options="{'no_create': True}" groups="stock.group_locations"/>
                    </field>
```

where

```
    def onchange_warehouse_id(self, cr, uid, ids, warehouse_id, context=None):
        val = {}
        if warehouse_id:
            warehouse = self.pool.get('stock.warehouse').browse(cr, uid, warehouse_id, context=context)
            if warehouse.company_id:
                val['company_id'] = warehouse.company_id.id
        return {'value': val}
```

So, after changing warehourse, company is changed.
But becase company_id field is readonly, after clicking "save" only warehourse is saved.

I think readonly="True" on company_id should be removed

**Comment by rafaelbn** [comment]
cc @pedrobaeza @antespi @Yajo @sergio-incaser @carlos-incaser

**Comment by rafaelbn** [comment]
@yelizariev it's much more effective if you make a PR to Odoo fixing it.
Also you can make a PR to https://github.com/OCA/OCB fixing the problem and have it solve it

**Comment by JKE-be** [comment]
@rafaelbn, @yelizariev  it's not an issue for Odoo... so don't need to be fixed. Odoo don't save the readonly field, it is by design.
Confirmed by @KangOl (https://github.com/odoo/odoo/issues/171#issuecomment-45533080) and https://bugs.launchpad.net/openobject-client/+bug/378824/comments/2

**Comment by andreinl** [comment]
@JKE-be, so storing Warehouse with company_id from another Company is not a problem?

**Comment by JKE-be** [comment]
@andreinl not exactly. The fact that field readonly is not saved is not an issue. The fact that you can store "Warehouse with company_id from another Company" yes. But the discuss was confusing. The fix as suggest @KangOl  will be to change the field "company_id" to be a stored related field. or keep the onchange but remove the readonly and add the invisibility.

**Comment by andreinl** [comment]
@JKE-be The other solution can be intercept create() and write() and write company_id from warehouse. Users will always see the right company as onchange works fine. It seems to me that this is less intrusive solution.

**Comment by Yenthe666** [comment]
Dear @yelizariev,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by yelizariev** [comment]
@Yenthe666 
this issue is for 8.0 and need updates mentioned here https://github.com/odoo/odoo/issues/171#issuecomment-198464364

**Comment by Yenthe666** [comment]
@JKE-be and @KangOl could you guys give feedback on this and get this going?

**Comment by Yenthe666** [comment]
Hi @yelizariev ,

Again a bit thank you for the report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
