### ISSUE TITLE
[10.0] usability regression: searching by journal code does not work

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#17102]
Impacted versions:

10.0

Steps to reproduce:

In a Journals combo box (eg on invoices), searching by journal short code does not work. 

In V8 it did work:

![image](https://cloud.githubusercontent.com/assets/692075/26247233/40a74dbc-3c9d-11e7-8c80-5906a200f044.png)

In v10 it does not work;

![image](https://cloud.githubusercontent.com/assets/692075/26247204/17055e86-3c9d-11e7-9dc0-f7e69c4db13a.png)

For customers with a large number of journals, it is important.

**Comment by sbidoul** [comment]
OPW 744362

**Comment by Yenthe666** [comment]
@sbidoul what response did you get on ticket 744362?

**Comment by sbidoul** [comment]
It has been resolved. Closing.
