### ISSUE TITLE
How to create stock moves for configurational products in odoo ( pledra's product configurator wizard ) ?

### ISSUE THREAD

**Issue by manpreetdash** [odoo/odoo#17108]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

You are talking about a non official module so, please, check with the author of the module.

Regards
