### ISSUE TITLE
[10.0] "Send to shipper" button almost useless if we cannot change carrier

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#17115]
### Impacted versions:
10.0

### Steps to reproduce:
On a new database with demo data and DHL delivery module (or any integrated carrier), go on a delivery stock picking operation, select DHL and validate. Once validated, there is a link beside the tracking number to cancel the label. If you click it, the label will be cancel on the carrier system.

### Current behavior:
After cancelling a label, there is no way to change the carrier to another one. There is a button called "Send to shipper", but it will allow you to send the same information to the carrier. 

### Expected behavior:
To make sure we can correct the information to send to the shipper, allow changing the carrier if the label has previously been cancel.

**Comment by pedrobaeza** [comment]
As this is something about an enterprise module, please open the corresponding OPW ticket for this to be treated by the enterprise team.
