### ISSUE TITLE
Measures and col_group_by not worked in pivot views

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#17113]
**Impacted versions:**
9, 10. Tested today on runbot
**Steps to reproduce:**
Go to purchase analysis, use Favorites Filters, measures no changed
**Current behavior:**
Favorites filter not change measures or col_group from context
**Expected behavior:**
Keys col_group_by and measures read from context on favorites filters defined by user
**Video/Screenshot link:**
**Filter Average Delivery Time V8:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253677/cf59ec46-3c79-11e7-8fcc-935917f17ec4.png)
**Filter Average Delivery Time V9:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253695/de005532-3c79-11e7-8d0d-9117c52762e1.png)

**Filter Monthly Purchases V8:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253762/0b5e22fc-3c7a-11e7-8e4f-22160c5cb1a6.png)

**Filter Monthly Purchases V9:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253769/12b97718-3c7a-11e7-9bfa-07561ce909ea.png)

**Price Per Supplier V8:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253796/2839a54a-3c7a-11e7-8a1a-058dcabf47d4.png)

**Price Per Supplier V9:**
![image](https://cloud.githubusercontent.com/assets/7775116/26253805/2f036942-3c7a-11e7-86dd-bfd61cb79ac4.png)
Other issue #14316
PR only for measures, but not col group: #7692

Please review

**Comment by celm1990** [comment]
Correction Here #17119 Please merge

**Comment by ged-odoo** [comment]
@celm1990 The PR is merged. Thank you.
