### ISSUE TITLE
[10.0] product price with pricelist discount policy = without_discount in multi company and multi currency

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#17116]
Impacted versions:
10
Steps to reproduce:
1. Make  company A currency = USD
2. Create new company B with currency = EUR
3. Update USD rate in company B to be = 2
4. Create new product X sales price = 100  USD and remove company 
5. Create pricelist for company B with currency EUR and discount 10% and choose "Discount policy" to be "Show public price & discount to the customer"
6. create sales order with previous pricelist and choose product X

Current behavior:
 - Appear 100 as unit price and discount 10% 

Expected behavior:
- Appear 50 as unit price and discount 10%

Notes:
When change "Discount policy" to be "Discount included in the price" and create sales order appear 45 as unit price so i think it calculate correct with this option

**Comment by pedrobaeza** [comment]
I see you are mixing companies, currencies and pricelists and this is advocated to fail, as the thing you are trying to do are not allowed between the companies. Please define a clear and real use case with one company and reproducible on runbot that can be traced.

Meanwhile, I close this issue.
