### ISSUE TITLE
Wkhtmltopdf generate empty file 

### ISSUE THREAD

**Issue by diegorichi** [odoo/odoo#17120]
Impacted versions:
9
Steps to reproduce:
Excecute 

report_obj.get_pdf(self, 'any_report_name')

Anda no log file, nothing. Pdf is generating 0kb

Wkhtmltopdf 0.12.1 / odoo 9

On prompt can exec wkhtmltopdf www.google.com google.pdf and work fine 

Current behavior:
0kb pdf 
Expected behavior:
Normal pdf report 
Video/Screenshot link (optional):

**Comment by diegorichi** [comment]
This is on Ubuntu 14.04 server. I have install wkhtmltopdf with apropiate package. 

Ask some thing, i response quickly. 

Thanks

**Comment by ddfs** [comment]
install version 0.12 and that's it. doesn't matter what operating system or version of odoo you are running. i have 3 setups, 2 v10 and 1 v8 running on same server. no probs.

**Comment by diegorichi** [comment]
Ok, but the problem persist. 
Thanks for your reply

**Comment by diegorichi** [comment]
In temp dir, i see the html files generated. But pdf still having 0kb

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/9.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by ddfs** [comment]
@diegorichi  can you try to add  "report.url" in parameters with 127.0.0.1:PORT_NUMBER

**Comment by diegorichi** [comment]
@ddfs thanks for your reply.
I added the parameter and it started working!.
Thanks again.
