### ISSUE TITLE
error when creating a new project

### ISSUE THREAD

**Issue by DJzx** [odoo/odoo#1712]
Error message when creating a new project

The following fields are invalid:
Accept Emails From
Currency

Workaround assign a parent project and a new project can be created that way

**Comment by Yenthe666** [comment]
Hi @DJzx,

Thank you for your report.
This should be fixed by https://github.com/odoo/odoo/commit/d68537022fc03baf59af29cb7cc8f9c5aa91a7b2
I can no longer reproduce this bug anymore.

Regards,
Yenthe
