### ISSUE TITLE
[10.0] POS doesn't load on osx 10.12.4 sierra (Stucking with "loading pictures")

### ISSUE THREAD

**Issue by spacegoing** [odoo/odoo#17122]
Impacted versions:
odoo 10.0

Steps to reproduce:
Install Odoo using docker.
All configurations are the same with document.
Install POS app.
Click on POS app.

Current behavior:
the ui is stucking on "loading pictures"

Expected behavior:
Enter POS system

Video/Screenshot link (optional):
<img width="1066" alt="screenshot 2017-05-20 10 42 18" src="https://cloud.githubusercontent.com/assets/5180020/26272372/0df0b4f6-3d49-11e7-8757-76193fb6ff39.png">

Please let me know if there is any info I can provide

**Comment by lukebranch** [comment]
@spacegoing ,

I'm just another user like yourself, however I would suggest the best possible place to start for troubleshooting would be your logs. Make sure your log level is set to debug in your /etc/odoo-server.conf file like this:

log_level = debug

I would tail your logs (please change the path depending on the log path specified in your odoo-server.conf/openerp-server.conf file):

tail -f /var/log/odoo/odoo-server.log

try running the process to reproduce the issue while looking at the tail of your logs in a terminal and see if it provides you with any hints.

I would also suggest trying one of the runbots online to see if you can reproduce the same behaviour in the runbots:

http://runbot.odoo.com/runbot

click the blue arrow button next to the latest build of the 10.0 branch. This is often a good way to check if it's a configuration issue on your end (in which case it will work fine on the runbots), or whether perhaps it is an issue with the latest code in your branch.

**Comment by jorenvo** [comment]
I tested opening the POS on macOS Sierra in Safari v10.1.1 and it worked as expected. Are you using any non-standard modules?

**Comment by Yenthe666** [comment]
@spacegoing are you using any non-standard Odoo modules? Can you reproduce it on an official runbot (runbot.odoo.com)?

**Comment by sle-odoo** [comment]
Closing as this seems to have been fixed in the meantime. If you're still facing the issue, feel free to comment.
