### ISSUE TITLE
hr_expense_check no amount in words on check

### ISSUE THREAD

**Issue by raycollazo** [odoo/odoo#17128]
Even though I noticed the latest commit on the hr_expense_check module says it was related to this issue. In Version 10 Enterprise with the latest update, printing checks from Expenses results in no words on the check.

Impacted versions:  Enterprise 10

Steps to reproduce:  Pay Expense Report, Choose Check, Print Check

Current behavior:  Currently if you are going to print a check, the check will print with no amount in words

Expected behavior: Check should print normally and display the amount in words

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @raycollazo,

Thank you for your report.
Are you talking about the report for the expense? Because that looks fine:
![image](https://user-images.githubusercontent.com/6352350/34440890-9f5b2894-ecb8-11e7-8316-0897a3880aff.png)
Please do add more feedback (ideally a video) if I'm wrong.

Regards,
Yenthe

**Comment by raycollazo** [comment]
Hey Yenthe, this has to do with actual printing of Checks (to reimburse employee). The amount in words does not print on check when you follow the steps above. I'm pretty sure this was fixed somewhere along the line. We originally had to create a new view and called it **ckus_check_address** and later updated the **ckus_check** view to inherit **ckus_check_address**. I'm not sure what the original was but I will paste what my ckus_check_address is today (working) in case anyone comes across this.
I'm also pasting screenshots of ckus_check to show current working code and inherited view.
![ckus_inherited](https://user-images.githubusercontent.com/17937809/35481271-65adbb64-03ee-11e8-888d-3273a1d016c1.png)
![ckus_code](https://user-images.githubusercontent.com/17937809/35481272-65b7d89c-03ee-11e8-8ac9-e3a8aab58727.png)

ckus_check_address code:

`<data>
    <xpath expr="//div[@class='ckus_amount_in_word']" position="after">
        <div style="font-size: 95%; padding-top: 175px; padding-left: 62px;">
            <div  t-field="o.partner_id.name"/>
            <div t-if="o.partner_id.street"><span t-if="o.partner_id.street" t-field="o.partner_id.street"/> <span t-if="o.partner_id.street2" t-field="o.partner_id.street2"/></div>
            <div>
                <span t-if="o.partner_id.city" t-field="o.partner_id.city"/><span t-if="o.partner_id.state_id.code">,</span> <span t-if="o.partner_id.state_id.code" t-field="o.partner_id.state_id.code"/> <span t-if="o.partner_id.zip" t-field="o.partner_id.zip"/>
            </div>
            
        </div>
    </xpath>
</data>

**Comment by Yenthe666** [comment]
@raycollazo so this issue should have been fixed already?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this as there has been no feedback in a few months.
I think this has been solved in the meanwhile.
