### ISSUE TITLE
[10.0] Wrong "Ordered qty" on delivery slip report

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#17145]
Impacted versions: 10.0

Steps to reproduce:
1) Connect to runbot v10 as admin
2) Create a new stockable product "Test product1"
3) Click on "Update quantity on hand" and set the new qty on hand to 20
4) Create a quotation for Agrolait with 1 line:
- Product = "Test product1"
- Qty : 50 
-> you get the warning about the fact that you are trying to sell 50 units but you only have 20 units.
5) Click on "Confirm sale"
6) Go to the related picking. In the operation line, the "Todo qty" is 20. Set the "Done quantity" to 20 and validate. In the pop-up, select "Create backorder".
7) Print the delivery slip: you have 1 line with:
- Ordered qty = 20 -> this is wrong, the ordered qty is 50 !
- Delivered qty = 20

**Comment by jco-odoo** [comment]
In your case, it is the ordered_qty on the stock move that counts and not the ordered_qty on the pack operation.  If I look at the code of the report, the two values are used and shown.

**Comment by Yenthe666** [comment]
Closing this bug report as it has been answered by jco.
