### ISSUE TITLE
[9.0] ir.attachment edge case could remove all your data by accident

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#17183]
**Impacted versions:**
9.0

**Steps to reproduce:**
- Make sure that your attachments are stored in the filestore, meaning the `ir.config_parameter` with the key `ir_attachment.location` should not be `db`
- Change the `ir.config_parameter` with the key `ir_attachment.location` to `db`
- Call the [built in Odoo method](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_attachment.py#L59-L73) `self.env['ir.attachment'].force_storage()`

**Current behavior:**
- If anything goes wrong[1] when the `force_storage()` method is called, the `ir.attachment` records will have been [deleted from the filestore](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_attachment.py#L187), but because of a traceback the database will roll back
- You are then left with no file under the filestore and also no data in the database, meaning your `ir.attachment` records are gone forever

**Expected behavior:**
- A `self.env.cr.commit()` should be executed directly after a file has been removed from the filestore and successfully inserted in the database, before the next `ir.attachment` record is processed

[1] An example case where "something" might go wrong:
- Install Recruitment
- Add an attachment to any `hr.recruitment` record
- Uninstall Recruitment
- Change `ir_attachment.location` to `db`
- Call `self.env['ir.attachment'].force_storage()`
- Traceback will occur [here](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_attachment.py#L311) since an `hr.recruitment` model doesn't exist anymore

**Comment by Yenthe666** [comment]
Hi @adekock11,

Thank you for your report. This does look like an issue to me.
@mart-e not sure who to have a look at this one. I guess you?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Also relevant for @xmo-odoo and @odony

**Comment by mart-e** [comment]
Have you been able to reproduce this bug? I wasn't.
And reading the code, I don't think it should be an issue as the `check` is called before the `_file_delete`.

**Comment by odony** [comment]
Removed the plus sign from "9.0+" in the description, as even if the issue gets confirmed in 9.0, it is very unlikely that the phenomenon happens in 10.0, as file deletion is now [based on a deferred GC](https://github.com/odoo/odoo/blob/8fb203f7c692c0262a579575127b429e858ff3a2/odoo/addons/base/ir/ir_attachment.py#L120-L122).

**Comment by adekock11** [comment]
@odony thanks for the link to version 10.0. That is indeed a well thought out way of doing it - much better.

**Comment by Yenthe666** [comment]
I guess we can conclude that this is fixed/handled in 10.0 and up.
I tried this on V9 but wasn't able to reproduce it right away either.
