### ISSUE TITLE
Singleton error in company when country is changed

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#17180]
Impacted versions:
saas-14

Steps to reproduce:
1.- Install l10n_mx_edi (With enterprise)
2.- Configure the company address with country = Mexico
3.- Save the record
4.- Change the country (Ej. Albania)
5.- Save the record

Current behavior:
Traceback:
<img width="1280" alt="captura de pantalla 2017-05-24 a la s 03 01 39" src="https://cloud.githubusercontent.com/assets/7606656/26392766/5768cd62-402d-11e7-80f9-c050aef8dbf1.png">

Expected behavior:
Company country is updated

Video/Screenshot link (optional):
https://youtu.be/YLpSQlFHWTk

**Comment by luistorresm** [comment]
FYI @nhomar 

CC: @qdp-odoo

**Comment by rco-odoo** [comment]
Fixed by 1095744e7f058ad370315ef80d56b225376e7b99.
