### ISSUE TITLE
Showing all supplierinfo related to product template in products

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#17182]
Impacted versions:10.0

Steps to reproduce:Activate product varients. Create a product template with some varients. For each varients set different supplierinfo. 

Current behavior: Each variant shows  supplierinfo added to the other varients also
Expected behavior: Should show only its supplier info

Video/Screenshot link (optional):

**Comment by omalbastin** [comment]
I think, by redefining seller_ids in product.product will solve this issue.
```
class ProductProduct(models.Model):
    _inherit = 'product.product'
    seller_ids = fields.One2many('product.supplierinfo', 'product_id', 'Vendors')
```

**Comment by jco-odoo** [comment]
There are some ideas for master to put it also on the product variant level, but then we need to think well about how to display them.  But in stable, it is going to stay this way.
