### ISSUE TITLE
[8.0] Cannot delete invoices that have been validated before

### ISSUE THREAD

**Issue by anassahmed** [odoo/odoo#17193]
Impacted versions:
8.0

Steps to reproduce:
1. Install `account_cancel` first.
2. Set _Allow Canceling Entries_ to *True* in the Sales Journal.
3. Create a customer invoice and validate it to take a number and generate a Journal Entry (account move).
4. Cancel the invoice.
5. Delete the invoice.

Current behavior:
Raises exception: "You cannot delete an invoice after it has been validated (and received a number).  You can set it back to "Draft" state and modify its content, then re-confirm it."

Expected behavior:
Deletes the invoice without errors.

Video/Screenshot link (optional):
None

Additional info:  
The real reason behind this issue is that you don't reset the `internal_number` on canceled invoice even if the moves that has this `internal_number` has been canceled and deleted.
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L1011  
This is where you set the `internal_number` for the first time:
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L980  
This is where you raise the exception:
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L423

The question is: Is there a reason to justify this behavior?

**Comment by bistaray** [comment]
The reasons used to justify this behavior:

- The Invoice may have been sent to a Customer
- Deleting Invoices that have been assigned a Number may be against the law / against good book keeping practices
- Gaps in the Invoice sequence may be against the law / against good book keeping practices

Many Accounting packages follow this same design.

**Comment by anassahmed** [comment]
Oh, thanks.  
I just wrote an addon to reset the `internal_number` and allow deleting the invoice altogether.

The question really is: if you already allow canceling journal entries with `account_cancel` which is also illegal and against best practices (then you can delete them, like the code does on invoice canceling), then why don't you allow deleting the invoice (AFAIK, the invoice will take a new number after you reset to _Draft_ again, then validate, it won't take the previous number one more time).

**Comment by bistaray** [comment]
After resetting to draft and validating, the Invoice will retain the same number.

**Comment by anassahmed** [comment]
@bistaray I don't think that's really happening, have you tried it?

The `invoice_open` workflow signal that switches the invoice from _Draft_ to _Open_ triggers the workflow activity `act_open` which will always regenerate a new number for the new moves that it will create (it calls `action_move_create` method which create `move_id` whose number is assigned to `inv.number`, then calls `action_number` which assigns the new number to `inv.internal_number`), as you can see in this file:
https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice_workflow.xml#L22

**Comment by bistaray** [comment]
Sorry. I have tried it at version 9.0 and 10.0. and it preserves the Invoice Number during the cancel / set to draft / edit / validate cycle.

**Comment by anassahmed** [comment]
@bistaray I don't think it works with `8.0` though, is there a reason why it's not included in `8.0`?

The change you're talking about is here, it clearly addresses this scenario, but it's on `10.0` not `8.0`:
https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_invoice.py#L212

**Comment by anassahmed** [comment]
Oh, I was mistaken.  
My way of solving the removal issue was to reset the `internal_number` on cancel, but looks like I've been wrong. Now, my code reset the `internal_number` on `unlink`, thus it retains the number on cancel in case of resetting back to draft, then validating the invoice again.

**Comment by zoloo777** [comment]
# # # # @ @ @ @

- [ ] 

> 

> **_өхихаисм_**

- [ ] аөхөах

- [ ] [бөм[](url)]([url](өөамөа))
