### ISSUE TITLE
odoo mailer broken? cannot reach odoo.com by e-mail

### ISSUE THREAD

**Issue by adrelanos** [odoo/odoo#17199]
We signed up for odoo for a trial.

I've mailed info at odoo.com, help at odoo.com, gregory at odoo.com. (Of course I replaced to at with @ since I don't want to feed spam harvesting bots.)

Mailed from adrelanos at riseup.net as well as a private e-mail domain.

Never received any reply.

Until 5/15/2017 I got `Undelivered Mail Returned to Sender`, `ob1.odoo.com[46.105.111.221] said: 550 Mailbox unavailable (in reply to end of DATA command)`. This issue was confirmed to me to be an odoo issue by the support chat.

I am no longer getting that, but also no replied from odoo. Please advice.

**Comment by JKE-be** [comment]
Hi @adrelanos,

The mail server is up...

But gregory@odoo.com don't exist...
Maybe if you give me the name, I can help you to find his email ?

Best regards

**Comment by adrelanos** [comment]
I mistyped above.

geoffrey@odoo.com

Head of Customer Delight

My mail from 05/17/2017 to geoffrey@odoo.com is still unanswered.

Mail to info@odoo.com from 05/16/2017 01:34 UTC unanswered.

Mail to info@odoo.com from 04/30/2017 07:31 UTC from different domain
unanswered.

Usually, everyone is receiving my mails.
