### ISSUE TITLE
Can't delete opportunities from the calendar view (day mode)

### ISSUE THREAD

**Issue by andreparames** [odoo/odoo#1721]
***Impacted versions:***
- 7.0

***Steps to reproduce:***
1. Open Opportunities
2. Choose Calendar view
3. Choose the Day mode
4. Delete an item

***Current behavior:***
 - crash with traceback

**Comment by beledouxdenis** [comment]
Closed with 7e0ed740f38d035174d4c1258a372af38ea4f677.
