### ISSUE TITLE
[10.0] Inventory Valuation can't open related picking

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#17226]
Impacted versions:
10.0
Steps to reproduce:
1. Go to Inventory --> Reports --> Inventory Valuation
2. Open form view and click on ![image](https://cloud.githubusercontent.com/assets/13385546/26487443/d28b842a-41ff-11e7-9189-316ee74ff8c4.png) to open related picking

Current behavior:
Error appear "Form view couldn't be loaded"

Expected behavior:
Open related picking as it work in version 9.0

Video/Screenshot link (optional):

![image](https://cloud.githubusercontent.com/assets/13385546/26487681/c139b31c-4200-11e7-8393-9901cca1fd60.png)

**Comment by jco-odoo** [comment]
Apparently because of show_picking linking to action_show_picking.  (If I leave just show_picking, it works)

**Comment by jco-odoo** [comment]
@ged-odoo @qsm-odoo Could this be because of a wrong deferred in the web client?  The first time, it indicates "Form view could not be loaded".  The second time, it is opened directly.  (if you want to test it on runbot, maybe receive an incoming picking and check that product afterwards)

**Comment by ged-odoo** [comment]
@jco-odoo I don't think that a wrong deferred causes the problem.  It looks like the show_picking method in stock.picking returns a wrong res_id.  If you look at the read rpc, it returns an empty list.  But if you try to do it in saas-15, it returns something.

**Comment by jco-odoo** [comment]
In saas-15, it is as broken.

**Comment by ged-odoo** [comment]
I meant to say that in version 9.0, it returns a valid res_id, but not in version 10.0

**Comment by Yenthe666** [comment]
@jco-odoo is there any update on this one? The PR has been quiet for quite a while.

**Comment by sle-odoo** [comment]
Hi,
Sorry for the delay, we opened a task to solve this issue.

Regards
master bug 817491

**Comment by sle-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/fb2df13ea8b222e1f3ce1a5edbc316589fb7db12
Thanks for the report
