### ISSUE TITLE
[17.0] l10n_de: error sending invoice via mail

### ISSUE THREAD

**Issue by flt-papillo** [odoo/odoo#172367]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Since the last update ( https://github.com/odoo/odoo/commit/50c62eab72678d51fb88c88fbeb81da2decca6f2#diff-ae789c742fc90cab1faa3a18daa9aa88f0bef70198552f3c99a7d10d164e90ea) we are not able to send invoices via mails. It seems like there is a problem while generating new attachments, which has already been generated or sent.

This error occurs, when i try to send an invoice via mail using the send&print button and the invoice_send wizard. 

This is kind of an urgent one, since we are not able to send our mails via mail!!

**Comment by intero-chz** [comment]
What is the error? Why didn't you open an official support ticket when it's urgent?

**Comment by flt-papillo** [comment]
I did and as it was told me yesterday it is solved according to this FIX: https://github.com/odoo/odoo/pull/172355/commits/aaf747b24ef3bf8f9821b2ee71992050fb10613c
