### ISSUE TITLE
Creating PO order line planned date changes to default after changing quantity

### ISSUE THREAD

**Issue by DrSchuh** [odoo/odoo#17234]
Impacted versions: 10.0

Steps to reproduce: Create Purchase Order

Current behavior: Adding an order line the planned date changes to default after changing the quantity

Expected behavior: keep date

Video/Screenshot link (optional):

Browser: Firefox 52.1.2, Chrome

**Comment by remz1337** [comment]
Any update on this issue? It is really annoying and creates lots of problems between our buyers and suppliers.

Thanks

**Comment by Yenthe666** [comment]
Hi @DrSchuh,

Thanks a lot for the bug report.
I was no longer able to reproduce this on the latest Odoo 10.0.
Please update your Odoo source code if you still face this issue on your local Odoo instance.

Regards,
Yenthe
