### ISSUE TITLE
hr_payroll miscalculation in no of work days when a works schedule with irregular time-slices is used

### ISSUE THREAD

**Issue by jordanvrtanoski** [odoo/odoo#17249]
Impacted versions: Odoo 10.0 (After fix #15404 was introduced)

Steps to reproduce: 
    Create Employee and a Contract. Assign a Working Schedule which has irregular hours (ex. Mo: from 8 to 14, Tu: from 9 to 16, We: from 8 to 11 and from 13 to 17, etc.) The total of working hours should not be divisible by 8 (since 8 is a hardcoded number introduced with the fix #15404)
    Create a leave for the employee for a duration of 3 days. Create another leave for a period of 3 hours.
    Create a pay slip for the employee.
Current behavior:
    The WORK100 hours will be calculated correctly as per the Working Schedule and the leave hours will be calculated correctly, however, if the days will be calculated as Hours / 8.0.
Expected behavior:
    The days should be calculated in accordance with the Working Schedule.

**Comment by jordanvrtanoski** [comment]
Fixed, testing in progress.

**Comment by Yenthe666** [comment]
@nim-odoo you might want to look at this as it might have broken this because of your commit. (no offense obviously)

**Comment by pedrobaeza** [comment]
Closing as there's a PR opened for tracking this.
