### ISSUE TITLE
[BLUEPRINT] Generic merge mechanism for records

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#17268]
Instead of writing specific code for merging each type of record (see the contact merging, or the OCA invoice merging - https://github.com/OCA/account-invoicing/tree/9.0/account_invoice_merge -), that requires a lot of effort to make it work, and it needs to be expanded when the data structure of the model changes, we can provide a generic mechanism that allows to define when declaring the model the behavior we want when merging records, the same way as we define the on_delete behavior on linked fields, giving also possibilities for applying constraints or performing custom merging operations, and then provide them generally through all records.

These are the foundations of the feature:

Declaration of merge operation
------
We make it through an attribute in the field definition, called `on_merge`, with following values:
* `main` or `target`: the value taken is the one from the target record. (default)
* `sum`: only for numeric fields. The merge result is the sum of all the values of the merge records.
* `avg`: also only for numeric fields, and the result is the average.
* `concatenate`: only for char fields. The result is the concatenation of the strings of the merge records.
* `combine`: only for one2many/many2many. The result is the addition of all values from the fields in the merge records.
* `custom`: a custom merge method should be provided via an additional attribute `merge` or `merge_method`, that can be enclosed by quotes to be inheritable the same way as the compute method. This method will have the signature `def merge_method(self):`, having self as the recordset with the records to merge, and returning the expected valued to be used (in the same syntax as `default` method).

Contraints on merging
-----
Sometimes we can't merge some record attending to the business logic. We need to provide a mechanism for restricting these merging. Having a decorator `@api.merge_constrains` for method that are triggered on the merge operation and raising an exception when not possible.

Security
-----
We can use the constraints for checking security, but it would be also interesting to add an ACL and record rule operation called "Merge" integrated with the current security mechanism for allowing this operation or not.

User experience
-----
Providing a transient model that displays the list of records and a many2one selector (maybe including the ID in brackets) for selecting the target record. We can also improved it showing a preview of the result.

Troubleshooting
----
The default provided value is the most versatile one and the most commonly used, but someone can argue that if you don't provide the corresponding argument, the merge operation is going to be incorrect or inconsistent, but the same happens with `copy=False` or `on_delete='cascade'` missing attributes. They are part of your duties when programming for Odoo, and you have to take care about the proper values corresponding your business logic.

**Comment by pedrobaeza** [comment]
@mart-e here you have my first draft.

**Comment by mart-e** [comment]
Hello,

Nice idea but as we discussed during the code sprint, it was rejected.
The idea will be instead to implement the different relevant scenarios individually instead of a complex generic solution.
Regards

**Comment by bealdav** [comment]
I like this proposal, particularly `sum`.

You could summarize some historical data instead of keep 20 years: sales by product / partner / year.

OK process, can't be so easy because all is implied (procurement, stock) but one day or another Odoo should introduce a way to historize its data. Summarize is a way to do it.
You keep essential parts of old data.

**Comment by pedrobaeza** [comment]
cc @rco-odoo
