### ISSUE TITLE
Bug in cost computation for BOM

### ISSUE THREAD

**Issue by DidierLACOMBE** [odoo/odoo#17266]
Impacted versions:
ODOO 10C
Steps to reproduce:

-Create a BOM with a routing involving 2 or more workcenters
-install product_extended
-fatal error during install costs_hour is missing

After x_cost_hour is created into the workcender module, try to compute from BOM
the labor cost is wrong...

2 bugs in the standard community module : product_extended

1) the costs_hour must be created in the workcenter data model (x_costs-hour) otherwise the module can't  be installed

2) following changes to be made in the code for product.py
------------------------------------------------------------------------------------------------
for order in bom.routing_id.operation_ids:
    ########################################################
    # WEBINAR-OPENERP.COM  Change costs_hours field by x_costs_hour
    # workcenter_cost is not an average cost
    ########################################################
    total_cost += (order.time_cycle_manual/60) * order.workcenter_id.x_costs_hour
# workcenter_cost = total_cost / len(bom.routing_id.operation_ids) WEBINAR-OPENERP.COM change
workcenter_cost = total_cost # WEBINAR-OPENERP.COM change
-----------------------------------------------------------------------------------------------------
regards

**Comment by jco-odoo** [comment]
As costs_hours was put in mrp_account in enterprise, it is maybe better to try to skip it.  I suspect the calculation to be wrong also.

**Comment by DidierLACOMBE** [comment]
Hello

this module is distributed into V10 community
so it should work
with this fix, calculation with many WC in routing and many component in BOM works fine, but NOT with variants configuration
