### ISSUE TITLE
[10.0]Crash on invoice refund without sale module

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#17272]
Impacted versions:

10.0

Steps to reproduce:

* Go on runbot
* uninstall sale module
* Go on an open customer invoice
* Click on refund button
* Choose modify option
* Fill in the reason
* Click on create refund

Current behavior:

An exception is raised

![selection_056](https://cloud.githubusercontent.com/assets/8035793/26552047/c320c3aa-4485-11e7-9005-b92cb799562a.jpg)

Expected behavior:

Refund created

Video/Screenshot link (optional):

**Comment by adrienpeiffer** [comment]
@mart-e As just discussed

**Comment by Yenthe666** [comment]
If I'm not mistaking this PR fixed it: https://github.com/odoo/odoo/pull/17273#event-1101783384
Commit: https://github.com/odoo/odoo/commit/abb71fea51eac0c26a5296c03d1fb7b9657c08d2
