### ISSUE TITLE
auth_ldap incompatible with new *email as login* policy

### ISSUE THREAD

**Issue by nicoclavier** [odoo/odoo#1727]
Hello,

**In V8 : the res.users login field is set to become the email address of a user** (as the login label string says "Email Address"), at least , when administrating your users from the settings page, this field is clearly inviting to enter and email address in the login field.

If using the auth_ldap module with a thrd party account provider (we use Active Directory), the
the ldap login of an ldap user will fail to authenticate against the server after the user's login field has been set to his email address (unless your LDAP server allows authenticating with your email).

**_Impacted versions:**_
- master branch or 8.0

**_Steps to reproduce:**_
- install auth_ldap & configure with default user set to any generic user record.
- logout from admin account 
- log back in with LDAP credential
- logout of personal account
- login as admin and change the **Email address** field to the user's email as it invites you to do, and save.

**_Current behavior:**_
- logout of admin, try to login with your LDAP credentials : it fails

**_Expected behavior:**_
- updating the user's Email address field would only update the related partner's email field

**_Workaround :**_
- LDAP users should update their email address from the preference window, which will instead set the email on the appropriate field of the related partner record.
- admins should update the partner records email directly

**Comment by Dadodadolontong** [comment]
I am using mail=%s, users are authenticated and created in odoo, but the email address is referring to default user.  Is there any case reported?

**Comment by jmccoy555** [comment]
Can anyone help me with this. I'm having the same issue as pvassalli above, using sAMAccountName it tells me I have the wrong password, and with mail I get a server error.

In ownCloud my login filter is - (&(&(|(objectclass=user))(|(memberof=CN=ownCloud,CN=Groups,DC=xxxxx,DC=yyyy)))(|(sAMAccountName=%uid)))

I have also changed ownCloud to use mail for login and that works perfectly.

I am using Zentyal 4.0 as the backend.

Thanks.

**Comment by alexixalex** [comment]
I had the same issue, I could not connect with short names. My username was UID in LDAP, so the filter I setup is uid=%s. But you HAVE TO CHECK the "Create User" box. What happens is that the user needs to exist in odoo. If you authenticate with a valid ldap user, but the user is not created in odoo, you get the invalid username/password error. So when the user first logs in with the ldap credentials, the local account is also created, however, using the ldap authentication.

hope this helps

**Comment by Yenthe666** [comment]
Hi @nicoclavier,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
