### ISSUE TITLE
[10.0e] inter-company sales / purchase issue

### ISSUE THREAD

**Issue by abdallamohamed1992** [odoo/odoo#17282]
Hello

I test inter-company rules in version 10.0e on runbot but i found issue if i have company A and B.
- Then in company B create purchase order and choose A as vendor.
- If i do not check on "Sale/Purchase Orders Auto Validation" odoo will create quotations if i confirm it i cannot find any picking related to sales order in inventory and found that there is procurement order in exception state "No rule matching this procurement"

**Comment by lap-odoo** [comment]
@abdallamohamed1992 I've just re-tested it on version 10 and it's working fine. See video : https://drive.google.com/file/d/171cW-jmAld_b2z1PgXez2QznDVl1Hpku/view. I think the problem was linked to the configuration of your product. There was probably no route delivery linked to your product.
