### ISSUE TITLE
[8.0] Odoo allows to reconcile in payable/receivable accounts with different partners

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#17292]
This bug is present in v8, but not in v9 nor in v10.

Here are the steps to reproduce the bug:
1) Connect to runbot v8 as admin
2) Create 2 new partners: Customer1 and Customer2
3) Create a customer invoice for Customer1 validate it.
4) In the menu "Journal Entries", create a Journal entry in a bank journal for Customer2 with credit on receivable account (same as the one used in invoice) and debit on bank account. The amount used should be the same as the total amount of the invoice.
5) In the menu "Journal Items", select:
- the move line in the sale journal on the receivable account (partner = Customer1)
- the move line in the bank journal on the receivable account (partner = Customer2)
then click on "Action > Reconcile Entries" and then click on the "Reconcile" button.
-> it should trigger an error message, but it doesn't !

Code analysis: in the "account" module, there is a constraint on the object "account.move.reconcile" which is supposed to block this scenario: https://github.com/odoo/odoo/blob/8.0/addons/account/account.py#L1674
But this constraint is not triggered when the reconcile mark is created. This constraint is triggered on the fields "line_id" and "line_partial_ids", which are one2many fields.

Attempt at fixing this: I tried to add the 'name' field to the list of fields which trigger the constraint, but it doesn't solve the problem: the method of the constraint in executed, but during its execution reconcile.line_id = False and reconcile.line_partial_ids = False, so it doesn't return False.

**Comment by mart-e** [comment]
Hello Alexis,

Indeed, the constraint is not triggered in old API because you are not directly accessing this field.
In v9, the accounting has changed so the constrain is not triggered.
We should probably port it to the new API to properly trigger it.

**Comment by alexis-via** [comment]
@qdp-odoo I think it's an important issue that require your attention :)

**Comment by ploegvde** [comment]
Hi, In V10E you can also reconcile a invoice of customer A with a bankstatement of customer B. On the reconciliation you undo the partner selection and reconcile with another partner's invoice.

We use that a lot on customers where sub companies get all the invoices, but they get paid by a main company, what is another partner in Odoo.

We are happy that it is possible.
