### ISSUE TITLE
SQL Error creating Activity

### ISSUE THREAD

**Issue by euroblaze** [odoo/odoo#17313]
#### Impacted versions

10E, maybe others

#### Steps to reproduce

Try to create an Activity from Contacts app as a Sales / User.
You'll have to give permissions in the ACL

#### Current behavior

Throws an error-bomb
https://dl.dropboxusercontent.com/s/rck2kaij4ly2v71/2017-05-30-17.25.png

#### Expected behavior:

Should be possible to create an Activity, attached to Partner and Sales/User.

#### Video/Screenshot link (optional):
https://dl.dropboxusercontent.com/s/rck2kaij4ly2v71/2017-05-30-17.25.png

**Comment by mart-e** [comment]
Hello,

Are you sure you are on a fresh v10? Your screenshot shows a mix of v9 and v10 in the traceback.
Please be sure to be able to reproduce the error on a standard [runbot](http://runbot.odoo.com/runbot/repo/git-github-com-odoo-odoo-1) and give precise step to get the same error.
