### ISSUE TITLE
[10.0]MRP  stock orderpoint  repeated calculation

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#17320]
Impacted versions:
10.0
Steps to reproduce:
1. I Process  "Run Reordering Rules" 
2. **in 5s** ,I process "Run Schedulers"

Current behavior:
I found stock order point repeated calculation,cause my demand to double
Expected behavior:

Video/Screenshot link (optional):
![qq20170531-090633](https://cloud.githubusercontent.com/assets/5398273/26611367/76cdf5ac-45e0-11e7-947a-0217bff72c47.png)

**Comment by jco-odoo** [comment]
I think a fix was made for this.  The purpose of Run Reordering Rules was to keep it in debug mode and here the "lock" was forgotten.     @pimodoo

**Comment by pimodoo** [comment]
@jco-odoo could you confirm me that the problem is still there in last update of 10.0, because something similar has been fixed in this commit https://github.com/odoo/odoo/commit/85e21d1725ad2d4a6c59c51d1144d34ea664018e

**Comment by jco-odoo** [comment]
I wanted to say it was probably solved by that.

**Comment by sum1201** [comment]
this is ok !
