### ISSUE TITLE
Product Variants - Various issues

### ISSUE THREAD

**Issue by fvdsn** [odoo/odoo#1732]
- The additional price on variants does not work
- Impossible to access the form view of properties ( where you can setup price, etc)
- Assigning a barcode to a product variant results in a crash
- Stock issues in the eshop
  etc.

**Comment by Yenthe666** [comment]
@Gorash can you give an update?
I believe one is fine now, two is too, three is no longer reproducable and not sure what the 'problem' should be with 4.

Regards,
Yenthe
