### ISSUE TITLE
got error many time when use odoo 10

### ISSUE THREAD

**Issue by milan-thakkar** [odoo/odoo#17333]
Impacted versions:
odoo_10

Current behavior: Stop working
Expected behavior: Solve the issue

Video/Screenshot link (optional):
![odoo_10_load_error](https://cloud.githubusercontent.com/assets/13216534/26630507/9d78ee2a-4624-11e7-8142-81f4c0822664.png)

**Comment by Yenthe666** [comment]
Hi @milan-acespritech,

Thanks for the report.
Please provide more information though, there is no way for us to reproduce or test this.
On which menu are you, what did you do, how did you trigger it, can you reproduce it on a runbot?
And as a sidenote: it is the bottom part of the stacktrace that is relevant. 😉 

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @milan-acespritech,

Thanks for the report.
Please provide more information though, there is no way for us to reproduce or test this.
On which menu are you, what did you do, how did you trigger it, can you reproduce it on a runbot?
And as a sidenote: it is the bottom part of the stacktrace that is relevant. 😉 

Regards,
Yenthe

**Comment by milan-acespritech** [comment]
Hi @Yenthe666

This error i was getting when i load language and after when i change the language from preferences from the user.

**Comment by milan-thakkar** [comment]
Hello @Yenthe666 ...have you seen that i posted error from runboot..please look at it and solve it...

**Comment by ror-odoo** [comment]
Hello @milan-thakkar 
I am not getting any error on runbot .can you please provide more information ?
Thank you

**Comment by milan-thakkar** [comment]
Hello @ror-odoo 
Can you see i attached screenshot of runboot?
See the screenshot and check on your side again.

**Comment by ror-odoo** [comment]
Hello @milan-thakkar 
i think issue has been fixed,please check again
Thank you
