### ISSUE TITLE
[9.0, 10.0] Unable to do inventory adjustments with scanners when opening Odoo in xs view

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#17337]
Impacted versions: 9.0, 10.0

Steps to reproduce: 
1. Open a runbot 9.0 or 10.0, go to Inventory > Inventory Adjustments and create a new adjusment. You'll get something like this:
![image](https://cloud.githubusercontent.com/assets/6352350/26633826/0629da66-4615-11e7-8ec2-9c71cd0899a3.png)
You can clearly see that the inventory details are inside of `table` elements:
![image](https://cloud.githubusercontent.com/assets/6352350/26633901/35c4f95e-4615-11e7-9ef8-b2f9b4fdb937.png)

2. Now make your browser a lot smaller (or open it on a mobile phone) you'll now see this (after refreshing the page):
![image](https://cloud.githubusercontent.com/assets/6352350/26633979/68a850f0-4615-11e7-99c6-1386e8338469.png)
When your resolution is small or when you make your browser small enough the bootstrap tables are removed and that there are other classes:
![image](https://cloud.githubusercontent.com/assets/6352350/26634027/94f7e486-4615-11e7-81ee-39cb9a07b463.png)

Current behavior: Because of this behaviour there is no longer a table around the inventory lines. Without this table around it is impossible for a scanner to work. Because of the missing table the scanner can no longer apply values and update quantities.

Expected behavior: It is possible to do inventory valuations with a scanner when having Odoo open in XS resolution.

Possible fix: Do not hide the `divs` when opening Odoo in XS mode. If the classes and divs are around the records the scanner can detect them and input the values correctly.

**Comment by Yenthe666** [comment]
CC @cyhexy
@csnauwaert probably for you?

**Comment by jco-odoo** [comment]
Maybe @sle-odoo or @pimodoo know more about it.

**Comment by pimodoo** [comment]
@Yenthe666 Hello, if you want to use the barcode scanner for inventory adjustment or picking, the best way is to go to Barcode -> Inventory (for inventory adjustment) and Barcode -> Operation (for picking). By using the application Barcode, scanning will work on small screens and you'll be able to also scan locations.

**Comment by Yenthe666** [comment]
Yep - agreed.
