### ISSUE TITLE
[10.0] website_sale_option: website modal not show correct prices when the product has an optional product configured

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#17342]
Impacted versions:
10.0

### Steps to reproduce:
-Add an optional product to Apple In-Ear Headphones product in backend
    for example Bose Mini Bluetooth Speaker
![image](https://cloud.githubusercontent.com/assets/10233975/26645632/58d15364-45fe-11e7-9395-d4525b311a20.png)

- Got to website shop and open product detail of Apple In-Ear Headphones

- Then click in add to cart button in order to make website modal options open

### Current behavior:

The price showed is wrong

Before adding an optional product
![image](https://cloud.githubusercontent.com/assets/10233975/26645585/2321e54e-45fe-11e7-9bc9-d5ac378da7dd.png)

After adding  a optional product
![image](https://cloud.githubusercontent.com/assets/10233975/26645565/0979fa78-45fe-11e7-8b5b-f2cf397fa63c.png)

Expected behavior:

Show correct prices

Video/Screenshot link (optional):

https://www.youtube.com/watch?v=mqpIL0e76pE

**Comment by Yenthe666** [comment]
I summon you @JKE-be 😉

**Comment by hugho-ad** [comment]
Here is a posible clue https://github.com/odoo/odoo/commit/c8a434306f110bfb5e5ce71609e8e096a850d309

**Comment by hugho-ad** [comment]
Fixed in https://github.com/odoo/odoo/commit/8bd56bb46628e57f41c635f20c527264d7a20d86
