### ISSUE TITLE
[10.0] Currency mixing in HR expense sheet and report

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#17341]
Impacted versions:

10.0

Steps to reproduce:

See  https://youtu.be/I3Qb3m1GmJ4

Current behavior:

Currency mixing in expense sheet view and report

Expected behavior:

Have no currency mixing :smile: 

Video/Screenshot link (optional):

See https://youtu.be/I3Qb3m1GmJ4

Credit : @alexis-via - Barcelona OCA code sprint

**Comment by Yenthe666** [comment]
@adrienpeiffer your link does not seem to work?
![image](https://cloud.githubusercontent.com/assets/6352350/26649289/b9bdc030-4645-11e7-9790-51ba4d13bd33.png)

**Comment by adrienpeiffer** [comment]
Sorry I fixes the link

**Comment by sbidoul** [comment]
OPW 745714

**Comment by nim-odoo** [comment]
#17567 :
- corrects the report
- displays the currency in the view
- set the total amount to zero if multiple currencies (the sum doesn't make any sense anyway...)

The sum in the view would be much more tricky to remove, however. But this is not a big deal.
