### ISSUE TITLE
[17.0] base: en_US uses incorrect datetime format

### ISSUE THREAD

**Issue by gabriel-grinspan** [odoo/odoo#173444]
### Odoo Version

- [X] 15.0
- [X] 16.0
- [X] 17.0
- [X] Other (specify)
In any version of Odoo

### Steps to Reproduce

There is an issue with the default configuration of Odoo. Users in the United States expect their system to reflect their preferred means of displaying dates, like any other country. The default in Odoo is to use 24-hour time. In the United States, everyone uses 12-hour time. The default for en_US in Odoo should match this. If the issue is that en_US is the default res.lang, we should still change it to 12-hour time and then change the default language.
Relevant PR: https://github.com/odoo/odoo/pull/168046

**Comment by ray-odoo** [comment]
PR rejected. See feedback at #168046

**Comment by gabriel-grinspan** [comment]
@ray-odoo The only feedback provided there was that the task requires updating a bunch of tests and that I should either fix the issue myself or open an issue. I opened and issue and you are suggesting that there was a proper reason given for this issue to be ignored. Using Odoo out of the box is actively more difficult as it requires more technical setup for a user.

**Comment by ray-odoo** [comment]
It is easy for Users to change the default time format of an Odoo database

https://www.odoo.com/forum/help-1/changing-the-time-date-setting-in-v14-system-183679

This is still applicable for Odoo 15, Odoo 16 and Odoo 17

Odoo has defaulted to 24 hour time since inception, and many of our US Customers use 24 hour time.

**Comment by burkeallen** [comment]
one challenge with just adjusting the date or time format from the Odoo interface, is that the change does not survive when all modules are updated "-u all".

**Comment by ray-odoo** [comment]
If you are worried about this you can change the NO UPDATE flag of the External ID of the Language so no new updates are made and all "old" values are kept.

**Comment by burkeallen** [comment]
Thanks for the suggestion ray, this did not seem to provide the expected result, after changing the time format value to "%I:%M:%S %p"  and checking the field "Non Updateable" to True.  then performing the "-u all"  the default time format value of "%H:%M:%S" was restored to the table.  I am not real familiar with the odoo core code, have been spending a majority of my time on custom modules, but this is an annoying behavior. and from what little i have looked into it, not a trivial matter to overcome with current implementation of how the default format is set, both form the data import from the res.lang.csv file and related code in the res.lang model 

DEFAULT_TIME_FORMAT = '%H:%M:%S'

  time_format = fields.Char(string='Time Format', required=True, default=DEFAULT_TIME_FORMAT)
  
I am not familiar with how odoo actually handles the upgrade process, and why once set in the odoo interface it would override the value back to the original default value for this particular record and model. I attempted to override the default value for the time format field in a custom module, but that did not have any effect on it. assuming the data in the data in the CSV file was being imported again in the update.  this does appear to be a bug in how i see a bug being defined, as no general user would expect this value to change from what they set the value to be by an update to the module running, after they set the value manually. 

it is not a breaking bug, but is an annoying one for users and system admins to have to deal with. I know those maintaining the core code  have much more pressing and important issues to deal with.  so I understand if this is not worth the effort to fix.  and just wanted to share my understanding of the issue as best i know to possible help others who are seeing the same behavior and wondering if they were doing something wrong or if there was an easy fix to it.

cheers and much appreciation for those maintain the core code.
