### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by engmahmoud** [odoo/odoo#17357]
after i try to install odoo for windows 7 i get this error
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\python27 \\lib\\site-packages\\python_dateutil-2.6.0-py2.7.egg'

**Comment by sle-odoo** [comment]
@engmahmoud Hi, we need more steps to handle your issues. Which odoo version did you try to install and what steps did you followed to install it?

**Comment by Yenthe666** [comment]
@engmahmoud could you please provide us with feedback? What Odoo version did you try to install and how did you install it exactly?
