### ISSUE TITLE
Actions>User-Defined Defaults doesn't work with related= fields

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1735]
Version: rc1 8. Aug. 2014
Reproduce:
- Define a field Many2one
- Define a related field Many2one
- Define according views
- all fine so far :smile: 
- define a "user-default" on this field eg 1  - just type in 1 like in the other defaults of the full demo db on runbot
  - remark: [1] will raise an unicode error (at least with my machine), so just type 1
- try to open your view

You'll get the following unexpected error (with my model):
`No value found for res.country.state.city('1',).state_id`

> Note: city with ID 1 exists

In order not to distract from the essence, I'll be glad to post code upon request.

<hr\>

![image](https://cloud.githubusercontent.com/assets/7548295/3880268/e273bb24-2181-11e4-8568-328c8c80d539.png)

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
