### ISSUE TITLE
Quotation date is shown in SO "month" filter instead of the date the SO is confirmed

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#17368]
Impacted versions:9.0ee

Steps to reproduce: Create quote in April, confirm in may.  Group SO by month.

Current behavior: The confirmed SO shows in the April group.

Expected behavior: The SO should show the date it was confirmed.

Video/Screenshot link (optional):

**Comment by raycarnes** [comment]
Default Odoo has no "Date of Confirmation" of orders in version 9.0.

**Comment by Yenthe666** [comment]
Indeed @raycarnes - good catch. This looks like you have custom development. If you want to show the SO depending on the confirmed date you should add more custom development.
