### ISSUE TITLE
website_crm (contact form) issue when edit and delete company info

### ISSUE THREAD

**Issue by MiguelMachadoM** [odoo/odoo#1737]
if edit company info on contact form and delete it this delete company info from database and system crash.

Im not a expert but check it to confirm.

**Comment by Yenthe666** [comment]
Hi @MiguelMachadoM,

Thank you for your report.
This shouldn't be any problem though.. The fields that we really need (such as the name) are required so there is no way to leave these fields blank (which would in fact result in a crash).
I really can't reproduce this to crash the database.

Regards,
Yenthe
