### ISSUE TITLE
[9e][10e] Security Issue: Session Fixation

### ISSUE THREAD

**Issue by auditum-pbe** [odoo/odoo#17376]
< issue reported to security@odoo.com >

**Comment by lukebranch** [comment]
@auditum-pbe,

I am just another user like yourself, however I would suggest reporting this through the security@odoo.com email address:

https://www.odoo.com/page/responsible-disclosure

**Comment by auditum-pbe** [comment]
@lukebranch Thanks, issue reported to security@odoo.com.
