### ISSUE TITLE
[10.0+e] Customer email showing as an internal note! - mail.thread searching on un-stripped message_id

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#17374]
Hi there.

Inside the `message_parse` function in `mail.thread`, to link a message to a parent, and also determine if the message is to be internal or public, there is an issue with searching on the `message_id`.
I understand this is probably an edge case, but for whatever reason, a message coming from outlook into odoo often has a tab character in front of the `Message-ID` header, as this is not stripped in the initialisation of the `message_id` field in the database, when we are later trying to search on that field it fails.
```python
self.env['mail.message'].search([('message_id', '=', tools.decode_smtp_header(message['In-Reply-To'].strip()))], limit=1)
```
As you can see this search utilises the `strip()` string function (Which it quite rightly should), however, the initial setting of this field does not;
```python
message_id = message['message-id']
```
This causes the match to fail, Odoo will then try to use the message_id match in the `References` header, which in the case of a sale order is actually the parent system notification stating `Sales Order created`.
The problem with this is that although an email from a customer is still attached to the document, **it will have the wrong subtype match and it will be set as an internal note `mt_note`.**

The fix is simple, make the setting and getting of message_id symmetrical
```python
message_id = message['message-id'].strip()
```

See original code below:
https://github.com/odoo/odoo/blob/79477b8d96be47cca5609ce5e4dd84a7e7f64f0a/addons/mail/models/mail_thread.py#L1494-L1499
https://github.com/odoo/odoo/blob/79477b8d96be47cca5609ce5e4dd84a7e7f64f0a/addons/mail/models/mail_thread.py#L1530-L1541

**Comment by dhannyz** [comment]
@nle-odoo I've had you respond on another issue, can i get you to look at this?

**Comment by dhannyz** [comment]
@Yenthe666 Just giving this a bump as you might know who might best be able to handle mail related issues. This one at the least is semi-important

**Comment by m3dbedb** [comment]
Similar behavior found in task chatter: for internal project (visible by employees) odoo time to time adds partner email to recievers of massage, even if partner is not subscribed.

**Comment by andrewdhastings** [comment]
I had the same issue, but just updated odoo to the latest nightly and issue was resolved.

**Comment by pedrobaeza** [comment]
Yeah, this should be solved already in latest code. Closing.
