### ISSUE TITLE
[17.0] Calendar : Cannot  sync due to mismatch_url error (The redirect url is malformed)

### ISSUE THREAD

**Issue by gaetan-puleo** [odoo/odoo#173799]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I selfhost odoo.

When trying to sync the google calendar, I get a mismatch_uri error.

I noticed 2 things.

- The redirect url start with HTTP (I am using HTTPS)
- The redirect url is malformed
What I get exaclty

`http://{myurl}/google_account/authentication flowName=GeneralOAuthFlow`

I cannot sync google calendar with oddo

### Support Ticket
#4063738

_No response_

**Comment by rianmz-genz** [comment]
i have same issue

**Comment by karimsteros** [comment]
Has anyone found a solution to this issue?

**Comment by vava-odoo** [comment]
@gaetan-puleo The ticket says that you need to be in production. Link to the doc https://www.odoo.com/documentation/16.0/applications/productivity/calendar/google.html
If unclear, don't hesitate to open a ticket in the [documentation repo](https://www.github.com/odoo/documentation/issues)
