### ISSUE TITLE
product form view : sale_ok field can not be clicked

### ISSUE THREAD

**Issue by mcassuto** [odoo/odoo#1738]
if the user try to unset the field sale_ok, he can not achieve the operation since the action open the file selector to upload the product's image.

However we can still get the focus using the tab key (not using the mouse).

**Comment by Yenthe666** [comment]
Hi @mcassuto,

Thank you for your report.
This issue has been solved in the meanwhile. Example of the version from today:
![image](https://user-images.githubusercontent.com/6352350/27579082-9470ca98-5b26-11e7-9c6e-7ece92ac0c49.png)

Regards,
Yenthe
