### ISSUE TITLE
duplicate company report reference y1=, what's wrong?

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#17398]
Impacted versions:
10.0-CE

Steps to reproduce:
duplicate company

Current behavior:
report `a mandatory field is not correctly set`

Expected behavior:

Video/Screenshot link (optional):

>  The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: y1= - y1=]

**Comment by gustavovalverde** [comment]
Same here, can't duplicate a company. 

I don't know in who's domain this issue is, but I think one of you can have a look at it @nle-odoo @mart-e

**Comment by gustavovalverde** [comment]
Just to add a bit more of information:

I've tested this on a new installation, 0 modules and no demo data. And it's also happening on runbot, trying to duplicate the res.company model.

**Comment by Yenthe666** [comment]
Yep this looks like an issue. Reproduced on the latest runbot:
![image](https://cloud.githubusercontent.com/assets/6352350/26827165/4ea5a774-4abc-11e7-9b12-63aca0a7f7f0.png)
@tde-banana-odoo think you could give us some more code sprint awesomeness? 😉

**Comment by nle-odoo** [comment]
Hello,

A change in 8.0 has been made so the company partner (which contain the name/address/... of the company) is duplicated when duplicating a company: https://github.com/odoo/odoo/commit/ed61da67932

It should be available in 10.0 on the next forward-port ( you will be able to see them when there is a new "[MERGE] forward port branch ..." in the change list in https://github.com/odoo/odoo/commits/10.0 ).
