### ISSUE TITLE
[9.0] context not deleted on action xml declaration removed

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#17392]
Impacted versions: 9.0

Steps to reproduce:
1.- create a new action like : 
```
<record model="ir.actions.act_window" id="action_pos_all_sales_lines">
      <field name="name">Lines</field>
      <field name="type">ir.actions.act_window</field>
      <field name="res_model">pos.order.line</field>
      <field name="view_type">form</field>
      <field name="context">{error:2}</field>
      <field name="view_id" ref="pos_order_line_view_tree" />
  </record>
```
2.- install/upgrade module

3.- then remove context:
```
<record model="ir.actions.act_window" id="action_pos_all_sales_lines">
      <field name="name">Líneas de pedido</field>
      <field name="type">ir.actions.act_window</field>
      <field name="res_model">pos.order.line</field>
      <field name="view_type">form</field>
      <field name="view_id" ref="pos_order_line_view_tree" />
  </record>
```
4.- install/upgrade module
Current behavior:
 - Context keep context {error:2}
Expected behavior:
- remove context declared on step 1
must add context= {} to avoid previous  context

**Comment by Yenthe666** [comment]
Hi @dansanti,

Thank you for your report!
Just to be sure, your XML code is not within `<data noupdate='1'>` right?
@mart-e what do you think?

Regards,
Yenthe

**Comment by dansanti** [comment]
Hi!

yes , is not with  `<data noupdate='1'>`  a clean `<data>` tag

**Comment by mart-e** [comment]
Hello,

Sorry but it is how the ORM works, it is expected.

When installing/upgrading a module, Odoo will work +/- like this:

```
- Does external ID (here `action_pos_all_sales_lines`) exists?
|- No 
   |- create (`create`) a record will all the given data in the xml
   \- create an external id with the id of the created record
\- Yes
   |- find the id of the existing record linked to that external id
   \- update (`write`) the record will all the given data in the xml
```

So if you remove, a line from the `record` tag, it will do nothing on that field.

If, in my module, I do
```xml
<record model="ir.actions.act_window" id="action_pos_all_sales_lines">
</record>
```

it will do... nothing
