### ISSUE TITLE
add IGNORECASE to DBFILTER check

### ISSUE THREAD

**Issue by emanuelezambrano** [odoo/odoo#17407]
Impacted versions: 10.0

Steps to reproduce:

Current behavior:
if I set "dbfilter = ^%d$" and I go to "http://mydb.mydomain.com" but my database name is "MYDB", odoo can't identify the database. I need to use "^(?i)%d$" to force case invariant regex match.

Resolution:
You can add "IGNORECASE" to "db_filter" funcition inside "http.py" file. Alternatively document this behavior

**Comment by Yenthe666** [comment]
Hi @emanuelezambrano,

Thank you for your report.
In my opinion this is desired behaviour. Why? Imagine having a database named "Live" and "live". With your database filter changes the first one wouldn't show up while you might need it. I do believe that it is not a best practice to create database that are so similar with just a capital letter as a difference but it is possible.
@mart-e to change or to document?

Regards,
Yenthe

**Comment by mart-e** [comment]
Thanks, this is not a usual case so we don't want to add it in the command. Regex _are_ case sensitive, it makes sense to add the option if needed.
I have added your example in the documentation.

**Comment by Mhnd3** [comment]
from python 3.6 onward, using this regex "^(?i)%d$" emits a deprecation warning "Deprecate the use of flags not at the start of regular expression", check https://bugs.python.org/issue22493 
in future versions it might even be forbidden to use the flags in the middle of regex, therefor The flag "(?i)" should be positioned before the "^", to be "(?i)^%d". of course this effects all flags "(?aiLmsux)", check https://docs.python.org/3.6/library/re.html
