### ISSUE TITLE
[10.0] Wrong number of accounts when searching

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#17408]
Impacted versions: v10c / v10E

Steps to reproduce:

Create a product, open any dropdown related to accounts under the accounting tab, click on search more.

Current behavior:

Odoo is displaying only a set of accounts and not all of them. But if you place your cursor on the search field and press enter it will now show all the accounts.

It is like if some sort of filter is getting applied but is not visible by any tag or anything.

Expected behavior:

Show all accounts.

Video/Screenshot link (optional):

https://youtu.be/bjV0JVMf-lY

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Thank you for your report.
Can you try to reproduce this kind of behaviour on an official Odoo instance? (runbot.odoo.com).
If I do this on a runbot I always see all of them. (cc @nim-odoo)

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Actually, this is true. There [is a limit](https://github.com/odoo/odoo/blob/75c803bbbda447e6357e7a4fefd9e8b39e81f971/addons/web/static/src/js/views/form_common.js#L214) to show only the first 160 records when doing a search more.
It was introduced as a quick fix for performance reasons, as search more of large databases where too slow.
We assume that, if you have more than 160 result, you will remake a new search anyway that will research on the whole set.

@ged-odoo can we consider removing the `name_search` to make the search only once the popup is opened instead?

**Comment by edsersolis** [comment]
Hello @ged-odoo should I close this issue? I know it is a minor issue but still should be fixed. Please let me know.

**Comment by ged-odoo** [comment]
yes, I do not see how to fix this issue properly in version 10.0, because changes would be non trivial.
