### ISSUE TITLE
base_import_module stopped working

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#17419]
I'm using `Odoo 10.saas~14+e (Enterprise Edition)`. Today the base_import_module suddenly stopped working for me. I have a large module of xml data files that I use to import some customizations to our odoo instance. The module has been imported 100's of times without issue. All of a sudden today, I am getting an error:

    Error while importing module 'mycompany': u'Unknown path: /tmp/tmpX2SRDC/mycompany/__manifest__.py'

It's as if the base_import_module does not think my module contains a `__manifest__.py` file, but it does. 

Did something change with the base_import_module that might be causing this error all of a sudden?

**Comment by wtaferner** [comment]
Jep b/c of this [security patch](https://github.com/odoo/odoo/commit/76cd8d2558d2a1fc11681dbc4a134ba06fb698c0) which does limit the allowed path.

@odony
This is for you I guess :smile:

**Comment by flyingL123** [comment]
Oh wow, thanks @wtaferner this has been causing me headaches all day. @odony is it possible to get this fixed? On Odoo SaaS the module gets uploaded into that temporary location. How can this security patch account for that?

**Comment by flyingL123** [comment]
Hi @odony, do you have any input on this? Is this something that can be resolved, and if so, do you know how long it will take to make it into the framework? This change is completely preventing me from importing modules on Odoo SaaS, which has brought development to a halt.

**Comment by odony** [comment]
@flyingL123 Just a little more patience, the patch will be rolled out in the coming hours

**Comment by odony** [comment]
Should have been fixed by c6b9b69f6a483e7ccebf0b823240b71a8f426fd3. Forwarded and rolled out to the infrastructure a few minutes ago.
@flyingL123 let me know if you still have issues

**Comment by flyingL123** [comment]
Yes! Thank you so much @odony and @wtaferner. It's working correctly for me now.
