### ISSUE TITLE
[9.0]@api.constrains or create_from_ui override for calls from POS to res.partner not working

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#17418]
Impacted versions:
9.0

Steps to reproduce:
1.- create models with ( osv or models)
```
class res_partner(models.Model):
    _inherit = 'res.partner'

    @api.constrains('vat')
    def _vat_check(self):
        _logger.info("im in")

```

2.- Restart odoo instance 
Current behavior:
_vat_check never fired, also create_from_ui

Expected behavior:
fire method from models for res.partner

**Comment by mart-e** [comment]
Sorry but it works, we are [doing it here](https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/res_partner.py).

My guess is that you have not imported your python file or something like this.

Closing as github is for bug reporting, not for help on custom development.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by dansanti** [comment]
@mart-e  hi! thanks for the reply but that module is fired from backoffice, but from pos not https://github.com/dansanti/l10n_cl_base_rut/blob/9.0/base_vat.py
