### ISSUE TITLE
[8.0][Master] Barcode Scanner - Error in Process

### ISSUE THREAD

**Issue by gigidn** [odoo/odoo#1746]
If a line make an error (like no serial number entered) system make a strange behavior.

a) Create a delivery order whit one product that need shipping lot trace. (1 unit)
b) Open barcode scanner and enter 1 unit but not the serial number.
c) System show popup error because no serial number is entered.
d) System put the operation on processed state
e) Change the view from to-do to processed 
f) Add the serial number to the product

Now for complete the shipment need to click on create backorder, the label of button should be "complete transfer" not "create backorder" and maybe if user can create a backorder in this stage need addition button for this.

**Comment by Yenthe666** [comment]
Hi @gigidn,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
