### ISSUE TITLE
POSBox image in a raspberry pi3, how does it work with an HDMI screen?

### ISSUE THREAD

**Issue by SborealisS** [odoo/odoo#17472]
I installed the POSBox image in a raspberry pi3, everything worked great, now I would like to use that rp as a graphic POS and connect some HDMI screen and a printer to it..

I could see that there is no graphic interface installed by default in the POSBox image. shoulod I install a graphic interface on the raspberry pi3?

Thanks in advance!

**Comment by Balipeace** [comment]
I would like know too...

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

For the posbox subject, you don't need to install anything, everything is shipped.
The latest version of the posbox has a graphical screen when you connect to it but this feature is only available in v11

Regards
