### ISSUE TITLE
accounting: Settings "Inter-Bank Transfer Account" not offering correct (SKR03) account.

### ISSUE THREAD

**Issue by bsgmbh** [odoo/odoo#17476]
Impacted versions: 9,0C, 10.0C

Steps to reproduce: 
- Install German SKR03 chart of accounts, then Accounting module.
- Goto Accounting > Settings, try to setup "Inter-Bank Transfer Account". 
- Odoo will offer a few accounts and when prompted to search for more, will only show 160 entries 
> This is obviously by design, see [here](https://github.com/odoo/odoo/issues/17408).
- Pressing enter in the search field will retrieve 237 entries, effectively ALL accounts from the correct section of the chart of accounts, except for bank and cash accounts, which IS correct, but there is 1, only one, additional account missing, which is the correct entry for this setting, "1360 Geldtransit".
- This makes it seem as though this omission is done "by design", but it is of course a bug.

Current behavior:
- The correct account for "Inter-Bank Transfer Account" is (seemingly deliberately) excluded from the SQL query for available accounts for this feature.

Expected behavior:
German SKR03 account "1360 Geldtransit" should be offered as a choice for this setting.

Video/Screenshot link (optional):

**Comment by JosefKaser** [comment]
Only current asset accounts with "Allow Reconciliation" == True are being listed in the mentioned dropdown list. Account 1360 is not set to allow reconciliation.

The same applies to account 1460 of the german SKR04.

Once you allow reconciliation for the account it can be selected.

**Comment by bsgmbh** [comment]
That did it, thank you Josef, and also for the super fast reply!

Out of curiosity, would you say that the default setting of "Allow Reconciliation" == False for these two accounts is correct? 

I may misunderstand the concept of reconciliation in Odoo, but classically this would refer to both sides of a double entry being checked to match. If this is what is meant here, would an "implicit money transfer account" such as this or 1460 in SKR04 not be a prime target for requiring "reconciliation"?

**Comment by Yenthe666** [comment]
Closing this report as @JosefKaser answered it (thank you!).
