### ISSUE TITLE
Odoo 10 service crash in ubuntu 16.04 LTS 

### ISSUE THREAD

**Issue by setiaji** [odoo/odoo#17483]
Impacted versions: 10

Steps to reproduce: When creating new inventory product and opening e-commerce module (shop page) in the same time, suddenly odoo services crash. 

This is my journalctl report: 

Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,797 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/dataset/call HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,824 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/dataset/call HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,826 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/dataset/call HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,852 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /im_livechat/init HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,945 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/proxy/load HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,963 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/proxy/load HTTP/1.1" 200 -
Jun 08 13:23:28 server01 odoo-server[3606]: 2017-06-08 04:23:28,966 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:28] "POST /web/proxy/load HTTP/1.1" 200 -
Jun 08 13:23:29 server01 odoo-server[3606]: 2017-06-08 04:23:29,070 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:29] "POST /website/translations HTTP/1.1" 200 -
Jun 08 13:23:29 server01 odoo-server[3606]: 2017-06-08 04:23:29,078 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:29] "POST /web/dataset/call_kw/web.planner/search_read 
Jun 08 13:23:29 server01 odoo-server[3606]: 2017-06-08 04:23:29,206 3606 INFO server01 werkzeug: 192.168.12.147 - - [08/Jun/2017 04:23:29] "POST /web/dataset/call_kw/web.planner/render HTTP/
Jun 08 13:23:33 server01 systemd[1]: odoo-server.service: Main process exited, code=killed, status=9/KILL
Jun 08 13:23:33 server01 systemd[1]: odoo-server.service: Unit entered failed state.
Jun 08 13:23:33 server01 systemd[1]: odoo-server.service: Failed with result 'signal'.

My server specification: 
RAM: 1GB
CPU: 1 core

Current behavior: odoo service crash

Expected behavior: running smoothly

**Comment by nilshamerlinck** [comment]
Looks like the linux OOM killer killed your odoo process because of a lack of memory. Do you have some swap memory configured?

**Comment by Yenthe666** [comment]
Hi @setiaji,

As @nilshamerlinck already answered, this is because of a lack of memory, your server probably ran completely out of memory. As a sidenote, one core in combination with 1GB RAM is really not a lot. Your Ubuntu itself needs ~700MB of RAM, which only leaves 300MB.
You might want to upgrade you server a bit 😉

**Comment by setiaji** [comment]
@nilshamerlinck and @Yenthe666 thanks for your analysis, i have to upgrade for RAM only or core also ?

**Comment by Yenthe666** [comment]
Hi @setiaji,

You should probably change to two cores and 2GB of RAM. It depends a lot on the amount of users etc though but two cores and 2GB RAM should atleast keep your Odoo up & running.

**Comment by setiaji** [comment]
Hi @Yenthe666,

Allright i will upgrade then hope my Odoo will running smooth

**Comment by Yenthe666** [comment]
@setiaji best of luck! I'll close this report for now. If you still face issues after this then comment back and we'll see what we can do for you.
