### ISSUE TITLE
[10.0] Pricelist not applying with quantity on POS

### ISSUE THREAD

**Issue by xavierjimenezqubiq** [odoo/odoo#17493]
**Impacted versions:**

Latest 10.0 version on Runbot

**Steps to reproduce:**

Create a pricelist with variable prices for a product depending on the quantity:
![issue1](https://user-images.githubusercontent.com/22770010/26925018-6940f8b2-4c48-11e7-8daa-7f4e3750d913.jpeg)

Select that pricelist on the POS:
![issue2](https://user-images.githubusercontent.com/22770010/26925062-8428d604-4c48-11e7-9ea1-35378a6474cc.jpeg)

**Current behavior:**

Price is not changing on the POS:
![issue3](https://user-images.githubusercontent.com/22770010/26925080-97369150-4c48-11e7-839a-7ea526b988d8.jpeg)
![issue4](https://user-images.githubusercontent.com/22770010/26925082-9a2116e2-4c48-11e7-9c8d-94256add727f.jpeg)

**Expected behavior:**

Price changing on the POS when the minimum quantity is selected for that product.

**Comment by jorenvo** [comment]
Indeed, this is a current limitation with how pricelists are handled in the POS. Essentially the price for a product is computed once when the POS loads and that's it. We are currently improving this for future versions. You can follow the progress at: https://github.com/odoo/odoo/pull/16549.
