### ISSUE TITLE
forward message functionality

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#1751]
Ability to forward messages internally & externally, significant roadblock to using OpenERP/Odoo as a single businesswide application

**_Impacted versions:**_
- Version 7.0-20140722-231204

**_Steps to reproduce:**_
1. Open message in messaging

**_Current behavior:**_
- No option to forward message

**_Expected behavior:**_
- Option to forward message

**Comment by Yenthe666** [comment]
Hi @rolandwells ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
