### ISSUE TITLE
Poblem with Emojis 

### ISSUE THREAD

**Issue by durvilchat** [odoo/odoo#17517]
Hello, I need help on odoo
My problem is the following: when I open the caches windows, the emojis no longer work and in the chat window and only works when I close the chat windows.
this.$('.o_composer_button_emoji').popover({

        placement: 'top',
        content: function () {
            if (!self.$emojis) { // lazy rendering
                self.$emojis = $(QWeb.render('mail.ChatComposer.emojis', {
                    emojis: emojiss,
                }));
                self.$emojis.filter('.o_mail_emoji').on('click', self, self.on_click_emoji_img);
            }
            return self.$emojis;
        },
        html: true,
        container: '.' + self.emoji_container_classname,
        trigger: 'focus',
    });
I think the problem would be due to a multiplication of this part of the code in the other other windows. 
Please i am not experienced in i jquery i would like you to help me solve this problem.
 Thank you in advance for your understanding.

**Comment by Yenthe666** [comment]
Hi @durvilchat,

Am I correct that you're asking a question about custom development? This is not a bug in the official Odoo without any custom development, right?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi,

I'm closing this issue as there has been no response in almost a month.
If you still face this issue then please provide more information and if it is valid I will reopen this issue for you.

Regards,
Yenthe

**Comment by jlzhou** [comment]
The issue is still there, the emoji button does not work in the channel footer, see #18586.
But the next issue is by clicking these emoji icons without any effect sometimes.
