### ISSUE TITLE
[10] Required Textarea field wrong background in non-edit form view

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#17510]
Impacted versions:
v10

Steps to reproduce:
1. Login to v10 runbot
2. Enable debug mode
3. Go to Setting/System Parameter
4. Click anyone of the item

Current behavior:
![image](https://user-images.githubusercontent.com/8391358/26961489-9d2596d2-4d11-11e7-9ed9-d1d07c503b06.png)

Expected behavior:
No background color

**Comment by Yenthe666** [comment]
Hi @auyeung112002,

Thank you for your report.
This does indeed look like a bug as the required fields should only be blue (highlighted) when you're in the editable mode.
@mart-e and @nim-odoo can you check out the linked PR please?

Regards,
Yenthe

**Comment by auyeung112002** [comment]
Created another PR https://github.com/auyeung112002/odoo/pull/3

**Comment by qsm-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/3a13eada0ee522b8ac919bbac424519dcf639ac1
