### ISSUE TITLE
Sale & Purchase Vouchers

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#17520]
Impacted versions: 10

Steps to reproduce: install the Sale & Purchase Vouchers app

Current behavior: tables were properly installed, but no item menus have been created

Expected behavior: new item menus for managing purchase vauchers

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your report.
To which module & menuitem are you referring? Could you add more information please?

**Comment by Yenthe666** [comment]
@ccandito I'm closing this bug report as there has been no response in a few months.
