### ISSUE TITLE
[10.0] ODOO Payroll - Payslip Refund Issue

### ISSUE THREAD

**Issue by milanpatel1519** [odoo/odoo#17529]
Impacted versions:
10.0

Steps to reproduce:
Make employee's payslip with salary rule which have input values. Like add BONUS salary rule with result = inputs.BONUS.amount python code and also add one input for for rule.
Create payslip with with BONUS rule salary structure and compute and confirm it.
After paid the salary slip REFUND it.

Current behavior:
If we click on refund it shows "Wrong python code for salary rule Bonus.".
demo record for BONUS
       `<record id="hr_rule_bonus" model="hr.salary.rule">
            <field name="name">Bonus</field>
            <field name="sequence">15</field>
            <field name="code">BONUS</field>
            <field name="category_id" ref="hr_payroll.ALW"/>
            <field name="condition_select">none</field>
            <field name="amount_select">code</field>
            <field name="amount_python_compute">result = inputs.BONUS.amount</field>
            <field name="input_ids" eval="[(0, 0, {'name': 'BONUS Allowance', 'code': 'BONUS'})]"/>
        </record>`

Expected behavior:
Please let me show the changes or solve this bug.

**Comment by Yenthe666** [comment]
Hi @milanpatel1519,

Thank you for your report.
Could you please make a recording of this behaviour showing it step by step? This would make it much easier to reproduce (and fix if there is an issue).
Can you reproduce it on an official Odoo instance? (runbot.odoo.com)

Regards,
Yenthe

**Comment by milanpatel1519** [comment]
Hey @Yenthe666,
Thanks for replay.
Here I made video for salary rule, salary structure and payslip for employee. You can find a warning of wrong python code for salary rule while you are refunding payslip and not when you confirming.

[payslip_issue.zip](https://github.com/odoo/odoo/files/1067146/payslip_issue.zip)

Regards,
Milan

**Comment by stormfish-sci** [comment]
Hello @milanpatel1519,

I have been struggling with this issue for a long time, too.  I have not found a solution yet, however my analysis of the code suggests that the refund code doesn't copy the input values into the refund context properly.  When any rules which depend on Input values run in this refund context, the values don't exist resulting in the errors you describe.  I have not yet figured out how to correct this, but I will share if/when I do.

Sadly, the only solution I have found is to backup my odoo instance, run payroll, and roll-back if any errors occur.

This issue exists in Odoo 10.0-20181126 (Community Edition).

Best regards,
Theron

**Comment by jersoncf** [comment]
Hi.

I've had the same problem and came to the same conclusion as **stormfish-sci**. My solution was to redefine the field **input_line_ids** from model **hr.payslip.**.

So I created a module that inherits hr_payroll and as I said, I redefined the field **input_line_ids**.

So it's like this:
`input_line_ids = fields.One2many('hr.payslip.input', 'payslip_id', string='Payslip Inputs',
        readonly=True, copy=True, states={'draft': [('readonly', False)]})`.

I just added copy=True.

It solved the refund problem because now it copies the inputs.

I hope this will also work for you.

Best regards,

Jerson Figueiredo
