### ISSUE TITLE
Error trying to add new field related with address in res.partner model

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo/odoo#17534]
Impacted versions: 10.0

Steps to reproduce: 
Create a new module that inherited from res.partner, then create a field and the variable name must contain the address word. In my case the variable called contact_address. Add the new field in the partner view. If you reproduce the error and try to overwrite the write function the issue don't dessapear.

Current behavior:
When edit the partner record Odoo assign a address value to the new field. If the user modify the value and save the Odoo discard the change and return the pre-change value.

Expected behavior:
Odoo must allow save the user input value in the new field.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @yasmanycastillo,

Could you perhaps share all of your code, either by pasting it here or providing a download link?
I'd like to see the whole logic & code. 😄 

Regards,
Yenthe

**Comment by Yenthe666** [comment]
I'm closing this as there has been no response in ages.
