### ISSUE TITLE
[16.0] project: Incorrect button with token access on stage change mail

### ISSUE THREAD

**Issue by carolinafernandez-tecnativa** [odoo/odoo#175396]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Go to Project > Projects and Create new Project with this configuration:

Setup a Customer and Project privacy All internal users
![image](https://github.com/user-attachments/assets/43b328a4-641d-4007-92ca-39193f1d4706)

- Create two task as an example:
<img width="505" alt="image" src="https://github.com/user-attachments/assets/57933b4e-a040-4fbf-b4b1-6aef398d3a4f">

- Activate in Project > Configuration > Settings > Project stages.
-  Set a email template to one of the stages:
![image](https://github.com/user-attachments/assets/fd36580f-0e2c-4282-9781-005b797ce23c)

- Change project created to stage "Done".
- Email is sent to Customer and without any access to project 

![image](https://github.com/user-attachments/assets/78c1fbfa-114d-45d5-a87c-f442c07774e0)

As i show before, the url has access_token, so anyone that has access to that url can see all tasks and project information in the portal without login and if user is logged, he should not be able to see project as the project privacy is set private.

![image](https://github.com/user-attachments/assets/f3feb3ce-4436-4d8c-b668-bf4390fdf469)

The same is happening with notification sent on changing task stages if the stage is configured with an email template.

Commit that introduces this change of behaviour:
https://github.com/odoo/odoo/commit/4059bbabac8983a335545b06e5366dcda32445a5

@Tecnativa TT50365

**Comment by carolinafernandez-tecnativa** [comment]
Hi any news?
@tde-banana-odoo 
cc @pedrobaeza

**Comment by tde-banana-odoo** [comment]
@xavierbol

**Comment by xavierbol** [comment]
(Hello @tde-banana-odoo thanks for the ping 🙂 )

Hello @carolinafernandez-tecnativa @pedrobaeza 

Thanks for your feedback! 

Indeed, we did not override the [_notify_get_recipients_groups](https://github.com/odoo/odoo/blob/16.0/addons/project/models/project.py#L2407-L2436) in project (`project.project` model) as we did in Task (`project.task` model) to display or not the a link to the record in the portal view according to the visibility of the project.

We will do a fix to have the same behavior than task.

However, you said you have the same issue in task? 😨 I am a bit surprised. I quickly check in local and I don’t have the issue in 16.0. Maybe. I miss something. 🤔

**Comment by pedrobaeza** [comment]
Hi, @xavierbol thanks for the follow-up. Yeah, I have tried it again from a runbot, and it seems to work properly from tasks:

![imagen](https://github.com/user-attachments/assets/e1fff7d3-ad94-48b0-bc9b-b7a6097515c1)

so the problem seems to be only with projects.

**Comment by xavierbol** [comment]
Hello @pedrobaeza 

Great! Thanks for the confirmation, I will do a fix for project. 🙂 

Have a nice evening! 🙂
