### ISSUE TITLE
Repair management

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#17546]
Impacted versions: 10

Steps to reproduce: create a repair order with a component to be add 

Current behavior: no inventory posting, only accounting posting and decrease of stock

Expected behavior: inventory posting should be performed also in warehouse module

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback here please?

**Comment by ccandito** [comment]
???
sorry I'didn't get it
which feedback I should provide?
regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

From nobody, I'm waiting for feedback from jco-odoo - he is the one that made this module. 😄

**Comment by sle-odoo** [comment]
Hi,
A move is (fortunately) created for the components added in a repair order. See [here](https://github.com/odoo/odoo/blob/10.0/addons/mrp_repair/models/mrp_repair.py#L366).

Regards
