### ISSUE TITLE
Point of sale: sequential invoice number on receipt is mandatory in many countries

### ISSUE THREAD

**Issue by vilder** [odoo/odoo#1754]
point of sale module should generate a sequential number on the receipt instead of a timestamp,
this way ODOO could be used out of the box in many countries.

**Comment by Yenthe666** [comment]
Hi @vilder,

Thank you for your report.
I'm closing this one in favour of https://github.com/odoo/odoo/issues/1288 (as it is older). You can find all the replies and feedback on this case there.

Regards,
Yenthe
