### ISSUE TITLE
[8.0] Bug price included tax

### ISSUE THREAD

**Issue by SGiuseppe** [odoo/odoo#17547]
Impacted versions: In my system there is 8.0

on module: product_visible_discount.py

Steps to reproduce: When you change the amount for a product with tax included, the calculated discount is reset

solution:
After line 107 replace with:
```            
            if taxes.price_include:
                tax = [taxes.id]
            else:
                tax = result.get('tax_id', [])

            # new_list_price = account_tax_obj._fix_tax_included_price(cr, uid, new_list_price, taxes, result.get('tax_id', []))
            new_list_price = account_tax_obj._fix_tax_included_price(cr, uid, new_list_price, taxes, tax)`

In my tests it works

**Comment by Yenthe666** [comment]
Hi @SGiuseppe,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
