### ISSUE TITLE
Label translation does not work

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#1755]
Hello

While testing around and also test this on runbot http://10365-8-0-164470.runbot.odoo.com/web, I saw, that translation of labels even not work on some places.

On above runbot there are 3 languages installed:
en, de, fr. If you switch eg. to de and go to *Finanzen* (Accounting) some labels are still in english, same if you switch to fr.

Eg. translation for *Invoice Date*:
In account/i18n/de.po the msgid for *Invoice Date* does exist:

#. module: account
#: report:account.invoice:0
#: view:account.invoice:0
#: field:account.invoice,date_invoice:0
#: field:report.invoice.created,date_invoice:0
msgid "Invoice Date"
msgstr "Datum Rechnung"

But even in accounting and also on a invoice report it's not translated.

As translation is a base/main feature, it should be fixed...

Thanks and regards
thomi

**Comment by yostashiro** [comment]
I cannot get the Qweb PDF translations of Request for Quotation and Purchase Order to work.  I thought this commit https://github.com/odoo/odoo/commit/27fa742a700dfada76658661073f4b002032adf5 should have fixed the issue but it does not seem to be the case.

Translations of Quotation (sales) works as expected.

**Comment by yk2kus** [comment]
@odony any update on mail groups translations?

**Comment by mart-e** [comment]
@yk2kus this is issue is quite messy and outdated (we have fixed most of it), you should probably create a new issue.
Closing, so better create new one for individual problems (and eventually referring to this one)
