### ISSUE TITLE
[project] '_check_dates' constraint never checked

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#1756]
A constraint named '_check_dates' is defined in the _constraints statement of the class project in project/project.py but even if I enter a start date greater than the end date, no error is displayed.

**_Impacted versions:**_
- trunk (e081fd0df4a4989eacc0e06ccda3f1091eae61b9)

**_Steps to reproduce:**_
1. Install project module
2. Go to project and create a new project called 'Test'
3. Put '08/13/2014' as start date
4. Put '08/06/2014' as end date
5. Save the new project

**_Current behavior:**_
- No error message is displayed (and the project is saved) because the constraint '_check_dates' is not checked (the system doesn't enter in the _check_dates() method.

**_Expected behavior:**_
- The error message "Error! project start-date must be lower then project end-date." must be displayed and the project mustn't be saved with these values.

**Comment by Yenthe666** [comment]
@pna-odoo any update on this one?

**Comment by qtheuret** [comment]
It seems that this issue was closed by the fix on https://github.com/odoo/odoo/issues/2514

**Comment by Yenthe666** [comment]
Ahh you're right @qtheuret! Than you for the feedback - closing as it is solved.
