### ISSUE TITLE
-u module, --update=all restores deleted data.xml records

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#17561]
Impacted versions: All

Steps to reproduce:
1) Delete a project.task.type stage (or any record record declared via an xml data file)
2) Update project (or the corresponding module)

Current behavior:
The deleted records are restored. 

Expected behavior:
The deleted records stay deleted.

One of the systems strengths is its ability to be adapted to a specific use cases. The fact that such changes as deleted records are reverted potentially clutters the user experience and or hinders development if such behavior is desired (think initial non demo data that the user is expected to tailor to meet their specific needs). 

Would a pull request implementing a flag such as <data delete="1"> be considered? Such records when deleted would be be left in ir.model.data with *res_id* set *null* and when updating a module reinsertion of these records would be skipped based on there presence in the database. To satisfy a situations where current behavior might be desired (fixing broken module state) a command line flag --restore-data could be implemented.

**Comment by Yenthe666** [comment]
@mart-e didn't you once say on another thread this was the desired behaviour and that it won't be changed?

**Comment by gustavovalverde** [comment]
Isn't the "noupdate" changing this behavior in XML?

**Comment by mart-e** [comment]
> Would a pull request implementing a flag such as be considered?
> Isn't the "noupdate" changing this behavior in XML?

`forcecreate="True"` is what you are looking for.

So yes, not going to change the behaviour of the noupdate but we can add `forcecreate` where it makes sense.
If it makes sense for the business case, we can accept adding these flags in master.

Ironically, in your example. you have chosen a model where we have already added the flag forcecreate 59a700c8e6c7ae982a6d2c40521a43edf31194f8 😉
