### ISSUE TITLE
Bug in file upload in Odoo 16

### ISSUE THREAD

**Issue by mithang** [odoo/odoo#175793]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I uploaded the file a.png, then removed a.png and tried to upload a.png again, but it failed and couldn't be uploaded. However, uploading the file b.png works fine. I tested this on Odoo 17 and did not encounter the same issue, but in Odoo 16, this error occurs.
Ex: Upload avatar in my profile

**Comment by duong77476-viindoo** [comment]
Fix here bro, hope they merge https://github.com/odoo/odoo/pull/176126

**Comment by duong77476-viindoo** [comment]
they merged, please close this if it does the trick
