### ISSUE TITLE
Cannot change product in draft picking (TypeError: d.error is undefined)

### ISSUE THREAD

**Issue by sitimawaddah** [odoo/odoo#17578]
Impacted versions: 10c

Steps to reproduce:
- i am using demo database
- go to menu Inventory/All Transfers
- create new picking, choose any picking type (I choose delivery order)
- input items
- Save
- click Edit
- choose one of items and change to other product 

Current behavior:
if using Google Chrome, It will raise error warning *Error: QWeb2 - template['CrashManager.warning']: Runtime Error: TypeError: Cannot read property 'data' of undefined* 
if using Firefox, error will become *TypeError: d.error is undefined*

Expected behavior:
no error 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/12973701/27066034-6db66440-502b-11e7-8326-982a7f73ff4d.png)

**Comment by sitimawaddah** [comment]
additional info: this issue happened when I select item use key down or up in keyboard. If using mouse selection, this issue rarely exist.

**Comment by Yenthe666** [comment]
Hi @sitimawaddah,

Thank you for your report.
I can confirm that this is an issue in Odoo.
@Gorash and @sle-odoo can one of you guys look at this one?

Regards,
Yenthe

**Comment by Troublicious** [comment]
Hi all,
this bug is still present in recent versions, and happens also when changing consumed materials on manufacturing order.
No solution so far ??

**Comment by sle-odoo** [comment]
Hi,
I just test in the latest version and i't s working at my end. Could you test on the latest runbot?

**Comment by Troublicious** [comment]
I can confirm it works on latest runbot, but not in my 20 september install ...
I'll update it and report here

**Comment by sle-odoo** [comment]
Alright, in the meantime i'm closing this issue. If you're still facing it after an update, feel free to comment and i'll reopen it.

Regards
