### ISSUE TITLE
[9.0]Thousand separator is not applied by website module odoo 9

### ISSUE THREAD

**Issue by BoubakerAB** [odoo/odoo#17614]
Impacted versions: [9.0]

Steps to reproduce:
Configure your language with decimal separator as ","
Once your language is configured, go into the shop and select an article. You'll see the price correctly with the comma

(Same comportment when adding to cart and trying to change the quantity. I suppose this is the same bug)
image

[[ Bugs ]]
in Website Ecommerce odoo with product price séperator i change the configuration in Settings >Translations >Languages "Thousands Separator" Field But is not applied in Website(Look picture ) for example 200 000 > in website 200,000 How to delete the comma

I want to display 200 000 
Example:
<img src="https://i.stack.imgur.com/PPkMn.png/">

**Comment by Yenthe666** [comment]
Hi @OpenDevTN,

Thanks for your report.
I've edited your first comment so it shows the image right away (which is very handy for other people).
@JKE-be this looks like one for you to check though!

**Comment by OpenDevTN** [comment]
thank you @Yenthe666

**Comment by JKE-be** [comment]
@OpenDevTN Can you reproduce it on runbot ? 

Because between the release of 9.0 and now, their are many patch about it !

Could you provide the code that you use to print this amount ? 
t-esc ? t-field ? t-options ? 

Thanks

**Comment by OpenDevTN** [comment]
thank you @JKE-be  for your reply
I do the same in runbot and it changes nothing
I want to remove the comma in the price in website
750,000.00 I want him to appear without a comma > ( 750 000) 
look  picture in runboot Odoo V9 


<img src="https://s18.postimg.org/fpoqk6sl5/image.png">
<img src="https://postimg.org/image/4u7veq1iz/">
Thanks

**Comment by OpenDevTN** [comment]
There is no solution to this problem @Yenthe666 @JKE-be 

Thank all

**Comment by JKE-be** [comment]
Hi @OpenDevTN 

I don't see the problem.
Go to language setting, set that you want a ' <space>' as thousand separator, and that works out of the box.

The only specific case that is if you don't want anything, you need to set an empty char (eg: &#x200b;) because by default, we use a comma if no symbol is given !

**Comment by BoubakerAB** [comment]
thank @JKE-be  
No problem the web interface it perfectly 
but in website shop the price not true

**Comment by JKE-be** [comment]
Are you sur to set a space and not nothing ? 

And yes, it works on ecommece also !

**Comment by BoubakerAB** [comment]
Thank @JKE-be 
The problem has been resolved
I put a SPACE in thousand separator 
Example :  20000 > 20 000 
If field thousand separator   left blank, this appears 20,000

the solution
<img src="http://www.zupimages.net/up/17/25/mnn1.png">

**Comment by JKE-be** [comment]
Hello,

Glad to hear that ;)

As specified in my previous answer:

> if you don't want anything, you need to set an empty char (eg: `&#x200b;`) **because by default, we use a comma if no symbol** is given !

It is not a bug, but the expected behavior.
