### ISSUE TITLE
[17.0] stock: delivery slip has product description in two languages when partner language changed.

### ISSUE THREAD

**Issue by john-herholz-dt** [odoo/odoo#176317]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Enable at least two languages
- Go to Inventory > Delivery Orders and select a delivery
- From the delivery, go to partner_id and change the language
- Go back to delivery order and print delivery slip

Current behaviour:
On the delivery slip, the product description is in both languages. The previous and the newly changed language.

Expected behaviour:
The delivery slip contains the product description in the newly changed language

[language_doubled.webm](https://github.com/user-attachments/assets/b857d781-84f6-4289-ae06-f170d7ffa5bf)

**Comment by hari1119** [comment]
@john-herholz-dt , It's indicating description on transfer else we will confuse between the delivery slip and transfer entry.I think it's make sense.

**Comment by john-herholz-dt** [comment]
Hello @hari1119 

thanks for having a look at it.
I am not sure if you understood the issue.

When printing a delivery slip normally, the description is the product name field.
If you change the language of the partner it is the product name twice.
One in the old language, one in the new language.

Having the description twice is confusing.

**Comment by hari1119** [comment]
I am not sure @john-herholz-dt ,i explored the code, in my point of view it's one of the feature.

Lets me try to explain
         For example the partner language is French, same time company language is English, ERP user don't know French, if the ERP user want to check the products in delivery slip means, description on transfer in English will help to verify that.
