### ISSUE TITLE
[V8] - Partial Delivery - Usability Issues

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#1763]
Hello, 

As a business analyst I found some points quite confusing in the V8 regarding partial delivery, could you please take a minute to answer those questions/remarks: 
1.  I can’t find a way to process a partial delivery in the back end. Is it something intentional? Did I miss something? In my opinion, some users only manage manually their small stock with odoo and don’t really need this new interface especially made for scanner and barcode. Will they be obliged to use it to process partial deliveries? 
2.  When you deliver only a part of your delivery order in the front end (“process button”), you don’t have any trace of this in the back end (no stock move, no change on delivery order, etc). It apparently creates stock packs but they are not visible for the user? It means that the user has to click on “process” and then on “create back order” if he wants to see the real stock in back end. I’m a bit afraid that instinctively people think that “process” is enough, what do you think? 
3.  If you “process” 10 units and then you want to cancel it but not cancel all the delivery order (for example, you made a mistake or your customer prefers have all the products at once). How do you process as the stock packs are not visible? 
4.  If you open the bar code interface just one time, the “transfer” button in the back end disappears. You are therefore not able to deliver all products at once for this delivery order in the back end anymore.  Is it not a weird behavior?

Thanks in advance for your answer, 

Christelle De Coninck (ACSONE)

**Comment by Yenthe666** [comment]
Hi there,

Jco-odoo has handled this report pretty much and Odoo 8.0 is no longer supported as a long term version.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
