### ISSUE TITLE
[saas-17.4] base: translations are missing in v17.4 which were existing in 17.0

### ISSUE THREAD

**Issue by jmutsaerts** [odoo/odoo#176498]
### Odoo Version

- [X] 17.4

### Problem description

Please note that there are many translations missing in saas-17.4. Below image shows a comparison of a Dutch portal page in 17.4 and 17.0. In 17.4 it's not translated, in 17.0 it was.

### Steps to Reproduce

Go to v17.0, switch to dutch and check translation in dutch my/account page
Go to v17.4, switch to dutch and check translation in dutch my/account page
Go to transifex and check the actual translation on 17.4 (and 17.0)

![image](https://github.com/user-attachments/assets/4869e15f-a4cc-4326-9c30-4f5039051144)

I have lost a potential client over this. He did not find the needed translations, wanted to import them but this is also disabled (base translations are ignored during import process through odoo backend UI as from v16.0, so I've learned)

@oomsveta @HydrionBurst @mart-e thank you very much for having a look at this. 

### Cause after first research

This term specifically was first introduced in 17.0 in october 2023. It just hasn't made the trip into saas-17.4.

https://github.com/odoo/odoo/commit/6739c317d11fe7e86379b65c16bdfde66807a09e#diff-a05c6616176d93a28e745d0f5220be22d96b4c4d01cd0b6b99fc859bc83763e8

As you can see here, the commit list on this file in saas-17.4 is awefully quiet:
![image](https://github.com/user-attachments/assets/339dc316-9d9f-48ec-a0a8-a73e4c3ea971)

Best wishes from Switzerland!
Cheers, Joep

**Comment by oomsveta** [comment]
Hello @jmutsaerts, thank you for reporting this issue!

The script that synchronizes between Transifex and Github has been broken for Dutch all this time 😕
It should be fixed now, thanks to @mart-e 👍 https://github.com/odoo/odoo/commits/saas-17.4/addons/sale/i18n/nl.po

**Comment by jmutsaerts** [comment]
Hi @oomsveta thank you so much for the quick solve! Cheers, Joep
