### ISSUE TITLE
Cannot added external javascript

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#17656]
Impacted versions: 10 c

Steps to reproduce:
i want to add google maps api, then i create xml to added web.assets_backend
`<odoo>
	<data>
		<template id="my_assets_backend" name="my_maps_asset" inherit_id="web.assets_backend">
			<xpath expr="." position="inside">
				<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3"/>
			</xpath>
		</template>
	</data>
</odoo>`

Current behavior:
google chrome console displaying error message "Could not get content for https://maps.googleapis.com/maps/api/js?v=3 defined in bundle 'web.assets_backend'."

Expected behavior:
no error message & i can use google maps

Video/Screenshot link (optional):
![screenshot from 2017-06-16 14-12-12](https://user-images.githubusercontent.com/7473166/27216111-7b2c2b1c-529e-11e7-9f76-e0ba418e733d.png)

**Comment by JKE-be** [comment]
Yes, it seems that this feature has disappeared during the last refactoring of the assets.

So, we will probably not patch it in v10 because it  is is not really a bug but a feature, and that a workaround exists, I invit you to add your file outside the asset.

@Gorash: any idea why it has been dropped ?

**Comment by Gorash** [comment]
Everything in the bundle is compiled into a single file (by type: css, js ...). External APIs should not be included in the compiled JavaScript file. A change can be made to insert the script before the compiled file. I can not remember whether this change was intended or not.
Nb: some particular behaviors could be modified and worked before by chance of implementation

**Comment by JKE-be** [comment]
@Gorash
Thanks for your reply.
We are agree that it should be not included in the 'single file'.
In the past we have a special behaviour (for absolute url: start with 'http') where we add all external files after.

```
<script src='assets.where_end'/>
<script src='external_lib1.js'/>
<script src='external_lib2.js'/>
<script src='external_lib3.js'/>
```


@CakJuice 
But as specify in previous answer, there are a work around and It not really a bug.
So I fwd it to the feedback team to keep a track and maybe add this behavior in a future version.

**Comment by CakJuice** [comment]
@JKE-be @Gorash thanks for your explanation.

**Comment by augustocadini** [comment]
How it can fixed?

**Comment by JKE-be** [comment]
@augustocadini 
You just need to don't add you external library inside the assets but after.

**Comment by augustocadini** [comment]
> @augustocadini
> You just need to don't add you external library inside the assets but after.

I is having a problem with it and I can't solve. I understanded the reason, but I can't found my error, I posted a question about it on SO: https://stackoverflow.com/questions/55169117/how-to-embed-google-maps-on-a-field-on-odoo-through-a-new-widget. I tried of several ways and I would be very grateful if anyone help me.

**Comment by JKE-be** [comment]
1. Prefer to use odoo.com/forum that github for question/bug instead of issue tracker github ;)
2. Odoo community /expert are probably more present on forum that SO ;)

else as explain... start to move maps.ggapi.com outside of your assets

```xml
<odoo>
    <data>
        <template id="assets_backend" inherit_id="web.assets_backend">
            <xpath expr="." position="inside">
                <script type="text/javascript" src="/vz_visit/static/src/js/google_maps_widget.js"/>
            </xpath>
            <xpath expr="." position="after">
                <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=[MY_API_KEY]&callback=initMap"/>
            </xpath>
        </template>
    </data>
</odoo>
```

And be sure that loading is finish before to use "new google.maps.Map(this.el, ..."

**Comment by augustocadini** [comment]
>     1. Prefer to use odoo.com/forum that github for question/bug instead of issue tracker github ;)
> 
>     2. Odoo community /expert are probably more present on forum that SO ;)
> 
> 
> else as explain... start to move maps.ggapi.com outside of your assets
> 
> ```
> <odoo>
>     <data>
>         <template id="assets_backend" inherit_id="web.assets_backend">
>             <xpath expr="." position="inside">
>                 <script type="text/javascript" src="/vz_visit/static/src/js/google_maps_widget.js"/>
>             </xpath>
>             <xpath expr="." position="after">
>                 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=[MY_API_KEY]&callback=initMap"/>
>             </xpath>
>         </template>
>     </data>
> </odoo>
> ```
> 
> And be sure that loading is finish before to use "new google.maps.Map(this.el, ..."

Thank you for your help and explanations. I can't make questions on Odoo forum yet. 

About the code, I'm use a callback function so the instance of object is called just when callback is called, that show happens after load content, but at now I found my problem at `<src>` declaration. The Odoo really can't get the content of my link, I've commented all code and just leave `<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=[MY_API_KEY]&callback=initMap"/>` part on .xml file and when page is loaded the error keeping the same: `Could not get content for....`. I think that I'm missing something on .xml files.

**Comment by JKE-be** [comment]
> Could not get content for..
mean that your external JS is still in your assets ! 

Just need to validate your email to be able to post on forum.
