### ISSUE TITLE
[BUG] Double validation on diferente tag/browser

### ISSUE THREAD

**Issue by JesusZapata** [odoo/odoo#17667]
**Impacted versions:**
- 8.0
- 9.0
- 10.0

**Steps to reproduce:**
Go to one stock movement and duplicated the tag on the navigator. 
In the firts tab we will validate the stock movement, and the another tab you can re-validate the same stock movement

**Current behavior:**
Double validation of the same stock movement

**Expected behavior:**
Block the possibility of validating the same stock movement even if it is open in different tab

This behavior is equal in the rest of the document inside odoo

**Comment by Yenthe666** [comment]
Hi @JesusZapata,

Thank you for your report.
Are you talking about multiple browser tabs? As in you have browser tab 1 with stock movement 1 and browser tab 2 with stock movement 2?

**Comment by JesusZapata** [comment]
Hi @Yenthe666 
We have this scenario:

Two people have the same stock movement in different browser, and the first person validated the stock movement, then the second person (have the button validate enable) press the button validate.

The action of the second person causes a bad inventory move 

This example serves to understand the case?

**Comment by Yenthe666** [comment]
Hi @JesusZapata,

Yes it does, thank you for the additional information.
@mart-e I don't believe this is something on the roadmap to handle/fix, is it?

Regards,
Yenthe

**Comment by JKE-be** [comment]
@sle-odoo 

Probably a check in valid method to add ? 

if state not already in 'done'

**Comment by mart-e** [comment]
The concurrent updates of the same record are currently not supported. We can try to improve it on case by case but this is not something we have plan to support on a global level.

**Comment by JesusZapata** [comment]
@mart-e 
I made on video with this behaviour https://youtu.be/5DaEdImiaB0 
Just for a better explanation
This issue is only related with `stock.picking` the double validation cause a bad movement inventory

I causes a change of status not allowed in `stock.picking` change status from `Done to Draft`

![image](https://user-images.githubusercontent.com/1387970/27302679-11541af0-5506-11e7-83bd-4221202e3a0d.png)

We can work on a specific solution for `stock.picking` ?

**Comment by Yenthe666** [comment]
As Martin said it is not really something we want to include / work on. Please do feel free to make a PR for this case and then it will most likely be accepted. I'm closing this report as everything is answered.
