### ISSUE TITLE
[10.0] searching m2m field results in a error if domain="[('x', '=', y)]"

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#17669]
I have extended crm.lead with a Many2many field with a domain straight in the field declaration. 
```
user_id = fields.Many2one('res.users') # the default crm.lead.user_id
assistant_ids = fields.Many2many('tags.tags', domain="[('assistant_ids', '!=', user_id)]")
```
If a user searches on this field an error with the stacktrace pasted below will be raised. The issue seems to be that the domain term isn't evaluated and is simply left as a string. 

Unless i misunderstand the intent behind a domain defined one a model's field, i would argue that domains defined on a model field, in this context of a user search, should be dropped. Since the domain is passed to the view it defines a *contraint* on what values one can select/store in this many2many relationship. So searching with the domain doesn't make sense unless it to be interpreted as "only records where the assistant is not the user himself". If that indeed is the case then domains defined on a model are ambiguous in their function. 

odoo/osv/expression.py line 978
<pre>
```
            elif field.type == 'many2many':
                ...
                if operator in HIERARCHY_FUNCS:
                    ...
                else:
                    ...
                    if right is not False:
                        if isinstance(right, basestring):
                            op = {'!=': '=', 'not like': 'like', 'not ilike': 'ilike'}.get(operator, operator)
                            domain = field.domain <b># the literal domain string "[('user_id', '!=', user_id)]"</b>
                            if callable(domain):
                                domain = domain(model)
                            <b># domain is not evuluated and passed to name_search as a string</b>
                            res_ids = [x[0] for x in comodel.name_search(right, <b>domain</b> or [], op, limit=None)]
                            if res_ids:
                                operator = 'not in' if operator in NEGATIVE_TERM_OPERATORS else 'in'
```
</pre>

 
Impacted versions: 10.0

Steps to reproduce:
This is somewhat of a fringe use case, but a many2many fields with a constraint defined on the model's field definition can be observed at.

Settings -> Automation -> Automated Actions -> (Advanced Search/Magnifying glass) -> Server Actions -> Search

Current behavior:
```
Odoo throws an error:
Traceback (most recent call last):
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/karlis/odoo/10/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/karlis/odoo/10/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/karlis/odoo/10/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/karlis/odoo/10/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/karlis/odoo/10/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/karlis/odoo/10/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/karlis/odoo/10/odoo/odoo/models.py", line 1932, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/karlis/odoo/10/odoo/odoo/models.py", line 1955, in _read_group_raw
    query = self._where_calc(domain)
  File "/home/karlis/odoo/10/odoo/odoo/models.py", line 4023, in _where_calc
    e = expression.expression(domain, self)
  File "/home/karlis/odoo/10/odoo/odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "/home/karlis/odoo/10/odoo/odoo/osv/expression.py", line 1000, in parse
    res_ids = [x[0] for x in comodel.name_search(right, domain or [], op, limit=None)]
  File "/home/karlis/odoo/10/odoo/odoo/addons/base/res/res_users.py", line 393, in name_search
    users = self.search([('login', '=', name)] + args, limit=limit)
```
Expected behavior:
Odoo performs a search ignoring the domain term in the model's definition.

**Comment by InfernalLV** [comment]
P.S.
I do understand a workaround would be to move the domain to the view definitions. But i find defining a domain in one location to be more powerful and would love to see this fixed.

**Comment by fmdl** [comment]
Remove ""
domain="[('assistant_ids', '!=', user_id)]" -> domain=[('assistant_ids', '!=', user_id)]

**Comment by Yenthe666** [comment]
Hmm, I do agree that you should put this dynamic domain in the XML and not in the Python. Nevertheless, perhaps you have a valid point.
CC @xmo-odoo and @odony

**Comment by odony** [comment]
Model-level domains are meant to be enforced on the server-side too, for correctness. There are cases where an x2m relationship must be filtered for all accesses, even in server-side business case. One example is the "message_ids" field on the mail.thread mixin, where the domain is absolutely required because the comodel table has no regular inverse FK, so you'd end up mixing unrelated records.
Note that you can use a _callable_ domain to make it dynamic on the server-side as well. The official addons have lots of example of model-level field domains defined with lambdas.
Admittedly, this could be better documented in the official doc - PRs welcome ;-)

And indeed, if you only want to filter on the view side, you might want to define the domain in your views only.
