### ISSUE TITLE
l10n_fr_certification : Only the last line of the account.move is used to compute hash

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#17671]
Impacted versions:
9+

**Context:**
l10n_fr_certification is a module that ensures inaterability of accounting datas, once entries are posted. it is based on a hash of the datas present of account.move and account.move.line. the hash is stored, so if data are corrupted (by UI or by SQL request, the computed hash should change, to indicate that the data has been corrupted.

**Steps to reproduce:**

* Create an entry with 3 lines.
![image](https://user-images.githubusercontent.com/3407482/27238629-f8fca6d2-52cd-11e7-90db-f0e5724e0a3e.png)
* post the entry.
* alter the database, changing value of the two first lines. (for exemple, credit / debit values)
![image](https://user-images.githubusercontent.com/3407482/27238732-4ce7f7e2-52ce-11e7-8f38-27f330ec1f92.png)

**Current behavior:**
* The computed hash did not changed.

**Expected behavior:**
* The computed hash should change.

**Solution:**
* Change code in the link below, including all move.line datas.

CC : @qdp-odoo 

Réf : https://github.com/odoo/odoo/pull/16935/files#r122426669

kind regards.

**Comment by fclementic2c** [comment]
good catch @legalsylvain

**Comment by legalsylvain** [comment]
Hi @qdp-odoo any news for this bug ?

kind regards.

**Comment by legalsylvain** [comment]
Fixed by https://github.com/odoo/odoo/pull/18175.

thanks.
