### ISSUE TITLE
sass-14 does not support exec_workflow

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#17680]
The Odoo API documentation says to use the `exec_workflow` method in order to execute methods on a particular instance of a model. I was attempting to do this and kept getting an error that `exec_workflow` is not an available method.

I can see in the code for sass-14 that this method is not listed:

https://github.com/odoo/odoo/blob/saas-14/odoo/service/model.py#L33

However, it is listed on the version 10 branch as well as other versions:

https://github.com/odoo/odoo/blob/10.0/odoo/service/model.py#L33

Is this intentionally left out? Is there any way to call a method on a particular model instance if our server is using one of the sass versions?

**Comment by JKE-be** [comment]
Hello,

If you blame this line, you can see that it is not a bug. (https://github.com/odoo/odoo/commit/98cb4719dbe90dbe980be4ad98f22fe155c2dae1)
Workflow has been dropped.

Best regards

**Comment by flyingL123** [comment]
Then what is the appropriate way to call a method on a specific instance of a model via the XML RPC api? For instance, if I want to call the `run` method on server action with ID 123, how do I do that?

**Comment by JKE-be** [comment]
`models.execute_kw(db, uid, password, 'model', 'method', [<params>], {<context>})`

should work... 

More infos here: https://www.odoo.com/documentation/10.0/api_integration.html

This tracker is for issue in Odoo only, if you need help please uses forum.odoo.com
