### ISSUE TITLE
Mail template error

### ISSUE THREAD

**Issue by aliya994** [odoo/odoo#176830]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

I found an error while using the email template. In the content, I wanted to wrap the line in the first line, but no matter how I tried, I couldn't achieve it

**Comment by johnny-longneck** [comment]
You did not write any information how someone (not you) can reproduce the issue.
