### ISSUE TITLE
[10.0][9.0][8.0][BUG] Problem with mrp_byproduct and traceability of lots/serial numbers

### ISSUE THREAD

**Issue by AntMoreno** [odoo/odoo#17702]
Impacted versions: v10, v9, v8

Steps to reproduce:

1.- Install mrp_byproduct by enabling "Produce several products from one manufacturing order" under Settings -> Manufacturing
2.- Enable "Track lots or serial numbers" under Settings --> Warehouse
3.- Create three products, A, B and C, and enable "Full Lots Traceability" (for v8) or "Tracking: by lots" (for v9 or v10) for all of them.
4.- Create a BoM for "Product A" that will consume "Product B" and will also produce "Product C" as byproduct.
5.- Launch a Manufacturing Order for "Product A", and set lot "111" as the lot of the produced and byproduct products.
6.- Create a Sale Order for "Product A" and "Product C" and confirm it.
7.- In the Delivery Order force availability
8.- Go to Transfer Wizard and try to select lot "111" both for "Product A" and "Product C"

Current behavior:

You can select lot "111" only for "Product A", but not for "Product C"

Expected behavior:

You should be able to select lot "111" for both products, since they were final products produced in the same Manufacturing Order.

Aditional information:

If you check stock_production_lot the lot "111" was only created for "Product A", although in stock_quant there are quants for both "Product A" and "Product C" pointing to the same lot_id.

In v10 it doesn't even produce the quantity of "Product C", not to say create the lot number asociated to "Product C"

**Comment by AntMoreno** [comment]
Edit to add v9.0, since this happens also in that version.

**Comment by Yenthe666** [comment]
@jco-odoo this one might be for you.

**Comment by scejudo** [comment]
Hi !

Nobody knows about this serious bug ???? 

We're in same situation as Mr Antonio Moreno. We're surprising that Odoo don't comment nothing about this bug. We're working in v9 and as Mr Moreno in v8 we have the same problem with produce several products working with serial numbers. Three impacted versions and Odoo don't "say" nothing ?????

Waiting for response................................................................

**Comment by AntMoreno** [comment]
Hi scejudo

I also find it somehow "strange" that nobody has hit this bug before (there's nothing related on this issues until I opened this one) given that it affects three major versions of a core functionality, and also given the big number of users with them installed, so someone has, for sure, used "Traceability" and "Produce several products from one manufacturing order". 

I think this is a very serious bug, as it affects a functionality that, when implemented, uses to be critical (as in chemical, pharma or food sectors). Adding to this, there's not even a workaround by standard functionality, simply you cannot use the products produced as bypoduct in any warehouse movement. The only way is to install some custom or community addon that allow you to manually select quants in warehouse operations, but then again, you lose a lot of functionaloty, and you cannot use the Transfer Wizard, or the removing strategies as FIFO, FEFO,...

I am guessing this should not be easy to address, but I am also hoping from someone at Odoo or the community to help us with this.

Regards

**Comment by sle-odoo** [comment]
@amoyaux i think you worked on something similar?

**Comment by amoyaux** [comment]
Yep, @AntMoreno by product tracked are not really good integrated.
In v10 at least you have to go through the finished product tab once you used the produce button in order
to set the lot for by product before mark the MO as done.

It's even worse for v11 where you have to go to the finished tab unlock the mo and then edit the lot.

I'm aware of this issue and made a feedback to @lap-odoo . We plan to integrate the by product lot/Sn in the produce wizard directly for future version.

Here is a screenshot for 10.0
![by_product](https://user-images.githubusercontent.com/5512395/31724963-75b956fa-b423-11e7-97a2-9f9328831d98.png)

**Comment by lap-odoo** [comment]
@AntMoreno 

Here is the fix that should be done in V10 : 
- The byproduct will be produced
- If you click on Mark as done on the MO, an error message will be raised because there won't be any serial or lot number defined on the byproduct
- You can then go in the tab final products to encode the lot/serial number and then close the MO

@amoyaux will inform you when it's done

We will improve that feature for the next versions to make it more use-friendly.

**Comment by amoyaux** [comment]
We won't do it in stable since it requires to risky change for a stable version. However you can apply this commit https://github.com/odoo/odoo/pull/20339/commits/1786e48b385e3970b8c2b77bbde115cc11402b7a
if you want to have a quantity done set by the produce wizard
