### ISSUE TITLE
[10.0e] TaxCloud module prevents validation of invoices with negative lines

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#17703]
**Impacted versions:** 10.0e (TaxCloud module)

**Steps to reproduce:**
1. Configure TaxCloud
1. Create a sales order with appropriate fiscal position
1. Click create invoice
1. Choose Down Payment (fixed amount) and specify some fraction of the total
1. Validate the invoice
1. Go back to the sales order and deliver the product
1. Go back to the sales order and click create invoice again
1. Choose Invoiceable lines (deduct down payments)
1. Validate the invoice

**Current behavior:**
The final invoice is created with a line deducting the previously paid down payment. That line has a negative quantity. The invoice cannot be validated because TaxCloud returns an error message "Cart item has a negative qty. Only positive values can be used"

**Expected behavior:**
The invoice should validate without error.

**Video/Screenshot link (optional):**

**File:** "/account_taxcloud/models/account_invoice.py"
**Method:** ```def validate_taxes_on_invoice(self):```
**Line:** ```raise ValidationError(response['error_message'])```
![screenshot_2017-06-14_15 14 34](https://user-images.githubusercontent.com/7604932/27293923-1044096c-54d5-11e7-91fd-d3df3871d1a1.PNG)

TaxCloud does not allow negative quantity.
![screenshot_2017-06-14_14 51 34](https://user-images.githubusercontent.com/7604932/27293762-931417a2-54d4-11e7-9c9c-b4d9999d425f.PNG)

**Comment by taxcloud** [comment]
Our returns API is a forward-looking context, meaning the fact you are calling Returned means all amounts are inferred to be negative relative to the original purchase price. Subtracting 10 dollars would result in raising the original purchase price by 10 dollars.

Word of caution: when using the Returned API, if you supply the ItemPrice (for line item returns), make sure the ItemQty is 1. Conversely, if you provide and ItemQty of 0.2, don't include ItemPrice (sit will be calculated).

Example: $200 original ItemPrice, $50 credit/return. If you Return an item price of $50, with an ItemQty of 0.25 (25% of original purchase), TaxCloud will interpret the API call as 25% of the $50 return, yielding a $12.50 return.

We will be updating the endpoint soon to provide non-blocking information message guidance when the ItemPrice and ItemQty parameters compound. 

Please let us know if you have any other questions, and we will monitor this thread.

-David

**Comment by taxcloud** [comment]
Upon further review of this ticket, I misunderstood the fact pattern. This not a return, but a partial payment. Terms of payment are not tax-related, and should not be sent to TaxCloud.

Reducing the balance due is a ledger balance activity, not a term of sale event (meaning, it does not change the Sales Price of the item(s) being purchased.

I apologize if my previous comment caused and confusion.

Thanks!

**Comment by tivisse** [comment]
@taxcloud Thanks for the feedback.

We won't include negative lines when making calls to taxcloud.

**Comment by tivisse** [comment]
Fixed by https://github.com/odoo/enterprise/commit/0541317c5372bff1934507bb0d3f64bec0620e6d

**Comment by matt454357** [comment]
The above fix doesn't work.  It only checks for negative price.  The down payment invoice line has a positive price, and a negative quantity.

In the current code, how about changing this:
```python
if line.price_unit >= 0.0:
```
To something like this:
```python
if line.price_unit >= 0.0 and line.quantity >= 0.0:
```

**Comment by tivisse** [comment]
Hello @matt454357 

You're right, I missed that when closing this ticket. 

It's working as expected now with the revision https://github.com/odoo/enterprise/commit/4c9d86693738a55bdc1942713485d30130b24a63

Thanks for the feedback.
