### ISSUE TITLE
[10.0 + 10.0e] Landed costs producing negative value quants which later breaks inventory adjustments

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#17707]
The landed costs button_validate() method attempts to create a correction in quant cost that occurs due to currency rounding. However this can lead to a negative cost value being assigned to a stock.quant

The issue affects move lines with a very low price to quantity ratio. ie 1000 x $0.10
Applying a landed cost of $456.70 to this line gives a diff of $0.4567
Having a 2 decimal rounding on the currency makes diff_rounded = $0.46

Now the formula used to determine the cost correction (diff_correct) on the single qty quant (quant_correct)
```python
diff_correct += (line.quantity * diff) - (line.quantity * diff_rounded)
```
This equates to diff_correct = 0.46 + (1000 * 0.4567) - (1000 * 0.46) = -2.84

and then
```python
if quant_correct:
    quant_dict[quant_correct] = quant_correct.cost + diff_correct
for quant, value in quant_dict.items():
    quant.sudo().write({'cost': value})
```
The correction quant's cost becomes $-2.74

If this quant is then in an inventory adjustment, the accounting lines generated violate a constraint on the journal that (credit + debit) >= (0)

I would suggest that the solution is that this line should be changed to only ever round down
```python
diff_rounded = tools.float_round(diff, precision_rounding=curr_rounding)
```
If rounded down in this case, diff_rounded = 0.45  and diff_correct would be calculated as $7.15 and quant.cost = $7.25
A disproportionately large cost for a $0.10 product, but at least it's positive.

Perhaps a rounding_method='DOWN' should be implemented in tools.float_utils ?

**Comment by Yenthe666** [comment]
@qdp-odoo probably for you.

**Comment by qdp-odoo** [comment]
@nim-odoo I think this is related to one of your many fixes

**Comment by nim-odoo** [comment]
@qdp-odoo indeed

**Comment by dhannyz** [comment]
@nim-odoo Any update on this issue?

**Comment by nim-odoo** [comment]
will work on it soon

**Comment by nim-odoo** [comment]
I agree with the issue (obviously), but another solution would be to avoid the error by handling a quant with a negative cost correctly. This is proposed in PR #18210 .

**Comment by dhannyz** [comment]
@nim-odoo I agree, this would handle the issue more generally rather than just the landed cost case.

**Comment by jumshudsultan** [comment]
Hi, is this issue resolved?

**Comment by Yenthe666** [comment]
@jumshudsultan should be done in https://github.com/odoo/odoo/commit/69fa111e95f1697a007aae8be32fe51188789da2
