### ISSUE TITLE
[10.0] Can't change Phone and User in PosTicket

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#17704]
Impacted versions:
10.0

Steps to reproduce:
1. Inherit PosTicket with `t-extend`
2.  Change the whole ticket part-by-part with `t-jquery` (so other modules can inherit the original PosTicket and my changes won't mess with that).

Current behavior:
![image](https://user-images.githubusercontent.com/16890942/27302522-5db9998e-5505-11e7-80ae-b0c5edee1564.png)
Just as this image shows `Phone:` and `User:` can't be inherited and thus can't be changed. I have to change the whole `class="pos-sale-ticket"` just to overwrite this ones.

Expected behavior:
This texts should be inside a node so they can be inherited and changed using `t-jquery`

cc: @jorenvo

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

Thank you for your report.
I actually faced this problem a while ago too.
On a sidenote, which is somewhat related: you also can't use CSS on this report and neither can you do `left-align` for example. CC @vincentadriaensen
