### ISSUE TITLE
summernote.js has an bug

### ISSUE THREAD

**Issue by ksiadz** [odoo/odoo#17719]
Impacted versions: 10.0

Steps to reproduce:

Current behavior: when users try to make two new lines it doesn't work (using soft enter, shit+enter) only strong enter allowed

Expected behavior: creating two new lines

Video/Screenshot link (optional):
![19369139_1363616163707585_33962016_o](https://user-images.githubusercontent.com/20033156/27325300-46d6e494-55a8-11e7-810d-68783ef6bbd3.png)

**Comment by Yenthe666** [comment]
Hi @ksiadz,

Thank you for your report. This is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/29061547-99fdd870-7c1e-11e7-897f-1b304da9a4c7.png)
@nim-odoo I believe you recently made some other patches for corner cases too. Could you look at this one too perhaps?
P.S: Using a few soft enters or ctrl+shifts after having entered text does weird things too.

Regards,
Yenthe

**Comment by nim-odoo** [comment]
@nle-odoo

**Comment by Yenthe666** [comment]
@nle-odoo any update on this one? Also managed to generate another one by doing:
1) Enter
2) Ctrl+enter
3) Ctrl+shift+enter
4) Enter

**Comment by Yenthe666** [comment]
@nle-odoo could you give an update please?

**Comment by Yenthe666** [comment]
@ksiadz I've just tested this again in the latest Odoo 10 and it seems to be fixed! Please update your Odoo source code.
