### ISSUE TITLE
[bug]filter domain multi value ,result is error 

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#17729]
Impacted versions:
9.0,10.0
Steps to reproduce:
I click customer ,after I click vendor ,the result only about vendor
I click vendor, after I click customer ,the result only about customer

Current behavior:
I click customer, the sql code:
`SELECT count(1) FROM "res_partner" WHERE ((("res_partner"."active" = true)  AND  ("res_partner"."customer" = true))  AND  "res_partner"."parent_id" IS NULL )`

i click customer ,after i click vendor ,the sql code：
` SELECT "res_partner".id FROM "res_partner" WHERE (((("res_partner"."active" = true)  AND  (("res_partner"."customer" = true)  OR  "res_partner"."parent_id" IS NULL ))  AND  ("res_partner"."supplier" = true))  AND  "res_partner"."parent_id" IS NULL ) ORDER BY "res_partner"."display_name"   limit 40`

above sql code is error, the position of or is not right  ,the correct code is : 

`  SELECT "res_partner".id FROM "res_partner" WHERE (((("res_partner"."active" = true)  AND  (("res_partner"."customer" = true)  AND  "res_partner"."parent_id" IS NULL ))  OR  ("res_partner"."supplier" = true))  AND  "res_partner"."parent_id" IS NULL ) ORDER BY "res_partner"."display_name"   limit 40`

Expected behavior:

i click customer and vendor ,the result about vendor or customer
Video/Screenshot link (optional):

![Uploading QQ20170621-091237.png…]()

**Comment by llcai** [comment]
big bug

**Comment by GoodERPJeff** [comment]
I confirm this happen in my instance. there are many cases in odoo when user expect both, but get only the last filter result in same separator. 

issue may related to filters that contain more than one fields in the domain expression, the OR operator been insert at wrong place.

**Comment by feitas** [comment]
need fix this ASAP

**Comment by yanggg1133** [comment]
mark

**Comment by Yenthe666** [comment]
@mart-e can you check this?

**Comment by mart-e** [comment]
Hello,

A bit more information will be needed here.  Actually finishing uploading the screenshot would have helped 😉 
Which screen ? Which operation ? I tested on both 9 and 10 and I got an `or`.

**Comment by sum1201** [comment]
i in  partner screen. 

if  filter's domain only have a  condition ,it is correct .
if filter's domain have a more condition, it is not a correct.
e.g in  base/res/res_partner_view.xml  line 332:
` <filter string="Customers" name="customer" domain="[('customer','=',1), ('parent_id', '=', False)]"/>
   <filter string="Vendors" name="supplier" domain="[('supplier','=',1), ('parent_id', '=', False)]"/>`

customer and supplier filter have two condition. 
join two filter's domain is   [('customer','=',1), ('parent_id', '=', False)]  or [('supplier','=',1), ('parent_id', '=', False)]

but in web/static/src/js/framework/pyeval.js  line 850:
`function eval_domains (domains, evaluation_context) {
    evaluation_context = _.extend(pycontext(), evaluation_context || {});
    var result_domain = [];
    _(domains).each(function (domain) {
        if (_.isString(domain)) {
            // wrap raw strings in domain
            domain = { __ref: 'domain', __debug: domain };
        }
        switch(domain.__ref) {
        case 'domain':
            evaluation_context.context = evaluation_context;
            result_domain.push.apply(
                result_domain, py.eval(domain.__debug, wrap_context(evaluation_context)));
            break;
        case 'compound_domain':
            var eval_context = eval_contexts([domain.__eval_context]);
            result_domain.push.apply(
                result_domain, eval_domains(
                    domain.__domains, _.extend(
                        {}, evaluation_context, eval_context)));
            break;
        default:
            result_domain.push.apply(result_domain, domain);
        }
    });
    return result_domain;
}
`

the result is    '|','&',('customer','=',1),('parent_id', '=', False), ('supplier','=',1),('parent_id', '=', False)

it is not correct

**Comment by mart-e** [comment]
Ok thanks for the info. Your code is acutally outdated, already fixed at b2d66d0c1468b9d321d9ffa5782e370e92525a43
Just update your code.

When you report a bug, please make sure to test it on the latest version of Odoo. You can always use the [runbot](http://runbot.odoo.com/) to quickly get an instance with the latest code.
