### ISSUE TITLE
[bug][10.0] Gevent and Longpolling not starting in non-posix environment (resource module not found)

### ISSUE THREAD

**Issue by silviofdez** [odoo/odoo#17726]
Impacted versions:
All versions from 20170505

Steps to reproduce:
If you try to run gevent in a non posix environment, it fails, i.e.
```
python.exe odoo-bin gevent -c odoo-server.conf --max-cron-thread=0
```

Current behavior:
The command fails indicating that:
```
ImportError: No module named resource
```
Expected behavior:
Just start the service. 

Detailed description:
It comes from commit 831a2a00e35bde8e47a1678b3156148381414392
It assumes that `resource` module is always loaded, but it is only available in posix environments.
In this commit the following lines have been added (369 and on):
```
+        # Set process memory limit as an extra safeguard
 +        _, hard = resource.getrlimit(resource.RLIMIT_AS)
 +        resource.setrlimit(resource.RLIMIT_AS, (config['limit_memory_hard'], hard))
 +
```
In lines 23 and so there are:
```
if os.name == 'posix':
    # Unix only for workers
    import fcntl
    import resource
    import psutil
else:
    # Windows shim
    signal.SIGHUP = -1
```

I think it could be resolved by adding the same `if` before each `resource` invocation.

**Comment by aduijs** [comment]
I got the same problem on Centos7 where i run Odoo as wsgi.
I am trying to start odoo through the CLI with the longpolling port defined, but it never starts a listener.

Is the fix you are proposing also fixing this?

**Comment by silviofdez** [comment]
@aduijs I don't think so. Could you give me the steps in order to reproduce the problem on Centos7, as well as the error. 

Could be possible that you have any missing module?

**Comment by aduijs** [comment]
@silviofdez 
the command i used:
 ./odoo-bin --addons-path=/myaddons/addons --logfile=/mylog/odoo10-longpolling.log --database=v10odoo --db_port=28817 --longpolling-port=26302

There is nothing listening on that port as shown below. (and neither is it listening on the ports specified in the configfile  .openerp_serverrc)

[root@wf-50-116-28-65 ~]# netstat -anp |grep 26302
[root@wf-50-116-28-65 ~]#

on stackoverflow i found the folowing
https://stackoverflow.com/questions/30161575/odoo-on-debian-longpolling-port-is-never-used-opened#30574672
but installing the missing psycogreen didnt solve it.

I also tried starting odoo-bin with gevent, but that didnt help either.
 ./odoo-bin gevent --addons-path=/myaddons/addons --logfile=/mylog/odoo10-longpolling.log --database=v10odoo --db_port=28817 --longpolling-port=26302

**Comment by silviofdez** [comment]
PR resent for Odoo 11 branch. Other PR closes

All checks passed
