### ISSUE TITLE
website_sale: Strikethrough pricing not showing in v10

### ISSUE THREAD

**Issue by obulkin** [odoo/odoo#17727]
**Impacted versions:** 10.0

**Steps to reproduce:** Here are the steps for reproducing this issue in an Odoo v10 Runbot instance with all modules installed:
1. Go to ``Sales >> Settings``
2. Under ``Pricing``, select advanced pricing and apply the changes
3. Go to ``Website >> Shop``
4. Search for ``ipad``
5. Open the product page for the ``iPad Retina Display`` product
6. The ``website_public_price`` of this product is 750, and its ``website_price`` is 600, so the page should show the higher value in red, with a strikethrough. Instead, it remains hidden.

**Current behavior:** The ``website_public_price``of the product is not visible on the page.

**Expected behavior:** The ``website_public_price``of the product should be shown in red, with a strikethrough. 

As far as I can tell, this issue stems from [use of the wrong selector](https://github.com/odoo/odoo/blob/10.0/addons/website_sale/static/src/js/website_sale.js#L320) in the ``website_sale`` JS. The ``oe_optional`` class is only present on [one of the spans](https://github.com/odoo/odoo/blob/10.0/addons/website_sale_options/views/website_sale_options_templates.xml#L104) introduced by the ``website_sale_options`` module, whereas the class used in the [base template](https://github.com/odoo/odoo/blob/10.0/addons/website_sale/views/templates.xml#L588) and elsewhere is ``oe_default_price``.

**Comment by Yenthe666** [comment]
@JKE-be could you give feedback? I believe this is indeed a bug?

**Comment by JKE-be** [comment]
Have you checked that the pricelist are with option 'show visible discount' and not 'inclused in price' ?

**Comment by obulkin** [comment]
Ah. I could swear I had this option selected, but I guess I didn't. Everything seems to be working correctly now. Thanks for the reply.
