### ISSUE TITLE
[10.0][Ent]Db Filter and report.url make followup report don't use the css [ISSUE 748346]

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#17725]
Impacted versions:
v10.0 ent

Steps to reproduce:
Start an instance with db filter really simple with the name of a db for example.
Set up report.url

Current behavior:
* Invoice, Sale.order are printing correct PDF
* Account followup don't work correctly

Expected behavior:
* Account follow up work like other reports

**Comment by flotho** [comment]
Hi,
Here is a set of ir.config_parameter to illustrate the issue :
1. Config that works
web.base.url | http://localhost:8069
report.url | http://localhost:8069 or None
web.base.url.freeze | true

2. Config that works (a.b.c.d is the IP adress of the server)
web.base.url | http://a.b.c.d:8069
report.url | http://a.b.c.d:8069 or None
web.base.url.freeze | true

3. Config that fail (http://external-public-domain.com is a public domain mapped behind a reverse proxy. The proxy = True option is used in the conf file)
web.base.url | http://external-public-domain.com
report.url | http://a.b.c.d:8069 or None
web.base.url.freeze | true

In the latest case, the css is not properly loaded and the followup report is uggly. Keep in mind that it has been tested with the latest updates and also on a production server and locally on a dev server.

Thanks for your support.

cc @odony , @sle-odoo is it possible to have a review on this ?

**Comment by rim-odoo** [comment]
https://www.odoo.com/web?debug#id=748346&view_type=form&model=project.issue&action=963&active_id=49&menu_id=4720

**Comment by rim-odoo** [comment]
maybe this https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_followup_report.py#L319
could be coherent with this: https://github.com/odoo/enterprise/blob/10.0/account_reports/models/account_report_context_common.py

**Comment by flotho** [comment]
@rim-odoo , thanks for you analysis.
Do you then consider this as a bug ?

**Comment by nim-odoo** [comment]
Hello,

The following enterprise commit should solve the issue: https://github.com/odoo/enterprise/pull/1186
(it is for v9, but you can apply it in v10). Can you confirm it works for your case?

**Comment by nim-odoo** [comment]
Solved from v10 in https://github.com/odoo/enterprise/commit/75a0dbf53ffa8759d0a717bf253d23c611f39926
