### ISSUE TITLE
File name missing in attachment

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#17749]
Impacted versions:
saas-16, master

Steps to reproduce:
1. Create attachment
2. Add file
3. Save attachment

Current behavior:
File without name
![test odoo 1](https://user-images.githubusercontent.com/17258001/27390806-40973cd2-5670-11e7-86dd-6cc835d2ea23.png)
Expected behavior:
File with name 
![test odoo](https://user-images.githubusercontent.com/17258001/27390662-d4c29c54-566f-11e7-9d90-264ef2b5eff0.png)
Video/Screenshot link (optional):
https://youtu.be/AQV8kvUxVHU

**Comment by ged-odoo** [comment]
this is definitely a bug in the new views.

**Comment by Yenthe666** [comment]
@ged-odoo any update on this?

**Comment by hmo-odoo** [comment]
this issue is fixed at revision: https://github.com/odoo/odoo/commit/378efa14449baeb19a8fb6a810b8db148971c0c1
