### ISSUE TITLE
Extra Move is created and duplicate the stock quants in packet drop

### ISSUE THREAD

**Issue by mrzingo** [odoo/odoo#17747]
Impacted versions: 8

Steps to reproduce:
Try to transfer the picking in a bad connection with packet drop.

Current behavior:
Duplicated stock move lines in the picking (Extra move) is created and doubling the quants transfer to the customer location.
Expected behavior:
Stock moves is transferred to the customer location without any extra moves (duplicates).

Video/Screenshot link (optional):

**Comment by Marnoel** [comment]
I'm facing the same issue, in my case i have duplicated move with huge quants, did you managed to find a solution?
![image](https://user-images.githubusercontent.com/14309209/29065120-013e4bc4-7c23-11e7-92a7-e21f2193726f.png)

**Comment by crsilveira** [comment]
I'm facing the same issue 
![selecao_2561](https://user-images.githubusercontent.com/3135336/30111304-825aceea-92e3-11e7-8900-631ac7fe1667.png)

**Comment by Sanat90** [comment]
Any update on this issue? We have a similar issue where odoo has created additional 'Extra Moves' on a picking document.

**Comment by Yenthe666** [comment]
Hi @mrzingo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by Sanat90** [comment]
This exact issue has happend on Odoo 9 as well. Impacted Versions include Odoo 9 - Community too.

**Comment by Wesamazmy** [comment]
This bug is still in version 10 as well! please any feedback?

**Comment by Yenthe666** [comment]
Hi @Wesamazmy,

Please do create a new bug report for V10 then! We'll try to label and handle it as fast as possible.

**Comment by faisalsi** [comment]
Any fix of this issue ? we are facing it V10 Enterprise, that it creates lot of Quants instead of one, in one case an item got 99,000 qunants for just 22,000 of liters, this is causing lot of slowness i.e. opening screens that involve such items take 15 to 60 minutes literally, and running schedule take 7 to 10 hours with CPU usage of 120%

**Comment by mrzingo** [comment]
> Hi @Wesamazmy,
> 
> Please do create a new bug report for V10 then! We'll try to label and handle it as fast as possible.

Done here >> https://github.com/odoo/odoo/issues/27456
