### ISSUE TITLE
[16.0] module: website_sale

### ISSUE THREAD

**Issue by duchuynguyen93** [odoo/odoo#177531]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

When i use price range in shop ecommerce to filter product
- if no product found -> continue search with price range -> raise error
![odoo_core_error1](https://github.com/user-attachments/assets/6cb8d160-6589-4550-a143-4088bfda5816)
- this error show because in javascript file website_sale.price_range_option, not check class o_wsale_products_grid_table_wrapper existed when add opacity-50 to classList.
![odoo_core_error2](https://github.com/user-attachments/assets/2feae62a-5775-465b-bdef-8834ecd96869)
Please fix this error ASAP!!!

**Comment by duong77476-viindoo** [comment]
You can do a fix for odoo if you really need it "ASAP" or fix in a fork maybe
