### ISSUE TITLE
Can\'t compare DateTime and bool  

### ISSUE THREAD

**Issue by EBII** [odoo/odoo#17752]
Impacted versions: 10.0

Steps to reproduce: import date with xmlrpc

Current behavior:  TypeError: Can't compare DateTime and bool
TypeError: Can't compare DateTime and bool

File "/workspace/parts/odoo/odoo/fields.py", line 774, in convert_to_column
    if value is None or value == False:

Expected behavior: no error 

Video/Screenshot link (optional):

needs to inverse test 
test isinstance before Value==False

    def convert_to_column(self, value, record):
        """ Convert ``value`` from the ``write`` format to the SQL format. """
        print "convert_to_column %s type %s" % (value, type(value))
        if value is None or value == False:
            return None
        if isinstance(value, unicode):
            return value.encode('utf8')
        return str(value)

convert_to_column 2017-05-29 type <type 'str'>
convert_to_column 1980-07-23 type <type 'str'>
convert_to_column image type <type 'unicode'>
convert_to_column 20170327T00:00:00 type <type 'instance'>
TypeError: Can't compare DateTime and bool

**Comment by mart-e** [comment]
Hello,

Thanks for the report but it looks like the issue is with your rpc call, not odoo.
We expect string, not datetime.
