### ISSUE TITLE
The shopping cart redirect user to homepage without finish the process

### ISSUE THREAD

**Issue by johnsh** [odoo/odoo#17762]
Impacted versions: 9.0c

Steps to reproduce: This is the problem, sometimes happend

Current behavior: When i try to make a sale through the website sometimes the shopping cart redirect the users to homepage.

When the var request.session.get('sale_order_id')  is False  the  problem ocurrs but i have some products in the cart.

Expected behavior:  Finish all the sale without problems

Video/Screenshot link (optional):

Thanks

**Comment by mart-e** [comment]
Hello,

Thank you for the report but with this is not enough information to allow us to work on that.
Please let us know if you find more info when it happens.

**Comment by Yenthe666** [comment]
@johnsh could you please provide us with more information?
