### ISSUE TITLE
Price Accuracy fields missing when creating new currency 

### ISSUE THREAD

**Issue by Swerone** [odoo/odoo#17776]
Impacted versions:
**Latest today 10 (please write where i can find the specific version number)**

Steps to reproduce:
****Try to add a new currency**

**Invoicing -> Edit Company Data -> "Activate **here** a new currency before creating a new company. " -> Create**

Current behavior:

****The following fields are invalid:**
**- Symbol****

Expected behavior:
**I guess there should be a symbol field. On this picture from an other guy there seams to be the hold Price Accuracy missing.**  https://cloud.githubusercontent.com/assets/7801740/7424482/ea4bd2e6-efe4-11e4-9a41-6c54aa2d4bae.png

Video/Screenshot link (optional):
https://gyazo.com/15a4ef5e27bcbf239b7c2fa64910e782

**Comment by pandalion98** [comment]
Issue exists on fresh install of Odoo 10. Because of this, I can't add my local currency.

**Comment by pedrobaeza** [comment]
You mustn't create currencies by hand, but enable one of the existing ones (that are not visible by default, as long as you don't remove the default filter), so that's the problem.

Closing as no real issue.
