### ISSUE TITLE
Need a dedicated menus for journal entries locking dates

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#17786]
Impacted versions: 9,10 and master

Steps to reproduce:
install account_accountant module + connect with adviser access rights.

Current behavior:
As an accountant, I want to block journal entries modifications but I do not want to have access to Accounting / configuration / settings 

Expected behavior:
We need dedicated menus for such regular accounting process (one for accountant and one for adviser).
This is a pain for 2 version, it is a error to do this again for v11.
@qdp-odoo 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5735158/27473051-fbf9810e-57fd-11e7-8c33-1c423aaefc9a.png)

**Comment by qdp-odoo** [comment]
it's currently in progress

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/pull/18333

**Comment by qdp-odoo** [comment]
landed in master, for saas-18, at revision https://github.com/odoo/enterprise/commit/68e09e1f4588205efb2f4def3e0f2f619f2d1772

although that we might improve it slightly in a further revision to let non-adviser lock a period by creating a dedicated menu for that (as proposed by Frédéric). Currently, we've added a menuitem under 'Adviser' to set both lock dates without giving access to the settings.
