### ISSUE TITLE
[11.0] CRM doesn't take into account pricelist currency

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#17802]
Impacted versions: v10, v11

Steps to reproduce: 
- Set a currency for your company.
- Set the public pricelist in a differente currency.

Current behavior:
- CRM currency is set as the company's currency, not the pricelist.

Expected behavior:
- Be able to set the currency for the CRM according to a pricelist or directly to the pipeline. This because you may have to make your statements in a currency however you sell in a different one, this is very common in countries with weak currencies and more common if it fluctuates a lot.

**Comment by gustavovalverde** [comment]
And after changing the company currency, it's still showing the old one: 

![image](https://user-images.githubusercontent.com/16890942/27972834-b857b74e-6325-11e7-945c-01ce10aa3f6a.png)

**Comment by gustavovalverde** [comment]
And after changing the company's currency is still showing the old one: 

![image](https://user-images.githubusercontent.com/16890942/27972928-0d084de4-6326-11e7-8d01-d2e4bf157ab4.png)

**Comment by gustavovalverde** [comment]
This seems odd @mart-e

**Comment by edsersolis** [comment]
Could you give this thread a push? @Yenthe666

**Comment by mart-e** [comment]
Could you please give more info on what you configured to show this amount with a currency?

This amount does not mean much as it is the sum of all total of sale orders but it may mix different currencies.

**Comment by mart-e** [comment]
My question was what did you do to display the currency on the kanban? Because it shouldn't as the amount is a mix of different currencies.

However, I agree it would be very nice to do it in the future. We probably need the same `amount_total_company_signed` field as we added [on the invoices](https://github.com/odoo/odoo/blob/d76237e038ac379ae96e2c72848a013731c3de03/addons/account/models/account_invoice.py#L284) on the sale.order (and purchase.order probably)

**Comment by edsersolis** [comment]
We didn't do anything. It just shows when the company's currency is set.

Another plus, related to whole system and not only CRM is that the SUM of Tree Views treat different currencies as the same. 

I know this is more of a logical thing and that it can be solved by grouping, but maybe if we have a another column that shows the amount in the Company's currency it would be a plus. Or better yet have the SUM to show some message like MIXED instead of the SUM to warn that there is a mixture of currencies so the sumatory won't be real.

**Comment by MohsenWaleed** [comment]
@mart-e Do you have any updated regarding this?

**Comment by mart-e** [comment]
Sorry but it was rejected, it was considered too confusing to add more fields.
