### ISSUE TITLE
[bug]filter domain multi condition ,result is error  from #17729

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#17812]
Impacted versions:
9.0,10
Steps to reproduce:

Current behavior:
https://github.com/odoo/odoo/issues/17729
@mart-e 
Are you sure this bug is fixed ?

@Yenthe666 
I test in runbot.odoo.com.
I track function   eval_domains  in pyeval.js:
In partner screen 
**1. I filtered by Customer , eval_domains return result is :**
![qq20170624-163123](https://user-images.githubusercontent.com/5398273/27507082-a7bbbd66-58fa-11e7-8f07-fc48abdac007.png)

![qq20170624-163332](https://user-images.githubusercontent.com/5398273/27507103-e0f87f92-58fa-11e7-8620-a5533f4d173d.png)

**2.I filtered by Vendor ,eval_domains return result is :**
![qq20170624-163626](https://user-images.githubusercontent.com/5398273/27507119-4e17c074-58fb-11e7-89bb-874dab06a1dc.png)
![qq20170624-163730](https://user-images.githubusercontent.com/5398273/27507125-6ef6c9ac-58fb-11e7-8537-53853e4f4c4a.png)

Expected behavior:

**if filter's domain only have a domain condition, it's result is correct .
I filtered by Persons,the result 's  count is 39,
I filtered by Company ,the result's count is 9.
I filtered by Persons Or Company ,the result's count is 46. it is correct.
example:**
![qq20170624-164226](https://user-images.githubusercontent.com/5398273/27507159-205f568c-58fc-11e7-9b29-e43f1c90bb20.png)
![qq20170624-164536](https://user-images.githubusercontent.com/5398273/27507203-c0b6c840-58fc-11e7-88f0-5513d5c5c47c.png)
![qq20170624-164558](https://user-images.githubusercontent.com/5398273/27507204-c4651a6e-58fc-11e7-8b51-ff7f6c6138f2.png)
![qq20170624-164649](https://user-images.githubusercontent.com/5398273/27507206-c6d9f27e-58fc-11e7-954e-4b539becba91.png)

**if filter's domain  only have a more domain condition ,it's result is error.
I filtered by Customer ,the result's count is 10.
I filtered by Vendor ,the result's count  is 5.
I filtered by Customer and Vendor ,the result's count is 12 ,but is not 15.
 example:**
![qq20170624-164059](https://user-images.githubusercontent.com/5398273/27507150-ed0f863a-58fb-11e7-9320-1fe5933c1118.png)
![qq20170624-164755](https://user-images.githubusercontent.com/5398273/27507212-f55e4578-58fc-11e7-87e4-b93ea1942802.png)
![qq20170624-164810](https://user-images.githubusercontent.com/5398273/27507213-f94817f4-58fc-11e7-95e8-1b09f2928fc0.png)
![qq20170624-164828](https://user-images.githubusercontent.com/5398273/27507215-fc07559a-58fc-11e7-9a42-020a77b8e88f.png)

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
maybe some partner belong to both vendor and customer.

**Comment by mart-e** [comment]
Hello,

Yes, as said @jeffery9 there is some partners that are both (as there is some that are neither). For instance camp2camp or china export.
In your second screenshot, you see that the domain is correct with the `or` operator `|`.

**Comment by mart-e** [comment]
Closing as no bug shown. Please reply on this issue if you disagree instead of opening a new one.
