### ISSUE TITLE
10.0 Sequence without default doesn't update in one2many handle of form view

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#17850]
Impacted versions:
10.0
Steps to reproduce:
This is a bit strange, but if a sequence field is created without a default (e.g. fields.Integer()) then in the resulting formview if you use the handle to reorder the lines that triggers an onchange, the sequence fields are all 0 if you access them.

However if you use any positive integer default (e.g. fields.Integer(default=1), using the handle does update the sequence field of all the one2many items in the view.

Perhaps further to that and worth noting, is that the reason I needed to access the sequence field is that when the onchange is called, the one2many lines are listed by creation order (NewID objects) rather than by _order defined on the model, so in my case (creating a text representation of the one2many), I needed to re-sort.

To be honest, the workaround is so simple I've not bothered looking more into it.  Just logging here in case it comes up elsewhere.

**Comment by pedrobaeza** [comment]
@seb-odoo maybe you know if this is still happening on new handle widget implementation, or it's a known issue.

**Comment by seb-odoo** [comment]
I don't know about this issue, I tried to reproduce it on master but it's working fine even without a default.

I have no idea about 10.0.

**Comment by pedrobaeza** [comment]
Then we should consider this as solved in latest version, but won't fix in previous ones. As it's a very corner case, it's not very critical IMO, but I let @seb-odoo to decide if this should be closed.

**Comment by seb-odoo** [comment]
I'll close it, if someone manage to give me a step by step to reproduce on master, it can be reopened.
