### ISSUE TITLE
Odoo client error

### ISSUE THREAD

**Issue by kevhernandez1** [odoo/odoo#17858]
Impacted versions: Odoo 10.0
just created an odoo app when this JS error appears on every single module i've installed

Video/Screenshot link (optional):

![screenerrorr](https://user-images.githubusercontent.com/29732793/27592972-954ec484-5b1b-11e7-86f2-9333320e9c7f.png)

**Comment by Yenthe666** [comment]
Hi @kevhernandez1,

Thank you for your report.
The Github issue tracker however is for bugs in the official code, it is not the place to ask questions about custom development. Please post this question at http://odoo.com/help (with code!) so people can help you.

Regards,
Yenthe
