### ISSUE TITLE
[10.0] Email field required on res.partner even if no user_ids.

### ISSUE THREAD

**Issue by Fenkiou** [odoo/odoo#17855]
**Impacted versions:**
10.0

**Steps to reproduce:**
Create a new database and install sale module.
Go to customer list view and create two partners:
 - one with portal access.
 - one without portal access.

**Current behavior:**
From the customer list view, open the partner that has portal access. Use the arrow on the top right of the screen to change partner and try to access its invoices for example.

A widget error is shown telling us that `The email is required.`

**Expected behavior:**
The email shouldn't be required and should be able to access partner invoices.

**Video/Screenshot link (optional):**
![screen shot 2017-06-27 at 15 10 44](https://user-images.githubusercontent.com/3717417/27589234-05b85d1e-5b4b-11e7-9306-098396dd1d5a.png)
![screen shot 2017-06-27 at 15 11 00](https://user-images.githubusercontent.com/3717417/27589235-05b91420-5b4b-11e7-9126-20ae2cc3246b.png)
![screen shot 2017-06-27 at 15 12 57](https://user-images.githubusercontent.com/3717417/27589260-20caf8c8-5b4b-11e7-9ac9-776f401d484a.png)

The problem comes from form_common.js where renderElement function is called only when you access the form view for the first time and not when switching record with arrows.

As it's in this function that the view knows if a field is required or not, records shown with arrows keep field required even if they don't meet the condition.

When you click on Edit then Save, the required class disappear as recomputed. But this is not a viable solution.

**Comment by nle-odoo** [comment]
Hi @Fenkiou,


If you wish, you could try the solution I am working on in:
 https://github.com/odoo/odoo/pull/18239/commits/6f62f7eb258

I still needs to do more test but if all is well it could be merged next week.

**Comment by Fenkiou** [comment]
Hi @nle-odoo,

Thanks for the update, I confirm that your fix solve the issue.

But it creates a new issue, when you go on `Applications` page, you get: `TypeError: field.field is undefined`.

**Comment by nle-odoo** [comment]
well spotted, I'm not sure I would have tested that.

I have updated the PR.'

**Comment by Fenkiou** [comment]
@nle-odoo it was just a coincidence, I didn't meant to try all views.

Anyway, thanks for the fix. :)

**Comment by Fenkiou** [comment]
@nle-odoo, any news on this ? I didn't test your last changes though.

**Comment by nle-odoo** [comment]
Hi @Fenkiou 

The last version from today (https://github.com/odoo/odoo/pull/18815/commits/23de379402a6) seems good to me, it has also been approved once. I will probably be able to merge it beginning next week.

**Comment by Fenkiou** [comment]
@nle-odoo That's great, thanks!

**Comment by nle-odoo** [comment]
it is merged in 10.0 with https://github.com/odoo/odoo/commit/6252c210

**Comment by Fenkiou** [comment]
Thanks @nle-odoo, just tried it and it works.
