### ISSUE TITLE
Autoregistered website user can't access to the shop ( "Forbidden" )

### ISSUE THREAD

**Issue by antoniocanovas** [odoo/odoo#1786]
Every web user can access to the shop and buy products, 
But if you register as a "autoregister web user":
- You can access the portal services
- You can't see the shop:  
  403: Forbidden
  The page you were looking for could not be authorized.

When the user press logout, he can see the shop again.

**Comment by franscronje** [comment]
I'm testing the latest ODOO 8.0 branch and this is still an issue. "Autoregistered website user can't access to the shop".  I have set everything as said above and it makes no difference.  Only if I set the "Template User" access to a "User" under Setting>Users>Users>Human Resources, can I then see the SHOP.  WTF must be done to fix this!

**Comment by CoderParamita** [comment]
These are the following steps I have done already but still getting this 403 Forbidden Error in Odoo community version. In the general settings 1)Checked "Allow external users to sign up" and select Template User for "Template user for new users created through signup" 2)Checked "Activate the customer portal" 3)For the Template User checked as "public" There is another button in Product module and Also in User module which is called "Published on Website" I have already clicked as published. But Still getting this 403 forbidden error.Please help what else I have to do?

**Comment by M5soluciones** [comment]
Dear:

I will explain:

1) go setting -> users
2) erase search default filter , use advance search and select Active is false, then push apply, then it will show Template User
3) edit template user, check boxes public and portal access
4) save user
5) logout
6) shop already is shown for guest customers

thank you and good luck !!

Marcelo Magnatera

**Comment by Yenthe666** [comment]
Hi @antoniocanovas,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
