### ISSUE TITLE
[10.0] 500 internal server error wher portal user logging in after portal access cancellation

### ISSUE THREAD

**Issue by m3dbedb** [odoo/odoo#17879]
Impacted versions: 10.0-20170228 

Steps to reproduce:Grant access to customer, log in as customer, remove access, log in as customer again

Current behavior: error uppears until access is denied

Expected behavior: user have to be informed his account is disabled

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @m3dbedb,

Thank you for your report.
I can confirm that this is a bug, there should be some nice form of dialog. The result on the latest Odoo 10:
![image](https://user-images.githubusercontent.com/6352350/27632776-118c5110-5bfd-11e7-91bd-751c83e5e17d.png)
@JKE-be this might be for you. 😉

Regards,
Yenthe

**Comment by JKE-be** [comment]
@Yenthe666 
what do you call 'remove access' ?

**Comment by Yenthe666** [comment]
@JKE-be easiest to reproduce is to open the user (under settings > user) and check off the option 'Portal'

**Comment by JKE-be** [comment]
why do you want to remove the portal access... if you want disable the user, you can unable at the top right to toogle the active.

**Comment by Yenthe666** [comment]
Hi @JKE-be,

In my opinion it is not really that the message is unclear.. but it triggers a 500: internal server error.
If this warning would be shown on login or right after logging in on a webpage it would be fine. It is just the 500 internal that is not user friendly.

**Comment by JKE-be** [comment]
if you disable the user instead of removing all rights... you will be not able to connect and so you will have a proper message: 'User and password don't match'... or something similar instead of a internal error.

There are 3 main roles:
   public
   portal
   employee

If you are not in one of this 3 case, you will have a lot of traceback.

**Comment by Yenthe666** [comment]
@JKE-be well I don't entirely agree on this. Okay this will throw errors and yes it is not the 'desired' behaviour or the conventional way. However, the fact is, that there is an option to uncheck this and don't get any warnings. The user will get troubles while the one that disables this wouldn't even notice it.
We should atleast pop-up a warning or something somewhere along the way?

**Comment by JKE-be** [comment]
IMHO, if you are not in 'technical' you don't have it... So you are supposed to know what you do... 

And if the purpose is to disable a user, that seems logic that the best manner to do is to click on "Disable'.

When you want to archive a lead, you click on archive and don't add an access rule to you user to don't see it again... even if the insterface allow to do it.

**Comment by mart-e** [comment]
I agree with Jeremy. Traceback is never good but you are going in the technical zone, that is the danger zone ! If you misconfigure something, your Odoo can just stop working correctly.

Maybe we should have a message like on firefox ;-)

![screenshot from 2017-06-28 15-39-19](https://user-images.githubusercontent.com/564822/27639895-fdc6190c-5c17-11e7-8ecf-222e8ac7c98d.png)

Regarding the change itself, it is a possible improvement on the user configuration but not a fix.

**Comment by Yenthe666** [comment]
Hmm something like this woud be great. 😆 
Okay @mart-e and @JKE-be let us just label this wishlist for now then? Is that okay for everybody?
