### ISSUE TITLE
6.0 poor performance in account_move_line.unlik

### ISSUE THREAD

**Issue by juanvmarquezl** [odoo/odoo#1788]
OpenERP 6.0.4 + Postgres 8.4 + Ubuntu 10.04

I have a large invoice, it creates an account move with 257 lines, when I try to cancel this invoice the server take a very long time to cancel the invoice + 30 min and the transaction fails (timeout?).
I found a fix in addons 6.1, I create a fork and make a backport with that fix. When be ready, I send the merge proposal.

I hope that this helps.

Thanks.

**Comment by Yenthe666** [comment]
Hi @juanvmarquezl,

Thank you for your report.
Odoo 6.0 (and 7.0) are no longer officially supported. If you can reproduce these issues on a V8, V9 or V10 you're free to create a new report and we'll look into it as soon as we can.
P.S: Sorry for the late feedback.

Regards,
Yenthe
