### ISSUE TITLE
[10.0] Generated empty PDF file

### ISSUE THREAD

**Issue by Germano0** [odoo/odoo#17897]
I opened this new bugreport since older one has been marked as closed despite new feedbacks on CentOS https://github.com/odoo/odoo/issues/364
Impacted versions:
10.0

If you try to generate a PDF file with for example a bill, you will get an empty file (0 byte)
Additional infos
wkhtmltopdf-0.12.1-1.el7.x86_64

**Comment by sylwek845** [comment]
Hi, 

can you try different version of wkhtmltopdf 

[https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.2.4/](url)

**Comment by Germano0** [comment]
Same result with an even higher release:
wkhtmltopdf-0.12.4-1.el7 from CentOS epel-testing repository https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-b72ec227e7

**Comment by Yenthe666** [comment]
@sylwek845 Wkhtmltopdf 0.12.4 is not an officially supported version by Odoo.
@Germano0 do you get this on any report you try to print? There are no error codes or any errors logged in the logfiles?

**Comment by Germano0** [comment]
@Yenthe666  Which log_level should I use among ‘debug_rpc_answer’, ‘debug_rpc’, ‘debug’, ‘debug_sql’, ‘info’, ‘warn’, ‘error’, ‘critical’ ?

**Comment by Yenthe666** [comment]
Hi @Germano0,

This really depends on how much you want to log. Usually in production this is `error` or `critical`.
It is probably good to check the logfile from wkhtmltopdf too.

**Comment by eyonatan** [comment]
Hi @Germano0,

I was having the exact same problem on CentOS  7, x86_64, Odoo 10, . I was able to fix it by upgrading wkhtmltopdf to the latest version found here (https://wkhtmltopdf.org/downloads.html).  I understand per @Yenthe666 , this version is not supported.  Instructions detailed here helped on upgrading: http://datos.asia:8069/blog/odoo-tips-3/post/blank-pdf-reports-generated-6

**Comment by GasparYYC** [comment]
I found out that the packaged versions do not work (even the most recent)
The solution is to download and install the packaged version then do a manual install of a different version so you get the libraries from the packaged version and use the executables **only** from version 12.4
After this no more empty reports on CentOS

##Install the packaged version via:
yum install wkhtmltopdf

##Note Ubuntu works fine. This is for CentOS
cd ~
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
cd /root/wkhtmltox/bin
cp  /usr/bin/wkhtmltopdf /usr/bin/wkhtmltopdf.Original
cp  /usr/bin/wkhtmltoimage /usr/bin/wkhtmltoimage.Original
cp wkhtmltopdf   /usr/bin
cp wkhtmltoimage /usr/bin
systemctl restart odoo

**Comment by go4site** [comment]
@GasparYYC 
You are a real Hero!
I was looking for it for some days. Followed your instructions and yep. It is working now.
Thanks!

**Comment by Yenthe666** [comment]
Hmm sorry to hear it was that complex.. @sle-odoo although it is an external package this might be worth to have a look at or report?

**Comment by danger89** [comment]
wkhtmltopdf 0.13.0-alpha-7b36694
OS: Debian Jessie

Actually it's working fine when I execute the commands on the command-line. So /usr/bin/wkhtmltopdf is just working fine, using this bash wrapper. **HOWEVER**.

As @TeroK [wrote here](https://github.com/odoo/odoo/issues/364#issuecomment-251347550) I pipe the stdout & err to a file. And when Odoo executes this script via xvfb ("Virtual" X), I get to stdout:
_**QThread::start: Thread creation error: Resource temporarily unavailable**_

So, somehow it can create a thread on my terminal. But not when this script is triggered via the web interface..!?

What do I wrong? PDF files keep zero size:
```
/tmp# file report.tmp.Vlf4r9.pdf
report.tmp.Vlf4r9.pdf: empty
```

The wkhtmltopdf process is not stopping, meaning I get a lot of open zombie processes. And last but not least, the web-interface shows an endless loading animation.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions and use preferred OSes. Check them on https://www.odoo.com/documentation/10.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by gdgellatly** [comment]
That's great that /usr/bin is fine. Now all you need to do is link it in
/usr/local/bin .
