### ISSUE TITLE
[master] l10n_mx_reports: Now with the new hierarchy if broken for CoA

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#17927]
Impacted versions:

[master]

Steps to reproduce:

Print the CoA report of l10n_mx.

Current behavior:

Missing tree structure

Expected behavior:

Proper tree structure

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/338634/27722128-fd7b4bf2-5d2a-11e7-82fd-0fac6f03c2e9.png)

**Technical Solution: **

- Using the new tree structure with grouping try to implement such report avoiding only tags as before.

**Comment by nhomar** [comment]
@luistorresm Can you give a try to this please.

**Comment by pedrobaeza** [comment]
This corresponds to an enterprise module, so it should be reported through their OPW system, and this belongs to community version.
