### ISSUE TITLE
Changing the hours of an entry in Timesheet Activities (HR) does not change the corresponding activity line of the associated task.

### ISSUE THREAD

**Issue by hokkaido** [odoo/odoo#1792]
This concerns projects with subtasks.

While updating the amount of "hours worked" on the task is immediately reflected in the corresponding Timesheet Activities (HR menu), the opposite is not true. If we change the amount of hours worked through Timesheet Activities, the amount of hours recorded on the task is not changed.

We can easily see this that this is the case inside `project_timesheet/project_timesheet.py`, since the overriden `class account_analytic_line` inside it does not handle this case.

**Comment by Yenthe666** [comment]
Hi @hokkaido,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
