### ISSUE TITLE
[10.0]  fields.Html doesn't track when track_visibility is onchange

### ISSUE THREAD

**Issue by lescobarvx** [odoo/odoo#17923]
Impacted versions:
**10.0**

Steps to reproduce:
**1. Added field in model**
![seleccion_218](https://user-images.githubusercontent.com/16093067/27702180-46f5e954-5cd1-11e7-8ff6-91f95076cc06.png)

**1. Added field in view**
![seleccion_217](https://user-images.githubusercontent.com/16093067/27701816-18e791e4-5cd0-11e7-8f6d-3bbb7a90e40c.png)

Current behavior:
**When I modify the field, the track is not made.**

Expected behavior:
**When I modify the field, the track must be made.**

PS:
In the line https://github.com/odoo/odoo/blob/10.0/addons/mail/models/mail_tracking_value.py#L39 of module `create_tracking_values()` is missing the field html.

**Comment by Yenthe666** [comment]
Hi @lescobarvx,

Thank you for your report.
I've made a PR on which some people from Odoo gave feedback, you can find it here: https://github.com/odoo/odoo/pull/17943

Regards,
Yenthe
