### ISSUE TITLE
[master] Account Group Allow name_get by code - missing feature

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#17926]
Impacted versions:
master

Steps to reproduce:
On the video

Current behavior:
You have to write the name of the group only

Expected behavior:
Either Writing the code or the name of an Account Group fetch the record 

Video/Screenshot link (optional):
https://drive.google.com/file/d/0B1w9gokcJL9hVWpaMTdGQ3RlLTQ/view

**Comment by qdp-odoo** [comment]
geez guys, you're fast
