### ISSUE TITLE
[8.0] "Could not serialize access due to concurrent update" when multiple workers loading registry

### ISSUE THREAD

**Issue by moderatemisbehaviour** [odoo/odoo#17938]
Impacted versions:
8.0, produced on [this commit](https://github.com/bjss/odoo/commit/dcfd94cbf526e0168f51087259434cedb2c4c061).

Steps to reproduce:
1. Set workers to `5` in server config.
2. Start server.
3. Send multiple HTTP requests to the login page in quick succession.

Current behavior:
Each subsequent request is directed to one of the 5 workers which each start loading their own registry.
The workers block each other because they are all trying to access the same row to flag modules as _installed_. This results in the registry load failing for the worker, and it starting registry load again next time it does a _signalling check_.

```
< 2017-06-30 10:27:07.667 UTC >ERROR:  could not serialize access due to concurrent update
< 2017-06-30 10:27:07.667 UTC >STATEMENT:  UPDATE "ir_module_module" SET "state"='installed',"latest_version"='8.0.0.1
```

Under light load the situation eventually resolves itself. Under heavy load the workers can get into an infinite loop of loading registries.

Expected behavior:
I'm not sure what the expected behaviour should be, I'm wondering if its somehow my application code that's causing this or if its a known issue.

If it's a known issue I would suggest that registry loads are properly serialised or that the PostgreSQL error is caught and the registry loading is retried automatically.

**Comment by odony** [comment]
The workers should all load the registry separately without touching the module rows. The error you see will only occur if the server was started with command-line parameters or config parameters asking to install/update modules (i.e. `-u <module>` or `-u <module>` or equivalent config params).

This is an error, those parameters are meant for one-shot operations, typically used during development or in combination with `--stop-after-init`, so the server will stop immediately after the install/update.
This is not compatible with `--workers`, which is used for running a production service.
The documentation might need to be improved on this area.

Also you should verify that all your modules are in state "Uninstalled" or "Installed" in the database. There should be no leftover "to install" or "to remove" modules during normal production operation, as they indicate failed/incomplete operations.

**Comment by moderatemisbehaviour** [comment]
I was just coming back to report that was my problem but you beat me to it! I was using an `init.d` script to start and stop Odoo and I had no idea that for some strange reason it had the `-u` flag set in it for one of our modules. Silly mistake, sorry to waste your time with this one.

Thanks for the in-depth response though, it helps clarify things for me, greatly appreciated ❤️
