### ISSUE TITLE
Ubuntu 17.04 - Installation fail due to python-pypdf is uninstallable

### ISSUE THREAD

**Issue by kurtjcu** [odoo/odoo#17948]
Impacted versions: 
Ubuntu Server 17.04
Odoo - nightly

Steps to reproduce:
apt-get install odoo on fresh install of Ubuntu Server 17.04

Current behavior:
Odoo fails to install as it has unmet depencencies:
odoo: depends python-pypdf but it is not installable.
E: Unable to correct problems, you have broken packages.

Expected behavior:
Odoo should install, Should Odoo be using python-pypdf2 ??

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11880007/27754531-4da81674-5e2e-11e7-9f67-00f5abc14046.png)

**Comment by odony** [comment]
Indeed, this is the same issue (for Ubuntu) as #17002 for Debian, so let's close this one and track it there. I've updated the title of #17002 to make it more discoverable.
