### ISSUE TITLE
Fails to install on Debian 9 due to missing python-pypdf

### ISSUE THREAD

**Issue by grubshka** [odoo/odoo#17944]
Impacted versions:
10

Steps to reproduce:
aptitude install odoo

Current behavior:
 odoo : Dépend: python-pypdf which is a virtual package and is not provided by any available package

Expected behavior:
Installs odoo

**Comment by Yenthe666** [comment]
@sle-odoo looks like one for you?

**Comment by odony** [comment]
Duplicate of #17002, so closing it ;-)

**Comment by Yenthe666** [comment]
Woops I've missed that, although I've responded on both.. Sorry! ;-)

**Comment by zeroheure** [comment]
It is very easy to fix the problem by using a fake python-pypdf package. Then install pypdf from pip.
See the complete tutorial on my blog :
http://zeroheure.info/how-to-install-odoo-on-latest-debian-ubuntu-without-python-pypdf-dependency/

**Comment by kholioeg** [comment]
Another workaround is to do the following:

`apt-get install python-pypdf2`

`dpkg --ignore-depends=python-pypdf -i odoo_*`
