### ISSUE TITLE
Action button in wizard List view is permanently disabled after one press

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#17945]
Impacted versions: 9.0, 10.0

Steps to reproduce: Add an action button to a list view that is used in a wizard. Clicking the button causes Odoo code to add an attribute `disabled="disabled"` to the button. 

Current behavior: Without closing the wizard by returning `{type:'ir_actions_act_window_close'}` from the action there is no way to remove the disabled attribute from the button, so the button becomes permanently disabled. If `{type:'ir_actions_act_window_close'}` is returned from the action then the wizard is closed. 

This issue has been in Odoo since at least version 7.0. Extensive analysis of the code that causes the problem can be found in issue https://github.com/odoo/odoo/issues/9551 originally submitted in 2015

Expected behavior: There should be some means of either preventing disabling of the button or having the action re-enable it. Example use case is a button to show a quick preview of a records in the "Search more..." listing of a wizard with a many2one selection field. In that case using the standard Open link loses the state of the "Search more..." window thus seriously inconveniencing the user. An alternative solution would be to provide a means to return to the exact "Search more..." dialog state so that the user's search is not lost.

Video/Screenshot link (optional):

**Comment by taifu** [comment]
A problem living since version 7.0 is a shame :-(

**Comment by elgow** [comment]
@odony @Yenthe666 I should point out that this issue adds insult to the injury presented by the Odoo `ilike` based text search from https://github.com/odoo/odoo/issues/19208. The effect of this issue is to prevent users from having decent ability to preview the results that they get from a search in a wizard. If they open the record directly from list of results then it closes the wizard and they need to re-do their search. This is extremely aggravating and it's made worse by forcing them to use the `ilike` search all over again.

The solution seems to be to present a button for record preview in the wizard view rows. That's a bit lame, but it would suffice if the button were not made one-time-only by this problem. I find that users are understandably puzzled when told that they can preview their search results, but only once. 

Note  that this issue should not fall foul of the stable policy because it's not looking for a new feature. This is a bug. It's been flagged since Odoo version 7. It was claimed to have been fixed in 2012, but it either was not or it was re-broken. The combination of sub-standard search and the inability to effectively use the search results is bad.

**Comment by elgow** [comment]
This is fixed in 11.0. Thanks.
