### ISSUE TITLE
Cess in India GST

### ISSUE THREAD

**Issue by muralikrishnareddy** [odoo/odoo#17974]
Impacted versions: 9.0, 10.0

Steps to reproduce: Check the Taxes of INDIA GST, not found any option to configure Cess

Current behavior: CESS Configuration for the INDIA GST not available

Expected behavior: In TAXes, need to able to configure CESS % with amounts (Ex : 5% + Rs.1591 per
thousand, 12.5% or Rs. 4,006 per thousand whichever is higher)

Video/Screenshot link (optional):

**Comment by mga-odoo** [comment]
Hello muralikrishnareddy,

first, thanks for the notice about the GST and CESS in Odoo, by the way I check and both of your case are working with the standard Odoo configuration, however i am agree that for the endusers it may not be usable.

**Case 1: 5% + Rs.1591 per thousand, 12.5%** 

Look at how the tax configured, 5% + fixed per pcs. 

![case001](https://user-images.githubusercontent.com/7595796/28200855-ef5a5506-688b-11e7-8f94-02bd0d9dc17a.png)

Look at the invoice, how it will be looked like
![case001-invoice](https://user-images.githubusercontent.com/7595796/28200935-4bc00598-688c-11e7-9df1-6ad57530739c.png)

**Case 2: Higher from 12.5% or Rs. 4,006 per thousand** 

This is little bit tricky, you have to use the python code to compute the tax, make sure that you have installed the module called "Define Taxes as Python Code", look at the below image how it is configured

![case002](https://user-images.githubusercontent.com/7595796/28201023-c0f1ea2a-688c-11e7-9fb6-c31c1530e9c6.png)

Look at the invoice 
![case002-invoice](https://user-images.githubusercontent.com/7595796/28201099-11140ea2-688d-11e7-9b69-5718f171592d.png)

Let me know this can solve your configuration issue with the GST and CESS in Odoo.

**Comment by mga-odoo** [comment]
I think GST Cess listed https://www.indiafilings.com/learn/gst-cess/ can be configured within Odoo without any further development.

**Comment by Yenthe666** [comment]
@qdp-odoo can you verify / confirm this? 😄

**Comment by muralikrishnareddy** [comment]
@mga-odoo Hi Mantavya Gajjar,

Thanks for your reply with samples. I hope your solution works perfectly for me.

**Comment by qdp-odoo** [comment]
I've no knowledge at all of the indian taxes, but I suppose Mantavya is right. 

Let's close this bug report, and assume @muralikrishnareddy will reopen it if it's not 100% working as expected.

Thanks

**Comment by muralikrishnareddy** [comment]
@mga-odoo Is there any Idea about developing GSTR1 formats to upload bulk invoices to the GST system for at least Enterprise Editi
[GSTR1_Excel_Workbook_Template-V1.0.xlsx](https://github.com/odoo/odoo/files/1152159/GSTR1_Excel_Workbook_Template-V1.0.xlsx)
on ?
