### ISSUE TITLE
User is not notified when receives new mail which create a new thread.

### ISSUE THREAD

**Issue by csrocha** [odoo/odoo#1797]
User is not notified when receives new mail which create a new thread.

Using exim4 as SMTP server, routing the mail to odoo using  ./addons/mail/static/scripts/openerp_mailgate.py

**_Impacted versions:**_
- master
- v8.0

**_Steps to reproduce:**_
1. Send a mail to a normal user.
2. Login as this user.
3. Check for new messages.

**_Current behavior:**_
- No new message. The message is set as readed.

**_Expected behavior:**_
- New message.

**Comment by Yenthe666** [comment]
Hi @csrocha,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
