### ISSUE TITLE
[master] sale: can't extend combo configurator controller

### ISSUE THREAD

**Issue by Levi-Bensley** [odoo/odoo#179816]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [ ] 17.0
- [X] Other (specify)

### Steps to Reproduce

- Import controller in file
`from odoo.addons.sale.controllers.combo_configurator import SaleComboConfiguratorController`
- Create Class inheriting original controller
`Class ComboConfigExt(SaleComboConfiguratorController):`
- Overwrite a function and add logger
```
@route()
def sale_combo_configurator_get_data(
    self,
    product_tmpl_id,
    quantity,
    date,
    currency_id=None,
    company_id=None,
    pricelist_id=None,
    selected_combo_items=None,
):
    _logger.info('test')
    return super().sale_combo_configurator_get_data(**kwargs)
```

**Outcome:**
- Logger doesn't output and it just uses the base function

**Workaround:**
The only solution to this that I have found is extending from website_sale WebsiteSaleComboConfiguratorController but would then require the custom module to have a dependency on website_sale which isn't necessary.

**Comment by ltinel** [comment]
Hi, this is a known issue that we're fixing in https://github.com/odoo/odoo/pull/181135. Once that PR is merged, you should be able to add your own overrides. Note that your overrides will need to be added in the `product.template` model instead of the controller.

**Comment by ltinel** [comment]
Fixed with https://github.com/odoo/odoo/pull/181135
