### ISSUE TITLE
[hw_escpos] Problem identifying IP address on machines with non-US localization (at least with spanish one...)

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#1798]
Method print_status on main.py relies on the presence of string "inet addr" in the output from command "ifconfig".

Problems is that, at least on Ubuntu 14.04 with Spanish localization, it returns "Direc. inet" instead...

In other situations, we have used regular expression "inet.*:" to find the information, and works reliably at least in English and Spanish localized operating systems... Or maybe could use translated string instead...

Regards,
-Mario

**Comment by Yenthe666** [comment]
Hi @TheCloneMaster,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
