### ISSUE TITLE
Missing server filter for aggregated results in ORM domains

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#18001]
**Impacted versions**: all

**Steps to reproduce**: 

It's not an error. It is just a desired feature of the ORM. The current contexts are:

1) Queries that use the **HAVING** sql clause. Like this [one](https://github.com/odoo/odoo/blob/814c55091339ea508a2aecf03f9c41bf4a63a14a/addons/crm/wizard/base_partner_merge.py#L375)

2) Loops over the result of **ORM** queries that perform counts and a second loop to filter those with specific counts, totals, subtotals, etc...

3) Loops over the **read_group** results  to filter out the results with __count = 1

**Current behavior**:

The three previous contexts are looking to achieve the same goal: _Filter over aggregated results_.

The nearest option is the *read_group* option but it requires the additional loop in the client side (odoo) even when *postgresql* server can implement those filters in the server side. For those use contexts the performance gain would be noticeable, because is saves:

1) the bandwidth and CPU time for the rows transference (**postgresql** -> **odoo**)
2) the CPU time for the loop over the results 
    and  / or ....
3) the cache memory for all those objects 

**Expected behavior**:

The *Model.read_group* function seems to be the place intended to make aggregations in the ORM. And initial option would be to convert the **groupby** parameter (currently a list) in a dictionary where the keys **maintain** the same meaning and the values are extra spec (range (min, max) for the aggregation, etc..)

Actually it would be good that the groupby_functions could be extended for **sum**, *max* and *min* in the case of numeric fields.

Then many performance stuff could then be treated converting all the occurrences of those three cases in the code to *read_group* calls, minimizing the rows transference from the sql server, the amount of loops over the result sets, ... and the cases where an specific **sql** sentence is needed.

**Comment by pedrobaeza** [comment]
There has been already some work for custom aggregations at read_group level, so please check them and tell back if this still applies. If you have it clear, a PR to master is also very welcome with your proposal.

**Comment by yucer** [comment]
sorry, I'm a bit outdated.

I barely have time to report the problems when I find them.

But I will check it ass soon I have time.

**Comment by pedrobaeza** [comment]
OK, closing meanwhile. Open a new issue with the conclusions.
