### ISSUE TITLE
[NL] Translation typo

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#18007]
Looks like a typo got commited to:

https://github.com/odoo/odoo/blob/10.0/addons/web_kanban/i18n/nl.po

```
msgid "Create"
msgstr "Aanmken"
```

Should be 

```
msgid "Create"
msgstr "Aanmaken"
```

**Comment by Yenthe666** [comment]
Hi @adaptivdesign,

Thank you for your report.
Translations however are handled on another platform (transifex.com/odoo/).
You can fix the translations there and they'll be synchronised into Odoo every once in a while (usually about once a week).
For more information see https://github.com/odoo/odoo/wiki/Translations

Regards,
Yenthe
