### ISSUE TITLE
POS no support taxes with python code

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#18009]
**Impacted versions:**
all
**Steps to reproduce:**
Create taxes with python code applicable, configure tax on products, on POS this taxes are not calculate
**Current behavior:**
taxes with python code returned 0
**Expected behavior:**
POS spport taxes with python code
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Thank you for your report but indeed as the point of sale works offline, it can not execute python code. It is not supported.
Sorry
