### ISSUE TITLE
[10.0+e] Balance Sheet Report Problems

### ISSUE THREAD

**Issue by cliffkujala** [odoo/odoo#18010]
Impacted versions:
Odoo 10.0+e-20170703 (Enterprise Edition)

Steps to reproduce:
Set custom date for a Balance Sheet Report

Current behavior:
1. CURRENT YEAR EARNINGS does not match the P&L number for the fiscal year associated with the custom ending date selected as a basis for the Balance Sheet Report. 
IE: Manually choose 12/31/2015 for the balance sheet date, and the CURRENT YEAR EARNINGS that Odoo calculates for that Balance Sheet does not match a manual P&L report for the same period (1/1/2015-12/31/2015).  
2. Also when you click on CURRENT YEAR EARNINGS from the Balance Sheet Report, you are taken to a P&L report which is dated having a range of 1/1/2017 to 12/31/2015(or whichever custom date you had selected on the Balance Sheet).  It is always starting at 1/1/2017 instead of the correct start of the associated fiscal year.

Expected behavior:
1. CURRENT YEAR EARNINGS reported on the Balance Sheet should match a P&L report with a range the same as START OF FISCAL YEAR up to DATE SELECTED ON BALANCE SHEET.
2. Clicking on CURRENT YEAR EARNINGS from the Balance Sheet report should produce a P&L with the correct date range of START OF APPROPRIATE FISCAL YEAR to DATE SELECTED ON BALANCE SHEET.

Video/Screenshot link (optional):
[https://goo.gl/photos/TpGLGs5nTZFe33geA](https://goo.gl/photos/TpGLGs5nTZFe33geA)
STEP ONE - BALANCE SHEET WITH CUSTOM DATE
![screen shot 2017-07-04 at 9 20 37 am](https://user-images.githubusercontent.com/7710215/27837894-060b214c-609c-11e7-8e39-567bee1c4490.png)
STEP TWO - Resulting P&L Report from clicking on CURRENT YEAR EARNINGS
![screen shot 2017-07-04 at 9 21 05 am](https://user-images.githubusercontent.com/7710215/27837924-2c2f655e-609c-11e7-8b50-222df63e5c29.png)
STEP THREE - This is a P&L with correct date range
![screen shot 2017-07-04 at 9 21 28 am](https://user-images.githubusercontent.com/7710215/27838012-bc589c90-609c-11e7-86c7-7095ca997e40.png)

**Comment by cliffkujala** [comment]
Perhaps the problems with the reporting has something to do with the Account Types, and if they are set to bring balances forward or not??

See a screenshot of how my account types are configured.  Does anyone know if they are as they should be per Odoo guidelines?
![screen shot 2017-07-07 at 3 41 32 pm](https://user-images.githubusercontent.com/7710215/27987682-4ecd9e82-63c6-11e7-98dd-a5bcb98f7e61.png)

**Comment by cliffkujala** [comment]
Ok. So to update this.

1. I guess this is an expected problem if you do not make a manual Journal Entry to move "Current Year Earnings" over to a retained earnings account at the end of the fiscal period (or for me it seems cleaner to do the move on the first day of the next period but I'm not an accountant).  So I guess this portion of this could be marked closed, ALTHOUGH I don't agree with the need to do this.  Odoo should add an Account Type called "Retained Earnings" and force 1 and only 1 Chart Account to be set as the Retained Earnings account.  Then the reports could dynamically move the CYE over to RE at the changeover between fiscal periods.  Quickbooks does this automatically.  This would eliminate the need for that manual journal entry.

2. This problem with date-range is for sure still a BUG on my system.  I spun up a new SAAS trial version, and the behavior is working correctly. When you click CURRENT YEAR EARNINGS from a Balance Sheet, it takes you to a P&L with the exact same date range as the BS you were viewing.  

So please someone at Odoo look into this.
Again I am running on Odoo 10.0+e-20170703 (Enterprise Edition)

**Comment by fmdl** [comment]
There are a PR to limit at one the number of account with "Current Year Earning" (it is generally the 999999).
https://github.com/odoo/odoo/pull/17777

**Comment by pedrobaeza** [comment]
This is something about enterprise modules, so it should be treated through http://odoo.com/help, but any way, it's not an issue, but a misconfiguration: you have to put at least one account type of "Current Year Earnings", and one account (only one) belonging to that account type.

Closing by the reasons stated above.
