### ISSUE TITLE
[master] TZ field refresh each second and not allow choose value

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#18011]
Impacted versions:
 - master

Steps to reproduce:
  1. Open timezone user configuration
  2. Try choose one timezone

Current behavior:
 - A refresh for the timezone field and not allow choose the correct one.

Expected behavior:
 - Allow choose a TZ without Flash's ability

Video/Screenshot link (optional):
 - [![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/VB3fkEeLxwA/0.jpg)](https://www.youtube.com/watch?v=VB3fkEeLxwA)

**Comment by Yenthe666** [comment]
Yep, there is absolutely something wrong here. 😄

**Comment by bst-odoo** [comment]
Similar tickets have been sent to the support. Bug fix team is on it.
