### ISSUE TITLE
Git version is out of date

### ISSUE THREAD

**Issue by hdezela** [odoo/odoo#18014]
Impacted versions:
10.0

Steps to reproduce:
git checkout
git describe --long --tags

Current behavior:
Returns version 7.0

Expected behavior:
Version 10.0

Video/Screenshot link (optional):

**Comment by dbo-odoo** [comment]
Hello,

We don't use tags in our git workflow; therefore git describe will never return something really relevant... You can find the version number in the branch name; since we do not increase the version number with revisions this will remain correct.

KR,
