### ISSUE TITLE
Why in the Calendar View if you move the invoice can change the date of the invoice validated ? 

### ISSUE THREAD

**Issue by scuestae** [odoo/odoo#1803]
I open the Customers Invoices in Calendar View, I move a invoice to other day, I return to the Tree View and the invoice date has changed.
I think is a error.

**Comment by Yenthe666** [comment]
Hi @scuestae,

Thank you for your report and sorry for the late reply.
You can indeed move a confirmed (and even paid invoice) from the calendar view.
@mart-e what do you think about this?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @scuestae,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
