### ISSUE TITLE
[8.0] When create res.partner.bank in multicompany, company_id is not set

### ISSUE THREAD

**Issue by daviddiz** [odoo/odoo#18034]
Impacted versions: 8.0

Current behavior: When a bank account is created in multicompany, the field company_id is not set

Expected behavior: By default the company_id of the bank account must be the company of the user

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
