### ISSUE TITLE
Understanding " Real Price " Costing Method in Product Master

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#1804]
Its a very powerful method to Implement FIFO, LIFO and FEFO Delivery policies. And its working fine in all the scenario including landed cost calculation.
Only Imitation you can see is Cost Price Settings, The filed is enabled to enter cost price of the product and it will appear in sales order to calculate sales order margin. But actual cost of goods calculation will be based on the Delivery Removal Strategy (FIFO /LIFO /FEFO) in Anglo Aaxson Accounting System. 
In this scenario Sales order Margin and Accounting Journals will not match and profit will be different. 
In stock valuation its taking the batch wise cost of the items. So the average stock value will be 
Balance Quantity of each batch \* Purchase Cost of the same batch + Next Batch / Total Quantity.
But not at easy to calculate manually and set in product master. So the suggestion is Odoo should set the cost value as average (method used in stock valuation) and a link button to show the calculation exactly as the stock valuation list view (see attached)

![products odoo](https://cloud.githubusercontent.com/assets/2189864/3941978/a2e295be-254d-11e4-80d8-84c2d45f5911.png)

![untitled](https://cloud.githubusercontent.com/assets/2189864/3941986/b8fc56fa-254d-11e4-801b-ee80d8defcb1.png)

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
