### ISSUE TITLE
[10.0]-Init debian odoo-server script

### ISSUE THREAD

**Issue by luistriana28** [odoo/odoo#18049]
Impacted versions: 10.0

Steps to reproduce: copy /debian/init script in /etc/init.d/odoo-server

Current behavior: Syntax Error 

Expected behavior: start-stop-restart service 

Video/Screenshot link (optional):
![captura de pantalla 2017-07-05 a la s 12 02 14](https://user-images.githubusercontent.com/12242599/27875714-d0274fae-6179-11e7-8707-b70e2a4463a0.png)

**Comment by Yenthe666** [comment]
Hmm there doesn't seem to be anything wrong with the init (see https://github.com/odoo/odoo/blob/10.0/debian/init).
Could you try updating your Odoo to the latest codebase, copy the init again and give it another try please?

Regards,
Yenthe

**Comment by luistriana28** [comment]
I have checked my init with my personalization of Daemon etc,
![captura de pantalla 2017-07-06 a la s 10 41 49](https://user-images.githubusercontent.com/12242599/27919647-dcd23aa2-6237-11e7-8029-6c18088d64de.png)

i have already updated my base: the last commit is this : 2454dce7c5738750bee34

And here is my /etc/init.d/odoo-server permissions:

![captura de pantalla 2017-07-06 a la s 10 40 18](https://user-images.githubusercontent.com/12242599/27919700-fc80f974-6237-11e7-86e4-9704b89dd7f4.png)


Regards

**Comment by luistriana28** [comment]
I have checked the past sha of odoo that i used to use and is this: 6981320

**Comment by Yenthe666** [comment]
Hmm @sle-odoo do you have any idea?

**Comment by sle-odoo** [comment]
@luistriana28 what version of debian do you use?

**Comment by luistriana28** [comment]
@sle-odoo im using ubuntu 14.04

**Comment by luistriana28** [comment]
It only happens when I run by /etc/init.d/odoo-server start
it shows the error

**Comment by pedrobaeza** [comment]
@d-fence any news about this?
