### ISSUE TITLE
Error with ldap in samba 4

### ISSUE THREAD

**Issue by WolfDangerY** [odoo/odoo#18051]
Impacted versions: 10.0

Steps to reproduce: Autentication with samba 4, the last version, field cn in samba 4 new is CN
return {
            'name': ldap_entry[1]['cn'][0],
            'login': login,
            'company_id': conf['company'][0]
        }

ERROR!!!!!!

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by kryskool** [comment]
Hi

I have been the same issue, it's a bug in Samba

Fix un the last version

**Comment by Yenthe666** [comment]
Thank you for your feedback @kryskool.
@WolfDangerY please update your Samba version to the very latest version and it should be fixed.

Regards,
Yenthe
