### ISSUE TITLE
Picking is not done, when the product.type ='product' and line.qty = 0 

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#18089]
Impacted versions: 10.0

Steps to reproduce:
1. Create pos order with two products.
2. One of the products, must be type= Stockable Product and quantity=0.
3. Pay order.
4. check order --> extra info --> picking
5. picking state = Waiting Availability  

Current behavior:
picking State = Waiting Availability

Expected behavior:
picking State  = Done
[As in v9.0](https://youtu.be/X_R_jHZdYb8)

Video/Screenshot link (optional):
https://youtu.be/eWCe6juEcvw

**Comment by simongoffin** [comment]
Hello @jco-odoo 

What do you think about it?

**Comment by jco-odoo** [comment]
There is nothing against putting the code back as before, but why do we allow lines of 0 to be generated in the pos picking? Normally, we don't work with moves at 0 qty.

**Comment by wtaferner** [comment]
I agree with Jos that a zero stock move does not make any sense.
After taking a look at the video I think that the fix is not to allow zero stock moves but to not create them based on a PoS zero unit sale event of a stockable product.
