### ISSUE TITLE
User with admin access rights don't show other user

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#18093]
Impacted versions: odoo 9

Steps to reproduce: User with admin access rights (test1) don't show other user in one2many field only just see yourself.

Other user with the same access rights (test1) see everything!

Current behavior: How fix this problem, any solution?

Expected behavior:

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Please, test on runbot.odoo.com that is it a generic bug and explains the step to reproduce your problem.

1. create a user with administraion right
2. connect with this user
3. go to the form view xxxx 
4. try to add a user
5. ... 

Without more informations, we cannot reproduce anything.

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in a few months.

Regards,
Yenthe
