### ISSUE TITLE
Cannot change image or title in local events snippet

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#18103]
Impacted versions: 8, 9, 10, master.

Steps to reproduce:

1. Install `website_event`.
2. Edit any website page.
3. Add a structure block.
4. Add the local events snippet.
5. Change image and title of the snippet as usual.
6. Save.

Current behavior:

Each time the page gets loaded, you can see the user's editions for a little while, and then they get suddenly changed for the default layout.

Expected behavior:

Events should change, but image and title should stay the same.

Video/Screenshot link (optional):

[Screencast_07-07-17_14:47:11.zip](https://github.com/odoo/odoo/files/1130985/Screencast_07-07-17_14.47.11.zip)

@Tecnativa

**Comment by Gorash** [comment]
Hi,
To change the image or other rendering of this snippet you must change the template loaded by the JavaScript : "website_event.country_events_list".
There is no editor for content dynamically loaded by JavaScript.
You can edit it in the views backend settings.
Regards
