### ISSUE TITLE
Server Crash when login with User created with specific permissions

### ISSUE THREAD

**Issue by davidqdr** [odoo/odoo#18105]
Impacted versions:
10.0

Steps to reproduce:
1. Create a user with blank permissions on every application except point of sale.
2. Try to login with this new user.
3. Server crash with 500 Internal Server Error and restarting of the server is needed.
4. When you modify the user configuration leaving all permissions with blank except Employee, the error not reproduce.

Current behavior:
- Server crash with "500 Internal Server Error" and restarting of the server is needed.
- After Restart Server and before you type server url in browser you need to delete browser history because the user is logged in and the server crash again.

Expected behavior:
Not permit create users with Employee application in blank option if it produce server crashing. Or if a user is misconfiguration don't let login.

Video/Screenshot link (optional):
<img width="960" alt="servercash_1" src="https://user-images.githubusercontent.com/5203985/27983973-5f92db82-63c2-11e7-99ed-cab4d6b2641c.png">
<img width="960" alt="servercash_2" src="https://user-images.githubusercontent.com/5203985/27983897-2d9199fe-63c0-11e7-8e6e-54b4524cbacb.png">
<img width="960" alt="servercash_3" src="https://user-images.githubusercontent.com/5203985/27983898-38f8bcb4-63c0-11e7-9962-0a6182cbb047.png">

**Comment by Yenthe666** [comment]
Hi @davidqdr,

Thank you for your report.
I've just tested this on the latest Odoo 10 runbot and was able to reproduce this:
![image](https://user-images.githubusercontent.com/6352350/27986495-c38f0b6e-63ff-11e7-8e84-c656c4e35391.png)
@mart-e perhaps for you?

Regards,
Yenthe

**Comment by mart-e** [comment]
> Steps to reproduce:
> 
> 1.  Create a user with blank permissions on every application except point of sale.

Ok search no more. An odoo user **must** be one (and only one of):

- Employee
- Portal
- Public

It will not work if you are not at least one of them.

**Comment by Yenthe666** [comment]
@mart-e perhaps a warning is in place though? This is a bit harsh to me.

**Comment by mart-e** [comment]
Actually @jem-odoo is working to improve the setting screen to prevent this. You will get a dropdown where you have to chose between one of the three (but still in the spec state, not ready yet)

**Comment by Yenthe666** [comment]
Fair enough - if it is handled or will be handled it is fine. Thank you.
