### ISSUE TITLE
with gmail for smtp... less secure apps warning

### ISSUE THREAD

**Issue by matecsaj** [odoo/odoo#1810]
In general settings, when setting up an outgoing SMTP server if you use a gmail account then press the test button you, get the warning below in your gmail inbox. 

In gmail after you change to the less secure option, then Odoo's outgoing mail server test will succeed, but this doesn't seem like an ideal solution.  I don't want to risk getting my gmail account hacked while using the less secure option.
## Running 7.0 nightly build on a Ubuntu server. 

```
Hi John, 
```

We recently blocked a sign-in attempt to your Google Account [matecsaj@gmail.com]. 

Sign in attempt details
Date & Time: Saturday, August 16, 2014 6:02:05 PM UTC 
Location: Port Dover, ON, Canada 

If this wasn't you
Please review your Account Activity page at https://security.google.com/settings/security/activity to see if anything looks suspicious. Whoever tried to sign in to your account knows your password; we recommend that you change it right away. 

If this was you
You can switch to an app made by Google such as Gmail to access your account (recommended) or change your settings at https://www.google.com/settings/security/lesssecureapps so that your account is no longer protected by modern security standards. 

To learn more, see https://support.google.com/accounts/answer/6009563. 

Sincerely,
The Google Accounts team  
This email can't receive replies. For more information, visit the Google Accounts Help Center.

**Comment by Yenthe666** [comment]
Hi @matecsaj,

Thank you for your report.
This is however the desired behaviour and we know this is the case. If you change the settings of your account it'll work this way.
@JKE-be perhaps it might be time to change this behaviour to OAUTH2.0 or something in the upcoming V11 though?
Closing as this is the desired behaviour.

Regards,
Yenthe

**Comment by martinblonk** [comment]
Hi, when will a more secure version of OAUTH be implemented In Odoo so I can use gmail as imap server?

**Comment by eLBati** [comment]
@martinblonk you can use gmail just allowing less secure apps in your google account settings

**Comment by Yenthe666** [comment]
@eLBati I think @martinblonk is trying to point out that he doesn't find the 'allowing less secure apps' in Odoo very safe.

**Comment by martinblonk** [comment]
Indeed @Yenthe666 , that's what I mean. I do not want to give less secure apps access to my gmail account.

**Comment by Yenthe666** [comment]
Hmm, maybe we should reopen this and get this checked by the Odoo guys?
