### ISSUE TITLE
bad html in templates.xml from website_sale issue to untranslatable Shop Cart strings

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#18106]
Impacted versions:
10.0 CE nightly builds  (untested with others)
Steps to reproduce:
install website_sale and load a translation
Current behavior:
1. Strings "My cart" in nav menu and "Remove" in shop cart are not translated because existing translations are not loaded.
2. When one try to translate or change text by Editing from website, string are unselectable.
Expected behavior:
Translations loaded, user able to change text.

Workaround:
- adding «p» html tag around "Remove" solve the problem.
- but adding «p» tag around "My cart" change its position in menu

**Comment by qsm-odoo** [comment]
Seems like it works for me, it may have been fixed meanwhile

![image](https://user-images.githubusercontent.com/10338094/35334991-7721419a-0114-11e8-91c8-e05a49d2f1ed.png)

Please tell me if this needs to be reopened.
