### ISSUE TITLE
[9.0] TypeError: chart.tooltip.chartContainer is not a function

### ISSUE THREAD

**Issue by open-net-sarl** [odoo/odoo#18116]
**Impacted versions:** 
9.0

**Steps to reproduce:** 
![screenshot_1](https://user-images.githubusercontent.com/8555256/28007505-fa5b5116-6553-11e7-9b21-ee1a7bbcd9db.png)
 (use a mesure that has no values)

**Current behavior:**
![screenshot_4](https://user-images.githubusercontent.com/8555256/28007731-db23e26c-6554-11e7-8faf-ea5eb54fa76e.png)

**Expected behavior:** 
Dont pop-up an error with the traceback when there's no valid values to construct the graph, like the behavior on 10.0 .

**Comment by Yenthe666** [comment]
Hi @open-net-sarl,

Thank you for your report.
I've just tested this on the latest Odoo 9.0 (ENT) runbot without any problems.
Can you please update your Odoo environment or try to reproduce this on a runbot?

Regards,
Yenthe

**Comment by open-net-sarl** [comment]
Hi @Yenthe666,

If you see the url in the last print you can confirm that I tested in runbot.
Has I said, to reproduce the error you should use a "mesure" that has no values. 
For exemple I removed all the leads colors and used "color index" as a mesure to create the pie chart.
The error is only in the pie chart.

**Comment by Yenthe666** [comment]
Oops I'm sorry @open-net-sarl and yes indeed this is a bug. If you remove all the colours on the lead its tags and open te graph it'll even crash without taking the parameter without values:
![image](https://user-images.githubusercontent.com/6352350/28055422-2304b074-6619-11e7-8695-68a11ef1ee61.png)
@ged-odoo as it is JS related, here is one for you. 😉 

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@ged-odoo could you have somebody have a look at it perhaps? Could you assign somebody (sorry for pinging you so much today, I'm going over all issues).

**Comment by ged-odoo** [comment]
@nim-odoo this is a bug in v9.0. If you don't want to/can't solve it, ping me back, and we'll do it

**Comment by Yenthe666** [comment]
@nim-odoo and @ged-odoo any update here?

**Comment by Yenthe666** [comment]
Hey,

I just tested this again and it seems to be fixed and working fine in the meanwhile! I've removed all leads tags from all customers and reset all colors. After opening the graph:
![image](https://user-images.githubusercontent.com/6352350/38664397-be986ef6-3e39-11e8-8464-16b80646fa13.png)
