### ISSUE TITLE
pos_discount 

### ISSUE THREAD

**Issue by yousef-soliman** [odoo/odoo#18138]
Hi, 
Impacted versions:
10.0

why we need to put discount as product ..?
we can put as function and get same result !
i think we haven't use as product..
i try to put some products and get discount and put other some products again
the discount was in the middle between products 
i think this not logical !!

**Comment by Yenthe666** [comment]
Hi @yousef-soliman,

Thank you for your report.
This is however intended behaviour and works as Odoo wants it to work. If you'd like the discount line on the last line (or some other behaviour) you'll need to do some custom development to achieve this.

Regards,
Yenthe
