### ISSUE TITLE
[17.0] Google Calendar

### ISSUE THREAD

**Issue by whes1015** [odoo/odoo#181308]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Steps to Reproduce

The authentication https for google calendar oauth has been changed to http and I have configured the web base url

![image](https://github.com/user-attachments/assets/069f91ab-4b57-4579-b1f4-7f54d6a9d54d)

### Log Output

```shell
Error 400: redirect_uri_mismatch

This application does not comply with Google's OAuth 2.0 policy, so you can't sign in.

If you are an application developer, go to the Google Cloud Console to register a redirect URI.
Request details: redirect_uri=http://odoo.exptech.synology.me/google_account/authentication flowName=GeneralOAuthFlow
```

**Comment by rianmz-genz** [comment]
I have same issue, what should i do?
