### ISSUE TITLE
Attachments to messages stuck on "uploading"

### ISSUE THREAD

**Issue by bigmillz** [odoo/odoo#18137]
Impacted versions: v9.0c

Steps to reproduce:
1. Create a new quote
2. Click New Message
3. Click the attach button and attach any file

Current behavior: Attachment icon appears above, but says "uploading" indefinitely

Expected behavior: Attachment should finish uploading

Log output even on debug is useless:
2017-07-10 19:53:08,965 31123 INFO amzt-odoo-2 werkzeug: 127.0.0.1 - - [10/Jul/2017 19:53:08] "POST /web/binary/upload_attachment HTTP/1.0" 200 - 
2017-07-10 19:53:11,978 31123 INFO amzt-odoo-2 werkzeug: 127.0.0.1 - - [10/Jul/2017 19:53:11] "POST /longpolling/poll HTTP/1.0" 200 -

Update: traced it to our SSL configuration in nginx. Running without SSL/HTTPS for now and uploading works. Any ideas?

**Comment by Yenthe666** [comment]
Hi @bigmillz,

Thank you for your report.
I've just double checked it on the latest source code and it works fine out of the box.
This really looks like an implementation /configuration issue. Please have a look at https://www.odoo.com/documentation/10.0/setup/install.html and especially at https://www.odoo.com/documentation/10.0/setup/deploy.html
If you still face this issue afterwards please do ask help on the official forums, where plenty of people can help you. See http://odoo.com/help

Regards,
Yenthe

**Comment by mstuttgart** [comment]
@bigmillz I face this same problem. Do you find what cause this error?

**Comment by arafatx** [comment]
@mstuttgart It's related to the configuration server on the SSL. If you follow the rule then it's gonna work.

**Comment by sanjay-onnet** [comment]
@arafatx @Yenthe666 please let me know which SSL configuration solves this problem
