### ISSUE TITLE
[10.0] [Bug] Could not set First language as Russian in website

### ISSUE THREAD

**Issue by sindhav** [odoo/odoo#18134]
**Impacted versions:**
Odoo 10.0

**Steps to reproduce:**

I have a use-case where I want to set the Russian language as the First language. When anyone hits the domain of my website then by default website should be in the Russian Language because I want Russian language as the First language and English as a Second Language. 

To achieve this I did a configuration as below.

1) My Company language is a Russian language.
2) Public user language is a Russian language.
3) In the "Website Admin > Configuration > Settings" menu I have selected the Default language as Russian and in Languages field I have selected checkbox for both English as well as Russian because I want English as a Second Language.

**Issue / Problem:**
When anyone(as Public user) hits the domain then website is displayed in the English language but it should be in the Russian language.

**Current behavior:**
When anyone(as Public user) hits the domain then website is displayed in the English language but it should be in the Russian language.

**Expected behavior:**
But Website should be in the Russian language.

**Comment by Yenthe666** [comment]
Hi @sindhav,

Thank you for your report.
It does seem to work to me. However, I did first need to go to the website with the admin user, select the Russian, then logout and then it'll be in Russian (also in other browsers and tabs). Can you try that too and update to the latest source code?
CC @JKE-be because I'm sure you can give more info 😉 

Regards,
Yenthe

**Comment by JKE-be** [comment]
You need to check yours urls... 
you are probably in russe by defaut (so no language in URL) but because your browser is in en_us, we match automatically your browser language and your Website.

It is just a lead to explain... can you confirm ?

**Comment by sindhav** [comment]
@JKE-be is right, website sent response accordingly the browser language. :relaxed: 
Thanks @JKE-be and @Yenthe666 for your quick & valuable response.

**Comment by Yenthe666** [comment]
No problem - best of luck!
