### ISSUE TITLE
[8.0] MRP Operation: Operation scheduling - End date calculation wrong

### ISSUE THREAD

**Issue by maljac** [odoo/odoo#18156]
Impacted versions: 8.0 (probably 9.0 and 10.0)

Steps to reproduce:
1. Create a new Resource schedule (Mo - Sun, 00:00 - 24:00)
2. Create a new Work Order, set Hours to 5, start date to 00:00 or 05:00 (doesn't matter)

Current behavior:
The planned_end is always missing the difference between the users timezone and UCT. For example in UCT+2 the planned end, if we schedule the start to 00:00 and set hours to 5, is 03:00 instead of 05:00.

Expected behavior:
The planned_end must be 05:00 in the above mentioned scenario.

How to fix:
You can fix the behavior if you comment the lines https://github.com/odoo/odoo/blob/8.0/addons/resource/resource.py#L344-L345

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/10473754/28057269-c8a1b8dc-661f-11e7-99af-a3770e7f05c3.png)

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback? Is this intended behaviour?

**Comment by dhannyz** [comment]
@maljac @Yenthe666 Could this be related to an issue I just posted?
https://github.com/odoo/odoo/issues/18166
I found an issue here regarding the timezone handling as well. Going back an extra day

**Comment by maljac** [comment]
@dhannyz In my opinion the issues are the same. The code snipped you posted in #18166 is exactly the part that I also identified as issue for this problem. So this behaviour can be found in 8, 10 and probably 9.

**Comment by Yenthe666** [comment]
Hi @maljac,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
