### ISSUE TITLE
[17.0] hr_holidatys: Incorrect Return Type in _get_remaining_leaves Method

### ISSUE THREAD

**Issue by piash23** [odoo/odoo#181546]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [X] 17.0
- [ ] Other (specify)

### Issue Title
**Return Type Error in `_get_remaining_leaves` Method Leading to AttributeError in `_compute_remaining_leaves` in `hr_holidays` Module , file hr_employee_base.py**

#### Description
In the `hr_holidays` module for Odoo version 17.0, the `_get_remaining_leaves` method currently returns a set of tuples instead of the expected dictionary. This results in an error when the `_compute_remaining_leaves` method attempts to access the returned value using `.get()`, which leads to the following error:

#### Expected Behavior
The `_get_remaining_leaves` method should return a dictionary where:
- Keys are employee IDs.
- Values are the corresponding remaining leave days.

#### Actual Behavior
Currently, the `_get_remaining_leaves` method returns a set of tuples, for example:
```python
{(2, 10.0)}
```

#### Suggested Fix
To resolve this issue, change the return statement in `_get_remaining_leaves` to:
```python
return dict((row['employee_id'], row['days']) for row in self._cr.dictfetchall())


### Log Output

_No response_

### Support Ticket

_No response_

**Comment by duong77476-viindoo** [comment]
Are you sure, last time i check it same as your suggested code
https://github.com/odoo/odoo/blob/17.0/addons/hr_holidays/models/hr_employee_base.py#L77

**Comment by piash23** [comment]
yeah, i am 100% sure it is returning a tuple instead of dict

**Comment by duong77476-viindoo** [comment]
> yeah, i am 100% sure it is returning a tuple instead of dict

Actually, it return set, anyway , i 've made a fix for odoo, just wait

**Comment by piash23** [comment]
Yeah, it returns set, thank you for the fix.
