### ISSUE TITLE
[10.0 + 10.0e] Important! Working Hours Not Computed Correctly

### ISSUE THREAD

**Issue by dhannyz** [odoo/odoo#18166]
Working hours calculated by the method get_working_hours(...) in the resource.calendar model are not computed correctly in certain edge cases.

When both timezone and the beginning of a working interval defined in a resource.calendar happen to overlap, the computation of hours fails for the first hour of the working interval.

Examples:
**Timezone = UTC + 10
Work Interval = 9:00 - 17:00**

### Case 1a:
```
start = fields.Datetime.from_string('12/07/2017 9:10:00')
end = fields.Datetime.from_string('12/07/2017 9:40:00')
res = self.get_working_hours(start_dt=start, end_dt=end)
```
_**res = 1.00
Expected: 0.50**_ 

### Case 1b: Using Context
```
start = fields.Datetime.from_string('12/07/2017 9:10:00')
end = fields.Datetime.from_string('12/07/2017 9:40:00')
res = self.with_context(force_start_dt=start).get_working_hours(start_dt=start, end_dt=end)
```
_**res = 0.00
Expected: 0.50**_

### Case 2a:
```
start = fields.Datetime.from_string('12/07/2017 9:10:00')
end = fields.Datetime.from_string('12/07/2017 10:40:00')
res = self.get_working_hours(start_dt=start, end_dt=end)
```
_**res = 2.67 
Expected: 1.50**_

### Case 2b: Using Context
```
start = fields.Datetime.from_string('12/07/2017 9:10:00')
end = fields.Datetime.from_string('12/07/2017 10:40:00')
res = self.with_context(force_start_dt=start).get_working_hours(start_dt=start, end_dt=end)
```
_**res = 1.50
Expected: 1.50**_  
_The use of the force_start_dt context seems to resolve the issue when the end date is >= 1.0 hrs in the future._

Now setting the resource.calendar working times to start on a time that does not overlap a UTC day.
**Timezone = UTC + 10 
Work Interval = 11:00 - 17:00**
### Case 3a:
```
start = fields.Datetime.from_string('12/07/2017 11:10:00')
end = fields.Datetime.from_string('12/07/2017 11:40:00')
res = self.get_working_hours(start_dt=start, end_dt=end)
```
_**res = 0.50
Expected: 0.50**_  

### Case 3b: Using Context
```
start = fields.Datetime.from_string('12/07/2017 11:10:00')
end = fields.Datetime.from_string('12/07/2017 11:40:00')
self.with_context(force_start_dt=start).get_working_hours(start_dt=start, end_dt=end)
```
_**res = 0.50
Expected: 0.50**_  

We can notice from Case 3 that when the timezone is not causing the use of the previous UTC date, hours are being computed correctly. And also that the force_start_dt context doesn't alter results.

This seems like a relatively major issue for scheduling, especially in countries where the timezone adjustment used in get_working_intervals_of_day(...) places a working interval across two UTC dates

Looking at the get_working_hours(...) method, I haven't figured out the cause of this problem yet, can anybody aid in this?

Edit: I've isolated it to occurring within the `get_working_intervals_of_day(...)` method

**Comment by dhannyz** [comment]
Stepping through get_working_intervals_of_day(...) the implementation of the timezone adjustment seems completely broken.
Lets say the intended start time, as taken from the webclient is 2017/07/12 9:00 UTC+10
This will be stored in the database as 2017/07/11 23:00

Inside `def get_working_intervals_of_day(...):` we take this as a datetime as the start_dt
start_dt = datetime.datetime(2017, 7, 11, 23, 0)
Then
```python
        work_dt = start_dt.replace(hour=0, minute=0, second=0, microsecond=0)
        ...
        working_intervals = []
        tz_info = fields.Datetime.context_timestamp(self, work_dt).tzinfo
        for calendar_working_day in self.get_attendances_for_weekday(start_dt):
            dt_f = work_dt.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(seconds=(calendar_working_day.hour_from * 3600))
            dt_t = work_dt.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(seconds=(calendar_working_day.hour_to * 3600))

            # adapt tz
            working_interval = (
                dt_f.replace(tzinfo=tz_info).astimezone(pytz.UTC).replace(tzinfo=None),
                dt_t.replace(tzinfo=tz_info).astimezone(pytz.UTC).replace(tzinfo=None),
                calendar_working_day.id
            )
```
Now... work_dt has had its time information zeroed out. then the new times are pulled from the calendar working time line. But this fiddling with the timezone produces an entirely incorrect interval.
Given a start time of 9:00, work_dt becomes `datetime.datetime(2017, 7, 11, 9, 0)` and gets the UTC+10 timezone.
**Then converted to UTC again!**
In essence the **timezone conversion occurs twice and we go backwards in time too far**.
So, our actual start time being `datetime.datetime(2017, 7, 11, 23, 0)` we end up with an interval starting on `datetime.datetime(2017, 7, 10, 23, 0)`

This accounts partly for the extra hour in Case 2a above, however I'm not sure if it identifies all the problems occuring here.

**Comment by Yenthe666** [comment]
Hmm @mart-e this looks off.

**Comment by maljac** [comment]
As I wrote in #18156 this issue seems the same as I described in #18156

**Comment by dhannyz** [comment]
Hi @maljac 
There are in fact multiple errors occuring in that module, not just the timezone issue, it seems 
The entire resource module was re-written for saas-15+ and I can confirm it now functions correctly.
Unfortunately, I believe backporting the fixed versions to 10 and below would take some effort. I've got an instance working on 10, but am running without manufacturing and calendars on order points.
My use case was to implement lead times for sales and deliveries, based off working calendars.
It could be that waiting for v11 is an easier solution

**Comment by lininac** [comment]
From my installation, I found problem cause on in hr_leave_hours/models/hr_holidays.py 
dt = dt - reference_date.tzinfo._utcoffset
from IMO this is double implemented, because datetime saved in DB is UTC

**Comment by pedrobaeza** [comment]
These rough edges you mention are indeed there, but with difficult solutions in current versions. The good news are that there has been a massive refactoring of all the resource calendar code in #24717, so in v12 this is not going to happen anymore.

I'm going to close this as "won't fix" for v10/v11, but solved on v12. If you have an enterprise contract, then maybe you can redirect your issue to the bugfix team to see if something can be handled on stable.
