### ISSUE TITLE
[16.0] mail.notification: Mark-as-Read notifications at the notification tray won't remove them instantly, requires a page reload

### ISSUE THREAD

**Issue by AzizDevl** [odoo/odoo#181601]
### Odoo Version

- [ ] 15.0
- [X] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

Current behaviour:

1: Open the notification tray (Conversations) on the top-right corner (Enterprise Edition).
2: Mark-As-Read any notification using the check-icon button next to the notification.
3: The notification entry still exists, and a page reload is required to notice the notification dismissal.

Expected behaviour:

3: The notification entry should go as you click on the check-icon button instantly, without page refresh.

Screenshot:
![mark_read_not_working_properly](https://github.com/user-attachments/assets/dbf327e9-16c5-4fce-af94-0487426e0bdc)

Now this is strange as it seems that it happens on our on-premise Odoo system.
I've tried it on a freshly installed Odoo, the problem isn't there.

The problem seems to be in the discuss app too, if you try to mark a notification as-read it won't go unless refreshing the page.

What could the problem be?!

**Comment by intero-chz** [comment]
Sounds like a problem with the bus.

**Comment by AzizDevl** [comment]
@intero-chz I don't know what you mean, but anyways, for anyone facing the same problem and have a proxy to Odoo such as Nginx, try to allow communication on port 8072 within the WebServer, as this would allow instant chatting using WebSockets.

**Comment by intero-chz** [comment]
@AzizDevl the bus.bus Error was a symptom when something about a used proxy wasn't configured correct. Admittedly, I should have pointed out a correct nginx config right away.

You'll find a really nice one in the official [documentation](https://www.odoo.com/documentation/17.0/administration/on_premise/deploy.html#https).
