### ISSUE TITLE
[8.0]Wizard for Accounting chart and others failed behind a proxy

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#1816]
Hy,

I'm trying to install customer_reference that depends on accounting module.
When working directly on IP:8072 no problem.
When working behind a proxy => it failed, a xml http request error is thrown

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
