### ISSUE TITLE
[9.0] account_tax_adjustment: tax_line shouldn't be set on both credit/debit

### ISSUE THREAD

**Issue by philhug** [odoo/odoo#18165]
Impacted versions: 9.0

Steps to reproduce: Create tax adjustment using the account_tax_adjustment module

Current behavior: move lines are created with tax_line_id set on both credit and debit. In the accounting/VAT report this will result in a value of zero as both values cancel each other out.

Expected behavior: Tax is set on either credit or debit, but not on both

Video/Screenshot link (optional):

Suggested fix: remove tax_line_id on credit side:

```
    def _create_move(self):
        debit_vals = {
            'name': self.reason,
            'debit': self.amount,
            'credit': 0.0,
            'account_id': self.debit_account_id.id,
            'tax_line_id': self.tax_id.id,
        }
        credit_vals = {
            'name': self.reason,
            'debit': 0.0,
            'credit': self.amount,
            'account_id': self.credit_account_id.id,
-            'tax_line_id': self.tax_id.id,
        }
        vals = {
            'journal_id': self.journal_id.id,
            'date': self.date,
            'state': 'draft',
            'line_ids': [(0, 0, debit_vals), (0, 0, credit_vals)]
        }

```

**Comment by pedrobaeza** [comment]
@qdp-odoo I haven't used the tax adjustment, as it's not needed in my country. Can you answer this issue?

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported aI'm closing this issue.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe
