### ISSUE TITLE
[10.0/11.0-account] reconcile with writeoff does not work if writeoff account is the same as the move lines account

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#18177]
Impacted versions:
9.0-10.0-11.0-master
Workaround :
- for some liquidity accounts, we need to reconcile move lines and keep the writeoff in the same account

Steps to reproduce:
- select move lines to be reconciled with debit <> credit
- in the wizard, choose "reconcile with writeoff"
- in the "Reconcile writeoff" wizard, set the same account that the moves to be reconciled

Current behavior:
- the move lines are not reconciled

Expected behavior:
- the move lines should be reconciled

**Comment by qdp-odoo** [comment]
I tested and it seems that problem doesn't occure anymore in v11, can't say exactly when it was fixed though....
