### ISSUE TITLE
[10.0/11.0-point_of_sale] When closing pos session, the account move date does not take session date in shop timezone

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#18182]
Impacted versions:
10.0
Steps to reproduce:
- Setup a Company with timezone GMT-10
- Open a pos session on day 1 at 8:00PM (GMT-10)
- When sales are over, close the pos session

Current behavior:
- The account move date is set at day 2

Expected behavior:
- The account move date should be set at day 1

Video/Screenshot link (optional):

**Comment by invitu** [comment]
fixed here : https://github.com/odoo/odoo/pull/17883

**Comment by Yenthe666** [comment]
Hi @invitu,

Thank you for your report.
I'm not sure why you first made a PR and then a bug report though? You don't need to create a bug report if you make a PR. It generates noise / extra issues while it isn't really needed.
Somebody from the Odoo team will look at the PR as soon as possible 😉

**Comment by pedrobaeza** [comment]
Closing as there's an opened PR: #17883
