### ISSUE TITLE
[10.0/11.0-point_of_sale] Taxes calculation is wrong with fiscal position

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#18181]
Impacted versions:
10.0

Steps to reproduce:
- Setup a fiscal position with taxes mapping
- Make a pos_order with the fiscal position

Current behavior:
- When payment is done, taxes calculation is wrong and the pos_order is not paid

Expected behavior:
- The pos_order taxes calculation should be ok and the pos_order should be paid

Video/Screenshot link (optional):

**Comment by invitu** [comment]
fixed here : https://github.com/odoo/odoo/pull/17865

**Comment by Yenthe666** [comment]
Hi @invitu,

Thank you for your report.
I'm not sure why you first made a PR and then a bug report though? You don't need to create a bug report if you make a PR. It generates noise / extra issues while it isn't really needed.
Somebody from the Odoo team will look at the PR as soon as possible 😉

**Comment by invitu** [comment]
@gustavovalverde it looks like you are the other guy that really uses pos ;-)
Are you interested in that one ?

**Comment by invitu** [comment]
@Yenthe666 I made a PR first and it looks like nobody saw it... then I made an issue and you saw it... It was worth doing it ;-)

**Comment by invitu** [comment]
here is another case that seems to be reviewed in that issue (tested on runbot) : 
steps to reproduce : 
- setup 2 taxes with different rate and that are "included in price" (ie. 15% and 10%)
- setup a fiscal position that does tax mapping between those 2 taxes (ie tax15 --> tax10)
- setup a new price list that computes a new price for a given product (ie 100 USD)
- setup the given product with tax15
- setup a pos with the fiscal position as default AND the new price list
- in pos, choose the given product
Actual Behavior : 
- in the pos, the order line price is 86.96 USD including 7.91 USD for tax
Expected behavior : 
- in the pos, the order line price should be 100.00 USD including 9.09 USD for tax

Note : 
A workaround is to change fiscal position to "none" in the pos, then add products, then reselect the fiscal position

**Comment by gustavovalverde** [comment]
@invitu Actually, I'd say there's a bunch of things with taxes that could be fixed in the POS, including:
https://github.com/odoo/odoo/issues/17963
https://github.com/odoo/odoo/issues/10538
https://github.com/odoo/odoo/issues/17526

**Comment by invitu** [comment]
@gustavovalverde could you please check this ? https://github.com/odoo/odoo/pull/17865

**Comment by pedrobaeza** [comment]
Closing as there's already an opened PR: #17865
