### ISSUE TITLE
Critical: users without an account(public users) can create infinite number of quotations in the system just by adding products to Cart from website.

### ISSUE THREAD

**Issue by anaghjose** [odoo/odoo#18201]
Impacted versions: Version: 10.0-20170712 confirmed. Probably present in older versions 

Steps to reproduce: Open up Odoo website(front end). as a public user add any one of the products into the cart,  go to  '/shop/cart' page and in the product quantity, instead of giving a integer number, give a random test string eg: 'sfsdgf'. refresh the quotations menu in the backend repetedly to see the quotations created

This will trigger deleting the sale order line of the corresponding order in the backend as the system assumes the quantity value to be non integer. 

For some reason the unlink call is happening recursively and if (only if) the user is non logged in(pubic user), quotations will be created and recursively and sale line is unlinked from them but the sale.order record will stay.

Current behavior: infinite number of quotations are created by a public user in the system (leave the page open, it can go on forever). the system will be flooded with quotations from public users(without any sale line)

Expected behavior: Not to create quotations infinitely 

Video/Screenshot link (optional):
![bug](https://user-images.githubusercontent.com/22314352/28152673-56d31c22-67bf-11e7-8fd8-f9530aa85e9f.png)

**Comment by Yenthe666** [comment]
Hi @anaghjose,

Thank you for your report.
I've just tried this on the latest Odoo 10.0 but was not able to reproduce this. Can you reproduce this problem on an official Odoo runbot instance (at runbot.odoo.com)?
CC @JKE-be 

Regards,
Yenthe

**Comment by JKE-be** [comment]
It has been fixed meanwhile.

Thanks for the report !

**Comment by wilfriedsip** [comment]
How this is fixed? We have the same problem with our Odoo 13. When a user without an account (public user) add something in the cart Odoo makes a quotation. How can we stop this.

**Comment by JKE-be** [comment]
It is the default behaviour since thé cart is a quotation !
If you are in v14 you can add groups on product(s) page to make it only visible by logged in user...
You can filter your quotation list view to hide public cart (quotation with website_id with partner_id = ‘public user’)
Thé bug reportéd here, and so fixed, was a Loop that generate several quotations at once for thé same user/cart

Kr
