### ISSUE TITLE
[9.0 Enterprise]: Leads get deleted after call of function: crm.lead2opportunity.partner search_read

### ISSUE THREAD

**Issue by Derter** [odoo/odoo#18207]
Impacted versions: [9.0 Enterprise]

We noticed the behavior of deletion of leads about 2 weeks ago. Since then I increased logging to be sure whats happening if a deletion happens again. Today the deletion of a huge amount of leads happened again. In the Logs I can see that the  crm.lead2opportunity.partner search_read function calls all the ID's of the Leads that get deleted afterwards.

Following a little abstract of the  crm.lead2opportunity.partner search_read call:

`017-07-13 07:15:47,849 14469 DEBUG DATABASE openerp.http.rpc.response: call_kw: crm.lead2opportunity.partner search_read: time:0.017s mem: 370544k -> 370544k (diff: 0k), [{u'__last_update': '2017-07-13 07:15:47',
  u'action': u'exist',
  u'display_name': u'merge',
  'id': 282,
  u'name': u'merge',
  u'opportunity_ids': [9323,
                       17533,
                       9796,
                       9795,
                       9794,
                       9793,
                       9789,
                       9788,
                       9787,
                       9786,
                       9785,
                       9784,
                       9783,
                       9781,
                       9779,
                       9778,
                       9777,
                       9775,
                       9774,
                       9772,
                       9771,
                       9770,
                       9769,
                       9768,
                       9767,
                       9766,
                       9765,
                       9764,
                       9763,
                       9762,
                       9761,
                       9760,
                       9759,
                       9757,
                       9756,
                       9755,
                       9754,
                       9753,
                       9752,
                       9751,
                       9750,
                       9749,
                       9748,
                       9747,
                       9746,
                       9745,`

and so on...

Short after I can see the deletion call in the logs. All of these ID's are listed in the search call above:

`2017-07-13 07:16:02,246 14469 INFO DATABASE openerp.models.unlink: User #1 deleted crm.lead records with IDs: [9164, 9165, 9166, 9167, 9169, 9170, 9174, 9175, 9183, 9184, 9185, 9186, 9188, 9192, 9195, 9196, 9199, 9200, 9203, 9204, 9206, 9208, 9209, 9210, 9212, 9213, 9214, 9217, 9219, 9223, 9226, 9227, 9228, 9229, 9230, 9231, 9232, 9233, 9240, 9241, 9242, 9243, 9244, 9245, 9246, 9247, 9248, 9249, 9250, 9251, 9252, 9253, 9254, 9255, 9256, 9257, 9258, 9259, 9262, 9263, 9265, 9266, 9267, 9268, 9269, 9270, 9273, 9274, 9275, 9276, 9277, 9278, 9279, 9282, 9283, 9284, 9285, 9286, 9287, 9288, 9289, 9290, 9291, 9292, 9293, 9295, 9296, 9299, 9300, 9301, 9302, 9304, 9305, 9307, 9309, 9310, 9311, 9312, 9314, 9320, 9321, 9326, 9330, 9331, 9333, 9335, 9337, 9339, 9340, 9341, 9343, 9345, 9347, 9348, 9349, 9350, 9351, 9354, 9356, 9358, 9362, 9363, 9364, 9367, 9368, 9369, 9370, 9371, 9373, 9374, 9375, 9377, 9379, 9380, 9381, 9382, 9384, 9385, 9386, 9390, 9391, 9393, 9394, 9395, 9396, 9397, 9399, 9400, 9401, 9402, 9403, 9404, 9407, 9409, 9411, 9412, 9413, 9414, 9415, 9416, 9417, 9418, 9419, 9420, 9421, 9422, 9423, 9424, 9426, 9427, 9428, 9429, 9430, 9431, 9433, 9434, 9435, 9436, 9437, 9438, 9439, 9440, 9441, 9442, 9444, 9445, 9446, 9447, 9449, 9450, 9451, 9454, 9457, 9458, 9459, 9463, 9464, 9466, 9471, 9472, 9473, 9474, 9476, 9478, 9479, 9481, 9483, 9484, 9485, 9486, 9488, 9489, 9490, 9496, 9497, 9508, 9509, 9510, 9512, 9513, 9514, 9515, 9516, 9517, 9518, 9519, 9520, 9521, 9522, 9523, 9524, 9525, 9526, 9527, 9528, 9529, 9530, 9531, 9532, 9533, 9534, 9535, 9536, 9537, 9538, 9539, 9540, 9541, 9542, 9543, 9544, 9545, 9546, 9547, 9549, 9550, 9551, 9552, 9553, 9554, 9555, 9556, 9557, 9558, 9559, 9560, 9561, 9562, 9566, 9568, 9569, 9571, 9572, 9574, 9577, 9579, 9581, 9582, 9585, 9586, 9587, 9588, 9589, 9590, 9592, 9595, 9596, 9597, 9598, 9600, 9604, 9607, 9609, 9611, 9613, 9615, 9617, 9619, 9622, 9628, 9629, 9631, 9632, 9641, 9644, 9645, 9646, 9650, 9651, 9653, 9654, 9655, 9656, 9657, 9658, 9659, 9660, 9662, 9663, 9664, 9666, 9667, 9668, 9670, 9672, 9673, 9674, 9675, 9677, 9678, 9679, 9680, 9681, 9682, 9683, 9684, 9685, 9686, 9687, 9688, 9689, 9690, 9691, 9692, 9693, 9694, 9695, 9696, 9697, 9698, 9699, 9700, 9701, 9702, 9703, 9704, 9705, 9706, 9708, 9709, 9710, 9711, 9712, 9713, 9715, 9716, 9717, 9718, 9721, 9722, 9725, 9731, 9732, 9733, 9734, 9735, 9737, 9739, 9740, 9741, 9742, 9743, 9745, 9746, 9747, 9748, 9749, 9750, 9751, 9752, 9753, 9754, 9755, 9756, 9757, 9759, 9760, 9761, 9762, 9763, 9764, 9765, 9766, 9767, 9768, 9769, 9770, 9771, 9772, 9774, 9775, 9777, 9778, 9779, 9781, 9783, 9784, 9785, 9786, 9787, 9788, 9789, 9793, 9794, 9795, 9796, 17533, 9264, 9298, 9322, 9323, 9327, 9355, 9495, 9500, 9640]`

We cannot live with such an behavior of Odoo deleting hundreds of leads without our action. Im looking forward to see a fast reaction for our issue so that we can have a prompt fix of the behavior.

**Comment by Yenthe666** [comment]
Hi @Derter,

Thank you for your report.
I miss one thing though. You're stating what is happening but not how to reproduce this. Can you reproduce this on an official Odoo instance? (runbot.odoo.com).
Could you please update your Odoo to the latest source code and test again?

Regards,
Yenthe

**Comment by Derter** [comment]
Hi @Yenthe666,

thanks for your answer. 

Its not reproduceable since we dont know what exactly is executing the deletion. I guess the functions is called when you create an opportunity out of a lead. 

The function crm.lead2opportunity.partner search_read is called many times in the log but only one time it has that many ID's that afterwards get deleted. 

I was hoping that this behavior might have occurred already.


This is the version we are commit we care currently sitting on:

commit 4c79aa8d9d57a4e7e5cde083d3f8fb755e0a8693
Author: Martin Trigaux <mat@odoo.com>
Date:   Mon Mar 13 15:56:45 2017 +0100

**Comment by Yenthe666** [comment]
Hi @Derter,

Can you please try updating your Odoo first and try to reproduce this on a runbot? Without this there is little we can do.. 😞

**Comment by Derter** [comment]
Hi @Yenthe666,

i tried reproducing it but since i have no access to logs whatsoever I have no clue whats really going on on the server and if a deletion call is sent.

Furthermore I cannot find opporturnities on odoo 9 community.

**Comment by Yenthe666** [comment]
Hi @Derter,

You have to configure this under `Sales` > `Settings` to allow leads on a runbot.
If you don't have acces to the logs / server then please ask your partner (or contact) to update and verify this.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @Derter,

Do you have any additional info?

**Comment by Derter** [comment]
Hi @Yenthe666,

we were in contact with the odoo technical enterprise support which could not help us either. They checked the server and saw mutliple third party addons. They insisted on the fail of a user converting multiple leads and thus deleting them. We couldnt reproduce this on runbot.

**Comment by Yenthe666** [comment]
Thank you for the extra info. Best of luck with Odoo!
