### ISSUE TITLE
[9.0] stock: MTO picking lines are reserved with other material if any

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#18209]
Impacted versions: 9.0

Steps to reproduce:

* Create an MTO product with 
  * Product Type: Stockable Product
  * Routes: "Buy" and "Make to Order"
* Update Qty on Hand to any quantity (i.e, 2).
* Create a sales order with this product and a number <= to the one in the step before.
* Confirm the sales order.

Current behavior:

The created delivery picking appears in state "Reserved" and the current quantity on stock has been reserved, allowing you to transfer that stock.

Expected behavior:

The created delivery picking should be in "Waiting another operation", or at least in "Waiting availability" until the purchase order is confirmed (if you have defined a supplier for the product and the procurement creates the purchase order), which seems to be the current behavior when there's no stock available (is this also correct, as it allows to manually reserve?).

**Comment by pedrobaeza** [comment]
@jco-odoo I think this one is for you. If you don't have time right now, just tell me and I'll investigate the PR, but this is as you have more fresh everything stock related and you will need less time.

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by jco-odoo** [comment]
Indeed, it should be waiting another operation.  But has not this been corrected already?

**Comment by pedrobaeza** [comment]
I have just tried on runbot before putting the issue.

**Comment by pedrobaeza** [comment]
On v10 is not happening. Only in v9.

**Comment by sle-odoo** [comment]
rev https://github.com/odoo/odoo/commit/8d65763f935dcc6483278a6aecd2039e41974773 indeed landed only in v10

**Comment by jco-odoo** [comment]
@nim-odoo

**Comment by pedrobaeza** [comment]
I have backported the fix to v9 in https://github.com/odoo/odoo/pull/18376. Can you please review?

**Comment by Yenthe666** [comment]
Should be fixed in https://github.com/odoo/odoo/commit/e2a255717fb941fffa1fcc8ed0c5e390fba76618
