### ISSUE TITLE
starred message update - unstar it for example

### ISSUE THREAD

**Issue by wpichler** [odoo/odoo#18204]
Impacted versions: 10.0
Steps to reproduce: Star a message - then click it again to unstar it.
Current behavior: UI does not update, after a reload you will have the correct result
Expected behavior: UI should update immediately

**Comment by Yenthe666** [comment]
Hi @wpichler,

Thank you for your report.
I've just tested this on the latest Odoo 10 (starring and unstarring without refreshing) and it works fine out of the box.
Please update your Odoo codebase and try again.

Regards,
Yenthe
