### ISSUE TITLE
Odoo 10E: Consumable Items Showing as stocked

### ISSUE THREAD

**Issue by ChemHseOz** [odoo/odoo#18216]
Impacted versions:

Steps to reproduce:
Stars with a stocked item that has had past transactions therefore has a possible/negative stock level. The stock item is then changed to consumable (ie decide it is no longer necessary to track stock levels of that particular product/item). I call this a previously stocked/now consumable item (PSNCI).

Current behaviour:
Once the above occurs, the BOMs using the PSNCIs continue to draw stock. Once the PSNCI stock levels 
 goes negative, the various views highlight the consumable item as red (out of stock). More importantly the manufacturing orders hold the order waiting for a positive stock level unless you force availability (which only makes the stock level more negative).

When viewing products, these PSNCI show a stock level. The forecasted stock level also behaves as if the product was still being stocked.

If I change back to "stocked item" and set inventory level to zero, and then switch back to "consumable", the stock levels goes negative on the next manufacturing order using that item.

Expected behaviour:
Inventory related movements should not occur once the stock is set to consumable.

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
Consumables do have quants from version 8 to 10. If you never buy them, it's normal they go into negative. This is not the case anymore.

Regards
