### ISSUE TITLE
Accounting dashboard Vendor Bill journal shows the total ammount in the "payments to do" section instead of the "to pay" ammount

### ISSUE THREAD

**Issue by BeAntares** [odoo/odoo#18217]
Impacted versions: 10

Steps to reproduce: When partial payments are performed on vendor bills, the Accounting dashboard shows the total amount to pay including the quantity already paid instead of the remaining amount to pay.

Current behavior: When partial payments are performed on vendor bills, the Accounting dashboard shows the total amount to pay including the quantity already paid instead of the remaining amount to pay.

Expected behavior: The dashboard should show the amount to pay instead of the total amount of the vendor bills. 
The fix #13568 for version 9 could work for version 10. Instead of adding up the amount_total field, residual_signed field should be added.

Video/Screenshot link (optional):

**Comment by celm1990** [comment]
Hello,

Any solution???.

Fix  #13568 must be ported to V10, it work fine

**Comment by BeAntares** [comment]
@Yenthe666 There is a pull request ( #19047) that solves this issue. Do you know who can review that.

**Comment by pedrobaeza** [comment]
Closing as there's already an opened PR for this: #19047
