### ISSUE TITLE
[9.0] decimal_point and thousands_sep on clean db always on default format

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#18236]
Impacted versions:
9.0

Steps to reproduce:
1.- Create a new db
2.- select another country an language( ie. Chile, and spanish(Chile)),
4.- install some modules (i.e sales)
5.- activate debug mode
6.- go to configuration > translations > languages

Current behavior:
decimal_point == .
thousands_sep == ,

Expected behavior:
use idiom default config
decimal_point == ,
thousands_sep == .

**Comment by JKE-be** [comment]
Please give more information

Thanks

**Comment by Yenthe666** [comment]
Hi @dansanti,

Can you please explain in more detail what you want/expect? The topic is not very clear (to me).

Regards,
Yenthe

**Comment by dansanti** [comment]
I'm sorry, it's a problem with locales
