### ISSUE TITLE
[18.0] website_sale_wishlist: Combo products saved to wishlist and added to cart don't work

### ISSUE THREAD

**Issue by jtoktas** [odoo/odoo#182464]
### Odoo Version

- [ ] 15.0
- [ ] 16.0
- [ ] 17.0
- [ ] Other (specify)

### Steps to Reproduce

- Add combo product to cart with choices
- At checkout click save for later
- Click on wishlist and add the saved item back to cart
- Combo product loses it's choices and price

Expected behaviour :
Combo product retain it's chosen values and price when saved. 

Bonus. 
If the combo info is saved maybe we can even get an 'edit combo' button so customers can edit the combo choices after.

**Comment by ltinel** [comment]
Thanks for spotting this. We'll investigate whether we want to support combos in the wishlist, but for now, we'll disallow it.

**Comment by ltinel** [comment]
Fixed with https://github.com/odoo/odoo/pull/182807
