### ISSUE TITLE
[8.0] no "bigger/smaller than" Filter Search on e.g. ZIP / Postcode

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#1825]
Hello,

in 6.1 it was possible to do an extended search like
postcode "bigger than" 1000
postcode "smaller than" 1100
although it's just a char field.

In 7.0 and 8.0 those bigger/smaller options are missing for e.g. postcode, but it would be quite helpful.

with kind regards,
Sven

**Comment by Yenthe666** [comment]
Hi @svenpetersen,

Thank you for the report. 6.1 and 7.0 are no longer supported by Odoo (as we only support three versions back) but you could easily do this with advanced filters. For example to find all invoices with a total bigger than 100€:
![image](https://user-images.githubusercontent.com/6352350/27579854-3c639cce-5b29-11e7-948b-98f8cd6bb758.png)

Regards,
Yenthe
