### ISSUE TITLE
[9.0,10.0] Should not allow users to change product in stock moves of duplicated picking associated to sale order

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#18250]
Impacted versions:9.0, 10.0

Steps to reproduce:
1.Install module sale_stock
2. Create a sales order containing a stockable product
3. Confirm the SO
4. Duplicate the picking
5. Change the product in the new picking

Current behavior:
The stock move that was changed by the user continues to point to the procurement associated to the sales order line. But now there's an inconsistency between the product ordered, and the product delivered, for the same SO line.

When the picking is completed, the SO lines shows a value in field 'Qty Delivered' that may be related to a totally different product, mixing oranges and apples.

Expected behavior:
It makes sense that the users may want to duplicate a picking that has been created from a sale order, but there should be a constraint in the stock move to ensure that the product of the stock move matches with the product of the related sales order line.

Will submit a separate PR.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thankyou for your report.
Just a tip: if you make a PR you don't have yo create an issue too. Just create a PR with all yhe information about how to reproduce it and what it fixes.
That being said, @jco-odoo could you have a look at the PR please? It looks good to me.

**Comment by jbeficent** [comment]
Closing the issue, as the PR would probably not address the issue correctly.

I guess that the root cause of the problem is another. 

In my use case users are unable to change the source location after the sales order has been confirmed. It usual for shipping to decide that a product will be sourced from a different location/warehouse once the sales order has been confirmed, if they realize that there are stockouts in the proposed location. This should not require the cancellation of the sales order, since often the terms with the customer will not change in case that the product is sourced from another place.

At this moment the only way to resolve this issue is to cancel the picking provided by the sales order, and duplicate it into a new one, where one can change the source location.
