### ISSUE TITLE
[10.0] Permissions: Portal user cannot access Project/Tasks

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#18252]
Impacted versions: 10.0

Steps to reproduce:
1. Create new database
2. Install Project App
3. Install Contacts Directory App
4. Create new customer contact, set email address
5. Create new project, Privacy: Visible by following customers or On invitation only
6. Create project tasks
7. Add contact from step 3 to Customer and to Followers
8. Allow external users to sign up (General Settings)
9. Add Contact Creation permission to administrator
10. Add portal acces to customer from step 3
11. Log in as Customer
12. No project in menu, unable to access project and project tasks

Current behavior:
Permission error, portal user cannot view Project and Tasks information

Expected behavior:
Portal user can access project and project task information, write messages in chatter, create new tasks

Video/Screenshot link (optional):
https://youtu.be/RITa1ddW8ec

**Comment by jem-odoo** [comment]
Hello,

To access project and task as portal user, you have to install website_project module. This provide the customer portal in which you can find all your documents (sale order, project, issues, invoices, ...).
Portal users should not access '/web' page anymore, this is empty for them.

Regards

**Comment by Dax1900** [comment]
I think you have to invite the customer to follow the project. That puts the external user to the project user permission group without making it an internal user.
