### ISSUE TITLE
Is there any Idea about developing GSTR1 formats to upload bulk invoices to the GST system for at least Enterprise Edition?

### ISSUE THREAD

**Issue by muralikrishnareddy** [odoo/odoo#18271]
Impacted versions: 9.0, 10.0

Steps to reproduce: INDIA GST, not found any module for GSTR1 excel

Current behavior: GSTR1 excel Not Available

Expected behavior: Shall be able to generate GSTR1 excel formats based on customer's company 
[GSTR1_Excel_Workbook_Template-V1.0.xlsx](https://github.com/odoo/odoo/files/1152496/GSTR1_Excel_Workbook_Template-V1.0.xlsx)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo I think you can give a quick reply on this. Anything on the planning for India GST and GSTR1?

**Comment by qdp-odoo** [comment]
@hmo-odoo anything in "RD India" project for that?

**Comment by hmo-odoo** [comment]
@qdp-odoo we are working on it for master version.

**Comment by Yenthe666** [comment]
Hi @muralikrishnareddy,

So this should land in V11 then. I guess this answers your question. 😉 

Regards,
Yenthe
