### ISSUE TITLE
Creating many2one linking to ir.model.fields inside a One2many throws ValueError

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#18295]
Impacted versions: 10.0, probably all others too.

Steps to reproduce:
1. Create a new model (in my example `project.task.settings`)
2. Create a `many2one` from your new model to `ir.model.fields`. Add in another custom field. Your code should look something like this:
```
# -*- coding: utf-8 -*-

from odoo import models, fields, api, _


class ProjectTaskSettings(models.Model):
    _name = 'project.task.settings'
    field_ids = fields.Many2one('ir.model.fields', domain=[('relation','=', 'project.task')])
    show_in_portal = fields.Boolean(string='Show in portal')
```
3. Inherit an existing model or add a new one and add a `one2many` to the just created `many2one` (in my example `field_ids`). Your code should look something like this:
```
# -*- coding: utf-8 -*-

from odoo import models, fields, api, _


class ResUsers(models.Model):
    _inherit = 'res.users'
    project_task_fields = fields.One2many('project.task.settings', 'field_ids')
```
4. Inherit or create a view in which you add the `many2one` with the `one2many` inside it. My example:
```
<odoo>
  <data>
    <!-- ========== [ INHERIT VIEW : RES.USER ] ========== -->
    <record id="view_user_form_inherit_rebus" model="ir.ui.view">
      <field name="name">res.user.form.inherit.rebus</field>
      <field name="model">res.users</field>
      <field name="inherit_id" ref="base.view_users_form"/>
      <field name="arch" type="xml">
          <xpath expr="//page[last()]" position="after">
              <page name="portal_settings" string="Portal settings">
                <group name="project_taks_settings" string="Course settings">
                    <field name="project_task_fields">
                        <tree string="Courses" editable="bottom">
                          <field name="field_ids"/>
                            <field name="show_in_portal"/>
                        </tree>
                    </field>
                </group>
              </page>
          </xpath>
      </field>
    </record>
  </data>
</odoo>
```
5. Install your module, go to the view and click on add record. You'll now get a `ValueError`:
![image](https://user-images.githubusercontent.com/6352350/28310511-ffeb6e7c-6bac-11e7-8889-6d2e2ee99e4c.png)
You can find an example module to quickly reproduce this here: https://github.com/Yenthe666/ir_model_fields

Current behavior: `ValueError` when creating a `many2one` and `one2many` relation that links to `ir.model.fields`.

Expected behavior: You can select records and add them.

**Comment by Yenthe666** [comment]
@mart-e this is the whole case with a minimum coding example to reproduce.

**Comment by mart-e** [comment]
Ok, I have found your issue:

```python
    project_task_fields = fields.One2many('project.task.settings', 'field_ids')
```

The inverse of your one2many is not `field_ids`

**Comment by Yenthe666** [comment]
Yep, that was very stupid. Sorry!
