### ISSUE TITLE
[10.0] Uploading large file crash Chromium/Google Chrome

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#18293]
Impacted versions: 10.0, works good on 8.0
Google Chrome: Version 59.0.3071.109 (Official Build) (64-bit)

Steps to reproduce:
1. Activate the developer mode
2. Settings -> Technical -> Database Structure -> Attachments -> Create
3. Upload 20mb file.
4. Google Chrome crash

Current behavior:
Google Chrome crash

Expected behavior:
File uploaded

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5862658/28307784-5b5802e2-6ba4-11e7-933a-84d15bda230b.png)

**Comment by lukebranch** [comment]
@grzekru ,

What are the specs of the machine you are on?

**Comment by grzekru** [comment]
@lukebranch 
Machine 1:
Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
8 gb ram
128gb sdd

Machine 2:
Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
64gb ram
256gb sdd

Both running on ubuntu 16.04

**Comment by Yenthe666** [comment]
Hi @grzekru,

Thank you for your report.
I've just tested this on the latest Odoo 10 with a file that is 369MB and it now gives a proper warning:
![image](https://user-images.githubusercontent.com/6352350/34440725-6438ef86-ecb7-11e7-9176-8dc3b3af7eaa.png)
Please update your Odoo to the latest codebase and you'll have this fixed too.

Regards,
Yenthe
