### ISSUE TITLE
[10.0] Sale Price calc error

### ISSUE THREAD

**Issue by daimengmeng** [odoo/odoo#18303]
Impacted versions:  
versions: 10.0

Steps to reproduce:
1.  1 price list with 2 price list items A and B, each one have difference date range, say  A is early than B
2.  assign the price list to partner 1
3.  create a sales order for partner 1, and set the order date during the date range of B,
4.  it update the price according to A not to B

Current behavior:
1, get price not following date range

> It seemed that have not passed the date when  onchange product_uom.

Expected behavior:

Video/Screenshot link (optional):
![sale_order](https://user-images.githubusercontent.com/13128021/28320224-966ba7e0-6c02-11e7-8866-4fc8793d9352.gif)

**Comment by GoodERPJeff** [comment]
talk is cheap, show me the code

**Comment by jeffery9** [comment]
https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L919

**Comment by msntop** [comment]
吊吊的

**Comment by mart-e** [comment]
Hello,

Thank you for the report. You are totally right, this was broken in 9.0.
Thanks Jeffery for the patch.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/60d46345444fcb268d1846d30963e63adcba98c0

**Comment by jeffery9** [comment]
@mat-e  this effected 10.0 too.

**Comment by Yenthe666** [comment]
@jeffery9 no worries, it'll be forward ported to newer versions (usually takes a good week)

**Comment by mart-e** [comment]
Indeed, it will be forward ported. I have added at test at a03eb9a3e8f625fc2f68dad8e9ef653329fb568f to make sure it does not happen again.
