### ISSUE TITLE
[16.0] web: Impossible to set multiple DatePicker with different granularity

### ISSUE THREAD

**Issue by AnizR** [odoo/odoo#183226]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

## Context:
This issue was discovered when attempting to implement a date range filter (from date X to date Y) in a Dashboard (similar to what exists in odoo version 17 and 18). Despite configuring one `DatePicker` for day-level selection, it was forced into year selection mode due to the presence of the `YearPicker` filter. This issue is not specific to dashboards but applies across Odoo wherever multiple date pickers with different granularities are used together.

## Impact:
When using Odoo 16.0, the `YearPicker` component globally sets `MinViewModeNumber`, which forces all `DatePicker` components on the same page to share the same selection granularity (e.g., years only). As a result, if a `YearPicker` is present, it becomes impossible to configure other `DatePicker` instances to select days or months.

## Steps to Reproduce:

1.  Add a `DatePicker` in an Odoo view to allow users to select a specific date (day, month, year).
2.  Add a `YearPicker` on the same page, which restricts selection to years.
3. The global `MinViewModeNumber` is set by the `YearPicker` in `odoo/addons/web/static/lib/tempusdominus/tempusdominus.js`.
4. All `DatePicker` instances on the page inherit this global setting, limiting them to year selection only, even if they should allow day or month selection.

## Solution:
The problem has been discovered and is already patched, here is the issues with the related merge request on the library tempusdominus: https://github.com/tempusdominus/bootstrap-4/issues/133

### Log Output

```shell
--No real logs--
```
## Observed Behavior:
Once the `YearPicker` is initialized, it sets the global `MinViewModeNumber` variable, which restricts all other DatePicker components on the page to year-only selection. This overrides any specific configuration passed to those date pickers.

**Comment by acsonefho** [comment]
@ged-odoo :pray:

**Comment by IT-Ideas** [comment]
Hello the JS team 🤘🏼 (@aab-odoo @ged-odoo)
Could you possibly update the lib?
Thanks!

**Comment by pparidans** [comment]
This issue has been fixed in https://github.com/odoo/odoo/pull/186339

Thank you for your feedback :+1:

**Comment by IT-Ideas** [comment]
> This issue has been fixed in #186339
> 
> Thank you for your feedback 👍

Thanks @pparidans !
