### ISSUE TITLE
Search method for product.product qty_available field not working correctly

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#18336]
It seems like something might be wrong with the search method on the `qty_available` field on the `product.product` model:

https://github.com/odoo/odoo/blob/saas-14/addons/stock/models/product.py#L270

If I have search for products with `qty_available <= 5`, products with `qty_available = 0` are not included in the results.

For example, if I have the following products:

Product A -> qty_available = 0
Product B -> qty_available = 0
Product C -> qty_available = 5

The following domain will return only Product C:
```
[('qty_available', '<=', 5)]
```

This seems like a bug.

**Comment by intero-chz** [comment]
No wonder, the search is done on `stock.quant`. There won't be a product without quants  (qty = 0) in the result, because there are no 0 quants.

**Comment by Yenthe666** [comment]
Yep indeed - so in my opinion this isn't a bug.
@mart-e the decision is up to you. 😉

**Comment by intero-chz** [comment]
As user (black box) i would expect finding products with zero quantity on hand. So for me this is a bug. But yes, not my decision either.

**Comment by flyingL123** [comment]
From a user's perspective, this is absolutely a bug in the sense that it doesn't function as you would expect. I have the `qty_available` field visible in my `product.product` tree view, so I see the on-hand quantity for every product. Some of them are 0. If I filter that list to show products with on-hand quantity less than a certain number, I fully expect the products with 0 to appear in that list.

**Comment by flyingL123** [comment]
Also, if I filter for products that have `qty_available == 0`, then the products with 0 appear correctly. This seems inconsistent in the sense that the products with 0 shouldn't appear sometimes but not others.

**Comment by masterdungeon** [comment]
How can i access qty_available in pos ? and how to display it in each product?

**Comment by Yenthe666** [comment]
@masterdungeon don't hijack other threads to ask questions. Please ask these kind of questions on the official help forum (help.odoo.com).

**Comment by masterdungeon** [comment]
( help.odoo.com ) gives server error. Can you solve my problem?

**Comment by Yenthe666** [comment]
There is actually currently a bug in the forum, it should be fixed soon.
