### ISSUE TITLE
[10.0] Stock inventory security error in multicompany and multi language

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#18334]
Impacted versions: 10

Steps to reproduce:

Create new database with demo data.
Create new company, (not child of default companies)
Create new user and give all companies access.
Install stock module.
Do and inventory in default company with one product variant (p.e. ipad) and initialize it.
Change to the new company, and do the same inventory of the same product: No problem.
Now if you load a new language in configuration menu and repeat the inventory in the new company with the same product, we get a security error.
Current behavior:
Security error when we have more than a language.and we try to create a inventory line when in the other company already exists one with the same product.

Expected behavior:
No security error.

Comments
A solution is to put related field product_name in inventory_line as readonly.
When we have more than a language, the _write() method do a explicit write of related product_name in inventory_line. Because of it is a related field, it triggers the recompute in the other inventory_lines belonging to the other companies, so we got the security error.

**Comment by pedrobaeza** [comment]
This has been handled in commit https://github.com/odoo/odoo/commit/d6d901c7bc23c7aaafd09c2abccfbe6a7c963b70
