### ISSUE TITLE
[bug] product 's  cost price is incorrect when bom's type is phantom

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#18349]
Impacted versions:
10.0
Steps to reproduce:
product name : A cost price: 40
product name: B cost price : 100  It have a phantom nom, 1 B = 3 A .

I create a purchase order, details is 1 B , price: 100.
I confirm this purchase order , a stock picking  was created.
I confirm  stock picking. 
Current behavior:
I query Inventory Valuation: 
A quantity :3  valuation: 120.

**I think valuation is 100,not 120.**
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback? I'm not sure..

**Comment by jeffery9** [comment]
if use real price or average price.  this cost should be updated with 100, not the standard price 120

**Comment by fmdl** [comment]
Dear 

I have made a PR to be sure the purchase price is distributed on the move price, but is not accepted.

https://github.com/odoo/odoo/pull/15350

**Comment by sum1201** [comment]
@Yenthe666 @jco-odoo

**Comment by jco-odoo** [comment]
You can not know how the costs are divided among the different products.  The logic would bring us too far.
