### ISSUE TITLE
Tags titles are not displayed properly on the kanban view of applications

### ISSUE THREAD

**Issue by gva-acsone** [odoo/odoo#18345]
Impacted versions: V10

Steps to reproduce:
- Create a new application
- Add a tag on this new application
- Move to the applications kanban view and check the application juste created

Current behavior:

We see a grey bar that indicates that a tag is present, but we don't see the tags label/title as we could see in V8

Expected behavior:
The grey bar is present and we can see the tag label directly from the kanban view, without having to put our mouse on the grey bar. 

Video/Screenshot link (optional):

![sans titre 2](https://user-images.githubusercontent.com/22000568/28405651-b89a6ae6-6d2d-11e7-899c-b65da5f8b899.png)
![sans titre](https://user-images.githubusercontent.com/22000568/28405650-b889a120-6d2d-11e7-8c64-5a4fc6ca2874.png)

**Comment by gva-acsone** [comment]
755952

**Comment by zeusflp** [comment]
pudiste solucionar el problema?
