### ISSUE TITLE
[17.0] l10n_hu_edi: _parse_error_response fails to extract error messages

### ISSUE THREAD

**Issue by gezzzan** [odoo/odoo#183425]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Reproduce:
- Add a bank account to your HU invoice issuing company with an invalid syntax (eg: 1234567812345678)
- Tryt to report the invoice to NAV

A correct bank account syntax in HU is either IBAN format or 2 or 3 times 8 numbers separated by dash "-". So in this example 12345678-12345678 would be acceptable.

The NAV manage invoice message fails, but there is no meaningful reason is extracted by _parse_error_response  method, we see: 

_Invalid Operation_
_A számlát a NAV elutasította._
_- (None) None: None_
_- (None) None: None_
_- (None) None: None_

Maybe in case of error the meaningful part of the response xml could be extracted as an attachment and linked to the invoice

thanks for looking into this

**Comment by chklop** [comment]
https://github.com/odoo/odoo/pull/184470/
