### ISSUE TITLE
[10.0] website_live_chat: Chrome lang spanish Latin America (es_419), Faild to create mail channel (opw-766489)

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#18363]
Impacted versions:
10.0

Steps to reproduce:
From Chrome Versión 59.0.3071.115 (Build oficial) (64 bits)
with lang  spanish Latin America es_419
Go to http://247698-10-0-f3ee58.runbot8.odoo.com/?db=247698-10-0-f3ee58-all

Current behavior:

```python
2017-07-20 16:21:02,024 10584 INFO 247698-10-0-f3ee58-all odoo.sql_db: bad query: INSERT INTO "ir_translation" ("id", "lang", "src", "name", "type", "value", "state", "res_id") VALUES(nextval('ir_translation_id_seq'), 'es_419', 'Visitor, Administrator', 'mail.channel,name', 'model', 'Visitor, Administrator', 'translated', 81) RETURNING id
```
Expected behavior:
Chat being open

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10233975/28430589-aa27e01a-6d46-11e7-82fc-18473bcf0e5e.png)

**Comment by Yenthe666** [comment]
Hi @hugho-ad,

Just to double check. Which spanish version from this list?
![image](https://user-images.githubusercontent.com/6352350/28511352-1b19e3fa-704d-11e7-80e1-c5139b82fc9d.png)
I've tested on the runbot you've linked but that works fine.

Regards,
Yenthe

**Comment by hugho-ad** [comment]
Sure, it's `Spanish/Español` I think is the generic one, but I think the problem is that odoo itselft does not support  lang spanish Latin America( es_419)

My chrome lang configuration looks like the follow
![image](https://user-images.githubusercontent.com/10233975/29387362-63d4cee2-82a5-11e7-9f30-b827f218bc4c.png)

When trying to open the live chat, next error is shown and the chartter is not displayed
![image](https://user-images.githubusercontent.com/10233975/29387405-82090de2-82a5-11e7-8b1f-d9dec5214af7.png)

And lang es_419 are not in the languages list
![image](https://user-images.githubusercontent.com/10233975/29387489-db1b030e-82a5-11e7-8e2e-2ab10f174e7c.png)

**Comment by hugho-ad** [comment]
Just for the record, this issue could be solved when we add the languege es_419
![image](https://user-images.githubusercontent.com/10233975/29387761-41256008-82a7-11e7-8d08-2a8353287f14.png)

**Comment by Yenthe666** [comment]
@mart-e could you look at this?

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/6879409723184ed360043b7a2da11fcd725e5c4f

**Comment by hugho-ad** [comment]
This fix causes the following problem

keeping  lang es-419 in chrome browser
First Open the live chat from website , be sure  you are not logged in (guest user)
- Second, Sign up/ Sign in
**- The live chat channel is not displayed**
- Finally logout and you will be able to see the live chat channel
![image](https://user-images.githubusercontent.com/10233975/31291974-3697eb52-aa97-11e7-9464-a1de278bbb94.png)

At the runbot log
![image](https://user-images.githubusercontent.com/10233975/31291995-56cf471c-aa97-11e7-8851-7eb2e9345cb1.png)

RUNBOT INSTANCE http://269567-10-0-b80c7b.runbot9.odoo.com/

**Comment by kebeclibre** [comment]
@hugho-ad 
@odony 
This issue doesn't seem to be linked with the language though.
It has to do with the request ID and the im_livechat cookie

im_livechat.js:L42
if no cookie: just initiate the chatter
If you open the livechat while being a public user it will, (thanks to im_livechat/controllers/main.py:L41) as the administrator

Now, log in as a user, whichever except admin
There is a cookie, so this line will be called:
mail/bus.py:L51
The problem is, we basically do a sudo(portal_user_id), which cannot see the channel created earlier.

I will be working on a fix, but the obvious workaround is
- do not start a livechat session when in public user (log in as your user beforehand)
- if you do anyway, erase the cookie (like with the google chrome extension EditThisCookie)
       Since you can erase the particular cookie that triggers the chain of events, you won't even have to re-login

**Comment by SalahAdDin** [comment]
It is still happening in `Odoo 12.0`.
