### ISSUE TITLE
Installed but does not appear in chart of account configuration.

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#18373]
Impacted versions:10

Steps to reproduce:does not appear in chart of account

Current behavior:does not apper

Expected behavior:does not see any behaviour

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @odoouser2,

Thank you for your report but we really miss information to reproduce this.
What did you do? What did you install? What happens?

Regards,
Yenthe

**Comment by odoouser2** [comment]
I have installed "United States - Accounting" module from the app. Module is installed without error but it does not appear in the Account >>setting>> Chart of Account.

**Comment by Yenthe666** [comment]
I'm not sure what your problem is? I've just tested this on the latest Odoo source code and it works perfect. Just installed the accounting and you can see it is working fine. Fiscal positions etc are added:
![image](https://user-images.githubusercontent.com/6352350/28563808-5c4b0d74-7127-11e7-8af1-df6932b8d2c0.png)
Chart of accounts (under accounting > Adviser > Chart of accounts):
![image](https://user-images.githubusercontent.com/6352350/28563957-e166a27a-7127-11e7-8a43-3b32594b9e9c.png)

So, what exactly is your issue?

Regards,
Yenthe

**Comment by odoouser2** [comment]
Hello,
Greetings,

I use odoo V10 Community edition. I have installed "United States - Accounting" but it does not appear in the Account >>setting>> Chart of Account template..

**Comment by Yenthe666** [comment]
Hi @odoouser2,

It is exactly the same case on V10 community? Example:
![image](https://user-images.githubusercontent.com/6352350/28565878-cdecc606-712d-11e7-840a-671aa3718e85.png)

Regards,
Yenthe

**Comment by odoouser2** [comment]
Hello,
Greetings,

I use odoo V10 Community edition. I have installed "United States - Accounting" but it does not appear in the Account >>setting>> Chart of Account template
Attached is the details.
![coa](https://user-images.githubusercontent.com/21218238/28703070-261eabbe-7381-11e7-81a3-23487e5394af.jpg)

Installed the module but unable to assign to the company.


![coa1](https://user-images.githubusercontent.com/21218238/28703071-26238d64-7381-11e7-8886-b3e0ebb309a1.jpg)

**Comment by Yenthe666** [comment]
@mart-e and @qdp-odoo could you give feedback? If I'm not mistaking he wants to assign different chart of accounts to multiple companies, which I think is not possible? Or am I wrong? 😟

**Comment by mart-e** [comment]
No it is possible. You switch company go to Accounting > Settings > Install more chart templates as whon in the screenshot.

**Comment by odoouser2** [comment]
Hello, 
Greetings,

I switched the company, went to accounting settings. I am able to get other chart of account that I install but is unable to get the United state chart of Account.
Please assist me.

Thank you.

**Comment by odoouser2** [comment]
Hello, 

Greetings,

 

I switched the company, went to accounting settings. I am able to get other chart of account that I install but is unable to get the United state chart of Account.

Please assist me.

 

Thank you.

 

Possibilities : Unlimited; 

Shivendra Thakur 
Kathmandu, Nepal 
M: 9844297010

**Comment by mart-e** [comment]
Oh I see. No you can use the configurable chart of accounts. There is no specific chart for the US, it is the default one.

**Comment by pradip2503** [comment]
How can i delete configurable chart of accounts and reinstall chart of account?
