### ISSUE TITLE
[9.0,10.0] Security error in many2many widget

### ISSUE THREAD

**Issue by adomingo-rgbconsulting** [odoo/odoo#18372]
Impacted versions:
9.0,10.0

Steps to reproduce:

1. Install the point_of_sale module

2. Define a secondary Point of Sale (apart from the main one)

3. Create a new user with full permissions in the Point of Sale

4. Login with the new user and go to Point of sale > Reports > Sale Details

Current behavior:
In the report wizard, both Point of Sales are preloaded in the many2many list and the user cannot remove them.

Expected behavior:
The user should be able to remove Point of Sales from the list in order to print a sale details report of a single point of sale.

This issue can be reproduced in any many2many list where the user doesn't have delete permissions on the referenced model (in this case pos.config).

The behavior only affects the default many2many widget. Other widgets, like many2many_tags, do not have this issue.

**Comment by pedrobaeza** [comment]
Hi, I'm not able to reproduce this problem in latest v11, so I consider that it has been solved, although not on the target version, and I'm going to close this issue.

If you have an enterprise contract, you can open an OPW ticket to see if the bugfix team can fix the problem in v10.
