### ISSUE TITLE
Partial access in custom module for model

### ISSUE THREAD

**Issue by AhsanAshfaq** [odoo/odoo#18383]
Hi,

Is this possible is odoo that we grant edit access to a model in one view but not in over all system. Because as per my knowledge if you grant any of CRUD access to a particular group or user. It will be applied on all views in your system. I want user to be able to edit a record of model only if he is in a specific view.

**Comment by Yenthe666** [comment]
Hi @AhsanAshfaq,

The Github issue tracker is for bugs/issues in the official code, this is not the place to ask questions.
You can do this on the official help forums @ http://help.odoo.com/
On a sidenote: you can do this with access rules and `create=False` keys for example.

Regards,
Yenthe
