### ISSUE TITLE
[10.0] shop payment step did not generate sale order

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#18390]
Impacted versions:
10.0

Steps to reproduce:

1. install e-commerce
2. install  wire transfer payment, or any other payment like paypal
3. add some products to cart
4. checkout cart, and select any payment method.   debug the pay now button, found that there have no value for  order reference

Current behavior:

Expected behavior:

on step payment, should generate sale order, so that use can transfer it as reference for payment with 3rd payment acquirer

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1404460/28489519-2bbc1310-6ef7-11e7-9bf8-a281aa3026ee.png)

**Comment by rdeodoo** [comment]
Hello,

As @odony [pointed out here](https://github.com/odoo/odoo/pull/18392#issuecomment-336386853), it is intended to work that way.

Even if theses fields appear empty in your browser source code, they will be filled afterward when the user will click on the "Pay Now" button, before requesting paypal.

As you can see on Paypal checkout, the SO reference is there 
![ch4t](https://user-images.githubusercontent.com/30048408/34520732-4e22e0b8-f08a-11e7-9c38-6de84866fa0c.png)
