### ISSUE TITLE
Unit of Sale is not taken

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1840]
8rc1
- Set up a product with custom UoS
- Sell it on an invoice (account-module)

The UoS measure will not be taken.
If it is not meant to be available on invoices, the technical setting should not be available. The concept would not have the right implementation scope.
- Install sale
- Register a Sale via Sales Order
  The UoS will not be applied automatically, it will be suggested only:
  ![image](https://cloud.githubusercontent.com/assets/7548295/3959429/6585ad74-272c-11e4-84aa-19bba43fa672.png)

**Comment by malonsopraxya** [comment]
Hello all.

I have the same issue. It's very confusing to try to explain our clients this behavior.
Also sales price may be recalculated, right?

Hope this will be fixed in next version...

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
