### ISSUE TITLE
Sale Pricelist price is not taken into acocunt

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1841]
8rc1
Sale Pricelist ist not taken into acocunt on an invoice (account-module)
If it is not ment for account-module, the according technical setting should only be available when the according modules are installed.
Pricelist is defined as follows:
Public Price is not a field in the product form (suggest it is the same as "Sales Price")

![image](https://cloud.githubusercontent.com/assets/7548295/3958845/4844ca22-2724-11e4-9693-fa113bf5979d.png)

![image](https://cloud.githubusercontent.com/assets/7548295/3958870/65664c34-2724-11e4-83b2-7265b42e3e82.png)

**Comment by Yenthe666** [comment]
Hi @blaggacao ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
