### ISSUE TITLE
United States - Accounting, Installed but not showing in chart of account configuration

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#18428]
Impacted versions:10 C

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by odoouser2** [comment]
I have installed "United States - Accounting" module from the app. Module is installed without error but it does not appear in the Account >>setting>> Chart of Account.

**Comment by Yenthe666** [comment]
Please don't create exact duplicates of your original issue (and without adding any additional information). Original: https://github.com/odoo/odoo/issues/18373
You didn't even give me time to reply on the original topic.
