### ISSUE TITLE
Database restore error

### ISSUE THREAD

**Issue by odoouser2** [odoo/odoo#18429]
Impacted versions:10 Community

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I have backup my database from database/manager and when I try to restore it again from the database/manager it throws error as  "Database restore error: Too much data for base64 line" Please assist the process that I can follow or any alternative way for it. Database size is around 2 GB.

Thank you.

**Comment by odoouser2** [comment]
Hello,
Greetings,

Any update on this issue???

Thank you..

**Comment by Yenthe666** [comment]
Hi @odoouser2,

Sorry for the late reply on this.
It looks like you store all attachments in the database as `base64` and that you have a huge `base64` record in that database.
When you have such a long string it can result into this error. As far as I know the only way to resolve it is to do a command line database dump or to remote the `base64` line.
