### ISSUE TITLE
[Odoo Forum]People with more than 750 karma are again listed as Odoo employees when hovering over

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#18430]
Impacted versions:
Actual version of the Odoo Help Forum

Steps to reproduce:
Do hover over a contributor with more than 750 karma points.

Current behavior:
These people are listed as Odoo S.A. employees:
![image](https://user-images.githubusercontent.com/1814941/28559068-3447f16e-7115-11e7-91ef-20f2d2d8bcc7.png)

Expected behavior:
Do show the true contributor information

Video/Screenshot link (optional):

**Comment by treviser** [comment]
Where can I claim my salary? :-)

**Comment by Yenthe666** [comment]
Count me in! @JKE-be forum related.

**Comment by JKE-be** [comment]
Let me some time to fix it ;)
Now it is 75000, I will check it later :/ sorry

**Comment by treviser** [comment]
> Now it is 75000

What is 75000, my salary :-)

**Comment by Yenthe666** [comment]
Hey then I'll do double shifts. 😉 
But in all seriousness, thank you Jérémy!

**Comment by Yenthe666** [comment]
@JKE-be can you give feedback on this one when you're back from your vacation?

**Comment by JKE-be** [comment]
Landed in v9. Will be fwd-ported asap. already applied on prod
