### ISSUE TITLE
[16.0] crm: date_action_last does not get updated

### ISSUE THREAD

**Issue by oa-eska** [odoo/odoo#184333]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

-Go to any CRM record. 
-Complete any activity or any other change on form.
Expected: date_action_last field to be updated
Behaviour: date_action_last field keeps blank

**Comment by MihranThalhath** [comment]
@oa-eska 
The date_action_last fiel in crm (odoo 16) is used to store the last datetime when an automated action was run in the crm record and not for mail activity changes

**Comment by vava-odoo** [comment]
Hi @oa-eska 
@MihranThalhath is right. As the name was misleading, it was renamed `date_automation_last` in more recent versions.
Cheers
