### ISSUE TITLE
Accounting module doesn't set the "Account" in decimal.precision

### ISSUE THREAD

**Issue by seyed-mohammad-motahar** [odoo/odoo#18437]
Impacted versions:
10.0 E
Steps to reproduce:

Install accounting
Go to Decimal Accuracy
There is no "Account" 

Current behavior:
For balance entry validation code here:
https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_move.py#L206
It tries to fetch "Account" and if it can't fetch it returns 2 decimals. 

Expected behavior:
When we install accounting it has to set "Account" value to the decimal.precision table. 

Video/Screenshot link (optional):

**Comment by csnauwaert** [comment]
Since version 9 we do not use the decimal.precision table anymore, after a check there are a few places that still uses them, those are coming from bug fixes in version before 9 that were forward ported in ulterior version.

I confirm this issue and we will fix it.

best regards

**Comment by csnauwaert** [comment]
Hello,

this has been solved in master branch. Since there was no clear use case where that would cause a problem, no stable version has been impacted. If a specific issue would come up, we will solve it.

Best regards
