### ISSUE TITLE
Public Price is wrongly displayed

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#1843]
8.0rc1 un runbot : 10946-8-0-af1415

![image](https://cloud.githubusercontent.com/assets/7548295/3959455/efcf733e-272c-11e4-8cc7-46122c49852d.png)

![image](https://cloud.githubusercontent.com/assets/7548295/3959466/2b65533c-272d-11e4-9711-b9c373393cc0.png)

![image](https://cloud.githubusercontent.com/assets/7548295/3959457/fbd000d6-272c-11e4-92f5-c4a96b98218a.png)

**Comment by Yenthe666** [comment]
Hi @blaggacao ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
