### ISSUE TITLE
Unique Field in Odoo 10

### ISSUE THREAD

**Issue by YnievesDotNet** [odoo/odoo#18448]
Impacted versions:
10.0

Steps to reproduce:
I try make on my own module an unique field

Current behavior:
I can insert an some records equal value on a this field

Expected behavior:
The system denied repeat value on a field

My code is here:

```
class ResPartner(models.Model):
    _inherit = 'res.partner'
    ...
    nitnumber = fields.Char("NIT")
    ...
    _sql_constraints = [('def_identification_unique', 'unique(nitnumber)', 'NIT must be unique!')]
    ...
```
How I can restrict this unique field

Thanks.

**Comment by Yenthe666** [comment]
Hi @YnievesDotNet,

The Github tracker is only for bugs and issues in the official code, it is not the good place to ask questions about custom development. Please do post it at the official help forums (http://help.odoo.com).
You can handle this in a few methods though. An sql_constraint or an override of the create / write method or an onchange.

Regards,
Yenthe
