### ISSUE TITLE
[10.0] Changing report_name does not update translation

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#18447]
Impacted versions:
10.0
Steps to reproduce:
1. Change field report_name of the template 
2. Load languaje
3. Go to the translation of report_name 

Current behavior:
the translate of report_name is no update when load languajes
Expected behavior:
the translation be origin term or new translation

We changed the template from an [xml ](https://github.com/Vauxoo/mexico/blob/10.0/l10n_mx_base/views/mail_invoice_template.xml#L3) and added the translation to the .po, but from the [commit](https://github.com/odoo/odoo/commit/26627391870af2edd8315748929122392a9a5f68)  this does not work

```
<?xml version="1.0" ?>
<odoo>
    <record id="account.email_template_edi_invoice" model="mail.template">
        <field name="report_name">${object.l10n_mx_report_name}</field>
    </record>
</odoo>
```

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=jk8XMX9ENIg&feature=youtu.be

**Comment by maitaoriana** [comment]
@moylop260

**Comment by moylop260** [comment]
cc @marte

**Comment by moylop260** [comment]
cc @mart-e 
How we should translate inherited items?

**Comment by mart-e** [comment]
Hello,

What do you expect exactly?
The mail template is in no update so it is expected that the translations are non-updated either. This was the point of my commit 26627391.

Or is the issue that you have changed the content of a master record (the invoice mail template) in a custom module and want to handle properly the translations?
I have a bad news on this, it does **not** work to have a translatable field whose value change based on installed module.
For instance, this is what we try to achieve with the module Invoicing/Accounting but it does not work. You have to chose one translation and stick to it, whatever the installed module.
It is not really linked to the changes of 26627391.
If you want a different translation, you will need to create a new record (which is unfortunately not always an option).

Was that indeed the issue?

**Comment by maitaoriana** [comment]
@mart-e Hi, thank you for you answer

Yes, I have changed the content of a master record (the invoice mail template) in a custom module, but before your commit we added [this translation](https://github.com/Vauxoo/mexico/blob/10.0/l10n_mx_base/i18n_extra/es.po#L1168) and the translation worked. As you can see in [the video](https://www.youtube.com/watch?v=PUSkD_dJfEQ&feature=youtu.be).

```
#. module: account
#: model:mail.template,report_name:account.email_template_edi_invoice
msgid ""
"Invoice_${(object.number or '').replace('/','_')}_${object.state == 'draft' "
"and 'draft' or ''}"
msgstr "${object.l10n_mx_report_name}"
```

In Mexico ir required a specific name to PDF files that are send to the customers, by this reason We rename the report name to use the Mexican format

I think that add a new mail template (copy of email_template_edi_invoice) with only the translatable field changed is not a good option. Is there another way to change the translation?

cc @moylop260

**Comment by pedrobaeza** [comment]
The technique for getting this is to used a hook (like post-init) in a custom module, where you explicitly change the file name, but this can't be performed with standard tools the way you want without breaking the translation system (and thus the reason for the @mart-e's commit).

Another option is to install the language on the very beginning before installing account, sale, and so on, and on that case, you won't have the problem either.

Closing this as "won't fix", but for the reasons above.
