### ISSUE TITLE
[18.0] module: description WIP Posting get Error from action menu [Enterprise )

### ISSUE THREAD

**Issue by klqwy** [odoo/odoo#184536]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Go to Manufacturing order ->Click on actions->Click on WIP (post) entry,getting error :

**Comment by klqwy** [comment]
1. https://prnt.sc/W2OwU2OVrdLA
2. https://prnt.sc/mE-RNetTi_9a

**Comment by vava-odoo** [comment]
Fixed in https://github.com/odoo/odoo/commit/d7f913e5e3362dcb8cbca2419f9e81ec9edb4cb3
Thanks for the report

**Comment by klqwy** [comment]
Appreciated.
