### ISSUE TITLE
[7.0] uid of function in function fields

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#1845]
When we use function fields and need information of user connected, we meet the following problem: always uid is the administrator user id. 

we believe it can cause security problems. For example:
we could get all passwords of system users from a function field
Is it a correct behavior?
- **Impacted versions**:

7.0 and above
- **Steps to reproduce**:

create function field
- **Current behavior**:

always get uid=1 (Admin user)
- **Expected behavior**:

get user id connected, to be used in the function

**Comment by Yenthe666** [comment]
Hi @ernesto-gm ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
