### ISSUE TITLE
[16.0] web: Invalid field on selection required with one value

### ISSUE THREAD

**Issue by micheledic** [odoo/odoo#184664]
### Odoo Version

- [X] 16.0
- [X] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

On a form with a field Selection REQUIRED with a single value in list (for example a many2one with widget selection)  saving the record  the error "Field is invalid" appear .
This is caused by this commit https://github.com/odoo/odoo/commit/ad706ab7886e9cf9169c8a47948882ed4468b003  .
The reason is that when the field is rendered, the first element in option is selected, the onChange is not triggered so the this.record prop does not contain this selected value

**Comment by quyvsquy** [comment]
Thanks you, Its save my day,

**Comment by thanhpc2001** [comment]
Thank you, I have found the cause of the error in my project

**Comment by micheledic** [comment]
@chevalierv

**Comment by chevalierv** [comment]
Hello 👋 

We are aware of the issue, we are currently investigating what would be the best way to fix it. I'll let you know when a solution will be provided.

Have a nice day!

**Comment by chevalierv** [comment]
Hello 👋 

We have decided to revert for the moment with those PRs:
