### ISSUE TITLE
[10.0] Current page is not selected when editing a website page 

### ISSUE THREAD

**Issue by benwillig** [odoo/odoo#18465]
**Impacted versions:** 10.0

**Steps to reproduce:**
- Go to the website
- Go on a specific page (events, shop, etc...)
- Customize page using html editor

**Current behavior:**
- Main layout is always the default selected page

**Expected behavior:**
- If users is on products page, products page template should be selected as default.

Video/Screenshot link (optional):
https://youtu.be/Gie0n9zzFqU

**OPW 760279**

**Comment by qsm-odoo** [comment]
@kebeclibre

**Comment by Yenthe666** [comment]
@qsm-odoo could you check the ENT ticket at 760279? Perhaps it has been handled but hasn't this been closed here?

**Comment by qsm-odoo** [comment]
That's why I pinged Lucas just before, I think he solved this :wink:

**Comment by Yenthe666** [comment]
Awesome - thank you!

**Comment by benwillig** [comment]
This has been fixed in https://github.com/odoo/odoo/commit/ac3bfee8f387a43dea00dc9054fc744152922261
