### ISSUE TITLE
[10.0] _get_providers(self, cr, uid, context=None): seems not to work for me

### ISSUE THREAD

**Issue by yezyilomo** [odoo/odoo#18486]
Impacted versions: 10.0

Steps to reproduce:  The aim was to create a custom payment acquirer with its provider as shown bolow 
 class MpayAcquirer(models.Model):
    _inherit = 'payment.acquirer'

    def _get_providers(self, cr, uid, context=None):
        providers = super(MpayAcquirer, self)._get_providers(cr, uid, context=context)
        providers.append(['Mpay', 'MPay'])
        return providers

    Mpay_account_id = fields.Char('Account Id')
    Mpay_access_tocken = fields.Char('Access Token')

Current behavior: Am getting this message in terminal  2017-07-27 10:53:48,449 12663 WARNING ? odoo.api: Deprecated method MpayAcquirer._get_providers in module odoo.addons.Mpay.models.models
 and I don't see newly created provider,

Expected behavior:  creation of new provider in addition to Manual Configuration, Wire Transfer and paypal

Video/Screenshot link (optional):

![terminal](https://user-images.githubusercontent.com/20328561/28669950-20a3bdfc-72df-11e7-8c3c-fc2b305d8784.png)

**Comment by intero-chz** [comment]
Just rewrite you method to the new API style, the old API style is deprecated, as the log mentioned to you.

    @api.model
    def _get_providers(self):
        providers = super(MpayAcquirer, self)._get_providers()
        providers.append(['Mpay', 'MPay'])
        return providers

**Comment by Yenthe666** [comment]
Hi @yezyilomo,

The Github bug tracker is only for bugs/issues in custom development. It is not the place to ask questions about custom development - you can do this on the official help forums (http://help.odoo.com).

Regards,
Yenthe
