### ISSUE TITLE
[ALL] Updating Cost Price on products with realtime is not easy to track from PoV of accounting people

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#18492]
when updating cost on products with realtime valuation.
journal entry lines do not have product_id, which make difficult to track
the accounting valuation of products.

Impacted versions:
all versiones
Steps to reproduce:
take a product with real_time valuation and qty_available > 0
and update de price.
Current behavior:
aml's do not bear product_id field.
Expected behavior:
product_id field filled

https://github.com/odoo/odoo/blob/10.0/addons/stock_account/models/product.py#L96

how we resolved it.
https://github.com/Vauxoo/addons-vauxoo/blob/8.0/product_extended_variants/model/template.py#L157-L166

**Comment by lap-odoo** [comment]
@hbto : Thanks for the feedback. @sle-odoo has created a branch for this, I'll test it and if it's ok it will be merged in master.

**Comment by hbto** [comment]
Thanks @lap-odoo 

Could you point out the branch to check it out.

Thanks
