### ISSUE TITLE
[Bug] Pricelists don't apply the priority

### ISSUE THREAD

**Issue by ed29** [odoo/odoo#18502]
Impacted versions:

odoo 10.0

Steps to reproduce:

![0](https://user-images.githubusercontent.com/3096827/28700646-a7d18c92-7383-11e7-8c14-ee17fdf8c644.png)

![1](https://user-images.githubusercontent.com/3096827/28700645-a7d0fcfa-7383-11e7-980d-28a7cf9f4436.png)

![2](https://user-images.githubusercontent.com/3096827/28700647-a7d23fd4-7383-11e7-9e83-56c575e11013.png)

Current behavior:

Don't apply the pricelists's priority

Expected behavior:

Should apply the pricelists's priority

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Totally agree that PoV usability it is not clear.

But just drag the second Pricelist CNY before USD will fix your problem.

I Keep it open, while we debug the root cause.

**Comment by JKE-be** [comment]
Is it reproducible in a clean database with the latest code? (eg: runbot ?)

**Comment by rdeodoo** [comment]
Hello @ed29 

When you change your company's currency, it also changes the default pricelist currency.
I assume your second screen shot is in fact the first thing you did, then second screen shot?

So, in that exact order:
1. You moved your USD pricelist order before CNY pricelist
2. You changed your company default currency to CNY.
    By doing so, it in fact changed your USD pricelist currency to CNY
3. On ecommerce, you selected USD (which is only a name you chose, not the currency) pricelist and it 
    shows CNY currency which is logical since USD (the name) pricelist currency was changed to CNY.

Can you confirm?
