### ISSUE TITLE
'openerp' in Odoo js

### ISSUE THREAD

**Issue by kamilmuhammed** [odoo/odoo#18518]
Impacted versions: Odoo 10 Community

Steps to reproduce: Change 'openerp' to 'odoo'

Current behavior: Currently Redirect Warning is not working, because in web/static/src/js/framework/crash_manager.js , instead of 'odoo.exceptions...' its 'openerp.exc....'

Expected behavior: 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo looks like on for you. If you confirm the change is fine I'll make a PR for you.

**Comment by kamilmuhammed** [comment]
Yeah Sure

**Comment by ged-odoo** [comment]
@Yenthe666 @kamilmuhammed yes, looks like it needs to be renamed... good catch
