### ISSUE TITLE
[BUG] Group operators in kanban view 

### ISSUE THREAD

**Issue by benwillig** [odoo/odoo#18525]
**Impacted versions:** 
9.0, 10.0

**Steps to reproduce:**
- Go on the task kanban views
- Edit the kanban view
- Add 'sum' attribute on 'remaining_hours' field

**Current behavior:**
In 9.0 and 10.0, group operators don't work in kanban view.

**Expected behavior:**
We should be able to use group operators in kanban view for 9.0 and 10.0. 
[Documentation](https://www.odoo.com/documentation/10.0/reference/views.html#kanban) says it's possible to add group operators but I think they are not even implemented.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/27724417/28720561-cde6352a-73ad-11e7-8389-a5f3fe99fd24.png)
![image](https://user-images.githubusercontent.com/27724417/28720567-d8bd9a9c-73ad-11e7-9f23-ae97d9d4fa57.png)

OPW 760772

**Comment by aab-odoo** [comment]
Hello,

What do you mean by group operators?

Regards

**Comment by aab-odoo** [comment]
Ok got it, never mind.

**Comment by aab-odoo** [comment]
Hello,

This is not a bug, the feature has been dropped in 9.0 because it didn't work correctly (the values weren't updated correctly).

Regards.
