### ISSUE TITLE
[17.0] module: description

### ISSUE THREAD

**Issue by cramosh** [odoo/odoo#185259]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

When making a sale from the POS, if we select the option to pay in cash and enter the amount given by the customer to calculate the change, and then complete the sale.

This occurs when a simplified invoice for the ticket is generated. The error originates from commit https://github.com/odoo/odoo/commit/6172c9af65dbeb730e2ed39485fb169445defb9f uploaded last week by user @kawkb 

In the current version, after applying the change, when a cash payment is made and the amount received from the customer is entered, the system incorrectly transforms the entered cash into the total value of the cart and then subtracts the change given to the customer. This causes discrepancies when closing the register, as the expected cash does not reflect the actual amount received. In other words, the cash received is not being properly accounted for.

**Comment by vava-odoo** [comment]
Thanks for the report. This change was reverted in https://github.com/odoo/odoo/commit/b32a37550f2f1133cd171bd4009acb02c9642dae
