### ISSUE TITLE
 [BUG] website_event_sale to slow with public user

### ISSUE THREAD

**Issue by antoniofregoso** [odoo/odoo#18531]
Impacted versions:10

Steps to reproducThe rule 

Product template linked to event: Public whith  domain:[('product_variant_ids.event_ticket_ids.event_id.website_published', '=', True)] affects the performance of the page only with public users.

Current behavior:
Removing that rule the site works correctly but mark error:
AccessError: (u'No se ha podido completar la operaci\xf3n por restricciones de seguridad. Contacte por favor con su administrador de sistema.\n\n(Tipo de documento: product.product, Operaci\xf3n: read)', None)
Template: website_event.registration_template
Path: /templates/t/form/table/tbody/t/tr/td[1]/div[2]/small
Node: <small itemprop="description" t-field="ticket.product_id.description_sale"/>
Expected behavior:

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Cannot reproduce the performance issue.
How many event_tickets_ids and variant in your case? 
And yes, if you remove the rule that gives access to something, you will have no access and so an error.

**Comment by JKE-be** [comment]
No feedback
