### ISSUE TITLE
[master] .openerp_serverrc still being recognized as default config file.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#18539]
Impacted versions:

saas-17 and master

Steps to reproduce:

Run a v8.0 for example and save the default name, then run a saas-17 server and you see errors related to for example removed web_kanban module comes up.

Current behavior:

Loading .openerp_serverrc as default config file.

Expected behavior:

Ignore .openerp_serverrc.

**Comment by Yenthe666** [comment]
@sle-odoo this is probably for you?

**Comment by sle-odoo** [comment]
`.openerp_serverrc` is not considered as the default config file, but is used if it is present while `.odoorc` is not. It's the intended behavior (see rev https://github.com/odoo/odoo/commit/630b4b1d556b84649cf7b9bfe7a170114d918a36).

As for the web_kanban error, you just have to delete the entry.

This fallback could be removed for v11 but i don't know if anything has been decided yet.

Regards

**Comment by nhomar** [comment]
@sle-odoo Well I think that should be removed, because track the error is a little complicated, if at least a WARNING is sent to the logger, it should be fine.

something like:

info: Loading config file /path/config/being/.whateverrc

If you add the info log I feel served, the point is inform, but if you delete a module (like web_kanban) 100% of people will receive such error related to web_kanban which is time consuming for everybody.

Thanks in advance.

**Comment by sle-odoo** [comment]
@nhomar this information is already displayed, typically it's the second line of your log when you start your server. see https://github.com/odoo/odoo/commit/630b4b1d556b84649cf7b9bfe7a170114d918a36#diff-81879b430cf32e1cae939fcb2b98bb7bR59

**Comment by nhomar** [comment]
@sle-odoo you are right, my mistake, forget it about! remove it if you want (I think delete it is better, but the info is Ok) I miss that sorry.
