### ISSUE TITLE
Module hr_timesheet_sheet was removed but some files still present

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#18532]
### Impacted versions:

saas-17

### Steps to reproduce:

Go to directory `[ODOO_HOME]/addons/hr_timesheet_sheet/` Or see [this link](https://github.com/odoo/odoo/tree/af0048679183018a0b4dbc91fb1a0cf5219600eb/addons/hr_timesheet_sheet)

### Current behavior:

You find the `hr_timesheet_sheet` directory with no manifest file but with some `.py` files and a module tree structure.

### Expected behavior:

The folder should not exist.

**Comment by Yenthe666** [comment]
@jem-odoo this looks like a leftover from https://github.com/odoo/odoo/commit/af0048679183018a0b4dbc91fb1a0cf5219600eb
Should it be removed entirely? If you wish I'll make you a PR.

Regards,
Yenthe

**Comment by jem-odoo** [comment]
Hi,

thanks for reporting. This is now fix at https://github.com/odoo/odoo/commit/04c5aa31259b9e2d8d52f21f9ccde1d0b93d24e8, and will be forward ported in a few days.

Regards,

  Jem

**Comment by Yenthe666** [comment]
Great clean-up, thanks!
