### ISSUE TITLE
Odoo url keeps showing /shop rather than the url shop.intertotal.co.uk i want

### ISSUE THREAD

**Issue by neilbrennan** [odoo/odoo#18543]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by neilbrennan** [comment]
i have put odoo on its own url shop.intertotal.co.uk but odoo keeps putting /shop on the end and redirecting shop.intertotal.co.uk. How can i resolve this issue?

**Comment by Yenthe666** [comment]
Hi @neilbrennan,

Thank you for your report.
The Github tracker however is only for bugs/issues in the official code. It is not the place to ask questions about implementation and configuration. Perhaps the official documentation at https://www.odoo.com/documentation/10.0/setup/deploy.html#https can help you.
You'll need to configure `Nginx` or `Apache` to handle calls from `/shop` to be redirected. If you're still not sure or are facing issues then feel free to create a topic on the official help forums (http://help.odoo.com)

Regards,
Yenthe
