### ISSUE TITLE
[9.0] POS : "Could not serialize access due to concurrent update" for lot of SERIALIZATION_FAILURE

### ISSUE THREAD

**Issue by kiattipong** [odoo/odoo#18553]
Impacted versions: 9.0 (8.0, 10.0 maybe)

**Steps to reproduce:**
1. Creating concurrent pos order for 10 branches, 100 orders per minute approximately.
2. Odoo framework will detect such transaction conflicts in most 
cases and silently retry the failed transaction. You will notice this in the 
logs with messages such as: 
    (...) INFO (...) SERIALIZATION_FAILURE, retry 1/5 in 0.324 sec 
In most cases the next attempt will pass without any conflict. 
3. But if we have a lot of them, the system performance will be impacted.

**Current behavior:**
we try to upgrade Postgres to 9.5 or 9.x to the latest version following below link but it does not solve the problem
(http://www.postgresql-archive.org/Serialization-failures-on-PQ9-5-td5920010.html)

**To change the code in ir_sequence for each POS branch session then the sequence will be created for each branch** This is our solution for now but we need Odoo to fix the problem that still be in POS standard source code

**Expected behavior:**
Running without "Could not serialize access due to concurrent update" red popup error
when two transaction attempt to update the same 
record at the same time, and you can safely ignore them. 
If you have a lot of them to the point of impacting your system performance, 
then something might be wrong in odoo standard source code

**Video/Screenshot link (optional):**
<img width="447" alt="screen shot 2560-07-31 at 12 25 15 pm" src="https://user-images.githubusercontent.com/4959737/28763867-5f8fba7a-75eb-11e7-97a8-763a96206b6f.png">

**Comment by Yenthe666** [comment]
Hi @kiattipong,

Thank you for your report.
Is this related to this report? https://github.com/odoo/odoo/issues/18546 It looks quite identical and the reporting is close to eachother.
Anyways, on topic. What hardware specs do you have? How did you configure your postgresql configuration? Did you use `pgtuneup` to finetune the postgreSQL?
CC @odony

**Comment by Yenthe666** [comment]
Closing as there has been no response in a few months.

**Comment by kiattipong** [comment]
Hi @Yenthe666 ,

please help, this issue still be opened 
pgtune already set but it's not working

There are 2 Servers for App and DB
App: CPU 16 Core RAM 32 GB
DB: CPU 24 Core RAM 64 GB

Database Size : ~50 GB

**Comment by phoenixsampras** [comment]
This issue is Critical. We cannot compete with other POS professional solutions because of this. It affects all Odoo versions.
Multithread is a must for dozens of POS sessions.
What should be do please?

**Comment by BelalSalahH** [comment]
This issue also appears on odoo14 ee, with 35 POS concurrent sessions, and each pos order creating an invoice, the system gives a bad query for generating sequence for the invoice(account.move).

`bad query: 
            UPDATE account_move SET write_date = write_date WHERE id = (
                SELECT id FROM account_move
                WHERE journal_id = 14 AND name != '/' AND date_trunc('month', date::timestamp without time zone) = date_trunc('month', '2021-12-14'::date)  AND id != 2104531 
                AND sequence_prefix = (SELECT sequence_prefix FROM account_move WHERE journal_id = 14 AND name != '/' AND date_trunc('month', date::timestamp without time zone) = date_trunc('month', '2021-12-14'::date)  AND id != 2104531  ORDER BY id DESC LIMIT 1)
                ORDER BY sequence_number DESC
                LIMIT 1
            )
            RETURNING name;
        
ERROR: could not serialize access due to concurrent update
 `
