### ISSUE TITLE
No redirection/validation of when paying through stripe on e-commerce

### ISSUE THREAD

**Issue by esciara** [odoo/odoo#18579]
Impacted versions:
Odoo 10.0-20170731

Steps to reproduce:

* Setup a brand new odoo database with demo data
* Install the e-commerce app
* Setup Stripe as a payment acquirer (production ; make it available on the website ; use your stripe test API credentials)
* Go on the e-commerce shop page
* Select any item to buy
* Go through the purchase process up to the Validate Order page, where you can make your payment
* Try to pay through Stripe (EDIT: use the "Remember me" functionality offered by Stripe and go through text message verification. see comment https://github.com/odoo/odoo/issues/18579#issuecomment-319280241)
* Stripe's pop up appears. Enter the test credit card details (4242 4242 4242 4242) and hit "Pay".

Current behavior:
* Once the popup disappears, one stays on the Validate Order page. One can pay again for the same order, which records another transaction on Odoo and on the Stripe.com Dashboard. We never get to the confirmation page, and the cart is never emptied. 
* Let's say that we paid 3 times using Stripe's popup. The payment transaction is recorded **only once** in Odoo and 3 times on the Stripe.com Dashboard

Expected behavior:
* Once the popup disappears, one should be redirected on the confirmation page, and the cart should be emptied
* If for any reason, I pay with Stripe several times for the save order, 3 payment transactions should be recorded in Odoo (as they are on Stripe.com Dashboard

Video/Screenshot link (optional):
https://youtu.be/F3P0j7edysA

**Comment by Yenthe666** [comment]
@JKE-be could you have a look? (it would be nice to add the responsible people for payment modules at https://github.com/odoo/odoo/wiki/BugManagement too)

**Comment by JKE-be** [comment]
Hello

Why are you testing in 'production environment' with test card?

Can you test in 'test environment' ...

**Comment by esciara** [comment]
@JKE-be I did. Same thing.

**Comment by esciara** [comment]
@JKE-be if it can help you out testing I can give you my publishable and secret Stripe test keys... Once you are done, I will roll them.

**Comment by JKE-be** [comment]
@esciara 

I just do the test... and it works... : https://youtu.be/JKZoVscDg1A

Just creating new DB with website_sale installed
Install stripe payment acquirer
Puclish the payment acquirer
Create new stripe account
Use api key stripe of test (be aware than in Odoo, the order is the opposite)

And that's all :/

https://youtu.be/JKZoVscDg1A

**Comment by esciara** [comment]
Indeed @JKE-be , the way you do it works. After looking into it, the problem occurs when one uses the "Remember me" feature of on Stripe's popup, and gives a phone number. 

![image](https://user-images.githubusercontent.com/1336689/28823436-d24db8d2-76bd-11e7-9964-47d936882b1c.png)

Then, the phone number entered associated with the email address given in the Stripe popup, and when reusing the same email address, a verification code is sent by text message to verify one's identity. After entering the verification code and clicking the "Pay" button, the problem I describe occurs. (as demonstrated in my video)

**Comment by lukebranch** [comment]
@esciara ,

FWIW I have been encountering the same issue and have used stripe for quite some time in version 9.0. I deployed a fresh version 10.0 instance on Ubuntu 16.04 with the OCA module (db filter from header for db:domain routing, and nginx as a reverse proxy), and was having issues.

I am running on a micro-instance in GC with a single shared CPU and roughly 2GB

I've just upgraded to the latest version of python-stripe:

pip install --upgrade stripe==1.62.0

and restarted the odoo service, however this has not resolved the issue.

Are you running workers > 0 by any chance? I have found with workers < 0 stripe's page load event triggers and Odoo successfully goes to the confirmation page. With workers > 0 Odoo just sits there, or eventually times out with a 502 Bad Gateway error from Nginx.

**Comment by esciara** [comment]
@JKE-be I am testing with a fresh instance using vagrant to spin and provision a Ubuntu 16.04 with 2GB of memory and go straight from there. Provisioning follows the doc at https://www.odoo.com/documentation/10.0/setup/install.html#deb .

Vagrantfile : https://gist.github.com/esciara/a174aa6f26b08ff5ffaa569a69a40fd1

This means it does not work out of the box as is. Not sure what are the defaults as to the number of workers.

**Comment by esciara** [comment]
Hi @JKE-be . Any progress/more comments on this?

**Comment by srokatonie** [comment]
There's a chance your system doesn't have Wkhtmltopdf.
Can you try pay by Stripe and post browser's console output if any errors?

**Comment by lukebranch** [comment]
I think workers > 0 is the key here, especially if you have them enabled for live chat. Are you using live chat at the moment?

If you give yourself an extra core on that server (ie. two cpu cores) and add this to /etc/odoo-server.conf:
workers = 1
max_cron_threads = 1

and restart your odoo service I think your issue will be resolved. Alternatively if you don't need live chat and discuss features updating in real time you can try just comment out the above lines in your /etc/odoo-server.conf file and restart the odoo service again.

**Comment by esciara** [comment]
@srokatonie : as you can see in the `Vagrantfile` I mentioned in my previous post, I have a `sudo apt-get install -y wkhtmltopdf`. However, looking at the console, I could find the following error message, which is related to Wkhtmltopdf:
```
stripe.js:25 
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 677, in dispatch
    result = self._call_function(**self.params)
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File \"/usr/lib/python2.7/dist-packages/odoo/service/model.py\", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 935, in __call__
    return self.method(*args, **kw)
  File \"/usr/lib/python2.7/dist-packages/odoo/http.py\", line 506, in response_wrap
    response = f(*args, **kw)
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/payment_stripe/controllers/main.py\", line 38, in stripe_create_charge
    request.env['payment.transaction'].sudo().form_feedback(response, 'stripe')
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/website_portal_sale/models/payment.py\", line 57, in form_feedback
    tx._confirm_so(acquirer_name=acquirer_name)
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/website_portal_sale/models/payment.py\", line 75, in _confirm_so
    tx.sale_order_id.with_context(send_email=True).action_confirm()
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/portal_sale/models/sale_order.py\", line 16, in action_confirm
    return super(SaleOrder, self).action_confirm()
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/sale/models/sale.py\", line 457, in action_confirm
    self.force_quotation_send()
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/sale/models/sale.py\", line 441, in force_quotation_send
    order.with_context(email_ctx).message_post_with_template(email_ctx.get('default_template_id'))
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py\", line 1947, in message_post_with_template
    update_values = composer.onchange_template_id(template_id, kwargs['composition_mode'], self._name, res_id)['value']
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py\", line 361, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py\", line 498, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_template.py\", line 533, in generate_email
    result, format = Template.env['report'].get_pdf([res_id], report_service), 'pdf'
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py\", line 265, in get_pdf
    context.get('set_viewport_size'),
  File \"/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py\", line 453, in _run_wkhtmltopdf
    raise UserError(message  % (str(process.returncode), err[-1000:]))
UserError: (u'Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display \\n', '')\n","exception_type":"user_error","message":"Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display \n\n","name":"odoo.exceptions.UserError","arguments":["Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display \n",""]}}
```

On a side note, I also had the following warnings:
```
stripe.js:86 
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ web.assets_common.js:950
ajax @ web.assets_common.js:930
(anonymous) @ web.assets_common.js:3025
genericJsonRpc @ web.assets_common.js:3023
jsonRpc @ web.assets_common.js:3025
(anonymous) @ stripe.js:86
dispatch @ web.assets_common.js:637
elemData.handle @ web.assets_common.js:610
```
```
payment: 1
This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
```
Here is a screenshot:
![image](https://user-images.githubusercontent.com/1336689/29388612-f9c0c9f2-82e5-11e7-9304-bb884c0cae88.png)

@lukebranch: 
- made it two cpus in the `Vagrantfile` with `vb.cpus = "2"`
- added the following lines to `/etc/odoo/odoo.conf`:
```
workers = 1
max_cron_threads = 1
```
- restarted the service with a `sudo /etc/init.d/odoo restart`
- cleared Stripe's cookies just in case.

Same result.

Did this all on a brand new installation with Odoo 10.0-20170816 . (`vagrant destroy` and the `vagrant up`)

**Comment by esciara** [comment]
Ok... I googled on the error message "`Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored. [..]`" and I came accross this article: https://discuss.erpnext.com/t/wkhtmltopdf-error-erpnext-v7/14673 .

Indeed the version installed by default on Ubuntu 16.04 has an issue:
```
vagrant@vagrant:~$ wkhtmltopdf -V
wkhtmltopdf 0.12.2.4
```
And when I look again at the installation guide at https://www.odoo.com/documentation/10.0/setup/install.html#deb , it does say that it recommends to install version 0.12.1, although it does not mention problems with later versions. I was hence misguided by http://askubuntu.com/questions/556667/how-to-install-wkhtmltopdf-0-12-1-on-ubuntu-server , and the `sudo apt-get install wkhtmltopdf` was installing version 0.12.2.4, which contained the issue. (to note that it seems the issue was already present in versions prior to 0.12.1)

So I installed version 0.12.1 with the following steps found in the first article mentioned above:
```
sudo apt-get remove --purge wkhtmltopdf
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb
sudo /etc/init.d/odoo restart
```
(Incidently, I also had to start a new shell for the installation to take full effect.)

After this installation all worked fine (even though I had to do a full clean install, probably because of left overs of the previous installs)

By the way, it also works fine with wkhtmltopdf 0.12.4 too.

Thanks all for your help. I am closing this ticket

**Comment by gdgellatly** [comment]
You are confounding 2 things. Wkhtmltopdf version and whether it has been
built using patched qt. Different versions have issues but whichever
version must always be built using patched qt. Your initial error was
because it wasn't built using patched qt not due to version specifically.

**Comment by esciara** [comment]
@gdgellatly thanks for this clarification. So that means that the version distributed on ubuntu 16.04 and installed through `sudo apt-get install -y wkhtmltopdf` has not been built using patched qt and that is it better to install it through another mean (one of which is described in the article cited in my previous comment).
