### ISSUE TITLE
[16.0] account config show_line_subtotals_tax_selection field  must be separate from website_sale config

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#185722]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

1.- Config "Line subtotals tax display" in account settings
2.- go to website_sale config and set "Prices displayed on your eCommerce"

### Log Output

```shell
Both settings use the same show_line_subtotals_tax_selection field, so if I want to configure price include for website prices, this make shows lines with price include in Invoices
```

**Comment by vava-odoo** [comment]
Hi @dansanti 
Indeed, this is was corrected in recent versions but it is unfortunately not safe to change in stable.
