### ISSUE TITLE
Manual reconciliation: wrong buttons displayed sometimes when balance is 0

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#1859]
When the user selects lines to reconcile and their balance is 0.0, so write-off is 0.0, the wizard sometimes shows the button with the Write-off / Partial Reconcile buttons instead of the Reconcile button.

![lettrage_avec_ajustement_a_zro](https://cloud.githubusercontent.com/assets/417223/3965388/37dc37a2-2796-11e4-8c5c-fdf367eafdd3.jpg)

It slows down the efficiency of the accountants when they have many reconciliations to do because each time they have to fullfill the journal and account information for the write-off. At least, as expected, no write-off is created.

I did not find a way to reproduce, our users say that it happens about 10% of the time.

**_Impacted versions:**_
- 7.0 at least

**_Steps to reproduce:**_
1. Select lines to reconcile, their balance should be 0.00
2. Open the reconcile wizard, the write-off should display 0.00
3. If the wizard displays only the "Reconcile" button (and cancel), return to 1 with other lines
4. If the wizard displays 2 buttons "Reconcile with write-off" and "Partial Reconcile", the bug happened

**_Current behavior:**_
- Sometimes display the wrong buttons when the write-off is 0.00

**_Expected behavior:**_
- Always display the "Reconcile" buttons when the write-off is 0.00

**Comment by Yenthe666** [comment]
Hi @guewen ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
