### ISSUE TITLE
Odoo -- Hodor?

### ISSUE THREAD

**Issue by passboltUser** [odoo/odoo#18598]
I see that you renamed yourself to Odoo only just recently (September 18, 2014). Could "Odoo" be a reference to Game of Thrones' "Hodor"?

**Comment by Yenthe666** [comment]
Hi @passboltUser,

Not really a bug, right? 😉
Any references are purely random, I assume 😉 

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
![gallery-1464017558-hodor-l](https://user-images.githubusercontent.com/7165771/28824214-5e7ca630-76c1-11e7-886b-17c90d277021.gif)

:laughing: :laughing:

**Comment by fpodoo** [comment]
The reason of the change:
https://www.odoo.com/blog/notre-blog-5/post/odoo-the-new-openerp-156

**Comment by passboltUser** [comment]
(Not a bug indeed.)
Ah, ok, thanks. Yes, indeed, certain letters seem to be perceived more pleasant (I think e.g. l and g are such letters). If I remember correctly, it goes so far, that when a company is created, they choose these letters more frequently. Unfortunately I could not find how this thing is called or more informations on it.
Now with so many 'o's, you should be able to buy Google soon :D
