### ISSUE TITLE
Employee sensitive data can be seen

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#18610]
Impacted versions:
V11
V10 community or enterprise

Steps to reproduce:
1. Create an employee and add some Personal Information under Contact Information / Home Address.
2. Create a home address and fill some data.
3. Log in as a user with HR "Employee" role, like demo/demo in runbot
4. Go to Employess / Employees and look up the employee. You will notice you cannot see Personal Information [OK]
5. Go to Sales / Customers. Remove all the filters in the search and search the Employee
6. You can now view the Home Address [NOT OK].

Another way to view the same info:
7. Make sure that employee is added as a follower in a sales order.
8. Open the sales order and look for the employee in the chatter.
9. When you open the follower you can also view the same data.

or using export data
10. Go to employees
11. Select the employee
12. Export these fields Home Address, Home Address/City, Home Address/Street

It's not allowed to view the sensitive information!! This is very dangerous.

Current behavior:
---

Expected behavior:
Not allowed to view the Home Address or any sensitive information when you have the role Employee, should be only restricted to the HR Manager.

Video/Screenshot link (optional):
----

**Comment by yung-wang** [comment]
This problem is also in V11. Please upte the label and add V11.

**Comment by Yenthe666** [comment]
@mart-e who can check / fix this?

**Comment by mart-e** [comment]
Hello,

Indeed this is right. You can work around this by creating some specific record rules but it is a bit tricky.
The idea is to separate the res.partner linked to the employee and the one of the user and restrict the access to the first one.

This is something we should improve in the future, I will report the feedback.

**Comment by pedrobaeza** [comment]
@yung-wang is enough with #24573 for you?

**Comment by yung-wang** [comment]
@pedrobaeza I have to check when the PR is finished. If it also fix the problem with the follower and the export of the excel, than it is. But the PR is very promising and it is going in the right way for the Dutch localization. We need this for the Dutch privacy / personal data law.

**Comment by pedrobaeza** [comment]
The PR has been already merged.

**Comment by astirpe** [comment]
I just tried on Runbot and it seems working fine on master branch. @yung-wang could you confirm?
Anyway the issue still occurs in V11 and V10.

**Comment by yung-wang** [comment]
@pedrobaeza I did a check in Master. For the private address it works. But not all the sensitive data is hidden. I created this issue, only with examples of the home address. So that is fixed with the PR, so that is great.
But what I don't understand is that the other sensitive data is still visible somehow. If you log in as demo/demo, and you go to the employee, you can only see the tab Work Information. Private Information is not visible. This is how is should work. But Odoo allows you to export infomation belonging from the Private Information. So for me, this issue is partly fixed.

**Comment by yung-wang** [comment]
@pedrobaeza Yes, I'm sure. See the screenshots for the other fields. But I really like the improvements that Odoo made. They are close to a perfect solution.

**Admin**
![selection_001](https://user-images.githubusercontent.com/30628967/39747818-a63f1fa6-52ae-11e8-8190-4f434a75d413.png)

**Demo**
![selection_002](https://user-images.githubusercontent.com/30628967/39747831-adcc00cc-52ae-11e8-982d-312765b0e43c.png)

**Comment by pedrobaeza** [comment]
Well, that's something undesirable indeed. @tivisse @odony this is something inherent of the export framework, not only for this case. Should this export feature restrict to the allowed fields by group?

**Comment by mart-e** [comment]
If I am not mistaken #24573 was only for the private address field. All the other information are still on the employee, so just protected on the view.

**Comment by pedrobaeza** [comment]
Yeah, that's it, @mart-e. The problem seems to be that using the export option from employee, you can drill down on the home address (with export all option), and get the same information although "private". Is that, @yung-wang ?

**Comment by yung-wang** [comment]
@pedrobaeza yes, that was part of the problem of this issue. With the [#24573](https://github.com/odoo/odoo/pull/24573) the private address seems to be fixed. For so far I tried, I cannot export the Home/Private Address. But still the data on the Private Information tab can be exported. So to solve this issue, we need to make sure all the Private / Sensitive data should stay hidden even in the export.

**Comment by odony** [comment]
Access control on employee fields is not based on the location of the fields in the view, but on the restrictions chosen at the model level. When certain fields are restricted in this manner, you won't even see them in the list of fields to export (look for 'Passport No' for example).

"Field of Study", "School", etc. are recently added fields in a new 11.0 Enterprise module closely related to Belgian Contracts, and they were not protected in this manner yet, as they were not considered very sensitive. However, since they were in the Private information tab, HR personnel and employees could reasonably expect these fields to be protected in the same manner as the other private employee fields. This is now fixed in Enterprise 11.0 by odoo/enterprise@533db05b5e3b8a28028cb9b61d31eb13296daa55.

**Comment by yung-wang** [comment]
Thanks for the fix!! Keep up the great work.

**Comment by Yenthe666** [comment]
Awesome, that is a good improvement to the security. Keep up the good work Olivier, you're doing terrific work.
