### ISSUE TITLE
[16.0] stock: cannot create return as sequence is not unique

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#186365]
### Odoo Version

- [X] 16.0
- [ ] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Install a new DB with stock module and demo data. Take a done delivery. Create a return. You get the error `The operation cannot be completed: Reference must be unique per company!`

### Cause

The bug has been introduced by https://github.com/odoo/odoo/pull/185966

The return sequence code is set to IN here https://github.com/odoo/odoo/blame/16.0/addons/stock/models/stock_warehouse.py#L1025
as for the reception. You now end-up with 2 sequences with the same prefix causing UniqueViolation error since the change to use the picking type sequence code.

### Suggestion

Could you change the return sequence to `RET` instead of `IN`?
Can you add a unit test creating a return as this does not seem covered by tests?
Maybe having a python constraint on the picking type to ensure there are not 2 picking types on a same warehouse with the same sequence_code but different sequence (we still need to allow to picking type with the same sequence code if they are linked to the same ir.sequence).

**Comment by rousseldenis** [comment]
@amoyaux @clesgow

**Comment by clesgow** [comment]
A fix is underway, thanks for the notice. :slightly_smiling_face: 
However, I'm curious on how you reproduce it in `17.0`, as `return_type_id` was removed in `16.4` through https://github.com/odoo/odoo/pull/118568?

**Comment by clesgow** [comment]
Fixed in https://github.com/odoo/odoo/pull/186462.
