### ISSUE TITLE
Incorrect Invoice Status in Sales Order

### ISSUE THREAD

**Issue by juhk** [odoo/odoo#18639]
Impacted versions:
Odoo 10.0

Steps to reproduce:
1. Create a new sales order with order line having unit price > 0.00
2. Create a invoice from the sales order
3. Add a new invoice line with unit price equal to 0.00
4. Validate the invoice
5. Check invoice status of the sales order

Current behavior:
Invoice Status is 'Nothing to Invoice'

Expected behavior:
Invoice Status is 'Fully Invoiced'

Video/Screenshot link (optional):

**Comment by intero-chz** [comment]
The calculation is based on the invoiced quantity not the invoiced amount. I see no Bug/Error here.

**Comment by juhk** [comment]
The same thing happens if you add a delivery method with 0.00 unit price (Free delivery charges) to a sales order. It will create a sales order line for the delivery with 'invoice_status' equal to 'no'. The invoice status of the sales order will be 'Nothing to Invoice' although invoice has been created and validated for the sales order.

**Comment by Yenthe666** [comment]
As mentioned by intero this is not a bug. If the amount is 0.00 and you validate it there is literally nothing to invoice.
