### ISSUE TITLE
You cannot have 2 pricelist versions that overlap!

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#1863]
On version 7, I have a pricelist with 2 versions:
- v1 ending on August 15th
- v2 starting on August 16th

I want to change the dates to:
- v1 ending on Sept 15th
- v2 starting on Sept 16th

When I save the change, I get the error message: You cannot have 2 pricelist versions that overlap!

My new dates do not overlap from a functional point of view. I expect the changes to be saved without any error message.

I guess Odoo saves v1 before v2 so Sept 15th overlaps August 16th. In this scenario, v2 should be saved first because the date is delayed. In a scenario where the date is sooner, v1 should be saved first.

**Comment by grayousious** [comment]
Confirmed in v8 also.

**Comment by Yenthe666** [comment]
Hi @max3903 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
