### ISSUE TITLE
[18.0] website: notification in frontend always stays at top

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#186432]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

All frontend notifications stay at the top.
[Products _ My Website.webm](https://github.com/user-attachments/assets/7aaa5bb8-4101-4bd6-861e-b3a78b02060c)

**Comment by kig-odoo** [comment]
Hey @qsm-odoo ,

I hope you're doing well.

I just found the issue [see video](https://github.com/user-attachments/assets/7aaa5bb8-4101-4bd6-861e-b3a78b02060c)

Not sure if it is due to a change in 18.0 because now we have a different scrolling element with [PR](https://github.com/odoo/odoo/pull/98429) we changed `#wrapwrap` to `body`.

**Comment by qsm-odoo** [comment]
Hello @kig-odoo :wave: 

There you go: https://github.com/odoo/odoo/pull/186435 -> should be merged soon enough. Thanks for the bug report :+1:
