### ISSUE TITLE
[BUG] IotBox 24.10 CUPS printer discovery fails without proper display initialization

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#186436]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [ ] 18.0
- [X] Other (specify)

### Steps to Reproduce

When booting the IoT Box without HDMI connected or proper display configuration, CUPS printer discovery (lpinfo -m) hangs indefinitely. This is caused by improper framebuffer initialization in the vc4-fkms-v3d driver.

Steps to reproduce:
1. Flash IoT Box image 24.10
2. Boot without HDMI
3. SSH into the iotbox
4. Run lpinfo -m - command hangs (this also translated into no devices being found or added to the cups server and the inability to add any because the driver loading fails).

Current workarounds:
1) Boot once with HDMI and a display connected
2) Add to /boot/config.txt
```
  hdmi_force_hotplug=1
  hdmi_group=2
  hdmi_mode=82
```
3) Delete /usr/lib/cups/backend/driverless which si the actual driver that fails

Suspected root cause:
- The vc4-fkms-v3d driver requires proper display initialization
- Without it, system resource allocation is incomplete
- This causes CUPS driverless backend to hang during printer discovery

My suspicion is that this commit introduced the issue: https://github.com/odoo/odoo/commit/de2b8444de73d9a46ea190cbbff6ee52dae1435e#diff-0f2612517c5210de5e73d24d91598b9d4d99bccea6a91e1c4469ac6853b940a2R203

@loouis-t Can you reproduce the issue as described? This seems to not be present in 24.01

I am not sure if it is related to https://github.com/odoo/odoo/issues/51640 or not.

### Log Output

**With HDMI plugged in and in a working state:**

Initialization Messages
[    8.505808] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    9.409512] vc4-drm gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
[    9.413636] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 1
[    9.738237] vc4-drm gpu: [drm] fb0: vc4drmfb frame buffer device  # Creates framebuffer

**Without HDMI and broken state where lpinfo -m hangs:**

From earlier logs
[    6.936780] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    8.621962] [drm] No displays found. Consider forcing hotplug if HDMI is attached  # Error
[    8.622014] vc4-drm gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
[    8.642766] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 1
[    8.642818] vc4-drm gpu: [drm] No compatible format found  # Error
[    8.642835] vc4-drm gpu: [drm] Cannot find any crtc or sizes  # Error

### Support Ticket

opw: 4314249

**Comment by MaxTheWhale** [comment]
This issue has been fixed in the new [24.11 image](https://nightly.odoo.com/master/iotbox/iotboxv24_11.zip), please raise a new issue if you encounter any problems with it.

Thanks!
