### ISSUE TITLE
wrong signature in get_min_max_date method

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#1864]
Affects 7.0 and up, including master.

https://github.com/odoo/odoo/blob/master/addons/stock/stock.py#L642

Here the `get_min_max_date` method accepts a `field_name` parameter that should actually be `field_names` because `multi` is set and the method returns a dictionary.

The method works, because the ORM calls it with positional parameters. This however is confusing and we can't rely on it.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your report.
Odoo V7 is however no longer supported by Odoo (as Odoo only supports three versions) so this won't be patched / fixed anymore.
Sorry for the late reply.

Regards,
Yenthe

**Comment by lepistone** [comment]
Thanks @Yenthe666 for cleaning up those old issues!

I gave a look and it appears that the same issue appears in odoo 8.0 and 9.0 https://github.com/odoo/odoo/blob/9.0/addons/stock/stock.py#L773 but disappeared in 10.0 when those fields were refactored to the new API.

**Comment by Yenthe666** [comment]
Hi @lepistone,

Please do create a new issue (or a PR then) 😄 that would be perfect.

Regards,
Yenthe

**Comment by lepistone** [comment]
I'd say since the bug went away in v10, and no-one else showed up since 2014, let's keep it closed! Thanks.
