### ISSUE TITLE
[10] Alternative products related with product.template, but not product.product?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#18641]
Impacted versions:
10.0
Steps to reproduce:
Look up source or open interface with debug mode and open product.product form or product.template form.
Current behavior:
As you can see in this code (in module `website_sale/models/product.py`):
```python
    alternative_product_ids = fields.Many2many('product.template', 'product_alternative_rel', 'src_id', 'dest_id',
                                               string='Alternative Products', help='Suggest more expensive alternatives to '
                                               'your customers (upsell strategy). Those products show up on the product page.')
    accessory_product_ids = fields.Many2many('product.product', 'product_accessory_rel', 'src_id', 'dest_id',
                                             string='Accessory Products', help='Accessories show up when the customer reviews the '
                                             'cart before paying (cross-sell strategy, e.g. for computers: mouse, keyboard, etc.). '
                                             'An algorithm figures out a list of accessories based on all the products added to cart.')
```

`alternative_product_ids` has a relation to `product.template`, but `accessory_product_ids` to `product.product`. Why is that? If we have `product.template`, then we won't know specific product we need to use (if let say variants are used). Shouldn't it be `product.product` relation?
Expected behavior:
```python
 alternative_product_ids = fields.Many2many('product.product', 'product_alternative_rel', 'src_id', 'dest_id',
                                               string='Alternative Products', help='Suggest more expensive alternatives to '
                                               'your customers (upsell strategy). Those products show up on the product page.')
```

**Comment by pedrobaeza** [comment]
This is something specifically thought for current website e-commerce structure, where the product details page is the template, not the variant, and you select there the attributes for "configuring" the variant. Linking product.product wouldn't make sense in this scenario.

Closing as no real issue.
