### ISSUE TITLE
Email send failure in Helpdesk due to \u200 character in user emails

### ISSUE THREAD

**Issue by vostokbike** [odoo/odoo#18656]
Impacted versions:
10 Enterprise
Steps to reproduce:
1. Create a user (customer) in Users
2. Create contact for the above user and copy-paste the email address
3. Create a ticket in Helpdesk for the newly created customer
4. Send email from the helpdesk ticket
Current behavior:
The email is not sent with the following error:
Error without exception. Probably due do sending an email without computed recipients.

Log output:
2017-07-31 07:20:29,882 2956 INFO odoo odoo.addons.mail.models.mail_mail: Ignoring invalid recipients for mail.mail <1501485629.355113983154297.481168696408933-openerp-4884-helpdesk.ticket@odoo>: [u'Autumn Parker <example@\u200gmail.com>']

The only way to correctly populate the email field is by typing in the address manually, without copy-pasting. 
Expected behavior:
After the email address is added to the User, email should be able to be sent out.

**Comment by pedrobaeza** [comment]
If this is still happening, please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.
