### ISSUE TITLE
can not access webpage with my machine IP

### ISSUE THREAD

**Issue by piyushgohel** [odoo/odoo#18651]
Hello,

I have created one page with odoo website addon. I will properly work when I select database.If I have not select database, it will return 404 error. In log, i will see following line.

"2017-08-03 05:14:04,265 19930 INFO ? werkzeug: 192.168.0.102 - - [03/Aug/2017 05:14:04] "GET /test HTTP/1.1" 404 -"

I am access webpage with http://myIP:8069/test

give me solution about this error

Best Regards,
Piyush

**Comment by Yenthe666** [comment]
Hi @piyushgohel,

If I understand you correctly you have two (or more) databases? If you haven't selected a specific database Odoo simply doesn't know which database it should take. If you have two databases for example the webpage will exist in database 1 but this same page will not be known in database 2. So, how should Odoo be able to handle that? If you've selected the database where the page exists on it'll work.

**Comment by piyushgohel** [comment]
But normally there are more than one database, at that time how to select default database?

**Comment by Yenthe666** [comment]
@piyushgohel have a look at the deployment documentation from Odoo https://www.odoo.com/documentation/10.0/setup/deploy.htm
If you still face this issue please continue this on the official help forums (help.odoo.com).

Regards,
Yenthe

**Comment by piyushgohel** [comment]
Link not open

**Comment by Yenthe666** [comment]
The 'l' was missing for '.html'. URL: https://www.odoo.com/documentation/10.0/setup/deploy.html
