### ISSUE TITLE
Timesheets to Validate not seems any timesheet of any user admin side

### ISSUE THREAD

**Issue by sachinbanugariya** [odoo/odoo#18652]
hello,

timesheet validation approvals is not seems admin side,
approvals only seems on perticular manager account,

we must also need to see all timesheet on admin account.
how can i delete or refused timesheet which is approved,

thanks.

**Comment by Yenthe666** [comment]
Hi @sachinbanugariya,

The administrator user can see every record on any model. You can see all timesheets from the app Timesheets under the menuitem Timesheets > All Timesheets:
![image](https://user-images.githubusercontent.com/6352350/34440608-790f3556-ecb6-11e7-8b86-fa53de122d6a.png)

P.S: Notice that only those users that actually have timesheets in the selected period are shown. If you've got a user "James" but he hasn't booked any hours he won't show up.

Regards,
Yenthe
