### ISSUE TITLE
Which connector would you recommend for Magento v1.9.3.4?

### ISSUE THREAD

**Issue by passboltUser** [odoo/odoo#18661]
Impacted versions: 10.0

Which connector would you recommend for Magento v1.9.3.4?

**Comment by Yenthe666** [comment]
Hi @passboltUser,

Thank you for your report.
The Github tracker is only for bugs in the official code though. It is not the place to ask questions.
Please ask this question on the official help forums (help.odoo.com) where plenty of people can help you.
P.S: Odoo itself does not support connecting to Magento, but there are some apps in the app store for this.

Regards,
Yenthe

**Comment by passboltUser** [comment]
It doesn't allow my to ask a question and I get: "3 Karma-Punkte sind erforderlich um diese Aktion auszuführen. Sie können Karma-Punkte erwerben, wenn Ihre Antworten durch die Community positiv bewertet werden."

**Comment by Yenthe666** [comment]
Hi @passboltUser,

This means you haven't verified your account (your e-mail) yet. If you do this you'll get more karma and you will be able to create a new questions.

Regards,
Yenthe

**Comment by passboltUser** [comment]
I can't anwser any Odoo related questions to collect Karma-Points since I'm totally new to it..

**Comment by passboltUser** [comment]
When I wanted to ask a question, there was a message saying that I need to verify my email. I clicked on the link, but got a "500: Internal Server Error", but when I refreshed the tab, the message disapeared. Where can I find the resending link to my email in my account profile settings, can't find it.

**Comment by passboltUser** [comment]
Thanks.
