### ISSUE TITLE
[10.0-pos_restaurant] name is cut on the kitchen printer if it does not fit on 1 line

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#18688]
Impacted versions:
10.0
Steps to reproduce:
- Setup a Product with a long name (ie. Chicken with Barbecue Sauce and French Fries)
- Setup a posbox with kitchen printer

Current behavior:
- on the kitchen ticket, the name is cut. The whole name is not printed
 
Expected behavior:
- on the kitchen ticket, the name should not be cut and be printed on several lines

**Comment by Yenthe666** [comment]
@jorenvo I think this is one for you? (sorry if I bother you)

**Comment by invitu** [comment]
@jorenvo thank you for your commit. BTW, the name appears on several lines but words are still cut in the middle if they appear next to the end of the line

**Comment by jorenvo** [comment]
@invitu which printer are you using?

**Comment by invitu** [comment]
@jorenvo Epson TM20II

**Comment by jorenvo** [comment]
Hmm, odd. I'm sure I tested it on that printer. Could you give me a name of a product for which the issue occurs? With that I can see if I can reproduce it.

**Comment by majeedkalathingal** [comment]
@cvinh hi did you got solution? now i am facing the same problem
