### ISSUE TITLE
Unable to self-publish user profiles on public forum website

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#1868]
After the upgrade of odoo.com to v8rc1 and in current runbot v8rc1 new and old website forum users profiles are not published on the website.  Also the user can set his/her profile to publish but it will not be saved.  Confirmed on runbot v8rc1.

**_Impacted versions:**_
v8rc1

**_Steps to reproduce:**_
1. From public website click login/sign up and create a new account.
2. Click Forum | Ask a question and post a question so your karma is > 1
3. Click Forum | People, the new user will not be listed.
4. Click your name | My Account to enter odoo back-end.
5. Click your name | Preferences to see your user preferences.
6. Click Not Published to change it to Published then click save.
7. Click your name | Preferences to confirm the change has not been saved.
8. Cancel the preferences window and click website | forum | people to confirm user is still not listed.

**_Current behavior:**_
Users are not automatically published to the public website upon creation and can not elect to make their account publicly seen.  The master branch does not have this behavior.

**_Expected behavior:**_
If the default behavior is to keep new users private then users should be able to change this to make their profile public.

**Comment by Yenthe666** [comment]
Hi @smack815 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Missing you around buddy 😉 

Regards,
Yenthe
