### ISSUE TITLE
[17.0] Survey: Section is not displayed when using Pagination "One page per question"

### ISSUE THREAD

**Issue by MarDom14** [odoo/odoo#186856]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- go to survey
- create a new survey
- write down a name for the survey (any name)
- add a section (any name)
- add a question
- go to "Options"
- select Pagination "One page per question"
- save
- click on "Test" button

there will be no section displayed using the "one page per qustion" option - participants will not recognize when a new section starts

### Support Ticket

#4322994

**Comment by vava-odoo** [comment]
Ticket closed with:
Section not shown in "one page per question", but questions are grouped by sections
Sections are only displayed in "one page per section"
