### ISSUE TITLE
[17.0] web_editor: can't add video as section background

### ISSUE THREAD

**Issue by M4hd1BD** [odoo/odoo#186874]
### Odoo Version

- [x] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Open Web Editor, Add any section to the page, add a new background video, paste a link, try to save the popup. 

Expected behavior: It saves and the video is added as the background. 
Current Behavior: Throws an exception. 

https://github.com/user-attachments/assets/82bf8712-cc8b-4998-abf7-fa8528ada9d9

I believe this issue was introduced with https://github.com/odoo/odoo/commit/f79fb841b9f3eebdb8c65d155f74bf1a37419eec by @paru-odoo: 

### Log Output

```shell
TypeError: Cannot read properties of null (reading 'tagName')
    at https://domain/web/assets/4/7f4333a/web.assets_web.min.js:14737:269
    at Array.forEach (<anonymous>)
    at MediaDialog.renderMedia (https://domain/web/assets/4/7f4333a/web.assets_web.min.js:14729:191)
    at async MediaDialog.save (https://domain/web/assets/4/7f4333a/web.assets_web.min.js:14745:240)
```

**Comment by paru-odoo** [comment]
Hello @M4hd1BD 

Thank you for bringing this issue to my attention. I appreciate your diligence in reviewing the code. I will investigate the problem you identified and work on a solution promptly.

**Comment by M4hd1BD** [comment]
@paru-odoo if the issue is fixed and merged everywhere, we can close this.
