### ISSUE TITLE
[17.0] web: some io icons not showing in last version of Chrome

### ISSUE THREAD

**Issue by danPr0** [odoo/odoo#186936]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

- Update chrome to last version: 130.0.6723.117
- Install clean odoo without any external dependencies

### Log Output

![Screenshot 2024-11-12 150832](https://github.com/user-attachments/assets/4a7c4aad-d707-4c43-8978-8964716fe60e)

**Comment by chgo-odoo** [comment]
Hello, thanks for submitting this feedback 👋

At first sight, it looks like this could be related to your browser cache, given that some icons are well rendered.
Could you try refreshing the page using <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd> ?

This should refresh the page, ignoring cached content, which might solve the issue.

**Comment by danPr0** [comment]
Now everything's fine. Don't know what was the cause of this issue.
