### ISSUE TITLE
[10.0] Cancelled (reversed) payment entries appear in bank reconciliation screen

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#18699]
### Impacted versions:

10.0 (and maybe others)

### Steps to reproduce:

1. Create a customer payment.
2. Create a reverse journal entry for the journal entry generated from Step 1 (upon realizing that there was a mistake).
3. Create a new customer payment (with correct content).
4. Go to bank statement reconciliation screen.

### Current behavior:

Journal items from above Steps 1-3 show and can be selected.

### Expected behavior:

Only the journal item from above Step 3 should show.

Although you could select all the journal items from Steps 1-3 and reconcile them all together (journal items from Steps 1 and 2 cancel out each other).  It does not appear to be a clean approach (if you forget to reconcile the journal items from Step 1 and 2 together with the one from Step 3, they need to be reconciled with some other random entries instead which does not make any business sense), and is confusing to the users.

There is currently no field in account.move.line to indicate whether the record should be eliminated from bank reconciliation in this scenario.  Would be good if Odoo could add this field and logic around it to handle this scenario nicely.

Slightly off topic, but I find the way Odoo currently handles payment cancellation/reversal not very clean:

 - you could reverse the journal entry of a payment, but there is no clear indication on the payment that it has been cancelled/reversed (as it does not come with "Cancelled" state for some reason)
 - when a journal entry is reversed, items with "reconcilable" accounts are not automatically reconciled (i.e. more unnecessary lines appear in bank reconciliation for liquidity transfer account in case inter-bank transfer is reversed)

### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7766939/29001947-760a1d58-7ac9-11e7-95e1-0e141a596246.png)

**Comment by nim-odoo** [comment]
Closed in https://github.com/odoo/odoo/commit/7544c22de9a4cea028ff8fe63931bf68573e0821 and https://github.com/odoo/odoo/commit/df755ef6d4b470b4083a2d0556c809e78627e4db , but from SaaS-14 since it is a major change in behavior.

However, this can be applied on a local v10 installation without problem.

**Comment by XeJames** [comment]
You need to be careful here.  There are scenarios where you WANT this to be fully transparent and the reversal needs to stay on the books.

1. E-Transfer to vendor. (reconcile to invoice)
2. Vendor cannot accept.
3. Cancel E-Transfer. (un-reconcile invoice)
4. Wire Transfer. (reconcile to invoice)

In truth, your paper bank statement WILL show all three entries and they all need to be reconciled to something.  In this scenario the original solution of simply reconciling all of the entries as a group is perhaps the only way that is fully transparent for audit.
