### ISSUE TITLE
[10.0] Cancelling bank reconciliation does not clear move_name field

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#18697]
### Impacted versions:

10.0 (and maybe others as well)

### Steps to reproduce:

Here we assume there was an inter-bank transfer from Bank A to Bank B, and user has already input such transfer through Accounting > Sales > Payments (with "Internal Transfer" payment type).

1. Create a bank statement for Bank A with a line for outgoing payment (to Bank B)
2. Reconcile the statement line by creating a journal entry (select liquidity transfer account) through bank reconciliation screen (which is a mistake).
3. Upon realizing the mistake in Step 2, cancel the reconciliation of the statement line (which does not clear `move_name` field).
4. Try to reconcile the statement line with a journal item from the internal transfer.

### Current behavior:

Following warning message appears, and it is not possible to reconcile the statement line with an existing journal item.

> Odoo Warning - Warning
> Operation not allowed. Since your statement line already received a number, you cannot reconcile it entirely with existing journal entries otherwise it would make a gap in the numbering. You should book an entry and make a regular revert of it in case you want to cancel it.

### Expected behavior:

There should be no such warning, or there must be an workaround to handle this scenario otherwise.

**Comment by yostashiro** [comment]
Here is a related PR: https://github.com/odoo/odoo/pull/15715

**Comment by nim-odoo** [comment]
As explained in the related PR, that's a standard behavior in order to make sure that there is no gap. So nothing can be done in a standard version.

**Comment by vcloud9ray** [comment]
Currently allowing users to remove the value in **move_name** by creating a Menu for Bank Statement Lines.  The tree view needs `editable="top"` and the move_name field added with `readonly="0"` and then users can easily find and edit entries that need to be reconciled after mistakes.
