### ISSUE TITLE
Uncaught TypeError: Cannot read property 'off' of undefined

### ISSUE THREAD

**Issue by chchow** [odoo/odoo#18696]
Impacted versions: 10.0

Steps to reproduce: 
1. Installed Odoo on Linode VPS with Apache2 using the instruction mentioned here: https://www.linode.com/docs/websites/cms/install-odoo-10-on-ubuntu-16-04
  - Git clone version: commit 2cd63aa2dc2ab0706922a660242b2132694e41a8
  - Ubuntu version: Distributor ID: Ubuntu
                               Description:    Ubuntu 16.04.3 LTS
                               Release:        16.04
                               Codename:       xenial
2. Created a new Database (Language: English, Country: Malaysia)
3. Everything seems ok until install any app (i.e. Sales or Purchase)
 
Current behavior:
**Chrome Browser**
```Uncaught TypeError: Cannot read property 'off' of undefined
https://xxxx/web/content/288-258b900/web.assets_backend.js:2898
Traceback:
TypeError: Cannot read property 'off' of undefined
    at Class.destroy (https://xxxx/web/content/288-258b900/web.assets_backend.js:2898:863)
    at Class.prototype.(anonymous function) [as destroy] (https://xxxx/web/content/251-04aeab5/web.assets_common.js:3010:559)
    at Class.destroy (https://xxxx/web/content/288-258b900/web.assets_backend.js:1625:332)
    at Object.<anonymous> (https://xxxx/web/content/288-258b900/web.assets_backend.js:1634:118)
    at fire (https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:299)
    at Object.add [as fail] (https://xxxx/web/content/251-04aeab5/web.assets_common.js:542:467)
    at Class.push_action (https://xxxx/web/content/288-258b900/web.assets_backend.js:1634:91)
    at https://xxxx/web/content/288-258b900/web.assets_backend.js:1666:170
    at https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:681
    at fire (https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:299)
```

**Firefox**
```

TypeError: this.$buttons is undefined

https://xxxx/web/content/288-258b900/web.assets_backend.js:2898
Traceback:
ChatAction<.destroy@https://xxxx/web/content/288-258b900/web.assets_backend.js:2898:850
OdooClass.extend/</prototype[name]</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:3010:556
WidgetAction<.destroy@https://xxxx/web/content/288-258b900/web.assets_backend.js:1625:320
ActionManager<.push_action/<@https://xxxx/web/content/288-258b900/web.assets_backend.js:1634:107
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.add@https://xxxx/web/content/251-04aeab5/web.assets_common.js:542:467
ActionManager<.push_action@https://xxxx/web/content/288-258b900/web.assets_backend.js:1631:66
ActionManager<.ir_actions_common/<@https://xxxx/web/content/288-258b900/web.assets_backend.js:1666:165
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:678
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.add@https://xxxx/web/content/251-04aeab5/web.assets_common.js:542:467
.Deferred/promise.then/</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:631
.each@https://xxxx/web/content/251-04aeab5/web.assets_common.js:370:758
.Deferred/promise.then/<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:553
.Deferred@https://xxxx/web/content/251-04aeab5/web.assets_common.js:548:189
.Deferred/promise.then@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:518
ActionManager<.ir_actions_common@https://xxxx/web/content/288-258b900/web.assets_backend.js:1666:104
ActionManager<.ir_actions_client@https://xxxx/web/content/288-258b900/web.assets_backend.js:1671:8
ActionManager<.do_action@https://xxxx/web/content/288-258b900/web.assets_backend.js:1660:15
.on_menu_action/</<@https://xxxx/web/content/288-258b900/web.assets_backend.js:1723:35
Mutex.prototype.exec/<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:3202:136
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:678
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.add@https://xxxx/web/content/251-04aeab5/web.assets_common.js:542:467
.Deferred/promise.then/</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:631
.each@https://xxxx/web/content/251-04aeab5/web.assets_common.js:370:758
.Deferred/promise.then/<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:553
.Deferred@https://xxxx/web/content/251-04aeab5/web.assets_common.js:548:189
.Deferred/promise.then@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:518
Mutex.prototype.exec@https://xxxx/web/content/251-04aeab5/web.assets_common.js:3202:98
.on_menu_action/<@https://xxxx/web/content/288-258b900/web.assets_backend.js:1722:279
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:678
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@https://xxxx/web/content/251-04aeab5/web.assets_common.js:548:31
DropMisordered<.add/<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:3218:259
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:849
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:849
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@https://xxxx/web/content/251-04aeab5/web.assets_common.js:548:31
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:849
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
.Deferred/promise.then/</</<@https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:849
jQuery.Callbacks/fire@https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@https://xxxx/web/content/251-04aeab5/web.assets_common.js:546:198
done@https://xxxx/web/content/251-04aeab5/web.assets_common.js:937:86
.send/callback@https://xxxx/web/content/251-04aeab5/web.assets_common.js:957:15
```

**Internet Explorer**
```
Unable to get property 'off' of undefined or null reference
https://xxxx/web/content/288-258b900/web.assets_backend.js:2898
Traceback:
TypeError: Unable to get property 'off' of undefined or null reference
   at destroy (https://xxxx/web/content/288-258b900/web.assets_backend.js:2898:850)
   at Anonymous function (https://xxxx/web/content/251-04aeab5/web.assets_common.js:3010:548)
   at destroy (https://xxxx/web/content/288-258b900/web.assets_backend.js:1625:320)
   at Anonymous function (https://xxxx/web/content/288-258b900/web.assets_backend.js:1634:107)
   at fire (https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:278)
   at self.add (https://xxxx/web/content/251-04aeab5/web.assets_common.js:542:467)
   at push_action (https://xxxx/web/content/288-258b900/web.assets_backend.js:1631:59)
   at Anonymous function (https://xxxx/web/content/288-258b900/web.assets_backend.js:1666:158)
   at Anonymous function (https://xxxx/web/content/251-04aeab5/web.assets_common.js:547:661)
   at fire (https://xxxx/web/content/251-04aeab5/web.assets_common.js:541:278)
````

After the above error, you will see no content in the main content area (right). No matter what you click on the left or top navigation.
![image](https://user-images.githubusercontent.com/1451026/28995513-9916c744-7a1d-11e7-988f-8ae006ce2502.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo JS related issue.

**Comment by chchow** [comment]
Is there any update on this?

I've tried using this installation method for Odoo 11 on Ubuntu 16.04:
https://www.odoo.yenthevg.com/installing-odoo-11-enterprise-ubuntu/

It turns out to be the same as below:

Error:
Uncaught TypeError: Cannot read property 'off' of undefined

https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:2096
Traceback:
TypeError: Cannot read property 'off' of undefined
    at Class.destroy (https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:2096:4781)
    at Class.prototype.(anonymous function) [as destroy] (https://techkono.com/web/content/303-bf006a0/web.assets_common.js:3811:488)
    at Class.destroy (https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:406:326)
    at Object.<anonymous> (https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:414:118)
    at fire (https://techkono.com/web/content/303-bf006a0/web.assets_common.js:796:299)
    at Object.add [as fail] (https://techkono.com/web/content/303-bf006a0/web.assets_common.js:797:467)
    at Class.push_action (https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:414:91)
    at https://techkono.com/web/content/304-aa6f268/web.assets_backend.js:449:170
    at https://techkono.com/web/content/303-bf006a0/web.assets_common.js:802:681
    at fire (https://techkono.com/web/content/303-bf006a0/web.assets_common.js:796:299)

**Comment by Yenthe666** [comment]
Hmm, I'm actually the author of this and I have multiple Odoo 11's running just fine. Could you post some more output of the log? Did all the commands finish successfully? Are there no issues in the log about it?
Cc @ged-odoo

**Comment by chchow** [comment]
I've just wiped my VPS clean and reinstalled using your script.
It works for my apache2 with no rewrite and proxyreverse, accessing only http://xxx:8069.

However, once a rewrite and proxyreverse for port 80-> 8069, this error appears. Below are my apache site conf:
`<VirtualHost *:80>
    ServerName xxxxx.com
    ServerAlias *.xxxxx.com

    RewriteEngine On
    RewriteCond %{SERVER_PORT} 80
    RewriteRule ^/(.*)$ https://xxxxx.com/$1
</VirtualHost>

<VirtualHost *:443>
    ServerName xxxxx.com
    ServerAlias *.xxxxx.com
    LogLevel warn
    ErrorLog /var/log/apache2/xxxxx.com.error.log
    CustomLog /var/log/apache2/xxxxx.com.access.log combined

    SSLEngine on
    SSLProxyEngine on
    SSLCertificateFile /etc/apache2/ssl/xxxxx.com.crt
    SSLCertificateKeyFile /etc/apache2/ssl/xxxxx.com.key
    SSLCertificateChainFile /etc/apache2/ssl/xxxxx.com.ca-bundle
    SSLHonorCipherOrder On
    SSLCipherSuite ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH
    SSLProtocol -ALL +TLSv1
    SSLCompression Off

    ProxyPreserveHost On
    ProxyPass / http://localhost:8069/ retry=0
    ProxyPassReverse / http://localhost:8069/

</VirtualHost>
`

I've had a feeling that it has something to do with Discuss app.
Below are the scenarios that leads me to suspect the Discuss app issue:
Scenario 1
1. load page xxxx.com
2. login to odoo backend
3. Discuss app are loaded by default. showing the web.assets_backend.js error mentioned in previous comments.
Result: Thereafter, sales/inventory/purchases/invoicing does not work but Apps/Website/Settings.

Scenario 2 (continues from scenario 1)
4. Click Sales, shows web.assets_backend.js error
5. Clicking on Apps/Website/Settings will recover the content area, making the backend admin workable.
Result: Discuss still does not work and weird page loaded.

Scenario 3 (continues from scenario 2)
6. Click Website app.
7. Go to Website
8. Entry to Sales/inventory/purchases/invoicing from top left drop down menu "Website" 
9. It works again until Discuss is selected which will trigger the same error

**Comment by ged-odoo** [comment]
This exact error is a JS error, which happens more in community, because the discuss app is the landing page (in enterprise, you have to click on the application, which takes more time).  The problem was that the messages are fetched before some buttons could be rendered, so if the user clicks quickly somewhere else, the client action is destroyed, but the buttons were not rendered.

This is fixed in commit https://github.com/odoo/odoo/commit/6182053c5af12fabf24b7194a3ca74858dbeb68a

Note that it was solved in saas-16, but was lost to a forward port in v11.0...  :(

**Comment by felipesadias** [comment]
Hi!! please tell us if you fixed that error, becouse I think that hapen when the web have SSL or proxy reverse...
