### ISSUE TITLE
[14.0] product template name does not update in database

### ISSUE THREAD

**Issue by Enikish** [odoo/odoo#187011]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [ ] 18.0
- [X] Other (specify)

### Steps to Reproduce

Install Product and Stock, create a new product template record then edit it's name.
It just does not change in the database, and other fields like list_price is normally changed.

**Comment by intero-chz** [comment]
Do you work with more than one language? The name is a translateable field.

**Comment by Enikish** [comment]
Yes, I installed and updated to zh_CN chinese.

**Comment by Enikish** [comment]
It workd, thank you.
