### ISSUE TITLE
[Master] (Stripe) Feature Request: Phase Out The Use of Checkout.js in Stripe in Favour Of Stripe.js

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#18710]
<h1>Impacted Versions:</h1>

- 11.0
- Master

<h1>Steps to Reproduce:</h1>

- Enable Alipay as a payment method in Stripe

- Enable alipay: true, in included JS to enable alipay with checkout.js

<h1>Current Behaviour:</h1>

- Outside of the USA Stripe will not accept Alipay and many other offered payment methods, despite supporting them.

- After many discussions with Stripe (support@stripe.com) I have been advised that unfortunately checkout.js is being deprecated in favour of stripe.js for use with the Sources API.

- All payment methods offered by Stripe currently, and any new methods introduced will be supported by the Sources API.

<h1>Expected Behaviour:</h1>

- The Odoo payment method for stripe can handle Alipay (for internationl payments), WeChat Pay, Giro, and many other new payment methods supported by Stripe (eg. bitcoin, SEPA, etc.).

<h1>Excerpt From Discussions With Stripe:</h1>
Here is a small excerpt from my discussions with Stripe's support team regarding integration:

"Checkout [1] is our prebuilt form for collecting customers' payment information, while Stripe.js [2] is a library you can use to achieve the same thing with a form of your own design."

"[1] https://stripe.com/docs/checkout
[2] https://stripe.com/docs/stripe.js"

"Regarding Odoo, I'm afraid that since they created their own integration with Stripe I can't really advise here. I'll have to ask you to get in touch with them directly to see how exactly they are using us and if they'd support our new API Sources."

This is a wishlist, however I think it would greatly improve the number of payment options supported in Odoo.

**Comment by pedrobaeza** [comment]
I see that this is still present in v11 and master: https://github.com/odoo/odoo/blob/6ad1a36b6eba2fcfee79641bde56cf6c4180001f/addons/payment_stripe/static/src/js/stripe.js#L164

@tbe-odoo I think you are the one that implemented this module, isn't it? Can you comment about this?

**Comment by pedrobaeza** [comment]
Thanks for the answer, Toufik. Do you think we should close this then?

**Comment by lukebranch** [comment]
@tbe-odoo ,

We've developed a custom payment method for an end-customer to use stripe.js instead of checkout.js, and would be happy to share our code with you by inviting you to a private repo, or sending a zip file to you if it is useful for you as a reference.

It provides more robust set of payment methods and it will be the way forward with Stripe (with new payment methods added), and checkout.js will be deprecated.

**Comment by lukebranch** [comment]
FWIW, it appears there's some work on a stripe rewrite to use stripe.js in this branch which is great news:

https://github.com/odoo-dev/odoo/tree/master-payment-stripe-rja

**Comment by lukebranch** [comment]
PR to master is here:

https://github.com/odoo/odoo/pull/25373

Once merged i'll close this feature request.
