### ISSUE TITLE
[10] Procurements run one by one instead of batch

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#18714]
Impacted versions: 10
Steps to reproduce: confirm multiple moves (with pick/ship setup)
The current code run all the procurement one by one at creation as they are not created with context option to not do a "run" at creation. Afterwards, procurements.run() does nothing anymore.
While this does not raise any traceback, this slow down the sale order confirmation.
Here is a fix:
Current behavior:
```
--- a/addons/stock/models/stock_move.py
+++ b/addons/stock/models/stock_move.py
@@ -485,7 +485,9 @@ class StockMove(models.Model):
         # create procurements for make to order moves
         procurements = self.env['procurement.order']
         for move in move_create_proc:
-            procurements |= procurements.create(move._prepare_procurement_from_move())
+            procurements |= procurements.with_context(
+                procurement_autorun_defer=True).create(
+                    move._prepare_procurement_from_move())
         if procurements:
             procurements.run()
```

**Comment by jco-odoo** [comment]
Indeed, this can speed up some things.

**Comment by sle-odoo** [comment]
Hi,
Sadly we won't make such a change in stable versions. We have a task to try to process procurement by batch (which is complicated since there aren't procurements anymore :) as well as the push rules.

Thank you for the suggestion,
Regards
