### ISSUE TITLE
stop auto kanban emails

### ISSUE THREAD

**Issue by sachinbanugariya** [odoo/odoo#18726]
hello,

using odoo version 8.
we need to stop auto  generated emails from kanban when drag-drop applications from recruitment process job application.

can you please explain from where i can stop to send auto emails(like Application Approved, Application refused) to applicant from kanban.
need to send mails to applicant if we click on send messages and applicant mail.

not want to send any auto generated mails to applicant of application.

please reply ASAP.
Thanks.

**Comment by Yenthe666** [comment]
Hi @sachinbanugariya,

Thank you for your report.
The Github tracker is however for bugs in the default code. It is not the place to ask questions about custom development or how to do things functionally (as you're asking).
Please post this question on the official help forums (help.odoo.com).

Regards,
Yenthe
