### ISSUE TITLE
[18.0] sale_pdf_quote_builder; system doesn't pull header to the quote

### ISSUE THREAD

**Issue by lyusikov** [odoo/odoo#187514]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

**Steps to reproduce your errors:**
1. Go to the Sales - Configurations - Quotation Template
2. Go to the Quote Builder tab
3. Add header PDF Template.
4. Add New Quote, choose Quotation template
5. Print Quote
6. System returns only page with components, without Header page (in version 17 system returned Header Page and page with components)

**Expected behavior**
6. System returns Header Page and page with components, just as in 17th version
_____________
I've tested this on different Odoo 18 instances with different Headers (including Odoo example) as well as on the Odoo runbot

**Files**
Original Quotation Template
![image](https://github.com/user-attachments/assets/0c24de85-8746-4bf2-b02a-0b56d37c01f9)
Quote
![image](https://github.com/user-attachments/assets/9763f423-f2e7-4f11-a353-8fab930bb6dd)

**Comment by Demesmaeker** [comment]
Hello @lyusikov 
Yes, the quote builder changed a lot in 18.0, we don't enforce header and footer anymore, but now also allows to put more than one header, or one footer, or also to choose which product document you want included.
You can also, now, map more values to any form field inside your PDF. Or write any custom text to a non-mapped form field.

Once on the sale order, you'll see a new tab, the "Quotation Builder" one. There, you can choose and fill any form fields non mapped with custom text.

I'm sorry the documentation is a bit late, but it should be updated soon.

Have a nice day
