### ISSUE TITLE
email_from in template

### ISSUE THREAD

**Issue by seacom** [odoo/odoo#18764]
Impacted versions: 10

Steps to reproduce: Create an incoming mailserver, then select "Create new recors" inserto project.issue, and and as action select send email, in the email template in the to field put: ${object.email_from}

Current behavior: Some email address show escape char: for example instead of 
Lorenzo Fascì <lorenzof@seacom.it>, it the email I see  Lorenzo Fascì &lt;lorenzof@seacom.it&gt;

Expected behavior: Correct to address and email sent

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is not done this way, but configuring on the project the mail alias for issues and having a generic catchall incoming server. This way, everything should be handled without problems.

Closing as no real issue.
