### ISSUE TITLE
Many ir.attachment are unprotected available from the internet

### ISSUE THREAD

**Issue by thomas-work** [odoo/odoo#18766]
Impacted versions:
ODOO10

Steps to reproduce:
Add an attachment for a public readable model.

For example the module event has the model security rule.
access_event_event_portal | event.event.portal | model_event_event |   | 1 | 0 | 0 | 0

It means, that the event is readable without any restriction by any user. It's needed for event confirmation. If someone adds an attachment to the event with the "document" app (Attachments List and Document Indexation) or a custom module, all attachments are available by everyone. You only need to probe some ids.

Same for event.registration. 

There are some more places with global public access rules. I did not check, whether it's a problem there too.

Current behavior:
All attachments are readable without permission. The website_event module is not installed.

Expected behavior:
The file should be accessible only by internal users.

**Comment by wardm95** [comment]
Another thing related to this issue are the contact images. You can access all of them without being logged in as a user.
For example:
If you add this to the url of a runbot: `http://[your odoo URL]/web/image/res.partner/3/image?`, you will see the picture of the contact Administrator.

**Comment by pedrobaeza** [comment]
I'm afraid this is the current behavior of attachments: if you have access to the record, you can access their attachments, because you can need also the contrary: that the attachment should be available. There should be a great architecture change for managing permissions of attachments isolately from record permissions. @mart-e do you know if there's something planned about this?

About the images, it's more or less the same reasoning, but in this case you control through the published in website toggle button what do you want to be seen.

**Comment by thomas-work** [comment]
I have started a workaround for this design issue, but it's far from completed. I had to stop working on it last year. The idea is very simple.

I have added an access_key to every file, which is initialized on create
```
access_key = fields.Char('Download access key', readonly=True)
values['access_key'] = random_hex(8)
```
I added some mote path like /web/scontent/<string:access_key>/... and added access_key parameter to every binary_content occurrence.

This change does not solve the design issue, but it disallow the attacker from probing the files by id.

Maybe some portal user can download all files like invoices, drafts... But I did not check it. 

Currently all assets are generated and delivered correctly. But there is still a lot of work to do.
Currently it works only on ir.attachment and not on embedded files like /web/image/res.partner...

**Comment by mart-e** [comment]
As Pedro said, if you have access to the record, you have access to the linked attachments.
Sorry but I don't see the issue here.

**Comment by thomas-work** [comment]
It's not a bug. It's a design issue.
You can download all documents by probing the ids of the ir.attachments.
If a model is readable by everyony, all documents linked to a record of this model are readable by a simple increment id by one and try again attack. Even if the main record is unpublished or has no website components, the documents are downloadable.

**Comment by pedrobaeza** [comment]
@mart-e I also see as a feature that it's needed for records exposed publicly (events, partners with website_partner, etc), which will expose also their attachments, which is a potential leak of information, as people can attach things in the backend without being aware of that is accessible.

**Comment by mart-e** [comment]
I have troubles to understand exactly the design issue what you are reporting.
Are you saying somebody that has _no_ access to an event is able to fetch its attachments?

**Comment by thomas-work** [comment]
It's easy. I have installed only the modules event and document. Created an event, uploaded a file and copied the link of the file. 
In my case it's http://localhost:8069/web/content/270?download=true
Download the file from another browser or private session without login. There is no permission check in the binary_content for the record, only for the modell access. By disabling the global read access of event.event.portal, the file is protected.

**Comment by mart-e** [comment]
Sorry but, I confirm, the right fix is to set a group on the access rule instead of public. This is by design.

**Comment by thomas-work** [comment]
It's not possible to use a read only public model with protected files? This is needed in cases like double opt-in with file upload (e.g. CVs). How can I restrict the download without restrict the read access for the double opt-in?
