### ISSUE TITLE
[saas-16] On debug mode buttons are not showing the popover properly

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#18790]
Impacted versions:

>saas-16

Steps to reproduce:

Open Any wizard with debug mode enabled, put the mouse on the button nothing shown.

Current behavior:

Nothing shown.

![image](https://user-images.githubusercontent.com/338634/29168811-3935d97e-7d96-11e7-80b1-ac9aa451b548.png)

Expected behavior:

Works as oldest version works.

![image](https://user-images.githubusercontent.com/338634/29168909-bfe28b48-7d96-11e7-9d72-5a6f4957cad7.png)

**Comment by Yenthe666** [comment]
Hi @nhomar,

Thanks for the response. This is indeed gone in SaaS-16.
@mart-e another one 😉 

Regards,
Yenthe

**Comment by mge-odoo** [comment]
Thanks for reporting the bug @nhomar ; it has been fixed in 11.0.
