### ISSUE TITLE
[9.0] [10.0] CSV export with extra quote on negative values

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#18798]
**Impacted versions:**

- 9.0
- 10.0
- 11.0
- 12.0

**Steps to reproduce:**

Login on runbot, go in Inventory stocks.
Edit a stock move to give it a negative value

Not the best example but you can do that on any object with a float or int value.

For Integer value this can be tested with seats_min on `event.event` object.

**Current behavior:**

An extra `'` is added before the negative sign. (you will have to look closely)

```
"id","product_uom_qty","quantity_done_store","quantity_done","name"
"__export__.stock_move_156","4.0","0.0","0.0","MO/00003"
"__export__.stock_move_157","'-4.0","0.0","0.0","MO/00003"
```

```
"id","seats_min"
"event.event_3","'-20"
```

**Expected behavior:**

No negative unwanted quote.

Video/Screenshot link (optional):

**Comment by yvaucher** [comment]
This is due to https://github.com/odoo/odoo/blob/10.0/addons/web/controllers/main.py#L1384

Unfortunately this makes exported values not importable.

For instance:

![2017-08-10-171046_567x348_scrot](https://user-images.githubusercontent.com/4158438/29177441-01da96e6-7def-11e7-8ab2-a8c3acce664c.png)

**Comment by Yenthe666** [comment]
@mart-e is there any reason why this was done? I don't see the logic in this.

**Comment by xmo-odoo** [comment]
@Yenthe666 comment in the first line of the snippet

**Comment by Yenthe666** [comment]
Oh, totally missed that, thanks.

**Comment by xmo-odoo** [comment]
Note that the intent was clearly to only do that for strings (though I don't know that it's handled on the import side either) *but* the historical `_export_rows` thing converts *everything* to strings by default.

The Excel exports opts into "raw" export in order to generate proper values (e.g. numbers, dates, …) instead of typing everything as strings, the CSV export does not and thus prefixes plain numbers which don't need to be, which is the issue here.

**Comment by pedrobaeza** [comment]
@mart-e @xmo-odoo there's a PR for this on hold for a long time. Can you please check?

**Comment by qndi** [comment]
This issue applies also für version 12

**Comment by yvaucher** [comment]
@qndi thanks for reporting, I added 11.0 and 12.0 as impacted version in issue description.

**Comment by yvaucher** [comment]
Seems the follow up is there: https://github.com/odoo/odoo/pull/26724

**Comment by mart-e** [comment]
Hi,

This was changed in master at #26724 to always use the raw mode in export, you will get the same content in CSV and XLS export.
Thanks for the report
