### ISSUE TITLE
[Translations]  IntegrityError message not tranlsted

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#18792]
Impacted versions:
 10.0CE

Steps to reproduce:

Current behavior:

```
msg = _('The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set')
```

this message is not translated.

Expected behavior:

should translated.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e I've noticed this one before too actually. Could you have a look?

**Comment by mart-e** [comment]
Hello,

Could you please give me a way to reproduce it? I suspect a loss of context so I need a scenario to reproduce and trace it.

**Comment by pedrobaeza** [comment]
Closing as no answer.
