### ISSUE TITLE
POS Mercury Module of version 10 is not functioning properly

### ISSUE THREAD

**Issue by vicky198609** [odoo/odoo#18805]
Impacted versions: version 10

Steps to reproduce: Install https://www.odoo.com/apps/modules/10.0/pos_mercury/ this module and try swapping  different card. It will neither give you fronted error nor it say anything in logs.

Current behavior:Install https://www.odoo.com/apps/modules/10.0/pos_mercury/ this module and try swapping  different card. It will neither give you fronted error nor it say anything in logs.

Expected behavior: It should read the Cards and process the payment.

Video/Screenshot link (optional):

**Comment by jorenvo** [comment]
@vicky198609 what card reader are you using and how have you connected it?

**Comment by Yenthe666** [comment]
Hi @vicky198609,

Could you please let us know which card reading you are using and how you've connected it?
