### ISSUE TITLE
[10.0]The channel member list of mention menu was not updated while new member was joined.

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#18808]
Impacted versions:
10.0
Steps to reproduce:
Login as Administrator, create a new private channel in Discuss module, then invite a new member to join the channel, at the chat composer textarea, type '@' char to activate mention list menu.
Current behavior:
No new joined member was appeared in the mention list menu, except manually reload the Discuss page.
Expected behavior:
The new joined member appeared in the mention list menu without page reloading.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this is something reasonable for not overloading background network activity reloading a lot of components. Refreshing browser page is a normal activity for other things like reloading changed views and so on, so this is also acceptable.

Closing by the reasons stated above.
