### ISSUE TITLE
[10.0] MRP not filtering by Internal Reference nor Barcode

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#18817]
Impacted versions:
10.0, maybe others.

Steps to reproduce:
- Go to Manufacturing -> Master Data -> Bill of Materials.
- Create a new BoM.
- Look for product by its internal reference or barcode.

Current behavior:
- Product not found by internal reference.
- Only those shown are the ones that contain the searched characters within its name.

Expected behavior:
- Be able to filter products by its internal reference or barcode.

Video/Screenshot link (optional):
https://youtu.be/s9UovzEAtn8

**Comment by Yenthe666** [comment]
@jco-odoo perhaps it is nice to have this working?

**Comment by amoyaux** [comment]
Seems to be fixed in 10.0 and 11.0
