### ISSUE TITLE
[Wishlist] master: upgrade Bootstrap from 3.4 to 4.0

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#18811]
Impacted versions: master

Currently Odoo is using bootstrap 3.x (https://github.com/odoo/odoo/tree/10.0/addons/web/static/lib/bootstrap) but today the beta for V4 came out. You can find all information here: http://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/
It would be great to ship Odoo 11 with bootstrap 4.

Regards,
Yenthe

**Comment by lukebranch** [comment]
Stable is now here as of the 18/01/2018:

http://blog.getbootstrap.com/2018/01/18/bootstrap-4/

It would be great to have BS4 in Odoo 12.0

**Comment by Yenthe666** [comment]
Hi @lukebranch,

Indeed, I saw the release notes today too!
@JKE-be this is your cue to add it in the master version. 😄 

Regards,
Yenthe

**Comment by hanyelbanna** [comment]
Will you transfer from LESS to SASS?

**Comment by Yenthe666** [comment]
A first step has been made from bootstrap 3.3.4 to 3.3.7 at https://github.com/odoo/odoo/commit/126850e9bd66175985b562eb4c912f1e352097c0 - which is the preparation step before bootstrap 4.

**Comment by JKE-be** [comment]
@qsm-odoo Is working on the sass/less/sass conversion
While @rdeodoo works on sass "engine"

I permit to closes this issue since it is just a discussion ;)
But yes, v12 (or previous saas version) should be with bootstrap 4  and with jquery 3

**Comment by Yenthe666** [comment]
@JKE-be thanks for the feedback. I vote for to keep it open as a reminder and a place to get input though. If it is closed barely anybody will see/find it. Should it really be closed?

Anyways, great that we'll get bootstrap 4 and jQuery 3!

**Comment by Yenthe666** [comment]
The task / PR is on the way at https://github.com/odoo/odoo/pull/25045 by the way!
