### ISSUE TITLE
[9.0] Can't set False as default on Many2one

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#18829]
Impacted versions:
9.0
Steps to reproduce:
1.-  Create a new  module
2.- create a new field type m2o
3.- set default=function_get_default,
4.- def function_get_defult(self):
           if some_condition:
              return register.id
           elif return_false:
                return False
 
Current behavior:
1.- on case some_condition for exists record work fine, and return id
2.- on case we want return False or non exists record, odoo try get id from bool
3.- on case we don't return values, odoo try get id from NoneType
Expected behavior:
if value dont exists or is False, or None,  don't try to get id from it

**Comment by gdgellatly** [comment]
return self.env['register']

**Comment by dansanti** [comment]
@gdgellatly works!, thanks
