### ISSUE TITLE
[11.0] Supplier Currency when creating invoice in purchase order

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#18825]
**Impacted versions:** 11.0

**Steps to reproduce:**

To reproduce it is necessary to select a supplier with a different currency than the main currency

- Create a sales order with a product that triggers a purchase order

![so094 odoo](https://user-images.githubusercontent.com/5775695/29241855-4dba0fee-7f50-11e7-8979-101e7a268f07.png)

- Look for the related purchase order and receive the product

![po00039 9 20 odoo](https://user-images.githubusercontent.com/5775695/29241986-7fbe2640-7f52-11e7-9621-f8e6b11401eb.png)

- Create an invoice for the purchase order

**Current behavior:**

The currency of the invoice does not match the vendor's currency by default, always take the company's currency

![new odoo 3](https://user-images.githubusercontent.com/5775695/29242024-54fb9ec8-7f53-11e7-8fd0-9813f47c0210.png)

![supplier test odoo](https://user-images.githubusercontent.com/5775695/29242051-c48de836-7f53-11e7-989a-4bd80175520d.png)

**Expected behavior:**

The currency for billing must match the purchasing currency used by the supplier

**Video/Screenshot link (optional):**

https://youtu.be/vcAf4PL76UM

**Comment by simongoffin** [comment]
@deivislaya In fact, this is not a bug. To avoid this problem, you have to define a journal with type purchase in EUR. The currency of a bill is always in the currency of its journal.

**Comment by deivislaya** [comment]
@simongoffin Thanks you
