### ISSUE TITLE
Error in query outside http request

### ISSUE THREAD

**Issue by triplustri** [odoo/odoo#18828]
When I try select records from (for example) res.user like this:
    
    with api.Environment.manage():
        registry = RegistryManager.get(db_name)
        with registry.cursor() as cursor:
            environment = api.Environment(cursor, None, {})
            environment['res.user'].search([])

I get an exception

    Traceback (most recent call last):
      ...
      File "/opt/odoo10/odoo/models.py", line 4200, in _generate_order_by
        order_by_elements = self._generate_order_by_inner(self._table, order_spec, query)
      File "/opt/odoo10/odoo/models.py", line 4167, in _generate_order_by_inner
        raise ValueError(_("Sorting field %s not found on model %s") % (order_field, self._name))
    ValueError: Sorting field model_id not found on model ir.rule

So it happens with any models. But everything is fine if I make a request in the controller method or in the method of the model.

In addition, I can say that the models obtained in this way `_fields` field is empty

**Comment by pedrobaeza** [comment]
I see several problems in your code:

* It's not `res.user`, but `res.users`.
* You are creating a new environment on a very weird way, even creating a new cursor. This will lead inevitably to errors.

Closing this as no real issue, but misuse of the ORM.
