### ISSUE TITLE
http.route url just work on browser

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#18833]
Impacted versions: 10c

Steps to reproduce: I created controller.py then add route like
```
@http.route('/api/check', type='http', auth='public', methods=['GET'], csrf=False)
	def check(self, **params):
		return 'Check Success'
```

Current behavior: When i called from browser it works properly, but when i call from other python code like:
```
import requests

url = 'http://localhost:8069/api/check'
r = requests.get(url)
print r
```

it gives me error 404

Expected behavior: call from python requests should works properly

Video/Screenshot link (optional):
![screenshot from 2017-08-14 12-05-06](https://user-images.githubusercontent.com/7473166/29259094-b01c8d7a-80e9-11e7-9cf3-f56fd7eeab45.png)
![screenshot from 2017-08-14 12-07-35](https://user-images.githubusercontent.com/7473166/29259095-b76467e2-80e9-11e7-8ba8-2b8b1e7f18ce.png)

**Comment by CakJuice** [comment]
it's not work properly because i have multiple database on my server. Then i delete other database, it works done.

**Comment by xmo-odoo** [comment]
Yeah if you have multiple databases you'll need to either run in mono-db mode (`--db-filter=<a database>`) or add sessions support and first select one of the dbs so that it's associated with your client.

**Comment by CakJuice** [comment]
@xmo-odoo thanks for your explanation
