### ISSUE TITLE
UnicodeDecodeError when Postgresql report errors in UTF8.

### ISSUE THREAD

**Issue by csrocha** [odoo/odoo#1884]
When Postgresql report an error in an UTF8 environment, logger raise a UnicodeDecodeError exception.

**_Impacted versions:**_
- 8.0

**_Steps to reproduce:**_
1. Set your unix in locale Spanish.
2. Add a not existing column in a SQL query.
3. Execute the query

**_Current behavior:**_

This the error:
-   File "/home/crocha/Proyectos/odoo/sba_homo/local/lib/python2.7/site-packages/openerp-8.0rc1-py2.7.egg/openerp/netsvc.py", line 120, in format
  return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/**init**.py", line 474, in format
    s = self._fmt % record.__dict__
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)

**_Expected behavior:**_
- Just the SQL error.

**Comment by Yenthe666** [comment]
Hi @csrocha,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
