### ISSUE TITLE
[18.0] enterprise /l10n_it_pos: error on calculation of VAT on POS

### ISSUE THREAD

**Issue by MarcoCalcagni** [odoo/odoo#188528]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

Look the video . one with the enterprise/l10n_it_pos  NOT installed and the behavior is OK , the secon one with the module installed and tha vat calculation is wrong. 

If I use a product with the tax included the pos module add again the tax and the total is wrong. 
if I change the price it must be taxes included.
the videos are very explanatory

[Uploading Modulo It10n_it_pos-Punto vendita.webm…]()
[Uploading NO-Modulo It10n_it_pos-Punto vendita.webm…]()

**Comment by MarcoCalcagni** [comment]
Link to the video (I'm not sure if git loaded them) :-)  
https://dinamicheaziendalisrl-my.sharepoint.com/personal/mcalcagni_dinamicheaziendali_it/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmcalcagni%5Fdinamicheaziendali%5Fit%2FDocuments%2FNO%2DModulo%20It10n%5Fit%5Fpos%2DPunto%20vendita%2Ewebm&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ed4107bac%2D8080%2D45a1%2D8448%2Da1504418d9be

https://dinamicheaziendalisrl-my.sharepoint.com/:v:/g/personal/mcalcagni_dinamicheaziendali_it/EWd56lf8rDVBinAcfNeA2s8BYatLj40-1LoRQo_IK3e3TA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=vwLN53

**Comment by caburj** [comment]
Hello @MarcoCalcagni. Can you provide a more public links of the videos? I don't have a microsoft account to download them.

**Comment by MarcoCalcagni** [comment]
Hi @caburj 
link on google 

https://drive.google.com/file/d/111osmkUTEVypyqZhtQomB5CbGo2rpWJ0/view?usp=sharing, https://drive.google.com/file/d/118XwojdPhD28e5xkHG7gwb0onU3cMu6W/view?usp=sharing

let me know

**Comment by MarcoCalcagni** [comment]
video on youtube 
https://youtu.be/ns55CFntkqM
https://youtu.be/N6Xp6qV3a0g
