### ISSUE TITLE
7.0 - master: onchange and default methods called from yaml tests are run as superuser

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#1885]
If you set the user for a yaml test, it will not be used for onchange and default methods (admin is used instead).

This looks to me like a bug as it can hide bugs in onchange and default methods without saying.

Observed in v7 but it is still there in master AFAIK.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
