### ISSUE TITLE
Access Security loophole: user can create Project Tags without "create" access for that Model

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#18879]
Impacted versions:
10.0

Steps to reproduce:
Log in as "demo" user, edit a Task, type some text in the "Tags" field and select "Create ...".

Current behavior:
The new Tag is created.

Expected behavior:
Only the Project Manager has access to "Create Tags".
User Demo should no be able to create a new Tag.

This seems a generic issue with x2x fields.
Might be related to https://github.com/odoo/odoo/pull/15243

**Comment by rco-odoo** [comment]
There is no security issue: the user Demo belongs to the group "Project Manager"...

**Comment by dreispt** [comment]
Sorry @rco-odoo - I created a "test" user with Project User access, and indeed was unable to create a Tag.
