### ISSUE TITLE
[10.0] product: Display variants name with a single or multiple possible attribute values

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#18878]
Impacted versions:
10.0
Steps to reproduce:
In v9.0
![image](https://user-images.githubusercontent.com/10233975/29373928-5497db52-8275-11e7-8754-0ee108c96a7d.png)
![image](https://user-images.githubusercontent.com/10233975/29374015-8e9c89ec-8275-11e7-8512-734f3fd71bf4.png)

Current behavior:
v10.0
![image](https://user-images.githubusercontent.com/10233975/29374021-9978de7e-8275-11e7-827d-948d4a7e21a3.png)

![image](https://user-images.githubusercontent.com/10233975/29374079-d23b1466-8275-11e7-9eca-1412f2ee307d.png)

# Expected behavior:

### In order to be consistent with v9.0, the desired behavior is to display variant name including attribute value doesn't matter if there is just one attribute value, also will be nice if the inner `_name_get` function be declared outside of the `name_get` function

https://github.com/odoo/odoo/blob/master/addons/product/models/product.py#L350-L355

![image](https://user-images.githubusercontent.com/10233975/29374227-3de1adba-8276-11e7-9ae5-45459e47b69c.png)

**Comment by ThijsvOers** [comment]
Hi @hugho-ad,

Installing the (free) third party module (from Pledra) product_configurator_base may solve this problem. I found it a very powerful module to make better use of product variants. Reasons;
- after configuring the attributes and attributes values not all the variants are created immediately. This only occurs when the configurable product is sold. 
- You can add restraints to steps. 
- last but not least, after selecting the product the different attribute values will be shown in the product header:)

Kind regards,
Thijs van Oers
Onestein

![bank onestein rood leer odoo](https://user-images.githubusercontent.com/30256071/29458984-0b9a8f40-8422-11e7-8347-989253382839.png)

**Comment by hugho-ad** [comment]
@ThijsvOers  thanks for your input!, But the module product_configurator_base adds extra behaviors that are not desired to only change the product display name, I think we can accomplish this by only changing this line
https://github.com/odoo/odoo/blob/master/addons/product/models/product.py#L371
s/len(l.value_ids) > 1)/len(l.value_ids) **>=** 1)

Or make this [function](https://github.com/odoo/odoo/blob/master/addons/product/models/product.py#L350-L355) out of the `name_get` function scope, in order to allow us to inherit it and set the name structure that we could need.

**Comment by kholioeg** [comment]
Changing the mentioned line as per the instructions fixed the issue correctly. 
From:
`            variable_attributes = product.attribute_line_ids.filtered(lambda l: len(l.value_ids) > 1).mapped('attribute_id')`

To:
`            variable_attributes = product.attribute_line_ids.filtered(lambda l: len(l.value_ids) >= 1).mapped('attribute_id')`

This should be the fix.

**Comment by fgi-odoo** [comment]
We made this change on purpose. Setting only one attribute value on the product only helps search the product catalog as a customer or product manager (using the attribute filters). A product can have dozens of such attribute values. It didn't make sense to display them as part of the product name if they weren't used to flag specific variants.
