### ISSUE TITLE
[8.0] Unable to differentiate rights in website builder / ir_qweb.py

### ISSUE THREAD

**Issue by anderswallenquist** [odoo/odoo#1887]
I want users in the group base.group_website_publisher to have the right to edit pages and create new pages, but without the right to change theme, edit HTML/CSS or install new apps. Usually you have web-editors that have daily responsibilities with the site, creating new pages, simple text editing and change images here and there. Responsibilitis for content in short.

The web designer on the other hand are responsible for the look and feel of the site. Working with theme and HTML/CSS and adding new apps. When a design are ready there are not a daily routine to change it. You don't want a web-editor to change the layout or function of the site from one day to another. 

The navbar have one menu for web-editors "Content" and another for the web designer "Customize".

If I change groups for the "Customize"-menu to (for example base.menu_administration) the web-editor (base.group_website_publisher) no longer can change "Content". In spite of group=base.group_website_publisher that are pinned on the Edit-button its disabled due to the group=base.menu_administration on the Customize-menu. The web-editor has to belong to all groups on the entire page to have the right to edit. base/ir/ir_qweb->render_node (261) "Editor disabled because some content can not be seen by a user who does not belong to the groups %s"

template website.user_navbar:

```
   <!-- Customize -->
        <li class="dropdown" id="customize-menu" groups="base.menu_administration">
            <a id="customize-menu-button" class="dropdown-toggle" data-toggle="dropdown" href="#">
                Customize <span class="caret"/>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#advanced-view-editor" data-action="ace">HTML Editor</a></li>
                <li><a href="/page/website.themes">Change Theme</a></li>
                <li><a href="/web#return_label=Website&amp;action=website.action_module_website">Install Apps</a></li>
                <li class="divider"/>
            </ul>
        </li>
```

What is best practice in this case?

**Comment by Develoman** [comment]
Hi,
The same needs!

**Comment by Yenthe666** [comment]
Hi @anderswallenquist ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: This would be more of a wishlist thing or custom development though, as you can't do that all out of the box.

Regards,
Yenthe
