### ISSUE TITLE
[10.0] analytic tags access group for sale.order.line?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#18875]
Impacted versions:
10.0
Steps to reproduce:
If no analytic group is set for user, I can still see analytic tags field from sale order line form.
Current behavior: (form ID: `sale.view_order_form`).
```xml
....
....
<label for="analytic_tag_ids"/>
    <div>
        <field name="analytic_tag_ids" widget="many2many_tags"/>
    </div>
...
...
```

Expected behavior:
```xml

.....
.....
<label for="analytic_tag_ids" groups="analytic.group_analytic_accounting"/>
    <div>
        <field name="analytic_tag_ids" widget="many2many_tags" groups="analytic.group_analytic_accounting"/>
    </div>
....
....
```

Other references to this field in sale.order.line uses that access group. So it does not make sense that in form, that group is not used for that field.

**Comment by Yenthe666** [comment]
@qdp-odoo I believe this makes sense. Okay for you? I'll make you a PR then.

**Comment by qdp-odoo** [comment]
yes fine for me
