### ISSUE TITLE
[17.0] module: stock

### ISSUE THREAD

**Issue by vojtakropibtl** [odoo/odoo#188814]
### Odoo Version

- [ ] 16.0
- [X] 17.0
- [ ] 18.0
- [ ] Other (specify)

### Steps to Reproduce

In def _set_lot_ids(self): on line 539 reserved_quants = self.env['stock.quant']._get_reserve_quantity(move.product_id, move.location_id, 1.0, lot), there should be lot_id=lot. The fucntion takes 9 parameters and it passes the lot as wrong parameter. Its fixed on version 18 already but not in version 17

### Log Output

If we try to assign SN on STOCK IN it changes after save.

**Comment by vava-odoo** [comment]
Hi @vojtakropibtl 
Issue was solved with https://github.com/odoo/odoo/commit/28f5b2244954a8aaa2a7c2599b0716c88a55e5f0
Thanks for reporting
