### ISSUE TITLE
[10.0] Overriding computed field value

### ISSUE THREAD

**Issue by YnievesDotNet** [odoo/odoo#18882]
Impacted versions:
10.0

Steps to reproduce:
1 - adding in custom module the field
`display_name = fields.Char(compute='_compute_display_name', store=True, index=True)`

2 - redefining the function _compute_display_name in the custom module
```
    @api.depends('is_company', 'name', 'parent_id.name', 'type', 'company_name', 'documentnumber')
    def _compute_display_name(self):
        self.display_name = self.documentnumber + '-' + self.name
```
3 - editting one funtion working and adding the line self.display_na......
```
    @api.onchange("is_company")
    def _onchange_company(self):
        if self.is_company is True:
            self.documenttype = '31'
        else:
            self.documenttype = '13'

        self.display_name = self.documentnumber + '-' + self.name
```

Current behavior:
Doing any step along, dont work.
The step 1 and 2, nothing.
The step 1, 2 and 3, nothing, but the if of step 3 working fine.

Expected behavior:
Update the display_name value to concatenate documentnumber and name using '-' as joinner.

Video/Screenshot link (optional):
none

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
