### ISSUE TITLE
[10.0] server error when trying to download attachment whose file name includes non-ascii characters

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#18897]
### Impacted versions:

10.0.  Probably other versions as well.

### Steps to reproduce:

1. Install website_sale_digital
2. Attach a file with name "テスト" to a product that is sold on website
3. Purchase the product and make a payment.  Go to My Orders under My Account, open the order, and try to download the file "テスト".

### Current behavior:

Odoo throws server error and nothing is downloaded.

### Expected behavior:

No server error and the file should be downloaded as normal.

**Comment by Yenthe666** [comment]
@mart-e encoding issue?

**Comment by Yenthe666** [comment]
Hi @yostashiro,

Thanks for the report.
It has been fixed by @nim-odoo in https://github.com/odoo/odoo/commit/110bf158f68cc3066dc8cd1f6e47b1dd04ae7fac

Regards,
Yenthe

**Comment by yostashiro** [comment]
@Yenthe666 @nim-odoo Thank you!  I have confirmed that the issue has been fixed.

**Comment by Yenthe666** [comment]
Great to hear that. Good job guys!
