### ISSUE TITLE
7.0: move a picking with three lines in three different days: the middle one is not moved

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#1889]
To reproduce:
- create a picking with three lines, expected respectively in the 10th, 11th, 12th of the month. 
- go to the calendar view
- with the mouse, move it to the next week, for example starting the 17th.
- update the page.

Expected result: the picking starts the 17th and ends the 19th.
Actual result: the picking starts the 11th and ends the 19th.

Reason: the inverse function of min_date and max_date of the picking does not change the date on the middle.

Moreover, the docstring is incorrect and out of date. A test would really help for a situation like that.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
