### ISSUE TITLE
[saas-17]  Erroneous view of dates in analytic account lines

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#18906]
**Impacted versions:** saas-17

**Steps to reproduce:**

- Configures the user's time zone to mexico city

![agrolait agrolait odoo 1](https://user-images.githubusercontent.com/5775695/29435889-f16a04c6-8376-11e7-8221-40afbdd02af9.png)

- Edit an analytic account

![agrolait agrolait odoo](https://user-images.githubusercontent.com/5775695/29435897-f8fce9ec-8376-11e7-876b-e4d4a39fc3f4.png)

**Current behavior:**

- The selected date does not match the date shown on the line

![agrolait agrolait odoo 2](https://user-images.githubusercontent.com/5775695/29436081-f4244b80-8377-11e7-889f-a9059bc71496.png)
![agrolait agrolait odoo 3](https://user-images.githubusercontent.com/5775695/29436096-0bd874fe-8378-11e7-8abe-96c2db932526.png)

**Expected behavior:**

The select date and shown date must match on the line

**Video/Screenshot link (optional):**

https://youtu.be/_tS-zWPLjfI

**Comment by pedrobaeza** [comment]
Date format is not associated to the timezone, but to the interface language, so there's no real issue here.

Closing by the statement above.
