### ISSUE TITLE
[10.0] Received quantities are not getting updated on a PO when returning products

### ISSUE THREAD

**Issue by benwillig** [odoo/odoo#18900]
**Impacted versions:**
8.0, 9.0, 10.0

**Steps to reproduce:**
- Create a Purchase order
- Add stockables products
- Confirm the PO
- Receive all products (received quantity is updated)
- Go on the previously validated picking, return some products to the provider and validate the new picking

**Current behavior:**
After returning products from a picking linked to a purchase order, received quantities on purchase order lines are not updated.

**Expected behavior:**
Received quantities should be updated.

**OPW 766586**

**Comment by fmdl** [comment]
It is fix for the V11.

For V10, I made a PR to fix, but it is still in waiting : https://github.com/odoo/odoo/pull/17674

**Comment by lap-odoo** [comment]
@benwillig @fmdl As said, this has been fixed in version 11 but unfortunately this cannot be changed in the previous versions. 

This fix requires to move a field from a model to another and this cannot be done on stable versions. 

Thanks for reporting this.
