### ISSUE TITLE
"for...each" doesn't work in mail.template

### ISSUE THREAD

**Issue by blabllavita** [odoo/odoo#18903]
Impacted versions:
odoo 10 Enterprise

Steps to reproduce:
I'm customizing the existiing mail template "Sales Order - Send by Email". 

Current behavior:
I can use some variables e.g. ${object.amount_total} ${object.pricelist_id.currency_id.name} or ${object.amount_tax} ${object.pricelist_id.currency_id.name} . But there is no possibility to print the order lines in the mail template. The syntax "for each" is not possible. 

Expected behavior:
I wan't to display all order lines in the mail 

Video/Screenshot link (optional):

**Comment by a741424975game** [comment]
Same problem

**Comment by dreispt** [comment]
AFAIK Python does not have the "for each" specific syntax. if the template engine is QWwb, shouldn't it be "for X in ITERABLE"?

**Comment by pedrobaeza** [comment]
This uses Mako syntax, so you should learn how to make the loop with that syntax: http://www.makotemplates.org/.

Closing as no real issue.
