### ISSUE TITLE
Eliminate upgrade migration pain by using facade pattern microservices API

### ISSUE THREAD

**Issue by chris001** [odoo/odoo#18905]
Impacted versions:
All 10.0 and lower.

Steps to reproduce:
Upgrade migration is painful because just running new module code breaks on old version database.

Current behavior:
Semi automatic scripted migration upgrade, plus manual coding upgrade.

Expected behavior:
Use microservices for python and/or "facade pattern" (API) for all modules.  No direct calling of implementation functions.  Module developer should support current version and previous versions.  This way, upgrade to new version of odoo will be simply accomplished by git clone from github.  The new interface can detect old database schema and automatically migrate it.  Old 3rd party modules will call the old interface for the module they are trying to use, and the old interface will continue to work on the new schema, because the interface is made in such a way that it doesn't break it dynamically adapts at runtime.

Examples of python microservices to draw upon or use:
https://github.com/mfornos/awesome-microservices#python

**Comment by dreispt** [comment]
@chris001 The problem  with migrations is not with the programming API - it is mostly about changes in the business login and underlying data models.
I'm afraid the facade pattern wouldn't be of much help.
You might want to have a look at [OpenUpgrade](https://github.com/OCA/OpenUpgrade).

**Comment by chris001** [comment]
@dreispt 
* When I say API what I mean is the internal API.  There should be no direct access to data or database.  Data access should all be done via an abstracted data model microservices API which cannot break because it adapts dynamically at runtime to the version of the db schema which currently exists in the database. 
* Same with business logic.  Business logic should be written in such a way that it cannot break no matter which version of the data model microservices API is running.  
* Both of these should be able to quickly detect, even during normal runtime, the outdated database schema (with respect to the code version running) and invoke an asynchronous request to the core that the core update to the new db schema as soon as it completes all running transactions.

We do this and upgrading from one major version to the next becomes seamless, as it should be, in 2017 with the software technology we have available.

**Comment by dreispt** [comment]
While it is possible, I believe that it would be far from practical in an ERP-like system.
In practice that would require to never remove code from previous versions - similar to the Git version history. The code base would just grow. You would have to keep support for old ORM APIs, deprecated methods, tables , fields, etc.

Regarding teh core, I personally see more harm than good in this.
Now, regarding the 3rd party/community developed apps, there is a end user issue in that you are supposed to get the correct version of the app/module that is compatible with the Odoo version you are running.

It could be nice to have a "module package" containing the latest version of the that module targeting. The correct version would be installed depending on the version of the target Odoo server.

**Comment by chris001** [comment]
* Only current code is running and installed, old code lives in github.
* The core code must be aware of only the old-stable schema and the current schema, and auto detect which schema is currently installed in the database.  When core detects old-stable schema installed, because the code was upgraded offline or live, it waits until transactions complete, and installs upgrade to current schema.
* About apps yes they should detect schema version and when it's the wrong version, they should upgrade themselves dynamically to the app version matching the schema.

**Comment by jholze** [comment]
Hi chris, can I have your twitter account or email ? I would like open this discussion again.

**Comment by chris001** [comment]
@jholze 
Email sent!

**Comment by jholze** [comment]
Hey @chris001, ^^ I have to remember myself :) after almost two years. I think this was in a time when we migrated a huge odoo project. I liked your ideas. Did you create a prototype or something like that? 

Regards,

Jens
