### ISSUE TITLE
[18.0] hr_expense:  Incorrect model used for accessing property_account_expense_categ_id field

### ISSUE THREAD

**Issue by hassanyahya101** [odoo/odoo#189252]
### Odoo Version

- [ ] 16.0
- [ ] 17.0
- [X] 18.0
- [ ] Other (specify)

### Steps to Reproduce

There is an issue with the code where the wrong model is being used to access the property_account_expense_categ_id field. The original code uses the property.category model, but it should be using the product.category model.

**Current Code:**
      field = self.env['property.category']._fields['property_account_expense_categ_id']
      account = field.get_company_dependent_fallback(self.env['property.category'])

**Corrected Code:**
      field = self.env['product.category']._fields['property_account_expense_categ_id']
      account = field.get_company_dependent_fallback(self.env['product.category'])
      

1.   Navigate to the code section that references property_account_expense_categ_id inside function _get_base_account in "hr.expense" model.
2.  Check the model being used (it currently uses property.category).
3. The model should be product.category, as it correctly links to the property_account_expense_categ_id field.

**Expected Behavior:**
    The model used should be product.category instead of property.category to correctly retrieve the 
      property_account_expense_categ_id field.
      
      
![Screenshot from 2024-12-01 14-44-13](https://github.com/user-attachments/assets/ccbe5181-221b-485d-8598-ff4e72243847)

**Comment by vava-odoo** [comment]
Hi @hassanyahya101 
This was solved by https://github.com/odoo/odoo/commit/2d9cdf9963c2321ebbdd7f97da75380d061146d2
Cheers
