### ISSUE TITLE
Entry of Deposit incorrectly allowed for Quotation

### ISSUE THREAD

**Issue by ThijsvOers** [odoo/odoo#18929]
Impacted versions: 10.0

Steps to reproduce: 
Generate a new quotation (state of the quotation is 'not confirmed').

Current behavior:
- I can make a deposit on a quotation. This is not desirable, normally you will only make a deposit if the quotation is a sales order.

Expected behavior:
Do not allow a deposit to be made for a quotation. Deposits are only allowed for sales orders with status confirmed (or on invoices)

**Comment by bistaray** [comment]
"Normally" for you and others isn't the same.

Not every company requires an order confirmation before they will take a deposit.

Some companies require a deposit BEFORE they will confirm an order.

I have several Customers who would be upset if they could not ask for payment before they confirmed an order which kicked off associated purchase orders and manufacturing orders (things they don't want to do until they have some money from their Customer).

**Comment by ThijsvOers** [comment]
Thank you for replying. I understand that there are situations where a payment is required before creating a purchase order. The way I look at it , the quotation in Odoo is a non-confirmed sales order. 

My point is that there could be multiple quotations before the customer decides. There will also be quotations that will not go through or where the client has not decided yet. These quotations are 'mixed' with the non-confirmed orders.

The solution in Odoo might be that you work with certain labels so that you can split the quotations and the non-confirmed sales orders.

**Comment by bistaray** [comment]
I understand - for most of my Customers a Quotation and Un-confirmed Sales Order are the same - but I can see why you would want to think of them differently.  Perhaps just add a boolean flag to separate them from each other.

**Comment by ThijsvOers** [comment]
Yes. I have already tried your 'boolean' solution. I think it will work as long as I can group or report on this boolean.


There is one another thing that I will have to check: is it possible to recalculate price and/or delivery lead times at the moment the quotation is 'upgraded' to  salesorder?


Met vriendelijke groet / Kind regards,



Thijs van Oers

Open Source ERP Consultant



Onestein B.V.  /  Reduitlaan 45 - 4814 DC - Breda / Kantoor Het Pakhuis

M:  +31 6 2412 8996

T:  +31 88 627 0400

E:  t.vanoers@onestein.nl

W: www.onestein.nl

Twitter: onestein_erp<https://twitter.com/onestein_erp>

LinkedIn: onestein<https://www.linkedin.com/company/onestein>


[1494341476569_image003.png]<http://www.onestein.eu/>


Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Als dit bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden. Onestein B.V. staat door de elektronische verzending van dit bericht niet in voor de juiste en volledige overbrenging van de inhoud, noch voor tijdige ontvangst daarvan. Voor informatie over Onestein B.V. raadpleegt u http://onestein.nl.



This e-mail is intended for the addressee’s eyes only. If you are not the intended recipient, you are hereby kindly requested to inform the sender of this. In view of the electronic nature of this communication, Onestein B.V. is neither liable for the proper and complete transmission of the information contained therein nor for any delay in its receipt. For information about Onestein B.V., direct your browser to http://onestein.nl.






________________________________
Van: Ray Carnes <notifications@github.com>
Verzonden: maandag 21 augustus 2017 23:45
Aan: odoo/odoo
CC: Thijs van Oers; Author
Onderwerp: Re: [odoo/odoo] Entry of Deposit incorrectly allowed for Quotation (#18929)


I understand - for most of my Customers a Quotation and Un-confirmed Sales Order are the same - but I can see why you would want to think of them differently. Perhaps just add a boolean flag to separate them from each other.

**Comment by bistaray** [comment]
We wrote a refresh button for this.

**Comment by pedrobaeza** [comment]
Closing following the debate, but without an specific conclusion, as the use case can be valid depending on the business.
