### ISSUE TITLE
Fiscal position not considerd on onchange partner in invoice

### ISSUE THREAD

**Issue by CybroOdoo** [odoo/odoo#18926]
Impacted versions:10.0

Steps to reproduce: 
1-Setup a fiscal position with tax mapping
2- Specify this fiscal position for a customer/vendor
3-Create a draft invoice for any customer except the one who has fiscal position specified
4-Add some Invoice lines 
5-Change the customer to the one we specified the fiscal position

Current behavior:
You can see the taxes remains same.
in step 3, if you select the customer with fiscal position, tax selection while adding invoice lines is correct. But after that, if I change to another customer without having a fiscal position, there are no updations on tax
This is working fine on SO

Expected behavior:
Taxe should be updated according to the fiscal position

Video/Screenshot link (optional):

**Comment by fmdl** [comment]
Dear there are an module on the OCA to do that : https://github.com/OCA/account-invoicing/tree/10.0/account_invoice_fiscal_position_update

**Comment by pedrobaeza** [comment]
Yes, this is a feature that is not present currently in Odoo, so it's not an issue, but missing feature. It has been already included in sales and purchase orders, but not on invoices, so closing this.

@qdp-odoo is there any plan to also include automatic tax computation on the onchange of the fiscal position?
