### ISSUE TITLE
Deposit is not removed when deleting the coupled sales order

### ISSUE THREAD

**Issue by ThijsvOers** [odoo/odoo#18930]
Impacted versions: 10

Steps to reproduce:
create a sales order, make a deposit on the sales order and then remove the sales order.

Current behavior:
- I can remove the sales order if a deposit has been made. The order is removed, but the deposit remains. The source document mentioned on the deposit does not exist anymore. If I remove an order with an unpaid deposit, the deposit should also be removed. If the deposit has been paid (partly), it can not be removed, but it should also mean that i cannot delete the sales order).
- I can make a deposit on a blocked sales order. I think that this should not be allowed

Expected behavior:
- delete the deposit when  deleting the SO
- do not allow the SO to be deleted when the deposit (partially)  has been paid.

**Comment by bistaray** [comment]
It is best practice to cancel and/or archive documents once entered.  

If you delete things that the Customer has a copy of, you lose the record of the actual conversation and/or agreement that happened in the real world.  Months later when there is a dispute, you won't have all the documents to re-create what actually happened.  Even documents created as the result of user error should be kept. 

I view this report as requirements that are custom for you, but that may cause problems for the customers who send a payment for the deposit invoice (accounting might not talk to the same people who cancelled the order in time to stop payment); for those users wishing to apply the deposit to another sale; and those users who are not allowed to modify (and in no way can they delete) an accounting document once issued (in many countries this is illegal or at least a red flag for auditors)***.  

Odoo, as a generic system, cannot know how to handle what happens next once the Sales Order is no longer valid (cancelled, deleted, blocked).  Should the deposit request be cancelled completely? Cancelled and Reissued for a new order? Kept open so the Customer payment (which may be on the way) can be accepted and applied to another order? Not every company so tightly links Sales Orders and Deposits.

Document permissions in Odoo are easy to modify - remove delete permission for sales orders except for those in an Administrative group

*** I always tell people to assume that as soon as an Accounting document leaves your company, it has been entered into another Accounting system and validated, and cannot be modified.  Whatever you send, you are stuck with.  A deposit Invoice may be considered a liability when entered into your Customer's system - one they can't delete but can only cancel (if needed).
