### ISSUE TITLE
Stock Landed Cost  validation Issue

### ISSUE THREAD

**Issue by sanaldavis-12** [odoo/odoo#18947]
Impacted versions: Could not complete the landed cost  validation button functionality 

Steps to reproduce: Create a landed cost with Valuation Adjustments lines more than 500. Apply validate button. Could not complete the function. scrolling screen appears,  after that nothing happened. 

Current behavior: Scrolling window appears

Expected behavior: Journal Entry created and Current landed cost, record state changed to POSTED

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look?

**Comment by rgeromegnace** [comment]
I have the same problem with valuation adjustments lines more than 500.

Did Odoo fixed this issue?

Regards,

**Comment by jco-odoo** [comment]
I think @kebeclibre got a look at that.  Anyways, there is no way you can split in two landed costs?  500 lines is quite a lot.

**Comment by rgeromegnace** [comment]
Hello @jco-odoo 500 lines in a purchase order is the everyday of our customers...I think odoo have to find a solution.

**Comment by pedrobaeza** [comment]
This is not an Odoo problem, but a misconfiguration. "The nothing happened" thing is because the timeout or memory limit in your instance is risen, so what you have to do is to adjust the configuration for bypassing that limits.

Closing by the reasons above.

**Comment by sanaldavis-12** [comment]
Hi All,

Seems like this was a legitimate issue and has been fixed in this:
https://gitlab.openminds.be/mirror/odoo/commit/77bf2c96af30ae17ff43e8a08d2ae81b3960b3fa
@Yenthe666 

Please don't misjudge real issues like this as configuration issues. @pedrobaeza

**Comment by jco-odoo** [comment]
It seems to be like this in v12 as there, you also have the create in batch
