### ISSUE TITLE
[PosBOX]Image failed on python babel since stretch is the latest raspbian

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#18942]
Hi,

I've tested to create an brand new image and it failed on the package list installation saying that python-babel has no candidate.
I observed that the latest raspbian image return strecth version since a few days .
maybe could be usefull to precise/force jessie intergration instead?

regards

**Comment by Yenthe666** [comment]
@jorenvo this is for you I assume.

**Comment by MaitreDede** [comment]
Hi,
As a simple quick fix that @flotho suggested, my updated `posbox_download_images.sh` :

```
#!/bin/sh

#latest jessie
IMAGEURL=https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/2017-07-05-raspbian-jessie-lite.zip
#stretch
#IMAGEURL=https://downloads.raspberrypi.org/raspbian_lite_latest

wget "${IMAGEURL}" -O raspbian.img.zip
unzip raspbian.img.zip
wget 'https://github.com/dhruvvyas90/qemu-rpi-kernel/raw/master/kernel-qemu-4.4.13-jessie' -O kernel-qemu
```

**Comment by pedrobaeza** [comment]
Is this still happening with latest image?

**Comment by qle-odoo** [comment]
for v17 and v18.10 image on : https://nightly.odoo.com/trunk/posbox/ it's work
