### ISSUE TITLE
[10.0] when running on Windows on Cygwin ImportError is raised 

### ISSUE THREAD

**Issue by alpham** [odoo/odoo#18944]
Impacted versions:
10.0
Steps to reproduce:
Run `odoo-bin` on Cygwin on Windows 7
Current behavior:
Raises ImportError from block at line 23 file: odoo/service/server.py
Expected behavior:
on errors

**Comment by Yenthe666** [comment]
@d-fence could you perhaps double check if this is already fixed and checkout the PR?

**Comment by Yenthe666** [comment]
@d-fence can you give an update?

**Comment by pedrobaeza** [comment]
You shouldn't run Odoo with Cygwin, but use the specific Windows build if you prefer that platform (which is not very recommended), but there's no issue at all, as Odoo is not developed to be Cygwin compatible, but cross-platform compatible through Python interpreter.

Closing as no real issue.

**Comment by alpham** [comment]
@pedrobaeza I agree that windows platform is not recommended for odoo and python development in general. 
But I Use Cygwin to build custom Odoo installer, so the build process as I understood from the documentation should be done in Cygwin.

**Comment by pedrobaeza** [comment]
You are not building an Odoo installer, but trying to run Odoo. If not, please point to that documentation.

**Comment by alpham** [comment]
Sorry the title is not specific.
And sorry again this is not mentioned in a documentation but in an answer on `Odoo Forums`:
[Link to the answer](https://www.odoo.com/forum/help-1/question/how-to-build-odoo-10-for-windows-as-an-executable-software-117670#answer_117671)

I did wrote a fix to this and created a [pull request](https://github.com/odoo/odoo/pull/18945) #18945

**Comment by pedrobaeza** [comment]
OK, now it's clearer. I still see that doing this on Windows is a waste of time, but let's fix it as it's very clear.
