### ISSUE TITLE
[10.0] can't checkout on mobile browser, CSS problem in checkout wizard

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#18948]
Impacted versions: 
10.0 CE  
Saas version is not impacted.
Tested on Firefox, Chromium, webkit, and 2 mobile Android browsers.

Steps to reproduce: 
install ecommerce demo, use a mobile phone or resize your browser window, add something in cart, try to checkout.

Current behavior:
Can't click on Checkout button unless cursor (or finger) is on top of the button ; same behaviour for every right button in the wizard checkout.  Because the right column div transparently cover half of the button (see 4th screenshot). Increasing z-index of "oe_cart" fix the problem.

Other forms tested on website not impacted.

First screenshot shows no problem on the left button (cursor at the middle)
Second screenshot shows right button not activated (cursor at the middle)
Third screenshot shows right button activated (cursor at the top)
Fourth screenshot shows problem with the right column transparently covering half of the button.

Video/Screenshot link (optional):
![odoo 10 button bug on mobile 01](https://user-images.githubusercontent.com/24126/29498492-0094cf6a-85fe-11e7-9909-0564375520a0.jpg)
![odoo 10 button bug on mobile 02](https://user-images.githubusercontent.com/24126/29498493-023524e6-85fe-11e7-8cbe-3273f61cba9b.jpg)
![odoo 10 button bug on mobile 03](https://user-images.githubusercontent.com/24126/29498494-03a61042-85fe-11e7-9794-abcbdc12ec74.jpg)
![odoo 10 button bug on mobile 04](https://user-images.githubusercontent.com/24126/29498496-05627ad8-85fe-11e7-9efb-cb7a0b9f9fe0.jpg)

**Comment by zeroheure** [comment]
Same behaviour as previously fixed #15551 and #13805

**Comment by JKE-be** [comment]
@Cocographique can you check it plz

Wraps both button into a row should fix the problem

**Comment by qsm-odoo** [comment]
Hello, sorry for the delay, the issue has just been solved in 10.0 with https://github.com/odoo/odoo/commit/bc623461b3783da4767035f28e0f0ba59db82839

**Comment by zeroheure** [comment]
Please re-open, https://github.com/odoo/odoo/commit/bc623461b3783da4767035f28e0f0ba59db82839 doesn't solve the problem at all (tested on Samsung Galaxy S5 and S7). It work even badly, as it breaks the z-index workaround.

**Comment by qsm-odoo** [comment]
Hello,
I tested on Samsung Galaxy S5 and it seems to be working there as well. Have you tried with the latest version? Please send a screenshot if this is still not working on your side.
Thanks.

**Comment by zeroheure** [comment]
Hi
Thanks for your quick answer.
Below is a screenshot. You can try on https://wwwchez-les-enfants.fr
![Chez les enfants, ecommerce payment on mobile](https://user-images.githubusercontent.com/24126/32690020-78ef52fa-c6ef-11e7-9e72-24093ed170bb.png)

**Comment by zeroheure** [comment]
Problem solved. Your fix was correct. It was not working because css and less files were not updated even so I've requested the module to be updated.
Might be a problem with the website_style_manager module from SythilTech.
