### ISSUE TITLE
KeyError: 0 while call method name_search

### ISSUE THREAD

**Issue by fananimi** [odoo/odoo#18954]
Impacted versions:
Odoo version 10.0

Steps to reproduce:
Call method [name_search](https://github.com/odoo/odoo/blob/8cb991c7725e25654db47a8d656bc462309ff889/addons/product/models/product_template.py#L313 ) with the following parameters:

```
--- BEGIN Parameter ----
name     : apple macbook pro
args     : [{u'values': [u'name', u'ilike', u'apple macbook pro']}, {u'values': [u'id', u'not in', {u'values': [10, 34, 32, 28, 7, 8, 4, 5, 33, 31, 23, 30, 2, 3, 1, 9, 29, 6, 27, 26, 25, 24, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11]}]}]
operator : ilike
limit    : 10
---- END  Parameter -----

```

Current behavior:
Returning an error
```
File "~/odoo/addons/product/models/product_template.py", line 322, in <genexpr>
    if not name or any(term[0] == 'id' for term in (args or [])):
KeyError: 0
```

Expected behavior:
Return product list.

**Comment by Yenthe666** [comment]
Hi @fananimi,

Thank you for your report.
Could you add your whole code too please?

Regards,
Yenthe

**Comment by fananimi** [comment]
Hi @Yenthe666 ,

Here's my code,

```
ServerDataHelper helper = mProductModel.getServerDataHelper();
ODomain domain = new ODomain();
domain.add(mProductModel.getDefaultNameColumn(), "ilike", params[0]);
domain.add("id", "not in", mProductModel.getServerIds());
if (mCol != null) {
    for (String key : mCol.getDomains().keySet()) {
         domain.add("sale_ok", "=", true);
    }
}
return helper.nameSearch(params[0], domain, 10);
```
It's actually my custom code  from [Odoo Mobile Framework](https://github.com/Odoo-mobile/framework).

**Comment by pedrobaeza** [comment]
The code you mentioned is not present anymore, so I assume that the problem has gone. Curious way to get to the error...

Any way, if you still experiment any problem, please feel free to open a new issue.
