### ISSUE TITLE
[BUG] Issue on button Save timesheet when filtering mandatory fields

### ISSUE THREAD

**Issue by elsafdama** [odoo/odoo#18959]
Impacted versions:
10 CE

Steps to reproduce:
if i add new line on timesheet and there are some mandatory fields (analytic account, description and project)
if I fill on analytic account and project and then I click button save (warning to fill mandatory can display)
but if i click edit on the same line and then  i click save again, no warning returned and the record suddenly disappeared

Current behavior:
When saving a timesheet line, if any mandatory field wasn't filled, no warning returned and the record suddenly disappeared 

Expected behavior:
return warning display when click save and click outside line if any mandatory fields not filled 
Video/Screenshot link (optional):
![screenshot from 2017-08-14 08 56 07](https://user-images.githubusercontent.com/16060115/29514115-903e155c-8691-11e7-9583-3da5b9839b31.jpeg)

**Comment by Yenthe666** [comment]
Hi @elsafdama,

Thank you for your report.
I was no longer able to reproduce this. Could you please try this again on an official Odoo test instance at runbot.odoo.com?
Have you tried updating your Odoo codebase to the latest version?

Regards,
Yenthe
