### ISSUE TITLE
[10.0] point_of_sale: Cashier is changed if browser is refreshed

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#18968]
Impacted versions:
10.0, maybe olders too.

Steps to reproduce:
- Log in to Odoo with Cashier A
- Open a new POS Session
- Cashier A goes to eat and Cashier B replaces it.
- Cashier B inputs its PIN and takes the session

Current behavior:
- If Cashier B refreshes the Browser, it will be able to make transactions with Cashier A
- After ending doing illegal transactions on Cashier A's behalf, it goes back to using his user, inputting it's known PIN.

Expected behavior:
- No way to change to go back to Cashier A if it's not inputting his/her PIN.

**Tested on runbot**
cc: @jorenvo

**Comment by gustavovalverde** [comment]
Closed by: https://github.com/odoo/odoo/commit/e14ab697727d87773dbefba11453b9edca79fc68 

cc: @kebeclibre

**Comment by Yenthe666** [comment]
@gustavovalverde what about this part:

> This crashed 6 point of sales I have, they won't load the products and the payment widget won't show. I'll try to pinpoint the root cause (maybe this is colliding with a third party module). But just an FYI that this might happen to others.

Did you find out what caused it and if it is from custom code or not?

**Comment by gustavovalverde** [comment]
Yes I could pinpoint the root cause, it's from one of Yelizariev's modules, something from this file seems to be colliding as the Payment button and products won't load:
https://github.com/it-projects-llc/pos-addons/blob/10.0/pos_disable_payment/static/src/js/pos_disable_payment.js#L24

**Comment by gustavovalverde** [comment]
Reopening this issue as it's happening again. 

cc: @Yenthe666 @kebeclibre

**Comment by gustavovalverde** [comment]
Oh, sorry @Yenthe666, this is also happening on 11.0

**Comment by gustavovalverde** [comment]
OPW 1844006

**Comment by Yenthe666** [comment]
Relabeled 😉

**Comment by pedrobaeza** [comment]
This has been solved again, so I'm closing. Correct me if I'm wrong.

**Comment by gustavovalverde** [comment]
That's correct, thanks Pedro.
