### ISSUE TITLE
[v8] Enhancement Request - Reconcile Bank Statements.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#1896]
On the new bank statement reconcile front end, 2 enhancement requests.
1. When typing in to the transaction filter, could the filter look at amounts too.  (i.e. keying in 137 shows transactions that are $137.00, as well as filtering on the transaction description).
2. After selecting a partner for a given line, it is not possible to entirely unselect a partner.  You can select a different partner, but you can't change it back to blank.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
