### ISSUE TITLE
More than one ir.logging record when a ir.ui.view is updated

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#18971]
**Impacted versions:**

10.0

**Steps to reproduce:**

1. Create an automated action that will be trigger every time a ir.ui.view record is updated. The server action related will write at ir.logging model which view and how edit it  
   ```python
   log('edited view %s' % (record.id))
   ```

   ![image](https://user-images.githubusercontent.com/7593953/29481164-36d95540-844c-11e7-9265-ddd6db841c3d.png) | ![image](https://user-images.githubusercontent.com/7593953/29481170-44f720da-844c-11e7-8a7a-e043acd5fc55.png)
   --- | ---
 
2. Update any view
3. Go and review the ir.logging to Logging Menu

   ![image](https://user-images.githubusercontent.com/7593953/29481201-6dbd39fa-844c-11e7-9dc3-f41202d2d765.png)

**Current behavior:**

We have 6 records that belongs to the same view that was modified, this 6 logging records that belongs to the same view when this one is updated.

**Expected behavior:**

After modify the view record, the result should be only one logging record generated.

**Comment by zaoral** [comment]
OPW 767070

cc @rdmachadog @nhomar

**Comment by rim-odoo** [comment]
Looks highly specific to `ir.ui.view`... probably some `write()` are triggered 

Does this _really_ prevent you from working?

**Comment by rim-odoo** [comment]
Do you have website_version installed, as this method could be the cause of the trouble? https://github.com/odoo/enterprise/blob/10.0/website_version/models/ir_ui_view.py#L36-L62

**Comment by zaoral** [comment]
Hi @rim-odoo 
Sorry for the late answer

> Does this really prevent you from working?

It really does no prevent me to work. But complicate the way a work. The idea we are trying to apply is to  log when I view is modified, to control this changes that have been made in production in order to determine what happen if an error appears. 

If I have 6 records for each modification not only I am using extra space in my database that is really not necessary, i think is adding garbage information that I really don't want to have because is not a clean log, it is also make it really tedious and hard when I try to review the log list to review each log and see what is the one that matters to me: if I just have one log, the one expected will be clear and will be easy to control the views changes.

> Do you have website_version installed, as this method could be the cause of the trouble? https://github.com/odoo/enterprise/blob/10.0/website_version/models/ir_ui_view.py#L36-L62

First, I don't have access to the path you add in your last comment, So I am not sure about what are you trying to show me. 

Nevertheless, the answer is no. I don't have website_version module installed in my instance. In fact, as you can see in the main message of the issue I made a simple test in a clean runbot odoo instance (that do not have website_version module either) and the result was the same.

**Comment by zaoral** [comment]
**NOTE:** we are not only logging the information about who and when a view has been modified, also we are managing a diff of the previous and new view arch. 

For that reason we need the automated action, not only the last modified data/user information that we can check it from the record meta data.

For this instance in particularly is updated via web for our clients, and changes to some views are not applied explicitly in code: that is the reason that of the diff in order to control and review the changes.

**Comment by zaoral** [comment]
any updates about this issue?

**Comment by rco-odoo** [comment]
@zaoral this is not a bug. A log entry appears every time the record is modified, which includes the user modification, **and** all subsequent modifications made by the ORM, like computed fields and such things.

You can actually track changes to a specific field. In the server action that is triggered by an update, the context contains a key `old_values` with the old values of the modified fields of the records. It looks like:
```python
old_value = env.context['old_values'][record.id][field_name]
```
You can thus adapt your server action as
```python
if 'arch_db' in env.context['old_values'][record.id]:
    log('edited view %s' % (record.id))
```
This server action logs **one** entry per view update.
Using the `old_values` dict, you can even log the values before/after modification...

**Comment by nhomar** [comment]
lovely @rco-odoo this helps A LOT!

**Comment by zaoral** [comment]
Thanks @rco-odoo for the solution.  
This is really helpful, and it was exactly what we were looking for.

Best Regards
