### ISSUE TITLE
[v8] Various date defaults are not using the context timezone

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#1897]
Default dates in many places are not using the context timezone.

Code such as:
        'date': lambda *a: time.strftime('%Y-%m-%d'),

is not adequate for non-UTC locations.

Examples are in account_voucher, account_payment, mrp, and more.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
