### ISSUE TITLE
TypeError in image_resize_image

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#18985]
[Reported by @dhannyz](https://github.com/odoo/odoo/commit/3824b5dcc13678d3985ad45ac21dcf9ac9202c20##commitcomment-23787602):

> This line is causing issues for me on python3.5+ (`TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)`)

> This occurs for me during setting a logo image on the company form view.

**Comment by dhannyz** [comment]
@xmo-odoo Any progress on this?
Also, regarding other python3 based issues, what would be the best way to alert you or your team?
Just create an issue as normal?

**Comment by Yenthe666** [comment]
@dhannyz you're always free to create new bug reports. If you have an enterprise license you can always report them through https://www.odoo.com/nl_NL/help

**Comment by xmo-odoo** [comment]
> @xmo-odoo Any progress on this?

I just came back from holidays, so no.

> Also, regarding other python3 based issues, what would be the best way to alert you or your team? Just create an issue as normal?

Yeah, you can optionally tag me and/or @odony

**Comment by xmo-odoo** [comment]
Should be fixed in 6bb6944e6b8bce7c50ee46c1350f3c70012cd476
