### ISSUE TITLE
[v8] DataError in search

### ISSUE THREAD

**Issue by daivaras** [odoo/odoo#1898]
Steps to reproduce:
-Open runbot v8
-Open sale orders
-Write in the filter some text, e.g. "agro" and press on customer without expanding the search field
-Press create new order
-Get traceback:
File "/home/bak/runbot/extra/runbot/static/build/11490-8-0-0829af/openerp/sql_db.py", line 230, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "agro"
LINE 2:                     WHERE res_partner.id IN ('agro') AND (TR...

**Comment by Yenthe666** [comment]
Hi @daivaras,

Thank you for your report!
This issues has been fixed in the meanwhile and does no longer happen.
P.S: Sorry for the late reply.

Regards,
Yenthe
