### ISSUE TITLE
moment._locale & moment._locale._week 

### ISSUE THREAD

**Issue by Nucleardragon88** [odoo/odoo#18994]
Hello, 
in my ODOO 10 when I try open calendar APP I am getting different errors in different web browsers:
Mozilla:
TypeError: moment._locale is undefined
Safari:
TypeError: undefined is not an object (evaluating 'moment._locale._week')
Chrome:
Uncaught TypeError: Cannot read property '_week' of undefined

but in odoo.log no any errors, what is happened?

**Comment by Yenthe666** [comment]
Hi @Nucleardragon88,

Have you installed all Odoo dependencies (https://github.com/odoo/odoo/blob/10.0/requirements.txt) and followed the official installation guidelines (https://www.odoo.com/documentation/10.0/setup/install.html) ?

Regards,
Yenthe

**Comment by bnjroos** [comment]
I had the same problem and found the solution: 

Go to your odoo installation folder
`cd /addons/web_calendar/static/src/js`
edit web_calendar.js line 57 by replacing moment._locale._week.dow by moment()._locale._week.dow

And this should fix your issue.

**Comment by Yenthe666** [comment]
Hmm, I've made a PR with what you suggested. This needs to be checked by somebody from Odoo. 😉
