### ISSUE TITLE
UI Master - Invoice numbers

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#18996]
Impacted versions: Only Master

Steps to reproduce:
Install Account or Invoicing - whatever you just need to be able to create an invoice.

Current behavior:
Notwithstanding the wisdom of being able to edit the number here, it should at least display correctly.  Currently it will display only 4 digits in edit mode.  A touch limiting for anyone with over 10,000 invoices in a period.

Expected behavior:
Display all digits in sequence.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/29592264-148fc18c-87f7-11e7-9671-fc769939b3b9.png)

**Comment by gdgellatly** [comment]
As an aside I notice this width is hard coded in the invoice view <field name="sequence_number_next" class="oe_inline" required="1" style="width: 80px !important;"/>  Seems a bit of a work around so it looks nice with the standard sequence which uses INV/2017/xxxx but very few companies would choose such a sequence unless it was legally required.  (Because it would allow competitors to estimate their business volume)

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look please?

**Comment by qdp-odoo** [comment]
fixed by https://github.com/odoo/odoo/commit/fff4d41da24c8fcd228477ead34794317e9db15a

thanks
