### ISSUE TITLE
[TERMINOLOGY] Authentification is not the usual English word

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#18995]
Impacted versions: Master - probably all

Steps to reproduce:
Go to Settings Screen

Current behavior:
You'll see Authentification written twice.  In English, and especially in English technology speak the usual word is Authentication.

The only real issue it causes is that when searching for docs, you would search for Authentication (e.g. "How do I setup Oauth Authentication with provider x?"

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/29589757-99092af0-87ea-11e7-8bbe-dd8593b54d42.png)

Seems it occurs 4 times in code, but didn't want to PR as I don't understand translations
![image](https://user-images.githubusercontent.com/5093264/29589851-1e30f71c-87eb-11e7-94a7-fdb16a9eeccf.png)

FIx if you want, close if you want, I won't be offended and can manage

**Comment by Yenthe666** [comment]
Hmm I agree Authentication is better then Authentification.
@mart-e do you agree? Can we change it in the master?

Regards,
Yenthe

**Comment by mart-e** [comment]
> Impacted versions: Master - probably all

Shouldn't be too much. I remember correcting all a few years ago but this kind of [Frenglish](https://en.wikipedia.org/wiki/Franglais) tends to come back from time to time.

@Yenthe666 sure, now is the perfect time to fix all of these before the release of v11 and freeze of terms

**Comment by Yenthe666** [comment]
@mart-e just double checking. Does this mean I also have to change the translations for every language it's `.po` file? not only `.pot`?

**Comment by Yenthe666** [comment]
@gdgellatly all fixed - thank you for reporting.

**Comment by vcloud9ray** [comment]
AUTHENTIFIED (another word that does not exist) is showing in the DOWNLOAD SECURITY dropdown when publishing website document (v9, v10 and v11).

https://github.com/odoo/odoo/blob/11.0/addons/website_slides/models/slides.py#L284

download_security = fields.Selection(
        [('none', 'No One'), ('user', '**Authentified** Users Only'), ('public', 'Everyone')],
        string='Download Security',
        required=True, default='user')

**Comment by mart-e** [comment]
Thanks, fixed at f8e38a6a0ca

cc @d-fence @tde-banana-odoo
