### ISSUE TITLE
[10.0] Automatic reconcile doesn't work

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#19008]
Impacted versions:

10.0

Steps to reproduce:

See https://youtu.be/f24uIcjf8B0

Current behavior:

There is no possiblity to do automatic reconciliation

Expected behavior:

Have the possibility to do automatic reconciliation like in version 8

![capture du 2017-08-23 09-58-09](https://user-images.githubusercontent.com/8035793/29604991-9fc5c368-87e9-11e7-83f5-d04312ccc1e9.png)

Video/Screenshot link (optional):

https://youtu.be/f24uIcjf8B0

**Comment by adrienpeiffer** [comment]
OPW 767309

**Comment by pedrobaeza** [comment]
The method for automatic reconciliation has changed since v9, and that button has no sense anymore (and it has been hidden already in latest builds), so I close this.
