### ISSUE TITLE
V10 - Sitemap generates hundreds of non existing URLS (jobs and products)

### ISSUE THREAD

**Issue by aduijs** [odoo/odoo#19019]
[sitemap.txt](https://github.com/odoo/odoo/files/1246503/sitemap.txt)
Impacted versions: V10

Steps to reproduce:
install recuitement module
install ecommerce module

Current behavior:
- 1) the sitemap generates a /jobs/country/<insert country>/department/somedepartment  for every single country in the world. while there is no job listed.. there is only wwwdomain/jobs

- 2) As well the sitemap generate a link for ALL the products, even when they are not published!
NOTE, even products that are to buy only!!!

Expected behavior:
1)either just put link in sitemap to wwwdaomin/jobs  (and perhaps a joblisting if it is published)
2) just a link in the sitemap for the published products
attached is full sitemap should contain about a max of 60 links (not 480+)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7501203/29630917-795381e2-8803-11e7-96f4-a9b7f2d77127.png)

below are links to unpublished products
![image](https://user-images.githubusercontent.com/7501203/29630982-aede62c8-8803-11e7-82b7-eb5cb59b0380.png)

**Comment by Yenthe666** [comment]
@JKE-be this looks like one for you. Was this done by purpose?

**Comment by JKE-be** [comment]
For recruitment, and route with controller of type ModelConverter that is not precise (eg. country):
the issue is known, here a begin of improvement https://github.com/odoo/odoo/pull/15317/files

For the product, it should never show unpublished product by default.
The sitemap is generated in Public user 
`locs = request.website.with_context(use_public_user=True).enumerate_pages()` 
which one don't have the access right
PS: be sure to have the last version or at least this commit #18822 

You can see it for max 12h after that you have unpublished your products because the sitemap is "cached" for 12h: `SITEMAP_CACHE_TIME = datetime.timedelta(hours=12)`

**Comment by JKE-be** [comment]
FYI, we have a task to allow to specify in the controller a function that generates itself the locs without using enumerates_page, we can hope to got it after the v11 :/

**Comment by aduijs** [comment]
double checked everything, we do have a build that includes that commit you mentioned

to show you an example the links below show up in the sitemap but none of these are published:
<url>
<loc>https://www.sapelli.pe/shop/product/pandora-2818</loc>
</url>
<url>
<loc>
https://www.sapelli.pe/shop/product/panel-metalico-4053
</loc>
</url>
<url>
<loc>https://www.sapelli.pe/shop/product/panel-pd-3899</loc>
</url>
<url>
<loc>
https://www.sapelli.pe/shop/product/pegaso-gerente-2783
</loc>
</url>
<url>
<loc>
https://www.sapelli.pe/shop/product/pegaso-interlocutor-2784
</loc>
</url>
<url>
<loc>
https://www.sapelli.pe/shop/product/percepcion-3442
</loc>
</url>
<url>

![image](https://user-images.githubusercontent.com/7501203/29694725-fce91066-8903-11e7-8e26-56bfffda44b2.png)

even worse.. this example product cant even be bought nor sold!
![image](https://user-images.githubusercontent.com/7501203/29694792-6b66c3bc-8904-11e7-96e0-468620a917cd.png)

**Comment by JKE-be** [comment]
It is possible that the filter on 'sold' is missing, but the product in the sitemap is only the list of product template that the user linked to the website is able to read.

Are you using multi-website? Do you have updated the ACL or record rules? Do you have custom modules ? 

I cannot reproduce your problem on runbot, and without more pieces of information, I cannot help you more...

Best regards

**Comment by JKE-be** [comment]
About the sale_ok, it is not missing, it is the desired behavior.

You can use e-commerce as catalog and don't want to sell it!

So the only criteria to be visible in the sitemap is the 'website_published' field.

**Comment by aduijs** [comment]
It seems a git pull solved the problem, the commit you mentioned earlier indeed wasnt applied. which is kind of strange because the last time i pulled git was in may.
anyway, that's solved.
As for the original question, the recruitment links. ill guess ill have to wait for the solution then.

**Comment by JKE-be** [comment]
Nice to hear it!

About the recruitment, the patch will probably don't come before the v11.

What you can already do to decrease it, is to remove unused country :/
For the department, there are not really hack except cherry pick my commit.
