### ISSUE TITLE
BOM Cost report not linking to BOM Cost View

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#19026]
Impacted versions:10, 9 both enterprise and community

Steps to reproduce:  Go to Technical - Reports - BOM Cost and click on "searach associated views" (QWeb views in 10)

Current behavior: Nothing 
Expected behavior:Link to BOM Cost view

The problem seems to be that the name in **mrp_report_views_main.xml** for the BOM Cost view doesn't match the name in **mrp_bom_cost_report_templates.xml** (BTW, these are the file names in v10)  

Changing the name in the **mrp_report_views_main.xml** and the model file **mrp_bom_cost_report.py** seems to fix this.  I don't know if there is a reason for this mismatch - or if it really matters.   I am trying to extend this report and my fix seems to help.

**Comment by Yenthe666** [comment]
@jco-odoo could you give feedback?

**Comment by sle-odoo** [comment]
Hi,
Sorry but it's not fixable in v9 and v10, and we should actually correctly fix the issue by having a view_id or view_ids on ir.actions.report.xml.

We noted the feedback.

Regards
