### ISSUE TITLE
[10.0] "undefined" stage cannot be deleted or renamed

### ISSUE THREAD

**Issue by WeeDom** [odoo/odoo#19039]
Impacted versions: 10.0

Steps to reproduce: create project from Sales Order, with a product where the unit of measure is hours, and invoicing has "Ordered quantities" as the Invoicing Policy, Track Service is"Create a task and track hours", and Project is blank.

Current behavior: create Sales Order from Quotation. Project is created, with a single task in the column "Undefined". This "Stage" cannot be renamed or deleted.
![cannot-delete-undefined-task](https://user-images.githubusercontent.com/1910021/29668282-8533f738-88d7-11e7-9caf-17b95e29909f.png)

Expected behavior: The column should be editable and/or delete-able.

Video/Screenshot link (optional):

**Comment by WeeDom** [comment]
ah - so the "workaround" is to create a new column/stage, move the task into that, and either refresh the page or leave/re-open the project. The "undefined" column then disappears

**Comment by JKE-be** [comment]
Yes, it is a solution.

Undefined is not a stage, so it cannot be updated, on each model you will have it when you group by a field that is undefined on some record.

**Comment by Yenthe666** [comment]
To be extra clear: this is desired and wanted behaviour. :)

**Comment by WeeDom** [comment]
I can *kinda* see the point, and I do understand about not being able to group by something that doesn’t yet exist, but it's very clunky and a horrible ux. It’s something that I’ll need to clearly highlight to my client, and all their staff who might come into contact with this area, to avoid multiple bug reports to me.

**Comment by Xurg** [comment]
I've been setting up an Odoo 11 Community edition on Ubuntu and this "Undefined" column in Tasks does seem weird and should probably be rethought a little to make it more intuitive. But I think I understand why it's like that, as a place to put unsorted tasks until they can be moved to a more specific column. Or for tasks that don't fit the typical mold of a workflow and will never be assigned to another column before being completed. Or leave it there while the idea is being developed. Right yall??

**Comment by Yenthe666** [comment]
Yep, indeed @Xurg 😉
