### ISSUE TITLE
[10.0] It's possible to delete a paid expense report ...

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#19044]
Impacted versions:

10.0

Steps to reproduce:

See https://youtu.be/HvD6gblBKxA

Current behavior:

It's possible for a simple employee to remove a paid expense report. After that, the related expenses return in "To submit" status.

Expected behavior:

It shouldn't be possible the remove expense report in this state (and other !)

Video/Screenshot link (optional):

See https://youtu.be/HvD6gblBKxA

**Comment by adrienpeiffer** [comment]
OPW 767549

**Comment by adrienpeiffer** [comment]
Hi @nim-odoo 

Thanks for the fix but I don't really agree with this. For me, an expense or report validated or posted or paid shouldn't be delete, even by an expense officer.

This causes a total inconsistency of the data present in the ERP. If it is possible to delete approved, posted or paid expenses, the payments and entries in the accounting no longer coalesce, there is no trace of validations, no history, ...

**Comment by nim-odoo** [comment]
I introduced the bare minimum for security, to avoid a change in behavior in stable. I agree, this is most probably not enough, but you always have the possibility to change the rule on your side.
