### ISSUE TITLE
Master - create="0", create="false" does not work

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19053]
First @odony do we want issues reported on master?  Is hard when it is WIP, but close to release to know and its not like it is a short list of open issues to look for PR's or duplicates.

Steps to reproduce. (Sorry this was easiest way to explain, as stock.picking validation is broken on master atm)

1. On runbot create a draft invoice and add a product line.
2. Save it and in debug mode edit the formview to add create="0" on the tree tag for invoice_line_ids.
3. Save and refresh view.  If successful you will see Add an Item no longer exists.
4. Click Edit.
5. Click on the line you created.
6. Tab through it until the end, eventually you will see a new line to create/enter.

NOTE: When done reproducing, change the view back or else you will get new issue reports :)

Obviously the expected behaviour is no new line. 

EDIT: OK I tested on SaaS-17 as well in both community and enterprise - same result, new line gets added.

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thank you for your report.
I've just tested this on the master version and this indeed works:
![image](https://user-images.githubusercontent.com/6352350/29705006-7608e7d2-897c-11e7-907f-86b824b79271.png)

@ged-odoo if I'm not mistaking you're the right person to ping for this?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
looks like a bug with the new views. I added this issue in our team's internal todo list

**Comment by ged-odoo** [comment]
@Yenthe666 yep, most likely a bug coming from the new views...  I added this issue in our team's internal todo list

**Comment by aab-odoo** [comment]
Commit 551dc26940f2f33af7fa71c7d1256fe4f2f2fd8f fixes the issue.
