### ISSUE TITLE
7.0: update quantity on hand of CARD 

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#1905]
On a fresh database, install only the `stock` module.
- take the product CARD. Quantity from demo data is 16.
- click "update". enter 5.
- quantity is now 21, I expected 5
- click "update" again, enter 7
- quantity is now 23, I expected 7.

This is due to the fact that with default settings, I do not see stock locations, and demo data puts 16 units of this product in Shelf 1. While I understand the technical reason, it is very confusing to have an "update" button  next to a field that does not actually update the field it is next to.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
