### ISSUE TITLE
[10.0] breadcrumbs in Project module go mental

### ISSUE THREAD

**Issue by WeeDom** [odoo/odoo#19068]
Impacted versions: 10.0

Steps to reproduce: 
1. create project with a task
2. click task title
3. click project title in task-view
4. click "1\nTasks" icon (takes you back to kanban tasks-view)
5. click task title 
6. click Project title in task-view
7. click "1\nTasks" icon
 repeat ad infinitum

Current behavior: breadcrumbs are incorrect, as per attached image

Expected behavior: breadcrumbs should be reset to just show where you actually are

Video/Screenshot link (optional):
![broken-breadcrumbs](https://user-images.githubusercontent.com/1910021/29711010-c74206e8-898a-11e7-8966-a25a327a6fd9.png)

**Comment by Yenthe666** [comment]
Hi @WeeDom,

Thank you for your report.
This may seem a bit strange but this is actually intended and normal behaviour. When you're navigation up and down the projects/tasks the breadcrumb just keeps track of where you went. When you keep going back and forth to the same views it'll keep stacking just like you did.
Odoo doesn't consider this a bug.

Regards,
Yenthe
