### ISSUE TITLE
[8.0] Search field for pricelists

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#19076]
**Impacted versions:**
8.0

**Steps to reproduce:**

- Go to the pricelists view
![image](https://user-images.githubusercontent.com/19410285/29717068-da70a58a-897b-11e7-81b6-cc2c16267195.png)

- Search a pricelist
![image](https://user-images.githubusercontent.com/19410285/29717516-6d475862-897d-11e7-8f82-8e5c7d2d813e.png)
- In English
![image](https://user-images.githubusercontent.com/19410285/29719027-a5767db2-8982-11e7-9b6a-83caa77056e1.png)

- In Spanish
![image](https://user-images.githubusercontent.com/19410285/29718085-8ccb826a-897f-11e7-9d49-9d91379fe60d.png)

**Current behavior:**
The base string was "Products Price" ([reference](https://github.com/odoo/odoo/blob/8.0/addons/product/pricelist_view.xml#L131)), is this correct?
This can be confusing because it's no a price.

**Expected behavior:**
Maybe, It could be better "Pricelist Name", but if the base string is right the problem was the spanish traduction "Precio de los productos" ([reference](https://github.com/odoo/odoo/blob/8.0/addons/product/i18n/es.po#L2409)), it means that you want to search by a price.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
