### ISSUE TITLE
[BUG / Inconsistency] In PO, dest location of move differs from dest location of operation, when a push rule applies

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#19088]
Impacted versions:
10.0 from last week approx.

Steps to reproduce:
1. Create a location WH/Stock/RawMat
2. Create a route with a push strategy WH/Stock -> WH/Stock/RawMat
3. Put that rute on a (stockable) product, that can be bought
4. Create a PO with that product and confirm this PO

Current behavior:
Developer-Mode = on

1. If you review the move, that has been created (Initial Demand Tab), you will see as destination location WH/Stock/RawMat
2. If you review the operation (Operations Tab), you will see destination location WH/Stock

Expected behavior:
The operation should go to the same destination as the move (in other words, respect the Push strategy). It does respect put-away-strategies, but this is just an alternative and less versatile than push strategies.

Video/Screenshot link 

**Ticket Nr: 767901**

**Comment by blaggacao** [comment]
Please find linked as PR my suggestion for a fix.

**Comment by gustavovalverde** [comment]
@Yenthe666 this seems like an important issue for inventory management, I'm also experiencing this.

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look please?

**Comment by Yenthe666** [comment]
@sle-odoo could you have a look?

**Comment by sle-odoo** [comment]
Hello,

I read the associated ticket and  the real issue was the use of automated push rule in a picking, which never worked. The support made a [video](https://www.youtube.com/watch?v=6_8B1trK09k&feature=youtu.be) to show the correct way to implement this flow, with a manual push rule.

Regards
