### ISSUE TITLE
[10.0/11.0-point_of_sale] account mapping is wrong with fiscal position

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#19084]
Impacted versions:
10.0/11.0

Steps to reproduce:
- Setup a fiscal position with account mapping for income account and receivable account
- Make a pos_order with the fiscal position

Current behavior:
- When pos is closed, account mapping is not done and the account_move does not take the mapped income account nor receivable account

Expected behavior:
- The account_move should take the mapped income account and receivable account

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
AFAIK, this is not handled in v10, but until v11. @pimodoo can you confirm this?

**Comment by invitu** [comment]
I pushed a PR for v11 : https://github.com/odoo/odoo/pull/25283

**Comment by cvinh** [comment]
https://github.com/odoo/odoo/pull/29433
