### ISSUE TITLE
needs examples of XMLRPC requests with javascript

### ISSUE THREAD

**Issue by natoine** [odoo/odoo#19083]
Hello Guys,

I'd like to make XMLRPC requests on Odoo using node.js
And I was wondering why don't you give an example of XMLRPC requests using javascript in your API documentation ?
http://www.odoo.com/documentation/10.0/api_integration.html

I've tried these node modules but still don't get any satisfying result :
https://github.com/baalexander/node-xmlrpc
https://github.com/faisalsami/odoo-xmlrpc

Thx

**Comment by Yenthe666** [comment]
@mart-e perhaps a nice addition to the docs?

**Comment by pedrobaeza** [comment]
Closing this as no real issue. This is still waiting for any contribution though.
