### ISSUE TITLE
[10.0] Suggestion for AccountAnalyticLine in Sales module, function _get_sale_order_line

### ISSUE THREAD

**Issue by seancallahan88** [odoo/odoo#19090]
Impacted versions:
10.0
Steps to reproduce:
When a quotation template has a contract associated with it, and both service and stockable items, when the sale is confirmed it will start as state 'done' instead of state 'sale'. This causes issues when the template was made in v9e and has gone through an upgrade.

Current behavior:
Any invoice made from above template will raise 
'raise UserError(_('The Sale Order %s linked to the Analytic Account must be validated before registering expenses.') % order.name)'

Expected behavior:
Invoice should be created as per regular sales.

The line 111 **'if order.state != 'sale':'**

perhaps should be instead 

**if order.state != 'sale' and order.state != 'done':**

**Comment by Yenthe666** [comment]
@qdp-odoo this is probably for you. What do you think about the suggested change?

**Comment by pedrobaeza** [comment]
The explanation is not very clear, and I also have my doubts and I have always seen these orders in "sale" state, so if you have a proposal, please make a PR about this. I'm closing this meanwhile.
