### ISSUE TITLE
Error introduced by bad SQL query in 6f39672eb686f07ca3941a878c24895c79f2c889 master

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19094]
Impacted versions: master
@tde-banana-odoo made the commit.
Steps to reproduce:
Pull the version with any existing invoices.  
Update account
Watch error.

In the function L496 of account/model/account_invoice.py
```python
    @api.model_cr_context
    def _init_column(self, column_name):
        """ Initialize the value of the given column for existing rows.

            Overridden here because we need to generate different access tokens
            and by default _init_column calls the default method once and applies
            it for every record.
        """
        if column_name != 'access_token':
            super(AccountInvoice, self)._init_column(column_name)
        else:
            query = """UPDATE %(table_name)s
                          SET %(column_name)s = md5(md5(random()::varchar || id::varchar) || clock_timestamp()::varchar)::uuid::varchar
                        WHERE %(column_name)s IS NULL
                    """ % {'table_name': self._name, 'column_name': column_name}
            self.env.cr.execute(query)
```
It uses the model rather than table name, so you get an error UPDATE account.invoice ... Relation does not exist.  

Current behavior:
Server won't start
Expected behavior:
Server starts

I just changed self._name to self._table as a workaround for now and it seems to work.

Video/Screenshot link (optional):

**Comment by tde-banana-odoo** [comment]
Indeed.

**Comment by tde-banana-odoo** [comment]
Done at https://github.com/odoo/odoo/commit/33feb5abcc0c92a964ff427e7201bf0cb1c6dff8 .
