### ISSUE TITLE
readonly fields in wizards - master - wishlist I guess

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19096]
Impacted versions: master

Steps to reproduce:
The new readonly fields behave differently to v10 in master.  It is a common use case (e.g stock returns) to populate a wizard with fields from the source model as essentially informational, but to access them on the completion of a wizard to perform some update (especially a relational field such as the associated picking line).

Under the new behaviour, this doesn't work and requires you to use the presently undocumented attribute force_save="1".

From a migration / development perspective and given that in every case for a wizard readonly field force_save is harmless, I think for wizards in particular, this behaviour should be considered to be made default.

Other alternatives are
- just to document force_save but that was some painful debugging.
- consider combining readonly and force_save into an attribute like user_readonly  - EDIT: actually that idea is dumb, as readonly can also be set on field

When this is released, you will want this covered before the issue reports come in.

**Comment by Yenthe666** [comment]
@gdgellatly isn't the new field option that Odoo is making an option for this? The readonly that only applies to the front-end?

**Comment by pedrobaeza** [comment]
@gdgellatly previously to this option, readonly fields are not sent back to the server, so the default force_create="0" is the proper one for preserving the same behavior. Why do you say the contrary?

**Comment by gdgellatly** [comment]
@pedrobaeza Lets not get confused.

Previous behaviour: readonly set in python - no write, readonly set in xml - write (e.g. If an onchange changed an xml readonly field it would still write).  Also the change didn't just effect readonly set in xml, also invisible.

But moreover, this is so long ago I can't even remember but I think the problem I was facing was populating readonly one2many from a parent model on the launch of a wizard.  I didn't even need to save the values.  

Probably stock returns seeing I mentioned them.  Without force_save wizard creation would fail (not 100% sure, its nearly a year).

A year on, perhaps just documenting the feature is easiest.

**Comment by gdgellatly** [comment]
I kind of don't run into this anymore, maybe its fixed, maybe I'm fixed.
