### ISSUE TITLE
_ans local variable - arch constrain error view

### ISSUE THREAD

**Issue by artatlasperu** [odoo/odoo#19115]
Odoo 8

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
local variable '_ans' referenced before assignment" while parsing /home/wzuniga/odoo/mymodules/odoo_tasita/tasita_desarrollo/views/modelo_componente.xml:12, near
<record id="view_form_desarrollo_componente" model="ir.ui.view">

<?xml	version="1.0"?>
<openerp>
  <data>

    
    <act_window id='action_desarrollo_modelo_componente'
		name='ModeloComponente'
		res_model='modeloprenda.componente.rel'
		view_mode='tree,form'/>

    
    <record id='view_form_desarrollo_modelo_componente' model='ir.ui.view'>
      <field name='name'>ModeloComponente</field>
      <field name='model'>modeloprenda.componente.rel</field>
      <field name='arch' type='xml'>
				<form>
	  			<header>
	  			</header>
	  			<sheet>
	    			<group name='group_top' string='Componentes por Prenda'>
	      			<field name='grupo_componente' on_change='_clear_componentes()'/>
	      			<field name='tipo_componente1' on_change='_compute_componente(grupo_componente, tipo_componente1)' attrs="{'invisible':[('grupo_componente','!=','01')],'required': [('grupo_componente', '=', '01')]}"/>
	      			<field name='tipo_componente2' on_change='_compute_componente(grupo_componente, tipo_componente2)' attrs="{'invisible':[('grupo_componente','!=','02')],'required': [('grupo_componente', '=', '02')]}"/>
	      			<field name='componente_id' options="{'limit': 15,'no_create': True, 'create_edit': False, 'search_more': False}"/>
	      			<field name='tipo_componente' invisible="1"/>
        			<field name='componentecolor_ids' context="{'colors': context.get('colores', False)}" >
								<tree string='Color'>
            			<field name='componente_color_id' domain='' options="{'no_create': True, 'limit': 10, 'search_more': False, 'no_open': True}" readonly="not context.get('colores', False)" />
            			<field name='numero_cabos' widget='integer'/>
          			</tree>
							</field>
							<field name='galga_id' options="{'limit': 10,'no_open': True, 'create_edit': False, 'search_more': False}"/>
		  				<field name='tipo_punto' on_change='_compute_punto(tipo_punto)' options="{'limit': 10, 'create': False, 'create_edit': False, 'search_more': False}"/>
		  				<field name='punto_id' options="{'limit': 20, 'create_edit': False, 'search_more': False}"/>
	      			<field name='observaciones' placeholder='Ingrese algunas observaciones del Componente a Utilizar'/>
	    			</group>

	    			<group name='group_bottom'>
	      			<field name='image' widget='image' width='150' height='150'/>
	      			<separator />
	      			<separator />
	      			<field name='image_optional' attrs="{'invisible':[('image','==',False)]}" widget='image' width='150' height='150'/>
	    			</group>

	  			</sheet>
				</form>
      </field>
    </record>

  </data>
</openerp>

I did not find documentation for this _ans variable, is exatly the same code for other view but the other view works,

**Comment by Yenthe666** [comment]
@artatlasperu do you have any extra code (JS, Python?) - this looks like problems with custom development.

**Comment by artatlasperu** [comment]
Thanks I fixed the error. the error was in the python code.
