### ISSUE TITLE
mrp_repair: NoneType object is not callable

### ISSUE THREAD

**Issue by crbll0** [odoo/odoo#19119]
Impacted versions:
9.0 Community 
Steps to reproduce:
Create a mrp_repair with a line and to_invoce = True and trying to save it
I got the next error.

  File "/opt/odoo/addons/mrp_repair/mrp_repair.py", line 560, in _amount_line
    line.repair_id.partner_id.id)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable

on _amount_line line 560. . . 
taxes = tax_obj.compute_all(cr, uid, line.tax_id.ids,
                                            line.price_unit, cur.id,
                                            line.product_uom_qty,
                                            line.product_id.id,
                                            line.repair_id.partner_id.id)

**Comment by sle-odoo** [comment]
Hi,
Sorry but i was not able to reproduce the issue.
If you're still facing it and are able to reproduce it on our runbot, feel free to comment and i'll reopen the issue.

Regards
