### ISSUE TITLE
[11] Issue in website_slide demo file

### ISSUE THREAD

**Issue by XtremXpert** [odoo/odoo#19136]
Impacted versions: master

Steps to reproduce: install Odoo with demo data then install website_slide 

Current behavior: Error parsing the /data/website_slide_demo.xml, commenting the file in the manifest make it install correctly

Expected behavior:No error and flawless install 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @XtremXpert,

Thank you for your report.
This bug has been fixed in the meanwhile. Please update your local Odoo and try again.

Regards,
Yenthe
