### ISSUE TITLE
[ODOO 10] Unknown error during import: <class 'odoo.exceptions.UserError'>: Configuration error! Could not find any account to create the invoice, are you sure you have a chart of account installed? at row 2 Resolve other errors first

### ISSUE THREAD

**Issue by 3bdul3zziz** [odoo/odoo#19151]
Hi All
Have a good day,

When i import excel bulk invoices from ( ODOO 10 >> Accounting >> Customer invoices >> Import ) i get this message:

> [Error] Unknown error during import: <class 'odoo.exceptions.UserError'>: Configuration error! Could not find any account to create the invoice, are you sure you have a chart of account installed? at row 2 Resolve other errors first

I dont know where is the problem, please help me to resolve that 
The excel in below link:
https://drive.google.com/open?id=0Byt2gz3YDPzNU1lQajY5UDlod1E

Thank you :)

**Comment by Yenthe666** [comment]
Hi @3bdul3zziz,

Thank you for your report.
Have you configured the whole accounting with a chart of account installed & configured?
Can you reproduce this on an official runbot (at http://runbot.odoo.com)?

Regards,
Yenthe

**Comment by 3bdul3zziz** [comment]
Hi @Yenthe666 

Is the "chart of account" a "Accounting and Finance Module"?
If this isn't it, How can i install it?

Thank you :)

**Comment by Yenthe666** [comment]
Hi @3bdul3zziz,

It is an app that is always named Country - accounting which will install the account specifics for your country. Example:
![image](https://user-images.githubusercontent.com/6352350/30049490-3a171b70-921b-11e7-92f2-c5169d89dab0.png)
If I live in Belgium I would install "Accounting - Belgium" for example.

Regards,
Yenthe

**Comment by 3bdul3zziz** [comment]
Dear @Yenthe666

How can i create bulk invoices by import excel or CSV file?

Thank you :)

**Comment by Yenthe666** [comment]
Hi @3bdul3zziz,

Have a look at https://www.odoo.com/documentation/user/10.0/general/base_import/import_faq.html
If you have any problems like this feel free to post them on the official help forums (http://help.odoo.com) as Github is only for bugs.
P.S: Is the previous problem solved?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
I'm going to assume the other issue was solved as there has been no response.
