### ISSUE TITLE
Error in filters menu view

### ISSUE THREAD

**Issue by Davidluna19** [odoo/odoo#19169]
Impacted versions: 10.0

Steps to reproduce: Add multiple custom filters consecutively

Current behavior: You do not see the end of the menu or leave to navigate to reach the end.

Expected behavior: You can delete custom filters or navigate to the end of the menu where you see the buttons "Apply" and "Add Condition"

Video/Screenshot link (optional): 
![sin titulo](https://user-images.githubusercontent.com/4563802/29889861-0dd2c286-8d9c-11e7-9b56-adfa37c5ee1a.jpg)

**Comment by Yenthe666** [comment]
Hmm, mainly usability / UI related instead of a real bug I guess.
@nim-odoo can you have somebody from the UI team have a look at this?

**Comment by Davidluna19** [comment]
Yes, it refers to usability.
Anyway, I found it useful to report it, as it is quite uncomfortable, having to leave the menu and come back to apply more filters or change them.

**Comment by pedrobaeza** [comment]
Version 10.0 is out of support, so I'm going to close this. If this still happens on later versions, please comment back.
