### ISSUE TITLE
Error while posting invoice to ZATCA odoo sh

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#191754]
### Odoo Version

- [X] 17.0 sh

Server returned an unexpected error: {"validationResults":{"infoMessages":[{"type":"INFO","code":"XSD_ZATCA_VALID","category":"XSD validation","message":"Complied with UBL 2.1 standards in line with ZATCA specifications","status":"PASS"}],"warningMessages":[],"errorMessages":[{"type":"ERROR","code":"BR-KSA-39","category":"KSA","message":"The invoice must contain the seller VAT registration number (BT-31) and/or seller group VAT registration number (KSA-18).","status":"ERROR"}],"status":"ERROR"},"reportingStatus":"NOT_REPORTED"}

**Comment by oaliflint** [comment]
I am facing the same issue, 
do you think it's related to the Gov authority?

**Comment by oaliflint** [comment]
i think if you rollback your odoo sh to version 17.20241216 it will work until they fix it, 
try to label the issue.

**Comment by AamerAli1** [comment]
We are facing the same issue on our SH servers , but On-premise running older versions have no issue and ZATCA invoices are being processed without any issues.

**Comment by nesmaodoo** [comment]
any solution to this?

**Comment by oaliflint** [comment]
@nesmaodoo, the solution is mentioned above just rollback on 17.20241216

**Comment by bodyx1994** [comment]
> @nesmaodoo, the solution is mentioned above just rollback on 17.20241216

did you try it

**Comment by oaliflint** [comment]
@bodyx1994 yes 😄
