### ISSUE TITLE
[10.0e] Can't quality check partial receipts

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#19186]
**Impacted versions:** 10.0 Enterprise (quality module)

**Steps to reproduce:**
1. create products A and B **both with quality points**
1. create picking for products A and B
1. pick all of product B **but not A** (set done qty to full required amount on product B)
1. click Quality Checks button

**Current behavior:**
User is prompted to inspect product A

**Expected behavior:**
User should be able to inspect product B without inspecting product A

**Video link:**
https://youtu.be/VgZhMvuUyG4

**Comment by fmdl** [comment]
Dear

I have made this fix : https://github.com/odoo/enterprise/pull/1252

Linked issue : https://github.com/odoo/odoo/issues/18497

**Comment by sle-odoo** [comment]
fixed at rev https://github.com/odoo/enterprise/commit/6eb56ef10441c7662478dd8a0bb6ac5c98bb0ef0

thank you
