### ISSUE TITLE
Missing menu

### ISSUE THREAD

**Issue by j209** [odoo/odoo#19219]
My OS is win 10
After installation odoo(All the process was sucessfull) my first page show any thing!
I unistall -reinstall odoo three times and test other browsers and have the same problem.
![untitled](https://user-images.githubusercontent.com/18129232/29999199-b0021466-9054-11e7-835a-768948dc9829.png)

**Comment by madhavcoder** [comment]
use ubuntu 14 as your OS

**Comment by dan18fan** [comment]
Indeed with the comment above, but stilla it might be a module not loading or something corrupt, did you modify anything in odoo's folder?

**Comment by j209** [comment]
No.
As I mentioned,I install a fresh copy three times after complete uninstalling.

**Comment by Yenthe666** [comment]
Possible related to https://github.com/odoo/odoo/issues/19368 perhaps?

**Comment by Bedo1212** [comment]
I got the same issue with a fresh installation for Odoo 11 on windows 10  .

**Comment by ALVSoft** [comment]
Like @Bedo1212 , I got the same issue with a fresh installation for Odoo 11 on windows 10 but, there is no problem on windows 7.

**Comment by Yenthe666** [comment]
@d-fence anything packaged related perhaps?

**Comment by d-fence** [comment]
I'm pretty sure that it's related to this one https://github.com/odoo/odoo/issues/20441

May I ask you to check in the registry of windows if something exists like 'HK_CLASSES_ROOT.js' with a value pair like 'Content Type', 'text/plain' ?
It could explain why the '.js' files are detected as 'text /plain'.

A patch was merged in master:
https://github.com/odoo/odoo/pull/20731

**Comment by d-fence** [comment]
Fixed here: https://github.com/odoo/odoo/commit/77ca51f0892ec62d357e099d5c2a91e580e35383

**Comment by AmrDataHolic** [comment]
I had the same issue with the same version on the same OS
Tried many Solutions.....  The only worked solution is :  
1- open the path : C:\Program Files (x86)\Odoo 11.0\server\odoo\addons
2- remove the last addon you installed
3- restart the service of Odoo v11.0
Now ALL IS WORKING PERFECTLY
This is the easy solution ..... simplest way to get back online>>>
no need for complexity
