### ISSUE TITLE
[saas-17] Error changing currency on purchases

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#19218]
**Impacted versions:** saas-17

**Steps to reproduce:**

To reproduce it is necessary to select a supplier with a different currency than the main currency

- Create a sales order with a product that triggers a purchase order

![so098 odoo](https://user-images.githubusercontent.com/5775695/29998476-e93241b2-8ff9-11e7-8ff8-d236546bdcf8.png)

-  Find the related purchase order and modify the currency

![po00042 3 000 00 odoo 1](https://user-images.githubusercontent.com/5775695/29998477-f33c65ca-8ff9-11e7-8b75-4e34e4a6caf6.png)

**Current behavior:**

- Shows a permissions error when saving the purchase order after changing currency

![po00042 3 000 00 odoo 2](https://user-images.githubusercontent.com/5775695/29998484-1a709558-8ffa-11e7-9a16-603bbe7a49f9.png)

![po00042 3 000 00 odoo](https://user-images.githubusercontent.com/5775695/29998479-fb3dd13c-8ff9-11e7-9fe6-12551c2fcabd.png)

**Expected behavior:**

The purchase order must be saved with the selected currency change

**Video/Screenshot link (optional):**

https://youtu.be/9D4GADJthuU

**Comment by sle-odoo** [comment]
Hello,
Saas-17 is not supported, i'm thus closing thus bug report.

Thank you
