### ISSUE TITLE
[UX BUG] Reconcile reverting moves automatically

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#19222]
Steps to reproduce:
1. Create a Account Move which touches a reconcilable, for example payable, account
2. Revert it
3. Do for example a bank statement Reconciliation

Current behavior:
Both the original and the reverted Account Move Line will show up as possible counterparties for any matching payment.

Expected behavior:
Account Move Lines are reconciled automatically, so that they cannot be taken as counter party for a payment by mistake.

**Comment by qdp-odoo** [comment]
It's not occuring anymore since the case since saas-14 (https://github.com/odoo/odoo/commit/7544c22d).

Should you need it in prior versions, @nim-odoo  will be able to tell you if the support can backport it or not. I let him decide and close (or not) this issue

**Comment by nim-odoo** [comment]
Since this is a major change in behavior, it won't be merged in v10. Anyway, you can cherry-pick the following commits on your side if you want: 7544c22d and df755ef6d4b47
They should apply without problem.

**Comment by blaggacao** [comment]
Wow, thank you guys for the quick response!
