### ISSUE TITLE
[v10] Calendar view mode display UTC hour instead of user local hour

### ISSUE THREAD

**Issue by jreders** [odoo/odoo#19220]
Impacted versions: v10

Steps to reproduce: In calendar, create an event, setup start time & duration and save.

Current behavior: the event in calendar view is in UTC,so as i'm in France (utc+2), it is displayed 2 hours early. In list view start/end time are ok

Expected behavior: the event in calendar view should start/stop at the time configured by user

**Comment by jreders** [comment]
I think i found the problem let's had a +1 if it work for you too :)

in terminal, connect to your server

$ sudo dpkg-reconfigure locales
$ sudo dpkg-reconfigure tzdata
$ date


This solve the problem for me and i hope it will help you.

**Comment by Yenthe666** [comment]
Yep - looks like the local server configuration which causes the time to be off against the Odoo.
Thanks for the details & answering your own issue @jreders 😉
