### ISSUE TITLE
[stock] Stock Move Price Unit not show

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#1923]
Impacted versions:

8.0 and above - at least
Steps to reproduce:

create a new purchase order 
with order line Product1 Price: 10 ->
Go to Receptions (Delivery Order / Invoice come with the Price 10.5 - No field to change the price in tree view of stock moves)->
Hit Transfer Button ->
No field to change the price the wizard.

Current behavior:

Price Unit Fields not shown in both views

Expected behavior:

For receptions the price unit fields to be shown.

**Comment by Yenthe666** [comment]
Hi @feketemihai,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
