### ISSUE TITLE
RELAXNG Error - I don't know if an error or not

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19245]
Impacted versions: master - in trying to resolve #19239 issues in custom code I had the following scenario.

An Abstract Model with fields and a view defined.  For a variety of reasons, each of these are then realized as seperate objects for their respective business document lines (sale order line, invoice line, purchase line, stock move etc) where the only field added is an M2O e.g. invoice_line_id.

To date I had just been using context view ref back to the abstract model and it seemed to be working fine.  When the save stopped working, I figured that maybe its because my Abstract Model view was declared for the Abstract rather than realized model.

So I inherited the Abstract View, changed name and model etc and set view mode as primary and an empty arch.  Seems a valid operation to me.

It isn't.  As I say not sure if an issue as it worked fine before, and it still worked even with these other issues, insofar as the view still displayed, onchanges worked etc, but thought I'd mention it, that there is probably a use case for inherited views with an empty arch especially with view mode primary.

In the end I just worked around by declaring an empty tag in the arch.  e.g.

```
<field name="price_unit" position="after" />
```

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hey @gdgellatly,

Are you still facing this issue and is it still relevant?

**Comment by gdgellatly** [comment]
I don't know tbh. I rewrote that code.

**Comment by pedrobaeza** [comment]
This is not happening anymore AFAIK, so closing. If you are still facing this, please scream ;)
