### ISSUE TITLE
Web Master Editable x2many onchange

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19240]
Impacted versions: Master #19239 is the placeholder report

Steps to reproduce:
On runbot
Go to invoicing
Fill Header and Add a line
Pick a product (cursor stays at product)
Tab, click over to quantity
Change qty press tab - cursor stays at quantity
Press Tab - now you are in section (field after product)

Current behavior:
As above
Expected behavior:
Honestly I think this commit changing onchange return cursor is misguided (as well as buggy as described above), user presses tab, then they expect to tab to next field. https://github.com/odoo/odoo/commit/2728fe1ec1ac7e99819d0f30f29a1814b00c82a4#diff-c9e667922e5e2156581f5fda2b10b75f (I'm only assuming its this one)

Video/Screenshot link (optional):
@ged-odoo

**Comment by ged-odoo** [comment]
@gdgellatly Thank you for your report.  I am always scared to come back from vacation and to see what was merged... The commit you mentioned is definitely the culprit.  I'll see what I can do, as soon as I can.

**Comment by ged-odoo** [comment]
@mge-odoo

**Comment by mge-odoo** [comment]
Hi,

The issue seems to be fixed in master. Probably by the same revision (https://github.com/odoo/odoo/commit/36b4d78a2678806b25aaa5650b64496f9da9d205) I mentioned in your other issue.

Again, thanks for the time you have taken to report these issues.

Regards,

Martin
