### ISSUE TITLE
[stock] Stock Move - Price Unit on Purchase in different currency

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#1924]
Impacted versions:

8.0 and above - at least
Steps to reproduce:

Company Currency - RON 
create a new purchase order - Currency - EUR ->
Condirm it ->
Go to Stock Moves ->
Price on the stock move calculated at purchase order date rate.
Delivery after 3-5 days.Currency rate modified.
Go to Receptions ->
Hit Tranfer ->

Current behavior:

The price unit remained at old price, meaning the stock value is not the correct one.

Expected behavior:

Before transfer the stock moves, check if the purchase was made in a different currency, and compute the price with reception date in context.

**Comment by Yenthe666** [comment]
Hi @feketemihai,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
