### ISSUE TITLE
Got error while evaluating website feature in odoo master

### ISSUE THREAD

**Issue by ravi-webkul** [odoo/odoo#19251]
Impacted versions: master

Steps to reproduce: After enabling "Extra step option" on website getting below error during checkout.

Current behavior: 
**AttributeError: 'sale.order' object has no attribute '_get_website_data'**

Also i noticed that payment icons are not showing during checkout.

Expected behavior:
it should open extra step for checkout.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be perhaps for you?

**Comment by tde-banana-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/76976692531255acf39e669b9426a71826742c29 . Thanks !
