### ISSUE TITLE
Odoo Enterprsie

### ISSUE THREAD

**Issue by fiyona** [odoo/odoo#19277]
Am so interested in buying the enterprise version but i have a few inquiries

1. i was told by one of your support that 96 USD is paid per user per year and i want to know whether in this case the 96 USD is paid per single company or single user within the company account? or the admin on the main portal

2. if i buy the Enterprise version , i would like to know if i can fully customize it to my own company brand while i use it in my company and have all odoo logos and copyrights off

3. i want to host it on Amazon servers ,i much do i have to pay per annum or one off

  Thanks

**Comment by Yenthe666** [comment]
Hi @fiyona,

Thank you for your report.
The github tracker is however for bugs in the code, not for questions. Please ask them on the help forums or by contacting Odoo by e-mail (https://www.odoo.com/en/page/contactus)

To answer your questions:
1. The price is always per user. If your Odoo has a multicompany environment you will still pay for 1 user, even if you have multiple companies (in the same database).
2. You can remove all logo's and change the lay-out of the Odoo - please do this in a custom developed module to prevent issues with custom code though.
3. The prices for hosting depend on what Amazon charges and what resources you need.

P.S: I don't work officially for Odoo so feel free to still contact them.
I hope my answers helped them.

Regards,
Yenthe
