### ISSUE TITLE
Wrong payment amount for invoices with negative amount

### ISSUE THREAD

**Issue by dufresnedavid** [odoo/odoo#19280]
Impacted versions:
10.0

Steps to reproduce:

1 - Create a supplier invoice with a negative amount (-70$).
2 - Click on REGISTER PAYMENT

Current behavior:

The payment amount is 70$ outgoing. The system does thinks I am paying an invoice, but actually, it's a credit note.

If I select 2 invoices in list view, one positive (150$) and one negative (-70$), the system will propose that I pay 220$ to my supplier instead of 80$.

Expected behavior:

The system proposes the correct amount to pay. Negative invoices are treated exactly the same way as credit notes, because it is the same thing.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/8628981/30082926-83623e56-925a-11e7-9f5c-72335cc25b71.png)

**Comment by fwillier** [comment]
Have you solved, or found a way to solve this issue as I have the same problem, and have invoices (negative) and credit note (positive, which I created to balance the negative invoice), and hoping i could match both of them, 
But Odoo does let me do this, and I have a negative invoice stuck and a positive credit note stuck.

Thanks,

Sincerely,

**Comment by gokhanerdogdu** [comment]
The same problem also exists in V11.

**Comment by Gyuri77** [comment]
and V9 of c(o)urse. Maybe the point of view of the odoo, is every invoice must be gt 0. 
The fast "solution" for this is making positive incoming invoices instead of negative outgoing.  But in Hungary for example it is normal, that you can create an invoice with negative total. 
For example refunding some product is a negative invoice. Customers can not give you an invoice, you must give them a negative outgoing invoice for returned products.

**Comment by sergiocorato** [comment]
Fix for v. 8.0 (with a separated module, but can obviously be put in original code): https://github.com/efatto/efatto/commit/1f8496127b8fd9b63a73d6b89a8faa2528e186d7

**Comment by sergiocorato** [comment]
In V12 it is disabled the ability to create negative invoice/refunds, not a good thing.

**Comment by sergiocorato** [comment]
I did a PR to solve this issue: https://github.com/OCA/account-payment/pull/222

**Comment by pedrobaeza** [comment]
This is not a problem, but a design decision. No negative invoices are possible to be created. For that, you have the positive refund. And thus, payments for that are not handled the way you expect.

Closing this as "won't fix".
