### ISSUE TITLE
How to add a menu category shop in home page website Odoo 9

### ISSUE THREAD

**Issue by BoubakerAB** [odoo/odoo#19296]
Impacted versions: [v9]

Steps to reproduce:
In website sale odoo / shop I can add the menu to the left of the page containing each category 
like the image
<img src="http://zupimages.net/up/17/36/086l.png"   width="800" height="502">

My problem :
 How to add this menu in   **home page**
 
thank for all

**Comment by Yenthe666** [comment]
Hi @BoubakerAB,

Thanks for your report.
The Github issue tracker however is only for bugs in the official code, not for asking questions.
Please do ask this question on the official help forums, where there are a lot of people that can help you (http://help.odoo.com).

As to answer your question: you'll have to write your own module to handle this, you cannot do this by default.

Regards,
Yenthe

**Comment by BoubakerAB** [comment]
Thank you for caring @Yenthe666

**Comment by Yenthe666** [comment]
You're welcome - best of luck!
