### ISSUE TITLE
Access Error

### ISSUE THREAD

**Issue by audit01** [odoo/odoo#19307]
Impacted versions: Odoo 10

Steps to reproduce: Sales>Sales/My Pipeline>Create

Current behavior: Sale/User-own Documents cannot save the new opportunity.

Expected behavior:  Sale/User-own Documents can save the new opportunity.

![my pipeline](https://user-images.githubusercontent.com/31650876/30142440-5b8c8f76-93b3-11e7-8cfb-70d81748c95c.png)
 opportunity.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @audit01,

Thanks a lot for your report.
I've just tested this and I can confirm that this is an issue, both in V10 and V11.
OPW 803071.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @audit01,

In fact, this is because the user is not attached to any sales teams. After adding the user to a team he/she can create new opportunities without any problems.
[This video](https://youtu.be/uSs9pDa7S74) shows how it works.

Regards,
Yenthe
