### ISSUE TITLE
odoo 10.0 community version upload image while answering survey question.

### ISSUE THREAD

**Issue by inteslar** [odoo/odoo#19310]
hi,

i am customizing "Survey" app of odoo 10.0.

i want user to upload image while answering the questions of survey.

user must be upload image for each question in survey.

how can this be done? 

Best Regards!

**Comment by Yenthe666** [comment]
Hi @inteslar,

There is no default possibility to upload files for every question you ask to the end user.
If you want this you'll need to write your own module to add this in.

Regards,
Yenthe

**Comment by inteslar** [comment]
thank you sir for you reply.
and this is what i am doing.
please check the image below.
![syrvey image](https://user-images.githubusercontent.com/26567265/30149208-d9d7e6b0-93b7-11e7-939a-4803ec4d3a1e.PNG)
i need to get this uploaded image (by the user who is answering)
and store in model/table user_input_line as i have a field of type binary there.

can you please help?

**Comment by Yenthe666** [comment]
Hi @inteslar,

Please ask this on the official help forums, a lot of people can help you there (http://help.odoo.com).
This all comes down to writing extra code in order to achieve this.

Regards,
Yenthe

**Comment by inteslar** [comment]
yes sir i already have posted on odoo forum. let us c. below is the link of my post at odoo forum
https://www.odoo.com/forum/help-1/question/odoo-10-0-community-version-upload-image-while-answering-survey-question-123609
