### ISSUE TITLE
[10.0] account: accounting reports wrong hierarcy in pdf file

### ISSUE THREAD

**Issue by repodevs** [odoo/odoo#19316]
Impacted versions:
10.0

Steps to reproduce:
- Create Hierarchy report more than 3 view type
- Print That report

Current behavior:
- Report in 4 view type and its account detail with hierarchy will the same position with that parent view

Expected behavior:
- Report in 4 view type and its account must not the same position with that parent view

Video/Screenshot link (optional):

1. Hiererchy Report
![selection_223](https://user-images.githubusercontent.com/13567128/30154211-62d87f94-93e3-11e7-9efe-a68115e58fc9.png)

2. Accounts Value
![selection_224](https://user-images.githubusercontent.com/13567128/30154031-c29be494-93e2-11e7-8db5-942e81cb0470.png)

3. PDF Report
![selection_222](https://user-images.githubusercontent.com/13567128/30154208-5dd4f784-93e3-11e7-84a3-fe450fd6ff1c.png)

I think it's happening because level of report/accounts value forced to `4` (https://github.com/odoo/odoo/blob/10.0/addons/account/report/account_report_financial.py#L127)
if yes, why this level value forced to `4` ? 

CC: @Yenthe666 @qdp-odoo sorry ping-in you

**Comment by Yenthe666** [comment]
Yep, I believe this was done on purpose. @qdp-odoo would you accept a PR that bumps it one more level?

**Comment by repodevs** [comment]
@Yenthe666 is there any already PR for this?

**Comment by repodevs** [comment]
I have a patch in my local odoo for this, if needed I will make PR.

**Comment by Yenthe666** [comment]
@repodevs there is no PR for that as far as I'm aware. You're always welcome to make one but I can't guarantee it'll be accepted, that is up to qdp-odoo.

**Comment by be-cloud-js** [comment]
I would definitively vote for this PR as I did the same patch on my install.

@qdp-odoo any idea why it was done this way ?

**Comment by qdp-odoo** [comment]
we didn't really need it before but it has been improved in v11 to go up to level 9.

Because of this and also because the original bug report concern only a cosmetic change that appears rarely (and I don't even talk about the fact 'view' accounts aren't existing anymore outside any OCA module), I'm closing this issue

**Comment by be-cloud-js** [comment]
Hello,

I would favor this if we were speaking of v8 or v9, but we still have some time before everyone migrate to v11.

My question is simple, if we prepare a PR (or a backport of v11 in that matter) will it be accepted.

Jerome
