### ISSUE TITLE
Change Image 

### ISSUE THREAD

**Issue by auditum-sbl** [odoo/odoo#19318]
Description: 

Hello,
I would like to edit a linked image or change the link in edit mode, but in Mozilla Firefox is
this not possible, because I am always forwarded to the page to which the image links

Can you help me? 

Video/Screenshot link (optional):

![bildschirmfoto 2017-09-07 um 11 05 21](https://user-images.githubusercontent.com/22189188/30155380-ef08e70a-93bc-11e7-9107-c190e15129ad.png)
[Change linked Image.zip](https://github.com/odoo/odoo/files/1284099/Change.linked.Image.zip)

**Comment by Yenthe666** [comment]
Hi @auditum-sbl,

I've just tried this on the latest Odoo 10 but it seems to work fine out of the box?
![image](https://user-images.githubusercontent.com/6352350/34438568-0efe9ed0-eca8-11e7-9c60-8ad6c3a5cf93.png)
After double clicking on the image:
![image](https://user-images.githubusercontent.com/6352350/34438577-1b26458c-eca8-11e7-8078-2f9b47c34c0b.png)

@qsm-odoo perhaps there is room for a usability improvement on the website here though. I've just added an image through a link and clicked on add. I've saved, then double clicked the image again to get the edit dialog. However, the original link from my image is nowhere to be seen / found. Perhaps it should be visible somewhere?

Regards,
Yenthe

**Comment by qsm-odoo** [comment]
Hello,
I indeed never saw the bug reported here... maybe need more information.
And yes, this of course needs usability improvements and we are currently working on it (at least, we are working on making the link and media dialog better and making them interact with each other in a more intuitive way).

**Comment by Yenthe666** [comment]
@qsm-odoo thanks for the fast response. I guess that'll be all for V12? 😉

**Comment by qsm-odoo** [comment]
Probably, yes :smile:
