### ISSUE TITLE
Simple Fix in setup_dev.py forgotten ")"

### ISSUE THREAD

**Issue by cantecim** [odoo/odoo#19315]
Impacted versions:
11.0

Steps to reproduce:
Compile all the repo via "python -m compileall"

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Hello, could someone throw an ")" end of the line 156 of setup/setup_dev.py :)
https://github.com/odoo/odoo/blob/18d63d4717657f4b43a61df2fda016f0a6316a65/setup/setup_dev.py#L156

Thanks.

**Comment by xmo-odoo** [comment]
Should be fixed in the saas-17 branch, and FWIW you had linked to a commit *before* the incorrect change so I spent some time counting parens and finding them to match 😉
