### ISSUE TITLE
Valid Czech VAT number not accepted

### ISSUE THREAD

**Issue by andreparames** [odoo/odoo#19327]
Impacted versions: 10.0

Steps to reproduce: Create a partner with the VAT number CZ682127228

Current behavior: Show message saying the format is invalid

Expected behavior: Accept the number, as VIES reports it as valid.

-----------------

I have investigated a bit, and it seems the library that actually validates the number (python-stdnum) treats it as a special case, and it might be incorrect, although I was unable to find the official algorithm for calculating the check numbers. I've opened [an issue in their tracker](https://github.com/arthurdejong/python-stdnum/issues/51), but since Odoo is affected, maybe a contribution is in order?

**Comment by andreparames** [comment]
It seems the Odoo Runbot doesn't show this problem, is there a fix that I'm missing?

**Comment by Yenthe666** [comment]
Hi @andreparames,

Thank you for your report.
Which version of vatnumbers are you using? Odoo uses the following version(s) for the package(s): https://github.com/odoo/odoo/blob/10.0/requirements.txt#L36
@odony could you verify the runbot runs on this version too?

Regards,
Yenthe

**Comment by andreparames** [comment]
Yeah, that's it. Version 1.1 doesn't use stdnum and seems to work OK. I think I found the bug in stdnum, I just wonder why the Odoo runbot seems fine.

**Comment by andreparames** [comment]
The author of stdnum [confirmed and fixed the bug](https://github.com/arthurdejong/python-stdnum/issues/51#issuecomment-328047303). I'm still wondering why the Runbot doesn't exhibit this problem, though.

**Comment by Yenthe666** [comment]
That is quite a fast response and fix rate! I can't check the runbot servers so I don't know on which version that runs (atleast, not sure).
I guess that if the library has a new version you could make a PR (against the master version) to update the `requirements.txt` to the newest version.

**Comment by andreparames** [comment]
@Yenthe666 yeah, very fast! Much respect for @arthurdejong. I'll make a PR as soon as a new version is uploaded to PyPI.

**Comment by Yenthe666** [comment]
Alright - closing this one as it is no longer a problem then.
