### ISSUE TITLE
[9.0] Field not correctly populated into export depending on position of exported fields

### ISSUE THREAD

**Issue by eldy** [odoo/odoo#19330]
Impacted versions: 9.0

Steps to reproduce:
I extended the model product.template to add a field called "fieldabc"

Current behavior:
I export the stock move, export all data to get 3 fields:
the ID of move + fieldabc + productid => I get a file with column fieldabc that is filled with value into field "fieldabc" when line is related to a product where fieldabc is fielld and i get the value of product name instead of empty when value for fieldabc is not filled on product.

If I do the same export, and i put productid before fieldabc, then fieldabc is correctly populated (with a value for product that has a value, without when product has no value).

Expected behavior:
Having same result into a column whatever is position of fields into export.

**Comment by Yenthe666** [comment]
Hi @eldy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
