### ISSUE TITLE
[8.0][auth_signup] 404 in /web/signup link

### ISSUE THREAD

**Issue by Softdil** [odoo/odoo#19343]
Hello everyone, I have a single db Odoo with website installed on it. I added website_sale on it and also installed a theme module for the website. After several hours trying to fix this issue and reading through many other similar issues I am not able to get the signup to work... I know @mart-e and @Yenthe666 have seen this issue for a long time, but **this is not a multi-db environment**

I tried to uninstall the theme in case it was interfering with the signup, but it's not the case. I also configured the dbfilter and created a [db].domain.com:8069 subdomain to reach my single DB but it didn't work. I don't know what else to try. Am I missing something?

Impacted versions: 8

Steps to reproduce:

1. Install website and auth_signup.
2. Go to your http://odoo.domain.com:8069/web/signup
3. Cry

Current behavior:

I get a 404 error

Expected behavior:

A page that allows new users to sign up

**Comment by Yenthe666** [comment]
Hi @Softdil,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
