### ISSUE TITLE
[8.0] Remove Message BCC from Header to hide BCC in the email receive

### ISSUE THREAD

**Issue by xubiuit** [odoo/odoo#19344]
https://github.com/odoo/odoo/blob/7805cf5fef8257addcd16c98e46ba07096769895/openerp/addons/base/ir/ir_mail_server.py#L433

Please insert more line
`del message['Bcc']`
after line 433 to remove Bcc from Header.

We just need insert the bcc to email listing to toaddrs, do not need to show bcc in the header.

Reference:
[python: how to send mail with TO, CC and BCC?](https://stackoverflow.com/questions/1546367/python-how-to-send-mail-with-to-cc-and-bcc)

Regards,
Binh Nguyen

**Comment by Yenthe666** [comment]
Hi @xubiuit,

Thank you for your report.
The Odoo V8 support will be stopped within one month. As this is not a bug and neither is anything broken this won't be changed. This has been a stable version for over two years and changing this behaviour would risk breaking more than that it improves.

P.S: You can still create your own module, inherit the function and modify it as you please though!

Regards,
Yenthe

**Comment by xubiuit** [comment]
OK, I see
Thanks :)
