### ISSUE TITLE
Integer values are replaced with empty string in some locales because thousands separator is "."

### ISSUE THREAD

**Issue by cantecim** [odoo/odoo#19357]
Impacted versions:
11.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Hello, there is a small problem in parseInteger function https://github.com/odoo/odoo/blob/ad2dc1e7cd31bb7847f33a7f20ac3300dbc81960/addons/web/static/src/js/fields/field_utils.js#L495

We should escape regex like in parseFloat. so the line should be
https://github.com/cantecim/odoo/blob/8d647bf4296fe79a3b6fc0cc8f0d581e53a46cd1/addons/web/static/src/js/fields/field_utils.js#L495

Could someone do that ?

**Comment by cantecim** [comment]
Hello everyone, can we say it'll be fixed before the release ?
It is very important fix for us. Turkish users wont be able to use many models with integer fields
Thanks

**Comment by jbeficent** [comment]
@cantecim The fix is now being proposed.

**Comment by mge-odoo** [comment]
Hi @cantecim 

I see that some modifications have been done regarding the `parseInteger` function recently.
See rev. https://github.com/odoo/odoo/commit/b8dac2ff32d2e875e2f43c91f702e17adc938f7e

Do these changes fix your issue?

Regards,

Martin

**Comment by cantecim** [comment]
@mge-odoo yes totally, thanks
