### ISSUE TITLE
Cancel Credit Note with invoice partially paid

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#19366]
**Impacted versions:**
10
**Steps to reproduce:**
Tested on runbot
Create a customer invoice and paid partially(amount total 4,610.00) paid 4000, amount remaining 610. Create a credit note for invoice, validate and reconcile amount remaining of invoice with credit Note.
Invoice is paid completely, Credito note is paid partially, its is good.

Paid Invoice
![image](https://user-images.githubusercontent.com/7775116/30244958-d3736702-958f-11e7-91ea-bb87e520c938.png)

Invoice is paid partially
![image](https://user-images.githubusercontent.com/7775116/30244960-f74dddec-958f-11e7-8f8e-03f6056a0545.png)

Create a Credit Note
![image](https://user-images.githubusercontent.com/7775116/30244963-05eda184-9590-11e7-8667-ea3a2b29bf9d.png)

Validate and reconcile Credit Note with remaining amount of invoice
![image](https://user-images.githubusercontent.com/7775116/30244969-3f51597a-9590-11e7-9953-62c85f02d63a.png)

Now, Credit Note is Open, invoice is paid
![image](https://user-images.githubusercontent.com/7775116/30244973-6a323434-9590-11e7-955c-35f98daccc10.png)

Go to Credit Note and Unreconcile payment.
![image](https://user-images.githubusercontent.com/7775116/30244981-a2028f80-9590-11e7-9992-14540ce6a005.png)

**Current behavior:**
Invoice is Open and two payments are unreconciled
**Expected behavior:**
Invoice is Open but only payment from credit note must be unreconcile, other payment not. Please any solution????
![image](https://user-images.githubusercontent.com/7775116/30244992-dc49758c-9590-11e7-9112-a43a511455a6.png)

Video/Screenshot link (optional):

**Comment by proloycoder** [comment]
good morning

**Comment by celm1990** [comment]
Any solutions???

**Comment by celm1990** [comment]
solved in commit 6d195ee603503242a6b120889ac63d990b357ec3 and da27836f454ab65fbd268e6d19fbf4f2d4977a6c thanks

**Comment by Yenthe666** [comment]
Thanks for the followup!
