### ISSUE TITLE
[OE] Idea : show next activity and message on the apps screen

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#19364]
Dear dev Team

On Odoo community, when you start your session, it is start by the apps "Discuss", and you see the last message. It great, like that ou can see what's happen.

But on Enterprise version, when you start your session, you see the apps dash. And my guys never go on the "discuss" apps. I think because it is not super visible, that you have new message.

This Idea it is display dicuss/next activity directly on the screen without having to click on the small icon on the top screen.

Screenshot of the idea :
![image](https://user-images.githubusercontent.com/16716992/30239422-2ffd2e1a-952a-11e7-93bc-58bedb593640.png)

**Comment by Yenthe666** [comment]
Hi @fmdl,

I'm a bit confused. You're talking about having this on the community and wanting to have it on Enterprise. However, this feature is Enterprise and is not in the community plus your screenshot shows an enterprise version.
Do you mean you want this in community just like in enterprise or?

Regards,
Yenthe

**Comment by fmdl** [comment]
Hi @Yenthe666 ,

It is not an issue that this feature is not in community edition.

It is just an idea to display dicuss/next activity directly on the screen without having to click on the small icon on the top screen. To do a more interactive home page, with real time data.

Do you know what I mean ?

Regards

Nota : I have update the first comment.

**Comment by Yenthe666** [comment]
Hmm yes I understand. This is something for the R&D team and somebody has to decide if it's fine. I summon you @mart-e!

**Comment by fmdl** [comment]
Thank for your support. 

And maybe add the support of apps notification, like "Today you have 34 reception to do : link". "Today it is first day of holidays of your design manager". "Reminder : re call this vendor". "Top 10 des ventes d'hier sur votre site est : ..., vérifier vos stocks". "Alerte de qualité : cette pièce est HS".


The global idea is create a smart interface with apps, notification, ... like your iPhone (Remember that the next generation doesn't know Win98, but they was born with an iPad on hand). Your software is definitely turn on the futur, stay ahead with simplicity :-). 

Florent de Labarre

**Comment by mart-e** [comment]
Hello,

We already have some indications of the notifications when you are working. Isn't that enough?

![screenshot from 2017-09-12 15-14-23](https://user-images.githubusercontent.com/564822/30327654-24562440-97cd-11e7-9bee-8eca572e7a54.png)

**Comment by fmdl** [comment]
Honestly, it is not enough, I was ask to my guys and just one people saw that there are this icon with new message ... (each have hundred and hundred unread messages). 

If you have desactivate the forward message on your mail box, it is not friendly to see the new message. (Just an increment of the number of unread). 

Start Odoo will be the same
experience then unlock your iPhone, You see in first the last message. 

What do you think.

**Comment by mart-e** [comment]
Using the android application, you should/will (unsure if already released) get notifications for important messages.
You can also enable the browser notifications to make it easier to notice messages.

![screenshot from 2017-09-18 13-56-05](https://user-images.githubusercontent.com/564822/30540861-272d9d50-9c79-11e7-9281-3f9562e18b01.png)

I have transmitted your feedback to the UX team. At the moment we do not plan to add more than that.
I agree it may be a bit light but we have to find a fine balance between spamming of notifications and missing important ones.
We may change it in the future though.

**Comment by fmdl** [comment]
I have made the module :-)


![image](https://user-images.githubusercontent.com/16716992/33241264-5478af4a-d2c3-11e7-9fc5-86cd2814d5d4.png)
