### ISSUE TITLE
[POS] rounding difference between front and back

### ISSUE THREAD

**Issue by vuongtien2411** [odoo/odoo#19374]
Impacted versions:
9.0

Steps to reproduce:
1. Change oranges price to 3.80 / 1kg
2. Load POS 
3. Buy 0.575kg of oranges

Current behavior:
- Total is 2.19 in frontend.
- Total is 2.18 in backend

Expected behavior:
- Total is 2.19 in frontend.
- Total is 2.19 in backend

Video/Screenshot link (optional):
on POS screen
![POS here](https://preview.ibb.co/hGnqJk/Screenshot_from_2017_09_11_11_15_01.png)

Back end order
![backend order](https://preview.ibb.co/fqGpB5/Screenshot_from_2017_09_11_11_16_14.png)

**Comment by nilshamerlinck** [comment]
Looks like a similar issue to the one mentioned in https://github.com/odoo/odoo/pull/16119

In [`set_quantity()`](https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/js/models.js#L1148), we have:
```
> round_pr(0.575, .001)
0.5750000000000001
```

Then, when calculating the line's amount:
```
> round_pr(3.8 * 0.5750000000000001, .01)
2.19
```

While it should have been (as in the backend):
```
> round_pr(3.8 * 0.575, .01)
2.18
```

So I would spontaneously suggest to fix `get_quantity()` the same way `get_unit_price()` was already fixed:
```
    get_quantity: function(){
        var decimals = this.pos.dp['Product Unit of Measure'];
        return parseFloat(round_di(this.quantity || 0, decimals).toFixed(decimals));
    },
```

What do you think about it @jorenvo ?

**Comment by houssine78** [comment]
any news on this issue guys? @sle-odoo @mart-e 

thanks

**Comment by houssine78** [comment]
@tfr-odoo

**Comment by Yenthe666** [comment]
Hi @vuongtien2411,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
