### ISSUE TITLE
Purchase Order is editable and visible when invoice is validated

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#19387]
**Impacted versions:**
10
**Steps to reproduce:**
Create and validate invoice  from purchase order, field Add Purchase Order is editable but invoice is state Open
![image](https://user-images.githubusercontent.com/7775116/30285372-84782962-96e3-11e7-90d0-e99cb45b947b.png)

**Current behavior:**
Field Add purchase Order is  editable when invoice is validate
**Expected behavior:**
Field Add purchase Order is not editable when invoice is validate, view difinition is wrong on attrs, invoice state has not opcion _purchase_, invoice state are: draft, proforma, proforma2, open, paid) but no state proforma, this state is own purchase model.
Error on [this line](https://github.com/odoo/odoo/blob/10.0/addons/purchase/views/account_invoice_views.xml#L62)
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @celm1990,

Thanks a lot for your bug report.
This does indeed look like a correct bug. In V11 this is fixed but not in V10.
OPW 803068 - You'll hear back from Odoo soon.

Regards,
Yenthe

**Comment by celm1990** [comment]
Tanks,

On V11 and master is same error. 
For more information, this bug is introduced on  [this commit](https://github.com/odoo/odoo/commit/0c618d79ff9ecc8ffaea1404931a62695890d6d2)

**Comment by Yenthe666** [comment]
Hi @celm1990,

The bug has been fixed in https://github.com/odoo/odoo/commit/deb00a703b6c2f676a551bcff45ddbd3225f8fb8

Regards,
Yenthe

**Comment by celm1990** [comment]
@Yenthe666, tanks you, but this commit will ported to V11???, [on V11 is same error ](https://github.com/odoo/odoo/blob/11.0/addons/purchase/views/account_invoice_views.xml#L62)

**Comment by Yenthe666** [comment]
@celm1990 yes, usually the forward porting is done about once every 1-2 weeks so you should see it being fixed in a few weeks in V11 too.
