### ISSUE TITLE
[saas-14] base_address_extended: Fields to address extended not show in contacts

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#19388]
### Impacted versions:
saas-14

### Steps to reproduce:
1.- Create a new partner, with company_type = 'Company'
![new odoo](https://user-images.githubusercontent.com/7606656/30289260-3153ac6c-96f1-11e7-8f10-52a3ded3ec99.png)

2.- Create a contact to partner created in step 1, with type = 'Invoice'
Come to partner created in step 1, and press "Create" in contacts, 
![captura de pantalla 2017-09-11 a la s 13 02 40](https://user-images.githubusercontent.com/7606656/30289355-86437112-96f1-11e7-8837-21dd9c5b1db2.png)

### Current behavior:
En the contact with type = 'Invoice', I can´t select the 
`House Number `& `Door Number`

### Expected behavior:
I should be select the `House Number `& `Door Number` in each contact with address type = 'Invoice'

Video/Screenshot link (optional):

**Comment by luistorresm** [comment]
Hello @qdp-odoo 

FYI.

**Comment by luistorresm** [comment]
FYI @nhomar

**Comment by Yenthe666** [comment]
Hi  @luistorresm,

Thank you for your report.
@mart-e was this done with a specific reason or? Looks like a usability thing we have to check.

**Comment by nhomar** [comment]
Hello @Yenthe666 

Some points.

1. This issue is affecting not from an usuability PoV but technical one.
The Address management should be done consistently with the address when "Is company" is enabled.

**Comment by luistorresm** [comment]
This issue was fixed in 11.0
