### ISSUE TITLE
Upgrade module reload to wrong path.

### ISSUE THREAD

**Issue by sinfulcapacity** [odoo/odoo#19385]
Impacted versions:
10

Steps to reproduce:
Reload same page with same parameter.

Current behavior:
After module updated page reload without any parameter.

Expected behavior:
After module updated reload page with the current parameter.
Reload the current page and do not redirect page.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sinfulcapacity,

What exactly do you mean? Can you please add more information and how to reproduce this?

**Comment by Yenthe666** [comment]
Hi there,

Closing as there has been no feedback in almost a month.

Regards,
Yenthe
