### ISSUE TITLE
[10.0] Posbox image and connection issue

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#19381]
Hi,

Recently I have bought a Raspberry Pi 2 ( ref: https://www.raspberrypi.org/products/raspberry-pi-2-model-b/ ) and wished to build a PosBox by installing the image myself.

I downloaded the latest posbox_image from https://nightly.odoo.com/trunk/posbox/ which is the posbox_image_v16.zip and wrote the image to a 8GB mircoSD card using Win32DiskImager.

After I started up the raspberry with the memory card inserted, "POSBox Client display" has successfully showed up with tables containing the two IP addresses, i.e. 127.0.0.1 and 10.0.x.x 
Below the Ips table, there is a message, "Odoo version 11 or above is required". 

As I am using Odoo v10.0 yet it seems not to be compatible with the posbox_image. Hence I tried to use another microSD card and write an older version of the image, posbox_image_v15.zip to it. However, this time when starting up the raspberry pi, the "POSBox Client display" does not show up and asked about the login and password to the raspberry. I executed "ps aux | grep odoo" and odoo is actually running on the raspberry.

It will be glad if anyone could answer the following question
1. Which version of image should I use for Odoo v10?
2. According to the "Point of Sale Hardware Setup" from Odoo, ( https://www.odoo.com/documentation/user/9.0/point_of_sale/overview/setup.html ), it states

> Make sure that your LAN is set up with DHCP, and gives IP addresses in the range 192.168.0.X, 192.168.1.X, 10.0.0.X. If you cannot setup your LAN that way, you must manually set up your POSBox's IP address.

How could I manually set up the IP address of my POSBox?

**Comment by 3man5** [comment]
Hi TimLai125,
the version 16 is actually compatible with odoo v10 , but the feature you have just described is an upcoming feature in odoo 11 that will allow second screen to show customer pos cart.


Best Regards,
Ghalib

**Comment by MaitreDede** [comment]
Hi @3man5 
Is it possible to use the posbox primary screen as the pos interface ? And eventually a secondary screen as the customer pos cart ?

**Comment by 3man5** [comment]
Hi @MaitreDede,
With current Posbox setting unfortunatly its not possible , but if you are familier with linux u may install a GUi interface and install normal browser then you may us it as An interface.

**Comment by MaitreDede** [comment]
Thanks @3man5, trying to achieve this on my spare time :)

**Comment by TimLai125** [comment]
Hi @3man5 

Thanks for the reply and the information.
I changed to v15 image and turnout, I was accessing the posbox via "https" instead of "http".
Now the issue is solved.
As odoo 11 is coming, I will try to use the v16 pos_image next time.

**Comment by alexis-via** [comment]
Le 25/09/17 à 00:59, Damien DALY a écrit :
>
> Hi @3man5 <https://github.com/3man5>
> Is it possible to use the posbox primary screen as the pos interface ? 
> And eventually a secondary screen as the customer pos cart ?
>

This is a new feature of Odoo v11 (which will probably be released next 
week during the event Odoo Experience 2017), cf 
https://github.com/odoo/odoo/commit/1600216c1da0fcbb7c91819b103242fa69337c67

-- 
Alexis de Lattre
