### ISSUE TITLE
Not editable flag doesn't work inside snippets website

### ISSUE THREAD

**Issue by GuavanaUX** [odoo/odoo#19389]
Impacted versions: 
10.0

Steps to reproduce: 
Create a snippet inside website and add the next code lines (mix with html, if you want):
```
<t t-if="editable">OOOOOOOOOOOOOOOO</t>
<t t-if="not editable">ZZZZZZZZZZZZZZZZZZZZ</t>
```

Always print OOOOOOOOOOOOOOOO (even when the session was closed).

Current behavior:
Not editable flag doesn't works inside snippets website. If the template inherit from website.layout works but the snippets not (website.snippets).

Expected behavior:
Merely, that works. When I write not editable flag only print when the session is closed and viceversa.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be website related 😉

**Comment by JKE-be** [comment]
Expected behavior.
The snippet is rendered before to be be dropped.

So before that the snippet is dropped, there is already only the OOOO.

You need to do it in javascript...

**Comment by GuavanaUX** [comment]
Thanks for answer. But, how know if the website is in editable mode without use this flag?
I need to know how do that in python to translate to javascript.
