### ISSUE TITLE
[master] New RecordCache issue with inspect

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19396]
Impacted versions: master
@rco-odoo 

Steps to reproduce:
Open an Odoo shell.

```python

In [1]: import inspect

In [2]: bom = self.env['mrp.bom']

In [3]: inspect.getmembers(bom, predicate=inspect.ismethod)
```

(Note the model doesn't matter)
Current behavior:
```python
<ipython-input-3-e3030d293ef5> in <module>()
----> 1 inspect.getmembers(bom, predicate=inspect.ismethod)

/usr/lib/python2.7/inspect.pyc in getmembers(object, predicate)
    251     for key in dir(object):
    252         try:
--> 253             value = getattr(object, key)
    254         except AttributeError:
    255             continue

/home/graemeg/PycharmProjects/odoo10-c/odoo/odoo/tools/func.pyc in __get__(self, obj, cls)
     21         if obj is None:
     22             return self
---> 23         value = self.fget(obj)
     24         setattr(obj, self.fget.__name__, value)
     25         return value

/home/graemeg/PycharmProjects/odoo10-c/odoo/odoo/models.pyc in _cache(self)
   4671     def _cache(self):
   4672         """ Return the cache of ``self``, mapping field names to values. """
-> 4673         return RecordCache(self)
   4674 
   4675     @api.model

/home/graemeg/PycharmProjects/odoo10-c/odoo/odoo/models.pyc in __init__(self, record)
   5016     """ A mapping from field names to values, to read and update the cache of a record. """
   5017     def __init__(self, record):
-> 5018         assert len(record) == 1, "Unexpected RecordCache(%s)" % record
   5019         self._record = record
   5020 

AssertionError: Unexpected RecordCache(mrp.bom())

```

Expected behavior:
No error, should be able to inspect a Model without failure.
Video/Screenshot link (optional):

\cc @guewen FYI

**Comment by gdgellatly** [comment]
FYI _cache is the member that inspect initially fails on.

**Comment by Yenthe666** [comment]
@xmo-odoo framework related.

**Comment by gdgellatly** [comment]
Only reason I pinged @rco-odoo is it was working just fine for years until #19304

**Comment by guewen** [comment]
I could trace down this one. `inspect.getmembers()` will use `getattr` on each attribute to check if it's a method, thus it will also evaluate the `property` and `lazy_property`. This one:

https://github.com/odoo/odoo/blob/42264d8dcb7f8d0795c84718d1fc9a5fd1aefd32/odoo/models.py#L4671-L4674

Will try to create an instance of `RecordCache` with a "empty" `self`, which is not supported by the `RecordCache` implementation. Basically I expect you can reproduce it with:

```python
env['mrp.bom']._cache
```

I lazily worked around that when porting `queue_job` to 11.0 with a custom reimplementation of `inspect.getmembers()` that skips the `_cache` property. :sweat:

```python
        for attr_name in dir(self):
            # _cache on models is a lazy_property which raises an
            # AssertionError when called on a empty model, just skip it.
            if attr_name == '_cache':
                continue
            try:
                attr = getattr(self, attr_name)
            except AttributeError:
                continue
            if inspect.ismethod(attr) and getattr(attr, 'delayable', None):
                job_methods.add(attr)
```

https://github.com/OCA/queue/blob/6a7b0548624ce5acbc2818089d0e7924819bcc99/queue_job/models/base.py#L20-L30

**Comment by pedrobaeza** [comment]
I think this is not relevant anymore, isn't it?

**Comment by Yenthe666** [comment]
I'm pretty sure this changed with the V13 ORM rewrite?

**Comment by pedrobaeza** [comment]
Yes, let's close it for now and if it's not correct, we reopen or reissue.
