### ISSUE TITLE
Enterprise Settings - Master

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19394]
Impacted versions: master
I'd be astonished if someone doesn't already know this, but then again the code got merged that causes this some time ago.  The new settings screen has some issues.

Steps to reproduce:
Go to Enterprise -> Settings -> General Settings
Click to change the document template
Click on a template

Current behavior:
Chaos
The screen closes
The settings sidebar disappears
And you get presented with a single screen of all of the settings.

Expected behavior:
Something else, definitely not that.

Tested on runbot.
Just for giggles, find it again, open it and click preview on one of the choices.

Video/Screenshot link (optional):

**Comment by fgi-odoo** [comment]
Thanks for reporting this. We are in the process of fixing the remaining issues of the new settings design. This will be corrected by the launch of Odoo 11.

**Comment by gdgellatly** [comment]
assume its fixed
