### ISSUE TITLE
[BUG] plan and check both generate competing stock.move.lots

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#19426]
Impacted versions:
current stable

##### Steps to reproduce:
1. Add `move_lot_ids` tree view on both, the work-order view and the `mrp.view_stock_move_lots` to better see what happens.
2. Prepare Products as described in https://github.com/odoo/odoo/issues/19422 (but set existing stock to some high value)
3. Copy en existing MO like the one created in https://github.com/odoo/odoo/issues/19422
4. PLAN and CHECK AVAILABILITY (order is not relevant)

##### Current behavior:
1. PLAN does create `stock.move.lots` on the work order, see `_generate_lot_ids`
2. CHECK AVAILABLILITY does create a second `stock.move.lots`, see `create_lots`

Both are competing, and when both used, sum up to a combined consumption, while both have the implicit notion of a SUGGESTION to the respective user, which is a different one.
To verify: Repeat steps above and use both suggestions at some value of your choice and post inventory at will on the MO.

Therefore two users obtain the (independent) suggestion to consume lots' quantity.
USER A (Production Planning), if clicking on the lines next to the consumption moves, it will be shown to him a suggestion of consuming certain quantities based on the availability (usually FIFO) of certain lots in the source location.
USER B (Operator), will be shown the final consumption of the current production, irrespective of the availability by the way, and will be able to choose (hastely) among every possible lot available for this product.

NOTE (tricky!): `active_move_lot_ids` and `move_lot_ids` are referencing the same inverse field, but have individual filters so that enabling `move_lot_ids` tree views as suggested in step 1 helps understanding what's going on.

##### Expected behavior:
If USER B (Operator) obtains the suggestion to consume a certain lot,
USER A (Production Planning) should work and see the very same suggestion, at the end, he is controlling the USER B, and should have the ability to correct him in the execution of his suggestion.

Additionally, USER B should only get lots suggested which have been actually reserved by the raw_materials move. It is very uncommon that in a WAREHOUSE A a material is reserved for PRODUCTION B and PRODUCTION PLANNING is aware and planning with this reserved material, but then, as if at the very last moment, OPERATOR jumps up runs to the WAREHOUSE A and actually uses a different material without the need for proper handling (or at least awareness) of PRODUCTION PLANNING. It is usually even a forbidden operation to consume a lot which is not actually in stock. Quod erat demonstrandum.

Video/Screenshot link (optional):

**Comment by blaggacao** [comment]
## Discussion

It seems to me that the entity relationship model of `stock.move.lots` has entered prematurely the release of the mrp. See for example hilarious fixes such as: 471115b06ad4

That being said, the problem is that the typical use case where a somewhat "Production Planning" department is planning and controlling "Operations", and there fore need a unified way. Possibly the motivation to separate is based on the double use of the mrp model for simple (without work order) productions and more complex (with work order) productions. IN the first case, this individual suggestion does indeed make sense.

The core problem is that `_generate_lot_ids` is called from the mrp planning action, but originally probably was crafted to serve the use case, where a work order is executing a bigger amount than planned and additional lots need hastely be added.

Instead, if PLAN and CHECK AVAILABILITY should not be made sequential (eg planning only possible when reserved), which wouldn't probably be a very good idea, then we need at least awareness of `stock.move.lots` creation for each other in such a way that the work order sees his' but the production as itself sees all. It is still possible to separate them via the actual or siglthly modified `done_wo` boolean mechanism. In a way that USER A is always on the same page as his operators.

Limiting the operators choice to what is reserved, is in a unified view, rather simple, as the move would create or complement the respective information on the same page. Anyhow, starting a production, without reserved material is rather something that usually cannot happen in practice. So at the time the USER B interacts with Odoo, available lot information has long been made available.

As to this limitation, one could argue that actually USER B should have certain liberties to change the lot, for example in the case that he is working on a workstation which has its individual freehand location configured. But in any case, this should probably be limited to this condition (location per workcenter) and anyhow it's not supported by odoo by default. So limiting available lots to what has been reserved, once reserved seems a reasonable decision to make.

**Comment by blaggacao** [comment]
**Ticket Nr: 771603**

**Comment by blaggacao** [comment]
Interestingly the actual behaviour completely invalidates this filter: https://github.com/odoo/odoo/blob/58c928a73256678bd1041076455bdf3e90a36d69/addons/mrp/models/stock_move.py#L156
Which is in part the culprit line of https://github.com/odoo/odoo/issues/19426

**Comment by nim-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
It was meant like that.  The worker's are no suggestions, because we thought it to be too complicated for him to be faced with the reservation itself.  That is why they exist twice.

**Comment by blaggacao** [comment]
@jco-odoo Thank you, I pretty much was suspecting that this is somewhat intended behaviour. I'd like to propose you a PR (to master) based on my abstractable project experience where PRODUCTION PLANING should at least see the current consumption by the work orders.

Then, it would be visually more transparent to PRODUCTION PLANNING a) what's going on where and b) it would be visually clear, that what they can edit are corrective records.

Case in upstream: when using lots
Case in customized: when workers [or: Workcenters!] do indeed liquidate ACTUAL consumption.

I'd not suggest a separate module, but a configuration option or would you upfront prefer a separate module? I don't expect the changes to be huge, and I'll need to backport them for current projects, but would like to do it in the most commonly agreed upon manner right from the beginning.

Slightly Off-Topic:

I'd also like to include a definition on where the Side-Product is born (in which work order), because Side Product is an excellent mechanism to control waste and indirectly (by resting waste + produced from input) robbery. However, waste of different types is produced at different workcenters and the control MIGHT be within the workcenter itself, so being able to produce Side Products at the workcenter is a greate gain.
