### ISSUE TITLE
[BUG] mrp: on lot agotation, existing assigned lots to production don't get purged

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#19422]
Impacted versions:
current stable

Steps to reproduce:
1. Create consumed Product CONSUMED-PRODUCT A
2. Create produced Product PRODUCED-PRODUCT B
2. Enable Lots on CONSUMED-PRODUCT A
3. Create a BOM for PRODUCED-PRODUCT B which consumes 1000 of CONSUMED-PRODUCT A
3a. Add a one step routing and configure 
4. Make CONSUMED-PRODUCT A partially available, in other words do an operation of your choice, so that 500 units of CONSUMED-PRODUCT A will be available within "LOT 0001".
5. Plan the production of 1 unit of PRODUCED-PRODUCT B
6. **Make eg. an inventory adjustment so that _NO MORE_ units of CONSUMED-PRODUCT A will be available under "LOT 0001"**
7. Make CONSUMED-PRODUCT A entirely available in another "LOT 0002", in other words do an operation of your choice, so that 1000 units of CONSUMED-PRODUCT A will be available within "LOT 0002".
8. Go to the production and Recheck Availability.
9. Assign the lots and quantity to consume of CONSUMED-PRODUCT A.

Current behavior:
(If the steps above are right)
1. You will find a default of 500 units of "LOT 0001" + 1000 units "LOT 0002", 1500 units in total.
2. If you just follow the default, (to be verified), a negative quant is created although you didn't force availability anywhere throughout the process.

Expected behavior:
1. The defaults should be updated with the current available quantity, and should be removed if the lot is not available any more.
2. No negative quants should be created through production without the special powers of forcing availability. (to be verified)

Video/Screenshot link (optional):

**Comment by blaggacao** [comment]
just confirmed in http://263687-10-0-d51802.runbot13.odoo.com

**Comment by blaggacao** [comment]
**Ticket Nr: 771584**

**Comment by blaggacao** [comment]
### Discussion

The relevant check, which has no side effect, in the case of UPDATING quantities is in the `create_lots` method:
```
    @api.multi
    def create_lots(self):
        lots = self.env['stock.move.lots']
        for move in self:
            unlink_move_lots = move.move_lot_ids.filtered(lambda x : (x.quantity_done == 0) and not x.workorder_id)
            unlink_move_lots.sudo().unlink()
```

The filter `lambda x : (x.quantity_done == 0) and not x.workorder_id` is always true in our use case, as per planning the production, see: `_generate_lot_ids` on the workoder model, which is called on WO creation and writes the relevant field on `stock.move.lots`: `'workorder_id': self.id`.

The goal of the filter might have been to somehow assure, that once something is handed off to an operator (work order), he cannot be overruled by some random rechecking clicks on the Production Preparation floor.

However, physical availability is represented by a quant, so if there is nothing left of the lot (as per line 7. of the above case), that means it's also impossible that the operator should have it, as it is not there.

Also, the `quantity_done` filter is set by default (eg `'quantity_done': min(1.0, qty_todo),` in `_onchange_qty_producing`) and represents a default, that is a FUTURE value (which is validated on a stage change. This is also potentially conflicting with the ACTUAL representation that quants infer.

### Solution Path

Quants should be the uncontested source of truth throughout the whole code. No rivaling information should exist once a quant has been updated. And worse, no rivalring information should ever be the source for further construction (see current behavior 2.) This implies relational fields or mechanisms which assure proper updating. Especially in the production module we can see some violations of this concept.

This case reveals one of such violations.

**Comment by blaggacao** [comment]
Suggestion: `not bool(x.lot_id) or (x.quantity_done == 0) and not x.workorder_id`
Would that have any unexpected side effects?

**Comment by blaggacao** [comment]
Eventually changeing the offending line to:
`unlink_move_lots = move.move_lot_ids.filtered(lambda x : (x.quantity_done == 0) and not x.done_wo)`
would just be a maximum in compatibility and be stable worthy...

When shown on any work order (usually still without any lot assigned), don't purge. When not currently on any work order, then go ahead and purge it if it has no quantities assigned yet.

Possibly this was even the original intention of this line which then has lost meaning as code has changed.

**Comment by nim-odoo** [comment]
@jco-odoo

**Comment by jco-odoo** [comment]
In theory, lots should be scanned, as you need them to be chosen explicitly
to be sure to have the correct traceability.  In practice, in v11, we will
allow to correct these invalid actions afterwards.  You could create a
calculated field that calculates the correct lots and add it as domain (id,
in, ) of the lot fields.

**Comment by blaggacao** [comment]
@jco-odoo Looking forward to v11, then. As far as I know, the (id, in, calculated-2m-field) has be recently added in master, I'd have to see how to backport this behaviour to v10, then...

Do you see a way to merge best of both worlds: Limiting suggestion to what is reserved, but giving scan force-overriding powers? We should really improve usability for the smaller shop that want's to automate a little with just a few tablets.

**Comment by jco-odoo** [comment]
@blaggacao I think you are right about that 'and not x.workorder_id' was intended to be 'and done_wo'.  I will put this in a branch and see if we can merge it.

**Comment by blaggacao** [comment]
@jco-odoo I'm glad my feedback is/was useful! Thank you sincerely for taking the time looking at it!

**Comment by jco-odoo** [comment]
In commit 365362a4a0d86701d6f991b3917528d02923b22d
