### ISSUE TITLE
Bug: Database creation error - still there after resubmit until result

### ISSUE THREAD

**Issue by pashute** [odoo/odoo#19423]
Impacted versions: 10

Steps to reproduce: Create new database with wrong admin credentials

Current behavior:  Shows error on top of page without time. If input-values changed and resubmitted, error message is still there till shown again

Expected behavior:  Either the "Database creation error" should dissapear immediately when I resubmit, or add a timestamp to the "Database creation error..." message, so that I know this is the result of my former submittal and not this one. 

Code is in: addons/web/controllers/main.py  
Line 600 and something....

**Comment by Yenthe666** [comment]
Hi @pashute,

Thank you for your report.
I've seen this one before, this is simply built this way at the moment.
@mart-e I'd love to improve this so the previous message is indeed removed or shows a timestamp though. Let us label it wishlist for now.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hi there!

What do you mean if resubmited the message stays?

If the password is correct, the database is created and you are redirected to the new database.
If you close the popup with the database creation, yes you still see the previous error message but it is normal as you haven't done any action yet.

I am not in favour of adding a timestamp. This is too technical. You never see a timestamp when you write a wrong password in a form.

**Comment by pashute** [comment]
If the password was incorrect, and I fixed it and resubmitted (meaning
submitted, this time with the correct credentials) I see the error message
AFTER I submitted although this time I may have entered the correct pw. IT
IS NOT NORMAL. It is confusing because I now think I received the error
message on MY SECOND submit.

Since creating the database may take some time it is quite nerve-racking,
especially if you are not sure what the pw you are writing should be. The
odoo.conf uses one name set, the UI another  (admin password, database
password...). The documentation is not clear which roles will be used when
creating and using these two passwords, when and how each was created and
what will be done with them. And you have this unchanging error message
stuck up on screen.

*As far as I understand: *
* *Master Password *in the UI is the Admin Password of the Postgres SQL.
This is the password of the role: *pgadmin*,
and is listed in *odoo.conf *as *ADMIN PASSWORD*.  (default, if I'm not
mistaken: openpg)
*  the "*odoo*" role (hardcoded to use that name for the role) will be used
for creating the database. You should have created that role in
PostgresSql before hand.
* the database name in the UI is the database-name of the db now to be
created.
* Choose Password in the UI, is the *database* *password *in the odoo.conf
 , and the two should be the same.

**Comment by mart-e** [comment]
Could you give a video/screenshot? I am not sure we are talking about the same screen

**Comment by pashute** [comment]
http://lmgtfy.com/?q=odoo+create+database

:-)

**Comment by mart-e** [comment]
I am trying to help you here, but if you do not wish to give me the needed information too bad...

**Comment by pashute** [comment]
I understand, and thank you for your time!!
I'm sorry for the misunderstanding. Totally in humor, did not intend to be
anything but that.
This is not a problem of "mine" (since I'm not creating a database right
now) but IMHO a problem of ODOO.

The screen is this one: (I don't have a clean database)
https://cdn.techjourney.net/2015/01/odoo-db.png

With the ODOO 10 looks.

If you put the wrong pw in, you'll get an error.
If you then put the correct pw in, the error stays on the screen until
fixed, or until another error (but you don't know that, because the fomer
error message is the same...)

**Comment by mart-e** [comment]
No offence taken but given the screenshot ensure we are talking about the same error message.
Here you give me a 8.0 screen without the error message so I will try to guess.

When you put a wrong password, you get this error in v10

![screenshot from 2017-09-18 16-43-35](https://user-images.githubusercontent.com/564822/30547776-8e716b9c-9c90-11e7-96b0-0d6590cb0fef.png)

Now, you are telling me (this is the part I am not getting), that you go to this screen again, and set the correct password

![screenshot from 2017-09-18 16-49-08](https://user-images.githubusercontent.com/564822/30548116-9121ef50-9c91-11e7-82b2-84daa622ea6f.png)

but if I press "Continue", the database is created and I am redirected to the new database.
I no longer see the error message.

**Comment by pashute** [comment]
Hi, OK I'm sorry I cannot supply a screenshot.  And again, thank you for
your time.
Please let me stress that this is not a problem that I have, my database is
now running ok.
But rather, this is a problem I think ODOO has, and I'm reporting it for
the benefit of ODOO.

Here's what I did and what I got:
1. I ran it from the code (on windows running from Eclipse and with the
Enterprise --addons)
    It runs OK and brings up the screen for creating a new database. (Your
second screenshot)

2. I never saw the first screenshot you are showing, although the red
message is similar... let me explain:

3. Your second screenshot is how I start off creating a database. I'll call
this screen CreateDbForm:

3.1 I put in the wrong MASTER PASSWD on the CreateDbForm, or the postgres
service is not running
3.2 I put in the rest of the credentials and fields including country and
press Continue
3.3 The CreateDbForm stays unchanged and the browser shows a "churning"
animation while the database creation is being attempted.

4. The database creation attempt fails - behind the scenes.
4.1  Except for a red error message on the top of the form, CreateDbForm
stays unchanged (or maybe is reset without any data, I don't remember). In
any case the CreateDbForm itself is retained on screen.
4.2 The wording of the red error message was given in my ticket. If I'm not
mistaken, it's the same as you showed:
       Orange square and in it: Database creation error: Access denied.

5. If the user STAYS ON THE SCREEN, without "going to the screen again" and
enters a new master password, (and if the other fields were cleared, enters
the other fields) then:
5.1 While entering the new data, the error message is still there.
5.2 After pressing CONTINUE, the error message is still there. The browser
is now showing a churning animation.
5.3 After a long and nerve-racking wait: one of two things can happen:

6a. If all's well, the form is replaced with the ODOO main screen which
begins initializing. Yay!  Success.
6b. If I still have a mistake, the churning stops and I'm back on 4.
      i.e. I'm on CreateDbForm with a red error message, which is the same
as I had since the former iteration.

7. I then start wondering to myself:
a. checking what "Master Password" means. is it the postgres admin password?
b. I check if the PgAdmin role exists. If I have the password set correctly?
c. I look in the odoo.conf to see what I listed as "admin password". Is it
the same? Is that important? Is it what is causing the error?
d. I wonder if perhaps the "Password" at the bottom of the CreateDbForm is
the cause of the problem, and try setting it otherwise. (From the user
questions on the web you can see that this is not only unclear to me)

8. Obviously at some stage I get things right. (I've done this on several
computers, my own and my partner's, several times when we restarted the
system, and still not sure what I've done right!)

9. So the problem starts at 5.1
    Continues to 5.2  and during the long wait until 5.3
    Continues to 6b
    Continues till the main ODOO screen is shown after I (now finally,
obviously)  got it right.

**Comment by mart-e** [comment]
> 4. The database creation attempt fails - behind the scenes.
>  4.1 Except for a red error message on the top of the form, CreateDbForm stays unchanged (or maybe is reset without any data, I don't remember). In any case the CreateDbForm itself is retained on screen.
> 4.2 The wording of the red error message was given in my ticket. If I'm not mistaken, it's the same as you showed:
>  Orange square and in it: Database creation error: Access denied. 
> 

Orange message? Not red? This is strange because, the error message is created here

https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/controllers/main.py#L659-L661

and rendered in alert-danger style (red) here, not in the popup (what you call CreateDbForm).

https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129

Is your code up to date? Only standard?
Do you have the same if you try to create a new database on http://runbot.odoo.com (where you do not have the master password so will get the error ;-) ).

The master password is the `admin_password` set in your configuration file.

**Comment by pashute** [comment]
OK, not orange. A shade of red (pinkish orange, depending what time of the
day and lighting I'm subjectively looking at it...)
Obviously not the same red as the text...

alert-danger is red text on pinkish text:


72
<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/web/static/lib/bootstrap/less/alerts.less#L72>
.alert-danger { .alert-variant(@alert-danger-bg; @alert-danger-border;
@alert-danger-text);
73
<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/web/static/lib/bootstrap/less/alerts.less#L73>
}
alert-danger-bg is set to state-danger-bg, which in turn is defined:

490
<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/theme_bootswatch/static/src/less/spacelab/variables.less#L490>
@state-danger-text: #b94a48;
491
<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/theme_bootswatch/static/src/less/spacelab/variables.less#L491>
@state-danger-bg: #f2dede;
492
<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/theme_bootswatch/static/src/less/spacelab/variables.less#L492>
@state-danger-border: darken(spin(@state-danger-bg, -10), 3%);

​The color #b94a48; is dark orengish, don't you agree
<http://www.colorhexa.com/b94a48>?
The color #f2dede; is definitely with a tinge of orange, no? ​
​ Here's a drawing I made with sketchpad. The background is #f2dede;

Seriously though, the code you showed me is a div on the top of the
CreateDbForm form.
​
​
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>
https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d7
1246734a2b/addons/web/views/database_manager.html#L113-L129
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>

<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>

The <body> tag (on line 113) is where actual html page starts, and the form
above will be inserted there via the macro on lines 55 to 59... (AFAICS
there is no <body> before and it is not conditionally created here)
​
​
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>
https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d7
1246734a2b/addons/web/views/database_manager.html#L55-L5
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>
9

<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>



​

**Comment by mart-e** [comment]
Please use the github interface if you are trying to send media or attachment, it does not work by email

**Comment by pashute** [comment]
I was being funny: Here it is: https://photos.app.goo.gl/CkhV3a7tD0g8W9Sy2

**Comment by pashute** [comment]
OK, not orange. A shade of red (pinkish orange, depending what time of the day and lighting I'm subjectively looking at it...) Obviously not the same red as the text...

[alert-danger is defined here](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/web/static/lib/bootstrap/less/alerts.less#L72-L74) and is red text on pinkish text:

    72 .alert-danger { 
    73     .alert-variant(@alert-danger-bg; @alert-danger-border; @alert-danger-text);
    74 }

alert-danger-bg is set to state-danger-bg, which in turn is defined: 

<https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/theme_bootswatch/static/src/less/spacelab/variables.less#L490-L494>

​The color #b94a48; is dark orengish, [don't you agree](http://www.colorhexa.com/b94a48)?    
The color #f2dede; is definitely with a tinge of orange, no? ​    
​ Here's [a drawing I made with sketchpad](https://photos.google.com/photo/AF1QipPdopHhBw5ALR0UW0vlXgI-zVaZOyh4XZus5YnF). - Just being funny. The background of the orange is #f2dede;

Seriously though, the code you showed me:
 
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L127-L129>

 is a div on the top of the CreateDbForm form.
​​
Notice the code in [lines 113 to 129]<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L113-L129>

The <body> tag (on line 113) is where actual html page starts, and the form above will be inserted there via the macro on lines 55 to 59... (AFAICS there is no <body> before and it is not conditionally created here)
​
And here's the macro: 
<https://github.com/odoo/odoo/blob/875dd9221f80ea1b60cd9ee8a005d71246734a2b/addons/web/views/database_manager.html#L55-L59>
​
