### ISSUE TITLE
[V8] Loading States and Provinces

### ISSUE THREAD

**Issue by palfrader** [odoo/odoo#1946]
Checkout can't load the states/pronvinces if the country is loades:
![italia_01](https://cloud.githubusercontent.com/assets/8029350/4021199/56eec0b2-2ae6-11e4-834b-316a1aebc24d.gif)

If the country is not loaded/selected again it works:
![italia_02](https://cloud.githubusercontent.com/assets/8029350/4021200/5b207964-2ae6-11e4-9271-c83d0a3aa45c.gif)

**Comment by Yenthe666** [comment]
Hi @palfrader,

Thank you for your report.
I'm not sure what you're trying to explain / show though. If I look at the country field ('Paese') I can see it filled in on both of your screenshots, so what is the problem exactly?
Can you please give more feedback or make a recording?

Thanks,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this as there has been no response on this issue.
Don't hesitate to add more info or reopen if you still face this issue.

Regards,
Yenthe
