### ISSUE TITLE
Barcode Nomenclature pattern for weighted barcode doesn't integrate the lot no. 

### ISSUE THREAD

**Issue by kunalgoel1** [odoo/odoo#19461]
**@Yenthe666 @jorenvo @jco-odoo @aab-odoo @mart-e @nim-odoo** 

**Impacted versions:**
V10

**Steps to reproduce:**
Create a product that can be tacked by lots.

**Current behavior:**
When we scan a weighted barcode, it does update the Product and its quantity of the scanned item on the POS Screen, but doesn't have a provision for updating the LOT no for that item since no such pattern type is defined in current Barcode Nomenclature Settings.

**Expected behavior:**
Would like to have a new barcode pattern which can integrate Product Barcode along with Lot Number and Quantity.
_Eg.: 25.....{NNDDD}&LLLLLLLLLL  
So for Item Barcode: 2112345  quantity: 51.250 and Lot no: 0000000001
Barcode will be 251234551250&0000000001_

The above example is just for illustration purpose. You may define the pattern as your team seems would best fit.

**Comment by kunalgoel1** [comment]
@jco-odoo

**Comment by sle-odoo** [comment]
Hi,
This is a limitation of the current barcode nomenclature implementation. It may be improved later on.

Regards
