### ISSUE TITLE
sitemap and og:title generated with wrong domain name

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#19499]
Impacted versions: 10 and others

Steps to reproduce: for various reasons you may need to put some domain names in /etc/hosts file. Try to put something like[your IP] [special.domain name] You may need to put it also in DNS record.

Current behavior: sitemap generated with wrong domain name because request.httprequest.url_root get wrong domain name from system. System respond with what you have put in /etc/hosts (special.domain name).

Expected behavior: sitemap generated with web.base.url instead of request.httprequest.url_root

This happens because of request.httprequest.url_root from werkzeug. It seems to me that it read domain name from system. System read domain name from DNS, hostname and /etc/hosts. /etc/hosts file takes precedence.
Actually there is 3 problems in one :

- domain name in sitemap is not what is expected (web.base.url)
- nothing tells that request.httprequest.url_root is different than web.base.url and that sitemap.xml may contains wrong domain name (if the Odoo admin doesn't care about reading sitemap.xml...).
- if the Odoo admin is not the sysadmin, he can't guess where the problem comes from.

If needed I can give access to my impacted server.

**Comment by ddfs** [comment]
this issue has been there long time. robots.txt is affected too. http https no difference. https is ignored too.

**Comment by zeroheure** [comment]
On my system https is not ignored, all urls in sitemap start with https.

**Comment by zeroheure** [comment]
I just found that og:title (SEO tag for social networks) is affected too. Furthermore, while I removed every mention of my special.domain_name (in /etc/host and web.base.url and company sitename), it's not updated.

**Comment by JKE-be** [comment]
It will be wrong to use web.base.url to generate a sitemap.

Works as expected.

I add mydomain.ext in /etc/host
and the sitemap is correct:
![image](https://user-images.githubusercontent.com/4848797/33373511-89f1d0de-d502-11e7-8c60-f70d37bfd21e.png)
