### ISSUE TITLE
Comming soon url configurable.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#1949]
Hello.

It should be cool to have a "configurable" "off-line mode" with some cool comming soon or under construction template.

Example on drupal.

https://drupaltraining.stanford.edu/node/63

**Comment by tvibliani** [comment]
It should be nice to have possibility to take down a website for editing and display to visitors some "Under Construction" page, while admin quietly edits a site using the Odoo Website Builder.

**Comment by jholze** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @nhomar,

Thanks for your suggestion. As stated by @jholze there is a current live version of the page and the ability to update / change pages.
@sle-odoo can this one be closed?

Regards,
Yenthe
