### ISSUE TITLE
[10.0] all the pdf report with negatif number, the negatif sign "-" rendered into 2squares 

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#19520]
Impacted versions: 10. Community

Steps to reproduce:
Clean Instsall Odoo 10 Community in CentOS 7.3, postgresql9.6, python 2.7.9, with virtual envirionment  
All dependency is satisfied
Install wkhtmltopdf (i have try version 0.12.1, 0.12.2, 0.12.2.1, 0.12.4) dependency satisfied  
Make an entry in any form to get a printable pdf report such as in balance sheet that should show a negatif numbers (such as cash balance or other balance to be negatif)  
Also can make a purchase order with price set to negatif so the total negatif

print the report (pdf), save or see directly on the browser.

Current behavior:
The negatif sign "-"  of any negatif numbers in the report is not rendered correctly, but rendered into a small square or 2squares/rectangles in adjacent

Expected behavior:
The negatif  sign should be rendered correctly   as "-" instead of squares

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7310629/30528549-51c3866c-9c5e-11e7-9b4b-9404a63f732e.png)

Please help solving the issue.

**Comment by Yenthe666** [comment]
@sle-odoo I know you've answered something similar to this before. Could you have a look please?

**Comment by sle-odoo** [comment]
Hi,
Did you make any customisations to these reports?

Regards

**Comment by bunhin** [comment]
Hi thank you for responses,

Standard odoo report no report customization

Thanks,

**Comment by bunhin** [comment]
@sle-odoo would you please share how to solve it, or what that could be wrong ? Thank you

**Comment by bunhin** [comment]
Self closed, After i try installing so many fonts including lieberation font package, urw-fonts package, etc,  The dejavu-sans-commons is working for me.  I believe the dejavu font should become one of requirements to provide a fall back in case other fonts can't render correctly.
