### ISSUE TITLE
[BUG] MRP: Producing twice the products with half the raw materials

### ISSUE THREAD

**Issue by dduarte-odoogap** [odoo/odoo#19527]
Impacted versions:10.0

Steps to reproduce: Create a BOM type kit and add a route, then create another that includes the the last type and also add a route. 

Current behavior: Create a MO for this last one and run the steps,it will produce 2 finished products consuming only half the raw materials
Expected behavior: Create a MO for this last one and run the steps,it should produce 1 finished product.

Video/Screenshot link (optional):
https://youtu.be/FiBr4g4V14U

**Comment by dduarte-odoogap** [comment]
@Yenthe666 @jco-odoo : just found this problem also exists in EE 10.0 and 11.0, this only occurs when we have a kit BoM with a routing, inside another BoM. It will produce several finished products.

https://youtu.be/lBLCr-CYHSY

**Comment by jco-odoo** [comment]
Is it because the first workorder does not have a next_workorder_id as it was hierarchical.  (so it would add 1 in the first workorder and a second in the second?)

**Comment by lap-odoo** [comment]
@dduarte-odoogap Hello, thanks for reporting this. It's a bug and I've created a ticket (817398). Our support will take care of it. I've added you as follower on the ticket. I'm closing the github issue, you'll be updated from the ticket. Thanks

**Comment by cpintofonseca** [comment]
@lap-odoo @jco-odoo thanks, can this be merged on 10.0 as well?
