### ISSUE TITLE
Master - logos broken on reports

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19540]
Impacted versions: Master

Steps to reproduce:
Go to runbot
Print an invoice

Current behavior:
No logo - see little box in screenshot

Expected behavior:
Logo
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/30568348-c3e08414-9d28-11e7-9fd5-9bbcd85f9902.png)

There seems to be some other issues.  Now the only change I made on my demo system to realize this issue that I know of was to spin up on Python 3.5, however I don't what runbot is using.

EDIT: Their to there, can't have complaints about broken english

**Comment by gdgellatly** [comment]
As follow up
- changing header to 

```xml
t-att-src="'/logo?company=%d' % company.id"
```

Worked nicely for me.  Tested in multicompany enterprise master

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thanks for your report - I've just tested this and I can confirm it is broken.
Do you mean that you've changed the default XML template for the header to that code? Feel free to make a PR! 😉 

Regards,
Yenthe

**Comment by gdgellatly** [comment]
@Yenthe666  well I could, but while it fixes the issue of the logo not displaying, it doesn't fix the underlying issue of base64 images not displaying, which is really what needs fixing.  

On the one hand I think the web route I used is an elegant way to do it (certainly makes debugging html 1000 lines shorter) to get company logo, there's still a lot of scenarios that will need base64 I think.

**Comment by Yenthe666** [comment]
Agreed - I'm absolutely positive the base64 scenario is used a lot too.
@mart-e pinging you for this one.

**Comment by mart-e** [comment]
Fixed at 1df6f4c7
Unfortunately it implied changing all reports but it is due to the python3 migration and we had not much other choices
