### ISSUE TITLE
master - subst function removes css styling from headers in printed reports

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19544]
Impacted versions:
master

Steps to reproduce:

- Create a custom less file and add to assets, setting a new font and h1 weight (for clean template)
- Add to assets etc (report_assets_common)
- Change external report style to clean (if using below code)
- Change invoice report to HTML.
- Print an invoice to display web page - CSS Applied.
- Print a pdf - CSS applied only to body, Header and footer unstyled.
- Change the render call so subst is False for headers and footers - CSS applied (but obviously it prints multiple headers, you may just be able to edit minimal layout to disable subst)
- Change the layout so the css is declared directly in the document. - CSS Applied

So my super guess here is that the subst function is somehow removing css stylings. 

See https://github.com/gdgellatly/odoo_bug_demos/tree/master/subst_error for a premade module setting this up for steps 1 and 2 (less file, assets plus a css styled and directly styled H1 heading).  

Current behavior:
CSS Customizations are not applied to printed reports headers and footers and therefore look completely different between screen and pdf.

Expected behavior:
Screen and pdf have identical stylings.

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
@sle-odoo I think I've worked this out.  It appears that the only css styling that is not applied is what is in the first div, so if it starts <div class="header o_clean_header" > it doesn't apply, but any classes applied elsewhere work.  SO for example - taking clean layout if I do this

```html
        <div class="header o_clean_header">
          <span class="header o_clean_header">
            <div class="row">
                <div class="col-xs-6 pull-right">
                    <img t-if="company.logo" t-att-src="'/logo?company=%d' % company.id" />
                </div>
                <div class="col-xs-6" name="company_address">
                    <ul class="list-unstyled">
                        <h1 t-if="company.name"><span t-field="company.name"/></h1>
                        <li t-if="company.vat"><t t-esc="company.country_id.vat_label or 'TIN'"/>: <span t-field="company.vat"/></li>
                        <li t-if="company.phone">Tel: <span t-field="company.phone"/></li>
                        <li t-if="company.email"><span t-field="company.email"/></li>
                        <li t-if="company.website"><span t-field="company.website"/></li>
                    </ul>
                </div>
            </div>
            </span>
        </div>
```

It works.

**Comment by smetl** [comment]
Hello, t will be fixed by https://github.com/odoo/odoo/pull/19579

**Comment by Yenthe666** [comment]
@gdgellatly should be fixed in saas-18 with https://github.com/odoo/odoo/commit/85a0399d4f31b6edcdf6541d4b6a37220a5e0771 - can you check?

**Comment by gdgellatly** [comment]
@Yenthe666 I don't really need to test it, fix looks fine, it wasn't really an external problem, I just noticed it while doing external work.  Turns out if affected all Odoo reports.  WHen I do I'll reopen if needed.
