### ISSUE TITLE
Taxcloud usage issues

### ISSUE THREAD

**Issue by uojemeni** [odoo/odoo#19569]
Hi,

I need some help with setting up Taxcloud for Odoo v10 Community. 

The issue I face is when I click on the checkbox Compute sales tax automatically in the United States using TaxCloud. under Accounting >> configuration >> settings, I am redirected to the Odoo App store. 

My expectation is that when the checkbox is clicked I should be allowed the option of filling in my Taxcloud API information which sets up TaxCloud.

I believe I am doing something wrong and would appreciate any help.

**Comment by Yenthe666** [comment]
Hi @uojemeni,

Thank you for your report.
@tivisse can probably have a look at this and/or answer your question, I'm not familair with taxcloud myself.
@tivisse could you help please?

Regards,
Yenthe

**Comment by vcloud9ray** [comment]
TaxCloud is an Enterprise Edition feature - each time you select Enterprise Edition features you will be directed to the App Store.

**Comment by Yenthe666** [comment]
Wow, I totally didn't notice the community in the initial comment. You will need an enterprise version to be able to use TaxCloud.
