### ISSUE TITLE
[10.0][Website] Error while editing a blog preview in the website

### ISSUE THREAD

**Issue by benwillig** [odoo/odoo#19577]
Impacted versions:
10.0

**Steps to reproduce:**
1) Connect as a website editor
2) Go to the blog post list page
3) Open edit mode
4) Edit the blog teaser and add carriage return
5) Try to save

**Current behavior:**
A popup indicating "None" is opened on the blog post teaser and it's impossible to save.

**Expected behavior:**
Save should be possible.

Video/Screenshot link (optional):
https://youtu.be/IgiHCgBXLCY

**OPW 772579**

**Comment by qsm-odoo** [comment]
@nle-odoo

**Comment by nle-odoo** [comment]
I had a trial solution for this issue in this pull request to remove "wrong" things from editor if it was set on phrasing element (eg. `<p t-field="..."/>`) : https://github.com/odoo/odoo/pull/20230

But after discussions, something similar has happend previously and currently the way to solve issue like this is:

* on the instance with the issue: edit the view to transform the phrasing element in a div (eg. 
 change `<p t-field="..."/>` in `<div t-field="..."/>`)

* on master: do the change in Odoo sources

Even if it can be a bother (for stable instance which would have to do the fix manually), this way it is solved for future version of Odoo without breaking existing customization in stable versions.
