### ISSUE TITLE
2 steps incoming operations warehouse produce 2 procurement orders for each procurement rule, but when one of this procurement orders is in exception the other one is left in running state

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#19570]
**Impacted versions:**
10.0

**Steps to reproduce:**

This one was reproduced in last [build](http://265119-10-0-054295.runbot8.odoo.com/?db=265119-10-0-054295-all) of runbot 10.0 enterprise.

1. Create a product A stockable, create re-ordering rule min 5, max 10.
2. Configure a supplier for the new product
2. Configure principal warehouse YourCompany to Incoming Shipments: Unload in input location then go to stock (2 steps)
3. Run schedulers
4. Review Procurement Exceptions list view, remove the Exceptions default filter and search procurements by Product A. We have 2 procurements in running state, one for each warehouse step.
5. Check for purchases orders and we have a new RFQ created  (PO00001 in this case) 
6. Delete the purchase line related to Product A.

**Current behavior:**

One of the procurement orders related to the purchase order line is passed to exception state, which is the expected behavior, but, the second procurement stays in Running state

![image](https://user-images.githubusercontent.com/7593953/30617017-39acd1b4-9d62-11e7-9786-64e0a68f08af.png)

This running procurement left does not have purchase order line related, so when re-running the schedule no operation is applied to the procurement and its state does not change at all: Will be there always and will block the schedulers to create a new procurement that is required by the rule. For other hand, since does not have any state or any way to relate this one with the another procurement order will be very messy to find when we have a real life environment with multiple procurement rules, warehouses and products: not easy to identify

**Expected behavior:**

This running procurement is the second step to fulfill our re-ordering rule. If the first procurement changed to exception state then this one should also change to exception state too. This way we will be able to identify and deal with any action we need to handle the exception, and the more important, we will be able to still use scheduler for this procurement rule.

In case that we can not change both procurement to exception state, then we could have some sort of a message or an info inside the notes of the procurement that let us to identify the procurements that are related for this 2 o more incoming warehouse steps.

**Comment by zaoral** [comment]
FYI
OPW 772553

**Comment by zaoral** [comment]
cc @rdmachadog

**Comment by sle-odoo** [comment]
Closing as this was answered on the opw. For reference

> 
> Dear,
> 
> It seems to be the wanted behavior. I checked inside the code and there is the results:
> -> When you cancel a purchase order line it will pass the procurement in exception state but it will not propagate(cancel) it to the following move.
> -> When you cancel the purchase order itself, it will also cancel all the following move and linked procurement.
> 
> In your case, the procurement pass in exception but the picking from input to stock is not cancel thus the procurement still in running state. The purpose is to run the procurement in exception
> again in order to introduce the removed purchase order line in a new purchase order.
> 
>
