### ISSUE TITLE
Web x2many form modal - usability issues

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19599]
Impacted versions: All since web client came out (gtk was fine) for issue 1. Just master for 2.

Steps to reproduce:
1. Save and Save & New need shortcut keys (or at least the functions they call do) - this is a major usability issue and prevents mouse free operation and on large modals were often only the first field requires entry is even worse, users sometimes requiring 20 tabs just to hit enter.  

In the best case for me, it would actually override the same shortcut keys of the parent, which is another usability issue, that when in a modal the parent shortcut keys still work. (so modifier-S for save and modifier-c or n I forget) for create/save & new but thats minor.

2. Editable one2many inside form modal and escape key have undesired/unexpected effect. In prior versions the escape key would remove the extra x2many created after tabbing too far.  In master it actually discards the parent modal record and returns to the form view.  At the very least we need a warning there, but the old behaviour was much better.  

@ged-odoo just minor web client issues I see that inhibit users daily.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by ged-odoo** [comment]
@gdgellatly I agree.  I added the second point on our internal list of things to fix before v11.  First point should be done as well, but this is more a usability concern (we have somewhere a task about keyboard shortcuts, I just don't know its exact status).

**Comment by Yenthe666** [comment]
@ged-odoo could you give an update? 😄
