### ISSUE TITLE
[10.0e] usability issue with menu search with Japanese text

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#19592]
### Impacted versions:

10.0e

The issue was confirmed using Windows 10 + Chrome Version 61.0.3163.79 (Official Build) (64-bit).

### Steps to reproduce:

Try to type "サブスクリプション" (which is "Subscription") in backend home page.

Expected keystroke sequence using Japanese IME: "s" -> "a" -> "b" -> "u" -> "s" -> "u" -> "k" -> "u" -> "r" -> "i" -> "p" -> "u" -> "s" -> "h" -> "o" -> "n" -> space (to convert the text from hiragana to the first suggested option (which is katakana) -> enter (to confirm the suggested option)

### Current behavior:

As soon as "s" -> "a" is input, this part of the text ("さ") is confirmed (as if enter was pressed after "s" -> "a") without giving you the chance for conversion.

### Expected behavior:

When "s" -> "a" is input, the character should not be confirmed yet, and you should be able to complete the keystrokes for the whole word before continuing to the conversion of the word.

### Video/Screenshot link (optional):

![2017-09-20_22-18-21](https://user-images.githubusercontent.com/7766939/30648996-fba97a34-9e51-11e7-8d19-f767215f35fb.gif)

Following keystrokes also seem to have the same issue when they are the first character:
- "i": instantly confirmed as "い"
- "o": instantly confirmed as "お"
- "t" -> "a": instantly confirmed as "た"
- "t" -> "e": instantly confirmed as "て"
- "t" -> "o": instantly confirmed as "と"
- "n" -> "o": instantly confirmed as "の"
- "y" -> "o": instantly confirmed as "よ"
- "w" -> "o": instantly confirmed as "を"

This makes the menu search function unusable in Japanese.

https://www.odoo.com/web?debug#id=772683&view_type=form&model=project.issue&action=609&menu_id=4720

**Comment by odony** [comment]
@ged-odoo an interesting corner case for the menu search

**Comment by ged-odoo** [comment]
@odony @yostashiro I am not surprised, I remember thinking about other input methods.  I created a task in RD Framework to make sure that the home menu is usable in japanese (and I guess other languages). I just can't promise when we will have the resource to actually do it (definitely not for the next few weeks).

**Comment by yostashiro** [comment]
@ged-odoo Welcome!  I quite like the menu search function so I hope to see it working well with Japanese soon.

**Comment by ged-odoo** [comment]
@yostashiro the search function is really really cool (I dislike using previous odoo version just for that).  But this is sadly one of the many features that need more work...   I hope that we will improve it for version 12. There are many ways to do that. The coolest thing would be to add full text search (searching among all fields in all 'business' models).  There is some support in postgres for that.

**Comment by TimLai125** [comment]
@ged-odoo @odony 
FYI, although it is quite obvious, the condition for this issue to occur is the entered string "hits" a result, i.e. name of any menuitem. otherwise there will be no such a issue.

**Comment by yostashiro** [comment]
Fixed with https://github.com/odoo/enterprise/pull/1558/commits/e36b0179b6d4614dba85cd119db9f8bd4be688fd
