### ISSUE TITLE
[9] Purchace order cost price

### ISSUE THREAD

**Issue by garfildas** [odoo/odoo#19598]
Impacted versions: 9

Steps to reproduce: 
Costing method real price
Purchace order 1 item 1usd
Receive
Stock move cost price is 1usd
Invoice price 2usd (mistake in purchace order after receiving)
Cost price in stock move still 1usd

Current behavior:

Expected behavior:
Need to have correct stock move real prices. Is it possible ?

Sorry if my post is know but i cant find answer. I'm new at github.

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
This is a duplicate of #16441, please see my answer on this issue.

Regards
