### ISSUE TITLE
ImportError: No module named reportlab.lib on OSX

### ISSUE THREAD

**Issue by abbood** [odoo/odoo#19609]
# Impacted versions:
odoo 10.0, trying to install on OSX

# Steps to reproduce:
I'm following [these instructions](https://www.linkedin.com/pulse/how-install-odoo-10-os-x-mac-ei-capitan-damilola-awe) to install odoo on mac. It required that I install all the python modules for the user like so:

    $ sudo pip install -—user -r requirements.txt

(*[note](https://stackoverflow.com/questions/42988977/what-is-the-purpose-pip-install-user/42989020#comment79635214_42989020)  about the `--user` part)

However when I run odoo, I get this error:

    $ ./odoo-bin
    Traceback (most recent call last):
      File "./odoo-bin", line 5, in <module>
        __import__('pkg_resources').declare_namespace('odoo.addons')
      File "/Library/Python/2.7/site-packages/setuptools-36.5.0-py2.7.egg/pkg_resources/__init__.py", line 2241, in declare_namespace
      File "/Library/Python/2.7/site-packages/setuptools-36.5.0-py2.7.egg/pkg_resources/__init__.py", line 2257, in declare_namespace
      File "/Library/Python/2.7/site-packages/setuptools-36.5.0-py2.7.egg/pkg_resources/__init__.py", line 2192, in _handle_ns
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
        mod = imp.load_module(fullname, self.file, self.filename, self.etc)
      File "/opt/odoo/odoo-10.0/odoo/__init__.py", line 64, in <module>
        import report
      File "/opt/odoo/odoo-10.0/odoo/report/__init__.py", line 5, in <module>
        from . import custom
      File "/opt/odoo/odoo-10.0/odoo/report/custom.py", line 20, in <module>
        from . import render
      File "/opt/odoo/odoo-10.0/odoo/report/render/__init__.py", line 4, in <module>
        from .simple import simple
      File "/opt/odoo/odoo-10.0/odoo/report/render/simple.py", line 8, in <module>
        import reportlab.lib
    ImportError: No module named reportlab.lib

I noticed that this reportlab is available in requirements.txt:

    reportlab==3.3.0

however, if I run this command

    pip freeze | grep reportlab

I get nothing, but also when I run this command

    sudo pip install --user reportlab

I get the following:

$ sudo pip install --user reportlab

    The directory '/Users/odoo/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/odoo/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Requirement already satisfied: reportlab in /Users/odoo/Library/Python/2.7/lib/python/site-packages
    Requirement already satisfied: pillow>=2.4.0 in /Users/odoo/Library/Python/2.7/lib/python/site-packages (from reportlab)
    Requirement already satisfied: pip>=1.4.1 in /Users/odoo/Library/Python/2.7/lib/python/site-packages (from reportlab)
    Requirement already satisfied: setuptools>=2.2 in /Library/Python/2.7/site-packages/setuptools-36.5.0-py2.7.egg (from reportlab)
    Requirement already satisfied: olefile in /Users/odoo/Library/Python/2.7/lib/python/site-packages (from pillow>=2.4.0->reportlab)

I have tried force reinstalling as suggested [here](https://stackoverflow.com/a/38769487/766570) but that didn't do much.

Ideas?

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by rcastro-tyc** [comment]
Hi @abbood !

It's much better if you use python through [virtualenv](https://virtualenv.pypa.io/en/stable/).

You can use [Homebrew](https://brew.sh). With Homebrew you can install packages in the console as you can in the most Linux distributions. To install you have to run this command in your console  and follow the instructions:

`# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

After this you can install Python. If you already did this with a downloaded installer you can skip installing Python with Homebrew but I cannot guarantee for that. If you have problems then uninstall Python and try the package from Homebrew. To install run and follow the instructions:

`# brew update`
`# brew install python`

Now you have installed Python. Next you need the PostgreSQL server. Here you can also use Homebrew:

`# brew install postgresql`

To start the PostgreSQL right now and automatically at system startup we run:

`# ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents`
`# launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`

Before you install the Python modules you need to install some dependencies for the Pillow module:

`brew install freetype jpeg libpng libtiff webp xz`

Next you can decide how to install the Python dependencies for odoo. One way is to install these globally. If you developing on other Python applications you sometimes need the same Python packages but in different versions. Or you want to let the system clear and remove these easy when you do not need them anymore. To get these advantages we can create a virtual environment for Python. This virtual environment copies Python and some other files (like pip) to a specified directory (e.g. in your home path) and provides a script which rewrites the path to use the Python from this directory.

To install the Python dependencies you can use pip which is package manager for Python (like Homebrew but for Python modules) and is already installed with Python. For creating the virtual environment you can have to install virtualenv. Homebrew does not contain virtualenv so we install it with pip (globally):

`# pip install virtualenv`

Now you can create the virtual environment. You can use for this the directory odoo-env in our home directory:

`# virtualenv ~/odoo-env`

With this command all necessary files were copied to this directory. Next you can enter the created virtual environment:

`# . ~/odoo-env/bin/activate`

Okay, all looking the same as before? :) You can look if you are in this virtual environment:

`# which python`
`/Users/youruser/odoo-env/bin/python`

As you can see the Python binary from this directory is used. If you want to leave this environment you can type deactivate or close the terminal. Be aware that if you open a new tab or reopen the terminal you are not in the environment. Here you have to run the activate script as before.

Now you can start installing all dependencies for odoo. Download odoo if you did not have (e.g. [clone the git repository](https://github.com/odoo/odoo)) . In the newer odoo versions there is a [requirements.txt](https://github.com/odoo/odoo/blob/10.0/requirements.txt) file which contains all dependencies. To install these you have to change to the odoo directory (with cd) and run (you have to be in your virtual environment):

`# pip install -r requirements.txt`
 
This takes some time. If you get these as last lines you can be happy:

`Successfully installed [...]`
`Cleaning up...`
 
You have installed all dependencies. Now you can start odoo if you want:

`# python ./odoo.py`

Then you can open your browser and open http://localhost:8069.

Here you can create a new database with or without demo data and playing/developing with odoo. If you done you can stop with CTRL+C in your console.

Regards,

**Comment by Yenthe666** [comment]
@d-fence perhaps something to check for you?

**Comment by d-fence** [comment]
I agree with @rcastro-tyc that did a good explanation. I'm not sure about the "sudo pip --user", are the files installed for the root user ? Probably. So, that could explain why the module could not be found for the current user. I think that the virtualenv way is far easier.

**Comment by Yenthe666** [comment]
Yeah indeed but can we conclude that this 'bug' is simply an implementation issue and that you should run a virtualenv if you want to do this? Or do we want to improve/change the behaviour?

**Comment by mart-e** [comment]
Closing as the 10.0 is no longer supported
