### ISSUE TITLE
editable x2many form modal tests

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19600]
@ged-odoo Here we go - fun times.  Let me know what more you need.

Impacted versions: master
All tests carried out under python 3.5 on Odoo Enterprise.
rev no's 
3deabab6152d0f89c95eaed24b0169c1d1c63592 ent
08db385d02dd67f82937e4325179dda1a82519b7 core
Browsers - Chromium and Firefox
Localhost w/o proxy on port 8076
Postgres 9.6

Steps to reproduce:
see detailed manual test instructions and test module in commits (commits are atomic so can reproduce each test)
https://github.com/gdgellatly/x2many_bug/commits/master

Current behavior:
Something I didn't notice and I think this is getting to the bottom of it.  Yes the database records were created, but they had no field values for either name or product id, hence they were blank.

In fact the only ones with field values were the edits in Test 3 which gave the traceback in the commit message.  Despite traceback in test 5, no records were updated.

Expected behavior:

Video/Screenshot link (optional):
Test 4 - WTF - NaN
![image](https://user-images.githubusercontent.com/5093264/30671999-e91967fa-9ebd-11e7-9b11-b2bac54da84d.png)

**Comment by gdgellatly** [comment]
Note I just did a couple more tests trying some ideas and adding some basic print code to debug.  Its pretty instructive the output so I add here.

Editing an existing sub line of an existing record - note sub order write never called and nothing in order lines.
```
Order Write
{'order_line': [[1, 11, {'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'tax_id': [[6, False, []]], 'layout_category_id': False}]]}
Order Line Write
{'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'tax_id': [[6, False, []]], 'layout_category_id': False}
```
Adding a new line to an existing record. Note, fields are not in the sub order create.

```
Order Write
{'order_line': [[1, 11, {'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'sub_order_line_ids': [[4, 13, False], [4, 14, False], [0, 'virtual_151', {}]], 'tax_id': [[6, False, []]], 'layout_category_id': False}]]}
Order Line Write
{'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'sub_order_line_ids': [[4, 13, False], [4, 14, False], [0, 'virtual_151', {}]], 'tax_id': [[6, False, []]], 'layout_category_id': False}
Sub Line Create
{'sale_line_id': 11}
Order Write
{'order_line': [[1, 11, {'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'sub_order_line_ids': [[4, 13, False], [4, 14, False], [4, 15, False], [0, 'virtual_208', {}]], 'tax_id': [[6, False, []]], 'layout_category_id': False}]]}
Order Line Write
{'route_id': False, 'invoice_lines': [[6, False, []]], 'analytic_tag_ids': [[6, False, []]], 'product_packaging': False, 'sub_order_line_ids': [[4, 13, False], [4, 14, False], [4, 15, False], [0, 'virtual_208', {}]], 'tax_id': [[6, False, []]], 'layout_category_id': False}
Sub Line Create
{'sale_line_id': 11}
```

**Comment by ged-odoo** [comment]
@gdgellatly wow, this is something we need to process. I added this issue to our internal todo list.  Sadly, we have other duties because of the coming Odoo Experience event, so this will not be done before next week.

**Comment by gdgellatly** [comment]
@ged-odoo Its fine, I got lots to get on with.  If you need anything ping me. 

One thing I did notice was that I did have correct records on the original model around the 2/9 but unfortunately I have no memory of how recent my copy of master was at that time.

**Comment by gdgellatly** [comment]
@aab-odoo I left you another comment over at the bugfix branch you commented on, however I have tested on saas18 and a fresh database just now as it seems more up to date than master.  I think part of the issue I had with initial testing was that while the commits are clean, before the first commit I may have spun up a non working environment - which may have led to some incorrectly created records, Maybe, or maybe its just saas18 has some change, idk, but anyway, the create scenario I can get working in test.

However edit is still most definitely broken as you can see from this video https://youtu.be/U6Z4MHKrIQ4

\cc @ged-odoo

**Comment by aab-odoo** [comment]
Hello,

Commit https://github.com/odoo/odoo/commit/f49d758665938ed7cbb9f46221ba8f0663def514 (in saas-18) closes the issue. The onchange specs weren't correctly computed, and thus the onchange RPC returned unexpected commands erasing your changes.

Regards
