### ISSUE TITLE
Blank odoo page after login

### ISSUE THREAD

**Issue by ilyasProgrammer** [odoo/odoo#19627]
![e3e3](https://user-images.githubusercontent.com/15200087/30705635-67837396-9f0f-11e7-8a71-78d1aab9f863.png)
Impacted versions: 9, 10

Steps to reproduce: install odoo on SLES 11

Current behavior: When I open localhost:8069 i select database and login as usual. Then when redirection to \web happens i see empty Odoo background without menus. When i add ?debug=assets - then all menu appears and  everything works fine. No errors neither in Odoo logs nor in JS console.
I tried this: https://github.com/odoo/odoo/issues/9201#issuecomment-250425399
I tried create new database.
Problem stay.
I test it on remote computer using ssh tunnel. When i use lynx on remote server and open localhost:8069\web\?debug - thats enough for page load correct (not necessary ?debug=assets).

**Comment by Yenthe666** [comment]
Hi @ilyasProgrammer,

Thank you for your report.
This looks like an issue with the compilation of your assets. Do you have all requirements installed for Odoo? See https://github.com/odoo/odoo/blob/10.0/requirements.txt
CC @ged-odoo another asset related issue perhaps?

Regards,
Yenthe

**Comment by muntean** [comment]
Hi all,
I have a similar behaviour (Odoo v10, Ubuntu 14.04, installed from source). I have multiple databases on the same server. For only one of them, after it has been used without problems for some time, we get the blank page after every login now. I've tried the suggestions from the comment posted by @ilyasProgrammer. But the problem still persists.
I've restored the database on another server and there the login works fine.
Any ideas how to proceed further?
Thanks,
Ioan.

**Comment by ged-odoo** [comment]
to state the obvious, it is definitely an asset issue.  I think that we should have a simple mechanism to force the server to regenerate them.  But in the meantime, I may have a workaround (use at your own risk!!!):

- open Odoo in debug mode
- find the 'attachment' action (settings/database structure/attachment)
- go to list view (easier)
- filter on all attachment which starts with /web/content (those represent your assets)
- delete them all

With this, the server should be force to regenerate them.

**Comment by Yenthe666** [comment]
@ged-odoo this is actually safe to do - I've done this a few times before too. You can also do this on database level by running an SQL to remove all the assets.
Is there any idea / roadmap for the asset regeneration?

**Comment by ged-odoo** [comment]
@Yenthe666 I just created a task to add the feature in the debug manager. This is a good task for a junior dev, will be done in master in the next few days.

This does not really solve the underlying issue (assets not being properly generated or updated/maybe race conditions with less compiler/...), but it gives us a simple work around

**Comment by Yenthe666** [comment]
Awesome - thanks a lot!

**Comment by muntean** [comment]
Thank you guys!

**Comment by AMArostegui** [comment]
Same situation here.

I use Odoo 10.0 on several computers: 

- Windows Server 2008 R2
- Linux Mint 17
- Windows 10.

So far, the problem appears only in my Win10 machine. Another workmate runs in Win10 without any issues.

I run Odoo in localhost, using the installer and have never been able to get past the login screen.

When I startup the service, no error is shown in _Odoo.log_ . If I'm logged in, after I refresh the browser I get:

```
2017-10-17 15:53:26,104 8672 ERROR Tests odoo.service.server: Exception happened during processing of request from ('127.0.0.1', 2964)
Traceback (most recent call last):
  File "SocketServer.pyc", line 599, in process_request_thread
  File "SocketServer.pyc", line 334, in finish_request
  File "SocketServer.pyc", line 657, in __init__
  File "SocketServer.pyc", line 716, in finish
  File "socket.pyc", line 283, in close
  File "socket.pyc", line 307, in flush
error: [Errno 10053] Se ha anulado una conexión establecida por el software en su equipo host
```
I've tried the following:

- Disable firewall
- Disable antivirus
- Make Odoo listen in a port other than 8069
- Delete assets, using SQL. They get recreated but no difference shown at all
- Running directly odoo-bin, as an administrator, instead of the service
- Make Odoo create another database

So far, nothing has made a difference.

**Comment by muntean** [comment]
In my case, the only thing that helped was a clean install
of Odoo (v10).

**Comment by ged-odoo** [comment]
for your info, there is now a way to regenerate assets in the debug manager (in master, commit https://github.com/odoo/odoo/commit/28491aac45dc912696c1fcc57a50e3ec98906336)

**Comment by muntean** [comment]
@ged-odoo : Thanks! I'll try this out next time when this issue will occur.

**Comment by Yenthe666** [comment]
@muntean you can't, really, because it is in the master version. It won't be available before V12. 😉
@ged-odoo I'm guessing a backport won't be allowed as it is a new feature?

**Comment by ged-odoo** [comment]
@Yenthe666 correct.

But it should be trivial to backport, and the feature is also pretty easy to add in an external module.

**Comment by wtaferner** [comment]
@ged-odoo 
Hmm, I am kind of tempted to cherry-pick the master commit on v11 :-) should be safe I guess...

**Comment by Yenthe666** [comment]
Yup - I'm tempted to do this too. Maybe I'll make a little addon for it that I publish on Github. Time to find me some time..

**Comment by boumboum** [comment]
I've tried to delete (at the database level) all the assets but it didn't help.
I still have an empty screen
![kep](https://user-images.githubusercontent.com/17336267/31854987-c7b4e8ea-b6a1-11e7-9ae4-bf5c121e9719.png)

**Comment by lukebranch** [comment]
@boumboum ,

After deleting the assets in the DB, try an odoo service restart.

**Comment by boumboum** [comment]
As I've told you in my previous post, deleting the assets at the database level (and restart the service after that) doesn't help.
Odoo is just simple not usable.
IMHO if a product after a first initial clean setup is just usable like that (i.e. not usable at all), you can just forget it.

**Comment by Yenthe666** [comment]
Hey guys,

For all of you that are on Windows - there is a PR in development that will most likely fix these issues. See https://github.com/odoo/odoo/pull/20731
On MS Windows, the mimetypes module relies on the Windows Registry to
guess mimetypes. As a consequence, when generating assets bundle for
javascript files, the mime type of js files may be wrong. 

Regards,
Yenthe

**Comment by fardnia** [comment]
this problem occurred after install some add-on s or apps or modules . for solving this problem go to odoo  add-on s directory in server  and remove folder of your last installed apps or modules . after this work restart odoo service and then all things is  true . :)

**Comment by arafatx** [comment]
I dont have addons from other 3rd party. I made a new database, restart the server still it showing the blank page at the back end, the front end is OK. the server log has no info about the error but in the console I got the following error:

web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'ActionManager' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.renderElement (web.assets_common.js:3943)
    at web.assets_common.js:3943
    at web.assets_common.js:802
    at fire (web.assets_common.js:796)
    at Object.add [as done] (web.assets_common.js:797)
    at Array.<anonymous> (web.assets_common.js:802)
    at Function.each (web.assets_common.js:625)
exception @ web.assets_common.js:3689
_render @ web.assets_common.js:3734
render @ web.assets_common.js:3730
renderElement @ web.assets_common.js:3943
(anonymous) @ web.assets_common.js:3943
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
add @ web.assets_common.js:797
(anonymous) @ web.assets_common.js:802
each @ web.assets_common.js:625
(anonymous) @ web.assets_common.js:802
Deferred @ web.assets_common.js:803
then @ web.assets_common.js:802
__widgetRenderAndInsert @ web.assets_common.js:3943
appendTo @ web.assets_common.js:3943
set_action_manager @ web.assets_backend.js:503
(anonymous) @ web.assets_backend.js:503
(anonymous) @ web.assets_common.js:802
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
fire @ web.assets_common.js:796
fireWith @ web.assets_common.js:801
deferred.(anonymous function) @ web.assets_common.js:803
script.onload.script.onreadystatechange @ web.assets_common.js:3843
web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'CrashManager.error' not found
    at Object.exception (web.assets_common.js:3689)
    at Engine._render (web.assets_common.js:3734)
    at Engine.render (web.assets_common.js:3730)
    at Class.show_error (web.assets_backend.js:576)
    at window.onerror (web.assets_backend.js:503)
exception @ web.assets_common.js:3689
_render @ web.assets_common.js:3734
render @ web.assets_common.js:3730
show_error @ web.assets_backend.js:576
window.onerror @ web.assets_backend.js:503

Is there an official explanation about this error? Because this is not the first time I'm having this issue. Since the earliest Odoo 10 also has this problem. I can reinstall everything and restore the database but why is this happen? Sudden crash ? Random bug ? 

PS: Today, my employees are happy because they don't have to take attendance because the system is blank.

**Comment by fvlasie** [comment]
I am experiencing it too.

**Comment by blackansible** [comment]
I am having the same problem in Windows. Maybe an update make it crash. We have not make any addon installation.

**Comment by Jaffri1** [comment]
HI Friends,

After a lot of search i have find the solution.Kindly update your droplet specification if you are using cloud,The Ram should be at least 4 GB and hard should be at least 40 GB .
 Cheers 
Jaffri

**Comment by SmithLin0618** [comment]
hi @Yenthe666 
I am having a big problem with that.
I have try a long time but i can't fix it.

May I ask you how to do that on database level by running an SQL to remove all the assets?
What command should I do on psql?

**Comment by Jaffri1** [comment]
hi @Yenthe666,

Which version you are using?
Jaffri

**Comment by Mchizan** [comment]
hi @SmithLin0618 

> 
I am having a big problem with that.
I have try a long time but i can't fix 

> 
i faced the same issue twice on a win 7 machine with version odoo version 11. 
To fix it,i installed node js and restarted the machine. That fixed the blank page issue.
ps i had errors loading java script .
I hope that helps you

**Comment by SmithLin0618** [comment]
**hi Everyone 
Thank for your help. 
after I do all of yours advice, but I still can't fix that 

that is my system screen below：
log in page：**
![image](https://user-images.githubusercontent.com/38001362/39390763-f8f6edc2-4acb-11e8-9a16-64fee75fbada.png)

**after login**
![image](https://user-images.githubusercontent.com/38001362/39390782-42c497c4-4acc-11e8-8db2-6765116657de.png)

**Comment by Jaffri1** [comment]
Hi,

Dear kind install odoo blank screen module..kindly download it from odoo
website..it's free.it will solve your error.
Thanks
Jaffri

**Comment by chepoez** [comment]
Thanks Jaffri1 , I think this solution works for Linux instalations right?
https://m.facebook.com/story.php?story_fbid=1927479740907670&id=1858655611123417
for odoo 10 I leave this link I havent tried but hope it works and helps you
https://apps.odoo.com/apps/modules/10.0/web_fix_blank_page/

How shold we install a module if we cannot display the menu of the system?

**Comment by SmithLin0618** [comment]
@chepoez 
-How shold we install a module if we cannot display the menu of the system?
--
I HAVE SAME PROBLEM TOO!

**Comment by Jaffri1** [comment]
Hi dear,kindly make a copy of data base..and reinstall odoo nd modules and
after this restore the data..

Thanks

**Comment by allshore-ahsan** [comment]
I had the same issue but @ged-odoo  you saved me. Thanks for help, deleting all /web/content attachments works.

**Comment by rovermx** [comment]
Same error here, all of the sudden after a server restart, Ubuntu 16.04 with Odoo v11 Enterprise, menu was gone and I panicked database was gone, but was there, anyhow, I tried the two methods explained before:
1- deleting  /web/content attachments items from the settings/database structure/attachment menu
2- issuing DELETE commands

They did work partially in my case, which I am very thankful for!, login page is now correctly formatted, before was crappy, therefore I believe some of the CSS stuff was fixed.
Problem still persists with the images of the modules though, anything else looks visually correct, I already tried incognito and deleting temp browser files.

These suggestions saved my arse!, however I would love to hear is somebody knows how to finish fixing this issue completely, .i.e. making the images of the modules icons re-appear

Thanks!

**Comment by CasVissers** [comment]
@rovermx You should run a base update to restore the images (go to Apps, search Base and click update). Seems like you have restored the database without restoring the filestore. If you have excisting attachments to objects like sale orders they won't be available untill you also restore the filestore.

Btw, this module did the trick for me in EE11:
https://www.odoo.com/apps/modules/10.0/web_fix_blank_page/

**Comment by RezTahar** [comment]
the same problem odoo 11

**Comment by rovermx** [comment]
> 
> 
> If you are not able to install the web_fix_blank_page because you have no interface, I used this command:
> ./odoo-bin -c /etc/odoo-server.cfg -d databasename -i web_fix_blank_page

Thank you for your time and help CasVissers!

**Comment by Aquilog** [comment]
Same problem on Odoo11
Surprisingly, problem disapears if i delete the 'static' folder inside module.
Works even with an empty 'static' folder ...
I work with Pycharm (pycharm / git problem ?)

**Comment by HafedhRahmani** [comment]
> DELETE FROM ir_attachment WHERE url LIKE '/web/content/%'; 
This instruction worked for me, Thank you verry much

**Comment by anmolonline** [comment]
Same issues as above, I tried the delete commands, tried update web, uninstalled the new addon, updated base, but nothing works !

My console  :
`Uncaught Error: QWeb2: Can't clone undefined template FieldMany2ManyTag
    at Object.exception (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:736)
    at Engine.add_template (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:736)
    at Object.<anonymous> (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741)
    at Object.<anonymous> (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10)
    at fire (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10)
    at Object.fireWith [as resolveWith] (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10)
    at done (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14)
    at XMLHttpRequest.callback (web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14)
exception @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:736
add_template @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:736
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
fire @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
fireWith @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
done @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14
callback @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14
XMLHttpRequest.send (async)
send @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14
ajax @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14
jQuery.(anonymous function) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:14
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
fire @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
add @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
each @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:9
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
Deferred @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
then @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
exec @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
load_qweb @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
fire @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
add @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
each @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:9
(anonymous) @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
Deferred @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
then @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:10
session_init @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
session_bind @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:741
(anonymous) @ web.assets_backend.js.pagespeed.jm.wF8Rq9RyuE.js:2
process_job @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:738
process_jobs @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:738
define @ web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:738
(anonymous) @ web.assets_backend.js.pagespeed.jm.wF8Rq9RyuE.js:2
web.assets_common.js.pagespeed.jm.cMBokMkCzY.js:738 GET http:/domain/voip_sip_webrtc/static/src/xml/voip_window.xml 404 (NOT FOUND)
`
Seems like 1 file is missing ?

I tried to install the blank page fix module but received another error:
`psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?`

**Comment by gustavovalverde** [comment]
I got here because it happened to me installing with Docker in WSL. Seems odd as its the first time I got hit by this.

**Comment by gustavovalverde** [comment]
Basically; this is a permission issue. This can be safely closed @Yenthe666

**Comment by FlyingPigSolutions** [comment]
> In Odoo 11, I dont have addons from other 3rd party. Every app is from Odoo. I made a new database, restart the server still it showing the blank page at the back end, the front end is OK. the server log has no info about the error but in the console I got the following error:
> 
> web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'ActionManager' not found
> at Object.exception (web.assets_common.js:3689)
> at Engine._render (web.assets_common.js:3734)
> at Engine.render (web.assets_common.js:3730)
> at Class.renderElement (web.assets_common.js:3943)
> at web.assets_common.js:3943
> at web.assets_common.js:802
> at fire (web.assets_common.js:796)
> at Object.add [as done] (web.assets_common.js:797)
> at Array. (web.assets_common.js:802)
> at Function.each (web.assets_common.js:625)
> exception @ web.assets_common.js:3689
> _render @ web.assets_common.js:3734
> render @ web.assets_common.js:3730
> renderElement @ web.assets_common.js:3943
> (anonymous) @ web.assets_common.js:3943
> (anonymous) @ web.assets_common.js:802
> fire @ web.assets_common.js:796
> add @ web.assets_common.js:797
> (anonymous) @ web.assets_common.js:802
> each @ web.assets_common.js:625
> (anonymous) @ web.assets_common.js:802
> Deferred @ web.assets_common.js:803
> then @ web.assets_common.js:802
> __widgetRenderAndInsert @ web.assets_common.js:3943
> appendTo @ web.assets_common.js:3943
> set_action_manager @ web.assets_backend.js:503
> (anonymous) @ web.assets_backend.js:503
> (anonymous) @ web.assets_common.js:802
> fire @ web.assets_common.js:796
> fireWith @ web.assets_common.js:801
> deferred.(anonymous function) @ web.assets_common.js:803
> fire @ web.assets_common.js:796
> fireWith @ web.assets_common.js:801
> deferred.(anonymous function) @ web.assets_common.js:803
> fire @ web.assets_common.js:796
> fireWith @ web.assets_common.js:801
> deferred.(anonymous function) @ web.assets_common.js:803
> fire @ web.assets_common.js:796
> fireWith @ web.assets_common.js:801
> deferred.(anonymous function) @ web.assets_common.js:803
> fire @ web.assets_common.js:796
> fireWith @ web.assets_common.js:801
> deferred.(anonymous function) @ web.assets_common.js:803
> script.onload.script.onreadystatechange @ web.assets_common.js:3843
> web.assets_common.js:3689 Uncaught Error: QWeb2: Template 'CrashManager.error' not found
> at Object.exception (web.assets_common.js:3689)
> at Engine._render (web.assets_common.js:3734)
> at Engine.render (web.assets_common.js:3730)
> at Class.show_error (web.assets_backend.js:576)
> at window.onerror (web.assets_backend.js:503)
> exception @ web.assets_common.js:3689
> _render @ web.assets_common.js:3734
> render @ web.assets_common.js:3730
> show_error @ web.assets_backend.js:576
> window.onerror @ web.assets_backend.js:503
> 
> Is there an official explanation about this error? Because this is not the first time I'm having this issue. Since the earliest Odoo 10 also has this problem. I can reinstall everything and restore the database but why is this happen? Sudden crash ? Random bug ?
> 
> PS: Today, my employees are happy because they don't have to take attendance because the system is blank.

did you find a solution in the end? I have opened a similar issue I believe for ODOO 11 [there](https://github.com/odoo/odoo/issues/41102)

**Comment by arhimas** [comment]
> @rovermx You should run a base update to restore the images (go to Apps, search Base and click update). Seems like you have restored the database without restoring the filestore. If you have excisting attachments to objects like sale orders they won't be available untill you also restore the filestore.
> 
> Btw, this module did the trick for me in EE11:
> https://www.odoo.com/apps/modules/10.0/web_fix_blank_page/

But How you did it?, how you can activate a module from linux bash?
