### ISSUE TITLE
Wrong warning when create new record of model which has widget char

### ISSUE THREAD

**Issue by nguyenductamlhp** [odoo/odoo#19634]
Impacted versions: 
10.0
Steps to reproduce:
1. Create model A which has integer a field and a One2many field
2. In form view of model A, add `widget="char"` for fields integer
3. Create new record for model A

Current behavior: Raise warning

> The record has been modified, your changes will be discarded. Are you sure you want to leave this page ?

Expected behavior: Do not raise warning. New record is created normally

Video/Screenshot link (optional):
https://youtu.be/5Xu-ny171TI

**Comment by afwanwh** [comment]
Dear @Yenthe666 ,

Just curious, any update on this issue or will be fixed in next version? I still found it in version 10.0.

**Comment by Yenthe666** [comment]
Hi @afwanwh,

As long as there is no response it is basically not checked and there is no solution or feedback yet.
Nevertheless I would say that this is basically misuse of framework functionalities, don't you think? (cc @pedrobaeza)

**Comment by afwanwh** [comment]
Ah I see.

I just checked char widget isn't used in that way inside Odoo's source code. So, I agree with you.

**Comment by pedrobaeza** [comment]
This is an invalid use, so errors are expected. The `char` widget can't be used with `fields.Integer` fields, so closing this as invalid.
