### ISSUE TITLE
Enterprise Master Less Syntax Error

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19648]
Impacted versions: master

@fwi-odoo 

Steps to reproduce:
Use any IDE that automatically detects errors and watch it complain after pulling enterprise master
https://github.com/odoo/enterprise/blame/master/voip/static/src/less/voip.less#L259

There's a trailing comma on that line just before the brace.

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thanks for the report - you're actually correct.
I made a PR to fix this minor thing at https://github.com/odoo/enterprise/pull/1724 😉 

Regards,
Yenthe
