### ISSUE TITLE
[8.0] [account_asset] Number of assets created from invoice line

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#1965]
Number of Assets Created from Invoice Line

Impacted versions:

8.0 and above
Steps to reproduce:

create a supplier invoice
add a line with product 'Asset', quantity 2, unit price 10.0, asset_category Assets
validate the Invoice
Current behavior:

Create one asset with subtotal of invoice line

Expected behavior:

Create 2 assets with line subtotal / line.quantity (not taking the price unit if it is the case of discount)

Fix in #1964

**Comment by Yenthe666** [comment]
Hi @feketemihai,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
