### ISSUE TITLE
Purchase Double Validation is not working

### ISSUE THREAD

**Issue by Amit-Parik** [odoo/odoo#19657]
Impacted versions:

Steps to reproduce:
installed , purchase double validation module.
configure purchase order limit with 5000
Made PO with more then 5000  
Confirm it , it will directly move to purchase order 
Current behavior:
Once we confirm PO which over the assigned limit for double validation,  it will be not going for two step validation
Expected behavior:

It should be move to "To Approve" state for double validaion

Video/Screenshot link (optional):

**Comment by moylop260** [comment]
What is your version of odoo used?
Could you give us the sha of your repository? (git log -r -1)

**Comment by Amit-Parik** [comment]
Sorry Moylop,

Accept my apology. 

Issue at my end, I was tested it with Purchase Manager access then suddenly I got that purchase double validation workflow only apply for purchase user and purchase manager can approve that order.

So I am closing this issue now
