### ISSUE TITLE
[8.0] [account_asset] History of asset based on depreciation lines

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#1966]
History of Depreciation Lines in Asset Form

Impacted versions:

8.0 and above
Steps to reproduce:

create a asset
Confirm It
Create move from first depreciation line
Current behavior:

In history it will show the account move line associated with depreciation expense account

Expected behavior:

Show in history the account move lines associated with the account depreciation account.

Fix in #1964

**Comment by Yenthe666** [comment]
Hi @feketemihai,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
