### ISSUE TITLE
Forum Karma settings missing karma_answer

### ISSUE THREAD

**Issue by KurtHaselwimmer** [odoo/odoo#19672]
Impacted versions: All

Steps to reproduce: Go to Forum form view (tab) Karma Related rights

Current behaviour: No option to change value for 'Answer Questions' (karma_answer)

Expected behaviour: Should be able to change all Karma Related rights for a forum on this form

Solution: Simply add an extra field (karma_answer) in form view after 'Ask Questions'

**Comment by Yenthe666** [comment]
Hi @KurtHaselwimmer,

Thanks for your report.
Could you give a bit more information about this please? What exactly would you like to achieve with this? I'm not sure I'm understanding what you mean.
CC @JKE-be 

Regards,
Yenthe

**Comment by KurtHaselwimmer** [comment]
Yenthe,

I would like to adjust all the forum karma posting requirements in a single place. I discovered that this setting and this setting along was the only one missing from the forum control panel. When you change some of the karma setting values you can end up with problems due to changing the forum setting values but not being able to change karma_answer from its default value of 3. 

Dr. Kurt Haselwimmer

-------------------------------------------------------------
Willow House, 100 High Street, Somersham, PE28 3EH
Tel +44 (0) 845 899 0257  Fax +44 (0) 845 899 0259
-------------------------------------------------------------
