### ISSUE TITLE
Is odoo totally free and can odoo be tailored for organization use  

### ISSUE THREAD

**Issue by bboalimoe** [odoo/odoo#19671]
As the title tells, which modules of odoo are free and which can be imported by paying the fee.

Thank you!

**Comment by dan18fan** [comment]
This is not the right place to ask that.

**Comment by vcloud9ray** [comment]
See https://www.odoo.com/page/editions

Online = Hosted
Enterprise = Subscription Shared Source (source code to those who license)
Community = Free in the traditional sense of Open Source

Where you can ask questions (this is a place for logging issues):

https://www.odoo.com/groups

**Comment by Yenthe666** [comment]
Hi @bboalimoe,

Thanks for your report.
The Github issue tracker is only for bugs or problems in the official code though. Please do feel free to ask this on the official forums (help.odoo.com) or on the groups (https://www.odoo.com/groups).
To answer in short: yes Odoo is 100% free if you take the community version and host it on your own server.

Regards,
Yenthe
