### ISSUE TITLE
[master community]: Required fields on one2many are not highlighted

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#19689]
Impacted versions: master

Steps to reproduce:

* Go to an invoice.
* Add a line.

Current behavior:

* You see field "Description" without the required color

Expected behavior:

* You see any visual hint for indicating that the field is required.

cc @Tecnativa

@ged-odoo is this on purpose?

**Comment by aab-odoo** [comment]
Hello

This seems to be fixed.

Regards.

**Comment by pedrobaeza** [comment]
Are you sure? I don't see any new runbot build and the last working one was not working. I haven't tried locally. Can you provide a runbot link for checking?

**Comment by aab-odoo** [comment]
Ok sorry, it's community only. I only checked enterprise. We'll fix it.

Regards.

**Comment by pedrobaeza** [comment]
Sorry, I didn't specified either. I'll take it into account next time.

**Comment by aab-odoo** [comment]
Closed by https://github.com/odoo/odoo/commit/ca258b8691c3581f0ec4d203b591c2279cc7a6a2

**Comment by pedrobaeza** [comment]
Thanks!
