### ISSUE TITLE
Master - Inventory report displays only template name - not variant

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19695]
Impacted versions: Master

Steps to reproduce:
Use Variants
Print Inventory Valuation

Current behavior:
You see the template name - rather than including variant name
Expected behavior:
You can tell what the product is.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/30829809-5e3e85b8-a29e-11e7-8548-3a2547e79611.png)

**Comment by amoyaux** [comment]
Seems to be fixed in 10.0 and 11.0
