### ISSUE TITLE
Usability - input types

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19727]
Impacted versions: Master

Steps to reproduce:
Access runbot using a mobile device - preferably a tablet.
Find an editable numeric field. - Starting an inventory should do
Watch normal keyboard pop rather than numeric.

I know it isn't strictly a bug in a technical sense, but in a usability sense - (such as entering an inventory quantity in a mobile warehouse) its a nightmare.

Current behavior:
All fields excluding checkbox and toggles have input type defaulted to "text"

Expected behavior:
Appropriate input type for appropriate fields. (or at least near enough) 

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
Note: I was a bit bored so I thought I'd give it a go myself as an extension module.  Its the first javascript I've ever written so no way I'd propose here, but if you decide to do it, thats how I've done it and tested on a tablet.

Integer as a telephone field
Float as a number field
Char accepts an options dict entry of input_type.  It doesn't do any validation there, but if you get a field type wrong it just falls back to text anyway.

https://github.com/odoonz/odoonz-addons/tree/11.0/web_field_input_type

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thank you for the report & the concept. I'm sure @ged-odoo can give feedback and/or a fix.

**Comment by ged-odoo** [comment]
@gdgellatly @Yenthe666 did not really read the code, but the concern is obviously sound. We should definitely take that into account
