### ISSUE TITLE
Not able to Create Product variant without Product Template

### ISSUE THREAD

**Issue by bharatkhandelwal** [odoo/odoo#19745]
Impacted versions: 11 (community)

Steps to reproduce: 
Sale Price Currency and Cost Price currency fields are mandatory in Product Template and those fields  are directly set in  product variant but in case in attempt of  product variant  creation directly from Product variant form view system will raise warning of 'Sale Price Currency and Cost Price currency fields'.

Current behavior: Raising Field error

Expected behavior: Product variant should be created without Product Template
![product_variant](https://user-images.githubusercontent.com/11583449/30906577-e52271aa-a395-11e7-8bc0-3ab6affb4be7.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e can you have a look? I believe the idea is that a product template is made which creates a variant (automatically) and not the other way around?

**Comment by mart-e** [comment]
> Impacted versions: 11 (community)

I doubt it, as it is not released yet 😉 I guess you mean the saas-18? Which modules installed?

Yes, indeed. It is intended to work only with templates creating variants.
I tried on a runbot it worked for me but depending of options or installed module, you may get an error.

**Comment by bharatkhandelwal** [comment]
Hello @mart-e 

i have checked in runbot odoo master brach and i found this issue as mentioned previously.
in odoo -8 to odoo 10  whenever we create product variant it will automatically create product template

**Comment by mart-e** [comment]
So you are not even testing on the (yet unreleased) version 11 (saas-18 branch) but on the future version 12 (master branch).

Sorry but the master branch is the development version, it is changing a lot frequently and the sale form will change quite a lot before the release in a year.
Closing as we want to focus on the stable versions report.

**Comment by bharatkhandelwal** [comment]
hello @mart-e 

i will be waiting to release  version 11 and  later on i will check it and let you inform if there will be an issue. 
thanks for your time
