### ISSUE TITLE
Not option for bank account of thirdparty

### ISSUE THREAD

**Issue by krijn1981** [odoo/odoo#19754]
Impacted versions:
V9 / V10

Steps to reproduce:
xxx

Current behavior:
Currently is not possible to add a bank account lets say on Vendor A that is from a other company.
Many companies are using factoring (selling there receiveables) to other company. So in that why the bill needs to be paid to other "bank account" instead of the vendors account.

The option to create a thirdparty vendor is no option, because if you get 2 vendors with the same factoring company account you can not see anymore which vendor bills is who's.

Expected behavior:
Idem to version 8, Bank account need to fill in the connected vendor + name of bank account owner.

Video/Screenshot link (optional):
xxxx

**Comment by Yenthe666** [comment]
@qdp-odoo could you give feedback? This is beyond my knowledge. 😉

**Comment by qdp-odoo** [comment]
not a bug, simply a feature not supported
