### ISSUE TITLE
[10.0] account_asset: Incorrect behavior with "widgetonbutton" on assets

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#19756]
Impacted versions: 10.0

Steps to reproduce:

* Create an asset type with default values, filling a random journal and account, but leave "Auto-confirm Assets" unchecked.
* Create an asset with that type and any gross value.
* Confirm the asset.
* On the depreciation board, all depreciation lines have a red circle on the right.
* Clicking on the circle, the journal entry is created, and it appears now in orange.

Current behavior:

Clicking again on the circle (in orange) makes nothing.

Expected behavior:

Clicking again on the circle (in orange), it should post the journal entry.

If you mark on the asset type the "Auto-confirm Assets" check, then when you click on the red circle the first time, the journal entry is created posted and the circle is green. If you click now on the circle, the entry is unposted and becomes orange, so that reinforces the expected behavior on "orange" state.

@qdp-odoo although this is more a problem with the widget `widgetonbutton`, I ping you to see which is the most appropriated for this

**Comment by qdp-odoo** [comment]
mmh no, I don't agree to one-click-post journal entries: if you didn't thick the auto-confirm option it means that it's not likely what you want to do when clicking on the orange bullet.

It should maybe open the journal entry in a popup... Anyway, that can't be considered as a bug, I'm afraid
