### ISSUE TITLE
OperationalError: could not obtain lock on row in relation "ir_sequence"

### ISSUE THREAD

**Issue by andreasdsp** [odoo/odoo#19761]
Impacted versions: Odoo 9c

i try to make stock picking with some transaction at the same time.
scenario 1 :
create 3 PO with 20 line on each order line which each product will generate stock journal. make stock picking on them and then open them in seperate tab (1 tab 1 picking) and at the same time validate it.
result : 3 picking are success

scenario 2 :
in this scenario i duplicate PO from scenario 1 and make it 5 PO. and then make stock picking on each of them. last, i validate them at the same time.
result : 4 picking are success and 1 picking is unsuccess

below is the screenshot of the unsuccess picking from scenario 2
![screenshot_26](https://user-images.githubusercontent.com/32347701/30945817-91e69616-a42a-11e7-9c5d-eebd6b3e5b07.png)

scenario 3 : 
uncheck date_range in stock sequence. duplicate PO from scenario 1 become 5 PO and make 5 stock picking of them. and then validate them at the same time.
result : 5 picking are success

scenario 4 :
still uncheck date_range,but in this scenario i try to validate 10 stock picking at the same time.
result : 5 picking are success and 5 picking are unsuccess

below is the screenshot of unsuccess picking from scenario 4 (4 error with this message)
![screenshot_28](https://user-images.githubusercontent.com/32347701/30946034-dd08d4e6-a42b-11e7-97c2-a86b9d9c0e7e.png)

below is the screenshot of unsuccess picking from scenario 4(1 error with this message)
![screenshot_27](https://user-images.githubusercontent.com/32347701/30946085-185233bc-a42c-11e7-97ee-2aaad65fdf78.png)

how do i solve this problem?

update : 
when implementation in sequence stock journal changed from no gap to standart and do scenario 4, all of picking are success.

**Comment by bimajatiwijaya** [comment]
We can reproduce only for sequence with implementation "No Gap"

**Comment by gdgellatly** [comment]
It's a desirable behaviour.  The system is waiting until it can be
guaranteed not to mess up a sequence.  After retrying 5 times, it quits
with that error.

Your choices are:
Segment sequences (i.e. multiple stock journals with different sequences)
Use standard sequences (i.e. tolerate gaps)
Use faster hardware, better tuning etc (i.e. transactions complete faster
so less chance of retry failure)
Asynchronous processing (using some kind of message queue to process)

Or a mix of the above.  There may be others, which works best is often
situation dependent.  But lets face it, if you are processing 5 incoming
goods per 10 seconds, or 30 a minute, even on an 8 hour day thats about
10,000 receptions / day.  Its a bit more than the general use case and
you'd expect to have to do a lot of performance tuning.

**Comment by bimajatiwijaya** [comment]
@gdgellatly : Thank you for quick response and your advice.

**Comment by Yenthe666** [comment]
This is indeed desired behaviour. @gdgellatly gives a lot of good tips & ideas about how to overcome this. Best of luck!

**Comment by GrupoAlvamex** [comment]
@gdgellatly Thank you!!

**Comment by mortenstarfly** [comment]
While trying the suggestions from @gdgellatly I found that I still get the error while:
1) using multiple Journals with their own sequences
2) using no-gap sequences

Can anybody confirm that using multiple Journals with their own sequences should fix this?

My case is a long running transaction that will post Journal Entries on **Journal A**. If I meanwhile try to post a Journal Entry on **Journal B** I get this error. Even if the second sequence is standard implementation (not no-gap).

I'm curious why the error is related to date_range sub sequence: `ir_sequence_date_range`.

**Comment by gdgellatly** [comment]
@mortenstarfly I've actually seen that in logs on v12. I think its a different issue as you get it even without using date range sequences.

**Comment by HaydarZaraki** [comment]
> While trying the suggestions from @gdgellatly I found that I still get the error while:
> 
> 1. using multiple Journals with their own sequences
> 2. using no-gap sequences
> 
> Can anybody confirm that using multiple Journals with their own sequences should fix this?
> 
> My case is a long running transaction that will post Journal Entries on **Journal A**. If I meanwhile try to post a Journal Entry on **Journal B** I get this error. Even if the second sequence is standard implementation (not no-gap).
> 
> I'm curious why the error is related to date_range sub sequence: `ir_sequence_date_range`.

did you find any solution for this problem ? i'm facing it right now

**Comment by flotho** [comment]
Same here with v12 community uptodate on accounting part with pos.
I have multiple pos and each of them has dedicated sequence for sales and invoicing and only 1 user is working per pos.
a consequent number of invoices are not validated because of this issue and this shouldn't be the case because of the segmentation.
Any chance to have another help from Odoo here ?
