### ISSUE TITLE
Bug pdf font rendering, not readable after install wkhtmltopdf

### ISSUE THREAD

**Issue by labcrm** [odoo/odoo#19769]
_Impacted versions:_
Odoo 10 OCA (2017-08-15)
Linux Centos7 version on Bitnami stack
![odoo10_pdf_report_font_error](https://user-images.githubusercontent.com/31368648/30958900-d4c14a4e-a43e-11e7-8609-70beecef9974.PNG)

_Steps to reproduce:_
Print a pdf report on Odoo client

_Current behavior:_
The pdf is generated but **## the pdf font is not readable !**

_Expected behavior:_
Standard font when opening the pdf

_Video/Screenshot link (optional):_
See attachment

**Comment by Yenthe666** [comment]
@sle-odoo any idea? A setup that isn't done quite a lot I guess (bitnami on Centos 7)

**Comment by flotho** [comment]
Hi @labcrm , it looks like you're missing a font

**Comment by labcrm** [comment]
Yes that's right, we've resolved the issue by installing these package :
$ sudo apt install libxrender1 fontconfig

=> with 0.12.1 of wkhtmltopdf version

Thank you.

**Comment by Yenthe666** [comment]
@d-fence not sure but can we add this in the preconfigured package too for CentOS?
