### ISSUE TITLE
Graph Label Values on Selection Fields are not translated

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#19790]
Impacted versions:

9.0

Steps to reproduce:

Create a bar graph using a selection fields to group the records.

Current behavior:

The label are not translated and the "value" is displayed rather than the "label".

Expected behavior:

Display the Label Translated in the user language.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @be-cloud-js,

Thank you for your report.
Could you add a screenshot and/or an example where we can see this by default on a runbot perhaps?

Regards,
Yenthe

**Comment by be-cloud-js** [comment]
Sure, a simple example by using the graph view on invoices in the accounting module,

![capture d ecran 2017-10-02 a 14 11 28](https://user-images.githubusercontent.com/12003829/31076741-f32980ce-a77b-11e7-98d8-6962a6b10c6d.png)

As you can see, despite my local is French, the graph shows draft,open,... while the tree view shows the translated labels

![capture d ecran 2017-10-02 a 14 13 13](https://user-images.githubusercontent.com/12003829/31076745-f603bbca-a77b-11e7-8427-1edfaaf22396.png)

Jerome

**Comment by Yenthe666** [comment]
Yep, this is correct. @ged-odoo I believe the labels and their translations are handled in the JS side? CC @mart-e

**Comment by mart-e** [comment]
Not exactly, it is not really a translation issue.
The issue comes actually from the ORM, the grouping method returns the technical labels instead of the display name of the fields.
For instance if you try to group by type, you will see "out_invoice" instead of "outgoing invoice".

This is still a bug but it requires a bit more change.
We will definitely not change the return format of the `read_group` method in stable version but maybe we can work it out another way.

**Comment by ged-odoo** [comment]
@mart-e @Yenthe666 Actually, it looks like a JS bug to me.  The JS code should have a way of doing the mapping between the technical name and the label.  In this case, I assume that it is a selection field.  So, the issue may be that in version 9.0, we did not have the field_get which contains the necessary information. To be sure, I would need to have a look at the code, and I think that I should work on my presentation instead...

Note: this works in master, and we definitely did not change read_group

**Comment by Yenthe666** [comment]
Don't worry, we can look at this later on. Let us get back to it when it is a bit calmer.
Best of luck on your presentation @ged-odoo!

**Comment by mart-e** [comment]
> The JS code should have a way of doing the mapping between the technical name and the label. 

I agree, this is what I intended by

>  but maybe we can work it out another way

**Comment by mge-odoo** [comment]
Hi @be-cloud-js 

Thanks for reporting the issue. It has been fixed in 9.0

Regards,

Martin
