### ISSUE TITLE
Critical fixes in odoo 8.0 - account_tax

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19808]
Impacted versions: 8.0

Steps to reproduce: account_tax

Current behavior: Current philosophy of odoo is to work b2b situations, but in many law in Europe all dial is negotiated and makes with model b2c. All public prices is need to offer, negotiate and scribe with included taxes. The problem in account_tax is d'not have calculations take price with taxes and return without taxes. This problem reflect on POS, Website Sale and Pricelist. Now definited list_price is without taxes, if you make beautiful price calculate and offer with taxes (example: price like 99 or 95 in this moment impossible to make with pricelist).

Expected behavior: Add new model for calculations take price with taxes and return price without taxes, new fields in product_product public price with taxes, same in variant. New JS engine for pricelist and taxes in POS and website_sale.
Partly fixed in my repository

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
