### ISSUE TITLE
Critical fixes in odoo 8.0 - account

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19807]
Impacted versions: 8.0

Steps to reproduce: account, account_move_line

Current behavior: When make Intercommunity dial EU taxes rate is 0%, Account movement is one monolite record, one movement for dial + taxes. This is not correct in some situations is possible to change rules, and to lose tax credit for VAT, when lose tax credit, taxes is added to total amount of deal. Now is not possible to configured taxes with lose tax credit. Same problem with customs rates when have dial export and import with 3d countries. 

Expected behavior: To resolve this problem is need to add functionality in account.tax to work with separated movement one for taxes, one for dial. For import/export dial is need to add new type taxes customs rate (this is specialty dynamic definition percentage).
This is fixed in my repository

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
