### ISSUE TITLE
Critical fixes in odoo 8.0 - account_account

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19809]
Impacted versions: 8.0

Steps to reproduce: account_account

Current behavior: Pricelist in manual invoice. Special field price_vat. This is need in special situations when calculate customs taxes and same deal with buildings. When make import price in Invoice is a dial price, but price for calculations of duty taxes is recalculated price with statistics currency rate. After if add in landed cost some expences, need to be possible to add for example price of transport to calculate base for calculations of taxes, but for dial price if have EXW is without transport and taxes.

Expected behavior: Add new field in SO, PO and invoice and corrections in landed module.
This is fixed in my repository

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
