### ISSUE TITLE
Critical fixes in odoo 8.0 - res_currency 

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19801]
Impacted versions: 8.0, 10.0

Steps to reproduce: res_currency

Current behavior: Currency rate is only from central EU Banka.

Expected behavior: In SO, PO and BS is different way for The money. When made SO and PO, you need to understand what is real price of The deal, after recalculate with currency rate. When make SO in different currency you when calculate, and you wand money, need to recalculate with "sell currency rate". With PO is same, but with "buy currency rate". In same special cases like recalculations customs taxes need to take "statistics currency rate". 
Resolves : New field for buy, sell, statistics currency rate, fix in pricelist when recalculate price for sell and purchase. In Account, when calculate customs rates. Last is other issue.
Fixed in my repository

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
