### ISSUE TITLE
We want to help translating Odoo 10.0 in Malay Language.

### ISSUE THREAD

**Issue by arafatx** [odoo/odoo#19805]
Me and my team at Maxibi (maxibi.com) want to help translating odoo 10.0 in Malay Language (Bahasa Melayu). I guess the correct ISO code is ms_MY, file name-> "ms.pot". We have not seen this this language enabled in Odoo. I have read in the odoo documentation, that in order to contribute I can use Transifex or other software. I prefer using Transifex but the Malay language is not available yet to be chosen in the system. Do I need to create *.po files and do pull request first? Please guide.

**Comment by Yenthe666** [comment]
Hi @arafatx,

First of all a big thank you for your interest to collaborate! You can create an account on Transifex and then request a language. One of the guys from Odoo can accept this and then you can start translating on Transifex.
It is better not to create the .po files through Transifex as this would make it difficult to maintain the language.
@mart-e can you follow up on this please?

**Comment by mart-e** [comment]
Hello,

As said Yenthe, you can register on the [Transifex project](https://www.transifex.com/odoo/public/) and request the language.
Closing as this is to be handled on Transifex.
You can [contact me](https://www.transifex.com/user/messages/compose/mart_e/) there if you have issues.
