### ISSUE TITLE
[STOCK] stock: Stock user should not see all the sales orders by default

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#19816]
Impacted versions:

saas-18

Steps to reproduce:

- Create an user with only "Inventory User" ACL.
- Login with It. 

Current behavior:

- This user see Sales and Inventory
- Including all sales orders.

Expected behavior:

- Only Inventory app should be seen and all sales should be retrieved from the inventory app if necessary

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/338634/31045897-07d2f45e-a5ee-11e7-82c5-7fff2be14cde.png)

![image](https://user-images.githubusercontent.com/338634/31045908-52222f0c-a5ee-11e7-94d8-d2f2ece8e22f.png)

**Comment by sle-odoo** [comment]
@lap-odoo i think this makes sense, we can merge this one if you agree

**Comment by lap-odoo** [comment]
@sle-odoo Yes, I'm ok with this
