### ISSUE TITLE
 Critical fixes in odoo 8.0 - stock_account

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#19810]
Impacted versions: 8.0

Steps to reproduce: stock_account

Current behavior: When the product have scrapped and robbed you need to calculate taxes. There is no option to configure fiscal positions in configurations of warehouse places. The other problem when sell the materials or take for producement have two models for accounting movement, now if configure product like materials to possible to sell it is not possible to take for producement. 

Expected behavior: Add new configurations for fiscal positions in virtual places of warehouses. Rebuild stock_account to add this functionality. It must have two fields one for producement and one for sell in the configurations in product_product and the categories for outgoing account

**Comment by Yenthe666** [comment]
Hi @rosenvladimirov,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
