### ISSUE TITLE
Saas18 Product Product name search messed up

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#19828]
Impacted versions: Saas18

Steps to reproduce:
The below code is cut and paste from product module name search.  I suspect this is a hangover from when specific variants could not be specified on the supplierinfo record (although even then, this is questionable).

```python
        if not products and self._context.get('partner_id'):
                suppliers = self.env['product.supplierinfo'].search([
                    ('name', '=', self._context.get('partner_id')),
                    '|',
                    ('product_code', operator, name),
                    ('product_name', operator, name)])
                if suppliers:
                    products = self.search([('product_tmpl_id.seller_ids', 'in', suppliers.ids)], limit=limit)
```

This response is nonsense.  Lets say I pass the arguments name='ABC', operator='=' knowing it will search product code of suppliers.  Now after successfully finding the correct supplier info record, we go and fetch all products from that supplier.

To reproduce, create some supplierinfo records for some products all belonging to one supplier.
Name one ABCD (or make the supplier partcode ABCD).
Name the rest whatever you like except not containing ABCD obviously.
Watch as you get all the products back in say a purchase order.

Current behavior:
The result I do not expect is all products from that supplier, but rather just the ones that match the search.  Indeed, given the limit of 8, its highly feasible that you don't even get a single matching record.
Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
I'm all for what you're suggesting! @mart-e one for you.

**Comment by gdgellatly** [comment]
@mart-e 

Just a follow up, it was a little bit tricky to get corrrect behaviour for me, and I'm still not sure its right.  My actual use case is scanning a barcode, but not an EAN one necessarily, it might just be supplier internal partcodes.

```python
        if not products and self._context.get('partner_id'):
                suppliers = self.env['product.supplierinfo'].search([
                    ('name', '=', self._context.get('partner_id')),
                    '|',
                    ('product_code', operator, name),
                    ('product_name', operator, name)])
                if suppliers:
                    supp_args = [('id', 'in', suppliers.mapped('product_id').ids)]
                    suppliers = suppliers.filtered(lambda s: s.product_id is False)
                    if suppliers:
                        supp_args = ['|', ('product_tmpl_id.seller_ids', 'in', suppliers.ids)] + supp_args
                    products = self.search(supp_args, limit=limit)
```
