### ISSUE TITLE
Small typo in Dutch language (Accounting module)

### ISSUE THREAD

**Issue by danger89** [odoo/odoo#19821]
Impacted versions:
All (up and including Odoo 10.0-20170930)

Steps to reproduce:
In Accounting app go to:
 - Step by step guide (right top menu)
 - Welcome pop-up opens
 - Dutch translation is wrong 'Welko' instead of 'Welkom' (Welcome).

Current behavior:
Welko

Expected behavior:
Welko**m** (note: the 'm' is missing here)

Screenshot link:
![welko](https://user-images.githubusercontent.com/628926/31049762-7b0dd92e-a63a-11e7-8ddd-8f3e83ff41f4.png)

I tried to find this string in Transifex and on the repository (addons/account/views/web_planner_data.xml), but in all cases I could NOT FIND the Dutch translation with the spelling error.

So hopefully you guys/girls know where to fix this string.

Thanks!

Regards,
Melroy

**Comment by Yenthe666** [comment]
Hi @danger89,

Thank you for the report. There was indeed a typo in this translation and I've fixed it:
![image](https://user-images.githubusercontent.com/6352350/31056532-777d35cc-a6d3-11e7-9e44-f1d7a924e5e8.png)
The easiest way to find a wrong string is to open the correct version on Transifex (Odoo 10), then choose to translate everything and then search for "Translation text" with the value you search for 😉 

Regards,
Yenthe

**Comment by danger89** [comment]
@Yenthe666 Thanks, but initially I really tried that.
I admit I don't know transifex at all.

My search kinda stopped here:
![no_results](https://user-images.githubusercontent.com/628926/31056751-4defc752-a6d7-11e7-98bd-1b10c179865f.png)

**Comment by Yenthe666** [comment]
@danger89,

Yep, this has been hidden quite well. It took me some time to figure that out too to be honest. 😉 
This will be automatically fixed in the new Odoo 10 minor updates - usually it takes a good week for translations to synchronise back into Odoo.
If you do an update of your Odoo in two weeks it should be fixed!

Regards,
Yenthe

**Comment by danger89** [comment]
'Memoriaa' and 'Welko' is still part of the latest daily: 10.0.20171008. How long does it take to apply the new translations or do I need to do something special?

**Comment by Yenthe666** [comment]
The translations have been synced today (https://github.com/odoo/odoo/commit/19eb19b92d6e28630fe62ca3e93c9c4e5bc89ee5) so if you do a git update now it should be fine as the Dutch fix should be in there.
