### ISSUE TITLE
URL Rewrite

### ISSUE THREAD

**Issue by inteslar** [odoo/odoo#19833]
Impacted versions:10.0

Steps to reproduce:i want to change url

Current behavior:https://mydomain.com/page/contact-us

Expected behavior:https://mydomain.com/contact-us

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @inteslar,

The Github tracker is only for bugs in the official code, it is not the place to ask questions about custom development. Please do ask this question on the official help forums (help.odoo.com).
You might want to look at slug URL rewrites by the way.

Regards,
Yenthe
