### ISSUE TITLE
Quotation/Sales Order print has duplicate address

### ISSUE THREAD

**Issue by reyelts3101** [odoo/odoo#19843]
Impacted versions: 10

Steps to reproduce:
1. Open a Quotation or Sales Order. 
2. Click the Print button.

Current behavior:
If the invoice and shipping addresses are the same, the heading "Invoice and Shipping Address" is printed following two copies of the address.

Expected behavior:
If the invoice and shipping addresses are the same, only one address should be printed with the heading "Invoice and Shipping Address". 

Video/Screenshot link (optional):
![salesorder](https://user-images.githubusercontent.com/32462470/31088855-53d70b84-a75f-11e7-8135-0eabc615c570.jpg)

I looked at the template (report_saleorder_document). It look like the extra copy is emitted by HTML starting at line 19. I didn't try it, but if the invoice and shipping addresses are different, it looks like three addresses will be printed.

**Comment by JayVora-SerpentCS** [comment]
@reyelts3101 Professionally, it needs to print all addresses considering it can be all different in real business case. 
And, https://github.com/odoo/odoo/blob/10.0/addons/sale/report/sale_report_templates.xml#L10 already handles that if the addressed are same (ofcourse by ID), it will print only one.
Should be closed @Yenthe666

**Comment by pedrobaeza** [comment]
Closing by the reason stated by @JayVora-SerpentCS
