### ISSUE TITLE
[11.0] Documentation links give 404 page

### ISSUE THREAD

**Issue by alexweggs** [odoo/odoo#19846]
Hi,
Links for documentions in master branch are in 404 error :/

Can you put good links in the project ?
Thanks a lot !!!

**Comment by Yenthe666** [comment]
Hi @alexweggs,

Thank you for your report.
Which ones are you referring too? Can you link an example please?

Regards,
Yenthe

**Comment by alexweggs** [comment]
Hi,
The links in the master branch, in the readme.md file :

https://www.odoo.com/documentation/master/setup/install.html
https://www.odoo.com/documentation/master/tutorials.html

Alex

**Comment by Yenthe666** [comment]
Hi @alexweggs,

Thank you for the update.
If I'm not mistaking these will be changed to 11.0 after Odoo 11 is launched (should be tommorow).
@mart-e can you confirm? Let us keep this open as a reminder.

**Comment by mart-e** [comment]
Hi !

Indeed, we will publish the 11.0 documentation in a few days but we should first update it to apply all the changes (e.g. python3).
Thank you for your patience.

**Comment by alexweggs** [comment]
Hi,

Thanks mart-e, any idea when the 11 will be launched ?

**Comment by Yenthe666** [comment]
It is launched earlier today.

**Comment by alexweggs** [comment]
Yes, good news, but links still in 404 :/

**Comment by Yenthe666** [comment]
The docs aren't updated yet. Give it a few days.
