### ISSUE TITLE
odt2txt.py output error

### ISSUE THREAD

**Issue by levivm** [odoo/odoo#1986]
Using odt2txt.py and this test file [link](https://www.dropbox.com/s/eavnukoyxkh028t/standardized_text.odt?dl=0)  
 Output should be something like this:
`the quick 
brown fox
jumps
over
the
lazy dog`

But I'm getting:
`the quick
brown fox
jumps 
over 
the 
lazy dog
jumps over the`

I fixed removing `text:list` from   `for val in["text:p", "text:h", "text:list"]` and getting the same result, I think that tag is not necessary.

**Comment by Yenthe666** [comment]
Hi @levivm ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
