### ISSUE TITLE
The auto_install of this module would make l10n_cn_standard unable to be selected in setup Chinese COA

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#19863]
https://github.com/odoo/odoo/blob/597ee1c58118bdba5238b4d25cd20467f73d02bd/addons/l10n_cn_small_business/__manifest__.py#L30

There're two modules: l10n_cn_standard and l10n_cn_small_business standing for different sets of COA in China, both of the modules depend on l10n_cn module. If the auto_install of 10n_cn_small_business is set to True, when you install l10n_cn, 10n_cn_small_business will be installed automatically. That means, for a single company instance, you can't select l10n_cn_standard, even you installed it.

**Comment by Yenthe666** [comment]
Please do add more information / background / a case / ...
This is a very short report 😉

**Comment by Yenthe666** [comment]
Closing as there has been no feedback.

**Comment by pedrobaeza** [comment]
@oliverzgy That's because he expected to have more information as a new comment, not editing your first comment. Any way, although the auto-install makes the module to install, you can still install the other one manually and configure the CoA you want, isn't it?

**Comment by oliverzgy** [comment]
Easy to close an issue without looking into it! That time once the small business COA installed automatically, you couldn't switch to another COA. @pedrobaeza, thank you for your kindness, indeed

**Comment by Yenthe666** [comment]
@oliverzgy my apoligies, I was indeed expecting to get a new response and didn't look at the original post again. Sorry for that. Thanks for reopening @pedrobaeza

**Comment by oliverzgy** [comment]
I don't want to blame anyone, fix the issue is the right thing  to do. In the latest commits, we can switch from the automatically installed small business to the standard COA. This may solve the issue, but still mislead the user that when the use select the standard COA to install, but the small business one is installed.

**Comment by pedrobaeza** [comment]
@qdp-odoo what do you think about this?
