### ISSUE TITLE
[11.0] Impossible to generate an expense sheet

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#19877]
Impacted versions:

11.0

Steps to reproduce:

See https://youtu.be/9jYY_XV2RrQ

Current behavior:

It's not possible to generate an expense sheet from expenses

Expected behavior:

We should be able to generate an expense sheet.

Video/Screenshot link (optional):

See https://youtu.be/9jYY_XV2RrQ

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

Thank you for your report!
I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/31217905-cfe49be6-a9b8-11e7-8345-8c10732491b9.png)
@KangOl perhaps from one of your forward ports?

Regards,
Yenthe

**Comment by adrienpeiffer** [comment]
Hum ... I check on http://271183-11-0-57f03f.runbot14.odoo.com. It doesn't work ... @KangOl Can you reopen this one ?

**Comment by KangOl** [comment]
This bug has now been fixed.
