### ISSUE TITLE
auth_ldap doesn't search users in nested OUs 

### ISSUE THREAD

**Issue by carlinux** [odoo/odoo#19874]
Impacted versions:
ODOO v8 , 
python-ldap 2.4.10-1
auth_ldap 8.0.1.0 
Debian Jessie

Steps to reproduce:
set up in LDAP AUTH module base DN:  "OU=USERS, DC=domain,dc=com" 
it doesn't find users in (for example) "OU=good_Users,OU=USERS, DC=domain,dc=com"
Just in the exact path 
Current behavior:
Above explained 
Expected behavior:
Recursively search for users in the nested OUs of a domain.

**Comment by Yenthe666** [comment]
Hi @carlinux,

Thank you for your report.
Odoo 8 is no longer supported officially and we're no longer fixing bugs in Odoo 8.
If you still face this in 9.0, 10.0 or 11.0 please do create a new report and we'll look into it!

Regards,
Yenthe
