### ISSUE TITLE
[10.0] Payment acquirer automatic payment reconciliation does not support multiple currencies

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#19886]
### Impacted versions:

10.0 (haven't checked other versions)

### Steps to reproduce:

- Install eCommerce app.
- Set default company currency to JPY.
- Set exchange rate.  e.g. 1 EUR = 130 JPY
- Configure Stripe payment acquirer with "Authorize & capture the amount, confirm the SO and auto-validate the invoice on acquirer confirmation" for Order Confiration, and Bank (JPY) for Payment Journal.
- Create a pricelist with EUR and assign it to the website.
- Purchase something in online shop and pay (10 EUR) through Stripe.  In Stripe, net amount is recognized as 120 JPY after conversion (i.e. Stripe is linked to a JPY bank account) from 10 EUR and deducting their fee.

### Current behavior:

- Payment transaction is created as 10 EUR (which is not incorrect)
- Payment (account.payment) is created as 10 JPY (10 from 10 EUR in invoice and JPY from the Payment Journal in Stripe payment acquirer), and journal entry and reconciliation with invoice are all messed up.

### Expected behavior:

There can be a few different approaches to handle this issue.

#### Option 1:

- Payment transaction is created as 120 JPY.
- Payment (account.payment) is created as 120 JPY (based on payment transaction) and reconciled with invoice, posting the variance of 10 JPY (with the company currency invoice amount of 130 JPY) as transaction fee.

*The handling of the variance mentioned above may technically not be correct depending on how you interpret the variance, and this option requires rather radical design changes.*

#### Option 2:

- Allow assigning multiple payment journals to a payment acquirer.
- Payment transaction is created as 10 EUR (no change from the current design).
- Payment (account.payment) is created as 10 EUR (10 from 10 EUR in invoice and EUR from the Payment Journal of the same currency as invoice in Stripe payment acquirer).

*This option is probably easier but requires setting up multiple journals for a payment acquirer according to available currencies, which may complicate the balance management of the accounts for the payment acquirer.*

#### Option 3:

- Payment transaction is created as 10 EUR (no change from the current design).
- Payment (account.payment) is created as 10 EUR (just apply the same amount and currency as the invoice regardless of the used journal).

*Not sure if this will cause some side effects as I believe Odoo does not expect inconsistent currencies between payment and assigned journal.* 

#### Option 4:

Give up on handling multi currencies with a payment acquirer with the setting of "Authorize & capture the amount, confirm the SO and auto-validate the invoice on acquirer confirmation", and show error when customer tries to select a payment acquirer whose journal currency is inconsistent with the order currency.   Document this limitation in related user docs.

**Comment by Yenthe666** [comment]
Hmm that looks off indeed. @qdp-odoo and @nim-odoo could one of you look at this?

**Comment by yostashiro** [comment]
It seems the issue has been fixed with this commit https://github.com/odoo/odoo/commit/875dd9221f80ea1b60cd9ee8a005d71246734a2b which is in line with Option 3 in my issue report.

I guess we can close this issue for now.
