### ISSUE TITLE
[11.0] account_cancel module does not activate cancel option in journal

### ISSUE THREAD

**Issue by augustosamame** [odoo/odoo#19888]
Impacted versions:

11.0 (works fine in version 10.0)

Steps to reproduce:

Install Accounting app.
Install account_cancel app. 
Activate debug mode
Navigate to Accounting Settings - Journals
Edit a Journal (ex. Cash)
Click on Advanced Configuration Tab

Current behavior:

Advanced Configuration Tab does not show checkbox to enable Account Cancel

Expected behavior:

Advanced Configuration Tab should show checkbox to enable Account Cancel for this journal.

As a matter of fact, there seem to be other options missing like checkbox for showing journal in Dashboard. These options, along with the account_cancel checkbox were visible under a Miscellaneous Title in v10 and now they're gone.

**Comment by Yenthe666** [comment]
Uhm it is there? Same for "Show journal in dashboard".
V10:
![image](https://user-images.githubusercontent.com/6352350/31217384-15846eee-a9b7-11e7-981b-8c2861ef950d.png)

V11:
![image](https://user-images.githubusercontent.com/6352350/31217402-25cd1ae4-a9b7-11e7-87b5-559ac2881c35.png)

Can you reproduce it on the latest runbot (runbot.odoo.com)? Have you tried updating your Odoo codebase?

**Comment by augustosamame** [comment]
It seems the Community v11 I got yesterday from the v11 branch is not the latest one?

git clone https://github.com/odoo/odoo.git -b 11.0

This is what I see. Even the UI is different so I will check my Odoo download and report back:

![image](https://user-images.githubusercontent.com/16038063/31227635-2833cbdc-a9a0-11e7-80d5-d8d27c48653e.png)

**Comment by Yenthe666** [comment]
Hi @augustosamame,

Please do try to update the Odoo instance or install a new one - it looks like something went wrong there. 😉 
Keep me updated!

**Comment by augustosamame** [comment]
This is so weird:

![image](https://user-images.githubusercontent.com/16038063/31227865-055f3654-a9a1-11e7-91a1-b80fa13620ac.png)

![image](https://user-images.githubusercontent.com/16038063/31227884-13dbcb5c-a9a1-11e7-9aeb-3d627ed2f707.png

Sorry for such a basic question, but how can I get the latest (stable) version 11 community code, preferrably via git?

I used this yesterday:

git clone https://github.com/odoo/odoo.git -b 11.0

**Comment by Yenthe666** [comment]
Hmm that all looks fine really, including your git command. @mart-e do you see anything off?

**Comment by mart-e** [comment]
Click on the "Activate the developer mode" link in your last screenshot and you should see it 😉

**Comment by mart-e** [comment]
The difference is that Yenthe is looking at the enterprise version and you are looking at the community version.
In version 11, the accounting is an enterprise version, so this is why you don't see all the options.
To see it you need to active the full accounting feature group in the settings.

**Comment by augustosamame** [comment]
Thank you for clarifying it in part. However, I don't understand the proposed solution: "you need to active the full accounting feature group in the settings". Where is this option located in the v11 community version? Can't find it anywhere.

**Comment by augustosamame** [comment]
Ok. Got it! The solution is to give extended Accounting permissions to the user. In debug mode, go to Users, Access Permissions Tab, Technical Configuration, and select the Accounting checkbox. After refreshing/relogging user will have access to Accounting Dashboard and the missing Journal Advanced Settings.
