### ISSUE TITLE
[11.0] PDF report print

### ISSUE THREAD

**Issue by fabioluna** [odoo/odoo#19887]
Hi,

I'm trying to implement a new report type, because I need to generate a pdf on the fly without wkhtmltopdf, I've created the following code.
https://github.com/Trust-Code/odoo-brasil/blob/11.0/br_boleto/reports/report.py#L16

But when it executes it throws the following error.

Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/home/fabio/projects/odoo/addons/web/controllers/main.py", line 73, in wrap
    return f(*args, **kwargs)
  File "/home/fabio/projects/odoo/addons/web/controllers/main.py", line 1503, in index
    action["report_name"], report_ids, report_data, context])
  File "/home/fabio/projects/odoo/odoo/http.py", line 116, in dispatch_rpc
    dispatch = odoo.service.report.dispatch
AttributeError: module 'odoo.service' has no attribute 'report'

What the correct procedure to implement this, since odoo.service.report was removed?

https://github.com/odoo/odoo/commit/3425752eaca236c1e4b4d616aa49b3faa6cfd957#diff-d366afc9386284f354116991f6cce54fL26

@smetl Could you help me on this?

**Comment by Yenthe666** [comment]
Hi @fabioluna,

Please note that the Github issue tracker is only for bugs or problems in the official code. This isn't the right place to ask questions about custom development really. Please do post this on the official help forums (help.odoo.com) - plenty of people can help you there!

Regards,
Yenthe

**Comment by danimaribeiro** [comment]
@Yenthe666 Indeed is a bug:
This piece of code does not make sense anymore:
https://github.com/odoo/odoo/blob/11.0/odoo/http.py#L116

As odoo/service/report.py was completely removed.

**Comment by smetl** [comment]
Mistake fixed on 11.0 at revision https://github.com/odoo/odoo/commit/c23ef9a9b6e2c7a43b3f98bdbd85e6c7b2b0ba74

Thanks!

**Comment by Yenthe666** [comment]
Sorry for the confusion @danimaribeiro.
Thanks a lot for the fix @smetl!
