### ISSUE TITLE
No module named 'PyPDF2'

### ISSUE THREAD

**Issue by alexweggs** [odoo/odoo#19883]
Hi, 
Try to launch odoo-bin in 11.0v but always same error of 
No module named 'PyPDF2' 

But module is install, got his error on a ubuntu 17.04
Any ideas ?

Thanks a lot!

**Comment by gdgellatly** [comment]
Without stating the obvious, install pypdf2

**Comment by alexweggs** [comment]
ok, sorry for that one, i missed the fact it was python3....

**Comment by dgamarnik** [comment]
I pip installed PyPDF2  on Windows and I'm still getting this error. Any solutions?

**Comment by Reema-Mansour** [comment]
the same issue I pip installed PyPDF2 on windows and I'm still getting this error [ModuleNotFoundError: No module named 'PyPDF2']

**Comment by Reema-Mansour** [comment]
the issue has been solved. the problem was that I had installed  PyPDF2 in another environment using anaconda So, you have to activate the environment the you are using then install PyPDF2 by 
pip install PyPDF2

activate the environment by
conda activate env_name
