### ISSUE TITLE
[11.0] Pdf layouts issues

### ISSUE THREAD

**Issue by alexweggs** [odoo/odoo#19885]
Hi, 
When i print a quote or invoice, the pdf has no logo, and not same structure as the chosen template (wront typo, backgournd color and borders)

I had last wkhtmltopdf version and i tried with the 0.12.1, i've got the same problem.
I tried to add the report.url parameters (http://localhost:8069) but it doesn't solved my problem.

Thanks a lot !

**Comment by Yenthe666** [comment]
@mart-e it does seem off under some circumstances. Logo's don't always come true, not the whole templates comes through, ... can you test it please?

**Comment by alexweggs** [comment]
Here is a generated PDF (second pdf model sets)
No logo, wrong fonts, wrong backgrounds etc...

[Quotation - SO003 (1).pdf](https://github.com/odoo/odoo/files/1395205/Quotation.-.SO003.1.pdf)

**Comment by alexweggs** [comment]
Hi,
After the today update there are some changes, fonts seem ok, but still not got logo and some background and styles still missing

**Comment by mart-e** [comment]
The logo is be fixed at 1df6f4c7. You _must_ adapt your reports from previous versions to work in v11.

Closing but if it does not solve the issue, please give an example of report configuration, saying "it does not work" is not very informative.

**Comment by alexweggs** [comment]
Thanks for informations but still got no logo and no good styles.
If i don't make any mistake, i've chosen a template from the 4 available, fill all fields for my company, and my logo.

What can i give you as more informations ti help resolving that issue ? 

What do you mean "You must adapt your reports from previous versions to work in v11" ? I'm from a clean install for the v11 and want to use built in PDF templates.

Thanks a lot !

**Comment by mart-e** [comment]
Which style have you chosen? Is there any customization?
I did not understood you are using a specific style, it looked like customized.

What we need, is enough information to be able to reproduce the problem on our side. You can try on the [runbot](http://runbot.odoo.com/runbot) to try on the latest 11.0 version to give us a step by step.

**Comment by alexweggs** [comment]
When i'm in "Sales" i go on "Configuration" and "General settings".
Here, in "document templates" i chose the one i want to have, named "box".

That's it ! When i print a report, the layout is not the same.

**Comment by lukebranch** [comment]
@alexweggs ,

I encountered the same issue, i'd suggest that you manually edit each of the views that were updated in that commit that (@)mart-e mentioned here:

https://github.com/odoo/odoo/commit/1df6f4c74151d012f9ff784cef6eea58a5ac3b9e

inside the UI of your database. I believe the views in your current DB don't include the changes in this commit, and therefore you are still experiencing the old behaviour.

You can just upgrade the related modules, however a quick fix for now would just be to update the views manually in the UI with the above commit.

**Comment by alexweggs** [comment]
@lukebranch ,

Thanks for that, but still same problem after update the views in the commit :/

**Comment by malexgp46** [comment]
Hi alexweggs, I have the exact same problem, did you find a solution?

**Comment by alexweggs** [comment]
@malexgp46 nope it's too bad i have to use another tool !

**Comment by Bedo1212** [comment]
Guys i am facing the same issue with Ubuntu server only on windows server it is fine  . Any news  ??
