### ISSUE TITLE
'TypeError: cannot marshal None unless allow_none is enabled' when action_cancel called for a sales order

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#19889]
I'm using `Odoo 10.saas~14+e (Enterprise Edition)`. When I call `action_cancel` on a `sale.order` via the XMLRPC api, I get the following error response:

```
  File "/home/odoo/src/odoo/saas-14/odoo/service/wsgi_server.py", line 57, in xmlrpc_return
    response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
```

My call to the API looks like this:

```
self::$modelClient->execute_kw(self::$db, self::$uid, self::$password,
                               'sale.order', 'action_cancel', [8696], $keywordArgs, []);
```

Is there anyway to fix this? Is this response intentional behavior?

**Comment by Yenthe666** [comment]
Hi @flyingL123,

Thank you for the report.
The XMLRPC protocol doesn't allow `None` values to be passed on though. You would have to filter out the `None` values and replace those by `False` statements.
Alternatively you can add `allow_none=True` to the parameters of `rpc.py` but I would go with converting them to be honest.

Regards,
Yenthe

**Comment by flyingL123** [comment]
Thanks @Yenthe666. Just to clarify, I am calling the API from a PHP script on my own server. We're using a hosted version of Odoo Sass, so we don't have access to the actual Odoo source code. Does this mean I have no way around this issue since I can't access the actual XMLRPC code?

Or is there some way to convert `None` to `False` before this error gets thrown?

**Comment by xmo-odoo** [comment]
@flyingL123 these have been fixed in 9.0 (as it's the oldest supported version where they appear), the fix should be forward-ported soon-ish.

**Comment by abuvanth** [comment]
passing without None values via xmlrpc solved this error....

**Comment by flyingL123** [comment]
Hi @Yenthe666, I just came across this same problem in another location. If I call the `process` method on a `stock.immediate.transfer` object, I get the same "Cannot marshal None` error. I can see in the source code that `process` does have a return value:

https://github.com/odoo/odoo/blob/saas-14/addons/stock/wizard/stock_immediate_transfer.py#L22

Can this be fixed?

**Comment by Yenthe666** [comment]
@KangOL couls you handle this one too?

**Comment by flyingL123** [comment]
@Yenthe666 I think this is already being addressed. I submitted #21266  for it.

**Comment by Yenthe666** [comment]
Indeed. This should all be handled. :)
