### ISSUE TITLE
Odoo 11 repo missing 

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#19890]
Hello together , 

where I can find the Odoo 11 repo ,that I can install on CentOS ? 

Under nightly.odoo.com -> 11 , i can’t see it

**Comment by Yenthe666** [comment]
![image](https://user-images.githubusercontent.com/6352350/31224187-3baf5d8e-a9cd-11e7-9394-845c685aeae2.png)
Am I missing something or is it just there? CC @mart-e

**Comment by F3000** [comment]
I see only that when I click on 11.0 Stable . 

But when I follow the instructions to install 11.0 , there is one line where I have to add the repo . 

Under nightly 10.0 there is another entry Odoo.repo. Do you have an idea ?

**Comment by F3000** [comment]
![aa5824bb-8204-4642-be08-a4cba6ac4d27](https://user-images.githubusercontent.com/8161283/31224509-80f1c4da-a9ce-11e7-96f3-c3f687679249.png)

**Comment by F3000** [comment]
Can nobody help me ?

**Comment by mart-e** [comment]
It should be published soon.
However, I am afraid CentOS will not work, the packages provided in the repositories are too old. We advise the latest Fedora version for minimum packages.

**Comment by F3000** [comment]
Is there no way to support CentOS like with version 10 ? 
We use only CentOS in the company  :(

**Comment by mart-e** [comment]
You can always make a source install or make sure to have the minimum [requirements](https://github.com/odoo/odoo/blob/11.0/requirements.txt) but I think CentOS does not ship python 3.5 (to check)

**Comment by F3000** [comment]
Ok . Python 3.5 is the minimum ? 

I can install it Woche EPEL Release etc. .

**Comment by F3000** [comment]
I have tried with odoo 3.5 

i use yum localinstall odoorepro

But than i see the error in the picture 
![unbenannt](https://user-images.githubusercontent.com/8161283/31429071-41229ee4-ae6d-11e7-95c6-79f59b95d5de.PNG)

I have installed all depencies

**Comment by d-fence** [comment]
@F3000 Do you mean on Centos ?
Can you explain the steps ? Did you use EPEL repos ?
I have to mention that I also tried the latest Centos with EPEL repos and friends but I did not manage to make it work. That's why we suggests Fedora26.

**Comment by F3000** [comment]
First i have installed all python3 depencies with pip3.5 
. But i only see this in my picture. 

the odoo RPM Repo is missing , so i cant install it with this

**Comment by d-fence** [comment]
@F3000 the problem is that installing python3 packages with pip does not fullfill the RPM package dependencies. You need the RPM versions of the python3 packages to be able to install the Odoo RPM package. We are working on the rpm repo but it will not work with CentOS 7. CentOS 7 is outdated for RPM python3- packages.

**Comment by F3000** [comment]
ok i will try it with fedora 26 . 

On fedora can i install odoo with localinstall ?

**Comment by d-fence** [comment]
@F3000 yes, it should work out of the box

**Comment by F3000** [comment]
ok thanks . I will reply after testing . But one problem i have is my company . We use only centos for the Servers.

When i understand it right , there must be a newer version from Centos that support python 3 out of the box ?

**Comment by d-fence** [comment]
AFAIK, the CentOs project is an unbranded RedHat and RedHat follows the Fedora baseline. So, the next RedHat should be based on Fedora 26 and then the CentOs version should follow. But I cannot give a timeline :-)

**Comment by F3000** [comment]
a i understand :) 

so you wait until that or did you try to make it compatible with the centos version at the moment ?

**Comment by d-fence** [comment]
We tried hard to make our RPM package compatible but it did not work.
But Odoo could probably work on CentOS 7 **when installed from sources**

**Comment by F3000** [comment]
great . The installation guide is up to date on your website for the **install from source** ?

**Comment by d-fence** [comment]
@mart-e just pushed an update here: https://github.com/odoo/odoo/commit/f5b2a4b0f294b509171f559ba6a4b548da8cb728
So the documentation page should be updated soon:
https://www.odoo.com/documentation/11.0/setup/install.html

**Comment by F3000** [comment]
Thank you for your grat work 👍 

I will write back when i finished the install

**Comment by F3000** [comment]
![unbenannt](https://user-images.githubusercontent.com/8161283/31435948-9921a2a2-ae81-11e7-97b9-9cf4bbadd620.PNG)


Here i will get an error . I want to add the repo

**Comment by F3000** [comment]
So i have added the repo with : 

`dnf config-manager --add-repo=https://nightly.odoo.com/11.0/nightly/rpm/odoo.repo`

But after trying to install odoo  with `yum install odoo` there is a new error: Cannot sychronize the repo. Deactivated

Any idea ?

**Comment by d-fence** [comment]
Repo is fixed, it should work now.

**Comment by d-fence** [comment]
At the end of install you probably will have to add this package manually and enable/start Odoo
```bash
$ sudo dnf install python3-psycopg2
$ sudo systemctl enable odoo
$ sudo systemctl start odoo
```
I will update the rpm package soon, the missing package is a mistake

**Comment by F3000** [comment]
so repo is working fine . You should add the SElinux command to allow the connections. 
`firewall-cmd --zone=public --permanent --add-service=http`
`firewall-cmd --zone=public --permanent --add-port=8069/tcp`
`firewall-cmd --reload`

But when i want to open the webpage i see only Timeout in all browsers. 

Is there something missing in the FW ?

**Comment by F3000** [comment]
![unbenannt](https://user-images.githubusercontent.com/8161283/31448356-866b3182-aea4-11e7-86df-e60dfa4d9fb9.PNG)

i think the service was not probably started

**Comment by d-fence** [comment]
As you see it's the psycopg2 module that is missing. That's the reason of the timeout, the Odoo server is not even started.
I updated the RPM to fix that : https://github.com/odoo/odoo/commit/7d45ca23e1920e0c8e261cec92335c4efddf196a
You can try this command :
```bash
$ sudo dnf install python3-psycopg2
```
And then restart Odoo systemd service unit.
```bash
$ sudo systemctl restart odoo
```
I hope it helps

**Comment by F3000** [comment]
I have added the package and have the same error . In another trying i didnt have the error . 

Thanks i will install itwithe the new RPM. 

Do you have also a ansible extension for odoo ?

**Comment by d-fence** [comment]
@F3000 about the ansible extension, AFAIK no we have not.

About the rpm, you have to wait that the build with the 7d45ca2 commit is finished.

**Comment by F3000** [comment]
that is in every night ?

**Comment by d-fence** [comment]
Every morning, I just checked, it's in progress.

**Comment by F3000** [comment]
top . I will write back when i have tested again :)

**Comment by F3000** [comment]
I'm afraid now . 

When i install Version 10 with your instaructions , there is all fine . 
When i install Version 11 with your instruction i must stop at `yum install odoo`. 
I can add the repo , but it doesnt find the package odoo ;(

Any idea

**Comment by d-fence** [comment]
I'm going to check of all went after the migration well this night.

**Comment by d-fence** [comment]
Ok, it's fixed.
I think that 'yum' is deprecated. You should use 'dfn'.
I'm going to update the documentation accordingly

**Comment by F3000** [comment]
thanks i will will look at this

**Comment by F3000** [comment]
Repo is working fine . But i see online a timeout in Firefox after installing

**Comment by d-fence** [comment]
Hi, that's probably because it takes time to start for the first time.

**Comment by F3000** [comment]
I waiting now one hour after starting the odoo service. 

`systemctl status odoo` show following : 
![unbenannt](https://user-images.githubusercontent.com/8161283/31602961-eafe0b34-b25e-11e7-95f0-51f2750a2572.PNG)

campared to odoo 10 , there i can start firefox directly after starting the service. I think there is not all components ok . 

Do you have a running version 11  for testing ?

**Comment by d-fence** [comment]
I just tested again and it seems to work fine. Can you check in /var/log/odoo/odoo-server.log ?
I tested on Fedora 26. Installed through dnf.
I had to wait a few seconds and then the browser is redirected to "/web/database/selector" as expected.

**Comment by F3000** [comment]
[odoo-server.log](https://github.com/odoo/odoo/files/1386932/odoo-server.log)

Here is the file

**Comment by d-fence** [comment]
Well, it seems that it works but nobody tried to connect. Maybe your firewall is blocking access before reaching the server ?
Is you firefox on the same machine ?

**Comment by F3000** [comment]
I have installed a VM with virtual box. The VM get the IP from the local network . FF is on the same machine as the VM

**Comment by d-fence** [comment]
You should chek if a firewall is not blocking port 8069 on your VM.

**Comment by F3000** [comment]
i have made the exception for port 8069

`firewall-cmd --zone=public --add-port=8069/tcp --permanent`
`firewall-cmd --reload`

Right ? 

SeLinux i have disabled

**Comment by d-fence** [comment]
You should see lines with gets like "GET / HTTP/1.1" 200 -" in your log file.
If you don't, it's probably because something prevent your browser to reach the server.
Probably the firewall.

**Comment by F3000** [comment]
hmm ok . It's curios . Odoo 10 is working fine with the same setup . 

Is the a way how to test the installion withethe enterprise version ?

**Comment by gdgellatly** [comment]
Or virtualbox network adapters. They can be finicky when connecting from
same host as vm. Sometimes  need an explicit forward set up to pass
traffic.

**Comment by gdgellatly** [comment]
Maybe conf file related as well. I had an issue other day with xmlrpc port
renamed to http port. Worth checking anyway.

**Comment by d-fence** [comment]
Sure, you should test the whole network things first, the usual way.
start to ping from host to vm and if it does not work, resolv this first problem.
If you don't see anything in your firewall logs, double check your VM network settings.

**Comment by F3000** [comment]
Can you send me a VMware package ? So i can better test :)

**Comment by d-fence** [comment]
@F3000 It seems difficult. I don't use VMware. Further more, I think that you may experience the same problem if your firewall or VM system configuration prevent you to send HTTP request the Odoo instance running in the VM.

**Comment by Yenthe666** [comment]
This is out of scope of the bug itself too to be honest. For installation, configuration and implementation you should look at the guides:
https://www.odoo.com/documentation/11.0/setup/install.html
https://www.odoo.com/documentation/user/11.0/db_management/db_premise.html
http://www.odoo.com/documentation/11.0/setup/deploy.html

**Comment by emilianoavendano** [comment]
Hello, Colleague
I am involved in the same thing, but when I solve it, I will share the experience.
MY environment is Centos7 Python 3.6.3 I think that the dependencies will have to be installed one by one, but that's where I'm entangled, for example:

_rpm -ihv odoo_11.0.latest.noarch.rpm  -i
error: Error de dependencias:
python3-babel es necesario por odoo-11.0.post20171027-1.noarch_

but if I try to install that dependency babel from pip3 I get this:

_pip3 install babel
Requirement already satisfied: babel in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.6/site-packages (from babel)_

**Comment by d-fence** [comment]
I think that if you go the 'pip' way, it's preferable to install from sources instead from 'rpm' package.
The package manager will never have its dependencies satisfied with 'pip' installation.
