### ISSUE TITLE
[I18N] Error in content translation using es_VE

### ISSUE THREAD

**Issue by fernandoparada18** [odoo/odoo#19895]
Impacted versions: 8.0

Current behavior: When installing the es_VE translation, translate the word "or" in English for the following content in Spanish "¡el módulo base no puede ser cargado! (consejo: verifica el addons-path)".

Expected behavior: With the installation of the es_VE translation you should translate the word "or" from English to "o" in Spanish.

Screenshot link:

https://www.dropbox.com/s/vcdh1y3mjtxh78h/1.jpg

https://www.dropbox.com/s/2krepa27b7sbuf8/2.jpg

**Comment by Yenthe666** [comment]
Hi @fernandoparada18,

Thank you for your report.
As mentioned on the PR the support for 8.0 has ended so I'm closing this because of that. Sorry.

Regards,
Yenthe
