### ISSUE TITLE
[11.0] odoo v11 developer mode installation error < No module named packages >

### ISSUE THREAD

**Issue by vimit** [odoo/odoo#19897]
i had this bug , i have all python packages installed
![bug1](https://user-images.githubusercontent.com/32547704/31235302-139ad136-a9e9-11e7-8aa0-f0e8c18f70c2.jpg)

![bug2](https://user-images.githubusercontent.com/32547704/31235301-13974ab6-a9e9-11e7-967d-f2dccb75f7c0.jpg)

**Comment by totalard** [comment]
I got the same

**Comment by Yenthe666** [comment]
Hi @vimit,

Can you give more information please?
Is this on a community version? How does your config file look? Did you customize anything?

Regards,
Yenthe

**Comment by gdgellatly** [comment]
Use python 3.

**Comment by Yenthe666** [comment]
Ohh good catch @gdgellatly.
@sle-odoo I guess your question is already answered - it looks like 2.7 won't work out of the box anymore. 😉

**Comment by vimit** [comment]
I'm using community version, and i didn't change any thing in config file
I changed to python 3 and i get this message
![bug3](https://user-images.githubusercontent.com/32547704/31269049-c4bf8096-aa76-11e7-96f4-73151306ec9a.jpg)

**Comment by gdgellatly** [comment]
It's pretty unlikely you are using python 3, that's a python 2.7 traceback.

**Comment by vimit** [comment]
![python version](https://user-images.githubusercontent.com/32547704/31269327-e1912d72-aa77-11e7-8430-b5aa64426c8e.jpg)

**Comment by Yenthe666** [comment]
@vimit you have version `3.4.3` installed (and `2.7`). It is not because you have Python `3.4.3` installed that Odoo will automatically use Python 3.4.3.

**Comment by gdgellatly** [comment]
In any case, python 3.5 is minimum version. I'm running 11 on Ubuntu just
fine and have for a couple months so it isn't likely a bug, just deployment
issues.

**Comment by vimit** [comment]
the same with python 3.5
is it problem with PYTHONPATH in my system ?

**Comment by Derter** [comment]
I have the same error as OP. I have installed python 3.5 ontop of my python 2.7 environment. Its a VS and it has dependencies on python 2.7. How can I make it work? Thanks for any advice.

![bildschirmfoto 2017-10-06 um 15 55 23](https://user-images.githubusercontent.com/14194754/31281164-f636d56a-aaae-11e7-81fa-7b8a0c9f4287.png)

**Comment by JKE-be** [comment]
@rrahir urllib3 not compatible python 2, can you check alternative plz

**Comment by dmo-odoo** [comment]
Fixed with 6f6f3a44e63213a9d812fc480ac37a537efa5a05.
