### ISSUE TITLE
Odoo 11 debian nightly repository missing signature

### ISSUE THREAD

**Issue by xabitrigo** [odoo/odoo#19900]
**Impacted versions:**
Odoo 11

**Steps to reproduce:**

Ubuntu 16.04 machine, setup following https://nightly.odoo.com/

```
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list
apt-get update
```
**Current behavior:**
```
Ign:5 https://nightly.odoo.com/11.0/nightly/deb ./ InRelease
Get:6 https://nightly.odoo.com/11.0/nightly/deb ./ Release [1,188 B]
Hit:6 https://nightly.odoo.com/11.0/nightly/deb ./ Release
Ign:7 https://nightly.odoo.com/11.0/nightly/deb ./ Release.gpg
Reading package lists... Done
E: The repository 'https://nightly.odoo.com/11.0/nightly/deb ./ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
It seems `Release.gpg` is missing from the repository

**Expected behavior:**

Installation complete

**Comment by HNaga** [comment]
still not signed
W: The repository 'http://nightly.odoo.com/11.0/nightly/deb ./ Release' is not signed.

**Comment by Yenthe666** [comment]
@sle-odoo can you correct this?

**Comment by JKE-be** [comment]
@Yenthe666 

It is now @d-fence that manage this now ;)

**Comment by Yenthe666** [comment]
Oh right! @d-fence could you do that please? 😉

**Comment by d-fence** [comment]
Sure, it's on its way.

**Comment by larmar** [comment]
The InRelease is also giving a simmilar error in Ubuntu 17.04. 
But It seemed to work in 16.04.

**Comment by totalard** [comment]
Waiting

**Comment by d-fence** [comment]
Actually, the Debian build process is broken due to package signature. I'm working on it.

**Comment by d-fence** [comment]
The problem was that the 'Release' file needed for the Debian repository was signed with what is now considered a weak digest algorithm: sha1. Ubuntu 16.04 was giving a warning and Debian 9 refuse to use a repository with such a signature.
Although the fact that the preferred algorithms were in the right order, gpg signatures were always using sha1.
Finally, and as a reminder, adding the following config option in the gpg.conf file solved the problem:

personal-digest-preferences SHA256

**Comment by gp187** [comment]
This doesn't work and you haven't posted any solution.

**Comment by kondwani204** [comment]
it's giving me the same error, could you please provide a solution for this ASAP
