### ISSUE TITLE
 [10.0] Translation string missing from .po file

### ISSUE THREAD

**Issue by khishigbat** [odoo/odoo#19907]
Impacted versions: 10.0

Steps to reproduce:
Deleting an employee on HR module.

Current behavior:
The strings "The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set" and "object with reference:" on file  odoo/odoo/service/model.py are not included in .po files. Cannot translate them.

Expected behavior: 
The above strings to be included in their corresponding .po files and eventually on Transifex, so that we can translate them.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @khishigbat,

Thank you for your report.
Can you reproduce this on an official Odoo instance (at runbot.odoo.com)? Have you tried updating your Odoo? An example from the latest Odoo 10 in Dutch:
![image](https://user-images.githubusercontent.com/6352350/31265428-116e544c-aa6f-11e7-8a49-4ff4b3a56f0f.png)

Regards,
Yenthe

**Comment by khishigbat** [comment]
Hello @Yenthe666,

Thank you for your fast reply,
I'm unable to reproduce this on runbot.odoo.com, because my account is portal. (I signed in with my odoo.com account. And I'm not familiar with runbot, sorry.)
![portal](https://user-images.githubusercontent.com/29530738/31326844-6ab133a4-acfd-11e7-8348-5db1d5ceab77.png)

Here is the screenshot of the term search result from all mongolian odoo10 resources in Transifex:
![transifex](https://user-images.githubusercontent.com/29530738/31326493-5dd576e8-acfa-11e7-9dc9-bcc1a4f7835a.png)

And here is my odoo10 localhost instance, which is up-to-date:
![virtualbox_ubuntu 14 04 60gb_09_10_2017_13_52_20](https://user-images.githubusercontent.com/29530738/31326551-f3c16748-acfa-11e7-9c0d-343db8e5c6b4.png)
![eclipse](https://user-images.githubusercontent.com/29530738/31326657-d2237dc8-acfb-11e7-8f9c-08b0851663e1.png)

**Comment by Yenthe666** [comment]
Hi @khishigbat,

You can login with the user `admin` and the password `admin` on any runbot instance.

**Comment by khishigbat** [comment]
Thanks @Yenthe666 ,

Here's the runbot screenshot of the issue:
![runbot](https://user-images.githubusercontent.com/29530738/31327874-82f9a1d8-ad04-11e7-9a77-2c6aa0bd3a1e.png)

**Comment by Yenthe666** [comment]
@mart-e could you double check this? 😕

**Comment by khishigbat** [comment]
Can somebody please solve this?
I would be very happy. :)

**Comment by mart-e** [comment]
Fixed at 8f1d889e50e18d81db7d4e8bb0555513a2b1019c in 9.0
Will be ported to 10.0 soon and I will reexport the sources to update Transifex

**Comment by khishigbat** [comment]
@mart-e Thanks a lot!

**Comment by khishigbat** [comment]
Hi @mart-e,
I don't see the string on Transifex. When is it gonna be there? 
Thank you.

**Comment by mart-e** [comment]
@khishigbat today 😉

**Comment by khishigbat** [comment]
@mart-e looking forward to it.

**Comment by khishigbat** [comment]
@mart-e Thank you! :D
