### ISSUE TITLE
[11.0] Website cart setting - Promo is settable in community version

### ISSUE THREAD

**Issue by saeugetier** [odoo/odoo#19909]
Impacted versions: V11c

Steps to reproduce: When opening the cart view on eCommerce website there is a menu "customize". The option "Promo code" can be activated. The promotion code feature is an enterprise feature.

Current behavior: With activated promotion code option there is a server error 500 when viewing the shopping cart.

Expected behavior: Promotion code should not be selectable in community edition. Or there should be a prompt that the user has to change to enterprise version. Application should not crash when viewing the shopping cart.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @saeugetier,

Thank you for your report.
I've just tested this on the latest Odoo 11.0 without any problems:
![image](https://user-images.githubusercontent.com/6352350/31268395-5fcf0714-aa7c-11e7-908a-2e462b78e18d.png)
Can you reproduce this on an official Odoo instance (at runbot.odoo.com)? Have you updated your Odoo to the latest codebase?

Regards,
Yenthe

**Comment by saeugetier** [comment]
@Yenthe666 thanks for the quick reply. Obviously I wasn't using the latest version. Right after my git pull there was a commit which fixes the problem: https://github.com/odoo/odoo/commit/ea51b6b06f33fa97ace9c55bb86fceaeb60bb18a

**Comment by Yenthe666** [comment]
Awesome - best of luck!

**Comment by prakashkumar163** [comment]
Still facing the same issue in the latest pull, please help
    raise ValueError(message)
ValueError: Element '<xpath expr="//div[@id='right_column']">' cannot be located in parent view

Error context:
View `Promo Code`
[view_id: 1002, xml_id: website_sale.reduction_code, model: n/a, parent_id: 997
