### ISSUE TITLE
[Master,11,10,9,8][Security] model.transient : read_group() and read() have access of all records of all user

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#19904]
Impacted versions:
master, 11, 10, 9, 8

Steps to reproduce:

- use SQL code to generate lines on transient model, with create_uid = 1.
- connect with an other uid
- go on the tree view of this model
- you see no record
- BUT group by and pivot works

Current behavior:
any other user can see with pivot or group by some information

Expected behavior:
any other user cannot see data

Start of solution :
It seems the function `read_group` have no filter about the create_uid during the query for the transient model.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/16716992/31256826-18ef9ef4-aa35-11e7-84ab-0420802b90a5.png)

cc : @sylvain-garancher 

https://github.com/odoo/odoo/pull/20328

**Comment by Yenthe666** [comment]
Hmm perhaps something for you to check @odony?
