### ISSUE TITLE
Wrong partner_id store in account_invoice_line database after set a new customer in invoice

### ISSUE THREAD

**Issue by browseinfo** [odoo/odoo#1990]
Impacted versions: 7.0

Steps to reproduce:
in latest trunk go to Accounting > Customer invoice
Create a invoice with account invoice line
Click On "Save" Button.
Now current invoice edit record
and change a Customer
Click On "Save" Button. 

Current behavior :
in database customer_invoice_line table partner_id not change after set a new Customer

Expected behavior :
in database customer_invoice_line table partner_id change as per latest Customer set in account invoice

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
