### ISSUE TITLE
Google Analytics Not Tracking Ecommerce Revenue Accurately

### ISSUE THREAD

**Issue by jreed63119** [odoo/odoo#19918]
Impacted versions: 11?

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

FYI NOT a developer. This seems like it should be easy. Google Analytics is not tracking revenue accurately. Some of the revenue is being tracked. I added my Google Analytics UA number to Odoo. Where can I add the JS to track ecommerce?

**Comment by Yenthe666** [comment]
Hi @jreed63119,

Thank you for your report. Could you please add more information and details about what exactly doesn't work or is wrong according to you?

**Comment by JKE-be** [comment]
@jreed63119 

Hello, you just need to provide de UA,

The tracking code is already implemented by default.
(https://github.com/odoo/odoo/blob/11.0/addons/website_sale/static/src/js/website_sale_tracking.js)



Best regards

**Comment by JKE-be** [comment]
No news ! 

Don't hesitate to complete with more information and ask to reopen the issue if needed.
But while we have no news, we consider that all is working fine now.

See here what we watch about the e-commerce api: https://github.com/odoo/odoo/blob/11.0/addons/website_sale/static/src/js/website_sale_tracking.js)

**Comment by PabloRC1985** [comment]
Hi There,

We cannot track any conversion in this website https://www.reketec.com/ with Odoo 11.0 (Versión Community). We can track everything except conversions. Any idea of where could I start trying to debug this?

Thank you very much in advance

**Comment by PabloRC1985** [comment]
I checked in google analytics community, and they say the code should be much higher:
https://support.google.com/analytics/thread/5397441?hl=en
I´ll try to change the xpath expresion to insert google script before the wrap wrap ID instead of after and I´ll update with the results

**Comment by PabloRC1985** [comment]
Unfortunately this didn´t did the trick, it still doesn´t track conversions... Anyone has more ideas?

Best Regards,

Pablo

**Comment by JKE-be** [comment]
1. be sure to not use ublock / adblock /...
2. be sure to have the UA-xxx configured in your website (I just checked, it is ok)
3. check on the confirmation page after the payment, that you have a element that math the selector:
`.oe_website_sale div.oe_website_sale_tx_status`
4. check that the json controller /shop/tracking_last_order/ return a 200

You can check in your debugger, if the vpv and ecom:query are well sent to google

I just checked on runbot, and it seems to work as expected.

track_ga is a custom function in odoo that use ga()
```js
    function track_ga() {
        website_ga = this.ga || function(){};
        website_ga.apply(this, arguments);
    }
```

**Comment by PabloRC1985** [comment]
Thank you very much JKE-be for your answer.
1. Good
2. Good
3. We are currently checking this. Our confirmation page is:
https://www.reketec.com/payment/redsys/result/redsys_result_ok
4. We are not familiar with runbot and we don´t know how you checked that.

Thank you very much in advance

**Comment by Yenthe666** [comment]
@PabloRC1985 you can find the runbots at runbot.odoo.com - it holds builds of all major Odoo releases and you can login on any build with "admin" as password and username.

**Comment by PabloRC1985** [comment]
According to Analytics help the code should be INSIDE the head tag. I wonder how that could affect, but i´ll try it putting inside in the position of the xpath expression:
https://support.google.com/analytics/thread/5397441?hl=en
![Captura](https://user-images.githubusercontent.com/18579062/57468366-95717100-7284-11e9-9e83-7247566fe5c9.PNG)

**Comment by JKE-be** [comment]
It will no change anything for you to change where you insert this code.

Double check that your flow go to the /shop/confirmation page.
If not you need to have the class .oe_website_sale div.oe_website_sale_tx_status on your own custom confirm page.

I dont try a full flow, but I just going on the link that you provide and you don't use this class.

**Comment by PabloRC1985** [comment]
JKE-be thank you very much, we´ll try that with our developer since that´s out of my reach...

**Comment by PabloRC1985** [comment]
Ok, We have added the class in https://www.reketec.com/payment/redsys/result/redsys_result_ok, now we have to wait and see if it worked. We´ll update with the results.

Thanks again for your support.

**Comment by PabloRC1985** [comment]
JKE-be you were completely on point, that fixed the problem and now analytics tracks conversions.

Thank you very much.

Take care,

Pablo

**Comment by PabloRC1985** [comment]
Hi there again, the problem is not fixed, sometimes Analytics sees more money, sometimes Analytics sees less money (sometimes it seems like it doesn´t track some of the transactions), but in general it does things right 28% of the time overall it counts a 64% more revenue than in real life.

¿Any idea of where to look in order to fix the problem?

Best regards,

**Comment by JKE-be** [comment]
For the missing transaction, not surprising ... ad block probably!

For wrong amount, except track yourself the push notification during a flow to detect what happens... no idea ...

Jeremy Kersten

**Comment by PabloRC1985** [comment]
Thanks Jeremy, we will check that (Y).
