### ISSUE TITLE
MRP: Product Cost Structure decimal precisions

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#19919]
**Impacted versions:**
Odoo CE - 10.0

**Steps to reproduce:**
Setup MRP, Product BOM, on database decimal precision set 3 digit on cost price.

**Current behavior:**
The decimal precisions for the quantities, cost/supplier price per unit of measure were not respected. It was always set to 2 digits, whatever the configuration in the database decimal precisions.

**Expected behavior:**
Use the defined precision (3 digits) for cost price report.

Video/Screenshot link (optional):

![2017-10-06-160535_828x142_scrot](https://user-images.githubusercontent.com/7444518/31307876-070fdd36-ab32-11e7-860d-fecddec8677d.png)
![2017-10-06-160552_868x143_scrot](https://user-images.githubusercontent.com/7444518/31307878-090d88d6-ab32-11e7-9bcf-9f955d024bef.png)
![2017-10-07-073629_543x273_scrot](https://user-images.githubusercontent.com/7444518/31307900-48c9ec80-ab32-11e7-962b-0e9f4942daae.png)

**Comment by Yenthe666** [comment]
Hi @Ark74,

Thank you for your report!
@jco-odoo could you have a look at this? I believe we should look at the decimal precision.

Regards,
Yenthe

**Comment by pimodoo** [comment]
@sle-odoo

**Comment by sle-odoo** [comment]
@Ark74 
Thanks for your report.

The quantity is now formatted according to the unit of measure decimal precision. However the cost won't be, it is computed with the "price_unit" field on the move which doesn't use the product price decimal precision, so imo it doesn't make sense to change its format. I think formatting this field according to the current currency does makes sense, so i'll keep it like that.

Regards

**Comment by sle-odoo** [comment]
see rev 4e0367c611919e924f5a9fd68d46737e622b1d8c

**Comment by Ark74** [comment]
Hi thanks for taking the time to check this issue.
Could you tell me where can I find rev 4e0367c611919e924f5a9fd68d46737e622b1d8c ?

Cheers!
