### ISSUE TITLE
[11.0] Create or edit contact / company: "Account Receivable, ..." missing

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#19912]
Impacted versions:
11

Steps to reproduce:
-- create a contact / company from contacts manager
or
-- create a new sale order create customer 

Current behavior:
Account Receivable, Account Payable fields are not visible to set any information.

Expected behavior:
Make fields visible for editing data

Video/Screenshot link (optional):
![screenshot from 2017-10-06 13-50-45](https://user-images.githubusercontent.com/6930079/31274880-9a319374-aa9d-11e7-893f-07bff47bb046.png)

**Comment by Yenthe666** [comment]
Hi @ddfs,

These fields are available under the tab "Invoicing":
![image](https://user-images.githubusercontent.com/6352350/31275440-7b2bc20c-aa97-11e7-9e77-b51e09d6d0e9.png)

Regards,
Yenthe

**Comment by ddfs** [comment]
@Yenthe666 this is related to res.partner.

**Comment by Yenthe666** [comment]
Hi @ddfs,
Okay I've been a bit to fast. Do you mean this (taken from V10)?
![image](https://user-images.githubusercontent.com/6352350/31275923-99a81670-aa99-11e7-9bd5-290cfcad709d.png)
![image](https://user-images.githubusercontent.com/6352350/31275934-a7b424c0-aa99-11e7-821c-4a3b923907e8.png)

**Comment by ddfs** [comment]
from V11 and this warning pops up when no i10n_xx is installed but sale, invoicing etc all installed.
in earlier versions installation of i10n_xx packages were prompted to install. i guess that is the issue.

**Comment by Yenthe666** [comment]
Gotcha, sorry for the confusion. @mart-e perhaps we have to prompt this again?

**Comment by edsersolis** [comment]
Haven't tried it on CE but on EE it works just fine. Did you make sure that you have installed your corresponding localization?

**Comment by intero-chz** [comment]
@Yenthe666 IIRC that issue will also fit to Odoo V10. Without l10n_xx module installed there are no accounts to set on partners, what will throws this warning on every create or write on res.partner.

**Comment by SnakeDoc** [comment]
For now, you can fix this easily by selecting a Package under Fiscal Localization. This wasn't entirely obvious to me, as someone new to Odoo.

Settings --> Invoicing --> Fiscal Localization --> Save

[https://image.ibb.co/gCAhT6/fix_error.png](https://image.ibb.co/gCAhT6/fix_error.png)

**Comment by ddfs** [comment]
@SnakeDoc since you are new to odoo and other things, it is good to read the following threads before your comment.

**Comment by mart-e** [comment]
I am not sure to get your issue. You need a chart of account to use sale & purchase modules.
However, when you create a new Odoo install, it is automatically installed based on your country.
If you create another company, you need to specify it manually though.

**Comment by ddfs** [comment]
the problem is that not installed automatically and causes this case. in v8 didnt face such issue. so this probably left from ee when trimmed out for ce.

**Comment by mart-e** [comment]
This is the part I would like more information about. It _should_ be installed automatically (based on the country you have specified).
How do you install your db and modules? What are the steps?

The goal is that, in CE, all the accounting part is silent and done automatically. No wizard asking you to chose to a chart of account.

**Comment by ddfs** [comment]
country: Finland, no i10n is available.

db setup is done on init via nightly packages.
modules installed from admin panel. modules from nightly package too, local.

**Comment by mart-e** [comment]
I just tried with a fresh v11, Finland as the country. I just installed the "sale" module and got the generic chart of account as expected. Creating a new contact was working fine.

**Comment by SnakeDoc** [comment]
For me, it was installed automatically, but not enabled/selected. In the screenshot I provided, I had just then clicked the drop-down and selected it (there was only one option available, but it wasn't active). After selecting it and Saving, this error went away for me.

@ddfs honestly, not sure what you're implying. I may be new to Odoo, but that doesn't make my 2 cents any less valuable, especially when it may help others with a similar issue for now until Odoo can resolve this upstream. Snark less next time please.

**Comment by SnakeDoc** [comment]
@mart-e What do you mean by "a fresh v11", did you install on a new OS, or just dropped the database and re-created it?

I "reset" my odoo today (dropped database in postgres), but did not uninstall the package from my server nor did I wipe the server (fresh install of the OS). Surprisingly I did not run into this issue while setting things back up again. Maybe there's something there... ?

I don't know enough about Odoo yet to know if the initial installation logs survived what I did... if so, I'd be happy to provide them if you point me in the right direction. Maybe they'll lend some clues to both my initial problem and @ddfs current problem (they seem related to me).

**Comment by mart-e** [comment]
What I am saying is that, I made the following:

Using the database manger, I created a new 11.0 community instance with Finland as the country
![screenshot-2017-10-23 odoo](https://user-images.githubusercontent.com/564822/31932875-dce4bbe8-b8a7-11e7-848f-71109870355f.png)

Just installed the sale app and tried to create a new customer. No issue met.

Don't worry, no need to uninstall Odoo or whatsoever but just make sure you are up to date (we have been correcting a lot of issues in v11 lately, be sure to use the latest version).
If you are using a package, check on [the nightly server](https://nightly.odoo.com/11.0/nightly/).

**Comment by fiee** [comment]
I got stuck by the same error, trying v10, until I got the idea to install an account system. I.e.
* new database, English/Germany (the same with German/Germany), no demo data
* installed Contacts app – works
* installed Invoicing (with or without Sales) – can’t save Contacts anymore; the required account fields aren’t visible. There was no hint to install an account system.

**Comment by mart-e** [comment]
@fiee this issue is for v11 where the accounting modules have changed, please open a new one if you have an issue on v10.
As said above, if you set the country, the chart of account should be installed automatically. Otherwise, you can just to the accounting settings.

**Comment by gralet** [comment]
Just to confirm in my case : I had the problem (with just CRM and Project installed) probably because I did not choose the country when creating the database.   I recreated a new database with a country choosen (Belgium) and no more problem.    I guess the other solution would be to install account module and set a chart of account.
