### ISSUE TITLE
[11.0] Does Odoo 11.0 Support PostgreSQL 10.0 (Released 05/10/2017)?

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#19924]
<h1>Impacted Versions:</h1>
Odoo 11.0

<h1>Steps To Reproduce:</h1>
N/A

<h1>Current Behaviour:</h1>
Odoo 11.0 appears to support PostgreSQL 10.0.

<h1>Expected Behaviour:</h1>
There are a number of major improvements included in PostgreSQL 10.0, listed in the release notes here:
https://www.postgresql.org/docs/10/static/release-10.html

It would be great to hear from the Odoo SA team if Odoo 11.0 officially supports PostgreSQL 10.0, or whether there are plans to officially support this PG version in upcoming releases of Odoo.

**Comment by gdgellatly** [comment]
@lukebranch While I'm not odoo, this is how it has gone for every single release in the past.

Yes it will work (obviously test first, and wait a few weeks for the inevitable minor bugfix release/issue reports), but only those **database** features that are present in the minimum recommended version and that the ORM actually uses.  The ORM -> psycopg2 -> postgres really is just generating very simple queries, so short of a severe bug in postgres 10 then there isn't likely to be an issue. (NOTE: There was a bug in a recent 9 release which did affect Odoo so it does happen)

A postgres release isn't like an Odoo release.  It doesn't introduce things that break existing features, and if they did it would be in those release notes.

So as a general rule, if there is low level database engine specific things i.e. conf file type stuff (like query optimizers, parallel execution, logging) then it is never visible to the ORM, so usually those new features are usable.  If it is database specific e.g. Table partitioning, special data type, row/field level security, materialized view, trigram index then no Odoo won't take advantage of it (as standard).

**Comment by Yenthe666** [comment]
Hmm this is a good question. I think we should ask an official statement from either @mart-e or @odony here. I'm quite sure it'll work though. If I have time I'll try this out too. ;-)

**Comment by lukebranch** [comment]
@gdgellatly ,

Thanks for the valuable advice. I have moved a test instance of Odoo 11.0e over to PG 10.0 and will run some automated testing. I believe PG 10.0 should work with Odoo 11.0 (and probably previous versions). It looks like there were some significant work done on parallel execution among other things in  PostgreSQL 10.0, so if we're able to take advantage of the performance improvements for Odoo 11.0 (and perhaps previous versions) I may start experimenting with it with new deployments.

@Yenthe666 ,

Thanks, it would be great to hear back from (@)mart-e or (@)odony once they have time to look into it.

**Comment by gdgellatly** [comment]
@lukebranch just be aware parallel execution is disabled by default in postgres (at least it was in 9.6 and I never heard it changed).  It needs setting in the conf file.  That said, I really don't think that parallel execution of index/heap scans and merge joins is going to be that much impact, compared to what parallel execution did for seq scans in 9.6.

**Comment by mart-e** [comment]
Hello,

As said @gdgellatly the new release of postgresql is mostly backwards-compatible. As psycopg 2.7 supports the version 10, we do support it officially as well, now that it is released.

It's unlikely to require PG 10.0 is a close future. We tend to stick to the PG releases on the latest Debian stable/Ubuntu LTS, as a way to simplify deployments. Xenial (Ubuntu 16.04 LTS) has 9.5 Stretch (Debian 9) has 9.6.

**Comment by lukebranch** [comment]
@mart-e,

Thanks for the confirmation.

**Comment by seyuf** [comment]
Hi *,
what is the official answer here? Cause odoo 11 is not working fine with postgres 10.4.
I m getting `psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update`
Supposed to be solved here https://github.com/odoo/odoo/issues/8585
@mart-e any help would be appreciated.

**Comment by mart-e** [comment]
@seyuf are you sure it is not really a concurrent update?
We are running with postgres >10 on production servers without issues.
Please open a new issue with the context of the error.

**Comment by seyuf** [comment]
@mart-e,
 indeed it seems to be linked to concurrent updates which is linked to postgres (may be not version related though).
Anyway, i found a patch it seems to be working so far https://bitbucket.org/xcg/base_res_users_streamline/overview.
Otherwise my instances are currently on aws:
 - Rds postgres 10.4
 - Nginx 5 workers if you want to test

**Comment by mart-e** [comment]
Strange, this module should no longer be useful.
Since 94a0bbed0a94e4bd34965c1466615d225ac8e509 (2015), the login is moved to another table so you don't have this issue of concurrent update during login.

**Comment by seyuf** [comment]
Humm I'm not sure that the patch fixes all concurrency issues i.e `This minimizes the chances of transactional conflicts`.
Also, i was having this kind of errors since i have increased the nginx and odoo workers numbers (from 1-2 to 5). 
It appeared first while loading a module with a lot of uninstalled dependencies, then when i was droping/creating new/old databases.

My odoo.conf 
```
db_host = xxxxxx
db_user = xxxx
db_password = xxxx
load = "web, dbfilter_from_header"
db-filter=^%d$
longpolling_port = 8072
workers = 5
limit_time_real = 1600
limit_time_cpu = 1600

limit_memory_hard =  2684354560
limit_memory_soft =  2560000000


proxy_mode = True

xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1

addons_path = /XXXXXX/addons,/XXXX/odoo-custom-addons

logfile = /XXXXX/odoo-server.log
```
