### ISSUE TITLE
[11.0] Previously logged on an Odoo 10 db then logging in always stops on 500 error.

### ISSUE THREAD

**Issue by FilippoIOVINE** [odoo/odoo#19927]
Steps to reproduce:
- version 11 just installed
- several odoo 10 DBs were already installed
- before installing odoo 11 I was logged to an odoo 10 db
- when tried to login then stop on 500 error loops (because incompatible odoo 10 db was chosen)

Forcing url /web/session/logout didn't fix (db is not forget), check file: odoo-11.0/addons/web/controllers/main.py to see code involved when logging out:
```
    @http.route('/web/session/logout', type='http', auth="none")
    def logout(self, redirect='/web'):
        request.session.logout(keep_db=True)
        return werkzeug.utils.redirect(redirect, 303)
```

Same behavior if:
- odoo 11 installed
- choose wrong db (odoo 10 db)
- 500 error loops

Only way to fix this issue is to clean the "session_id" cookie.

**Comment by gdgellatly** [comment]
That's weird? How would the v11 database user even see the v10 database?

**Comment by FilippoIOVINE** [comment]
here you can see first two DBs are from v10.

![image](https://user-images.githubusercontent.com/5149320/31307343-ef89bb9c-ab62-11e7-9b6c-fe39050a3f49.png)

**Comment by gdgellatly** [comment]
I think if you run same port and I'm assuming same db user for postgres for
2 different versions thats asking for trouble. I actually did that once by
accident, and it upgraded the database for me with a -u base. Was a lot of
manual database edits to fix that one.

**Comment by FilippoIOVINE** [comment]
I just updated my local version of Odoo to v11 (v10 has gone) and db selector was giving me list of local postgres DBs (including v10 ones).
So quite common case IMHO.
Just considering that if you wrongly select a v10 DB you got stuck in the 500 error loop if you do not delete its cookie.

**Comment by Yenthe666** [comment]
This is an implementation / configuration issue. Both the Odoo 11 and Odoo 11 should have a different user and those databases should be assigned to the correct user too.
