### ISSUE TITLE
[10.0] website_live_chat: Chrome lang spanish Latin America (es_419), channel_fetch_meesage- Faild Expected Singleton

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#19920]
Impacted versions:
10.0

Steps to reproduce:
At https://github.com/odoo/odoo/issues/18363 was reported issue related with es-419 lang
And were applied this fix
https://github.com/odoo/odoo/commit/6879409723184ed360043b7a2da11fcd725e5c4f

But that fix tiggers the next

This fix causes the following problem

keeping  lang es-419 in chrome browser
- First Open the live chat from website , be sure  you are not logged in (guest user)
- Second, Sign up/ Sign in
**- The live chat channel is not displayed**
- Finally logout and you will be able to see the live chat channel
![image](https://user-images.githubusercontent.com/10233975/31291974-3697eb52-aa97-11e7-9464-a1de278bbb94.png)

Current behavior:
RUNBOT INSTANCE http://269567-10-0-b80c7b.runbot9.odoo.com/0

At the runbot log
![image](https://user-images.githubusercontent.com/10233975/31291995-56cf471c-aa97-11e7-8851-7eb2e9345cb1.png)
Expected behavior:
Live chat being opened and fetched all messages

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hmm @mart-e this is a follow up of the previous one you fixed. Perhaps you can look at this one too?

**Comment by kebeclibre** [comment]
I think commit 7c486b4d0c84c04ac1a42b67484ff3383a69dc28 solves this issue
