### ISSUE TITLE
Responisve theme odoo 11

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#19929]
Impacted versions: 11

Steps to reproduce:

Current behavior: Is it available responsive backend theme in community odoo 11?

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @aspcsharp9,

Thanks for your report.
While Odoo tries to look at responsiveness and flexibility I believe we can conclude that the community version is not fully responsive and mobile. The enterprise version is though!

Regards,
Yenthe
