### ISSUE TITLE
[FIX/IMP] Non-updateable views based on changes in frontend editor are not properly maintained via module

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#19930]
**Impacted versions:**
All

**Steps to reproduce:**
In the frontend it is possible to change module maintained views in edit mode or via the HTML Editor. These views are marked as non-updateable and therefore will not be updated when the responsible module is upgraded. This is not fun for the same reason why the web studio does create a proper inheritance on the view in the backend.

**Current behavior:**
Frontend edit on module maintained views for the website, shop, etc. mark the views as non-updateable and destroy the possibility to maintain them automatically on module upgrade (mostly not an issue if the stable policy is not changing anything, but in reality it happens more often than we want, but still for a good reason and without breaking stable)

**Expected behavior:**
Do the right inheritance based on the content outcome in edit mode and do clearly communicate the consequences in the HTML editor or even make it a two-step action for the user and not black magic by doing it automatically. So, without marking a checkbox (this view will only be maintained in the database in the future or your changes will disappear in case you uncheck again on upgrade) it is locked to edit directly in the HTML editor.

@rco-odoo 
As talked yesterday I would appreciate if you could assign it to someone in your team or yourself to take care in the future. As this is a bigger task I guess I could only participate easily by reviewing and giving feedback. I am pretty sure this will make a lot of people's work easier and Odoo core even greater.

@Yenthe666 
Please be so kind and tag this as framework and wishlist for me too. Thx :-)

**Comment by Yenthe666** [comment]
So I did.
I've actually been hit by this a few times before too and it can be annoying.
In my opinion it should have a checkbox or two step flow to be sure.

**Comment by qsm-odoo** [comment]
Same idea as this: https://github.com/odoo/odoo/issues/15437 (solution suggested there is even simpler as does not require any change of framework). To be continued.

**Comment by wtaferner** [comment]
@qsm-odoo 
Thank you for pointing me to the other issue...was not aware of that one...Jairo had some really good inputs about this...it would be anyway nice if the editor can do the job at some point (clean is enough for the start) and also that versioning of content is possible as you know the user is always just playing as hard as possible and it would be awesome to be able to rewind or forward these content views easily ;-)

**Comment by JKE-be** [comment]
Duplicated of #15437
