### ISSUE TITLE
project_issue was dropped on Odoo 11?

### ISSUE THREAD

**Issue by ofssetpr** [odoo/odoo#19934]
I just found the 'project_issue'(Issue Tracking) module is missing on 'Odoo 11 Community Edition'. So, how to handle issues on this version?

Thanks.

**Comment by Yenthe666** [comment]
Hi @ofssetpr,

The project_issue module has been removed in V11.
It has moved to the 'Helpdesk' module, under which you can create issues (tickets):
![image](https://user-images.githubusercontent.com/6352350/31309868-d0fda14a-ab8d-11e7-9f03-95e6c85b961c.png)

Regards,
Yenthe
