### ISSUE TITLE
[11.0] Logo missing in all reports

### ISSUE THREAD

**Issue by milanpatel1519** [odoo/odoo#19942]
Impacted versions: 11.0

Steps to reproduce: Print Invoice report and check company logo in header.

Current behavior: Just square box is printing.

Expected behavior: Has to print image of logo.

Video/Screenshot link (optional):

Also check in runbot.

Link : http://269483-saas-18-iap-al-cd48a8.runbot9.odoo.com
[Invoice - INV-2017-0007 (1).pdf](https://github.com/odoo/odoo/files/1366654/Invoice.-.INV-2017-0007.1.pdf)

**Comment by Yenthe666** [comment]
Hi @milanpatel1519,

Thank you for your report. I've just tested this on the latest Odoo 11.0 and this does seem to be broken:
![image](https://user-images.githubusercontent.com/6352350/31317212-529bcb14-ac3d-11e7-8485-f2d7e2d21cc8.png)
@sle-odoo could you have a look?

**Comment by pimodoo** [comment]
@smetl I think this one is for you

**Comment by naglis** [comment]
Seems it happens because the [`'%s' % record.binary_field`](https://github.com/odoo/odoo/blob/c7ca783e242ba7963fbb847cb53c3b9be9203936/addons/web/views/report_templates.xml#L145) produces artifcats, eg. `"b'base64data'"` and due to these `b''` the image can not be rendered properly.

Possible fixes:
```xml
<img t-if="company.logo" t-att-src="b'data:image/png;base64,%s' % company.logo" class="pull-left"/>
```
```xml
<img t-if="company.logo" t-attf-src="data:image/png;base64,#{company.logo}" class="pull-left"/>
```
Less nice:
```xml
<img t-if="company.logo" t-att-src="'data:image/png;base64,%s' % company.logo.decode('ascii')" class="pull-left"/>
```

**Comment by smetl** [comment]
@xmo-odoo I think it's due to P3, can you have a look plz? Thanks!

**Comment by xmo-odoo** [comment]
It looks like this has been fixed (likely by @tivisse in 1df6f4c74151d012f9ff784cef6eea58a5ac3b9e)

**Comment by antillia** [comment]
My logos still do not show up although I've upgrade my odoo 11 to 20180120 CE. 

I checked the files in my addon folder to ensure that they had the latest commit to "Render correctly the base64 images in P3". 

The files are all updated but I still don't have the company logos showing.

Any help?

**Comment by antillia** [comment]
**This issue is still very active!!!!!!** Please reopen it as databases created before the bug fix are still being displayed without logos. 

If you don't want to reopen, at least look at the issue and give a reason for not reopening.

**Comment by tivisse** [comment]
Hi @antillia 

There's 2 ways to handle your issue:
- Update the ``base`` module. That implied to update all your modules. That could have some problematic side effects.
- Update the related templates by hand in the concerned modules (``event``, ...).

Having the code up-to-date in not sufficient as the templates have to be modified on the database.

Please open a ticket at https://www.odoo.com/en_EN/help with the needed information (database name, ...) and also a link to this issue. 

Our dedicated support team will handle your issue with great pleasure.

Have a nice day,

Yannick.
