### ISSUE TITLE
[11.0] : TypeError: this.editor.snippetsMenu is undefined when adding a new Point of Sale

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#19948]
Impacted versions:
version11 (odoo-11.0-20171007)

Steps to reproduce:
NOTE: using CentOS 7.3, Python 3.5.4, Postgresql 9.2.18

1. Fresh install : unzip source
2. ./odoo-bin -c demo.conf
3. Create database "odoo11_demo" and check "Load Demonstration Data"
4. Install "Point of Sale" App (Internal Error: #19947. Not sure if the error is related)
5. Point of Sale > Create > Enter "test" for "Point of Sale Name"
![image](https://user-images.githubusercontent.com/7699250/31315600-33d4bdc4-ac4e-11e7-9bc3-a8e4b2def9d5.png)

**Comment by Yenthe666** [comment]
Hi @peterhoth,

Thank you for your report.
I've just tested this on the latest Odoo V11 (20171008) without any problems. Can you reproduce this on an official Odoo instance at runbot.odoo.com? Can you update your source code and try this again?

Regards,
Yenthe

**Comment by peterhoth** [comment]
Hi @Yenthe666,

I tried http://runbot.odoo.com/runbot/1/11.0 but i can only login as demo and demo user cannot create Point of sale.

**Comment by Yenthe666** [comment]
Hi @peterhoth,

Yep, somebody has changed the password sadly. You can try the exact same thing on a V11 enterprise runbot though (http://269491-11-0-e7156a.runbot11.odoo.com/web?db=269491-11-0-e7156a-all)

**Comment by peterhoth** [comment]
runbot enterprise seems ok but i am testing using the community. I assume they are using the same base code, but i have tried many times re-installing and still getting the same error. However, when i install the point of sale app (or other app), odoo has an internal error which i reported #19947. Not sure if that error is causing this error. Looks like you tested using the new source 20171008. I will test again if i have the time. Thanks.

**Comment by Yenthe666** [comment]
Thank you - please do keep me updated! 😄

**Comment by peterhoth** [comment]
Hi @Yenthe666,

I was using the code from https://nightly.odoo.com/11.0/nightly/src/odoo_11.0.latest.zip

I just tried using the developers version but it failed:
```
$ wget -O- https://raw.githubusercontent.com/odoo/odoo/11.0/setup/setup_dev.py | python
--2017-10-09 07:38:19--  https://raw.githubusercontent.com/odoo/odoo/11.0/setup/setup_dev.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.40.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5656 (5.5K) [text/plain]
Saving to: ‘STDOUT’

100%[======================================>] 5,656       --.-K/s   in 0s

2017-10-09 07:38:20 (33.4 MB/s) - written to stdout [5656/5656]

  File "<stdin>", line 31
    print "odoo:" + f % l
                ^
SyntaxError: Missing parentheses in call to 'print'

```
print is a function in Python 3 and requires parenthesis. May i know how did you install the new odoo 11 ?

**Comment by peterhoth** [comment]
I just tested the latest code from https://nightly.odoo.com/11.0/nightly/src/odoo_11.0.latest.zip and it seems to fix the problem. Thanks.

**Comment by Yenthe666** [comment]
Awesome, thank you.
