### ISSUE TITLE
Employees screen bug

### ISSUE THREAD

**Issue by HNaga** [odoo/odoo#19950]
Impacted versions: odoo community 11

Steps to reproduce: duplicate admin
update the new employee name to x

Current behavior:
all employees are updated  to x

Expected behavior:
only current record updated
Video/Screenshot link (optional):

**Comment by ror-odoo** [comment]
Hi @HNaga 
Thank you for your bug report.

**Comment by qsm-odoo** [comment]
Hello,

Could you give more details on how to reproduce that issue (apps to go to / buttons used / ...) ? I tried duplicating the admin partner and the admin user (there is no admin employee) and it worked as expected both times.

Thanks

**Comment by qsm-odoo** [comment]
I am closing the issue, please tell me if the problem still occurs.
