### ISSUE TITLE
[V7] Payment order : can't import supplier invoice from closed fiscal year

### ISSUE THREAD

**Issue by CSester** [odoo/odoo#1995]
Hello,

If you want to import invoice into the Payment Order, you can't import from closed fiscal year.
When OpenERP search supplier account_move_line it made a restriction on fiscalyear, state must be draft.

You need to be able to import unreconciled supplier invoice even if the supplier invoice was done last year.

Original bug report is from V5, but it has not been fixed yet : https://bugs.launchpad.net/openobject-addons/+bug/775573

The patch proposed https://code.launchpad.net/~openerp-dev/openobject-addons/5.0-bug-775573-ado/+merge/66581 is always valid.

**_Impacted versions:**_
 7.x

**_Steps to reproduce:**_
1. Create a supplier invoice in a period of fiscal year A.
2. Validate supplier invoice.
3. Close fiscal year A.
4. Try to add to payment order.

**_Current behavior:**_
- Invoice doesn't appear in "Select invoice to pay" wizard.

**_Expected behavior:**_
- Invoice should appear in "Select invoice to pay" wizard.

Regards
Cyril

**Comment by StefanRijnhart** [comment]
For the record: https://bugs.launchpad.net/ocb-addons/+bug/1172293

**Comment by Yenthe666** [comment]
Hi @CSester ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
