### ISSUE TITLE
[11.0] Error on Sale Quotation Cancel in CE

### ISSUE THREAD

**Issue by cdasadiya74** [odoo/odoo#19968]
Impacted versions:11.0

Steps to reproduce:

Current behavior :

I have downloaded the latest build from the today morning from the nightly and use Odoo-11 in my local system.

[ downloaded nightly source ](http://nightly.odoo.com/11.0/nightly/src/)
Please review below attached screens

Expected behavior: No Need to Raise Error 

Video/Screenshot link (optional):

![so032 odoo_cancel_button](https://user-images.githubusercontent.com/7426056/31336600-2526c94e-ad15-11e7-8ad5-170456f004c7.png)

![so032 odoo_canceltime_error](https://user-images.githubusercontent.com/7426056/31336601-258852d6-ad15-11e7-823a-9d7526650de2.png)

**Comment by sle-odoo** [comment]
Hello,
This issue was fixed today with rev c7ca783e242ba7963fbb847cb53c3b9be9203936.

The packages will be rebuild tonight with the latests fixes.

Regards

**Comment by Yenthe666** [comment]
Phew - sle was just ahead of me. It has indeed been fixed in the meanwhile. 😄

**Comment by cdasadiya74** [comment]
Ok thank you @sle-odoo let me download the latest build and check
