### ISSUE TITLE
mail_thread: _find_partner_from_emails fail if more than 1 email address in partner

### ISSUE THREAD

**Issue by simmatica** [odoo/odoo#19967]
Impacted versions:
10, 11

Steps to reproduce:
Assign 2 email address in a partner (es. john@acme.com, john@acme.eu)
Send an email to sales team alias from john@acme.com and then send another email from john@acme.eu.

Current behavior:
Opportunities created from emails are not linked to the partner/customer
The problem is the exact match
partners = Partner.search([('email', '=ilike', email_address)], limit=1) 

Expected behavior:
partners = Partner.search([('email', 'ilike', email_address)], limit=1) 

Video/Screenshot link (optional):

**Comment by jem-odoo** [comment]
Hello,

if I understand well, you set multiple email addresses on the 'email' field of a partner ? This field must only contains one email adress. We don't support multiple email address for the same partner, or you should create different partner (one per email address).
We have no plan to support that kind of use case, sorry.
Regards
