### ISSUE TITLE
[11.0] deb nigtly buils

### ISSUE THREAD

**Issue by rimusz** [odoo/odoo#19960]
Impacted versions: v11.0

There are no more new nightly build for `deb` packages.
The last one is `20171004`

**Comment by Yenthe666** [comment]
@sle-odoo could you check this? I don't see new ones.

**Comment by sle-odoo** [comment]
@d-fence

**Comment by d-fence** [comment]
That's right, we are updating nightly and that should solve this issue.

**Comment by totalard** [comment]
Any status info of updation?

**Comment by d-fence** [comment]
@totalard It's in progress, there is a server migration under the hood.

**Comment by d-fence** [comment]
@totalard up and running !
But the actual deb does not yet reflect 347acbb4c2cded737b4282614c243cbbd6d5a85f
So the deb will install smoothly in Stretch but not on Xenial.

**Comment by totalard** [comment]
Dear,

It is build only for one time... Now it is not Upto date.. Kindly Check... There is some error in Build process.

**Comment by rimusz** [comment]
broken again :-(

**Comment by d-fence** [comment]
Actually, the Debian build process is broken due to package signature. I'm working on it. Related to #19900

**Comment by d-fence** [comment]
It works for more than a week. I close.
