### ISSUE TITLE
Odoo10C allows to update the produced quantity on a cancelled MO, which leads to false stock moves

### ISSUE THREAD

**Issue by svantesuominen** [odoo/odoo#19962]
Impacted versions: 
Found on 10C

Steps to reproduce: 
1. Create a manufacturing order and cancel it. 
2. UPDATE Quantity To Produce. 
3. Click the Inventory Moves of current MO, you see the false stock moves that even reserve some quants (Status = Available / Waiting Availability). 

Current behavior: 
UPDATE link is visible and operational even if the MO is in cancel state (updating leads to false stock moves). 

Expected behavior: 
Could we fix it so, that the UPDATE (Quantity To Produce) link is hidden on manufacturing orders that are cancelled?

**Comment by aisopuro** [comment]
Seems like the relevant line in here: https://github.com/odoo/odoo/blame/10.0/addons/mrp/views/mrp_production_views.xml#L92

Last updated in the big 10.0 refactor by @jco-odoo and @tde-banana-odoo: https://github.com/odoo/odoo/commit/2ddc35a5300e89981c0572ae6749aee946f34e9d
