### ISSUE TITLE
Odoo Website german translation 

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#19978]
The German translation from the Odoo homepage is not the best . 

Is the translation also done with Transifex ?

**Comment by Yenthe666** [comment]
Hi @F3000,

Yes, this is done with Transifex.
You can view (and edit) them at https://www.transifex.com/odoo/odoo-com/dashboard/

Regards,
Yenthe

**Comment by F3000** [comment]
thanks for the link :)

**Comment by Yenthe666** [comment]
You're welcome. 😉
