### ISSUE TITLE
[11.0] Partner form view messed up while city selection

### ISSUE THREAD

**Issue by milanpatel1519** [odoo/odoo#19992]
Impacted versions: 11.0

Steps to reproduce: Turn on debug mode. After **base_address_city** module install go to United States country (if demo data for same user company country) and make one city of it. Enable **Enforce Cities**. In **Input View** select **res.partner.form** with sequence 2 id. Then go to **Contacts** and create one.

Current behavior: Address view is messed up as screen shot. Also 2 times name showing.

Expected behavior: It has to invisible **city** field and visible only **city_id** field.

Also checked on runbot. Link: http://269880-11-0-9d5c18.runbot8.odoo.com

![partner_city_issue](https://user-images.githubusercontent.com/21196280/31371601-5fadffe8-adaf-11e7-9018-b2b5168d1048.png)

**Comment by Yenthe666** [comment]
Hi @milanpatel1519,

Thank you for your bug report.
The contacts view is indeed bugged when you have this configured:
![image](https://user-images.githubusercontent.com/6352350/31372136-ade077d8-ad94-11e7-9fa4-95f4f986679b.png)
@xmo-odoo and @qdp-odoo the last two commits are from you guys - can one of you have a look?

**Comment by qdp-odoo** [comment]
@smetl can you check this bug report please?

**Comment by smetl** [comment]
It's totally normal to have this kind of view because you are using the **res.partner.form** itself as the address view.

For more details, see the helper of **Input View**:

 _Use this field if you want to replace the usual way to encode a complete address. Note that the address_format field is used to modify the way to display addresses (in reports for example), while this field is used to modify the input form for addresses._

**Comment by Yenthe666** [comment]
Wait, how can this ever be functionally fine? This is messed up from an usability point of view..

**Comment by smetl** [comment]
This feature is very flexible because it allows the user to define (in xml) its own address block formatting. However, an high degree of freedom is risky because it allows the user to break a lot of things.

_With great power comes great responsibility!_
