### ISSUE TITLE
[10.0][11.0] Tax computation throws traceback in Sale order line/Invoice Line.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#19997]
Impacted versions: 10/11 Community and Enterprise

Steps to reproduce: Go to [http://269855-11-0-0dd370.runbot8.odoo.com](http://269855-11-0-0dd370.runbot8.odoo.com) --> Accouting -->Taxes --> Change Tax Computation method to "Group of Taxes" --> Add taxes same tax in group taxes.
Create new sales order or Invoice and select same tax, It will throw tarceback.

Current behavior: It is allowing to add same tax in Group taxes.

Expected behavior: It should not allow to select same tax.

Video/Screenshot link (optional): Tax Configuration: [https://prnt.sc/gvibed](https://prnt.sc/gvibed)
Traceback: [https://prnt.sc/gvic7b](https://prnt.sc/gvic7b)

**Comment by Yenthe666** [comment]
@qdp-odoo could you check please?

**Comment by sswapnesh** [comment]
Resolution: Need extend domain on field `children_tax_ids`

Add new field `<field name="id" invisible="1"/>`

Extend domain on field `children_tax_ids` -->` domain="[('type_tax_use','in',('none',type_tax_use)), ('amount_type','!=','group'),('id','!=',id)]"`

**Comment by sswapnesh** [comment]
Same Issue in version 8 and 9.

**Comment by qdp-odoo** [comment]
best would be to use _check_m2m_recursion()

**Comment by sswapnesh** [comment]
@qdp-odoo Could you please verify this?

**Comment by qdp-odoo** [comment]
master bug created

**Comment by Yenthe666** [comment]
@qdp-odoo is there any update for this one? Will it be changed in 10.0 and 11.0 or will it only be handled in the upcoming 12?

**Comment by sswapnesh** [comment]
Probably from v9 I believe.

**Comment by nim-odoo** [comment]
Fixed in master at https://github.com/odoo/odoo/commit/ac0ac23cdcc3072607894086d88c610bb9159af4
