### ISSUE TITLE
Add dependencies for odoo11:

### ISSUE THREAD

**Issue by Hamza-Talibi** [odoo/odoo#20000]
Hello everybody,
After downloading Odoo 11, I got this error when I was  trying to add dependencies with this commande ./odoo/setup/setup_dev.py setup_deps:
E: Impossible de trouver le paquet python3-vobject
https://github.com/odoo/odoo/blob/c7490671659293b984793ba68406698ceface67c/setup.cfg#L46

Any help please!

Thank you

**Comment by Yenthe666** [comment]
@sle-odoo another dependency report. Can you check this?

**Comment by sle-odoo** [comment]
@Hamza-Talibi Hello, on which distribution are you running this command? python3-vobject is packaged since debian stretch, so it shouldn't be an issue.

@d-fence

**Comment by Hamza-Talibi** [comment]
@sle-odoo Hello, I 'am on Ubuntu 16.04

**Comment by sle-odoo** [comment]
@Hamza-Talibi Ok, the python3-vobject is only available in debian stretch and that's why it's not available in your distribution. If it's the only issue to make Odoo 11 run on Ubuntu 16.04, we could make this dependency not required, as it's only used in of calendar to handle ics file. @JKE-be

But at the moment, you won't be able to install Odoo 11 on your distribution.

**Comment by Hamza-Talibi** [comment]
@sle-odoo It's Ok. So until when can I install Odoo 11 on my distribution.

Thank you

**Comment by d-fence** [comment]
@Hamza-Talibi actually, there are three missing dependencies for Ubuntu Xenial (16.04):
python3-vobject , python3-pyldap and python3-qrcode.
python3-vobject is only used in the calendar module to generate ical files.
python3-pyldap is used when we want ldap authentication.
python3-qrcode is only used in ESC/POS hardware driver.

So, those three dependencies can be moved to the recommends section of the Debian package.

I'm going to prepare a patch for that.

To solve your problem immediately, I tested the install of those three packages from the 'Zesty' version of ubuntu into 'Xenial'. Here is the way:

First, you have to download the three packages from here:
http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-vobject/python3-vobject_0.9.3-3_all.deb
http://cz.archive.ubuntu.com/ubuntu/pool/universe/p/python-qrcode/python3-qrcode_5.3-1_all.deb

If you are on amd64:
http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-pyldap/python3-pyldap_2.4.25.1-2ubuntu1_amd64.deb
else if you are on i386 platform:
http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-pyldap/python3-pyldap_2.4.25.1-2ubuntu1_i386.deb

Now, in a shell:
```bash
$ sudo apt install python3-dateutil python3-tz python3-pil
$ sudo dpkg -i python3-qrcode_5.3-1_all.deb
$ sudo dpkg -l python3-pyldap_2.4.25.1-2ubuntu1_amd64.deb
$ sudo dpkg -i python3-vobject_0.9.3-3_all.deb
```

Now, you should be able to install Odoo.

Hope this helps.

**Comment by Hamza-Talibi** [comment]
Hi @d-fence ,
It works.
Thank  you so much.

**Comment by d-fence** [comment]
Thanks to you. I'll close this issue when the patch will be pushed.
