### ISSUE TITLE
[11.0] unsupported format character '?' (0xa) at index 53

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#20008]
### Impacted versions:

11.0

### Steps to reproduce:

- Create a new DB with language English, country **Japan** and "Load demonstration data" selected.
- Install `website_event` module.
- Open an event under /event in website.

### Current behavior:

500: Internal Server Error

Error message:
```
unsupported format character '?' (0xa) at index 53
Traceback (most recent call last):
  File "/home/ytashiro/ws/11.0/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "
```

The same error shows at several different places in website as you install more website modules.

### Expected behavior:

No such error.

It seems the issue depends on the country selection at DB creation.  The issue did not reproduce when I selected Hong Kong.

### Video/Screenshot link (optional):

![2017-10-10_18-12-35](https://user-images.githubusercontent.com/7766939/31381494-4dba63c0-ade7-11e7-8d1e-67b150b336b0.gif)

**Comment by Yenthe666** [comment]
Hi @yostashiro,

Thank you for your report. It was actually fixed earlier today in https://github.com/odoo/odoo/commit/45085d3685998080abc24bd57d3d4426530729d6 😉 

Regards,
Yenthe

**Comment by yostashiro** [comment]
@Yenthe666 Thanks for the follow-up, however, I'm afraid this is a different issue.  I use the latest code from Github as of now and the issue reproduces.  Can you please reopen this.

**Comment by Yenthe666** [comment]
@yostashiro,

Actually I tried this on a completely clean database with:

- Language English
- Country Japan
- Demo data selected

The problem doesn't happen on all records, that is why I was sure it was fixed. There is indeed still an issue when you click on "Functional Webinar" for example. 😉

**Comment by xmo-odoo** [comment]
> It seems the issue depends on the country selection at DB creation.

Indeed, it's a typo in the Japanese address format field, so it should blow up whenever a "complete" address is displayed.
