### ISSUE TITLE
[11] Traceback during installation of sale_management (With demodata)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20015]
Impacted versions: 11 c

Steps to reproduce: Create new database and Install sale_management module

Current behavior: Thorws traceback during installation. (During installation of demo data from sales_team)

Expected behavior: Should install module

Video/Screenshot link (optional): 
![](https://image.prntscr.com/image/V9mksPQ3QuSyek_EenOn4w.png)

**Comment by sswapnesh** [comment]
Solved: Demo user is not present in database.

**Comment by Yenthe666** [comment]
Yup - it works by default. 😉
