### ISSUE TITLE
Website link for product drops "https://" portion of the link, thus resulting in failed redirect

### ISSUE THREAD

**Issue by Ehrenstein** [odoo/odoo#20021]
Impacted versions: 10

Steps to reproduce: 
- have your Odoo installation "behind" a proxy redirect so that you can access it via https://myodooexample.com/ instead of http://myodooexample.com:8069/
- install Sales, Website, and eCommerce modules, if not installed yet
- create any arbitrary product
- click on the button with the globe symbol in the upper right corner, reading "Published On Website"/"Unpublished On Website" (which triggers web.assets_common.js/web.assets_backend.js JavaScript)

Current behavior: 
the "https://" portion of the link is dropped, resulting in a redirect error (for some reason this somehow throws off the ProxyPass redirect that proxies the :8069 links to the HTTPS links in the first place, but that is another story)

Expected behavior:
any link in odoo should respect and adhere to the protocol used; in this case: if it's HTTPS, it should remain HTTPS.

Feature Request:
provide Odoo with a robust path assembly method that, additionally, allows for arbitrary separation of parts of Odoo (e.g. different subdomains for ERP, Website, Shop, such as https://intranet.mycompany.com, https://mycompany.com, https://shop.mycompany.com, respectively)

Video/Screenshot link (optional):

**Comment by Ehrenstein** [comment]
This seems to occur generally when the site is trying to redirect, e.g. when trying to login or when odoo redirects to /web/database/selector if the database is missing, among others.

**Comment by pedrobaeza** [comment]
I think you haven't put proxy_mode=True in your configuration file.

**Comment by Ehrenstein** [comment]
Thanks, pedrobaeza, that seems to have done the trick. Once I knew what to look for, Google gave a lot of advice about proxy_mode that wasn't mentioned in my recent sources to the reverse proxy approach before.
