### ISSUE TITLE
[11.0] Event : odoo.addons.website.models.ir_ui_view: Could not find view object with xml_id 

### ISSUE THREAD

**Issue by mhdsyarif** [odoo/odoo#20023]
Impacted versions: 11.0

Steps to reproduce:
- Create Event
- Input Event Name
- Save and Publish on Website

Current behavior:
If the name of the character event is too much then an error.
link : [http://270110-11-0-60a207.runbot11.odoo.com/event/erp-run-business-transformation-in-organization-2017-10-28-16/page/introduction-erp-run-business-transformation-in-organization](http://270110-11-0-60a207.runbot11.odoo.com/event/erp-run-business-transformation-in-organization-2017-10-28-16/page/introduction-erp-run-business-transformation-in-organization)
![selection_295](https://user-images.githubusercontent.com/5978109/31388800-6541aee2-adf9-11e7-9d8a-4181a9fed9b2.png)

error in terminal : `odoo.addons.website.models.ir_ui_view: Could not find view object with xml_id 'website_event.introduction-erp-run-business-transformation-in-organization'
`

Expected behavior:
Event name characters are not limited

**Comment by Yenthe666** [comment]
Ahh, yes, thank you for the extra info!
@JKE-be another one in the website 😉

**Comment by mhdsyarif** [comment]
Welcome, I wait for the good news  :wink:
