### ISSUE TITLE
[11] UI issue for widget "upgrade_boolean"

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20020]
Impacted versions: 11 c

Steps to reproduce: Go to Inventory --> Setting and find Shipping Connectors.
 
Current behavior: upgrade_boolean is applied three times as same fields are defined in three XMLs.
(Is has been defined in sale,stock and website_module)

Expected behavior: Widget should be applied only once. 

Video/Screenshot link (optional):

![](https://image.prntscr.com/image/3RhDHz6kRvmUtNfFm5oK5Q.png)

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thank you for your report - this is indeed a bug.
@mart-e if you tell me from which two you want to remove them I'll make a PR to fix it right away.

Regards,
Yenthe

**Comment by mart-e** [comment]
Thanks for the report but the analysis is not correct. It is defined 3 time because it appears in three different settings. This is a bug in the widget.
We will fix it.

**Comment by Yenthe666** [comment]
Something for @ged-odoo perhaps? 😉

**Comment by sswapnesh** [comment]
@mart-e  Yes, Excatly it appears in three different settings but widget has been applied three times on each view.

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

This has been fixed in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/31935228-9267ef7a-b8ae-11e7-9858-959a9884f01c.png)
This was handled in https://github.com/odoo/odoo/commit/dd2a619ad55191e58fb7d7112009624910142390

Regards,
Yenthe
