### ISSUE TITLE
Invoicing_type on sale order do not appear on delivery order

### ISSUE THREAD

**Issue by mvercruysse** [odoo/odoo#2003]
**Impacted versions:**
8.0 and above

**Steps to reproduce:**
1. Configure a customer with a defined invoicing type
2. Create a new sale order with this particular customer
3. Confirm the sale
4. View the delivery order

**Current behavior:**

On this sale order > other information , the invoicing type of the customer is well presented.
However, on the delivery order> additional information, the invoicing type of the customer is empty.

**Expected behavior:**
The invoicing type of the customer is well presented on the sale order and on the related delivery order.

**Comment by Yenthe666** [comment]
Hi @mvercruysse,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
