### ISSUE TITLE
Statusbar widget shows status that aren't included in statusbar_visible

### ISSUE THREAD

**Issue by bhollowa** [odoo/odoo#20034]
Impacted versions:10

Steps to reproduce: 

1. Create a selection field with 2 (or more) pairs so the value of one is included in the value of the other, for example, hello and hello_world:
`hello = fields.Selection([
                       ('hello', 'Hello friend'),
                       ('hello_world', 'Hello friends of all the world')
])`
2. Add the field to a view with attributes widget="statusbar" and statusbar_visible="hello_world" (or the value that contains the other(s)):
`<field name="hello" widget="statusbar", statusbar_visible="hello_world"/>`
3. Run odoo and go to the view. The statusbar will show both (or more) status.

Current behavior: The statusbar will show both (or more) status.

Expected behavior: Statusbar shows only the status added.

I've been doing some research and maybe this problem comes from the file adons/web/static/src/js/views/form_widget.js, line 1373:
`if(key === this.get('value') || !this.options.visible || this.options.visible.indexOf(key) !== -1)`
The third condition (`this.options.visible.indexOf(key) !== -1`) checks that the key is present in a string, but not that that's the value that wants to be included.

It's not a critical problem, the workaround is quite easy, you just have to check that any of the status is included as a string in other, but i don't think is the expected behavior.

Best regards,

Benjamin

**Comment by mge-odoo** [comment]
Hi @bhollowa 

Thanks for reporting the issue.
It has been fixed in 10.0 with the rev. https://github.com/odoo/odoo/commit/75d9a2b4db9fbad00114832186b7d4e3983124ba

Regards,

Martin
