### ISSUE TITLE
[11] Missing upgrade_boolean widget or Allow to check "Automatic Currency Rates" in Invoicing Configuration.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20030]
Impacted versions: 11 c

Steps to reproduce: [http://270205-11-0-bfba2c.runbot13.odoo.com](http://270205-11-0-bfba2c.runbot13.odoo.com) Go to Invoicing -->Configuration --> Settings --> Check "Automatic Currency Rates"

Current behavior: It asks to Upgrade odoo.

Expected behavior: "upgrade_boolean" widget should be there or It should allow to install module (If included in community version)

Video/Screenshot link (optional):

![](https://image.prntscr.com/image/f-nZRGaKSH_Xx2gY7xyWYg.png)

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thank you for the bug report. This does look wrong, the enterprise label should be shown.
@mart-e the odd part is that the label is set there in the view:
https://github.com/odoo/odoo/blob/ff0abd214c89dce19984ed0f3c72ea556e23da01/addons/account/views/res_config_settings_views.xml#L176

Can you have a look?

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Not Sure If it is related to #20020 or not

**Comment by sswapnesh** [comment]
This Is not Resolved yet. Still no Enterprise label at few places.

**Comment by Yenthe666** [comment]
@sswapnesh can you add screenshots of where it is still not fixed please?

**Comment by sswapnesh** [comment]
Accounting - - >Settings
Hide Setup Bar
Batch Deposits
Sepa SCT

**Comment by Yenthe666** [comment]
@mart-e guess you can do another round? 😉

**Comment by mart-e** [comment]
Or we could fix the `upgrade_boolean` widget. 
```sh
$ grep -r "widget=.upgrade_boolean" -3 | grep "label.*string" | wc -l
17
```

I can accept PR for both.

**Comment by sswapnesh** [comment]
Hello @mart-e 
 In v12 
`grep -r "widget=.upgrade_boolean" -3 | grep "label.*string" | wc -l`
`19`

**Comment by mart-e** [comment]
@sswapnesh my point stands ;-)

> I can accept PR for both.

**Comment by sswapnesh** [comment]
> > I can accept PR for both.


Why not an Internal Odoo task?🤔

**Comment by Yenthe666** [comment]
@mart-e I see you did some changes at https://github.com/odoo/odoo/commit/3715244a51a2aa382e98da69905a4aa6759b50e0 where you for example modifief `module_account_reports_followup` for V12.0 However 12.0 still doesn't show the enterprise label?
If you tell me what you'd like to be changed I'll make a PR for all those matches.

**Comment by Yenthe666** [comment]
@sswapnesh your grep doesn't say a lot I believe. It shows 18 matches but you can see it showing up items such as "UPS" which works fine.
You can view more details with `grep --with-filename -r "widget=.upgrade_boolean" -3 | grep "label.*string"`

**Comment by mart-e** [comment]
@Yenthe666 my patch was in 11.0. Maybe the patch needs to be adapted? Was it correctly forward ported?
What you show on your screenshot is not followup but a sepa module.

**Comment by Yenthe666** [comment]
Sorry indeed, I confused both. I'll do a recheck because the one I highlighted should have an enterprise label too, the issue has to be there. To be continued.

**Comment by sswapnesh** [comment]
@Yenthe666 Are you going to fix it in 11/12 or directly master?

**Comment by Yenthe666** [comment]
Probably 11/12 as it is a real fix to me :)

**Comment by sswapnesh** [comment]
> @sswapnesh your grep doesn't say a lot I believe. It shows 18 matches but you can see it showing up items such as "UPS" which works fine.
> You can view more details with `grep --with-filename -r "widget=.upgrade_boolean" -3 | grep "label.*string"`

On v11
```

> grep -r "widget=.upgrade_boolean" -3 | grep "label.*string" | wc -l
> 17

```

**Comment by sswapnesh** [comment]
@Yenthe666  :speak_no_evil: 
Added https://github.com/odoo/odoo/pull/35469 as the fix for the One you mentioned. (I didn't found others so far)
