### ISSUE TITLE
[11.0] Stock Move - Price Unit on Purchase in different currency

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#20035]
**Impacted versions:** 11.0

**Steps to reproduce:**

1. Company Currency - MX
2. Create a new purchase order - Currency - USD
3. Confirm it
4. Go to Stock Moves
5. Price on the stock move calculated at purchase order date rate.
6. Delivery after 1 day. Currency rate modified.
7. Go to Receptions
8. Transfer it

**Current behavior:**

The price unit remained at old price, meaning the stock value is not the correct one.

**Expected behavior:**

Before transfer the stock moves, check if the purchase was made in a different currency, and compute the price with reception date in context

**Video/Screenshot link (optional):**

**Comment by sle-odoo** [comment]
Thank you for your report, i see this was handled [correctly in v10](https://github.com/odoo/odoo/blob/10.0/addons/purchase/models/stock.py#L48) was mistakenly [removed in v11](5e5cd081232b982d4be6412ebf1d336195f2c451). I'll made the modification tomorrow and add a test so this won't happen again.

**Comment by deivislaya** [comment]
Thanks, it is also important to consider this [line](https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L247), since if it already has `price_unit` it is not recalculated again

**Comment by sle-odoo** [comment]
@deivislaya Hi, would you have a look at the proposed patch and testcases? thanks

**Comment by deivislaya** [comment]
LGTM +1
