### ISSUE TITLE
.Deb nightly build not building every day

### ISSUE THREAD

**Issue by totalard** [odoo/odoo#20043]
Impacted versions:11

Steps to reproduce:
Check https://nightly.odoo.com/11.0/nightly/

Current behavior:
.Deb is not building... All others are ok

Expected behavior:
.Deb should build every day

Video/Screenshot link (optional):
https://nightly.odoo.com/11.0/nightly/

**Comment by Yenthe666** [comment]
Hi @totalard,

Thank you for your report. This is a duplicate of https://github.com/odoo/odoo/issues/19960 and somebody from Odoo is already looking at it.

Regards,
Yenthe
