### ISSUE TITLE
[9] Different Billing Adress changes Contact Data of User

### ISSUE THREAD

**Issue by auditum-sfr** [odoo/odoo#20049]
Impacted versions:
At least V9

Steps to reproduce: 
- Create a User
- Login as user
- Buy something in ECommerce
- Use different Billing-Data

Current behavior:
The Contact-Data of the User that is logged in gets changed.

Expected behavior:
The Contact-Data of the User dont get changed

Video/Screenshot link (optional):
![billing-adress1](https://user-images.githubusercontent.com/25483058/31427653-4a2f7908-ae68-11e7-8841-4713e83bd90f.PNG)
![billing-adress2](https://user-images.githubusercontent.com/25483058/31427665-53c969ba-ae68-11e7-9b1a-9755b7290568.PNG)

**Comment by Yenthe666** [comment]
Hi @auditum-sfr,

Thank you for your bug report but this is actually intended behaviour.

Regards,
Yenthe
