### ISSUE TITLE
[11] Removing Product image doesn't reflect on Kanban View

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20046]
Impacted versions: 11 c

Steps to reproduce: [http://270244-11-0-e1104a.runbot9.odoo.com](http://270244-11-0-e1104a.runbot9.odoo.com) --> Open any Product --> Remove Image

Current behavior: After removing Image it still reflects on kanban view.

Expected behavior: Image should not be visible on kanban view.

Video/Screenshot link (optional):

![](https://image.prntscr.com/image/Ei3TAD7URkmbfUC7UVKygQ.png)

![](https://image.prntscr.com/image/ggIWJBJBS1iUgh9qc4c7gQ.png)

**Comment by sswapnesh** [comment]
Adding more: Duplicating that product will add image in new product again.

![](https://image.prntscr.com/image/uaN8pUjTQoKlTE3rcUw6EA.png)

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thank you for your report.
This is indeed a bug. @ged-odoo JS related?

Regards,
Yenthe

**Comment by sswapnesh** [comment]
@Yenthe666  Same Issue in Customers,Employees,Users and Vehicles.

**Comment by webkul** [comment]
@Yenthe666 @sswapnesh : please check #20606  if it fixed this issue, merge if it is correct.
Thanks

**Comment by mart-e** [comment]
Introduced at e5ef1c59172b7b8ebb1912e015fd41003ffc275d
@xmo-odoo I think the patch needs to be a bit more complex than that.
