### ISSUE TITLE
Community update 10 to 11

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#20051]
Is there any possibility to update the Version 10 to 11? 

I use centos 7 .

**Comment by Yenthe666** [comment]
Hi @F3000,

Please keep the bug reports to issues that are only about bugs in the official code. You can ask these kind of questions on the official help forums (help.odoo.com).
You can either upgrade with the official upgrade platform, which requires an enterprise license (see upgrade.odoo.com) or through OpenUpgrade as an open source alternative (see https://github.com/OCA/OpenUpgrade). There is no upgrade way for OpenUpgrade at the moment though.

Regards,
Yenthe
