### ISSUE TITLE
[11] Print model overview → no pages / empty PDF

### ISSUE THREAD

**Issue by bosskopp** [odoo/odoo#20066]
Impacted versions:
11 community and enterprise
tested @ https://demo.odoo.com

Steps to reproduce:

1. Enable dev settings
2. Goto Settings → Technical → Models
3. Select any model (e.g. account.analytic.account) to view model details
4. Click on Print → Model Overview

![bildschirmfoto vom 2017-10-11 18-45-23](https://user-images.githubusercontent.com/1733427/31454401-9ef40bbe-aeb5-11e7-92cf-54f510faa217.png)

(Locally installed wkhtmltopdf version: 0.12.1; demo.odoo.com version unknown to me. Some other reports I tested don't show the described behavior.)

Current behavior:
Webbrowser downloads a PDF-file, however, that file contains no pages (file-size: 306 bytes, no matter what module)

Expected behavior:
Webbrowser downloads a PDF-file that contains pages describing the model.

**Comment by Yenthe666** [comment]
Hi @bosskopp,

Thank you for your report.
This is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/31482039-b654afcc-af26-11e7-952c-a72f121480e7.png)
@mart-e can you check this please?

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

I have fixed it in saas-14 at b1bf99b7e3. It will be ported in 11.0 in a few days.

Thanks for the report
