### ISSUE TITLE
[10.0] Payments Widget return account.move view

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#20068]
Impacted versions:
10.0

Steps to reproduce:
1. Create Invoice
2. Validate Invoice
3. Register Payment
4. Open Payment
![payment](https://user-images.githubusercontent.com/17258001/31472493-18379ad4-aebd-11e7-852e-3264c8fee0f0.png)

Current behavior:
Open account.move of invoice
[Video 10.0](https://youtu.be/jYrMqJGSmeM)
Expected behavior:
Open account.payment of invoice  
[Video 11.0](https://youtu.be/i3-gxLwUkKA)

**Comment by Yenthe666** [comment]
@qdp-odoo is this desired behaviour?

**Comment by qdp-odoo** [comment]
that was the desired behavior in v10, because this would work also if there is no account.payment object (manual payment entry for example) but it changed in v11, tough, to open the account.payment if there was one, default to account.move otherwise.

So not a bug, yet not ideal I conceed

**Comment by maitaoriana** [comment]
I understand @qdp-odoo and thanks for your prompt response. But then, is there a way to access the account.payment from the invoice or from the account.move? Also, it is confusing that the button has the label "Open Payment" and it shows the account.move.
