### ISSUE TITLE
[11.0]Can not Load Chinese(CN)

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#20062]
Impacted versions:
odoo11-20171011
Steps to reproduce:
1、Creat a new database, select language is Chinese(CN),
2、User interface display in english.
3、Load Chinese(CN), user interface display in english
4、Load Chinese(TW), user interface display in Chinese(TW)
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

The v11 was not translated in Chinese yet.
I have added it on [Transifex](https://www.transifex.com/odoo/) so it should be good now.
