### ISSUE TITLE
dependency is not satisfiable python3-pyldap in Odoo11

### ISSUE THREAD

**Issue by eduquintana** [odoo/odoo#20077]
Impacted versions: Odoo Enterprise 11

Steps to reproduce:
I download odoo_11.0+e.latest_all.deb from odoo website.

I am trying to install that in ubuntu 16.04

this are the steps I follow:

echo -e "\n---- Update Server ----"
sudo apt-get update
sudo apt-get upgrade -y

# Este instala la utilería vim para editar textos
sudo apt-get install vim

#  Este instala la utilería gdebi que me servirá para instalar el archivo.deb de la instalación del odoo Enterprise
sudo apt-get install gdebi

#--------------------------------------------------
# Install PostgreSQL Server
#--------------------------------------------------
echo -e "\n---- Install PostgreSQL Server ----"
sudo apt-get install postgresql -y

#--------------------------------------------------
# Install Dependencies
#--------------------------------------------------
echo -e "\n--- Installing Python 3 + pip3 --"
sudo apt-get install python3 python3-pip

echo -e "\n---- Install tool packages ----"
sudo apt-get install wget git bzr python-pip gdebi-core -y

echo -e "\n---- Install python packages ----"
sudo apt-get install python-pypdf2 python-dateutil python-feedparser python-ldap python-libxslt1 python-lxml python-mako python-openid python-psycopg2 python-pybabel python-pychart python-pydot python-pyparsing python-reportlab python-simplejson python-tz python-vatnumber python-vobject python-webdav python-werkzeug python-xlwt python-yaml python-zsi python-docutils python-psutil python-mock python-unittest2 python-jinja2 python-pypdf python-decorator python-requests python-passlib python-pil -y

sudo apt-get install python3-setuptools
sudo easy_install3 pip
sudo pip3 install pypdf2 Babel passlib Werkzeug decorator python-dateutil pyyaml psycopg2 psutil html2text docutils lxml pillow reportlab ninja2 requests gdata

echo -e "\n---- Install python libraries ----"
# This is for compatibility with Ubuntu 16.04. Will work on 14.04, 15.04 and 16.04
sudo apt-get install python3-suds

echo -e "\n--- Install other required packages"
sudo apt-get install node-clean-css -y
sudo apt-get install node-less -y
sudo apt-get install python-gevent -y

#--------------------------------------------------
# Install Wkhtmltopdf if needed
#--------------------------------------------------

  sudo wget https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
  sudo gdebi --n `basename https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb 

  sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
  sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

at the end I execute this sentence to install odoo 11 Enterprise

gdebi odoo_11.0+e.latest_all.deb

And I receive this message:

dependency is not satisfiable python3-pyldap

Current behavior:

After install dependences an try to install Odoo 11 Enterprise using next sentence

gdebi odoo_11.0+e.latest_all.deb

I receive this message:

dependency is not satisfiable python3-pyldap

Expected behavior:

I expect to finish odoo installation

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @eduquintana,

Have you actually tried to install the dependency?

**Comment by eduquintana** [comment]
I do not know how to install the dependency

**Comment by eduquintana** [comment]
I tried to use
root@localhost:~# sudo apt-get install python3-pyldap
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-pyldap
root@localhost:~#

**Comment by Timodz** [comment]
I got it working by installing the missing file 
http://ftp.us.debian.org/debian/pool/main/p/python-vobject/python3-vobject_0.9.5-1_all.deb

**Comment by sterbhai** [comment]
I cant get it working.

The error on installation of ldap_auth is:
> Unable to install module "auth_ldap" because an external dependency is not met: No module named ldap
There ist no error in the log files. I installed with the "yente script" on ubunut 16.04

Tried the file indicated above:
```
sterbhai@odoo11-vm4:~$ sudo dpkg -i python3-vobject_0.9.5-1_all.deb
(Lese Datenbank ... 76333 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von python3-vobject_0.9.5-1_all.deb ...
Entpacken von python3-vobject (0.9.5-1) über (0.9.5-1) ...
python3-vobject (0.9.5-1) wird eingerichtet ...
sterbhai@odoo11-vm4:~$
```

Still the same problem.

**Comment by laps-odoo** [comment]
me too. after installing python3-vobject_0.9.5-1_all.deb, still get the same issue: 

       _/home/parallels# gdebi odoo_11.0+e.latest_all-enterprise.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: python3-pyldap_

**Comment by Yenthe666** [comment]
@d-fence could you check this one too please? Perhaps we still have a dependency issue after all.

**Comment by d-fence** [comment]
python3-pyldap dependency was removed here: 347acbb4c2cded737b4282614c243cbbd6d5a85f
It should install smoothly with the latest debian package.

**Comment by d-fence** [comment]
@sterbhai It seem that you use the ldap functionalities. As the Debian package 'python3-pyldap' does not exists on Ubuntu, it was removed from the dependencies.
So, if you want to use the ldap functionalities, you should install the Python3 module manually:
```console
$ sudo apt install libldap2-dev libsasl2-dev
$ sudo pip3 install pyldap
```
I hope this helps.

**Comment by aimerbois** [comment]
The solution from @d-fence  solved my problem

Thank you.
