### ISSUE TITLE
[account] wrong cost used with fifo when use unique serial number

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#20083]
Impacted versions:
* 11.0

Steps to reproduce:
* Create product with real time and FIFO and unique serial number
* Create purchase by 100 and receive with **123** serial number
* Create purchase by 120 and receive with **abs** serial number
* Create sale order transfer picking with **abs** serial number

Current behavior:
The journal entry by stock valuation is 100

Expected behavior:
The journal entry by stock valuation must be 120

Video/Screenshot link (optional):
https://youtu.be/3fQGL3aAQs8

**Comment by sle-odoo** [comment]
Hi @JulioSerna 
This is actually how financial FIFO is [supposed to work](https://en.wikipedia.org/wiki/FIFO_and_LIFO_accounting): the lot you chose dos not matter, the price is computed according to the order of received prices. In you usecase, if you make a second sale order, the second price (12) will be chosen to value the out move.

Regards
