### ISSUE TITLE
[account] wrong journal item by COGS with invoice policy delivered quantities

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#20080]
Impacted versions:
* 11.0

Steps to reproduce:
* Create product with real time valuation
* Invoice policy in delivered quantities
* Create sale and invoice

Current behavior:
The journal item of cogs is  cost(credit) stock valuation(debit)

Expected behavior:
The journal item of cogs is  cost(debit) stock valuation(credit)

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=NEAhfXgJ9tk&feature=youtu.be

**Comment by sle-odoo** [comment]
@JulioSerna 
Hello, thanks for your report but i just made the same scenario in version 10 and the entries are the same:
- expense account: debit 120 credit 0
- out account: debit 0 credit 120

Could you please test in version 10 and confirm me that i did not miss a step in reproducing your usecase and that the resulting entries are the same across version 10 and 11? That would be super useful.

Regards

**Comment by lap-odoo** [comment]
@JulioSerna I've answered on the ticket you opened.

**Comment by Yenthe666** [comment]
@lap-odoo can you add the feedback here too? If anybody finds this report in the future they'll know the answer too.

**Comment by lap-odoo** [comment]
Hi Julio, 

I've made a test in V11. 

Here is the accounting entry I get when I deliver the product : https://drive.google.com/a/odoo.com/file/d/0B0ITmdw6h3ZraGhhaUFzUFdTYTQ/view?usp=drivesdk
Here is the accounting entry I get when I invoice the product : https://drive.google.com/a/odoo.com/file/d/0B0ITmdw6h3ZrM1JHR1VCRVc0Rmc/view?usp=drivesdk

As you can see, the COGS (here expense account) is well debited and the Stock valuation account (delivered) is well credited. 

There is no change compared with V10. 

Can you confirm me it's ok ? 

Thanks

**Comment by JulioSerna** [comment]
Hello @lap-odoo 

The wrong journal entry is when product is with **Invoice policy in delivered quantities**
![prueba odoo](https://user-images.githubusercontent.com/7595505/31645923-483f002c-b2c4-11e7-9d3c-6761478e88f9.png)

**Comment by lap-odoo** [comment]
Hello @JulioSerna, 

Thank you for the precision, I've been able to reproduce the issue. 
I'll forward this to the technical team for bug fix. 
You will receive an answer on the support ticket when it will be fixed. 

Thank you for reporting it to us.
