### ISSUE TITLE
Website video media widget does not support multi lang environnement

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#20098]
Impacted versions:
10
Steps to reproduce:

Create a website, 
install many lang on the website via the website admin menu. 
On any page instanciate a media/video widget

Current behavior:

In the media widget, you can set an URL to your video, but you can not translate it or set 
a language detection for video platform that support this kind of feature.  

Expected behavior:

When I publish a video on a webpage I must be able to have a video with different audio, subtitle and 
even content depending on the website lang. 

This is the minimum sustainable feature, for internationalisation that is not concidered as buggy.

Ideally the media widget should be far more sophisticated on that topic.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be I believe you'd like this one. 😄

**Comment by JKE-be** [comment]
Hello,

It is not really considered as a bug.
The only workaround until now is to add a t-if lang inside the html_editor.

A task exists to improve it and make alt image translatable e.g. That will be probably improved for the next version.

Thanks for the feedback.

**Comment by JKE-be** [comment]
@stefanorigano 

I know that you have a big task on it.
Maybe you can take this one in consideration.

Thanks.
