### ISSUE TITLE
[11.0] Could not open Bill of Materials Structure

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20108]
Impacted versions: [11.0 c/e]

Steps to reproduce: Go to BOM --> Open Bill of Materials Structure

Current behavior: It open new form view for mrp.bom.line
[http://270780-11-0-04a110.runbot14.odoo.com](http://270780-11-0-04a110.runbot14.odoo.com)
![1](https://user-images.githubusercontent.com/16624719/31502572-1f665a7e-af8b-11e7-9859-67973e75e2cb.png)

[http://270871-11-0-055c03.runbot8.odoo.com](http://270871-11-0-055c03.runbot8.odoo.com)
![2](https://user-images.githubusercontent.com/16624719/31502562-1734748a-af8b-11e7-95d7-3e1895f37da8.png)

Expected behavior: It should show BOM structure

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
I honestly don't see the problem? When you click on the menuitem `Bill of materials` it opens the tree view of the BOM, as it should be.

**Comment by sswapnesh** [comment]
Open form view-->Action--> BOM Structure

**Comment by sle-odoo** [comment]
It's because of the tree view removal in the new webclient. The actions and tree view were not deleted accordingly.

**Comment by aisopuro** [comment]
@sle-odoo are there any plans to replace the tree view with a new version at some point so that these hierarchical view types could be restored?

**Comment by aisopuro** [comment]
Cool. Will it make it to either the community or enterprise versions of 11.0 soon after that @sle-odoo?

**Comment by sle-odoo** [comment]
no new features will be added to v11, so it'll be for v12. and i suppose it'll be in community.

**Comment by sswapnesh** [comment]
@sle-odoo  I think @aisopuro  is taking about hierarchical tree views not only BOM reprt.

**Comment by aisopuro** [comment]
I mean I guess. It'll be less of a pain to reimplement if the view type is available in Odoo 11 at some point, even if the BoM hierarchy itself isn't available. But I get the feeling this is one of those "too big of a change to introduce in the middle of a version" type of deals. :suspect:

**Comment by sswapnesh** [comment]
Agree @aisopuro 
@sle-odoo There is one more Issue related to this #22304 (PR was rejected due to Stable Policy #22312)
