### ISSUE TITLE
The company logo is not displayed in the upper left corner

### ISSUE THREAD

**Issue by sngnt** [odoo/odoo#20102]
# **# I cleared the browser cache and the issue was fixed**
![image](https://user-images.githubusercontent.com/5066447/31499874-2ede3710-af90-11e7-8538-cdbb1a5d34bc.png)

**Comment by Yenthe666** [comment]
@mart-e this looks a lot like the 8.0 version where images never came true?

**Comment by aleifuu** [comment]
sorry, reading this post I'm not sure wether we can close this issue or not ? 

Fixed means problem solved, no ?

**Comment by sngnt** [comment]
Thanks for your attention. Yes, the bug was fixed when I cleared my browser
cache. The problem has been resolved.

*Best regards!*
--------------------------------
Mr. Son
NhaTrang city, KhanhHoa province, VietNam.
https://www.facebook.com/sngtek.vn/
