### ISSUE TITLE
Odoo 10 Apps list display error

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#20103]
![unbenannt](https://user-images.githubusercontent.com/8161283/31500700-6a71dd7c-af68-11e7-9640-9bdd7bcde276.PNG)

when you look at this picture you cann see that the description is not displayed correctly

**Comment by Yenthe666** [comment]
This one has been around for quite a while though. @mart-e perhaps it is time to fix the overflow though.

**Comment by F3000** [comment]
Ok . 

When my Odoo 11 installation is finished , I will look if there is the same problem .

**Comment by mart-e** [comment]
Where is this taken from?
Context please

**Comment by F3000** [comment]
When I install more available apps . I click on a specific app for more infos . The info page is looking like this

**Comment by mart-e** [comment]
I see thanks. It is due to a bad CSS rule.
Actually @JKE-be has fixed it in 10.0 at c0a47980fc2458b2ef5f1e0c689842c8eafdde06 🎉
