### ISSUE TITLE
[hr] uniqueness of employee for a user

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#2011]
In the demo data of `hr`, a `hr.employee` with xmlid  `employee_fp` is created, linked to the admin `res.users`. A consequence of this is that there are 2 employees linked to the same user (the admin employee created elsewhere, and employee_fp), which makes testing inconvenient as finding the employee linked to uid 1 (the one you get by default in the tests) non deterministic. The following code in `hr_attendance.py` assumes there is a single employee linked to a given user. 

```
def _employee_get(obj, cr, uid, context=None):
    ids = obj.pool.get('hr.employee').search(cr, uid, [('user_id', '=', uid)], context=context)
    return ids and ids[0] or False
```

Is it legal to have 2 employees linked to the same user, anyway? I'm doubtful about this, and I'd welcome a unique constraint on the `user_id` column.

**Comment by Yenthe666** [comment]
Hi @gurneyalex ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
