### ISSUE TITLE
[11.0]Can not enable workorder in community editon

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#20112]
Impacted versions:
11.0
Steps to reproduce:
1、Odoo11 Release Note declare Work Center Control Panel & Work Order Steps are in community editon，but setting option is Enterprise actually。
2、Workcenter & Workorder function code are both in community editon, but can not install properly by the Enterprise option.
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look?

**Comment by jco-odoo** [comment]
Indeed. As mentioned on the community list, this has been done because we need quality steps for the work orders in enterprise and one way to do it, is to activate the security group in the user.  Need to check.

**Comment by kunalg140** [comment]
Though 'works order and quality' is marked as ENTERPRISE . Works orders can be enabled from users / Technical  setting / Manage Work Order Operations - settings. However Lot Numbers cannot be entered in the works order form .  Also material consumption not reflected in stock.
--

**Comment by kunalg140** [comment]
Reason for material consumption not getting reflected in stock seems to be the following:
Material consumption moves are being wrongly created from Virtual Location/Production  to Virtual Location/Production,  should be from Stock to Virtual Location/Production.

**Comment by sle-odoo** [comment]
linked to #20133
the reason is that if quality_mrp is installed, the users should work on workorder through the view based on quality checks

we'll remove the readonly in mrp to move it quality_mrp, that's what we shoud have done since the start

in the meantime you could simply revert 44f06a66467cb39780fa65d0cefb44704b072e94 and it'll work

@khoi-nguyen

**Comment by Guobower** [comment]
Why you change the workorder default security? As like 10.0, each function is expand by module, is not the standard way of moudle design?

**Comment by khoi-nguyen** [comment]
Hi,

The change has now been reverted in community.

Best,
Khoi

**Comment by kunalg140** [comment]
Hello,
Yes the LOT # issue in works order has been resolved. However the Consumed stock moves are still wrong.
Virtual Location /Production -> Virtual Location /Production . (So stock not effected)
![moves_with_wo](https://user-images.githubusercontent.com/32765682/31616983-d06e4318-b2ab-11e7-8e70-04d4561be25e.jpg)

If we do not use works order the moves are correct- WH/Stock ->  Virtual Location /Production .
![moves_without_wo](https://user-images.githubusercontent.com/32765682/31617020-e19a6234-b2ab-11e7-8d00-8a3d131f40f3.jpg)

**Comment by jco-odoo** [comment]
I don't know what you did, but it looks fine in last 11.

**Comment by kunalg140** [comment]
Okay would check again , I have only installed Sales , Purchase, Manufacturing & Inventory  in a new database.

**Comment by jco-odoo** [comment]
![image](https://user-images.githubusercontent.com/3832699/31618122-5ba63334-b291-11e7-93b9-c8b975d26037.png)

**Comment by jco-odoo** [comment]
Probably you filled in the production location on your routing.  Don't.

**Comment by jco-odoo** [comment]
I added them myself indeed, just to show.

**Comment by kunalg140** [comment]
Checked in a new database - everything works okay.
 Thanks

**Comment by sle-odoo** [comment]
Can we close this issue?
