### ISSUE TITLE
Dashboard view translate bug

### ISSUE THREAD

**Issue by kalway-tony** [odoo/odoo#20117]
Impacted versions:
10.0

Steps to reproduce:
translate po file by Poedit（English to Chinese）
then import translation

Current behavior:
some translated，some not.

Expected behavior:
all translated.

Video/Screenshot link (optional):

![helpdesk](https://user-images.githubusercontent.com/31125609/31529228-85f3dda0-b00a-11e7-9b4e-e21813900e81.png)

**Comment by Yenthe666** [comment]
Hi @kalway-tony,

Thank you for your report.
You should handle translations on Transifex though (https://www.transifex.com/odoo/)
For more information see our official guidelines at https://github.com/odoo/odoo/wiki/Translations

Regards,
Yenthe
