### ISSUE TITLE
[11.0] Can create employee without name

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20126]
Impacted versions: [11.0 c/e] 

Steps to reproduce: Create employee without filling any data

Current behavior:

![](https://image.prntscr.com/image/TbWUearnS22dzKM-T-JFnA.png)
To create employee without name--> Create employee with name --> After saving record remove name and Save it.

Expected behavior: Name should be required.

Video/Screenshot link (optional): https://prnt.sc/gwth4e

**Comment by mart-e** [comment]
Thanks, fixed at 6286dc4809e

**Comment by Yenthe666** [comment]
Yup, thats cleaner since it requires no model change. Thanks.
