### ISSUE TITLE
font family and size in Firefox in non-ui-widget context

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#2012]
Firefox has a standard css file that styles form inputs:

``` css
input {
  [...]
  font: -moz-field;
  [...]
}
```

In contexts where we don't sit in a ui-widget element, we get this font (which is some sans) because it wins against the `.openerp` declaration. Within ui-widgets, we get jquery-ui's declarations and everything is okay.

So for example the date field gets seriously messed up if it sits directly on a form as opposed to a notebook (where we are within an ui-widget):
![datefield](https://cloud.githubusercontent.com/assets/2563186/4057038/56a8822a-2dc3-11e4-8928-2db140ed8eb1.png)

Adding `ui-widget` globally to the form's div seems to solve the problem without side effects

**Comment by Yenthe666** [comment]
Hi @hbrunn ,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
