### ISSUE TITLE
[11.0] Action is visible even after not adding "client_action_multi" in act window.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20124]
Impacted versions: [11] 

Steps to reproduce: Go to [http://270891-11-0-349612.runbot14.odoo.com](http://270891-11-0-349612.runbot14.odoo.com)  --> Open any tree view select records

Current behavior:  All the action will be visible even if "client_action_multi" is not added in Act window.

![](https://image.prntscr.com/image/aYfwsJoRRlyjoEN1X6u3jA.png)

![](https://image.prntscr.com/image/4_KMQ134TY63g05BIlvwgQ.png)

[https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_view.xml#L170](https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_view.xml#L170)
It will Show Invoices/ Journal Items for first record only
Expected behavior: Action should be available in form view only.

Video/Screenshot link (optional): https://prnt.sc/gwt4ok

**Comment by Yenthe666** [comment]
@xmo-odoo perhaps one for you?

**Comment by xmo-odoo** [comment]
Indeed it looks like the "relate" type was lost when ir.values was split out and the "action" ir.values were moved over to actions.

**Comment by sswapnesh** [comment]
@xmo-odoo  Could please suggest me any temporary solution?

**Comment by xmo-odoo** [comment]
@sswapnesh I don't think there is one.

**Comment by sswapnesh** [comment]
@xmo-odoo Is it advisable to use #20351?  (Just to make sure, It don't break something in existing Environment.)
