### ISSUE TITLE
[11.0] Multiple Invoices for Sales Order regardless of Invoice state.   

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20121]
Impacted versions: 11.0

Steps to reproduce: Go to --> [http://270891-11-0-349612.runbot14.odoo.com](http://270891-11-0-349612.runbot14.odoo.com) Sales Order tree view --> Select Order and Invoice Order.

Current behavior: It creates invoice for only one Sales order (Without taking care of Sale Order State)
Same Way from Form view we can create multiple invoices for same Sales order.

![](https://image.prntscr.com/image/2udpkpSJSoas0Eukwf-opw.png)

We can create even multiple invoices for cancelled order.

![](https://image.prntscr.com/image/V0cZf9--QZW5JA_2bPXb4g.png)

Expected behavior: Invoices should be created per Sales order based on order state.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo this looks like one for you to check 😄

**Comment by sswapnesh** [comment]
@Yenthe666 Closing this issues as same was handled in #20637.
