### ISSUE TITLE
Lot numbers can't be entered in works orders in Odoo 11 CE

### ISSUE THREAD

**Issue by kunalg140** [odoo/odoo#20133]
Impacted versions: 11 

Steps to reproduce: Always

Current behavior: Lot numbers can't be entered in works orders

Expected behavior:

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
@khoi-nguyen

**Comment by khoi-nguyen** [comment]
Hi @kunalg140,

The issue should now be fixed in 11.0.

Best,
Khoi
