### ISSUE TITLE
[DMS] Usability issue of filter

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#2013]
- In Filter functionality there's usability issue, By clicking on filter it not displaying proper view, go to Knowledge >> Configuration >> Directories then click on any directory OR create new directory and go to tab security, click on 'Add Item', popup window will appear and click on dropdown arraw of filter, you will see filter option is displaying on textbox, and if you click on any filter option also it will not in a proper view.
- Here is the link of video: http://youtu.be/UsflHt9bC4s
- Issue present in V8.0 & Master

**Comment by Yenthe666** [comment]
Hi @dsu-odoo,

Thank you for the report.
This issue has been fixed in the meanwhile. From the latest V8:
![image](https://user-images.githubusercontent.com/6352350/27585261-c37d04b8-5b3b-11e7-8d2f-039803f8c67b.png)

Regards,
Yenthe
