### ISSUE TITLE
[11.0] Tool tip not available on widget="statusbar" on state field in Header with developer mode on.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20147]
Impacted versions: 11.0 c/e

Steps to reproduce: [http://271163-11-0-8c2c95.runbot8.odoo.com](http://271163-11-0-8c2c95.runbot8.odoo.com) --> Open Form View of Invoice/Sales order with developer mode on. 

![](https://image.prntscr.com/image/7Ti_KsfyTduFa0i97eXm3A.png)

Current behavior: Developer tool tip is not available.

Expected behavior:  Developer tool tip should be available.
It works when stages are used in header (Eg. Tasks)

![](https://image.prntscr.com/image/CKaHAfywTaSmCACtKCj6cw.png)

Video/Screenshot link (optional):[https://prnt.sc/gwznth](https://prnt.sc/gwznth)

**Comment by milanpatel1519** [comment]
Also not showing in many of this forms like 
1) Inventory -> operations -> Transfer
2) Invoicing -> Adviser -> Accounting Entry -> Journal Entry
3) Inventory -> operations -> Inventory Adjustments
4) Manufacturing -> Operations -> Manufacturing Orders
Please check this issue.

**Comment by Yenthe666** [comment]
@mart-e this looks like one for you. 😉

**Comment by mge-odoo** [comment]
This issue seems to be fixed.
Maybe by this rev. https://github.com/odoo/odoo/commit/66f7d393d3d6b0ac77cfde9172be86f77d9b63b1? Can you confirm?
