### ISSUE TITLE
Error installing ebaysdk - pip requiriments

### ISSUE THREAD

**Issue by rodriguesraphael** [odoo/odoo#20148]
When trying to install the requirements, ebaysdk does not conclude.

root@6c39e9c357bd:/# pip3 --no-cache-dir install ebaysdk
Collecting ebaysdk
  Downloading ebaysdk-2.1.4.tar.gz (40kB)
    100% |################################| 51kB 47kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ybr869ll/ebaysdk/setup.py", line 26, in <module>
        open(VERSIONFILE, "rt").read(), re.M).group(1)
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 29: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ybr869ll/ebaysdk/

**Comment by Yenthe666** [comment]
@d-fence could you have a look at this? Judging by the output the external dependency is broken at this point. Perhaps we could make a report there?
@rodriguesraphael which OS and version?

**Comment by luizcarlospedrosogomes** [comment]
for  ubuntu  server 14.04
 sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev

**Comment by yvaucher** [comment]
I experienced the same issue on debian:stretch

```
pip3 install -r requirements.txt 
Collecting Babel==2.3.4 (from -r requirements.txt (line 1))
  Using cached Babel-2.3.4-py2.py3-none-any.whl
Collecting decorator==4.0.10 (from -r requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting docutils==0.12 (from -r requirements.txt (line 3))
  Using cached docutils-0.12-py3-none-any.whl
Collecting ebaysdk==2.1.4 (from -r requirements.txt (line 4))
  Using cached ebaysdk-2.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-te49hz4n/ebaysdk/setup.py", line 26, in <module>
        open(VERSIONFILE, "rt").read(), re.M).group(1)
      File "/root/odoo-11.0/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 29: ordinal not in range(128)
```

**Comment by yvaucher** [comment]
See related issue:

https://github.com/timotheus/ebaysdk-python/issues/182

**Comment by rodriguesraphael** [comment]
@Yenthe666  It was a bug in the installation of ebaysdk, the repository maintainer made a correction and released version 2.1.5 correcting the error, I suggest updating the version in the requiriments file.

**Comment by Yenthe666** [comment]
The PR is ready at https://github.com/odoo/odoo/pull/20182 - just needs to be approved by somebody from Odoo.

**Comment by jcarlosmontoya** [comment]
This error is present in AWS if you have base LANG=C.UTF-8
