### ISSUE TITLE
Problema para levantar servicio odoo 10

### ISSUE THREAD

**Issue by giannio** [odoo/odoo#20159]
Problema para levantar servicio Odoo 10  

File "./odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2086, in declare_namespace
    path = sys.modules[parent].__path__
KeyError: 'odoo'

**Comment by Yenthe666** [comment]
@d-fence does this say anything to you?
@giannio please follow the guidelines and write a bug report with more information.. It really contains little information. Please do try to write them in English too..
