### ISSUE TITLE
[11.0] delivery generation at SO confirmation does not consider cancelled deliveries

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#20156]
### Impacted versions:

11.0

### Steps to reproduce:

- Create a sales order with  a line with qty 1 of a stockable product.  Confirm it, which generates a delivery.
- Cancel the sales order, which cancels the delivery as well.
- Set the sales order back to draft, change the qty to 3, and confirm the order again.

### Current behavior:

New delivery is generated with qty 2.  The cancelled delivery stays as cancelled and there is no way to modify it.

Odoo considers the cancelled delivery as if it is still alive when it comes to judging the need for generating a new delivery.

### Expected behavior:

A new delivery should be generated with qty 3 according to the updated sales order content.

**Comment by sle-odoo** [comment]
fixed by rev c30f8c50a3f4492c68f7cc4c2c1ce6cb5bf5350b

thanks
