### ISSUE TITLE
Odoo.sh Email Server Failed In Production

### ISSUE THREAD

**Issue by injazllc** [odoo/odoo#20157]
Impacted versions:
**11.0 EE**

Configured External Email Server on odoo.sh in production Database odoo.sh give me error...

**

> Connection Test Failed! Here is what we got instead:
> -3
> Temporary failure in name resolution

** 

**Note:** I already tried with Google SMTP still same error, when I put same settings on odoo 10 EE It works fine but not on odoo 11.0 EE

**Comment by Yenthe666** [comment]
@dbo-odoo another Odoo.sh related issue 😉

**Comment by injazllc** [comment]
this is the only one that I show you, otherwise odoo.sh have lots of error. :nerd_face:

**Comment by Yenthe666** [comment]
@injazllc there has been a quite big report about domains etc. It has been fixed though. 😉

**Comment by dbo-odoo** [comment]
Hello,

Currently, customized outgoing mail servers are not supported on Odoo.sh and we have no timeframe about that at the moment (it may stay that way for the foreseable future).

We still need some documentation to write that somewhere, quite obviously.

Regards,

**Comment by h4818** [comment]
If external mail servers are not supported in odoo.sh, what is the recommended solution for incoming email for helpdesk or crm? 
Does that mean that email integration is not supported on odoo.sh?

**Comment by fpodoo** [comment]
@h4818 If I am not wrong, incoming and outgoing email work out-of-the-box in Odoo.sh, but based on our own email servers and email gateway. We will support custom email servers, but later on (what would be the use case if we provide the SMTP email server as well as the incoming email gateway?)

@dbo-odoo can you confirm?

**Comment by h4818** [comment]
@fpodoo Thanks. I see now how this is supposed to work. Both Incoming and Outgoing emails are working on Odoo mail servers with one small issue:
catchall@[project name].odoo.com responds with a SMTP 550 mail delivery failure message as follows:
550 Requested action not taken: mailbox unavailable

 I think this is exclusive to odoo.sh

**Comment by dbo-odoo** [comment]
@fpodoo 
You're correct about our own smtp server being used out-of-the-box. We don't have an ETA about custom servers though.

@h4818 I just observed the same behaviour as you did, we will investigate soon.

**For the record**, if anyone from the future reads this: incoming and outgoing servers are configured out of the box. Assuming your Odoo.sh project's name is <my-company>.odoo.com, the catchall email is catchall@<my-company>.odoo.com & aliases are  <alias>@<my-company>.odoo.com  (e.g. for the "direct sales" sales team, it's sales@<my-company>.odoo.com). Note that this is exactly the same as our classical online platform.

**Comment by dbo-odoo** [comment]
@h4818 
Fix was in fact ready since friday but we do not deploy on friday (for sanity reasons :smiley:)

The fix is deployed on the european production server and should be deployed globally within the week.

**Comment by odoo-mastercore** [comment]
Hi There!

@dbo-odoo 

I have the same code 

[15:58, 3/1/2018] +58 426-5752512: Action: failed
Final-Recipient: rfc822;odoo@tecnicanet.odoo.com
Status: 5.0.0
Remote-MTA: dns; ampp1.odoo.com
Diagnostic-Code: smtp; 550 Requested action not taken: mailbox unavailable

The project is deployed on America production server.

**Comment by izotecarlitos** [comment]
How are we supposed to use Gmail or Google Apps IMAP and/or SMTP servers?

**Comment by dbo-odoo** [comment]
Dear people from the past, present & future,

Please use https://www.odoo.com/help to submit tickets about the Odoo.sh platform (please make sure to mention that you use Odoo.sh and the name of your project); I no longer work on this project myself and we prefer centralizing communications on tickets to avoid public thread pollution.

This issue will remain closed and I will not answer queries regarding it.

Thank you for your understanding,

Cheers
