### ISSUE TITLE
Recurring Documents module Not in v11.. How do Recurring so?

### ISSUE THREAD

**Issue by totalard** [odoo/odoo#20167]
Impacted versions:11

Steps to reproduce:
check in App list

Current behavior:
cant find it

Expected behavior:
contract module must be there

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @totalard,

Are you talking about the module `sale_subscription`? It is an enterprise app.

Regards,
Yenthe

**Comment by BeAntares** [comment]
Hi @Yenthe666, The module name is `subscription` in v10, 9 and others, and it's not in v 11. Is it now `sale_subscription`

**Comment by Yenthe666** [comment]
Yep, it has been migrated under a new module name.

**Comment by totalard** [comment]
How i get it without enterprise?




Ashique Zakariyya P
*Sales*


Golden Square Mukkam road, Areacode PO
Malappuram Dt, Kerala - 673639
Tel: +91-483-2851331
Fax: +91-483-2851331


*Store Available at**Total Uniforms Store*
Kamala Arcade, Annie Hall Road
Calicut - 673001, Kerala
Tel: +91-495-4050403

Ph:+91-9037453581,9387474096

Visit : <http://www.total-uniforms.com>www.totaluniformstore.com
Email: totalard@gmail.com

Like Us at:     facebook.com/totalard
<https://www.facebook.com/pages/Total-Uniforms/120058738137609>
Follow us on: twitter.com/total_uniforms




DISCLAIMER: This email (including any attachments) is intended for the sole
use of the intended recipient/s and may contain material that is
CONFIDENTIAL AND PRIVATE COMPANY INFORMATION. Any review or reliance by
others or copying or distribution or forwarding of any or all of the
contents in this message is STRICTLY PROHIBITED. The opinions expressed are
those of the sender, and do not necessarily reflect those of the Company.
If you are not the intended recipient, please contact the sender by email
and delete all copies; your cooperation in this regard is appreciated.

**Comment by Yenthe666** [comment]
The simple answer is not. You'd need to write yourself a new app that does the equivalent of the enterprise app or find one on the app store that has the functionalities you need. In case of self development it would cost you a lot more probably.
