### ISSUE TITLE
Sales invoices should not allow future dates

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#20160]
In some countries this is not logic at all.

Opinions?

**Comment by gdgellatly** [comment]
Is a common practice in all the countries I've worked, so nz, Australia,
England. To get a deal over the line, often a salesperson will agree to
invoice following month.

Also some companies which do overnight delivery make the invoice for the
following day so date matches delivery.

Finally in large transactions in NZ we have a tax law called 'time of
supply' which relates in part to invoice date so sometimes for cash flow
reasons or tax timing invoices get forward dated. Not for any bad reason,
just to make actually supply match more closely with legal supply and not
trigger an early sales tax liability.

That said in my company, with 5000 invoices a month, maybe 1 a month is
forward dated.

**Comment by nhomar** [comment]
Thanks that's what I want to read.

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269 (Telegram)
Móvil México:
+52 1 4773933942 (Whatsapp)

**Comment by Yenthe666** [comment]
Hmm - this is the same for Belgium and the Netherlands. There are some sectors or reasons to invoice ahead.
@nhomar I really wouldn't consider this a problem or bug. Are you fine with a close?

**Comment by nhomar** [comment]
Yes, I just want to open the comment, for me It is closed
