### ISSUE TITLE
Project Kaban view sorted after employe

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#20162]
Is this a bug or not ? 

I have created a project with different tasks . 
How can I see in the kaban view only the tasks from a specific person ? 

When it is not a bug , you can add this on the wish list :)

**Comment by Yenthe666** [comment]
Hi @F3000,

You can do this by adding filters in order to get the tasks from one specific version. Nothing to improve or wishlist here as it is possible by default. 😉
