### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float' while using  update  trigger 

### ISSUE THREAD

**Issue by Sarina111** [odoo/odoo#20168]
Impacted versions: 10

Steps to reproduce:

Current behavior: It works to reject  update in odoo. But gives  error as TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

Expected behavior: Reject update in odoo without  any error.

Video/Screenshot link (optional):

**Comment by Sarina111** [comment]
In odoo, I needed an update trigger, which  would not let any  user to update inserted data. I used following trigger function for rejecting update. The functio and trigger did work  but it gives error TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'. How  can I resolve this ?

Function:

create function check_id_change() returns trigger language plpgsql as $account_invoice$

begin

if (TG_OP='UPDATE') THEN

    RAISE NOTICE 'CANNOT EDIT RECORDS';

    RETURN OLD;

END IF;

    RETURN NULL;

END;

$account_invoice$;


Trigger:

create trigger check_update_trigger

before update on account_invoice

for each row

execute procedure check_id_change();

**Comment by Yenthe666** [comment]
Hi @Sarina111,

Thank you for your report.
The update functionality works fine in the latest Odoo 10 though. Can you reproduce this an official Odoo instance (at runbot.odoo.com)? Have you updated your Odoo to the latest source code?

Regards,
Yenthe

**Comment by Sarina111** [comment]
Hi Yenthe V.G,
I am using odoo 10, but it gave me error. How can I resolve it.

**Comment by Yenthe666** [comment]
Try to upgrade your Odoo to the latest update.
