### ISSUE TITLE
naive date in purchase order onchange_quantity, plus others

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20178]
Impacted versions: 11.0

Steps to reproduce:
Live anywhere where your timezone isn't exactly UTC - the further away the worse it gets, lucky for me I'm UTC+13 so more than half the time its wrong.

Current behavior:
In _onchange_quantity of addons/purchase/models/purchase.py there is this call
```python
        seller = self.product_id._select_seller(
            partner_id=self.partner_id,
            quantity=self.product_qty,
            date=self.order_id.date_order and self.order_id.date_order[:10],
            uom_id=self.product_uom)
```

Which uses the database date rather than a converted to user date.

Also affected in same file
```
def _prepare_purchase_order_line
def _run_buy(self, product_id, product_qty, product_uom, location_id, name, origin, values):
def copy(self, default=None):
```
Also affected by same thing in hr_payslip (I didn't really check, just the regex brought them back)
```python
date_to = fields.Date(string='Date To', readonly=True, required=True,
        default=str(datetime.now() + relativedelta.relativedelta(months=+1, day=1, days=-1))[:10],
        states={'draft': [('readonly', False)]})

date_end = fields.Date(string='Date To', required=True, readonly=True,
        states={'draft': [('readonly', False)]},
        default=str(datetime.now() + relativedelta.relativedelta(months=+1, day=1, days=-1))[:10])
```
Plus another couple in the hr reports, but because of the way the relativedelta is added you will only see it early on first day of month or late on last day of month depending on timezone.

There were a couple in website_event_track (but I don't know that module at all so left, they might be right) 

The regex to search was `date.*\[:10\]`

Expected behavior:
Use the correct date as expected by the user.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@nim-odoo another timezone and date related bug. I believe you fixed quite a few in the past, can you check this one too please? The report looks correct and a timezone should probably be applied on it.

**Comment by ke-real** [comment]
This is a big issue actually. Anywhere where there is fields.Datetime.now() all the custom dates are stored in user TZ. 
Example with POS session:
stop_at in db: "2018-10-05 15:41:17"
create_date in db: "2018-10-05 13:39:33.967208"
Both activities were done around 15:39

**Comment by gdgellatly** [comment]
Whether the more general issue is solved idk, but _select_seller is fixed.
