### ISSUE TITLE
Another Issue in odoo.sh

### ISSUE THREAD

**Issue by injazllc** [odoo/odoo#20186]
Impacted versions:
odoo.sh 11 EE

When click on studio button it gives me error.

Error:
TypeError: studio_info is undefined

https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:2850
Traceback:
switch_studio_mode@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:2850:32
trigger@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:3906:166
trigger@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:3912:115
toggle_app_switcher@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:2973:242
OdooClass.extend/Class.include/</prototype[name]</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:3814:368
toggle_app_switcher@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:2821:867
OdooClass.extend/Class.include/</prototype[name]</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:3814:368
on_hashchange/</<@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:516:1
then/</</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:678
fire@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:796:281
add@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:797:467
then/</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:631
each@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:625:758
then/<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:553
Deferred@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:803:189
then@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:518
on_hashchange/<@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:515:277
then/</</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:678
fire@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:796:281
add@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:797:467
then/</<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:631
each@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:625:758
then/<@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:553
Deferred@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:803:189
then@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:802:518
on_hashchange@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:515:22
new_handler@https://injazllc-coolco.odoo.com/web/content/1146-b692740/web.assets_backend.js:286:327
dispatch@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:892:378
add/elemData.handle@https://injazllc-coolco.odoo.com/web/content/1145-366cbf4/web.assets_common.js:865:151

![screenshot from 2017-10-16 11 29 26](https://user-images.githubusercontent.com/31472988/31599939-8d64cfa6-b265-11e7-8298-d9d82631d27f.png)

**Comment by Yenthe666** [comment]
@dbo-odoo Odoo.sh bug.

**Comment by dbo-odoo** [comment]
@injazllc 
Hello,

When reporting issues, please be sure to be as thorough as possible. Does this happen every time you click the button or only when you are on a specific view? When reporting javascript issue, it is a huge help to reproduce the issue in full debug mode ("debug mode with assets" in the Settings dashboard) to have a complete traceback.

That being said, this is probably not related to odoo.sh _per se_, probably just a v 11 bug. Since you have an odoo.sh project, I assume you have a partnership or enterprise subscription; could you please report your ticket on odoo.com/help instead? It will be treated faster (since i'm not from the odoo studio team) and will have a visible tracability on our system. Thank you :)

**Comment by injazllc** [comment]
@dbo-odoo 
Hi,
Thanks for your response, sometimes error occur on different application like if I click on CRM or Sale sometime errors occur and after 2 to 3 times continuously click error automatically remove and application opens or sometime need to reload browser.

And one more error I'm facing on odoo.sh I can't configure my SMTP even I tried Google SMTP but every time same error.
Thanks :)

**Comment by dbo-odoo** [comment]
I was not able to reproduce the issue. Is it still happening now?

As I said, I believe this is more a standard Odoo 11 EE issue than a odoo.sh one. If it still happens, please provide a full traceback using the debud=assets mode (a traceback in the minified assets is pretty undecipherable).

Concering outgoing mail servers, see #20157

**Comment by Yenthe666** [comment]
Hi guys,

Closing as there has been no response in over a month and it was no longer reproducable.
@injazllc please do post back if you can still reproduce this issue.
