### ISSUE TITLE
Variant Image is not updating

### ISSUE THREAD

**Issue by ashish-webkul** [odoo/odoo#20198]
Impacted versions: 11.0

Steps to reproduce:

- Create a simple or multivariant product with image whatever you want. I tested on a multi-variant product.
- Then go to the variant section and try to update image. Then you will see the image is not updating.

Current behavior:
In Odoo 10.0, I am able to update the image of every variant.

Expected behavior:
The image should update for every variant.
Video/Screenshot link (optional):
[error.webm.zip](https://github.com/odoo/odoo/files/1387366/error.webm.zip)

The video is attached inside zip. Kindly check.

**Comment by sswapnesh** [comment]
@Yenthe666 Seems related to #20046

**Comment by Yenthe666** [comment]
Hey @ashish-webkul,

Thank you for your report.
It is related to https://github.com/odoo/odoo/issues/20046 so I'm closing this one in favour of the other.

Regards,
Yenthe
