### ISSUE TITLE
[11.0] Invalid binding_model_id in action "hr_employee_action_subordinate_hierachy"

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#20203]
Impacted versions: 11.0 C

Steps to reproduce: Go to Customer--> Actions --> Subordinate Hierarchy

Current behavior: It asks you to create new Employee each time.

![](https://image.prntscr.com/image/6_RDsYBBRr_6QZiG_ChwlA.png)

![](https://image.prntscr.com/image/CtcshQn9Qo_1IZQR7hR3-A.png)

Code: [https://github.com/odoo/odoo/blob/11.0/addons/hr/views/hr_views.xml#L292](https://github.com/odoo/odoo/blob/11.0/addons/hr/views/hr_views.xml#L292)

Expected behavior: Action "Subordinate Hierarchy" Should not be there in res.partner.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e can we remove this? I do believe it shouldn't be there.

**Comment by mart-e** [comment]
Hi, I have corrected the source of this action but actually, it should be removed in master as we now have a hr_org_chart module that does that in a better way.

**Comment by sswapnesh** [comment]
I think action and view both should be removed in master as view_id `view_partner_tree2` is not used at any other place.
