### ISSUE TITLE
Stock moves of consumed items wrong when using Works Orders in CE 11

### ISSUE THREAD

**Issue by kunalg140** [odoo/odoo#20207]
Impacted versions: 11 CE

Steps to reproduce: Always

Current behavior:
Stock moves for consumed items are wrong  Virtual Location/Production -> Virtual Location/Production when using works orders , moves are okay WH/Stock -> Virtual Location/Production  if we do not use works orders.
![moves_with_wo](https://user-images.githubusercontent.com/32765682/31617595-36adb112-b2ad-11e7-9370-b392667b02f8.jpg)
Expected behavior:
When works orders not used .
![moves_without_wo](https://user-images.githubusercontent.com/32765682/31617726-a2b43750-b2ad-11e7-8fbb-c1af766514b5.jpg)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo could you check this?

**Comment by jco-odoo** [comment]
@Yenthe666 I can not reproduce this on runbot.  (and have already commented about it, probably a wrong setting in the routing)
