### ISSUE TITLE
Missing odoo-bin.exe in windows distribution

### ISSUE THREAD

**Issue by ErikSJan** [odoo/odoo#20208]
Impacted versions: 11.0

Steps to reproduce: download latest nightly in exe

Current behavior: create an sh file called odoo-bin

Expected behavior: create an odoo-bin.exe just like in 10.0 version

Video/Screenshot link (optional):

Can't use scaffolding with the current distribution as there is no usable odoo-bin.exe.

**Comment by Yenthe666** [comment]
@d-fence could you give feedback?

**Comment by d-fence** [comment]
Hello,

For some reasons, we decided to move from py2exe to source install on Windows.
So, for sure odoo-bin.exe does not exists anymore and will not work.

But you can still use Odoo from the command line by providing the full path to the python executable and the full path to Odoo. For example:
```
"c:\Program Files\Odoo 11.0\python\python.exe" "c:\Program Files\Odoo 11.0\server\odoo-bin" scaffold xyz
```
I hope it helps.

I'm closing this issue as the "exe" won't come back in a near future.
