### ISSUE TITLE
11.0 Major bug in unlocked sales order? Product changes not reflected downstream

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20217]
Impacted versions: 11.0
I checked, and couldn't find another report so maybe this is expected behaviour, but to my mind it is nuts.

Steps to reproduce:
On runbot:
Create an order for a product to be delivered.
Confirm it.
Change the product.
Save.

Current behavior:
Sales order updates - nothing else does - no warnings, no errors, nothing.
Picking is still for original product etc etc.

Expected behavior:
Picking, purchases, manufacturing etc to reflect change.

Video/Screenshot link (optional):

**Comment by wtaferner** [comment]
@gdgellatly @nim-odoo @Yenthe666 
I can confirm this behavior and I agree that there should be a user error instead. As it is crucial and IMHO straight forward I provided a fix.

**Comment by Yenthe666** [comment]
Hmm.. that doesn't look good. @JKE-be or @nim-odoo could one of you have a look?

**Comment by nim-odoo** [comment]
Introduced in https://github.com/odoo/odoo/commit/0e4f3bb95991261c04c08e72b28430acfabdecd1#diff-4c73fa68e85fd25b11c211d403c6b864L255
without procurement, no protection against modification
@sle-odoo @amoyaux this one is quite a severe issue

**Comment by amoyaux** [comment]
Hello I created a PR there https://github.com/odoo/odoo/pull/20282 and we gonna fix this issue asap

**Comment by amoyaux** [comment]
Resolved on 11.0 with commit 0cf3b1237351e63cf80918506a5fe0b9b45e181c Thanks for reporting the issue.
