### ISSUE TITLE
[10.0] Bug after update modules, error 500. ParseError: "null value in column "name" violates not-null constraint

### ISSUE THREAD

**Issue by altoch** [odoo/odoo#20215]
Impacted versions:
10.0
Steps to reproduce:
Install sales team, remove direct sales, create your teams and update modules
Current behavior:
After pull modules from git, and upgrading modules it gives an error 500
Expected behavior:
Upgrade modules and go on, I solved reinstalling sales team to create direct sales again

Video/Screenshot link (optional):

ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (9, 2017-10-16 20:52:26.331246, null, 1, 1, null, null, 1, 2017-10-16 20:52:26.331246, t, null, null, 17, t, t, null, null, null, null).
" while parsing /opt/odoo/addons/crm/data/crm_data.xml:4, near
<record id="sales_team.team_sales_department" model="crm.team">
            <field name="use_leads">True</field>
            <field name="alias_name">sales</field>

**Comment by Yenthe666** [comment]
Hi @altoch,

Thanks a lot for your bug report.
I've just tried to reproduce this but I was no longer able to do so. Now when you update your modules it will automatically recreate the sales group and no errors are thrown.
If you still face this issue then please update your Odoo source code to the latest version.

Regards,
Yenthe

**Comment by emiculax** [comment]
I have the same problem, some solution?
