### ISSUE TITLE
[IMP] apply preferred route also on push rules

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#20213]
@sle-odoo @amoyaux having you been committing the changes to stock recently, I wanted to know if it is a deliberate decision to not support preferred routes on push rules?

**Background:** I'm working on a import module and want to send pre-configured push rules from the PO, as preferred route, according to the entry harbor. I'll do a quick PR, and like to ask you would consider it a harmful operation, what I'm pretending to suggest...

**Comment by Yenthe666** [comment]
CC for @jco-odoo I believe he was active on this too.

**Comment by pimodoo** [comment]
Hello,

We have already get this feedback, but we cannot fix this in stable version as it will need a lot of changes. It will be fixed in the next version of Odoo (12.0).

Best regards

**Comment by blaggacao** [comment]
@pimodoo Thanks, it feels great to hear your opinion.

Please feel free to reuse, retarget my pull request at will.
