### ISSUE TITLE
A/B Testing (Create several versions of your website page) not working 

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20228]
Impacted versions:11.0

Steps to reproduce:
Go to Sale==> Configuration => Settings==> **Website**
Now marked A/B Testing as True and Save.
On page reload A/B Testing  now again Unselected(set to False)

**Comment by Yenthe666** [comment]
Hi @prakashkumar163,

Thank you for your report.
I've just tested this on the latest Odoo 11 and it works fine. Can you please update your Odoo and try again? Can you reproduce it on an official runbot (runbot.odoo.com)?

Regards,
Yenthe

**Comment by prakashkumar163** [comment]
I think this feature (module_website_version)not in CE.
Please confirm

**Comment by Yenthe666** [comment]
@prakashkumar163 actually, I was able to reproduce your issue in the community version - I was testing on the enterprise version where it works.
@JKE-be is this a migration issue from V10 to V11 perhaps?

**Comment by JKE-be** [comment]
hi @prakashkumar163 


Sorry it is an error that label is missing, website_version is into Enterprise.


I see also on runbot that some feature have multi label.

We will fix it asap.

Thanks for the reporting

**Comment by JKE-be** [comment]
@rdeodoo 

Can you add missing enterprise option + Fix duplicated label !
thx

**Comment by rdeodoo** [comment]
Missing enterprise label [fixed on saas-14](https://github.com/odoo/odoo/commit/bdaa3b88e471c3c0ec686e7ef4f2fe2cca595da2)

**Comment by rdeodoo** [comment]
Duplicate label [fixed on saas-16](https://github.com/odoo/odoo/commit/dd2a619ad55191e58fb7d7112009624910142390)
