### ISSUE TITLE
 Wire Transfer doing  nothig on portal pay(my/orders/34)

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20234]
Impacted versions: V11

Steps to reproduce:
Go To My account
Open Quotations Details View(/my/orders/34#portal_pay)
Select  Wire Transfer and  Click  Pay now
Nothing happens.

**Comment by Yenthe666** [comment]
Hi @prakashkumar163,

Thank you for your report.
We do not have enough information to test / validate this though.
Can you please try to reproduce this on a runbot instance (runbot.odoo.com) and add more information about the steps you've followed?

Regards,
Yenthe
