### ISSUE TITLE
Stripe  Payment Redirect to  /shop/undefined

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20232]
Impacted versions:V11

Steps to reproduce:
On shop/payment page while selecting the stripe, no popup open.
Instead, it redirects to /shop/undefined

Current behavior:
Undefined  redirect
Expected behavior:
Stripe popup open should open.

**Comment by Yenthe666** [comment]
Duplicate of https://github.com/odoo/odoo/issues/20054
