### ISSUE TITLE
Error: Server Error We are not able to redirect you to the payment form.

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#20236]
Impacted versions: V11

Steps to reproduce:
While accepting Online quote using wire transfer facing 

**Error: Server Error
We are not able to redirect you to the payment form.**

Create order for back end;
==>Select the partner and product.
==>Select the quotation template.
==>Select  Online Payment as Confirmation Mode.
===> confirm order.

Now go to my/order open order(/quote/35) click on Pay Now in the left corner.
Select wire transfer in PopUP and Click on Pay & Confirm.
a new wizard will open 
Error: Server Error
We are not able to redirect you to the payment form.

**Comment by rdeodoo** [comment]
Hello, this got fixed [here](https://github.com/odoo/odoo/pull/20464)
