### ISSUE TITLE
[V8 Runbot] External Identifiers 

### ISSUE THREAD

**Issue by palfrader** [odoo/odoo#2024]
Just now on runbot: http://12789-8-0-f25833.runbot6.odoo.com/ I have created two products, one in Products (Test Product) and one in Product Variants (Test Product Variants)

Please take a look on the External Identifiers:
![test-product](https://cloud.githubusercontent.com/assets/8029350/4060414/49735f54-2def-11e4-9580-827699c5a5e9.JPG)

**Comment by Yenthe666** [comment]
Hi @palfrader,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
