### ISSUE TITLE
Traceback when displaying Sequences, when deployed with PostgreSQL 10 

### ISSUE THREAD

**Issue by phuongnguyen3108** [odoo/odoo#20269]
Impacted versions: 11

Steps to reproduce:
Settings > Technical > Squences&Identifiers > Sequence

Current behavior:
psycopg2.ProgrammingError: column "increment_by" does not exist
LINE 1: SELECT last_value, increment_by, is_called FROM ir_sequence_...

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @phuongnguyen3108,

Thank you for your report.
I've just tested this on the latest Odoo 11.0 and it works without any problems:
![image](https://user-images.githubusercontent.com/6352350/31707235-fa145860-b3eb-11e7-980e-7486dc4bf1e6.png)

Can you reproduce it on an official Odoo (runbot.odoo.com)? Have you updated your Odoo to the latest source code?

Regards,
Yenthe

**Comment by phuongnguyen3108** [comment]
Thank you Yenthe666 for your very quick reply. I've just pull code this morning. And I'm running Postgresql10.
![external identifiers odoo](https://user-images.githubusercontent.com/32894807/31707988-00d7bc88-b418-11e7-99b1-b1768e342a7d.jpg)

**Comment by navinks04** [comment]
I have the same issue but my version is Odoo10. And the thing that is common between mine and phuongnguyen3108 issue is that Postgrsql version 10. I have upgraded my database to postgresql 10.

Hope the updgrade is not causing such isue.

**Comment by am05mhz** [comment]
exact same issue with phuongnguyen3108, Odoo 11 + PostgreSQL 10, for now I am using a work arround based on my personal assumption that increment_by is always 1:

    query = "SELECT last_value, 1 increment_by, is_called FROM ir_sequence_%03d" % seq.id

for now, it works normally, but I don't know when my assumption will break Odoo 11

**Comment by phuongnguyen3108** [comment]
@am05mhz Thank you for your work-around solution.

**Comment by phuongnguyen3108** [comment]
@Yenthe666 Could you please check this issue on Postgresql10 to see if that is the root cause? Thanks

**Comment by Yenthe666** [comment]
An alternative way to install Odoo for example: https://github.com/Yenthe666/InstallScript 😉 
Or check the official guides at https://www.odoo.com/documentation/11.0/setup/install.html

**Comment by petrus-v** [comment]
We've got the same issue on odoo version 9.0 and  Postgresql 10.0. 


Before pg 10 we get all settings in the sequence object:

```sql
mydb=> select * from ir_sequence_001;
  sequence_name  | last_value | start_value | increment_by |      max_value      | min_value | cache_value | log_cnt | is_cycled | is_called 
-----------------+------------+-------------+--------------+---------------------+-----------+-------------+---------+-----------+-----------
 ir_sequence_001 |       9399 |           1 |            1 | 9223372036854775807 |         1 |           1 |       0 | f         | t
```

Since pg >= 10 a new model appear pg_sequence which contains commons fields:

```sql
mydb=> select * from ir_sequence_001;
 last_value | log_cnt | is_called 
------------+---------+-----------
      10128 |      32 | t

mydb=> select * from pg_sequences where sequencename like 'ir_sequence_001';
 schemaname |  sequencename   | sequenceowner | data_type | start_value | min_value |      max_value      | increment_by | cycle | cache_size | last_value 
------------+-----------------+---------------+-----------+-------------+-----------+---------------------+--------------+-------+------------+------------
 public     | ir_sequence_001 | lalouve       | bigint    |           1 |         1 | 9223372036854775807 |            1 | f     |          1 |      10128
``` 
As long odoo user CREATE/ALTE/DROP  sequence to manage pg sequence and nextval() to get next values, I belive the matter is only on display informations on that vue.

@odony what kind of implementation do you expect here ?

 is there a plan to support different postgresql versions ?

Are you aware of some other issue with pg10 ?

**Comment by odony** [comment]
@petrus-v thanks for the heads up, we'll fix this in 9.0 and later to stay compatible with PG 10.

According to the release notes of PG10, SELECTing fields from the sequence relation is the main incompatibility introduced there, so it should only affect the Sequences menu indeed.

No major issue was discovered with PG10 thus far (one of our runbot servers is running on PG10). But as you can see, subtle changes can have consequences in less visible places too ;-)

**Comment by petrus-v** [comment]
@odony great thanks for that quick reply!

Indeed some unit test to read values on a specific model would looks likes useless until reading methode are not overwritten !

**Comment by odony** [comment]
The following patches are under test for this issue:
- 9.0: 7be3bcefb6c7682d37dd8c49b8da9f28f02a81e4
- 10.0 | 11.0: 69582ab05dee445854b11303f2e48965f1ad4a90 (should apply cleanly in both versions)

Thanks for your feedback if you have the chance to test them with PG 9 and PG 10

**Comment by odony** [comment]
The fix was merged in 9.0 at rev. fa5ee6ed2634b1a5b4388efb2c6ab6ae80356f28, in 10.0 at rev. 7a4c6eb35d0dd662d2bd992f4725413efbe31a97, and in 11.0 at rev. 56588e8d447a188f730ecfc62b451dba046e81ef (the patch was slightly different, so this makes fwd-ports easier). Thanks for your patience!

**Comment by petrus-v** [comment]
@odony 

I was not in the hurry, I'm testing it patch looks good to me and works like a charm!

regards,

**Comment by phuongnguyen3108** [comment]
@odony: Thank you so much. It works like charm on my system now.

**Comment by Nick-OpusVL** [comment]
This fix hasn't appeared in the official Odoo docker containers (odoo:10.0 and odoo:11.0) yet.

Any chance someone could trigger a new build on those?

**Comment by Yenthe666** [comment]
@Nick-OpusVL a new update of the docker image is planned to happen soon (but there is no specific date)
CC @sle-odoo the docker master.

**Comment by sle-odoo** [comment]
@d-fence

**Comment by d-fence** [comment]
@sle-odoo I agree, seems a good opportunity to update the docker image. I will do it soon

**Comment by pramadhana92** [comment]
can someone help to fix this issue for odoo 8?
```
ProgrammingError: column "increment_by" does not exist
LINE 1: SELECT last_value, increment_by, is_called FROM ir_sequence_...
```
i'm using odoo 8 with postgresql 13. it's running well but will get this error when opening sequence menu

**Comment by odony** [comment]
> i'm using odoo 8 with postgresql 13. it's running well but will get this error when opening sequence menu

@pramadhana92 v8 didn't support PostgreSQL 10+. You should upgrade your deployment, because v8 has been unmaintained and without any security updates for more than 4 years.

A dumb temporary workaround is to replace `increment_by` with `1` in the SQL query where it appears in `ir_sequence.py`. Or look at the patch for v9 and backport it properly. But seriously, don't use v8 anymore.

**Comment by pramadhana92** [comment]
hi @odony , I appreciate for your reply. The temporary solution is work for me.

I know it's out of topic. I know that v8 has been so old, but I have some important data in my v8 odoo. I don't know how to migrate the data and the custom module.

**Comment by jmarpi** [comment]
I had the same problem in odoo 8.0 I solved it as @odony  indicates
in the file: addons/base/ir/ir_sequence.py
I replaced this
`statement = (
                    "SELECT last_value, increment_by, is_called"
                    " FROM ir_sequence_%03d"
                    % element.id)`
to:
`statement = (
                    "SELECT last_value, 1, is_called"
                    " FROM ir_sequence_%03d"
                    % element.id)`
