### ISSUE TITLE
Widget "date" doesn't work on datetime field

### ISSUE THREAD

**Issue by phuongnguyen3108** [odoo/odoo#20271]
Impacted versions: 11

Steps to reproduce: 
<field name="date_order" position="attributes">
                    <attribute name="widget">date</attribute>
                    <attribute name="string">Quotation Date</attribute>
</field>
Current behavior:
System show warning message whenever user click on Create button from Quotation menu: "The record has been modified, your changes will be discarded. Do you want to proceed?"
And still show time on Order Date field

Expected behavior:
No warning message appear and date should be displayed without time portion

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @phuongnguyen3108,

Thank you for your bug report.
I'm closing this one in favour of https://github.com/odoo/odoo/issues/20311 as the other report has more info and screenshots.

Regards,
Yenthe
