### ISSUE TITLE
11.0 Purchase Order field visible on Customer Invoices and Credit Notes

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20274]
Impacted versions: 11.0

Steps to reproduce:
View a customer invoice or credit note on runbot and open a line.

Current behavior:
See purchase order field

Expected behavior:
Don't see purchase order field

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/31711844-e94a5902-b455-11e7-83d3-0e325365601c.png)

**Comment by Yenthe666** [comment]
@qdp-odoo do you agree to hide/remove this field in this view?

**Comment by qdp-odoo** [comment]
yep

**Comment by sswapnesh** [comment]
Same behaviour in 9,10.

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

As we where facing it too I made an OPW and @nim-odoo fixed it.
Commit that fixed it is https://github.com/odoo/odoo/commit/927a1337690c615d9c15d8b582b34b551fe85200
