### ISSUE TITLE
[10.0] Forecasted stock report is not multi-company compliant

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#20292]
### Impacted versions:
10.0

### Steps to reproduce:

On runbot, create a new company called Company B.
![image](https://user-images.githubusercontent.com/7813258/31724293-9e63ebd0-b421-11e7-8aec-a3a33444af26.png)

Give access to demo user:
![image](https://user-images.githubusercontent.com/7813258/31724342-bf156ba6-b421-11e7-92fb-81dd5ec86614.png)

Connect as demo user and consult product E-COM08 in YourCompany. The forecasted stock is 18.
![image](https://user-images.githubusercontent.com/7813258/31724461-0d521030-b422-11e7-8b9d-223eefc514cf.png)

Switch to Company B and display the same product, the forecasted stock is 0.
![image](https://user-images.githubusercontent.com/7813258/31724536-50d4a4a8-b422-11e7-9207-cc81b62c40ee.png)

Clic on the Forecasted button and display the report:
![image](https://user-images.githubusercontent.com/7813258/31724587-74b69c14-b422-11e7-9d61-27dcabc20e43.png)

### Current behavior:

The forecasted quantities displayed uses quantities from YourCompany.

### Expected behavior:

The report should display 0 for Company B.

Video/Screenshot link (optional):

**Comment by Cedric-Pigeon** [comment]
OPW-777270

**Comment by simongoffin** [comment]
Closed with 135823a4d8a7f65381f4e9c3dcebfdfde4423e71
