### ISSUE TITLE
[11: Widget] widget="date" doesn't work on form view

### ISSUE THREAD

**Issue by Tinhnguyen96** [odoo/odoo#20311]
Impacted versions: 11

Steps to reproduce:
![pic_1](https://user-images.githubusercontent.com/32927838/31766018-9d0121de-b4f0-11e7-9bff-26f6d0e889f4.png)

add widget="date" to field date_order:

![pic_2](https://user-images.githubusercontent.com/32927838/31766036-b03f4a64-b4f0-11e7-865c-d6e8a2d20a1f.png)

Enter "F5" and Create new Request For Quotation

![pic_3](https://user-images.githubusercontent.com/32927838/31766065-befdc04e-b4f0-11e7-8677-e1b3cf0e94e3.png)

Current behavior:
System show warning message whenever user click on Create button from Request For Quotation menu: "The record has been modified, your changes will be discarded. Do you want to proceed?"
And still show time on Order Date field

Expected behavior:
No warning message appear and date should be displayed without time portion

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo the widget seems to be broken?

**Comment by sswapnesh** [comment]
@Yenthe666  Related to #20271

**Comment by Yenthe666** [comment]
Indeed. Let me close the other in favour of this bug report as this bug report contains more info and screenshots.

**Comment by mge-odoo** [comment]
@Tinhnguyen96 thanks for reporting the bug. It has been fixed in a previous version (saas-16) and will soon be forward-ported.

**Comment by Tinhnguyen96** [comment]
Thank you for your interest in my bug! Thank you
