### ISSUE TITLE
Workflow leave management odoo 

### ISSUE THREAD

**Issue by guesmihela** [odoo/odoo#20327]
Hi I'm having a hard time trying to work out the permissions for the Human Resources module of Odoo10 when it comes to the Leave Management Workflow. 
I active the double validation in the leave Type. 
Let say I have a Department Production with the following employees:
Manager1 (Manager of the Department) 
Employee1 (Employee on the same department production) 
and I have an other department : HumanRessources with the following employees:
HR officier
I've initially set both Manager1 and Employee1 as Employee in the access rights for Human Resources. 
I also set Manager1 as Employee1's manager in the employee directory and set both persons in the same department. 
So the problem here is that if I want to do a leave request :
Employee1->Manager1->HR officier 
the leave request from employee to manager it ok working
![image](https://user-images.githubusercontent.com/18150593/31779148-b6e938a0-b4f2-11e7-93eb-475ae5347ffd.png)
but now from Manager01 to HR officier (second approve) don't work how can I do it !!! what is the acces right can i assign to HR officer

**Comment by Yenthe666** [comment]
Hi @guesmihela,

Thank you for your report.
The Github tracker is only for bugs in the official code though, it is not the place to ask questions about implementation. You might want to ask this on the official help forums (help.odoo.com) or have a look at the official documentation at https://www.odoo.com/documentation/user/11.0/index.html

Regards,
Yenthe
