### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by kl31b3r** [odoo/odoo#20338]
Impacted versions: odoo 11

Steps to reproduce: 
1. Install Point of Sale
2. des-Install Point of Sale
3. Install Point of Sale
Current behavior:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/odoo/odoo/addons/point_of_sale/models/pos_config.py", line 335, in create
    **'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting**

Expected behavior:

Video/Screenshot link (optional):

**Comment by kl31b3r** [comment]
The solution:

Replace in Line 335
#'name': _('POS Order %s') % values['name'], 
  'name': "POS Order %s" % values['name'],

Replace in Line 344
#val.update(name=_('POS order line %s') % values['name'], code='pos.order.line')
   val.update(name="POS order line %s" % values['name'], code='pos.order.line')

**Comment by Yenthe666** [comment]
@kl31b3r I've tried this on the latest Odoo 11 and it works fine too.

**Comment by kl31b3r** [comment]
Check this file /opt/odoo/odoo/addons/point_of_sale/models/pos_config.py

Line 335 and 344.
