### ISSUE TITLE
[11.0][10.0] Landed Costs do not support Customs Tariffs per product

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20347]
### Impacted versions:
11.0, 10.0

### Steps to reproduce:

1. Create a Landed Cost
2. Add a bunch of pickings with more than 100 products
3. Add all applicable Cost Lines
4. Create a "Customs Tariffs" cost, which just applies to some of the products of this Landed Cost

### Current behavior:
There's no way to use Customs Tariffs, as we can't apply additional costs just to specific products. Doing this will raise an error with: 

> _Cost and adjustments lines do not match. You should maybe recompute the landed costs._

Obviously, recomputing deletes all the changes made in the Valuation Adjustments

### Expected behavior:
Allow to set additional costs on individual products (maybe product categories?)

**Context:** On many countries customs (at least all that I've worked with) the use of **tariffs** it's part of the day to day importation process as products pay customs depending on their category/type. 

Even though some companies prorate this costs across all products, there are cases were doing this would affect the cost of less expensive products making them not competitive at all were using Pricelists based on cost. 

**Tested on runbot**

**Comment by gustavovalverde** [comment]
@sle-odoo pinging you based on your last commits ;)

**Comment by lukebranch** [comment]
i've also run into this issue in 11.0

**Comment by lap-odoo** [comment]
@gustavovalverde @lukebranch : Thanks for the feedback, I agree it would be interesting to have it. We plan to do some improvements on the landed costs, hopefully for V12. I've added your feedback in our backlog.

**Comment by gustavovalverde** [comment]
@lap-odoo any hope of this this landing in v12?

**Comment by lap-odoo** [comment]
@gustavovalverde Unfortunately not but it's still in the pipe ..

**Comment by yellowsnow** [comment]
For those still waiting for this feature there an add-on for v13+ : https://apps.odoo.com/apps/modules/17.0/import_fees/
