### ISSUE TITLE
[10.0][BUG] Export a grouped selection will export all

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#20340]
Impacted versions:
10.0

Steps to reproduce (tested on runbot):
* Go to partner selection
* Group partners by country
* Select belgium with the "all" selection
* Export this selection 

Current behavior:

ALL the partners are  exported into the file

Expected behavior:

Only the selected partner should be exported (moreover if you elapse other grouped selection you will see that none of them are selected 

related to https://github.com/odoo/odoo/issues/13233

**Comment by JonathanNEMRY** [comment]
OPW 777595

**Comment by gustavovalverde** [comment]
Also confirming this issue @Yenthe666

**Comment by Yenthe666** [comment]
@JonathanNEMRY and @gustavovalverde do you guys mean like this?
![image](https://user-images.githubusercontent.com/6352350/31818463-967e25b6-b598-11e7-9257-84354b8315e5.png)
This only exports the belgian companies for me:
![image](https://user-images.githubusercontent.com/6352350/31818485-abb276b2-b598-11e7-99f8-104f853ddb0c.png)

I think I'm doing something slightly different. 😉

**Comment by sswapnesh** [comment]
@Yenthe666  You need to remove advance search `Country contains "belgium"` to reproduce issue.

**Comment by sswapnesh** [comment]
Same Issue in every list view. (v10/11)
Go to any List view --> Group By --> Select and Export.
It will export all records.

**Comment by JonathanNEMRY** [comment]
@Yenthe666  your exemple is actually a workaround of this bug...but into a user-use-case he does not want to select agin a filter to select what he already has into its screen...don't you think? :smile:

**Comment by JonathanNEMRY** [comment]
@JKE-be do you have an idea how to fix this?

**Comment by JKE-be** [comment]
It is more a debate of usability than an issue IMHO.

But your solution is to uncheck the first checkbox from 1 group by to say "Not all but all what is selected" and after reselect the unchecked to get it. There you will have all selected, and all record of the current domain in the filter.

We should probably implement a warning in the gmail style

![image](https://user-images.githubusercontent.com/4848797/31881872-37396418-b7e5-11e7-8cd5-89dfefd7e856.png)

![image](https://user-images.githubusercontent.com/4848797/31881843-171bd56c-b7e5-11e7-8a43-417f1746fbed.png)

**Comment by JonathanNEMRY** [comment]
OK yes a big red warning should be welcome then because if you had first selected all grouped ones then just after this your customer elapsed another saying 'just see what's into this grouped one' --> he's into a situation where he see its selected records and others not selected but the result will be its selected+its unselected+all others....pretty not-understandable for a user that will open a big file vs 10 selected records shown. But actually reading the source code I understand it will be quite a big change..so maybe thinking about it into master?

**Comment by JKE-be** [comment]
@ged-odoo one feedback for you
