### ISSUE TITLE
/jsonrpc call without parameter, response with Bad Request and showing memory allocation address 

### ISSUE THREAD

**Issue by BetaUliansyah** [odoo/odoo#20341]
Impacted versions: 8, 10, 11 (9 is not tested yet)

Steps to reproduce: Open $ODOOURL/jsonrpc from browser

Current behavior: Return with Bad Response page

Expected behavior: 404 page maybe?

Video/Screenshot link (optional):

![screenshot from 2017-10-20 15-48-08](https://user-images.githubusercontent.com/3723780/31812729-2ee9563a-b5ae-11e7-9b18-99db92103d5c.png)

Personally I used this technique to identify whether a website is using Odoo. I know it is normal, but I am not sure, is this going to lead to another risk?

**Comment by xmo-odoo** [comment]
400 Bad Request is correct, json-rpc endpoint require a request mimetype of application/json or application/json-rpc.
