### ISSUE TITLE
attrs readonly not working in group, page, notebook tags

### ISSUE THREAD

**Issue by NicolasWebDev** [odoo/odoo#2034]
When using the attrs readonly in a group, page, notebook tag, I would expect the same behavior than using the invisible attrs, that it applies to all the contained elements.

**_Impacted versions:**_
Version 7.0-20140603-231034

**_Steps to reproduce:**_
1. Create a group tag like this : <group attrs="{'readonly': [('condition', '=', True)]}"> containing fields.
2. Fullfill the condition.

**_Current behavior:**_
The contained fields are not readonly.

**_Expected behavior:**_
That the readonly attrs was applied to all the contained fields within this group tag.

**Comment by simple-task** [comment]
Can this be implemented please.
It is not intuitive to know that a readonly attribute can only be applied to a field.

**Comment by Sathors** [comment]
Moreover, it would in some cases spare a lot of code, because I have many times a whole group that I would want readonly, without having to repeat the attribute in everyone of the fields.

**Comment by Yenthe666** [comment]
Hi @NicolasWebDev ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
