### ISSUE TITLE
[11.0][10.0] Password validation is being done after database upload

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20348]
### Impacted versions:
11.0 10.0

### Steps to reproduce:
1. Select a 2GB database to restore
2. Start a database restore process
3. Input Master Password
4. Input Database name
5. Click Continue

### Current behavior:
Database starts uploading.
After 15 minutes...
![image](https://user-images.githubusercontent.com/16890942/31819748-fdff6d44-b56b-11e7-9414-666521bb016a.png)

### Expected behavior:
Validate the password before uploading the database, not after.

**Comment by gustavovalverde** [comment]
@odony 😄

**Comment by odony** [comment]
I think this was already reported somewhere, maybe in relation with #17663. The thing is, we're dealing with HTTP requests here, and we only get to process the request when we receive it entirely, i.e. when the bytes have been sent. That can take a while if you're not doing this locally.

We could do a pre-flight validation of the password before posting the file, but that seems mostly overkill for 2 reasons:
1. The db manager is mostly a dev/staging/test feature, and not meant to be used for production. It is even [strongly recommended to disable it](https://www.odoo.com/documentation/11.0/setup/deploy.html#security).
2. The db manager is not well suited for uploading large files, as everything is put in memory of the Odoo server (see #17663). Working directly with PG dumps and zipped filestores is a much better alternative for any serious deployment. This is also directly related with your ability to do proper backups.

So I'm not sure there is anything to do here... but you can always try a PR ;-)

**Comment by gustavovalverde** [comment]
I mainly used the db manager after an upgrade from v8 to v10 as it was the recommended tool by the upgrade team. But I do agree with your statements. 

I'll close this as is not that "relevant"
