### ISSUE TITLE
[V10] Cannot Print Anything (SyntaxError: JSON Parse error: Unexpected EOF)

### ISSUE THREAD

**Issue by august434** [odoo/odoo#20366]
**Dear Everyone,**

Please kindly help me solve this headache issue. **Cannot print anything from Odoo.** Been stuck with it for a year now.

Please any expert help me.

Thank you so much.

**Impacted versions:** 
Odoo Version 10 running on Ubuntu 16.04
Nginx as reverse proxy

**Steps to reproduce:** 
(1) Install wkhtmltopdf
(2) Re-install many time

**Current behavior:**
The error show as below when try to print any report.

```
SyntaxError: JSON Parse error: Unexpected EOF

https://august.net:7070/web/content/248-cd4137d/web.assets_common.js:3038
Traceback:
parse@[native code]
https://august.net:7070/web/content/248-cd4137d/web.assets_common.js:3038:384
dispatch@https://august.net:7070/web/content/248-cd4137d/web.assets_common.js:637:456
handle@https://august.net:7070/web/content/248-cd4137d/web.assets_common.js:610:178
```

**Expected behavior:**
Can successfully print.

**Best Regards,
August**

**Comment by Yenthe666** [comment]
Hi @august434,

Have you ever updated your Odoo codebase to the latest version?

**Comment by august434** [comment]
Hi @Yenthe666 ,

I just make a newly installed last week.

Odoo 10.0

Thank you

**Comment by Yenthe666** [comment]
@august434 can you reproduce this on an official runbot (at runbot.odoo.com)?

**Comment by august434** [comment]
Hi @Yenthe666 ,

How does Runbot work?

Thank you.

**Comment by Yenthe666** [comment]
Hi @august434,

The runbot are all test instances of Odoo where you can test on.
On the left side you see the Odoo version of the test instance (10.0 and 11.0 in my screenshot) and you can choose a database by clicking on the blue button (also marked in my screenshot):
![image](https://user-images.githubusercontent.com/6352350/32090156-5a840458-baee-11e7-8d3b-b9de195d3ea7.png)
After clicking on the button you will see a login screen where you can login with `admin` as username and password.

Regards,
Yenthe

**Comment by august434** [comment]
Dear Yenthe,

I can print as PDF on the Runbot test.

However, for my own server it's still cannot print by showing an error message as described above.

Thank you so much.

Best Regards,
Kridsakon

**Comment by august434** [comment]
Dear @Yenthe666 ,

I can print as PDF on the Runbot test.

However, for my own server it's still cannot print by showing an error message as described above.

Thank you so much.

Best Regards,
Kridsakon

**Comment by Yenthe666** [comment]
Hmm, which version of Wkhtmtopdf do you have? How do you install and deinstall it multiple times? Does it also happen when you just install wkhtmltopdf once?

**Comment by august434** [comment]
Dear @Yenthe666 ,


My installed version is 0.12.4. It's happened since the first time install.

Thank you.


Best Regards,
Kridsakon

**Comment by W360S** [comment]
Hello @august434 @august434 you need to test the Wkhtmtopdf on vps to check it work or not first. then go to odoo and try to print
here is the command: wkhtmltopdf http://google.com google.pdf
here for more information
https://wkhtmltopdf.org/
and here for successfull install https://github.com/W360S/ODOO
hope that work to you :) goodluck

**Comment by Yenthe666** [comment]
@august434 have you tried the proposal from @W360S? (Thanks @W360S)

**Comment by W360S** [comment]
you're welcome :)

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no feedback in a few months.

Regards,
Yenthe
