### ISSUE TITLE
Unknown CORS error when connecting to Google Analytics

### ISSUE THREAD

**Issue by eduquintana** [odoo/odoo#20365]
Impacted versions: Odoo 11

Steps to reproduce:

1. Install odoo 11 in Ubuntu 16.04
2. Install apache and the module proxy-uwsgi and do the process to redirect port 8069 to 80.
3. Follow the steps in this pages to configure Google Analitics:
https://www.odoo.com/documentation/user/11.0/website/optimize/google_analytics.html
https://www.odoo.com/documentation/user/11.0/website/optimize/google_analytics_dashboard.html
4. After that I tried to configure my panel in Odoo website to connect my account to google analytics and receive following error:  
Error:
Unknown CORS error

An unknown CORS error occured. The error probably originates from a JavaScript file served from a different origin.

Current behavior:
I receive this error:

Error:
Unknown CORS error

An unknown CORS error occured. The error probably originates from a JavaScript file served from a different origin.

I notice in my google analytics account that I can see my information, but I cannot see the same in odoo web panel.

Expected behavior:
I expect to successfully connect my google analytics accout to odoo
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be does this ring any bells to you buddy?

**Comment by JKE-be** [comment]
Are you sure that in your Google Anlaytics Account, Odoo is well whitelisted as origin?

https://www.odoo.com/documentation/user/11.0/_images/google_analytics_authorization.png

**Comment by eduquintana** [comment]
Yes, of course i did that

**Comment by JKE-be** [comment]
@eduquintana 

If you can reproduce it on runbot let me know, and I will check it.

But until now, I cannot reproduce your issue.

**Comment by rdeodoo** [comment]
Hi @eduquintana 
Could you check on your browser console if you have a more specific error? 
This error comes from the injected analytic file from google. For security reason, your browser may show the error in your console but it won't let the code access it.
Therefore, we can't retrieve it to display it, so you see that error message that is not telling anything about the error.

**Comment by khaungyemin** [comment]
i am facing this issue ! what will be the final resolution?
please let me know how to solve.thz

**Comment by JKE-be** [comment]
@khaungyemin

It is because you don’t whitelist the correct domain !
You can check in console chrome the message.

kr

**Comment by ozentella** [comment]
If even with the  right domain you  are receiving the CORS error, you may try disabling the Demo Account in google analytics side.
