### ISSUE TITLE
[11.0] l10n: Issue on "Partner" translation

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20371]
Impacted versions:
11.0

Steps to reproduce:
Install a database with es_DO.

Current behavior:
All places where the word partner is found, it translate to a bunch of symbols with the translation in the middle: 
![image](https://user-images.githubusercontent.com/16890942/31872376-7d6d80a6-b789-11e7-948b-329a0b350ce8.png)

Expected behavior:
Correct translation without bunch of symbols 

cc: @mart-e

**Comment by Yenthe666** [comment]
That actually looks like somebody f***ed up the translation files.. @mart-e will surely have a look at this soon.

**Comment by mart-e** [comment]
Thanks, fixed at 0ad610672b1
