### ISSUE TITLE
Internal Error 500 when login 

### ISSUE THREAD

**Issue by aleifuu** [odoo/odoo#20387]
Impacted versions:
Odoo10
Steps to reproduce:
Create any user, and set him/her to be non-Employee on his/her Access Rights
Current behavior:
System spits out Internal Error 500
Expected behavior:
I would have expected a warning or a message would have been a better alternative, rather
than straight to Internal Error 500
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @aleifuu,

Thank you for your report.
What exactly do you mean with "...and set him/her to be non-Employee on his/her Access Rights..."?
I just made a new user without any problems:
![image](https://user-images.githubusercontent.com/6352350/31892282-ec312fcc-b808-11e7-9438-70ac115ff3d2.png)

**Comment by aleifuu** [comment]
Hi @Yenthe666 , 

Thanks for your quick reply. This is why I like posting more on gitHub rather than Odoo's official forum, where less people reply unfortunately

Here's what I have
![screenshot 2017-10-24 at 9 24 46 am](https://user-images.githubusercontent.com/21986424/31922145-9560e63e-b89d-11e7-809b-003e95cb0b3d.png)

Here, the user _cashier@badminton.com_ either have choice to be Employee, Officer. Manager or None. Just set to None for this user and when you try to login as _cashier@badminton.com_, Odoo will go straight blank white page with typical 500 internal error message, the kind that imbues fatal error

**Comment by Yenthe666** [comment]
Hi @aleifuu,

Thanks for the feedback. I really can't get it reproduced though. I've made a user with no access rights - I can login and see the portal.
I made a user with basic rights to one module - the user can login just fine.
Can you reproduce it on a runbot (at runbot.odoo.com)?

**Comment by aleifuu** [comment]
I'm not sure, but I can give it a try

**Comment by Yenthe666** [comment]
You do have acces. Go to http://runbot.odoo.com/runbot/repo/git-github-com-odoo-odoo-1?search=, choose an Odoo 10 (marked by the 10.0 at the beginning) and click on the blue button to login. Username and password are both admin. 😉 
![image](https://user-images.githubusercontent.com/6352350/31927666-5b7522ee-b895-11e7-9d4e-b8764455b44e.png)

**Comment by aleifuu** [comment]
hmm, first time using it LOL. seems I do have access after all =). Okay, I'll give it a go

**Comment by aleifuu** [comment]
Well, I could not replicate on the runbot. But it definitely happens on my Odoo10's raspberry pi 3

And I was downloading from the official https://www.odoo.com/page/download

I suppose we can close this, as this is probably affecting only a small number of people ( or just me :( lol )
