### ISSUE TITLE
Stock Availability on Product is wrong, take all childs's locations warehouse, must be take only locations type internal

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#20397]
**Impacted versions:**
Tested today on runbot, V8, V9, V10, V11, master
**Steps to reproduce:**
On any instance of runbot, any product type stockable with stock on 2 or more locations type internal and same parent view for locations.
For example, product [LAP-CUS] Laptop Customized, on form view Stock on Hand is 85 Units
![image](https://user-images.githubusercontent.com/7775116/31912106-7ef6db64-b808-11e7-934b-a42a4e61cef6.png)
Stock on WH/Stock/Shelf 1 is 80 Units
Stock on WH/Stock is 5 Units
![image](https://user-images.githubusercontent.com/7775116/31912241-d6919184-b808-11e7-9d26-99b9119b9b39.png)

It is correct, two locations are type internal.

But if change type on location WH/Stock/Shelf 1 to other type(production for example)
![image](https://user-images.githubusercontent.com/7775116/31912358-390d24ae-b809-11e7-8ffb-8fb577ea940b.png)

Open form view again and stock on hand is same 85 units
![image](https://user-images.githubusercontent.com/7775116/31912387-5abc2708-b809-11e7-825d-c050b1bbf9ec.png)
Now open quants view and only show one line of location type internal(5 units), but location type production is hide(80 units). 
![image](https://user-images.githubusercontent.com/7775116/31912460-99e905d6-b809-11e7-8d46-cdf430ae9ed5.png)

Stock on hand must be computed only with locations type internal, but is compute by parent left and parent rigth of view location on warehouse. It is wrong, must be only type internal.

Error on function _get_domain_locations_new, only filter by parent left and parent_right, but must be add filter by **('location_id.type','=','internal')**

**Current behavior:**
Stock is computed from parent left and parent rigth locations
**Expected behavior:**
Stock must be computed only with locations type internal.
Video/Screenshot link (optional):

**Comment by nhomar** [comment]
As you see.

This is a normal behavior in Odoo since A LOT of time.

You CAN NOT change the type of a location because you will get this result.

i.e: What you expect happend it chancge to loss? to production? to customer?

the expected behavior is so variant, you can lock this change with a simple server action if you have curious customers but it is Ok for me the current behavior.

**Comment by celm1990** [comment]
OK, I can not change the type of location, but has no constraint.

On example change type of location(more speed on bug desciption) but if create a new location type customer with parent location is  type view and this parent is Warehouse view location(field view_location_id), [here](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/product.py#L190) take this location type view, and [follow function](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/product.py#L194) take all childs locations for location type view(including all locations for all types, not only type internal)

Example create new location type customer and parent location choose  a location used on warehouse(field view_location_id, for example use location WH is used on warehouse)
![image](https://user-images.githubusercontent.com/7775116/31918262-6ee52ae6-b821-11e7-922a-8075d40032d7.png)

Create a inventory adjust(inventory adjust on customer location is not real, only for purpose example for create some stock move).

Stock before inventory adjust is 85 on 2 locations
![image](https://user-images.githubusercontent.com/7775116/31918736-e7ddd694-b823-11e7-8d6a-cccf175e6eb2.png)

Validate inventory for 10 unit on location type customer
![image](https://user-images.githubusercontent.com/7775116/31918757-fe77e6ba-b823-11e7-92e4-d6953d6e9510.png)

Refresh product view and now stock is 95, bus open quant view, only show 85.

![image](https://user-images.githubusercontent.com/7775116/31918974-15638446-b825-11e7-909b-a1ce4b35b818.png)

![image](https://user-images.githubusercontent.com/7775116/31918987-1ea14af2-b825-11e7-8934-dc0a04bec252.png)


Because, New location named _test location_ has parent view **WH** is used on warehouse, and computing stock **take all child locations** must be take locations type internal.
![image](https://user-images.githubusercontent.com/7775116/31918995-2fa92414-b825-11e7-8726-125da06ebe7d.png)


This example is using location type view and creating inventory adjust, but is reproducible on any location with parent location is used on warehouse.

**Comment by celm1990** [comment]
Point here is not change location type, point is **[this function](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/product.py#L193)** take all child locations of any types, must be take only internal type

**Comment by Yenthe666** [comment]
@jco-odoo could you have a look please? To save you some time: the last comment is the essence of the whole thread. 😉

**Comment by jco-odoo** [comment]
The logic of the quantity on hand is just taking what is in your warehouses.  Location types is for when you do reservation, when quants need to be created, to see if it is incoming or outgoing, ...

**Comment by celm1990** [comment]
Hi,

But exist difference on form view, Quantity on hand show a quantity, open quants view show other quantities, is inconsistent. Wrong configuration, can be, but inconsistency is the point here.

Examples on real case a client report this bug from production orders, when create a location type production and picking for raw materials move products to new location. Products show quantity wrong on form view but at open quants show  quantity correct, inconsitency.

PS: Sorry for my bad english :wink:

**Comment by nhomar** [comment]
@celm1990 

The point is that (I think) You are not understanding the contraints (yes that should be nice to have a LOT of checkings) but the location configuration is properlly explained into the code as you poited properly.

Customers and Suppliers locations can not be bellow an internal location.

I mean "The true is in only one place **the code**" try to follow what code says because it is not planned (AFAICK @lap-odoo can be more precise here) put tons of constrains into the configuration of locations, that's considered a technical feature and not all options are fully supported as you "think" they can work.

IMHO the behavior your are having is correct.

**Comment by lap-odoo** [comment]
@celm1990 I agree with @nhomar. 

So no changes planned in stable versions. 

However, we will put more constraints in the configuration of the locations (for next versions) to avoid the creation of unsupported configuration.
