### ISSUE TITLE
[10.0] Discard test dialog triggers cannot get property error

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#20405]
Impacted versions: 10.0

Steps to reproduce:
1. Click on "Tests"
2. Click on "Discard" when the wizard opens:
![image](https://user-images.githubusercontent.com/6352350/31926836-674e5d6e-b891-11e7-92ef-dd9bccc5b94f.png)

Current behavior: Uncaught TypeError: Cannot read property 'get_nb_views' of null

Expected behavior: Wizard closes without errors.

**Comment by Yenthe666** [comment]
@ged-odoo this is a JS bug, could you have a look please?

**Comment by Yenthe666** [comment]
OPW 786866

**Comment by nle-odoo** [comment]
This should be solved in 10.0 with https://github.com/odoo/odoo/commit/1ce4f15c39b (it is a backport of the solution available in 11.0 ).
