### ISSUE TITLE
[8.0] regression: wrong CSS style of tree view in print mode

### ISSUE THREAD

**Issue by rvalyi** [odoo/odoo#2040]
Hello, in v7 you introduced a nice print CSS for tree view. So for instance when printing the list of product we had in v7:
![v7](https://cloud.githubusercontent.com/assets/16926/4070748/9d6cf26e-2e62-11e4-9ccf-40b69e529f1b.png)

But now in v8, it seems that the specific print CSS is not applied anymore: there is the browser scrollbar instead of the pagination, no more odd/even styling:
![v8](https://cloud.githubusercontent.com/assets/16926/4070763/e3bcda4a-2e62-11e4-88c2-097f78d124c7.png)

**Comment by Yenthe666** [comment]
Hi @rvalyi,

Thank you for your report.
This is actually still the same as the moment you've reported it and I personally liked the old CSS print more too.
@mart-e could you give feedback perhaps?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @rvalyi,

I'm closing this as Odoo 8.0 is no longer supported.
I'll label this bug report as wishlist though so it will keep popping up.

Regards,
Yenthe
