### ISSUE TITLE
[10.0] Longpolling requests fail from time to time

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#20400]
We noticed that the longpolling request keep failing by monitoring the network using the developer tool in Chrome. We are using Odoo 10.0 enterprise version.  

Within the "Network" tab of the developer tool, we find out most of the "poll" request is failing, i.e. Status Code: 502 Proxy Error. 
![developer_tool](https://user-images.githubusercontent.com/27185427/31922431-716ea4fa-b8a7-11e7-8242-997f1ff7ba8d.png)

However, when we try to use LiveChat in Odoo, the "poll" request followed by the "message_post" request is successful.
![success](https://user-images.githubusercontent.com/27185427/31922440-785f93c8-b8a7-11e7-94ba-d07ba4186fcf.png) 

Environment information for our Odoo 10 instances: 
Within the configuration file: 
longpolling_port = 8072 
proxy_mode = True 
workers = 2 

We are using Apache/2.4.18 (Ubuntu) on our sever and following is part of the virtual host settings related longpolling: 
<VirtualHost *:443> 
... 
<Proxy *> 
Order deny,allow 
Allow from all 
</Proxy> 
ProxyRequests Off 
ProxyPass /longpolling/ http://127.0.0.1:8072/longpolling/ 
ProxyPassReverse /longpolling/ http://127.0.0.1:8072/longpolling/ 
ProxyPass / http://127.0.0.1:8069/ 
ProxyPassReverse / http://127.0.0.1:8069/ 
RequestHeader set X-Forwarded-Proto "https" 
... 
</VirtualHost> 

Do anyone encounter similar issue?

**Comment by sivaj** [comment]
I want Unsubscribed this mail imme... Plz help me...
