### ISSUE TITLE
setup_dev.py missing in odoo 11

### ISSUE THREAD

**Issue by tluanga** [odoo/odoo#20412]
Impacted versions: 11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @tluanga,

Please add more information and details to a bug report. Nobody can help you based on a title with no information or context. See https://github.com/odoo/odoo/wiki/BugManagement

Regards,
Yenthe

**Comment by tluanga** [comment]
I tried to install odoo 11 using this ./odoo/setup/setup_dev.py setup_deps command. but the file doesnt exist. kindly help

**Comment by xmo-odoo** [comment]
@tluanga that file has indeed been removed but even before it was intended as a setup for internal developers of the Odoo company (e.g. predicated upon the ability to push to the odoo-dev organisation's repositories and possibly odoo as well), setting up Odoo via this script was never a good idea for external developers.

**Comment by tluanga** [comment]
then what would be the best setup for external module developer like us.

**Comment by xmo-odoo** [comment]
> then what would be the best setup for external module developer like us.

Whatever works for you? All the script would do for you was:

1. an overly complex way of "git clone https://github.com/odoo/odoo"
2. install postgres and the dependencies in debian/control *if you were using debian*
3. create the local user in pg again if you were using debian

**Comment by Yenthe666** [comment]
An alternative way to install Odoo for example: https://github.com/Yenthe666/InstallScript 😉 
Or check the official guides at https://www.odoo.com/documentation/11.0/setup/install.html
