### ISSUE TITLE
[8.0] Both the compose new message and the top-right email icon are missing.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#2042]
This pair of commits (earliest first):
-   commit e6f8666b521fe8c2522d6e94c0c3def54a5f73ed
-   commit 5209fbc7ed9fcad966ab064654a8a8697142be42

Remove the ability to compose email to arbitrary partners (i.e typing an email address directly).  The first commit removes the button from the wall, cause the icon is already there.  And the second commit removes the icon, cause the wall has the same functionality.  They seem to be getting into each other's way.

The wall recovers this functionality (though hidden) after the HR addons is installed.  The "Share with..." box can be expanded and then used to send emails to arbitrary partners.  But IMO the feature is now hidden.

Would you please either get the icon back or the button?  

I have tested (locally) that reverting the second commit is sufficient for getting the icon to function again.  The first commit touches other files so reverting needs to be done "surgically".

**Comment by peefour** [comment]
any update on this?
I am new to odoo, and I do not understand why there is no "compose email" button as this functionality is crucial!

tx!

**Comment by mvaled** [comment]
Hi @tde-banana-odoo,

Could you check this issue?

**Comment by mvaled** [comment]
Hi @odony,

Can you vouch for this issue to be responded? 
There's probably an alternative solution to this issue, since it was reported long ago.  I haven't be able to check any new functionality in Odoo regarding this.

Best regards,
Manuel.

**Comment by tde-banana-odoo** [comment]
Actually it has been put back in master (especially in saas-6). Not sure about the potential backport.

**Comment by mvaled** [comment]
Le 13/03/15 09:26, Thibault Delavallée a écrit :
> Actually it has been put back in master (especially in saas-6). Not sure
> about the potential backport.

When I tested back then, simply reverting the commit that removed icon
worked.

**Comment by yelizariev** [comment]
I'd like to post here short instruction how to fix this issue.

Just execute command below in odoo source path

    git revert 5209fbc7ed9fcad966ab064654a8a8697142be42

**Comment by isometriq** [comment]
Many thanks for that snippet, I will try that and get back with the result.

**Comment by edlwise** [comment]
Thank you @yelizariev it works for me

**Comment by willardjansen** [comment]
what is odoo source path?

**Comment by yelizariev** [comment]
You can apply the [patch](https://github.com/odoo/odoo/files/441804/commit_5209fbc.txt), if your installation doesn't have git history:

    patch -p1 -R < /tmp/commit_5209fbc.txt

I made it with a command:

    git format-patch 5209fbc^..5209fbc --stdout > /tmp/commit_5209fbc.txt

**Comment by dreispt** [comment]
Can this be closed?

**Comment by shingonoide** [comment]
@dreispt I don't think so, there's a unresolved problem here.
Why Odoo version 9 have the message icon but the version 8 has not?
It's needs fix in main repository, can anyone at Odoo see and handle it? just guessing...

**Comment by Yenthe666** [comment]
Hi @shingonoide and @mvaled,

There has been an official response from Odoo saying that we no longer want this option. Odoo is not a mailclient, it is an ERP system. You can easily use the chatter, mail templates and so on to communicate.

Regards,
Yenthe

**Comment by yelizariev** [comment]
I missed that 10.0 doesn't have Send Mail button https://github.com/odoo/odoo/commit/452bf80affd678884c13d0a076de34c82f3a6127
Possible solution for ones who still need this button: [mail_sent](https://github.com/it-projects-llc/mail-addons/tree/10.0/mail_sent) module -- it adds "Sent" menu and "Send mail" button

**Comment by levkar** [comment]
@yelizariev it seems like it hasn't been ported to 10.0 yet.

It would have been better having it without installing two modules for just a "send button", .
