### ISSUE TITLE
[10.0]EE account_reports: Can't collapse, expand all.

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#20439]
### Impacted versions:
10.0

### Steps to reproduce:
- Install account_reports
- Open a Trial Balance in accounting with more than 400 accounts
- Export the Trial Balance to PDF or XLS

### Current behavior:
- If I'd like to see the detail of each account I have to click each one of it.
- To export the detail of the whole report, I also have to click on each account and open it.

### Expected behavior:
Have a way to mass expand / collapse accounts

@lap-odoo

**Comment by lap-odoo** [comment]
@gustavovalverde : You mean the General Legder (not the trial balance) ? 

This improvement has already been done in the V11 : https://drive.google.com/a/odoo.com/file/d/0B0ITmdw6h3ZrWW5lN3UxN1VEeGc/view?usp=drivesdk

**Comment by Yenthe666** [comment]
@gustavovalverde can you confirm you where talking about the general ledger?

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

I'm closing this bug report as there has been no feedback in a few months.
Don't hesitate to post back if you can still reproduce it and can answer the question.

Regards,
Yenthe
