### ISSUE TITLE
[11.0 Enterprise] pos_loyalty - Discount reward type fails completely

### ISSUE THREAD

**Issue by jacob1264** [odoo/odoo#20432]
## Impacted versions:
11.0.1.0

 ## Steps to reproduce:

Create loyalty program for POS as normal
Add loyalty program rules as normal
Add Reward with "Discount" Reward Type

## Current behavior:

Discount is not applied properly, discount seems to be arbitrary, the total order then increases by the false amount instead of decreasing.

e.g: Reward stipulates Product X to be Discount 50% 

1. Product X added to cart, 

2. Proper reward selected

Cart adds additional Product X discount as item at incorrect price.

Discount amount (negative) subtracted to line item as negative incorrect amount, increasing total instead of decreasing it.

## Expected behavior:
Reward discount should be applied to relevant order line (if present), or should add the product with the discount to the order.

This is an enterprise module that I do not have access to, I cannot offer a fix myself.

 ## Suggested temporary solution:
This module should be modified to disable the Discount reward type as it does not behave at all like designed.

Unit tests should be implemented to ensure proper pos_loyalty functionality

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7730947/31953669-68a78ca6-b898-11e7-9dbc-2a8bf82beccb.png)

**Comment by jorenvo** [comment]
Thanks for the report. This was fixed in 9.0 and 10.0 with 33d20a224164cd83f09018addcf02496f22bced2. This patch will be forward-ported to 11.0 soon.

**Comment by NathanQj** [comment]
Interestingly enough, what's been pointed out as "Rewards products with a negative price do not decrease the order's price but increases the price instead" is still today's behavior on V12.

No matter if you set the "Reward Product" as -15$ or as 15$, you can't get the order to be subtracted $15.
