### ISSUE TITLE
[account_follow_report] Does not work with several journal items with date due

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#20440]
Impacted versions:
* 11.0

Steps to reproduce:
* Create several invoice with date due

Current behavior:
* Report does not work

Expected behavior:
* Report must work

Video/Screenshot link (optional):
https://youtu.be/_e8P5upxWDw

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look when you've got time please?
