### ISSUE TITLE
Critical: Infinite number of quotations are creating when a public user tried to update the Cart line Quantity field with a non-integer value in website.

### ISSUE THREAD

**Issue by vishnumurali1992** [odoo/odoo#20482]
Impacted versions: 11, 10.  Probably present in older versions

Steps to reproduce: Open up Odoo website(front end). as a public user add any one of the products into the cart, go to '/shop/cart' page and in the product quantity, instead of giving an integer number, give a random test string eg: 'abcd'. refresh the quotations menu in the backend repeatedly to see the quotations created

This will trigger deleting the sale order line of the corresponding order in the backend as the system assumes the quantity value to be non-integer.

For some reason the unlink call is happening recursively and if (only if) the user is not logged in(public user), quotations will be created and recursively and sale line is unlinked from them but the sale.order record will stay.

Current behavior: An infinite number of quotations are created by a public user of the system (leave the page open, it can go on forever). the system will be flooded with quotations from public users(without any sale line)

Expected behavior: Not to create quotations infinitely

Video/Screenshot link (optional):
![28152673-56d31c22-67bf-11e7-8fd8-f9530aa85e9f](https://user-images.githubusercontent.com/33111542/32036002-910a0ce8-ba3a-11e7-93bf-2054ba8609fb.png)

**Comment by Yenthe666** [comment]
Hi @vishnumurali1992,

Thanks a lot for your report. I've just tried it and it seems to work without any problems.
I've changed the quantity on the product form, in the dialog and on the checkout and still there is just one order.
Can you still reproduce this on an official runbot (at runbot.odoo.com)? Do you have any custom development on your environment? Have you tried updating your Odoo?

Regards,
Yenthe

**Comment by vishnumurali1992** [comment]
Hi,
 Sorry that you couldn't reproduce it, I have tried with the nightly latest build of odoo-11 in the local server without any custom modules, still the same is happening.

**Comment by Yenthe666** [comment]
@vishnumurali1992 can you please try to reproduce this on an official runbot (at runbot.odoo.com?)

**Comment by vishnumurali1992** [comment]
Sure, please try with base database...

**Comment by vishnumurali1992** [comment]
Hi,
You can reproduce the bug in runbot, the demonstration is attaching with the same.
[bug_report.ogv.zip](https://github.com/odoo/odoo/files/1426692/bug_report.ogv.zip)

**Comment by Yenthe666** [comment]
@JKE-be can you check?

**Comment by rdeodoo** [comment]
Fix landed [in 9.0](https://github.com/odoo/odoo/commit/82bde85030b58959bba8efddb13746e5dc3e4601)
