### ISSUE TITLE
Google calendar Sync

### ISSUE THREAD

**Issue by necrodevz** [odoo/odoo#20481]
## Impacted versions: 
v10, v11, Online

## Steps to reproduce:
Set up Sync with Google calendar, attempt to sync. Have tried this with v10 community, v11 community and online. 

#### returns error (same for all versions):
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/google_calendar/controllers/main.py", line 43, in sync_data
    return GoogleCal.with_context(context).synchronize_events()
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 591, in synchronize_events
    res = recs.update_events(lastSync)
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 807, in update_events
    self.create_from_google(event, my_partner_id)
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 408, in create_from_google
    res = self.with_context(context_tmp).update_from_google(False, event.GG.event, "create")
  File "/odoo/odoo-server/addons/google_calendar/models/google_calendar.py", line 520, in update_from_google
    res = CalendarEvent.create(result).id
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 1443, in create
    meeting = super(Meeting, self).create(values)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/odoo/odoo-server/odoo/models.py", line 3834, in create
    self._fields[key].determine_inverse(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1041, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 840, in _inverse_rrule
    meeting.update(data)
  File "/odoo/odoo-server/odoo/models.py", line 5017, in update
    record[name] = value
  File "/odoo/odoo-server/odoo/models.py", line 5220, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/odoo/odoo-server/odoo/fields.py", line 949, in __set__
    record.write({self.name: write_value})
  File "/odoo/odoo-server/addons/google_calendar/models/calendar.py", line 25, in write
    return super(Meeting, self).write(values)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 1419, in write
    self.env['calendar.alarm_manager'].notify_next_alarm(partners_to_notify)
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 430, in notify_next_alarm
    notif = self.sudo(user.id).get_next_notif()
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 380, in get_next_notif
    for one_date in meeting._get_recurrent_date_by_event():
  File "/odoo/odoo-server/addons/calendar/models/calendar.py", line 567, in _get_recurrent_date_by_event
    return [d.astimezone(pytz.UTC) if d.tzinfo else d for d in rset1]
  File "/usr/lib/python2.7/dist-packages/dateutil/rrule.py", line 1164, in _iter
    advance_iterator(ritem)
  File "/usr/lib/python2.7/dist-packages/dateutil/rrule.py", line 1091, in __next__
    self.dt = advance_iterator(self.gen)
  File "/usr/lib/python2.7/dist-packages/dateutil/rrule.py", line 649, in _iter
    date = datetime.date.fromordinal(ii.yearordinal+i)
ValueError: year is out of range

## Expected behavior:
Sync events with google calendar.

**Comment by Yenthe666** [comment]
@JKE-be does this ring any bell?
@necrodevz do you have any way to easily reproduce this? I believe this is a default environment, without any custom development?

**Comment by JKE-be** [comment]
@Yenthe666 
seems like Google use a syntax of rrule that ODoo don't manage.
If we have the rrule that fail, we can check maybe to adapt the rrule parsing with Odoo.

@necrodevz 
Could you provide your dbname on online, like that I will be able to check the full traceback after a sync

**Comment by necrodevz** [comment]
@Yenthe666 
Yes it's a default install, no custom development. 

@JKE-be 
The db name online is dkb99.

**Comment by JKE-be** [comment]
db expired :/

**Comment by VBoucher** [comment]
We have the same bug. We use Odoo 11 Community on a private server (so no online database). Any idea what could be done to fix this? Or at least some debugging assumption?

Thanks

**Comment by necrodevz** [comment]
I have the same issue. I've done some traceback and have mostly concluded that the problem is Google's authenticatioion system. It expects the odoo instance to add a transformation to the year digits and spit out a realistic date. Whats been happening so far, in my opinion, is that the data being sent, when parsed, results in an object being generated for the year figure instead of plain digits. This is what's causing the year transform function generator to crash and throw an error. 

I may be wrong, I'm just a newbie programmer, after all. Just want to place a not here that this has never been resolved for my database. 

Seeking for answers <-

**Comment by JKE-be** [comment]
@necrodevz 

Have you a running DB with this bug?
Because as explained in a previous post, your database was expired, and I cannot reproduce the bug in local without more information.

@VBoucher 

Add an ir config parameter "calendar.debug_print"  to show more info in your logs. (each event, the date, what odoo try to do with the event, ...)
You can also add the "calendar.block_since_synchro" to make a side by side synchronization (instead to compare what has been changed these last week, it will take all the event from the last week)

**Comment by VBoucher** [comment]
I do not see changes to the log when I add the "calendar.debug_print" with value 1. With or without it, the log is the same. But, I do see the sync event similar to this one : 

> ---- A SYNC EVENT ---
May 23 17:22:07 Serveur odoo-bin[1022]:     ID          OE: False
May 23 17:22:07 Serveur odoo-bin[1022]:     ID          GG: uahlj168dp03c6ln4s7gup7hfc
May 23 17:22:07 Serveur odoo-bin[1022]:     Name        OE: False
May 23 17:22:07 Serveur odoo-bin[1022]:     Name        GG: b'tsdfgdgf'
May 23 17:22:07 Serveur odoo-bin[1022]:     Found       OE:False vs GG:  True
May 23 17:22:07 Serveur odoo-bin[1022]:     Recurrence  OE:False vs GG: False
May 23 17:22:07 Serveur odoo-bin[1022]:     Instance    OE:False vs GG: False
May 23 17:22:07 Serveur odoo-bin[1022]:     Synchro     OE:      False
May 23 17:22:07 Serveur odoo-bin[1022]:     Update      OE:      False
May 23 17:22:07 Serveur odoo-bin[1022]:     Update      GG: 2018-04-22 21:12:23.395
May 23 17:22:07 Serveur odoo-bin[1022]:     Status      OE:False vs GG:  True
May 23 17:22:07 Serveur odoo-bin[1022]:     Action      Create
May 23 17:22:07 Serveur odoo-bin[1022]:     Source      GG
May 23 17:22:07 Serveur odoo-bin[1022]:     comment     New EVENT CREATE from GMAIL}
May 23 17:22:08 Serveur odoo-bin[1022]: 2018-05-23 17:22:08,371 1022 INFO DB odoo.models.unlink: User #1 deleted bus.bus records with IDs: [171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 247, 300, 353, 380, 394, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 974, 975]


Then, I see this error : 

> May 23 17:22:16 Serveur odoo-bin[1022]: 2018-05-23 17:22:16,412 1022 ERROR DB odoo.http: Exception during JSON request handling.
2018-05-23 17:22:08,371 1022 INFO DB odoo.models.unlink: User #1 deleted bus.bus records with IDs: [171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 1
May 23 17:22:16 Serveur odoo-bin[1022]: 2018-05-23 17:22:16,412 1022 ERROR DB odoo.http: Exception during JSON request handling.
May 23 17:22:16 Serveur odoo-bin[1022]: Traceback (most recent call last):
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 647, in _handle_exception
May 23 17:22:16 Serveur odoo-bin[1022]:     return super(JsonRequest, self)._handle_exception(exception)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 307, in _handle_exception
May 23 17:22:16 Serveur odoo-bin[1022]:     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
May 23 17:22:16 Serveur odoo-bin[1022]:     raise value
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 689, in dispatch
May 23 17:22:16 Serveur odoo-bin[1022]:     result = self._call_function(**self.params)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 339, in _call_function
May 23 17:22:16 Serveur odoo-bin[1022]:     return checked_call(self.db, *args, **kwargs)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
May 23 17:22:16 Serveur odoo-bin[1022]:     return f(dbname, *args, **kwargs)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 332, in checked_call
May 23 17:22:16 Serveur odoo-bin[1022]:     result = self.endpoint(*a, **kw)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
May 23 17:22:16 Serveur odoo-bin[1022]:     return self.method(*args, **kw)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/http.py", line 512, in response_wrap
May 23 17:22:16 Serveur odoo-bin[1022]:     response = f(*args, **kw)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/controllers/main.py", line 43, in sync_data
May 23 17:22:16 Serveur odoo-bin[1022]:     return GoogleCal.with_context(context).synchronize_events()
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/models/google_calendar.py", line 589, in synchronize_events
May 23 17:22:16 Serveur odoo-bin[1022]:     res = recs.update_events(lastSync)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/models/google_calendar.py", line 805, in update_events
May 23 17:22:16 Serveur odoo-bin[1022]:     self.create_from_google(event, my_partner_id)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/models/google_calendar.py", line 406, in create_from_google
May 23 17:22:16 Serveur odoo-bin[1022]:     res = self.with_context(context_tmp).update_from_google(False, event.GG.event, "create")
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/models/google_calendar.py", line 518, in update_from_google
May 23 17:22:16 Serveur odoo-bin[1022]:     res = CalendarEvent.create(result).id
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/crm/models/calendar.py", line 38, in create
May 23 17:22:16 Serveur odoo-bin[1022]:     event = super(CalendarEvent, self).create(vals)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 1525, in create
May 23 17:22:16 Serveur odoo-bin[1022]:     meeting = super(Meeting, self).create(values)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/mail/models/mail_thread.py", line 231, in create
May 23 17:22:16 Serveur odoo-bin[1022]:     thread = super(MailThread, self).create(values)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/models.py", line 3315, in create
May 23 17:22:16 Serveur odoo-bin[1022]:     self._fields[key].determine_inverse(record)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/fields.py", line 1070, in determine_inverse
May 23 17:22:16 Serveur odoo-bin[1022]:     getattr(records, self.inverse)()
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 907, in _inverse_rrule
May 23 17:22:16 Serveur odoo-bin[1022]:     meeting.update(data)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/models.py", line 4493, in update
May 23 17:22:16 Serveur odoo-bin[1022]:     record[name] = value
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/models.py", line 4697, in __setitem__
May 23 17:22:16 Serveur odoo-bin[1022]:     return self._fields[key].__set__(self, value)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/odoo/fields.py", line 979, in __set__
May 23 17:22:16 Serveur odoo-bin[1022]:     record.write({self.name: write_value})
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/google_calendar/models/calendar.py", line 25, in write
May 23 17:22:16 Serveur odoo-bin[1022]:     return super(Meeting, self).write(values)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 1482, in write
May 23 17:22:16 Serveur odoo-bin[1022]:     self.env['calendar.alarm_manager'].notify_next_alarm(partners_to_notify)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 463, in notify_next_alarm
May 23 17:22:16 Serveur odoo-bin[1022]:     notif = self.sudo(user.id).get_next_notif()
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 413, in get_next_notif
May 23 17:22:16 Serveur odoo-bin[1022]:     for one_date in meeting._get_recurrent_date_by_event():
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 622, in _get_recurrent_date_by_event
May 23 17:22:16 Serveur odoo-bin[1022]:     return [d.astimezone(pytz.UTC) if d.tzinfo else d for d in rset1]
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/opt/odoo/odoo/addons/calendar/models/calendar.py", line 622, in <listcomp>
May 23 17:22:16 Serveur odoo-bin[1022]:     return [d.astimezone(pytz.UTC) if d.tzinfo else d for d in rset1]
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/usr/local/lib/python3.5/dist-packages/dateutil/rrule.py", line 1385, in _iter
May 23 17:22:16 Serveur odoo-bin[1022]:     advance_iterator(ritem)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/usr/local/lib/python3.5/dist-packages/dateutil/rrule.py", line 1302, in __next__
May 23 17:22:16 Serveur odoo-bin[1022]:     self.dt = advance_iterator(self.gen)
May 23 17:22:16 Serveur odoo-bin[1022]:   File "/usr/local/lib/python3.5/dist-packages/dateutil/rrule.py", line 859, in _iter
May 23 17:22:16 Serveur odoo-bin[1022]:     date = datetime.date.fromordinal(ii.yearordinal + i)
May 23 17:22:16 Serveur odoo-bin[1022]: ValueError: year is out of range

**Comment by Pootch75** [comment]
Hi,
has this bug ever been fixed? I am using version 10.0 community and I have the same error.
Plus, it raised with no apparent reason, before 10 jan 19 Calendar synchronized correctly, then suddenly this error appeared.

Is there a way to avoid it? Maybe versions 11 or 12 are working?
Thank you
