### ISSUE TITLE
[Bug] fields.Date.today() not return date as expected

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#20493]
Impacted versions: tested with version 9

Steps to reproduce:

Create a field with default value = `fields.Date.today()`, example:
`task_start_date = fields.Date(string='Start Date', default=fields.Date.today())`

Current behavior:
return the date when app start, not the date of current day (ex: if app start 2017-10-23, today = 2017-10-26, fields.Date.today() return 2017-10-23) 

Expected behavior:
return date = current date, not date when app start.

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
`default` can take either a value or a callable. Here you are giving it a *value* (the result of calling `fields.Date.today` when the server starts), Odoo is respecting your wishes by putting that value as the default for the field. This is bog-standard Python behaviour.

If you don't want that value, either pass the *method* to `default` or wrap the entire thing in a `lambda`. Either way, this is an issue with your code, not with Odoo.

**Comment by sharifulrocky** [comment]
You can try like this 
```
@api.model
    def _get_current_date(self):
        """ :return current date """
        return fields.Date.today()
start_date = fields.Date(required=True, default=lambda self: self._get_current_date())
```

**Comment by JordiMForgeFlow** [comment]
Hi,

For future reference, a solution can be to use the following:

`default=fields.Date.context_today`

You will need first to check if it is available in the Odoo version you are using
