### ISSUE TITLE
[8.0] "Missing document" when unlinking because of computed field

### ISSUE THREAD

**Issue by Softdil** [odoo/odoo#20496]
Impacted versions:
8.0

Steps to reproduce:
Create a computed field with store=True and then try to delete a record that has that computed field.

Current behavior:
It says "Missing document" because it tries to write this computed field after deleting the record.

Expected behavior:
Just delete the record and forget about the computed field since the record won't be there anymore

Code:
```
    @api.depends('phonecall_ids','phonecall_ids.name')
    def _compute_llamadas(self):
        for partner in self:
            valores_llamadas = ''
            contacts = self.search([('parent_id','=',partner.id)])
            if contacts:
                for contact_partner in contacts:
                    llamadas = self.env['crm.phonecall'].search([('partner_id','=',contact_partner.id)])
                    for llamada in llamadas:
                        valores_llamadas += ' ' + llamada.name
            llamadas2 = self.env['crm.phonecall'].search([('partner_id','=',partner.id)])
            for llamada in llamadas2:
                valores_llamadas += ' ' + llamada.name
            partner.valores_llamadas = valores_llamadas

    valores_llamadas = fields.Text(string='Llamadas', compute='_compute_llamadas',store=True)
```

Could it be because of the depends? Maybe the unlink in cascade of the phonecalls are trying to do the write of the "valores_llamadas" field?

Thanks in advance.

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
Perhaps you're better off to create a question on help.odoo.com.

Regards,
Yenthe
