### ISSUE TITLE
POS reload view when data object change

### ISSUE THREAD

**Issue by Prashant31892** [odoo/odoo#20505]
Impacted versions: 10

Steps to reproduce: We are now fetching data using web services and based on that trying to change UI on POS but didn't success on it, So how can we change UI without reload POS  

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Prashant31892,

The Odoo Github tracker is only used for bugs in the official code. This is not the place to ask questions or get your custom development solved.
Please ask this question at the official help forum (at help.odoo.com)

Regards,
Yenthe
