### ISSUE TITLE
[10.0.20171023] Fiscal positions no more taken into account in POS

### ISSUE THREAD

**Issue by MaxEvron** [odoo/odoo#20519]
**Impacted versions:**
Odoo 10.0-20171023 

**Steps to reproduce:** 
Configure different Fiscal Positions on a POS, including _Import/Export + DOM-TOM_ or any custom fiscal positions (ex. for France FP where TVA/tax is calculated from TTC/net amount).

**Current behavior:**
Nothing changes when selecting another fiscal position, default taxes set on products are applied.

**Expected behavior:**
Tax are calculated according to selected Fiscal Position. Seems to be a regression, works fine on Odoo 10.0-20170725. Noticed a change between Odoo 10.0-20170725 and Odoo 10.0-20171023: there is a new "Active" check box in account.tax model, maybe not taken into account in POS.

**Video/Screenshot link (optional):**
https://photos.app.goo.gl/DCPa6iZdNzMSkmYW2

**Comment by odony** [comment]
@smetl @qdp-odoo @nim-odoo maybe this is another example related to the rewrite of tax-included base/amounts computations? Could you double-check?

**Comment by nim-odoo** [comment]
As of today, it doesn't seem to occur anymore:
https://screenshots.firefox.com/HBRejlzCib5387al/276439-10-0-3b43dd.runbot9.odoo.com
https://screenshots.firefox.com/ly6pnhggLMqLVNnG/276439-10-0-3b43dd.runbot9.odoo.com

**Comment by odony** [comment]
@nim-odoo Thanks!

@MaxEvron Could you verify if the issue still happens for you with the latest v10? Otherwise we can probably close this issue.

**Comment by MaxEvron** [comment]
@odony : Update done, issue fixed. Closing the issue. Thanks. :+1:
