### ISSUE TITLE
Odoo 11 Calendar View

### ISSUE THREAD

**Issue by dairondv1986** [odoo/odoo#20537]
Impacted versions: 
11.0

Steps to reproduce:

- New Odoo compiled (python3 setup.py build) from latest published in odoo download page. Community - 20171017.
- Install Calendar module.
- Go to Calendar View and then create an event.
- Go to month(button) view
 * Drag and drop the event
 * Resize the event

Current behavior:
1. With the event created, if you drag the event to other day, the event drop into that day but automatically change the day to back one.
2. If you drag the event to extend it by 2 days, the action take place but do the same, change its start date to one day back.

Expected behavior:
- The event can't change start date.
- The event can't change state to all day.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Fixed a long time ago
