### ISSUE TITLE
[11.0] How to know odoo changelog?

### ISSUE THREAD

**Issue by W360S** [odoo/odoo#20547]
Hello, where can we know what's change in odoo in odoo when news thing come?
I cant find odoo changelog

**Comment by W360S** [comment]
need somethings like this :)
https://bitnami.com/stack/odoo/changelog.txt

**Comment by Yenthe666** [comment]
Hi @W360S,

You can basically all changes that are made to Odoo at https://github.com/odoo/odoo/commits/11.0
There is no such changelog in your local Odoo at the moment. You can however see when the latest update was done (if you install with git you can see the latest commit you fetched for example) so you know how 'old' your Odoo is.
If you need more information or help I'd suggest you to ask this on the official help forums (at help.odoo.com), as this bugtracker is only for bugs in the official Odoo code.

Regards,
Yenthe
