### ISSUE TITLE
[11.0] frontend assets not rendered.

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#20554]
front-end assets not rendered after restart without login. if first url have 404 status code. assets won't be generated. until a valid page would be requested. 

Impacted versions: 
-11.0 nightly package

Steps to reproduce: 
- logout is required for this. 
- website (installed) 
- stop/start odoo instance to regenerate assets
- enter random url to generate 404: http://127.0.0.1:8090/no-js-or-css-here

Current behavior:
- front-end assets not rendered

Expected behavior:
- front-end assets should be rendered

Video/Screenshot link (optional):
![screenshot from 2017-10-29 12-12-20](https://user-images.githubusercontent.com/6930079/32142569-a11c5c0c-bca2-11e7-9445-c2f2e895c3f1.png)

**Comment by Yenthe666** [comment]
@d-fence and @JKE-be perhaps something nice to check for the two of you?
