### ISSUE TITLE
[11.0] Product Variants separate notes

### ISSUE THREAD

**Issue by W360S** [odoo/odoo#20550]
I have a question. I try to make a product and add some variants attribute then try to add notes for each variants attribute but cannot do that. i go to products Variants => see each product Variants have separate the. anyone know how to add notes for each product variant?

**Comment by vcloud9ray** [comment]
The best place for questions on Odoo is help.odoo.com - this site is for posting Odoo bug reports. 

The guidelines for this site - and what is considered an issue - are posted at https://github.com/odoo/odoo/wiki/Contributing
