### ISSUE TITLE
[9.0] Stock picking not validated when (POS) selling under-stock products in 2 lines (one with 0 qty and other with non-0 qty)

### ISSUE THREAD

**Issue by vdewulf** [odoo/odoo#20552]
Impacted versions: 9.0 on commit e520aab

**Steps to reproduce:**
- prepare 2 stockable products available in POS, one with some stocks (qty on hand > 0) named Product 1 and another without stock (qty on hand =< 0) named Product 2

- Sell in a POS session the products following this sequence:

1. Product 1: 1 unit
2. Product 2: 0 unit (use backspace to make it display 0 but don't erase the line)
3. Product 1: 1 unit
4. Product 2: 1 unit

- Finalize the sale (proceed to payement and go to the next sale).

**Current behavior:**
In the Inventory, there is one stock.picking waiting for validation.
We have to manually validate the stock picking to have a correct stock in Odoo, after each working day.

**Expected behavior:**
In the Inventory, the corresponding stock.picking is marked as "Done". No manual operation is needed.

**Video/Screenshot link (optional):**
![issue_pos_stock_picking_initialdemand](https://user-images.githubusercontent.com/27895270/32133321-d2bacd16-bbd5-11e7-8802-13dc500808df.jpg)
![issue_pos_stock_picking_operation](https://user-images.githubusercontent.com/27895270/32133322-d3115cda-bbd5-11e7-9a9f-c4e62c07635d.jpg)

**Comment by DegroodtNicolas** [comment]
And when we try to validate these Stock Picking we receive an error
![image](https://user-images.githubusercontent.com/22113490/32134916-e23747c6-bbf6-11e7-8b28-050d4ef26218.png)

In the database, it looks like we have 2 stock_move for one stock_picking.

We then have to "Annuler la réservation" then "reserver" and then "validate"

**Comment by Yenthe666** [comment]
Hi @vdewulf,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
