### ISSUE TITLE
[11.0] Many2one Selection keyboard interaction in a x2m embedded list view

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#20553]
**Impacted versions:**
saas-16 and above

**Steps to reproduce:**

- Go to Purchase and open an order
- Take an existing line and remove the product string
- You will get a list of products to choose from
- Now try to use the cursor down/up to choose from the open selection

**Current behavior:**
Cursor down/up will go into the next line even if you are within a focused selection

**Expected behavior:**
Cursor down/up does what is expected normally in a selection

**Video/Screenshot link (optional):**
Ok, the cursor is not visible...but I hope reproduction is clear :-)
https://youtu.be/OQcNB4C1wLQ 

@ged-odoo @nim-odoo 
Hi Gerry, another one for you I guess ;-) Thank you for taking care :-)

**Comment by ged-odoo** [comment]
good catch. @wtaferner I am surprised, I really thought we had solved that issue a few months ago. I guess it was a similar, but slightly different issue.

**Comment by ged-odoo** [comment]
fixed in saas-16, commit https://github.com/odoo/odoo/commit/3c55407f111dcf44fdc0258b2352d208bdc71a0a
