### ISSUE TITLE
Package tracking does  not work out

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#20564]
Impacted versions: 10

Steps to reproduce:
inventory/Operations/Packages
press the package Transfer button on the right up corner
Current behavior:
the whole list of stock operation moves comes up
Expected behavior:
list for package tracking should be displayed
Video/Screenshot link (optional):

**Comment by ccandito** [comment]
Dear All,
any news on it?
thanks in advance
Claudio Candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

The Github bug tracker is on a best effor basis. If you have an enterprise license you can report a ticket at odoo.com/help - where response rates are way better.

Regards,
Yenthe

**Comment by sle-odoo** [comment]
this should be fixed by https://github.com/odoo/odoo/commit/64237aa3abc7b85fa6c513a4cd31aae1fc004e39

feel free to comment if i'm mistaken

regards
