### ISSUE TITLE
Translation Errors & Language Settings

### ISSUE THREAD

**Issue by palfrader** [odoo/odoo#2056]
I've had some troubles with languages and translations - My situation is as follow:
- I'm German
- My Computer OS is German
- My Odoo is Italian (as default language & user)
- My translated languages are italian, english, german and russian.

Some problems I have:
- On the website, default language is selected by browser language, it is impossibile to set default on all, some pop-ups are still german
- while translating text and products, some time I see all 4 languages, sometime I see only 3 and source
- often I have duplicated language values in the translation, see below:
  ![translation-quest](https://cloud.githubusercontent.com/assets/8029350/4075621/e4108f38-2eb1-11e4-80a7-58ad6729b535.JPG)

**Comment by Yenthe666** [comment]
Hi @palfrader,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
