### ISSUE TITLE
[Odoo 11]Unit Price set to Default when changing Ordered Qty 

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#20583]
Impacted versions: 11

Steps to reproduce:
1.Create Sale Order
2.Input any product suppose default price are 0 and ordered qty set to 1
3.Change Unit Price to any number,
4.Change Ordered Qty to any number , the unit price will come back to default value !

Current behavior:

Expected behavior:
1.When changing Ordered Qty it will not reflect the Unit Price like older version 

Video/Screenshot link (optional):

**Comment by vcloud9ray** [comment]
Isn't this expected behavior?  When you change the quantity, Odoo needs to refresh the pricing because a pricelist may have been defined to give a cheaper price with the increased quantity?

**Comment by sle-odoo** [comment]
@bst-odoo is this the expected behaviour? Thanks

**Comment by bst-odoo** [comment]
Yes it is intended for 2 reasons: 
- changing the quantity is like a new negotiation
- and as @vcloud9ray said, because of the pricelists

**Comment by kast69** [comment]
Is there a way to turn this feature off?
