### ISSUE TITLE
[10.0][11.0] The notification email action button text cannot be translated properly

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#20595]
**Impacted versions**: 10.0, 11.0

**Steps to reproduce**:
1. Switch your language to Finnish, or any other language where the word "View" has a different translation when it is used as a noun or as a verb.
2. Trigger any action in Odoo that sends a notification email for you (eg. a new message in a task's mail thread)
3. Open the email

**Current behavior**:
The action button (eg. "View Task") on the email doesn't make any sense in your language. In Finnish this is "Näkymä Tehtävä".

**Expected behavior**:
The action button on the email makes sense in your language. In Finnish it should be "Näytä tehtävä" or "Katso tehtävä".

**The problem**:
(ping @tde-banana-odoo) The [view title](https://github.com/odoo/odoo/blob/5a9f1539e19f13d3f3b0fced65759c4e72bc62c9/addons/mail/models/mail_thread.py#L671) is built without a context. It means that using languages which use a different word for View (noun) and View (verb, [imperative mood](https://en.wikipedia.org/wiki/Imperative_mood)) will display a nonsensical button text on the notification emails.

**Suggested fix**:
Part of the problem could be fixed by changing
```
view_title = '%s %s' % (_('View'), model_name)
```
to
```
view_title = _('View {}').format(model_name)
```
so we at least would have the possibility to distinguish between the noun form and the imperative form. This doesn't fix everything, because below the line 
```
view_title = _('View')
```
doesn't contain any hint about the context in which the word is used. And I don't know if including a context is possible in translations. If this line read
```
view_title = _('View Record')
```
it would be an easy task to translate properly, but this probably sounds too technical in English.

**Comment by Yenthe666** [comment]
More of interest for @mart-e - our localization expert.

**Comment by mlaitinen** [comment]
In fact we had some discussion about this with @mart-e on Transifex. https://www.transifex.com/odoo/odoo-10/translate/#fi/mail/98160213

**Comment by mart-e** [comment]
Thanks, changed that in 11.0 at dc6757032fe
