### ISSUE TITLE
New state for quotations

### ISSUE THREAD

**Issue by stabit** [odoo/odoo#20593]
Hi,

I'm new in Odoo, I'm using Odoo 8 and I want to create a custom state for my quotations between the drafts and sends, but my new not appear in state table.

I need some help to make this :(

**Comment by Yenthe666** [comment]
Hi @stabit,

Please ask help questions on the official help forum at help.odoo.com.
You can simply inherit the field and add your own state to it or you can use the parameter `selection_add` to add one key to the field (in the database).

Regards,
Yenthe

**Comment by stabit** [comment]
Ok thanks :D

Regards
Saber
