### ISSUE TITLE
[10.0] widget="radio" not working in Tree view

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#20600]
Impacted versions: 10.0

Steps to reproduce:

- Add boolean field in model.

- Visible that field in tree view with _widget="radio"_

Current behavior:

- Create/Edit record via tree view, we can not set it either _True_ or _False_.

Expected behavior:

- It should give us same result as in Form view worked.

Request:

- I got radio symbol in tree view but my concern with it's value

**Comment by qsm-odoo** [comment]
Hello,

Well `widget="radio"` is not supposed to work with a boolean (I am not sure what would be your use case for this). Even in form view, I don't think it works.

Note that in 10.0 widgets in the tree view and in the form view are different while they are all supposed to work in all views in 11.0. This is however the case only for compatible widget/field type pairs and I don't think a radio/boolean is one of those.

I am closing the issue, tell me if I misunderstood your request.

Regards
