### ISSUE TITLE
cr.commit() calls in unit tests are not ignored

### ISSUE THREAD

**Issue by yajo** [odoo/odoo#20603]
Impacted versions: 8.0-12.0

Steps to reproduce:

Write a test that either sends an email or calls any other method that handles manual commits.

Current behavior:

Test data end in the database.

Expected behavior:

Test data goes away with the test, AKA `cr.commit()` calls get translated into savepoint calls, AKA **tests should always use `TestCursor` as cursor**, to get this:

https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/odoo/sql_db.py#L457-L459

... or at least there should be a documented way on how and when get that kind of cursor for your test.

@Tecnativa

**Comment by mmcalea** [comment]
This seems to happen in 11 as well, even when you put self.registry.enter_test_mode()/self.registry.leave_test_mode() around the offending function.

**Comment by lreficent** [comment]
Same issue happening in v12 testing an extension for partner merge wizard.

**Comment by lreficent** [comment]
BTW, there is a "todo" comment in the commit line for my case:
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/wizard/base_partner_merge.py#L521

:wink:

**Comment by Yajo** [comment]
Thanks pals, I updated the description with the affected versions. Could you update the tags @Yenthe666 please?

**Comment by Yenthe666** [comment]
Done :)
