### ISSUE TITLE
website_slides (pdf): preview blocked, because mixed-content (http within https)

### ISSUE THREAD

**Issue by nikiwaibel** [odoo/odoo#20614]
Impacted versions:
* 11 (11.0.post20171028)

Steps to reproduce:
* have odoo on https (via loadbalancer, nginx, reverse apache, …)
* install website_slides
* upload a pdf (ie public channel)
* try to look at the uploaded slides / pdf (download is okay)

Current behavior:
* the webbrowser reports that the mixed content (http request within a https page) was blocked:
====
Mixed Content: The page at 'https://odoo.scitronix.com/slides/slide/scitronix-katalog-2017-de-small-6' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://odoo.scitronix.com/slides/slide/scitronix-katalog-2017-de-small-6/pdf_content'. This request has been blocked; the content must be served over HTTPS.
====
and so there is no preview of the PDF within odoo / the webbrowser.
* download is okay

Expected behavior:
* webside_slides should load the document via https (not http) and show/preview the PDF wihin odoo / the webbrowser

additional comments:

i've seen other reports about mixed content, but allowing this somehow in the browser or serving odoo over http is no option.

further, web.base.url  (starts with https://) and web.base.url.freeze are set correct.

the problematic lines of code may be within
* egrep -r -n slide[-_]?url /usr/lib/python3.6/site-packages/odoo/addons/website_slides/{static,view}
* /usr/lib/python3.6/site-packages/odoo/addons/website_slides/static/lib/pdfslidesviewer/PDFSlidesViewer.js

the URL is set to
  t-attf-data-slideurl="/slides/slide/#{slide.id}/pdf_content"
which seems correct. unfortunately i can't find out which place the first part (including http(s)) is added.

**Comment by sswapnesh** [comment]
@nikiwaibel  Could you please add `'proxy_mode = True'` in your odoo config file and check again.

**Comment by nikiwaibel** [comment]
@sswapnesh that works! thank you for that hint!!!

**Comment by mr-module** [comment]
i am facing similar problem. Even I did 'proxy=True' in config but still it gives me error below 

Mixed Content: The page at 'https://domain.com/shop' was loaded over HTTPS, but requested an insecure image 'http://domain.com/web/image/website.s_parallax_slider_default_image'. This content should also be served over HTTPS.
Can you please help me

**Comment by sswapnesh** [comment]
Hello @mr-module 
Add `proxy_mode = True` instead of `proxy=True` in your odoo config and try again.

**Comment by mr-module** [comment]
Hello @sswapnesh ,
Thanks for the quick response, but I did proxy_mode=True, still facing the problem!

**Comment by sswapnesh** [comment]
I am pretty sure this is working fine in all Case. (Just to Confirm - Make sure you are using that conf file, Restart your server and refresh you page)

**Comment by mr-module** [comment]
Actually, I configured https on my website. and as the image path is like - /web/image/....... 
So it takes full path as - http://domain.com/web/image/.... .but it should take as https://domain.com/web/image/.......

So, that's why I get warning mentioned above in my browser console. And this result in https [Not secure] on browser URL

**Comment by sswapnesh** [comment]
Change value for `web.base.url` from http//domain to http**s**//domain

and add system parameter for 
Key:` web.base.url.freeze`
Value: `True`

**Comment by mr-module** [comment]
I already changed web.base_url to https://domain.

Yeah I didn't freeze it but it was still https. when I got this issue.
Can you please help me over skype?

**Comment by sswapnesh** [comment]
Can't do skype at the moment.
You can mail me (Email is added in Github Profile)

**Comment by mr-module** [comment]
But what can be the resolve for this?

**Comment by nikiwaibel** [comment]
you may also need
`proxy_set_header Host $host;`
`proxy_set_header X-Real-IP $remote_addr;`
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`proxy_set_header X-Forwarded-Proto https;`
in your nginx config.

**Comment by mr-module** [comment]
It is apache2 so what shall I do?

Warm Regards

*Opensys*
Turning your imagination to solution
*Odoo | Python | Django | Ruby on Rails | React JS Development*
For More Info, Log on to - *http://www.opensysknw.com
<http://www.opensysknw.com>*

**Comment by mr-module** [comment]
Can you tell me exact file and where in that file I must write this
 RequestHeader set "X-Forwarded-Proto" "https"
I'm quite new with bitnami

**Comment by nikiwaibel** [comment]
@mr-module: sorry. i know nothing about the bitnami odoo docker container.

in general, if a loadbalancer is used:

- the odoo environment variable proxy_mode has to be set to True and
- within the loadbalancer config (apache, nginx, …) some HTTP request header have to be set and forwarded to odoo properly.

**Comment by asiamatrix** [comment]
I facing same error in Odoo 12 EE, Apache2 on Ubuntu 18.4

**Comment by lyprono** [comment]
Hello @mr-module i have got problem like this too and i have tired to set proxy_mode = True in odoo.conf 's docker but i still got this error .can help let me know about can fix this?
