### ISSUE TITLE
Error during insert multiple Serial Number

### ISSUE THREAD

**Issue by DbTechGit** [odoo/odoo#20610]
Impacted versions:
Odoo 11.0-20171023 Community Edition

Steps to reproduce:
I follow this Odoo documentation for enable the lots/serial number management.
https://www.odoo.com/documentation/user/11.0/inventory/management/lots_serial_numbers/lots.html

Current behavior:

When i click on the lot icon the pop-up appear correctly, but when i try to add a serial number an error is appeared with this message:" Unknown field lots_visible in domain".
I made a screenshot wich I attached below.

Expected behavior:
The behavior that should occur is what is described in the guide.

Video/Screenshot link (optional):

![pop_up_erp](https://user-images.githubusercontent.com/33259480/32233482-c8f7e868-be5a-11e7-96eb-2c65ed52c41a.png)

![lot_serial_error](https://user-images.githubusercontent.com/33259480/32233406-937b4b4e-be5a-11e7-8d65-6f9586bb347b.png)

**Comment by sle-odoo** [comment]
Hello,
I'm not able to reproduce your issue in the latest version. Please upgrade your codebase and upgrade the stock module (go to the apps menu, search for "Inventory" and hit the green "upgrade" button.

If the issue is still present after this, help me reproducing the bug by explaining step by step what you're doing.

Thanks!

**Comment by sswapnesh** [comment]
@sle-odoo  Got same error.
 
Just Performed same on [runbot.](http://274975-11-0-ee2b9f.runbot8.odoo.com)
Field `lots_visible` is used in domain [here.](https://github.com/odoo/odoo/blob/11.0/addons/mrp/views/stock_move_views.xml#L81)


![](https://image.prntscr.com/image/vE5mHBl4Q128aEddlrIA1w.png)


![](https://image.prntscr.com/image/z0gs0j9URv6NSjW-SdOtIg.png)

Clicking on Item will throw same error.

**Comment by DbTechGit** [comment]
Hi, I have updated odoo at the last version (Odoo 11.0-20171101  Community Edition) and the Inventory Management app also, but problem still remain.

The step to replicate the error are the followings:

- Enable the traceability  in Menu Configuration > Settings > Inventory
- Use inventory apps
- Go to "Tranfser"
- In  "stock operations" select a product  (Screenshot 1)
- Click "Lot Icons" (Screenshot 2)
- Click on a row for add a products serial number (Screenshot 3)
- At this point i got the error instead obtain a field for serial number insert

The same error is present if I choose the app "Manufactoring" and I do the same operations made in @sswapnesh screenshot

![stock_operation1](https://user-images.githubusercontent.com/33259480/32321041-1ebfad1a-bfc0-11e7-9e00-83a75c0e168b.png)
![lot_icon2](https://user-images.githubusercontent.com/33259480/32321036-1e181f64-bfc0-11e7-8df8-89e0e7d6d1db.png)
![serial_pop_up3](https://user-images.githubusercontent.com/33259480/32321039-1e860e02-bfc0-11e7-8964-bb0cbbd6719a.png)
