### ISSUE TITLE
Sales Order Item is not saved when creating new task

### ISSUE THREAD

**Issue by dmldima** [odoo/odoo#20625]
Impacted versions: Odoo 11.0-20171031 (Community Edition)

Steps to reproduce: Open any task - > Button create -> Enter task title and choose Sales order item

Current behavior: Sales order item is not saved.

Expected behavior: Sales order item is to be saved.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @dmldima,

Thank you for your report.
What exactly do you mean with "choose sales order item"? Can you please add more information and/or a screenshot?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback in a few months.
