### ISSUE TITLE
[11.0] lost css class when one2many edit state（editable="bottom"）

### ISSUE THREAD

**Issue by daimengmeng** [odoo/odoo#20620]
Impacted versions:
- 11.0 github souce code

Steps to reproduce:
- Add attribute **editable="bottom"** to the One2many field  
- Add a button, **type=’object‘**, **class="oe_read_only"**

Current behavior:
- When I edit the record, the button still shows

Expected behavior:
- the button should be hidden

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/13128021/32262683-e4556a52-bf10-11e7-9458-42deaadf6df2.png)
![image](https://user-images.githubusercontent.com/13128021/32262704-0a7368e2-bf11-11e7-97ca-d6097500131c.png)
![image](https://user-images.githubusercontent.com/13128021/32262759-74808378-bf11-11e7-9b91-ed10cf6c743b.png)

**Comment by daimengmeng** [comment]
Maybe the problem is here：
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/list/list_renderer.js#L249
It looks like covered the origin class

![image](https://user-images.githubusercontent.com/13128021/32262840-e1128c20-bf11-11e7-8efa-02bc71a8d083.png)

**Comment by leangjia** [comment]
不明真相的吃瓜群众前来围观

**Comment by Yenthe666** [comment]
@mart-e can you have a look?

**Comment by mart-e** [comment]
Hello,

After discussing with the framework team. We do not consider this as a bug (not supported) but we can accept a PR to modify the behaviour

**Comment by mge-odoo** [comment]
Hi,

Thanks for reporting the bug. It is now fixed in 11.0

Regards,

Martin

**Comment by jlzhou** [comment]
@daimengmeng good! thank everybody!
