### ISSUE TITLE
[9.0] User can create un-cancelable picking

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#20628]
#### Impacted versions:
9.0 (checked on a 1 1/2 day old runbot instance at time of writing)

#### Steps to reproduce:
With `stock` module installed:
1. Create a new internal picking
2. Do not add any products on the picking
3. Press the "Mark Todo" button
4. The "Initial Demand" tab cannot be edited any more
5. Add some lines without amounts to the the Operations tab
6. Save the picking

#### Current behavior:
The picking cannot be cancelled or deleted: cancellation wants to cancel moves that don't exist, and deletion triggers some kind of constraint related to the packing operations.

#### Expected behavior:
The user should be able to cancel or delete the picking if it is in this state. Alternatively the user should not be able to reach this state in the first place.

#### Workaround:
If the user processes the picking (presses the "Validate" button), Odoo will "process" all of the pack operations so that they disappear without doing anything. The picking is not marked Done, but since the pack operations are gone, the user can now delete the picking.

**Comment by jco-odoo** [comment]
We could put ondelete='cascade' on the picking_id of the stock_pack_operation, but we should take care not to break anything.

**Comment by jco-odoo** [comment]
ondelete='cascade' changes the model however.

**Comment by Yenthe666** [comment]
@jco-odoo any update for this one?

**Comment by Yenthe666** [comment]
Hi all,

As Odoo 9 is no longer officially supported I'm closing this issue off.
If you can reproduce it in V10 or up you're more than welcome to create a new bug report.

Regards,
Yenthe
