### ISSUE TITLE
[master] FEATURE REQUEST: Multi-Currency Kanban Counter widget & planned_revenue

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#20631]
<h1>Impacted Versions:</h1>
11.0/Master
<h1>Steps to Reproduce:</h1>
FEATURE REQUEST:<br/>

- Go to CRM > Pipeline >> Kanban View
- See Kanban Counter widget

<h1>Current Behaviour:</h1>

- Currently the Kanban Counter in the pipeline kanban view only supports the base currency of the company_id you're working in.

<h1>Expected Behaviour:</h1>

- Allow users to adjust the currency_id in the crm.lead form view
- Do a foreach on each currency_id in that stage, and show a separate kanban counter widget on the header of each kanban stages showing the split between each currency

<img src="https://user-images.githubusercontent.com/2337666/32304877-2b0b1220-bfad-11e7-9652-7e7f19971672.png"/>

**Comment by Yenthe666** [comment]
Hi @lukebranch,

Thanks a lot for your suggestion.
I'm closing this issue as we're going to work a bit differently from now on. We will close older issues that are labelled wishlist but they will still keep popping up and will still be looked at.
The idea is to keep the 'real' issues open and to search through wishlist items no matter of the open/closed state.

Regards,
Yenthe
