### ISSUE TITLE
[IMP / PROPOSAL] picking waves with ordered pickings

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#20630]
@jco-odoo Would you accept a PR which would implement ordered pickings in picking waves?

The use case is to use the picking wave as a basic delivery route with ordered pickings and a printable overview report for this wave.

I'd appreciate a quick answer in order to prepare a private module or a PR to master accordingly. Thanks.

**Comment by jco-odoo** [comment]
@lap-odoo Have not we already done so for v11?

**Comment by lap-odoo** [comment]
@blaggacao Could you explain with more details what you want to do ? Because I don't understand what you plan to add in your PR. 

For the batch pickings, we just plan to improve the printed report (pdf) to group the products that need to be picked location per location. No other plan yet for that feature.

**Comment by gdgellatly** [comment]
@lap-odoo Obviously I am not @blaggacao but his use case is a really common one although I don't agree with his approach.  If you check back through mailing archives over the years you will find many messages.

Some companies run their own delivery fleet and therefore we like to use stock journal / batch picking as a kind of delivery run.  The problem with Odoo is it assumes that a companies delivery responsibility ends at their warehouse door.  For many companies this just isn't true.  So when he says add a sequence, he literally means, when the driver leaves, deliver the orders in this order.

For a few days work Odoo could have a pretty awesome mashup of a delivery app at least in enterprise.

It just takes
document_sign - for Proof of delivery
image capture
google_map extended to provide some backend capability, along with using the optimize tag in the route call.
fleet and hr to assign drivers/vehicles to deliveries.
picking waves or similar

to be joined up
mobile app already exists.

**Comment by jco-odoo** [comment]
So, what you need is the picking wave module with e-sign on its report?

What would you use image capture for?  Scan documents?

Google Maps would just be the addresses of the partners in the pickings of
the picking wave.  But that would only be in handy if you have your own
fleet.

**Comment by nhomar** [comment]
> @blaggacao Could you explain with more details what you want to do ? Because I don't understand what you plan to add in your PR.

> For the batch pickings, we just plan to improve the printed report (pdf) to group the products that need to be picked location per location. No other plan yet for that feature.

@lap-odoo We have such report on New API, would you accept a PR?.

Some points and please correct me if I am wrong:

1. Batch pickings ahouls be used for what their name says "PICK" not "DELIVER", Why? the ordering strategy is completelly different.
2. Report MUST include the informations of all localtions where the product can be foud.
3. **New Feature** With a proper coding strategy on your locations you can propose a "Route to Pick" really used A LOT on big warehouses (and you do not need to be a big company for such required feature BTW).

We have that report very well tested and with a huge number of fancy FUnctional features (Like barcodes on it **also** to trigger: Location -> what I pick. That report had evolved on our side since 4 years ago and we will migrate it soon to 11.0 (and we can do it ready for master).

Then... If you share the specification on your side once you have it, I think it will work for you and I stop to maintain that report my self for the next 5 years jeje.... and everybody wins ;-)

Regards.

**Comment by jco-odoo** [comment]
Why not merge pickings for this?

**Comment by nhomar** [comment]
> Why not merge pickings for this?

Ok, let's explain:

A picking is a document for control, I mean, THe picking has all the information related to order, dates and so on.

The **pick process** has nothing to do with that part is just give the coordinates to the picker guy in the warhouse to look for the products.

Even in some cases such process is done for people that do tens of times the same per day, and even if he/she do not need to know the picking info itself and it is not relevant at this point, she/need to know where to find in the more expedite way the products.

Let's say:

**rationale** Picking Batch is for internal logistic purposes and pickings are for external purposes.

BTW, IMHO the to merge picking you will need to merge the Picking and only will work on 2 steps or 3 steps delivery process (because you should not loose the picking itself -->Customer).

Then with the approach of Batch in the way I mentioned if you have **delivery** you will make a batch for PIck and another for Delivery (the one that will go in the truck) and both of them will not have any relation in terms of grouping, and no impact at all in the Inventory itself, it is just for operational purposes, affect the inventory to give such feature (modifying the picking in any way) will be incorrect from a design POV, the grouping logic is related with sizing, volume, position (very different depending of the business and easily achiveable by a server action business by business) on the warehouse (due to that you will not know at that moment such information frequently), that's why the picking batch is so important and must be independent from the picking itself (in order to have the proper technical freedom).

I hope it helps @jco-odoo let me know.

**Comment by gdgellatly** [comment]
@nhomar I agree, for many use cases.  Ideally they would be separate, we just work with what we have.  There are other use cases however where effectively the delivery step is the picking step in reverse.  e.g if you are stacking a truck with 3 tonne orders (and each item is over a tonne), one on top of the other, you want them in reverse for unloading.  Also at the point of manufacture/incoming they need to be stored in a certain way that is dependent on its future delivery, so warehouse/location/putaway setup doesn't really work for that case.  That is different to picking a box off a shelf.

@rco-odoo I realise the image capture thing was my own use case.  Sometimes a person isn't home, or the nature of the items makes verification difficult, or you are dropshipping, so you need to prove where and when they were delivered without damage.  So the driver takes a photo or 3.  Currently we use a custom android app for that based on odoo-mobile and Android native exif interface which captures time, location, GPS coordinates.

A delivery app with signature is only useful if you have your own fleet so google maps follows.  Besides a google map integration is far more than just a nice picture.  Route optimisation, delivery planning (you can see your deliveries on a map and assign to different vehicles/ days).  But i truth, if you just have a gmaps route url and you are using the odoo mobile app, it launches navigation anyway.

**Comment by nhomar** [comment]
> @nhomar I agree, for many use cases. Ideally they would be separate, we just work with what we have. There are other use cases however where effectively the delivery step is the picking step in reverse. e.g if you are stacking a truck with 3 tonne orders (and each item is over a tonne), one on top of the other, you want them in reverse for unloading. Also at the point of manufacture/incoming they need to be stored in a certain way that is dependent on its future delivery, so warehouse/location/putaway setup doesn't really work for that case. That is different to picking a box off a shelf.

Completely agree, this case is possible when no *+Picking Batch** feature is used, and you are totally right, I am talking just when *+Picking Wave** is in the tablle!

**Comment by gdgellatly** [comment]
@nhomar I think we are agreeing here. Then I think effectively you have a multi step operation.  I wonder if its doable with routes.  Internal Picking Waves for Warehouse -> Truck Loading (for clarity here) Then second picking waves Truck Loading -> Customer.  

I am actually slated to do this dev next week, a port from v7, but have done all the background work.

**Comment by gdgellatly** [comment]
@nhomar @jco-odoo Also check out this V10 module by @gityopie . https://github.com/gityopie/odoo-addons/tree/10.0/web_google_maps It's a beautiful thing and covers of course the other issue with maps integration, getting addresses correct.

**Comment by nhomar** [comment]
> @nhomar I think we are agreeing here. Then I think effectively you have a multi step operation. I wonder if its doable with routes. 

#beentheredonethat result --> UGLY.

Picking Wave is really a nice conceptual feature, routes are more technical and in our **try** that become a mess.

> Internal Picking Waves for Warehouse -> Truck Loading (for clarity here) Then second picking waves Truck Loading -> Customer.

Yes exaclty!

**Comment by blaggacao** [comment]
I agree with https://github.com/odoo/odoo/issues/20630#issuecomment-341478905 - this would be even a more complete approach, especially for the DocuSign/Scan part. Scan, because docusign is not always practical.

@nhomar 
> Batch pickings should be used for what their name says "PICK" not "DELIVER", Why? the ordering strategy is completelly different.

The order strategy can be set on the view, so it would not interfere with the standard model (picking) ordering structure.

>Report MUST include the informations of all localtions where the product can be found.

No, a picking already contains this information already, we don't want to replicate it in an overview document. There is always the possibility to add barcodes to open the picking on demand on some sort of HDI.

> New Feature With a proper coding strategy on your locations you can propose a "Route to Pick" really used A LOT on big warehouses (and you do not need to be a big company for such required feature BTW).

Sounds interesting, can you elaborate?

Ceterum: Picking Wave is a far too loose concept to have a real thorough discussion on it and I'm not sure if there is an accepted industry definition.
I look at picking waves this way: According to the step (Pick, Pack, Quality, etc.) they have completely different meaning. The only common denominator is a group of pickings and a responsible person. Thing of the attached use cases which comes with responsible person only (painting device or work environment definition, etc.)

With my proposal, you would just have a picking wave which is forcibly assigned to a person, represents a group of pickings, which you can optionally put into your chosen order without affecting the order of the underlying pickings themselves (see order by on view definition)

It's dead simple:

```python
# -*- coding: utf-8 -*-
# Copyright 2017, XOE Corp.
# XOE Enterprise Edition License v1.0.

from odoo import models, fields, api, _  # noqa
from odoo.exceptions import UserError


class Picking(models.Model):
    _inherit = "stock.picking"
    _order = "priority desc, date asc, id desc"

    sequence = fields.Integer('Sequence', help="Used for ordering, ej. in picking waves", default=1000)


class StockPickingWave(models.Model):
    _inherit = "stock.picking.wave"

    @api.multi
    def print_picking(self):
        pickings = self.mapped('picking_ids').sorted('sequence')
        if not pickings:
            raise UserError(_('Nothing to print.'))
        return self.env["report"].with_context(active_ids=pickings.ids, active_model='stock.picking').get_action([], 'stock.report_picking')

```

I'm still fine tuning this one:
```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <template id="external_layout_barcode_right" inherit_id="report.external_layout" primary="True">
            <xpath expr="//t[@t-call='report.external_layout_header']" position="attributes">
                <attribute name="t-call">stock.external_layout_header_barcode_right</attribute>
            </xpath>
        </template>
        <template id="external_layout_header_barcode_right" inherit_id="report.external_layout_header" primary="True">
            <xpath expr="//div[@name='company_address']" position="after">
                <div class="col-xs-4 pull-right mt8" name="right_box">
                    <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 100)" style="width:300px;height:50px;"/>
                </div>
            </xpath>
        </template>
        <template id="report_picking_wave">
            <t t-call="report.html_container">
                <t t-foreach="docs" t-as="o">
                    <t t-call="report.internal_layout">
                        <div class="page">
<!--                             <br/>
                            <div class="row">
                                <div class="col-xs-6">
                                    <div t-if="o.move_lines and o.move_lines[0].partner_id and o.move_lines[0].partner_id.id != o.partner_id.id">
                                        <span><strong>Delivery Address:</strong></span>
                                        <div t-field="o.move_lines[0].partner_id"
                                            t-options='{"widget": "contact", "fields": ["address", "name", "phone", "fax"], "no_marker": True, "phone_icons": True}'/>
                                    </div>
                                    <div t-if="o.picking_type_id.code != 'internal' and (not o.move_lines or not o.move_lines[0].partner_id) and o.picking_type_id.warehouse_id.partner_id">
                                        <span><strong>Warehouse Address:</strong></span>
                                        <div t-field="o.picking_type_id.warehouse_id.partner_id"
                                            t-options='{"widget": "contact", "fields": ["address", "name", "phone", "fax"], "no_marker": True, "phone_icons": True}'/>
                                    </div>
                                </div>
                                <div class="col-xs-5 col-xs-offset-1">
                                    <div t-if="o.picking_type_id.code=='incoming' and o.partner_id">
                                        <span><strong>Vendor Address:</strong></span>
                                    </div>
                                    <div t-if="o.picking_type_id.code=='internal' and o.partner_id">
                                        <span><strong>Warehouse Address:</strong></span>
                                    </div>
                                    <div t-if="o.picking_type_id.code=='outgoing' and o.partner_id">
                                        <span><strong>Customer Address:</strong></span>
                                    </div>
                                    <div t-if="o.partner_id" name="partner_header">
                                        <div t-field="o.partner_id"
                                           t-options='{"widget": "contact", "fields": ["name", "phone"], "no_marker": True, "phone_icons": True}'/>
                                        <p t-if="o.sudo().partner_id.vat">VAT: <span t-field="o.sudo().partner_id.vat"/></p>
                                    </div>
                                </div>
                            </div>
                            <br/> -->
                            <h1 t-field="o.name" class="mt0"/>
                            <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <th><strong>Responsible</strong></th>
                                    <th><strong>State</strong></th>
                                    <th><strong># Pickings</strong></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <span t-field="o.user_id"/>
                                    </td>
                                    <td>
                                        <span t-field="o.state"/>
                                    </td>
                                    <td>
                                        <span t-esc="len(o.picking_ids)"/>
                                    </td>
                                </tr>
                            </tbody>
                            </table>
                            <br/>
                            <br/>
                            <table class="table table-condensed" t-if="o.picking_ids">
                                <t t-set="has_packs" t-value="not(any([picking.pack_operation_pack_ids for picking in o.picking_ids]))"/>
                              <thead>
                                <tr>
                                    <th><strong>Reference</strong></th>
                                    <th><strong>Source Document</strong></th>
                                    <t t-if="has_packs">
                                        <th><strong># of Packs</strong></th>
                                    </t>
                                    <th><strong>Routing</strong></th>
                                    <th><strong>Scheduled Date</strong></th>
                                </tr>
                              </thead>
                              <tbody>
                                <t  t-foreach="o.picking_ids" t-as="picking">
                                    <tr>
                                        <td rowspan="2"><span t-field="picking.name"/><br/>
                                            <t t-if="picking.backorder_id">Backorder of: <span  t-field="picking.backorder_id.name"/></t>
                                        </td>
                                        <td><span t-field="picking.origin"/></td>
                                        <t t-if="has_packs">
                                            <td><span t-esc="len(picking.pack_operation_pack_ids)"/></td>
                                        </t>
                                        <td><span t-field="picking.location_id"/> -> <span t-field="picking.location_dest_id"/></td>
                                        <td><span t-field="picking.min_date"/></td>
                                    </tr><tr>
                                    <t t-if="picking.picking_type_code != 'internal' and picking.partner_id">
                                        <td colspan="4"><strong>Address: </strong><span t-field="picking.partner_id.commercial_partner_id.name"/> //
                                        <span t-esc="picking.partner_id._display_address(without_company=True)"/></td>
                                    </t></tr>
                                </t>
                              </tbody>
                            </table>
                            <p t-if="o.state in ['draft']">
                                This wave is still in draft.
                            </p>
                            <!-- <p t-field="o.note"/> -->
                        </div>
                    </t>
                 </t>
             </t>
        </template>
    </data>

    <data>
        <report
            string="Picking Wave"
            id="action_report_picking_wave"
            model="stock.picking.wave"
            report_type="qweb-pdf"
            name="stock_picking_wave_ordered.report_picking_wave"
            file="stock_picking_wave_ordered.report_picking_wave"
        />
    </data>
</odoo>

```

and of course - the magic:
```xml
    <record id="view_stock_picking_wave_form_inherited" model="ir.ui.view">
        <field name="name">view.stock.picking.wave.form inherited</field>
        <field name="model">stock.picking.wave</field>
        <!-- Please veryfiy, that the following inherited view really sticks to the naming convention. -->
        <field name="inherit_id" ref="stock_picking_wave.view_picking_wave_form" />
        <field name="type">form</field>
        <field name="arch" type="xml">
            <xpath expr="//tree" position="attributes">
                <attribute name="default_order">sequence</attribute>
            </xpath>
            <xpath expr="//tree/field[@name='name']" position="before">
                <field name="sequence" widget="handle" />
            </xpath>
        </field>
    </record>
```

That's all and does a marvelous job without adding too much complexity. It could be just made standard... into the `stock_picking_wave` whereon further use cases can build upon.

**Comment by blaggacao** [comment]
Ok the `default_order` is a bit sub-perfect UI as there is a small sorting triangle on the sequence column... But Odoo has the power to make "contextual sorting" a more embedded use case. Not really necessary, though...

**Comment by jco-odoo** [comment]
It is not because you merge the internal picking that you don't have any
information anymore about the original quantities or where to whom it
should go to.  Merge picking internal and picking wave external stays
logical to me.   The sale order/purchase orders /moves are your initial
demand, they give all the information.

**Comment by blaggacao** [comment]
Ceterum: I think we should restrain ourselves from over-specifying picking waves as a general purpose, lean and abstract concept...

**Comment by blaggacao** [comment]
I agree: https://github.com/odoo/odoo/issues/20630#issuecomment-341514823
There is a sub concept, which could be expanded in some logistics hub which is the packing operations or in future, as I heard, the stock.move.line.

**Comment by jco-odoo** [comment]
You could even use the two together: group by transporter first through
waves and then merge according to what is practical for the picker.

**Comment by nhomar** [comment]
@jco-odoo 

My point against the group pickings is that the control of the flow and routes should not be affected (and it frequently is).

Can you enlight me with a real example? Is that feature available in some way? may be I am not understanding something on your point.

Another important topic is that Batch is not Picking (you need both documents) because they are totally independent in logistical terms, change a picking doe not cover 100% of cases (and cover less than 50% BTW), and yes it can work, but it can not be **the** way (at least AFAICU) if you elaborate a little bit more may be I can understand you better.

REgards.

**Comment by nhomar** [comment]
@blaggacao 

> Ceterum: Picking Wave is a far too loose concept to have a real thorough discussion on it and I'm not sure if there is an accepted industry definition.

mmm noup! this is very well explained, I will just put the [first results of my google search](http://www.delivrd.com/2017/04/picking-by-order-vs-batch-picking-whats-the-difference/) (and you can check a SAP book both concepts **picking wave** and **picking batch** are there).

BTW, I made a mistake confusing the conversation, Picking Wave <> Picking Batch, My scope is more for **picking wave** than for **picking batch** [the difference can be found here](http://multichannelmerchant.com/operations/batch-vs-wave-picking/).

> With my proposal, you would just have a picking wave which is forcibly assigned to a person, represents a group of pickings, which you can optionally put into your chosen order without affecting the order of the underlying pickings themselves (see order by on view definition)

Please my dear friend @blaggacao  **do not paste code in a functional discussion to hard to read, do a gist and link to it instead**

Answering: It is clear the technical approach is fairly simple but tricky from a functional perspective, all what you say make sense.

**Comment by nhomar** [comment]
@lap-odoo 

Even if you want to use and do it yourself, we can have a hangout call and expose you what we have (it would be really sad if you miss this opportunity).

In the image what we have, and we can make a proper PR (We are already migrating it to v11-master-ready).

An honestly as @blaggacao says and explain it is really simple technically it is just a matter of willingness to have it and do it in the right way because the complexity as you know is that the usability stay clean.

Expossing a little bit My report, is that it can be used as a document for control (picker hand written says how much he/she pick) and the receptionist itself just load the information triggering the barcode (we have that technilogy on v11 already that can be a little more complex).

This kind of little features add a HUGE values to end customers and does not cost too much effort.

![image](https://user-images.githubusercontent.com/338634/32345133-e62cd7a2-bfce-11e7-8739-a8bd346d97c9.png)

**Comment by gdgellatly** [comment]
@jco-odoo I think I understand your idea, but I do think there are difficulties with such an approach beyond the single customer case.

1. It is often a requirement for the customer to receive a packing slip.
2. Warehouse users do not necessarily have access to the other documents you talk about.
3. While it may make sense to pick together, it almost certainly does not make any sense to pack together unless they are all going to the same destination.  OK this is wave vs batch talk now.
4. Moreover, picking waves are actually really good for the batch picking use case.  It just so happens they are also really useful with some modification for the delivery use case.
5. There is nothing in merging 2 pickings that I can see that could not be done using a single report or picking wave view (efectively a functional one2many on stock.move.line)

I am not saying by any stretch I have the answers or the ultimate design, but I have a really strong functional understanding of the problem of managing a largish fleet of delivery vehicles with Odoo (multicompany, manufacturing, 40 trucks and 30 other vehicles, multiple pilot vehicles, and cranes).

Right now I'm even thinking that a many2many on picking waves constrained somehow for each step would be a nice little solution combines with @nhomar  report.
I also second nhomar's offer, if this is a feature you wish to develop, use our real world functional experience.

**Comment by blaggacao** [comment]
@nhomar I understand that Control Flow is twofold, at the picking level, and (to be implemented) on the operation level (`stock.move.line`).

When a use case based definition of the nodes are found, then the edges are steared by the routes and expressed by the pickings, BUT, and that is I think the conceptualy trickiness here, there can be differente edge context (eg. 5 parallel packing lines), thos probably should not represent individual nodes in the location/routes concept, but rather a context to the operation (aka `stock.move.line`). 

This has to be implemented, but I think it explains my view of an optimal solution for the problem you expose, as I understood it.

I think your report is based on the internal only use case, albeit there are generally accepted as I read in your quoted article, I would not go so far as to increase the specification of picking wave, rather I would suggest a name change to batch, as this is what it is. And a wave would be a grouping of actual `stock.move.lines`.

Your report has the internal case in mind, but I think there is no big deal in having several purpose reports on the picking wave according to it's use case context, rather then increasing it's specification to fit one specific use case.

**Comment by nhomar** [comment]
>  I would not go so far as to increase the specification of picking wave, rather I would suggest a name change to batch

It has been done on v11 already

**Comment by blaggacao** [comment]
> There is nothing in merging 2 pickings that I can see that could not be done using a single report or picking wave view (efectively a functional one2many on stock.move.line)

**I think I agree, as I understand it:**
wave = grouping of `stock.move.line`
batch = grouping of `stock.picking`

>Right now I'm even thinking that a many2many on picking waves constrained somehow for each step would be a nice little solution 

I also was thinking of that, but it is UX wise a bit difficult, probably, but of course it would permit multiple purpose while maintaining clear focus... UX wise i think it's difficult to maintain because picking itself are floating concepts, especially if you combine it with the utter granularity, so maintaining a simple grouping would be difficult, a meta concept on picking **batches** and pickings would be advisable, but it's another model, so we end up in model hell :) - If that's something that exists...

**Comment by nhomar** [comment]
> I think your report is based on the internal only use case, albeit there are generally accepted definitions as I read in your quoted article, I would not go so far as to increase the specification of picking wave, rather I would suggest a name change to batch, as this is what it is. And a wave would be a grouping of actual stock.move.lines.

The separation per line is another story and need a lot of functional decisions behind, IMHO that's another story, but yes a nice to have also.

BTW: We use the wave for both, this is how a **Delivery report on wave context** looks like, basically this is the report about what is in the truck actually, this report make sense with an interim windows we did to mark what was picked in the **packing** zone to be loaded into the truck:

![image](https://user-images.githubusercontent.com/338634/32347654-ebaf7d1c-bfd6-11e7-99cb-0cec3e3c9e08.png)

**Comment by blaggacao** [comment]
All roads lead to Rome :heart:

**Comment by blaggacao** [comment]
For reducing the need of reports, I suggest a TC8000. Just received a demo device... ;) With PTT and everything, simply NICE!

**Comment by jco-odoo** [comment]
What you can do right now is group everything together in the PICK if you do PICK-PACK-SHIP (but you don't do it in PACK-SHIP, by putting a fixed procurement group on the PICK procurement rule).  A sometimes more practical solution would be to simply select several pickings and merge them.  It can be easily done with even a server action where you just move all the moves to the same picking.  In v10, you might need to unreserve/reserve to regenerate pack operations, in v11 maybe you want to merge moves/move lines.  In the case of (multiple order) picking where you sort them out them immediately, you would prefer not to merge. (if you pick the entire quantity at once, it better to merge)

By having one picking per pack operation, you can still apply different packing lines and have a different packing slip, although why not put that report on the pack itself.  

There are some important advantages of merging into one picking: you can use barcode scanning, not just a printed report and it has the possibility to merge items if necessary e.g. if you need 100 pieces for several orders or indicate when it is easier to move an entire pack.  

On a sidenote, a picking wave is not the same as wave picking.  

Throughout your comments, it makes me think that a bundling of stock.move.line onto picking waves/batches makes sense when you don't merge the moves/move lines: when it is important to distinguish which move line is for which client e.g. the case I gave when sorting out immediately on picking or deliveries to carriers.  In the other case, it is better to merge the pickings themselves.

**Comment by jco-odoo** [comment]
Still thinking you are wanting two objects for the same thing.

**Comment by blaggacao** [comment]
> Throughout your comments, it makes me think that a bundling of stock.move.line onto picking waves/batches makes sense when you don't merge the moves/move lines: when it is important to distinguish which move line is for which client e.g. the case I gave when sorting out immediately on picking or deliveries to carriers. In the other case, it is better to merge the pickings themselves.

Absolutely, and I think merging is an interesting approach. wave picking might be a historical conceptualization where almost was true: picking = sales order.

We might refine conceptualization of pickings further, but conceptualized as a "loose group of operations of some kind" would shift the main focus towards operations, but then we have a problem of ambiguity between picking and `picking.wave`.

On the other hand, let picking be "the instance of an edge between two nodes" would also honor general perception. The operations would then limit to put aways on sub-locations on one or the other end. So a picking would represent in some form one physical warehouse pathway (like where the operator would walk along if he only picked one picking) for a specific group of operations. The problem here is (afic) that a sale would not trigger two pickings of tow distant pathways for two products of one sales order which counteracts the before mentioned principle.

However, the simplified approach, eliminating one intermediate concept (wave) and just saying a picking as an aggregation of operations (be it according to batch [bucket optimization] or wave [pathway optimization] strategy) is a fresh and valid thinking.

**Comment by blaggacao** [comment]
As a side effect of the before said: we would, over time, up-vote the importance of operations which gives us more flexibility on the edge context, as elaborated before...

**Comment by gdgellatly** [comment]
@jco-odoo I'm lost, I trust you.  If anything ever happens and you want functional review please ping me and I'll be happy to give a thorough test with feedback.

**Comment by blaggacao** [comment]
![image](https://user-images.githubusercontent.com/7548295/32350107-47a671ce-bfe7-11e7-824b-d38415198c09.png)

**Comment by blaggacao** [comment]
Here goes the image for truck driver Jacky...
![image](https://user-images.githubusercontent.com/7548295/32350551-b7ba8f44-bfe8-11e7-923d-a961984cfe30.png)

**Comment by blaggacao** [comment]
@nhomar I prefer having either a separate (sealed paper) location barcode inventory or put location barcode on physical locations only, which has the nice side effect: "Once it's scanned, the operator was actually there" :smile: 

Similar for product, usually products are packed and packings have a bar-code... ("I had this product in my hands for real")

**Comment by blaggacao** [comment]
Now it's cool: 
![image](https://user-images.githubusercontent.com/7548295/32356508-8b146508-c003-11e7-8ab9-e944057f9ae3.png)

Perfect hitrate with the TC8000. printed ona a normal HP P1102w Laser Jet on white paper.

**Comment by lap-odoo** [comment]
Hi,

**1. Distinction between picking wave and batch picking** 

I confirm that : 

Picking wave = grouping of stock.move.line. 

Batch picking = grouping of stock.picking. Previously, this was named "picking wave" in Odoo, creating a lot of confusion but as @nhomar explained, this has been corrected in V11. By the way, we are working on improving the report printed from the batch picking. 

**2. Improve delivery**

I've seen many interesting suggestions in this thread. However, as pointed out, we need to make sure that the usability stays clean while adding additional features. 

Some of you have already implemented these features and have PRs. What I suggest: 
- You can send me the PR
- If you can join an explanatory document with it it would be even better. This doesn't need to be detailed! Just a quick overview of which features are implemented and why so that I can test them is enough

I can check it with the Logistics Team and based on that we will be able to take decisions on what we really want to implement or not. I won't hesitate to discuss it here to get your opinion. Please, note that it may take some time. As you can imagine, we have already started to work on the next steps for V12, so don't expect an answer too quickly.

Is that ok for you ? 

Thanks

**Comment by blaggacao** [comment]
@jco-odoo I think in the light of some of our comments you could complement:

Wave picking strategy > grouping of `stock.move.line` (aka "Picking") according to pathway optimization strategy.

Batch picking strategy > grouping of `stock.move.line` (aka "Picking") according to "order bucket" optimization strategy.

This is a valid theoretization for your suuggestion of regrouping `stock.move.line`s

**Comment by vcloud9ray** [comment]
In my case, this was resolved by:

(1) Configure for PICK/PACK/SHIP
(2) Merging Transfers
(3) Reordering the items on the Picking Operations report (Warehouse users scan paper)

Three steps:
PICK - merge all Transfers, print stock.picking lines in location order
LOAD - merge by Customer, print stock.pickings in reverse STOP order
DELIVER - merge by Customer, print stock.pickings in STOP order

Actually didn't use Picking Waves - cancelled the original Transfer after the new merged one was made in each step.

**Comment by blaggacao** [comment]
@vcloud9ray Nice idea! Coneceptually you shrinken the picking and broaden the picking.line concept... But then on the picking line we don't have chatter by default etc...

But I'm with you, in that one exceeding and probably unnecessary concept in this trinty (wave, picking, line)...

**Comment by lap-odoo** [comment]
Thanks for the feedback, as explained in the conversation, there is already an ongoing task to improve the batch picking report and we will try to included some of your ideas in the next versions. I'm closing this issue as I've already added this thread in our logistics backlog.
