### ISSUE TITLE
Invoice from Quotation. Without confirming the quotation the invoice can be generated against it.

### ISSUE THREAD

**Issue by NiyasRaphy** [odoo/odoo#20637]
Impacted versions: V10 and v11. Didn't checked below versions

Steps to reproduce:  Create a Quotation, then click on action drop down menu, then we can find an option 'Invoice Order'. Using this it is possible to create invoice against quotation.

Current behavior: Using this it is possible to create invoice against quotation which is not yet confirmed.

Expected behavior: Invoicing should be only possible for the confirmed quotations

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@Yenthe666  Related to #20121.

**Comment by Yenthe666** [comment]
Hi @NiyasRaphy,

Thanks for your report but I really wouldn't call this a bug. This would mean that you would always need to confirm orders first before creating an invoice from it. Sometimes you can directly convert a quote to an invoice.. just like you can create an invoice from scratch right away.
@mart-e final call is up to you.

Regards,
Yenthe

**Comment by vcloud9ray** [comment]
If this isn't possible, and the policy of the company is to ask for a deposit before confirmation, how would your do this?

I know Customers who won't confirm certain Orders for certain Customers without a deposit first. 

They need to be able to create a Invoice  from a Quotation.

**Comment by mart-e** [comment]
Yes, it actually depends of the use case. It may be useful for some to create the invoice before the quotation confirmation.

CCing @nim-odoo to be sure (was added during the Big Sale Refactoring)

**Comment by nim-odoo** [comment]
TBH, we didn't consider this use case. But yeah, as @vcloud9ray said, it can be useful to not fully block the feature since it might be useful. So I wouldn't change anything.
