### ISSUE TITLE
Some view feature does not work properly odoo 11 

### ISSUE THREAD

**Issue by ward-ye** [odoo/odoo#20659]
Any view contains "field_parent" It does not work properly odoo 11 

e.g Salary Structures Hierarchy, Salary Rule Categories Hierarchy and all other of the same

**Comment by ged-odoo** [comment]
@ward-ye Hmm, I suppose that this is a JS problem.  But I am not sure what you mean by 'not work properly'?  Can you elaborate?  What exactly is not working?

**Comment by Yenthe666** [comment]
@ward-ye could you give us feedback and more information please?

**Comment by azzougouagh** [comment]
hello,
The hierarchical tree view doesn't exist no more in odoo 11. I need it too. is there another solution?

**Comment by jaumeplanas** [comment]
It seems indeed that the hierarchical tree view doesn't exists. If you search "field_parent" in web module, no occurrence is found.

If the hierarchical tree view doesn't exist in Odoo v11.0, is this a bug or is it by purpose? If it's by purpose, what is the alternative, if exists?

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue from the creator.
Indeed, the hierarchical tree view has been removed in V11.
