### ISSUE TITLE
iOS App : iPhone X Support

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#20683]
I have bought today the iPhone X . 

But the odoo App looks not nice until now : 

![img_0002](https://user-images.githubusercontent.com/8161283/32395421-5192bcb0-c0e1-11e7-931a-86ce4ca691c8.PNG)

**Comment by adr-odoo** [comment]
Hello,

This issue has been fixed.
PR: https://github.com/odoo/mobile-ios/pull/2

Regards,
