### ISSUE TITLE
"record has been modified" warning after editing and saving

### ISSUE THREAD

**Issue by mamiu** [odoo/odoo#20699]
**Impacted versions:**
11 and master

**Steps to reproduce:**
* Go to any object with a many2one field (e.g. fleet vehicle)
* Click on 'Edit'
* Click on the 'Edit many2one object' button
<img width="61" alt="screen shot 2017-11-04 at 23 26 30" src="https://user-images.githubusercontent.com/3653465/32410011-c4add640-c1b7-11e7-9390-f3a704acf1ed.png">

* In the form that opens click on 'Save'
* The form closes. Don't edit anything in the current form.
* Click on 'Save'

**Current behavior:**
If you now want to leave the current form (which is not in edit mode) the "record has been modified" warning appears
<img width="650" alt="screen shot 2017-11-04 at 23 32 32" src="https://user-images.githubusercontent.com/3653465/32410046-79a5128e-c1b8-11e7-8125-1a0cec7cddc7.png">

**Expected behavior:**
The warning shouldn't appear, like in the versions below 11.

**Comment by Yenthe666** [comment]
@ged-odoo this looks like one for you I believe?

**Comment by ged-odoo** [comment]
@Yenthe666 yep, definitely a problem with the new views. Looking at it right now

**Comment by ged-odoo** [comment]
fixed in saas-16, commit https://github.com/odoo/odoo/commit/9e97ad8dce4525d6a132b8f8353b5c8fa87caba2

Thank you for your detailed report

**Comment by mamiu** [comment]
Your welcome!

**Comment by mamiu** [comment]
You're welcome!
