### ISSUE TITLE
[Translation] some strings are hard to translate due to inappropriate divisions

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#20698]
### Impacted versions:

Probably all.

### Steps to reproduce:

N/A

### Current behavior:

This line `<h2 class="mt0">Welcome to your <b>Homepage</b>!</h2>` from https://github.com/odoo/odoo/blob/4035d55d564764710f573baa4c23a96f711992e1/addons/website/static/src/xml/website.editor.xml#L4 is divided into "Welcome to your" and "Homepage" as the source terms.

This is particularly problematic when you try to translate the sentence into Japanese - "ホームページへようこそ" which is basically in the sequence of "homepage" "to" "welcome".  Besides, the string "Homepage" is shared among different sources (in Transifex), which makes it impossible to manipulate with the translation by applying incorrect translation to make the sentence make sense.  i.e. translate "Welcome to your" as "ホームページへ" (to homepage) and "Homepage" as "ようこそ" (welcome).

### Expected behavior:

A sentence should not be divided into multiple source strings for translation.

### Video/Screenshot link (optional):

Current website top page (demo) looks a bit stupid in Japanese because of this issue.

![image](https://user-images.githubusercontent.com/7766939/32407147-be5595d2-c1bf-11e7-9866-462ff8a36445.png)

**Comment by Yenthe666** [comment]
Hmm, this is quite hard to handle though as this is really depending on the language of the user. @mart-e could you give feedback? I'm afraid this is something we can't change easily..

**Comment by yostashiro** [comment]
> as this is really depending on the language of the user

@Yenthe666 Yes, this is why a sentence should not be split into multiple source strings.

I believe this is an issue with Korean as well since its grammar is similar to Japanese.

Would be nice to see this fixed in the next major version as I guess making changes on the current version will affect all the languages.

**Comment by yostashiro** [comment]
Another example:
![image](https://user-images.githubusercontent.com/7766939/32424733-4f615b72-c2e9-11e7-8e92-7ee8dd0a95a7.png)

The sentence is split into "Use an integrated hardware setup like" and "PosBox", which makes it really difficult to make the Japanese translation (in which "PosBox" should come first) not awkward.

**Comment by mart-e** [comment]
Hello,

We already do that for views stored in the database. However, for dynamic views like the ones in the web editor, this is unfortunately, not possible at the moment.
We need to change the way we process these views (translated client side, not server side) and this is not something we plan to do at the moment.
Sorry

**Comment by yostashiro** [comment]
> We need to change the way we process these views (translated client side, not server side) and this is not something we plan to do at the moment.

@mart-e Just wondering if anything has been changed from here.  Would you mind explaining a bit how it's technically difficult to make a sentence like below translatable as a sentence (instead of as phrases broken down into pieces)?

```.xml
    <t t-name="website_forum.social_message_answer">
        <p>By sharing you answer, you will get additional <b>karma points</b> if your
        answer is selected as the right one. See what you can do with karma
        <a href="/forum/help-1/faq" target="_blank">here</a>.</p>
    </t>
```

I would like to understand clearly where the technical constraint is as I see some tagged sentences being source strings just fine as complete sentences. Thank you.

**Comment by mart-e** [comment]
@yostashiro you can check the following (complicated) code that will process a translatable XML/HTML field server side.

https://github.com/odoo/odoo/blob/fb377a8f1bf2bea020c14ea57997ea9078a54e5f/odoo/tools/translate.py#L209

When reading such field, the result of the `read` is already translated, all the processing was done server side.

On a view in `/static/src/xml`, it is processed differently. 
1. All the static assets (js, css, xml) are loaded when you load the webclient
2. A call to [the route](https://github.com/odoo/odoo/blob/fb377a8f1bf2bea020c14ea57997ea9078a54e5f/addons/web/controllers/main.py#L993) `/web/webclient/translations/...` is made to retieve all web-related translations (xml and `_t()`)
3. Translations are applied on each xml chunk

The above flow does _not_ prevent to apply the same logic than what is done for XML fields but it means we should apply +/- the same approache than the above `process` method in javascript. Not impossible but not an easy task (futhermore, we do not have `lxml` in javascript as we do for python).

**Comment by yostashiro** [comment]
Thank you very much for your explanation!
