### ISSUE TITLE
ISR Postal number regex

### ISSUE THREAD

**Issue by dcoopennet** [odoo/odoo#20691]
Impacted versions: 11.0

Steps to reproduce:
- No step required

Current behavior:
- The check with the regex on the postal number match absolutely no number.

Expected behavior:
- The check should match the last number of the postal account number (example: 01-123456-8 -> 8)

def _is_l10n_ch_postal:
    if re.match('\d+$', account_ref or ''):
        account_ref_without_check = account_ref[:-1]
        return mod10r(account_ref_without_check) == account_ref
    return False

I think you should replace match with search.

**Comment by Yenthe666** [comment]
Hi @dcoopennet,

Thanks a lot for your report!
@qdp-odoo I see that you made this commit (at https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/l10n_ch/models/res_bank.py#L10 - commit https://github.com/odoo/odoo/commit/1ba42a6f2958b7c49c3b827d587ed7b97e64df84#diff-b6235a49c5949673bb213f3f712026cb). Could you check / answer this please?

Regards,
Yenthe

**Comment by qdp-odoo** [comment]
I'm sorry, but I don't see the problem: 
* _is_l10n_ch_postal() is also testing that all chars are ciphers (as stated in the docstring)
```
>>> import re
>>> account_ref = '01-123456-8'
>>> bool(re.match('\d+$', account_ref or ''))
False
>>> account_ref = '011234568'
>>> bool(re.match('\d+$', account_ref or ''))
True
```
* this function is called on the sanitized account number, so all dashes are stripped (see https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_bank.py#L11)
```
>>> acc_number = '01-123456-8'
>>> re.sub(r'\W+', '', acc_number).upper()
'011234568'
```

So for me there is no bug, or at least your analysis is wrong... and as this ticket ain't a bug I'm closing it.

**Comment by open-net-sarl** [comment]
So we have to input our account numbers without the "-" ?
The test i made were with the "-" and it seems that your method _is_l10n_ch_postal receive as argument the non-sanitized number.
