### ISSUE TITLE
Invoice : French amount letter

### ISSUE THREAD

**Issue by abenzbiria** [odoo/odoo#2070]
Impacted File system: tools.amount_to_text

I want to display amount to french text in the invoice view using amount_letter field .

 for an amount_total = 14608,71 it return  : quatorze Mille, six Cent huit dh Soixante-dix-un Cents

This file should convert totam amount considering muti lang and multi currencies aspects

My code :
from openerp.tools import amount_to_text_fr

 def _compute_amount_letter(self):
        self.amount_letter=self._get_amount_letter(self.amount_total)

def _get_amount_letter(self,amount)
        return amount_to_text_fr(amount,'dh')

 amount_letter = fields.Char(string='Total',compute='_compute_amount_letter' )

Expected behavior:

  quatorze mille, six cent huit dh soixante et onze centimes

**Comment by Yenthe666** [comment]
Hi @abenzbiria ,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: You can always make a PR with these kind of fixes.

Regards,
Yenthe
