### ISSUE TITLE
The pages_management must change to pages

### ISSUE THREAD

**Issue by goutoudis** [odoo/odoo#20704]
https://github.com/odoo/odoo/blob/11a8728c743b3251912ea45dc57c960aa36bf1fe/addons/website/views/website_templates.xml#L879

**Comment by Yenthe666** [comment]
Hi @goutoudis,

Thank you for your report.
Could you add some more information please? Why do you believe this has to point to `/pages` instead of `website/pages_management?` I don't see the problem at the moment. (CC @JKE-be)

Regards,
Yenthe

**Comment by goutoudis** [comment]
Hi @Yenthe666 and @JKE-be

I go to that URL: /website/pages
I use the search field to filter the pages.
The browser redirect to /website/pages_management?search=test
but the error 404 appear.
If the form redirect to /website/pages?search=test
the response is OK.

Thanks.

**Comment by Yenthe666** [comment]
Thank you for the extra info, this looks wrong indeed. PR @ https://github.com/odoo/odoo/pull/20706 😉
