### ISSUE TITLE
[Idea] : upgrade the security of read access with UUID

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#20703]
Dear Community

I propose in this document an improvement of the security in Odoo.

**Why ?**
In some case some model are not accessible in tree view mode by the web client. But it is accessible by xml_rpc.
For exemple an stock user, who use only the picking model for reception, he need acces to stock.move to show and excecute those picking. But he can also download **with xml_rpc** all stock.move of the company (and sell on dark web).
There lot of other exemple that the UI block data, but by xml_rpc there no more block.
There are case where the Record Rules can not be used (no link between child to parent (exemple : tags, you can not protect only tags use in public project).

**Proposal**
The proposal is base on two new concept (but not hard to implemente).

_1- ID --> UUID_
The first step is to replace the ID (easy to find, because it is an number start 1 to infinit) by an UUID (Universal Unique Identifier), the probability to find one is around zero.
Like that the read() méthode is secure, if you have not the UUID you cannot read any records.

_2- Add search on ACL_
The second step is to add search on ACL. Like that you can give or not the access to search UUID.

_3- Nota_
This proposal do not replace ACL and Record Rules.

**Exemples**
This system is very usefull for user whis very low access.

_Repair man:_
A repair man have access to model mrp.repair. He can create an invoice at the end of repair with a wizard with create.sudo(). He have acces to read on invoice. By default he have access of all invoices in the database. But with this system, and because there a fields Many2one in mrp.repair, he have only access at the linked invoice (and invoice line, ...). The invoice ACL have search=False.

_Random check Invoice:_
An Invoice Check Man, have an wizard to select random invoice to check, this wizard give the UUID of the invoice, and like that he can read the invoice and check. He have no access to the other invoice. In this case is not possible to use un Record Rules, because the access is not predictable.

_Apple lunch iPhone with 512 GB:_
By default the product.attribut are all accessibles by xml_rpc because you need that to show product on the website. If you create the new attribute for the new iPhone, it will be accessible by xml_rpc. Whis this proposal you will have only acces on the attributes use on public product.

_Purchase user access by region:_
You would like restricte access by region at some purchase user. In this case the configuration is most easily :
res.partner : Record Rules with domain on country. ACL Search and Read
Purchase.order : Record Rules with domain on country. ACL Search and Read
purchase.order.line : ACL Read (you don't need to add an record rules)

_Give access on one record over email:_
If you want give a link to one record and give the access to only this record, with the UUID it is build-in.
It is the same use by youtube, each video have an UUID, if the video is not public you cannot play, because you have not the UUID. But if you have the UUID you can.

**Issues**
If you have access an record with field One2Many which there inside all the records you have access to all the record by default (maybe add an argument like that with_acl_search on the field).

**Evolution**
To secure again, it will be possible to change all UUID some time.

What do you think ?

Regards

cc: @odony

**Comment by Yenthe666** [comment]
Hi @fmdl,

Thank you for your report and especially for the detailed information (with usecases)! I wish more reports would contain as much information as yours. Good job on that.
As for a real answer to this: I'm absolutely leaving this open for @odony to make an official statement. He is far more capable in security as me. 😄

**Comment by fmdl** [comment]
Hi @Yenthe666 , there are not an security issue. It is an idea already use on youtube, ... 
For your information I have already speak with @odony , the idea is not completely mature, that like I will suggest to the community. It is an open subject for the next version.

**Comment by Yenthe666** [comment]
@fmdl I've labeled it security as it involves data & well, it touches the subject of security. I'm trying to categorize reports and I believe it fits best under security. 
Thank you for the extra information too!

**Comment by abdurrahmankutlu** [comment]
Hello,  Are there any future plans for this proposal? Why this issue is closed? @fmdl
