### ISSUE TITLE
[10.0] Reordering rules: rule is applied twice

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#20719]
Impacted versions:
10.0

Steps to reproduce:

- Create one product with a vendor and a reordering rule of 1 PC
- Run the scheduler
- A procurement order is generated linked to a purchase order for 1 PC
- Cancel the procurement order and clic on Reset to draft immediately
- Run the scheduler again

Current behavior:

- Another procurement order is generated linked to the same PO
The quantity on the PO has been doubled

Expected behavior:

The quantity should not have been doubled as the reordering rule is for 1 PC.

Video/Screenshot link (optional):
https://youtu.be/tk8cD4cp1-U

**Comment by jco-odoo** [comment]
Is the procurement still linked to the orderpoint?

**Comment by jco-odoo** [comment]
I guess there is still moves related to the procurement that are counted.  (it checks the procurements without its moves)  Doing a quick fix.

**Comment by Cedric-Pigeon** [comment]
@jco-odoo Why does the procurement order stay in 'cancel' state after clicking on 'Reset to draft' on the PO ? It should be in "running" state again. No ?

**Comment by jco-odoo** [comment]
Reset to draft on po instead of on procurement?  Because you handled it differently maybe in the meantime.  (and also by default, it will even cancel the entire flow behind)

**Comment by Cedric-Pigeon** [comment]
No. I mean the reset to draft does not change the state of the procurement. It should do. 
Cancel Purchase Order -> cancel procurement
Reset to draft Purchase order -> no influence on procurement

**Comment by jco-odoo** [comment]
So I understood correctly... Because sometimes it would have cancelled the entire flow or you would have generated another po.

**Comment by nim-odoo** [comment]
@jco-odoo can you merge your fix?

**Comment by nim-odoo** [comment]
Hello,

Actually, I don't think there is anything to fix on the stable version. 
> Reset to draft Purchase order -> no influence on procurement

To me, that makes sense: you might have canceled the procurement manually, setting it back to 'Running' without any confirmation could also cause issues.

You can definitively change that on your side with a specific module:
``` python
    @api.multi
    def button_draft(self):
        self.mapped('order_line').mapped('procurement_ids').filtered(lambda r: r.state == 'cancel').write({'state': 'running'})
        return super(PurchaseOrder, self).button_draft()
```

Or directly in the code: https://gist.github.com/nim-odoo/fff0efd6465829ddaddee6ee0d71ca8b

**Comment by Cedric-Pigeon** [comment]
@nim-odoo I don't really agree. You must prevent reordering rules to be trigger twice in that case. I thing that the fix of @jco-odoo is a must-have.

**Comment by nim-odoo** [comment]
@Cedric-Pigeon The fix of @jco-odoo doesn't work in your use case. The right fix would be to to reactivate the procurements, but that cannot be done in stable.

**Comment by Cedric-Pigeon** [comment]
@nim-odoo I don't understand why you can not fix it on stable. It is a bug, no ?

**Comment by nim-odoo** [comment]
@Cedric-Pigeon to me, that's not a bug. Once you cancel the PO, all procurements are canceled. When reset to draft, the procurements stay canceled. This kind of logic is applied in several places in Odoo: cancellation is propagated, but resetting to draft is not.

Changing this would anyway be a change in behavior, therefore there is no way we will change it in stable.

**Comment by Cedric-Pigeon** [comment]
@nim-odoo Ok, I understand. As I need to change it on several projects, could please create a PR so that I have a common pointer ?
Just like your colleague did for another fix: https://github.com/odoo/odoo/pull/20430

Thanks

**Comment by nim-odoo** [comment]
@Cedric-Pigeon sure, here it is: https://github.com/odoo/odoo/pull/20971
