### ISSUE TITLE
Convert the link from www.odoo.com to https://www.odoo.com

### ISSUE THREAD

**Issue by goutoudis** [odoo/odoo#20714]
Hi.

When i read those emails in my email client, Microsoft Outlook:

https://github.com/odoo/odoo/blob/8787f5acee9b5d2cad15b97804522dc04717a1c1/addons/auth_signup/data/auth_signup_data.xml#L49

https://github.com/odoo/odoo/blob/8787f5acee9b5d2cad15b97804522dc04717a1c1/addons/auth_signup/data/auth_signup_data.xml#L88

https://github.com/odoo/odoo/blob/8787f5acee9b5d2cad15b97804522dc04717a1c1/addons/auth_signup/data/auth_signup_data.xml#L132

https://github.com/odoo/odoo/blob/8787f5acee9b5d2cad15b97804522dc04717a1c1/addons/website_quote/data/website_quote_data.xml#L143

then link change from www.odoo.com to http://192.168.1.3/www.odoo.com

When i open the HTML source of email message, the first line is:
<base href='http://192.168.1.3'>

I suggest to change the:
<a href="www.odoo.com"
to: 
<a href="https://www.odoo.com"

Thanks.

**Comment by Yenthe666** [comment]
Hi @goutoudis,

Thank you for your bug report.
What exactly do you mean with "then link change from www.odoo.com to http://192.168.1.3/www.odoo.com"? There is nothing that changes the link in the email to contain the IP too. As for the https: the Odoo website will automatically redirect HTTP calls to HTTPS so that shouldn't be any issue.

Regards,
Yenthe

**Comment by goutoudis** [comment]
Hi.
The steps to produce the issue:
1)	Odoo is installed at my computer with IP-URL: 192.168.1.3
2)	From Settings/Dashboard I invite some user with email e.g. user@example.com
3)	The user receives the email 
4)	The user click at Odoo link from email footer
5)	The browser (Chrome in my case) try to load the page: http://192.168.1.3/www.odoo.com instead of http://www.odoo.com

This happens because the html code of email contains the element:
<base href='http://192.168.1.3'>
and the href attribute of linκ Odoo is:
href=”www.odoo.com”

If you change the href from "www.odoo.com" to "https://www.odoo.com" works fine.

Thanks
Kostas Goutoudis

**Comment by Yenthe666** [comment]
Hmm I see. @mart-e should we change this?

**Comment by mart-e** [comment]
Hello,

We can change that in master but it would break the translations of the email templates in stable

**Comment by Yenthe666** [comment]
@goutoudis feel free to make a PR to fix this. Otherwise it'll be handled as a best effort by @mart-e.
