### ISSUE TITLE
Button actions don't get called unless record is edited.  Show-stopper bug. 

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#20736]
Impacted versions: 11.0 from commit https://github.com/odoo/odoo/commit/0b41f21c165f231054488fd660c04f2ac3dc2560

Steps to reproduce: Create a button on a form view that calls a model method e.g. 
`<button string="Raw report" name="raw_form" type="object"/>`
Try pushing the button from view mode of the form with no changes to the record. Note how the button does not function.   

Next go to the form, enter edit mode, and make some change to the form. Now push the button. See how it works as it should. 

This issue supersedes issue #20509. As the commit comment on 0b41f21 describes, buttons with and w/o confirm dialogs used to behave differently. As issue #20509 pointed out, one behavior worked and the other didn't. Now the behavior has been unified so that it's broken with or without a confirm dialog. 

Current behavior: Buttons on forms don't function unless the form has been edited. 

Expected behavior: Buttons work whether form is edited or not per the docs and in accord with pre-11.0 behavior. 

Video/Screenshot link (optional):

**Comment by elgow** [comment]
BTW, this was tested with branch 11.0 commit https://github.com/odoo/odoo/commit/dc6757032fea0cc7713bf316b126fc1970cddae5

**Comment by ged-odoo** [comment]
@elgow This sounds bad, but I think I must be missing something.  I tried to literally do what you suggest:
- open a customer form view in 11.0
- add <button string="Raw report" name="raw_form" type="object"/> in the form view
- reload the page (on an existing customer, in readonly mode)
- click on the button

It then calls the route /web/dataset/call_button, as expected. I tried in edit mode, and did not see any difference.  What am I missing?

**Comment by elgow** [comment]
Sorry, my bad. I've traced the problem to the commitChanges() call on my custom widget. When not it edit mode my widget was returning an unresolved jQuery Deferred from commitChanges() which caused processing to freeze waiting for it to resolve. Returning either a resolved Deferred or nothing at all fixes. Migrating my custom widget to the new 11.0 front-end class structure has been an adventure. 

Thanks for testing this and sorry for the trouble.
