### ISSUE TITLE
Website Menuitem translation

### ISSUE THREAD

**Issue by brychmilan** [odoo/odoo#20743]
Impacted versions:
ENT 11.0
Steps to reproduce:
If you create menuitem on website and translate it to Czech, it seems works fine if you are logged in. After logout is always shown only one language version - Czech rewrite English.
Tested on clear ent instance of 11.0
Current behavior:
Create new menuitem as EN Admin - give name to menuitem.
Translate menuitem as EN admin to Cz language.
It seems works fine until logout.
After logout Odoo show only one translation -Cz.
All other translations on webpage works like a charm.
Other tested languages works fine.
Expected behavior:
After translation we expected changing translations also on website menuitems during change languages.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @brychmilan,

Thank you for your report. This works fine out of the box though? I made a new menuitem "Overview", translated it to "Overzicht" in Dutch, then logged off and watched the website in Dutch:
![image](https://user-images.githubusercontent.com/6352350/32482756-5d874134-c399-11e7-966e-8e5b302fbc4c.png)

Perhaps you forgot to switch the language or something?

**Comment by brychmilan** [comment]
And in English translate you got English or Dutch translation please? Because in X language we get translated term but in English we see X language. Thank you for test.

**Comment by brychmilan** [comment]
OK I can approve your answer - this is probably caused by some changes in our module. Abolutely new installation from git work fine. Thank you and sorry for missinfo.

**Comment by Yenthe666** [comment]
Thanks for the extra info and best of luck!

**Comment by brychmilan** [comment]
Hi, I have one more thing. Issue is still here but only if we use Czech language. Can you please try i with Czech translation? If we use Germany or many others all seems fine, but Czech language cause this issue.

**Comment by Yenthe666** [comment]
@brychmilan,
Works fine for me too.
Czech:
![image](https://user-images.githubusercontent.com/6352350/32545285-7c2bace6-c47b-11e7-9b41-449813db9032.png)
English:
![image](https://user-images.githubusercontent.com/6352350/32545293-84643946-c47b-11e7-8033-2b8a6c19876e.png)

**Comment by brychmilan** [comment]
In your post you are logged in, bud if you are as public user (logged out) there is only czech translation. Other languages works fine also if you are logged out.

**Comment by brychmilan** [comment]
Is seems as EN menu is replaced by Czech menu for public users.

**Comment by brychmilan** [comment]
Hi do you have some news about this please? This bug block using of web modul. Thank you for every update.

**Comment by Yenthe666** [comment]
@JKE-be could you have a look too?

**Comment by brychmilan** [comment]
Hi all, some update about this? Can you approve our bug? How long is bugfix time on ENT version for this type of bug?

**Comment by JKE-be** [comment]
Hi, 

If the issue is on GitHub, that will be 'best effort' to find time to fix it by the concerned team.

If you have an enterprise contract, you can open an Odoo issue and that should be done by the bug fix team.

Don't forget to link your Odoo issue with the Github issue (and your Github issue in the Odoo issue) to avoid to make the job 2 times and so block another issue that could be fixed at the same time.

Best regards

**Comment by brychmilan** [comment]
We are a partner of Odoo and this bug is present in 2 instances of our customers with ENT contract. We can wait more time but we need estimate for our customers who wait for fix.

**Comment by JKE-be** [comment]
In this case, open a ticket with one of these contracts is your best solutions to make this bug as a priority.

Because I have some doubts that I got the time this week to take a look at your issue. 
And @rdeodoo is not there today to ask him an ETA.

**Comment by JKE-be** [comment]
After analyzing your problem.

Are you sure that the problem is not only for the default lang ? that ignore it and use your chrome lang ...

Seems what we can reproduce here.

**Comment by brychmilan** [comment]
Can you please create runbot and send me a link? I try reproduce bug there and send you description. We see bug on fully EN notebook too.

**Comment by brychmilan** [comment]
http://279638-11-0-a10021.runbot9.odoo.com here is runbot with CZ lang. If I am logout I see EN and CZ menu same. Bud correctly I want see czech menu in czech lang and EN with EN lang.

**Comment by rdeodoo** [comment]
@brychmilan 
We found the issue, it will be fixed ASAP, in the upcoming days. 
Indeed, the fix should be written in part of the code that is currently being refactored.
If this is really critical, I can send you an untested patch (it fixes your issue and should not cause any side effects).

Regards

**Comment by JKE-be** [comment]
@brychmilan 

Here a wip patch for master: https://github.com/odoo-dev/odoo/commit/73b8709a0e67a7b7f97b0b3fe2d5c6cf3fae8742?w=1#diff-fbc4825cc5f9fbcd44a55994c7a8d953R73

But just move the call to super at first line should be enough for your bug.

Best regards

**Comment by brychmilan** [comment]
Hi, we had deploy your changes to both instances and now all works as a charm. Thank you very much for support and debugging!

**Comment by JKE-be** [comment]
Nice to read you again and see that it works.

Just for your information, some test fails with this path due to this line: 
https://github.com/odoo-dev/odoo/commit/73b8709a0e67a7b7f97b0b3fe2d5c6cf3fae8742?w=1#diff-fbc4825cc5f9fbcd44a55994c7a8d953R85

request.website = request.website
should be 
request.website = request.website.with_context(context)

Without it, website_id is not set in the context and can bring strange behaviour on all modules that support multi website.

I will try to find a reviewer for the commit and will merge it in standard asap.

**Comment by brychmilan** [comment]
Thank you for this info and for try merge also. Thank you
