### ISSUE TITLE
[Master/12.0] China Localisation - 

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#20753]
<h1>Impacted Versions:</h1>
ALL

<h1>Steps to reproduce:</h1>
Try to print the following reports and compare with 'Kingdee' output (popular Odoo competitor in China) for example:

- Balance
- Sheets
- Income Statements
- Profit & Loss Statements
- Vouchers/Journal Entries >> Fapiao Report Printed From Journal Entries

<h1>Current Behaviour:</h1>
No complete China localisation in core supporting the reporting requirements for the China government.

<h1>Expected Behaviour:</h1>
CN Localisation includes additional reporting requirements.

<h1>Video/Screenshot link (optional):</h1>

<h1>More Information Updated At a Later Date Showing GAP Analysis</h1>
- More info coming soon.

**Comment by Elkasitu** [comment]
Hello,

I think issue #18512 is an open thread for these kind of suggestions, I invite you to write your feedback over there since there's a higher chance that it'll be taken into consideration.

@lap-odoo

**Comment by lukebranch** [comment]
@Elkasitu ,

Thanks for the link.

Closing in favour of #18512 .
