### ISSUE TITLE
[11.0] When company does not have logo set, reporting is not working.

### ISSUE THREAD

**Issue by dxepitropov** [odoo/odoo#20765]
Impacted versions:
11.0
Steps to reproduce:
Create a new DB (no demo data) -> Install Leaves App, Generate Report "Leaves by Department"

Current behavior:
When you click print it prompts for choose a report Layout. After you click save & print you receive the following error message: " Form content is missing, this report cannot be printed. "

Expected behavior:
Either notify that a report layout cannot be set without company logo in a clear manner or fix it to enable to generate a report without having a logo for the company.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/29486955/32497678-ff6fb67a-c3d5-11e7-9db0-2d8d5e2f1ae8.png)

**Comment by Yenthe666** [comment]
Hi @dxepitropov,

Thank you for your bug report.
I've just tested this and I can confirm that this is a bug.
I've made an official bug report with the number 803051 and it should be handled soon.
OPW 803051

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Fixed at https://github.com/odoo/odoo/commit/733ce266ef793652f5958c24e2a8a6f443432552
