### ISSUE TITLE
[Odoo Forum]: all new questions are tweeted under ThinkOpen Solutions name in twitter!!!

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#20764]
Check this: https://twitter.com/thinkopenTW

I don't think that this is good for ThinkOpen's reputation!

@Yenthe666 let's earn some Caipirinhas from ThinkOpen Brazil :-)

**Comment by Yenthe666** [comment]
@treviser aren't they tweeting this theirself? Perhaps they made a checker to automatically tweet? Or am I missing something huge here? 😆

**Comment by treviser** [comment]
No, these are completely different people and it's every new post meanwhile.

**Comment by Yenthe666** [comment]
@treviser yes this is indeed every new topic on the help forums. I just don't see what the problem is though? They probably scrape the page, get the content and make tweets from it automatically.

**Comment by treviser** [comment]
@Yenthe666 That would not make any sense at all, creating such efforts to damage the own reputation???

**Comment by Yenthe666** [comment]
Well, there isn't much we can do about it. This literally looks like the did this theirselves. 😄 
CC @JKE-be or beloved forum guru.

**Comment by treviser** [comment]
@Yenthe666 I tried to contact them, let's see. I don't believe they do that themselves and on purpose.

**Comment by JKE-be** [comment]
@treviser waiting your feedback ;)

**Comment by treviser** [comment]
@Yenthe666 .....mmmmhhh, on the other hand, you may be right, this is maybe a new SEO marketing gag to get better rankings....tons of content linked to the own name....

**Comment by Yenthe666** [comment]
Yup - I'm quite sure it is. It makes me think of tweets like https://twitter.com/Suleman_Hasib/status/927559813432774656

**Comment by treviser** [comment]
Unbelieveable....what a crazy world that is

**Comment by Yenthe666** [comment]
Let me know if you get any response from the guys - but I think we can conclude some people really do everything for some views 😉

**Comment by treviser** [comment]
Got a response, they are really doing that on purpose in the believe it would support their marketing.

**Comment by treviser** [comment]
Sorry for bothering you all in my naïveté :-)

**Comment by Yenthe666** [comment]
LOL. Hmm, yes, it will absolutely support their marketing /sarcasm
Thanks for the confirmation! :-)
