### ISSUE TITLE
Error when trying to add a picture to the project task description

### ISSUE THREAD

**Issue by dominiquekonsuntack** [odoo/odoo#20778]
Impacted versions: 11 Community and Enterprise

Steps to reproduce:
Go to a task form
Edit
Add a picture to the description field. A dialog box opens to upload an image.
Upload the image.
Save
Error message
![screenshot_110817_081141_am](https://user-images.githubusercontent.com/13960037/32524837-8fd4a1f4-c45c-11e7-80db-fd2d89c8425e.jpg)

Error:
Uncaught TypeError: Cannot read property 'className' of null

http://odoo.justanalytics.com/web/content/359-6c941ef/web_editor.assets_editor.js:285
Traceback:
TypeError: Cannot read property 'className' of null
    at Class.clear (http://odoo.justanalytics.com/web/content/359-6c941ef/web_editor.assets_editor.js:285:988)
    at Class.save (http://odoo.justanalytics.com/web/content/359-6c941ef/web_editor.assets_editor.js:305:68)
    at Class.prototype.(anonymous function) [as save] (http://odoo.justanalytics.com/web/content/356-5ded524/web.assets_common.js:3811:488)
    at HTMLButtonElement.<anonymous> (http://odoo.justanalytics.com/web/content/356-5ded524/web.assets_common.js:4038:421)
    at HTMLButtonElement.dispatch (http://odoo.justanalytics.com/web/content/356-5ded524/web.assets_common.js:892:451)
    at HTMLButtonElement.elemData.handle (http://odoo.justanalytics.com/web/content/356-5ded524/web.assets_common.js:865:173)

Current behavior:
In order to add a picture, we have to do in two steps.
Step 1: Upload the picture, then close the pop up window
Step 2: re-open the "add picture" wizard, select the picture uploaded previously, and save
 
Expected behavior:
We should not need to do two steps ...

Video/Screenshot link (optional):
![screenshot_110817_081645_am](https://user-images.githubusercontent.com/13960037/32524959-3617ffc0-c45d-11e7-908a-b12d3a916549.jpg)

**Comment by Yenthe666** [comment]
Hi @dominiquekonsuntack,

Thanks a lot for your report! I can confirm that this is a bug in Odoo:
![image](https://user-images.githubusercontent.com/6352350/32535616-0ee79822-c45b-11e7-9a7c-f105846a4953.png)
@ged-odoo it is a JS error - can you check? It is coming from https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/web_editor/static/src/js/widgets/widgets.js#L185

Regards,
Yenthe

**Comment by qsm-odoo** [comment]
@Yenthe666 For editor errors, you can ping me instead of @ged-odoo, most of the time I will handle those bugs anyway :wink: 

There were some bug fixes concerning that media dialog recently. I think the traceback bug is gone. I also already know about the two-steps problem and can confirm it is a regression as it did not happen in previous versions. I will try to fix this as soon as possible.
@kebeclibre I think we talked about that problem recently (uploading an image closes the modal without adding it), did you check anything about that or not ?

**Comment by qsm-odoo** [comment]
I guess we can keep this opened while the upload behavior is not fixed :)

**Comment by Yenthe666** [comment]
Alright! Thanks for the feedback.

**Comment by qsm-odoo** [comment]
In fact, both behaviors are fixed.
