### ISSUE TITLE
MRP :: Routing :: Work Orders

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#2077]
If on the manufacturing order you delete any auto-allocated routing, the corresponding work order is not deleted form the MO.

-> Either make Routing read only
-> Or make an appropiate nchange

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
