### ISSUE TITLE
Odoo 11 error when create invoice from SO

### ISSUE THREAD

**Issue by phuongnguyen3108** [odoo/odoo#20780]
Impacted versions: 11

Steps to reproduce:
1. Create a Customer Quotation for a product which its invoicing policy = 'Delivered quantity' (say "Server")
2. Confirm sale and set Delivery to "Done"
3. Click "Create Invoice" button.

Current behavior:
System shows error message "There is no invoicable line" 
Expected behavior:
Invoice should be created successfully since the product is received
Video/Screenshot link (optional):
![invoice_create_error](https://user-images.githubusercontent.com/32894807/32528775-75be2e60-c467-11e7-8efd-92de1aa15715.jpg)

**Comment by sle-odoo** [comment]
@phuongnguyen3108 Hello, sorry but i'm not able to reproduce this issue. Could you try it on the latest runbot and tell me the exact steps you followed? Thank you

**Comment by Yenthe666** [comment]
No problem at my side either.

**Comment by phuongnguyen3108** [comment]
I could not re-produce it either. You can close it. Thank you.

**Comment by vuducmanh96vp** [comment]
![image](https://user-images.githubusercontent.com/33730451/78811769-9068f480-79f4-11ea-8f1f-3594e09ea488.png)

I have the same issues when my order has product is a server
