### ISSUE TITLE
Sign up and Reset Password lost

### ISSUE THREAD

**Issue by zhujin001032** [odoo/odoo#20788]
Impacted versions:10.0

Steps to reproduce:
When install "tko_web_sessions_management" ,Web front "Sign up" and " Reset Password " lost !
![11111](https://user-images.githubusercontent.com/7955640/32537307-1777c6f0-c49d-11e7-813f-6b034710a7cb.png)

When uninstall "tko_web_sessions_management" , Web front "Sign up" and " Reset Password " show .
![2222](https://user-images.githubusercontent.com/7955640/32537313-1d1f6748-c49d-11e7-8a3a-c7fcd7ac98f9.png)

Please help me ，thanks

The "tko_web_sessions_management" link : https://github.com/thinkopensolutions/tko-addons
Error messages from chrome Console:
Server application error {"message":"Odoo Session Expired","code":100,"data":{"debug":"Traceback (most recent call last):\n  File \"/Users/hezhujin/Documents/odoo_apps1/Trunk/odoo/http.py\", line 638, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/Users/hezhujin/Documents/odoo_apps1/Trunk/odoo/addons/base/ir/ir_http.py\", line 184, in _dispatch\n    auth_method = cls._authenticate(func.routing[\"auth\"])\n  File \"/Users/hezhujin/Documents/odoo_apps1/Trunk/odoo/addons/base/ir/ir_http.py\", line 112, in _authenticate\n    getattr(cls, \"_auth_method_%s\" % auth_method)()\n  File \"/Users/hezhujin/Documents/odoo_apps1/Trunk/odoo/addons/base/ir/ir_http.py\", line 85, in _auth_method_user\n    raise http.SessionExpiredException(\"Session expired\")\nSessionExpiredException: Session expired\n","exception_type":"internal_error","message":"Session expired","name":"odoo.http.SessionExpiredException","arguments":["Session expired"]}}

Current behavior: Sign up and Reset Password lost

Expected behavior: Sign up and Reset Password Show

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @zhujin001032,

Thank you for your report but the bug tracker is only for bugs in the official code. This module is not from Odoo S.A itself.
You can ask for support at the creator of the module or on the official help forums (at help.odoo.com).

Regards,
Yenthe

**Comment by zhujin001032** [comment]
Thanks

**Comment by zhujin001032** [comment]
@Yenthe666  Thanks.
