### ISSUE TITLE
suds

### ISSUE THREAD

**Issue by humanitiesNerd** [odoo/odoo#20790]
Impacted versions: 11.0

Steps to reproduce: trying to install the sales module

Current behavior: an error dialog window pops up claiming no suds module available (suds-jurko is installed but it' s for python2, I suppose)

Expected behavior: the module to install flawlessly

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @humanitiesNerd,

This is not a bug but an implementation issue. You should install suds for Python 3, as Odoo runs on Python 3 by default. 
`sudo pip3 install suds-jurko` would fix this for example.

Regards,
Yenthe

**Comment by humanitiesNerd** [comment]
2017-11-08 10:35 GMT+01:00 Yenthe V.G <notifications@github.com>:

> Hi @humanitiesNerd <https://github.com/humanitiesnerd>,
>
> This is not a bug but an implementation issue. You should install suds for
> Python 3, as Odoo runs on Python 3 by default.
> sudo pip3 install suds-jurko would fix this for example.
>
> Regards,
> Yenthe
>
> —
>

Ok, thank you !

**Comment by Yenthe666** [comment]
You're welcome - best of luck!
