### ISSUE TITLE
[11.0] Invoices reconciled via Payment Matching smart button on Payment are not setting has_invoices, so the Invoices smart button is missing, and no Invoices are associated with the Payment, even though the Invoices have their balances correctly reduced..

### ISSUE THREAD

**Issue by vcloud9ray** [odoo/odoo#20804]
With the new functionality to do payment matching directly from the Payment, the resulting logic to allow the Invoice button to be shown isn't working - the Invoices do show they are paid but are not linked to the Payment (even if I force the Invoices button to be shown, nothing is shown in the Invoice list when the button is clicked).

Impacted versions:

11.0

Steps to reproduce:

Create a Customer Payment and click the (newly added at v11) PAYMENT MATCHING smart button to reconcile it with Invoices:

![](https://i.imgur.com/3XkKB49.png)

Current behavior:

The Invoices are closed (or have balances reduced) as expected.

The Invoice smart button is not shown on the Customer Payment.
The **has_invoices** variable on the account.payment record is not set to True.
Users have no way to see which Invoices the Payment was applied to (they could at v10)

Expected behavior:

The Invoice smart button IS shown on the Customer Payment.
The **has_invoices** variable on the account.payment record IS set to True.
Users DO have a way to see which Invoices the Payment was applied to.

Video/Screenshot link (optional):

Please let me know if you need a more detailed explanation.

**Comment by Yenthe666** [comment]
@qdp-odoo this is for you. 😉

**Comment by celm1990** [comment]
I confirm issue, please, any solution????

**Comment by Yenthe666** [comment]
@vcloud9ray did you make an OPW for this one?

**Comment by vcloud9ray** [comment]
No.   I have nobody using Payment matching in v11 yet.

**Comment by Yenthe666** [comment]
Hmm, neither do I so can't make a ticket there. @qdp-odoo could you check whenever you have time please?

**Comment by gustavovalverde** [comment]
OPW-813642

**Comment by Yenthe666** [comment]
Hooray! Thanks for the report @gustavovalverde - let us know what the feedback is.

**Comment by oco-odoo** [comment]
Hello, 

Thank you for reporting the issue. I just had a talk about it with qdp, and this is unfortunately something we won't be able to solve efficiently in stable versions. However, we are aware that this behavior is confusing, and are going to work on a fix for a future version. I'm closing this issue, but this does not mean we are forgetting you ;)

**Comment by gustavovalverde** [comment]
Even though you guys label this as "confusing", for the user it's a feature that is not giving the expected result (a bug), as explained here: https://github.com/odoo/odoo/issues/22386#issue-289980645 
Applying a payment through both ways should show the invoices paid in the payments menu, as it's a bunch easier to do it with Payment Matching.

Could we at least have a fix in master so we can cherry-pick it? Otherwise there's no way to correctly apply advances in payment made by customers and give a payment receipt with the right information.

P.D.: I wan't to remove this excel use for creating customer receipts :)

**Comment by qdp-odoo** [comment]
@gustavovalverde yeah sure, we'll improve in master and give the patch here. So let's leep closed the ticket and reopen this issue. Ok?

**Comment by Yenthe666** [comment]
Good call @qdp-odoo 👍

**Comment by gustavovalverde** [comment]
@qdp-odoo Agree

**Comment by gustavovalverde** [comment]
Hi, is there an update on this issue? This is becoming a bit overwhelming on implementations that have to reconcile a payment with a bunch of invoices, as the user has to go to each invoice and apply the payment manually instead of  using the reconcile function.

**Comment by oco-odoo** [comment]
@gustavovalverde I'm currently working on it ;)

**Comment by gustavovalverde** [comment]
Thanks for the ping @oco-odoo 👍

**Comment by qdp-odoo** [comment]
fixed by https://github.com/odoo/odoo/commit/c9b7cf140cafd49c06ca114975eee220bb54112a
