### ISSUE TITLE
No official/compatible release of wkhtmltopdf 12.1 for Ubuntu 17.04 (Zesty Zapus) or greater

### ISSUE THREAD

**Issue by mohitg1213** [odoo/odoo#20823]
Getting error while printing PDF reports, on Ubuntu 17.04 or greater for Odoo 10/11

As explained in Odoo Installation page, " _the version of wkhtmltopdf available in debian repositories does not support headers and footers so it can not be installed automatically. The recommended version is 0.12.1..._", but it is not available on the wkhtmltopdf download page for Ubuntu 17.04 or greater. I have tried with other available options but with no success. 
Can anybody suggest some other links/way to fix it ?

**Comment by Yenthe666** [comment]
@sle-odoo can you give feedback please?

**Comment by eisenheimjelid** [comment]
You can download old versions from official page in: https://wkhtmltopdf.org/downloads.html for example, exactly 0.12.0 are in https://github.com/wkhtmltopdf/wkhtmltopdf/releases/0.12.0/ i trying the same.

**Comment by eisenheimjelid** [comment]
Ok! i understand, the error is:
`Wkhtmltopdf falló (error code: -6). Mensaje: b'The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display \n' `

With wkhtmltopdf 0.12.3.2

**Comment by mohitg1213** [comment]
@eisenheimjelid I tried to install wkhtmltopdf 0.12.1 version from same github repo, but unfortunately it didn`t worked(installed) for me, are you able to do it ?

**Comment by eisenheimjelid** [comment]
Hi! I did solve. But my enviroment is with Debian 9 Stretch amd64, and when i tryied to follow the next instructions for install wkhtmltox, i had multiple errors and broken dependecies, because this packages are from 2014.
```bash
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-wheezy-amd64.deb
dpkg -i  wkhtmltox-0.12.1_linux-wheezy-amd64.deb
```
So, with Debian i change the apt sources with the old wheezy, adding into `/etc/apt/sources.list`:
```
deb http://ftp.mx.debian.org/debian wheezy main contrib non-free
deb-src http://ftp.mx.debian.org/debian wheezy main contrib non-free
```
I'm from Mexico, so the apt urls are correct for me, and function.

You, in Ubuntu maybe can do same, adding the apt sources for Trusty (14.04) in your actual Zesty (17.04) and download the .deb installer from https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.1 (which do you need? i386 o amd64, select one) and finally installing manually .deb file. If you have some error after execute dpkg, after that you can execute: `apt --fix-broken install` and apt made all, installing from Trusty the correct dependencies.

I hope you cand solve this, with this instructions.

I think this is a problem, and maybe Odoo will be work on upgrade the dependency for use wkhtmltopdf 0.12.3, or change with other library or component newer.

**Comment by mohitg1213** [comment]
@eisenheimjelid : I tried installing wkhtmltopdf manually via .deb file downloaded from [,](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.1) but i got error

`**root@d5487876f00d:/# dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb**
Selecting previously unselected package wkhtmltox.
(Reading database ... 4383 files and directories currently installed.)
Preparing to unpack wkhtmltox-0.12.1_linux-trusty-amd64.deb ...
Unpacking wkhtmltox (0.12.1) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on fontconfig; however:
  Package fontconfig is not installed.
 wkhtmltox depends on libfontconfig1; however:
  Package libfontconfig1 is not installed.
 wkhtmltox depends on libfreetype6; however:
  Package libfreetype6 is not installed.
 wkhtmltox depends on libpng12-0; however:
  Package libpng12-0 is not installed.
 wkhtmltox depends on libjpeg-turbo8; however:
  Package libjpeg-turbo8 is not installed.
 wkhtmltox depends on libx11-6; however:
  Package libx11-6 is not installed.
 wkhtmltox depends on libxext6; however:
  Package libxext6 is not installed.
 wkhtmltox depends on libxrender1; however:
  Package libxrender1 is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wkhtmltox
`
As suggested i tried `apt --fix-broken install`, but it comes up with this error:
`**root@d5487876f00d:/# apt --fix-broken install**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  wkhtmltox
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
1 not fully installed or removed.
After this operation, 120 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 4403 files and directories currently installed.)
Removing wkhtmltox (0.12.1) ...
dpkg: warning: while removing wkhtmltox, directory '/usr/local/share' not empty so not removed`


FYI, It worked on previous Ubuntu for Trusty (14.04) but on Ubuntu actual Zesty (17.04) it didn`t .

**Comment by eisenheimjelid** [comment]
Yes!, will work on Trusty 14.04, because the dependency for wkhtmltox exists only for 14.04. So, you can try to add Deb Apt URL into `/etc/apt/sources.list`for Trusty, into your Zetsy (17.04).

**Comment by jpaulin** [comment]
If the package installation works by swapping sources (or adding new ones) to /etc/apt/sources.list 
as mentioned, what are the reasons that the Zesty distro have not used this one yet? Are we 
a) riding on such cutting edge that this solution (which was proposed) is a kind of "peek ahead of time"
b) or, is that swap implicating some run-time hazards, ie. in some instances the wkhtmltopdf might crash?

**Comment by pedrobaeza** [comment]
Closing this one as referring old versions and being package related.
