### ISSUE TITLE
[10.0, 11.0] Implementation progressbar stays in main screen

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#20828]
Impacted versions: 10.0, 11.0

Steps to reproduce:
- Open up an app that has an implementation guide (for example accounting):
![image](https://user-images.githubusercontent.com/6352350/32607201-63b5b3cc-c558-11e7-97d0-8de3e2d6601f.png)
- Go back to the main app switcher. You will now see the progressbar from the implementation guide in your screen:
![image](https://user-images.githubusercontent.com/6352350/32607225-7a895b08-c558-11e7-9e6f-faed46fcef0a.png)
- Open up an app that has no implementation guide (for example Notes)
- Go back to the main app switcher. The progressbar is now gone:
![image](https://user-images.githubusercontent.com/6352350/32607259-9be02746-c558-11e7-888d-a244c38c3dde.png)

Current behavior: The progressbar from the implementation guide is kept on the mainscreen if you come from an app that has an implementation guide.

Expected behavior: The progressbar is hidden on the main screen.

**Comment by Yenthe666** [comment]
OPW 781726
@ged-odoo this might be for you 😉

**Comment by nim-odoo** [comment]
IMHO, that's not an issue. If I follow what you say, what should happen if I open several apps which have an implementation guide?

**Comment by Yenthe666** [comment]
@nim-odoo you should see the bar when you have the bar open but not in the main screen. Why would you ever want to have a progress bar floating around on the main menu of Odoo while you don't know where it is from?

**Comment by nim-odoo** [comment]
@Yenthe666 ok, got it, I understood incorrectly. Well still, I don't see it as an issue: if you click on "<" (top left), you are back to accounting. So keeping this progress bar doesn't seem weird to me.

**Comment by nim-odoo** [comment]
To me, that's more a usability concern than any kind of issue. This behavior has been introduced back in v9, therefore I don't see why suddenly this should be a bug since it doesn't prevent you from working. I will create a feedback, but clearly no fix in stable.

**Comment by Yenthe666** [comment]
It is a usability concern, not really a bug as it doesn't break anything I guess but that is the only way to officially reach out. Thank you @nim-odoo
