### ISSUE TITLE
[9.0, 10.0, 11.0] Website planner is not translated from the website

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#20829]
Impacted versions: 9.0, 10.0, 11.0

Steps to reproduce:
- Install the website module and install another language that is fully translated (Dutch in my example).
- Go to settings and open the implementation planner for the website - you will see it translated in Dutch:
![image](https://user-images.githubusercontent.com/6352350/32609136-e64a5abc-c55e-11e7-88f7-76c7581f203a.png)
- Go to the website and open the implementation planner from the website:
![image](https://user-images.githubusercontent.com/6352350/32609172-ffdd223e-c55e-11e7-8bdd-f8729764f017.png)
The same implementation planner is not translated in Dutch, although my website is in Dutch:
![image](https://user-images.githubusercontent.com/6352350/32609208-2232bc54-c55f-11e7-8f46-0edef72801c4.png)
Dutch is 100% translated for Odoo 9 so that can't be the issue:
![image](https://user-images.githubusercontent.com/6352350/32609222-3629db02-c55f-11e7-91b9-bc8313b1f8cf.png)

Current behavior: The website planner is not translated from the website, although it is from the backend.

Expected behavior: The website planner is translated from the website and from the backend.

**Comment by Yenthe666** [comment]
OPW 781727
@JKE-be might be something for you too. 😉

**Comment by JKE-be** [comment]
@nle-odoo can we close it ?

**Comment by nle-odoo** [comment]
I have 3 PR (9.0, 11.0 and master):

- 9.0 https://github.com/odoo/odoo/pull/21004
- 11.0 https://github.com/odoo/odoo/pull/21006
- master https://github.com/odoo/odoo/pull/21035

9.0 and 11.0 are hackish but should be near ready to merge.

master is what @ged-odoo prefer but I still have work to do.

I will probably merge 9.0 and 11.0 next week after doing last tests.

**Comment by Yenthe666** [comment]
Awesome! Keep up the good work

**Comment by nle-odoo** [comment]
Hello,

Sorry for the delay, I merged 9.0 (#21004) and 11.0 (#21006) pull request that should solve the issue and for other version it will be available in next forward-ports.

**Comment by Yenthe666** [comment]
Thanks a lot @nle-odoo!
