### ISSUE TITLE
[purchase] wrong invoice status when return picking

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#20839]
Impacted versions:
* 11.0

Steps to reproduce:
* Create purchase by 100 qty
* Receive purchase by 100 qty
* Create invoice by 100
* Create return by 1 qty with `Refund (to update SO/PO)` 

Current behavior:
Status invoice is `No Bill to Receive`

Expected behavior:
Status invoice must be `Waiting Bills`

**Comment by vcloud9ray** [comment]
If there are no Bills to receive, why do you want the PO Billing Status to show Waiting Bills?

You have already created the Bill, for 100.

What you will get next from your Vendor is a Credit Note, not a Bill.

When you select the PO on a new Vendor Credit Note, it will list the 1 item you returned.

**Comment by bst-odoo** [comment]
Hello @JulioSerna ,

Thanks for your feedback. It will be done in master by our R&D team.

Kind regards,

BST

**Comment by JulioSerna** [comment]
@bst-odoo 

What is the fix?

could be applied into version11 as well?

**Comment by bst-odoo** [comment]
Hello Julio,

Your request is an improvement and not a fix. It won’t be merged in a stable version. That’s why our R&D team will handle it.

Kr,

BST

De : Julio [Vauxoo]
Envoyé le :jeudi 16 novembre 2017 17:03
À : odoo/odoo
Cc : bst-odoo; Mention
Objet :Re: [odoo/odoo] [purchase] wrong invoice status when return picking(#20839)

@bst-odoo
What is the fix?
could be applied into version11 as well?
