### ISSUE TITLE
key number 83 produce a . not an , like expected 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#20837]
Impacted versions:
10
Steps to reproduce:
1 set the server in spanish
2 go to a product and type 123,12€ using the numpad
Current behavior:
pressing key number 83 produce a . not a , when introducing numbers
Expected behavior:
key number 83 should produce , not a .

key number 83 is between 0 and enter on numpad

**Comment by Yenthe666** [comment]
Hi @icf20,

Thank you for your report.
Aren't you just talking about the configuration of the decimal and thousand separators? (You can find this under settings > Translations > languages
![image](https://user-images.githubusercontent.com/6352350/32648325-943dd6f8-c5f5-11e7-9274-696b359e29bb.png)
Wouldn't this resolve your issue?

**Comment by icf20** [comment]
> Aren't you just talking about the configuration of the decimal and thousand separators?
no no we dont talk about decimal separator i am talking about how the software responds when i press the key

for example in speed crunch if i set the decimal to be . when i press the key i get dot if i set the decimal to be , i got , 

i am talking about how odoo reads when i press the key

**Comment by icf20** [comment]
apparently this was "solved" in version 8 by installing this app https://www.odoo.com/apps/modules/8.0/web_decimal_numpad_dot/

**Comment by icf20** [comment]
if anyone still wonders you need to install this to solve this issue that should have been fixed by default https://github.com/OCA/web/tree/11.0/web_decimal_numpad_dot
