### ISSUE TITLE
Print survey answer is empty

### ISSUE THREAD

**Issue by zouine** [odoo/odoo#20836]
Impacted versions: 11.0

Current behavior: when i fill and submit a survey, 'print answers' get me a blank form instead of one with the answers i submitted.

Expected behavior: get my answers on the form
![survey](https://user-images.githubusercontent.com/13539058/32619160-c59f3b3a-c571-11e7-9c21-d10d90a5a7ea.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @zouine,

Thanks a lot for your bug report. I can confirm that this is a bug - the answers are not shown:
![image](https://user-images.githubusercontent.com/6352350/32648199-1d958686-c5f5-11e7-88ea-c7883e3050f3.png)
@JKE-be can you check the issue please?

**Comment by zouine** [comment]
Hello,
I see that I can view my answer, so it was saved in Odoo, so the issue concerns viewing the answer, not saving it..I guess
![odoo-sur](https://user-images.githubusercontent.com/13539058/32655888-826ea864-c607-11e7-8823-7172562f85b6.png)

**Comment by Yenthe666** [comment]
The problem is in the view the data is not printed (or it is not passed to the view).

**Comment by zouine** [comment]
Hello,
Did anybody manage to solve or find where does the problem come from  ?
Thnx

**Comment by Yenthe666** [comment]
Hi @zouine,

Nobody had the time to look at this (yet). If you have an enterprise contract I'd advice you to report it with your license. This will be handled faster than though Github as this is best effort.

Regards,
Yenthe

**Comment by zouine** [comment]
Thank you @sswapnesh 
I did edit the surveys.js and it worked
