### ISSUE TITLE
[11.0] Unable to translate main settings app names

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#20831]
Impacted versions: 11.0

Steps to reproduce:
- Go to settings > general settings in another language than English (I took Dutch since its almost 100% translated)
- The app names are never translated in the settings menu and they are not in the source terms to translate:
![image](https://user-images.githubusercontent.com/6352350/32609893-6d629134-c561-11e7-85bd-5f3efb648d5b.png)

Current behavior: Unable to translate main settings app names

Expected behavior: Able to translate the main settings app names.

**Comment by Yenthe666** [comment]
OPW 781728
@mart-e this is probably for you.

**Comment by nle-odoo** [comment]
Hi Yenthe,

This should be solved with:
https://github.com/odoo/odoo/issues/20831

Translation will be available once the transifex translations are updated.

**Comment by Yenthe666** [comment]
Thanks a lot @nle-odoo - great job!
