### ISSUE TITLE
[BUG] wrong value when inherit from product_id_change to changing price_unit

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#20835]
Impacted versions:
10.0

Steps to reproduce:

inherit from sale.order.line and add this code:
```
@api.multi
@api.onchange('product_id')
def product_id_change():
    res = super(SO, self).product_id_change()
    self.update({'price_unit':5896523})
    return res
```

Go to sale order and do the exact steps:
* add a customer
* add a line and select a product

Current behavior:

price_unit = product.price
Expected behavior:

price_unit = 5896523

**Comment by JonathanNEMRY** [comment]
Any news about this issue?

**Comment by JonathanNEMRY** [comment]
@rco-odoo I think it is due to a problem with the temporary saved values...something about writing two times into the same fields during the loop of the onchange process..do you have any idea how to fix this?Or any other workaround?

**Comment by nim-odoo** [comment]
The price is reset here: https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L925
