### ISSUE TITLE
[BUG] Inventory Adjustments ---Wrong credit or debit value in accounting entry !

### ISSUE THREAD

**Issue by Adasquirrel** [odoo/odoo#20847]
Impacted versions:10.0

Steps to reproduce:
Product Cost :15
On hand: -2000
We create a new Inventory Adjustments (Select products manually) for this product.
Theoretical Quantity :-2000
Real Quantity:0
After we click "validate inventory" button ,system gives a message "Wrong credit or debit value in accounting entry !"..

If we change product cost more than 15, it's OK, no this message pop up ,but if is less than 15 or still 15,this message will pop up .

Current behavior:
Supplier prices will be changed frequently,if the price is less than cost,and on hand is less then zero,
when we make a new Inventory Adjustments ,system will give a message "Wrong credit or debit value in accounting entry !"

Expected behavior:
how to solve it？
Video/Screenshot link (optional):

http://user.qzone.qq.com/44034020/blog/1510299382

**Comment by Yenthe666** [comment]
@jco-odoo this looks like one for you, could you have a look?

**Comment by sle-odoo** [comment]
Hi,
I just tested the same scenario on the runbot and everything worked. Did you find a workaround for this? It could be linked to a rounding issue. Not sure. If you're still facing it, can you try to reproduce it on the runbot?

Regards
