### ISSUE TITLE
[11] delete option in list tree not worked

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#20844]
Impacted versions:
11-ce

Steps to reproduce:

any list view, set `delete="0"` in tree tag

the form view of the same model, set `delete="0" `in form tag

Current behavior:

delete action been removed in from form view, but not been removed from list view.

Expected behavior:

delete atrribute should effect both,

Video/Screenshot link (optional):

in form view, worked 
![image](https://user-images.githubusercontent.com/1404460/32644953-c264edf8-c61f-11e7-9619-a692a186ceb3.png)

in list view,  not workded
![image](https://user-images.githubusercontent.com/1404460/32644982-e350dad6-c61f-11e7-9e68-63295d470dfb.png)

**Comment by jeffery9** [comment]
@mat-e would you like to confirm this issue ?

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thanks a lot for your bug report.
I've just tested this and I can confirm that this is a bug. @mart-e and @xmo-odoo could you guys have a look?

Regards,
Yenthe

**Comment by JanarthananDeveloper** [comment]
@jeffery9  This issue has been fixed from the following commit https://github.com/odoo/odoo/commit/056fe805a1a434644879a3814e03392d36e2bbc5

**Comment by Yenthe666** [comment]
@JanarthananDeveloper thanks a lot for linking this. You're correct, it has been fixed in https://github.com/odoo/odoo/commit/056fe805a1a434644879a3814e03392d36e2bbc5
