### ISSUE TITLE
[REF] Add loading process for load other_module.test_file.yml

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#2084]
In the past, we made a proposal to merge, to run a test of another module. 
This is very practical when you inherit a module and change some features.
But you want to be sure you do not damage the original flow (without having to copy and paste the original yaml again) 

Reported this issue to discuss if it is a good idea to create a new pull request with this change.

https://code.launchpad.net/~vauxoo/openobject-server/7.0-load_test_other_module-dev-moylop260/+merge/187665

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
