### ISSUE TITLE
Swiss VAT IDs are based on VAT rate (that can change), not purpose

### ISSUE THREAD

**Issue by AntoineZen** [odoo/odoo#20858]
**Impacted versions:** All

**Context:**

At the end of this year, the Swiss VAT will change:
 - The Normal tax goes from 8.0% to 7.7%.
 - The Reduced tax goes from 3.8% to 3.7%.

We like to prepare Odoo for deployment inside our company. That will happens in 2018. Thus I am working to prepare the new VAT inside the source code, so when we install the VAT is right from the beginning. 

**Current behavior:**

I've noticed that the different VAT tax are referenced in internal with percentage like `vat_38` or or `vat_80_incl`. I can replace those, for instance, with `vat_37`  or `vat_77_incl` to keep consistent, but if VAT changes again in the future (I think it's very probable) and we change the VAT percentage manually in the GUI, then the IDs will be inconsistent again.

Impacted files are : 
 - `odoo/addons/l10n_ch/data/account_data.xml`
 - `odoo/addons/l10n_ch/data/account_vat2011_data.xml`
 - `odoo/addons/l10n_ch/data/account_fiscal_position_data.xml`
 - and associated .po files in `odoo/addons/l10n_ch/i18n_extra/`

**Expected behavior:**

Would not be better to have the ID named after the **VAT purpose** instead of **rate** ? I propose to change in this way:
- `vat_25` -> `vat_rt`
- `vat_25_incl` -> `vat_rt_incl`
- `vat_38` -> `vat_st`
- `vat_38_incl` -> `vat_st_incl`
- `vat_80` -> `vat_nt`
- `vat_80_incl` -> `vat_nt_incl`
- ...and so one for others IDs.

This way, the label stays consistent event if rate change in the future.

`rt` stand from "Reduced tax" (2.5%), `st` for "Special tax (3.8% -> 3.7%) and `nt` for  "Normal tax" (8%->7.7%).

@nbessi and Frederic Clementi (and @nim-odoo ) : As you worked in the topic in the past, can you give me you opinion ? If you think this make sense, I would be happy to make a pull-request in that sense.

/Antoine

**Comment by Yenthe666** [comment]
@lap-odoo this looks like something you should keep track off for Odoo 12.

**Comment by qdp-odoo** [comment]
it could look like a a good idea, but as we'd need both rates to co-exist for a small period of time (transition time), best would be to not do it.

**Comment by yvaucher** [comment]
@qdp-odoo at some point you probably want to have a vat xmlid with the year when is starts like vat_st_incl_2017
And add two date field start stop on tax object.
Or a sub object in taxes with rate and start stop date fields.

to manage the validity, thus even the bot can go on the new year's eve and it can be planned and be less error prone.

Furthermore, as invoicing is done on delivery, you could create your invoice to a future date before sending them and be sure to use the correct tax.

It would be very useful for e-shops running non stop with thousands of products.

**Comment by fclementic2c** [comment]
@AntoineZen For the record (even if this issue is closed), it is not correct to say : 
'Swiss VAT IDs are based on VAT rate (that can change), not purpose' beacuse in odoo you never change the Vat rate for a tax ; you must create a new taxe with a new rate and archive the old one when possible.
