### ISSUE TITLE
[10.0] not possible to toggle tree columns with search filter context and tree column context

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#20854]
Impacted versions: 10.0 (CE and EE)

Steps to reproduce:
1. open Reqcruitment and change to the list of applications (either on job positions or in debug mode by using the applications menu)
2. use filter "Next Actions"

Current behavior:
The filter is used, but both *_action field columns aren't shown.

Expected behavior:
The filter sets context flags which should toggle the columns to show in the tree view.

tree view column definition:
`<field name="title_action" invisible="context.get('invisible_next_action', True)"/>`

filter definition:
`<filter string="Next Actions" context="{'invisible_next_action':False, 'invisible_next_date':False}" domain="[('date_action','&lt;&gt;',False)]"
help="Filter and view on next actions and date"/>`

Did something happen to that feature? Odoo 11.0 isn't affected for that example, because the activity feature makes it unnecessary. I didn't checked against another example in Odoo 11.0

**Comment by intero-chz** [comment]
@Yenthe666 something unclear here or no idea who to ping? It's not a very big issue, but it's nearly half a year since i've created it.

**Comment by Yenthe666** [comment]
Hi @intero-chz,

Not exactly sure who to ask for this one honestly.
I see you've also mentioned the enterprise having it so I'd suggest you to make an official ticket at odoo.com/help for this one.

Regards,
Yenthe

**Comment by intero-chz** [comment]
@Yenthe666 good point. Thanks

**Comment by intero-chz** [comment]
Ticket 1827968

**Comment by intero-chz** [comment]
Forgot that i've already get some answers:

> Hi, 
> 
> Unfortunately, this feature is not supported by Odoo v10.  
> Since supporting this would require some important changes to the architecture, it won't be changed in an old stable version. 
> 
> It's unclear why this is still in the code, it may have been supported some time in the past, but if it is the case it is now a vestigial line.
> 
> Thank you for your understanding,


and 

> I went to talk with the framework guys, and they told me it may return in v12.
> But they're still unsure because they have a lot of work to do, while trying to make the frontend more stable. 
> Thank you for your feedback!
