### ISSUE TITLE
Install Odoo11 on CentOS7

### ISSUE THREAD

**Issue by TornikeOdikadze** [odoo/odoo#20866]
I just bought new VPS server installed CentOS7 and tried to install [Odoo11](https://www.odoo.com/) on my server.

So I researched some articles and tried following.

    // Install requirement packages
    [root@odoo ~]# yum update -y 
    [root@odoo ~]# yum install epel-release -y 
    [root@odoo ~]# yum install fontconfig libpng libX11 libXext libXrender xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi wkhtmltopdf yum-utils -y 
    
    // Install PostgreSQL
    [root@odoo ~]# yum install postgresql-server -y 
    [root@odoo ~]# postgresql-setup initdb
    [root@odoo ~]# systemctl enable postgresql
    [root@odoo ~]# systemctl start postgresql
    
    // Install Odoo
    [root@odoo ~]# yum-config-manager --add-repo=https://nightly.odoo.com/11.0/nightly/rpm/odoo.repo 
    [root@odoo ~]# yum install odoo -y 

After run last command, I get error.

> ...
> 
> Error: Package: odoo-11.0.post20171110-1.noarch (odoo-nightly)
>            Requires: python3-psutil Error: Package: odoo-11.0.post20171110-1.noarch (odoo-nightly)
>            Requires: python3-requests Error: Package: odoo-11.0.post20171110-1.noarch (odoo-nightly)
>            Requires: python3-greenlet
> 
> ...

How can I fix this?

**Comment by TornikeOdikadze** [comment]
Solved by installing python3 & restart.

**Comment by mugua** [comment]
@TornikeOdikadze , Hi Tornike
Could you help to give a more detail info about "installing python3 & restart".
I test many times, But it still can't run in CentOS 7.
Thanks very much.
