### ISSUE TITLE
After removing custom module menuitem does not disappear

### ISSUE THREAD

**Issue by jelenak** [odoo/odoo#2087]
Hello,

I installed my own odoo module, added link like this : 
<menuitem name="Sutartys" id="base.menu_main_pm" sequence="555" groups="base.group_user"/>

But after module delete, this menu item still there in the menu. So how I can remove this?

Thanks,
Jelena

**Comment by soap** [comment]
I have this problem too. My Odoo is 9.0. Look for response.

**Comment by JayVora-SerpentCS** [comment]
Guys,
The menu disappears for sure!
Probably it would just be a cache!
Does it give a traceback?
Make sure your did not create any actions/values/wizards/menus dynamically.

**Comment by Yenthe666** [comment]
Hi @jelenak,

As @JayVora-SerpentCS said it will dissapear, it is most likely your cache or something that didn't update entirely. To be sure you can do a `-u all` and a hard refresh, you'll notice it'll be gone then.

Regards,
Yenthe
