### ISSUE TITLE
Update Qty on Hand is multicompany stupid due to defaulting to a company specific field

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20889]
Impacted versions: 11.0 it breaks completely, but its existed in various forms in prior versions

Steps to reproduce:
As a single company user, whose company isn't blessed with the location self.env.ref('stock.stock_location_stock') click Update Qty On Hand in the product variants screen

Current behavior:
AccessError

Expected behavior:
Either try/except, do something smarter or really just delete those 2 lines, its not like a default is really needed and in a complex environment (i.e. more than just 1 Stock location, or worse multicompany, just dumb things can happen, like users thinking its the correct location).
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo for you. 😉
