### ISSUE TITLE
Do we really need this self.ensure_one() ?

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#20887]
https://github.com/odoo/odoo/blob/293dd507fa12a76f8f5b47ff09dfc0a897017624/addons/delivery/models/stock_picking.py#L113

 we can process multiple picking if delivery module is not installed. Or if this method is nodified to manage multiple pickings

**Comment by Yenthe666** [comment]
@tde-banana-odoo you wrote a comment saying `# TDE FIXME: should work in batch`. Could you have a look? Can't we remove it?

**Comment by wtaferner** [comment]
@Yenthe666 
Just removing won't work b/c the following are ensured to be one as well, but I guess with a little rewrite it should be possible by looping and calling IMHO.

**Comment by Yenthe666** [comment]
Yeah - it won't work in all cases out of the box but since he's put a comment should work it is worth the effort in my opinion.

**Comment by Yenthe666** [comment]
Friendly reminder @tde-banana-odoo 😄
