### ISSUE TITLE
List view pagination redirecting to 1st page, not redirecting to current page

### ISSUE THREAD

**Issue by georgeppts** [odoo/odoo#20895]
Impacted versions: 10

Steps to reproduce: 

Check in list view which has more than 160 records.

In 1st page it will display 1 to 80 records.

In 2nd page it will display 81 to 160 records.

Now click on records between 81 to 160(2nd page), the record will display in form view.

Now again go back to list view, it display the records as 1 to 80(1st page record) not 81 to 160(2nd page record)

**Scenario:** Now imagine we have 10000 record in one model(res.partner). Currently navigated to 200th page in list view, now clicked on 200th page any record, if we go back to list view, again we need to start from 1st page. It will be little complicated, 

Current behavior: Whenever u go back from form view to list view, it will navigate to first page.

Expected behavior:  It should navigate to current page(Ex. If we click 200th page record, the record will display in form view, if we go back, it should navigate to 200th page)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @georgeppts,

Thank you for your report.
This has been in the case in all Odoo versions though! I believe this was a limitation off the framework.
@ged-odoo or @mart-e could we change this in V11 now that we have a whole new JS engine perhaps? Could you give me feedback? It would be a neat little wishlist item.

Regards,
Yenthe

**Comment by ged-odoo** [comment]
@Yenthe666 @georgeppts 

I consider this as a bug.  The bad news is that is is a low priority bug in odoo 10, and, unless a PR is submitted, is unlikely to be fixed. However, the good news is that it is fixed with the new views in Odoo saas16 (so, released in Odoo 11).

**Comment by Yenthe666** [comment]
Oh hey I didn't know this was fixed in V11. I just tested this in V11 and it is amazing. Good job!

**Comment by georgeppts** [comment]
Thank you guys for your response. 
Now only i too checked with Odoo11. It is working. **Well done guys**.

**Comment by itssubas** [comment]
Hello all! 
Is there any way to fix this issue in Odoo 10?

**Comment by Yenthe666** [comment]
V10 is almost EOL and it's working in V11 and up so it's almost certainly a no. You can backport a fix yourself though.
