### ISSUE TITLE
[BIG BUG] Inventory Accounting is multicompany impossible due to naive shortcut in methods

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20892]
Impacted versions: 11.0

Steps to reproduce:
One Example: You can apply to production, customers, suppliers if you wish, anything that is a 'virtual location'

In a multicompany environment the inventory valuation accounts set on the Inventory Adjustment locations are not property fields.  (btw setting to property fields is not the answer as there are other reasons for company specific virtual locations)
Therefore we need a seperate inventory adjustment location per company.
To do this - you guessed it, we add a company_id to the location.

Now unfortunately, and for no good reason whatsoever, the sole determinant on whether accounting entries are created is the absence of a value in the company_id field on either the source or destination location

There are lots of important reasons for all the virtual location types to have a company set, but with these two methods _is_in and _is_out it isn't going to work.  

@jco-odoo 
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
@gdgellatly We are working on a bunch of fixes for the valuation in [this branch](https://github.com/odoo-dev/odoo/tree/11.0-valuation-sle) and we plan to
- remove the company_id check
- raise if any of the stock move lines move something directly from a company to another one

The company_id is not even used in the condition that updates the value/remaining value/ remaining qty fields on the stock move, so it indeed does not make sense to implement it in the account entry creation condition.

Please confirm me your use case:

- you have two companies
- you want to set different accounts for the inventory loss on these two differents companies
- the only way to do it is to set a company_id to the inventory loss location
- if you set a company_id, no accounting entries are created but the valuation (on the moves) is updated

**Comment by sle-odoo** [comment]
I forgot to add, if we raise if a move goes directly from a company to another, the `_is_in` and `_is_out` methods will work. Please note that they are fine-tuned in the branch i linked to take into consideration the moves lines...

**Comment by gdgellatly** [comment]
The main use cases are pretty straight forward and your description is correct.

Doing an Inventory Adjustment in multicompany and having the adjustments post to the correct P&L account.
To do so you must have multiple Inventory Gain/Loss accounts, ergo, company_id set on multiple Inventory Adjustment Locations

Consuming items in Manufacturing, typically goods go to WIP Inventory on consumption (raw moves), and reverse on production (finished moves) so again we need to set an account on the production location, ergo, company_id must be set and multiple Production locations.

I'll check that branch closer later today, but I would say that for tests, setting accounts and companies on the test locations would be a good idea, or running them effectively twice, if company_id is going to be a relied on field.

**Comment by sle-odoo** [comment]
@gdgellatly I just tested this scenario in my branch and it worked, the accounting entries are posted in the right account. The valuation report is broken probably due to this [domain](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/product.py#L157) though.

**Comment by gdgellatly** [comment]
OK I review some code here, not all related to this bug. @sle-odoo 

https://github.com/odoo/odoo/compare/11.0...odoo-dev:11.0-valuation-sle#diff-ff8b11b98cea4f7451b225e1e21f0b9eR51

I get the use case here, but if the product has been changed is returning 0.0 the right thing to do?  In fact that is a more general question beyond just valuation.  I have received goods different to what I ordered, say a different variant colour, and I've decided to keep them what should Odoo do in that scenario?  But its no big deal for me, we have to replace this entire method anyway, to take account of rebates and other additions and deductions that must occur at incoming shipment so we've already solved according to what we think is right.

I actually have a little module, which because often times the price isn't known at purchase time, that it refuses to process the incoming shipment until the user indicates the purchase pricing is correct.  

https://github.com/odoo/odoo/compare/11.0...odoo-dev:11.0-valuation-sle#diff-ff8b11b98cea4f7451b225e1e21f0b9eR51

OK I see this is fixed for the is_in and is_out case.  I would consider a second function called def should_not_be_valued which just returns not(should_be_valued).  It will make the subsequent in and out code much more functional to read.

The rest all looks good.  It defintely should resolve all my cases of this bug.

**Comment by sle-odoo** [comment]
@gdgellatly Thanks for your time. I think the diff you linked are not working. If i get it right, you first linked to [this commit](https://github.com/odoo-dev/odoo/commit/a5a67276d75a5cd87e8e4c4c02394e7465dfa233). Essentially its goal is to use the standard price instead of the purchase order line on the stock moves created when confirming a stock move for a kit. AFAIK this usecase never worked the right way in Odoo. We would need to define somewhere which part of the cost the components should get from the price of the whole kit.

**Comment by sle-odoo** [comment]
@gdgellatly 
The branch i linked is now merged in [11.0](79821458facfdddc0087a5e85aadceb585dd8b04), so this particular bug should now be fixed. Feel free to report here if it's not the case.

Thank you for the detailed bug report.
Simon
