### ISSUE TITLE
[10.0][typo][tutorial]

### ISSUE THREAD

**Issue by m3dbedb** [odoo/odoo#20902]
Impacted versions:10.0

Steps to reproduce: make a module with suggested code

Current behavior: tutorial code doesn't work

Expected behavior: module installation should pass

Video/Screenshot link (optional):

![typo](https://user-images.githubusercontent.com/25632818/32730446-2e9e1772-c898-11e7-8dad-41287483b1b8.PNG)

After removing the comma tutorial works:
`state = fields.Selection([`
`        ('draft', "Draft"),`
`        ('confirmed', "Confirmed"),`
`        ('done', "Done"), #remove last comma`
`    ], default='draft')`

**Comment by xmo-odoo** [comment]
Erm… what? Python has allowed trailing commas in collection literals (and function arguments) pretty much forever. It's certainly supported on
