### ISSUE TITLE
Issue in wrong reference being assigned when Validating Picking

### ISSUE THREAD

**Issue by JADCO5692** [odoo/odoo#20913]
Hi Team,

I was testing and created a Picking for Goods Return, however, when I did that, following error was created:
![image](https://user-images.githubusercontent.com/5710396/32747248-2f22e1f0-c8de-11e7-817a-17e238e928b3.png)

I checked and found that in the code instead of account.move, stock.move object was referenced.
![image](https://user-images.githubusercontent.com/5710396/32747171-e9a88832-c8dd-11e7-8c35-cd184c92cbfe.png)

Please advice.

Regards

**Comment by Yenthe666** [comment]
@jco-odoo and @sle-odoo looks like on for you to check. I believe we're talking about V10 at https://github.com/odoo/odoo/blob/13d2b29f0151a9f607df96246104f30bb49cae86/addons/stock_account/models/stock.py#L74

**Comment by JADCO5692** [comment]
Yes, it is Odoo v10

**Comment by JADCO5692** [comment]
Any update on this.?
