### ISSUE TITLE
PY3/V11 String Decoding : AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jam-odoo** [odoo/odoo#20912]
Importable module with **static files** when running Odoo v11.0 with **python3** runs into following error 

Traceback (most recent call last):
  File "/home/odoo/code/odoo/addons/base_import_module/models/ir_module.py", line 126, in import_zipfile
    self._import_module(mod_name, path, force=force)
  File "/home/odoo/code/odoo/addons/base_import_module/models/ir_module.py", line 82, in _import_module
    url_path = url_path.decode(sys.getfilesystemencoding())
AttributeError: 'str' object has no attribute 'decode'

With Python3 Odoo code is trying to decode an object that is already decoded at https://github.com/odoo/odoo/blob/11.0/addons/base_import_module/models/ir_module.py#L82. 
[Line 82 in import module](https://github.com/odoo/odoo/blob/11.0/addons/base_import_module/models/ir_module.py#L82) will have a `str`, there is no need to decode from file system encoding anymore.

Thank You

**Comment by Yenthe666** [comment]
@xmo-odoo this looks like another `P3` migration issue for you. 😉

**Comment by jam-odoo** [comment]
@xmo-odoo I understand that  you must be overloaded with work but this is blocking for PS Teams as we can not upload module with static files and we have few pending deliveries of apps for customer because of this. Can you please look  into this ?

**Comment by jam-odoo** [comment]
@nim-odoo Thanks, for expediting this (cheers).
