### ISSUE TITLE
[10.0] Odoo not taking timezone into consideration

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#20914]
Impacted versions:
v10

Steps to reproduce:
1. Set timezone to an user. 
2. Create any document (quotation, invoice, picking...) 

Current behavior:
As soon as the document is created it says it was created four (4) hours ago. We believe that this is because it is taking UTC and we're in a -04:00 timezone. 

Expected behavior:
Have the correct time when the document was created.

Video/Screenshot link (optional):
https://youtu.be/O_esG5_3NdY

**Comment by Yenthe666** [comment]
Hi @edsersolis,

Thanks for the report!
On which timezone did you set your Odoo? I tried with canadian (which is -4) and it seems to work fine:
![image](https://user-images.githubusercontent.com/6352350/32767880-aaff6e88-c915-11e7-94a1-14635998f723.png)
Can you reproduce it on the latest Odoo 10 runbot too?

Regards,
Yenthe

**Comment by edsersolis** [comment]
Hello @Yenthe666 

Could you please confirm to what timezone do you have set the server to? We have it set to America/Santo_Domingo, however changing the timezone in Odoo does not affect at all, it always says 4 hours ago.

We believe that what Odoo is considering the -04:00 as UTC and to that deducting the 4 hours.

Last night I tried changing the postgresql to UTC, it worked for a while and then back to the same issue. Just a minute ago I changed the server's time to UTC, it's working again but let's see if it won't go back to the same behavior.

**Comment by Yenthe666** [comment]
Hmm,

Just tested this on V10 community in the timezone America/Santo_Domingo and it works fine there too:
![image](https://user-images.githubusercontent.com/6352350/32823945-3caf4514-c9df-11e7-87dd-d70e16417824.png)
Have you tried updating your Odoo to the latest update? Can you reproduce it on a runbot?
@mart-e do you happen to have any other clues?

**Comment by mart-e** [comment]
In #15867 there was a bug reported on Windows not handling well the timezones.
Could you detail how you have installed Odoo? On Windows or Linux? Sources or package?
You could reproduce only when your server was in your local timezone?

**Comment by Yenthe666** [comment]
@edsersolis could you answer the question from Martin please? Otherwise we can't help really.

**Comment by edsersolis** [comment]
Hello sorry for the delayed answer. We're using Linux and Sources.

Haven't been able to find out what is causing this because some instances in the very same server do have the issues others don't. Seem to be related to some module but haven't been able to identify which one. We're further checking and we find it to be an issue related to Odoo will reopen this ticket.

Thanks!

**Comment by Yenthe666** [comment]
Awesome. Thanks for the feedback!
