### ISSUE TITLE
new option in module management

### ISSUE THREAD

**Issue by amiryousefi** [odoo/odoo#2092]
to enable clearing all module data without uninstalling it, add an option like upgrade and update to modules form.
after i test any new module or my own under development one, i wish to clear all data but if i reinstall the module i lost customization in views or  access rules i set.

**Comment by Yenthe666** [comment]
Hi @amiryousefi,

This is not something that'll be added in Odoo.
I don't really see the problem either. You either drop the database through the database manager (pgadmin) or you delete and install the module again to clear the data.
If you miss customizations it means you didn't add them by code, so you should then.

Regards,
Yenthe
