### ISSUE TITLE
Financial Reports Configuration form no option to set Report Value

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#2093]
In V7 there is an option to set report value if it set report type = Report Value, but in V8 there is no option below to set the value.
In detail investigation its hided in V8, is there any reason for it or by mistake it happened ?

In V7 - no attribute to hide
  <---notebook>
  <--/---notebook>
In V8 - attribute to hide
   <---notebook attrs="{'invisible': [('type','not in',['accounts','account_type'])]}">
   <--/--notebook>

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
