### ISSUE TITLE
[v11] Variant Pricing (price_extra) not used in Point of Sale instead Sale Price (list_price) is used

### ISSUE THREAD

**Issue by bradrust** [odoo/odoo#20939]
Impacted versions:

11.0 community and 11.0 odoo online (via trial instance)

Steps to reproduce:

* Login with user that has ability to run a Point of Sale session.
* create a Variant (i.e., "size")
* create two Variant values for "size" (i.e., "small" and "large")
* create new new Product
* set Sale Price (list_price) to 1.00
* add "size" variant to the new Product and save
* edit "Variant Pricing" and assign non-zero values to the "Extra" (price_extra) fields and save
* start a Point of Sale session
* observe the two variant instances (product.product) with price values of 1.00 which is encapsulated in the span for class "price-tag"

Current behavior:

* Point of Sale item instances are showing Sale Price instead of (Sale Price + Variant Price Extra) ... which appears to be the logic used in v10.0 

Expected behavior:

* Point of Sale item instances should have price computed to include Variant Price Extra.

Development Notes:

* I noticed this when trying to upgrade my module from v10 to v11.  
* I have a model which extends Product.Product and I override the method price_compute(self, price_type, uom=False, currency=False, company=False)
* In v10.0, the Point of Sale bootstrapping or reading of Product.Product would call this price_compute method which is where I do my list_price modifications.   
* in v11.0, I never see price_compute called at any point during Product template or product modifications, variant changes, POS session starting, etc...

**Comment by jorenvo** [comment]
Thanks for the report, this has been fixed last week in v11 with b4debf7e1b19710ef3dcc39448d08a698b5657b0.

**Comment by Yenthe666** [comment]
Also labeling this for reporting / filtering later on. Good job Joren!
