### ISSUE TITLE
Cannot chat on read-only  forms

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#2094]
oe_chatter is not shown if form cannot be edited.
When view is created as follows:

<pre>
...
field name='arch' type='xml'
                form edit='false' create="false" string='cdr'
..
</pre>

For example, to discuss a call recording that is not editable and created from pbx.

Here is the solution :-)

<pre>
diff --git a/addons/mail/static/src/js/mail.js b/addons/mail/static/src/js/mail.js
index b3fb0da..da22b05 100644
--- a/addons/mail/static/src/js/mail.js
+++ b/addons/mail/static/src/js/mail.js
@@ -1786,6 +1786,7 @@ openerp.mail = function (session) {
             if (!this.ParentViewManager.is_action_enabled('edit')) {
                 this.node.params.show_link = false;
             }
+           
         },
 
         start: function () {
@@ -1809,7 +1810,7 @@ openerp.mail = function (session) {
 
             this.node.params = _.extend(this.node.params, {
                 'message_ids': this.get_value(),
-                'show_compose_message': this.view.is_action_enabled('edit'),
+                'show_compose_message': true, //this.view.is_action_enabled('edit'),
             });
             this.node.context = {
                 'mail_read_set_read': true,  // set messages as read in Chatter
</pre>

**Comment by Yenthe666** [comment]
Hi @litnimax ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
