### ISSUE TITLE
[10.0] issue with internal stock movements and sub locations

### ISSUE THREAD

**Issue by matt-willdooit** [odoo/odoo#20944]
Impacted versions: 10.0

Steps to reproduce:
In Inventory Settings - Enable [Manage only 1 Warehouse, composed by several stock locations]
Create 2 locations which are both children of WH/Stock (e.g. Shelf_1 and Shelf_2)
Create a new product.
Receipt 50 into WH/Stock
Perform an internal transfer to move 25 from WH/Stock to WH/Stock/Shelf_1
Attempt to perform another internal transfer to move the remaining 25 from WH/Stock to WH/Stock/Shelf_2 - When you press reserve it will incorrectly reserve the stock in WH/Stock/Shelf_1 instead of WH/Stock.

Current behavior: When performing an Internal Transfer, the reserve button reserves stock from a sub location even though there is stock available in the selected source location.

Expected behavior: The stock should be reserved from the source location.

Video/Screenshot link (optional):

**Comment by jco-odoo** [comment]
As the 25 in Stock and the 25 in Shelf_1 were received at the same date, the FIFO removal strategy can choose either of them.  The locations on the moves function as a zone where the products can be reserved.
