### ISSUE TITLE
[odoo11] create new account in odoo . get an internal server error when user enter password and confirm password is not same

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#20941]
Impacted versions: Odoo 11

Steps to reproduce:
Go to settings - > General settings -> Enabale B2C (Free signup) under customer Account - > Save
go to login page of odoo
click on dont have an account?
then fillup the signup form and  enter password and confirm password are diffrent 

Current behavior:
**500: Internal Server Error**

Expected behavior:
display the message "password and confirm password is not same,please retype theme"

Video/Screenshot link (optional):
**https://drive.google.com/open?id=1EDh9jGSd1ImEPCMQ24IyZHiYzTf80Wmu**

Please correct me, if i am wrong
Thank You

**Comment by rohitramnani1994** [comment]
@Yenthe666 can you please review it
Thank you

**Comment by Yenthe666** [comment]
Hi @rohitramnani1994,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 11 and I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/32893477-eb0649aa-cad9-11e7-9c2e-b9755ea48ef7.png)

@JKE-be can you have a look please?

Regards,
Yenthe

**Comment by JKE-be** [comment]
@Yenthe666 not really website but fixed ^^
