### ISSUE TITLE
Minor, next release fix, unusual/incorrect view id name in mrp - just FYI

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20952]
Impacted versions: 11.0

Steps to reproduce:
In mrp there is view called
`mrp_production_workcenter_form_view_inherit`

however it is for workorders, not workcenters.  Its also not an inheriting view, but the primary one.  

Its not used anywhere else so not causing issues.  Just confusing is all.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
I just noticed, same deal for tree and search

**Comment by pimodoo** [comment]
Hello, thank you for your feedback.
We have just created a task to fix it in master, and we'll keep you up to date through this issue when it will be merged. I just close this issue to have a better overview of the remaining ones.

Thank you.

**Comment by pimodoo** [comment]
Hello @gdgellatly , your feedback has been applied in commits:
- https://github.com/odoo/odoo/commit/f483d6cc87b0e3e35bd23abd41af444c98df8812
- https://github.com/odoo/enterprise/commit/9625b690c0507d59e4e57fcfaa089339db423e34

Thanks
