### ISSUE TITLE
IE9 Javascript Qweb Support

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#20963]
Impacted versions:
10, 11

Steps to reproduce:
Use IE9(or IE11 with document mode set to IE9) to browse version 10 or 11 website on runbot

Current behavior:
https://github.com/odoo/odoo/blob/4e32a23d969d6ba1b54836bfc09be1eb6ee4f3c0/addons/web/static/lib/qweb/qweb2.js#L314

In this line, doc is a msxml object in IE9. And this object does not have method querySelectorAll, making javscript qweb template not working.

Related Info: https://blogs.msdn.microsoft.com/ie/2012/07/19/xmlhttprequest-responsexml-in-ie10-release-preview/

-----

https://github.com/odoo/odoo/blob/4e32a23d969d6ba1b54836bfc09be1eb6ee4f3c0/addons/web_tour/static/src/js/tour_service.js#L70

IE9 and IE10 do not have MutationObserver API. It will not work without polyfill.

**Comment by Yenthe666** [comment]
@nim-odoo and @ged-odoo I know we don't really like IE but perhaps we should have a look at this?

**Comment by Yenthe666** [comment]
@ged-odoo any update? 😊

**Comment by Yenthe666** [comment]
@qsm-odoo could you have a look?😉

**Comment by Yenthe666** [comment]
@qsm-odoo or @ged-odoo could you give an update please?

**Comment by ged-odoo** [comment]
Hey @Gorash could you have a look at the qweb thing?

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by Yenthe666** [comment]
It probably is but I don't know if we should keep it open any longer. No comments in 1.5 year, Odoo 10 is EOL so only 11 remains and IE is not really adviced anyways.

**Comment by pedrobaeza** [comment]
OK, then let's take the risk of closing. It can be reopened if needed.
