### ISSUE TITLE
Bank statment import

### ISSUE THREAD

**Issue by aspcsharp9** [odoo/odoo#20975]
Impacted versions: odoo 9

Steps to reproduce: 

Current behavior:

Expected behavior: I need help about bank statment import in odoo 9. Where can find simple template of any bank statment?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @aspcsharp9,

Please do ask questions about functionalities on the official help forums (help.odoo.com) or have a look at the documentation (at https://www.odoo.com/page/docs).
You can usually download statements from your bank.

Regards,
Yenthe
