### ISSUE TITLE
CRM deduplicate contacts major bug

### ISSUE THREAD

**Issue by maxcmoi89** [odoo/odoo#2097]
The deduplicate contacts tool in the CRM is bugged. When you decide to merge two customers with the same name (they are actually the same company but the salesman inserted them wrongly) you cannot. You get the following error message: 

"Constraint Error

Error, a partner cannot follow twice the same object."

A work arround is to unfollow one of the duplicate and then merge them. Then there are no problems. 

The problems is due to both customers being followed by the same user and when you merge the customers together their followers gets appended to the new customer. Thus there is an error because he tries to append user1 to mergedcustomer twice, which brings the error message up.

**Comment by Yenthe666** [comment]
Hi @maxcmoi89,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
