### ISSUE TITLE
[9.0] Duplicated customer reference on invoice when creating from sale order

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#20985]
If the Customer Reference on the sale order has commas, the invoice Reference/Description gets duplicated for each invoice line

The duplication happens on addons/sale/sale.py:329

Impacted versions: 9.0

Steps to reproduce:

- On a sale order, set a customer reference with a comma (ex: Pedido de Compra Nº 55011690, de 30.10.2017)
- Create a invoice from the SO (any option can be selected)

Current behavior:
- Reference/Description on the invoice gets duplicated per line (5 sale order lines, 5 time duplicated)

Expected behavior:
- Reference/Description on the invoice doesn't get duplicated

Screenshot:
![so](https://user-images.githubusercontent.com/8062666/32854303-1b4da530-ca36-11e7-8c61-067ebe4e1eaa.png)
![ft](https://user-images.githubusercontent.com/8062666/32854302-1b26a4bc-ca36-11e7-82a4-26a47e547b14.png)

**Comment by Yenthe666** [comment]
Hi @hmrodrigues,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
