### ISSUE TITLE
[10.0e] TaxCloud module shows sales tax on down payments

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#20986]
**Impacted versions:** 10.0e (TaxCloud module)

**Steps to reproduce:**
1. Configure TaxCloud
1. Create a sales order with appropriate fiscal position
1. Click create invoice
1. Choose Down Payment (fixed amount) and specify some fraction of the total
1. Validate the invoice

**Current behavior:**
The down payment invoice shows sales tax, but the sales tax doesn't add to the amount due.  It's confusing.

**Expected behavior:**
There should be no sales tax on down payment.

![image](https://user-images.githubusercontent.com/7604932/32863854-2cee8f28-ca1a-11e7-8043-b10511aea9ff.png)

**Comment by matt454357** [comment]
In issue #17703, @taxcloud explains that "Terms of payment are not tax-related, and should not be sent to TaxCloud."  But, there is no way to prevent this product from being sent.

The final invoice calculates sales tax correctly:
![image](https://user-images.githubusercontent.com/7604932/32864709-6e4a0e86-ca1d-11e7-8e60-5f71bc08b44b.png)

**Comment by Yenthe666** [comment]
@tivisse another taxcloud related issue - might be of interest for you.

**Comment by vcloud9ray** [comment]
Workaround: Set Deposit Invoices to Fiscal Position Tax Exempt?  Find a TIC code that means 'exempt' ?

**Comment by tivisse** [comment]
Hello everyone :)

This commit from yesterday should fix your issue I think. https://github.com/odoo/enterprise/commit/4c9d86693738a55bdc1942713485d30130b24a63

The tax rates won't be computed if either the line quantity or the unit price is negative. 

Have a nice day,

Yannick.

**Comment by vcloud9ray** [comment]
@tivisse - thanks for this fix, which will help.  The deposit Invoice however has a positive amount and positive quantity.

**Comment by tivisse** [comment]
Hi @vcloud9ray 

I reopen this issue to discuss about a clean solution. ;)

**Comment by tivisse** [comment]
Just a question that could be easy if you live in the US.

Is there a kind of a 'Tax Free' TIC category ?

If it's the case, the Down Payment product is configured on the sales settings. By setting this TIC category on the down payment product, the taxes won't be computed in the future. That could be a clean workaround.

**Comment by vcloud9ray** [comment]
@tvisse - a good idea, but I think it DEPENDS on the Sales Tax jurisdiction:

http://www.boe.ca.gov/lawguides/business/current/btlg/vol2/suta/315-0370.html - "Tax paid with respect to the core deposit should not be refunded or credited to the customer."

**Comment by matt454357** [comment]
If I understand my comptroller, we don't need to collect sales tax on down payments.  Down payments are held in deferred revenue.  If the sale is canceled, and the down payment is NOT refunded, then we post a portion of the down payment as sales tax liability and recognize the remainder as revenue.

If we were required to collect sales tax on down payments, then Odoo would need to avoid double charging the sales tax.  Currently, Odoo applies the sales tax on the down payment invoice, and then applies sales tax again to the total price on the final invoice.  In other words, we are double charging sales tax on some portion of the total sale.

@vcloud9ray - The California document is referring to "EXCHANGES OF USED FOR RECONDITIONED [or new] PROPERTY."  That's different from my current situation, but very interesting.

@tivisse - I read the TIC descriptions, and tried the few that I thought might work, but they were all taxed. For example,  I tried the following:

> Taxability Information Code: 10040
> --
> Charges by the seller for any services necessary to complete the sale (other than delivery).  This means any charges separately contracted for or separately stated  on the invoice or similar document, and the amount is not the sales  price.

> Taxability Information Code: 11110
> --
> Seller State Responsible is a very special category of state and local taxes on a retail sale that are imposed on the seller  if the state statute authorizing or imposing the tax provides that the  seller may, but is not required, to collect such tax from the consumer.  The tax must be separately stated on the invoice, bill of sale or  similar document given to the purchaser.
> 
> IMPORTANT: Do not  use this TIC unless you are absolutely confident (as advised by your tax  counsel) that this is the proper TIC for your sales activity.

**Comment by taxcloud** [comment]
In tax terms, a down payment is referred to as a "stored value instrument" (like a gift card or gift certificate).

You may want to try TIC 10005 ([https://taxcloud.net/tic/](https://taxcloud.net/tic/) --> Administrative --> Gift Card)

> Gift certificates are treated like cash. No sales tax is collected at the time the certificate is purchased. When a customer presents a gift certificate, the customer receives a credit against the total cost of the purchase and pays the difference, if any. The sales tax applies to the total amount of the purchase, not the amount due after the certificate is deducted.

Please let us know if you have any other questions!

Thank you.

**Comment by vcloud9ray** [comment]
@tvisse - looks like we have the 'tax free' product setting!!

**Comment by taxcloud** [comment]
**Please do not use any TICs to fraudulently attract pre-determined (or preferred) tax results.**

TICs define product categories, not tax treatment.

Merchants using our APIs should assign TICs based upon the description provided that most accurately reflects the item being sold. TaxCloud keeps track of where each TIC is exempt, and these rules are constantly monitored and updated as laws change.

**Comment by vcloud9ray** [comment]
@taxcloud - understood.  Another way to word my comment is "we can resolve this with product configuration (setting), rather than via code"

**Comment by tivisse** [comment]
Thanks @vcloud9ray @taxcloud and @matt454357 for your participation to the discussion. 

I will summarize the issue and the solution.

Issue: When calling taxcloud on the sales order and invoices validation, Odoo sets the tax rates for all the lines with a positive quantity and price unit. This includes the down payments and excludes the discount lines. However in tax terms, a down payment is referred to as a "stored value instrument" and is not subject to taxes.

Solution: As a down payment could be assimilated to a gift certificate that is treated like cash, no sales tax is collected at the time the certificate is purchased. We can in that case set the TIC 10005 (Administrative --> Gift Card) for the product is that is used by default for down payments. This could be configured in a few clicks in the sales settings on the Odoo configuration.

If this seems correct for every one, I'm gonna cancel this issue as the workaround is valid. 

Don't hesitate to come back to me for every question / feedback / comment.

Have a nice day,

Yannick.
