### ISSUE TITLE
Users are not allowed to remember their accounts and passwords when landing 

### ISSUE THREAD

**Issue by lonelyleaves** [odoo/odoo#20983]
Odoo is a b/s architecture, odoo is now through the browser to be use, I hope you can set does not allow the user to remember username and password when landing, although the browser can settings, but users can also modify the remember password, for security, odoo is the best platform directly is not allowed

**Comment by Yenthe666** [comment]
Hi @lonelyleaves,

Thank you for your bug report.
This is however desired behaviour and it is built in as an option in the browse. So, not a bug.

Regards,
Yenthe
