### ISSUE TITLE
POS uses the same picking_type_id for both in and out moves

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#20982]
Impacted versions:
at least 9.0

Steps to reproduce:
sell a product in POS
Get back a product in POS

Current behavior:
The in and out move have the SAME picking_type_id

Expected behavior:
The in and out must have a different picking type id.

**Comment by jco-odoo** [comment]
Picking types are a grouping of pickings for practicality and we did not see the practicality here to split for returns as there is already one for the pos.  (e.g. there default source and destination locations on them, but you can use other)
