### ISSUE TITLE
POS session can be closed while active, and you can sale after closed the session

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#20980]
Impacted versions:
at least 9.0

Steps to reproduce:
start a POS session
in a new window close this session
sell  products in the other window

Current behavior:
You can close a POS session while activly using that causing:
products sold after closing the POS session, creates stock movements without  picking_id or picking_type_id

Expected behavior:
POS prevents the sales when its session are closed

**Comment by Yenthe666** [comment]
Hi @Gyuri77,

Thank you for your report.
However, I wouldn't really call this a bug. When you're using multiple tabs in a browser and then close the POS in one tab, how should we detect it is closed? The POS can work offline and does no communication with the backend whatsoever. So, what would you ever expect to happen? There can't be a check to the database as it can work offline plus you've closed it yourself in another tab.
I honestly don't call this a bug but the final call is for @mart-e 

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Still using a pos session while closing it on another screen is not something I expect to end well.
However, as it still seems to happen from time to time, we try to mitigate that by creating what we call a rescue session.

![screenshot-2017-11-16 sessions - odoo](https://user-images.githubusercontent.com/564822/32896817-54b01584-cae4-11e7-895c-292cd0760121.png)

This way, the orders you are creating while your session is closed are not lost.
Obviously, you need to close that session as well to get the right entries.

**Comment by Gyuri77** [comment]
Thank you for your answers.
 I checked again, and in our pilot, the users are created  rescue session yet,  so i hope it will  be good.
