### ISSUE TITLE
Manufacturing routing modification in V11 CE not working

### ISSUE THREAD

**Issue by kunalg140** [odoo/odoo#21001]
Impacted versions:11 CE

Steps to reproduce:
The manufacturing routing was modified to make a QC location between production finished products and stock  
step1 :  Production Location -> QC location (When MO is completed)
step2:  QC Location -> Stock  (Manual after QC checking)

Current behavior:
The above steps work when MO is created manually, however if a MO is generated  from an SO or through the scheduler the moves are always "Production Location -> Stock"

Expected behavior:
The moves should be same in both cases. 

I was wondering whether the Production Output Location is hard coded to Stock in the Procurement module or I am overlooking some point .

Video/Screenshot link (optional):

**Comment by lap-odoo** [comment]
@kunalg140 Hi, how did you configure it ? 

Here is what I suggest you to do  : 
- Create a WH/Quality location
- Modify the manufacturing operation type : the default destination location should be WH/quality
- Modify the manufacture procurement rule : the procurement location should be WH/quality
- Create a new route : with a push rule from Quality to Stock and a procurement rule from Quality to Stock
- Make sure to apply this new route to your product

I've just tested in on runbot V11 and it works when I create the MO manually but also when the MO is created automatically. 

I'm closing the issue. If this doesn't solve your problem, do not hesitate to answer, it'll be reopened if necessary.
