### ISSUE TITLE
Odoo live chat online working error

### ISSUE THREAD

**Issue by habin201291** [odoo/odoo#21027]
Hey, I have created live chat channel and intergating your code into my website, but i have got an error below when i clicked to the "Have Question?...." label.
![image](https://user-images.githubusercontent.com/4486666/32940790-473673e4-cbb6-11e7-9642-f750850dfef8.png)

And here is the same error when i link to https://demo32.odoo.com/im_livechat/support/4
![image](https://user-images.githubusercontent.com/4486666/32940849-79c42892-cbb6-11e7-98da-6e822aa21480.png)

**Comment by Yenthe666** [comment]
Hi @habin201291,

Thank you for your bug report.
Could you please try to update your whole Odoo and try again? Do you have custom development in this environment?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no addition feedback/answer on my questions in a few months.

Regards,
Yenthe
