### ISSUE TITLE
Odoo 10 unable print pdf

### ISSUE THREAD

**Issue by lucian0112** [odoo/odoo#21026]
Impacted versions: 10

Steps to reproduce:
1 - Generate an invoice
2 - Print it
3 - Open pdf file

Current behavior:
Pdf is generated but is empty and cannot be open with adobe reader. Get Failed to load PDF document

Expected behavior:
Get a valid PDF file

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @lucian0112,

Thank you for your report.
However, printing reports has worked for years in Odoo and when testing it with the very last Odoo 10 it still works:
![image](https://user-images.githubusercontent.com/6352350/32939271-48e53a90-cb7f-11e7-91bf-9736556e5b80.png)
I believe there is an issue with your local installation and most likely with your wkhtmltopdf or PDF reader.
Can you reproduce the issue on runbot.odoo.com with a demo instance?

Regards,
Yenthe

**Comment by lucian0112** [comment]
Hi @Yenthe666 
You are right. I try to reproduce on runbot and was working. I reinstalled wkhtmltopdf  and now is working for me also
Thanks a lot

**Comment by Yenthe666** [comment]
You're welcome - best of luck!
