### ISSUE TITLE
[11.0] User Autocomplete of New Message does not display

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#21031]
Impacted versions:
11.0

Steps to reproduce:
1. New Message
2. Type any name of existing users

Current behavior:
Nothing is shown up, yet using up and down arrow-keys can still select the users.

Expected behavior:
Suggested users are shown below the input field.

Screenshot:
![image](https://user-images.githubusercontent.com/27185427/32943030-cd05b50c-cbc5-11e7-849f-616a011a0620.png)

**Comment by Yenthe666** [comment]
Hi @TimLai125,

Thank you for your report but I'm missing quite some context/screenshots/details though.
Are you talking about this? Because it works fine on the latest Odoo 11:
![image](https://user-images.githubusercontent.com/6352350/32942890-a8ad83fa-cb8a-11e7-893d-3bf6e5964f15.png)

**Comment by TimLai125** [comment]
@Yenthe666 

Sorry about the confusion, here is the screenshot 
![image](https://user-images.githubusercontent.com/27185427/32943008-b3cd4a96-cbc5-11e7-9465-29296b509732.png)

**Comment by Yenthe666** [comment]
Okay that makes more sense. You're talking about the chat when you'd like to make a new chat.
It indeed doesn't suggest users anymore. @mart-e not sure who to ping for this.

**Comment by mart-e** [comment]
@qsm-odoo could you check?

**Comment by Yenthe666** [comment]
Hey all,

This seems to have been fixed in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/34601311-a5b61710-f1fb-11e7-9cca-d0225e284cb6.png)
Please update your Odoo @TimLai125 and it'll be fixed.

Regards,
Yenthe

**Comment by TimLai125** [comment]
@Yenthe666 Thank for the update. I have checked and confirmed the fix

**Comment by qsm-odoo** [comment]
Sorry I forgot to reply here, it was indeed fixed a month ago with https://github.com/odoo/odoo/commit/41d2470093a5e18ecebc86f2f878813f1879462d

**Comment by Yenthe666** [comment]
Thanks for linking the right commit.
