### ISSUE TITLE
[11] new field in group get no label

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21033]
Impacted versions: 11

Steps to reproduce: 

```
class TomResPartner(models.Model):
    _inherit = 'res.partner'

    fax = fields.Char(string='Fax')
```
```
<record id="tom_view_partner_form" model="ir.ui.view">
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="name">res.partner.view</field>
            <field name="model">res.partner</field>
            <field name="arch" type="xml">
                <field name="phone" position="after">
                    <field name="fax"/>
                </field>
            </field>
        </record>
```
Current behavior:
The field will inserted directly behind field phone, but without label.
Expected behavior:
The field should get an auto label and should be inserted into next row under phone, cause phone is in group/group.

regards,
Karsten

**Comment by mge-odoo** [comment]
Hi @Karsten-77 

This doesn't seem to be an issue.
It is linked to another inherited view (see https://github.com/odoo/odoo/blob/11.0/addons/sms/views/res_partner_views.xml#L11 )

The field phone is replaced and put in a `<div class="o_row"/>`

Regards,

Martin
