### ISSUE TITLE
Probably easiest to reproduce bug ever - Quotations != Everything

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21030]
Impacted versions: 11.0

Steps to reproduce:
- Go to Runbot
- Click Sales
By default this is the quotations screen, if per chance it isn't
- Click Quotations

Current behavior:
Shows all Sale Orders

Expected behavior:
Shows only Quotations

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/32942007-8c06a3dc-cbec-11e7-8511-4db0231d0f5a.png)

kind of related #20615 probably worth fixing both at same time

**Comment by gdgellatly** [comment]
Hmmm,

There is another bug with the sale actions which will break if we fix this.

![image](https://user-images.githubusercontent.com/5093264/32942938-6113e5b0-cbef-11e7-85dc-914727ace8c5.png)

This is the action for sales.  See how the 'cancel' is included in the domain.  So how can one ever see cancelled Sales Orders.  The cancel part probably needs to be in context.

**Comment by Yenthe666** [comment]
Yep - indeed. @mart-e or @nim-odoo could one of you have a look? 😉

**Comment by nim-odoo** [comment]
Introduced by the maestro himself at https://github.com/odoo/odoo/commit/f972b60dc248fe3d54c6e92542d9967de565a31f#diff-0a7015ba0c1db502cc0bfe9b942688c4L514

**Comment by Yenthe666** [comment]
@fp-odoo was this literally done intentionally?

**Comment by gdgellatly** [comment]
@nim-odoo I'm confused.  This was closed because?

**Comment by Yenthe666** [comment]
I think because he believes it was introduced by Fabien himself on purpose? I'm still a bit confused too though. Is this really the case @nim-odoo?

**Comment by wtaferner** [comment]
Guys, I think I have the rationale behind...cancelled orders are still considered as potential quotations for the simple reason that they would be visible to the portal user as well as long they are not deleted. Based on this it is kind of logical that the backend user should see under the quotations the same as the portal user.

So, basically if you do not want to have this in your view, it is recommended to set a default filter for yourself IMHO.

But I guess @fpodoo can explain his intentions probably best ;-) @nim-odoo why did you close it without explanation? at least Fabien is not always the best explanation...nobody is perfect...here I think he had good reasons :-)

**Comment by gdgellatly** [comment]
@wtaferner and the rationale for also showing sales? and done sales? If that was the case why have 2 menus?

**Comment by wtaferner** [comment]
Hmm, at least [this code](https://github.com/odoo/odoo/commit/f972b60dc248fe3d54c6e92542d9967de565a31f#diff-0a7015ba0c1db502cc0bfe9b942688c4L514) does not suggest your described behavior...maybe we are talking about different things...

**Comment by gdgellatly** [comment]
@wtaferner I am not suggesting.  I have a screenshot from runbot, and steps to reproduce.  However,I think you misunderstand the minus sign in a diff.

**Comment by wtaferner** [comment]
Haha, you are right, the highlighting was irritating...I wonder why I was not having issues so far with this non-domain...by the way the file was replaced and the commit is somehow outdated anyway.

**Comment by nim-odoo** [comment]
@gdgellatly that was made on purpose because people were confused to see the quotation disappear from the list view as soon as it was validated. BTW, it was already reported in the past (introduced in v10), and we were also surprised to see this behavior.

**Comment by gdgellatly** [comment]
@nim-odoo and they aren't confused by seeing Sales when they click quotations?  Honestly its no big deal, like most companies we have to extend quotations as there is a difference between a quote and a draft sale, so all this gets overwritten anyway, but in this case, it is clearly wrong behaviour and the 'fix' doesn't match the issue.
