### ISSUE TITLE
[11.0] l10n_mx_edi: Missing package dependency for enterprise.deb package

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#21044]
Impacted versions:
 - 11.0

Steps to reproduce:
Using the following Dockerfile:
 - https://github.com/odoo/docker/blob/master/11.0/Dockerfile

Use the URL of the enterprise debian package `.deb`
```patch
diff --git a/11.0/Dockerfile b/11.0/Dockerfile
index 4e9c814..4cc4baa 100644
--- a/11.0/Dockerfile
+++ b/11.0/Dockerfile
@@ -27,8 +27,7 @@ RUN set -x; \
 ENV ODOO_VERSION 11.0
 ENV ODOO_RELEASE 20171030
 RUN set -x; \
-        curl -o odoo.deb -SL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
-        && echo '63d3fd997c850b657b93fb9351624d88d45d1682 odoo.deb' | sha1sum -c - \
+        curl -o odoo.deb -SL https://download.odoocdn.com/download/11e/deb?payload=YOUR_VALID_TOKEN \
         && dpkg --force-depends -i odoo.deb \
         && apt-get update \
         && apt-get -y install -f --no-install-recommends \
```

Build a image
`docker build -t odoo .`

Run a container
`docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4`
`docker run -p 8069:8069 --name odoo --link db:db -t odoo`

Open browser and install `l10n_mx_edi` module.

Current behavior:
 - No module named "OpenSSL"
 - <img width="959" alt="screen shot 2017-11-17 at 17 58 35" src="https://user-images.githubusercontent.com/6644187/32974052-f730b35e-cbc0-11e7-86a8-e3d6bec1a377.png">

Expected behavior:
 - Allow install the module out-of-box after install `.deb` package.

Note: I fixed this issue installing `python3-openssl`:
`docker exec -it --user=root odoo /bin/bash -c "apt-get update && apt-get install -y python3-openssl"`

**Comment by Yenthe666** [comment]
@sle-odoo if I'm not mistaking you manage the docker installers? Could you have a look please?

**Comment by sle-odoo** [comment]
@d-fence is now in charge of our docker file, but i can tell you it is not aimed at running the enterprise package. If one wants to run enterprise, he's free to fork adapt the docker file as needed.

I hope you understand. Regards

**Comment by moylop260** [comment]
This issue is related with dependencies packages from `enterprise.deb`

FYI I fixed from https://github.com/odoo/odoo/pull/21226
