### ISSUE TITLE
[11.0] l10n_mx_edi: Missing files for enterprise.deb package

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#21045]
Impacted versions:
11.0

Steps to reproduce:

Following the instructions from: 
 - https://github.com/odoo/odoo/issues/21044
and installing `python3-openssl` package
Try to install `l10n_mx_edi`

Current behavior:
```bash
file "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 256, in _fileopen
    raise IOError('File not found: %s' % basename)
odoo.tools.convert.ParseError: "File not found: l10n_mx_edi/demo/pac_credentials/certificate.cer" while parsing /usr/lib/python3/dist-packages/odoo/addons/l10n_mx_edi/demo/l10n_mx_edi_demo.xml:4, near
<record id="demo_certificate" model="l10n_mx_edi.certificate">
            <field name="content" type="base64" file="l10n_mx_edi/demo/pac_credentials/certificate.cer"/>
            <field name="key" type="base64" file="l10n_mx_edi/demo/pac_credentials/certificate.key"/>
            <field name="password">12345678a</field>
        </record>
```

<img width="381" alt="screen shot 2017-11-17 at 17 35 46" src="https://user-images.githubusercontent.com/6644187/32974147-920499a4-cbc1-11e7-8efa-6ab73740b03b.png">

The following files are missing:
https://github.com/odoo/enterprise/blob/11.0/l10n_mx_edi/demo/pac_credentials/certificate.cer
https://github.com/odoo/enterprise/blob/11.0/l10n_mx_edi/demo/pac_credentials/certificate.key
All *.xslt files from https://github.com/odoo/enterprise/blob/11.0/l10n_mx_edi/data/3.2/

Expected behavior:
Allow install the module out-of-the-box from .deb package and allow create a invoice

**Comment by Yenthe666** [comment]
@d-fence looks like another packaging issue 😉 (possible related to https://github.com/odoo/odoo/issues/21015)
