### ISSUE TITLE
[11.0] view_mode "list" alias doesn't match with "tree" in ir.actions.act_window.view

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#21056]
**Impacted versions:**
Odoo 11.0

**Steps to reproduce:**

Create an `act_window` with `view_mode` = `list,form`

Then create an `act_window.view` of type `tree` and an other of type `form`. (see example)

`list` seems a valid alias for `tree` as it is used at multiple places and makes more sense than the former tree term:

https://github.com/odoo/odoo/blob/11.0/addons/website/views/website_views.xml#L168
https://github.com/odoo/odoo/blob/11.0/addons/stock/views/stock_picking_views.xml#L108
https://github.com/odoo/odoo/blob/11.0/addons/mrp/views/mrp_production_views.xml#L377

**Current behavior:**

The act_window.view of type tree will be ignored and the default one will be taken.

**Expected behavior:**

The act_window.view of type `tree` needs to be matched with the `list` alias.

**Example of faling code**

Relevent part is:
`view_mode="list,form"`

``` xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>

    <record id="tree_my_partners" model="ir.ui.view">
        <field name="model">res.partner</field>
        <field name="arch" type="xml">
            <tree>
                <field name="name" />
            </tree>
        </field>
    </record>

    <record id="form_my_partners" model="ir.ui.view">
        <field name="model">res.partner</field>
        <field name="arch" type="xml">
            <form>
                <group>
                    <field name="name" />
                </group>
            </form>
        </field>
    </record>


    <act_window id="action_my_partners"
        name="My partners"
        res_model="res.partner"
        view_mode="list,form"
        />

    <record id="action_my_partners_tree" model="ir.actions.act_window.view">
        <field name="act_window_id" ref="action_my_partners" />
        <field name="view_id" ref="tree_my_partners" />
        <field name="view_mode">tree</field>
        <field name="sequence">5</field>
    </record>


    <record id="action_all_customers_form"
        model="ir.actions.act_window.view">
        <field name="act_window_id" ref="action_my_partners" />
        <field name="view_id" ref="form_my_partners" />
        <field name="view_mode">form</field>
        <field name="sequence">10</field>
    </record>


    <menuitem id="menu_test"
        name="TEST actions"
        />
    <menuitem id="menu_test_sub"
        parent="menu_test"
        />


    <menuitem id="my_menu"
        parent="menu_test_sub"
        action="action_my_partners"
        sequence="10"
        groups=""
        />

</odoo>
```

**Comment by Yenthe666** [comment]
@xmo-odoo and @sle-odoo looks like something for you guys to look into 😉

**Comment by sle-odoo** [comment]
@ged-odoo

**Comment by mge-odoo** [comment]
Hi @yvaucher,

Thanks for your report.

Nevertheless, `view_mode="list"` is not, according to me, an alias but it seems to work by coincidence.
You should just avoid to use it in the `act_window` definition.

The occurrences will be removed from our code base.

Regards,

Martin

**Comment by yvaucher** [comment]
Thanks @mge-odoo this will clear up things.

**Comment by mge-odoo** [comment]
Hi,

The views using `list` in `view_mode` have been fixed in master.

Regards,

Martin
