### ISSUE TITLE
[10.0] Can't create new modules because an error in odoo-bin

### ISSUE THREAD

**Issue by jkrauer** [odoo/odoo#21057]
Impacted versions:

> 10.0

Steps to reproduce:

> ./src/odoo-bin scaffold [nameofmodule] local

Current behavior:

> Traceback (most recent call last):
>   File "./src/odoo-bin", line 9, in <module>
>     odoo.cli.main()
> 
>   File "/home/jkrauer/dev/[project]/src/odoo/cli/command.py", line 55, in main
>     for module in get_modules():
>   File "/home/jkrauer/dev/[project]/src/odoo/modules/module.py", line 403, in get_modules
>     plist.extend(listdir(ad))
>   File "/home/jkrauer/dev/[project]/src/odoo/modules/module.py", line 398, in listdir
>     return map(clean, filter(is_really_module, os.listdir(dir)))
> OSError: [Errno 2] No such file or directory: '/home/jkrauer/dev/[project]/src/odoo/openerp/addons'

Expected behavior:

> module is created

**Comment by Yenthe666** [comment]
Hi @jkrauer,

Thanks for your report.
What happens if you change the `local` part to something else to output the module to though?
For example: `./odoo-bin scaffold my_module addons/`

**Comment by jkrauer** [comment]
Hi @Yenthe666 
I've tried in another folder, and even no putting any folder just in case and get the same error. 

But now apparently works under ubuntu 16.04. Yesterday tried under ElementaryOS (who is based on ubuntu 16.04).

**Comment by Yenthe666** [comment]
@jkrauer ElementaryOS is not in the official supported versions though, usage works slightly different there. If it works in Ubuntu 16.04 I believe we can close this.
