### ISSUE TITLE
Can't search by fields date and datetime on search view

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#21067]
Impacted versions:
V10C, V10E, V11C, V11E, tested on runbot today
Steps to reproduce:
On any view search by date or datetime fields
Current behavior:
Open Customer Invoice and input on search view a date(19/11/2017, today)
V11
![image](https://user-images.githubusercontent.com/7775116/32992866-113398da-cd1e-11e7-974a-52952a00313f.png)

Expected behavior:
Option filter by Period is show on search view
V9
![image](https://user-images.githubusercontent.com/7775116/32992855-ea1f89de-cd1d-11e7-8619-89bf5a7d75bd.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @celm1990,

Thanks for your report but this isn't a bug - should be done by design. If I am not mistaking this has been removed alongside the removal of fiscal years (which is removed in V10 & V11 of Odoo).
If you'd like it back you can create an own module to create this though!

Regards,
Yenthe

**Comment by celm1990** [comment]
Sorry, but my not referenced to fiscal year.
On any view(sales order, purchase order, etc) on search view can't search by fields type date and datetime. Bad example customer invoice jejejeje.
For example on search view of sales order, I add field for search view(edit view directly on debug mode)
**<field name="date_order"/>**
![image](https://user-images.githubusercontent.com/7775116/33040995-d4ecbe04-ce0a-11e7-8216-25ebc6857a16.png)

But at refresh page, on search view not display option for search for new field
![image](https://user-images.githubusercontent.com/7775116/33041070-1021d8e2-ce0b-11e7-9254-5704cab13ef5.png)

Sorry for bad english

**Comment by celm1990** [comment]
@MaxyMoos  Thanks so much, tested on runbot and work when enter the full date.

![image](https://user-images.githubusercontent.com/7775116/43286048-7723b0e4-90e6-11e8-9ac9-363b40ff584a.png)

@Yenthe666 On  Version <= 9 is not need enter the full date, is not a bug???

![image](https://user-images.githubusercontent.com/7775116/43286189-e3f6e4de-90e6-11e8-827e-727370e9f858.png)
