### ISSUE TITLE
[Model] browse with ids in string doesn't make sens.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#21062]
**Impacted version**
11,10

**Steps to reproduce:**
With the shell

Create two recordset, one with id 1 and this other with '1'
```
>>> a = self.env['res.users'].browse('1')
>>> b = self.env['res.users'].browse(1)
```

You can call both
```
>>> b
res.users(1,)
>>> a
res.users('1',)
```

But when you try to read, the `a` doesn't work.
```
>>> a.name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/florentdelabarre/git/aln150601_lab/server/odoo/fields.py", line 873, in __get__
    value = record._cache[self]
  File "/Users/florentdelabarre/git/aln150601_lab/server/odoo/models.py", line 5562, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/Users/florentdelabarre/git/aln150601_lab/server/odoo/fields.py", line 48, in get
    raise self.exception
AccessError: (u"Database fetch misses ids ('1') and has extra ids (1), may be caused by a type incoherence in a previous request", None)
```

**And the `exists()` function return the record. It doesn't make sens:**
```
>>> self.env['res.users'].browse('1').exists()
res.users('1',)
```

**Current behavior:**
Id in string are not converted.

**Expected behavior:**
Converte Id in string to Id in Int. Or raise.

If find this issue in the sms module in Saas-18 Enterprise.
Get params return a string and not an int, because the params are write in string.
```
def get_default_sms_provider(self):
      provider_id = self.env['ir.config_parameter'].sudo().get_param('default_sms_provider_id', default=False)
      return self.env['sms.provider'].browse(provider_id)
```

https://github.com/odoo/enterprise/pull/1624

**Comment by mart-e** [comment]
Hello,

Actually we do have strings as ids for some very corner cases like virtual ids for recurrent events.
The proper fix is to make sure we always are working with integers (i.e. converting) when browse. The `sms` example you give is a place where the conversion is missing.

**Comment by mart-e** [comment]
```
>>> self.env['calendar.event'].browse(4).recurrency
True
>>> self.env['calendar.event'].browse(4).get_recurrent_ids([])
['4-20171122080000', '4-20171121080000', '4-20171120080000']
>>> self.env['calendar.event'].browse('4-20171122080000').start_datetime
'2017-11-22 08:00:00'
```

So we can actually have string as ids and not to check it at the ORM level.
Closing as the given code/bug no longer exists in 11.0
