### ISSUE TITLE
[11][OE] sms.gateway no present (but present in Saas-18)

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#21061]
Impacted versions:
11, master

Current behavior:
The V11 enterprise reposit have an empty `sms` module.
But the Saas-18 have a real model with `sms.gateway`.

Expected behavior:
@antonylesuisse  Could you clarify the situation, the `sms` module in community use `iap` to send SMS, but the `sms` module in Sass-18 don't use inherance. (Maybe `iap` will be a provider).

It is normal ?

Thanks

**Comment by Yenthe666** [comment]
@mart-e can you enlighten what happend/changed here? This is odd.

**Comment by mart-e** [comment]
Hello,

https://github.com/odoo/enterprise/commits/11.0/sms
https://github.com/odoo/odoo/commits/11.0/addons/sms
should answer your questions.

We have refactored sms yo use IAP while moving to community. So yes, models and inheritance did changed. I don't see what is odd here.
saas-18 is not a supported branch so, don't rely on it.

**Comment by fmdl** [comment]
I understand that `sms.gateway` is deprecated.

**Comment by mart-e** [comment]
That is also something I don't understand in your bug report. You are talking about the model `sms.gateway` but it does not exists neither in saas-18 not in 11.0..

**Comment by fmdl** [comment]
I sorry it is not `sms.gateway` but it is `sms.provider` https://github.com/odoo/enterprise/blob/saas-18/sms/models/sms_provider.py#L10

In V11CC, you have only `sms.api`.

In fact I have dev a module to use sms by OVH. `sms.provider`, doesn't exist in V10, V11, but in Saas18. That why I put the question, if it is normal ?

I will use `sms.api` for my module.

Regards

**Comment by mart-e** [comment]
Ok I see now. Yes, this is part of the change to use IAP instead.

**Comment by fmdl** [comment]
Thank :-)

**Comment by mart-e** [comment]
To modify your provider, the easiest is probably to set yourself as `sms.endpoint` param and to override the controller `/iap/message_send`

**Comment by fmdl** [comment]
Ok, thanks

Florent de Labarre
