### ISSUE TITLE
0 value provider invoice is allowed

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#21071]
Impacted versions:
11

Steps to reproduce:
create a new invoice put the price to any item to 0

Current behavior:
the invoice is accepted the invoice

Expected behavior:
in order for the net price to be 0 it should require a 100% discount

**Comment by Yenthe666** [comment]
Hi @icf20,

Thank you for your report.
I don't really agree though. In some cases you would like to add a product on an invoice that has no price. The 'product line' is more or less used for information for the customer.
I don't see any problem in having the ability to add product lines where both the price is 0 and no discount is set. It would only block real life cases that some people would most likely use.
Anyways, final call is for @qdp-odoo 

Regards,
Yenthe

**Comment by qdp-odoo** [comment]
indeed
