### ISSUE TITLE
Sale Order totals misaligned

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21078]
Impacted versions: 11.0

Steps to reproduce:
Go to runbot
Print a quote

Current behavior:
The totals box is too far right.
So what you say, well it looks ugly. If using in conjunction with background layout it looks extra ugly

Expected behavior:
Totals box aligned with order lines

Video/Screenshot link (optional):
Ignore the whitespace, that line just happened to have a really long description.
![image](https://user-images.githubusercontent.com/5093264/33003341-ef79d57c-ce1e-11e7-9949-6617b6c83555.png)

**Comment by Yenthe666** [comment]
@mart-e this can indeed be better 😉

**Comment by gdgellatly** [comment]
Note: I fixed for myself just by adding

```less
.o_report_layout_background {
  #total {
    margin-right: 0;
  }
}
```

to override the row class

**Comment by gdgellatly** [comment]
@mart-e @Yenthe666 Actually after completing the entire suite of reports using this layout, I've come to the conclusion that purchase order has it right and looks awesome.  Everything else should use that total box style.

![image](https://user-images.githubusercontent.com/5093264/33122932-87926f80-cfdd-11e7-9264-731cd97d7d2c.png)

e.g. for sale my override (it has some other customisation) but really just the first 3 divs and table tag is all that matters.

```xml
<xpath expr="//div[@name='total']" position="replace">
            <div class="row " name="total">
                <div class="pull-right col-xs-4">
                    <table class="table table-condensed" style="min-width: 200px;max-width: 350px;">
```

instead of 

```xml
<div class="row pull-right" name="total">
                    <div>
                        <table class="table-condensed" style="min-width: 200px;max-width: 350px;">
```

looks so much nicer, no need for any additional css either.  Anyway, use it, close the issue, do what you want, just updating it.

**Comment by Yenthe666** [comment]
Final call is for @mart-e 😄

**Comment by mart-e** [comment]
Thanks for the investigation, changed that at b0a75b8fcda6d9949646cfa3c178b7823d3103ab

**Comment by nim-odoo** [comment]
Thanks was just working on this for an OPW :) BTW, same occurs in invoices: https://github.com/odoo/odoo/pull/21149
