### ISSUE TITLE
website_event_sale: bug allows to get tickets for N persons, but pay only for one

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#21082]
Impacted versions: 10.0, 11.0, maybe others

**Steps** to reproduce: *for 10.0*

* install website_event_sale
* open event registration page (e.g /event/conference-on-business-apps-2017-11-23-3/register )
* fill form for 2 person
* after filling the form you are redirected to /shop/checkout
* Now click Review Order -- opens /shop/cart
* change quantity from 2 to 1
* finish checkout process 
* Login to backend: 
* Confirm Sale Order (Alternatively: pay for one ticket on website via paypal)

Current behavior:
* two tickets are confirmed

Expected behavior:
* only one paid ticket must be confirmed

PS There is an enterprise subscriber who faced the issue

**Comment by Yenthe666** [comment]
Hi @yelizariev,

Thank you for your report.
I've just tried this and you can indeed change your own quantities. Quite handy that you can do this 😆
@JKE-be perhaps something for you to look at.

Regards,
Yenthe

**Comment by stfl** [comment]
Any updates? We currently keep on getting multiple registrations which have not been paid for.

**Comment by Yenthe666** [comment]
@stfl no update - if you really want it handled fast and have an enterprise contract then log an official ticket. The support on Github is best effort and can take weeks/months honestly. (Nope, I didn't come up with those rules)

**Comment by nim-odoo** [comment]
Closed in https://github.com/odoo/odoo/commit/ac31252d540c0aa80435ca87ce8d756b064a1f7c
