### ISSUE TITLE
[11.0] lost all css attributes ( width,height...... ) in list view (tree, x2many,)

### ISSUE THREAD

**Issue by daimengmeng** [odoo/odoo#21087]
Impacted versions:
- 11.0 github souce code

Steps to reproduce:
- Add html attribute **width="200px"** to any field in one2many field
- Add html attribute **width="200px"** to  any field in tree view

Current behavior:
- nothing happend

Expected behavior:
- The column width should be 200px

Video/Screenshot link (optional):
![issue-330](https://user-images.githubusercontent.com/13128021/33011009-8bd01eac-ce17-11e7-899f-a1746d0b1e32.gif)

**Comment by daimengmeng** [comment]
@Yenthe666 can you have a look? It's same as #20620？

**Comment by Yenthe666** [comment]
Hi @daimengmeng,

Thanks for the report.
As you've linked the other issue too it and as it is very identical to the other issue I'm sure @mart-e will look at this one while handling https://github.com/odoo/odoo/issues/20620

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Sorry but the `width` attribute is not supported in form view declarations. I let the framework team decide for #20620 but I am pretty sure this one is not supported.
You may want to try hacking the CSS of the form but it is at your own risks.

**Comment by daimengmeng** [comment]
@mart-e  Thank you for your reply，
I've used the css style to control the column width， 
but as issue #20620 ，It doesn't work :(
