### ISSUE TITLE
[10.0] Bad currency rate on invoices

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#21085]
Impacted versions:

10.0

Steps to reproduce:

See https://youtu.be/IKGp4r5aHpc

Current behavior:

Currently, a currency invoice is converted in company currency using the rate of the accounting date.

Expected behavior:

The rate to convert a supplier invoice into the company currency should be the rate at the invoice date like in version 8.0.

Video/Screenshot link (optional):

See https://youtu.be/IKGp4r5aHpc

**Comment by adrienpeiffer** [comment]
OPW 783372

**Comment by qdp-odoo** [comment]
I confirm we were taking the invoice date in v8, so we probably should do the same in v9 and onward

**Comment by nim-odoo** [comment]
@qdp-odoo then I guess you'll have to fight with @lap-odoo , because this behavior was confirmed by the lady herself and introduced on purpose in 74e4130f5f370c (see opw 751848)

**Comment by adrienpeiffer** [comment]
@nim-odoo @qdp-odoo @lap-odoo Just to complete this one, this bug was reported by 2 of my customers.   The accounting departments of these confirms the behavior of the version 8. 
For one of them, we made a migration from version 8 to 10. So, there is a mix in accounting.

**Comment by Yenthe666** [comment]
@adrienpeiffer did this get handled? What was the feedback for the OPW?

**Comment by adrienpeiffer** [comment]
Odoo introduced a hook in order to allow to change the date taken for the conversioon.

**Comment by Yenthe666** [comment]
Then I guess this can be closed.
