### ISSUE TITLE
[10.0] LongPolling returns "Odoo Server Error"

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#21080]
Impacted versions:
10.0

Steps to reproduce:
1. Login as admin user.
2. Open the "Developer Tools" (Ctrl + Shift + I for Chrome)
3. Observe the "poll" request in the "Network" tab.
4. All "poll" request should return 200 as the Status Code and something like `{"jsonrpc": "2.0", "id": 787294406, "result": []}` in the response.
5. Duplicate the browser tab, do not close the first tab.
6. On the second tab, logout and re-login as the same admin user.
7. Access any backend page on the second tab (e.g. Sales -> Customers).
8. On the first tab, wait until the current polling request to finish (around 1min), the "poll" request returns 200 as the Status Code and following response message
`{"jsonrpc": "2.0", "id": 973573527, "error": {"message": "Odoo Server Error", "code": 200, "data": {"debug": "Traceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/279404-10-0-5a467f/odoo/http.py\", line 640, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/extra/runbot/static/build/279404-10-0-5a467f/odoo/http.py\", line 1453, in _dispatch_nodb\n    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()\n  File \"/usr/lib/python2.7/dist-packages/werkzeug/routing.py\", line 1483, in match\n    raise NotFound()\nNotFound: 404: Not Found\n", "exception_type": "internal_error", "message": "404: Not Found", "name": "werkzeug.exceptions.NotFound", "arguments": []}}}`
9. Switching back to the second tab, "Odoo Server Error: NotFound: 404: Not Found" appears when click on any link.

Concerns:
I would like to know if this is considered as a standard behavior?
It seems that the session of the first tab has affected the session in the second tab to me. The "Odoo Server Error" response body has raised my concerns that it is kind of telling user that something goes wrong on the server side.

Video/Screenshot link (optional):
https://youtu.be/ePVs9K62gZ8

**Comment by Yenthe666** [comment]
Hi @TimLai125,

It is quite logical that this breaks. You're logging in and out with different tabs. How should Odoo ever know what is what? In one tab you're keeping your Odoo open while in the other tab you've already logged out and back in - which changes all the behaviour. Tab1 is not aware about tab2 and the same applies the other way around.
This is normal behaviour and not a bug. If you would do this on two different devices / browser you shouldn't get this.

Regards,
Yenthe
