### ISSUE TITLE
[11] sale and website_sale / There is no widget=checkbox

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21099]
Impacted versions: 11

Steps to reproduce:
Install one of apps: sale, website_sale
https://github.com/odoo/odoo/blob/11.0/addons/sale/views/sale_layout_category_view.xml#L11
https://github.com/odoo/odoo/blob/11.0/addons/sale/views/sale_layout_category_view.xml#L12
https://github.com/odoo/odoo/blob/11.0/addons/sale/views/sale_layout_category_view.xml#L25
https://github.com/odoo/odoo/blob/11.0/addons/sale/views/sale_layout_category_view.xml#L26
https://github.com/odoo/odoo/blob/11.0/addons/website_sale/views/res_config_settings_views.xml#L30

Current behavior:
Warning
Missing widget:  checkbox  for field group_website_multiimage of type boolean
data_manager.js:467:17

Expected behavior:
without warning

**Comment by mart-e** [comment]
Yes, this widget seems useless and can be probably removed (while not harmful) :)

**Comment by mart-e** [comment]
Removed in master at e7f76783b638ffcab3ee2c4cf37f75cfc1135511
