### ISSUE TITLE
[gmail] User can't know if wrong destination email address has been used

### ISSUE THREAD

**Issue by eLBati** [odoo/odoo#21119]
**Impacted versions**:

8.0, 9.0, 10.0, 11.0

**Steps to reproduce**:

 - Install ```contact``` and ```fetchmail```
 - In technical --> email --> incoming mail servers, configure a mailbox dedicated to odoo, say ```odoo@mydomain.com```
 - In technical --> email --> outgoing mail servers, configure the same mailbox, ```odoo@mydomain.com```
 - Set system parameter ```mail.catchall.alias``` = ```odoo```
 - Set system parameter ```mail.catchall.domain``` = ```mydomain.com```
 - Set system parameter ```mail.bounce.alias``` = ```odoo```
 - Create a contact with a wrong email address, say ```jj@jj.pink```
 - Add this contact as follower of the contact
 - Send a message in the contact's chatter

**Current behavior**:

 - Odoo set the sent message as OK, see image
![jj](https://user-images.githubusercontent.com/1033131/33071403-a5653bfa-cebb-11e7-8e4d-3f47dcb66b0d.png)
 - Mailbox ```odoo@mydomain.com``` receives a ```multipart/report``` message saying "address not found"
 - Odoo reads this message (by ```fetchmail```) and discards it
 - User doesn't know that the messagge was not delivered

**Expected behavior**:

User should be notified of failure

**Comment by eLBati** [comment]
In my case, ```odoo@mydomain.com``` is a gmail mailbox. Thus, it seems gmail ignores the ```Return-Path``` set by odoo.

Indeed, odoo correctly sets it to something like ```odoo+128-crm.lead-34@mydomain.com``` and sends the message to smtp.gmail.com.

At line
https://github.com/odoo/odoo/blob/0783318f9745c4e213016b825e9bbd8e1e9bd546/odoo/addons/base/ir/ir_mail_server.py#L456
```message._headers[11]``` is ```<type 'tuple'>: ('Return-Path', 'odoo+128-crm.lead-34@mydomain.com')```

and ```smtp_from``` is ```odoo+128-crm.lead-34@mydomain.com``` too

Nevertheless, the message delivered by smtp.gmail.com has ```Return-Path``` = ```odoo@mydomain.com```, instead of ```odoo+128-crm.lead-34@mydomain.com```.

So, the bounce message can't be processed by odoo.

I found some confirmations:
https://productforums.google.com/forum/#!topic/gmail/Nk1oL7mvgUI
https://stackoverflow.com/a/9925518/1187150

@odony are you aware of this problem with odoo + gmail?

Thanks!

**Comment by odony** [comment]
@eLBati I think you're testing with the default GMail SMTP server. This is not suitable for use as a generic outgoing SMTP server by any application.
It only provides a "portable SMTP server" for personal use by the owner of a GMail account. This service has strict limitations:
- it can only send messages "From" one of the verified aliases of the user (the ones in the "Send mail as" section of the GMail settings)
- it will automatically replace the SMTP "Envelope FROM" with the **default** alias of the user (chosen in the "Send mail as" section of the GMail settings). This will translate into the final "Return-Path" header, as you've seen.
- it drastically limits the number of emails that can be sent per day

If you'd like to use GMail has a general purpose outgoing SMTP, you should look into the [GSuite SMTP Relay service](https://support.google.com/a/answer/2956491), which works with whitelisted IPs and can relay based on the From domain, or the authenticated GSuite user, etc.
It probably has its own limitations, but might be more suitable as an outgoing SMTP server for Odoo.

**Comment by eLBati** [comment]
Thanks @odony .
More in general, what is the configuration (SMTP + IMAP/POP) you suggest to use in order to correctly send and receive emails with odoo (thus to cover the use case described here)?

**Comment by eLBati** [comment]
Meanwhile I made a module https://github.com/OCA/social/pull/223 to get anyway notified about bounced emails

**Comment by mart-e** [comment]
Since 12.0, the user is notified of emails that are not sent in the chatter (sorry I don't have examples to provide a screenshot).
