### ISSUE TITLE
Some unchanged constraints dropped and created at each module update

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#2112]
Ported from https://bugs.launchpad.net/openobject-server/+bug/1011538

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
