### ISSUE TITLE
POS: Search on customer Ignores last character due to keypress event

### ISSUE THREAD

**Issue by dek-odoo** [odoo/odoo#21129]
**Impacted versions:**

`All`

**Current behaviour:**

 When the content of textbox is of two characters, it just searches for length-1, ignoring last character.

**Possible Solution**
> Instead of using keypress, keyup could be used.

**Expected behaviour:**

It should search for all the text entered, instead of ignoring the last character.

**Steps to reproduce:**

1. Type a character in searchbox of POS Customer screen and it will do nothing.
2. Check the Regex for more clear inspection of what is being searched.

**Video/Screenshot link (optional):**

Keyup event could be used to prevent this behaviour.

**Comment by dek-odoo** [comment]
[A Video Showing Bug](https://youtu.be/KI7A3LwJSLE)

**Comment by Yenthe666** [comment]
@ged-odoo or @jorenvo probably something for one of you?

**Comment by dek-odoo** [comment]
Thank you @jorenvo .

This may be a different issue on `Customer Screen Searchbox`.
The replace function [here](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/static/src/js/db.js#L304), will only replace the first occurence of space ` `  with `.+` (for regexp), so user may not be able to search for `Name Address Phone` together like `agro namur 588`. Probably `query.replace(' ','.+')` can be replaced with `query.split(' ').join('.+')`

@Yenthe666
