### ISSUE TITLE
[10] Save user in urgent case not possible

### ISSUE THREAD

**Issue by auditum-sfr** [odoo/odoo#21144]
Impacted versions:
at least 10

Steps to reproduce:
- install module: projects
- install module: timesheets
- create a contact

Current behavior:
Following error occurs:
"The following fileds are invalid:
Account Receivable
Account Payable"

I cant add the datas, beacuse I dont have installed the module "accounting".

Expected behavior:
Contact is saved

Video/Screenshot link (optional):
![error](https://user-images.githubusercontent.com/25483058/33132122-f61c843a-cf98-11e7-8516-523ed34a1a40.jpg)

**Comment by Yenthe666** [comment]
Hi @auditum-sfr,

Thanks for your report.
This is however default behaviour and I don't think this will be accepted as a bug. @mart-e what do you think?
P.S: This isn't only the case in V10 😉 

Regards,
Yenthe

**Comment by mart-e** [comment]
Indeed, it is the expected behaviour 😉 
To fix your error, you need to install a chart of account on your company.
If you have these fields, you do have the `account` module installed.
