### ISSUE TITLE
Odoo 11 Enterprise, Strange Issue | Basic Inheritance Crash on Views

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#21146]
Impacted versions: Odoo 11.0 Enterprise Tested.
Seem also in 10.0

Steps to reproduce:
<xpath expr="//field[@name='name']" position="attributes">
       <attribute name='readonly'>1</attribute>
</xpath>

Note: When we inherit and make readonly `name` field of "res.partner" and make readonly.
Than after in case remove xpath or do readonly=0. than it gives validation error.

Contact required a 'name', its mean main `name` field effect but same 'name' field in child_ids,
Where in in-line form view also 'name' field their might stuck and not do undo readonly.
Even we remove xpath code, it keep gives an error for require and readonly. 

Here seems xpath with child_ids in res.partners, with customer list, found difficulties during adding some custom module.

Please check and confirm if applicable.

Current behavior: Not working xpath readonly removal

Expected behavior: Check and will odoo framework decide todo.

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Hi @tejastank can you provide a copy/screenshot of the traceback/error you get?

**Comment by tejastank** [comment]
@Elkasitu I try soon to attach screenshot and other possible steps

**Comment by rruebner** [comment]
@tejastank I tried to reproduce the error in odoo 11 enterprise runbot and if you mean what you see in the image below I confirm the bug.
![change_field_attribute_readonly_error](https://user-images.githubusercontent.com/2195663/33423789-245800d2-d5ba-11e7-88c2-f5b6394e16fa.png)

**Comment by tejastank** [comment]
Not this one.

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as @tejastank has been blocked from the Odoo repository.
An official response can be found on the thread https://github.com/odoo/odoo/issues/7466#issuecomment-378920731, to quote @mart-e:

> Due to the repeated aggressive tone (#16056 (comment), #8514 (comment), #1880 (comment), #7019 (comment), #7085 (comment)...) with the one that are trying to help you or just failing to give useful information to a point beyond bad faith (#10931 (comment), #3443 (comment), #4544 (comment),...), @tejastank is now blocked on the Odoo repository.
I was hoping we could manage a solution but, after almost 4 years, it seems sadly that we can not discuss constructively with him.
