### ISSUE TITLE
traceback - account reports followup when signature is not set

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21151]
Impacted versions: 11.0

Steps to reproduce:
Go to followups
Click send an email on the followup
Current behavior:
Error:
Odoo Server Error

Traceback (most recent call last):
<truncated>
  **File "/home/graemeg/PycharmProjects/odoo10-c/enterprise/account_reports/models/account_followup_report.py", line 204, in send_email
    body_html': append_content_to_html(body_html, self.env.user.signature, plaintext=False),**
  File "/home/graemeg/PycharmProjects/odoo10-c/odoo/odoo/tools/mail.py", line 396, in append_content_to_html
    content = re.sub(r'(?i)(</?(?:html|body|head|!\s*DOCTYPE)[^>]*>)', '', content)
  File "/home/graemeg/PycharmProjects/odoo10-c/python-odoo11/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

Expected behavior:
Like everywhere else signature is accessed 
`body_html': append_content_to_html(body_html, self.env.user.signature or '', plaintext=False`

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thanks for the report - I made a PR on the enterprise branch to handle this. Somebody from Odoo has to merge it in now. 😄

**Comment by Yenthe666** [comment]
Hey,

It has been fixed and merged at https://github.com/odoo/enterprise/issues/1634
Thanks again for the report.

Regards,
Yenthe
