### ISSUE TITLE
[point_of_sale] Sale details report is not considering user time zone

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#2115]
Sale details report have wrong data when orders get registered in different day because of time zone differences.

How to reproduce:
Set user time zone to GMT-6:00
Register a sale after 18:00 user local time
-->  The sale gets registered on next day
Create Sale Details report for Point of Sales
-->  The sale does not show up

Regards,
-Mario

**Comment by florca1979** [comment]
Hello there any solution to timedate
please if anyone can tell me how to fix it
my records made after 21:00 after all spend the next day
my zone is GMT-3: 00
in reports and records show bad form
this leads to Odoo not very user friendly
there is a solution to this problem
surprise me after so many years Odoo still have this same problem

**Comment by invitu** [comment]
Problem is still present in v9 : 
Orders are well computed but payments are not

**Comment by Yenthe666** [comment]
Hi @TheCloneMaster,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
