### ISSUE TITLE
[10.0] Delivery 2 steps going into the past

### ISSUE THREAD

**Issue by umiphos** [odoo/odoo#21179]
### Impacted versions:
10.0
### Steps to reproduce:
First configure: 
- Inventory
- Warehouse Management
- Warehouses 
- (Select the warehouse you are going to use) 
- **[Change] Outgoing Shippings** to **Bring goods to output location before shipping (Pick + Ship)**

Steps to reproduce:
1. Create a Sale Order
2. Set the Requested Date 1(or more) hours into the future of the current time
3. Confirm it
4. Select the delivery icon on the top right
5. Enter in the one that says PICK
6. Validate it

After that you should be seeing the OUT out of date. 
### Current behavior:
If you put that previous configuration the Stock Operations OUT movement is going to be sent into the past.
### Expected behavior:
The OUT date should be into the same day if the PICK has been occurred. The OUT suddenly changing to a date into the past is a bug for the records.
### Video/Screenshot link (optional):
[![IMAGE DESCRIPTION](http://img.youtube.com/vi/4hDJL7yhEBA/maxresdefault.jpg)](https://youtu.be/4hDJL7yhEBA "Bug on 2 way delivery")

### Additional notes
We detected that this error was the result of this
![image](https://user-images.githubusercontent.com/4094256/33189709-0ea2f19c-d06b-11e7-91ee-00a395d49b49.png)

If you clic on that option the default value is 0 any time we open the view, even if you set another value, next time you open that view and save, that 0 is going to be saved if we don't take care each time we make a modification to that view.

**Comment by sle-odoo** [comment]
Hello,
This issue should have been fixed by https://github.com/odoo/odoo/pull/21445.

If you're still facing the issue, feel free to comment.

Regards
