### ISSUE TITLE
[11.0] filtering on datetime field does not properly handle the client timezone

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#21173]
### Impacted versions:

11.0 (10.0 seems to work fine)

### Steps to reproduce:

- Go to purchase order list view (or a list/kanban view for any model with a datetime field).
- Try applying a filter with order date field (or any datetime field).

### Current behavior:

Selected time for filter is converted to the selected time + variance to UTC time.

e.g.
- client timezone: Hong Kong (UTC+8)
- selected time: 2017/11/23 23:00:00
- the time actually applied for filter: 2017/11/24 07:00:00

### Expected behavior:

Selected time for filter should stay as it is.

### Video/Screenshot link (optional):

![2017-11-23_21-47-24](https://user-images.githubusercontent.com/7766939/33175892-2833a174-d098-11e7-8e45-a6a7eae081f2.gif)

**Comment by Yenthe666** [comment]
@nim-odoo if I'm not mistaking you are the guy for timezones?

**Comment by aab-odoo** [comment]
@adr-odoo is the guy :)

**Comment by adr-odoo** [comment]
Hello,

Merged: https://github.com/odoo/odoo/commit/d2e1a1deb3c5caaaa99a3e06122035349d440b35
Thank you for reporting.
Regards,
