### ISSUE TITLE
[11.0] Enterprise handle widget produces incorrect sort order

### ISSUE THREAD

**Issue by InfernalLV** [odoo/odoo#21200]
Impacted versions: 11.0 Enterprise

Steps to reproduce:
Go to runbot, select any v11 instance.
Sales -> Catalog -> Product -> List View

Pick any item in the list move it by the handle. Refresh (F5) and notice that it doesn't change place.

Observations made in local dev environment.

In case of a full list when you move an item resequence is called, but only some of the item's sequence value seems to be updated. Resulting in a incorrect sorting.

A form's o2m tree widget seems to call onchange. Move 2 or more rows to random locations. They should should jump around seemingly randomly. But are re sorted after pressing save. The resulting sort order is incorrect though.

At on point i figured that the partial re sequence should be used with a secondary sort row like id, but that also didn't produce the expected result. In fact native addons also seem to sort only on the sequence column. 

Current behavior:
Using handle widget produces random sort orders.

Expected behavior:
Recompute sequence so that the items are sorted as the user sorted them with a handle.

**Comment by Gorash** [comment]
Thank you for your report, a branch has already been created https://github.com/odoo/odoo/pull/21135

**Comment by Yenthe666** [comment]
@Gorash is there any update on this? It seems to have been laying still for a bit?

**Comment by Gorash** [comment]
Code in review. We must wait

**Comment by Yenthe666** [comment]
Okay - thanks for the feedback!

**Comment by hugho-ad** [comment]
Also replicated in account bank statement lines

**Comment by Gorash** [comment]
The branch #21135 is merged

**Comment by hugho-ad** [comment]
@Gorash Can you share us the fix commit?

I replicated in bank stament lines

I added some lines, then I modify the view in order to show up the sequences number, and it looks it's not working

![image](https://user-images.githubusercontent.com/10233975/36166906-aa1cf882-10b9-11e8-97c4-7ea431ecdedf.png)

**Comment by Gorash** [comment]
The fix does not create an incremental default value for the sequence field. The fix take in care the reordering with handle widget. If the sequence is identical, the sorting will be done according to the preference of the model (the id by default) which does not change the order. We will discuss internally to know if we will change that for the future.
