### ISSUE TITLE
[8.0/10.0] Astonishing api.onchange behaviour

### ISSUE THREAD

**Issue by ssaid** [odoo/odoo#21212]
Impacted versions: 8.0 & 10.0 (not tested in 9.0)

Steps to reproduce:
In 10.0
1. Edit a partner, change the country, this will trigger the onchange that returns the domain for state_id, correct domain is set, save the register.
2. Go to another partner, the domain is set to the old domain returned in the previous edition.

Current behavior:
The domain is incorrect because the function was called only in the first register

Expected behavior:
IMHO, the domain should be empty but also, a nice option could be that onchange is triggered on the field if it has any contents.

**Comment by katyukha** [comment]
Odoo 11.0 still have this bug.

Steps to reproduce it in Odoo 11.0:
1. Create clean database
2. Install *Contacts* application
3. Create Contact *Test 1*: **Do not set address!**
4. Create Contact *Test 2*: **Select only country US**
5. Go back to *Test 1* contact record.
6. Click *Edit* button
7. Open *State* selection.

Expected: list of all available states
Current bechavior: Only US states available in State selection.

**Comment by Yenthe666** [comment]
Dear @ssaid,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
