### ISSUE TITLE
TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects when calling do_new_transfer on stock.picking

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#21238]
I'm using Odoo 10.saas~14+e (Enterprise Edition). When I call `do_new_transfer` on a `stock.picking` via the XMLRPC api, I get the following error response:

```
Traceback (most recent call last):
    File "/home/odoo/src/odoo/saas-14/odoo/service/wsgi_server.py", line 57, in xmlrpc_return
      response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)
    File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps
      data = m.dumps(params)
    File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps
      dump(v, write)
    File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
      f(self, value, write)
    File "/usr/lib/python2.7/xmlrpclib.py", line 741, in dump_struct
      dump(v, write)
    File "/usr/lib/python2.7/xmlrpclib.py", line 658, in __dump
      raise TypeError, "cannot marshal %s objects" % type(value)
  TypeError: cannot marshal <class 'odoo.tools.misc.frozendict'> objects
```
My call to the API looks like this:

```
self::$modelClient->execute_kw(self::$db, self::$uid, self::$password,
                               'stock.picking', 'do_new_transfer', [52], $keywordArgs, []);
```

Is there anyway to fix this? Is this response intentional behavior?

I'm trying to validate a picking via the API. The picking does not have any completed operations yet, so I would expect to get a response telling me the ID of the `stock.immediate.transfer` that was created so that I can then call the `process` method on that, like I would through the UI, but instead I am getting this error.

For reference, I recently reported a similar issue with return values of `None` via issue #19889. Just mentioning that in case they are somehow related.

**Comment by flyingL123** [comment]
Apologies, I just realized I am going about this the wrong way. I should be creating the `stock.immediate.transfer` myself, then calling the `process` on it. This works, however, I now see that it has the same issue as mentioned in #19889. The `process` method does not have a return value. I will bring this up in the other issue.

**Comment by zubaer93** [comment]
@flyingL123 you said " I should be creating the stock.immediate.transfer myself, then calling the process on it. ". may i ask how are you creating that. In my case when i am trying to create the same error "cannot marshal <class 'odoo.tools.misc.frozendict'> objects" is showing

**Comment by flyingL123** [comment]
@zubaer93 I'm happy to help, but can you provide a code sample of what you're trying to do?

**Comment by zubaer93** [comment]
@flyingL123 sure 
this is my function 
 public function validate($model, $action, $id)
    {
        $response = $this->getClient('object')->execute_kw(
            $this->database,
            $this->uid(),
            $this->password,
            $model,
            $action,
            [ $id ]
        );
        return $response;
    }

and i am calling it like this 
                $buttonValidate = $odoo->validate('stock.picking', 'button_validate', (int) $id);

which do the work fine. but does not return the `stock.immediate.transfer` ID. its showing that error response as you said

**Comment by flyingL123** [comment]
@zubaer93 thanks for the code. The `button_validate` method simply returns an action which instructs the Odoo UI to open a wizard window which then allows the creation of a new `stock.immediate.transfer` for the given picking.

It doesn't really make sense to call this method via the API unless you're building your own UI or something like that. Instead, your code should simply create the `stock.immediate.transfer` itself and call the `process` method on it, which is what is happening when you click the `Apply` button in the `stock.immediate.transfer` popup.

To clarify, here's my `validate` method:

    public function validate()
    {
        $transferId = $this->client->create('stock.immediate.transfer', ['pick_id' => $this->id]);

        $this->client->method('stock.immediate.transfer', 'process', [$transferId]);

        return $this;
    }

Any questions, let me know.

**Comment by zubaer93** [comment]
@flyingL123 I just implemented your process. But the problem is there is a 'stock_picking_transfer_rel' table which maintain the many to many relation between  stock_immediate_transfer AND stock_picking. SO when I follow your process an Id is returned from the stock_immediate_transfer model, but there is no relation created between stock_immediate_transfer AND stock_picking in 'stock_picking_transfer_rel'. Therefore the stock_picking state doesn't change from 'assigned' to 'done'. and the stock also dont actually validated.

**Comment by flyingL123** [comment]
Are you passing in the pick_id field as I show? For me it works as expected. The state changes to done and the stock moves are completed. You must be doing something differently.

**Comment by flyingL123** [comment]
Also the pick_id field is many2one, so there is no relation table needed. Are we using different versions of Odoo? I’m still using 10.

**Comment by zubaer93** [comment]
@flyingL123 yes i am passing the pick_id. And I am using odoo 12. maybe that is causing the trouble

**Comment by flyingL123** [comment]
Yea in 12 it's many2many, and it's called `pick_ids`, so just change the field name to `pick_ids`. You will probably need to make it an array too:

```
$transferId = $this->client->create('stock.immediate.transfer', ['pick_ids' => [$this->ids]]);
```

There may be other small changes needed to work for Odoo 12, but that should be a start. You just need to populate whatever fields are needed to get this method to work correctly:

```
https://github.com/odoo/odoo/blob/12.0/addons/stock/wizard/stock_immediate_transfer.py#L14
```

**Comment by CharlesLemon** [comment]
```
transfer_id = odoo.perform(
    'stock.immediate.transfer', 'create',
    [
        {
            'pick_ids': [
                [4, picking_id, False]
            ]
        }
    ])
```

For odoo 12, this works for me.
