### ISSUE TITLE
How to add Nepali Calendar to Odoo?

### ISSUE THREAD

**Issue by bishisht** [odoo/odoo#21236]
Hello all, let me know if I am posting this on wrong place and I will remove this. 

Issue: I live in Nepal. We use Nepali Calendar system. I want to add Nepali Calendar to odoo please let me know how can I add new calendar system? 

Ask me for more details if you don't get what I am trying to express here.

**Comment by Yenthe666** [comment]
Hi @bishisht,

Thank you for your report. The bug tracker is only for bugs in the official code and not to ask questions though.
Please do ask this on the official help forums (at help.odoo.com) where plenty of people can help you.
To give you some insight: you will need to do custom development to add in the calendar with JS.

Regards,
Yenthe
