### ISSUE TITLE
Theme Tutorial: Create a specific page layout

### ISSUE THREAD

**Issue by dataprojects** [odoo/odoo#21243]
Impacted versions: 11

Steps to reproduce:
I'm following the tutorial:
https://www.odoo.com/documentation/11.0/howtos/themes.html#create-a-specific-page-layout
When I'm adding pages.xml to data (in __manifest__.py) I'm getting an error:
AssertionError: Element odoo has extra content: template, line 5
```
Current behavior:
2017-11-26 22:10:41,454 14789 ERROR OdooDemo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/odooadmin/odoo/odoo/odoo/service/server.py", line 251, in app
    return self.app(e, s)
  File "/home/odooadmin/odoo/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/odooadmin/odoo/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odooadmin/odoo/odoo/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odooadmin/odoo/odoo/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/odooadmin/odoo/odoo/odoo/http.py", line 1456, in dispatch
    odoo.registry(db).check_signaling()
  File "/home/odooadmin/odoo/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/home/odooadmin/odoo/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/home/odooadmin/odoo/odoo/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odooadmin/odoo/odoo/odoo/modules/loading.py", line 339, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odooadmin/odoo/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odooadmin/odoo/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odooadmin/odoo/odoo/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odooadmin/odoo/odoo/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odooadmin/odoo/odoo/odoo/tools/convert.py", line 836, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:194922)

AssertionError: Element odoo has extra content: template, line 5
```

Expected behavior:
I expect the behavior described in the tutorial

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @dataprojects,

Can you add the code from the file here please?

**Comment by dataprojects** [comment]
I followed the tutorial 
https://www.odoo.com/documentation/11.0/howtos/themes.html#create-a-specific-page-layout

I tried both versions. None worked for me
Version 1:
`<?xml version="1.0" encoding="utf-8" ?>
<odoo>

    
    <template name="Services page" id="website.services" page="True">
      <h1>Our Services</h1>
        <ul class="services">
          <li>Cloud Hosting</li>
          <li>Support</li>
          <li>Unlimited space</li>
        </ul>
      </template>

  </odoo>`

Version 2:
`<?xml version="1.0" encoding="utf-8" ?>
<odoo>


<template name="Services page" id="website.services" page="True">
  <t t-call="website.layout">
   <div id="wrap">
     <div class="container">
       <h1>Our Services</h1>
       <ul class="services">
         <li>Cloud Hosting</li>
         <li>Support</li>
         <li>Unlimited space</li>
       </ul>
       
       <div class="oe_structure" />
     </div>
   </div>
  </t>
</template>

</odoo>`

**Comment by nehemiascr** [comment]
I am experiencing the same issue, I have a website that works in odoo 9 but it's not working on odoo 11, same same error 
```
AssertionError: Element odoo has extra content: template, line 3
```

my .xml file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<odoo>
   <template name="Home page" id="website.homepage" page="True">
      <t t-call="website.layout">
         <div class="landing">
             ...
         </div>
      </t>
   </template>
</odoo>
```

I have other files that load properly, the only difference with this one is that I am making use of qweb template directives, any help is appreciated :)

**Comment by Yenthe666** [comment]
@mart-e looks like one for you to handle in the docs.

**Comment by nehemiascr** [comment]
I think it may have to do with the [import_xml.rng](https://github.com/odoo/odoo/blob/11.0/odoo/import_xml.rng) file, for instance, [v9](https://github.com/odoo/odoo/blob/9.0/openerp/import_xml.rng) of the file has 
```xml
<rng:optional>
   <rng:attribute name="page"><rng:value>True</rng:value></rng:attribute>
</rng:optional>
```
while [v11](https://github.com/odoo/odoo/blob/11.0/odoo/import_xml.rng) of the same file doesn't.
Still, after deleting the `page="True"` property, still getting the same error.

**Comment by qsm-odoo** [comment]
Hello,

`page="True"` is indeed not the correct way to define pages in 11.0 anymore and will prevent loading `<template/>` data correctly. We should update the doc about that.

In 11.0, website pages have their own model (`website.page`) and are not simple `ir.ui.view` records anymore. To define a page, there are two ways:
```xml
<record id="my_page" model="website.page">
    <field name="name">My Page</field>
    <field name="website_published">True</field>
    <field name="url">/my_page</field>
    <field name="type">qweb</field>
    <field name="key">my_app.my_page</field>
    <field name="arch" type="xml">
        <t t-name="my_app.my_page_template">
             <t t-call="website.layout">
                <!-- ... -->
             </t>
        </t>
    </field>
</record>
```
or:
```xml
<template id="my_page_template">
    <t t-call="website.layout">
        <!-- ... -->
    </t>
</template>
<record id="my_page" model="website.page">
    <field name="name">My Page</field>
    <field name="website_published">True</field>
    <field name="url">/my_page</field>
    <field name="view_id" ref="my_page_template"/>
</record>
```

Both ways are fine. The first one has the advantage to define the page "with one record data" and the second has the advantage of using the `<template/>` shortcut and allows to inherit from this template.

This new model allows to integrate the pages in the page management system which, as you can see, allows some new page features. To name a few: choosing the exact URL you want for your pages (without `/page/`) or choosing if the page is published or not.

cc @rdeodoo @JKE-be

**Comment by Yenthe666** [comment]
Actually quite the same as https://github.com/odoo/odoo/issues/20772 although the other report is not about the documentation.

**Comment by Yenthe666** [comment]
@qsm-odoo I see the docs are still wrong. Did you have time to look at this yet? Even just removing `page=True` in the doc example would already be a neat improvement.

**Comment by qsm-odoo** [comment]
Sorry, I do not have the time to properly do that yet.

**Comment by Yenthe666** [comment]
No problem, we understand that! Best of luck and thanks for the update.

**Comment by OliHall** [comment]
As this is still a live issue, until the documentation is updated, would it be possible to put a small warning in the appropriate place referencing this page? This would stop users who are faithfully following the tutorial from going round in circles trying to work out what they have done wrong when their code doesn't work.

**Comment by gunarssimkuns** [comment]
It's hard to learn because the whole documentation is outdated and copy-pasted from older versions. Please update!

**Comment by Yenthe666** [comment]
@mart-e we should really fix it :(

**Comment by gunarssimkuns** [comment]
```
<record id="services_page_link" model="website.menu">
    <field name="name">Services</field>
    <field name="url">/page/services</field>
    <field name="parent_id" ref="website.main_menu" />
    <field name="sequence" type="int">99</field>
</record>
```
could be
```
<record id="services_page_link" model="website.menu">
    <field name="name">Services</field>
    <field name="url">/services</field>
    <field name="parent_id" ref="website.main_menu" />
    <field name="sequence" type="int">99</field>
    <field name="page_id" ref="services_page" />
</record>
```
otherwise *Services page* will have no *Related Menu Items* under `Website / Pages / Services Page`

**Comment by dcode666** [comment]
Yup - the documentation is still not up-to-date.  The latter portion of the changes mentioned by @qsm-odoo is probably the best fit to leverage the new odoo page feature as well as inherit the template.  Also, an additional record would be needed to include the menu - like shown below (the complete pages,xml as per odoo docs)

    
	<template name="My Page Template" id="my_page_template">
		<t t-call="website.layout">
			<div id="wrap">
				<div class="container">
					<h1>Our Services</h1>
					<ul class="services">
						<li>Cloud Hosting</li>
						<li>Support</li>
						<li>Unlimited space</li>
					</ul>
					
					<div class="oe_structure" />
				</div>
			</div>
		</t>
    </template>
	<record id="my_page" model="website.page">
		<field name="name">My Page</field>
		<field name="url">/my_page</field>
		<field name="view_id" ref="my_page_template" />
	</record>
	<record id="my_page_menu" model="website.menu">
		<field name="name">My_Page</field>
		<field name="url">/my_page</field>
		<field name="parent_id" ref="website.main_menu" />
		<field name="sequence" type="int">99</field>
	</record>

**Comment by Yenthe666** [comment]
Thanks a lot @qsm-odoo!

**Comment by qsm-odoo** [comment]
The part which explains how to create page records has been updated. We will try to keep updating our doc and to add additional details as soon as possible.

**Comment by sombatsombat** [comment]
I think at least a warning at the top of the document could save time for the readers/developers.
