### ISSUE TITLE
[11] messages entered in channel is not shown. need to refresh browser to see the entered messages

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#21242]
Impacted versions: 11 [odoo-11.0.post20171125]

Steps to reproduce: 
login as admin, click on discuss, select #general and type a message.

Current behavior: 
message not shown in the chat window. need to refresh browser to be able to see recent messages

Expected behavior:
messages should appear immediately after sending message.

Video/Screenshot link (optional):

I am using CentOS 7 and nginx and I have Odoo10 and Odoo11 installed in the same machine using venv. Both odoo are having similar .conf. Except the string `odoo11` is replaced with `odoo10`

[options]
db_host = localhost
db_port = False
db_user = odoo11
db_password = odoo11
db_filter = ^odoo11_demo.*$
no_database_list = True
log_level = debug
log_handler = odoo.addons.web.http:DEBUG
logfile= /var/log/odoo/odoo11_demo.log
logrotate = True
addons_path = /opt/odoo11/demo/odoo/odoo/addons
xmlrpc_port = 8069
longpolling_port = 8072
xmlrpc = True
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
proxy_mode = True
workers = 2

If i start odoo10, i have no issue with sending messages. the following is the browser inspection screen:
![odoo10](https://user-images.githubusercontent.com/7699250/33242899-a0739c86-d316-11e7-870b-d1d1d3028cc6.PNG)

However, if i stop odoo10 and start odoo11, the messages i type are not shown and i see the 502 gateway error in inspection:
![odoo11](https://user-images.githubusercontent.com/7699250/33242925-0b8d6ec0-d317-11e7-8f45-cd24e25fd5e9.PNG)
I need to refresh the browser for the messages to appear.

I have tried runbot for odoo11 but it does not have the problem that i encounter.

Shouldn't be problem with nginx as it works with odoo10. 

There are no errors in odoo11 logfile. I can login and install apps with odoo11.

However, i noticed that runbot for odoo11 has additional parameter `im_livechat_history` in request header :
![odoo11runbot](https://user-images.githubusercontent.com/7699250/33243161-a0781bc6-d31b-11e7-83df-76339c2c05ec.PNG)

It's weird that i get the following nginx error from using odoo11 but not when using odoo10:

> 2017/11/27 13:13:02 [error] 27217#0: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.8, server: 192.168.1.110, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://127.0.0.1:8072/longpolling/poll", host: "192.168.1.110", referrer: "http://192.168.1.110/web"

Did i miss out any configuration for Odoo11 ?

**Comment by peterhoth** [comment]
1. Disable nginx
2. Change config file:
```
[options]
db_host = localhost
db_port = False
db_user = odoo11
db_password = odoo11
db_filter = ^odoo11_demo.*$
no_database_list = True
log_level = debug
log_handler = odoo.addons.web.http:DEBUG
logfile= /var/log/odoo/odoo11_demo.log
logrotate = True
addons_path = /opt/odoo11/arcpos/odoo/odoo/addons
xmlrpc_port = 8069
longpolling_port = 8072
workers = 2
```
3. run odoo11 as a service. No more 502 error but `Exception: bus.Bus unavailable` generated
![image](https://user-images.githubusercontent.com/7699250/33441178-0364430e-d62d-11e7-81d8-2cd37a24d332.png)

**Comment by Yenthe666** [comment]
@mart-e do you have any idea? I believe the issue is local and not in Odoo itself though.

**Comment by peterhoth** [comment]
I just did another fresh install:
- CentOS Linux release 7.4.1708
- Postgresql 9.2.23
- Python 3.5.4
- Odoo 11 [odoo-11.0.post20171204]
- Firewall allow for ports 8069 and 8072
- Created a service to run odoo11 with the following configuration
```
odoo.conf setting
[options]
db_host = localhost
db_port = False
db_user = odoo11
db_password = odoo11
log_level = debug
log_handler = odoo.addons.web.http:DEBUG
logfile= /var/log/odoo/odoo11_demo.log
logrotate = True
addons_path = /opt/odoo11/demo/odoo/odoo/addons
xmlrpc_port = 8069
longpolling_port = 8072
```
typed message in channel appears immediately maybe because workers=0 ?

When i change the configuration to add this line :
```
:
workers = 2
```
typed message does not appear. (same problem as reported)

The service status is : 
```
● odoo11demo.service - Odoo 11 ERP instance
   Loaded: loaded (/etc/systemd/system/odoo11demo.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-04 17:58:57 +08; 29min ago
  Process: 21621 ExecStart=/bin/bash -c cd /opt/odoo11/demo; source bin/activate; odoo/odoo-bin -c odoo11demo.conf & (code=exited, status=0/SUCCESS)
 Main PID: 21625 (python3)
   CGroup: /system.slice/odoo11demo.service
           ├─21625 python3 odoo/odoo-bin -c odoo11demo.conf
           ├─21627 python3 odoo/odoo-bin -c odoo11demo.conf
           ├─21628 python3 odoo/odoo-bin -c odoo11demo.conf
           ├─21629 /opt/odoo11/demo/bin/python3 odoo/odoo-bin gevent -c o...
           ├─21630 python3 odoo/odoo-bin -c odoo11demo.conf
           └─21631 python3 odoo/odoo-bin -c odoo11demo.conf

Dec 04 17:58:57 hawoonku.arcpos.com systemd[1]: Starting Odoo 11 ERP instance...
Dec 04 17:58:57 hawoonku.arcpos.com systemd[1]: Started Odoo 11 ERP instance.
Hint: Some lines were ellipsized, use -l to show in full.
```
There is an error from Odoo log : 
```
2017-12-04 09:59:13,488 21628 ERROR odoo11_demo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11/demo/odoo-11.0.post20171204/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11/demo/odoo/odoo/addons/bus/controllers/main.py", line 37, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
2017-12-04 09:59:13,490 21628 INFO odoo11_demo werkzeug: 192.168.1.8 - - [04/Dec/2017 09:59:13] "POST /longpolling/poll HTTP/1.1" 200 -
2017-12-04 09:59:13,495 21627 INFO odoo11_demo werkzeug: 192.168.1.8 - - [04/Dec/2017 09:59:13] "POST /web/action/load HTTP/1.1" 200 -
```

**Comment by peterhoth** [comment]
I re-installed a fresh server with Odoo 11 and the channel message seems to be working. I will do further test on my side to find out the cause. I will close this issue for now. Thanks.

**Comment by szegc** [comment]
@peterhoth ，i encountered the same issue, did you find out the root cause?

**Comment by robotiko** [comment]
This might help.
In case that working in a proxy/ssl environment,  it looks like it need different config.
https://www.odoo.com/forum/help-1/question/odoo-10-ce-chat-is-not-refreshing-on-ssl-connection-118876
