### ISSUE TITLE
call to non existent service_name in reports

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21244]
Impacted versions: 11.0

Steps to reproduce:
I was trying to implement a custom text report, I'm sure there are other things wrong here, but the bug is obvious so I'll just put code here.

In web/controllers/main.py grep "dispatch_rpc('report'" - line 1511 is one

NOTE: First argument of dispatch_rpc is service_name - so in this case we send 'report'
Now check dispatch_rpc in http.py and you will see
```python
        if service_name == 'common':
            dispatch = odoo.service.common.dispatch
        elif service_name == 'db':
            dispatch = odoo.service.db.dispatch
        elif service_name == 'object':
            dispatch = odoo.service.model.dispatch
        result = dispatch(method, params)
```

Current behavior: Traceback
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "PycharmProjects/odoo10-c/odoo/addons/web/controllers/main.py", line 74, in wrap
    return f(*args, **kwargs)
  File "PycharmProjects/odoo10-c/odoo/addons/web/controllers/main.py", line 1511, in index
    action["report_name"], report_ids, report_data, context])
  File "PycharmProjects/odoo10-c/odoo/odoo/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
UnboundLocalError: local variable 'dispatch' referenced before assignment

```

Expected behavior: Honestly I have no idea.  Text reports were simple in v10 using qweb.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sle-odoo any clue?

**Comment by mduvergey** [comment]
The 'report' service seems to have been removed in version 11. I tried to find another way to generate reports using the API but found none...

**Comment by gdgellatly** [comment]
@mduvergey Thats not really relevant to this bug report and is well known.  This is about the UI and traceback raised if you add a report action where the report_type isn't qweb-pdf or qweb-html.  

But it is trivial now to render reports without the service for those 2 report types.  You just call render from ir.actions.report with the ids, or else make a web call to the endpoint.

**Comment by gdgellatly** [comment]
@sle-odoo @Yenthe666 Note this is not urgent or a priority for me, but it seems it is left over code in both the js side of webclient and python that was ultimately replaced by the ReportsController class.  Its a ton more effort to add a ReportController route converter override and create new js actionmanager code, but its done now.

**Comment by sle-odoo** [comment]
@aab-odoo we talked about the js part yesterday, as you're cutting on leftover code there maybe this issue will be of interest to you

**Comment by jeroen7s** [comment]
any guide on how to do this in odoo11?

**Comment by pedrobaeza** [comment]
Is this still relevant?
