### ISSUE TITLE
float_round of 3.0 breaks with precision at 5 - and can break Odoo test suite of sale_stock

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#21246]
Impacted versions:

**11.0**

Steps to reproduce:

Install a new db with demo data, and sale_stock module.  Set rounding for product unit of measure from 3 to 5.  Run sale_stock tests (from command line with --test-enable)

Current behavior:

> FAIL: test_02_sale_stock_return (odoo.addons.sale_stock.tests.test_sale_stock.TestSaleStock)
> 
> AssertionError: 3.0000000000000004 != 3.0 : Sale Stock: delivered quantity should be 3.0 instead of "3.0000000000000004" after picking return
> 

At the lowest level, it appears that float_round is called by  convert_to_cache.

- **float_round(3.0, precision_digits=x) == 3.0**, if x is 1, 2, 3, 4, 6, 7, 8, 9, 10
- **float_round(3.0, precision_digits=5) == 3.0000000000000004**

**Comment by richard-willdooit** [comment]
@odony @qdp-odoo @gdgellatly @Yenthe666

**Comment by richard-willdooit** [comment]
` self.assertEqual(self.so.order_line[0].qty_delivered, 3.0, 'Sale Stock: delivered quantity should be 3.0 instead of "%s" after picking return' % self.so.order_line[0].qty_delivered)

Could we get that to somehow use float_compare instead of equal???

**Comment by Yenthe666** [comment]
Hmm alternatively this is something for @nim-odoo or for @xmo-odoo

**Comment by odony** [comment]
@richard-willdooit sure, did you want to make a PR for this small change? ;-)

**Comment by nim-odoo** [comment]
Maybe use AlmostEqual :)

**Comment by Yenthe666** [comment]
Official Odoo ticket number is 803837.
