### ISSUE TITLE
'TypeError: cannot marshal None unless allow_none is enabled' when 'process' called for a 'stock.immediate.transfer'

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#21264]
I'm using `Odoo 10.saas~14+e (Enterprise Edition)`. When I call `process` on a `stock.immediate.transfer` via the XMLRPC api, I get the following error response:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-14/odoo/service/wsgi_server.py", line 57, in xmlrpc_return
    response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False, encoding=None)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
```

This is the same issue that I reported previously for a `sale.order` in issue #19889. The error is a result of there being no return value for the `process` method:

https://github.com/odoo/odoo/blob/saas-14/addons/stock/wizard/stock_immediate_transfer.py#L22

Can this be fixed?

**Comment by mart-e** [comment]
Hello,

> I'm using Odoo 10.saas~14+e (Enterprise Edition).

You know that is a bad idea, right? This version is not officially supported.
As this one is easy, no problem to merge your PR but to be sure you are aware 😉

**Comment by flyingL123** [comment]
Nope I had no clue this was a bad idea. I am an Odoo online user, not on-premise. When I created a new database through the Odoo UI, this was the version that I was given. I didn't have a choice.

Anyway, thanks for merging and for the information.

**Comment by mart-e** [comment]
Oh right, I understood you were on premise :)
We ensure migrations for our online customers, don't worry about it.
Thanks for the patch
