### ISSUE TITLE
Automated next activities 

### ISSUE THREAD

**Issue by est-odoo** [odoo/odoo#21268]
Dear Odoo Partners, 

We're currently working on our Next Activities tool. The main idea of the specification is adding automated activities to help users in their daily work. 

What we would like to implement: 
- A feature to add a reminder for yourself (not related to an object, it's only a kind of to do list) 
- Some automated activities that will remind you the next step on your documents: for example, a manager will receive a Next Activity when he has to approve a leave request from one of his employee. 

You can see a quick prototype here: 
https://invis.io/YNE0NV8V6 

In order to cover our user's needs, we would like to gather some feedback: 
what kind of Next Activities would be useful for you and what would be your use case?

Thanks in advance for your help, 
Eloïse Stilmant 
Product Owner @ Odoo

**Comment by hirenraval77** [comment]
Hello,
in the accounting side need to add the separately realized and un realized  forex exchange gain loss as well as forex re valuation process.

also  there should be a functionality where in the multi currency we should able to get the partner ledger in both currency local as well foreign currency.

thanks,
Hiren

**Comment by fmdl** [comment]
Hi Eloïse

Next activities, is very great ! 

**Notifications**
Today, the main issue that there no notifications when you receive a new activity. A badge like with iPhone or the list of notification is way to use a lot the Next Activities.
I have made a module to see the next activities when you start odoo:
![image](https://user-images.githubusercontent.com/16716992/33287730-eedc3bfa-d3b9-11e7-9f4b-9a076b6d4e0e.png)
PS : I have still an issue with the CSS ...

**Manager validation**
A "Tinder" like validation system :
For a manager it could be longer to validate lot of things (invoice, creation of partner, ...). An system like this could be great:
- I click on "I would like validate some stuff"
- I see the first, Click on "Agree" or "Refuse" (+ why)
- Then I see the second
- ...

**Work Flow**
In big enterprise, when you create some things, it could be validate from multi department. An system of workflow activities like this could be great.
- Creation of Partner by an user
- Next :  Next Activity for the manager : "Validate the partner"
- Next : Next activity for the accountant : "Validate the bank data"
- Next : Next activity for the project manager : "Add project"
- ...

Thanks

**Comment by est-odoo** [comment]
@hirenraval77 Thanks for your feedback, for general accounting Feedback you can check this issue, created by my colleague Laura Piraux (LAP): https://github.com/odoo/odoo/issues/18637 : ) 

@fmdl Thanks it's indeed a good Feedback, we'll take this into account during our reflection,  
and good luck with your CSS! : )

**Comment by fmdl** [comment]
Hi @est-odoo 

Some models have "next activities", but there are no filters to use correctly, for exemple products need filter : find this PR to fix that : https://github.com/odoo/odoo/pull/21237. Maybe there are other models in same case.

ERPNext use already badge notification:
![image](https://user-images.githubusercontent.com/16716992/34157894-bed120a4-e4c3-11e7-8548-5f67d79a5372.png)

Regards

**Comment by fmdl** [comment]
@est-odoo one more thing : some model have not icon (product, contact, invoice, ...), and the system to find the icon is not the best, it could me great to add the link of icon in the definition of model :

```
Class AccountMove(Models.model):
    _name = 'account.move'
    _icon = 'accounting/static/img/account.png'
```

Thanks

**Comment by jusle** [comment]
Hello @est-odoo  

I think it should be integrated with project management. If planned and/or delivered hours of tasks linked to a sale order line exceeds ordered quantity (hours), activity should be created for the salesperson of SO to upsell.
