### ISSUE TITLE
[10.0/11.0] Can not edit Sequence (Traceback on Screen)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#21267]
Impacted versions: 10.0/11.0

Steps to reproduce: go to [http://281537-11-0-12c7d3.runbot8.odoo.com](http://281537-11-0-12c7d3.runbot8.odoo.com/web?debug=1?#id=12&view_type=form&model=ir.sequence&menu_id=38&action=22) --> Settings --> Sequences --> 'Account reconcile sequence'

Current behavior: Traceback during Saving record

![](https://image.prntscr.com/image/G4x_oq6xQr2HduZQiUPDdA.png)

Change Implementation to Standard and Save the record.

![](https://image.prntscr.com/image/cv0b3Pq9SzW0Dya-zZ4cyA.png)
Expected behavior: Should Save the record

Video/Screenshot link (optional):

**Comment by rruebner** [comment]
@Yenthe666 I can confirm the issue.

**Comment by Yenthe666** [comment]
Thanks for the report and the confirmation guys.
@qdp-odoo is for the accounting sequence. Couls you check?

**Comment by qdp-odoo** [comment]
actually, it is not related to the accounting, but it's generic to all sequences...

**Comment by Yenthe666** [comment]
Hmm yeah I wasn't sure how to handle it. I guess it is framework and as it is about sequences it might be @odony - he has done some changes to it recently.

**Comment by sswapnesh** [comment]
@Yenthe666 It is not due to any recent changes I believe, I can reproduce same on [8.0](http://283354-8-0-837bd7.runbot9.odoo.com/web#id=11&view_type=form&model=ir.sequence&menu_id=38&action=21) and [9.0](http://283628-9-0-62fcf6.runbot13.odoo.com/web?debug#id=276&view_type=form&model=ir.sequence&menu_id=37&action=21)

**Comment by odony** [comment]
As the error indicates, you can't create/alter a sequence to make it generate "0" as the first number for a "Standard" sequence. We should add a constraint to provide a more user-friendly message. ([PR welcome](https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests) ;-))
@sswapnesh  If you change the "Next number" to 1 it should work, and that's probably what you want, too :-)

**Comment by Yenthe666** [comment]
Ohhhh... right, that makes sense. Wow, that indeed just needs a little user-friendly message. 😆 :man_facepalming:

**Comment by wtaferner** [comment]
@Yenthe666 
Are you heading for this? if you do change the default of the field to 1 as well ;-)

**Comment by wtaferner** [comment]
@odony 
Yenthe is not going to make it so I will do this little PR for you guys...would you accept the user message and the new default in 10.0 or should I target 11.0?

**Comment by sswapnesh** [comment]
@odony @Yenthe666 It won't work If I change it to 1 as well.It is taking value from `number_next` (it will be 0 in this case) not `number_next_actual`

To resolve this I must save it with value 1 and then change it to Change Implementation to Standard.

**Comment by nim-odoo** [comment]
Closed from v9 in 30d0861f0a9c9079c3c2222ca6d1b2a2e33469c2

**Comment by Yenthe666** [comment]
Thanks @nim-odoo - great job!

**Comment by sswapnesh** [comment]
Hello @nim-odoo , @Yenthe666 

Still, we need to manage the same situation in for Sequence [based on date range](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_sequence.py#L330).

Just tested on [Runbot](http://286140-10-0-1022e4.runbot8.odoo.com/web?debug#id=12&view_type=form&model=ir.sequence&menu_id=38&action=22)


![](https://image.prntscr.com/image/62i_R2kCTLuTjZVMYALCdg.png)


![](https://image.prntscr.com/image/y1sao3_ySnSv44ycHGpOBw.png)

**Comment by sswapnesh** [comment]
@nim-odoo Can I make PR for this?
