### ISSUE TITLE
Website_forum - error if karma_flag is less than karma_edit_all

### ISSUE THREAD

**Issue by KurtHaselwimmer** [odoo/odoo#21274]
Impacted versions: All

Steps to reproduce: Set karma_flag to 200 so that it is less than the default value of karma_edit_all of 300. Then create a user and set his karma to 201. Log in as that user and try flagging a post or an answer from another user

Current behavior: error 403 is produced 

..Log...
File "/odoo/odoo-server/addons/website_forum/models/forum.py", line 628, in flag 'flag_user_id': self.env.user.id, File "/odoo/odoo-server/addons/website_forum/models/forum.py", line 491, in write raise KarmaError('Not enough karma to edit a post.') odoo.addons.website_forum.models.forum.KarmaError: 403 Forbidden: Not enough karma to edit a post.

Expected behavior: The ability to flag another users (possibly offensive) post should be determined only by the level setting of karma_flag. 

Furthermore it should not be a requirement for the user to have the ability to edit anyone else's posts (very dangerous) simply to have to ability to flag one of their posts so that moderators can make an assessment later - this would be a fairly standard feature that should be available to pretty much all forum users.

**Comment by Yenthe666** [comment]
@JKE-be this is one for you. 😉

**Comment by KurtHaselwimmer** [comment]
It has been more than two weeks since I pointed out this problem - is this being looked at ?

**Comment by Yenthe666** [comment]
Hi @KurtHaselwimmer,

Bug reports on Github are on a best effort basis. If you have an enterprise license you can report it through the official channel too.

Regards,
Yenthe

**Comment by KurtHaselwimmer** [comment]
I do have an enterprise license but have not idea what the official channel is

**Comment by Yenthe666** [comment]
@KurtHaselwimmer you can do this from https://www.odoo.com/help
