### ISSUE TITLE
[BUG] ir.model.field : manual create with inherit model doesn't set the good type 

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#21275]
Impacted versions:
Master, 11, 10 (maybe 9)

Steps to reproduce:
- go to Technical/Fields
- create a new field on `product.template`
- save

The system create automatically a field in `product.product` model, but the type is "Base" instead "Custom field".

![image](https://user-images.githubusercontent.com/16716992/33284825-a648c04c-d3b0-11e7-88dd-13e892ea9192.png)

**Comment by Yenthe666** [comment]
@mart-e for you.

**Comment by rco-odoo** [comment]
@fmdl I agree that it seems buggy, but making it a custom field would be worse.

The point is: the field on `product.product` is **inherited**, and its definition may **not** be changed.  In particular, one cannot remove the inherited field from `product.product`.  So, making the inherited field look like any custom field would open the door to configuration nightmares.  Making the field look like a "Base field" prevents users from screwing up their models.

So the situation is not as bad as it seems... :neutral_face:

**Comment by mreficent** [comment]
And what do you think of changing that view to show the `type` as "Inherited from Custom Field"?

**Comment by mart-e** [comment]
> And what do you think of changing that view to show the type as "Inherited from Custom Field"?

In master, we could add a new field type "inherited". For stable we won't change the behaviour.

**Comment by fmdl** [comment]
Solve by : https://github.com/odoo/odoo/pull/25135

**Comment by Bedo1212** [comment]
I created a product manually , it seems that i can never use it in import anywhere the import module doesn't find the ID although i get the ID using the export in the first place :)
