### ISSUE TITLE
Issue in many2many without widget specified when loading records from onchange and saving. 

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#21285]
Impacted versions:10.0

Steps to reproduce:Add a many2many field in the view.(say Products). Don't specify the widget many2many_tags or similar widgets. Then from a onchange load records to this many2many(say when changing product template, load its products). Then click save. Boom!!Everything loaded from onchange disappears. Upon checking the data coming to the create method, I found that many2many data loaded from onchange is coming in the format [(1,ID,dict_with_fields_listing_in_the_view)] and not in [(6,0,list_of_ids)]

Current behavior: Many2many records are loaded at onchange but on saving, it disappears.

Expected behavior: records should be successfull saved.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Related to #14761

**Comment by Yenthe666** [comment]
Dear @omalbastin,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
