### ISSUE TITLE
[10.0EE]Cannot import company_type field in Enterprise

### ISSUE THREAD

**Issue by elicoidal** [odoo/odoo#21295]
Impacted versions:
10.0EE
Steps to reproduce:
1. Demo database
2. Go to Sales / Sales / Customer
3. List view / select Agrolait
4. More / Export, select field Company Type
5. In Excel change field value from Company to Individual
6. Import the file back in Odoo
Current behavior:
The field Company Type is still Company for Agrolait
Expected behavior:
The field Company Type should be Individual
(NB: in CE the behavior is correct)
Video/Screenshot link (optional):

**Comment by yostashiro** [comment]
I guess this is related to https://github.com/odoo/odoo/issues/20623.

**Comment by elicoidal** [comment]
Solved with newest code
