### ISSUE TITLE
odoo有DTD文件么 

### ISSUE THREAD

**Issue by jalena** [odoo/odoo#21291]
I am now using pycharm development Odoo，and I'm a programmer from JAVA。。

In JAVA development, I use the DTD as IDE code hints.

I now know that Odoo uses RNG files as xml validators.

Will Odoo have provided tips to pycharm tool it.

Thank you!

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
