### ISSUE TITLE
le play store

### ISSUE THREAD

**Issue by benmbark** [odoo/odoo#21307]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @benmbark,

Please do add more information to a bug report then just a title.
We really can't help you like this. Feel free to create a new and more detailed report.

Regards,
Yenthe

**Comment by benmbark** [comment]
sorry i added this issue by error
