### ISSUE TITLE
[10.0e] TaxCloud error: The destination zip must be 5 numbers

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#21309]
**Impacted versions:** 10.0e (TaxCloud module)

**Steps to reproduce:**
1. Create customer with 9 digit zip code (address must be invalid according to USPS)
1. Create and confirm a sales order with this customer

Here's a sample address, which is valid with most carriers, but not with the USPS:
> 314 State Highway 10
> Walsenburg, Colorado, 81089-9525

**Current behavior:**
An error message is returned from the TaxCloud Lookup api:
> The destination zip must be 5 numbers (810899525)

**Expected behavior:**
In the ```verify_address``` method, Odoo should set the 5 digit portion in the Zip5 field and the 4 digit portion in the Zip4 field.

**Current code:**
```python
    "Zip5": re.sub('[^0-9]', '', partner.zip or ''),
    "Zip4": ""
```
**Suggested code:**
```python
    "Zip5": len(partner.zip or '') >= 5 and partner.zip[:5] or '',
    "Zip4": len(partner.zip or '') >= 9 and partner.zip[-4:] or '',
```
Or, if we need to ignore leading and trailing garbage, then maybe something like this:
```python
    "Zip5": re.match(r"^\D*(\d{5})", partner.zip or '') and re.match(r"^\D*(\d{5})", partner.zip or '').group(1),
    "Zip5": re.match(r"^\D*(\d{5})\D*(\d{4})", partner.zip or '') and re.match(r"^\D*(\d{5})\D*(\d{4})", partner.zip or '').group(2)
```
Or more efficiently like this:
```python
zip_match = re.match(r"^\D*(\d{5})\D*(\d{4})?", partner.zip or '')
zips = zip_match and list(zip_match.groups()) or []
...
    "Zip5": zips and zips.pop(0) or '',
    "Zip4": zips and zips.pop(0) or '',
```

**Comment by vcloud9ray** [comment]
I also have this issue and have had to tell my Customers to not use ZIP+4 - which is not desirable.  @matt454357 - did you log this with Odoo support with an Enterprise Contract# so it can get higher up on the list of Issues?

**Comment by taxcloud** [comment]
Agreed. Plus4 zip code extensions should be passed in using the zip4 parameter. ;)

**Comment by matt454357** [comment]
@vcloud9ray,
I just submitted a support ticket.

**Comment by vcloud9ray** [comment]
@matt454357 :thumbsup:

**Comment by Yenthe666** [comment]
@tivisse we have another TaxCloud issue to handle. This'll probably end up at you through the ENT ticket I guess.

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/enterprise/commit/53365366a0d625bd606070a6fb75ceeb80db33b4
