### ISSUE TITLE
Cannot change attribute decoration-* on tree

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#21316]
Impacted versions: 10

Steps to reproduce:
```
<record model="ir.ui.view" id="view_hr_holidays_tree_inherit">
	<field name="name">hr.holidays.tree.inherit</field>
	<field name="model">hr.holidays</field>
	<field name="inherit_id" ref="hr_holidays.view_holiday_simple"/>
	<field name="arch" type="xml">
		<xpath expr="//tree" position="attributes">
			<attribute name="decoration-info">state=='confirm'</attribute>
		</xpath>
        </field>
</record>
```

Current behavior: tree color still black (default) when state == 'confirm'

Expected behavior: tree color should be colored like "decoration-info color"

**Comment by gdgellatly** [comment]
You definitely can - see

https://github.com/odoo/odoo/blob/e56d91be29bdd7baca0bf003db8bc50e8ea7b3c3/addons/stock/views/product_views.xml#L29

and

![image](https://user-images.githubusercontent.com/5093264/33369610-ee761888-d559-11e7-9eb2-84dcdd5387cd.png)

**Comment by sswapnesh** [comment]
Hello @CakJuice 
Could please try this?

```
<xpath expr="//tree" position="attributes">
       <attribute name="decoration-info">"state=='confirm'"</attribute>
</xpath>

```


![](https://image.prntscr.com/image/DDrmNJ5uTq2RnoSaRilAfA.png)

**Comment by CakJuice** [comment]
@gdgellatly @sswapnesh thanks for your help. today i was updated my odoo then my code works normally. maybe there is any bug in my previous version.
i still use code:
'''
<xpath expr="//tree" position="attributes">
	<attribute name="decoration-info">state=='confirm'</attribute>
</xpath>
'''

**Comment by Gelson15** [comment]
I want to display data in my inherited tree view, but I'm not getting it as I can do it, thanks.

**Comment by Gelson15** [comment]
I would like to know how to use the metpath xpath to add a field in my tree view could anyone help me please

**Comment by Gelson15** [comment]
I would like to know how to use methos xpath to add a field in my tree view could anyone help me please

**Comment by Gelson15** [comment]
![screenshot from 2018-09-19 11-38-10](https://user-images.githubusercontent.com/41471156/45773415-65ac2500-bc31-11e8-86b8-dcf9cb416382.png)

**Comment by Gelson15** [comment]
Hi everyone, I'm new to odoo development, I'm looking for a help, I have this client field, I want it when I polish my client I want to populate the following tree automatically with some data from the client table, I'll be very grateful for any answer
![screenshot from 2018-09-19 17-29-34](https://user-images.githubusercontent.com/41471156/45774267-b15fce00-bc33-11e8-8329-4ef1a5cb06ab.png)

**Comment by CakJuice** [comment]
@Gelson15 can you send your model & view code to my email? maybe I can help you

**Comment by sswapnesh** [comment]
@Gelson15  Please do not ask for  this type of help  in Github. You should use Forum instead.
