### ISSUE TITLE
[10.0e] subscription plan change does not take quantity from original subscription

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#21312]
### Impacted versions:

10.0 Enterprise

### Steps to reproduce:

- Install website_contract
- Create two subscription templates **with different products**, both with quantity 1 with the same plan change tag.
- Create a subscription for a template for quantity 2.
- Change plans in frontend through My Account > Your Contracts > (select the subscription) > (click on "Change plan" button) > (select the other subscription template).

### Current behavior:

Quantity of the subscription line is overridden by the quantity of the template, which is 1.

### Expected behavior:

Quantity of the original subscription line should prevail.

### Video/Screenshot link (optional):

EDIT: The assumption here is that the subscription templates are created with different products.  The issue does not reproduce when the templates share the same product.

**Comment by yostashiro** [comment]
If the behavior is as intended, I'd like to know the rationale behind it.  Not sure what business scenario the current design has in mind.

**Comment by yostashiro** [comment]
OPW-785532

**Comment by Yenthe666** [comment]
@yostashiro did you get feedback on the OPW and is this solved?

**Comment by yostashiro** [comment]
@Yenthe666 The OPW ticket was closed and I didn't get a clear explanation on the design rationale.

Me: You say it is a generic behavior but you do not even have a single use case to back it up. We normally consider such case as a defect in design, which in broader sense should be a bug.

Odoo: I am just a contact here between you and the usability team. I have reported your feedback and they will analyze it.

**Comment by yostashiro** [comment]
To supplement my previous comment, Odoo seemed to have no intention to fix the issue for 10.0, and they hinted that the issue does not exist in 11.0, which I haven't checked.  I will report back when I get around to check the behavior in 11.0, but I am OK if this issue is closed here.

**Comment by Yenthe666** [comment]
Thanks for the feedback! I'll close it for now and if you have the same issues in V11 or V12 we can reopen it. Just let me know.
