### ISSUE TITLE
Odoo 10 Installation Menu not display Bug

### ISSUE THREAD

**Issue by khoapn102** [odoo/odoo#21319]
Impacted versions: 10.0

Steps to reproduce:
- Install Odoo 10 Nightly Builds
- Open Odoo on Chrome

Current behavior:
    - No menu display, JS display Error:  `Refused to execute script from: http://localhost:8069/../web.assests common.js because its MIME type ('text/plain') is not executable, and strict MIM type checking is enabled`

Expected behavior:
    - display and work normally

Video/Screenshot link (optional):
![sample](https://user-images.githubusercontent.com/22443720/33368054-1b9c04e4-d523-11e7-81fa-4fde14129d5f.png)

However, there is a temporary solution in Help Forums. I would want to have the bug fixed permanently in Odoo 10.0. 
Solution is: 
- Use PgAdmin then type `select * from ir_attachment where mimetype ='text/plain' and datas_fname like '%.js';` and  Change the value of the mimetype field: text/plain to text/javascript. Clear cache and it works. 
- link to Temp. Solution: [Solution](https://www.odoo.com/forum/help-1/question/odoo-10-no-menu-displayed-117432)

I would want to report this bug and share with everybody.

**Comment by d-fence** [comment]
@khoapn102  May I ask you if are using Windows as operating system ?
A fix was made for 11.0 here: https://github.com/odoo/odoo/commit/77ca51f0892ec62d357e099d5c2a91e580e35383

**Comment by khoapn102** [comment]
any patch for Odoo 10.0 ?

**Comment by mkchx** [comment]
@d-fence Thanks for pointing the fix, i used it successfully in odoo 10.

**Comment by d-fence** [comment]
Fixed here: 17c9208889d91d4302797d8f72a6ebc4968ff2e4
