### ISSUE TITLE
[11.0] write off in payment from invoice, when the amount to payment is higher than of amount due from invoice

### ISSUE THREAD

**Issue by ernesto-telematel** [odoo/odoo#21330]
**write off in payment from invoice, when the amount to payment is higher than of amount due from invoice**
Impacted versions:
- 11.0 

Steps to reproduce:
 1.- Create a new customer invoice or supplier invoice.
 2.- Added a product and set the field unit price=10 and remove the taxes of invoice line.
 3.- Save and validate the invoice.
 4.- Into invoice, register a payment with amount 12, and select the option "Mark invoice has fully paid".
 5.- Select any account for send the writeoff amount and validate.

Current behavior:
Show a warning message, with the following text: " Wrong credit or debit value in accounting entry !"

Expected behavior:
the register of payment should be successful, and create a new journal item for difference of amount of the payment.

Video/Screenshot link (optional):

**Comment by ernesto-telematel** [comment]
Hello @fpodoo,
is possible send this issue to OPW from here?, If this is possible, what are the next steps?

Regards

**Comment by Yenthe666** [comment]
Hi @ernesto-telematel,

If you have an enterprise license you can create a ticket at https://www.odoo.com/help and add the link to this bug report in the ticket.

Regards,
Yenthe

**Comment by gbhadolfo** [comment]
Hello, it worked for me doing the replacement of version 11 code, from lines 564 to 567, in this file
/addons/account/models/account_payment.py:

            if counterpart_aml['debit'] or writeoff_line['credit']:
                counterpart_aml['debit'] += credit_wo - debit_wo
            if counterpart_aml['credit'] or writeoff_line['debit']:
                counterpart_aml['credit'] += debit_wo - credit_wo

by following, from version 10:

            if counterpart_aml['debit']:
                counterpart_aml['debit'] += credit_wo - debit_wo
            if counterpart_aml['credit']:
                counterpart_aml['credit'] += debit_wo - credit_wo

I do not know if the change is correct, considering other features in version 11.

**Comment by Yenthe666** [comment]
@qdp-odoo what do you think about the proposed changes?

**Comment by lap-odoo** [comment]
@ernesto-telematel Hello, are you still able to reproduce that issue ? I've just tested it on runbot version 11 and it seems to work fine : https://drive.google.com/file/d/1X1SyfFZZeczrDDYO35KEGBrEUXtg0zrG/view.

**Comment by gbhadolfo** [comment]
Thanks for the answer Ernesto, a separate question, which is the Chrome
extension used to record the video saved in
https://drive.google.com/file/d/1X1SyfFZZeczrDDYO35KEGBrEUXtg0zrG/view

Greetings, Adolfo

2018-02-28 7:45 GMT-03:00 Laura Piraux <notifications@github.com>:

**Comment by qdp-odoo** [comment]
whaaaat?

@gbhadolfo man, if you have the opportunity to ask only a single one question to a girl, I'd suggest any but this one...

**Comment by gbhadolfo** [comment]
Oops, sorry, I got confused. Thanks for the response Laura.

2018-02-28 17:37 GMT-03:00 De Paoli Quentin <notifications@github.com>:
