### ISSUE TITLE
[REF] point_of_sale: avoid relating order with not complete invoice

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#21335]
Impacted versions:
10.0

Steps to reproduce:
On point of sale module:
- Create automated action on update pos.order, and for paid orders. This action execute a server action who (for example) validate invoice related with the order.
- In a new session create one order without invoice.
- From the order view try to invoice the order.

Current behavior:
![captura de pantalla de 2017-11-29 20-24-16](https://user-images.githubusercontent.com/19410285/33406472-7be39504-d543-11e7-9e9e-650ba7cbe6f8.png)

Expected behavior:
Invoice order and run server action with complete invoice.

Video/Screenshot link (optional):

**Comment by GavyMG** [comment]
Possible solution https://github.com/odoo/odoo/pull/21334

**Comment by mart-e** [comment]
Hello,

Sorry but this seems to be an issue with your server action that does not handle this scenario properly, not with Odoo core code.
