### ISSUE TITLE
[11.0] Bad addons path in conf makes server not to load assets

### ISSUE THREAD

**Issue by lionel-deglise** [odoo/odoo#21351]
Impacted versions:
Odoo 11.0 community

Steps to reproduce:
Give invalid addons path in odoo.conf (ex: non existent directory)

Current behavior:
Serveur start, no error logged but nos assets can be retreived from browser (even database manager). We get HTTP 404 status for JS, CSS and IMG (log as INFO, no other log or stacktrace)

Expected behavior:
- An error is logged 
- Server starts
- Assets can be retrieved

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo could you have a look?

**Comment by Yenthe666** [comment]
On a sidenote: it seems to work fine out of the box on V11 ENT.
Probably relevant to @JKE-be too.

**Comment by JKE-be** [comment]
I cannot reproduce.

```bash
~/src/odoo/odoo [11.0|✔]$ vim ~/.odoorc 
~/src/odoo/odoo [11.0|✔]$ ./odoo-bin openerp-dev 
Traceback (most recent call last):
  File "./odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/home/odoo/src/odoo/odoo/odoo/cli/command.py", line 51, in main
    for module in get_modules():
  File "/home/odoo/src/odoo/odoo/odoo/modules/module.py", line 408, in get_modules
    plist.extend(listdir(ad))
  File "/home/odoo/src/odoo/odoo/odoo/modules/module.py", line 401, in listdir
    for it in os.listdir(dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/src/odoo/xenterprise'

```

Please provide more information

**Comment by chris001** [comment]
@JKE-be @ged-odoo @Yenthe666 
Easy solution to this bug: you catch the python `FileNotfoundError`, and continue to the next directory in `addons_path`.  It shouldn't crash that way.  Does linux kernel crash when one of the directories in `PATH` doesn't exist? Nope, it goes past it and continues to the next directory.

**Comment by Yenthe666** [comment]
@JKE-be and @ged-odoo any update on this one?

**Comment by JKE-be** [comment]
As explain previously...

It crash on my pc andthe owner of this issue never reply about the ‘how to reproduce’

**Comment by lionel-deglise** [comment]
Sorry for the delay,

Try to put /donotexist in addons_path of odoo.conf.
Result is attached.
![screenshot 2018-05-03 09 39 55](https://user-images.githubusercontent.com/19615637/39564877-34811046-4eb6-11e8-8f59-f5efb686c371.png)
![screenshot 2018-05-03 09 38 44](https://user-images.githubusercontent.com/19615637/39564878-34aa1f36-4eb6-11e8-88e3-e68fc2a18b2b.png)

**Comment by ErMaqui** [comment]
I've detected the same behavior on Odoo 12 (dockerized). If you put a nonexistent route on addons_path, server starts but got 404 on every asset who try to load. Even if you put the "general" addons path on the config, they continue giving 404.
