### ISSUE TITLE
[POS] allow searching customers on >2 fields 

### ISSUE THREAD

**Issue by jorenvo** [odoo/odoo#21357]
Reported by @dek-odoo in https://github.com/odoo/odoo/issues/21129#issuecomment-347811031:

> This may be a different issue on Customer Screen Searchbox.
The replace function here, will only replace the first occurence of space with .+ (for regexp), so user may not be able to search for Name Address Phone together like agro namur 588. Probably query.replace('  ','.+') can be replaced with query.split(' ').join('.+')

**Comment by dek-odoo** [comment]
:+1:

**Comment by Yenthe666** [comment]
Handled in https://github.com/odoo/odoo/commit/b2f0af4543293350365a43893f9184e0a8669b48
