### ISSUE TITLE
Compute field in Advanced Properties requires always at least one value in Dependencies

### ISSUE THREAD

**Issue by zdarova** [odoo/odoo#21371]
**Impacted versions:**
Odoo 11

**Steps to reproduce:**
1. Create new char x_text_field, 
2. Add code:
```
for record in self:
     record['x_text_field'] = "ciao"
```
3. Leave Dependencies empty

**Current behavior:**
No error is shown, and the Compute script is not working

**Expected behavior:**
Error raised OR The value of x_text_field is updated with "ciao" value

**Comment by Yenthe666** [comment]
@mart-e could you check?

**Comment by mart-e** [comment]
Hello,

If you leave all the defaults (which I guess you did), meaning stored and readonly, it actually makes sense.

If you do not ask to compute the value (no dependencies to trigger the computation, not writeable), the method will not be called.
Sorry but this is the way the ORM works

**Comment by zdarova** [comment]
Clear, where can I find the ORM guide with all the python objects and @api I can use with Odoo 11?

The majority of the examples I found are resulting in permission execution lambda error...
On both Odoo 11 Community on-premise and Odoo 11 Enterprise in Cloud.
Thank you

**Comment by mart-e** [comment]
You can check the ORM documentation at 
https://www.odoo.com/documentation/11.0/reference/orm.html
The backend tutorial also gives some nice tips for beginners to Odoo development
https://www.odoo.com/documentation/11.0/howtos/backend.html
