### ISSUE TITLE
Can't add a new time @workOrder

### ISSUE THREAD

**Issue by dan18fan** [odoo/odoo#21388]
Impacted versions:
10.0e
Steps to reproduce:
Open a "in process-finished" work order
Go to time tracking
Open odoo studio
Select time tracking and disable "Read only"
Close odoo studio
Click "Edit"
Go back to time tracking
Add a new field with the dates-hours and loss reason
Save and Close
Save
Current behavior:
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: workcenter_id - workcenter.id]
Expected behavior:
To let me add a new field with a new time

Video/Screenshot link (optional):

[img]https://imgur.com/j4Zhp8w[/img]

**Comment by dan18fan** [comment]
https://imgur.com/j4Zhp8w

**Comment by Yenthe666** [comment]
Hi @dan18fan,

Could you make a recording of this so we can reproduce it please? I believe I'm missing something.

**Comment by Yenthe666** [comment]
Dear @dan18fan,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
