### ISSUE TITLE
Two identical conditions in L288 and L290

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#21396]
https://github.com/odoo/odoo/blob/f03437ae001622fd58e6029203fa679841dc4499/addons/mail/models/mail_message.py#L288

Two identical conditions in L288 and L290. You can rewrite:

```
            if message.partner_ids:
                partners |= message.partner_ids
```

**Comment by Yenthe666** [comment]
Hi @KomarovAlea,

Thanks for the report.
The conditions are not identical though. The first says if it has a `subtype_id` and `partner_ids`, the other one says when it does <b>not</b> have these.

**Comment by gdgellatly** [comment]
@yenthe either he's right or there is a bug caused by unexpected behavior
because one of the branches is wrong.

**Comment by xmo-odoo** [comment]
@KomarovAlea You could even remove the condition entirely and unconditionally add `message.partner_ids` to `partners`, according to @tde-banana-odoo it's even possible that the entire thing could be removed as `needaction_partner_ids` *should* be a superset of `partner_ids` (though he wouldn't stake his salary on it).

It's correct, but not exactly considered an issue.

**Comment by KomarovAlea** [comment]
I'm sorry, I explained it wrong. The word "condition" is inappropriate here.
Of course, this is not a mistake.
That's what I meant.
[https://ibb.co/bvfsxw](url)

**Comment by KomarovAlea** [comment]
```
if a == 1 and message.partner_ids:
    x = 2
elif a != 1 and message.partner_ids:
    x = 2
```
0_o
