### ISSUE TITLE
Wrong To Do value in stock picking

### ISSUE THREAD

**Issue by eng-eslam-a-y** [odoo/odoo#21403]
Impacted versions:
9.0

Steps to reproduce:
1.Create two unit of measure under the same category bottle= 120 * Ml (reference)
2.create a new product  set its UOM as bottle and Purchase UOM as bottle
3.let us assume there 10.00 bottles in inventory
4.create a delivery order and choose to delivery 1 Ml

Current behavior:
after reserving the order the to do qty is set to 2 ml

Expected behavior:
to do qty should be 1 ml

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/9556898/33526685-6ea28d48-d84d-11e7-9965-56e295fe4961.png)

![image](https://user-images.githubusercontent.com/9556898/33526693-8e4eb270-d84d-11e7-8a16-e634bdd215eb.png)

**Comment by Yenthe666** [comment]
@jco-odoo could you check this please?

**Comment by eng-eslam-a-y** [comment]
Can any please replay , it's getting messy in the production environment

**Comment by jco-odoo** [comment]
This has to do with rounding on the UoM.  Everything is stored in the main UoM, which is bottles.  So if the rounding of the bottle UoM is e.g. 0.01, it might round 1 ml to 2.  (as there is 120ml in a bottle).  You might e.g. change to 0.00001.

**Comment by eng-eslam-a-y** [comment]
thanks
