### ISSUE TITLE
[11.0] analytic default is using partner_id instead commercial entity.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#21401]
Impacted versions:

11.0

Steps to reproduce:

Create a default analytic:

![image](https://user-images.githubusercontent.com/338634/33523292-706b0b6c-d7c8-11e7-829e-f3d2673eda6c.png)

Create an invoice with Agrolite properly.

![image](https://user-images.githubusercontent.com/338634/33523299-bc3ef1e8-d7c8-11e7-923a-3d2fe2cb8174.png)

But then try to use a contact from Agrolite (not agrolite itself).

![image](https://user-images.githubusercontent.com/338634/33523305-e8767a7e-d7c8-11e7-9e94-b648ad7e25d2.png)

Current behavior:

- Analytic is not proposed.

Expected behavior:

- Analytic is proposed from Agrolite company IF contact does not have one set.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo could you have a look? I believe this should be changed.

**Comment by smetl** [comment]
Hello @nhomar 

This issue is now fixed on 11.0 at revision: https://github.com/odoo/odoo/commit/d5d2a33424cebcfbd77e22175748bd5ebee6fefb

Thank you!

**Comment by Yenthe666** [comment]
You're on a roll today @smetl. Thanks a lot!
