### ISSUE TITLE
Cost of Product with Kit type BoM and REAL PRICE / PERP. INVENTORY not updated --> Invoice has (incorrect) $0.00 Cost of Sales

### ISSUE THREAD

**Issue by vcloud9ray** [odoo/odoo#21400]
**Impacted versions:**

v10 EE - testing with Dec 1st builds:

Community:
commit 3d1e23aaba2e220c7a92fb4323746a08a5a1b7ed
Author: Adrian Torres <adt@odoo.com>
Date:   Fri Dec 1 14:15:42 2017 +0000
[FIX] *: Reset module states on registry init error

Enterprise:
commit 1bfcdce65aadbf8c88d467260c14f8105c97b5b2
Merge: 1db11a5 7dc0d38
Author: Christophe Simonis <chs@odoo.com>
Date:   Tue Nov 28 13:52:28 2017 +0100
[MERGE] forward port branch 9.0 up to 7dc0d38b372

**Steps to reproduce:**

1. Create a New Database with Demo Data and choose UNITED STATES as the Country;

![image](https://user-images.githubusercontent.com/31354495/33522555-40ef32ce-d7a4-11e7-8525-154f918c4fd8.png)

2. Click Apps; Clear the Search Filter;
3. Enter sale_mrp , stock_account, purchase_mrp and account_account one by one into the Search;
4. Change to List View;  Select All; From the Action Menu, select Module Immediate Install;

![image](https://user-images.githubusercontent.com/31354495/33522558-4ddab56c-d7a4-11e7-9d51-2192abc28c6a.png)

5. Go to Apps Switcher, refresh browser to see all Apps;
6. Click Settings; Click Activate the Developer Model
7. Click Purchases --> Configuration --> Settings;
8. Next to Costing Methods, check “Use a 'Fixed', 'Real' or 'Average' price costing method”; APPLY;

![image](https://user-images.githubusercontent.com/31354495/33522560-5e928c2c-d7a4-11e7-8000-15a7909d3734.png)

9. Click Inventory --> Configuration --> Product Categories;
10. Open Category All/ Saleable / Physical;  EDIT;
11. Set Costing Method to Real Price;  Set Inventory Valuation to Perpetual (Automated); SAVE; 

![image](https://user-images.githubusercontent.com/31354495/33522561-6bce91ba-d7a4-11e7-9948-27e67f3d6de9.png)

12. Click Inventory Control --> Products;
13. Open Product [FURN001] Table Head; EDIT;
14. Change the COST PRICE to $0.00 (so it will update with REAL PRICE);
15. Open Product [FURN002] Table Head; EDIT;
16. On the Inventory tab, check Buy Route;
17. Add Delta PC (important as this Vendor uses USD) as a Vendor with a price of $543.00; SAVE & CLOSE;
18. Click the Reordering Rule button; CREATE; SAVE (create a default reordering rule of 0 quantity)

![image](https://user-images.githubusercontent.com/31354495/33522563-7dfc51e2-d7a4-11e7-961e-7f268ab29cf8.png)

19. Open Product [FURN003] Table Leg;  EDIT;
20. On the Inventory tab, check Buy Route;
21. Add a Delta PC as a Vendor with a price of $12.34; SAVE & CLOSE;
22. Click the Reordering Rule button; CREATE; SAVE (create a default reordering rule of 0 quantity)

![image](https://user-images.githubusercontent.com/31354495/33522566-88ccfed2-d7a4-11e7-8e21-cb30b2ccb13f.png)

23. Open Product [FURN004] Bolt; EDIT;
24. On the Inventory tab, check Buy Route;
25. Add Delta PC as a Vendor with a price of $5.67; SAVE & CLOSE;
26. Click the Reordering Rule button; CREATE; SAVE (create a default reordering rule of 0 quantity)

![image](https://user-images.githubusercontent.com/31354495/33522569-9298bb72-d7a4-11e7-8de4-9d6306606353.png)

27. Back to Apps Switcher, click Manufacturing --> Master Data --> Bills of Materials; Open [FURN001] Computer Desk; EDIT;
28. Change BoM Type to Ship this product as a set of components (kit); SAVE; 

![image](https://user-images.githubusercontent.com/31354495/33522572-9b8768f0-d7a4-11e7-8ca6-dc8a50218868.png)

29. Back to Apps Switcher, click Purchases; 
30. Open and CANCEL PO00004; Open and CANCEL PO00007;
31. Back to Apps Switcher, click Sales --> Sales --> Sales Orders; CREATE;
32. Choose The Jackson Group (important as this Customer uses USD) as the Customer;  Add 1 x [FURN001] Computer Desk to the Sale Order;  CONFIRM SALE;
33. Back to Apps Switcher, click Purchases;  Open PO00008;

![image](https://user-images.githubusercontent.com/31354495/33522575-a748e6d2-d7a4-11e7-9387-8ce42445eb39.png)

34. CONFIRM ORDER;  RECEIVE PRODUCTS;  VALIDATE;  APPLY;
35. Back to Apps Switcher, click Accounting --> Adviser --> Journal Entries;
36. Search for MOVE WH/IN/00006;
37. Verify the correct Inventory cost is being booked: (543 x 1; 4 x 12.34 = 49.36; 4 x 5.67 = 22.68);

![image](https://user-images.githubusercontent.com/31354495/33522583-d84d70a4-d7a4-11e7-858c-08511e699516.png)

38. Back to Apps Switcher, click Inventory; Click the TODO button on the Delivery Orders Chip; Open WH/OUT/00006; VALIDATE; APPLY;
39. Back to Apps Switcher, click Accounting --> Adviser --> Journal Entries;
40. Search for MOVE WH/OUT/00006;
41. Verify the correct Inventory cost is being booked: (543 x 1; 4 x 12.34 = 49.36; 4 x 5.67 = 22.68);

![image](https://user-images.githubusercontent.com/31354495/33522586-e693e864-d7a4-11e7-9e01-cbc1e8351eb1.png)

42. Back to Apps Switcher, click Sales --> Sales --> Sales Orders;  Open SO008;  CREATE INVOICE; CREATE & VIEW INVOICES; VALIDATE;
43. Click the OTHER INFO tab; CLICK the Journal Entry INV/2017/0004; 

**Current behavior:**

44. The Expenses / Stock Interim Account pair is $0
45. The Cost of [FURN001] Table Head is $0.00

![image](https://user-images.githubusercontent.com/31354495/33522587-f054201c-d7a4-11e7-8e83-55fed683d1d9.png)

**Expected behavior:**

The Expenses / Stock Interim Account pair should be $615.04
The Cost of [FURN001] Table Head is $615.04

What I expect is that a KIT product should have the PRICE updated when the raw materials for that product leave the warehouse (after processing WH/OUT/00006) since this is when the Inventory Valuation Account is credited for $615.04.

Video/Screenshot link (optional):

**Note:**

If in Step 28 you don’t change the Bill of Materials to KIT, everything works as expected.

1) The Expenses / Stock Interim Account pair on the Invoice **IS** $615.04 plus the cost of time recorded on the MO.
2) The COST of the [FURN001] Computer Desk product **IS** updated to $615.04 plus the cost of time recorded on the MO.
3) The MO correctly shows the cost of the RAW MATERIALS as $615.04:

![image](https://user-images.githubusercontent.com/31354495/33522603-78bff700-d7a5-11e7-8ae9-f715ac9cf8ef.png)

So when the Bill of Materials is configured as "Manufacture this Product" it works, when the Bill of Materials is configured as "Ship this product as a set of components (kit)" it doesn't work.

**Comment by vcloud9ray** [comment]
Enterprise Support Ticket logged: #786268

**Comment by Yenthe666** [comment]
Hi @vcloud9ray,

Thanks a lot for the response!
Please do let me know what the official response is on the ticket. Odoo doesn't really check their enterprise bugs against Github sadly.

**Comment by vcloud9ray** [comment]
@Yenthe666 - understood.  I logged all the details via GITBUG because it was easier than using the Enterprise Bug submission form.

**Comment by Yenthe666** [comment]
I know right? I do exactly the same. Keep up the good work.

**Comment by odony** [comment]
@lap-odoo @pimodoo Could you have a quick look? There's only 45 easy steps to reproduce :-)

**Comment by lap-odoo** [comment]
@vcloud9ray : What is the invoicing policy on your products (the components of the kit and the finished kit) ? Based on ordered or based on delivered quantity ? Thanks

**Comment by vcloud9ray** [comment]
@lap-odoo - I used runbot and the demo data so you could easily check for yourself how everything was setup, I did nothing other than what I showed in the screenshots.

All products are configured the same way they are in the demo data - Invoicing Policy = Ordered Quantities.

**Comment by vcloud9ray** [comment]
@lap-odoo - I just saw that the Customer responded to the Ticket that they use Invoicing Policy = Delivered Quantities - to clarify our different statements:

Delivered Quantities was setup on the Customer's Odoo system when the bug was first discovered.
Ordered Quantities is the default setting I left as is when I was able to replicate the bug on runbot.

**Comment by lap-odoo** [comment]
@vcloud9ray : Hi, 

For the sake of simplicity, we will now centralize the discussion on the ticket and when the ticket will be closed we can add the conclusion on this issue. Ok for you ? This will be easier to manage for our support team. Thanks

**Comment by vcloud9ray** [comment]
@lap-odoo OK.

**Comment by vcloud9ray** [comment]
Odoo Support has released the following patch, which I have not tested yet.

(Enterprise Repository) at https://github.com/odoo/odoo/commit/f1fdb97eed377951eb680049522dc02df445ee32

**Comment by vcloud9ray** [comment]
Patch seems to resolve the issue on the SALES SIDE (ie: when the kit is sold) but I tested on the PURCHASING SIDE (ie: when the kit is purchased, and the invoice is using the finished product [not the components] as the product to put on the Bill, but the quantity from the components.

**Example:**

1. Purchase Order for 1 x [FURN001] Computer Desk

2. Receipt Shipment shows (correctly) as:
1 x [FURN002] Table Head
4 x [FURN003] Table Leg
4 x [FURN004] Bolt

3. Vendor Bill shows (incorrectly) as:
9 x [FURN001] Computer Desk with a unit price matching the PO, rather than the product component product cost.

Odoo knows there are 3 SEPARATE items (1 + 4 + 4) for a total of 9 TOTAL QUANTITY that make up the cost, but it doesn't choose the correct products - it selects only the product from the PO, rather than the products from the Receipt Transfer.

The Bill SHOULD show as:
1 x [FURN002] Table Head
4 x [FURN003] Table Leg
4 x [FURN004] Bolt

The pricing on the Bill should match the product cost price for the components from the BoM of the Computer Desk.

I have asked if this case can be addressed on the same ticket, or if a new one is needed.

**Comment by lap-odoo** [comment]
@vcloud9ray If I remember well, you've received an answer on the ticket. So I'm closing the issue. Thanks
