### ISSUE TITLE
Not  going to do_transfer method  in delivery method

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#21417]
Impacted versions:v11 I believe for v11  enterprise also

Steps to reproduce:Install delivery module and validate a delivery order.Check the call to do_trasnfer method is coming or not

Current behavior:Not coming to the do_transfer method when a delivery order is processed.

Expected behavior: When transfering a delivery order, it should call do_transfer method defined in delivery module

Video/Screenshot link (optional):

https://github.com/odoo/odoo/blob/61847490f258eefa44702b2b5039619514897309/addons/delivery/models/stock_picking.py#L106

Instead of do_transfer, action_done method should be called

**Comment by Yenthe666** [comment]
@jco-odoo or @sle-odoo could you guys check this please?

**Comment by jco-odoo** [comment]
Indeed, needs to be action_done as do_transfer disappeared.

**Comment by Yenthe666** [comment]
@jco-odoo if I'm not mistaking the PR https://github.com/odoo/odoo/pull/21420 is what is proposed and should fix it?

**Comment by sle-odoo** [comment]
following the merge of https://github.com/odoo/odoo/commit/47e2521d94f090e4dc2035be2ce36c43842609ed this should now be fixed

thanks for the report
