### ISSUE TITLE
[11.0] website and website_sale cant be debug

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21423]
Impacted versions: 11

Steps to reproduce:

1. Install new database
2. Install website_sale
3. Go to settings and activate developer mode
4. Go to website frontend, param ?debug=assets is on homepage
5. Go to another link like shop, ?debug=assets is not in as parameter anymore

Current behavior:
?debug=assets is not in as parameter anymore
Expected behavior:
?debug=assets is in every link at frontpage

**Comment by Karsten-77** [comment]
@rdeodoo Why you tag as wishlist. I would say it undermines the odoo pattern, when the param is not appended, when the developer mode is activated. Its an important feature for odoo for its customization, when submodules not does, the feature breaks and isnt complete anymore.

**Comment by Yenthe666** [comment]
I do agree it can be annoying honestly. @JKE-be for interest of you too.

**Comment by JKE-be** [comment]
We agree that it's an annoying behaviour and that it will be a nice feature to keep the params from form to form. But because IMHO it was not supported before, it is not really an issue.

When we will have some time to implement this feature, we will do it.
Meanwhile, PR is welcome ;)

**Comment by JKE-be** [comment]
Added in an internal task "[website] custom dynamic URL". Task-36857
