### ISSUE TITLE
onchange_pickings removed from stock.landed.cost

### ISSUE THREAD

**Issue by jaymaniar** [odoo/odoo#2144]
I have just downloaded latest 8.0.  From there onchange_pickings is removed.

**Comment by Yenthe666** [comment]
Hi @jaymaniar ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report (with more information).

Regards,
Yenthe
