### ISSUE TITLE
[11.0] website_sale with caching problems

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21448]
Impacted versions: 11

Steps to reproduce:
1. Create a fresh new database with demodata
2. Install website_sale
3. Use another browser or logout and delete all cockies and sessions
4. Buy something and process checkout -> first time will work without any issue
5. After first buying, make another buying and process checkout

Current behavior:
seems as that the partner_id is not stored for session, but when doing the second buying, the address informations from first buying is used, when not doing a force refresh
```
2017-12-05 16:49:45,346 15955 ERROR testdb odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/workspace/odoo11/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/workspace/odoo11/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/workspace/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/workspace/odoo11/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/workspace/odoo11/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/workspace/odoo11/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/workspace/odoo11/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/workspace/odoo11/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/workspace/odoo11/addons/website_sale/controllers/main.py", line 818, in payment_transaction
    assert order.partner_id.id != request.website.partner_id.id
AssertionError
```
Expected behavior:
Should use the cached address information or should ask for new address informations without forced reload

**Comment by JKE-be** [comment]
Hi

Could you details:

the address informations from first buying is used, when not doing a force refresh


Thx

**Comment by Karsten-77** [comment]
When you doing the second buying, then at the position where you have normally to enter your address, is still filled with the address of the first buying. I think cause its cached from browser.
We are talking about a guest. Means the buying user is not logged in.

**Comment by Karsten-77** [comment]
@JKE-be This caching problems also exist, when you force reload "Billing&Shipping". After enter a new Address, you cannot reach payment, cause /shop/confirm_oder and /shop/payment are cached too.

Request URL:http://dev.tomws.ddnss.de/shop/confirm_order
Request Method:GET
Status Code:302 FOUND (from disk cache)
Remote Address:91.13.107.191:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:max-age=86400
Cache-Control:private
Content-Length:233
Content-Type:text/html; charset=utf-8
Date:Wed, 06 Dec 2017 11:38:35 GMT
Expires:Thu, 07 Dec 2017 11:38:35 GMT
Location:http://dev.tomws.ddnss.de/shop/payment
Server:nginx
Request Headers
Provisional headers are shown
Referer:http://dev.tomws.ddnss.de/shop/checkout
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

As result you are landing again on /shop and you cant checkout anything.

**Comment by Karsten-77** [comment]
I have observed, that there is also a problem with logged in user.
Try to buy 2 or more times the same product with same quantity, you will everytime land on same order confirmation. No new order is created, also not when payment is confirmed from order before. You will every time stay in same order.

**Comment by Karsten-77** [comment]
When you only change the payment method, you will get as result one order with multiple transactions.

**Comment by Karsten-77** [comment]
@JKE-be Could you set this to high priority and critical, cause would like to roll out odoo11 with website_sale, but for production and also  developing website_sale seems unusable.

**Comment by Yenthe666** [comment]
@Karsten-77 if you do have an enterprise license I suggest you to make a an official ticket. You can escalate bug reports there. If it is for the community and you don't have an enterprise version it is a best effort from the developers.

**Comment by Karsten-77** [comment]
@Yenthe666 Sorry, iam not the owner of an enterprise licence, but when the enterprise module is in same condition, it will effect it too. I reporting this to help any user independent of any licence.

**Comment by Yenthe666** [comment]
I understand. @JKE-be always does his best to help as fast as he can though.

**Comment by JKE-be** [comment]
Hi @Karsten-77 

Just to be sure that it is not your own nginx server that add the cache header...
Could you reproduce your bug on runbot: http://runbot.odoo.com/runbot/1/11.0 (and record it if possible plz). We don't touch the cache recently, so it is strange that it appears suddenly)

Waiting for your feedback

Thanks.

**Comment by JKE-be** [comment]
@Karsten-77  any news ?

**Comment by Karsten-77** [comment]
@JKE-be My in development active nginx conf:
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
        worker_connections 768;
}
http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";

        upstream odoo11 {
            server 127.0.0.1:8069 weight=1 fail_timeout=0;
        }
        upstream odoo11-im {
            server 127.0.0.1:8069 weight=1 fail_timeout=0;
        }
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```
../sites-enabled/odoo
```
server {
        listen *:80;
        server_name *.XXX.de;
        
        location / {
                index index.html index.htm;
                proxy_pass http://odoo11;
        }
        client_max_body_size 200m;
        keepalive_timeout 60;
        proxy_buffers 16 64k;
        proxy_buffer_size 128k;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
        # set headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        server_tokens off;
        proxy_redirect off;
        proxy_buffering off;
        location /longpolling {
                expires 0;
                add_header Cache-Control private;
                proxy_pass http://odoo11-im;
        }

        location /web/static/ {
                proxy_cache_valid 200 60m;
                proxy_buffering on;
                expires 864000;
                proxy_pass http://odoo11;
        }
}
```

I cannot reproduce on runbot, but that looks also different to my demo database. Do you have any recommend settings for nginx? My discribed problems, exist with param 
      #add_header Cache-Control private; and also without.

**Comment by JKE-be** [comment]
have you try to overidde the 301/302 cache via `proxy_cache_valid <statusCode> <delay>` ?

**Comment by Karsten-77** [comment]
I have to apologize searching the problem with odoo, that must be really something strange with nginx. Cant reproduce when serving the port directly without nginx. So I close this. Sorry. No idea why I have that not checked first. We all improve ourself.

**Comment by Yenthe666** [comment]
It is good that you've found it yourself and gave feedback. Thanks for that.

**Comment by Karsten-77** [comment]
Do you recommend to make different settings for location / and /shop in nginx? Would be really interrested how your nginx config looks like in a website_sale production.

**Comment by Karsten-77** [comment]
@JKE-be  No have not override 301/302. Until now I have not known that I have to do. Will search for an example. My Nginx conf has worked so far, first time that I recognize that cache problem with my conf. For any tip to improve nginx thanks in advance.

**Comment by JKE-be** [comment]
You don't need to do...

By default, you don't have 301/302 cache... 

I know some e-commerce that runs with the default Nginx configuration from the documentation and it works as expected :/ Nothing to do...

**Comment by Karsten-77** [comment]
So any idea, why that behavior changed with my posted nginx conf? As I said, I recognize this problem first time and roll out a few website_sale shops with odoo version 9 and that problem never has exist. That was the reason, Ive searched the issue in odoo and not in nginx.

**Comment by JKE-be** [comment]
Maybe on line into this: 
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

**Comment by Karsten-77** [comment]
```
karsten@tomws01:~$ ls -ls /etc/nginx/conf.d/
insgesamt 0
```
with
```
location / {
                index index.html index.htm;
                add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
                expires off;
                proxy_pass http://odoo11;
                proxy_cache_valid 301 302 1m;

        }
```
it works like expected, but that will avoid caching of any content in that location :-(

**Comment by JKE-be** [comment]
301/302 should have 0 min of cache
301 should be cached by the browser anyway.

**Comment by Karsten-77** [comment]
Changed that. Thanks for your help.
