### ISSUE TITLE
psycopg2.IntegrityError

### ISSUE THREAD

**Issue by mreficent** [odoo/odoo#21440]
**Impacted versions:** 11.0 (but possibly all the others)

**Steps to reproduce:**
- Install `account` and `purchase` modules.
- Have a test that creates a partner or a company, and put that test in `account` module, just to be able to execute it after clicking "upgrade" on `account`.
- Click "upgrade" on `account`.

**Current behavior:** During the creation of the partner, as mentioned before, the `purchase` module is not yet loaded, and thus, `res.model` doesn't have the field `purchase_warn`. But the database already have this column so, at the creation of the partner, Odoo gives the error _psycopg2.IntegrityError: null value in column "purchase_warn" violates not-null constraint_.

**Expected behavior:** The test creates the partner correctly without error. I don't bother when the test should be executed but it should be executed correctly.

**Comment by pedrobaeza** [comment]
That's something that can be avoided due to Postgres constraints. The solution is to put your test with
`
from odoo.tests import common

@common.at_install(False)
@common.post_install(True)
class Test(common.*Case)
```

**Comment by Yenthe666** [comment]
@pedrobaeza I'm actually curious about this - could you enlighten this a bit please? Why exactly wouldn't this be possible? (feeling nooby here)

**Comment by pedrobaeza** [comment]
Because the not null constraint is set at DB level. Changing this would need to remove all the constraints at the beginning of the update process, and imagine what this means with partial updates and so on...

**Comment by xmo-odoo** [comment]
@pedrobaeza is correct. The issue, if you want to call it that, is global, structural and long-standing: a module A can modify the DB schema such that it becomes incompatible with a module B ('s tests, or the module itself). Until somebody thinks of and implements a workable solution, developers will have to work around the issue somehow.

**Comment by mreficent** [comment]
@xmo-odoo well, I opened the issue (yes, I think it's an issue) just to remind everyone reading the issues that this should be fixed someday (without haste). To remind that somebody should think of and implement a workable solution.

With the issue closed, it's not working as a reminder as intended 😕

**Comment by Yenthe666** [comment]
Let us atleast label it wishlist so it keeps coming up and functions as a reminder then. 😉
