### ISSUE TITLE
Error while installing Inventory Module Odoo 11

### ISSUE THREAD

**Issue by pakiza-asim** [odoo/odoo#21456]
Impacted versions:
11
Steps to reproduce:
app -> Inventory Module ->install
Current behavior:
display Error message after some processing.
Expected behavior:
Setup Inventory Module
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/26475715/33647127-1e2d021a-da75-11e7-8615-796050add48a.png)

Error:
Odoo Server Error

> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/tools/cache.py", line 84, in lookup
>     r = d[key]
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/tools/func.py", line 68, in wrapper
>     return func(self, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/tools/lru.py", line 44, in __getitem__
>     a = self.d[obj].me
> KeyError: ('account.move', <function BaseModel._table_has_rows at 0x7fc8810da7b8>)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 646, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 683, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 927, in __call__
>     return self.method(*args, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-42>", line 2, in button_immediate_install
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/addons/base/module/module.py", line 438, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/addons/base/module/module.py", line 531, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/modules/registry.py", line 84, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
>     loaded_modules, update_module)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/modules/loading.py", line 135, in load_module_graph
>     registry.init_models(cr, model_names, {'module': package.name})
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/modules/registry.py", line 302, in init_models
>     model._auto_init()
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/models.py", line 2142, in _auto_init
>     new = field.update_db(self, columns)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/fields.py", line 1942, in update_db
>     return super(Many2one, self).update_db(model, columns)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/fields.py", line 853, in update_db
>     self.update_db_notnull(model, column)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/fields.py", line 892, in update_db_notnull
>     if model._table_has_rows():
>   File "<decorator-gen-2>", line 2, in _table_has_rows
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/tools/cache.py", line 89, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/models.py", line 2081, in _table_has_rows
>     self.env.cr.execute('SELECT 1 FROM "%s" LIMIT 1' % self._table)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/sql_db.py", line 155, in wrapper
>     return f(self, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171118-py3.6.egg/odoo/sql_db.py", line 232, in execute
>     res = self._obj.execute(query, params)
> psycopg2.InternalError: invalid page in block 0 of relation base/16384/22186
>

**Comment by Yenthe666** [comment]
Hi @pakiza-asim,

Thanks for your report.
I've just tried this on a fresh install from today and installing the modules work just fine.
Are you doing this with the latest source code? Have you tried updating your source code? Can you reproduce it on a runbot (runbot.odoo.com)?

Regards,
Yenthe

**Comment by pakiza-asim** [comment]
I am sorry I forget to mention that I am using
"bitnami-odoo-11.0.20171118-2-linux-debian-8-x86_64"  on virtual box.

Regards,

Pakiza Beenish Rana
Senior Web Developer
Skype: pakiza.rana

**Comment by Yenthe666** [comment]
Hi @pakiza-asim,

Please do answer the other questions too. We really need some more info.

**Comment by pakiza-asim** [comment]
Thanks for your quick response.
I am working with fresh install. I have done following changes to acess db from pgadmin.

Edit the file /opt/bitnami/postgresql/data/pg_hba.conf and add the following at the end
host all all all md5
Edit the file /opt/bitnami/postgresql/data/postgresql.conf and replace this line
listen_address='127.0.0.1'
with:
listen_addresses = '*'

I have installed eCommerce app, It has installed successfully. 
next, I installed Inventory module but it gives me the error. module is installed but not working fine. Inventory link is appears on top bar but it is not working.
next, I have tried to install sales module but it gives me the same odoo server error and nothing will be installed. 
I am only working on front end I have not change any python source code.

**Comment by pakiza-asim** [comment]
Thanks Yenthe,  I found the solution. Virtual box will break the connected port when system get idle so the server did not respond correctly and could not complete the install process. I start with a fresh copy of ODOO Server if system get idle I logout from server then restart the server from virtual box. so it works seamlessly. Hope it help others.

**Comment by Yenthe666** [comment]
Thanks for the feedback & answering yourself!

**Comment by Rikja67** [comment]
Gents, I've got the same issue. I'm working on a Windows 2012. I have tested the logout and logon. I have restarted the server but I have no success. The Inventory Management cannot be installed at all. Any help would be appreciated.
