### ISSUE TITLE
_search method with one2many with auto_joins field shows wrong results

### ISSUE THREAD

**Issue by mhamra** [odoo/odoo#21453]
Impacted versions: 8 (i don't know if this problem ocurs in higher versions)

Steps to reproduce: trying to search on a one2many relation field marked with auto_join produces duplicated ids in search result list. For example using a class.search([('one2many_field.foreign_field', '>', 1)], order_by='class_field ASC') makes duplicated class.id field

Current behavior: duplicated ids are eliminated from the id list at the end of _search() method on models.py file, but list size does not reach LIMIT. The view receives less records than the limit and thinks that there are no more results to show, displayin wrong results.

Expected behavior: search method should use a SELECT DISTINCT ID query to avoid duplicates in order to match the number of the LIMIT clause. Keep in mind that the generated SQL shoud add order by fields to the SELECT clause list to avoid SQL syntax errors (they shoud appear because DISTINCT is being used in SELECT)

Video/Screenshot link (optional):

Attached a corrected version of models.py. 

_search, _generate_inner_order_by, _generate_order_by were modified 

In this version _search method generates a SELECT DISTINCT query. _generate_order_by and _generate_inner_order_by Methods where modified in order to produce order by field list without ASC/DESC words (used in SELECT DISTINCT)

[models.zip](https://github.com/odoo/odoo/files/1533802/models.zip)

**Comment by Yenthe666** [comment]
Hi @mhamra,

Thanks for your report.
Odoo 8 is no longer a long term stable version though. Odoo 9, Odoo 10 and Odoo 11 are the only stable versions that are supported at the moment. 

Regards,
Yenthe
