### ISSUE TITLE
[Enterprise 11.0] Account Reports - incorrect company name on report in multicompany

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21452]
Impacted versions: 11.0e

Sorry, just easier to raise here than the ticket thing. @qdp-odoo ?

Steps to reproduce:
Tested in runbot on General Ledger Report but its fairly inherited so I imagine all reports affected.
Add admin user to MyCompany.
Go to General Ledger Report
Deselect your company, select mycompany

Current behavior:
Report still says YourCompany

Expected behavior:
Report says MyCompany.

In addition - needs to cover the case when multiple companies are selected.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/33642869-d29e09ee-daa0-11e7-8586-b825cdc8f23d.png)

**Comment by Yenthe666** [comment]
Hi @gdgellatly,

Thanks for the report.
What I usually do is create a bug report here and then simply paste the URL in the official bug report. The thing is that nobody is obligated to answer / fix these bug reports, while they are with the official bug reports. (no offense to the guys from Odoo obviously).
Anyways, (@)qdp-odoo will answer when he comes around I guess.

Regards,
Yenthe

**Comment by qdp-odoo** [comment]
Indeed. We, at R&D, aren't bound to any customer satisfaction, SLA or delay-to-reply things. It's fine if you're not in a hurry 'cause we're having our own priorities ^^

@csnauwaert can you have a look at this, please?

**Comment by csnauwaert** [comment]
Hello,

This has been fixed in the latest saas-14 version and will be available in version 11 in a few days. Since we've had to change a view, you'll have to update the account_reports module once you've updated your source in order to see the change.

Since this is fixed, I'm closing this issue.

Best regards
