### ISSUE TITLE
[10.0] Deinstalling and reinstalling MRP in demo database causes constraint error

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#21462]
Impacted versions: 10.0

Steps to reproduce:
- Install an Odoo 10 with demo data and MRP (default runbot)
- Deinstall the `MRP` module
- Reinstall the `MRP` module
You'll be greated by a traceback:
![image](https://user-images.githubusercontent.com/6352350/33653606-d9b314d2-da6d-11e7-8c11-95d450e9979d.png)

Current behavior: Traceback about a constraint

Expected behavior: Succesfull installation

**Comment by Yenthe666** [comment]
@Elkasitu OPW 786790 by the way. 😉

**Comment by Elkasitu** [comment]
@Yenthe666 Bug seems unrelated to MRP, all modules inheriting from mail.thread seem to have the same behaviour... Unlucky, will investigate further :^)

**Comment by Yenthe666** [comment]
Thanks a lot @Elkasitu!
