### ISSUE TITLE
Language refresh

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#21473]
I have translated some strings in transifex. when i can see them in the build ?

**Comment by Yenthe666** [comment]
Hi @F3000,

Synchronisation of the terms happens every once in a while. For V11 this should be about once a week and normally this is on a sunday.
More info at https://github.com/odoo/odoo/wiki/Translations#when-will-my-translations-appear-in-the-software-or-in-github
(@mart-e we should update the wiki as it doesn't mention 11.0 yet)

Regards,
Yenthe
