### ISSUE TITLE
Apps overview page 

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#21474]
Odoo 11 latest build 

some of the app introduction pages are only filled with one sentence . Not very nice 

![contacts](https://user-images.githubusercontent.com/8161283/33669321-6a32ca64-daa2-11e7-9f3d-0c47ba1aec40.PNG)

And where i can find the strings to translate the phrases on every app information page ?

**Comment by Yenthe666** [comment]
Hi @F3000,

By default these pages can't be translated at the moment. For more information you can find the whole topic at https://github.com/odoo/odoo/issues/11721
As for the text.. while it doesn't look great it is not really a bug.
FYI @mart-e 

Regards,
Yenthe

**Comment by F3000** [comment]
Thanks for the answer. Also i see every time there is an update "Aktualisieren" . But when i want to install ist , there isnt an update. 

cam you fix that ?

**Comment by Yenthe666** [comment]
@F3000 not really a bug. You first have to fetch the updates and then update the module(s). 😉

**Comment by Yenthe666** [comment]
@F3000 this depends on what OS and how you've installed the Odoo. Usually this is done with a `git fetch origin` and then the Odoo is usually updated from the terminal with `./odoo-bin -u all -c /etc/odoo-server.conf` for example. Have a look at the docs (for example https://www.odoo.com/documentation/10.0/setup/install.html)

**Comment by F3000** [comment]
i use fedora . ok thanks
