### ISSUE TITLE
modern looking 

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#21475]
odoo 11 latest build

![view](https://user-images.githubusercontent.com/8161283/33669963-2163595a-daa4-11e7-98eb-d1696fe68c71.PNG)

where can i chage the optic of the site ? 

At the moment my odoo is looking like this 
![view2](https://user-images.githubusercontent.com/8161283/33670035-5210b0de-daa4-11e7-883e-8cffd31faaa7.PNG)

**Comment by Yenthe666** [comment]
Hi @F3000,

The difference is that you have an Odoo community version while the screenshot you show is an Odoo enterprise version.
If you want the 'beautiful' layout you will need to buy an enterprice lisence at https://www.odoo.com/nl_NL/pricing#pl=66&num_users=1&hosting=online&implementation_service=self&pack=25&force_country=BE&integrating_partner_id=0&price_by=yearly and then need to upgrade your Odoo to an enterprise version.
For more information about the Odoo versions see https://www.odoo.com/nl_NL/page/editions

Regards,
Yenthe
