### ISSUE TITLE
[10.0] Wrong customer invoice unit of measure with COGS affectation

### ISSUE THREAD

**Issue by dsabrinarg** [odoo/odoo#21485]
Impacted versions:
**10.0**

Steps to reproduce:
With group "Some products may be sold/purchased in different units of measure (advanced)" active and a product for example with the following unit of measure setting:
    Unit of Measure | Unit(s)
    Purchase Unit of Measure | Dozen(s)
1. Go to a POS sales window.
2. Create a POS order with invoice for the example product.

Current behavior:
1. The pos order picking will move the product on the unit of measure (Unit(s) for the example product case) as expected.
2. But on the customer invoice line the unit of measurement established will be the "Purchase Unit of Measure", however the customer invoice line "Unit Price" will not be considering the purchase unit of measure.
3. The lines for the COGS on the customer invoice journal entry will be considering the "Purchase Unit of Measure", this in consequence is leading to a sale cost a lot much hider than the sale as such.

Expected behavior:
The customer invoice line for a pos order sale should have the "Unit of Measure" of the product and be consistent with the unit of measure in which the product is being moved in the pos order picking. Also in presence of Anglo-Saxon accounting the lines for COGS should be considering the product "Unit of Measure" in place of the "Purchase Unit of Measure".

Video/Screenshot link (optional):
[Demo Video](https://youtu.be/cNoU80OgAQw)

Note: IMHO [this](https://github.com/Vauxoo/odoo/commit/fea667a2433dfc2387daa7051989e840d30e18e0) is the commit where this issue started.

**Comment by amoyaux** [comment]
It should be used in a vendor bill case. True I failed this since I didn't check for the invoice type. I will correct it.

**Comment by sle-odoo** [comment]
@dsabrinarg can you confirm it is solved now thanks to 6d02f7d6bfa5c59495c44db35d39a2eeef59e395 ? thank you

**Comment by dsabrinarg** [comment]
Issue solved @sle-odoo by the mentioned commit. Best regards!
