### ISSUE TITLE
Ability to insert blank page in PDF export for pro

### ISSUE THREAD

**Issue by sathieu** [odoo/odoo#21495]
Impacted versions: latest

Steps to reproduce:

- Select several *Sale Orders*:
  - ORDER-1 with 2 pages
  - ORDER-2 with 1 page
  - ORDER-3 with 3 pages
- Click "Print" (i.e export to PDF)
- Print the PDF with duplex

Current behavior: 
- Page 1 has ORDER-1 duplex
- Page 2 has ORDER-2 on one side, and ORDER-3 on the other side :disappointed: 
- Page 3 has the end of ORDER-3

Expected behavior:
- Page 1 has ORDER-1 duplex
- Page 2 has ORDER-2 on one side (the other side blank)
- Page 3 has ORDER-3 duplex
- Page 4 has the end of ORDER-3

**Comment by sathieu** [comment]
Note that wkhtmltopdf supports this: 
```
style="page-break-after: always;"
```

**Comment by Yenthe666** [comment]
I really don't see the issue in this though.. If you'd want this you can add a `<p style="page-break-after:always;"></p>` through your own module.
@mart-e do you agree? I don't see why we would want to change this.

**Comment by sathieu** [comment]
@Yenthe666 The problem is that ```page-break-after:  left``` is not working (i.e it is working as ```always```).

**Comment by sathieu** [comment]
This is a Chrome missing feature. See https://caniuse.com/#search=page-break
> 3.Treats the left and right values like always.

**Comment by sathieu** [comment]
The problem in qtwebkit [Source/WebCore/css/CSSComputedStyleDeclaration.cpp](https://github.com/qt/qtwebkit/blob/30af5bd74a1c035f0b3efc73767c0d2bef21333a/Source/WebCore/css/CSSComputedStyleDeclaration.cpp#L2089):
``` C
static CSSValueID convertToPageBreak(BreakBetween value)
{
    if (value == PageBreakBetween || value == LeftPageBreakBetween || value == RightPageBreakBetween
        || value == RectoPageBreakBetween || value == VersoPageBreakBetween)
        return CSSValueAlways; // CSS 2.1 allows us to map these to always.
    if (value == AvoidBreakBetween || value == AvoidPageBreakBetween)
        return CSSValueAvoid;
    return CSSValueAuto;
}```

**Comment by Yenthe666** [comment]
So not an Odoo bug.

**Comment by sathieu** [comment]
Submitted upstream: https://bugreports.qt.io/browse/QTBUG-65045
