### ISSUE TITLE
[11.0] "No exception to reraise"

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#21504]
Impacted versions:11
My IDE(pycharm) says "No exception to reraise" and marked as error.
https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_http.py#L180

Could be rely more on style and not harmful. Just for the next who works on it.

**Comment by Yenthe666** [comment]
@xmo-odoo perhaps we should handle this slightly better? (there are a few more that only have `raise` in the file)

**Comment by xmo-odoo** [comment]
The alternative would be to raise the specific exception object but I believe that would lose us the traceback unless we went and retrieved it in our reraising.

All in all, meh.

**Comment by rolandas-simkus** [comment]
Hi, I have the same issue and can't find a solution on how to ignore these kind of issues, maybe there is some referral on how to do them?

Thank you!!
