### ISSUE TITLE
[10.0] Outgoing shipments in pos order, skip the warehouse's configuration for two or more steps

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#21509]
**Impacted versions:** 10

**Steps to reproduce:** 

- Configure the warehouse, related to the outgoing delivery steps

![yourcompanyshipment](https://user-images.githubusercontent.com/5775695/33736463-15058848-db69-11e7-8257-c5434edd5b91.png)

- Set the point of sale, with the corresponding warehouse

![setpointsale](https://user-images.githubusercontent.com/5775695/33736529-4a02c15a-db69-11e7-93c5-02b84ffca7a6.png)

- We select a storable product in the pos

![storableproduct](https://user-images.githubusercontent.com/5775695/33736883-b0ca7bfc-db6a-11e7-8ced-a2bab7b80d17.png)

- Verify location and picking in pos order
![verifylocactionpicking](https://user-images.githubusercontent.com/5775695/33737123-7a857dc0-db6b-11e7-9271-3b47ddad7481.png)

**Current behavior:**

The product is being delivered directly to the customer without going through the previous locations given in the warehouse configuration

![verifypicking](https://user-images.githubusercontent.com/5775695/33737289-f9933ac6-db6b-11e7-91ca-194f43a80d9a.png)

**Expected behavior:**

The picking must follow the delivery configuration of the warehouse

**Video/Screenshot link (optional):**

Video [Here](https://youtu.be/UVZpGK86fbo)

**Comment by jco-odoo** [comment]
It is not meant to steer warehousing through PoS.  A point of sale is really a point where the client searches the goods and he takes it with him immediately.  What you could do e.g. is create a separate warehouse from the PoS and resupply it from another warehouse that has pick ship.
