### ISSUE TITLE
Advanced filter “doesn't contain” not working on many2many field

### ISSUE THREAD

**Issue by rven** [odoo/odoo#2151]
The following applies to each version of odoo.

Suppose the following partners exist in the system:

Partner A, with Tags “Partner/Gold”, “Services”
Partner B, with Tags “Partner/Gold”
Partner C, with Tags “Partner/Silver”
Partner D, with Tags “Partner/Gold”
Partner E, with no Tags

When applying the following advanced filters on the field Tags:

Tags contains “Gold”, Partners A, B, D are returned in the search, which is ok.

Tags doesn't contain “Gold”, Partners A, C are returned in the search, which is not ok.
The result should be C, E.

This because the many2many fields are filtered the following way.

This case referes to the partner categories.

First the partner categories are returned which do not contain the string “Gold”, in this case “Partner/Silver”.
With these partner categories returned from the previous search, the partners are returned which have these tag assigned to them.
This is wrong, it should return the partners not assigned a tag containing "Gold".

**Comment by thomich** [comment]
i confirm this bug... if multiple tags are used in partners, then searching by tags failed and is useless.

**Comment by thomich** [comment]
same in odoo 9alpha1
![shot-selection-101](https://cloud.githubusercontent.com/assets/4398840/9515315/d84ed84a-4ca0-11e5-8a1c-272a556f3673.png)
used runbot: http://95996-master-97cc5b.runbot6.odoo.com/web

**Comment by pedrobaeza** [comment]
This is something I have faced also, but it seems inherent to current search behaviour. As an alternative workaround, you can use this module from OCA: https://github.com/OCA/web/tree/8.0/web_advanced_search_x2x

**Comment by Yenthe666** [comment]
Hi @rven,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
