### ISSUE TITLE
[10.0]Cannot update standard_price on product.template when it contains more than one variant!

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#21512]
**Impacted versions:** 10.0 and **test on runbot**

**Steps to reproduce:**
1) Create a product with two variants. For example color: reg and yellow
2) Modify Cost price

**Current behavior:**
**The cost price is not update and return to value 0**

**Expected behavior:**
The cost price must update to the set value.

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
Probably more a usability issue.  Field should be invisible when variant_count > 1 so it shouldn't be possible to even set once yo have variants.  Is definitely set that way in v11, and all standard_price for all product_templates with > 1 variant is 0.  Maybe that fix needs backporting.  

Once you use variants, the cost must be managed on each individual variant.  When there are no variants Odoo tries to treat the template and the product as one, but obviously once you have more than one variant, certain things cannot be the same (partcodes and cost being 2 examples).

**Comment by Yenthe666** [comment]
Hi @rgeromegnace,

Thanks for your report.
What @gdgellatly said is true, so it is rather an usability issue then a bug. 
Always set the price on the variant(s) when you have them.
@mart-e perhaps we should make a little improvement on this case?

Regards,
Yenthe

**Comment by rgeromegnace** [comment]
Hi @gdgellatly and @Yenthe666 

Thanks for you quick answer.
I will set the price on the variant(s) if any.

Regards,
