### ISSUE TITLE
[11.0] Cannot create purchase.order.line after confirmation of the purchase order 

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#21519]
Impacted versions:
11.0

Steps to reproduce:
1. Create a purchase order.
2. Add Product A to the order.
3. Confirm the purchase order.
4. Edit the order and add Product B to the order.

Current behavior:
Odoo Server Error (message quoted below) appears and the purchase order line cannot be added to the order.

![image](https://user-images.githubusercontent.com/27185427/33754287-855a1b96-dc26-11e7-99f7-97968c54ccad.png)

Following is the `values` of the create method
`{'account_analytic_id': False, 'name': '[00005] ABC', 'order_id': 21, 'sequence': 10, 'product_uom': 1, 'taxes_id': [[6, False, [2]]], 'price_unit': 0, 'product_qty': 1, 'analytic_tag_ids': [[6, False, []]], 'date_planned': '2017-12-08 06:27:40'}`
https://github.com/odoo/odoo/blob/02b9dbac3250abd942e8f9f9e06621ef829315fe/addons/purchase/models/purchase.py#L581-L588

Expected behavior:
If the "Lock Confirmed Orders" option is not enable, user should be able to edit the purchase order.

**Comment by Yenthe666** [comment]
Hi @TimLai125,

Thank you for the bug report and detailed analysis.
@jco-odoo could you please have a look? I believe this is correct.

Regards,
Yenthe

**Comment by jco-odoo** [comment]
I confirm, I tested it on runbot.  @sle-odoo, we need to fix this.
