### ISSUE TITLE
Wishlist: option to store email-servers passwords encrypted

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21520]
Impacted versions:
11.0
Steps to reproduce:
Add new incoming or outgoing mail server
Current behavior:
in DB in ir_mail_server and fetchmail_server i can see our server password
Expected behavior:
Passwors must be seen as hash

**Comment by Yenthe666** [comment]
@odony could you check this from a security point of view please?

**Comment by elicoidal** [comment]
Not sure you can avoid it as you need to use the password to connect to the email and you cannot use a hash for that.

**Comment by gdgellatly** [comment]
Well, you could configure SMTP without a password, and just relay as a trusted IP.  Configure authorized senders on your domain correctly and really there's not a lot someone could do with the SMTP password anyway.

I also imagine someone trusted to administer your ERP database directly in postgres, is also trusted to have the SMTP password.  I mean there's financial information, peoples salaries potentially, customer lists.  And if its an attacker, then you've probably got bigger problems than your email passwords.  

But the easy workaround is to use a localhost, or at least local network mail relay.

**Comment by sergeiruzkiicode** [comment]
It is possible simply provide passkey in settings or conf file for each new instance and make standart python encrypt-decrypt thing.

**Comment by gdgellatly** [comment]
It is secured, just not encrypted.

**Comment by odony** [comment]
I think @gdgellatly has said everything. We could do an encrypt/decrypt dance to store those passwords encrypted, but it would come at the cost of deployment complexity (necessity to create and maintain an encryption key somewhere outside the database, and secure it!).

If you're concerned about this, a simple and safer option is to go for a passwordless deployment. You can do that today:
- for outgoing emails, use one of the techniques already mentioned (IP-based, etc.)
- for incoming emails - use the mail gateway integration that feeds incoming emails directly to the system, instead of relying on a scheduled fetchmail process. It will also bring real-time email integration.

**Comment by wtaferner** [comment]
@odony 
I agree with you and @gdgellatly, but I lately wondered how to handle the incoming emails with the mail gateway integration as it was promoted very often by you guys? Do you have any pointer where this is described? What kind of setting do I need to have? Can I still use a provider like Google to manage my mail domain and accounts?

I would appreciate to get a good head start...it is on my personal research wishlist for quite a while but did not have the time to dive deep enough I guess or maybe it is just obvious and I did not get it :-)

**Comment by hparfr** [comment]
We resolved the issue of having password in clear text in our databases with keychain module https://github.com/OCA/server-auth/tree/11.0/keychain
(Note: I don't think there is a module for smtp credentials yet, but there is for attachments (AWS S3, SFTP),  SMS providers, carriers, etc.)

A passkey should be generated and given to odoo via config file or env variables or externally,  then password are encrypted in the db.

It prevent leaks related to db dumps, and the use in unauthorized work environments (dev/tests/prod) + other nice features.
It doesn't prevent leak if an attacker gain access in the python runtime, for this threat as stated before on this issue: putting passwords out of odoo can be the safest design while it's hard to achieve it for every kind of passwords.

A good and easy improvement can be at least to be more explicit with a disclamer in the smtp settings view.

**Comment by aelmanaa** [comment]
Is it normal that this is not tackled as high priority? Actually , this is really problematic in a milti-tenancy setup: we are not supposed to see our client passwords.

**Comment by mart-e** [comment]
Closing as not something we are going to do at the moment and there are alternatives. Maybe we will do something more general like "secret" fields at #47103 (which is still an experiment)
