### ISSUE TITLE
[9.0, 10.0] Automated action issue

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#21528]
Impacted versions: 9.0 (not tested but i think this issue is on every version)

Steps to reproduce:
Create an automated action where you want to receive an email when someone try to change product price on form view:
![image](https://user-images.githubusercontent.com/7678583/33772302-730fa48e-dc34-11e7-8622-a80f92b7ce0b.png)
![image](https://user-images.githubusercontent.com/7678583/33772319-80f8e092-dc34-11e7-9e9d-f57ed24836b9.png)

Here is the action server detail:
![image](https://user-images.githubusercontent.com/7678583/33772349-9c28611c-dc34-11e7-89ef-4d1ffd4ad1d4.png)

Current behavior:
When changing the price in product template form view, No email is sent

Expected behavior:
An email should be sent

Video/Screenshot link (optional):
In this video, i show the case where it doesn't work and i change the "When to run" field value to show that when using on update it works but not on form modification
https://youtu.be/ae4DnX1N4GY

Thank you for the help

**Comment by sswapnesh** [comment]
Hello @jlaloux 

I can confirm this issue.
I am not sure but the possible reason is we are not getting `active_id` in `context`.

Same context example which I am getting [from this line ](https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_actions.py#L1088)here. 

`{u'lang': u'en_US', u'search_default_filter_to_purchase': 1, u'params': {u'action': 384, u'model': u'product.template', u'_push_me': False, u'id': 55, u'view_type': u'form'}, u'uid': 1, 'onchange_self': product.template(<openerp.models.NewId object at 0x7f1984668850>,), 'active_model': 'product.template', u'tz': u'Europe/Brussels'}`

I have performed this test case on Product template with Id 55.

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
This is also reproducible in v10 too. (I will create new Issue if you suggest)

**Comment by Yenthe666** [comment]
Don't worry, renamed & retagged. Thanks for testing!

**Comment by sswapnesh** [comment]
Thanks, I will give try for latest versions and update result here.

**Comment by sswapnesh** [comment]
Works well in latest V12 Runbot

**Comment by Yenthe666** [comment]
Dear @jlaloux,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
