### ISSUE TITLE
How to set redis as cache storage in odoo?

### ISSUE THREAD

**Issue by PigPigAutumn** [odoo/odoo#21524]
I'm going to run odoo in a multi-server environment and now I'm able to store the session on redis, but there is too little information on odoo's cache  on the Internet, so can someone give me some information?
Thanks

**Comment by Yenthe666** [comment]
Hi @PigPigAutumn,

Thanks for your report.
The Github tracker is only for bug reports and not for asking questions though.
Please do post this question on the official help forum at odoo.com/help or on the mailing list at https://www.odoo.com/groups

Regards,
Yenthe
