### ISSUE TITLE
[11.0] l10n_in_hr_payroll - Payslip Report not working

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#21527]
Impacted versions: 11.0

Steps to reproduce: Introduce the payslips and try to open Reporting/Payslip Analysis
The menu shows no data
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
@elperrofarelo Hello Could you provide us with more information please

**Comment by elperrofarelo** [comment]
The report is not working as well in version 12.

**Comment by Yenthe666** [comment]
@elperrofarelo can you please add a video showing the issue?

**Comment by elperrofarelo** [comment]
Hi. Sorry for the short information.
The filters content in Group by are not working, making the function useless.
See pictures.
![payslip analysis 1](https://user-images.githubusercontent.com/9564408/49221204-1c224800-f3e1-11e8-9909-372f480c5771.jpeg)
![payslip analysis 2](https://user-images.githubusercontent.com/9564408/49221228-33f9cc00-f3e1-11e8-9a22-ef4cbe1ba3fc.jpeg)
![payslip analysis 3](https://user-images.githubusercontent.com/9564408/49221244-3f4cf780-f3e1-11e8-9a76-398a0eddcab3.jpeg)

**Comment by RomainLibert** [comment]
Not even sure what this report should show.
What is certain is that it is not very usable, for versions 11 and 12 I cannot promise to do anything as they are stable releases but for v13 we will try to do something.

**Comment by akloptim** [comment]
I think the issue can solve by removing "'group_by_no_leaf':uid" context from window action

**Comment by tivisse** [comment]
@robodoo r+

**Comment by Yenthe666** [comment]
@tivisse I believe you wanted to do this on the PR instead of on the issue 😉

**Comment by tivisse** [comment]
Ah :)

Indeed, thank you. ;)

**Comment by tivisse** [comment]
Done at https://github.com/odoo/odoo/pull/42754
