### ISSUE TITLE
[10.0] Partial reconciliation on pos session when doing a product return

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#21525]
Impacted versions: 

10.0

Steps to reproduce:

Add a payment method to the pos config:
![image](https://user-images.githubusercontent.com/7813258/33763388-97669eba-dc10-11e7-8abd-872b1cf76d87.png)

Do 1 sale on Cash payment for the exact amount:
![image](https://user-images.githubusercontent.com/7813258/33763483-f0259f6a-dc10-11e7-92ef-9d94b1d4b2d1.png)
![image](https://user-images.githubusercontent.com/7813258/33763536-28b92482-dc11-11e7-867d-2886ae8c2b90.png)

Do 1 return on Cash payment:
![image](https://user-images.githubusercontent.com/7813258/33763577-4f649ac6-dc11-11e7-923d-ba22317af0ae.png)
![image](https://user-images.githubusercontent.com/7813258/33763588-5dbc7b34-dc11-11e7-91e9-3297b2e6bd0b.png)

Do 1 sale on Bank Payment:
![image](https://user-images.githubusercontent.com/7813258/33763624-856ba088-dc11-11e7-81a6-4099c351d128.png)
![image](https://user-images.githubusercontent.com/7813258/33763645-977a71b4-dc11-11e7-89e8-2473ddbf6ae1.png)

Close the session and validate the accounting entries:
![image](https://user-images.githubusercontent.com/7813258/33763693-b46c93a6-dc11-11e7-84cf-abb8374926a6.png)

Go on the journal entry generated:
![image](https://user-images.githubusercontent.com/7813258/33763730-dc5e9bca-dc11-11e7-9942-ab447b90de1f.png)
![image](https://user-images.githubusercontent.com/7813258/33763769-092cb114-dc12-11e7-8a42-df723ff83c56.png)

Current behavior:

The payment line concerning the return is not taken in account in the reconciliation process.
The balance of reconcilied lines should be 0.
The gap here exactly fit with the amount of the return.

Expected behavior:

The following line should be reconcilied:
![image](https://user-images.githubusercontent.com/7813258/33763883-7690c1e6-dc12-11e7-8f4f-532385860ebe.png)
with this one:
![image](https://user-images.githubusercontent.com/7813258/33763902-87151d50-dc12-11e7-9cfe-ae545d0d4cd1.png)

Video/Screenshot link (optional):

**Comment by Cedric-Pigeon** [comment]
OPW-787298

**Comment by Cedric-Pigeon** [comment]
@Yenthe666 thanks but it has nothing to do with Logistics, it is accounting rather

**Comment by Yenthe666** [comment]
Hmm indeed - I was looking at the first screenshots and was assuming it was coming from the POS.
After reading it all in detail (I guess I was a bit too fast here) it is clear that the issue happens in the accounting part. Corrected.

**Comment by lukebranch** [comment]
@Yenthe666 ,

As a side note, i've had some DO's generated from the POS getting stuck in the draft state periodically (haven't been able to provide steps to reproduce yet). POS transactions are processed in the normal fashion, however the DO gets stuck in draft.

I have noticed this with rather huge POS orders (one in particular the user added 200 different products for a single POS transaction).

Should I create another issue for this, or are you aware if there is already something open for this for 10.0 (and possibly 11.0)?

**Comment by Yenthe666** [comment]
@lukebranch,

Haven't seen an issue about this lately really.
Feel free to create a new bug report!

**Comment by kebeclibre** [comment]
closed at 296c5a2

**Comment by Cedric-Pigeon** [comment]
@kebeclibre I think your fix introduced a severe regression: https://github.com/odoo/odoo/issues/22697
Could you have a look ?
