### ISSUE TITLE
Duplication Error

### ISSUE THREAD

**Issue by puakinsin** [odoo/odoo#21542]
Impacted versions: 10

Steps to reproduce:
Create Product A; **ID=1**
Upload thumbnail for product A

Duplicate Product A and rename it to product B; **ID=2**

Current behavior:
The #{product.id} in the following line of product B = [1]

 <meta property="og:image" t-attf-content="#{request.httprequest.url_root}web/image/product.template/#{product.id}/image"/>

Expected behavior:
The #{product.id} in the following line of product B should be [2]

 <meta property="og:image" t-attf-content="#{request.httprequest.url_root}web/image/product.template/#{product.id}/image"/>

**Comment by Yenthe666** [comment]
Hi @puakinsin,

I'm not sure how you would be ever able to get this though. Can you reproduce this on an official Odoo instance at runbot.odoo.com? Have you updated your Odoo to the latest codebase?
Anyways, there is like no way this can ever happen.. Odoo always assigns new id's to newly created records and this has been the case for years. An example when I duplicate the product with id 1:
![image](https://user-images.githubusercontent.com/6352350/33819907-13eaf66e-de4d-11e7-8a27-7fba0a2bfcf1.png)
Please do give more info.

Regards,
Yenthe

**Comment by puakinsin** [comment]
Here is a screenshot while inspecting the code after the product was duplicated.
Notice the ID in the URL and the ID in for og:image

![screen shot 2017-12-12 at 8 48 18 am](https://user-images.githubusercontent.com/29155944/33861615-ab4a58a2-df19-11e7-85d4-87dd2069b95e.png)

**Comment by sswapnesh** [comment]
Hello @puakinsin 
I have tried to reproduce same on [Runbot V10](http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com) and I am getting new ID in  `og:image`

I have performed same with Product [Basic Membership](http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/shop/product/basic-membership-33)

Main Product with ID 33: [Basic Membership](http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/shop/product/basic-membership-33)

```

<meta property="og:url" data-oe-id="2350" data-oe-model="ir.ui.view" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/div[1]/t[1]/meta[2]" content="http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/shop/product/basic-membership-33"/>

<meta property="og:image" data-oe-id="2350" data-oe-model="ir.ui.view" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/div[1]/t[1]/meta[3]" content="http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/web/image/product.template/33/image"/>
```

Duplicate Product with ID 478: [Basic Membership (copy)](http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/shop/product/basic-membership-copy-478)


```
<meta property="og:url" data-oe-id="2350" data-oe-model="ir.ui.view" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/div[1]/t[1]/meta[2]" content="http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/shop/product/basic-membership-copy-478"/>

<meta property="og:image" data-oe-id="2350" data-oe-model="ir.ui.view" data-oe-field="arch" data-oe-xpath="/t[1]/t[1]/div[1]/t[1]/meta[3]" content="http://285830-10-0-fix-bad-sudo-ape-2a9e6e.runbot8.odoo.com/web/image/product.template/478/image"/>

```

**Comment by Yenthe666** [comment]
Indeed, double checked this on the latest V10 runbot too and this is no longer the case.
@puakinsin please update your Odoo to the latest codebase.
