### ISSUE TITLE
Odoo 11.0E  - Permissions error product.product read operation

### ISSUE THREAD

**Issue by thegunshow** [odoo/odoo#21546]
Impacted versions: 11.0E

Steps to reproduce: Multi company, give 1 user all permissions but only allow then to have access to 1 company.

Create sales order, click "Create invoice" button

Current behavior: 

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.(Document type: product.product, Operation: read)

Logs:
```
odoo.models: The requested operation cannot be completed due to record rules: Document type: product.product, Operation: read, Records: 29, User: 14
odoo.models: The requested operation cannot be completed due to record rules: Document type: product.product, Operation: read, Records: 29, User: 14
werkzeug: 105.184.134.192 - - [10/Dec/2017 21:06:45] "POST /web/dataset/call_kw/sale.advance.payment.inv/default_get HTTP/1.1" 200 -
werkzeug: 105.184.134.192 - - [10/Dec/2017 21:06:45] "POST /web/dataset/call_kw/sale.order/read HTTP/1.1" 200 -
werkzeug: 105.184.134.192 - - [10/Dec/2017 21:06:45] "POST /web/dataset/call_kw/sale.order.line/read HTTP/1.1" 200 -
werkzeug: 105.184.134.192 - - [10/Dec/2017 21:06:46] "POST /web/dataset/call_kw/account.tax/read HTTP/1.1" 200 -
werkzeug: 105.184.134.192 - - [10/Dec/2017 21:06:46] "POST /web/dataset/call_kw/res.partner/name_get HTTP/1.1" 200 -
```
Expected behavior: Create an invocie

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/16087167/33809509-b03cb2ac-de00-11e7-8a41-438792882c85.png)

**Comment by jboilesen** [comment]
+1 waiting for solution

**Comment by pedrobaeza** [comment]
This is a misconfiguration in your part, using products with the company field set with the other company. You should leave that field empty or use another product. Closing as no real issue.

**Comment by jboilesen** [comment]
No, it's not with the other company (!!!)

**Comment by jboilesen** [comment]
I found that "Down Payment" (product template) has something to do with this. It's not a configuration issue, since Odoo may be assigning Down Payment to a company and making it impossible to generate invoices to other companies.

It needs some investigation since this issue is reported since Odoo 8. :)

**Comment by jboilesen** [comment]
Yes! This is it: In a Multi Company environment, Down Payment must be assigned to the Company to let that specific company generate Invoices ─but the other companies will be unable to generate invoices.

**Comment by jboilesen** [comment]
SOLVED!

To solve this: set the company_id of the Down Payment product template equals to "NULL". ;)

**Comment by pedrobaeza** [comment]
As said, misconfiguration in your part :wink: so I don't deserve the thumb down.

**Comment by jboilesen** [comment]
In part misconfiguration: Odoo shouldn't allow this to happen

**Comment by pedrobaeza** [comment]
Well, putting a lot of constraints can be counterproductive in some cases, and more in a specific use case like this one IMO. Any way, if you see clearly an improvement over the default values for data or where to constraint this, you can make a PR improving that (against master branch).

**Comment by TaRaDa14** [comment]
> > SOLVED!
> > To solve this: set the company_id of the Down Payment product template equals "NULL". ;)
> 
> Thank You

Where change this ?

**Comment by tono88** [comment]
> > > SOLVED!
> > > To solve this: set the company_id of the Down Payment product template equals "NULL". ;)
> > 
> > 
> > Thank You
> 
> Where change this ?

Did you find where?

**Comment by jboilesen** [comment]
@tono88 @TaRaDa14 : look in your database in the products table. There must be a row for Down Payment there - than just nullify the company_id.
