### ISSUE TITLE
Parse error in module, key allready exists

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21554]
Impacted versions:
11.0

I have two l10n modules. Both provides check if new currency is created in xml files:
```
       <record id="BYN" model="res.currency">
            <field name="name">BYN</field>
            <field name="symbol">руб.</field>
            <field name="rounding">0.01</field>
            <field name="active" eval="True"/>
            <field name="currency_unit_label">Ruble</field>
            <field name="currency_subunit_label">Kapeyka</field>
        </record>

```
So if I try to install the second one, I become res_currency_unique_name error: (name)=(BYN) allready exists.

How can I say to odoo, that if that record exists, it shouln't create it, but if not - to create?

**Comment by sswapnesh** [comment]
Hello @sergeiruzkiicode 

I think you can use the same record id in both modules.

` <record id="base.BYN" model="res.currency">`

**Comment by sergeiruzkiicode** [comment]
Indeed - one currency, one id. So question is, how can I say to odoo "update or create" instead of "create"

**Comment by sswapnesh** [comment]
It will do the same.

It will create new record if the record id doesn't exists,  and will update
if record exists.

**Comment by sergeiruzkiicode** [comment]
It must do the same. And it does if we have one module. But in different I become an duplicate error ((

**Comment by sswapnesh** [comment]
Hello @sergeiruzkiicode 

Same should Work in two modules as well.

   ```
        <record id="base.BYN" model="res.currency">
            <field name="name">BYN</field>
            <field name="symbol">руб.</field>
            <field name="rounding">0.01</field>
            <field name="active" eval="True"/>
            <field name="currency_unit_label">Ruble</field>
            <field name="currency_subunit_label">Kapeyka</field>
        </record>
```
When you are installing first module you will get log for same.

`db_name odoo.addons.base.ir.ir_model: Creating the ir.model.data BYN in module base instead of first_module.`

and when you will install the second module it will automatically `write` to that record.

You can close this issue if this works.

**Comment by sergeiruzkiicode** [comment]
It is one more thing: someone can add new currency value by hand. And if I install module - it gives me an error too: dupliate names and ids.

**Comment by sswapnesh** [comment]
> It is one more thing: someone can add new currency value by hand. And if I install module - it gives me an error too: dupliate names and ids.

I don't think there is way to manage this .
What do you think @pedrobaeza  ?

**Comment by pedrobaeza** [comment]
You have to use same full XML-ID (`base.BYN`) for example, although it has a side effect of the currency not being removed on uninstallation.

Any way, this is not an Odoo issue, but programming question, so I close.

**Comment by pedrobaeza** [comment]
About manual addition: you have to remove that currency also by hand prior to install the module or assign manually the same XML-ID as the one being installed. Constraints are for preventing inconsistencies, so if an inconsistency is raised, you have to solve it.
