### ISSUE TITLE
[11.0] When calculating the payroll, the value set in the field hr.payslip.structure_id is not used

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#21567]
**Impacted versions:**
11.0 
**Steps to reproduce:**
  - Create payslip
  - Add a contract with any structure
  - Add a structure in payslip, different from the one defined in step 2
  - Confirm or compute sheet

**Current behavior:**
Payslip is computed using the contract structure

**Expected behavior:**
Payslip should be computed using the payslip structure

**FYI:**  This is an issue because, sometimes, it's necessary to pay the employee using a structure different from their contract, e.g. in case of Christmas bonuses

**Video/Screenshot link (optional):**
[Video](https://www.youtube.com/watch?v=32H01n503uU&feature=youtu.be)

**Comment by Yenthe666** [comment]
Thanks a lot @nim-odoo! @maitaoriana this has been fixed in https://github.com/odoo/odoo/commit/3a79d2cf2e02a2337b7dcc0a8a54dff32c6eb2b9 😄
