### ISSUE TITLE
Cannot print PDF reports with the correct wkhtmltopdf version

### ISSUE THREAD

**Issue by jl2035** [odoo/odoo#21562]
Impacted versions: Odoo10
wkhtmltopdf --version
wkhtmltopdf 0.12.1 (with patched qt)

Steps to reproduce: Create an invoice and try to print it

Current behavior: The error pops up: "Wkhtmltopdf failed (error code: -11). Memory limit too low or maximum file number of subprocess reached. Message : " and message is empty. This is really stupid as I have enough RAM on my VPS and the invoice I'm trying to print is just one page. 

Expected behavior: I should get the pdf file to download..

**Comment by Yenthe666** [comment]
Hi @jl2035,

The memoy limit means your server doesn't have enough RAM, can you add more RAM and try again please?

**Comment by jl2035** [comment]
Should be enough for one page report:

```
free -h
total        used        free      shared  buff/cache   available
2.2G        1.3G        771M        218M        143M        796M
```

I cannot add RAM.

**Comment by jpaulin** [comment]
Remember reading, not long ago, some posting about especially PNG images within wkhtmltopdf; they used for some reason, at least these cases, totally uncompressible (we're not talking quality loss, but basically huffman encoding ie. run-length compression + a code tree) PNG images where even simple ones then started to be 150 MB or more. Do you have any images on the said invoice?

**Comment by jl2035** [comment]
I had a png company logo, now replaced it with a jpg image and still getting the same error :(

**Comment by gdgellatly** [comment]
@jl2035 The first thing to check is worker memory.  Start odoo with --workers=0.  If it works, then your problem is worker memory settings.  With only 2GB RAM you probably won't be able to run workers anyway, given a reasonable minimum setting is roughly 1GB.

**Comment by jl2035** [comment]
@gdgellatly you are correct! With 0 workers I successfully printed an inovice. So you are saying there is no reason for me to run workers. Otherwise I must say this instance is doing quite well with only 2GB.

**Comment by Yenthe666** [comment]
Aha, good catch @gdgellatly 
Workers are usually used when you have a lot of users and a lot of RAM, not with an instance with only 2GB of RAM. Almost 1GB of that RAM is already used for the OS itself, so there is not much left for Odoo itself.

**Comment by gdgellatly** [comment]
@jl2035 Not really if its a small instance with a few users. Even now for larger instances I'm seeing a trend away from workers (at least a large number of them) to multiple containers spread across multiple servers - although thats solving a different set of problems.

**Comment by bhaskarreddyg** [comment]
**Wkhtmltopdf failed (error code: -6). Message: b'The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display \n**



showing above error while printing the reports in odoo server

**Comment by jl2035** [comment]
@bhaskarreddyg I don't think this is related. Why not open a new issue?

**Comment by udamuri** [comment]
I have an error like this Wkhtmltopdf failed (error code: -8). Message: b''

**Comment by vijaykumar-odoo** [comment]
I have try this. Problem has been fixed:

sudo apt install ttf-mscorefonts-installer
sudo fc-cache -f -v

**Comment by udamuri** [comment]
> I have try this. Problem has been fixed:
> 
> sudo apt install ttf-mscorefonts-installer
> sudo fc-cache -f -v

thank you  @vijaykumar-odoo , it works

**Comment by mutamizh** [comment]
> I have try this. Problem has been fixed:
> 
> sudo apt install ttf-mscorefonts-installer
> sudo fc-cache -f -v

It's worked for me. Tons of thanks.
