### ISSUE TITLE
Odoo 11 enterprise on premise demo version

### ISSUE THREAD

**Issue by F3000** [odoo/odoo#21560]
is there any possibility to install the enterprise version on premise as a trial version ? 

I cant use the web demo. I will test it with some internel data ...

**Comment by Yenthe666** [comment]
Hi @F3000,

If you're an official Odoo partner you have an enterprise test license for demo instances. Otherwise you can install an Odoo with a new database and use the trial for 30 days, without extending it. 
Or, alternatively, you can use a runbot.

Regards,
Yenthe

**Comment by F3000** [comment]
thnaks for answering.

I'm not an odoo partner. Where i can find the option for the 30days trial ? 

Runbot is not on premise ;(

**Comment by Yenthe666** [comment]
Hi @F3000,

Well, the runbot instances have that by default.
When you have an Odoo enterprise installed you can create new databases that last for 30 days without a license. The downside is that you need to be a partner or have access to the enterprise repository of Odoo (at github.com/odoo/enterprise) to be able to install it.

Regards,
Yenthe

**Comment by fpodoo** [comment]
I'm not an odoo partner. Where i can find the option for the 30days trial ?

It's online, not on premise: https://odoo.com/start

You can test all apps there. It's easier than on premise as everything is
automatically configured for you (email gateways, dns...)


-- 
Fabien

**Comment by F3000** [comment]
It's online, not on premise: https://odoo.com/start 

-> So when i fill it out with my data it is save for 15 days ? 

When i want to access the enterprise repo, i have to buy the enterprise license ?
