### ISSUE TITLE
[USABILITY] Export widget with technical name

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#21573]
Impacted versions: all

Steps to reproduce: no special (just export)

Current behavior: Especially if working in a multilanguage situation, it is very error prone to obtain the right column names... as there is no mapping handily available.

Expected behavior: In developer mode, both panels should be a two column list with the technical name of the field. This technical name then should also be the "orderby" bit.

Additionally: There should be a checkbox which exports the model with column description (to be skipped by an offset in import or simply being deleted before import).

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e what do you think about this idea? I think it would be neat. At the moment it can be a bit of a hassle to get the right columns in other languages.

**Comment by pedrobaeza** [comment]
Meanwhile, check module https://github.com/OCA/server-tools/tree/10.0/base_export_manager that performs that.

**Comment by Yenthe666** [comment]
@pedrobaeza OCA really has it all, doesn't it?

**Comment by pedrobaeza** [comment]
Well, there a a lot of use cases that OCA covers indeed
