### ISSUE TITLE
After backorder, moves are still linked to pack operations of initial picking

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#21620]
Impacted versions: 8.0, 9.0, 10.0

Make a backorder of a picking.
In the method _create_backorder in stock.picking:
The not done moves are linked to the new picking.
However the table that links operations to moves is not updated. And the initial picking still has the operations (tested on 8.0).
So the new backorder has moves, no pack operations yet but the moves are linked to pack operations of the initial picking.
When action_done is called on a move, the operations linked to the move are processed (not the operations of the backorder picking). This could cause serious issues.

For instance, I faced in a backorder picking the "The roundings of your Unit of Measures %s on the move" error (raised by action_done) due to an old pack operation on the initial picking. So while there was no pack operation on the picking, the move could not be processed.

**Comment by jco-odoo** [comment]
These things are normally recalculated (as it is a new picking) and normally only moves without links go to the backorder.  It would be interesting to know what triggered the move from the other picking.
