### ISSUE TITLE
[11.0] Sequence problem with monthly date_range

### ISSUE THREAD

**Issue by my1649** [odoo/odoo#21624]
Impacted versions: V11.0-20171030 CE

Steps to reproduce: 
Go to the Sequence under developer mode
Edit the Customer Invoice and set the rules as following:
Prefix: INV/%(year)s%(range_month)s-
Size: 3
Subsequences : checked
Delete the data on the list of Date_Range and input the following (mm/dd/yyyy)
12/01/2017 to 12/31/2017
01/01/2018 to 01/31/2018
02/01/2018 to 02/28/2018

Create a new invoice, and make the invoice date in March, 2018, which is out of the date_range we have above. Save and generate the sequence.

Current behavior:
Invoice Sequences are generated as
INV/201803-001 on the Invoice dated in March (Correct)
INV/201803-002 on the Invoice dated in March (Correct)
INV/201803-003 on the Invoice dated in April (Wrong)
INV/201803-004 on the Invoice dated in May (Wrong)
And the new row on the list of date_range is generated from 03/01/2018 to 12/31/2018

![sequence_range_month](https://user-images.githubusercontent.com/25192449/33939888-d0f0d278-e047-11e7-9f4c-8fbaeb0e4271.jpg)

Expected behavior:
The sequences shall be generated as
INV/201803-001 on the Invoice dated in March 
INV/201803-002 on the Invoice dated in March 
INV/201804-001 on the Invoice dated in April 
INV/201805-001 on the Invoice dated in May 

New row of date_range should be following the "range_month" generated as:
03/01/2018 to 03/31/2018

**Comment by Yenthe666** [comment]
@mart-e to check 😉

**Comment by mart-e** [comment]
I confirm the bug once but could not always reproduce it.
Need a bit more investigation but there is indeed something wrong depending on how you generate your sequences.

**Comment by mart-e** [comment]
Hello,

I have checked this bug again and actually, what you are trying to do is not supported. When automatically generated, the auto-generated sequences ranges are increased on a one year basis.
The generated range is something like:
![screenshot-2018-2-5 customer invoices - odoo](https://user-images.githubusercontent.com/564822/35790653-8d849f32-0a69-11e8-9076-f51df168e09c.png)

where you clearly see that the last range is 2018-03-01 -> 2018-**12-31**. So it is logical the invoice is April is INV/201803-003 (03 as you are using the March range).

There is no settings to say that the sequence must be generated on a monthly basis. If you really want a monthly sequence, you have to generate it in advance.

**Comment by my1649** [comment]
As we set the "range_" with the month above, I believe the date range shall be applied and generated monthly. Does it mean that "range_" only apply on year, and that is the only purpose for "range_"? Just wondering... 
Thanks!

**Comment by mart-e** [comment]
How could Odoo know that you want month? By making a regex to see in 'year' or 'month' is present in the sequence string? Not very clean, we need to have a proper setting to generate on a per year/month/day basis.

The sequence format and generation are two different things. You could even make a sequence with day code if you want but needs to create the range yourself (e.g. server action).

**Comment by satriani-vai** [comment]
Take a look to this module [auto_reset_sequence](https://apps.odoo.com/apps/modules/11.0/auto_reset_sequence/)
Not tested yet, but I think this do the trick.
