### ISSUE TITLE
[11.0] "Set Defaults" function create wrong "User-defined Defaults" records 

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#21639]
**Impacted versions:**
11.0

**Steps to reproduce:**
1. Activate developer mode.
2. Choose any form view, e.g. create a customer.
3. Select "English" as the `Language`, or other fields that you wish to set a default value.
4. "Open Developer Tools" -> "Set Default".
5. Choose "Language = English" as the `Default`.
6. Choose "Only you" / "All users"
7. Save defaults

**Current behavior:**
The "Users-defined Defaults" record created does not have the correct user,
e.g. if you chose "Only you" in 6. , the `User` of the record will be empty (False). 
And the `User` will be set with the login-ed user if you chose "All users".
_Although you could change the users of the record manually to change back the behavior._

**Expected behavior:**
Choose "Only you" in 6. , the `User` of the record will be set with the login-ed user.
Choose "All users" in 6. , the `User` of the record will be empty (False).

**Comment by GillPotter** [comment]
This was still an issue on my 1st March 2018 Odoo V11 community build, but is now working as expected on my 30th March 2018 build. Don't know when it was fixed but I think it was!

**Comment by TimLai125** [comment]
@GillPotter Thank you for the information. Then it should be a commit within March that fixed the issue, please let me know if you find the corresponding commit. =]

**Comment by Yenthe666** [comment]
Hi guys,

As @GillPotter mentioned it was fixed I'm closing this. If there should still be a problem just respond and I'll reopen.

Regards,
Yenthe
