### ISSUE TITLE
Binary widget shows Base64 up to first save and old filename up to following save when uploading a different file.

### ISSUE THREAD

**Issue by Nick-OpusVL** [odoo/odoo#21630]
The current behaviour of the default Binary widget is confusing to end users.

Impacted versions:

* 10.0

Steps to reproduce:

* Create a database with demo data enabled
* Install 'sale' module from core
* Install this module: https://github.com/OpusVL/odoo-examples/tree/10.0/example_binary_field
* Sales -> Customers -> Agrolait
* Click Edit
* Next to the field 'Signed Contract' click Upload a File
* Choose a file, for example a PDF and attach it

Current behavior:

* The Base64 representation of the file is filled in in the field until you press Save, at which point the filename is then correctly written.
* If you press Edit again, the filename is shown correctly, however if you re-upload another file then the old filename stays there until you press Save again.

Expected behavior:

* The filename is filled in straight away when first filling it in, without exposing the Base64 encoded representation
* When replacing an existing uploaded file, the displayed filename should also change straight away.

Screenshot:

![spectacle zu6090](https://user-images.githubusercontent.com/7963793/33943862-3601d238-e012-11e7-83ae-d853f51cf422.png)

**Comment by sswapnesh** [comment]
@Yenthe666 
I can confirm this issue.

Just reproduced same on [Runbot](http://286140-10-0-1022e4.runbot8.odoo.com/web?debug#view_type=form&model=ir.attachment&menu_id=36&action=20)


![](https://image.prntscr.com/image/bGsa77RnQNCjgtqIhggCXQ.png)

**Comment by Yenthe666** [comment]
Yeah it is absolutely true. Just not sure who should look at this though. @ged-odoo maybe?

**Comment by Nick-OpusVL** [comment]
I've created a PR fixing this: #24275
