### ISSUE TITLE
[11.0]  want child packages feature back

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#21637]
Impacted versions:
11.0

Steps to reproduce:
odoo 10 support child packages, odoo 11 does not support this no longer.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
@mart-e @Yenthe666   how about this?

**Comment by Yenthe666** [comment]
More of a question for @sle-odoo as he is for stock. Anyways as this would add a feature it would automatically go in V12 if any new field or big(ger) change is needed.

**Comment by mart-e** [comment]
Hello,

Sorry but this feature was indeed removed. It was not considered as a mandatory feature during the refactoring and we do not plan to reintroduce it, sorry about that.
