### ISSUE TITLE
[11.0][BUG] follow-up report ignores language settings on partner

### ISSUE THREAD

**Issue by giordano-ch** [odoo/odoo#21632]
Impacted versions:
Tested on version 10 and 11 

Steps to reproduce:

1. Install more than one language (my example: English and German)

2. Create a new company in contacts and set checkbox "is a customer" (or use existing customer)

![1-1-company-english](https://user-images.githubusercontent.com/15436224/33945293-e5d2a212-e01e-11e7-98f1-dd4986be25de.JPG)

3. Create a customer invoice for this company and set due date in the past

![1-2-invoice](https://user-images.githubusercontent.com/15436224/33945303-f31f498e-e01e-11e7-871e-6e89a275b905.JPG)

4. Go to the contact -> Print -> Due Payments

Current behavior:

The text of the report gets translated based on the user language
The labels of the report get translated based on the partner language

Print: User Language English Customer Language German
![1-3-print-user-en-customer-de](https://user-images.githubusercontent.com/15436224/33945327-0213a32c-e01f-11e7-8a95-404eca7e8b1c.JPG)

Print: User Language English Customer Language English
![1-4-print-user-en-customer-en](https://user-images.githubusercontent.com/15436224/33945384-30eb5b9a-e01f-11e7-91d2-f034635ae927.JPG)

Print: User Language Deutsch Customer Language English
![1-6-print-user-de-customer-en](https://user-images.githubusercontent.com/15436224/33945414-46160ec0-e01f-11e7-860e-8b86afb6da29.JPG)

Print: User Language German Customer Language German
![1-7-print-user-de-customer-de](https://user-images.githubusercontent.com/15436224/33945452-65fa46d4-e01f-11e7-8d57-f57f41cdbb43.JPG)

Expected behavior:

The Text of the report should get translated based on the partner language

**Comment by Yenthe666** [comment]
Hi @giordano-ch,

Thanks for the report! There seem to be quite some things wrong with this honestly. Do this:
1. Install a second language (Dutch in my example)
2. Create a new customer (YenCustomer for example)
3. Create an invoice for this customer and set the due date back a few months
4. Validate the invoice
5. Go back to the customer (YenCustomer in my example) and click on the smart button "$ xx.xx due"
6. Click on "Print letter"
=> The letter is now printed in English (see https://i.imgur.com/QeQUQiU.png)
7. Change the user his language (in my example to Dutch), hit F5, click on "$ xx.xx due" and print the report again
=> Part of the letter is in the user his language, while the customer its language is untouched. (see https://i.imgur.com/a2wudAO.png)
8. Change the user his language back to English and change the customer his language from English to Dutch, hit F5, click on "$ xx.xx due" and print the report again
=> The Dear Sir/Madam text is now translated and the rest of the document is now in English, while it should also be in Dutch. (See https://i.imgur.com/f0kub1D.png)
=> The form view is now partially translated in Dutch while the user his language in English and the customer his language is Dutch. The view should still be in English in this case. The invalid logic is also in the view itself (See https://i.imgur.com/FKApVSo.png) 

Conclusion: both the view and the report are incorrect in both cases.

OPW 788301

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hey @giordano-ch,

This has been fixed in https://github.com/odoo/enterprise/commit/68478f10249894be9ccf5e2367109cb06133f699 and should all work fine now. Everything looks fine at my end!

**Comment by giordano-ch** [comment]
Hi @Yenthe666 

Is the fix for Community Version still in progress or why is it only fixed for enterprise?
Community Version has the same problem, but the report is in the account module (template name: account.report_overdue)

Thanks in advance for your answer.

**Comment by Yenthe666** [comment]
Hi @giordano-ch,

@nim-odoo can probably answer this better as he made the fix.

**Comment by sudo-san** [comment]
Hi @nim-odoo 

Any updates on this?

I see the fix was only made for enterprise? Can we expect a fix for community version?

Best Regards
