### ISSUE TITLE
[account] Bank statement does not allow to enter amounts in foreign currency

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#21645]
Impacted versions:
9.0, 10.0, 11.0

Steps to reproduce:
1. Set up a company with main currency USD
1. Create a new bank statement for a bank journal using the company currency
2. Try to enter a payment for an paid in EUR. 

Current behavior:
It is not possible to indicate the payment amount in the foreign currency. Only in the company currency, because the fields 'currency_id' and 'amount_currency' are hidden.

Expected behavior:
The fields 'currency_id' and 'amount_currency' should be visible.

Additional information:
These fields were hidden in the commit:
https://github.com/odoo/odoo/commit/c538bedd53ab1dd5f01eccf2947a04585ecf470b

But this makes no sense, because the banks very often provide the amount that was paid in the foreign currency, and this amount often matches an invoice that was issued using the same foreign currency. But still, you want to use a bank in the main company currency.

For example, a US company has a customer from Europe, and issues invoices to them in EUR. The customer pays in EUR to the company, but to a company's bank account that is in USD.

One would expect to be able to record the paid amount in EUR, and reconcile this amount with the invoice amount in EUR.

cc @fclementic2c @qdp-odoo @mreficent

**Comment by qdp-odoo** [comment]
Hi Jordi,

unfortunately, I cannot confirm that as an issue: it has been hidden on purpose (usability), because it was confusing people.

Fortunately, the feature still exists and you just have to customize a little bit the view. And with studio, it should be less and less a problem.

have a great day ahead
