### ISSUE TITLE
[Wishist] Update FontAwesome from V4.7 to V5

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#21648]
Impacted versions: 11.0 and above

Current behavior: Odoo it using FontAwesome 4.7.0 at the time of writing (see https://github.com/odoo/odoo/tree/11.0/addons/web/static/lib/fontawesome) while V5 is already released.
For more information see http://fontawesome.io/icons/

Expected behavior: Add FontAwesome V5 to Odoo 11 and up.

**Comment by Yenthe666** [comment]
@qsm-odoo perhaps something for you too? 😄

**Comment by qsm-odoo** [comment]
@ged-odoo (see OPW)

**Comment by Yenthe666** [comment]
Official statement is that this will be added but in Odoo V12.

**Comment by lukebranch** [comment]
it would be great to see some SVG/JS support as well if possible. It opens up some additional design possibilities as well, eg.:

https://fontawesome.com/how-to-use/svg-with-js#layering

On an unrelated note (unrelated to this issue thread), are there any plans on better support SVG's in printed reports? It's currently pretty tricky to integrate SVG's into reports using the standard methods. 

I've had a bit of trouble integrating SVG's back in 9.0, and have had to do something like this:

<img src="data:image/svg+xml;base64 ............=="/>

**Comment by Yenthe666** [comment]
@lukebranch agreed that better SVG support would be neat. Google is pushing hard towards it too.
Perhaps another wishlist report to keep things separated?

**Comment by lukebranch** [comment]
@Yenthe666 ,

I definitely agree. I'll create another issue detailing the main points later today and tag you on it.

**Comment by Julien00859** [comment]
On going effort https://github.com/odoo/odoo/pull/48094
