### ISSUE TITLE
Contact, Employee, User relations

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21650]
Impacted versions:
11.0e

There are many places, where we store information about user.
1. User: we store email there. 
We see "Related Partner" in user view only in Debug mode
If we change email - it is changed in Contact(partner)

2. Contact (Partner)
We see much more information about user, but there is no sign, that it is our user. If we will have contacts with the same Name/Surname, user can be confused.
Can there be a sign like "Is employee" or "Related user"

3. Emploee
We have non required field related user.
We try to send message to emploee:
if there is emploee-user relation - it goes to user email
if not - message goes to followers only(to none)
how do we user user work email? 
There is no connection between phones, job positions etc.
In field work adress we can choose... Contact of emploee itself as partner

I think, connections between hr.employee, res.partner, res.users must be cleared

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

Thanks a lot for the report.
All the cases that you describe are actually intended behaviour and work as expected. There is no intention to change this at this point plus these kind of changes wouldn't even be possible in a stable version.
Nevertheless I've labeled it with functional review so somebody else can still look at it eventually (if wanted).

Regards,
Yenthe
