### ISSUE TITLE
Accounting Configuration is too hard

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21656]
Impacted versions: 11.0

Steps to reproduce:
As an easy example, create a new company.
Now add a user to the company before you can configure it.
Now switch to that company.
Now go to settings and click invoicing.
Now choose a chart of accounts, set a fiscal year and choose anglosaxon accounting.
Click save.

Ok so sometimes the fiscal year saves, sometimes not, anglosaxon never does and generally the chart works.

**Comment by Yenthe666** [comment]
@lap-odoo could you have a look at this from a functional point of view please? I know you're very active on the accounting part of Odoo so I think you're the best person for this.

**Comment by lap-odoo** [comment]
@gdgellatly : 

Did you report that to our Support? For me, this is not functional but technical. If you set different settings and save the settings page, I expect to have all of them saved. If you report that to our support (odoo.com/help) they could have a look at this and ask our bug fix team to solve it if possible.

**Comment by gdgellatly** [comment]
@lap-odoo Just reopen this issue, my accounting is configured now, so I'm in no rush.

**Comment by Yenthe666** [comment]
Indeed - closing is a bit invasive. @gdgellatly can you please report it through the official channel too and add the number of the ticket here?

**Comment by gdgellatly** [comment]
@Yenthe666 was a customer demo so not OPW.

**Comment by Yenthe666** [comment]
@gdgellatly just log it under another customer that uses this version - I tend to do that too 😉

**Comment by mart-e** [comment]
Hi,

Is this one still an issue?

**Comment by gdgellatly** [comment]
@mart-e I honestly don't know, but as a general rule most configuration is better now.
