### ISSUE TITLE
web responsive no active i have installeed web_responsive module

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#21664]
Impacted versions:
10.0
Steps to reproduce:
android browser  link demo10.ideawork.link
Current behavior:
no web responsive
Expected behavior:
si web responsive
Video/Screenshot link (optional):

![odoo_mobile](https://user-images.githubusercontent.com/4387127/34037664-fb265188-e189-11e7-86aa-53e7484b498d.jpeg)

**Comment by pedrobaeza** [comment]
That's a frontend website, not backend, which is the goal of the module. More over, this is Odoo, and the module is OCA, so it's not the proper place to publish this. Please close this issue.

**Comment by Yenthe666** [comment]
Indeed - not the right place. Plus, loads of custom modules added.
