### ISSUE TITLE
[8.0] Using a for loop in email templates in a table structure will lead to non functional email templates

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#2166]
When trying to use a for loop (% for) in email templates in a table structure the for loop will be rendered before the table.

**_Impacted versions:**_
- 8.0 and above

**_Steps to reproduce:**_
1. Update a sale order email template in odoo backend for example
2. Switch to the source view of the html editor in the sale order email template detail view
3. Add the following code snippet and save the email template

```
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        % for line in object.order_line:
        <tr>
            <td>${line.product_id.name}</td>
            <td>${line.product_uom_qty}</td>
        </tr>
        % endfor
    </tbody>
</table>
```

**_Current behavior:**_
- the code part is rendered in this way which leads to an error in the log because "line" is not defined in "line.product_id.name"

```
% for line in object.order_line: % endfor
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>${line.product_id.name}</td>
            <td>${line.product_uom_qty}</td>
        </tr>
    </tbody>
</table>
```

**_Expected behavior:**_
- the code part should be rendered in this way

```
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        % for line in object.order_line:
        <tr>
            <td>${line.product_id.name}</td>
            <td>${line.product_uom_qty}</td>
        </tr>
        % endfor
    </tbody>
</table>
```

**Comment by loiclavoie** [comment]
Still having this issue in 2015

**Comment by mylbco** [comment]
I'm having the same issue +1

**Comment by StefanRijnhart** [comment]
See https://www.odoo.com/forum/help-1/question/if-endif-does-not-seem-to-work-with-mail-templates-sent-e-mails-are-blank-74389

**Comment by rruebner** [comment]
After some more research I come to the conclusion that the problem is not related to the for-loop itself. The problem is the for-loop in combination with the \<table\> tag. If you build a table with CSS the for-loop works.

For example the following code works in email templates.

```
<div style="display:table;">
    <div style="display:table-header-group;">
        <div style="display:table-row;">
            <div style="display:table-cell;">Name</div>
            <div style="display:table-cell;">Quantity</div>
        </div>
    </div>
    <div style="display:table-row-group;">
        % for line in object.order_line:
        <div style="display:table-row;">
            <div style="display:table-cell;">${line.product_id.name}</div>
            <div style="display:table-cell;">${line.product_uom_qty}</div>
        </div>
        % endfor
    </div>
</div>
```

**Comment by anj4u** [comment]
the issue is still there. Has anyone a solution?

**Comment by kevin8909** [comment]
the issue still stucks, any solution?

**Comment by anj4u** [comment]
the only solution until i know now is not to use tables (tr, td) in the for loop. Use divs to solve it.

**Comment by Yenthe666** [comment]
Hi @rruebner,

Thank you for your bug report and the alternative way around the bug.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by geekobi** [comment]
Thank to rruebner, his solution works perfectly.
To set it closer to table/tr/td/th tags, I use html classes which include also borders which are natural with table/tr/etc... and not with div :

	.tem_table{
		display:table;
		border-top:1px solid;
		border-left:1px solid;
	}
	.tem_trh,
	.tem_tr{
		display:table-header-group;
	}
	.tem_tdh{
		display:table-row;
		font-weight:bold;
	}
	.tem_td{
		display:table-row;
	}
	.tem_tch,
	.tem_tc
	{
		display:table-cell;
		padding: 2px 4px;
		border-bottom:1px solid;
		border-right:1px solid;
	}

example of use :

	<div class="tem_table">
		<div class="tem_trh">
			<div class="tem_tdh">
				<div class="tem_tch">Type de produit</div>
				<div class="tem_tch">Description</div>
			</div>
		</div>
		<div class="tem_tr">
			% for oline in object.order_line:
				<div class="tem_td">
					<div class="tem_tc">${oline.sale_layout_cat_id.name or ''}</div>
					<div class="tem_tc">${oline.description or ''}</div>
				</div>
			% endfor
		</div>
	</div>

note : the use of border-left/top/right/bottom is needed because I want borders of 1 px. I you want 2 px, you can use simply border:1 px instead

**Comment by ivantodorovich** [comment]
It's still a bug on `9.0`

**Comment by horanet-admin** [comment]
It's still a bug on `10.0`

**Comment by Yenthe666** [comment]
I'll reopen this as two people confirm it in higher versions that are still supported.

**Comment by Creamaster** [comment]
@Yenthe666 thank you.

PS: I think the workaround (using CSS table) isn't useful in some cases, as several email clients still need <table> tag to render the mail correctly. (I’m thinking about Outlook)

**Comment by Creamaster** [comment]
@Yenthe666 The issue still exists in `11.0`. It's easily reproduceable (I tried on runbot instances) as some Odoo data contains nested for loop in HTML table

Steps :  

1. Open the mail.template list view

2. Search 'Simple Challenge Report Progress', open view form
(xml_id = `gamification.simple_report_template`)

3. Using the preview button or entering edition mode will break the source (body_html field)

**Comment by Yenthe666** [comment]
@Creamaster the preview looks ok though? See this:
![image](https://user-images.githubusercontent.com/6352350/44716941-f886f300-aabb-11e8-879e-b71f5fb3b33f.png)

**Comment by Creamaster** [comment]
@Yenthe666  Indeed, my bad, only the edition mode/save break the code.

**Comment by Yenthe666** [comment]
Got it, indeed! That's a bug, I can confirm.
@mart-e who can check this one? Present in V9, V10 & V11.

**Comment by mart-e** [comment]
Hi,

Yes, it is a known issue. @Yenthe666 even opened an issue about it some time ago :wink: 
See #4671 for details, we do not recommand to use the wysiwyg editor for email templates.
We do not plan to fix the editor but rather switch to QWeb instead.
Something we have been working on for some time (at #16726)

**Comment by trainoasis** [comment]
Still an issue in 2020, tables are quite required for legacy mail clients unfortunately - we need TR tags :D

**Comment by Cl0ut1eR** [comment]
still here in 2025 on odoo 17 using \<t t-foreach="records" t-as="rec">
