### ISSUE TITLE
[BUG]compute fields depends on user.employee_ids.department_id field raise a error

### ISSUE THREAD

**Issue by kevin3274** [odoo/odoo#2167]
compute fields depends on user.employee_ids.department_id field raise a error

**_Impacted versions:**_
8.0
**_Steps to reproduce:**_
1.write a compute field like this

```
    @api.depends('user_id.employee_ids.department_id')
    def _compute_department_id(self):
        self.department_id = self.user_id.employee_ids and self.user_id.employee_ids[0].department_id.id or False
```
1. goto Human Resource->Employees, open and edit one employee, change the department_id field, save it ,
   report error:
   ProgrammingError: column "user_id" does not exist
   LINE 1: SELECT "user_id" FROM "hr_employee" WHERE "id" IN (1)

**Comment by Yenthe666** [comment]
Hi @kevin3274,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
