### ISSUE TITLE
[11CE] avg attribute in field tag works like sum not avg

### ISSUE THREAD

**Issue by grzegorz-openglobe** [odoo/odoo#21673]
Impacted versions: 11

Steps to reproduce: Write XML view with avg attribute in float field tag.

Current behavior: All values are summed on grouping bar when you group records in tree view.

Expected behavior: Values should be aggregated as Average value.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @grzegorz-openglobe 

I just tested Same on [Runbot](http://286583-11-0-c12ff1.runbot14.odoo.com/web?debug#view_type=list&model=sale.order&action=715) and seems working fine.

`<field name="amount_total" avg="Total Tax Included" widget="monetary"/>`

![](https://image.prntscr.com/image/FLiXUDzjR-y2_vQ3w3_-_w.png)
![](https://image.prntscr.com/image/zbAi8BNST96NbcF6wZKb0Q.png)

`<field name="amount_total" sum="Total Tax Included" widget="monetary"/>`

![](https://image.prntscr.com/image/NRro9Y6NTma55Ly-uSRUSA.png)
![](https://image.prntscr.com/image/U9W-Cv3bTLuf2fEOQYL5Dw.png)

Same way `sum/avg `works for v9 and 10.

**Comment by Yenthe666** [comment]
@sswapnesh thanks for testing this too. @grzegorz-openglobe can you confirm this is what you reported and that it works on an official Odoo instance (at runbot.odoo.com)?

Regards,
Yenthe

**Comment by grzegorz-openglobe** [comment]
I confirm that on runbot on 11CE it works correctly. I made a test witch Timesheet view. I edited tree view  in interface changing sum to avg, and behavior was as expected. 
Did it worked this way all the time and I reported it wrongly or did you fixed it just on my issue report? It is not clear for me.
Anyway thanks for quick reaction. When it will be on nightly.odoo.com?

**Comment by Yenthe666** [comment]
Hi @grzegorz-openglobe,

Thanks for the feedback. The issue might have been fixed in the meanwhile, I can't find anything referencing it but it is gone now anyways.
The nightly build is updated daily so if you download it today it will be gone (see http://nightly.odoo.com/11.0/nightly/).

Regards,
Yenthe

**Comment by grzegorz-openglobe** [comment]
Unfortunately yet now I found that it works not like I expect.  
In solution you made avg works only on final amount at the bottom of view. So when there is no grouping it works on all lines. When you group lines the grouping works like sum and final amount is avg. 
I understand that your solution makes sense in some cases but I seem avg should work as avg for grouping and for final amount. Maybe we should have another attribute for full avg?
