### ISSUE TITLE
[10.0/11.0] Invalid company in Order created from Website

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#21675]
Impacted versions: 10.0/11.0

Assuming the Multi-company setup having two Company `YourCompany`
and `My Company, Chicago`

Steps to reproduce: Create Portal user belongs to `My Company, Chicago` --> Log in as Portal user and Place an order on the website. (Tested on [Runbot](http://286583-11-0-c12ff1.runbot14.odoo.com))

![](https://image.prntscr.com/image/590Gf5GXQiuMEkP2Lpjv4Q.png)

Current behavior: Order placed by Portal user is created for `YourCompany`

![](https://image.prntscr.com/image/KMPJhErzRoyIaPARrb2EiQ.png)

Expected behavior: It should belong to Portal User's Company which is `My Company, Chicago` 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qsm-odoo could you have a look at this? Should we allow this behaviour so it keeps track of the correct company the portal user is related to? 
If this would be added / fixed we should also change the `Portal managament access` dialog a bit, so you can configure the company the new portal user belongs to too:
![image](https://user-images.githubusercontent.com/6352350/34096322-329aae46-e3d5-11e7-9516-987e39adec82.png)

Regards,
Yenthe

**Comment by JKE-be** [comment]
Sale order is created for the company_id set on the website and not the portal user.
![image](https://user-images.githubusercontent.com/4848797/34770358-360270a8-f601-11e7-9628-477a779768af.png)

![image](https://user-images.githubusercontent.com/4848797/34770362-3a8ee80e-f601-11e7-8c9b-f1a1965d192a.png)

**Comment by sswapnesh** [comment]
@JKE-be 
Thanks for the Update.

I will check once again If the same flow works till Invoice/Payments as Both Partner and Product will have different accounts belongs to different companies.
