### ISSUE TITLE
[11.0] emoji shows messy code in chat window

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#21690]
Impacted versions:
11.0
Steps to reproduce:
Pull latest 11.0 code(Dec 18, 2018), initialize an odoo db with demo data, install Discuss module.
Send emoji to Demo user by DIRECT MESSAGE.
Current behavior:
emoji shows messy code instead of icon.
Expected behavior:
shows correct emoji icon.
Video/Screenshot link (optional):
<img width="1347" alt="messy" src="https://user-images.githubusercontent.com/1243299/34086792-bc61c61a-e3d9-11e7-8c6d-9853a22f6f1a.png">

**Comment by jlzhou** [comment]
After deep drill down the code, I found the cause:

In file odoo/tools/mail.py line 167 def html_sanitize(...

around line 225: 
cleaned = cleaner.clean_html(src) makes the emoji be changed to messy code.

In lxml lib clean.py, around line 508, 
doc = fromstring(html) returns the messy code.

by the way, LXML_VERSION is 3.5.0 on my macbook.

Hope this can help. :)

**Comment by Yenthe666** [comment]
Hi @jlzhou,

Thank you for the report and for the details.
I've just tried to reproduce this on Chrome but it seems to work fine. Can you reproduce this on a runbot at runbot.odoo.com? I'm going this guess this only happens in safari?

Regards,
Yenthe

**Comment by jlzhou** [comment]
@Yenthe666 I am not a native English speaker, so I try to describe the issue more clearly:

Not only in safari, but in firefox. I think it doesn't look like a browser compitability issue.  LXML lib convert the emoji string to messy code then persistent to the db.

Maybe the issue only occurred on Mac platform?

Sorry, I am not familiar with odoo runbot, if you did not find any issue like this on runbot, it is maybe an LXML issue on MacOS High Sierra. I will test this case on an ubuntu 16.04.03 server and get back here later.

**Comment by Yenthe666** [comment]
@d-fence could you double check dependencies perhaps? I don't have any Mac to test with anyways.

**Comment by jlzhou** [comment]
@Yenthe666 on ubuntu 16.06.03, It is ok. So the issue may cause by lxml lib on macos.

**Comment by jlzhou** [comment]
I'm trying to replace lxml 3.5 with higher version to see if it can solve.

**Comment by jlzhou** [comment]
Bingo! After replace lxml 3.5 with 3.8, the issue has gone. (lxml 3.6, 3.7 still not works)

**Comment by jlzhou** [comment]
The python version is 3.6.3

**Comment by jlzhou** [comment]
Wow, issue #21642 also be solved together by upgrading lxml on macos!

**Comment by jlzhou** [comment]
@Yenthe666 You are welcome, good luck.

**Comment by sswapnesh** [comment]
Closed in https://github.com/odoo/odoo/commit/3ede4c72df9e22a2b0c3129edc20d69201de2520 as mentioned https://github.com/odoo/odoo/pull/21703#issuecomment-368556460
Cc: @Yenthe666

**Comment by pedrobaeza** [comment]
Thanks for the follow-up, Swapnesh. Closing this.
