### ISSUE TITLE
[10.0] empty fields and new generated view when creating user through @api.onchange/@api.depends

### ISSUE THREAD

**Issue by bouktaibMohssin** [odoo/odoo#21701]
Impacted versions:
10.0
Steps to reproduce:
use this code to create user name from username field
```
from odoo import api, fields
from odoo.models import Model

class SaleOrder(Model):
    _inherit = 'sale.order'

    username = fields.Char(string='User Name')

    @api.onchange('username')
    def onchange_username(self):
        if self.username:
            user_obj = self.env['res.users']
            user_test = user_obj.create({'name': self.username, 'login': self.username})
            self.update({'username': self.username, 'partner_id': user_test.partner_id, 'user_id': user_test})
```
Current behavior:
The user is created ,and the partner is assigned but there is a new form generated the fields which were already filled get empty, the status bar is invisible

Expected behavior:
The partner get assigned and no change on the current form view.
Video/Screenshot link (optional):

**Expected form view**

![selection_008](https://user-images.githubusercontent.com/17483600/34103591-2dab6fa0-e3e5-11e7-8adc-7e0321719c88.png)

![partner_other_case](https://user-images.githubusercontent.com/17483600/34199773-c678b79c-e566-11e7-919e-5669e93f7557.gif)

**Current form view**
![selection_007](https://user-images.githubusercontent.com/17483600/34103623-4871ca64-e3e5-11e7-8fe4-3100876ba78b.png)

![user_case](https://user-images.githubusercontent.com/17483600/34199533-fe072d70-e565-11e7-8a60-9972861fc840.gif)

**Comment by sswapnesh** [comment]
Hello @bouktaibMohssin 

I will not recommend using create method inside onchnage.

In your case when you are entering `User Name` it will remove all values from the current record.(default values and all the inputs you have added manually)

Still to solve status bar (header) issue you can use this.

```
@api.onchange('username')
    def onchange_username(self):
        if self.username:
            user_obj = self.env['res.users']
            user_test = user_obj.create({'name': self.username, 'login': self.username})
            self.partner_id = user_test.partner_id.id
            self.user_id =  user_test.id
            self.state = 'draft'
            if not self.id:
                self.name = 'New'
```

Related to #5611 and [this](https://www.odoo.com/forum/help-1/question/create-new-many2one-records-in-api-onchange-method-2nd-try-70212)

**Comment by bouktaibMohssin** [comment]
Thank You @sswapnesh for your answer ,from my tests i think the issue is not the creation of records inside on-change but particularly creating a user record for example if i create a partner and assigned it directly i get the normal expected behavior you can try this to see:

```
    @api.onchange('username')
    def onchange_username(self):
        if self.username:
            user_obj = self.env['res.partner']
            partner_id = user_obj.create({'name': self.username})
            self.partner_id = partner_id
            self.state = 'draft'
            if not self.id:
                self.name = 'New'
```

**Comment by sswapnesh** [comment]
Yes, It will work but It will remove default values for `Order Date, Salesperson and Sales Team.`

Anyways, you can close this issue if this works for you.

**Comment by bouktaibMohssin** [comment]
Hello @sswapnesh the issue is not solved yet I've added an GIF picture to understand, this issue  happen only in the case of user creation and in other cases (partner creation for example) it those not happen and the fields are not emptied (Order Date, Salesperson and Sales Team.)

Partner creation (normal expected behavior):
![partner_other_case](https://user-images.githubusercontent.com/17483600/34199705-92157300-e566-11e7-86d4-c6d58afd758d.gif)

User Creation (the current issue):
![user_case](https://user-images.githubusercontent.com/17483600/34199725-a098c882-e566-11e7-81be-4ced89d80c4f.gif)

**Comment by Yenthe666** [comment]
Dear @bouktaibMohssin,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
