### ISSUE TITLE
[11.0] Tests of sale_timesheet module failing when main company currency different than USD

### ISSUE THREAD

**Issue by keylor2906** [odoo/odoo#21712]
Impacted versions:
11.0

Steps to reproduce:
Install the modules `sale_timesheet` and  `l10n_mx` with tests enabled

Current behavior:
There is an error on test `test_timesheet_revenue.py` [here](https://github.com/odoo/odoo/blob/11.0/addons/sale_timesheet/tests/test_timesheet_revenue.py#L136) because the `l10n_mx` module sets the main company currency to be different than USD.
The second error of the [test](https://github.com/odoo/odoo/blob/11.0/addons/sale_timesheet/tests/test_timesheet_revenue.py#L277) is caused because the differences on currency rates of using MXN instead of USD.
![image](https://user-images.githubusercontent.com/17324113/34121500-de674680-e3ee-11e7-8551-94e979ba8825.png)

This is a functional example of the second error using MXN as main company currency and USD as sale order currency
![image](https://user-images.githubusercontent.com/17324113/34122411-fff6c570-e3f1-11e7-9e32-03fa13900de7.png)

Expected behavior:
Not having errors in the tests when the currency of main company is different than USD.

**Comment by Yenthe666** [comment]
Hi @keylor2906,

Thanks for the report!
@jem-odoo I see you've been working on these tests. Could you please have a look and change this?

Regards,
Yenthe

**Comment by jem-odoo** [comment]
Should have been done at https://github.com/odoo/odoo/commit/3c61cd09928977922674d021241269b0bf1c3c5d
Regards
