### ISSUE TITLE
Process Checkout button is not removed when the buying cart is emptied from products.it happens only in case of languages other than English.

### ISSUE THREAD

**Issue by amir511** [odoo/odoo#21722]
Impacted versions:10

Steps to reproduce:
1- Change the language of the website
2- Open the Shopping Cart page
3- Remove all the products in the cart
Current behavior:
The Process Checkout button remains 
Expected behavior:
It should be removed to prevent the user from confirming his order as his cart is now empty
Video/Screenshot link (optional):

* Normal behaviour for english website:
![1](https://user-images.githubusercontent.com/18488957/34146584-50e346e6-e4a3-11e7-82fc-b2adf3c7100c.png)

![2](https://user-images.githubusercontent.com/18488957/34146619-6db28782-e4a3-11e7-88f9-7c1b71f3e221.png)
* Different behaviour in case of arabic:
![3](https://user-images.githubusercontent.com/18488957/34146635-7dfd0374-e4a3-11e7-8451-18a02f097115.png)

![4](https://user-images.githubusercontent.com/18488957/34146654-8b214362-e4a3-11e7-8e95-031ef5b45894.png)

**Comment by Yenthe666** [comment]
Hi @amir511,

Thanks for the report.
I've just tested this and was able to reproduce this on the latest Odoo 10. @qsm-odoo could you have a look please?

Regards,
Yenthe

**Comment by amir511** [comment]
Thanks @Yenthe666

**Comment by amir511** [comment]
Now it works after the fix, thanks @qsm-odoo :)

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/16065f3ee2f02aba9b7a78f24522fc561cbdc2fe in 9.0, will be forward-ported later :)

**Comment by Yenthe666** [comment]
Thanks for the very fast response and fix @qsm-odoo. Great job!
