### ISSUE TITLE
[11.0] Wrong license translation in base de.po

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#21728]
The translation of the OEEL-1 license can be found in the translation of the OPL-1 license: https://github.com/odoo/odoo/blob/506e45e73f4c6cb19b9d68098d663c7aac7f8fc6/odoo/addons/base/i18n/de.po#L15738

Instead of

```
#. module: base
#: selection:ir.module.module,license:0
msgid "Odoo Proprietary License v1.0"
msgstr "Odoo Enterprise Edition Lizenz v1.0"
```

it should be 

```
#. module: base
#: selection:ir.module.module,license:0
msgid "Odoo Proprietary License v1.0"
msgstr "Proprietäre Odoo Lizenz v1.0"
```

or (first is better, but second example is also possible)

```
#. module: base
#: selection:ir.module.module,license:0
msgid "Odoo Proprietary License v1.0"
msgstr "Odoo Proprietäre Lizenz v1.0"
```

I might open a pull request after work if not already corrected until then.

**Comment by Yenthe666** [comment]
Hi @Armitxes,

Thank you for the report.
This issue however has to do with the translations. These shouldn't be changed on Github and neither should this be done through a PR. The correct way is to translate the terms on transifex.com.
For more information see https://github.com/odoo/odoo/wiki/Translations

Regards,
Yenthe

**Comment by ACBRI** [comment]
Excuse me, I would like to know where I can find information about the OPL-1 license, that is, what is it for?
