### ISSUE TITLE
[11] preload_registry not works as excepted

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#21736]
Impacted versions:
11

Steps to reproduce:
set workers more than 1 and set db_name as those want to be preload. 

Current behavior:
the registry is not be new() for all workers, the registry is be created when the worker is started 

Expected behavior:
registry can be created when start the odoo server.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get what is the practical problem here, and why it should be changed.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
