### ISSUE TITLE
[Reconciliation] Account clicked on in 'Search More' window does not appear in the selection box.

### ISSUE THREAD

**Issue by denislour** [odoo/odoo#21751]
### Impacted versions:
- 11
### Steps to reproduce:
I would like to inform you about a bug in the existing Reconcile in Odoo.
After I created a new statement in the bank statement and proceeded to reconcile:
1. [CASE 1] If I choose the account in the selected box, everything is normal.

2. [CASE 2] 
  * If I click on search more and select any account in list of chart of account (In this case is COA 101302) will appear on bank statement line but it does not appear in `Account`.
![1](https://user-images.githubusercontent.com/5222185/34198672-cf3ef5ee-e59d-11e7-9917-51818e79151c.png)
  * Then if I continue to choose another account (in this case is 104200), the COA 101302 appears in `Account` , and at the same time the COA 104200 appears on bank statement line.
![2](https://user-images.githubusercontent.com/5222185/34198696-de030930-e59d-11e7-8378-0acad7eef53d.png)
![3](https://user-images.githubusercontent.com/5222185/34198697-deac38de-e59d-11e7-8d2a-1f3334ba0dd3.png)

**Comment by lap-odoo** [comment]
Thanks for reporting this ! We will take care of fixing this bug.  
(note for myself: checked with chm who is taking care of this)
