### ISSUE TITLE
[11.0] Wire Transfer Payment Acquirer does not show up on website

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#21764]
Impacted versions:
11.0

Steps to reproduce:
Publish Wire Transfer payment acquirer, go to shop, add any product to cart, checkout and proceed to payment state.

Current behavior:

Even if Wire transfer is published, it will not appear as one of the options to pay with (reproduced this on newest version of 11.0 Enterprise code on `runbot.odoo.com`)

Expected behavior:
If Wire transfer is published, it should appear in shop, when in payment state.

Also I do not know if this is related, but there is no Test/production button for Wire transfer. I guess it is intended, because `Wire Transfer` is just a template for text, not real integration with some external system that handles payments?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qsm-odoo website issue for you. 😉

**Comment by oerp-odoo** [comment]
@Yenthe666 
Hm, it seems this was my misunderstanding of when wire transfer is showed as a payment.

It collects acquirers by checking what kind of payment flow they have. This part is important for wire transfer:

```python
values['form_acquirers'] = [acq for acq in acquirers if acq.payment_flow == 'form' and acq.view_template_id]
```

For wire transfer it must be `form`, so it would be included in website shop (using standard settings). Though confusing part was how those different flows are labeled:

There are two forms:

- `server`:  `The customer encode his payment details on the website.`
- `form`: `The customer is redirected to the website of the acquirer.`

So I thought that latter (`form`) means user will be redirected to some external site. That's why I changed it to `form`. And if you choose second option, then wire transfer appears. I don't know maybe that's just me, but it is kind of confusing what each payment flow means. I mean when I hear word `redirect`, I assume I will be actually redirected somewhere (but with wire transfer you do not need to be redirected anywhere).
