### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by davidgomezq** [odoo/odoo#21765]
Impacted versions: 11

Steps to reproduce: Access to Point of Sale > Configuration > Point of Sale > Open any POS

Current behavior: Browser console show "Mixed Content" error, it is caused by url link ('http://placehold.it/300x350?text=ADV) implemented on "point_of_sale.customer_facing_display_html" view.

Expected behavior: Do not show the error

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @davidgomezq,

Thank you for your bug report.
Where exactly is the URL placehold.it in your comment coming from? Can you reproduce this problem on an official Odoo instance at runbot.odoo.com? We'll need more information to handle this one.

Regards,
Yenthe

**Comment by danger89** [comment]
@davidgomezq Did you set your `web.base.url` to https address? Enable developer mode, go to settings->system parameters->`web.web.url` change it to a domain starting with https instead of http.

**Comment by davidgomezq** [comment]
Now works well! Thanks @danger89

**Comment by danger89** [comment]
You are welcome.
