### ISSUE TITLE
Adding type-hinting/optional static typing to Odoo

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#21794]
Look here:
http://mypy-lang.blogspot.com.co/2017/11/dropbox-releases-pyannotate-auto.html

Optional static typing on the `accounting` and `stock` hotspots for example on `constrains` and `creates` logic... Nice idea.

Sorry to bother you with my procrastination efforts... :smile: 
/cc @odony @rco-odoo

**Comment by Elkasitu** [comment]
It's not optional static typing but type hinting, defined in [PEP484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code), it's just hints for the dev or potentially auto-completion engines about the type of the arguments to a function/method, but the interpreter won't complain like a compiler would if the passed-in arguments are not of the correct type.

I do agree that it'd be a good idea to add it to some obscure low-level functions/methods though, or maybe even use it everywhere, but that could turn into a herculean task.

**Comment by blaggacao** [comment]
Yeay! Also I think PyAnnotate is rather an aid for such attemt, as it gives the inclined developer a right away suggestion of some annotations... To minimize risk, I would proceed filewise, it's a small investment at a time but coming up from low level, nothing's wrong of giving it a try con Mypy, it will not be THAT wild in relatively short time. That I'm sure of... (https://www.python.org/dev/peps/pep-0484/)

**Sublime:** https://packagecontrol.io/packages/SublimeLinter-contrib-mypy
**Cheatsheet:** http://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html
**Typing Core:** https://github.com/python/typing
**Seems highly traded:** https://www.python.org/dev/peps/pep-0544/

**Comment by D4N** [comment]
This would be very nice to have indeed, for modules too. Unfortunately currently you cannot install modules with typing hints in odoo. Shameless plug: should be fixed by #24069.

**Comment by tooolbox** [comment]
Are type hints supported in any version of Odoo?  *(please oh please oh please dear lord)*

**Comment by rht** [comment]
Why is this issue closed? An explanation would be nice. I think type hints help code readability especially in a large codebase. Not to mention that Sphinx for RTD require argument and return type for the documentation.
