### ISSUE TITLE
 [usability] mail.compose.message wizard doesn't show email address of receipients - Does not work on sale.order compose

### ISSUE THREAD

**Issue by RoelAdriaans-B-informed** [odoo/odoo#21812]
#21523  fixes showing the email adres on the compose window. This works for the followers, but not on the send message from the sale.order

Impacted versions:

11

Steps to reproduce:

Open sale order, click on **send by email**

Current behavior:

Email popups, partner but without email adres

Expected behavior:

Show  the email adres

Video/Screenshot link (optional):

Current screen, tested on the latest Odoo 11 enterprise runbot.

![image](https://user-images.githubusercontent.com/7871661/34298030-e84f36be-e71b-11e7-84d3-3386d3e665b9.png)

**Comment by nle-odoo** [comment]
Hi, this should be solved in saas-16 with https://github.com/odoo/odoo/commit/bc8f7a44d6e2c4153dbca9c06d3e5ecfea5a9855 and will be available in the next forward-port in version 11. Thanks.
