### ISSUE TITLE
[11.0] One2many records are deleted when I try to update them

### ISSUE THREAD

**Issue by josemoralesp** [odoo/odoo#21817]
Impacted versions:
11.0

Steps to reproduce:

1) You should  have a model with a one2many field shown in your form view([Example](https://github.com/josemoralesp/bug_report/blob/master/bug_test/models/bug_report.py#L18))

2) Try to update your one2many field from another method(compute_field, onchange) using [(1, id, values)] as odoo explains in its official [documentation](https://www.odoo.com/documentation/11.0/reference/orm.html).([Example](https://github.com/josemoralesp/bug_report/blob/master/bug_test/models/bug_report.py#L31)) 

Because of the branch where I have this problem is private I've created a dummy model to show how I can do it.

https://github.com/josemoralesp/bug_report/blob/master/bug_test/models/bug_report.py

Current behavior:

The records in the one2many fields are deleted.

Another thing I could see in the log, it was that the onchange method is called. 
https://drive.google.com/a/vauxoo.com/file/d/1SdbJjG1ptP9GmGjmQ882WHpLeDmHanK6/view?usp=drivesdk

This issue is happening only when the field is shown in the form view.

Expected behavior:

The records in the one2many fields should be updated with the new values passed in the list of tuple

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=A9fwZOcRkOc&feature=youtu.be

**Comment by findsomeoneyys** [comment]
some problem in 12.0， it's there any way to slove it?
