### ISSUE TITLE
[saas-3] Background images of Website snippets are repeated when we apply Narrow style.

### ISSUE THREAD

**Issue by dja-odoo** [odoo/odoo#2182]
In any website snippet, when you add background image with small height, and then apply 'Narrow' style, the background image is repeated.  See the video :  http://youtu.be/BC1J3Hs_IPk
The behavior is same from saas-3 to master.

**Comment by Yenthe666** [comment]
This bug is still in V8 @pna-odoo 
It is however fixed in V9 and above.

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As this cannot be reproduced in upper versions (it changed) this is no longer relevant.

Regards,
Yenthe
