### ISSUE TITLE
product.template __last_update web service not filtering

### ISSUE THREAD

**Issue by davidqdr** [odoo/odoo#21835]
Impacted versions: 10

Steps to reproduce: 

models.execute_kw(db, uid, password,
    'product.template', 'search_read',
    [[['__last_update', '>', '2017-12-20']]],
    {'fields': ['name'], 'limit': 5})

Current behavior:

When you execute the search_read using "create_date" to filter "more than" for example, you get the result filtered but when you use "__last_update", the filter "more than" for example, you get all rows without filter.

Expected behavior:
filter with "__last_update" would work as "create_date" does

Video/Screenshot link (optional):

**Comment by stechnique** [comment]
__last_update doesn't work for me either when filtering, but write_date did. Odoo 11 Enterprise.

**Comment by pedrobaeza** [comment]
Indeed, `__last_update` is a deprecated field that is not used anymore, so it's not valid for performing searches.

Closing as no real issue.
