### ISSUE TITLE
[11.0] read_group with many2one field raise  ir.rule restriction 

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#21842]
Impacted versions:
11-ce

Steps to reproduce:
initialize database with demo data
enable multi-company
create a normal user
login as normal user, create new partner

Current behavior:
group by `create_by` raise security restrictions

Expected behavior:
group by should filtered out the data those user can not to read, then return those to client

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1404460/34347402-db53d2ba-ea3d-11e7-8a17-e05e63b4264f.png)

**Comment by Yenthe666** [comment]
@mart-e can you check?
