### ISSUE TITLE
[11.0] Miscalculation of regular Leaves in Worked Days (Number of Days & Number of Hours)

### ISSUE THREAD

**Issue by airitos** [odoo/odoo#21860]
Impacted versions:
11.0 build 20171226

Steps to reproduce:

- Use the schedule 'Standard 40 Hours/Week' in employee & contract, define any structure in the contract
- Create a generic Leave and call it 'Late In' for encode people getting late to work.
- Create & approve for a given month a leave for the same day from 08:00 to 09:30.
- Create a Payslip for the period above
- Check in Worked Days the line regarding the leave 'Late In'.

Current behavior:
In Worked Days, the line regarding 'Late In' leaves states:
- Number of Days = 2.75
- Number of Hours = 22

Notice that we realized this happens when the working schedule has 2 shifts (morning and evening period). If you configure a single shift from 8:00 to 16:00 it computes right. If you in 'Standard 40 Hours/Week' void/deactivate the evening shift, it computes right. Problem seems to occur when is more than a shift for the day

Expected behavior:
Well, the leave recorded was from 8:00 to 09:30, so time elapsed has been 1:30 that in float value should be 1.5. So it shout present the below
- Number of Days = 0.19
- Number of Hours = 1.5

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
Hello @airitos 
This issue seems to be fixed as I cannot reproduce it on runbot
When trying to reproduce this, I get : 
   number of days = 0.19
   number of hours = 1.50

**Comment by celm1990** [comment]
@RomainLibert  can you review isuue #26256 please, can be related
