### ISSUE TITLE
[settings] create new message with 'TypeError' Traceback

### ISSUE THREAD

**Issue by gan-odoo** [odoo/odoo#2186]
Traceback when create new message from settings.

Step to reproduce : 
1.  Go to Settings  > Technical.
2.  Select a Messages in Email.
3.  Create new message.

Impacted Version : master And 8.0

See issue here:
![message-error](https://cloud.githubusercontent.com/assets/7599957/4148579/b0b5f65c-3427-11e4-9886-625e8f72594e.png)

**Comment by pna-odoo** [comment]
Seems fixed now.
