### ISSUE TITLE
[9.0e/10.0e/11.0e] Deployment Requirements For Working Native iOS/Android Notifications

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#21876]
<h1>Impacted versions:</h1>

- 9.0e/10.0e/11.0e/Master (Enterprise Edition)
- Nginx as reverse proxy (following deployment suggestions)

<h1>Steps to reproduce:</h1>

1. Install Android or iOS app on your mobile device.
2. Send a direct message from one user to another.

<h1>Current behaviour:</h1>
No native push notifications in native iOS/Android app (Odoo S.A. App)

<h1>Expected behaviour:</h1>
Odoo S.A. mobile apps should handle push notifications out of the box. 

Or if additional setup is required, it would be very useful if sample deployment documentation was provided for on-premise deployments (eg. setup requirements, dependencies, and perhaps Nginx proxy configuration example if required).

**Comment by Yenthe666** [comment]
@ged-odoo I believe you know who works in the mobile team and can have a look.

**Comment by Elkasitu** [comment]
@adr-odoo perhaps related to OPW 788386

**Comment by adr-odoo** [comment]
Hello,

I recently made some fixes:
https://github.com/odoo/enterprise/commit/51a4651173aa8ffd3328858cf04ac184c93639bf
https://github.com/odoo/mobile/commit/1c45f7f606c38281e7ab22ec8058db63bd166220

Now, iOS notifications should work.
But you also need to update the Android app because we changed how we send FCM messages.

So, for on-premise deployments, you need to go to
'General Settings' -> 'Mobile App' -> check Notifications.
You will find a link to 'Generate API and Sender ID'.
To make it work for iOS, you need to do some extra operation like mentioned in the documentation:
https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by Yenthe666** [comment]
@lukebranch could you update your Odoo and try the mobile apps to see if it is working fine at your end now?

**Comment by lukebranch** [comment]
@adr-odoo ,

Thanks for the update.
Are there any additional steps to use FCM behind a reverse proxy setup like Odoo + Nginx? I have been doing some reading and it wasn't entirely clear from the information and documentation I could find online and on stackexchange.

@Yenthe666 ,

Yes, i'll definitely update this as soon as possible and test and confirm. Unfortunately it might not be till the weekend at this stage. I'll update this thread once i've tested and confirmed.

**Comment by adr-odoo** [comment]
Hello @lukebranch ,

I think that it should work without any additional steps.
I would advise you to test and once done, kindly ask you to get back to me.

**Comment by hermannleidi** [comment]
@adr-odoo Any news on this Topic?
I got the Android App running smoothly with Push. Unfortunately all our devices are on iOS.
I red https://firebase.google.com/docs/cloud-messaging/ios/certs , but dont really know which configuration I have to do in my Apple Account?
The App ID I used is the domain of our on site odoo: de.["company"].erp . Is this correct? I got alle sorts of .cert files. Shall I put them somewhere. A detailled deployment guide for the Apple certificats needed and how to implemt them would be very much appreciated.

**Comment by adr-odoo** [comment]
Hello,

Unfortunately, we have some problems with notifications with on premise databases.
The main problem for iOS devices is that the Odoo application should be compiled with your own certificates but we don't allow it for security reasons.

We are currently working on a big improvement to avoid the part of the configuration with certificates.
In the future, this configuration will be automatically done by Odoo.

Thank you for your patience.

**Comment by hermannleidi** [comment]
Any news on that topic?
Push notification is thze most desired feature for our company. We are only running iOS and the push would make life so much easier.
