### ISSUE TITLE
string of city_id is 'Company'

### ISSUE THREAD

**Issue by shameembabu** [odoo/odoo#21870]
https://github.com/odoo/odoo/blob/ab65a02f5ace3b72d5dc00cd46523958bda964c0/addons/base_address_city/models/res_partner.py#L12

**Comment by Yenthe666** [comment]
Hi @shameembabu,

Thanks for the report.
Can you please mention on which branch you're seeing this? 9.0, 10.0 or 11.0 don't have this.

**Comment by shameembabu** [comment]
@Yenthe666 
I see in 11.0
[https://github.com/odoo/odoo/blob/11.0/addons/base_address_city/models/res_partner.py](https://github.com/odoo/odoo/blob/11.0/addons/base_address_city/models/res_partner.py#L12)

**Comment by Yenthe666** [comment]
@shameembabu yep it is there, I was just a little too fast. That is why I edited my original response 😉 To be changed soon.

**Comment by mart-e** [comment]
Thanks, fixed at abf0e355222
