### ISSUE TITLE
[BUG] Report : print date&time is not in user format

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#21883]
**Impacted versions:**
11,10,9 (and other)

**Steps to reproduce:**
Print a report with internal_layout (exemple : Accounting/PDF report/Journal audit
In the top left corner the date&time are not in the current user lang format, in some case it could be an issue (american/europe format).

**Current behavior:**
![image](https://user-images.githubusercontent.com/16716992/34396011-2caaad4a-eb66-11e7-93da-095afe73201a.png)
Date and time is not formated in the user lang.

**Expected behavior:**
Date and time need to be formated.

Come from : https://github.com/odoo/odoo/blob/10.0/addons/report/views/layout_templates.xml#L165

OPW : 802892

**Comment by simongoffin** [comment]
Hello @fmdl 

This format of date is the ISO 8601, it's an international standard format to avoid any format issue.

https://en.wikipedia.org/wiki/ISO_8601

**Comment by fmdl** [comment]
Hi @simongoffin 

I understand your point of view. I think I have don't explain very well this little issue: when print a document with an date field, the date format is differente than the top right ISO date of the document, it can be confuse (exemple on a production order):

![image](https://user-images.githubusercontent.com/16716992/34522052-238094ca-f091-11e7-977c-307d892e509d.png)

Regards

**Comment by Yenthe666** [comment]
@fmdl looks like one keeps track of the timezone and another one doesn't.
@simongoffin can you double check?
