### ISSUE TITLE
Point of Sale not loading javascript files defined in custom modules

### ISSUE THREAD

**Issue by wguerram** [odoo/odoo#21882]
Impacted versions:
11

Steps to reproduce:
Create a new module, add template under views, js and xml under static/src. I'm loading some fields and a new model using load_fields and load_models. See attached screenshots.

If further details are needed I can provide them.

Current behavior:
My code works when I run in development mode with assets but doesn't work when I run in user mode.

I've trying reloading, rebooting, updating my application, changing the files permissions and nothing looks to work.

Expected behavior:
Execute my js file so that new fields and models are loaded to be used in xml files.

Video/Screenshot link (optional):

![js](https://user-images.githubusercontent.com/8525985/34391730-36ed0de2-eb0d-11e7-8c5c-9202e8b87d0d.PNG)
![template](https://user-images.githubusercontent.com/8525985/34391732-3ab76a58-eb0d-11e7-8c09-92f3ce321b95.PNG)

**Comment by Yenthe666** [comment]
Hi @wguerram,

Thank you for your report.
Your `templates.xml` file looks quite weird though. Why are you putting your custom JS in through an xpath after `tests.js`? You should do something like this:
```
<odoo>
    <!--========== [ JavaScript import ] ==========-->
    <template id="assets_backend" name="pos assets" inherit_id="point_of_sale.assets">
        <xpath expr="." position="inside">
            <script type="text/javascript" src="/ss_point_of_sale/static/src/js/ss_point_of_sale.js"/>
        </xpath>
    </template>
</odoo>
```

Can you try this first please?

**Comment by wguerram** [comment]
Hi @Yenthe666, thanks for taking the time to review this, I really appreciate it. I have no words.

Your solution worked, looks like odoo doesn't like the <script> </script> tag but this <script/>. that did the trick.

Quick question, I see the id label says assets_backend but you'r not including _backend in the inherit_id, is that the standard way?

**Comment by Yenthe666** [comment]
Hi @wguerram,

No problem, happy it helps.
As for the id label having `assets_backend` and the `inherit_id` not having it: I usually add `_backend` or `_frontend` so that I know if the assets are for the backend or the Odoo frontend (website). This is a bit personal I guess.

**Comment by Ojooluwaseun** [comment]
Thanks...worked for me
