### ISSUE TITLE
"Label on Invoices" option is  not showing when option Group of Taxes is selected

### ISSUE THREAD

**Issue by shashishekhar1001** [odoo/odoo#21889]
Impacted versions: 11.0

Steps to reproduce:

1) Go to Accounting -> Configuration -> Accounting -> Taxes
2) Open or Create any tax.
3) Change field Tax Computation to Group of Taxes
4) Click on Advanced Options tab
5) No field for Label on Invoices is shown

Current behavior:
When printing, the value that the localization has on this field is the one that is going to show, some localizations have a coding there which end customer may not understand.

Also options to change this value are not open to accountants and customer, who at the end, are the ones that are going to manage this part of the platform.

To change the value in this field you either have to:

Select any other value on Tax Computation field, input the label text in the Label on Invoices field, go back and change the Tax Computation to Group of Taxes.
Edit the form and create of copy of the line that contains the description field, remove the invisible attribute and comment the original line with the description field.
Or simply edit the original line containing the description field and delete the invisible attribute.

Expected behavior:

Show the Label for Invoices field at all times.

**Comment by sswapnesh** [comment]
@Yenthe666  I can confirm this behavior (Same in v9 and v10) but cannot consider this as a bug, But will be good to give the option to use different tax name in odoo and Label on Invoice. (As It is there for other types of tax computation.)

It has been introduced from this [commit.](https://github.com/odoo/odoo/commit/c04065abd8f62c9a211c8fa824f5eecf68e61b73)

**Comment by lap-odoo** [comment]
@shashishekhar1001 @sswapnesh I do not consider this as a bug neither however I agree it's an improvement that can be done. I've created a task in our backlog (1819063) to improve this for future versions. Thanks for the remark
