### ISSUE TITLE
[Account] Payment wrongly generated entries when there is payment difference and exchange difference

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#21888]
# Impacted versions:
V10 impacted, V9, V11 not tested

# Steps to reproduce:
## 3. Accounting->Multiple Currencies->Currencies, Set USD Exchange as 0.895@2017-11-01 and 0.88@2017-12-01
![image](https://user-images.githubusercontent.com/8391358/34400031-1fa0ef4e-ebc8-11e7-9756-993d6e9cbee1.png)
## 4. Create a USD Bank Journal and USD Bank Account
![image](https://user-images.githubusercontent.com/8391358/34400044-51e9055e-ebc8-11e7-96bc-1920dbdbe11c.png)
![image](https://user-images.githubusercontent.com/8391358/34400047-5f94a1d6-ebc8-11e7-9b09-3d84da41a100.png)
## 5. Create a vendor invoice, Bill Date 2017-11-07, Currency USD, Amount 5325.6
![image](https://user-images.githubusercontent.com/8391358/34400078-b679e204-ebc8-11e7-8b70-888cf8e482f8.png)
Its generated enty:
![image](https://user-images.githubusercontent.com/8391358/34400083-d4e9f2f6-ebc8-11e7-9777-e973fc1fd505.png)
## 6.  Register Payment
Payment Date 2017-12-15
Journal USD Bank
Amount 5325
Mark invoice as fully paid, Post Difference in an income account(I created a supplier discount on the fly in this example) and validate the invoice
![image](https://user-images.githubusercontent.com/8391358/34400136-4f51c8ac-ebc9-11e7-9f33-cec693874cbd.png)
![image](https://user-images.githubusercontent.com/8391358/34400148-7587c472-ebc9-11e7-91e7-9d316bccf282.png)

# Current behavior:
The Payment Journal entries generated are all wrong. The system assume the only difference is exchange difference when generating entries. Therefore, when there are also payment difference and want to mark invoice as fully paid, all amount difference go to exchange difference and the sign of counterpart account may be wrongly flipped.

## USD Bank Entry:
![image](https://user-images.githubusercontent.com/8391358/34400301-b1e67da4-ebca-11e7-82e3-3301cfb43073.png)

## Exchange Difference Entry:
![image](https://user-images.githubusercontent.com/8391358/34400472-c20147ee-ebcc-11e7-9acc-5552deea5faf.png)

## Account Payable Reconciliation:
![image](https://user-images.githubusercontent.com/8391358/34400458-9b9a5208-ebcc-11e7-9cdf-c802215b0145.png)

# Expected behavior:
![image](https://user-images.githubusercontent.com/8391358/34400606-3506a4a4-ebce-11e7-8b39-cabd0c379885.png)

**Comment by auyeung112002** [comment]
@Yenthe666 Would you please help to convey this issue to odoo responsible staff?

**Comment by auyeung112002** [comment]
https://github.com/odoo/odoo/issues/15000

Not sure if it is related?

**Comment by Yenthe666** [comment]
@qdp-odoo is already assigned and it is labeled for accounting so this should be handled as soon as he has some spare time.

**Comment by qdp-odoo** [comment]
ping @lap-odoo

**Comment by qdp-odoo** [comment]
this has been fixed in saas-11.2, at revision e1306066026649acd388b49d7429337d87cf819a

We indeed consider that the patch is too huge/risky for being applied massively as it on stable versions.

Anyway, thanks for the reporting and the contribution

**Comment by auyeung112002** [comment]
Can you make a patch for users to download for v10 and v11?

**Comment by qdp-odoo** [comment]
yes... actually the patch can be applied directly as it to v11, for the other stable versions please contact our support team via the regular channel (https://www.odoo.com/help)

**Comment by qdp-odoo** [comment]
wait a minute... actually that patch needs a patch (that was to illustrate why it is risky to do in stable versions)

**Comment by auyeung112002** [comment]
It will be more risky to keep this bug in stable versions since it produce inaccurate accounting entries.

**Comment by auyeung112002** [comment]
For example, income becomes expense and vice versa.

**Comment by qdp-odoo** [comment]
fix of the fix landed at 8bec4fa

@auyeung112002 I know, that's not ideal at all... @nim-odoo who's in charge of the support might revise his opinion on that hot topic, sooner or later, when my patch would have reached a final version for example :-)

**Comment by auyeung112002** [comment]
@qdp-odoo I created this fix and tested this will solve the original problem I mentioned in this issue. Would you please comment on the fix under version 10 and 11? I understand that the fix is not going to merge in stable release. But I wonder if this is a acceptable workaround.

https://github.com/auyeung112002/odoo/commit/ea2f4a6c57161ebee0206e20f76e5145b325038d
