### ISSUE TITLE
[9.0] Deinstalling and reinstalling marketing campagne makes it impossible to choose website theme

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#21898]
Impacted versions: 9.0 (I've seen similar behaviour on 10.0 and 11.0 but haven't found a reproducable way yet)

Steps to reproduce:
1. Deinstall `marketing_campaign`
2. Reinstall `marketing_campaign`
3. After a few seconds you'll see the page to select your theme but it simply shows `False` and you can't choose a theme. You're also 'stuck' on this page:
![image](https://user-images.githubusercontent.com/6352350/34411180-5c321bd8-ebd5-11e7-931c-ab5faac1402d.png)
**Note:** You can only do this once per database so be sure to test it on a clean runbot / test instance

Current behavior: You're stuck on the page and can't choose the theme.

Expected behavior: Either you're able to choose your theme (again) or Odoo skips the page.

**Comment by Yenthe666** [comment]
OPW 802936

**Comment by Elkasitu** [comment]
@Yenthe666 I can't seem to reproduce your issue, even on a clean local install, however I did notice that upon installation or reinstallation of marketing_campaign I get redirected to an empty page (non-blocking though, the installation happens anyway) and the outcome is different in community and enterprise:

Community: An error is logged to the console saying 'Menu no action found web test 04 will fail' and the screen is all white

Enterprise: A JS traceback appears on screen, action is undefined

In both cases it seems like it can't find some action (potentially the choose your theme action?)

@ged-odoo can you or any of your boys look at this?

**Comment by Yenthe666** [comment]
@Elkasitu,

Thanks for the feedback.
Some things seem to have changed in the meanwhile indeed. Just tested on V9 ENT runbot and it now actually throws a JS error.
Runbot: http://289383-9-0-093470.runbot14.odoo.com/web?#menu_id=156
Error:
![image](https://user-images.githubusercontent.com/6352350/34567297-002ccaf8-f162-11e7-82e6-236b1bc32ec3.png)


V9 community gives a white page now:
![image](https://user-images.githubusercontent.com/6352350/34567347-3928d572-f162-11e7-9e3a-e26765f9c5d7.png)

**Comment by Yenthe666** [comment]
Hi @Elkasitu,

Did you get around to looking at this yet?
I've just tried it again but it seems to need a minor change instead of the first error report.
Now you should have developer mode activated the whole time to trigger it.
The issue for the white page is still present in V9 community too.

Regards,
Yenthe

**Comment by Elkasitu** [comment]
Nope sorry, I'll have to check with the JS team

**Comment by Yenthe666** [comment]
Okay - thanks!

**Comment by Yenthe666** [comment]
My monthly return! Any update @Elkasitu?

**Comment by Elkasitu** [comment]
@Yenthe666 Actually yes, but since it's really old JS it will have to be looked at by @nim-odoo 's team when they have the time ;)

**Comment by Yenthe666** [comment]
Awesome - good to know that it is somewhere in the backlog.

**Comment by Yenthe666** [comment]
Yup, looks good. Thank you!
