### ISSUE TITLE
Uninstalling website module blocks general settings

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#21905]
Impacted versions: 11.0

Steps to reproduce: Just test on [Runbot](http://289106-11-0-b95622.runbot13.odoo.com/web?debug=1#id=&view_type=form&model=res.config.settings&action=110&menu_id=4) --> Uninstall website module --> Go to the Configuration page for any module > Make any changes and save it.

Current behavior: [Odoo Server Error - Validation Error]

![](https://image.prntscr.com/image/Gx3lGxX4Qg6lsxAhGxL5SQ.png)

Even the field which was added by website module (website_id) is also not removed from the database.

![](https://image.prntscr.com/image/Wn1C8lPdTg6frBLga0ZVqQ.png)

Expected behavior: Configuration should be applied.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thank you for the bug report.
I've just tested this and I can confirm that this is a bug. 
I've made an official bug report with ticket number 803018

Regards,
Yenthe
