### ISSUE TITLE
[10.0] Inherited view is not working with Many2one on itself

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#21903]
**Impacted versions:**
10.0 and above

**Steps to reproduce:**

```python
class AccountInvoice(models.Model):
    _inherit = 'account.invoice'

    related_invoice_id = fields.Many2one(
        comodel_name='account.invoice',
        string='Related Invoice',
        compute='_compute_related_invoice',
        store=True, readonly=True
    )

    @api.multi
    @api.depends('name')
    def _compute_related_invoice(self):
        for invoice in self:
            related = False
            related_invoices = invoice.search([
                ('name', 'like', invoice.name),
                ('id', 'not in', invoice.ids),
            ])
            if related_invoices:
                related = related_invoices[0]
            invoice.related_invoice_id = related
```
```xml
 <record id="invoice_form" model="ir.ui.view">
    <field name="name">Customer Invoice (Form)</field>
    <field name="model">account.invoice</field>
    <field name="inherit_id" ref="account.invoice_form" />
    <field name="arch" type="xml">
        <data>
            <field name="name" position="before">
                <field name="related_invoice_id" attrs="{'invisible': [('related_invoice_id', '=', False)]}" />
            </field>
        </data>
    </field>
</record>
```
**Current behavior:**
Error while valildating the view as the field is not found although it is registered and working...easily tested by adding it to the main view which should be inherited in the database

**Expected behavior:**
Validation should not block if the field is available and ready to use

@rco-odoo @nim-odoo 
I was going nuts with this as I could not believe it is an issue of the framework in the first place but it seems to be. Please check and fix this...probably it is also present in 9.0. Thank you.

OPW-802962

**Comment by kebeclibre** [comment]
Hey,

I tried in v10 as admin:
created a custom field on hr.employees
adding it in the main form view as

`<field name="x_lol" attrs="{'invisible': [('x_lol', '=', False)]}" />`
It works correctly

removing it from the main view,
create a inherited view
inserting the field as 
`<field name="department_id" position="before">
<field name="x_lol" attrs="{'invisible': [('x_lol', '=', False)]}" />
</field>`
Also works fine

Am I missing something ?

**Comment by wtaferner** [comment]
@kebeclibre 
Maybe try it with creating a module depending on ```account.invoice``` like I did (computed stored field) and inherit the view like described and try to install it? It seems the new view validation is playing a role here...but maybe in the meantime it works as something has been fixed? I don't know...anyway, it has been a month since the bug report. 
If this works on your side I will test again on mine.

**Comment by kebeclibre** [comment]
@wtaferner 
Hi, I tried many things and here is what I found:
using <field /> as a xpath will end up doing xpath =  //field[XXXX]
Then first occurence is taken to do the inheritance

in the view you try to inherit from, the first field name=name is the one of invoice_line_ids

`  <field name="invoice_line_ids" nolabel="1" widget="one2many_list" mode="tree,kanban" context="{'type': type, 'journal_id': journal_id, 'default_invoice_id': id}">
                                <tree string="Invoice Lines" editable="bottom">
                                    <field name="sequence" widget="handle"/>
                                    <field name="product_id"/>
                                    <field name="origin" invisible="1"/>
                                    <field name="name"/>`
In this case, related_invoice_ids will try to refer to invoice_line_ids.related_invoice_ids which indeed doesn't exist

I tried to do an xpath on another field, and it works just fine to have the field in a domain, in the attrs of itself.

You can do an explicit refined xpath to avoid the problem

I'm closing this issue

**Comment by wtaferner** [comment]
@kebeclibre 
Oh, damn, I was not aware that it is diving into sub-views and models too for the simple inheritance (it is actually weird and confusing as I stumbled here, but thank you for pointing out, so I will hopefully think about anytime in the future). My bad, thank you very much for taking the effort to explain it. :+1:
