### ISSUE TITLE
Invalid Status (Locked/Unlocked) of Manufacturing order

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#21904]
Impacted versions: 11.0

Steps to reproduce: Go to [runbot](http://289107-11-0-012682.runbot8.odoo.com/web?debug#view_type=list&model=mrp.production&menu_id=487&action=680) --> Create new Manufacturing order --> It will create new MO in Locked state (Unlock button is also visible)

Current behavior: MO is created in the Locked state.

![](https://image.prntscr.com/image/-8cZ_9CqTuy4k6KnEsIjGw.png)

Expected behavior: MO should be created in Unlock state.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@sle-odoo 
This has been introduced from this [Commit](https://github.com/odoo-dev/odoo/commit/94b673dd293c3889c41b026e98dcab5033a72250#diff-b62e2447dcdf46e87d838527e24dc866R163)

**Comment by sle-odoo** [comment]
it's the expected behavior, isn't it? if i'm not wrong, the unlock is only visible to the mrp manager and allows to edit the reserved quantities and other things.

**Comment by sswapnesh** [comment]
Those buttons Lock/Unlock are only visible to MRP manager.
But what I am thinking is "`Unlock`" should unlock (`set is_locked= False`) the MO and should be visible if MO is locked and "Lock" should be visible and it should (`set is_uocked= True`).

So when we create MO, `is_locked` should be set to `False` and Lock button should be visible.

**Comment by sswapnesh** [comment]
@jco-odoo I am not sure If I should ping you or not but you have added this [here](https://github.com/odoo/odoo/commit/94b673dd293c3889c41b026e98dcab5033a72250).

**Comment by sle-odoo** [comment]
> So when we create MO, is_locked should be set to False and Lock button should be visible.

the mo should be locked by default, and then if a manual change is needed, the manger unlock it, change the quantities and lock it again

what's the usecase you cannot do with the current implementation?

**Comment by sswapnesh** [comment]
I agree with this use case also but the Same works differently for Sale order, So it is Confusing.

You can close this If you believe the current scenario for MO is more usable.

**Comment by sle-odoo** [comment]
i get your point... it is however consistent with the pickings and also with the sale order if you enable the "auto lock" mechanism.

i consider it the expected behavior and we cannot change this in 11 anyway.

thank you for the reports though, if you stumble on others issues feel free to ping me
