### ISSUE TITLE
Ref.Question. Automatic Currency Rates updates

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#21919]
Impacted versions:
11e

Exchange rates automatically update functionality is hardcoded in currency_rate_live module for 4 sources.

Will it be refactored for more common API usage or we sholdn't wait and rewrite module for our purpose?

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

Please do link all the places you're talking about - it'll help Odoo!

**Comment by Elkasitu** [comment]
What do you mean by "a more common API usage"? what is your use case? If you want to do your own queries from another module you can just query the APIs yourself, they're all free iirc

**Comment by sergeiruzkiicode** [comment]
@Elkasitu 
more common - it's like:

currency_provider can be a function, list of providers goes to the db. 
update_currency_rates() can be rewrited and call separate function for currency_provider code:

```
try:
    parse_function = getattr(self, 'parse_currency_{}'.format(company.currency_provider.code)
    rates_dict = parse_function()
    pass
except:
    rates_dict = False

```
rates_dict should have common structure.
so then we can have update_currencies(rates_dict) function to store data in db.

so we can inherit ResCompany model with functions like update_currency_PROVIDER, add or remove providers in db without risk to loose another providers when we add or remove modules.
