### ISSUE TITLE
[10.0] account_tax_cash_basis: does not take into account if a tax is directly coded in the payment reconciliation

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#21923]
**Impacted versions:**
10.0 and maybe above

**Steps to reproduce:**
- Define a tax and use tax cash basis by defining the two accounts normally needed
- Go into a bank or cash journal statement and do reconciliation
- In case there is no invoice with the proper intermediate account move lines for the tax not yet and you try to apply this tax on the payment itself it does take the wrong (intermediate) account for the account move line instead of the final account (already taxable)

**Current behavior:**
Wrong account chosen by the system for directly paid and coded account moves

**Expected behavior:**
Take the correct final destination account in case the invoice was not done on another date and the intermediate account is needed to reduce the intermediate tax in case less is paid (i.e. "cash" discount or any other reduction)

@qdp-odoo @nim-odoo 
I tried to figure out a way how to do it for doing a PR but was not happy about this and finally decided to let Odoo fix it "alone"...I think you are more than happy to just fix something with a clear use case and a real bug for me, are you? ;-)

OPW-803075

**Comment by qdp-odoo** [comment]
mmh unfortunately, given that, for cash basis taxes, the said intermediate accounts have to be set on the "regular" account fields, I don't see how we could fix that. BTW, the journal items created are also set as tax_exigible=False...

I suppose, we don't have any solution but to say that this use case is not supported: you've selected a cash bases tax, and that's what Odoo is doing. If you don't want that behavior, you should have a non-cash-basis version of that tax ready.

That being said, we could probably simply add [('use_cash_basis', '=', False)] in the domain of taxes in bank statement reconciliation widget... what do you think?

**Comment by wtaferner** [comment]
Hmm, the work around sounds reasonable (an extra tax which is directly put on the right account).

The domain is a bit difficult for the taxes which should be deducted from the intermediate accounts if you are writing-off  an invoice for the cash discount or other payment relevant tax reductions.
But maybe you could add a checkbox to activate and deactivate the domain in Javascript which would help to emphasize the issue and make it clear to be responsible yourself to have the right taxes at hand.

**Comment by qdp-odoo** [comment]
Well, no. if you think it has still some meaning to allow the use of cash basis taxes in the bank statement reconciliation widget then we'll just leave as it.

Since the workaround proposed is the only valid option, I'm closing the issue.

thanks for your understanding

**Comment by wtaferner** [comment]
Hmm, not soo much understanding this time as it seems a nasty usability bug, but thank you anyway for the feedback and the suggested workaround. I hope you think about this in master and future versions as usability is not clearly communicated and should be improved. Would you accept a PR on the suggested usability fix in the module (not saying I will do it, but asking helps to categorize your No)?

Configuring for "every" use case a new tax is a bit odd and is making instances complex for the user in the end. Luckily I have hardly customers using this, but still I think Odoo owe them a clean and easy solution at some point for such a feature like cash tax basis ;-)

**Comment by qdp-odoo** [comment]
actually, I personally don't see any real use case where you would choose deliberately to use a cash basis tax in the statement reconciliation widget, so I will double check that and probably add the said domain [('use_cash_basis', '=', False)] in the widget. That way, the usability issue will be "fixed" (well, kinda).

I'm against your proposal since it would make a more complex fix (# lines of code, ...)  for a use case that shouldn't happen (according to me, but I might be wrong). That's the reason: keep the code as clean as possible by avoiding exceptions being too present in the code.

Hope this clarifies my position :-)

**Comment by wtaferner** [comment]
Ok, so you don't see the use case...well, I can guarantee you that there is one as this was found together with an accountant I work with ;-)

It is common that not all invoices are put into the invoicing model as small bills and amounts are sometimes coded directly in the T account view instead of having the overhead of creating an invoice for each of them as they were directly paid...you might use the expenses module I guess, but I have not yet tested that it works for tax cash basis as well and it is also considered as an overhead.

And again, there might be a situation where you want to write off a tax or better say you do not finally have to pay the tax (so we have mixed use cases which needs to be possible to show the correct taxes, if we use the workaround) - by the way this is also not considered in the payment widget on the invoice itself as it is not possible to write-off the related tax)...so, taxes should be used with care and knowledge in the reconciliation widget which is a cool tool for accountants...by now, this is not communicated at all on a user level...

I wonder why you consider this only happening if you don't do tax cash basis, but maybe there is a different angle how we see tax cash basis to be used, not sure if we can find a common view in writing ;-)
