### ISSUE TITLE
Extended Addresses  module creating  useless fields.

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#21927]
Impacted versions:

11

Steps to reproduce:

Install extended address module and create a new partner

Current behavior:

2 fields are added House number and Door number. The problem is you can only see one digit in any of the fields. If you tipe you can only see 1 number. 

Expected behavior:

See at least 3 or 4 digits, if not the extra fields are useless. This is a view error.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hmm that is a usability thing but quite annoying.. @mart-e can you pass this through?

**Comment by mart-e** [comment]
This is due to the size of the window, too much information on a column.
I agree it can be improved. Changed that in master at 98580ed7301b651f4f592b078eeb946d766812fc
