### ISSUE TITLE
POS Test Workflow should work with a "required" partner on sale

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#21922]
**Impacted versions:**
10.0, 11.0

**Steps to reproduce:**
Test in Odoo.sh with a POS module that makes the partner a requirement for every sale.

Current behavior:
POS Workflow fails as the partner is required.

Expected behavior:
Most continental (anglo-saxon) countries require a partner on the point of sale; which makes the tests to fail when this is the case.

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

Thanks for your report.
Am I correct that by adding custom development you're breaking the test because you're requiring a customer?

Regards,
Yenthe

**Comment by gustavovalverde** [comment]
That's correct @Yenthe666

**Comment by Yenthe666** [comment]
Hmm doesn't sound like a very big problem to me but perhaps the test can be slightly altered.
CC @jorenvo (sorry for the ping Joren I forgot the other guy his name that does the POS now)

**Comment by jorenvo** [comment]
Are you proposing to modify the tests to set a partner on every POS order? I don't think that's a good idea, the standard POS doesn't need that. Modifying the tests should be done by the custom module. Maybe the easiest way is to patch the `pos.order` `create` function in the test code to set some default partner. You'd have to monkey patch the POS test classes, here's an example of how you can patch the create function:

https://github.com/odoo/odoo/blob/652f8746d6d1cc16bed1d388a4341f717c93dbcb/odoo/addons/test_assetsbundle/tests/test_assetsbundle.py#L359-L380

**Comment by gdgellatly** [comment]
If you make a field required in an extension module then in general it is best practice to give a default.

Forget the tests.  What about the existing data before you install said extension?

**Comment by jorenvo** [comment]
Indeed, if this is meant to be a reusable module then it might be a good idea to consider what to do with pre-existing `pos.order` records. Regardless, I don't think this is an issue in standard Odoo so I'm closing this. If you have any further questions you can still reply.
