### ISSUE TITLE
[11.0] Export pivot table into Excel

### ISSUE THREAD

**Issue by minos84** [odoo/odoo#21941]
Impacted versions: 11.0

Steps to reproduce:
In a pivot table view, when I click on vertical arrow icon for exporting Excel, I got an error.

Current behavior:
The pivot table is not exported and this error is displayed:
Erreur:
Uncaught SyntaxError: Unexpected token T in JSON at position 0

http://my-odoo-url/fr_FR/web#view_type=pivot&model=sale.order&menu_id=67&action=405:1
Retraçage :
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (http://my-odoo-url/web/content/307-e9e73df/web.assets_common.js:3848:379)
    at HTMLIFrameElement.dispatch (http://my-odoo-url/web/content/307-e9e73df/web.assets_common.js:892:451)
    at HTMLIFrameElement.elemData.handle (http://my-odoo-url/web/content/307-e9e73df/web.assets_common.js:865:173)

Expected behavior:

The pivot table in every pivot table should be exported.

Video/Screenshot link (optional):

**Comment by Ark74** [comment]
Hi!
Two questions,
How many lines are you trying to export?
Are you using a reverse proxy with your odoo instance?

Cheers!

**Comment by minos84** [comment]
**How many lines are you trying to export?** ==> I have used it for 1, 2 or more lines. I got the same error

**Are you using a reverse proxy with your odoo instance?** ==> No, I am using an apache 2 server

Thanks!

**Comment by Ark74** [comment]
Since there is only so few lines, then it must be something else that I was suspicious of.
You might wanna check it on a [runbot](http://runbot.odoo.com/runbot) and confirm you can reproduce it there.

Since you are using apache then **you are** using apache as a reverse proxy.

I got a similar issue but it was because I was exporting 65k lines, and it was related to a timeout between the proxy (apache) and Odoo. Ending on this error.

Cheers!

**Comment by Ark74** [comment]
Finally, you could check that your proxy is well configured.

**Comment by minos84** [comment]
Thanks Ark74, in ubuntu nightly odoo 11 package version, the tool "xlwt" is not pre-installed. The installation of this tool solved my issue.

Thanks to "Shameem Babu" in this thread:

https://www.odoo.com/fr_FR/forum/aide-1/question/uncaught-syntaxerror-unexpected-token-t-in-json-at-position-0-104689
