### ISSUE TITLE
[translation] add translators list to odoo.com website.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#21956]
Impacted versions:
all

Steps to reproduce:

Current behavior:
no translator contributor listed in odoo.com website.

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jeffery9 is there any reason why you would like this or find that it should be added?
@mart-e this is absolutely for you!

**Comment by mart-e** [comment]
Hello,

While a credit page could be a nice idea, it is not something we have at the moment, sorry.

**Comment by jeffery9** [comment]
do you have any plan for this?

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [translation] add translators list to odoo.com website. (#21956)
发件人：Martin Trigaux
收件人：odoo/odoo
抄送：Jeffery CHEN Fan ,Mention


Hello,

While a credit page could be a nice idea, it is not something we have at the moment, sorry.

―

**Comment by jeffery9** [comment]
this option should attracting more people to improving the website

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [translation] add translators list to odoo.com website. (#21956)
发件人：Martin Trigaux
收件人：odoo/odoo
抄送：Jeffery CHEN Fan ,Mention


Hello,

While a credit page could be a nice idea, it is not something we have at the moment, sorry.

―

**Comment by mart-e** [comment]
I will report the feedback for improving the website
