### ISSUE TITLE
[11.0] General Holiday in Leave Request Calender

### ISSUE THREAD

**Issue by abdallamohamed1992** [odoo/odoo#21960]
Impacted versions:
11.0
Steps to reproduce:
1. Add general holiday in Working Time.
2. Create new user 
3. Assign "Related User"  in employee and choose "Working Hours"
4. Create new contract and choose same "Working Hours"
5. Login with user and open Leave Request screen

Current behavior:
There is no general holiday appear in his calender
Expected behavior:
Appear general holiday as in "Working Hours"

**Comment by Yenthe666** [comment]
@mart-e perhaps this check should be done when the employee is created? What do you think?

**Comment by jem-odoo** [comment]
Hello, 

actually, this is not a supported feature. Since it may be cool, i'll transmit it to the concerne team. Maybe it will be available in futurue version. 
Thanks.
