### ISSUE TITLE
Website Event Sale : registrations with wrong data

### ISSUE THREAD

**Issue by tandrieuxx** [odoo/odoo#21975]
Impacted versions: 11.0

Steps to reproduce:
website_event_sale needs to be installed.
Log in Odoo and go the website. Buy tickets (at least 2) for an event. Provide the attendees' information in the popup, in this example their name will be : "Attendee 1", "Attendee 2". Validate and you should be redirected to the cart (No need to go further).

![attendees](https://user-images.githubusercontent.com/22955971/34489546-0f2d464e-efdd-11e7-890a-2c1300ea8218.png)

Current behavior:
Back to Odoo's backend, if you display the list of attendees for the event you just bought tickets for, you should see 2 new lines :

![attendees2](https://user-images.githubusercontent.com/22955971/34489565-1a96471a-efdd-11e7-9bde-4a93ac7e32e5.png)

One with the right data (Here "Attendee 2", his email address and phone number) and all the others with some default data corresponding to the user logged in (here "Administrateur", his email address and phone number because I was logged as an administrator when I purchased the tickets)
There is always only one attendee with the right data (sometimes the first, sometimes the last) and others with the wrong data.

Expected behavior:

Every attendee created should have the data provided by the user who purchased the tickets, not only the first or last one.

**Comment by rdeodoo** [comment]
Hello, thank you for your issue.

I couldn't reproduce the issue locally as you can see on this video: https://youtu.be/XfZJf3opyU8
Any steps I forgot or didn't reproduce like you mentioned?

**Comment by tandrieuxx** [comment]
After further investigations, the problem comes from our module. Thank you and sorry for bothering you.
