### ISSUE TITLE
[10.0/11.0]  Traceback during creating meeting from Calendar 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#21979]
Impacted versions: 10.0/11.0

Steps to reproduce: Just tested on [Runbot](http://289916-11-0-3fe946.runbot14.odoo.com/web?#view_type=calendar&model=calendar.event&menu_id=147&action=177) --> Go to Calendar menu --> Create meeting

Current behavior: Traceback on Screen

![](https://image.prntscr.com/image/Wo2Tix-CSBeGf_DK7YZP7w.png)

![](https://image.prntscr.com/image/9fo7Cg3oR3Kx6b1bHqhG2Q.png)

Traceback
```
File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/addons/crm/models/calendar.py", line 38, in create
    event = super(CalendarEvent, self).create(vals)
  File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/addons/calendar/models/calendar.py", line 1525, in create
    meeting = super(Meeting, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/addons/mail/models/mail_thread.py", line 231, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/runbot/extra/runbot/static/build/289916-11-0-3fe946/odoo/addons/calendar/models/calendar.py", line 881, in _inverse_dates
    startdate = tz.localize(startdate)  # Add "+hh:mm" timezone
  File "/usr/lib/python3/dist-packages/pytz/tzinfo.py", line 303, in localize
    if dt.tzinfo is not None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'
```
Expected behavior: Startdate should be required in xml (If needed) and Meeting should be created.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi, thanks for the report, but i cannot reproduce: 
![image](https://user-images.githubusercontent.com/4848797/34515032-8e071380-f070-11e7-8d76-227b62688bb4.png)

Required field are well caught.

tested on: http://289999-10-0-36e784.runbot8.odoo.com

**Comment by sswapnesh** [comment]
Could you please try same from Calendar view it self?

**Comment by sswapnesh** [comment]
Just tested on same runbot instance, Can reproduce Issue there too.

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

I've just tested it too but I couldn't reproduce it either.
You're doing this from the app `Calendar` from the agenda/treeview right?
![image](https://user-images.githubusercontent.com/6352350/34554445-3993a954-f12d-11e7-9346-f4149dde2917.png)
Could you make a little movie please?

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Hello @Yenthe666  
Just test on [Runbot.](http://290681-11-0-6a481d.runbot9.odoo.com)

Here is the Video [https://youtu.be/pvyFepay-ik](https://youtu.be/pvyFepay-ik)

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks a lot for the video! This is indeed a bug and I was able to reproduce it now too:
![image](https://user-images.githubusercontent.com/6352350/34598909-b6597d5c-f1ef-11e7-914b-1b205342e15f.png)
@JKE-be can one of your guys look at it?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Ok, thanks we can reproduce it !

Maybe @adr-odoo could take a look in the same time of issue 19355... thanks

**Comment by sswapnesh** [comment]
@JKE-be 
You can close this Issue. (Not sure if it has been forwarded to v11 or not)
