### ISSUE TITLE
[11.0] PayPal IPN settings do not seem to work

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#21986]
### Impacted versions:

11.0

### Steps to reproduce:

1. Configure PayPal business account and Odoo's PayPal acquirer as explained in this doc (set the acquirer to test mode): https://www.odoo.com/documentation/user/11.0/ecommerce/shopper_experience/paypal.html

2. Buy something on online shop with PayPal.  Confirm payment in PayPal and immediately close the browser tab.  As a result, the transaction status in PayPal becomes "Completed", however Odoo's payment transaction stays as draft.
![image](https://user-images.githubusercontent.com/7766939/34512134-3edfbdf4-f09b-11e7-9fc6-7c1b7c158ba0.png)

3. Open IPN history in PayPal account through https://sandbox.paypal.com/ie/cgi-bin/webscr?cmd=_display-ipns-history&nav=0.3.2 and resend the concerned IPN message. Wait for a few minutes for the resend to complete. Open the resent message to confirm that it went through with HTTP response code 200.
![image](https://user-images.githubusercontent.com/7766939/34512257-0df71b50-f09c-11e7-95a4-8923f3de3597.png)

### Current behavior:

The status of the payment transaction in Odoo remains as draft.

### Expected behavior:

The status should be updated to done upon receiving IPN.

**Comment by Yenthe666** [comment]
Hi @yostashiro,

Thanks a lot for your report!
@tde-banana-odoo could you please have a look?

Regards,
Yenthe

**Comment by vostokbike** [comment]
Can confirm similar behaviour on [11CE]. It looks like the payment is not attaching to the SO at all. 
IPN set as per above article.

**Comment by JKE-be** [comment]
Should be fixed by f2bcebb9f2046f3c87dbcf3c99054cee555c53fe

Thanks for the reporting
