### ISSUE TITLE
[11.0] Parsing CSV uses wrong format

### ISSUE THREAD

**Issue by Ottunger** [odoo/odoo#21988]
Impacted versions: 11.0

Steps to reproduce: Import CSV and set custom date or datetime format

Current behavior: The frontend sends %%w whereas %d format was asked

Expected behavior: The frontend should send %d

Video/Screenshot link (optional): http://hpics.li/b247400

**Comment by gdgellatly** [comment]
What happens if you use a valid date?  i.e not the 24th month of the year.

**Comment by Ottunger** [comment]
Nvm in my screenshot I used a wrong date but I did try both, and same result.

**Comment by JKE-be** [comment]
Hu,

You need to specify the format with this syntax: YYYY-MM-DD HH:mm
