### ISSUE TITLE
[10.0] Error when trying to read multiple records using xmlrpc

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#21994]
Impacted versions: 10.0

Steps to reproduce: Create a database on last 10.0, install accounting modules for example and create a few invoices and validate them. After that, try to read account.move with a few existing ids using xmlrpc script like this:
![image](https://user-images.githubusercontent.com/7678583/34527312-7d41c254-f0a5-11e7-8b5c-08122d59f1d4.png)

Current behavior: If one id, it works well, if more than one id, i have this error:
![image](https://user-images.githubusercontent.com/7678583/34527373-a8217550-f0a5-11e7-9e67-d9a24ccb9680.png)

Expected behavior: We wait for a list containing field values for each record (as it was working in version 8 for example)

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
maybe ...` 'read', [[1,2,3], ['id', 'name']]) `

please provide your sample in plain text.

**Comment by fmdl** [comment]
Replace `[1,2,3]` by `[[1,2,3]]`.

Infomation for  Xml RPC: https://www.odoo.com/documentation/10.0/api_integration.html

**Comment by Elkasitu** [comment]
API misuse

**Comment by jlaloux** [comment]
Thx for your help
