### ISSUE TITLE
[BUG][10.0][11.0] There is no option to link tax code on each account.move.line

### ISSUE THREAD

**Issue by giordano-ch** [odoo/odoo#21995]
Impacted versions:
9, 10, 11 (Community and Enterprise)

Steps to reproduce:
1. Create Invoice with random tax code and validate it
![1-1-rechnung-mit-mwst](https://user-images.githubusercontent.com/15436224/34528434-3f9ee32e-f0a9-11e7-930d-72b0d7c9c1c7.JPG)
![1-2-journal_entry](https://user-images.githubusercontent.com/15436224/34528462-4f50d9a8-f0a9-11e7-9cd8-50043d5f54db.JPG)

2. After Validation, Journal Entry is generated
![1-3-journal-entry-tax-line](https://user-images.githubusercontent.com/15436224/34528503-6bc4f90c-f0a9-11e7-8943-9b7462c2548c.JPG)

3. Now click on the tax line (without entering edit mode)
![1-4-tax-origin](https://user-images.githubusercontent.com/15436224/34528556-8b11044a-f0a9-11e7-9624-5cf1129f6e60.JPG)

4. The tax code is in the field originator tax. So far so good, everything is correct.

5. Now try to do the same, but create the entry manually. 
![1-5-manual-entry](https://user-images.githubusercontent.com/15436224/34528736-1e87229a-f0aa-11e7-85f7-54285811532c.JPG)
![1-6-manual-entry-tax](https://user-images.githubusercontent.com/15436224/34528745-227d2d2c-f0aa-11e7-885d-ca1ddf4e5df3.JPG)

As you can see the field originator tax is not visible on each line. This means there isn't an option to link a tax code on a journal entry/item if it is created manually. It only works with automatically generated invoices.

Am I missing something out? If not this is a huge bug in my opinion.
p.s. in version 8 it worked perfectly.

**Comment by Yenthe666** [comment]
Hi @giordano-ch,

Thanks a lot for your report.
@qdp-odoo could you have a look please?

Regards,
Yenthe

**Comment by smetl** [comment]
Hello,

The creation of journal entries will be improved on the next release. 

However, if you need to do so in your current version, you can "add" this feature manually by adding on the `account.view_move_form` view, in the "Journal Items" section:

```
<field name="tax_ids" string="Taxes Applied" widget="many2many_tags" options="{'no_create': True}"/>
<field name="tax_line_id"/>
```

The `tax_ids` field allows you to add taxes.
The `tax_line_id` field corresponds to the 'Originator Tax'.

Don't hesitate if you have any questions.

Best regards,
