### ISSUE TITLE
[9.0] Inventory valuation doesn't show total valuation

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22009]
Impacted versions: 9.0

Steps to reproduce:
1. Open up a V9 runbot and go to inventory
2. Go to Reports > Inventory Valuation
3. Let the Odoo generate all the data and look at the bottom of the view:
![image](https://user-images.githubusercontent.com/6352350/34554066-4b9f4448-f12b-11e7-833d-d767b265499b.png)
There is no total shown, while this is pretty much what the inventory valuation report is usefull for.
Now check a V10 or V11 you'll see the total amount of all inventory lines:
![image](https://user-images.githubusercontent.com/6352350/34554096-6bc2a3e6-f12b-11e7-9a51-2debf043d97c.png)

Current behavior: There is no total shown for the inventory valuation (like in V9/V10)

Expected behavior: See the total of the inventory valuation

**Comment by Yenthe666** [comment]
OPW 803786

**Comment by lukebranch** [comment]
A printed report is also a commonly requested requirement here as well.

**Comment by Yenthe666** [comment]
@lukebranch agreed - I was missing that too. That would be a new feature and would be for master though. Perhaps we should make a wishlist item for this.

**Comment by nim-odoo** [comment]
We only fix critical issues for v9... This is more an improvement. So we won't fix this.

**Comment by Yenthe666** [comment]
As I've responded on the official ticket:

> Hi Nicolas,
I don't agree with this one. The whole point of that view is to get the total of your inventory valuation. What use does this view ever have if I cannot see the total of the inventory valuation? I can only see the total per line.
You could say "why don't you export those lines?" and get the sum in Excel right? Nope, because I would have to unfold every single product manually and then also unfold the locations before I can check them all on and export it to a CSV.
Finally, there is no option to print out this data so there is not a single way for me to get these numbers out in a PDF report nor in an Excel.
Furthermore the feature is present in V10 & V11 and works like a charm.
Could you please recheck this? I really think this is a legit issue.
Regards,
Yenthe


@JKE-be pointed out that you could do it with an advanced groupby and he has a fair point. This will work but I still believe that it should be in V9 too. But that is just my opinion!

**Comment by JKE-be** [comment]
The group by was the easy way to do the sum without update the code.
The change to do in the code will be to add sum=' ' into the field inventory_value from the tree view.
