### ISSUE TITLE
[Odoo.com website] wrong link to Mailing List in footer

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#22022]
This bug is redated to Odoo website.
Despite the reworked page on Mailing Lists (https://www.odoo.com/groups), the footer in each web page still point to the old one (https://www.odoo.com/page/odoo-community)

**Comment by Yenthe666** [comment]
@mart-e or @JKE-be for one of you to fix in the official Odoo website. 😉 
Perhaps we should also make some redirects?

**Comment by mart-e** [comment]
Please report the odoo.com bugs to the support team, github is for bugs on the software Odoo.
Nevertheless, I have fixed it as an easy one :-)
