### ISSUE TITLE
[BUG] Configuring warehouses infers from user company instead of warehouse company

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22028]
Impacted versions:
10.0

Steps to reproduce:
1. Beeing logged in into a holding company
2. Adapt warehouse configuration of child companies

Current behavior:
1. Routes will be created with the holding company set
2. Therefore, routes will never apply for the warehouse of the respective child company.

Expected behavior:
1. It has it's logic (create a route for the holding company doing movements as holding in child companies)
2. But the expected behavior is: it will configure the Warehouse itself, that is under the hood of the warehouses' company.

@jco-odoo 

Video/Screenshot link (optional):

**Comment by jco-odoo** [comment]
I think this is solved by ecaf5f6

**Comment by blaggacao** [comment]
Wow, nice, thanks! I definitely need to rebase :wink:
