### ISSUE TITLE
Bug: While making a return from Picking

### ISSUE THREAD

**Issue by burhanghee** [odoo/odoo#22035]
Impacted versions:
11
Steps to reproduce:
1) Create a one line Sales Order with Qty 1 and UOM Dozen.
2) Confirm the order and complete the Picking.
3) Make a return from the completed picking.
Current behavior:
The return order will be created with Qty 12 and UOM Dozen
Expected behavior:
The return order should have created with Qty 1 and UOM Dozen
Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hello,
I just tried your steps and the return is 60 units. Is your code up to date? This issue was solved by rev https://github.com/odoo/odoo/commit/0322f6e51f41f92b3531942b0923dfe74cfcd26a#diff-fc6cef81fac5ca3c30afb09ccb60ff4c4

**Comment by Yenthe666** [comment]
@burhanghee please update your Odoo instance and try again.
Alternatively you can try this on an official Odoo test instance at runbot.odoo.com (username and password are both admin).

Regards,
Yenthe

**Comment by burhanghee** [comment]
Hi,

Yes, it fixed.

Thanks all. Cheers
