### ISSUE TITLE
refund option in PO return movement

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#22049]
Impacted versions: 10

Dear All,
I've noticed in the version 11 the refund option in return movement with reference to a PO is avalable.
could it be implemented in version 10 also?
Regards
claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thanks for the report/feedback.
However adding new features (even if they exist in newer versions) to an older version is against the stable policy of Odoo.
You can find more information at https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Regards,
Yenthe

**Comment by ccandito** [comment]
Dear Yenthe,
before disregarding it, please consider the following thread also
received and billed qty in PO form are not updated properly #13642
regards
claudio

**Comment by Yenthe666** [comment]
@ccandito no matter what.. a new feature or option is never allowed in a stable version, only in the master. Those are the rules (which I didn't come up with).
Anyways, I'll leave the final call to @mart-e

**Comment by mart-e** [comment]
Sorry but as said Yenthe, we do not add new features in stable versions, it is too dangerous for the users running in production with it.

**Comment by ccandito** [comment]
Dear All,
in the screen there is already this indicator;
so it is not a new feature, but a missing  one
Regards
claudio

**Comment by mart-e** [comment]
Nevertheless, it is a feature.
I am sorry but if we backport changes like that, we introduce the risk of regressions (which is not acceptable). We release new versions every year that, hopefully, is more complete than the previous one.

In stable versions, we fix bugs but do not change the behaviour of the system.

Regards
