### ISSUE TITLE
[Wishlist] Ability to expand all records in treeview in one click

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22047]
Impacted versions: All

Steps to reproduce: Go to a treeview which has grouped lines and try to unfold the times. You'll have to do this line by line. A good example of this can be found in V9 under inventory > Reports > Inventory valuation:
![image](https://user-images.githubusercontent.com/6352350/34611116-73d290a6-f224-11e7-9d30-0b523bba97ab.png)
If you want to unfold there is no option to unfold all lines, only to do it one line at a time. Imagine that you want to have every line unfolded - you'll be up for a good job.
The problem because bigger and more dramatical if you have 3.000+ lines here. Every unfold triggers framework functions which will result in a locking view that takes seconds (or minutes depending on the amount of records) to unfold.

If I would want to unfold all the items and export them I would be up for quite a challenge as an enduser.

Current behavior: There is no good and easy way to unfold all the lines at once.

Expected behavior: There is an 'Unfold all' option to unfold all records at once.

**Comment by Yenthe666** [comment]
@ged-odoo: I believe this would be a great addition to build for your team?
@wtaferner: for your interest.

**Comment by pedrobaeza** [comment]
This module was made for that: https://github.com/OCA/web/tree/8.0/web_group_expand, but not migrated yet.

**Comment by Yenthe666** [comment]
@pedrobaeza neat - thanks for the link! Nevertheless, wouldn't it be great to have it by default in Odoo?

**Comment by pedrobaeza** [comment]
Yeah, indeed, but the good thing is that you can always complement vanilla Odoo with OCA modules for having a great deployment on current versions. And now with new v11 JS architecture, is even easier!

**Comment by Yenthe666** [comment]
Indeed, something that we'll probably start doing more in the future. 👍
