### ISSUE TITLE
[FUNCTIONAL] Procurements in the context of active inventory management

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22041]
I was just playing around in demo.odoo.com and did realize that the request procurement on the product is not available anymore.
How the use case, that the inventory person goes through the inventory and requests a procurement (where no automatic rule is set) is managed from now on?

**Comment by blaggacao** [comment]
Especially when doing manual resupply of another warehouse, without beeing able to rely on rules, this becomes a potentially complicated situation, as the 2 necesary automatic moves (delivery to intercompany location, and reception from intercompany location are not created automatically...)

**Comment by blaggacao** [comment]
I tried to do a move, 
`WH1 <- Intercompany transit`
but as in a move you cannot specify the procurement method, and it will be "take from stock", so the other move will not be created...

@jco-odoo Not sure if this is to be alarmed... :wink:

**Comment by blaggacao** [comment]
For an manual / active inventory management (let's say reordering rules would change that frequently so they are just impractical and stock is managed "at sight" for certain products), this change might be critical / blocking, provided I did get it right.
Otherwise you would assume, that the inventory guy can anticipate routes (bought, resupplied, manufactured), in order to trigger those actions himself. This is not only inefficient and impractical, but also close to irrealistic, because make or buy decisions are usually done/changed at a higher management level, so central configuration (routes) is a good thing to do.

**Comment by jco-odoo** [comment]
You could make a planned transfer (settings of the picking type vignette) and add the procure_method in the view of the moves.  It is true that the request procurement wizard disappeared, but the mechanism stays.  So, it is not that difficult to create a wizard (or even a stored object) with all the information and pass its values to the function that will create all the moves/purchases/mos as before.

**Comment by blaggacao** [comment]
Thanks a lot! I'll figure out a practical solution when I migrate then! And as usually, will share it with you! :smile:

**Comment by Yenthe666** [comment]
@blaggacao I guess you've got the answer you need & that this can be closed? 
@jco-odoo thanks a lot for the terrific response rate!

**Comment by blaggacao** [comment]
I would prefer to keep this open, as it is a functional blocker in some cases... I'll rename and follow up once I have a solution. The ball is in my hands.

**Comment by Yenthe666** [comment]
Okay, sounds good!

**Comment by blaggacao** [comment]
@jco-odoo Yea, thank you Josse! I'll try to keep the quality as high as possible so your commitment will be worthwhile...

**Comment by rousseldenis** [comment]
@rvalyi You could see also at https://github.com/OCA/stock-logistics-warehouse/pull/352

**Comment by jbeficent** [comment]
@blaggacao @rvalyi the modules 'stock_request' and 'stock_request_purchase' have just been merged in OCA. See https://github.com/OCA/stock-logistics-warehouse/tree/11.0.

I created them to satisfy precisely this need. And IMHO the quality of the modules is good.

**Comment by jbeficent** [comment]
@jco-odoo If you like the idea we could propose them to odoo core!

**Comment by Yenthe666** [comment]
@sle-odoo this might be of interest for you too.

**Comment by sle-odoo** [comment]
@Yenthe666 at the moment i just create a planned picking and add the move_type in the view to chose the procure_method. I don't know if we want the "request procurement" feature back, @lap-odoo for a feedback.

**Comment by sle-odoo** [comment]
@blaggacao we plan to bring back the feature in master, this task is now in the pipe. right now i would prefer to make a simple wizard that asks for the warehouse, location and quantity. confirming the wizard would create the picking + the move and confirm it. should be quite simple. we'll keep you updated. thanks for the tip on this topic

**Comment by blaggacao** [comment]
@sle-odoo I think choosing the `procure method` in regular pickings with probably a little wizard wrapper on the products is an elegant solution to keep the somewhat "difficult" procurement concept out of sight, while providing the same functionality. I think this is a good direction to explore and does provide exactly the same functionality. Procurement as it was should probably not come back, because its general uid=1 nature has brought it's own set of problems difficult to solve (eg. not knowing in one warehouse who issued something in the other and stuff)

**Comment by jbeficent** [comment]
@sle-odoo Consider that the requesting person may not necessary be a stock user or stock manager. I find that the pattern of requesting entity vs servicing entity being different roles is missing across odoo. 

For example, consider an R&D department that needs samples of product A. The person that needs a sample of the product is a lab guy, that has nothing to do with warehouse management. But he needs 10 units of product A.

IMHO this person should be able to ask for material to be brought to his place, and does not necessarily need to be a stock user (he himself does not deal with anything that has to do with warehouse).

Given that, I understand that you try to make the system easy to use as much as possible. But just consider that this pattern exists in companies.

**Comment by sle-odoo** [comment]
Hi,
We have an internal task with the id 47938
Once we'll have worked on it and have something to show, i'll make a comment on this issue to inform you guys.

Regards

**Comment by sle-odoo** [comment]
see 438006b56d66175923c3795c666f07245358ade3
