### ISSUE TITLE
[11] Odoo Client Error on updating Many2Many via Onchange

### ISSUE THREAD

**Issue by ges7** [odoo/odoo#22050]
Impacted versions: 11

Steps to reproduce: Make an onchange on any field of a model, then from the onchange return values like { 'value' : { 'order_line': (6, 0, [ids]) } }. One of the ids is a record that was created via model.new(), so the thing works on a not created record (NewId).

Current behavior: Line gets added fine to the Many2Many, the widget updates fine, and even saves fine. But if you try to click on the line that was just added, you get an error that comes from the fact that the "value" field is empty in "this" in the interface.

Expected behavior: When the line added by the onchange is clicked right after being inserted and before being saved, it displays the view form as it normally does for the other lines.

Video/Screenshot link (optional): 
![issue_github_x2many](https://user-images.githubusercontent.com/1526152/34613693-eff55498-f22e-11e7-8fc2-96c94cd3c362.gif)

edit : the full error of the client :

Uncaught TypeError: Cannot read property 'count' of undefined
http://127.0.0.1:8071/web/content/29208-c6e6f6a/web.assets_backend.js:1048

TypeError: Cannot read property 'count' of undefined
    at Class._renderControlPanel (http://127.0.0.1:8071/web/content/29208-c6e6f6a/web.assets_backend.js:1048:127)
    at Class.start (http://127.0.0.1:8071/web/content/29208-c6e6f6a/web.assets_backend.js:1041:107)
    at Class.prototype.(anonymous function) [as start] (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:3811:488)
    at Array.<anonymous> (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:3932:963)
    at Array.<anonymous> (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:802:681)
    at fire (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:796:299)
    at Object.add [as done] (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:797:467)
    at Array.<anonymous> (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:802:649)
    at Function.each (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:625:767)
    at Object.<anonymous> (http://127.0.0.1:8071/web/content/29191-e149c9d/web.assets_common.js:802:560)

**Comment by Yenthe666** [comment]
@ged-odoo related to the new views?

**Comment by ged-odoo** [comment]
@Yenthe666 probably the new views.  We do not have many bugs lately, it is finally getting quite stable (yay for tests), but there may still be some bugs, obviously.

**Comment by Yenthe666** [comment]
That is good to hear and it was all worth it! Could you have somebody have a look?

**Comment by ges7** [comment]
Would be nice, my client is not happy with this :(. I tried fixing the issue myself but I couldn't figure out why the datapoint seems to not get fetched in the view after the onchange... I don't have a lot of time to allow to this issue in my company.

**Comment by ged-odoo** [comment]
@ges7 this issue is not forgotten... this is the kind of bug I consider high priority. However, I was stuck with some other issues/tricky bugfixes.  But this one will be done someday

**Comment by aab-odoo** [comment]
Hello @ges7,

Thanks for reporting this issue. However, i doubt that you obtained this result with a command 6, as this command is currently not supported in onchanges. I just tried, and it basically produces nothing (like if there were no onchange).

I'll do a fix so that commands 6 are supported.

That being said, i'm interested in your usecase as it seems that you spotted another bug. Could you precisely explain the onchange you defined (or even copy paste the python code).

Regards

**Comment by ges7** [comment]
Hello @aab-odoo,

Sure, here is the code of the onchange : 

```
class SaleOrder(models.Model):
    _inherit = 'sale.order'

    @api.onchange('order_line')
    def onchange_order_line_decond(self):
        logfunc()
        # for rec in self:

        self.ensure_one()

        product_obj = self.env['product.product']
        soline_obj = self.env['sale.order.line']
        decond_product = product_obj.search([('name', '=', 'Déconditionnement')])

        if not decond_product:
            msg = """ Il n'existe aucun produit nommé "Déconditionnement" en base.
            Le mécanisme d'ajout de ligne de déconditionnement ne peut pas fonctionner.
            """
            # raise UserError(msg)
            # return {'warning' : {'title': 'Erreur Déconditionnement', 'message': msg }}
            logger.warning(msg)
            return

        # si déjà une ligne de déconditionnement, ne rien faire
        line_there = [line for line in self.order_line \
            if line.product_id.id == decond_product.id]

        if line_there:
            logger.critical('already a decond line : setting decond_added for all lines & returning')
            for line in self.order_line:
                line.decond_added = True
            return

        add_decond = False
        for line in self.order_line:
            qty = line.product_uom_qty
            nb_par_colis = line.product_id.nb_par_colis
            logger.critical('nb_par_colis : %s' % nb_par_colis)
            if not nb_par_colis:
                continue
            if ((qty % nb_par_colis) != 0 ) and not line.decond_added  :
                add_decond = True
                break

        # if we decide to add a deconditionnement line,
        # we mark all the present lines as decond_added = True
        # this is for when we remove a line that is a deconditionnement line,
        # it doesnt get re-added instantly...
        if add_decond:
            for line in self.order_line:
                line.decond_added = True

        if not add_decond:
            return

        values = {
            # 'name': 'déconditionnement',
            'name': decond_product.name,
            'product_id': decond_product.id,
            'price_unit': decond_product.lst_price,
            'product_uom_qty': 1,
            'product_uom': decond_product.uom_id.id,
            'is_decond': True,
        }

        line_ids = [x.id for x in self.order_line]

        # https://www.odoo.com/forum/help-1/question/create-new-many2one-records-in-api-onchange-method-2nd-try-70212
        # Jario Llopis answer
        nl = soline_obj.new(values)
        line_ids.append(nl.id)

        return { 'value': {
            # 'partner_id': 42,
            # 'note': 'I was changed automatically!',
            'order_line': [
                (6, 0, line_ids)
                # line_ids
                # (0, 0, values),
                #(1, 13, {'product_id': decond_product.id, 'product_uom_qty': 10}),
                #(1, 14, {'discount': 15, 'quantity': 34}),
            ]
        } }
```

Basically, on a new record (not saved) or on an existing one, this onchange adds a line of "deconditioning" if the quantity on a sale.order.line is not a multiple of its "number per package". The bug arises if we try to click on that newly added line before saving the record.

**Comment by aab-odoo** [comment]
Hello,

Ok I now understand what's happening. The problem occurs when the onchange returns a command 0 with some field values, and when there is in the one2many (dialog) form view a one2many or many2many field, say F, that isn't in the one2many list view, and when no value is given for F in the command 0 returned by the onchange.

I'll fix this issue as soon as I can.

Regards.

**Comment by ged-odoo** [comment]
that's a nice explanation @aab-odoo !

**Comment by AmrDataHolic** [comment]
I had This Issue. happened to me after installing an addon.
I tried a lot of solutions. some on DataBase, some with coding.
Nothing solve it but one solution.....
I removed the last installed addon folder from my Server Folder on the path :  
C:\Program Files (x86)\Odoo 11.0\server\odoo\addons

that solved the issue totally
