### ISSUE TITLE
[11.0] Invoicing App should change its name when accounting module is installed

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22054]
#### Impacted versions:
11.0

#### Steps to reproduce:
Install Invoicing Module
Then install Accounting Module

#### Current behavior:
The App still shows "Invoicing" even after the accounting module is installed.

#### Expected behavior:
Change the App name to Accounting when accounting is installed.

cc: @qdp-odoo @mart-e

**Comment by gustavovalverde** [comment]
This is mainly because companies that work with the accounting app (and v10 or older clients) find it very confusing that the Accounting functionalities are inside the "Invoicing" App

**Comment by celm1990** [comment]
I agree

**Comment by Yenthe666** [comment]
Hmm, it can get confusing I guess. This call should be up to @mart-e.

**Comment by mart-e** [comment]
Hmm could you specify what modules you install exactly (technical names) in which order?
I tested and the name of the menu changed.
(but IMHO, I find it more confusing to rename menus and would like to avoid it in the future ;-))

**Comment by gustavovalverde** [comment]
@mart-e It's still saying Facturar (Invoicing) after installing `account_accountant`

**Comment by mart-e** [comment]
@gustavovalverde ok, so you are not working in English! Indeed, the term does not change then.

This is one of the reason why I don't think it is a good idea to rename the menus :  it is not possible to efficiently translate a record that you rename with some module installation.

We chose to keep Invoicing as it is what most of the people will probably see (Invoicing is in CE).

**Comment by gustavovalverde** [comment]
@mart-e I can agree with you and the dynamic terms, it would also make it harder for translators having the same word in the same context.

Then, targeting the actual issue, in the Americas (aside from USA, where I don't have much experience) there's not an existing ERP use case without `account_accountant`. Maybe for Spanish speakers the best way would be to consider this translation as Accounting and not Invoicing. 

As es_ES is the main language for Spanish speakers I wouldn't like to make a decision which harms Spains (which commonly have different use cases than LATAM) cc: @pedrobaeza

**Comment by edsersolis** [comment]
Invoicing is such a small term for the Accounting module. And I can already hear customers complaining for it, and yes, I know it's just a word but we must keep attention to details. SOTA.

USA, Canada and LATAM use the concept of Accounting, these will also complain if you just call it Invoicing.

**Comment by gustavovalverde** [comment]
Just a follow-up here @mart-e; as this is still happening in master (v12).

**Comment by mart-e** [comment]
@gustavovalverde and it will probably still happen in v13. My proposal was to name it "accounting" all the time but it was rejected...

**Comment by gustavovalverde** [comment]
@mart-e Thanks for the feedback. I won't keep this one open and just talk it with the product owners in charge of accounting.

@pedrobaeza The fastest workaround is changing this in transifex for es_ES; I'll be doing this.

**Comment by pedrobaeza** [comment]
OK for me. It's acceptable.
