### ISSUE TITLE
[11] abstract_field's _setValue isn't properly handling exceptions.

### ISSUE THREAD

**Issue by sadasant** [odoo/odoo#22065]
Impacted versions: 11.0

Steps to reproduce: Build a new field with a new formatType, but don't extend `field_utils.parse`.

Current behavior: When saving the new field, the value doesn't get sent to the server, but the form behaves as if it succeeded (it doesn't break or shows an error).

Expected behavior: Having a new field with a new formatType but not having `field_utils.parse` causes an exception that should be visible either in the UI of the application, or at least in the developers console of the browser.

The issue happens because [this try catch](https://github.com/odoo/odoo/blob/e918271f7600d9f77dc6631e48814f0daf951ad8/addons/web/static/src/js/fields/abstract_field.js#L416-L423) is not properly handling exceptions.

Perhaps setting `_isValid` to false and triggering up `is_dirty` and doing `Deferred().reject()` should be enough, but it's not announcing the broken behavior still. `_setValue` is being called by a large number of functions which probably don't have the means to react to these properties changed during the exception.

**Comment by Yenthe666** [comment]
Hi @sadasant,

Thank you for your report.
@qsm-odoo or @ged-odoo could one of you two have a look at this JS suggestion please?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
@sadasant good catch. this is definitely a problem we need to look at.

**Comment by sadasant** [comment]
@Yenthe666 @ged-odoo heeey :) thanks for the replies! Have a wonderful day!
