### ISSUE TITLE
[11.0][10.0] Field job_id is in the module hr_recruitment but it should be in hr

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22069]
### Impacted versions:
11.0 and 10.0, maybe others.

### Steps to reproduce:
Make a mass employees upload
Try to upload their job position (`job_id`)

### Current behavior:
Job positions can't be created from import as this menu is just available in `hr_recruitment
`
### Expected behavior:
The job positions view, for importing, should be (also?) available with just the `hr` module, as most employee information is handle in this module without the need of hr_recruitment or its related functionalities.

**P.D.:** This might actually be a design issue.

**Comment by Yenthe666** [comment]
@mart-e can you have a look and see what you think about this?

**Comment by mart-e** [comment]
Hello,

Isn't it the same than account vs account_accountant? The hr module set all the basic models for underlying logic and hr_recruitment handles the part with the job positions.
It looks like it was always the case (I stopped to search when was in 2012)

**Comment by mart-e** [comment]
I have reported the feedback to see if we can improve that. If agree, it will land in master.

**Comment by gustavovalverde** [comment]
@mart-e is there an update on this one. Just to know if this keeps open or gets closed.

**Comment by mart-e** [comment]
I checked the state of the feedback. It was was merged in a bigger refactoring task which was then changed to a minor change at #23742
@tivisse could you check this issue. It was reported in task 47832 and got lost lost in oblivion.

**Comment by gustavovalverde** [comment]
@tivisse just a ping here, as this is still true in v12 and master. Right now there's no way in community to import/export **job_ids**.

**Comment by gustavovalverde** [comment]
cc: @tivisse

**Comment by tivisse** [comment]
Hi. This makes sense. Thanks for the feedback.

I'm gonna create an internal task about that. This should be done soon.

Thanks, 

Yannick.
