### ISSUE TITLE
[10.0] [11.0] point_of_sale: Some terms are not translatable

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22062]
Impacted versions:
10.0 11.0

Steps to reproduce:
Install point_of_sale
Go to sessions

Current behavior:
![image](https://user-images.githubusercontent.com/16890942/34642366-2d2e1098-f2e8-11e7-8f4a-71be794cd930.png)

Term does not appear in Transifex

Expected behavior:
Translatable term

**Comment by gustavovalverde** [comment]
cc: @mart-e

**Comment by Yenthe666** [comment]
@mart-e for your interest - this is coming from this line:
https://github.com/odoo/odoo/blob/25943696ea00b140ea19de1c6ee6a42d97d8e2f7/addons/point_of_sale/views/point_of_sale_dashboard.xml#L74

It doesn't seem to be translatable indeed.

Regards,
Yenthe

**Comment by gustavovalverde** [comment]
Thanks for the fix @mart-e. Is this also an issue or is it just me? https://github.com/odoo/odoo/issues/22062#issuecomment-355763683

**Comment by mart-e** [comment]
@gustavovalverde where do you see that? I just see "Punto de Venta" which is from here https://www.transifex.com/odoo/odoo-11/translate/#es/point_of_sale/119297951?qt=Punto%20de%20Venta

**Comment by gustavovalverde** [comment]
@mart-e, indeed. But as you can see in the image it actually says "Terminal Punto de Venta", it should be "Punto de Venta", as it says in Transifex.
![image](https://user-images.githubusercontent.com/16890942/34717829-c4495040-f50a-11e7-86f2-38fa3d89afb5.png)

**Comment by mart-e** [comment]
Not in the latest v11 on the runbot
![screenshot-2018-1-9 punto de venta - odoo](https://user-images.githubusercontent.com/564822/34717990-468973f8-f535-11e7-906f-6c9a6c7ce69c.png)

Make sure your translations are up to date

**Comment by Yenthe666** [comment]
@gustavovalverde those are probably old terms that are still saved in your local Odoo.
