### ISSUE TITLE
[10.0] [11.0] The field available_in_pos should be set to False if sale_ok is False

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22061]
### Impacted versions:
10.0 11.0

### Steps to reproduce:
With the point_of_sale module installed, create a New product (Product A) and remove the Salable option (`sale_ok` will be false), and save the product.

### Current behavior:
Product A will be available in the Point of Sale, as the `available_in_pos` is hidden in the product.template, but it's still set as `True`, but hidden.

This causes that on every product creation the user has to be aware to first remove the default True from 
the `available_in_pos` field, before setting `sale_ok` as False.

### Expected behavior:
If a product is not Salable, do not leave the `available_in_pos` field set as `True`, as this causes a lot of products to be wrongly shown in the PoS.

This is even a _default_ behavior, as every product comes with `sale_ok` set as `True` on creation, which is fine but also causes the above wrong behavior.

**Comment by pimodoo** [comment]
Hello, thanks for your feedback, we'll fix it as soon as possible

**Comment by Yenthe666** [comment]
@pimodoo is there any update on this one?

**Comment by gustavovalverde** [comment]
OPW 1844188

**Comment by gustavovalverde** [comment]
Just to consider, based on the OPW recommendation.

A product without `sale_ok` set to False, and `available_in_pos` to True will mainly cause problem in this places:

When adding a POS order line from the backend:
https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L929

When using a discount product:
https://github.com/odoo/odoo/blob/11.0/addons/pos_discount/models/pos_config.py#L13
https://github.com/odoo/odoo/blob/11.0/addons/pos_discount/models/pos_config.py#L20

When invoicing products from POS:
https://github.com/odoo/odoo/blob/11.0/addons/account/views/account_invoice_view.xml#L414

Inside the POS:
https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/static/src/js/models.js#L354

**Comment by pedrobaeza** [comment]
Well, you can argue that in the issue. It's not the first time they overlook something, but giving the proper arguments, they rectify.

**Comment by Yenthe666** [comment]
@pedrobaeza I guess you have better luck then us then. ;)
I can relate a bit to @gustavovalverde though, generally a lot of responses try to get to a closure or denied very quickly. Most of our tickets have the "this will be improved at some point" or "we do not consider this a bug" or  "you can use x to your advantage by doing Y and Z".

I think it has to do with the amount of issues they have to solve a day and response / closure times. Perhaps there is a bit too much pressure there.

**Comment by pimodoo** [comment]
FYI:
Hello,

Indeed you were right, while in v10.0 the feature works, in v11.0 opening a POS session crashes with the "Can be Sold" False and "Available in POS" True.

We'll fix it in v10.0, it'll be forward-ported to later versions. The fix will likely be the addition of an onchange on the "Can be Sold" field that will set the "Available in POS" to the same value.

Thanks for reporting the issue (and insisting ^^).

Best Regards,

**Comment by Yenthe666** [comment]
@pimodoo now that is a great response. Thanks a lot for looking into it again and deciding on fixing it!
