### ISSUE TITLE
[11.0] Product Category not translating on product.template

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22060]
### Impacted versions:
11.0

### Steps to reproduce:
Create a new Product

### Current behavior:
It shows "All" as the default category
![image](https://user-images.githubusercontent.com/16890942/34640988-77db4a9e-f2d3-11e7-98e2-36cf6f351da4.png)

But the category name is Todos (in spanish, the only installed language in this case)

![image](https://user-images.githubusercontent.com/16890942/34641005-b6c2973a-f2d3-11e7-9acb-48b5b0c5ce41.png)

### Expected behavior:
It should show the translated term in the product.template

**Comment by gustavovalverde** [comment]
This might be one for you @mart-e

**Comment by mart-e** [comment]
Yes, you don't show the same field on both screen. In the first it is the hierarchy of categories

![screenshot-2018-1-8 e-com10 apple draadloos toetsenbord - odoo](https://user-images.githubusercontent.com/564822/34675248-4b3c30f4-f489-11e7-8ac6-aade9bf9e063.png)

and the second is the name of the category

![screenshot-2018-1-8 all saleable physical - odoo](https://user-images.githubusercontent.com/564822/34675233-433fba38-f489-11e7-95e0-ae04ae229692.png)

The hierarchy is computed and stored. So I am sorry but it is not possible to translate this part.
One solution would be not to store the complete name but it means we can no longer search or sort on it...

**Comment by intero-chz** [comment]
What about recomputing the field after translation change?

**Comment by mart-e** [comment]
No, otherwise, you would store a translated value. You store the computed result (here the list of parent categories), and use it. But if you store the translated result, other users will see it in the language of user that executed the computation.
We have the same issue with stock location I think.

**Comment by gustavovalverde** [comment]
So a "workaround" would be not to use the premade categories that comes with `base`, but instead use others created from scratch?

**Comment by mart-e** [comment]
The solution would be not to store it but implies restoring the beautiful methods @tde-banana-odoo removed at b1a8cf2e270195516b2729f4c88a3db0f01b7811...
Creating new categories in mono-language would do it too

**Comment by RoelAdriaans** [comment]
We have this issue with client, raised enterprise ticket; 1863536.

**Comment by pedrobaeza** [comment]
Quoting @mart-e from a duplicated issue, this is a wonderful summary:

> This is not linked to the display_name but a limitation of the framework, you can't have, at the same time, a field that is
> *    translatable
> *    computed
> *    stored
> *    You must choose two.

**Comment by robinhli** [comment]
I tried this, and it works. but don't know if there are any other issue.

    _rec_name = 'display_complete_name'

    @api.depends('name', 'parent_id.complete_name')
    def _compute_display_complete_name(self):
        for category in self:
            if category.parent_id:
                category.display_complete_name = '%s / %s' % (category.parent_id.display_complete_name, self.env['ir.translation'].search([('name', '=', 'product.category,name'), ('res_id', '=', category.id), ('lang', '=', self.env.user.lang)]).value)
            else:
                # category.complete_name = category.name
                category.display_complete_name = self.env['ir.translation'].search([('name', '=', 'product.category,name'), ('res_id', '=', category.id), ('lang', '=', self.env.user.lang)]).value

**Comment by jeroen7s** [comment]
easier fix: _rec_name = 'name'
works if you don't use subcategories

**Comment by mart-e** [comment]
Closing as explained at https://github.com/odoo/odoo/issues/23867#issuecomment-405267037
In 13.0, at 322618a69c8870835e0e4ea785b7268a16d14f67, we took the solution of not translating the categories anymore.

**Comment by rousseldenis** [comment]
@mart-e Even if it solves display inconsistencies, this solution would not apply to installs in a multi language company. You predicate that everybody speak the same language, which is not the reality. Shouldn't have been the moment to make a better solution ? Or for v14... :smile:

**Comment by jeroen7s** [comment]
@mart-e there are ways around this, like the one I mentioned above if you don't need to see the full parent category structure in the categories display name

Otherwise you could alter the _rec_name to be a computed value of all translated values of all categories, and make this field Not stored like the regular default_name is

**Comment by lmignon** [comment]
@mart-e The decision taken in 13.0 is a sad news.. This decision remove an essential functionality for some of our customers. Is Odoo ready to pay language courses to customer's employees so they can still do their job with part of the information no available into their language :smirk: ? Why didn't you restore code removed at b1a8cf2... ?
For customers we are migrating to v13 it's a requirement to keep the category name translatable and it's hard to explain that they have to pay to have this functionality back into Odoo.

**Comment by rousseldenis** [comment]
@mart-e Any news about a new implementation ?

**Comment by mart-e** [comment]
@rousseldenis the question hasn't changed : which one do we remove from translate, compute and stored ? We haven't figured out a solution to make the three work together, sorry.

**Comment by Cedric-Pigeon** [comment]
@mart-e This is insane. How can we explain that to customers? I agree on the technical complexity but this stuff is a basic need. Could you please reconsider?

**Comment by igallart** [comment]
> @mart-e This is insane. How can we explain that to customers? I agree on the technical complexity but this stuff is a basic need. Could you please reconsider?

We also have problems with customers in this issue. In some cases we have chosen to add the deleted commit https://github.com/odoo/odoo/commit/b1a8cf2e270195516b2729f4c88a3db0f01b7811. Personally, I think it was a bad decision to remove the functionality that was there.
