### ISSUE TITLE
Missing selection for two-step PO validation in Odoo 11

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#22064]
Impacted versions: 11.0

Steps to reproduce: 
1. Install **Purchase Management**
2. Go to **General Settings**
3. Configure company data

Current behavior:
There is only Order Approval checkbox under Purchases > Cofiguration > Settings. 

Expected behavior:
There needs to be a selection for levels of PO validation: one_step and two_step. I can't seem to get the instructions here: [https://www.odoo.com/documentation/user/11.0/purchase/purchases/rfq/approvals.html](https://www.odoo.com/documentation/user/11.0/purchase/purchases/rfq/approvals.html)

**Comment by Yenthe666** [comment]
@mart-e the "configure your company" part does seem to have moved in V11. Perhaps we need a little doc update here too?

**Comment by mart-e** [comment]
Thanks, we will fix the doc  at odoo/documentation-user#259 !
Closing as an issue of doc, not of Odoo

**Comment by macdelacruz** [comment]
Where is that Levels of Approval radio buttons in Community Edition?

![selection_099](https://user-images.githubusercontent.com/13848476/34906558-cbfa2b2e-f867-11e7-8708-432edf71206d.png)
