### ISSUE TITLE
Exception: bus.Bus unavailable in odoo 10

### ISSUE THREAD

**Issue by shajal8015** [odoo/odoo#22076]
Dear All, I have facing problem when workers >0: 
I am using odoo 10 and ubuntu 16.04 with nginx 
The following error display: 
------------------------------------------
return self.method(*args, **kw)

File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python2.7/dist-packages/openerp/addons/bus/controllers/main.py", line 34, in poll
raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
------------------------------------------------------------
My nginx configuration
vim /etc/nginx/site-available/odoo.conf
--------------------------------------------------------
upstream odooweb {
server 127.0.0.1:8069 weight=1 fail_timeout=300s; 
} 
upstream odooweb-im { 
server 127.0.0.1:8072 weight=1 fail_timeout=300s; 
} 
server { 
# server port and name 
listen 80; 
server_name 127.0.0.1:8069; 
# Specifies the maximum accepted body size of a client request, 
# as indicated by the request header Content-Length. 
client_max_body_size 200m; 
#log files 
access_log /var/log/nginx/odoo-access.log; 
error_log /var/log/nginx/odoo-error.log; 
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600; 
keepalive_timeout	600;
gzip on;
gzip_disable "msie6";
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss application/rss+xml text/javascript image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype image/bmp image/png image/gif image/jpeg image/jpg;
# increase proxy buffer to handle some odoo web requests 
proxy_buffers 16 64k;
proxy_buffer_size 128k;
location / { 
proxy_pass http://127.0.0.1:8069; 
# force timeouts if the backend dies proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
# set headers
proxy_set_header Host $host; 
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto http;
# by default, do not forward anything 
proxy_redirect off; }

location /longpolling { 
proxy_pass http://127.0.0.1:8072;
} 
# cache some static data in memory for 60mins. 
# under heavy load this should relieve stress on the odoo web interface a bit. 
location ~* /web/static/ { 
proxy_cache_valid 200 60m; 
proxy_buffering on;
expires 864000;
proxy_pass http://127.0.0.1:8069; 
}
}
------------------------------------------------------
and my odoo.conf file is
----------------------------------
/etc/odoo-server.conf
-------------------------------------
[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = saimon
db_password = False
db_maxconn = 500
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/odoo-server/odoo/addons,/odoo/odoo-server/addons
log-level=debug_rpc
workers = 5
longpolling_port = 8072
xmlrpc_port = 8069
proxy_mode = True
max_cron_threads = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1

------------------------------------------
Where is wrong? I anybody can help? then it will very much helpful for me.....
Thanks

**Comment by Yenthe666** [comment]
Hi @shajal8015,

Please ask this question on the official help forums (help.odoo.com) where plenty of people can help you.
The Github tracker is for bugs in the official code, it isn't used for asking questions about deployment.
You might also want to look at the deployment docs at https://www.odoo.com/documentation/11.0/setup/deploy.html

Regards,
Yenthe
