### ISSUE TITLE
Suggestion: When changing a task's project, the stage should not change if it is one of the possible stages of that project

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#22082]
Impacted versions: 10.0 at least

Steps to reproduce:
1. In the general tasks Kanban view, group tasks by stage. Make sure more than one lane is visible
2. Add a new task in some lane that is not the leftmost lane. Make sure to use the +-menu associated with the lane.
3. A new task will be created, though it will not a have an associated project. You will need to change the project by opening the task's form view and editing it there.

Current behavior:
When the project is changed, the task's stage is automatically updated to be the "leftmost" stage possible for that project, even if the current stage is accepted in that project.

Expected behavior:
The task's stage should not change if it's current stage is one of the possible stages for that project.

This is clearly a wishlist item, and I don't expect this to change before version 12 at the earliest. Maybe @Yenthe666 can tell me if this is even the right place for something like this.

**Comment by Elkasitu** [comment]
Here is a counter-example to your request:

I have a task called "potential client 23555"

I have 2 project: pre-sales and sales

pre-sales have the stages "talk with client about custom features, custom features quotation, done"

sales have the stages "talk with client about his needed standard features, standard features quotation, done"

The task would first go through pre-sales until done, then it would be transferred to sales to go over all the stages and then set to done, if we introduced your change it would automatically go to done which, in this case, is not the intended behavior (not to mention it could potentially trigger an action that, for example, creates a Sales Order for the client.).

All this to say that different people/companies/workflows expect different behaviors, how do you define which of the two is the "right" or "best" behavior?

**Comment by aisopuro** [comment]
Good point @Elkasitu, you're right in that we mainly assume projects to be standardised, and we don't want to mov tasks from project to project, because it messes with the analytic accounting. You're right in that there isn't really any good way of determining which of our ways is "better" necessarily, so I think that it might just be better to forget about this.
