### ISSUE TITLE
[11.0] timesheet_grid: Unable to set not null on Column 'name' 

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#22097]
Impacted versions:
11.0
Steps to reproduce:
-Install timesheet_grid module
- Create some lines in the timesheet with null description
- Stop the instance and made -u all
Current behavior:
It triggers next error
![image](https://user-images.githubusercontent.com/10233975/34697794-5d1be09c-f49a-11e7-92f6-edb2e3811d85.png)

Expected behavior:
-Remove the requiere attribute from name field in account.analytic.line model definition Or be consisten in the module timesheet_grid
https://github.com/Vauxoo/enterprise/commit/b0894f19a3e5e4c55db937a67b843e6dd2f41ad4
-End the update process without erros

**Comment by jem-odoo** [comment]
Hello,

Thanks for reporting this issue. Unfortunately we can not modifying SQL contraint in stable version. We will try to do something about this, as I already experienced this error.
Thanks for reporting.

Note: internal odoo task #1839540

**Comment by hugho-ad** [comment]
@jem-odoo 

Can you Reopen this issue until the bug is fixed, please.

Regards!

**Comment by jem-odoo** [comment]
Landed in master enterprise at https://github.com/odoo/enterprise/commit/272eb08bb600d17013dcba140a84d8145b50b212
We can not do it for stable version, so it will be available for 12.0.

Regards

**Comment by Yenthe666** [comment]
@jem-odoo you made a typo. You have `Ajustment` instead of `Adjustment`

**Comment by jem-odoo** [comment]
Thanks @Yenthe666 . Typo fixed at https://github.com/odoo/enterprise/commit/296666a99d957a7be56437d4b59762aa31be8257

**Comment by Yenthe666** [comment]
Thanks a lot! 🎉
