### ISSUE TITLE
Sale Order PDF report Order lines changed Variant product name value not display in PDF

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#22101]
Impacted versions:
Version 9.0c (Community Edition) 

Steps to reproduce:
Create New Sale Order with order lines Product variant and save record.
Edit record and Change Product variant value to other variant and save.
Finally, Generate PDF report for this Sale Order.

Current behavior:
Changed Product variant should not reflected in PDF report, old value displayed.

Expected behavior:
Product variant changed value should be reflect in sale PDF report.

Video/Screenshot link (optional):

**Comment by fmdl** [comment]
I think it is a normal behavior, the field description is generate when you choose the product. That why when you change the name of the product, the description field doesn't change.

In the report, it is the field description (`name`) wich is printed. (You can change by `product_id.display_name`)

Regards

**Comment by prakashjain** [comment]
Ok let we check, Thanks for reply
And  also Noticed custom module name field set as readonly, so readonly field changes not affected in database. please if possible provide link to overwrite write method  to call on_change method and assign  name field value .

**Comment by Yenthe666** [comment]
Hi @prakashjain,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
