### ISSUE TITLE
Procurement (Buy) still "Running" after cancel related Receipts

### ISSUE THREAD

**Issue by webtekindo** [odoo/odoo#22102]
**Impacted versions:**

10.0 

**Steps to reproduce:**

- Create Stockable Product (route Buy)
- Create Reordering Min/Max = 1.0
- Run Reordering Rules
- Confirm PO
- Cancel Receipt (picking)

**Current behavior:**

The related procurement state is still "Running". If we try to cancel manually the procurement then we get the error "Can not cancel a procurement related to a purchase order. Please cancel the purchase order first.". But in the case we have many products in the PO and we already receive some of them, we of course don't want to cancel the PO. So it looks like to me that this procurement is stuck forever in "Running" state. 

A simple use case, is we order (MTO) to supplier, and we don't need that product anymore, then we will cancel the product to supplier and cancel the reception of that product.

**Expected behavior:**

The order point procurement (OP/00..) state change to "Canceled" after "Cancel Receipts".

**Question**

I would like to know if this is a bug, or just a normal behavior and in this case what should be the workflow for my use case?

Thank you!

**Comment by Yenthe666** [comment]
@sle-odoo for interest of you.

**Comment by jco-odoo** [comment]
Could reproduce on runbot and made preliminary fix in a branch.  Might be better to use stock logic.

**Comment by webtekindo** [comment]
Thanks for the fix!

But shouldn't we add also the case where all moves are cancelled:

`
if all(move.state in ('cancel') for move in self.move_ids):
          self.write({'state': 'cancel'})
`

Probably the write shouldn't be in the _check methods, but I don't see another way?

**Comment by jco-odoo** [comment]
I think the _check method in the stock module should handle it. (super)

**Comment by webtekindo** [comment]
@api.multi
    def _check(self):
        """ Checking rules of type 'move': satisfied only if all related moves
        are done/cancel and if the requested quantity is moved. """
        if self.rule_id.action == 'move':
            # In case Phantom BoM splits only into procurements
            if not self.move_ids:
                return True
            move_all_done_or_cancel = all(move.state in ['done', 'cancel'] for move in self.move_ids)
            move_all_cancel = all(move.state == 'cancel' for move in self.move_ids)
            if not move_all_done_or_cancel:
                return False
            elif move_all_done_or_cancel and not move_all_cancel:
                return True
            else:
                self.message_post(body=_('All stock moves have been cancelled for this procurement.'))
                # TDE FIXME: strange that a check method actually modified the procurement...
                self.write({'state': 'cancel'})
                return False
        return super(ProcurementOrder, self)._check()


He handles it only in case **_self.rule_id.action == 'move'_** but not in case **_if self.purchase_line_id_**

Am I correct?

**Comment by jco-odoo** [comment]
I seems you are.  I will check it thoroughly tomorrow.

**Comment by jco-odoo** [comment]
I am even not sure, because if you cancel the picking and not the purchase order, you can still regenerate the picking from the purchase in theory.  And if you cancel the purchase, it will put it to exception/cancel.

**Comment by jco-odoo** [comment]
With the changes in v9 of course the shipping exception disappeared.

**Comment by jco-odoo** [comment]
I do not think there is a better solution here.
