### ISSUE TITLE
[11.0] A duplicated blog with the snippet Text-Image, when you change the image (double-click) the image is not saved

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#22109]
Impacted versions:
V11

Steps to reproduce:
1. Make sure you have a blog with a Text-Image snippet block. For our example we will change the image to a youtube video. Edit the image by double clicking on it and change the video url to: https://www.youtube.com/watch?v=EkbBFmIWoTE
2. Save this blog. Now we duplicate this blog by choosing the option in the top-right menu.
3. Edit the Text-Image again and put another video:  https://www.youtube.com/watch?v=da90PilMwSo  you can also choose an image.
4. Save the duplicated blog and you will see that the video or image or not saved.
5. If you edit the blog again, you will see that changed video is there. But when saved only the old video is visible.

Current behavior:
see above

Expected behavior:
The video / image should be changed after editing and saving.

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
This has been [fixed on 10.0](https://github.com/odoo/odoo/commit/bd00fa8dd1808478e70232dfcbd2f4b48f9e1cc8)
The fix will be forwardported to 11.0 in the upcoming days
Thank you for reporting the issue
