### ISSUE TITLE
[11.0] When you duplicate a blog, the view count is also copied.

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#22107]
Impacted versions:
V11

Steps to reproduce:
Go to the website editor and select an existing blog (if not there, create one first). Make sure there is already a view count. Duplicate the blog using the option on the top right. Once you save your copy, you will see that the blog has the same view count.

Current behavior:
see above

Expected behavior:
The view count should not be copied.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @yung-wang,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 11 and I can confirm that this is happening:
![image](https://user-images.githubusercontent.com/6352350/34713830-ba6268ba-f527-11e7-86db-ff93939ea2c9.png)
@JKE-be can you have a look when you have time? The counter shouldn't be copied.

Regards,
Yenthe

**Comment by JKE-be** [comment]
Just a copy=False missing (in v9 probably)

I try to take a look tomorrow ;)

**Comment by JKE-be** [comment]
Merged in v9 and will be forward ported to next versions asap. (some days expected)

**Comment by Yenthe666** [comment]
You can apply the fix at https://github.com/odoo/odoo/commit/eeea6e8667cfafc18e4966170d5dd6a6312aa40c or update your whole Odoo to fix this.

**Comment by yung-wang** [comment]
I applied the fix on our server and it works. Thanks for the quick fix.
