### ISSUE TITLE
[11.0] Unable to delete a Company, Warehouse, and Procurement Rule

### ISSUE THREAD

**Issue by bradrust** [odoo/odoo#22117]
Immediately after creating a new Company (and it's subsequently auto-created Warehouse, Routes, and Procurement Rule) you can't immediately delete it.   There have been no operations (moves, business logic, etc...) against this Company, Warehouse or related entities.

Impacted versions:

community 11.0 (11.0 branch from Jan 1)

Steps to reproduce:

Configure Sales, Point of Sale, Inventory, Invoicing
Configure Multi-Company
Enable Multi-Step Routes (although I did this just to try and find Procurement Rules for delete)
Settings->Companies->Create ... give it a Company Name and Save.
From the Companies listview, select the Company and try to Delete

Current behavior:

When deleting the newly created Company.

* Can't delete company because of warehouse FK ... [object with reference: Warehouse - stock.warehouse]
> ERROR oj odoo.sql_db: bad query: b'DELETE FROM res_company WHERE id IN (10)'
> ERROR: null value in column "company_id" violates not-null constraint 
> DETAIL:  Failing row contains (9, try to delete, t, null, 21, 68, 69, try t, one_step, ship_only, 70, 71, 72, 73, 34, 44, 45, 43, 42, 46, 28, 26, 27, null, 1, 2018-01-09 14:57:23.639954, 1, 2018-01-09 14:57:23.639954).
> CONTEXT:  SQL statement "UPDATE ONLY "public"."stock_warehouse" SET "company_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "company_id""

* Try to delete the Warehouse... fails because of FK ... [object with reference: Procurement Rule - procurement.rule]
> ERROR oj odoo.sql_db: bad query: b'DELETE FROM stock_warehouse WHERE id IN (9)'
> ERROR: null value in column "picking_type_id" violates not-null constraint
> DETAIL:  Failing row contains (35, try t: Input -> Output, f, propagate, null, move, 20, 10, 72, 70, 28, make_to_order, 20, null, 0, null, t, null, null, 1, 2018-01-09 14:57:23.639954, 1, 2018-01-09 14:57:23.639954). 
> CONTEXT:  SQL statement "UPDATE ONLY "public"."procurement_rule" SET "picking_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "picking_type_id""

* Try to delete the Route with a Procurement Rule called "Ship Only"
> ERROR oj odoo.sql_db: bad query: b'DELETE FROM stock_location_route WHERE id IN (27)'
> ERROR: update or delete on table "stock_location_route" violates foreign key constraint "stock_warehouse_delivery_route_id_fkey" on table "stock_warehouse"
> DETAIL:  Key (id)=(27) is still referenced from table "stock_warehouse".

* Try to delete Warehouse *after* you have removed the Procurement Rule from the "Ship Only" Route
> ERROR oj odoo.sql_db: bad query: b'DELETE FROM stock_warehouse WHERE id IN (9)'
> ERROR: null value in column "picking_type_id" violates not-null constraint
> DETAIL:  Failing row contains (35, try t: Input -> Output, f, propagate, null, move, 20, 10, 72, 70, 28, make_to_order, 20, null, 0, null, t, null, null, 1, 2018-01-09 14:57:23.639954, 1, 2018-01-09 14:57:23.639954).
> CONTEXT:  SQL statement "UPDATE ONLY "public"."procurement_rule" SET "picking_type_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "picking_type_id""

Expected behavior:

You should be able to delete a Company, Warehouse, Route, and associated database relationships if no operations have occurred.

Video/Screenshot link (optional):

**Comment by lap-odoo** [comment]
@bradrust : Hi, thanks for reporting this. We will make sure this will be possible in the future versions (unfortunately, it cannot be fixed on stable versions).

**Comment by bradrust** [comment]
Would you mind commenting on what you think the problem is?  If there are some constraints that I need to hack out of the way, at least I can do that locally verses codebase.  I guess what I mean is,... you mention making it in a future version so there must be some idea on what the constraint complexity might be.

Thanks

**Comment by sle-odoo** [comment]
At the moment the idea is that if you don't have any data then you could extend the unlink of the company to unlink all the models linked to the warehouse (route, picking type, location) then unlink the warehouse. this could work. @jir-odoo 

Note that we won't make the patch in stable versions, and when it's done it'll reference this issue.

**Comment by hartmannj** [comment]
We're at version 12 and this issue still exists. What would be the current way to solve this problem of deleting a company?

**Comment by EwetoyeIbrahim** [comment]
I guess the new contraints are:
* ```Model: Stock Rule (stock.rule), Field: Destination Location (location_id)``` when trying to delete the warehouse
* ```Model: Warehouse (stock.warehouse), Constraint: stock_warehouse_reception_route_id_fkey```: When trying to delete the receive routes.
* ```Model: Warehouse (stock.warehouse), Constraint: stock_warehouse_delivery_route_id_fkey```: When tring to delete the deliver routes.

**Comment by ramchippe** [comment]
This problem still exists in version 14 too

**Comment by caprarioa** [comment]
I am also experiencing this problem in v14. I have a completely fresh install and I added two companies. I tried deleting one of them but get an error:

> Model: Picking Type (stock.picking.type), Constraint: stock_picking_type_company_id_fkey

Seeing if I can just delete the entry and all dependencies in the database without breaking it.

**Comment by pedrobaeza** [comment]
Although not direct, you can remove a company deleting things in order:

- Stock rules
- Picking types
- Warehouse
- Company

**Comment by ramchippe** [comment]
I don't have any Stock rules, Picking types, Warehouses defined for the new company, still unable to delete

**Comment by pedrobaeza** [comment]
If you don't say the message you get, it's difficult to help you.

**Comment by pedrobaeza** [comment]
Maybe you have populated the chart of accounts and then you need to remove all that records.

**Comment by caprarioa** [comment]
@pedrobaeza 
> Although not direct, you can remove a company deleting things in order:
    Stock rules
    Picking types
    Warehouse
    Company

This worked perfectly for deleting a company that had no entries under it. I figured that this was the order and the tables but it was good to see some confirmation. Thanks!

**Comment by caprarioa** [comment]
Actually I found one more place to delete information of a company you want to delete.
> stock_location
If you do not delete the entries for the company here then it will still pop up in some drop down menus.

**Comment by mdazmir** [comment]
I'm new to Odoo v14 and I'm trying to delete one company with no entries but unable to find the three items below:
- Stock rules
- Picking types
- stock_location

Can someone please guide me on how find these?

**Comment by mdazmir** [comment]
> @pedrobaeza
> 
> > Although not direct, you can remove a company deleting things in order:
> > Stock rules
> > Picking types
> > Warehouse
> > Company
> 
> This worked perfectly for deleting a company that had no entries under it. I figured that this was the order and the tables but it was good to see some confirmation. Thanks!

Where did you find these items?

**Comment by caprarioa** [comment]
I found these using PGAdmin and accessing the Odoo database tables. 
In PGAdmin you find the tables in Schemas > public > Tables. You find the the companies in the res_company table. Get the id from res_company of the associated company you want to delete and match the associated rows in stock rule, picking type and warehouse tables.

**Comment by ttt-cj** [comment]
You should change the company to the one you want to delete, else you will only see records from the other company you wish to delete.
Hope that helps

**Comment by KigulaJesse** [comment]
This seemed to work for me, I changed the ondelete optional parameter to cascade, by default its restrict

class StockPicking(models.Model):
    _inherit = 'stock.picking.type'

    company_id = fields.Many2one(ondelete ="cascade")

class WareHouse(models.Model):
    _inherit = 'stock.warehouse'

    company_id = fields.Many2one(ondelete ="cascade")

class WareHouse(models.Model):
    _inherit = 'stock.rule'

    company_id = fields.Many2one(ondelete ="cascade")

**Comment by chjud** [comment]
> This seemed to work for me, I changed the ondelete optional parameter to cascade, by default its restrict
> 
> class StockPicking(models.Model): _inherit = 'stock.picking.type'
> 
> ```
> company_id = fields.Many2one(ondelete ="cascade")
> ```
> 
> class WareHouse(models.Model): _inherit = 'stock.warehouse'
> 
> ```
> company_id = fields.Many2one(ondelete ="cascade")
> ```
> 
> class WareHouse(models.Model): _inherit = 'stock.rule'
> 
> ```
> company_id = fields.Many2one(ondelete ="cascade")
> ```

Where exactly did you edit/change this? i found the parameters in the frontend, but not the exact .py file. Sorry, if I am not more precise, I am not too savvy on this.

**Comment by KigulaJesse** [comment]
In your custom module, under the models folder, create a new python file e.g stock_picking.py and then paste that code

**Comment by KigulaJesse** [comment]
> > This seemed to work for me, I changed the ondelete optional parameter to cascade, by default its restrict
> > class StockPicking(models.Model): _inherit = 'stock.picking.type'
> > ```
> > company_id = fields.Many2one(ondelete ="cascade")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > class WareHouse(models.Model): _inherit = 'stock.warehouse'
> > ```
> > company_id = fields.Many2one(ondelete ="cascade")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > class WareHouse(models.Model): _inherit = 'stock.rule'
> > ```
> > company_id = fields.Many2one(ondelete ="cascade")
> > ```
> 
> Where exactly did you edit/change this? i found the parameters in the frontend, but not the exact .py file. Sorry, if I am not more precise, I am not too savvy on this.


In your custom module, under the models folder, create a new python file e.g stock_picking.py and then paste that code

**Comment by chjud** [comment]
Thank you! (Even though I failed with these approaches due to lack of coding skills i guess... And the frontend doesn't allow a change to cascade)

But using PGAdmin as caprarioa suggested worked in the end. Only I also hat do detelet values in ir_property
