### ISSUE TITLE
[10.0][11.0]-DateTimes in Attachments

### ISSUE THREAD

**Issue by luistriana28** [odoo/odoo#22119]
Impacted versions: 10.0

Steps to reproduce: Accounting > Sales > Customer Invoices > Create > Save the Invoice > Add an Attachment > Click on attachments > Mouse over the Attachment the hour is 6 hours later than my pc hour.

Current behavior: It sums 7 hours to all the attachments uploads.

Expected behavior: Get the user timezone and upload the attachment as the user local time. 

Video/Screenshot link (optional):

![captura de pantalla 2018-01-09 a la s 11 39 15 2](https://user-images.githubusercontent.com/12242599/34734706-59c088ce-f532-11e7-962e-7318ee8bc258.png)

Even i configured the user preferences time zone

![captura de pantalla 2018-01-09 a la s 11 44 58 2](https://user-images.githubusercontent.com/12242599/34734748-88a7cac6-f532-11e7-927c-5beb70bb2c82.png)

**Comment by Elkasitu** [comment]
Hi,

This is normal behavior as attachment time is saved as *server* time, which for the runbot is UTC time.

**Comment by luistriana28** [comment]
Even tho my personal server is with UTC -6 ?? America/Mexico_City??

**Comment by Elkasitu** [comment]
[It would seem it is so](https://stackoverflow.com/questions/38801527/timezone-incorrect-in-odoo-log-file)

**Comment by luistriana28** [comment]
@Elkasitu 

The problem is with the writes in the database, your [articule](https://stackoverflow.com/questions/38801527/timezone-incorrect-in-odoo-log-file) works for the log files, im tryin'g to view the write datetimes in postgres.

Regards

**Comment by luistriana28** [comment]
@Yenthe666 @Elkasitu @nhomar @luistorresm @moylop260 @alan196 @pedrobaeza @ougc27 

Here is how it is not working the descriptions they gave me.

Here is my server time

![captura de pantalla 2018-01-26 a la s 10 00 16](https://user-images.githubusercontent.com/12242599/35448379-bed045ce-027f-11e8-8f12-c014cb6a1684.png)

Here is my postgresql.conf timezone 

![captura de pantalla 2018-01-26 a la s 10 01 25](https://user-images.githubusercontent.com/12242599/35448438-ec3ab210-027f-11e8-85b9-9278603c0618.png)

![captura de pantalla 2018-01-26 a la s 10 01 34](https://user-images.githubusercontent.com/12242599/35448441-f0b1e3b8-027f-11e8-845e-e43c000ba0e5.png)

Here is my user preferences config
![captura de pantalla 2018-01-26 a la s 10 02 51](https://user-images.githubusercontent.com/12242599/35448514-1d911b6a-0280-11e8-86f5-660500a06ec7.png)

Here is the example when i just upload an attachment
It is +6 hour from my local & server timezone

![captura de pantalla 2018-01-26 a la s 10 03 54 2](https://user-images.githubusercontent.com/12242599/35448631-712f9cd8-0280-11e8-9047-0bc892602ed0.png)

**Comment by luistriana28** [comment]
Here is the same exercise in runbot V11, even my administrator user doesn't has the America/Mexico_City timezone

![captura de pantalla 2018-01-26 a la s 10 19 27](https://user-images.githubusercontent.com/12242599/35449352-6abe2642-0282-11e8-8ecd-d1841dfac3e5.png)

Here is the attachment

![captura de pantalla 2018-01-26 a la s 10 17 18 2](https://user-images.githubusercontent.com/12242599/35449382-76be9bde-0282-11e8-9086-7f094ca7a0d9.png)

**Comment by luistriana28** [comment]
In runbot V11, there a problem too if you want to change the timezone,

here is the example

https://www.screencast.com/t/M6r1PbGcTT7

**Comment by kuro088** [comment]
It happens to me

**Comment by Elkasitu** [comment]
Ok thanks, I'll check this on monday 👍

**Comment by moylop260** [comment]
Hello @Elkasitu Do you have a news about this issue?

**Comment by Elkasitu** [comment]
Hi,

I've been busy with other stuff so I haven't had the time to investigate and probably won't be able to anytime soon, maybe some other dev will be able to take a look at it.

As always, PR welcome :)

**Comment by pedrobaeza** [comment]
As the attachment system has changed from v12, this problem doesn't seem to happen anymore, so closing.
