### ISSUE TITLE
[10.0] Issue with float_time widget 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22120]
Impacted versions: 10.0

Steps to reproduce: Tested on [Runbot](http://291817-10-0-1ad886.runbot13.odoo.com) --> Go to View Containing float field with float_time widget on it --> Create a new record and Save it. (Eg. Project --> Task)

Current behavior:
 Warning on Screen
`The record has been modified, your changes will be discarded. Do you want to proceed?`

Expected behavior: Warning should not be there.

Video/Screenshot link (optional): [ https://youtu.be/U0H-R7_jn1k](https://youtu.be/U0H-R7_jn1k)

**Comment by Yenthe666** [comment]
@ged-odoo could this be triggered at the JavaScript side?
@sswapnesh yep - that doesn't look right 😆

**Comment by Gorash** [comment]
Hi, it's a rounding error because there is no precision, you can add an option to take into account only 4 digits for example. This will fix the problem.

**Comment by Yenthe666** [comment]
So we can conclude that this will be improved?

**Comment by Gorash** [comment]
I did not test in v11.0. And we will not be n will not make a change in the form view.
This is not a blocking bug, if we have another ticket we will put a digit to 6 decimal by default on the widget.
