### ISSUE TITLE
[11.0][QUESTION] What does this line mean? Haven't found an answer nor code producing it

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22122]
Impacted versions: 11.0

Steps to reproduce: Don't know. Some journals have it others don't (seems that only sales and purchase).

Current behavior: A purple line is shown at the left of some journals in the accounting dashboard. Haven't found a condition in the code that creates it.

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/6585110/34749147-3cb868f2-f576-11e7-8586-a2e5f655ed0b.png)

**Comment by fmdl** [comment]
Dear

Just click on the menu and choose a color :-)

![image](https://user-images.githubusercontent.com/16716992/34761001-50cde134-f5e2-11e7-811e-1e4626df8570.png)

**Comment by Yenthe666** [comment]
Exactly - as answered by @fmdl (thanks for the answer!)

**Comment by edsersolis** [comment]
Thanks @fmdl was in front of our eyes :sweat_smile:
