### ISSUE TITLE
debian package removal shouldn't remove /var/lib/odoo

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#22138]
Impacted versions: 7.0 to 11.0

Steps to reproduce: `apt-get remove odoo`

Current behavior: ODOO_LIB_DIR (/var/lib/odoo) is deleted.

Expected behavior: ODOO_LIB_DIR (/var/lib/odoo) shouldn't be deleted, deletion is required only whith `apt-get purge odoo` command. /var/lib/ store important datas that are not expected to be deleted with package removal. /var/lib/odoo contains customized modules, filestore data, backups and so on. As a comparison /var/lib/postgresql is not deleted.

File `odoo/debian/postrm` contains errors because `remove` command does more than `purge` command : 

- currently, `remove` delete package, user, group and ODOO_LIB_DIR, while `purge` delete only package and ODOO_LIB_DIR ;
- instead, `remove` should delete package, user and group while `purge` should delete package, configuration file, user, group and ODOO_LIB_DIR.

**Comment by zeroheure** [comment]
RPM package should be checked also

**Comment by Yenthe666** [comment]
@d-fence package / system related.

**Comment by d-fence** [comment]
I agree.

**Comment by zeroheure** [comment]
Additionally, /usr/lib/python2.7/dist-packages/odoo/ is not purged. IMHO it should be removed in the 2 cases.
