### ISSUE TITLE
(Odoo 11) Scheduled actions don't work for sub domain multi database

### ISSUE THREAD

**Issue by wangsamas** [odoo/odoo#22130]
Impacted versions: 11

Steps to reproduce:
https://docs.bitnami.com/installer/apps/odoo/#how-to-find-the-database-credentials

@ installdir/apps/odoo/conf/odoo-server.conf 
  db_name = False
  dbfilter = ^%d$
  proxy_mode = True

@  installdir/apps/odoo/scripts/odoo_background_worker.sh 
  SCHEDULER_START="$ODOO_HOME/bin/odoo-bin -c $ODOO_HOME/conf/odoo.conf --max-cron-thread 1 --db-filter=^%d$"

@ installdir/apps/odoo/scripts/odoo_gevent.sh
  GEVENT_START="$ODOO_HOME/bin/odoo-bin gevent -c $ODOO_HOME/conf/odoo-server.conf --max-cron-thread 0 --db-filter=^%d$"

@ installdir/apps/odoo/conf/httpd-app.conf
   <Proxy *>
     Order deny,allow
     Allow from all
   </Proxy>
   ProxyRequests Off

Current behavior:
Scheduled actions don't work

Expected behavior:
Scheduled actions work

I follow instructions from bitnami to use multi database for subdomains
they all works but scheduled actions.

please help

**Comment by raestrada95** [comment]
I have the same problem. odoo 11 on google cloud.

**Comment by rwngallego** [comment]
@wangsamas @raestrada95  have you find a solution for this? I'm having the same exact problem

**Comment by gmontcru** [comment]
Do you find a solution? Same problem

**Comment by UnixedIT** [comment]
Same Problem, do you find the solution ?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, with the worker that runs cron (scheduled) tasks. See `max_cron_threads` variable.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by UnixedIT** [comment]
Any one find the solution? please let's know?
