### ISSUE TITLE
[11.0] Unlink generated timesheets when leave is set back to draft or refuse

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#22140]
Impacted versions:
11.0

Steps to reproduce:
Make sure you have a leave type that generates timesheets. (debug mode). Ask a leave for 10 working days. The system will generate timesheets for each day, which will result in 10 lines. Refuse and set the leave back to draft. Now change the leave to another date with 10 days and approve it again. The system will generate another 10 lines.

Is it possible to unlink the timesheets when they are not yet approved?

Current behavior:
A lot of timesheet lines will be created. A user has to create an extra filter to find the lines without leave request attached and delete them.

Expected behavior:
Would be nice to have the timesheets unlinked if they are not approved yet. If the timesheet is approved, the system should get a message first.

Video/Screenshot link (optional):

**Comment by jem-odoo** [comment]
Thanks for reporting, it was indeed a bug.
Regards

**Comment by yung-wang** [comment]
You're welcome. Thanks for researching this!
