### ISSUE TITLE
[11.0] Generate payslip only employees with running contract

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#22150]
**Impacted versions:**
11.0
**Steps to reproduce:**

1. Create an employee  with an expired contract
2. Create payslips Batches
3. Generate Payslip

**Current behavior:**

All employees are listed, even those who no longer have a contract with the company

**Expected behavior:**

Only employees who have an in-force contract should be listed because the payroll should only be generated for employees who have a current contract

[Video/Screenshot link](https://www.youtube.com/watch?v=mkUSDQJI0ds&feature=youtu.be):

**Comment by maitaoriana** [comment]
@luistorresm

**Comment by edsersolis** [comment]
+1

**Comment by bst-odoo** [comment]
The behavior is expected. You might still want to issue payroll slips (for example to correct one that has been made when the employee was still working for your company).
That's why we didn't put any restriction on this field.
