### ISSUE TITLE
Font size configuration based on user in odoo 10

### ISSUE THREAD

**Issue by Svickie7** [odoo/odoo#22177]
Is there any module or any proper way for font size configuration based on user in odoo 10.

**Comment by Yenthe666** [comment]
Hi @Svickie7,

Not that I'm aware of. Anyways, the Github tracker is only for bugs in the official code. You should ask these kind of questions on the help forum (help.odoo.com).

Regards,
Yenthe

**Comment by bunhin** [comment]
Hi all,
[V10],  I would like to change font size on all odoo pdf reports only, how to do it in an efficient way correctly? is it possible with this below idea?

My idea  is to inherit and insert a style tag and put a font-size in it.  I have tried create new template that inherit "report.layout" template, then insert tag style inside its head tag, and specify a font-size there for '.page' class.  My expectation is that all report using 'page' class (<div class="page">) will be affected but it does not.  No any clue at the moment to make it works. please anybody help. @Yenthe666 you may have a trick

**Comment by Yenthe666** [comment]
@bunhin the only way to specify CSS is within the report itself and for that report if I'm not mistaking. If you do an xpath into the existing report and add it there it should work.

**Comment by gdgellatly** [comment]
You just need to inherit and override the relevant scss. No need to mess
about with reports and tags.

**Comment by bunhin** [comment]
the idea is (if possible) just add or extend the relevant css class (like page class), and all the pdf report will change on the font-size as example,  with this no need to go to every report just to change the font size one by one,  or no need to create so many report templates (one for each report ) just to inherit and change the font-size.   but if it is only the way than i should go with it

**Comment by bunhin** [comment]
thank you for all responses.
