### ISSUE TITLE
[10.0/11.0] rte and and rte_inline tour creating cluttered output and locks user in page

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22171]
Impacted versions: 10.0, 11.0

Steps to reproduce:
- Open up a runbot, activate developer mode and run the tour `rte` or `rte_outline`:
![image](https://user-images.githubusercontent.com/6352350/34825647-9fed1284-f6d3-11e7-8324-e776e7e54aeb.png)
- Look at where you end when the tour is done. The whole page is garbled with nonsense and ugly lay-outs and there is no way for an enduser to leave this page. The close button is missing in the view and the only way to get out of the page is by editing it:
![image](https://user-images.githubusercontent.com/6352350/34825687-c75a2f0a-f6d3-11e7-85f8-9d0adef214d2.png)
Alternatively you can surf to the page yourself by going to http://yoururl.com/web_editor/field/html?callback=FieldTextHtml_0&enable_editor=1&datarecord=%7B%7D to get the same page without any content:
![image](https://user-images.githubusercontent.com/6352350/34825710-dcb1edc0-f6d3-11e7-95b7-10c18862adb0.png)

Current behavior: The enduser gets a cluttered (or white) page that makes no sense at all and no option to get out of this page.

Expected behavior: The tour creates a minimalistic nice example with readable input and an exit button in the page.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
OPW 804952

**Comment by rim-odoo** [comment]
We do not consider this as an issue since this tour is a purely technical integration test and not targeted to final users.

**Comment by Yenthe666** [comment]
Uhh.. I guess atleast an exit button would be neat though. 😞 But ok.
