### ISSUE TITLE
BoM Component filter for product.template via mrp.views.product_views.xml is incorrect

### ISSUE THREAD

**Issue by trcarden** [odoo/odoo#22187]
Impacted versions:
7-11 enterprise

Steps to reproduce:

1. Install mrp module
2. Create 2 new products. One to be the parent and one to be a component of that parent
3. Create a BOM that establishes the parent child relationship
4. Filter your products by BoM components

Current behavior:

Returns only those products that are not listed in BOMs (the parent products)

Expected behavior:

Return products who are listed as BOM components

Relevant code is here:
```xml
        <record id="product_template_search_view_procurment" model="ir.ui.view">
             <field name="name">product.template.search.bom</field>
             <field name="model">product.template</field>
             <field name="inherit_id" ref="product.product_template_search_view"/>
             <field name="arch" type="xml">
                 <xpath expr="//filter[@name='consumable']" position="after">
                     <separator/>
                    <filter string="BoM Components" name="components" domain="[('bom_ids','not in',[])]"/>
                 </xpath>
             </field>
        </record>
```

I believe the domain filter is not set correctly and is a bit confusing. Instead I believe this gives the correct behavior.

```xml
                <!--
                    We define a component to be a product that has no bom ids (aka it is not in any BOMs)
                -->
                <filter name="components" position="attributes">
                    <attribute name="domain">[('bom_ids','=',False)]</attribute>
                </filter>
```

Can someone check and see if that is right and if so issue a PR correctly? I am not ready to do that myself yet.

**Comment by Yenthe666** [comment]
@sle-odoo you're the master of stock. What do you think?

**Comment by trcarden** [comment]
@sle-odoo any comments?

**Comment by pimodoo** [comment]
Hello,

Thank you for your feedback, we have created a task to make a filter that works, we cannot apply your solution, because it shows all the products that have no bom, and not the ones that are in boms.

We'll also add a filter to show the products that have BOMs.

I close this issue and keep you up to date when it will be merged, it will be done in master as a new field in python code is required to complete it.

Best regards

**Comment by pimodoo** [comment]
Hello @trcarden your feedback has been applied in master in commit: https://github.com/odoo/odoo/commit/3ae9dde258303b8212ae47654edf00e5879e8bab

Thanks
