### ISSUE TITLE
[BUG] Purchase: product display doesn't change if the quantity change

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#22188]
Impacted versions:
Master,11,10,9

Steps to reproduce:
- Create a `product A` with two seller information:
- Partner: `Delta`, Name: `Delta_YY`, Code:`YY`, minium_qty:`1`
- Partner: `Delta`, Name: `Delta_XX`, Code:`XX`, minium_qty:`1000`

**BUG 1**
- Create a purchase
- Add a line with `1` x `product A`
--> You see in the description `[YY] Delta_YY` --> OK
- Modify the quantity to `2000`
--> You see in the description `[YY] Delta_YY` --> **NOT OK**, normaly you see `[XX] Delta_XX`

**BUG 2**
- Create a purchase
- Type `product A` in the field `product_id` in a new line
- If you select `[XX] Delta_XX`, in the description you see `[YY] Delta_YY` --> **NOT OK**

It is come from:
https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/purchase.py#L786 could be pass the supplier info compute from https://github.com/odoo/odoo/blob/11.0/addons/product/models/product.py#L468 to compute the name here : https://github.com/odoo/odoo/blob/11.0/addons/product/models/product.py#L354

Regards
![image](https://user-images.githubusercontent.com/16716992/34851272-9248a156-f729-11e7-9548-7ce6160dd9e0.png)

**Comment by sle-odoo** [comment]
Hi,
So the supplier info is not updated and you get the price of the initial one, even if it is not applicable anymore? Or is just the description not updated but the prices are correct?

Regards

**Comment by fmdl** [comment]
The price is updated (it is correct).

The issue is : if you have a special product code for a specifique quantity, the description for the vendor is not correct (because during the seller info selection the quantity is not use).

**Comment by lap-odoo** [comment]
@sle-odoo Master Bug 817414 created. There will be soon a PR to review.

**Comment by fmdl** [comment]
@lap-odoo any news ?

**Comment by lap-odoo** [comment]
@fmdl We tried to fix it but we faced several issues. 

1: the onchange that will rewrite on a description that you potentially already changed can be problematic from a functional point of view.
2 :  that's complex to manage technically. The many2one here works in a very particular way as the same product can appear more than once. That's the only place in Odoo where we do that. 

Given the technical complexity and the fact that we do not believe it adds a lot of added value to the user, we decided to cancel this.

**Comment by fmdl** [comment]
it is possible to modified the behavior during the procurement (and not on the UI) ?

**Comment by lap-odoo** [comment]
@fmdl It already works when the PO is created by the system (MTO or Reordering rule). 

You just have to make sure to order the supplier info in the right order (https://drive.google.com/a/odoo.com/file/d/1FGRFsWfCs_qx5s3d3lSYFXDtW-Ygq1RO/view?usp=drivesdk).  The system will check the supplier info one by one based on the order of the supplier info and see if it respects the conditions (min qty, validity, ...). 

I've just done the test and it's working fine.
