### ISSUE TITLE
[11.0][community]Odoo Server Error when click button in dashboard module

### ISSUE THREAD

**Issue by Charlesgu1988** [odoo/odoo#22191]
Impacted versions:

- 11.0 community

Steps to reproduce:

- add inventory dashboard context to dashboard module

- click on '3 To receive' button in middle of kanban

Current behavior:

- Odoo Server Error was raised and shows system trying to read a 'board.board' record

Expected behavior:

- go to receive picking list

Video/Screenshot link (optional):
![fireshot capture 4 - my dashboard - odoo_ - http___0 0 0 0_8069_web id view_ty](https://user-images.githubusercontent.com/22249485/34856936-10f30416-f783-11e7-8332-5273593006a0.png)

Details:
in odoo11 when I click on the button, it trigger up a function 'button_clicked' which defined in kanban, form, and list with different action. it's expected to use the function under kanban which just load an action but it call the form function in fact which will save current record before load action. I try on odoo10 and found it use a different function name which just define in kanban and no issue there.
 `            case 'action':`
`            case 'object':`
`                this.trigger_up('button_clicked', {`
`                    attrs: $action.data(),`
`                    record: this.state,`

**Comment by Yenthe666** [comment]
Hi @Charlesgu1988,

Thanks a lot for your bug report.
I've just tested this and I can confirm that this is a bug:
![image](https://user-images.githubusercontent.com/6352350/34863983-64f929b6-f772-11e7-8a4c-d378c367db21.png)

@ged-odoo probably something that you guys missed in the new views. Can you check?

Regards,
Yenthe

**Comment by yueqin** [comment]
@ged-odoo  Hi, I meet this bug too, can you help reslove it, thanks.
Regards,
Dean

**Comment by majumdarmohit** [comment]
![Capture](https://user-images.githubusercontent.com/51365538/59029856-0b192e80-887d-11e9-8124-6d8b1623282e.PNG)

**Comment by kebeclibre** [comment]
@majumdarmohit 
Yeah, and ?
This issue has been closed for 6 months, without any negative feedback from the issue's stakeholder.
So, I strongly doubt the traceback you get is linked in anyway to the issue or fix.
Secondly, If "an image is worth a thousand words", a few ones don't hurt.

I suggest you do a little research on your own traceback (which seems to be linked to your customizations), and that you explain the use case, if the traceback seems, after investigation, linked to the issue.

Also, don't expect us to treat your message, presented like you did, in any other way than I am presently doing

**Comment by Yenthe666** [comment]
It is clearly an issue in the custom development anyways.
