### ISSUE TITLE
[9.0] Website Live Chat - pop up functionality does not work properly

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#22204]
Impacted versions: 9.0

Steps to reproduce:
Go to Website Live Chat and create new channel. Scroll down to "Channel Rules" and ad "Auto popup" action.
Current behavior:
Just a chat button is displayed. There is no difference between "Auto popup" and "Display the button" actions.
Expected behavior:
Pop up with started conversation should open
Video/Screenshot link (optional):
![chat1](https://user-images.githubusercontent.com/18479073/34872815-6cd8e10e-f78a-11e7-9296-3d949e2a7929.JPG)

![chat2](https://user-images.githubusercontent.com/18479073/34872818-7079ea60-f78a-11e7-939c-def59d812ec6.JPG)

**Comment by qsm-odoo** [comment]
Hello,

It appears to be working on my side. Be sure to check these steps and retry:
- The channel you are configuring must be set to be used on the website by choosing it as "Website Live Chat Channel" in the "Website admin" settings
- Your URL regex must be correct
- Try using the livechat as an anonymous user (the only way to do that correctly is to use a private window in your browser or use another computer or clear your cookies)
    - /!\ The auto popup feature is disabled for users who already opened the chat window once (by clicking on the button or anything else)

I am closing the issue, please tell me if this needs to be reopened.
