### ISSUE TITLE
[10] payment_stripe: invoice paid from website charges 100 times the actual amount to pay

### ISSUE THREAD

**Issue by tech006** [odoo/odoo#22213]
Impacted versions:10.0

Steps to reproduce: customer pays open invoice with credit card from website

Current behavior: while the payment process appears to be correct, it actually charges amount*100

Expected behavior: the actual charged amount should be consistent with the amount confirmed during the payment process

Temporary fix to solve this issue:
change: amount:amount --> amount:amount/100 at the following line:
` ajax.jsonRpc('/website_payment/transaction', 'call', {
  reference: $("input[name='invoice_num']").val(),
  amount:amount/100,`
file: odoo/addons/payment_stripe/static/src/js/stripe.js

Video/Screenshot link (optional):

**Comment by yostashiro** [comment]
@tech006 You may check these commits:
- https://github.com/odoo/odoo/commit/b335ae0348ac74b2edb6d5ea56cc230e276ef283
- https://github.com/odoo/odoo/commit/ecda057e1166ea1fa9afa4e5b954e5c99aa80232

**Comment by Yenthe666** [comment]
@tech006 can you please try the commits that should fix this provided by @yostashiro? (Thanks @yostashiro!)

**Comment by tech006** [comment]
@yostashiro @Yenthe666 Your suggested fix has been committed on August 2017. Our issue has been found with the "payment_stripe" add-on that we downloaded 3 days ago (January 2018) from this github ODOO branch 10.0. Please help understand how we can help. Thanks.

**Comment by Yenthe666** [comment]
Hi @tech006,

If you have an enterprise version of Odoo then create a bug report at odoo.com/help too, then it gets a priority.
Otherwise you'll need to wait a bit I guess.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @tech006,

Absolutely! It makes it easier to find for everybody this way too.
If you have an enterprise license you can still report it on odoo.com/help and link to this issue though.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Dear @tech006,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
