### ISSUE TITLE
[8.0] Inheritance by delegation views, active_id and model

### ISSUE THREAD

**Issue by haufes** [odoo/odoo#2221]
When using Inheritance by delegation and extending a view, the UI uses the wrong model and active ID when viewing the "child" model.

EG:

The res.partner model and views are used and extended everywhere. If I create a new model using Inheritance by delegation of res.partner and extend the view "base.view_partner_form" I will see all the partner and my attributes correctly. However, using a button (to crm.phonecall) on this view will use the id of the child model. This is fine for any button added to the child view, but an button added to the res.partner expects a partner ID and model.

I think this is a bug. If not, it means that every module needs to be aware that it could be dealing with an inherited class. Otherwise, anytime Inheritance by Delegation is used to extend a module, that module may need to be modified. 

More details of my issue are here.
https://www.odoo.com/groups/community-framework-62/community-framework-8976100?mode=thread

**Comment by Yenthe666** [comment]
Hi @haufes,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
