### ISSUE TITLE
[11.0]Bug image product and contact [SOLVED]

### ISSUE THREAD

**Issue by Uwantec** [odoo/odoo#22215]
Impacted versions: V. 11 CE

Steps to reproduce: Upload image product or contact

Current behavior: The image product/contact  is added correctly and is visible on the form but does not appear in a group view (articles) 

Expected behavior: See the images displayed

Screenshot :

![bug](https://user-images.githubusercontent.com/18238678/34899599-3d87f406-f7fa-11e7-8583-70f5b3b3ef4a.png)

**Comment by pedrobaeza** [comment]
I think this has been fixed here: https://github.com/odoo/odoo/commit/d5e97eab8b2465c968f5d2abaaabf8c33641dee6

**Comment by Uwantec** [comment]
Thank you very much @pedrobaeza
