### ISSUE TITLE
TypeError: window.getComputedStyle(...) is null

### ISSUE THREAD

**Issue by lfr-opennet** [odoo/odoo#22211]
**Impacted versions:**
11.0 on Firefox (working on Chrome) - entreprise and community

**Steps to reproduce:**
On Firefox: Go to module "Point of Sale" then "Settings" then "Save"

**Current behavior:**
Return javascript error "TypeError: window.getComputedStyle(...) is null" and break the js and don't save at all.

**Expected behavior:**
Save and doesn't return an error

**Video/Screenshot link (optional):**
![pos_error](https://user-images.githubusercontent.com/26574217/34879336-2f44eba8-f7ad-11e7-9100-24617888009b.png)

**Comment by Yenthe666** [comment]
Hi @lfr-opennet,

Thanks for the bug report.
This is indeed an issue. @ged-odoo could you have somebody from the JS team have a look?

Regards,
Yenthe
