### ISSUE TITLE
Automated action runs twice instead of once when invoice gets paid

### ISSUE THREAD

**Issue by flh** [odoo/odoo#22226]
Hello,

On Odoo10, I've created two automated actions (base.action.rule) on the account.invoice model, which trigger when invoice state changes.

Both actions are set to run when the invoice record is modified ("on_write" event in base.action.rule).

Action A:
* filter precondition : [('state', '=', 'draft')]
* filter precondition : [('state', '=', 'open')]
* runs the following Python action : log("invoice draft->open")

Action B:
* filter precondition : [('state', '=', 'open')]
* filter precondition : [('state', '=', 'paid')]
* runs the following Python action : log("invoice open->paid")

When an invoice is created, confirmed then paid, action A is launched once as expected, while action B is launched twice, as shown on the configuration->technical->logging tree view: I get three log lines (one for action A, two for action B, which may appear at the same timestamp or have a small 1 second difference) while I would have expected only two log lines (one for each action).

This is a little annoying since I expected to use action B to automatically print the invoice using OCA base_report_to_printer module. For the moment, the invoice gets printed twice.

Is there any workaround (such as adding more filter conditions) which would prevent action B from running twice?

I've tried to investigate a little the issue, without much success. The account.invoice model defines its own low-level method _write (with a leading underscore), which is exactly the method that base.action.rule tries to patch. Yet, I do not understand why both wouldn't interact correctly.

**Comment by flh** [comment]
I've actually found a workaround: watching changes on the "state" field of an invoice seems to work well except when the invoice moves to the "paid" state. Yet, in this case, the "reconciled" field (boolean) can be used (before: reconciled is false, after: reconciled is true) in the automated action. In this case, the automated action only runs once when the invoice is paid.

After trying to read more carefully the _write method on account.invoice, I suspect that the same problem may occur as well when an invoice is re-opened after being paid.

**Comment by flh** [comment]
After some more testing, the suggested workaround does not seem to always work: I tested it on another Odoo instance and I still get duplicate automated action triggers.

**Comment by flh** [comment]
After some more testing, the suggested workaround (watch "reconciled" instead of "state") yields fewer duplicates but unfortunately some of them still happen.

**Comment by flh** [comment]
I've just updated to v10 commit c3ce7123593e8819f0bb933c6809b8e1df5656ce and:
* my workaround using the "reconciled" field does not work anymore. The automated action is not triggered at all;
* reverting to watching changes on the "state" field still yields to the automated action being run twice.

After reading accounts/models/account_invoice.py, I've seen that the _write() method calls the "action_invoice_paid()" method on account.invoice. According to the first comment in this method, I am not the only one to have noticed the bug:
```python
@api.multi
     def action_invoice_paid(self):
         # lots of duplicate calls to action_invoice_paid, so we remove those already paid
         ...
```
I have written a new workaround by inheriting from account.invoice and overriding account_invoice_paid in the following way:
```python
class MyInvoice(models.Model):
    _inherit = 'account.invoice'

    @api.multi
    def action_invoice_paid(self):
        # For some reasons, this method is often called on already paid
        # invoices. Keep only invoices which are not yet paid.
        to_pay_invoices = self.filtered(lambda inv: inv.state != 'paid')
        # The method from the account module updates the invoice states to "paid"
        res = super(MyInvoice, self).action_invoice_paid()
        # Now we deal only with invoices which were not paid initially and are now marked as paid
        paid_invoices = self.filtered(lambda inv: inv.state ==
                'paid') & to_pay_invoices

        # Fetch our predefined server-action
        action = self.env['ir.model.data'].get_object('my_workaround_module', 'invoice_action_paid')

        # Run the server-action for each paid invoice
        for inv in paid_invoices:
            ctx = {
                    'active_model': inv._name,
                    'active_id': inv.id,
                    'active_ids': inv.ids,
                }
            action.with_context(**ctx).run()

        return res
```
This code runs the "my_workaround_module.invoice_action_paid" server-action, defined by the following XML file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
  <data>
    <record model="ir.actions.server" id="invoice_action_paid">
      <field name="name">When an invoice is paid</field>
      <field name="model_id" ref="account.model_account_invoice"/>
      <field name="state">multi</field>
    </record>
  </data>
</odoo>
```
This creates an empty "multi" server-action. I can then populate this server action with child actions from Odoo web interface.
After some tests, everything seems to run fine: my server action is exactly called once when an invoice moves from the "open" state to the "paid" state.

**Comment by pedrobaeza** [comment]
This is not really an Odoo issue, because ORM can make internally several writings by convenience. You have to adjust your custom code to accommodate it to the base. Take into account that on automated rules you can also add a domain for restricting when to act (for example, state = 'x'), so this can reduced the duplicity.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

Closing this.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Comment by flh** [comment]
As I mentionned on my first post, my automated action actually **does** have a domain state="open" as well as a codomain state="paid".

This does not at all prevent duplicate calls.
