### ISSUE TITLE
Invoice sequence is not maintained when POS sesssion is closed. 

### ISSUE THREAD

**Issue by rameshkarangiya** [odoo/odoo#22234]
Impacted versions: 10.0

Steps to reproduce:

1. Enable Invoicing in POS.
2. Open a POS session.
3. Do some selling(few orders) enabling invoice in order
4. Close Session
5. Click "Validate Closing & Post Entries"

Current behavior:

- It skips few steps after closing session even if no gap and step=1 is set.
- This behavior is not consistent. 

Expected behavior:

- Invoice number should be in sequence without leaving any gaps.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @rameshkarangiya,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
