### ISSUE TITLE
[11.0] Could not save company logo

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#22231]
Impacted versions:
master, 11.0 20180115
Steps to reproduce:
1、Edit company infomation ,upload a img for company logo
2、Click save button
Current behavior:
Error: Incorrect padding

Expected behavior:

Video/Screenshot link (optional):
![qq 20180115123353](https://user-images.githubusercontent.com/22065407/34927363-90eac748-f9f0-11e7-884a-13b634df92de.png)

**Comment by Elkasitu** [comment]
probably linked to #22222

**Comment by Yenthe666** [comment]
@Elkasitu yep, most likely. The logo's seem to break a lot in V11 though, this is the third time? 😕

**Comment by wtaferner** [comment]
Not sure if it is just the logo...I think it is system wide...I was crashing into it with the res.users.

**Comment by Elkasitu** [comment]
should be working as of 2a54886

**Comment by wtaferner** [comment]
@Elkasitu 
Thx

**Comment by Yenthe666** [comment]
Tested & seems to work fine! Thanks for all the great work @Elkasitu
