### ISSUE TITLE
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)

### ISSUE THREAD

**Issue by jigneshept** [odoo/odoo#22267]
**Impacted versions:** Odoo 11.0 (Community Edition)

**Steps to reproduce:** Take latest Odoo v11 and try to set image in the company.

**Current behavior:** 

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/fields.py", line 947, in __get__
>     value = record.env.cache.get(record, self)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/api.py", line 960, in get
>     value = self._data[field][record.id][key]
> KeyError: <odoo.api.Environment object at 0x7f0b43e5b588>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/base64.py", line 518, in _input_type_check
>     m = memoryview(s)
> TypeError: memoryview: a bytes-like object is required, not 'str'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/encodings/base64_codec.py", line 19, in base64_decode
>     return (base64.decodebytes(input), len(input))
>   File "/usr/lib/python3.5/base64.py", line 552, in decodebytes
>     _input_type_check(s)
>   File "/usr/lib/python3.5/base64.py", line 521, in _input_type_check
>     raise TypeError(msg) from err
> TypeError: expected bytes-like object, not str
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 646, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 683, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 927, in __call__
>     return self.method(*args, **kw)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/lunel/odoo_v11/odoo_v11/addons/web/controllers/main.py", line 930, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/addons/web/controllers/main.py", line 922, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/addons/base/res/res_partner.py", line 514, in write
>     result = result and super(Partner, self).write(vals)
>   File "/opt/lunel/odoo_v11/odoo_v11/addons/mail/models/mail_thread.py", line 277, in write
>     result = super(MailThread, self).write(values)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/models.py", line 3008, in write
>     self._write(old_vals)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/models.py", line 3223, in _write
>     self.recompute()
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/models.py", line 4801, in recompute
>     vals = {n: rec[n] for n in ns}
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/models.py", line 4801, in <dictcomp>
>     vals = {n: rec[n] for n in ns}
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/models.py", line 4659, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/fields.py", line 951, in __get__
>     self.determine_value(record)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/fields.py", line 1038, in determine_value
>     self.compute_value(recs)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/fields.py", line 1018, in compute_value
>     self._compute_value(records)
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/fields.py", line 1009, in _compute_value
>     getattr(records, self.compute)()
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/addons/base/res/res_company.py", line 135, in _compute_logo_web
>     company.logo_web = tools.image_resize_image(company.partner_id.image, (180, None))
>   File "/opt/lunel/odoo_v11/odoo_v11/odoo/tools/image.py", line 56, in image_resize_image
>     image_stream = io.BytesIO(codecs.decode(base64_source, encoding))
> TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)

**Expected behavior:**
Save and doesn't return an error

**Video/Screenshot link (optional):**
![screenshot from 2018-01-16 16-06-50](https://user-images.githubusercontent.com/20922072/34984563-5cc28ed2-fad7-11e7-98e3-f3583c7432f8.png)

**Comment by Yenthe666** [comment]
Hi @jigneshept,

Thanks a lot for your report.
This has actually been fixed yesterday (in https://github.com/odoo/odoo/commit/2a5488619da22cfd901963dd141e722b195e82ab)
Please update your Odoo source code and try again 😉 

Regards,
Yenthe

**Comment by jigneshept** [comment]
@Yenthe666 It's working now!

Thanks for your information.

**Comment by Yenthe666** [comment]
Good to hear! Best of luck.
