### ISSUE TITLE
Logistical Valuation & Accounting Valuation don't match when applying costs to Internal Transfers

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#22280]
Impacted versions:
v11

Steps to reproduce:
https://drive.google.com/file/d/13gxGEbsTX1ESCCOdTi5-Micsl_xvwmix/view

Current behavior:
The accounting valuation and the logistical valuation of the products don't match after applying a Landed Cost over an internal picking
Expected behavior:
Either the internal picking are not allowed to be used in Landed Cost to avoid accounting valuation to be increased or Logistical is to be increased when Landed Cost is applied.

**Comment by sle-odoo** [comment]
Hi, thanks for the report!
I think internal pickings should be excluded by now (as it was before?) but supporting them is in our pipe for v12.

Regards

**Comment by fpodoo** [comment]
Yes, we should avoid landed costs on internal pickings. (and we should not
support it for v12 neither as it's not a priority and a weird case)

**Comment by nhomar** [comment]
@fpodoo 

FYI I have 4 customers on (2 on-premise and 2 saas) with simple Importation process in México.

In México which is a huge country it is quite normal move with extra costs things between warehouses.

Would you accept a PR? it is quite easy to solve, instead kill the feature I think my friend.

**Comment by nhomar** [comment]
An import on warehouse of their ownership on EEUU but consolidate shipments and then send them to their own warehouse, Would I manage a different process? what would be the proper functional solution team?

**Comment by nhomar** [comment]
Another very simple situation:

Free LAnded Zones, that's pretty common on countries like Panamá, RRDD, Colombia, México, .... and others where the Landed process finish between internal warehouses...

**Comment by fpodoo** [comment]
But the usual process to manage inter-warehouses flow is to do a delivery
order & a reception order (eventually automated with push/pull rules),
going through a transit location. That way, you can apply a landed cost at
the reception.

Landed cost on an internal picking is weird: one internal move (product =
5$), another internal move (same product becomes 6$). I am not even sure
you can justify that to an auditor.

On Jan 16, 2018 8:20 PM, "Nhomar Hernández [Vauxoo]" <
notifications@github.com> wrote:

Another very simple situation:

Free LAnded Zones, that's pretty common on countries like Panamá, RRDD,
Colombia, México, .... and others where the Landed process finish between
internal warehouses...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/22280#issuecomment-358074462>, or mute
the thread

**Comment by hbto** [comment]
@fpodoo 
Ok, I will try doing your proposal of using inter-warehouse transfers going through transit locations.

Thanks

**Comment by hbto** [comment]
Hi @fpodoo  due to the latest changes included in https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L52-L59

transit locations are not longer taken into account for valuation purposes if coming from or going to another internal location.

Thus applying landed costs on the suggested way is not possible

> But the usual process to manage inter-warehouses flow is to do a delivery order & a reception order (eventually automated with push/pull rules), going through a transit location. That way, you can apply a landed cost at the reception.

https://github.com/odoo/odoo/blob/11.0/addons/stock_landed_costs/models/stock_landed_cost.py#L106-L109

Making a test with your approach we have reached to this end: 

Logistical Valuation:
![stock_moves_-_odoo](https://user-images.githubusercontent.com/7598010/35019995-3ce15a98-fb00-11e7-9033-2c304ad0b726.png)

Accounting Valuation:

![journal_items_-_odoo](https://user-images.githubusercontent.com/7598010/35020067-8fde6e5c-fb00-11e7-994f-7b9524ec5e6f.png)

**Comment by gdgellatly** [comment]
@fpodoo FYI: Under IAS2 it is mandated to include all costs in bringing the product to its **present** location. So there is nothing to justify to an auditor in including them, at least under IFRS rules.  In fact you would need to be able to justify not including them (e.g. immaterial, immeasurable, always instantly consumed, fvm, nrv measurement basis or something).

**Comment by nhomar** [comment]
>> @fpodoo FYI: Under IAS2 it is mandated to include all costs in bringing the product to its present location. So there is nothing to justify to an auditor in including them, at least under IFRS rules. In fact you would need to be able to justify not including them (e.g. immaterial, immeasurable, always instantly consumed, fvm, nrv measurement basis or something).

Totally agreed! but I can't find an specific document that validate this.

The main point here is that this is not a feature that requires a huge refactor, just few key changes and everything will be fixed.

Can you reconsidere @fpodoo ?

**Comment by nhomar** [comment]
Just to answer myself and to point to @fpodoo 

My friend here is a document which say exactly what @gdgellatly is pointing out.

https://www.iasplus.com/en/standards/ias/ias2

**Quoting:**

> Measurement of inventories
> 
> Cost should include all: [IAS 2.10]
> 
> costs of purchase (including taxes, transport, and handling) net of trade discounts received costs of conversion (including fixed and variable manufacturing overheads) and other costs incurred in bringing the inventories to their present location and condition 
> 
> IAS 23 Borrowing Costs identifies some limited circumstances where borrowing costs (interest) can be included in cost of inventories that meet the definition of a qualifying asset. [IAS 2.17 and IAS 23.4]
> 
> Inventory cost should not include: [IAS 2.16 and 2.18]
> 
> abnormal waste storage costs administrative overheads unrelated to production selling costs foreign exchange differences arising directly on the recent acquisition of inventories invoiced in a foreign currency interest cost when inventories are purchased with deferred settlement terms. 
> 
> The standard cost and retail methods may be used for the measurement of cost, provided that the results approximate actual cost. [IAS 2.21-22]
> 
> For inventory items that are not interchangeable, specific costs are attributed to the specific individual items of inventory. [IAS 2.23]
> 
> For items that are interchangeable, IAS 2 allows the FIFO or weighted average cost formulas. [IAS 2.25] The LIFO formula, which had been allowed prior to the 2003 revision of IAS 2, is no longer allowed.
> 
> The same cost formula should be used for all inventories with similar characteristics as to their nature and use to the entity. For groups of inventories that have different characteristics, different cost formulas may be justified. [IAS 2.25]

Then said that:

AFAIK, the technique to add this costs properly is the landed cost document (which do the job nicely), IMHO we are facing a bug here if we support the fact that "Accounting should not miss match the logistic information"

And wait until v13.0 is not a good idea in my opinion.

**Comment by gdgellatly** [comment]
@nhomar - That's a summary - NZ standards are generally verboten copies of the internationally drafted standards, and are well organized, although the implementation date may vary.  

PBE IPSAS 12 - Not-for-profit http://www.xrb.govt.nz/accounting-standards/not-for-profit/pbe-ipsas-12/
NZ IAS 2 - For profit http://www.xrb.govt.nz/accounting-standards/for-profit-entities/nz-ias-2/

Whether the correct technique is landed costs, the standards don't really care about how you implement them (with few exceptions), just that you do.

**Comment by nhomar** [comment]
> Whether the correct technique is landed costs, the standards don't really care about how you implement them (with few exceptions), just that you do.

Exactly, that's why I am open to other options, but landed IMHO is the best one and the more clear to use for such deal.

**Comment by gdgellatly** [comment]
Also note - I think US GAAP is quite different on the topic of inventory measurement.  I've never really looked at it, I just remember being told it was a lot more prescriptive.

**Comment by lap-odoo** [comment]
Hi,

Applying landed costs on internal moves is currently not supported. 

For the future, it is in our plans to support applying landed costs on moves coming from an inter-warehouses transit location. So if you move your products between warehouses (WHA > Transit, Transit > WHB), you'll be able to apply landed costs.

**Comment by lap-odoo** [comment]
@nhomar As discussed, we don't plan to do any changes related to that point in V11 but we'll have a look at your patch when you'll send it :)
