### ISSUE TITLE
history_ids field not defined in stock.quant, but used.

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#22299]
**Impacted versions:** 
11.0

**Steps to reproduce:** 
Try to call method **action_traceability()** from model: stock.production.lot  

**Current behavior:** 
field history_ids used in method but there is no history_ids filed define in entire odoo code. 

**Expected behavior:** 
there should be history_ids field in stock quant.
and if odoo remove history_ids field from stock.quant then whats the method doing here.
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_production_lot.py#L48 

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Hi, thanks for your report.

It looks like dead code as a byproduct of commit b3180c8

cc @sle-odoo

**Comment by sle-odoo** [comment]
Seems unused now, but "action_stock_report" is callable by the "up/down traceability" stat button and opens the traceability report. Did you manage to call this method with the standard views?
