### ISSUE TITLE
[11.0] Hierarchy view is not working.

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#22304]
Impacted versions:11.0

Steps to reproduce: Go to Payroll >> Configuration >>   Salary Rule Categories Hierarchy

Current behavior: It shows New Form View

Expected behavior: It should show Hierarchy view 

Video/Screenshot link (optional): http://294612-11-0-ca2060.runbot9.odoo.com/web?debug#id=&view_type=form&model=hr.salary.rule.category&menu_id=450&action=626

**Comment by sswapnesh** [comment]
Related to #20108.

**Comment by tuomoaura** [comment]
We really need this view type.

**Comment by pedrobaeza** [comment]
It seems that this view is not going to be available anymore. See the related issues referenced here.
