### ISSUE TITLE
[SECURITY] odoo login details getting from browser cache form data

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#22311]
Impacted versions: v8, v9, v10 community, v11 community

Steps to reproduce: In google chrome browser, open a odoo url with ssl enabled(https). Activate the page inspect element, then go to network tab and activate the preserve log. then enter the login details and press enter. Now check network tab,on the login's form data and we can see the csrf token, login and password.

Current behavior:Showing the login details as plain text

Expected behavior: It should show the hashed/salted value

Video/Screenshot link (optional):
![hash_issue](https://user-images.githubusercontent.com/381874/35058458-fecb6c6a-fbdd-11e7-9a10-613f2fcd9208.png)

**Comment by wtaferner** [comment]
@Yenthe666 
I doubt it is a security issue of Odoo as it is the normal post request which should be communicated securely over SSL. The browser can read based on being an endpoint anyway, but here @omalbastin did not even use a SSL connection, so I think this can be closed as invalid. If it should be somehow relevant in terms of security we could question only whether the browser is secure of being eavesdropped form other software on the client computer, but I doubt this too nowadays ;-)

But Yenthe is right...please report such issues directly and via the responsible-disclosure rules.

**Comment by Yenthe666** [comment]
@wtaferner yeah I do agree but I let everything security related pass through @odony or @mart-e. Those are not my call honestly. 
But yes, to me this is also invalid / irrelevant.

**Comment by mart-e** [comment]
Hello,

Indeed, for security issues, please be responsible and check our [responsible disclosure](https://www.odoo.com/page/responsible-disclosure) page.
In this case, it is not an issue as it is how form authentication works and most website do as well.
This is also the reason why having SSL enabled is so important because only you can access the form information.
