### ISSUE TITLE
Barcodes seems to do some weird stuff

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#22335]
Impacted versions: 11.0

Steps to reproduce:
DISCLAIMER: I am guessing a lot here

I found this in testing an enterprise workflow by adding barcode_trigger='scrap' to 1 of the action_next buttons and then barcode_trigger='pack' to the other one in the mrp_workorder tablet view of mrp_quality, however the bug is in barcodes module js somewhere.

```xml
<record model="ir.ui.view" id="mrp_workorder_form_view">
        <field name="name">mrp.workorder.form (in quality_mrp_barcode)</field>
        <field name="model">mrp.workorder</field>
        <field name="inherit_id" ref="quality_mrp.mrp_workorder_view_form_tablet"/>
        <field name="arch" type="xml">
            <form position="inside">
                <field name="_barcode_scanned" widget="picking_barcode_handler"/>
            </form>
            <xpath expr="//button[@name='action_next'][1]" position="attributes">
                <attribute name="barcode_trigger">scrap</attribute>
            </xpath>
            <xpath expr="//button[@name='action_next'][2]" position="attributes">
                <attribute name="barcode_trigger">pack</attribute>
            </xpath>
        </field>
    </record>
```
Note their are no events for _barcode_scanned in mrp.workorder and the issues is the same with or without. I just reused a couple of available codes for easy testing.

Current behavior:
Its almost like the barcode recognition follows the breadcrumbs or something.
If I go through MRP and then to the form view of workorder and then to the tablet view - it works, but with an error.
If I go directly to it it works without error.

Expected behavior:
To just work

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=-RWVU9pakRY&feature=youtu.be

The video is a bit of a mess as it can be a bit tricky to reproduce, also note sometimes it gets a CORS traceback - that happened in the vid.  The first part of the video is it working correctly - the undefined error is for the hidden button which is OK.  The Validate button [action_next][2] goes without error.  In the end of the video you see 3 errors for the hidden button and 2 for the visible one.

**Comment by Yenthe666** [comment]
@sle-odoo I believe this is of interest for you.

**Comment by sle-odoo** [comment]
i suppose the barcode listener is not unbound when a new action is processed?
also, you need code for the barcode mechanism to do something (inheriting the barcode mixing on the model and implementing the onchange at least, then implementing some javascript to bypass the onchange if it's not needed for performance reasons)
i'll have a look, there are still things to do with the barcode in 11

**Comment by gdgellatly** [comment]
@sle-odoo I have done all that on workorder (you can see in xml I must have mixin) - I'll do the same on manufacturing orders and see what happens - because even if I can just get a noop chain it will be a completely fine workaround as the end commands will only be valid for workorders - it just wasn't necessary for this report to show it all as O-BTN commands seem to be treated regardless of mixin being present or not.

To be continued

**Comment by gdgellatly** [comment]
@sle-odoo I think you are right about the action not being unbound, because I can reproduce now straight from workorders dashboard, into kanban, into workorder, but if I then go back and go back in no errors.

However I also now have a working workaround.

Instead of using O-BTN commands and assigning to a button, if I use just a non special barcode and use the onchange mechanism through on_barcode_scanned it all works in all scenarios, which also kind of confirms that this issue is all js and its handling of special commands.

Not great but workable.  But in doing all of this I found lots of other weird little bugs with this especially if you use the O-CMD codes, as they get processed.

**Comment by sle-odoo** [comment]
We'll have a look. We have an ongoing task on the barcode at the moment. As this isn't reproducible in a standard Odoo environment, i'm closing this issue but i will link it in our internal task. cc @amoyaux
