### ISSUE TITLE
Odoo9 Mobile view is not working

### ISSUE THREAD

**Issue by prakashkumar163** [odoo/odoo#22331]
Impacted versions: Odoo9

Steps to reproduce:
Open web menu on chrome and click on mobile view in the bottom .
**The view will not change and navbar-toggle is will  not visible** 

 
Now open a new tab and increase screen size: 175%
**The navbar-toggle is visible  here**

:
Video/Screenshot link (optional):

![screenshot from 2018-01-18 15-08-20](https://user-images.githubusercontent.com/25385447/35091060-9a56c002-fc61-11e7-896e-0e513d496caf.png)
![screenshot from 2018-01-18 15-05-56](https://user-images.githubusercontent.com/25385447/35091061-9a955f6a-fc61-11e7-9e1a-b89b820bc942.png)

**Comment by prakashkumar163** [comment]
In Odoo 10 this issue, 
![screenshot from 2018-01-18 15-06-31](https://user-images.githubusercontent.com/25385447/35091228-fe08b5a6-fc61-11e7-8222-2c0edf996f97.png)
not present.

**Comment by Yenthe666** [comment]
@adr-odoo can you check?

**Comment by adr-odoo** [comment]
Hello,

This is the 9.0 community.
This is not supposed to be mobile optimized.
I only fix blocking issues.

Sorry about that.
Regards,
