### ISSUE TITLE
JSON Error when accessing Sales Teams menu while thousand separator is active

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#2233]
How to reproduce the issue:
1. Enable Sales Teams
2. Go To Settings => Languages. Select language of the current user and enable thousand separator, e.g. [3,3,3,3]
3. Reload with Ctrl+F5
4. Go to Sales => Sales Teams to see the following error:
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 3 of the JSON data

**Comment by Yenthe666** [comment]
Hi @davidtranhp,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
