### ISSUE TITLE
Locking feature Prevents "Coupons & Promotions" feature in Sale App.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#22333]
Impacted versions:
Odoo 11 (Enterprise)

Steps to reproduce:
1) Go to Sales > Configuration > Coupons & Promotions > Create any Promotion Program.(e.g with 
     coupon code), 
2) Go to Sales > Configuration > Click on 'Lock Confirmed Orders'.
3) Sales > Create Quotation >Button 'Apply Coupon' > Enter Code > Click on 'Confirm Sale' Button.

Current behavior:
 >  Its preventing us from confirming the quotation even.
Expected behavior:
 >  It should allow to confirm the quotation.

Video/Screenshot link (optional):
https://youtu.be/G3_XnXoYiy8
https://www.awesomescreenshot.com/image/3109020/e370c37d70ad2c48ff3646186a2d3bda

**Comment by dipsshah42** [comment]
Hello @Yenthe666 ,  

Hope you are doing great !
Can you please check this ?
Many Thanks.

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

I'm honestly not sure who is responsible for this or who can verify it. @mart-e can you check?

Regards,
Yenthe

**Comment by dipsshah42** [comment]
No problem @Yenthe666 :) 

Have a good day !

**Comment by Yenthe666** [comment]
Thanks you too! Ping me again if you had no response in two weeks.

**Comment by sswapnesh** [comment]
@Yenthe666 
I can Confirm this bug. 
Looks like it is calling Super method `action_confirm` first before doing some operations on Sale Order line.
Couldn't trace code as I don't have enterprise Repo access.

**Comment by dipsshah42** [comment]
@sswapnesh i do agree with you.
