### ISSUE TITLE
Could not print "Financial Reports" from "Account reports" menu

### ISSUE THREAD

**Issue by metlaivan** [odoo/odoo#22349]
Impacted versions: 11.0 529a8f5aa87985592b957ba97b4e476ed41aea9c

Steps to reproduce:
Open Invoicing->Financial Reports->Account reports click on "Profit and Loss" report and try print it.
![image](https://user-images.githubusercontent.com/1558327/35100693-66151696-fc65-11e7-90fc-1fd02f8f70fa.png)

Current behavior:
Get warning with the message "Form content is missing, this report cannot be printed." Tested on new DB with test data.
![image](https://user-images.githubusercontent.com/1558327/35100652-3b808f8c-fc65-11e7-8571-76211c13ee8b.png)

Expected behavior:
Print(download) this report in PDF. If I try to print this report from another menu it will succeed. 
![image](https://user-images.githubusercontent.com/1558327/35100828-e2ad4cb4-fc65-11e7-94d9-1b6ee1867744.png)

**Comment by sswapnesh** [comment]
Hello @metlaivan 
I don't think this menu should be used to Print Report, It is there to Configure that report. (It is same in v10 too)

These are report types.
![](https://image.prntscr.com/image/dA4uLuuKQFC-a1OANMSzrA.png)

Which is used here to Print Individual report
![](https://image.prntscr.com/image/HnxfqlDHRNKNpFXG3Dlb9A.png)


![](https://image.prntscr.com/image/EFz3nj74TJe0NEIGIqIbFg.png)

CC: @Yenthe666

**Comment by Yenthe666** [comment]
Mhmm, I believe so too. However the print option is there and it is in fact broken.
@mart-e final call up to you 😉 I guess a minor fix to make the minimal report work would be fine.

**Comment by smetl** [comment]
Hello,

This issue has been fixed on 11.0 just now. This action is now invisible. You should be able to see the difference after upgrading your 'account' module.

Best regards,

**Comment by Yenthe666** [comment]
@smetl can you please add the commit/PR link too?

**Comment by smetl** [comment]
commit: https://github.com/odoo/odoo/commit/91be355bf9203708245ed02383c5331db0610628

**Comment by Yenthe666** [comment]
Aha. Thanks a lot!
