### ISSUE TITLE
new group added in code existing code in 9

### ISSUE THREAD

**Issue by sagarrt** [odoo/odoo#22350]
Impacted versions:9

Steps to reproduce:
in file addons/mail/models/mail_message.py  line no 100
    field tracking_value_ids has no group in previous git pull before 5-6 month
    now it has bean added a group  **groups="base.group_no_one",**
    why would you added this, shall i know the reason?, so i can change my code accordingly
Current behavior:
    it getting error on my new machine when i reinstall the os and odoo configuration.

    the issue is when i save my quotation first time it shows access write error
    i overtire the field still it not working.
    so i remove the group from my code and it work.
Expected behavior:
    
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sagarrt,

Usually group.no_one is set on fields that are very technical or require quite some knowledge. As an administrator you'll have access to this though.
If you don't want to have this behaviour you'll need to create custom code to override this behaviour.

Regards,
Yenthe
