### ISSUE TITLE
[11.0] Could not Validate Incoming Picking

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22356]
Impacted versions: 11.0

Steps to reproduce: Performed on [Runbot](http://295137-11-0-66a95d.runbot13.odoo.com/web?&debug=#id=287&view_type=form&model=stock.picking&action=539&active_id=5) --> Click on Validate 

Current behavior:  Warning On Screen `Record does not exist or has been deleted.`

In Cosole: 
`Server application error {"code":200,"message":"Odoo Server Error","data":{"exception_type":"missing_error","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 947, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 960, in get\n    value = self._data[field][record.id][key]\nKeyError: <odoo.api.Environment object at 0x7f3e5e725be0>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 646, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 927, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/web/controllers/main.py\", line 934, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/web/controllers/main.py\", line 922, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock/models/stock_picking.py\", line 742, in button_validate\n    self.action_done()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/delivery/models/stock_picking.py\", line 112, in action_done\n    res = super(StockPicking, self).action_done()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock/models/stock_picking.py\", line 636, in action_done\n    todo_moves._action_done()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/sale_stock/models/stock.py\", line 30, in _action_done\n    result = super(StockMove, self)._action_done()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock_account/models/stock.py\", line 304, in _action_done\n    res = super(StockMove, self)._action_done()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock/models/stock_move.py\", line 1013, in _action_done\n    if move.quantity_done <= 0:\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 954, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 961, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 993, in getter\n    raise exception\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 1023, in compute_value\n    self._compute_value(record)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 1009, in _compute_value\n    getattr(records, self.compute)()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock/models/stock_move.py\", line 243, in _quantity_done_compute\n    for move_line in move._get_move_lines():\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/mrp/models/stock_move.py\", line 105, in _get_move_lines\n    if self.raw_material_production_id:\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 947, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 961, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 993, in getter\n    raise exception\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 1018, in compute_value\n    self._compute_value(records)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 1009, in _compute_value\n    getattr(records, self.compute)()\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/stock/models/stock_move.py\", line 243, in _quantity_done_compute\n    for move_line in move._get_move_lines():\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/addons/mrp/models/stock_move.py\", line 105, in _get_move_lines\n    if self.raw_material_production_id:\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 947, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 961, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 993, in getter\n    raise exception\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/models.py\", line 2520, in read\n    values[name] = field.convert_to_read(record[name], record, use_name_get)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/models.py\", line 4659, in __getitem__\n    return self._fields[key].__get__(self, type(self))\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/fields.py\", line 947, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 961, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/extra/runbot/static/build/295137-11-0-66a95d/odoo/api.py\", line 993, in getter\n    raise exception\nodoo.exceptions.MissingError: ('Record does not exist or has been deleted.', None)\n","arguments":["Record does not exist or has been deleted.",null],"message":"Record does not exist or has been deleted.\nNone","name":"odoo.exceptions.MissingError"}}`

![](https://image.prntscr.com/image/jSlte9mNSU_-0pcbrIJFZg.png)

Expected behavior: Should be Processed

Video/Screenshot link (optional):

![](https://image.prntscr.com/image/_TufkVZSTSOmaY7hJTiaIQ.png)

**Comment by sswapnesh** [comment]
@sle-odoo 
Could you please check it?

**Comment by Yenthe666** [comment]
Thanks for the very quick fix @sle-odoo! Great job.
