### ISSUE TITLE
Sort function field, which is not stored in the db

### ISSUE THREAD

**Issue by ntodorova** [odoo/odoo#22354]
Impacted versions: all

Steps to reproduce:
I have a function field, which I don`t want to store in the db.

The problem is that I want to be able to sort by this field in a tree
view via click on the column header.

Current behavior:
Nothing happens when you click on the functional field header in the list view.

Expected behavior:
Sort the results by this field

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@Yenthe666 I can confirm this behavior. Even you cannot use `sum` or `average` in group by also.

**Comment by mart-e** [comment]
Hello,

If you want to be able to search or sort on a non-stored field, you need to define a `search` method on that field.
https://www.odoo.com/documentation/11.0/reference/orm.html#field-computed

If you want to be able to sum, you must store it.

**Comment by ntodorova** [comment]
Hi, 

thank you for your answer and time @mart-e , but the search method does not enable the sorting, at least this is my observation. It enables just the filtering. Or I am wrong?

Regards
N.Todorova

**Comment by mart-e** [comment]
My bad, you are indeed right. I have checked and it is unfortunately not possible to sort if the field is not stored.
It is postgresql that directly apply the sort parameters, so not applied for values not present in the database.

**Comment by ntodorova** [comment]
@mart-e, could you please open the issue again since there is no proper answer to the question?

**Comment by mart-e** [comment]
@ntodorova while it is true it is not possible, we do not have a solution. That would require too much changes in the ORM so we are not going to implement that.
Sorry but the only workaround at the moment is to store it.

**Comment by ntodorova** [comment]
ok, thank you for your answer : ))

**Comment by Protoneer** [comment]
@mart-e related fields are stored in the DB right? or are related fields data added after the initial Postgresql fetch?

**Comment by mart-e** [comment]
@Protoneer please open a new issue for old topics. And the related fields are stored only if you add the `store=True` attribute on the field definition.
