### ISSUE TITLE
[9.0][mail] email from in mail template is not taking current users email id.

### ISSUE THREAD

**Issue by knk-kanak** [odoo/odoo#22368]
Impacted versions: 9.0

Steps to reproduce: 

1. In Settings > Email> Outgoing mail server i had configured my gmail smtp.
2. Now From Odoo i am trying to send RFQ/PO/SO by send mail button.

Current behavior: In "Email From" it always taking my outgoing mail server email id

Expected behavior: "Email From" should be current user's email id instead of outgoing mail server email id.

**Comment by knk-kanak** [comment]
hello sir any update this??

**Comment by Yenthe666** [comment]
Hi @knk-kanak,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
