### ISSUE TITLE
[V80] only 80 accounts on receipts shown

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#2236]
please read: #2235 
The same seems to be true for accounts on receipts.

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Quite a short bug report. 😄 

Regards,
Yenthe
