### ISSUE TITLE
[BUG] [10.0] ACCESS ERROR CRM.TEAM

### ISSUE THREAD

**Issue by ventilooo** [odoo/odoo#22360]
Impacted versions: 
* Odoo 10.0+e-20171030 (Enterprise Edition)
     * EE sha: 94778b813a03b29b005735235c2e7fe06c066034
* Postgres 9.4

Steps to reproduce: 
1. Install `CRM` module
2. create a **Test User** with only `employee` and `see_own lead right`
3. Enable in `CRM` configuration _**Use leads if you need a qualification step before creating an opportunity or a customer**_
4. Connect as the **Test User**
5. Open an **existing lead**  in `CRM`
6. Convert the lead to an **opportunity** with the _Do not link to a customer_ option.

:building_construction: [Gif with all the steps](https://send.firefox.com/download/9327197b52/#zPxuu1UJ2IuZGDL3L1cg8w) :tractor: 

Current behavior:
* If a user is not in a **Sales Team** the sale_team is field on a lead is marked as **Unknow**
* You'll have an **access error** if you try to create a lead !
* You'll have an **access error** if you try to convert a lead to an opportunity with the  _Do not link to a customer_ option.
* If you disable those two **ir.rules** the _access error_ disappear.
![screenshot-2018-1-18 record rules - odoo](https://user-images.githubusercontent.com/9092178/35128440-8849d962-fc84-11e7-84ea-1603c4772a8e.png)

Expected behavior:
* There should be no access error if a user is not in a **sale teams**  when you try to create a lead. 
* The sale_team field on a lead should not be filled with **Unknow**

Video/Screenshot link (optional):

![screenshot-2018-1-18 need a quotation for computers with accessories - odoo](https://user-images.githubusercontent.com/9092178/35128387-517c5b6c-fc84-11e7-9382-8dd989de7b69.png)

**Comment by kebeclibre** [comment]
Hello,

The commit 262be78957dc8f7d9db87e49ee36fe9b5e735fbd closes this issue
