### ISSUE TITLE
[11.0][EN] Do not include "Draft" Journal Entries in the Accounting Dashboard balance

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22383]
#### Impacted versions:
11.0 (as far as tested)

#### Steps to reproduce:
Create a Journal "Test Bank"
Go to the Dashboard and it has 0 balance
![image](https://user-images.githubusercontent.com/16890942/35151770-fe42ce00-fcf5-11e7-8253-327c27b43a4f.png)

Create a draft Journal Entry to use later, just save it, do not confirm it.
![image](https://user-images.githubusercontent.com/16890942/35151869-51da11ea-fcf6-11e7-9fc0-24b448ab9a4e.png)

#### Current behavior:
![image](https://user-images.githubusercontent.com/16890942/35151880-62655646-fcf6-11e7-858f-c5ac9168ab12.png)
We're rich...but just in draft.

#### Expected behavior:
Just confirmed richness should show in the Dashboard.

cc: @qdp-odoo

**Comment by qdp-odoo** [comment]
mmhmmhmhmhmh maybeeee, I suppose... although 
* it is debatable
* it is not really breaking anything or a blocking issue
* it is a behavior change, as minor as possible, but still

so I'll change that in master, not in stable.

**Comment by qdp-odoo** [comment]
closed by https://github.com/odoo/odoo/commit/6c211376f0faa9c72213a2efe2ea1b726d247678

**Comment by gustavovalverde** [comment]
I agree it's debatable, there might be moments in time where you would like to see this information (when loading initial balances or in the first weeks of an implementation). 

It could also be a configurable option.
