### ISSUE TITLE
[11.0] Payment reconciliation does not give the same result as paying an Invoice directly

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22386]
#### Impacted versions:
11.0, but there's also a similar behavior when doing bank reconciliation with invoices in 10.0

#### Steps to reproduce:
Create multiple invoices for the same partner, all of them in the **Open** state
![image](https://user-images.githubusercontent.com/16890942/35152591-57a244e6-fcf9-11e7-8211-6ad1439b3bfb.png)

Make a Partial payment of two (2) of the invoice with one (1) payment, from the Invoices view:
![image](https://user-images.githubusercontent.com/16890942/35152719-e64845ec-fcf9-11e7-870a-80b7cf0749e0.png)

![image](https://user-images.githubusercontent.com/16890942/35152769-16b99b72-fcfa-11e7-97fa-84e14f43e756.png)

#### Current behavior:
Payment shows the invoices paid
![image](https://user-images.githubusercontent.com/16890942/35152812-4b3dfd66-fcfa-11e7-9d3b-8d390c900e02.png)

And payment receipt is OK
![image](https://user-images.githubusercontent.com/16890942/35152854-83fff2d0-fcfa-11e7-8e92-7166686f47cb.png)

![image](https://user-images.githubusercontent.com/16890942/35153103-8304691e-fcfb-11e7-9ffa-64b41a0b3e94.png)

#### Steps to reproduce:
The payment will be create from the Payments Menu:
![image](https://user-images.githubusercontent.com/16890942/35153342-821f2b46-fcfc-11e7-8ab3-6c62ab76d2ce.png)

After confirmed we go to the payments matching:
![image](https://user-images.githubusercontent.com/16890942/35153368-a811a798-fcfc-11e7-8a2e-59c1423b8b5c.png)

We reconcile with the selected invoices
![image](https://user-images.githubusercontent.com/16890942/35153452-f4d996f8-fcfc-11e7-8a30-800fa95dcea2.png)

#### Current behavior:
Paid Invoices are not shown:
![image](https://user-images.githubusercontent.com/16890942/35153505-27ea21fc-fcfd-11e7-826a-c541bd40aa8c.png)

Payment receipt does not show the paid invoices:
![image](https://user-images.githubusercontent.com/16890942/35153549-5b94df2e-fcfd-11e7-9fcf-8f9af3621c13.png)

#### Expected behavior:
Both processes should give the same result

cc: @qdp-odoo

**Comment by gustavovalverde** [comment]
@qdp-odoo  This also happens with Bank Reconciliation in v10

**Comment by gustavovalverde** [comment]
This one is slightly important, any comments?

**Comment by vcloud9ray** [comment]
Is this the same as https://github.com/odoo/odoo/issues/20804 ?

**Comment by gustavovalverde** [comment]
Yes it is, I'll close this one and relate yours to the ticket I created.
