### ISSUE TITLE
[11.0] Journals shouldn't show the "Available in the PoS" if the point_of_sale is not installed

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22382]
#### Impacted versions:
11.0

#### Steps to reproduce:
Do not install the "point_of_sale" module
Create a new Journal

#### Current behavior:
It shows the option to add it to the Point of Sale as a payment option.
After installing the "point_of_sale" module, it also adds a Tab on the journal for the Point of Sale, but it has no options inside.

#### Expected behavior:
Maybe this option was meant to be inside that tab, as it's in v10

**Comment by Yenthe666** [comment]
@qdp-odoo probably relevant for you.

**Comment by qdp-odoo** [comment]
@gustavovalverde don't know what you're talking about: this field is added in point_of_sale module (https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/account_journal.py#L10) so there's no way it could be visible without the module installed...
