### ISSUE TITLE
[11.0] A Cash Journal shouldn't have the "check" payment method as an option

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22381]
#### Impacted versions:
11.0

#### Steps to reproduce:
Create a Cash Journal

#### Current behavior:
In the Payment Methods, there's `check` option

#### Expected behavior:
No way to have the check option if the journal is not Bank type

**Comment by smetl** [comment]
Hello,

A feedback has been created concerning this issue.

Thank you,
