### ISSUE TITLE
[11.0][10.0] Creating a Bank Journal should set it related account as reconcile by default

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22380]
#### Impacted versions:
11.0 10.0

#### Steps to reproduce:
Create a new Bank Journal
Do not specify an Account

#### Current behavior:
The newly created account `reconcile` option is not set as True

#### Expected behavior:
Bank and Cash accounts should be (by default) reconcilable, otherwise if needed after doing a transaction, it can't be changed.

It's easier not to use the feature, than wanting the feature and not being able to enable it after doing a transaction.

**Comment by lap-odoo** [comment]
@gustavovalverde Thanks for the remark. Since saas 11.1 it's possible to set to true the value of the reconcilable checkbox even if some transactions have been done. I think it solves your problem.

**Comment by Yenthe666** [comment]
To further expand on this: this means we'll have it available/fixed in V12 😉
