### ISSUE TITLE
[11.0] URL widget opens links in same tab it should open link in new tab

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#22389]
Impacted versions: 11.0

Steps to reproduce: go to contacts and click on website link

Current behavior: opens site in same tab

Expected behavior: should open in new tab. in v10 it works as expected.

Video/Screenshot link (optional): http://295554-11-0-f3449f.runbot13.odoo.com/web?#id=8&view_type=form&model=res.partner&action=93

**Comment by Yenthe666** [comment]
Hi @tpa-odoo,

Thanks for the bug report.
This has been the same behaviour in V9, V10 and V11 though. All smart buttons redirect in the same tab anyways. So in short: desired behaviour and not something that will be changed.

Regards,
Yenthe

**Comment by tpa-odoo** [comment]
Hello @Yenthe666,

May be you misunderstood the point. If it is about smart button or odoo link it is fine. But this is about website URL widget.

on the customer you have site and on click you lost odoo screen which is not good. It should open customer website in new tab only. In previos version also it was opening in tew tab. (yo can check it)

**Comment by sswapnesh** [comment]
@Yenthe666 I agree with @tpa-odoo 
It should open the link on the new tab like V9 and V10.

**Comment by Yenthe666** [comment]
@tpa-odoo and @sswapnesh are you guys talking about an URL in a webpage or? Please add some screenshots / videos or something 😄

**Comment by sswapnesh** [comment]
We are talking about `widget=url ` in form view.

![](https://image.prntscr.com/image/th2HJDs7TQKu7WBa-BOh6g.png)

**Comment by Yenthe666** [comment]
Ahh, now this makes sense. This behaviour has changed indeed and I do agree the previous way (a new tab) was better.
@ged-odoo was this done by accident in the JS framework rewrite?

**Comment by ged-odoo** [comment]
We always tried to keep the previous behaviour, unless it did not make sense.  In this case, the previous widget inherited from FieldEmail, which added the target=_blank attribute.  I assume that when we rewrote the FieldURL, we did not see it.  This is a bug, and really easy to fix.

**Comment by ged-odoo** [comment]
fixed with commit https://github.com/odoo/odoo/commit/21c1b1acd34406d1c568a66976c69511a656861e

Thanks to everyone for reporting/triaging/commenting on this issue... :)

**Comment by Yenthe666** [comment]
Thanks a lot for the fix @ged-odoo!
