### ISSUE TITLE
[V8] Sales quotation: pressing ENTER after changing qty on an existing multi-line order copies the product to the next line

### ISSUE THREAD

**Issue by jon-willdooit** [odoo/odoo#2238]
To reproduce:

1) Create a multi-line sales order/quote
2) Save (or not save - it doesn't matter)
3) Edit the order
4) Click on the qty window of the first line and change the qty THEN press the ENTER key (DO NOT use the tab key or click on another window on the same order line)

Result: the product on the line for which the qty was changed is copied to the next line

You can keep doing this on all remaining lines with the same results

**Comment by Yenthe666** [comment]
Hi @jon-willdooit ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
