### ISSUE TITLE
Wrong behavior adding new line in bank statement

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#22399]
Impacted versions:
* 11.0

Steps to reproduce:
* Add several lines in bank statement
![bankstatement](https://user-images.githubusercontent.com/7595505/35175704-90ac61f4-fd3a-11e7-8d4b-c2c26944dffd.png)

* then try to add one line and set amount
![account_bank_statement](https://user-images.githubusercontent.com/7595505/35175763-e1b59304-fd3a-11e7-8459-06cae1ab22c2.png)

Current behavior:
The line disappears when try to add amount

Expected behavior:
Set the amount in line

**Comment by sswapnesh** [comment]
Hello @JulioSerna 
I have tested same on [Runbot.](http://295682-11-0-c5749e.runbot9.odoo.com/web?&debug=#view_type=list&model=account.bank.statement&action=311&active_id=102)

New Lines are added successfully there.

Note: Those lines are sorted based on Dates and Record Id, So In your case date for all lines are same and after saving the may have been moved to fist page.

Adding Line:
![](https://image.prntscr.com/image/MVlZnrKXQ8ieSrmMi3gk2A.png)

After Save:

![](https://image.prntscr.com/image/CnniXk56Smy6PBBWF6DAlA.png)

**Comment by Yenthe666** [comment]
@JulioSerna can you please update your odoo and test if this is solved for you too?

**Comment by JulioSerna** [comment]
this issue was solved

**Comment by Yenthe666** [comment]
Great, thank you!
