### ISSUE TITLE
[10.0] Warning should be Improved to modify a posted entry of this journal.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22406]
Impacted versions: 10.0/11.0

Steps to reproduce: Create Journal entry --> Post It --> Cancel It.

Current behavior:
Warning on Screen

```
Odoo Warning - Warning
You cannot modify a posted entry of this journal.
First you should set the journal to allow cancelling entries.

```

Warning is Correct but however "Cancel Journal Entries" module is not installed.

Expected behavior: Warning message should be Improved or It should ask to Install "Cancel Journal Entries" module to allow cancelling entries or module should be Installed by default.

Video/Screenshot link (optional):

![](https://image.prntscr.com/image/maJl2iJkRC2TsI3fghPrlQ.png)

![](https://image.prntscr.com/image/LWUwsEpXRDi41w2qfk2fPA.png)

**Comment by sswapnesh** [comment]
Warning should be managed like this

`You should install the mrp_byproduct module if you want to manage extra products on BoMs !'`
[https://github.com/odoo/odoo/blob/11.0/addons/mrp/models/mrp_bom.py#L218](https://github.com/odoo/odoo/blob/11.0/addons/mrp/models/mrp_bom.py#L218)
or 
RedirectWarning type Warning with Valid message and "Cancel Journal Entries" module action.

**Comment by sswapnesh** [comment]
@qdp-odoo Could you please check this?

**Comment by qdp-odoo** [comment]
feedback noted (cc @lap-odoo ). 

On the other hand, this is not a critical failure so we'll be closing this issue for the sake of Clarity.

Thanks for reporting

**Comment by sswapnesh** [comment]
Indeed, It is Possible Improvement.

**Comment by sswapnesh** [comment]
Hello @qdp-odoo 

> feedback noted (cc @lap-odoo ).


May I ask you for update if any ?

**Comment by qdp-odoo** [comment]
nothing new, yet. That might be improved for v13... cc @avw-odoo

**Comment by qdp-odoo** [comment]
well actually, I'm lying... our vision is to make the whole accounting editable/cancellable by default, and restrict it only when a lock date exists. 

We've already made a step towards that in saas-12.3, so that's already a fragment of answer, although not really related to the error message or the account_cancel module

**Comment by sswapnesh** [comment]
Does it means we won't need  `account_cancel` to allow cancelling Entries in future versions ?

**Comment by qdp-odoo** [comment]
hopefully :-)
