### ISSUE TITLE
[ASK] Ubuntu 16.04 安装Odoo10 连接数据库失败

### ISSUE THREAD

**Issue by XiaoDaJun** [odoo/odoo#22409]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by XiaoDaJun** [comment]
如题，参考文档《odoo-10-中文开发指南-更新至第五章》中的操作，在Ubuntu 16.04版以odoo用户登录，前面安装各种依赖文件、从GitHub下载源码等步骤都正常，只有在最后启动服务之前，连接数据库的步骤发生报错，如下，请教各位大神指点：
录入指令如下：./odoo/setup/setup_dev.py setup_pg
收到报错信息：createuser:无法联接到数据库 postgres: 无法联接到服务器：没有那个文件或目录
                                    服务器是否在本地运行并且在Unix域套接字“/var/run/postgresql/.s.PGSQL.5432”上准备接受联接？

**Comment by elicoidal** [comment]
If you want to get some help from this repo, you'd better write English. Otherwise you should contact the Chinese community

**Comment by Yenthe666** [comment]
Closing as there has been no further feedback/info.
