### ISSUE TITLE
Calender open fixed position not move while scrolling top to bottom or vice versa

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#2240]
Sales  » Customer  » Create/Edit  » Accounting tab » Latest Full Reconciliation Date Field click on this field  » Calender open

Now Scroll outside the calender calender can't scroll it's position should be fixed. Effected in Master.
![calender_scroll](https://cloud.githubusercontent.com/assets/7599891/4182190/e640dda0-3729-11e4-9ab0-2f548e128c96.png)

**Comment by Yenthe666** [comment]
Hi @imjaypatel,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
