### ISSUE TITLE
[10.0] Could not remove Image from Email template from Configuration

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22407]
Impacted versions: 10.0

Steps to reproduce: Performed on [Runbot.](http://295680-10-0-ae6037.runbot13.odoo.com/web?debug#id=36&view_type=form&model=mail.template&menu_id=142&action=169) --> Open Email template --> Try to remove image from Email content

Current behavior: Trackback on Screen

![](https://image.prntscr.com/image/e7bvwTXnQOiFHGYLkM3CxQ.png)

On Backspace:

![](https://image.prntscr.com/image/CpUpgHziR7CU5NFBhwtWxA.png)

On Delete:

![](https://image.prntscr.com/image/RvMuRNGYQQ_ak-LXsp4PDg.png)

Expected behavior: No trackback should be there.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks a lot for your bug report.
This is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/35209900-5603f270-ff50-11e7-964f-9252c3e90ec0.png)

@ged-odoo can you let somebody have a look? (CC @qsm-odoo)

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Dear @sswapnesh,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
It seems working well on 13.

**Comment by Yenthe666** [comment]
Good, thanks for the feedback.
