### ISSUE TITLE
[11.0e] Yodlee Bank Feed Sync Not Working

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#22412]
<h1>Enterprise Support Ticket #:</h1>
806792
<h1>Impacted versions:</h1>
<ul>
<li>9.0e</li>
<li>10.0e</li>
<li>11.0e</li>
</ul>
<h1>Steps to reproduce:</h1>
<ul>
<li>In Odoo 11.0e, go to: Accounting > Configuration > Bank Accounts</li>
<li>Enter Account Name as Bank Account Name, Account Number, as Bank Account Number, Bank (setup HSBC bank with BIC in Odoo), Set Bank Statements selection as 'Bank Syncronization'</li>
<li>Click 'Configure' button</li>
<li>Add a new bank to the system > Search HSBC</li>
<li>Select Name: "HSBC Bank", Country Code: "HK"</li>
<li>Click 'Choose This One'</li>
<li>Enter Username: (my HSBC online banking username here)</li>
<li>Enter Password: (my HSBC online banking password here)</li>
<li>Enter Second Password: (my HSBC online banking security device code used for 2FA on my bank account)</li>
<li>"Please wait while we are updating your account... This process can take several minutes..."</li>
<li>Odoo Server Error: "Problem Updating Account(403):We're sorry, there was a technical problem updating your account. This kind of error is usually resolved in a few days. Please try again later."</li>
</ul>
<h1>Current behaviour:</h1>
<ul>
<li>Odoo Server Error: "Problem Updating Account(403):We're sorry, there was a technical problem updating your account. This kind of error is usually resolved in a few days. Please try again later."</li>
</ul>
<h1>Expected behaviour:</h1>
<ul>
<li>Authenticates with my bank account and allows online sync.</li>
</ul>
<h1>Video/Screenshot link (optional):</h1>
Here's the error message for HSBC Bank (HK):<br/>
<img src="https://user-images.githubusercontent.com/2337666/35202616-b12345f8-ff5e-11e7-81a0-bd671ad33420.png"/>

Here's the error message for Hang Seng Bank, (HK):<br/>
<img src="https://user-images.githubusercontent.com/2337666/35202641-d0bd91fc-ff5e-11e7-9c05-c5f6078888cd.png"/>

Here's the error message for HSBC Commercial (HK):<br/>
<img src="https://user-images.githubusercontent.com/2337666/35202670-f378e674-ff5e-11e7-8e04-447b788f52a5.png"/>

<h1>Further Information:</h1>
Here's what I can find related to the error codes i've mentioned above.<br/>
<h3>402 Error:</h3>
**402 (Credential verification required)**<br/>
Errors of this variety generally mean that the banking credentials have been entered incorrectly. Enter your credentials again very carefully, making sure you have included all the correct capitalisations, special characters, etc.

If you are certain that the entered credentials are correct, make sure that you're also able to log in with the same details at our supported URL.

Check if the login process or your online banking website has changed - there may be a new URL, or a new layout to the website which is causing the error.

**I am able to login with the URL provided, however the login in Odoo is not working.**

<h3>403 Error:</h3>
**401, 403, 412, 413, 415 (Problem updating account)**<br/>
These are often temporary (~24 hours) errors which will disappear if you wait for 5-10 minutes and then try syncing the bank feed again.

**I have been retrying over the course of approximately one week now with no success.**

<h3>507 Error:</h3>
**507 (Beta feed)**<br/>
This bank feed is still in development by our bank feed provider. When constructing a new bank feed, it is put through a beta test stage, during which users will probably not be able to make a successful connection.

**Comment by lukebranch** [comment]
@Yenthe666 @csnauwaert,

Are there any special deployment requirements with Nginx, etc. for using Odoo with Yodlee?

For some reason I am unable to get bank feeds working.

**Comment by lukebranch** [comment]
Further to my above comments there is an issue with one popular Hong Kong bank in particular:<br/>

Hang Seng Bank - the URL provided links to the personal Hang Seng Bank bank login. 

Hong Kong companies will generally use the 'Business e-banking' login which can be found at the following URL:<br/>
<a href="https://ebusiness.hangseng.com/1/2/">https://ebusiness.hangseng.com/1/2/</a>

In Odoo the Yodlee feed provided is for the personal e-banking login which can be found here:<br/>
<a href="https://e-banking.hangseng.com/1/2/">https://e-banking.hangseng.com/1/2/</a>

Should I get in touch with Yodlee directly, or Odoo Enterprise Support regarding this particular point?

**Comment by lukebranch** [comment]
Further to my comment here:
https://github.com/odoo/odoo/issues/22412#issuecomment-359325463

Bank of China [HK] login URL is here:
https://cib.bochk.com/login/cib_login012_e.jsp

**Comment by lukebranch** [comment]
Hi All,

Does anyone have a direct email address for anyone at Yodlee? I have tried every channel of communication available (Facebook messages, Emails to their contact form, etc.), and have not received a single reply for months on end.

**Comment by qdp-odoo** [comment]
this kind of issues needs to be dig case by case, as it is often (not to say every time) a problem located in the yodlee service. For this reason, I'm closing the issue

Please contact the support of odoo (https://www.odoo.com/help) if you still experience issues with your syncronization.

**Comment by Yenthe666** [comment]
@qdp-odoo there is actually a ticket at 806792 or am I missing something?

**Comment by qdp-odoo** [comment]
Indeed, and the ticket has been closed on the 1st of February :-)

**Comment by Yenthe666** [comment]
Gotcha. 😉
