### ISSUE TITLE
[11ce] field project_time_mode_id not set in multi company environment

### ISSUE THREAD

**Issue by ThijsvOers** [odoo/odoo#22422]
Impacted versions: 11 community edition. 

Steps to reproduce:
Create a new company A, connect user B to that company (on the employer menu), then
write a time sheet line in company A for user B on a project. 

Current behavior:
The field Unit of measure of the time sheet line (in this case 'hours') is empty. As the UoM is empty, invoicing the time sheet line is not possible. 

Expected behavior: The UoM should be filled on the time sheet line. In the first (automatically created) company this field is set.
The issue is that field project_time_mode_id is not set for a new company which is created in a multi company environment. 

FYI: This issue does not happen in version 10.

**Comment by astirpe** [comment]
I confirm this issue.

**Causes**
The field `project_time_mode_id` is defined in module `project` and used by module `sale_timesheet`. In a multicompany environment here is what happens:

- When creating a new company, the value of `project_time_mode_id` is not set (indeed there is not any default value defined).
- There is no way to set a value for that field. In V10 it was possible to set that value by the `project.config.settings` form, but in V11 that field is not available in the view. Probably it was forgotten while porting the configuration views from V10 to V11.


**Temporary workaround**
A Customer of us uses a multicompany environment and is experiencing this issue. We temporarily added `project_time_mode_id` in the company form. By setting that field for each of the companies, the functional problem described by @ThijsvOers does not occur anymore.


Anyway this is a very annoying bug, that was costing time to be discovered. I hope you can fix it soon.

**Comment by jem-odoo** [comment]
This has been fixed at https://github.com/odoo/odoo/commit/eaa73beaaab3fd09198f915d53902563b73f404d
Please update your code if required ;)
Regards.
