### ISSUE TITLE
404 page not found does not respect HTTP status

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#22438]
**Impacted versions:** 11

**Steps to reproduce:**

Go on runbot, open a v11 and access a non-existing page, like `/page/foo`

**Current behavior:**

HTTP STATUS = 200

**Expected behavior:**

HTTP STATUS = 404

**Video/Screenshot link (optional):**

**v11:**
![image](https://user-images.githubusercontent.com/347149/35233411-635661a8-ff9e-11e7-882a-f5b5d531e6e7.png)

**v10:**
![image](https://user-images.githubusercontent.com/347149/35233415-695e766c-ff9e-11e7-9966-dcacd317824d.png)

**Comment by lasley** [comment]
IMO this is a fairly high priority issue - 404s returning 200s will absolutely wreck a site's SEO on a long term basis.

**Comment by Yenthe666** [comment]
Yuuup.
@JKE-be or @mart-e can one of you check?

**Comment by mart-e** [comment]
This is definitely something we can improve but not an high priority IMHO

**Comment by Yenthe666** [comment]
@mart-e whenever it would be changed it would also be neat to have a slightly layouted 404 page too. This one is really basic and not sexy. (no hate)

**Comment by simahawk** [comment]
@mart-e "improve"? :open_mouth: Seriously?
Sorry but... **it's broken**. And it's clearly a regression since it used to work.

**Comment by JKE-be** [comment]
Yes, don't worry, we will fix it ASAP
