### ISSUE TITLE
odoo 11 - cannot upadte apps list

### ISSUE THREAD

**Issue by almustafago** [odoo/odoo#22431]
Impacted versions: odoo v 11

Steps to reproduce: after activate developer mode i click on update apps list ,, but no response

Current behavior:
work under odoo bitnami cloud
Expected behavior: there is bug in image 

Video/Screenshot link (optional):
![display](https://user-images.githubusercontent.com/15360515/35223683-5bea9b9c-ff93-11e7-8426-651ed39d8339.PNG)

**Comment by sswapnesh** [comment]
Hello @almustafago 
Looks like some python Library import error. 
Could you please share server log?

**Comment by almustafago** [comment]
ok , now i am trying to update sale model but it gives me connection lost , i using odoo bitnami v 11 in google cloud ,, so how can i update model using command line

**Comment by lukebranch** [comment]
i'd say you're probably best off removing all custom modules from the addons_path and trying again. It's likely an import error from a custom module, or a missing dependency you haven't installed from Odoo core modules as (@)sswapnesh mentioned.

**Comment by almustafago** [comment]
now the problem in just on sale and invoice model i cannot make update in apps list , it loding and then give me 
![sale](https://user-images.githubusercontent.com/15360515/35906934-5ffe5702-0bfd-11e8-95d2-7d05b65eff0a.PNG)
 connection lost

**Comment by almustafago** [comment]
so how can i update sale model in command line ??

**Comment by sswapnesh** [comment]
We can close this now. 
What do you think @Yenthe666  ?

**Comment by Yenthe666** [comment]
Agreed. & you can update a module in the terminal with `./odoo-bin -u sale -c /etc/your-odoo-server.conf`

**Comment by sswapnesh** [comment]
I am not sure but `-u` should come after `-c` as `-u` requires database first. (Just Saying not Tried this)

**Comment by Yenthe666** [comment]
Other way around works just fine, I use it all the time 😄
