### ISSUE TITLE
Invoice Based on Delivered Quantity is not working in odoo 10 when check the Invoice delivered quantities

### ISSUE THREAD

**Issue by wiseguuy** [odoo/odoo#22448]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @wiseguuy 
I think you are Confused about Invoicing options at two different Places.

1: Sales --> Setting  --> Default Invoicing

![](https://image.prntscr.com/image/ddSkQDX9QlGS3q6qL43Npg.png)

The Default Invoicing method you have selected here will be used for all new Products. (Current configuration in all Products will remain Same.)

2: Product --> Invoicing

![](https://image.prntscr.com/image/A-uKTv2MRnS-MNSUeyI41Q.png)

This will be used for Actual Invoicing Process. (Changing Default Invoicing in Sales setting will not make any difference as for this Product it based on Delivered quantities.)

CC: @Yenthe666  Correct me If I am missing something here.

**Comment by wiseguuy** [comment]
Yes, I got it, Yenthee. Sorry for missing the configuration at the Product.

**Comment by Yenthe666** [comment]
That is indeed correct @sswapnesh and thanks for the answer!
@wiseguuy no problem, happy you've got it working now. Best of luck.
