### ISSUE TITLE
[10.0] website_sale: Show product quantity as integer in order confirmation

### ISSUE THREAD

**Issue by MTantin** [odoo/odoo#22443]
## Current behavior
Currently, in Odoo 10.0, with website_sale module installed, the quantity behavior is not the same in the full workflow for frontend templates. To reproduce this workflow, you just have to buy some demo products on website shop.

For example: in cart_lines template, we show quantity as integer
```html
<input type="text" class="js_quantity form-control quantity" t-att-data-line-id="line.id" t-att-data-product-id="line.product_id.id" t-att-value="int(line.product_uom_qty)" />
```
![image](https://user-images.githubusercontent.com/4457345/35264533-693a0b40-001d-11e8-95e9-33f49967991f.png)

Some lines down, in cart_popover template, again as integer:
```html
<small>Qty: <t t-esc="int(line.product_uom_qty)" /></small>
```
![image](https://user-images.githubusercontent.com/4457345/35264562-895e686c-001d-11e8-92d0-69e8563c7e68.png)

In payment template, no integer parsing but called as "t-esc":
```html
<div t-esc="line.product_uom_qty" />
```
![image](https://user-images.githubusercontent.com/4457345/35264594-a52e2e74-001d-11e8-95af-7d2f41a8f2d2.png)

And finally in confirmation template, no integer parsing but called as "t-field":
```html
<div id="quote_qty">
    <span t-field="line.product_uom_qty"/>
    <span t-field="line.product_uom"/>
</div>
```
![image](https://user-images.githubusercontent.com/4457345/35264731-1da66830-001e-11e8-8a91-0e591435f970.png)

The decimal precision of UOM (Unit of Measure) isn't used at any time.
The last template finished on the worst displaying with quantity as float with 3 digits after coma.
I tried to edit UOM of my product tested to reduce number of precision:
![image](https://user-images.githubusercontent.com/4457345/35265082-61de95d0-001f-11e8-8e46-4e635fb80035.png)
But nothing changed after that. Always 3 digits after coma in my order confirmation

## Expected behavior
The fast patch could be to apply the same parsing (as int) in the last template as first ones.
We can check value of quantity for more security:
```html
<div id="quote_qty">
    <span t-if="line.product_uom_qty == int(line.product_uom_qty)" t-field="line.product_uom_qty" t-options='{"widget": "int"}'/>
    <span t-if="line.product_uom_qty != int(line.product_uom_qty)" t-field="line.product_uom_qty" t-options='{"widget": "float"}'/>
    <span t-field="line.product_uom"/>
</div>
```
![image](https://user-images.githubusercontent.com/4457345/35264675-f3669c34-001d-11e8-8f94-7de5aa24ee3e.png)
 
What do you think about this patch? And about using the decimal precision of UOM in template?

**Comment by JKE-be** [comment]
We avoid to change the dom in the stable branch, so your solution cannot be applied.

We will probably add int in confirm an order to be coherent with other screens.
And improve it in master to manage float display (code allow float already).

Thanks for the feedback.

**Comment by JKE-be** [comment]
Landed in 10: https://github.com/odoo/odoo/commit/c9edca7896e3096289936f5399a82f08a59b60ce

Thanks for suggestion.
