### ISSUE TITLE
[11.0] Missing account.journal Accounting Dashboard

### ISSUE THREAD

**Issue by xabispacebiker** [odoo/odoo#22445]
Impacted versions: 11

Steps to reproduce: Fresh install

Current behavior: missing Accounting Dashboard

Expected behavior: Link to display the Accounting Dashboard

Video/Screenshot link (optional):

Hello,

On a fresh OCA 11 installation I am missing the Accounting Dashboard link. When the initial action for the user is set to Accounting Dashboard, then the user can access it but there is no link available form the menus. Is there any option to activate it or am i missing something?

Thanks in advance

**Comment by ThijsvOers** [comment]
Hi xabispacebiker,
If you activate the developer mode (under settings), and then go to a user, you will see that there is an option 'show full accounting features'.  Activate this option and you will see the dashboard, the link is also visible.

![afbeelding](https://user-images.githubusercontent.com/30256071/35443130-3cf9a704-02aa-11e8-9521-8ae73514e74d.png)

**Comment by xabispacebiker** [comment]
That worked, thanks!
