### ISSUE TITLE
[10.0] IBAN check is not checking anything

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#22458]
Impacted versions:

10 and 11 at least

Steps to reproduce:

Create a bank account with an error in the account number. Generate a SEPA file to execute payments.

Current behavior:

Everything run smoothly without error or warning raised despite the fact the IBAN in the SEPA file is wrong. 

The account type is set to BBA but nothing prevents the wrong IBAN to be used in the SEPA file.

See https://github.com/odoo/odoo/blob/9.0/addons/base_iban/base_iban.py#L53

Expected behavior:

An error or at least a warning shall be raised. The SEPA file should not be generated with non valid IBAN account numbers.

Video/Screenshot link (optional):

NA

**Comment by be-cloud-js** [comment]
I just write a PR in Odoo Enterprise https://github.com/odoo/enterprise/pull/1811

BUT I think the behavior of the account module is weird, it is very unclear when an IBAN is not valid, the acc_type is not shown in the interface.

At least a Warning should be a good idea, no ?

**Comment by lap-odoo** [comment]
@be-cloud-js : 

1) I agree that it was not clear if the bank account was a valid IBAN or not. This has already been improved in master (future SaaS 11.3). Now the acc_type is displayed in the interface. 

2) If you're using non-generic SEPA, you can use non-IBAN accounts. This is accepted by some banks. But in that case, there is normally an warning that is raised when generating the SEPA to inform you that some accounts are not valid IBAN. Here is what I have on runbot : https://drive.google.com/a/odoo.com/file/d/1BcFzEB5uYgeyucMn3SQz1_69qu8yZcsz/view?usp=drivesdk

**Comment by be-cloud-js** [comment]
Hi

Yes, in 11 I have a message... not in 10 (saas 15) though.

I would vote in favor of a system wide flag to prohibit non-generic SEPA, warning are good but having a strong notice is better. 

Thing is in Luxembourg, Multiline does not check either and you end up missing payments.

Best regards,

Jerome

**Comment by lap-odoo** [comment]
Hi, we'll think about this but I think that with the warnings + the acc_type visible, it should already be much easier to avoid mistakes. Regards, Laura

**Comment by intero-chz** [comment]
Hi Laura,

we already had two customers (Odoo 10) who had the same problem: Making mistakes on bank account numbers, which will only give errors on SEPA export (here it was the OCA SEPA modules).
A configuration (flag) which will activate a IBAN check with warning after number "onchange", would be very nice.

Would be interesting, how other partners think about the topic.

Best Regards,
Christian
