### ISSUE TITLE
TypeError: content_common() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by dhimasya** [odoo/odoo#22465]
Impacted versions: 
10

Steps to reproduce:
```python
file_url = '/web/content/?model=%s&field=file_binary&filename_field=file_name&download=true&id=%s' % ('purchase.return.wizard', self.id)
return {
    'type': 'ir.actions.act_url',
    'url': file_url,
}
```

Current behavior: 
500 internal server error
TypeError: content_common() got an unexpected keyword argument 'debug'

Expected behavior:
file binary downloaded

Note:
i try to switch the debug mode off, issue error solved, but why it unable to download when in debug mode?

Video/Screenshot link (optional):
![screenshot from 2018-01-24 10-04-27](https://user-images.githubusercontent.com/34560775/35312434-528221bc-00b3-11e8-983b-8179672ed792.png)

**Comment by sswapnesh** [comment]
Hello @dhimasya 
I can reproduce it on [Runbot](http://297213-10-0-962098.runbot14.odoo.com) and Confirm this Issue.
However, I can reproduce it when it is `web?debug=1#` only,  `web?debug#` seems working fine.
CC: @Yenthe666

**Comment by Yenthe666** [comment]
Hey @sswapnesh,

Could you make a little video / screenshots or info on how to reproduce it? I wasn't able to trigger it right away.
@KangOl and @odony does one of you have any idea?

**Comment by sswapnesh** [comment]
Hello @Yenthe666 
Same Piece of code is used here: [https://github.com/odoo/odoo/blob/10.0/addons/l10n_fr_fec/wizard/account_fr_fec.py#L353](https://github.com/odoo/odoo/blob/10.0/addons/l10n_fr_fec/wizard/account_fr_fec.py#L353)

So I Installed that module (`l10n_fr_fec`) in local and Triggered that method.
![](https://image.prntscr.com/image/7u7LxVjxTACBKmw2WUSiiQ.png)

Sorry, I can not Reproduce it on runbot as I can not validate FR Vat number. Even I am using Same as expected Vat number Format. (Not Sure If I should create Issue for this or not.)

![](https://image.prntscr.com/image/UaQuaeXxR6O-v7CYU9b5xw.png)

**Comment by dhimasya** [comment]
@sswapnesh in my case, my url is web?debug#
still, it got error code 500 and same error log.
![image](https://user-images.githubusercontent.com/34560775/35438196-791071b8-028d-11e8-9fb4-f5bf57e00cb1.png)

**Comment by devang-dreambits** [comment]
Any solution/workaround of this issue? We are also facing a similar issue...

**Comment by dhimasya** [comment]
> Any solution/workaround of this issue? We are also facing a similar issue...

don't know, maybe they still work on this

**Comment by Yenthe666** [comment]
Dear @dhimasya,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
It was there on v11 too when I tested this.

**Comment by Yenthe666** [comment]
Could you recheck to be sure please?

**Comment by sswapnesh** [comment]
> Could you recheck to be sure please?

Works well in v13 (With this as reference https://github.com/odoo/odoo/blob/10.0/addons/l10n_fr_fec/wizard/account_fr_fec.py#L355)

**Comment by Yenthe666** [comment]
Thanks :)
