### ISSUE TITLE
Adding Security Group in Submenu Throws Error in (v11C/E).

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#22468]
Impacted versions:

 > V11 Community and Enterprise both.(V11C/E)

Steps to reproduce:

 > Menu Settings > User interface > Menuitems > Open any Menu having submenus (Childs) >
 > Now open any submenu >  Add access rights (1st Tab) > Add any group here  And Click on 'Save'.
  
Current behavior:
 > It's even not allowing to save a record.

Expected behavior:
 > It should allow to do save and apply security group accordingly.

Video/Screenshot link (optional):
> Screenshot
![employees odoo](https://user-images.githubusercontent.com/35560490/35316734-3ac86130-00f9-11e8-9fd5-688c1bd1f4ea.png)

>  Video
https://youtu.be/6tSoh6A8oic

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for the bug report.
I can confirm that this is a bug. @ged-odoo could one of the guys of your team have a look?
![image](https://user-images.githubusercontent.com/6352350/35331827-07dae864-0109-11e8-9bec-6a57af84e4db.png)

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @kebeclibre,

Thanks a lot for the fix.
