### ISSUE TITLE
'external_dependencies' not documented in manifest

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#22471]
Impacted versions:
8.0 -> 11.0
Steps to reproduce:

The documentation of __openerp__.py / __manifest__.py doesn't include anymore 'external_dependencies' key.
https://github.com/odoo/odoo/blob/11.0/doc/reference/module.rst

Current behavior:

Expected behavior:
The 'external_dependencies'  to be documented.
If ok i can create a PR.
Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Thanks for the report, there's actually many more undocumented __openerp__/__manifest__ features, I'll try to update it :^)

**Comment by Yenthe666** [comment]
Nice, extra documentation! Good job @Elkasitu

**Comment by Elkasitu** [comment]
Done in aae4d8a
