### ISSUE TITLE
[11.0][BUG]stock.move Poor performance when product have serial number

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#22476]
Impacted versions:
11.0
Steps to reproduce:

1. product A have serial number 
2.I purchase A ,quantity 1000, i confirm purchase order ,It cost my some minutes create 1000 line stock.move.line.(Poor performance)
3.in stock.picking, I input a serial number for product A , odoo cost some minutes to check serial number (Poor performance).
i must wait some minutes to input next serial number

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
On which commit are you? We removed the constraints and added onchanges in https://github.com/odoo/odoo/commit/6ef460b6a7f0ec46e009da0b339dc676bc850b89#diff-fc6cef81fac5ca3c30afb09ccb60ff4c as, before this patch, the validation had poor performance (around 17 minutes to receive 5000 serial numbers, now it's around 4).

How may serial number do you have to encode? How many move lines?

**Comment by sle-odoo** [comment]
I just checked and the creation of 1000 move lines is less than 10 seconds. The onchanges are indeed slowish but they are around 5 seconds max. The view is stuck a little more longer but's because of the o2m re-rendering in the webclient, a problem we know about (@ged-odoo).

You have probably an issue in your installation if it's taking minutes at your end. Is your code up to date? Do you have any custom modules installed?

**Comment by sum1201** [comment]
my code had update to date.
I create a new database ,only install purchase, inventory  module.
my test result:

1. I create a prouct  A have serial number.
2. I create a purchase order ,order line have a line ,product is A ,quantity : 3000. I cost one minute to confirm order.
3.I go to stock picking screen in tree view, i cost 0.5 minute  from tree view to form view.
4. in stock picking form view, I cost 20 million  open stock.move.line view.
5.i cost 0.5 minutes input a serial number to next input.

please help me @ged-odoo @sle-odoo

**Comment by sum1201** [comment]
if I production product A  10000000 piceces, odoo will One-time establishment of 1000 records...
My God!!!!
Seriously unreasonable design

**Comment by sum1201** [comment]
enterprise Issue 807,588

**Comment by wangshan0901** [comment]
???有处理吗

**Comment by sle-odoo** [comment]
closing since the linked opw is closed
