### ISSUE TITLE
module openacademy: Unmet dependencies: web_gantt

### ISSUE THREAD

**Issue by huoxy** [odoo/odoo#22478]
Impacted versions:
```
(odoo-venv) huoxy@madeonearch ~/odoo> ./odoo-bin --version
Odoo Server 12.0alpha1
(odoo-venv) huoxy@madeonearch ~/odoo>
```

Steps to reproduce:
According step-by-step exercise of:
https://www.odoo.com/documentation/11.0/howtos/backend.html#gantt

Current behavior:
![image](https://user-images.githubusercontent.com/1237528/35324956-4abbe2ae-012d-11e8-9cf5-6991eac1c9d8.png)

2018-01-24 09:29:21,053 3969 ERROR odoo odoo.modules.graph: module openacademy: Unmet dependencies: web_gantt

Expected behavior:
1. web_gantt removed?
2. another choice to work properly?

**Comment by huoxy** [comment]
Well, When I removed the `color` attribute, It works.

**Comment by huoxy** [comment]
I don't know if this due to `the doc is for 11.0` and my HEAD is `12.0alpha`.

if it is, please provide the latest doc for the latest HEAD,
else please fix the exercise... thanks, it takes me a long time to find the reason...

**Comment by huoxy** [comment]
If already has plan to fix this, please close this issue directly.

**Comment by huoxy** [comment]
But there is still no Gantt Icon(after upgrading):

![image](https://user-images.githubusercontent.com/1237528/35327260-22ab0bc6-0134-11e8-9afd-61cc5cd8fe2a.png)

**Comment by Yenthe666** [comment]
@huoxy in short: you're using documentation for V11 but you're developing against an alpha (master) version. The alpha version should never be used - in this case you're trying this on the upcoming V12 which will be released in october.

**Comment by huoxy** [comment]
@Yenthe666 OK, Thanks for explanation, I will try to checkout repo to v11 and test again.

**Comment by Yenthe666** [comment]
Best of luck - don't hesitate to post back if you face those issues there too (but I'm quite sure you won't 😉 )

**Comment by pedrobaeza** [comment]
Well, certainly `web_gantt` module doesn't exist anymore in community, so the example should be updated with that detail.

**Comment by Yenthe666** [comment]
@pedrobaeza true, there should be atleast a little warning in the docs.
@mart-e or @Elkasitu for you guys!

**Comment by huoxy** [comment]
@Yenthe666 A pity that there is still errors... :
```web.assets_backend.js:473 View type 'gantt' is not present in the view registry.```

With `<gantt/>` and `view_mode`  declared in action in views.xml:
```xml
    <record model="ir.ui.view" id="session_gantt_view">
      <field name="name">session.gantt</field>
      <field name="model">openacademy.session</field>
      <field name="arch" type="xml">
        <gantt string="Session Gantt" date_start="start_date" date_stop="end_date" default_group_by='instructor_id'></gantt>
      </field>
    </record>

    <record model="ir.actions.act_window" id="session_list_action">
      <field name="name">Sessions</field>
      <field name="res_model">openacademy.session</field>
      <field name="view_mode">tree,form,calendar,gantt</field>
    </record>
```

Version:
```
(odoo-venv) huoxy@madeonearch ~> odoo --version
Odoo Server 11.0-20180124
(odoo-venv) huoxy@madeonearch ~>
```

With `depends=['base', 'web_gantt']`, I try to upgrade(odoo -u) openacademy in cli, It said:
```
ERROR odoo odoo.modules.graph: module openacademy: Unmet dependencies: web_gantt
```

With `depends=['base']`(without web_gantt), Odoo can start properly, but Chrome console still shows: `View type 'gantt' is not present in the view registry.`

**Comment by Yenthe666** [comment]
@huoxy, this is a community version right? This will only work on the enterprise version I'm afraid.

**Comment by huoxy** [comment]
@Yenthe666 Yes... I am testing community version, well, I see.

**Comment by mart-e** [comment]
I already added a warning some time ago b1a3bb7d9adff664554d7ba63c1513c318057160
https://www.odoo.com/documentation/11.0/howtos/backend.html#gantt

> The gantt view requires the web_gantt module which is present in the enterprise edition version.

**Comment by Soyuz-Tec** [comment]
Hi There, can anyone help with odoo 12v latest download link

**Comment by mart-e** [comment]
@Soyuz-Tec please do not hijack existing threads but create a new one with your questions.
The v12 is not yet released, so there is no download link yet. It will be released in october
