### ISSUE TITLE
Create Product from Many2one field create and edit option having bug.

### ISSUE THREAD

**Issue by MainakHaripiyas** [odoo/odoo#22480]
Impacted versions: 10.0

Steps to reproduce:
1. Go to Purchase Order
2. Click on add an item from order line
3. Try to create new product 
4. Add 2 variant attributes
5. Remove last added variant with "X" button
6. Click on Save

Current behavior:
Product didn't save on to the PO line

Expected behavior:
Product should be store to PO line 

Video/Screenshot link (optional):
https://drive.google.com/open?id=17WhkqEdrp37Y-DhMhpBXqP1c2UBUMhf7

**Comment by sswapnesh** [comment]
Hello @MainakHaripiyas 
I can Reproduce this Issue on Runbot.
It is not Related to PO only, It has Same behavior where `product_id` is used in o2m field with tree view.

In Sales Order it seems working fine as it open form View.

![](https://image.prntscr.com/image/NB1N0JjeQrqQi8W8xYaj-Q.png)

 I can reproduce same in PO lines/Bom Lines where `product_id` is added in tree view.

**Comment by Yenthe666** [comment]
Dear @MainakHaripiyas,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
