### ISSUE TITLE
Payroll report does not print header when company_id is not set

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#22497]
**Impacted versions:**
11.0

**Steps to reproduce:**
with multi-company configuration in True -> in payroll print a payslip without company

**Current behavior:**
the header is not printed

**Expected behavior:**
Print the report with header

**Video/Screenshot link (optional):**
[video](https://youtu.be/yPUWni5C2bM)

**Comment by Yenthe666** [comment]
Hi @GavyMG,

Thank you for the bug report and the video!
This indeed looks like a bug.
@qdp-odoo and @tde-banana-odoo you two seem to be have the last ones working on this module.

Regards,
Yenthe

**Comment by kebeclibre** [comment]
hey,

There is an opw on our side, I'll just copy paste what I answered:

This issue cannot be considered as a bug.
Indeed, in Odoo logic every report is tied to a company. For a payroll, an employee is employed by a particular company and it quite doesn't make sense to have free electron that wouldn't.

Technically, even if it were understandable to have such free electron, what would be the header (or footer) ? a default one -- with what address ? or the first company's ?

If you can come up with a use case that justifies such behavior, we will be glad to hear it and think about its management in a future version
