### ISSUE TITLE
[11.0] mass_mailing: field as readonly to avoid write ir.model

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#22496]
Impacted versions:
11.0

Steps to reproduce:
1. [Assign permission to Mass Mailing to a demo (or any not admin) user](https://docs.google.com/uc?id=1wfK_E3iW436mcn_hF0rWpxrf0lsMC0qS)
2. Log in with demo user.
3. Go to Email Marketing and try to create a Mass Mailing

Current behavior:
Access denied when try to create a mass mailing with a not admin user

Expected behavior:
Allow create a mass mailing with a not admin user

Video/Screenshot link (optional):
![img](https://docs.google.com/uc?id=1mz2xTuDeDQDA-HmvDL6nr3y_b2jaVBjy)

Proposed solution:
The field `mailing_model_name` in Mass Mailing model should be readonly
https://github.com/odoo/odoo/blob/11.0/addons/mass_mailing/models/mass_mailing.py#L335

**Comment by Yenthe666** [comment]
Hi @suniagajose,

Thanks a lot for the report.
I can confirm that this is a bit of a bug 😉 
@KangOl you're the last one that worked on the security rules. Can you have a look?

Regards,
Yenthe

**Comment by KangOl** [comment]
You're right, this field should be readonly.
