### ISSUE TITLE
[11.0] Translated string caused JavaScript error and images failed to load in kanban view

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#22506]
Impacted versions:
11.0c

Steps to reproduce:
1. For the string "Bytes,Kb,Mb,Gb,Tb,Pb,Eb,Zb,Yb" in https://github.com/odoo/odoo/blob/894229c26855fc177d223f7736ce5ffb2b773cde/addons/web/static/src/js/core/utils.js#L144-L152 , it is translated to "バイト、キロバイト、メガバイト、ギガバイト、テラバイト、ペタバイト、エクサバイト、ゼッタバイト、ヨッタバイト" in Japanese.
2. Update the translation of the string and change user's language into Japanese.
3. Access Product / Partners kanban view.

Current behavior:
1. Since the method separate the string into parts by comma, i.e. ",", while Japanese use "、" instead therefore the method cannot "cut" down the strings into parts
```
# The current unit variable that we got
> unit=string.split(',');
< ["バイト、キロバイト、メガバイト、ギガバイト、テラバイト、ペタバイト、エクサバイト、ゼッタバイト、ヨッタバイト"]

# The expected variable that should be
> unit=string.split(',');
< ["Bytes", "Kb", "Mb", "Gb", "Tb", "Pb", "Eb", "Zb", "Yb"]
```
This will cause error when the JavaScript tries to execute `unit[1].trim()` since `unit[1]` is `undefined`.

2. If we manually change the translation into a format that allows the method to process, i.e. "バイト,キロバイト,メガバイト,ギガバイト,テラバイト,ペタバイト,エクサバイト,ゼッタバイト,ヨッタバイト"

The method will execute flawlessly, however the images in the Kanban view cannot be load, 
![image](https://user-images.githubusercontent.com/27185427/35374821-767c2644-01df-11e8-866d-a6fe30b36238.png)

I have further checked with Developer Tool, it seems that the image's URL generated is strange and contains some Japanese characters.
![image](https://user-images.githubusercontent.com/27185427/35375017-5b6d0962-01e0-11e8-885b-a769d7e6aa4c.png)

**Comment by mart-e** [comment]
Hello,

You are right regarding the bug report and analysis. It was already reported at #22519
