### ISSUE TITLE
Project Duplication Throwing irrelevant/Wrong Warning ! (Not allowing Duplication)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#22507]
Impacted versions:
Odoo V11E

Steps to reproduce:

Menu >Project > Create Project > Save > Try to duplicate it.

Current behavior:
 > Its not allowing to duplicate a Project and even throwing wrong warning to user !

Expected behavior:
 > Even Project is not containing any Single Task ,that's why it should allow to do duplication of Project in smooth manner.

Video/Screenshot link (optional):

1) Screenshot >
   
![test runbot odoo](https://user-images.githubusercontent.com/35560490/35375485-33d16668-01cd-11e8-8d85-df019b69da94.png)

2) Video >
 https://youtu.be/HFDdJUDLjCo

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for your report. In V10 this was indeed possible but it is no longer possible in V11. I believe that should be changed / fixed.
@mart-e could you have a look? Coming from
https://github.com/odoo/odoo/blob/894229c26855fc177d223f7736ce5ffb2b773cde/addons/hr_timesheet/models/project.py#L70-L71

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/3afe5b65089b92a0df6d3056f3f123457d7a677c
