### ISSUE TITLE
Bug when user image near 800ko

### ISSUE THREAD

**Issue by negstek** [odoo/odoo#22509]
Impacted versions: 11 

Steps to reproduce: try to add an image whith a size of 800 ko (jpg or png)

Current behavior: say connection lost, try to reconnect and never save changes

Expected behavior: a better error message about image size or a real record
Video/Screenshot link (optional):

**Comment by negstek** [comment]
resize image to 600ko  make it works

**Comment by Yenthe666** [comment]
Hi @negstek,

Thanks for the report.
Could you provide an example image to reproduce please?
Is the behaviour the same throughout the whole Odoo, no matter where you upload?

Regards,
Yenthe

**Comment by negstek** [comment]
![capture du 2017-10-25 09-39-25](https://user-images.githubusercontent.com/883536/35380409-72aa67b8-01b9-11e8-8532-727bd4f97e74.png)

just from settings/users

**Comment by Yenthe666** [comment]
Hi @negstek,

Thanks. Can you provide your example image please?

**Comment by negstek** [comment]
No it is a user image but when the size of the image is more than 800ko it does not work and when it is less than 700ko it works. This is a general comment so it is true for any image u take. Probably because of the column size where binary data from image is store in the database. But it is really bad that there is no control or limitation on the file upload and also no adapted error message

**Comment by negstek** [comment]
thx for support

**Comment by sswapnesh** [comment]
Hello @negstek 
I just tested same on [Runbot](http://297206-11-0-3afe5b.runbot9.odoo.com/web?debug#id=5&view_type=form&model=res.users&action=65) with Image Size 1.5 MB (15,08,257 bytes) and it has been added to User successfully.


![](https://image.prntscr.com/image/krHP_jlGQXqfBKJa_ojtLg.png)

**Comment by Yenthe666** [comment]
Yup, it works perfect at my end with a bigger file size too.

**Comment by sswapnesh** [comment]
Hello @negstek 
I have Reproduced the Same Issue on other Server (Latest v11) Where I was getting this error message in Console while uploading an image with 855 Kb.

`Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)`

![](https://image.prntscr.com/image/-NPCZl12TWGTP0aaqYf16Q.png)


I resolved it by adding `client_max_body_size 100M;` in my nginx Config.
CC: @Yenthe666

**Comment by negstek** [comment]
Oh great I had just resized my image but I will fix it now. Thank you very much for your help @sswapnesh .

**Comment by Yenthe666** [comment]
@negstek can you confirm that it fixes your issue and that you can continue now?

**Comment by negstek** [comment]
I Does not work on this project anymore, sorry.

**Comment by Linekio** [comment]
I'm now working on the negstek's project, I confirm that the sswapnesh's answer works fine !

**Comment by sswapnesh** [comment]
Glad that Issue is Solved.

**Comment by asiamatrix** [comment]
<img width="649" alt="screenhunter 607" src="https://user-images.githubusercontent.com/44358604/51441787-b2992880-1d03-11e9-8aa9-fddb2babf676.png">
I 'm facing same error.
