### ISSUE TITLE
[11.0] Contact image in contact list not showing

### ISSUE THREAD

**Issue by helpvits** [odoo/odoo#22519]
Impacted versions:11.0.1

# in contact cart all right

![photo_2018-01-25_15-35-52](https://user-images.githubusercontent.com/6968973/35388642-a72a17f0-01e5-11e8-802c-cd89e919a3bf.jpg)

`<img class="img img-responsive" border="1" height="90" name="image" src="http://192.168.1.118/web/image?model=res.partner&amp;id=16&amp;field=image_medium&amp;unique=25012018153203" width="90">`

# in contact list all images failed

![photo_2018-01-25_15-35-42](https://user-images.githubusercontent.com/6968973/35388681-cd1998c8-01e5-11e8-9349-60d36a57de09.jpg)

`<img modifiers="{}" src="data:image/png;base64,6.14 Кб">`

**Comment by Yenthe666** [comment]
Hi @helpvits,

Thanks a lot for your bug reports.
Can you reproduce this on the latest Odoo 11 or on an official test instance from Odoo (at runbot.odoo.com)?
It seems to work fine out of the box on the latest Odoo 11.

Regards,
Yenthe

**Comment by helpvits** [comment]
This bug in selected Russian langeage. And same problem in product list. And in Russian lang is bug with import images for products

**Comment by sswapnesh** [comment]
Hello @helpvits 

I have Performed same on [Runbot](http://297720-11-0-8ed757.runbot12.odoo.com/web#view_type=kanban&model=res.partner&action=93) and can confirm bug.
In Console:
`Failed to load resource: net::ERR_INVALID_URL  data:image/png;base64,5.95 %D0%9A%D0%B1`

Same Issues in Other Kanban views as well.


![](https://image.prntscr.com/image/qjLqfvhwTZSrzCEsT2BNwQ.png)



![](https://image.prntscr.com/image/cywQmIdiR1qB1Fu8i9pezw.png)

CC: @Yenthe666

**Comment by Yenthe666** [comment]
@mart-e language related!

**Comment by helpvits** [comment]
@Yenthe666 I have same problem in product list is "sale" and in "website"

**Comment by mart-e** [comment]
@ged-odoo funny one !

https://github.com/odoo/odoo/blob/63c39c74605a9458de4e7a8a2a2f3821e55843ba/addons/web/static/src/js/core/utils.js#L229-L233

Tries to detect it the content is base64 or vaguely a file size. This code does not match on a Russian (and probably other) file size like `"1.39 Кб"`

**Comment by helpvits** [comment]
where i can fix it?

**Comment by sergeiruzkiicode** [comment]
Will it be normal simply remove \w+ from regex? Or we need it for something?

**Comment by TimLai125** [comment]
@helpvits Hi, I have this issue in my Japanese environment as well. As a temporary workaround, you can simply find the translation record of "Bytes,Kb,Mb,Gb,Tb,Pb,Eb,Zb,Yb" and change translations to "Bytes,Kb,Mb,Gb,Tb,Pb,Eb,Zb,Yb" but not the language of Odoo.

**Comment by TimLai125** [comment]
Although I have posted in another issue, i.e. #22506 , other language that does not use "," as separator like Japanese will cause further error on here
https://github.com/odoo/odoo/blob/894229c26855fc177d223f7736ce5ffb2b773cde/addons/web/static/src/js/core/utils.js#L144-L152

**Comment by am2008** [comment]
Replace word detect pattern to your locale character set. Russian set example:
odoo/addons/web/static/src/js/core/utils.js:
```
    /**
     * @param {string} v
     * @returns {boolean}
     */
    is_bin_size: function (v) {
        // return (/^\d+(\.\d*)? \w+$/).test(v);
        return (/^\d+(\.\d*)? [а-яА-Я]+$/).test(v);
    },
```
