### ISSUE TITLE
[10.0] base_import : Date Format in import settings is mandatory

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#22512]
Impacted versions:

10.0

Steps to reproduce:

Try to import csv data with a date field (with common settings).

Current behavior:

Error :
`Column X contains incorrect values. Error in line 60: unconverted data remains: 1980-06-25`

Expected behavior:

Data well imported

The problem is on line :

https://github.com/odoo/odoo/blob/efd300156b8ae7dd768864b4078f9c89672b8703/addons/base_import/models/base_import.py#L626

the 'date_format' in options dict is always filled in (it contains '' in case of void setting value) and so 'user_format' is always equals to ''.

@JKE-be @nim-odoo

**Comment by rousseldenis** [comment]
Arf, I suppose @pedrobaeza and you have closing work in progress.

IMHO, as Odoo wants feedback (cfr OXP), these kind of bugs should have been verified in further versions before closing. That could avoid frustrations.

There was nobody who looked at this...

**Comment by pedrobaeza** [comment]
@rousseldenis checking that it's very costly. That's why @Yenthe666 ask the initial reporter to check if it's still happening. You know that our role then can only be ping again to involved people to try to get it solved.

**Comment by Yenthe666** [comment]
Yeah, I'm sorry but manually checking and testing every issue that is created against multiple versions is an impossible job. We've got ~1150 open issues and three active versions. That would mean ~3450 tests to check them all against all versions. If the author of the issue does the job for his own issue he only has to do it three times though. ;)

**Comment by rousseldenis** [comment]
Of course I understand. What I pointed more is the non acknowledgement on Odoo side on almost the two years period of this issue opened state. Thanks for the feedback and the great job!

**Comment by Yenthe666** [comment]
Yeah I know, I wish it went quite a bit smoother and better too :( Their focus is on enterprise tickets I'm afraid.

**Comment by JKE-be** [comment]
> "Their focus is on enterprise tickets I'm afraid."
not agree

Probably wrong tag, since it is not really framework team that will handle it.

You spot a problem in a module that's not really handled by a specific team, so except if you target one of the main committer or a cool people that have time... Nobody will catch it.

And yes, in v13 it has been already refactored and this code seems no more present.
