### ISSUE TITLE
[8.0] move out PHP code included on crm module

### ISSUE THREAD

**Issue by OSguard** [odoo/odoo#2252]
https://github.com/odoo/odoo/tree/8.0/addons/crm/scripts/php

should be removed

**Comment by Yenthe666** [comment]
Hi @OSguard,

The PHP scripts have been removed in 9.0 (and also in the master).
I bet a backport will never happen, there is no reason to at this point either, since its a stable version.
Closing this since the new versions no longer have the PHP code.

Regards,
Yenthe
