### ISSUE TITLE
wkhtmltopdf 12.4

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#22524]
Impacted versions: 11.0

Steps to reproduce:

Current behavior: dnot work qt version on the wkhtmltopdf

Expected behavior:  wkhtmltopdf = ['xvfb-run',_get_wkhtmltopdf_bin()] + command_args + files_command_args + paths + [pdf_report_path] at base/ir/ir_action_report.py - 387 row
apt-get install xvfb xauth
Video/Screenshot link (optional):

**Comment by gustavovalverde** [comment]
How did you installed it?

**Comment by rosenvladimirov** [comment]
https://wkhtmltopdf.org/downloads.html

**Comment by gustavovalverde** [comment]
Try with:

```
cd /usr/local/src
wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
ln -s -f /usr/local/src/wkhtmltox/bin/wkhtmlto* /usr/bin/
cd ~
chown -R [odoo-user]: /usr/local/src/wkhtmltox
chown -R [odoo-user]: /usr/bin/
```

As this is working just fine for me.

**Comment by sle-odoo** [comment]
Hi,
I'm closing the issue as only 0.12.1 is officially supported by Odoo. If you're having (or not) any issues with 0.12.4, it'll be helpful to report here, so we can think of supporting this one too.

Thank you

**Comment by gustavovalverde** [comment]
@sle-odoo, I've been using 0.12.4 since Odoo v11 launch, no problems so far and PDF generation is also faster. If you need help testing it, just let me know which kind of test you need to be done.

**Comment by sle-odoo** [comment]
@gustavovalverde especially the handling of the --dpi argument, but it doesn't look fixed according to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2156

**Comment by rosenvladimirov** [comment]
problem with wkhtmltox >12.2 come from 8.0 in 11.0 i fix only xvfb-run to start in virtual display
