### ISSUE TITLE
[10.0][11.0] Add Purchase Order field is always empty

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22526]
Impacted versions: v10e, v11e

Steps to reproduce:
1. Create on or more POs.
2. Validate the shipment.
3. Create a new bill (not from the POs).
4. Add the POs in the Add Purchase Order field.

Current behavior:
- The data from the POs is pulled but the field remains empty not showing to which POs it belongs to.

Expected behavior:
- Show the selected POs in the field.

Video/Screenshot link (optional):

************
This is important for users who generate lots of POs but receive a single Bill for many of the POs.

**Comment by pedrobaeza** [comment]
That's the intended behavior for adding more possible purchase orders. You have each reference on the invoice line itself.

**Comment by edsersolis** [comment]
@pedrobaeza that is true, however the POs could remain in a tags format in the mentioned field, if you have many lines in many POs it becomes quite a hassle to later identify these between the lines.

**Comment by lap-odoo** [comment]
Hello, 

I agree with Pedro, that's a possible improvement (not a bug). I've added this in our backlog to improve that for future versions. Thanks for reporting this.
