### ISSUE TITLE
[10.0] WYSIWYG editor - image remove button has no effect

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#22523]
Impacted versions:

Odoo 10.0
Tested on runbot on version edac5550ec4cf38236f54278c9f2e11a59c3ebbf

Tested on chrome 54.0.2840.59  and Firefox 58.0

Steps to reproduce:

Open email template "Invoice Notification Email" in edit mode and select Odoo logo then click on the "remove" bin icon.

Current behavior:

No effect.

Expected behavior:

Image is removed.

Video/Screenshot link (optional):

![2018-01-25-151257_925x454_scrot](https://user-images.githubusercontent.com/4158438/35392795-532e189c-01e3-11e8-83fe-7e876d560412.png)

**Comment by Yenthe666** [comment]
Hi @yvaucher,

Thanks a lot for your report.
I believe this was done on purpose as it contains the branding of Odoo but I'm not absolutely sure.
@qsm-odoo can you verify and/or give feedback?

Regards,
Yenthe

**Comment by yvaucher** [comment]
Thanks for the answer @Yenthe666 .

If it is to enforce the use of Odoo logo in emails it won't work. You can still change it with an other image.
![2018-01-25-155719_928x481_scrot](https://user-images.githubusercontent.com/4158438/35394656-940c5518-01e8-11e8-997f-f335384e2c81.png)

Plus, people can still edit the html itself.

**Comment by qsm-odoo** [comment]
Hello,
The bug has been solved in 9.0 with commit https://github.com/odoo/odoo/commit/ce51ad7e69dbc1415eaf5f2ae846bbe89a37f69b, it will be forward-ported in 10.0 in the upcoming days.

**Comment by yvaucher** [comment]
@qsm-odoo thanks for the patch
