### ISSUE TITLE
[10.0] Can't validate an inventory adjustment 

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22532]
### Impacted versions:
10.0

### Steps to reproduce:
Create an Inventory adjustment and set the location
Inventory of: 'All products'
Set quantities to 0
Validate

### Current behavior:
![image](https://user-images.githubusercontent.com/16890942/35423166-dbf21784-0222-11e8-9c0f-40a7ef3c481c.png)

In logs:
```pythons
odoo.sql_db: bad query: INSERT INTO "stock_move" ("id", "product_uom", "sequence", "product_uom_qty", "date", "location_id", "company_id", "priority", "to_refund_so", "qty", "weight_uom_id", "date_expected", "inventory_id", "partially_available", "propagate", "restrict_partner_id", "procure_method", "scrapped", "restrict_lot_id", "name", "product_id", "location_dest_id", "groud", "write_uid", "create_date", "write_date") VALUES(nextval('stock_move_id_seq'), 1, 10, '1', '2018-01-25 21:40:59', 15, 1, '1', false, 'confirmed', '1', 3, '2018-01-25 22:13:49', 16207, false, true, NULL, 'make, NULL, 'FV:Ajuste Inventario', 14945, NULL, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
```

### Expected behavior:
Validated inventory or better error message

**Comment by vcloud9ray** [comment]
Unable to replicate on Runbot

http://296300-10-0-238a8a.runbot14.odoo.com/web#id=54&view_type=form&model=stock.inventory&action=701&menu_id=490

![image](https://user-images.githubusercontent.com/31354495/35425585-a2e21c9e-0210-11e8-8902-870e92a5597b.png)

**Comment by gustavovalverde** [comment]
Were a bunch of products that (somehow) were created without a `property_stock_inventory/id`.

That was the real issue, I'll be monitoring to know if this can be replicated.
