### ISSUE TITLE
[11.0] No Hierachy in salary structure, its always open form view in editable mode

### ISSUE THREAD

**Issue by ajeetyv** [odoo/odoo#22536]
Impacted versions:
V11.0
Steps to reproduce:
Go to Payroll->Configuartion->Salary Structure Hierarchy
Current behavior:
Open Salary structure form view.
Expected behavior:
Open Salary structure Hierachy
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @ajeetyv 
Hierarchy has been removed from V11.
You can check related Issue #22304, #20203, 
CC: @Yenthe666

**Comment by ajeetyv** [comment]
is there any valid reason to remove hierarchy?

**Comment by sswapnesh** [comment]
Honestly I don't have any Idea about that. 
Better to ask @mart-e  or @sle-odoo.

**Comment by mart-e** [comment]
Hello,

Sorry but it has indeed been removed during a refactoring of our web client. It is no longer a feature we want to offer.
