### ISSUE TITLE
[11.0] External API - Report printing is not working in 11

### ISSUE THREAD

**Issue by wai** [odoo/odoo#22540]
Impacted versions:
V11.0

Steps to reproduce:
https://www.odoo.com/documentation/11.0/webservices/odoo.html#report-printing

Current behavior:
```
Caused by: org.apache.xmlrpc.XmlRpcException: Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\wsgi_server.py", line 124, in wsgi_xmlrpc
    result = odoo.http.dispatch_rpc(service, method, params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
UnboundLocalError: local variable 'dispatch' referenced before assignment
```
Working in V10, but in V11 same code got this error. It seems like missing service "report" to define the dispatch function 

Expected behavior:
report sent as PDF binary data encoded in base64

**Comment by Yenthe666** [comment]
Hi @wai,

Thanks a lot for your bug report.
This is coming from the following part of the code:
https://github.com/odoo/odoo/blob/11.0/odoo/http.py#L107-L115

@xmo-odoo or @sle-odoo I think this is relevant for one of you?

**Comment by sswapnesh** [comment]
Hello @wai 
It has been removed in V11.
Commit: c23ef9a9b6e2c7a43b3f98bdbd85e6c7b2b0ba74 and 3425752eaca236c1e4b4d616aa49b3faa6cfd957 
Related Issues: #19887

**Comment by nim-odoo** [comment]
The feature was indeed removed in v11.

**Comment by fnaquira** [comment]
I just clone a project of Odoo 11 a week ago and start using the XMLRPC for my App, but when it comes down to report printing I got this error:

`Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py\", line 124, in wsgi_xmlrpc\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 118, in dispatch_rpc\n    result = dispatch(method, params)\nUnboundLocalError: local variable 'dispatch' referenced before assignment\n"}`

Everything else works fine.

**Comment by sswapnesh** [comment]
@fnaquira  The feature is removed from V11.
Commit: c23ef9a9b6e2c7a43b3f98bdbd85e6c7b2b0ba74

**Comment by gylmar-infotools** [comment]
So "report" endpoint was removed, is there any way to get pdf report with external api for account.invoice model for example?

**Comment by jeffery9** [comment]
i think mostly use action `ir.actions.report`, and  `/report/` endpoint for api call.

**Comment by webfarmer** [comment]
Can someone please submit a proper code example of what you have to rewrite in order to get a simple invoice to download/fetch as a pdf. Been struggling with this for hours.

**Comment by sswapnesh** [comment]
I don't think there is a way to do this. As they have removed the whole feature at https://github.com/odoo/odoo/commit/c23ef9a9b6e2c7a43b3f98bdbd85e6c7b2b0ba74 and https://github.com/odoo/odoo/commit/3425752eaca236c1e4b4d616aa49b3faa6cfd957

**Comment by webfarmer** [comment]
https://stackoverflow.com/questions/54441130/odoo-v12-api-get-invoice-pdf
