### ISSUE TITLE
[8.0] Onchange partner / company on account invoice related to account property

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#2255]
# Impacted versions:

8.0 and above
# Steps to reproduce:
- Install account
- Create a second company child of main company and set up a chart of account for this second company
- Give administrator multicompany group and access to both companies
- Set administrator to work in child company, modify a partner (for example "Agrolait") and  assigning new payable account (different from the default one) ir order that it creates a new property
- Set administrator to work in parent company, go to a Customer Invoices, create a new invoice (for example for "Agrolait" (no need for lines), save it.
- Edit de invoice and try to change the company --> Error (Expected singleton: ir.property(75, 90, 91, 92) )
# Workaround:

onchange_partner_id and onchange_company_id seems to have an error when retriving account and payable properties, for example, in:

```
pay_prop = prop.search(pay_dom + res_dom) or prop.search(pay_dom)
```

If not sepecific propperty for the partner, then it should look for a one without res_id, should be:

```
pay_prop = prop.search(pay_dom + res_dom) or prop.search(pay_dom + [('res_id','=',False)])
```

Also, it will give error if more than one property has been found, tow posibilities:
- Improove "get_by_record" 
- Check if more than one value in pay_account and then use the first one with pay_account[0]
# Video to show error:

http://youtu.be/HtuZ96T5AlQ?hd=1

**Comment by Yenthe666** [comment]
Hi @jjscarafia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
