### ISSUE TITLE
Custom Report generates empty PDF (html works fine)

### ISSUE THREAD

**Issue by GillPotter** [odoo/odoo#22555]
Impacted versions: 
Odoo v11

Steps to reproduce:  
Using Ubuntu Server 16.04 LTS , wkhtmltopdf v0.12.1 (have also tried v0.12.3 and v0.12.4)
Add a custom module to create a new report from the Sale Form.

Current behaviour: 
New report is added to the Sale Print drop down menu. When selected it produces an empty PDF file with the correct file name. I can view the html file which has the new report.
The default reports work correctly to PDF.
The custom report module worked in Odoo v10, only needed to change "report" to "web" to adapt for v11.

Expected behavior: 
Content to be generated for the PDF

Video/Screenshot link (optional):
See this Odoo Question https://www.odoo.com/forum/help-1/question/odoo-11-custom-report-generate-empty-pdf-html-works-fine-128526

**Comment by sswapnesh** [comment]
Hello @GillPotter 

I have gone through the template code you have added in Forum Question.

Seems like you are missing `<t t-call="web.external_layout">` in template.
```

<?xml version="1.0" encoding="UTF-8"?>
<template id="sale.sale_proposition">
    <t t-call="web.external_layout">
        <t t-set="o" t-value="doc.with_context({'lang':doc.partner_id.lang})" />
        <div class="page">
            <div class="oe_structure" />
            <div style="text-align:center;font-size:1.5em;font-weight:bold;font-style:italic">
                <div class="row">
                    Proposition technique et commerciale
                    <br />
                    N°
                    <span t-field="o.name" />
                    <br />
                    POUR
                </div>
                <div>
                    <img t-if="o.partner_id.image" t-att-src="'data:image/png;base64,%s' % o.partner_id.image" style="max-height: 100px;" />
                </div>
                <div>
                    <span t-field="o.partner_id.name" />
                    <br />
                    <t t-if="o.partner_id.street">
                        <span t-field="o.partner_id.street" />
                        <br />
                    </t>
                    <t t-if="o.partner_id.street2">
                        <span t-field="o.partner_id.street2" />
                        <br />
                    </t>
                    <span t-if="o.partner_id.zip" t-field="o.partner_id.zip" />
                    <span t-if="o.partner_id.city" t-field="o.partner_id.city" />
                    <br t-if="o.partner_id.city or o.partner_id.city" />
                </div>
                <div>Réalisée par</div>
                <div>
                    <img class="img img-responsive" src="/mymodule/static/img/coverpage.jpg" />
                </div>
            </div>
            <div class="oe_structure" />
        </div>
    </t>
</template>
``` 

![](https://image.prntscr.com/image/qO35wcFfTHOsagSqCiHfIg.png)

**Comment by sle-odoo** [comment]
Hi,
This bug tracker is meant to be used for standard bugs, not customizations. Please use the forum for that.

Regards

**Comment by GillPotter** [comment]
Hi @sswapnesh,
Thank you for your quick reply. It was not necessary to call the external or internal layout for reports to work properly in v10. It would be useful to see this in the migration notes.
