### ISSUE TITLE
[MRP] move the PDF Viewer Widget into Web Module

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#22569]
Impacted versions:
10,11,master

It could be great to move the Pdf viewer widget from `mrp` to `web`.

It is here : https://github.com/odoo/odoo/blob/11.0/addons/mrp/static/src/js/mrp.js#L14

Thanks

**Comment by Yenthe666** [comment]
@mart-e perhaps nice to change this in the master version?

**Comment by mart-e** [comment]
cc @mge-odoo 5ec62a0b31a5c8a03dfd527500189e469bc9c752
Also why not use PDFjs from website?

**Comment by mge-odoo** [comment]
Hi,

Yep, this field widget could probably be moved in web (in master though).
It was initially only used in mrp, the mentioned commit just restored the previous widget in its initial place, adapted to the new views refactoring.
(cc @ged-odoo )

Martin

**Comment by mart-e** [comment]
It was already done at d83f7587 to include pdfjs in web

**Comment by mge-odoo** [comment]
Hi @fmdl 

The widget `pdf_viewer` has been put in `web` in master in rev. odoo/odoo@a7b521f.
Thanks for your feedback.

Martin

**Comment by Yenthe666** [comment]
Thanks a lot @mge-odoo 😄
