### ISSUE TITLE
Quotation Template link to Subscription Template Missing

### ISSUE THREAD

**Issue by raycollazo** [odoo/odoo#22576]
Impacted versions: V11

Steps to reproduce: Create a new Quotation Template

Current behavior: Missing link to Subscription

Expected behavior: Have a dropdown in the Quotation Template setup to link a Subscription

Video/Screenshot link (optional):
![quotationtemplate-v10](https://user-images.githubusercontent.com/17937809/35481433-959f8f2a-03f1-11e8-8f02-533831b140a6.png)
![quotationtemplate-v11](https://user-images.githubusercontent.com/17937809/35481432-9594e62e-03f1-11e8-9adf-78926b59d534.png)

This is a very key link, without it a subscription has to be created completely separate from a salesorder transaction. For example, you want to sell a 1 year software license as a line item on a quote. You would simply select the Quotation Template i.e **1 year Software** this Template has the Subscription Template **Annual SoftwareTemplate** upon confirming the quote this will automatically create the Subscription for the annual software charges. 
This functionality was in version 10, and I believe it may have been an oversight.

**Comment by bst-odoo** [comment]
Hello, 

In V11, the subscription template is set on the product and no more on the quote template.
It is much more easier to handle it this way.

Kr,

BST
