### ISSUE TITLE
[11.0] MRP Non-functional with consumed product lots

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#22578]
Impacted versions: 11.0CE

Steps to reproduce: 
1. Enable work order and lot
2. Enable lot tracking for consumed and finished products
3. Create MO and WO
4. Unable to submit partial quantity or lots.  If disable readonly, allows manual lot selection not referenced to MO reserve. 

Expected behavior: The WO should allow full and partial quantity submissions assigned to the reserved consumed lots and final lot.

**Comment by amoyaux** [comment]
Hi @Moto017 Effectively have to use the exact number of product specified.
We can do a feedback to @lap-odoo for future version.

However you can always edit the MO at the end of workorders using the edit/unlock functionality

**Comment by Moto017** [comment]
Hi,

Yes, but with lots assigned, it will only pull from the assigned lot and cause a negative stock.  The reserve should assign the quantity available in each lot.

**Comment by ray-odoo** [comment]
FYI: v12 allows as many Lots as are needed to meet the QTY of the Work Order to be selected, one after the other.
