### ISSUE TITLE
in chrome 64 and the latest firfox , the odoo11 style error has occurred。why?

### ISSUE THREAD

**Issue by sunjie20081001** [odoo/odoo#22583]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![deepinscrot-2002](https://user-images.githubusercontent.com/2008986/35494712-70ae9e98-04f7-11e8-9284-8000f873957e.png)

**Comment by Yenthe666** [comment]
Hi @sunjie20081001,

Thanks a lot for the report.
There where actually some problems with the translations that broke the Odoo layout in the latest versions.
If you still face it then please update your local Odoo instance and your problem should be resolved then:
![image](https://user-images.githubusercontent.com/6352350/36193529-8c7b5b0e-1166-11e8-9ec7-921985d7aed3.png)


Regards,
Yenthe
