### ISSUE TITLE
Could not take Backup

### ISSUE THREAD

**Issue by SuhebBodhih** [odoo/odoo#22586]
Impacted versions:
10.0
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![odoo db error](https://user-images.githubusercontent.com/35912526/35496532-42d065a2-04ec-11e8-8e51-96c9c5ad8471.JPG)

**Comment by Yenthe666** [comment]
Hi @SuhebBodhih,

This is an issue with the configuration of your database(s) and the users assigned to a database.
You might want to have a look at https://www.odoo.com/documentation/11.0/setup/install.html
