### ISSUE TITLE
[10.0] Translation value not being updated from Transifex

### ISSUE THREAD

**Issue by khishigbat** [odoo/odoo#22593]
Impacted versions: 10.0

Steps to reproduce: 

Current behavior: Some translations are not being updated weekly from Transifex.

Expected behavior: All translations from every module to be updated weekly from Transifex.

Video/Screenshot link (optional):
For example, translation for the term "Still loading...<br />Please be patient." is still "Ачаалласаар байна...<br />Тэвчээрэй." on runbot instance. 
But it was translated to "Программ ажиллаж байна,<br />Та түр хүлээнэ үү." 10 days ago on Transifex. 

![image](https://user-images.githubusercontent.com/29530738/35498584-eb741dd0-0509-11e8-9987-ae1ddd6a937f.png)

![image](https://user-images.githubusercontent.com/29530738/35498736-75c4d830-050a-11e8-9543-4a138b4bf813.png)

The same happens for Sale module. 

![image](https://user-images.githubusercontent.com/29530738/35499237-7df01e8c-050c-11e8-8fbc-c72ae2d12363.png)

![image](https://user-images.githubusercontent.com/29530738/35499245-8700dc28-050c-11e8-8c6d-8f04dfdb9899.png)

**Comment by khishigbat** [comment]
Hello?
Can anyone solve this, please?

**Comment by Yenthe666** [comment]
@mart-e could you check? The translations synced yesterday but it still doesn't seem to have updated?

**Comment by khishigbat** [comment]
@mart-e, please?

**Comment by mart-e** [comment]
Fixed at 91f2209216a964b3b2fbfe54ed4cc684357d0d98
Thanks for the report

**Comment by khishigbat** [comment]
Thank you. :smiley:
