### ISSUE TITLE
Project Forecast hours are not reported properly

### ISSUE THREAD

**Issue by wolfhall** [odoo/odoo#22617]
Impacted versions:  
11.0

Steps to reproduce:
In Projects: Create a forecast of 40h on a task that spans one week.

Current behavior:

Click on Project-Forecast-Gantt-By User: 
The task has a proper forecast in the Gantt chart with 100% resource utilization across the 5 days.
![image](https://user-images.githubusercontent.com/3019378/35540871-d961020e-050c-11e8-8061-481ceac6d747.png)

Open Project-Forecast-Grid-By User:
Click on Week and the week you forecasted: all 40h are shown on one day. 
Currently the 40 forecasted hours are all shown on the forecast start date. 
 
![image](https://user-images.githubusercontent.com/3019378/35540928-1aec20aa-050d-11e8-8843-d6d721ef429e.png)

Expected behavior:
Click on Week and the week you forecasted: the 40h should be spread across the five forecasted days giving each day 8h of forecasted work.  

Video/Screenshot link (optional):

**Comment by bst-odoo** [comment]
I'm closing the PR because the answer was given on the ticket 813910

**Comment by Yenthe666** [comment]
Thanks. @bst-odoo perhaps it is handy to add the final answer here too? If others land here they'll know the official statement too.
