### ISSUE TITLE
White page with brute text when print invoice to pdf (no template)

### ISSUE THREAD

**Issue by pokapow** [odoo/odoo#22613]
Impacted versions: 11.0

Steps to reproduce: Print a document (invoice)

Video/Screenshot link (optional): [https://ibb.co/n758UR](https://ibb.co/n758UR)

In a fresh docker install, when print a document, there is no active template. Only white page with brute text, like in the picture above...

Try differents thing since 5 days with no result. Is it a known bug ?

<a href="https://ibb.co/n758UR"><img src="https://preview.ibb.co/kZVa9R/Capture_du_2018_01_29_18_58_08.png" alt="Capture_du_2018_01_29_18_58_08" border="0"></a>

**Comment by Yenthe666** [comment]
@d-fence could you answer?

**Comment by adekock11** [comment]
Seems like the CSS is not being loaded. Try setting `report.url` in Settings -> Configuration -> System Parameters. Similar issues: #5548 and #1105

**Comment by adekock11** [comment]
Also #9085 and [this discussion](https://www.odoo.com/forum/help-1/question/qweb-reports-missing-css-on-pdf-export-64335) on the forum.

**Comment by pokapow** [comment]
Ok I tried different configuration for `report.url`, but still same problem ...
This is my docker-compose:

version: '3'
services:
  web:
    container_name: odoo-web3
    image: odoo:latest
    environment:
      - web.base.url.report=http://0.0.0.0:8069
      - report.url=http://0.0.0.0:8069
    depends_on:
      - db
    ports:
      - "93:8069"
    volumes:
      - odoo-web-data3:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    extra_hosts:
      - "mywebsite.com:127.0.0.1"
  db:
    container_name: odoo-db3
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data3:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data3:
  odoo-db-data3:

I tried with 127.0.0.1, with the externe docker port, with the host domain instead, or whit de local ip adresse of the docker container ... Always same issue.

**Comment by pokapow** [comment]
oook I fixed it!
I didn't know the debug mode to see all parameters ... So I added url.report in localhost and everything is find now =)
thank you!

**Comment by pokapow** [comment]
**Settings > Technical > Parameters > System Parameters**

**This can only be accessed when in 'debug' mode**, add url parameter ?debug after web in your browser address bar.

You have to create a new record with

key:    **report.url**

value:    **http://localhost:8069**
