### ISSUE TITLE
[10.0]Anti fraud module could be bypassed in POS

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#22638]
Impacted versions:
* tested on a french company with latest Odoo Core

Steps to reproduce:
* Open a session
* Wait for tomorrow
* Try to resume => Odoo prevent you from resuming the session (Ok)
* Open the POS url directly

Current behavior:
* Odoo let you add some pos.orders in the current session.

Expected behavior:
* Odoo should prevent the orders to be added in the session

Video/Screenshot link (optional):

**Comment by flotho** [comment]
Hi @legalsylvain , @Yenthe666 ,

What's your point of view on this one?

**Comment by Yenthe666** [comment]
In my opinion that should be a no go. When entering the POS URL there should be a security check for this. In case that you shouldn't be allowed to do this an UI blocker should be shown.
@mart-e and @jorenvo what do you two think?

**Comment by mart-e** [comment]
cc @kebeclibre @qdp-odoo why not overriding the controller `/pos/web` instead?

**Comment by kebeclibre** [comment]
@mart-e 
That shouldn't be a problem to override the controller.
However the function should be factorized properly then, to avoid duplicating the code

**Comment by legalsylvain** [comment]
Hi @flotho.
Agree with you. This check should be done in another way.
 
- in the UI like in the module pos_check_session_state (https://github.com/OCA/pos/pull/34). This module prevent to write in a closed session. (another must have feature, in a certification context !) 
- or by the controller like @mart-e said

**Comment by sle-odoo** [comment]
@pimodoo

**Comment by Yenthe666** [comment]
@mart-e and @sle-odoo are we still going to fix this in V10?

**Comment by qdp-odoo** [comment]
@pimodoo is the one to ping for pos-things ;-)

**Comment by Yenthe666** [comment]
or @switch87 actually? 😄

**Comment by pimodoo** [comment]
@Yenthe666 We are aware of this behavior, and it will probably not be fixed for now. We have made a lot of modification in 13.0 regarding the french certification, and those modifications will be backported to older versions which is our priority for now. We'll lookat this issue after.

**Comment by legalsylvain** [comment]
CC : @lap-odoo .
