### ISSUE TITLE
Cannot call action_validate_invoice_payment on account.payment using XML-RPC

### ISSUE THREAD

**Issue by mduvergey** [odoo/odoo#22630]
Impacted versions:
Odoo 11

Steps to reproduce:
```
proxy = xmlrpclib.ServerProxy('{}/xmlrpc/2/object'.format(config['odoo_url']), 
  allow_none=True)
proxy.execute_kw(config['odoo_db'], config['odoo_uid'], config['odoo_password'],
  'account.payment', 'action_validate_invoice_payment', 
  [payment_id])
```

Current behavior:
Get "TypeError: cannot marshal None unless allow_none is enabled" message

Expected behavior:
No error message

**Comment by xmo-odoo** [comment]
@qdp-odoo the method returns no value (~None) which then blows up when serialising back to XMLRPC.

**Comment by qdp-odoo** [comment]
done.

thanks for the contribution

ps: nice avatar, @mduvergey :+1:

**Comment by luvyouso** [comment]
please share fix

**Comment by luvyouso** [comment]
i call method : ### action_validate_invoice_payment
error : 

> This method should only be called to process a single invoice's payment. 

but, i add param invoice_ids 
error 

> dictionary update sequence element #0 has length 100; 2 is required
