### ISSUE TITLE
Translations are not exported when new items are added to a selection field

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#22645]
Impacted versions:
- 11.0

Steps to reproduce:
- From a new module, e.g. `new_module`, inherit a model which contains a selection field, e.g. `account.invoice` and add a new value to the selection:
```
class AccountInvoice(models.Model):
    _inherit = "account.invoice"
    type = fields.Selection(selection_add=[('new_value', 'New Value')])
```
- Update the module `new_module`
- Go to Settings -> Translations -> Export Translations
- Select any language and file format, search for `new_module` and click on Export

Current behavior:
The therm "New Value" is not exported.

Expected behavior:
The term should be exported as part of `new_module`, because it was defined in that module

Additional information:
- If the term is added manually in the `.po` file, then it's translated, but is not exported.
- If it's not an existing selection field but a new one defined in the inherited model, the exportt works as expected.
- If the module account is exported, the new term is included there.

**Comment by Yenthe666** [comment]
Hi @luisg123v,

Thanks a lot for the bug report!
This is in fact a known 'issue' at the moment. The translations will be exportable from the module you've inherited (accounting in your case) and not your custom module.
There is an internal task at Odoo, which is currenctly blocked, to see if we can change this behaviour for newer versions. If this is the case it should be coming to V12.
CC @mart-e (as discussed)

Regards,
Yenthe
