### ISSUE TITLE
[10.0] Reply in website_forum does not work for portal user

### ISSUE THREAD

**Issue by ivosm** [odoo/odoo#22648]
**Impacted versions:**
10

**Steps to reproduce:**
Create forum with allowed questions and/or links (questions works correctly). Create new discussion and new link and create some Replies. Give portal user enough karma to do anything (to be sure, that karma does not influences it at all). Login as portal user and try to reply any of the Replies. Then login as as any other user in employee group and try it again.

**Current behavior:**
Portal user with enough karma can see "Reply" link as active but after clicking on it, nothing happened. User from Employee group get after clicking on Reply link the editor and is able to reply anything while portal user can reply only to discussion topic and link directly, i.e. at top level.

**Expected behavior:**
The behavior for portal user should be the same as for user from employee group. 

**Video/Screenshot link (optional):**

**Comment by qsm-odoo** [comment]
Hello, the bug has been solved in 9.0 with commit https://github.com/odoo/odoo/commit/76665df0cfc765483c8d2856ad9579e9d7b6b58d, it will be available in 10.0 in the upcoming days.
