### ISSUE TITLE
[v11] Colors don't work in the list view

### ISSUE THREAD

**Issue by KasperDeclercq** [odoo/odoo#22658]
Impacted versions:
v11

Steps to reproduce:
Go to Settings / Languages

Current behavior:
All records have black text

Expected behavior:
Inactive records should be in gray,
Active records should be in black
external id:  base.res_lang_tree
`<tree string="Languages" colors="gray:not active">`

Video/Screenshot link (optional):
Left: v11
Right: v10
(I changed gray to red to make it more visible:  `<tree string="Languages" colors="red:not active">`

 )
![image](https://user-images.githubusercontent.com/24540328/35609893-83219756-065f-11e8-8ed4-e7b47b1831db.png)

**Comment by fmdl** [comment]
@KasperDeclercq 
It was deprecated from V9 (and remove in V11). Please find a module in OCA to reimplement that : https://github.com/OCA/web/pull/839

**Comment by Yenthe666** [comment]
Hi @KasperDeclercq,

The `color` attribute has been removed in V9 and up and can't be used anymore.
You can look at OCA modules, such as @fmdl suggest (thanks!) or you can use `decoration-{$name}`

Regards,
Yenthe

**Comment by fmdl** [comment]
@Yenthe666 the problem with decoration, is that it is limited in the scope of color.

**Comment by KasperDeclercq** [comment]
@Yenthe666  Ok, tnx for the information. 
But as I have showed it's still in the view with external-ID: base.res_lang_tree

**Comment by sswapnesh** [comment]
@KasperDeclercq 
It should be replaced by `decoration-muted="active == False">`.
