### ISSUE TITLE
[BUG][10] Orm domain search wrong result with OR and one2many field

### ISSUE THREAD

**Issue by d3stozaur** [odoo/odoo#22661]
Impacted versions:
10.0
Steps to reproduce:
add boolean field in res.users (ex. x_test), set it to True for some user with partner, next search res.partner with domain like [('user_ids.x_test', '=', True)] result is 1 id (the one we set on True), next do same search with domain [('user_ids', '=', False)] which will result with all partners without user set for example the result is 44, if we do search with domain ['|',('user_ids.x_test', '=', True),('user_ids', '=', False)] 
Current behavior:
the result is 1 id, the one from  [('user_ids.x_test', '=', True)] domain
Expected behavior:
the result is 45 ids, the one from  [('user_ids.x_test', '=', True)] domain and 44 from [('user_ids', '=', False)]
Video/Screenshot link (optional):
http://webm.land/media/77DS.webm

**Comment by anassahmed** [comment]
Can you update your bug with the impacted nightly release?

**Comment by d3stozaur** [comment]
I tested it on runbot v10 and i think it happens on all v10 versions.

**Comment by d3stozaur** [comment]
I just checked and this same bug occurs in v11, and i think it may lead to serious problems if it occurs globaly

**Comment by StefanRijnhart** [comment]
In case you're interested, I am proposing a patch on master for this here: https://github.com/odoo/odoo/pull/25182

**Comment by Yenthe666** [comment]
Dear @d3stozaur,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
