### ISSUE TITLE
[7.0] Minimum q.ty bug on purchase orders

### ISSUE THREAD

**Issue by bucciz** [odoo/odoo#2267]
Hi guys, I found a bug concerning the decimal separator and the thousands separator into the purchase orders. I set into Configuration > Translations > Languages the decimal separator with the "," and the thousands separator with the "." I select an item into the purchase orders and when I set the q.ty to 10.000,00 pcs. Odoo displayed to me a warning message that inform me that the minimum q.ty that I can order is of 10000.00 pcs. 
Essentially Odoo when verify the minimum q.ty that can be ordered didn't apply the decimal separator and the thousands separator that I set (the ERP take the default settings). How can I apply my own settings also into the purchase orders?

Tanks :)

**Comment by Yenthe666** [comment]
Hi @bucciz ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
