### ISSUE TITLE
hr_contract: field 'type_id' from model 'hr.contract' is not translatable due to non-unique XML ID

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#22685]
Impacted versions:
- 11.0

Steps to reproduce:
- Install the module `hr_contract`
- Export translations to any language to a `.po` file
- Open the `.po` file, look for "Contract Type" and note the translation name ends with a number, like [here](https://github.com/odoo/odoo/blob/1d4a75d9303613888e349625ba6c27735315ed85/addons/hr_contract/i18n/es.po#L88).

Current behavior:
There are two fields that could produce the XML ID `field_hr_contract_type_id`:
- Model `hr.contract`, field `type_id`
- Model `hr.contract.type`, field `id`

Since `type_id` is created lately, its XML ID is followed by its database ID, which means it uses a non-constant XML ID.

Expected behavior:
Each field should produce its own XML ID and it should be constant across installations, so fields may be referenced and translated.

**Comment by Elkasitu** [comment]
Thanks for the report, unfortunately the kind of changes required to fix this cannot be applied to stable versions, therefore it probably won't be fixed until Odoo 11.3

cc @mart-e like #22643

**Comment by nim-odoo** [comment]
Fixed in master with https://github.com/odoo/odoo/commit/cde120058aa4edd259b7d7e1624465af313710fe

**Comment by Yenthe666** [comment]
@nim-odoo could you give a bit feedback on the commit? What is the rationale behind using `__` instead of `_` in the names? I'd like to understand the why/how for this one.

**Comment by Elkasitu** [comment]
@Yenthe666 before that commit, if you had a field whose model was say `base_category` and the field name was `id`, the resulting XMLID would be `base_category_id` and if you had a model named `base` and a field named `category_id`, the resulting xid would be `base_category_id`, as you can see the xids are the same but the fields aren't, which means that there's an xid conflict...

With commit cde1200, we can now properly differentiate model name from field name, by the double undersocre, so my previous examples would now be `base_category__id` and `base__category_id`, conflict solved 😄

**Comment by Yenthe666** [comment]
Aha, I see! Thanks for the detailed information. 👍 
I really hope that this will be in the official docs for the upcoming V12 though. Otherwise it'll bite quite some people. 😉
