### ISSUE TITLE
QWeb2: Template 'Dialog' not found

### ISSUE THREAD

**Issue by iBasit** [odoo/odoo#22694]
Impacted versions: 11.v

Steps to reproduce: unknown

Current behavior: 

when I click on the create or delete button on opportunity in CRM, I get 

```
Uncaught Error: QWeb2: Template 'Dialog' not found
    at Object.exception (web.assets_common.js:3673)
    at Engine._render (web.assets_common.js:3718)
    at Engine.render (web.assets_common.js:3714)
    at web.assets_common.js:4019
    at web.assets_common.js:789
    at fire (web.assets_common.js:783)
    at Object.add [as done] (web.assets_common.js:784)
    at Array.<anonymous> (web.assets_common.js:789)
    at Function.each (web.assets_common.js:612)
    at Object.<anonymous> (web.assets_common.js:789)
```

Expected behavior:

Dialog should open

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/34341/35667360-463629c6-0725-11e8-8b23-3396e65ff73c.png)

![image](https://user-images.githubusercontent.com/34341/35667370-4d2cea76-0725-11e8-9471-b765d0b999c9.png)

**Comment by iBasit** [comment]
it was caused by auto refresh plugin, once installed.

**Comment by ovnicraft** [comment]
I have the same issue after install invoicing module and trying to update modules list.
Full traceback: https://gist.github.com/ovnicraft/4d2ba97b1ddf7a8f6c91541caf730365

**Comment by FlyingPigSolutions** [comment]
Hello Eveyrone,
I do encounter the similar issue after upgrading our ubuntu server 16.04.3 x64 from 1 GB Memory to 4 BG Memory that was causing us issue to print PDF reports, on ODOO 11 that we just installed early this year 2018.
Trying to solve it now...

**Comment by luisparedesa** [comment]
Help please. how do you disable the auto refresh ???

**Comment by KhichadiyaVK** [comment]
I don't think it's a real bug from odoo. I also have same issue but only when I use it in debug mode.
At last I found library problem of python3.5 in the module that is not installed yet and odoo is not show actuall error while compiling that module.

**Comment by obaqueiro** [comment]
This also started happening to me after trying to add a new  module.  Has anyone been able to solve this issue?

**Comment by devstar317** [comment]
Hey, I am encountering such errors. and I followed Obaqueiro but same here. Who can? Please 🙏.
