### ISSUE TITLE
Partial production behaviour

### ISSUE THREAD

**Issue by anhdv1979** [odoo/odoo#22693]
Impacted versions:
10.0
Steps to reproduce:
Create (e.g 5 [LAP-CUS] Laptop Customized)-> Checking availability -> Produce -> 2 -> Record Production (with quantity 2) -> Back to Manufacturing order, the consumed still zero (even if I change the consume from the produce form in the previous step) ?????
Btw, is it possible to post 2 finished goods into the stock ? (and of course reduce the consumed good) ?
And I could not see button ""Post inventory" in normal mode, only in development mode
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by lap-odoo** [comment]
@anhdv1979 : Did you fill in the quantity of consumed components in the produce wizard as in this video ? https://drive.google.com/file/d/1-hoDx0GHcUhVxjhEZ2M2zxw6v1ubLzqt/view. There it seems to work fine. Also, it's indeed desired to only show the "post inventory" button in debug mode. 

Please let me know if I missed something in your explanation. 

I'm closing the issue.
