### ISSUE TITLE
Not found item "Receive Inbox Notifications by Email" in mail.pot file

### ISSUE THREAD

**Issue by kevin3274** [odoo/odoo#227]
Impacted versions:
master

the [notify_email] field of res.partner object in mail module, default caption is "Receive Inbox Notifications by Email". not found in mail.pot file, can't translate to another language.

**Comment by JKE-be** [comment]
Thank you for the reporting !
It has been fixed meanwhile :)
https://github.com/odoo/odoo/blob/8.0/addons/mail/i18n/mail.pot#L1434
