### ISSUE TITLE
[11c]  Related sales orderline on a task is not always saved

### ISSUE THREAD

**Issue by ThijsvOers** [odoo/odoo#22707]
Impacted versions: 11 CE, tested on runbot

Steps to reproduce:
Create a quotation with a service product on the SO line (settings for the product are: timesheet  lines and create a new project but no task). Approve the quotation, go immediately to the newly created project and create a new task. Assign the sales orderline to this task. Save the task.

Current behavior:
The task is created but without the sales orderline. 
Expected behavior:
When i select a sales orderline on a task it should always be saved.

![schermafdruk van 2018-02-01 13-29-13](https://user-images.githubusercontent.com/30256071/35678882-58012b94-0755-11e8-81d3-7b4d303e3424.png)

AFTER saving:
![schermafdruk van 2018-02-01 13-40-10](https://user-images.githubusercontent.com/30256071/35678947-8f8acc78-0755-11e8-8ec6-77661670956c.png)

**Comment by sswapnesh** [comment]
Hello @ThijsvOers 
I can Confirm this Behaviour and also added PR #22721  for the same.

**Comment by ThijsvOers** [comment]
Hell sswapnesh, thank you for looking into the bug i reported, but your fix did not repair my bug (I just tested it on runbot). 

I think 'my' bug has nothing to do with the subtask task issue that you solved.

**Comment by ThijsvOers** [comment]
I am sorry sswapnesh, but i tested your pull request on the wrong runbot. The runbot that is related to your pull request seems be expired. Can you perhaps reset the version so that I can test it properly?
thanx in advance!

**Comment by pedrobaeza** [comment]
Thanks for this, @jem-odoo
