### ISSUE TITLE
[BUG][11.0] in import screen, fields can't translate.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#22703]
Impacted versions:
11.0
Steps to reproduce:

https://github.com/odoo/odoo/blob/e6cccbf441eddf48feaa0ff1e99ecf40f9f973ed/odoo/fields.py#L742-L747

- in import screen ,I load a file , in fields column ,can't translate.
- I tracked code ,I found  env.lang =None  in fields.py.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![qq20180201-185115](https://user-images.githubusercontent.com/5398273/35674832-e71bec76-0780-11e8-817f-56778525e481.png)

**Comment by sum1201** [comment]
enterprise ticket is 813996

**Comment by sum1201** [comment]
I pull a request ,but unit test not ok.
https://github.com/odoo/odoo/pull/22717

please help me @ged-odoo @sle-odoo

**Comment by Yenthe666** [comment]
@mart-e can you give feedback why this is the case?

**Comment by mart-e** [comment]
Hello,

There was an easier fix to just pass along the user language in the context.
Done at https://github.com/odoo/odoo/commit/56a25e5f0c2fa83cc622e0ed010ea24a62fbc8d9
