### ISSUE TITLE
Calendar event list view slow when we have 200k records

### ISSUE THREAD

**Issue by sferket** [odoo/odoo#22719]
Impacted versions: 10.0

Steps to reproduce:
- Create 200k records in calendar.event
- Open list view on this model, without filter
- Takes several minutes to display records
- Also tried with 3k records, speed is acceptable

Current behavior:
- Takes several minutes to display records

Expected behavior:
- Start displaying records in a few seconds. This works fine for other models with many records. 

It works as expected if we comment out line (1589 for v10) in addons/calendar/models/calendar.py: 
events = self.browse(events.get_recurrent_ids(args, order=order))

**Comment by Yenthe666** [comment]
Dear @sferket,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
