### ISSUE TITLE
Deleting the unposted depreciation lines having date less than the first posted one

### ISSUE THREAD

**Issue by MOGuerillaSoft** [odoo/odoo#22710]
Impacted versions:
10.0

Steps to reproduce:
1 - Create and Confirm an asset.
2 - Post some depreciation lines apart the first one.
3 - Update the value of asset (For example, value of description field).

Current behavior:
1 - The unposted depreciation lines having date less than the posted ones were removed.
2 - The first depreciation line become the first posted one before the update.
By the result, the asset depreciation lines will not be correct.

Expected behavior:
The unposted depreciation lines with date less than the first posted one will not be removed after asset update.

Video/Screenshot link (optional):

**Comment by qdp-odoo** [comment]
that's a tricky use case.. I'd say you were looking for trouble when doing that ^^

we will improve in master, to raise an error if the user wants to change the asset value while having this specific use case (will force to unpost all or post the needed ones). cc @lap-odoo 

thanks for reporting
