### ISSUE TITLE
server form doesn't work with implicit '&' in modifiers domain

### ISSUE THREAD

**Issue by pimodoo** [odoo/odoo#22711]
Impacted versions:
master

Steps to reproduce:
try to develop
Current behavior:
Huge Lie

Expected behavior:
work

Video/Screenshot link (optional):
FIX IT! PLEASE!!

**Comment by xmo-odoo** [comment]
Can not reproduce. Please advise.

**Comment by pimodoo** [comment]
shamefull !

**Comment by xmo-odoo** [comment]
![shamenun](https://user-images.githubusercontent.com/7571158/35681010-599fe358-075c-11e8-8e3e-93ee43a7be36.gif)
