### ISSUE TITLE
[11.0] Readonly modifiers is not handled well in m2o field

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22729]
Impacted versions: 11.0

Steps to reproduce: Apply readonly modifier on m2o field based on other m2o field

Example in odoo v11
`<field name="sale_line_id" string="Sales Order Item" attrs="{'invisible': [('partner_id', '=', False)], 'readonly': [('parent_id', '!=', False)]}" options="{&quot;no_open&quot;: True, &quot;no_create&quot;: True}" context="{'sale_show_order_product_name': True}"/>`

Sales Order Item = sale_line_id
Parent Task = parent_id

![](https://image.prntscr.com/image/EtRtKODFR2CGFNtvDslSpw.png)

Current behavior: Selecting Parent Task will make Sales Order Item readonly, Which is correct

![](https://image.prntscr.com/image/N9ZcROqcR1a0wljwN2xbMw.png)

The Issues is Sales Order Item is readonly after Remove Parent Task. (Record is not saved yet, It is already in edit mode.)

![](https://image.prntscr.com/image/kwGC3MPVSD_Sil33fgd2pA.png)

Expected behavior: It should be editable after removing Parent Task

Video/Screenshot link (optional):

**Comment by celm1990** [comment]
Other example [is here](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_partner_view.xml#L161), On res_partner view when a partner is contact, change type(contact, delivery, invoice, other), attrs not work.
