### ISSUE TITLE
[11.0] Uncaught TypeError: Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22728]
Impacted versions: 11.0

Steps to reproduce: Go to Pivot View (Empty View) --> Export Xls

![](https://image.prntscr.com/image/DW0hKhIgTNOzzq8TOvdaVQ.png)

Current behavior: Traceback on Screen

![](https://image.prntscr.com/image/91YVVKBETnGUdmCV5h5IEQ.png)

Expected behavior: No traceback 

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I agree with the fact No one wants to Export Blank xls but for another Empty Pivot view, it exports with all records.

![](https://image.prntscr.com/image/ZS5iTO42TWSDF7So9EJWCg.png)

**Comment by Yenthe666** [comment]
@ged-odoo another one for you (sorry!)

**Comment by mge-odoo** [comment]
Hi @sswapnesh 

Thanks for reporting the bug.
It has been fixed in 11.0

Martin
