### ISSUE TITLE
[11.0] Decimal precision is not handled well on Pivot Export

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22727]
Impacted versions: 11.0
Not tested on older versions

Steps to reproduce: Go to Pivot View --> Export xls

Current behavior: Decimal precision is not handled well on xls

![](https://image.prntscr.com/image/X4Un-7sBRHOcupquMN1HOw.png)

![screenshot from 2018-02-02 01-30-08](https://user-images.githubusercontent.com/16624719/35700317-b6394706-07b8-11e8-9384-b7a449df2f0d.png)

Expected behavior: Amount should be same at both Places.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@xmo-odoo or @mart-e I believe one of you worked on the exports recently?

**Comment by mart-e** [comment]
Hmm actually I don't see it as a bug. Reducing the precision is good for the display but for the export, you want the raw numbers, not rounded.

And to be honest, both behaviours are justifiable.

But the pivot is not the classic export you are talking about @Yenthe666, the pivot is something else custom.
@ged-odoo will probably be able to confirm/prove me wrong on this one

**Comment by Yenthe666** [comment]
Yep I agree, after all they are stored in the database as raw numbers too. I guess @ged-odoo can give us the final answer to confirm/dissaprove this. 👍

**Comment by gdgellatly** [comment]
I think the truly correct behaviour (feature request/enhancement) is to format the cells of the spreadsheet, while keeping the raw number.

**Comment by ged-odoo** [comment]
I am pretty sure that, as @mart-e  said, the initial spec was to export the raw unformatted number, since it is quite easy to add the formatting in excel afterward.  

But now, the suggestion by  @gdgellatly seems to be the correct solution, if you ask me.

**Comment by Dayssam** [comment]
@sswapnesh 

i fix it by making round in read_group function

 @api.model
    def read_group(self, domain, fields, groupby, offset=0, limit=None, orderby=False, lazy=True):

hope this help someone

**Comment by diannejose** [comment]
> @sswapnesh
> 
> i fixed it by making round in read_group function
> 
> ![pivot_decimal_precision](https://user-images.githubusercontent.com/13301885/59543974-431c1380-8f06-11e9-8fc9-2aeb98d92775.PNG)
> 
> @api.model
> def read_group(self, domain, fields, groupby, offset=0, limit=None, orderby=False, lazy=True):
> 
> hope this help someone

I didnt understand the fix of round, can you share the new function

**Comment by sswapnesh** [comment]
Update for v13:
Same Issue on "Export All" 
![Screenshot (4)](https://user-images.githubusercontent.com/16624719/66095914-e4fb6500-e5b6-11e9-9abd-40ff416bb91d.png)
![Screenshot from 2019-10-03 08-22-23](https://user-images.githubusercontent.com/16624719/66095947-f6dd0800-e5b6-11e9-87a6-d3f873badc39.png)

**Comment by mart-e** [comment]
Cf discussion previously, we won't apply the decimal precision, keeping the raw numbers is better

**Comment by sswapnesh** [comment]
Same for  Float time widget?

**Comment by mart-e** [comment]
What do you mean? The time widget is changing only at the rendering but in database, it is best to keep the original value (and also at export)

**Comment by sswapnesh** [comment]
Original issue was for Decimal Precision, Nd on the last comment I was talking about applying Time widget there.
But if it's about Exporting Raw data than we can keep as it is.

**Comment by hassaniqbalhx** [comment]
Hi,

You can override export controller to round values in the excel file downloaded from pivot.

This is the controller from which excel file is printing in Odoo 10.

 **@http.route('/web/pivot/export_xls', type='http', auth="user")**
 
 So override this controller in your custom module and use:
 **worksheet.write(y, x, "%0.2f" % cell['value'])** to round values to 2dp.
 
 Hope this will help.
 Best Regards,
 Yaseen Jamii
