### ISSUE TITLE
[whishlist] Use Action Name  as xls file name on Pivot view.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22726]
Impacted versions: 11.0
Not tested in older versions

Steps to reproduce: Go to Pivot view of any module --> Export xls

Current behavior: xls file will be generated with name `table.xls`

![](https://image.prntscr.com/image/55di4pasS8KkeQ_FgtVXKA.png)

Expected behavior: Action name should be used as file name

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sswapnesh thanks a lot for the suggestion.
I don't really agree with the action name, I think there are better options (model name, menu name?) but I do agree it could be an improvement.
@mart-e your call 😉

**Comment by sswapnesh** [comment]
Ya we can use that also, But not static table.xls

**Comment by Yenthe666** [comment]
Too fixed, I (personally) agree.

**Comment by mart-e** [comment]
Hello,

Well, having the model name is not very good either as it is something quite technical and not understandable by users (e.g. `account.invoice.xls` is not very good either).
The point of the pivot view is that people configure it to match their needs. Probably aggregating data from multiple models and with specific filtering.
Also, the report is generated server side by just sending the raw data. We do not have the information of the model, menu, actions,...

So `table.xls` is actually quite safe as a filename and changing that would probably require a lot of work for something people will rename when saving anyway.

We could accept pull request to have a better name if you can suggest easy and generic ones but not something we are likely to change now.
