### ISSUE TITLE
[11.0] Sum/Avg value become 0.0 after doing some operation from List view.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22725]
Impacted versions: 11.0

Steps to reproduce: Performed on Runbot -->. Got to List view where Sum/Avg is Used --> Select records and Do Some Operation (Print Report or Delete)

![](https://image.prntscr.com/image/dp07H3QzTdGiugTR36bkDA.png)

Current behavior: Total Sum/Avg values become 0.0 at the bottom.

![](https://image.prntscr.com/image/bxPjhdCfR0qX4_znAvyNZQ.png)

Expected behavior: It should the Total Sum/Avg amount

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Yep, that looks wrong. Not sure if it related to the JS @ged-odoo?
