### ISSUE TITLE
Multi Currency reported Margin if flawed

### ISSUE THREAD

**Issue by farazda1** [odoo/odoo#22734]
Impacted versions:
10.0 community
Steps to reproduce:
Enable Multi Company
Install product_multi_company
Enable Multi Currency
Create Price lists in different currencies
Enable sales_margin
Create Sales Order with currency different than company currency
The Cost value is pulled in Company Currency Value, - from the Sales Value in foreign currency.
Margin reported is wrong.
Current behavior:
The Cost value is pulled in Company Currency Value, - from the Sales Value in foreign currency.
Margin reported is wrong.
Expected behavior:
The Cost value should also be converted to selected currency Currency Value, - from the Sales Value in foreign currency or something.
Margin reported shouldnt be wrong.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10349579/35714171-96531314-07e4-11e8-9ae3-5fa3ee7bfeb6.png)

**Comment by farazda1** [comment]
![image](https://user-images.githubusercontent.com/10349579/35726234-9012e978-081d-11e8-934a-0b47085f29bc.png)

![image](https://user-images.githubusercontent.com/10349579/35726355-128189c8-081e-11e8-8cd4-a1956a19443f.png)

![image](https://user-images.githubusercontent.com/10349579/35726447-5f9ae3a8-081e-11e8-9f86-93fd3d4615e5.png)

inside the product view the currency field is used to show in the display, whereas if the product is configured to be accessible by multiple companies, then the currency showing with the cost price gives a false representation. and a negative margin.

Maybe its just that the cost actually saved is in the currency of the current company, but is just showing the currency inside product of the company from which the product was created.

**Comment by farazda1** [comment]
![image](https://user-images.githubusercontent.com/10349579/35727609-1f666f60-0822-11e8-8936-c4023e451f73.png)

i believe the solution will be to show in this line the Label of the currently active company.

as we are storing the standard_price value per company.

**Comment by farazda1** [comment]
![image](https://user-images.githubusercontent.com/10349579/35730567-06c6f1f0-082c-11e8-854e-9df23c087712.png)

the currency symbol only for the cost price should appear based on the currency of the current company, not the company which is selected in the company_id field of the product.

**Comment by Yenthe666** [comment]
Dear @farazda1,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
