### ISSUE TITLE
[11.0] Could not merge Selected Contacts

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22730]
Impacted versions: 11.0

Steps to reproduce: Select few Contacts from List view --> Actions --> Merger Selected Partners

Current behavior: Traceback on Screen 

![](https://image.prntscr.com/image/mxCyfTL2TqGBJ9RYDtJliA.png)

![](https://image.prntscr.com/image/iqPbp2twQoueulwtvRjNJw.png)

Expected behavior: Should Open Wizard to Merge Contacts

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
However, One of the Record is created without `create_date` in it , which is causing Issue. (Verified on Runbot)


![](https://image.prntscr.com/image/-0fJ1prGRlmZQ1_YO0Jc3A.png)


This part of code is throwing traceback 
[https://github.com/odoo/odoo/blob/11.0/addons/crm/wizard/base_partner_merge.py#L382](https://github.com/odoo/odoo/blob/11.0/addons/crm/wizard/base_partner_merge.py#L382)

**Comment by Yenthe666** [comment]
@mart-e could you have a look at this one? Why is the `create_date` used as a key though?
https://github.com/odoo/odoo/blob/f5e7b866860436782ade53308da1ff725be1f124/addons/crm/wizard/base_partner_merge.py#L381-L383

**Comment by mart-e** [comment]
`create_date` is supposed to be always set and a good criteria to sort.
What is the rational to try to merged the administrator and the company contacts? Sounds like a bad idea.

**Comment by Yenthe666** [comment]
@mart-e from a functional point of view there is probably not a good case. It happens with some others too though, such as `Your Company`:
![image](https://user-images.githubusercontent.com/6352350/35729026-bbe4a42a-080d-11e8-9a36-a046debbfcc2.png)

**Comment by mart-e** [comment]
Yes I understood the bug. Just that the code is not wrong, it does not cover a specific usecase (no create_date on a record) that should not happen in production.
We could also probably just add a create_date for the admin

**Comment by Yenthe666** [comment]
Yep, sounds like the easiest fix to me. Or an if/else. Let us just cover it to be 100% covered? 😄

**Comment by sswapnesh** [comment]
I am wondering how `create_date` is empty for admin

**Comment by mart-e** [comment]
Prevented in master at b661881e3514a515244ba81ecb278d29d55d55fb
