### ISSUE TITLE
[bug][11.0] main menu can't show

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#22748]
Impacted versions:
11.0
Steps to reproduce:
my code have update-to-date,
![qq20180202-183331](https://user-images.githubusercontent.com/5398273/35728878-fd25d168-0847-11e8-9fe5-fa77b4261459.png)

but in screen main menu can't show ( in community ).
![qq20180202-183804](https://user-images.githubusercontent.com/5398273/35728975-3bdb2458-0848-11e8-8e25-c59392f3760d.png)

 I open import screen ,in enterprise.main menu can't show.

Current behavior:

chrome not show error.
I think css is error.

Expected behavior:

Video/Screenshot link (optional):

**Comment by levin222** [comment]
big bug

**Comment by sum1201** [comment]
enterprise ticket is 814231.
please help me @ged-odoo @sle-odoo @mart-e @Yenthe666

**Comment by Yenthe666** [comment]
@sum1201 please add more steps on how to reproduce this bug though. With just a screenshot nobody can help you.
Can you reproduce it on a runbot instance at runbot.odoo.com? Do you have custom development? How can we trigger this issue? Does your Odoo work if you activate developer mode?

Regards,
Yenthe

**Comment by levin222** [comment]
the same to me !

**Comment by sum1201** [comment]
not only me ,but other people find it also .

**Comment by levin222** [comment]
![tim 20180202185508](https://user-images.githubusercontent.com/8110722/35729768-bc1cbefe-084a-11e8-8973-1441a2b10f79.png)
![tim 20180202185454](https://user-images.githubusercontent.com/8110722/35729775-c0264ccc-084a-11e8-9f26-8009f660b118.png)

**Comment by sum1201** [comment]
@Yenthe666  I test  in runbot.odoo.com.
language is english , no problem.
language is chinese ,main menu can't show.
![qq20180202-192103](https://user-images.githubusercontent.com/5398273/35730753-3ddc7d1e-084e-11e8-9ac4-27f2bdab5737.png)
![qq20180202-192034](https://user-images.githubusercontent.com/5398273/35730755-3f2bd9c6-084e-11e8-942a-6f7feb523d75.png)

**Comment by Yenthe666** [comment]
@mart-e this is language related and I believe we had something very similar a while ago because of broken translations?

**Comment by woodheadhn** [comment]
Big bug

**Comment by mart-e** [comment]
Probably one Chinese translation not formatting properly the HTML code. Now the idea is to find which one :)

**Comment by GoodERPJeff** [comment]
It will be hard to find a special character in 18000 sentences

**Comment by mart-e** [comment]
@sum1201 actually, looks like you introduced the bug 😉 
It was kind of tricky but bad comment making the web client not to load properly

Fixed at 3e91cbf47d6

https://www.transifex.com/odoo/odoo-11/translate/#zh_CN/web/119303199?q=if%20lt%20IE%2010

**Comment by sum1201** [comment]
@mart-e 
I believe this will happen next time.
Can this code  be changed to do not need translation?
