### ISSUE TITLE
Franglais term "Undefined Yet" label on account.journal selection field bank_statements_source 

### ISSUE THREAD

**Issue by vcloud9ray** [odoo/odoo#22769]
Impacted versions:
 v11

https://github.com/odoo/odoo/blob/11.0/addons/account/models/account.py#L382

`bank_statements_source = fields.Selection([('undefined', 'Undefined Yet'),('manual', 'Record Manually')], string='Bank Feeds', default='undefined')`

Steps to reproduce:

Open up any Bank Account from Accounting --> Configuration --> Bank Accounts 

Current behavior:

![image](https://user-images.githubusercontent.com/31354495/35754427-38a9215c-0818-11e8-9395-d3804dce3471.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/31354495/35754442-44d6ad32-0818-11e8-8806-c10a175a424c.png)

When can we have a Community (of native English speakers and writers) translation of the English language terms??  It's like me telling you that I have "le logiciel meilleur d'entreprise du monde" - are you interested in buying it?  :smirk:

**Comment by Yenthe666** [comment]
@vcloud9ray thanks for the suggestion! I made a PR at https://github.com/odoo/odoo/pull/22793 for this easy fix.

**Comment by mart-e** [comment]
Fixed in master at https://github.com/odoo/odoo/commit/e81d922ef2b2e3981b1e69ac69c870246148147f
Workaround in 11.0 at 1b5d0c3773e

> When can we have a Community (of native English speakers and writers) translation of the English language terms??

Please do report the English mistakes you see.
If you have suggestions for an early review of the source terms, please don't hesitate to contact me to see if we can do something about it.
