### ISSUE TITLE
I am working with multi-companies, but when applying a payment to a supplier or client invoice, the payment does not apply that could be happening

### ISSUE THREAD

**Issue by rzavalatk** [odoo/odoo#22777]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @rzavalatk,

Please add reproducable steps and details to your bug report. All the details should be filled in.
Can you please fill it in? Otherwise we can't help you and will have to close this bug report eventually.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
