### ISSUE TITLE
[ACL] Intercompany warhouse moves

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22774]
https://github.com/odoo/odoo/blob/43617bbcb65fc4048ad97567067cb2f3138873a3/addons/stock/models/stock_picking.py#L222

Here it should be `compute_sudo=True`, so that propagated changes in an inter company move do not result in a read error if warehouse users has no world access...

@jco-odoo

**Comment by blaggacao** [comment]
In v10 this translates to `min_date` AND `max_date` fields...

**Comment by amoyaux** [comment]
Dear,

In order to do inter company move you have to pass through transit location that is virtual and every stock user should have access to it.

**Comment by blaggacao** [comment]
Yes, but not to the chained moves created by routes as explained in the related issue.

**Comment by blaggacao** [comment]
Let's keep it open for the sake of tracking this down until solved ultimately. I'll close it myself, then
