### ISSUE TITLE
[ACL] intercompany stock moves

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22772]
https://github.com/odoo/odoo/blob/43617bbcb65fc4048ad97567067cb2f3138873a3/addons/stock/security/stock_security.xml#L92

Shouldn't it be?

```
['|', '|', '|', ('company_id','=',False), ('company_id','child_of',[user.company_id.id]), ('move_dest_ids.company_id','child_of',[user.company_id.id]), ('move_orig_ids.company_id','child_of',[user.company_id.id])]
```
In order to be able to do cross company moves via an ~internal~ intercompany transit location.... without the one doing the move beeing in the need to have some kind of more global access....
EDIT: Under the circumstance of a routed move creation with chaining.

@jco-odoo

**Comment by Yenthe666** [comment]
@sle-odoo another security rule to check.
@blaggacao again, always welcome to make a PR, which saves us all some time & trouble. 😉

**Comment by sle-odoo** [comment]
@blaggacao hello, why do you want to make an inter company move in an internal transit location? the normal way would be to go through the inter company transit.

**Comment by blaggacao** [comment]
@sle-odoo I'm not sure if I understand you right. Those are only subsidiaries of the same company, the traceability of the quants must be ensured.

**Comment by sle-odoo** [comment]
> Those are only subsidiaries of the same company, the traceability of the quants must be ensured.

Not between companies. Between companies, you must use the intercompany transit and between warehouses of a same company, you must use the internal transit. Note that the traceability is kept in the internal transit.

**Comment by sle-odoo** [comment]
@blaggacao can you confirm nothing is to do here if you follow what should be done when doing an intercompany move?

**Comment by blaggacao** [comment]
@sle-odoo No, unfortunately I can't.
Everyone but the admin user, doesn't have access to do so because of the chaining put in place by the route. In the case he is logged in into one company of both participating in this transaction and not in a super-company which grants access to both realms.

**Comment by sle-odoo** [comment]
can you briefly describe the company hierarchy and the kind of route you're using? to ease my testing :)

**Comment by blaggacao** [comment]
Holding
-- Sub City 1 (Operator Alice)
-- Sub City 2 (Operator Bob)
-- Sub City 3 (Operator Charlie)

-- Sub City 1 (Operator Alice)
will request transfer of 3 Ducks from
-- Sub City 3 (Operator Charlie)

Alice states:
I need 3 ducks, and will use "Sub City 1: Intercompany transfer from Sub City 3" Route (warehouses previously configured for resupply)

**Comment by blaggacao** [comment]
This goes along with #22775

**Comment by blaggacao** [comment]
Verbosing the leaves `'|', ('move_dest_ids.company_id','child_of',[user.company_id.id]), ('move_orig_ids.company_id','child_of',[user.company_id.id])`:

- OTHER move
- which has orig / dest moves
- which belong to CURRENT company (or child)

That OTHER move can be accessed in order for the reservation chain to work on it.

Note that routes applied to procurements (in v10) are executed as sudo, so the initial creation of the move chain is not of a concern.

**Comment by blaggacao** [comment]
@sle-odoo Is this still blocked? I guess the use case is evidenced or is there something you want me to clarify?

**Comment by sle-odoo** [comment]
@blaggacao still didn't have the time to look into it, sorry

**Comment by blaggacao** [comment]
Ok, make sure to ping me when you start working on it, I might then be able to recapitulate and feed back eventual missing bits. It's a use case which needs some mental setup... :wink:
