### ISSUE TITLE
[ACL] Intercompany moves

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22775]
https://github.com/odoo/odoo/blob/43617bbcb65fc4048ad97567067cb2f3138873a3/addons/stock/security/stock_security.xml#L62

should be:
```
['|','|',('company_id','=',False),('company_id','child_of',[user.company_id.id]),('move_lines.move_orig_ids.company_id', 'child_of',[user.company_id.id])]
```
While being necesary on it's own, I think this is also sufficient to fix #22774

**Comment by Yenthe666** [comment]
@sle-odoo for you to check I guess.
@blaggacao why don't you make a PR right away when you believe it should be fixed like this? This way it gets a higher priority / response rate than bug reports. Plus, it saves everybody some time. 😉

**Comment by blaggacao** [comment]
@Yenthe666 You're right, but ther is a simple and valid reason why I don't do it: Complexity. When I'm investigating those kind of things I have 50.000 things in my head and doing a simple PR suddenly gets quite expensive. Normally I do PRs :)

**Comment by sle-odoo** [comment]
can you describe the flow you're trying to achieve that is blocked by the rule?

**Comment by blaggacao** [comment]
Of course:
1. I create two companies
2. I create two warehouses, one for each company
3. I configure resupply from one warehouse to the other (cross company)
4. Jon Doe (company A) logs in and requires a transfer (he uses the preferred route to tell the system where he want's to get inventory from)
5. Max Musterman (company B) get's the dispatch order

Then things start to break. They cannot complete the transaction with their limited view of the world.
(in v10 - I see v11 fixes some of the issues in the code already, so all that's left are those ACL issues)

Things to note:
- Quants must be kept intact so they need to metamorphose into the other company, in v11 this is no problem through relating the company directly to the location, in v10 a little code fix was needed
- We have a chain of business logic going into the origin and the destination moves, also touching quants and pickings of the other company.
- In v10 with procuprements things where even worse (I understand why you dropped them, now) - However I guess, Odoo needs a more robust elevation system (in general)

**Comment by blaggacao** [comment]
Jon Doe and Max Musterman are both operators...

**Comment by jco-odoo** [comment]
I don't think either that this is to be solved by changing the security rule and using the origin moves would be a good solution (and then it should be in the other sense too?).  In v10, we can not keep them intact as the cost is different from one company to the other.  Therefore, we used to refer to the inter_company module creating purchase/sale in the other company.

**Comment by blaggacao** [comment]
@jco-odoo I cannot really make sense of your response.

I did some hacking to solve my use case in v10 in my own code.

This issue refers to what I believe is forward-portable to v11, given that v11 changes proxies effectively the quant company column through the location (which I think is pretty elegant, btw)

**Comment by jco-odoo** [comment]
Ok, but that does not change anything to it being weird as security rule.

**Comment by blaggacao** [comment]
The rule follows the widely nested (chained) business logic, that routes necessarily produce...
This rule goes down the first iteration, in order to complete the chained reserve operation.

The other solution to the problem would be to do more ACL directly in the business logic and go sudo where boundaries are detected for the reserve operation. Not defaulting to sudo to preserve authroship and chatter logs as much as possible.

However with this access rule, chatter logs are transparently preserved even in intercompany context.

SO that the operator can see who triggered that the move is now in reserved state (which is practically a lot more useful than just `Administrator`)

**Comment by jco-odoo** [comment]
But if it triggers more than one rule or in the other sense, it would not work either.

**Comment by blaggacao** [comment]
>But if it triggers more than one rule

I haven't tested this, but as the rule maps down to a move, and it targets the first iteration it will always get access to that move's picking just for the reservation.

The other way round it not a real use case as reservations are only triggered downstream, if I'm not completely wrong on this...

It's a brainf**k so I'll translate the leaf `('move_lines.move_orig_ids.company_id', 'child_of',[user.company_id.id])`:

- A OTHER picking
- Has a move line
- Which has a origin move
- Which belongs to my CURRENT company (or a child)

Then I can access that picking in order to programatically trigger the reservation method on it.

It will leave in the chatter a note like so:
"David A. reserved the picking on sunday the best day of the week" :smile:
