### ISSUE TITLE
[11.0] Unable to finish Odoo unit tests because of at least one file missing from .deb package

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#22778]
Impacted versions: 11.0

Steps to reproduce: Download the [20180203](http://nightly.odoo.com/11.0/nightly/deb/odoo_11.0.20180203_all.deb) deb installation file, run Odoo unit tests.

Current behavior: The unit tests get stuck at [base_import](https://github.com/odoo/odoo/blob/11.0/addons/base_import/tests/test_base_import.py#L296) tests, because `addons/base_import/tests/test.xlsx` is missing

See for yourself. Download the deb package and look inside. That xlsx file _is_ missing.

Expected behavior: The unit tests finish without any problems

**Comment by mlaitinen** [comment]
Not sure how the .deb packages are built in Odoo, but the solution could be adding `.xlsx` to this file https://github.com/odoo/odoo/blob/11.0/MANIFEST.in

**Comment by aisopuro** [comment]
Related to #22778.

**Comment by mlaitinen** [comment]
Any clues? Can I help somehow?

**Comment by Yenthe666** [comment]
Hi there,

This should have been fixed in https://github.com/odoo/odoo/commit/cd21ea414e9b16e0a1044cfdf26aba744b269c8b
The fix is for 9.0 at the moment but should be forward ported soon (give it a week or so).

Regards,
Yenthe

**Comment by mlaitinen** [comment]
Ok, forward ported to 11.0 in commit f492c7308034c2b6a1418c22d83385f866772988. Thanks.
