### ISSUE TITLE
[11.0] Error creating a new line in the bank statement

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#22770]
**Impacted versions:** 11.0

**Steps to reproduce:** 

1. Create different bank journals
2. Load lines for the bank statements so that it is generated, several pages in each extract
3. Try to register a new line for the extract

**Current behavior:**

An error occurs when trying to register a new line

![bank test 2 odoo](https://user-images.githubusercontent.com/5775695/35755355-469b4a0e-083d-11e8-9c81-da700d289de2.png)

**Expected behavior:**

Register lines for each bank statement, regardless of the number of lines you already have

**Video/Screenshot link (optional):**

https://youtu.be/1nFcpRv43iM

**Comment by hugho-ad** [comment]
@deivislaya in order to replicate the issue more easily, can you share us the demo data you has use and the way you has load all those lines?

**Comment by deivislaya** [comment]
@hugho-ad To replicate the issue, the demo data used is in runbot odoo. The way to load all lines is loading between 100 and 300 lines for each bank statement and then returning to the first statement, in order to page 40 lines on each page with a considerable jump in the ids

**Comment by mge-odoo** [comment]
Fixed by odoo/odoo@a16013b

Thanks for reporting.

Martin
