### ISSUE TITLE
ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#22779]
when i start my odoo in linux ubuntu
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
ImportError: No module named pkg_resources

how can i solve it??

**Comment by Yenthe666** [comment]
@d-fence this looks relevant to you.
@spectra10008 is this Odoo version 11? How did you install the Odoo?

**Comment by d-fence** [comment]
Do you have the "python3-setuptools" or "python-setuptools" installed ?

**Comment by spectra10008** [comment]
For yenthe666:-

installed by command in odoo essential developing book .. just fallow instructions

**Comment by spectra10008** [comment]
For d-fence:-
no I installed python 2.7

**Comment by d-fence** [comment]
Can you try with "python-setuptools" (apt install python-setuptools) ?

**Comment by spectra10008** [comment]
Ok I will

**Comment by Yenthe666** [comment]
@spectra10008 any feedback?

**Comment by spectra10008** [comment]
no

**Comment by spectra10008** [comment]
not fixed

**Comment by Yenthe666** [comment]
@d-fence I guess ther eis more work for you 😉

**Comment by spectra10008** [comment]
i had to remove reinstall odoo again

**Comment by Ahmed-Shukr** [comment]
You need to check the version of setuptools you are using, if it is 82, you need to downgrade it

pip install 'setuptools<82'
