### ISSUE TITLE
Replace the picture of the General Director

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#22773]
Impacted versions:
11.0
Steps to reproduce:
goto https://github.com/odoo/odoo/tree/11.0/addons/hr/static/img/employee_fp-image.jpg

Current behavior:
Odoo General Director and inventor
![spayderman](https://github.com/odoo/odoo/raw/11.0/addons/hr/static/img/employee_fp-image.jpg)

Expected behavior:
I think this photo will be more consistent with the General Director.
![employee_fp-image](https://user-images.githubusercontent.com/34191760/35758246-9adba530-087b-11e8-8cf6-b627c50d2bd9.jpg)

I created this photo from [this](http://www.gettyimages.com/detail/92627279) photo.
You can use it as a GPL license. Those. I give to this picture all the rights to use, modify, etc.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@fpodoo as you're the person that this topic is about. What do you say? ;)
