### ISSUE TITLE
[11.0] Missing Access Rights for Portal User

### ISSUE THREAD

**Issue by dion-pci** [odoo/odoo#22789]
Impacted versions:
11.0 (both Community and Enterprise)

Steps to reproduce:
The easiest way to reproduce is by using Odoo demo data. Create a fresh database using demo data (with no module installed), then login as the default portal user (user: portal, pass: portal)

Current behavior:
Enterprise edition throw an access error for `ir.ui.menu' model
Community edition stopped at login page and showed the following message.
`Only employee can access this database. Please contact the administrator.`

Compared to the older version (10.0), the `portal` module is missing the necessary access rights.

Expected behavior:
Portal user can login and access Odoo normally.

Video/Screenshot link (optional):
![2018-02-05-114838_1600x876_scrot](https://user-images.githubusercontent.com/28971196/35789039-dd350132-0a6b-11e8-8b9b-216c2741e06c.png)
![2018-02-05-115724_1600x876_scrot](https://user-images.githubusercontent.com/28971196/35789041-e10095e2-0a6b-11e8-80b1-07e1b184ab71.png)

**Comment by sswapnesh** [comment]
Hello @dion-pci 
Make sure you have installed `portal` module.

**Comment by dion-pci** [comment]
Alright, I tried it again with `portal` module installed per @sswapnesh suggestion. The portal user can login now, but it now simply directly to a minimized version of `website` module.

![2018-02-06-075957_1600x876_scrot](https://user-images.githubusercontent.com/28971196/35836680-35e5f54a-0b14-11e8-9f82-4db26fce4610.png)

I don't know if this is intentional or not, but I can't find any references about the portal being changed in the 11.0 release notes. Nor in the module itself. Is there any proper explanation about this?

**Comment by vcloud9ray** [comment]
![image](https://user-images.githubusercontent.com/31354495/35841841-2e285b38-0ab3-11e8-95ba-4e2904949aae.png)

**Comment by dion-pci** [comment]
Yes, I'm aware of that. My exact question is, is there any proper explanation about the change? What happen to the old method of limited access to Odoo modules? And how we should adapt to this for custom model?

I'll close this for now since this issue is not really an issue, but rather a poorly documented changes.
