### ISSUE TITLE
[11.0][10.0][IMP] MRP work sheet in BoM instead of Route

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22787]
Impacted versions: 11 and 10 confirmed but probably all

Work sheet and overall documents to be displayed on Work Orders are set per operation under route, this limits Odoo's MRP to companies which manufacture the same products over and over again.

Other manufactures that want to have their data sheets on WO but are MTO (ie. furniture, printing and marketing materials) are too uncomfortable of being set up in Odoo because you would have to create a route per every BoM even if it's the very same route but only the work sheet is what's different.

By having the Work Sheet moved to the BoM it will be able to handle every production scenario. Having it considered in both places would be the best.

**Comment by sle-odoo** [comment]
@lap-odoo for a feedback

**Comment by lap-odoo** [comment]
Ok, added in our feedbacks 

@edsersolis It's not in our plans yet to modify this but I've taken good note of your feedback, thanks
