### ISSUE TITLE
Product image gets duplicated in Website Shop image carousel

### ISSUE THREAD

**Issue by jlopezg** [odoo/odoo#22786]
**Impacted versions**:

- 11.0
- 10.0

**Steps to reproduce**:

1. Create a product with at less two variants
2. Set an image to the first product variant
3. Set an image to the second product variant
4. Set an image to the first product variant (again)
5. Go to Website > Shop and search for your product

**Current behavior**:
First variant (the one with the smallest database id number) image gets duplicated in Website Product Image Carousel

**Expected behavior**:
Image should not get duplicated

**Video/Screenshot link (optional)**:

<img width="869" alt="screen shot 2018-02-04 at 10 59 00 pm" src="https://user-images.githubusercontent.com/16394301/35786665-3e05171c-09ff-11e8-999a-c1fa8a272b0a.png">

<img width="845" alt="screen shot 2018-02-04 at 10 59 09 pm" src="https://user-images.githubusercontent.com/16394301/35786668-421a13de-09ff-11e8-9ffe-6e1aae416145.png">

<img width="852" alt="screen shot 2018-02-04 at 10 59 17 pm" src="https://user-images.githubusercontent.com/16394301/35786671-44f243a6-09ff-11e8-8294-f9dd44bdad3e.png">

**Comment by edsersolis** [comment]
I can confirm the issue. This may confuse customers who don't know the product, it should only show the variant that is selected, other pictures in the carousel should be of the same variant if set.

**Comment by andrp92** [comment]
Same here. A customer who doesn't know the product, may get confused by having pictures shown of other product variants' in the carousel of a selected product.

**Comment by esantos-octagono** [comment]
I got the same problem.

**Comment by gustavovalverde** [comment]
Confirming this issue.

**Comment by Yenthe666** [comment]
@gustavovalverde this is something for the web team. More something for @JKE-be 😉

**Comment by gustavovalverde** [comment]
@Yenthe666 I'll learn, just give me time 😅

**Comment by Yenthe666** [comment]
Absolutely! https://github.com/odoo/odoo/wiki/BugManagement#issues should be of interest for you. It has quite a good and updated list.

**Comment by gustavovalverde** [comment]
That's great @Yenthe666, didn't know that resource existed. Thanks.

**Comment by qsm-odoo** [comment]
Hello,

I understand the problem and acknowledge this for a future improvement. If I am not mistaken, the current behavior is designed to:
- With multi image option enabled: show the variant image first, then the template image (which you can set to be a generic one), then the additional template images
- With multi image option disabled: show only the variant image

So in your example, disabling the multi image option does what you want. And if you need the multi image option, you can set the "ball" template image to a generic ball image.

I agree the behavior should be better customizable though.

**Comment by gustavovalverde** [comment]
@qsm-odoo based on this part of your comment:

> And if you need the multi image option, you can set the "ball" template image to a generic ball image.

If we don't have multi-images for a 60% of our products, wouldn't be easier that those products without a multi-image set on their variants, just don't show the carousel?

I might be underestimating the solution, but it seems theoretically simple.

The issue as-is is not the multi-image feature, it's that it gets activated without having a secondary image on the first variant. And it won't happen always, but just if you decide to update the first picture you set in the product. 

**Summarizing**: This is not a change on the actual feature, it's just a bug that makes the feature active when it shouldn't.

**Comment by qsm-odoo** [comment]
The multi-images options is a global website option, when you enable it, that is for all products. When this option is enabled, we show the 3 kind of images: variant / template / others (in the "ball" example, there is no "others" images). Otherwise we show only the variant one.
The problem here is a functional one, so we cannot make XML/python changes in stable to improve that. Showing the template image makes sense, we should just improve our code to be able to hide it if necessary.

**Comment by jlopezg** [comment]
Thank you @qsm-odoo for take your time to check this issue.

I got to say that I haven't get convinced yet. 

I personally think that this issue I created has been misunderstood. Let say I have not explained it in the most explicit way.

First, I agree that the current functionality of Multi-images makes product in eCommerce shows the 3 kind of images you commented above (variant / template / others). But actually there is a weird behaviour that should be checked.

This is my Product Template "Ball". **Note the white ball picture and that no picture is set in Images tab (secondary images).**

<img width="1198" alt="screen shot 2018-02-07 at 11 57 43 am" src="https://user-images.githubusercontent.com/16394301/35926314-3d8dc580-0bfe-11e8-94d7-25c530561012.png">


This Product Template has 3 variants. The Red, Blue and Yellow balls. Each one have it own image.


<img width="1195" alt="screen shot 2018-02-07 at 11 11 20 am" src="https://user-images.githubusercontent.com/16394301/35924866-a07b832a-0bfa-11e8-925e-6a6ea99ab163.png">

<img width="1207" alt="screen shot 2018-02-07 at 11 11 26 am" src="https://user-images.githubusercontent.com/16394301/35924870-a3f7ebc4-0bfa-11e8-8e77-418d22f820be.png">

<img width="1202" alt="screen shot 2018-02-07 at 11 11 35 am" src="https://user-images.githubusercontent.com/16394301/35924958-d6a3034c-0bfa-11e8-9d37-91e44e3260d6.png">

Everything looks good from here. Now let see what happen in my eCommerce.

As you can see, the Product Template image is shown as the main product picture. Great.

<img width="850" alt="screen shot 2018-02-07 at 11 11 56 am" src="https://user-images.githubusercontent.com/16394301/35925070-26a59134-0bfb-11e8-8344-b754ef91e147.png">

Now is when it gets weird.

Let's take your explanation to this place, just to be in context.

> I understand the problem and acknowledge this for a future improvement. If I am not mistaken, the current behavior is designed to:
> 
> With multi image option enabled: show the variant image first, then the template image (which you can set to be a generic one), then the additional template images
> With multi image option disabled: show only the variant image
> So in your example, disabling the multi image option does what you want. And if you need the multi image option, you can set the "ball" template image to a generic ball image.

Now that we all are in the same page, let's take a look at this:

This is the product variant Color: Red, of my Product Template "Ball"

<img width="1158" alt="screen shot 2018-02-07 at 11 12 16 am" src="https://user-images.githubusercontent.com/16394301/35925431-0fe94ed0-0bfc-11e8-97b3-bbb365443d4a.png">

Note how the Red Ball image gets duplicated in the carousel. It is suppose to show the variant image and the template image, but it doesn't.

Now look at this:

<img width="1151" alt="screen shot 2018-02-07 at 11 12 24 am" src="https://user-images.githubusercontent.com/16394301/35925543-5d1cf3f0-0bfc-11e8-85ab-799bda6768f7.png">

<img width="1091" alt="screen shot 2018-02-07 at 11 12 34 am" src="https://user-images.githubusercontent.com/16394301/35925553-61024268-0bfc-11e8-864a-9b24db29d566.png">

See how Red Ball picture is shown in other variants?

**As I said in my first entry, take into account that the duplicated image is the one who belongs to the variant with the smallest database id.**

I really hope this explanation is clear enough.

Greetings!

**Comment by qsm-odoo** [comment]
Oh ok, from the steps you explained initially, I thought that your product template's image had been automatically set to the red ball image (as in your steps you updated the first variant's image without setting the template's one first).

The problem you are describing now was indeed a bug that I fixed some days ago with commit https://github.com/odoo/odoo/commit/d295b4360db93a0d3333153098e623e573ac099b. So I suppose that if you take the latest version of the Odoo version you are using and that you properly update the `website_sale` app, your problem should be solved.

**Comment by jlopezg** [comment]
Confirmed! Thank you @qsm-odoo
