### ISSUE TITLE
[11.0][Bug] stock: bad reservation with product with unique serial number

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#22781]
Impacted versions: 11

Steps to reproduce:
- create a `product A` with serial number
- add 2 `product A` in stock
- create a delivery order with this 4 product
- Check Availability
- in Detail opration you see 2 lines with quantity = 1 --> OK
- add 2 more `product A` in stock
- Check Availability
- in the first line the quantity is now 3 --> **Not OK**

![image](https://user-images.githubusercontent.com/16716992/35778672-ca24b1b4-09c1-11e8-8292-670cc45176d5.png)

https://github.com/odoo/odoo/pull/22782

OPW-814441

@alnslang @sylvain-garancher

**Comment by sle-odoo** [comment]
nice catch 👍 i'll have a look this week. thanks

**Comment by amoyaux** [comment]
Hi @fmdl I modified a bit your commit https://github.com/odoo-dev/odoo/commit/9b09010765e5f87976012dd6119850c9d1a469c0

I removed the product_uom_qty == 0 since quantity is not always equals to 1 and this you will keep the same issue. Do you want to keep the authorship?

**Comment by fmdl** [comment]
I have add this condition `product_uom_qty == 0`, if case. If not `m.product_id.tracking == 'serial'` is enought.

**Comment by amoyaux** [comment]
Pushed on v11.0 with commit ee7e9198f2ef7b468b929c8dec14570e6af1afcf

Thanks for reporting
