### ISSUE TITLE
can't edit a Sales Order Description

### ISSUE THREAD

**Issue by mario-lopez-dnoise** [odoo/odoo#22797]
Impacted versions: 11

Steps to reproduce:
1.- Create a new SO
2.- Fill Description Field
3.- Save SO
4.- Edit SO
5.- Change Description Field

Current behavior:
Description Field must keep new value
Expected behavior:
Description Field doesn't change

Video/Screenshot link (optional):

**Comment by ThijsvOers** [comment]
Hi Mario,
On my 11 version and also on runbot you can edit the so line description field as long the SO is not locked. Could it be that your SO is locked?

**Comment by mario-lopez-dnoise** [comment]
SO was not blocked, but, if I block It and unblock again description can change.

If I move products in the same SO with drag&drop they doesn't move correctly and come back to original position

Example:
PROD111
PROD222

I drop PROD222 to first place:

Still seeing:
PROD111
PROD222

Expected behavior:
PROD222
PROD111

Drag&Drop for me doesn't work.

**Comment by mario-lopez-dnoise** [comment]
I think odoo shows the views with a some frontend cache.
Navigator cache is disabled, but I don't know how can disabled the odoo cache

**Comment by sswapnesh** [comment]
Hello @mario-lopez-dnoise 
I have tested same on [Runbot](runbot.odoo.com).
Description and  drag&drop for Order line are working fine, Odoo is not using cache for handling Display sequence.

Make sure you are on the latest Source code.

**Comment by mario-lopez-dnoise** [comment]
tested on odoo 11 with github installation: All's ok.
We will install it again
Thanks.

**Comment by sswapnesh** [comment]
I believe we can close this as Related Issue was solved after Code update.

**Comment by Yenthe666** [comment]
@sswapnesh it is already closed 😉

**Comment by sswapnesh** [comment]
> @sswapnesh it is already closed

Right My bad. But actually I was asking to close related Open Issues. (Was too fast)

**Comment by Yenthe666** [comment]
Done 😄
