### ISSUE TITLE
what I need to learn before studies odoo

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#22801]
I mean do I need to learn all about python or xml ??..

**Comment by sle-odoo** [comment]
Hi,
This is a bug tracker, thus it is not the right place for this kind of questions. Please use our forums instead.

Regards

**Comment by Yenthe666** [comment]
P.S: You can find the forums at help.odoo.com or you can have a look in the documentation at https://www.odoo.com/page/docs

**Comment by sehrishnaz** [comment]
Learnopenerp.blogspot.com
You can Learn odoo from scratch
