### ISSUE TITLE
Rounding Error in Lot Traceability

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#22815]
Impacted versions:

- v11

Steps to reproduce:

- Inventory → Settings → Traceability: activate "Lots & Serial Numbers"
- Order 3.57 units of a product
- Confirm order
- Receive delivery, assign a lot number and confirm 3.57 units received
- Confirm
- Click "Up/Down Traceability"

Current behavior:

- On the "Upstream Traceability" notice you find 3.5700000000000003 units in the lot

Expected behavior:

- 3.57 units in the lot

Screenshot link:

![po](https://user-images.githubusercontent.com/29736794/35828796-1f83f2b4-0ac1-11e8-9847-3794544d80b5.png)

![in](https://user-images.githubusercontent.com/29736794/35828811-2add5042-0ac1-11e8-9dd5-146421a8dda2.png)

![lot](https://user-images.githubusercontent.com/29736794/35828818-306a0488-0ac1-11e8-9c9b-f7806a3419fd.png)

Note: 

Rounding issues are found in many spots, see
https://github.com/odoo/odoo/issues/20784
https://github.com/odoo/odoo/issues/22214

**Comment by Yenthe666** [comment]
@sle-odoo another rounding widget missing on the report I guess?

**Comment by sle-odoo** [comment]
@Yenthe666 not that easy since this report is all prepared server side (see [here](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_traceability.py#L158)). We probably should directly call [this method](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_qweb/fields.py#L134).

**Comment by proloycoder** [comment]
Done

**Comment by lap-odoo** [comment]
@sle-odoo Master bug 817420 created. A PR will be soon available for review.

**Comment by sle-odoo** [comment]
fixed at https://github.com/odoo/odoo/commit/e3a0d926d6e7d13a54537e1fb3d3a29f6922159b
thanks for the report
