### ISSUE TITLE
Email template editor breaks template

### ISSUE THREAD

**Issue by amatosg** [odoo/odoo#22821]
Impacted versions: 11.0.20171202 (maybe others)

Steps to reproduce: Open email template, edit, save and preview email

Current behavior: body is blank with extra code in the template.

Expected behavior: body should have the changes

Video/Screenshot link (optional):

Before editing
![image](https://user-images.githubusercontent.com/4570069/35842796-802043dc-0ad2-11e8-9b3e-8a059e3ff12f.png)

After editing
![image](https://user-images.githubusercontent.com/4570069/35842802-8cf6b87a-0ad2-11e8-9724-c875be92dce0.png)

**Comment by Yenthe666** [comment]
Hi @amatosg,

Thanks a lot for the bug report.
Can you reproduce this on the latest Odoo test instance (at runbot.odoo.com)? Do you do everything from the frontend?
I see your Odoo source code is quite old too, please update it to the latest version.

Regards,
Yenthe

**Comment by amatosg** [comment]
Hi @Yenthe666 
Do you think 11.0.20171202 is too old (honest question)? although I see 11.0.20180204 available to download but it's a nightly release and I don't want things to be broken.
I haven't tried the test instance, but take it a look at home.
And yes, I do it on the front end.

**Comment by Yenthe666** [comment]
@amatosg,

I try to update the Odoo source atleast once every two months really. Please do try it on a test instance. If you can reproduce it can you please add a video or detailed info on how to reproduce it on a runbot then?

**Comment by amatosg** [comment]
yes, will do as soon as I get home, but to reproduce it, I just edit a template (add a new line, for example), specifically the invoice template, and then pressed the "preview" button, the preview has a blank body.

**Comment by Yenthe666** [comment]
Seems to work fine out of the box on the latest 11.0 so I'll wait for your feedback. 😉

**Comment by amatosg** [comment]
One last thing, it's a nightly? on which version did you test it? I'm at 11.0.20171202 =/

**Comment by Yenthe666** [comment]
From runbot.odoo.com so the instances from today.

**Comment by amatosg** [comment]
I updated to the last nightly (I think it was 20180210) and the issue is gone. I have to say, it was very annoying, the email was even showing the `% if` and `% else` statements. Anyways, I'm happy this is not affecting my instance anymore :smiley:

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!
