### ISSUE TITLE
[8.0] qweb doesn't use digits option for float like views does

### ISSUE THREAD

**Issue by houssine78** [odoo/odoo#2282]
The qweb engine doesn't use the digits option like the views does. 

According the code you can pass options to the function but it does nothing with it. Which is quiet problematic for reporting.

The code should in fact use the digits option it takes in params. It looks like an unfinished work.

![ir_qweb](https://cloud.githubusercontent.com/assets/7766650/4200426/0a0c5b96-3811-11e4-89d2-a9bc5b766450.png)

**Comment by Yenthe666** [comment]
Hi @houssine78 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: As this is labelled wishlist it will keep popping up.

Regards,
Yenthe
