### ISSUE TITLE
Picking State changes to Ready when deleting a stock move

### ISSUE THREAD

**Issue by gralet** [odoo/odoo#22834]
Impacted versions:
11.0

Steps to reproduce:
1. From Inventory dashboard, create a "Planned Transfer" with 2 products
2. Save
3. Exit to another menu
4. Come back on the picking
5. Delete one line

Current behavior:
The picking state automatically changes from "Draft" to "Ready"

Expected behavior:
The picking state should not change  (stay in Draft)

Remark:
This maybe comes from :  stock_move._recompute_state() 

Video/Screenshot link (optional):

<img width="915" alt="new planned transfer" src="https://user-images.githubusercontent.com/11177216/35853519-ff8518b8-0b2d-11e8-81b2-f6b759c0eab3.png">

<img width="1022" alt="auto change state on delete" src="https://user-images.githubusercontent.com/11177216/35853534-09e960d4-0b2e-11e8-9a20-cf3c8f7530df.png">

**Comment by sswapnesh** [comment]
Hello @gralet 
I believe it is correct as you are creating Transfer of Receipt type.

**Comment by gralet** [comment]
It does the same for all type of transfer.
For example "DropShip", or "Internal Transfers" (if you activate "Multi-Step Routes")

**Comment by sswapnesh** [comment]
Does it works same for Delivery also?

**Comment by gralet** [comment]
For Delivery Orders it seems the delete button on Operations (Stock move) is deactivated.

**Comment by sswapnesh** [comment]
@amoyaux  Could you please confirm?

**Comment by sle-odoo** [comment]
as planned_transfer is not in the context, the autoconfirm is triggered
maybe we should skip the autoconfirm if there's at least an intial demand in one of the move
