### ISSUE TITLE
can not create new database in ubuntu 16.04 LTE

### ISSUE THREAD

**Issue by naitikvithlani** [odoo/odoo#22832]
Impacted versions:
10 Community
Steps to reproduce:
Just create new database using create database button
Current behavior:
It seems the error like attached screenshot.
Expected behavior:
It should create database without error
Video/Screenshot link (optional):
![odoo](https://user-images.githubusercontent.com/6597323/35851573-018d6f66-0b5b-11e8-95a8-1816378f695f.jpeg)

**Comment by Yenthe666** [comment]
Hi @naitikvithlani,

Have you installed all the required Odoo dependencies? (See https://github.com/odoo/odoo/blob/10.0/requirements.txt)
Are you running on the latest source code?
Does the Odoo have suffecient rights on all the files?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
