### ISSUE TITLE
Permissions do not register field change

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#22857]
**Impacted versions:**

11.0

**Steps to reproduce:**

Download and restore backup: [odoo_2018-02-06_17-50-03.zip](https://github.com/odoo/odoo/files/1700186/odoo_2018-02-06_17-50-03.zip)

Data:
Two Sales Channels: "Sales" and "Sales2"
Two invoices one in Sales Channel "Sales" and one in Sales Channel "Sales2"
One rule for account.invoice: [('team_id', '=', user.sale_team_id.id)]
User "Test" assigned to "Sales2" channel

1. Log in (user: test, pass: test)
2. Go to invoices, there is one invoice visible INV/2018/0001
3. Go to Sales -> Configurartion -> Sales Channels
4. Add user "test" to "Sales" sale channel
5. Go to Invoices, There is one invoice visible INV/2018/0001 - assigned to "Sales2"

Video: https://www.youtube.com/watch?v=jv3FRf6-iC4

**Current behavior:**

After changing users "Test" sales channel from "Sales2" to "Sales" INV/2018/0001 is still visible. Permission error when trying to access INV/2018/0002

**Expected behavior:**

User should have access to INV/2018/0002 invoice instead of INV/2018/0001

**Comment by oco-odoo** [comment]
@grzekru I managed to reproduce you problem locally. After investigating it, though, it appears it is not a bug in itself, but some side-effect of the caching performed by the ORM on server side. To apply the rule immediately, you can simply kill and restart the server, as it will clear the cache.
