### ISSUE TITLE
Removal strategy "FEFO" does not work

### ISSUE THREAD

**Issue by gralet** [odoo/odoo#22850]
Impacted versions:
11.0

Steps to reproduce:
1. In Inventory settings, activate Lot tracking
2. On one product, set tracking = "By Lot"   (imac)
3. Set Removal Strategy = "FEFO" on product category  
4. Create 3 lots with 3 distinct expiry date (End of Life Date), the second one having the first expiry date
5. Update quantity on hand on 3 lots (quantity = 5)
6. On Operation Type = Delivery Orders, activate checkbox : "Show Detailed Operations"
7. On inventory Dashboard, Delivery Orders, create a new "Planned Transfer"
8. Choose the product, and set Initial Demand  (quantity = 2), Save, Mark as Todo
9. Click "Check Availability"

Current behavior:
The reserved lot is not the first expired

Expected behavior:
The system should reserve the first expired lot
(or I missed something)

Video/Screenshot link (optional):

<img width="1021" alt="categ" src="https://user-images.githubusercontent.com/11177216/35863115-edddf736-0b4d-11e8-90e7-9c9ee6838c1a.png">

<img width="1021" alt="quants" src="https://user-images.githubusercontent.com/11177216/35863125-f273938c-0b4d-11e8-8bbb-c0f4ea3cd8ad.png">

<img width="1022" alt="lots" src="https://user-images.githubusercontent.com/11177216/35863542-50f4b8b8-0b4f-11e8-87ab-74f431976df6.png">

<img width="1022" alt="pick" src="https://user-images.githubusercontent.com/11177216/35863267-766f4e1a-0b4e-11e8-80d9-42d910247d5d.png">

**Comment by amoyaux** [comment]
Use removal date instead of expiry date
