### ISSUE TITLE
[11.0] Bank staments Lines- Bad cursor pointing when showing reference field in list view

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#22859]
Impacted versions:
11.0

Steps to reproduce:
- Set debug mode in order to show reference field in bank statement lines
- Create a bank statement
- Add a line
- Try to set an amount
Current behavior:
When clicking or tabbing to the amount column, the cursor changes the position to another cell of the list

Expected behavior:
Improve the usability and allow set the amount does not matter if reference field is showed

Video/Screenshot link (optional):
https://youtu.be/kBk6YZYl69I

**Comment by luistorresm** [comment]
Hello @Yenthe666 @lap-odoo 

Do you have news about this Issue?

Regards

**Comment by Yenthe666** [comment]
Hi @luistorresm,

No, there is no feedback at the moment.
When somebody from Odoo starts at this or fixes it it'll be added here.
If you face this issue and have an enterprise license you can also report it to odoo.com/help with a link to this issue to get it handled faster.

Regards,
Yenthe

**Comment by kebeclibre** [comment]
@luistorresm 
Hi,
The issue seems to be gone with the latest revision. Do you confirm ?

**Comment by hugho-ad** [comment]
@kebeclibre 

Hello,
it is not fixed yet, I was able to reproduce it in http://311537-11-0-1ddaf0.runbot13.odoo.com

Regards!

**Comment by Yenthe666** [comment]
@hugho-ad perhaps it is nice/easy to add a little recording here that shows @kebeclibre how to reproduce this?

**Comment by hugho-ad** [comment]
@Yenthe666 @kebeclibre 

The video is in the issue description
https://youtu.be/kBk6YZYl69I

In the same way I was able to reproduce it in http://311537-11-0-1ddaf0.runbot13.odoo.com

Regards!
