### ISSUE TITLE
Language settings nl_NL

### ISSUE THREAD

**Issue by thomaspot** [odoo/odoo#2286]
I think my issue has nothing to do with translations, but I'm not sure.

As for default settings of Language could we set the default settings as below:
For every new server we have to edit these settings. I would propose to change it.

Settings->Translations->Languages

for nl_NL change these settings as default:

![screenshot-p200 prod open2bizz nl 2014-09-09 13-55-15](https://cloud.githubusercontent.com/assets/8189005/4200964/3e7a9f8a-3818-11e4-8fba-15a0100c0a3c.png)

1. Change date format to "%d-%m-%Y"
2. Change decimal to "," (comma)
3. Thousand seperator: "." (dot)

**Comment by lualpa** [comment]
That is absolutely correct. The US format is actually replicated for every language I have reviewed so far (I have tested NL, NO, UK, two versions of FR and two versions of ES). And re the Thousands separator, even though it is listed, it does not show.

**Comment by Yenthe666** [comment]
@mart-e this is actually still the same up until today.
Do you think we could add in an option for this? It would be handy.

**Comment by mart-e** [comment]
Hello,

These settings are done [based on](https://github.com/odoo/odoo/blob/def824682edc770a79128ee7ed80661dfb68140f/openerp/addons/base/res/res_lang.py#L51) the local installed on the machine you are running. The fallback is done on the main locale of the server. So if you want another language, you need to install it on your server first.

The good news is that we have changed that in master (around saas-9 I think) to include all languages in data file with the correct info.
