### ISSUE TITLE
[odoo 11] _merge_quants takes too long for large stock_quant table

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#22866]
I am working on migrating an odoo 10 database to odoo 11 database in which there are 5 million rows of stock quants. The problem we are facing is that the method _merge_quants takes very long time to complete. Actually I don't know how long does it take. It had been running for 2 days before I shut it off.
This method was introduced by this commit d547f63cb76936427c2f6c87fc919d291f4e625a and consolidated by this commit bb87187cd8225e8007077cd1c1e0500b0f6802f5.

The problem comes from the delete query `DELETE FROM stock_quant WHERE id in (SELECT unnest(to_delete_quant_ids) from dupes)` which has very bad performance
I ran a part of that query to find out how many quants to update/delete:
```
                            SELECT min(id) as to_update_quant_id,
                                (array_agg(id ORDER BY id))[2:array_length(array_agg(id), 1)] as to_delete_quant_ids,
                                SUM(reserved_quantity) as reserved_quantity,
                                SUM(quantity) as quantity
                            FROM stock_quant
                            GROUP BY product_id, company_id, location_id, lot_id, package_id, owner_id, in_date
                            HAVING count(id) > 1
        """
```
The result showed up that there were more than 4 million rows that need to be deleted.

Is there a solution to improve such the large deletion?

**Comment by sle-odoo** [comment]
Hello,
I know @jco-odoo stumbled over this issue and found that adding some indexes (or removing, i don't remember) solved the issue. He'll tell you more.

Regards

**Comment by jco-odoo** [comment]
Please wait for proper migration scripts or check your foreign keys.
