### ISSUE TITLE
[10]Cannot be completed due to security restrictions. Please contact your system administrator. (Document type: Applicant, Operation: write)

### ISSUE THREAD

**Issue by Tinhnguyen96** [odoo/odoo#22864]
Hi,
I have created two users in Odoo10.
User1 is dept_manager & User_2 is interviewer on "hr.applicant" models.
*.py file:
![py](https://user-images.githubusercontent.com/32927838/35897062-f8e2ad12-0bf1-11e8-83e7-2ef8cc9bfcd4.png)

*.csv file (new groups)
![csv](https://user-images.githubusercontent.com/32927838/35896888-116808ce-0bf1-11e8-8a2b-206bebf25db5.png)

and i have create rule for them:
![rule](https://user-images.githubusercontent.com/32927838/35896976-7ac34aa4-0bf1-11e8-85bb-e24707225ce2.png)

But when I try to edit a application with User_1 & User_2 account, I am getting the following error:
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: Applicant, Operation: write)
(Note: If i inactive "Department Manager: Applications" & "Interviewer: Applications" rules, I can create a normal applicant. I don't understand it, please help me!)
Thank,

**Comment by Yenthe666** [comment]
Hi @Tinhnguyen96,

The Github issue tracker is only for bugs in the official code and is not the place to ask questions about custom development.
Please post these kind of questions on the official help forum (at help.odoo.com).

Regards,
Yenthe
