### ISSUE TITLE
[12.0/?] FEATURE REQUEST: Introduce GraphQL Implementation In Odoo In Addition To RPC

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#22871]
<h1>Impacted versions:</h1>
12.0/13.0/14.0/?

<h1>Steps to reproduce:</h1>
N/A

<h1>Current behaviour:</h1>
No Support for GraphQL

<h1>Expected behaviour:</h1>
It would be incredibly useful to have a GraphQL implementation in core Odoo in a similar manner to the current RPC implementation.

<h1>Existing Odoo Integration:</h1>
There seems to be some initial work that's been done for this by @adaptivdesign here:<br/>
<a href="https://github.com/odooku/odooku-graphql">https://github.com/odooku/odooku-graphql</a>
<h1>Additional Info:</h1>
<a href="http://graphql.org/">http://graphql.org/</a><br/>
<a href="https://blog.apisyouwonthate.com/tagged/graphql">https://blog.apisyouwonthate.com/tagged/graphql</a><br/>
<a href="https://nordicapis.com/5-potential-benefits-integrating-graphql/">https://nordicapis.com/5-potential-benefits-integrating-graphql/</a><br/>
<a href="https://medium.freecodecamp.org/so-whats-this-graphql-thing-i-keep-hearing-about-baf4d36c20cf"/>https://medium.freecodecamp.org/so-whats-this-graphql-thing-i-keep-hearing-about-baf4d36c20cf</a><br/>

<h1>Benefits:</h1>
<ul>
<li>My Use Case:
  <li>Realm.io DB Server (Used in many of the top mobile apps on both Android & iOS app stores). Used in development of ReactNative apps, as well as elegant handling of offline-first style functionality for applications (whether iOS,watchOS,Android,OSX,Windows,etc.), removing the need to build some of the complex logic required to handle this feature set to allow for 'eventual consistency' for offline-first style applications.</li>
</li>
</ul>

More information to be added to this issue at a later date.

**Comment by Elkasitu** [comment]
Hi, thanks for the feature request, we already have an internal task on _potentially_ using GraphQL within Odoo but it's just an idea, there's no priority on it or anything.

What I'm saying is that we're aware of GraphQL's popularity and its benefits, but we're not committing any resources into it for the time being :^)

**Comment by lukebranch** [comment]
@Elkasitu ,

Thanks for letting me know, it's great to know it's being considered. There are alot of forward-looking companies like Realm that have been adopting it, and it looks to be quite useful as a replacement for RPC eventually.

**Comment by Yenthe666** [comment]
Oooh, I never heard about this but it looks very neat!

**Comment by gustavovalverde** [comment]
@Elkasitu let our prays be heard, and change that for v12 🙏

**Comment by antonylesuisse** [comment]
Not planned yet.
