### ISSUE TITLE
[FIX][BUG][9.0alpha1]Analytical account was not added on function 'check_tax_lines'

### ISSUE THREAD

**Issue by 10537** [odoo/odoo#2288]
I'm migrating some modules to the new version of Odoo and see this detail on 'account_invoice' on line 711, in function 'check_tax_lines':

 @api.multi
    def check_tax_lines(self, compute_taxes):
        account_invoice_tax = self.env['account.invoice.tax']
        company_currency = self.company_id.currency_id
        if not self.tax_line:
            for tax in compute_taxes.values():
                account_invoice_tax.create(tax)
        else:
            tax_key = []
            for tax in self.tax_line:
                if tax.manual:
                    continue
                #~ This key need the analityc account ------------------------------------
                key = (tax.tax_code_id.id, tax.base_code_id.id, tax.account_id.id)
                #~ ---------------------------------------------------------------------------------
                tax_key.append(key)
                if key not in compute_taxes:
                    raise except_orm(_('Warning!'), _('Global taxes defined, but they are not in invoice lines !'))
                base = compute_taxes[key]['base']
                if abs(base - tax.base) > company_currency.rounding:
                    raise except_orm(_('Warning!'), _('Tax base different!\nClick on compute to update the tax base.'))
            for key in compute_taxes:
                if key not in tax_key:
                    raise except_orm(_('Warning!'), _('Taxes are missing!\nClick on compute button.'))

**Comment by pedrobaeza** [comment]
This has been changed so long ago, so I close it.
