### ISSUE TITLE
Trackback : While Confirming the SO (Singleton) Issue.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#22880]
Impacted versions:

	> OdooV11 Enterprise

Steps to reproduce:
	> Make sure 'sale_subscription' module is installed !
	> Create Sale order > Select Add 2 or more than order lines with product belongs to same subscription template.
		(e.g Here product odoo_custom_module belongs to sale subscription template 'MON - Odoo Monthly'.)
	> Now confirm the SO ,Cancel it, Click on 'Set to Quotation' and again confirm the SO.

Current behavior:
	> Its should allow to confirm the SO without any error.But generating Traceback of Singleton.

Expected behavior:
	> Its should allow to confirm the SO smoothly.

Solution :
	> Need to iterate the loop for it 
	   > Module : 'sale_subscription',
           > as method named '_update_subscription_line_data' getting multiple sale subscription lines.
	
Video/Screenshot link (optional):

	Screenshot > 	https://www.awesomescreenshot.com/image/3157084/6b4443f64ec4ff26f552f9ae1164de51

	Video > 	https://youtu.be/LfSJbuMUHjo

Thanks.

**Comment by Yenthe666** [comment]
Hi there,

This issue has been fixed in the meanwhile at https://github.com/odoo/enterprise/commit/8301c8e52434796baf6c1573a2ac52c882442671#diff-7a59e6cf02bef33dc92534f56545c1b5

Regards,
Yenthe
