### ISSUE TITLE
[10.0][11.0] Default country in res.partner should be the company's country, not Argelia.

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#22885]
### Impacted versions:
10.0, 11.0

### Steps to reproduce:
Create a partner

### Current behavior:
Argelia is set as the country

### Expected behavior:
If a default country is going to be set, then it should be the country of the company, otherwise it shouldn't be set, as this causes to have unreal and "trash" information on partners.

**Comment by Yenthe666** [comment]
@mart-e perhaps we should improve this for the upcoming V12?

**Comment by edsersolis** [comment]
On earlier versions it would just stay empty. It was better like that.

**Comment by vcloud9ray** [comment]
I can't replicate on http://300876-11-0-7ff518.runbot8.odoo.com/ (v11)

![image](https://user-images.githubusercontent.com/31354495/35954835-d1b6cd96-0c40-11e8-8774-05f56e5ad4c8.png)


![image](https://user-images.githubusercontent.com/31354495/35954839-d41c6ee2-0c40-11e8-8e7a-57bb233a5d29.png)

**Comment by Yenthe666** [comment]
Actually, I just tried this with a database made with the country of the Netherlands and the whole Dutch accounting scheme etc. After creating a new partner:
![image](https://user-images.githubusercontent.com/6352350/35959245-11164002-0ca5-11e8-8eb5-a176999f3614.png)
@gustavovalverde do you have any custom development or OCA modules perhaps?

**Comment by pedrobaeza** [comment]
It seems that they have set a default value in developer mode. This is not a real bug.

**Comment by gustavovalverde** [comment]
I'm plenty sure I tested this on runbot before opening the issue. Seems like I need some sleep; I'll re-validate to see what happened
