### ISSUE TITLE
[11.0] Product read for Manufacturing Manager

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#22899]
# Impacted versions

11.0. Not tested on others.

# Steps to reproduce

* Create a user in the Manufacturing Manager group only.
* Logged in as this user, create a product
* Save your new product

# Current behavior

I get the following error message:

```
Sorry, you are not allowed to access this document. 
Only users with the following access level are currently allowed to do that: 
- Sales/User: Own Documents Only
- Sales/Manager

(Document model: sale.report)
```

# Expected behavior

The product is saved with no error message.

**Comment by vcloud9ray** [comment]
I was able to replicate this on runbot:

![image](https://user-images.githubusercontent.com/31354495/35955015-cc0d24fc-0c41-11e8-9232-5ec3c10f1950.png)

The model isn't readable unless you are ALSO in one of the Sales groups.

**Comment by Yenthe666** [comment]
@sle-odoo one for you!

**Comment by max3903** [comment]
@vcloud9ray I think group configuration is fine. I am guessing the view is not...
