### ISSUE TITLE
Multi Company Create Invoices Security Restrictions Issue

### ISSUE THREAD

**Issue by GillPotter** [odoo/odoo#22891]
Impacted versions:
11.0

Steps to reproduce:
1. Multi Company with no parent company – Company A set up first and then Company B. They do not share Customers or Products.
2. User 1 and User 2 have both companies. Sales - Manager access and Accounting - Billing access. 
3. In Company A – User 1 creates and validates 2 orders. User 2 creates and validates 2 orders.
4. In Company B – User 1 creates and validates 2 orders. User 2 creates and validates 2 orders.
5. In Company A - User 2 tries to create an invoice from an order created by User 1, and User I tries to create an invoice from an order created by User 2.
6. In Company B - User 2 tries to create an invoice from an order created by User 1, and User I tries to create an invoice from an order created by User 2.

Current behavior:
1. In Company A – User 1 can only create invoices from orders that User 1 created. If he tries to create invoices from orders that User 2 created Odoo Server Error occurs. User 2 can create invoices irrespective of who created the original order.
2. In Company B - User 2 can only create invoices from orders that User 2 created. If he tries to create invoices from orders that User 1 created an Odoo Server Error occurs. User 1 can create invoices irrespective of who created the original order.

Expected behavior:
Either User should be able to create invoices in either Company, irrespective of who created the original order.

Video/Screenshot link (optional):

[OdooServerError.txt](https://github.com/odoo/odoo/files/1704039/OdooServerError.txt)

**Comment by ThijsvOers** [comment]
Hi GillPotter,

I have  similar restriction errors in our multi company environment [11.0 CE], but on other areas. To give you one example: 

I have access to 2 companies(A/B). I am project leader in company A, and sometimes the tasks of projects which I am the project leader cannot be edited by other team members. I have found the reason: this only happens when I am logged in (or was last logged in) in company B. If I log in in company A, then 'my' projects are released and related tasks can be edited by everyone without problems.

I think that the problem is that the 'logged in user' instead of the employer/user rights are used. I am not sure how and if this can be fixed in general, but because we switch  a lot between companies, these errors occur quit often.

I hope this comment helps you finding the cause of your bug.

**Comment by GillPotter** [comment]
Hi ThijsvOers 

Thank you for your comment, it has helped me understand when the error occurs.

When User 1 creates the Sale Order in Company A, User 2 can only create an invoice for that order if User 1 is (or was when last logged in) in Company A. And the same for Company B etc.

This is a big issue for us as User 1 and User 2 work part time and are not always in the office at the same time. I would suggest that this is definitely a bug in the way Odoo Multi Company works. We could both do with a solution, or work around if anyone knows of one?

**Comment by ThijsvOers** [comment]
Hi Gill,

The workaround would be that you create users AND employers per company, so if an employer works in 2 companies, he would have 2 user_id's and 2 employer id's. I have tested the combination 2 employers/ 1 user but that doesn't work. 
I know this is not the best of solutions, but for the moment I cannot think of a better one.

**Comment by GillPotter** [comment]
Hi Thijsv

I’ve found a work around which doesn’t involve users having to have a different sign in for each of the companies.

When the Sale Order is created if the automatically filled Salesperson field is cleared and left blank then invoices can be created by the second user no matter what company the first user was last using.

I had hoped to use Set Defaults for the Salesperson field to always be blank, but unfortunately Set Defaults only offers fields which are filled in as possibilities.

I have added the following to my custom module :-

```from odoo import models, fields, api

class SaleOrder(models.Model):
    _inherit = 'sale.order'
 
    @api.multi
    def _prepare_invoice(self):
        self.ensure_one()
        invoice_vals = super(SaleOrder, self)._prepare_invoice()
        invoice_vals.update({
                'user_id': False,
                })
        return invoice_vals
```

It seems to have solved my problem.

**Comment by astirpe** [comment]
Are there news about this issue?

**Comment by pedrobaeza** [comment]
As no answer, closing this.
