### ISSUE TITLE
Field Invoicing Policy in Product Variants is not saved correctly

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#22893]
Impacted versions:
11.0

Steps to reproduce:
Create a new register of Product Variant and select in field ```Invoicing Policy``` -> ```Delivered quantities```

Current behavior:
The Product Variant created is stored with ```Invoicing Policy``` -> ```Ordered quantities```

Expected behavior:
The Product Variant created must be stored with ```Invoicing Policy``` -> ```Delivered quantities```

Video/Screenshot link (optional):
The behavior described is shown in the following video https://youtu.be/J5rrZgwd9ts

**Comment by Yenthe666** [comment]
Hi @ysantiago,

Thanks a lot for the bug report.
I made a new (template) product with the setting to delivered quantities:
![image](https://user-images.githubusercontent.com/6352350/35959509-31eb24e0-0ca6-11e8-8f80-6c2d68b25a0b.png)

Then I made two variants (for the colors black and red):
![image](https://user-images.githubusercontent.com/6352350/35959545-593c9d44-0ca6-11e8-84a9-48600de84dab.png)


It seems to work fine at my end. Can you reproduce this on the latest Odoo test database (at runbot.odoo.com)? Is your Odoo instance up to date?

Regards,
Yenthe

**Comment by ysantiago** [comment]
Hi @Yenthe666,

The problem is present when is created a Product Variant without having first created the Product (template), as shown in the [video](https://www.youtube.com/watch?v=J5rrZgwd9ts&feature=youtu.be). 

Regards

**Comment by sswapnesh** [comment]
I agree with this behavior but not sure If Invoicing Policy should be used on Product Variants or not. (We should make it invisible if It is not allowed on Variants)

Create New Products from Variants menu

Default `Ordered quantities` is there already

![](https://image.prntscr.com/image/lFHSIRoyQfKRI1EXIETbHg.png)

Change it to `Delivered quantities` and Save it.
It will be changed to `Ordered quantities` again.

![](https://image.prntscr.com/image/gvhVCmtbRFaSLVQhtDnSsg.png)

Maybe functional Review from @nim-odoo ?

**Comment by sle-odoo** [comment]
fixed by https://github.com/odoo/odoo/commit/5c1f025a424b95395d2de087520ce211534e7edc

thank you
