### ISSUE TITLE
[11.0] analytic default using partner_id not work from Purchase Order

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#22896]
**Impacted versions:**
V11 tested on runbot
**Steps to reproduce:**
This issue is related to #21401
1.- Create a default analytic for Vendor ASUSTeK:
![image](https://user-images.githubusercontent.com/7775116/35939902-81b64256-0c1b-11e8-9836-b5a36dba7d51.png)
2.- Create a Purchase Order for this Vendor and receive products
![image](https://user-images.githubusercontent.com/7775116/35939963-b1ce84ee-0c1b-11e8-8529-39f39a99a130.png)
3.- Create Invoice for PO(directly from PO, or go to Menu Invoicing/Purchases/Documents/Vendor Bills)
a) Create invoice from PO(analityc Account is nothing)
![image](https://user-images.githubusercontent.com/7775116/35940191-5b8d00dc-0c1c-11e8-826f-0c03a078aeff.png)
b) Create invoice from Menu Invoicing/Purchases/Documents/Vendor Bills and select PO, invoice lines are create, but analityc Account is nothing
![image](https://user-images.githubusercontent.com/7775116/35940369-d67524d2-0c1c-11e8-9a09-a2935ba82dfa.png)

![image](https://user-images.githubusercontent.com/7775116/35940397-f45f71e6-0c1c-11e8-8d91-c048e34dfca6.png)

**Current behavior:**
Analytic Account is nothing, because is obtained from [_set_additional_fields function](https://github.com/odoo/odoo/blob/11.0/addons/account_analytic_default/models/account_analytic_default.py#L69) and self.invoice_id.partner_id.id is nothing.
On [this function](https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/account_invoice.py#L85) first create invoice lines, after invoice lines are assigned  to new invoice(before, at call function _set_additional_fields invoice_id is nothing)

**Expected behavior:**
When add lines manually, work fine because Analytic Account is get [from onchange](https://github.com/odoo/odoo/blob/11.0/addons/account_analytic_default/models/account_analytic_default.py#L62) and _**self.invoice_id.partner_id**_ is set
![image](https://user-images.githubusercontent.com/7775116/35940457-318fbf3a-0c1d-11e8-962f-3be1f1920aef.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo this is one for you. Could you check?

**Comment by lap-odoo** [comment]
@celm1990 Thanks for the feedback. The module has not been built to work with purchase orders. However, I agree it would be interesting to have this feature. I've created a task in our backlog (60417) to improve this for future versions. Thanks
