### ISSUE TITLE
i can't add any fields to odoo

### ISSUE THREAD

**Issue by Aksth93** [odoo/odoo#22907]
Impacted versions:
V9
Steps to reproduce:

**# 1. at .py:**
# -*- coding: utf-8 -*-
import logging
from openerp import api, fields, models, _
from openerp.exceptions import UserError

_logger = logging.getLogger(__name__)

class Relative(models.Model):
    _name = 'hr.employee'
    _description = 'Relatives'
    _inherit = 'hr.employee'

    relative_ids = fields.One2many('hr.relative.line', 'employee_id', string="Relatives")
    relative_ids = fields.Many2many('hr.relative.line', 'employee_id', string="Relatives")

class Relative(models.Model):
    _name = 'hr.relative.line'
    _description = 'Relatives'

    employee_id = fields.Many2one('hr.employee','Employee Name')
    name= fields.Char('Name')
    dob = fields.Date('Date of Birth')
    id_number = fields.Char('ID number')

# **2. __init__.py**
# -*- coding: utf-8 -*-
import relatives

# **3. at .xml**
<?xml version="1.0" encoding="UTF-8"?>
<openerp>
    <data>
        <report id="action_employee_relatives_report_template"
                string="Employee Identification"
                model="hr.employee"
                name="test.employee_relatives_report_template"
                file="test.employee_relatives_report_template"
                report_type="qweb-pdf"

        />

        

    </data>
</openerp>

Current behavior:
can't install the packages : from openerp import api, fields, models, _
it's installed successfully for a moment then the red lines appears again.
when I restart the server and upgrade my module
" error Context - field does not exist "
Expected behavior:
the module should correctly uploaded.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Aksth93,

The Github tracker is only used for bugs in the official code and shouldn't be used for questions about custom development.
Please do ask this on the official help forum at help.odoo.com.
I believe that the official documentation that learns you how to create a module would be good for you to look at too. You can find it at https://www.odoo.com/documentation/9.0/howtos/backend.html

Regards,
Yenthe
