### ISSUE TITLE
Traceback: While click on print button

### ISSUE THREAD

**Issue by a-gandhi** [odoo/odoo#22915]
Impacted versions:

> OdooV11 Enterprise

Steps to reproduce:
> Go to Settings > Technical > Actions > Reports > Select any report(Quotation / Order)
> Change report from PDF to HTML
> Now go to print that report screen and refresh that page
> Try to print that report

Current behavior:
> Report not print

Expected behavior:
> Report should be print

Video/Screenshot link (optional):
>  Screen shot:
https://www.awesomescreenshot.com/image/3159664/9993de08ca4d7a5f9f62d83eed0a670e

**Comment by Yenthe666** [comment]
Hi @Ankit-Gandhi,

Same response as the other ticket, this seems to work too.
Can you reproduce it on the latest runbot? Have you updated your Odoo to the latest code?

Regards,
Yenthe

**Comment by Ankit-Gandhi** [comment]
Hello @Yenthe666,

I have checked in runbot, still facing same issue.

Kindly refresh report page and try to print report.

Best Thanks,
Ankit H Gandhi.

**Comment by Yenthe666** [comment]
Hi @Ankit-Gandhi,

Indeed:
![image](https://user-images.githubusercontent.com/6352350/35972483-4f2a4834-0cd2-11e8-81c9-99ddf4f8ecdd.png)

But this is also directly coming from https://github.com/odoo/odoo/issues/22913
If that one is fixed these will be too.

Regards,
Yenthe
