### ISSUE TITLE
Calculating delivery costs in SO: "warning: no delivery carrier fits" / "Kein Frachtführer passt"

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#22918]
Impacted versions: 10 Community

Steps to reproduce: 
Delivery Method depending on weight + fixed value (5+0,1*weight) for Zip 70000 to 79999

Current behavior:
Works fine in eCommerce-Webshop, but manual Salesorders it works only the first 5-10 SOs,
after that, the warning comes up every time you click the "calculate delivery costs" button in SO.
There is no chance to create a delivery carrier for every shipping method in community i've found.

Expected behavior:
Calculate correctly

Video/Screenshot link (optional):
![bildschirmfoto_2018-02-08_11-51-29](https://user-images.githubusercontent.com/840301/35969293-ae608b9e-0cc6-11e8-9dda-d328466d27a2.png)

the error occuring:
![bildschirmfoto_2018-02-08_11-54-04](https://user-images.githubusercontent.com/840301/35969339-d3e45ea4-0cc6-11e8-9129-aa1af4f4574f.png)

**Comment by Yenthe666** [comment]
Hi @explanar,

Thanks a lot for the report.
Just a quick question: can you also reproduce this when the user language is in English? Is your Odoo on the latest source code too?

**Comment by sswapnesh** [comment]
Hello @explanar 
This is the Desired behavior I believe as You are applying some rule for zip 70000 to 79999, Based on that there might be some Delivery location which doesn't fit in your Rules for any of the Delivery Carrier.


![](https://image.prntscr.com/image/agtA6sv5QTCIvZdHz2r3EA.png)

Cc: @Yenthe666

**Comment by explanar** [comment]
Hello sswapnesh,

yes, that's the warning in english - you've been faster than me. Thank you.
In between i know the behaviour a bit more detailed:
The warning mostly occurs when an SO gets duplicated and after that a new Shipping and its zip is not similar to the one of the original SO's delivery adress is adviced to be calculated.

When calculating a new SO's delivery costs i didn't se the warning until now.

Best regards and thank you for your help!

Benjamin

**Comment by sswapnesh** [comment]
Glad that Issue is Solved.

**Comment by sswapnesh** [comment]
@sle-odoo Could you please check #22947?

**Comment by Yenthe666** [comment]
@sswapnesh please don't ping people on other issues with a link to another issue. This creates noise on irrelevant issues and becomes confusing.

**Comment by sswapnesh** [comment]
It is not Issue. It is PR related to this Issue.

**Comment by Yenthe666** [comment]
Just ping on the PR and not on the closed issue, that is what I mean. That way it is cleaner and better.

**Comment by sswapnesh** [comment]
Sure, Thanks.
