### ISSUE TITLE
Default sales team on invoice gives access error on customer invoices

### ISSUE THREAD

**Issue by levkar** [odoo/odoo#22923]
Impacted versions: V9+, tested on V11

Steps to reproduce:
1) Select a company on the sales team created by default. (company is empty by default)
2) Switch to other company
3) Go to account -> sales ->  invoices -> customer invoices
4) Click on Create button

Current behavior:
Internal server error

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document Type: crm.team Operation: read)

This is due to the _get_default_team_id method on invoice. This sets sales_team.team_sales_department without controlling company id.

Expected behavior:

Do not use sales_team.team_sales_department on other companies if company is different and create invoice without any error. Using xml_id for finding a default team is a very bad idea....

Video/Screenshot link (optional):

**Comment by ThijsvOers** [comment]
Hello Levkar,

I can confirm that if I have the same error on our 11 C multi company environment, latest base Odoo updates are installed.

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/commit/262be78957dc8f7d9db87e49ee36fe9b5e735fbd (Along with https://github.com/odoo/odoo/issues/22360 and https://github.com/odoo/odoo/issues/23169)
