### ISSUE TITLE
[11.0] Odoo Studio breaks framework when creating fields with track_visibility

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#22922]
Impacted versions: 11.0 Enterprise atleast (V9 & 10 too probably)

Steps to reproduce:
1. Create a new database
2. Install the `purchase` module
3. Install the `odoo_studio` module
4. Activate developer mode
5. Go to purchases > purchase orders and create a draft purchase order. Then open up the studio and create a new monetary field. The new field should have the following settings:
- readonly
- required
- widget = monetary
![image](https://user-images.githubusercontent.com/6352350/35973264-0f372f46-0cd5-11e8-8b79-1516c2fa4fef.png)
6. Click on the "More" button and activate tracking for this field too:
![image](https://user-images.githubusercontent.com/6352350/35973298-308bfb18-0cd5-11e8-9475-cafeb447579b.png)
7. Save all these changes and go back to the apps list. Now try to install another app, for example `project`. You'll now get a traceback:
![image](https://user-images.githubusercontent.com/6352350/35973342-52005578-0cd5-11e8-90a5-695706dcf4c9.png)

Current behavior: You cannot install new modules or update existing modules anymore. The `track_visibility` breaks the framework.

Expected behavior: You can install new apps and update existing apps without any issues.

**Comment by Yenthe666** [comment]
OPW 815185

**Comment by Yenthe666** [comment]
@ged-odoo @aab-odoo and @mge-odoo this is relevant for you guys. This was quite a challenge to figure out.

**Comment by lukebranch** [comment]
Bumped into this issue a few times as well. I think some sort of ‘locking’ feature per field, action, etc. Could be quite useful to make Studio feel a little less fragile for partner use.

**Comment by Yenthe666** [comment]
Fragile? I'm not even touching that thing on any production environment. It is a pesky module for technical people (sorry, no offense guys, I know it was hard work).

**Comment by mge-odoo** [comment]
Hi @Yenthe666 

The feature your mention (set `track_visibility` on custom fields) has been pushed in 11.0 (see odoo/odoo@1119fdd) so it's probably not reproducible in 10.0 or in 9.0.

I don't understand neither why you blame Studio. This code is in `mail` and you could do the exact same think without Studio ; it's just a shortcut.

@lukebranch you are right. We do our best to make as less fragile as possible ; reporting the issues you encounter would probably be helpful for us to improve its stability.

This being said, @rco-odoo would probably be the most inclined to fix this issue.

Regards,

Martin

**Comment by Yenthe666** [comment]
@mge-odoo okay maybe I was a bit strict. I was able to reproduce it _with_ studio. My last comment about the fragile/pesky part is more out of previous experience with Odoo studio where non-technical people begin to play with Studio and break views etc. This is annoying for a developer to find/fix. 😉 
Anyways it would be great if @rco-odoo could have a look and thanks for the quick feedback.

**Comment by mge-odoo** [comment]
I understand your point as I already had to find/fix break views in production databases on our SaaS platform. Nevertheless, trying to debug the same break views done without Studio (views being directly edited without using inherited views for example, like Studio does) was, in my opinion, even more difficult.

**Comment by Yenthe666** [comment]
@mge-odoo but that is because all the Studio views have `studio` in it, so they're easier to filter out, no? 😆
