### ISSUE TITLE
Unable to change quotes / sales orders order line description

### ISSUE THREAD

**Issue by simosuu** [odoo/odoo#22927]
Impacted versions: Odoo 11 (25.1.2018)

Steps to reproduce:

Create quote / sales order and add products to it. Save and tryto modify order lines descriptions. 

Current behavior:

Usually wont save. Revert to old value.

Expected behavior:

Change always.

Video/Screenshot link (optional):
Try to add "111"

![image](https://user-images.githubusercontent.com/23297584/35977417-c8568fe2-0ceb-11e8-83ad-3bca40e40f90.png)

But always revert back to "[EXP] Kulut"

![image](https://user-images.githubusercontent.com/23297584/35977498-ecbcfae2-0ceb-11e8-8c02-32a9245e2432.png)

**Comment by sswapnesh** [comment]
Hello @simosuu 
Could you please update your source code and try again?
Related to #22797

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this issue as it should have been solved in the meanwhile and as we recieved no feedback.
Please update your local instance and try again. Don't hesitate to respond back if you can still reproduce it on the latest 11.0

Regards,
Yenthe
