### ISSUE TITLE
Quality alerts are only visible on the work order form view, not in the specialized view

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#22925]
### Impacted versions:
11.0 at least, possibly 10.0. Tested on demo.odoo.com

### Steps to reproduce:
- Install Quality Control and MRP. Go into settings and check that you want to manage work orders
- Create a quality alert for some product and workstation. Also create a workstation message
- Create a manufacturing order for said product with a route that uses the workstation in question
- Progress the manufacture until you have an active workorder on that workstation
- Open the form view of the workorder by pressing on the workstation's "In Progress"-link
- Note that on the form, the warning set on the quality alert is visible in a warning box
- Go back to the workcenter dashboard and open the customized view by pressing the "Work Orders"-button

### Current behavior:
- No trace of the alert is visible in the specialized view 

### Expected behavior:
- The alert should be visible in the specialized view: if there is no space for a text box, at least add a pulsing exclamation mark that opens a pop-up with the warning when clicked.

### Screenshot link (optional):

From the dashboard card you can go to two places:
![image](https://user-images.githubusercontent.com/2587901/35975584-e5ca4d76-0ce5-11e8-8e45-983751bcc9cb.png)

The form (where the warning is visible):
![image](https://user-images.githubusercontent.com/2587901/35975608-f2ef45ba-0ce5-11e8-8e14-83a05783340b.png)

Or the specialized processing view, where it is not:
![image](https://user-images.githubusercontent.com/2587901/35975633-0a9f8616-0ce6-11e8-98c6-c5e81a5d4750.png)

**Comment by sle-odoo** [comment]
Hi,
Isn't it just an issue of demo data? Are you able to reproduce it with a new routing and quality control point?

Regards

**Comment by amoyaux** [comment]
Hi,

It's not integrated with work order step in enterprise. However you can use the dummy quality check that will do the same.
![qcp00021 odoo](https://user-images.githubusercontent.com/5512395/36257859-dece30be-1258-11e8-8317-7c2003267127.png)
![mo 00021 computer sc234 manual assembly odoo](https://user-images.githubusercontent.com/5512395/36257863-e443b406-1258-11e8-8305-8648b25aa444.png)

**Comment by aisopuro** [comment]
So wait. That means that the user has to try to figure out in what places the quality alert should be visible? So they have to hunt down every possible stage that uses the product in question? Is there a way for them to do that?

I don't understand your question @sle-odoo . What does demo data have to do with this? It seems to me that Odoo is able to run some form of logic to determine what workorders should display an alert (because it is visible on the form). The user, I am sure, expects this to be visible to the person who starts processing the workorder. However, it seems that in enterprise, there is a new view, whose purpose is to be the primary way of processing work orders. But it becomes very much less useful if it does not show the alert that is expected to be displayed.

As it is, the user cannot be certain that the enterprise view will show them all the data they need to see, which makes it much less useful.
