### ISSUE TITLE
[10.0c]Can not validate inventory adjustment in multi-company mode

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#22930]
Impacted versions: 10 CE

Steps to reproduce:
New Database Install, activate Dev Mode, Install sales, purchase, inventory, accounting
Activate multi Company, Create Company,
Setting COA for each company
Create admin user for company with access right Sales Manager, Purchase Manager, Adviser, and HR and Employee, and Setting,    allow to the company,  also allow super admin for the company

Create new virtual location view and set a company for it
Create virtual loaction type inventory loss,  set parent to the above created new virtual location view
Set company to the company
set account for incoming and out going to account belong to the company
login as admin user for the company
import inventory adjustment csv file  (success)
validate the inventory adjustment
Access error warning

Logout
login as super admin and activate dev mode
select the company
validate the inventory adjustment
warning  "can not create move for different companies"

Current behavior:
Can not validate inventory adjustment for both super admin or company admin with inventory manager access right
Expected behavior:
Should be able to validate inventory adjustment
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7310629/35979535-2bf03056-0d1b-11e8-8e30-cccd251d19d0.png)

**Comment by jco-odoo** [comment]
Virtual ocations like inventory, supplier, production, even customer should not have a company_id.  We will also use it later as the owner of the location (and what is in it, except when owner_id is set) and you don't own something in inventory, supplier,...
