### ISSUE TITLE
[7.0] account_asset: - Negative Next Period Depreciation when currency not equal to company currency

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#2294]
Hi Team,

Asset is computing wrong depreciation line when asset currency is not equal to company currency.

[steps to reproduce bug]
* Create a new asset
* Change company currency different to base company currency
* Fill in the following values in asset 
 * Gross Value - 4,004.85
 * Salvage Value - 0.00
 * Computation Method - Linear
 * Time Method - Number of Depreciations Change Duration
 * Pro rata Temporis - True
 * Number of Depreciations - 12
 * Number of Months in a Period - 1
* Compute depreciation line (Press compute button in second tab)

**Comment by dmo-odoo** [comment]
The following commits have fixed this issue (as well as another) in mainline 7.0 (despite GitHub only showing the 8.0 tag):
https://github.com/odoo/odoo/commit/2606e37b18c92f02331c05620f5c0edc7b9f14ad
https://github.com/odoo/odoo/commit/e2ccc5709b1b4909eb857d77ebb2e21c9a5c7fb9

Best regards,
David
