### ISSUE TITLE
[11.0] Permission error when creating initiative / opportunity.

### ISSUE THREAD

**Issue by egrivero** [odoo/odoo#22945]
Impacted versions: Odoo Enterprise 11.0

Steps to reproduce: 
 - Install CRM
 - Login with the demo user.
 - Try to create an initiative / opportunity.

Current behavior:
 - Odoo generates the following error when trying to create the initiative / opportunity.
![screenshot from 2018-02-07 20 38 30](https://user-images.githubusercontent.com/7115776/35989483-dcbe8d74-0cc6-11e8-9e00-11fd3af11f80.png)

Expected behavior:
 - The initiative / opportunity must be created

Video/Screenshot link (optional):
Reviewing it was found that deactivating this rule allows me to create initiatives without problems. And when checking a little data it was obtained that the user_id of the mail.activity has assigned the user admin.
![screenshot from 2018-02-07 20 39 45](https://user-images.githubusercontent.com/7115776/35989569-1b082d92-0cc7-11e8-86fe-7ca977a0e97c.png)

Permissions of the demo user
![screenshot from 2018-02-07 20 38 55](https://user-images.githubusercontent.com/7115776/35989614-3a0c2572-0cc7-11e8-955f-ed0c40af680c.png)

**Comment by Yenthe666** [comment]
@egrivero,

Thanks for the report. 
@mart-e if I'm not mistaking there was recently another bug report about this.
If I'm not mistaking @mart-e was saying this is intended behaviour and that it depends on if the user is attached to sales teams or not. Can you give feedback Martin?

Regards,
Yenthe

**Comment by egrivero** [comment]
Hello, @Yenthe666 and @mart-e 
Do you have any information regarding this issue?

Greetings.

**Comment by Yenthe666** [comment]
@egrivero at the moment he is out of the country so probably next week.

**Comment by egrivero** [comment]
@Yenthe666 Thanks for the info.

**Comment by mart-e** [comment]
Fixed at 4e061d8c51f92fd8dde626bb8ddbdd867db84046
