### ISSUE TITLE
Odoo 10 Community - Delete PO with Movement

### ISSUE THREAD

**Issue by valvalvalvalval** [odoo/odoo#22951]
Impacted versions: Odoo 10 Community

Hi, 
I created a PO, validate, received goods until create BILL. But I found out that I inputted wrong partner so I refund the BILL, return the goods and want to delete the PO.
However I can't delete the PO and below is the warning from Odoo:

**Odoo Warning - Warning
Unable to cancel purchase order PO00001 as some receptions have already been done.**

Can anyone help with this issue? or is that we really can't delete the PO?

Thank you in advance.

**Comment by sle-odoo** [comment]
It seems logical you cannot just unlink this PO, there are a few other documents and potential accounting entries depending on it. If you don't want to see it, add a filter or disable this record.

Regard
