### ISSUE TITLE
[HR] (Design Flaw) BrowsableObject does not aggregate

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#22969]
Observed on v10, suggestively all versions
**Replication (roughly):**
1. Having contrued a Browsable object in your favorit manner, for example by adding Work Days or Input Items in a salary slip, (say line `WORK100`)
2. Adding a second item with a duplicate `code` field (say `WORK100`) with different values
3 will override former items with the same code, when accessing it through the browseable object

**Causality (precise):**
This is because two factors:
1. The dict passed to the constructor is just a dict which uses `code` as key (and consequently just overrides in it's generation order).
2. The browseable object has no abstraction for dealing with `{}dict` or `[]list{}dict` types interchangeably, and thus is not providing the expected standard behaviour aggregation (`sum`) out of the box.

EDIT: `sum` out of the box will not be possible as we deal with standard RecordSet at that level but at least a `sum(worked_days.WORK100.mapped('number_of_days'))` will be easily possible... Ok this causes other trouble, I'll report back.
EDIT2: Error out ASAP with a meaningful message to the user ("You share the same code across items, but your python code in rule XYS is accessing attribute YZY of code CODE with a singleton in mind.")

**Expectancy:**
It would be expected that browseable objects handle multiple codes transparently and apply `sum` aggregation on all `int` or `float` fields and `join` operations on strings.

**Rationale:**
**_Disclaimer:_** This uses an abstract example to make the point. Please ask for a concrete one, which is certainly less condensed and more noisy and complicated to grasp.

`code` can be interpreted as a way of grouping, in which `code` represents a calculation semantic, while `name` represents a human consumable detail. Example:
- Norms says: Family days off: 10
- Your company says: 5 for friends / 5 for family
So different `name`s (Family and Friends) would be subsumed under the same `code` (eg. "FF") and should be treated as such in the calculus. 

-------------
Dear reader, if you find a contradicting rationale you can expose to me, I would be very grateful to enable me to correct my reasoning and opt for a different solution to the problem.

**Comment by blaggacao** [comment]
Uses cases where `code` implements alternatively and more manageable so than external ids a legal grouping throughout the holiday application (which is rather common worldwide): "Ester holidays are different from holidays originating from overtime."

**Comment by Yenthe666** [comment]
Hmm I was not sure about this one. As it is quite low level and technical I went for framework :D
