### ISSUE TITLE
FR: [12.0/Master] Hot Reloading During Dev (eg. Report Dev)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#22966]
Impacted versions:
All
Steps to reproduce:
N/A
Current behavior:
Upgrade and refresh every time a change is made. 

Expected behaviour:
Hot reload/refresh.

Video/Screenshot link (optional):
https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html

Explanation:
It would be incredibly useful to have this kind of functionality in Odoo.
This is how many devs work, and it would be great to have this option in the development phase.

**Comment by Yenthe666** [comment]
Hey @lukebranch,

Thanks for the suggestion!
I think this is of interest for @ged-odoo, @xmo-odoo and @odony and I also believe something along these lines was once mentioned as 'would like to have'?

Regards,
Yenthe

**Comment by JKE-be** [comment]
@lukebranch 

Have you already try the --dev xml,reload mode when you start your server? 

That will reload automatically the server when you update one python file.
And read XML from the xml file instead of db.

**Comment by blaggacao** [comment]
@lukebranch 
Note: What @JKE-be  doesn't work when you have a docker based development workflow on windows, as Windows for Docker does not implement the inotify api. 
Not sure how advanced is native pynotify on Windows and if it handels the use case without docker..
That would be in any case unrelated to Odoo, however...

**Comment by lukebranch** [comment]
@JKE-be ,

I wasn't aware of this feature, i'll definitely give this a go and report back, thanks!

@blaggacao ,

Thanks for the advice. I've only used Docker in Ubuntu for dev/staging, so I haven't run into this issue yet, i'll make a note of it for our internal docs though, thanks.
