### ISSUE TITLE
Timesheets-tab should be hidden if "Allow Timesheets" is disabled on project

### ISSUE THREAD

**Issue by simosuu** [odoo/odoo#22963]
Impacted versions: 11.00 CE (9.2.2018)

Steps to reproduce:

Create project with "Allow timesheets" disabled
Create task to project

Current behavior:

Timesheets-tab is shown in projects tasks.

Expected behavior:

Timesheets-tab should be hidden on tasks.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/23297584/36030443-ec83e170-0daf-11e8-9486-acc829fd512b.png)

![image](https://user-images.githubusercontent.com/23297584/36030610-9203fa2c-0db0-11e8-963d-efffdec61e96.png)

**Comment by jem-odoo** [comment]
Hello,
as explain on the proposed PR, we can not add new field (even related) in a stable version. So, we can do nothing for 11.0.
However this feedback was taking into account, and we even go further by checking that the analytic account is active. See https://github.com/odoo/odoo/blob/master/addons/hr_timesheet/models/project.py#L109 for more details. This fix is done in master and will be available for next stable version.
Thanks for contributing. Regards.
