### ISSUE TITLE
res.partner.bank do not register currency and company change in connected account.journal

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#22980]
**Impacted versions:**

11.0

**Steps to reproduce:**

Install sale module
Set multi-currency and multi-company
Create other company and set accounting in settings.
Go to Invoicing -> Configuration -> Accounting -> Bank Accounts
Set bank name, bank account number, currency
Add "bank_account_id" field to the form view
Edit currency and company

**Current behavior:**

Bank name and account number update in connected res.partner.bank
currency and company **do not** update in connected res.partner.bank

**Expected behavior:**

All data updated in res.partner.bank record

**Video/Screenshot link (optional):**

https://youtu.be/pwt3vFSAmwE

**Comment by oco-odoo** [comment]
@grzekru Thank you for reporting the issue. This bug did not originate from 11.0, but 9.0, so I did not merge your PR. It has been fixed with this commit : https://github.com/odoo/odoo/commit/239f4fec29c0b856c14b02e318c615c41bab5868
