### ISSUE TITLE
[11.0] When creating a File field with Odoo Studio the file gets the extension removed

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#22986]
Impacted versions: 11.0 EE

Steps to reproduce:
1. Create a File field using Odoo Studio in any form.
2. Attach a document.
3. Export the document.
4. Try to open it.

Current behavior:
The file extension is getting removed, for example a picture with a JPG format when uploaded and downloaded back from the field it will download with another name generated by Odoo and with no extension.

In order to open the file you must know the extension, change the name to set the extension and then open it.

Expected behavior:
Keep the file name and extension.

**Comment by Yenthe666** [comment]
@ged-odoo for you guys 😉

**Comment by mge-odoo** [comment]
Hi @edsersolis 

This has been improved in the next version (from saas-11.1) in the following rev. odoo/enterprise@fd4eeb3.

This was not a blocking issue as you could still open the file so we didn't consider it as a bug and put it as improvement, which is normally done in master (not a stable version).

If you really need it in 11.0, I would advise you to cherry-pick the following rev. odoo/enterprise@fd4eeb3 and odoo/enterprise/a4c3e5b (a related bug-fix).

Martin
