### ISSUE TITLE
[9.0] Invalid field (name) is used in copy_data method of mrp.bom

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#22992]
Impacted versions: 9.0
(Not an Issue but Code cleanup)

Steps to reproduce: Copy Bom

Current behavior: Warning in log
`WARNING mrp_v9 openerp.models: mrp.bom.create() includes unknown fields: name`

Expected behavior: No Warning in log

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hey @sswapnesh,

Thanks for the bug report.
As you've made a PR to fix it an issue is not really needed (as it only fills up the queue of issues).
I'm closing this bug report as somebody will give the appropriate feedback on the PR soon enough.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Agree with that but my personal experience says Issues are resolved faster
that PRs. (you can have a look)

**Comment by Yenthe666** [comment]
@sswapnesh at the moment yes, but that really shouldn't be the case. PR's should always get priority over issues and usually this is the case.

**Comment by sswapnesh** [comment]
Sure, Will keep in mind for next time.(It has been also mentioned in PR Guidelines😉)

**Comment by Yenthe666** [comment]
Thanks! 😉
