### ISSUE TITLE
[10] import refund

### ISSUE THREAD

**Issue by Vartkat** [odoo/odoo#22995]
Impacted versions:
10.0ce

Steps to reproduce:
Go to accounting-->supplier invoice--> Import button

Current behavior:
Even if I provide a csv file with a 'type' column I can't specify that the imported document is a refund and not and invoice.
Whenever I import a refund, Odoo sees it as an invoice and not a refund

Expected behavior:
I excepted to have 'type' in the local menus up the data columns.

<img width="272" alt="screenshot" src="https://user-images.githubusercontent.com/1696899/36075493-14f63e4a-0f50-11e8-9d5d-82f78e52a1c5.png">

**Comment by qdp-odoo** [comment]
That's more a missing feature than a bug, since you can import refunds by going in the dedicated menuitem...

It will be fixed in a near future, in a next version, though.

So I'm closing this issue for the sake of Clarity.

thanks
