### ISSUE TITLE
fleet module usability for provider field

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23000]
This module don't have a way to set the product purchased, for example diesel, and on the provider drop down it should show only the providers that sell diesel not every other provider on alphabetic order 

also, introducing the invoice number is not in any way connected to the invoice module, if the invoice is introduced in the provider invoices the provider field should auto complete

**Comment by tivisse** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by icf20** [comment]
@tivisse FYI the mailing list and forums dont support international domain names see https://github.com/odoo/odoo/issues/23527
