### ISSUE TITLE
[11.0] Horizontal scroll bar only visible if you scroll down to the end in Listview when using small screen resolutions.

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#23007]
_Impacted versions:_
V11 - Enterprise and Community
Previous versions also

_Steps to reproduce:_
1.Go to any listview with a lot of columns or add some columns using the Studio or Debug mode. For example let have a look at the Products listview. Make sure there are more than 80 products, so you can scroll down.
2. When the screen is wide enough, Odoo will show you all the columns. But if you make your screen smaller, at some point not all the columns are shown.
3. At that moment you have to scroll all the way down to be able to use the horizontal scroll bar.

I have tested this with the latest version of Firefox and Chrome. Both have the same problem.

This problem doesn't occur when you try the kanban view, like the one of the project tasks. The horizontal scroll is always there.

_Current behavior:_
Horizontal scroll bar only visible when you scroll down.

_Expected behavior:_
Would be nice if the scroll bar is there, when there isn't enough space for all the columns.

_Video/Screenshot link (optional):_
Screen is wide enough. OK
![selection_018](https://user-images.githubusercontent.com/30628967/36092696-9103fe58-0fe8-11e8-9e64-36a797eb7557.png)

Screen is smaller. Horizontal scroll bar only visible when you scroll all the way down. NOT OK
![selection_019](https://user-images.githubusercontent.com/30628967/36092749-b2c5c5e4-0fe8-11e8-8471-a850e47c107b.png)

For example how the kanban view works. This is what I would expect.
![selection_017](https://user-images.githubusercontent.com/30628967/36092766-c324c9a8-0fe8-11e8-814d-13e13afeb4f4.png)

**Comment by Elkasitu** [comment]
@ged-odoo Perhaps something for your team to look at

**Comment by omar7r** [comment]
any solution?

**Comment by omar7r** [comment]
I found a temporary solution deleting two css lines, I paste the diff for 10.0 version

diff --git a/addons/web/static/lib/bootstrap/css/bootstrap.css b/addons/web/static/lib/bootstrap/css/bootstrap.css
index 680e768..2107a71 100644
--- a/addons/web/static/lib/bootstrap/css/bootstrap.css
+++ b/addons/web/static/lib/bootstrap/css/bootstrap.css
@@ -2442,7 +2442,6 @@ table th[class*="col-"] {
 }
 .table-responsive {
   min-height: .01%;
-  overflow-x: auto;
 }
 @media screen and (max-width: 767px) {
   .table-responsive {
diff --git a/addons/web/static/lib/bootstrap/less/tables.less b/addons/web/static/lib/bootstrap/less/tables.less
index 2242c03..f1b07e0 100644
--- a/addons/web/static/lib/bootstrap/less/tables.less
+++ b/addons/web/static/lib/bootstrap/less/tables.less
@@ -169,7 +169,6 @@ table {
 // will display normally.
 
 .table-responsive {
-  overflow-x: auto;
   min-height: 0.01%; // Workaround for IE9 bug (see https://github.com/twbs/bootstrap/issues/14837)
 
   @media screen and (max-width: @screen-xs-max) {

**Comment by manisharpatil** [comment]
I have same functionality required for odoo10, So what is the changes for odoo10 web? Any help would be appreciated?
