### ISSUE TITLE
Employee Time Sheet Cost on Sales Order Invoice

### ISSUE THREAD

**Issue by inianrck** [odoo/odoo#23012]
Impacted versions: Odoo 11

Steps to reproduce:

Step1 : Add a time sheet cost on Hr Setting for a employee ( eg : inian = $10 per hour)
Step2 :  Create a Product and choose type service.  Under invoicing choose, create task on existing project
Step3 : We don't fill sales cost or product cost as it will be generated from time sheet hours that user punch in.
Step4 : After confirming the order, a task is created under specified project.
Step5: After entering time sheet for the task.
Step6 : Sale order line  Invoice status changes to products waiting to invoice
Step7 : If we invoice it, we expect the time sheet per hour cost to be multiplied with quantity of what user punch in time sheet (based on per user time sheet cost).
**Current behavior:**
It is multiplying product cost specified instead of time sheet cost  from employee's hr setting.
**Expected behavior:**
It is suppose to take time sheet cost per employee($10) and multiply it with quantity of hours he worked and bring it to sale order line and consecutively to invoices.
Video/Screenshot link (optional):

**Comment by ThijsvOers** [comment]
Hi inianrck,

In version 11 (C) the invoicing of timesheetlines works differently than version 8. The invoicing is based on the price added on the sales orderline (and depending on pricelist or extra specific deductions) and s no longer connected with the cost price you see on the employer record. As far as I can see this field is in use for computing margins.

**Comment by inianrck** [comment]
Hi ThijsvOers,
Thanks for your response, Now I Know its not a issue? Can you explain how we can compute margin from it.

**Comment by bst-odoo** [comment]
Hello, 
The timesheet cost is used for the project overview and not for the SO lines. 
Several employees with different timesheet costs can record timesheets on a single task linked to an SO line. That's why we cannot overwrite the product cost.
