### ISSUE TITLE
Odoo 11 Documentation - Building Interface Extensions: is outdated

### ISSUE THREAD

**Issue by Bahaa-Addin** [odoo/odoo#23010]
Impacted versions: 11

Current behavior: Outdated (It's just the same as 10.0)

Expected behavior: Up to date

Link : https://www.odoo.com/documentation/11.0/howtos/web.html#widget-events-and-properties

**Comment by Yenthe666** [comment]
Hi @Bahaa-Addin,

Thanks for the report.
Actually, @ged-odoo and his team are working on the new V11 documentation for JavaScript etc but it hasn't made it to production yet.
@ged-odoo any timeframe?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
The issue raised here is absolutely correct.  The documentation is in a terrible state.  

We are trying to fix it, by basically rewriting the documentation (JS).  Here is a branch, which is just the start. I am afraid that this is not much yet, but I'll keep working on it as much as I can.

Meanwhile, I'll close this issue.

**Comment by Yenthe666** [comment]
@ged-odoo I think you wanted to link a branch but didn't.
And as I said on site at Odoo: you're doing a great job, keep it up!

**Comment by ged-odoo** [comment]
haha, I actually cut the link, but forgot to paste: https://github.com/odoo-dev/odoo/tree/11.0-doc-ged
