### ISSUE TITLE
Can't sign quotations in My Account or Tokenized link sent by email.

### ISSUE THREAD

**Issue by oscarolar** [odoo/odoo#23017]
**What are the steps to reproduce your issue?** 
Here is a video 
https://youtu.be/ye3NWuzFai0 

**What is the current behavior that you observe?** 

After entering a signature on the signature widget, Click on the button to sign the quotation and nothing happens. 

**What would be your expected behavior in this case?** 

Should be able to sign quotations online 

ENT issue:  816127

**Comment by jacobbubu** [comment]
I've got the same issue
