### ISSUE TITLE
[11.0] Analytic tags cannot be added in journal entry

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#23029]
Impacted versions: 10.0 11.0

Steps to reproduce: Create an account journal

Current behavior: You cannot add/remove analytic tags to acccount move lines

Expected behavior: Have the possibility to add/remove analytic tags to the account move line

Video/Screenshot link (optional):

Remarks: It can be solved adding the many2many_tags widget to the field.

**Comment by lap-odoo** [comment]
@jalzaga Hi, thanks for reporting this. It has already been improved in SaaS 11.2. You'll see that from this version many improvements have been done on analytic accounting in general.
