### ISSUE TITLE
HTML Editor cannot paste code into it

### ISSUE THREAD

**Issue by 2SI3NX** [odoo/odoo#23032]
Impacted versions:
Odoo 10
Steps to reproduce:
HTML Editor in Website, copy any code from there and try to paste it back or anywhere in the HTML editor
Current behavior:
It will not paste code
Expected behavior:
It should paste code for ease of use.  It can only copy and cut

**Comment by Yenthe666** [comment]
Hi @2SI3NX,

Thanks a lot for your bug report.
I've just tested this on the latest Odoo 10 and it seems to work fine out of the box. I can both cut and paste the code with my mouse and paste it with `ctrl` + `v`. Can you reproduce it on an official Odoo instance at runbot.odoo.com?
Have you tried updating your Odoo to the latest source code?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on this issue.
