### ISSUE TITLE
[11.0] Internal server error on DB Manager

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#23035]
Impacted versions: 11.0

Steps to reproduce:
1. Open DB Manager
2. Try to duplicate or restore a DB.

Current behavior:
1. If trying to duplicate a DB it gives an internal server error.
2. If trying to restore a DB it gives an internal server error.
3. Even with the internal server error it will do the task.
4. If the Master Password is wrong also gives an internal error.

Expected behavior:
1. Do the task without giving an internal error.
2. Information dialog on what the error was if any.
3. Information dialog on success.

**Comment by edsersolis** [comment]
On runbot it gives the same error, however I was just able to test the one with the wrong master password as I'm not able to know what password is set in that instance.

**Comment by sle-odoo** [comment]
hi,
can you share the error from your logs?

regards

**Comment by sswapnesh** [comment]
Hello @sle-odoo 
I can Reproduce same in Runbot

`http://302403-11-0-ca0875.runbot13.odoo.com/web/database/manager`

![](https://image.prntscr.com/image/P6wU4lznSTCwKIP2DTBtow.png)

Type wrong password


![](https://image.prntscr.com/image/QyxioYmGTC_kh8uy_fS9uA.png)

**Comment by Yenthe666** [comment]
Yeah, absolutely a problem 😄

**Comment by edsersolis** [comment]
No error is shown in the log, and system keeps working. @sle-odoo

**Comment by sswapnesh** [comment]
Maybe this can be helpful 

![](https://image.prntscr.com/image/Bh_9k1TKQ-CHm_TIYJ9zbg.png)

**Comment by Elkasitu** [comment]
Oddly enough, I can reproduce it on the runbot but not locally, but I might have a clue as to what is causing it...

@edsersolis Did this issue happen on the saas or in a local installation? If the latter, can you provide your launch options / configuration?

**Comment by edsersolis** [comment]
```
[options]
addons_path = /odoo/odoo-server/src/enterprise,/odoo/odoo-server/src/odoo/addons, [OTHERS HIDDEN]
admin_passwd = [HIDDEN]
data_dir = /odoo/odoo-server/data
db_host = False
db_maxconn = 64
db_password = False
db_port = False
db_template = template1
db_user = False
dbfilter = ^%d$
list_db = True
import_partial = True
workers = 9
limit_memory_hard = 4294967296
limit_memory_soft = 671088640
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 2
log_handler = :WARNING,werkzeug:CRITICAL,openerp.service.server:INFO
log_level = debug
logfile = /odoo/odoo-server/log/odoo-server.log
logrotate = True
proxy_mode = True
```

**Comment by edsersolis** [comment]
There you go @Elkasitu

**Comment by sswapnesh** [comment]
Could also provide error part of Odoo log?

**Comment by edsersolis** [comment]
No error is shown in the log @sswapnesh

**Comment by sswapnesh** [comment]
Is there something in the console?

**Comment by Yenthe666** [comment]
@edsersolis and @sswapnesh do you still face this issue? I've updated my local Odoo and doesn't seem to happen

**Comment by edsersolis** [comment]
Hey @Yenthe666 it has improved but still there. I've only noticed when dropping a DB now.

Note: we always install the last build on new installations. This statement is based on last installation I've worked with that was about two weeks ago.

**Comment by edsersolis** [comment]
This seems to have been fixed. Closing.
