### ISSUE TITLE
Redundant (Two) Change password and Cacel Button on User formview

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23045]
Impacted versions:
	> V11E
Steps to reproduce:
	> Settings > Users  > Open formview > Click on Action 
	> Click on Change password 
	> Click on new password and then again click anywhere on that popup.
	> So its showing two 'Change Password' and 'Cancel' Button. 
		
Current behavior:
	> Its showing two 'Change Password' and 'Cancel' Button. 
Expected behavior:
	> It should show only single 'Change Password' and 'Cancel' Button. and Should proceed Smoothly.

Video/Screenshot link (optional):

Video > 	https://youtu.be/XgCNxn_A8UA
Screenshot > 	https://www.awesomescreenshot.com/image/3172231/3bad48376eb5e99a0c48a4d4423ee6d1

Thanks,
Dipak

**Comment by Yenthe666** [comment]
@ged-odoo I believe this is view related from the JS side. This is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/36197816-2b0f7850-1175-11e8-8eba-474609b7aaa3.png)

**Comment by sswapnesh** [comment]
This has been fixed in 132137939cc8460868a0e77ff78814a9d95e5a56

**Comment by Yenthe666** [comment]
Indeed. Thanks for keeping track @sswapnesh
