### ISSUE TITLE
odoo.com. Forum. Karma.

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#23047]
Sorry, guys, but i can ask this question only here:

I'd like to ask something on http://odoo.com/forum/

If I click Ask a question:

> 3 karma is required to perform this action. You can earn karma by having your answers upvoted by the community.

If I click "reply" in question:

> 3 karma is required to perform this action. You can earn karma by having your answers upvoted by the community.

If I click "comment" in question:

> 8 karma is required to perform this action. You can earn karma by having your answers upvoted by the community.

So where is that carma? What should I do, if I want community help? Should I go to stackoverflow?

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

You should recieve a verification email on the email you've created your forum user with.
When you verify your account you get some karma which puts you above the 3 karma limit. This was done because of the huge amounts of spam.

Regards,
Yenthe

**Comment by sergeiruzkiicode** [comment]
@Yenthe666 recieved, clicked, verified from the start.

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

And you never got the karma applied ony our account? So you mean you're stuck? (CC @JKE-be)

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!

**Comment by JKE-be** [comment]
Hi @sergeiruzkiicode 

What is the email used into the forum?

**Comment by sergeiruzkiicode** [comment]
@JKE-be sergei.ruzki@icode.by
and one more thing: odoo.com often try to switch my language from english to french. All locales are ru_RU and be_BY.

**Comment by Yenthe666** [comment]
I have that problem quite a lot too, especially with french.
If you open a link from somewhere else that points to the forums and if it contains the lang in the URL Odoo tends to keep track of it and keeps applying that lang.

**Comment by ganesh-trabacus** [comment]
I have changed my email, earlier it was incorrect and how can I send email-verification to my email, as I cleaned my spam emails and can't found account verification link.

**Comment by JKE-be** [comment]
@sergeiruzkiicode  I just re-send you a link if need.
If not just ignore it, and token will expired automatically

**Comment by JKE-be** [comment]
@ganesh-trabacus 

You can just ask a new reset password email via ou login page.
https://www.odoo.com/fr_FR/web/reset_password

**Comment by newtratip** [comment]
I can't post my question on the odoo forum. Show Karma Error **3 karma is required to perform this action**, I ever posted 3 posted.
![Selection_463](https://user-images.githubusercontent.com/24691983/143556810-54016fac-1b79-41d6-8f1f-b66b6a1c1b0d.png)

Please suggest me, Thanks.
