### ISSUE TITLE
Mandatory field popup showing unncessary (hidden) field too in popup.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23043]
Impacted versions:
	> V11E
Steps to reproduce:
	> Click on menu : Employees > Challenges > Badges 
	> Click On Grant Button located in Kanban view.
	> without filling any single mandatory field (employee_id) , just click on 'Grant Badge' Button. 

Current behavior:
	Its popping up a message ,
		> The following fields are invalid:
			> User
			> Employee
	While there is only one field which is mandatory (employee_id) in popup.Still its showing for User (second field which is hidden) as well.
	
	
Expected behavior:
	> It should show only one field as invalid in popup of mandatory.
	  as another field is invisible so.

Video/Screenshot link (optional):
Screenshot >
	https://www.awesomescreenshot.com/image/3172143/d601ea2f68be0854b351391888e20329
Video >
	https://youtu.be/0VU9BewTLjw

Hope you can understand !
Many Thanks !

**Comment by dipsshah42** [comment]
@Yenthe666 i believe this is also from .js side issue. is it ?

**Comment by Yenthe666** [comment]
@dipsshah42 I assume so yes. @ged-odoo could one of the guys have a look?

**Comment by dipsshah42** [comment]
@Yenthe666 and @ged-odoo any updates on this ?
