### ISSUE TITLE
[10.0] Bank statements reconcile interface, blue lines, liquidity accounts (example on l10n_fr)

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#23040]
Here are the steps to reproduce the problem:

1) Create a new database with demo data and country = France
2) Login as admin user
3) Install the module account_accountant
4) Check that the french chart of accounts in loaded

Note : in l10n_fr,  the account 511200 "Chèques à encaisser" (checks to cash in) has Type = "Bank and cash"

5) Create a new journal :
Name : Customer Checks
Type : Bank
Short Code : CHQ
Default debit/Credit account : 511200

6) Create a new customer invoice :
Customer : Camptocamp
1 invoice line. Total amount with taxes : 30.00 €
Validate it.

7) On this new customer invoice in "open" state, click on "Register Payment"
- Payment Journal : Customer Checks
- Payment amount : keep default value (= 30,00 €, the total amount of the invoice)

8) On the dashbord, go to the journal "Bank" and create a new bank statement :
Journal : Bank
1 transaction lines :
- Label : Check C2C
- Partner : keep empty
- Amount : 30.00

9) Click on the "Reconcile" button
For the bank statement line with 30,00 € (without partner), Odoo proposes the line in the account 511200 for 30.00 € as blue line.
Select that blue line and click on the button "Reconcile". As it is a blue line, no new account move is generated.
=> In this case, it is a problem: we would need to create a new account move between 511200 and 512001 (bank account linked to the "Bank" journal). So the line linked to account 511200 should not be a blue line but a black line.

Simple workaround: 
A) change the configuration of the account 511200 from "Bank and Cash" to something else (such as "Current Asset" for example).
B) In the reconcile interface of the bank statement, it will now propose a line of 30.00 linked to account 511200 as black line, not as blue line any more. So, if you select that line and validate it, it will create a new move line (that's what we want).

I tried to find in the code the exact algo that puts the line as blue line or black line, but I could not find it. The "blue"color is defined here https://github.com/odoo/odoo/blob/10.0/addons/account/static/src/less/account_reconciliation.less#L326
The "reconciliation lines" are generated here https://github.com/odoo/odoo/blob/10.0/addons/account/models/account_bank_statement.py#L557  but the distinction between blue lines and black lines doesn't happen here...
But I still don't find the piece of code that decide whether the proposed line is black or blue.

So:
a) do we need to fix something in the account module of Odoo ?
b) or do we need to update l10n_fr (and probably chart of accounts of other localisations) and make sure that only real bank accounts have Type = "Bank and Cash" ?

**Comment by fclementic2c** [comment]
@alexis-via I use the same workaround. Odoo does not allow entries like bank to bank from a bank statement which is a problem in the very come cases you describe here. 
Similar issue with the the account '580 - Internal transfert' by the way which is suppose to be a bank type account as per french CoA but not possible with odoo.

:+1:

**Comment by alexis-via** [comment]
@fclementic2c Thanks for your feedback. I see that I'm not the only one to have a problem with this!

@qdp-odoo What do you think about this problem ? Should we try option a), or should I go for option b) and make a PR to modify the chart of accounts in l10n_fr ?

**Comment by qdp-odoo** [comment]
definitively solution a): the accounts created by odoo when you create a new bank/cash journal are the only ones that should be of type 'bank and cash'.

**Comment by qdp-odoo** [comment]
PR has been merged, this issue can be closed.

thansk
