### ISSUE TITLE
Outlook plugin

### ISSUE THREAD

**Issue by Hari-Guhan-s** [odoo/odoo#23042]
Impacted versions:
7.0 or above

Steps to reproduce:
Install outlook_plugin 
Download outlook 64 bit plugin.msi installer

Current behavior:
Able to install plugin successfully
But could not see openerp menu under add ins option in outlook 2016

Expected behavior:

A menu under add ins named openerp  to configure and use outlook plugin

**Comment by Yenthe666** [comment]
Hi @Hari-Guhan-s,

Thank you for your report.
I'm afraid that the support for Odoo V7 and Odoo V8 has ended. The `plugin_outlook` module has also been removed from Odoo 8 and up and is no longer used/shipped anymore.
As this addon is deprecated and as Odoo 7 is too I'm closing this bug report. I'd advice you to ask for help on the official Odoo help forums at help.odoo.com

Regards,
Yenthe
