### ISSUE TITLE
OdooV11E : Traceback while adding model Constraint.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23059]
@Yenthe666 , one more :)

Impacted versions:
	> Odoo V11E

Steps to reproduce:
	> Open Settings > Database Structure > Model Constraint > Create,
	> Create Module from here > it will open two popup where one is with Traceback. 

Current behavior:
	> its throwing traceback 'join() argument must be str or bytes, not 'bool'

Expected behavior:
	> It should allow to add model / constraint properly.

Video/Screenshot link (optional):

Video > 	https://youtu.be/4vy-jEWqLs8
Screenshot > 	https://www.awesomescreenshot.com/showImage?img_id=3172729

Thanks.

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for (yet another) bug report!
This is also a confirmed bug:
![image](https://user-images.githubusercontent.com/6352350/36204175-738b9ac2-118a-11e8-8ec1-47a541697d1d.png)
@xmo-odoo could you check this one too?

Regards,
Yenthe

**Comment by xmo-odoo** [comment]
Thanks for the report. The field was changed to be non-creatable as creating module records through the UI makes very little sense.
