### ISSUE TITLE
Odoov11E : Traceback while adding a field and selecting all group in Email Template.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23055]
Impacted versions:
	> Odoo V11E

Steps to reproduce:
	> Open Settings > Email > Templates > Open any Template,
	> Navigate to Tab 'Dynamic Placeholder Generator' ,
	> Click on Field > Create and Edit ,
	> Move to 'Access Rights' Page > Click on 'Add an item' (Group) ,
	> Click on checkbox to select all groups in one go.

Current behavior:
	> Its Generating Traceback while creating a field and adding security group.

Expected behavior:
	> It should allow to creation field and adding of group.

Video/Screenshot link (optional):

Video > 	https://youtu.be/1IYHBgX26Bc
Screenshot > 	https://www.awesomescreenshot.com/image/3172474/32f215003e1e4070f4d1a105f05f54ec

Thanks !

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for the bug report.
This is indeed a bug (in the JavaScript framework):
![image](https://user-images.githubusercontent.com/6352350/36199547-23fc12e4-117a-11e8-8fd8-6224577e655e.png)
@ged-odoo could you have somebody from the team have a look?

Regards,
Yenthe

**Comment by aab-odoo** [comment]
@VincentSchippefilt Another occurrence of the issue with nested SelectCreateDialog instances. Could you close this once it is fixed?

**Comment by VincentSchippefilt** [comment]
Yes, I will work on this bug in the coming days.

**Comment by Yenthe666** [comment]
@aab-odoo and @VincentSchippefilt could you guys give feedback on this one please?

**Comment by aab-odoo** [comment]
Hello,

The issue has been fixed by d4c8a7cfb4acf54b730c149c025b355b2f88ec77

Regards
