### ISSUE TITLE
OdooV11E : Not able to save record of Vehicle Odometer (Fleet)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23061]
Impacted versions:
	> OdooV11E
Steps to reproduce:
	> Fleet menu > Vehicles > Vehicles  Odometer > Remove filter > Create Record 
	> Try to save it.

Current behavior:
	> its not allowing to save a record.

Expected behavior:
	> it should allow to save relevant record.

Video/Screenshot link (optional):
	Video 		> https://youtu.be/mWQFNcLrgBo

Thanks.

**Comment by Yenthe666** [comment]
Hi @dipsshah42,

Thanks a lot for the report.
This one is odd, I had to test it twice before I figured out it is just not saving 😆 
@ged-odoo another one for you 😨
