### ISSUE TITLE
[11.0] Bank Statement: Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#23076]
Impacted versions:
11.0
Steps to reproduce:
- Create new bank statement
- Add more than 40 items, be sure that the total items added exced the items limit in the tree view
- Set random dates in each item, you can create a server action that use next code 
https://gist.github.com/hugho-ad/9ad8993e1ad02bb5b5129e5dbbb51a81
- Try to edit any line
Current behavior:
When _applyOnChange method is executed it fails 

Uncaught TypeError: Cannot read property 'id' of undefined
    at web.assets_backend.js:1167

It seems that it a issue with handle widget, since it tries to sort by sequence but it can't since the model has a specific order
![image](https://user-images.githubusercontent.com/10233975/36232611-26ee509c-11a8-11e8-9be5-755de0eed6b7.png)

**Note:**
The error it is not trigger when we set item limit at the same qty of items in the view

Expected behavior:
Be able to edit

Video/Screenshot link (optional):
Lines
![image](https://user-images.githubusercontent.com/10233975/36232729-873938cc-11a8-11e8-81ff-47772d60ccab.png)

![image](https://user-images.githubusercontent.com/10233975/36232584-ff84da44-11a7-11e8-9bb4-24eb6eb965cb.png)

**Comment by sswapnesh** [comment]
Related to #22770

**Comment by Elkasitu** [comment]
cc @ged-odoo

**Comment by ged-odoo** [comment]
@mge-odoo could you have a look at this?

**Comment by Yenthe666** [comment]
Good job guys! These days I can wake up and some new issues are already labeled & the right person is already pinged. Keep up that good work @Elkasitu and @ged-odoo 👏

**Comment by mge-odoo** [comment]
Fixes by odoo/odoo@a16013b

Thanks for reporting.

Martin
