### ISSUE TITLE
[BUG] Aged partner report in multi-company

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#23072]
Ready? Go!

**This:** https://github.com/odoo/enterprise/blob/6fb0346735c56a093c749a8ba898757a3eece274/account_reports/models/account_aged_partner_balance.py#L36
**does not parse the selected companies filter, so that (eg):**

https://github.com/odoo/odoo/blob/b4bda28f0daf6188a8575877ea9a2f68497686b7/addons/account/report/account_aged_partner_balance.py#L30
**cannot be construed with the selected companies, which for example here:**
https://github.com/odoo/odoo/blob/b4bda28f0daf6188a8575877ea9a2f68497686b7/addons/account/report/account_aged_partner_balance.py#L54

**causes the ignorance of the selected filter.**

------------------------------

Out from the current demo.odoo.com, this filter is well intended to exist:
http://nimb.ws/RGYdML

-------------------------------------
**Observed behaviour:**

- The company filter is just plainly ignored (always takes current company of the user)

**Desired behaviour:**
- The company filter is respected so that if a due account on the child company has been paid on the parent company it would not show.

- This has another implication to look for: Even though I only have access to the child company, any account paid & reconciled on the parent company ought not to show as an open balance.

**Comment by Yenthe666** [comment]
@blaggacao thanks for the report. I assume you're talking about Odoo V11?

**Comment by qdp-odoo** [comment]
closed by https://github.com/odoo/odoo/commit/fcaf459a89b721e2ebc8b758980c76f27052e24f
