### ISSUE TITLE
Wrong COGS when invoice from dropshiping

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#23075]
Impacted versions:
* 11.0

Steps to reproduce:
* Create sale order
* Add sale order line with route *Dropshiping*
* Validate the sale order
* Validate purchase order and receive
* Create invoice from sale order
* Validate invoice

Current behavior:
The journal items by COGS is wrong
![inv 2018 0006 odoo](https://user-images.githubusercontent.com/7595505/36229448-dba90f74-119c-11e8-8399-1ba222a5fcaa.png)

Expected behavior:
The account 220000 Expenses should be by debit
The account 101130 Stock Interim Account (Delivered) should be by credit

**Comment by lap-odoo** [comment]
@JulioSerna Thanks for reporting this! We are aware of this issue and we already have a fix : https://github.com/odoo/odoo/pull/23331. It still needs to be reviewed and merged, will be done soon. Thanks again
