### ISSUE TITLE
[11.0] Improve position of 'forum alert' on Ask Question

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23071]
Impacted versions: 11.0

Steps to reproduce:  Login with Portal User (Who has no Karma) -->  Click On Ask Question

Current behavior: Alert message will be generated at Bottom Right of the Page

![](https://image.prntscr.com/image/WS1LKoyVS5_Uw5Qe78tjKw.png)

Expected behavior: Improve Position of Alert Box and It should not Create multiple Alert box when User clicks again on Button.
(If we will click on 'Ask Question' buttons three times it will generate three alert boxes at same position)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@JKE-be Could you please check this?

**Comment by JKE-be** [comment]
Not blocking. So, not a priority. => PR welcome.

Will be refactored with BS4 for v12

**Comment by sswapnesh** [comment]
Agree with that, But it should not be labeled as wishlist.

**Comment by JKE-be** [comment]
Wishlist is ambiguous, but it is also the stack of 'tasks' that we could do if we had more resources available.

So for me, wishlist issue/pr are no more in my pipe.

**Comment by JKE-be** [comment]
Internal task-1829835
