### ISSUE TITLE
[10.0-point_of_sale] performance issue on pos_session form view because of _compute_picking_count function

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#23073]
Impacted versions:
10.0
Steps to reproduce:
On production instance (db is less than 2Gb), we have very slow performance on pos_session form view.
Current behavior:
Opening pos_session form view is very slow (> 15 minutes)
Expected behavior:
Opening pos_session form view should be less than 1 minute

**Comment by invitu** [comment]
Analysis : 
- postgresql server does not show performance
- python process takes 100% CPU
- we did a strace on the process and we noticed that there is a lot of queries on stock_picking table

We removed action_stock_picking button from the view and the issue is solved.
We concluded that the performance issue occurs in _compute_picking_count function

**Comment by pimodoo** [comment]
Hello,

We cannot improve the compute function for this field. If you want to have the session form faster and keep the access to the pickings that are not done, you can remove the field 'picking_count' from the button 'action_stock_picking' and remove the 'attrs' attribute from the same button. It won't compute the number of picking anymore.

Best regards

**Comment by invitu** [comment]
@pimodoo thank you, we are going to customize as you suggested
But it's a performance issue and our use case is a very small store with less than 400 orders per session, I cc @odony @mart-e @KangOl @legalsylvain @alexis-via @pedrobaeza
Maybe the solution that @pimodoo gave here should be committed into odoo

**Comment by legalsylvain** [comment]
Hi @invitu. Thanks for reporting this bug. I can not figure out why computing this field is so slow ! (15 minutes !)
it's just a count of some pickings.

The workaround mentioned by @pimodoo should work but it's quite problematic. As an alternative, we could in odoo core : 

**Solution 1** : set a store=True in the field picking_count with ``@api.depends('picking_id.state')``
**Solution 2** : do not compute picking_count on form view and allways display the button.
