### ISSUE TITLE
[11.0] Purchases created from Reordering Rules are not linked to that Rule

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23096]
Impacted versions: 11.0

Steps to reproduce: Inventory --> Reordering Rules --> Purchases

Current behavior: If you create new PO from Reordering Rules It is not linked to that Rule

![](https://image.prntscr.com/image/tOxQoQu6RO6gf2iE-KvEFQ.png)

Expected behavior: It should be linked to Particular Rule or Creation of Po should not be allowed from there.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
For you @sle-odoo ?
Maybe we can pass default orderpoint_id from there or Remove PO Creation.

**Comment by sle-odoo** [comment]
I think if we linked the purchase order to the orderpoint it could be inconsistent, 'cause nothing prevents you to add po line of another product. So we should indeed remove the create button from this tree view, but AFAIK it's not possible in the action. So we would have to inherit_id primary=True the original tree view, add create=0, then force this new tree view in the action of the stat button.

@lap-odoo do you think this report is relevant usability wise?

**Comment by amoyaux** [comment]
@sswapnesh Seems to be a regression from 10.0 when we removed the procurement order. I will check if it's possible to do something in stable.

**Comment by Yenthe666** [comment]
Handled in https://github.com/odoo/odoo/commit/2c5022b4f33b1406736d0f9a0bee76942ba0bf7f 🎉
