### ISSUE TITLE
[11.0] Invalid form view binding on Timesheet Calendar's View 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23092]
Impacted versions: 11.0

Steps to reproduce: Go to Timesheet --> Create new Entry from Calendar View

![](https://image.prntscr.com/image/8aEbJIRARh6YCR9jYeAZAg.png)

Current behavior: It will open Incorrect from view. (Entry will be not linked to Project created from Here)

![](https://image.prntscr.com/image/CKFh-stEQW_uQ4lwM4XlhQ.png)

Expected behavior: It should open Default form view which is used for Timesheet entry

![](https://image.prntscr.com/image/hyTaV9zKRPq1esSqf35nNQ.png)

Video/Screenshot link (optional):

**Comment by jem-odoo** [comment]
@ged-odoo Any idea on this ? Why doesn't it takes the form view defined on the action as ir.actions.act_window.view explicitely ?

**Comment by ged-odoo** [comment]
fixed in 11.0 https://github.com/odoo/odoo/commit/e0424b960315b8328f7da96f9d5bc58f2628cd47
