### ISSUE TITLE
[V11] Error with write-off in favor

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#23091]
Impacted versions:
11.0 - https://github.com/odoo/odoo/commit/251b2fdc548c7edc55748e4a6aec91507f39a247

Steps to reproduce:

1.- Create a new customer invoice to 100.69
2.- Validate the invoice
3.- Make a payment to 101, with write-off

Current behavior:
I get this error:
Wrong credit or debit value in accounting entry !

Expected behavior:
I expected that the payment is validated, and generate a movement as this:

![bnk1 2018 0002 odoo](https://user-images.githubusercontent.com/7606656/36265825-ab0febd2-1235-11e8-9d92-de4e3f3f668a.png)

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=N-SCfVUeKvE

**Comment by simongoffin** [comment]
Closed with 0da5d63f526398022f918bcfdf082c75f26a8b2e
