### ISSUE TITLE
[11.0] Could not re-install Stock module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23094]
Impacted versions: 11.0

Steps to reproduce: Uninstall Stock module --> Re-install it

Current behavior: Tracabck 

![](https://image.prntscr.com/image/BFYy3KU4TWWY2-SLEJXlZQ.png)

Expected behavior: Module should be installed 

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@sle-odoo  Could you please check this?

**Comment by sle-odoo** [comment]
fixed by #22265 probably

**Comment by sswapnesh** [comment]
When trying to install Manufacturing module

![](https://image.prntscr.com/image/maW_JDK7T_qyiUKDa0PQeg.png)

**Comment by sswapnesh** [comment]
Just tested on Latest Runbot [http://303281-11-0-665496.runbot14.odoo.com](http://303281-11-0-665496.runbot14.odoo.com)

**Comment by sle-odoo** [comment]
this issue is a duplicate of #22243
we don't have the ressources at the moment to look into it sadly

i'll close the original issue once it's fixed

thanks for the report

**Comment by sswapnesh** [comment]
My bad, Agree with You.

**Comment by sle-odoo** [comment]
no worries
