### ISSUE TITLE
[10.0] Odoo cant import Watcher  (when he istalled)

### ISSUE THREAD

**Issue by advance** [odoo/odoo#23109]
Impacted versions: 10V
Steps to reproduce: 
1. $ pip install watchdog
2. odoo-bin --dev=reload
Current behavior:
2018-02-16 09:04:40,566 4180 WARNING ? odoo.service.server: 'watchdog' module no
t installed. Code autoreload feature is disabled

P.S.
Hello, guys. I think i read all tickets in internet for google 'Watcher odoo windows don`t work why who i am ad e.t.'
In real i use pip install watchdog, and in py file on desktop its work
 >  try:
>     import watchdog
>     from watchdog.observers import Observer
>     from watchdog.events import FileCreatedEvent, FileModifiedEvent, FileMovedEvent
>     except ImportError:
>     watchdog = None
>     print(watchdog)
>     if watchdog:
>     print("'Well, its work")
>     ###its work
>     else:
>     print("'watchdog' module not installed. Code autoreload feature is disabled")

But why odoo cant import them???
In odoo, import return nothing.
Should i install it for odoo folder, or what???
Thank you, for responce.

**Comment by Elkasitu** [comment]
Hi,

The python that Odoo uses in Windows is different than your system-wide python, if you want to install it for Odoo you need to navigate to `C:\Program Files\Odoo\python\` and from there, enter the command-line and call the `pip.exe` found in the `\scripts` folder.

**Comment by Elkasitu** [comment]
`cd "c:\Program Files\Odoo 11.0e\python"` then `Scripts\pip.exe install watchdog`

**Comment by ctac1412** [comment]
if i not have python folder?
in C:\Program Files (x86)\Odoo 10.0

**Comment by Elkasitu** [comment]
Ah yeah my bad sorry, apparently there is no `\python` folder in v10 of the Odoo windows package (there is one for v11), unfortunately there is no way to use watchdog or any other external libraries not included by default, sorry for the inconvenience.
