### ISSUE TITLE
Deposit product category account is ignored on SO advance payments

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#23100]
Impacted versions: Master, 11.0, 10.0

Steps to reproduce:
* Create product category Deferred
  * Specify an income account (something other than the default one for this company)
* Create product Sale Deposit
  * Specify the Deferred category from above
  * Don't specify an income account
* Select the new product for Deposit Product in sales settings
* Create invoice from sales order
* Specify a down payment amount

Current behavior:
The account on the invoice line is the default income account

Expected behavior:
The account on the invoice line should be the income account specified on the product category

The problem is here:
https://github.com/odoo/odoo/blob/71c36f608b1f1520b45e26d2b044e5395b979748/addons/sale/wizard/sale_make_invoice_advance.py#L70

**Comment by oco-odoo** [comment]
@matt454357 Thank you for reporting the issue. I reported it to our teams so that we can fix it.

**Comment by Yenthe666** [comment]
@oco-odoo is there any update on this one?

**Comment by oco-odoo** [comment]
@Yenthe666 They're working on it, should be okay soon ;) (https://github.com/odoo/odoo/pull/23633)

**Comment by Yenthe666** [comment]
Hi @matt454357,

This should have been fixed in https://github.com/odoo/odoo/commit/aaadfd7d768e6271afc287cea2de19c769aa786a

Regards,
Yenthe
