### ISSUE TITLE
Awaiting Payment shows wrong value in Accounting Dashboard

### ISSUE THREAD

**Issue by gokhanerdogdu** [odoo/odoo#23107]
Impacted versions: 
V10 and V11

Steps to reproduce:
In accounting, Customer Invoices Dashboard, Waiting payment total is showing wrong results if there are partial payments. 
For example, I have an invoice in total amount of 118. Dashboard shows me 1 Awaiting payment in total amount of 118. This is fine so far. If there is 50 partial payment to the invoice, again the dashboard shows 1 Awaiting payment in total amount of 118 in stead of 68. The correct amount should be 68 since the residual for that invoice is 68. 
If there are lots of invoices with partial payment, this amount shows huge difference with the exact awaiting payments. 

Video/Screenshot link (optional):

![screen shot 2018-02-15 at 17 07 09](https://user-images.githubusercontent.com/20369981/36296823-4df4f1ce-1300-11e8-92d6-151d72664884.png)
![screen shot 2018-02-15 at 17 06 16](https://user-images.githubusercontent.com/20369981/36296824-4e4a8daa-1300-11e8-806a-d99a4fd7bc45.png)

**Comment by celm1990** [comment]
Please see PR #19047

**Comment by lap-odoo** [comment]
@gokhanerdogdu Thanks for the feedback. This has been improved in SaaS 11.1.
