### ISSUE TITLE
[11.0-point_of_sale] accounting setup are invisible in pos_config

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#23128]
Impacted versions: 11.0

Steps to reproduce:
Open pos_config form view
Current behavior:
Accounting setup is invisible
Expected behavior:
Accounting setup shoul be visible

Solution:
is_installed_account_accountant is always False because account_accountant module does not exist in v11
I suggest that the acccounting part should be visible to account.group_account_user

**Comment by pimodoo** [comment]
Hello,

The module 'account_accountant' is an enterprise module, as those fields are only significant when this module is installed we don't want to show them, and the installation of the localization set up the needed fields correctly.

Best regards

**Comment by MGinshe** [comment]
Sorry to bump an old issue, but I believe that this does impact CE users fairly significantly, especially in the case where a user has migrated from v10 CE -> v11 CE.

The fields hidden by `is_installed_account_accountant` are `journal_id` and `group_by`.

These fields _were_ editable in v10 CE, so these fields could have been set pre-migration, but are not editable after migrating to v11. A typical POS setup would have a dedicated `journal_id` for each `pos.config`, but that is not possible right now.

Furthermore, while the fields may only be significant in EE, they are still _used_ in CE. For example:
- If users are pulling data from the Odoo database, into an external reporting tool (such as Grafana).
- If users are exporting data via Odoo's export functionality.
- The fields still used/selectable in various default Odoo reports (e.g. the `Journals Audit` report).

I suggest fixing this issue by either:

- Checking the users group (probably `account.group_account_user`?), or
- Checking for `account_invoicing`.

I've opened another issue (#31304) with an explanation, and links to the culprit files. 

What are your thoughts @nim-odoo @pimodoo? I'm happy to create a quick PR to implement one of the fixes.
