### ISSUE TITLE
odoo 11.0 not starting properly with workers > 0

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#23124]
Impacted versions: 11.0

Steps to reproduce:
Install odoo 11.0 in debian stretch using standard procedure.

Using Ansible, you can use the playbook https://github.com/OCA/ansible-odoo

name: Odoo 11
hosts: odoo11
roles:
role: postgresql
postgresql_version: 9.6
role: ansible-odoo
odoo_version: 11.0
odoo_config_unaccent: True
odoo_config_admin_passwd: SuPerPassWorD
odoo_config_workers: 4
odoo_config_proxy_mode: True
`

Current behavior:
The UI is broken, with the following error:
![image](https://user-images.githubusercontent.com/7683926/36335951-0639f792-1384-11e8-8b78-ae26daafd03e.png)

When starting with workers = 0 it works perfectly.

**Comment by sswapnesh** [comment]
May be related to #21391

**Comment by Yenthe666** [comment]
@d-fence could you have a look/test on a debian stretch with multiple workers?

**Comment by jbeficent** [comment]
Finally I found I was putting wrong valued in limit_nemory_hard and limit_memory_ soft. See
https://github.com/odoo/odoo/pull/23131
