### ISSUE TITLE
[10.0] Rounding error in total tax value in sale order and invoice

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#23125]
Impacted versions: 10.0 - Test on Runbot http://303701-10-0-484110.runbot8.odoo.com

Steps to reproduce:
Create a sale order and its invoice with 4 products
- product 1: unit price: 598.89 - tax: 8.5% - quantity: 1
- product 2: unit price: 329.84 - tax: 8.5% - quantity: 1
- product 3: unit price: -59.89 - tax: 8.5% - quantity: 1
- product 4: unit price: -32.98 - tax: 8.5% - quantity: 1

product 2 and product 4 have negative unit price because I encounter the error while testing discount.

Current behavior:
Odoo calculate a untaxed amount of:835.86 and a total tax of: 71.06

Expected behavior:
Odoo must calculated a untaxed amount of:835.86 and a total tax of: 71.05
<img width="1226" alt="capture d ecran 2018-02-16 a 23 10 05" src="https://user-images.githubusercontent.com/14253152/36337526-a1fcc256-136e-11e8-93b1-b4a048b0d452.png">

Video/Screenshot link (optional):

**Comment by rgeromegnace** [comment]
Bonjour,

I Hope you will find a solution quicky because the odoo instance is in production.
This problem is touchy because the odoo instance is connected with a e-commmerce web site and the order amount of the e-commerce web site is different with the invoice amount of Odoo.

Regards,

**Comment by Yenthe666** [comment]
@rgeromegnace if this is a high priority issue then please report it at odoo.com/help and use your enterprise license in order to get it handled.
Github is a best effort issue fixing policy.

**Comment by rgeromegnace** [comment]
Ok thanks, I will create the issue on odoo.com/help two.

Regards,

**Comment by gdgellatly** [comment]
Looks like round per line is set on tax.

**Comment by rgeromegnace** [comment]
Hello @gdgellatly

What do you mean by "round per line is set on tax"?

Regards,

**Comment by gdgellatly** [comment]
https://www.odoo.com/forum/help-1/question/round-only-total-in-invoice-19895

**Comment by rgeromegnace** [comment]
Hello,

@gdgellatly Thanks to you and odoo support team,the problem is solved.
It was just a problem of rounding method setting.

Regards,
