### ISSUE TITLE
Access restriction with packages and sale own documents only

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#23127]
Impacted versions:
[11]
Steps to reproduce:

- enable sale user setting "own documents only"
- enable packages
- enable user setting inventory "user"
- create 2 users
- create sale order - confirm from user 1
- user 2 , delivery, "put in pack".

when transfering delivery "put in pack" with sale order not in "own documents only", produces access restriction error

Current behavior:
- access restriction error calls for read only of sale.order

**Comment by amoyaux** [comment]
Hi,
We'll have a look. Thanks for the report and your patience.

MB 817439
Regards

**Comment by Yenthe666** [comment]
@amoyaux is there an update here?

**Comment by sle-odoo** [comment]
solved by e155244007bf6bfd88e4b4ee248e9570a2725d5f
