### ISSUE TITLE
odoo 11 import sale order 

### ISSUE THREAD

**Issue by almustafago** [odoo/odoo#23136]
Impacted versions: odoo 11

Steps to reproduce:  import sale order with product in line

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![import](https://user-images.githubusercontent.com/15360515/36353213-a817ad56-14d4-11e8-9a9d-c3b059026708.PNG)

**Comment by Yenthe666** [comment]
Hi There,

The formatting of your import is not correctly built up and you're referring to a non-existing item.
