### ISSUE TITLE
Cannot cancel validated invoice if amount is zero

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#23140]
### Impacted versions:

10.0, 11.0 (haven't tested other versions)

### Steps to reproduce:

- Install modules `account_invoicing` and `account_cancel`.
- Set "Allow Cancelling Entries" to True for Customer Invoices journal.
- Create a customer invoice with zero amount, and validate it.

### Current behavior:

There is no option provided to cancel the invoice (i.e. "Cancel" button does not show).  This is not ideal for keeping a clean history.

### Expected behavior:

"Cancel" button shows and you can cancel the invoice.

### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7766939/36362611-4cac25da-1571-11e8-974d-07ade52213f6.png)

**Comment by yostashiro** [comment]
OPW: 817025

**Comment by lap-odoo** [comment]
@yostashiro Hi, this has been fixed in version 11.2. Thanks for feedback.
