### ISSUE TITLE
Missing fields in sale order with more then 40 order lines

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#23154]
Impacted versions:
ODOO 11

Steps to reproduce:

1. Create a quote/sales order
2. Create order with more then 40 order lines -> results multiple pages (e.g. 1-40/60; 41-60/60)

Current behavior:

When clicking to the next order page (to 41-60/60) couple fields will disappear: "delivered quantities" and "invoiced quantity". When adjusting quantities on the second page some weird things happen.

Expected behavior:
Same functionality and view as on page 1 of the sales_order.

Video/Screenshot link (optional):
Two screenshots in attachment to present the bug.
<img width="797" alt="example_1" src="https://user-images.githubusercontent.com/36632285/36382603-da7136b8-1589-11e8-9639-17aab3f6e836.png">
<img width="807" alt="example_2" src="https://user-images.githubusercontent.com/36632285/36382608-deef4dce-1589-11e8-9f6d-4833281aa4c4.png">

**Comment by sswapnesh** [comment]
Hello @Patrickar 
I have tested Same on Runbot and Seems working fine.
(Fields Delivered/Invoiced will be only visible when Order state is Sale Order or Done)
![](https://image.prntscr.com/image/Ki4A0v9TSyKWRIfg3P26xA.png)


As you mentioned 

> When adjusting quantities on the second page some weird things happen.

I have tried to enter Order Qty manually as well.

![](https://image.prntscr.com/image/ib58SgVARKetEB9VPv5tig.png)
