### ISSUE TITLE
Attach ics-file on event registration

### ISSUE THREAD

**Issue by BurtGummer** [odoo/odoo#23152]
Hello,

is there a way, to attach the date from a event as ics-file to a registration mail? I have found this:

https://www.odoo.com/de_DE/forum/hilfe-1/question/attach-ics-file-on-event-registration-122739

but there is no ics-file in the mail?

Any ideas?

Odoo 11 on Debian 9.3.

**Comment by invitu** [comment]
here is a solution : 
https://www.odoo.com/fr_FR/forum/aide-1/question/create-attachment-in-mail-template-122871

**Comment by Yenthe666** [comment]
Yeah and it is not supported by default right now, sorry.
