### ISSUE TITLE
[11.0] Menu Leaves to Approve > Leaves. Remove filters and you get error because of Multi Company

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#23162]
Impacted versions:
V11

Steps to reproduce:
Make sure you have multiple companies A, B and C.
1. UserA is HR manager but has rights for companies A, B and C. And he is allowed to approve the leave request.
2. UserB create a leave request in company B
3. UserC create a leave request in company C

Odoo CE, If you go to the left menu: "Leaves to Approve" > Leaves, you can remove all the filters "To Approve" and "My Department Leaves". Now you see all the leaves.
If you click on the request of UserB you get the error: (Document type: hr.holidays.status, Operation: read).

Current behavior:
The view "Leaves to Approve" > Leaves  (hr.holidays.allocation.tree) allows to much. You can see all the request over all the companies. And when you try to open one, you get the error.

Expected behavior:
The view "Leaves to Approve" > Leaves  (hr.holidays.allocation.tree). should only show the request of the current company.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@RomainLibert that PR is never merged 😉

**Comment by RomainLibert** [comment]
My bad, I went too quick

**Comment by tivisse** [comment]
Done at https://github.com/odoo/odoo/pull/42766

Thanks.
