### ISSUE TITLE
[11.0] crm: error trying to create a new opportunity

### ISSUE THREAD

**Issue by alxolivares** [odoo/odoo#23169]
Impacted versions:
11.0

Steps to reproduce:
1. Assign **User: Own Documents Only** to the demo user for sales application.
2. Assign the demo user to a sales channel.
3. Log in with demo user.
4. Go to CRM and create a new opportunity.

Current behavior:
A Validation error is raised trying to create the new opportunity.

Expected behavior:
A new opportunity should be created without problems.

Video/Screenshot link (optional):
![screenshot_20180219_141033](https://user-images.githubusercontent.com/13812335/36391851-c7542172-157e-11e8-9a9a-205945d2ff4a.png)

**Comment by sswapnesh** [comment]
Maybe related to #22360 and #22923

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/commit/262be78957dc8f7d9db87e49ee36fe9b5e735fbd
Cc: @kebeclibre
