### ISSUE TITLE
POS - Customer Information is not updated Runtime

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23166]
Impacted versions: 11.0 (probably all)

Steps to reproduce: Go to Customer Screen in POS --> Edit Customer Information

![](https://image.prntscr.com/image/1y0mcn4lQxqXrWG9uQCpQQ.png)

Comeback on the Same screen after Saving the record.

![](https://image.prntscr.com/image/_A39YH91TsmqON2p26vI-w.png)

Current behavior: Customer Information is not Updated, Need to Refresh the Page

Expected behavior: Information should be updated runtime.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Duplicate of #13856 (Found later after Submitting Issue)

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks for the report.
This is indeed a duplicate of https://github.com/odoo/odoo/issues/13856 on which I've added labels & pinged the right people. Would you mind that I close this one in favour of the other? It should be fixed from 9.0 up anyways.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Sure
