### ISSUE TITLE
[11.0]POS - Could not Complete Return Products workflow due to negative amount in Invoice

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23167]
Impacted versions: 11.0 

Steps to reproduce: Create POS Order (Frontend) --> Go to Order in Backend -->Create Return Order  --> Make Payment --> Create Invoice for Return Order --> Validate Invoice

![](https://image.prntscr.com/image/7ZankfFbRG_id_IWmHbaTQ.png)

![](https://image.prntscr.com/image/TSQh7_8XTs_xgyRE5ys1Ww.png)

![](https://image.prntscr.com/image/mnO0JzAbTeSU6VWejTop8g.png)

Current behavior: Can not validate Return Invoice due to Negative Amount.

![](https://image.prntscr.com/image/E0_I9J-KRLu4uZBcDoAetA.png)

Expected behavior: Credit not should be Created Instead of Negative total

Video/Screenshot link (optional):

**Comment by minos84** [comment]
Just a question to @sswapnesh. Do you need to invoice a customer after paying him? In my understandings, in POS, you don't need to create an invoice after payment.

Regards

**Comment by qdp-odoo** [comment]
@pimodoo negative invoices can't happen (if you think so, have a talk with fp), you need to create a positive credit note instead

**Comment by sswapnesh** [comment]
Possible Improvement: We should keep track of Refund Invoice as well to prevent multiple refund.

**Comment by pimodoo** [comment]
@qdp-odoo Totally agree with you, I will check how the POS handle it and fix it.

**Comment by sswapnesh** [comment]
@pimodoo  Possible Workaround at  [https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L561](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_order.py#L561)

**Comment by smetl** [comment]
@pimodoo I suggest that https://github.com/odoo/odoo/compare/11.0...odoo-dev:11.0-fix-23167-las

**Comment by pimodoo** [comment]
@smetl seems good to me, have you ever tested it? if it's ok for you you can merge it.

**Comment by smetl** [comment]
issue solved on 11.0 at revision https://github.com/odoo/odoo/commit/515160978ad6807504378600acec116674624abb

Thanks
