### ISSUE TITLE
[11.0] Uninstalling Signup module breaks General Settings 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23171]
Impacted versions: 11.0

Steps to reproduce: Uninstall Signup module --> Go to General Settings --> Make a Change in Some Configuration --> Save

![](https://image.prntscr.com/image/ehf0ZrHGRrG45SO0jZIUVg.png)

Current behavior: Traceback on Screen

![](https://image.prntscr.com/image/XHFHi-z8TJePn2X_0jvZWg.png)

Expected behavior: Should be able to Save Settings

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Yep - absolutely a bug. Thanks for the report @sswapnesh!
