### ISSUE TITLE
Parent company's Salesperson not being proposed to quotation if it is created with public user

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#23175]
**Impacted versions:**
10.0e

**Steps to reproduce:**
1. Create a portal user, set the "Salesperson" as empty and assign a parent company to the user. 
2. Assign a "Salesperson" to the parent company. 
3. Add products to the cart in shop without login. 
4. Login and process the checkout. 

**Current behavior:**
A quotation is created and the "Salesperson" of the quotation is not set. 

**Expected behavior:**
A quotation is created and the "Salesperson" of the user's parent company should be proposed to the quotation. While if the user logins before adds products to the cart, the "Salesperson" of the user's parent company will be passed to the quotation. 

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/1SCSGmvV5FDKLPWen_aXESoIOCEdFpdrl/view

**Comment by yostashiro** [comment]
OPW: 817189

**Comment by yostashiro** [comment]
Feedback from Odoo on OPW817189:

> Concerning your request, I have transferred it to our product owner team who have informed me that this will be improved and taken into account for future versions of Odoo. The reason being, that it is not a 'blocking' issue.

For our request to provide a patch:

> They have informed me that providing patches has and will only be done for exceptionally urgent matters, whereas in this case, the issue is resolved by putting a salesperson on the contact form.
>
> Another workaround would be to create an automated action if ever you have the technical knowledge to do so. 

We accepted this answer.

**Comment by Yenthe666** [comment]
I guess we can close this, although the answer is not perfect. 😉
