### ISSUE TITLE
[11.0] ir.default : condition field is deprecated ?

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#23182]
Impacted versions:
11.0

The field `condition` don't appear on the views (view form and wizard from Set Default), but it still present in python code (fields definition and appear in differents functions), it is normal or not ?

https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_default.py#L21

**Comment by Yenthe666** [comment]
@mart-e perhaps this got lost in a migration? Should we reintroduce it on the view?

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/pull/41803
