### ISSUE TITLE
[11.0] Issue with filters in Equipment

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23204]
Impacted versions: 11.0

Steps to reproduce: Go to Maintenance --> Equipment --> Apply Filter 
(Assume Activity is created with Scheduled Date today)

![](https://image.prntscr.com/image/X_FmlWKyQS6wD666Qe_ZVg.png)

Current behavior:
When applying filter --> Upcoming Activities (7 days)
It shows One record Which is correct

![](https://image.prntscr.com/image/69LFYzlfTdy8Zf1TDi2XDg.png)

When applying filter -->Upcoming Activities (All)
It does not show any record

![](https://image.prntscr.com/image/X11h8Uj2TEO2jxm6D7kRaw.png)

Expected behavior: Should show one record in both filters

Video/Screenshot link (optional):

**Comment by fmdl** [comment]
Corrected here : https://github.com/odoo/odoo/pull/23211

**Comment by sswapnesh** [comment]
Resolved in 0166b3ddbc3e13a3697337565ec085076adf7ec4
