### ISSUE TITLE
[10.0] Incorrect filter/Information for Invoice in Dashboard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23207]
Impacted versions: 10.0 

Steps to reproduce:  Go to Sales Dashboard

Current behavior:

- It is written "Invoiced" in block and mouseover says it is 'To Invoice Report'

![](https://image.prntscr.com/image/JCz5Gc7cRLuSMAi8Gg_-PA.png)

- Click on Invoiced Block you will see total Invoiced amount which is different than Dashboard amount

![](https://image.prntscr.com/image/sc1rtdY4SOCimJnLvDTbaw.png)

Expected behavior: It should Show Invoiced amount for By Sales Person (Would be difficult to show only one Sales Person in Invoice Analysis).

![](https://image.prntscr.com/image/qDsyxb6GTti6iwj8wSeS8A.png)

Alternative solution will be showing list view with filtered records

![](https://image.prntscr.com/image/bj47r5mAQsKVpyjev118_w.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @sswapnesh,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
