### ISSUE TITLE
Odoo11e Inventory Valuation Report Creates Duplicate Stock Journal Entries When Minus Qty is adjusted!

### ISSUE THREAD

**Issue by armbakri** [odoo/odoo#23210]
Impacted versions:
Odoo V11
Steps to reproduce:
I am using this configuration
Cost Method : Fifo
Valuation : Real Time
Accounting : Anglo-Saxon
I have disaster bug for odoo v11 inventory valuation for example if i have Product - A Qty=10pcs, Cost = $12 (My Stock Value is $120 OK)
Now if i sale more then 10pcs (for mistake or from pos) let i say we sold 20 pcs
two journals will create
Stock Out Journal  Ref.WH/OUT/0001** : 
Debit  Acc : $240 is Stock Output Interim Acc (20pcs x $12) 
Credit Acc : $240 is Stock Value Acc 
Invoice Journal
Sales Acc Credit xxx, Acc Receivable Debit: xxx ;; Stock Output CR=$240, Cost of Good Sold DR=$240
---
Now Both my inventory acc in balance sheet and inventory valuation are -$120.0 (Negative - OK)
---
Current behavior:
 Now if i make inventory adjustment or purchase for that negative qty product
and i run inventory valuation report again
it will create another stock out journal entry with same reference the above first journal(WH/OUT/0001)**
----------
Expected behavior:
When i run inventory valuation report it should not create stock journal entries which already created when i sold the product.
because here the stock valuation acc will be credit in two times and that is not corrected !!!!
Video/Screenshot link (optional):**
https://youtu.be/lsX1HS-ywjY

**Comment by sle-odoo** [comment]
fixed by 001b36045888e35a03d63398ba395284ba36abba
