### ISSUE TITLE
require_once(/opt/lampp/lib/Ripcord-master/src/Ripcord.php): failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#23217]
i download Ripcord-master but i got these error

**Comment by Yenthe666** [comment]
Hi @spectra10008,

Please add more information / details.
What version? What OS? What steps do we need to do to reproduce?
Please follow the report template.

**Comment by xmo-odoo** [comment]
That's something to see with the maintainers of ripcord, not us.

**Comment by Yenthe666** [comment]
Oh wow, I totally filtered out half of that title in my head. Yep, not Odoo related.
