### ISSUE TITLE
[6.1] dependancy on python-dateutil < 2

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#2322]
dependency on python-dateutil is < 2

This is too restrictive.

Only python-dateutil 2.0 is not compatible with python 2.6

http://bazaar.launchpad.net/~dateutil/dateutil/trunk/view/head:/NEWS

Could this be backported on 6.1 ? On 8.0 it has already been changed.

**Comment by Yenthe666** [comment]
Hi @yvaucher,

Thank you for your report.
As Odoo 6.1 and 7.0 are no longer supported by Odoo (they only support three versions) this will not be fixed anymore in those versions. It has been fixed from V8 and upwards so you shouldn't have this problem in new versions anymore.

Regards,
Yenthe

**Comment by yvaucher** [comment]
That was old :smile:

**Comment by yvaucher** [comment]
By the way I hope Odoo will be able to port code base to python 3

**Comment by Yenthe666** [comment]
@yvaucher yep quite late 😉 
Odoo V11 will come with python 3 support.
