### ISSUE TITLE
Odoo 10 multiple workers - Repeat log

### ISSUE THREAD

**Issue by novobi1** [odoo/odoo#23227]
Impacted versions: 10.0

Steps to reproduce:
Set 
workers = 2 #( >0  , to enable multiple workers ) 

Current behavior:
- Repeated logs 
- Port 8072 is not listening 

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/14120607/36476738-4e9b2e24-1731-11e8-8285-419e882fd4b6.png)

![image](https://user-images.githubusercontent.com/14120607/36476705-35f8f4a0-1731-11e8-9dbd-146aa622dc4d.png)

![image](https://user-images.githubusercontent.com/14120607/36476714-3e018482-1731-11e8-9f19-ac6ab09a3961.png)

**Comment by jpaulin** [comment]
So, "repeat", as in: something appears multiple times, and shouldn't ?

By the way, just a check: this instance of Odoo mentioned up there, it's 
running from a clean slate, ie. no previous Odoo process has run on that particular server? 

I found if I do real-world change to /etc/odoo.conf (or in general, change configs)
and restart the server with **systemctl stop** + **systemctl start** -kind of thing, I might have to sometimes do a manual killing of some leftover processes. That is, _not all processes
always get killed_ with the "systemctl stop". This might be a by-design feature, letting 
worker threads get killed with grace, not sure about this.

I hunt for those renegade processes then with "ps ax" and grep for 'python.*odoo'
then kill them with a "kill" command. And then go on and issue the 'systemctl start odoo-server'

**Comment by akhdaniel** [comment]
i found the exact same problem...
any update on this?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html. Specifically, it seems the configuration you show is not taken into account (permissions?) and default memory limit makes to reload one time after another the worker due to memory exhausted.

Closing this issue now.
