### ISSUE TITLE
Attachments XSS.

### ISSUE THREAD

**Issue by miosoftnew** [odoo/odoo#23236]
Impacted versions: 11.0

Steps to reproduce:
1. Install "crm" and "document" modules.
2. Try to upload any file with name ```"><svg onload=alert(1)>``` as attachment for any opportunity.

Current behavior: alert appears.
Expected behavior: escaped html code in attachment title.

**Comment by mart-e** [comment]
Thank you to contact the security team if you believe have found a security issue.
Please read our [responsible disclosure page](https://www.odoo.com/page/responsible-disclosure).
