### ISSUE TITLE
Error inheriting an abstract model

### ISSUE THREAD

**Issue by Gio666** [odoo/odoo#23239]
Impacted versions: 10.0

Steps to reproduce: inherit an abstract model

Good day, I am developing a reference guide module for Ecuador, but when I try to inherit an abstract model (for example edocument) I get the following error: "TypeError: Model 'StockPicking' inherits from non-existing model 'stock.edocument'."

this is my code: 

class StockPicking

`class StockPicking(models.Model):

    _inherit = ['stock.picking', 'stock.edocument']

    type = fields.Selection([('delivery_note', 'Electronic Delivery Note'),
                             ('c_delivery_note', 'Customer Delivery Note')],
                            readonly=True, index=True, change_default=True,
                            default=lambda self: self._context.get('type', 'delivery_note'),
                            track_visibility='always')`

class Edocument

`class Edocument(models.AbstractModel):

    _name = 'stock.edocument'

    SriServiceObj = SriService()

    clave_acceso = fields.Char('Clave de Acceso', size=49, readonly=True)
    numero_autorizacion = fields.Char('Número de Autorización', size=37, readonly=True)
    estado_autorizacion = fields.Char('Estado de Autorización', size=64, readonly=True)
    fecha_autorizacion = fields.Datetime('Fecha Autorización', readonly=True)
    ambiente = fields.Char('Ambiente', size=64, readonly=True)
    autorizado_sri = fields.Boolean('¿Autorizado SRI?', readonly=True)
    security_code = fields.Char('Código de Seguridad', size=8, readonly=True)
    emission_code = fields.Char('Tipo de Emisión', size=1, readonly=True)
    sent = fields.Boolean(u'¿Enviado?')`

why this error?, How can I solve it?

**Comment by Jerther** [comment]
Once the module is installed, if you add the module itself to the dependencies in the manifest, the error goes away but that's not really a fix and you will most likely get a recursion error later.

I guess for now we have to declare the mixin (Edocument) in a separate module so we can add this other module to the dependencies of another module (with StockPicking) which would basically just be a bridge.

Don't quote me on this but I've found no module in Odoo that uses a mixin in the same module it is defined.

**Comment by Yenthe666** [comment]
Dear @Gio666,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
