### ISSUE TITLE
OdooV11E Studio

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23241]
Impacted versions: Odoov11E Studio Traceback when clicking on confirm button

Steps to reproduce:
	> Open Odoo studio > Open Any app >
	> Click on Views  > Form view > Drag one2many field
	> in popup directly click on 'Confirm' Button. 

Current behavior:
	> Throwing traceback
	
Expected behavior:
	> It should work smoothly.

Video/Screenshot link (optional):

Video > 
	https://youtu.be/v6uOMZdDDzQ

Screenshot >
	https://www.awesomescreenshot.com/image/3188514/16fda005da003bd94282979594ac6179

Thanks !

**Comment by Yenthe666** [comment]
@aab-odoo and @mge-odoo another Odoo studio issue.

**Comment by aab-odoo** [comment]
Fixed by https://github.com/odoo/enterprise/commit/5a2e383740e23aa23ac6722893c45bf50d6b6a77
