### ISSUE TITLE
 Odoov11E Studio : Group disappear automatically (limit visibility to groups)

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23243]
Impacted versions: Odoov11E Studio

Steps to reproduce:
	> Open Odoo studio > Open Any app >
	> Click on Views  > Form view > Select (click) on Any field
	> on left pane > select 'Limit Visibility to groups' 
	> add groups and it will disappear automatically in few seconds.

Current behavior:
	> Groups is disappearing automatically.
	
Expected behavior:
	> It should be stayed as it is.

Video/Screenshot link (optional):

Video > 
	https://www.youtube.com/watch?v=EKAiSJ4xFGg&feature=youtu.be
	
Many Thanks,
Dipak

**Comment by AyaYousef** [comment]
I'm expecting the same behaviour  In Odoo V11

**Comment by Elkasitu** [comment]
For enterprise support you'll probably have better luck by opening a support ticket

**Comment by Yenthe666** [comment]
Indeed. @mge-odoo or @aab-odoo could you guys have a look at this studio bug though?

**Comment by mge-odoo** [comment]
Hi @dipsshah42 

Thanks for reporting the bug.
It has been fixed in the rev. https://github.com/odoo/enterprise/commit/bafe85b9aea6b968dacc878a3e7f24e3aa0b1aaf

Regards,

Martin

**Comment by amrani1insaf** [comment]
Hello @mga-odoo  

This page can not be displayed, Please how could I fix this bug?

Best regards,

**Comment by Yenthe666** [comment]
@amrani1insaf you can't see it because you don't have access to the enterprise repository probably. If you update your enterprise source code it should be fixed.

Regards,
Yenthe

**Comment by amrani1insaf** [comment]
Hi @Yenthe666 

Thank you very much for the prompt reply.

Best regards,
Insaf

**Comment by Yenthe666** [comment]
You're welcome - best of luck.
