### ISSUE TITLE
[11.0] Sale: Re-install sale_management doesn't restore all menus

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23245]
Tested on [Runbot](http://305111-11-0-dbb713.runbot9.odoo.com/web#view_type=list&model=sale.order&menu_id=526&action=715)
Impacted versions: 11.0

Steps to reproduce: Uninstall sale_management --> Re-Install sale_management

Current behavior: Few Submenu are not there

![](https://image.prntscr.com/image/O-2DgaeITLajidAHamfHjg.png)

Expected behavior: All Submenu should be there.

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Whoops, byproduct of 985c224, working on a fix :innocent:
