### ISSUE TITLE
Deduplicate wizard - where to find it

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#23254]
Impacted versions:
11CE
Steps to reproduce:
Try to find menu or action to contacts deduplicate wizard
Current behavior:
We must go to contacts, then select some(or all), click to Actions -- > Merge Selected Contacts --> [Panic] --> click Skip these contacts --> and only there we see button Deduplicate the other contacts.

If I hadn't seen the source code, I would never guess that this functional in general exists and how to find it in interface.

Expected behavior:
There must be "Deduplicate Contacts"  menu item in Partners/Configuration (or CRM/Configuration) from the start.

**Comment by pedrobaeza** [comment]
The menu was removed some time ago. Use https://github.com/OCA/crm/tree/10.0/crm_deduplicate_acl for v10 or migrate it to v11.

**Comment by sergeiruzkiicode** [comment]
@pedrobaeza yes, I can make it manually without crm_deduplicate_acl + 10->11 migrations, but it is not so easy for user, to find it from the box - we have fuctionality, but don't see it clear. That's why I think, it make sense, to return menu item.

**Comment by pedrobaeza** [comment]
Odoo is not going to do that for a stable version.

**Comment by Yenthe666** [comment]
Indeed - this won't be changed or added in a stable version. Sorry.
