### ISSUE TITLE
[11.0] Sale order lines reset to previous values after onchange

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#23276]
Impacted versions:
11.0

Steps to reproduce:
1. Create empty database (tested without demo data, set language to English, Netherlands as country).
2. Install the sale_management app.
3. Create new quotation.
4. Assign new partner to quotation.
5. From inline editable listview add a new order line (created the product inline).
6. Save.
7. Click on the order line (NOT IN EDIT MODE). This opens the order line in a popup.
8. Close the popup.
9. Click edit again.
10. Now change the order line description.
11. Unfocus order line.
12. Order line description resets to previous value!

Current behavior:

Changes to order line fields ('name' e.g. description, 'price', etc) are reset.

Expected behavior:

Changes to order line fields are preserved.

Cause:

This issue almost drove me crazy, as it was very hard to find the underlying cause. And I'm still not certain how to correctly solve it.

- Inspect the /onchange request that happens.
- Inspect the /onchange request that happens without performing step 7 and 8 (be sure to F5 or reload form view).

You will notice a different json values. Tip:

- Format with https://jsonformatter.curiousconcept.com/
- Diff with https://www.diffchecker.com/

- The faulty request contains invoice_lines (which must have come from the popup)
- By running Odoo in debug mode, you will notice that the faulty request triggers a SELECT on the order lines table. Thus retrieving the stored values and resetting the changes.

This is as far as I have come.

**Comment by adaptivdesign** [comment]
@nhomar the issue is even worse. I just ran another set of tests.

The issue also occurs in this situation:

1. Install both sale_management and **stock**
2. Create new quotation
3. Assign new partner to quotation.
4. From inline editable listview add a new order line (created the product inline).
5. Save.
6. Click edit again.
7. Now change the order line description.
8. Unfocus order line.
9. Order line description resets to previous value!

In this scenario simply editing the order lines fails even without opening the order line popup :(

**Comment by adaptivdesign** [comment]
I have found the cause and solution for situation 2.

See https://github.com/odoo/odoo/blob/11.0/addons/sale_stock/models/sale_order.py

- At method _compute_invoice_status (line 113) an invalid @api.depends decorator is used.
- By depending on 'order_id.state' it seems the order_line field is reevaluated and thus it triggers a query and resets the records for order_line.

The solution is simple:

- Change @api.depends('order_id.state') to @api.depends('state')
- At line 121 change.. if line.order_id.state into if line.state 

I believe this issue is one of the reasons you have added the state field to sale.order.line

**Comment by nhomar** [comment]
@adaptivdesign 

If you propose a PR all will be faster.

**Comment by celm1990** [comment]
Hello,

Please see commit f51d24d613f2bf125e54f0f87fd00e3e68688d93, can be related.

**Comment by Yenthe666** [comment]
Hey guys,

I've asked two persons of Odoo to have a look at it as soon as possible (on the PR).

**Comment by sswapnesh** [comment]
I believe there are 2 or 3 more Issue related (May be duplicate) to this.

**Comment by sswapnesh** [comment]
Related to #23066, #22927 and #22797.

**Comment by adaptivdesign** [comment]
@sswapnesh  they all seem related to this issue yes. I believe this is a low level issue, my pull requests might have solved your issues already.

**Comment by adaptivdesign** [comment]
@Yenthe666 any news on this ? My pull requests fixes situation 2 as described in this issue but not situation 1. Any chance Odoo engineers found a solution to this?
