### ISSUE TITLE
[11.0] Two footer on Pressing Esc on Wizard's o2m field

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23271]
Impacted versions: 11.0

Steps to reproduce: Go to Wizard having Editable o2m tree view --> Add an Item --> Press Esc

![](https://image.prntscr.com/image/WxkOKSTRSCuP4tGW6LEPEg.png)

![](https://image.prntscr.com/image/29ZeNv_7QZmMUSOObUpyTw.png)

![](https://image.prntscr.com/image/zcNYeC9zROaeZMAC2zcmZA.png)

Current behavior: Two footers on Screen

Expected behavior: One footer

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks a lot for your report! I've seen this one before on Github.com somewhere but can't seem to find it right away. Last time I pinged @ged-odoo for that one too.

**Comment by sswapnesh** [comment]
Indeed, There is one. But it was not due to Pressing Esc

On Feb 23, 2018 1:25 AM, "Yenthe V.G" <notifications@github.com> wrote:

Hi @sswapnesh <https://github.com/sswapnesh>,

Thanks a lot for your report! I've seen this one before on Github.com
somewhere but can't seem to find it right away. Last time I pinged @ged-odoo
<https://github.com/ged-odoo> for that one too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/odoo/odoo/issues/23271#issuecomment-367801465>, or mute
the thread

**Comment by sswapnesh** [comment]
Related to #23045.

**Comment by Yenthe666** [comment]
Ah yes indeed! Thanks for the link.

**Comment by ged-odoo** [comment]
fixed by commit https://github.com/odoo/odoo/commit/132137939cc8460868a0e77ff78814a9d95e5a56

thank you for your bug report
