### ISSUE TITLE
[Odoo forum] Unable to answer new questions or to delete comments

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#23289]
Impacted versions: Odoo official forum (https://www.odoo.com/forum/help-1/)

Steps to reproduce:
- Try to post an answer or delete an answer. You'll get a 403:
![image](https://user-images.githubusercontent.com/6352350/36594518-ae4a94f4-189e-11e8-941c-7b772b93b884.png)

Current behavior: No way to answer/delete comments

Expected behavior: Works.

**Comment by Yenthe666** [comment]
@JKE-be, @mart-e your whole forum has broken down after your migration.

**Comment by blaggacao** [comment]
Confirmed for support tickets on my end

**Comment by JKE-be** [comment]
wip

**Comment by Yenthe666** [comment]
Other things:
- No more option to create a ticket from within the portal
- You can't find ticket numbers anymore in the whole portal.

**Comment by mart-e** [comment]
@Yenthe666 we are looking into it but could you please not use the gihub issues for odoo.com problems (which is _not_ a standard Odoo), there is different channels for that (like support tickets).

**Comment by Yenthe666** [comment]
Urgh.

**Comment by blaggacao** [comment]
Support tickets are down as well :/ skype?

**Comment by sswapnesh** [comment]
I have also one more Issue regarding odoo. But I can't share here. What Can I do? 🤔

**Comment by Yenthe666** [comment]
@sswapnesh apparently odoo.com/help (if it works for you)

**Comment by sswapnesh** [comment]
I can access odoo.com/help But` 'Odoo Community users don't get access to the support.'`

**Comment by Yenthe666** [comment]
Yeah that is the second problem for most end users. Basically what my urgh comment was for.

**Comment by blaggacao** [comment]
Just to let you know, I can still not post onto an already opened issue (comment): 403 - Forbidden...

**Comment by NiyasRaphy** [comment]
As you team are working to fix these issues, it will be better of you can add the feature that , who up-voted a answer and who down-voted a post such details have to known.

**Comment by Yenthe666** [comment]
@JKE-be in the meanwhile the validation queue has broken down too now:
![image](https://user-images.githubusercontent.com/6352350/36777092-6e82429a-1c68-11e8-8289-92c620f6c54b.png)

**Comment by NiyasRaphy** [comment]
Can answer and comment for some questions, but not for all

**Comment by NiyasRaphy** [comment]
Closing the question and reopening the question make the question validated

![validate_qstn](https://user-images.githubusercontent.com/27989791/36777790-cb8f3498-1c90-11e8-8771-1bcb30cc2646.png)

**Comment by Nikhilkrishnan0101** [comment]
But still issue is there, we can't give a answer. its through a 403 – Forbidden!

**Comment by aniketht** [comment]
I buy odoosh and setup with github odoo worked but i am not able to install simple custom addon(app)
![screen shot 2018-09-16 at 8 11 54 pm](https://user-images.githubusercontent.com/35223414/45609260-c5a99c80-ba74-11e8-9bad-1169fc52a8d1.png)

**Comment by aniketht** [comment]
I am using different commit of odoo version 11 and odoo.sh git log commit id is different. how to change odoosh commit with same as my commit id
