### ISSUE TITLE
Odoov11E Studio : Traceback while saving 'Favorites in searchview.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23293]
Impacted versions: Odoov11E Studio

Steps to reproduce:

> Open Odoo studio > Open Any app >
> Click on Views > Form view > Select (click) on Any field
> on left pane > select Search more in 'Limit Visibility to groups' field ,
> In opened popup click on 'Favorites' > save current search > Enter name > Save.

Current behavior:
> Traceback while saving Favorites.

Expected behavior:
> It should to save Favorites as we want.

Video/Screenshot link (optional):

> https://youtu.be/gGiNUr1WUus

Thanks,
Dipak

**Comment by Yenthe666** [comment]
@aab-odoo and @mge-odoo another studio bug.
