### ISSUE TITLE
OdooV11E Studio : Coonditional filteres are added outside of the page / Missing responsiveness

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23292]
Impacted versions: Odoov11E Studio

Steps to reproduce:

> Open Odoo studio > Open Any app >
> Click on Views > Form view > Select (click) on Any field
> on left pane > Click on 'Conditional link' under Properties Tab,
> add few filteres.

Current behavior:
> Filtered are going to add even out of the page,no scrolling or any resonsiveness.

Expected behavior:
> It should be add filteres in page only and provide scrolling / responsiveness to interface.

Video/Screenshot link (optional):

https://youtu.be/1y76Ip_9_uY

Thanks,
Dipal

**Comment by Yenthe666** [comment]
@aab-odoo and @mge-odoo another studio bug.
