### ISSUE TITLE
project upgrade does nothing

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23307]
![image](https://user-images.githubusercontent.com/17784575/36636687-66b36a70-19cb-11e8-84ef-0559e29b1960.png)

i noticed that there is no way to upgrade app so i wend on odoo runbot and try just, clicking upgrade does nothing even the local folder is a fresh pull from github 

i am missing something obvious ?

**Comment by sswapnesh** [comment]
Hello @icf20 
I can upgrade Project module on Runbot [http://305741-11-0-a4e05f.runbot9.odoo.com](http://305741-11-0-a4e05f.runbot9.odoo.com/web?#id=113&view_type=form&model=ir.module.module&menu_id=45&action=31) and local server too.

PS: I cannot test on Runbot link you gave as It is no more Active.
