### ISSUE TITLE
Odoo 11 stop working after adding a module "voip_sip_webrtc"

### ISSUE THREAD

**Issue by sandeepbrst** [odoo/odoo#23301]
Hello,

I just installed Odoo 11 on Ubuntu and then add a custom module  which was downloaded from here "https://apps.odoo.com/apps/modules/11.0/voip_sip_webrtc/" but after installing that module odoo admin stop working and showing this error (http://prntscr.com/ij1h0g) and now there is no option to uninstall this module. please help on this that how can i remove this module and what is the issue..

Thanks in Advance...!

**Comment by Elkasitu** [comment]
Contact the author of the custom module, this is not a bug within Odoo CE

**Comment by sandeepbrst** [comment]
Hello,

Thanks for repond..
But i want to uninstall this module as am not sure that it will work for me better and now on every page i'm getting this issue (http://prntscr.com/ij1h0g) so is there any way to uninstall it as my application is not working due to this...

Thanks

**Comment by Yenthe666** [comment]
@sandeepbrst,

Remove the module from the modules list (the folder) and then update your Odoo with the -u command.

**Comment by sandeepbrst** [comment]
But how can i remove modules as now no options showing and please let me know the command which you are taslking about

thanks

**Comment by RayKisor** [comment]
You may remove the module from the /opt/odoo/odoo12/addons director (assuming you are using odoo12.
For example if you want to remove module hr_reminder then just use  rm -r hr_reminder.  Then
Update all the modules .using command line:
sudo service odoo stop
login as odoo system user
cd /odoo12
./odoo-bin -u all -c /etc/your-odoo.conf
exit
sudo service odoo start
Thanks
