### ISSUE TITLE
el modulo de asistencia no muestra icino de check in/out

### ISSUE THREAD

**Issue by Joel1971** [odoo/odoo#23311]
Impacted versions:
odoo 11
Steps to reproduce:
he instalado el modulo de asistencia y solo con el usuario administrador me sale el check in/out
![imagen](https://user-images.githubusercontent.com/17445655/36647709-62fed502-1a4f-11e8-8658-e46758bdb435.png)

Current behavior:
con nungun usuario puedo hacer que salga dicho icono, aun dando rol de empleado RRHH o responsable.

Expected behavior:

Video/Screenshot link (optional):

**Comment by JayVora-SerpentCS** [comment]
Report in English please @Joel1971

**Comment by pedrobaeza** [comment]
Closing this waiting for a new issue in English if the problem is still present.
