### ISSUE TITLE
[master] Extending `shop` route method from website_sale: possible keyword argument error

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#23310]
Impacted versions:
9, 10, 11
Steps to reproduce:
Extend method  `shop` from `website_sale/controllers/main.py` in a way that you would pass `ppg` keyword argument both as independent argument `ppg` and as dictionary key in `post` kwargs.

Current behavior:
You would get TypeError: shop() got multiple values for keyword argument 'ppg'
Expected behavior:
If `ppg` is used inside `post` kwargs, it should not be used as independent keyword argument or vise versa. This can cause issues when you want to extend such method.

I mean look at this part of the method:

```python
    def shop(self, page=0, category=None, search='', ppg=False, **post):
        if ppg:
            try:
                ppg = int(ppg)
            except ValueError:
                ppg = PPG
            post["ppg"] = ppg
        else:
            ppg = PPG
        ...
        ...
```
We have `ppg` as visible optional argument and then if it is passed, it is also put into `post`. Now if we would call super when extending this method and pass both `ppg` as optional argument and inside `post`, we would get that error I mentioned.
Is this really intended that way? If so, at least comment why it is done this way? To me it looks very prone to error.

P.S. It looks this was added since version 9, because 8 version did not have `ppg` optional argument.

**Comment by JKE-be** [comment]
> "and pass both ppg as optional argument and inside post"...


In which case, would you like to pass 2 times ppg (in *args and in **kwargs)?

**Comment by oerp-odoo** [comment]
@JKE-be thats the opposite of what I'd like. Thats the way this method is now structured. What I meant is if you mimic implementation from super and pass the same way it is structured now, it would crash.

**Comment by JKE-be** [comment]
Could you show us your code?

**Comment by JKE-be** [comment]
Imho, the error is in your override.
The "post["ppg"] = ppg" should not be there. It is an error of copy/past from the original controller...

There is none reason to do it ...

And the PPG from qcontext is probably wrong, it should be ppg instead of PPG

**Comment by oerp-odoo** [comment]
@JKE-be I know its in my override. Though what I'm questioning here is why we technically have possible duplicates of arguments?

Maybe you are right that is not needed, but what if I need to reuse `ppg` in my override the same way it would be used in original? 

What I think would be better and much less confusing, is to just use always use `ppg` directly from `post` without having this separate `ppg` argument. I don't get it why we need to have it as separate argument and then use it to update `post` which is also part of arguments (even though problem arises if you override in some similar fashion as original one is written).

Why not use just this?

```python
    @http.route()
    def shop(self, page=0, category=None, search='', **post):
        ppg = post.get('ppg')
        if ppg:
            try:
                ppg = int(ppg)
            except ValueError:
                ppg = PPG
            # If we need to update it by converting to int.
            post["ppg"] = ppg
        else:
            ppg = PPG
        # the rest of logic
        ...
        ...
```

Other parts I don't think are important, as I said those need to be cleaned up, cause its community module :)
