### ISSUE TITLE
Odoo11E Studio : Menu name should be required.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23323]
Impacted versions:
 > Odoov11E Studio.

Steps to reproduce:
    > Open any studio app > Click on 'Edit menu' > Click on 'Confirm' so it will create blank menun.
Current behavior:
     > Its creating a menu with no name.
Expected behavior:
     > menu name should be mandatory or warning should be there..
Video/Screenshot link (optional):
      > https://youtu.be/DkUBTzqrLeg

Thanks,
Dipak

**Comment by Yenthe666** [comment]
@aab-odoo studio related fix/improvement

**Comment by mge-odoo** [comment]
Hi @dipsshah42 

I don't see the issue here. It doesn't cause any traceback and it should be the user's choice if she wants an empty menu, don't you think?

Thanks for reporting anyway.

Martin
