### ISSUE TITLE
Cannot remove/refund a vendor bill with a negative amount  [CE 10]

### ISSUE THREAD

**Issue by ki1022** [odoo/odoo#23337]
A client has created a negative vendor bill to indicate that they have a credit due with a vendor.  After the bill is validated, the bill is showing a POSITIVE amount due but I cannot even pay the amount, negative or positive.  The accounting journals shows the payments but they are not reconciled with the bill.  The bill is just stuck in open status.  If I create a refund for the bill, it still shows a positive amount due which I still cannot apply any payment to.  When viewing bill or refund for the vendor I do see the "You have outstanding debits for this supplier. You can allocate them to mark this bill as paid" message.  I do see the "credits" lists at the bottom near the total but when I click to add to the bill nothing happens.

I did see this previous discussion about use Bill Refund instead:

https://github.com/odoo/odoo/issues/10778

...which is good for next time, but for now how do I remove this negative bill and make adjustments to my vendor account to get back to zero balance?  This is Odoo CE 10.  Thank you.

**Comment by qdp-odoo** [comment]
you should deal with that at the journal entry level, I think. 

So open the wrong journal entry and,
1st possibility: un-post it (you need to have the account_cancel module installed, then thick the option "allow cancelling entries" in the vendor bill's journal), then modify the journal entry manually to inverse the debit/credit columns
2nd possibility: reverse the journal entry (there's a button to do that) then recreate a new refund and validate it.

for your information, this have been improved in v11 and we now raise an error if we detect that a negative invoice/bill is being validated.

I hope that'll help.

best regards
