### ISSUE TITLE
[IMP] company currency on accounts

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#23335]
Impacted versions:
all (I guess)

Configure an account, a currency field will be shown, which easily will be misinterpreted as the account currency, wile the semantic meaning is "different from company currency".
As a matter of clarification and for improved code access it would be desirable to relate and store the company currency onto the account as the accounts primary read only currency.
Would make things a lot clearer.

Also would help in the case of an implementation of accounting companies where the account company can be a super-company, where the currency field then would not be readable by everyone... (but that's just a nice side effect)

**Comment by blaggacao** [comment]
Customer Feedback Tracking: 1818842

**Comment by lap-odoo** [comment]
@blaggacao Hi, this behavior has been improved in Version 11, now it's not an issue anymore to set on an account the currency of the company.

**Comment by blaggacao** [comment]
@lap-odoo Thank you, I heard the feedback form the ticket. I have a use case where accessing the company of an account does produce access errors. THis use case is not yet considered by Odoo SA but in our country is a "conditio sine qua non". What I'm trying to do is to help you strategically improve so that when Odoo itself will be concerned with that use case, you will be able to adapt more easily, while I will be able to maintain my fork more cleanly).

If that's something to consider in the face of an implementation partner, it will be very much appreciated. If not so, I can live with that. :wink:

**Comment by lap-odoo** [comment]
@blaggacao : Can you please explain the steps to follow to face this access errors ? Thanks

**Comment by blaggacao** [comment]
_Disclaimer:_ It's not officially supported. Custom code.
@lap-odoo What I intent to do is exposed here:https://github.com/odoo/odoo/pull/19839
Imaging a company structure like follows:
- Holding  (COA holder)
-- Subsidiary Brussels
-- Subsidiary Grand-Rosiere
-- Subsidiary Charleroi

Now there are many accesses in the code to `account_id.company_id.currency_id` (effectively accessing the company's currency through the account). Noe you can easily imagine that a user without privileges who is logged in into Subsidiary Charleroi will get blocked, at the `currency_id` as he has no access to `company_id`'s fields and values (other then `id`).
Effectively I do prepend every instance of that with sudo in my code, but I guess this is bad practice and it would be cleaner to have the company currency proxied on the account.
Maybe Odoo will never implement a subsidiary hirarchy the way I proposed, however, i think the concept of company is semantically so close to the concept of subsidiaries (due to ACL isolation, self-counterparty distiction in transactions, and may other things) that I predict the strict COA binding will be released at some point in the future. For me that's just the natural next step towards corporate implementations.
