### ISSUE TITLE
[8.0RC1,New API] Many2one field, context is not passed to fields_view_get

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#2333]
In order to specify which view to be used in many2one field, we can specify _view_ref in context.
For example, <field name="invoice_id" context="{'form_view_ref':'module.view_id'}"/>
Currently, only the built-in information(eg, active_model,active_id,etc) in the context is available in fields_view_get in new api.

On the other hand, the context specified in field definition will be merged with the context in view in previous version. Now the context in field definition is ignored.
invoice_id=fields.Many2one('account.invoice','Invoice',context={'form_view_ref','module.xml_view_id'})

Impacted versions:

8.0rc1, Sep 10

Steps to reproduce:

Specify the form view id in context of many2one field definition / view
Click to that many2one field to open the form.

Current behavior:

View specified is ignored.

Expected behavior:
View specified is loaded

**Comment by tadeusz-karpinski-openglobe** [comment]
still not work ;_;

**Comment by auyeung112002** [comment]
@tadeusz-karpinski-openglobe 
How did you reproduce this problem? In my cases, some of the fields work while some other fields do not work.

**Comment by auyeung112002** [comment]
Found out the reason why the xxx_view_ref value in context has no effect sometimes. In my case, it is because there is another view_id defined in model.get_formview_id. See get_formview_id method in account_invoice.py for example.
