### ISSUE TITLE
create new user issue : Cannot read property 'views' of undefined

### ISSUE THREAD

**Issue by Abdelrahman-Mahareek** [odoo/odoo#23340]
Impacted versions: 11.0
OS Version: windows 10- 64 

Steps to reproduce: setting -> users -> click create

Current behavior: Uncaught TypeError: Cannot read property 'views' of undefined

Expected behavior: create user easily 

Video/Screenshot link (optional):
![odoo](https://user-images.githubusercontent.com/10356905/36714041-2e497100-1b99-11e8-9a40-eb4851da846e.PNG)

**Comment by Elkasitu** [comment]
Hi, this has been fixed in commit 034c075, since you seem to be using Windows it is possible that the fix (pushed yesterday) hasn't made its way into the windows build yet, you should probably have it working by tomorrow.

**Comment by Abdelrahman-Mahareek** [comment]
please clarify how could i update odoo

**Comment by Elkasitu** [comment]
@d-fence

**Comment by d-fence** [comment]
Did you use the Odoo windows installer or did you install from sources ?

**Comment by Yenthe666** [comment]
@d-fence and @mart-e on a sidenote: it would be nice if the documentations would have a part explaining how to update on any version / installation method. That would be a great addition.

**Comment by Afzaalkh** [comment]
I am still facing this issue ?
