### ISSUE TITLE
Creating a journal with default next number value raises error.

### ISSUE THREAD

**Issue by stundzia** [odoo/odoo#23352]
Impacted versions: 11.0

Steps to reproduce: Create a journal with a user that does not have Administration/Settings access rights. Enter any values in the required fields. Issue is with default value on Next Number field (which is 1). Clearing the field or entering 0 works around the issue.

Current behavior: An access error is raised for the model ir.sequence.date_range. This is due to the inverse method (_inverse_seq_number_next) on the Next Number field triggering a write on the related ir.sequence.date_range record.

Expected behavior: at the very least the default value of Next Number should not trigger an access error for Accounting Advisors that are not Admins.

Video/Screenshot link (optional):
[create_journal_issue.ogv.zip](https://github.com/odoo/odoo/files/1763080/create_journal_issue.ogv.zip)

**Comment by smetl** [comment]
Issue fixed on 11.0 at revision: https://github.com/odoo/odoo/commit/c08f56379553a4882df96c6511c29ffbcf15f191

Thank you!
