### ISSUE TITLE
Send an invoice or a sale order by mail

### ISSUE THREAD

**Issue by JoCloud007** [odoo/odoo#23357]
Impacted versions:

10.0 (also in 8.0 : https://github.com/odoo/odoo/issues/9150#event-1358211017)

Steps to reproduce:
  1. Go to an open invoice
  2. Push the button Send by Email
  3. The wizard opened, push the button Send
![send_email](https://user-images.githubusercontent.com/13097291/36737619-c759f81e-1bdb-11e8-84b0-c3e7193164d6.png)

Current behavior:

2 messages are created (Technical > Email > Messages) : 
  1. The notification message. No problem with that
  2. the message email with the following Type subtype : Comments / Discussions. 
![message_email](https://user-images.githubusercontent.com/13097291/36737631-cf23a612-1bdb-11e8-9d60-cdfddd114695.png)
![email_type](https://user-images.githubusercontent.com/13097291/36737649-da3e4214-1bdb-11e8-8214-4591b9255e7b.png)

The mail is never send (the mail Queue Manager runs every minute)

Expected behavior:
The email is send and the message for the email is generated with the type email

**Comment by Yenthe666** [comment]
Dear @JoCloud007,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
