### ISSUE TITLE
Not installed in comunity version

### ISSUE THREAD

**Issue by sandeepbrst** [odoo/odoo#23366]
I want to install this module in my odoo 11 comunity verison installed on ubuntu and running on ip is it possible to install over there ??

**Comment by Yenthe666** [comment]
Hi @sandeepbrst,

The Github tracker is only for bugs in the official code.
Your question is quite vague too honestly. I believe you're asking if it is possible to install an app when it runs on an IP and from the browser?
Yes you can install a module from the frontend, both when running from an IP and a web address.

**Comment by sandeepbrst** [comment]
i just want to confirm that I'm Talking about this App which i want to install in my Odoo 11 community version. is possible to install or it is only for enterprise edition

https://apps.odoo.com/apps/modules/11.0/website_calendar/

**Comment by Yenthe666** [comment]
It is an enterprise app.
