### ISSUE TITLE
[v10] Required field in one2many relationship

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#23372]
Impacted versions: 10, 10E

Steps to reproduce: On invoice make tax as a required field. Now try to add line and do not add anything in tax and click on save. you will loss line. it should rais warning that tax is missing instead of removing that line.

In Enterprise version m2m_tags required field shown as normal. 

another reported bug #9308 has also happened in v10E.  To reproduce that just make tax required and try to edit any existing invoice you will face that.

Current behavior: Removes line.

Expected behavior: It should raise a warning. same as other required fields.

Video/Screenshot link (optional):

![invoice odoo](https://user-images.githubusercontent.com/7599790/36784059-1866686e-1ca4-11e8-827a-47a3510cc86a.png)

**Comment by Yenthe666** [comment]
Dear @tpa-odoo,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
