### ISSUE TITLE
Move availability info empty when having stock with sub-locations

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#23383]
Impacted versions: v10, v11

If you have sub-locations under stock and the main stock has usage='view', then the availability info on stock move is not computed

Steps to reproduce: Make the stock location a view and have locations under stock. Have a product A with available stock. Make a picking from stock to customer and reserve the available product A. Odoo will search in stock sub-locations to find an available quant and reserve it. Open the move, the reservation info is not displayed.

In stock/models/stock_move.py, void_moves should consider locations with usage 'internal' and 'view'
```
@api.multi
def _compute_string_qty_information(self):
  precision = self.env['decimal.precision'].precision_get('Product Unit of Measure')
  void_moves = self.filtered(lambda move: move.state in ('draft', 'done', 'cancel') or move.location_id.usage != 'internal')
```

**Comment by sle-odoo** [comment]
Hi,
Afaik the field isn't displayed in 11 and removed in master so i think we can close this one as 10 isn't supported anymore.

Regards
