### ISSUE TITLE
l10n_nl: ICP report improvements for master

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#23394]
This is an extension of the topic at https://github.com/odoo/odoo/issues/18572

As discussed with @lap-odoo we will be splitting up different issues if they have no relevance in order to keep an overview of all the things there have to be done for the upcoming V12 accounting.

It looks like the current ICP report in Odoo is having some issues and it could be improved too.
- The amounts on the ICP report can be rounded and shown with nothing behind the decimal precision. If it is for example 49.49 it should be rounded down and become 49. When it is 49.98 it should become 50.
- When a customer has no amount in the product or in the services column the column should be empty (not even containing 0) as there is no booking for that side on that customer.
- On the official report the country code is shown before the VAT number, not the other way around.
- The official label is "Country code", not "Code".
- The country code should not be added in the VAT number. At this moment it shows something like `BE0477472701` while it should be `0477472701`, without the country code.
- When the balance of the debit and credit sides are both identical (which means balance is zero) then the row should not be shown in the ICP report.
- Ideally the VAT number is formatted in groups of 4, so that `0477472701` becomes `0477 4727 01`, but that is just a neatpick.

After doing all these changes an ICP report should look much like this example:
![image](https://user-images.githubusercontent.com/6352350/36799504-a17a533c-1cad-11e8-8bd3-2aa0dd109da9.png)

**Comment by Yenthe666** [comment]
@lap-odoo this is as we discussed. On a sidenote: I believe that some of these changes/fixes could already be done in the stable versions too. Could you let me know how you would like to continue? We're more than happy to contribute or test in order to help.

**Comment by ploegvde** [comment]
Looking good. This is indeed a improvement. You have to imagine that the VAT number and the amount needs to be entered manually in a webform on the Dutch tax authorities. It is a terrible job and now fields are in exactly same order and better readable. Also if balance is zero you don't have to report, so now the are suppressed from the report.

NOTE: If you have more then 100 companies (Tax numbers) then it is not allowed anymore to report manually on the webform. It is required to use a software tool. So i will raise a new issue for that, so that Odoo can also be used by larger companies. This new issue is #23404

**Comment by Yenthe666** [comment]
@lap-odoo could you please have a look and give us feedback on this one?

**Comment by lap-odoo** [comment]
@Yenthe666 Hi Yenthe, I'm transferring the followup of the accounting app to a new colleague : @avw-odoo . I'll try to update him on this task as soon as possible and then he should be able to give you some feedback about it

**Comment by Yenthe666** [comment]
Hi @lap-odoo,

Thanks for the feedback! Does this mean you'll no longer be on Github/accounting here? Where are you going? 💔 
Welcome to the club @avw-odoo - best of luck!

**Comment by Yenthe666** [comment]
I'm sure of that! Will you still be active on Github but for logistics then? So I can ping you regarding those issues? ;)

**Comment by lap-odoo** [comment]
@Yenthe666 : Yes you can :)

**Comment by Yenthe666** [comment]
@avw-odoo (cc @lap-odoo) can we please ask for an update here? We would really want to have this in V12.

**Comment by avw-odoo** [comment]
Well noted in our internal tasks, I keep you posted as fast as i can.

Have a good day.

**Comment by Yenthe666** [comment]
Okay, thanks a lot @avw-odoo! Have a good day too.

**Comment by Yenthe666** [comment]
@avw-odoo can I ask you for a status update please?

**Comment by Yenthe666** [comment]
@avw-odoo is there any progress in this? We'd love it in V12.

**Comment by Yenthe666** [comment]
@avw-odoo or @lap-odoo where are we with this? Odoo 12 is just around the corner and we'd love to have this available for our Dutch customers.

**Comment by Yenthe666** [comment]
It is a pity we missed this one after pinging for months. It would still be nice to get it going for V13 then..

**Comment by oco-odoo** [comment]
@Yenthe666 I'm working on it, should be okay for 12.1 ;) 

Just a small additional question about rounding: how should, say 2.5 be rounded? 2 or 3?

**Comment by Yenthe666** [comment]
@oco-odoo woooh, nice! You can round up, so 2.5 will become 3.

**Comment by oco-odoo** [comment]
Alright, thanks! ;)

**Comment by ploegvde** [comment]
@oco-odoo If changes are not that big, maybe we can make customers happy for V12, so that migration to V12 gives them the benefit. Issue is reported 9 months ago ;(

**Comment by oco-odoo** [comment]
@ploegvde It's true it's a pity, but this is unfortunately something we cannot do. We have to be strict about this, otherwize we will keep on making exceptions and merging new stuff in stable releases, which could in the end make them way less stable.

**Comment by ploegvde** [comment]
@oco-odoo What do you think, will it get merged in V13, or are we top late ;)

**Comment by oco-odoo** [comment]
@ploegvde Sorry for the late answer. It will be there in v13, this is 100% sure ;)

**Comment by Yenthe666** [comment]
@oco-odoo is there any timetable or branch for us to test yet?

**Comment by oco-odoo** [comment]
@Yenthe666 Sorry, I forgot to notice you: it has been merged, so you can test it on master branch on runbot. It will also be inluded in upcoming saas-12.2 ;)

**Comment by Yenthe666** [comment]
Hi @oco-odoo - that is great news! I'll ask @ploegvde to check it out and test. I guess we can close this issue then. Thanks!

**Comment by Yenthe666** [comment]
@oco-odoo there is actually a breaking issue not allowing you to install the module.
I've made a PR (fix) at https://github.com/odoo/enterprise/pull/3685 - could you get that in?
