### ISSUE TITLE
[11.0] Could not add Product with variant to Comparison List.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23397]
Impacted versions: 11.0

Steps to reproduce: Website --> Shop --> Enable List view Of Variant and Comparison List--> Open Product having Variants --> Compare

![](https://image.prntscr.com/image/Li53qF5EQWmHFx5aVcQSBw.png)

![](https://image.prntscr.com/image/806IjIS1R6WF1EP-td7mVw.png)
Current behavior: Product is not added to Comparison List and Trackback in Console.

```
Uncaught TypeError: Cannot read property 'render' of undefined
    at web.assets_frontend.js:1885
    at Function._.each._.forEach (web.assets_common.js:12)
    at Class.update_content (web.assets_frontend.js:1885)
    at Object.<anonymous> (web.assets_frontend.js:1883)
    at Object.<anonymous> (web.assets_common.js:802)
    at fire (web.assets_common.js:796)
    at Object.fireWith [as resolveWith] (web.assets_common.js:801)
    at Object.<anonymous> (web.assets_common.js:802)
    at fire (web.assets_common.js:796)
    at Object.fireWith [as resolveWith] (web.assets_common.js:801)

```
Expected behavior: It should add Product to Comparison List

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Adding more,
Enable Product Attribute's Filters

![](https://image.prntscr.com/image/LaCwFkdZRtuBW3ecSDAmaQ.png)

**Comment by JKE-be** [comment]
This last behavior is the expected one about the filter.
Wishlist add the first variant of the product template that you see.
While the filter show all products where a least one variant match your filter.

It could be improved, and use the first variant that match the current filter... but it is a nice to have ... PR is welcome

About the previous bug, I try to take care this week :) sorry for delay

**Comment by rdeodoo** [comment]
Initial bug was fixed (I checked again to be sure)
Then the PR was reopened for extended bug on non existing combinaison but the button is not clickable anymore in that case since https://github.com/odoo/odoo/commit/6a0274b300a25859d8c4d924dd9f032d5a0a39c9
Everything is now fixed for this PR?

**Comment by sswapnesh** [comment]
@rdeodoo  Works Well. (y)
