### ISSUE TITLE
[11.0] Could not add Product with Variant to Wishlist

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23395]
Impacted versions: 11.0 (not tested on 10.0 )

Steps to reproduce: Website -->  Shop --> Enable List view Of Variant --> Select Variant --> Add to Wishlist 
(or add any Product which have variants)

![](https://image.prntscr.com/image/XcGLNdf9Q-K7GRMiskeI1A.png)

Current behavior: Trackback in Console

`Server application error {"message":"Odoo Server Error","code":200,"data":{"message":"The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: product_id - product.id]\nNone","arguments":["The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: product_id - product.id]",null],"name":"odoo.exceptions.ValidationError","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 933, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/addons/website_sale_wishlist/controllers/main.py\", line 29, in add_to_wishlist\n    session\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/addons/website_sale_wishlist/models/product_wishlist.py\", line 57, in _add_to_wishlist\n    'website_id': website_id,\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/models.py\", line 3294, in create\n    record = self.browse(self._create(old_vals))\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/models.py\", line 3387, in _create\n    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/sql_db.py\", line 155, in wrapper\n    return f(self, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/sql_db.py\", line 232, in execute\n    res = self._obj.execute(query, params)\npsycopg2.IntegrityError: null value in column \"product_id\" violates not-null constraint\nDETAIL:  Failing row contains (11, 3, null, null, 1, 0.0, 1, 2018-02-28 16:36:26.761736, t, 1, 1, 2018-02-28 16:36:26.761736).\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 647, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 689, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/extra/runbot/static/build/307124-11-0-971ed8/odoo/service/model.py\", line 139, in wrapper\n    raise ValidationError(msg)\nodoo.exceptions.ValidationError: ('The operation cannot be completed, probably due to the following:\\n- deletion: you may be trying to delete a record while other records still reference it\\n- creation/update: a mandatory field is not correctly set\\n\\n[object with reference: product_id - product.id]', None)\n","exception_type":"validation_error"}}
`

Expected behavior: Product should be added to Wishlist

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sswapnesh now you're just being gready! Nah, just kidding. I guess you submitted to fast. I'll keep it open for now 😉

**Comment by sswapnesh** [comment]
Accidentally Submitted without adding detail.

**Comment by Yenthe666** [comment]
@sswapnesh just tested and this is indeed a bug.
CC @JKE-be

**Comment by sswapnesh** [comment]
Note: It works well on the Main page.
![](https://image.prntscr.com/image/BC1b9ZSBRz_bIQxyj2TVog.png)

**Comment by JKE-be** [comment]
hello

should be fixed by https://github.com/odoo-dev/odoo/commit/8a90de89e05298e8fdb3eb8a29f023b16ecd6958 from PR #23397

**Comment by sswapnesh** [comment]
PR is not proposed yet for that Issue.

**Comment by sswapnesh** [comment]
@JKE-be  Not Sure If I should add this here or Create new Issue.

Click two times on Same Button
![](https://image.prntscr.com/image/AUtfHwV0R2a6CZhJAJqqSw.png)


![](https://image.prntscr.com/image/2zMtytrWT4ugBEZkgEt8FA.png)


![](https://image.prntscr.com/image/w-aTGS0NQOepowNKNgEk3g.png)

**Comment by rdeodoo** [comment]
Initial issue was fixed and closed.
Reopened for extendeg bug on non existing combination and fixed with https://github.com/odoo/odoo/commit/6a0274b300a25859d8c4d924dd9f032d5a0a39c9
I double checked on runbot and these fixes are still working.
Let's close this one.

**Comment by sswapnesh** [comment]
@rdeodoo 
I am able to Reproduce this (regarding adding same items multiple times on Wishlist) on latest Runbot http://391126-11-0-bb939f.runbot13.odoo.com/shop/wishlist

![](https://image.prntscr.com/image/CCSPQezFRr_DmE6486wEtQ.png)

**Comment by rdeodoo** [comment]
@sswapnesh Hi, yes indeed. Initial bug from this PR and then extended bug where fixed.
The double click is not related to this one, please open a new PR if needed for it as we prefer to keep PR as much clean as possible. (Note that it was fixed in 12 as mentioned in another PR see my last message)

**Comment by sswapnesh** [comment]
@rdeodoo  

> (Note that it was fixed in 12 as mentioned in another PR see my last message)

Yes, I have reported that in https://github.com/odoo/odoo/issues/27489, I didnt mentioned about v11 as It was mentioned here.
Thanks

**Comment by JKE-be** [comment]
No, please don't open new ISSUE/PR for small UI bug !

An issue in stable version is a code that generate traceback or wrong behaviour.

In most of your last cases, it is simply bad user experience or bad user uses.
Ok, user can double click and have 2 time the product in their cart, it is not a drama and the user can fastly remove one if it was not the expected behavior.

So yes we could improve it in new version, maybe... 
But please stop to open useless issue about double click in UI
