### ISSUE TITLE
stock.quant cost is not alligned to the standard price

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#23408]
Impacted versions: 10

Steps to reproduce:
create some goods receipts for a product evaluated at standard price
change the standard price
Current behavior:
no change in field cost in model stock.quant
hence stock inventory and inventory accounting are not aligned
Expected behavior:
updating of cost field as new standard price

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
You should not care about the stored cost of the quant. If the product is in standard price, the accounting entry will be created with the standard price.

Regards

**Comment by ccandito** [comment]
Dear Simon,
so I'd suggest to remove the cost field in stock.quant model because it is misleading.
Removing it, the physical part of stock inventory is completely separated to the stock accounting part.
Regards
claudio candito

**Comment by ccandito** [comment]
Dear Simon,
so I'd suggest to remove the cost field in stock.quant model because it is
misleading.
Removing it, the physical part of stock inventory is completely separated
to the stock accounting part.
Regards
claudio candito

2018-03-01 11:37 GMT+01:00 Simon Lejeune <notifications@github.com>:

**Comment by sle-odoo** [comment]
It is separated, except when the cost method is real. Anyway, this confusion isn't present anymore in v11.
