### ISSUE TITLE
[11.0] price_unit become 0.0 when user edits the product in the purchase order line

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#23405]
**Impacted versions:**
11.0c

**Steps to reproduce:**
1. Create a purchase order 
2. Create a purchase order line
3. Add a product the the line
4. Change the price of the product
5. Edit the product information through the external button

**Current behavior:**
The onchange method of `product_id` is triggered and the `price_unit` and `price_subtotal` of the purchase order line become 0.0
https://github.com/odoo/odoo/blob/bb6039369c1b2d0e02d7c1db46c9b5213643ae74/addons/purchase/models/purchase.py#L789

**Expected behavior:**
The `price_unit` and `price_subtotal` should remain the same since the product does not change.

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/1FcFx7m7fG16fyCylT7zrs9Pqc74xwdr-/view

**Comment by sswapnesh** [comment]
Hello @TimLai125 
Added OPW-1986957 (It is for Invoice) 
I tested this and It is same behaviour across all.

**Comment by sswapnesh** [comment]
From Odoo Support team:

_The technical team had confirmed that the behavior is expected._ 

IMO this is not desired behaviour as we are not changing product here.

Hello @pedrobaeza  @Yenthe666 
What do you think on this one ?

**Comment by Yenthe666** [comment]
Hmmm I find this an odd choice as there is no price changed?

**Comment by sswapnesh** [comment]
This happens when you change anything on Product. (Even a Space on name/description)

Ps: This is happening all over the Places/for all onchange in odoo. :disappointed:

**Comment by Yenthe666** [comment]
I don't really like it but as Odoo has gave an official response saying it won't be changed / is expected there is not much we can do. It is their final call so I guess I can only close this one :(
