### ISSUE TITLE
Sales Journal posting to general ledger for Products created using BoM type of kit is incomplete 

### ISSUE THREAD

**Issue by KangOdoo** [odoo/odoo#23403]
Impacted versions: Odoo 10 CE 

Steps to reproduce: Perpetual Inventory, Anglo-Saxon Accounting, sale of consumer goods at CASE or bundle built from EACH level goods, the unit of measure in inventory. 

Current behavior:

	1. Observed behaviour when kitted product set as Stockable Product and manage production by manufacturing orders :

Dr Accounts Receivable $550
Dr  Cost of Goods Sold   blank value 
Cr Sales                                           $500
Cr GST collected                            $50
Cr Finished Goods                         blank value
(missing values for Dr Cost of Goods Sold and Cr Finished Goods, unreconciled to Inventory App balance)

Inventory App decrements both quantity and cost of components used by $300

	2. Observed behaviour when kitted product set as Consumable and manage production by production orders:

Dr Accounts Receivable $550
Dr  Cost of Goods Sold   blank value 
Cr Sales                                           $500
Cr GST collected                            $50
Cr Finished Goods                         blank value
(missing Dr Cost of Goods Sold and Cr Finished Goods, unreconciled to Inventory App balance)

Inventory App decrements both quantity and cost of components used by $300

3. Observed behaviour when kitted product set as Stockable and manage production by work orders :

Dr Accounts Receivable $550
Cr Sales                                           $500
Cr GST collected                            $50
(missing Dr Cost of Goods Sold and Cr Finished Goods, unreconciled to Inventory App balance)

Inventory App decrements both quantity and cost of components used by $300

4. Observed behaviour when kitted product set as Consumable and manage production by work orders :

Dr Accounts Receivable $550
Cr Sales                                           $500
Cr GST collected                            $50
(missing Dr Cost of Goods Sold and Cr Finished Goods, unreconciled to Inventory App balance)

Inventory App decrements both quantity and cost of components used by $300

The Expense Account on Product card (Cost of Goods Sold) is clearly being referenced by sales journal in first scenario as evidenced by entry in general ledger post but cost value is blank. The Finished Goods value in general ledger is overstated by the cost of all kit components used and sold.

Expected behavior:

Sales Journal for sale of product using BoM type set of components/kit:

	a. Posting in General Ledger
Dr Accounts Receivable $550
Dr Cost of Goods Sold    $300
Cr Sales                                           $500
Cr GST collected                            $50
Cr Finished Goods                         $300

	b. Inventory App should also decrement both quantity and cost of components used by $300

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sle-odoo or @qdp-odoo can you guys please look at this? The (very friendly!) guy called me and explained to me how he is really stuck.
Can you guys please have a look at this and help this along?

**Comment by sle-odoo** [comment]
Hi,
Not sure i understand all the usecase. If the product is set as consumable, there no valuation entries in the stock accounts, so the cogs won't be ok. Also, valuation and kit never really worked together correctly... What's your configured cost method?

Regards

**Comment by Yenthe666** [comment]
@KangOdoo I'd also propose you to make a video of the whole flow you're doing as an example for @sle-odoo. This will probably prevent you both from quite a long message chain and as the timezones are quite different I think this can save you both time.

**Comment by KangOdoo** [comment]
The issue is experienced in a number of four test scenarios but the kit components are stock able items because they are sold in their own right as well as being sold in a kit , and the sales journal works perfectly  for these. I use perpetual inventory and FIFO.

 

If ‘valuation and kit never really worked together correctly’ then let’s fix this with what may only need as small bit of coding. As I let Yenthe know I’m more than willing to work with you to assist in the resolution of this issue.

 

To put this issue into some sort of commercial context, I see the BoM feature as the only viable way for Odoo Inventory to be configured that enables Odoo users selling packaged consumer goods comply with GS1 global recommendations to treat the packaging levels BASE_UNIT_OR_EACH, PACK_OR_INNER_PACK and CASE as separate but related products, not as variants of one product only.

**Comment by sle-odoo** [comment]
> If ‘valuation and kit never really worked together correctly’ then let’s fix this with what may only need as small bit of coding.

I know that we are stuck for the purchase entries, we'd need a model to correctly say this kit cost x usd ; its first component costs x/2 and the two others costs x/4. It should be good for the sales part though, if the products are well configured in delivered invoicing policy.

We are aware of the issue, there's already an internal task but we have to improve a lot of other things in the stock accounting before working in it. I'm afraid a this moment this feature is not supported in standard.

**Comment by KangOdoo** [comment]
Unsure why you state “we are stuck for the purchase entries” when the four scenarios I posted are all for a sale of a kitted product where debit to cost of goods sold and credit to inventory are not being posted in general ledger. Let me know if my examples of sale are not clear.

 

If the kitting feature has been around since at least version 7 and still not fixed in 10/11 is it likely to remain broken indefinitely? Do I need to engage a partner to engineer a workaround?

**Comment by sle-odoo** [comment]
In 3 of the 4 examples, you set the kit as consumable if i read well. Goods set as consumable are not valued. It think this is probably not a good start, but maybe it's unrelated to the problem. Please describe a little meore an example of your first issue, like what is the exact configuration of your kit and contained products, costs of everything, operations made, etc. A video like @Yenthe666 suggested would be even better. Here, i'm not sure how to reproduce and where to start digging.

**Comment by KangOdoo** [comment]
Thanks Simon,

 

I’m double-checking my test scenarios again to see the outcomes, there should have been two scenarios with Stockable components and two with Consumable components (as part of identifying what works and what doesn’t work) so will edit my OP when I’ve done this.

 

I won’t post online a video of my DB for the world to see without anonymising it first  as content is commercially sensitive. For speed happy to arrange a screen share or other suggestion in the meantime..

**Comment by Yenthe666** [comment]
@KangOdoo you can reach him through e-mail too, it should be sle[at]odoo[dot]com if I'm not mistaking, maybe you can send it directly to him or a private link?

**Comment by KangOdoo** [comment]
Will do Yenthe – many thanks for your assistance, it’s very much appreciated!

**Comment by Yenthe666** [comment]
@KangOdoo you're welcome! P.S: Sorry for the delay on answering your e-mail, I'm a bit behind on e-mails. 😉

**Comment by KangOdoo** [comment]
Good news! I have come up with a workaround but have a suggestion for a fix to the missing Cost of Good Sold and Finished Goods entry.

Configuration needed:
1. Kitted product is set as Stockable
2. BoM Type is kit
3. The Cost field on the kitted product needs to be populated - it's this value that gets posted in the Sales Journal, NOT the cost price of the components from the Inventory app. It also does not multiply by the quantity of BoM products sold, it is fixed only. The area for improvement here is for the process to read components' cost down to the quant level and multiply by the number of kitted products sold.. Whilst manually adding a cost into the kitted product's field is ok at a point in time, where costs for a component vary from quant to quant this will then cause inaccuracies.

Thank you Yenthe and Simon for showing interest in this issue - I trust this might get looked at for a fix in the not too distant future.

**Comment by KangOdoo** [comment]
Some bad news - the workaround above is valid only for limited kitting scenarios. These are:

1. Kit BoM consists of multiples of one component.
Eg. Kit1 = Product A x 6 
Cost of 6 Product A must be entered into Cost field of Kit 1 product to generate COGS and Finished Goods entries in Sales Journal 

2. Kit consists of one, and one only, of several different components 
E.g. Kit 2 = Product A x1 + Product B x 1
Cost of 1 Product A and 1 Product B must be entered into Cost field of Kit 1 product to generate COGS and Finished Goods entries in Sales Journal 

The Sales Journal postings to COGS and Finished Goods fails when there are more than one of any of the components in the BoM. 
E.g.
Kit 3 = Product A x 6 + Product B x 3 = Product C x 3
The cost posted to general ledger on sale will only total one each of Products A, B and C.

Furthermore, if the correct cost of the kitted product's Cost field is populated in order to post this number (or a multiple if more than one kit is sold) this fails and the cost of only one each of the components will post. So, bizarrely, if Cost field is blank, no posting occurs. If the correct cost is first entered in to the kitted product, Odoo decides it won't co-operate and posts the wrong amount.

A shoutout to the guys at Probuse Consulting Service and their Show BOM Total Cost on BOM app https://www.odoo.com/apps/modules/10.0/bom_cost_price_update/ This app correctly calculates the cost of the kitted product and shows it on the kit. Sadly, because of the bug(s) in the BoM feature even this correctly calculated cost does not make it to the journal entry.

Odoo S.A. developers - over to you!

**Comment by KangOdoo** [comment]
Just tried yet another workaround to solve the issue of Odoo's BoM feature failing to recognise the costs of more than one of each of the component products. Approach was create a sub-assembly of these and then add these to the highest level kit BoM.

Again, the Sales Journal only pulls from the transaction in Inventory module the costs of one, and only one, of each of the kit's components. Sigh...

**Comment by KangOdoo** [comment]
@Yenthe666 @sle-odoo The posting of COGS and Finished Goods entry has been sorted out by download and reinstallation of latest Windows Odoo - seems it was fixed at some stage. All good now - please close issue.

**Comment by Yenthe666** [comment]
Excellent! That is very good to hear - so you can continue now?
P.S: You should run Odoo on Linux, much easier to update and most people use Linix.

**Comment by KangOdoo** [comment]
Yep, making good progress now. Regarding Linux I haven't had an opportunity to use my cloud server running Ubuntu for a few weeks so have had to do my configuration and testing on a Windows PC. Glad we got that BoM issue sorted out

**Comment by Yenthe666** [comment]
Happy to hear, best of luck! 😄 
P.S: If you need an easy way to install: I have an automated install script for Linux.
