### ISSUE TITLE
ir.sequence with code 'dispatch.name' does not work

### ISSUE THREAD

**Issue by pkgvrpdm** [odoo/odoo#23418]
the following xml for generating sequence does not work, the problem is  'dispatch.name' in line 
\<field name="code">dispatch.name\</field>

\<?xml version="1.0" encoding="utf-8"?>
\<odoo>
    \<data noupdate="1">

        
        <record id="seq_dispatch" model="ir.sequence">
            <field name="name">Dispatch_Order</field>
            <field name="code">dispatch.name</field>
            <field name="prefix">DO</field>
            <field name="padding">5</field>
            <field name="company_id" eval="False"/>
        </record>

    </data>
</odoo>

**Comment by fmdl** [comment]
Try `<field name="code" eval="dispatch.name" />`
