### ISSUE TITLE
[10/11/master] Onchange performance issue on model with several "stored computed field"

### ISSUE THREAD

**Issue by tfossoulw** [odoo/odoo#23410]
**Impacted versions:** 
10, 11, master

**Steps to reproduce:**
You can reproduce the problem on every model that have several "stored computed field" -> Purchase.order for instance

Create a Purchase order and add about 2000 lines on it.
Edit the purchase order
Change the "product_qty" on several lines.

The system will start to work and will freeze your screen for 30 seconds to 2 minutes.

**Why is it freezing**

The system is working because each time you adapt a value, **the "onchange" function (in odoo/models.py line 5419** for V10) is launched.
If you analyse this function you will see the system will try to read all values of the record and subrecord and it will force the recalculation of All computed fields.

You can see it on line 5456 (v10)
```
	# load fields on secondary records, to avoid false changes
        with env.do_in_onchange(): -> This option force the recalculation of computed field
            for field_seq in secondary:
                record.mapped(field_seq)
```
Then if you read further you will see the system recalculate them Again a second time on line 5491:
```
	# force re-evaluation of function fields on secondary records
        for field_seq in secondary:
            record.mapped(field_seq)
```

So it start to be really slow if your are trying to edit a Purchase order or a stock picking with 2000 lines or more.

**Question:**
- Is it really needed to recalculate all field ? Even those we don't need ? Actually we just need to load field that depend the field we are actually editing right ?
- Why recalculate it 2 time ?
- Is this behaviour that apply to "onchange function" must also be applied to "compute function" ?

**Comment by Yenthe666** [comment]
@xmo-odoo I believe this is one for you and you're the best guy to answer this.

**Comment by tfossoulw** [comment]
I was looking for this guy to resolve this :) @xmo-odoo don't hesitate to contact me if you need more details.

**Comment by ged-odoo** [comment]
I would say that @rco-odoo is even more an expert on the topic

**Comment by tfossoulw** [comment]
@Yenthe666 @ged-odoo @rco-odoo @xmo-odoo Any news guys ?

**Comment by Yenthe666** [comment]
Nope, otherwise one of the guys would have commented. I guess whenever @rco-odoo has time he'll look into it.

**Comment by pedrobaeza** [comment]
I don't get where do you want to go? Where's the degradation data?

**Comment by pedrobaeza** [comment]
@rco-odoo I let you see this to decide what is the problem here.

**Comment by piqoni** [comment]
We're also being affected by this issue at Purchase Order model with >15-20 order lines, when onchange is called (so when the user is adding new items), it will show the loading spin and eventually block the user for about 4-5 seconds for each order line added. 

Odoo 10 Enterprise.

**Comment by rousseldenis** [comment]
OPW-1853391

**Comment by rim-odoo** [comment]
Hello

According to @rco-odoo (our ORM/performance specialist), this won't be a piece of cake to optimize, especially in a stable version.
A performance patch should land in master soon, but I'm afraid that older version won't be optimized.

If this onchange really bothers you, you can still add `on_change="0"` in your view in order to disable it.
https://www.odoo.com/documentation/11.0/reference/orm.html#onchange-updating-ui-on-the-fly

Regards

**Comment by egonravalah** [comment]
Hi,

is there any information about this?
