### ISSUE TITLE
[11.0] Chatter doesn't work with imported records

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#23421]
Impacted versions: 11.0e

Steps to reproduce:
1. Import records of any type (contacts, products, etc...)
2. Open any of the imported records.
3. Edit any of the imported records.

Current behavior:
Chatter doesn't show anything.

Expected behavior:
Chatter to show logs.

![image](https://user-images.githubusercontent.com/6585110/36873526-1c72ba3a-1d7f-11e8-8377-16a194b2850c.png)

**Comment by Yenthe666** [comment]
@edsersolis can you please provide a sample file to trigger this behaviour?

**Comment by edsersolis** [comment]
[product.template (6).xlsx](https://github.com/odoo/odoo/files/1778083/product.template.6.xlsx)

**Comment by edsersolis** [comment]
The one above is an example file.

**Comment by edsersolis** [comment]
This seems to not be happening in last builds. Closing it.

**Comment by Malaayoussif** [comment]
The same issue faced me any update regarding to this issue please .
