### ISSUE TITLE
Real Duration Calculation in work orders

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#23427]
Impacted versions: 10

Steps to reproduce:
create a MO with WOs
confirm them

Current behavior:
Effective duration is calculate without taking into account the working calendar

Expected behavior:
the working calendar should be taken into account for determining the Real Duration.... as done in the planning phase
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @ccandito,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
