### ISSUE TITLE
Message out of context - "You should rather cancel the transfer"

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#23434]
### Impacted versions:

11.0

### Steps to reproduce:

Click on "Validate" in picking form when status is "Waiting".

### Current behavior:

Error message "You cannot validate a transfer if you have not processed any quantity. **You should rather cancel the transfer**" shows.

It used to be just "You cannot validate a transfer if you have not processed any quantity", but this commit https://github.com/odoo/odoo/commit/7ed86b53cdfbab9a7867de328604850138692caf#diff-998d1e77af0fdebafa3c662492abe33c added "You should rather cancel the transfer" part, which sounds abrupt and and out of context/incomplete.  I am not sure why it was added.

### Expected behavior:

Perhaps revert the message back to what it was before the commit, or add more context to the added part of the message.

### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7766939/36902188-93c866bc-1e64-11e8-92fc-d34d980e6927.png)

**Comment by sle-odoo** [comment]
The new message is "You cannot validate a transfer if no quantites are reserved nor done. To force the transfer, switch in edit mode and encode the done quantities."
