### ISSUE TITLE
[10.0] E-Commerce multi pricelist with multi country group

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#23444]
Impacted versions:
10.0

Steps to reproduce:
1. Create new product A with sales price 100 USD
2. Create 2 pricelists for different country groups as the example below:
     - Name Europe Pricelist:
                - Country group "Europe" that contain country "Belgium".
                - Discount 20% for a product A.
      - Name Asia Pricelist: 
                - Country group "Asia" that contain country "China".
                - Discount 10% for a product A.
3.  Open shop without login and add product A has price 80 USD in a cart.
5. Adding billing detail and choose country "China" then Confirm order.

Current behavior:
Appear product price from "Europe Pricelist" with price 80 USD.

Expected behavior:
Appear product price from "Asia Pricelist" with price 90 USD based on pricelist country groups.

**Comment by JKE-be** [comment]
Hello @abdallamhafeez 

The fiscal position is based on the shipping address and not billing address.
Can you confirm that bug is still reproducible?

Thanks

**Comment by abdallamhafeez** [comment]
@JKE-be Please can you explain relation between pricelist and fiscal position in e-commerce?

**Comment by Yenthe666** [comment]
@JKE-be any update here?

**Comment by Yenthe666** [comment]
Dear @abdallamhafeez,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
