### ISSUE TITLE
Pivot view of Inventory at Date and Inventory Valuation reports drops value by Product and totals

### ISSUE THREAD

**Issue by KangOdoo** [odoo/odoo#23448]
Impacted versions: 10

Steps to reproduce:
Switch from List view to Pivot view for both inventory reports
Current behavior:
Inventory at Date report:
Inventory at Date in List view is correct. Switch to Pivot view shows 'Product Quantity' and 'Value' which is actually Unit Cost. Total on this last field is meaningless. Primary benefit of a pivot view is lost and no ability to view Inventory Value by Location, Product or in total.

Inventory Valuation report:
Inventory Value in List view is correct. Switch to Pivot view shows 'Quantity' and 'Unit Cost' (which is labelled Value' in previous report. Total on this field is meaningless. Primary benefit of a pivot view is lost and no ability to view Inventory Value by Location, Product or in total.

Expected behavior:
 Inventory Value (Product Quantity x Unit Cost) is calculated field in both inventory reports Pivot views
Consistent field labels between inventory reports

Video/Screenshot link (optional):
List View showing Product Quantity and Inventory Value (Product Quantity x Unit Cost) 
![image](https://user-images.githubusercontent.com/36682465/36942958-1f19725e-1fd4-11e8-962e-53a2eaaa1ae8.png)

Pivot View drops Inventory Value, the 'Value' is not correct unit cost (doubled because held in two locations!) and therefore grand total meaningless.
![image](https://user-images.githubusercontent.com/36682465/36943159-e8cd2f84-1fd7-11e8-9a20-2ad7bbe2b11c.png)

**Comment by edsersolis** [comment]
@KangOdoo how did you get the Pivot Table in that report?

**Comment by KangOdoo** [comment]
Hi @edsersolis my data in the Inventory at Date and Inventory Valuation was created by an opening inventory adjustment at the beginning of a new financial year, part of a migration from a legacy accounting system. 

In the 'List' view the inventory value is correct. However, the issue is that in the  'Pivot' view the field labelled 'Value' is incorrectly showing Unit Cost data. 

Since 'Valuation' is defined as  Quantity x Unit Cost the Pivot view lacks the ability of the user to do any reporting of inventory valuation at all because the measure is missing. This would be fixed by having the measure 'Valuation', correctly calculated, added to Pivot view.

**Comment by Yenthe666** [comment]
Dear @KangOdoo,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
