### ISSUE TITLE
[7.0] audittrail: many2many message_follower_ids in res_partner gives extra line in audittrail when creating a new res_partner

### ISSUE THREAD

**Issue by progressdll** [odoo/odoo#2344]
Hi Team,

When creating a new contact in res_partner and audittrail is active for create on res_partner,
audittrail log wil create 2 lines. One for the newly created partner but also one extra for the value of the  field message_follower_ids which defaults to the user who is creating the contact

In audittrail.py the recursive call of self.get_data on the field message_follower_ids
will add this to audittrail logs.
if model.model == x2m_model.model:
    # we need to remove current resource_id from the many2many to prevent an infinit loop
   if resource_id in field_resource_ids:
       field_resource_ids.remove(resource_id)
   data.update(self.get_data(cr, SUPERUSER_ID, pool, field_resource_ids, x2m_model, method))

[steps to reproduce bug]
Activate autittrail for res_partner ( CREATE )
create a new contact in res_partner

Now there are 2 CREATE lines in the audittrail log.
One of the new res_partner and also a CREATE method for the user who created the new partner.

**Comment by Yenthe666** [comment]
Hi @progressdll,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
