### ISSUE TITLE
use of shareit

### ISSUE THREAD

**Issue by support113** [odoo/odoo#23460]
shareit is an android application which is mainly used for data transfer and USB is also for the same process means to transfer data from one device to [other.<a href="http://sharetech.myfreesites.net/"> shareit for pc</a> universal serial bus connector is mainly used for transfer data from one device to another device but a new technique release in the market that is hot-swapping through this you can transfer your data from one device to other without connecting any USB.

**Comment by Elkasitu** [comment]
Nice try jackass
