### ISSUE TITLE
sales_team team_id field

### ISSUE THREAD

**Issue by wredwan** [odoo/odoo#23482]
Impacted versions:
V10.0 CE
Steps to reproduce:

Current behavior:
sales_team add-on does not contain res.partner inherted view to show **team_id** field 
Expected behavior:
this field have to add to res.partner views Without need to install crm_lead to show up
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

What crm_lead module are you talking about?
The field `team_id` on the partner is technical and not something we wish to display on all contacts.
You may customize the view if you want to display it
