### ISSUE TITLE
doc document can't translated

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23495]
Impacted versions:

Steps to reproduce:

Current behavior:
[documenttation-user](https://github.com/odoo/documentation-user) can be translated at www.transifex.com.
why [doc](https://github.com/odoo/odoo/tree/11.0/doc) can not be translate at www.transifex.com

Expected behavior:

Video/Screenshot link (optional):

**Comment by sum1201** [comment]
why no reply ? @Yenthe666

**Comment by Yenthe666** [comment]
@sum1201,

As @mart-e can answer this one. I just label them so that the relevant people find them easily whenever I don't know the answer/reason myself.

**Comment by mart-e** [comment]
Hello,

We do not wish to translate the technical documentation at this time.
Unlike the documentation-user, it is a document that is intended for developers, not end users.
As most developers resources are already in English only, developers tend to understand this language.

We prefer to properly translate the product and user documentation before adding even more content.

Maybe later but it is not planned now.
