### ISSUE TITLE
[11.0] Enterprise: scrollTo behaviour with MD viewport

### ISSUE THREAD

**Issue by vincentius** [odoo/odoo#23491]
Impacted versions:
11.0 Enterprise
Steps to reproduce:

- On Odoo 11 Enterprise, zoom in on a Sale Order form view until the chatter is below the form and scroll down a bit. (so `config.device.size_class` is smaller than 3)
- Click "Add an item"

Current behavior:
The modal opens, and the form in the background scrolls back to the top.

Expected behavior:
The modal opens, and the form in the background stays at its current scroll position, like when `config.device.size_class` is 3.

I hotfixed this behaviour by modifying 
`var xs_device = config.device.size_class <= config.device.SIZES.XS;` 
to 
`var xs_device = config.device.size_class <= config.device.SIZES.MD;` 
in
`web_enterprise/static/src/js/web_client.js`. 

But I don't know if these changes will break something else...

**Comment by Yenthe666** [comment]
@ged-odoo something for the JS team to check. 😉
