### ISSUE TITLE
[Odoo 11 CE] Inventory: The barcode for the product is not generated. 

### ISSUE THREAD

**Issue by arafatx** [odoo/odoo#23508]
In odoo 10, there is no problem generating Odoo barcode for product. In odoo 11, the barcode is not showing. 

I follow the solution from this by adding the report.url : https://www.odoo.com/forum/help-1/question/generate-pdf-report-to-product-labels-the-barcode-is-missing-on-pdf-but-it-work-on-html-116519

But still the product barcode not showing. 

Here is the screenshot attached:

https://s18.postimg.org/9uj1ynuk9/barcode-image.png

Any other things that I can try ? Out of Idea.

**Comment by arafatx** [comment]
Any news on this? Please.

**Comment by arafatx** [comment]
This is configuration problem. Solved.

**Comment by Yenthe666** [comment]
Thanks a lot for the feedback @arafatx!

**Comment by aaronsaquing** [comment]
In my Odoo 11, barcode is missing in html as well as in pdf. I have installed and follow every instruction here. Please help me out. 

See file example below for Print Badge ID. 

![id](https://user-images.githubusercontent.com/42097911/43679146-ac6ab982-9852-11e8-9a12-691a1a4c2871.JPG)
![id2](https://user-images.githubusercontent.com/42097911/43679147-aca5f42a-9852-11e8-98cc-c879b9f57d8b.JPG)

**Comment by pedrobaeza** [comment]
This seems to be a problem with your `web.base.url` system parameter. Check it to see.

**Comment by aaronsaquing** [comment]
@pedrobaeza I strictly followed adding or updating value on web.base.url the  http://127.0.0.1:8069 but nothing work.

**Comment by aaronsaquing** [comment]
@pedrobaeza Yes, will continue to other mean to solve this. Btw, nothing is printed, both in HTML and PDF. Other issues on the forums is that they have it on HTML and not in pdf. My case is a little bit different.
