### ISSUE TITLE
Hierarchical Tree view Bug

### ISSUE THREAD

**Issue by zhnajafzade** [odoo/odoo#23509]
Impacted versions:
version 11

Hello
Hierarchical Tree view dose not work in Salary rule category Hierarchical. I test it in online version too. I think Hierarchical Tree view has problem in odoo 11. It works good in odoo 10.

**Comment by Yenthe666** [comment]
Hi @zhnajafzade,

Please add more information about how to configure / reproduce what you're reporting.
Please do follow the provided template with questions.

Regards,
Yenthe

**Comment by zhnajafzade** [comment]
Hi
I just click in salary rule category hierarchical menu in payroll/configuration. after that , in odoo 10 or odoo 9 i can see hierarchical  tree view that group by parent rule. but in odoo 11 form view open for create new salary rule category.

**Comment by zhnajafzade** [comment]
![odoo10](https://user-images.githubusercontent.com/37137088/37080690-508ba31e-21fc-11e8-95ee-163e451fe662.png)
in odoo 10 works good

**Comment by zhnajafzade** [comment]
but in odoo 11 .....
![odoo11](https://user-images.githubusercontent.com/37137088/37080725-6c035b28-21fc-11e8-859f-5944637afd1b.png)

**Comment by sswapnesh** [comment]
Hello @zhnajafzade 
Hirerarchical tree views has been removed from V11.

**Comment by sswapnesh** [comment]
Related Issues #20203,#22304 and #20108

**Comment by Yenthe666** [comment]
Indeed, as said by @sswapnesh this view type has been removed from Odoo 11.

**Comment by zhnajafzade** [comment]
Thanks a lot

**Comment by SpiraMira** [comment]
Hi - so what replaces the tree view in 11?

**Comment by holdenrehg** [comment]
Is there some sort of replacement/alternative, outside of developing a custom solution, @Yenthe666 or @sswapnesh . It's nice in some scenarios such as res.partner hierarchies, GL accounts, etc.

**Comment by Yenthe666** [comment]
Not really @holdenrehg, as far as I know there is no alternative on the table yet.
