### ISSUE TITLE
[11.0] Uninstalling hr_timesheet breaks Project's report Feature

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23529]
Impacted versions: 11.0

Steps to reproduce: Uninstall hr_timesheet

Current behavior: Project --> Reporting --> Task Analysis
![](https://image.prntscr.com/image/BH5ZQxUMTjqzCq4B8U1yFA.png)

Expected behavior: Report Should be there.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Ugh, uninstalls break things all over the place.. 😕

**Comment by sswapnesh** [comment]
Yeah, models with `_auto = False` should be auto Initialized. (Better than adding `uninstall_hook` at all places)

**Comment by sswapnesh** [comment]
@Elkasitu  Same behavior in v10 (For all these types of Issues)

**Comment by Elkasitu** [comment]
PR #23551 should address them but it targets v11, I'll backport to v10 if necessary

**Comment by sswapnesh** [comment]
Fixed in #23551
