### ISSUE TITLE
\t does not become a tab character when reading a .po file

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#23521]
Impacted versions: 9-11

Steps to reproduce:

Load a translation file that contains a `\t` escape sequence, such as those generated by POEdit when pressing the TAB key

Current behavior: `\t` becomes a literal `t`

Expected behavior: `\t` should become a literal `	`.

@Tecnativa

**Comment by pedrobaeza** [comment]
@mart-e can you check?

**Comment by pedrobaeza** [comment]
@mart-e this can be closed, isn't it?

**Comment by Yenthe666** [comment]
Yep, fixed in https://github.com/odoo/odoo/commit/4fc09478505689300fe7e2557a605fe47425d0af

**Comment by mart-e** [comment]
You always ruin the fun of automatic closing when forward ported :disappointed:

**Comment by mart-e** [comment]
So, yes, was fixed in 10.0 at https://github.com/odoo/odoo/commit/4fc09478505689300fe7e2557a605fe47425d0af :)

**Comment by pedrobaeza** [comment]
Hehe, it's curious that GitHub doesn't close this if the merge is not on the main branch.

**Comment by mart-e** [comment]
It is actually [documented](https://help.github.com/articles/closing-issues-using-keywords/).
I guess the idea behind this, is to avoid, on small projects, that as soon as you make a commit in your development branch, it already closes the bug report.

**Comment by pedrobaeza** [comment]
Yeah, I see... thanks for the info
