### ISSUE TITLE
[11.0] Uninstalling pos_sale breaks Sale Channel report

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23530]
Impacted versions: 11.0

Steps to reproduce: Uninstall pos_sale

Current behavior: Sale --> Reporting --> All Channels Sales Order
![](https://image.prntscr.com/image/tk6hMEBIRDiX_8NoC0p94Q.png)

Expected behavior: Report should be there

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This seems to be Issue for all modules where` _auto = False` models are Inherited.
We should have better Solution other than adding `uninstall_hook` in all init.

**Comment by Yenthe666** [comment]
@Elkasitu I thought you where working on some of these recently. Can you check?

**Comment by sswapnesh** [comment]
Fixed in #23551
