### ISSUE TITLE
RFC [11.0] Merge Multiple Company's DB's Into a Single Multi-Company DB

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#23536]
<h1>Impacted versions:</h1>
<ul>
<li>7.0</li>
<li>11.0</li>
</ul>

<h1>Steps to reproduce:</h1>
Take two companies within the same group of companies with two separate databases and attempt to merge them into one multi-company database.

<h1>Current behaviour:</h1>
It is unknown whether this is possible by adjusting company_id's on records alone, or whether more is required.

<h1>Expected behaviour:</h1>
Be able to merge two separate companies with their own individual databases into a single multi-company database.

<h1>Use-Case Explanation:</h1>
I have a customer with a group of companies currently running two separate databases for two separate companies in OpenERP 7.0 (ie. one company per database).
 
I plan to migrate them both to version 11.0 with the Odoo upgrade scripts, however it would be preferred to merge these two migrated databases into a single multi-company database.

I believe in essence I would need to adjust the company_id records in one database and adjust the company_id and increment by +1 for example. 

This is an over-simplification of the process obviously, however I would like to know if this is indeed feasible, or whether another approach might be required.

**Comment by lukebranch** [comment]
@Yenthe666 ,

I wasn't sure whether opening an Enterprise support ticket or an issue would be appropriate for this. Please advise if it's more appropriate to open an internal support ticket for this.

**Comment by Yenthe666** [comment]
Hey @lukebranch,

Honestly, I think that this is something out of the scope that Odoo would want to do. It adds a lot of development/testing to get things like this done.
I guess the answer both on Github and odoo.com/help will be the same but that the response will be faster on odoo.com/help.
@mart-e I think you could answer this anyways.

**Comment by mart-e** [comment]
Hello,

Merging two databases is a very complicated operations that you will need to do manually.
Probably something like try to import all documents from one DB to the other, rectifying the `company_id` indeed.

Please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

**Comment by lukebranch** [comment]
@Yenthe666 @mart-e ,

Noted, and thanks. Apologies for the question/issue. 

I will create an support ticket to discuss this option further if we decide to go down this route.

**Comment by jacobuserasmus** [comment]
@lukebranch we needed to do exactly what you needed to do and I would like to know if you were able to get this done. 

In our case exporting and importing a single model ('res.partner') was trivial, just changed the company-id, but, upgrading and transferring the whole DB into a multi_company DB was quite difficult (still working on it) working on all the exception cases now.

**Comment by Jamufa** [comment]
@jacobuserasmus 
we also need to do exactly what you needed to do and I would like to know if you were able to get this done.
