### ISSUE TITLE
Website_Sale: Product Detail View: Attributes not shown when having multiple values

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#23538]
Impacted versions:
Observed with Odoo 10.0-20180227 (Community Edition)

Steps to reproduce:
Create a product having an attribute with multiple values but does not create variants:
![selection_009](https://user-images.githubusercontent.com/1814941/37139534-8ff35684-22ae-11e8-832d-c487785f691c.png)

![menu_011](https://user-images.githubusercontent.com/1814941/37139737-3fb994b6-22af-11e8-8edf-179a458e3b48.png)

Current behavior:
The attribute "Varietal" is not shown in the Product Detail Page:

![selection_012](https://user-images.githubusercontent.com/1814941/37139840-bbad4e6e-22af-11e8-920f-0a2e3bd01133.png)

Expected behavior:
The attribute and its values should be shown the same way as there is only one attribute value:

![selection_013](https://user-images.githubusercontent.com/1814941/37139924-1195c054-22b0-11e8-833e-8ba6c9ff8166.png)

@Yenthe666 This is a nasty little detail and I'm sure it needs some love :-)

**Comment by Yenthe666** [comment]
@JKE-be might be something for your team to check.

**Comment by treviser** [comment]
@rdeodoo Thanks for your reply.

> It looks like an attribute that is not creating product variants should still be displayed the same way as if it was creating variants.

This is not possible, because the display for variants is a display which needs a user interaction (selecting). When there are no variants, then there is no need for an interaction, then it is information only.

> In your case you should have a select list for Varietal with Cabernet Franc, Cabernet Sauvignon and Merlot.

The wine in my example is a blended wine (as all Bordeaux wines are), there is no selection possible, there is only the display of the blended varietals as an important information about the product. This is the fundamental meaning of the term "attribute", it's a type of description.

> I just tried on community v10 and it looks fine to me: https://drive.google.com/file/d/1RT9pxv6uRzvF3S_Yp3R1qb3jGXXNX1n4/view


In your example, you have selected the attribute type "Radio", in my example, I have selected the attribute type "Select". In your case, there is a radio list displayed, which is wrong in my opinion, because as already mentioned, if there is no variant, then there is nothing to select. In my case, there is nothing displayed at all, not even a selection dropdown, which should then be available according to your logic.

**Comment by treviser** [comment]
@rdeodoo After thinking more about it, I understand that there is a display in case of an attribute of type "Radio", but no display in case of "Select", because there is no possible display when following your logic and obviously, there is nothing displayed at all instead. So my proposal: instead of displaying nothing in case of attribute type "Select" without creating variants, simply display the comma separated atttribute values as regular text like the case where an attribute has one value only.

**Comment by rdeodoo** [comment]
@treviser No problem, trying to be as reactive as possible on issue and PR, not always easy to find time and answers

> In your example, you have selected the attribute type "Radio", in my example, I have selected the attribute type "Select".

I saw you coming with that one, after recording the video with a `radio` I noticed you mentionned a `select` but did not want to record it again :yum:.
But it behave the same way with select or radio as you can see in this video: https://drive.google.com/file/d/1eTyZOCCdRp3Ti8cDd7JysGscWKlEJeKL/view

I just double checked with colleagues and it really is intented that way. The purpose of this `Create variant` is to avoid being overwhelmed with unnecessary product variants.

It really is for use cases like I mentionned:

> Indeed, let's imagine a metal bolt product that would be declined in 100 sizes. You may want to give the choice to the user to select on the size but you don't wan't to have a variant for each one, especially if you then have another 'real' attribute that generate variants, it would be too much variants at the end.

Then on the sale order, you will see the product with it's attribute value even if there is no variant.
That way you know what size of `metal bolt` the customer wants.

**Comment by treviser** [comment]
Sorry for my misunderstanding right now concerning the selection dropdown.

So we have 2 use cases:
One use case is for products, which are not stockable, but could possibly create too many variants, so there are no variants, but a selection, which would be treated like a comment (to me this seems to be more an unworldly use case, because either such a "variant" has another price or inventory must be tracked or both). 
The second use case is mine, means products which have attributes with multiple values, which are descriptive only, but must be available for attribute value filters (show me all wines containing "Merlot" as a varietal").
What is the intended way for the second use case?

**Comment by rdeodoo** [comment]
@treviser No problem, I didn't know this feature myself before this issue and asking colleagues.

It really is not intented to be display as description. It is just to avoid showing/asking unnecessary information to customer that an attribute with a single value is displayed as description (eg: there is no choice so don't highlight the value to customer, put it away in description).

For your second use case, since it is not supposed to be used for this, the only thing I could suggest is to set only one value for your attribute `Varietal` (with the `Create variant` still unchecked) to `Cabernet Franc, Cabernet Sauvignon,Merlot`.
That way the attribute having only one value, it will be displayed in the description as you want: https://drive.google.com/file/d/1B3e5PONDa1pjSnPniY6fex9ycFIdfK34/view

**Comment by treviser** [comment]
I know, but this way the attribute filter gets useless because then we have "unnecessary variants" in the filter:
![selection_016](https://user-images.githubusercontent.com/1814941/37413591-ae4127a8-27a7-11e8-97a0-96100f2dece6.png)

Restricting the use of attributes to variants and "quasi-variants" only is in some way mistakable (I really did not expect a "quasi-variant" and still do not see any benefit for that) and unnecessary and hindering for the more common and useful use of attributes (and filters) in a descriptive manner. This is especially helpful for all food and beverages with all the legal requirements for the description of products, which could easily be met with descriptive attributes (instead of BoMs!!!).

So I have a proposal: Could we then have an additional attribute type "Filter (only)", which then only shows the atttribute values as description without any radio boxes or selection dropdowns?

**Comment by treviser** [comment]
@lukebranch I have seen in this issue: https://github.com/odoo/odoo/issues/18682 that you also use attributes in the same way I do. Are you aware about these "quasi-variants" as described here by @rdeodoo

**Comment by fgi-odoo** [comment]
Your case is interesting. It's an improvement request for future versions. For now we don't support it. Attributes are only used to select items in the website. I agree it could be also used just as a simple description.
It's not a small change though if we want to introduce it properly. If we add a new attribute type, it should automatically uncheck "Create Variant" option. It will definitely confuse users. We will work on a better usability.

**Comment by JKE-be** [comment]
Task has been created internally.
I close it since it is not really a bug, but a missing feature.

**Comment by treviser** [comment]
@JKE-be @rdeodoo In the release note for 12.5 in the eCommerce section I read this:

> Product Variants
Use several values of a same attribute as product description. It will ease customer search in the shop.

Is this the realisation of this feature here?

**Comment by JKE-be** [comment]
Yes, it is ;)

![image](https://user-images.githubusercontent.com/4848797/82672038-13aa7680-9c40-11ea-8ded-28c264520f35.png)


Here, how to set up it:

![image](https://user-images.githubusercontent.com/4848797/82672102-29b83700-9c40-11ea-9e54-49543c9f2559.png)


It means that you have a mix of cep2 and cep3.

---


Opposite to 
![image](https://user-images.githubusercontent.com/4848797/82672177-494f5f80-9c40-11ea-845a-66c553bde9d7.png)
![image](https://user-images.githubusercontent.com/4848797/82672318-80257580-9c40-11ea-9ace-b10fb4ab49e4.png)


That mean's that you have as well red as well white
