### ISSUE TITLE
[11.0] Cart Quantity is not updated on Continue Shopping

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23531]
Impacted versions: 11.0

Steps to reproduce: Add Product to Cart --> Change Qty to 3 -> Continue Shopping --> Cart
![](https://image.prntscr.com/image/oDMho4GsSTi8cko6F0z5Ng.png)
![](https://image.prntscr.com/image/l1Zl6Cw-SjCgvK9DBV9Yhg.png)
Current behavior: Quantity is still 1. (Old one added on Product's Page)
![](https://image.prntscr.com/image/WHCKLLLGTnaxleUoQcco0A.png)
Expected behavior: Quantity should be updated

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Should be fixed by commit https://github.com/odoo/odoo/commit/1d6e4a6e6b89e0a589ab8f346365bdb22e073cf2.

Please, reopen if not !

**Comment by JKE-be** [comment]
Shoul dbe fixed by https://github.com/odoo/odoo/commit/1d6e4a6e6b89e0a589ab8f346365bdb22e073cf2

**Comment by Yenthe666** [comment]
Just tested this on the latest 11.0 and it does indeed look fixed.

**Comment by sswapnesh** [comment]
Hello @Yenthe666 
I just tested Same on [Runbot](http://324271-11-0-b81128.runbot11.odoo.com) and Stil Issues Exists.
