### ISSUE TITLE
[11.0] HR Holiday duration no longer takes into account calendar hours

### ISSUE THREAD

**Issue by rmmr** [odoo/odoo#23558]
Impacted versions:
11.0
Steps to reproduce:

1. Go to employees.
2. Select Pieter Parker
3. Edit working time
4. Change (for example) Friday evening from 17:00 to 15:00
5. Go to leaves
6. Create a leave request for a Friday

Current behavior:

Odoo 11: Duration shows **1.0** days

Expected behavior:

Odoo 10: Duration shows **0.75** days

**Comment by jem-odoo** [comment]
Hello,

So the employee is supposed to work from 8h to 12h and from 13h to 15h ? 
If he registers a leave from 7h to 19h, this covers only one work day, even if the leave duration overlaps the working hours. The computation is only based on the working calendar of the employee.

**Comment by adaptivdesign** [comment]
Yes. If you change the working calendar on a given day from 13:00 - 17:00 to 13:00 - 15:00. Requesting a leave on that day would still subtract 1 day from the employees holidays. 

This wasn't the behaviour in Odoo 10. There it would subtract 0.75 days. 

These sort of changes can leave the end user very confused. 

I reverted the behaviour of both this and issue #23559 with the fix supplied there.

**Comment by RomainLibert** [comment]
I suppose this is ok as https://github.com/odoo/odoo/issues/23559 is closed?
