### ISSUE TITLE
[11.0] HR Holiday duration no longer takes into account UoM

### ISSUE THREAD

**Issue by adaptivdesign** [odoo/odoo#23559]
Impacted versions:

11.0

Steps to reproduce:

1. Enable uom in inventory settings.
2. Go to inventory -> Unit of measures -> UoM
3. Edit Hours  (working time)
4. Set ratio to 12.0
5. Create a leave request on any given work day

Current behavior:

Odoo 11: Duration shows **1.0**

Expected behavior:

Odoo 10: Duration shows **0.67**

Possibly related to #23558

**Comment by Yenthe666** [comment]
Hi @adaptivdesign,

Thanks for the bug report.
There is indeed a difference in behaviour between 10.0 and 11.0 actually. Somebody will look into this as soon as they can.

**Comment by abdallamhafeez** [comment]
Hi
I think it should come from contract working schedule because in some cases working time different from employee to other employees

**Comment by adaptivdesign** [comment]
I have looked into this issue myself, and it seems this is not a bug but a decision to strip out this functionality. 

The abstract model 'resource.mixin' defines a method 'get_work_days_data'. This returns both hours and days between two given dates according to the schedule of a resource. The days value is rounded in increments of 0.25. 

This data is used in 2 places:

- Holiday duration (this issue and #23558)
- Payslips

I have overridden this method to work like it did in Odoo 10 (Although Odoo 10's implementation was different, due to resource.mixin not existing and uom_id being present in resource.calendar).

```
from datetime import timedelta
from odoo import api, fields, models
from odoo.tools import float_utils


class ResourceMixin(models.AbstractModel):

    _inherit = 'resource.mixin'

    def get_work_days_data(self, from_datetime, to_datetime, calendar=None):
        days_count = 0.0
        total_work_time = timedelta()
        calendar = calendar or self.resource_calendar_id
        for day_intervals in calendar._iter_work_intervals(
                from_datetime, to_datetime, self.resource_id.id,
                compute_leaves=True):
            theoric_hours = self.get_day_work_hours_count(day_intervals[0][0].date(), calendar=calendar)
            work_time = sum((interval[1] - interval[0] for interval in day_intervals), timedelta())
            total_work_time += work_time
            if theoric_hours:
                days_count += float_utils.round((work_time.total_seconds() / 3600 / theoric_hours) * 4) / 4

        hours_count = total_work_time.total_seconds() / 3600
        uom_hour = self.env.ref('product.product_uom_hour', raise_if_not_found=False)
        uom_day = self.env.ref('product.product_uom_day', raise_if_not_found=False)
        if uom_hour and uom_day:
            days_count = uom_hour._compute_quantity(hours_count, uom_day)

        return {
            'days': days_count,
            'hours': hours_count,
        }

```

@Yenthe666 any updates on this?

**Comment by Yenthe666** [comment]
Hi @adaptivdesign,

Sorry no update. For an official response about it being done on purpose or not we'll have to wait from a comment from somebody within Odoo itself. I'm only here to help as much as I can on issues, I do not work for Odoo.

**Comment by jem-odoo** [comment]
Hello,

Indeed in 10.0, UoM was used to do so, but this is not the case anymore in 11.0, as employee can have different working calendar, and so different hours per day to work. UoM of time are only used when selling timesheet. For working time management, we used only resource module (leaves, forecast, ...).
So, this is not a bug, this is a feature change done on purpose.
Regrads
