### ISSUE TITLE
[10 Enterprise] Sale order line validation Issue

### ISSUE THREAD

**Issue by purnendu03** [odoo/odoo#23556]
Impacted versions: 10 Enterprise

Steps to reproduce:
1) Create a sale order and add sale order lines(Not Inline) without saving the sale order.
2) Edit any of the existing sale order line and hit on "Save & New" on the sale order line.
3) Add another sale order line and hit on "Save & Close". See the magic

Current behavior:
Getting sale order line validation error.

![image](https://user-images.githubusercontent.com/7599739/37172436-c71f81f4-2336-11e8-8fcf-0a5ec30e2515.png)

Note*
Tested same scenario on Enterprise 11 and to my surprise it was allowing me to save and close but last sale order line never included on sale order

Expected behavior:
Sale order line should save and allow us to save main sale order

Video/Screenshot link (optional):

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/dcf77ee9f9c816d8daef474bf566e89411b45bdd
