### ISSUE TITLE
[10.0][11.0] Partial payment not included in partner ledger report

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#23553]
Impacted versions: 10.0, 11.0

Steps to reproduce: Create an invoice. Pay the invoice partially. Activate the full accounting settings and print Invoicing -> Reporting -> PDF Reports -> Partner Ledger. Leave the box 'Reconciled' unchecked so that only open invoices are reported.

Current behavior: The invoice is included in the partner ledger report for the full amount

Expected behavior: The invoice is included in the partner ledger report for the residual amount.

**Comment by StefanRijnhart** [comment]
From today's 11.0CE runbot:

[Invoice - INV_2018_0005.pdf](https://github.com/odoo/odoo/files/1793544/Invoice.-.INV_2018_0005.pdf)
[Partner Ledger.pdf](https://github.com/odoo/odoo/files/1793545/Partner.Ledger.pdf)

Similar to https://github.com/odoo/odoo/issues/21353

**Comment by oco-odoo** [comment]
Than you for reporting the issue. It was indeed the same kind of bug as on the issue you linked, though it came from something else. I just fixed it https://github.com/odoo/odoo/commit/6f35d859c5f341c350103158e97dcfe99c5b241b .
