### ISSUE TITLE
LOGO missing after login

### ISSUE THREAD

**Issue by arthurmoreirarei** [odoo/odoo#23560]
Impacted versions:

Steps to reproduce: after set the LOGO image, when user login the LOGO missing.

Current behavior:LOGO missing

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Have you tired to empty your browser cache?
The company logo is cached so the old one may remain for some time

**Comment by cierek** [comment]
Let me add my two cents - had the similar issue as well as many others when used Bitnami to deploy (https://community.bitnami.com/t/uploaded-company-logo-not-appearing-in-website/43689/5), However, if it is changing after logging cleaning the browser cache is the solution. You can also try to simple "Ctrl+R".

In future please fill in all required fields as Odoo devs don't know what version of Odoo you are using, they are not magicians.

**Comment by mart-e** [comment]
Thank you for confirming the cache possibility.
