### ISSUE TITLE
3 fields with same compute: 1 store and 2 not

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#23577]
v11.0:
https://github.com/odoo/odoo/blob/0ddcdb1315e96954c1193af550344921ff844a7a/addons/sale/models/sale.py#L145-L152

master:
https://github.com/odoo/odoo/blob/414b1ef7817cc24d348d59a65d7ce19d5af091c4/addons/sale/models/sale.py#L146-L153

This compute method is called evey times and allways write DB.

I think that we have 2 options:
 - none field store: avoid write in DB
 - all field store: avoid recompute every time

@Tecnativa

**Comment by pedrobaeza** [comment]
Version? In stable, we can't make any of the options.

**Comment by carlosdauden** [comment]
master:
https://github.com/odoo/odoo/blob/414b1ef7817cc24d348d59a65d7ce19d5af091c4/addons/sale/models/sale.py#L146-L153

**Comment by carlosdauden** [comment]
I understood that stored field can be used in many functions and not stored only in form view.
