### ISSUE TITLE
[l10n_mx_reports] wrong period in coa xml report

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#23572]
Impacted versions:
* 11.0

Steps to reproduce:
* Create xml file to send SAT

Current behavior:
* The period in name file and xml is the current period and if the date is into the first  days of the month the SAT could be return error like this,
![catalogo de cuentas marca error al subirlo al sat 2208 odoo](https://user-images.githubusercontent.com/7595505/37225056-01fe50fc-239b-11e8-8b6f-c282ae1c663e.png)

Expected behavior:
* Select the desired period 

Video/Screenshot link (optional):

**Comment by nim-odoo** [comment]
Fixed in https://github.com/odoo/enterprise/pull/1951/commits/ec381670ea6077c3346721c00d44025e8b740869 if I'm not misleading

**Comment by luistorresm** [comment]
This was fixed on https://github.com/odoo/enterprise/pull/1951
