### ISSUE TITLE
Website translations hell

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#23586]
**Impacted versions:**

Odoo CE from v9 to v11.

**Steps to reproduce:**

Play w/ translations on website (see attached screenshots).

**Current behavior:**
A mess. This is the report I got from a customer:

* The "workflow" of creating copy and translating it is so buggy that it is almost impossible to create proper content in an acceptable amount of time (and nerves). 

* If I use paragraphs in the English original they are automatically transferred into the German version. Copy paste of a complete translation of the English original is impossible. 

* It is not possible to get rid of these prearranged paragraphs properly in translation mode, HTML snippets seem to survive attempts to delete them making it impossible to save the draft. 

* Links created in the English master are converted into a paragraph in the German translation. It is mostly not possible to overwrite them without creating a total mess (see screenshots attached)

**Expected behavior:**
Be able to edit translations and get a nice result.

**Workflow screenshots:**

![odoo_translation_issue_01](https://user-images.githubusercontent.com/36938103/37210954-b8538d86-23aa-11e8-8564-e9b1899e3143.jpg)
![odoo_translation_issue_02](https://user-images.githubusercontent.com/36938103/37210956-b86f4350-23aa-11e8-99d3-c7c8c8e52a87.jpg)
![odoo_translation-issue_03](https://user-images.githubusercontent.com/36938103/37210957-b88c2466-23aa-11e8-8c86-71beb91c8d04.jpg)
![odoo-translation_issue_04](https://user-images.githubusercontent.com/36938103/37210958-b8a85b86-23aa-11e8-93fc-e8a0a228206b.jpg)
![odoo_translation_issue_05](https://user-images.githubusercontent.com/36938103/37210959-b8c1820a-23aa-11e8-9691-3c8ad3371968.jpg)
![odoo_translation_issue_06](https://user-images.githubusercontent.com/36938103/37210963-ba676c78-23aa-11e8-834c-3bb08056f9cc.jpg)
![odoo_translation_issue_07](https://user-images.githubusercontent.com/36938103/37210964-ba875bb4-23aa-11e8-9f54-f0830a736f62.jpg)
![odoo_translation_issue_08](https://user-images.githubusercontent.com/36938103/37210966-baa3b714-23aa-11e8-8220-21f2bfee3a25.jpg)
![odoo_translation_issue_09](https://user-images.githubusercontent.com/36938103/37210967-bac27226-23aa-11e8-8f5f-a29e3ead5022.jpg)

**Comment by lucode** [comment]
Blog module is indeed messy. It is not usable without the possibility to edit HTML source. But I think the described issue relates more / only to blog and not website pages in general.

**Comment by simahawk** [comment]
@lucode AFAIK nope, is related to all snippets editing. Try to deal w/ a link, then you tell me if it works fine out of blog. There's no (or should not be) any difference in editing a blog snippet or a page snippet. To editor they are the same thing.

**Comment by michaelkarrer81** [comment]
+1 real problem, not user friendly at all

**Comment by JKE-be** [comment]
Translations are done paragraph by paragraph.

So it is by design that you cannot delete a paragraph in the German version.

If you want to translate by copy / past, you need to do it one by one.

Yes... it is annoying and take sometimes, but in the previous version when you update 1 char of a paragraph, all the block was no more translated, that was worst! Now, you break just the translation of 1 paragraph.

**Comment by simahawk** [comment]
IMHO translating a full page by paragraph does not make sense. It makes sense only for translating UI (menu items, stuff in header and footer). 
In real world you can have different content for different languages. 
That been said... is there any way, even if hacky, to work around this?
Which are the plans - if any - to improve this situation?

**Comment by pedrobaeza** [comment]
I tend to agree with @simahawk, as paragraph translation only brings one benefit: extracts texts from HTML tags for easy translation, but supposes a lot of other drawbacks:

* Not able to decouple text content between each website language. There are titles, paragraphs and so on that doesn't make sense on other language. And it's weird to explain to users that they have to empty that paragraph/title (which is not even the solution, as you have to put at least a blank space for making effective the translation). The final layout can be very ugly with these extra lines.
* You can't change an image. If your image has any translatable content (like an screenshot, or advertising text), and you want to use another image for other language, you aren't able to.
* The same happens with links. You are able only to change the alt text.

@simahawk have you tried to overwrite `translate=html_translate` with `translate=True` to see if the translation mechanism return to classic one?

**Comment by simahawk** [comment]
@pedrobaeza nope, I'll give it a try next week but I fear is going to be troublesome if you set it on pages whose model is ir.ui.view -> will it still work fine w/ all the views? Tnx for the hint anyway :)
