### ISSUE TITLE
Attach solution screenshots against Exercise code

### ISSUE THREAD

**Issue by ASHWINI-GUPTA** [odoo/odoo#23585]
Impacted versions: All

Current behavior: There are only exercise code for practice. 

Expected behavior: Attach screenshot for the solution (how code will look like in working) against every exercise file.

**Comment by Yenthe666** [comment]
Hi @ASHWINI-GUPTA,

About which exercises are you talking?

**Comment by ASHWINI-GUPTA** [comment]
Documentation exercise code.

**Comment by ASHWINI-GUPTA** [comment]
[https://www.odoo.com/documentation/10.0/howtos/backend.html](url)
Have exercise section which have no screenshot of how the solution looks like.

**Comment by Yenthe666** [comment]
@ASHWINI-GUPTA the documentation is full of examples/answers? 😕 For example:
![image](https://user-images.githubusercontent.com/6352350/37276002-e5c19834-25e0-11e8-8449-a70bdfa07882.png)
The solution is literally in there.
