### ISSUE TITLE
How to override  chat_manager.js of mail module?

### ISSUE THREAD

**Issue by durvilchat** [odoo/odoo#23580]
Good evening friends please help me I would like to know how to inherit the mail.chat_manager file from odoo and modify the functions of the ChatManager varibles. thank you

``odoo.define('mail_modern.chat_manager', function (require) {
    "use strict";

    var bus = require('bus.bus').bus;
    var utils = require('mail.utils');
    var config = require('web.config');
    var Bus = require('web.Bus');
    var core = require('web.core');
    var session = require('web.session');
    var time = require('web.time');
    var web_client = require('web.web_client');
    var Mixins = require('web.mixins');
    var Class = require('web.Class');
    var chat_manage = require('mail.chat_manager');

    var _t = core._t;
    var _lt = core._lt;

// Private model
//----------------------------------------------------------------------------------
    var messages = [];
    var global_unread_counter = 0;
    var client_action_open = false;

// Global unread counter and notifications
//----------------------------------------------------------------------------------
    bus.on("window_focus", null, function () {
        global_unread_counter = 0;
        web_client.set_title_part("_chat");
    });

    chat_manage.include({
        
    })

    var ChatManager = Class.extend(Mixins.EventDispatcherMixin, ServicesMixin, {
        // these two functions are exposed for extensibility purposes and shouldn't be called by other modules
        make_message: make_message,
        make_channel: make_channel,

        init: function (parent) {
            var self = this;
            Mixins.EventDispatcherMixin.init.call(this);
            this.setParent(parent);

            this.bus = new Bus(this);
            this.bus.on('client_action_open', null, function (open) {
                client_action_open = open;
            });

            bus.on('notification', null, on_notification);

            this.channel_seen = _.throttle(function (channel) {
                return self._rpc({
                    model: 'mail.channel',
                    method: 'channel_seen',
                    args: [[channel.id]],
                }, {
                    shadow: true
                });
            }, 3000);
            this._super(parent);
        },

        start: function () {
            this.is_ready = session.is_bound.then(function () {
                var context = _.extend({isMobile: config.device.isMobile}, session.user_context);
                return session.rpc('/mail/client_action', {context: context});
            }).then(this._onMailClientAction.bind(this));

            add_channel({
                id: "channel_inbox",
                name: _lt("Inbox"),
                type: "static",
            }, {display_needactions: true});

            add_channel({
                id: "channel_starred",
                name: _lt("Starred"),
                type: "static"
            });
        },

        get_message: function (id) {
            return _.findWhere(messages, {id: id});
        },
        get_messages: function (options) {
            var channel;

            if ('channel_id' in options && options.load_more) {
                // get channel messages, force load_more
                channel = this.get_channel(options.channel_id);
                return this._fetchFromChannel(channel, {domain: options.domain || {}, load_more: true});
            }
            if ('channel_id' in options) {
                // channel message, check in cache first
                channel = this.get_channel(options.channel_id);
                var channel_cache = get_channel_cache(channel, options.domain);
                if (channel_cache.loaded) {
                    return $.when(channel_cache.messages);
                } else {
                    return this._fetchFromChannel(channel, {domain: options.domain});
                }
            }
            if ('ids' in options) {
                // get messages from their ids (chatter is the main use case)
                return this._fetchDocumentMessages(options.ids, options).then(function (result) {
                    chat_manager.mark_as_read(options.ids);
                    return result;
                });
            }
            if ('model' in options && 'res_id' in options) {
                // get messages for a chatter, when it doesn't know the ids (use
                // case is when using the full composer)
                var domain = [['model', '=', options.model], ['res_id', '=', options.res_id]];
                this._rpc({
                    model: 'mail.message',
                    method: 'message_fetch',
                    args: [domain],
                    kwargs: {limit: 30},
                })
                    .then(function (msgs) {
                        return _.map(msgs, add_message);
                    });
            }
            console.log(messages);
            this._super(options);
        },
    });
});``

**Comment by Yenthe666** [comment]
Hi @durvilchat,

The Github issue tracker is only for bugs, not for asking questions.
Please do ask these kind of questions on the official help forum at odoo.com/help.

Regards,
Yenthe

**Comment by aaguptaayush** [comment]
how to use chat_manager.js for desktop notification in odoo

**Comment by vancouver29** [comment]
did anyone figure out how to inherit the `mail.chat_manager` ?
