### ISSUE TITLE
[7.0] Search widget on date doesn't take date format into account

### ISSUE THREAD

**Issue by sferket** [odoo/odoo#2359]
We tested this on version 7.0

We use the search widget in odoo to search on dates. We want to find all partners that are born on a specific date. 
We have date format set to %d-%m-%Y

When we enter 01092014 (without dashes) in the serach box we get: Search date: 09-01-2014. We would have expected 01-09-2014. If we enter 31092014, it seems to work as expected (31-09-2014).

**Comment by Yenthe666** [comment]
Hi @sferket,

Thank you for your report.
As @rha-odoo said it is handled by the library and it has been fixed in https://github.com/odoo/odoo/pull/3238/commits/7a1e385946cbbbd2c390eab0d92ff35492e563f7

Regards,
Yenthe
