### ISSUE TITLE
wrong-label in SO form - website

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#23594]
Impacted versions: 11.0 CE

Steps to reproduce:
-Go to My account
-Sales orders - > open sale order which is in done state
-in list of sales order, state sign of label is correct but when i open form view that sale order state sign of label  is incorrect

for more information show screen-shot or video

Current behaviour:
SO state label sign is incorrect

Expected behaviour:
SO state label sign should is correct if it is done state

Video/Screenshot link (optional):
Video : https://youtu.be/IlkfmnKazU8
Screenshots : 
![from_view](https://user-images.githubusercontent.com/25322407/37277908-1ca259c6-260c-11e8-93e8-0c8422ec9f1e.png)
![list_view](https://user-images.githubusercontent.com/25322407/37277909-1cd07c48-260c-11e8-993c-c3f4252d2359.png)

@Yenthe666 , can you please look into it !

Thanks!

**Comment by rohitramnani1994** [comment]
Hello @Yenthe666 
please fix it

Thanks!

**Comment by Yenthe666** [comment]
@rohitramnani1994 I don't work for Odoo, don't forget that 😉 Somebody from the team will look into this as soon as they can!

**Comment by JKE-be** [comment]
confirmed for sign, wishlist for color
