### ISSUE TITLE
field not refreshed on form view after data modification if triggered from comodel

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#23608]
Impacted versions: 9.0 others not tested

Steps to reproduce:
create a model and lines for that model.
create a form view, and on the lines, create buttons, and that button onclick modifiies one of the main model's field  ---- in my case, the comodel lines was a computed field

Current behavior:
The data modified on the database, but not refreshed on the screen
Forced refresh, or next/prev record reloads the record and shows the modified data

Expected behavior:
data must be refreshed on the screen

**Comment by Yenthe666** [comment]
Hi @Gyuri77,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
