### ISSUE TITLE
[11] Vendor Bills Create view changes to Customer Invoices

### ISSUE THREAD

**Issue by antsjr** [odoo/odoo#23612]
Impacted versions:
11

Steps to reproduce:
1. Go to Vendor Bills
2. Create a bill, save it
3. Duplicate the bill (Action -> duplicate)
4. Click on the Vendor Bill URL above "Edit/Save" buttons
5. Click Create, go to "Other Info" tab on the bill draft and observe

Current behavior:
Vendor bill is changed to Customer invoice (journals, accounts etc)

Expected behavior:
Vendor bill is not changed to Customer invoice

Other info:
No apparent error visible
Not reproducible on 10.0

![screenshot from 2018-03-13 13-50-18](https://user-images.githubusercontent.com/24793392/37341019-b1b3ab3e-26c8-11e8-9d60-f0aa41359fe2.png)

**Comment by sswapnesh** [comment]
This will be fixed in fd148c8d5e969a98c1f065e29e5b33dac8501d1a
Cc: @Yenthe666

**Comment by Yenthe666** [comment]
Hi @antsjr,

This should indeed be fixed in https://github.com/odoo/odoo/commit/fd148c8d5e969a98c1f065e29e5b33dac8501d1a
Thanks for the tip @sswapnesh 

Regards,
Yenthe

**Comment by drg19** [comment]
@Yenthe666 
The link to the solution is broken
could you repost the solution link?

**Comment by sswapnesh** [comment]
@drg19  Is it still happening on latest v11 ?
I believe it was fixed in https://github.com/odoo/odoo/pull/24036

**Comment by drg19** [comment]
@sswapnesh Thanks!
