### ISSUE TITLE
Division by zero Exception in Currency rate conversion method

### ISSUE THREAD

**Issue by shameembabu** [odoo/odoo#23615]
https://github.com/odoo/odoo/blob/088e3d2fecb159eebf750b1437cc336b60f2a428/odoo/addons/base/res/res_currency.py#L175

I have faced the error : ZeroDivisionError: float division by zero when I call the function `_get_conversion_rate`

**Comment by Yenthe666** [comment]
@shameembabu please follow the provided template and add more info. How to reproduce, version, etc.

**Comment by shameembabu** [comment]
I faced this in odoo 11 while using below code

`currency_id._get_conversion_rate(product_currency_id, currency_id)`

Please update like this ..

   ```
 @api.model
  def _get_conversion_rate(self, from_currency, to_currency):
         from_currency = from_currency.with_env(self.env)
         to_currency = to_currency.with_env(self.env)

         if from_currency.rate != 0.0:
             return to_currency.rate / from_currency.rate
         else:
             return 0.0
```

**Comment by mge-odoo** [comment]
Hi @shameembabu 

Thanks for reporting this issue and proposing a fix.

However, `from_currency.rate` should never be 0.0 ; if you don't specify a rate, the default rate is 1.0 (see https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_currency.py#L61) so it means that you have specified a rate of 0.0 for a currency which doesn't make any sense to me.

I therefore close this issue ; do not hesitate to reopen it if you can you provide me a use case of a rate 0.0.

Regards,

Martin
