### ISSUE TITLE
[10.0] Confusion with Decimal Accuracy in POS

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#23619]
**Impacted versions:** 10.0, not tested in other ones

**Steps to reproduce:**

* Set Decimal Accuracy for *Product Unit of Measure* to zero
* Create a product with price 1
* Open POS
* Select the product
* Type on virtual Numpad *2.5*
* You see total price 2.5
* Pay 2.5
* Go to created POS Order in Backend

**Current behavior:**

Pos order has total 3 and payment 2.5. As it's not the same, order's state is *New* and not *Paid*. So, you cannot close the session.

**Expected behavior:**
POS should ask to pay 2.5. Quantity should be rounded the same way as backend does.

**Comment by Yenthe666** [comment]
Dear @yelizariev,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Comment by yelizariev** [comment]
It was fixed here: https://github.com/odoo/odoo/commit/eca99f1f12174cc59e7ff93c40a3aedc2d422049

**Comment by Yenthe666** [comment]
Thanks for pointing that out 😉
