### ISSUE TITLE
l10n de datev module (enterprise) not setting the correct datev main account

### ISSUE THREAD

**Issue by tbaden** [odoo/odoo#23623]
Impacted versions: 11.0

Steps to reproduce:
Install Apps: account_accountant, account_invoicing, l10n_de_skr04
use account chart (fiscal localization): Deutscher Kontenplan SKR04

create an invoice: 
set/create some customer
set journal to "customer invoices"
set account to "120000 Forederungen aus Lieferungen und Leistungen"
set/create two invoice lines with different products
create a third one with a product named "discount" and a negative unit price (e.g. -5.00)
save the invoice and validate.

check the account.move (journal entries) grouped by "L10N de Datev Main Account"
the account.move (journal entry) is in the "undefined" tab

Current behavior:
the created account.move has no "l10n_de_datev_main_account_id" set (undefined)

Expected behavior:
l10n_de_datev_main_account_id set to the correct account_id.

additional info:
if you just use one line item and the discount line item it sets the "l10n_de_datev_main_account_id" correctly.

Video/Screenshot link (optional):
Invoice Creation:
![bildschirmfoto 2018-03-13 um 15 54 10](https://user-images.githubusercontent.com/6755125/37349736-59d2bc8e-26d7-11e8-91d5-f86bffe6b607.png)
![bildschirmfoto 2018-03-13 um 15 54 15](https://user-images.githubusercontent.com/6755125/37349737-5c48a956-26d7-11e8-8840-cc2d8ab0b558.png)

Journal entries:
![bildschirmfoto 2018-03-13 um 15 55 18](https://user-images.githubusercontent.com/6755125/37349782-74a28788-26d7-11e8-9969-2c30d33fd6a9.png)

**Comment by Yenthe666** [comment]
@lap-odoo for your interest!

**Comment by tbaden** [comment]
Any progress on this?

**Comment by thomaspot** [comment]
We also have a customer who encounters this issue. How can anyone use this module; I believe this is a major problem. In Germany they use payment discounts, so there are, almost everytime, multiple item lines on the journal.

Can anyone give an update on this?
