### ISSUE TITLE
[Odoo community 11] In HTML CSS Editor, when I type in Korean its text duplicated

### ISSUE THREAD

**Issue by Linkup2017** [odoo/odoo#23629]
Impacted versions: Odoo Community 11 Website

Steps to reproduce: 

Current behavior: In HTML CSS Editor, when I type in Korean its text duplicated

Expected behavior: No more duplicated text

Video/Screenshot link (optional):
https://youtu.be/XoZrzxdpWWk

**Comment by alexkuhn** [comment]
Hello, this commit should fix the issue:
https://github.com/odoo/odoo/commit/ec199222c34a9f3f7d40b3bf7af7881941d82017

Best,
