### ISSUE TITLE
Internal Server Error for Invalid url on odoo website 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#23627]
Impacted versions:11.0

Steps to reproduce: Go to https://www.odoo.com/login

Current behavior: Internal Server Error 

Expected behavior: 404 Page 

Video/Screenshot link (optional):
![screenshot_20180314-010401](https://user-images.githubusercontent.com/16624719/37365592-fa680a18-2723-11e8-8b16-4d0140b0628e.png)

Still not sure Is that right place to Submit Issue?

**Comment by cierek** [comment]
anything from the log file?

**Comment by Yenthe666** [comment]
@cierek I think you missed a bit here. It is Odoo.com, the official Odoo, so he cannot access the logs. 😆

**Comment by JKE-be** [comment]
Expected behavior, this route exists but some args are missing.

**Comment by sswapnesh** [comment]
@Yenthe666 Already using `web/login`, typo `/login` resulted into this error.
