### ISSUE TITLE
Confirming a purchase order while in multi workers mode fails before the end of the process

### ISSUE THREAD

**Issue by cyp-opennet** [odoo/odoo#23637]
Impacted versions:
- 9.0

Steps to reproduce:
- Multi-workers mode, 
- 32 active  users connected and using Odoo, 
- a scheduler continuously synchronizing with an external web server
- a purchase order with 67 lines
- each product has one route: buy

Current behavior:
While in mono-workers: every runs fine: corresponding IN and OUT pickings correctly created.
Note that in my virtual machine, the process takes up to 5 minutes.
If multi-workers mode activated in the customer's environment, the javascript in the browser seems to time out before the process is finished.
Result: incomplete IN and OUT pickings

Expected behavior:
IN and OUT pickings with complete initial demand.

**Comment by intero-chz** [comment]
Maybe 5 min is a bit too long for the workers, whose lifetime is 1 min by default IIRC.

**Comment by Yenthe666** [comment]
Hi @cyp-opennet,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
