### ISSUE TITLE
[11.0] Back to the last page displays the wrong menu.

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#23639]
Hi, here is a client-side issue that trouble my users.

Impacted versions:
11.0 (and others ?)

Steps to reproduce:
- Install crm and sale_management modules, then create at least one customer
- Go to Sales, Customers, and open a customer
- Click on browser button to go to the last page
(same on reloading the page)

Current behavior:
You are now on CRM menu

Expected behavior:
Stay on Sales menu

Video/Screenshot link (optional):
<a href="http://www.k-upload.fr/afficher-video-2018-03-14-14ea35976out.mp4.html" title="K-Upload - Hébergeur de video gratuit">Link to my Video</a>

**Comment by alexkuhn** [comment]
Hi, the issue should be fixed by this commit: https://github.com/odoo/odoo/commit/71616e8d4f9a5bf92487dc6cc89d4945d29b4343

Best,
