### ISSUE TITLE
CSV files under the `init_xml` section are loaded when the module is updated

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#23630]
Impacted versions:
- 11.0

Steps to reproduce:
- Take any module which loads data from a CSV file, e.g. `account`.
- In the manifest, move a CSV file from the `data` section to the `init_xml` section.
  ```
  'init_xml': [
      'security/ir.model.access.csv',
  ],
  ```
- Update the module

Current behavior:
As may be appreciated in the log, the CSV file is loaded

Expected behavior:
Since it's under the section `init_xml`, it should be loaded only when installing the module, not when updating it, as stated [here](https://github.com/odoo/odoo/blob/e449055189328d999a1d61a778dca0aabd34426b/odoo/modules/loading.py#L82).

In addition, since this does not work, there's no way to load a CSV file using `noupdate=1`.

Additional information (technical):
This doesn't work because the method `_load_data` is called only with `kind='data'` and `kind='demo'` ([source](https://github.com/odoo/odoo/blob/e449055189328d999a1d61a778dca0aabd34426b/odoo/modules/loading.py#L156-L159)); and, when the data is loaded, the kind `init_xml` is included.

**Comment by moylop260** [comment]
OPW Odoo Ticket 1826926

**Comment by mart-e** [comment]
Hello,

The `init_xml` and `update_xml` are deprecated arguments. It is still present in the code but not documented, it actually behave like noupdate records (which is +/- the same behaviour).
5 years ago, at dfb9d317f269810c8e857a7bc898389242ac9fa7 @antonylesuisse made it behave like a noupdate writing it as deprecated but we never took the time to fully remove it from the code base.

Sorry but the proper patch should be to remove all the remaining references.

**Comment by Yenthe666** [comment]
@mart-e that is not really an answer that solves or handles this in my opinion. Why don't we make a PR for it right away to remove it? (I guess master?)

**Comment by mart-e** [comment]
My point is that there is no bug. I do not know how you found this manifest key that is not supported for year. I believe we have removed all reference to it from the documentations.

Removing it from master is probably not a patch done in 5min and is just not a priority at the moment.

**Comment by moylop260** [comment]
@mart-e FYI currently importing data from a big file with a xml is 10 times more biggest because each tag is repeated then the importation is so slow.

Using CSV the importation is 10x faster but the main issue is that for each `--update module` the csv is reloaded then requires a way to use a noupdate for xml like as old versions.

What do you think?

**Comment by nhomar** [comment]
@moylop260 We used a technique to achieve that in the module l10n_mx_edi + include the set of noupdate=1 into ir.model.data if needed, please check with @luistorresm 

I do not think that's a really needed feature that can have a clean answer.
