### ISSUE TITLE
[11.0] Expense-module expands user rights in sales

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#23643]
### Impacted versions: 
11.0 (confirmed with latest runbot build

### Steps to reproduce:
1. Install `sale_expense`
2. Create a user with sale rights `User: Own documents only`
3. Create sale orders as another user and confirm them
4. Log in as the user created in step 2 and open the sales orders view

### Current behavior:
The user can see sales that are not theirs, even if they are not the seller.

### Expected behavior:
User should not see sales that are not theirs

**Comment by aisopuro** [comment]
My guess is that the problem stems from the fact that `sale_expense` adds a record rule allowing all Employee-level users to see all sale orders that are in state `sale`. This is fine so long as they don't also have the See own documents only access right, in which case they will have access to the sale views, and so will be able to see sales that are not theirs.

The change was made in 751330a843f30298f50a479cba3d22b5ffaf6cb3 by @jem-odoo .

**Comment by jem-odoo** [comment]
The fix landed in 12.0 with https://github.com/odoo/odoo/commit/f8e41c6b00131bf387843c24d1003310cde92a5e

There are still discussion to backport this fix in 11.0.
