### ISSUE TITLE
[11.0] hr_leaves : Improve access rights of manager/officer 

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#23644]
Impacted versions:
V11

Steps to reproduce:
Login as a user with the Leaves > Officer rights and he should be linked to an employee with a different manager / department manger. This user is a manager and he needs the officerrights to approve leaves for his department.
If you create a leave request, you can approve your own leaves. [NOT OK]

Current behavior:
As a officer you can approve your own leaves. This should be only allowed by his manager

Please apply the same logic for the leaves as this one:
[https://github.com/odoo/odoo/commit/3f9433228cae53b0cbeba38854286e2cd7f70a2a](https://github.com/odoo/odoo/commit/3f9433228cae53b0cbeba38854286e2cd7f70a2a)

**Comment by Yenthe666** [comment]
@RomainLibert I think this is of interest for you. You did the same logic at `hr_expense`

**Comment by RomainLibert** [comment]
Hello,
This is something that we are currently working on in master here (https://github.com/odoo/odoo/pull/19270/files).
Sadly we cannot put this into the stable 11.0 version as it is a change in behaviour and not a bugfix as stated here (https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch). @mart-e

**Comment by yung-wang** [comment]
Thanks, glad it will be solved in the next version.
