### ISSUE TITLE
[11.0] _check_camt method incorrect check

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#23649]
Impacted versions:
[11.0] [enterprise]
Steps to reproduce:
Try to import camt file using bank statement wizard which is not 053 format.
Current behavior:
It returns root tag even if you try to import incorrect file.
Expected behavior:
It should correctly check format and then it would need to return None, instead of root tag.

Look at this file: `enterprise/account_bank_statement_import_camt/wizard/account_bank_statement_import_camt.py` method:

```python
    def _check_camt(self, data_file):
        try:
            root = etree.parse(io.BytesIO(data_file)).getroot()
        except:
            return None
        if root.tag.find('camt.053'):
            return root
        return None
```

`find` method returns `-1`, so this check is passed, because `bool(-1) is True`. It should check  if `root.tag.find('camt.053') != -1`

P.S. I don't know if this is the right place to report enterprise issues? If not, you can remove it, I will report it via enterprise tickets then.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

To answer your question: it is fine to make a bug report for an enterprise issue here. The only downside is that Github is a best effort. If you report it through the official channel (at odoo.com/help) it'll get prioritised. 
P.S: Do add the link to this Github issue on the official bug report if you make it there to have a cross reference.

Regards,
Yenthe

**Comment by oerp-odoo** [comment]
I added link on ticket. Well I could fix it, but I have a feeling it would take longer to get that PR approval then to get fix from odoo itself :). But maybe things have changed..:)

**Comment by Yenthe666** [comment]
@oerp-odoo things do have changed, usually new PR's are handled quite fast now. Give a try next time I'd say 😉
