### ISSUE TITLE
[11.0] Full information of leave is not shown in calendar view

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#23661]
Impacted versions:
V11

Steps to reproduce:
Make sure you have a employee with a long name. Create a leave using the calendar view for 0,5 day. Now you see the leave in the calendar view, but the text is not wrapped. You cannot see the full description with the amount of leave. It use to work fine in V10.

Current behavior:
Leave is not wrapped, full description is not visible until you open the leave.

Expected behavior:
Same or similar to V10

Video/Screenshot link (optional):
**This is V10**
![image](https://user-images.githubusercontent.com/30628967/37411645-94520b04-27a3-11e8-8878-35514603465e.png)

**This is V11**
![image](https://user-images.githubusercontent.com/30628967/37411734-c8b66a16-27a3-11e8-907a-fbd7184ae2ff.png)

**Comment by grzekru** [comment]
Caused by css style from fullcalendar.css
Probably not a bug but intended behavior
```
.fc-day-grid-event .fc-content { /* force events to be one-line tall */
	white-space: nowrap;
	overflow: hidden;
}
```

**Comment by Yenthe666** [comment]
@JKE-be for your interest I believe.

**Comment by JKE-be** [comment]
not really a bug, but maybe we could override css to wordwrap.
/cc @adr-odoo

**Comment by astirpe** [comment]
Is Odoo SA intentioned to fix this behavior or shall we close the issue?

**Comment by JKE-be** [comment]
not really! maybe improve, but never fix since it is not a bug as shown by @grzekru

**Comment by tivisse** [comment]
Hello,

Thank you for the report but I will have to reject this, sorry.

The 11.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.

Regards
