### ISSUE TITLE
[v9.0] Survey data security issue - results visible to anyone

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#23675]
Impacted versions:
9.0
Steps to reproduce:
Create a Survey or use existing one, click "View Results" and copy the address. Log out, enter the results address in the browser.
Current behaviour:
Any user is able to see the results of the survey(s) by simply accessing the survey and adding /results/ in the browser, before the survey name.
This brings two threats:
1) If a survey is anonymous, competitors are able to access the data from the survey that is not necessary for their use.
2) Data Security issue - if the survey contains any personal questions (name, email etc.) that brings a possible data breach. GDPR is coming in 25th of May and this could bring a threat of data loss and huge fines.
Expected behaviour:
Survey answer should be accessed only by employee or admin. Alternatively, there should be an information in the module that data is not safe and it can be used only for general, anonymous research.
Video/Screenshot link (optional):
![survey_issue](https://user-images.githubusercontent.com/18479073/37453359-58d61b24-282f-11e8-95df-fcc53e4d5623.PNG)

**Comment by Yenthe666** [comment]
Hi @cierek,

Thanks a lot for your bug report.
These kind of bug reports are better to be send through the responsible disclosure (at https://www.odoo.com/nl_NL/page/responsible-disclosure) as it is about security and possible data breaches.
@mart-e and @odony for you guys - security related.

**Comment by cierek** [comment]
Probably adding sth like groups="base.group_hr_or_other" in the views would be a temporary fix. Perfectly there could be a tick box in surveys "Results accessible by manager only".

Will make a free module if will have some spare time today.

**Comment by mart-e** [comment]
Hello,

Indeed, the results are public but it is not as bad as you think.
To see the result, you actually need to be logged in.
However, there was indeed a weakness that people not in survey group can not access.
It was fixed at 9fd5df43055.
Thank you for the report !

This is not a security issue to report on the responsible disclosure (even if always good to keep in mind) as the one we consider on the responsible disclosure page

> NON Qualifying vulnerabilities - DO NOT REPORT!
> ...
> Issues in default configuration of access control rules (e.g. ACLs and record rules) - please open regular bug reports instead

@Yenthe666 please keep the security label for security announcements we make, not for the reports of other people.

**Comment by Yenthe666** [comment]
@mart-e apoligies. The label used to mention it was limited to official use only, which is no longer the case. I assumed that with the change of the labels (such as addition of Point of sale besides logistics) this was also changed now. Sorry!

**Comment by mart-e** [comment]
@Yenthe666 no problem. I had written on the label it was for official use but somebody changed it, don't know why :thinking: 
Anyway, I would like to be able to use
https://github.com/odoo/odoo/issues/labels/security
to find all the Odoo security reports

**Comment by Yenthe666** [comment]
Yeah, makes sense. I won't use it again.

**Comment by cierek** [comment]
Thanks for the solution. Well, it might be not security issue from the IT point of view. However, if any logged user can view the results of the survey might be harmful in terms of data protection legislation. Thanks for the commit. Will update
