### ISSUE TITLE
hw_scale module not installable on odoo running on Windows System

### ISSUE THREAD

**Issue by karan-dreambits** [odoo/odoo#23685]
Impacted versions:
v10

Steps to reproduce:

1. Install pyserial module using pip or easy_install
2. Go to Apps and search for hw_scale module
3. Click Install

Current behavior:
Module is not installable as serial library is not found

Expected behavior:
It should be possible to install python libraries for module depending on it 

--------------------

While going through forums and blogs on this issue, we have understood that odoo on windows uses its own internal python installation but a few answers/articles suggested to copy library's folder from python27/lib/site-packages to odoo 10/server.

That also doesn't work making it impossible to integrate a scale with odoo pos if odoo is running on windows

**Comment by Elkasitu** [comment]
@d-fence

**Comment by karan-dreambits** [comment]
@Elkasitu  I believe this issue is also related to https://github.com/odoo/odoo/issues/23109 

Don't know why I cannot refer it here directly

**Comment by Elkasitu** [comment]
@karan-dreambits Hi, this is a limitation of the python executable, it's a closed environment so there's no way for it to access outside dependencies, and there's also no *easy* way of injecting them.

Perhaps in the future some optional libraries will be added to the .exe by default, but for now the best you can do is try a source installation.

**Comment by karan-dreambits** [comment]
Okay .. Thank you for quick replies @Elkasitu .
While I have not been able to find exact documentation on source installation for windows.
I believe it is same as for linux i.e. 

1. Installing python and odoo needed libraries.
2. Installing postgres and setup proper user
3. Download odoo source.

But I think there would be need of creating some service or so manually. Right ?

**Comment by d-fence** [comment]
Hello @karan-dreambits , you can find some windows tips in our install documentation for 10.0: http://www.odoo.com/documentation/10.0/setup/install.html#source-install

About the service, you could get some ideas from our 11.0 installer for windows because 11.0 is some kind of source install on windows:
https://github.com/odoo/odoo/blob/ca83d3c1accb4908e457f6f0564b001142d426fb/setup/win32/setup.nsi#L249

FYI, we use NSSM https://nssm.cc/ and we are very happy of it

**Comment by karan-dreambits** [comment]
Okay @d-fence , thanks for the detailed response. We will look into this options

**Comment by abdomahal** [comment]
I'm Facing This Problem Can any one help me soon because i install python on C:\Program Files (x86)\Python37-32
and The lib its there i need access to lib but i cant the module need serial Module 
any one have a solution
