### ISSUE TITLE
[10.0] AssertionError while delete event from calendar

### ISSUE THREAD

**Issue by mayankksolves** [odoo/odoo#23680]
Impacted versions:

Steps to reproduce:

Current behavior: Currently in Record class record_id type set as unicode
class Record(object):
    def __init__(self, model, record_id):
        assert isinstance(model, basestring)
        assert isinstance(record_id, (int, long))
        self.model = model
        self.id = record_id

Expected behavior:  record_id  should come as int or long type 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @mayankksolves,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
