### ISSUE TITLE
[Enterprise] Not possible to navigate enterprise's main menu using the keyboard

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#23692]
Impacted versions:
- 11.0
- 10.0

Steps to reproduce:
- Go to enterprise's main menu (web_enterprise)
- Pres the keys `<Tab>` or `<Shift>+<Tab>` to navigate

Current behavior:
Nothing happens. All key presses are captured and redirected to the search text box, so they are invalidated.

Expected behavior:
The focus should move forward when `<Tab>` is pressed, and backward when `<Shift>+<Tab>` is pressed.

If I type something into the search box, I can navigate over the search results. However, I'm not able to navigate through anything else, i.e. I can't neither go to the user preferences nor logout,.

**Comment by luisg123v** [comment]
CC @luistorresm

**Comment by luisg123v** [comment]
opw ticket: 1827425.

**Comment by Elkasitu** [comment]
Hi, 

We only handle Standard Odoo issues here, if you already have opened a support ticket and there's a PR in the enterprise repo then there's no need to open an issue here, they will be handled in due time.

Regards

**Comment by luisg123v** [comment]
@Elkasitu 
Thanks a lot for the information, sorry for the inconveniences
