### ISSUE TITLE
web_enterprise: Include Cyrillic subset  into Rotobo font

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#23702]
Impacted versions: 9.0-11.0 EE

Steps to reproduce: Install any Cyrillic language(Ukrainian for ex.) and select it in Preferences.

Current behavior:
Cyrillic text falls back to  serif font

Expected behavior:
Cyrillic text is rendered with Roboto font

Video/Screenshot link (optional):
![screenshot-2018-3-16 odoo](https://user-images.githubusercontent.com/5942291/37518216-ea0bedb0-291c-11e8-9bf4-c10b10ba2650.png)

**Comment by Yenthe666** [comment]
@mart-e probably for you.

**Comment by mart-e** [comment]
Will depend on the decision on #21781

**Comment by lem8r** [comment]
https://apps.odoo.com/apps/modules/11.0/web_enterprise_cyrillic_fonts/
