### ISSUE TITLE
How to change default delete icon of odoo 11 only in my own module

### ISSUE THREAD

**Issue by VarshaBolli** [odoo/odoo#23703]
I have given editable bottom so i am getting default delete icon of odoo11. But i want to change it only to my module. How to change the delete icon to my own module ?

<record id="attachments_form" model="ir.ui.view">

     <field name="name"> Attachments</field>

     <field name="model">attachments</field> 	

     <field name="arch" type="xml">

     <form string="Attachments">

     <field name="line_ids" >

        <tree string="Attachments" editable="bottom">

              <field name="description" />

               <field name="file_name" invisible="1" />

              <field name="upload_file" filename="file_name" />

                <button name ="download" icon ="gtk-go-down" type="object" />

           </tree>

        </field>

</record>

Thanks in Advance !

**Comment by Yenthe666** [comment]
Hi @VarshaBolli,

The Github issue tracker is only for issues in the Odoo source code.
Please do ask questions on the official help forum at help.odoo.com.

Regards,
Yenthe
