### ISSUE TITLE
[9.0][10.0][11.0] Customized view recreated every time we fold/unfold a board on dashboard instead of updating the record

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#23712]
Impacted versions: 9.0, 10.0, 11.0

Steps to reproduce: Add something to your dashboard. Fold and unfold your boards in it.

Current behavior: It creates a new customized view on every fold/unfold

Expected behavior: It should update customized view instead of creating a new one every time

Video/Screenshot link (optional): https://youtu.be/9_dHdosNiqA

**Comment by alexkuhn** [comment]
Whenever we fold/unfold the dashboard, we save it. When we save it, we create a custom view:
https://github.com/odoo/odoo/blob/9.0/addons/board/static/src/js/dashboard.js#L172

I don't know why we have to save the dashboard on this action, neither why "save" becomes "create".
@amigrave could you give us a hint?

**Comment by amigrave** [comment]
@alexkuhn It's a long time ago so I can't be 100% sure, but I think that back in time (v6.1) the goal was to write a new version of the custom view every time, providing the user the ability to Undo all the steps if needed.

It seems that the Undo functionality has been removed in 9.0 (don't know who did that though) but the rest of the controller has not been changed. So I think it is safe to say that creating a new record every time does not make sense anymore now that the Undo button is gone.

That's all I can tell. Over...

**Comment by alexkuhn** [comment]
@jlaloux This issue should be fixed with the following commits:

- in v9: https://github.com/odoo/odoo/commit/b15e805b5ad40e1e8e08e9be1ba248da66158bc9
- in v11: https://github.com/odoo/odoo/commit/b15e805b5ad40e1e8e08e9be1ba248da66158bc9

The patch in v10 is exactly the same as in v9, so it will be forward-ported very soon.

Best,

Alexandre
