### ISSUE TITLE
[11.0] "Total Value" are not displayed after using "grouping by" in Inventory Valuation View 

### ISSUE THREAD

**Issue by minos84** [odoo/odoo#23723]
Impacted versions:
[11.0]
Steps to reproduce:
1- Go to "Inventory"
2- Under "Reporting", click on "Valuation Report"
3- Click on "Group By"
4- Click on "Add Custom Group"
5- Select "Internal Category" for example
6- Click on "Apply" button

Current behavior:
The "Total Value" of the Inventory is not displayed

Expected behavior:
The "Total Value" of the Inventory should be displayed

Video/Screenshot link (optional):

![2018-03-17_13h29_34](https://user-images.githubusercontent.com/6032392/37555461-b724982c-29e7-11e8-8eb3-67370b7633a0.png)

**Comment by KangOdoo** [comment]
@Yenthe666 the problem described here by @minos84 is one part of the significant problems in Inventory Valuation Report and Inventory at Date that I raised here for Odoo 10 https://github.com/odoo/odoo/issues/23448

**Comment by Yenthe666** [comment]
@sle-odoo could you have a look? I think it would be great to still see the sum of the values after grouping.

**Comment by sle-odoo** [comment]
This is fixed in v13.

Regards
