### ISSUE TITLE
Hierarchy Tree View

### ISSUE THREAD

**Issue by yk2kus** [odoo/odoo#23728]
Impacted versions:
V8, V9, V10

Steps to reproduce:
Take any hierarchy View. Here I will take Chart of Account Hierarchy. Setting Start Date
![image](https://user-images.githubusercontent.com/6999933/37561016-9f312a9c-2a22-11e8-9b67-b2041a14ffb5.png)

Opening Hierarchy View shows all balances zero because there is no move line after the selected start date. That's correct.
![image](https://user-images.githubusercontent.com/6999933/37561022-c8f31fd4-2a22-11e8-8566-6b77aa23a2a6.png)
As soon as I click Account Receivable it opens all the Account moves in that particular account. Not caring the selected start date anymore. Which is wrong
![image](https://user-images.githubusercontent.com/6999933/37561030-f1ae1a3c-2a22-11e8-8222-a3ae54cefba2.png)

Current behavior:
Doesn't respect domain on any field other than parent_id. It shows all the children of selected parent
[('account_id','child_of',[active_id])]
Expected behavior:
Should respect the domain which was used to open the hierarchy view initially.[Start Date in this example]
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @yk2kus,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
