### ISSUE TITLE
Stock move line date field never update

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#23725]
This field:
https://github.com/odoo/odoo/blob/625a648f227325468981a9e4a51e80b44132a45f/addons/stock/models/stock_move_line.py#L40

Allways shows the same value as create_date.

Could it be defined as stock.move related field?

Should it be written here?
https://github.com/odoo/odoo/blob/3c0337673385876922da95296e70a0b7b728f275/addons/stock/models/stock_move.py#L1048

@Tecnativa

**Comment by Yenthe666** [comment]
@sle-odoo could you give feedback on this please?

**Comment by sle-odoo** [comment]
hi,
yes i think you're right ; if the field isn't updated it's not really useful
did you notice this issue in the product moves stat button?

**Comment by carlosdauden** [comment]
Yes.

![seleccion_155](https://user-images.githubusercontent.com/7701001/37780203-8df2daa8-2dee-11e8-9719-d12306f859b5.png)
