### ISSUE TITLE
On PO/SO lines, quantity invoiced should only consider open & paid invoices (not draft)

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#23736]
Impacted versions: [10] and probably 9.0 & 11.0

Steps to reproduce:
Create a PO or SO 
Deliver
Create invoice
Save (do not validate it)

Current behavior:
Go back to SO or PO
At PO or SO line level, you will notice that the quantity invoiced has increased.
Odoo considers the draft invoice as it is was validated.

Expected behavior:
On PO/SO lines, Quantity invoiced should consider only open & paid invoices (not draft)

Video/Screenshot link (optional):

**Comment by fclementic2c** [comment]
If the only issue is to avoid to invoice multiple time the same PO/SO line then I do not agree since we provide with a false information buyers/sellers and accountant.

**Comment by fclementic2c** [comment]
Well, you cannot send a draft invoice to a customer. For the SO the seller might think wrongly it has been invoiced. 

@jbaudoux Think about account accrual picking OCA module. This module intend to post accruals when goods have been delivered but not invoiced. 

No accrual are posted when qty received = qty invoice even when invoice are draft. 
It is non sense accounting wise. 
Don't you think?

**Comment by jbaudoux** [comment]
@fclementic2c You are not supposed to stay with your draft invoice. Either you validate it, or you delete it and the quantity will come back as to invoice in the SO/PO.
For PO invoice, you need to encode the accounting date and put it in the current period if you don't want to validate it immediately. (Btw, you anyway need to encode this date if you want to encode the real invoice date and it's in a previous period). Then your accrual will be correct.
For SO, why making a draft invoice and leave it not validated? But would be good to fill the invoice date at invoice generation from SO. Then you are sure your accrual will be correct.
Another solution is to use the OCA module that makes accrual of all draft invoices.

**Comment by Yenthe666** [comment]
Dear @fclementic2c,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
