### ISSUE TITLE
[11.0] Menú action don't work if sale_manager is not installed

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#23757]
Impacted versions:
11.0

Steps to reproduce:
1.- make a clean DB
2.- direct install point_of_sale (without sale_manager)
3.- click on point of sale menu
Current behavior:

Clicks don't work, till additional click on sale_manager install 

Expected behavior:

Can Use point_of_sale without sale_manager

**Comment by arafatx** [comment]
Sorry, I just wanna ask for my doubt. Is sale_manager an enterprise module ? Do you mean sale_management?

From the manifest of point_of_sale module. I can see POS depends on the sale management:

Screenshot
http://prntscr.com/iwqrii





--

**Comment by akevinieron** [comment]
I just try to reproduce your issue but everything works as expected. Can you say another details of your environment as Operating System, exact version of Python, etc

**Comment by dansanti** [comment]
solved with latest commits, thanks
