### ISSUE TITLE
odoo xmlrpc by php

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#23760]
i use odoo 10 ,on sale module, and i need to confirm sale ,to move form quotation to order sale via php page 
and i tried to use xmlrpc update but doesn't effect.
![screenshot from 2018-03-20 10-16-13](https://user-images.githubusercontent.com/34648267/37642973-275aeb2e-2c30-11e8-9473-4b972d5d39da.png)

**Comment by Yenthe666** [comment]
Hi @spectra10008,

Thanks for your report.
The Github tracker is only for bugs in the official code though, this is not the right place to ask questions.
Please do ask this question on the official help forums at help.odoo.com.

Regards,
Yenthe
