### ISSUE TITLE
[9.0] bug product: taxes vendor not display all the availables taxes

### ISSUE THREAD

**Issue by dlemireanybox** [odoo/odoo#23779]
**Impacted versions:**
[9.0]
**Context:**
purchase only installed

**Steps to reproduce:**
1) from product "A" create a vendor taxe "B"
2) save the product with taxe "B"

**Current behavior:**
after save, in the product "A" the vendor taxe value is erased and is blank
the new taxe "B" is not appeared in the list of availables taxes
the same problem occurs in setting of invoicing for the vendor taxe
**Expected behavior:**
the vendor taxe should have the customer taxe behavior
when create from a product or setting of invoicing=> not erased and appear in list

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment]
Hi @dlemireanybox,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
