### ISSUE TITLE
[10.0] odoo.conf - Enable workers and longpolling port  - Exception: bus.Bus unavailable

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#23770]
Impacted versions:
Odoo - 10.0, Centos 7 x64

Steps to reproduce: odoo.conf
workers = 1 # or more
longpolling_port = 8072

restart odoo

Current behavior: 
As soon as I start the chat, in the logs this error and chat does not work.

log odoo

2018-03-20 12:26:00,806 3885 ERROR bd odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 641, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 683, in dispatch
result = self._call_function(self.params)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
return checked_call(self.db, *args, kwargs)
File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
return f(dbname, args, **kwargs)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
result = self.endpoint(a, kw)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 941, in call
return self.method(*args, kw)
File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
response = f(args, *kw)
File "/usr/lib/python2.7/site-packages/odoo/addons/bus/controllers/main.py", line 35, in poll
raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable

Expected behavior:
should be all good

Video/Screenshot link (optional):

**Comment by arafatx** [comment]
Mine to share your server configuration ?

**Comment by collex100** [comment]
upstream oddo {
    server 127.0.0.1:8069;
}
upstream etherpad {
    server 127.0.0.1:9001;
}

server {
    listen 443 ssl http2;
    server_name mydomen.com;
    client_max_body_size 64m;
    access_log  /var/log/nginx/oddo.access.log;
    error_log   /var/log/nginx/oddo.error.log;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    ssl on;
    ssl_certificate    /etc/ssl/marker/ssl-bundle.crt;
    ssl_certificate_key /etc/ssl/marker/ssl-bundle.key;
    keepalive_timeout   600;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    location / {
	proxy_redirect off;
        proxy_pass  http://oddo;
    }

    location /pad {
      rewrite                /pad/(.*) /$1 break;
      rewrite                ^/pad$ /pad/ permanent;
      proxy_pass             http://localhost:9001/;
      proxy_redirect         / /pad/;
      proxy_set_header       Host $host;
      proxy_buffering off;
  }

    location /web/database {
        auth_basic           "O-ops! Password required";
        auth_basic_user_file /usr/share/nginx/odoo_pass;
        proxy_pass http://oddo;
    }

    location /sp-push-worker.js {
	root /usr/share/odoo/;
    }

    location /sp-push-manifest.json {
        root /usr/share/odoo/;
    }
    
    location ~* /web/static/ {
	#proxy_cache marker;
        #proxy_cache_valid 200 60m;
        #proxy_buffering on;
        #expires 864000;
        proxy_pass http://oddo;
    }

}

server {
    listen      80;
    server_name mydomen.com www.mydomen.com;
    rewrite ^(.*) https://$host$1 permanent;
}

server {
    listen 443;
    server_name www.mydomen.com;
    return 301 https://mydomen.com$request_uri;
    }

**Comment by collex100** [comment]
http://www.serpentcs.com/web/content/1980
13 page

2). Jasper Reports With Workers (multi process) :
When you wan't to use –workers (multi process) in jasper reports in V8 , then you faces errors like
“ EXCEPTION: [Errno 111] Connection refused (111, 'Connection refused') ” or
“ Exception: bus.Bus unavailable “ .
Solution:
At first install psycogreen python library. And after that uninstall im_chat module from your
database.It's successful worked with workers.

im_chat creates a problem with the multiprocessor. Known since the 8th version.

**Comment by collex100** [comment]
Corrected nginx while it works.
```
upstream odoochat {
 server 127.0.0.1:8072;
}

# Redirect longpoll requests to odoo longpolling port
	location /longpolling {
	proxy_pass http://odoochat;
	}
```

**Comment by baixinan** [comment]
good

**Comment by bellabeen** [comment]
How enable longpolling port on apache2?
        ProxyPass / http://10.23.6.134:8070/
        ProxyPassReverse / http://10.23.6.134:8070/
	ProxyPass /poll http://10.23.6.134:8073/
	ProxyPassReverse /poll http://10.23.6.134:8073/
I enable this but not work

**Comment by MosabAlhady** [comment]
No answer  ??

**Comment by intero-chz** [comment]
Odoo 10 isn't supported anymore. And there are some answers: you have to configure your proxy correctly to use the chat with multi worker setup. How to do that depends on your proxy software (eg. nginx or apache) and ofcourse the odoo config itself. There are a lot of examples out there already, don't use Odoo issues for that.
