### ISSUE TITLE
CRM - Oppertunities in combination with Multy-company setting 

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#23775]
**Impacted versions**:
11

**Steps to reproduce**:
Configure Different Sales Channels in different companies configured with multy-company setting

**Current behavior:**

- Creating Sales Channel X available for Company X
- Creating Sales Channel Y available for Company Y
- Contacts are NOT shared between companies
- If User X is assigned to Sales Channel X and Sales Channel Y and user X is logged in on Company X then user X sees both Sales Channel X and sales channel Y with all oppertunities and all stages. An right issue occurs when user X clicks on a contact in oppertunty on Sales Channel Y

**Expected behavior:**
When user X is logged in Company X it should NOT see oppertunities from Sales Channel Y related to Company Y (and visa versa)

Video/Screenshot link (optional):

**Comment by Patrickar** [comment]
What is the status of this issue?

**Comment by Yenthe666** [comment]
@Patrickar as long as there is no feedback on the issue there is nobody looking or working on it.
P.S: If you have an enterprise version you can report the bug at odoo.com/help
