### ISSUE TITLE
[11.0] The Prices of order lines not update when change price list and currency

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#23771]
**Impacted versions:**
11.0
**Steps to reproduce:**
- Multiple Sales Prices per Product = True
- Prices computed from formulas = True
- Multi-Currencies = True
- Set rate to currencies
-  Create  pricelist in other currency
- Crear sale order
- Add product
- Change pricelist

**Current behavior:**

The price of line not updated

**Expected behavior:**

The price of line is compute in the currency of price list current

Video/Screenshot link (optional):

[Video](https://youtu.be/xoGleHrTZow)

**Comment by maitaoriana** [comment]
@atpollmann

**Comment by cecchip** [comment]
The price of line is compute in the currency of price list current and not change pricelist  when select  client with other pricelist default

**Comment by krueger80** [comment]
We had the same reasoning as you @maitaoriana. We had open a ticket with Odoo (1807735). Here is a copy and paste of the discussion we had with support: https://docs.google.com/document/d/11SYhobpUiBfcsHZnOAObG4l6BaPnkMqrh1rW-4HVS04/edit?usp=sharing

In the end, this a how they designed it... as confusion as it can be with multi-currencies. I personally think the design is bad. Pricelist should be recorded at order line level to reflect the current behaviour.

**Comment by maitaoriana** [comment]
@cecchip I agree with you, it is a design problem. But i do not think that a problem like that can be solved in a stable version of odoo (11.0), but maybe in a next version.

FYI: A temporary solution could be add wizard to change currency and updated the lines.

**Comment by sswapnesh** [comment]
Hello All,
Adding PR https://github.com/odoo/odoo/pull/31535 for reference (For future versions)

**Comment by pedrobaeza** [comment]
Install OCA module `sale_order_price_recalculation` for having a button to recompute.

Closing as wishlist not possible on v11 and with the PR for new versions referenced.
