### ISSUE TITLE
[WEB] Editor html not saved %for correctly

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#23786]
**Impacted versions:**
11, tested on runbot
**Steps to reproduce:**
Go to email template, edit any template(sales order for example), and toggle to Code View on editor, paste next code:

https://pastebin.com/sSMf6T9e

toggle to Code View again, and code is other, not is original
**Current behavior:**
for is not save correctly
**Expected behavior:**
for save correctly on Editor HTML
**Video/Screenshot link (optional):**

Tooggle to Code View and paste code html
![image](https://user-images.githubusercontent.com/7775116/37694213-5c9411a4-2c93-11e8-8b19-bf7b889f4cbe.png)

Toggle Code View again and code html is other( for before table)
![image](https://user-images.githubusercontent.com/7775116/37694226-72c69370-2c93-11e8-855d-c2067d0205b3.png)

Toggle Code View again and code html is other( for before table)
![image](https://user-images.githubusercontent.com/7775116/37694229-778d3116-2c93-11e8-906d-e673eee419c9.png)

I try create template from module(on file xml) and same result.

Is related to #18903

**Comment by mart-e** [comment]
Hello,

This is unfortunately a limitation of our web editor.
It is made for HTML content but not Jinja.
This was already discussed back them at #4671

**Comment by celm1990** [comment]
Thanks for your answer.
PR #16726 is solution????

**Comment by mart-e** [comment]
I don't think it will avoid all errors but it should help a lot
