### ISSUE TITLE
[10.0] intermittent errors when initializing database

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#23781]
Impacted versions: 10.0

Steps to reproduce: `odoo -d dbname --stop-after-init` where dbname is an empty or non-existent database.

Current behavior: 

The above command fails intermittently with python 2.7.14 with error

`ProgrammingError: column res_company.sequence does not exist
LINE 2: ...          WHERE "res_company".id IN (1)  ORDER BY "res_compa...`

An complete error log is here: https://travis-ci.org/acsone/click-odoo/jobs/355525080

It might be the same issue as the one solved in https://github.com/odoo/odoo/commit/b62ba7ee1adc8e3c41040cafde30c2c93154ce69#diff-a7f3fa198325d9e70aede8b550b93b43, made for v11.

**Comment by Yenthe666** [comment]
@xmo-odoo could you have a look please?

**Comment by pedrobaeza** [comment]
@xmo-odoo maybe you can check this with a possible solution in #27747

**Comment by pedrobaeza** [comment]
@sbidoul now that the PR has been merged, you can check if there's no more this problem, and update the issue.

**Comment by sbidoul** [comment]
Looks good, thanks!
