### ISSUE TITLE
[9.0]vendor pricelists is not used for invoice

### ISSUE THREAD

**Issue by dlemireanybox** [odoo/odoo#23780]
**Impacted versions:**
[9.0]
**Context:**
purchase only installed

**Steps to reproduce:**
0) use purchase settings: "Allow using and importing vendor pricelists"
1) for a product with cost 5$, create a price for supplier "A" equal 100$
2) create invoice from this supplier
3) add quantity of 1 product

**Current behavior:**
the line price is equal 5$
**Expected behavior:**
the line price should be equal 100$
Video/Screenshot link (optional):

**Comment by intero-chz** [comment]
IIRC pricelists where never used in invoices. They are only used in sale/purchase orders.

**Comment by Yenthe666** [comment]
@dlemireanybox perhaps you have custom development or open source modules for this?

**Comment by dlemireanybox** [comment]
@intero-chz : as invoicing is installed with purchase module, if we create a purchase order with supplier price that seems regular to create invoice with same rules.

**Comment by intero-chz** [comment]
@dlemireanybox that maybe is true, but such a feature was never implemented in Odoo. You don't have a pricelist on invoices, so you don't have pricelist prices or costs.

**Comment by Yenthe666** [comment]
As mentioned, this is not the case. Pricelists are applied on sale and purchase orders.

**Comment by dlemireanybox** [comment]
I am new, where can I write suggestions for evolutions?

**Comment by dlemireanybox** [comment]
test

**Comment by Yenthe666** [comment]
Basically here on Github, they'll then be labeled wishlist or Odoo makes an internal task for it.
