### ISSUE TITLE
Timesheet_analysis report showing wrong total values

### ISSUE THREAD

**Issue by mcassuto** [odoo/odoo#2378]
- record and validate some timesheets for different users
- open the report Reporting \ Human Ressources \ Timesheet_analysis
- the total per user is correct
- the total line is wrong

**Comment by Yenthe666** [comment]
Hi @mcassuto,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
