### ISSUE TITLE
unreachable code after return statement in web_kanban

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#23793]
Impacted versions: 9 and 10
@ged-odoo
File odoo/addons/web_kanban/static/src/js/compatibility.js contains a return statement before the end of the code. This result in a warning message in JS console.

**Comment by Yenthe666** [comment]
Good catch - I made a PR to fix this issue. Waiting for approval from Odoo to get it merged in.

**Comment by mart-e** [comment]
Hello,

Thank you for the rport. This useless return was already removed in 11.0.
Please check our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean), we do not make code cleaning in stable version,
