### ISSUE TITLE
Domains with subfields don't evaluate properly

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#23808]
Impacted versions: tried on `10.0` and `11.0`

In a `search()` domain of the kind (A **OR** (X **AND** Y **AND** Z))

For the case of X, Y or Z having a subdomain to evaluate, A is discarded.

A example that can be tried in a runbot creating a `res.partner` `ir.filter`

(Left **OR** operand (A) should return _Agrolait_; Right **OR** operand (X AND Y AND Z) should return _Administrator_).

**No subfield:**
`["|",["id","in",[8]],"&","&",["email","=","admin@yourcompany.example.com"],["active","=",True],["user_ids","!=",False]]`

**It's ok.** Returns: _Agrolait_ and _Administrator_ partners.

**With subfield: (user_ids.active)**
`["|",["id","in",[8]],"&","&",["email","=","admin@yourcompany.example.com"],["active","=",True],["user_ids.active","!=",False]]`

**It's wrong**. Returns: _Administrator_ partner. It doesn't seem to evaluate the first operand of the **OR**. It should return also _Agrolait_

OPW: 1830250

**Comment by nim-odoo** [comment]
@rco-odoo @Elkasitu

**Comment by Elkasitu** [comment]
Hi @chienandalu,

I talked with @rco-odoo and unfortunately this bug is not fixable in a stable branch, it practically requires a whole refactoring of the `osv.expression` module as the `_auto_join` feature is improperly implemented, the code in `osv.expression` is very old and even if we could devise a nasty hack to fix it in stable branches, it would probably break business code everywhere (not just from odoo apps, but from third-party apps as well).

We've made a task to completely refactor and decouple domain resolution and query building, which will *hopefully* be done for Odoo 12 so that this no longer happens.

Sorry for the inconvenience.

cc @nim-odoo

**Comment by pedrobaeza** [comment]
Can you tell us a possible hack for performing the expression in 10/11?

**Comment by Yenthe666** [comment]
Hmm, good question @pedrobaeza. I'm amazed that I haven't been bitten with this one before (or I don't know yet). Quite a big one.

**Comment by Elkasitu** [comment]
@pedrobaeza You would have to modify https://github.com/odoo/odoo/blob/4c08b98c8a7ed43a6ef65f5a1eda9c0bb71901ec/odoo/models.py#L3682-L3731

So as to parse the `WHERE` clause and find the part that currently creates a cartesian product of two tables:

```sql
SELECT ... FROM res_partner, res_users WHERE res_partner.id = res_users.partner_id
```

and convert it to the appropriate JOIN for the type of field (potentially different for o2m, m2o, m2m)

```sql
SELECT ... FROM res_partner LEFT JOIN res_users ON res_partner.id = res_users.partner_id
```

but I wouldn't advise this as it might break not only standard Odoo modules but also third-party modules.

**Comment by pedrobaeza** [comment]
Yeah, I see... Well, we'll find an alternative domain expression.

One last thing: is there any possibility of detecting this situation and throw a log alert for at least being aware of the problem (the same way you have alerts for writing non-existing fields for example)?

**Comment by StefanRijnhart** [comment]
This is fixed by https://github.com/odoo/odoo/pull/25182

>>> session.env['res.partner'].search(["|",["id","in",[8]],"&","&",["email","=","admin@yourcompany.example.com"],["active","=",True],["user_ids","!=",False]])
res.partner(3, 8)
>>> session.env['res.partner'].search(["|",["id","in",[8]],"&","&",["email","=","admin@yourcompany.example.com"],["active","=",True],["user_ids.active","!=",False]])
res.partner(3, 8)

**Comment by StefanRijnhart** [comment]
Wait, I can't reproduce this without my patch on master. Is the example correct?
