### ISSUE TITLE
[7.0] Advanced Search in the Tasks from the Project module are case sensitive

### ISSUE THREAD

**Issue by sergioernestotostadosanchez** [odoo/odoo#2381]
## Good Day!

Thanks for the attention to this report. The issue consists as follows: when I do an _advanced search_ in the _Tasks_ from the _Project module_ with the filter _Assigned to_ as next **"Assigned to : contains : value"**, I detect that in distinct forms for the same value doesn't return the tasks belonging to 
that search criteria, in other words, is _case-sensitive_.
## How to reproduce

Now I describe steps to get in front the problem:
1. Enter to your **OpenERP (v7.0)**
2. Go to **Settings**
3. Select _Users_ Menu and create a new one, with minimal fields name and login
4. If we don't have installed Project module, install it. For this example, we will create a user called _"Juan Perez"_ with login _juan_
5. Go to the **Project** module
6. Select the menuitem **Tasks**, located in the left of the screen
7. Now, clic in the _Create_ button, and fill the task name (any you want) and select the user you create in step number 3 like value for **Assigned to**
8. Opctionally, create more tasks assigned to your created user
9. Select Tasks menuitem again
10. In the right top of the screen, clic on the arrow in the search bar to open search options and select the **Advanced Search**
11. Now select the option from the list called _Assigned to_, the _contains_ operator in the next list and the value **juan** in the textfield; do the search, it doesn't return any task, this is the main problem detected, so steps 5 and 6 explain other examples that should return needed tasks displayed in the screen
12. Without change the parameters, set the value **Juan** and execute search; it returns the tasks that contains Julio, the result that is supposed to be appearing in step 4
13. Another example is setting the value **juan p**, to it returns the supposed result for  step 4

This happens with both v7.0 and v8.0. To see the example explained here in video, I leave you the next link: https://www.youtube.com/watch?v=KvMdzCuenBU
## What I get

The value juan doesn't return any task, when is well proved that variations
for this value do it expected
## What I expect

The tasks  returned  for the value juan, due to many variations for this values
returns effectively the expected result; maybe this problem can be present in 
other similiar cases
## I suppose into the code

Researching inside the code, in the res_users.py file, line 357, is detected the comparison action for the value to search; I think this is due to the _if statements_ that are both using an operator parameter, when maybe could be enough only use the condition in the second _if statement_; this is only a suggested hint.

**Thanks a lot for your support, regards!**

**Comment by Yenthe666** [comment]
Hi @sergioernestotostadosanchez ,

Thank you for your (very detailed and neat!) bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
