### ISSUE TITLE
[11.0] helpdesk: Url not computed correctly when sending customer notification from a ticket- 404: page not found

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#23817]
Impacted versions:
11.0

Steps to reproduce:
- Configure Out going mail server
- Create a portal user with a valid email address
- Configure a mail template to stage new in helpdesk app
- Create new Ticket in order to new customer
- Send a new message in order to sent a customer notification

![image](https://user-images.githubusercontent.com/10233975/37748101-18790a00-2d48-11e8-8f85-85a16c33ba33.png)

- Open Recived mail and click on view ticket button

![image](https://user-images.githubusercontent.com/10233975/37748115-2feaa0cc-2d48-11e8-8c94-1992cd14d00c.png)

Current behavior:
The URL is not computed well

Expected behavior:
Get the correct url
Video/Screenshot link (optional):

Replicated in http://313508-11-0-5aedb8.runbot14.odoo.com/ticket/29

OPW 1830356

**Comment by hugho-ad** [comment]
@nim-odoo 

I tried to replicate again, and the issue was not solved yet
http://315390-11-0-6cfb54.runbot12.odoo.com/mail/view?message_id=10031

![image](https://user-images.githubusercontent.com/10233975/37987532-a30f85dc-31bb-11e8-9b15-95e90c3636dd.png)

replicated in http://315390-11-0-6cfb54.runbot12.odoo.com

**Comment by sswapnesh** [comment]
@hugho-ad 
Try to open URL where Database is preselected or start the server with `--db-filter`.
