### ISSUE TITLE
[10.0][11.0] hr_payslip: Accounting in payslip rules are not multicompany aware

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#23814]
### Impacted versions:
All

### Steps to reproduce:
- Install a **l10n_xx_hr_payroll** which includes information of the rules (it always install in the main company: **Company A** in this use case).
- Configure the accounting for the rules
- Create **Company B**
- Use the same salary rules for both companies, as **l10n_xx_hr_payroll** modules are not multicompany.

### Current behavior:
- **Company A** accounts are shown in **Company B** salary rules.
- If the accounts are changed in **Company B** rules, it also overrides **Company A** accounts, (which causes major confusions, and great mistakes if a payslip is run).
- A salary rule with **Company A** set on `company_id` can still be **seen** through Company B. which causes that it can be mistakenly _ran by a user in Company B_, with the _accounting of Company A_.

### Expected behavior:
- The accounting in Salary rules should behave as **Product Categories**, same categories for all companies but different accounts.

**Comment by gustavovalverde** [comment]
Ticket 1830754

**Comment by gustavovalverde** [comment]
As update based on the ticket:

My problem is not oriented to salary structures but to salary rules, as their use in multi-company is completely confusing and error prone, because:

1- If a salary rule has **Company A** set, the rule can still be **seen** through **Company B**.

2- If a salary rule has **Company A** set, it still allows to set **Company B accounts**. (which causes major confusions and mistakes).

3- If a salary rule has **Company A** accounting, a user in **Company B** can mistakenly run a Payslip using this salary rule with the **wrong accounts**.

Based on the suggestion of *duplicating* the rules, if an **l10n_xx_hr_payroll** module is updated (including its rules) it will just update the main_company, other companies rules have to be manually updated, because the same rule can't be used for multiple companies.

This is utterly complex and error prone.

A simple solution would be to have the same logic as in **res.partner** when being share in multiple companies. It's the same record, and depending on the user's actual company, just the accounting of that company is shown and used.

This has a great impact on implementations and updates dealing with multicompany environments, as it's painful to maintain.

cc: @qdp-odoo (as this is an accounting headache in the payroll)

**Comment by gustavovalverde** [comment]
Ticket closed with no solution or workaround.
![image](https://user-images.githubusercontent.com/16890942/39784641-1eaeffc8-52e7-11e8-9707-f9551e99af4d.png)

**Comment by Yenthe666** [comment]
Euh, that is honestly a shit response as he is not saying anything about any further action (although he wants you to think that though).
I'd honestly reply back on that and ask what the next step is. 👎

**Comment by Yenthe666** [comment]
Ugh, sorry to hear.. The downside is that now we have an open bug report here which is basically denied by Odoo itself while it might still be relevant for a future task.

**Comment by blaggacao** [comment]
@gustavovalverde Havn't, but I hear you clearly.

I would spec:

- Accounts and analytical accounts company dependent fields
- Rules company dependent model, with optional (inactive) rule for sharing those across companies.

**Comment by tivisse** [comment]
Done in master at https://github.com/odoo/odoo/commit/344877a0813a915344a230f1aaf1f932f2f9d5cb

Thanks.
