### ISSUE TITLE
[11.0] Oauth2 Google and FB

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#23812]
Impacted versions: 11 and 10(latest on git as of today)

Steps to reproduce:

Current behavior:
Tryingh to enable Oauth2 services send http://address to provider despite only using https:// on server causing errors saying it needs to use secure..

https://www.facebook.com/dialog/oauth?response_type=token&redirect_uri=http%3A%2F%2Fwww.kartalin.online%2Fauth_oauth%2Fsignin&client_id=292020387996559&state=%7B%22p%22%3A+2%2C+%22r%22%3A+%22http%253A%252F%252Fwww.kartalin.online%252Fweb%22%2C+%22d%22%3A+%22www.kartalin.online%22%7D&scope=public_profile%2Cemail

Same goes for google. and probibly even when linking website dashboard.

Expected behavior: Websshop front end users should be able to login... 

Video/Screenshot link (optional):

**Comment by kimasplund** [comment]
works fine in v10

**Comment by kimasplund** [comment]
Well now its broken in v10 to...
Look at the pretty arrows...

![facebook](https://user-images.githubusercontent.com/13152668/39083482-0c7abf68-456d-11e8-9387-676f954f4425.png)
![google](https://user-images.githubusercontent.com/13152668/39083483-0c961e8e-456d-11e8-9513-1456fb19c02d.png)

**Comment by kimasplund** [comment]
https://www.odoo.com/forum/help-1/question/google-oauth-issue-of-https-redirect-uri-mismatch-94071

Well seems this have been issue before?

**Comment by nhomar** [comment]
Hello.

at our website we use this feature by default, it is working fine, AFAICR you need to have properly set the ir.config parameter to the https and not the HTTP.

```

Key | web.base.url
-- | --
Value | https://ỳourdomain.com
```

Do not forget set the add the `web.base.url.freeze` parameter to avoid the change of this when admin login.

Other point is set the http on your load balancr to always redirect to https:// with that you avoid by mistake goes in into http by mistake.

I hope it helps.

**Comment by kimasplund** [comment]
Well i have the website set to https:// under company data. I cant really understand where i should have to put it again. and if i would need to start to dig in to the code somewhere i kind of think its a bugg :D 

![company](https://user-images.githubusercontent.com/13152668/39083760-ab77f680-4572-11e8-839c-a2194d891bf6.png)

But on the facebook login any http option can prob be removed completely as it is not supported anymore anyway.

![fb2](https://user-images.githubusercontent.com/13152668/39083728-ddbc606e-4571-11e8-9b8b-b3940f71a3f3.png)

**Comment by nhomar** [comment]
@kimasplund 

It is not a bug, it is into ir.config.parameter table (enable technical features and go to the proper menu under technical menu).

I am sorry but the leak of knowledge into the deployment process **cannot be considered a bug**.

As I just said, it is a parameter, and as I said, it is working exactly the same way since some time ago (we have that working).

Sometimes you must dig into the code in odoo to compliment what documentation says, due to this set of data I am mentioning is the 

Here they are.

![image](https://user-images.githubusercontent.com/338634/39083792-4c817c38-4530-11e8-8748-5811a82298f9.png)

**Comment by kimasplund** [comment]
But i have https://domain there and it still refuses to properly make the link

**Comment by Boss1669** [comment]
@kimasplund  hi kim have you found a solution to this i am facing problem as well, i also have https://domain in system parameter it still doesn't work

**Comment by Boss1669** [comment]
i found a solution if you running nginx reverse proxy add this line to configuration

proxy_set_header X-Forwarded-Host $host;

**Comment by kimasplund** [comment]
Thx Boss1669 
Works like a charm with that. 
Did not get it working before even by changing
