### ISSUE TITLE
Can not decorate a method that is already decorated with  @http.route

### ISSUE THREAD

**Issue by JVegaB** [odoo/odoo#23815]
Impacted versions:
    11.0

Steps to reproduce:
    Inherit a CustomerPortal controller from odoo.addons.portal.controllers.portal. Defining a route method. Then defining a decorator to extract and validate a parameter of the request object, If its correct return the normal execute of the decorated method, otherwise an error response will be instead. 

Decorate the route method like 
@http.route
@decorator
def method(self)

Current behavior:
when a request is sent to its route the method raise the followinf exception:
AssertionError: Method <bound method WebsiteAccount.token_authorization.<locals>.wrapper of <odoo.http.CustomerPortal (extended by WebsiteAccount)>> has not route defined.

Expected behavior:
to return the expected response of the method decorated only if the requests contains a valid value.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/34751857/37736453-9482bfe2-2d16-11e8-88f3-cf6d40a97a29.png)
![image](https://user-images.githubusercontent.com/34751857/37736476-a5003d54-2d16-11e8-856f-6162550c23bc.png)
![image](https://user-images.githubusercontent.com/34751857/37736539-c8f2637c-2d16-11e8-92af-2d00ab3bde1c.png)

**Comment by moylop260** [comment]
This is not a issue related with odoo itself...
Could you close it?

**Comment by JKE-be** [comment]
why not simply use a new auth_method?

```python
@http.route(..., auth='xunnel', ...)
def _test(self):
    retrun [1, 2, 3, None]

class ir_http(models.AbstractModel):
    _inherit = 'ir.http'

    @classmethod
    def _auth_method_xunnel(cls):
        user = request.httprequest.headers.get('Xunnel-Token')
        ...
```

And please use the forum for this kind of topic.
Issue Tracker is for issue into Odoo code base.
