### ISSUE TITLE
Website Builder / inserting "Code" does not work

### ISSUE THREAD

**Issue by blahmutz** [odoo/odoo#23828]
Impacted versions: 11

Steps to reproduce: 
- Edit any page
- click on the page to get the menu bar visible
- click on the first icon where you can chose "Normal", "Code", "Header 1", "Header 2", ... and select "Code"
- insert `<b>test</b>`

Current behavior:
it displays the unformatted code

Expected behavior:
i would expect that i can enter html/js code here which is getting executed/marked up

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
NOTE: I have edited main comment for showing the inserted code correctly.

@blahmutz for inserting directly HTML code, you have to click on Customize > HTML/CSS editor, and there you will be able to change at code level whatever you want, but the "Edit" option is a WYSIWYG editor that hides all that things on purpose.
