### ISSUE TITLE
Odoo 10 purple Kitchen Orders button

### ISSUE THREAD

**Issue by AMEKCapital** [odoo/odoo#23827]
Impacted versions: 10 enterprise 

Steps to reproduce:

Current behavior:
appear with no reason the kitchen order button become purple and don't send orders to kitchen and have to refresh many time to back green again, and internet and network all work and icons green

plz advice
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you pleaser try to reproduce it on runbot (http://runbot.odoo.com/runbot/repo/git-github-com-odoo-enterprise-7) and tell the exact steps followed?

**Comment by Yenthe666** [comment]
Closing this issue as there has been no response from the author and as 10.0 is no longer officially supported.
