### ISSUE TITLE
[10.0][bug] Installation "hr_expense" module error in zh_CN environment 

### ISSUE THREAD

**Issue by liweijie0812** [odoo/odoo#23820]
Impacted versions:10.0

Steps to reproduce: Installation "hr_expense" module error in zh_CN environment
```
Current behavior:
Video/Screenshot link (optional):
    self.determine_value(record)
  File "/app/odoo/fields.py", line 1012, in determine_value
    record._prefetch_field(self)
  File "/app/odoo/models.py", line 3065, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/app/odoo/addons/base/ir/ir_actions.py", line 322, in read
    values['help'] = self.env[model].get_empty_list_help(values.get('help', ""))
  File "/app/odoo/addons/hr_expense/models/hr_expense.py", line 321, in get_empty_list_help
    _('or send receipts by email to %s.') % (link,),
ValueError: unsupported format character '?' (0x53d1) at index 12
```
#. module: hr_expense
#: code:addons/hr_expense/models/hr_expense.py:305
#, python-format
msgid "or send receipts by email to %s."
msgstr "或者通过电子邮件向 % 发送收据。"

Expected behavior:
#. module: hr_expense
#: code:addons/hr_expense/models/hr_expense.py:305
#, python-format
msgid "or send receipts by email to %s."
msgstr "或者通过电子邮件向 %s 发送收据。"

**Comment by Yenthe666** [comment]
@mart-e this looks like another issue with the translation terms on Transifex.

**Comment by mart-e** [comment]
Hello,

Thanks for the contribution but please check [translation documentation](https://github.com/odoo/odoo/wiki/Translations), the translations are handled on [Transifex](https://transifex.com/odoo), not Github.

I have submitted your changes there, let me know if you have issues.

Thanks
