### ISSUE TITLE
Data in company field is not updated according to the Location's Company in stock quants - Intercompany Transfer is not working

### ISSUE THREAD

**Issue by burhan-vakharia** [odoo/odoo#23823]
Impacted versions: v10 community and Enterprise

Steps to reproduce:
1. Create an Odoo Community database with the Stock module installed.
2. Enable Multi Company and share the products.
3. Go to stock quants form view and add the company_id field in form view, so that you can check the value in it. - https://prnt.sc/iupwo1
3. With Company A user, create a new product (naming it Custom Product) type stockable and update its on-hand quantity to 10. Next check the inventory valuation, you will find the product at Wh/Stock. It is good till this step.
5. Now create an internal transfer of company A, Custom Product 10qty, Source will be WH/Stock and destination will be Inter-Company Transit.
6. The stock is available at this location hence you can Validate the transfer. 
7. Now again go to the Inventory valuation and open the quant for Custom product. The company field is not updated here. It will still show Company A. The transit location does not have any company and hence the company should get blank. - https://prnt.sc/iuq66d
8. What effect will happen if the company is not updated according to the location? There is a record rule on quant to show only current company quant and the quants which do not have any company.
Hence the stock manager of Company B is not able to see this quant. When he tries to create an internal transfer from Transit location > Company B location, the transfer stays in 'Awaiting Availability' state, even though the product is on the transit location.

In Odoo 11, the company_id field in stock quant is taken as a related field of location_id.company_id. Hence the company is updated every time and the inter-company warehouse is working good there.

Current behavior: The company_id field in stock.quant is not updated according to the location's company_id.

Expected behavior: The company_id field in stock.quant should update according to the location's company_id. It is working in Odoo v11 but not in Odoo v10.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @burhan-vakharia,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
