### ISSUE TITLE
[10.0 enterprise] Error when comparing with previous period (tax report) in a language containing special characters in month name

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#23836]
Impacted versions: 10.0 enterprise (not sure i have to post it here because it's related to enterprise modules)

Steps to reproduce: On Runbot, install fr_BE language. Change your user language to fr_BE and go to Comptabilité/Rapport/Rapport de taxes. Select to compare by month and compare with previous month. (Ensure February is in the previous compared month).

Current behavior: You have a big stacktrace error because it tries to "str('Février')" and you have unicode error

Expected behavior: No stacktrace

Video/Screenshot link (optional): https://youtu.be/HvOrjQSK0SI

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thanks a lot for your bug report. This is indeed a bug:
![image](https://user-images.githubusercontent.com/6352350/37781945-07a1a89a-2df2-11e8-8154-bf1da6cdc890.png)
@mart-e I think you're the best fit to have a look and fix this one?

Regards,
Yenthe

**Comment by gustavovalverde** [comment]
I thinks this also happens on other reports (pickings for example), maybe a general check would be good.

**Comment by mart-e** [comment]
Hello,

Should be fixed at https://github.com/odoo/enterprise/commit/0c6dde7f32084293bdccc8ec7974c8192e01af4b
