### ISSUE TITLE
V.7 & V.8 user password change 500 internal server error

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#2384]
In Odoo v.7 and v.8 when the admin changes a user password the system should expire/delete all sessions related to this user to avoid an internal server error the next time the user tries to use the system and most users doesn't understand that they have to clear the browser cookies for getting the system work.

to reproduce the issue:
1- login with the Admin
2- from settings > users > admin > more  > change the admin password

now the browser will throw the below 500 internal server error, you can get the system working by clearing the browser cookies .

```
Internal Server Error
{"message": "OpenERP Server Error", "code": 200, "data": {"debug": "Server Access denied.\nClient Traceback (most recent call last):\n File \"/opt/oe7/openerp/addons/web/http.py\", line 294, in dispatch\n r = method(self, **self.params)\n File \"/opt/oe7/openerp/addons/web/controllers/main.py\", line 592, in index\n lang = self.get_lang(req)\n File \"/opt/oe7/openerp/addons/web/controllers/main.py\", line 611, in get_lang\n current_lang = req.session._uid and req.session.get_context().get('lang', 'en_US') or 'en_US'\n File \"/opt/oe7/openerp/addons/web/session.py\", line 170, in get_context\n self.context = self.model('res.users').context_get() or {}\n File \"/opt/oe7/openerp/addons/web/session.py\", line 42, in proxy\n result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)\n File \"/opt/oe7/openerp/addons/web/session.py\", line 30, in proxy_method\n result = self.session.send(self.service_name, method, *args)\n File \"/opt/oe7/openerp/addons/web/session.py\", line 97, in send\n raise xmlrpclib.Fault('AccessDenied', openerp.tools.ustr(e))\nFault: <Fault AccessDenied: u'Access denied.'>\n", "fault_code": "AccessDenied", "type": "server_exception"}} 
```

Normally the system should instead expire / delete all the user sessions from the DB and logout the user.

Regards,

**Comment by Yenthe666** [comment]
Hi @mohamedhagag,

Thank you for your report.
This issues has been fixed in the meanwhile. You will be logged out, redirect to the login and everything is cleared.

Regards,
Yenthe
