### ISSUE TITLE
[11.0] odoo Chinese translation is a mess!

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#23841]
Impacted versions:
11.0
Steps to reproduce:
install odoo website_sale_comparison with demo data
Current behavior:
on website shop comparison page, It is normal in English, but a mess in Chinese.
Expected behavior:
Correct translation, are you using machine translation? @mart-e 
Video/Screenshot link (optional):

<img width="979" alt="9df3ad5656e119d0cf18eec7a26a35ef" src="https://user-images.githubusercontent.com/1243299/37812250-0729faae-2e9a-11e8-90df-8b97efaff238.png">

**Comment by jlzhou** [comment]
The correct translation should be:
<i class="fa fa-shopping-cart"/>&amp;nbsp;添加到购物车

**Comment by jlzhou** [comment]
<img width="561" alt="09bc8223aa8cc0a5f30e27d448c742d2" src="https://user-images.githubusercontent.com/1243299/37812848-1c50835a-2e9d-11e8-90ca-99893aefe702.png">

**Comment by Yenthe666** [comment]
@mart-e it looks like there are yet more problems with the Chinese translations from the external company. Perhaps it is time to let them know the quality isn't terrific?

**Comment by mart-e** [comment]
Hello,

>  Correct translation, are you using machine translation? @mart-e

No, human translation only (ironically, this kind of error would not happen with a machine translation).
Thank you for the report, [it is corrected](https://www.transifex.com/odoo/odoo-11/translate/#zh_CN/website_sale_comparison/119306980?q=add%20to%20cart).

> Perhaps it is time to let them know the quality isn't terrific?

As stated in [the first issue](https://github.com/odoo/odoo/issues/23720#issuecomment-374131600), we already did. We are investigating.
So far, I have received 6 different terms that were not correctly translated. This is far from being a problematic number. No offence, but I am sure you have already made more than 6 errors in Odoo translations.
Please do report problems you find but this is not very constructive.
Thank you to use Transifex to report Transifex problems. Create issues on the translations you find, pinging the translator and myself.
