### ISSUE TITLE
[11CE] avg attribute in field tag works like sum not avg 

### ISSUE THREAD

**Issue by grzegorz-openglobe** [odoo/odoo#23854]
Impacted versions: 11 (issue related to issue #21673)

Steps to reproduce: Write XML view with avg attribute in float field tag.

Current behavior: All values are summed on grouping bar when you group records in tree view. They have avg value only at the bottom aggregation. And this average is only from grouping values (but grouping values are sums instead of average).

Expected behavior: I seem when you use avg option all aggregation should be average.

Video/Screenshot link (optional):
![avg_option](https://user-images.githubusercontent.com/7620435/37833910-e1f46a7c-2eac-11e8-8888-34f3acfc6b53.png)

**Comment by xmo-odoo** [comment]
That is intended behaviour, the group-wise and list-wise aggregates are completely different, the group-wise aggregation is performed server-side and controlled by `group_operator` on the model field while the list-wise aggregation is performed client-side and more indicative.

The list-wise aggregation may also give odd/unexpected results in the presence of groups as it works on unweighted group values e.g. in your screenshot you have 4 groups with "invoiced" values 36, 26, 6 and 0 so the list-wise average is 17 while an other possibility would have been 1.66 (the average of all 41 selected timesheets).
