### ISSUE TITLE
Odoo Voip calling issue 

### ISSUE THREAD

**Issue by sandeepbrst** [odoo/odoo#23869]
I have added Voip module in odoo 11 comunity verssion and when clicking on Audio/Video Call it showing error..
Failed to access to media: SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
as my app is currnetly running on IP.

**Comment by Yenthe666** [comment]
Hi @sandeepbrst,

Which app exactly are you using? What Odoo version or you on? How do you reproduce this?
We really need more information and I've got a feeling that you're not using an Odoo official app as VOIP from Odoo is an enterprise module.

**Comment by sandeepbrst** [comment]
PLease see this screenshot.
![image](https://user-images.githubusercontent.com/31003996/37890957-1ebe4398-30f0-11e8-9818-1634d926ea0c.png)

and this is the module.
https://www.odoo.com/apps/modules/11.0/voip_sip_webrtc/

**Comment by Yenthe666** [comment]
Hi @sandeepbrst,

Sorry but the Odoo issue tracker is only for bugs in default Odoo code, not in third party apps.
Please contact the author of the app and ask them to fix it (steven@sythiltech.com.au)

Regards,
Yenthe

**Comment by joglomedia** [comment]
@sandeepbrst it seems that you must use secure protocol (https) for your odoo web
