### ISSUE TITLE
Odoo 11.0: Product Categories field display_name not translateable

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#23867]
Impacted versions:
Odoo 11.0-20180324 (Community Edition)

Current behavior:
Odoo uses the display_name instead of the name field (which makes perfectly sense) to display the product category name in the product category tree view and in the product template form view (
General Information tab), and probably even in more views. But the field display_name is not translateable and therefore the product categories are always shown in English despite of any available translations.
Field Definition:
![selection_029](https://user-images.githubusercontent.com/1814941/37878392-ff6edb06-3068-11e8-8d05-6af7d924eb9e.png)

Product Category Tree View (name field added to see the point):
![selection_027](https://user-images.githubusercontent.com/1814941/37878394-0b60f7f0-3069-11e8-8ab0-7dd65df8d6b7.png)

Product Category in the product form view:
![selection_030](https://user-images.githubusercontent.com/1814941/37878400-1c7eb57c-3069-11e8-9e7d-6d375c778a7b.png)

Expected behavior:
Show the translated value in the display_name and therefore make the field translateable.

**Comment by treviser** [comment]
I'm actually asking myself if this is not a generic issue for all display_name fields?

**Comment by gustavovalverde** [comment]
Same as #22060

**Comment by RoelAdriaans** [comment]
We have this issue with client, raised enterprise ticket; 1863536.

**Comment by mart-e** [comment]
Closing as duplicates of #22060.
This is not linked to the display_name but a limitation of the framework, you can't have, at the same time, a field that is 
- translatable
- computed
- stored
You must choose two.

**Comment by pedrobaeza** [comment]
Wonderful summary!
