### ISSUE TITLE
<xpath position="attributes"/> seems affects only node matching first

### ISSUE THREAD

**Issue by eternalharvest** [odoo/odoo#23862]
Impacted versions:
11.0 (maybe all version)

Steps to reproduce:

Create new plugin and add following template
```xml
<template id="custom_report_saleorder_document" inherit_id="sale.report_saleorder_document">
    <xpath expr="//thead//th[position()=3 or position()=4 or position()=6]" position="attributes">
	<attribute name="style">min-width: 3em;</attribute>
    </xpath>
</template>
```

Current behavior:

Only affect the node matching first.
I think it makes confusion if developer had thought that there is only one match and if xpath matched multiple elements unexpectedly. Actually, i was confused because the matched element is not same as I thought.
Actually, I was confused because the matched elements were different from what I thought.

Expected behavior:
Affect all of the node matched.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this is the intended behavior. Only first match is selected. Otherwise, it can have side effects not expected. If you want to have multiple changes, you have to add as much specific selectors as you need. The key is to use an unique selector that matches the wanted node.
