### ISSUE TITLE
[11.0] account.move unlink performance related issue

### ISSUE THREAD

**Issue by cantecim** [odoo/odoo#23863]
Hello everyone, 

why this line is inside the loop?

https://github.com/odoo/odoo/blob/132c7e75e57321c77aac9250a2587c74c5da7857/addons/account/models/account_move.py#L1364

We were removing 100k~ account.move.line records for testing purposes. It took ages. So we do some little investigation and saw this, we took out from the loop the process duration became minutes from hours.

Regards from Projet

**Comment by gustavovalverde** [comment]
Well, this line is necessary as an account.move.line can't be modified if it's inside inside the lock date range. If this causes a performance issue, that's a complete different thing, but this validation is needed.

**Comment by gdgellatly** [comment]
@gustavovalverde I think you missed the point.  He is not saying the check is not necessary, it just isn't necessary 100,000 times.  Looks like a clear mistake, should be outdented one tab.  @cantecim Just make a PR, pretty clear error.

**Comment by Yenthe666** [comment]
@gdgellatly good correction on the spaces. 😉 I made a PR to handle it.

**Comment by cantecim** [comment]
Hello guys, @gdgellatly thanks for the clarification. I just needed to make sure there isn't any special case to put that in the loop. @Yenthe666 thanks for the PR
