### ISSUE TITLE
Please help me. In Odoo 11, what is the table account_config_settings replaced with?

### ISSUE THREAD

**Issue by sngnt** [odoo/odoo#23888]
Impacted versions: Odoo 11 CE

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sngnt,

The Github tracker is only for bugs in the official Odoo code. This is not the right place to ask questions, you can do this on the official help forums at help.odoo.com.
Anyways, to answer your question, all configuration settings are now stored in `res.config.settings`.

Regards,
Yenthe

**Comment by sngnt** [comment]
Thanks for your kind help!
Regards,
Sngnt
