### ISSUE TITLE
User's name is lost on message_post when using non-latin caracters in name

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#2388]
We loose sender name in ir_mail_server.encode_rfc2822_address_header.
It expects email to be "Non-latin name" email@company.com. 
But in mail_message._get_default_from calls email.utils.formataddr((this.name, this.email)) and it does not return double quotes thus dropping person name completely from headers. When latin names are used it's ok but as soon as non-latin is used in person's name his name is lost from headers exactly at ir_mail_server.encode_rfc2822_address_header.

Here is my fix (remove double quotes as they are anyway not passed):
# name_with_email_pattern = re.compile(r'("[^@]+")\s*<([^ ,<@]+@[^> ,]+)>')

name_with_email_pattern = re.compile(r'([^@]+)\s*<([^ ,<@]+@[^> ,]+)>')

**Comment by Yenthe666** [comment]
Hi @litnimax,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
