### ISSUE TITLE
Odoo supports multiple companies. Does each company have its own domain name and website in a database?

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23894]
Impacted versions:
10.11
Steps to reproduce:
I found that Odoo, in a database, doesn't seem to support different domains and can open different websites.

If I want to do this, can I achieve it?

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Hello.

This is not a supported feature officially on v11.0 may be for the next version but yet in development.

I hope this helps you to set a proper road map on your side.

Regards.
