### ISSUE TITLE
[11.0] Multi-company: Partners visible for all companies although Common Contact Book not selected

### ISSUE THREAD

**Issue by salmemik** [odoo/odoo#23890]
Impacted versions: 11 (I'm using Community edition)

Steps to reproduce:
- Activate Multi-company configuration from General Settings but do NOT select sub-selection "Common Contact Book"
- Create parent company "Company 1" and its child company "Child Company"
- Create Test User for Child Company
- Create Customer 1 for Company 1 and Customer 2 for Child Company

Current behavior:
- Test User can see also parent Company 1 customers even it was restricted in General Settings 

Expected behavior:
- Test User should see only Child Company customers

Video/Screenshot link (optional):
<img width="1185" alt="customers_-_odoo" src="https://user-images.githubusercontent.com/11749898/37914149-3ae06e82-311f-11e8-9e10-c453a74119a7.png">
<img width="1183" alt="customer_2_-_odoo" src="https://user-images.githubusercontent.com/11749898/37914150-3b0d55be-311f-11e8-8ccd-86880ea4226f.png">
<img width="1142" alt="customer_1_-_odoo" src="https://user-images.githubusercontent.com/11749898/37914151-3b2dcf6a-311f-11e8-8fb8-2aecd64865d4.png">
<img width="456" alt="test_user_-_odoo" src="https://user-images.githubusercontent.com/11749898/37914153-3b4e7e5e-311f-11e8-84a2-6757651bea67.png">
<img width="1103" alt="settings_-_odoo" src="https://user-images.githubusercontent.com/11749898/37914154-3b714bbe-311f-11e8-91e8-3697925ac29c.png">

**Comment by pedrobaeza** [comment]
I face this the other day also. The partner multi-company rule is not active by default.

**Comment by pedrobaeza** [comment]
OK, seeing the commit https://github.com/odoo/odoo/commit/275234c06796ababf5bfb5356e8d216c8aea81c7 it seems by default now are shared. Please try to uncheck option in configuration "Share partners to all companies", and it it works, then close this issue.

**Comment by salmemik** [comment]
Could you tell more detailed where I can find that configuration "Share partners to all companies" that I need to uncheck? Do I need to upgrade some module before that? My technical skills are quite limited.. :)

**Comment by pedrobaeza** [comment]
OK, I can directly confirm that is correct, so I close the issue.

![seleccion_003](https://user-images.githubusercontent.com/7165771/37916085-4462b180-311b-11e8-9e05-6309805c870c.png)

**Comment by salmemik** [comment]
So have you tested with version 11 that Partners are NOT visible for all child companies if you have unchecked those selections? That was my issue in the first place that I cannot hide partners even if I uncheck those options.

**Comment by salmemik** [comment]
@pedrobaeza, how can I reopen this issue because in my opinion the bug still exist. I have selected partners to be not shared and those still are. Please check my initial issue description again. Products and orders are correctly hidden from other companies but customers are not.

**Comment by salmemik** [comment]
There is also similar visibility issue concerning Lots/Serial Numbers: https://github.com/odoo/odoo/issues/23889

**Comment by pedrobaeza** [comment]
Yeah, it's working, but you have to try with other user that is not admin, as admin ignores that record rules. As a general statement, never use admin user for adding transactional records, and most if you have multi-company.

**Comment by salmemik** [comment]
I used test user - not admin. Please see the description & screenshots from my initial issue description.  This issue was reported to me and then I tested and got the same results. But now you tested it with version 11 Commynity and you could hide partners by just unchecking those general setting options. Right?

**Comment by pedrobaeza** [comment]
Yeah, that's it. Please try on runbot. Maybe you have on outdated version.

**Comment by pedrobaeza** [comment]
You can see the record rule here: https://github.com/odoo/odoo/commit/275234c06796ababf5bfb5356e8d216c8aea81c7#diff-f1c7d6b4c3ff3a5faa7953f53afe6e4bR52

If it doesn't fit your needs, you can adapt it, as it's a noupdate record.
