### ISSUE TITLE
Procurement request results in picking with wrong date

### ISSUE THREAD

**Issue by flyingL123** [odoo/odoo#23906]
The following issue is occurring on `saas-14`:

When I go to a product and click the "Procurement Request" button, why does the resulting picking always have a date 1 day earlier than the scheduled date? For example, in the first screenshot I am making a new procurement and you can see the date is set to 3/23/2018:

![screenshot1](https://user-images.githubusercontent.com/2486712/37973989-bce895d2-31a9-11e8-984b-3184646e93c2.png)

In the second screenshot, you can see the resulting picking has a date of 3/22/2018:

![screenshot2](https://user-images.githubusercontent.com/2486712/37974011-caa8c61a-31a9-11e8-8f59-82d263f81287.png)

I think this might be a bug having to do with timezones. The planned date is just a date field, not datetime, so it's getting set to 3/23/2018 00:00:00 UTC. Then the picking uses a datetime field and converts it to Eastern Time, which subtracts 4 hours and becomes 3/22/2018 20:00:00.

Also, just to clarify, there is no RFQ or PO involved in this process at all, so I don't think this has anything to do with 'lead times' or anything like that. The route I am selecting on the `make.procurement` is set to simply create a picking. The picking that is created has the wrong date.

**Comment by sle-odoo** [comment]
Hi,
saas-14 isn't supported anymore and this wizard is now replaced by the replenish button on the product form. If there's an issue with it feel free to open  new issue.

Regards
