### ISSUE TITLE
Odoo 11 fails to alert user on Fatal error out of memory.

### ISSUE THREAD

**Issue by chris001** [odoo/odoo#23909]
Impacted versions: 11.0

Steps to reproduce: 
https://github.com/Yenthe666/InstallScript/issues/80#issuecomment-376424256

Current behavior:
* Odoo 11 silently fails whatever operation the use requested.
* The user never knows the true cause of why the Odoo 11 software failed to do what the user is requesting.
* Odoo 11 does not tell user when `lessc` and `wkhtmltopdf` encounter fatal error "Out Of Memory".
* Odoo 11 **_probably_** also does not tell user when its own code encounters fatal error "Out of Memory". Verify this with tests.

Expected behavior:
* Odoo 11 should display some sort of toaster or popup alert message to the user, "FATAL: Out of Memory while trying to render css with node-less", "FATAL: Out of memory when trying to render PDF with WKHTMLtoPDF".
* Odoo 11 should display to the user a clear runtime warning fatal error message, when it encounters fatal runtime errors due to having run out of RAM during any operation (style or pdf rendering, or anything else typically memory intensive, such as large reports, etc). 
* Users shouldn't be left wondering why their odoo is malfunctioning, and forced to guess, "that web css style just failed, maybe odoo needs more RAM? But why didn't it show an error message on the browser?!" 
* Odoo should clearly communicate, "I just ran out of RAM, so you really should add more RAM, whatever it was you just tried to do, it failed because of lack of RAM."

Video/Screenshot link (optional):
See https://github.com/Yenthe666/InstallScript/issues/80 for full details how to reproduce this step by step.
Key details: install odoo 11, and run it on a virtual machine with 1 CPU, 1.0 GB RAM.
Original poster, @AyaYousef would surely make a video demonstrating this silent crash, if you ask him.

**Comment by Yenthe666** [comment]
Hi @xmo-odoo, @odony and @mart-e,

This is something that I've seen happening multiple times on people that use my script or people that have very little RAM.
Can we add in a safety check to improve/fix this behaviour? I'm sure one of you guys can give some good framework feedback about this.

Regards,
Yenthe

**Comment by mart-e** [comment]
Hello,

Odoo User != Server Administrator. I don't think this kind of server information such as memory consumption should be revealed to the user.
It is the job of the sysadmin to detect problems if the server is not powerful enough for the application installed on it.

**Comment by Yenthe666** [comment]
@mart-e it shouldn't persé show the RAM and server specs. It should give a clear indicator that this is the problem or a graceful fail.
@Elkasitu you're a bit fast with closing here, no? 😉

**Comment by chris001** [comment]
* One thing to keep in mind, many users self-install this Odoo app, and don't have a dedicated sys admin to monitor the system, so they're counting on the Odoo app itself to communicate clearly and quickly to them, of serious system failures.
* If you don't want to show a detailed technical popup/toaster to the user, and just blame the sys admin, fine, but there are alternative solutions to this problem (silent failure of odoo causing massive wasted time on technical users without professional sys admin training, trying to track down the cause):
1. Show a more vague popup/toaster message to the web user. "Your Odoo has encountered a system error. Please contact your system administrator to address this."
2. On FATAL out of memory errors, and other FATAL errors, send a silent EMAIL message, FROM the odoo system, TO the sys admin email (the email address of the first user in odoo, named "Administrator").

**Comment by mart-e** [comment]
> One thing to keep in mind, many users self-install this Odoo app

Maybe the marketing department will make you think Odoo is as easy to install as any desktop application on your computer but this is a bad idea to consider you can just "install and leave it". Sorry to disagree, but I believe you need some minimal technical knowledge to manage an Odoo installation (but I know this is not a opinion everybody agrees on).

> Show a simple, clear, popup/toaster message to the web user.

Showing a clear error instead of a traceback or hiding the failure is always a good idea. The kind of improvement we can accept.
