### ISSUE TITLE
[BUG]App name cannot display localized name

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23910]
Impacted versions:
10,11.0
Steps to reproduce:
Install a new database, the application name is the Chinese name, this is no problem.
After entering the developer mode and updating the application list, all module names have become English.
Even if I reload the translation, it has no effect.
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![qq20180328-092755](https://user-images.githubusercontent.com/5398273/38003496-5735df58-326a-11e8-84ac-331e90faa9af.png)

**Comment by sum1201** [comment]
@Yenthe666  Why no man reply me ?

**Comment by Yenthe666** [comment]
@sum1201 community bug reports are handled in a best effort. There are even bug reports that have been open for over 2 years. If you have an enterprise license you can escalate your issue through odoo.com/help

**Comment by sum1201** [comment]
@Yenthe666  enterprise ticket : 1832796
thanks

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!

**Comment by kebeclibre** [comment]
@sum1201 
Hi,

I couldn't reproduce the issue
The database I use in the video has been made with /web/database/manager with language Chinese/CN

https://drive.google.com/file/d/1VbH63x_HHus_iv9AaTBIpwC5n462Tete/view

**Comment by sum1201** [comment]
@kebeclibre 
https://youtu.be/e2Rbt_CxMgY
