### ISSUE TITLE
heloo odoo develpoer in need help "      i need to show related and relation fields in Qweb report when i use " o.myfields i see just the name of relations in my report

### ISSUE THREAD

**Issue by osamaIT** [odoo/odoo#23926]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @osamaIT,

Thanks for the issue but Github is only for bugs in the official Odoo code. 
You can ask questions on the official forum at help.odoo.com

Regards,
Yenthe

**Comment by osamaIT** [comment]
i need to ask but i cant do it , what is karma requirment in help.odoo.com

**Comment by Yenthe666** [comment]
Hi,

You need to verify your email in order to get enough karma for posting questions. This I to combat spam users.
