### ISSUE TITLE
[8.0] help: editing a question looses the tags

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#2393]
When I edit a question of help.odoo.com, the tags widget is not populated with the existing tags, which means that it is very easy to loose the tags when editing to fix a typo.

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

This issue is no longer present in the latest Odoo codebase.
This bug has been around for quite a while though. :smile: 

Regards,
Yenthe
