### ISSUE TITLE
[Odoo.com] QUESTION/WISHLIST: ReactJS Use in Odoo User Documentation. Are there plans on using ReactJS in Odoo Website?

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#23931]
<h1>Impacted versions:</h1>
Master/Odoo.com
<h1>Steps to reproduce:</h1>
In chrome, visit:<br/>
<a href="view-source:https://www.odoo.com/documentation/user/11.0/index.html">view-source:https://www.odoo.com/documentation/user/11.0/index.html</a>
<h1>Current behavior:</h1>
Line 31 of index.html includes react.js:<br/>
```    <script type="text/javascript" src="_static/react.min.js"></script>```
<h1>Question:</h1>
Are there plans to use react.js in the website builder, allowing for ReactJS components and themes in Odoo website?

**Comment by Yenthe666** [comment]
Hi @lukebranch,

I don't think there is any idea for this.
@JKE-be can answer this though.

**Comment by JKE-be** [comment]
Hello,

No, actually there is no plan to use react.js

Best regards
