### ISSUE TITLE
Qweb-html exceptions raised as Internal Server Error

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#23946]
Impacted versions: 11

Steps to reproduce:

1. create report with report_type="qweb-html"
2. customize method get_report_values() like this
   
```
    @api.model
    def get_report_values(self, docids, data=None):
        ...
        raise ValidationError('information for user')
        ...
        return docargs
```
Current behavior:

**Internal Server Error**

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Expected behavior:

Message wizard: "Odoo Server Error"

**Comment by pedrobaeza** [comment]
At that level the exception can't be processed the way you want, so you will need to find another way of popping up a message to the user, like a wizard or similar.

**Comment by zbik2607** [comment]
But ... when report_type="qweb-pdf" exception is processed ok.

**Comment by pedrobaeza** [comment]
Yeah, but it's something inherent the way this is done internally.

**Comment by zbik2607** [comment]
Is a big problem at least raise werkzeug.eceptions.HTTPException in web/controller/main.py, in method report_routes?

**Comment by pedrobaeza** [comment]
Well, I haven't dug enough on this, but if you want that, try to do it and propose a PR improving that part.
