### ISSUE TITLE
Why we have this restriction on Product UoM change in accounting?

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#23949]
https://github.com/odoo/odoo/blob/1631889e917b29066e4fb8f2d851723927bd35ff/addons/account/models/product.py#L40

https://github.com/odoo/odoo/blob/1631889e917b29066e4fb8f2d851723927bd35ff/addons/account/models/product.py#L51

Hi @fpodoo @odony 

Sorry for interruption, but I wonder why we overridden the write function to put such restriction ?? 
BTW there's a comment by odoo developer asking the same question.

Why we can't change the PO UoM if we have journal items related to this product .

Regards,

**Comment by Yenthe666** [comment]
@simongoffin or @mart-e why is this restriction there? Could you guys elaborate?

**Comment by mart-e** [comment]
Why not asking the guy who wrote the code instead of pinging random people? :wink: 

@qdp-odoo is it a port of the infamous 8.0 constraint on product?

https://github.com/odoo/odoo/blob/8.0/addons/product/product.py#L763-L768

**Comment by qdp-odoo** [comment]
@mart-e Well, considering that I was the one who wrote that 
```#TODO: really? i don't see the reason we'd need that constraint.. ``` I don't know what to answer, except that I still have the feeling this constraint is useless.

**Comment by Yenthe666** [comment]
So can we conclude it can be removed?

**Comment by mart-e** [comment]
> Well, considering that I was the one who wrote that

Yes but it was not present before v9 accounting, so is the reason lost in the development limbos?
https://github.com/odoo/odoo/commit/c04065abd8f62c9a211c8fa824f5eecf68e61b73#r20844972

If I recall correctly, in 8.0 we had the constraint on product (the above link). It was kind of painful (preventing to modify the category just after creating it, even if never used) and we tried to move it to the different modules to restrict the changes as soon as it was used (to avoid messing up the history).
Now, in the account override, I don't see the category verification so, not sure if the same thing.

> So can we conclude it can be removed?

I am sure you can guess the answer :wink:

**Comment by Yenthe666** [comment]
I'm going to go ahead and guess that we can remove this whole function but in the master version? 😉

**Comment by wtaferner** [comment]
@mart-e @qdp-odoo @Yenthe666 @sle-odoo 
I am pretty sure it had/has something to do with the stock modules and some assumptions which are probably now not existent anymore, but maybe @jco-odoo has some memory?! I was not checking the history but I know that there was from now and then confusion between the po_uom and the uom of a product...

**Comment by jco-odoo** [comment]
I think it is indeed something very old and there must have been a reason behind.  Maybe just because this way it did not let you change the UoM category on a product just like that.

**Comment by Yenthe666** [comment]
@jco-odoo would you too be fine with a removal though? If we do this in `master` and if there would be an issue with this it would come up before it lands in a stable version. To me it looks like unuseful code (at this point).

**Comment by jco-odoo** [comment]
Check at least we can not set inconsistent uoms of different categories, ...

**Comment by mohamedhagag** [comment]
Hi all, 
As I can see, we all agree that the constraint should apply only on inconsistent UoMs.
Then we should restrict not on journal entries existence but on stock moves, so if we have stock moves for this product, then we can not change the UoM to one out of the category.
Regards,

**Comment by gdgellatly** [comment]
From memory I can't remember why it applies to uom_po_id, but doesn't account move line record quantity without UoM and then use it in certain reports.

**Comment by nhomar** [comment]
I remember like yesterday.

There was a full discussion about some constraints, but several of them where anoying and incorrectly done (like the uom_po_id) I do not knwo why they were removed (and I realize too late).

Specifically the uom_po_id should not be blocked only the uom_id.

**Comment by mohamedhagag** [comment]
Dears,
I was going to ask for a way to override this function because normal override will still raise an error and rewriting the write() function will remove other overrides .

But I remembered the product_uom_change_fix module and searched for it which is made by odoomrp here: 
 https://github.com/odoomrp/odoomrp-utils/blob/9.0/product_uom_change_fix/models/product.py

I will port to 10.0 and try to make a PR to odoomrp's repo or should we put it under OCA's one ?!

Regards,

**Comment by mohamedhagag** [comment]
Here's a fast fix based on the mentioned @odoomrp 's module that's tested and works fine.
https://github.com/mohamedhagag/dvit-odoo/tree/10.0/dvit_product_uom_change_fix

I'm waiting for a suggestion to the best repo to make the PR.

**Comment by nhomar** [comment]
>> I'm waiting for a suggestion to the best repo to make the PR.

odoo/odoo#10.0 can be a good place, but I recomend check your change do not need anything to be forward ported to 11.0 if yes, then try to make 1 PR and beware to propose the change in 11.0.

**Comment by mohamedhagag** [comment]
AFAIK, Odoo will not accept such PR in released stable versions like 9, 10, 11 and they will only for master .

**Comment by nhomar** [comment]
>> AFAIK, Odoo will not accept such PR in released stable versions like 9, 10, 11 and they will only for master .

This do not change the current datamodel and do not need update the data structure, and this make sense from a technical and functional perspective, try the PR and then we discuss there (the stable policy is other story and you are maybe right) but let's try.

**Comment by Yenthe666** [comment]
@nhomar this will not make it in 9.0/10.0 or 11.0. This will only make it in master, 99% sure. See also my earlier comment about the whole function:

> I'm going to go ahead and guess that we can remove this whole function but in the master version?

**Comment by nhomar** [comment]
@Yenthe666 Then go for master, What I am sure of is that "remove it all" is not the way, I am worried left unclean verification, but at least for uom_po_id it should be in the same category of unit of measures.

BUt , nice, master is ok for me (even if I am pretty sure it can be done on >v10)

**Comment by nhomar** [comment]
I think we can close this issue because it is more a question, but for master this constraint can be improved a little.

**tip** (do this with adult supervision).

You can change the uom with the product deactivated, but remember you will need to set properly with a server action the new uom into the stock.move and stock.move lines and IF with the new unit of measure the cost is different, you will need to rectify your accounting also properly **tip2** product_id is into the account move lines on v11 now).



Regards.

**Comment by sswapnesh** [comment]
Removed in v11 @ 85f8e4761b9ad1d05ed787de4235fbbdfd33d7dd
