### ISSUE TITLE
[Question]Proper way to start web listener with Odoo?

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#23950]
Impacted versions:
11.0
I've asked on odoo-forum, on stack, but became no answer. So I'll ask here - sorry if it bothers you.

We use a python library, that is a listener for external web events(python-telegram-bot).
So we wrote some functions, that can be called, make stuff and so.
So what is the proper way to start this job with odoo11(as worker?) without bunch of third party apps?

**Comment by Yenthe666** [comment]
Hi @sergeiruzkiicode,

Please ask these questions on the official help forums at help.odoo.com only.
The Github tracker is only for issues in the official code, not for custom development. We basically can't handle/filter out all the issues well if we allow loads of questions here too. Sorry.

Regards,
Yenthe
