### ISSUE TITLE
POS Mercury Module - Partially Approved

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#23952]
**Impacted versions:**
Odoo v10CE 

**Steps to reproduce:**
1. Install Odoo 10 (latest commit)
2. Install _Mercury Payment Services_ (10.0.1.0)
3. Setup Mercury and Credentials as described here:
a) https://www.odoo.com/documentation/user/10.0/point_of_sale/advanced/mercury.html
b) https://www.odoo.com/forum/help-1/question/step-by-step-guidelines-to-accept-credit-card-payments-in-odoo-pos-92896#answer_92898
4. Pass debit/gift card with less amount than requested.
5. Get "Partially approved" notice.

**Current behavior:**

* Partial paid purchase is approved.
* No statement about the amount accepted / due
* No option to fill the due balance

**Expected behavior:**

* Allow to input any other payment method, cash or any other card 'til purchase amount is completed.
* Display the amount paid with the card and the missing one.
* Something like:
http://help.cwebtechnologies.com/ssm/howto/partial_approval_or_partial_auth.htm

**Video/Screenshot link (optional):**

![partially-approved-reviewd](https://user-images.githubusercontent.com/7444518/38119466-2c01eb36-337f-11e8-9b51-f7df48a0786b.jpeg)

**Comment by Ark74** [comment]
Seems like something here is not completely right,

https://github.com/odoo/odoo/blob/10.0/addons/pos_mercury/static/src/js/pos_mercury.js#L422

Thanks.

**Comment by Ark74** [comment]
Just found about this: https://github.com/odoo/odoo/commit/0fd06e59482cb3921002679c97bce9d42e09409f

Will test next week, in order to confirm and hopefully close this issue.
Thanks!

**Comment by jorenvo** [comment]
Indeed, that commit solves this exact issue. Normally you shouldn't encounter the problem anymore. If you do, please reply to this issue and I can reopen.

**Comment by Ark74** [comment]
Haven't have the chance to confirm it.
I'll do as soon as I have the chance. Thanks.
