### ISSUE TITLE
[10.0] Adding item (sale.order.line) on sale.order on mobiel devices only shows quantity & price

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#23954]
Impacted versions:

Odoo 10 APP or mobile device (thus small screen)

Steps to reproduce:

1. Create a sale.order
2. Click on "add item" on sale.order
3. Select product
4. "save" ==> results in error

Current behavior:

Error when clicking save when selected right product

Expected behavior:

Just the standard functionality as on normal screen ps/laptop

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @Patrickar,

Thanks a lot for your bug report.
I've just tested this and it seems to work fine out of the box. Could you please try to reproduce it on an official runbot at runbot.odoo.com? Can you replicate it there?

**Comment by Patrickar** [comment]
Hmm I tested it on 2 different Odoo 10 installation, and in both cases it does not work as it should be in my opinion. 

I will check on official rubot

**Comment by Patrickar** [comment]
Ok tested it, and indeed there is no error or whatssoever, What is in my opinion not correct is that there is no information available in the screen. See image. Is that the standard functionality? 

![image](https://user-images.githubusercontent.com/36632285/38130028-b03b5d92-3401-11e8-97eb-dc034405dd24.png)

**Comment by Yenthe666** [comment]
Hi @Patrickar,

Just tested and it indeed it doesn't show any info except for the amount and price when you're in edit mode of new sale order.
I believe you have an enterprise license? You should report this through odoo.com/help in order to escalate this then.

**Comment by Patrickar** [comment]
Hi Yenthe V.G.,

Ok, thanks. I'll do!

Met vriendelijke groeten,

*Patrick Ariëns*
Consultant | Odoo Gold Partner

+31 (0) 6 30 30 34 56
patrick@alpiek.nl




Alpiek BV
www.alpiek.nl
Odoo Gold Partner





2018-03-30 10:15 GMT+02:00 Yenthe V.G <notifications@github.com>:

**Comment by Yenthe666** [comment]
Closing as it should've been reported through an OPW and as Odoo 10 is no longer officially supported.
