### ISSUE TITLE
How to cancel a sales order after products have been delivered and returned?

### ISSUE THREAD

**Issue by icoro** [odoo/odoo#23951]
Impacted versions: V11

If I create a sales order and deliver the product. Then I can return the product in which case I should be able to cancel the sales order but it won't let me even after returning the product.  Odoo should be able to recognise that the product was returned (there is another stock picking) so that I can cancel the sales. The reporting of the sales are wrong because of this. Salespeople can get commissions on sales orders that have been returned. 

Or by now, is there a workaround/solution for this?

**Comment by Ark74** [comment]
Please try to use https://www.odoo.com/forum/help-1 for this kind of questions.
GitHub is more related to issues at code level and development.

Cheers!

**Comment by Yenthe666** [comment]
Hi @icoro,

As mentioned by @Ark74 the Github tracker is only for issues/bugs in the official code. Questions can be asked on the help forum at https://www.odoo.com/forum/help-1

Regards,
Yenthe
