### ISSUE TITLE
[11.0] Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by eternalharvest** [odoo/odoo#23963]
Impacted versions:
11.0 Ubuntu nightly build

```javascript
> console.log(odoo.session_info.server_version);
11.0-20180329
```

Steps to reproduce:
1. Enter debug mode
2. Click the menu 'Open View' from Developer Tools
3. Search **tree** view (e.g. 'sale.order.tree') and click on it.

Current behavior:

The view is not displayed due to the following error.

```
Uncaught TypeError: Cannot read property 'type' of undefined
```
```
http://garnet:8069/web/static/src/js/chrome/view_manager.js:235
Traceback:
TypeError: Cannot read property 'type' of undefined
    at Class.get_default_view (http://garnet:8069/web/static/src/js/chrome/view_manager.js:235:73)
    at Class.init (http://garnet:8069/web/static/src/js/chrome/view_manager.js:122:34)
    at Class.prototype.(anonymous function) [as init] (http://garnet:8069/web/static/src/js/core/class.js:90:38)
    at new Class (http://garnet:8069/web/static/src/js/core/class.js:107:33)
    at Object.widget (http://garnet:8069/web/static/src/js/chrome/action_manager.js:851:24)
    at Object.<anonymous> (http://garnet:8069/web/static/src/js/chrome/action_manager.js:826:76)
    at Object.<anonymous> (http://garnet:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://garnet:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://garnet:8069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://garnet:8069/web/static/lib/jquery/jquery.js:3275:77)
```
Expected behavior:

The view specified is displayed without any error.

Video/Screenshot link (optional):

![view error](https://user-images.githubusercontent.com/1128403/38137632-bf9b5404-3460-11e8-8911-d6712cfc7e10.png)

**Comment by Yenthe666** [comment]
Hi @eternalharvest,

Thanks a lot for your bug report.
I've just tried this on an Odoo 11.0 from today and it works fine out of the box:
![image](https://user-images.githubusercontent.com/6352350/38137725-a13b10ce-3426-11e8-8ba4-155438012f09.png)
Can you reproduce this on an official Odoo instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by eternalharvest** [comment]
@Yenthe666 thank u for ur quick reply.

The tree view with title "Select a view" itself is no problem.
But when I search the tree view such as 'sale.order.tree' and click on it, the error occurs that I mentioned.
I can open any view from the Developer tools with Odoo version 10 (nigtly build).
So, I think this is a bug related to the Odoo version 11.

Thank u.

**Comment by Yenthe666** [comment]
Hey @eternalharvest,

Indeed, just managed to reproduce it. I just didn't click on a view that is why I didn't get it. Result:
![image](https://user-images.githubusercontent.com/6352350/38140578-abdeb02c-3434-11e8-84a1-c9c6d561a91a.png)


Regards,
Yenthe

**Comment by eternalharvest** [comment]
it stuck on line 235 of view_manager.js (in `ViewManager#get_default_view()` method)
and it seems `this.views` is empty object, and `this.view_order` is empty array.
But I'm not sure why...

![error](https://user-images.githubusercontent.com/1128403/38140740-12798876-3470-11e8-8240-05ae944f3fae.png)

Thanks a lot.

**Comment by OpenTechValue** [comment]
Dear All,
I've got a similar error.
Could you please tell me whether this fix has been release?
thanks 
claudio

**Comment by kebeclibre** [comment]
@OpenTechValue 
Can you be more specific. The fix has been in 11.0 for like 6 months.....

**Comment by OpenTechValue** [comment]
Dear Lucas,
this is the error log I received back.
I've created a plain tree view editable.
no error at all in creation and change mode for new records.
This error occurred in change mode for record created before, i.e. after
leaving the screen and coming back to it.
Regards
thanks in advance
claudio

http://localhost:8069/web/content/1041-9d48731/web.assets_backend.js:1055
Traceback:
TypeError: Cannot read property '0' of undefined
    at Class._renderEdit
(http://localhost:8069/web/content/1041-9d48731/web.assets_backend.js:1055:1050)
    at Class._render
(http://localhost:8069/web/content/1041-9d48731/web.assets_backend.js:892:778)
    at http://localhost:8069/web/content/1041-9d48731/web.assets_backend.js:890:1316
    at http://localhost:8069/web/content/647-59578dd/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/647-59578dd/web.assets_common.js:796:299)
    at Object.add [as done]
(http://localhost:8069/web/content/647-59578dd/web.assets_common.js:797:467)
    at Array.<anonymous>
(http://localhost:8069/web/content/647-59578dd/web.assets_common.js:802:649)
    at Function.each
(http://localhost:8069/web/content/647-59578dd/web.assets_common.js:625:767)
    at Object.<anonymous>
(http://localhost:8069/web/content/647-59578dd/web.assets_common.js:802:560)
    at Function.Deferred
(http://localhost:8069/web/content/647-59578dd/web.assets_common.js:803:194)


Il giorno ven 14 set 2018 alle ore 09:54 Lucas Perais <
notifications@github.com> ha scritto:

**Comment by OpenTechValue** [comment]
Dear All,
this is the error in debug mode
I hope this could be more helpful
[image: image.png]

Il giorno lun 17 set 2018 alle ore 09:24 Lucas Perais <
notifications@github.com> ha scritto:

**Comment by eclipse-dx** [comment]
Hi all, I am receiving the same error as @OpenTechValue. When attempting to modify any field in Odoo Studio, I am presented with the following:

```
Error:
Uncaught TypeError: Cannot read property 'prototype' of undefined

https://culinary.odoo.com/web_studio/static/src/js/view_editor_sidebar.js:95
Traceback:
TypeError: Cannot read property 'prototype' of undefined
    at https://culinary.odoo.com/web_studio/static/src/js/view_editor_sidebar.js:95:46
    at https://culinary.odoo.com/web/static/lib/underscore/underscore.js:219:11
    at Function._.each._.forEach (https://culinary.odoo.com/web/static/lib/underscore/underscore.js:145:9)
    at Function._.filter._.select (https://culinary.odoo.com/web/static/lib/underscore/underscore.js:218:7)
    at _.(anonymous function) [as filter] (https://culinary.odoo.com/web/static/lib/underscore/underscore.js:1484:34)
    at Class.init (https://culinary.odoo.com/web_studio/static/src/js/view_editor_sidebar.js:94:18)
    at Class.prototype.(anonymous function) [as init] (https://culinary.odoo.com/web/static/src/js/core/class.js:90:38)
    at new Class (https://culinary.odoo.com/web/static/src/js/core/class.js:107:33)
    at Class.instantiateSidebar (https://culinary.odoo.com/web_studio/static/src/js/view_editor_manager.js:367:16)
    at Object.<anonymous> (https://culinary.odoo.com/web_studio/static/src/js/view_editor_manager.js:500:33)
```

Upon inspection of the console, it would appear that the javascript in question is referencing an undefined array (or element in an array) at line 95 of view_editor_sidebar.js:
```
        if (this.state.node && (this.state.node.tag === 'field' || this.state.node.tag === 'filter')) {
            // deep copy of field because the object is modified
            // in this widget and this shouldn't impact it
            var field = jQuery.extend(true, {}, this.fields[this.state.attrs.name]);

            // field_registry contains all widgets
            // We want to filter these widgets based on field types
            field.field_widgets = _.chain(field_registry.map)
                .pairs()
                .filter(function (arr) {
=> HERE             return _.contains(arr[1].prototype.supportedFieldTypes, field.type) && arr[0].indexOf('.') < 0;
                })
                .map(function (array) {
                    return array[0];
                })
                .sortBy()
                .value();

            this.state.field = field;

            // only for list & tree view
            this.state.modifiers = this.state.attrs.modifiers || {};
            this._computeFieldAttrs();

            // get infos from the widget:
            // - the possibilty to set a placeholder for this widget
            // For example: it's not possible to set it on a boolean field.
            var Widget = this.state.attrs.Widget;
            this.has_placeholder = Widget && Widget.prototype.has_placeholder || false;
        }
```

I've never had an issue with Studio before, so what has changed? Also note that we are running an Odoo.sh installed with a partner so I'm not sure how much access one has to source code as I haven't seen the Odoo.sh portal.

**Comment by kebeclibre** [comment]
@eclipse-dx 
I still can't reproduce.
Please provide a video on the runbot

Although at https://github.com/thegunshow/culinary/blob/master/sh_barcode_scanner/static/src/js/barcode_scanner_handler.js#L107 

it seems weird to add to the field registry an object which is a form controller AND with an include

**Comment by eclipse-dx** [comment]
Hi @kebeclibre thanks for the quick response.

> Please provide a video on the runbot

I do not know how to use the runbot, could you please provide me with a resource that explains the process? I'm having difficulty finding one.

> Although at https://github.com/thegunshow/culinary/blob/master/sh_barcode_scanner/static/src/js/barcode_scanner_handler.js#L107 it seems weird to add to the field registry an object which is a form controller AND with an include

This is part of an external module we had installed. It didn't fully function, but it's never caused an issue with Studio previously. Shall I have it removed?

**Comment by kebeclibre** [comment]
@eclipse-dx 
runbot is our automated testing platform. It builds, install every module and runs automated tests for each commit and for each supported branch.

Enterprise branches and design branches are also built and tested on it.

Demo data are installed, there are three basic users: admin, demo, portal, whose passwords match their login.

runbot databases are the reference concerning what we call standard Odoo, that is unaltered databases with every app installed. That way, when an issue occurs business-wise and can be reproduced on runbot we are sure that it comes from our code, and not from from specific data or external module.

Accessing it is done through url runbot.odoo.com
![ezgif-3-467745ebe474](https://user-images.githubusercontent.com/17759223/47204464-a78cd000-d383-11e8-81b4-3e80fd7b271b.gif)

The comment on your module was just me trying to figure out what went wrong without being able to reproduce. I just find that weird that you add in the field registry a widget that is not a field widget Moreover it is even weirder that you add a FormController in there.

**Comment by eclipse-dx** [comment]
@kebeclibre managed to test it in the runbot and as expected could not reproduce the error, meaning the error less likely to be in the Odoo codebase, correct?

This is what I'm currently getting on my instance:

![2018-10-19_10-53-25](https://user-images.githubusercontent.com/7691316/47208300-ba0c0700-d38d-11e8-8c59-c1922c99352b.gif)

I will have my partner remove the third-party barcode app and see if that corrects the issue..

Thank you for all your help

**Comment by eclipse-dx** [comment]
@kebeclibre Thank you for identifying the oddity in the 3rd party app; since removing it Studio has been working without error for the past 24 hours.

Thank you again. I can't believe there was once a time where we used ERPs with no community to support them...

**Comment by annya007** [comment]
Hi I am using odoo 18 and getting error like this ----    Uncaught Promise > The following error occurred in onWillDestroy: "Cannot read properties of undefined (reading 'disconnect')"
OwlError: The following error occurred in onWillDestroy: "Cannot read properties of undefined (reading 'disconnect')"    
Caused by: TypeError: Cannot read properties of undefined (reading 'disconnect')
