### ISSUE TITLE
[bug] when manufacuring order had canceled,it's procurment order had not canceled

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#23978]
Impacted versions:
10.0
Steps to reproduce:
- I create  a product :test,
      routes: Manufacture
- I create a sale order ,run mrp ,create a procurement order and a Manufacturing Order
    procurement order: OP/00006 state:running, quantity:30
   manufacturing order: MO/00018 state: confirmed,quantity:20
**- I canceld manufacturing order , it's procurement order throw exception.
    procurement order: OP/00006 state: exception,quantity:30
   manufacturing order: MO/00018 state: canceld,quantity:30**
-  i run procurement at procurement order: OP/00006,create a new manufacuring order
     procurement order: OP/00006 state: exception,quantity:30
    manufacturing order: MO/00019 state: canceld,quantity:30
- i  run mrp ,system create a procurement order and a  duplicate manufacuring order
     procurement order: OP/00006 state: exception,quantity:30
    manufacturing order: MO/00019 state: canceld,quantity:30
Current behavior:

Expected behavior:
 I thind when manufacuring order had canceled ,it's procurment order should be canceld ,not exception.
![qq20180401-202107](https://user-images.githubusercontent.com/5398273/38173202-9c0ef9ae-35ec-11e8-9bfe-cb02ed1f092c.png)
![qq20180401-202519](https://user-images.githubusercontent.com/5398273/38173203-a08a08ac-35ec-11e8-83ba-d60c4c0501eb.png)
![qq20180401-202957](https://user-images.githubusercontent.com/5398273/38173204-a491d4e8-35ec-11e8-9b32-64136ea07d9b.png)
![qq20180401-203122](https://user-images.githubusercontent.com/5398273/38173206-a97f20fa-35ec-11e8-8ecd-44a3bcf9af8c.png)
![qq20180401-203413](https://user-images.githubusercontent.com/5398273/38173210-ba9f7eb6-35ec-11e8-872c-b9d183dc524e.png)

Video/Screenshot link (optional):

**Comment by sum1201** [comment]
enterprise ticket :1833292

**Comment by Yenthe666** [comment]
Dear @sum1201,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue but you should've gotten a good response on the enterprise ticket.

Regards,
Yenthe
