### ISSUE TITLE
Problem with button vista odoo

### ISSUE THREAD

**Issue by giannio** [odoo/odoo#23985]
Impacted versions:9.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

> 
![error1](https://user-images.githubusercontent.com/20817262/38196990-f2ad97d6-3653-11e8-9787-9cf9cc6a96cd.png)

**Comment by giannio** [comment]
With the database restoration, I deleted all the contents of the ir_attachment table, and some buttons do not appear the figure, how can I solve this?

**Comment by Yenthe666** [comment]
@giannio,

The ir_attachment table contains your attachments and it looks like you've also deleted your assets.
Please recompile your assets and restore your ir_attachment table in order to fix this.
Closing as you've simply dropped a table of a database

Regards,
Yenthe

**Comment by giannio** [comment]
How do I recompile my assets? and my table restore from where?

**Comment by Yenthe666** [comment]
from your original backup / old database.
Compilation can be done by updating your whole Odoo its sources (`-u all`) and using `?debug=assets`

**Comment by giannio** [comment]
odoo.py -c /etc/odoo-server -s --update=all ?debug=assets  ????? would it be this?

**Comment by sswapnesh** [comment]
@giannio 
odoo.py -c /etc/odoo-server -d=db_name -u=all
Access odoo using: [http://localhost:8069/web?debug=assets ](http://localhost:8069/web?debug=assets)

**Comment by giannio** [comment]
thanks...

**Comment by giannio** [comment]
pg_restore: [archiver (db)] could not execute query: ERROR:  column "id" of relation "ir_attachment" does not exist
    Command was: COPY public.ir_attachment (id, create_date, write_date, res_model, write_uid, res_name, db_datas, file_size, create_uid, com...
WARNING: errors ignored on restore: 1

**Comment by giannio** [comment]
When I tried to restore a table from the ir_attachment database,
