### ISSUE TITLE
Importing module with odoo studio is not updating the version

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#23988]
Impacted versions:

11.0 (saas)

Steps to reproduce:

- Create a simple module, ser version to 1.0
- Import it using odoo studio.
- Check the version (11.0.1.0)
- Change the version.
- Import it again (or even un-install it and install it again if you wish)

Current behavior:

- Version is yet 11.0.1.0

Expected behavior:

- Take the proper version from the module itself

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@aab-odoo could you have a look at this studio bug please?
