### ISSUE TITLE
[11.0] Kanban: Drag and Drop Pipeline throws trace back.

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#23982]
Impacted versions:
11.0
Steps to reproduce:
Click on CRM > Pipeline Kanban view.

Remove My Pipeline filter.

Select group by **Country** and open any one pipeline from kanban card.

Edit record and remove country value from record and save the form.

Redirect to previous kanban view and new undefined column will be displayed with record.

Drag and drop to any country and again drag and drop to undefined column.

It will throw an error $el undefined

Current behavior:
Throws undefined error.

Expected behavior:
Undefined column should be hidden if there is only one record and user is dropping it to another column.

Video/Screenshot link (optional):

![drag_n_drop](https://user-images.githubusercontent.com/37578829/38192980-44301eb0-368d-11e8-9ea6-27f6dec6074c.png)

**Comment by Yenthe666** [comment]
Hi @MeetKD,

Thanks a lot for your bug report.
I've just tried this on the latest Odoo 11.0 but it seems to work fine. Can you reproduce it on an official Odoo test instance at runbot.odoo.com?
Could you make a video of it please?

Regards,
Yenthe

**Comment by sswapnesh** [comment]
@Yenthe666  I can reproduce on Runbot.
[https://youtu.be/V9sCOsQ_Q5s](https://youtu.be/V9sCOsQ_Q5s)

**Comment by Yenthe666** [comment]
Aha, I didn't do that last redrag, which was the difference.
@ged-odoo another JS traceback. Could one of your guys have a look please?

**Comment by mge-odoo** [comment]
Hi @MeetKD 

Thanks for reporting the bug, this was a tricky one.

Regards,

Martin
