### ISSUE TITLE
Odoo v11E Studio : Error when adding / updating 'Help Tooltip' for any field.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#23980]
Impacted versions: 
                              > OdooV11E Studio

Steps to reproduce:
                            > Open Odoo v11 Studio and Click on Any apps (e.g. sales)
                            > Click on any field in listview (e.g Quotation number)
                            > Now, in Left pane > under Properties Tab > Add/Update 'Help Tooltip'.

Current behavior:
                            > raising Odoo Server Error - Validation Error (Invalid view definition).
Expected behavior:
                           >  It should allow to add / update tooltip.

Video/Screenshot link (optional):

**FYI > Error Showing under Console is as follows :** 
**------------------------------------------------------------------------------------------------------------------------------------------**
Server application error {"message":"Odoo Server Error","data":{"exception_type":"validation_error","message":"Invalid view definition\nNone","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 647, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 689, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 933, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/web_studio/controllers/main.py\", line 624, in edit_view\n    self._set_studio_view(view, new_arch)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/web_studio/controllers/main.py\", line 552, in _set_studio_view\n    self._create_studio_view(view, arch)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/web_studio/controllers/main.py\", line 663, in _create_studio_view\n    'name': self._generate_studio_view_name(view),\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/web_studio/models/studio_mixin.py\", line 18, in create\n    res = super(StudioMixin, self).create(vals)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/base/ir/ir_ui_view.py\", line 398, in create\n    return super(View, self).create(self._compute_defaults(values))\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/models.py\", line 3315, in create\n    self._fields[key].determine_inverse(record)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/fields.py\", line 1070, in determine_inverse\n    getattr(records, self.inverse)()\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/base/ir/ir_ui_view.py\", line 266, in _inverse_arch\n    view.write(data)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/website_version/models/ir_ui_view.py\", line 64, in write\n    return super(view, self).write(vals)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/web_studio/models/studio_mixin.py\", line 27, in write\n    res = super(StudioMixin, self).write(vals)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/base/ir/ir_ui_view.py\", line 414, in write\n    return super(View, self).write(self._compute_defaults(vals))\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/models.py\", line 3024, in write\n    self._write(old_vals)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/models.py\", line 3190, in _write\n    self._validate_fields(vals)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/models.py\", line 982, in _validate_fields\n    check(self)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/316573-11-0-6b2817/odoo/addons/base/ir/ir_ui_view.py\", line 343, in _check_xml\n    raise ValidationError(_('Invalid view definition'))\nodoo.exceptions.ValidationError: ('Invalid view definition', None)\n","name":"odoo.exceptions.ValidationError","arguments":["Invalid view definition",null]},"code":200}
**-------------------------------------------------------------------------------------------------------------------------------------**

Hope this will help to trace issue in more precise way.

**Thanks,**
Dipak Shah

**Comment by mge-odoo** [comment]
Hi @dipsshah42 

Thanks for reporting the issue. It has been fixed in odoo/enterprise@c9baa37

Regards,

Martin
