### ISSUE TITLE
relation fields and related fields  in report  i can't see it

### ISSUE THREAD

**Issue by osamaIT** [odoo/odoo#23983]
relation fields and related fields  in report  i can't see it in Qweb report just i can see the name of relation
i use to see the fields in Qweb    o.fieldName

**Comment by osamaIT** [comment]
i use Qweb report

**Comment by sswapnesh** [comment]
Related to #23926

**Comment by Yenthe666** [comment]
@osamaIT please add more information and details (and don't duplicate issues).
What version? How do you reproduce it? Can you reproduce it on an official Odoo instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi there,

Closing as there has been no feedback in over a month.

Regards,
Yenthe
