### ISSUE TITLE
invoicing 

### ISSUE THREAD

**Issue by shaneebkhan** [odoo/odoo#23981]
Impacted versions:11

Steps to reproduce:invoicing -->sales-->documents-->payments-->internal transafer

Current behavior:Transfer account not defined on the company.

Expected behavior: tranasfer one head to anther 

odoo error on internal transfer (payments invoicing )

wher i can set transfer account

Odoo Server Error - Warning
Transfer account not defined on the company.

Video/Screenshot link (optional):
![error on transfer](https://user-images.githubusercontent.com/10399842/38191151-27652ddc-3685-11e8-9d20-beefa124f4de.png)

**Comment by shaneebkhan** [comment]
odoo error on internal transfer (payments invoicing )

wher i can set transfer account 

Odoo Server Error - Warning
Transfer account not defined on the company.

**Comment by Yenthe666** [comment]
Hi @shaneebkhan,

This is not a bug. You've simply didn't define a transfer account for your Odoo environment. Without this account Odoo does not know where to book your internal transfer too.
Please configure the module.

Regards,
Yenthe

**Comment by shaneebkhan** [comment]
i am asking you how i can define a transfer account for your Odoo environment
please show me the way clearly
