### ISSUE TITLE
[11.0] Wrong Position of list view sort handler.

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#23984]
Impacted versions:
11.0
Steps to reproduce:

1. Install Sales Module.
2. Click on Sales > Quotations list view.
3. Open one of the record.
4. Observe that there is a dropdown of sort handler which is in wrong position.

Current behavior:

Wrong position of list view sort handler.

Expected behavior:

Sort handler should display in correct position.

Video/Screenshot link (optional):

![wrong_position](https://user-images.githubusercontent.com/37578829/38194246-ec623edc-3693-11e8-8e9b-65d933c634b1.png)

**Comment by mge-odoo** [comment]
Hi @MeetKD 

Thanks for reporting the issue.
It has been fixed in 11.0.

Regards,

Martin

**Comment by sswapnesh** [comment]
Hello @mge-odoo 
I can reproduce same at one more Place. (Actually for any Integer/Float field)
List view is sorted by Total
![](https://image.prntscr.com/image/jDNyFg8QSZS8UQIKaZThHg.png)
