### ISSUE TITLE
'Access Rights' / 'Settings' - Wonky behaviour

### ISSUE THREAD

**Issue by hokkaido** [odoo/odoo#240]
1. A member of the group 'Access Rights' can give itself and other users elevated privileges (group 'Settings') by enabling 'Technical Features' and accessing the 'Groups' menu. I think this is a security risk. From a security perspective these two groups are ultimately the same and give a false sense of separation.

2. If a member of the group 'Access Rights' tries to change his administration group to 'Settings' an error is triggered saying that the user has to be a member of the group 'Access Rights'. I guess this is an unrelated error that probably wasn't intended, and well, it doesn't make a whole lot of sense because the user is in the group 'Access Rights'. He or she however can elevate other users to the 'Settings' group through the user edit form, or him- or herself by doing 1.)

3. If there is a third custom administration group, the user edit and create form now displays the administration group as a multi-select with three checkboxes ('Settings', 'Access Rights' and 'Custom Group'. With the two default groups an either-or drop down list is displayed. Doesn't make that much sense to me from a UI perspective...

4. If a group has full CRUD permissions for res.users, the members of this group can create new users with elevated privileges. Again, I think this is a bit flawed.

**Comment by Yenthe666** [comment]
Dear @hokkaido ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
On a sidenote: Everything regarding access rights and settings has changed a lot in V8, V9 and V10 so have a look at that again 😉 

Regards,
Yenthe
