### ISSUE TITLE
[11.0] Issue With Sorting Products based on Name in Website/Backend.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24019]
Impacted versions: 11.0

Steps to reproduce: Shop --> `Sorting by : Name - Z to A` 

Current behavior: 
Invalid Sorting of Products

![](https://image.prntscr.com/image/1WUO0GRjRhua44qDnFlLhw.png)

Expected behavior: Should be sorted Correctly.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Same behavior in Backend. (Maybe I am missing something here)

![](https://image.prntscr.com/image/8hdwO8mNStq-EyH6boa4OA.png)

**Comment by eternalharvest** [comment]
@sswapnesh

I'm not expert of odoo but I think the order is rely on the database locale or collation configuration.
When u click column header, `product.template#search_name()` is called by json rpc.
If you have not overriden the method, it is the cause is database configuration I think.

**Comment by Yenthe666** [comment]
I think there is actually an easier answer. iPod starts with a small character, Warranty with a big one. I believe by default small characters win over capital characters, but I might be wrong here.
@JKE-be can answer this one.

**Comment by sswapnesh** [comment]
I thought same after posting this Issues but If you look at First screenshot, Warranty should come first as sorting is Z to A.

**Comment by JKE-be** [comment]
That will depend from your collation in your psql config.
Odoo uses the default order by.

```sql
select id, name from product_template order by name COLLATE "en_US.utf8" asc ;
 id |          name           
----+-------------------------
 18 | Apple In-Ear Headphones
 19 | iMac
 16 | iPad Mini
  6 | Switch, 24 ports
(4 rows)

select id, name from product_template order by name COLLATE "C" asc ;
 id |          name           
----+-------------------------
 18 | Apple In-Ear Headphones
  6 | Switch, 24 ports
 19 | iMac
 16 | iPad Mini
(4 rows)
```

Psql compares strings according to your locale and collation.

**Comment by sswapnesh** [comment]
Thanks for Review.
