### ISSUE TITLE
Landed Cost not include in COGS

### ISSUE THREAD

**Issue by snomes** [odoo/odoo#24028]
Impacted versions:
Odoo Version 10.0

Current behavior:
I purchase one product 10$ with 3$ custom duty and 2$ insurance, total cost of item is 15$. I sold this item 20$ but Odoo post in COGS 10$ instead of 15$. Please can you help me how can i able to fix this problem.

**Comment by nhomar** [comment]
Hello.

Odoo put the cost set into the product itself, can you check if you manually set the cost on the product, or created the sales order before you applied the landed?

Those are the 2 reasons I see this can happen.

Regards.

**Comment by Yenthe666** [comment]
@nhomar to be honest, questions shouldn't be asked on the Github issue tracker.
@snomes please do ask these questions on the official help forums at help.odoo.com.
The Github issue tracker is only for bugs/issues in the default Odoo and is not the right place to ask questions.

Regards,
Yenthe

**Comment by snomes** [comment]
Sure Mr. Yenthe
