### ISSUE TITLE
Voucher lines do not pass product_id to aml

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24022]
V10

_Apparently_, creating accounting entries via `account.voucher`, the `product_id` is _not_ copied over to the account.move.line. This is impractical if the `product_id` has been set on purpose in order to do filters / analytics or even tax reports based on the product's characteristics.

- Is this a behavior we _do_ want?
- Or would we rather have the `product_id` copied over to the aml just as in normal invoices?

@qdp-odoo 

--------------

Here a proposal of a possible migration script for someone hitting this who want's to fix existing movements:
```sql
UPDATE account_move_line SET product_id=sub.product_id FROM (SELECT DISTINCT avl.product_id, aml.id
    FROM account_voucher_line AS avl 
    JOIN account_voucher AS av ON avl.voucher_id=av.id 
    JOIN account_move_line AS aml ON aml.move_id=av.move_id
    WHERE av.move_id IS NOT NULL
    AND avl.product_id IS NOT NULL
    AND aml.name != '/' -- only works if you do not have any api integraiton which overrides av.name field when initializing a record
    AND avl.name = aml.name) as sub
    WHERE account_move_line.id = sub.id;
```

**Comment by Yenthe666** [comment]
Dear @blaggacao,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
