### ISSUE TITLE
PDF report header and style missing when call via scheduller or shell

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#24023]
Impacted versions: 10 CE

Steps to reproduce:
I create some qweb-pdf report attachment which the method can call via button and scheduled action.

Current behavior:
When i call the method from button, everything works great. But when the method called from scheduled action, header not appear and some style is missing. I tried to call the method via odoo shell, but still have error.
Wkhtmltopdf version 12.0, i have also tried change my wkhtmltopdf to ver 12.1 and newest 12.4 but the problem still appear.
And no error message.

Expected behavior:
The qweb-pdf report should works great when call both via button and scheduled action.

Video/Screenshot link (optional):
This is forum link with same problem https://www.odoo.com/forum/help-1/question/report-missing-header-footer-and-styling-when-scheduled-109206
SS result via button.
![ss_github_1](https://user-images.githubusercontent.com/7473166/38292723-f6e45242-380e-11e8-92e8-be7603878770.png)
SS result via scheduled action
![ss_github_2](https://user-images.githubusercontent.com/7473166/38292727-fb9cc29c-380e-11e8-9ed3-742f5468642a.png)

**Comment by CakJuice** [comment]
I think the problem is wkhtmltopdf need --cookie <name> <value> argument

**Comment by Yenthe666** [comment]
Dear @CakJuice,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
