### ISSUE TITLE
[FIX] Company bank accounts in foreign currency

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#2403]
Impacted versions:

8.0 and above
Steps to reproduce:

Go to Account -> Configuration -> Accounts -> Configure Bank Accounts
Create new Bank Account
Current behavior:

Currency of the bank account not selectable
Expected behavior:

Ability to select currency. Currency choosen will be copied to account journal and account account created as second currency.

**Comment by Yenthe666** [comment]
Hi @feketemihai,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
