### ISSUE TITLE
expresion.OR result is not expected

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#24038]
https://github.com/odoo/odoo/blob/0bde7aa106b74e793bec69fe7f388cc1d4a5deca/addons/sale_timesheet/models/sale_order.py#L179

domain
[('so_line', 'in', [91]), ('amount', '<=', 0.0)]

timesheet_domain
['&', ('so_line', 'in', []), ('project_id', '!=', False)]

expresion.OR(domain, timesheet_domain)
['|', ('so_line', 'in', [91]), ('amount', '<=', 0.0), '&', ('so_line', 'in', []), ('project_id', '!=', False)]

@Tecnativa

**Comment by Elkasitu** [comment]
@jem-odoo for stable you should either explicitly add the `&` or pass the domain to `osv.expression.normalize_domain`

In master `expression.OR` and `expression.AND` will automatically perform the domain normalization.
