### ISSUE TITLE
[11.0] - enable_editor not working on html reports

### ISSUE THREAD

**Issue by gandalfsag** [odoo/odoo#24034]
Impacted versions: 11

Steps to reproduce: 
Print a report. Report is set to html. 

Current behavior: 
It shows the linked qWeb Code as HTML in an embedded space on the page. But there is no possibility of changing anything once there. No font change or possibility to add a letter or even sentences.
Adding a "...?enable_edit=1" does not help. The Web Editor App is installed.

Expected behavior:
In Odoo 9 and 10. It was possible to enter the editor mode in HTML view. Allowing for small changes before print. It was a nice way for the user to make small changes or add a line without going into Form-View or even changing the qWeb-Code.

**Comment by gandalfsag** [comment]
Thanks for your quick answer. 
Argh, this is annoying with Odoo. On each new Version: 2 improvements for 1 feature that doesn't work, is buggy or is not available anymore.

**Comment by mge-odoo** [comment]
@nim-odoo same as in opw-1826599

**Comment by qsm-odoo** [comment]
Hello, this was indeed a bug. The feature is now restored thanks to commit https://github.com/odoo/odoo/commit/61c32429a6063e376ae622bb05d912c36ac9778a.
