### ISSUE TITLE
[9.0] Report of Request for Quotation doesn't show the Vendor Product Name and the Vendor Product Code.

### ISSUE THREAD

**Issue by MouTio** [odoo/odoo#24054]
Impacted versions: 
9.0

Steps to reproduce: 
1. Go to a Product -> Inventory -> Vendors, add a vendor with Vendor Product Name and Vendor Product Code.
2. Create a request for quotation with the vendor and the product configured previously.
3. Print the Request for Quotation.

Current behavior:
The report of Request for Quotation doesn't show the Vendor Product Name and the Vendor Product Code.

Expected behavior:
The report of Request for Quotation should show the Vendor Product Name and the Vendor Product Code.

**Comment by nhomar** [comment]
Hello @MouTio 

You can inherit the report itself and make a custom change if you want to be mandatory on that behavior.

The current behavior is print what you see (which is taking propely what you write in the line).

This is not a bug it is a customization very easily done.

Tested on 11.0:

- Printed what you see.

![image](https://user-images.githubusercontent.com/338634/38353428-03510b52-387c-11e8-8914-5f948c3d8ceb.png)

- Retreived from the onchange if the proper supplier is added.

![image](https://user-images.githubusercontent.com/338634/38353458-1642244e-387c-11e8-8bf0-1b131dd9e561.png)

- Which should be into the list of suppliers.

![image](https://user-images.githubusercontent.com/338634/38353487-2f520ea4-387c-11e8-8c44-6328da333f73.png)

- Which has the name.

![image](https://user-images.githubusercontent.com/338634/38353591-80825306-387c-11e8-9864-8e557aaa6bea.png)

Tested on v9.0:

- The same flow on v9.0:

![image](https://user-images.githubusercontent.com/338634/38353706-dd83c7e2-387c-11e8-9042-3dbcaab3cddb.png)

Thanks for your issue, but this is a customization, the current behavior is what it is expected for.

**Comment by Yenthe666** [comment]
Great answer @nhomar - good job!

**Comment by MouTio** [comment]
@nhomar Thanks for the answer.

I updated and reinstalled the purchase module and now it works as expected (I installed it around 2 years ago).

Sorry for the inconveniences
