### ISSUE TITLE
[11] [L10N] language context breaks for order_lines when creating po/so and printing pdf

### ISSUE THREAD

**Issue by antsjr** [odoo/odoo#24053]
Impacted versions: 
11 Ent

Precondition:
- Odoo has 2 distinct languages activated, one can be default English
- There is a product that has been translated into language X
- There is a partner that uses English pdf templates
- User language is set to language X

Steps to reproduce:
1. Create a vendor PO/SO with given product to the given vendor
2. Print PO/SO and Observe
3. Create Bill from SO/PO
4. Print Bill and Observe

Current behavior:
PO and Vendor Bill from it has order lines in language X 

Expected behavior:
PO and Vendor Bill from it has order lines are in English

Other:
When creating Vendor Bill/Invoice directly and adding products its not reproducible

**Comment by E4O** [comment]
Hi! Is this problem fixed?

**Comment by MohammadSalek** [comment]
Hey @Yenthe666, any updates on this?

**Comment by Yenthe666** [comment]
Well, V11 is end of life for a while now so this should've been closed a while ago already sorry :(

**Comment by MohammadSalek** [comment]
@Yenthe666 But it's still an issue on version 14 !

**Comment by Yenthe666** [comment]
ahh in that case make a short new one please :) This one would be ignored by Odoo anyways
