### ISSUE TITLE
[10.0] Custom financial report actions/menu's are deleted after updating Odoo

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#24067]
Impacted versions: 10.0 atleast

Steps to reproduce:
1. Create a new database and install an accounting chart, for example `l10n_nl`
2. Make sure the option "Get dynamic accounting reports" is checked on under `Accounting > Configuration > Settings`
3. Go to `Accounting > Configuration > Management > Financial reports`
4. Create a new financial report, for example `P&L 2018`:
![image](https://user-images.githubusercontent.com/6352350/38374430-e2667daa-38f3-11e8-8c69-875a014143d9.png)
5. Refresh your Odoo and behold the new menu automatically being added (with the correct menuitem and action created in the Odoo database automatically):
![image](https://user-images.githubusercontent.com/6352350/38374525-26383b72-38f4-11e8-9590-c77af12f0a33.png)
6. Update your whole database from the command line with `-u all`
7. Go back to `Accounting` and have a look at the menuitem, the menu is now gone all of a sudden:
![image](https://user-images.githubusercontent.com/6352350/38374736-b8659436-38f4-11e8-8df3-464a523d106d.png)

Current behavior:
The action and the menuitem are dropped automatically by Odoo when you do a `-u all`, the report itself is kept in the database but is no longer linked to anything so that it shows up to the enduser.

Expected behavior:
Both the action and the menuitem are no longer deleted and protected by the system for future use.

**Comment by Yenthe666** [comment]
Official ticket created. OPW 1834222

**Comment by kebeclibre** [comment]
#2083

**Comment by kebeclibre** [comment]
https://github.com/odoo/enterprise/pull/2083

**Comment by kebeclibre** [comment]
closed at https://github.com/odoo-dev/enterprise/commit/06084da514e7362602362bb874ec70376de8b26b
