### ISSUE TITLE
[11.0] Unable to import 'readonly' fields if field is set readonly from py

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#24072]
Impacted versions:
11.0

Steps to reproduce:
By hr.payslip importation the state of the payslip is not available for importation.
Current behavior:
Can't import readonly fields

Expected behavior:
Can import readonly fields values

Video/Screenshot link (optional):
https://bugs.launchpad.net/openobject-client/+bug/648114

**Comment by vcloud9ray** [comment]
Why is it an issue that you can't import a READ ONLY field?  That's what READ ONLY means.

**Comment by Yenthe666** [comment]
This is indeed by design in the framework and it is wanted behaviour.
If you want to be able to do this you'll need to some custom development to remove the readonly so you can import on that field.
