### ISSUE TITLE
BUG pricelist_id is not taken from parent company

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24073]
https://github.com/odoo/odoo/blob/9a9da5763b38a3bce54e9c4870af0032e38cacc3/addons/sale/models/sale.py#L230

It should be:
```python
self.partner_id.comercial_partner_id.property_product_pricelist
```

Same for payment terms.

**Comment by blaggacao** [comment]
@nim-odoo You last touched this, it seems.

**Comment by pedrobaeza** [comment]
There's no need for that, as both are "commercial fields", and the values are synced between parent/children:

https://github.com/odoo/odoo/blob/9a9da5763b38a3bce54e9c4870af0032e38cacc3/addons/product/models/res_partner.py#L43

**Comment by pedrobaeza** [comment]
I haven't found any problem there, because first the lead is created, and then you link it to the company and propagation is done. Any way, if you find reproducible steps for getting the problem, please open a new issue about that problem, which is not linked with this issue.

**Comment by blaggacao** [comment]
Thanks Pedro! Now this becomes interesting indeed, I'll have a deeper look asap!
