### ISSUE TITLE
Taxcloud not computing on Quotation

### ISSUE THREAD

**Issue by jx2y** [odoo/odoo#24074]
Impacted versions: v11 online

Issue: we have Odoo V11 online and when we create a quotation taxcloud is not reporting the tax. Only when the quote is moved to a sales order will the tax appear. 

Thanks for any help!

**Comment by Yenthe666** [comment]
@tivisse taxcloud so probably of interest to you.

**Comment by tivisse** [comment]
Yes. 

The taxes are computed on the sales order confirmation. 

If you want to compute the taxes before that, you can call Taxcloud manually with the action under the "Action" menu. 

Thanks for the feedback.

**Comment by jx2y** [comment]
Thank you @tivisse! Are you referring to the action menu on the quotation screen? We only see delete, duplicate, invoice. Do we need to manually add that somehow? Thank you so much!

**Comment by sswapnesh** [comment]
@jx2y  It is there in Quotation - -> Action
![screenshot_20180407-105523_01](https://user-images.githubusercontent.com/16624719/38451708-7a53639e-3a52-11e8-916d-f558e267b004.png)

**Comment by jx2y** [comment]
@sswapnesh is that for an online order through the website or is that with a quotation done through the backend? We dont have those options under action....

![quote](https://user-images.githubusercontent.com/37647186/38462485-7c5f314e-3aad-11e8-9071-e5aa7f56df89.PNG)

**Comment by sswapnesh** [comment]
I have check it on Runbot. It is for the quotation created in the backend.

**Comment by tivisse** [comment]
Hi @jx2y 

It seems that your module is not up-to-date. Could you please go to "Apps" and update the module 'account_taxcloud" (You have to remove the filter). 

It should appear after that. 

Thanks.
