### ISSUE TITLE
Not able to convert Belgi\xc3\xab to België in odoo11 python3.5

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#24075]
Impacted versions: odoo 11 python3.5

Steps to reproduce: UTF-8 string Belgi\xc3\xab

my_str = "Belgi\xc3\xab"
encoded_str = my_str.encode('latin1').decode('utf8')
print(encoded_str)

Current behavior: Unable to convert latin chars.

Expected behavior: Should be able to convert to latin chars.

Video/Screenshot link (optional):
https://d.pr/free/i/bbmbip

**Comment by Elkasitu** [comment]
Not an Odoo issue, I suggest you read up on python's [Unicode HOWTO](https://docs.python.org/3.5/howto/unicode.html)

**Comment by mohdshoaib04** [comment]
I have tested this I have tested on python terminal and in odoo too.
Still same.
