### ISSUE TITLE
Server Config For 2K Users

### ISSUE THREAD

**Issue by naitikvithlani** [odoo/odoo#24089]
Hello Team,

I just want to know the which server configuration will work for 2K users in odoo ?

Or any one have idea for how to design the server for 2K users in odoo

**Comment by Yenthe666** [comment]
Hi @naitikvithlani,

Sorry but the Github issue tracker is only for bugs in the official code.
This is not the place to ask for custom development, deployments or any other questions.
Please do ask this question on the help forums at help.odoo.com

P.S: A lot of this depends on if all those users will login at the same time or not, if you will have custom development that does heavy interactions etc.

Regards,
Yenthe
