### ISSUE TITLE
[10.0] stock: Inventory adjustments doesn't restrict lots/serial numbers

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#24084]
Impacted versions
===============

10.0

Steps to reproduce
===============

* Create an stockable product, with Tracking = By lots / By Unique Serial Number
* Press button "Update Qty on hand" (or create an inventory adjustment of that product)
* Introduce a quantity, but not a lot.
* Apply.

Current behavior
==============
The quantity is introduced in the system without the lot.

Expected behavior
===============
There should be an error saying that you can't introduce quantity without lot, and when unique serial number, quantity should be 1.

@Tecnativa

**Comment by sle-odoo** [comment]
Actually, it is possible to have tracked quants without any lot in the system. You can achieve by playing with the create lot and use existing lot in the picking type, i think by disabling both.

**Comment by pedrobaeza** [comment]
So we should restrict that option too?

**Comment by sle-odoo** [comment]
If you want to forbid the "tracked quants without lot" presence, then no. Some business only track products at the delivery step for instance.

We have an ongoing task to display a warning in the use case you pointed-out. I don't think there's something more to do in v10 though.

**Comment by pedrobaeza** [comment]
Yeah, but that's something totally strange. So you put the lot on delivery and quants are overwritten with lot?

Any way. this shouldn't be the default IMO, and even that there should be an option for strictly forbidden it I think. I remember that this was forbidden in v8.

I have opened an enterprise ticket with number 1834389 because this is a problem directly reported by our customer, so the final call is to leave it as is?

**Comment by sle-odoo** [comment]
You can wait for an answer by the support team, but for me there's nothing to do. For the record, i don't like it either functionally and it makes the code trickier (try to reserve on a lot/fallback on a quant without lot).

**Comment by pedrobaeza** [comment]
Closing this as won't fix in current versions.
