### ISSUE TITLE
Drag and drop CRM cards doesn't work on a tablet

### ISSUE THREAD

**Issue by vincentbeland** [odoo/odoo#24096]
Impacted versions: 11.0 (I have only tried on this version, but i know it doesn't work either in odoo 8.0) see issue #1605

Steps to reproduce: On any tablet, try to drag and drop a CRM card from one column to another.

Current behavior: It does nothing

Expected behavior: The card should switch to the desired column

It is an important feature we need to have since our salespersons are always on the road to meet clients.

**Comment by Yenthe666** [comment]
Hi @vincentbeland,

Thanks a lot for the report. This seems to be the case on mobile phones to actually.
@ged-odoo or @aab-odoo could any of you have a look perhaps?
@vincentbeland you could do it (for now?) by opening the record and changing it from within the record instead of from the main view I guess?

Regards,
Yenthe

**Comment by Elkasitu** [comment]
Just to be clear, are you using the mobile app on your tablet or are you experiencing this from your mobile browser?

**Comment by vincentbeland** [comment]
I did it in the web browser on a tablet. Thanks for the quick answer guys! I didn't even know there was a mobile app. I will take a look at it.

**Comment by aab-odoo** [comment]
Hello @vincentbeland 

The drag&drop feature isn't supported on touch devices (tablet or mobile). There was a task to make it work but we faced several technical limitations. It will maybe be supported in future versions, but not in v11 or before.

Regards.

**Comment by david-fleischmann** [comment]
Hi @vincentbeland @Yenthe666 
Is there any update on this topic?
Facing the same issue here. Was thinking about a workaround with widget but to have it work properly on mobile would be way better

**Comment by llabusch93** [comment]
Yep, +1 from me.
