### ISSUE TITLE
[11.0] Bar chart not working in dashboard with multiple actions in Firefox

### ISSUE THREAD

**Issue by ap-wtioit** [odoo/odoo#24092]
Impacted versions:
Odoo 11.0
Firefox 59.0.2 (64-bit)

Steps to reproduce:
- Use Firefox on runbot (db all)
- Go to Sales > Orders > Quotations
- Show graph view
- Extend searchbar to geht "Favourites" Button
- Favourites > Add to my Dashboard > Add
- Go to Repairs
- Favourites > Add to my Dashboard > Add
- Go to Dashboards
- If rendered correctly click on "My Dashboard" again

Current behavior:
Quotation bar chart is only rendered properly sometimes in Firefox when multiple actions are added to a dashboard.

Expected behavior:
Quotation bar chart is always rendered properly.

Video/Screenshot link (optional):
![bar_chart_nok](https://user-images.githubusercontent.com/38032588/38424356-0eabac4c-39b1-11e8-8b4c-ea2dfafba070.png)
![bar_chart_ok](https://user-images.githubusercontent.com/38032588/38424363-12504c68-39b1-11e8-8edb-6373173dda57.png)

Info @wt-io-it

**Comment by wtaferner** [comment]
@ged-odoo @nim-odoo 
Maybe you can put someone of your team on this issue whoever feels responsible...clearly reproducible and probably an easy win fix IMHO

@Yenthe666 
Thx for tagging ;-)

**Comment by alexkuhn** [comment]
Dear,

The bug is caused by the graph that was rendered too soon, i.e. before its container was visible in the page. As a result, bad rendering parameters were used, such as a height of 0 pixels.

The fix guarantees that the rendering of the graph is done at the correct time.

Kind regards,

**Comment by wtaferner** [comment]
@alexkuhn 
Great, thank you for fixing and adding a test :wink:
