### ISSUE TITLE
[11.0] Uncaught SecurityError  - Cannot load/view Order Confirmation from email/message itself 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24112]
Impacted versions: 11.0

Steps to reproduce: Sales Order --> Send by Email --> Send It
Go to Messages --> Open Particular Message --> View order confirmation

![](https://image.prntscr.com/image/mt__JWpwTqetJS4pVHwmgA.png)

or click on the button in any Email

![](https://image.prntscr.com/image/ugKCBksNTqSdXcf4EtrEPA.png)

Current behavior: Traceback on Screen

![](https://image.prntscr.com/image/Bm12W1ivT6Cn8aiAqL1rpw.png)

`Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://318416-11-0-d9f749.runbot8.odoo.com" from accessing a cross-origin frame.
`
Expected behavior:

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Maybe related to #13658

**Comment by Yenthe666** [comment]
@ged-odoo probably another one for your team.

**Comment by mart-e** [comment]
I believe this is because the email is rendered inside an iframe (which is fine, to avoid styling issues).
Setting the link with a `target="_blank"` should avoid the error.
This is however only a problem when you check the email in the technical settings views, not when somebody check its email in the mail client.

**Comment by Yenthe666** [comment]
@mart-e maybe we can make a commit to add `target=_blank` then? If you let me know where I'm happy to make you one.

**Comment by mart-e** [comment]
@Yenthe666 sure, in master we can change these buttons to add the target

**Comment by sswapnesh** [comment]
Reproducible in v12 too.
![screenshot 44](https://user-images.githubusercontent.com/16624719/47271112-d200a800-d592-11e8-8a82-5da0e974f903.png)

**Comment by EyCas** [comment]
Hi,

What is the solution for version 12?
I have the same problem

**Comment by sswapnesh** [comment]
Still there is no Solution.

**Comment by pooja-zakhariya** [comment]
Hello,
Is it fixed now?

**Comment by mart-e** [comment]
Hello,

As explained above, this is not an issue in the email the person recieves, only if you check it from Odoo.
We will not change this in a stable version.
The sale emails should no longer be a problem but if you notice other templates with the same problem **in master**, we can change it by adding a `target=_blank` on the button.

Closing as won't fix.
