### ISSUE TITLE
[11.0] Do not remove attachment from Webpage on Re-Select

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24113]
Impacted versions: 11.0

Steps to reproduce: Create a Web page with having Binary field in it.
Ex.Job Application Form

1:`Choose File` --> Select an File
![](https://image.prntscr.com/image/7S-hMoqUSq2IHqhMYU8vdw.png)

2: Click on `Choose File` Again
3: It will Open Default file Explorer
4: Cancel/Close it.

Current behavior: Selected attachment is Removed on Closing File explorer.

Expected behavior: Attachment should be Preserved or There should be Option to Remove selected attachment. (For now I agree there is no other way to remove selected filr from there)

Video/Screenshot link (optional):

**Comment by LofbergValentin** [comment]
It's standard behaviour for input file. We can't get the file path for security reason and therefore  can't override the current way the input behave.
