### ISSUE TITLE
[11.0] account.fiscal.position.template should have an 'active' field

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#24117]
Impacted versions:
11.0

Steps to reproduce:
- Reconfigure an account.fiscal.position.template for any of the l10n_xx
- Maybe some fiscal positions changed based on legal requirements

Current behavior:
- There's no way to deactivate this fiscal positions from the template

Expected behavior:
- Same behavior as account.tax.template, as Fiscal Positions and Taxes depend on each other.

**Comment by Yenthe666** [comment]
@qdp-odoo for your interest.

**Comment by pedrobaeza** [comment]
I don't think this is needed:

* There's no relation between fiscal position and fiscal position template. The latter serves for generating the first one, but nothing more.
* While fiscal position is a live data that belongs to the company, and thus must be deactivated when it has reached its end on life cycle, the templates can be removed/added on demand for reflecting the latest needed chart template.
* All this data in l10n_xx are noupdate=0 records, so they are automatically handled when there are changes.

Any way, I let someone from Odoo to have the latest word.

**Comment by nhomar** [comment]
Hello @gustavovalverde as @pedrobaeza says, and completing what he said.

Templates** are for the initial configuration only, the generation of the change of the rules is not supposed to be done automatically.

To deactivate them, simply set the field active=False.

![image](https://user-images.githubusercontent.com/338634/38493109-9a42be7e-3bb6-11e8-9695-968ca5c7ff93.png)

The faster way to do it in all your customers is creating a fast server action for that.

**Comment by gustavovalverde** [comment]
I have a case were some fiscal positions were deprecated in l10n_do, the old ones shouldn't show on new installs. For my clients @nhomar approach is the best, but for people who I can't reach (Odoo Online for example) how can I deal with this Fiscal Position deprecation if I can't remove the ids from l10n_do.

**Comment by nhomar** [comment]
@gustavovalverde do not forget to explain the rationale of your changes on the PR, it can not be a full refactor because is "nice" you need to try minimal change required by law only.

**Comment by gustavovalverde** [comment]
In others l10n_do PRs I've been told that I can't remove External IDs in stable, that's why I proposed to add this field, this way the external ID is kept and the fiscal position is deactivated on new installs.

But I could add an automated action to the PR so it can deal with it (but not sure it will be accepted).

**Comment by pedrobaeza** [comment]
Can you point where that has been said? It can be a general rule, but not applicable with chart of accounts. I have removed several records from l10n_es when needed by changes in law. Example: https://github.com/odoo/odoo/pull/8453

**Comment by gustavovalverde** [comment]
I might misunderstood something here: https://github.com/odoo/odoo/pull/13787#issuecomment-261448165, but I understood in that moment that xml-ids can't be touched.

**Comment by pedrobaeza** [comment]
Well, that are tags, that don't have templates, so you are mixing things. Tags can't be removed indeed in stable, as they are shared in the templates and in the companies CoAs.

**Comment by gustavovalverde** [comment]
Well, thanks for the clarification, I got confused with those. If that's the case, the field is not needed and this can be closed.
Thanks @pedrobaeza and @nhomar

**Comment by qdp-odoo** [comment]
indeed

**Comment by darbi-a** [comment]
what is the relation between:
(account.fiscal.position.template) and (account.fiscal.position)
