### ISSUE TITLE
[PERF][11.0] access to related field with very bad performance

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#24119]
Impacted versions: 11.0 (and maybe more)

Steps to reproduce:
- create a model : `perf_max`
- create a field : `name`
- create a field computed (or related) and stored : `compute_name`, with depends `name`
- create 2000 record of `perf_max`
- execute :
```
def stuff(self):
    recs = self.search([]) # get all records
    with self.env.norecompute():
        recs.write({'name':truc})
        for rec in recs:
             print(rec.compute_name)

     self.recompute()
```
--> it is so long inside the loop. Because 
- during the write, alls record are flaged in the `todo recompute list`. And by the fact we are on `norecompute` `env`, the records stay in the `todo recompute list`.
- during the `get('compute_name')` all records are computed each time (by prefech fonction), because after the compute the records are not removed from the `todo recompute list`. 
https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L997

Nota : `record._recompute_check(self)` aka https://github.com/odoo/odoo/blob/11.0/odoo/api.py#L878, return all records not updated.

I think it is not the best idea to use the `todo recompute list` to know if the record is update. When a record go into the `todo recompute list`, those cache are invalided.

With this https://github.com/odoo/odoo/pull/24115 or https://github.com/odoo/odoo/pull/24118 (more generic), it could be fix that.

@odony @rco-odoo @wtaferner @sylvain-garancher 

For an importation of 1000 sale.order.line with `env.norecompute` : before 237 secondes, after 89 secondes : - 54%

**Comment by sylvain-garancher** [comment]
I can confirm that by applying the patch of [this PR](https://github.com/odoo/odoo/pull/24110/files), importing ~3000 sales order lines on my computer goes from more than 10 minutes (I stopped it before it finishes) to less than 4 minutes. My import script only calls `order.write({'order_line': [long list of (0, 0, data) order lines]})` once.

I tried with and without the `with self.env.norecompute():`, the result is the same in both cases.

**Comment by Yenthe666** [comment]
@xmo-odoo for your interest.

**Comment by fmdl** [comment]
@sylvain-garancher have you test with https://github.com/odoo/odoo/pull/24118 ?

**Comment by sylvain-garancher** [comment]
@fmdl No, because unit tests are broken in your PR.

**Comment by fmdl** [comment]
After the study of the code, the use of a field reported in calculations is globally slower than the access to the field directly because there are more operations:

`field_A = fields.Char(related='parent_id.field_B')`
**When get self.field_A :**
1. resolve depth
2. by the fact that this a compute field, Odoo check in the cache the un-computed field (and take time when you are lot of record).
3. get value of parent_id (from database or compute)
4. set in cache value of parent_id 
5. get from cache value of parent_id
6. get value of field_B (from database or compute)
7. set in cache value of field_B
9. get from cache value of field_B
10. set in cache value of field_B in field_A
11. get from cache value of field_A
12. return value of field_A

**When get self.parent_id.field_A :**
1. get value of parent_id (from database or compute)
2. set in cache value of parent_id 
3. get from cache value of parent_id
4. get value of field_B (from database or compute)
5. set in cache value of field_B
6. get from cache value of field_B
7. return value of field_A

**Comment by fmdl** [comment]
@odony @rco-odoo some news ?
