### ISSUE TITLE
Security audit needed. Crypto miner virus discovered in odoo directory.

### ISSUE THREAD

**Issue by chris001** [odoo/odoo#24120]
Impacted versions: 11.0

Steps to reproduce:
Install odoo from github source, to publicly accessible vm, with nginx ssl front end reverse proxy.

Current behavior:
Hackers are able to break into system and upload crypto miner virus, consuming 100% of one CPU core.

Expected behavior:
Impervious to hackers. Detect if/when system broken into by hackers.
Video/Screenshot link (optional):
The hacker crypto miner code was saved to tar/gz tarball for possibly examining by odoo security audit team.

**Comment by Yenthe666** [comment]
@chris001 please don't post these things publicly and create a new email to the security team. See https://www.odoo.com/page/responsible disclosure
You can report at security[at]odoo.com.
Cc @odony and @mart-e

**Comment by chris001** [comment]
OK.  Mail sent.

**Comment by odony** [comment]
There can be many causes for attackers getting into any system. A security bug is one of them, and we'll be happy to assist in your investigation, but there are many other possible causes (much more frequent!), such as insecure deployments, the use of default passwords, etc.
In this era, deploying an internet-facing service requires great care and a skilled admin, one who can follow all security best practices (of the OS, platform, and software). For an Odoo deployment, a good place to start is our [deployment guide](https://www.odoo.com/documentation/11.0/setup/deploy.html#security), especially the Security section.

In order for us to assist, please send all the evidence/logs/etc. you can provide via our security channel, and we'll see together what we can find.

**Comment by Yenthe666** [comment]
@odony & @chris001 can you please give us a small conclusion here too when this topic is done?

**Comment by chris001** [comment]
* Sorry for the trouble, this hacking incident was not the fault of `Odoo 11.0` application code.
* It happened because in the course of development, our developer set an easily guessed password for the `odoo` system user, without realizing remote login was enabled for all users so you mustn't set an easily guessed password.  
* Then, it was easy for the hacker, in Poland, who was scanning the entire internet for servers to login, from their gigabit fiber to the home internet service.  They were able to guess the password for the user `odoo`, login, and install their cryptominer virus.
* Thanks @odony for your help looking into this.
* We're relieved Odoo software itself is without vulnerability.
* We'll update our `InstallScript` to default block remote login for the `odoo` system user, this should prevent future possibility of any remote hacker from being able to login and install their cryptominer viruses.

**Comment by Yenthe666** [comment]
Thanks for the feedback! And something as IP based logins can be a nice security addition.
