### ISSUE TITLE
Hello,,As odoo 11 does not support hierarchical tree view is ther another way to have hierarchical tree view in odoo 11?

### ISSUE THREAD

**Issue by zfarahani** [odoo/odoo#24133]
Impacted versions: 11

Steps to reproduce:

Current behavior:odoo 11 does not have hierarchical tree view. 

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hello, but you shouldn't use issues for asking things. Use the forums or mailing lists for that.

**Comment by zahra97** [comment]
sorry
