### ISSUE TITLE
Odoo11‘s live chat not work

### ISSUE THREAD

**Issue by foxinstone** [odoo/odoo#24147]
Impacted versions:
odoo11
Steps to reproduce:
Follow the official documents 

Current behavior:
Odoo11‘s live chat not work
Expected behavior:
Fix it.
Video/Screenshot link (optional):

Hi,
I have successfully installed the software on Ubuntu16.04，The site looks very good work except the online chat feature does not work.
I checked the error log, found these :

[error] 15035#15035: *68 connect() failed (111: Connection refused) while connecting to upstream, client: 222.221.198.110, server: www.free-le.com, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://127.0.0.1:8072/longpolling/poll", host: "www.free-le.com", referrer: "https://www.free-le.com/web?"

And the same mistake in timing keeps coming up...

Why?

**Comment by lukebranch** [comment]
You need workers > 0 in /etc/odoo-server.conf and you need a reverse proxy like Nginx for the longpolling on 8072.

I'd suggest closing this issue and reading the deployment documentation examples, they provide examples on how to do this:

<a href="https://www.odoo.com/documentation/11.0/setup/deploy.html">https://www.odoo.com/documentation/11.0/setup/deploy.html</a>

**Comment by foxinstone** [comment]
Of course I have this set，In my config file(/etc/odoo.conf), workers=3.
And Please note that this is a log file from nginx，this seems to indicate that it has reverse proxy, but the port declined. also, the site work is ok...

![image](https://user-images.githubusercontent.com/35874666/38534630-a1f07f02-3cb1-11e8-84a2-b94bc9110b8d.png)
![image](https://user-images.githubusercontent.com/35874666/38534642-b1468d34-3cb1-11e8-872c-fdfc688b452b.png)

**Comment by foxinstone** [comment]
Please believe that I have read this Document carefully, and follow the instructions to configure it.

**Comment by foxinstone** [comment]
All right, have been repaired!
The problem is that I didn't notice the path to the ’conf‘ file.
Thanks for your work.

**Comment by vladnfr** [comment]
Hi @foxinstone, can you please be more specific about what you problem was? 
Thank you in advance!

**Comment by sopizet** [comment]
For me the worker parameter in /home/.odoorc was overriding the /etc/odoo.conf parameter
