### ISSUE TITLE
v8 Accounting Module is also installing Warehouse....

### ISSUE THREAD

**Issue by nostahl** [odoo/odoo#2415]
I just installed a fresh server and added accounting and finance module, it continues to install warehouse module and some other dependancies.... why would you need warehouse module if your general service based accounting...

**Comment by Yenthe666** [comment]
Hi @nostahl ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
