### ISSUE TITLE
[V11.0] hr_payroll: Issue with "other input" in Payslip computation

### ISSUE THREAD

**Issue by kharbat** [odoo/odoo#24156]
Impacted versions: 11.0

**Steps to reproduce:** In a Payslip Batch, try to enter values for "Other Inputs" and click Compute Sheet

**Current behavior:**  Values of other inputs are being saved to the database, but not retrieved when the popup reloads. Might be something with the JS code.

**Expected behavior:** The user input values should remain after clicking Compute Sheet and be reflected on the Payslip computation.

**Video link:** https://youtu.be/BK4dJLVB_WI

**Comment by kharbat** [comment]
Hi @rahways, thanks for your response. That's true when you're editing a single payslip, you need to save it first then compute. However, when you're editing a batch, records are already saved. And even if you hit save, the input values still do not work properly.

**Comment by tivisse** [comment]
Hi @kharbat 

Thanks for the feedback.

Unfortunately, I cannot reproduce the issue. The ``hr.rule.input`` is supposed to be introduced when setting the employee on the payslip, and doesn't interfere with the payslip inputs that were entered manually.

But, if you still think that this report is relevant, feel free to reopen it, which a video that shows how you configure the inputs, and how the payslip computation erases the value.

Have a nice day,

Yannick.
