### ISSUE TITLE
[11.0] Drag and Drop Issue

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#24154]
Impacted versions:
11.0
Steps to reproduce:
Click on Project Menu.

Go to Task Menu.

Open one of the task.

Drag and Drop Kanban state or Priority field on description field.

it will show the link with element in description iield.
Current behavior:

While drag and drop the kanban state or priority field it is showing link with image.

Expected behavior:

It should not allow to drag and drop on kanban state and priority field in html field.
 

Video/Screenshot link (optional):

![apr 10 2018 2_26 pm](https://user-images.githubusercontent.com/37578829/38547367-854bfe7e-3ccc-11e8-9a40-4ea1b6d0ca3d.gif)

**Comment by pedrobaeza** [comment]
This is something inherit to the browser and how it handles the images, so I don't consider this an Odoo bug. Any way, just don't drag the element. Others will consider this a blessing, as you get the URL of an image easily...

Closing as no real bug.
