### ISSUE TITLE
SalesManager can't confirm quotation 

### ISSUE THREAD

**Issue by AlexZhangY** [odoo/odoo#24168]
Impacted versions:
Odoo 8
Steps to reproduce:
The sales create a quotation(permission:see owner),when salesManager（permission:Manager) confirm the quotation, appear odoo warning,access reject:because safe limit,request operation can't complete,please connect the system manager, document type Sales Order, operation:write.
So 

1. I check the User->group -->sales/salesManager,  both ‘see all leads’ and ‘see owner leads‘ are inherit.
2. Second: I search sale.order in  check access control list, they all have the right to write.
Current behavior:

Odoo8 install App:sales 、purchase、 manufactory、warehouse、 project(And then it was uninstall）.
Too many companies have been set up.
The sales create quotation, He can confirm it himself。and so does the administrator（In sales Department permission:salesManager）, but salesManager can't do this。
I have no problem with installing new Odoo systems on other computers.
 I confusion.

Expected behavior:
Sales create a quotation, the salesManager can confirm it, turn into a sales order.
If there is any description, please let me know
Thank you for your help.

Video/Screenshot link (optional):
￼
![qq20180410-1](https://user-images.githubusercontent.com/20588144/38566018-4d7b6c34-3d15-11e8-97f4-9fcbdf7179ad.png)
￼
![image](https://user-images.githubusercontent.com/20588144/38566797-27e37ef6-3d17-11e8-8778-625cc1a818dd.png)

**Comment by Yenthe666** [comment]
Hi @AlexZhangY,

Thank you for your bug report.
The Odoo 8 version is no longer supported though as it is end of life. Odoo only supports the last three versions (at this point 9.0, 10.0 and 11.0).
For this reason I'm closing this bug report.

Regards,
Yenthe
