### ISSUE TITLE
Odoo 11 PDF generation extremly slow only when NO Internet connection on the Server

### ISSUE THREAD

**Issue by fhrancis** [odoo/odoo#24173]
Impacted versions: Odoo 11

Steps to reproduce: Block Internet connection to the Odoo Server. Now Print a Quotation or Invoice. 
The parameter "report.url" is already set to: "http://127.0.0.1:8069"

Current behavior: The PDF generation takes like 2 minutes.

Expected behavior: The PDF generation should take between 2 - 3 seconds.

Video/Screenshot link (optional): https://www.youtube.com/watch?v=QV4cnLDdt7M&feature=youtu.be

**Comment by sswapnesh** [comment]
I have faced similar behavior on live server too where it has limited access and other ports are already disabled.

**Comment by dhannyz** [comment]
@nhomar you would need to run a local cache of those assets and modify your hosts file to point google and other CDN addresses to your local cache.
Otherwise you could write a module that replaces all references to remote included resources and store those resources inside your new module.

**Comment by gdgellatly** [comment]
For Google fonts in particular there is a good less/sass generator for
doing exactly this. I forget its name but I've used quite a bit. Just
select your fonts, specify path and download the zip file.

**Comment by OliHall** [comment]
Hi @gdgellatly is this the utility you mentioned above to download google fonts?
https://google-webfonts-helper.herokuapp.com/fonts
https://github.com/majodev/google-webfonts-helper
thanks,
Oli.

**Comment by gdgellatly** [comment]
@OliHall i think so. looks a bit different now but seems to be it

**Comment by OliHall** [comment]
@gdgellatly Thanks, I'll give it a go - I am experiencing the same problem on an AWS Odoo11 instance. I'll report back if I manage to fix it.

**Comment by RoelAdriaans** [comment]
We seem to have similar issues, but with a machine with full outgoing connectivity at a clients side. 
One caveat; the DNS server returned IPv6 results for hostname queries, but IPv6 was not configured (properly) in the network.
Request for fonts would first use the ipv6 address, timeout and fetch from the ipv4 result, resulting in a big delay.  

Disabling IPv6 support on the linux server sped things up a lot.

**Comment by muerto7** [comment]
Greetings @fhrancis 
Any solution so far?
My question is not answered in the forum, also post a video
https://www.odoo.com/es_ES/forum/ayuda-1/question/slow-printing-qweb-report-without-internet-133300

**Comment by fhrancis** [comment]
Hi @muerto7 
Could not solve it. Moved back to Odoo v10.

**Comment by Floggedhorse** [comment]
[This worked for me]( https://github.com/odoo/docker/issues/160)

**Comment by ncarro** [comment]
Is there a solution for this?

> The technical reason is the downloading of some google fonts and CDN assets...

What odoo code does this? Can someone point me in the right direction?
Thanks

**Comment by boris-burgos** [comment]
Hi.

Our problem with this was fixed adding the Odoo server name (i.e. odoo.mycompany.com) to the /etc/hosts pointing to 127.0.0.1.

Regards.

**Comment by ncarro** [comment]
We fixed our issue upgrading odoo 11 to the latest version. It was a link to an external font that genereted the problem.
The file that contained the link was:
addons/web/views/report_templates.xml

The latest version doesn't have external links.

**Comment by mart-e** [comment]
Fixed at 940246f583880d6a1f186e098f18
