### ISSUE TITLE
[Odoo Forum]: The forum is under spam attack again!

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#24170]
@Yenthe666 @JKE-be @odony Since days the well known spam attacks from korean IP origins are growing again, at the moment with a rate of 1 spam message per minute.
Our measures taken a longer time ago (https://github.com/odoo/odoo/issues/12803 )seem not to be sufficient anymore. We should introduce a closing reasing which does not only delete the karma of spammers, but which additionally also blocks the IP address, or we create a filter, which deletes these messages automatically, as they all look exactly the same. I did not delete the last messages, but only close and downvote them so you can check what's going on.

**Comment by Yenthe666** [comment]
@treviser,

Yeah I've noticed so too. I think we should create an IP filter of some sorts on the forums. We should catch the user IP and only allow x posts per x time. If this threshold is passed there should be a redirect page saying that you cannot create so many topics at such a short interval.

I think this is one of the only long term and good fixes to prevent this from happening. :)

Regards, 
Yenthe

**Comment by JKE-be** [comment]
2 days that we check, but I don't see the validation queue increase...
Do we need to take action?

If that arrives again, I can re-add the blacklist like for the previous issue #12803
