### ISSUE TITLE
[8.0] Error Validating Invoice with analytic multi plan.

### ISSUE THREAD

**Issue by dattah** [odoo/odoo#2417]
Create Invoice line.  Add analytic distribtuion. Cannot validate invoice. Remove plan and invoice validates.

File "/opt/odoo/odoo/addons/account_analytic_plans/account_analytic_plans.py", line 395, in _get_analytic_lines
    ref = self._convert_ref(inv.number)
ValueError: "" while evaluating
u'action_move_create()'

**Comment by jeffery9** [comment]
related with #6473

**Comment by Yenthe666** [comment]
Hi @dattah,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
