### ISSUE TITLE
[11.0] Can't change code digits for chart of account

### ISSUE THREAD

**Issue by qpeyramale** [odoo/odoo#24190]
Hello,

In v10 we were able to change the code length in the settings of accounting (debug mode).

![image](https://user-images.githubusercontent.com/7935472/38628862-b7aacd82-3db2-11e8-98c6-9cb9bde9668d.png)

In v11, this option was erased: https://github.com/odoo/odoo/commit/23ddd7d0faa4b9c29f3a3a81dfd95fd4daa13f87

Is there an other way to do it?
Thanks

**Comment by pedrobaeza** [comment]
Not in standard, as it's not a real need (only old accounting uses), and it was removed for simplifying the setup.
