### ISSUE TITLE
odoo saas-5 has wrong behaviour in website non edit mode 

### ISSUE THREAD

**Issue by shingonoide** [odoo/odoo#2419]
In branch saas-5 has a strange bug, I don't know how to fix that can not get any clue somewhere how to fix that
Can be checked at http://16363-saas-5-9699f6.runbot.odoo.com/ for example or any build of saas-5 branch.
This bug is not present in saas-3 or 8.0 branch.

When I click in banner button "contact us", seems like edit mode but it's not.
This happens too if try to access through phone browser.
Anyone has some clue how to fix that?

**Comment by Yenthe666** [comment]
Hi @shingonoide,

This bug should be no longer in V8.
As V8 is no longer an official supported version I'm closing this issue.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.


Regards,
Yenthe
