### ISSUE TITLE
Not possible to load data from CSV files using noupdate=1

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#24209]
Impacted versions:
- 11.0
- 10.0

Current behavior:
The manifest supports several keys to load data files, like `data`. However, none of them loads the data using `noupdate=1`, as used to do the key `init_xml`.

Sometimes, it's necessary to load large data files, and CSV files are loaded about 10 times faster than XML  files.

Expected behavior:
There should be any way to load CSV files using `update=1`, like
- ```
  'data_noupdate': [
      'module/data/large_file.csv',
  ],
  ```
- ```
  'data': [
      ('module/data/large_file.csv', 'noupdate'),
   ],
  ```

**Comment by nhomar** [comment]
Hello.

Sorry but this is not supported for now.

When you need speed up the load of a CSV you can use with an init hook + a proper SQL.

Another option simply creates a hook that marks noupdate=1 with such technique in the table ir.model.data (where the xml_id are saved).

I hope you understand.

Regards.

**Comment by luisg123v** [comment]
Hi @nhomar,

It seems this topic has comed up several times lately. Would you consider reopening this issue?

CC @moylop260 @ovnicraft

**Comment by LuisMalave2001** [comment]
> Hi @nhomar,
> 
> It seems this topic has comed up several times lately. Would you consider reopening this issue?
> 
> CC @moylop260 @ovnicraft

(Link are from last current commit)
I don't know if it was completly romoved, but I could find this in the core code.
https://github.com/odoo/odoo/blob/aeebe275016b47c359ffc4a07ac5b7f03534701c/odoo/modules/loading.py#L38-L71

![image](https://user-images.githubusercontent.com/58850261/91443496-b55ee680-e873-11ea-816b-bd40c8e68319.png)

**Comment by luisg123v** [comment]
Hi @LuisMalave2001,

The key `init_xml` currently behaves just as the key `data`, which means is `noupdate=False`. For more info, see https://github.com/odoo/odoo/issues/23630.
