### ISSUE TITLE
[11.0] Location should be required in Return Picking

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24207]
Impacted versions: 11.0

Steps to reproduce: Create a Return Picking --> Do no Select Return Location --> Return

Current behavior:

![](https://image.prntscr.com/image/CWQQqT2jSXam9a6_x4OW1w.png)

Expected behavior:  Location Should be required and Return should be Processed.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Or maybe better to take the source location of the picking being returned.

**Comment by sswapnesh** [comment]
That's True, We should take the source location of the Original Picking. (Actually, I removed it from that to test the Picking behavior.)

**Comment by ThijsvOers** [comment]
In the case of return of goods by a customer, retail companies will often first inspect the returned goods before it's returned te the original location. In this situation a separate return warehouse (or return location) is created. 
My suggestion for improvement is  that the user has the option to return the goods first to the return/warehouse or location (a return warehouse would be a warehouse with a boolean 'is a return WH'  set to ' yes' ). 
After inspection the product can be manually transferred to the original location or (example) a store location. 
If the product is damaged it would be nice if you could tag the product as damaged. By doing so, it can be identified in the sales process (e.g to show it with a rabat on your website).

**Comment by sswapnesh** [comment]
Hello @jco-odoo , @sle-odoo 
Same situation in v12.
Can we make this required in master ?

**Comment by sle-odoo** [comment]
internal task to fix this: 1986294

**Comment by sswapnesh** [comment]
> internal task to fix this: 1986294

Is is it going to Improve or Can we just make it required there ? (than it will be an easy task for sure)
