### ISSUE TITLE
[WishList]Importation on Database ID

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#2420]
Hi Odoo,

For now Odoo just support External ID as id to import things.
It will be great if we can import from database id too.
We can do that for other field, but not on primary ID.

When we just support external ID, we must export the record first so the record will have external id, but if the system support database ID, we don't have to do that. So it will be very convenient to import things.

Thank You.

**Comment by pedrobaeza** [comment]
@xmo-odoo any news about this wishlist?

**Comment by dreispt** [comment]
For updating existing records you can use database id.
You mean importing new records?
Why don't you just build External IDs based on the foreign database ID?

**Comment by falinwa** [comment]
what I mean is to import existing one.
really? how to do it?
what can I see right now is only for external id.
we can just update the value of the record with database id, but not the id of the record

**Comment by pedrobaeza** [comment]
This is already supported in latest versions, so I close it.
