### ISSUE TITLE
[11.0] Online orders' Salesperson is overwritten as Admin for new portal user

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#24216]
**Impacted versions:**
11.0c

**Steps to reproduce:**
1. Specify an user as the "Salesperson" for online orders, e.g. Demo User,
![image](https://user-images.githubusercontent.com/27185427/38730551-85b39a78-3f49-11e8-9e2c-91b3143071fa.png)

2. Register an account for a new user
3. Login to the new account
4. Add products into the cart and "Process Checkout"
5. Enter the address and press "Next"

**Current behavior:**
The `Salesperson` of the sales order is changed from Demo User to Administrator

**Expected behavior:**
The `Salesperson` should be kepy as Demo User.

**Comment by yostashiro** [comment]
The culprit: https://github.com/odoo/odoo/blob/6fb59b23378d05ad59621cf5094dfbe02a311ba5/addons/sale/models/sale.py#L234

This onchange method is triggered when address is updated.  I think the logic to get a sales person should be put into a separate method, so that it can be overriden by website_sale module.

**Comment by pedrobaeza** [comment]
@JKE-be can you please check this?

**Comment by JKE-be** [comment]
Waiting PoV of @tde-banana-odoo about commit 0c97c2c47f51a09ecd0efe571bf5ee4448c7c329

**Comment by TimLai125** [comment]
Hi @tde-banana-odoo , can we have your opinion regarding this issue?

**Comment by rdeodoo** [comment]
It looks like the behavior was fixed a few days ago with https://github.com/odoo/odoo/commit/5dea3651f133b1096fede9ee476cf5dfcc255f28
The salesperson is not overwritten by admin anymore, I just tested it.
I think this one can be closed?
