### ISSUE TITLE
 File "C:\Program Files (x86)\Odoo 8.0-20141128\server\.\openerp\http.py", line 517, in _handle_exception

### ISSUE THREAD

**Issue by Ingala2018** [odoo/odoo#24227]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, not enough information. Please indicate the steps to reproduce the problem.

**Comment by Yenthe666** [comment]
@pedrobaeza,

Really doesn't matter. The bug report is for an Odoo version 8.
@Ingala2018 sorry but Odoo 8 is end of life and is no longer officially supported. 

Regards, 
Yenthe the

**Comment by pedrobaeza** [comment]
Yeah, indeed
