### ISSUE TITLE
website_sale: requesting not existing shop category results in MissingError and returns 500 instead 404 not found

### ISSUE THREAD

**Issue by ruuter** [odoo/odoo#24235]
Impacted versions: at least 10.0 and up. Tested in runbot.

Steps to reproduce: request not existing category with URL like **/shop?category=999**
Use query parameter instead slug form.

Current behavior: returns 500 Internal Server Error (MissingError)

Expected behavior: to gracefully return 404 not found

The culprit seems to lie [on this line](https://github.com/odoo/odoo/blob/10.0/addons/website_sale/controllers/main.py#L218), which assumes existing category.
I would propose a fix something like this:

```
try:
    url = "/shop/category/%s" % slug(category)
except Exception, e:
    return request.env['ir.http']._handle_exception(e, 404)

```

**Comment by sswapnesh** [comment]
or maybe we can Propose combination like [this](https://github.com/odoo/odoo/blob/10.0/addons/website_sale/controllers/main.py#L278) and [this](https://github.com/odoo/odoo/blob/10.0/addons/website/controllers/main.py#L121).

**Comment by JKE-be** [comment]
Thanks for the reporting

It has been fixed in v10 and will be ported asap in the next versions
