### ISSUE TITLE
[11.0] Technical group users removed after an update

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#24230]
**Impacted versions:** 11.0

**Steps to reproduce:**

1. From a file of configuration .yml execute the configuration for example:
```yml
-
  Stock settings set for Unit of Measures, Manage several Warehouse & locations.
-
  !record {model: res.config.settings, id: stock_configuration}:
    {
      'group_uom': 1,
      'group_stock_multi_locations': true,
      'group_stock_multi_warehouses': true,
      'default_picking_policy': 'direct'
    }
-
  !python {model: res.config.settings}: |
    self.browse(ref('stock_configuration')).execute()
```
**Current behavior:**

The users of group_stock_packaging group are deleted

**Expected behavior:** 

After the update, the users added to group_stock_packaging group remain

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this is not a problem of Odoo itself, but a bad manipulation of its ORM/tools. FYI, YAML support will be removed in next version.

Any way, please ask for the problem on the forums or in mailing lists.
