### ISSUE TITLE
[Master] Can not update app list

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#24231]
Impacted versions:
Master version 20180413
Steps to reproduce:
1、Creat database using Chinese language
2、Enable debug
3、Update APP list
Current behavior:
Odoo server error
Expected behavior:

Video/Screenshot link (optional):

![qq 20180414081541](https://user-images.githubusercontent.com/22065407/38762243-bd0f05fc-3fbc-11e8-88d3-5f5d96cd037f.png)

**Comment by Yenthe666** [comment]
Hi @Guobower,

Thanks a lot for your bug report.
The master version however is a version that is in constant development and which will become the new V12.
This means that we usually don't keep those bug reports open and actively track them as the master keeps breaking quite some times with big changes.
@mart-e it would be nice to fix it anyways.

Regards,
Yenthe
