### ISSUE TITLE
fail web interface

### ISSUE THREAD

**Issue by Jca2714** [odoo/odoo#24239]
Impacted versions:
odoo 11 teme backend_theme_v11-11.0.1.0.3
Steps to reproduce: 
at the time of implementation in odoo window there are several inconvenient one of them is that
ient one of them is that it is no
on in odoo window there are several inconvenient one of them is that
ient one of them is that it is not being cleaned when the application is unregistered the records of postgrest is old but in this verificatio
eing cleaned when the application is unregistered the records of postgrest is old but in this verification just when it is deleted several times it stops deleting the records in local macquina posgrees

the second inconvenience dectectado is that payton tries to solve based on the codification that the topics have and causes the application to stop working which implies that everything is lost especcminte with the template for issues this situation happens

http: // localhost: 8069 / web # menu_id = 4 & action =

it stays that way and does not allow anything to exceed the web part that if it works

another incident is at the moment of putting the application in port 80 the configuration for the database stops working which prevents that a backup can be made medinate the application.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/17165351/38776477-402b236e-4065-11e8-9657-1772c0a27b21.png)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in that code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.
