### ISSUE TITLE
[11.0] External API documentation is outdated

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24232]
Impacted versions: 11.0

Steps to reproduce:
Officical Documentation link: [https://www.odoo.com/documentation/11.0/webservices/odoo.html](https://www.odoo.com/documentation/11.0/webservices/odoo.html)

Current behavior:

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlrpclib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xmlrpclib'
>>> 

```

Expected behavior:

```
try:
    from xmlrpc import client as xmlrpclib
except ImportError:
    import xmlrpclib

```
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
More than outdated, it should unfold Python section into 2: one for Python 2 and one for Python 3. You can access via XML-RPC to an Odoo v11 using Python 2 if you want.

**Comment by pedrobaeza** [comment]
@mart-e are you the one that handles this documentation?

**Comment by Yenthe666** [comment]
Yep, he is 😉

**Comment by sswapnesh** [comment]
@Yenthe666 I was also thinking of that, But as @pedrobaeza  Said, We have to change it into  2 Sections. So I was not sure how to Handel there.

**Comment by mart-e** [comment]
The current doc example are indeed in python 2, not python 3.
It is not really an issue but it can confusing. To avoid the confusion, I explicitly specified the examples are written in python 2 at a87dc3111c5.

If somebody wants to submit a PR to convert to python 3, it can be accepted too (not sure if the export is enough, maybe some encoding conversions to do as well).

No need to have two sections for python 2 & 3 as it will probably be almost the same...

**Comment by pedrobaeza** [comment]
@mart-e there are several differences in the import, and in the syntax as it's different syntax, so I think the 2 sections are needed. Thanks any way for clarifying a bit the documentation with that move.

**Comment by sswapnesh** [comment]
@mart-e 
or May be we can add like this
```
try:
    #Python3 Import
    from xmlrpc import client as xmlrpclib
except ImportError:
    #Python2 Import
    import xmlrpclib
```
