### ISSUE TITLE
Wrong cost price update if zero quantity on move

### ISSUE THREAD

**Issue by gr22** [odoo/odoo#24240]
Impacted versions: 10

Steps to reproduce: Create MO with a line having lot numbers. When producing select the Lot number but leave qty to 0. Complete the MO.

Current behavior: The cost price of that line is updated to 0 [here](https://github.com/odoo/odoo/blob/10.0/addons/stock_account/models/stock.py#L224) the check doesn't take in account the case when move.quant_ids is empty and so the price get's wrongly set

Expected behavior: check in move.quant_ids is an empty list and skip setting the cost price

**Comment by pedrobaeza** [comment]
I don't see why the cost price should be updated if the final quantity doesn't change...

**Comment by gr22** [comment]
It shouldn't but it does update it to 0

**Comment by pedrobaeza** [comment]
Well, then I think it's only a question of float compare. @jco-odoo that line of code should use `float_is_zero` function instead, don't you think?

**Comment by gr22** [comment]
Also the next line in the code breaks the whole loop with **return** so as soon if there is a line with negative quant it will skip updating any following lines but this is probably a new bug report!

**Comment by Yenthe666** [comment]
Dear @gr22,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
