### ISSUE TITLE
CRM Activities not showing in Calendar

### ISSUE THREAD

**Issue by axeforeverjumo** [odoo/odoo#24265]
Impacted versions: 11

Steps to reproduce: Create an Activity in CRM and then looking for in calendar.

Current behavior: Not showing

Expected behavior: Show my activities in Calendar.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Calendar is not for Activities.
You can find Activities here.

![](https://image.prntscr.com/image/IIVhVV6QThurS2_Hu7u6YQ.png)

**Comment by pedrobaeza** [comment]
Indeed, they are treated isolately, as activities don't have a date, but a deadline date, which is a maximum date, so it would wrong to be represented on that date, and very confusing if you see all of them in the calendar while not due.

Closing as no real issue.
