### ISSUE TITLE
Impose style guidelines

### ISSUE THREAD

**Issue by tgroutars** [odoo/odoo#24274]
I'm still surprised by the lack of imposed guidelines regarding code style.
For example, trailing spaces, space before a column, are still present everywhere I look. 

I use a linter, which is very helpful to not only discover style issues, but also real errors, but the sheer amount of errors and warnings when working in the odoo codebase make it completely useless.

Working in a clean codebase makes a developer happy, and happy developer = productive developer.

I understand it can be challenging on an open source project, but IMO it's worth it. 

Can we at least discuss it and propose some solutions ?

**Comment by Yenthe666** [comment]
@mart-e you're the guy here.

**Comment by mart-e** [comment]
Hi Thomas!

https://www.odoo.com/documentation/11.0/reference/guidelines.html

> When modifying existing files in stable version the original file style strictly supersedes any other style guidelines. In other words please never modify existing files in order to apply these guidelines. It avoids disrupting the revision history of code lines. Diff should be kept minimal. For more details, see our pull request guide.
> 
> When modifying existing files in master (development) version apply those guidelines to existing code only for modified code or if most of the file is under revision. In other words modify existing files structure only if it is going under major changes. In that case first do a move commit then apply the changes related to the feature.

Don't also forget we have decided to _not_ follow some PEP8 guidelines:
https://www.odoo.com/documentation/11.0/reference/guidelines.html#python

In the web framework (as it was recently fully rewritten), the guidelines are now imposed. On the python side, it is a bit on best effort. I don't think @antonylesuisse wants to impose strict coding rules to developers. I know @tde-banana-odoo tries to apply it in his team for instance but in the end, it depends on the one who is merging.

I believe it is going in the right direction to clean the codebase but it will take some time.
