### ISSUE TITLE
[v8]No handlers could be found for logger "openerp.addons.base.ir.ir_attachment"

### ISSUE THREAD

**Issue by rainberg** [odoo/odoo#2428]
with uwsgi log

No handlers could be found for logger "openerp.addons.base.ir.ir_attachment"
[pid: 9741|app: 0|req: 2/2] 116.22.142.145 () {44 vars in 798 bytes} [Tue Sep 16
 07:05:24 2014] GET /web/js/web.assets_common/a5f2994 => generated 0 bytes in 27
 msecs (HTTP/1.1 200) 5 headers in 290 bytes (1 switches on core 0)
[pid: 9741|app: 0|req: 3/3] 116.22.142.145 () {44 vars in 823 bytes} [Tue Sep 16
 07:05:25 2014] GET /web/css/website.assets_editor/d4c23e5 => generated 0 bytes
in 33 msecs (HTTP/1.1 200) 5 headers in 276 bytes (1 switches on core 0)
[pid: 9741|app: 0|req: 4/4] 116.22.142.145 () {44 vars in 806 bytes} [Tue Sep 16
 07:05:25 2014] GET /web/js/website.assets_editor/d4c23e5 => generated 0 bytes i
n 46 msecs (HTTP/1.1 200) 5 headers in 290 bytes (1 switches on core 0)
[pid: 9741|app: 0|req: 5/5] 116.22.142.145 () {44 vars in 767 bytes} [Tue Sep 16
 07:05:25 2014] GET /logo.png => generated 8604 bytes in 26 msecs (HTTP/1.1 200)
 3 headers in 195 bytes (1 switches on core 0)
[pid: 9741|app: 0|req: 6/6] 116.22.142.145 () {44 vars in 852 bytes} [Tue Sep 16
 07:05:25 2014] GET /website/image?field=datas&model=ir.attachment&id=16 => gene
rated 1192 bytes in 104 msecs (HTTP/1.1 200) 4 headers in 248 bytes (1 switches
on core 0)
[pid: 9741|app: 0|req: 7/7] 116.22.142.145 () {44 vars in 852 bytes} [Tue Sep 16
 07:05:25 2014] GET /website/image?field=datas&model=ir.attachment&id=17 => gene
rated 1192 bytes in 149 msecs (HTTP/1.1 200) 4 headers in 248 bytes (1 switches
on core 0)
No handlers could be found for logger "openerp.addons.base.ir.ir_attachment"
[pid: 9744|app: 0|req: 1/8] 116.22.142.145 () {44 vars in 810 bytes} [Tue Sep 16
 07:05:24 2014] GET /web/js/website.assets_frontend/a0382f4 => generated 0 bytes
 in 6399 msecs (HTTP/1.1 200) 5 headers in 290 bytes (1 switches on core 0)
No handlers could be found for logger "openerp.addons.base.ir.ir_attachment"
[pid: 9742|app: 0|req: 1/9] 116.22.142.145 () {44 vars in 815 bytes} [Tue Sep 16
 07:05:24 2014] GET /web/css/web.assets_common/a5f2994 => generated 0 bytes in 7
283 msecs (HTTP/1.1 200) 5 headers in 276 bytes (1 switches on core 0)
No handlers could be found for logger "openerp.addons.base.ir.ir_attachment"
[pid: 9743|app: 0|req: 1/10] 116.22.142.145 () {44 vars in 827 bytes} [Tue Sep 1
6 07:05:24 2014] GET /web/css/website.assets_frontend/a0382f4 => generated 0 byt
es in 7604 msecs (HTTP/1.1 200) 5 headers in 276 bytes (1 switches on core 0)
[pid: 9742|app: 0|req: 2/11] 116.22.142.145 () {46 vars in 899 bytes} [Tue Sep 1
6 07:05:32 2014] GET /website/static/src/img/banner/color_splash.jpg => generate
d 0 bytes in 1 msecs (HTTP/1.1 304) 3 headers in 147 bytes (0 switches on core 0
)
[pid: 9742|app: 0|req: 3/12] 116.22.142.145 () {46 vars in 885 bytes} [Tue Sep 1
6 07:05:32 2014] GET /website/static/src/img/banner/mango.jpg => generated 0 byt
es in 1 msecs (HTTP/1.1 304) 3 headers in 147 bytes (0 switches on core 0)

**Comment by Yenthe666** [comment]
Hi @rainberg ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Please do try to provide more info when creating a report, such as steps on how to reproduce it.

Regards,
Yenthe
