### ISSUE TITLE
[11.0] Landed cost don't consider returns

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#24286]
Impacted versions:
11.0

Steps to reproduce:
- Create an OC
- Receive products
- Return part of the products

Current behavior:
- When creating a landed cost for the picking Odoo won't consider the returned products.
**- In case of a mistake (which happened to a customer) there is no way to fix the picking after validated so that the landed cost is only by the products which were actually received.**
- In the landed cost calculation there is no way to exclude a product from calculation, or change the value of a line and have that difference distributed to the other lines.

Expected behavior:
- Be able to fix human errors and distribute costs accordingly.

**Comment by pedrobaeza** [comment]
I would say that this is not a correct use case, as the costs are the same if you return the picking or not, as the thing that provokes the cost has been already expensed (like the delivery).

@sle-odoo what do you think?

**Comment by gustavovalverde** [comment]
What I've seen is a Landed Cost validated by mistake; and those mistakes are **costly**; because there's no refund, cancel or anything.

There should be an option to at least cancel a landed cost; or a procedure to undo the mistake.

**Comment by edsersolis** [comment]
Any comments on this? As @gustavovalverde states, user should be able to cancel the Landed Cost, and even better if we can change it back to draft after cancelling.

**Comment by sle-odoo** [comment]
Hi,
The user can always create an accounting entry to cancel the landed cost, so i don't think it's really a blocking issue.

Regards

**Comment by gustavovalverde** [comment]
How does an accounting entry will revert the valuation of an specific product? As you know, if I'm doing a landed costs with hundreds of products, the result is hundreds of account moves each one with the product_id that's being affected. To revert that, I'd have to do 1 accounting entry, with no option to specify the product_id.

I don't see a workaround for this.

**Comment by sle-odoo** [comment]
> with no option to specify the product_id.

Indeed you need to display the product_id in the form view.

**Comment by gustavovalverde** [comment]
But that would require to manually do hundreds or thousands of journal entries to accomplish a simple task.

**Comment by sle-odoo** [comment]
okay you got it, i was about to answer you just have to filter the account moves list and reverse them all at once, which is working accounting wise, but then we have an issue in the valuation report. when this is fixed i'll close this issue again.

**Comment by sle-odoo** [comment]
Actually the easiest way is to create a new landed cost cancelling the other one, so if you added a lc of 100 on wh/in/001 you simply have to add a lc of -100 on wh/in/001. It's even easier: all the necessary account moves are created automatically and the valuation is correctly impacted.
