### ISSUE TITLE
website public user session expired always w/ ajax requests

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#24289]
**Impacted versions:** v9 to v11

**Steps to reproduce:** fetch some records w/ proper permission via JS in the frontend

**Current behavior:** session expired

**Expected behavior:** give me those records

**Quick solution that is working for all our projects:** 

```python
class IrHttp(models.Model):

    _inherit = 'ir.http'

    def _auth_method_user(self):
        try:
            return super(IrHttp, self)._auth_method_user()
        except SessionExpiredException:
            return self._auth_method_public()
```

Taken from https://github.com/OCA/web/pull/402

Full explanation w/ a use case (for v9 at that time) https://stackoverflow.com/questions/40630972/how-to-give-anonymous-user-access-to-rpc-api

**Comment by Yenthe666** [comment]
@ged-odoo could one of the guys at your team have a look please?

**Comment by simahawk** [comment]
I guess we can close this one :wink
