### ISSUE TITLE
product.supplierinfo product_uom should be a stored field not a related one to avoid a bug in supplierinfo

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#24308]
https://github.com/odoo/odoo/blob/a36ff26ce0954c57c00b3ef691714aaf0b5f7eb6/addons/product/models/product.py#L585

https://github.com/odoo/odoo/blob/a36ff26ce0954c57c00b3ef691714aaf0b5f7eb6/addons/product/models/product.py#L587

The product_uom field on product.supplierinfo should be a stored field to avoid a bug that happens as described below:
- create a ProdA with uom_id KG and uom_po_id KG and cost price 10
- create PO for ProdA with UoM Ton and price 10,000 from a vendor Vend1
- confirm the PO and receive the shipment
- create and validate the vendor bill
if you try to create a new PO with ProdA from Vend1 with KG UoM the price will be 10,000 for the KG instead of 10 which means that the supplierinfo stored the wrong price for the default UoM due to the related field.

To fix this bug we need to compute_price for the supplierinfo UoM and change the related field to stored one.

**Comment by sle-odoo** [comment]
Hi,
I'm closing since it actually works in v13, i didn't find the bug fix though.

Regards
