### ISSUE TITLE
[Bug] [v7] crm.lead triggers wrong on_change_partner

### ISSUE THREAD

**Issue by OSguard** [odoo/odoo#2430]
If you select a partner to create a crm.lead a onchange method will be call to fill in all data fields.

The crm.lead object has the method "on_change_partner" but the view "crm.crm_case_form_view_oppor" triggers the method "on_change_partner_id" method witch will be the method of the object "base_stage" in the "base_status" model.

As a result the following fields are not copied:
- mobile
- fax
- function
- title
- opt_out
- section_id

Affected Version: V7

How to fix:
As v7 is stable, we can not rename the method in crm.lead also changing the view also would not help existing installation. So the best way is to add a patch to base_status/base_stage.py

**Comment by Yenthe666** [comment]
This has been fixed in https://github.com/odoo/odoo/commit/c4339e0cec330e5ad29c9b7607d56b3af745b561 and https://github.com/odoo/odoo/commit/56f3f01491f3c682f3604c6d0011d7ecfbbaa210 but it was never closed.
