### ISSUE TITLE
[11.0] Cannot start inventory

### ISSUE THREAD

**Issue by aitorbouzas** [odoo/odoo#24323]
Impacted versions:
11.0

Steps to reproduce:
Start a new inventory of a full location.

Current behavior:
SQL fails because the search of locations made in
```
    def _get_inventory_lines_values(self):
        # TDE CLEANME: is sql really necessary ? I don't think so
        locations = self.env['stock.location'].search([('id', 'child_of', [self.location_id.id])])
        domain = ' location_id in %s'
        args = (tuple(locations.ids),)
```
returns no locations.

Expected behavior:
Expected to get correct list of ids to add them in args, but it fails.

Video/Screenshot link (optional):
I've checked in the shell the search and it didn't work ok, for some reason "child_of" operator is not working in the shell.

![question](https://user-images.githubusercontent.com/11627953/39002698-66e49214-43f9-11e8-9b3e-3219ae09d1fc.png)

**Comment by pedrobaeza** [comment]
Please try to reproduce it in runbot, as this seems that can be a problem with your DB (and parent_left/parent_right fields not correctly computed).

**Comment by pedrobaeza** [comment]
Indeed, and there's no more answers, so closing.
