### ISSUE TITLE
may be it is better

### ISSUE THREAD

**Issue by xunonxyz** [odoo/odoo#24327]
Impacted versions:
11.0
Current behavior:
`    def update_db(self, model, columns):
        if self.comodel_name in model.env:
            comodel = model.env[self.comodel_name]
            if self.inverse_name not in comodel._fields:
                raise UserError(_("No inverse field %r found for %r") % (self.inverse_name, self.comodel_name))
`
when raise error, i do not which model cause the error
Expected behavior:
`                raise UserError(_("No inverse field %r found for %r in model %r") % (self.inverse_name, self.comodel_name, model.name))`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please don't report this as issue. Do a PR if you think it's something to qualify.
