### ISSUE TITLE
Sale order margin shouldn't use product purchase price directly

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#24339]
**Impacted versions:** 8.0, 9.0, 10.0, 11.0

**Steps to reproduce:**

1. Create a product X with sale price 3000 € and purchase price 2000 €
1. Create a new sales quotation
1. Add the product X on the sales order lines and set the purchase price to 0 €
1. Save the quotation

**Current behavior:**
The margin for this order will be 1000 €

**Expected behavior:**
The margin for this order should be 3000 €, because the purchase price is 0 €.

**Video/Screenshot link (optional):**
In this screenshot you see the problem. We sell a Computer Case, the margin from that is $ 5. We also sell two iPods with zero cost and the margin from that is $ 20. So the margin should be $ 20, but instead it shows $ 3 and that is very confusing. 
![selection_351](https://user-images.githubusercontent.com/1525066/39042905-bb68df3e-4494-11e8-9992-2dae409765da.png)

I think it's wrong to check the purchase price directly from the product because Odoo is doing something secretly behind your back that you might not want. I don't see any reason why it couldn't read it only from the `purchase_price` field because anyway `product_id`'s `onchange` will read the purchase price from the product on to the order line.

**Comment by mlaitinen** [comment]
Another expected result could be to ignore the lines where the Cost is 0. That would be less worse than having Odoo do stuff behind your back.

**Comment by nhomar** [comment]
>> Another expected result could be to ignore the lines where the Cost is 0. That would be less worse than having Odoo do stuff behind your back.

Hello @mlaitinen 

IMHO this is a correct behavior, I expect the margin to be either what product says or what the line says.

This is useful when you are evaluating perpetual (with accounting properly set) then you will have the margin closer to what the accounting will say.

Everything has a cost, cost 0 does not make sense in almost any scenario (even if you sale services that you produce you have a cost)

I think this is a proper behavior the one you are having.

Feel free to reopen if you do not agree or argument more deeply if you find a scenario where the cost must be considered forced to 0.

**Advice:** Try to set a cost of 1 (or a little amount) if you want to be **almost** 0
