### ISSUE TITLE
"Many2many_tags" widget not working in tree view odoo-10

### ISSUE THREAD

**Issue by muhsinalungal** [odoo/odoo#24334]
Impacted versions:
odoo-10
Steps to reproduce:
go to product variant list view
Current behavior:
widget="many2many_tags" not working properly
Expected behavior:
fixed the same in odoo-11
Video/Screenshot link (optional):
![screenshot-321439-10-0-87b42a runbot14 odoo com-2018 04 20-10-40-27](https://user-images.githubusercontent.com/26205626/39031701-6abbf2ea-4487-11e8-842b-e0d932e99b3b.png)

**Comment by pedrobaeza** [comment]
Why is not working? Can you be a more specific? I only see one screenshot (I suppose for v10). How is the same on v11?

**Comment by muhsinalungal** [comment]
![odoo-11](https://user-images.githubusercontent.com/26205626/39032979-928f62c4-448d-11e8-9a02-374c23e5d701.png)

**Comment by pedrobaeza** [comment]
But I still don't see the problem. That's a change in the visual appearance, and in my opinion, it's now better than before.

**Comment by muhsinalungal** [comment]
@pedrobaeza 
But I can see the same comparing both versions in the runbot, please look through it.

**Comment by Yenthe666** [comment]
@pedrobaeza he is talking about the label styling that is missing in V10 in the tree view, which you can see on V11 on the second screenshot.
It is just a cosmetic change though, no? I don't see anything breaking or big issue and the cosmetics are better on 11.0

**Comment by muhsinalungal** [comment]
@Yenthe666 
you said it, 
not a big issue, just mentioned,
thank you both..
