### ISSUE TITLE
[Bug][v7,v8,master] crm.lead on_change_partner_id missing fileds 

### ISSUE THREAD

**Issue by OSguard** [odoo/odoo#2435]
If you create a new crm.lead an select an existing partner the method on_change_partner_id will be triggered but some information are not copied from partner by this method:
- function
- title
- opt_out
- section_id

Affected Version: v7, SaaS-x, v8, master

**Comment by askz** [comment]
I confirm the bug.

**Comment by Yenthe666** [comment]
Hi @OSguard,

Thank you for your report.
This has been fixed in https://github.com/odoo/odoo/commit/56f3f01491f3c682f3604c6d0011d7ecfbbaa210 and https://github.com/odoo/odoo/commit/c4339e0cec330e5ad29c9b7607d56b3af745b561 actually.
Sorry for the late feedback.

Regards,
Yenthe
