### ISSUE TITLE
User without administration access can enable “Developer mode” 

### ISSUE THREAD

**Issue by MohsenWaleed** [odoo/odoo#24361]
Impacted versions: 11.0
Steps to reproduce:
Create a new user and grant it manager access for any module (Here I granted it manager in inventory). For Administration, I left it empty.
 
![image](https://user-images.githubusercontent.com/24973578/39087413-4eab4b78-45a9-11e8-844a-be0af15bcb8c.png)

Then access to the system with this new created account and click inventory menu and you will see it as below: 
 
![image](https://user-images.githubusercontent.com/24973578/39087422-5c0f73de-45a9-11e8-8e9f-b66b7baab582.png)

Then add “?debug” after “web” to the address bar and see what you will get:
http://localhost:8069/web?debug#view_type=kanban&model=stock.picking.type&action=137
You will see the developer Tools icon and you will see new menus in the configurations and you will be able to open them and amend them

![image](https://user-images.githubusercontent.com/24973578/39087424-64ad039e-45a9-11e8-8a32-d1bcbd9e1ea1.png)
 
Current behavior:
User able to activate the developer mode through URL by adding “?debug” after “web” and he will able to see the hidden configuration and amend them and can access the developer Tool.

Expected behavior:
User shouldn’t able to activate developer if doesn’t have access to Administration even through the URL.

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
hello @MohsenWaleed 

I think you are a little confused with the Manager for administration given, you can change this behavior by yourself, but it is not what you need to do when you want to give access to all apps for a customer, you should give manager per app.

**Comment by MohsenWaleed** [comment]
Hello @nhomar,

As you can see from my first screenshot, I never gave any access for administration and from the second screenshot you will see that the user have access to configuration as a manager (but there is no menu names "Intercoms" or "Barcode nomenclature") and when a use add "?debug" to URL after "web"  there are a new menus shown in the configuration as you can see from the third screenshot, These menus not shown only if the user active the "developer mode" and our user have no access to administration to active the "developer mode: but he able to active it through inject "?Debug" in the URL.

**Comment by MohsenWaleed** [comment]
I know you already closed this issue but issue not solved.

I will explain it in other words, In Odoo, only admin users have access to "Activate Developer mode" from settings menu but any other user who doesn't have access to settings menu able to active developer mode by typing ?debug in the URL and he will be able to see more menus and able to change them as well as I mentioned in the issue above?

**Comment by Jerry6869** [comment]
Yes. I have same issue. Btw, is this one help? https://gitlab.merchise.org/merchise/odoo/commit/69e38dcf356c8142544d360c8ac332fd8dd51b2b

**Comment by dinoherlambang** [comment]
i have the same problem, have you find the solution?

**Comment by dinoherlambang** [comment]
i still have the same problem with version 13, have you found any solution to avoid non-admin user accessing developer mode? i know there are tricky way in odoo store a module to hide the button.. but is there any better solution?
