### ISSUE TITLE
QR code not being correctly printed

### ISSUE THREAD

**Issue by lualcontre01** [odoo/odoo#24362]
[Etiqueta QR (28).pdf](https://github.com/odoo/odoo/files/1935171/Etiqueta.QR.28.pdf)
Impacted versions:
10.0
Steps to reproduce:
Print report from form view
Current behavior:
The QR generated ignores anything after #
Expected behavior:
i expect to generate a QR from an URL
http://localhost:8071/web?#id=23&view_type=form&model=account.asset.asset&menu_id=143&action=235
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get what is the problem. Is there any error? Steps to reproduce it?

**Comment by lualcontre01** [comment]
The problem is that in intend to transform an URL into a QR, but anything after a # just dont show in the QR.

For example, if y try to transfor this string "Hello#Wrold" into a QR i will only transform "Hello"

**Comment by pedrobaeza** [comment]
But transforming how? Put the code you are using.

**Comment by lualcontre01** [comment]
Im just doing whats in the odoo doc.

<img t-att-src="'/report/barcode/?type=%s&amp;value=%s' % ('QR',o.get_asset_url())" style="width:300px;height:300px;"/>

**Comment by lualcontre01** [comment]
anyone?

**Comment by exceedsodar** [comment]
Try to replace `#` with `%23` before putting it in the `t-att-src=`

I suggest you to add `.replace('#','%23')` in your method `get_asset_url()`

**Comment by lualcontre01** [comment]
Thanks for the answer, but if i change the '#' the URL wont work anymore, i
think odoo uses it to send an ID, its like the predecessor of the ID:

localhost:8069//web?#id=7form_view=1&tree_view=7

The last url will send me to the form view wich is what i intend, bit if i
replace the # with a %23 odoo wont be able to find the view i try to show
and will send me to another view.

2018-05-03 3:12 GMT-04:00 exceedsodar <notifications@github.com>:

**Comment by mga-odoo** [comment]
I think o.get_asset_url() method returns the qrcode image that is written by you, if i am not wrong, the correct way to put the qrcode on the report is, put the data which used to generate the qrcode,   instead of o.get_asset_url(), it will generate the qrcode and attached the image on report, look at https://github.com/odoo/odoo/blob/11.0/addons/stock/report/report_lot_barcode.xml#L36

`<img t-if="o.field_qr_code_data" t-att-src="'/report/barcode/?type=%s&amp;value=%swidth=%s&amp;height=%s' % ('QR',o.field_qr_code_data, 200, 200)" class="img img-responsive img-thumbnail"/> 
`

**Comment by exceedsodar** [comment]
> I think o.get_asset_url() method returns the qrcode image that is written by you

I rather think that he want his QR code to output something like: `localhost:8069//web?#id=7form_view=1&tree_view=7`

For this example, replace `#` with `%23` and `&` with `%26`:

`<img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('QR','localhost:8069//web?%23id=7form_view=1%26tree_view=7',200,200)" style="width:200px;height:200px;"/>`

If you scan the QR code generated by this code, you'll get the original url with the # and &.
But if you write directly the encoded url (with the `%23`) on the navigator, Odoo may not recognise it.

It worked for me with odoo11

[https://www.w3schools.com/tags/ref_urlencode.asp](url)

**Comment by lualcontre01** [comment]
Ok, i will try, Thanks for the answer.

2018-05-03 6:33 GMT-04:00 exceedsodar <notifications@github.com>:

**Comment by JayVora-SerpentCS** [comment]
@pedrobaeza you may close this.

**Comment by pedrobaeza** [comment]
Thanks for the follow-up.
