### ISSUE TITLE
[11.0] Bad Translations in Chinese!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#24365]
Impacted versions:
11.0

Steps to reproduce:
Search odoo code by the following keywords and filter files with *cn.po:
mail.template,report_name

Current behavior:
Many wrong translations cause odoo running error:
jinja2.exceptions.TemplateSyntaxError: unexpected char '‘' at 18

Expected behavior:
DO NOT using auto translation!!! PLEASE do complete  translation REVIEW!!!

Video/Screenshot link (optional):
<img width="868" alt="bug" src="https://user-images.githubusercontent.com/1243299/39101403-c452a5ce-46cb-11e8-8b03-8b4bc6fb6127.png">

**Comment by woodheadhn** [comment]
Bad Translations

**Comment by niulinlnc** [comment]
Chinese translation is too bad！！

**Comment by xhair** [comment]
Chinese translation is too bad！！
Some of the original translations are quite good. Now many translations are too unprofessional translated by translation companies.

**Comment by elicoidal** [comment]
@fpodoo This is becoming quite an issue with more and more complaints.
The community knows the language of the implementations and the translation company is overriding terms with unrelated ones.

**Comment by digitalsatori** [comment]
Another example. The transaltion done by the transaltion company changed the order of the variables in the text, which caused a type error. 
<img width="1282" alt="odoo_11_0___transifex_" src="https://user-images.githubusercontent.com/140909/39105019-d161bd4e-46e5-11e8-96cd-efdfdf2790a0.png">

**Comment by jlzhou** [comment]
![bug2](https://user-images.githubusercontent.com/1243299/39105657-9ffa858e-46e9-11e8-8279-5c7de6704386.png)
Translation BUG in the website footer!!!!

**Comment by Yenthe666** [comment]
@mart-e for your interest, multiple complains about the bad Chinese translations (again).

**Comment by mart-e** [comment]
@jlzhou I believe we already stated about that issue at #23841. Creating more issues with more exclamation marks is not helpful.
Thank you to stay cordial and do report the issues on transifex, pinging the translator and myself.

**Comment by jlzhou** [comment]
@mart-e suggest to hire full-time employee to manage Chinese translation instead of the community review. Too many Chinese translation mistakes cause great odoo running in bad quality.

**Comment by Yenthe666** [comment]
@jlzhou why don't you contribute and change the wrong terms though? After all it is an open source effort. We do it for Dutch too.

**Comment by elicoidal** [comment]
@Yenthe666 I think this is not the problem here: last year Chinese translation was handled by the community and Chinese was one of the highest translated language.
Decision has been made to rely on external translation company to supersede community effort: in principle to improve the quality of the translation.
A lot of "proper terms" maintained originally by the community have been removed/changed.
Here we are not complaining of the effort by the community but the fact that this effort is somehow wasted/tainted by external translators.

**Comment by Yenthe666** [comment]
Hmm, that is a pity to hear.. Usually things should improve when you have a paid service but that doesn't seem to be the case then. I guess the final call is still up to @mart-e and @fpodoo

**Comment by mart-e** [comment]
@elicoidal @jlzhou even if I am rejecting this github issue, I do consider your feedback. We have forwarded your comment about the bad translations.

The fact that bad translations are made: honest mistakes happens. These are not machine translations (or you would not get this kind of errors). Bad placeholder position is the kind of errors that happens all the time with every translation team unfortunately. It should obviously be checked but it does not seem problematic either.

The fact that good translations are changed with incorrect one is however not acceptable. This is something we will make sure no longer happens (the translations you are showing are a few months old, before the first feedbacks)

**Comment by jlzhou** [comment]
@mart-e @Yenthe666 I am glad that I became the reviewer of odoo Chinese translation team on Transifex in few days ago. I will do the correction in next days, thank you for your attention.
