### ISSUE TITLE
[11.0] Forum: Could not Create and Edit Documentation stage from Kanban View

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#24377]
Impacted versions: 11.0

Steps to reproduce: Go to Website/Forum/Documentation Posts --> Create New Stage and Edit Without Refreshing the Page

![](https://image.prntscr.com/image/00oNC_6ORS6HBa_XUghh4w.png)

![](https://image.prntscr.com/image/SwCqL3ejTRmGTWZgDctBxw.png)

![](https://image.prntscr.com/image/92blOg2jR8mf0441rJYtiw.png)

![](https://image.prntscr.com/image/dII-rybiTg2QPPZno_ZdYQ.png)

Current behavior: Stage is not Visible in Kanban View

Expected behavior: Stage Should be Visible

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks a lot for your report. I've just reproduced this and that has to be a bug 😉 It isn't even saved and the problem is not only there but also in other views so it is framework related.

**Comment by sswapnesh** [comment]
@Yenthe666 I believe we are missing something here. 
Records (Basically Stages) Created from Kanban are Saved. 
![](https://image.prntscr.com/image/QdTyiO4wTHGAbKej-Qq2gg.png)

It worked well in CRM --> Pipeline because Kanban displays Empty stages (Even there are not Records there.) 
![](https://image.prntscr.com/image/ejsoGl2KSyyoiHUGPINmDw.png)

In Project --> Tasks, It shows Stage with Records in it, So we didn't notice newly created Stage as It doesn't have any record in it.
![](https://image.prntscr.com/image/x7HaMLT2SgWhWltFvtBFsw.png)

After moving task to new stage
![](https://image.prntscr.com/image/YbefHPAhTke1FdhSWMdZ9g.png)

Closing the Issue as this is Normal Behaviour I believe.

**Comment by Yenthe666** [comment]
Yeah, just not entirely clear I guess. :)
