### ISSUE TITLE
raise Exception("bus.Bus unavailable") with /longpolling/poll  while setting workers

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#24375]
Impacted versions:11

Steps to reproduce: after setting wrokers other than 0 only 

Current behavior: raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
2018-04-23 14:34:22,984 18239 INFO vedb werkzeug: 192.168.6.234 - - [23/Apr/2018 14:34:22] "POST /longpolling/poll HTTP/1.1" 200 

Expected behavior: it should be working fine 

Hi There, I have gone through all the  questions mentioned before for setting upto reverse proxy but its not being stoped its make my logs full,  longpolling comes very fast.  anyone have faced and solved this issue 

Thanks

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by sandeepksrana** [comment]
Hi @pedrobaeza  I had did the same based on the link you shared even many time but its the same issue, can we remove this as we don't need the chat system or longpolling thing,  please let me know, here is the screen shot of logs coming up and even very fast , system working fine but exception coming up in logs 
![screenshot from 2018-04-25 12-43-48](https://user-images.githubusercontent.com/3022856/39231042-60766b6e-4886-11e8-89b5-85d0ad4009d0.png)

**Comment by pedrobaeza** [comment]
If you don't want that, remove workers, or fix the underlying problem (a bad configuration).

**Comment by sandeepksrana** [comment]
Hi removing worker is no the solution i think, the worker are the process so you can speed up  your server. please open my issue thanks

**Comment by alexis-via** [comment]
To solve that, you need 2 things:
1) with your web browser, don't connect directly via HTTP to port 8069 ; always connect via the proxy (HTTP port 80 or HTTPS port 443 I guess)
2) setup your nginx with the section "location /longpolling" as explained here:
https://odoo-development.readthedocs.io/en/latest/admin/longpolling.html

**Comment by OdooConcepts-OC** [comment]
> To solve that, you need 2 things:
> 
> 1. with your web browser, don't connect directly via HTTP to port 8069 ; always connect via the proxy (HTTP port 80 or HTTPS port 443 I guess)
> 2. setup your nginx with the section "location /longpolling" as explained here:
>    https://odoo-development.readthedocs.io/en/latest/admin/longpolling.html

it worked
