### ISSUE TITLE
Issue on reception The combination of serial number and product must be unique!

### ISSUE THREAD

**Issue by carlosecv** [odoo/odoo#24381]
Impacted versions: 

11.0 CE

Steps to reproduce:You must have tracking lots on products installed

Current behavior:
Create a product with tracking by lots
Create a reception for one Lot number on inventory, 
then create a new reception with the same lot number and product
I couldn't receive same lot product twice Selected Tracking by lots not unique serial numbers

Expected behavior:
the product is setting Tracking: By Lots. so if we use a lot number that has been used earlier the system must use it and not to try to create it we receive:The combination of serial number and product must be unique!

Video/Screenshot link (optional):
--

**Comment by sle-odoo** [comment]
hi,
you have to tick "use existing lots" in the settings of the picking type.

regards

**Comment by aliomattux** [comment]
There could have been slightly better description of the issue, however The recommendation by Odoo will not solve the problem. This issue is due to functional problem in code. This is also a duplicate of issue 24333
https://github.com/odoo/odoo/issues/24333
I provide free module fix for this issue.
