### ISSUE TITLE
Loading a product with Variants (The avg variants dimension is 10x7)

### ISSUE THREAD

**Issue by majeedid** [odoo/odoo#2439]
We have created a products some of which have variants with average dimension of 10*7
we found it takes like 4 to 15 minutes to load such product from our odoo server!!! which is impossible!!!. While our sister company with same product same variants dimensions can loads nortmally!.
Our  HW specs are quite high: Intel(R) Xeon(R) CPU X3430 @ 2.40GHz RAM 8GB

Sample of product@ our company using odoo:
http://sudanerp.com/shop/product/sonic-25

sample of our sister company using another e-commerce solution: https://billing.amanah.com/form/addplan.php?q=7&pid=59&f=5

I have been searching for  like 10 days to find a solution to such a problem with nothing!!!

Mageed

**Comment by Yenthe666** [comment]
Hi @majeedid,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
