### ISSUE TITLE
Bug with 2 fields with ace editor widget on same form view

### ISSUE THREAD

**Issue by hmartinet** [odoo/odoo#24398]
On Odoo 10, if 2 fields of the same object uses widget="ace" there is a js error "define is not a function" when loading mode-python.js.

**Comment by Yenthe666** [comment]
Dear @hmartinet,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
