### ISSUE TITLE
[account] wrong taxes in accounting setting with multicompany

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#24403]
Impacted versions:
* 11.0

Steps to reproduce:
* Create two company companyA and companyB
* Set the user with both companies
* With the user in companyA set the CoA and purchase/sale taxes
* With the user in companyB set the CoA and purchase/sale taxes
* Create one file e.g. into account/data/res_config_settings.yml
* Define the file in account/__manifest__.py

e.g. of file account/data/res_config_settings.yml
```yml  
   -
     Now set properly the company accounting chart template
   -
     !record {model: res.config.settings, id: account_configuration}:
       {
           'company_id': 'base.main_company',
           'group_multi_currency': 1,
       }
   -
    !python {model: res.config.settings}: |
      self.browse(ref('account_configuration')).execute()
```

Current behavior:
If update server with` -u account`  with admin user into companyB the taxes into companyA change to taxes of companyB

this is because [get_values](https://github.com/odoo/odoo/blob/11.0/addons/account/models/res_config_settings.py#L64) method take the 
[company from the user](https://github.com/odoo/odoo/blob/11.0/addons/account/models/res_config_settings.py#L68) and when call  [set_values](https://github.com/odoo/odoo/blob/11.0/addons/account/models/res_config_settings.py#L77) the company_id(`base.main_company = companyA`) is from the definition of file .yml

Expected behavior:
do not change the taxes

Video/Screenshot link (optional):
https://youtu.be/-8exDdHzdus

**Comment by pedrobaeza** [comment]
Are you going to make a PR?

**Comment by kebeclibre** [comment]
@JulioSerna 
The yml code seems odd.
I would go for what group_multi_currency actually does:
 <code> self.env.ref('base.group_user').write({'implied_ids': [(4, self.env.ref('product.group_sale_pricelist').id)]}) </code>

Also, given that the res.config model is not an actual one, I wouldn't use it at all for installing stuff
I'd rather setup a post_init hook on the module, or anything else rather than this.

I'm closing this as, from my point of view, the use case is a misuse of Odoo

**Comment by JulioSerna** [comment]
@kebeclibre 

The issue is no about what the yml does
The yml could contain or setting whatever you want
I just show you in this issue that is a wrong behavior especially with taxes when res.config.settings is trigger by yml when update server

Could you please double check?

**Comment by kebeclibre** [comment]
@JulioSerna 
.... So it IS the design that is problematic
My point was that it is wrong to use res.config.settings this way.
That is a model that is designed for user interaction, not or programatic changes

Doing it in the code, you bypass onchanges, also probably the set/get values etc....
you are basically executing a res.config without anything in there apart from the group
