### ISSUE TITLE
Action applied only on first page when using select all checkbox on list views

### ISSUE THREAD

**Issue by yuriqp** [odoo/odoo#24405]
Impacted versions:
11.0

Steps to reproduce:
Go to a list view (for example: Sales -> Orders -> Quotations)
Apply a filter (for example: Quotations)
Modify the records per page in the list view, so there is more than one page for the filtered records
Use select all checkbox
Apply an action (for example: Delete)

Current behavior:
The action is applied only to the records on the first page

Expected behavior:
The action is applied to all records in the filter

Video/Screenshot link (optional):
![capture 2018-04-03 at 7 49 50](https://user-images.githubusercontent.com/8631284/39228277-936c5890-485d-11e8-8a74-0dabaf993ba4.png)

Comments:
Apparently, this behavior is already implemented (addons/web/static/src/js/views/list/list_controller.js, function getActiveDomain()) but only used for the export functionality.

I see there is a TODO comment, but haven’t been done. Is it because it is too complicated (some important structural change is required) or because is it too risky (hard to test the impact on other actions)

**Comment by pedrobaeza** [comment]
I don't consider this should be done everywhere, as it can lead to confusions. If you want to apply to all the recordset under the domain, change the page limit.

**Comment by mart-e** [comment]
>  Modify the records per page in the list view, so there is more than one page for the filtered records

The other way around, you can modify the records per page to show everything.
I agree with Pedro, it can be confusing if you apply to hidden records. If we change that, it must be clear in the interface, which is not yet the case.

**Comment by yuriqp** [comment]
You are right, somehow I was assuming the select all checkbox, as for all records and not all on the page. 
However, I still think that if one wants to perform an action for a large number of records (10000), could be too much to show them all on the page. Any alternative solution?

**Comment by mart-e** [comment]
On gmail you see this when you use the select all
![screenshot-2018-4-27 inbox](https://user-images.githubusercontent.com/564822/39362699-aa45b824-4a27-11e8-9e11-d751fc140d23.png)

Could be an idea of implementation.

**Comment by Yenthe666** [comment]
Good idea actually @mart-e!

**Comment by pga-odoo** [comment]
@mart-e @Yenthe666 ongoing dev for select all in list  https://github.com/odoo/odoo/pull/24198
![screen shot 2018-05-09 at 2 58 48 pm](https://user-images.githubusercontent.com/7629089/39807355-b778108e-5399-11e8-8527-a7c56af239b1.png)

**Comment by Yenthe666** [comment]
@pga-odoo that is so awesome! Thanks a lot for the followup and the example!

**Comment by ZERO20** [comment]
works for odoo 13?
