### ISSUE TITLE
Group by company_dependent/property field

### ISSUE THREAD

**Issue by erkesado** [odoo/odoo#24411]
Impacted versions: 10.0

Steps to reproduce: Install Sales app with demo data. Go to Apps > Sales > Sales > Customers.
Try to group by "Customer Payment Terms" which is a company dependent field (traditionally property field).

Current behavior: Even though a company dependent field is searchable, it is not groupable.

Expected behavior: Is there anyway to group by a company dependent field.

**Comment by pedrobaeza** [comment]
That's a limitation of the framework and how SQL works, so there's no possibility of that.

Closing as it's technically not possible for now to do this.

**Comment by erkesado** [comment]
Thanks for your quick response.

**Comment by JavierB7** [comment]
Hello. @pedrobaeza please could tell us if this was implemented in other versions?, we are using Odoo 14 and the **company_dependent** fields do not appear in the grouping list. Thanks!
