### ISSUE TITLE
Possible to edit a postes journal (account_move_line)

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#24423]
Impacted versions: 11

Steps to reproduce: Go to Journal Items > open a journal item > click edit > change partner > save

Current behavior: new partner (and also label can be edited) has been saved to a posted journal entry

Expected behavior: it should not be possible to change a posted journal entry

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
It's possible to change that options if you haven't posted yet the entry, as your steps suggest, but that's normal. What is the error then?

**Comment by sswapnesh** [comment]
@pedrobaeza  I can Reproduce same on Runbot (v10 and v11) for Posted Entries too. ( field `partner_id` should be considered ad the Legal fields)

**Comment by pedrobaeza** [comment]
Again I don't understand the problem: if you try to edit a posted journal item, this is what you get:

![seleccion_004](https://user-images.githubusercontent.com/7165771/39292530-bfea0b18-4936-11e8-8fda-c296b72a2166.png)

Partner is already readonly.

**Comment by ahetland** [comment]
Hi, if you go to a Journal Item directly a posted entry is editable ...

Thanks,

Alex

 

 

Gesendet: Donnerstag, 26. April 2018 um 09:48 Uhr
Von: "Pedro M. Baeza" <notifications@github.com>
An: odoo/odoo <odoo@noreply.github.com>
Cc: Alexander <a.hetland@web.de>, Author <author@noreply.github.com>
Betreff: Re: [odoo/odoo] Possible to edit a postes journal (account_move_line) (#24423)


Again I don't understand the problem: if you try to edit a posted journal item, this is what you get:



Partner is already readonly.

**Comment by pedrobaeza** [comment]
I have gone directly... Please put the detailed steps then for that operation.

**Comment by ahetland** [comment]
Accounting > Adviser > Journal Items > ... click any > Edit > ... now possible to change partner + label

**Comment by pedrobaeza** [comment]
But naturally on the UI you can't edit the partner_id. It's something you are doing by code?

**Comment by ahetland** [comment]
no this is possible in the UI ... 
![screenshot_2018-04-26_11-26-28](https://user-images.githubusercontent.com/3541706/39301043-1ef7287c-494e-11e8-8545-f47f556d0b2e.png)

**Comment by sswapnesh** [comment]
@pedrobaeza  Partner is editable in v11. (Tested in fresh local instance too.)

**Comment by ahetland** [comment]
Hi Pedro, adding name to the line above caused a new problem (not possible to post entry) ..
so below "name" does not work
if any(key in vals for key in ('account_id', 'journal_id', 'date', 'move_id', 'debit', 'credit', 'partner_id', 'name')):

**Comment by sswapnesh** [comment]
@nim-odoo  I proposed Same Solution in PR #24432 linked to this Issue.

**Comment by nim-odoo** [comment]
@sswapnesh sorry I didn't see it :(
