### ISSUE TITLE
Nightly repository - bad signature

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#24426]
Impacted versions: 11

Steps to reproduce: 
apt-get update

Current behavior:
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://nightly.odoo.com/11.0/nightly/deb ./ Release: Następujące podpisy były błędne: BADSIG DEF2A2198183CBB5 Odoo SA, Linux Package Signing Key <info@odoo.com>

**Comment by d-fence** [comment]
@zbik2607  can you check if you are still impacted ? There was an issue last night with our build system that is now fixed.

**Comment by zbik2607** [comment]
Today everything is fine.
