### ISSUE TITLE
Inventory Stock On-Hand only shows number of first warehouse, not total

### ISSUE THREAD

**Issue by ossimantylahti** [odoo/odoo#24428]
Here is my first bug report, so please bare with me ;) 
If more info is needed then please let me know.

Impacted versions: 11

Steps to reproduce: add extra modules besides Inventory (Sales, CRM, Purchases, Accounting)

Current behavior: With the same product in multiple warehouses it will only show the amount of the first warehouse in the on-hands amount, not the expected total of all the warehouses in on-hands

Expected behavior: With only the Inventory module installed it displays the total amount of all the warehouses on the products on-hand

Video/Screenshot link (optional):

![cap01](https://user-images.githubusercontent.com/37711285/39257790-fa754082-4877-11e8-9082-86adb25ee742.PNG)
![cap02](https://user-images.githubusercontent.com/37711285/39257791-fa909b52-4877-11e8-9829-74d8c7dd7446.PNG)

**Comment by sle-odoo** [comment]
Hi,
I just tested on runbot, activated mutli-warehouses, created a product and two inventory adjustments: one in wh1, the other in wh2. The quantity on hand correctly sums the quants in all the warehouses.

I see it isn't working in your screenshot, did you change something in your locations configurations?

What would be useful is the "view_location_id" field on the warehouse, and correctly check that the warehouses'locations are correctly located under "Physical locations".

Regards
