### ISSUE TITLE
[10.0] Discuss - The public setting for the channel does not work.

### ISSUE THREAD

**Issue by collex100** [odoo/odoo#24431]
Impacted versions:
[10.0] 

Steps to reproduce:
I make the channel public.

Current behavior:
The channel no one sees. In addition, who created it

Expected behavior:
The channel should see everything.

Video/Screenshot link (optional):

Administrator
![screenshot_4](https://user-images.githubusercontent.com/11208423/39266170-e4d9ca2c-48d1-11e8-898b-f857dfa93b1d.jpg)

User
![screenshot_5](https://user-images.githubusercontent.com/11208423/39266178-e984b4ba-48d1-11e8-86a1-8da860c0b24e.jpg)

**Comment by Yenthe666** [comment]
@collex100 you can fix this by adding the users under the "Members" tab though.

**Comment by collex100** [comment]
@Yenthe666 So it's the same thing that I signed the user. It's not the user who chose to subscribe to the channel, I signed it myself. What's the point in setting up a public one?

**Comment by Yenthe666** [comment]
I know, just suggesting a workaround. I'm not sure about this part as I never use it personally so this is for somebody from the services team (@tde-banana-odoo I summon you!)

**Comment by collex100** [comment]
I know about the workaround. I just thought for a long time about the trick of such settings. In the technical part, you can subscribe to the channel, but on the fact that in the foreground there is no way to subscribe to the channel, if someone does not sign you. So I finally decided to write, find out what is the trick of such an implementation.

**Comment by Yenthe666** [comment]
Dear @collex100,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
