### ISSUE TITLE
[11.0] chatter , jpeg/jpg type image crop size bug

### ISSUE THREAD

**Issue by kalway-tony** [odoo/odoo#24437]
Impacted versions:
V11
Steps to reproduce:
goto any model's chatter, send a message , upload an attachment , choose jpg type image.

Current behavior:
size of image become larger than origin

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31125609/39284418-b76dbc50-4945-11e8-9937-ee33c9ac10c2.png)
origin size is about 500kb

**Comment by pedrobaeza** [comment]
That's not the real size, but the transmitted one. Can you check the real size on the DB?

**Comment by kalway-tony** [comment]
@pedrobaeza It's true, but what users care about is not db size instead of opening the page quickly.

**Comment by pedrobaeza** [comment]
I haven't experimented this any way. Please include your test image and try to do it on runbot.

**Comment by chrizzTs** [comment]
This was fixed by #26575 
Please close!

**Comment by pedrobaeza** [comment]
Thanks for the pointer. Closing due to no answer by the original issuer and seems to be fixed.
