### ISSUE TITLE
res.partner display_name: other than Latin letters

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#24440]
Impacted versions: 10.0,11.0

Steps to reproduce: When entering a partner name for a cell for the first time, the name in the display is recorded in Cyrillic. The sorting is done according to these rules, but after the Latin display is written, the name does not appear and continues to be arranged in the original alphabet.

Current behavior: The function _compute_display_name in res.partner model is not correctly created. It creates the name for the name of the field name, but it is not for translation.  It creates the display_name from the field: name, but it is not for translation. As a result, the base language is recorded firmly in the base language with which the name is entered. As a result, different language users see an abnormal name ordering.

Expected behavior: to fix def _compute_display_name to fork on iso9 base for the languages mentioned therein, and add a search box display_name_xx based on that language. 

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Sorry for the late reply. I am not sure what you mean by "after the latin display is written". Have you made the name field translatable through a custom module?

**Comment by rosenvladimirov** [comment]
Hi,
I all ready fixed the all problems with multilang and ISO 9 support hire is module, inside is included 3-language support [l10n_bg_multilang](https://drive.google.com/file/d/16r_Br9b7Q8f4unn0U_4cer46gFIATQZW/view?usp=sharing)

**Comment by mart-e** [comment]
Ok thanks for the update, so this was not a request for odoo but for customisation. Doing it in a custom module is indeed the right way to do it.

**Comment by rosenvladimirov** [comment]
I think the multi-language is need to be more flexible when used for many languages, at moment The res partner support only one-language names when show on display and sorting and searching. My offer is to check the module and to see inside. And in some in account module, there is lot of wrong logic for EU deals.
