### ISSUE TITLE
[Proposal] Idempotent test execution

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24456]
As a general design flaw o test execution might be considered the double use of demo data, which might be affected by subsequent installs in a way to produce undesired side effects during test execution.

It would be helpful to have idempotent test execution, so that it is guaranteed repetitive tests on the same database will always return the same result.

This would make it a lot easier to include constant testing directly into the development cycle (like on auto reload, for example).

See: http://jasonpolites.github.io/tao-of-testing/ch4-1.1.html#rule-10-ensure-tests-are-isolated-and-idempotent for a contextualized argument.

/cc @yelizariev

**Comment by yelizariev** [comment]
May it be a problem of the tests itself, that uses demo instead of making necessary data \ updates in temporary database transaction?

**Comment by blaggacao** [comment]
Example Pricelist:

#### module A defines in demo data (pseudo xml):
```
id = pricelist.public
name = Public
...
```
at `create`, python defaults set currency to `EUR`,


#### module B sets
```
id = pricelist.public
currency_id = USD
```

QED

**Comment by blaggacao** [comment]
Not sure of the tracktion of this

**Comment by pedrobaeza** [comment]
The problem is to rely on that kind of demo data as said. You can't redo the previous state of demo data before performing a test.

**Comment by blaggacao** [comment]
Hi Pedro, I propose this for discussion. It is a (rather uncontested) flaw in the Odoo framework, so would you mind reopen? It was not meant for immediate shut down... :wink:

**Comment by pedrobaeza** [comment]
But as said is a problem on how you design your tests, not a flaw on Odoo itself.

**Comment by blaggacao** [comment]
@pedrobaeza I don't agree based on the arguments in the related document. As I said, would really appreciate not to shut the discussion down :wink:

**Comment by Yenthe666** [comment]
@pedrobaeza I believe it's not bad to keep this one open a little longer. Discussion and thoughts are never bad, right?
I can relate a bit with this issue. In Odoo.sh we also have some tests that fail because of previous tests or some tests that fail because they are short sided (always excepting English text for example). So in general I think tests could be improved a bit.

**Comment by mart-e** [comment]
Hi,

Please do keep in mind that tests are intended to work in specific conditions (i.e. our runbot) and the fact that it requires a specific environment, timezone or language is not a problem, the priority is to test the framework and the modules, not to have a tolerant test suite.
When testing with different parameters, getting a different result than expected and wrong result are not the same thing.

Relying on demo data in the tests definitely makes it less tolerant to changes (but makes it easier to test with data closer to production). This is however a choice we took, we already got endless internal discussions about this with @antonylesuisse and I don't think we consider changing that.

Making PR to make a test more tolerant is fine but is still an improvement (for master version, no guarantee to be accepted).

**Comment by mart-e** [comment]
@blaggacao I hear you and mostly share that opinion, but, as I said before, this was already discussed but rejected. I believe we have other priority like increasing the [test coverage](https://github.com/odoo/runbot/tree/master-coverage-moc) for instance.

I have personally no objections on PRs improving the test base if you have easy tweaks. Fully changing the way we build our tests is not going to happen at the moment.
