### ISSUE TITLE
Assign DEFAULT value on sql level

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#24461]
It could be implemented for fields with static values
**Impacted versions:**
all
**Steps to reproduce:**
* in one module add a required field with a default value to some model
* run CI tests in another module that doesn't depend on the first module and creates records in the model

**Current behavior:**
Error about ``NOT NULL`` value. 
See also 
https://github.com/odoo/odoo/commit/1d544087faee25463d6a4a83a581d3c311e780d4
https://github.com/odoo/odoo/commit/71181a0e39e825ba21b347af856b32d2056d7bb8
https://github.com/odoo/odoo/commit/dd47abdcc3ee1f8e3ad548989f80ebd40035d47c
https://github.com/odoo/odoo/commit/06a02ae4c22fe91c47702712420134e06c4d35d0
**Expected behavior:**
No error

**Video/Screenshot link (optional):**

**Comment by rafaelbn** [comment]
Thank @yelizariev :+1:  Ref: https://github.com/OCA/pos/pull/237

**Comment by pedrobaeza** [comment]
The problem with that is the extensibility. If you do it via SQL, then it can be inherited and changed.

**Comment by yelizariev** [comment]
@pedrobaeza do mean 

> If you do it via SQL, then it can **not** be inherited and changed.

I thought about it. Can we just update SQL scheme when new module redefine default? Or just consider default value as redefinition as non-static and make evaluation in python side?

**Comment by pedrobaeza** [comment]
Well, I think that complicates a lot the framework for a very specific case. The trend should be to not add required fields on inherited models. Put the required only on UI.

**Comment by mart-e** [comment]
Actually, even adding default in SQL would not solve it.
With your suggestion, we would be fixing the cases like
```python
purchase_warn = fields.Selection([..], required=True, default="no-message")
```
but these are actually the easy scenario.

Now, let say we have a field like:

```python
def _get_tomorrow(self):
     self.next_action_date = datetime.today() + datetime.timedelta(days=1)

next_action_date = fields.Date(required=True, default=lambda s: s._get_tomorrow())
```

The problem stays the same, we execute the tests with a subset of the code in the registry but the database is in a different state, with more fields and constraints. You have an inconsistency that you won't be able to fix by adding more info in the database.

Not linked to default values problem, imagine something like:

```python
# in module A
state = fields.State([('draft', 'To Approve'), ('done', 'Approved')], required=True)

def send_state_report(self):
    if self.state == 'draft':
         self.message_post("The object has not been approved yet, please be patient")
    else:
         self.message_post("Good, news! The object has been approved!")


# in module B
state = fields.State(selection_add=[('second', 'Second Approval Required')])

def send_state_report(self):
    if self.state == 'second':
         self.message_post("The object needs a second approval")
    else:
         super().send_state_report()
```

If you execute codes of module A without having the full registry loaded, you will end up with records in your database on which the `send_state_report` will give you incoherent results (while the code of module A is a bit naive but not wrong).
Wanting to execute tests without the full registry (and there is good reasons to do so) will always lead to these kind of inconsistency.
I am afraid we do not have good solutions for these except applying local workaround like at 1d544087faee25463d
