### ISSUE TITLE
[11.0] api.onchange not working for many2many_tags widget

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24497]
Impacted versions: 11

Steps to reproduce: Build your custom modul and extend with @api.onchange method
As example:
```
class ResPartner(models.Model):
    _inherit = 'res.partner'

    category_id = fields.Many2many('res.partner.category', column1='partner_id',
                                   column2='category_id', string='Tags')

    @api.onchange('category_id')
    def onchange_category_id(self):
        print(self.category_id)
```

Current behavior:
method is never called
Expected behavior:
method should called and print the ids

**Comment by pedrobaeza** [comment]
This is working on my side, so you should make something incorrect. Print only works in an interactive shell or log, so you should make another operation to make sure is not being executed.

**Comment by DR4RCON** [comment]
I have a semilar problem with other models and onchange method. As example I store image_variant to product.product then I trigger an onchange for same record. I have now a newID Object of that record. But no image_variant. Same in self._origin, no image_variant.

**Comment by pedrobaeza** [comment]
With the code you have put, this is working on my side, so if you don't provide more info, I'll close this issue as non reproducible.

**Comment by DR4RCON** [comment]
I close this, have to go more into the deep, why I have so much trouble with onchange methods. Thanks Pedro.
