### ISSUE TITLE
Odoo.sh - github connection with full access

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#24499]
Hi @amigrave @rim-odoo 

I find that the requested rights to connect github with odoo.sh are a little on evaluate while one just wants to test: https://twitter.com/fpodoo/status/989141923024777216. Especially access all private reposit.

![image](https://user-images.githubusercontent.com/16716992/39427076-b81e26f4-4c82-11e8-95a0-c149712e750f.png)

Regards

**Comment by rim-odoo** [comment]
Hello,

As Odoo.sh allows you to create branches into your repositories, yes, it requires write access to your repositories (and if you have bought an app on apps.odoo.com, you might prefer to test it in a private repo in order not to disclose its source...). 

This may look a bit overkill for people who "just" want to test an open source app, I do agree. But for now, we don't have finer-grained permissions requests for Odoo.sh. I'm not an expert of Github's permissions, so I'm not sure this is doable easily. (@beledouxdenis ?) We will think about it, but I cannot commit here on what we will do and when :)

Anyway, we keep the security of our users as a primary concern:
- We don't store Github access tokens (and you may revoke permissions at every moment, as well as destroying your Odoo.sh project)
- Odoo.sh won't perform any branch creation/commit in the authorized repositories without an explicit user action (eg: an user MUST click on "create a new branch" in Odoo.sh GUI to create a new branch and push it, the server will never do it "on its initiative")

I hope this reassures you a bit

**Comment by fmdl** [comment]
Thank for you answer
@rim-odoo I am sure that every thing is build to prevent unallowed action or keep privacy. It is just a remark.
A better confugiration of permission could be great (exemple : you don't need write access of the private email adress).

If not it is great feature, good job !

**Comment by rim-odoo** [comment]
@fmdl thanks for the feedback anyway, we are still developing new stuff for the platform & refining the existing ones

**Comment by beledouxdenis** [comment]
We indeed thought about this matter, that people might feel uncomfortable granting the write access to their repository.

For that sake, we explain in the [documentation ](https://www.odoo.com/documentation/user/11.0/odoo_sh/getting_started/create.html#authorize-odoo-sh)why we need these rights. 

We are considering a manual/advanced mode for projects creation, where we do not ask any rights at all, but the user will then be responsible to create the webhook and the deployment key manually. Besides, every action requiring the access to your Github repository will be disabled. That includes the feature you are willing to test, as it creates a new branch in your repository and commits the given app into it.

Regarding the write access on the user (email), this is not possible, at the moment, in the Github OAuth API, to ask a read-only access scope to these information.
https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/#available-scopes
There is nothing we can do at the moment regarding that specific matter.

**Comment by fmdl** [comment]
Thank for your answer.

**Comment by ranjan-purbey** [comment]
You can use github's `read:user` or `read:email` scopes for read only access.  Asking for full access to user's github account doesn't look right. Platforms like vercel/digitalocean have better implementation for this.

**Comment by amigrave** [comment]
> You can use github's `read:user` or `read:email` scopes for read only access. Asking for full access to user's github account doesn't look right. Platforms like vercel/digitalocean have better implementation for this.

We are working on an update that should allow one to only grant those basic scopes, then incrementally grant additional scopes when/if needed.
The goal is to let a contributor sign in without having to accept all the scopes we are gathering when using the "Deploy your platform" route. The use case we want to cover is typically for contributors who does not necessarily have to deploy a project but just working on a project. No ETA to communicate though.

**Comment by debreczeni** [comment]
Requiring full write access to all private repositories including all organisation's repositories is certainly complete madness.

**Comment by MazElysian2** [comment]
@ahu-odoo (Maz-ODIY here :)) this has become an issue for our more safety sensitive clients (particularly those that work with Defence or other private/confidential code). Is there any further update or guidance on this issue of access to private repositories? Perhaps something we can put to @fpodoo at Odoo Insider 13th March :)
