### ISSUE TITLE
Not able to convert Belgi\xc3\xab to België in odoo11 python3.5

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#24519]
Impacted versions: odoo 11 python3.5

Steps to reproduce: UTF-8 string Belgi\xc3\xab

my_str = "Belgi\xc3\xab"
encoded_str = my_str.encode('latin1').decode('utf8')
print(encoded_str)

Current behavior: Unable to convert latin chars.

Expected behavior: Should be able to convert to latin chars.

Video/Screenshot link (optional):
https://d.pr/free/i/bbmbip

**Code** 
I have tested this I have tested on python terminal and in odoo too.
Still same.

Below is my function to convert latin chars

@api.model
def reconvert_chars(self, address):
    '''
        This function will reconvert chars of address
        eg \xc3\xab to ë
        @param : address(str)
        @returns : address(decoded)
    '''
    try:
        
        encoded_str = address.encode('latin1').decode('utf-8')
        return "{}".format(encoded_str)
    except Exception as e:
        print("INSIDE EXCEPTION",e)
        return False

**Comment by pedrobaeza** [comment]
Already answered in #24075

**Comment by mohdshoaib04** [comment]
I have checked my code and the documentation provided by python
However my issue still persists.
Request you to please open the issue again.
@pedrobaeza @Yenthe666

**Comment by pedrobaeza** [comment]
As stated, this is not an Odoo issue, so you should ask for help in other place.

**Comment by Yenthe666** [comment]
@mohdshoaib04 please ask this on the official help forums at help.odoo.com
