### ISSUE TITLE
Odoo should set the secure flag on its cookie when reverse proxied from https

### ISSUE THREAD

**Issue by greaber** [odoo/odoo#24518]
I terminate SSL on nginx and reverse proxy to Odoo.  I configure nginx to set the X-Forwarded-Proto header to alert Odoo that the connection is secure.  (This is common, and most cookbook instructions for setting up a reverse proxy will include this.)  I think Odoo should respond by adding the secure flag to its cookie so that the browser will not send it over an insecure connection.

**Comment by greaber** [comment]
OK, it could be a mistake on my part, but I'm not yet seeing where.  I noticed that `curl -I https://my.crm.server.com` returns

```
Set-Cookie: session_id=xxxxxxxxx; Expires=Mon, 30-Jul-2018 17:37:33 GMT; Max-Age=7776000; HttpOnly; Path=/
```

I was expecting (or thinking that it would be better for security) to see `secure` in the Set-Cookie response.  My `nginx.conf` has

```
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by greaber** [comment]
I realize that it is possible to configure nginx to add the secure flag itself, but my understanding is that it is better practice for Odoo to check X-Forwarded-Proto.  Certainly this would be safer for the community at large since most people won't configure their reverse proxy to add the secure flag.

**Comment by pedrobaeza** [comment]
No, that a task that doesn't belong to Odoo itself, but the middleware. Odoo shouldn't do things that are already better done by other layers. Closing this.

**Comment by marcos-mendez** [comment]
Hey @pedrobaeza I didn't understand. Im checking also this Issue on Odoo S.A https://github.com/odoo/odoo/issues/51065

Im currently having slow down and gateway issues on a Specific Odoo v12 installation. They show me as: Some cookies are misusing the recommended “SameSite“ attribute on the Browser Console

Do I have to make the tweeak in the Odoo server or in the NGINX reverse-proxy server? Also, if you don't mind answering me, is it better to handle this issue in the reverse proxy layer(NGINX)?

Which directive should be included? 
`proxy_cookie_path` / "/; secure; HttpOnly; SameSite=strict"; `
?

Thanks in advance from S.V Amigo

**Comment by pedrobaeza** [comment]
That's something unrelated to this issue and in fact, it's not a real error. See https://github.com/odoo/odoo/issues/71843#issuecomment-859767985
