### ISSUE TITLE
Reversal of account move where Journal has dedicated reversal sequence

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#24526]
Impacted versions: v11 (likely also before)

Steps to reproduce: Create an invoice and post. Go to Journal entries in accounting (not to the invoice view) cancel the Journal entry produced by the original invoice.

Current behavior: The accounting entry is cancelled correctly and the invoice is marked paid. However the sequence used for the entry is not taken from the cancellation sequence but from the invoice sequence.

Expected behavior: Sequence used for entry should be the refund sequence when the journal used has a dedicated refund sequence defined.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @ahetland 

> Create an invoice and post. Go to Journal entries in accounting (not to the invoice view) cancel the Journal entry produced by the original invoice.

I don't think going to Journal Entries from Invoice or not matters here.

> Current behaviour: The accounting entry is cancelled correctly and the invoice is marked paid. However the sequence used for the entry is not taken from the cancellation sequence but from the invoice sequence.

Invoice will not be marked as Paid if you cancel those Entries, It will be Paid If you Reverse those Entries.

> Expected behaviour: Sequence used for entry should be the refund sequence when the journal used has a dedicated refund sequence defined.

I believe you are Reversing those entries (Not Cancelling as you mentioned) than in that case "Dedicated Credit Note Sequence" wont matter here, It works for Credit notes not for Reversal of Original Entries

May be  @pedrobaeza can add more focus on it.

**Comment by pedrobaeza** [comment]
The problem here is that you are not doing things correctly. An invoice is not cancelled through a reversal move, but refunding it, and thus, on refunds is where the refund sequence is taken into account.

Closing as no real issue.

**Comment by ahetland** [comment]
Gentlemen, there are two issues here; first is that the user is allowed to do things incorrectly (why, it would be nice to warn the user no?), second there is a reversal sequence defined so if one really wanted to do this incorrectly, then one should expect that the system uses the correct sequence.
