### ISSUE TITLE
standard_price field in product.template is hidden from public user

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#2452]
I setted up a webshop. Uploaded the products with supplier price setted (normal sell price leaved empty), and modified the public pricelist to get the price from the supplier price plus add 40%.
If i browse the webshop with a user logged in it works, but when i logout the webshop crash with an exception: the public user have no right to see the standard_price field. This is because in the field definition it is available only to the users group:

``` python
        'standard_price': fields.property(type = 'float', digits_compute=dp.get_precision('Product Price'), 
                                          help="Cost price of the product template used for standard stock valuation in accounting and used as a base price on purchase orders.", 
                                          groups="base.group_user", string="Cost Price"),
```

In this situation the webshop should work!

From my point of view there should be an option in the webshop to view products without price, but this is another story..

**Comment by Yenthe666** [comment]
Hi @tsabi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
