### ISSUE TITLE
[bug]run odoo-bin --dev xml ,some translations cannot be loaded

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#24534]
Impacted versions:
11.0
Steps to reproduce:

- run odoo-dev ,don't use --dev xml, no problem
![qq20180503-092547](https://user-images.githubusercontent.com/5398273/39556598-03fe3964-4eb4-11e8-84a1-d54cec5b5ab1.png)

- run odoo-dev --dev xml, some translations cannot be loaded
![qq20180503-092720](https://user-images.githubusercontent.com/5398273/39556628-335aa210-4eb4-11e8-89e2-8f8fac5bf60e.png)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e could you have a look please?

**Comment by mart-e** [comment]
Hello,

The option `-- dev xml` is:

> xml: read template qweb from xml file directly instead of database. Once a template has been modified in database, it will be not be read from the xml file until the next update/init.

So it means, you are not working with the database for the views. As the translations are stored in the database, it actually make sense.
This option is to be used when you are actually developping on your views, to see the result directly.
