### ISSUE TITLE
group by and editable="bottom" not working 

### ISSUE THREAD

**Issue by adrianlaraperez88** [odoo/odoo#24536]
Impacted versions:

odoo 11

Steps to reproduce:

<record id="view_ed_order_product_tree" model="ir.ui.view" >
            <field name="name">ed.order.product.tree</field>
            <field name="model">ed.order.product</field>
            <field name="type">tree</field>
            <field name="arch" type="xml">
                <tree string="Demand Product" editable="bottom" create="false" delete="false">
                    <field name="department_id" readonly="1" groups="ed_base.group_procurement_manager"/>
                    <field name="product_id" readonly="1"/>
                    <field name="partner_id" readonly="1" groups="ed_base.group_procurement_manager"/>
                    <field name="price" groups="ed_base.group_procurement_manager"/>
                    <field name="product_qty"/>
                    <field name="date" readonly="1"/>
                    <field name="state" readonly="1"/>
                </tree>
            </field>
        </record>

add group by and editable="bottom" not working

**Comment by pedrobaeza** [comment]
Please put more details or this will be hardly understandable.

**Comment by sswapnesh** [comment]
@pedrobaeza I can confirm this Behavior too.

**Comment by pedrobaeza** [comment]
But the problem is that I don't understand what is the problem and neither will do Odoo support team.

**Comment by sswapnesh** [comment]
Will add Detailed Description with Screenshot.

**Comment by sswapnesh** [comment]
You can reproduce Same by Group by "Some field" on any editable list view.

Tested on [Runbot](http://325328-11-0-rounding-pim-772ce2.runbot11.odoo.com/web?debug=#view_type=list&model=purchase.order&action=794) 
(I have added editable="top" to test)
![](https://image.prntscr.com/image/elym8cWfQAye9hmRApwjGw.png)

No more editable
![](https://image.prntscr.com/image/uO3WrFDASZS0lr90_nuClA.png)

**Comment by Yenthe666** [comment]
@ged-odoo was there a chance in the framework (view usage) here? Not sure about this one.

**Comment by ged-odoo** [comment]
what is the issue? the fact that if we group an editable list, it cannot be edited anymore?

If that is the issue, then it was totally impossible before v11. When we started working on the new views for v11, we actually thought about it, and I think we had a basic working prototype.  However, we were so much in a rush that we decided it was not a priority and we just worked on making sure that the new views had the same features as the old ones.

Now, making this work is now doable, but definitely not easy. This require fiddling with offsets in each group, and taking care of many small/not so small details.  For example, what if we change a field in a record and this cause the record to move to another group? (via an onchange) What if this other group is closed? What if this is a new group?  Where does the focus go when we are at the end of a group and press enter/tab?  Where do we create a new record (when using the create button)?

**Comment by adrianlaraperez88** [comment]
This solution no working for me.

https://apps.odoo.com/apps/modules/10.0/grouped_by_list_view_editable/

**Comment by adrianlaraperez88** [comment]
Sorry, bad click

**Comment by Yenthe666** [comment]
@adrianlaraperez88,

As said by @ged-odoo it is not supported in current versions by design so that means we don't consider this a bug.
The apps on the app store are note from Odoo itself so if they do not work then reach out to the author of the module. 
P.s: you are also linking to a 10.0 module. 

Regards, 
Yenthe

**Comment by Yenthe666** [comment]
As ged-odoo said it is not supported, so not  it will not work. Adding features in a stable version is not allowed so this won't ever land in any of the current versions. Which means there is nothing to do or wrong here.

**Comment by Yenthe666** [comment]
For now, yes. Who knows if the great JS team has enough time and finds it critical enough it could be fixed in 12.0. No promisses though.

**Comment by Kiplangatdan** [comment]
Had been facing the same issue till I came across this. Hope it will be fixed in 12.0.

**Comment by ged-odoo** [comment]
You might be interested to know that some progress have been made in that direction:
https://github.com/odoo-dev/odoo/tree/master-editable-groupby-rga

Code not reviewed, so it may still not be ready, but I suppose that there is a decent chance of having it in 12.0

**Comment by Kiplangatdan** [comment]
@ged-odoo Thanks, it looks promising already.
