### ISSUE TITLE
 Product names do not appear on the second page.

### ISSUE THREAD

**Issue by bariserdogan** [odoo/odoo#24547]
Impacted versions:  Odoo11

Steps to reproduce: Sales -> Orders -> Select an order from list -> Delivery -> Return -.> Stock Return 
                                Picking Wizard 

Current behavior: When I click return button in delivery form; If there are too many items on the product list, it goes to the second page. Everything is normal up to here but the names of the products on the second page do not appear. For this reason we can not get a refund.
 

Expected behavior: Product names appear on the second page if there are too many products

Video/Screenshot link (optional): 

![issue1](https://user-images.githubusercontent.com/17798258/39573608-95c1a21e-4edc-11e8-8af1-ca397bc87b22.JPG)

![issue2](https://user-images.githubusercontent.com/17798258/39573644-bdc4c444-4edc-11e8-8652-c10370ee349a.JPG)

**Comment by Yenthe666** [comment]
Hi @bariserdogan,

Thanks a lot for the bug report.
Do you also have this on the latest 11.0? You can test this at runbot.odoo.com.
Do you have it when your language is English too?

**Comment by bariserdogan** [comment]
Hi @Yenthe666 ,

Thank you very much for your interest. 
I installed the latest version of 11.0 one week ago.
When I do it in English, I get the same mistake.

**Comment by bariserdogan** [comment]
Thank you so much for your development. 
I need to wait for the merge to update my source code correctly?

**Comment by Yenthe666** [comment]
@tusu77 I do not work for Odoo and only manage issues on a voluntarely basis. In short: @alexkuhn is working on this (as you can see from the commits). When it is fixed he will close this issue and link to the relevant fix.

**Comment by alexkuhn** [comment]
Hello, this bug should be fixed with this commit: https://github.com/odoo/odoo/commit/8ac98fc78a3794e06481b02a431bcdc386a5a6ee
