### ISSUE TITLE
import a zip from one odoo to another breaks document storage

### ISSUE THREAD

**Issue by zem** [odoo/odoo#24557]
Impacted versions: 11

Version: 11.0.20180503
APT-Sources: http://nightly.odoo.com/11.0/nightly/deb ./ Packages

Steps to reproduce: Export a Database as Zip File and Reimport it on a fresh installation 

Current behavior: Stored Documents are not available after Import 

Expected behavior: Stored Documents should be Available after import

Video/Screenshot link (optional):

As soon as I move the Files to the right location, everything works again... 

root@erp:/var/lib/odoo/.local/share/Odoo/filestore/databasename# (cd filestore/ ; tar cvfz - . ) | tar xvfz -

**Comment by zem** [comment]
sure.  The data is in the zipfile, it just ends up at the wrong place on the target system.

**Comment by pedrobaeza** [comment]
Why is it in the wrong place? Can you specify a bit more?

**Comment by zem** [comment]
I cant tell you why that happens, otherwise i would most likely have send you a patch. 

Please read an understand the last line of my bug report carefully. it tells you most of things you have asked for so far. If you have any trouble understanding that piece of terminal output, than we can go through that via phone or email. 

We are using odoo comunity edition nightly build on a recent Debian, installation, but i would bet that this can be reproduced elsewhere. If it can't be reproduced out of the box I can run more tests.

**Comment by mart-e** [comment]
Hi,

I have just tested and it worked without issue.
My guess is that it is/was an issue of deployment where the filestore specified in the wrong place.
As this issue is quite old and is the only feedback of such problem, I am closing the report.
However if you have more details on how to still reporduce it, let me know and we can reopen
