### ISSUE TITLE
Vehicles Fuel Logs

### ISSUE THREAD

**Issue by ftribrunn** [odoo/odoo#2455]
in the Vehicles Fuel Logs Form
if I add 62,93 Liter and 83,00 EUR the Price Per Liter must be 1,319
but a price of 1,32 is stored. so the "on_change_" recalc the values and they are not accurate

sry guys but it makes no sense for me...if I am come from the gas station, I have a bill with EUR and Liter. I would not enter the price per liter. 

The price per liter should be always claculated with 3 decimal places and be readonly in the form

you might be able to explain it to me.
thx
fabian

**Comment by Yenthe666** [comment]
Hi @ftribrunn,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
