### ISSUE TITLE
Demo should have a language selection as first step

### ISSUE THREAD

**Issue by muescha** [odoo/odoo#24563]
### Impacted versions: 

11.0

### Steps to reproduce:

1. i open the link demo.odoo.com and get redirected to demo3.odoo.com
2. i use the demo
3. i like to have it in my language: go to user settings
4. i see only english as language
5. (after hours walk through english demo side)
6. i found that in some settings i need to load a different language before i can setup my language in user settings 
7. unhappy ;)

### Current behavior:
1. it starts with english language
2. for changing the language i need 2 steps which are very hidden

### Expected behavior:

a) preselect language before startup:
i should have an language selection before redirection to demo3
the selected language should be loaded and selected for the demo user

b) add a hint 
add hint to user/preferences to the language that i need to load the language in the odoo settings

### Video/Screenshot link (optional):
![bildschirmfoto 2018-05-04 um 01 27 39](https://user-images.githubusercontent.com/184316/39607308-8396983e-4f3a-11e8-940e-1952129ca336.png)

**Comment by pedrobaeza** [comment]
If you want a customized language demo, you should go to https://www.odoo.com/trial and start a new one, but not on demo.odoo.com. As this is not a real issue, closing.

**Comment by muescha** [comment]
just one last note: 

a) the trial is not an option because i need to register (and maybe loose my 14days free trial if i register) - so the demo side is the best option at first look at odoo

b) but on the demo site **it is possible** to change the language on the demo site. The tooltips and the Tutorials are also translated. Then it is a big loss for a new customer to have the first experience in english and not in his native language 

![bildschirmfoto 2018-05-04 um 01 34 47](https://user-images.githubusercontent.com/184316/39607612-3570891a-4f3c-11e8-8498-0d437c8b8331.png)
![bildschirmfoto 2018-05-04 um 01 35 52](https://user-images.githubusercontent.com/184316/39607613-3594f61a-4f3c-11e8-9bfb-314daa9d77cf.png)
![bildschirmfoto 2018-05-04 um 01 36 17](https://user-images.githubusercontent.com/184316/39607614-35ae7a04-4f3c-11e8-9def-84e7c3f01f9e.png)
![bildschirmfoto 2018-05-04 um 01 36 42](https://user-images.githubusercontent.com/184316/39607615-35cbb47a-4f3c-11e8-81a3-c5a2ae7b0910.png)
![bildschirmfoto 2018-05-04 um 01 37 18](https://user-images.githubusercontent.com/184316/39607616-35e90f0c-4f3c-11e8-8ce7-3ee11559892e.png)
