### ISSUE TITLE
Outgoing Email with G Suite Groups Aliases 

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#24565]
We use G Suite as email server with google Groups aliases as our "catchall" or collaborative inbox.  Would like to send outgoing emails as alias@domain.com, but "from" field only changes the name and not the sending address alias.  

Does odoo currently support this or would this be an addon?

**Comment by wtaferner** [comment]
Afaik G Suite/Gmail does only support aliases as a sender if it is explicitly authorized, so it is not Odoo who is changing the from address but G Suite/Gmail.

Give it a try and try to register an alias and try to send from this alias via Odoo and see if I remember correctly :-) If so you can close this issue yourself, if not there might be another way to do it, but IMHO it is nothing related to Odoo, but your SMTP.

**Comment by Moto017** [comment]
I have my aliases registered with my user account.  With typing alias@domain.com, still sends all outgoing email as user@domain.com.  Only work around I can think of is is to create a google user for the main company email so google can directly connect to that email.  

I would imagine this would be a common issue for companies looking to send official company emails with similar setups.

**Comment by pedrobaeza** [comment]
You need to activate the mail relay option in your G Suite:

https://help.frontapp.com/t/184yz6/configuring-g-suite-accounts-to-send-via-gmail-smtp-relay

Closing as no issue, but misconfiguration.

**Comment by michaelwittwer** [comment]
@pedrobaeza I configured the Google SMTP Relay service as described in the linked help article. But unfortunately only a few emails will be delivered. (running odoo v12 on odoo.sh) Every day I have a few of `Connection unexpectedly closed`, do you have any idea on how to fix this?

**Comment by pedrobaeza** [comment]
I can't say. We are using this service with no such problem. Try to get a network inspector to see if you have some kind of network problem in your deployment.

**Comment by michaelwittwer** [comment]
@pedrobaeza are saying that you are using Google SMTP Relay service on the odoo.sh platform with no issues?

**Comment by pedrobaeza** [comment]
Not on odoo.sh. I have it on "on premise" instances working well.
