### ISSUE TITLE
sale portal from paypal link 

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#2456]
hi,
In the Sale portal in the Form the link paypal option can't to be clicked,  show the hidden xml tag.
![screenshot - 16092014 - 17 48 29](https://cloud.githubusercontent.com/assets/4387127/4290183/9037f182-3db9-11e4-96f5-2589746dd000.jpg)
kind's regards

**Comment by Yenthe666** [comment]
Hi @roccocesetti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
