### ISSUE TITLE
account_sepa_direct_debit (enterprise) not XMLRPC compatible

### ISSUE THREAD

**Issue by tbaden** [odoo/odoo#24571]
Impacted versions:
11.0

Steps to reproduce:
install accounting & account_sepa_direct_debit
create an invoice with a XMLRPC call and call "action_invoice_open" function via XMLRPC for this invoice

Current behavior:
Error:
File "/home/odoo/odoo/odoo/service/wsgi_server.py", line 125, in wsgi_xmlrpc
    response = xmlrpclib.dumps((result,), methodresponse=1, allow_none=False)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 951, in dumps
    data = m.dumps(params)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 501, in dumps
    dump(v, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 523, in __dump
    f(self, value, write)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 527, in dump_nil
    raise TypeError("cannot marshal None unless allow_none is enabled")
TypeError: cannot marshal None unless allow_none is enabled
' in /www/htdocs/w015a605/magento/lib/Zend/XmlRpc/Client.php:370

Expected behavior:
invoice creation and validation without an error

How to fix:
in "./enterprise/account_sepa_direct_debit/models/account_invoice.py"
add a return to the  function "invoice_validate" (start at line 13)
Quicktested with "return True"

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this ticket as there has been no feedback and there is no clear example on how to reproduce it. I create dozens of invoices through API calls without issues too so I assume this has been solved in the meanwhile?

Regards,
Yenthe

**Comment by tbaden** [comment]
Yes it has been fixed.

**Comment by Yenthe666** [comment]
Thanks for the feedback!
