### ISSUE TITLE
widget.model not working ?

### ISSUE THREAD

**Issue by peterhoth** [odoo/odoo#24578]
Impacted versions: odoo-11.0.post20180504

Steps to reproduce:
1. Sales module is installed

2. mymodule/static/src/xml/newbutton.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<template id="template" xml:space="preserve">       
  <t t-extend="ListView.buttons">
    <t t-jquery="button.o_list_button_add" t-operation="after">
        <t t-if="widget.model == 'sales.order'">
             <button class="btn btn-primary btn-sm" type="button">New Button</button>
        </t>
    </t>
  </t>   
</template>

```
3. mymodule/__manifest__.py:
```
:
   'qweb': [
        'static/src/xml/newbutton.xml',
    ],
:
```

4. Upgrade module 

Current behavior:

When in Sales Order, new button is not shown. However, when the element  `<t t-if="widget.model == 'sales.order'">` is removed, the **New Button** is shown in every form.

Expected behavior:
New Button should be shown only in the Sales Order form.

**Comment by peterhoth** [comment]
Tried changing the condition to <t t-if="doc_model in ['sales.order']"> but it is still not working.

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
