### ISSUE TITLE
[9.0] If product quantity of purchase_order_line is modified, the quantity of associated procurement_order is not updated. 

### ISSUE THREAD

**Issue by MouTio** [odoo/odoo#24585]
Impacted versions: 9.0 and 10.0 (in 11.0 works fine)

Steps to reproduce: 
1. Create a product and set to stockable. Route: Buy. 
2. Create a reordering rule for that product. For example with minimum stock 5 and maximum 10.
3. Run reordering rules. It creates a purchase order with 10 units of the product. The status of the order is draft.
4. Modify the quantity of the **purchase order line** from 10 to 2. 

Current behavior:
The quantity (product_qty) of the **procurement_order** is not updated. It remains at 10.

Expected behavior:
The quantity (product_qty) of the procurement_order should be 2, like the purchase order line modified.

**Comment by pedrobaeza** [comment]
That's something expected, as this chained records don't work as a full sync chain, from the original source (SO, reordering rule...) you get the procurement order, and from the procurement order you get the PO line, but not on the reverse order.

Closing then as no real issue.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
