### ISSUE TITLE
Are there plans to resurrect the Hierarchical Tree View ?

### ISSUE THREAD

**Issue by SpiraMira** [odoo/odoo#24584]
Impacted versions: 11

Steps to reproduce: NA

Current behavior: broken

Expected behavior: a functional tree view in the framework

Video/Screenshot link (optional):

Hi - are there any plans to resurrect the tree view in Odoo 11.  I think it's not only a nice to have but critical given that your framework is ORM based.  I would like to display a hierarchical view of vendor/supplier accounts such as real world prime/subcontractor m2m relationships in large projects.

In the short term, does anyone have a alternate approach?

Regards P

**Comment by Yenthe666** [comment]
Hi @SpiraMira,

As far as I am aware there is no plan to reintroduce the hierarchical tree view in the upcoming version.
@ged-odoo can probably answer this and confirm.

**Comment by ged-odoo** [comment]
I am not aware of any future plan for the hierarchical tree view.  As far as I know, the decision was that grouped list views can replace most of the use cases for the hierarchical tree view.  Sorry
