### ISSUE TITLE
[8.0] Access error on Association/Members

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#2458]
Create a user with only the "Employee" group and log in with it.
If you click on the "Association" menu you will get the error:

    AccessError
    No value found for res.partner(6,).phonecall_ids

**Comment by mistotebe** [comment]
This is caused by commit 9f3abe3ea4d040b0ded7c4384077d799ecb24ab2, the phonecall count should have either been put back or in a try statement of its own.

**Comment by mistotebe** [comment]
The same thing affects crm_claim's _claim_count, the same treatment could be used to deal with that as well.

**Comment by SVQTQ** [comment]
So in order to fix this, I should have to put the phonecall_ids back in the res[partner.id] dict?

**Comment by mistotebe** [comment]
Maybe, but if the aforementioned commit is correct, it should go into a "try: except" of its own. Some users might have access to phonecalls but not meetings?

**Comment by SVQTQ** [comment]
But this just takes all the partners and tries to get their phonecall_id.
As I don't have permission to see the admin, but still try to access it, it
throws an AccessError. Or am I thinking wrong?

A solution in my eyes might be using SUPERUSER_ID (imported from openerp)
in the self.browse

What try/catch would you place then?

2015-06-10 10:20 GMT+02:00 mistotebe <notifications@github.com>:

> Maybe, but if the aforementioned commit is correct, it should go into a
> "try: except" of its own. Some users might have access to phonecalls but
> not meetings?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/2458#issuecomment-110647354>.
>



-- 
Kind regards
Sonny Valkeneers



ERP-Consultant at Cats&Dogs bvba
Industrieweg 1506 - 3540 Herk-de-Stad,   Belgium
Mobile : +32 497 90 46 24
Website: http://www.catsanddogs.com
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsf6pNdW4Xr82F1q0yjlW7gs3QC56dTmvf3zwpFs02?t=http%3A%2F%2Fwww.catsanddogs.com%2F&si=5058211664101376&pi=69deef44-76d8-4268-b1da-58b7e68a7eda>

[image: www.catsanddogs.com] <http://www.catsanddogs.com>

**Comment by mistotebe** [comment]
No, only the partners requested in 'ids' will be acted on. A better but fix might be to rework that to use read().

**Comment by mart-e** [comment]
Hello,

The computation of the field phonecall_count was a bit mixed up with other fields. I have isolated the computation at 99052611084eced10aec3fcdb9404a96e41e71ea
This requires an update of the crm module

**Comment by mistotebe** [comment]
The fix is incomplete, crm_claim and claim_from_delivery are still affected, see #7734.
