### ISSUE TITLE
[11.0] Activity Due Date Glitch

### ISSUE THREAD

**Issue by Maxim-Mazurok** [odoo/odoo#24587]
**Impacted versions:**
11.0

**Steps to reproduce:**
1. Create an Activity (for example, for a Task). 
2. Set Due Date (any date in future or past, except for today)
3. Set Activity Type

**Current behavior:**
Due Date is now reset to today date

**Expected behavior:**
Do not reset Due Date if it was manually set before changing Activity Type.

**Video/Screenshot link (optional):**
https://youtu.be/vPOD_ykd-Go

**Comment by Yenthe666** [comment]
Hi @Maxim-Mazurok,

Indeed, that could be improved. I've given it the correct labels so that somebody from the responsible team can have a look as soon as they have time.
It gets even cooler if you change from e-mail to call by the way, then you even get other dates.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
I think This is the Intended Behavior.

**Comment by Maxim-Mazurok** [comment]
@sswapnesh I thought about it. But I'm new to Odoo and I haven't yet discovered all of it features. As I understand, Odoo may automatically set issue date based on already planned activities, for example. In this case, I think that it's ok to change date automatically, until it's already changed manually.

**Comment by Yenthe666** [comment]
@sswapnesh it feels very random though, as you do not get any feedback or warning. It almost feels like it randomly sets dates, so if this is intended I wouldn't really like it (or I do not understand it well)

**Comment by sswapnesh** [comment]
It is based on Days Configured in Activity Type.

![](https://image.prntscr.com/image/YDSFT7mLR6qjjOekh8DNtw.png)

It will add Configured days in today's Date.

**Comment by Yenthe666** [comment]
Aha! Good catch, now the whole functionality makes sense. Thanks.
