### ISSUE TITLE
Calendar meeting starting @ today 12 am doesn't appear on calendar

### ISSUE THREAD

**Issue by eng-eslam-a-y** [odoo/odoo#24583]
Impacted versions:
11.0
Steps to reproduce:
go to calendar quick create a meeting on today 12 am
Current behavior:
meeting won't appear on calendar level week or day but would appear on month

Expected behavior:
it should appear on all levels

Video/Screenshot link (optional):
https://www.useloom.com/share/47a73e3776f64eedaf19d29a8e5da5c0

**Comment by eng-eslam-a-y** [comment]
@Yenthe666 
if you could have a look at this.

**Comment by Yenthe666** [comment]
Hi @eng-eslam-a-y,

Seems to work fine in the latest 11.0:
![image](https://user-images.githubusercontent.com/6352350/39693001-dab6e998-51e2-11e8-8ca5-6e97f67d1139.png)
Can you make a video from the start to the end? (also the clicking etc) and can you reproduce it on a runbot?

**Comment by eng-eslam-a-y** [comment]
Hi @Yenthe666 
i have tried it on run bot it turns out that the problem is with first column in the calendar not today column
you can check it out on this video
https://drive.google.com/file/d/1PYKSZNRMoPZKcY2050P08p1W5X2ZjYps/view?usp=sharing

**Comment by Yenthe666** [comment]
Hi @eng-eslam-a-y,

Thanks a lot for the addition video! I was now able to reproduce this and I can confirm that this is a bug!

**Comment by sswapnesh** [comment]
Related Issue: #23099

**Comment by Yenthe666** [comment]
I've made an official bug report as it is a matter of time before one of our customers will his this one.
OPW 1844781

**Comment by Yenthe666** [comment]
Hmm, the odd part is that I can reproduce it but the people from Odoo cannot. I've seen a video from them. They do exactly the same thing, with the same browser, and it works at their end. No clue what the difference is..

**Comment by sswapnesh** [comment]
Can you please pass the video?

**Comment by Yenthe666** [comment]
See https://youtu.be/tgavdPPhKpk

**Comment by Yenthe666** [comment]
This ticket has been closed as no longer reproducable and most likely fixed (by Odoo S.A.) so I'm closing this related ticket too.
