### ISSUE TITLE
Odoo 11: website_animate module doesn't work after saving changes to the website pages

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#24599]
Impacted versions:
odoo 11

Steps to reproduce:
1. Download and install "website_animate" add on in a clean odoo 11 environment.
2. Set animation to any desired website page block -> the preview of the animation is working fine.
3. After saving the page changes, and reload the page, the animation is not working. Also, if for example the animation set is "fade in from left", the block disappear from the page without come visibile as expected from the nimation.

Current behavior:
The add on is not working as expected after saving page changes, il was tested with a local full community installation and also with the "online" version

Expected behavior:
The animation set should be activated 

Video/Screenshot link (optional):

**Comment by Mariotutal** [comment]
I got the same problem, the only variation is that in my case, the animation that doesn't work is "Rotate In-Down-Left" & "Rotate In-Down-Right"

**Comment by qsm-odoo** [comment]
Hello, sorry this issue was a bit forgotten. We are planning to rework the website_animate app to make it part of the website application. Meanwhile, I confirm the issue sometimes still occurs in 12.0 (last supported version). We'll fix that at the same time.

**Comment by bvr-odoo** [comment]
> I got the same problem, the only variation is that in my case, the animation that doesn't work is "Rotate In-Down-Left" & "Rotate In-Down-Right"

@qsm-odoo This one is fixed [here](https://github.com/odoo/design-themes/pull/329)

**Comment by rdeodoo** [comment]
Not sure what happened here about the original issue, but everything here seems fixed in last runbot 12.0.
A fix might have been done without closing this one.
Let me know if you still experience the issue, with a step to reproduce, I'll reopen it.
