### ISSUE TITLE
AssertionError: External ID must be fully qualified [Odoo 10]

### ISSUE THREAD

**Issue by 7Eleven1995** [odoo/odoo#24590]
I have a custom module with user group: Sample - User and Manager. My module have two main menus - in Accounting and Portal. 

Accounting Menu
Main
  - SubMenu1
  - SubMenu2
  - SubMenu3

Portal
Main
  - SubMenu1
  - SubMenu2

Billing user group can access all custom menus in the Accounting menu. Manager can access those menus thru Portal menu only. But whenever I access SubMenu2 as Manager in Portal menu, Odoo shows AssertionError: External ID must be fully qualified. But when I try a different user with Billing and Manager user group, there's no error, only the Manager user group.

sample1.xml
`<record id="sample1_action" model="ir.actions.act_window">`
           ` <field name="name">Sample</field>`
           ` <field name="res_model">sample.model</field>`
           ` <field name="view_type">form</field>`
	 ` <field name="view_mode">tree,form</field>`
       ` </record>`

sample2.xml (for portal menu)
`<menuitem id="my_sample_portal_menu" parent="sample_portal_main_menu" name="SubMenu2"
	  	          groups="my_module.group_sample_manager" sequence="40" action="my_module.sample1_action"/>`

Upon checking, the system only pass the **group_sample_manager** without the module name that's why the error occurs.  I already tried using different menu, but only the SubMenu2 has an error. What is the possible cause here?

**Comment by pedrobaeza** [comment]
You can put any full XML-ID that you want. If you don't put that, it's assumed that the module part is the current one, so it's not any problem, but a misunderstanding on how Odoo works. Closing.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
