### ISSUE TITLE
Create new pos order through xmlrpc?

### ISSUE THREAD

**Issue by minaeid90** [odoo/odoo#24601]
I created a new pos order through XML-RPC in a draft state(New), when the order created. Does it works fine with POS printers in cashier and kitchen?

**Comment by pedrobaeza** [comment]
Sorry, but this issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
