### ISSUE TITLE
link_bank_to_partner (in AccountBankStatement) changes master data

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#24602]
Impacted versions: v8, v9?, v10, v11

Steps to reproduce: 
the method link_bank_to_partner in AccountBankStatement (account_bank_statement.py) changes the bank id of of a partner if the bank_id and the partner_id is different. 

Current behavior:
when importing bank data and the bank payment is allocated to a new partner (e.g. payment was made on behalf of someone else, another partner) then the bank account of the paying partner is shifted onto the other partner.

Expected behavior: Master data should not be changed by the system, in this case it is changed without notifying the user. However in general in accounting systems one should not change sensitive data as bank account, without two eyes approval, and not without confirmation and logging.

Remedy: remove feature.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@ahetland what you are doing is something incorrect, as bank reconciliation is not supposed to use the "behalf of" someone other. If you put a partner there, that partner is the owner of the bank account.

Closing as no real issue, but use case misunderstanding.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.

**Comment by ahetland** [comment]
Pedro, my explanation might not have been the best. However the method is always executed when closing a bank statement, and if there (by way of error or not) is a difference between the partner_id in the reconciliation postings (because user changed this when doing reconciliation) then the bank account is changed if the bank account exists in the system. This change, or shift of bank owner, is done without the user even knowing about it. Not good, the method must be removed.

**Comment by pedrobaeza** [comment]
I don't agree on that. It was made on purpose for assuring a correct link after the bank account automatic creation, so it has its purpose.
