### ISSUE TITLE
[11.0 IMP] Please allow alpha numeric PLM revision & BoM numbers

### ISSUE THREAD

**Issue by fathomtreelimited** [odoo/odoo#24615]
Impacted versions: 11.00

Hi!  I've not been able to adjust the new BoM/part numbering system in 11.0 when making a new PLM/BoM/ECO revisions. I've tried using Studio and also tried to add and overide the Sequence with no luck.

I'd like a lettering system A B C D, instead of 1 2 3 4.

Any guide would be appreciated if this already available, else, please accept this is a change/improvement request.

Many thanks.

**Comment by pedrobaeza** [comment]
This is something about enterprise modules. Please open the corresponding OPW ticket instead of opening an issue in this community issue tracker.
