### ISSUE TITLE
[11.0] Wishlist page returns Internal Server Error if any product is "unpublished"

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#24618]
**Impacted versions:**
11.0

**Steps to reproduce:**
1. Create a new portal user A.
2. Add a product to the wishlist
3. Login as Admin and make the product "unpublished"
4. Login back as user A and access the wishlist page, i.e. /shop/wishlist

**Current behavior:**
The wishlist page will return "Internal Server Error".

**Expected behavior:**
The product should be removed from the wishlist if it is "unpublished" and the wishlist page should be still accessible.

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/16PVI9wwuS5hGPLGaG3TWLVFC69O4GcQy/view

**Comment by pedrobaeza** [comment]
@JKE-be can you please check?

**Comment by TimLai125** [comment]
Related PR: https://github.com/odoo/odoo/pull/24857
