### ISSUE TITLE
Duplicated iteration within three code lines

### ISSUE THREAD

**Issue by akevinieron** [odoo/odoo#24614]
Duplicated iteration with no reason:

https://github.com/odoo/odoo/blob/9d6ea8ef3e22d29181a0094807bf2b1745c36ef8/addons/point_of_sale/static/src/js/models.js#L318

https://github.com/odoo/odoo/blob/9d6ea8ef3e22d29181a0094807bf2b1745c36ef8/addons/point_of_sale/static/src/js/models.js#L321

**Comment by pedrobaeza** [comment]
They are not duplicated. The second one is for setting correctly the parent.

**Comment by Yenthe666** [comment]
@akevinieron if you think you can improve the behaviour and/or performance then you're always welcome to make a PR! We really welcome PR's.

**Comment by pedrobaeza** [comment]
@akevinieron but it should be done that way because we need a second pass for having all the elements that are indexed.
