### ISSUE TITLE
Global Leaves not visible when you create a leave request

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#24629]
Impacted versions:
V11 and higher

Steps to reproduce:
1. Create a global leave (like new year 01/01/2018) on a working schedule. (model = resource.calendar.leaves)
2. Go to Leaves > My Leaves > Leaves Request. If you look at the calendar, you won't be able to see that there is a global leaves there (model = hr.holidays). This is also not visible in the calendar (model = calendar.event). But if you try to take a leave on that day, the system will calculate the right amount of days, but the user does not know there is a 'global leave' on that day. This is confusing and users will have to research why that day is not taking into account of the amount of days requested.

Current behavior:
See above.

Expected behavior:
Make it possible to see the global leaves, the system is using this to calculates the correct days when you take a leave. It would be better to align this since Odoo is using it. It is for a normal user very difficult to check why the system is deducting the amount of global leaves from the request.

Video/Screenshot link (optional):

**Comment by jem-odoo** [comment]
Hello,
actually, this features is not supported. We keep this as a feedback for future version.
Regards,

  Jerome

**Comment by yung-wang** [comment]
Ok, lets hope this will be add in a future version.

**Comment by alexey-pelykh** [comment]
Was this changed in 12.0? It seems that math should be ok since https://github.com/odoo/odoo/blob/88242d6a15a03955b6f219c8330420454e571e6c/addons/resource/models/resource.py#L239 after #24717
