### ISSUE TITLE
Calendar recurring start date is wrong

### ISSUE THREAD

**Issue by gralet** [odoo/odoo#24638]
Impacted versions:
9.0 CE

Steps to reproduce:
- Create a recurring meeting, with a start date with time (not all day) (for example 09:00), a duration (for example 5 hours) , each week for example on fridays, for 3 occurences.
- Save

Current behavior:
The start_datetime ("Starting at")  is increased with the duration of the meeting.  
In my example the "Starting at" becomes 14:00 

Expected behavior:
The start_datetime should not change

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11177216/39779468-89174402-5309-11e8-83be-f08f8941f319.png)

![image](https://user-images.githubusercontent.com/11177216/39779489-9d3054d8-5309-11e8-9464-545c5c4ea3d1.png)

![image](https://user-images.githubusercontent.com/11177216/39779528-c34bad70-5309-11e8-9b8b-ac507f0bd7e3.png)

Sorry if I missed something

**Comment by simongoffin** [comment]
Fixed with this commit: https://github.com/odoo/odoo/commit/9cb37398f2c5a36ebd666c434c4478c3b45d6f92
