### ISSUE TITLE
[Wishlist] Ability to use multiple units of different unit types on one product

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#24639]
Impacted versions:
All versions up to now
Steps to reproduce:

Current behavior:
Now in odoo one product can only use one unit type to campute quantity. Just like tone & Kg. In fact, unit conversions between the same unit type are not required，account & purchase can use only Kg to process business.
Expected behavior:

In many machinery manufacturing companies，as a raw material, steel pipes need to use different types of units in different business departments in order to efficiently handle actual business.
The engineering department only considers the length of steel pipe used for pipe parts，so the engineering BOM uses the unit "m". Warehouse management requires “pice” as a unit for outbound and inbound operations.Financial management needs to process invoices and amounts in kilograms.
Although third parties can provide such functions through modules, because unit problems involve too many objects, it is not suitable to solve this problem through inheritance.
Because all manufacturing companies using steel pipes face the same management issues, we hope that the official can provide such functions.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sle-odoo and @lap-odoo for your interest. Is something like this planned or is there any interest in adding it?
@Guobower you could always do this with custom development too though!

**Comment by Guobower** [comment]
We can fix it, but I don't know if we can pull requests

**Comment by pedrobaeza** [comment]
I think this is too complex and very case specific for being in the core. It's the management of a dual unit system, with the corresponding conversion factors on each of the possible steps as convenience, so I see this more as a vertical community set of modules.

**Comment by lap-odoo** [comment]
@Guobower Hi, thanks for the suggestion however it's not in our plans to add this in Odoo Standard. That's a very specific need that only a few companies have and we don't want to make Odoo more complex  to support that specific use case.
