### ISSUE TITLE
Odoo.sh - delete a project entirely

### ISSUE THREAD

**Issue by SpiraMira** [odoo/odoo#24637]
Hi - how do I delete a project and start over. My initial project was created under a personal github account and I need to regen with a business account. The FAQ states odoo.com/project/<your_project>/settings provides this function, but I tried using the github repo name as a project name to no avail (also tried the name qualifying the administrator account in parenthesis unsuccessfully)

Thanks.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by fpodoo** [comment]
Questions related to odoo.sh can be asked on https://odoo.com/help

**Comment by pedrobaeza** [comment]
Thanks for the link, Fabien. I note it for further references.
