### ISSUE TITLE
Unbuild Order quant issue

### ISSUE THREAD

**Issue by anhdv1979** [odoo/odoo#24646]
Impacted versions:10.0

Steps to reproduce: After making unbuild order for lotted product, I check the lot/serial management and the quantity isn't reduced. I also check the stock quant table and it seems that there is no record related to unbuild ?

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @anhdv1979,

Thanks a lot for your bug report.
Please add more detailed information about how we can reproduce this, at this point we do not have enough information. Can you reproduce it on the latest Odoo 10 at runbot.odoo.com?

Regards,
Yenthe

**Comment by jco-odoo** [comment]
That is normal.  When you have a move from production/supplier/inventory, at each time, a new quant is created.
