### ISSUE TITLE
Run Schedulers button appears to be broken

### ISSUE THREAD

**Issue by jnewm13** [odoo/odoo#24659]
Impacted versions: Odoo 10.saas~14+e

Steps to reproduce: I don't know what happened between it not working and 2 weeks ago and it was definitely working

Current behavior: Click run schedulers and nothing happens (Run reordering rules in developer mode is still working)

Expected behavior: Generate a batch of manufacturing orders or RFQs

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have to check the logs in the server to see if there's any error and stack trace when pressing the button. Please copy that part here.

**Comment by pedrobaeza** [comment]
I didn't see the saas part, but if you are under Odoo SaaS, notify this to Odoo via an OPW ticket. If it's under other SaaS partner, notify the problem to that partner. Any way, I understood this is solved, so I close it.
