### ISSUE TITLE
Possibility to change "Contact Us Form"  map details

### ISSUE THREAD

**Issue by infomate** [odoo/odoo#2465]
Generated map on the Contact Us Form does not exactly show the vicinity location of the company specially for an unknown street (not yet update on google map), the zoom value (currently set to "8") is too small thus generating a map image too small to be used as location reference (unless clicked and opened to a new tab).

Suggestion:
1.  Additional custom fields to pin point location.
     a. Longtitude 
     b. Latitude
2. Additional custom field to define zoom level.
    a.  numeric value (between 10 ~ 15)
3.  Additional custom field to define pin /marker.
    a.  choose from a built-in collection of pins / markers
    b.  User defined / upload
4.  Additional custom field to define map size.
    a.  Pre-defined size - Small, Medium, Large
5.  Option to Display / Do-not-Display the map
6.  Possibility to move the map around the page.

**Comment by Yenthe666** [comment]
Hi @infomate,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
