### ISSUE TITLE
[11.0] Error in Form View of ir.attachment

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24664]
Impacted versions: 11

Steps to reproduce: Install some moduls which uses ir.attachment. Upload some files. Activate developer mode. Go to Settings -> Attachments.

Current behavior: Click on title opens up form(allright), Click on image of attachment triggers download. After one download you get errors for every next click on an attachment record. "Form could not be loaded" Right side red warning, no error in console or debugger.

Expected behavior:
no errors

**Comment by pedrobaeza** [comment]
I'm trying on runbot, and although the message "Form could not be loaded" appears, I'm always able to download the file clicking on the icon.

**Comment by DR4RCON** [comment]
Yes, but after one download you can not reach the form view anymore.

**Comment by DR4RCON** [comment]
upps sorry missclicked. 
But when you have downloaded an attachment you cannot reach the form view anymore.

**Comment by pedrobaeza** [comment]
Yeah, I see, unless you refresh the browser page. Then I can confirm the problem.

**Comment by pedrobaeza** [comment]
@ged-odoo can you check this and maybe assign another person for solving it?

**Comment by alexkuhn** [comment]
Hello,

I was not able to reproduce the issue on runbot: there is no error when I click on any record after downloading an attachment.
with community: https://youtu.be/QNcGp9vU7z4
with enterprise: https://youtu.be/JQ7K7qDdsUU

Could you please provide more details about this issue?

Thanks,

**Comment by DR4RCON** [comment]
Hello! What I can see in https://youtu.be/QNcGp9vU7z4 is that this is not representative for the current version. Normally you will get direct download of the document, when clicking on the icon. You could only reach the form view, when clicking on the title. Once you have clicked on icon and have dowloaded, you will not be able to reach the form view anymore, but with a page refresh.

**Comment by DR4RCON** [comment]
![peek 2018-05-14 15-55](https://user-images.githubusercontent.com/30311920/40001770-35b9e6d6-578f-11e8-9d35-cb124a3c1628.gif)

**Comment by DR4RCON** [comment]
Here fresh installed database, with demo data and only modul website installed.

![peek 2018-05-14 16-04](https://user-images.githubusercontent.com/30311920/40002305-a16a6f6c-5790-11e8-98ca-92fa9825eb2a.gif)

**Comment by alexkuhn** [comment]
Thank you for the .gif, I was able to reproduce this issue on Firefox.

When clicking on an attachment in community, it downloads the files **and** opens the record. I don't think this is the expected behaviour.

As a result, with Firefox, it prompts the "Save as" dialog and prevent the web client to access the record afterwards.

**Comment by DR4RCON** [comment]
I think best would be 1. direct download when click on icon  2. open form when click on title
