### ISSUE TITLE
base_import: Exporting on Excel adds FALSE to non-boolen fields, which can't be reimported

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#24669]
#### Impacted versions:
10.0, 11.0

#### Steps to reproduce:
Example:
- Create a Contact without City
- Export the `city `field

#### Current behavior:
- The `city` field is exported with **FALSE**
- When importing **FALSE** can't be imported in this field, so it has to be removed before importing

#### Expected behavior:
If a field doesn't accept a **boolean**, do not export a boolean.

**Tested on runbot**

**Comment by pedrobaeza** [comment]
Please indicate with a screenshot or the exact line text what are you exporting.

**Comment by gustavovalverde** [comment]
![image](https://user-images.githubusercontent.com/16890942/39876824-330615ea-5442-11e8-920a-5ba39b38c419.png)

To be more specific, as you can see in the picture those M2O fields are exported with **FALSE**, but that can't be reimported.

**Comment by gustavovalverde** [comment]
OPW 1847139

**Comment by Yenthe666** [comment]
@gustavovalverde I see you closed it without a comment, what happend to the OPW?
