### ISSUE TITLE
HR / Application / Applicant info block - star ratings has only 4 start 5th image missing

### ISSUE THREAD

**Issue by infomate** [odoo/odoo#2466]
Under Human Resources / Applications, inside the applicant information block there are only 4 stars (initially grayed-out) and a 5th image place-holder with no image.

Are there only 4 available ratings? If so the 5th image has to be removed.
Suggestion:
1.  Add an additional rating star:
     a.  Not qualified
     b.  Below Average
     c.  Average
     d.  Good
     e.  Excellent
2,  If only 4 rating stars are available, remove the image place holder in the 5th position.

**Comment by Yenthe666** [comment]
Hi @infomate,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
