### ISSUE TITLE
how can i add custom attr to tree?

### ISSUE THREAD

**Issue by xunonxyz** [odoo/odoo#24662]
Impacted versions:
11.0
Steps to reproduce:
add "no_open" to tree attr
 <tree no_open="true">
Current behavior:
validate error
Expected behavior:
provide someway to override the view.rng
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this is not possible to be done unless you modify a lot of things in the JS client plus the validation part, but that's not something expected to be done.

Closing as no real issue.
