### ISSUE TITLE
Redirection from HTTPS to HTTP ends in Bad Request

### ISSUE THREAD

**Issue by javsalgar** [odoo/odoo#24666]
Impacted versions: 11

Steps to reproduce: Install Odoo in ports different from 80 and 443 (for example, using Bitnami Odoo in ports 81 444). Then try accessing via https://address:444 (for example)

Current behavior: The page get redirected from HTTPS to HTTP with a Bad Request error.

Expected behavior: The page should load HTTPS.

I tried with proxy_mode = True but it didn't work either.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by javsalgar** [comment]
Thanks. Could you confirm that Odoo itself does not do any kind of redirections that require the ports to be 80 or 443?

**Comment by pedrobaeza** [comment]
No, just watch your web.base.url system parameter that it's correct.

**Comment by basstone40** [comment]
Hi Pedobaeza,
The URL we are using is correct. What Javsalgar explained is what is happening. All the time the Odoo server is redirecting to http and not https, even if the url contained https. May you help on this? 
We will real appreciate your support.
Regards,
Jubha

**Comment by pedrobaeza** [comment]
I'm sorry, but this should be something in your end. Recheck proxy_mode is enabled in your Odoo conf, and your proxy is properly configured. You can try an all-in-one solution like https://github.com/Tecnativa/docker-odoo-base for avoiding deployment problems.

**Comment by javsalgar** [comment]
Hi,
Apart from  https://github.com/Tecnativa/docker-odoo-base , is there an official Odoo container image that we can check if the issue appears?

**Comment by Yenthe666** [comment]
See https://github.com/odoo/docker and https://hub.docker.com/_/odoo/

**Comment by pedrobaeza** [comment]
But it doesn't contain the proxy part, so you will have the same configuration problem.
