### ISSUE TITLE
Customer lead has incorrect default on the SO line from shop

### ISSUE THREAD

**Issue by dduarte-odoogap** [odoo/odoo#24671]
Impacted versions:
11.0

Steps to reproduce:
Go to "iMac" demo product and set customer_lead to 4 days.
Go to /shop and add "iMac" to the cart and confirm the order.

Current behavior:
Opening the result SO we will see that the SO line has 0 instead of 4 on the customer_lead

Expected behavior:
Opening the result SO we will see that the SO line has 4 days on the customer_lead

**Comment by sswapnesh** [comment]
I can confirm this Behaviour . (It works fine if you are Creating in the Backend)

**Comment by sswapnesh** [comment]
Managed in d25719cdf2b8a863c1a855f2e42e9c3a43580f66 but still it has Issue as mentioned in #26855.
