### ISSUE TITLE
Module base_address_city is not changed to type Many2one

### ISSUE THREAD

**Issue by apisakoctcorp** [odoo/odoo#24674]
Impacted versions:11.0

Steps to reproduce: 
1. Install latest odoo 11 from github
2. Install module base_address_city and some module referred to customer such as sales, invoice
3. Create customer, City field is still text (debug mode showed field type char not Many2one)

Current behavior:
After installed module base_address_city field city is text as defined type as Char
Expected behavior:
After installed module base_address_city filed city become combobox as defined type as Many2one.

Video/Screenshot link (optional):
Before installed base_address_city
![image](https://user-images.githubusercontent.com/37141354/39906019-7afade94-550a-11e8-8aad-d2aacc82ede5.png)

After installed base_address_city
![image](https://user-images.githubusercontent.com/37141354/39905876-e6f12f00-5509-11e8-82ed-e5d472446796.png)

**Comment by pedrobaeza** [comment]
That's not how the module works. It adds a new many2one field `city_id`, but doesn't overwrite old `city` field. You should refresh your browser for loading new views with the new field.

Closing as no real issue.

**Comment by apisakoctcorp** [comment]
The reason I think it's pretend to overwrite are: 
1. City's modifiers changed after installed modules base_address_city. Attached picture above.
2. Module's details is "This module allows to enforce users to choose the city of a partner inside a given list instead of a free text field." This message seem to replace old behaviors as consider overwritten.

BTW, thanks for response.

**Comment by pedrobaeza** [comment]
I think you are forgetting that you have to check at country level the field "Enforce cities" for having what you want.

**Comment by apisakoctcorp** [comment]
Yes, you are right users must go into country level to enforce cities.

As of the step to reproduce mentioned, the users only install app sales and/or invoice. There is no module contracts to easily access to country level. The user will face the difficultly to find the way to enforce cities.

I would like to propose some improvement:
1. Force install module contracts when user install module base_address_city
2. Add few words in module base_address_city that it's required to go into module contracts->localization->countries to enforce cities for each countries.

And again, many thanks for quick response.

**Comment by pedrobaeza** [comment]
You have to install `sale_management` module, not `contacts`, and modules tend to have the minimal dependency chain if not technically needed, which is the case. The improvement on the description would help, but the idea is not to put all the documentation there. For that, you have https://www.odoo.com/documentation/user/11.0/.

**Comment by apisakoctcorp** [comment]
After fresh installed odoo11 then install "Sales Management", there is no simple way to access country.
I really have to install "Contact Directory" then users could access to country.

Fresh installed odoo11:
![image](https://user-images.githubusercontent.com/37141354/40032053-a5f64056-581c-11e8-8b96-5b03514ee8a4.png)

After installed Sales Management:
![image](https://user-images.githubusercontent.com/37141354/40032144-ff20e30c-581c-11e8-9860-60d08d9f7c8c.png)

After installed Contacts Directory:
![image](https://user-images.githubusercontent.com/37141354/40032166-27ce5848-581d-11e8-9f62-654ead09b7dc.png)

Thanks for quick response.

**Comment by my1649** [comment]
I am afraid I agreed with @apisakoctcorp . I installed the `base_address_city`, and had a really hard time on this. 
I need to add a tree view of Cities under the States, hide the 'city', add a 'city_id', make the relation of 'city' to 'city_id'.
I mean I didnt even know there is a "enforce cities". As now I know that need to be checked, and I am going to check every "enforce cities" on every country. All the cities field under every country should be the same for users. No wonder I felt incomplete for this module.

**Comment by my1649** [comment]
When the `city_id `is added, it is overridden with a group of div, which makes the line of city/states/zip breaks into 2 lines. After installing this module, it changes the layout of address even for the countries without "enforce cities". 
Could you just add the fields without the div? 

XML before module installed:
```
<field name="city" placeholder="City" class="o_address_city" attrs="{'readonly': [('type', '=', 'contact'),('parent_id', '!=', False)]}"/>
<field name="state" .../>
<field name="zip" .../>
```

XML after module installed:
```
<div>
   <field name="country_enforce_cities" invisible="1"/>
   <field name="city" placeholder="%s" attrs="{'invisible': [('country_enforce_cities', '=', True), ('city_id', '!=', False)], 'readonly': [('type', '=', 'contact'), ('parent_id', '!=', False)]}"/>
   <field name='city_id' placeholder="%s" attrs="{'invisible': [('country_enforce_cities', '=', False)], 'readonly': [('type', '=', 'contact'), ('parent_id', '!=', False)]}" context="{'default_country_id': country_id}" domain="[('country_id', '=', country_id)]"/>
</div>
<field name="state" .../>
<field name="zip" .../>
```
(from the res.partner.py of the module)

Expected structure:
```
<field name="country_enforce_cities" invisible="1"/>
<field name="city" class="o_address_zip" placeholder="%s" attrs="{'invisible': [('country_enforce_cities', '=', True), ('city_id', '!=', False)], 'readonly': [('type', '=', 'contact'), ('parent_id', '!=', False)]}"/>
<field name='city_id' class="o_address_zip" placeholder="%s" attrs="{'invisible': [('country_enforce_cities', '=', False)], 'readonly': [('type', '=', 'contact'), ('parent_id', '!=', False)]}" context="{'default_country_id': country_id}" domain="[('country_id', '=', country_id)]"/>
<field name="state" .../>
<field name="zip" .../>
```
Somehow the code above doesnt work without the div.

**Comment by aug1804** [comment]
I'm looking for a place to download the module 'base_address_city', where can I find this place?
Thanks in advance.

**Comment by leandroguimaraes** [comment]
> I'm looking for a place to download the module 'base_address_city', where can I find this place? Thanks in advance.

You can download it from here: https://github.com/odoo/odoo/tree/15.0/addons/base_address_city
