### ISSUE TITLE
[10.0][11.0] hr_payslip: l10n_xx_hr_payroll modules just update the main company

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#24683]
### Impacted versions:
All

### Steps to reproduce:
- In **Company A**, install a **l10n_xx_hr_payroll** which includes salary rules computation for the country
- Create **Company B**
- Create **Company C**
- Duplicate Company A rules to be used in **B** and **C** (using the same rule is not possible: #23814 )

**(major changes happens in l10n_xx_hr_payroll)**

- Git pull & update l10n_xx_hr_payroll

### Current behavior:
- **Company B** and **Company C** doesn't replicate the changes in l10n_xx_hr_payroll; as the only _safe_ way to use salary rules in multi-company environments is duplicating it.

If an **l10n_xx_hr_payroll** module is updated (including its rules) it will just update the main_company, other companies rules have to be manually updated, because the same rule can't be used for multiple companies. This is utterly complex and error prone.

This behavior has a great impact on implementations and updates dealing with multicompany environments, as it's painful (some times impossible) to maintain.

### Expected behavior:
1- Being able to use the same rule for multiple companies (#23814 has to be solved)
2- Having salary rules on l10n_xx_hr_payroll as templates (as Taxes, CoA, etc.), so the same rules can be 'installed'/'updated' on all companies with module update.** 

_(**)_ This might require a major refactoring, leaving stable installs with the headache.

**Comment by gustavovalverde** [comment]
![image](https://user-images.githubusercontent.com/16890942/39931328-106bdf0a-550b-11e8-858d-07412de352cc.png)

@Yenthe666 I (a) need patience or (b) I'm completely confused on what a bug is :)

**Comment by gustavovalverde** [comment]
After that reply I, of course, replied back with:
![image](https://user-images.githubusercontent.com/16890942/39932446-2db086b2-550e-11e8-98a0-99908d793a1c.png)

And he replied to that: _'Our technical department will evaluate if it is a bug or not.'_

I actually don't like to **make a fuss** of this things; but the immediate answer to most problems is oriented to: _'I won't even test that, as that can't be a bug'_. And just today I've spent 3+ hours just to prove them wrong.

**Comment by Yenthe666** [comment]
Yeah those kind of bug reports take time to figure out and prove. At least this time somebody from the tech team will look at it which is good right? I've got a feeling that some of your bug reports are too complex for some of the tech support guys. And what you do not know you usually try to get rid off or say that it is not supported. ;)

**Comment by gustavovalverde** [comment]
Mainly this is caused by the same principle: https://github.com/odoo/odoo/issues/26215

@tivisse do you know if property fields are being considered for v12 in payroll?

**Comment by tivisse** [comment]
Hi @gustavovalverde 

Yes, the payroll module doesn't manage correctly the multi company. 

There are no plan to improve this for the 12.0 release. Anyway, I'm gonna open a feature request that will be qualified and prioritized by our product owners team.

Have a nice day,

Yannick.

**Comment by tivisse** [comment]
Done at https://github.com/odoo/odoo/commit/344877a0813a915344a230f1aaf1f932f2f9d5cb

Thanks
