### ISSUE TITLE
Kitchen order is not working

### ISSUE THREAD

**Issue by sparshprogrammer** [odoo/odoo#24699]
Impacted versions:10

Steps to reproduce:

Current behavior:odoo.addons.hw_escpos.controllers.main: disconnected : Printer Not Found

Expected behavior:it should print the order in specified ip

Video/Screenshot link (optional):
![screenshot from 2018-05-14 13-25-01](https://user-images.githubusercontent.com/22262028/39984887-42b6f622-577a-11e8-8615-bb05e83edca1.png)
![screenshot from 2018-05-14 13-25-45](https://user-images.githubusercontent.com/22262028/39984914-5455b364-577a-11e8-8bb8-9d5f807e90ff.png)
![screenshot from 2018-05-14 13-26-13](https://user-images.githubusercontent.com/22262028/39984944-64387654-577a-11e8-9ddd-5fc540d8a313.png)

**Comment by Yenthe666** [comment]
@sparshprogrammer are you actually using an official supported ticket printer?

**Comment by sparshprogrammer** [comment]
I am using Gprinter thermal .....

**Comment by Yenthe666** [comment]
Dear @sparshprogrammer,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
