### ISSUE TITLE
multi language creating new product by duplicate create translation based on old product

### ISSUE THREAD

**Issue by ioppolo** [odoo/odoo#24693]
Impacted versions:
V10 enterprise

What are the steps to reproduce your issue?
--
You can watch this YouTube Video : https://youtu.be/eU33a04Q_sQ
Runbot tested on V10 enterprise at :
http://327355-10-0-da950e.runbot13.odoo.com/web?debug#min=1&limit=80&view_type=list&model=ir.translation&menu_id=227

Login to Runbot v10 enterprise
Go to settings > Language and find below two language and click on active button
English Australia
Spanish Spaniul

then go to the sales > Products and create a new product named :
"Product A" and save it

Then click on edit and click on the small translate icon next to the product name to open translation page.

Translations are correct. 

Now go back to product A formview and from the action > Duplicate product

The new product is created, Change the name to Product B and save it.

Now click on the edit and click on the small translate icon next to the product name

You will see the translation which is WRONG. 

What is the current behavior that you observe?
--

The second product B translation Table is showing : 

Language                       translated field                    Source term   Destination Term  
-------------------                 ---------------------------------       --------------       -----------------
English (AU)           	product.template,name      Product B	Product A	 
Spanish / Español	product.template,name	Product B	Product A

What would be your expected behavior in this case?
--

The second product B translation Table is showing : 

```
Language                       translated field                    Source term   Destination Term  
-------------------                 ---------------------------------       --------------       -----------------
English (AU)           	product.template,name      Product B	Product B	 
Spanish / Español	product.template,name	Product B	Product B
```
Video/Screenshot link (optional):
https://youtu.be/eU33a04Q_sQ

**Comment by Yenthe666** [comment]
This is actually desired behaviour and how the framework works if I'm not mistaking.
@mart-e can you verify please?

**Comment by mart-e** [comment]
Hello,

Indeed it works as intended.
What you have to keep in mind, when working with multiple languages is that you _must_ check translations when you are working on a translated term. Odoo can not guess if you are changing the full source meaning of just adapting a bit.
When you duplicate, it keeps all the previous translations to avoid you to retranslate it.

Let say you have a a big event happening in Brussels, you write the description in English, French and Dutch.
When creating your next event in Paris, you duplicate the Brussels event, this way, you only need to adapt the parts with the city name but the rest of the translation is already translated (easy, even if you do not speak these languages).
