### ISSUE TITLE
[11.0] Insecure behavior with groups and implied_ids

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24720]
Impacted versions: 11

Steps to reproduce: Install fresh db, install some modules with groups. Create a custom group from settings. Set some other groups to implied_ids.

Current behavior: When assigning my group a user, it gets the groups from implied_ids. When deleting my group from user, all groups from implied_ids remain for the user.

Expected behavior: When deleting my group from user all groups from implied_ids will also lose relation to that user, when the user not inherit this groups from other groups which still related to the user.

In a production environment you can not expect, that the person setting the rights, knows all relations from implied_ids and deletes relations manually. That is really insecure.

**Comment by pedrobaeza** [comment]
That's because you shouldn't make the group assignation/de-assignation that way, but on user form, where hierarchy groups are put on a dropdown combo.

What you ask is not possible, as it would can make more damage than good, removing groups that have might be assigned by other methods.

Closing as the use case doesn't apply for a fix.

**Comment by DR4RCON** [comment]
"That's because you shouldn't make the group assignation/de-assignation that way, but on user form, where hierarchy groups are put on a dropdown combo."  Iam doing this Pedro. Iam assigning groups from user form and it is the behavior I reported.

**Comment by DR4RCON** [comment]
Please link me the documented method for building security groups.

**Comment by pedrobaeza** [comment]
If you do that and put empty the correspondent one, all groups are removed. I think you are making a multi-children hierarchy, and in that way, dropdown is not possible. 

Documentation is https://www.odoo.com/documentation/11.0/reference/security.html

**Comment by DR4RCON** [comment]
I cannot find any hint for creating hierarchy groups.

I create in xml one category and 5 groups which have implied_ids from other modules. I have no documentation or method to define if the category is dropdown or checkmarks. When compare with other like sale, I see no diff.

```
<record model="ir.module.category" id="tom_billardmanager">
            <field name="name">TOM] Billardmanager</field>
            <field name="sequence">8</field>
        </record>

        <record id="group_tom_customer_admin" model="res.groups">
            <field name="name">Admin</field>
            <field name="category_id" ref="tom_security"/>
            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
        </record>

        <record id="group_tom_billardmanager_tournament_user" model="res.groups">
            <field name="name">Tournament User</field>
            <field name="implied_ids" eval="[(4, ref('base.group_public'))]"/>
        </record>

        <record id="group_tom_billardmanager_tournament_manager" model="res.groups">
            <field name="name">Tournament Manager</field>
            <field name="implied_ids" eval="[(4, ref('tom_billardmanager.group_tom_billardmanager_tournament_user'))]"/>
        </record>

        <record id="group_tom_billardmanager_mitglied" model="res.groups">
            <field name="name">Mitglied</field>
            <field name="category_id" ref="tom_billardmanager"/>
            <field name="implied_ids" eval="[(4, ref('project.group_project_user')), (4, ref('base.group_user')), (4, ref('base.group_public'), (3, ref('base.group_document_user')), (3, ref('project.group_project_manager')))]"/>
        </record>

        <record id="group_tom_billardmanager_vorstand" model="res.groups">
            <field name="name">Vorstand</field>
            <field name="category_id" ref="tom_billardmanager"/>
            <field name="implied_ids" eval="[(4, ref('project.group_project_manager')), (4, ref('base.group_partner_manager')), (4, ref('base.group_document_user')), (4, ref('tom_billardmanager.group_tom_billardmanager_mitglied'))]"/>
        </record>

        <record id="group_tom_billardmanager_kassierer" model="res.groups">
            <field name="name">Kassierer</field>
            <field name="category_id" ref="tom_billardmanager"/>
            <field name="implied_ids" eval="[(4, ref('tom_billardmanager.group_tom_billardmanager_vorstand'))]"/>
        </record>
        <record id="group_tom_billardmanager_ceo" model="res.groups">
            <field name="name">Geschäftsführer</field>
            <field name="category_id" ref="tom_billardmanager"/>
            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
        </record>
        <record id="group_tom_billardmanager_vorsitzender" model="res.groups">
            <field name="name">Vorsitzender</field>
            <field name="category_id" ref="tom_billardmanager"/>
            <field name="implied_ids" eval="[(4, ref('tom_billardmanager.group_tom_billardmanager_vorstand'))]"/>
        </record>
```

**Comment by DR4RCON** [comment]
ignore the tuples with (3,     was only the try to unlink them when set to lower group. But that try does not change behavior.

**Comment by DR4RCON** [comment]
@pedrobaeza  I think this informations are to important, as that everybody have to ask in a forum. The security should well documented.
