### ISSUE TITLE
[11.0] Documentation for building security groups missing

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24721]
#24720

Impacted versions: 11

Steps to reproduce: Ask yourself, how you can create security groups with implied_ids, where the implied_ids not remain for user, when the security group is removed from user.

Current behavior: I dont know the right way. From backend and from xml created groups with implied_ids resolve in a insecure behavior.

Expected behavior: I could read how to do it right.

**Comment by pedrobaeza** [comment]
@DR4RCON please don't open more issues like this one, as this is not constructive. Documentation try to be the more extensive possible, but it can cover each of the developers' questions they have in some moment. There are developer books for that. You have also the forums.

**Comment by DR4RCON** [comment]
That is not a question for developers. That wrong insecure behavior is also from backend.

**Comment by DR4RCON** [comment]
Why you close this? How should anybody give a qualified answer for this when it is not documented?
In which forum I can ask the developer of this?

**Comment by pedrobaeza** [comment]
Sorry, but this is not insecure. It's only your opinion.

**Comment by DR4RCON** [comment]
Sure it is, when assigning a group it adds other groups, but when remove the group from user it not removes the other groups. That is asynchrone and not transparent for the user. That is really insecure above all its not documented how to demote a user securily, with all groups former implied.

**Comment by DR4RCON** [comment]
Its only your opinion that it isnt. Would like to here more about this topic from other. So please reopen.

**Comment by Yenthe666** [comment]
@DR4RCON this is actually the way Odoo works by default. The security system is quite granular and flexible and I've never had big issues here. I honestly do not see any issues or security problems in your topic either, it comes down to correct configuration.

**Comment by PCatinean** [comment]
Once again, as explained on IRC there is no current way to determine how a user ended up in a group A:

1. Was he added manually by a user?
2. Was he added by a group B(or C or D) that had implied ids set to group A?
3. Some other way that does not come to mind at the moment.

If you remove a user from a group the implied ids just because you remove him from a group you might be invalidating a manual conscious action or breaking all other groups that might have group A set in implied ids.

If I make a module that adds a group which has project_user group in implied_ids and you make a module that does the same and he removes a user from your group does that mean my application will just stop working?

**Comment by DR4RCON** [comment]
I care for this problem for days, you 10minutes?  Ive thought for all that possibilities. For 30 years in IT ive never had an application with that strange group permission system. But a solution for your scenario is easy. If you set a user to project manager manually, then the manager group is not implied, then the changing of the security group to Mitglied has to remove the project manager group. If there is any other group which implies project manager, then the project manager group remains in user. 
Everyone would like to develop user friendly software and archive user requirements and would like to be secure. This current behavior is the opposite. It does not make it easy for the user to upgrade and downgrade user rights. Its insecure cause you can give more rights with one wrong selection, but you have to make a lot of clicks to undo that selection. And you can not explain a normal user that strange behavior thats just to hardcore for the average user.

**Comment by pedrobaeza** [comment]
You are handling groups like roles, and groups in Odoo are not that. Please undo your 30 years prejudices and simply see how security in Odoo works.

**Comment by DR4RCON** [comment]
Ok, then please explain or point me to the documentation, where an user can upgrade and downgrade an user with not moving through all groups and check if the user is still connected?!

**Comment by pedrobaeza** [comment]
Again that's not how it works, sorry, and this is not a free consultation service. I will give you one hint only, for you to not think I'm rude: https://github.com/OCA/server-tools/tree/10.0/base_user_role

**Comment by DR4RCON** [comment]
Thanks Pedro point me to, this https://github.com/OCA/server-tools/tree/10.0/base_user_role#user-roles does not make less then underlining what iam saying. This default behavior is strange and insecure and if there would not a requirement for beeing different in today usecases, OCA had not developed user-roles. There is no usecases, where you would like to use a feature to upgrade, but not be able to downgrade. Why not reopen a new discussion for changing this in core?

**Comment by pedrobaeza** [comment]
The core is like that because a lot of reasons that you will get when you dig deeper on Odoo, but the good new is that you don't need to change the core for having what you want. Just expand it with modules like the one I have pointed to you. Not everything must be in the core.

**Comment by DR4RCON** [comment]
Pedro why you have just closed instead point me directly to the OCA module, when you should know about it as co-developer. So you know about the problematic, what I assume as Iam not the first with that problem with odoo. But I stay with my opinion, that this should be part of the core module, cause current behavior is everything but not user friendly, transparent or secure. I know we all have not the time for long discussion, but this topic should be important for odoo CE and EE. Sure we are able to solve this on our own, but Iam also interessted in the success of odoo as erp-software.
So please reopen if there is actually not any other public discussion currently about this group permission system.

**Comment by DR4RCON** [comment]
Ok, Ive understand now "Odoo does not have security groups. Only the feature to apply rules in groups. For reject you have to move through every rule.group and remove the user manually"
All that people like https://www.odoo.yenthevg.com/creating-security-groups-odoo/ they are in error to speak from security groups. Me too, how can I abstract from "security group" not beeing secure. This misunderstanding alone is reason enough for this issue. Or is this official politics to be unclear in this important questions?

**Comment by Yenthe666** [comment]
Hmm. You're actually linking to a post of mine, so thanks for saying I'm in error. They are in fact named security groups, you just have to look at them from another perspective. Odoo is very flexible so you can basically do what you like.

**Comment by DR4RCON** [comment]
Really, thats what Ive tried allday to see it from another perspektive, but I can be generous with the term security, but cant call it security group, when the opposite is the fact. At least we all have to see through the eyes of our customers and I would not investigate so much, if that is not a problem for my customers too. As I said above there is obviously a misunderstanding between term "security groups" and in effect how odoo "works". Simple scenario, where the dao sets a high privilegued group to the public user, he recognize his mistake and changes back in the belief, all is like before. That can not be suggested. I can accept that this group system has its reason in architecture to be flexible, but this base_user_role module should be the main feature for setting and unsetting user rights, so that this described scenario can not be reached. 

@pedrobaeza P.S.: Seems as the base_user_role working properly with odoo11, with only changing https://github.com/OCA/server-tools/blob/10.0/base_user_role/data/ir_cron.xml#L13 into 
```
<field name="model_id" ref="model_res_users_role"/>
```
