### ISSUE TITLE
[11.0] Tax calculation incorrect for the Netherlands

### ISSUE THREAD

**Issue by CasVissers** [odoo/odoo#24725]
Impacted versions:
11.0

Steps to reproduce:
Create an invoice with 1 invoice line: 9 x 13,60 with 6% tax. The tax amount = 7,34
Create an invoice with 9 invoice lines: 1 x 13,60 with 6% tax. The tax amount = 7,38

Current behavior:
The calculation is done per line and then summed.

Expected behavior:
 It should be based on the total amount, thus 122,40 

Video/Screenshot link (optional):
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw_berekenen_aan_uw_klanten/btw_berekenen/hoe_berekent_u_btw_aan_uw_klanten (in Dutch) 

**Over het totaal hiervan berekent u btw.** _"On the total amount the tax is calculated"_

**Comment by CasVissers** [comment]
@Yenthe666 Are you aware of this issue?

**Comment by gdgellatly** [comment]
It's not really an issue. Just a setting. Change your accounting setting to
round globally rather 5han per line.

**Comment by Yenthe666** [comment]
Indeed, is it not because you haven't rounded globally but per line? Can you check @CasVissers ?

**Comment by CasVissers** [comment]
:) Sorry!
