### ISSUE TITLE
[Bug] O2M lines populated from Onchange Event, gets appended rather than overriding, when saving....

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#2473]
Using Onchange Event am trying to populate values to One2Many field.. (which is working fine)

But, Consider a scenario... 

Once the record is saved, And again I try to change the value (event triggering field), which in turn calls the Onchange Event, and it again populates the fresh  new One2Many lists... (which is also working perfectly)

But when I save the record, then list  values are changed... i.e. instead of overriding the O2M values, with new lists, it actually appends to the existing list.,....

Let me explain with acute scenario...

I have an object, based on Sale Order Id, am trying to capture its Order lines.... So all i have done is... I have added Order_id (M2O) and Order_lines(O2M)... Onchange Event is written for Order_id, which returns Order_lines pertaining to its order.... (which is obsolutely working fine)...

But the problem arises, with the saved records, If I change the Order_id, surely onchange fetches me the new lines pertaining to the new Order_id, but when I save the record... Order_lines are changed... (i.e. lines of pervious Order and lines of new Order gets saved)...

So I believe, this is a bug in Openerp, because am pretty sure there is nothing wrong in my code... Anybody faced this kind of problem, or any fix for it, do let me know....

**Comment by Yenthe666** [comment]
Hi @deepa4lok,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
