### ISSUE TITLE
[MASTER] Error in vendor bill payment with a tax based on payment

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#24743]
**Impacted versions:**

master enterprise (just FYI)

**Steps to reproduce:**

1. In Accounting / Configuration / Settings: in taxes set true the cash basic configuration
![image](https://user-images.githubusercontent.com/19410285/40074342-5f489656-5847-11e8-9fca-bb918d8124d2.png)

2. in  Accounting / Configuration / Taxes: set the purchase tax with tax_exigibility = base on payment.
![image](https://user-images.githubusercontent.com/19410285/40074582-f5604b3e-5847-11e8-974f-98b4f9f2ec2b.png)

3. Create a vendor bill with the tax mentioned before. Validate it and try to pay it.
![image](https://user-images.githubusercontent.com/19410285/40074703-586e6ed6-5848-11e8-987f-d78c95ccf0a1.png)

Current behavior:

![image](https://user-images.githubusercontent.com/19410285/40074675-3ca4ad00-5848-11e8-94b3-927879dafc16.png)
 

Expected behavior:
Pay the vendor bill

Video/Screenshot link (optional):

https://youtu.be/g18fEX-6Hu4

**Comment by luistorresm** [comment]
Hello @nim-odoo 

We detected this error, only FYI,

This affects the Mexican reports on Master.

Regards

**Comment by Yenthe666** [comment]
@qdp-odoo for your interest, broken in master.
@GavyMG bug reports against the master are not really needed as most likely all this code still changes / get fixed before the 12.0 release though.

**Comment by qdp-odoo** [comment]
was broken since https://github.com/odoo/odoo/commit/d3d26120614139fd7d7e888bd66d21de5158a034

was fixed in https://github.com/odoo/odoo/commit/e2864c8

Thanks for the report :+1:
