### ISSUE TITLE
[11.0] Point of Sale- Price list not show discount to user

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#24747]
**Impacted versions:**
11.0
**Steps to reproduce:**
Complementary to #16549
Configure TPV for enable pricelist
![image](https://user-images.githubusercontent.com/7775116/40091616-687142f0-587e-11e8-8862-d69abacb7e3f.png)
Enable Discount on Sale's configuration
![image](https://user-images.githubusercontent.com/7775116/40091658-9828e0de-587e-11e8-8a15-068d5099a58a.png)
Configure **Discount Policy** on pricelist as _Show public price & discount to the customer_
![image](https://user-images.githubusercontent.com/7775116/40091698-ce1888ac-587e-11e8-92ab-a286da1380fe.png)
Open POS and select Public Pricelist, add lines
**Current behavior:**
Discount is not visible, price unit included discount. **_Configuration on Pricelist is ignored_**
![image](https://user-images.githubusercontent.com/7775116/40092142-65bd7756-5881-11e8-85d5-2716c23ffbb2.png)
**Expected behavior:**
Show price unit and discount, same as Sale Order([backend](https://github.com/odoo/odoo/blob/11.0/addons/sale/models/sale.py#L1173-L1182)).
![image](https://user-images.githubusercontent.com/7775116/40091946-3564fdc8-5880-11e8-91a0-8153ad33d79b.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because PoS doesn't support that feature yet. @pimodoo, is there any plans to support that?

**Comment by sswapnesh** [comment]
Landed in master a #25211
Cc: @pedrobaeza

**Comment by GabbasovDinar** [comment]
I think we need to move `discount_policy` field from `sale` module to `product` module (no need to inherit the `product.pricelist` model in the `sale` module to add the field), because the `discount_policy` field may be used on the `Point of Sale` app only (without installing `sale`)
Cc: @pedrobaeza

**Comment by celm1990** [comment]
Review #26020 

On PR move fields from `sale` module to `product` module

**Comment by mart-e** [comment]
Hello,

As you have figured out, it is not currently supported. We are working on adding this possibility at #26020 but we won't change it in stable version, it is a new feature.
