### ISSUE TITLE
[9.0] Unit price onchange on vendor bills

### ISSUE THREAD

**Issue by ThomasBinsfeld** [odoo/odoo#24740]
Impacted versions:
* 9.0

Steps to reproduce:
* Enable multi currencies
* Enable units of measure management on invoices
* Create a purchasable product with a cost (i.e. 33$)
* Create a vendor bill in a foreign currency
* Add the product on the invoice
* Change the unit of measure to 'Dozen(s)'
* Change the unit of measure to 'Unit(s)'

Current behavior:
* Changing the unit of measures infinitely multiplies the unit price

Expected behavior:
* The unit price should be recomputed correctly at each unit of measure change
* Probably due to this line of code: https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L1244

Video/Screenshot link (optional):
* On Runbot Community 9.0: https://www.youtube.com/watch?v=57miWyNAu10

**Comment by Yenthe666** [comment]
Hi @ThomasBinsfeld,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
