### ISSUE TITLE
[10.0]Key Error 'procelist' when loading TpV if we have a pricelist based on another pricelist.

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#24752]
Impacted versions:
v10
Steps to reproduce:
Load a PoS having a prielist based on another procelist, so the pricelist.version.item field base is 'pricelist'
Current behavior:
We get a Key Error 'pricelist' when loading products in TpV

This is because in the file parts/odoo/addons/product/models/product_pricelist.py, in method _compute_price_rule(), whe have the next code line:
**product.price_compute(rule.base)[product.id]**

When rule.base is equals to 'pricelist', we got key error because of the next line code in the price_compute method:
**prices[product.id] = product[price_type] or 0.0**

In v10 there is no more pricelist field, now is called pricelist_id, so we got the key error in this case.
If we put in the begining of the method the next code we fix the problem.
**if price_type == 'pricelist':
            price_type = 'pricelist_id'**

**Comment by pedrobaeza** [comment]
Can you please propose a PR with this?

**Comment by pedrobaeza** [comment]
Closing as there's a current PR.
