### ISSUE TITLE
AttributeError: module 'stdnum.eu.vat' has no attribute 'country_codes'

### ISSUE THREAD

**Issue by Nimja** [odoo/odoo#24757]
Impacted versions: Odoo 11

Steps to reproduce: 
* Install odoo with requirements.txt
* Install VAT module
* Attempt to add VAT number to partner

Current behavior: 
```  
File "odoo/addons/base_vat_autocomplete/models/res_partner.py", line 52, in vies_vat_change
    if len(partner.vat) > 5 and partner.vat[:2].lower() in stdnum_vat.country_codes:
AttributeError: module 'stdnum.eu.vat' has no attribute 'country_codes'
```

Expected behavior:
* VAT Validation works

Work around:
In your own requirements.txt: `python-stdnum==1.8`

It is caused by: 
`vatnumber==1.2` => Which installs `python-stdnum==1.9`, which was released April 14th. This drops the attribute country_codes

Video/Screenshot link (optional):

**Comment by Nimja** [comment]
I apologize, it appears to be fixed in the most recent commits.

**Comment by pedrobaeza** [comment]
Yeah, in concrete thanks to #24395
