### ISSUE TITLE
Fields do not fit

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#2476]
The total amount field does not fit
![sales-receipt](https://cloud.githubusercontent.com/assets/7593317/4299866/e5845242-3e3c-11e4-8138-4b7cec895e46.png)
. see image.

**Comment by Yenthe666** [comment]
This issue is still present (V8):
![image](https://cloud.githubusercontent.com/assets/6352350/15274693/2d25caf4-1ab9-11e6-836a-d458988e914d.png)
@pna-odoo

**Comment by Yenthe666** [comment]
@pna-odoo and @mart-e, pinging you guys again.
