### ISSUE TITLE
[9.0] Unable to load Payments Matching; Javascript error 

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#24769]
Impacted versions:
9.0

Steps to reproduce:
Have a lot of unreconciled entries
Open Payments Matching for the diary where the unreconciled entries are

Current behavior:
Odoo gives a JS error saying: **Uncaught TypeError: Cannot read property 'animation_speed' of undefined**

Expected behavior:
Show the Payments Matching window

Video/Screenshot link (optional):

![unnamed](https://user-images.githubusercontent.com/8062666/40124115-b8b93424-591f-11e8-8c33-223ce51121d5.png)

**Comment by pedrobaeza** [comment]
Can you reproduce the problem in latest runbot?

**Comment by Yenthe666** [comment]
Hi @hmrodrigues,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
