### ISSUE TITLE
installing odoo11 service issue

### ISSUE THREAD

**Issue by erictang0825** [odoo/odoo#24776]
Impacted versions: 11

i download odoo 11 community on odoo website, then installing that,
but i can't open this url http://localhost:8069 
                                      http://localhost:8069/web/database/manager  
find service in my window service is not work,
try to restart that, but get some error message.

 can help me to fix this issue? thanks.

![o1](https://user-images.githubusercontent.com/39365433/40162013-0c578b6c-59a2-11e8-8366-e63a86a9098b.jpg)
![o2](https://user-images.githubusercontent.com/39365433/40162016-10d81fe4-59a2-11e8-80df-126c2dee5bb0.jpg)
[odoo.log](https://github.com/odoo/odoo/files/2012007/odoo.log)

**Comment by pedrobaeza** [comment]
Sorry, but the information you provide doesn't indicate any problem, but this clearly a deployment problem, not a problem in Odoo itself. Windows is also conflicting itself for making deployments of Odoo. The preferred platform for deploying it is Linux, but any way, it should work at least.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
