### ISSUE TITLE
gevent.wsgi does not exist in 1.3

### ISSUE THREAD

**Issue by schout-it** [odoo/odoo#24779]
https://github.com/odoo/odoo/blob/77aa313b141b9b4c79fa8e24ed0984a9d5c955fe/odoo/service/server.py#L366

gevent.wsgi became gevent.pywsgi in gevent 1.1.0
version 1.3.0 released a couple of days ago removed the backwards compatibility

**Comment by Elkasitu** [comment]
I don't see the problem as we specify gevent 1.1.2 in `requirements.txt`

**Comment by gdgellatly** [comment]
? It was deprecated in 1.1.0. Why would you not want to fix?

**Comment by Elkasitu** [comment]
Because it's not broken

**Comment by gdgellatly** [comment]
So let me get this straight.  You can deploy a non breaking futureproof fix
now using the current API of the pinned version of the lib for which a PR
has already been created, or you can keep the deprecated one, put up with
complaints until such time as you update your requirements file and create
your own PR then?  Seems like a waste of everybody's time for me.

**Comment by Elkasitu** [comment]
I did not see the PR ([don't create issues if you create a PR](https://github.com/odoo/odoo/blob/11.0/CONTRIBUTING.md)), which might change things.

But as a rule of thumb, we don't fix something that's not broken just because it might be broken in the future even if the change *seems* seamless.

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/pull/24780
Linking to the PR to have it here. To me this looks like a good fix with very little harm though @Elkasitu 
In general dependencies are very outdated for Odoo.
