### ISSUE TITLE
[11.0  -->] Sorting on fields is not working properly

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#24789]
Impacted versions:
V11 and higher

Steps to reproduce:
1. Go to a task and enter directly some timesheets lines in the task.
2. Now try to sort on the field Employee.
3. You will see that the sorting is not working properly, see screenshot.

![selection_001](https://user-images.githubusercontent.com/30628967/40176766-ca97c0bc-59dc-11e8-98d7-cbbcf17068f3.png)

Current behavior:
You cannot sort on the field employee in task -> timesheet

Expected behavior:
If you can use the sort functionality in a column, than Odoo should sort it properly.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
May be related to #24019

**Comment by ged-odoo** [comment]
that is weird. i am actually curious

**Comment by sswapnesh** [comment]
Tried same on latest v11(http://517403-11-0-0bf5ad.runbot13.odoo.com/web?debug=#id=25&view_type=form&model=project.task&menu_id=368&action=511)  and seems working well now

**Comment by yung-wang** [comment]
Tested today on latest V11. Seems to be fixed now.
