### ISSUE TITLE
where is report_sxw from version 11 ?

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#24798]
Impacted versions:
11, master

Steps to reproduce:

from odoo.report import report_sxw

Current behavior:

no module named odoo.report

Expected behavior:

should be work

Video/Screenshot link (optional):

the report directory under odoo directory was removed from odoo11, how we can add parser for qweb ?

**Comment by pedrobaeza** [comment]
Old SXW engine was removed already in v11, so it's expected to not be found. You should update your code with current engine tools.

**Comment by GoodERPJeff** [comment]
@pedrobaeza what is the current engine tools for adding custom method to be called in t-esc of qweb?

**Comment by pedrobaeza** [comment]
I have overwriting other times `get_html` method.

**Comment by GoodERPJeff** [comment]
I will try this solution later 

https://www.odoo.com/zh_CN/forum/help-1/question/is-it-mandatory-to-inherit-report-sxw-rml-parse-for-custom-report-even-with-odoo-8-97653

**Comment by GoodERPJeff** [comment]
report_irmodulereference  answered my question, thanks !

**Comment by jeffery9** [comment]
ir.action.report have setup one interface called  `get_report_values`  use to pass customise data into qweb report render.  the step to use this interface..
 

1.  define new model called  `report.%reportname%`
2.   define  mthod `get_report_values`  in this model, to generate data need to render report

**Comment by Ridcull** [comment]
Hi everyone,

Thanks for the post, I have the same problem. Unfortunately my level is not good enough to get your answers T.T
Could a gentle soul help this lost sailor with a more detailed map of the solution, please ? *puppy eyes*

**Comment by Yenthe666** [comment]
@Ridcull give it a try on the official help forums (help.odoo.com), I'm sure somebody can help you out there with a clear example!

**Comment by Ridcull** [comment]
@Yenthe666 thanks a lot for the useful comment! Unfortunately, in Odoo forums there's a system of points (called karma) which impedes me from asking this question there.

**Comment by Yenthe666** [comment]
@Ridcull create your account with your emailaddress. You'll get an e-mail on the mail address. After being verified you get 3 karma, which allows you to ask a new question.

**Comment by etiennebonnafoux** [comment]
I would be also interessed for a clear answer for this issue if someone had one.

**Comment by pedrobaeza** [comment]
@etiennebonnafoux this issue tracker is not for that, so please use the proper channels as indicated.
