### ISSUE TITLE
Not possible to create Mass Mailing Template in Web Editor 

### ISSUE THREAD

**Issue by adfra** [odoo/odoo#2479]
# Short description:

Odoo -> Marketing -> Mass Mailing -> Mail Templates -> Pick one -> click on "Edit Template".

The mail template functionality in the web frontend is thoroughly broken, not even sure how to describe the error. Please see attached picture. Irrelevant templates are not hidden, the CSS is not interpreted correctly etc. etc.

There are a range of issues when trying to create a mailing in the web editor, so if you are having a go at this one, please go through the full process. Note that establishing the template through the backend edit function seems to work fine.

Btw - a very similar problem seems to be there when editing the email templates from Technical Settings - Email - Templates within the website builder.
# Impacted versions:

v8.0rc1
# Steps to reproduce:

Attempt to create/modify Mail Template from Marketing -> Mass Mailings -> Mail Templates -> Edit Template
# Current behavior: #

See image.
![mass mail](https://cloud.githubusercontent.com/assets/8445317/4300536/d41aed1e-3e45-11e4-852b-9e36504300cf.png)
# Expected behavior:

Clean form in which I can create / edit a single html email template using the web editor html blocks / widgets.

**Comment by tvld** [comment]
We have this problem on a complete new installation today... We can not find this "website_mail"  module though...

**Comment by VascoVisser** [comment]
I'm also having this problem on a new installation. I can't edit the templates, everything looks scrambled. I can't start from a clean template. There is nothing to suggests what variables are available and can be included in the template. The preview also doesn't work: drop down with customers/leads is empty, so I can't select an example.

**Comment by Yenthe666** [comment]
Should have been handled (as beledouxdenis said) and as V8 is no longer supported this can be closed.
