### ISSUE TITLE
Sending mail to wrong recipients in 'Sales'

### ISSUE THREAD

**Issue by giusygiallara93** [odoo/odoo#24808]
Impacted versions:10.0

Steps to reproduce: I create an order, I send the order e-mail, I remove the customer's e-mail address (which I visualize of defaut) and insert another e-mail associated with a contact. 

Current behavior: Send me the same email to the customer's email (which I did not enter) and also to the other email that I entered. I have this error both in sending orders and in invoices.

Expected behavior: I want to be able to send the email of the estimate or invoice to recipients who are not the customer.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think you are not understanding the social mechanism of Odoo. To start with, Odoo is not a mail client. It's a system who takes care of being a hub of all communications, and this is through followers. If someone is a follower of one thread, he/she will receive the email. Adding other emails in the compose wizard you will add that partner to the thread, but not remove the others.

So to achieve what you want you have to modify the followers.

Closing as no real issue.
