### ISSUE TITLE
_quant_reconcile_negative is very solw with large amount of negativate quants

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#24821]
Impacted versions:
  -Version 8.0
Steps to reproduce:
  -Sell a lot of products without stock (create a lot of negative quants)
  -try to create an opening balance by doing receipt pickings
Current behavior:
  -The transfer process take a lot of time (1.5-2 hours) per transfer with only 20-40 products to receive
Expected behavior:
  -Shouldn't take that long !

**Comment by pedrobaeza** [comment]
Sorry, but version 8 is already out of its life cycle and it doesn't receive support anymore. Migrate to a newer version, where this process has been already improved.

**Comment by ronozoro** [comment]
@pedrobaeza actually the issue is still with v10 too. Is v10 also doesn't receive support anymore?

**Comment by Yenthe666** [comment]
@ronozoro 10 is still reported. Can you update the initial comment to the V10 issues and reproducible steps? If that is done then ping me back and I'll reopen.

**Comment by ronozoro** [comment]
@Yenthe666 No need to reopen,i created a new one #24825 as the problem is seen in both v8 and v10.Reconciling negative quants takes a lot of time due to spiting and merging.I had to stop this function to be able to transfer the opening balance records.
