### ISSUE TITLE
how to add attachment in helpdesk when submit ticket on website form?

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#24828]
Impacted versions:10

Steps to reproduce: submit ticket on website form

Current behavior: no attachment field

Expected behavior: Add attachment field

Video/Screenshot link (optional):

Normally when a customer submit a ticket, he mostly have a proof for attachment. It is kind of basic function for all ticket system. But I can not see how to add a attachment on website form when submit an issue on website helpdesk. Is this feature do not exist of some settings I did not perform?

**Comment by pedrobaeza** [comment]
As this is an enterprise option, please submit an OPW ticket through https://www.odoo.com/help, but this is mostly a question, so maybe a better host for it is the official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
