### ISSUE TITLE
_quant_reconcile_negative method is very slow with large amount of negativate quants

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#24825]
Impacted versions:
  -V10.0 & V8.0
Steps to reproduce:
-(Deliver 'Short sale') a lot of products without stock (create a lot of negative quants)
-try to create an opening balance by doing receipt pickings
Current behavior:
-The transfer process take a lot of time (1.5-2 hours) per transfer with only 20-40 products to receive
Expected behavior:
-Shouldn't take that long !

**Comment by jco-odoo** [comment]
We are not going to improve that still in stable (also in v11, it is working differently).  You should try to avoid having too many negative quants, by e.g. doing an inventory adjustment from time to time.
