### ISSUE TITLE
[v7, v8] Weeknumber timesheet is wrong

### ISSUE THREAD

**Issue by ploegvde** [odoo/odoo#2483]
The week on the created timesheet is wrong. There is already fix in LP for this, but this is not merged in V7 nor V8. I think it is important to merge this, at least to V8. Can you have a look at that?

https://code.launchpad.net/~openerp-dev/openobject-addons/7.0-opw-602425-msh

**Comment by Yenthe666** [comment]
@ploegvde,

I'm really missing some context / info on how to reproduce this.
Could you confirm the issue is still present or not? If it is still present please provide some extra information / screenshots.

**Comment by ploegvde** [comment]
Haha, you realy want to close all. You're great. I just tested only in v8 and it is ok now. Issue can be closed.

**Comment by Yenthe666** [comment]
I do want to get a lot of them cleaned out! Thanks for the quick reaction and closing the issue!
