### ISSUE TITLE
Duplicate of tables in pos restaurant

### ISSUE THREAD

**Issue by minaeid90** [odoo/odoo#24831]
Impacted versions: 11

Steps to reproduce: 

Add new tables in POS screen, close the screen and resume the session again, the tables you created duplicate

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Indeed I have been able of reproducing this problem in runbot. The extra step not specified in the steps to reproduce is that you need to access to the new created table (or at least is how I get it to reproduce it):

![pos](https://user-images.githubusercontent.com/7165771/40382948-e45fea98-5dff-11e8-885d-8aae4a5966f3.gif)


@pimodoo can you take a look to this?

**Comment by pedrobaeza** [comment]
There are some insights of the problem in #27921

**Comment by pedrobaeza** [comment]
@qle-odoo maybe you can attend this, that is an old bug.

**Comment by lastalfriday** [comment]
And this is the fix:
```
                    .then(function (result){
                        var table = result[0];
                        for (var field in table) {
                            self.table[field] = table[field];
                        }
                        self.renderElement();
                    });
```

**Comment by Yenthe666** [comment]
@lastalfriday we encourage people to make a PR to fix issues in Odoo. We'd love to see yours here too, please feel free to make one.

**Comment by qle-odoo** [comment]
@switch87 can you look at this.

**Comment by switch87** [comment]
Closed by  #27924

**Comment by switch87** [comment]
You can see it in the pull request

**Comment by sswapnesh** [comment]
Hello @switch87 
Still same Issue in v12

**Comment by switch87** [comment]
@sswapnesh I tried to reproduce on runbot, the problem initially mentioned in this issue is still fixed.
