### ISSUE TITLE
Freeze during installing apps

### ISSUE THREAD

**Issue by tibo-bogota** [odoo/odoo#24838]
Impacted versions: 10.0

Steps to reproduce: I install varios addons (web responsible, Backend Theme, Odoo web login) and then it just freeze when I want to installed any new apps. I try few time, and it's all the them. I don't undustand, it work before. What can I do ?

Current behavior:  Freeze during installation of apps. 

Expected behavior: install new apps

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in that code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
