### ISSUE TITLE
[stock_account] button to_refund with widget boolean_toggle not visible

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#24835]
Impacted versions:
* 11.0

Steps to reproduce:
in one picking in done try to return and in the line of return pass to True the button to_refund

Current behavior:
when I want to clic in button the field is disable and not change to True and the widget looks like invisible,
![wh in 00107 odoo](https://user-images.githubusercontent.com/7595505/40320037-de52aef8-5cef-11e8-8e2d-52459ab07a2f.png)

  
Expected behavior:
make visible the button

**Comment by pedrobaeza** [comment]
I agree this is not very visible, and it requires 2 clicks for being activated. The good news is that on master, these 2 problems have been solved:

* You can now directly click on the toggle button without needing to click first on the line.
* The styles have been slightly changed for a better visualization of the toggle.

Unfortunately, this can be changed in current stable branches, so you'll have to wait for the new version.

**Comment by hugho-ad** [comment]
@pedrobaeza can you share us the commit at master branch please?

**Comment by pedrobaeza** [comment]
Sorry, but no, but you can easily test it on runbot on master branch.

**Comment by deivislaya** [comment]
@pedrobaeza 

The bug has reappeared in the master branch

Attach Video https://youtu.be/-jl4NWN_kPg

**Comment by pedrobaeza** [comment]
There's now another opened issue about this in #24883, so let's continue there.
