### ISSUE TITLE
I can't specify a route for product variants individually

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#24840]
Impacted versions:
11.0
Steps to reproduce:
- I create a Product Template A , A have 2 product variant:A1,A2.
- I want to set product A1 's route  only to  buy, prodct A2's route only to manufacture.
- When I set A1's route to buy, product A2's route had set to buy .

How to set produt
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Currently, the routes are set by template, not by variant, so this is not going to change for v11. For getting the desired behavior, you need to program a custom module.

@jco-odoo I suppose there's no plan for changing this for upcoming versions, isn't it?

**Comment by jco-odoo** [comment]
Indeed, no plans for this.

**Comment by lalitkumar2k10** [comment]
Hi, Is there any solution implemented yet?

**Comment by harryiliffe** [comment]
Hello, I'm also interested in a solution for this!

**Comment by grzekru** [comment]
@pedrobaeza 

Hello, i need this feature in odoo 13.
I've added new field to produt.product model
```
route_ids = fields.Many2many('stock.location.route', 'stock_route_product_variant',
                             'variant_id', 'route_id', 'Routes',
                             domain=[('product_selectable', '=', True)])
```

Do you think this is a safe solution and will not cause problems in the system?

**Comment by pedrobaeza** [comment]
I can't say right now, but probably yes. It depends if the access to such field in the business logic is through variant or through template.
