### ISSUE TITLE
[11.0]  Issue with widget handle

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#24843]
Impacted versions:
11.0
Steps to reproduce:
Add some items on a X2many field with widget="handle".
Reorder them using the widget.
Add a new item.
Current behavior:
The new item isn't at the bottom.
Expected behavior:
The new item should be at the bottom. 
Video/Screenshot link (optional):
[Video](http://www.k-upload.fr/afficher-video-2018-05-22-1e97dba66output.mp4.html)

**Comment by pedrobaeza** [comment]
Already notified in #10003, so we continue there.
