### ISSUE TITLE
[11.0] Character encoding in message notification

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#24846]
Impacted versions:
11.0
Steps to reproduce:
Fill the parent_id field of an user.
Put a quote (') on the parent_id's name.
Send a message from this user.
Current behavior:
Display & #x27; (without space)
Expected behavior:
Display Correctly the parent_id's name
Video/Screenshot link (optional):
![your](https://user-images.githubusercontent.com/25034353/40357050-468aafb8-5dbb-11e8-976b-718c968fcddb.png)
![popup](https://user-images.githubusercontent.com/25034353/40357060-4e9144d8-5dbb-11e8-924d-ac010304ce9b.png)
![popup2](https://user-images.githubusercontent.com/25034353/40357321-1a9bed26-5dbc-11e8-816b-849a42e51bff.png)
EDIT: 
same with & (& amp;) and " (& quot;) and probably others chars

**Comment by Linekio** [comment]
I took screenshot from runbot.
 Second and this screens show the same browser notification but with different browsers.
The problem is in the browser notification when using chatter.

**Comment by mart-e** [comment]
Hi,

I just tested and it seems it works fine

![Screenshot from 2020-02-04 08-32-50](https://user-images.githubusercontent.com/564822/73723712-ffdb1300-4729-11ea-816d-81f22a578362.png)

I am closing but we can reopen if I missed something

**Comment by mart-e** [comment]
My bad, it was actually still reproducible (my screenshot was on an internal notification, not a native browser notification).
I have fixed the issue in master at #44550
Thanks for the report and sorry for the delay
