### ISSUE TITLE
Returned and refunded products won't create new delivery orders after SO update

### ISSUE THREAD

**Issue by rvw0** [odoo/odoo#24858]
Impacted versions: 11.0

Steps to reproduce: 
* Create new Sale Order with a Product that needs delivery and confirm sale
* Deliver the products and then return & refund them
* Set ordered quantity to 0 and save
* Set ordered quantity to desired amount and save

Current behavior:
Nothing happens. 

Expected behavior:
New Delivery Order with desired product quantity

Video/Screenshot link (optional):
https://streamable.com/lime2
(http://330138-11-0-739571.runbot16.odoo.com/)

OPW-1850683

**Comment by hdh-odoo** [comment]
I couldn't reproduce on odoo 11. Given links aren't working. Please let me know if issue persists !

**Comment by Yenthe666** [comment]
Hi @rvw0,

Did you ever get feedback on the odoo enterprise report that solved your issue?
@mart-e any chance you can quick check the OPW please?

Regards,
Yenthe

**Comment by mart-e** [comment]
Hi,

This issue was qualified as an unsupported behaviour. To quote my colleague who has worked on it:
> The workaround would be to "return" the "return" move.

If somebody wants to submit a PR to work with this in the future we can review it but we won't change that in stable.

Regards,
