### ISSUE TITLE
Getting error of js when installing account module.

### ISSUE THREAD

**Issue by HirenDangar** [odoo/odoo#24856]
Impacted versions:
community  v11.0

Steps to reproduce:
1.- Install account module

Current behavior:
Getting  traceback when installed account module.

![v11error](https://user-images.githubusercontent.com/16575953/40410369-40fd2abe-5e8b-11e8-9a70-715077fb9307.jpg)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
