### ISSUE TITLE
Valuation Account on Stock Location should be company dependent

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#24862]
Impacted versions: master

Steps to reproduce:
  - Create two companies with different COA.
  - Install `stock_acount`.
  - Try to assign **Stock Valuation Account** of Virtual Locations (like Scrap or Production) for each company.

Current behavior:
If account was set with account from Company A, switching to Company B will not allow to set it again.
You will receive access error because you are trying to read account from other company.

Expected behavior:
Each company can configure it's own valuation accounts on virtual locations.

Video/Screenshot link (optional):
https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L37-L50

**Comment by nhomar** [comment]
Closing as wishlist, due to the fact that this brake stable policy.

**Comment by gdgellatly** [comment]
This is a bit of a non issue tbh,  All you do for virtual locations with locations with accounts is have one for each company and set the default location properties as company specific in settings.
