### ISSUE TITLE
[11.0] Copy User triggers Mail with password link to source user

### ISSUE THREAD

**Issue by KarstenK77** [odoo/odoo#24860]
Impacted versions: 11

Steps to reproduce: Copy any User.

Current behavior: With copy odoo triggers an email to the source user.

Expected behavior: Copy a user should not trigger mail with password link. When changed email of target user and save, then it could trigger the password link mail, but not before.

Or email should get attribute copy=False   Anyway per default there could only be a unique Emailaddress.

**Comment by Yenthe666** [comment]
@mart-e for you, perhaps a copy=False is neat here?

**Comment by pedrobaeza** [comment]
I reported 2 days ago an enterprise ticket for exactly this. The number is 1850206.

**Comment by krueger80** [comment]
And ticket 1847328 about shopping cart stolen by new user because the field last_website_so_id didn't have copy=False too.

**Comment by sswapnesh** [comment]
Will be managed in d0d93b8d583198df942747879e3ac1d755b4132c @#25419

**Comment by sswapnesh** [comment]
Fixed in #25419

**Comment by Yenthe666** [comment]
Yep, done at https://github.com/odoo/odoo/commit/2e4a75cbee162381c814ccc3e07d61c35dc88485
