### ISSUE TITLE
Possible error in the calculation of delivery costs with the "delivery" module.

### ISSUE THREAD

**Issue by msimof** [odoo/odoo#24874]
Impacted versions: 
8.0

Steps to reproduce:
We create two conditions in the delivery cost:
1 condition: price> 500, sale price = 0
2 condition: price <500, sale price = 39.

We create a sales order, we add a product with price without taxes 499. We press the button to calculate the costs. The calculation is 0, because 499+ taxes is greater than 500.
We create another sales order, we add the same product with price without taxes 499.
We do not calculate the delivery costs in the sales order, we do the steps to create the invoice and odoo automatically calculates a delivery cost line and the calculation is 39. Because 499 <500

Current behavior:
If I calculate the delivery costs in the sales order, the expenses are calculated on the total price of the order (Untaxed Amount + taxes). But if I calculate the delivery costs automatically on the invoice, they are calculated only from the tax base.

Regardless of the conditions we have created for the calculation of the expense, the calculation will be different depending on how it is calculated.

Expected behavior:
I believe that the calculation must be the same in the sales order as in the invoice so that the conditions of the calculation serve in both situations

Thank you

**Comment by Yenthe666** [comment]
Hi there,

We're sorry but Odoo 8 is no longer supported. The Odoo long term stable policy is only for the latest three versions.
Don't hesitate to create a new bug report if you can reproduce the same problems in Odoo 9 or up though!

Regards,
Yenthe
