### ISSUE TITLE
[IDEA] popup for hidden field in tree view

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#24879]
Hi Community

I think to some thing to add information in tree views without add columns.
When you pass your mouse on the I icon you see a popup with field with attribute `hidden="1"`.

![image](https://user-images.githubusercontent.com/16716992/40449466-cdbf7bc6-5ed8-11e8-8341-a97e5ac4f616.png)

What do you think ?

@pedrobaeza @Yenthe666

**Comment by krueger80** [comment]
Instead of that, I would prefer to have the ability to change the view per user base or for everyone (like for saving favorite search). So I could remove and add columns if I want and reset the view to come back to default. The popop you talk about would not allow sort and is too limited imho.

**Comment by antonylesuisse** [comment]
Hidden means "not visible". I dont think we should add an attribute or clutter the view. Studio allows you to add or remove columns in 3 clicks (of course this is global).
