### ISSUE TITLE
[11.0] Scanning a barcode on delivery does not update the done quantity

### ISSUE THREAD

**Issue by cpintofonseca** [odoo/odoo#24872]
Impacted versions:
11.0

Steps to reproduce:
On Odoo 11.0 Enterprise runbot (to avoid listing the installed modules) create a new Sale Order with the product that has the following barcode: 054398267125. After that, confirm the Sale Order, navigate to the related delivery, click in the "Edit" button of the delivery and scan the barcode. Please make sure the product is reserved before clicking in the "Edit" button.

Current behavior:
The "Done" quantity is updated only when we click in the "Save" button after scanning the barcode, assuming a candidate was successfully found.

Expected behavior:
The "Done" quantity should be incremented by 1 immediately after scanning the barcode, assuming a candidate was successfully found.

Video/Screenshot link (optional):
https://youtu.be/JavpM46uMn0

**Comment by amoyaux** [comment]
Hey @cpintofonseca,

It happens because you are using the regular view with stock move. However barcode increment quantity on move line. You should pass through the barcode app in the app switcher or enable 'Show Detailed Operations' on your picking type.
