### ISSUE TITLE
[Proposal] Renovate: CI

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24871]
https://github.com/marketplace/category/continuous-integration

The issue with runbot is:

- Not future proof, nor standard compliant
- Ignores best practices (eg. CI pipeline yml files)
- High ongoing investment in maintenance
- Makes Odoo a bad ecosystem player (for me that's the most worry-some)

@yelizariev

**Comment by pedrobaeza** [comment]
David, as said this should be discussed on mailing lists (and without too much meaning I have to say, as Odoo is not asking you opinion in this), not here, but I let @mart-e to decide for not being the only one thinking this way.

**Comment by blaggacao** [comment]
About open discussion: https://github.com/odoo/odoo/issues/24869

**Comment by Yenthe666** [comment]
@blaggacao I do suggest you to take these concepts to the mailing list, the help forum (help.odoo.com) or some related channel. You'll have more success there 😉

**Comment by blaggacao** [comment]
Reason for closure: https://github.com/odoo/odoo/issues/24869#issuecomment-391361145

"wont-fix" would be a very digestible labeling alternative to communicate the essence of that decision...

**Comment by blaggacao** [comment]
https://github.com/odoo/odoo/issues/24869#issuecomment-391377838
>please do keep in mind that we are not community-driven

This is actually new information to me, I might have missed something or misinterpreted in the past.
I think it would help others to not feel bad about some "ways" of doing things if this would be stated more clearly. Not stating it is putting contributors at risk of confounding "open-source" with "community-driven" which in the great majority of projects goes hand in hand.

Seriously, I did not acknowledge this fact before your comment. Also because of communication pieces like the left hand side of https://co.linkedin.com/in/olivierdony 's wallpaper.

Making things extra clear would genuinely avoid a lot of open or tacit conflict.
@mart-e
