### ISSUE TITLE
[Proposal] Renovate: Build Odoo.sh arround k8s

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#24870]
https://github.com/xoes/odoo-operator

The current issues with odoo.sh:

- Black Box
- Not easily extensible (to meet market demand for integration and enterprise grade deployments quickly)
- Not emerging standards compliant / future proof
- No support other than by Odoo SA
- Bad ecosystem player by reinventing the wheel (at least from what's known publicly)

@yelizariev

**Comment by pedrobaeza** [comment]
Other issue to be considered to be closed as vague and irrelevant, @mart-e

**Comment by blaggacao** [comment]
About open discussion: https://github.com/odoo/odoo/issues/24869

**Comment by blaggacao** [comment]
@pedrobaeza You can have a look at the related link for a detailed example of what is purpotrated by this issue :wink:

**Comment by blaggacao** [comment]
I'm fully aware that I'm being audacious, here. After all that's the only way to tackle the future. :wink:

**Comment by Yenthe666** [comment]
@xmo-odoo please don't just close off an issue without any information, that is rude. How would you feel if somebody did that to you?
Can't we just answer on the issue and tell @blaggacao why we close it off? I bet that a one liner answer would already be enough to be friendly and gives the OP insight.

P.S: to be clear, I am not choosing sides here and I'm not judging anyone. I just like communication. 😉

**Comment by pedrobaeza** [comment]
@Yenthe666 there is no rudeness, there is pragmatism. If you see the issues history with this user, you will see patterns :wink:

**Comment by Yenthe666** [comment]
I agree @blaggacao sometimes has odd topics and/or tries to push into new ways but is it really that bad? Sometimes from these kind of discussions new ideas or concepts arise. Atleast that is what I like to believe.
And sorry but a closure without any comment is rude, there is no other way to say it. No matter the history and if the OP has made 'shitty' topics it is still  a person that deserves an answer. One should not judge by the history or similar cases in the past.

**Comment by blaggacao** [comment]
> If you see the issues history with this user, you will see patterns

This is an personally targeted insinuation. Unfortunately, not a respectful one.

**Comment by blaggacao** [comment]
Getting back On Topic (in terms of this issue) for future readers
----

I propose the [operator-pattern](https://www.redhat.com/en/blog/introducing-operator-framework-building-apps-kubernetes) as an alternative implementation of running odoo workloads at scale and under a fully controlled environment. Anyone willing to join or read more is invited to push the discussion forward on: https://github.com/xoes/odoo-operator

(No rude down closing guaranteed :wink: )

**Comment by mart-e** [comment]
As for the runbot topic, odoo.sh is a tool we have made for a specific need : provide an easy deployment platform for module developers that are not system administrator.
You will not be able to do what you were doing on your own server but that is not the point!

We believe there is too many people that badly deploy their custom Odoo modules and ends with slow, unsecured and outdated Odoo instances. We give an option to these people focus on what they are good at (coding).
odoo.sh should be seen as odoo.com : a non-free (as beer _and_ speech) service that we offer but do not force anyone to use if it is not what you are looking for.
If you are paying user of the service of odoo.{com,sh}, you can, as always, contact the support for claims or suggest improvements.
But again, this github repository is not the place for this kind of discussions.

**Comment by blaggacao** [comment]
>The purpose of the issues is probably to warn odoo and the community that there are alternative approaches which should be considered at least

Point made.
Consider yourself being informed.
