### ISSUE TITLE
[OAuth][Google] redirect_uri set to 127.0.0.1

### ISSUE THREAD

**Issue by sebastien-kr** [odoo/odoo#24882]
_Disclaimer  : this is strictly the same issue as #6556 . But as stated in the [last message](https://github.com/odoo/odoo/issues/6556#issuecomment-351340533), a new issue is needed, so here we are._

Impacted versions:
 - At least Odoo 11.0-20180515 (Community Edition).

Steps to reproduce:
 1. Use Odoo behind a reverse proxy. 
 1. Active Google OAuth login
 1. Setup your Google OAuth credentials
 1. Enjoy the Error 400 that shows up when clicking on "Login with Google"

Current behavior:
 - 🐛 A 400 error from google shows up with the following content : 
 - 🐛 The `web.base.url` value is ignored
 - There is no way to edit this `127.0.0.1` out

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://127.0.0.1:8069/auth_oauth/signin, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/....
```

Expected behavior:
 - The google login page should be shown
 - The `redirect_uri` value should either be editable OR it should be the same as the  `web.base.url` value

Video/Screenshot link (optional): Nope.

**Comment by pedrobaeza** [comment]
@mart-e as you have been touching about Google lately, can you say something about this?

**Comment by mart-e** [comment]
This seems to be linked to `auth_oauth` module, not Google.

@beledouxdenis in the 8.0 report, at https://github.com/odoo/odoo/issues/6556#issuecomment-339325778 there was a patch proposed to use `web.base.url` instead of `request.httprequest.url_root`. What do you think?

```diff
--- /usr/lib/python2.7/dist-packages/odoo/addons/auth_oauth/controllers/main.py-orig    2016-12-04 07:54:25.469995024 +0000
+++ /usr/lib/python2.7/dist-packages/odoo/addons/auth_oauth/controllers/main.py    2016-12-04 08:22:55.712403078 +0000
@@ -56,7 +56,7 @@
         except Exception:
             providers = []
         for provider in providers:
-            return_url = request.httprequest.url_root + 'auth_oauth/signin'
+            return_url = request.env['ir.config_parameter'].get_param('web.base.url') + '/auth_oauth/signin'
             state = self.get_state(provider)
             params = dict(
                 response_type='token',
@@ -71,7 +71,7 @@
     def get_state(self, provider):
         redirect = request.params.get('redirect') or 'web'
         if not redirect.startswith(('//', 'http://', 'https://')):
-            redirect = '%s%s' % (request.httprequest.url_root, redirect[1:] if redirect[0] == '/' else redirect)
+            redirect = '%s/%s' % (request.env['ir.config_parameter'].get_param('web.base.url'), redirect[1:] if redirect[0] == '/' else redirect)
         state = dict(
             d=request.session.db,
             p=provider['id'],
```

**Comment by pedrobaeza** [comment]
According @beledouxdenis's comments, I close this as no real Odoo issue, but misconfiguration on the deployment side (specifically in reverse proxy configuration).

**Comment by kainhofer** [comment]
I ran into the same problem. The issue here was that the auth_oauth addon explicitly checks for the X-FORWARDED-HOST header, while Nginx Proxy Manager by default sets only HOST, X-FORWARDED-PROTO, X-FORWARDED-SCHEME, X-FORWARDED-FOR and X-REAL-IP....

Adding the 
```
proxy_set_header X-Forwarded-Host $host;
```
cannot be done in NPM's Advanced tab for the host (due to an Nginx-peculiarity), but needs a separate Custom location for url "/" (with the same forwarding settings as the proxy host) where you can add it in the settings. 

That solved the problem for me.
