### ISSUE TITLE
Stock Picking - Return form's "To Refund" toggle button doesn't responsive

### ISSUE THREAD

**Issue by Arvinman** [odoo/odoo#24883]
Impacted versions:
Odoo 11: reproducible since this commit in odoo-11 branch

> 

Revision (SHA-1): 2f5e44d40b35ea6790a5e10223273c0cbe900c87
Date: 4/18/2018 3:44:01 PM
[FIX] web: checkbox in editable list are clickable

>

Steps to reproduce:
- Go to Inventory / Operations / Transfer.
- Open any validated (done) transfer and then click on Return button to open return form.

Current behavior:
- A click on [To Refund] toggle button sometime will not change the value between True/False.
- A double click on [To Refund] toggle button sometime can change the value.
- Once user click on [To Refund] a purple area of the button is gone.
- *User must exactly click on White area of toggle button to change the value.

Expected behavior:
- A single click on [To Refund] toggle button on any area of it should change the value back and forth

Note: 
- Reproducible in both Google's Chrome 66.0.3359.181, Firefox 66.0.1

**Comment by pedrobaeza** [comment]
Can you please make a video with this to see that behaviors?

**Comment by sswapnesh** [comment]
Not only in Stock Picking - Return form but it works Same way in each editable list view.

**Comment by pedrobaeza** [comment]
I see. @ged-odoo there was recently a commit about this, but I can't find it. Can you point us to the person that can attend this?

**Comment by jso-odoo** [comment]
Hello @Arvinman ,
Let me know if you're still facing the issue.! 
Because, I'm not able to reproduce your issue as I've checked it on runbot where the **toggle button** is removed and **checkbox** is added which works is working as expected now.

**Comment by Arvinman** [comment]
Hello @jso-odoo, 
The issue was resvoled. Thanks

**Comment by pedrobaeza** [comment]
Closing this then.
