### ISSUE TITLE
Accounting Partner Ledger report (Japan date)

### ISSUE THREAD

**Issue by thanglt0209** [odoo/odoo#24881]
Impacted versions:
Odoo 10.0-20180214

Steps to reproduce:
Languages: Japanese
Date Format: %Y年%m月%d日
Menu: Accouting/ report/ pdf reports/  Partner Ledger -> Print
Menu: 会計/ レポート/ PDF　レポート/  取引先元帳 　-> 印刷

Current behavior:
Get error: '     r['date'] = datetime.strptime(r['date'], DEFAULT_SERVER_DATE_FORMAT).strftime(date_format)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u5e74' in position 2: ordinal not in range(128) '

Expected behavior:
Download pdf report

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10916115/40521927-0edbc002-6009-11e8-94b8-2bbc36548f94.png)
![image](https://user-images.githubusercontent.com/10916115/40459030-0d0f6816-5f3a-11e8-9880-e6d335c87662.png)

I think the problem is there: 
/odoo/odoo/addons/account/report/account_partner_ledger.py
r['date'] = datetime.strptime(r['date'], DEFAULT_SERVER_DATE_FORMAT).strftime(date_format'))

I had fix like this
r['date'] = datetime.strptime(r['date'], DEFAULT_SERVER_DATE_FORMAT).strftime(date_format.encode('utf-8'))

**Comment by thanglt0209** [comment]
![image](https://user-images.githubusercontent.com/10916115/40460621-9eb89622-5f42-11e8-81b1-f3f72645ac44.png)

**Comment by Yenthe666** [comment]
Dear @thanglt0209,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
