### ISSUE TITLE
Supplier product code + partner ref bug: For/else bug in addons/product/models/product.py

### ISSUE THREAD

**Issue by mduvergey** [odoo/odoo#24890]
Impacted versions: Odoo 11, Odoo 10

Steps to reproduce:
Create a purchase order from a given supplier containing a product that has a custom product code (i.e. different from the default product code) for that supplier.
_for/else constructs in methods **ProductProduct._compute_product_code()** and **ProductProduct._compute_partner_ref()** lack a break keyword._

Current behavior:
If a product has a custom product code for a given supplier, the code is not displayed.
_The **else** part of the **for/else** construct is always executed since no **break** keyword is present._

Expected behavior:
If a product has a custom product code for a given supplier, the code is displayed properly.
_A **break** keyword should prevent the **else** part to be run if the need arises._

**Comment by Yenthe666** [comment]
@mduvergey you're welcome to make a PR to improve this though!

**Comment by Yenthe666** [comment]
Thanks a lot!

**Comment by mduvergey** [comment]
PR done, should I close the issue?

**Comment by pedrobaeza** [comment]
Yes, we continue through the PR #24905
