### ISSUE TITLE
Client Error when generating any report with Chrome 66

### ISSUE THREAD

**Issue by nilshamerlinck** [odoo/odoo#24894]
Impacted versions: 9, 10, 11 + Chrome 66

Steps to reproduce: Try to generate any report, for example `Sales > Orders > Quotations > Print` 

Current behavior: Fails with a misleading error message:

```Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://330568-11-0-1e21b7.runbot14.odoo.com" from accessing a cross-origin frame.```

![image](https://user-images.githubusercontent.com/511258/40485697-72b3c320-5f89-11e8-8421-56fcc389d8be.png)

**Comment by nilshamerlinck** [comment]
The root cause is a [regression in Chrome 66](https://bugs.chromium.org/p/chromium/issues/detail?id=845443&can=2&q=845443&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

There are 2 workarounds:
- Disable `chrome://flags/#click-to-open-pdf`
- or Disable `chrome://settings/content/pdfDocuments`

Chromium team is working on a fix that should be rolled out shortly.

**Comment by Yenthe666** [comment]
@nilshamerlinck,

Thanks a lot for the report.
You seem to have already found the culprit and it is Google Chrome, not Odoo so I believe we can close this issue off? It is not related to Odoo specific.
Correct me if I'm wrong.

Regards,
Yenthe
