### ISSUE TITLE
Fail to search purchase order by vendor

### ISSUE THREAD

**Issue by wangsamas** [odoo/odoo#24908]
Impacted versions: 11

Steps to reproduce: 
Open purchase menu, enter a vendor name in search field.

Current behavior:
No purchase order showed

Expected behavior:
Purchase orders list with the vendor name showed

**Comment by gdgellatly** [comment]
Um no.  Just use the already included partner filter.

https://github.com/odoo/odoo/blob/11.0/addons/purchase/views/purchase_views.xml#L313

**Comment by yusufdw** [comment]
Maybe you can use Search Vendor for ....
![screenshot from 2018-05-25 10-31-16](https://user-images.githubusercontent.com/25214401/40524802-da149d6e-6006-11e8-8cc3-b48a9574029c.png)

**Comment by Yenthe666** [comment]
Indeed, you can use the filter as suggested by @gdgellatly.
There is no real issue here.
