### ISSUE TITLE
POSBox recognize the printer but doesn't print.

### ISSUE THREAD

**Issue by jcguzman11** [odoo/odoo#24906]
Hi everyone, I'm running Odoo v10 Point of Sale and using the PosBox v16.

I bought the thermal printer STAR TSP100, configured everything in the Point of Sale configuration but the printer doesn't print. 

The hardware status page and the POS indicates that the printer is recognized, by the way the printer doesn't print.

![image](https://user-images.githubusercontent.com/35904046/40498478-6ba902ea-5f3c-11e8-8d0a-e8880bfcfc55.png)

![image](https://user-images.githubusercontent.com/35904046/40498614-bb0bd1c8-5f3c-11e8-8c7f-f5e98139306e.png)

Any idea what I'm doing wrong?

Thank you.

**Comment by pedrobaeza** [comment]
More information is needed if you want to receive help. Please check PosBox logs, and try first to print directly connected to the server without the PosBox before going the most complicated structure.

**Comment by jcguzman11** [comment]
Thanks for the reply.

I already tried printing without the POSBox and it worked fine. 
But for this particular case, I need to do the implementation using the POSbox.

This is the warning message in the log file:
WARNING ? odoo.addons.hw_escpos.controllers.main: ESC/POS Device Disconnected: Printer Not Found

**Comment by pedrobaeza** [comment]
Well, that indicates that the printer has been disconnected, but you should check logs, even in debug mode, in the exact moment when you print from PosBox.

**Comment by jcguzman11** [comment]
The log in debug indicated the same warning message. That printer is not supported by the POSBox but I read that there´s a way to add that printer model to the supported printers by changing some configurations files but I have no idea which configurations files.

**Comment by pedrobaeza** [comment]
Then if the PosBox is not oficially supported, the problem is clearly that one. The reason for not being supported will be probably this kind of problems, and then this can't be fixed right now through an issue.

Please ask on the forums about that configuration files, and if you find which is the problem, you can propose a PR for adding the support to this printer.
