### ISSUE TITLE
in mobile ,I can't delete detail.

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#24910]
Impacted versions:
in runbot.odoo.com, I create a sale order and a detail.
i want to delete detail, but i can't find the delete button.
how can i delete the detail ?
enterprise ticket: 1851433

![qq20180525-095839](https://user-images.githubusercontent.com/5398273/40522399-5ca39ac2-6003-11e8-9643-e7f3db30bbc9.png)
![qq20180525-100020](https://user-images.githubusercontent.com/5398273/40522400-605abd58-6003-11e8-8b7e-5f88924d18c1.png)

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sum1201 which version?

**Comment by sum1201** [comment]
11

**Comment by sum1201** [comment]
@Yenthe666

**Comment by sum1201** [comment]
@Yenthe666
 I think it's a bug and I didn't get a correct response at odoo.com/help. Now that the user added the detail data, it cannot delete it. Can't always go to the PC to delete it? Please help resolve this issue as soon as possible.

**Comment by Yenthe666** [comment]
@sum1201 what was the official response on the ticket?

**Comment by sum1201** [comment]
Hello,

Indeed, I have tested query with mobile layout and unfortunately, advance option like ''delete' or to attach document is not available for mobile design.

Feel free to share me screenshot if you see different problem.

Regards,

**Comment by sum1201** [comment]
@Yenthe666
 I think this is unreasonable.

**Comment by Yenthe666** [comment]
Hmm, that seems odd to me too. If you cannot delete or attach documents then what good is a mobile view for?
@mart-e could you double check this please?

**Comment by pga-odoo** [comment]
@Yenthe666  check this https://github.com/odoo/odoo/pull/15857

**Comment by Yenthe666** [comment]
@pga-odoo thanks! If I understand it correctly this will support deleting from the mobile view, right?

**Comment by Yenthe666** [comment]
Ahh nice! I see it is against master. It won't be added in stable versions?

**Comment by sum1201** [comment]
@Yenthe666 @pga-odoo 
I see that the kanban can swipe left and right, and when I slide to the left, the delete button appears. Is this better?

**Comment by sum1201** [comment]
@Yenthe666 @mart-e @pga-odoo 
Can it raise the priority of this issue? Without this feature, there is simply no way for the mobile to use it.

**Comment by Yenthe666** [comment]
@sum1201 as it is not in current versions and the PR is against master it looks like this won't land before V12 I'm afraid. Finall call is up to @pga-odoo

**Comment by sum1201** [comment]
@Yenthe666 @pga-odoo 
If it can't be solved, then the mobile terminal can only be used to view data, it cannot be used to edit and process data, and its usability will be greatly reduced. For enterprise users, they all value the mobile terminal. Otherwise, why do they not use the community version?

**Comment by Yenthe666** [comment]
@GoodERPJeff the odoo/enterprise repository is closed off for issues as all enterprise issues technically need to go through odoo.com/help. 😉

**Comment by sum1201** [comment]
@Yenthe666 
I tested the three versions 9, 10 and 11 and none of them support deletion.
I remember supporting it before. Why can't you miss it all at once?

**Comment by Yenthe666** [comment]
@sum1201 I'm sorry but that call is not for me to make. Don't forget that I do not work for Odoo and try to help on a voluntary basis. This means that I cannot make final calls on these kind of things, I can only advice and bring it under attention of the right people.
Sorry!

**Comment by sum1201** [comment]
Well, thank you very much for your help.

**Comment by pga-odoo** [comment]
@mart-e In mobile we render kanban view instead of list view. Not quite sure about this https://github.com/odoo/odoo/pull/15857 if we can do this or not  in v11

but maybe for v11 we can put remove icon in so line kanban like partner 
![screen shot 2018-06-07 at 12 07 17 pm](https://user-images.githubusercontent.com/7629089/41082294-70e56c0c-6a4b-11e8-8828-5be9124dfd2d.png)

cc @ged-odoo

**Comment by sum1201** [comment]
From the chart above I can see that the kanban view supports left and right slides. I think that when swiping to the left, if this record can be deleted, a delete button should be displayed. This is also a solution that many mobiles use.
It is hoped that the removal of details of the mobile can be resolved as soon as possible.
@mart-e

**Comment by sum1201** [comment]
cc @ged-odoo

**Comment by sum1201** [comment]
@ged-odoo 
I have seen your changes. You can see it in the Form view of one2many.
But for a single model, it can't be deleted in the mobile interface. For example, I added a quotation on the mobile phone side, I need to delete it, I still can't delete it.
You have not solved this problem perfectly.
Why not use the mobile-side common method, by sliding to the right, the delete button is displayed, delete it?

**Comment by ovnicraft** [comment]
I confirm at v10.0 with enterprise from mobile app cant delete items on one2many.

**Comment by pedrobaeza** [comment]
Yes, but this is not going to be fixed in these versions. It's already covered in v12, in both CE and EE, so I'm closing this with no possible backport.
