### ISSUE TITLE
Production order running schedulers created stock move,procurement exceptions,purchase order Expected Date error

### ISSUE THREAD

**Issue by Vegeta-D** [odoo/odoo#24913]
Impacted versions:
Odoo 10.0

Steps to reproduce:
First, create a production order and assign a date to the start date on the production order, for example June 10, 2018
Second , Run Schedulers
Third, check the generated the Scheduled Date（date_planned）on Procurement Orders, Stock Move will find errors

Current behavior:
Generated the Scheduled Date（date_planned）on Procurement Orders, Stock Move  is the current date

Expected behavior:
It should be the date after the start date（date_planned_start） on the production order was calculated

Video/Screenshot link (optional):
First
![image](https://user-images.githubusercontent.com/18547994/40538260-d39c48dc-6043-11e8-8561-b28e021e1d74.png)
Second 
![image](https://user-images.githubusercontent.com/18547994/40538693-f338c246-6044-11e8-8354-4b84ee0b619a.png)
and
![image](https://user-images.githubusercontent.com/18547994/40538738-11c51caa-6045-11e8-9172-c9e297b8199d.png)
Is wrong
Only the stock move created by the production order is correct
![image](https://user-images.githubusercontent.com/18547994/40538931-bd653b12-6045-11e8-9837-f9dcd3591acd.png)

**Comment by Vegeta-D** [comment]
The process went to this and there was a serious error. All purchase order lines are scheduled to have a wrong Scheduled Date.

**Comment by Vegeta-D** [comment]
Serious process error, please reply！@Yenthe666

**Comment by Yenthe666** [comment]
@jco-odoo or @sle-odoo could you have a look please?

**Comment by Vegeta-D** [comment]
The logic is wrong. The replenishment time should not be calculated from the current time of running the schedule. Instead, it should be scheduled from the production list.

**Comment by jco-odoo** [comment]
@Yenthe666 This is not entirely clear to me. In the code, the moves generated in the production order on creation take the date of the date_planned_start.  So, from there, everything should be fine.  If you are running orderpoints /mts, this would be normal however.

**Comment by Vegeta-D** [comment]
@jco-odoo 
Because of the re-ordering rules, after the OP order, the time of stocking is wrong.
In theory, the lead time should be pushed forward on the date of the production schedule, instead of running the schedule to get the current time back. Stock time is wrong

**Comment by jco-odoo** [comment]
When you work with reordering rules you are breaking the chain, so there is
no link between the dates before and after.  You can add a lead time on the
reordering rule itself.

**Comment by jco-odoo** [comment]
When you work with reordering rules you are breaking the chain, so there is no link between the dates before and after.  You can add a lead time on the reordering rule itself.
