### ISSUE TITLE
[9.0] Error in search an inherited many2many

### ISSUE THREAD

**Issue by mreficent** [odoo/odoo#24927]
**Impacted versions:** v9, v10, v11, ...

**Steps to reproduce:**

Declare:
```python
class A(models.Model):
	_name = 'a'


class B(models.Model):
	_name = 'b'
	a_field = fields.Many2many(a)


class C(models.Model):
	_name = 'c'
	_inherit = 'b'
```
Then, if you execute:
```python
record = self.env['c'].search([a_field, '=', 1])
```
... this `search` breaks.

**EXAMPLE:** The following breaks:
```python
 self.env["mail.compose.message"].search([('needaction_partner_ids', '=', 1)])
```

**Current behavior:**

You cannot search in an inherited model if in the domain you put a column many2many from the "parent" model.

**Expected behavior:**

The search doesn't break in the above case.

**Traceback:**
```python
    q3= self.env["mail.compose.message"].sudo().search([('needaction_partner_ids', '=', partner.id)])
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/models.py", line 1668, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/eficent/odoo/9.0/OCB/addons/mail/models/mail_message.py", line 629, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/models.py", line 4812, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/eficent/odoo/9.0/OCB/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/eficent/odoo/9.0/OCB/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "mail_compose_message_id" does not exist
LINE 1: ...ge" WHERE ("mail_compose_message"."id" in (SELECT "mail_comp...
                                                             ^
```

**Comment by mreficent** [comment]
@Yenthe666 please, add v10, v11 tags, I also confirmed the issue in those versions.

**Comment by mart-e** [comment]
Hello,

We recommend the use of the [prototype inheritance](https://www.odoo.com/documentation/11.0/reference/orm.html#inheritance-and-extension) to add features (e.g. mail.thread) but to clone a model with stored fields, there is limitations and we usually do not recommand this kind of inheritance.

@rco-odoo is this supposed to be supported?

@Yenthe666 the mail was an example but we are talking about the ORM here ;-)

**Comment by tde-banana-odoo** [comment]
Indeed this is a known limitation of the ORM. The composer example is a good example of something that should never have been done; there is an inheritance just to avoid redefining a few fields, most of them, especially 2many ones, are not used or redefined to avoid issues.

**Comment by mreficent** [comment]
More examples of breaks:
```python
self.env["mail.compose.message"].search([('starred_partner_ids', '=', 1)])
self.env["survey.mail.compose.message"].search([('needaction_partner_ids', '=', 1)])
self.env["survey.mail.compose.message"].search([('starred_partner_ids', '=', 1)])
```

**Comment by tde-banana-odoo** [comment]
Anyway those fields make no sense on the composer model.

**Comment by merdinesh89** [comment]
You can not search in this way inherited model.
But you can try below lines of code for your expected result.

message_ids = self.env["mail.message"].search([('needaction_partner_ids', 'in', 1)]).ids
self.env["mail.compose.message"].search([('message_id', 'in', message_ids)])

**Comment by rousseldenis** [comment]
I can confirm the issue.

The problem occurs on many2many fields that are declared in the base class with the relation table defined in the arguments and not on the inherited model.

So, the solution is to redeclare every many2many field with the good relation table name on inherited models (eg. mail.compose.message).

**Comment by rousseldenis** [comment]
Just tested and solution confirmed

**Comment by mreficent** [comment]
@rousseldenis  please, could you try to propose a PR with the tested solution?

**Comment by rousseldenis** [comment]
@mreficent I've tested on one model. The real solution should be modifying the Many2many class to take this into account. I'm looking into it now.

**Comment by rousseldenis** [comment]
@mreficent I've proposed a PR to fix this.

If you don't want to use it, simply redeclare fields in concerned models

**Comment by rco-odoo** [comment]
@mreficent @rousseldenis the description of the issue is not correct.
I wrote down a test case in master based on the problem statement, i.e.,
```python
class Tag(models.Model):
    _name = 'tag'

class Alpha(models.Model):
    _name = 'alpha'
    tags = fields.Many2many('tag')

class Beta(models.Model):
    _name = 'beta'
    _inherit = 'alpha'
```
The result should be the same from version 10.0 on (at least). Note that the many2many field definition does not specify values 'relation', 'column1', 'column2'. In that case, we have
```python
field = self.env['alpha']._fields['tags']
assert field.relation == 'alpha_tag_rel'
assert field.column1 == 'alpha_id'
assert field.column2 == 'tag_id'

field = self.env['beta']._fields['tags']
assert field.relation == 'beta_tag_rel'
assert field.column1 == 'beta_id'
assert field.column2 == 'tag_id'
```
This case is correct: each model has its own table for the field `tags`.

Now things are indeed getting messy if you define the field as
```python
    tags = fields.Many2many('tag', 'alpha_tag_rel', 'alpha_id', 'tag_id')
```
The field `tags` in model `beta` uses the exact same table and columns, *as it is expected to*. But now all operations on `tags` in `beta` are confused because the table uses a foreign key to model `alpha`, and is not expected to store identifiers from `beta`. This is a **programming error** that is not caught by the ORM.

I have an idea to detect this situation. Give me a few hours, and I might get a simple and efficient fix.

**Comment by mreficent** [comment]
Good for the news. Sorry my description was not fully correct.

**Comment by rco-odoo** [comment]
@mreficent @rousseldenis I have a working solution, simple and efficient.
But I had to fix/work around some code of ours that is broken.  That's why it took longer than I expected.
The pull requests should come soon.

**Comment by rco-odoo** [comment]
Dear all, we decided to not introduce such a check on stable versions.
However, a proper error will be raised on versions > 12.0 (#29323).

**Comment by Yenthe666** [comment]
@rco-odoo I'm happy to see you found a fix. Couldn't we introduce it into 12.0 though? V12 is not out very long and I'd assume that the amount of people being in production on V12 is small?

**Comment by mreficent** [comment]
I suppose that this can be closed as all the related PRs are merged/closed :)

Thanks @rco-odoo
