### ISSUE TITLE
Can't filter on some fields in invoice report

### ISSUE THREAD

**Issue by fgeorgeanybox** [odoo/odoo#24924]
Impacted versions: V9, V10

Steps to reproduce: Go to Accounting > Reports > Business intelligence > Invoices, then try to add a custom filter on 'Total Without Tax'. The results are quite hazardous and not always acurate nor comprehensive.

Current behavior: The results are not the one expected by the filter.

Expected behavior: The results are accurate based on the defined filter.

Video/Screenshot link (optional):
![capture d ecran_2018-05-25_16-55-58](https://user-images.githubusercontent.com/36856705/40551203-9721bfb0-603c-11e8-8893-8343659ba4e1.png)
![capture d ecran_2018-05-25_16-56-18](https://user-images.githubusercontent.com/36856705/40551204-9752d79e-603c-11e8-9fb9-c84f18b31a5b.png)

**Comment by Yenthe666** [comment]
Dear @fgeorgeanybox

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
