### ISSUE TITLE
Method _barcodeScanned is called twice when user open picking form from purchase order form and scan a barcode

### ISSUE THREAD

**Issue by FaTaToo** [odoo/odoo#24929]
Impacted versions: Odoo 11

Steps to reproduce:
- Step 1: Create a Purchase Order (PO) and buy some product and confirm that PO.
- Step 2: In PO form, click on button `Receive Products` to open Picking form.
- Step 3: Scan a barcode.

Current behavior:
Method `_barcodeScanned` ([link](https://github.com/odoo/odoo/blob/11.0/addons/barcodes/static/src/js/barcode_form_view.js#L279)) is called twice.
Expected behavior:
Method `_barcodeScanned` should be called only once.
Video/Screenshot link (optional):

**Comment by FaTaToo** [comment]
I think function `_barcodeStartListening` should be called in function `on_attach_callback`  instead of inside function `init` currently. Then, we should call function `_barcodeStopListening` inside function `on_detach_callback`.

**Comment by pedrobaeza** [comment]
Why do you think is incorrect to be called twice? Why don't you propose a PR with your patch?

**Comment by sle-odoo** [comment]
Closing since  it seems everything works as expected.
Regards
