### ISSUE TITLE
CRM : send notificaion email when an activity has created within opportunity

### ISSUE THREAD

**Issue by rs430** [odoo/odoo#24932]
Impacted versions: 11.0

Steps to reproduce: CRM notification email

Current behavior: When activity has created within opportunity the systeme dones not send email notif

Expected behavior: send notificaion email when an activity has created within opportunity

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, @rs430 what you are requesting is a new feature, not an issue.
