### ISSUE TITLE
mrp: Manufacturing Order and MO workorder generation and other things very slow

### ISSUE THREAD

**Issue by leio** [odoo/odoo#24934]
Impacted versions:
10.0

Steps to reproduce:
Create MO Workorders

Current behavior:
Creating workorders for a MO with a routing with 7 operations takes 14-15 seconds

Expected behavior:
It takes less than 1 second

**Comment by leio** [comment]
stock.move production_id AND raw_material_production_id are missing index=True in v10.
Adding them in a custom module reduces mrp.production _generate_workorders runtime from ~13.15 seconds to ~5.1 seconds.
The save is mostly from `moves_raw = self.move_raw_ids.filtered(lambda move: move.operation_id == operation)` and `moves_finished = self.move_finished_ids.filtered(lambda move: move.operation_id == operation)` with indexes now taking about 0.04s and 0.005s respectively thanks to the indexes instead of 0.56s and 0.52s without indexes. This is over a second saved PER routing operation.
I suspect lots of performance improvement in other mrp module methods as well from this, but this was a nicely measurable place to start fixing the abysmal MRP performance.

This is an issue instead of PR because I have not and will not sign the CLA.

**Comment by Yenthe666** [comment]
Dear @leio,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Comment by leio** [comment]
Literally the last comment that no-one bothered to respond to (after commenting it the SAME DAY as a wrong 10.0 limiting tag was addded) stated that 11.0 has the same issue. And as far as I can see, the issue persists on 13 - there are no indexes on these fields still, at least not from mrp module. That said, I'm not sure how much it affects performance in 13.0.

**Comment by sle-odoo** [comment]
In version 13, there aren't any noticeable delays when planning an mo with a routing of 7 operations.
