### ISSUE TITLE
qty_delivered is set to 4,130 instead of 33 when I track 

### ISSUE THREAD

**Issue by zem** [odoo/odoo#24949]
Impacted versions: 

Odoo Community Edition 11  
11.0.20180512

Steps to reproduce:

Create a new Timebased Service Product in Timetracking (set unit of measurement to hours because it is time) 
Create a new SalesOrder using that Timebased Service 
Create a new Project to be Tracked by that Order 

Current behavior:

If I track 33:00 hours on the project, qty_delivered only shows a completely different value of 4.130 hours. 

Expected behavior:

If I track a number of hours it should show the same number in the delivered qty field in the sales order. 

Workaround: 

If I count the Timebased Service Product in  Units instead of Hours qty_delivered is set as it should be.   

Though this is not the Expected behavior because I tend to count products like "Programming" in hours this will work for me, but it should be fixed.

**Comment by pedrobaeza** [comment]
This seems something with the UoM defined on the timesheet product. Have you reproduce this problem on runbot (http://runbot.odoo.com/runbot)?

**Comment by zem** [comment]
It seems that we did mess up with the base Unit settings. There was an extra "workhours" unit there which was not in the base units but which was a reference unit.
