### ISSUE TITLE
[11.0] wrong data/datetime format in export

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#24950]
Impacted versions:11

Steps to reproduce: Export any Date or Datetime field

Current behavior: When exporting records from database, fields of time date and datetime are exported in en_US Format.

Expected behavior:When exporting records from database, fields of time date and datetime are exported in language Format of exporting user.

**Comment by pedrobaeza** [comment]
Dates are exported in a neutral form for possible future imports to get the same format, or on the contrary you will need to specify also the date format you are importing in each field, so this gets complicated without reason. You can open the file any way in Excel, Calc or any other spreedsheet and format the date easily.

Closing as no real bug.
