### ISSUE TITLE
 paypal_acquirer_button

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#2496]
paypal_button the key is not correctly displayed. is not visible and even clickable

**Comment by NaviDeck-fdim** [comment]
The button is only displayed after you send the quote (in my case) and try resending it.

**Comment by Yenthe666** [comment]
Hi @roccocesetti ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
