### ISSUE TITLE
Changes are saved when clicking Discard on website settings

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#24972]
Impacted versions:
- 11.0

Steps to reproduce:
- Go to Website -> Configuration -> Settings
- Modify any field, e.g. the website's name.
- Click on "Discard"

Current behavior:
Changes are saved, as if the button "Save" had been clicked.

Expected behavior:
Changes should not be saved

Video/Screenshot link (optional):

**Comment by luisg123v** [comment]
opw-1853230

CC @yaniaular  & @tomeyro

**Comment by Yenthe666** [comment]
Hi @luisg123v,

Thanks for the bug report. I've just tested this and it is indeed a bug, confirmed.
The issue will be handled through the OPW

Regards,
Yenthe

**Comment by luisg123v** [comment]
Thanks @Yenthe666, I'll be following any news on this.

**Comment by Yenthe666** [comment]
@luisg123v it has been fixed in https://github.com/odoo/odoo/commit/a1d5f32296fb49f1293354ad8da2ba338f100252 😄

**Comment by luisg123v** [comment]
Thanks @Yenthe666  & @kebeclibre 

This issue is indeed solved now.
