### ISSUE TITLE
multi company creating an invoice 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#24979]
```
No se ha podido completar la operación por restricciones de seguridad. Contacte con su administrador del sistema.

(Tipo de documento: crm.team, Operación: read)
```

this error pops only for one company but no other, why ?

**Comment by pedrobaeza** [comment]
You have to fix your sales team configuration and default team configuration, as there's one team that belongs to the first company that is being taken for the second company.

Any way, it's not an Odoo issue, but misconfiguration, so I close.

**Comment by icf20** [comment]
@pedrobaeza gracias boy this need a large documentation
