### ISSUE TITLE
[Wishlist] Website Product Attributes Filter Collapsible

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#24987]
Impacted versions: 11

Steps to reproduce: Create a product with attributes, Install module "website", go to the product page
Tick to turn on "Product Attribute FiIlter"
Current behavior: Doesn't have option "Collapsible"

Expected behavior: Have a Collapsible option for attribute filter like the one in category list

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a feature request, not an issue.

@JKE-be is there any plan for doing this?

**Comment by JKE-be** [comment]
Hello, it is not a priority for now, but I ping the product owner to let a feedback. //cc @fgi-odoo 

Thanks for the suggestion
