### ISSUE TITLE
[11.0] Cannot update a local modules

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#24993]
Clicking Updates displays the following error message:
![image](https://user-images.githubusercontent.com/5981417/40778716-7ca3c828-64d2-11e8-8c96-eeb1d79ff51e.png)

**Comment by Yenthe666** [comment]
Hi @satriani-vai,

This is by design. Odoo has disabled online apps due to security. It was unsafe to directly show, download and deploy apps from the app store. That is why you can only see/use local available modules.
In the new version & updates this is also removed i believe.

Regards,
Yenthe

**Comment by satriani-vai** [comment]
How now to see for which modules updates are available and update them?

**Comment by Yenthe666** [comment]
from apps > Updates (needs developer mode)
![image](https://user-images.githubusercontent.com/6352350/40842545-86928cf2-65ae-11e8-91a8-41baa4e50f5d.png)

**Comment by satriani-vai** [comment]
In Chrome/Chromium
![peek 2018-06-01 16-09](https://user-images.githubusercontent.com/5981417/40845249-7070f942-65b6-11e8-8a06-737cb3aa865a.gif)
and this is in Firefox
![peek 2018-06-01 16-13](https://user-images.githubusercontent.com/5981417/40845375-ccf00532-65b6-11e8-85b1-2f5cbe27b80b.gif)
