### ISSUE TITLE
How to add ''day'' in the date on pivot table？

### ISSUE THREAD

**Issue by Wolfnight233** [odoo/odoo#24992]
Impacted versions: Odoo 10.0

Steps to reproduce: Add a day classification on pivot table

Current behavior: Now the dates are classified only by Month by default

Expected behavior: Classfy the dates on day

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/35833382/40777387-00fcc46c-64ce-11e8-9d54-f0d71049493c.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

A quick tip: you have to add `:day` on the group by context.

Closing this by the reason above.
