### ISSUE TITLE
POSBOX: Cannot print in arabic

### ISSUE THREAD

**Issue by hassans2020** [odoo/odoo#25007]
Impacted versions: 9.0

Steps to reproduce: Write any header or footer of receipt in arabic

Current behavior: Empty characters

Expected behavior: Posbox doesn't support arabic

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't think this is a problem of PosBox, but the printer language itself. Have you tried to print the same header with the printer connected to the server directly?

**Comment by pedrobaeza** [comment]
But the print is done through ESC/POS protocol?

**Comment by hassans2020** [comment]
The print is done and print everything except Arabic characters.

**Comment by pedrobaeza** [comment]
You haven't answered my question.

@pimodoo who is the responsible of PosBox? I think PosBox prints through ESC/POS protocol, isn't it?

**Comment by hassans2020** [comment]
Yes, it is through ESC/POS

**Comment by pedrobaeza** [comment]
You can see here that printing Arabic through ESC/POS is not direct: https://stackoverflow.com/questions/38683686/print-arabic-words-from-python-to-esc-pos-printer

**Comment by lem8r** [comment]
Worth trying this fix https://github.com/odoo/odoo/pull/19757
It improves selection of proper character encoding for ESC/POS.

**Comment by antonylesuisse** [comment]
We dont plan to support arabic, japanese, chinese and korean using esc-pos. We will switch to a pdf/bitmap version of the driver, thus rendering the fonts ourselves after v12. The problem with that approach is that it's slower both on rpi and on the epson printer (you can try it under windows or with cups).
