### ISSUE TITLE
[IMP] it's not user-friendly to reload all the data after going back to the list/kanban view by clicking the breadcrumb link

### ISSUE THREAD

**Issue by duanyp1991** [odoo/odoo#25009]
Impacted versions:
---
All odoo versions (9.0,10.0,11.0)

Steps to reproduce:
---
Starting with a Product kanban or list view, enter any product form view and click the breadcrumb link to go back to list/kanban view.

Current behavior: 
---
The framework reload all the data again which might be quite slow and not user-friendly.

Expected behavior: 
---
The framework uses the cached data and only reload when user click "refresh/reload" button or certain operations which triggers the reloading ;

Video/Screenshot link (optional):
---

**Comment by pedrobaeza** [comment]
Sorry, but this is technically not possible and not desirable some times, as this will increase the memory use and not refresh data back data that can be needed to be refreshed. Any way, there has been advances on v11 and future v12 for preserving some things like expanded groups, scroll position and so on for making better the user experience without losing the refreshing part, and there's a continuous feedback on this matter on the usability team.

Closing as this is as "won't fix" as general, although if you have a more concrete action to propose, please do it through a new issue.

**Comment by duanyp1991** [comment]
Hi @pedrobaeza , 

Thanks very much for your reply. I think the design principle should be: **refresh when necessary**; Most of the cases, user goes back and forth from list view to form view just for information . it would be terrible experience when he/she goes back to list and system reload everything .

For your concern about memory usage: we can always control the size of the cache data;

Best regards,
Alex
