### ISSUE TITLE
[11.0] Cannot update modules in Chrome

### ISSUE THREAD

**Issue by satriani-vai** [odoo/odoo#25018]
This issue relates to this issue: https://github.com/odoo/odoo/issues/24993
It is very curious. Everything works wonderfully in Firefox. That issue I have in Chrome / Chromium. Clearing cache and deleting cookies did not help. Does somebody has any idea?

Take a look to the https://github.com/odoo/odoo/issues/24993#issuecomment-393893802

**Comment by Yenthe666** [comment]
@satriani-vai which chrome version do you have?

**Comment by satriani-vai** [comment]
I found the culprit. It was a Privacy Badger :laughing:
