### ISSUE TITLE
[11.0] Reconciliation Model Button independent of journal_id

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#25038]
Impacted versions: 11

Steps to reproduce: Create some reconciliation_model records with and without journal_id. 

Current behavior: In bank reconciliation view, you will see all reconciliation_model(Buttons) independent of journal_id .

Expected behavior: In bank reconciliation view, you should see all reconciliation_model(Buttons) dependent of journal_id .

You can easily fix that with adding:
```

                domain: ['|', ['journal_id', '=', context.active_id], ['journal_id', '=', false]],
```
to line:
https://github.com/odoo/odoo/blob/11.0/addons/account/static/src/js/reconciliation/reconciliation_model.js#L383

**Comment by Yenthe666** [comment]
@qdp-odoo can you have a look at the suggested fix? If you'd like we can make the PR for you.

**Comment by qdp-odoo** [comment]
mmh wait... this is not what this field is intended for (although I totally understand the confusion): that field is used when you are in the payment-invoice matching widget (and only there), creating a writeoff entry by pushing the reconciliation model button. This writeoff is a new entry, that will be created in the selected journal (that's the default value).

So changing the semantic of the field might be a good idea, but it was not planned and thus cannot be interpreted as a bug... and I feel there's more to do (usability, help tooltip... than just adding a domain).

We'll see what we can do in master, though.
