### ISSUE TITLE
Fixed string "Tax XX%" in the printed invoice pdf or html

### ISSUE THREAD

**Issue by ywiyogo** [odoo/odoo#25034]
Impacted versions:11

Steps to reproduce:
1. Open a non-english database
2. Go to accounting -> and open any outgoing invoice or create a new outgoing invoice
3. Click print (pdf or html)

Current behavior:
The line between subtotal and total contains "Tax XX% ..." which does not translated correctly.
I tested in two different languages.

Expected behavior:
The word "Tax" shall be translated to the local language.
For example, in the German translation file `de.po` I can find this translation:

    msgid "Tax %.2f%%"
    msgstr "Steuer %.2f%%"

Video/Screenshot link (optional):
1. https://drive.google.com/file/d/1wovG9TQXHc5S9-cgbt1vxDaCFfH-Fm0b/view?usp=sharing
2. https://drive.google.com/file/d/1yf5odc_iyKEcq2_FpbXzTIb_kXeJEvVR/view?usp=sharing

**Comment by mart-e** [comment]
Hello,

You are referring to the "Tax:" on the invoice report? Then it is not the translation of `Tax %.2f%%`, that is python code.
What you are talking about is from this part, it is actually the tax name:
https://github.com/odoo/odoo/blob/579f67166a25bd3b072edf92c24df99b3568eaf7/addons/account/views/report_invoice.xml#L116-L117

Please clarify what is not translatable

**Comment by ywiyogo** [comment]
Hi @mart-e, 

yes, you are right that is the "Tax:" on the invoice report. Thanks for the hint. I can at least manually edit the xml file. 
Is the translation missing? If not why it does not translated?

**Comment by pedrobaeza** [comment]
@ywiyogo, as said by Martin, it's the tax name what contains the text "Tax", so edit its name (or translation), and you will have it correctly. 

Closing as no real issue.

**Comment by satriani-vai** [comment]
It does not work for me
![image](https://user-images.githubusercontent.com/5981417/44244400-127b2880-a1d4-11e8-9a89-7433c6d28fd0.png)

**Comment by pedrobaeza** [comment]
@satriani-vai you are not looking for the proper term (`Tax`, not `account.tax.group`).

**Comment by Perino01** [comment]
Pedro, it is still an issue, which should be fixed!!
But thanks for the hint to make this work around.

**Comment by pedrobaeza** [comment]
It's not an issue. It's the way you should handle it, through translations:

https://github.com/odoo/odoo/blob/750e70e0a12c11d50998a44dff447f07fd7d06c3/addons/account/i18n/account.pot#L8635-L8636

If you want this to be permanent, go to Transifex, volunteer for translating your language, and put the translation there. Overwriting the translations on your DB of for new DBs, then you will have the proper translation once the transfer from Transifex will be done (once a week on weekends).

**Comment by Perino01** [comment]
Sorry, I don't understand this. The whole report is correct translated by the system, with one exception of a single term on one specific position. As mentioned, the translation for this term is already in the system....

**Comment by pedrobaeza** [comment]
Please check again, as it should work that way.

**Comment by pedrobaeza** [comment]
Try to synchronize terms also.

**Comment by Perino01** [comment]
In the view of the order/proposal the term "Tax" is correct translated to the german translation "Steuern". In the printed version, this term on this position won't be translated.

What do you mean with synchronize terms? How can I do that?
By the way, I'm testing this also on a complete fresh system with the latest build of Odoo => same Issue!

**Comment by mart-e** [comment]
As said before, this is not the term "Tax" but it is the name of a tax group.
If you have a German chart of account, the created tax groups will be something like "USt 0%"

![screenshot from 2018-08-17 08-39-38](https://user-images.githubusercontent.com/564822/44251570-238a6080-a1f9-11e8-82ad-3bec950fd33d.png)

If you have a different chart of account but still want to translate the tax group to a different language, go to your tax configuration, access the group through the **Tax Group** field

![screenshot_2018-08-17 19 umsatzsteuer - odoo](https://user-images.githubusercontent.com/564822/44251691-972c6d80-a1f9-11e8-9747-37205a1a20f8.png)

and set a translation
![screenshot_2018-08-17 translate - odoo](https://user-images.githubusercontent.com/564822/44251766-ed011580-a1f9-11e8-9323-7c39d08a5c61.png)

If your customer is in a different language, the group will be translated
![screenshot from 2018-08-17 08-42-09](https://user-images.githubusercontent.com/564822/44251736-c5aa4880-a1f9-11e8-9f6c-9b4a58459b83.png)

**Comment by pedrobaeza** [comment]
Thanks for the clarification, Martin, and sorry for the confusion.

@Perino01 then tax group should be.

**Comment by Perino01** [comment]
Do you mean this form? I've changed therefore the language to english....

![grafik](https://user-images.githubusercontent.com/29162103/44252601-fa6bcf00-a1fc-11e8-881c-99afc97c130d.png)

**Comment by Perino01** [comment]
Very good! Thanks to Martin & Pedro!
