### ISSUE TITLE
Odoo picks up the latest price when calculating COGS instead of following FIFO rule

### ISSUE THREAD

**Issue by passion342** [odoo/odoo#25053]
Impacted versions: 11 EE

**Steps to reproduce:**

1- Activate FIFO Pricing along with Automated Inventory Valuation on a Product Category, say, Real Pricing
2- Create a product 'Product 1' and assign it to product category Real Pricing
3- Buy 10 units of 'Product 1' @ $500 each => Valuation: $5000. Buy another 10 units of Product 1 @ $500 each => Valuation: $5000. Buy another 20 units @ $700 => Valuation: $14000
4- Sell 25 units @ $1000 each.

**Current behavior:**
When selling 25 units, the stock journal entries get correctly created i.e.

20 units @ $500 each => $10,000

5 units @ $700 each => $3,500

Total Value => $13,500

When I created and validate invoice, the system incorrectly debits and credits the COGS and Goods Issued Not Invoiced accounts. Insetad of debiting COGS by $13,500, it debits it by $17,500. What it really does is, takes the latest cost price of $700 and multiplies it by 25 units i.e. 17,500.

COGS $17,500 dr

Goods Issued Not Invoiced $17,500

![perpetual inventory scenario](https://user-images.githubusercontent.com/28576333/40934416-2c46b974-684e-11e8-9685-627203a0b0c0.png)

**Expected behavior:**
The journal entry should be like this:

COGS $13,500 dr

Goods Issued Not Invoiced $13,500

**Video/Screenshot link (optional):**
You can see all the journal entries, sales and purchases on the following account:

URL: https://passion342-real-time-inventory-test.odoo.com
Email: admin
Password: admin

I have also created a video: https://youtu.be/CBGn3_JIqm4

I had a developer look at it and he said the following:

We trace the code of stock accounting where we found that in _prepare_account_move_line - according to this method it takes latest cost price of product ( which is 700 ) and multiply with the requested qty of product ( which is 25 ) and as a result we are getting total amount 17500 .

This method is given under addons/stock_account/models/stock.py file .

**Comment by sle-odoo** [comment]
Real price doesn't exist anymore in v11, i think you're talking about financial fifo. To fix your issue, please set the product's invoice policy as "delivered quantity", then the price will be taken on the moves.

Regards

**Comment by passion342** [comment]
Thank you @sle-odoo. I could have never figured that out. I am wondering what the difference is between FIFO and real Pricing.
