### ISSUE TITLE
Progressive Web App Support Back End

### ISSUE THREAD

**Issue by emanjuGbr** [odoo/odoo#25087]
Dear all,

I am wondering if an when the back end theme is supporting progressive web apps.
This would almost eliminate the need of a mobile app. 

Also I am wondering at which modules / parts this would need to be implemented?
Would this be part of Community or of Enterprise since Enterprise UI is different anyways?

Could you please give me some insights and also help me out understanding how this would affect Community & Enterprise or if it must be developed within Community anyways because it relys on some core modules?

Really appreciate your insight!
Thanks in advance!

**Comment by pedrobaeza** [comment]
@emanjuGbr In odoo core you only have an enterprise module for backend responsive interface called web_enterprise. On community, I already pointed you the web_responsive module in the other issue.

Anything more you want to ask, please do it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
