### ISSUE TITLE
template never used

### ISSUE THREAD

**Issue by xunonxyz** [odoo/odoo#25082]
Impacted versions:
11.0
Steps to reproduce:

Current behavior:
<t t-name="SearchView.field"> never used, could someone tell me how it is used?
Expected behavior:
remove it ?

**Comment by xunonxyz** [comment]
also the 'web.search_inputs' use it, but the widget never render

**Comment by pedrobaeza** [comment]
Can you specify which template are you talking about?

**Comment by xunonxyz** [comment]
so sorry, i  like "SearchView.field"

**Comment by pedrobaeza** [comment]
I still don't understand what are you talking about. If you have a specific proposal, please make a PR.

**Comment by xunonxyz** [comment]
the "SearchView.field" (in base.xml) template is never used.  i do not understand why the widget of "web.search_inputs" need a template.

**Comment by pedrobaeza** [comment]
OK, closing then this meanwhile.
