### ISSUE TITLE
[11.0] Purchase Orders created with order_dates in the past.

### ISSUE THREAD

**Issue by KasperDeclercq** [odoo/odoo#25097]
Impacted versions: 11.0

Steps to reproduce:

1) Activate Dropshipping
2) - Create a product which uses dropshipping. 
    - Add a vendor with delivery leadtime 1 day
3) Create sale order + confirm the order

Current behavior:
Purchase order is created with order_date = yesterday. 

Expected behavior:
Purchase order should be created with the order_date = today
You can't create an order in the past. 

Video/Screenshot link (optional):
![po](https://user-images.githubusercontent.com/24540328/41035212-3f31639c-698c-11e8-9f38-8d75745c78ca.PNG)
![so](https://user-images.githubusercontent.com/24540328/41035213-3f4dd702-698c-11e8-9234-0690393ee8d1.PNG)

![vendor](https://user-images.githubusercontent.com/24540328/41035288-7bc62db0-698c-11e8-9b50-1d5303ec6159.png)

**Comment by jco-odoo** [comment]
It has always been possible to create orders in the past.  It alerts the user some things are late.
