### ISSUE TITLE
[11.0] Field name required in timesheet, but allows you to leave it null.

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#25092]
In module analytic, in line:

https://github.com/odoo/odoo/blob/10da9045a6c63468736b6a678356058c95d43219/addons/analytic/models/analytic_account.py#L100

The field is required, but allow you leave it null.

![imagen](https://user-images.githubusercontent.com/13520529/41036797-84d7f550-6991-11e8-834f-32aa593e1e30.png)

In first record, field description is empty.

**Comment by igallart** [comment]
In timesheet main module also.

**Comment by mreficent** [comment]
I think you should provide an image or something. It's not clear in what view you are facing the problem.

**Comment by mreficent** [comment]
That's Odoo Enterprise v11.

**Comment by igallart** [comment]
> That's Odoo Enterprise v11.
Yes, is Enterprise

**Comment by pedrobaeza** [comment]
Is it the problem also on community version?

**Comment by igallart** [comment]
In comunity it works fine.

**Comment by pedrobaeza** [comment]
Then please put an OPW ticket at https://www.odoo.com/help, as this is something specific of enterprise version, which doesn't belong to this repository.

Closing the issue by the reason above.

**Comment by rim-odoo** [comment]
Hello

This does not look to be a bug.
If `timesheet_grid` is installed, the `name` of the `account.analytic.line` is not required anymore.
https://github.com/odoo/enterprise/blob/11.0/timesheet_grid/models/models.py#L16

Regards

(cc @jem-odoo )

**Comment by jem-odoo** [comment]
Hi,
Unfortunately, this is not fixable in a stable version, as it impacts SQL constraint (and so, modify the SQL table schema). But this is fixed in master at https://github.com/odoo/enterprise/commit/272eb08bb600d17013dcba140a84d8145b50b212.
It will be available in 12.0.
Regards
