### ISSUE TITLE
[11] Uninstalling app does not remove related translations

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25105]
Impacted versions: 11

Tested On Runbot [(http://334967-11-0-partner-event-rights-lpe-087dd8.runbot14.odoo.com/web?reload#view_type=kanban&model=ir.module.module&menu_id=45&action=31)](http://334967-11-0-partner-event-rights-lpe-087dd8.runbot14.odoo.com/web?reload#view_type=kanban&model=ir.module.module&menu_id=45&action=31) with Project module

Steps to reproduce: Uninstall App 

Current behavior: Translated Terms related to module are not deleted

![](https://image.prntscr.com/image/V2wYmsqWRX2fz42-G-eOHQ.png)

Expected behavior: Should be deleted

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Are you sure this is unintended behavior? I tried with other apps (accounting, sales) and the translated terms are never deleted.

Furthermore, does this cause any real issues? i.e. bad translations or something of the sort? If not, I don't think the dev time would be worth the reward of fixing this.

Perhaps @mart-e can shed some light on this issue

**Comment by mart-e** [comment]
I guess we could, when deleting a record, delete its translations as well. We already [do it](https://github.com/odoo/odoo/blob/2c91f37e387ecd0dd9acd45b3af4e13e47950f92/odoo/models.py#L2957-L2961) for the attachments.
I don't see any reason to keep it but it is not a problem either to keep it, it is an improvement to remove old records in the database.

**Comment by sswapnesh** [comment]
Can we do this for master?

**Comment by sswapnesh** [comment]
Fixed in master (v13) at https://github.com/odoo/odoo/commit/ba58888ced44ea96374581a0f543bcc28afc130a

**Comment by MohsenWaleed** [comment]
@sswapnesh Thanks for raising this issue. I'm facing this issue in Odoo 11. Is that commit applied to 11 as well.

**Comment by sswapnesh** [comment]
Fix is not applied  in v11.
It has been fixed master and v12 at https://github.com/odoo/odoo/pull/32056

**Comment by MohsenWaleed** [comment]
@sswapnesh thanks for reply, what about v11?

**Comment by MohsenWaleed** [comment]
@sswapnesh thanks for reply, what about v11?  The issue which I'm getting now if I uninstalled any custom app and then install it again (Module not have a translation PO file for my Language) and tried to Generate Missing Terms it will not create anything and I have to delete the orphan translation to be able to generate missing terms for this custom module.

**Comment by sswapnesh** [comment]
Maybe @mart-e  can answer this.

**Comment by mart-e** [comment]
In 12.0 we could reproduce with a traceback, it is a bit risky to backport 112bd835d80619a0337dca10b21aa6ca68e3303d in previous versions if you don't have a blocking issue
