### ISSUE TITLE
editable="bottom": Nos show overflow: auto

### ISSUE THREAD

**Issue by adrianlaraperez88** [odoo/odoo#25117]
Impacted versions:
Odoo 11
Steps to reproduce:
 view type tree and editable="bottom" fields
`<record id="ed_product_tree_view" model="ir.ui.view"> <field name="name">ed.product.tree.view</field> <field name="model">product.product</field> <field name="arch" type="xml"> <tree string="Product" editable="bottom" create="false" edit="false" delete="false"> <field name="request_product_qty"/> <field name="is_user_manager" invisible="1"/> </tree> </field> </record>`

No show overflow:scroll in device size.

![example](https://user-images.githubusercontent.com/19626181/41080206-569f7750-69f3-11e8-8e47-c99c75cd3f79.png)

**Comment by pedrobaeza** [comment]
@adrianlaraperez88 you are using a custom backend theme, so this is not applicable here, but on the custom theme repository. Closing this.

**Comment by adrianlaraperez88** [comment]
Sorry I was try in default view in odoo 11 and exist the same problem, only
use the backen theme in the picture

**Comment by adrianlaraperez88** [comment]
@pedrobaeza picture
![screenshot from 2018-06-07 07-24-19](https://user-images.githubusercontent.com/19626181/41096912-2a7a3f9e-6a24-11e8-88aa-f59255050609.png)

**Comment by adrianlaraperez88** [comment]
Picture not web_responsive OCA addons
![screenshot from 2018-06-07 07-29-48](https://user-images.githubusercontent.com/19626181/41097039-a9d33d9a-6a24-11e8-8884-9a25ffd83d00.png)

**Comment by pedrobaeza** [comment]
Yeah, but the problem there is a very low resolution + the normal web module not adapted to mobiles. And please don't spam multiple places (OCA + here).

**Comment by adrianlaraperez88** [comment]
for what do you closed the ticket in two places, no is issued ,this problem
only view when use editable top or button in view tree

**Comment by pedrobaeza** [comment]
I close it because it doesn't belong here, as the community interface is not responsive and answering in 2 places is not the good option. I close it in the other place due to the reasons stated there.

**Comment by adrianlaraperez88** [comment]
Ok thanks
