### ISSUE TITLE
Archiving project does not archive issues

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#25112]
## Impacted versions: 
11.0

## Steps to reproduce:

1. Go to a project form view.
2. Create related tasks
3. Create related tickets
4. Click on the Archive button and then Ok

## Current behavior:

A confirmation message is showed:

> (Un)archiving a project automatically (un)archives its tasks and issues. Do you want to proceed?

![image](https://user-images.githubusercontent.com/7593953/41058456-3e286180-69a0-11e8-8f64-1c08c82b759e.png)

## Expected behavior:

It does archive the tasks but there is not issues to archive, issues does not exist in this odoo version. The message should be:

> (Un)archiving a project automatically (un)archives its tasks. Do you want to proceed?

If this is True here is the related PR https://github.com/odoo/odoo/pull/25111 with the change already 

In order hand, if you mean here "ticket" instead of issue, there is not logic attach that  a archive tickets related to a project. Here is a [video](https://youtu.be/9GOM68D9K_s) showing that the related tickets were not archived.

Best Regards

**Comment by zaoral** [comment]
FYI opw 1856325

**Comment by qsm-odoo** [comment]
Fixed in master to not break translations (see https://github.com/odoo/odoo/pull/25111)

**Comment by zaoral** [comment]
Thanks to you @qsm-odoo  
Best Regards
