### ISSUE TITLE
[11.0] ABA/Rounting Wrong value when saving: system is not saving left zeroes

### ISSUE THREAD

**Issue by pmartineznetquest** [odoo/odoo#25124]
Impacted versions: [11.0]

Steps to reproduce: 
- Install the l10n_us localization (wich makes appear the ABA/Rounting field in model and views)
- Go to any partner. 
- Access to the Sales & Purchases tab.
- Click on Bank accounts link on Purchase section. 
- Click on Create button to create a new bank account linked to the parner. 
- Fill the required fields. Fill the ABA/Rounting field with 000011111 value. 
- Save the record. 

Current behavior:
- The value stored is 11111, and is not correct. The system saves the record this way because the field type is an integer. 

Expected behavior:
- The value stored must be 000011111

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I confirm this is indeed a bug.

@qdp-odoo this should be a char of size  9.

However, I'm afraid this change can't be put in stable due to stability policy, unless considered critical.

**Comment by qdp-odoo** [comment]
already fixed by https://github.com/odoo/odoo/commit/a824b912

**Comment by pedrobaeza** [comment]
Thanks

**Comment by pmartineznetquest** [comment]
Thanks for the answer and the fix. 
I see that the change is in the _master_ branch, not in the _11.0_. Is it going to be merged into the 11.0?
Thanks, 
Pere

**Comment by qdp-odoo** [comment]
I'd suggest to make a ticket on our support platform to see if some kind of backport is acceptable
