### ISSUE TITLE
[11.0] E-Mail Model unclear

### ISSUE THREAD

**Issue by DR4RCON** [odoo/odoo#25125]
Impacted versions: 11

Steps to reproduce: Configure your mailsystem (SMTP/IMAP). Send and Receive E-Mails.

Current behavior: You will not find any email in mail.mail (Settings->E-Mail).  In Settings->E-Mail you will have only outgoing failed mails, when they are send correctly, the mail.mail views are empty. You have filter for Mails = Received, Sent, Failed and Outgoing, but when using any filter, no mails are shown.

Expected behavior: Using the filter in mail.mail, will show dependent mails.

Possible I do something wrong or I miss a configuration, but mail system works, but without that options to control it. I cant find any documentation for that mail.mail model and its unclear how to handle. Please can you explain?

Further more, the Incoming IMAP configuration shows everytime 0 records, but a lot are fetched, why it says 0 records?

**Comment by janbec** [comment]
No, you did not. I stumbled across that as well. The filters work as expected according to odoo. In order to increase system performance, only undeliverables are stored. If you change the auto-delete to false, you will see emails in 'sent'. However, this only applies to templates.

**Comment by sswapnesh** [comment]
@janbec  Even If you set` Auto Delete` False Emails are not Stored as mentioned in #25072

**Comment by janbec** [comment]
@sswapnesh I cannot confirm the behavior described in #25072 
I just tested on our v10e production and if auto-delete is set to false, mails sent using templates are stored in e-mail list.

**Comment by pedrobaeza** [comment]
Closing as no issue as explained in https://github.com/odoo/odoo/issues/25072#issuecomment-394791538
