### ISSUE TITLE
Pager is hidden when using a group by

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#2512]
Impacted versions:

 - 7.0 and above, functional regression introduced by revision https://github.com/odoo/odoo/commit/30ac724

Steps to reproduce:

 1) Open a view with many records, for instance the delivery orders
 2) Group them by state or another group by
 
Current behavior:

 - The pager allowing to choose the number of records is hidden

Expected behavior:

 - The pager allowing to choose the number of records is shown

Why is this behavior expected? 

To explain, I will continue my use case, say that I have 800 delivery orders  with state 'assigned' and I want to export them as CSV.

Current behavior:

 3) I expand the 'assigned' group
 4) I can't change the limit of records in the pager
 5) I select all the expanded records by clicking on the checkbox in the header
 6) I use the export wizard. 80 of them are exported, I can't export more!

Expected behavior:

 3) I expand the 'assigned' group
 4) I change the limit of the pager to 2000
 5) I select all the expanded records by clicking on the checkbox in the header
 6) I use the export wizard. 2000 of them are exported

This is a true regression for at least one of our customers who uses this process all along the day (not with export but with other wizards).

Also, if a group can't display more that 80 records, I don't see the point to show the records in the group: the name of the group is "Available (8235)" but it expands only to 80 records and we have no way to see the others.

**Comment by mart-e** [comment]
Fixed at a765876
