### ISSUE TITLE
[8.0] [9.0] stock.picking's claim_count_out field won't be computed

### ISSUE THREAD

**Issue by gabrielo77** [odoo/odoo#25134]
Impacted versions: I've seen it at least in 8.0 and 9.0

Steps to reproduce: Put the field in a view

Current behavior: The field is being computed always for the __first__ record in the RecordSet (using the old API).

Expected behavior: Compute the field for **all** records in the RecordSet.

You can see it here: https://github.com/odoo/odoo/blob/9.0/addons/claim_from_delivery/stock_picking.py#L10

_id_ variable should be passed on to `search_count()` instead of _ids[0]_

**Comment by pedrobaeza** [comment]
That module is deprecated and 8.0 is not maintained anymore. Maybe if you make a PR against 9.0, we can push to merge it as evident, and you can make the same for v8 in OCA/OCB, which is the community backports.

**Comment by Yenthe666** [comment]
Hi @gabrielo77,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
