### ISSUE TITLE
Widget char_domain: not using previous selection as default

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#2513]
(1) Install the Gamification module in the database.

(2) Create a new challange from the menu , Settings -> Gamification Tools -> Challenges

(3) Now , in the "Assign Challange To" field choose some users (employees) and save the record ..

(4) After saving the record , click on the same link called "See Selection" button ..it shows all the users of the system right now , in my point of view it should show only the selected users that you have done in step 3 , not all
![screen_1](https://cloud.githubusercontent.com/assets/7600117/4317938/0075f6f0-3f19-11e4-9de2-2bd2c701c6c3.png)
![screen_2](https://cloud.githubusercontent.com/assets/7600117/4317939/0076e34e-3f19-11e4-9059-bb8460141a93.png)

**Comment by avanzella** [comment]
Hello,
The previous fix does not seam to solve this issue (v8 with latest code).
What is the latest status regarding this error ?
Thank you.

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
