### ISSUE TITLE
[10.0][11.0] If 'View' locations can't have products, then restrict to put products on it. 

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25139]
### Impacted versions:
10.0, 11.0 

### Steps to reproduce:
(a) Do an Inventory Adjustment
(b) Do a transfer through a Picking
* Any other screen which allow to select a location

### Current behavior:
All kind of transfers allow to put products on view locations 

### Expected behavior:
View locations, by definition, shouldn't allow products on it. See: https://github.com/odoo/odoo/blob/25eacbf90017040e76f718ce3000b06c3f41a8e7/addons/stock/models/stock_location.py#L42

Having products on view location completely defies it definition.

**Comment by sle-odoo** [comment]
isn't [this constraint](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_quant.py#L83) enough?

**Comment by gustavovalverde** [comment]
Having a bunch of view locations makes the search complicated and error prone. In v11 if a save a picking with the wrong locations I can't change it afterward.

If the selection domain just removes the view locations, it's a much better experience for high-traffic warehouses.

**Comment by sle-odoo** [comment]
Oh ok, i didn't think about the many2one. We'll have a look :)

**Comment by sle-odoo** [comment]
but i'd only make sense on the stock move line, right? 'cause let's say the main location of your warehouse is a view location, it is allow to make a picking and a move from this location to this location ; it's only forbidden to set a view location on a stock move line, because no quants are allowed there

**Comment by sle-odoo** [comment]
actually it won't work even on the move line, let's imagine a receipt to wh/stock which is a view location ; once you edit the location the original one would disappear if we add a domain.

i'm afraid we can't do more than the constraint here

regards
