### ISSUE TITLE
[11.0] Rounding configuration is applied to all companies

### ISSUE THREAD

**Issue by pmartineznetquest** [odoo/odoo#25148]
Impacted versions: [11.0]

Steps to reproduce:
- Install a multicompany environment
- Configure the rounding.

Current behavior:
- The rounding is being applied to all companies (there is no company_id field)
NOTE: there are a lot of countries that use different roundings depending on its products and currency nature. It is a very common scenario. 

Expected behavior:
- The rounding model is applied only in the specified companies. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Although I agree that you can have different precision needs for product unit price and other minor things by company, accounting and currency related fields are handled correctly through the monetary field type, so although this is desirable, it's not a critical issue. 

@mart-e, what do you think about this?

**Comment by mart-e** [comment]
Sorry but it is not possible, the decimal precision is set at the field level, not for a specific company.
I hear your point but I am afraid it is not possible with the current framework.
