### ISSUE TITLE
[10.0] hr.attendance records does not have correct sheet_id

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#25142]
**Impacted versions:**
10.0c, probably for others version as well

**Steps to reproduce:**
1. Login to Odoo and adjust timezone settings to a non-UTC timezone, e.g. we use Hong Kong (GMT+8) in this example.
![image](https://user-images.githubusercontent.com/27185427/41144346-317f33f6-6b2f-11e8-986f-27975b4ad81f.png)

2. Create a timesheet that covers from 1st June 2018 to 30th June 2018.
![image](https://user-images.githubusercontent.com/27185427/41144324-21792e80-6b2f-11e8-8ae4-7a0e97fd2745.png)

3. Create an attendance record manually with `Check In` as `06/01/2018 07:00:00` and `Check Out` as `06/01/2018 09:00:00`. (The `Check In` time is will be in previous day in UTC)
![image](https://user-images.githubusercontent.com/27185427/41144195-a9fbbd6e-6b2e-11e8-8ac2-c88523c1ba12.png)

**Current behavior:**
- The `Sheet` of the attendance record will be empty.
- Even if there is a confirmed timesheet that is in 1st May 2018 to 31st May 2018, there will not be any user error when the attendance is created.
- For some countries like Japan that timezone difference is larger than 9 hours, e.g. >GMT+9, the record on the first day of the month will always be abandoned, i.e. empty `Sheet` field even the timesheets are no-gap.

**Expected behavior:**
The `Sheet` of the attendance record should be updated with the newly created timesheet.

**Comment by TimLai125** [comment]
Here is the PR fixing this issue, i.e. https://github.com/odoo/odoo/pull/25143

**Comment by pedrobaeza** [comment]
Closing as there's already a PR addressing this.
