### ISSUE TITLE
raise Exception(\"bus.Bus unavailable\")\nException: bus.Bus unavailable\n","message":"bus.Bus unavailable","arguments":["bus.Bus unavailable"]}}

### ISSUE THREAD

**Issue by veena-patel** [odoo/odoo#25154]
Impacted versions:
11.0

Error in Discuss module:
web.assets_common.js:3832 Server application error {"code":200,"message":"odoo Server Error","data":{"exception_type":"internal_error","name":"builtins.Exception","debug":"Traceback (most recent call last):\n  File \"/opt/odoo/odoo/odoo/http.py\", line 646, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 307, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/opt/odoo/odoo/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/opt/odoo/odoo/odoo/http.py\", line 683, in dispatch\n    result = self._call_function(**self.params)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 339, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/opt/odoo/odoo/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 332, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 927, in __call__\n    return self.method(*args, **kw)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 512, in response_wrap\n    response = f(*args, **kw)\n  File \"/opt/odoo/odoo/addons/bus/controllers/main.py\", line 37, in poll\n    raise Exception(\"bus.Bus unavailable\")\nException: bus.Bus unavailable\n","message":"bus.Bus unavailable","arguments":["bus.Bus unavailable"]}}

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, specifically on your reverse proxy configuration or in Odoo configuration without enabling proxy_mode=True, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by mars-trueplus** [comment]
I follow the steps below and it works
1. Config file like this:
[options]
addons_path = /home/ubuntu/source/odoo/odoo-12/addons,/home/ubuntu/source/odoo/odoo-12/odoo/addons, /home/ubuntu/source/odoo/demo_portal
data_dir = /home/ubuntu/source/odoo/datadir/demo_portal
db_password = demo_portal
db_user = demo_portal
xmlrpc_port = 9009
workers = 4
max_cron_threads = 1
server_wide_modules = web,queue_job
limit_time_cpu = 600
limit_time_real = 600
limit_memory_hard = 3221225472
limit_memory_soft = 2147483648
logfile = /home/ubuntu/source/odoo/log/demo_portal.log
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
longpolling_port = 8899
proxy_mode = True




2. Install Nginx and config as a reverse proxy
Nginx config file like this:
server {
    listen 80;
    location / {
        proxy_pass http://127.0.0.1:9009;
    }
    location /longpolling {
           proxy_pass http://127.0.0.1:8899;
    }
}

**Comment by xmars4** [comment]
I follow the steps below and it works
1. Odoo config file :
_[options]
addons_path = /home/ubuntu/source/odoo/odoo-12/addons,/home/ubuntu/source/odoo/odoo-12/odoo/addons, /home/ubuntu/source/odoo/demo_portal
data_dir = /home/ubuntu/source/odoo/datadir/demo_portal
db_password = demo_portal
db_user = demo_portal
xmlrpc_port = 9009
workers = 4
max_cron_threads = 1
server_wide_modules = web,queue_job
limit_time_cpu = 600
limit_time_real = 600
limit_memory_hard = 3221225472
limit_memory_soft = 2147483648
logfile = /home/ubuntu/source/odoo/log/demo_portal.log
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1
longpolling_port = 8899
proxy_mode = True_

2. Install Nginx and config as a reverse proxy
Nginx config file:
_server {
    listen 80;
    location / {
        proxy_pass http://127.0.0.1:9009;
    }
    location /longpolling {
           proxy_pass http://127.0.0.1:8899;
    }
}_
