### ISSUE TITLE
validation error message give no clue of wich check constraint method is failing

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#25167]
Impacted versions: all

Steps to reproduce:

- A new constraint check method which has an error in the validation. (e.g: missing import of ValidationError)

Current behavior:

- The error messages says "Error while validating constraint" and the constraint error. e.g.:
`NameError: global name 'ValidationError' is not defined`

but no clue is given of which constraint method failed.

Expected behavior:

That the error message include also which check failed.

`raise ValidationError("Error while validating constraint with check %s \n\n%s" % (check, tools.ustr(e)))`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code. You have to import the exception you are going to rise. That's something mandatory.

Closing as no real issue.

**Comment by sswapnesh** [comment]
Hello @yucer 
Looks like you are missing `from odoo.exceptions import ValidationError` in your py file.

I just tested Same and seems Working fine.

![](https://image.prntscr.com/image/mbmJAT79S1KWvaEPRFGyig.png)

**Comment by yucer** [comment]
Hi, 

Sorry, maybe I did not specify clearly the problem. I have updated the description.
