### ISSUE TITLE
[11] Odoo recalls computation for fields depending on a translated field

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#25169]
### Impacted versions:
11.0

### Steps to reproduce:
1. Python Code
```
class MyModel(models.Model):
    _name = 'my.model'

    name = fields.Char(translate=True)
    code = fields.Char(compute='_compute_code', inverse='_set_code', store=True)

    @api.depends('name')
    def _compute_code():
        for r in self:
            r.code = r.name.strip().replace(" ", "").encode('ascii', 'ignore').upper()
    def _compute_name():
        pass
```
2. Create a new record in English: ('id':1, 'name': 'My Name', 'code': 'MYNAME')
3. Install an additional language, i.e. Vietnamese and change the user language to the new language
4. Provide "Tên Của Tôi" as the translation term for 'My Name'
5. In another place:
```
rec = self.env['my.model'].search([('id','=',1)])
code = rec.code
```
### Current behavior:
The `rec.code` returns `'TNCATI'` which is the result computed in the method `_compute_code` instead of the value stored in the field `code` which is `'MYNAME'`

### Expected behavior:
The `rec.code` should return `'MYNAME'`

**Comment by fmdl** [comment]
@davidtranhp it is a normal behavior, if the lang of the current user is Vietname when you get `rec.name`, it take `name` in the language of the user. 

If you want name in english, write `rec.with_context(lang='en_US').name`

**Comment by fmdl** [comment]
@davidtranhp you want the `rec.code` always in english ?

**Comment by davidtranhp** [comment]
@fmdl The `code` field is not language concerning as it is defined with `code = fields.Char(compute='_compute_code', inverse='_set_code', store=True)`
Then, it should always return its stored value (i.e. `'MYNAME'`)

But when accessing its value with `rec.code`, Odoo recalls the method `_compute_code` to return the result made by the method instead of 'MYNAME'`
Currenty, to avoid this, I have to query `SELECT code from my_model where id = 1` instead of just `rec.code` as usual in Odoo 10/9/8

**Comment by fmdl** [comment]
@davidtranhp it os what I said, try this code (it always return in english) :

```
    @api.depends('name')
    def _compute_code():
        for r in self.with_context(lang='en_US'):
            r.code = r.name.strip().replace(" ", "").encode('ascii', 'ignore').upper()
```

**Comment by davidtranhp** [comment]
That's not the solution indeed. Why Odoo recomputes the code

**Comment by fmdl** [comment]
remove `inverse='_set_code', `

**Comment by davidtranhp** [comment]
@fmdl My business requires that inverse attribute.

@mart-e @pedrobaeza @Yenthe666 

Would you mind investing this case to see if this is a bug when Odoo recalls compute method although the field is set with `store=True`? It is strange that the form view still display the right data which is properly retrieved from the stored value in the database while the dot access in code recalls the compute method.

**Comment by mart-e** [comment]
Hi,

Having a stored computed field based on translated field while you field is not translatable does not make much sense actually.
I don't get exactly what you are trying to build but I don't think the is the right way.

**Comment by pedrobaeza** [comment]
I agree with @mart-e that you are starting from a wrong foundation: having an stored computed field with a translatable content in the dependency chained is simply something wrong right now on the current framework, as you can only store one value, not all the possible values by translation.

The only possibility for having completed translatable computed fields is to not store them, and add a search method on the field for allowing the search feature. You only lose here the sorting thing.

Closing as no possibility to fix.
