### ISSUE TITLE
[8.0][stock] functional regression: impossible to reserve a lot

### ISSUE THREAD

**Issue by rvalyi** [odoo/odoo#2517]
cc @jco-odoo sorry again for you
cc @anajuaristi 

Hello,

on v6.1 or v7.0, a stock.move had a product_lot_id and you could set it even if the move was just draft or confirmed. A "confirmed" move with a lot would hence "reserve" that lot and decrements its virtual stock.

But in v8, there is no such product_lot_id. It seems the lot is now carried by the stock.quant items associated to the stock.move.

So for instance now when you use the transfer wizard of a picking, you can assign lots for the move ad eventually these lot's are already assigned in the case of a chained picking. But it means you can assign a lot manually only when the stock.move will be in state "done" after validating the wizard.

But in v6.1 or v7, you could assign a lot to any stock.move, even just in "confirmed" state, not only for the move in "done" state! And you also had the "split lot" wizard that would allow to create several moves from a single move, each with different lots. And again you could do that on confirmed moves for instance.

So I feel we lost two important features:

1) how can we reserve one or several lot(s) for an arbitrary stock.move in v8?
2) where can we get the information about lots availability, that is the virtual stock level in a stock location BY LOT?

Thanks.

**Comment by njeudy** [comment]
I raphael, 

I think for the 1, use pick and ship on wharhouse so th pick operation is used to set / reserve special prod_lot.

For the second point, here is the method I will implement:
Add a new function field on stock.move `prod_lot_ids` that list all prod_lot from associated reserved quant, and add a filter on stock move to search prod_lot in ?

What do you think ?

**Comment by rvalyi** [comment]
Hello @njeudy I should push a module to the OCA, I believe I fixed it nicely. It's still tied a bit to our customer impl, but may be this week end I can push it. I'll ping you.

**Comment by njeudy** [comment]
Ok can you give me a access or senf me a zip file to test it ... I have to implement it very quick :) (tomorrow)

**Comment by clonedagain** [comment]
Can you please point to the modules you wrote if you pushed them to OCA?
And maybe close the issue if it's "done".

**Comment by Yenthe666** [comment]
Hi everybody,

At this point Odoo 7 and Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
