### ISSUE TITLE
[11.0-10.0] Impossible to click on "Register Now" button on website event registration

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#25171]
Impacted versions:

At least version 11.0 and 10.0

Steps to reproduce:

Go on the website.
Go on an event with tickets.
Select 1 tickets
Click on the "Register Now" button
Click out of the registration button
it's not possible to click on the "Register Now" button anymore.

Current behavior:

After clicking out the registration popup on the website, it's not possible to click on the "Register Now" button anymore.
This button is disabled.

Expected behavior:

This button should be enabled after clicking out of the registration from.

Video/Screenshot link (optional):

https://youtu.be/KjrNDhHLveQ (version 11.0)

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/pull/25174
