### ISSUE TITLE
State 'progess' dosen't exist anymore, it should be 'sale'...

### ISSUE THREAD

**Issue by RemiFr82** [odoo/odoo#25184]
https://github.com/odoo/odoo/blob/ada423558220375f1cbc49268dcc0b94b8efa0b2/addons/sale/views/sale_views.xml#L479

**Comment by Yenthe666** [comment]
Hi @RemiFr82,

Can you please add more information and reproducable steps?

**Comment by pedrobaeza** [comment]
The problem is specified on the title, and I confirm it's correct. @RemiFr82 maybe you can make a PR fixing this for speeding up the resolution of the problem.
