### ISSUE TITLE
helpdesk_timesheet breaks project form view

### ISSUE THREAD

**Issue by agajic-modoolar** [odoo/odoo#25197]
Impacted versions: 11.0+e

Steps to reproduce: Install helpdesk_timesheet, sign in as user with project manager permission, open project from view.

Current behavior: It is not possible to load form view without helpdesk/user or manager role. It throws Access Error

Expected behavior: ticket_ids and ticket_count fields should only be viewed and computed if user has helpdesk/user or helpdesk/manager role.

@nim-odoo

**Comment by pedrobaeza** [comment]
Please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.
