### ISSUE TITLE
Error converting the units of a purchased product when moving it to storage

### ISSUE THREAD

**Issue by Renatov** [odoo/odoo#25194]
Impacted versions:
10
Steps to reproduce:
Hello, he recommended that he found a problem in the purchase with another unit of measurement of a product, when I make the purchase and I do the movement of warehouses odoo does not allow the movement of the conversion factors to be made with more than 4 digits of decimals, the following error appears
The roundings of your unit of measure %s on the move vs. %s on the product don't allow to do these operations or you are not transferring the picking at once
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, we need detailed steps to reproduce the problem, or it would be very difficult to know what is the problem, and in a standard environment like the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot. If you reproduce the problem there, then please put all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.

**Comment by sswapnesh** [comment]
The Error message you are getting is Wrong as mentioned as here.

```
# TDE FIXME: I bet the message error is wrong
if not remaining_move_qty.get(move.id):
        raise UserError(_("The roundings of your unit of measure %s on the move vs. %s on the product don't allow to do these operations or you are not transferring the picking at once. ") % 
(move.product_uom.name, move.product_id.uom_id.name))
```

https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_move.py#L847

**Comment by pedrobaeza** [comment]
No further answer and details provided by @sswapnesh are also not enough, so I close this. Feel free to comment for reopening if more details are added.

**Comment by sswapnesh** [comment]
@pedrobaeza Author of this commit has already mentioned this is non relevant to the situation happening here.
So the question is why it is not allowing to transfer the Picking? It shows this wired Warning message.

**Comment by pedrobaeza** [comment]
Yes, but we don't have more traces of how to get to the error, so no possible solution (apart from the error message not being adequate).

**Comment by sswapnesh** [comment]
Okay, I will add detailed steps on this.

**Comment by mixdevdev** [comment]
so?
