### ISSUE TITLE
[POS] Wrong Alignment of Note Field.

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#25199]
Impacted versions:
11.0
Steps to reproduce:

1.Enable note functionality on orderline.
2. Select a product in pos.
3. click on note button .

Current behavior:

Dialog with note field will be displayed with wrong alignment.

Expected behavior:

Dialog with note field should be displayed with proper alignment.

Video/Screenshot link (optional):

![orderline note issue](https://user-images.githubusercontent.com/37578829/41270883-2e86cea8-6e2b-11e8-98b8-7b1e85ece6e2.png)

**Comment by sswapnesh** [comment]
BTW This works well in Chrome browser.

**Comment by MeetKD** [comment]
@sswapnesh Yes you are right that alignment is working well in chrome but there is another issue which i found testing on chrome is that you can resize this note field outside the dialog as well. I am adding another issue for that.

**Comment by switch87** [comment]
Closed by  #27887

**Comment by sswapnesh** [comment]
@switch87 
Still same Issue (Tested on Latest Runbot)
![Uploading Screenshot (59).png…]()
