### ISSUE TITLE
Street and House-number are viewed in wrong sequence (turned around) on printed sale.order PDF in the Nethelands  

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#25204]
Impacted versions:
11

**Steps to reproduce:**
1. In res.partner a fill street with streetname and fill housenumber with housenumer
2. Create sales.order en select the created contact
3. Pint sale.order

**Current behavior:**
Current behaviour is that the address is not viewed correctly on the PDF document. 

<housnumber> <streetname>
<zip>, <city>
 

**Expected behavior:**
In the Netherlands adresses should appear as following: 
<streename> <housnumber>
<zip>, <city>

Video/Screenshot link (optional):

<img width="577" alt="example_1" src="https://user-images.githubusercontent.com/36632285/41283759-bd25fd80-6e37-11e8-9601-6f2ab1cdab40.png">
<img width="778" alt="example_2" src="https://user-images.githubusercontent.com/36632285/41283767-bfcccd02-6e37-11e8-88d6-38da01e58e9b.png">

**Comment by mart-e** [comment]
@Patrickar why should it be switched?
The address format is actually set on the country configuration so you can change it if you want to use a different format.

![screenshot_2018-06-12 netherlands - odoo](https://user-images.githubusercontent.com/564822/41285612-06e8427a-6e3d-11e8-83e8-803d1f2fb47b.png)


@xmo-odoo this is the module base_address_extended, from @qdp-odoo

**Comment by qdp-odoo** [comment]
maybe we need to switch street_name and street_number(s) for the Netherlands' street_format, within the data xml directly? (If every Dutch around agrees with that, of course)

**Comment by yung-wang** [comment]
Yes, I agree with @qdp-odoo, this needs to be switched. 

street_name first and than the street_number + street_number2
Please change.

**Comment by nim-odoo** [comment]
I'm on it ;-)
