### ISSUE TITLE
[POS Restaurant] POS Order note Resize  issue.

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#25215]
Impacted versions:
11
Steps to reproduce:
1. Open POS.
2. Select a product.
3. Click on note button.
4. Resize the text box from bottom right corner.

Current behavior:

You can resize text box outside the dialog.

Expected behavior:

Resize should be done within dialog or disable the resize on note field.

Video/Screenshot link (optional):

![orderline_note_resize](https://user-images.githubusercontent.com/37578829/41308987-09509e00-6e9b-11e8-9de8-b3992f547bc5.png)

**Comment by MeetKD** [comment]
#25199

**Comment by sswapnesh** [comment]
This works same for text field in backend too.

**Comment by switch87** [comment]
Closed by  #27887

**Comment by sswapnesh** [comment]
I think still it has issue in Text field area in Backend.(May be I should add this in another Issues as this one refers to Pos only)

**Comment by switch87** [comment]
> I think still it has issue in Text field area in Backend.(May be I should add this in another Issues as this one refers to Pos only)

Indeed, the POS session is the only part of Odoo that works completely separate becous of the offline capabilities it needs. Therefore issues that it once inherented AR not linked anymore. 

Please make a new issue with screenshot so someone in the community or one of my colleagues can take a look at it.

**Comment by sswapnesh** [comment]
@switch87 
Still same Issue (Tested on Latest Runbot)
![screenshot 59](https://user-images.githubusercontent.com/16624719/47589340-7e250300-d986-11e8-913c-0dbca8bbc9f8.png)

**Comment by switch87** [comment]
> @switch87
> Still same Issue (Tested on Latest Runbot)
> ![screenshot 59](https://user-images.githubusercontent.com/16624719/47589340-7e250300-d986-11e8-913c-0dbca8bbc9f8.png)

On which runbot? The fix is done on 10 (to be ported to 11) and on 12. So if you tested on 11, this is normal becous there is no commit to fix it yet .

**Comment by sswapnesh** [comment]
Oops, Sorry.
I was not aware about this. 
Thanks
