### ISSUE TITLE
Banking : multicurrency group not correctely set for bank statement 

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#2521]
If the multicurrency group is activated I see on all bank statement extra columns 'amount currency' and 'currency'.
This can lead to errors so I suggest to correct as on the following printscreen : 
For bank journal in company currency ->

![banking_in_company_currrency](https://cloud.githubusercontent.com/assets/5735158/4319232/a6730588-3f29-11e4-877e-67cb34d1c10a.png)

For bank journal in foreign 
![banking_in_currrency](https://cloud.githubusercontent.com/assets/5735158/4319251/e1e118c6-3f29-11e4-9f24-3bfe3b1359b7.png)
currency ->

 Thanks

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
