### ISSUE TITLE
KeyError: 'crm.lead2opportunity.partner.mass'

### ISSUE THREAD

**Issue by bariserdogan** [odoo/odoo#25222]
Impacted versions: Odoo V11

Steps to reproduce: Login -> Homepage -> Crm

Current behavior: We use Odoo in the Odoo.sh platform. After logging into Odoo, we get Key Error like this when we click on CRM. And the crm module is not opening. :
                             **KeyError: 'crm.lead2opportunity.partner.mass'**
However, we don't get this error when we access to another modules

Expected behavior: We want use the CRM module 

Video/Screenshot link (optional
![error](https://user-images.githubusercontent.com/17798258/41340257-9c6293ba-6eff-11e8-997d-092911c2e780.PNG)

**Comment by Elkasitu** [comment]
Can you reproduce this on a standard runbot instance [1]? This is most likely an instance-specific issue. 

Since you mention `odoo.sh` I recommend you open an enterprise support ticket as we only handle Odoo standard bugs on GitHub.
