### ISSUE TITLE
Ebay connector module syncs wrong product variants in the generated Sale Order

### ISSUE THREAD

**Issue by macdelacruz** [odoo/odoo#25242]
Impacted versions:
v10 and v11

Steps to reproduce:
1. Create products with multiple variants.
2. Install sale_ebay module.
3. Connect Odoo to ebay.
4. Publish product and its variants to ebay.
5. Create a transaction from ebay and let Odoo sync this transaction to create a Sales Order

Current behavior:
Wrong product variant is added in the generated Sales Order.

Expected behavior:
From a developer perspective, I figured out that something is wrong in this line of code in sale_ebay/models/product.py:
![selection_008](https://user-images.githubusercontent.com/13848476/41386253-1ee23238-6fb3-11e8-89e2-48d37bd8d87a.png)

`variant` is used in the `for` loop when in fact it is already declared outside this loop and refers to the correct product variant purchased from ebay. Since this is used in this `for` loop, the original `variant` variable is replaced with the last item in the iterated object, `self.product_variant_ids`.

This is just like:
```
>>> x = "something"
>>> for x in [1,2,3]:
...     print("something again")
...
something again
something again
something again
>>> print(x)
3
```
I think that `variant` in the `for` loop should be renamed to something else.

**Comment by sswapnesh** [comment]
Better to add Official ticket on [https://www.odoo.com/help](https://www.odoo.com/help) as `sale_ebay` is enterprise module.

**Comment by pedrobaeza** [comment]
Please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.
