### ISSUE TITLE
No module named 'werkzeug'

### ISSUE THREAD

**Issue by pedroporras** [odoo/odoo#25254]
Impacted versions:
Odoo V11.0
Steps to reproduce:
The error is when execute ./odoo-bin -d databasename
Current behavior:

Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/home/odoousr/odoo-repo/odoo/__init__.py", line 84, in <module>
    from . import modules
  File "/home/odoousr/odoo-repo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/odoousr/odoo-repo/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/home/odoousr/odoo-repo/odoo/tools/__init__.py", line 9, in <module>
    from .misc import *
  File "/home/odoousr/odoo-repo/odoo/tools/misc.py", line 25, in <module>
    import werkzeug.utils
ImportError: No module named 'werkzeug'

Expected behavior:
Start the service
Video/Screenshot link (optional):
![error](https://user-images.githubusercontent.com/11019468/41422340-58180d38-6fbe-11e8-913c-8f6ea5f6afa8.png)

**Comment by sswapnesh** [comment]
Hello @pedroporras 
Have you gone through the installation document and followed steps ? [https://www.odoo.com/documentation/11.0/setup/install.html#source-install](https://www.odoo.com/documentation/11.0/setup/install.html#source-install)
Looks like you have not installed Required Packages

**Comment by pedroporras** [comment]
yes it isn't installed. i installed later by myself but i throws me other problem, the service of odoo dont start it keep freeze
![image](https://user-images.githubusercontent.com/11019468/41427208-cf0d3960-6fcb-11e8-99cb-10709c64ea8d.png)

**Comment by Elkasitu** [comment]
Hi,

Sorry but this is not the place for discussing misconfigured servers, only bugs in Odoo standard are handled on GitHub.

Please follow the installation guide linked by @sswapnesh and make sure to read all the relevant documentation and if despite that you can't seem to figure out what's wrong with your server, you can go to the Odoo Forum [1] and check if your issue already exists and if not, create a new thread asking for help.

Regards,

[1] https://www.odoo.com/forum/help-1
