### ISSUE TITLE
[Wishlist：Master] Separate the basic mrp.bom model into product

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#25259]
Impacted versions:
     I have noticed that the new version has always been doing business segmentation, so that the coupling between the modules is lower.
    The phantom in the BOM type is usually used only for non-manufacturing scenarios. In the current module design, to use this function, a manufacturing module must be installed. And from the perspective of product management, BOM is the basic information of the product, usually the source of bom is in engineering design.
    Therefore, it is recommended that the basic bom information in the bom object, which is not related to the manufacturing process, be moved to the product module, and then it is more appropriate to inherit and expand the manufacturing module.
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by gustavovalverde** [comment]
I agree a 100% with this.

Almost all clients need a way to create a Kit (product combination for combos, for example). This is very common on retail companies, as depending on the season or special dates (Black Friday) they need to create kits to offer on the POS or the Sales modules. 

The major issue we face with this scenario is that the Client needs the whole MRP module for a simple kitting.

It would be nice to have just the kitting on the Sales/Product module, as this is actually not a Manufacturing process, it's just having two products bundled together; and the cost of the MRP module is too high for tiny clients that just need to bundle their products together.

**Comment by pedrobaeza** [comment]
@jco-odoo What do you think about this?

**Comment by janbec** [comment]
I would also greatly appreciate the proposed changes. We are running a retail company and have a lot of modular products (set of products combined, freely re-combinable). Even from an enterprise contract view, I would prefer less complexity by not adding the MRP module.

**Comment by Guobower** [comment]
I think product kits are usually used only for bundling sale and do not actually require assembly, especially in the supermarket. As a typical trading business, bundling sale do not require a production process.

**Comment by pedrobaeza** [comment]
Bundles management requires more than only the BoM: special prices, grouped delivery,... so this can't be considered as something to be handled in product module, but on a series of modules that involve all areas.

Due to this and the comment by @jco-odoo, I'm closing this wishlist issue. If Odoo one day considers to include bundle management inside Odoo, for sure the structure will change and models will be allocated in the proper modules.

**Comment by gustavovalverde** [comment]
Just as l10n_xx issues. This one would be a good one to keep open for a
while to get some feedback and comments. From my PoV, this is a great idea
for v12 and it has been a real requirement for SME which just need bundling
without all the heavy lifting from the MRP module.

**Comment by pedrobaeza** [comment]
This issue doesn't add any valuable data to keep in mind, just the desire to have it, so it's not worth to keep it opened.

**Comment by Guobower** [comment]
It is not necessary to implement the bundle function here, but just want to explain that bom is not only in the production module, the module is split in order to follow the module does not depend on MRP

**Comment by Guobower** [comment]
In fact, in the product development business , the BOM is more used to describe the overall structure of the product, not the single-level BOM for manufacturing.

**Comment by lap-odoo** [comment]
I've taken good note of the feedback but that's definitely not a priority (especially for version 12). We prefer to focus on tasks that bring value (improvements or new features) instead of reordering modules and having the same features available at the end. For me, this is more a commercial issue than a technical/functional one. The question is : is it fair to ask users to pay for manufacturing module to be able to use kits ? It's debatable ...

**Comment by pedrobaeza** [comment]
@lap-odoo good point, Laura, although I still consider that the kit feature is half-implemented and only valid as an extra with few cost once you have installed manufacturing, but not fully featured for kitting management and of course not for bundling. If in any moment it's considered for extracting the functionality in more core modules, it should be expanded with other options. Please ping me when you decide to go with this.
