### ISSUE TITLE
[11.0]: Sale Order Line sometimes doesn't write new values when editing any field  

### ISSUE THREAD

**Issue by Luckin93** [odoo/odoo#25255]
Impacted versions:
11.0 Enterprise
Steps to reproduce:
1. Create a Quotation/Sale Order with 1 or more products and save it.
2. Using the form View instead of  tree view, edit any Sale Order Line (ex.) Try to add some routes, edit prices or product quantities.  
Current behavior:
When clicking save the values in tree view doesn't change and if I try to edit the line again in form view, the form view has the same values of the tree view.
Expected behavior:
When editing sale order line it has to save new values.

I have to say this only happens sometimes I mean once per week but when this happens it affects at all the Quotations created. The only way that I can fix this temporarily is restarting the Odoo service 

Video/Screenshot link (optional):
At the time that I wrote this the SO its working well, but I attach a photo of the form view of the sale order line.
![image](https://user-images.githubusercontent.com/16857863/41434040-935d3bd2-6fe8-11e8-836a-c605da60af2a.png)

**Comment by pedrobaeza** [comment]
Please put an OPW ticket at https://www.odoo.com/help, as this is something specific of the enterprise interface, which doesn't belong to this repository.

Closing the issue by the reason above.
