### ISSUE TITLE
Some translations values from Transifex do not update

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#25276]
**Impacted versions:**
Problem occurs when we are translating Odoo in Transifex from English to Estonian.

**Steps to reproduce:**
1. Open Transifex
2. Translate Odoo 11 from English to Estonian
3. Search in Transifex "translation_text:'arveldus'"
4. Open in a new tab Odoo database
5. Load Estonian language
6. Install Accounting module
7. Have a look on accounting module name
OR
Search source terms in Transifex for example "Archive"

**Current behavior:**
If you are looking in Transifex for translated term "arveldus", then you will not find source term "accounting", but if I update translations in our Odoo then Accounting module will be translated as "arveldus".
OR
If you are looking in Transifex for a source term "Archive", then you will see that all terms are translated as "Arhiveeri", but in real life this translation will not appear in Odoo database:
![image](https://user-images.githubusercontent.com/40301417/41479001-68b5870a-70d2-11e8-89dd-b9752291ac7f.png)

**Expected behavior:**
"Accounting" should have translation in Estonian "Raamatupidamine".
OR
"Archive" translation from Transifex should come to Odoo Database as "Arhiveeri"

**Video/Screenshot link (optional):**

![arveldus](https://user-images.githubusercontent.com/40301417/41478750-81e6d4aa-70d1-11e8-8673-8b27a7d49002.PNG)
![image](https://user-images.githubusercontent.com/40301417/41478891-04a205b8-70d2-11e8-808e-66e28ff2f720.png)

**Comment by mart-e** [comment]
Hello,

Sorry but the menu you are showing in your screenshot will always be called Invoicing. Renaming a menu when installing another module does not work with translations. I am personally in favour of stop renaming it in English too but that is not my call ;-)

Regarding the Archive, could you be a bit more specific? Where do you see the wrong translation (i.e. which module)?
Are you sure the translation is already synchronised with github (done every Sunday) ?
Are you testing with a system up to date (e.g. the [runbot](http://runbot.odoo.com/)) ?
If you have updated the translation on your server, did you checked the "overwrite existing terms" box?

**Comment by pedrobaeza** [comment]
No further answer, so I close. Feel free to comment for reopening if the answers are given.
