### ISSUE TITLE
Odoo pos duplicates tables

### ISSUE THREAD

**Issue by DennisAries** [odoo/odoo#25278]
Impacted versions: 10, 11

Steps to reproduce: create a floor plan with tables. Close the window. Enter the floor plan again and add an table. Close the browser and connect again. 

Current behavior: tables on the floor are duplicated or tripled after alteration. 

Expected behavior: floorplan to stay intact after alteration

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Duplicate of #24831

**Comment by Yenthe666** [comment]
Indeed, closing this one off as it is a duplicate.

**Comment by ZeroCoolHacker** [comment]
You marked this issue duplicate of the <a href="https://github.com/odoo/odoo/issues/24831">#24831</a> and marked that issue duplicate of this one and didn't answer the question in any of them -_-.

**Comment by sswapnesh** [comment]
@ZeroCoolHacker Resolved in #27924
