### ISSUE TITLE
[11.0] stock: 'Internal' picking type shouldn't force a default_location_dest_id

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25288]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Select **Internal** as the Picking type

#### Current behavior:
- The field `default_location_dest_id` is required

#### Expected behavior:
- On multi-location, multi-warehouse the destination location is not always known
- This also allows great mistakes as you can transfer from location A to location A (same location). As this is the _most sane_ default option, but it's also error prone.

**Comment by gustavovalverde** [comment]
Ticket 1863049

**Comment by sle-odoo** [comment]
Closing as the linked ticket is solved.
