### ISSUE TITLE
[11.0] Dropdown Issue

### ISSUE THREAD

**Issue by MeetKD** [odoo/odoo#25285]
Impacted versions:
11.0
Steps to reproduce:

1. Click On Point of sale menu inside configuration.
2. Click on Edit button.
3. Click on label of Fiscal Position per Order.

Try clicking on several label like (Fiscal Position per Order, barcode scanner, Fiscal Position etc)

Current behavior:

It will open a dropdown on top left panel.

Expected behavior:

It should not display the dropdown.

Video/Screenshot link (optional):

![incorrect dropdown](https://user-images.githubusercontent.com/37578829/41508980-5d658ffa-726a-11e8-9e2f-439e728d2f5c.png)

**Comment by switch87** [comment]
solved from https://github.com/odoo/odoo/commit/5da419a4fef48b36857593dd08346c68b0ba74c5
