### ISSUE TITLE
[11.0] point_of_sale: Prices don't change with a pricelist using a different currency

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25291]
#### Impacted versions:
11.0 
#### Steps to reproduce:
- Have a company with USD as main currency
- Create a pricelist with EUR
- Validate that in the Sales module prices are converted to EUR based on the exchange
- Use the EUR pricelist on the POS

#### Current behavior:
- POS won't convert to EUR using the corresponding rate.

#### Expected behavior:
- POS prices with the EUR pricelist should respect the rates.

**Comment by Yenthe666** [comment]
@pimodoo can you check please?

**Comment by gustavovalverde** [comment]
Tciket 1863047

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/32f5b8c034c9ec3c2772c5c8cad5789d67e6955b
