### ISSUE TITLE
Can't remove product description

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#25308]
When using Odoo with a language other than English, we can't remove the descriptions under the **Notes** tab

Impacted versions:
9.0, 10.0, 11.0

Steps to reproduce:
- Load Odoo on a new language;
- Set a new description for quotations on a product and save;
- Edit and remove the added description and save.

Current behavior:
After removing the description, the english translations in loaded.
The only way to remove the description is by deleting the translation

Expected behavior:
Leave the description empty when deleting the field value

Video/Screenshot link (optional):
[Example Video](https://archive.org/details/odoo_product_description_bug) (9.0 in pt_PT)

**Comment by mart-e** [comment]
Hello,

Sorry but when you work on a translatable field, you **must** consider all languages. If you remove the value, you must remove it in all languages.
As you have found out on the video, you have to reset the source value in addition of removing the translation.
The other possibility is to switch from one language to another and remove the value in each one.
