### ISSUE TITLE
setup.py install ends with error : setup script specifies an absolute path

### ISSUE THREAD

**Issue by mr-akin** [odoo/odoo#25311]
**impacted version:** 11.0

**How to reproduce?**
`python setup.py install`

**Result:**

```
error: Error: setup script specifies an absolute path:

    C:\Users\abcd\AppData\Local\Programs\Python\Python36\lib\site-packages\babel\global.dat

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

**Comment by pedrobaeza** [comment]
Can you specify the detailed steps to reproduce the problem?

**Comment by pedrobaeza** [comment]
@d-fence do you have a clue on this, or should we close it as not enough information?

**Comment by d-fence** [comment]
Hello, it seems linked to the py2exe stuffs:
https://github.com/odoo/odoo/blob/2ab3fa86fe83d507e9e1152ad2a44811af7f55cd/setup.py#L26

py2exe is not used anymore since v11, I have to clean the setup file.

**Comment by mr-akin** [comment]
Hello, I'm sorry for following up after too long. @d-fence Yes its related to py2exe stuff, I want to make an executable file but ends up with that mentioned error.

**Comment by d-fence** [comment]
@mr-akin py2exe doesn't not work anymore with Odoo since version 11.
I'm sorry.
I close this issue as it was the purpose.

**Comment by mr-akin** [comment]
@d-fence  so this means there is no way I can make an executable file?

**Comment by d-fence** [comment]
I tried hard, also with cx_Freeze and Pyinstaller.
The py2exe section in the setup.py is rather old and is about the previous Odoo version.
