### ISSUE TITLE
Birthdate should be date, not char

### ISSUE THREAD

**Issue by dhongu** [odoo/odoo#2531]
The field birthdate from res_partner is char, correctly type is date.

**Comment by u8621011** [comment]
why odoo8 this issure occurred again?? (char type)

is there any concern make this field change back to char type?

**Comment by tbaptista** [comment]
Same question. This issue is still open in the 8.0 version. The field type is set to char.

**Comment by BT-faebi** [comment]
Dear Odoo Team, even in Odoo 9.0 the birthdate field is still a char and not a date as it should be. Could we at least have an explanation why you don't want to change this, or why you didn't merge the PR from rda-odoo? Kind regards. Frédéric Aebi, brain-tec

**Comment by Yenthe666** [comment]
@mart-e  could you give your input here?

**Comment by fpodoo** [comment]
We should remove this field, as it is not used. That way, anyone can
customize and add the type he wants.

**Comment by Yenthe666** [comment]
Sounds good to me. @fpodoo can you assign somebody on this or create a task for it?

**Comment by tde-banana-odoo** [comment]
@fpodoo actually we kept that field a few months / years ago because we used it internally. It is still a char field because we did not want to put constraints on what to type in it. For me it should totally be a custom field. So if you agree, let's remove it !

**Comment by mart-e** [comment]
Done at 7b2ab482f3a06fadf4cdd3b566701611aaadd9b1
