### ISSUE TITLE
Odoov11E : Issue with widget many2many_tags in formview

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#25319]
Impacted versions:
	> Odoov11E

Steps to reproduce:
	> Do invisible any many2many field from treeview . 
		e.g : In sale app > sale order > do invisible field (Analytic Tags) analytic_tag_ids.
        > Now in create sale order and add Analytic tags (existed in order line formview).
 	> Once order is saved open that formview of order line.Analytic tags will be disappeared.
	> But while editing again that order line and going to select other analytic tag, all (saved)existing analytic tags appearing properly.

Current behavior:
	> Many2many field when having widget 'many2many_tags' causing issue in rendering a data.

Expected behavior:
	> It should render data in many2many field properly.

Video/Screenshot link (optional):
	
Screenshots:
 https://www.awesomescreenshot.com/image/3431073/777bd48d2df1390099742be2465d9e76
 https://www.awesomescreenshot.com/image/3431076/9f1a4921071aa0b30e97505a079f7504

Video :
		> https://youtu.be/YLcse-enB_8

Thanks,
Dipak

**Comment by dipsshah42** [comment]
Its on runbot  !
i tried with instance > [](http://339406-11-0-e48de5.runbot14.odoo.com)

**Comment by pedrobaeza** [comment]
That one is enterprise, not community

**Comment by dipsshah42** [comment]
Hey @pedrobaeza ,
I just checked and Its in community v11 odoo as well.
Please have a look [CommunityRunbotInstance](http://339499-11-0-d65043.runbot17.odoo.com)

Thanks,
Dipak

**Comment by pedrobaeza** [comment]
OK, then this issue tracker is the right place. If only enterprise, then it should be notified through other ways.

@ged-odoo this seems something for you.

**Comment by pedrobaeza** [comment]
@sswapnesh have you tried on enterprise or community runbot?

**Comment by Yenthe666** [comment]
I just tested on both community and enterprise and it has been fixed on both!

**Comment by sswapnesh** [comment]
> @sswapnesh have you tried on enterprise or community runbot?
enterprise runbot

**Comment by pedrobaeza** [comment]
OK, thanks for confirming. Screenshots were not very clear for differentiating both, or I'm not very used yet to neither 12.0 community/enterprise.

**Comment by sswapnesh** [comment]
Can Understand, BTW It was for v11, (Didn't tested this in v12 E)

**Comment by pedrobaeza** [comment]
hahaha, then my confusion comes from this! In v11 indeed community UI is not that way.

**Comment by sswapnesh** [comment]
It was also confusing for me in Release days of v12 as they kept same colour for few days. (Wasn't able to decide quickly if it is CE or EE)
