### ISSUE TITLE
Stock Inventory Line - Location Name related field must be readonly.

### ISSUE THREAD

**Issue by jacara** [odoo/odoo#25312]
Impacted versions:11.0

There is a location_name field on stock.inventory.line model. This field is related and non stored. But there is no readonly attribute. In this behavior if I have 500000 inventory line in my database then I can't upgrade stock module anymore. Because when loading addons/stock/data/stock_data.xml resource then its getting long time and too much memory usage.

**Comment by pedrobaeza** [comment]
Can you propose a PR changing this?

**Comment by jso-odoo** [comment]
@jacara , are you still facing the issue because I can see the field **location_name** is stored field, not the not stored. Please let me know if the issue remains same.! 
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_inventory.py#L327
