### ISSUE TITLE
[11.0] Access right issue when unpacking a package

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#25320]
Impacted versions:
11.0

Steps to reproduce:
On Runbot, Add "Manage package" on demo user. Connect with demo user. Do a picking IN and add some products to some pack. Validate your picking. Go to the packages and click on "unpack" (still with demo user)

Current behavior: you have an access error on stock quant

Expected behavior: No stock quant error

Video/Screenshot link (optional): https://youtu.be/D0-yHzoHZjw

**Comment by sle-odoo** [comment]
This is now fixed.
