### ISSUE TITLE
Commit issue

### ISSUE THREAD

**Issue by shurshilov** [odoo/odoo#25339]
1) We added a function to the hr_payroll module:

def _compute_sheet_cron (self, domain):
         record_compute = self.env ['hr.payslip']. search (domain)
         for rec in record_compute:
             rec.compute_sheet ()

2) To be able to automatically calculate from ir.cron (python_code), for example:

([('date_from', '> =', (datetime.date (day = 1, month = datetime.date.today (). month, year = datetime.date.today (). year) - dateutil.relativedelta. relativedelta (days = 1)). strftime ('% Y-% m') + '-01'), ('line_ids.category_id', '=', 'IT')],)

3) For proper operation, we added the datetime and dateutil libraries to the safe_eval file. The _import method in the _BUILTINS list
/usr/lib/python2.7/dist-packages/odoo/tools/save_eval.py

2 Lines: 'datetime': datetime, 'dateutil': dateutil,
And we wanted to ask you to make similar changes to this list, if possible, so that our module would be installed out of the box, without changes in the core of the odometer code.

**Comment by pedrobaeza** [comment]
Sorry, but you have to propose a PR if you want any change in this to be evaluated. This change should be minimal and well justified, and it can only be accepted on master. You can also make a custom module that make the proper extension.

Closing as no issue at all.
