### ISSUE TITLE
[11.0]Default kanban stages doesn't allow edit their titles

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25333]
Impacted versions:
Odoo 11.0-20180122 (Community Edition)

Steps to reproduce:
1. Create a new `Project`.
2. Go to task and create a new `Task` in that `Project`.
3. Review Kanban and try to edit its title.

Current behavior:
Edit option is not enable for that stage.

Expected behavior:
Edit option available for that stage.

You can compare it in the next screenshots:
![createdstage](https://user-images.githubusercontent.com/5034215/41599067-b450e528-73da-11e8-999e-409e602af876.png)
![defaultstage](https://user-images.githubusercontent.com/5034215/41599068-b478d506-73da-11e8-8bbe-5f983fc8cae2.png)

**Comment by pedrobaeza** [comment]
This is the expected behavior, as that stage is having "no stage", so you can't change a name of something that is not defined.

Closing as no real bug.
