### ISSUE TITLE
[11.0] Purchase.order.qty_received wrongly calculated

### ISSUE THREAD

**Issue by qtiplb** [odoo/odoo#25367]
Impacted versions:
V11 Enterprise

Steps to reproduce:
1. Make a PO with several lines
2. Confirm the PO
3. Go to the linked reception bill WH/IN
4. Leave one line to 0 and confirm the rest of the quantities
5. **Chose no backorder**
6. Go back to the linked PO

Current behavior:
On the PO, the _Receive Qty_ shows the full quantity even if none has been received

Expected behavior:
It should be showing 0 as _Receive Qty_

Additionnal info:
The problem seems to be related to the field _Receive Qty_ which is calculated based on the field _stock.picking.product_uom_quantity_ rather than _stock.picking.quantity_done_

Video/Screenshot link (optional):
![wh in 00018 - odoo 2018-06-20 17-14-02](https://user-images.githubusercontent.com/31708522/41685101-74710c7a-74ad-11e8-8973-a299e98ca33f.png)
![po00014 - odoo 2018-06-20 17-13-29](https://user-images.githubusercontent.com/31708522/41685106-78d5a0be-74ad-11e8-980b-f1454a397f50.png)

**Comment by sswapnesh** [comment]
Hello @qtheuret 
I cannot Reproduce the same on Runbot 11 Community  [http://342910-11-0-bb78b7.runbot16.odoo.com/web?debug#id=7&view_type=form&model=purchase.order&menu_id=577&action=794](http://342910-11-0-bb78b7.runbot16.odoo.com/web?debug#id=7&view_type=form&model=purchase.order&menu_id=577&action=794)

![po1](https://user-images.githubusercontent.com/16624719/41995845-b07b0c20-7a70-11e8-8fb2-79bfaa0f1bb6.png)
![po2](https://user-images.githubusercontent.com/16624719/41995846-b1229436-7a70-11e8-9fd6-be04a8515d92.png)
![po3](https://user-images.githubusercontent.com/16624719/41995873-c2d93b44-7a70-11e8-960a-2439b4af0020.png)
