### ISSUE TITLE
[10.0/11.0] PoS: Total is not updated after adding Tip

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25362]
Impacted versions:10.0/11.0

Steps to reproduce: Enable Tip In Pos Config
![15](https://user-images.githubusercontent.com/16624719/41670614-68d12aec-74d2-11e8-9cad-86b8baf2aab4.png)

Create Order --> Add Tip on Payment Screen
![14](https://user-images.githubusercontent.com/16624719/41670472-04bbbdec-74d2-11e8-8a24-b4476597dc7e.png)

Current behavior: Total is 8.0

Expected behavior: Total should be 10.0

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@pimodoo can you check this one?

**Comment by sswapnesh** [comment]
This is because of Bad configuration of Tip Product (Added ##25406 for same)

**Comment by sswapnesh** [comment]
Handled in 0562fc0ffde3711e33cb7744e7978deb8502bdff
