### ISSUE TITLE
[11.0] Invalid Datetime format in breadcrumb

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25364]
Impacted versions: 11.0

Steps to reproduce: See the Attached Image

Current behavior:
![12](https://user-images.githubusercontent.com/16624719/41670273-7472cb72-74d1-11e8-8c85-df9d15c33d93.png)
(It does not respect Timezone as well)

Expected behavior: Datetime format should be Same

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I'm seeing this doesn't take into account time-zones, probably in the `name_get`.

@tivisse I'm not sure if you are the proper one for checking this.

**Comment by sswapnesh** [comment]
My Bad, I didn't configured Timezone In that Db. 
Timezone is taken into account.
But it has still Issue with Datetime format Configuration.

![](https://image.prntscr.com/image/ZRp6tOufTheP-A-BCt2mig.png)

![](https://image.prntscr.com/image/r8HXULT_TSWPhvrujhDsKA.png)

**Comment by pedrobaeza** [comment]
That's because is printed in "raw" format. This is not critical, but it would be good to have it formatted.

**Comment by tivisse** [comment]
Hi @sswapnesh 

Thanks for the feedback.

As @pedrobaeza said, this is not critical. You can open a PR if you wish, and I would be able to review/merge it. We are now preparing for the release of Odoo 12.0 so I don't have much spare time to handle this.

Have a nice day,

Yannick.

**Comment by sswapnesh** [comment]
May be better to label this Issue as Wishlist and Keeop it open for reference.

**Comment by sswapnesh** [comment]
Improved in v12 https://github.com/odoo/odoo/pull/33369 at https://github.com/odoo/odoo/commit/5648bbada855928ea4f27a6585b24142593bb48a
