### ISSUE TITLE
[11.0] Could not Access Sales Channels report after Uninstalling CRM module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25363]
Impacted versions: 11.0

Steps to reproduce: Install  Sales Management --> Install CRM--> Uninstall CRM --> Go to Sales/Reporting/Sales Channels

Current behavior:

![](https://image.prntscr.com/image/orKQqyhuT826aZmgy1RYrA.png)

  File "/home/swapnesh/Workspace/11/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'crm.opportunity.report'
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@Elkasitu another one about uninstallations. Can you please check?

**Comment by sswapnesh** [comment]
This is Causing the Issue as it is trying to get Graph data from Content (Pipeline -`crm.opportunity.report`) which is removed during CRM uninstallation
![](https://image.prntscr.com/image/foyUcGilTzidKGhJXESTKA.png)
