### ISSUE TITLE
[10.0][11.0] Invoice Analysis displays positive product quantity for sales refunds

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#25380]
**Impacted versions:** 10.0, 11.0

**Steps to reproduce:**

1. Go to demo.odoo.com (or any demo database)
2. Go to Accounting -> Sales -> Customer Invoices
3. Open INV/2018/0001 (I picked this one because it was the only invoice for a single client and it made testing easier) or any other invoice made for a single client
4. Create a credit note ("Cancel: create credit note and reconcile")
5. Go to Accounting -> Reporting -> (Management) -> Invoices
6. Filter the invoices by partner, add "Product Quantity" as a measure, group by "Type" (invoice type)

**Current behavior:**
Total Without Tax sum is zero (which is correct) and Product Quantity is **double** instead of zero (which is incorrect)

**Expected behavior:**
The Product Quantity is negative for invoices of type `out_refund`.

**Video/Screenshot link (optional):**
1. Take the demo sales invoice for Camptocamp which has two lines and the product quantity sum is 10, and create a credit note ("cancel invoice": create a refund and mark both of the invoices paid)
![selection_507](https://user-images.githubusercontent.com/1525066/41706695-18f94ebe-7545-11e8-9649-aad91f56edc9.png)
![selection_506](https://user-images.githubusercontent.com/1525066/41706764-450f3270-7545-11e8-8e46-32ec0697b4f5.png)

2. Go to the Invoice Analysis and see the sum of the product quantity
![selection_508](https://user-images.githubusercontent.com/1525066/41706772-4c2567d2-7545-11e8-81d3-22995cd69c95.png)

#8990 is possibly related even though it has nothing to do with `account.invoice.report`.

To me it seems that this calculation used to work correctly until the commit e890682656b4739f489d34b954a1b1e8d9f78065 by @nim-odoo .

**Comment by farazda1** [comment]
any updates on this please @nim-odoo @Yenthe666

**Comment by celm1990** [comment]
See #27479 can be related

**Comment by celm1990** [comment]
Commit for product quantity solved in 7b87212ea851518a641f65a71dc094cf88507cdc

**Comment by mlaitinen** [comment]
Thanks @simongoffin.
