### ISSUE TITLE
[11.0] Sales Analysis: wrong Amount Invoiced after creating credit notes

### ISSUE THREAD

**Issue by astirpe** [odoo/odoo#25409]
**Impacted versions:**
11.0

**Steps to reproduce:**

- Create a SO with two lines:
-  - _LIne1_: Product: product50, Ordered Quantity: 1.000, Unit Price: 50.0
-  - _Line2_: Product: product12, Ordered Quantity: 1.000, Unit Price: 12.0

- Confirm the SO
- Click on "Create Invoice" (choosing for example "Invoiceable lines")
- Validate the invoice
- Click on "Add Credit Note" (choosing for example "Create a draft credit note")
- Validate the Credit Note

- Go to Reporting->Sales and open the Pivot view
- Enable the following measures:
- - Amount Invoiced
- - Amount To Invoice

- Expand the rows by Product

**Current behavior:**

- Amount Invoiced for product12 is 50.0
- Amount Invoiced for product50 is 12.0

**Expected behavior:**

- Amount Invoiced for product12 is 0.0
- Amount Invoiced for product50 is 0.0

**Comment by nhomar** [comment]
>> (choosing for example "Create a draft credit note")

Did you try the option where the credit note is reconciled automatically?

I think the manual credit note is having for you the expected result (not really sure if expected) but is how it has been working since few years ago.

**Comment by astirpe** [comment]
@nhomar I tried the manual credit note and the result is the present issue.
The problem is the way `amt_invoiced` is calculated. See a proposed fix [here](https://github.com/odoo/odoo/pull/25417/commits/41d1bfdce1afd192999c3e8e645adb57699251a2).

The actual (wrong) behavior is because, for each sale_order_line, the `amt_invoiced` is calculated as the difference between `amount_total` of the **credit note** and the `price_total` of the **invoice line**.

Instead it should be the difference between `price_total` of the **credit note line** and the `price_total` of the **invoice line**.
