### ISSUE TITLE
qweb t-esc does not apply timezone with_context( tz=a_tz) 

### ISSUE THREAD

**Issue by Gyuri77** [odoo/odoo#25402]
Impacted versions: V9.0c  others not tested

Steps to reproduce:
Create an event with start date
create a qweb form to display date with time_zone
<h1 t-field="esemeny.with_context(tz=esemeny.date_tz).date_begin"/>
<t t-esc="esemeny.with_context(tz=esemeny.date_tz).date_begin" />

Current behavior:
   t-field uses the tz but t-esc NOT uses the tz and gives UTC times 

Expected behavior:
t-esc use the tz as t-field
t-field can not put into <t> tag (only in html), so it can not used as parameters for JS because the extra scraptag

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is the expected behavior, as t-esc uses an expression as it's naive about the content. You should use t-field or make the proper conversion in t-esc expression.

Closing as no real issue.

**Comment by Gyuri77** [comment]
t-field can not be used as mentioned above.

It's more elegant and odoo like than with_context():
`timezone('UTC').localize(datetime.strptime(esemeny.date_begin,'%Y-%m-%d %H:%M:%S')).astimezone(timezone('Europe/Budapest')).strftime("%Y-%m-%d %H:%M:%S")`

**Comment by pedrobaeza** [comment]
I don't understand what do you mean by `t-field can not put into tag (only in html)`. You can check some examples of using timezone-aware fields in Qweb in standard in `website_event` module.

**Comment by Gyuri77** [comment]
i tried 
`<t t-field="esemeny.with_context(tz=esemeny.date_tz).date_begin"/>`
 but i got an error:
  "t-field can not be used on a t element, provide an actual HTML node"

**Comment by pedrobaeza** [comment]
That's a non-sense. That tag is a wildcard for `t-if` operations for example, but can't show any value. Use `<span t-field=...` or similar.

**Comment by Gyuri77** [comment]
I mentioned 2 times it's not possible.
I give it to parameter to js code. So if i got my datetime wrapped in anything it's not good.
