### ISSUE TITLE
Records whose external IDs contains spaces are not translatable

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#25408]
Impacted versions:
- 11.0

Steps to reproduce:
- Enable debug mode
- Go to Settings -> Technical -> User Interface -> Views
- Search for "search count" and enable inactive records in the filter
- Edit resulting record, check "Active" and save changes.
- Change website's language to any different of English, e.g. French (Website  -> Configuration -> Settings -> Available languages)
- Open URL /shop and search any text, e.g. "a"

Current behavior:
The string is displayed in English, even though it's translated [here](https://github.com/odoo/odoo/blob/1740b179bfa78dafe7094f1f090f4e42a2b13a5f/addons/website_sale/i18n/fr.po#L3904)

Expected behavior:
Either external ID's containing spaces should be translatable, or such cases should be fixed and forbidden, like [here](https://github.com/odoo/odoo/blob/1740b179bfa78dafe7094f1f090f4e42a2b13a5f/addons/fleet/data/fleet_cars_data.xml#L59), [here](https://github.com/odoo/odoo/blob/1740b179bfa78dafe7094f1f090f4e42a2b13a5f/addons/fleet/data/fleet_cars_data.xml#L131) and [here](https://github.com/odoo/odoo/blob/1740b179bfa78dafe7094f1f090f4e42a2b13a5f/addons/mass_mailing/views/link_tracker_views.xml#L36).

If I manually create an external ID without spaces, the term is translated correctly.

Video/Screenshot link (optional):
![website term not translated](https://user-images.githubusercontent.com/19801181/41743059-7d95012c-7565-11e8-8e7e-e038c65c00ee.png)

**Comment by nhomar** [comment]
We should not have xml_id with spaces AFAICR the title should be changed to "we have official xml_id with spaces" the translation is a consecuence of that.

cc @nim-odoo is this correct?

**Comment by mart-e** [comment]
Hi,

I agree with Nhomar, the external ids with spaces should be corrected, this is not a good way to name its elements.
I am a bit surprised, the only problem is a lack of translation.
It is probably worth checking why the view is not translated and see if we can't improve that too.

**Comment by luisg123v** [comment]
Fixed at:
- https://github.com/odoo/odoo/commit/3c568aec0b46640cf7d02409463a375bd2f2338e
- https://github.com/odoo/odoo/commit/13e14cf76442ba54afe923d35e8eef14ae599e0d

**Comment by luisg123v** [comment]
For the record:
Cases like these are no longer allowed, thanks to https://github.com/odoo/odoo/pull/38139

**Comment by mart-e** [comment]
Thanks for the constraint, it should avoid future issues
