### ISSUE TITLE
[11.0]PoS: Archiving PoS config should be not allowed when session is open

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25407]
Impacted versions: 11.0

Steps to reproduce: Create Pos Config --> Create Session (Do not Close and Post Entries) --> Archive PoS Config --> Continue Selling in Same Session

Current behavior:
![1991](https://user-images.githubusercontent.com/16624719/41740932-35a5101c-75b7-11e8-9924-3f7037fed263.png)

Expected behavior: Archiving PoS Config Should not be allowed If there is any Open Session

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@switch87 has there been any update for this one? 🙏

**Comment by switch87** [comment]
Actually there is nothing that can be done against it, becouse the odoo dB cannot know about existing offline sessions. But in master I am working on a task that will make it as waterproof as it is possible + adding the possibility to download the sales date if something like this happens.

**Comment by Yenthe666** [comment]
I don't know the design of the POS out of my head so just something that came up in my head (which might be very wrong/naive 😉)
We could write away a value the moment a POS session is started or stopped, no? The moment Odoo switches between Backbone.js and Odoo. Then check on that when the user wants to archive a POS session.

Either way, that would still result in a db scheme change which means not for stable. As you're talking about a task for master I believe we can close this one. I still hope my feedback has any value.

**Comment by switch87** [comment]
@jenthe666 this value is already there :) but becouse sessions can work without communication with the db, a session can be closed in the backend and still be open on a offline point of sale. This makes things more complicated with moments. I can look if I can backport some of the code as a fix. So I will leave it open for now.

**Comment by Yenthe666** [comment]
Awesome! Thank you for the feedback and for looking further into it, awesome job.

**Comment by sswapnesh** [comment]
Its seems this will be handled in https://github.com/odoo/odoo/pull/36279

**Comment by pedrobaeza** [comment]
This has been handled on master branch other way in #40500, so closing.
