### ISSUE TITLE
[12.0/Master] Multi-website - user_id relation to allowed website is Many2one, Should be Many2many like Allowed Companies

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#25413]
<h1>Impacted versions:</h1>
12.0/Master
<h1>Steps to reproduce:</h1>

- Go to master-multi-website-jov branch in runbot
- Go to Settings > Users >> [Your Username Here] > Preferences Tab
- Under Multi-website section there is a Many2one field for registered_on_website_id - this allows you to assign one user to only a single website.

<h1>Current Behaviour:</h1>
This setup allows for only assigning a user to a single website. There are many use-cases where this will not be enough. 

For example, a retailer who chooses to have a unique website_id per country or region, in this case it would be best to provide a login for all websites, and pick the region based on the Geo-IP of the user for example (see www.hp.com as an example of what I mean here).

Another example would be a retailer selling on multiple different websites for different purposes (eg. one website is for electronics goods of a particular brand, another is for electronic goods of another brand, and so on). There are many of our customers that are trading companies that have this exact requirement in Hong Kong, and i'm sure this is not the only country where this requirement is commonplace.

In the above example there might be a single distributor that is the authorised sole distributor (as an example) for Sony, Lenovo, Logitech, etc. In this case they would be selling each of these brands representing the brand within that region (eg. Hong Kong) and therefore appearing as the brands website within their region. They would sell only that brands products on a particular website_id, however for accounting purposes all those websites would relate back to a single company_id.

Bringing Magento in as an example, they can handle both of these use-cases using the following structure:

Website > Store > Store View

Website would be the base website_id in this example, and Store could be multiple regions within this website (take the first example with hp.com for reference), each store could have different content depending on the region. Store View in this example (within a Magento context) could be used to handle multi-languages within each store (for example if your store was in Belgium it could also have the languages of Dutch, French, and German).

In the second use-case, I mentioned, Website would be the base website_id for each brand. It would have a single Store, and perhaps multiple Store Views (as languages).

In Odoo we can have multi-language per website_id, however without the many2many on registered_on_website_id, I don't understand how we can achieve different content for different regions using a single user login (hp.com as an example). We would need the user to be able to be logged in throughout multiple website_id's in a single login session and simply pick the website_id based on the region they select (auto-selected by Geo-IP, or manually selected by a region switcher link).

<h1>Expected Behaviour:</h1>

- Use a Many2many for storing the allowed websites for this user, in the same way you use a Many2many to store the allowed companies for this user.
- We should have a way to assign one user to many websites
- We should have a way to assign one company to many websites
- We should have a way to assign one partner to many websites
- We should have a way to assign one product, website category, etc. to many websites
- We should have a way to assign one sales team to many websites, and one salesperson as the lead contact for many websites.
- Email alias_domain (res.config.settings) should be configurable company-wise, and website-wise, not just instance-wise as it is now.
- Themes should be able to be assigned/installed independently per website_id, each with it's own set of translations per website_id (this may already be on the roadmap i'm guessing).

<h1>Link to Code in Devbranch:</h1>
Here's a link to the model in odoo-dev:
<a href="https://github.com/odoo-dev/odoo/blob/master-multi-website-jov/addons/website/models/res_users.py#L18" target="_blank">https://github.com/odoo-dev/odoo/blob/master-multi-website-jov/addons/website/models/res_users.py#L18
</a>

<h1>NOTES:</h1>
It's great to see Odoo moving in the right direction in terms of multi-website support, however I feel it would be better to start off on the right foot in terms of the approach and structure of the multi-website implementation to allow for less headaches when migrating to newer versions of Odoo, and to also provide as much flexibility as possible in terms of implementation options for multi-website support.

With some of the above features I believe it will be possible to create some truly enterprise grade websites to handle global web presences for MNC's and brands/manufacturers looking to reach an international audience with localisation-specific content (not just translations of the same content).

**Comment by pedrobaeza** [comment]
I ping @jorenvo, but issues on dev branches shouldn't be notified here. You can point it on the PR or in the commit.

Closing this.

**Comment by lukebranch** [comment]
ok, will do, thanks. I will comment on the PR or commit notes from now on.
