### ISSUE TITLE
Sales Order Line: Invoice status wrong if invoice is in state draft

### ISSUE THREAD

**Issue by BT-sschmid** [odoo/odoo#25418]
Impacted versions: 9.0, 10.0, 11.0 

Steps to reproduce:
Create a Sales Order with one line and validate. The invoice-status of the SO will become "to invoice".
Then create a Invoice but do not confirm. The invoice-status will become "fully invoiced".

Current behavior:
invoice status is fully invoiced if invoice in state draft

Expected behavior:
invoice status is still to invoice if invoice in status draft

A possible fix is adding the state "draft" to https://github.com/odoo/odoo/blob/16fb8f0a7500218b7d53e89dcaaec3c5fb7d7eb5/addons/sale/models/sale.py#L605

**Comment by pedrobaeza** [comment]
That's incorrect, as you have already made the invoice, which is the important part. If not, until you validate the invoice, you will be able to invoice again the same SO line multiple times. You have another document (the invoice) for telling you that you have to validate it for continuing the business flow.

Closing as no correct interpretation on how this works, but no real issue.
