### ISSUE TITLE
The names of some products change in english-turkish language change.

### ISSUE THREAD

**Issue by bariserdogan** [odoo/odoo#25414]
Impacted versions: Odoo V11 

Steps to reproduce: Inventory -> Product -> Search product ( like "deneme ")  
                                After;  Preferences -> Language
                               
Current behavior: When we change Odoo's language, the product name is different. Language There is no problem when it is in Turkish, but when the language is English, it gets the same name as the other product. 

Expected behavior: We expect no change in product name

![turkish language](https://user-images.githubusercontent.com/17798258/41761718-03926940-7601-11e8-9d17-c6375a3334dd.PNG)

![english language](https://user-images.githubusercontent.com/17798258/41761741-107cf4fe-7601-11e8-98b9-f69f988583da.PNG)

Video/Screenshot link (optional):

**Comment by bariserdogan** [comment]
Also, when the language is English, I am changing the name and it does not change in Turkish version




![inkedfrom eng to turkish_li](https://user-images.githubusercontent.com/17798258/41768330-93bf061e-7614-11e8-8e92-4f03d2354fbf.jpg)



![to turkish](https://user-images.githubusercontent.com/17798258/41768337-9a3f2f1e-7614-11e8-97ed-f7c0b51e8747.PNG)

**Comment by gdgellatly** [comment]
Yes odoo cannot automatically translate product names. You need to click
the little icon in that field and translate manually.

**Comment by pedrobaeza** [comment]
Indeed, each product keeps "several names", depending on the language, so if you want to have the same translation on each language, you have to make sure you have the same content, clicking on the world globe icon for accessing the translations of that field.

For more information, please search or ask on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

Closing as no real issue.

**Comment by bariserdogan** [comment]
I'm very pleased for your informations.

Best Regards
