### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by husm91** [odoo/odoo#25447]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by husm91** [comment]
hello everyone

**Comment by husm91** [comment]
I can not cancel the invoice
![screen shot 2018-06-23 at 10 56 01 am](https://user-images.githubusercontent.com/40514868/41807224-0ecaa07e-76d4-11e8-88cd-36a955033aaf.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by husm91** [comment]
im sorry
