### ISSUE TITLE
Vietnamese Thousands Separator Error

### ISSUE THREAD

**Issue by leotran** [odoo/odoo#2545]
After config Decimal Accuracy for Product Price is 0. I enter Unit Price on Product or Quotation form, ex: 80.000. It become 80 when it saved. If Decimal Accuracy for Product Price is not equa 0 (ex: 2), it's work!
![selection_001](https://cloud.githubusercontent.com/assets/7899946/4333681/c30d59e0-3fe3-11e4-804a-5a9629045df9.png)

![selection_002](https://cloud.githubusercontent.com/assets/7899946/4333686/ca498184-3fe3-11e4-9028-d3eea85fa1b2.png)

**Comment by Adoniasv** [comment]
Is a Bug.

Change this file:

addons/web/static/js/formats.js

Find this line in function instance.web.parse_value:



```javascript
  case 'float':          
     tmp = Number(value); 
     if (!isNaN(tmp))
        return tmp; 
```

and change for this (Coment whit //)
```javascript
 case 'float':          
     //tmp = Number(value); 
     //if (!isNaN(tmp))
        //return tmp; 
```

is working for us

**Comment by mart-e** [comment]
Hello,

Is it still the case? The decimal separator is specified on the language and it can be accepted on a pull request if a change is needed.

**Comment by Yenthe666** [comment]
Hi @leotran,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
