### ISSUE TITLE
[11.0] Refresh data after edit

### ISSUE THREAD

**Issue by aitorbouzas** [odoo/odoo#25463]
Impacted versions:
11.0

Steps to reproduce:
1. Get inside a form view
2. Edit something in a one2many tree without `editable="bottom"` or `editable="top"`. This edition may update something in the parent form view like, for example, creating a new register in another one2many field (in the parent model).
3. Finish the editition hitting the button save.

Current behavior:
Data is not reloaded and new register is not added in the another one2many field.

Expected behavior:
It should show the newly created register.

**Comment by pedrobaeza** [comment]
This is another forbidden use: you can't add via onchange something outside your own record (the one2many one in this case), or you will have these unexpected side errors. You should check your designs, as they are not using Odoo paradigms (or constraints), and thus the framework is not adapted to them. This might change in the future, as it can be needed in some business cases, but it's not possible today.
