### ISSUE TITLE
Forced availability on Delivery Order causes new procurement with multiple lines on SO

### ISSUE THREAD

**Issue by tr3ysmith** [odoo/odoo#25488]
Impacted versions:
Version 11

Steps to reproduce:

1. Create an SO with the same product on multiple lines with different qty's. This is used when doing sections of a quote, like products in different rooms.
2. Confirm the SO, and confirm the Pick.
3. For the DO, force the reservation manually using Detailed Operations. This is needed when the procurement fails for unknown reasons.

Current behavior:
The link between the delivery lines and the product order lines gets lost and the system simply delivers everything to the first order line in the SO. So if you have the following:
Line 1 (Product A) - qty 3
Line 2 (Product A) - qty 5
Line 3 (Product A) - qty 6

Then your delivered column will show:
Line 1 (Product A) - delivered qty 14
Line 2 (Product A) - delivered qty 0
Line 3 (Product A) - delivered qty 0

This then tells the system to generate a procurement for the missing lines (11 qty) and therefore delivers more than needed.

Expected behavior:
Odoo will attempt to fill the delivered column of line 1 until it equals the ordered qty, and then search for more lines in the SO to add the rest of the delivered qty to. Preventing a new procurement.

**Comment by pedrobaeza** [comment]
@jco-odoo can you take a look to this?

**Comment by jco-odoo** [comment]
It is indeed even in the comment in the code that we could improve it.  There is no pr for this somewhere?

**Comment by sle-odoo** [comment]
we could improve [this part](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_picking.py#L634) but i don't want to introduce a split of the move lines

i'll see if i can do something

**Comment by jco-odoo** [comment]
You could do a first filter where qty_done < product_qty and fallback after.  It is not that unlogical to split.  It is done after.
