### ISSUE TITLE
Widget of a handy link for address on Phone or web

### ISSUE THREAD

**Issue by my1649** [odoo/odoo#25486]
Impacted versions: 11.0 or all

Steps to reproduce: NIL

Current behavior: Not available (I guess)

Expected behavior: When a field code it with <field name ="xxx" widget="map"/> and it will display as a hyperlink for computers in google map. Perhaps asking the map application launch on phone may be better. Apply Map on iOS, Google Maps on Android, I dont know.   

Video/Screenshot link (optional):
This may be a wishlist item, but since there are so many handy widget for users. I am wondering there is any for map, especially on phone.

**Comment by pedrobaeza** [comment]
That should be handled intercepting the URL by the mobile OS itself. AFAIK, nothing special can be done on the other side.

**Comment by Yenthe666** [comment]
Indeed, that is controlled by the mobile OS, not by the website / ERP.

**Comment by my1649** [comment]
Understood what you guys mean, perhaps having a link to recognize?
For example, input an address of Odoo Sales Office;
street1=Avenue Edmond Van Nieuwenhuyse, 6  
street2=3rd Floor (Serenitas building)
and it creates a link for street1 likes, http://maps.google.com/?q=Avenue+Edmond+Van+Nieuwenhuyse,+6 
Therefore the browser or phone will recognize its a content for map. Otherwise, its just a text. 
Anyways, its just a little suggestion. 
Cheers!
