### ISSUE TITLE
mrp_account: wrong inheritance

### ISSUE THREAD

**Issue by aborow** [odoo/odoo#25494]
Impacted versions:
EE 11
Steps to reproduce:

Create a view that inherits from "product.product_template_form_view" and update.

Current behavior:

"mrp_account.product_product_inherit_form_view_cost_structure" view is inheriting "product.product_template_form_view". This will throw an error as the mo_count field will not be recognized.

Expected behavior:

"mrp_account.product_product_inherit_form_view_cost_structure" view should inherit "mrp.product_template_form_view_bom_button" because that's where the "mo_count" field is defined.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't see the problem. Can you attach a minimal demo module that reproduces the problem?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this issue as there has been no feedback/extra info for this issue.
Don't hesitate to add more info or open a new issue with more information.
