### ISSUE TITLE
Barcode Interrupt Generated Without Device

### ISSUE THREAD

**Issue by jordhanbinnoushad** [odoo/odoo#25519]
Impacted versions:11.0

Steps to reproduce:

Current behavior:On the Point Of Sale interface or kiosk mode , user is able to create barcode interrupts by pressing number keys on the keyboard even without a device is connected.It may lead to create fake check in or check outs and alteration in POS billing.

Expected behavior:The barcode processing should be invoked only by the scanner or the Specific barcode device.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What do you mean by "barcode interrupts"?

**Comment by jordhanbinnoushad** [comment]
the key presses acts exactly like a barcode scanning operation
when i press 3 keys the value of the keys are taken as input from a barcode scanner

**Comment by pedrobaeza** [comment]
Yeah, but that's something normal, as there are no other way of distinguishing a barcode operation except the frequency of the inputs and possible the final indicator, but what's the problem with that?

**Comment by jordhanbinnoushad** [comment]
I thought Bar code signals can be distinguished from regular key strokes

**Comment by jordhanbinnoushad** [comment]
ok then , May I close this issue?

**Comment by pedrobaeza** [comment]
Closing it then.

**Comment by sswapnesh** [comment]
I have experienced same and some time it is frustrating.
![98](https://user-images.githubusercontent.com/16624719/42049382-6b338d8c-7b23-11e8-944f-bcb9ac41b880.png)

**Comment by pedrobaeza** [comment]
But that's a different issue. In that screen barcode scanning should be disabled. I think this has to be handled in a new issue.
