### ISSUE TITLE
TransientModel, _inherits and followers

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#25511]
Impacted versions:
11.0
Steps to reproduce:
I created a TransientModel like this:
```
class HrApplicantResult(models.TransientModel):
    _name = 'hr.applicant.result'
    _inherits = {'hr.applicant': 'applicant_id'}

    applicant_id = fields.Many2one('hr.applicant', required=True, ondelete='cascade')
    # other fields
```
And the view:
```
        <record id="hr_applicant_result_form" model="ir.ui.view">
            <field name="name">hr.applicant.result.form</field>
            <field name="model">hr.applicant.result</field>
            <field name="inherit_id" ref="acft_hr.crm_case_form_view_job"/>
            <field name="mode">primary</field>
            <field name="arch" type="xml">
            </field>
        </record>
```
Current behavior:
Warning : "For this kind of document, you may only access records you created yourself. Document: hr.applicant.result"
Because on read_followers method (mail/controllers/main.py), check_access_rule is called with the wrong res_model (hr.applicant.result instead of hr.applicant). 
Seems to be related to: https://github.com/odoo/odoo/pull/16473

Expected behavior:
show followers of the related record (applicant_id)
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a limitation over current ORM framework: you can't use inheritance by delegation with full guarantees on a transient model.

You can bypass this limitation overwriting methods like `check_access_rule` or similar ones, but this is not expected to be fixed on core MO, as it's a very rare use case.

@rco-odoo can you confirm my comments and thus close this?

**Comment by Linekio** [comment]
Ok I understand.
I can also fix by overriding read_followers method:
```
from odoo import http
from odoo.addons.mail.controllers import main

class MailController(main.MailController):

    @http.route('/mail/read_followers', type='json', auth='user')
    def read_followers(self, follower_ids, res_model):
        if res_model == 'hr.applicant.result':
            return super(MailController, self).read_followers(follower_ids, 'hr.applicant')
        return super(MailController, self).read_followers(follower_ids, res_model)

```
