### ISSUE TITLE
[Wishlist] Purchase Responsible `user_id`

### ISSUE THREAD

**Issue by SButko** [odoo/odoo#25525]
Impacted versions: All
Steps to reproduce:
**Current behavior:**

Currently, `create_uid` is shown as Responsible in Purchase Orders and we can not change it manually.
Moreover, `create_uid` is not displayed in a form or tree views, it's allowed to filter by this field only.
Purchase Analysis is also built using `create_uid` as Responsible.

**Expected behavior:**

Would be great (in future versions, I guess) to have a dedicated field (e.g. `user_id`) in PO, such as in other similar models, for assigning Responsible user.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e can you perhaps add this as an internal feedback / suggestion?

**Comment by pedrobaeza** [comment]
I agree this can be a good improvement.

**Comment by mart-e** [comment]
Hi,

It was already done in saas-11.1 at cad52c81e396430817c470cacf702245a34f3e74, it will be in the future version 12.
