### ISSUE TITLE
Attendance Graph Shows Inconsistant Data

### ISSUE THREAD

**Issue by jordhanbinnoushad** [odoo/odoo#25520]
Impacted versions:11.0

Steps to reproduce:

Current behavior:When we take the attendance report as Graph.It shows wrong data for the persons.ie the attendance of Aaron is Given to Ben , Ben's Attendance is given to Catherine etc.We have this problem with all the modules.

Expected behavior:The Graph should display attendances according to the employee names.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
We need more information for understanding the problem. Please try to reproduce the problem on runbot (https://runbot.odoo.com - admin/admin), and put here all the detailed steps to reproduce the problem and even screenshots/video.

**Comment by jordhanbinnoushad** [comment]
Installed the attendance module
then recorded some attendances
on reports selected linegraph

**Comment by pedrobaeza** [comment]
Still not enough information. Please provide screenshots, videos and detailed steps (which includes the records you add).

**Comment by jordhanbinnoushad** [comment]
http://codingfreek.blogspot.com/2018/06/blog-post.html i have uploaded two screenshots here please visit

**Comment by pedrobaeza** [comment]
But what is the error? You can attach here images, and why don't you provide more information? If this continues this way, I will close the issue as it doesn't bring anything useful for finding a possible issue.

**Comment by pedrobaeza** [comment]
Are you able to reproduce this problem on runbot? This can be something in your system.

**Comment by jordhanbinnoushad** [comment]
ooh 
let me try making it in runboot

**Comment by jordhanbinnoushad** [comment]
yes , the error is occuring in the runbot also

**Comment by jordhanbinnoushad** [comment]
![screenshot-2018-6-28 attendance analysis - odoo 3](https://user-images.githubusercontent.com/33719095/42026671-600fcc10-7ae5-11e8-93e8-b048fcbe9c20.png)
![screenshot-2018-6-28 attendance analysis - odoo 2](https://user-images.githubusercontent.com/33719095/42026673-60b77aaa-7ae5-11e8-9747-3b7c7fd5005e.png)

**Comment by pedrobaeza** [comment]
OK, thanks for putting the details.

@ged-odoo which one can take a look to this?

**Comment by mart-e** [comment]
Hi,
Sorry for the lack of reply.
I have just tried to reproduce on a runbot but it seems to work fine now in your scenario.
I am then closing this issue but in case it still happens, let me know and we can investigate more.
