### ISSUE TITLE
[11.0] Creating a Picking is not respecting the 'Draft' and 'Waiting' states

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25528]
####Impacted versions:
11.0

#### Steps to reproduce:
- Create a picking
- Save it

#### Current behavior:
- The picking state is set to **Confirmed** or **Assigned**
- The **Draft** and **Waiting for Availability** states are completely jumped
- The _Initial Demand_ and the _Reserved_ are never set, and the picking does not do the reservation. 
- Locations nor type can't be changed, as they're only editable when the picking is in draft.

#### Expected behavior:
- When saving a Picking it should be set to 'Draft' or 'Waiting for Availability' instead of jumping to 'Confirmed'

**Comment by gustavovalverde** [comment]
@sle-odoo this is odd. And I'm supposing this is not a wanted behavior.

**Comment by sle-odoo** [comment]
@gustavovalverde i think you're talking about "immediate transfers", which bypass the reservation. If you want the old (and right) behaviour, you should use the top right button on the vignette of the picking type and hit "planned transfer".

**Comment by gustavovalverde** [comment]
There should be a way to:
(a) Change that default per picking type (there's no way to do it without coding)
(b) Move that to an easier place than the picking kanban (who opens the kanban options to create a picking? :-)

**Comment by sle-odoo** [comment]
it is already taken care of in saas11.4 :)

**Comment by gustavovalverde** [comment]
So this is also causing this issue: https://github.com/odoo/odoo/issues/25289 I'll be closing that one if it's been taken care.

**Comment by gustavovalverde** [comment]
@sle-odoo is this already in master (or 11.4) to be tested?

**Comment by sle-odoo** [comment]
yep
