### ISSUE TITLE
Odoo shouldn't mark all files for garbage collection

### ISSUE THREAD

**Issue by tahaziadeh** [odoo/odoo#25522]
https://github.com/odoo/odoo/blob/f6d36d81f7a601eb8902552d08915cb493d917f6/odoo/addons/base/ir/ir_attachment.py#L115

After uploading attachment, if the attachment location is configured as "file",  the file is always marked for deletion by the vacuum job. 
This is an issue in production databases where users will find their files deleted after 1 day (autovacuum schedule)
The reported line shouldn't be there and must be in the except block.

**Comment by pedrobaeza** [comment]
AFAIK, that's a temporary file. I haven't found any data loss due to that. Can you be a bit more specific about where do you experiment this problem?

**Comment by tahaziadeh** [comment]
Thank you @pedrobaeza for your reply, here is my situation:
I have built a custom module which is responsible for managing custom data model "business.entity"
```
# Business model
class Business(models.Model):
   _name = 'business.entity'
   _description = 'Business entity'
   name = fields.Char('Name Of Business', translate=True)
   website = fields.Char('Website')
   email = fields.Char('Email')
   attachment_ids = fields.One2many(
       comodel_name='business.attachment',
       inverse_name='business_id',
       domain=lambda self: [('res_model', '=', self._name), ('type_of_attachment', '=', 'image')],
       string='Attachment',
   )
```

As you see we have the field `attachment_ids` related to the model `business.attachment`. 
The `business.attachment` model's class an inherited class from 'ir.attachment' like the following:
```
class Attachment(models.Model):
   _inherit = 'ir.attachment'
   _name = 'business.attachment'
   business_id = fields.Many2one('business.entity', 'Business', required=True)
   type_of_attachment = fields.Selection([('image', 'Image'), ('pdf', 'Pdf')], default='image', required=True)
```
The above is a fully working code, attachments are successfully saved and the management is fully working
Then after one day - and especially after execution of the autovacuum job - all uploaded images/files disappeared from the filestore, but the corresponding records still available in the db

Proposed solutions:
1- Remove the line `self._mark_for_gc(fname)` 
    Removing the above line will disable marking the attachment for garbage collection just after writing it
2- The attachments basically registered in 'ir.attachment' data table are whitelisted  through the query 
`cr.execute("SELECT store_fname FROM ir_attachment WHERE store_fname IN %s", [names])`. That's why the business attachments are not whitelisted since it is being registered in other table `business.attachment`.
Possible workaround :
 Use **delegation** inheritance instead of prototype inheritance as following:
```
class Attachment(models.Model):
    _inherits = {'ir.attachment': 'attachment_id'}
    _name = 'business.attachment'
   business_id = fields.Many2one('business.entity', 'Business', required=True)
   type_of_attachment = fields.Selection([('image', 'Image'), ('pdf', 'Pdf')], default='image', required=True)
```
This workaround works even if we don't apply the first solution. Though it was not expected to have such side effect only in case of prototype inheritance

**Comment by pedrobaeza** [comment]
@tahaziadeh thanks for the details, but as you have already found, twisting core models can have these side effects, and it's something that's not avoidable, as this is part of a pluggable system. But the good thing is that you have the source code for studying and inheriting what you need to adapt the system to that twist.

On the proposed solutions, I would go for the delegated inheritance, which is the safest for avoiding problems on next versions/updates, with other modules, and so on.

**Comment by razvanioan** [comment]
**Update**

By the end the problem is actually in the way I was updating those attachment fields, meaning through a wizard (so Transient Model) where I've used writable related fields to the selected stock move line, which ended up in linking the attachments to the transient model instead of stock move line persistent one ...

---

I've just came across to the same problem, with a customer which went to production and now is reporting that the attachments they're adding to some custom fields we've added (M2M directly to `ir.attachment`) are gone ...

This is crazy if you ask me!

How can we avoid this ? As I didn't find yet (but I will continue to look for) where in the code where the files are being removed from 'checklist' folder (which is meant for GC) ...

As an example, this is what I have in my code, and the attachments are not being kept, which is not ok from my point of view. How to avoid deleting them ?

```python
class StockMoveLine(models.Model):
    _inherit = 'stock.move.line'

    eg_doc_ids = fields.Many2many('ir.attachment')
```
