### ISSUE TITLE
Multicompany option switches off by itself

### ISSUE THREAD

**Issue by kesturbo** [odoo/odoo#25538]
Impacted versions: Odoo 11 Community 

Steps to reproduce:
It happens suddenly. I don't know how it can be reproduced.
Current behavior:
I have few users with MultiCompany option switched on. After a while - this option switches off by itself. This happens for all users, even if user was logged off from the system.
Expected behavior:
This should not happen.
Video/Screenshot link (optional):
![screen shot 2018-06-29 at 12 56 07](https://user-images.githubusercontent.com/3963352/42084190-0cef9a60-7b9e-11e8-8974-1f0d91b6ae04.png)

**Comment by hbto** [comment]
Whenever you apply any configuratión y the settings, All users even Admin are kicked off that group.

**Comment by kesturbo** [comment]
Is there any way to fix this issue ?

**Comment by hbto** [comment]
Steps to reproduce:

- Create two companies,
- Set your users as multicompany users.
- Go to General Settings.
- Enable Multicurrency and save the settings.
- Wait and check the Group for MultiCompany.

Result: Group is blank all users were kicked off the group even admin.

Regards

**Comment by kesturbo** [comment]
Any ideas how to fix ?

**Comment by Yenthe666** [comment]
Seems to work fine on the very last build of Odoo 11.0 community? Can you reproduce it on runbot.odoo.com and possible make a video?

**Comment by kesturbo** [comment]
my odoo was installed 1 week ago. Things happened same, as @hbto explained. 
Changing any settings affects on the problem.

**Comment by pedrobaeza** [comment]
This is not an issue, but the intended behavior (which doesn't mean that is the desired behavior). Let me explain: there are several options that are available at configuration level. One of those is the multi-company support:

![seleccion_020](https://user-images.githubusercontent.com/7165771/42088034-66fe13c0-7b98-11e8-82ff-0e8f60595f7e.png)

That settings are taken directly from groups definition.

When you click on "Apply" on that screen, then all settings that belongs to security groups are applied to all users, as this rule is considered a general one.

Someone can argue that if you have it enable/disabled before by user, it shouldn't be changed, but currently there's no way to know if that setting was changed manually user per user or it's a result of a previous "batch operation" through these settings.

Another possible argue is that if you don't change the check value, it shouldn't be reapplied unconditionally, but in this case I think there are technical limitations on how the settings are handled. This is the way to go IMO for improving current situation, but I'm pretty sure this can't be handled on stable.

@mart-e @odony I summon you for asking if you are aware of this situation (I suppose it does), and if there's something that can be changed, and this is really not ideal.

**Comment by fclementic2c** [comment]
I did a OPW on this some time ago and this was Odoo answer.
But this is really a pain.

*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com



Le ven. 29 juin 2018 à 12:38, Pedro M. Baeza <notifications@github.com> a
écrit :

**Comment by pedrobaeza** [comment]
@fclementic2c do you mean that my answer is equal to the one you got from the support team?

**Comment by fclementic2c** [comment]
yes

*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com



Le ven. 29 juin 2018 à 15:03, Pedro M. Baeza <notifications@github.com> a
écrit :
