### ISSUE TITLE
onchange globally "en-dirties" all secondary records of modified 2many

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#25533]
You'll find...
- Impacted Versions
- Steps to reproduce
- Current Behaviour
- _Undesired side effect_
- Expected behaviour
- _Further analysis_ (second post)

### Impacted versions:
V10, V11, master

### Steps to reproduce:
1. Chose a `ir.model` record for testing.
2. Add the below inheritance.
3. Create one custom field on your `ir.model` record + save (don't set it readonly)
4. Change the `ir.model`'s `name`-property
5. Save

```python
# Not a sensical use case
# Just minimal code to replicate
class IrModel(models.Model):
    _inherit = ['ir.model']

    @api.onchange('name')
    def _onchange_mapped_model(self):
        for fld in self.field_id.filtered(lambda f: f.state == 'manual'):
            fld.update({'readonly': True})
```

### Current behavior:
Because of ...
https://github.com/odoo/odoo/blob/2774e3b4a82f3c0ea94faff8facb7c4ee5ce7b48/odoo/models.py#L5524-L5532
... this onchange returns to the web client ...
```
field_id : Array(46)
0: [5]
1: (3) [1, 4740, {…}]
2 : (3) [1, 4739, {…}]
3 : (3) [1, 4738, {…}]
...
45 : (3) [1, 4805, {…}]
```

... which hits ...
https://github.com/odoo/odoo/blob/2774e3b4a82f3c0ea94faff8facb7c4ee5ce7b48/odoo/addons/base/ir/ir_model.py#L587

### Undesired side effect: 
An unnecessary write on `2many` causing misleading `write_date` entries.

### Expected behavior:
Only the effectively dirty secondary values will be written to. The rest should remain untouched.

**Comment by blaggacao** [comment]
Meanwhile, here is strategy to create a workaround for this situation: https://github.com/OCA/product-variant/pull/49/files#diff-f194b515e11db9b5f1384afb6c3db651R21
It seems, https://github.com/odoo/odoo/pull/10557 got close into this direction.

**Comment by pedrobaeza** [comment]
I don't get the problem. Please focus on what is the real problem, without excessive unneeded details.

> you need at least one custom field

You need for what?

**Comment by blaggacao** [comment]
@pedrobaeza I tried to contact you on tecnativa's phone number (+34 91 216 38 80) to explain, as I think you probably just overread the relevant details. I reformulated, let me know if it is clearer?

**Comment by blaggacao** [comment]
@Yenthe666 Could you double check if the problem @pedrobaeza exposes is on the sender or the receiver side? I think I did reasonably well and don't understand what @pedrobaeza could have possibly not understood.

**Comment by blaggacao** [comment]
PS... Someone with the power please delete this unproductive metadiscussion starting from here: https://github.com/odoo/odoo/issues/25533#issuecomment-401277812

**Comment by blaggacao** [comment]
I close this in favor of https://github.com/odoo/odoo/issues/25547 which should be clearer. 

@pedrobaeza If there is any problem of understanding, please let me know here in order not to clutter the issue report with unproductive meta-discussions. Thanks for your kind collaboration!

**Comment by Yenthe666** [comment]
@blaggacao for me it is reasonably documented. To me it boils down to:
"An unnecessary write on 2many causing misleading write_date entries." which means the ORM is doing a write to many which means performance related. Correct?

 I think it is great to have a functional case that is written out that explains on a functional level what is wrong, not just technical though. Nevertheless, if @pedrobaeza doesn't understand it it doesn't matter who's fault it is. The conclusion is that both persons should try to communicate untill they both understand it, no? 😄 

I wouldn't take it too personally. @pedrobaeza can be quite short / harsh in his answers, I've noticed it too, so I don't think it is personal but rather personality (or an approach). That being said @pedrobaeza you do seem to like closing off issues or responding very shortly. Can you explain the rationale behind this? I'm curious.

**Comment by pedrobaeza** [comment]
Time :wink:

**Comment by pedrobaeza** [comment]
Time for answering, not for reading.

**Comment by Yenthe666** [comment]
If you've put time into reading and thinking about it all the answering is just a small fraction of the time, no? Even with a detailed answer. But again, it's a personal choice. I personally believe that I should give a detailed answer if the creator of the issue put reasonably time in it. To me that fails like paying the person back the respect he or she deserves. We all like a neat answer after all.

P.s: Don't take it personally Pedro, just wanted to share my vision of it.

**Comment by pedrobaeza** [comment]
@Yenthe666 don't worry, no offense, but I think you are missing the general context and taking prejudices. My answer is very clear and focused (and also short, as my style):

![seleccion_030](https://user-images.githubusercontent.com/7165771/42140764-ac6fdc1a-7da3-11e8-85eb-90c85f9b5ee3.png)

The text of the issue has been modified after that, and the issue closed by the other person, not by me, so don't try to put in my shoulders something that is not my responsibility.

**Comment by Yenthe666** [comment]
@pedrobaeza I'm not blaming anyone, which I specifically mentioned in my previous answer. I think you've missed the part of my message saying:

> P.s: Don't take it personally Pedro, just wanted to share my vision of it.

I don't get why you're so easily offended. We're all trying to do the same thing and improve stuff, we just have a different vision.
@blaggacao I don't find an answer on the question from @pedrobaeza about "you need at least one custom field" though. Perhaps you can still answer that / mention it in the other thread. Perhaps it sheds some light.
