### ISSUE TITLE
[11.0] 403 Forbidden on existing session of deleted user

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25530]
Impacted versions: 11.0

Steps to reproduce: Create User 'abc' --> login with 'abc' on new Window --> Delete User 'abc' --> Refresh or access `http://localhost:8069/` or  `http://localhost:8069/web/database/manager` on window where user 'abc' was logged in.

Current behavior: Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
```
  File "/home/swapnesh/Workspace/11/odoo/addons/base/ir/ir_http.py", line 108, in _authenticate
    request.session.check_security()
  File "/home/swapnesh/Workspace/11/odoo/http.py", line 1067, in check_security
    if not security.check_session(self, env):
  File "/home/swapnesh/Workspace/11/odoo/service/security.py", line 21, in check_session
    if odoo.tools.misc.consteq(self._compute_session_token(session.sid), session.session_token):
  File "/usr/local/lib/python3.6/dist-packages/passlib/utils/__init__.py", line 295, in consteq
    raise TypeError("inputs must be both unicode or both bytes")
TypeError: inputs must be both unicode or both bytes
```

Expected behavior: `http://localhost:8069/web/database/manager` should open.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Related Issue #23947

**Comment by pedrobaeza** [comment]
Well, I think this extreme case can't be handled better. You can always delete cookies or open a private window on the browser for restarting the situation.

@mart-e I let your final call.

**Comment by sswapnesh** [comment]
I think this can be handled by checking `uid` exists or not in session
