### ISSUE TITLE
"History" link in online_quotation does not point to right ingormation

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#2553]
Steps to reproduce

1.Create a new quotation , then select the value in the field "Quote Template" in the form.

2.Save the record and click on "View Quotation" button that will lead you to the website view

3.Now in this view , click on the "History" link on the left side menu, you will find that it is not displaying the proper content on the page.

See the screenshot attached..
![not_proper_content](https://cloud.githubusercontent.com/assets/7600117/4334765/993d9926-3ff3-11e4-9d30-a0e3f5cf9199.png)

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
