### ISSUE TITLE
Duplicated stock move when mrp repair is cancelled

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#25542]
Impacted versions: 9.0

Steps to reproduce:

- Create a Repair Order
- Cancel the order (in any stage)
- Set to draft
- Follow the workflow until the order is repaired

Current behavior:
When the repair order is complete, it created one move or each time the order was cancelled + 1

Expected behavior:
Only create 1 move

[Video](https://archive.org/details/MrpRepairDuplicatedMove2018062912.59.56)

**Comment by Yenthe666** [comment]
Hi @hmrodrigues,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
