### ISSUE TITLE
Cost Structure Analysis Report issue

### ISSUE THREAD

**Issue by BipinVRathod** [odoo/odoo#25545]
Impacted versions: V11

Steps to reproduce: Product Template form, click on 'Cost Analysis' Smart button 

Current behavior:
If we have multiple variant for product and MO already done for all variants, report does not show the Cost analysis report for all variants.

Expected behavior:
Cost structure report should show for all variants.
Video/Screenshot link (optional):

**Comment by BipinVRathod** [comment]
Enterprise V11

Module : mrp_account

    def action_cost_structure(self):
       #This is the issue
        products = self.mapped('product_variant_id')

        #it should be like this 
         products = self.mapped('product_variant_ids')

        return self.env.ref('mrp_account.action_cost_struct_product_template').report_action(products, config=False)

**Comment by pedrobaeza** [comment]
Please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.

**Comment by BipinVRathod** [comment]
Thanks @pedrobaeza
