### ISSUE TITLE
onchange globally "en-dirties" all secondary records of modified 2many

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#25547]
You'll find...
- Impacted Versions
- Steps to reproduce
- Current Behaviour
- _Undesired side effect_
- Expected behaviour
- _Further analysis_ (second post)

### Impacted versions:
V10, V11, master

### Steps to reproduce:
1. Chose a `ir.model` record for testing.
2. Add the below inheritance.
3. Create one custom field on your `ir.model` record + save (don't set it readonly)
4. Change the `ir.model`'s `name`-property
5. Save

~EDIT: I'm still checking if this only occurs when `web_studio` is installed.~

```python
# Not a sensical use case
# Just minimal code to replicate
class IrModel(models.Model):
    _inherit = ['ir.model']

    @api.onchange('name')
    def _onchange_mapped_model(self):
        for fld in self.field_id.filtered(lambda f: f.state == 'manual'):
            fld.update({'readonly': True})
```

### Current behavior:
Because of ...
https://github.com/odoo/odoo/blob/2774e3b4a82f3c0ea94faff8facb7c4ee5ce7b48/odoo/models.py#L5524-L5532
... this onchange returns to the web client ...
```
field_id : Array(46)
0: [5]
1: (3) [1, 4740, {…}]
2 : (3) [1, 4739, {…}]
3 : (3) [1, 4738, {…}]
...
45 : (3) [1, 4805, {…}]
```

... which hits ...
https://github.com/odoo/odoo/blob/2774e3b4a82f3c0ea94faff8facb7c4ee5ce7b48/odoo/addons/base/ir/ir_model.py#L587

### Undesired side effect: 
An unnecessary write on `2many` causing misleading `write_date` entries.

### Expected behavior:
Only the effectively dirty secondary values will be written to. The rest should remain untouched.

**Comment by blaggacao** [comment]
### Further Analysis:

It seems, https://github.com/odoo/odoo/pull/10557 got close into this direction.
Provides context: https://github.com/odoo/odoo/pull/15336
Reports the "no-self-triggering" limitation: https://github.com/odoo/odoo/issues/2693

@ged-odoo Some time ago: https://github.com/OCA/web/issues/562#issuecomment-282384372

~Ideally the backend and frontend could communicate a command "`KEEP` (`7`)" for those sub values near...~

https://github.com/odoo/odoo/blob/ef0907d5b0858efbf7702c78698d21fadf0149e7/addons/web/static/src/js/views/basic/basic_model.js#L96-L134


Why not use command 0 through 4 to message a more detailed picture to the client?
https://github.com/odoo/odoo/blob/ef0907d5b0858efbf7702c78698d21fadf0149e7/odoo/fields.py#L2112-L2134
 ... after all the backend can infer this entropy first-hand. And let the client keep un-instructed values untouched.

Seems that someone elase already had a problem with this behavior already:
https://github.com/odoo/odoo/blob/8643175d00fb8ac418af15273cdbce32f9946c50/odoo/addons/base/ir/ir_model.py#L204-L207

**Comment by nhomar** [comment]
@all

Closing this because of the official non-support of this feature from here:

https://github.com/odoo/odoo/pull/22531

May be in a future this behavior will not happen.
