### ISSUE TITLE
Better python external_dependencies

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#25541]
The python external dependency mechanism currently tries `import` to determine if the package is available.

While this mechanism works, it has the drawback that it does not help discovering the python distribution that provides the package, nor the minimal required version. An example is package `stdnum` which is provided by the `python-stdnum` [distribution](https://pypi.org/project/python-stdnum/).

Would you be open to somehow using [pkg_resources.get_distribution()](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#getting-or-creating-distributions)?

**Comment by pedrobaeza** [comment]
@KangOl @odony I think you are the most suitable ones to give your opinion on this

**Comment by wtaferner** [comment]
Thank you @sbidoul for bringing this up. We have/had the same issue by automatically install virtual-env in our runbot instance based on this information that we needed to do a mapping for exactly this issue.

**Comment by sbidoul** [comment]
@wtaferner note if you install with pip, there is some support because setuptools-odoo has some [automatic](https://github.com/acsone/setuptools-odoo/blob/master/setuptools_odoo/external_dependencies.py) as well as [explicit](https://github.com/acsone/setuptools-odoo#controlling-setuptools-odoo-behaviour) mapping mechanisms. People tend to forget to declare it in setup.py as not everyone use that method.

So native support in the manifest would help a lot.

**Comment by wtaferner** [comment]
@sbidoul 
Alright, thank you for the pointer.

**Comment by KangOl** [comment]
You can make a PR against master

**Comment by sbidoul** [comment]
@KangOl good! Would you prefer a new key or a semantics change of the existing key?

**Comment by KangOl** [comment]
You can reuse the same key, it will still works for most of the cases

**Comment by sbidoul** [comment]
Closed by https://github.com/odoo/odoo/pull/25549

**Comment by estekadigital** [comment]
Althought I think this PR is a good approach, it is breaking my installation. When I try to install hw_escpos I get "No module named pyusb". 
PyUSB is installed via `pip`, `pip3` and even `apt install python-usb` and `python3-usb`, so the library is there. I tried with all versions of pyusb, even the recommended pyusb==1.0.0b1, pyusb==1.0.0b2 , etc..
