### ISSUE TITLE
[Account]: Traceback in confrim to asset  when click on  change a duration button

### ISSUE THREAD

**Issue by dbi-odoo** [odoo/odoo#2554]
steps for reproduce:
1.go to accounting in  a asset menu 
2.click a confrim to asset button 
3.then click the change duration button  give a tracback
see video
  http://youtu.be/LEKEoD3LxV4
produce  version sass-3,saas-5,7.0, master,8.0,.

**Comment by Yenthe666** [comment]
Hi @dbi-odoo,

I can no longer reproduce this issue with the latest codebase.
This bug has been fixed!

Regards,
Yenthe
