### ISSUE TITLE
[11.0] Payslip 'sum' function won't sum categories

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25554]
### Impacted versions:
11.0

### Steps to reproduce:
- Create a Rule with python code: `result = sum('categories.ALW', from_date, to_date)`

### Current behavior:
- The payslip rule will always be 0.

### Expected behavior:
The `sum` function should also consider categories, making it easier to maintain complex payslips. It's easier to create and maintain payrolls through categories behavior than rule by rule.

**Comment by gustavovalverde** [comment]
cc: @tivisse

**Comment by tivisse** [comment]
Hi @gustavovalverde 

Thanks for the feedback. I don't really like the idea of having to different behaviors if the 'code' parameter starts with 'categories.' or not. 

But we could certainly add a method 'sum_category(self, code, from_date, to_date=None)' that does the trick.

It could be done in stable, but as it is not a critical issue, I'm gonna create an internal task to do it. (Internal link: https://www.odoo.com/web#id=1895658&action=333&active_id=1251&model=project.task&view_type=form&menu_id=4720).

Thanks.

**Comment by tivisse** [comment]
FYI. This has been done in saas-12.5 at https://github.com/odoo/enterprise/pull/4423

Thanks.

**Comment by gustavovalverde** [comment]
Perfect. Thank you for taking the recommendation @tivisse 👍
