### ISSUE TITLE
[11.0] In/Uninstalling a module will take you back to the apps dashboard

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25555]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Uninstall a module

#### Current behavior:
- It takes you back to the main dashboard 

#### Expected behavior:
- Stay on the same module page

**Comment by Elkasitu** [comment]
That is the intended behavior

https://github.com/odoo/odoo/blob/2ab3fa86fe83d507e9e1152ad2a44811af7f55cd/odoo/addons/base/module/module.py#L550-L556

**Comment by Elkasitu** [comment]
The behavior seems the same in 10.0, but I put a pdb near that part of the code and turns out it's never actually ran, if it did it would indeed reload the Apps menu.

I'll take a deeper look tomorrow.

**Comment by sswapnesh** [comment]
We can set `Home Action` to `Apps` which is helpful when there are more apps to Install/Uninstall/Upgrade.

**Comment by mart-e** [comment]
@tivisse didn't you worked on the actions after installing a module some time ago? An educated opinion here?

**Comment by tivisse** [comment]
Dear all, @mart-e 

It is intended to jump on the app switcher each time you install/uninstall an application. The only exception is for some website application where we still define an ir.actions.todo to jump on the /shop page, the /forum page, ...

I'm gonna cancel this issue as this is what was requested by our product owners team. And I'm gonna create a feedback in our internal project to think about a better solution following your concern. 

Thanks for the feedback and have a nice day,

Yannick.

**Comment by frankdans** [comment]
weird...
