### ISSUE TITLE
Apply monkey patch through _register_hook on multi-db Instance. Worker <-> Registry Relationship?

### ISSUE THREAD

**Issue by BT-kaberer** [odoo/odoo#25551]
Impacted versions:
11.0
Steps to reproduce:
It's a general question how to safely apply monkey patches on an odoo instance

  ```
  @api.model_cr
    def _register_hook(self):
        """ MonkeyPatch method only when module is installed on the DB.
        The original function pointer to name_get is stored in 'origin'
        attribute.
        The patch need to be removed when module is uninstalled. This is
        done in the uninstall hook during runtime. No server restart
        needed.

        """
        res = super(ResPartnerExt, self)._register_hook()

        @api.multi
        def name_get(self):
            #.....
            return res

        origin = getattr(Partner.name_get, 'origin', None)
        if origin != name_get:
            Partner._patch_method('name_get', name_get)
            _logger.info('ResPartner.name_get method patched!')

        return res
```

Also there exist a uninstall hook, to remove the monkey patch during runtime:

```
def uninstall_hook(cr, registry):
    # If the method was patched we revert it during runtime
    if hasattr(Partner.name_get, 'origin'):
        Partner._revert_method('name_get')
```

To summarize:
1) Monkey patch only applied if the module is actually installed on the DB
2) Monkey patch will be removed during runtime when module is uninstalled

But:
Now imagine a multi DB instance where the monkey patch module is installed on DB1 but not on DB2.
This seems to work if the DB's are separated (--dbfilter) and the user cannot switch the DB manually.

However there is a case that is problematic:
So the user login to DB1 with the monkey patch applied. Then logs out and changes to DB2. The registry is reloaded but the monkey patch is still applied on DB2.

I am not fully aware of the worker-registry relationship, so my question might seem naive. Any hint to figure this out is kindly appreciated!

**What is the cleanest way to apply monkey patch on multi worker/multi DB instance without side effects?**

Thanks for your explanations.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
