### ISSUE TITLE
[9.0] Produce more than what we initially planner does not update the consumed list of materials in Produce wizard

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#25572]
## Impacted versions:

9.0

## Steps to reproduce:

1. Create a manufacture Order to produce (qty to produce 2.0)
2. Reserve and then click the Produce button
3. Produce 3.0 instead, one more product than the initially planned.

## Current behavior:

1. Quantities of the lines to consume in the Produce wizard are not updated 

## Expected behavior:

I think that this lines should be updated to reflect the materials for produce 3 products. 

This because this works for the case when we produce less quantity, for example if a pĺanned 2.0 but really produce 1.0 then the list of products to consume is updated to match the new product quantity. 

In addition, I have tested this cases in version 11.0 and in both more/less quantity produced updated the list of consumed materials, but in version 9.0 this does only apply to the produce more than planned case.

Video  https://youtu.be/e2dJthLKwWM

**Comment by zaoral** [comment]
FYI opw 1863632

**Comment by Yenthe666** [comment]
Hi @zaoral ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

P.S: I hope you got feedback through the OPW.

Regards,
Yenthe
