### ISSUE TITLE
'async' are reserved keywords in python 3.7

### ISSUE THREAD

**Issue by ZOOUQinn** [odoo/odoo#25578]
According document of 'What’s New In Python 3.7', 'async' are reserved keywords now.

Code in line 105 of 'odoo/addons/base/ir/ir_qweb/assetsbundle.py' 
`def to_html(self, sep=None, css=True, js=True, debug=False, async=False, url_for=(lambda url: url)):`
will throw SyntaxError out if we launch odoo with this update python.

**Comment by pedrobaeza** [comment]
Good point, although that version is not officially supported yet, it's good to check for possible problems.

@mart-e who can handle this?

**Comment by mart-e** [comment]
>  will throw SyntaxError out if we launch odoo with this update python

Are you sure about it? Won't you just be able to use the python `async` from this file?
Same as you can do
```python
def foo(float=42):
     ....
```

even if this is a bad idea

**Comment by pedrobaeza** [comment]
In other versions, using reserved keywords, you redefine its meaning for that context, but no error is raised

**Comment by guewen** [comment]
@mart-e `float` is a builtin type not a keyword, `async` is a keyword starting from python 3.7, like `def` or `class` are. You can't do that:

```python
def foo(class=42):
    ....
```

It's the same with `async` now.

**Comment by mart-e** [comment]
@guewen oh right, thanks for the clarification. That will be problematic as changing that would change the signature which may break the compatibility in stable versions.
We have to find a workaround to avoid forcing a maximum version of python for v11...

**Comment by yvaucher** [comment]
@mart-e maybe not the cleanest way but for retro compatibility, you could rename the key argument in the signature plus adding kwargs and then you search if kwargs contains an 'async' key. That way you only work with string for retro compatibility and the issue is on the caller side.

**Comment by dungnm-vt** [comment]
Please fix it, is big bug

**Comment by hbto** [comment]
Hello guys, I will take a quote from [here](http://docs.python-guide.org/en/latest/shipping/freezing/)

> Freezing Your Code

As version 11 of odoo can first than the python3.7, and making workarounds would render odoo useless for others using the original signature of the methods that involved with keywords reservation of Python3.7. 

In my opinion, it is better to suggest frozen requirement on python version stating it works with 3.6
and make the changes in master/post-11 version.

Regards.

**Comment by mart-e** [comment]
The compatibility to python 3.7 has been fixed in the following commits:
af9d6b86a1e [ADD] tools: add new 3.7 opcodes
5a57c29ff2a [FIX] base: do not use async reserved keyword

Freezing could be an option but is a radical change in the way we ship Odoo. If we can maintain the compatibility with several versions, it is better.
Python 3.7 will soon be shipped on different linux distributions (afaik not yet the case) and it would make it a lot harder to deploy Odoo.
