### ISSUE TITLE
Assigned by/created by not visible in chatter

### ISSUE THREAD

**Issue by Binformed** [odoo/odoo#25584]
Impacted versions: v10/v11

Steps to reproduce:
Login as user A, go to (for example a partner) click schedule activity, schedule the activity and assign user B to this activity.
User B opens Odoo, opens the partner for which the activity was created. User B can see that the activity has been assigned but the user cannot see who created this and/or who assigned this activity to user B

Current behavior:
Assigned by/created by not visible
Expected behavior:
Show assigned by/created by

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/32832163/42215590-3928a1e8-7ebf-11e8-97e2-d24e40676a07.png)

**Comment by hugho-ad** [comment]
@mart-e 

Users shall create activities for others users different than they?

currently, there is an ir.rule that should prevent that, but apparently, it does not work

![image](https://user-images.githubusercontent.com/10233975/46058505-11b5aa80-c121-11e8-82b5-7c0525d0fa32.png)

**Comment by mart-e** [comment]
@hugho-ad the rule you are showing only apply for write and delete. It has no effect on the permissions of read and create.
Closing this issue as it was implemented at #25842

**Comment by hugho-ad** [comment]
Try it your self, even when writing/deleting the activity, the rule do not have any effect

That is because next line
https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_activity.py#L167

**Comment by mart-e** [comment]
@hugho-ad indeed, you are right, as explained in the method comment, the rules to write on an activity are based on the rights of the linked documents (if you can modify it, you can modify its activities).

@tde-banana-odoo Shouldn't we just drop this ir.rule then?
