### ISSUE TITLE
User can change value of parameter in json-rpc call 

### ISSUE THREAD

**Issue by tungnt16a** [odoo/odoo#25581]
Impacted versions:11.0

Steps to reproduce: 
We have 2 account Manager(Id =12) and Employee(id =13)
-Login to system with account manager
-Click on Contract left menu to show his contract.
-Using Burpsuite to capture json rpc post request (many post requests, search_read, field_view_get ...)
```
{"jsonrpc":"2.0","method":"call","params":{"model":"hr.contract","method":"fields_view_get","args":[],"kwargs":{"view_id":1389,"view_type":"tree","context":{"lang":"vi_VN","tz":"Asia/Ho_Chi_Minh","uid":12,"search_default_working":1,"search_default_confirmed":1"params":{"action":785},"active_model":"hr.contract"},"toolbar":true}},"id":485311412}
```
find **uid** paramter and change the value from 12 to 13
```
{"jsonrpc":"2.0","method":"call","params":{"model":"hr.contract","method":"fields_view_get","args":[],"kwargs":{"view_id":1389,"view_type":"tree","context":{"lang":"vi_VN","tz":"Asia/Ho_Chi_Minh","uid":13,"search_default_working":1,"search_default_confirmed":1"params":{"action":785},"active_model":"hr.contract"},"toolbar":true}},"id":485311412}
```
Post request after edit to server.
Current behavior:
User login with Manager account but can see Employee contract.
Expected behavior:
encode or encrypt parameter in json rpc call.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What is for you `account manager`? Are you talking about `admin` user?

**Comment by tungnt16a** [comment]
i mean 2 different accounts. Manager is John's account and Employee is Jane's account.

**Comment by pedrobaeza** [comment]
But the visibility of records depend on the user you are logged in. If that user can see everything due to its permissions, then this is the expected result.

**Comment by tungnt16a** [comment]
Im using Burpsuite to modify POST request(change uid 12 to 13) and send that request to server, then i can see anything of user has id =13.
