### ISSUE TITLE
[11.0] Pos Orders taking the PC time instead of the user tz time?

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25606]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Change the local PC time to 3 days ago.

#### Current behavior:
- Create a POS order, the date shows a past date (3 days ago).
- The server gets the pos order with the same past date 

#### Expected behavior:
- Orders shouldn't be affected by the local PC time, it should respect the user TZ configured in the server.

**Comment by pedrobaeza** [comment]
That's not possible, as the POS work offline, and then the information stored is the local one. It's possible that the POS order hasn't been synchronized in that 3 days, or even in a month! Odoo only gets that information and store it.

This is not a real bug, but the way it works due to the offline capabilities, so closing.

**Comment by gustavovalverde** [comment]
@pedrobaeza How can you explain this?

Before Changing the PC time:
**POS Order**
![image](https://user-images.githubusercontent.com/16890942/42289877-22fab74a-7f90-11e8-9dba-727c4665b528.png)

**POS order Metadata**
![image](https://user-images.githubusercontent.com/16890942/42289914-51315c04-7f90-11e8-941c-22e37831ec3c.png)


After Changing the POS PC time:
**POS Order**
![image](https://user-images.githubusercontent.com/16890942/42289817-ac0d401c-7f8f-11e8-9b9f-ea6f3e83439a.png)

**POS order Metada**
![image](https://user-images.githubusercontent.com/16890942/42289839-e42f3108-7f8f-11e8-91fb-bda9ff5a9535.png)

**Comment by pedrobaeza** [comment]
I don't get where do you want to go. The creation date will be always server time, but the POS date will be the one saved on local.

**Comment by gustavovalverde** [comment]
The date saved on local should be taken from the server the moment you open the POS, and continue with it even if it gets offline.

We can't rely on the local POS computer time, if the user change the local PC time then the orders sent to the server will use the PC time.

I'd love that all my clients would use domain policies to lock their users from changing the computers local time, but that ain't a reality. Most of the time the user has access to change the PC date, and thus this could be use for frauds and other things.

**Comment by pedrobaeza** [comment]
As said, that's something not feasible, as even if you make an initial synchronization, then you can change the time when you want. But there's an standard solution for that, and it's called NTP :wink: No need that Odoo put in its shoulders this task, and you as sysadmin should provide these things in all your PCs. Tip: use Linux instead of Windows.

**Comment by gustavovalverde** [comment]
Just to be aligned here: This is happening **even** if the POS is completely online. At least if it's online it should rely on the server time instead of the local time.

> But there's an standard solution for that, and it's called NTP 😉 No need that Odoo put in its shoulders this task, and you as sysadmin should provide these things in all your PCs.

Based on Odoo's reality, most of the clients are SMEs. If Odoo needs an NTP to keep a reliable date on the pos.orders, maybe we should update the documentation with that information. Would that be OK @jorenvo @pimodoo

**Comment by pedrobaeza** [comment]
Yes, although the POS is online (which is some kind of "illusion", as orders are always synchronized), the date taken is the local one, as the JS that governs this is local. I don't think any documentation should be updated, as that's one of the basic responsibilities of any sysadmin. Or do you have to document that you have to protect your server ports and similar things? All of this is stuff out of the Odoo scope, and document it is to not focus on the important things in it.
