### ISSUE TITLE
[11.0-product_margin] Wrong Calculation with MultiCurrency and Tax Included Price and Landed Costs

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#25603]
Impacted versions:
11.0 (at least)
Steps to reproduce:
- Setup a product with costing method to automated FIFO and tax included in price
- Setup a foreign currency
- Buy a Product in foreign currency (purchase order --> stock receipt --> supplier invoice)
- Add Landed costs in company's currency
- Sale the product in company's currency

Current behavior:
product_margin report is wrong : 
- Avg. Unit Price is taken with tax included
- Sales Gap takes product price (tax included) - invoiced price (tax excluded)
- Total cost is in foreign currency
- Total cost does not include landed costs
- Expected margin does not include landed costs (normal_cost does not include landed costs)

Expected behavior:
- Avg. Unit Price should be taken tax excluded
- Sales Gap should take "if tax is included then (product price - tax amount) - invoiced price"
- Total cost should be in company currency
- Total cost should include landed costs
- Expected margin should include landed costs (normal_cost should include landed costs)

**Comment by sle-odoo** [comment]
This should now be fixed in master since we better integrate sale_margin and sale_stock with sale_stock_margin.
