### ISSUE TITLE
[11.0-product_margin] Pos orders are not included in product_margin report

### ISSUE THREAD

**Issue by invitu** [odoo/odoo#25605]
Impacted versions:
11.0

Steps to reproduce:
N/A

Current behavior:
pos_orders are not included

Expected behavior:
There might be a extra module that automatically installs when product_margin and point_of_sale are both installed. This module should include pos_order sales in the report
If Real Time Cost is activated, it should be taken into account

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's something not included in v11, but next version will include an unified sales report for all the channels: sales orders, e-commerce and POS, so this wishlist can be considered as solved on it.
