### ISSUE TITLE
[9][10][11]Not issue yet - Making Tax Digital - Automated tax reporting necessary in UK from April 2019 (MTD)

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#25619]
Current behavior:
Users can display and download tax documents in Excel/PDF
Expected behavior:
Automated/one click process from April 2019

MAKING TAX DIGITAL
The Making Tax Digital requirements will apply to all VAT registered businesses for their VAT obligations from April 2019 where their turnovers are in excess of the VAT threshold (currently £85,000). 
From April 2019, VAT registered businesses (including self-employed and landlords) with turnover above the VAT registration threshold (currently £85,000) will have to:
•	keep their records digitally (for VAT purposes only)
•	provide their VAT return information to HMRC through Making Tax Digital compatible software

Overview:
https://www.gov.uk/government/publications/making-tax-digital/overview-of-making-tax-digital
Compatible software suppliers:
https://www.gov.uk/guidance/software-for-sending-income-tax-updates
Making tax digital centre:
https://www.aat.org.uk/making-tax-digital

**Comment by pedrobaeza** [comment]
Please put this information in #18510 instead, that gathers all the requirements for UK localization.
