### ISSUE TITLE
Early payment discount

### ISSUE THREAD

**Issue by Binformed** [odoo/odoo#25623]
Is there a solutions for early payment discount where:

1. 100% of the invoice amount is due within the payment term period.
2. The invoice is not split into 2 invoice lines in reports (e.g. customer statements and aged reports).
3. The discount amount is only considered when processing payments.

Thanks in advance for all your comments.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by Binformed** [comment]
Well it depends on how you define issue.

How Odoo handles early payment discounts (according to the documentation) is not how early payment discounts should be handled. Odoo is splitting the invoice amount and assuming that one part of the invoice is due before the remaining part. But that's not what early payment discount is about. The invoice should due for 100% till the last day of the payment term. The received payment including discount should only be considered when processing the bank.

**Comment by pedrobaeza** [comment]
Odoo is not assuming anything. You reconciliate the way you want: with or without discount. Any way, as said, this should be discussed in forums, not here, and eventually get to here with an specific bug or issue.
