### ISSUE TITLE
Min Qty of product in Pricelist, integer or float

### ISSUE THREAD

**Issue by my1649** [odoo/odoo#25648]
Impacted versions: V11.0

Steps to reproduce: 
1. Activate Developer mode
2. Sales -> Configuration -> Settings
3. Pricing -> Enable "Multiple Sales Prices per Product"
4. Choose "Multiple prices per product", SAVE
5. Create a NEW product
6. Go to Sales of the product, Pricing, Pricelist
7. Create a new price for a pricelist
8. Input "1.5" as min quantity, SAVE
9. Warning for discard saving

Current behavior:
Unable to save the price because of min quantity. The field type of field "min_quantity" under model "product.pricelist.item" is set as integer. It doesnt accept any number with decimal.

Expected behavior:
Switch the field type as float, which accepts the decimal, because of following reason:
1. Some products are sold in Area or length, SQM, SQF, m, etc.
2. Min Qty ('min_qty') of Product Vendor ('product.supplierinfo') is a float field
3. Qty of product Sale ('product_uom_qty') of Sales Order Line ('sale.order.line') is a float field.
4. In fact, all quantity fields are float field

Video/Screenshot link (optional):
![fieldtype-minqty_pricelist](https://user-images.githubusercontent.com/25192449/42408511-595487f4-8200-11e8-9efb-bfcab3f140bb.jpg)

**Comment by Yenthe666** [comment]
Hi there,

Field types cannot be changed on stable releases no matter what. Besides of this a lot depends on this field so this has to be checked.
@mart-e what do you think? I've labeled it wishlist for now.

**Comment by my1649** [comment]
Hello guys, thanks very much for reviewing this. I am just curious about this field type.
Every Single field about min quantity is a float type field, but this min qty of pricelist. On the other hand, making it as float is a good idea. It could set the min qty of service in hours, or days, 3.5 hours, 0.5 days, not to mention about the area I am selling. Although we could switch it as 210 mins, 4 hrs, or cm even mm. 
Beside, I thought there is already something like `float_compare `calls though, otherwise how to check the qty of product is bigger than the `min_qty`? 
In fact, I believe not much is really effected. An Integer field is in a range of Float type, which is easy. Unlike switching from Float into Integer. I agreed it will be a terrible issue.
For my point of view, it just limit the possibility of Odoo. It is ok and understandable to label this wishlist.
Thanks so much again for your contributor, especially @Yenthe666 , I have learned so much about Odoo from you. And your **auto_backup**
Cheers

**Comment by my1649** [comment]
https://github.com/odoo/odoo/pull/45792 Fixed
