### ISSUE TITLE
[hr] Job description, qualification does not appear on website

### ISSUE THREAD

**Issue by infomate** [odoo/odoo#2564]
HR /Job Positions / Description and Qualification does not appear on the website.  Once the Job position is clicked on the website, only the  job title is displayed with a blank space underneath. Is this the default behavior? Should the description / qualification be entered manually by inserting blocks?

**Comment by Yenthe666** [comment]
Hi @infomate ,

This was made like this, it simply wasn't added.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. We could then label it as wishlist and might add it.

Regards,
Yenthe
