### ISSUE TITLE
[10.0] merge leads fails when a selection field is part of the fields to merge

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#25644]
## Impacted versions:

Tested 10.0 (bug probably exists on 9 and 11 too)

## Steps to reproduce:

* Add a custom field of type **Selection** to the `crm.lead` model.
* Add the field name to `CRM_LEAD_FIELDS_TO_MERGE`:

https://github.com/odoo/odoo/blob/8b8adcb5e6391d25fab9499c9cf1ccb585515db2/addons/crm/models/crm_lead.py#L19

* Try to merge two leads/opportunities

## Current behavior:

Stack trace here:

https://github.com/odoo/odoo/blob/8b8adcb5e6391d25fab9499c9cf1ccb585515db2/addons/crm/models/crm_lead.py#L507

`AttributeError: 'ir.model.fields' object has no attribute 'get_values'`

## Expected behavior:

No stack trace.

**Comment by pedrobaeza** [comment]
This reminds me my proposal of doing a general merge mechanism that it would be more bullet-proof any merge mechanism (now that we merge leads, tasks, partners...): #17268

**Comment by sbidoul** [comment]
OPW 1864870

**Comment by mart-e** [comment]
_Not tested_, probably introduced at c0f1f27dbd3eed7b30c0d7b40747e31073f2de31
We are now working with `ir.model.fields` records instead of `odoo.fields` objects.
To retrieve the (translated) fields labels on selection, something like:
```python
selections = self.fields_get()[field.name]['selection']
value = next(filter(lambda i: i[0] == value, selections), (value, value))[1]
```
should fix your issue (_still not tested_)
