### ISSUE TITLE
Overriding JS Method of UserMenu meet error 'user_context of undefined' when click Preferences in Admin menu

### ISSUE THREAD

**Issue by nguyenducthuanuet** [odoo/odoo#25656]
Hi everyone!
I want to display the username of user instead of name at the right corner. So I write a method to overwrite 'start' function of UserMenu in 'web.UserMenu'. My custom js file is:
`odoo.define('custom_crm.UserMenu', function (require) {
    "use strict";

    /**
     * This widget is appended by the webclient to the right of the navbar.
     * It displays the avatar and the name of the logged user (and optionally the
     * db name, in debug mode).
     * If clicked, it opens a dropdown allowing the user to perform actions like
     * editing its preferences, accessing the documentation, logging out...
     */

    var UserMenu = require('web.UserMenu');

    UserMenu.include({
        start: function () {
            var self = this;
            var session = this.getSession();
            this.$el.on('click', 'li a[data-menu]', function (ev) {
                ev.preventDefault();
                var menu = $(this).data('menu');
                self['_onMenu' + menu.charAt(0).toUpperCase() + menu.slice(1)]();
            });
            return this._super.apply(this, arguments).then(function () {
                var $avatar = self.$('.oe_topbar_avatar');
                if (!session.uid) {
                    $avatar.attr('src', $avatar.data('default-src'));
                    return $.when();
                }
                var topbar_name = session.username;
                if (session.debug) {
                    topbar_name = _.str.sprintf("%s (%s)", topbar_name, session.db);
                }
                self.$('.oe_topbar_name').text(topbar_name);
                var avatar_src = session.url('/web/image', {
                    model: 'res.users',
                    field: 'image_small',
                    id: session.uid,
                });
                $avatar.attr('src', avatar_src);
            });
        },
    });
});
`
It works. Username was displayed but when i click to 'Preferences' in Admin, I met the error: ' **Uncaught TypeError: Cannot read property 'user_context' of undefined**'. Detail here:
![screenshot from 2018-07-08 15-00](https://user-images.githubusercontent.com/20267242/42418034-cb147e3c-82c1-11e8-80af-bbccda591825.png)
![screenshot from 2018-07-08 15-00-11](https://user-images.githubusercontent.com/20267242/42417960-eb50024a-82bf-11e8-930e-478d146a91e0.png)
So, What id I wrong and How can I fix it ?
Thank you very much!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about custom development. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by MohsenWaleed** [comment]
Hi @nguyenducthuanuet 

I'm getting the same error, how did you solve it?

**Comment by tintumonmartin** [comment]
I'm also getting the same error, anyone solve it?

**Comment by MohsenWaleed** [comment]
Hi @tintumonmartin,

I was only to show the DB name without debug mode so I used the below code:

odoo.define('web_enhancement.UserMenu', function (require) {
"use strict";


var UserMenu = require('web.UserMenu');

UserMenu.include({
     start: function () {
       var self = this;
       var session = this.getSession();
       return this._super.apply(this, arguments).then(function () {

          var topbar_name = session.name;
          topbar_name = _.str.sprintf("%s (%s)", topbar_name, session.db);
          self.$('.oe_topbar_name').text(topbar_name);
        });
       },
})
});
