### ISSUE TITLE
in HR module the employee can view and edit all personnal data for any other employee

### ISSUE THREAD

**Issue by abdelshafysoliman** [odoo/odoo#25657]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's not true. It only happens if you are HR manager or admin. Can you please recheck?

**Comment by mart-e** [comment]
Indeed, only HR officers can modify the employees. This is set by the security rules and can be customized if it does not fit your company organisation.
Closing as lacking of proper details showing a bug.
