### ISSUE TITLE
website_sale_digital: download digital product

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#25651]
Impacted versions:
10.0 and 11.0

Steps to reproduce:
 1. Install "Website Sale Digital"
 2. Create a new product.
 3. Open Portal Files and upload file.
 4. Sell product in e-commerce.
 5. confirm the order and make invoice and payment.
 6. Open sales order from my portal.
 7. Click on download.

Current behavior:
 System redirect to "my/orders"

Expected behavior:
Download file

I trace issue and found that in this link https://github.com/odoo/odoo/blob/11.0/addons/website_sale_digital/controllers/main.py#L21
that because there is no option "digital" in 'type' field defined

**Comment by Yenthe666** [comment]
@JKE-be for your team to check when you're back 😉

**Comment by jlzhou** [comment]
One comment:
In odoo12.0, the field 'file_type' doesn't exist. We may remove it from search_read.

One more thing:
The file name in Chinese language (utf-8) will trigger an exception:
'latin-1' codec can't encode characters in position 43-47: ordinal not in range(256)

I change the code in 'def download_attachment' as below to work around it under python 3.6:
filename=attachment['name'].encode('utf-8').decode('latin-1')

**Comment by dansanti** [comment]
hello, this happens because if sale order have template defined, redirects to quote and not execute super, then never returns to website_sale

https://github.com/odoo/odoo/blob/617652bbfed923934cb1d3b6185d302031f4af18/addons/website_quote/controllers/main.py#L24

**Comment by rdeodoo** [comment]
The reported issue is no longer occurring in 12.0.
