### ISSUE TITLE
@ mentions fail in chatter when copied and pasted

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#25688]
Impacted versions: 9.0, 10.0, 11.0

Steps to reproduce:
1. Go to a contact and type a new chatter message that uses the @ function to mention somebody. For example "Demo user".
2. Before clicking on "Send" copy the text with ctrl+C
3. Paste the same text in a new message again
4. Click on "Send".
Video example on V11: 
https://drive.google.com/file/d/1hbHaka-wr657WmyGtnjl1KI1PpfI4LQy/view

Current behavior: The first message correctly pings and mentions thanks due to the @ that is working. The second message loses the @ reference because it is copied and not detected. This means that the mention goes lost and is not searched for again when clicking on "send". Due to this behaviour you cannot copy a message and reuse it on multiple records (for example for 5 tasks that need the same message).

Expected behavior: The @ works in both cases, either by manually typing or pasting.

**Comment by Yenthe666** [comment]
Notice that this issue gets way more problematic if you're working with internal notes by the way. What if you use internal notes on issues where the customer also responds on? Then the internal note with the failing @ will not be sent to anybody which causes losses are problems in the process.

**Comment by rim-odoo** [comment]
This feature is not supported.

**Comment by Yenthe666** [comment]
Nooo, seriously? It is so annoying when I duplicate a message across 10+ tasks that it doesn't work.
Thanks for the wishlist item @mart-e - I'd love this in a newer version.

**Comment by rim-odoo** [comment]
@Yenthe666 maybe one day, this could be a cool new feature indeed, and I do agree it can be a bit annoying, but for the moment I cannot consider it as a bug as it was never planned to make it work

**Comment by Yenthe666** [comment]
@rim-odoo yep, it would be a great little addition. I understand though. Let's hope for it one day :)
