### ISSUE TITLE
[10.0/11.0] Return backorder confirmation doesn't update sale order line

### ISSUE THREAD

**Issue by CasVissers** [odoo/odoo#25681]
Impacted versions:
10.0/11.0

Steps to reproduce:

- Create a sale order
- Add [LAP-E5] Laptop E5023 - qty 5
- Confirm outgoing picking
- Return qty 3 with to refund True
- Confirm incoming shipment - qty 2- backorder yes (SO line = 5ord-**3del**-0inv)
- Confirm incoming shipment - qty 1 (SO line = 5ord-**3del**-0inv)

Current behavior:
Delivered is not updated by last incoming shipment.

Expected behavior:
Qty delivered should have been 2 (5-2-1)

OPW 1872131

**Comment by janbec** [comment]
I tested on a v11e runbot and can confirm the same behavior.

**Comment by CasVissers** [comment]
For a ticket concerning a default Odoo process it's not really handled with priority.

**Comment by len-odoo** [comment]
Issues on Github are indeed treated with lower priority than OPWs.
In case you prefer to use this workflow, we would recommend creating the Github issue as usual, then simply linking to the issue in the OPW.

**Comment by CasVissers** [comment]
@len-odoo added OPW (OPW 1872131)

**Comment by CasVissers** [comment]
Fixed by 0ab71f124797912b3df39e748552741df430e4fc, closing issue.
