### ISSUE TITLE
[8.0] PNG Images: transparant is black and colordepth decreased

### ISSUE THREAD

**Issue by mgielissen** [odoo/odoo#2569]
When uploading PNG images in Website Builder, the transparant background is black instead of transparant. Also when uploading the Odoo Community Member logo, the colordepth is decreased (dittered).
![black](https://cloud.githubusercontent.com/assets/7700396/4346822/5535019e-4118-11e4-8c96-860b7ad16569.png)
![dittered](https://cloud.githubusercontent.com/assets/7700396/4346823/58ef0eb0-4118-11e4-9fa5-15943850ff5d.png)

Replay:
Install Odoo with this script: https://raw.githubusercontent.com/aschenkels-ictstudio/openerp-install-scripts/master/odoo-v8/ubuntu-14-04/odoo_install.sh

In WebsiteBuilder, upload PNG image from Computer.

**Comment by blessendor** [comment]
When I change my Company Logo from backend, odoo upload it in not original size and quality. My PNG logo with transparent background became a sharped.
