### ISSUE TITLE
Line chart axis bug

### ISSUE THREAD

**Issue by shanghq** [odoo/odoo#25690]
Impacted versions:
10.0 community

Steps to reproduce:
Select two layer grouping in line chart.

Current behavior:
When I select two layer grouping in line chart view, the X-axis moves one unit to left.

One layer grouping:
![image](https://user-images.githubusercontent.com/5986203/42497642-95aeb5d6-845c-11e8-8036-8c5abb7840e5.png)

Two layer grouping:
![image](https://user-images.githubusercontent.com/5986203/42497683-afbab06a-845c-11e8-8e22-adbdf976bf06.png)

Expected behavior:
The X-axis should not move.

Video/Screenshot link (optional):

#

**Comment by Yenthe666** [comment]
Dear @shanghq,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
