### ISSUE TITLE
[11][BUG] stock: reservation issue and unreservation with with product with serial number

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#25707]
Steps to reproduce:

Go to runbot:
- create a product with unique serial number
- create a picking in with 5 products, create 5 serial number and validate
- create a picking out, with 3 product, assign
- go to detailled operation, set to false the lot_A
--> Issue 1 : the quantity done is set to 1
- confirm the detailled operation
- reopen detailled operation, set the lot_A on the line without lot
--> the quantity is not reserved, 
It is strange because if you change change lot_1 to lot_B, it is good but if you change lot_A --> False --> lot_B it is re-reserve.

this create issue when you validade the picking.

@jco-odoo
@sle-odoo

**Comment by fmdl** [comment]
OPW: 1865827

**Comment by fmdl** [comment]
cc @sylvain-garancher

**Comment by sle-odoo** [comment]
Hi,

> Issue 1 : the quantity done is set to 1

I don't think it's an issue, it could mean you processed a product you don't want to track at this time.

> --> the quantity is not reserved,

There isn't any "quantity to do" field on the move line, and getting it through the move is tricky if the reservation is split across multiple move lines. We decided to not implement this case. You could always re-run check availability.

> this create issue when you validade the picking.

No it doesn't, i just tested it. Please elaborate if i missed something, i'll reopen the issue.

Regards

**Comment by fmdl** [comment]
@sle-odoo 

Go to runbot:
- create a product with unique serial number
- create a picking in with 5 products, create 5 serial number and validate
- create a picking out, with 3 product, assign
- go to detailled operation, set to false the lot_A
--> Issue 1 : the quantity done is set to 1, it is not logical
- confirm the detailled operation
- reopen detailled operation, set the lot_A on the line without lot
--> the quantity is not reserved, 
- click on action _assign
--> the quantité is not reserved again

**Comment by fmdl** [comment]
why we have a difference between :
-  lot_1 to lot_B
 - lot_A --> False --> lot_B

**Comment by fmdl** [comment]
whay is methode to reserve or unreserve only one stock.move.line

**Comment by sle-odoo** [comment]
Because there's no "quantity to do" field on the move line. Once it is unreserved, we don't know anymore which quantity it had reserved initially.

**Comment by fmdl** [comment]
what is technical name of `quantity to do`.
if it is with serial, it is always 1, no ?

**Comment by sle-odoo** [comment]
> what is technical name of quantity to do.

None, because we don't have the field :) 

we could do a special case for serial tracked products, but we won't
you'll have to live with this limitation or extend the code.. we do not plan to improve this part of the code
