### ISSUE TITLE
Odoo SMTP Send Invitation Mail failure 553

### ISSUE THREAD

**Issue by powerline332** [odoo/odoo#25703]
Sorry if this is not correct place as I'm new to github -  odoo.com/forum needs 3 'karma' points to ask a question.... chicken and the egg problem... 

I have a problem exactly the same as in this closed question:

https://github.com/odoo/odoo/issues/13479

I am using a dockerized version, from here: https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21 , as of July 10,2018 - so with

postgres:10.0
veivaa/odoo:11.0 --->  Odoo 11.0-20180710 (Community Edition) 

and am experiencing the exact same error as W360S. When I clear the Alias Field under General Settings, the Email Invitation works, but it sends a link to the user with "locahost" in it, e.g.

http://localhost:8069/web/reset_password?db=Everything&token=1kwQSGujVuFAULw

My WLAN IP is known so how do I send that address instead?

The administrator's email is the same account as the Incoming & Outgoing (IMAP/STMP) servers at yandex. The company's website is the WANIP - could leave it blank for now since it doesn't seem to matter, and the company's email address is the same as the administrator's. 

The docker image is running stretch, as am I, if it matters.

**Comment by sswapnesh** [comment]
You can verify your email to get 3 Karma.

**Comment by pedrobaeza** [comment]
You get that 3 points karma when registering and confirming your email. This is for avoiding spam bots on forums only. Please make that question there after passing through that validation.
