### ISSUE TITLE
Odoo 10.0/nightly/src/ Missing Files

### ISSUE THREAD

**Issue by DebianJK** [odoo/odoo#25717]
**Impacted versions:**
Odoo 10.0

**Steps to reproduce:**
>1. wget https://nightly.odoo.com/10.0/nightly/src/odoo_10.0.20180711.tar.gz
1.1 Info: 11-Jul-2018 05:41 95141696 (20519 files)
>2. wget https://nightly.odoo.com/10.0/nightly/deb/odoo_10.0.20180711.tar.gz
2.1 Info: 11-Jul-2018 05:42 114579464 (21979 files)

**Current behavior:**
Both 1. and 2. above have same file name but different sizes and 1. is missing lots of files including odoo-bin.

**Expected behavior:**
Both 1. and 2. should work? No!

**Comment by Yenthe666** [comment]
Dear @DebianJK,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
