### ISSUE TITLE
[11.0] Drag nd Drop should not be possible when blocked (Sales Orders)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25723]
Impacted versions: 11.0

Steps to reproduce: Performed on [Runbot](http://347432-11-0-6a5dc8.runbot16.odoo.com/web?debug#view_type=kanban&model=sale.order&menu_id=527&action=716) --> Sales Order --> Group By Customer (Make sure you have enough records to get scroll bar at bottom or resize windows)

Current behavior:
Able to drag and drop Sales Order
![4](https://user-images.githubusercontent.com/16624719/42589348-4e39e574-855e-11e8-81cb-d2a8c0da4a54.png)

![2](https://user-images.githubusercontent.com/16624719/42589344-4cf15a58-855e-11e8-8bdc-96e83d6d0a75.png) 
May be you have to hold card for a while to reproduce this
![3](https://user-images.githubusercontent.com/16624719/42589340-4c2ae9cc-855e-11e8-9317-de56f0c47cdf.png)

Expected behavior:
Should not be able to drag and drop record.
or
If this is intended behaviour than Onchange method is not call here (Invoice/Delivery address should be updated)
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

It looks this is fixed, it's not possible to move the kanban anymore.
sorry for the delay.
