### ISSUE TITLE
[11.0]PoS: Barcode action should not be available on Payment Screen

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25744]
Impacted versions: 11.0

Steps to reproduce: Go to PoS Payment Screen --> Type any words(Little fast)

Current behavior:
![pos1](https://user-images.githubusercontent.com/16624719/42649074-426f3cd0-8626-11e8-8f3f-f473f439b1f4.png)

Expected behavior:
Barcode action should not be enabled on this screen
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@switch87 Can we close this issue? or may be better to add Wishlist.

**Comment by switch87** [comment]
@sswapnesh we are not planning on changing this by default, it can be closed.
