### ISSUE TITLE
Language settings reset on upgrade of "base" module

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#25748]
# Impacted versions:

10.0, 11.0, maybe 9.0

# Steps to reproduce:

1. Activate debug, go to Settings > Translations > Languages
2. Edit English
3. Change the date and time format
4. Update 'base' module

# Current behavior:

The date and time formats are reset to the default values.

# Expected behavior:

The date and time formats are kept.

# Cause

The languages are loaded from a CSV file so at every update they are reloaded. They should be loaded in a xml file with noupdate=1.

**Comment by pedrobaeza** [comment]
@mart-e what do you think about this?

**Comment by mart-e** [comment]
Hi,

Yes, as any data not specifically in no-update, the changes are lost when you upgrade the module.
I don't see why the languages should be in noupdate, this is the kind of data you usually don't want to customise, it is the same for all companies.
On the contrary, in case you mess up your system when modifying it, you get it back with an upgrade.

If you believe there is an error in the language definitions, please, do make a bug report about it (or better, submit a fix).

If you want to have something different than the standard languages definition for whatever reasons, you should explicitly mark the record as noupdate (Settings > Technical > External Identifiers).

**Comment by guewen** [comment]
> this is the kind of data you usually don't want to customise

Well I guess our users who complained about losing their date formats didn't had the same expectations, I disagree but I won't argue more. We'll customize them in addons, and too bad for the ones with less technical knowledge.

**Comment by mart-e** [comment]
IMHO, customizing a date format is already a technical change.
However, it could be made easier to either inform the user or to toggle the noupdate flag. Maybe this is something to investigate.

**Comment by ra00f** [comment]
Get the **name** of the newly added language from 'View metadata' -> XML id and run the following sql under odoo DB
`update ir_model_data set noupdate = True where model= 'res.lang' and name='lang_lo_LA';`  

here lang_lo_LA is the name for the Lao language.
