### ISSUE TITLE
[11.0] Invalid base amount in Tax report when Group of taxes are used

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25743]
Impacted versions: 11.0 

Steps to reproduce: Create new `Tax 18 %` --> This contains two 9% Tax into it (Both are Included in Price with 9.0%)
![t1](https://user-images.githubusercontent.com/16624719/42645999-2fa53464-861d-11e8-8dcf-f224cc12dc62.png)
![t2](https://user-images.githubusercontent.com/16624719/42646001-30ee4612-861d-11e8-987a-265b08012145.png)

Create new Invoice with this tax in line --> Validate
Current behavior:
Print Tax Report from `Accounting/Reporting/PDF Reports/Tax Report`
![screenshot from 2018-07-12 21-51-22](https://user-images.githubusercontent.com/16624719/42646195-c6dc921e-861d-11e8-9fd4-809bc476bb88.png)

![t3](https://user-images.githubusercontent.com/16624719/42646168-b165c7f2-861d-11e8-8632-f73b454c8a93.png)

Expected behavior:
Valid Net amount in Report
![t4](https://user-images.githubusercontent.com/16624719/42646319-2d77e596-861e-11e8-8abd-e8657140fca8.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This affects Indian Accounting users as we have Group taxes in all applications.

**Comment by sswapnesh** [comment]
Strange behaviour when using official l10n_in module for Same Purpose.

Create Invoice With `18% GST` (I have Checked `Included in Price` in both Child taxes)
![91](https://user-images.githubusercontent.com/16624719/42647417-9760193a-8621-11e8-8240-69f0a8bad895.png)

![92](https://user-images.githubusercontent.com/16624719/42647408-9410638e-8621-11e8-9d68-3418a2b16493.png)

Notice amount in Tax report
![screenshot from 2018-07-12 22-15-05](https://user-images.githubusercontent.com/16624719/42647261-19a97022-8621-11e8-88bc-b6f7b3ab6d9c.png)

**Comment by mga-odoo** [comment]
Its a bug that is confirmed, but I thinks this has also solved in Odoo Master (Odoo ~12.0), the only workaround to this problem is to create a tax using python tax computation. 

I see that you selected "Affect Base of Subsequent Taxes" options too, it will computes tax included in a different way, you don't need this specially when you compute the GST tax for India.

Have a look at the video https://youtu.be/R2XP2t8-g14, hope this solved your problem. I think the fix for the V12 will not be applied to V11, as lots of users (i know many of them) already using this workaround so as of now this issue can be mark as solved.

**Comment by mga-odoo** [comment]
It works for both version, Community and Enterprise, check account_tax_python module installed not. If not install it to get the Python Code option on the Tax configuration.

**Comment by Yenthe666** [comment]
Then I guess we can conclude it is solved in the upcoming 12.0 and will not be fixed in 11.0.

**Comment by sswapnesh** [comment]
Hello @mga-odoo 
Thanks for Review but the Original Issue was about invalid Base amount in Tax Report.

> Its a bug that is confirmed, but I think this has also solved in Odoo Master (Odoo ~12.0), the only workaround to this problem is to create a tax using python tax computation.

Lets not add GST methodology here for a moment, Create Group taxes with Child having Tax Included into Price. --> Validate Invoice -->  Print Tax Report and compare Base amount.

> I see that you selected "Affect Base of Subsequent Taxes" options too, it will computes tax included in a different way, you don't need this specially when you compute the GST tax for India.

That's True, But It was due to bad onchange which automatically check `Affect Base of Subsequent Taxes` when we make it `Tax Included`.

I have added python code as mentioned in video (+1 for your efforts), Now it calculates correct taxes according to GST methodology but still it has wrong base amount in Tax report.

![c1](https://user-images.githubusercontent.com/16624719/42703217-9123d782-86e9-11e8-9579-dd9540277a9f.png)
![screenshot from 2018-07-13 22-10-21](https://user-images.githubusercontent.com/16624719/42703239-9f51e6e6-86e9-11e8-8140-204eda91d090.png)

**Comment by sswapnesh** [comment]
@Yenthe666 
Tested same in master and still It has Issue as mentioned above.

**Comment by sswapnesh** [comment]
@mga-odoo  Wrong amount in Tax report is because of `Tax application = None` in tax data of GST.
![screenshot from 2018-07-13 22-34-04](https://user-images.githubusercontent.com/16624719/42704292-ee55ea3c-86ec-11e8-8854-022d2bac2fd9.png)

Could you please confirm this ?

**Comment by mga-odoo** [comment]
Enterprise works well.

![tax-reports-on-screen](https://user-images.githubusercontent.com/7595796/42705481-1196a190-86f1-11e8-8009-19e2cdc3c553.png)

Export to XLS
![tax-reports-export-xls](https://user-images.githubusercontent.com/7595796/42705494-1ee97502-86f1-11e8-9572-180469318157.png)

Didn't notice that the community reports have problem so not only Tax Report but also Journal Audit report does not display Base + Tax amount.

![screen shot 2018-07-13 at 11 08 06 pm](https://user-images.githubusercontent.com/7595796/42705672-af2848d2-86f1-11e8-8c7d-6cbc591f0934.png)

**Comment by sswapnesh** [comment]
Works well in Community too if we change Tax Application to Sale.

**Comment by mga-odoo** [comment]
Perfect  :+1

**Comment by sswapnesh** [comment]
BTW, In ideal case this should not happen. When tax application is None, that means you could not use it directly on So/Po. but still that can be use in Child taxes and It should appear in Reports, So my original issues is still there.

**Comment by nidhishjain** [comment]
@mga-odoo @sswapnesh @Yenthe666 @xrg @rvalyi 

But what about this Python Based calculation in POS, no taxes showing in POS ticket. When base is wrong then? POS receipt too display the taxes.

**Comment by sswapnesh** [comment]
Have a look at https://github.com/odoo/odoo/issues/25829#issuecomment-405812763
