### ISSUE TITLE
[Wishlist]PoS: Ability to Define rules for Large Payment amount

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#25745]
Impacted versions: 11 (Not tested in other vesrsions)

Steps to reproduce: Create PoS order --> Payment Screen--> Pay 1000 times more than order amount

Current behavior:

At the moment, it is static code which is comparing Total amount  * 1000 with Payment amount

> if (!force_validation && order.get_total_with_tax() > 0 && (order.get_total_with_tax() * 1000 < order.get_total_paid())) 

![30](https://user-images.githubusercontent.com/16624719/42649614-ca218812-8627-11e8-958e-ac6d4488af8f.png)

Expected behavior:
Ability to define maximum amount or Rules based on order Price
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hi,

Don't you think this is an overkill feature? It would make the interface more complicated than needed.
We made this to avoid human mistake. If you really need to be able to change that, it has to be done in custom code.

**Comment by sswapnesh** [comment]
Hello @mart-e 
May be that's true but I was talking about adding this in Backend. (Compute in backed and display message based on comparison)
 

> If you really need to be able to change that, it has to be done in custom code.
Sure, we can use logic which is used to calculate Delivery charges in Sale order.

Thanks for review.

**Comment by mart-e** [comment]
@sswapnesh yes but this is typically the kind of complexity you do want to hide for the user. If 99% of the users don't need with this, it is probably not worth it. The point of Odoo is to have a simple interface that will work for most of the people, adding more checkbox is rarely a good idea.
Moreover the point of sale must work offline, so computing it in the backend is not an option,
Adding one more option is not just adding a few lines of code, it means maintaining one more feature.
