### ISSUE TITLE
Different number of decimals for product quantity in SO and PO

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#25760]
Impacted versions:
11

Steps to reproduce:

- create a PO
- purchase 1.999 units of any product
- receive goods

- create an SO
- sell what you just bought: 1.999 units of product

Current behavior:
- amounts in the SO will be rounded to two digits, i.e. to 2.00 units
- you get a warning that you are about to sell more goods than you have in stock

Expected behavior:
- one would like to sell products with the same accuracy as you can buy them, i.e. 3 digits of uom
- no warnings, just smooth purchase and sale

Note:
PO uses product_qty but SO uses product_uom_qty. Maybe this is a hint?

**Comment by sswapnesh** [comment]
@haconsult 
You have to change `Decimal Accuracy` for `Product Price` to 3 under `Settings/Technical/Database Structure/Decimal Accuracy`

**Comment by haconsult** [comment]
Hi,
This has nothing to do with Product Price - it is about Product Quantity. You can buy 5.678 quantities but you can not sell the same amount.

Please reopen the issue

**Comment by sswapnesh** [comment]
Try changing that, It will work.

**Comment by haconsult** [comment]
I did - it does not work.

**Comment by Yenthe666** [comment]
I'll reopen for now. @haconsult please make a video where you show the rounding configuration & the issue that you're talking about

**Comment by haconsult** [comment]
I reinstalled and it works now. However, it is not the product price but the product uom quantity that has to be set in the Database Structure/Decimal Accuracy.

Many thanks

**Comment by sswapnesh** [comment]
If I remember correctly decimal accuracy for product uom qty is already 3 by default.

**Comment by haconsult** [comment]
Yes that is right. I must have mixed something up while customizing. 
However, it would be great if you could have different decimal accuracies for different UOMs. For example you have a product sold in liter and one in pieces. You might sell 45.453 l gas at the station but it makes no sense to sell 1.000 cappuccino (who would want 0.965 cappuccinos?). Would there be a way to handle this?

**Comment by sswapnesh** [comment]
I don't think this is feasible in current framework.
