### ISSUE TITLE
[CI] Longpolling support in unittests

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#25773]
Impacted versions: all

Steps to reproduce: write any test with longpolling

Current behavior: it's impossible to implement tests with longpolling. See https://github.com/odoo/odoo/commit/673f4aa4a77161dc58e0e1bf97e8f713b1e88491

Expected behavior: Allow to cover longpolling-related features. Especially, it's needed for different instant synchronization features

Video/Screenshot link (optional):

====================

The main problem, for now, is that longpolling is running on another port and requires to use web-server (e.g. nginx) to proxy requests. What are possible workarounds for this? Can we proxy longpolling requests on odoo level?

**Comment by pedrobaeza** [comment]
This is a known limitation as you already know, but maybe @ged-odoo has anything on the roadmap though for this.
