### ISSUE TITLE
Dead code (QWeb)

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#25775]
https://github.com/odoo/odoo/blob/67279c87f84586487113a113677e42a08896896e/odoo/addons/base/ir/ir_qweb/ir_qweb.py#L91-L94

**Note:** `view.inherit_id` cannot ever be `None`

It's either an empty record set (`bool(view.inherit_id) == False`) or its a non-empty recordset.

Then, the question is what is this no-op code for and does it have an original mission?

**Comment by pedrobaeza** [comment]
If nothing is broken, don't touch it! If you have a reproducible error due to this code, please put it as issue. If not, better to leave it as is.

**Comment by Yenthe666** [comment]
@pedrobaeza I guess, technically speaking, you could do such cleanups in masters though.

**Comment by pedrobaeza** [comment]
But that's solved through PRs, not issues.

**Comment by Yenthe666** [comment]
Agreed. so @blaggacao we welcome a PR. 😉

**Comment by blaggacao** [comment]
Thanks for the discussion: which rises again my preliminary question of whether it's really dead code. This particular piece is so low level and at the same time *seems* so intentional. 

Maybe: Shouldn't it be replaced by a proper implementation of that intention? So what was the original mission?

First we should somehow agree (as it's not obvious) - and then I can act.
The only obvious thing is that's broken.

**Comment by Yenthe666** [comment]
@xmo-odoo can I please ask you for feedback here?
