### ISSUE TITLE
field.Html() does not have a correcponding column type in view_list.js

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#2577]
view_form.js does have  'html' : 'instance.web.form.FieldTextHtml' in instance.web.form.widgets.
But there is no field.html in instance.web.list.columns from view_list.js.
Here is the patch:

<pre><code>
diff --git a/addons/web/static/src/js/view_list.js b/addons/web/static/src/js/view_list.js
index 7159225..088d96e 100644
--- a/addons/web/static/src/js/view_list.js
+++ b/addons/web/static/src/js/view_list.js
@@ -2154,7 +2154,8 @@ instance.web.list.columns = new instance.web.Registry({
     'button': 'instance.web.list.Button',
     'field.many2onebutton': 'instance.web.list.Many2OneButton',
     'field.reference': 'instance.web.list.Reference',
-    'field.many2many': 'instance.web.list.Many2Many'
+    'field.many2many': 'instance.web.list.Many2Many',
+    'field.html': 'instance.web.list.Html',
 });
 instance.web.list.columns.for_ = function (id, field, node) {
     var description = _.extend({tag: node.tag}, field, node.attrs);
@@ -2393,5 +2394,10 @@ instance.web.list.Reference = instance.web.list.Column.extend({
         return this._super(row_data, options);
     }
 });
+instance.web.list.Html= instance.web.list.Column.extend({
+        _format: function (row_data, options) {
+            return row_data[this.id].value;
+        }                                                                                                                                                              
+    });
 })();
 // vim:et fdc=0 fdl=0 foldnestmax=3 fdm=syntax:
max@explorer:~/tmp-work/odoo/odoo.my$ B
</code></pre>

**Comment by Yenthe666** [comment]
Hi @litnimax,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
