### ISSUE TITLE
Registration link does not load

### ISSUE THREAD

**Issue by raymondnl** [odoo/odoo#25771]
Hi,

We are new to odoo. I was sent an invitation link. But uppon clicking the link the password change page did not load and got a page not found. 
After doing some testing I found out the page is loading after clicking one of the databases on the main screen. 

It seems the invite link is looking for a session cookie when it finds it, it loads. Removing the cookie gives the page not found message again.

First time users do not have the cookie, which means eacht new user gets the page not found message.

Is this a know issue?

Regards..

**Comment by sswapnesh** [comment]
You need to add dbfilter in odoo config.
You can find more here. 
https://www.odoo.com/documentation/11.0/setup/deploy.html

**Comment by Yenthe666** [comment]
Indeed, you're missing the db_filter and it is about deployment.
P.S: Don't forget there is an official Odoo forum to ask those kind of questions, see https://www.odoo.com/forum/help-1
