### ISSUE TITLE
Help description of "Generate tasks from sale order" is obsolete 

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#2578]
This description doesn't fit anymore due to the simplification in procurement tab of product forms.
![bildschirmfoto 2014-09-21 um 16 15 22](https://cloud.githubusercontent.com/assets/8348598/4348761/361d67f6-419a-11e4-872b-dc097d7ee16a.png)

Now it is much easier, i assume the help text needs to be updated.
![bildschirmfoto 2014-09-21 um 16 19 32](https://cloud.githubusercontent.com/assets/8348598/4348767/6aaadb34-419a-11e4-910a-fa8d66d0f3d5.png)

**Comment by Yenthe666** [comment]
Hi @tv-openbig,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
