### ISSUE TITLE
[11.0] Wrong cost price on Average Cost Method

### ISSUE THREAD

**Issue by AngelCamacho** [odoo/odoo#25782]
Impacted versions:
11.0

Steps to reproduce:
Product Category Costhin Metod: Average Cost (AVCO)

Make various warehouse entries with different cost prices and a partial entry.

![imagen](https://user-images.githubusercontent.com/11173802/42751443-17fdfe2e-88eb-11e8-96cb-ea69a9ea13be.png)

Current behavior:
When you make a partial reception Odoo seems to use ordered_qty to calculate cost price.

Expected behavior:
Uses qty_done to make the correct cost computation:
![imagen](https://user-images.githubusercontent.com/11173802/42751831-5822817c-88ec-11e8-8076-79abac290632.png)

**Comment by pedrobaeza** [comment]
@jco-odoo another one to check

**Comment by AngelCamacho** [comment]
@jco-odoo No, it's always stock entries and it's a new product.  Did you make a partial entry at the second or third reception?

**Comment by jco-odoo** [comment]
second and it calculated correctly. In the code, it is using the quantity_done also.

**Comment by AngelCamacho** [comment]
@jco-odoo Issue closed. I have updated code and it works fine. Sorry, rookie mistake.
