### ISSUE TITLE
[11.0] Error accepting calendar invitation with empty description

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#25795]
Impacted versions:
11.0
### Steps to reproduce:
- ### Create a calendar event from a document (sale order, invoice, applicant ..)
![image](https://user-images.githubusercontent.com/10233975/42788124-54906394-8923-11e8-875d-dad7d158d7e2.png)
- ### Edit it and add new guest

![image](https://user-images.githubusercontent.com/10233975/42788143-6a8e5da4-8923-11e8-9447-00022b3d47fd.png)

- ### Accept / Open the invitation from guest mail
![image](https://user-images.githubusercontent.com/10233975/42788165-829ef4e4-8923-11e8-8b01-fecf0aca7986.png)

### Current behavior:

![image](https://user-images.githubusercontent.com/10233975/42788178-8fca413c-8923-11e8-97f9-5d2d8043b369.png)

![image](https://user-images.githubusercontent.com/10233975/42788181-96ed1570-8923-11e8-8804-f94f3a093f34.png)

Expected behavior:
Should render the invitation page.

http://348861-11-0-979b2e.runbot16.odoo.com
Replicated at http://runbot16.odoo.com/runbot/static/build/348861-11-0-979b2e/logs/job_30_run.txt

## The thing is that the event has to have a description in order to render correctly the invitation page.
![image](https://user-images.githubusercontent.com/10233975/42788218-eab9b082-8923-11e8-948e-6301dfb9d95b.png)
![image](https://user-images.githubusercontent.com/10233975/42788220-f009f920-8923-11e8-8244-50c2a4324202.png)

Video/Screenshot link (optional):

OPW 1867283

**Comment by Yenthe666** [comment]
@JKE-be can one of the guys from your team check it please?
