### ISSUE TITLE
Can we have some automated testing on all pull requests?

### ISSUE THREAD

**Issue by cclauss** [odoo/odoo#25800]
Something like Travis CI, Circle CI, AppVeyor to test all pull requests _before_ they are reviewed?
* https://github.com/marketplace/category/continuous-integration

**Comment by xmo-odoo** [comment]
Already the case.

**Comment by Yenthe666** [comment]
@cclauss I think you've missed the fact that this is already in place. You can see tests on every single PR. Have a look at https://github.com/odoo/odoo/pull/25798 for example.
