### ISSUE TITLE
Taxes doesn't show on POS when selected as 'python code' 

### ISSUE THREAD

**Issue by niketnishi** [odoo/odoo#25829]
Impacted versions:
11
Steps to reproduce:
--> Create a tax having child taxes
--> Go to edit mode and assign child taxes 'Tax Computation' as 'Python Code'
--> Now associate the tax with a product and go to point of sale screen
--> Add the same product to cart

Current behavior:
--> When you add a product taxes does not show up on order lines nor in the tax receipt that is generated.

Expected behavior:
--> When a product is added taxes should show up on order lines and on pos ticket.

**Comment by jorenvo** [comment]
Indeed, it's not expected to work at the moment and I currently see no way of implementing this. The only option is doing RPC calls on order modification which kind of goes against the usual POS way of doing things.

**Comment by pedrobaeza** [comment]
Thanks for the confirmation, @jorenvo. Then should we close this? I suggest to add to the README of the `account_tax_python` module that is not compatible for POS.

**Comment by niketnishi** [comment]
Can you suggest then to solve the problem of incorrct taxes in pos?

**Comment by pedrobaeza** [comment]
I'm afraid you can't use python taxes on POS as stated. You should use normal taxes, or develop a custom module that breaks offline mode for getting the Python tax value against server, but this is not being done on the core.

**Comment by niketnishi** [comment]
Ok @pedrobaeza  Thank You.
