### ISSUE TITLE
odoo/How to show computed field in search

### ISSUE THREAD

**Issue by tushardonga** [odoo/odoo#25820]
i have age field in my student.student model,it is computed filed  and i want to search my module by this age field as i know little bit computed field r not stored so what i have to do now for enable searching give me some tips about the .py code

**Comment by xmo-odoo** [comment]
This place is for bug reports rather than help, you want the forum for that.

That aside, the answer is to implement a "search" method on your field, see https://www.odoo.com/documentation/11.0/reference/orm.html#field-computed for the basics.

**Comment by Yenthe666** [comment]
P.S: You can find the forum at help.odoo.com
