### ISSUE TITLE
[11.0-IrAttachment] Incorrect Padding when decoding some attachments

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#25828]
Impacted versions:
11.0
Steps to reproduce:
Difficult to reproduce as we got this error in production and we do not control the sender's mail system
This issue happened in fetchmail process only with 2 senders... fetchmail works very well including decoding attachments with other received emails

Current behavior:
The mail stays in the hosted catchall mailbox
Here is the log on odo server
`"/var/opt/odoo/11.0/server/odoo/addons/base/ir/ir_attachment.py", line 239, in _compute_mimetype#012    mimetype = guess_mimetype(base64.b64decode(values['datas']))#012  File "/usr/lib64/python3.6/base64.py", line 87, in b64decode#012    return binascii.a2b_base64(s)#012binascii.Error: Incorrect padding`

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That solution is for fixing the symptom, not the cause, but this is very strange, as the value is coded Odoo side, so it should be a multiple of 4.

@tde-banana-odoo do you have any clue?

**Comment by invitu** [comment]
here are the complete logs... hope it helps...
` Message-Id <004001d4162f$282e8b80$788ba280$@xxx.fr>: direct reply to msg: model: crm.lead, thread_id: 60, custom_values: None, uid: 7
Jul 17 13:32:30 odoov11 journal: Odoo Server 11.0:xxx:INFO:odoo.addons.fetchmail.models.fetchmail:Failed to process mail from pop server Gandi.#012Traceback (most recent call last):#012  File "/var/opt/odoo/11.0/server/addons/fetchmail/models/fetchmail.py", line 210, in fetch_mail#012    res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, message, save_original=server.original, strip_attachments=(not server.attach))#012  File "/var/opt/odoo/11.0/server/addons/mail/models/mail_thread.py", line 1301, in message_process#012    thread_id = self.message_route_process(msg_txt, msg, routes)#012  File "/var/opt/odoo/11.0/server/addons/mail/models/mail_thread.py", line 1229, in message_route_process#012    new_msg = thread.message_post(subtype=subtype, partner_ids=partner_ids, **message_dict)#012  File "/var/opt/odoo/11.0/server/addons/rating/models/mail_thread.py", line 14, in message_post#012    message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)#012  File "/var/opt/odoo/11.0/server/addons/mail/models/mail_thread.py", line 1909, in message_post#012    new_message = MailMessage.create(values)#012  File "/var/opt/odoo/11.0/server/addons/mail/models/mail_message.py", line 776, in create#012    values['body'] = _image_dataurl.sub(base64_to_boundary, tools.ustr(values['body']))#012  File "/var/opt/odoo/11.0/server/addons/mail/models/mail_message.py", line 770, in base64_to_boundary#012    'res_model': 'mail.message',#012  File "/var/opt/odoo/11.0/server_20180627/odoo/addons/base/ir/ir_attachment.py", line 438, in create#012    values = self._check_contents(values)#012  File "/var/opt/odoo/11.0/server_20180627/odoo/addons/base/ir/ir_attachment.py", line 243, in _check_contents#012    mimetype = values['mimetype'] = self._compute_mimetype(values)#012  File "/var/opt/odoo/11.0/server_20180627/odoo/addons/base/ir/ir_attachment.py", line 239, in _compute_mimetype#012    mimetype = guess_mimetype(base64.b64decode(values['datas']))#012  File "/usr/lib64/python3.6/base64.py", line 87, in b64decode#012    return binascii.a2b_base64(s)#012binascii.Error: Incorrect padding`

**Comment by invitu** [comment]
I updated Steps to reproduce

**Comment by cvinh** [comment]
Incredible... we debugged that issue deeply and our conclusion is as following : 
- our customer has png images in his signature
- he sends an email from an odoo object... ie... a purchase order to suppliers
- the suppliers have ms outlook (several versions) as a mail client :-|
- when he answers the email, the png are truncated (it looks like randomly but always at 2061 characters)
- when odoo fetchs the mail from the suppliers, we have a 'Incorrect Padding' error as 2061 is not a multiple of 4
- the solution we applied is not to put images in email signature but links to images...

So it's definitly not a problem coming from odoo but from ms outlook !

Hope it helps...
