### ISSUE TITLE
[11.0] pos.config TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by PeterAlabaster** [odoo/odoo#25836]
Impacted versions:
11.0

Steps to reproduce:
* Create new `pos.config` record under `Point of Sale --> Configuration --> Point of Sale
* Name the record something, like `PeterTest`
* Click `Save`

Current behavior:
On some databases, I am not sure why - but I get the foillowing error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/point_of_sale/models/pos_config.py", line 336, in create
    'name': _('POS Order %s') % values['name'],
TypeError: not all arguments converted during string formatting
```

I have taken a look at the pos_config.py file, line 336, and it appears that it _may_? need tweaking from this:
```
            'name': _('POS Order %s') % values['name'],
```
to this:
```
                'name': _('POS Order {name}'.format(name=values['name'])),
```
or this:
```
                'name': _('POS Order %s' %values['name']),
```

I have verified that both tweaks solve the problem.

`values['name']` is always a type `<str>` which reads `PeterTest`, in both success and fail cases.

There is no neat way to tweak this via inheritance because for some reason this function has to call super. So for me it's either patch this change into the docker image, wait for upstream, or figure out why this happens

I would have made a PR - but I cannot understand _why_ this error is happening only on some databases, but not others - so cannot justify changing the codebase for it. I am expecting it to be an issue with a mis-loaded translation module?

It is worth noting that the database which is producing this error had its modules loaded and installed on v11 Odoo from about 6 months ago, but has been backed up and restored to run on a recent version. Please note that both databases are running from the same server.

Any insight onto this would be very useful

Expected behavior:
No error, the record should be saved

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is the problem reproducible in runbot (https://runbot.odoo.com)?

**Comment by PeterAlabaster** [comment]
Right, I have done some digging and it turns out this line `_('POS Order %s')` is returning `Sales Orders`.

Had a trunge through the database.. Lo and behold:
```
staging=# select * from ir_translation where src='POS Order %s';
  id   |                   name                    | res_id | lang  | type |     src      |    value     |    module     |   state    | comments 
-------+-------------------------------------------+--------+-------+------+--------------+--------------+---------------+------------+----------
 24638 | addons/point_of_sale/models/pos_config.py |    180 | en_GB | code | POS Order %s | Sales Orders | point_of_sale | translated | 
(1 row)
```

I am honestly clueless as to how this entry got here. But effectively the error comes from the fact that there is no longer a %s in the string which we are formatting, because it has been reformatted to `Sales Orders` by translation. If you try and do `print('hello' %'world')` then you get the same error.

All I need to do is remove that id from the database. I am curious to know how this translation got there.. Maybe it was in the codebase 6 months ago but has since been fixed? 

After deleting that, I then had to delete this one for a similar issue..
```
staging=# select * from ir_translation where src='POS order line %s';
  id   |                   name                    | res_id | lang  | type |    
    src        |    value    |    module     |   state    | comments 
-------+-------------------------------------------+--------+-------+------+----
---------------+-------------+---------------+------------+----------
 24639 | addons/point_of_sale/models/pos_config.py |    191 | en_GB | code | POS
 order line %s | Order Lines | point_of_sale | translated | 
(1 row)
```

So if anyone runs into this issue, just go into postgres and run the following:
```
DELETE FROM ir_translation WHERE src='POS Order %s';
DELETE FROM ir_translation WHERE src='POS order line %s';
```
