### ISSUE TITLE
Odoo 11 - WAAD + OAuth2 error: Access denied

### ISSUE THREAD

**Issue by LakshmiChowdam** [odoo/odoo#25835]
Hi, 

When we tried to login with WAAD (microsoft) credentials,  authentication is successful and at the time of redirecting, the odoo 11 giving "Access Denied" error. Below are the configurations used:

1) Created Windows Azure AD(WAAD) in azure portal with granted the  User.ReadWrite.All permissions and reply URL: http://localhost:8069/auth_oauth/signin?

2)  Installed OAuth2 authentication app in Odoo 11 application
3)  OAuth Providers settings in Odoo application
    a.  Provider Name - Windows Azure AD
    b.  Client ID – WAAD ID
    c.  Allowed – Enabled
    d.  Body - Login with Microsoft
    e.  Authentication URL - https://login.microsoftonline.com/tenantid/oauth2/authorize
    f.  Scope - User.ReadWrite.All
    g.  Validation URL: https://login.microsoftonline.com/tenantid/oauth2/token
    h.  Data URL: https://graph.windows.net/<tenantid>

When we tried with other options, we changed the Authentication URL to https://login.microsoftonline.com/tenantid/oauth2/authorize?response_type=code+id_token&response_mode=fragment&nonce=678910

Then we are getting the Access denied error.

also, customized the code accordingly so that id_token act as access_token and requests.post(endpoint, params={'access_token': access_token}) used instead of requests.get(), then Odoo giving an error "Sign up is not allowed on this database"

Suggest us how to resolve the error(s)?

Thanks,
Lakshmi Chowdam.

**Comment by pedrobaeza** [comment]
Do you have correctly setup the db_filter mechanism in your Odoo?

**Comment by LakshmiChowdam** [comment]
I am new to Odoo framework. Please let me know how to setup db_filter mechanism or direct me some url to setup the db_filter mechanism

**Comment by pedrobaeza** [comment]
Check for example https://elmerdpadilla.wordpress.com/2014/08/30/domain-based-db-filter/

**Comment by gdgellatly** [comment]
@LakshmiChowdam You have done everything right.  I use WAAD for auth and yes it takes some adjusting because of the google centric odoo approach.

You can see my current approach here https://github.com/odoonz/odoonz-addons/blob/11.0/auth_oauth_microsoft_graph/__manifest__.py - however I did used to do it with a post in the past and openid oauth flow like you have.

The error is simply because you aren't allowing signups, so you need to either change that setting, or you need to prepopulate the provider / credentials for users.

**Comment by pedrobaeza** [comment]
Thanks for the detailed info, @gdgellatly. You always try things that I have never imagined to use, hehe.

Any way, it seems it's not a problem of Odoo itself, so I close.

**Comment by LakshmiChowdam** [comment]
Thanks Pedro for your information. I tried to change the dbfilter configuration in odoo.conf as below:
           dbfilter = %d or dbfilter = ^%d or dbfilter = ^%d$
but getting the same Access denied error. 
Can you please suggest me the fix for the error

**Comment by LakshmiChowdam** [comment]
Thanks for your reply @gdgellatly. 
As for as my understanding, provided addon will download and placed in odoo 11.0 folder, then install it or am I missing anything

**Comment by jgamella** [comment]
Hi,

Anyone knows if it fixed. I'm trying with Azure and AWS Cognito with the same results. Error 2 access denied.

Best regards
