### ISSUE TITLE
Menu of integrated etherpad is not shown in users language

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#2583]
The menu bar of etherpad is not translated.
![bildschirmfoto 2014-09-21 um 17 17 46](https://cloud.githubusercontent.com/assets/8348598/4348950/d2debf38-41a2-11e4-8f5d-c68921a30249.png)

**Comment by Yenthe666** [comment]
Hi @tv-openbig ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
