### ISSUE TITLE
I am not convinced by this demo data

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#25839]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/42877272-348a8118-8add-11e8-898d-f37caaa39043.png)

**Comment by pedrobaeza** [comment]
@tivisse I think you were changing demo data. Can you check and give your opinion about this?

**Comment by pedrobaeza** [comment]
@gdgellatly check #25856 for seeing if this is fixed.

**Comment by gdgellatly** [comment]
@pedrobaeza Not at this stage, all that has happened is converting images to png in base.  No name changes.

**Comment by pedrobaeza** [comment]
OK, thanks for confirming.

**Comment by Yenthe666** [comment]
This has to be one of the best issues ever made. 😆

**Comment by intero-chz** [comment]
Maybe he identifies as female!? Or Arthur is just a female first name in other cultures? (Beware of sarcasm ;-))

**Comment by mreficent** [comment]
The PR can be closed, as Arthur Gomez has disappeared from the master demo data.

**Comment by Yenthe666** [comment]
Poor Arthur 😢
