### ISSUE TITLE
Odoo 11 - WAAD + OAuth2 error: Access denied

### ISSUE THREAD

**Issue by LakshmiChowdam** [odoo/odoo#25861]
Hi,

When we tried to login with WAAD (microsoft) credentials, authentication is successful and at the time of redirecting, the odoo 11 giving "Access Denied" error. Below are the configurations used:

1) Created Windows Azure AD(WAAD) in azure portal with granted the User.Read.All permissions and reply URL: http://localhost:8069/auth_oauth/signin?

2) Installed OAuth2 authentication app in Odoo 11 application

3) OAuth Providers settings in Odoo application
a. Provider Name - Windows Azure AD
b. Client ID – WAAD ID
c. Allowed – Enabled
d. Body - Login with Microsoft
e. Authentication URL - https://login.microsoftonline.com/tenantid/oauth2/authorize
f. Scope - User.Read.All
g. Validation URL: https://login.microsoftonline.com/tenantid/oauth2/token
h. Data URL: https://graph.windows.net/

code changes:
1) auth_oauth\controllers\main.py: function - list_providers()
line no: 62 -  params = dict(
                response_type='code',   - instead of reponse_type='token' used the 'code'
                client_id=provider['client_id'],
                redirect_uri=return_url,
                scope=provider['scope'],
                state=json.dumps(state),
            )
line no: 81 - token = request.params.get('code') - instead of 'token' used as 'code'

2) Also installed the module from the url - https://github.com/odoonz/odoonz-addons/tree/11.0/auth_oauth_microsoft_graph   and changed the code in models\res_users.py 

 def _auth_oauth_rpc(self, endpoint, access_token):
        if '**login.microsoftonline.com**' in endpoint:
            return requests.get(endpoint, headers={
                'Authorization': 'Bearer {}'.format(access_token)
            }).json()
        return super(ResUsers, self)._auth_oauth_rpc(endpoint, access_token)

Then getting the Access denied error. The log is as follows -
2018-07-18 16:11:13,267 12652 INFO OnePlatform requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): login.microsoftonline.com
2018-07-18 16:11:13,579 12652 ERROR OnePlatform odoo.addons.auth_oauth.controllers.main: OAuth2: Expecting value: line 3 column 1 (char 4)
Traceback (most recent call last):
  File "E:\Odoo 11.0\server\odoo\addons\auth_oauth\controllers\main.py", line 145, in signin
    credentials = env['res.users'].auth_oauth(provider, kw)
  File "E:\Odoo 11.0\server\odoo\addons\auth_oauth\models\res_users.py", line 119, in auth_oauth
    validation = self._auth_oauth_validate(provider, access_token)
  File "E:\Odoo 11.0\server\odoo\addons\auth_oauth\models\res_users.py", line 51, in _auth_oauth_validate
    validation = self._auth_oauth_rpc(oauth_provider.validation_endpoint, access_token)
  **File "E:\Odoo 11.0\server\odoo\addons\auth_oauth_microsoft\models\res_users.py", line 17, in _auth_oauth_rpc
    'Authorization': 'Bearer {}'.format(access_token)**
  File "E:\Odoo 11.0\python\lib\site-packages\requests\models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\Odoo 11.0\python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "E:\Odoo 11.0\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Odoo 11.0\python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

Suggest us how to resolve the error?

**Note: Please do not close until I give clearence**

Thanks,
Lakshmi Chowdam.

**Comment by pedrobaeza** [comment]
But as said previously in the previous issue, this is not an Odoo error, but on your configuration, and this issue tracker is not a free technical consultancy service. You have to thanks @gdgellatly for giving you enough hints for solving your configuration problem. Said that, there's nothing more than we can do.
