### ISSUE TITLE
Some modules descriptions are not updated to Odoo (ex. gamification)

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#2586]
Some modules descriptions still relate to "OpenERP" instead of "Odoo".
I have attached one example here 
![bildschirmfoto 2014-09-21 um 17 43 25](https://cloud.githubusercontent.com/assets/8348598/4349048/5e4e7c04-41a6-11e4-8f4a-099dc610374d.png)
(gamification)

**Comment by Yenthe666** [comment]
Hi @tv-openbig,

This was indeed not yet changed in the older versions.
Starting from the next version, V10 (currently master), all descriptions will be "Odoo" instead of "OpenERP".
This is not something that will be changed in older versions.

Regards,
Yenthe
