### ISSUE TITLE
Source Document is empty in Quotation created from Opportunity

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#25876]
## Impacted versions:

11.0

## Steps to reproduce:

From an opportunity click on the `New Quotation` button

## Current behavior:

Created quotation have the Source Document field empty

## Expected behavior:

Created quotation should have the Opportunity name set in the Source Document field

Here is a [video](https://youtu.be/gofnL1U6tS4) showing the case

**Comment by zaoral** [comment]
FYI opw 1867985

**Comment by zaoral** [comment]
If you agree with this premise then the solution to this problem is already solved in PR https://github.com/odoo/odoo/pull/25877

**Comment by rim-odoo** [comment]
No need to create a GH issue if you have a PR already ready :)

**Comment by zaoral** [comment]
@rim-odoo thanks, got it
