### ISSUE TITLE
Multiple Issues Compiled in PDF

### ISSUE THREAD

**Issue by oks1998** [odoo/odoo#25881]
Impacted versions:
Odoo 10.0-20180717 (Community Edition)

[bug report (1).pdf](https://github.com/odoo/odoo/files/2212290/bug.report.1.pdf)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you or in the proper repository (and in a proper form, not in an embedded PDF).
