### ISSUE TITLE
Warehouse is not changing in Quotation?

### ISSUE THREAD

**Issue by AjayViknesh** [odoo/odoo#25892]
I am new to odoo.

I created 3 warehouses "WH", "WH1", "WH2" and created a product "Demo" with qty only in warehouse "WH1".

When I order the product from the site the order is created but the warehouse is in default "WH" because of that I am not able to reserve the product or validate it.

How to change the warehouse dynamically based on the product, or is there any other method to achieve and reserve the product and validate it for delivery

**Comment by Yenthe666** [comment]
Hi @AjayViknesh,

Sorry but the Github issue tracker is only for issues in the official code, it is not the place to ask questions.
You can do this on the official help forum at help.odoo.com though!

Regards,
Yenthe
