### ISSUE TITLE
[trunk] Import csv with field date "Perhaps you need a different 'datestyle' setting"

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#259]
1) Steps to reproduce the issue you have observed
Edit postgresql.conf
Set datestyle = 'iso, mdy'
cat postgresql.conf | grep datestyle
datestyle = 'iso, mdy'

Start openerp-server
Set you language date format to: %d/%m/%Y
![languages openerp](https://cloud.githubusercontent.com/assets/6644187/3108376/029835b0-e690-11e3-8c97-116ddc1f2553.png)

Create a new csv to stock.move.csv with date=20/07/2000
Try to import this csv

2) The result you observed
HINT:  Perhaps you need a different "datestyle" setting.

3) The result you expected
Importing data

4) The platform you are using (and browser version, if relevant)
trunk
commit a91a12e67f0b70cf6fe121a340c9fa67b58fb72f
Merge: 1779495 fc9d0d9

**Comment by Yenthe666** [comment]
Dear @moylop260,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
