### ISSUE TITLE
Gamification models/challenge.py domain ValueError - missing field 'ids' in table gamification_goal

### ISSUE THREAD

**Issue by vedler** [odoo/odoo#25913]
Calling the function _get_serialized_challenge_lines with a non-empty restrict_goals gives a missing field ValueError ("ValueError: Invalid field 'ids' ..."). Tested with no custom modules installed and when refreshing a started challenge after changing it.

Linked the line where the domain append seems to have a typo in it, where the field being referenced is most likely intended to be 'id' instead of 'ids'. Code for building the domain is present since Odoo 8, where it came up in testing. Confirmed to still be an issue in Odoo 11 too when testing it there, as the domain building code itself hasn't changed much at all in that part.

https://github.com/odoo/odoo/blob/11.0/addons/gamification/models/challenge.py#L480

**Comment by mart-e** [comment]
Hi,

Thanks for the report and analysis, you are right.
It will be fixed at #54363
