### ISSUE TITLE
POS Price button access rights not working properly

### ISSUE THREAD

**Issue by captainjapeng** [odoo/odoo#25914]
Impacted versions:
Odoo 11

Steps to reproduce:
Setup two users, one with User role and the other with Manager
Login with the account with a User role, open a POS Session. Price button will be disabled
Switch the current cashier to the one with the Manager role. Price button should be enabled but still disabled.
Switch back to the User role and the Price button will be enabled.

Current behavior:
Price Button's access rights are applied using the role of the previously selected cashier.

Expected behavior:
Access Rights should be using the newly selected cashier's role

Video/Screenshot link (optional):

**Comment by captainjapeng** [comment]
Code with the problem:
_screen.js_ on the _point_of_sale_ module:
`this.pos.bind('change:cashier', this.applyAccessRights, this);`

When this code runs, `this.pos.get_cashier().role` still evaluates to the previous cashier.

**Comment by Yenthe666** [comment]
@pimodoo could you check please?

**Comment by captainjapeng** [comment]
I was trying to replicate this functionality to the other buttons and found out this issue. Solved it by adding a `setTimeout` as the callback before calling the real function.

**Comment by switch87** [comment]
Solved  by https://github.com/odoo/odoo/pull/26829
