### ISSUE TITLE
Invisible product variant cost

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#25911]
Impacted versions: 11

Steps to reproduce:
See Form of product variant (porduct with many variants),
for example on https://demo3.odoo.com - Inventory/Products variants/[E-COM01] iPad Retina Display (White, 16 GB)

Current behavior:
Value of field is_product_variant = False

Expected behavior:
Product variant cost visible

PS. It would be good if cost should be visible in tree too.

**Comment by pedrobaeza** [comment]
`is_product_variant` is a technical field intended for specifying if the record is of type `product.template` or `product.product`, but it doesn't act as a pointer to say if there are variants, so there's no issue there.

About the cost, it's hidden by purpose due to the way it's designed.

**Comment by zbik2607** [comment]
See this commit: https://github.com/odoo/odoo/commit/7e724f96c55815728d478a889ff5f1a0314dcc16#diff-7525de0c57e690342ed3108fc9dcc8c2

and this code in product_template_form_view:
`<label for="standard_price" groups="base.group_user" attrs="{'invisible': [('product_variant_count', '&gt;', 1), ('is_product_variant', '=', False)]}"/>`

In this code, in last my branch,  value is_product_variant is always = False

If you're right, the template code and commit is unnecessary.

**Comment by zbik2607** [comment]
@pedrobaeza, my comment to closing this bug: https://github.com/odoo/odoo/commit/07cdd24f30c221de96dc1dda452959f9ae358c12
