### ISSUE TITLE
[V8] Record Rules not applied on written data.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#2592]
It seems that writing record rules are checked before writing data, but not after.

For example, create a record rule:

| Data | Value |
| --- | --- |
| Model | Product Template |
| Rule Definition | [('default_code','=','xxx')] |
| Apply for Read | False |
| Apply for Write | True |
| Apply for Create | True |
| Apply for Delete | True |

With this rule in place, you can find a product with default code 'xxx' and modify it.  You can even change the default code to 'abc' and write it.  You cannot change it back from 'abc' to 'xxx' (which I agree is correct)

I believe in v7 the rules were checked before and after writing (?!) - this seems to be the more logical interpretation.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
