### ISSUE TITLE
[11.0][mrp_repair] Missing widget:  kanban_label_selection  for field state of type selection

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25928]
Impacted versions:
`Odoo 11.0-20180723 (Community Edition)`

Steps to reproduce:

1. Install Repair module
2. Go to the module's panel

Current behavior:
Browser's console gives me the next warning message: `Missing widget:  kanban_label_selection  for field state of type selection`.

Expected behavior:
No warning messages.

Video/Screenshot link (optional):
![mensajeadvertenciareparacion](https://user-images.githubusercontent.com/5034215/43083876-2cd3afa0-8ea0-11e8-87bc-aaee1ff2bd39.png)

Notes:
- I tested this three times with a fulfilled databases.
- I tested this finally with a clean database, as you can see in the screenshot.

**Comment by hmen89** [comment]
Module web_kanban is missing.

https://github.com/odoo-dev/odoo/blob/c91f40ba76e5cb56c12d824d6cc4df6474a6339c/addons/web_kanban/static/src/js/kanban_widgets.js#L283

This module adds the widget and it does not exist on 11.0

**Comment by mge-odoo** [comment]
Thanks for reporting the issue. It has been fixed by the PR #31643
