### ISSUE TITLE
Odoo website background pictures

### ISSUE THREAD

**Issue by CarlijnPeeters** [odoo/odoo#25924]
Hi,

I have build a website with the websitebuilder from Odoo. However, an annoying bug seems to appear. When I place a backgroundpicture on the homepage, which is the first thing people will see, it looks all fine on my laptop. However, when I look at the website with a bigger size computer screen, the picture doesn't fully fit anymore even though both screens are set at 100%. Next to that, I clicked on 'fixed size' of the picture when editting. My question is how this can be fixed? How can that picture be fixed size, instead of scaling differently on different devices?
I would like to hear from you. Thanks in advance.

Kind regards,
Carlijn Peeters
Alpiek BV

![screenshot 50](https://user-images.githubusercontent.com/41581167/43080825-e3bf2d8a-8e90-11e8-910e-39f5a58b1265.png)

![alpiek_screenshot_homepage_100](https://user-images.githubusercontent.com/41581167/43080797-d9b33192-8e90-11e8-8b3e-330a1f516c3f.png)

![screenshot 52 _li](https://user-images.githubusercontent.com/41581167/43081130-93cc45f0-8e91-11e8-9812-c06422d62700.jpg)

**Comment by CarlijnPeeters** [comment]
I'm still having issues with this. Can someone help me out please?
Kind regards,
Carlijn Peeters

**Comment by Yenthe666** [comment]
@CarlijnPeeters why don't you make an official Odoo ticket? You're a partner 😉

**Comment by rdeodoo** [comment]
Handled with opw-1878171
