### ISSUE TITLE
[11.0]Sale order group order by month, group by date_order  not date_confirmation

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#25932]
Impacted versions:
11.0

Steps to reproduce:
1.- Create a database with demo activated
2.- install sale manager
3.- go to sales
4.- click on orders

Current behavior:

Orders is grouping by date_order ( same quotations) and confuse  when is grouping in orders

Expected behavior:

in menu orders, group by date_confirmation

Video/Screenshot link (optional):

<img src="https://dl.dropbox.com/s/edad3xu03i0620t/Captura%20de%20pantalla%20de%202018-07-23%2019-24-03.png" />

**Comment by Yenthe666** [comment]
Hi @dansanti,

Thanks a lot for the report.
I'm not sure if I get you. Do you mean that it is confusing that the dates shown are the "Order date" while it groups on another date field or?

**Comment by dansanti** [comment]
Hi!
 When you click on quotation's links and click on 'Order month' group,  expect see groups by order_date.  When you click on order's link and click on 'Order month' group, expect  group by confirmation_date,

because, if you see on image, tree display confirmation _date, and label of group mismatch to it

**Comment by Yenthe666** [comment]
@nim-odoo could you have a look please?
