### ISSUE TITLE
[11.0][website_sale] Missing widget:  checkbox  for field group_website_multiimage of type boolean

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#25936]
Impacted versions:
`Odoo 11.0-20180723 (Community Edition)`

Steps to reproduce:

1. Install eCommerce module
2. Go to the Settings panel

Current behavior:
Browser's console gives me the next warning message: `Missing widget:  checkbox  for field group_website_multiimage of type boolean`.

Expected behavior:
No warning messages.

Video/Screenshot link (optional):
![mismoproblemaconwebsale](https://user-images.githubusercontent.com/5034215/43124134-e0aa0162-8f2e-11e8-9463-3cf22fbd828e.png)

Notes:
- I tested this three times with a fulfilled databases.
- I tested this finally with a clean database, as you can see in the screenshot.

**Comment by Yenthe666** [comment]
@JKE-be could you or somebody from your team check please?
