### ISSUE TITLE
Remove forward slash on account move line of posted invoices (inn and out)

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#25938]
Impacted versions: 9, 10, 11

Steps to reproduce: create an inn and an out invoice, the first account move line posted will have a forward slash as text in the "label" field (account_move_line.name).

Current behavior: forward slash "/" is used as entry text

Expected behavior: more useful text... for invoice-out the internally generated invoice number (sequence number) for invoice-inn (supplier invoice) the external invoice number (not the internally generated sequence number).

Video/Screenshot link (optional):

**Comment by ahetland** [comment]
A forward slash is not very helpful information for the accountant, this could hence be improved.

**Comment by Yenthe666** [comment]
Hi @ahetland,

I don't really see the problem in this honestly. Why would you want it to be removed/changed?
CC @qdp-odoo I assume that you really don't want to change this, right?

**Comment by ahetland** [comment]
Hi Yenthe666, I have many comments from odoo users (accountants) who do not see the information value of a forward slash, when reading accounting entries it should be easy and understandable for the user what he/she is seeing. Also if you look at the payment reminders you will have forward slashes, this is no good communication to customers right?

**Comment by qdp-odoo** [comment]
I agree on the principle of removing the '/' but I'd target master only to avoid confusing people that adopted/accepted this behavior on their instance. 

BTW, this is something we already started as the name field of account.move.line object isn't required anymore. 

@smetl can you do that please?

**Comment by qdp-odoo** [comment]
landed in master, for saas11.5, at revision https://github.com/odoo/odoo/commit/858893494f756351d1a4061e384e5eb081c8e405

thanks

**Comment by qdp-odoo** [comment]
if I'm not wrong, these info are already in the 'reference' field of the move

**Comment by ahetland** [comment]
... yes you are, that the information is already present should make it easier to add in the field. Accounting systems should be easy to read and understand (in gaap standard I believe the requirement is something as "financial information should be presented in such a way that a person with a reasonable knowledge of business and finance, and the willingness to study the information, should be able to comprehend it" a forward slash or empty has no meaning. All well kept books use descriptive text when posting an entry, the invoice number (note in case of invoice-out the odoo sequence number, in invoice-inn the vendor reference number) will be of importance when reading the accounts. Also the reports generated are wrong or insufficient when based on this field when the content is empty. See for example the reminder report.

**Comment by ahetland** [comment]
Just a question, is there no one with accounting experience that also evaluates the accounting tickets in Odoo? I have raised several tickets here which I with my 17 years of accounting experience can guarantee are important to an accounting system.

**Comment by tr33** [comment]
I fully agree with ahetland. 
More descriptive lines would absolutely help to meet common compliance standards.

E.g. contents of account.move.ref could be copied into account move line?
A more flexible solution could involve a configuration with simple template tags like '${module.model.field}' or something.

How much efford would this need?
