### ISSUE TITLE
Customers statements history in UTC

### ISSUE THREAD

**Issue by BT-nfrancisco** [odoo/odoo#25953]
Impacted versions: 10.0

**Steps to reproduce**: Create an invoice for a company and set as a date some months ago, add a product and validate it. Go to Accounting->Sales->Customers Statements and you should see the previous company with an unpaid invoice. Log a note. Refresh the screen and click in history. The time shown in the history is in UTC, regardless what you have in your settings.

**Current behavior**: TIme in UTC

**Expected behavior**: Time in UTC + 2

**Video/Screenshot link (optional)**: https://youtu.be/L6wO8DW5AqY

**Comment by sswapnesh** [comment]
Did you configured Timezone in User's preference ?

**Comment by BT-nfrancisco** [comment]
The time shown in the history is in UTC, regardless what timezone you have selected in your settings.

**Comment by pedrobaeza** [comment]
If this is still happening, please put an OPW ticket at https://www.odoo.com/help, as this is something specific of an enterprise module, which doesn't belong to this repository.

Closing the issue by the reason above.
