### ISSUE TITLE
Update on hand quantity for the new product show error "The cost of the product P is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation"

### ISSUE THREAD

**Issue by robinhli** [odoo/odoo#25954]
Impacted versions: 11.0

Steps to reproduce: setup a new product, with no product variant. setup the product category inventory valuation as "Automated", Costing Method as "Standard Price"

Current behavior: update the onhand quantity. it prompts  "The cost of XXX is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation. "

Expected behavior: can update the on hand quantity

Video/Screenshot link (optional):

I have pick up the fix #25786

**Comment by robinhli** [comment]
Even I created a PO, then validate the WH/IN/xxxx, it show same prompt. How can I get the throught?
I go through this step by step with debug mode, but I still can't find why the cost is 0, and how/where can I setup the cost to non-zero?

Thanks

**Comment by pna-odoo** [comment]
Once you save the product page, you can find the 'Update Cost' link.
![ipad mini odoo](https://user-images.githubusercontent.com/7599574/43381363-104ffd5a-93f2-11e8-8c7c-df6475a89fc9.png)
