### ISSUE TITLE
[All] product_pricelist: New products can't benefit from standard_price with FIFO valuation

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#25977]
### Impacted versions:
All

### Steps to reproduce:
- Create the **New Product**, set a cost of $100 in the product template.
- Create a RFQ with the **New Product** (the supplier changes the price to $150 before receiving)
- Receive the New Product
- Add a landed costs of $50
- Add this New Product to the _Standard Pricelist_, with `base` based on `standard_price` an a margin of %100 (`-100`)
- Add New Product to a SO.

### Current behavior:
Product price = $200
(this is just considering the standard_price set on product creation)

### Expected behavior:
Product price = $400
(this considers the PO + Landed Cost)

A company with its core business being buying products from abroad and selling locally, needs to sale based on the the real cost (PO + Landed Cost). Otherwise it could be selling below the product cost.

**Comment by gustavovalverde** [comment]
Maybe using the `stock_value` instead of the standard_price could be a solution for this one.

**Comment by mga-odoo** [comment]
@gustavovalverde may be its not a software issues even in real-life its a challenge

Please go through the answer given by @vcloud9ray at https://github.com/odoo/odoo/issues/25604. It is relevant can be applicable for your case too. 

What I understand about the price change in your case, as a customer you accept change in purchase price, does that means your customer should accept the change in price? Once the delivery done the price can be updated on the sales order of course manually as of now if you really want to have the accurate customer price based on the real cost price.

**Comment by gustavovalverde** [comment]
@mga-odoo the deal breaker here is that we can't use pricelists based on `standard_price` because they won't work on new products (that haven't been sold).

Importing thousands of new products weekly and _trying_ to manually update sales order isn't a solution. This is a real (and very common use case), that should be handled by Odoo when importing goods.

I think we should be focusing in the `standard_price` used on the product:
- Is this the right value to consider when using a pricelist based on cost?
or
- Shouldn't the `standard_price` in the product get updated when buying new products and also when adding landed costs to it?

**Comment by mga-odoo** [comment]
Pricelist or Standard Price is not a problem, let's take an example to understand the real challenge

You purchase (import may be in your case), 4 qty of Product through four different purchase orders, and they purchased at different price

  | Purchase Price | Cost as per Inventory
-- | -- | --
Product | 110 | 110
Product | 120 | 120
Product | 105 | 105
Product | 115 | 115

There are many challenging cases, consider only 2 of them as below:
1. What if two customers (at a same time) come and ask for the quotation of Product (1 qty on each quotation), what price you should give and how it should be computed?
2. What if customer come and ask for the quotation of Product (4 qty in total), what price you should give and how it should be computed?

The reservation of the Product done at Inventory level and not at the Quotation/Order level, the earliest stage you will come to know the cost price once the product will be reserved on the delivery order and not before that (quotation or sales order).

**Comment by gustavovalverde** [comment]
First, let's segregate a Financial approach vs a Logistic approach.

> This problem is mainly caused because Odoo is trying to match an accounting behavior with a functional and logistic behavior (difference discussed here: https://github.com/odoo/odoo/issues/25055#issuecomment-406986634). A company doesn't have to wait for an accounting entry to set a selling price. And in a real-life scenario the price shouldn't fluctuate with each single sale.

Considering the above, and that from a Financial FIFO we can have an AVCO, I can answer both of your questions with 1 answer:
- Use an AVCO of **$112.5**, with a margin of **%100** I could easily sell them at **$225**. With a rounding of $10 I can handle a 90% of the fluctuation caused by the FIFO as the product start selling, without changing the final price.

**Side Note:** We wanted to use AVCO for this products but Landed Cost on AVCO was removed since https://github.com/odoo/odoo/commit/061874853e28ac473919675fb8d0cc8daed195d2#diff-37e64c3fafcf2d21a2545159f7f4d2c8L134

**Comment by mga-odoo** [comment]
Exactly that will be proposal that AVCO can satisfy your need.  Let's compute the profit using both methods FIFO and AVCO.

Profit when you sell cost + 100% margin, the cost computed based on the FIFO

  | Purchase Price | Cost | Sales Price | Profit (FIFO)
-- | -- | -- | -- | --
Product | 110 | 110 | 220 | 110
Product | 120 | 120 | 240 | 120a
Product | 105 | 105 | 210 | 105
Product | 115 | 115 | 230 | 115
  |   |   |   | 450

Profit when you sell cost + 100% margin, the cost computed based on the AVCO

  | Purchase Price | Cost | Sales Price | Profit (AVCO)
-- | -- | -- | -- | --
Product | 110 | 110.00 | 220.00 | 110.00
Product | 120 | 115.00 | 230.00 | 115.00
Product | 105 | 111.67 | 223.33 | 111.67
Product | 115 | 112.50 | 225.00 | 112.50
  |   |   |   | 449.17

You can use the Landed cost even with AVCO, simply divid the transportation cost per unit in warehouse, so after receiving 4 units the cost per unit is 112.50, the transportation cost for the last unit purchase is 50. 

Set the product cost manually by computing the new cost, 
Product Current Cost Price + (Transportation Cost / Total unit in warehouse)
112.50 + (50/4) = 125

Apply the new cost price manually on the product, (or may be you have to automate only that part)
![step-1](https://user-images.githubusercontent.com/7595796/43604564-b7ee2ad2-96b3-11e8-9ce3-4339f13cf51f.png)

Select the correct account (i.e. Transportation Exp.), the cost will be increased and you will have an accounting entry too.

![step-2](https://user-images.githubusercontent.com/7595796/43604785-47023bd2-96b4-11e8-922d-d71a967cbf83.png)

**Comment by gustavovalverde** [comment]
This is not functional nor easy at all.

We use landed costs because of the complex distribution that implies doing it based on cost; which would require us to depend on excel to calculate the distribution and then making a module with automated actions to distribute those cost to the products.

Even so, using this method would arise a bunch of consequences:
- Manual Input of costs
- No validation of total distribution
- No multi-type distribution (per cost, per unit, per weight)
- Use of Excel

And this is a pin-pointed solution for a General Issue (people on Odoo Online, for example, won't have a solution).

We can't put Landed Cost aside (this is a major feature for import dependent countries), and we even convinced our clients to use FIFO costing method to keep this functionality. Solutions would be:
- Having Landed Cost with AVCO
- Having FIFO set a standard_price on the product.template before selling (so a margin can be correctly used on the first sale).

**Side note**: I actually don't understand why AVCO was removed from the landed costs module.

**Comment by pedrobaeza** [comment]
@mga-odoo is this still applicable?
