### ISSUE TITLE
Duplicated reception not linked to purchase order

### ISSUE THREAD

**Issue by david-th** [odoo/odoo#25976]
**Impacted versions:** 11EE

**Steps to reproduce:**
1. validate purchase order
2. go to shipment
3. duplicate shipment
4. go back to purchase order

**Current behavior:**
duplicated shipment is created
duplicated shipment is not accessible via purchase order. 

**Expected behavior:**
duplicated shipment is linked to purchase order and can be seen via button "shipments"
Should be working exactly as it does on Sales Order, where this functions flawlessly.
It is needed to duplicate shipment if the original has been cancelled, because it is not possible to set it back to draft. 

i tested on demo.odoo.com
community version as tested on runbot does not seem to be affected

Video/Screenshot link (optional):
![grafik](https://user-images.githubusercontent.com/35835585/43212720-0c404668-9035-11e8-8398-734fcc32a43a.png)

![grafik](https://user-images.githubusercontent.com/35835585/43212708-049f410c-9035-11e8-811e-0f9196e70f80.png)

**Comment by Yenthe666** [comment]
Hi @david-th,

Thanks a lot for your report, I believe this should indeed work.
Why don't you report it through odoo.com/help with your official enterprise license? 
@sle-odoo this looks like one for you though.

Regards,
Yenthe

**Comment by david-th** [comment]
Hi @Yenthe666 

I reported it:
_Task - Duplicated reception not linked to purchase order_ (#1869464) 

Regards David

**Comment by Yenthe666** [comment]
Thanks a lot @david-th 👍

**Comment by sswapnesh** [comment]
BTW this works well in v11 Community.

![s1](https://user-images.githubusercontent.com/16624719/43337728-49ca2eea-91f2-11e8-9529-9d8619f6927a.png)
![s2](https://user-images.githubusercontent.com/16624719/43337731-4b098d6e-91f2-11e8-8fb3-43e817664a16.png)

**Comment by david-th** [comment]
Odoo gave me Feedback, they checked in latest v11 branch & says it's working well.
(See attached video regarding given scenario)

As far as I can see I also have the latest Version (is there another way to get the version?)
![grafik](https://user-images.githubusercontent.com/35835585/43386739-e43f2784-93e4-11e8-9e24-7ab112c2119b.png)

Isn’t the latest branch also installed for demo.odoo.com ?

In the video there are just 5 apps installed, maybe there is a cross-dependency that causes the problem? (e.g. manufacturing / MPS ?) 
[DO_linked_to_PO.zip](https://github.com/odoo/odoo/files/2240310/DO_linked_to_PO.zip)

Regards David

**Comment by david-th** [comment]
Problem is solved with latest revision
