### ISSUE TITLE
Portal user is able to see other project not intended for him/her - Odoo 11 EE

### ISSUE THREAD

**Issue by Patrickar** [odoo/odoo#25988]
Impacted versions:
Version 11 EE

Steps to reproduce:
1. Invite customer to be portal user
2. Log in as user in the portal
3. Click on my account
4. click on tasks
5. click on filter

Current behavior:
When clicking on filter, the customer is able to see also other projects done for other customers (image1). The projects that are visible are the projects with the setting: "visible by following customers" (image 2)

Expected behavior:
A customer should only see his own projects, and not projects for other customers. In addition, the setting: "visible by following customers" should only count for the customer that is selected.

Video/Screenshot link (optional):

![image1](https://user-images.githubusercontent.com/36632285/43261043-9ec9c92c-90db-11e8-82d5-b6e9315cdc59.png)
![image_2](https://user-images.githubusercontent.com/36632285/43261045-9ee58ab8-90db-11e8-8562-4bee48633450.png)

**Comment by Patrickar** [comment]
Hello Yenthe666. 

I noticed that you labeled this issue, however, we are three weeks from adding this issue and I am not seeing any response so far? 

I hear from you.

Kind regards, 
Patrick

**Comment by Yenthe666** [comment]
Hi @Patrickar,

I'm working as a contributor to manage/help on issues, I don't work for Odoo itself in case you don't know.
Basically somebody from Odoo (or a contributor) needs to test the whole flow, confirm it and then a fix can be made but it is a best effort.

P.S: I see you have an enterprise edition. Do you know you can report the issue through odoo.com/help? Then it has to be handled by Odoo with a priority.

**Comment by Patrickar** [comment]
Hi Yenthe,

Aah ok. Very clear, thank you;)!

I will escalate to odoo.com/help. Thanks for your quick response!

Met vriendelijke groeten,

*Patrick Ariëns*
Consultant | Odoo Gold Partner

+31 (0) 6 30 30 34 56
patrick@alpiek.nl




Alpiek BV
+31 (0) 85 333 000 8
www.alpiek.nl
Odoo Gold Partner





2018-08-15 15:08 GMT+02:00 Yenthe V.G <notifications@github.com>:

**Comment by Yenthe666** [comment]
You're welcome! Please do let us know what the response from Odoo is if they forget to handle it here.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 11.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
