### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#25995]
Impacted versions:
11.0
Greetings !
I'm using Odoo from version 10.0. In initial stage preferred PostgreSQL queries. After I preferred ORM.
Now i'm deleting 2000 records using ORM it's very slower taking 5 minutes to delete the 2000 records.
But using postgreSQL queries it take the 2 to 3 seconds.
Which is better either ORM or directly handing Queries.
Thanks and Sorry for my Poor Communication.

**Comment by Yenthe666** [comment]
Hi @Gokulakannanaj,

Ofcourse a direct query is faster. It doesn't go through the Odoo ORM and there are no validations/check which Odoo provide by default.
In short: direct queries are much faster but there are no safety checks on anything so you have to be careful. The ORM is great at validations, checks and domains.
