### ISSUE TITLE
Performance issue opening POS session as UID!=1

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#26001]
**Impacted versions:**
v10, arround 4252cd70536 with some adaptions

**Problem:**

- Open a (single) POS Session view as `UID=1` it returns in about 4 sec
- Open a (single) POS Session view as `UID!=1` it returns in about **51 sec**

**Analysis:**
[profiling4.zip](https://github.com/odoo/odoo/files/2233389/profiling4.zip)
As with related issues (section "see also", item B), the graph shows that the `domain_get` / `_where_calc` / `parse` is accounting for almost half of it (in sum).

**See also:**
A: https://github.com/odoo/odoo/issues/25967
B: https://github.com/odoo/odoo/issues/25912 & https://github.com/odoo/odoo/pull/25978

OPW: 1868698

**Comment by nseinlet** [comment]
Hi @blaggacao , could you show the used record rules? Do you use some custom ones?

**Comment by blaggacao** [comment]
@nseinlet Not extra ones, but we adapted some, like `stock.stock_picking_rule`
```
['|', '|', ('company_id', '=', False), ('company_id', 'child_of', [7]), ('move_lines.move_orig_ids.company_id', 'child_of', [7])]
```

Here is the full rule table, you might want to filter arround at your conveience or let me know if you prefer only specific columns...
[ir.rule.zip](https://github.com/odoo/odoo/files/2241299/ir.rule.zip)

**Comment by nseinlet** [comment]
@blaggacao Problem comes out the ('move_lines.move_orig_ids.company_id', 'child_of', [7])

The ORM search for all companies child of 7, then for id of moves (move_orig_ids) with company_id = one the childs, and with this list of ids, search for move_lines where move_orig_id = any(ids found earlier), and then the pickings. 

With million lines.... 

You can :
- use auto_join=True on fields , but this will bypass some record rules
- store the related move_lines.move_orig_ids.company_id on the stock_picking and index it

The second solution is the smartest one.

**Comment by blaggacao** [comment]
@nseinlet It's chilling to see what your experience produced in such record time. Bid thanks! 

**Duly noted:** Look at record rules first and don't be too creative...

I'll leave this issue open to give any feedback as I implement your recommendations, if that's ok for you...

**Comment by blaggacao** [comment]
@nseinlet 
- With your second recommendation it comes down to approx. 17 sec
- With standard record rules it is still 16 secs.


stock_picking multi-company
--
`['|','|',('company_id','=',False),('company_id','child_of',[user.company_id.id]),('x_orig_company_id', 'child_of',[user.company_id.id])]`


stock_move multi-company
--
`['|', '|', '|', ('company_id','=',False), ('company_id','child_of',[user.company_id.id]), ('x_dest_company_id','child_of',[user.company_id.id]), ('x_orig_company_id','child_of',[user.company_id.id])]`

Both `x_orig_company_id` are stored and indexed.

I will investigate further tomorrow...

**Comment by Yenthe666** [comment]
@blaggacao what is the status of this bug report (and the related OPW)?

**Comment by blaggacao** [comment]
I guess I abandoned this. Don't remember the reason...
