### ISSUE TITLE
Bug in purchase order line related "state" field (it should be store=True) [Typo in file there is stored=True]

### ISSUE THREAD

**Issue by miteshsa-onnet** [odoo/odoo#26004]
Impacted versions: 9.0

Steps to reproduce: Add view for "purchase order line" and try to group by state.

Current behavior: KeyError: u'state'

Expected behavior: it should be able to group by.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @miteshsa-onnet,

Thanks for your report.
Can you please link to the location where this is wrong? Even better is a PR to fix it right away!

Regards,
Yenthe

**Comment by sswapnesh** [comment]
That's because of `state` field is not stored in database so it can not be used for Group by. (it is because of Typo in field definition)
I have added PR #26477 for same.

**Comment by mart-e** [comment]
Sorry but we can not change that in a stable version. This kind of database schema changes must target  the master branch, not a stable one.
