### ISSUE TITLE
Mass mailind cron non latin domain search in relational fields

### ISSUE THREAD

**Issue by sergeiruzkiicode** [odoo/odoo#26015]
Impacted versions:
11.0e
Steps to reproduce:
User has set language as russian.
Add mass mailind with domain like
`["|","|","|","|","|","|","|","|","|","|","|","|","|","|","|","|","|","|",["country_id","=","Польша"],["country_id","=","Латвия"],["country_id","=","Литва"],["country_id","=","Израиль"],["country_id","=","Эстония"],["country_id","=","Бельгия"],["country_id","=","Франция"],["country_id","=","Португалия"],["country_id","=","Нидерланды"],["country_id","=","Дания"],["country_id","=","Чешская республика"],["country_id","=","Румыния"],["country_id","=","Турция"],["country_id","=","Испания"],["country_id","=","Италия"],["country_id","=","Норвегия"],["country_id","=","Сербия"],["country_id","=","Словакия"],["country_id","=","Словения"]]
`
In mass_mailind form and oz it works fine - as example we see "156 partners" . Domain works correct with non-latin characters.
We schedule mailing. 

Current behavior:
If we click "run manually" in cron(and admin has language russian) all works fine - 156/156

If cron is activated in planned time, odoo can't find any records for this domain. Mass mailing shows 0/156 send and status send.

you can avoid this if you modify you cron python code to something like model.with_context(lang=user.lang)._process_mass_mailing_queue()
And if administrator has language russian - cron works

Expected behavior:
Cron(or mass_mailing addon itself) checks language of mass_mailng creator and use it in domain search.

**Comment by Yenthe666** [comment]
@mart-e I'm not sure for who this is. Could you have a look please?

**Comment by mart-e** [comment]
Hi,

It actually makes sense. You are making a search with a translated field. If you evaluate it in a different language, it will not match.
It is globally a bad idea to use strings in your domains, it is not very tolerant to change.
Make your domain using ids instead `[('country_id', 'in', [1, 2, 42, 78,...])]` will work just fine.

**Comment by pedrobaeza** [comment]
This was reported by my team in #15445, and it's supposed to be fixed by the less bad of the options (discussed in #15467 with the famous banned employee thread :laughing: ).

Something has changed?
