### ISSUE TITLE
[BUG] Traceback on website_helpdesk_forum

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#26027]
**Impacted versions:**
4b9d6387b82

**Steps it occurred**:
- Install module manually randomly through the Apps interface.
- Not able to reproduce just by installing `website_helpdesk_forum` manually on https://demo.odoo.com
- Given it produced a trace back on a virgin instance, I consider it valid nonetheless

**Traceback**:
https://gist.github.com/blaggacao/89ae270c835bfdb08de167d399f707b6

**Comment by nhomar** [comment]
**runbot** is green can you share the commit, and installation method please?

**Comment by blaggacao** [comment]
I'll look for the commit shortly and update the report, but is was just manually installing those modules on a clean instance, clean code...

**Comment by Yenthe666** [comment]
@blaggacao please try following the official template too please. I wouldn't know what your problem is or what you want to have solved now 😉

**Comment by blaggacao** [comment]
I've updated the issue, it indeed was at bare at first iteration... Would this relieve the "Need Info" label?

**Comment by blaggacao** [comment]
Given it is not reproducible "just so", maybe a look at the trace back could help tracking this down?

**Comment by Yenthe666** [comment]
Hmm - most of us really like a reproducable way. @Elkasitu do you have an idea?

**Comment by blaggacao** [comment]
@Yenthe666 Me too :-) I was fuzzy testing v11 locally and it just happend. Trace back is my witness.

**Comment by Elkasitu** [comment]
If you installed other apps before the one that crashes you could try reproducing the issue by re-installing the same apps in the same order and seeing if it crashes again on the runbot, if it doesn't crash on the runbot then it's likely that it's something to do with your setup

**Comment by blaggacao** [comment]
I cannot even reproduce locally anymore on the very same instance... It must have been a ghost.
