### ISSUE TITLE
[9.0] JS Error when using advanced filter on float fields in Firefox Quantum

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#26021]
Impacted versions: 9.0

Steps to reproduce: 
- Install firefox quantum
- Go on Odoo
- Go in advanced filter in a list view. 
- Select a Float/integer field
- Try to enter an amount using your keyboard

Current behavior: A JS Error is displayed

Expected behavior: No JS error

Video/Screenshot link (optional): https://youtu.be/c5lm67DN4kc

**Comment by Yenthe666** [comment]
Pretty related to https://github.com/odoo/odoo/issues/26023
@ged-odoo could you look at this one too?

**Comment by jbeficent** [comment]
Also reproduced this issue. Does not happen in v10 onwards. Does not happen when you use Chromium, for instance

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
