### ISSUE TITLE
[9.0] JS Error when refreshing view on a mail.mail record in Firefox Quantum

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#26023]
Impacted versions: 9.0

Steps to reproduce:
- Install firefox quantum
- Go on Odoo
- In setting, go in mail.mail view
- Create a record and after creation simply refresh your page

Current behavior: A JS Error is displayed

Expected behavior: No JS error

Video/Screenshot link (optional): https://youtu.be/uMCp9b6hsrU

**Comment by Yenthe666** [comment]
@ged-odoo could one of the guys from your team look at this? I think we can/should try to avoid this ugly JS traceback in Quantum 😉

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
