### ISSUE TITLE
[11.0] RecursionError: maximum recursion depth exceeded on Pricelist miss-configuration

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#26026]
Impacted versions: 11.0  (Probably all)

Steps to reproduce: Create Pricelist A Depends on B
Edit Pricelist B and make it depends on A
![p2](https://user-images.githubusercontent.com/16624719/43336202-23358738-91ee-11e8-9154-32c44ae465a0.png)

![](https://image.prntscr.com/image/3tM4fnD8Thu_VTF8JIsCKg.png)

Assign it to Customer (or Calculate Price using it)
Current behaviour:
In Quotation
![p3](https://user-images.githubusercontent.com/16624719/43336408-745ad4e2-91ee-11e8-9f9f-a9da5e758616.png)

On `/shop` page
```
RecursionError: maximum recursion depth exceeded
Template: website_sale.products_item
Path: /templates/t/form/div/section/div/b/t
Node: <t t-if="product.website_price_difference and website.get_current_pricelist().discount_policy=='without_discount'">
                                <del class="text-danger mr8" style="white-space: nowrap;" t-esc="compute_currency(product.website_public_price)" t-options="{'widget': 'monetary', 'display_currency': website.get_current_pricelist().currency_id, 'from_currency': website.currency_id}"/>
                            </t>

```                          

Expected behavior:
Miss-configuration should not be allowed. (should be Validation Error in such cases)
Video/Screenshot link (optional):

**Comment by nhomar** [comment]
>>  Miss-configuration should not be allowed. (should be Validation Error in such cases)

The error itself is know, and this has been like this since few years ago. But this seems a little bit tricky to happen, and it is supposed you test your pricelists immediately you create them before make them public (even if you are testing prices, this is the very next step).

I personally would welcome a PR but for my point of view this is not a real issue more than an improvement.

**Comment by Yenthe666** [comment]
Agreed with @nhomar. A PR would be very welcome but it is not a huge priority issue.
@nim-odoo perhaps something for you guys to improve?

**Comment by pedrobaeza** [comment]
Closing this as no answer and very tricky to check circular dependencies in all possible pricelist combinations.
