### ISSUE TITLE
 export translation terms wizard creates lot of noise in .pot files

### ISSUE THREAD

**Issue by Flohack74** [odoo/odoo#26032]
Impacted versions:
11.0

Steps to reproduce:
- Use the export wizard to create translation terms for .pot files and Weblate translation import

Current behavior:
- Pot file contains a lot of non-readable/printable characters:

Expected behavior:
- Export filters out strings which contain only HTML entities. I can understand that the ones where the formatting is mixed in are very hard to cleanup, but the noise is bigger than necessary.

Video/Screenshot link (optional):
![grafik](https://user-images.githubusercontent.com/16186470/43354071-86248298-9245-11e8-9b5c-2d7b47633ce9.png)

![grafik](https://user-images.githubusercontent.com/16186470/43354085-a76cfd90-9245-11e8-9530-f769731a9dd2.png)

**Comment by Yenthe666** [comment]
@mart-e this one is for you 😉

**Comment by mart-e** [comment]
Hi,

Thanks for the report but what are you translating exactly?
We are splitting the text inside meaningful block (e.g. paragraph) to avoid splitting the translations in small chunks that do not make sense (e.g. do not split a sentence in 3 if there is one word in bold in the middle).
So yes, if your text is complex with a lot of HTML markups, the translation will be more difficult to read.
I don't know for Weblate but Transifex handles these quite well and hide it to the users.

**Comment by mart-e** [comment]
I could not find the page `ubuntu-nexus-5-1` on ubports.com but I saw nothing really wrong in the block

https://github.com/ubports/ubports.com-translations/blob/973434ce664fe5668dce84e676546447fb752221/website.pot#L4311-L4322


If your whole text is inside a `<i>` tag, it will be translated inline.

https://github.com/odoo/odoo/blob/9a48f67863db532cd1686eaf1978659591458b5a/odoo/tools/translate.py#L136-L142

The confusion probably comes from the unnecessary `<font>` and non-breaking spaces.
I guess they have been introduced by the WYSIWYG editor. I am afraid this is a drawback of these editors that produce "ugly" HTML content. You can modify directly your HTML with the HTML/CSS editor.

**Comment by Yenthe666** [comment]
Hi,

I'm closing this issue as there has been no feedback and because the answer given by @mart-e most likely solved your issue.

Regards,
Yenthe
