### ISSUE TITLE
id in sale.order

### ISSUE THREAD

**Issue by spectra10008** [odoo/odoo#26035]
im using odoo 10 , i want to change property of id of sale.order module and change Readonly to False , i tried before by inherit before but didn't effect.

**Comment by Yenthe666** [comment]
Hi @spectra10008,

The Github tracker is only for issues/bugs in the official code, it is not the right place to ask questions.
Please ask this on the official help forums at help.odoo.com - plenty of people can help you there (if you provide enough information).

Regards,
Yenthe
