### ISSUE TITLE
[Docker] Distributed caching for a "Horizontally scalable" Odoo

### ISSUE THREAD

**Issue by aelmanaa** [odoo/odoo#26059]
Is there any plan to make Odoo pluggable to a distributed caching system in order to store Odoo data?

Impacted versions:
all
Steps to reproduce:

Current behavior:

Currently odoo data is located in /var/lib/odoo. With Docker, one can mount this folder to a web-data volume as described here https://hub.docker.com/_/odoo/

The problem starts when you want to have a highly available cluster (e.g.: Kubernetes cluster when you can have multiple worker machines). In this configuration, Odoo containers can be located on any machine and thus, if you want to achieve horizontal scalability then "odoo-web-data" must be located on a shared drive (e.g.: NFS drive) . 
This works fine for low volume but as the number of users increase, IO access tend to be slow (in my case, I'm trying AWS EFS as shared drive and it is not very fast). Is it on the roadmap to make Odoo data pluggable to distributed caching system (e.g: Redis).  It would be probably better for performances and will make it easier to have stateless Odoo servers

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@d-fence could you have a look and answer as you manage docker files?

**Comment by Elkasitu** [comment]
I think this is more suitable for @antonylesuisse or @odony

**Comment by odony** [comment]
For scalable deployments we typically use a shared network filesystem with a high IOPS and a very low network latency. If you're using virtual storage, aim for the high IOPS ones, such as Google's SSD persistent disks (15k IOPS), AWS's io1 EBS, or large EFS volumes paired with properly sized EC2 instances (watch your burst credits!). Usually the IOPS and throughput increase when you use larger volumes ([AWS](https://docs.aws.amazon.com/efs/latest/ug/performance.html), [GCP](https://cloud.google.com/compute/docs/disks/performance)). Refer to your service provider for [tips](https://docs.aws.amazon.com/efs/latest/ug/performance-tips.html) to obtain very good IOPS and low latency.

Regarding your distributed cache question: simplicity and correctness beat pure speed in our design goals, so we're unlikely to engineer systems that rely on external caching tools, making code and deployments more complex. However Odoo is very flexible, so you should be able to plug your own system with little trouble. It also relies on a very basic supporting filesystem, so anything that can mimic a filesystem is easy to integrate.
