### ISSUE TITLE
Python 2 compatibility problem

### ISSUE THREAD

**Issue by cantecim** [odoo/odoo#26057]
Hello guys,

Did you stop python 2 backward compatibility support?

If no why these codes merged?
https://github.com/odoo/odoo/blob/44ea58234ec0d902ddf0caf7aefb367acc013627/addons/purchase/models/stock.py#L193

**Comment by pedrobaeza** [comment]
Yes, v11 is not supporting officially anymore Python 2 since the beginning of that version in stable, and thus using this kind of syntactic sugar is allowed.

**Comment by xmo-odoo** [comment]
@pedrobaeza while you're right that it's not officially supported our policy for v11 was still that we'd still like to maintain the Python 2 compatibility unless there are good reasons not to do so as it's convenient for us and partners, providing some buffers for bits and pieces of internal migration & conversion.

A P3-style super call isn't really a good enough reason to completely break compat', so I'll go and merge #26058. Thanks @cantecim.

**Comment by pedrobaeza** [comment]
Ok, thanks for the insights. I can't reopen the PR though, so if you want I can make a new PR, or you can cherry-pick directly the commit. On OCA we are going to Python 3 only directly, and there's already a lot of `super()` calls, but also on library imports and so on.

**Comment by xmo-odoo** [comment]
No worries. I managed to get the branch back from refs/pulls (it's not a big change but that way I could merge it with attribution as bf332e2e08ebe8533c91f39aa5b24e9dc297af67)

**Comment by pedrobaeza** [comment]
OK, thank you very much.
