### ISSUE TITLE
[11.0] TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#26060]
Impacted versions: 11.0

Steps to reproduce: Go to Project's Kanban View --> Group By Manager --> Click on Rating

![](https://image.prntscr.com/image/deikZAf3TnevhNd0ldU0Rg.png)

Current behavior:
`TypeError: Cannot read property 'type' of undefined`
![lo2](https://user-images.githubusercontent.com/16624719/43415489-47a19f0a-9453-11e8-8a95-af65d79e7916.png)

Expected behavior:
Should open related Ratings
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I am able to Reproduce same on v12 as well.
![screenshot](https://user-images.githubusercontent.com/16624719/49660203-09a4b000-fa6c-11e8-99f2-f1598d1de15b.png)
Drag order to another date
![scrsaaseenshot](https://user-images.githubusercontent.com/16624719/49660219-0f9a9100-fa6c-11e8-805c-5c28d47ccce7.png)

**Comment by Yenthe666** [comment]
OPW 1920979

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/04369bab39a217126811c0b8c26bd40b68f547c5
