### ISSUE TITLE
[11.0] Invalid status of Email Schedule in Event when trigger is After each registration

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#26061]
Impacted versions: 11.0

Steps to reproduce: Create new Event --> Schedule Email `After each registration`

Current behavior:  Status is always `Sent` even No mail is sent (Even event is not Created)
![e1](https://user-images.githubusercontent.com/16624719/43416611-68f5b7ec-9456-11e8-9324-d061ade8ce6a.png)

Expected behavior: 
Status should be False on Creation and should be updated according to Email status

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
hi

Imo, it is correct... each subscribed peoples (nobody during creation) got the email, none errors...

"Nice to have" will be to have this input hidden, but if checkbox was always unchecked, I will find it more buggy that always checked.

**Comment by sswapnesh** [comment]
Okay, I will purpose PR against Master for same.

**Comment by sswapnesh** [comment]
> "Nice to have" will be to have this input hidden, 


How can we hide that in List view ?
