### ISSUE TITLE
[9.0] Accounting: Incorrect digits in account code using template

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#26071]
Impacted versions: 9.0 (not test with 10 or above)

Steps to reproduce:

- Install accounting template have `code_digits = 0`, example: **Vietnam - Accounting,** technical name `l10n_vn`
- Active multi company (Admin user setting, check Multi company)
- Create a new company or using available company without seting Chart of account template (in runbot, I using company name _My Company, Chicago_), switch login user to that company.
- In Company settings, tab _Configuration_, set `Number of digits in an account code = 0`
![screenshot from 2018-07-31 14-35-06](https://user-images.githubusercontent.com/5380820/43448033-0d537718-94d7-11e8-8b01-f308f3ea697c.png)
- Go to Accounting >> Settings, in Chart of Accounts sections, select `VN - Accounting` template then click Apply
![screenshot from 2018-07-31 14-34-45](https://user-images.githubusercontent.com/5380820/43447992-f02e179c-94d6-11e8-9beb-fca8356ec96c.png)

Current behavior:
- Go to Accounting >> Adviser >> Chart of Accounts, new record create with 6 digits
![account_code_incorect](https://user-images.githubusercontent.com/5380820/43448096-2e4aa5ea-94d7-11e8-8e47-da53ab1a389a.png)
in Company setting, `Number of digits in an account code` got value = 6

Expected behavior:
- New record create with code value = value in template

Video/Screenshot link (optional):

**Comment by NothingCtrl** [comment]
Note: I can bypass this behavior by set `Number of digits in an account code = 0`

**Comment by Yenthe666** [comment]
Hi @NothingCtrl,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
