### ISSUE TITLE
[11.0] MissingError while debug assets with sass stylesheet in bundle

### ISSUE THREAD

**Issue by ruuter** [odoo/odoo#26076]
Impacted versions: 11.0

Steps to reproduce:
request any URL with ?debug=assets while there is at least one SASS stylesheet in bundle.

Current behavior:
MissingError: Record does not exist or has been deleted.
This happens in assetsbundle [preprocess_css method](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_qweb/assetsbundle.py#L386), which tries to unlink `old_attachments ` twice if both sass and less exist in bundle.

Expected behavior: no error.
Simple fix proposal: set `old_attachments = None` after first unlink:
```
old_attachments.unlink()
old_attachments = None
```
Happy to make a PR if wanted.

**Comment by pedrobaeza** [comment]
Any way to reproduce this on runbot?

**Comment by ruuter** [comment]
@pedrobaeza I don't think so. Runbot server does not seem to have sass installed.
