### ISSUE TITLE
Payslip Bank Account Number is not fetching

### ISSUE THREAD

**Issue by VanithaSankar** [odoo/odoo#26102]
Impacted versions:Odoo 10

Steps to reproduce: In payslip Bank Account Number is not fetching it shows code like res.partner.bank(11,)

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/37325240/43516834-589eeb44-95a4-11e8-850e-3433f357e479.png)

**Comment by pedrobaeza** [comment]
Indeed. It seems an override over method `name_get` or `_rec_name` attribute in `res.partner.bank` object.

Closing as no real issue.
