### ISSUE TITLE
[11.0] Incorrect fiscal position on Quotation / Sale Orders

### ISSUE THREAD

**Issue by AngelCamacho** [odoo/odoo#26100]
Impacted versions: 11.0

Steps to reproduce: Select a diferent partner for Delivery Address than a customer.

Current behavior: Delivery adress change the fiscal position of the quotation. 

![imagen](https://user-images.githubusercontent.com/11173802/43514946-9ebe6140-9581-11e8-847d-160027195365.png)

Expected behavior: The fiscal position only must be modified by the customer or invoice adress. The delivery adress only affects on stock picking and not on taxes.

Video/Screenshot link (optional):

**Comment by wtaferner** [comment]
@AngelCamacho 
Thank you for taking the time to post this screenshot.
The delivery address indeed must affect the Fiscal Position, at least in Europe it is important to whom the goods are delivered and also from where they come (VAT Reverse Charge) to determine the taxes to be applied. So basically it is your task to handle the use case if it is a corner case by doing a workaround or develop some logic to get it work. 

@Yenthe666 
IMHO invalid, but maybe @qdp-odoo should do the final call.

**Comment by Yenthe666** [comment]
Indeed, this is desired & wanted behaviour to my knowledge.
@nim-odoo could you do a quick confirm please?

**Comment by AngelCamacho** [comment]
In Spain the VAT depends on the customer to the invoice is going to. In other words, the TIN that appears on the invoice marks the taxation and who actually buys the goods or services. The delivery  address does not mark who is really sold, only the address where the goods will be delivered.

**Comment by AngelCamacho** [comment]
@wtaferner 

Don't worry, it's not an usual case. For now we make a specific development for the customer. 
If another partners think that the request may be valid, hopefully we can officially implement it in Odoo in the future.

Thanks!

**Comment by qdp-odoo** [comment]
as stated by others: this is the expected behavior. Might not be good in all use cases, but hey.. it's a default value anyway
