### ISSUE TITLE
Multi company : stock valuation bug

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#26112]
**Impacted versions:**
Odoo 10 CE , Odoo 10 EE , Odoo 11 CE , Odoo 11 EE 
**Steps to reproduce:**
Accounting Setting: 
- Use Anglo-Saxon Accounting : true 
- Configure 2 chart of account for 2 company1 and company2 
Inventory Setting : 
- Perpetual inventory valuation (stock move generates accounting entries)
- Costing Method 	Average Price
- Inventory Valuation 	Perpetual (automated)

**Current behavior:**
Calculate the average cost wrong for company2   it is the half of the cost in company1

**Comment by mga-odoo** [comment]
Its not a bug, don't try with Admin user, create a separate users for each company and do the same example, it's working.

**Comment by Yenthe666** [comment]
@Elbagoury can you test & confirm please?

**Comment by Elbagoury** [comment]
@Yenthe666  i tested it with two different users the bug didn't appeared  . 
@mga-odoo it is still a bug because in many business scenario we  need to  access with admin user or a power user has access to many different companies

**Comment by mga-odoo** [comment]
If you ask my opinion, don't allow your customer to work with the admin user as access rights and record rules are by-pass for admin use specially (when user=1 id), you should create a new super user same as admin by giving all the access rights to that user.

still if you consider as a bug, you can keep it open, but doing business operation with admin user (id=1) is not a right approach.

**Comment by mga-odoo** [comment]
I am not consider this as a bug, as goal of the admin user is to give the seamless experience to the user in their first 5 minutes of usage. 

The case we are taking **Inventory Valuation** itself is not so easy, and specially when we do it for the **multi company**, of course this is the case for the expert users and experts never use admin user to test the multi company business operations.

So, even if it seems like a bug, i would think a lot before fixing it, as it may cause the user on boarding experience (you have to test 1000 of standard business cases after this fix which may be affected for the lambda user).
