### ISSUE TITLE
Wrong Translation in language de does cause picking to not get generated for pos orders

### ISSUE THREAD

**Issue by wpichler** [odoo/odoo#26124]
Impacted versions:
10.0 git trunk

Steps to reproduce:
Install DE Language and POS - use DE Language - create a pos order - it will not generate the picking for the pos order - but order will get generated.

Current behavior:
No picking gets generated

Expected behavior:
Picking get generated

Video/Screenshot link (optional):

Solution:
Update de translation - in file: https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/i18n/de.po 

https://github.com/odoo/odoo/blob/88170774a77d64dbb8d990d703e65061bd7d752c/addons/point_of_sale/i18n/de.po#L3438-L3441

**Comment by pedrobaeza** [comment]
Please use Transifex for making the proper translation.

**Comment by wpichler** [comment]
I have entered the translation in transifex now - but i think this is also a general bug - if the next translation in an other language is broken - the same bug will come up again. It would be better to handle the exception - and don't let the user store the order in such case. Because with the current behavious - odoo will create the pos oder - everything does look fine - until the user checks the stock counts. So it would be better to not store the order...

**Comment by pedrobaeza** [comment]
Maybe you can propose a PR with the fix for that thing.

**Comment by mart-e** [comment]
Indeed, the right thing is to fix it in Transifex, thanks for the report and fix !
This is unfortunately a problem we could have with all translations containing a `%s`. If we have bad translations, we need to fix them asap.
We are planning to add a runbot test to detect such bad translations.
