### ISSUE TITLE
[10.0] when importing a module for customization is stored in a route that does not exist and odoo does not recognize the module.

### ISSUE THREAD

**Issue by ychirino** [odoo/odoo#26137]
**Impacted versions:**
10.0

**Steps to reproduce:**
- Apps > import module

**Current behavior:**
when importing a module for customization is stored in a route that does not exist and odoo does not recognize the module.

**Expected behavior:**
Must be created in an existing route so that odoo can read the module

**Video/Screenshot link (optional):**

**##IMPORT MODULO##**
![screenshot-localhost-2018 08 02-16-05-52](https://user-images.githubusercontent.com/37002368/43611413-a70070da-966e-11e8-875e-aab543006f28.png)

<br/>
<br/>
<br/>

**##DEBUG ROUTE DOES NOT EXIST##**
![screenshot-localhost-1984-2018 08 02-16-04-57](https://user-images.githubusercontent.com/37002368/43611415-a7155536-966e-11e8-99c6-ac4035dd7e50.png)

<br/>
<br/>
<br/>

**##ERROR OF THE SYSTEM##**
![menu_002](https://user-images.githubusercontent.com/37002368/43611417-a72c885a-966e-11e8-97e5-41b62e2c75f8.png)

**Comment by Yenthe666** [comment]
Dear @ychirino,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
