### ISSUE TITLE
Create a user,then the partner is show in Customers.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#26135]
**Impacted versions:**
master,11,10

**Steps to reproduce:**
Create a user,then the partner is show in Customers.

**Current behavior:**
most of the time,user is not a customer.

**Expected behavior:**
user do not become to a customer.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you removing the filter 'Customers' before searching for the user?

**Comment by tanghulu0608** [comment]
no,i did not remove the filter 'Customers'. The customer on the new created partner is True
@pedrobaeza

**Comment by pedrobaeza** [comment]
I have just tried and you're right: it appears as default as a customer. I remember this didn't happen before, but I wouldn't consider as a bug. There should be an explanation for this. Maybe @tivisse or @mart-e can tell us.

**Comment by tivisse** [comment]
Hi @tanghulu0608 

This is a known behavior that we do not consider as a bug. By the way I'm gonna change this behavior in master.

Thanks for the feedback and have a nice day,

Yannick.

**Comment by pedrobaeza** [comment]
FYI, the behavior has been changed in 8166eae0bf240fc530952814775d2e0b1039ee53
