### ISSUE TITLE
Cannot close point of sale, database growing, insane amount of time and queries.

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#26139]
Impacted versions:

11 Enterprise.

Steps to reproduce:

Open a point of sale, sell some products. Try to close the point of sale. 
The point of sale does not close. Or if it closes it takes a very long time to close.  I think it has something to do with the mexican accounting modules.  Also  it may be important to mention that we are using lot traceability in most of our products. 

Current behavior:

Here in our production system it takes at least 2 hours for the point of sale sessions that have few sales, and more than 6 hours for the point of sales sessions with more sales.  Also the table account_move_line grows without control, but the number or registers in the table does not grow, just the disk space that the table is using. I think this is because the postgresql temp files. The problem is that if the transactions does not finish, due to odoo closing the process, because of time limits, or any other reason, the temp files remain in the table
This causes a situation where it clogs the database server, and the disk space quickly. The database grows without control.  To control these we are backing up the database, every few days, and then uploading it again. If you do this, the database shrinks to its normal size, for example the .zip file generated by odoo, when backing up the database, is around 20MB.

Currently to workaround the problem we are creating a lot of users to create new point of sales each day, and also trying to close some sessions, leaving the server to work at night. Also it is not possible to close two sessions at the same time as we get a psycopg "error: current transaction is aborted, commands ignored until end of transaction block."

We are running the server with time limits for the  odoo process next to 10 hours, which i personally consider a little bit ridiculous, but we have to do it, since we are trying to close the sessions during the night.

Expected behavior:

Point of sale closes after a few minutes. 

Video/Screenshot link (optional):

First image: Point  of sale still closing after 4 hours of waiting. 

![captura de pantalla -2018-08-03 00-34-58](https://user-images.githubusercontent.com/7807363/43625934-32f5f632-96b5-11e8-8e81-087745c590e1.png)

Second images: An example of the table account_move_line before and after it grows. 
![captura de pantalla -2018-07-17 23-37-47](https://user-images.githubusercontent.com/7807363/43625990-662c1036-96b5-11e8-8124-a4496b5b2d0c.png)

**Comment by pedrobaeza** [comment]
This seems something related to enterprise modules, so please put the corresponding ticket at https://www.odoo.com/help.

**Comment by hydrosIII** [comment]
I already have. Thanks.

**Comment by pedrobaeza** [comment]
Please put here then the OPW number, and this can be closed waiting for the feedback on the other part.

**Comment by hydrosIII** [comment]
I think the issue has been solved. But i do not think it is exclusive to odoo enterprise. Here is the patch provided from odoo developers, Sorry for the question, what is an OPW?. : https://github.com/odoo-dev/odoo/commit/93bbbbae326ec7928b62ed5081e8e7ab836c15c4

**Comment by pedrobaeza** [comment]
OPW is the acronym of "Odoo Publisher Warranty", and it's the former name for the enterprise tickets that it's still used by a lot of people.

**Comment by hydrosIII** [comment]
Hi, has anyone been able to replicate this in odoo community?  because the error is general account_module.

**Comment by hydrosIII** [comment]
Hi, this error seems to replicate in the current versions of odoo enterprise so I cannot update my installation of odoo Enterprise. Also the patch in  https://github.com/odoo-dev/odoo/commit/93bbbbae326ec7928b62ed5081e8e7ab836c15c4 is not merged in the recent version of odoo 11 enterprise. And does not work in versions after the july version.

**Comment by hydrosIII** [comment]
A special module is provided from odoo support for version 11.0 https://github.com/odoo-dev/odoo/commit/ae5906bb5a23e8f8f5777fc4af365724eeb5b3b7. This module implements a patch, but It cannot be merged to mainstream because of the implications. For anyone experiencing the problem, this module is the solution. Also for odoo 11 Community.

**Comment by eabquina** [comment]
will the pos_fast_reconcile module work on Odoo 12 and 13 too? Thanks.

**Comment by hydrosIII** [comment]
Do the bug affects the version 12? In this case maybe We need to reopen the issue. I have not tried.

**Comment by Dimocave** [comment]
yes, this is a problem in version 12 community too, please provide a solution for this huge problem...

Thanks
