### ISSUE TITLE
[11.0] Wrong calculation in def get_work_days_data(self, from_datetime, to_datetime, calendar=None)

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#26141]
### Impacted versions:
11.0

### Steps to reproduce:
1. Create a new resource calendar for 44 hours per week  
![selection_036](https://user-images.githubusercontent.com/7938973/43630764-6a0d96b8-972b-11e8-841e-655c8b77b2eb.png)
2. Create an HR Contract for Roger Scott that refers to the above mentioned calendar and set it to Running
3. Create a payslip for that employee for the period 2018-08-01 ~ 2018-08-31

## Current behavior:
The `Normal Working Days paid at 100%` line on the payslip form shows 27 days due to the calculation of the following code in the `resource.mixin`
```python
    def get_work_days_data(self, from_datetime, to_datetime, calendar=None):
        days_count = 0.0
        total_work_time = timedelta()
        calendar = calendar or self.resource_calendar_id
        for day_intervals in calendar._iter_work_intervals(
                from_datetime, to_datetime, self.resource_id.id,
                compute_leaves=True):
            theoric_hours = self.get_day_work_hours_count(day_intervals[0][0].date(), calendar=calendar)
            work_time = sum((interval[1] - interval[0] for interval in day_intervals), timedelta())
            total_work_time += work_time
            if theoric_hours:
                days_count += float_utils.round((work_time.total_seconds() / 3600 / theoric_hours) * 4) / 4
        return {
            'days': days_count,
            'hours': total_work_time.total_seconds() / 3600,
        }
```
### Expected behavior:
The expected result is 25 days.

For the Saturday line, `work_time=4 hours` and `theoric_hours=4 hours`. And then `days_count = 1` as the result while 0.5 is expected.

**Comment by pedrobaeza** [comment]
Why should you expect 0.5? It should be 0.5 if you define 8 hours and work 4, but defining 4 hours and working 4 results in 100% of the expected work hours, and thus 1.

Change your working calendar to have 8 theoretical hours on Saturday and you will have your expected result.

Closing by the reasons above.

**Comment by davidtranhp** [comment]
@pedrobaeza It seems that closing issues/PR aggressively is what makes you enjoy ^_^

**Comment by intero-chz** [comment]
I think the big issue here is, that "a work day" is never been specified. And if we speak of payslips, "workdays" or "workweeks" or whatever base the calculation is made of, should be specified anywhere.
