### ISSUE TITLE
[11.0] Access right issue on projects when a project user tries to create a task related to a project when module project_pad is installed

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#26156]
Impacted versions: 11.0

Steps to reproduce: On runbot, 
- install pad_project module
- Change access rights on demo user to make him "project user"
- Connect on the same DB with demo user
- Create a task using form view with a project
![image](https://user-images.githubusercontent.com/7678583/43644317-a0bf9208-972e-11e8-9bb1-535c972083c8.png)
- Save

Current behavior:
Access right issue
![image](https://user-images.githubusercontent.com/7678583/43644338-af6fa5d6-972e-11e8-9d98-c24591587bcc.png)

The errors comes from related field use_pads:
![image](https://user-images.githubusercontent.com/7678583/43644403-dc73696e-972e-11e8-8175-75712b763a68.png)
By doing this the project user tries to update the project but the project is only accessible in read access

Expected behavior:
The task should be created

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a side effect of related fields without readonly attribute, that rewrites the field although not changed. I have created #26171 for solving it.

**Comment by jlaloux** [comment]
Thank you Pedro
