### ISSUE TITLE
(Closed for WRONG REASONS ) Delegation Inheritance and Inherited View (Odoo 11)

### ISSUE THREAD

**Issue by master-one** [odoo/odoo#26166]
Inheriting a model by delegation does not link to its associated form view buttons.

Details:
I have created a model that inherits the product.template model by delegation.
For the new model I have its form view inherit the product.template's form view.
Now when I add variants in the variant tab and then click on the Variant Prices button,
I get an empty list of variants.

I am using Odoo 11.

![2018-08-04 14_24_36-aashvi bra - odoo](https://user-images.githubusercontent.com/42087736/43675808-e4a48408-9803-11e8-8df6-5de72e201371.png)

![2018-08-04 14_23_38-variant values - odoo](https://user-images.githubusercontent.com/42087736/43675812-ec954c92-9803-11e8-9d39-6f14d4b18c95.png)
![2018-08-04 14_31_01- models py - official - visual studio code](https://user-images.githubusercontent.com/42087736/43675823-09e0e1d0-9804-11e8-8a40-a20910edb8fb.png)

![2018-08-04 14_41_04- views xml - official - visual studio code](https://user-images.githubusercontent.com/42087736/43675835-2a930f52-9804-11e8-8497-832bd51ceb66.png)
![2018-08-04 16_27_36- views xml - official - visual studio code](https://user-images.githubusercontent.com/42087736/43675836-2f8b8ebc-9804-11e8-85ee-35af8d111562.png)

**Comment by pedrobaeza** [comment]
Opening another issue doens't change the result: you have to check your custom code, not to blame Odoo. Any way, if you don't dig more in the possible underlying problem, and put some more elaborated reasons and possible ways of solving this, you are not going to get anything except an "opened issue".
