### ISSUE TITLE
[stock_account] Product cost (FIFO) is only updated after the product was delivered (not when receiving products)

### ISSUE THREAD

**Issue by novawish** [odoo/odoo#26169]
Impacted versions:
11.0
# Steps to reproduce:
Configure product category like below
![image](https://user-images.githubusercontent.com/31387997/43676549-b9a4c51e-981d-11e8-98a2-e71833041808.png)
And do a purchasing of products belong to that category, the product has been valued in menu `Inventory Valuation`:
![image](https://user-images.githubusercontent.com/31387997/43676606-9937a390-981e-11e8-8d23-860bd201e333.png)
But the Cost on Product's form is not updated to its value:
![image](https://user-images.githubusercontent.com/31387997/43676581-3b96d8f0-981e-11e8-82dd-84cb4c94c0d6.png)
After create a quotation for that product and confirm, its value has been updated:
![image](https://user-images.githubusercontent.com/31387997/43676629-ea6dab88-981e-11e8-8958-59ed61d39b73.png)

# Current behavior:
In manufacturing circumstances, some products are materials and only be used to manufacture, not to sale. Which leads to its value is always equal to 0 when printing BoM Cost, therefore it affects the result (Total Cost of Components) of the Finished Products

# Expected behavior:
Product's cost should be updated whenever the product was received to Stock Locations

# Suggested solution:
I checked the code and it seems that in function `_run_valuation` of stock move only evaluates the value of product when the move  `_is_out` via function `_run_fifo`, should we do something like this (update the product cost when the move `_is_in`)?
![image](https://user-images.githubusercontent.com/31387997/43676687-0e60c81c-9820-11e8-971e-a8488bc9b8cf.png)

**Comment by pedrobaeza** [comment]
I have updated the title to include the FIFO word.

@jco-odoo can you answer the reason for this behavior?

**Comment by jco-odoo** [comment]
Because of returns.  It is not a good measure to value it anyways.  Maybe we need remaining_value / remaining_qty or standard_price in the report.  @lap-odoo

**Comment by gustavovalverde** [comment]
As a heads-up, this same behavior is whats causing clients this unwanted behaviors: 
https://github.com/odoo/odoo/issues/25977
https://github.com/odoo/odoo/issues/25604

@jco-odoo  @lap-odoo I feel there's a general confusion between **Product Cost** (actual) and **COGS** (after sale) which is causing a wrong behavior (mainly with FIFO) in manufacturing, pricelists and margin computations. From my POV this is **critical** as it's causing a bunch of unwanted side-effects.
