### ISSUE TITLE
[FR] Archiving custom model records

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#26162]
**Impacted versions:**
v10  v11 master

**Steps to reproduce:**
- Create a Odoo Studio Model
- Create some records
- Select records that you want to archive (not delete)
- Click on actions

**Current behavior:**
- There is no "Archive" action
- It cannot be created as on the module, only custom fields prefixed with `x_` are allowed
- `x_active` does not seem have any "magic" functionality

**Expected behavior:**
- A canonical way of being able to archive Custom / Odoo Studio records.

**Comment by blaggacao** [comment]
cc @nhomar Might I ask you for your (previous) opinion on this?

**Comment by pedrobaeza** [comment]
Closing as there an associated PR where it's being discussed.
