### ISSUE TITLE
Missing Barcode on HTML and PDF print

### ISSUE THREAD

**Issue by aaronsaquing** [odoo/odoo#26170]
In my Odoo 11, barcode is missing in html as well as in pdf. Please help me out.

Running in Debian 9 stretch
Odoo CE 11

See file example below for Print Badge ID.
![id](https://user-images.githubusercontent.com/42097911/43679165-19eb683a-9853-11e8-85c0-c009c306d769.JPG)
![id2](https://user-images.githubusercontent.com/42097911/43679166-1a27314e-9853-11e8-948c-24eaa7e87cb7.JPG)

**Comment by pedrobaeza** [comment]
Please don't open new issues for questions. I have answered the other one kindly, but the suitable place for questions are the forums (https://www.odoo.com/forum/help-1). If the tip I have given you in the other issue is not enough, please go there for trying to reach more help.

Closing this by the reason above.
