### ISSUE TITLE
[trunk] No show field when enable "Track lots or serial numbers" configuration

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#262]
1) Steps to reproduce the issue you have observed
Entry to master instance from runbot.odoo.com
Set configuration enabling "Track lots or serial numbers" from configuration
![configure warehouse - openerp - habilitando track lot](https://cloud.githubusercontent.com/assets/6644187/3111283/5e0e16d4-e6af-11e3-892f-1c5548e68533.png)
Go to picking menu and open a stock move line in form view.
![ready transfers - openerp - number lot](https://cloud.githubusercontent.com/assets/6644187/3111299/7fdef742-e6af-11e3-83b3-514f0d51575e.png)

2) The result you observed
No show field to set a "Tracking lot"

3) The result you expected
Show field for set a "Tracking lot"

4) 4) The platform you are using (and browser version, if relevant)
trunk
commit a91a12e
Merge: 1779495 fc9d0d9

**Comment by lbaldi** [comment]
In the bardcode interface I can only select one lot for one product but I would like to select several lots for a product. Its that posible?

**Comment by LancashireDave** [comment]
Hi,
Not sure if I should start a new thread but my problem is similar to this.....
I want to make sure I only sale lots that are in stock. It seems standard Odoo allows you to create a new lot when you sell which is a little odd if you are trying to have stock traceability.
Or have I simply missed a setting or way of using Odoo?
Thanks for any help.
Dave

**Comment by NanoInformatics** [comment]
Hi, 
I also need to figure out this. I don't see the point, why Odoo not giving the option to select existing lot

**Comment by Yenthe666** [comment]
Dear @moylop260,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
