### ISSUE TITLE
[All] stock_account: Valuation accounts must be property fields (multicompany)

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#26215]
Impacted versions:
All

Steps to reproduce:
1. Create **Company A** & **Company B**
2. Go to **Company A**
3. Assign a Valuation account to the default stock adjustment location (ref: `stock.location_inventory`)
4.  Do an Inventory Adjustment of a product with a surplus (more than what you have on hand)
5. The valuation account of **Company A** is used

6. Go to **Company B** and repeat **step 4**.

Current behavior:
- Depending on the permission 2 things can happen (a) Permission error, (b) The surplus **valuation of Company B** is recorded in **Company's A accounting**

Expected behavior:
- If there's no account set on Company B, use Company B default valuation accounts.

**Note:** It's really hard to have a _workaround_ on this one because I have to create an action to change the _default stock location_ on all **Company B** products, then create an Automated action so each time a product is created it uses the new stock valuation location.

**Comment by lem8r** [comment]
+1
 #24862

**Comment by nhomar** [comment]
at least into stable versions change the type of fields brake 100% the status quo and the stable policies, I will close this issue as a wishlist.

The workaround from who come here in the future is create a virtual location for inventory per company, set the company field properly and set the proper account per location.

**Comment by gustavovalverde** [comment]
I'll say to keep it open for **master**. It's a huge pain to apply the workaround (as it depends on server and automated actions per company)

Even on master a default **per company** would be great, so each company can have it's own `property_stock_inventory` for products.

**Comment by gdgellatly** [comment]
@gustavovalverde This is a bit of a non issue tbh,  All you do for virtual locations with locations with accounts is have one for each company and set the default location properties as company specific in settings.

So company A has Inventory Loss - Company A etc etc and then you just set the properties.

**Comment by gustavovalverde** [comment]
I might be overthinking, but I'd say it's preferable to just have **1** virtual location to handle that logic. Just as it happens with the accounting on product categories.

**Comment by gdgellatly** [comment]
You are definitely overthinking.  It has been this way since v5, I know because I raised this exact bug report then when I was new. 

You would never have a regular stock location multicompany, so why is a virtual one so special that it can't be assigned to a company?  I actually use one inventory loss location per warehouse.  

In any case, your complaint was the workaround was too hard, it really isn't.
