### ISSUE TITLE
EE 11 - web_gantt not showing colours in bars (for tasks)

### ISSUE THREAD

**Issue by ruifranco** [odoo/odoo#26225]
Impacted versions: EE 11

Steps to reproduce:

Create a Gantt to be applied on tasks

Current behavior:

The colour of the tasks is not taken into consideration

Expected behavior:

The bars should show a colour aproximate to the one set for each task

This can be fixed by editing the web_gantt/static/src/js/gantt_model.js file and add "fields.push('color');" after "fields.push('display_name');"

**Comment by Yenthe666** [comment]
@ruifranco why don't you make a PR since you know the exact problem and you're proposing a fix? 😄 we'd love to see one!

**Comment by ruifranco** [comment]
Well @Yenthe666, because it would be much faster for Odoo guys to do it and publish the fix. But I'll do it, anyway (and let's see how long it will take to be accepted).

;)

**Comment by mart-e** [comment]
Hi,

A bit old issue but the 11.0 is no longer supported. Reading the code, it looks like this was fixed during odoo/enterprise@b81800881f330c7972c59f7679b8923fe612e1ab anyway :+1:
