### ISSUE TITLE
[10, 11] Can change entry date prior to account lock date

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#26240]
Impacted versions:
10, 11, master maybe

Steps to reproduce:
1. Create a journal entry dated 2018-01-01
2. Post the entry
3. Set both account lock date to 2017-12-31
4. User odoo api to change the entry date to 2017-12-31.
`account_move.date='2017-12-31'`

Current behavior:
Will Change the entry date

Expected behavior:
Will pop up error and fail to chnage the entry date

**Comment by pedrobaeza** [comment]
You are abusing the system changing a field manually through code, and this kind of side effects can happen. It's the same about changing for example the state of an order that has been confirmed via code. Checking all these possible changes will make the code more complex, slow and with possible side effects.

I have tried on runbot to force the same on the UI, and it's not possible, so it can't consider this as a real issue IMO. There's some hard checks that are already in the system for avoiding certain inconsistent data. @qdp-odoo can you decide if this one should be one of them as an improvement?

**Comment by auyeung112002** [comment]
Partly agree. But in the sense of account lock date, date of posted entry prior to lock date should not be changed in all way. It will help preventing developer to change the date unintentionally.

**Comment by Yenthe666** [comment]
@auyeung112002 what would you expect? That Odoo fully 'locks' the abilities you have on that field? The power of Odoo is its fleixbility. With flexibility comes responsability, this is one of those things that a developer (or the functional guy) should know. I can think of a few ways to override these behaviours through code so I wouldn't call this a bug.

**Comment by auyeung112002** [comment]
@Yenthe666 Yes, With flexibility comes responsability. When odoo provides flexibility to developers, odoo also need to make sure developers respect the lock date and produce correct result.

For odoo to be a serious business ERP, accounting module needs to be accurate. Without this kind of check, lock date is partially compromised since accountant can't rest assure that figure before lock date will not change!

**Comment by Yenthe666** [comment]
Well this is how Odoo works basically. It would require a logical change and technical change for these kind of features which I can guarantee won't happen. If you wan't more strict settings or options you'll need to code them, just like you do when you want to making things easier or add features.

**Comment by auyeung112002** [comment]
Yes, understand that odoo will not code for this issue. What I mean is to invite them to review this pull request https://github.com/odoo/odoo/pull/26954

**Comment by Yenthe666** [comment]
Sure, asked somebody to review.

**Comment by auyeung112002** [comment]
Thanks very much!
