### ISSUE TITLE
[11.0] Payroll Workdays wrong if User Time Zone is not UTC

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#26256]
**Impacted versions:**
11, tested on runbot
**Steps to reproduce:**
**With User's time zone NOT CONFIGURED(UTC)**
- Create a Payslip for a employee with contract active. Calendar is Standard 40 Hours/Week
-Set Date from 01/08/2018
-Set Date to 31/08/2018
-Number of day is 23 and Number of hours is 184
 IT IS OK, Between 01 to 31 August work 8 hours daily from Monday to Friday

![image](https://user-images.githubusercontent.com/7775116/43871575-e7b40210-9b6c-11e8-88de-5d730385e53b.png)

![image](https://user-images.githubusercontent.com/7775116/43871579-eb92df96-9b6c-11e8-812c-e3e1f94602cf.png)

**Change Time zone to User(America/Guayaquil) UTC-5. Repeat same steps:**
- Create a Payslip for a employee with contract active. Calendar is Standard 40 Hours/Week
-Set Date from 01/08/2018
-Set Date to 31/08/2018
-Number of day is 22 and Number of hours is 176

![image](https://user-images.githubusercontent.com/7775116/43871598-01196c54-9b6d-11e8-9903-cdd215414916.png)

![image](https://user-images.githubusercontent.com/7775116/43871607-0501d09a-9b6d-11e8-96b7-d27e744ad859.png)

**Current behavior:**
worked days is wrong compute with User's Time zone.
**Expected behavior:**
Number of day must be 23, not 22. Number of Hours must be 184 not 176

**Note:** 
Fields on payslip are type Date, but [here](https://github.com/odoo/odoo/blob/11.0/addons/hr_payroll/models/hr_payslip.py#L173-L174) change at datetime.  
Call to function [get_work_days_data](https://github.com/odoo/odoo/blob/11.0/addons/hr_payroll/models/hr_payslip.py#L197) and [this functions](https://github.com/odoo/odoo/blob/11.0/addons/resource/models/resource.py#L414-L470) are change to user time zone.

**Video/Screenshot link (optional):**

**Comment by pedrobaeza** [comment]
@tde-banana-odoo it seems you were the one who work on this. Can you check this issue report as it seems legit?

**Comment by RomainLibert** [comment]
Fixed here : https://github.com/odoo/odoo/commit/06373dde4eb46b4d392ec33cb070d53a94d4dbcd
