### ISSUE TITLE
[WISHLIST] Add Support of nulls first | last in order by clause

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#26257]
Impacted versions:
10, 11, master
Steps to reproduce:
`_order = 'name desc nulls last'`

Current behavior:
Fail to use this because this regex does not consider nulls first | last
https://github.com/odoo/odoo/blob/d92f17cebe048190679f7f86456d93aa98c0cb2a/odoo/models.py#L65

Expected behavior:
Able to use nulls first | last

**Comment by pedrobaeza** [comment]
@rco-odoo this can be good to have it if there's no other side effect. Can you evaluate the convenience of this?

**Comment by nhomar** [comment]
can you enligth us why do you need such word there? the convenience and the usage, I am sorry but I do not get the point of allow a partial reserved word there.

Regards.

**Comment by auyeung112002** [comment]
Not about convenience and usage. Currently no way to control this behavior. 

When you want to order in descending order, null always come first. If you dont want null value come first, other way is to order in ascending order which contradict with requirement. Simple as that

**Comment by sle-odoo** [comment]
note that while it is inconvenient it is possible to handle these usecases, it is done on the [quants](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_quant.py#L131)

**Comment by sdegueldre** [comment]
@rco-odoo Any chance you could take a look at this? At the moment nulls are always first whenever you have an `ORDER BY` clause.
