### ISSUE TITLE
Odoo Server Error:  You should provide a lot/serial number for a component

### ISSUE THREAD

**Issue by thienlam129** [odoo/odoo#26265]
Hello!
I'm using odoo v11. I have a problem when i try to 'done' a work order of MO/00003. It's denied. Pleases, tell me how to fix.
![screen shot 2018-08-09 at 3 43 13 pm](https://user-images.githubusercontent.com/41277661/43888175-1bc6e616-9beb-11e8-8523-a8d9e8be7b5f.png)
![screen shot 2018-08-09 at 3 43 16 pm](https://user-images.githubusercontent.com/41277661/43888187-2766650a-9beb-11e8-958f-8c939cbbbef6.png)

**Comment by pedrobaeza** [comment]
One of the components of the manufacturing order (the finished product or one of the raw materials) has the tracking by lot or by serial number, activated, and thus you should provide it.

Any way, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
