### ISSUE TITLE
[All] note: installing note_pad renders the note app useless

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#26277]
#### Impacted versions:
All

#### Steps to reproduce:
1. Install Note
2. Create a Bunch of Notes (first line is always shown in the kanban as the note **summary**)
3. Install **note_pad**

#### Current behavior:
All notes created with the pad have no way to show the **summary**, rendering notes useless as there's no way to see a summary to know which note is which:
![image](https://user-images.githubusercontent.com/16890942/43896766-ee563436-9ba7-11e8-9e10-fbaf7112caa4.png)

####Expected behavior:
All notes should have a summary even if the pad is installed, so we can navigate on the kanban or tree view and identify which note to open.

**Comment by nhomar** [comment]
I agree this is anoying but I think there is no intention to fix this. Didi you put this as part of your enterprise licence? some feedback?

**Comment by gustavovalverde** [comment]
Yeah, OPW 1873625. It has a week, but no answers yet.
