### ISSUE TITLE
Unable to print invoice from portal

### ISSUE THREAD

**Issue by nja-odoo** [odoo/odoo#2627]
In portal, admin can print an invoice but portal user can not print an invoice and getting error, reproduced in master and 8.0

![invoices odoo](https://cloud.githubusercontent.com/assets/7599705/4368717/e2fb697a-42f1-11e4-88b0-dd00e7fcaf7b.png)

**Comment by Yenthe666** [comment]
@mart-e this one is no longer present either, can be closed.
