### ISSUE TITLE
Delivery method is not translated in customer's language

### ISSUE THREAD

**Issue by olivierb2** [odoo/odoo#26289]
Impacted versions: 10

Steps to reproduce:
- Create new Order/Quote.
- Select a customer
- Add items to the Order/Quote
- Beside **Delivery method** choose the wanted delivery method.
- Click on **Set price**

Current behavior:
- The added item description is never translated to the customer language while traduction has been set from **delivery methods** under **Configuration**.
- Any other manually added products from **Add an item** is properly translated.

Expected behavior:
- Having the shipping item translated into the customer language.

Video/Screenshot link (optional):

![screenshot](https://user-images.githubusercontent.com/2324018/43903649-334eb5aa-9bed-11e8-8f05-40b72657a4d5.png)

**Comment by Yenthe666** [comment]
@mart-e can you check?

**Comment by mart-e** [comment]
Fixed at cd3230c1d35dde0cd02cfa49a7987f7a91775e35, thanks

**Comment by olivierb2** [comment]
Just a small comment, I confirm this fixed my issue, thanks !!
