### ISSUE TITLE
[11.0] Translation doesn't work for read_more / read_less (data-o-mail-quote) in thread.js (mail)

### ISSUE THREAD

**Issue by MickaelAdhoc** [odoo/odoo#26288]
**Impacted versions:**
11.0 (but previous too i think)
**Steps to reproduce:**
Try to use read more / read less in mail message, no translation on toggle button
**Current behavior:**
No translation when we change langage
**Expected behavior:**
Translation works
**Video/Screenshot link (optional):**
None
**References:**
https://github.com/odoo/odoo/blob/a10ea93dbe5bbfcdc53f7ba46fd2b52ef6862a8f/addons/mail/static/src/js/thread.js#L10
https://github.com/odoo/odoo/blob/a10ea93dbe5bbfcdc53f7ba46fd2b52ef6862a8f/addons/mail/static/src/js/thread.js#L17
https://github.com/odoo/odoo/blob/a10ea93dbe5bbfcdc53f7ba46fd2b52ef6862a8f/addons/mail/static/src/js/thread.js#L18
**Solution:**
Need to use core._lt instead of core._t for read_more and read_less variables

**Comment by pedrobaeza** [comment]
Can you make the pull request with the change as it seems you are sure about the solution?

**Comment by Yenthe666** [comment]
for your interest @mart-e
