### ISSUE TITLE
[8.0] 	Enqueue Jobs | No worker started for process Problem

### ISSUE THREAD

**Issue by bumblebeey** [odoo/odoo#26290]
Impacted versions: 8.0

Steps to reproduce:

i am using with virtualenv and start line here

/home/virtualenv/bin/python /home/odoo/server/odoo.py --config=/etc/openerp.conf --load=web,web_kanban,connector --logfile=/var/log/odoo/openerp.log

Current behavior:

Jobs stuck pending DEBUG log give me that error
DEBUG openerp openerp.addons.connector.queue.model: No worker started for process 

Expected behavior:

tested with --database --and --workers doesnt help me.

when try run Enqueue Jobs says No worker started for process Problem
but another Scheduled tasks run well.

Video/Screenshot link (optional):

**Comment by bumblebeey** [comment]
Also system time zone is checked, and Enqueue Jobs are dublicated.

**Comment by bumblebeey** [comment]
Thank you for your answer i have 4 worker for openerp and 2 worker for crons, also my dbfilter is .* 
I will try again tomorrow

**Comment by Yenthe666** [comment]
Hi guys,

I'm sorry but Odoo 8 is no longer an officially supported version. There is only official support for the last three versions.
Please ask this issue on the official help forums (help.odoo.com) or on the mailing lists.

Regards,
Yenthe

**Comment by bumblebeey** [comment]
i am getting following error any one help ?

`ERROR odoo openerp.service.server: Worker (23100) Exception occured, exiting...
Traceback (most recent call last):
  File "/home/odoo/server/openerp/service/server.py", line 759, in run
    self.process_work()
  File "/home/odoo/server/openerp/service/server.py", line 834, in process_work
    start_rss, start_vms = memory_info(psutil.Process(os.getpid()))
ValueError: too many values to unpack`
