### ISSUE TITLE
[10.0, 11.0] Odoo studio: impossible to remove home background and set back to default

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#26295]
Impacted versions: 10.0, 11.0

Steps to reproduce:
1. Open a runbot, go to the homescreen and open Odoo studio
2. Set a background image through the left top menu:
![image](https://user-images.githubusercontent.com/6352350/43941325-f6c8ff5a-9c73-11e8-89a6-268a456807cf.png)
3. Try to remove that image

Current behavior:
There is no option to remove a background image and to set the Odoo homescreen back to the default Odoo background.

Expected behavior:
Ability to delete the image on the home screen of Odoo and set it back to the default Odoo background.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this more a wishlist?

**Comment by Yenthe666** [comment]
@pedrobaeza not really. We've had two customers now that set a background and they want back the default theme background but there is no way to do so (functionally).
You really can't sell a customer that it is impossible to do for the customer himself & that you have to charge money 😕

**Comment by pedrobaeza** [comment]
OK, as it's in the edge, I remove the label. But remember that this being an enterprise option, it should be reported by OPW ticket, not here.

**Comment by Yenthe666** [comment]
@pedrobaeza I also have an OPW open right now. Very bad feedback/communication about this so that is why I keep it open.
When there is a final decision/call I close/update this one 👍

**Comment by gustavovalverde** [comment]
I actually liked the idea of having enterprise issues with a Github counterpart (not just the OPW), as this is a great tool for others to be aware of some issues and know how to tackle then before making the mistake.

For example, now I know i should be careful with this until fixed.

**Comment by pedrobaeza** [comment]
Then issue tracker should be activated on odoo/enterprise repo, not here. As you know, I'm helping community part of Odoo, not enterprise one, and so, I don't want to manage enterprise things, and also I don't want to raise the number of issues here (for those that uses this metric :wink: ), being about code not belonging to it.

**Comment by pedrobaeza** [comment]
It's not one ERP system. There's the community part, where I'm willing to lend my time helping there, as they offer a wonderful open source system and this is my way of getting back their gift, and the enterprise part, where they receive money for doing that task and they don't even consider any of these things in their partner grade policy (as stated directly to us by Fabien), so I won't be participating there for that reason.

**Comment by Yenthe666** [comment]
Okay - thanks for the feedback I was curious. I guess I like to improve both sides as in the end we all benefit from it. One more than another but ok 😉

**Comment by fpodoo** [comment]
@Yenthe666 it has been done in master some time ago: https://www.awesomescreenshot.com/image/3547972/8eee5dfe14d8ad672e0ea1699bfb90b5

Even if people would really like to have it, it's still a new feature, and not a bugfix. So, I don't think we should do that on a stable version.

**Comment by Yenthe666** [comment]
@fpodoo okay I'm more than happy enough it'll be in V12 then. Thanks for the clarification, that means we can close this off.
For now we'll have to manage without the option (because of new feature).
