### ISSUE TITLE
changes to web.base.url do not work

### ISSUE THREAD

**Issue by skyzluo** [odoo/odoo#26293]
Impacted versions: CE 11

Steps to reproduce: I want to server odoo CE 11 from mydomain.com/crm. So I changed web.base.url to www.mydomain.com/crm and added web.base.url.freeze to True. However, the settings do not work. My odoo still serves from www.mydomain.com. Is this a bug? How do I solve this issue? Thanks

I am using apache2 and odoo-wsgi.py. 

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here, as you have already done.

Closing this by the reason above.
