### ISSUE TITLE
app or python api upload files fail

### ISSUE THREAD

**Issue by CrazyGuo** [odoo/odoo#26300]
Impacted versions:   11.0

Steps to reproduce:   use python api to upload files

Current behavior:
![odoo_upload_error](https://user-images.githubusercontent.com/10334878/43948110-7a916ab4-9cbc-11e8-900f-84f6a1ba1f14.jpg)

TypeError: write() argument must be str, not bytes.

I checked the source code in odoo/http.py, line 1161 is  **with open(path, 'w') as fp:**
And I changed the parameter 'w' to 'wb+'  and I can upload the files successfully.
Maybe the reason just like [the issue](https://github.com/odoo/odoo/commit/43617bbcb65fc4048ad97567067cb2f3138873a3) happened before.

Expected behavior:
Succesful upload files.
Need to modify the source code to **with open(path, 'wb+') as fp:**  in odoo/http.py,  line 1161

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Use Python API? Can you be more precise and put the code that provokes this problem. I guess the fault is in your code, but without it, we can't figure out.

**Comment by CrazyGuo** [comment]
@pedrobaeza My source code in odoo server as follows:
**import json
from odoo import http
from odoo.http import request
import base64
import logging
_logger = logging.getLogger(__name__)


class AppUploadController(http.Controller):

    @http.route('/api/binary/upload_attachment', type='http', auth="user", csrf=False)
    def wechat_upload_attachement(self, model, id, **kw):
        files  = request.httprequest.files.getlist('ufile')
        attachement_model = request.env['ir.attachment']
        result = []
        for f in files:
            file_name = f.filename
            _logger.info("file ia %s", file_name)
            try:
                attachement_model.sudo().create({
                    'name': file_name,
                    'datas': base64.encodestring(f.read()),
                    'datas_fname': file_name,
                    'res_model': model,
                    'res_id': int(id)
                })
                result.append({'file_name': file_name, 'is_success': True})
            except Exception:
                result.append({'file_name': file_name, 'is_success': False})
        return json.dumps(result)**

my client source code as follows:
**wx.uploadFile
({
                url: "my real domian" + "/api/binary/upload_attachment",
                filePath: tempFilePaths[i],
                name: 'ufile',
                formData:
                {
                    'model': 'wechat.app',
                    'id': 1
                },
                header:
                {
                    "Content-Type": "multipart/form-data",
                     'Cookie': 'session_id = ' + wx.getStorageSync('token') 
                },
                success: function (res) 
                {
                      uploadImgCount++;
                      if (uploadImgCount == tempFilePaths.length) 
                      {
                          wx.hideToast();
                      }
                },
                fail: function (res) 
                {
                    wx.hideToast();
                }
 });**

**Comment by pedrobaeza** [comment]
The problem is in your code, that give to ORM the file in `bytes` encoding instead of `str`. Change it before calling to create.

**Comment by CrazyGuo** [comment]
@pedrobaeza   Actually, In my client source code, I transfer the files **by bytes** to odoo server, but it reports TypeError: write() argument must be str, not bytes. And I also tested the same code to asp.net mvc server, it  can receive the bytes files.  You mean I need to change the files into str in the client?

**Comment by pedrobaeza** [comment]
Yeah, that's it.

**Comment by jlzhou** [comment]
@pedrobaeza Maybe you didn't understand what CrazyGuo means.
He said this issue is caused by python upgrading from 2.x to 3.x.
In python 2, even we write open(path, 'w'), we still can upload both binary and text file, but in python 3, we must write open(path, 'wb+') for binary file operation.

**Comment by jlzhou** [comment]
@pedrobaeza what CrazyGuo mean is if we change code as open(path, 'wb') instead of open(path, 'w'), we can upload binary file from client directly without converting them in base64 format first.

**Comment by pedrobaeza** [comment]
Well, I'm not understanding then the problem. If you think you have the solution, you can try to propose a PR and I'l be glad to review it.
