### ISSUE TITLE
[WISHLIST] web_studio: Ability to set options: no_create_edit, no_create, no_open...

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#26309]
Just as we can modify the **domain** and the **context** with Odoo Studio, it would be nice to have the **options** too

Having the ability to easily set `no_create_edit` on a field, reduces users mistake a **bunch**.

**Comment by pedrobaeza** [comment]
The same answer that in #26307. Just report here Odoo community things, as this issue tracker is for this (as it's located in odoo/odoo, not in odoo/enterprise).
