### ISSUE TITLE
sales order edit expiration date not working

### ISSUE THREAD

**Issue by Perino01** [odoo/odoo#26329]
Impacted versions: 11

Steps to reproduce: Create New Quotation without Expiration Date. 

Current behavior: If you want to edit the Expiration Date later, it is not possible, because there is not input field available. You can only see the label 'Expiration Date'.

Expected behavior: Possible editing of the Expiration Date of an existing Quotation, which has no Expiration Date while creating.

Video/Screenshot link (optional):

![grafik](https://user-images.githubusercontent.com/29162103/44000508-310a7c8a-9e21-11e8-80b4-03ebcf9dda97.png)

**Comment by pedrobaeza** [comment]
I have tried on runbot and I'm able to change it without problems. See the GIF about it:

![peek 12-08-2018 16-33](https://user-images.githubusercontent.com/7165771/44003107-bbf55122-9e4d-11e8-8358-f124488b96c4.gif)

Closing as no real issue.
