### ISSUE TITLE
odoo product margin report, not showing purchase cost of manufacturing products in order to calculate correct expected margin.

### ISSUE THREAD

**Issue by muapk1** [odoo/odoo#26340]
Impacted versions:
v11 enterprise
Steps to reproduce:
accounting > reporting > product margin             (require settings configuration of product margin)
Current behavior:
not showing total cost value
![margin1](https://user-images.githubusercontent.com/31097388/44023843-432cf446-9ef4-11e8-91e1-0d97acb8bf7e.GIF)

![margin2](https://user-images.githubusercontent.com/31097388/44023865-56d187dc-9ef4-11e8-9d85-d9a463a04cf3.GIF)

Expected behavior:
correct purchase cost
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think you have to add the proper measure. Have you tried?

**Comment by muapk1** [comment]
proper measures?
