### ISSUE TITLE
Official Odoo forum error when posting

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#26373]
I tried to post on the https://www.odoo.com/forum/help-1 
Steps to reproduce:
Post any question on Odoo
Current behavior:
500: Internal Server Error, popup with "share" after returning to previous page.

**Comment by cierek** [comment]
reopened as it happens also for my office mates and for couple guys from the business next door

**Comment by Yenthe666** [comment]
Hi @cierek,

Thanks a lot for the bug report.
There is indeed an issue in the official forum right now, it is because of the upgrade they did.
@JKE-be should fix this soon.

**Comment by JKE-be** [comment]
Thank you, it has been fixed.

Local diff from previous traceback that was not migrated to the new code version.
