### ISSUE TITLE
Internal Server Error Odoo 10 for Ubuntu 16

### ISSUE THREAD

**Issue by cyberpollutionbd** [odoo/odoo#26383]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I am using ubuntu 16 and trying to setup odoo 10 into Ubuntu but fails after try. please check attached
![screenshot from 2018-08-14 21-04-17](https://user-images.githubusercontent.com/37775397/44099988-bfa784b6-a005-11e8-92ee-170f3dfa6de3.png)
![screenshot from 2018-08-14 21-04-22](https://user-images.githubusercontent.com/37775397/44099999-c40995bc-a005-11e8-9b01-4bf5760ebcef.png)

**Comment by pedrobaeza** [comment]
The port is in use by other Odoo instance or other service in your computer.

Closing as this is not a real Odoo bug.

**Comment by OGGonzalezM** [comment]
It looks that you must stop the odoo service, sometimes the service get stuck and is necesary to restart or even change port with the --xmlrpcport=your_port

sample:  ./odoo-bin --xmlrpc-port=8070

and like that shows Odoo will run in 8070 port
