### ISSUE TITLE
POSbox Error with Raspberry Pi b+

### ISSUE THREAD

**Issue by bishamontn** [odoo/odoo#2638]
There is a problem with the POSbox image and the new raspberry pi b+. The latest version of POSbox image is working on raspberry pi b without problem but if I change the sd card to a b+ I am getting this error. 

error opening /dev/input/event*

And the raspberry doesn't initialize.

I have tried to install last raspbian image and there is no problem so I guess the problem is the raspbian version used in your POSbox image. Hope you could update it.

**Comment by Yenthe666** [comment]
Hi @bishamontn,

Do you still face this issue? A newer version of the PosBox image should have fixed this.
Please let me know if it is fixed and if I can close this issue.

Regards,
Yenthe

**Comment by bishamontn** [comment]
Yes, working now @Yenthe666. Close the thread without problem. Thank you.

**Comment by nagahxp** [comment]
hi @bishamontn , have your resolved this issue
can you help?
I'm trying to use the latest posbox image for raspberry pi 3 B+, but unfortunately it is not booting
the posbox is giving a rainbow colored screen on the connected display

**Comment by Pyc0kw4k** [comment]
Hi, I've the same error with pi3 B+
