### ISSUE TITLE
the fields 'type' used in the attributes must be in the view but missing, El campo 'type' utilizado en los atributos debe estar presente en la vista pero falta

### ISSUE THREAD

**Issue by OGGonzalezM** [odoo/odoo#26388]
Impacted versions:
11.0 enterprise

Steps to reproduce:
* I've pulled  the updated modules from open and enterprise repositories.
1. I've just update the modules MRP and account_invoicing and this is show

Current behavior:
The modules can't be updated

Expected behavior:
all the modules must be updated correctly

Video/Screenshot link (optional):

This is not the first time that this error is reached, the last time i updated all the accounting modules and the mrp, and this was solved
![error in partner views](https://user-images.githubusercontent.com/28605714/44123534-699e002a-9fee-11e8-9043-ff9cd74055bd.png)

**Comment by nhomar** [comment]
Which is the method you used to install?
Which are the **sha** fo both of your repositories?.
Do you have any customization that touch such fields?.

In our side we compile and make a -u all to almost 20 instances and this is not happening to us, but may be I am missing something.

**Comment by OGGonzalezM** [comment]
I installed Odoo with a script from yenthevg, the sha are:

from Odoo: commit 51225c9b9f20c59eac1cd2ac117f9899ee76e391 
                   Merge: 388bc54 52e8803
from enterprise: 
                        commit d532798e841279a5112b17c46e5523caaf9c35d1
                        Merge: dab8a6d d8392b8
I don't have modules that modifies something of MX location, also i tried a "-u all" and this is not solved, 
I'm not doing extras, i was just trying a new custom module and this happened.

**Comment by sswapnesh** [comment]
@nhomar  It should be because of field `"type"` which is used in attrs in view `mx_partner_address_form` but it is not present in view.

**Comment by OGGonzalezM** [comment]
Then, if it is set as noupdate, how could i update this in an instance that is actually running??

**Comment by Yenthe666** [comment]
Manual update in that case.

**Comment by sswapnesh** [comment]
Hello @Yenthe666 ,
Manual update wont work for @OGGonzalezM  because view is not loaded into Database.
That comment was for @nhomar because in his case upgrading was working fine as view was set to not-update.
Someone has to check the Inherited view if `type` field is there or not.

**Comment by OGGonzalezM** [comment]
Exactly, this doesn't work, like i said i've tried update all the module in the terminal and in the Odoo apps and the issue/error is showed.

**Comment by celm1990** [comment]
@sswapnesh @nhomar FYI this [commit](7b3796d77c198553b1f9fe422a46eb477df3e3f3) introduce validation on views. Fields used on attrs, domain and context must be appears on view definition.

**Comment by sswapnesh** [comment]
Link of the commit is dead.

**Comment by celm1990** [comment]
Sorry [commit here](https://github.com/odoo/odoo/commit/7b3796d77c198553b1f9fe422a46eb477df3e3f3)

**Comment by sswapnesh** [comment]
The commit you have added is the Global one which adds of the validation of fields/view, but in this case it is working for other users well.

**Comment by sswapnesh** [comment]
Hello @OGGonzalezM 
Please upgrade your Odoo enterprise source code and try again as those fields are present on view in latest enterprise Build on [runbot](http://364708-11-0-65ef27.runbot11.odoo.com/web?debug#id=3485&view_type=form&model=ir.ui.view&action=25&menu_id=4)
![](https://image.prntscr.com/image/uNMb-qd1RAuxSvFaYiJekA.png)

@Yenthe666  Will be great If you can Point that commit here.

**Comment by Yenthe666** [comment]
Should be https://github.com/odoo/enterprise/commit/02e84c23c99f5e2e9a4291e053ba6438773ad795

**Comment by OGGonzalezM** [comment]
The issue is still there, i've just pulled the enterprise repository, tried to update the module, and i got the same.

![edi para mexico - odoo](https://user-images.githubusercontent.com/28605714/44546814-bb4aeb80-a6de-11e8-9de3-712025f4dbb6.jpg)
.

**Comment by OGGonzalezM** [comment]
Of course, i've done it, i'll try updating other database and reinstalling the Odoo server.

**Comment by mart-e** [comment]
Hello,

As you stated above, the view is in noupdate, so updating the module will not fix the issue.
You can
- manually make the change Swapnesh mentioned about
- delete the view record and update the module

By the way, I have changed that in enterprise at odoo/enterprise@028e22aef1 as there was no reason to set it in no update (but that won't affect existing db)
