### ISSUE TITLE
float_time widget does not work in pivot view

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#26390]
## Impacted versions:

11.0

## Steps to reproduce:

Go to Timesheet/Attendance menu to the report

## Current behavior:

It shows hours data like float numbers, even when the view has defined the fields to use float_time widget [code here](https://github.com/odoo/odoo/blob/11.0/addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report_view.xml#L32-L34)

![image](https://user-images.githubusercontent.com/7593953/44151129-ff794cba-a077-11e8-9bb9-f7b8516fb452.png)

## Expected behavior:

Should show the data as float_time not in float format. An example of the result we can found it in My Timesheet grid view.

![image](https://user-images.githubusercontent.com/7593953/44151187-28a7f71c-a078-11e8-89ae-c75309defccb.png)

**Comment by zaoral** [comment]
FYI opw-1876445

**Comment by sswapnesh** [comment]
BTW, This works fine in v10. Related commit dbaa345cec27d1a99556af6305e22e17e9760bb6

**Comment by zaoral** [comment]
Fixed and already merged thanks to @len-odoo 
related commits:  https://github.com/odoo/odoo/commit/8c1204954ef571e51e94ddf4070043ec2d5de3c6 and https://github.com/odoo/odoo/commit/a822d3ee41e04ab27d2587df0eee4efd441b1019
