### ISSUE TITLE
down payment  (percentage) should take percentage of new order line.

### ISSUE THREAD

**Issue by Omkar2295** [odoo/odoo#26397]
Impacted versions:
11.0

Steps to reproduce:
1. add new order line 
2. Enter amount and create invoice for that and validate it.
2. Again add new order line 
3. create invoice with selecting option Down payment (percentage).
4. click create invoice.

Current behavior:
- down payment will create on total of sales order.

Expected behavior:
- down payment  (percentage) should create on new order line (which is added currently)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
A down payment is always done over the total sales order, and it should be that way, as technically there's no option to distinguish when a new line has been added, but not only that, functionally speaking, you always receive a percentage of the full sales order.

If you don't want this behavior, just don't add new lines to existing invoiced sales orders, but create a new one.

Closing as no valid issue.
