### ISSUE TITLE
EE 11.0 - account_online_sync - Initial sync create only one bank statement.

### ISSUE THREAD

**Issue by alan196** [odoo/odoo#26391]
EE ticket: 1876449

Steps to reproduce:
- Create a new Journal with the following configurations:
  - Type: Bank.
  - Bank Feeds: Bank Synchronization.
  - Creation of bank statement: Any different than "Create one statement per synchronization".
- Then press the button "Configure" to add a bank account.
- When the wizard asks, select the date to sync since, and set to retrieve more than 1 month.
- Sync bank.

Current behavior:
- It creates only one bank statement.

Expected behavior:
- Create one or more banks statements depending on `Creation of bank statement` field.

It should be the next if you set:
- Create daily statements:
  - One bank statement per day.
- Create weekly statements:
  - One bank statement per week.
- Create bi-monthly statements:
  - One bank statement every 15 days.
- Create monthly statements.
  - One bank statement per month.

**Comment by oco-odoo** [comment]
Hi @alan196 ,

Thank you for your feedback. I created a task on our internal tools so that we can consider changing this behavior for the future versions of Odoo (not v12, though, as it has already been frozen, so we don't add any new stuff to it). We will keep you posted once we have taken our decision.

**Comment by cagecube** [comment]
This issue still exists in v13. Just FYI.

**Comment by oco-odoo** [comment]
It actualy has been done in saas-13.1 by @csnauwaert , here:

https://github.com/odoo/odoo/commit/0d6332fdbbea996aaae2dd07fb3c20deeb3a53b2
https://github.com/odoo/enterprise/commit/6136b991e1a6d6671abb733af86ec3ced18d920c

We simply forgot to close the issue, so I'm doing it now ;)
