### ISSUE TITLE
report_saleorder_document missing translation for Tax after Subtotal

### ISSUE THREAD

**Issue by Perino01** [odoo/odoo#26416]
Impacted versions: 11

Steps to reproduce: Print a quotation

Current behavior: Quotation calculation summary consists of Subtotal, Taxes, Amount_Total

The Term "Tax" eg Tax 20% will not be translated to the system defined language. In my case German. 
It seems to be a calculated value.

Expected behavior: In my case it should be "Steuer 20%" instead of "Tax 20%".

Video/Screenshot link (optional):

![grafik](https://user-images.githubusercontent.com/29162103/44249597-e0c48a80-a1f0-11e8-932a-5b5c7a3d0baf.png)

**Comment by pedrobaeza** [comment]
This has been already explained in #25034, so closing.
