### ISSUE TITLE
odoo v8  Pricelist   Min.Quantity   is not working for POS    

### ISSUE THREAD

**Issue by santosrody** [odoo/odoo#2641]
Pricelist  Min.Quantity is only working under  "Sales"  but if you  try to use it  under  the POS,  price will not change  accordingly

Product  prices  are not  change  according  to a  Minimun  set  in  pricelist   under  POS
but  they  would change  under  Sales   > Sales Order     

![pricelist](https://cloud.githubusercontent.com/assets/7780499/4371766/743a9238-431c-11e4-9d5f-2963d6f73b6b.png)

**Comment by Yenthe666** [comment]
Hi @santosrody,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
