### ISSUE TITLE
Searching record with "\" (Backslash) in field

### ISSUE THREAD

**Issue by brandon-blb** [odoo/odoo#26426]
Impacted versions: 11.0

Steps to reproduce:
 1. Create a customer with name "Test\name"
 2. Try to search for the customer using "Test\name"

Current behavior: 
 - Record is not found during search using `Test\name`.
 - Record is found when using 2 backslashes. `Test\\name`.

Expected behavior: 
 - For the record to be found when using just 1 backslash.

Video/Screenshot link (optional):

The following was done on **odoo.demo.com**

Created customer with \ in name:
![image](https://user-images.githubusercontent.com/10627196/44261032-a1a93000-a216-11e8-9b7e-fbe80287375c.png)

Searching for the customer using 1 backslash:
![image](https://user-images.githubusercontent.com/10627196/44261128-f2b92400-a216-11e8-98b8-64bee4fe05ef.png)

Searching for the record using 2 backslashes:
![image](https://user-images.githubusercontent.com/10627196/44261235-55122480-a217-11e8-9a0b-187969fa9a00.png)

**Comment by pedrobaeza** [comment]
Uhm, this seems a side effect of using Postgres SQL directly. @mart-e have you experienced this?

**Comment by mart-e** [comment]
Hi,

You are right about it, you need to use a double backslash or the operator "is equal to".
Please see the discussion about it at https://github.com/odoo/odoo/issues/5366#issuecomment-78053627
I am afraid we won't change that.
