### ISSUE TITLE
Odoo v10: Partial product consumption on manufacturing

### ISSUE THREAD

**Issue by Mikaelskou** [odoo/odoo#26433]
Impacted versions: Odoo v10

Sorry for not following the template, but this is more of a request for help, rather than a bug.

We are struggling alot to make the manufacturing module suit our needs. From my understanding when creating a manufacturing order, you can't partially consume products in the BoM as they are available. Lets say we are producing product: a

This product requires many components but for simplicity lets just say the BoM consists of: b, c and d.

What we want is the possibility to start the production gradually with products available in our warehouse, lets say b is the only product currently available, then we would like to be able to register that b is now in production (thus subtracting one from our stock) and marking that b has been installed in our production. Then whenever c and d becomes available the same would be possible.

As I see it right now you can only validate the manufacturing order once every component becomes available, and only then the inventory stock becomes updated. Up untill this point products available are only reserved for the move Stock -> Production, but they are still showing in our inventory and very hard to monitor. Has this been an issue for anyone else?

This makes inventory control very unreliable as many of our components might be in production and thus not actually available in stock if that makes sense. Hopefully someone can shed some light on this issue, as its a big hurdle for us, since our production can take upwards of weeks to complete. Surely we can´t be the only company using Odoo with a longer production time.

**Comment by intero-chz** [comment]
That's is more a matter of filtering here. If quants (actual stock units) are reserved, no other process can use or reserve them. So these quants are forecasted as negative stock. In products you will see that on the "Forecasted" smart button. The "On Hand" smart button shows the **real** stock there is, reserved or not.
On stock reports just try to filter more. For example in the "Inventory Valuation" report add the filter "Reserved for move is not set".

So no real issue, but a functional question.

**Comment by pedrobaeza** [comment]
I agree with @intero-chz that this is more a knowledge gap about how to use the module than a missing feature. For the record, you can make partial consumption, but it should be done manually setting the quantities on the manufacturing order. You have any way the available quantity on it for knowing what can be done.

For more questions, you can go to Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
