### ISSUE TITLE
Odoo - PosBox Less Printer Disconnect

### ISSUE THREAD

**Issue by oscarruz** [odoo/odoo#26437]
Hello,

I have installed to develop the Odoo Point of Sale. I have in the same raspberry the Odoo Point Of Sale and the Posbox Less(to manage printer).

At moment the Odoo Point Of Sale is running fine and the Posbox Less too. I can see in http://IP:8069/hw_proxy/status the printer but the printer doesn't print automatically the ticket when run the service and turn on the printer... 

The problem is to print tickets from Odoo Point Of Sale. It's display an icon to LAN disconnect and the printer isn't print.

In the official documentation doesn't talk about any configuration file or whatever:

https://www.odoo.com/documentation/user/10.0/point_of_sale/overview/setup.html#id2

I am a bit confused and I would appreciate help with this topic.

Thanks!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
