### ISSUE TITLE
Packaged installers: how to add custom module?

### ISSUE THREAD

**Issue by etiennebonnafoux** [odoo/odoo#26439]
Impacted versions: Odoo11 on Ubuntu 18 installed with Packaged installers

Steps to reproduce:
Install odoo 11 following https://www.odoo.com/documentation/11.0/setup/install.html#linux

Current behavior: Connecting in SSH I don't locate any addons folder or http.py or I need to add a custom module and to desactivate csrf identification in the http.py file. How can I do it? Is it possible with this kind of installation?

Expected behavior: Ability to add custom modules and change the csrf certification.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
