### ISSUE TITLE
Internal Server Error  The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by cyberpollutionbd** [odoo/odoo#26445]
Hello, I am using ubuntu 16.04 LTS 64 bit. I was trying to install odoo 10 but face this error: Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

PLEASE HELP

![screenshot from 2018-08-18 19-43-29](https://user-images.githubusercontent.com/37775397/44299859-03ed5800-a31f-11e8-8095-c5bd7d3c3ef0.png)
![screenshot from 2018-08-18 19-43-22](https://user-images.githubusercontent.com/37775397/44299860-03ed5800-a31f-11e8-8598-2935ecf80537.png)

**Comment by mstuttgart** [comment]
@cyberpollutionbd you have a other application running in this address and port (sorry for my english :)). 
 
Run this command: 

```
 sudo netstat -tlpn | grep 8069
```
It show the application that listening in port 8069. It output is:

```
tcp        0      0 0.0.0.0:8069            0.0.0.0:*               LISTEN       CODE/python2
```
This CODE is process ID. For example, if CODE is 12345, run:

```
sudo kill -9 12345
```
After this, try run Odoo again.

**Comment by pedrobaeza** [comment]
Please don't publish more duplicated reports (ref. #26383) for something that is not an Odoo error, but a problem of your deployment. There has been many people including me that has told you already what is the problem, so please solve it as indicated and if not, use other medium for asking how to solve it.
