### ISSUE TITLE
[11.0] Disclosing database name even db-list is disabled

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#26451]
Impacted versions: 11.0

Steps to reproduce:

- Start server with [--no-database-list](https://github.com/odoo/odoo/blame/11.0/odoo/tools/config.py#L247) 
- Enable password reset From login page
- Reset Password

Current behaviour:
Password reset Link contains database name 
http://host/web/reset_password?token=xxxxxxxxx&**db=database_name**
(Adding db name does not makes sense if there is no proper --db-filter is applied.)

Expected behavior:
Database name should not be Visible.
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hi,

The `--no-database-list` prevents you to list the databases on your server, it does not hide the name of the database.

The option is useful if you have some non-odoo databases or if you are deploying a SaaS.

**Comment by sswapnesh** [comment]
But still you can consider this as Improvement in master as this parameter is doing nothing.
