### ISSUE TITLE
[11.0] sale price list unable to delete/remove multiple in item in pricelist  [New Feature Request]

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#26461]
Impacted versions:

Steps to reproduce: 
Hi, 
I would like to know if there is a quick way to delete a sales price list items. we have a pricelist with 1800 product and accidentally we re-imported the prices from xls which created a double entry for each product in this sales price list. 

Current behavior: Cannot delete multiple item in pricelist at once

Expected behavior: To be able to delete multiple item in pricelist at once, considering create a checkbox like in product view and let user checkbox and delete at once

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/26357404/44328898-171e3600-a48d-11e8-86e3-36b31a25832f.png)

**Comment by pedrobaeza** [comment]
As @sswapnesh has said, what you want to achieve should be done in one of both ways, but this can't be covered on core. The OCA module will hardly be part of the core as it complicates the interface in all x2many widgets for a rare use case.

Closing as answered.
