### ISSUE TITLE
Impossible to install/upgrade "l10n_fr_fec" module

### ISSUE THREAD

**Issue by ertus-odoo** [odoo/odoo#26462]
Impacted versions:
Odoo V10 Enterprise

Steps to reproduce:
Init French database. Then, install accounting and the module with technical name "l10n_fr_fec". First, I had error on missing library unicodecsv. After installing manualy this library, the moduel stay in state "to update" in modules list.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![capture d ecran 2018-08-20 a 10 36 34](https://user-images.githubusercontent.com/37842397/44329685-56389100-a465-11e8-91cd-9549c67dc5fb.png)

Thank you

**Comment by mart-e** [comment]
Hello,

Cancel the installation and try to reinstall it. If you have an error message, please share.

**Comment by ertus-odoo** [comment]
Done, but problem still there. 

Logs =>
![capture d ecran 2018-08-20 a 12 06 42](https://user-images.githubusercontent.com/37842397/44334412-b6cdcb00-a471-11e8-8fcc-6e1fc962caa0.png)

Thanks

**Comment by mart-e** [comment]
Your logs don't really show an error, it just says the module is not installable. What is the current state of your module? To update? What happens if you try to update it?
Have you restarted odoo after installing the missing library?

Alos, when you share code/logs, please copy/paste them here inside a code block instead of a screenshot, easier to read.

**Comment by pedrobaeza** [comment]
I think the addons path is not accessible by Odoo user. Check permissions.

**Comment by ertus-odoo** [comment]
The current state : "To upgrade"
If I try to upgrade it, I'm redirect to homepage and the state is still "To upgrade". Logs are the same I sent you.
Yes I restart Odoo after installing library.
I have many customs modules why permissions set on root, all work. I tried with permissions for Odoo user, still have the problem.

I hadn't the problem with my local machine.

Thanks

**Comment by pedrobaeza** [comment]
I would bet for permissions problems on addons directory. Check created pyc files. But definitively this is not and Odoo issue, but deployment one, which should be treated on Odoo forums or mailing lists.

**Comment by ertus-odoo** [comment]
I found. Problem with addons path.

On server of production, community addons path was positioned at the beginning, before custom modules. I don't know who did that. I duplicate the database from production server to test server. On test server, addons path is different.

Can you say me what is the right method to construct addons path ? I have the feeling the rules change every times.

odoo_community_path/addons
+ odoo_community_path/odoo/addons ?
+ customs_modules_path
+ odoo_enterprise_path

And how to fix problem when you move a database from an environnement to another and addons paths are not the same ?

Thank you for your help

**Comment by mart-e** [comment]
The addons path is not stored in the database so, as long as two modules do not have the same name, the path to the modules does not really matter.
If you have moved around the modules, maybe try to refresh the list of modules ("update module list" button in debug mode).

Have you tried installing/updating the module using the [command line](https://www.odoo.com/documentation/11.0/reference/cmdline.html) too?

**Comment by ertus-odoo** [comment]
There are 2 modules with this name. 1 in Odoo modules, 1 in customs modules for FR spécifications! I always refresh module list but no changes. I didn't try with command line but i think the result will be the same. Now the module is install, I'll try next time !

Thank you for you help
