### ISSUE TITLE
Please, I need help with locale() and 'destroy' error

### ISSUE THREAD

**Issue by alexrasen** [odoo/odoo#26484]
Impacted versions:
Odoo Community 11.0

Steps to reproduce:
Trying to create a new Quotation

Current behavior:
Trying to create a new quotation: 
Uncaught TypeError: locale() locale es is not loaded from moment locales!

Expected behavior:
Create new quotations  with no errors... D:

Video/Screenshot link (optional):
http://prntscr.com/kl2dyx

Can you help me to fix it please? :(

**Comment by Yenthe666** [comment]
Hi @alexrasen,

The Github issue tracker is only for bugs in the official code, this is not the right place to ask questions.
Please ask your questions on the official help forum at https://www.odoo.com/forum/help-1 where plenty of people can help you.

Regards,
Yenthe
