### ISSUE TITLE
Date of Transfer(date_done) on stock picking is date of Odoo operation, but it should be date of warehouse operation(date of recieving goods or delivering goods).

### ISSUE THREAD

**Issue by xfx-oscg** [odoo/odoo#26482]
Impacted versions: 
Odoo Community Edition 9.0, 10.0, 11.0

Steps to reproduce:

Current behavior:
1） Odoo user can set date_done of picking and then validate picking.
2） When picking being validated, if date_done is set(not false), Odoo should not set date_done (with current date).
3) This issue exist in Odoo 9.0, 10.0 and 11.0 .
In Odoo 11.0, Code is in module stock, file stock_picking.py, method action_done():
`    todo_moves._action_done()`
`   self.write({'date_done': fields.Datetime.now()})`

Expected behavior:
1) field date_done on stock.picking should be editable(readonly=False):
`date_done = fields.Datetime('Date of Transfer', copy=False, readonly=False, help="Completion Date of Transfer")`

2) if date_done is set, Odoo should not set that with current date.
`if self.date_done:`
`    todo_moves.with_context(force_period_date=self.date_done)._action_done()`
`else:`
`    todo_moves._action_done()`
`    self.write({'date_done': fields.Datetime.now()})`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@jco-odoo what do you think about this? Maybe we can avoid writing the date if already filled.

**Comment by jco-odoo** [comment]
No, this is a feature request not to do things in Odoo. If you want that, you can easily add your own custom field and fill it in there.

**Comment by xfx-oscg** [comment]
@jco-odoo Yes, add a custom field is easy, but date of account move is not correct!

**Comment by hedshefer** [comment]
@Yenthe666
Yenthe666
