### ISSUE TITLE
Tutorial: Theme tutorial contains wrong javascript example

### ISSUE THREAD

**Issue by Biirra** [odoo/odoo#26494]
Impacted versions: 9.0

The code that is used as a javascript example does not work for odoo 9.0. 
This should be fixed since the example for odoo10 and newer isn't working either. 

the correct example for odoo 9 should be:
```
odoo.define('theme_tutorial.tutorial_editor', function (require) {
    'use strict';
    var options = require('web_editor.snippets.options');

    options.registry.snippet_testimonial_options = options.Class.extend({
        on_focus: function(){
           alert("On focus!");
        }
    });
});
```

link:
https://www.odoo.com/documentation/9.0/howtos/themes.html#javascript-options

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported I'm closing this issue.
Don't hesitate to post back if you can see the same issue in newer versions but I believe it is not present in 10 and up?

Regards,
Yenthe

**Comment by ateneolab** [comment]
This error persists in V12. This code does not work: var website = odoo.website;

What is the correct way to do that?

Thanks.
