### ISSUE TITLE
[Stock][11.0] product_qty and reserved_availability are not in the same unit

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#26504]
Impacted versions:
11.0

I don't know if it is an issue, but I think is strange.

`product_qty` is in unit of `product` : https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move.py#L240
`reserved_availability` is in unit of `stock.move` : https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move.py#L295

`move.product_qty - move.reserved_availability` seems to have no sens, no ?

https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move.py#L915
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move.py#L917
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move.py#L924

thank for your answer

@jco-odoo 
@alnslang

**Comment by wtaferner** [comment]
@jco-odoo @sle-odoo @pimodoo @amoyaux 
Seems really a bit weird...

**Comment by amoyaux** [comment]
@wtaferner @fmdl Yep, It's a bug, good job. I will fix it. Thanks for reporting

**Comment by fmdl** [comment]
OPW  1878897
