### ISSUE TITLE
Customer/Supplier address fields overlap when window is resized

### ISSUE THREAD

**Issue by scperkins** [odoo/odoo#2651]
Impacted versions: 8.0

Steps to reproduce:
1. Create a customer/supplier
2. Edit address fields Town, State, Zip (eg 'Freemont', 'California', '94538')
3. Adjust browser width to 950px or below and notice text overlaps.

Current Behavior:
![screenshot from 2014-09-23 11 01 20](https://cloud.githubusercontent.com/assets/2635358/4374401/f9ebf6da-4333-11e4-82e1-cac1827fda60.png)

**Comment by Yenthe666** [comment]
Hi @scperkins,

This has been fixed in the meanwhile and shouldn't be a problem anymore.

Regards,
Yenthe
