### ISSUE TITLE
Breadcrumbs lose full-width class when editing name

### ISSUE THREAD

**Issue by COUR4G3** [odoo/odoo#26525]
**Impacted versions:**
11.0

**Steps to reproduce:**

1. In a form with breadcrumbs, edit
2. Edit the name field (or the field that appears in the breadcrumb)
3. Save

**Current behavior:**

o_control_panel loses the o_breadcrumb_full class on save, and if your breadcrumbs are too long they wrap at 50%.

**Expected behavior:**

o_control_panel should retain the o_breadcrumb_full class on save.

**Video/Screenshot link (optional):**

![o_breadcrumb_full there](https://user-images.githubusercontent.com/12022074/44470898-13c0b100-a62b-11e8-9987-81f198921fdf.PNG)
![step1](https://user-images.githubusercontent.com/12022074/44470907-16230b00-a62b-11e8-8d98-93a17ed930a6.PNG)
![step2](https://user-images.githubusercontent.com/12022074/44470911-17ecce80-a62b-11e8-990e-cfb06ce3e75a.PNG)
![step3](https://user-images.githubusercontent.com/12022074/44470913-1a4f2880-a62b-11e8-971b-c241cc67b863.PNG)
![o_breadcrumb_full gone](https://user-images.githubusercontent.com/12022074/44470917-1c18ec00-a62b-11e8-9661-2f47d80652fb.PNG)

**Comment by pedrobaeza** [comment]
@qsm-odoo maybe you can check this.

Another thing I personally find annoying is to have full name_get text in the breadcrumb. Maybe a max-length can be applied through CSS?

**Comment by qsm-odoo** [comment]
@pedrobaeza I prefer that the framework team checks that kind of request first :)

@ged-odoo @aab-odoo

**Comment by pedrobaeza** [comment]
OK, thanks. I didn't know if I should ping them as this is something a bit sided.

**Comment by Yenthe666** [comment]
@aab-odoo did you have the time to look into this yet?

**Comment by aab-odoo** [comment]
@Yenthe666 Sorry, i didn't. I'll try to fix it soon.
