### ISSUE TITLE
[11.0][mail] mail activities shall not be deleted for reporting purposes

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoo/odoo#26531]
Impacted versions:
11.0

Mail activities are currently being deleted when they are marked as done.

This turns to be a huge problem for sales people who wish to analyze on activities performed by the sales personnel, for example. 

Perhaps a more sensible approach is to flag them as done, and hide them from the chatter and stat bars, but to allow viewing them in the reports.

See an implementation of this feature in https://github.com/OCA/social/pull/296
@pgu-odoo @tde-banana-odoo

**Comment by nhomar** [comment]
1000000% agree!! it is a little weird lost data on such design.

**Comment by tde-banana-odoo** [comment]
Hello,

Once done a message is logged on the document. Logged messages have a mail_activity_type_id field linked to the activity type of the done activity. You can use those information for reporting. Author is the user that marked the activity as done so you have most information available. Do you see any missing information using that ?

Regards,

**Comment by jbeficent** [comment]
Mixing models for reporting purposes seems to me a bad practice, plus you might be loosing data. Perhaps not odoo data, but people might maintain extra fields in the mail.activity that are then to be used for reporting.

IMHO deleting data is a bad practice.

**Comment by tde-banana-odoo** [comment]
In that case you can override action_feedback and rewrite it to avoid the unlink. I understand it can be an issue if you customize the activity model. This is a design choice, we choose to remove the activities done as there would be no extra information compared to messages. If you feel you need it in custom modules an override should be done for activity_feedback. Maybe keep an eye on event and voip (enterprise) overrides if overriding action_feedback without calling super.

Edit: I see you patched it in OCA :)

**Comment by Yenthe666** [comment]
@tde-banana-odoo we have the same problem at V11 customer of us.
I don't think it makes sense to delete records. What if you want to keep historical data or look at the history of these items? I'd really like to see a design change in this. Dropping records is way too harsh

**Comment by pedrobaeza** [comment]
@tde-banana-odoo is there any decision about this?

**Comment by tde-banana-odoo** [comment]
I don't think so. Both sides are still engaged in war.

**Comment by pedrobaeza** [comment]
hehe, OK, then I suppose I can leave this opened.

**Comment by msanchezceb** [comment]
Hi all,

Please, have a look at this module "mail_activity_done". In its description is says:

"This module implements the capability to keep activities that have been completed, for future reporting, by setting them with the boolean ‘Done’.

The activities that have been completed will not appear in the chatter.".

I installed it and now activities are not deleted once they are marked as completed. 

Hope this helps,
Mireya.

**Comment by pooja-zakhariya** [comment]
Hello,
It does not continue summary when converting to mail.message so subject/summary will be lost once mail.activity will be removed.

**Comment by Yenthe666** [comment]
@msanchezceb "mail_activity_done" is a third party app right? Ideally this is handled better in default Odoo.

**Comment by msanchezceb** [comment]
Hi @Yenthe666, this module is from the OCA if I'm not wrong...

![image](https://user-images.githubusercontent.com/39948914/57678363-5139f400-7629-11e9-8031-1d238efaf1c1.png)

**Comment by kdc-ft3** [comment]
@tde-banana-odoo - 

Activities can be a very powerful feature.  I would like to add my voice to those requesting this enhancement.

@jbeficent makes a powerful point.  I assumed that tracking customer contact activities - done and undone - would simply be a matter of exporting the activities on customers... and it's been a sad surprise that this is not the case.

My humble perspective and desire is as follows:

1. - that the activity be marked done and left undeleted, for the benefits mentioned
2. - that on completion a message is also logged.   
3. - that an optional completion date field be available when one marks an activity done 

      
The reasons for 2 & 3 above I hope are obvious 
- having the message in the chatter is useful because you can see the history - for example of interaction with a customer - in the chatter of the customer record
- If we are using the activities for activity tracking, then it's useful for one to be able to state not just that an activity was done, but when it was done


Respectfully, 


~KDC
Odoo Learning Partner

**Comment by tde-banana-odoo** [comment]
Hello,

It has been decided to keep current behavior. Reasons are
  * there is a reporting tool available in CRM;
  * "if necessary, it can be done with Studio" (hem);
  * concerning database, all activity information is stored inside messages meaning their content can be retrieved using a bit of custom search;

To develop a small tool to find done activities, you can search on messages with subtype_id being "mail.mt_activities", subtype used when logging an activity as done. This message has a field mail_activity_type_id holding the activity type that was on the done activity.

Normally with this information you can do a reporting on done activities without too much efforts.

Many thanks,
