### ISSUE TITLE
Installing Theme Bootswatch raises an error

### ISSUE THREAD

**Issue by drewes** [odoo/odoo#26536]
Impacted versions: master

Steps to reproduce: Install new database using master branch (12), install website module and select Theme Bootstrap 

Current behavior: Error is raised

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: mode - mode] 

Expected behavior:

Succesful installation of Theme Bootswatch

Video/Screenshot link (optional):
<img width="714" alt="grafik" src="https://user-images.githubusercontent.com/1628473/44509033-b1aa8f00-a6b0-11e8-9f65-16216af51a51.png">

**Comment by JKE-be** [comment]
Know issue
Thanks to avoid to open issue for master branch :)

**Comment by drewes** [comment]
Apologies. Was just trying to help. Fantastic work.

**Comment by JKE-be** [comment]
Thanks for the reporting and the help

It has been fixed here : https://github.com/odoo/odoo/commit/ceef32500df5329a656c26d14e264e5c9c4b836e

(In saas-11.5, that will arrive in master later)

Best regards
