### ISSUE TITLE
MemoryError (binary Field upload) / allocation size overflow (ir.attachment Field upload), Something horrible happened (Log note Attachment) When Uploading Huge File (Larger Than 300MB)

### ISSUE THREAD

**Issue by eva7sk** [odoo/odoo#26559]
Impacted versions:
10, 11

Steps to reproduce:
D:\Odoo\server\odoo\addons\web\static\src\js\fields\basic_fields.js
this.max_upload_size = 2048 * 1024 * 1024; //2GB

Current behavior:
MemoryError / allocation size overflow / Something horrible happened
Different file size (eg:300MB, 800MB) Trigger Different error messages (popup / odoo.log)

Expected behavior:
Upload many huge file Without performance risk

**Comment by eva7sk** [comment]
Actually, Different error messages will popup or Logged in odoo.log (Based on different file size, eg:300MB, 800MB)

**Comment by eva7sk** [comment]
Forgot to say: Tested with 8GB Memory Server, Odoo didn't eat all memory (About 30%~60% Memory Left)
Many big files in NAS here, We want to upload these files into Odoo Replace NAS

**Comment by pedrobaeza** [comment]
Well, as said, that's not for what Odoo has been designed, but @ged-odoo should confirm it.

**Comment by eva7sk** [comment]
Is there a way simply upload original file without serialization ? That I can back to NAS in the feature

**Comment by pedrobaeza** [comment]
Not directly. You will need to implement your own JS widget.

**Comment by eva7sk** [comment]
C:\EMS\server\odoo\addons\web\static\src\js\fields\basic_fields.js
on_file_change: function (e) {
filereader.onloadend = function (upload) {
                    var data = upload.target.result;    //The error popups from this line
                };
}

**Comment by eva7sk** [comment]
Odoo is Totally based on base64 Serialization, I think browser cannot handle when serialization large file

**Comment by eva7sk** [comment]
Hope Odoo support file streaming in 12
