### ISSUE TITLE
Lead Convert to Opportunity

### ISSUE THREAD

**Issue by anabeladamas** [odoo/odoo#26562]
Impacted versions:
Odoo version 11.0-20180820

Steps to reproduce:
Create a Lead just with name and Convert to Opportunity

Current behavior:
  File "/opt/odoo/odoo11/odoo/addons/crm/wizard/crm_lead_to_opportunity.py", line 29, in default_get
    tomerge.update(self._get_duplicated_leads(partner_id, email, include_lost=True).ids)
AttributeError: 'list' object has no attribute 'ids'

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @anabeladamas,

Thanks a lot for your report!
I've just tried this but it seems to work just fine on the latest V11:
https://drive.google.com/file/d/1twbHQnFtJBQY2ZmB1ABjxXilzqxDEYCr/view
Can you check and update your code please? Can you reproduce it on an official test instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by anabeladamas** [comment]
Hi,

In runbot, everything seems ok.
I wiil update my code, and test it.

Thanks and sorry for the inconvenience.


Yenthe V.G <notifications@github.com> escreveu no dia sexta, 24/08/2018
à(s) 09:01:

**Comment by Yenthe666** [comment]
@pedrobaeza thanks for the tip but doesn't seem to have Windows support sadly 😞 
@anabeladamas no problem. I'm closing this one as it has to be an issue in your local deployment.

**Comment by pedrobaeza** [comment]
:scream: you are using Windows! You should really consider switch to Linux as everything in Odoo is Linux oriented.

**Comment by Yenthe666** [comment]
Haha, don't worry! Al my Odoo's run on Linux, so do all the servers. I only work on Windows for things such as Outlook, Office, etc. All the Odoo stuff is handled in Linux 😄 This is just for work related purposes. I also develop on Linux 😉

**Comment by pedrobaeza** [comment]
You have joined my 2 personal most hated: Windows and Outlook :stuck_out_tongue_closed_eyes: 

I use Webmail (Gmail / Odoo) + LibreOffice in Linux without needing anything more IMO.

**Comment by Yenthe666** [comment]
We actually switched from Gmail to Outlook recently 😆 We started using SharePoint etc. I guess I'm going up on your person to hate list now!

**Comment by litmount** [comment]
Actually, I just encountered this error while testing something. This is on V10 but I suspect it happens on V11 also. 
Steps to reproduce. 

1. Create a lead with only Lead Name & "Company Name" filled in and nothing else.  (Note: Company name not Customer field)
2. Duplicate or create a new lead with the same exact Company Name.  
3. Then hit convert to opportunity button on either of the duplicates. 
4. It will throw the traceback error anabeladamas reported.
