### ISSUE TITLE
[META] : Links are not clickable directly inside rich text box help forum.

### ISSUE THREAD

**Issue by AnilKesariya** [odoo/odoo#26573]
**Impacted versions:**
Current and past versions too.

**Steps to reproduce:**

Copy any link into the text box and submit the answer or question. It won't be clickable anymore until user will set the link attribute into it. system should auto detect the links.

**Current behaviour:**
If paste link in text box it won't be clickable until unless we set link from tool. 
http://jupical.com/

**Expected behaviour:**

Direct links should be clickable in read only mode.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Thanks for the suggestion.
