### ISSUE TITLE
[META] help forum : Image is getting disappear after on help form text box.

### ISSUE THREAD

**Issue by AnilKesariya** [odoo/odoo#26574]
**Impacted versions:**

Live version

**Steps to reproduce:**

- Just added image with .png extension, it is visible in edit mode. once you will save it will disappear.

- Web browser used Google Chrome.

**Current behaviour:**

Image with png extension is getting disappear from the box on read only mode.

**Expected behaviour:**
 It should be visible,like jpeg file.

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi

Thank you, bu we cannot reproduce your issue.

Best regards
