### ISSUE TITLE
Odoo help forum: is it possible to increase the posts limit? [Website] [Wishlist]

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#26585]
Steps to reproduce:
Add post with images, it will be in "waiting for validation" stage
Current behavior:
Once there is a post that is waiting for validation user is unable to post any more posts and is getting "You already have one pending post.
Please wait for a moderator to validate your previous post before continuing."
Expected behavior:
Allow user to log more questions on forum, so if one(with imgs) needs a validation it won't prevent user from asking other questions.

Just a suggestion

**Comment by pedrobaeza** [comment]
I think that is an anti-spam measure, so it's that way by design until you get more karma.

**Comment by cierek** [comment]
it is for sure an anti-spam but it could be useful to lose the rules a bit

**Comment by Yenthe666** [comment]
I guess we could atleast bump it up to three posts, which covers any normal behaviour for normal users. Spammers cannot make more than 3 per account and they're in queue so there is little harm there too. This way we don't punish normal users (or atleast we assume they are) because of spammers.
