### ISSUE TITLE
module stock_account method _run_scheduler_tasks( ) should commit 

### ISSUE THREAD

**Issue by xfx-oscg** [odoo/odoo#26584]
Impacted versions: 
community 11.0

Steps to reproduce:
1) Scheduled Actions Procurement: run scheduler, Run manually 
2) Module stock_account, file stock.py, method _run_scheduler_tasks( ), code 
     self.env['stock.move']._run_fifo_vacuum() 
   is not commited!

Current behavior:

Expected behavior:
method _run_scheduler_tasks( ) should commit as below:

    @api.model
    def _run_scheduler_tasks(self, use_new_cursor=False, company_id=False):
        super(ProcurementGroup, self)._run_scheduler_tasks(use_new_cursor=use_new_cursor, company_id=company_id)
        self.env['stock.move']._run_fifo_vacuum()
        if use_new_cursor:
            self._cr.commit()

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why it should commit()? You should avoid as max you can manual commits.

**Comment by xfx-oscg** [comment]
@pedrobaeza  It's obviously a Bug！Since missed commit, self.env['stock.move']._run_fifo_vacuum()  is no impact on database.
The same method in module stock, file procurement.py, is commited:
    @api.model
    def _run_scheduler_tasks(self, use_new_cursor=False, company_id=False):
        # Minimum stock rules
        self.sudo()._procure_orderpoint_confirm(use_new_cursor=use_new_cursor, company_id=company_id)

        # Search all confirmed stock_moves and try to assign them
        confirmed_moves = self.env['stock.move'].search([('state', '=', 'confirmed'), ('product_uom_qty', '!=', 0.0)], limit=None, order='priority desc, date_expected asc')
        for moves_chunk in split_every(100, confirmed_moves.ids):
            self.env['stock.move'].browse(moves_chunk)._action_assign()
            if use_new_cursor:
                self._cr.commit()

**Comment by pedrobaeza** [comment]
OK, I see the problem. The method is called after calling `super`, and thus this never gets committed. It's a valid bug then.

@jco-odoo can you check this?

**Comment by sle-odoo** [comment]
the cron commit after processing its jobs
