### ISSUE TITLE
[FIX] Payment Integration error.

### ISSUE THREAD

**Issue by jsilvestar** [odoo/odoo#26586]
Impacted versions: 10.0

Steps to reproduce:
"1. Click on ""Website"".
2. Select any product.
3. Click on ""Add to cart"".
4. Click on ""Process to Checkout"".
5. Click on ""Confirm"".
6. Click on ""Pay Now"" button. 
7. Click on ""Back"" button.
8. Select ""Braintree"" under Payment Method method.
9. Click on ""Pay Now ->"" button.
10. Enter ""Card Number"".
11. Enter ""Expiration Date "".
12. Click on ""Pay Now"" button and observe.
13. Nevigate to Terminal and observe the Traceback." or Check the console.

Current behavior:
![payment_error](https://user-images.githubusercontent.com/34209318/44601052-e6c1f900-a7f8-11e8-91cc-f307117d0f19.png)

Expected behavior:
       Raise Warning 

Video/Screenshot link (optional):
https://drive.google.com/file/d/1ABveeI6FcNt7w9vSoNIMUAIJJDjvWA73/view

Regards,
Silvestar J.

**Comment by pedrobaeza** [comment]
Please show the traceback with debug=assets mode (https://odoo-development.readthedocs.io/en/latest/odoo/usage/debug-assets-mode.html)

**Comment by jsilvestar** [comment]
@pedrobaeza 

i have enabled and ended up with same problem.
![paymentpage](https://user-images.githubusercontent.com/34209318/44615094-cb81d880-a84e-11e8-9cf4-fba4b62da229.png)

**Comment by mart-e** [comment]
The problem is that we do not know the content of the request that is sent.
Could you, go to the network tab and check that request is failing? If you right click on the request, you should have a "copy data" or "copy as curl" option.
Please share the result

**Comment by sswapnesh** [comment]
I am not able to Reproduce this on latest Runbot build.

**Comment by jsilvestar** [comment]
hello @mart-e 

 after successful transaction going to same page and make another transaction it does not contain any request.

**Comment by jsilvestar** [comment]
hello @sswapnesh ,

please check the console.

**Comment by JKE-be** [comment]
Hi

Thank you, 

But if I'm not wrong, it works...
You try to paid for an obscure reason a already locked transaction and it don't allow you.

So yes we could improve the error management in a futur version, but we don't plan to improve it in stable.

Back from browser is hard to manage since it use his own cache. If you make an F5, you will see that the cart is empty and so you have nothing to paid
