### ISSUE TITLE
Odoo 10 missing form view button in the view switcher at the top right corner like it was on v9.

### ISSUE THREAD

**Issue by fuegita** [odoo/odoo#26591]
After database migration from v9 -> v10 when going to Settings->Application Terms->Translated Terms I can't see list/form view buttons in the view switcher at the top right corner like it was on v9.
v9 example:
![v9](https://user-images.githubusercontent.com/17007193/44622321-e5f39a80-a8be-11e8-8b2b-7b3d800cbb30.jpg)
v10:
![v10](https://user-images.githubusercontent.com/17007193/44622332-fad02e00-a8be-11e8-80a9-6c979c49012c.jpg)

Is this an intended feature in v10 or a bug? If it is an intended feature how can I enable it when I am creating a new records because I some fields for creating/editing are only available in it (Module, Record ID)?

**Comment by pedrobaeza** [comment]
Yes, it's intended. Now there's only editable list view. You shouldn't add terms that way. Go to "Synchronize Terms" for adding missing terms instead of create them manually.

Closing as no real issue.
