### ISSUE TITLE
Purchase report pivot view average price calculation issue. 

### ISSUE THREAD

**Issue by dibindevassy** [odoo/odoo#26600]
@Yenthe666 purchase report pivot view average price calculation is wrong can you please help to solve it.

Impacted versions: 11.0

Steps to reproduce: 
1. Purchase -> Reporting -> Purchase Analysis 
2. Expand group by Vendor.
3. Expand Vendor by Month.
4. Expand by Day.
5. Group by Product. 

Current behavior: 

              Total Price | Product Quantity | Average Price
22 Aug 2018  | 8050       | 411.85                 | **7.99875**
Product 1       | 4200.06  | 125.6                   | 33.44
Product 2       | 349.92    | 48                        | 7.29
Product 3       | 3200.79  | 159.8                   | 20.03
Product 4       | 300.03    | 74.45                   | 4.03
Product 5       | -0.8         | 4                          | -0.2

Expected behavior:

               Total Price | Product Quantity | Average Price
22 Aug 2018  | 8050       | 411.85                 | **12.918**
Product 1       | 4200.06  | 125.6                   | 33.44
Product 2       | 349.92    | 48                        | 7.29
Product 3       | 3200.79  | 159.8                   | 20.03
Product 4       | 300.03    | 74.45                   | 4.03
Product 5       | -0.8         | 4                          | -0.2

Video/Screenshot link (optional):

![issue](https://user-images.githubusercontent.com/10357384/44649107-02ddba00-a9f4-11e8-9948-1be1982b80af.png)

**Comment by pedrobaeza** [comment]
I'm afraid that this is not possible to achieve because the way it computes the SQL, making aggregations at the group level, and it's already a known limitation for average computations.

**Comment by Dayssam** [comment]
@dibindevassy 

you can do it by inherit 
`def read_group(self, domain, fields, groupby, offset=0, limit=None, orderby=False, lazy=True):`

```


        for r in res:
            if 'x' in fields:
                if r['y'] == 0 or r['y'] is None:
                    r['x'] = 0
                else:
                    r['x'] = 100 * r['z'] / r['y']
```

**Comment by sle-odoo** [comment]
As far as i can see, the newest updates on this report made the average price unit disappear and we now only get the total and untaxed total, i'm thus closing this issue.

I also think the solution to patch read_group is the right one but is a little complex for the value it adds to be considered, in my opinion.

Regards
