### ISSUE TITLE
[8.0][9.0][10.0][master] Field name "copy" on ir.model.field  conflict with "copy" method

### ISSUE THREAD

**Issue by sebastienbeau** [odoo/odoo#26618]
Impacted versions: all

On the model "ir.model.field" there is a field called "copy" : https://github.com/odoo/odoo/blob/master/odoo/addons/base/models/ir_model.py#L322

This name conflict with the method "copy" that exist browse record
https://github.com/odoo/odoo/blob/master/odoo/models.py#L4203

This make impossible to use the method copy on ir.model.field
And also raise warning when we make an inherits of the class ir.model.field (https://github.com/odoo/odoo/blob/master/odoo/models.py) as the field conflict with the method name

@odony @rco-odoo

**Comment by rco-odoo** [comment]
The bug is indeed present in versions 9.0, 10.0 and 11.0.
It **will not be fixed** in those versions, because schema changes are not allowed on stable versions.

However, a fix is on its way for the upcoming version 12.0.

Thanks for reporting!

**Comment by sebastienbeau** [comment]
If it's fix in 12 is perfect for me !
Thanks @rco-odoo !
