### ISSUE TITLE
[11.0] Company selection disappearing randomly

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#26610]
Impacted versions: 11.0

Steps to reproduce:
- Create many companies and give access to your user.

Current behavior:
- Sometimes when you create a new company the selection field disappears.
- After you add another company or remove one from your user it reappears.
- Happens randomly.
- Sometimes just by login out and login back in the selection will no longer show.
- Field doesn't show under user preferences either when this happens.

Expected behavior:
- Always show the selection field if the user has more than 1 company.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@edsersolis we need a reproducible way of getting the described behavior. Do you have all the companies added to the allowed companies in the user form?

**Comment by edsersolis** [comment]
@pedrobaeza of course all the companies are added for the user. No error is showing on the logs either.

It has happened with customers that have 3 or more companies.

**Comment by pedrobaeza** [comment]
Well, as said, without traceable steps to reproduce the problem, it's difficult to hunt this.

**Comment by Yenthe666** [comment]
@edsersolis can you please try to reproduce it on a runbot and make a video of it?

**Comment by sswapnesh** [comment]
This is possible if Multi Company is not enabled for that user.
It will work when you Add/Remove company because it will enable Multi company for that user.

**Comment by edsersolis** [comment]
I haven't been able to reproduce it on runbot. Once I'm able to identify the steps to reproduce the issue I'll be reopening the ticket.
