### ISSUE TITLE
[7.0] Getting Error while changing setting

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#2662]
When going to change setting got client error

Steps to reproduce issue:

> In 7.0 open setting form
> Open Account setting
> Make true checkbox of 'Allow Multi Currencies' and click on Apply button it will throw client error.
> And button will disappear. Attached ScreenShot of Error.

![configure accounting - openerp 2014-09-24 11-52-48](https://cloud.githubusercontent.com/assets/7599707/4384269/c4373146-43b3-11e4-99b1-81db2cba1e4d.png)

**Comment by Yenthe666** [comment]
Hi @dsu-odoo,

Thank you for the report.
As you know Odoo only supports the last 3 versions so this is no longer valid.
It does look fixed on 7.0 too though.

Regards,
Yenthe
