### ISSUE TITLE
[11.0]Can't translated `Save & Close` as one phrase

### ISSUE THREAD

**Issue by oleksandrpaziuk** [odoo/odoo#26629]
Impacted versions:

11

Steps to reproduce:

Try to change translation for the phrase `Save & Close`

Current behaviour:

Can't be translated as one phrase

Expected behaviour:

Can be translated as one phrase

Video/Screenshot link (optional):
English
![screenshot from 2018-08-28 13-21-46](https://user-images.githubusercontent.com/31699656/44717340-671c7e80-aac5-11e8-9f34-ca0adc00d6a6.png)

French
![screenshot from 2018-08-28 13-20-58](https://user-images.githubusercontent.com/31699656/44717357-70a5e680-aac5-11e8-9333-08ac049f2f96.png)

Source
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/view_dialogs.js#L125

**Comment by pedrobaeza** [comment]
But is it translatable by pieces?

**Comment by oleksandrpaziuk** [comment]
Maybe. But after I saw the code I did not try to translate it.
Also, I don't found `et Fermer` translation so I suppose it translates them as two separate words.

**Comment by pedrobaeza** [comment]
Yeah, this kind of tricks is for allowing to put several parametric texts, but the tradeoff is the split of the translatable words.

**Comment by mart-e** [comment]
Hi,

Indeed, as you have identified it is split in two parts as we want to allow to have more possibilities in between.
You can find the second part here
https://www.transifex.com/odoo/odoo-11/translate/#fr/web/119303230?q=text%3A'%26+close'
So what is the issue to work like this?

**Comment by oleksandrpaziuk** [comment]
Haven't access to https://www.transifex.com/odoo/odoo-11/translate/#fr/web/119303230?q=text%3A'%26+close'

**Comment by oleksandrpaziuk** [comment]
Problem is in how translation is organized.
from source code, we can see that we translate and then concatenate translated terms.
I think it will be more convenient if we first concatenate and then translate. In this case, we will have one phrase and one translation

**Comment by mart-e** [comment]
I have changed the way it is expressed at c77789b590c.
It is merged in saas-11.5 (future v12) as we can not change it in a stable version.
Thanks for the report.
