### ISSUE TITLE
[11.0] Discount doesn't show when pricelist is based on another pricelist

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#26639]
Impacted versions: 11.0

Steps to reproduce:
- Set price on a "Public Pricelist" pricelist for a product.
- Set the pricelist to show public price and discount (NOT in the price).

![image](https://user-images.githubusercontent.com/6585110/44731716-d6887300-aab1-11e8-9f30-7ae774a43aca.png)

- Create a new pricelist and set it to formula for a discount % and depending on another pricelist.
- Set the first pricelist (Public Price) as base for this one.

![image](https://user-images.githubusercontent.com/6585110/44731824-02a3f400-aab2-11e8-9243-f64c9eb67d85.png)

Current behavior:
- Even if the pricelist is set to have the discount shown it will show in the price. On the second image it should have taken a 2% on the discount but instead is showing in the price.

![image](https://user-images.githubusercontent.com/6585110/44732137-a55c7280-aab2-11e8-878c-5afad596aff9.png)

![image](https://user-images.githubusercontent.com/6585110/44732223-cf159980-aab2-11e8-84a9-5d89be8a3e3c.png)

![image](https://user-images.githubusercontent.com/6585110/44732253-e2c10000-aab2-11e8-84e8-35e51519a54d.png)

Expected behavior:

- Show the discount to the customer and not in the price even when the pricelist is based on another one and not on public price set on product.

**Comment by edsersolis** [comment]
**This a feature request / improvement.**

**Comment by mga-odoo** [comment]
The discount is always competed but the display option is trick and you will see discount based on which pricelist you have selected to display the discount on sales order

look at https://drive.google.com/file/d/1RxiTFrauhRp5GB6tdwxzkXE3OTJJZNlj/view video

Display discount selected on the Public pricelist + Special pricelist, 20% of 100 = 20 and 10% 0f 80 = 8 total 20+8 = **28%** discount will be discount visible on order

Display discount not selected on Public pricelist but selected on Special pricelist, 10% 0f 80 = **8%** discount will be discount visible on order

Display discount selected on the Public pricelist but not on Special pricelist, so no discount is visible on order as Special pricelist is applied on the sales order

**Comment by edsersolis** [comment]
Thanks @mga-odoo I doubled checked everything after your video. It works now.
