### ISSUE TITLE
Odoo Uncaught TypeError: Cannot read property 'controller' of null

### ISSUE THREAD

**Issue by pkpraveen052** [odoo/odoo#26642]
Impacted versions: 10.0

Steps to reproduce: **Clicking on a Menuitem pops up the bug**
![odoo error](https://user-images.githubusercontent.com/40301280/44739533-a96dac00-ab15-11e8-9d13-9ee157a00fba.PNG)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you able to reproduce the problem in runbot (https://runbot.odoo.com)?

**Comment by pkpraveen052** [comment]
This occurs more often. Also sometimes the property changes
Uncaught TypeError: Cannot read property 'type' of null

**Comment by pkpraveen052** [comment]
@pedrobaeza 
Steps reproduced in the runbot. Replicated there
![odoo error2](https://user-images.githubusercontent.com/40301280/44739810-737cf780-ab16-11e8-8933-f88ec712f0f8.PNG)

**Comment by pkpraveen052** [comment]
Now it raised on the property of 'type'

**Comment by pedrobaeza** [comment]
And what are the steps to reproduce the problem? Maybe you are not waiting until everything is loaded?

**Comment by pedrobaeza** [comment]
Closing as discussed in the other issue.
