### ISSUE TITLE
[Point_of_sale] Error with POS Sales with two journals in different currencies

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#26641]
Impacted versions: 11.0

Steps to reproduce: 

- In an instance with Multi-Currencies, create a Point of Sale with two Payment Methods (journals) which has different currencies, for example:

POS configuration:
![skitch](https://user-images.githubusercontent.com/11341058/44732013-70e8b680-aab2-11e8-8c09-00702910918e.png)

Journals:
![skitch 4](https://user-images.githubusercontent.com/11341058/44732059-8958d100-aab2-11e8-851d-84b6ed1ff046.png)

![skitch 5](https://user-images.githubusercontent.com/11341058/44732068-8d84ee80-aab2-11e8-9749-ebc278a09f94.png)

NOTE: In this case, journal sequence must be first MXN journal.
![skitch 6](https://user-images.githubusercontent.com/11341058/44732496-6b3fa080-aab3-11e8-94f4-4778f70236a7.png)

- Open a session POS.

- Register a Sale using payment method with USD currency:
![skitch 7](https://user-images.githubusercontent.com/11341058/44732617-b0fc6900-aab3-11e8-90b9-bbb35af15d38.png)

-Validate Sale.

Current behavior:
The payment of sale is registered in the USD journal and the remaining amount is registered in MXN journal without conversion.

Sale = $29
Payment = $30
Journal USD = $30
Jounal MXN = -1 MXN

Expected behavior:
The payment of sale is registered in the USD journal and the remaining amount is registered in MXN journal with the conversion currency.

Sale = $29
Payment = $30
Journal USD = $30
Jounal MXN = -1*(currency_rate) MXN

**Comment by ysantiago** [comment]
Hello @Yenthe666 

I want to know what is the status of this issue.

Thanks.

**Comment by Yenthe666** [comment]
@ysantiago open, as long as nobody responds there is nothing done for this ticket really.

**Comment by mart-e** [comment]
Hi,

How did you created this point of sale? You are supposed to get an error when configuring a pos with different currencies.

![screenshot_2018-09-11 main not used - odoo](https://user-images.githubusercontent.com/564822/45363462-e2a72100-b5d7-11e8-954a-8f466e9e4a14.png)

**Comment by ysantiago** [comment]
Hello @mart-e , thanks for your response!

I assigned the journals in POS first with the same currency, late I changed the currency in one of the journals.

**Comment by ysantiago** [comment]
@mart-e I propuse a solution in PR [odoo/odoo/26809](https://github.com/odoo/odoo/pull/26809)

**Comment by mart-e** [comment]
@ysantiago so this is the constraint that was not strict enough but the intention was clearly to specify that it is not something you should do.

I would not recommand relaxing the constraint in stable but instead, it could be a nice improvement to support multi-currency in the POS but it is a new feature.
For instance, if I supported multi-currency in payment method, I would expect to see the amounts to be converted in the pos interface. 
I am afraid, it is more complex than that to enable multicurrency.

I am closing this issue as we are not supporting multi-currency in the pos in 11.0. However, if you retarget your PR for master, we can try to make it work (and dropping the constraint, but it implies making the price conversion in the pos interface).
