### ISSUE TITLE
[master] social media content/icons not working

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#26648]
Impacted versions: Master

Steps to reproduce:
1. Go to settings > companies and edit the main company. Fill in all social links there:
![image](https://user-images.githubusercontent.com/6352350/44774452-722de800-ab73-11e8-963f-e2355b48365a.png)
2. Go to the website and look how the footer isn't showing the icons for those filled in records, it only seems to show the ones that are there in demo data:
![image](https://user-images.githubusercontent.com/6352350/44774637-e4063180-ab73-11e8-8323-2dec2dd02146.png)

Current behavior: The social media icons are not shown while the values are set.

Expected behavior: Show all social media icons that have content in the field.

**Comment by Yenthe666** [comment]
@JKE-be I found a bug in the upcoming V12 website, can you fix?

**Comment by sswapnesh** [comment]
That's because those fields are not Related to Company(Website's company) anymore.

**Comment by sswapnesh** [comment]
Adding demo data for Social Youtube/Github would be great.

**Comment by Yenthe666** [comment]
@sswapnesh demo data should be coming, see my PR https://github.com/odoo/odoo/pull/26649
& Tested your way and setting on company, still doesn't work fine in frontend.

**Comment by sswapnesh** [comment]
Thanks for the PR reference.
You have to add those fields in website view and set original values there.
Changing/Removing fields from company will not work here.

**Comment by sswapnesh** [comment]
Maybe they missed to manage this during New multi-company feature development.

**Comment by JKE-be** [comment]
@sswapnesh 
It has been fixed meanwhile

I have just tested on last saas-11.5

http://368379-saas-11-5-4bc79d.runbot17.odoo.com/

Website 1 vs website 2

**Comment by JKE-be** [comment]
@Yenthe666 

> This is a functional drama honestly.

It is not yet a full tested branch, don't worry ;)
drama... drama... we do what we can, sorry to add some bug between all the new features ;)

**Comment by sswapnesh** [comment]
Hello @JKE-be 
So Now they are not in sync with Company, (So its new feature to have different Social links for multiple Websites)

**Comment by sswapnesh** [comment]
> Yes, we just use it as default value but we don't want to synchronize it.

That's indeed good feature to support different links for Different website for same company

> you just need to remove all your links to don't display it ;)

Maybe thats somewhat Confusing for end user, We can add `_onchange_has_social_network` and make them blank.

**Comment by JKE-be** [comment]
Just need to replace the lambda from inverse function ;) 

Other solution is to make the checkbox in read only checked while there are 1 social configurated

I m not sure about the best solution ...

**Comment by sswapnesh** [comment]
> Other solution is to make the checkbox in read only checked while there are 1 social configured.

I would not Prefer this. Doing so will remove ease of Config. (Than even checkbox is useless.)

Rest is up to you and your team. ;)

**Comment by tarbib** [comment]
Hello @Yenthe666

On Odoo 12.0 community I can save the links to social media in website settings but it will not display icons on the website.

Any ideas how to fix this? Is it related to this issue or should I open another one?

![tim 20181205124936](https://user-images.githubusercontent.com/2255433/49490785-7feabc00-f88c-11e8-81fd-ef9209bcf8ed.png)
![tim 20181205124951](https://user-images.githubusercontent.com/2255433/49490787-7feabc00-f88c-11e8-9846-ee050988d6ac.png)

Thanks
