### ISSUE TITLE
[7.0] resource_calendar: can't call get_hours_interval or _get_hours_interval from a browse record

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#2665]
I want to see how many working hours an employee "skips" while on vacation. Looking at the source code I've found `resource_calendar.get_hours_interval` which does exactly that: Given the `resource.calendar` (the working hours of the employee) and the start and end datetimes it will return how many working hours are there in that time range.

Unfortunately you can't call that method from a resource.calendar browse_record.
Assuming `calendar` is of type `browse_record(resource.calendar, 18)`:

``` pytb
    calendar.interval_hours_get(dt.datetime.now(), dt.datetime.now())
  File "/srv/openerp/7.0/server/openerp/osv/orm.py", line 377, in function_proxy
    return attr(self._cr, self._uid, [self._id], *args, **kwargs)
TypeError: interval_hours_get() got an unexpected keyword argument 'context'
```

And true enough the [`interval_hours_get` function](https://github.com/odoo/odoo/blob/7.0/addons/resource/resource.py#L205) does not accept the context parameter. There is the equivalent [`_interval_hours_get`](https://github.com/odoo/odoo/blob/7.0/addons/resource/resource.py#L220) that accepts it, but using that I get:

``` pytb
    calendar._interval_hours_get(dt.datetime.now(), dt.datetime.now())
  File "/srv/openerp/7.0/server/openerp/osv/orm.py", line 377, in function_proxy
    return attr(self._cr, self._uid, [self._id], *args, **kwargs)
  File "/srv/openerp/7.0/addons/resource/resource.py", line 262, in _interval_hours_get
    cr.execute("select dayofweek, hour_from,hour_to from resource_calendar_attendance where calendar_id=%s order by hour_from", (id,))
  File "/srv/openerp/7.0/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/openerp/7.0/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = integer[]
LINE 1: ...rom resource_calendar_attendance where calendar_id=ARRAY[18]...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

In order to make the function work, I have to call it indirectly:

``` py
self.pool['resource.calendar'].interval_hours_get(
    cr, uid, 18, dt.datetime.now(), dt.datetime.now()
)
```

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
