### ISSUE TITLE
ODOO SERVER ERROR

### ISSUE THREAD

**Issue by luchotxrres** [odoo/odoo#26678]
When i tried to create a task in a project...
HELP!
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
>     r = d[key]
>   File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
>     a = self.d[obj].me
> KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f9a16eb0620>, 'project.mt_task_new')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
>     return call_kw_model(method, model, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/sale_timesheet/models/project.py", line 76, in create
>     return super(ProjectTask, self).create(values)
>   File "/usr/lib/python3/dist-packages/odoo/addons/hr_timesheet/models/project.py", line 60, in create
>     task = super(Task, self.with_context(context)).create(vals)
>   File "/usr/lib/python3/dist-packages/odoo/addons/project/models/project.py", line 657, in create
>     task = super(Task, self.with_context(context)).create(vals)
>   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 259, in create
>     track_thread.message_track(tracked_fields, initial_values)
>   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 503, in message_track
>     subtype_rec = self.env.ref(subtype_xmlid)  # TDE FIXME check for raise if not found
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in ref
>     return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1339, in xmlid_to_object
>     t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1323, in xmlid_to_res_model_res_id
>     return self.xmlid_lookup(xmlid)[1:3]
>   File "<decorator-gen-21>", line 2, in xmlid_lookup
>   File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1312, in xmlid_lookup
>     raise ValueError('External ID not found in the system: %s' % xmlid)
> ValueError: External ID not found in the system: project.mt_task_new
>

**Comment by sswapnesh** [comment]
Hello @luchotxrres 
That is because of message subtype (`Task Opened `with xml_id `mt_task_new`) is not available in your database.
You can check this from `Settings/Technical/Email/Subtypes`

**Comment by pedrobaeza** [comment]
Performing an update over project module should fix it.

Closing as no real issue.
