### ISSUE TITLE
[8][9][10][BUG] No negative counter part created during transfer.

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#26679]
Impacted versions:
8, 9, 10, maybe more

Current behavior:
When transfering a product (inside a picking) with a different lot than the reserved one, if the lot is not present in the specified location, Odoo will move the product without creating the negative counter part.

Expected behavior:
When transfering a product (inside a picking) with a different lot than the reserved one, if the lot is not present in the specified location, Odoo should create a negative counter part.

Steps to reproduce:
In version 10 : 
With demo data : 
1) Change wh/stock location type from internal to view. Indeed, in a complex environment, we have a lot of internal sublocation, but wh/stock is not a real location, it is just used to create the hierarchy.
2) Choose a stockable product with no stock (like wood for example). Configure it so we can work with lots (tracking : by lots)
3) Create 2 different lot for this product. LOT 1 and LOT2.
4) Update the qty on hand, add 1.0 product with LOT 1 in the location wh/stock/Shelf 1
5) Update the qty on hand, add 1.0 product with LOT 2 in the location wh/stock/Shelf 2
6) Create a delivery order containing one stock move, with the product wood (or the one you have chosen) with a quantity of 1.
7) Mark it as todo
8) Reserve it. It should create an operation, with source location : Shelf1. (as FIFO is set by default and you first update the qty on hand in shelf 1)
9) Indicate which lot you are about to transfer. By default, Odoo will propose the LOT 1, which is the one reserved. But, you are actually transfering the LOT 2 (say there is a problem in your informatic stock). So in the Lot/Serial Number detail wizard, choose the LOT 2 and put the field Done at 1.0 and save.
10) Validate the delivery Order
11) Check the stock of your product. In the sublocation Shelf 1, you should have -1 LOT2 and +1 LOT 1.
Instead, you just have +1 LOT1. Meaning Odoo did transfer the LOT2 in customer location, like it should have, but did not create the counter part. So this create a unconsistency between the stock moves and the stock quant.

This is a very serious bug, present at least in version 8, 9, 10, as, for a simple lot error, you whole stock level become wrong and inconsistent with the stock moves of the database.

The reason is simple (and it seems quite simple to solve), here : 
https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_quant.py#L249
Odoo check if the stock move source location is internal, but in our  case it is not, it is the type view. Odoo should check the force_location_from if exists, else check the move source location.

@rco-odoo @odony 
Please can you check this ASAP?

**Comment by pedrobaeza** [comment]
Please don't ping people randomly if you don't know correct people to do it.

The problem as you say is to put the source location as type view, as this is intended by design, but I let @jco-odoo the last word about this.

**Comment by florian-dacosta** [comment]
Sorry for the wrong pings.

Yes the problem is the source location view type, but, it is the only logic type for the location, as it is a virtual location where products should never enter...

In a complex tree of locations, with hundreds or thousands of locations per warehouse, it seems logical that only the last level is marked as internal, and the rest is only used to create the hierarchy, so view type. 
 Else we can not be sure no products will go there by mistake, and if it is the case, it will be lost in a big warehouse!


I doubt this behavior was intended.
Or maybe the view type locations should not even be configurable in pull rules, if it leads to bug this important.
Well, let's see what jco odoo says!
I am interested by other opinions on the use of view type on location.

**Comment by jco-odoo** [comment]
The negative counterpart is only done with internal locations.  You should not change WH/Stock to view as we still needed to know it was internal (location zones should have the appropriate type).  I know it is not ideal, as you might want to avoid to put stock in the  "non-leaf" locations.

**Comment by alexis-via** [comment]
FYI, the "bug" scenario described by Florian in this bug report doesn't happen in v12. Does it mean we are now allowed to set WH/Stock as "view" location (in order to force users to select sub-locations to store products) ?
Tip: another solution would be to use the OCA module stock_warehouse_lockdown https://github.com/OCA/stock-logistics-warehouse/tree/12.0/stock_location_lockdown
