### ISSUE TITLE
Uncaught SecurityError: Blocked a frame with origin "http://localhost" from accessing a cross-origin 

### ISSUE THREAD

**Issue by SalahAdDin** [odoo/odoo#26672]
Impacted versions:
`Odoo 11.0-20180827 (Community Edition)`

Steps to reproduce:
1. Go to work order section from a MO.
2. Run, pause, etc., there.

Current behavior:
```
Error:
Uncaught SecurityError: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.

http://localhost/mrp/static/src/js/mrp.js:66
Traceback:
Error: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost/mrp/static/src/js/mrp.js:66:67)
    at HTMLIFrameElement.dispatch (http://localhost/web/static/lib/jquery/jquery.js:4641:58)
    at HTMLIFrameElement.elemData.handle (http://localhost/web/static/lib/jquery/jquery.js:4309:63)
```

Expected behavior:
No error messages.

Video/Screenshot link (optional):
![deepin-screen-recorder_select area_20180829170855](https://user-images.githubusercontent.com/5034215/44793158-4d0a9b00-abae-11e8-9e23-afcfaf7fb15f.gif)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the builds in runbot doesnt' suffer that problem (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, the proxy configuration and the proxy_mode option in config.

**Comment by Yenthe666** [comment]
@pedrobaeza I actually think it is a duplicate of https://github.com/odoo/odoo/issues/24112 - but in either cases a close is fine as the other one is open

**Comment by SalahAdDin** [comment]
@Yenthe666 well, it is a local setup.
