### ISSUE TITLE
Out application when choose date in leave request

### ISSUE THREAD

**Issue by ThanhICSC** [odoo/odoo#26681]
Impacted versions:
v10.0 enterprise
v11.0 enterprise

Steps to reproduce:
Go to app on IOS or Android
Go to Leave / Leave Request
Create new request
Chooose type
Chooose duration

Current behavior:
Aplication is out
Expected behavior:
Chooose normal
Video/Screenshot link (optional):

![5688ef01-0a9a-487d-b2ac-f83e6e02038a](https://user-images.githubusercontent.com/32119643/44832974-c231ab00-ac56-11e8-974c-30d3e81a0640.jpg)

**Comment by ThanhICSC** [comment]
Hi pedrobaeza,

Yes, the application crashes. So what I will do if I want we fix it ?

**Comment by pedrobaeza** [comment]
You should issue a ticket in https://odoo.com/help with your OPW enterprise contract.

**Comment by ThanhICSC** [comment]
Thanh pedrobaeza,

I got it
