### ISSUE TITLE
[V11][V10] l10n_in_hr_payroll advice creation issue

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#26690]
Impacted versions: v10 & v11

Steps to reproduce: Install l10n_in_hr_payroll module and configure bank on a partner of the company.  Now create Paylip batch close it. Now try to create Advice for batch.

Current behavior: Now allow to create Payslip batch advice.

Expected behavior: It should not give error.

Video/Screenshot link (optional):

![ad odoo 1](https://user-images.githubusercontent.com/7599790/44852311-87dd0380-ac80-11e8-9d1c-79db21c9cce7.png)

**Comment by pedrobaeza** [comment]
As there's already a PR for fixing this, I close this issue for cleaning up the tracker.
