### ISSUE TITLE
[USABILITY] place the cursor in the search box when opening a list view

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#26699]
Impacted versions: tested on 10 and 11 CE and EE

Steps to reproduce: Open any list view

Current behavior: The cursor is not in the search box, the user must click on it to start searching

Expected behavior: As in 8.0 when you open a list view the cursor should be in the search box, to save one click on the most common operation which is to start searching for something

**Comment by sbidoul** [comment]
cc/ @chrisdec

**Comment by sswapnesh** [comment]
Hello @sbidoul 
Seems working fine on[ Runbot v11 CE](http://367887-11-0-487703.runbot17.odoo.com)
![peek 2018-08-30 21-55](https://user-images.githubusercontent.com/16624719/44865287-9555b600-ac9f-11e8-9f74-cbd92195328c.gif)

**Comment by sbidoul** [comment]
It seems to depend on different factors.

I can reproduce it consistently with, for instance:
- Firefox on Linux
- runbot Odoo 10 Enterprise
- Going to the Customer Invoices menu

With Chrome it works better.

**Comment by sswapnesh** [comment]
Works well for me in v10 CE/EE on [Runbot](http://367654-10-0-bb3aec.runbot11.odoo.com/web#min=1&limit=80&view_type=list&model=account.invoice&action=387&menu_id=262)
I am on Google Chrome (Version 68.0.3440.106) and Firefox Quantum (61.0.1)

**Comment by sbidoul** [comment]
Hm, the problem is real. I can reproduce (here is the video) and it's been reported to us by a customer migrating from 8.

![search_cursor](https://user-images.githubusercontent.com/692075/44870131-9aab0480-ac8f-11e8-905a-6a223da7906a.gif)

**Comment by sswapnesh** [comment]
Ah, I see. You are going to Invoices from Dashboard while I was trying from Menu.

**Comment by sbidoul** [comment]
Notice it happens when you go from kanban to list view too.

**Comment by Yenthe666** [comment]
@ged-odoo something for your team, can you check please?

**Comment by pedrobaeza** [comment]
Is this still happening in recent versions?

**Comment by intero-chz** [comment]
I've tested it right now on V13 EE and CE with Chromium 81, looks good to me :-)

**Comment by pedrobaeza** [comment]
OK, the let's close it as solved in latest versions :)

**Comment by intero-chz** [comment]
@pedrobaeza but it was issued for 10 and 11.

**Comment by Yenthe666** [comment]
@intero-chz not all improvements or changes or done against the oldest version. 10 is no longer supported, 11 is EOL so nothing to do there.
