### ISSUE TITLE
Can't select a module and export translations for specifics terms via Odoo interface

### ISSUE THREAD

**Issue by aelmizeb** [odoo/odoo#26716]
Impacted versions: 10.0

Steps to reproduce: 

Create a new term to translate in Settings/Translations/Translated terms.
There isn't a column in Odoo interface that let you choose the module concerning the term you've just translated.  

Consequences: 

The term you have translated has no module indicated in the database in which you made the translation. As a consequence, you can't export the translation in a .po/.csv/.tgz file because there is no module that contains your translation to choose.

Conclusion: 

You can't create a new translation for a specific module in this version of Odoo for now, via Odoo interface.

**Comment by mart-e** [comment]
Hello,

> You can't create a new translation for a specific module in this version of Odoo for now, via Odoo interface.

You are right (you don't have the res_id column either) but it is actually not intended this way.
We work with .po file, not directly from the interface.
You can use the "Import Translation" wizard to do import a custom po file.

However, when you create a new record with a translatable field, you don't need to create a translation manually, you can use the translation flag (blue planet) directly on the field to generate the missing translations.

I hope it helps
