### ISSUE TITLE
module purchase, method _get_price_unit() and _get_stock_move_price_unit() is duplicate

### ISSUE THREAD

**Issue by xfx-oscg** [odoo/odoo#26728]
Impacted versions:
Odoo Community 11.0
Steps to reproduce:

Current behavior:
File https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/stock.py   method def _get_price_unit(self):  can be removed.

Since:
File https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/purchase.py  method def _prepare_stock_moves(self, picking):   and def _get_stock_move_price_unit(self):
have set price_unit of stock.move,

And File https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py
def _get_price_unit(self):
    return self.price_unit or self.product_id.standard_price

will get correct price_unit of stock.move , 

Expected behavior:
Remove method def _get_price_unit(self): 
in file https://github.com/odoo/odoo/blob/11.0/addons/purchase/models/stock.py

Video/Screenshot link (optional):

**Comment by xfx-oscg** [comment]
When I made a module to add discount on purchase order line, I found _get_price_unit( ) in purchase module is a duplicate.

**Comment by gdgellatly** [comment]
@xfx-oscg they are different and serve different purposes, even though they may look the same here.

One is the price for the move, the other for the quant.  If you read something like IAS 12 - Accounting for Inventories - you can see situations where these methods need to be overridden differently.

**Comment by pedrobaeza** [comment]
As said by @gdgellatly, both can have different overridings, so they should stay both, so closing this. Any way, thanks for noticing.
