### ISSUE TITLE
[Odoo10] [beta] ; Accounting --> Sales --> customer invoice. When the user is bookkeeping, there is no entry for payment.

### ISSUE THREAD

**Issue by shaochanglei** [odoo/odoo#26729]
[Odoo10] [beta] Accounting --> Sales --> customer invoice. When the user is bookkeeping, there is no entry for payment.
![image](https://user-images.githubusercontent.com/25891205/45195888-49e96c00-b28c-11e8-9353-590ea0dd188e.png)

**Comment by pedrobaeza** [comment]
We need more information for deducing the problem: detailed steps to reproduce the problem, and you should try on runbot for avoiding specific problems with your deployments or custom modules: https://runbot.odoo.com

**Comment by shaochanglei** [comment]
odoo 10 ,   Accounting --> Sales -->  customer invoice.   When the user is bookkeeping, there is no entry for payment.

**Comment by shaochanglei** [comment]
I have test the issue again. if I have back to the database 2 months ago, It's ok. but back to database yesterday, it's wrong;

**Comment by mga-odoo** [comment]
It happen only in case when you have total on the invoice is 0
https://drive.google.com/file/d/1Z7RS7SJIx6bmxVzVB7IXeLkc3LGKnapv/view

**Comment by shaochanglei** [comment]
Please this video. not only this case:

**Comment by shaochanglei** [comment]
I have test  internal_type  is  'other'.  could you tell me why?

**Comment by shaochanglei** [comment]
Could you tell me when internal_type will be change?  The correct value is payable not other ?

**Comment by mga-odoo** [comment]
Can you please make the video with english screen, it will be easy for us to understand the scenario, also can you verify that there is no custom module installed.

**Comment by shaochanglei** [comment]
Topnotch!   Yes, you are right.  thank you very much.  


-
