### ISSUE TITLE
[11.0C], stand alone vendor bill, supplier reference disappear after add a product.

### ISSUE THREAD

**Issue by fanha99** [odoo/odoo#26734]
Impacted versions: 11.0C
after commit https://github.com/odoo/odoo/commit/052a5702c500a745fa94d13244eeaf14baccecb8

Steps to reproduce:
- create a vendor bill.  
- type something in the supplier reference
- add a product (invoice line)

Current behavior:
- supplier reference become blank.

Expected behavior:
- supplier reference must be remain, unchanged. 

Video/Screenshot link (optional):

**Comment by fanha99** [comment]
Some times, after select the relative PO, user make some note to the supplier reference, and than add or remove some invoice lines. the supplier reference is revert back to the PO ref also.

**Comment by gdgellatly** [comment]
@pedrobaeza @nim-odoo I kind of agree with this bug report.  The commit is really really annoying in practical use.

90%+ of purchase orders in the real world do not have a supplier reference on them.  Moreover, not all supplier invoices have purchase orders.  As such you typically enter the supplier reference when you get the supplier invoice, on the invoice.

The general workflow that most AP people I know follow is date, number, check total.  In this case if check total is wrong and they amend the lines to be correct, they lose the information they entered.

**Comment by pedrobaeza** [comment]
OK, I see that reference is changed also. I thought it was only origin.

I reopen this and recall @nim-odoo, who was the original author of this, to see if we can constraint a bit this not acting over full invoice line change (only on addition maybe), or not changing reference.

**Comment by nim-odoo** [comment]
I added back the `if purchase_ids`, so when manually encoding a vendor bill, you won't get this problem anymore. Anyway, it's quite difficult to satisfy everybody when it comes to automation. I think the actual solution is a good compromise: if you generate an invoice from a PO, you keep the vendor reference. If not, you keep the reference you added manually.

**Comment by pedrobaeza** [comment]
Thanks for the fast-reaction, Nicolas. Yeah, I agree this is a good balance.

**Comment by nim-odoo** [comment]
@gdgellatly yep, nice addition for this specific case. I will add it
