### ISSUE TITLE
Allow to create a default function that uses the create values

### ISSUE THREAD

**Issue by etobella** [odoo/odoo#26749]
Impacted versions:
[11.0]

Steps to reproduce:
When you create a record, it could be interesting to use a default value computed with the current values.

Current behavior:
The default is computed using context or environment parameters.

Expected behavior:
Define a function that can use the create values. For example::

        from odoo import api, fields, models

        class ResPartner(models.Model):
            _inherit = 'res.partner'

            ref = fields.Char(dependant_default='default_ref')

            def default_ref(self, vals):
                # Return the exepcted result from your vals
                return vals.get('name', '').upper()

Video/Screenshot link (optional):
You can check the module that I created on OCA/server-tools#1350.

**Comment by jbeficent** [comment]
@rco-odoo @xmo-odoo Would you find interesting to add this feature to the framework?

**Comment by gdgellatly** [comment]
I would probably spell it dependent.

**Comment by etobella** [comment]
Well, I don't see the circular, problem, The dependent function should use the fixed default values and the sent values, not the other dependent_default values. At least, It is programed these way on my module. If you are trying to do something like this, you should use the following::

        def create(self, vals):
            # Check here your multidependent code
            return super().create(vals)
Actually, when we have to add some computed code on the create, we must do something like this. On this issue, I am proposing a way to simplify the code for the most usual case.

**Comment by etobella** [comment]
It is being solved by  #31059

**Comment by pedrobaeza** [comment]
As there's a PR about this, I'm closing the issue. Let's continue on the PR.
