### ISSUE TITLE
No module named odoo.report error in odoo 11

### ISSUE THREAD

**Issue by Rathnakreeswaran** [odoo/odoo#26743]
Impacted versions:
11.0
Steps to reproduce:

Current behavior:
from odoo.report import report_sxw
Expected behavior:
How to solve this???
Video/Screenshot link (optional):

**Comment by bhanukiran6688** [comment]
@Rathnakreeswaran,
Report module has been merged with web module in odoo11, and also this your custom code please ask your queries in odoo forum.

**Comment by Rathnakreeswaran** [comment]
thanks @bhanukiran6688
