### ISSUE TITLE
Problem with Employee access rights / Menubar not shown

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#2675]
I encounter some issues with the employee access right (in version 8).
When i create a user and remove the access right employee. When i log into Odoo with this user, on my local database, i have an empty page without menu bar. (If i do it on runbot, i have an internal server error)

This is due to a "groups" attribute in the template "web.webclient_bootstrap". In my case, i really don't want my user to have access to what an employee have access so i'm a little bit stucked.

My second remark concerning the Employee group is that, if i want a freelance salesman to access my Odoo instance, I can't give him the access right only on the sales but he has access to my list of employees because nearly every group implieds the Employee group and the salesman group too. I think these 2 points should be fixed.

Thank you.

**Comment by seyed-mohammad-motahar** [comment]
This doesn't seem to be fixed yet. Another simple way to reproduce it is to duplicate employee group and assign a user to that group. He can't really login and see the menu bar

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
