### ISSUE TITLE
Pasting a URL link in the rich text editor draws a floating square

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#26769]
### Impacted versions:
11.0

### Steps to reproduce:

1. Using Firefox, copy a "permalink" to some code from GitHub (this step is important to reproduce it)
2. Go to Project > Search > Task and edit one task (or go to any form with a rich text editor)
3. Paste the URL you just copied

### Current behavior:

The URL pasted is **not** visible on the text field, and a mini-square is opened at the top left corner of the UI.

### Expected behavior:

The URL must be pasted in the field as normal text and be possible to edit it, and the squares not be shown at all.

### Example:

![seleccion_096](https://user-images.githubusercontent.com/442938/45037683-89664d00-b02d-11e8-822c-235e23f83d93.png)

![seleccion_094](https://user-images.githubusercontent.com/442938/45037081-27f1ae80-b02c-11e8-8251-196337ce60c9.png)

**Comment by mart-e** [comment]
Hi,

This is quite strange, the "copy permalink" option did not had this behaviour on my side.
```shell
$ xclip -selection clipboard -o
https://github.com/odoo/odoo/blob/56b6818e61ef91e01fa35cd68cb70fb14660d7fc/addons/sale/views/sale_views.xml#L41⏎ 
```

Could you detail which browser/OS you are using? (looks like firefox) Try with a fresh profile with no extension or another browser to see if the code does not come from there.

Moreover, even if I copy the HTML code you gave, I do not have the bug

![screenshot_2018-09-05 improve clean code and functionality - odoo](https://user-images.githubusercontent.com/564822/45076394-6352b280-b0ea-11e8-9056-118f5bc3164e.png)

**Comment by ebirbe** [comment]
Hello @mart-e 

> This is quite strange, the "copy permalink" option did not had this behaviour on my side.

I noticed that the `text/html` content is copied to the clipboard if you use the "permalink" option in Firefox. Once copied using Firefox, no matter what browser you use to paste it, the Odoo's rich editor will show the floating square.

> $ xclip -selection clipboard -o

If you use that `xclip` command, you will not see the HTML content, but I used an application called `CopyQ` and when I asked for the details of the copied content, this is what I get:

![contenido del elemento copyq_105](https://user-images.githubusercontent.com/442938/45224518-26242700-b288-11e8-97bb-628687c287c8.png)
![contenido del elemento copyq_107](https://user-images.githubusercontent.com/442938/45224524-29b7ae00-b288-11e8-8bf3-707bbf567981.png)

So, my conclusion here is that the rich text editor in Odoo is taking the HTML part (and that's OK, this is the expected behavior for a WYSIWYG editor), the problem start when that text/html content has a style like the fisrt image:

```
position: fixed; top: 5px;"
```

It causes the floating square at the top of Odoo UI.

Therefore, I tried to paste the same content using the rich text editor TinyMCE demo page, and noticed they clean successfully the style attribute.

![seleccion_110](https://user-images.githubusercontent.com/442938/45225985-c92a7000-b28b-11e8-9af2-37acf8f2c9a6.png)
![seleccion_109](https://user-images.githubusercontent.com/442938/45225988-ccbdf700-b28b-11e8-94c6-5387ebe6e497.png)

And then I tried it on Odoo (using Runbot):

**Firefox 61.0.1:**
![seleccion_111](https://user-images.githubusercontent.com/442938/45226683-8a95b500-b28d-11e8-9610-e2933f093f08.png)


**Chrome 68.0.3440.106 (Build oficial):**
![seleccion_113](https://user-images.githubusercontent.com/442938/45226725-ad27ce00-b28d-11e8-9575-6ceaa6beb6f6.png)

**Comment by ebirbe** [comment]
More about this:

>> $ xclip -selection clipboard -o
> 
> If you use that xclip command, you will not see the HTML content, but I used an application called CopyQ

You could use it like this:

```
$ xclip -selection clipboard -o -t text/html
<pre style="width: 1px; height: 1px; position: fixed; top: 5px;">https://github.com/odoo/odoo/blob/d7f5a1b25e4c14af49cccd65ad3b6e0553a77faa/addons/sale_stock/models/stock.py#L7-L10</pre>
```


Source: https://stackoverflow.com/a/16960316/1457233

**Comment by mart-e** [comment]
Thank you for the details but I am still unable to get the output in HTML. I have tried with both chrome and firefox on two different computers but got plain text with the "copy permalink" option (checked with xclip and CopyQ).
However, if I try putting the HTML content you gave me (e.g. copy the result from https://codepen.io/mart-e/pen/jvZOQg ) I do get the same problem as you.

The editor we are using is [summernote](https://github.com/summernote/summernote). You can try a demo at https://summernote.org/ and you will see you will get the same result.

@ged-odoo @Gorash what do you think? Should this be fixed upstream or should this be part of the sanitization server side when saving?
