### ISSUE TITLE
Odoo Widget Handle 

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#26770]
Impacted versions:
Odoo - 11
Steps to reproduce:
Sequence field added  and default value set to 1 in one2many fields table.
widget="handel"  and  _order = "sequence asc"  added

Current behavior:
It showing all value 1
After drag and drop showing in reverse order sequence 2, 1 (example two row)
Expected behavior:
Please let me know if any possible without drag and drop show sequence 1,2,3 and after drag and drop
sequence order shows in order (1,2,3 and value change).

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I'm afraid that's not possible. That's how widget works. The behavior has been improved for v12 for handling "holes", but the sequence will remain the same in your case.

Closing as no possible improvement.
