### ISSUE TITLE
8.0: cannot modify a many2many field in a yaml test

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#2678]
This block has no effect:

``` yaml
!record {model: product.template, id: product.product_product_7_product_template}:
  route_ids:
    - purchase.route_warehouse0_buy
```

The equivalent python block works fine:

``` yaml
!python {model: product.template}: |
  model.write(cr, uid, ref('product.product_product_7_product_template'), {
    'route_ids': [
        (4, ref('purchase.route_warehouse0_buy')),
    ]
  })
```

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by lepistone** [comment]
@Yenthe666 of course! Thanks for your cleanup efforts!

**Comment by Yenthe666** [comment]
@lepistone you're welcome! I hope this will 'push' the Odoo people to start doing better starting from Odoo 11.0 and to clean up the old & unmanaged bug reports. Let us see what this gives. 😉
