### ISSUE TITLE
[8.0] Suppliers for product variants don't work 

### ISSUE THREAD

**Issue by Christian-Death** [odoo/odoo#2679]
When i set a supplier for a product variant all other variants have the same supplier.
And When i change this on a other, variant, change all other, too.
When i now delete the supplier and will sav, i become this error.
Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: product_tmpl_id - product.tmpl.id]

**Comment by pjmcdermott** [comment]
The UI is not consistent: In the product variant view, the EAN13 field **is** different per variant. But in the procurement tab next door it seems that the supplier information is entered for the so-called product template. It is not clear that one is editing different objects.

And the implementation (and the language) is disconnected from the real world. For most companies selling things the lowest level of resolution is the stock-keeping unit or SKU. Units of the same SKU are indistinguishable from one another, and are interchangeable from the customer point of view. Units of different SKUs have different attributes, and are not interchangeable from the customer point of view. For many people, in day to day lanuguage, this is a "product", although in Odoo this is what we are calling a "product variant". But most importantly at the level of the SKU each SKU has a **set** of identifiers which mark this SKU as different from others, each used by a *different entity*.

Typically, there are:
* Company SKU code (in Odoo called "Internal Reference"), which is the company's identifier.
* Supplier or Distributor SKU code (not available in Odoo as the "Supplier Product Identifier" is an attribute of the "Product Template").
* Manufacturer part number (not directly handled by Odoo).
* EAN/UPC/ISBN - globally standardised unique product identifiers (confusingly able to set at both the "Product Template" level and the "Product Variant" level).
* An potentially unlimited number of product attributes.
* Also at this level, the suppliers, supplier price and sales price may also vary.

Odoo does a poor job of supporting what is for many users is essential information. It then compounds this lack of support with attributes at the wrong level, and confusing terminology (e.g. the view shown when you click "Product" is actually a view for a "Product Template", with some additional fields which probably shouldn't be there is it really is a "Product Template").

When I struggle with this I often wonder how Odoo go so far and so big without these fundamental data model issues being sorted out. And my conclusion so far it to forget about "Product Variants" and just enter product information at the "Product Template" level. However, this has implications if you use the website functionality, and adds to the amount of editing required.

For me the ideal data model would be (first pass):

"Product" or Product Group Level:
* Brand
* Manufacturer
* Model - This is the name that a manufacturer might give to a set of products with similar functionality but differing minor attributes (e.g. "iPhone 6")
* An arbitrary number of product attributes which *may* include sales price, supplier, supplier price, weight, dimensions, images and other product attributes

Product Variant or SKU level:
* Company SKU Code (SKU)
* Distributor/Supplier SKU Code (DSKU)
* Manufacturer Part Number (MPN)
* Global Identifier: EAN/UPC/ISBN
* An arbitary number of product variant attributes, which *may* include sales price, supplier, supplier price, weight, dimensions, images and other product attributes
* Remaining product attributes inherited from the Product Group

**Comment by maljac** [comment]
+1

**Comment by maljac** [comment]
A short statement why this ticket is closed would be usefull, since this requirement is a real-world requirement of many customers.

**Comment by jco-odoo** [comment]
The product suppliers are implemented on the product template.  Most fields
are, as we consider variants to be as much the same as possible.  Possibly
later, we will think of another object to solve this as indicated, but not
for v8.

**Comment by pjmcdermott** [comment]
The issue raised in this issue report is that the model Odoo assumes, as summarised above "we consider variants to be as much the same as possible" is fundamentally flawed, in that it is disconnected from the real world. I fail to understand why the issue has now been closed: the disconnect between the Odoo model and the real world still exists, and is very much an issue for users and potential users.

**Comment by mhapponen** [comment]
I'm also wondering why the Product Variants should not be supported in Purchasing. Purchase price and stock valuation for example do not work with current setup. If you have two variants of the same product which have different purchase price they are not valued correctly in the stock even if you're able to maintain purchase prices correctly via purchase pricelists. The valuation is always taking place in the product template (the mother product) level which is not correct.

Would be nice to know whether v9 brings some solution to this as this is a big gap in the product variant concept.

**Comment by jkevin530** [comment]
pjmcdermott has done a great job of summarizing the issue and the need for this to be corrected.
Supplier Code (SKU) has to get related to the SKU in product.prodcut NOT product.template.

This issue should get reopened.

**Comment by maljac** [comment]
and again +1

**Comment by jholze** [comment]
:+1:

**Comment by jkevin530** [comment]
I just noticed that the same issue is identified in:
https://github.com/odoo/odoo/issues/296

**Comment by AndreiGo** [comment]
And also some code implemented for v8: https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/tree/8.0/product_supplierinfo_variant.

The SKU per item/variant is basic inventory management stuff. After so many companies use Odoo, they will probably not update the system to the way it should be. Described above by pjmcdermott.
