### ISSUE TITLE
[11.0, +] website: Script injected in DOM: window.onerror empty params

### ISSUE THREAD

**Issue by HYROPES** [odoo/odoo#26812]
Impacted versions:
V11
This commit https://github.com/odoo/odoo/commit/4bd8e3e2ed48eb05b9e155826fd47753a85b5731  @rdeodoo 's work shall fix the error code if google API returns an error when configure wrongly in odoo Google Analytics in Dashboard.
**instead of showing** Current behavior:

![20180814 screen shot_error code](https://user-images.githubusercontent.com/34730355/45136811-3507cc80-b1e9-11e8-9402-633efaa84b5e.JPG)

**it shall be showing** Expected behavior:

> Google Analytics initialization failed. Maybe this domain is not whitelisted in your Google Analytics project for this client ID.

However, in the V11 latest runbot build, If user forgot to put the domain into google API "while list domain" , Odoo still give the old error code.

**Steps to reproduce:**
```
to recreate the issue , we can using the dummy google ID to test in V11 runbot:
tracking ID:UA-00000000-1
Client ID:000000000000-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
```

The website tutorial need to reflect the " while list domain" , I had suggest the changes in there.
https://github.com/odoo/documentation-user/issues/292

More about this issue can be found https://github.com/odoo/odoo/pull/21032

Impacted versions:
V11

**Comment by HYROPES** [comment]
@rdeodoo Yes, the test was done in Firefox. Thanks for your time.

**Comment by HYROPES** [comment]
Big thank-you for the new fix. I see the latest Runbot Dev version fixed the issue perfectly.

**Comment by rdeodoo** [comment]
You are welcome, thanks for reporting the issue and helping us making Odoo a great product ;-)!
