### ISSUE TITLE
[11.0] Website: Singleton error when we trying to unlink multiple pages.

### ISSUE THREAD

**Issue by Dangar-Serpentcs** [odoo/odoo#26823]
Impacted versions: 11.0

Steps to reproduce:

1 > Go to Website > Configuration > Pages tree view.
2 > Select more than one record of pages in list view.
3 > Click on Delete.

Current behavior:
Getting singleton error.
![page](https://user-images.githubusercontent.com/38550879/45153928-5e2d5a80-b1f3-11e8-843a-22bd3301b364.png)

Expected behavior:
Should allow to delete multiple pages.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This one is easy to fix: #26825

**Comment by pedrobaeza** [comment]
#26825 merged
