### ISSUE TITLE
Not able to use mobile app when having google authentication enabled

### ISSUE THREAD

**Issue by Binformed** [odoo/odoo#26832]
Impacted versions: v11

Steps to reproduce: enable google authentication in Odoo

Current behavior: not able to authenticate when logging into the mobile app. Even when you have the google app on your mobile

Expected behavior: mobile app should be able to use the authentication of the google app

Video/Screenshot link (optional):

**Comment by mga-odoo** [comment]
No only Google but third party authentication with any platform such as Facebook or LinkedIn is currently not implemented in the current mobile application.

**Comment by nhomar** [comment]
You should set a password and then login with password (even if the login with google is set by normal web interface).

It is not Ideal but it is the way is working now.
