### ISSUE TITLE
[8] import - selections fields must show complete text

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2685]
currently the text in selection fields is cut off - the user must open each box to see what is selected - a no go .... all selections fields look identical
![survey_import](https://cloud.githubusercontent.com/assets/6248560/4394215/467218cc-441f-11e4-97ed-bd1087810c66.png)

**Comment by pedrobaeza** [comment]
Closing this as the import tool has received several visual refinements, although the combo-box has not change too much, but larger widths will force to have larger side scroll, which will be uncomfortable for other things. As the column title is used to match the field, that should be the technique used for checking the imported field.
