### ISSUE TITLE
[11] In sequence Next Number jump 2 number when new record created

### ISSUE THREAD

**Issue by pank37** [odoo/odoo#26859]
Impacted versions:
11.0
**Steps to reproduce**:
I created a sequence with fields Implementation=nogap, Sequence Size=5, Step=1
**Current behavior:**
It jump always 2 number. For example if I set Next Number=1 after this If I create new record, its generate 3 and set Next Number=4
**Expected behavior:**
new sequence must be 1,2,3,4,5.....
**Video/Screenshot link (optional):**
![screen shot 2018-09-08 at 2 40 53 am](https://user-images.githubusercontent.com/41303099/45243308-efdeba00-b310-11e8-9351-50286011d555.png)

**Comment by mga-odoo** [comment]
I think you should check the code that use the sequence to get the next number, it may possible it try to get the next number two times, during default get method and again in create method.

**Comment by pank37** [comment]
Thanks @mga-odoo 
Issue solved sequence was called two times
