### ISSUE TITLE
menuitem xml record does not load when action to invoke is a report action

### ISSUE THREAD

**Issue by jeroen-vet** [odoo/odoo#26860]
Impacted versions: 10.0 but probably all other versions as well

Steps to reproduce: 
1. Define a report in xml using report tag
2. Define a menu item using menuitem tag to call the action setting "action" attribute to xml id of report action

Current behavior:
The XML fails to load because of bug in odoo/odoo/tools/convert.py
this is snippet in `_tag_menuitem` method containing the bug:
```

            # determine the type of action
            action_type, action_id = self.model_id_get(a_action)
            action_type = action_type.split('.')[-1] # keep only type part
            values['action'] = "ir.actions.%s,%d" % (action_type, action_id)
```
values['action'] will as a result of the split contain 'ir.actions.xml' as model which does not exist and results in an error trying to load the xml. 

Expected behavior:

values['action'] contains 'ir.model.report.xml' as model
when for example adding the following line as a quick fix directly below above snippet:

`values['action']=values['action'].replace('ir.actions.xml','ir.actions.report.xml')`

the xml can load and the report can be printed as expected by invoking the menu item.

**Comment by dairondv1986** [comment]
Using that temporal solution solve my problem too. Thanks.

**Comment by Yenthe666** [comment]
Dear @jeroen-vet,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
