### ISSUE TITLE
Problems with Purchase Order Notification Email Field

### ISSUE THREAD

**Issue by cfalconss30** [odoo/odoo#26865]
Impacted versions:v11

Steps to reproduce: I just want to change the back purple image back color in the Purchase Order Notification Email , I went to Purchase Order Notification Email Field as a developer mode, but in the process something unknown happened and the purchase order notification email does not have the notification image anymore.

I attached my code and the preview render image.

Current behavior: No email image is visible

Expected behavior: email image visible

Video/Screensh

![captura de pantalla 2018-09-09 a la s 9 31 06 p m](https://user-images.githubusercontent.com/43123466/45272072-2afbfd00-b479-11e8-93f0-027bebaaa88f.png)
ot link (optional):

![captura de pantalla 2018-09-09 a la s 9 31 25 p m](https://user-images.githubusercontent.com/43123466/45272083-36e7bf00-b479-11e8-95c8-492b39abbe38.png)

**Comment by sswapnesh** [comment]
You have to Check odoo log for this 
or 
Try upgrading `purchase` module. (You have to paste Body manually here if template is set to `noupdate=1`)

**Comment by Yenthe666** [comment]
Yep, looks like an old template that is not updated (because of noupdate), please try to manually correct it.

**Comment by pedrobaeza** [comment]
Any way, it's due to a bad manipulation (trying to change the purple color), so it's not Odoo's fault, so closing.
