### ISSUE TITLE
[8] import - mark columns causing the error

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2686]
currently the columns which cause an error are described as lines, but it is hard to identify which column is meant
![survey_import](https://cloud.githubusercontent.com/assets/6248560/4394250/937a3262-441f-11e4-8919-7d852a3b6a34.png)

**Comment by Yenthe666** [comment]
Hey guys,

This behaviour was improved in V9 and up and also mentions the lines+fields now. No longer relevant.

Regards,
Yenthe
