### ISSUE TITLE
navigation is not visible after scrolling to the right end

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2687]
https://www.odoo.com/blog/odoo-news-5/post/odoo-8-release-notes-186#blog_content
says
The navigation bar (search, breadcrumb) and menu use fixed positioning. You don't need to scroll anymore to search or navigate.

this is not true for import 

![survey_import2](https://cloud.githubusercontent.com/assets/6248560/4394490/f745728c-4421-11e4-8d59-e692839e2530.png)

**Comment by Yenthe666** [comment]
Hi @ferdiga,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
