### ISSUE TITLE
[WISH] use JSON-LD instead of Microdata for schema.org structured data

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#26885]
Google recommends using JSON-LD for structured data whenever possible : 
https://developers.google.com/search/docs/guides/intro-structured-data
Various other Google dev docs says it is Google's preferred format for structured data. See for example :
https://codelabs.developers.google.com/codelabs/structured-data/index.html#2

What about using JSON-LD in Odoo ? it would keep structured datas while users install new themes and customize html.

**Comment by baba75** [comment]
+1
