### ISSUE TITLE
[10.0] Account asset : wrong depreciation calculations and wrong posting date 

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#26896]
Impacted versions: 10.0 (probably all other versions)

Steps to reproduce:
* Install account_asset
* create an asset like on the attached printscreen : Asset cost : 1000 ; Depreciation over 5 years - Linear - prorata calculation. Depprciation start : 15/03/2018 - (Assumption fy end: 31/12)
* Compute the depreciation board (button)

Current behavior:
Dates on depreciation lines are wrong : on the 13/03 instead of the 31/12.
Calculation of the 1st depreciation (when prorata checkbox is true) is wrongly calculated: 1095.89 instead of 1594.52

Expected behavior:
1 - Depreciation entries must be the last day of the month/fy. (Worst situation is at the end of fiscal year you miss part of the depreciation that should be posted ; so you are wrong on your P&L !)

2 - The 1st depreciation must be computed until the end of the fiscal year

Screenshot link (optional):

![asset module errors](https://user-images.githubusercontent.com/5735158/45345924-0488af80-b5a8-11e8-8c3d-8e94885f1184.png)

**Comment by kmlew** [comment]
Hello fclementic2c,

Was this ever resolved for you?

K
