### ISSUE TITLE
[10] fleet odometer create form

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#26890]
Impacted versions:
9, 10, 11

Steps to reproduce:
login to dashboard. Fleet -> Vehicles Odometer -> Create

Current behavior:
nothing happens. create form for odometer not showing up.
possible to add records through Vehicles -> select a Vehicle -> Odometer -> Create

Expected behavior:
Form should be visible.

**Comment by sswapnesh** [comment]
This works well in v11 as Form view is there on Action.
![98](https://user-images.githubusercontent.com/16624719/45637461-257d6300-bac8-11e8-8c12-cbbc3fc05be0.png)

In v10:
It is Editable Treeview so you need to Remove Default `Vehicle` filter and create new Records.
![assa](https://user-images.githubusercontent.com/16624719/45637545-59588880-bac8-11e8-8478-3f7038cd168d.png)


PS: May be It should not display Create Button when Editable list is Grouped By.
Cc: @pedrobaeza  What are your views on this ?

**Comment by sswapnesh** [comment]
I don't think this will be solved in v10. (Already Improved in Newer versions)

**Comment by Yenthe666** [comment]
Nope, that won't be changed in such an old stable version. As it works in V11/V12 I suggest closing.
