### ISSUE TITLE
Restore Error!!

### ISSUE THREAD

**Issue by manishbisht94** [odoo/odoo#26893]
Impacted versions: Version 11 or lower.

Steps to reproduce: Build the Odoo 11 from source. Try taking & restoring backup using xmlrpc.  

Current behaviour: Backing up is fine. But restoration gives error.

Expected behaviour: The backup should happen.

**Comment by Linekio** [comment]
What is you're postgresql version ? Is it the same version as the backup?

**Comment by pedrobaeza** [comment]
If you don't provide more information, like the error, this is going to be definitively hard to help you. Any way, this issue tracker is not for receiving help, but for notifying issues in the code. Although I doubt this is an Odoo problem itself, I give you the opportunity to explain where do you think it's the problem or show any kind of log for proving the bug.

**Comment by manishbisht94** [comment]
> If you don't provide more information, like the error, this is going to be definitively hard to help you. Any way, this issue tracker is not for receiving help, but for notifying issues in the code. Although I doubt this is an Odoo problem itself, I give you the opportunity before closing it to explain where do you think it's the problem or show any kind of log for proving the bug.

The same backup file works when db is restored via Browser. But via xmlrpc "restore" function gives error.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 117, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo/service/db.py", line 460, in dispatch
    return g[exp_method_name](*params)
  File "<decorator-gen-9>", line 2, in exp_restore
  File "/opt/odoo/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/service/db.py", line 248, in exp_restore
    restore_db(db_name, data_file.name, copy=copy)
  File "<decorator-gen-10>", line 2, in restore_db
  File "/opt/odoo/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/service/db.py", line 290, in restore_db
    if odoo.tools.exec_pg_command(pg_cmd, *pg_args):
  File "/opt/odoo/odoo/tools/misc.py", line 130, in exec_pg_command
    raise Exception('Postgres subprocess --> %s error --> %s name --> %s prog --> %s args --> %s' % (args2, rc,name, prog,args))
Exception: Postgres subprocess --> ('/usr/bin/pg_restore', '--dbname=TEST', '--no-owner', '/tmp/tmpw19co496') error --> 1 name --> pg_restore prog --> /usr/bin/pg_restore args --> ('--dbname=TEST', '--no-owner', '/tmp/tmpw19co496')
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


I'm using xmlrpc restore function.
##############################
sock.restore(master_password,new_db_name,backup_file_path)  #backup_file_path is the encrypted location of backup zip file.
##############################
As per my analysis of code, the restore function as mentioned in above logs doesn't receive the absolute file path of the backup file. Rather it receives the temporary file location used to store the absolute file path given via "restore" RPC function call. 
So, odoo tries to restore using that temporary location & ends with the error. 

I fixed it by making a little change in  odoo/service/db.py file.
Replaced "restore_db(db_name, data_file.name, copy=copy)" at line no 245
by "with open(data_file.name,"r") as tmpfile:restore_db(db_name, tmpfile.read(), copy=copy)"

And it worked correctly.

Please review it once & have a say.

**Comment by pedrobaeza** [comment]
Thanks for the extra information. If you have the patch, you can propose a PR.

**Comment by Elkasitu** [comment]
Can you please detail the steps to triggering your error? i.e. the python code you're using to call this method.

**Comment by manishbisht94** [comment]
Below is the snippet of how I am restoring backup. It works with changes mentioned above.


import os,time,base64
import xmlrpclib
sock  = xmlrpclib.ServerProxy("http://127.0.0.1:8069/xmlrpc/2/db")
filepath = os.getcwd()+"/db_dump.zip" #path is readable by Odoo user
filepath = base64.b64encode(filepath)
missing_padding = len(filepath)%4
if missing_padding == 1:
        filepath += 'A=='
elif missing_padding == 2:
        filepath += '=='
elif missing_padding == 3:
        filepath += '='
res = sock.restore("masterpassword","newdb",filepath)

**Comment by manishbisht94** [comment]
@Elkasitu  is there any update on this..

Thanks!!

**Comment by manishbisht94** [comment]
@Elkasitu  Please update!!

**Comment by Elkasitu** [comment]
I do not understand why you're base64-encoding the filepath; in any case the function expects a string for the path and you're passing binary gibberish

**Comment by manishbisht94** [comment]
Thanks for the update,

xmlrpc restore function call goes to `exp_restore` which decodes the given path. And then to `restore_db` with decoded path.  This why i encoding is there. The setup is working fine as i am able to restore production backups too.

**Comment by manishbisht94** [comment]
I do agree that `restore_db` function expects a string as its dump_file arg which should/is the absolute file path of backup. `restore_db` function works perfectly as this is called also when backup is restored via browser interface. But my concern is about `exp_restore(db_name, data, copy=False)` which further calls `restore_db` for restoration when xmlrpc is used instead of web interface.

`exp_restore` function breaks the input absolute file path(encoded) into chunks & decodes the chunks. Then it writes them to a temporary file, then it passes this temporary file path to `restore_db` function as the backup file path. Rather it should pass the content of temporary file to `restore_db`. Afterwards, the `restore_db` processes the temporary file as backup file & ends with error.

**Comment by Elkasitu** [comment]
See https://github.com/odoo/odoo/pull/26997#issuecomment-428470238
