### ISSUE TITLE
[v7] export - must order parent records before child records

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2690]
v7 export does not ensure, that parent-resources are exported before child-resources

makeing import in v8 impossible (.... not found)

in v8 - Example import messages
No matching record found for external id '**export**.mail_message_839' in field 'Parent Message' at row 2

**Comment by Yenthe666** [comment]
Hi @ferdiga ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
