### ISSUE TITLE
Iot has wrong domain

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#26919]
https://github.com/odoo/odoo/blob/e2819a234c9921004954bf6a14f83860afcc178b/addons/iot/models/iot.py#L45

shoule be ` ('type', '=', 'printer') `

**Comment by pedrobaeza** [comment]
@jco-odoo isn't better to rename the field to `device_type` for avoiding to overwrite the Python `type`?

**Comment by jco-odoo** [comment]
We wanted to clean and make the name shorter as it is already a device. Needs to be fixed somehow, thx.

**Comment by pedrobaeza** [comment]
Yeah, but overwriting a standard Python method name is not a good practice.

**Comment by berrysmith** [comment]
IoT’s potential is massive, but many businesses still are wrestling with how it can benefit their organization and how to move forward.
Fix 24/7 Any Brother Wireless Printer Errors, Printer in error state, [Brother Wireless Printer Setup](https://www.brotherprintersupportnumber.com/brother-printer-setup/), Driver or Software Installation or Un-installation & Upgrade issues by Expert Techies.
