### ISSUE TITLE
base_geolocalize doesn't work anymore with new google API usage conditions

### ISSUE THREAD

**Issue by ecino** [odoo/odoo#26924]
Impacted versions: 10.0, 11.0

Steps to reproduce: Go on a partner, click on the button "Geolocalize"

Current behavior: Doesn't update the geolocation

Expected behavior: Should update

When calling the google service here https://github.com/odoo/odoo/blob/11.0/addons/base_geolocalize/models/res_partner.py#L16, the answer from google is `Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account` and status is `OVER_QUERY_LIMIT`

Information can be found here : https://cloud.google.com/maps-platform/user-guide/account-changes/#no-plan

**Comment by pedrobaeza** [comment]
Do you know any alternative free service?

**Comment by pedrobaeza** [comment]
And does it have API?

@mart-e what do you think about this?

**Comment by ecino** [comment]
Yes it has API, explained here: https://wiki.openstreetmap.org/wiki/Nominatim

**Comment by pedrobaeza** [comment]
@ecino would you accept the challenge :wink: ?

**Comment by ecino** [comment]
Ok, I'll give it a try :)

**Comment by lmignon** [comment]
@ecino @pedrobaeza @mart-e an old PR has been provided odoo/odoo#7958 on Aug 7, 2015! (unfortunately never reviewed nor merged and now on a no more supported Odoo version)

**Comment by gdgellatly** [comment]
@mart-e this probably needs reimplementing for the new google maps platform.

I use gityopie/odoo-addons for my maps and places service with the new API and it works really well including updating geo locations from base_geolocalize.

**Comment by pedrobaeza** [comment]
Closing as merged in master the alternative provider + generic geolocalize provider system.
