### ISSUE TITLE
Not able to redirect old links which have naked domain name

### ISSUE THREAD

**Issue by aTibrewala** [odoo/odoo#26944]
Impacted versions: 11.0 ( Odoo SH)

We are switching from Wordpress based WooCommerce store to Odoo.sh. However, since odoo has setting just for CNAME record we are obligated to use the www part before our domain. Currently we are used to following a naked domain name with WP site and hence once we switch to odoo our existing links are getting broken and not being redirected.

We tried forwarding to https://yourdomain.odoo.com in the domain manager but it is too slow and is timing out.

Also we cannot rewrite the url to be the same as we did not find a solution for that, also, not many of the apps available on odoo marketplace are for odoo.sh and the ones we found are available for previous versions of odoo.

Steps to reproduce:

Try to redirect the following

source : https://yourdomain.com/product/pr-1
destination : https://www.yourdomain.com/shop/product/pr-1

Which will be input in the website redirect setting as follows

srce : /product/pr-1
destination : https://www.yourdomain.com/shop/product/pr-1

Current behavior:

This type of redirection does not work under odoo redirects. The redirection works only for 404 pages if and only if the both the source and destination have the same structure ( with or without www).

Expected behavior:

Redirection needs to take place product wise from https://yourdomain.com to https://www.yourdomain.com

Also is there a way to achieve this with a .htaccess file by uploading it to git? If so where and how.

Any help is highly appreciated. Thanks in advance!

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@dbo-odoo maybe you can answer this.

**Comment by dbo-odoo** [comment]
This is out of the context of Github issues from my PoV. This is a platform question for odoo.sh.
