### ISSUE TITLE
[11.0] [Discuss-app] Odoo Server Error when create a public channel

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#26946]
**Impacted versions:** 11.0

**Steps to reproduce:**
With Demo user, create a new public channel with field ```Who can follow the group's activities?``` -> ```Invited people only```

![skitch 37](https://user-images.githubusercontent.com/11341058/45450366-033dac80-b6a6-11e8-8e0f-4c057fd7f0f6.png)

 
And save it.

**Current behavior:**
 An Odoo Server Error is thrown

![skitch 38](https://user-images.githubusercontent.com/11341058/45450250-a5a96000-b6a5-11e8-9b30-a0107a009dbe.png)

**Expected behavior:**
The channel must be saved without error.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you haven't add yourself into the members.

Closing as no real issue.

**Comment by ysantiago** [comment]
@pedrobaeza but the user that is creating the channel must be automatically into the channel.

**Comment by pedrobaeza** [comment]
That doesn't happen last time I check. Can you re-check adding it?
