### ISSUE TITLE
breadcrumb not translated for field.Selection

### ISSUE THREAD

**Issue by mjrk** [odoo/odoo#26948]
Impacted versions:
11 and on

Steps to reproduce:

In your model, e.g. similar to SaleReport specify _rec_name = "state" - or any other fields.Selection that usually is translated properly - and navigate there.

Current behavior:

The breadcrump will show for example "draft", but it's not translated.

Expected behavior:

It should be translated

**Comment by mjrk** [comment]
For sale.order, you may override the name field:

```
class SaleOrder(models.Model):
    _inherit = 'sale.order'
    _name = 'sale.order'

    @api.one
    @api.depends('state')
    def set_name(self):
        self.name = self.state

    name = fields.Selection([
        ('draft', 'Quotation'),
        ('sent', 'Quotation Sent'),
        ('sale', 'Sales Order'),
        ('done', 'Done'),
        ('cancel', 'Cancelled'),
    ], default="draft", compute=set_name)
```
Then navigate to a sale.order and in the breadcrumbs I see "draft". 

This may also be related to the selection, however, the original problem appeared in a new model where I used a selection field for _rec_name. It would take some time to prepare/test an minimal example but I could do this on the weekend.

**Comment by pedrobaeza** [comment]
But that's the expected behavior: you are assigning the internal value (`draft`), not the label ('Quotation`). If you want the label, you will need to sophisticate your compute method using fields definition (`_fields` variable). Take also into account that this compute can't be stored and translatable at the same time, as you are able to store only one value in one language.

Closing as no real issue.

**Comment by mjrk** [comment]
Sorry, you ask an example and I gave you a quick one telling, a better example with _rec_name I can provide on the weekend... Thanks for reading and your patience!

I don't understand what you mean with _fields-variable, you have an example?

**Comment by pedrobaeza** [comment]
`env[<model>].fields[<field_name>]['selection']` (this is by memory). Any way, this kind of questions should be done on the forums, not here.
