### ISSUE TITLE
Stock valuation report grouped by location issue

### ISSUE THREAD

**Issue by mahmoudmsoliman** [odoo/odoo#26955]
Impacted versions: 11 Community and Enterprise Editions

Steps to reproduce:
Go to inventory --> Reports -->  Inventory valuation report 
Current behavior:
The generated report doesn't contain any ability to group by location
Expected behavior:
It's mandatory of having the ability of grouping the inventory valuation report grouped by location
and if you checked version 10 you will find it grouped by location by default...

**Comment by pedrobaeza** [comment]
@gustavovalverde can you point to the issue where you were discussing this?

**Comment by gustavovalverde** [comment]
Here https://github.com/odoo/odoo/issues/25055

**Comment by pedrobaeza** [comment]
Thanks! So closing as duplicated of #25055
