### ISSUE TITLE
variant do not show cost, even in product template form

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#26961]
Impacted versions:
12

Steps to reproduce:
select product  conference chair, there have not show cost price.
select product variants  conference chair[steel] , there have not show cost price.
select product variants  conference chair[aluminium] , there have not show cost price.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by jeffery9** [comment]
@nle-odoo have any idea?

**Comment by nle-odoo** [comment]
Hi @jeffery9


Thanks for the report, this seemed to be an error in 11.0, I have solved it with https://github.com/odoo/odoo/commit/07cdd24f30c2 and it will forward-ported soon.
