### ISSUE TITLE
resource: incorrect get_next_day computation for calendars with only 1 working weekday

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#26968]
**Impacted versions**

10, possibly others

**Steps to reproduce**

1. Create a resource calendar with only 1 working day per week, e.g. only Monday 09:00 - 13:00 and 13:00 - 17:00.
2. Call [`get_next_day`](https://github.com/odoo/odoo/blob/dc9b3df431c0c971b73870bcb9eaf90c07a84da8/addons/resource/models/resource.py#L179) on the calendar passing as `day_date` a date which weekday is the single working weekday defined in the calendar. e.g. if the calendar is only Monday, pass 2018-09-10 (which is a Monday). Or call it two times for any date (the first call if different weekday will work, but the second one won't as it's guaranteed to be the same weekday as the calendar)

**Current behavior**
The function returns the date passed

**Expected behavior**
The function returns the same weekday in the next week

**Implications**
This bug also breakes the `_schedule_days` method and all its wrappers, because it uses `get_next_day` internally to iterate the days to schedule.

**Screenshot**
![image](https://user-images.githubusercontent.com/5588738/45486060-127e3200-b75a-11e8-8275-cc6800d82ed4.png)

**Comment by Yenthe666** [comment]
Dear @LeartS,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
