### ISSUE TITLE
Unable to change UOM of product

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#26974]
Impacted versions: Odoo 11 enterprise (sh)

**Steps to reproduce:** Try changing UOM of a product, You will get warning stating 
_"You can not change the unit of measure of a product that has already been used in a done stock move. If you need to change the unit of measure, you may deactivate this product."_

Even if you deactivate the product, You still cant change the UOM and same warning pop ups.
**Current behavior:** 
Unable to change UOM even after deactivating product
**Expected behavior:**
After deactivating the product, We should be able to change the UOM as this is the expected functionality.

**Comment by mohdshoaib04** [comment]
@beledouxdenis Hi, Can you please try to emulate same ? This is causing major confusions related to its functioning.

**Comment by gdgellatly** [comment]
@mohdshoaib04 I see what you mean.  The message is confusing.  

I think what the message was meant to imply was that you need to deactivate the product AND create a new one with the changed unit of measure.

**Comment by mohdshoaib04** [comment]
@gdgellatly 
Hi, thanks for your reply.
Do you know which commit added these changes ?

**Comment by sswapnesh** [comment]
> After deactivating the product, We should be able to change the UOM as this is the expected functionality.

No, even after Deactivate Product You cannot change Product UOM, You can deactivate and create New product with correct UOM.

**Comment by gdgellatly** [comment]
In terms of history on this kind of restriction.

From memory v5 and v6 had no such restriction and it caused a lot of problems, it is quite easy to sum a list of kg's and metres but it doesn't mean much.
In either 6.1 or 7.0 a blanket restriction on changing UoM was introduced - it caused a lot of the opposite problems.
So a middle ground was introduced in either 7 as a bugfix or 8 which meant you couldn't change it if there were any stock moves. 

While the restriction could be marginally looser, it is absolutely necessary, finding the exact commit won't help you.  Changing the UoM (well category IMO) is not a good idea if there are pre existing stock moves.

**Comment by pedrobaeza** [comment]
@mohdshoaib04 yeah, that's the correct solution, and I think we all agree that the message should be improved adding " and create a new one with the new UoM".

@jco-odoo or @mart-e maybe you can make a quick change on this at least for v12.

**Comment by mart-e** [comment]
Already done at 06a804596ebc0e9407003fafd705706c3af07dfe :wink:

**Comment by mohdshoaib04** [comment]
@mart-e Thanks.
