### ISSUE TITLE
[8.0,7.0] wrong price computation when we combine linked pricelists and supplier prices on the product form 

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#2697]
Settings:
1. configure a purchase pricelist "Camptocamp"
    create a pricelist item with the product "Bose Mini Bluetooth Speaker"
    the price computation is : "Other pricelist", create a pricelist in the "Other Pricelist" field
2. configure the other pricelist : "Discount 50%"
    create a pricelist item with a price based on "Supplier prices on the product form"
and the next computation : New Price =  Base Price  \* ( 1 + -0.5000 ) + 0.00
3. Set the supplier Camptocamp in the product form with the price 140€ for quantity 1.
4. Set the new pricelist "Camptocamp" on the supplier "Camptocamp".

Current behavior:
1. create a quotation, with the supplier Camptocamp => pricelist field is automatically filled with "Camptocamp"  pricelist.
2. choose the product "Bose Mini Bluetooth Speaker", the computed unit price is .... 0 €   :(

Expected behavior:
the computed unit price should be 140*0,5 = 70 €.

**Comment by Yenthe666** [comment]
Hi @rdeheele,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
