### ISSUE TITLE
fields_view_get active_id not showing in context

### ISSUE THREAD

**Issue by zeinabzaiour** [odoo/odoo#26975]
Impacted versions: 11

Steps to reproduce:
Wanted to add a new page in mrp workOrders that contains fields from another model, that's why i used fields_view_get then sent the string form tags in res['arch']
What i need is the active_id of the record in edit_mode so that i can use it to set data in the string form to send.

Current behavior:
self.env.context not containing the active_id

Expected behavior:
active_id in the context so that i can use it

(Part of the code)
@api.model
def fields_view_get(self, view_id=None, view_type='form', toolbar=False, submenu=False):
    res = super(MrpWorkOrderInherited, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar,submenu=submenu)    
    _logger.info(self.env.context)
    if view_type == 'form':
        active_id = self.env.context.get('active_id', False)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Any way, I advanced you that that's not possible, as `fields_view_get` is evaluated independently from the current active ID.

Closing this by the reason above.
