### ISSUE TITLE
Updated `Done` quantity for products NOT in the first page of a received shipment are NOT saved

### ISSUE THREAD

**Issue by fboutin-pmc** [odoo/odoo#26980]
Impacted versions: `11`

Steps to reproduce:

1. Create a purchase order with MORE than 40 entries (products) and confirm it.
1. Go into the associated shipment, click ` Edit`
1. Go to the second page of products
1. Click on a product, enter a `Done` qty and click `Save`

Odoo will refresh the current page and put you back to the first page of products.

1. Return to the second page

Current behavior:

The `Done` qty you entered for the product was NOT saved and is still `0`

Expected behavior:

The `Done` qty should be saved for all products that are NOT in the first page.

Video/Screenshot link (optional):

![screen shot 2018-09-13 at 15 24 34](https://user-images.githubusercontent.com/19207021/45510834-63e1ed80-b769-11e8-91b3-371585fa9b87.png)

**Comment by fboutin-pmc** [comment]
Not a single flying F given after more than a month. Wow...

**Comment by chevyrooteam** [comment]
[Pull Request #27903](https://github.com/odoo/odoo/pull/27903) Seems to resolve this issue. Not sure why I can't link it here.

**Comment by Yenthe666** [comment]
@fboutin-pmc could you check that it solves your issue please? Your report and the PR look identical so I assume it is fixed now. If you still have problems after updating then let me know so I can reopen.


Regards, 
Yenthe
