### ISSUE TITLE
missing header in reports 

### ISSUE THREAD

**Issue by JoelPTorrents** [odoo/odoo#27013]
**Impacted versions:**
Odoo 11 CE
on Ubuntu 18.2

**Steps to reproduce:**
Printing any report, for instance the "Quotation/SO" in Sales.

**Current behavior:**
The report contains the information of the body, in a table but not grey-striped like before, and above all without the header.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

Specifically, check `report.url` system parameter or `web.base.url`, and also the proxy configuration with the proxy mode.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by JoelPTorrents** [comment]
@pedrobaeza 
Thanks for answering.
The official documentation was well followed during the installation.
Could you please specify how to check `report.url` system parametr or `web.base.url`, and also the proxy configuration with the proxy mode, please ?

**Comment by pedrobaeza** [comment]
Look for other issues in this tracker with similar title for finding this information.

**Comment by JoelPTorrents** [comment]
@pedrobaeza 
We fixed both parameters in our local IP adress and restart the system without the expected results.
