### ISSUE TITLE
[11.5] Unexpected behavior when submit a survey 

### ISSUE THREAD

**Issue by rsilvam21** [odoo/odoo#27011]
Impacted versions: 
v11.5
Steps to reproduce:
Test a survey and submit it
Current behavior:
Nothing happens
Expected behavior:
A "Thank You for your answer" page must appear after submit

Video/Screenshot link (optional):
https://youtu.be/5pYvT2QOgb4

**Comment by Yenthe666** [comment]
@JKE-be I thing this has to do with your website refactoring. Just an FYI.

**Comment by alxolivares** [comment]
Hi, as additional information, I would like to add that the survey is submitted correctly if it doesn't have a date field. On the other hand, when you keep the date field, the following error message appears in the browser console:

```console
Uncaught TypeError: Cannot read property 'date' of undefined
    at Object.beforeSubmit (web.assets_frontend.js:1521)
    at jQuery.fn.init.$.fn.ajaxSubmit (web.assets_common.js:2125)
    at HTMLFormElement.doAjaxSubmit (web.assets_common.js:2227)
    at HTMLFormElement.dispatch (web.assets_common.js:892)
    at HTMLFormElement.elemData.handle (web.assets_common.js:865)
```

I think this may be related to #27012 

Regards

**Comment by rdeodoo** [comment]
Hi, thank you for your report.
As mentioned on https://github.com/odoo/odoo/issues/27012#issuecomment-433662328 there was a fix for date input on survey.
I checked and was able to submit the form and saw the thank you page.
Let me know if you still experience the issue so I can/can't close this one :-)
