### ISSUE TITLE
Notebook always display and focus on the first page

### ISSUE THREAD

**Issue by kl-adonze** [odoo/odoo#27021]
Impacted versions:
11.0 Enterprise and community

Steps to reproduce:
Make a notebook inside notebook
Focus for example on the last page if we save the record the focus become on the first page 

Current behavior:
Focus for example on the last page if we save the record the focus become on the **first** page 

Expected behavior:
Focus for example on the last page if we save the record the focus become on the **lase** page 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
It's not very clear by your description the problem. Can you please include screenshots/video explaining the problem?

**Comment by khalidoss** [comment]
![bug_notebook](https://user-images.githubusercontent.com/6010546/45634999-c4d83100-ba9b-11e8-8475-515720b9ebaa.gif)

**Comment by khalidoss** [comment]
@pedrobaeza FYI

**Comment by pedrobaeza** [comment]
OK, thanks for completing the information.

@ged-odoo what do you think about this?

**Comment by nicomacr** [comment]
Someone have any idea if there are some workaround to solve this issue?
