### ISSUE TITLE
[10.0] TypeError: $row is undefined on 'Add an Item' when Editable bottom is used on o2m

### ISSUE THREAD

**Issue by vimalpatelserpentcs** [odoo/odoo#27058]
Impacted versions: 10.0

Steps to reproduce: 

- Click on `Add and item` on one2many (editable=bottom) tree view
- Add one item 
- Click again on `Add and Item` multiple times (It was not intended but it took time to load new lines which lead to this issue)
- It will generates many blank lines on same view
- Click again on `Add an Item`

Current behavior:

on firefox: version(61.0.1 (64-bit))
![firefox_one2many_issue](https://user-images.githubusercontent.com/27808219/45686792-b6a51600-bb6a-11e8-847c-63f1fe7b0bea.png)

on Google Chrome: version(69.0.3497.92)
![google_chrome_one2many_issue](https://user-images.githubusercontent.com/27808219/45687072-5662a400-bb6b-11e8-8767-9a9655859fa5.png)

Expected behavior:
No traceback on Screen
Video/Screenshot link (optional):
[https://youtu.be/zFDmqsAIAzw](https://youtu.be/zFDmqsAIAzw)

**Comment by Yenthe666** [comment]
Dear @vimalpatelserpentcs,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue and a personal sorry that I didn't get around to watching your video either.

Regards,
Yenthe
