### ISSUE TITLE
Error bad name parameter in po

### ISSUE THREAD

**Issue by chmuche** [odoo/odoo#27059]
https://github.com/odoo/odoo/blob/598fafb3aa17def4071845ca674c2e1fa512b5b8/odoo/addons/base/i18n/fr.po#L6887

It should be `%%(field)s` like in the `msgid` above

This bug exist in v8/v9/v10/v11 and maybe in another language

**Comment by pedrobaeza** [comment]
This is something you should fix at translation level using Transifex. Please check more information about translations in https://github.com/odoo/odoo/wiki/Translations
