### ISSUE TITLE
Bad behavior in the payment when an invoice is reconciled from bank statement

### ISSUE THREAD

**Issue by ysantiago** [odoo/odoo#27076]
Impacted versions: 11.

Steps to reproduce:
1- Create a sale invoice and validate it:
<img width="1277" alt="skitch 46" src="https://user-images.githubusercontent.com/11341058/45726968-afdcca00-bb8f-11e8-82bd-c913e7b6593f.png">

2- Create a bank statement with an amount less than the invoice:
<img width="1269" alt="skitch 47" src="https://user-images.githubusercontent.com/11341058/45727009-dc90e180-bb8f-11e8-9a3c-7c70d6701c31.png">

3- Reconcile this bank statement with the invoice and the remaining amount is sent to a loss account:
<img width="1248" alt="skitch 48" src="https://user-images.githubusercontent.com/11341058/45727197-9720e400-bb90-11e8-8072-bbabc3398a9f.png">

4- The invoice now is in Paid state:
<img width="1279" alt="skitch 49" src="https://user-images.githubusercontent.com/11341058/45727260-e9fa9b80-bb90-11e8-959c-ba69f12053c6.png">

5- Now go to the payment document and note the name:
<img width="1272" alt="skitch 51" src="https://user-images.githubusercontent.com/11341058/45727325-3ba32600-bb91-11e8-845f-01e4ada47694.png">

6- Cancel this payment, set to draft and confirm again.

Current behavior:
The payment name has changed and the statement data is lost:
<img width="1275" alt="skitch 52" src="https://user-images.githubusercontent.com/11341058/45727396-96d51880-bb91-11e8-8d26-1cb35296dc67.png">

And the invoice is now in open state with the amount due that was sent to the loss account:
<img width="1272" alt="skitch 53" src="https://user-images.githubusercontent.com/11341058/45727546-38f50080-bb92-11e8-8dc9-a6fdf78da98e.png">

Expected behavior:
After cancel, set to draft and confirm the payment, the name must be the same and invoice must be in the paid state.

Video/Screenshot link (optional):

**Comment by ysantiago** [comment]
The error also occurs when from the statement a payment is reconciled with two invoices, which are paid. If later on one of these invoices the payment is canceled and validated again, this invoice is paid while the other is opened without any payment applied.

**Comment by qdp-odoo** [comment]
indeed... whenever you're cancelling something in the accounting app, you're kinda off-track skiing and you need to be sure what you do. Corner cases may arise doing so.

For this reason, we won't try to fix that in stable versions, but we will do something to avoid the same problem on master (or v12?), as for example the solution proposed by Pedro

Thanks for your understanding
