### ISSUE TITLE
Can't Add Custom filters on form view with fields many2one

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#27074]
**Impacted versions:**
11.5, master(Comunity and Enterprise)
**Steps to reproduce:**
Go to any view with a field m2o and _**search more**_, try add custom filter, panel hidden random.
**Note:** If add custom filter from main's menu this working fine, error is on form view with fields m2o at search more
**Current behavior:**
can't add custom filter
**Expected behavior:**
Add custom filter
**Video/Screenshot link (optional):**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7775116/45711293-a431d900-bb78-11e8-8da0-c7e7bb3f118c.gif)

**Comment by pedrobaeza** [comment]
@ged-odoo can any of your team please check this one?

**Comment by ged-odoo** [comment]
good catch. I don't know why, but I suppose this is caused by our recent changes on the search view.
@aab-odoo @adr-odoo

**Comment by kebeclibre** [comment]
closed at https://github.com/odoo/odoo/commit/034a27f63076529f23e368686409125b6ff1c21f
