### ISSUE TITLE
applications Technical Name should be in "technical datas" tab

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#27070]
Impacted versions: all

Steps to reproduce: enable developer mode, go to Applications, clic on one of them.

Current behavior: "Technical name" is writed in the "information" tab

Expected behavior: "Technical name" writed in the "technical datas" tab

**Comment by pedrobaeza** [comment]
I don't think so. That name is very important for a lot of people, so it should be easily located, and it's only shown when you have activated debug mode / Technical features group, so it's enough hidden for the rest of the users.

I let opened for a second opinion before closing.

**Comment by zeroheure** [comment]
I agree, that name is very important. But it is only visible when you have activated debug mode. Hence it seems more logical, in the ergonomic sense, to find it in the technical datas tab. May be it should be in both tabs ?

**Comment by pedrobaeza** [comment]
Well, showing a field 2 times is also not ergonomic and can have technical side effects, so I prefer to keep it as is.

**Comment by mart-e** [comment]
Hello,

Indeed, while it looks logical to move it in the technical tab, however, as said Pedro, it is an important information we usually wants to see first. I guess both points are understandable...

Anyway, in the master version, this view no longer exists so no need to debate if it should be changed or not (view improvement should target the master version).
