### ISSUE TITLE
Hard to remember which icon for which application

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#27073]
Impacted versions: all

Steps to reproduce: Click on the general Menu icon, look at the applications icons, choose one

Current behavior: the app icon is not display in the application itself. It doesn't help to associate the icon to its app.

Expected behavior: icon visible in the application screen, as for example in desktop application where it is usually display in the window decorations button

**Comment by pedrobaeza** [comment]
Well, you have search for that purpose, and on community, icons are not displayed, so it's only a problem on enterprise interface, and thus I close this. Propose the wishlist if you still want to get this on https://www.odoo.com/help

**Comment by zeroheure** [comment]
Well, the official users documentation sometimes contains application icons, so it's not only a problem on enterprise interface, and thus I suggest to reopen. ;-)
