### ISSUE TITLE
resource.calendar: is_work_day return always False with some timezones

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#27097]
Impacted versions:
11.0
Steps to reproduce:
In your preferences set Timezone = Europe/Brussels (or Europe/Paris like me).
on a resource calendar record, execute record._is_work_day(datetime.date(year, month, day), False)

Current behavior:
return always False
Expected behavior:
return True if the date is a working day
Video/Screenshot link (optional):
example in runbot with Timezone = Europe/Brussels:
![resFalse](https://user-images.githubusercontent.com/25034353/45752116-c24d1700-bc14-11e8-87e1-04429faac244.png)
same with Timezone = False or UTC
![resTrue](https://user-images.githubusercontent.com/25034353/45752137-d133c980-bc14-11e8-86ea-a50b634bc338.png)

**Comment by pedrobaeza** [comment]
You are using incorrectly the method. You have to pass a resource_id (the employee resource one for example).

Closing as no real issue. Please abstain of doing this kind of issues, as they are more your development questions, and check docstring instead of make the question on forums.

**Comment by Linekio** [comment]
Objection ! :)
There is the same issue with a resource_id (besides, I think resource_id should be optional since it's just to catch a resource's leave).
Here more tests with resource_id (on runbot, demo datas):
With Timezone = Europe/Brussels:
![capture du 2018-09-19 16-46-28](https://user-images.githubusercontent.com/25034353/45761237-23ccb000-bc2c-11e8-886d-d82f04ac0963.png)

With Timezone= False or UTC:
![capture du 2018-09-19 16-50-31](https://user-images.githubusercontent.com/25034353/45761399-78702b00-bc2c-11e8-8da6-38aca6494b5a.png)
