### ISSUE TITLE
[10,11,master]The translation template contains the html tag section

### ISSUE THREAD

**Issue by Guobower** [odoo/odoo#27096]
Impacted versions:
[10,11,master]  The translation template contains the html tag part. When the content of the tag is translated, the inherited xml file cannot find the id of the inherited object. The saas11.5 version have a few translation term of zh_CN.po, install moudle will received error messages
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get the problem. Do you have reproducible steps for getting an error?

**Comment by Guobower** [comment]
1、Creat a database in english, database creat normal.
![image](https://user-images.githubusercontent.com/22065407/45753121-584f6480-bc4a-11e8-988b-8694dcfff435.png)
2、Load the chinese language 
![image](https://user-images.githubusercontent.com/22065407/45753240-b2502a00-bc4a-11e8-80c4-9535be54d2f7.png)
3、when change the language refresh page
![image](https://user-images.githubusercontent.com/22065407/45753361-28549100-bc4b-11e8-8540-2e9408c5b7b5.png)
4、Search the translate term &amp;nbsp;
![image](https://user-images.githubusercontent.com/22065407/45753476-9bf69e00-bc4b-11e8-83dd-a3f7e7f53da3.png)
5、Correct translation ，then app page normal 
![image](https://user-images.githubusercontent.com/22065407/45753609-f263dc80-bc4b-11e8-8ea7-b312c43fb045.png)
![image](https://user-images.githubusercontent.com/22065407/45754624-b41bec80-bc4e-11e8-8900-d256723baf17.png)

In my point of view，Every information which we need translate was out of the html tag, 
![image](https://user-images.githubusercontent.com/22065407/45754831-520fb700-bc4f-11e8-872d-a53b816c6e1c.png)
so the translation template could not include the infomation like above.

**Comment by pedrobaeza** [comment]
But the problem is in an improper translation. You should translate also the HTML tags. This is done on purpose for allowing certain HTML variations depending on the language. See https://github.com/odoo/odoo/wiki/Translations for information on how to translate.

**Comment by progmars** [comment]
@pedrobaeza  The linked article does not mention how and why HTML tags are included in translations.
Also it does not solve the issue at its core.

For example, I create an XML template and want to add translations of text strings in the template. I run Generate missing terms. As a result, Odoo generates dirty text strings with HTML tags around them. For example, I have a template 
```
<div>
    <span>Invoice</span>
</div>
```
I would expect Odoo to generate `Invoice` as translation source, but it generates entire `<span>Invoice</span>`. It confuses our translator and makes it more difficult to translate.

How to prevent this from happening?

Odoo is v13, by the way.

**Comment by pedrobaeza** [comment]
That's another unrelated thing, and it's how Odoo works, as that minor HTML tags are translatable as they can vary on each language.
