### ISSUE TITLE
[11.0] Unexpected search behavior with `in` operator and 0.00 in its arguments.

### ISSUE THREAD

**Issue by ejbdev** [odoo/odoo#27112]
Impacted versions:
11.0
Steps to reproduce:
1- Search any model with a numeric field using `in` operator
 `self.env['account.bank.statement'].search([('balance_start','in',[0.00])]) # no results`
2- Search again using `=`
 `self.env['account.bank.statement'].search([('balance_start','=',0.00)]) # 1 result`

Current behavior:
Search results with operator `in` differ from search result with operator `=`.

Expected behavior:
Same results

Optional:
Search: `self.env['account.bank.statement'].search([('balance_start','in',[0.00])])`
Produce: `SELECT "account_bank_statement".id FROM "account_bank_statement" WHERE (FALSE OR "account_bank_statement"."balance_start" IS NULL) ORDER BY "account_bank_statement"."date" DESC,"account_bank_statement"."id" DESC` and ignore 0 as possible  value.

Search: `self.env['account.bank.statement'].search([('balance_start','=',0.00)])`
Produce: `SELECT "account_bank_statement".id FROM "account_bank_statement" WHERE ("account_bank_statement"."balance_start" = %s) ORDER BY "account_bank_statement"."date" DESC,"account_bank_statement"."id" DESC`

**Comment by pedrobaeza** [comment]
This is the expected behavior, as float fields are not searchable with `IN` operator. You should use arithmetic operators in this case.

Closing as no real issue, but misuse of the domain with floats.

**Comment by ejbdev** [comment]
thanks for the answer,
 
When i search: `self.env['account.bank.statement'].search([('balance_start','in',[1.00,10.00,0.00,])])`
produce the following sql:
`SELECT "account_bank_statement".id FROM "account_bank_statement" WHERE (("account_bank_statement"."balance_start" in (%s,%s)) OR "account_bank_statement"."balance_start" IS NULL) ORDER BY "account_bank_statement"."date" DESC,"account_bank_statement"."id" DESC`

searching correctly for values 1.00 and 10.00 and ignoring 0.0, so that's why my confusion

**Comment by pedrobaeza** [comment]
Well, that's a side effect of using it, but I don't recommend you that, as floats can be represented in DB with other decimals, and then don't match that way.
