### ISSUE TITLE
Can't add a ir.model.access to mrp.production

### ISSUE THREAD

**Issue by dorcyv** [odoo/odoo#27111]
Hello,

I have a problem with a `ir.model.access.csv` file: I try to add an access control to the `mrp.production` model and I have this error: 
```
 No matching record found for external id 'model_mrp_production' in field 'Object'
Missing required value for the field 'Object' (model_id)
```
There is the file:
```
id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_production_operator_group,mrp.production operator,model_mrp_production,mrp.group_mrp_user,1,1,0,0
```

It's append on odoo 11

**Comment by sswapnesh** [comment]
This should be asked here on Github.
Use Odoo forum instead.

Ps: You should add `mrp.model_mrp_production` instead of `model_mrp_production` If you are loading this in custom module

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
