### ISSUE TITLE
[11.0] cannot differentiate "Payment" status from treeview

### ISSUE THREAD

**Issue by Boss1669** [odoo/odoo#27129]
Impacted versions: 11.0

Steps to reproduce: 
1.Create Customer 
2.Create Invoices
3.Create Payment & Confirm

Current behavior:
If there are still balance that are able to match the invoices
it will shows INVOICES and PAYMENT MATCHING.
![image](https://user-images.githubusercontent.com/26357404/45810765-9b1a4680-bcf5-11e8-9d61-7099a402df87.png)
Where as if all balance match the invoices already 
it will shows just INVOICES
![image](https://user-images.githubusercontent.com/26357404/45810872-e92f4a00-bcf5-11e8-81a8-e9945de4941c.png)
(Ignore Customer Name)

On treeviews it will just show status "POSTED" and user not able to distinguish which one has actually been payment matching yet.
![image](https://user-images.githubusercontent.com/26357404/45810941-154acb00-bcf6-11e8-9481-463e2ac24579.png)

And I Couldn't find anything to filter.

Expected behavior: Need to able to distinguish between payment that, did payment matching and the one didn't

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
