### ISSUE TITLE
[11.0]How to change the maximum attachment size limit

### ISSUE THREAD

**Issue by foxinstone** [odoo/odoo#27123]
I don't understand why odoo11 wants to use the 25M limit. It should be known that this restriction may seem too old now!
How to change this limit?
(I have already googled and I have not found a solution for V11.0.)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
