### ISSUE TITLE
URL widgets refusing display text per documented api

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#27122]
Impacted versions: 11.0

Steps to reproduce: 
Create a view with the URL widget and attempt to set the displayed text per the documentation at   https://www.odoo.com/documentation/11.0/reference/javascript_reference.html#non-relational-fields

Documentation example is:  `<field name="foo" widget="url" text="Some URL"/>`

Current behavior:
A field defined exactly as shown in the documentation will throw a validation error from the relaxng validator for the list arch type

My field definition is:    `<field name="gendb" widget="url" text="GenDB"/>`

Result is:  
```
  File "/home/odoo11/odoo/odoo/models.py", line 3255, in _write
    self._validate_fields(vals)
  File "/home/odoo11/odoo/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/home/odoo11/odoo/odoo/addons/base/ir/ir_ui_view.py", line 343, in _check_xml
    raise ValidationError(_('Invalid view definition'))
odoo.tools.convert.ParseError: "Invalid view definition
None" while parsing /home/odoo11/addons/var_clin/views/views.xml:4, near
<record model="ir.ui.view" id="var_clin.list">
 ... omitted ...
        <tree>
            <field name="gendb" widget="url" text="GenDB"/>
```
If the field definition is changed to `<field name="gendb" widget="url" string="GenDB"/>`
then there is no error, but the actual href of the URL is displayed rather than the desired text. 

Expected behavior:
It should be possible to set the URL display string as described in the documentation.  Since this exact construction is used in Odoo code, e.g.

    addons/web/static/tests/fields/basic_fields_tests.js:1205
    addons/google_drive/views/res_config_settings_views.xml:17

it seems important that it should work.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I have just tried on runbot and it's working perfectly:

![seleccion_009](https://user-images.githubusercontent.com/7165771/45802691-d8f87a00-bcb7-11e8-8c07-261f26376fb9.png)

![seleccion_008](https://user-images.githubusercontent.com/7165771/45802694-dbf36a80-bcb7-11e8-830d-0a0bc64a7d8f.png)

It should be something more on your side.

Closing as no real issue.

**Comment by elgow** [comment]
I notice that you are in a form view rather than a list view, so you have not tested the problem that I cited.  Is it intentional that this widget should not work in a list view, and if so why? If it should work in a list view then please re-open so that the RNG schema will get fixed. As far as I can see that is the only thing preventing the widget from working in a list view.

**Comment by pedrobaeza** [comment]
You didn't mention in any moment that you wanted to put it in a tree view. Yes, in a tree view, it's not supported that way. Use a button with an act_url action instead.

**Comment by elgow** [comment]
Actually the error message in my issue report says clearly that it's in a tree view.


<record model="ir.ui.view" id="var_clin.list">
 ... omitted ...
        <tree>
            <field name="gendb" widget="url" text="GenDB"/>


May I ask why it's not supported in a tree view? The only thing that doesn't work is the display string change. The widget itself works fine in a tree view. It would seem to add quite a bit of value for no real cost to just not make the tree view schema break that widget.

  Ed



________________________________

**Comment by pedrobaeza** [comment]
No special reason, except it's not developed. I have told you another way to do it any way.

**Comment by elgow** [comment]
If that's the case then, if it's not too much trouble, may I request that one line be added to a file at
odoo/addons/base/rng/common.rng:217

The line is 
`            <rng:optional><rng:attribute name="text"/></rng:optional>`

Adding that line makes the widget work correctly.  The Odoo docs do not say anywhere that this widget won't work in the list view, so it's natural that the developers will assume that it will work as advertised. Indeed, the only reason that the form view works seems to be that there is no relaxng validation of the form view. If there were then it would also fail due to the spurious restriction in the common.rng file. 

Fixing the common.rng file seems easier than fixing the documents to explain the unnecessary restriction on the use of the URL widget in tree views, so it seems like the right thing to do.

**Comment by pedrobaeza** [comment]
I'm not sure if that's enough for making it work, but if you try and work, please propose a PR to Odoo itself (but it should be master branch) for adding this option.

**Disclaimer**: I'm not an Odoo employee, but a community member that voluntary contributes to triage / classify / solve issues. Take also into account that there's no obligation to answer nor solving things put in Odoo Community issue tracker. And thus, please consider this as a best effort initiative.
