### ISSUE TITLE
[BUG] stock_account : correction_value is always 'none'

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#27151]
Impacted versions:
V11

In this line https://github.com/odoo/odoo/blob/11.0/addons/stock_account/models/stock.py#L70

`move._run_valuation(res.qty_done)` must return some thing, but `_run_valuation` have no `return`.

cc @jco-odoo

**Comment by fmdl** [comment]
cc @lap-odoo @odony 

OPW:1 907 021

**Comment by lap-odoo** [comment]
@fmdl Thanks for reporting this.

@nim-odoo Could you please take care of that issue ? Do you want me to create a ticket ? I can test the fix if you want.

**Comment by Julien00859** [comment]
Solved with 4612d50b
