### ISSUE TITLE
Force type'html' in controller

### ISSUE THREAD

**Issue by SBC-MvS** [odoo/odoo#27169]
Hello

currently the odoo behavior for incoming requests with content-type application/json is to switch to type='json' for the controller functions which really is only for json rpc. A normal json request interface for a REST service is still possible if the request is any other type and odoo switchs to type='html'. The problem come's if you can't influence the content-type in the client. For example we are working on a module that uses outlook actionable messages to give a status to the user and can be refreshed through the action. Only Outlook always sets content-type appplication/json and expects a default json. 

For the reverse problem with clients that can't set application/json as content type there exists the parameter jsonp that can force the json mode. It would be good if there where a reverse parameter to force html mode. This way you only have to extend the url that is called with the parameter. Or maybe a option in @http.route like force_type to force the behavior of the controller.

**Comment by pedrobaeza** [comment]
Odoo is not REST compatible. If you want to make Odoo compatible with a REST service, check https://github.com/OCA/rest-framework PRs.

Closing as no possible to solve in the core.
