### ISSUE TITLE
[11.0] Typo in sale_timesheet controller

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#27160]
Impacted versions: 11.0

Typo in this line: https://github.com/odoo/odoo/blob/11.0/addons/sale_timesheet/controllers/main.py#L44

Should be "to_invoice" so that the value can be included in the timesheet_plan template.

**Comment by pedrobaeza** [comment]
@jem-odoo can you please check this?

**Comment by Yenthe666** [comment]
Made a PR for it at https://github.com/odoo/odoo/pull/27166
It does look like a typo/error. Other example where `to_invoice` is used is in https://github.com/odoo/odoo/blob/11.0/addons/sale_timesheet/controllers/main.py#L66
