### ISSUE TITLE
Accounting lets you cancel many times the same invoice

### ISSUE THREAD

**Issue by SamAndaluz** [odoo/odoo#27165]
Impacted versions: 11

Steps to reproduce: 
1. Create an invoice (I did create from a Sales Order)
2. Register payment
3. Unreconcile
4. Add a Credit Memo with the option:
Modify: create credit note, reconcile and create a new draft invoice 
This will create an Open Credit Memo with status 'Paid' and the invoice will have the status 'Paid'
5. Unreconcile the invoice
Cancel again with the option: Modify: create credit note, reconcile and create a new draft invoice 
6. Unreconcile the invoice
Cancel again with the option: Modify: create credit note, reconcile and create a new draft invoice 

Current behavior:
The system ends with more than one Credit Memo, that there is no way to delete or cancel applying a Debit Memo, for example.

Expected behavior:
After applying a 'Credit Memo' to cancel an invoice completely, the status should not be 'PAID'.  That is incorrect.  The status should be 'Canceled'.  In that way, the user does not get confused that the cancellation did not happen.
As the total sales is considering the cancelled invoice, and the status is 'PAID' it seems that the cancelation did not work, so the users tries again, and again. Until realizes that has more than one Credit Memo for the same invoice.
Also, more important, is that once the invoice has been cancelled completely once, the system should not allow to cancel again.

Video/Screenshot link (optional):

**Comment by SamAndaluz** [comment]
[multipleCreditMemosSameInvoice.pdf](https://github.com/odoo/odoo/files/2407553/multipleCreditMemosSameInvoice.pdf)
[multipleCMsSameInvoice.pdf](https://github.com/odoo/odoo/files/2407554/multipleCMsSameInvoice.pdf)

**Comment by pedrobaeza** [comment]
This is not a bad behavior, because you are tricking the system: you are unreconciling the same invoice several times (that's it, manual action), so you are the responsible of cancelling also the previously generated credit notes if you want that. If not, that's not a problem, as you are informed that you have the outstanding credits as soon as you validate the invoice.

Closing as no real issue.

**Comment by SamAndaluz** [comment]
Pedro, what you say cannot be done.  Your words: "...so you are the responsible of cancelling also the previously generated credit notes if you want that..." exactly this is the issue.  This cannot be done.  The system does not let you do that.  Please replicate it, instead of just telling me that I am wrong.  I know it is wrong what I did, but it is wrong that the system let me do it wrong.  And worst, is that it does not let me correct it.  If I could correct it, I would already have done it, instead of creating an issue here and a support ticket in Odoo.  It takes more time to explain these things that to correct them.  But this is what I am saying, the system does not let you correct it.  It seems that by all the Credit Memos being associated to the same invoice, you need to apply just to this invoice.

**Comment by SamAndaluz** [comment]
in numbers, I have positive 2,200 and negative 8,800.  But only one -2,200 is cancelling the positive 2,200 while the other -6,600 are also trying to cancel the same 2,200 already cancelled.

**Comment by SamAndaluz** [comment]
and I do not have an option to cancel the other 6,600.  I should have started showing the error, instead of the way I did.
[CreditMemosIssue3.pdf](https://github.com/odoo/odoo/files/2407779/CreditMemosIssue3.pdf)

**Comment by SamAndaluz** [comment]
that file just updated, shows the error, it says that I cannot cancel the Credit Memos.  That I should apply a Credit Memo; which by the way, it is also wrong, because a Credit Memo should be cancelled with a Debit Memo, which is the opposite direction.
