### ISSUE TITLE
POS Lot Product

### ISSUE THREAD

**Issue by andrewyova** [odoo/odoo#27173]
Impacted versions:
11
Steps to reproduce in pos screen:
1. order product "A" lot at 1st time
2. then order product with no lot option
3. order product "A" again
4. pop up error (no insert lot numbering)

Video/Screenshot link (optional):
![pos_lot_product](https://user-images.githubusercontent.com/25319332/45936983-a5369080-bfe6-11e8-98cd-bd62405098e2.png)

[bug_pos_11_lot.mp4.zip](https://github.com/odoo/odoo/files/2409561/bug_pos_11_lot.mp4.zip)

**Comment by andrewyova** [comment]
> Are you able to replicate the same behavior in runbot (https://runbot.odoo.com - admin/admin)?

i attach video is from runbot 
[bug_pos_11_lot.mp4.zip](https://github.com/odoo/odoo/files/2410174/bug_pos_11_lot.mp4.zip)

**Comment by sswapnesh** [comment]
Duplicate of  #25515

**Comment by pedrobaeza** [comment]
@sswapnesh are you sure it's the same?

**Comment by sswapnesh** [comment]
Steps to Reproduce are different but Error is Same.

**Comment by pedrobaeza** [comment]
OK, then maybe it's another thing. Let's keep it opened for now.

**Comment by sswapnesh** [comment]
Seems working well now. (Tried with new Config + Sessions, along with Steps mentioned in video)

**Comment by Yenthe666** [comment]
I'll close it now then, since you where able to reproduce it first and not again now. @andrewyova can you please update your Odoo, try again and can you confirm that it is solved for you now too?
