### ISSUE TITLE
many2many_binary Can't upload files that just have been deleted

### ISSUE THREAD

**Issue by eng-eslam-a-y** [odoo/odoo#27182]
Impacted versions:
11.0

Steps to reproduce

On any many2many attachment field with widget="many2many_binary"
1. Attah a new file
2. Delete file form attachment
3. try to attach the same file again (nothing happen)
4. try to attach a different file it will get attached 

Current behavior:
try to attach the same file again (nothing happen)

Expected behavior:
try to attach the same file again , it will get attached 

Video/Screenshot link (optional):

**Comment by eng-eslam-a-y** [comment]
@Yenthe666 could you please have a look at this?

**Comment by Yenthe666** [comment]
@ged-odoo I assume this one is for you guys.

**Comment by Linekio** [comment]
@eng-eslam-a-y  I can't reproduce the issue. Have you tried updating your Odoo?

**Comment by eng-eslam-a-y** [comment]
@Linekio sorry for inconvenience it was actually fixed in #25568
Thanks

**Comment by pedrobaeza** [comment]
Closing then as solved.
