### ISSUE TITLE
Incomming shipments don't update product quantity, Move in done state

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#27196]
**Impacted versions**: odoo 11 (sh)
Very difficult to reproduce, We faced this issue quite often on live odoo 11 sh.
Steps to reproduce: Create incoming shipments for any products, Process incomming shipment and check products quantity.

**Current behavior**: Sometimes, does not update the product quantity when processing incomming shipments.

**Expected behavior**: Should always process incomming shipments with full integrity.

**Additional Information** :
This issue seems to be linked to integrity of odoo transaction over network, I would like to highlight a point the place where odoo is used in production does not have good internet connectivity. This might be linked to transactions getting wrongly/incomplete commited.

**Comment by pedrobaeza** [comment]
@mohdshoaib04 I doubt this is linked to connectivity problems, as all operations are performed server-side and on client side you only see the result.

@sle-odoo unless you tell me the contrary, I would close this as it doesn't have enough reproducible steps. This doesn't mean that the problem might exist, but it's no possible to solve it with this vague references.

**Comment by pedrobaeza** [comment]
Yeah, but as said, this can't be solved with consistent steps to reproduce it.

**Comment by sle-odoo** [comment]
@pedrobaeza to increase the quantity on hand we have a logic to write on a quand if not lock is taken else create a new one, maybe this could be the culprit? [see here](https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_quant.py#L214)

however we have a [test](https://github.com/odoo/odoo/blob/11.0/addons/stock/tests/test_quant.py#L219) and it passes.

but yeah without some more context/logs i can't do much, furthermore we didn't have any ticket regarding this before

**Comment by pedrobaeza** [comment]
Thanks for the information, @sle-odoo. I see that there's not too much room for error there, so I'm going to close this until we have fixed reproducible steps. I have several 11.0 installations with a lot of stock load, and I haven't observed this problem (but a problem with reserved quantity I'm tracing).
