### ISSUE TITLE
[WISH] switch session to jwt?

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#27206]
Impacted versions:
master 

Steps to reproduce:

Current behavior:

Expected behavior:
Use jwt instead of session, more coud native

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
I think he means using jwt would be more stateless, as sessions are currently file based, just like those other solutions storing session info in postgres.

**Comment by xmo-odoo** [comment]
1. you haven't put forth a use case
2. [JWT is awful](https://hn.algolia.com/?query=author:tptacek%20jwt&sort=byPopularity&prefix&page=0&dateRange=all&type=comment)
