### ISSUE TITLE
Editable MOs in community edition 11

### ISSUE THREAD

**Issue by OpenTechValue** [odoo/odoo#27216]
Impacted versions:
11 community

Steps to reproduce:
create a MO 

Current behavior:
it is not possible to change/add material to be consumed

Expected behavior:
in the odoo11 release note it is stated as follows:
Editable MOs: You are now able to consume other products despite what was initially planned and edit MOs once they are done.
Please confirm this is related to enterprise version only.
Regards
Claudio

**Comment by pedrobaeza** [comment]
Claudio, it's working the same on both community and enterprise. You just need to press "Unlock" button before being able to add more consume lines:

![seleccion_004](https://user-images.githubusercontent.com/7165771/46017409-af848780-c0d7-11e8-977e-05394ca8d6fa.png)

Closing as no real issue.

**Comment by OpenTechValue** [comment]
thanks
claudio

Il giorno mar 25 set 2018 alle ore 15:31 Pedro M. Baeza <
notifications@github.com> ha scritto:

**Comment by lukebranch** [comment]
Hi @OpenTechValue Claudio,

Sorry to comment on a closed issue, could you advise how to contact you directly? I can't find contact details for your company and would like to discuss a few things with you.

(@)pedrobaeza, apologies in advance for commenting on a closed issue. a

**Comment by OpenTechValue** [comment]
Please contact me at opentechvalue@gmail.com

**Comment by lukebranch** [comment]
> Please contact me at [opentechvalue@gmail.com](mailto:opentechvalue@gmail.com)

Thanks!
