### ISSUE TITLE
Sale Order: cannot re-create a deleted invoice

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#27213]
Impacted versions:
9.0, 10.0, 11.0
Steps to reproduce:
Install sale_management
Don't install delivery
Create a quotation with a product. The invoice policy must be "Delivered quantity".
Confirm the quotation, and create an invoice. Choose "Invoiceable lines".
Delete the invoice.
Re-create the invoice with the same option.
Current behavior:
Error : "There is no invoiceable lines.
Expected behavior:
Create an invoice
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't have that problem on my installations nor runbot:

![peek 25-09-2018 13-38](https://user-images.githubusercontent.com/7165771/46012084-4e08ec80-c0c8-11e8-926e-692e1e3f47a1.gif)

Any way, you put 9, 10 and 11, and `sale_management` is only available on v11, so I suppose you have made the test there. Check you custom modules or updated code.

**Comment by Linekio** [comment]
Yes, just install sale on 9.0 and 10.0.
I tested without custom module. Have you tested without installing the delivery module ?
I advise you to test on runbot - base (not runbot all) and install only sale_management.

**Comment by pedrobaeza** [comment]
I have tried the same in base runbot, and the result is the expected: I'm not able to replicate the problem:

![peek 25-09-2018 15-37](https://user-images.githubusercontent.com/7165771/46017927-f2932a80-c0d8-11e8-9785-47598095a300.gif)
