### ISSUE TITLE
[11.0] Creating products renders no product name translation terms

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#27225]
Impacted versions: 11.0

Steps to reproduce: See the video
https://drive.google.com/file/d/1Q4JuczagMezX5G0AGSnEZtBvmI7_PHFu/view

Current behavior: The source term is not found under translations. When you go back to the product, click on the globe icon for translations and then do the search again you'll find the source term all of a sudden.

Expected behavior: The source term is directly added and shown under translations.

**Comment by Yenthe666** [comment]
@mart-e could you please check this? cc @OEFunctionals

**Comment by Yenthe666** [comment]
@mart-e I understand but what if you create/import hundreds of products manually? There is no way for me to trigger that in an import is there?

**Comment by mart-e** [comment]
If they have an external id, you may want to try with the "generate missing terms" option to generate empty translations to be able to use the import/export :crossed_fingers:
