### ISSUE TITLE
[WISHLIST] website: allow to set default values on fields built with FormBuilder

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#27221]
Impacted versions: All

Steps to reproduce:
1. Create a new webpage
2. Create a form with the `Form Builder` and set some fields on it

Current behavior: There is no ability to set default values or default selections from the UI.
![image](https://user-images.githubusercontent.com/6352350/46017223-44d34c00-c0d7-11e8-917d-da0706e666ae.png)

Expected behavior: The ability to set default values or default selections from the UI.

**Comment by pedrobaeza** [comment]
This is something enterprise only.

**Comment by Yenthe666** [comment]
Yep, absolutely & a great place to add wishlist items, no?

**Comment by pedrobaeza** [comment]
You know our discussion about that :wink:

**Comment by Yenthe666** [comment]
Oh I know you where hinting at that 😉 The thing is that it is not a bug but a wishlist item. Where else would you want me to put it? Through the "Other" option on odoo.com/help? We both know that won't end anywhere. So unless Odoo provides me a great way to fill in wishlist items where I'm confident they'll get handled neatly I'll stick with this. Even if that means bothering you, sorry 😄

**Comment by pedrobaeza** [comment]
Yeah, I know, that's why I haven't closed it as my usual way, hehe. But the reasoning is the same for wishlist/issues: it's something that doesn't matter to the rest of the community. Only for enterprise users. I hope we can discuss this with Odoo for a good enterprise issue/wishlist tracking (if not possible through odoo/enterprise repo).

**Comment by Yenthe666** [comment]
Yeah I completely agree with you. Thanks for keeping it open too.

**Comment by Yenthe666** [comment]
On a sidenote, there is another handy option missing here. When you choose 'Existing field' to add a field on the form with the FormBuilder and choose a selection value it is shown as radio buttons. It would be neat to be able to choose between radio buttons and an actual dropdown.
