### ISSUE TITLE
error odoo.conf on odoo10

### ISSUE THREAD

**Issue by lloscarll** [odoo/odoo#27239]
i was change config for addons on ~/odoo-dev/odoo/debian/odoo.conf, but nothing has change.
than i copy ~/odoo-dev/odoo/debian/odoo.conf to /etc/odoo.conf, but still not change.
thanks

**Comment by mart-e** [comment]
Hello,

What are you trying to achieve exactly?

**Comment by lloscarll** [comment]
just add new location for addons

**Comment by lloscarll** [comment]
how to set new location for addons

**Comment by lloscarll** [comment]
how to set new location for addons on ubuntu server
