### ISSUE TITLE
[11.0] CSS file doesn't found in dynamic URL.

### ISSUE THREAD

**Issue by Tacenda25** [odoo/odoo#27237]
Impacted versions:
11.0

Steps to reproduce:
If I render a template with dynamic URL, CSS file doesn't found.
`@http.route('/productList/<string:package>', type='http', auth='user', website=True)`
` def index_product_list(self, *args, **kwargs):`

If with static URL, CSS file founded.
`@http.route('/productList', type='http', auth='user', website=True)`
    `def index_product_list(self, *args, **kwargs):`

assets.xml
`<link href="vendor_package_frontend/static/css/styles.css" rel="stylesheet"/>`

Current behavior:
QWEB try to found by this URL: 
http://localhost:8079/productList/vendor_package_frontend/static/css/styles.css
For example http://localhost:8079/productList/Gold, when render it template CSS not founded.

Expected behavior:
If I render dynamic URL, CSS file found.

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
At a guess it has nothing to do with dynamic url, more to do with using a
relative path in assets.xml and being nested 1 level deeper so it isn't
found.

**Comment by pedrobaeza** [comment]
Indeed, the problem comes from the relative URL expressed in the asset. Put a `/` at the beginning.

Closing as no real issue.
