### ISSUE TITLE
[11.0] Default mail template set using debug mode does not work for sale order using the button "send by email"

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#27246]
Impacted versions:
[11.0]

Steps to reproduce:
1. Activate developer mode.
2. Open a sales order.
3. Click on the button "send by email".
4. Select a different mail template.
5. Click on debug icon and select "set default value"
6. use the setting for mail template and save it for only you.
![selection_006](https://user-images.githubusercontent.com/30628967/46081791-b1188300-c19d-11e8-92b8-110e072e643a.png)

7. In Settings > Technical > Actions > User-defined Defaults, you can find the saved value.
![selection_007](https://user-images.githubusercontent.com/30628967/46081915-048ad100-c19e-11e8-923a-c02d0a2112e8.png)

8. Open another sales order and click on send by email.

You will notice that your default value is not working here.

Expected behavior:
Either make it work or dont let the user save the setting. It is confusing and it is not working.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I am not sure but May be this is because we are passing default template here:
https://github.com/odoo/odoo/blob/11.0/addons/sale/models/sale.py#L494

**Comment by pedrobaeza** [comment]
Indeed, this can't be changed through default values as it's hardcoded. You should change that mail template to fit your needs, or overwrite the method and change that default template.

Closing as no issue, although non desirable behavior.

**Comment by yung-wang** [comment]
That is too bad it is hardcoded and not very user friendly. Especially if you have multiple layout you have to change manually the template. I hope Odoo can put this on the wishlist.
