### ISSUE TITLE
The report cannot show the warehouse address when shipping. What is wrong with this code

### ISSUE THREAD

**Issue by eremiter** [odoo/odoo#27245]
Impacted versions:odoo10-20170315

Steps to reproduce:

Current behavior:The report cannot show the warehouse address when shipping. What is wrong with this code.

Expected behavior:The report can show the warehouse address when shipping. 

Video/Screenshot link (optional):<div t-if="o.picking_type_id.code != 'internal' and (not o.move_lines or not o.move_lines[0].partner_id) and o.picking_type_id.warehouse_id.partner_id"></div>

**Comment by pedrobaeza** [comment]
The code is correct in my tests, so please specify detailed steps to reproduce the problem (which I still don't know what it is).

**Comment by sswapnesh** [comment]
I have tested same on Latest build and seems working fine.
![n1](https://user-images.githubusercontent.com/16624719/46098190-76383e80-c1e1-11e8-8256-d6cf67e78d42.png)

![](https://image.prntscr.com/image/cjfo6oOHSOeElW2c6OnKtg.png)

So there should be something wrong in the condition you are checking

**Comment by pedrobaeza** [comment]
Closing as confirmed that is working.

**Comment by eremiter** [comment]
What you test is the receipt of the goods. What is wrong is the delivery,Number is WH/OUT
________________________________
hermitweb@hotmail.com

**Comment by eremiter** [comment]
What you test is the receipt of the goods. What is wrong is the delivery,Number is WH/OUT,

  *   Unable to display warehouse address.

<div t-if="o.picking_type_id.code != 'internal' and (not o.move_lines or not o.move_lines[0].partner_id) and o.picking_type_id.warehouse_id.partner_id">
    <span><strong>Warehouse Address:</strong></span>
    <div t-field="o.picking_type_id.warehouse_id.partner_id"
        t-options='{"widget": "contact", "fields": ["address", "name", "phone", "mobile", "fax"], "no_marker": True, "phone_icons": True}'/>

</div>

________________________________
hermitweb@hotmail.com

**Comment by sswapnesh** [comment]
![screenshot from 2018-10-01 23-55-28](https://user-images.githubusercontent.com/16624719/46307774-854e3080-c5d5-11e8-8794-60cc4a13b388.png)
Works well there too.
I will suggest you to check this condition
`<div t-if="o.picking_type_id.code != 'internal' and (not o.move_lines or not o.move_lines[0].partner_id) and o.picking_type_id.warehouse_id.partner_id">`

**Comment by naxiangzi** [comment]
You can tell me your piece of code, my code may have an error

**Comment by sswapnesh** [comment]
I am using same code for address.(Without adding Condition)
