### ISSUE TITLE
[11.0][12.0] Approved leaves will be visible for all internal users, even if you haven't set a meeting type

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#27248]
Impacted versions:
[11.0][12.0] 

Steps to reproduce:
1. check the sick leave type if a meeting type is linked (you need debug mode).
![image](https://user-images.githubusercontent.com/30628967/46082751-153c4680-c1a0-11e8-8bc5-96b3021b0683.png)

2. Create a sick leave and approve it.

3. Log in as another user with very little rights (like only user rights for timesheets).

4. Check the calendar view and select the list view.
You will find here all the approved leaves.
![image](https://user-images.githubusercontent.com/30628967/46082847-56ccf180-c1a0-11e8-91b4-6bdc13c782f7.png)

Expected behavior:
Sick leaves contains sensitive information and should not be available for all the internal users. As a regular employee you dont want to find out that someone has been sick so many times during a year. Please hide this information when you don't link a meeting type to the leave type.

Video/Screenshot link (optional):

**Comment by tivisse** [comment]
Hello,

I don't know if we will fix this in a stable release, but this issue is valid for the newest version. I've opened an internal task to decide how we will fix this.

Regards,

Yannick.

**Comment by Yenthe666** [comment]
@tivisse could you be so kind to reference the ticket number here? I bet some day somebody will come back here and be like "but which ticket" 😄

**Comment by tivisse** [comment]
https://www.odoo.com/web#id=2167996&action=333&active_id=1251&model=project.task&view_type=form&menu_id=4720
