### ISSUE TITLE
[11.0] base: access_token is restricted to backend users, when needed by portal ones

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#27256]
**Impacted versions:**
11.0

**Steps to reproduce:**

- Create a portal user
- Define a project with Privacy = "Visible by following customers"
- Add the portal partner as follower of the project.
- Create a task in that project.
- Add an attachment to that task.
- Login with the portal user.
- Go to the task in the portal.

**Current behavior:**

You get a 500 error, due to permissions on `access_token` field:
```
odoo.models: Access Denied by ACLs for operation: read, uid: 118, model: ir.attachment, fields: access_token
```

This is due to this portal QWeb template accessing that field:

https://github.com/odoo/odoo/blob/09340bb7f0da35cc69e24f16e5262ec4825bc0c6/addons/project/views/project_portal_templates.xml#L214

but the field is restricted to backend users:

https://github.com/odoo/odoo/blob/09340bb7f0da35cc69e24f16e5262ec4825bc0c6/odoo/addons/base/ir/ir_attachment.py#L293

Token was added by @xmo-odoo in https://github.com/odoo/odoo/commit/a3cd0ac2ceaa25cc7ddbbb38e33a43726a0c7ac7

**Expected behavior:**

Everything goes well.

cc @Tecnativa

**Comment by pedrobaeza** [comment]
@xmo-odoo maybe you can check this side effect.

**Comment by kebeclibre** [comment]
closed with https://github.com/odoo/odoo/commit/fee419c7ea0f04b73d0c4fcd0ab0a3e51a0c3b80
