### ISSUE TITLE
[12] Could not close sidebar in calendar view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27266]
Impacted versions: 11.5

Steps to reproduce: Try to close Calendar sidebar

![](https://image.prntscr.com/image/mC6DkRqoQAaag1LthLbs4Q.png)

Current behavior:
Nothing Happens
Expected behavior:
Should be closed
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Not sure but I remember this was working fine in v11. (or maybe that was v10)

**Comment by sswapnesh** [comment]
@Yenthe666 
Seems working fine in v11 (Tested on Latest [Build]( http://379011-11-0-d61a24.runbot17.odoo.com/web#view_type=calendar&model=calendar.event&action=178))
![c5](https://user-images.githubusercontent.com/16624719/46159362-c8d73080-c29d-11e8-8c3e-9c7affd630ec.png)

**Comment by Yenthe666** [comment]
Not in enterprise hehe.

**Comment by sswapnesh** [comment]
Yup, I realised this just after added comment and Edited same.

**Comment by sswapnesh** [comment]
Same in v12.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/33570/commits/ee38015143c98c878d394942df9a2655a3e18302
