### ISSUE TITLE
[website_blog] : traceback throws when duplicating blog post from website.

### ISSUE THREAD

**Issue by sus-odoo** [odoo/odoo#2726]
affected version : 8.0, master

see image to reproduce traceback.

![blog post_click_duplicate](https://cloud.githubusercontent.com/assets/7599685/4419144/7257e9dc-4567-11e4-9556-3c863d24e8d0.png)

![403 error](https://cloud.githubusercontent.com/assets/7599685/4419165/a396c496-4567-11e4-96fc-ad66184afef6.png)

**Comment by Yenthe666** [comment]
Hi @sus-odoo,

Thank you for the report. 
It has been fixed by https://github.com/odoo/odoo/pull/2770/commits/2da1bdc1742b87f2bd415364ad93ffcf7fa229c2 a while ago but this issue was never closed. Closing as it is handled.

Regards,
Yenthe
