### ISSUE TITLE
[11.5] Could not create all day event

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27265]
Impacted versions: 11.5

Steps to reproduce: Create All day Event

![](https://image.prntscr.com/image/Sl6gpjQETGSPvv1Y25y0iA.png)

Current behavior:
![screenshot from 2018-09-27 00-18-12](https://user-images.githubusercontent.com/16624719/46101974-da133500-c1ea-11e8-8062-03cbcb9708be.png)

Expected behavior:
Able to Create Event
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e this looks related to the `DateTime` changes I assume. Source code that gives issue:
https://github.com/odoo/odoo/blob/2d8269264897211e2b335f3f8134749da567dc27/addons/calendar/models/calendar.py#L878
Maybe we can make one big thread for 11.5 issues by the way?

**Comment by mart-e** [comment]
Fixed at 2c26fc0e862

>  Maybe we can make one big thread for 11.5 issues by the way?

No please, while we appreciate the testing, still consider the saas-11.5 an unstable version, same as the master version. It is still changing very fast. PR welcome though.

**Comment by sswapnesh** [comment]
Thanks, Will wait for official Release.
