### ISSUE TITLE
[saas-11.5] Could not open Sales Teams

### ISSUE THREAD

**Issue by murtuzasaleh** [odoo/odoo#27276]
Impacted versions: 11.5

Steps to reproduce: Install sales_team (or sale management) module --> Open Sales Team

![main_menu](https://user-images.githubusercontent.com/20418904/46139061-2f8f2680-c26b-11e8-9914-50e86a84b94b.png)

Current behavior:  ![sales_team](https://user-images.githubusercontent.com/20418904/46139112-4afa3180-c26b-11e8-87aa-bd6fda09cb62.png)

Expected behavior: Should be able to see Sales teams

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Thanks, fixed at 099092ab812

@murtuzasaleh as a reminder the saas-11.5 (which is NOT a 11.5) is not a stable version. consider it as the master version, things break and change often.
