### ISSUE TITLE
[stock] The value of the scrap move is wrong

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#27283]
Impacted versions:
11.0
Steps to reproduce:
1. create an product `Product A` and cost method is `Standard Price`.
1. create an PO for this product and  confirm the PO.
1. validate shippment.
1. scrap this product.

Current behavior:

The `value` of the scrap `stock move` is wrong. It become `cost  * quantity + purchase price * quantity`

Expected behavior:

The `value` of the  scrap `stock move ` is `cost  * quantity`

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Closing as there's a related PR. Next time, you can put the issue report directly on the PR.
