### ISSUE TITLE
[11] not logging failed tries for master password in database manager

### ISSUE THREAD

**Issue by KNiewiadomski-uAvionics** [odoo/odoo#27292]
Impacted versions:11

Steps to reproduce:
/etc/odoo.conf:
 ...
 logfile = /var/log/odoo/odoo-server.log
 ...

(Tried in CentOS7 with nginx proxy, IP addresses of failed logins to user interface are logged OK)

Try wrong master password in database management page (/web/database/manager) for:

  subissue 1:
    delete, duplicate, create, set master password
      Current behavior:
        no information in log
      Expected behavior:
        information in log with IP address for fail2ban

  subissue 2:
   restore
      Current behavior:
        no information in log, uploading file to server
      Expected behavior:
       information in log with IP address for fail2ban, not uploading file to server

  subissue 3:
    backup
      Current behavior:
        error in log without IP address
      Expected behavior:
        information in log with IP address for fail2ban

**Comment by pedrobaeza** [comment]
Look for "fail2ban odoo" in Google. Example: https://www.odoo-consultants.com/2016/12/28/odoo-security-with-fail2ban/

Closing as no real issue.

**Comment by mart-e** [comment]
Also, check our deployment guidelines, especially the security section where we advise to [disable the database manager](https://www.odoo.com/documentation/11.0/setup/deploy.html#db-manager-security) for production.
