### ISSUE TITLE
stock: 'All products' in inventory adjustment does not filter some consumables or archived products

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#27302]
### Impacted versions:
All

### Steps to reproduce:
- Create an inventory adjustment with 'All Products'

### Current behavior:
- It brings non-stockable products that had quants in the past which raises:
https://github.com/odoo/odoo/blob/46f2e1918fc6e135b1c82af19a13f9cb01c81470/addons/stock/models/stock_inventory.py#L407
- It brings archived products which could be wrongly configured or with other conditions that caused their *archived* status.

### Expected behavior:
- When selecting 'All Products', just filter non-archived & stockable products.

**Comment by gustavovalverde** [comment]
I actually tried a PR there, but that code is _wicked_ 😄

**Comment by gustavovalverde** [comment]
Closed by https://github.com/odoo/odoo/commit/9cf22e5ef6e3e5f28b10d9be37a2c04b77785c0b

**Comment by Ark74** [comment]
I've noticed that products that are consumable and were adjusted before this patch, keep appearing on the Inventory Adjustments.

Have you seen that too?

**Comment by gustavovalverde** [comment]
If those products are **Active** I think they do.

**Comment by Ark74** [comment]
So in order to fully get the patch in place all previous consumable products (with previously inventory adjustments records) should be replaced by new ones without Inventory Adjustment history, so they don't keep appearing and any other new product by default will follow the new rules in place.

Did I got it right?
