### ISSUE TITLE
[IDEA] multicompany-multilocalization: Have menus selectable by country

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#27315]
Impacted versions:

master

Steps to reproduce:

Develop any menu/field that is only valid in a country.

Current behavior:

No possible to, using any api to hide/show fields/menus per country. 

Expected behavior:

We need to have the posibility to show/hide fields using an api with something like.

```
<menuitem ..
country="MX"
...>
```

These show hidden by country.

```
l10n_xx_fields_name = fields.TYPE(country="MX")
```

This is a proposal, may be it is a better way, for example we have already sort kind of management per country in the addresses (which is not as simplistic as this is) but I hope it gives a point.

**Comment by sswapnesh** [comment]
> No possible to, using any api to hide/show fields/menus per country.

and also Better to have way to display menus based on User's company. (Not sure If it is already there).
```
<menuitem ..
company="xml_id" or (any other field) 
...>
```

**Comment by ivantodorovich** [comment]
You can achieve it by creating user groups, and assign them according to the user's country
