### ISSUE TITLE
Translation broken when html/xml removed

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#27311]
Impacted versions:

saas-11.5

Steps to reproduce:

**example:** Install spanish and then swich your user to spanish, try to open Account main menu with just account_accountant installed.

Current behavior:

Traceback.

![imagen](https://user-images.githubusercontent.com/338634/46246333-3ac58c00-c3fc-11e8-9111-7e2062bdff17.png)

Expected behavior:

No traceback.

**solution**

We actually conrrected the transifex text with the erroneous element but some things pops out here:

1. An html string is sent to transifex which is not correct in the context of send just the text part.
2. No checking such translations that should comply with the original structure are bringing back again the problem we had when we allow placehold things into the string.

cc @mart-e thanks.

**Comment by moylop260** [comment]
Is not a regression of https://github.com/odoo/odoo/issues/14497?

**Comment by mart-e** [comment]
Hello,

Does this issue is still valid? As I understand, it is a problem of bad translations that needs to be fixed on Transifex but not really on Odoo side.
I did not know the `--test=xmltags`, thanks for the share

**Comment by mart-e** [comment]
By the way, you can check #33220 where I add a check to detect bad translations
