### ISSUE TITLE
[10.0] Incorrect currency in partner credit field.

### ISSUE THREAD

**Issue by jvargass** [odoo/odoo#27339]
Impacted versions: 
10.0 enterprise

Steps to reproduce:
Multi-company environment.
Two different companies (No childs): One Spanish and another English.
Partners associated to companies do not have established a company because we doing sales between them. So, the credit field in partner view does not show the correct currency (amount is ok). 

Current behavior:
The credit field in partner view does not show the correct currency (amount is ok). 

Expected behavior:
Correct currency without selected a company field in partner.

**Comment by jvargass** [comment]
Any news?

**Comment by oco-odoo** [comment]
Hi @jvargass , 

I am not sure I understand your issue; could you give more details about it? Since it's quite old, maybe has it been fixed since then?

**Comment by jvargass** [comment]
Hi @oco-odoo,

Thanks for answering, but yes, it has been fixed since then.
I'm gonna close this issue.
Thanks again.
