### ISSUE TITLE
[12] Document set of module with differnt signatures for the same method

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#27356]
<img width="990" alt="imagen" src="https://user-images.githubusercontent.com/338634/46290823-2c5aaa00-c58d-11e8-9132-adb2f4950dfd.png">

**Comment by ThanhDodeurOdoo** [comment]
Thanks, it will be changed this morning

**Comment by ThanhDodeurOdoo** [comment]
https://github.com/odoo/enterprise/pull/2765
