### ISSUE TITLE
Images in static not loading

### ISSUE THREAD

**Issue by sufianetaouil** [odoo/odoo#27350]
Impacted versions: 11

Steps to reproduce:
I'm trying to simply display a logo on my website, this is my current code : 
`<?xml version="1.0" encoding="utf-8" ?>
<odoo>
	<template id="custom_header" inherit_id="website.layout" name="Custom Header">
		
		<xpath expr="//div[@id='wrapwrap']/header" position="replace">
							<div class="logo">
		<a href="#" class="w-inline-block">
                    <img src="/theme_custom/static/src/img/kd_logo.png" class="logo-hover" width="100%" />
                </a>
							</div>
</odoo>
`

CSS are in the static folder as well, but they are loaded from different URL, e.g: 
http://localhost:8069/web/content/244-5fb8a70/web_editor.assets_editor.0.css

But for images, It's trying to load them from the same path I specify, e.g: 
http://localhost:8069/theme_custom/static/src/img/kd_logo.png

Current behavior: 404 NOT FOUND

Expected behavior: 200 OK

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
