### ISSUE TITLE
[saas-11.5] Integrity error due to retro-incompatible constraint for translations

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#27364]
Impacted versions:
- saas-11.5 (a01c1bf5bf377471c1c0fb31a20b59fc116fd545)

Steps to reproduce:
- Install a bd without this change: https://github.com/odoo/odoo/commit/7288b4779a83a04617d4f22a22bdd8edfd22e04f#diff-a41938cd3ff4c7e353103fcd581f839aR274
- Install Spanish translations
- Update branch
- run `-u all`

Current behavior:
Since there are already records that don't meet the SQL constraint introduced on the above change, errors like the following are raised:

```
psycopg2.IntegrityError: could not create unique index "ir_translation_code_unique"
DETAIL:  Key (type, lang, md5(src))=(code, es_MX, c9cc8cce247e49bae79f15173ce97354) is duplicated.
```

Expected behavior:
No errors should be raised.

**Comment by luisg123v** [comment]
CC @yaniaular, @dsabrinarg  & @nhomar

**Comment by mart-e** [comment]
Hello,

Thank you for the report but the saas-11.5 is NOT a stable version, it will be the future v12 but it is not yet. Expect unstable changes (well hopefully not many anymore).
We do make incompatible changes, that is the point of the development version.
