### ISSUE TITLE
[Saas-11.5] Invalid XML Id for models/fields

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27363]
Impacted versions: Saas-11.5

Steps to reproduce: 
Find `XML ID` of field
![screenshot from 2018-10-02 00-22-52](https://user-images.githubusercontent.com/16624719/46309228-618ce980-c5d9-11e8-8d8b-926ea3333e9f.png)

Current behavior:
![screenshot from 2018-10-02 00-23-37](https://user-images.githubusercontent.com/16624719/46309248-710c3280-c5d9-11e8-8024-5c2c4dd2ad6f.png)

Expected behavior:
![screenshot from 2018-10-02 00-24-00](https://user-images.githubusercontent.com/16624719/46309266-7d908b00-c5d9-11e8-9755-057d1e30f2e0.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Models too
![52](https://user-images.githubusercontent.com/16624719/46309437-f8f23c80-c5d9-11e8-8916-ba99a8b30dbd.png)

**Comment by mart-e** [comment]
Fixed at 718b0f8b632, thanks
