### ISSUE TITLE
[11.0] Employee: can't retrieve the bank account number.

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#27368]
Impacted versions:
11.0
Steps to reproduce:
Open an employee form.
Create a bank account number and save.
Remove the bank account number.
Try to retrieve the bank account number.
Current behavior:
Impossible to retrieve it because of the field's domain [('partner_id', '=', address_home_id)]. If I try to create a new number, I got an error : "Account Number must be unique".
Expected behavior:
The bank account number should appear in the list.
Video/Screenshot link (optional):
![vid](https://user-images.githubusercontent.com/25034353/46338029-5a90c600-c62f-11e8-8cc3-94dd0ff48def.gif)

**Comment by pedrobaeza** [comment]
But the error is that the account number already exists, so you have to remove the other bank account.

Closing as no real issue.

**Comment by Linekio** [comment]
But the number should be appear in the dropdown list. It works like this on 10.0.
