### ISSUE TITLE
Automated action new record

### ISSUE THREAD

**Issue by alielgarhi** [odoo/odoo#27372]
![checkvendor](https://user-images.githubusercontent.com/18075367/46340456-bb230180-c635-11e8-98ab-d8ca59fc8f8d.jpg)

for V 11 community i made this auto action for check if there is vendor for product or not and created a model to create record in it  it record in the model but record 15 record with 15 id

**Comment by pedrobaeza** [comment]
I don't get the problem...

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
