### ISSUE TITLE
[12] Could not perform "Save & New" on o2m field

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27409]
Impacted versions: 12

Steps to reproduce: Got To Sales --> Add an Item --> Select Product --> Save & New
![129](https://user-images.githubusercontent.com/16624719/46438117-a8661500-c77a-11e8-9d01-93c0eef7cdec.png)
Current behavior:
![130](https://user-images.githubusercontent.com/16624719/46438147-bae04e80-c77a-11e8-90fd-ea8092abf04f.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This requires to have sale line not editable (for popping up the form view) - for example, enabling product packaging -.

**Comment by sswapnesh** [comment]
Yes but this is the case for Each non editable o2m.

**Comment by pedrobaeza** [comment]
This seems then important, @ged-odoo

**Comment by dorcyv** [comment]
Any updates ?

**Comment by andrius-preimantas** [comment]
Anything?

**Comment by ged-odoo** [comment]
the issue comes from https://github.com/odoo/odoo/commit/8e5156938a9c87b80512bff9ecd025891406e624 I think.  
@len-odoo is working on a fix for this. Here is the PR: https://github.com/odoo/odoo/pull/28441
It should be merged very soon.

**Comment by Yenthe666** [comment]
Exact commit is https://github.com/odoo/odoo/commit/45bc7c92f804c0e2329eadf62043742f6986aa47
