### ISSUE TITLE
[8.0] product.template.product_uom not taken as default for mrp.bom and mrp.bom.line via XMLRPC

### ISSUE THREAD

**Issue by scosist** [odoo/odoo#2740]
When creating a BOM via the web interface and selecting a product for `mrp.bom` and `mrp.bom.line` the `product_uom` field is updated for each based on the `uom_id` contained in the respective `product_template`. When importing data to 'mrp.bom' and 'mrp.bom.line' via XMLRPC, if the product_uom is not specified it does not appear to use the `uom_id` from the respective product. Perhaps, this is just the nature of a difference in using the web interface vs XMLRPC but I mention it here because I think it may be unintended behavior.

I just merged the latest changes from the 8.0 branch with my working copy last night.

**Comment by Yenthe666** [comment]
Hi @scosist,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
