### ISSUE TITLE
[12] Could not copy error from Screen

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27408]
Impacted versions: 12 (Both Versions)

Steps to reproduce:
![128](https://user-images.githubusercontent.com/16624719/46437780-c8e19f80-c779-11e8-8fc2-016751b4c3ee.png)

Current behavior: Doesn't Copy anything

Expected behavior: Copy Detailed error

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Works well here
![131](https://user-images.githubusercontent.com/16624719/46438459-87ea8a80-c77b-11e8-8767-b1abd8ecd6ad.png)

**Comment by technicomp** [comment]
Same here - Cope the full error to clipboard doesn´t work in Enterprise Version 12

**Comment by Yenthe666** [comment]
Hi guys,

Just rechecked and works fine now.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
I (Chrome Browser: Version 69.0.3497.100 (Official Build) (64-bit)) can Reproduce Same on Latest Runbot (Community).
http://381034-12-0-23bec7.runbot17.odoo.com/web

**Comment by Yenthe666** [comment]
Yeah, scratch this. ENT.

**Comment by sswapnesh** [comment]
Didn't worked on Latest Enterprise version too.
http://381070-12-0-46a482.runbot15.odoo.com/web?#action=710&active_id=1&menu_id=460
Maybe you were in hurry while testing all these Issues, Just Kidding.&#x1F609;

**Comment by Yenthe666** [comment]
Haha, I have to admit that I rushed them. This is a lesson never to do that 🔨

**Comment by sswapnesh** [comment]
Works well now, Not sure if Related PR is https://github.com/odoo/odoo/pull/28117 or not
