### ISSUE TITLE
[12] No way to Get back to Normal admin user once logged in As Super user 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27402]
Impacted versions: 12

Steps to reproduce: Become Superuser

Current behavior: No way to Get back to Admin user
![12](https://user-images.githubusercontent.com/16624719/46432622-51594380-c76c-11e8-8d45-c87ca8529ef7.png)

Expected behavior: Should be able to get back to the Admin user

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@xmo-odoo  So the Only way to get back to Admin user is Logout and Login again ?

**Comment by janarthanandev** [comment]
It could be better to switch the user instead of logout and login back again
