### ISSUE TITLE
[12.0] Css error, sassc issue

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#27416]
**Impacted versions:**

12.0

**Steps to reproduce:**

Create new database
Tested on arch linux
sassc-3.5.0

**Current behavior:**

css error
`2018-10-04 07:01:48,211 1830 WARNING odoo12 odoo.addons.base.models.assetsbundle: Error: 2.375rem isn't a valid CSS value.
        on line 445 of addons/web/static/lib/bootstrap/scss/_variables.scss
>> $input-height-inner:                    ($font-size-base * $input-btn-line-h
   ----------------------------------------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/lib/tempusdominus/tempusdominus.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /web_settings_dashboard/static/src/scss/dashboard.scss 
2018-10-04 07:01:48,313 1830 INFO odoo12 werkzeug: 127.0.0.1 - - [04/Oct/2018 07:01:48] "GET /web HTTP/1.1" 200 - 301 0.148 0.489
`

**Expected behavior:**

no css error

**Comment by ashish-webkul** [comment]
For the compilation of *.scss extension file, you need to install sass library
apt install python-sass

**Comment by pedrobaeza** [comment]
This is a deployment issue. Check new requirements. Closing as no valid.

**Comment by grzekru** [comment]
This issue is connected with arch linux.
Resolved this with: sudo trizen -S python-libsass
Packages with main repository do not work.
