### ISSUE TITLE
[12]  Error on field image on tree view with widget="image"

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#27411]
**Impacted versions:**
12
**Steps to reproduce:**
Add any field image on tree view with widget="image", raise error 
![image](https://user-images.githubusercontent.com/7775116/46438460-6f637b80-c74d-11e8-9089-458e0cdf2d0c.png)

tecnichal info: field name with problem is [__last_update](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/fields/basic_fields.js#L1461)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo issue for your team in V12, issues with the widget.

**Comment by celm1990** [comment]
Fixed in #27545
