### ISSUE TITLE
[12] Wrong Edition

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#27414]
Impacted versions: 12

Steps to reproduce: Settings

Current behavior: Enterprise Edition

Expected behavior: Enterprise Edition -> Community Edition and remove "Database expiration: Invalid date"

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/40818338/46453021-500a3400-c7c9-11e8-8929-a2ab54cdf73a.png)

**Comment by Yenthe666** [comment]
@mart-e this one is probably best for you.

**Comment by celm1990** [comment]
See PR  #27403

**Comment by celm1990** [comment]
solved in 811c5d894e92c851da1d703c649f407357f369b4 and #27442
@dhamedic Can you tested with lasted code and close issue

**Comment by mart-e** [comment]
Should be fixed now :)
