### ISSUE TITLE
[12] Issue with widget="timezone_mismatch"

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27410]
Impacted versions: 12

Steps to reproduce:
Go to Users or Edit Preference 

Current behavior:
![132](https://user-images.githubusercontent.com/16624719/46438746-50c8a900-c77c-11e8-9e53-3f31e0320085.png)
Expected behavior:
![133](https://user-images.githubusercontent.com/16624719/46438817-82da0b00-c77c-11e8-8508-c09692b2aeb0.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Solved in #28108
