### ISSUE TITLE
[12.0] libsass version

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#27424]
Odoo web client fails to load when using python 3.7 (and maybe 3.6) because libsass fails to load a cython link

I think that this is related to the python version. If I install the latest libsass version, the web client loads currently. This can be fixed using a condition in requirements.txt.

Impacted versions:12.0

Steps to reproduce:
Run Odoo on python 3.7 with libsass from requirements.txt (0.12.3) and open the web client

Current behavior:
libsass fails loading due to missing link in cython

Expected behavior:
Load Odoo Web client

Video/Screenshot link (optional):
![screenshot from 2018-10-04 11-04-03](https://user-images.githubusercontent.com/8062666/46467298-4aaaea80-c7c5-11e8-98c5-241fdd362f51.png)

**Comment by pedrobaeza** [comment]
Closing as there's a PR.
