### ISSUE TITLE
[v8] export - import compatible - must encode res_id (example mail_messages)

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2743]
to be import compatible all "model:res_id" occurrences must be encoded.
currently res_id refers to the id of the export DB . (which is wrong)
but must refer to the target id during import using the  **export**.<model>_<id>
mechanism (external references)

at best it produces error messages, because the the target id does not exist
but it might also link to wrong resources

[related_model_res_id.ods | uploaded via ZenHub](https://files.zenhub.io/5426ca891bf73b532875b2e1)

**Comment by Yenthe666** [comment]
Hi @ferdiga,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
