### ISSUE TITLE
[12] Issue with class alert/alert-info

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27435]
Impacted versions: 12

Steps to reproduce: Inactive User (or add content with this class )

Current behavior: Button to Active User is not Visible 
![133](https://user-images.githubusercontent.com/16624719/46487241-2bd84280-c81d-11e8-849e-75f96b7ecd8a.png)

Expected behavior:
Button Should be visible
![134](https://user-images.githubusercontent.com/16624719/46487332-60e49500-c81d-11e8-86d3-1a8d14d1893f.png)

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
@qsm-odoo looks like the bootstrap 4 now uses a position relative for the `.alert`

**Comment by sswapnesh** [comment]
Hello @qsm-odoo 
I am able to Reproduce same on latest Runbot build http://382945-12-0-32cfa6.runbot19.odoo.com/web?#id=7&action=68&model=res.users&view_type=form&menu_id=4
![screenshot 4](https://user-images.githubusercontent.com/16624719/46757234-32682d80-cce7-11e8-80ad-34a547edf9c8.png)

Cc: @mart-e

**Comment by qsm-odoo** [comment]
@sswapnesh Yes, sorry, my previous bug fix was not enough. A new PR is being merged with, hopefully, the right fix.

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/c7f72248a9619a38cf91d8d35a10dc94b0c7e5a5

**Comment by qsm-odoo** [comment]
Modifying the view to achieve this would break the enterprise version (as nothing can go before the button box there). So the only solution to achieve this in community and leave the enterprise version as it is is JS code, which is not something we will do for now, and especially not in a stable version.
