### ISSUE TITLE
[12] Scroll bar should not be Printed on Traceability Report PDF

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27438]
Impacted versions: 12

Steps to reproduce: Print  Report
![140](https://user-images.githubusercontent.com/16624719/46489280-9b046580-c822-11e8-9742-1267cdf99c7f.png)

Current behavior:
![screenshot from 2018-10-04 22-11-44](https://user-images.githubusercontent.com/16624719/46489241-82944b00-c822-11e8-837f-f580dc29f696.png)

Expected behavior:
Scrollbar should not be there.
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Updated Label (y).
I thought Screenshot would help as Menu/Action is clearly visible there.

**Comment by Yenthe666** [comment]
Yeah it does, thanks a lot 👍

**Comment by sle-odoo** [comment]
Closing this one since the linked pr is merged.
