### ISSUE TITLE
[12] Could not print Bom Structure(or cost) Report with float quantity

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27437]
Impacted versions:

Steps to reproduce:
![139](https://user-images.githubusercontent.com/16624719/46488712-1c5af880-c821-11e8-8583-09d52c107e8f.png)

Current behavior: ![138](https://user-images.githubusercontent.com/16624719/46488713-1d8c2580-c821-11e8-99da-51b69d009fc6.png)

Expected behavior: Print Report

Video/Screenshot link (optional):

Ps: `print` --> `Print` , `print unfolded` --> `Print Unfolded` would have been better.

**Comment by sswapnesh** [comment]
I don't know the Reason behind this warning in odoo log while generating any PDF.

`2018-10-04 16:43:52,569 3736 WARNING 12 odoo.addons.base.models.ir_actions_report: wkhtmltopdf: b'QSslSocket: cannot resolve CRYPTO_num_locks\nQSslSocket: cannot resolve CRYPTO_set_id_callback\nQSslSocket: cannot resolve CRYPTO_set_locking_callback\nQSslSocket: cannot resolve sk_free\nQSslSocket: cannot resolve sk_num\nQSslSocket: cannot resolve sk_pop_free\nQSslSocket: cannot resolve sk_value\nQSslSocket: cannot resolve SSL_library_init\nQSslSocket: cannot resolve SSL_load_error_strings\nQSslSocket: cannot resolve SSLv3_client_method\nQSslSocket: cannot resolve SSLv23_client_method\nQSslSocket: cannot resolve SSLv3_server_method\nQSslSocket: cannot resolve SSLv23_server_method\nQSslSocket: cannot resolve X509_STORE_CTX_get_chain\nQSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf\nQSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf\nQSslSocket: cannot resolve SSLeay\nQSslSocket: cannot call unresolved function CRYPTO_num_locks\nQSslSocket: cannot call unresolved function CRYPTO_set_id_callback\nQSslSocket: cannot call unresolved function CRYPTO_set_locking_callback\nQSslSocket: cannot call unresolved function SSL_library_init\nQSslSocket: cannot call unresolved function SSLv23_client_method\nQSslSocket: cannot call unresolved function sk_num\nQSslSocket: cannot call unresolved function CRYPTO_num_locks\nQSslSocket: cannot call unresolved function CRYPTO_set_id_callback\nQSslSocket: cannot call unresolved function CRYPTO_set_locking_callback\n' 
`

**Comment by Yenthe666** [comment]
@sswapnesh this one looks fixed in the meanwhile already too. Can you test again?

**Comment by sswapnesh** [comment]
No new commit is there, So Problem should exists.
Checking this again.

**Comment by sswapnesh** [comment]
Try to Print Report With any Float value (I missed to mention this earlier)
![peek 2018-10-05 16-45](https://user-images.githubusercontent.com/16624719/46532379-23841400-c8be-11e8-9b72-64fca067a254.gif)

**Comment by Yenthe666** [comment]
Got it, thanks for the clear info! Confirmed. We shouldn't be able to enter float values here honestly.
@sle-odoo

**Comment by sswapnesh** [comment]
I don't think so, Float Values works fine and Values are Updated on screen are correct but it is converting into `int` on report.

> doc = self._get_pdf_line(bom_id, product_id=product_variant_id, qty=int(data.get('quantity')), child_bom_ids=json.loads(data.get('childs')))

So replacing this should work fine. `qty=int(data.get('quantity'))` --> `qty=data.get('quantity')`

**Comment by Yenthe666** [comment]
@sswapnesh why not make a PR with the suggestion though? 👍

**Comment by sswapnesh** [comment]
@Yenthe666 #27464 &#x1F609;

**Comment by amoyaux** [comment]
@sswapnesh Okay about it, but you are not suppose to be able to use float number in a type="number". How did you proceed?
