### ISSUE TITLE
[12] Upgrade Button for Enterprise App is Confusing when app is not Installed

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27439]
Impacted versions:12

Steps to reproduce: Open Any App which not installed

Current behavior: It shows `Install` and `Upgrade` which maybe confusing.
![141](https://user-images.githubusercontent.com/16624719/46490172-e61f7800-c824-11e8-86f8-1cbe9d92d615.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by jlzhou** [comment]
And no space between the 2 buttons.

**Comment by Yenthe666** [comment]
@mart-e I believe we should add some spacing & an if statement to check if the module is installed or not.

**Comment by sswapnesh** [comment]
This Upgrade button is not to upgrade installed module, it is for upgrade to enterprise version. So maybe changing label would also work.

**Comment by Yenthe666** [comment]
Ahh, I was confusing it with updating the module. Hmm we have a better enterprise label for that, don't we?

**Comment by sswapnesh** [comment]
Adding that Icon in the Button will do the Job.
Thank You

SWAPNESH SHAH <http://github.com/sswapnesh>

PHONE:-+91-8128104500 <http://www.facebook.com/sswapnesh>

**Comment by sswapnesh** [comment]
Would be good to have new Button (or Enterprise Upgrade Widget) in future versions

**Comment by sswapnesh** [comment]
Looks like this has been fixed in https://github.com/odoo/odoo/pull/41290

Cc @mart-e

**Comment by Yenthe666** [comment]
Indeed, that should be fine now :)
