### ISSUE TITLE
[v8] left menu bar - option to hide

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2744]
specially on small devices the left menu bar must hide immediately. it takes 50% of the width of the screen in portrait mode on a phone making it unusable.

IMO v6 option was perfect - either pull down from top or permanently open on the left side

**Comment by nguyenbs** [comment]
Vote +1

**Comment by pedrobaeza** [comment]
This has been implemented on the enterprise interface. You also have OCA module web_responsive or other community modules for doing so, so closing this.
