### ISSUE TITLE
[12] hr_holidays - Leaves left ignores Leave type (Fixed, no allocation)

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#27441]
Impacted versions:

12.0

Steps to reproduce:

For example:
Add 10 days to Legal Leaves 2018
Take 5 days from Legal Leaves 2018 (fixed)
Take 5 days from Sick Leaves (no allocation)
Leaves left in HR view show 0 days left, but there are still 5 days left in Legal Leaves 2018

Current behavior:

O days left in HR view

Expected behavior:

5 days left, maybe also count all leaves that are not refused.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/5862658/46498207-106d3780-c81d-11e8-8002-08d70dade9ba.png)
![image](https://user-images.githubusercontent.com/5862658/46498220-1bc06300-c81d-11e8-8e69-51d19ed9fe1d.png)

**Comment by grzekru** [comment]
It also ignores Leave type Validity date

**Comment by Yenthe666** [comment]
@tivisse maybe one for you in the new V12? 😉

**Comment by RomainLibert** [comment]
Should be fixed by that https://github.com/odoo/odoo/pull/28951
