### ISSUE TITLE
[12] Cannot read property 'decorations' of undefined

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27440]
Impacted versions: 12 (Aall apps are Installed)

Steps to reproduce: Go to `Settings` --> `General Settings` (Or Open Any settings)

Current behavior:
![142](https://user-images.githubusercontent.com/16624719/46490660-3814cd80-c826-11e8-9e98-58f752c4a19f.png)

Expected behavior:
Open General Settings
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks for the report!
I've just tried it on the latest 12.0 but it already looks fixed. Can you try again & confirm please?

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Hello @Yenthe666 
I am able to Reproduce Same on http://381034-12-0-23bec7.runbot17.odoo.com (All apps except l10n_lu are installed)
![peek 2018-10-05 17-44](https://user-images.githubusercontent.com/16624719/46534622-6813ad80-c8c6-11e8-9bc3-4361452881a2.gif)

**Comment by Yenthe666** [comment]
Video's help a lot. Confirmed that it is a bug :)
@ged-odoo can one of the guys check?

**Comment by sswapnesh** [comment]
Indeed Videos help, Next time I will try to add more detailed description.
