### ISSUE TITLE
[12] Portal / Project - Create message error

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#27458]
Impacted versions:

12.0

Steps to reproduce:

Create project with tasks
Create portal user and add him to project
Log in into portal website
Go to task
Try to write a message
Error

**Comment by sswapnesh** [comment]
Hello @grzekru 
I am not Able to Reproduce Same on latest v12 community.
Assigned Task to Portal user:
![91](https://user-images.githubusercontent.com/16624719/46567527-d8b3dc00-c951-11e8-98ac-c2a8a41f3730.png)


Portal user is able to Post message:

![90](https://user-images.githubusercontent.com/16624719/46567528-d9e50900-c951-11e8-9fe9-bb43dffb1160.png)


Would be great If you can add more steps to Reproduce Including Screenshots/Error message.

**Comment by Yenthe666** [comment]
Hi @grzekru,

Thanks a lot for the report! I've just tested it and it does seem to work now.
Can you try again on the latest 12.0 and let us know if you still face it (and possible a video).

Regards,
Yenthe

**Comment by grzekru** [comment]
@sswapnesh @Yenthe666 
Video showing both errors
https://youtu.be/hIPaPqgmitk

**Comment by sswapnesh** [comment]
There is PR  #27455 for the Access error you showed at https://youtu.be/hIPaPqgmitk?t=139

**Comment by jpr-odoo** [comment]
Hi @grzekru,
I've just tested it and it's working fine. thanks for the report
