### ISSUE TITLE
[12] Could not install l10n_lu module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27450]
Impacted versions: 12 Community Version

Steps to reproduce: Install `l10n_lu` module
![555](https://user-images.githubusercontent.com/16624719/46533999-4b767600-c8c4-11e8-90d1-30a3204b6cb3.png)

Current behavior: Loading data will be failed as model `account.financial.report` is not available in Odoo v12
Related commit: https://github.com/odoo/odoo/commit/e51b4f659fc5e4253d3156754ada21166c8d1bf8#diff-4a962261ce05b063353461d94ca14a38L12

Expected behavior:

Video/Screenshot link (optional):

Ps: Maybe We can handle this by removing data file 
`account_financial_report_data.xml` and` account_financial_report_abr_data.xml`

@StefanRijnhart Pinging you as I found your latest commit there.

**Comment by StefanRijnhart** [comment]
@sswapnesh sorry,I only detected a duplicate XMLID in this module when I was bootstrapping OpenUpgrade for all addons and proposed a fix, but I am not involved in the LU localization.

**Comment by StefanRijnhart** [comment]
No problem ;-)

**Comment by sswapnesh** [comment]
Resolved in https://github.com/odoo/odoo/commit/6329216242e3dc0389b466082a809f983ca704f0
