### ISSUE TITLE
[12] Portal's User Error, can't see your Invoices

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#27454]
**Impacted versions:**
12
**Steps to reproduce:**
Sent by email a document(invoice), user open link and get this error
Note: Customer has not login

![image](https://user-images.githubusercontent.com/7775116/46543042-71455000-c8af-11e8-846e-5f0865f9d4db.png)

![image](https://user-images.githubusercontent.com/7775116/46543056-7aceb800-c8af-11e8-9edf-bbf3df08a161.png)

Aditional, if a Customer grant access to portal, get other error
![image](https://user-images.githubusercontent.com/7775116/46543216-d305ba00-c8af-11e8-885d-70938c1d925f.png)

![image](https://user-images.githubusercontent.com/7775116/46543287-faf51d80-c8af-11e8-9189-7bce867424ce.png)

![image](https://user-images.githubusercontent.com/7775116/46543302-01839500-c8b0-11e8-8938-80ba9c6c483f.png)

Open Invoices and get error

![image](https://user-images.githubusercontent.com/7775116/46543373-342d8d80-c8b0-11e8-98fa-3d6456b6a2e2.png)

**Current behavior:**
Error at see your invoices on portal(Other documents no problem, only with invoices)
**Expected behavior:**
No Error
Video/Screenshot link (optional):

**Comment by celm1990** [comment]
**More Info:**
Log on local machine:
![image](https://user-images.githubusercontent.com/7775116/46543776-422fde00-c8b1-11e8-8876-47de1545b201.png)

[Write is here](https://github.com/odoo/odoo/blob/12.0/addons/portal/models/portal_mixin.py#L33) at generate access_token

**Comment by sswapnesh** [comment]
First error (Not found) is Because of deployment. On Runbot there is no default Db so first select database and try again. (Or apply proper db filter)

**Comment by celm1990** [comment]
Ok, is correct, but second error is related to access right
