### ISSUE TITLE
[12] Account should be required field in invoice

### ISSUE THREAD

**Issue by Dangar-Serpentcs** [odoo/odoo#27451]
Impacted versions: 12

Steps to reproduce:

Go to Invoicing --> Customer --> Invoices --> Create invoice and just Remove account and Click Validate button.

Current behavior:
![invoice](https://user-images.githubusercontent.com/38550879/46535939-93989700-c8ca-11e8-8310-00c86a48bed0.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@qdp-odoo perhaps an extra check / security measure might be neat here.

**Comment by Yenthe666** [comment]
So I can conclude that it is working as intended and won't be changed, right? Closing as answered.
