### ISSUE TITLE
[8.0][eCommerce] Suggested products: Variants are not shown in the cart (instead you just see the template name)

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#2746]
## Impacted versions:
8.0 and above

## Steps to reproduce:
* Create a product variant and add one of them as an "Accessory Products" of another product
* Buy the other product and see the suggested products in the shopping cart

## Current behavior:
* The wrong name (template name) is shown

## Expected behavior:
* Show the correct variant name (display_name)

* Might be related to https://github.com/odoo/odoo/issues/2246 as the product.product.name does give back the product.template name which is to be questioned.

**Comment by dmo-odoo** [comment]
Fixed at https://github.com/odoo/odoo/commit/9fdf06a0f69953eec213458bfbf078e1ef53683b
