### ISSUE TITLE
[12] TypeError: Cannot read property '_isDirty' of undefined on o2m

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27466]
Impacted versions: 12

Steps to reproduce: Open any `m2o` field from `o2m` field
Eg, Open `Product` from `Bom components `and Press `Esc`

Current behavior:
![ki](https://user-images.githubusercontent.com/16624719/46568126-7a8cf600-c95d-11e8-9324-8d888d4e5095.png)

Expected behavior: Back to Original Screen

Video/Screenshot link (optional):
![peek 2018-10-06 11-47](https://user-images.githubusercontent.com/16624719/46568143-c0e25500-c95d-11e8-9aeb-b211cb9a7390.gif)

**Comment by Yenthe666** [comment]
Thanks for the report, I can confirm it is a bug. @ged-odoo another one for the JS team 😉

**Comment by alexkuhn** [comment]
Hello,
This has been fixed in version saas-11.3: https://github.com/odoo/odoo/commit/8445baa08d4f7cdbe60555ef1ff691a37e99d900
This fix will be forward-ported in a few days.
cc @VincentSchippefilt
