### ISSUE TITLE
[12] Question: Which data is Sent to Odoo when we create new Database (12 Community)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27469]
Impacted versions: 12 Community

Create New database 
![screenshot from 2018-10-06 16-45-12](https://user-images.githubusercontent.com/16624719/46570762-37477d00-c987-11e8-8bef-1d526f4499f6.png)
It Mentios:
To enhance your experience, some data may be sent to Odoo online services. See our Privacy Policy. 

What We get on Privacy Page(https://www.odoo.com/privacy)
![2020](https://user-images.githubusercontent.com/16624719/46570793-a58c3f80-c987-11e8-85ee-421989a231b6.png)
It does not include any Information about Odoo Community version
Related Commit: a171694644cf5e58f065cf7ed18fd8d259ea744f

**Comment by Yenthe666** [comment]
@mart-e or @odony can one of you answer? I think the Odoo privacy page is missing some information regarding this.

**Comment by dek-odoo** [comment]
May be it's about "publisher warranty contract" ?

**Comment by ajepe** [comment]
Everything about the collected data is well explained here https://www.odoo.com/privacy and reasons behind it, and what they use it for.

**Comment by sswapnesh** [comment]
This does not include any details about Self hosted v12 community version. (or you can share that content if you find)

**Comment by odony** [comment]
This is about the "In-App Purchase (IAP) Transaction Data" section, and is related to the use of some embedded services that may be active by default even when you install a community edition on-premise. The linked [IAP Privacy Policy](https://iap.odoo.com/privacy) gives you further details on the data collected and processed when you use those various services.

**Comment by Yenthe666** [comment]
That only took 8 months 🤣 Thanks for the feedback Olivier!

**Comment by sswapnesh** [comment]
It's seems it was updated after I asked them on launch Day. (I am sure some some the related content was not there)
Thanks for the Update.
