### ISSUE TITLE
[12] TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'

### ISSUE THREAD

**Issue by kapilpatel-dev** [odoo/odoo#27467]
Impacted versions: 12

Steps to reproduce: Go To CRM -->Sales ---> Team Pipelines 
Than remove "My Favorites" Filter from search.

Current behavior:
![issue](https://user-images.githubusercontent.com/24518821/46568502-c2c6fc80-c8fa-11e8-909e-65fe9796732c.png)

Expected behavior:

Video/Screenshot link (optional):
![ezgif-4-0d8ecfcc93f7](https://user-images.githubusercontent.com/24518821/46568634-eb4ff600-c8fc-11e8-9fda-02d7f991ba77.gif)

**Comment by Yenthe666** [comment]
@mart-e another date conversion issue 😉

**Comment by sswapnesh** [comment]
I am able to Reproduce this on Runbot but not on Local Instance.

**Comment by sswapnesh** [comment]
I am able to Reproduce now, Thats when it loads data for` Point of Sale` team, (Make sure there is at least one pos order)
