### ISSUE TITLE
[12] buttons on tree view not appears

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#27472]
**Impacted versions:**
12
**Steps to reproduce:**
Go to Bank statements, reconcile lines and must be appears button to revert reconciliation

_V11 work fine_
![image](https://user-images.githubusercontent.com/7775116/46572993-69a0ac80-c97e-11e8-9b0f-08f9ed3dbb79.png)

_V12 no buttons_
![image](https://user-images.githubusercontent.com/7775116/46573004-92c13d00-c97e-11e8-9230-edd7729d2c2c.png)

Button is on DOM but not is visible
![image](https://user-images.githubusercontent.com/7775116/46573011-b84e4680-c97e-11e8-87fd-7bc4fd0b1e9d.png)

_Note:_ I tested only on bank statement view, but I think is bug general on all tree views(not sure)

**Current behavior:**
**Expected behavior:**
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Button works well on other Tree views.

**Comment by sswapnesh** [comment]
Added PR #27473 for this.
