### ISSUE TITLE
[12] Could not Edit and Save (load) Calendar event

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27474]
Impacted versions: 12.0

Steps to reproduce: Open http://381109-27468-82809c.runbot20.odoo.com/web?debug#id=32&action=167&model=calendar.event&view_type=form&menu_id=113
[I dont have detailed steps to Reproduce as I just edited Event (id=32) and Clicked on Save after doing changes belowed mentioned]
Current behavior:
![screenshot](https://user-images.githubusercontent.com/16624719/46573400-23fdd700-c9b2-11e8-80c4-8fd83e99c6fb.png)
This change resulted into this error:
![x1](https://user-images.githubusercontent.com/16624719/46573414-48f24a00-c9b2-11e8-9362-f044e74181cc.png)

Expected behavior:
Open Calendar Event
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
After adding id in list View: http://381109-27468-82809c.runbot20.odoo.com/web?debug#action=167&model=calendar.event&view_type=list&menu_id=113
![x2](https://user-images.githubusercontent.com/16624719/46573449-041ae300-c9b3-11e8-8293-1403cb4b4f1e.png)

**Comment by sswapnesh** [comment]
Hello @len-odoo 
This is also happening on v13 (http://652290-13-0-2298ef.runbot23.odoo.com/web?debug=assets#action=169&model=calendar.event&view_type=calendar&cids=1&menu_id=117)
![Screenshot (4)](https://user-images.githubusercontent.com/16624719/66775225-278b3e80-eee1-11e9-88ec-9db63cf76cd1.png)

(Just Create Recurring Calendar Event and try to Read ID)

Do I need to create new Issues for this?

**Comment by len-odoo** [comment]
Hello @sswapnesh 
It's clearly a different error since it's on the JS side. 
Not sure if somebody is working on this, but you can create a new ticket for it.

**Comment by sswapnesh** [comment]
@sswapnesh  I added a comment based on https://github.com/odoo/odoo/issues/27474#issuecomment-427587249
