### ISSUE TITLE
[12.0] regression in at_install/post_install test decorators

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#27471]
Impacted versions: 12.0

It seems we have to do this change to have post_install tests working in 12:
![image](https://user-images.githubusercontent.com/692075/46571636-b8e3de80-c978-11e8-8f85-abe0685a7495.png)

It should be backward compatible, or if that is intended, the old decorator should be removed completely so the change is explicit.

Example in https://github.com/OCA/server-tools/pull/1382

**Comment by Elkasitu** [comment]
[It seems like it is intended](https://github.com/odoo/odoo/commit/b356b190338e3ee032b9e3a7f670f76468965006)

perhaps the other two decorators will indeed be deprecated in the future

cc @d-fence @rco-odoo

**Comment by pedrobaeza** [comment]
@sbidoul I think that as variables inside the class, they are still working. Have you tried?

**Comment by sbidoul** [comment]
@pedrobaeza no I've not tried and I will not. IMO this is a regression that will cause a lot of head scratching. That's why I said these decorators should be removed if they are not meant to be backward compatible.

**Comment by Yajo** [comment]
IMHO it would be even better to actually make them backward compatible, but yes, indeed it's better to remove them than to make them lie.

**Comment by Yajo** [comment]
Fix at https://github.com/odoo/odoo/pull/27531
