### ISSUE TITLE
[12]Website: Remove related website menu on Uninstalling module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27488]
Impacted versions: 12

Steps to reproduce: Uninstall eCommerce module  (or Uninstall--> Re-install)

Current behavior:
Shop Menu is still there on Website (and repeated on Re-Install)
![999](https://user-images.githubusercontent.com/16624719/46585051-372fa600-ca89-11e8-9837-adef4e526e5b.png)
![99](https://user-images.githubusercontent.com/16624719/46585073-7e1d9b80-ca89-11e8-86f3-78d2a32052d8.png)

Expected behavior:
Single menu for Shop (Related module)

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
Hello,
Thanks for reporting the issue,

Indeed we implemented a solution for module installation at https://github.com/odoo-dev/odoo/commit/850e1675eb2550a86729199c1642b4bb381aede3 that creates a default tree menu to be able to replicate it on newly created website.
It also fixed the issue where it would recreate multiple times the menus on -u module installation.

But it was not handling the case of module uninstall (and not at all install after uninstall).

I will do a fix to handle these flows.
