### ISSUE TITLE
Could not execute command 'sassc'

### ISSUE THREAD

**Issue by SamAndaluz** [odoo/odoo#27483]
Impacted versions: 12

Steps to reproduce: Install Odoo 12 in Ubuntu

Current behavior:
Style error
×
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not execute command 'sassc'This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/fonts.scss
    - /web/static/src/scss/ui.scss
    - /web/static/src/scss/ui_extra.scss
    - /web/static/src/scss/navbar.scss
    - /web/static/src/scss/mimetypes.scss
    - /web/static/src/scss/modal.scss
    - /web/static/src/scss/animation.scss
    - /web/static/src/scss/rainbow.scss
    - /web/static/src/scss/datepicker.scss
    - /web/static/src/scss/banner.scss
    - /web/static/src/scss/colorpicker.scss
    - /web/static/src/scss/keyboard.scss
    - /web_tour/static/src/scss/tip.scss
    - /web_tour/static/src/scss/keyframes.scss
Expected behavior:
For the error not to happen

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
sudo apt install python3-libsass

**Comment by pedrobaeza** [comment]
Yes, it's a deployment problem due to the new requirement.

**Comment by Ericklomeli** [comment]
What was the solution? I already tried with sudo apt install python3-libsass and didn't work it

**Comment by phatminh** [comment]
Thanks!

**Comment by mgpolinn** [comment]
pip3 install libsass==0.12.3

**Comment by bodedra** [comment]
pip install libsass

**Comment by Zelelaw** [comment]
@bodedra it is working fine for me thankyou

**Comment by davidbister** [comment]
pip install libsass,if that dosent work thats,youu can just try  kill the port and compile agin ,or just restart pc and that should be just fine

**Comment by mvp5464** [comment]
Clear the cache and data from the browser or open in different browser. It worked for me.
