### ISSUE TITLE
[12] Do not add Same Product multiple times to wishlist

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27489]
Impacted versions:  12

Steps to reproduce:  Click multiple times
![default](https://user-images.githubusercontent.com/16624719/46585305-e28e2a00-ca8c-11e8-8419-36234dbc377c.png)

Current behavior:
![default](https://user-images.githubusercontent.com/16624719/46585339-529cb000-ca8d-11e8-9ce1-59bf29e0a95e.png)

Expected behavior: Do not add Same Product multiple times to wishlist

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
Hello,

I can't reproduce it on my end, I tried to click multiple times (very fast) on the `fa-heart` icon before it grayed out, but it is only added one time on the cart.
Both on Firefox and Chrome.

Let me now if this is the way you reproduced it.

**Comment by rdeodoo** [comment]
Yeah, it is not linked to List View, I reproduced it on my end after tens of tries.
Actually it is just a matter of connection speed, enabling "Fast 3G" on chrome console will show that issue.

I will keep you informed once it fixed

**Comment by sswapnesh** [comment]
@rdeodoo
Same situation here too
![screenshot 16](https://user-images.githubusercontent.com/16624719/47097776-b4a8a280-d24f-11e8-8198-082e82048ad7.png)
I will new Issue for this if you suggest
