### ISSUE TITLE
[12] es.po: Regression on translations

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#27494]
### Impacted versions:
12.0

### Steps to reproduce:
Install a database in spanish

### Current behavior:
Most terms are in English, which is an important regression from 11.0

### Expected behavior:
Have at least the same translations as in v11

cc: @pedrobaeza

**Comment by mart-e** [comment]
Looks fine to me, you probably tried before the weekly synchronisation which happens on Sunday (new release, new translations)

![screen](https://user-images.githubusercontent.com/564822/46682795-d9b56980-cbee-11e8-83c8-adba148be6cc.png)

Let me know if you still have the issue or if I am missing something.

**Comment by gustavovalverde** [comment]
Just updated to be sure:

v11:
![image](https://user-images.githubusercontent.com/16890942/46683721-e6ba6480-cbbe-11e8-8ba7-a97179e57a87.png)

v12:
![image](https://user-images.githubusercontent.com/16890942/46683710-dd30fc80-cbbe-11e8-833e-b55797822dfb.png)


v11:
![image](https://user-images.githubusercontent.com/16890942/46683843-36992b80-cbbf-11e8-934b-719e13bc283d.png)

v12:
![image](https://user-images.githubusercontent.com/16890942/46683805-1e291100-cbbf-11e8-9f16-2b5aa021d5dc.png)

**Comment by gustavovalverde** [comment]
There's a regression in the translation as you can validate with this images.

**Comment by gustavovalverde** [comment]
Almost all technical options are in English:
 v11:
![image](https://user-images.githubusercontent.com/16890942/46684571-339f3a80-cbc1-11e8-8118-0b43a92ffda7.png)


v12:
![image](https://user-images.githubusercontent.com/16890942/46684557-284c0f00-cbc1-11e8-8ad7-efb046be0866.png)

**Comment by mart-e** [comment]
Where are you trying? I do not get this on the latest runbot.

![screenshot_2018-10-10 accounting overview - odoo](https://user-images.githubusercontent.com/564822/46717138-01e0af00-cc67-11e8-8796-372eb1d91965.png)

![screenshot_2018-10-10 odoo](https://user-images.githubusercontent.com/564822/46717092-c5ad4e80-cc66-11e8-86d2-b61d19a9502e.png)

**Comment by pedrobaeza** [comment]
@gustavovalverde if you don't create a new DB, you must overwrite translation for getting latest translations.

**Comment by gustavovalverde** [comment]
@pedrobaeza  While loading a translation, isn't the `overwrite` boolean supposed to do that?

**Comment by pedrobaeza** [comment]
Yes, but how are you loading that translations? Maybe it can be a bug in the loading mechanism due to recent refactoring.

**Comment by gustavovalverde** [comment]
Oh wait. Now I understood what's going on. Last year I removed all es_DO.po because those were causing more harm than solving a problem: https://github.com/odoo/odoo/commit/aaa70fb433592e5a68e689007cc80c20446bc78d

But in some point in time most of them were added again. cc: @mart-e

**Comment by gustavovalverde** [comment]
@mart-e I'll be removing all es_DO.po again, as I'm guessing those were added by mistake.
