### ISSUE TITLE
Odoo12 - Cash on Hand chart of account not displaying reconciliation box

### ISSUE THREAD

**Issue by bsurfing** [odoo/odoo#27495]
Impacted versions:12

Steps to reproduce:Accounting>Configuration>Chart of Accounts>Cash on Hand

Current behavior:Reconciliation box not displaying

Expected behavior:This box is displayed in Odoo 11 and reconciliation is necessary on this account, so it should display

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31522016/46587758-fae75000-ca5e-11e8-8f9e-0cb7c36595ed.png)

**Comment by mart-e** [comment]
Hello,

Actually it is on purpose and is present in all versions (but was recently changed), the liquidity accounts have been hidden at 6b96e5024af628e501f5348068ef3c98919aca95
