### ISSUE TITLE
 Does not print from "html to pdf": Quotation, and all documents Odoo 12

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#27498]
Impacted versions: 
Odoo 12

**Current behavior:**

1. I create a quote
2. Click on Preview document
3. The PDF file is generated
4. When I open the file PDF, the error is generated

Note:
In the web address if I change from "pdf" to "html" I see the content of the document correctly (No PDF).

**Expected behavior:**

I would like to be able to print all documents correctly in PDF.

Video/Screenshot link (optional):

![captura de pantalla 7 _li](https://user-images.githubusercontent.com/34111479/46590597-29beef80-ca7a-11e8-86ee-e534b36ad6a1.jpg)

The PDF file is created:
![captura de pantalla 8 _li](https://user-images.githubusercontent.com/34111479/46590604-2fb4d080-ca7a-11e8-8426-1f2c7d8b2d7d.jpg)

An error when opening the PDF file:
![captura de pantalla 9](https://user-images.githubusercontent.com/34111479/46590612-37747500-ca7a-11e8-99f4-7fb3c8b01eb6.png)

The file that is attached to the quote is "Html" and not "PDF":
![captura de pantalla 12 _li](https://user-images.githubusercontent.com/34111479/46590617-3f341980-ca7a-11e8-86a8-34d968ebf74c.jpg)

Sale.order is in PDF:
![captura de pantalla 14 _li](https://user-images.githubusercontent.com/34111479/46590619-45c29100-ca7a-11e8-94a4-8ecc1069d46b.jpg)

wkhtmltopdf is working fine:
![captura de pantalla 14](https://user-images.githubusercontent.com/34111479/46590626-4d823580-ca7a-11e8-909e-7e03bbc0bdf4.png)

In general it does not print any document in PDF format

Thanks for your support

**Comment by Elkasitu** [comment]
Can you reproduce this on [runbot](runbot.odoo.com/runbot) ?

**Comment by AliHussJaafar** [comment]
i have the same bug as @LSR29  i m using the enterprise version installing the package downloaded from the website running it with demo data , trying to print , it shows the same error as shown . V.11 working just fine @Elkasitu

**Comment by Elkasitu** [comment]
Seems to work fine both on [runbot](http://runbot.odoo.com/runbot) and locally for me, can you please specify your wkhtmltopdf version?

**Comment by AliHussJaafar** [comment]
[Quotation - SO003 (7).pdf](https://github.com/odoo/odoo/files/2456170/Quotation.-.SO003.7.pdf)
this is an example of the file , my wkhtmltopdf version is 0.2

**Comment by LSR29** [comment]
> Can you reproduce this on [runbot](runbot.odoo.com/runbot) ?

I'll try. Thanks

**Comment by LSR29** [comment]
> i have the same bug as @LSR29 i m using the enterprise version installing the package downloaded from the website running it with demo data , trying to print , it shows the same error as shown . V.11 working just fine @Elkasitu

It seems that only the file extension from HTML to PDF will change. You try to change the extension of the file to HTML and you will see how it opens without problems in HTML.

**Comment by LSR29** [comment]
> [Quotation - SO003 (7).pdf](https://github.com/odoo/odoo/files/2456170/Quotation.-.SO003.7.pdf)
> this is an example of the file , my wkhtmltopdf version is 0.2

![captura de pantalla 15](https://user-images.githubusercontent.com/34111479/46621477-29137100-caed-11e8-948c-4b1ac1d7f45d.png)

It's the same problem that I have. And if you try changing only the extension of the file you can see it without problems. I attach your file changing the extension to Html.

**Comment by celm1990** [comment]
Hi, not is possible reproduce on runbot, but localy has same error, explain:

When start odoo with options **-s** -c odoo12.conf its create file as follow:
![image](https://user-images.githubusercontent.com/7775116/46621136-342ec700-cb16-11e8-98d4-05327e5ef741.png)

This is introduced on this [commmit](76c5389cd95b11b85ee176695556c6001674657c)

https://github.com/odoo/odoo/blob/12.0/odoo/tools/config.py#L488

Debbugin `bool(self.options['test_tags'])` is interpreted as `bool("None")` and result is True, 
At generate report If test enable is True, only render in html, no converted to pdf https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_actions_report.py#L603-L604

Tempory solution, in odoo config file chage this
![image](https://user-images.githubusercontent.com/7775116/46621479-14e46980-cb17-11e8-8136-08d308a8ccb4.png)

CC: @Xavier-Do

**Comment by LSR29** [comment]
> Hi, not is possible reproduce on runbot, but localy has same error, explain:
> 
> When start odoo with options **-s** -c odoo12.conf its create file as follow:
> ![image](https://user-images.githubusercontent.com/7775116/46621136-342ec700-cb16-11e8-98d4-05327e5ef741.png)
> 
> This is introduced on this [commmit](76c5389cd95b11b85ee176695556c6001674657c)
> 
> https://github.com/odoo/odoo/blob/12.0/odoo/tools/config.py#L488
> 
> Debbugin `bool(self.options['test_tags'])` is interpreted as `bool("None")` and result is True,
> At generate report If test enable is True, only render in html, no converted to pdf https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_actions_report.py#L603-L604
> 
> Tempory solution, in odoo config file chage this
> ![image](https://user-images.githubusercontent.com/7775116/46621479-14e46980-cb17-11e8-8136-08d308a8ccb4.png)
> 
> CC: @Xavier-Do


Great! I'm going to try it Then I told you what the results were.

**Comment by LSR29** [comment]
> Hi, not is possible reproduce on runbot, but localy has same error, explain:
> 
> When start odoo with options **-s** -c odoo12.conf its create file as follow:
> ![image](https://user-images.githubusercontent.com/7775116/46621136-342ec700-cb16-11e8-98d4-05327e5ef741.png)
> 
> This is introduced on this [commmit](76c5389cd95b11b85ee176695556c6001674657c)
> 
> https://github.com/odoo/odoo/blob/12.0/odoo/tools/config.py#L488
> 
> Debbugin `bool(self.options['test_tags'])` is interpreted as `bool("None")` and result is True,
> At generate report If test enable is True, only render in html, no converted to pdf https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_actions_report.py#L603-L604
> 
> Tempory solution, in odoo config file chage this
> ![image](https://user-images.githubusercontent.com/7775116/46621479-14e46980-cb17-11e8-8136-08d308a8ccb4.png)
> 
> CC: @Xavier-Do

Crack! @celm1990  Problem solved

**Comment by celm1990** [comment]
@Elkasitu @Xavier-Do  or Odoo team must be solved from base, it is temporary solution

**Comment by Xavier-Do** [comment]
I'll check for a base fix tomorrow morning. Thanks for the feedback!
