### ISSUE TITLE
[12] Internal Server Error on Sorting Products On Shop (No product defined.)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27490]
Impacted versions: 12

Steps to reproduce: Try Filter where there is no any matching Product

![-2](https://user-images.githubusercontent.com/16624719/46585384-e2425e80-ca8d-11e8-95e4-e7b1e0ede889.png)
Sort by - Price or NAme
![-1](https://user-images.githubusercontent.com/16624719/46585383-db1b5080-ca8d-11e8-99c4-f23660c89838.png)
Current behavior:
`500: Internal Server Error`

Expected behavior:
Should stay on Same Page

Video/Screenshot link (optional):
![peek 2018-10-08 00-07](https://user-images.githubusercontent.com/16624719/46585418-406f4180-ca8e-11e8-96a8-c6e5a7919d47.gif)

**Comment by rdeodoo** [comment]
Thank you for the report, a fix is coming :snowman:
