### ISSUE TITLE
Installed the latest version but not showing as CE

### ISSUE THREAD

**Issue by beeriz** [odoo/odoo#27496]
Hello.
After installing the latest nightly version, I noticed it wasn't the CE version, but instead its was Odoo 12.0-20181007 (Enterprise Edition).

Now to use the accounting module I have to "upgrade" which takes me to odoo website to pay for a subscription, which not what I intended to do.

Is this a normal behavior for the version 12 hosted on https://nightly.odoo.com/12.0/nightly/deb/ ?

Thank you 
Impacted versions:
12.0 (from https://nightly.odoo.com/12.0/nightly/deb/ )

**Comment by sswapnesh** [comment]
Please check https://github.com/odoo/odoo/pull/27442#issuecomment-427680504

**Comment by sswapnesh** [comment]
and also https://github.com/odoo/odoo/issues/27439 Regarding `Upgrade` button

**Comment by mart-e** [comment]
Hello,

As explained by Swapnesh, the version will be handled in #27442.
And yes, the upgrade button is intentional, it means upgrade to enteprise.

**Comment by beeriz** [comment]
Thank you sswapnesh, I was aware of #27442 but my issue is a bit different, I can't access basic apps that were available freely on my previous version (11 Community edition).

Here's a video of the issue :

**Comment by beeriz** [comment]
Hello. 

Thank you sswapnesh, I was aware of #27442 but my issue is a bit different, I can't access basic apps that were available freely on my previous version (11 Community edition).

@mart-e , even if I installed it as a community edition, I need to upgrade to use Accounting? after installing the version 11, I didn't have such issue.
Here's a video of the issue : https://youtu.be/6SDuHM1k3NY

**Comment by mart-e** [comment]
account_accountant_cbc is not an Odoo official module but one created by Cubic ERP. Get in touch with them to see if they plan to publish an update for v12.
