### ISSUE TITLE
[11.0] Font-family does not work in Qweb reports

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#27503]
[11.0] Font-family does not work in Qweb reports

**Comment by bhaveshselarka** [comment]
I have already tried with below mention link solutions.

1. https://www.odoo.com/fr_FR/forum/aide-1/question/9-0-how-to-define-custom-fonts-to-css-in-report-assets-common-113812

2. https://github.com/odoo/odoo/issues/4908

3. https://www.odoo.com/fr_FR/forum/aide-1/question/how-to-add-custom-fonts-to-qweb-reports-88923

Thanks,

**Comment by bhaveshselarka** [comment]
When I change report type to HTML. It will show and working fine. But when its print into original PDF report at that time not working.

So pdf render time it is not working.

**Comment by Yenthe666** [comment]
@mart-e could you have a look at this one? I did quite some testing too.
Adding fonts from Google in a `<style type="text/css">` block within the report works fine. When you have less / CSS files that you're adding to assets it doesn't seem to apply it in reports.
I tried it on the assets group `web.assets_common` and `web.assets_backend` but both options do not load and apply the custom font in the QWeb report

**Comment by bhaveshselarka** [comment]
Yes, @Yenthe666  I have tried also `web.report_assets_common` but not working.
I have tried most of the possible ways mention on the internet.

**Comment by gdgellatly** [comment]
I had this issue a long time ago.  From memory it was to do with the compatibility of embedding the fonts in the reports.  I seem to recall that when I linked I linked to TTF's or similar in my font-family the pdf was perfect, but html was wrong and vice versa with say WOFF/2 files cached locally in the module (or /usr/share).  I did eventually get it to work but it required some fallback definitions or some kind of switch.  Sorry it was a long time ago, so don't fully remember.

**Comment by Yenthe666** [comment]
I made an official enterprise ticket for this issue because I've tried all the options I could think of. Official ticket = 1899177

**Comment by bhaveshselarka** [comment]
Thanks a lot, @Yenthe666 . for official enterprise ticket. Because in this development I have also spent much time on it and not able to get fonts on PDF.

**Comment by bhaveshselarka** [comment]
Hello, @Yenthe666 Have you got something on Official ticket = 1899177.
Please let me know.

**Comment by bhaveshselarka** [comment]
Thanks, @Yenthe666 for the updates.

**Comment by Yenthe666** [comment]
No problem, I've also asked for an update so I atleast know where it is at somewhere.

**Comment by Yenthe666** [comment]
Hi all,

Quick update. I've had a suggestion from Odoo to try (the full URL to the font) but that also does not work.
I've asked for a fix as in my opinion it is truely broken.

Regards,
Yenthe

**Comment by bhaveshselarka** [comment]
Thanks, @Yenthe666 for the information.

**Comment by bhaveshselarka** [comment]
Hello, @Yenthe666 Have you got any updates on that ticket?

And yes @sswapnesh if you find something regarding this then let us know.

**Comment by sswapnesh** [comment]
@bhaveshselarka  Honestly this is not my cup of tea.

**Comment by sswapnesh** [comment]
> @pedrobaeza or @nhomar did you ever try this? Do you happen to know more about it?

@Yenthe666  I think as you edited comment to tag them, They may have not received notification for this.

**Comment by pedrobaeza** [comment]
I don't remember haven't dealt with this, sorry.

**Comment by Yenthe666** [comment]
Hmm might be indeed. The issue on the official Odoo tickets is now in the state technical / platform and I'm pretty sure it is going to qualify as a bug honestly. I've asked our account manager for more feedback as the issue is moving incredibly slow right now.
I'll keep you all updated.

**Comment by Yenthe666** [comment]
Hi all,

The issue has been confirmed by Odoo S.A. and they're working on a fix.

**Comment by bhaveshselarka** [comment]
Thanks a lot, @Yenthe666 for sharing an information.

**Comment by Yenthe666** [comment]
Asked for another update, still no solution.

**Comment by delebeat** [comment]
@Yenthe666, Thanks for the update on my odoo forum, i can see am not the only one facing this challenge and it a base issue . any update,let know . Thanks

**Comment by Yenthe666** [comment]
@delebeat you're welcome, I saw it was pretty similar so I assume it is the same.
I've asked both the responsible on the ticket and my account manager but have been waiting for days on feedback. Response times are pretty bad at the moment I'm afraid. I'll keep poking them 😉

**Comment by Yenthe666** [comment]
Hi all,

A quick update. There is still no fix from Odoo and I've once again escalated the issue, complaining about the lack of communication and the duration of the tickets (3 months+). I'll try to keep you all updated, this one is difficult to communicate about with Odoo, very bad response rates.

**Comment by bhaveshselarka** [comment]
Hi @Yenthe666, Thanks for the support and updates.

**Comment by Matt-OBell** [comment]
Thanks for the update @Yenthe666

**Comment by delebeat** [comment]
@Yenthe666 , Thanks for the update.

**Comment by Yenthe666** [comment]
Hi all,

The only truely working options seems to be by adding your font definitions to `web.report_assets_common` as pointed out by @rim-odoo 
Assets code for calling the `.less` file with the custom font definition:
```
  <template id="report_assets_common_custom_fonts" name="qweb_fonts less backend assets" inherit_id="web.report_assets_common">
    <xpath expr="." position="inside">
      <link href="/your_module/static/src/less/fonts.less" rel="stylesheet" type="text/less"/>
    </xpath>
  </template>
```

Less code to actually load the font:
```
@font-face {
    font-family: 'MonixBold';
    src: local('MonixBold'), local('MonixBold'), url(/your_module/static/src/fonts/MonixBold-Regular.otf) format('opentype');
}

.h1-title-big {
    font-family: MonixBold;
    font-size: 60px;
    color: #3399cc;
}
```


Custom report:
```
<?xml version='1.0' encoding='UTF-8'?>
<odoo>

  <template id="report_example_document">
    <t t-call="web.external_layout">
      <div class="page">
        <div class="row">
          <h1 class="h1-title-big text-center">This should be a Monix font title in PDF</h1>
        </div>
      </div>
    </t>
  </template>
  <template id="report_example">
    <t t-call="web.html_container">
      <t t-foreach="docs" t-as="doc">
        <t t-call="your_module.report_example_document"/>
      </t>
    </t>
  </template>
  <!-- PDF report -->
  <report id="report_example_action" string="Test report PDF" model="res.partner" report_type="qweb-pdf" name="your_module.report_example" file="your_module.report_example" print_report_name="'Test report - %s' % (object.name)"/>
  <!-- Same report in html for easy testing -->
  <report id="report_example_action2" string="Test report HTML" model="res.partner" report_type="qweb-html" name="your_module.report_example" file="your_module.report_example" print_report_name="'Test report - %s' % (object.name)"/>
</odoo>
```
Example taken from @rim-odoo

**Comment by Yenthe666** [comment]
Hi all,

I believe this ticket can be closed for the following reasons:
1) It works (although slightly confusing)
2) There is an internal task made at Odoo to look at how it can be more transparant and to rename some parts involved to get everything clear
3) I've documented an example in the official docs for other people that might face this. See https://github.com/odoo/odoo/commit/2ba6be20040a7b27d8cd8d95e089007a7a2edf78

Regards,
Yenthe
