### ISSUE TITLE
Odoo 12 on Windows Fix error Could not execute command Sassc Odoo 

### ISSUE THREAD

**Issue by turkimaki** [odoo/odoo#27509]
Hello ,
After installing Odoo 12 on Windows i have this problem when open database and starting using odoo
error Could not execute command Sassc Odoo  .
I had already resolve this problem on linux with installing libsas but on windows i didn't know how to install it  . I try to install libsas but when must I put the output of this command  on website/src/static/css of odoo 12 or where .
If there is another solution better  please propose it with details thanks 
Cordially Maki.

**Comment by Yenthe666** [comment]
@d-fence most likely for you.

**Comment by turkimaki** [comment]
this is because i use python 3.7 ?  I must downgrade the version python ! ?

**Comment by kenvac** [comment]
I had same issue. 
I fired up pythonevn and did pip3 install -r requirement.txt (solved my issue)

I am on debian 9

**Comment by turkimaki** [comment]
Kenvac i had solve the problem on linux (ubuntu 18.04 and 16.04) my problem is on windows

**Comment by d-fence** [comment]
Hello, did you install it through the official Odoo installer ? Libsass is bundled with the installer.

**Comment by turkimaki** [comment]
Yes i had install it by odoo installer

**Comment by d-fence** [comment]
Hmm, strange, Odoo 12 comes with its own version of python bundled and you said that you use Python 3.7. Can you give more context on how you tweaked Odoo to use your python version instead of the one bundled ?
If it's the case, you have to install [libsass-python](https://sass.github.io/libsass-python/) for your python version.

**Comment by d-fence** [comment]
But Odoo is started as a service installed by with the installer !?
I think that if you want to develop in Odoo, you should use the git sources and probably the Windows Subsystem for Linux.

**Comment by turkimaki** [comment]
i installed from the website nigthly i take the latest.exe
Yes the service installed by the installer

**Comment by makouk20** [comment]
So how to resolve problem please

**Comment by pedrobaeza** [comment]
@makouk20 it's clear that Odoo installer is not failing and you should figure out how to fix it on your system if you want to develop on Windows. My advice is to not do it that way, but develop on Linux, as you will have tons of more facilities for everything.

If you want to ask someone for how to do it, you should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by phatminh** [comment]
Thanks, it's really work.... :)
