### ISSUE TITLE
Area field in Odoo notes

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#2751]
Odoo notes was published on play market recently.
It would fail if it did not have offline mode but I does have it.
Nice UX, thanks.
By default categories reflect GTD concept.
To be 100% true GTD it must have also Areas.
Each Area has its own today/next/someday/week/etc categories and tags.
Just one field who is in charge :-)

P.S. From GDT point Areas reflect areas of life with its own projects. They must be seen in different ir.ui.view :-) GTD users will like it for sure ;-)

**Comment by Yenthe666** [comment]
Hi @litnimax,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
