### ISSUE TITLE
JS Client using POST request instead of GET

### ISSUE THREAD

**Issue by chrizzTs** [odoo/odoo#27516]
Impacted versions: 11

Steps to reproduce: Track network requests in your browser

Current behavior:
When loading Odoo you can see that the JS client uses POST requests to retrieve most data from Odoo Backend instead of GET requests. 
E.g. In CRM module, opening a lead fires a POST requests to get the name.
![image](https://user-images.githubusercontent.com/6087189/46600554-ca4cf800-caea-11e8-869a-3ba61ab78b1e.png)
 

Expected behavior:
I would expect to use GET method instead of POST method to retrieve data from the server. 
The issue is that by this implementation modern techniques like Progressive Web App with caching is not possible! 
I tried to implement a caching strategy based on Service Worker concept to increase performance by caching data and make the client more robust for connection lost. Unfortunately only caching of GET requests is supported since this is the regular way of retrieving data from a backend.

**Comment by pedrobaeza** [comment]
@ged-odoo can you please answer this?

**Comment by ged-odoo** [comment]
@chrizzTs @pedrobaeza This will never be done in v11.0.  However, I think that it makes a lot of sense. I added this to my todo list, but I expect that this will be difficult to do.  Not for a technical reason, but for 'political' reasons.  I'll try to make this, but no promise.
