### ISSUE TITLE
[12.0] Post At Bank Reconciliationchange setting is updating existing entries

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#27557]
Impacted versions: 12.0

Steps to reproduce: Create A journal Or on exiting journal set "Post At Bank Reconciliation" is True
Create a payment it will set JE unposted which is true.

Now change the Journal Setting to  "Post At Bank Reconciliation" is False

Current behavior:

It will post all unposted Journal Entries to posted after we change the setting (but not in inverse case i.e. when first we have Post At Bank Reconciliation=False create some entries and then you change Post At Bank Reconciliation=True past entries remain posted and new entries are unposted same behaviour should be in reverse case ).  
It should not as the previous setting was True and JE are created with that settings.

Expected behavior:

When JE are created with "Post At Bank Reconciliation" is True and all the entries created should be unposted, even after the setting is changed False but past entries should not affect.

Video/Screenshot link (optional):
PFA Video Refrence:

[post JE.ogv.zip](https://github.com/odoo/odoo/files/2459190/post.JE.ogv.zip)

**Comment by FlorianGilbert** [comment]
Hi,

Your solution will not be used because the desired behavior is the right one.
Indeed, we want to avoid payments for which the Journal Entry is not posted (if the "Post at bank Reconciliation" is False). This may create errors in the accounting.

Regards,
