### ISSUE TITLE
[7.0] Sales,Accouning Configuration setting gives recursion Error

### ISSUE THREAD

**Issue by pji-odoo** [odoo/odoo#2755]
when you click on Configuration setting of Module Sales and Accounting it gives client Error "too much recursion"

> Browser : Firefox 31.0  OS : Ubuntu 12.04
> I guess it's issue of event bubbling... 
> ![configuresettingerror - openerp](https://cloud.githubusercontent.com/assets/7599753/4438361/54d77a94-47ab-11e4-94f8-c22012d09516.png)

**Comment by petrus-v** [comment]
@estkae,

Are you telling that Odoo is only supported by Chrome ?

**Comment by Yenthe666** [comment]
Hi @pji-odoo,

Thanks for your report.
It looks like this has been fixed in the meanwhile and V7 is end of life so there is no more support for this version.

Regards,
Yenthe
