### ISSUE TITLE
Cant hide website or pricing for users not logged in

### ISSUE THREAD

**Issue by garethstead** [odoo/odoo#27552]
Impacted versions: v12

Steps to reproduce:

Current behavior:
Not sure if this is the place to add this (I'm new here) but it would be good to be able to have the e-commerce only show if there is a logged in user
Expected behaviour:

Video/Screenshot link (optional):

**Comment by garethstead** [comment]
Also the ability to hide pricing for non logged in users. This is important for B2B. This article describes how to do it but it would be good for a checkbox that allows the non-technical user to make the change https://www.odoo.com/forum/help-1/question/hide-the-shop-for-public-131567

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
