### ISSUE TITLE
[12.0]Error when creating new warehouses

### ISSUE THREAD

**Issue by zyyang** [odoo/odoo#27556]
Impacted versions:
12.0

Steps to reproduce:

1. Enable 'multiple warehouse' in Inventory app(with Manufacture App installed).
2.Create a new warehouse.

Current behavior:
> can't adapt type 'stock.location'.

Expected behavior:
new warehouse created.

Can be fixed by changing:
https://github.com/odoo/odoo/blob/3e178daa30d4d433df7f57be267a13c236376bd7/addons/mrp/models/stock_warehouse.py#L226

to: 
`'default_location_dest_id': self.manufacture_steps == 'pbm_sam' and self.sam_loc_id.id or self.lot_stock_id.id,`

**Comment by Yenthe666** [comment]
Resolved in the above commit. Thanks for reporting it!
