### ISSUE TITLE
[Odoo 12][Website] "Edit" button does not work if only Website module is installed

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#27565]
Impacted versions:
12.0
Steps to reproduce:
Install Odoo with test data, install "Website" module
Current behavior:
Edit, Customise and all the top buttons does not work. Installation of the Blog module solves the issue
Expected behavior:
Fully functioning Website module without the need of installation any other modules
Other info:
Ubuntu 18,04 2GB of RAM

**Comment by rdeodoo** [comment]
Hello,

I tried to reproduce what you described but I did not find any issues as you can see here: https://drive.google.com/file/d/113RensmqDOQs1yD4yAdrhjQrpBlo3s4i/view

Am I missing something?

**Comment by cierek** [comment]
Checked on the latest today and no issues anymore. Thanks
