### ISSUE TITLE
web client slower than 11.0

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#27577]
Impacted versions:
12 

Steps to reproduce:

Current behavior:
as title.

Expected behavior:

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
can you be more specific? this isn't very helpful

**Comment by jeffery9** [comment]
community feedback that the latest edition faster than the init release. maybe the changes recently has improved performance

**Comment by mart-e** [comment]
Please give clear and specific examples of performance issues and we can investigate.
