### ISSUE TITLE
Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

### ISSUE THREAD

**Issue by Dax1900** [odoo/odoo#27575]
Impacted versions:12

Steps to reproduce:
```
C:\Users\me\docker\test-v12>docker-compose up -d
Pulling odoo (odoo:12.0)...
12.0: Pulling from library/odoo
05d1a5232b46: Pull complete
75a3e5f892cb: Pull complete
cb3ba02f584a: Pull complete
405853b67e93: Pull complete
501dd141170c: Pull complete
2e1aeec802cd: Pull complete
1346d0907e53: Pull complete
a4eb0375692f: Pull complete
Digest: sha256:0e050fde9ca8b8ba5d92e7382d350e82faad8d8a554e8a1fd8f7ee0796e465d8
Status: Downloaded newer image for odoo:12.0
Creating test-v12_db_1 ... done
Creating test-v12_odoo_1 ... done

C:\Users\me\docker\test-v12>docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
b639c53e03c9        odoo:12.0           "/entrypoint.sh odoo"    15 seconds ago      Up 13 seconds       8071/tcp, 0.0.0.0:9012->8069/tcp   test-v12_odoo_1
6e56cb8a3af7        postgres:9.4        "docker-entrypoint.s…"   16 seconds ago      Up 14 seconds       0.0.0.0:5012->5432/tcp             test-v12_db_1
```
Current behavior:
![image](https://user-images.githubusercontent.com/42471159/46667929-56365100-cbcb-11e8-9bb1-6389ab57871e.png)

When creating a new odoo database is comes back with:

Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

Expected behavior:

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Could you try with a docker set to use postgres 9.5 (min), cf @d-fence comment https://github.com/odoo/odoo/issues/27447#issuecomment-427840100 )

**Comment by d-fence** [comment]
The docker documentation was updated yesterday.
I think that the issue is linked to #27447 and [this postgres change](https://github.com/docker-library/postgres/commit/3f585c58df93e93b730c09a13e8904b96fa20c58).
Also, I see that you use postgres 9.4, Odoo 12 will only work with postgres >= 9.5 because of the 'ON CONFLICT' clause that was introduced in postgres 9.5.

May I ask you to try again with the help of the [latest documentation](https://hub.docker.com/_/odoo/)
Thanks

**Comment by Dax1900** [comment]
Yesss it works together with the #27447 (comment)

This is my working docker-compose.yml:

version: '2.1'
services:
  odoo:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "9012:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=**********
  db:
    image: postgres:9.6
    ports:
      - "5012:5432"
    environment:
      - POSTGRES_PASSWORD=**********
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres

**Comment by Dax1900** [comment]
... but just another matter: is the Accounting app gone in CE ?!?

**Comment by Dax1900** [comment]
Aaah found it under user-settings: "Show full accounting features"

**Comment by d-fence** [comment]
Glad to see it works.

**Comment by Koussayabd** [comment]
hhhhhhhhhhhhhhhhh

**Comment by Koussayabd** [comment]
Any solution for these probleme

**Comment by saeed-raeisi** [comment]
check postgres user and permission 
i check res_partner_view -> <field name="state_id" class="o_address_state" placeholder="State" options="{'no_open': True, 'no_quick_create': True}"

**Comment by saeed-raeisi** [comment]
check postgres user and permission 
i check res_partner_view -> <field name="state_id" class="o_address_state" placeholder="State" options="{'no_open': True, 'no_quick_create': True}"
