### ISSUE TITLE
appending times to dates when searching datetime doesn't take timezone into account

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#2758]
In expression.py, the server appends ' 00:00:00' or ' 23:59:59' to dates if the field to be searched is of type datetime.

This gives confusing results for dates on day boundaries. Consider me searching
[('date', '<=', '2013-11-27')]
in timezone Europe/Amsterdam
which is rewritten in sql to
date <= '2013-11-27 23:59:59'
and a record with date 2013-11-27 23:30:00 UTC be found, even though it's 2013-11-28 00:30:00 CET.

So I think if we mess with the dates at all, we should convert the searched date from the user's timezone to UTC and search for the result or result+23:59:59.

(from https://bugs.launchpad.net/ocb-server/7.0/+bug/1255612)

**Comment by Yenthe666** [comment]
Hi @hbrunn,

Thank you for your report.
I believe this can be closed, as discussed on https://github.com/odoo/odoo/pull/2914 in combination with the PR https://github.com/odoo/odoo/pull/16698

Regards,
Yenthe
