### ISSUE TITLE
[v11] Would it be possible to configure email server without being admin?

### ISSUE THREAD

**Issue by aelmanaa** [odoo/odoo#27598]
It is not really an issue but kind of conceptual question or a wish. 

Impacted versions:
V11 CE, but I think all versions are impacted
Steps to reproduce:
Only administrator can set up the SMTP email server
Current behavior:
Only administrator can set up the SMTP email server
Expected behavior:
In a multitenancy SaaS mode, the administrator can be the service provider(which is not part of the users of a database) and hence, setting up configuration of SMTP email servers should be the responbility of a user with privileges(since every database is a different client. And every different client has its own SMTP server with its private credentials). The administrator should only control the number of users and the modules installed on each database.
Is there a workaround to solve this issue in Odoo CE v11?

thanks a lot

**Comment by Yenthe666** [comment]
Hi @aelmanaa,

By default you can't. You could make a custom menu/option for it though (for example under the user preferences) where you can set these values.
You basically will need extra security rules and some custom development.

Regards,
Yenthe
