### ISSUE TITLE
Asset Accounting and Budget management in CE 12

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#27595]
Impacted versions:
CE 12
Steps to reproduce:
activate them in invoicing setting 

Current behavior:
after saving, both sets are undone again

Expected behavior:
Both modules should be activated
please take into account the related apps are not included in the apps menu 

Video/Screenshot link (optional):
https://drive.google.com/open?id=1WGuto9Ib90Pas9b0PPxUi5xmKCW6RVWL

**Comment by dan18fan** [comment]
Isn't Assets and Budgets accounting disabled from communtity version? (enterprise only)

**Comment by jeffery9** [comment]
have been move to enterprise, and those license changed to OEE.

**Comment by Yenthe666** [comment]
Yeah indeed, it moved to enterprise. So no real issue here right?

**Comment by ccandito** [comment]
The issue is related to a downgrading from the previous release

**Comment by Yenthe666** [comment]
Hi @ccandito,

I know it is not nice to see and find out (I don't like it either) but after all that call is up to the guys from Odoo.
There is nothing that says they cannot add or remove features though.

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
Maybe there's a little issue, that is to mark that checks with the enterprise option (there's a widget for that).

**Comment by Yenthe666** [comment]
Yeah, that could be an improvement I guess. Made a quick PR for it at https://github.com/odoo/odoo/pull/27606

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/5822d3cbdb19288271a2b36613c44a678fa14cc1
