### ISSUE TITLE
[12] Issue with Form View Mobile

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#27602]
Impacted versions:
12
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/40818338/46708313-32751880-cc68-11e8-8897-a6f78ab37355.png)

**Comment by Yenthe666** [comment]
Hi there,

I'm sorry but this really is very little information. What do you believe that there is broken or wrong?

**Comment by dhamedic** [comment]
When I use the cell phone, the "edit" button has a space next to it. So I could think that the "create" button next to the "edit" button and paging button should be the same row with the "create", "edit" and "action"

**Comment by Yenthe666** [comment]
@mart-e can you give this one as feedback to the mobile team as improvement?

**Comment by mart-e** [comment]
Hello,

This is not the mobile application but the community in a browser.
Sorry but the community is not supported as responsive. Instead you should use the mobile application (we have an android and ios app).

**Comment by Yenthe666** [comment]
Oh yeah, I misinterpret that one. Nevertheless it is still acceptable to me too.

**Comment by Yenthe666** [comment]
@dhamedic no the conclusion was not too fast. You're showing it in browser with a community version. The community version is not officially response on mobile devices. The mobile app (with enterprise) is, so you could upgrade to get a great responsive feeling. 😉

**Comment by dhamedic** [comment]
![viber image](https://user-images.githubusercontent.com/40818338/46723212-7c2e2500-cca1-11e8-84ee-a5f16da370a7.jpg)

**Comment by mart-e** [comment]
@dhamedic you are opening odoo community inside a browser on your phone.
Sorry but we do not support the responsive design there.
We do have a [mobile application](https://play.google.com/store/apps/details?id=com.odoo.mobile) for enterprise databases.

**Comment by dhamedic** [comment]
OK Thanks @Yenthe666  @mart-e 
I will wait OCA to fix it

**Comment by sswapnesh** [comment]
@mart-e  @Yenthe666 
I believe Community version is Mobile Responsive. (I remember I have read it somewhere from Odoo Officials)

**Comment by mart-e** [comment]
@sswapnesh there has been efforts to improve it but no, it is one of the main difference between both editions
https://www.odoo.com/page/editions

**Comment by sswapnesh** [comment]
Yes, have seen this but there was statement about official support in Community too. Will add link if I am able to get it (was on Twitter or LinkedIn)

**Comment by Yenthe666** [comment]
@sswapnesh yes it was once claimed (I believe by Fabien) to land in V11 but it never did.

**Comment by sswapnesh** [comment]
It was from Odoo India Employee for Odoo v12 community. BTW, I am not asking to Open this Issue and consider this as Bug. So as Martin Said It will not be supported for v12 Community.👍
