### ISSUE TITLE
website_sale bug in controller function to create transaction

### ISSUE THREAD

**Issue by wpichler** [odoo/odoo#27615]
Impacted versions:
10.0

Steps to reproduce:
Do call the /shop/payment/transaction/<int:acquirer_id> function - do specify a so_id or so_token - or both - you will get the error

Current behavior:
Exception

Expected behavior:
No Exception

The website_sale module does here try to access the field access_token in sale.order - but this field is only available when website_quote is installed. website_quote is no dependency for website_sale.
If you specifiy on the so_id - then it does try to load the sale.order - but does not use sudo - so it will also fail here.
If you do not specify both - then it is ok - it does load the sale.order of the current session...

**Comment by pedrobaeza** [comment]
Which exception? Please specify the detailed steps for getting it.

**Comment by wpichler** [comment]
I will provide the problematic code here:

`        Transaction = request.env['payment.transaction'].sudo()

        # In case the route is called directly from the JS (as done in Stripe payment method)
        so_id = kwargs.get('so_id')
        so_token = kwargs.get('so_token')
        if so_id and so_token:
            order = request.env['sale.order'].sudo().search([('id', '=', so_id), ('access_token', '=', so_token)])
        elif so_id:
            order = request.env['sale.order'].search([('id', '=', so_id)])
        else:
            order = request.website.sale_get_order()

`
First Problem - is at "order = request.env['sale.order'].search([('id', '=', so_id)])" - this must get called with sudo - else it will throw a AccessDenied Exception.

Second Problem is here "request.env['sale.order'].sudo().search([('id', '=', so_id), ('access_token', '=', so_token)])" - it does query sale.order for the field "access_token" - this field does not exists if website_quote is not installed - so you will get an exception here

This does not happen with the payment modules included with odoo - this does happen if you develop a new payment module - and if you try to give the token or so_id as paramter to this function call.

**Comment by sswapnesh** [comment]
Hello @wpichler 
I am able to Reproduce Both Problem (On Runbot too).  

First Problem: 
`order = request.env['sale.order'].search([('id', '=', so_id)])` raises
`odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: sale.order`

Second Problem: 
Field `access_token` is part of `website_quote` module which is not required to Use as dependency. (or may be missing/Invalid dependency)

`order = request.env['sale.order'].sudo().search([('id', '=', so_id), ('access_token', '=', so_token)])`
 raises
```
order = request.env['sale.order'].sudo().search([('id', '=', so_id), ('access_token', '=', so_token)])
  File "/home/swapnesh/Workspace/10_odoo/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/swapnesh/Workspace/10_odoo/odoo/models.py", line 4242, in _search
    query = self._where_calc(args)
  File "/home/swapnesh/Workspace/10_odoo/odoo/models.py", line 4041, in _where_calc
    e = expression.expression(domain, self)
  File "/home/swapnesh/Workspace/10_odoo/odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "/home/swapnesh/Workspace/10_odoo/odoo/osv/expression.py", line 821, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'access_token' in leaf "<osv.ExtendedLeaf: ('access_token', '=', None) on sale_order (ctx: )>"
```

Ps: I have Removed If (`if so_id and so_token:`) condition to check execution of this lines.

Cc: @pedrobaeza

**Comment by sswapnesh** [comment]
On v11:
`access_token` is part of `sale` module but still we need to pass `sudo()` for `order = request.env['sale.order'].search([('id', '=', so_id)])
`

**Comment by rdeodoo** [comment]
Related to: https://github.com/odoo/odoo/commit/9010ed0a355d50792e13b29b3513cc824c5bdf1a

**Comment by Yenthe666** [comment]
I think this was fixed and as V10 is no longer officially supported I'm closing off this bug report.
