### ISSUE TITLE
multicompany products cost in fifo

### ISSUE THREAD

**Issue by chinu23081994** [odoo/odoo#27628]
Impacted versions: 

Steps to reproduce: when I created a child company of parent and setting it's account exactly the same as parent company. I created a product from parent company and then I wanted to create a sale or purchase of the same product, it gives a warning message "The cost of product is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation."
I have set the product category account configuration in both the company exactly the same.
Forced Removal Strategy : FIFO
Costing Method : FIFO
Inventory Valuation : Automated

Current behavior: I am unable to create sale and purchase

Expected behavior: I want to create sale and purchase automatically

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
I believe this can be closed now based on comment 
https://github.com/odoo/odoo/pull/32550#issuecomment-481672276 from Nicolas.

**Comment by sswapnesh** [comment]
@pedrobaeza 
Can we close this now based on https://github.com/odoo/odoo/pull/32550#issuecomment-481672276 ?

**Comment by pedrobaeza** [comment]
Yes, as it's said that is an incorrect configuration.
