### ISSUE TITLE
Automated action create record 15 times

### ISSUE THREAD

**Issue by alielgarhi** [odoo/odoo#27642]
in odoo 11 when i create automated action to create record in model it create record 15 time
any idea 

v11

**Comment by Yenthe666** [comment]
Hi there,

This is not really a bug but a question about how to do something.
You should ask this on the official help forums (at https://www.odoo.com/forum/help-1) where plenty of people can help you. Do add some screenshots/info there though as with this question nobody can help you right now.

Regards,
Yenthe
