### ISSUE TITLE
[12.0] Date widget does not accept dates before 01/01/1900

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#27648]
Impacted versions:
12.0, 11.0, 10.0, 

Steps to reproduce:
Create a new project Task.
Set as Deadline 01/01/1900 and press TAB - it works.
Set as Deadline 01/01/1899 and press TAB - it errors.

Current behavior:
Does not allow to select (and open forms with) dates before 01/01/1900. 

Expected behavior:
Should allow to select (and open forms with) dates before 01/01/1900.

Video/Screenshot link (optional):

**Comment by Linekio** [comment]
I add that the ORM doesn't accept dates prior to 01/01/1000, because of a condition on the length of the string:
```
(Odoo 11.0)
>>> from odoo import fields
>>> from datetime import date, datetime
>>> datemin = fields.Date.to_string(date.min)
>>> print(datemin)
1-01-01
>>> fields.Date.from_string(datemin)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benoit/Bureau/odoo/odoo/fields.py", line 1524, in from_string
    return datetime.strptime(value, DATE_FORMAT).date()
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '1-01-01' does not match format '%Y-%m-%d'
>>> 
>>> datetimemin = fields.Datetime.to_string(datetime.min)
>>> print(datetimemin)
1-01-01 00:00:00
>>> fields.Datetime.from_string(datetimemin)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benoit/Bureau/odoo/odoo/fields.py", line 1597, in from_string
    return datetime.strptime(value, DATETIME_FORMAT)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '1-01-01 00:00:00' does not match format '%Y-%m-%d %H:%M:%S'
>>> 

```

**Comment by pedrobaeza** [comment]
The problem with the date is known and it's a platform limitation:

https://bugs.python.org/issue1777412

You should have a Python version without that problem.

**Comment by pedrobaeza** [comment]
Have you tried with Python 3.5 which is the official Python supported version? Any way, there's maybe a problem also on JS side.

**Comment by dreispt** [comment]
Using `python3` in Ubuntu 14.04:
```
Python 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.date(1876, 2, 3).strftime('%Y-%m-%d')
'1876-02-03'
```

**Comment by pedrobaeza** [comment]
@ged-odoo do you know any problem with dates on JS part (maybe the date library)?

**Comment by BlommaertsEdwin** [comment]
Was there a solution for this as I'm having the same issue?

**Comment by Yenthe666** [comment]
Good news, starting from V14 you will be able to go back to dates before 1900. In fact, you can go all the way back to 01/01/0001.
Fixed in https://github.com/odoo/odoo/pull/51406
