### ISSUE TITLE
Unable to print Quotations and Sale Orders from portal

### ISSUE THREAD

**Issue by gan-odoo** [odoo/odoo#2764]
In Portal : portal user can not print Quotations and Sale Orders print.

Step to Reproduce : 

1)  Login in to portal
2) Go to Portal menu 
3) Click on Quotations or Sale Orders menu and try to print this.

Impacted Version : saas-3, 8.0, master

![portal_print](https://cloud.githubusercontent.com/assets/7599957/4439585/f1ef7d00-47b9-11e4-9e94-e40a57e46360.png)

**Comment by samuellefever** [comment]
Met the same issue.
The reason is that in order report, we have the sales person.
The portal user does not have access to that partner and the print fails.

My solution was to put sudo() in the chaining of the report so it can be printed.
Better solution?

**Comment by sle-odoo** [comment]
seems to be working fine noz

**Comment by dbape** [comment]
@samuellefever Can you please explain how'd you did that? I have no clue how to monkeypatch chaining of the report the right way

**Comment by samuellefever** [comment]
It should be fine now.
Do you still have the problem?
