### ISSUE TITLE
11E: Error when updating deliveries of kit products when sales order quantity updated

### ISSUE THREAD

**Issue by ChemHseOz** [odoo/odoo#27650]
Impacted versions: 11E

Steps to reproduce:
Create a sales order using a stockable product with a BoM type "kit". Lock confirmed orders in settings is NOT selected. Confirm sales order. Clicking "delivery" tab shows Picking operations is available to pick kit components but not picked/validated at this time - showing the components of the kit to picked.

Then after sales order confirmation, customer changes required quantity. So to update the ordered quantity - cancel order, set to quotation, change quantity. Reconfirm order.

Click on delivery shows one cancelled picking operation, and one new one with the updated quantities of the kit components. Complete picking operations on the active picking operation, and validate.

Current behavior:

If picking operations completed, the sales order still shows "Delivered quantity" as zero, even though picking quantities of kit components is correct. Stock moves have been generated for kit components and quantities are correct, but unable to invoice as delivered quantity not updated.

Expected behavior:

Delivered quantity should now be same as order quantity, allowing invoicing operations to be completed.

This ONLY occurs if quantity is updated. The process works fine for kit products if initial sales order quantity is not varied.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why do you cancel the sales order? You can change the quantity without cancelling it. Have you tried this way? I think that cancelling the order, you remove the link with the previous picking, and that's the reason you lose delivery orders.

**Comment by ChemHseOz** [comment]
Odoo wont allow us to edit the Sales Order because the kit and the kit components have different units. When you try to save the edited sales order, you are prevented by the error "Conversion from Product UoM kg to Default UoM Unit(s) is not possible as they both belong to different Category!."

**Comment by pgu-odoo** [comment]
@ChemHseOz , I tried to recreate the scenario in 11.0, and I am able to validate the invoice and the product qty of delivery is also updating according to SO. Please check the link as -
 https://youtu.be/aDgrZzD0k1g

Please let me know if any steps are missing or the other way in which you are facing the issue.
