### ISSUE TITLE
How to disable CSRF protection

### ISSUE THREAD

**Issue by happilymarrieddad** [odoo/odoo#27651]
Impacted versions:
all
Steps to reproduce:
post via Postman or any HTTP package to login
Current behavior:
unable to login due to csrf protection
Expected behavior:
ability to post login without csrf token

We are going to be running odoo internally so there is no need for csrf protection but for some reason I can't figure out how to disable it or remove it. When I use Postman I get the following error. I understand that I need to pass csrf=False via the `route` decorator but I don't know what that means. Am I supposed to pass some header or URL parameter or something? 

![selection_108](https://user-images.githubusercontent.com/6416323/46774898-fc648280-ccc1-11e8-842b-208369d630b9.png)
![selection_109](https://user-images.githubusercontent.com/6416323/46774901-fd95af80-ccc1-11e8-856d-fe4be7599f56.png)

```
web_1  | 
web_1  | * if the form is accessed by an external third party (e.g. REST API
web_1  |   endpoint, payment gateway callback) you will need to disable CSRF
web_1  |   protection (and implement your own protection if necessary) by
web_1  |   passing the `csrf=False` parameter to the `route` decorator.

```

**Comment by happilymarrieddad** [comment]
I tried to add `csrf=False` to the odoo.conf but that didn't seem to do anything.

**Comment by Yenthe666** [comment]
@mart-e I think you know this. If I'm not mistaking the only way is to override the routes of the controller and pass in `csrf_token=False` as parameter right?

**Comment by mart-e** [comment]
Hello,

> We are going to be running odoo internally so there is no need for csrf protection

You know that won't protect you against CSRF, right? If I trick you into displaying a page containing a link with a forged URL, I could make you fill a form without realising.

> If I'm not mistaking the only way is to override the routes of the controller and pass in csrf_token=False

Almost, the parameter is `csrf=False` to set on the route. However, it implies redefining all routes, which I guess is not what you want...

I don't see an easy way to disable CSRF and this is not something I would recommend anyway.

If you want to interact with Odoo programmatically, you may want to check our API documentation and use the XMLRPC routes instead.
https://www.odoo.com/documentation/12.0/webservices/odoo.html

**Comment by happilymarrieddad** [comment]
@mart-e Can you give me an example of how to do this? The documentation is very unclear unless you are using python/java/php/ruby. Are languages like Go/Nodejs not supported?

**Comment by Esau21** [comment]
Tengo un problema similar el servidor se ha caido de un sitio web como puedo solucionar este problema en odoo version 13????
alguien que me pueda ayudar y ya alla tenido la experiencia
![Sin título](https://user-images.githubusercontent.com/80347597/209444921-0fa48f1b-2b64-421a-86c0-ae133c6130f2.png)

**Comment by ihtaff** [comment]
did anyone find a solution for this issue ?

**Comment by Akshay-cp7** [comment]
This worked for me : https://stackoverflow.com/questions/37716329/bad-request-invalid-csrf-token-odoo-php
