### ISSUE TITLE
[11.0] Possibility to create partner from calendar view

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#27666]
The option "can_create: false" in web/static/src/js/views/calendarcalendar_renderer.js, line 76 doesn't work.

![sans titre](https://user-images.githubusercontent.com/25034353/46794012-3a57ba00-cd47-11e8-92ff-9759b7a6d749.png)

I propose to replace by "attrs: {can_create: false}":
[patch.txt](https://github.com/odoo/odoo/files/2468253/patch.txt)

**Comment by mart-e** [comment]
Thanks for the patch. Do you wish to create a PR with it so we can credit you?
