### ISSUE TITLE
[12.0] Contacts - wrong attachments number

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#27673]
**Impacted versions:**

12.0

**Steps to reproduce:**

1. Install constacts module
2. Create new partner
3. 3 attachments (information above chatter)

**Current behavior:**

![image](https://user-images.githubusercontent.com/5862658/46800462-0933b580-cd58-11e8-9866-1a32be71f0f4.png)

Expected behavior:

0 attachments

**Comment by grzekru** [comment]
http://383190-12-0-51d958.runbot18.odoo.com/web?#id=2327&action=169&model=res.partner&view_type=form&menu_id=117
![image](https://user-images.githubusercontent.com/5862658/46801088-ebffe680-cd59-11e8-837e-e5e105d054c5.png)

**Comment by Yenthe666** [comment]
That absolutely looks off honestly. 👍

**Comment by pedrobaeza** [comment]
There was changes done recently on this, so maybe that's the problem.

**Comment by sswapnesh** [comment]
Thats because of `image`,`image_medium` and `image_small` fields.
![screenshot 12](https://user-images.githubusercontent.com/16624719/46828179-3617b500-cdb8-11e8-8d55-97d3d3a50307.png)

**Comment by pedrobaeza** [comment]
Then I think that attachments should be left out of this count.

**Comment by sswapnesh** [comment]
It is from here
https://github.com/odoo/odoo/blame/12.0/addons/mail/models/mail_thread.py#L240

**Comment by sswapnesh** [comment]
@pedrobaeza  I believe counter is Correct here as `attachment=True` is passed in field Definition. But the Issue is with attachments previews.
![screenshot 13](https://user-images.githubusercontent.com/16624719/46829360-2fd70800-cdbb-11e8-8c7b-14e11e6e7715.png)

**Comment by pedrobaeza** [comment]
Well, I prefer that attachments that belongs to binary fields with `attachment=True` are not shown in the counter.

**Comment by sswapnesh** [comment]
True But not Sure How can we get this Information from Attachment itself. (So added second thought above)

**Comment by pedrobaeza** [comment]
It's possible as ir.attachment model has several fields for indicating that comes from a field, so it's a change on the attachment number computation to adjust the domain.

**Comment by sswapnesh** [comment]
Yes, `res_field` is there.
Added PR #27698 for same.
