### ISSUE TITLE
[12.0] Translation issue with nl_NL

### ISSUE THREAD

**Issue by JurreCl** [odoo/odoo#27681]
Impacted versions: 12

Steps to reproduce: Install CE version with dutch language

Current behavior: When installing applications the label on Enterprise applications says "Bijwerken" instead of "Upgraden". This causes confusion because "Bijwerken" is also used when you want to 'upgrade' a module when changes have been made.

Expected behavior: Label should be less confusing

Video/Screenshot link (optional): 
![screenshot from 2018-10-11 14-38-08](https://user-images.githubusercontent.com/418230/46804611-5cf7cc00-cd63-11e8-941f-fcaac0bbc9aa.png)

**Comment by Yenthe666** [comment]
Hi @JurreCl,

Thanks for the tip. This was just badly translated, I resolved it. In about a week it'll be in the synced terms and if you would update your language again it would be resolved.

Regards,
Yenthe
