### ISSUE TITLE
_set_taxes on invoices behaves badly in multicompany if product taxes set for another company

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#27696]
Impacted versions: 12 and prior

Steps to reproduce:
- Create a product as user for Company A.
- Set a tax on it for Company A.
- As a user in company B, set a default tax for the account associated with the product and/or company.
- As a multicompany user of Company A and B, in company B, create an invoice with the product.

When the onchange is triggered - no tax.

https://github.com/odoo/odoo/blob/11c950ef23faefb5b826c7fb6eb0dccb8e345ca0/addons/account/models/account_invoice.py#L1644-L1654

Its because first we evaluate product taxes for all companies, if none then the account, if none again then the company.  Then they are filtered by company, but in reality the only taxes that need filtering are product taxes (as account taxes and company taxes should already belong)

Maybe related to #20636 but I can't remember.

**Comment by Yenthe666** [comment]
@qdp-odoo for you 😉

**Comment by var-odoo** [comment]
@gdgellatly 
With the same configuration setup as you mentioned in this report, I didn’t face the issue. However, I did few changes in configuration and was able to face the issue. So, could you please go through the below configuration and have your say on this if it is somewhat similar to your issue or not?

Company setup:
Company A(Parent company)
Company B(child of Company A)

User setup:
Name: User A
Allowed Companies: Company A, Company B
Current Company: Company A

Product setup(common product to both companies):
Name: Product X
Customer Taxes = IGST 2%(Company B)
**Note: There are no default taxes configured for account related to Product X and there is no default tax for any of the companies**

Now, I try to create an invoice,

Expected result when User A creates invoice for Company B:
When I add a line for product X, IGST 2% should be applied by default

Current result when User A creates invoice for Company B:
When I add a line for product X, no tax is set by default

**Comment by gdgellatly** [comment]
opw-1963881
