### ISSUE TITLE
Problem to import bill of materials

### ISSUE THREAD

**Issue by marcelsavegnago** [odoo/odoo#27699]
Impacted versions:
12.0
Steps to reproduce:
Create a CSV file with columns with columns:
![image](https://user-images.githubusercontent.com/3595132/46827408-e8c32580-cd6e-11e8-8efc-9471f002bcbe.png)

- id 
- product_tmpl_id/id
- product_qty
- product_uom_id/id
- active
- bom_line_ids/product_id/id
- bom_line_ids/product_qty
- bom_line_ids/product_uom_id/id

Go to Manufacture / Bill of  Materials / Import

Current behavior:
insert or update on table "mrp_bom_line" violates foreign key constraint "mrp_bom_line_product_id_fkey" DETAIL: Key (product_id)=(19313) is not present in table "product_product". na linha 2

NOTE: The ID **19313** is from table product_template. Correct ID on table product_product is **9352**.

Expected behavior:
I did this same process a few days ago in version 11 and ran normally.
Both the product register and the bill of materials were extracted from another system.

One detail I noticed was that in my Odoo 11 installation the Product ID was the same as the Template ID. Already in the installation of Odoo 12 the IDs are different.

[produto_composicao2.txt](https://github.com/odoo/odoo/files/2470436/produto_composicao2.txt)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
