### ISSUE TITLE
[8.0] UnicodeEncodeError error in Buckaroo payment module

### ISSUE THREAD

**Issue by temmink** [odoo/odoo#2769]
When I try to test the payment Buckaroo module. I got the following error message after a successfully payment (test) has been serviced by Buckaroo.

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 112: ordinal not in range(128)

I think it's related to the following return data received from the form at buckaroo:

'BRQ_AMOUNT': u'49.95',
 'BRQ_CURRENCY': u'EUR',
 'BRQ_CUSTOMER_NAME': u'J. de T\xe8ster',
 'BRQ_INVOICENUMBER': u'SO013',

i'm on Ubuntu 14.04 lts with Odoo v8 from github.

Who can help me solve this?

**Comment by StefanRijnhart** [comment]
For the record, fixed in https://github.com/odoo/odoo/commit/e63cf3c1#diff-7d4816fc46b42a051b5e5d448da20cc7R89

**Comment by Yenthe666** [comment]
Indeed, fixed in the commit mentioned by Stefan.
