### ISSUE TITLE
[12], Online Trial : "Sampe Quotation" in sales got error 

### ISSUE THREAD

**Issue by nguyenquangtoan** [odoo/odoo#27690]
Impacted versions:12

Steps to reproduce: sales => setup screen has 4 steps, done first 3 them, click Send Sample

Current behavior: Error (attached)

Expected behavior:  Send Sample Quotation successfully
![screen shot 2018-10-11 at 10 45 22 pm](https://user-images.githubusercontent.com/294521/46816851-0496ed80-cda8-11e8-97eb-4ea00db6d059.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @nguyenquangtoan,

Thanks for your report.
I've just tested this on the latest 12.0 but it seems to work fine now. Can you try to reproduce it on an official Odoo test instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by nguyenquangtoan** [comment]
Hi @Yenthe666 

On http://runbot.odoo.com Enterprise, it works fine now. When shall you merge to make its fixed for online http://odoo.com/trial? We need this online trial works for potential customer demo success!

Thanks

**Comment by Yenthe666** [comment]
Hi @nguyenquangtoan,

I don't work for Odoo, I'm just a contributor.
@mart-e do you have any idea how often the trial version of Odoo is updated? There's a bug in that version that is not in the latest 12.

**Comment by mart-e** [comment]
Hello,

I believe you have set Vietnam as your company's country?
This problem has been fixed in 11.0 at 085d5045619d2cbd39124e9b045fb8d3242712d1, it will be ported to 12.0 (a few days).
