### ISSUE TITLE
Lot master data: not proper domain in product 

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#27706]
Impacted versions:
11

Steps to reproduce:
create lot master data

Current behavior:
all possible stockable products can be selected

Expected behavior:
only products with lot management can be selected

Video/Screenshot link (optional):

**Comment by pgu-odoo** [comment]
@ccandito  can you please provide the more details as -
1) From where only products with lot management can be selected?

**Comment by OpenTechValue** [comment]
Dear pgu-odoo,
in the form for managing batch master data: stock.view_production_lot_form
I've noticed also the same issue in version 12
regards
claudio

**Comment by sle-odoo** [comment]
Hi,
This was fixed by 454a05a0da2111719dc9b91f493fa02247965ea2

Regards
