### ISSUE TITLE
Shipping Address Selection Issue During Checkout

### ISSUE THREAD

**Issue by ashish-webkul** [odoo/odoo#27714]
Impacted versions: 12.0

Steps to reproduce: 

- Add any product to cart
- Then proceed to checkout and select other shipping address(**Make Sure address already exist because in case of new address this issue will never appear**)
-Then click on the confirm button then you will see the selected address is not there.
![download](https://user-images.githubusercontent.com/16383865/46864409-f2fd2680-ce37-11e8-8cfb-40dbe8a3d5ea.png)

Current behavior: Other shipping address in not selecting during checkout.

Expected behavior: Other shipping address should select during checkout.

Video/Screenshot link (optional):
http://nimb.ws/DnEQCR 
[shippingaddress.webm.zip](https://github.com/odoo/odoo/files/2472691/shippingaddress.webm.zip)

**Comment by pedrobaeza** [comment]
Thanks for the video. @JKE-be can you please check this?
