### ISSUE TITLE
Write-off for a Costumer Refund is not applied on the refund

### ISSUE THREAD

**Issue by alexander-heyber-manatec** [odoo/odoo#27716]
Impacted versions: 11e

Steps to reproduce: 
1) Create a Costumer-refund with
    Line1: Product 1 with price = 100
    Line2: Product 2 with price = 10
2) Confirm the refund
3) Register payment: 100
    keep difference open
4) Register a new payment: 0
    mark as paid/done (write off)
    
Current behavior:
- Refund is still marked as open
- Difference of Payment with 10 is still open

Expected behavior:
- Refund should be marked as done
- Difference of payment should be zero

Video/Screenshot link (optional):

**Comment by oco-odoo** [comment]
Seems to have been fixed since then. I'm closing the issue.
