### ISSUE TITLE
pdf generated on source code based Odoo v12  are blank  , any help ??

### ISSUE THREAD

**Issue by AliHussJaafar** [odoo/odoo#27723]
running package version by command line ( py odoo-bin) printing report gives blank pdf unless DPI was set to (ex. 300) however with running the service Odoo 12  from services result a normal pdf , how to fix that what command or conf are given with the service launch , 

both launch way resulting the following odoo.addons.base.models.ir_actions_report: Generating PDF on Windows platform require DPI >= 96. Using 96 instead.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
