### ISSUE TITLE
[11.0] Report printing as admin user does not work without company logo using 'Print' button

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#27732]
Impacted versions:
11.0

Steps to reproduce with **Print button**:
- Go to Settings -> Users & Companies -> Companies
- Delete logo company
- Go to Invoicing 
- Print and Invoice **using the 'Print Invoice' button**

Current behavior with **Print button**:
A popup window is displayed 

![choose document layout - odoo](https://user-images.githubusercontent.com/5191766/46876040-47d67800-ce0b-11e8-868f-9e416d9ff7aa.png)

Steps to reproduce with **Print menu**:
- Go to Settings -> Users & Companies -> Companies
- Delete logo company
- Go to Invoicing 
- Print and Invoice **using the 'Print' menu**

Current behavior with **Print menu**:
The report is printed without the company logo 

![screenshot_20181012_104636](https://user-images.githubusercontent.com/5191766/46876362-26c25700-ce0c-11e8-88df-d00c1d7d12f1.png)

Expected behavior:
To let to print the report without the logo company using the admin user or show the same behavior in both paths to print.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1XkqIIMSpjKfYAYS34vnoe8iOUjxLoO7n/view

**Comment by pedrobaeza** [comment]
This is the expected behavior first time you print a document: you have to select the layout to use from now on. It has nothing to do with the logo removal.

Closing as no real issue.
