### ISSUE TITLE
update link to module categories

### ISSUE THREAD

**Issue by kgeis** [odoo/odoo#27741]
Impacted versions: 12.0

Steps to reproduce: create a module and look at the manifest

Current behavior: has a link to https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml

Expected behavior: should refer to https://github.com/odoo/odoo/blob/master/odoo/addons/base/data/ir_module_category_data.xml

Files affected:
- odoo/cli/templates/default/\_\_manifest\_\_.py.template
- doc/howtos/backend/exercise-creation
- doc/howtos/website/module-empty

Sorry, I'd submit a PR but I can't sign the CLA.

**Comment by pedrobaeza** [comment]
I don't get the problem. Do you mean create a module with Odoo studio?

**Comment by kgeis** [comment]
Well, I reproduced it by creating a module with the odoo executable. The problem is just that the link is wrong in the comment in the template, so then the link is wrong in the manifest in the created module.

**Comment by pedrobaeza** [comment]
Uhm, I still don't figure out what do you mean by creating a module with the odoo executable. Can you put the exact steps you are doing? Maybe you are talking about the module scaffolding?

**Comment by sswapnesh** [comment]
@pedrobaeza  I can confirm this as Bug.
@kgeis  and here too `~/12/doc/reference/module.rst`

**Comment by mart-e** [comment]
> Sorry, I'd submit a PR but I can't sign the CLA.

Are you unsure how to sign the CLA? You can just create a PR with the `.md` file and I will merge it

**Comment by kgeis** [comment]
> Are you unsure how to sign the CLA?

I know how to sign a CLA, but I cannot accept the terms because of my employment. It conflicts with agreements I signed when hired and would need a lawyer at my institution to sign it. They refuse to sign agreements like this, primarily because of the patent grant clause. In order to sign it, I would need approval at the highest level of the institution.
