### ISSUE TITLE
Odoo website redirection security

### ISSUE THREAD

**Issue by OthmaneGhandi** [odoo/odoo#27745]
Impacted versions: V8, V9, V10, V11

Steps to reproduce: https://www.odoo.com/website/lang/fr_FR?r=http://www.youtube.com

Current behavior: When you put an URL like this : server_name/website/lang/fr_FR?r=http://www.youtube.com => it will redirect you to youtube or whatever link you put after ?r=

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@odony what's your opinion on this?

**Comment by sswapnesh** [comment]
Here is that route:
https://github.com/odoo/odoo/blame/11.0/addons/website/controllers/main.py#L108
Related Commit: https://github.com/odoo/odoo/commit/2a88020c104d474ac7effa05b5451be949a0050d#diff-167e2f4c21937f0a924ebe41ed38b16dR58

**Comment by naglis** [comment]
FWIW, there are multiple unvalidated (open) redirects in Odoo, but it is not considered as a security vulnerability by Odoo: https://www.odoo.com/page/security-nonvuln-redirectors.

**Comment by odony** [comment]
Thanks @naglis! Indeed, I had answered to @OthmaneGhandi directly that this is a known "false positive", and we have [a dedicated page](https://www.odoo.com/page/security-nonvuln-redirectors) with an explanation of our policy (and other vendor's similar policy).

It's fair for anyone to disagree with this policy, but before you try to patch it, it's important to realize that restricting redirects can cause serious complexities in the deployment of some generic features, and will not bring much increase in the security of users. There are many many ways to trick users into clicking on a malicious link, and this is just one of them. For an attacker, it takes much more effort and time to craft a convincing phishing page than to setup one of these tricks.
For instance, users who check the domain that appears when you hover on a link before clicking should be praised, but also warned that this is in fact trivial to circumvent (homograph attacks, js tricks, etc.)
