### ISSUE TITLE
Wrong sorting by price on eCommerce

### ISSUE THREAD

**Issue by pablo-lp** [odoo/odoo#27743]
Impacted versions: Odoo V11

Steps to reproduce:

Go to Website -> Settings -> Sale pricing settings and enable Multiple sale prices per product
Go to Pricelists and add a product to one (with a different price to Sales Price)
Assign that Pricelist to your user
Go to shop (eCommerce)
Sort by price

Current behavior: The prices are displayed correctly, but the products are ordered by the Sales Price instead of the displayed Pricelist price.

Expected behavior: Products should be sorted according to the price showed

Video/Screenshot link (optional):

![odoo-11-sort-problem](https://user-images.githubusercontent.com/31565658/46886677-dd99f380-ce5b-11e8-959d-9bf64844f324.png)

**Comment by sswapnesh** [comment]
Hello @pablo-lp 
I am able to Reproduce Same on Latest v11 Runbot Build http://384287-11-0-57ae94.runbot15.odoo.com/shop?order=list_price+asc and confirm this as bug.

Adding Steps to Reproduce with Screenshots: 
Tested With Admin user
![screenshot 14](https://user-images.githubusercontent.com/16624719/46901607-81bf8100-ced4-11e8-8846-f2e7798a3aa1.png)

Enable Pricelist
![screenshot 15](https://user-images.githubusercontent.com/16624719/46901612-969c1480-ced4-11e8-9ec0-4cafe8553264.png)
![screenshot 16](https://user-images.githubusercontent.com/16624719/46901613-97cd4180-ced4-11e8-9dfe-a30a34b230c8.png)
![screenshot 17](https://user-images.githubusercontent.com/16624719/46901615-98fe6e80-ced4-11e8-8b4a-2724d317eb60.png)


It Looks like Products are sorted and than Pricelist is applied to display Price.

**Comment by pedrobaeza** [comment]
@JKE-be for you

**Comment by JKE-be** [comment]
Hello

It is by design!

Filter is based on the list price and not the display price!

If you have thousand of products, it wil’ be very slow to calculate it !

**Comment by sswapnesh** [comment]
But still It is Confusing for End user. Will be better if  you consider as Wishlist.

**Comment by pablo-lp** [comment]
The prices are already taken from the Pricelist so it should not be slower to sort the records using that price, in my opinion. I consider it a design error

**Comment by JKE-be** [comment]
@pablo-lp 

`The prices are already taken from the Pricelist..., in my opinion.`
You are wrong, it uses the float field list_price on the product record.

`... it should not be slower to sort the records using that price, in my opinion.`
You are wrong, it will be slower to recompute each price for your current pricelist. So yes it could become very slow in case you have many product and pricelists !

`I consider it a design error`
Not really imo, it is a reasonable trade off.
A wishlist feature could be to allow to sort (if option enable only!) on website price.
Like that it allow small eCommerce of 20 product to sort it by Website Price specifically!

**Comment by AnilKesariya** [comment]
Same issue for v13, still persist. Any suggestion if we can improve based on price list will not slower performance.

**Comment by JKE-be** [comment]
Yes, and unfortunately for v15 too.

There are no solutions to have something without 'slower' performance.
You cannot do more with less resource.
What we need is to find the good compromise

It has been done with a cache, but ofc it will not scale for big db, so just cancelled. Here the PR https://github.com/odoo/odoo/pull/33897, you can probably backport locally a part of this one

//cc @pierre-pde

**Comment by JN-Klev** [comment]
Is there already a solution for this? Same problem here (V15).
And, what is 'slow'? I'd rather have a 'not so fast' but correct website than a fast but incorrect website.

**Comment by JKE-be** [comment]
What is slow is that you have to calculate for each product... what is the price for your current pricelist and your current promotion, ... 

It is not really wrong, it is just sorted by public sale price instead of your current customer price.

As mentioned in my previous comment, you can use code #33897 if you need it, but no plans to merge it into the main release.

KR
