### ISSUE TITLE
Odoo 11 Unable to Install Purchasing Module (ValueError: Element '<group name="invoicing">' cannot be located in parent view) 

### ISSUE THREAD

**Issue by OEGEM** [odoo/odoo#27748]
Impacted versions:11

Steps to reproduce:
Hi,

there is no group named invoicing in view product_template_form_view defined in module product, see the view code here:

https://github.com/odoo/odoo/blob/11.0/addons/product/views/product_views.xml

but in module sale, the view product_template_form_view_invoice_policy inherit this view, and try to insert in group invoicing some fields, but the group invoicing doesn't exist in view product_template_form_view , this is the cause of the error, see the view code here :

https://github.com/odoo/odoo/blob/11.0/addons/sale/views/sale_views.xml
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://www.odoo.com/fr_FR/forum/aide-1/question/odoo-11-unable-to-install-purchasing-module-valueerror-element-group-name-invoicing-cannot-be-located-in-parent-view-140687

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot (https://runbot.odoo.com - admin/admin).

**Comment by sswapnesh** [comment]
Uninstallation of `purchase` works fine. 
`<group name="invoicing">` is defined in Account module at https://github.com/odoo/odoo/blob/11.0/addons/account/views/product_view.xml#L27

**Comment by OEGEM** [comment]
Hi,
yes but xml_id of linked view is account. product_template_form_view, not
product. product_template_form_view where the inherit view is made.
Bye

Le sam. 13 oct. 2018 à 06:43, Swapnesh Shah <notifications@github.com> a
écrit :

**Comment by OEGEM** [comment]
perhaps a module dependecies problem, this is not a problme for me, but
there is an error for a user on the odoo forum, see the link I add int the
ticket.
Bye

**Comment by OEGEM** [comment]
close the ticket I will try to solve the problem on the forum.
Thank you for your answers.
Bye
