### ISSUE TITLE
error in RecordCache Class, prefetch_field function.

### ISSUE THREAD

**Issue by mhamra** [odoo/odoo#27744]
Impacted versions: 11, 12

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

It seems there's an error in the last line of this function 

            if not self.env.cache.contains(self, field):
                exc = AccessError("No value found for %s.%s" % (self, field.name))
                self.env.cache.set_failed(self, field, exc)

Last line raises an exception because the 'set_failed' function expects an iterable.

It seems that the code could be corrected passing a list of one field.

self.env.cache.set_failed(self, [field], exc)

**Comment by pedrobaeza** [comment]
Can you please put a PR amending the problem?

**Comment by mhamra** [comment]
Pedro, could you please tell me how to put a PR?

**Comment by pedrobaeza** [comment]
This is the basic GIT flow:

- You fork the repo
- Make the modifications and commit it.
- Push to your fork
- Make a Pull Request

As an extra step, you need to sign Odoo CLA.

**Comment by mhamra** [comment]
Thanks Pedro,

I've edited the source code and from github and after that i've created a Pull Request

**Comment by pedrobaeza** [comment]
Great, although you need also the CLA part.

**Comment by mhamra** [comment]
added mhamra.md with the requested CLA content to odoo's 12.0 branch.

Please tell me if it's everything ok

**Comment by pedrobaeza** [comment]
#27911 The CLA bot is complaining that is not correct. Where have you signed it?

**Comment by pedrobaeza** [comment]
There's no need of signing, because the signing is done through the commit with your email. You have to make a PR (or include it on existing one) for its integration. Please read https://github.com/odoo/odoo/blob/11.0/doc/cla/sign-cla.md for further details.

**Comment by pedrobaeza** [comment]
Closing as the PR has been merged. It will arrive v12 soon.
