### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dpopiashvili** [odoo/odoo#27754]
Hi

I'm trying to run odoo from source code by following this docs https://www.odoo.com/documentation/master/setup/install.html#setup-install-source.

I have installed all requirements, created postgre user, but when I try to navigate to localhost:8069 I get internal server error. The terminal displays the following error message:

```
 2018-10-13 15:31:44,966 18132 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/app/src/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/app/src/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/app/src/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/app/src/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/app/src/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/app/src/odoo/http.py", line 1470, in dispatch
    ir_http = request.registry['ir.http']
  File "/app/src/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -

```

Any idea what could be wrong?

Also the server is trying to run some queries on DB in background but is failing. I get this outputs as well:
```
2018-10-13 15:34:43,069 18132 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database odoo. 
2018-10-13 15:34:46,047 18132 ERROR odoo odoo.sql_db: bad query: b"SELECT latest_version FROM ir_module_module WHERE name='base'"
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
```

Do I need to initialize database or the application will populate the schema automatically? It is not mentioned in the docs.

Thanks

**Comment by abate** [comment]
same problem here. This can be reproduced using the following docker-compose snippet : 

```
  odoo:
    image: odoo:12.0
    depends_on:
      - odoodb
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-web-config:/etc/odoo
    labels:
      - traefik.backend=odoo
      - traefik.frontend.rule=Host:erp.tzalpha.net
      - traefik.docker.network=proxy
      - traefik.port=8069
    environment:
    - HOST=odoodb
    - USER=EdaViedgshdwev8
    - PASSWORD=aDdfggdsgdsgdjjjjlaisdgfoo8
    networks:
      - internal
      - proxy

  odoodb:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=aDdfggdsgdsgdjjjjlaisdgfoo8
      - POSTGRES_USER=EdaViedgshdwev8
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=false
    networks:
      - internal
```

**Comment by dpopiashvili** [comment]
I solved the issue by using postgres:10.0 image if someone will find it useful

**Comment by idelisGe** [comment]
I solve this putting postgres like db_name in the odoo_conf file
...
... db_name = postgresql
...
after the server config everything again access to the browser like always
.... localhos:port/web/database/selector
... remember remove this line in the config file after create a new database or set false value
I'm using ubuntu 18.04 , and odoo 12 version

**Comment by IlirBajrami** [comment]
> I solve this putting postgres like db_name in the odoo_conf file
> ...
> ... db_name = postgresql
> ...
> after the server config everything again access to the browser like always
> .... localhos:port/web/database/selector
> ... remember remove this line in the config file after create a new database or set false value
> I'm using ubuntu 18.04 , and odoo 12 version

wheres the odoo_conf located?

**Comment by idelisGe** [comment]
sorry about 'odoo_conf' this is not a special file it simple the odoo config file and it normally be in the odoo folder, but depends of your installation. I put odoo_conf in my comment because in my case use this name .. odoo_conf.config, but the common name is .. odoo.conf

**Comment by emenent98s** [comment]
> db_name

many thanks.. issue resolved
