### ISSUE TITLE
[11/12] Wishlist: Ability to Disable Export records for User

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27750]
Impacted versions: 11,12

Steps to reproduce: 
Disable ` Import & Export` from General Settings
![screenshot 3](https://user-images.githubusercontent.com/16624719/46902346-a3733500-cee1-11e8-8573-03e089f9917f.png)

Current behavior: It does not Disable Export Data
![screenshot 4](https://user-images.githubusercontent.com/16624719/46902361-c6054e00-cee1-11e8-92d1-66546ab8c8dc.png)

Expected behavior: It should disable Export as well

Video/Screenshot link (optional):

Maybe this can be considered as bug as Description states` Import & Export`

**Comment by pedrobaeza** [comment]
In this case I think it's only about the text. It should put only "Import". @mart-e do you confirm this?

For restricting exporting, we have the OCA module web_disable_export_group: https://github.com/OCA/web/pull/1061

**Comment by mart-e** [comment]
Hi,

Well, the description of the option only talks about import so I think this is fine.
I guess the idea of the label was that the possible flow now is to export, modify and import back.
Disabling export is not planned at the moment.

**Comment by sswapnesh** [comment]
> Disabling export is not planned at the moment.

I see it coming at https://github.com/odoo/odoo/pull/45400


-------------------
Can someone from Odoo Please report to Github about the Broken search? (I already did but no more updates)
![Screenshot from 2020-02-18 23-57-37](https://user-images.githubusercontent.com/16624719/74765977-822b1180-52aa-11ea-80cc-0c4bfe3ffca7.png)


I had to google it instead 
![Screenshot from 2020-02-18 23-56-43](https://user-images.githubusercontent.com/16624719/74765921-66277000-52aa-11ea-8359-74d1f4a09cd6.png)

Cc @Yenthe666

**Comment by mart-e** [comment]
> Can someone from Odoo Please report to Github about the Broken search? 

You know everybody can [contact the github support](https://support.github.com/contact), we don't have magical priority support ;-)
And for your search, you have to check [in the closed issues](https://github.com/odoo/odoo/issues?q=is%3Aissue+Disable+Export+is%3Aclosed), not opened

And yes, one and an half year later, we are working to add the feature ;-)

**Comment by sswapnesh** [comment]
![](https://user-images.githubusercontent.com/16624719/74765977-822b1180-52aa-11ea-80cc-0c4bfe3ffca7.png)
Still 0 Closed


I contacted them from two accounts but one Reply says It will be handled in Priority if Reported from Repo owner.
