### ISSUE TITLE
Descrepancy between Debian Depends and setup.py install_requires

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#27752]
Impacted versions: 11.0, 12.0 (10.0 too probably)

Steps to reproduce:

In debian/control, pyldap, qrcode and vobject are recommended dependencies. In setup.py they are mandatory, as part of install_requires.

As a consequence when trying to pip install a library that has odoo in its install_requires in an official Odoo docker image, pip tries to install the missing dependencies, which fails because the required build tools are not present.

Current behavior:

This fails

```bash
docker run -it --rm --user 0 odoo:12 bash
pip3 install odoo12-addon-queue_job
```

The error is

```
[...]
Failed to build vobject python-ldap          
Installing collected packages: odoo12-addon-queue-job, pyasn1, pyasn1-modules, python-ldap, pyldap, qrcode, vobject
[...]
```

Expected behavior:

pip3 install should not try to install python-ldap, qrcode and vobject since odoo is already installed as a debian package.

Proposed solution:

Either make python3-ldap, python3-vobject, python3-qrcode required dependencies in the debian package,
or move them to extra_requires in setup.py.

**Comment by sbidoul** [comment]
To be noted, the rpm package does require python3-pyldap and python3-vobject.

**Comment by sbidoul** [comment]
@antonylesuisse it would be cool if you could consider this one for easier packaging and distribution.

I made #28371 and #28372 as possible solutions.

If this is deemed to risky for stable, then it would be nice to have the missing dependencies installed by default in the 10/11/12 official docker images.

**Comment by antonylesuisse** [comment]
I'm ok to include them in master as they are arch: all. Ldap used to be a binary module.

**Comment by d-fence** [comment]
There is no problem with qrcode and vobject. So, as said by @antonylesuisse I did a PR to include them as Debian dependencies in master : #28588

ldap is another problem:

1. It's still not pure python
2. The versions are different in the [latest Debian](https://packages.debian.org/stretch/python3-pyldap) and the[latest Ubuntu LTS](https://packages.ubuntu.com/bionic/python3-ldap). The latter is a transitional package to python3-ldap to follow the upstream version.

There is a pure python [ldap python package](https://pypi.org/project/python3-ldap/) which is already packaged in [Debian](https://packages.debian.org/stretch/python3-ldap3) and [Ubuntu](https://packages.ubuntu.com/bionic/python3-pyldap). But this one is not used by Odoo and the API is not the same AFAIK.

What I propose is to modifiy the Docker Odoo 11.0 and 12.0 images to include python3-pyldap as a dependency. I think that it would solve the current issue.

**Comment by sbidoul** [comment]
> What I propose is to modifiy the Docker Odoo 11.0 and 12.0 images to include python3-pyldap as a dependency. I think that it would solve the current issue.

Fine with me. But then why not adding vobject and qrcode too for the sake of consistency setup.py install_requires?

**Comment by d-fence** [comment]
You are right as the fix will only stands in master :+1:

**Comment by sbidoul** [comment]
@d-fence thanks for the fix in master. 

Do you plan the 3 packages to the stable docker images?

**Comment by d-fence** [comment]
Sure, I'll do it ASAP

**Comment by d-fence** [comment]
Docker images landed here: https://github.com/odoo/docker/commit/05c776bcb2b0c8cda8d6fbb0bf93818b6c2625c7

**Comment by sbidoul** [comment]
@d-fence great! Many thanks for the thorough followup on this.
