### ISSUE TITLE
Testing In-App Purchases (12.0)

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#27753]
Is there a way to test IAP modules cleanly?

I have the problem that in order to get credits in sandbox mode, I have to manually change the endpoint and then unlock enough credits. But this is not possible in an automated test scenario, which creates a new database.

I programmed a workaround, but it looks more like a hack than anything else. I would be very grateful for information on how this scenario can be better solved.

``` python
class RemoteTestCase(common.HttpCase):
    
    def setUp(self):
        super(RemoteTestCase, self).setUp()
        self.provider = RemoteConverter(env=self.env)
        self.params = self.env['ir.config_parameter']
        self.account = self.env['iap.account'].get('<service>')
        self.params.set_param('<service>.service_key', SERVICE_KEY)
        self.params.set_param('iap.endpoint', 'https://iap-sandbox.odoo.com')
        self.params.set_param('<service>.endpoint', 'http://%s:%s' % (HOST, PORT))
        self.sandbox_credits()
        
    def tearDown(self):
        super(RemoteTestCase, self).tearDown()
    
    def sandbox_credits(self):
        session = requests.Session()
        data = {
            'dbuuid': self.params.get_param('database.uuid'),
            'service_name': '<service>',
            'account_token': self.account.account_token,
            'credit': 0,
        }
        resposne = session.get("https://iap-sandbox.odoo.com/iap/1/credit", data=data)
        content = html.fromstring(resposne.content)
        message_xpath = "//h3/span[contains(@class, 'text-success')]"
        message = next(iter(content.xpath(message_xpath)), None)
        if message is not None:
            _logger.info("%s Credits left on Sandbox Mode" % message.text_content())
        else:
            form_xpath = "//form[@action='/iap/1/sandbox_buy']"
            form = next(iter(content.xpath(form_xpath)), None)
            if form is not None:
                csrf_token = next(iter(form.xpath("//input[@name='csrf_token']/@value")), None)
                pack_id = next(iter(form.xpath("//input[@name='pack_id']/@value")), None)
                iap_account_id = next(iter(form.xpath("//input[@name='iap_account_id']/@value")), None)
                back_url = next(iter(form.xpath("//input[@name='back_url']/@value")), None)
                data = {
                    'csrf_token': csrf_token,
                    'pack_id': pack_id,
                    'iap_account_id': iap_account_id,
                    'back_url': back_url,
                }
                resposne = session.post("https://iap-sandbox.odoo.com/iap/1/sandbox_buy", data=data)
                _logger.info("Buy credits: %s" % resposne.status_code)
            else:
                _logger.error("Buy credits failed!")
```

**Comment by pedrobaeza** [comment]
@mart-e maybe there's a test class for this kind of things or can it be included with similar code?

**Comment by nhomar** [comment]
I think the best way is [mock it!](https://docs.python.org/3/library/unittest.mock.html)

**Comment by pedrobaeza** [comment]
Although mock is a good way for simulating and ending point that is not reachable easily, it always hides possible problems in a real scenario, so if there's the possibility of testing things with real IAP, it's a better option IMO.

**Comment by rrahir** [comment]
Hi,
Indeed this tool could be very useful, unfirtunately we don't have it for now and I plant to implement it during the week. 
What I suggest would be dedicated account tokens to trigger the different responses from the iap server.

Something like:
 send account_token:1111 -> always receive a positive answer // transaction token
send account_token:0000 -> always receive negative answer // Insufficient credit error

Tell me what you think of it.

**Comment by keshrath** [comment]
I think that would be a good choice for testing different scenarios. One problem of my workaround is that it is only possible to purchase credits once per database in sandbox mode. So it is not very easy to test error cases.

**Comment by rrahir** [comment]
Hi, we deployed the test module on iap-sandbox, here is a small doc you can use to try it yourself.  A big update of the documentation for IAP will follow in the coming 1 to 2 weeks but here is waht you need to test the api:

Some predefined "account_token" values can be used to test the different routes:
        "000000": non-exisitng account (balance = 0 credits)
        "000111": existing account with not enough credit to perform the requested action (balance 10 credits // still will fail when trying to charge)
        "111111": existing account which always has enough credit (balance = 100000 credits)

    When an action is authorized, the "/iap/1/authorize" route returns a dummy token that will be considered valid by the "/iap/1/capture" and "/iap/1/cancel" routes.

**Comment by keshrath** [comment]
Thanks for your answer. I will test it over the next week, but I think it should be a good solution. So yes I think the issue can be closed.

**Comment by rrahir** [comment]
@pedrobaeza @keshrath FYI, Some small features have been added for both the app developer and users. They are present in theupdated documentation in https://github.com/odoo/odoo/pull/28866/commits/b5b209298748dce867973b9f8365d39d48ba3217

**Comment by pedrobaeza** [comment]
Thanks for the follow-up
