### ISSUE TITLE
Accounts Payable account mandatory on Purchase Receipts when a user select 'Pay Directly'

### ISSUE THREAD

**Issue by passion342** [odoo/odoo#27765]
Impacted versions: Odoo 12 (E). 

Steps to reproduce:
1- Go to Accounting -> Vendors -> Receipts. 
2- Create a new Purchase Receipt and set the Payment to 'Pay Directly'. 

Current behavior:
Odoo asks you to select the Accounts Payable account even though a user has selected to pay directly. 

Expected behavior:
Odoo shouldn't ask for Accounts Payable account when payment is being made directly. The resultant Journal Entry also has Accounts Payable account. 
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/28576333/46919448-1ae7b800-cff9-11e8-90b8-03ae5f54810f.png)

**Comment by pedrobaeza** [comment]
"Pay directly" only affects to the validation stage for performing also the payment journal entry, but the account payable/receivable is needed because both journal entries should reflect the debit and credit operation on that account for a correct accounting.

Closing as no real issue.
