### ISSUE TITLE
[11] Hr Attendances - Multiple check-in

### ISSUE THREAD

**Issue by citronpower** [odoo/odoo#27762]
Impacted versions: Odoo11

Steps to reproduce: While check-in/check-out to quickly in Kiosk mode with badges

Current behavior: Multiple records are saved instead of one and create problem at the next check-in/check-out because there is a record which has not been checked-out but also an other, more recent, which has been check-out. Then Odoo is confused.

Solution found (if someone could check it and, if it is in order, pull it):
Change in hr_attendance/static/src/js/greeting_message.js function start():
```
start: function() {
        if (this.attendance) {
            this.attendance.check_out ? this.farewell_message() : this.welcome_message();
        }
        // remove this
        // if (this.activeBarcode) {
        //     core.bus.on('barcode_scanned', this, this._onBarcodeScanned);
        // }
    }
```

Thanks in advance for your feedback.

**Comment by pedrobaeza** [comment]
The problem maybe is because you have several tabs opened?

**Comment by citronpower** [comment]
No... Unfortunately its not the problem. 
It really happens when doing the check-in/check-out too fast (for example when many employees are leaving). If we wait enough between two check (until the greeting message page has left ~), this problem doesnt seam to occur.

**Comment by hw-aka** [comment]
This has happened to me too. Sometimes, when an employee does check-in/out, there are multiple check-in records in the system which blocks future records. 

It looked like the scanner was sending data too quickly without delay in between, but when I tested with a text editor, there was a delay - so not the problem with scanner. Even if there is a buggy scanner which sends data with no delay, it should be in-out-in-out, not in-in-in.

I could not find the problem, had to inherit the `attendance_scan(self, barcode)` function to discard the second scan of the same user within five seconds.

**Comment by RomainLibert** [comment]
Fixed by https://github.com/odoo/odoo/pull/28150
