### ISSUE TITLE
[10/11/12] Removal strategy not respected for sub-location

### ISSUE THREAD

**Issue by mehdi-ghezal** [odoo/odoo#27761]
Impacted versions: 10/11/12 (previous as well but not supported anymore)

Steps to reproduce: 

* Enable multi-location and tracking settings
* Create a location **WH/Stock/Sub Location** with LIFO removal Strategy 
* Create a storable product **Product A** tracked by lot
* Create a receipts transfer for **Product A** and choose **WH/Stock/Sub Location** for destination location
* Receive products as **LOT-1**
* Repeat and receive products as **LOT-2**
* Create a delivery order transfer with **Product A** and let **WH/Stock** for the source location
* Confirm, mark as todo and check availability
* **LOT-1** has been reserved

Current behavior: 

The first received product has been reserved

Expected behavior:

The last received product should be reserved

Reason:

The removal strategy (for location) is based on the stock.move source location that depend of the stock.picking source location. 

When you create the delivery order transfer if you setup *WH/Stock/Sub Location* for the source location, everything work as expected. 

Comment:

In technical point of view it make perfect sense, the picking is related to WH/Stock, WH/Stock is setup to use FIFO et voilà ! 

In user point of view it's inconsistent as he setup a location to use a specific removal strategy and the picking operations doesn't follow this strategy.

**Comment by pedrobaeza** [comment]
@jco-odoo what do you think about this?

**Comment by jco-odoo** [comment]
It works fine the way it does now.  The location on the move/picking is a parent location to be able to apply the putaway strategy afterwards, so it is just logical to check the putaway over there.

**Comment by mehdi-ghezal** [comment]
> So it is just logical to check the putaway over there.

Maybe I didn't get it but the behaviour I described was about the removal strategy.

**Comment by jco-odoo** [comment]
It is the same reasoning.
