### ISSUE TITLE
odoo point of sale USBerror [errno 110]

### ISSUE THREAD

**Issue by hengkysipocs** [odoo/odoo#2778]
when i ttry to print via proxy 
the result is error log instead of the receipt
USBError: [Errno 110] Operation Timed Out

**Comment by Yenthe666** [comment]
Hi @hengkysipocs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
