### ISSUE TITLE
[12] Outgoing Mailserver - Test Connection fails

### ISSUE THREAD

**Issue by poschinger** [odoo/odoo#27790]
Impacted versions:
12
Steps to reproduce:
Add new Outgoing Mailserver
Try to Test Connection 

Current behavior:
Test-Connection funcionality responds:  5.5.2 Send hello first
Expected behavior:
Test-Connection should work as in Odoo 10/11, but in 12 it does not (with same SMTP Settings as in 10/11)
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something with your mail server, not an Odoo problem.

Closing as no real issue.
