### ISSUE TITLE
[12.0.x] Reply message chat error in Discuss

### ISSUE THREAD

**Issue by nguyenquangtoan** [odoo/odoo#27812]
Impacted versions:12.0.x

Steps to reproduce:Dicuss chat

Current behavior: Click Reply

Expected behavior:

Video/Screenshot link (o
![screen shot 2018-10-15 at 10 15 27 pm](https://user-images.githubusercontent.com/294521/46960224-3cfc3b80-d0c8-11e8-994b-2dcd94e1ef29.png)
![screen shot 2018-10-15 at 10 15 42 pm](https://user-images.githubusercontent.com/294521/46960225-3cfc3b80-d0c8-11e8-8a94-7d1e60c4894b.png)

ptional):

**Comment by pedrobaeza** [comment]
Is this reproducible in runbot (https://runbot.odoo.com - admin/admin)?

**Comment by sswapnesh** [comment]
@pedrobaeza 
I am able to Reproduce this too. (But tracback is different -- I am on Linux/Chrome)
![screenshot 15](https://user-images.githubusercontent.com/16624719/46964417-a2026200-d0c5-11e8-85f7-d88f28c5e7bd.png)
![screenshot 16](https://user-images.githubusercontent.com/16624719/46964476-c9f1c580-d0c5-11e8-930e-ffc3c54620b1.png)

**Comment by pedrobaeza** [comment]
OK, tag this.

**Comment by sswapnesh** [comment]
Works well now.
Should be closed in https://github.com/odoo/odoo/pull/28744
cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
Thanks for the follow-up, Swapnesh. Closing this.
