### ISSUE TITLE
Duplicate Product SubMenu in Sales/Configuration

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#27817]
Impacted versions: 12.0 (not present prior)

Steps to reproduce:
May need to enable variants and/or UoM in Settings
Current behavior:
2 Product submenus
Expected behavior:
1 product submenu

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/46976787-e114cf80-d126-11e8-9fff-a243a9fc6c7d.png)
![image](https://user-images.githubusercontent.com/5093264/46976916-35b84a80-d127-11e8-9ddf-c555f8697d74.png)

**Comment by Yenthe666** [comment]
This has been handled and fixed in https://github.com/odoo/odoo/commit/3f634f29bd042b7e13b8e48507f8aa7a3a7ec50c
