### ISSUE TITLE
Odoo Internal user added as a customer

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#27829]
Impacted versions:
Odoo 9,10,11
Steps to reproduce:
Create New internal user auto created "Is a customer" 
Current behavior:
Odoo Internal User created and customer create and checked "Is a Customer".
Odoo default maintain login user contact details is ok, but internal user created as customer.
While creating sale order internal user list display.
Expected behavior:
Remove "Is a Customer" while creating new user.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is the behavior for these versions and it's not going to be changed. On v12, the behavior has been changed already and a created user isn't a customer by default (except for created users from website).

Closing as won't fix.
