### ISSUE TITLE
[7.0] Warehouse Internal Moves Bug at duplicate

### ISSUE THREAD

**Issue by santiago-orozco** [odoo/odoo#2782]
When we try to duplicate an Internal Move in warehouse module, the number of the reference doesn't generates a new one, it's because it doesn't exist a "stock.picking.internal" in  ir.sequence  that the function copy in object "stock.picking" intents to search and obtain.

**Comment by Yenthe666** [comment]
Hi @hsom1988,

I can no longer reproduce this issue. Could you double check this on the latest Odoo code?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @santiago-orozco,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
