### ISSUE TITLE
[12.0] Wrong Number of Invoices in Dashboard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27859]
Impacted versions: 12.0

Steps to reproduce: 
![screenshot 11](https://user-images.githubusercontent.com/16624719/47044274-5a570580-d1ad-11e8-9b3e-5a0f56898f71.png)
(Also Video for that)
Current behavior: Wrong Number of Invoices

Expected behavior: Correct Number of Invoices based on Filter

Video/Screenshot link (optional):
https://drive.google.com/file/d/1TRF6MgFgxFYyk3cLFQzRRKmJc26GhwEM/view

**Comment by william-andre** [comment]
#29357

**Comment by sswapnesh** [comment]
Can't we correct this in v12.

**Comment by william-andre** [comment]
#29361 
Sorry, went too quickly. Here is the 12.0 PR

**Comment by Yenthe666** [comment]
Thanks!

**Comment by sswapnesh** [comment]
@william-andre  https://github.com/odoo/odoo/pull/28582 was already there with same PR
