### ISSUE TITLE
Email templates - No subject, and company name problem --> ascii ordinal not in range(128)

### ISSUE THREAD

**Issue by HaraldPanten** [odoo/odoo#27853]
Impacted versions: Odoo V11 (I'm not sure in older versions)

Steps to reproduce:

1- Create an email template for a model

2- In the content tab, I put:

Subject: example example example.

3- In the email configuration tab I put:

From: ${object.company_id.name|safe}

Current behavior:

The email is received without subject in my email client (Gmail).

If my company name has à, ó... (not ascii characters) the email is not sent and i get this message from the failed emails -->  

ascii
(...)
(...)
(...)
ordinal not in range(128)

Expected behavior: email should be sent, even without ascii characters and a subject should be shown when receiving an email in my email client.

Thanks it advance

**Comment by HaraldPanten** [comment]
Hi Pedro, thanks for your prompt reply.

When I change the company name (I remove the accents) , the email is properly sent. Even though, I still receive the (No subject) subject.

I think that the problem is the non UTF-8 codification of the From field, when it comes from the company name. (${object.company_id.name|safe}).

Is it possible?

**Comment by pedrobaeza** [comment]
Well, if you put full stack trace it would be more helpful.

**Comment by HaraldPanten** [comment]
Hi Pedro, I finally, removed my ${object.company_id.name|safe} field from "from" field. I put an email address instead as you suggested before.

Even though, I have no subject defined when receiving the email in my gmail account.

See attached files to see my template settings

Thanks!


![screenshot 1](https://user-images.githubusercontent.com/32449357/47026703-58b61f00-d166-11e8-8077-a16226cd9689.png)
![screenshot 2](https://user-images.githubusercontent.com/32449357/47026704-594eb580-d166-11e8-9161-296c67a91a1f.png)
![screenshot 3](https://user-images.githubusercontent.com/32449357/47026706-594eb580-d166-11e8-87cc-3e612ea7bb8b.png)
![screenshot 4](https://user-images.githubusercontent.com/32449357/47026707-594eb580-d166-11e8-8b5b-85089c71468f.png)

**Comment by pedrobaeza** [comment]
Subject thing is another topic. This can be because it's a translatable field and it's empty or invalid on the source term.

**Comment by pedrobaeza** [comment]
Harald, maybe this is related to #20713

**Comment by HaraldPanten** [comment]
Good morning Pedro,

It seems to be the same issue. Maybe we can close this one, I'll follow #20713 

Thank you so much for your help :+1:

**Comment by pedrobaeza** [comment]
OK, closing.
