### ISSUE TITLE
[12.0] Bug, Send a message in opportunity does not add customer as a follower (No email sent out)

### ISSUE THREAD

**Issue by seyed-mohammad-motahar** [odoo/odoo#27864]
Impacted versions:
12.0

Steps to reproduce:
Go to runbot
Create an opportunity against an existing customer
Send a message to that customer.
review the openchatter

Current behavior:
Odoo does send a message to the "Followers" AND "Email address of the customer but only internal followers will receive it OR if we already added customer as a follower manually !

Expected behavior:
When we click on send a message and we tick the email address of the customer (It is ticked by default) it should  add customer as a follower of this oppotunity and then send an email to that customer. Just like how we send email to customer from the sales app by clicking on "Send by email)

Video/Screenshot link (optional):
https://youtu.be/JxMsklFo3Xs

**Comment by pedrobaeza** [comment]
Thanks for the video. Indeed, it seems to be a problem right now on this version, as in previous versions, when ticking the box, the partner is added as follower and then the message is sent.

@tde-banana-odoo I think you are the right person to check this.

**Comment by tde-banana-odoo** [comment]
@alexkuhn
