### ISSUE TITLE
Procurement scheduler should assign stock to partially_available

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#27874]
Impacted versions: 11

Steps to reproduce:
1. Product A - on stock 5 pcs.
2. Sale order - 7 pcs. of A
3. Generated picking has reserved 5 pcs.
4. Increase stock to 7 pcs. (Update qty on Hand)
5. Run procurement scheduler
6. Picking still has reserved 5 pcs.
7. Click on "Check availiability" - now picking has reserved 7 pcs.

Current behavior:
Procurement scheduler not assign stock to moves in state partially_available, only assign to confirmed

Expected behavior:
Procurement scheduler assign stock to moves in state partially_available - after step 5 picking has reserved 7 pcs.

**Comment by pedrobaeza** [comment]
@jco-odoo can you please answer this?

**Comment by jco-odoo** [comment]
Indeed, that is a good point, but it changes behaviour of the stable version.  I wonder if they might even get priority over the confirmed ones.  @lap-odoo @sle-odoo @nim-odoo odoo/addons/stock/models/procurement.py:240

**Comment by lap-odoo** [comment]
I'm checking with @nim-odoo to see if this can be solved in stable versions (1895622). I'll let you know. Thanks for reporting this !

**Comment by Elkasitu** [comment]
Should be fixed by https://github.com/odoo/odoo/commit/a4059804cc766c98d9f7d55af2fbb27013c5b3dc
