### ISSUE TITLE
[11.0] add translations for self.env.lang wrong concept

### ISSUE THREAD

**Issue by xubiuit** [odoo/odoo#27881]
Hi guys,

I've checked on the concept of create `ir.translation` for field which has the translation=True.
I loaded 3 languages: Vietnamese, English, English (UK)
After created new product, system always create new 2 lines for name (other lines for other fields) for translation. I wondering why those lines are always Vietnamese and English (UK) even I am choosing Vietnamese or English (UK) is the user's language.
I recommend that the concept should be:
- If I am selecting Vietnamese as user's language, then create new 2 lines for English and English (UK)
- If I am selecting English as user's language, then create new 2 lines for Vietnamese and English (UK)
- If I am selecting English (UK) as user's language, then create new 2 lines for Vietnamese and English
The reason is, when I am selecting the Vietnamese as user's language, I will create the product by Vietnamese Name, then I will need 2 other lines to translate, I do not need 1 line for Vietnamese anymore. 
I found the line with default prevent `en_US` and will be create translation for other language in this:
https://github.com/odoo/odoo/blob/b29b545fe8464610ce04ac8be11e0356962d10d9/odoo/models.py#L3533

Please check the concept and let me know should we update this?

Thanks and Regards,
Binh Nguyen

**Comment by pedrobaeza** [comment]
It's not the user language, but the "native" language you choose when you create the DB who determines the language out of you are going to translate the rest. Any way, you will always have a translation from English to that native language at least.

Closing as this is not an issue, but a question.

**Comment by xubiuit** [comment]
I'm still confusing after checked your explanation since the native language should be determined (dynamically) by Customer who create the database (should be found at User-defined Defaults) instead of a hardcode `en_US` as native language
