### ISSUE TITLE
[12.0] Could not change button string in E commerce product page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27914]
Impacted versions: 12

Steps to reproduce: Runbot http://386026-12-0-bd004a.runbot13.odoo.com/shop/product/customizable-desk-9#

Current behavior:
![screenshot 23](https://user-images.githubusercontent.com/16624719/47105279-158ca680-d261-11e8-9ac4-04ae2aca8d14.png)
Change string and Save
![screenshot 24](https://user-images.githubusercontent.com/16624719/47105281-16bdd380-d261-11e8-860f-c25933afbfad.png)

`Server application error {"code":200,"message":"Odoo Server Error","data":{"name":"odoo.exceptions.ValidationError","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/models.py\", line 1100, in _validate_fields\n    check(self)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 338, in _check_xml\n    view_def = view.read_combined(['arch'])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 773, in read_combined\n    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 722, in apply_view_inheritance\n    source = self.apply_inheritance_specs(source, specs_tree, view_id)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 700, in apply_inheritance_specs\n    self.raise_view_error(_(\"Element '%s' cannot be located in parent view\") % tag, inherit_id)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 538, in raise_view_error\n    raise ValueError(message)\nValueError: Element '<xpath expr=\"//hr[@id='hr_product_attributes_simple']\">' cannot be located in parent view\n\nError context:\nView `Product attributes table`\n[view_id: 2914, xml_id: website_sale_comparison.product_attributes_body, model: n/a, parent_id: 2782]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 653, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 312, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 695, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 344, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 337, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 938, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/http.py\", line 517, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/web/controllers/main.py\", line 962, in call_kw\n    return self._call_kw(model, method, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/web/controllers/main.py\", line 954, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/api.py\", line 749, in call_kw\n    return _call_kw_multi(method, model, args, kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/api.py\", line 736, in _call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/website/models/ir_ui_view.py\", line 318, in save\n    super(View, self).save(value, xpath=xpath)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/web_editor/models/ir_ui_view.py\", line 198, in save\n    self.write({'arch': self._pretty_arch(new_arch)})\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/website/models/ir_ui_view.py\", line 66, in write\n    inherit_child.write({'inherit_id': website_specific_view.id})\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/website/models/ir_ui_view.py\", line 54, in write\n    website_specific_view = view.copy({'website_id': current_website_id, 'key': view.key})\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 449, in copy\n    return super(View, self).copy(default)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/models.py\", line 4223, in copy\n    new = self.with_context(lang=None).create(vals)\n  File \"<decorator-gen-32>\", line 2, in create\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/api.py\", line 451, in _model_create_multi\n    return create(self, [arg])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/addons/base/models/ir_ui_view.py\", line 418, in create\n    return super(View, self).create(vals_list)\n  File \"<decorator-gen-3>\", line 2, in create\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/api.py\", line 452, in _model_create_multi\n    return create(self, arg)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/models.py\", line 3504, in create\n    records = self._create(data_list)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/models.py\", line 3636, in _create\n    records._validate_fields(name for data in data_list for name in data['stored'])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/386026-12-0-bd004a/odoo/models.py\", line 1104, in _validate_fields\n    raise ValidationError(\"%s\\n\\n%s\" % (_(\"Error while validating constraint\"), tools.ustr(e)))\nodoo.exceptions.ValidationError: ('Error while validating constraint\\n\\nElement \\'<xpath expr=\"//hr[@id=\\'hr_product_attributes_simple\\']\">\\' cannot be located in parent view\\n\\nError context:\\nView `Product attributes table`\\n[view_id: 2914, xml_id: website_sale_comparison.product_attributes_body, model: n/a, parent_id: 2782]', None)\n","message":"Error while validating constraint\n\nElement '<xpath expr=\"//hr[@id='hr_product_attributes_simple']\">' cannot be located in parent view\n\nError context:\nView `Product attributes table`\n[view_id: 2914, xml_id: website_sale_comparison.product_attributes_body, model: n/a, parent_id: 2782]\nNone","arguments":["Error while validating constraint\n\nElement '<xpath expr=\"//hr[@id='hr_product_attributes_simple']\">' cannot be located in parent view\n\nError context:\nView `Product attributes table`\n[view_id: 2914, xml_id: website_sale_comparison.product_attributes_body, model: n/a, parent_id: 2782]",null],"exception_type":"validation_error"}}`

Expected behavior:

Video/Screenshot link (optional):

**Comment by qsm-odoo** [comment]
In fact, even stranger: Go to a product page -> HTML editor -> Add a space somewhere -> Save -> Crash. I will check.

**Comment by rdeodoo** [comment]
Multi-website issue, fix is coming. Basically an inherit hierarchy when copying the view tree to make it website specific
