### ISSUE TITLE
Inventory app does not show Implementation Guide.

### ISSUE THREAD

**Issue by RPrestigeR** [odoo/odoo#27917]
Impacted versions: 12.0.20181019

Steps to reproduce:

1. Install Odoo
2. Install Inventory App
3. Go to Inventory App

Current behavior:
Inventory overview is shown. No "progress bar" is shown in the menu bar.
![image](https://user-images.githubusercontent.com/44245013/47117352-bc555080-d229-11e8-942e-374840a92368.png)

Expected behavior:
Progress bar should be shown in the menu bar of the page, as shown [here](https://www.odoo.com/documentation/user/12.0/inventory/overview/start/setup.html).
![image](https://user-images.githubusercontent.com/44245013/47117400-d8f18880-d229-11e8-8287-ad38448ff572.png)

I am running Linux Mint 18.3 and installed the 12.0 community edition via the .deb from the download page. Uninstall and reinstalling the app results in the same behavior.

**Comment by RPrestigeR** [comment]
Uninstalling and reinstalling the program via apt results in the same behavior, even after purging. However, the purge does not seem to be complete, as the company information returns when I install again.

**Comment by thiDucTran** [comment]
running on Arch Linux with `odoo:latest` docker image (`7f81310cfbf9`) with same result.

**Comment by Yenthe666** [comment]
Hi,

Implementation guides where in fact removed in V12.
