### ISSUE TITLE
[8.0] greyed out items in navigation bar not recognizable in bright light

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#2791]
it is a usability issue

on clear days, bright sunshine the greyed out items in the menu nav bar are hardly recognizable, especially on mobile devices outdoors.

**Comment by Yenthe666** [comment]
Hi @ferdiga,

I'm closing this report as Odoo 8 is no longer officially supported (Odoo only goes back three versions).
As this is labelled wishlist it will keep coming up though!

Regards,
Yenthe
