### ISSUE TITLE
[12] Wrong number of Purchase Orders/Invoices in Portal

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27913]
Impacted versions: 12.0

Steps to reproduce: Runbot http://386026-12-0-bd004a.runbot13.odoo.com/my/home
Go to My Account

Current behavior:
![screenshot 20](https://user-images.githubusercontent.com/16624719/47104677-99de2a00-d25f-11e8-91a9-ef9ee1c17b38.png)
![screenshot 21](https://user-images.githubusercontent.com/16624719/47104679-9a76c080-d25f-11e8-9735-d338542d6bc7.png)
![screenshot 22](https://user-images.githubusercontent.com/16624719/47104719-b4180800-d25f-11e8-9ad6-057080d5edb1.png)

Expected behavior: Correct Number of Purchase Orders/Invoices

Video/Screenshot link (optional):

**Comment by celm1990** [comment]
See #27475

**Comment by celm1990** [comment]
Posible solution #27583
Take into account my comments for inheritance on other modules

**Comment by sswapnesh** [comment]
Yes, I was not aware about that but still it has issue in Purchase Order's Domain.

**Comment by rdeodoo** [comment]
Fixed for invoice count with https://github.com/odoo/odoo/commit/01f642c17cea504bbdbabe45303021ed77861a6c
@sswapnesh I checked on runbot and it seems like everything is working fine now, can we close?

**Comment by sswapnesh** [comment]
@rda-odoo 
Works well.
Now Counter is in align with  Number of Records, However Both refers to different terminology.

**Comment by rda-odoo** [comment]
@sswapnesh I think that message was for @rdeodoo   :)

**Comment by sswapnesh** [comment]
@rda-odoo Sorry for wrong ping.
