### ISSUE TITLE
Broken assets bundle when using .less files

### ISSUE THREAD

**Issue by jakubhruby** [odoo/odoo#27922]
Impacted versions: 12

Steps to reproduce:
1. have a .less file in a module
2. let odoo make an asset bundle

Current behavior:
- bundle is malformed
- layout is broken
- odoo throws a JavaScript error

Expected behavior:
- bundlle is ok
- layout is ok
- no errors

All is caused by a bug in /odoo/addons/base/models/assetsbundle.py:442. Compiled `source` is not attached to `compile` string, but overwrites it. There needs to be `+=` instead `=`.

**Comment by jakubhruby** [comment]
> I remember this has been already notified, and maybe there's also a PR. Can you please search on issues/PRs?

I did, but I haven't found any PR/issue.

**Comment by pedrobaeza** [comment]
@JKE-be do you remember this case?

**Comment by jakubhruby** [comment]
So... How's this going?

**Comment by rdeodoo** [comment]
Hi fix is coming at https://github.com/odoo/odoo/pull/29109

**Comment by jakubhruby** [comment]
Nice, thanks

**Comment by rdeodoo** [comment]
You are welcome, sorry for the long time before merging a fix.
Thank you for reporting it
You had the solution, next time do not hesitate to create a PR if you can, as we will merge it faster than if we need to make the fix ourself :relaxed:

**Comment by jakubhruby** [comment]
Yes, but... you have those [obstructive politics](https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests) to gain the ability of making PRs...

**Comment by pedrobaeza** [comment]
@jakubhruby I'm curious: what is exactly the obstructive one? CLA?

**Comment by jakubhruby** [comment]
Yes, it's the CLA. But to be honest, it's my layziness at the first place ;-) Next time I'll give it a try, I promise.

**Comment by GoodERPJeff** [comment]
#32073 please check if this issue still happen
