### ISSUE TITLE
Odoo 12 - Multiple Company Setup. User with single company can see other companies

### ISSUE THREAD

**Issue by netronuk** [odoo/odoo#27953]
Impacted versions: Odoo 12

Steps to reproduce: Create Two companies. Create user with single company selected. Logoff, login, Go to Contacts, Employees or Equipments Form view and create new Contact, Employee or Equipments. Find Company field. click on the Company field. You will see both Odoo companies. looks like all form views shows Odoo Companies.

Current behavior:

Expected behavior: When you click Company field, you should see only USER related Odoo company, not all other Odoo companies.

Video/Screenshot link (optional):

![contacts](https://user-images.githubusercontent.com/33455439/47166594-79ac7a80-d2f4-11e8-9aee-70081f2e9dc3.JPG)
![equipments](https://user-images.githubusercontent.com/33455439/47166595-79ac7a80-d2f4-11e8-8f73-bcecdefc70a6.JPG)

**Comment by dbwelch** [comment]
Status?

**Comment by meigallodixital** [comment]
This bug is patched except in the list of employees. You see all the employees of all the companies although you can not access them. But I think it's a new issue. This issue can be closed imo.

**Comment by pedrobaeza** [comment]
Yes, yours is another thing.
