### ISSUE TITLE
[11.0] Copy link from Link Tracker page do not work

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#27958]
Impacted versions:
11.0

Steps to reproduce:
- Go to website and click to promote>Track this page menu
- Click on the copy button
![image](https://user-images.githubusercontent.com/10233975/47191251-e54e1200-d30b-11e8-826b-1a97a42588a2.png)

Current behavior:
The link is not copied

Expected behavior:
The link being copied
Video/Screenshot link (optional):
https://youtu.be/cjNIVXFG2j8

OPW 1896509

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/b4e310e7f621e067a406030a14257f32f4c5499e in saas-14
Wait a few day to see it in 11.0
Thanks for reporting the issue
