### ISSUE TITLE
[12.0] @api.model_create_multi causes many2many relation data loss in new record creation

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#27957]
Impacted versions:
12.0

Steps to reproduce:
write below code:

self.env['product.product'].create({
    ....., 
    'attribute_value_ids': [(6, 0, [.....])]
})

Current behavior:
attribute_value_ids data won't insert into db

Expected behavior:
raises error while inserting if the many2many data can not be accepted, or does not loss the many2many data in new record creation with @api.model_create_multi

**Comment by Yenthe666** [comment]
@rco-odoo this might be one for you to check I believe.

**Comment by rco-odoo** [comment]
@jlzhou it works fine on my computer :wink:

Please send me a **more specific example** that does not work
(and specify which modules are required to reproduce the bug.)

Here is what I just tried, on a database with module "product" and demo data, and things work as expected:
```python
>>> env['product.attribute.value'].search([]).name_get()
[(3, 'Color: White'),
 (4, 'Color: Black'),
 (5, 'Duration: 1 year'),
 (6, 'Duration: 2 year'),
 (1, 'Legs: Steel'),
 (2, 'Legs: Aluminium')]

>>> p = env['product.product'].create({
    'name': 'Stuff',
    'attribute_value_ids': [(6, 0, [3, 5])],
})

>>> p.name
'Stuff'

>>> p.attribute_value_ids
product.attribute.value(3, 5)
```

**Comment by jlzhou** [comment]
I set the type of attribute as "dynamic". I don't know if it is a difference.

**Comment by rco-odoo** [comment]
@jlzhou creating a `product.product` works as expected:
```python
>>> attribute1 = env['product.attribute'].create({
    'name': 'Foo',
    'create_variant': 'dynamic',
    'value_ids': [(0, 0, {'name': 'A'}), (0, 0, {'name': 'B'})],
})

>>> attribute2 = env['product.attribute'].create({
    'name': 'Bar',
    'create_variant': 'dynamic',
    'value_ids': [(0, 0, {'name': 'A'}), (0, 0, {'name': 'B'})],
})

>>> attribute_values = attribute1.value_ids[0] + attribute2.value_ids[1]

>>> attribute_values.name_get()
[(9, 'Foo: A'), (12, 'Bar: B')]

>>> product = env['product.product'].create({
    'name': 'Stuff',
    'attribute_value_ids': [(6, 0, attribute_values.ids)],
})

>>> product.attribute_value_ids.name_get()
[(12, 'Bar: B'), (9, 'Foo: A')]
```
I guess you are confused by dynamic attributes. The creation of a `product.template` with dynamic attributes **does not create automatically** the corresponding product variants (`product.product`).
```python
>>> template = env['product.template'].create({
    'name': 'Stuff',
    'attribute_line_ids': [
        (0, 0, {'attribute_id': attribute1.id,
                'value_ids': [(6, 0, attribute1.value_ids.ids)]}),
        (0, 0, {'attribute_id': attribute2.id,
                'value_ids': [(6, 0, attribute2.value_ids.ids)]}),
    ],
})

>>> template.product_variant_ids
product.product()
```
The variants are created on-demand, specifically when used in a sales order. The purpose is to not create all variants when there are too many of them. For instance, 7 attributes with 10 values each would generate 10 million variants!
