### ISSUE TITLE
Partner language has no effect on product description

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#27960]
Impacted versions:
Contacts Directory - 11.0.1.0
Sales Management - 11.0.1.0
Inventory Management - 11.0.1.1

Steps to reproduce:
1. Change your user language to Estonian.
2. Create new quotation or sales order or invoice.
3. Select partner whos language is English.
![image](https://user-images.githubusercontent.com/40301417/47202098-dc4d5700-d384-11e8-8f9d-1d28612bf9cf.png)
4. Add new sales order line.
5. Select product which is translated from english to estonian also.

Current behavior:
Product is translated to estonian:
![image](https://user-images.githubusercontent.com/40301417/47202180-1f0f2f00-d385-11e8-9db5-c4eb19b33080.png)
But when I select it, description will be still in estonian:
![image](https://user-images.githubusercontent.com/40301417/47202251-541b8180-d385-11e8-96ca-35fec0f6b03a.png)
This problem appears only on selected products but we cannot detect differences. 

If I use Odoo in English, then product will be in English. Same problem is with this product when partner language is Estonian, after selecting this product to sales order line, it will not be in Estonian, but it should be. It is in English.

Expected behavior:
When customer language is English and I am using Odoo in Estonian, then after selecting product "[EZ] Aknalaud WS100 Mdf Valge", Sales Order line description should be in English: "Window sill WS100 Mdf White". 

Also when I am using Odoo in English and partner language is English, then after selecting product "Window sill WS100 Mdf White" it should appear on sales order line description in Estonian: "[EZ] Aknalaud WS100 Mdf Valge".

This problem is only with some products. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is working in my side, and with everything. You should check that the products you mention don't have the source term in estonian.

Closing this as no reproducible. If you try to reproduce in runbot and put detailed steps, then we will reopen.

**Comment by E4O** [comment]
Like I wrote before, source term is in English but still the problem appears.

**Comment by pedrobaeza** [comment]
Please reproduce it on runbot then and give us detailed steps for being able to reproduce them.
