### ISSUE TITLE
[mrp] duplicated raw material display in consumed materials, and no create picking for finished product 

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#27962]
Impacted versions:
12

Steps to reproduce:

1. enable multi-location
2. enable 3 step for manufacturing
3. create MO for product `desk combination`, and save the MO, found that it have create 1 picking for raw materials, the item in picking is corrected, but displayed duplicated items in Raw Materials list.

Current behavior:

Expected behavior:
create picking both for raw materials, and finished product.

Video/Screenshot link (optional):

raw materials in MO is wrong
![image](https://user-images.githubusercontent.com/1404460/47205269-fa807a80-d3b7-11e8-997b-8109d0dbe0ae.png)

picking is corrected
![image](https://user-images.githubusercontent.com/1404460/47205301-15eb8580-d3b8-11e8-8625-eb992013e2c9.png)

i think that the raw materials should be consumed in `virtual Locations/production`, not need to move from production to `wh/post-production`
![image](https://user-images.githubusercontent.com/1404460/47205558-d709ff80-d3b8-11e8-9dfd-88b53e3f2e51.png)

**Comment by jeffery9** [comment]
1. picking for **move materials from stock to `pre-production`** is need,  it have been created.
2. **move materials from  `pre-production` to virtual production** is the internal operation  of manufacturing, not need picking is ok
3. **move finished from  to virtual production to `post-production`**  is the internal operation of manufacturing, not need picking is ok
4. **move finished from `post-production` to stock** is the operation of inventory, there need picking for this

**Comment by amoyaux** [comment]
@jeffery9 Yeah, you are right, it exists a rule in stock after manufacturing that was not set correctly.
If you want to test the feature waiting the fix.
In route Pick components, manufacture and then store products (3 steps) modify the push rule
XX: Production → Post-Production set Post-production location as source and stock location as destination.

**Comment by jeffery9** [comment]
@amoyaux  recommended apply the fixups I submit that use to avoid push materials from virtual production to other location.

**Comment by amoyaux** [comment]
@jeffery9 Not sure that we want to remove this. Some people could use push rules to different sub virtual location in order to do statistics for example
