### ISSUE TITLE
Website: Issue with "Pay Now" button

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#27976]
Impacted versions:
12.0, 11.0 (Probably other versions with E-Commerce module)

Steps to reproduce:
(Assume the server is running with worker > 0, as the issue only happens in  multi-processing mode)
1. Add some products to the cart and proceed to checkout.
2. Select "Wire Transfer" is selected as the payment method.
3. Press the "Pay Now" button for more than 1 time (or as much as you can before Odoo changes the page)

** It is reproducible on Runbot

Current behavior:
1. The page will keep loading and there seems to be no response.
2. Odoo server seems to be entered a deadlock state.
3. Other users will not be able to access the Odoo server until the server timeouts the above process, in other words, the server is down.

Expected behavior:
There should be a way to prevent the user from preventing this in the UI level.

**Comment by TimLai125** [comment]
I believe it is very common that normal internet user will press the button for a few times in order to make sure the server is "handling" their request when the server is loading.

**Comment by pedrobaeza** [comment]
@JKE-be you have just made a very similar patch for wishlist. Can it be generalized?

**Comment by TimLai125** [comment]
@pedrobaeza Thank you for the suggestion. Maybe we can have something similar to this PR? i.e. https://github.com/odoo/odoo/pull/25527 @nim-odoo Do you have any opinion on this?

**Comment by TimLai125** [comment]
As an extra information, the issue only happens in multi-processing mode.

**Comment by JKE-be** [comment]
@TimLai125 

Thx, yes I followed your email with security  team...

> However that is not really a security concern, and could be discussed directly on the bug tracker, as a minor "feature".  

We keep in mind, but it is really not a critical issue. 
We prefer (at this moment) to fix issue that raise trace back and wrong behavior instead of UI design.
And keep them for when we will have more resource/time to improve it

**Comment by TimLai125** [comment]
@JKE-be Thank you very much for the reply. As mentioned in the email as well, I see this issue is quite critical since it could easily make a server down for a few minutes, especially you are running E-Commerce business.
@njeudy, do you have any opinion on this? I expect this could be a frustrating issue to many small Odoo customers.

**Comment by yostashiro** [comment]
@JKE-be I second Tim's comment.  The issue looks to me rather critical if you are in business to sell stuff online, and the cost of the fix (on UI), I guess, is relatively trivial.  Just an opinion.

**Comment by JKE-be** [comment]
That will not secure anything ! just hide the misconfiguration !

Let me know in which case you will auto confirm a payment in wire transfer ? It is a not realistic usecase.
If you want to make shit configuration, you will be always able !

**Comment by yostashiro** [comment]
@JKE-be Not sure if we are on the same page. The issue does not require misconfiguration in Odoo. If you go to a runbot instance, and try processing checkout with wire transfer by quickly clicking the pay now button like 10 times, and the runbot is dead for a few minutes until all the consumed workers are dead and revived. It looks to me realistic enough.

**Comment by yostashiro** [comment]
@JKE-be If you meant using "wire transfer" as a payment method for eCommerce was not a realistic use case, I do not think so especially in B2B. Not sure about the situation in your country, but it's pretty common in Japan.

**Comment by JKE-be** [comment]
@yostashiro not really, I was speaking about the fact to auto-confirm the SO. But after analyze, seems like it is before, when it send the Quotation by mail that worker is busy.

PS: runbot don't have a production configuration. Configuration is optimized for test and support a max of instance in parallel.

But yes, this 'debounce' is probably more justified (even if not so critical...) that most of the lasts debounce, disabled property, ... added to avoid double add to cart, or wishlist, comparator, and ...

**Comment by JKE-be** [comment]
![image](https://user-images.githubusercontent.com/4848797/47721862-51f0d700-dc51-11e8-8b44-ea6f172787a8.png)


Courtesy of @nim-odoo

**Comment by JKE-be** [comment]
we don't forget this 

We are working for a global solution in master, and hope to backport a small part to make 12 compliant.
