### ISSUE TITLE
[8.0] cannot modify classic selection fields with the new API

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#2797]
See the commit that worked around that:

https://github.com/lepistone/purchase-workflow/commit/7c343c677e2037f1587b9d2ee7867f5d4dc7a480

That module modifies the field `state` of the purchase order, adding three new states. Before that commit, the tests failed because the selection was not updated. After this workaround the field is updated just fine.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
