### ISSUE TITLE
[mps] to_supply became zero after generat_procurement when enable multi-step route.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#27979]
Impacted versions:
12

Steps to reproduce:
enable multi-location
enable multi-route
planning product ` Desk Combination` with monthly or other frequency.
set to_supply by manual or let it automatic
generate procurement by click the green circle.

found that the to_supply became zero.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

to_supply because zero.
![image](https://user-images.githubusercontent.com/1404460/47217966-c4a1bd00-d3dc-11e8-9cdc-fa48cfaaa917.png)

production order have been created corrected
![image](https://user-images.githubusercontent.com/1404460/47218003-e602a900-d3dc-11e8-82e0-8da7a8d293ab.png)

**Comment by sle-odoo** [comment]
Hi,
I think this is fixed with enterprise rev 5bdcecf878a4ef8d033e44b6b4400ec86c77f42e.
If it's not the case, i will need more steps do reproduce the issue.

Regards
