### ISSUE TITLE
[12] model 'sale.layout_category' is deleted in version 12

### ISSUE THREAD

**Issue by edison12347** [odoo/odoo#27977]
While migrating to odoo:12.0 I figured out that model 'sale.layout_category' is missing in the source code, an option for it is missing in Sale settings. Looking through the issues in this repo I couldn't find a reason why. Does anyone know the reason for removing this model/feature?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by DucTruongKomit** [comment]
It's sale.order.template now

**Comment by pedrobaeza** [comment]
Not really, they are now `sale.order.line` with field `display_type` = `line_section`.
