### ISSUE TITLE
[12.0] Width property set to 80% creates line breaks in e-commerce categories nav-item

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#27970]
Impacted versions: 12.0

Line: https://github.com/odoo/odoo/blob/12.0/addons/website_sale/static/src/scss/website_sale.scss#L574

Category names around 10-15 characters in length create a line break below them.

Removing the width property seems to do the trick, but I'm not sure if it was left there intentionally.

Example:
![screenshot_2018-10-19 products my website](https://user-images.githubusercontent.com/42942314/47210879-0b1afb80-d38c-11e8-87e3-3d810e875dfc.png)

**Comment by pedrobaeza** [comment]
@JKE-be can you answer this?

**Comment by qsm-odoo** [comment]
I made the minimal fix to restore the design as it was designed. I suppose we could improve it further in master though.
