### ISSUE TITLE
Database creation error: database 'postgres' already exists! Docker compose configuration

### ISSUE THREAD

**Issue by jonbk** [odoo/odoo#27980]
I'm stuck on create an Odoo instal with docker-compose. The database already exist when clicking on "Create database".
I use the default docker-compose.yml

Impacted versions:
 - odoo:12.0
 - postgres:1

Steps to reproduce:
Up the default docker-compose file:

`
version: '2'

services:

  web:

    image: odoo:12.0

    depends_on:

      - db

    ports:

      - "8069:8069"

   db:

    image: postgres:10

    environment:

      - POSTGRES_PASSWORD=odoo

      - POSTGRES_USER=odoo

      - POSTGRES_DB=postgres

`

Current behavior:

![screenshot_2018-10-19_14-25-46](https://user-images.githubusercontent.com/29717277/47218095-eeda8700-d3aa-11e8-8ff7-f425844cc6f7.png)

**Comment by pedrobaeza** [comment]
Your DB can't be named `postgres`, as it's a reserved one. Use another one.

Closing as no issue.

**Comment by patsotoe** [comment]
this solve the problem, thanks dude.

**Comment by patsotoe** [comment]
> Your DB can't be named `postgres`, as it's a reserved one. Use another one.
> 
> Closing as no issue.

this solve the problem, thanks dude.
