### ISSUE TITLE
[11, 12] Tooltip not displayed in the fields many-to-one

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#27986]
Impacted versions:
11.0 - 12.0
Steps to reproduce:
1. Active config of the pricelist
2. Go to a pricelist
3. When you place the cursor over the "Applicable on" not show Help Text, However in debug mode or in form view if this text is displayed. This happens in all views with these fields

Current behavior:
Not  displayed Help Text to the normal user in view tree of many-to-one objects
Expected behavior:
Not only can see the help of these fields in debug mode but it is visible to any user

Video/Screenshot link (optional):
[Video](https://youtu.be/qA6zEF4ty4Q)

**Comment by pedrobaeza** [comment]
This is not really a fault, but a misunderstanding on what going on. You are not over the field "Applicable on", but over the one2many field, and the tooltip belongs to that field. When editing in place that one2many tree field, then you will get the tooltip for the subfields.

Closing as no real issue.

**Comment by luisg123v** [comment]
Hi @pedrobaeza,

If this is actually expected, why the behavior is different in debug mode?

CC @CarmenMiranda

**Comment by pedrobaeza** [comment]
On developer mode, it's not needed to be in edit mode for seeing that on purpose, because you are on **developer** mode, so you want to see this information more prominent.

**Comment by CarmenMiranda** [comment]
Hi @pedrobaeza The thing is that if you have for example an o2m field and you only have the tree view to edit (for example the sale/purchase lines) and you are not on developer mode you can't see the tooltip with the help on the subfields. 
The only way to see the help on the subfields of fields like o2m or m2m when you only have the tree view to edit is using the developer mode

CC @luisg123v

**Comment by pedrobaeza** [comment]
If I don't remember bad, although the o2m is not editable inline, you can push on edit and see field tooltips. If not, it's because clicking on it, you will have the form with their tooltips.
