### ISSUE TITLE
[12] Could not remove Multi website access rights

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27996]
Impacted versions: 12.0
(Only website module is installed)
Steps to reproduce: Uncheck Multi-Website from Settings (Tested with Demo user)

![](https://image.prntscr.com/image/kdooVHhUTWOtyCn96-rwwA.png)
Save it
Current behavior:
![screenshot 37](https://user-images.githubusercontent.com/16624719/47256949-36ddd480-d4a5-11e8-9f1e-614d28e369d4.png)
Demo user is able to access all websites
Expected behavior:
Should be able to  Remove access rights for that user
Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Hi,

Thanks for the report.

This checkbox i just there to show field multi website or not. 
That will have not impact on the business logic. Code is not conditioned by this groups.

It is purely for show/hide website field in views.
