### ISSUE TITLE
[12] Shortcuts to add attachment not working on Messaging screen

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#27994]
Impacted versions: 12.0

Steps to reproduce: Go to Discuss page and Start Direct Message
Runbot : http://387358-12-0-238e56.runbot11.odoo.com/web?debug=#action=132&active_id=70&menu_id=96

Current behavior: Can not add attachment with `Alt  + T`
![](https://image.prntscr.com/image/zp_loDWPTQyR5h-5r-RRvw.png)
Expected behavior: Able to Select attchment

Video/Screenshot link (optional):

Ps: There is no log on Console

**Comment by Yenthe666** [comment]
@mart-e do you know who made the shortcuts options in V12?

**Comment by sswapnesh** [comment]
Looks from commit a4d00a56b640d9da5129e2611667b3f491157ca5

**Comment by Yenthe666** [comment]
Good catch. @VincentSchippefilt this might be for you!

**Comment by sswapnesh** [comment]
BTW, Commit message mentions     `2. Not assigning keys to the chatter section` so not sure If it is issue with that Button (To add Attachment) or  those Shortcuts should not be there on Chat screen.

**Comment by sswapnesh** [comment]
OPW - 1985039 

Ps:Shortcuts for menu works with `Alt` + `Shift` + `Number`

**Comment by Julien00859** [comment]
Working fine on my Linux Mint Tara running Firefox 66

![TheExtermelyRareCircumstancesBug](https://user-images.githubusercontent.com/8208953/58094799-c7160080-7bd1-11e9-9462-97ebaf95d34e.png)

**Comment by Julien00859** [comment]
@sswapnesh what OS/browser are you using ?

**Comment by Julien00859** [comment]
Changes are your key is intercepted by your *operating system*, *desktop environment* or *browser* before it reaches the application thus the key is simply not detected by odoo and there is nothing we can do our side.

**Comment by Julien00859** [comment]
Try it yourself: https://codepen.io/anon/pen/WBXwPO

**Comment by sswapnesh** [comment]
> @sswapnesh what OS/browser are you using ?

Chromium Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)

Btw, This works well on most of the Browser/OS. you can also ask functional analyst (assigned on ticket) as they have confirmed same Behavior.

You can go ahead and close this issue/opw if this is related to specific Browser/OS.

**Comment by Julien00859** [comment]
I went and ask her myself earlier today. If it is just the T key on Chrome/Ubuntu then you understand I close this ticket
