### ISSUE TITLE
Saving settings fails when multi-company is enabled and the website module is installed

### ISSUE THREAD

**Issue by tomeyro** [odoo/odoo#27991]
**Impacted versions**: 12.0

**Steps to reproduce**:

1. On a clean database with odoo 12.0 and having the website module installed.
2. Enable multi-company from general settings.
3. Change active user to a different company (that is not the main one).
4. Go to the general settings page.
5. Try saving (a change is not needed, this is just to run the execute method once, it should work).
6. After the page reloads, try saving again.

**Current behavior**: An error is raised saying "can't create two users with same login".

![image](https://user-images.githubusercontent.com/8657959/47233507-9bf7d400-d398-11e8-8ee6-e47bd39d17be.png)

**Expected behavior**: It saves correctly each time.

Video/Screenshot link (optional):
https://drive.google.com/open?id=1sVp8U28GhISaPps4maWgQTCNy5i1YNBE

**Comment by sswapnesh** [comment]
Resolved in https://github.com/odoo/odoo/pull/27873

**Comment by Yenthe666** [comment]
Indeed, should have been fixed in https://github.com/odoo/odoo/commit/1ccd148775aa3a01e5a86c38b3038063ff2b714a
