### ISSUE TITLE
Translatable term is not linked to the module where is it defined/used.

### ISSUE THREAD

**Issue by captivea-jpa** [odoo/odoo#27997]
**Impacted versions:**

Tested on 10 and 11.

**Steps to reproduce:**

Create a new database.
Install 'calendar' module.
Install a new custom 'my_calendar' module containing this data:
```
<record model="ir.ui.menu" id="calendar.mail_menu_calendar">
    <field name="name">Appointments</field>
</record>
```
Export translation for the module 'my_calendar'.
Export translation for the module 'calendar'

**Current behavior:**

The "Appointments" xml text node is not included in the translation file of 'my_calendar'.
But it is in the 'calendar' one.

**Expected behavior:**

Translatable terms should be linked to the module where they are defined/used.
Translation file of one mother module should not include employed terms of its child modules.

**Comment by sswapnesh** [comment]
That's because your are assigning external id  `id="calendar.mail_menu_calendar" `which refers to another (`calendar`) module.

**Comment by pedrobaeza** [comment]
Exactly, so the only way to make this work is manually including the translation in your module `i18n_extra` folder. Closing as no real issue.
