### ISSUE TITLE
[12] Impossible to Import Bank Statement

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#27995]
Impacted versions:
odoo v12 CE

Steps to reproduce:
- in Accounting, click "Import a Bank Statement"
- upload file (CSV or .xls)
- click "Import"

Current behavior:
- fails with the following error: 
  "Odoo Server Error - Warning
  Could not make sense of the given file.
  Did you install the module to support this type of file ? 

Expected behavior:
- import bank statement (base_import and base_import_module installed)

Video/Screenshot link (optional):
![screenshot_20181020_115853](https://user-images.githubusercontent.com/29736794/47254266-759d6b80-d460-11e8-9911-bcc3f3f1ed1d.png)

**Comment by haconsult** [comment]
Hi @sswapnesh 
This means there is no way whatsoever to import a statement in CE? I assume this would be a showstopper for most CE users. Nobody would manually "import" a statement line by line.

Regards, Helge

**Comment by sswapnesh** [comment]
At the moment there is no feature for that in CE by default,
(You can go through OCA modules https://github.com/OCA/bank-statement-import/tree/11.0 _(Still not migrated to v12)_)

**Comment by haconsult** [comment]
Ok, thanks for the hint. 
Regards.
