### ISSUE TITLE
Tab button not working in 8.0 while filling a timesheet in 8.0 or master

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#2802]
Steps to reproduce 

(1) Go to Human Resorce -> My Current Timesheet

(2) Go to Details tab and click on "Add an Item" 

(3) Now , fill the date press tab , then fill the "Description" press Tab , then analytic account and tab , odoo 8.0 or master will not allow you to fill Invoiceable field with the Tab button which was working in 7.0

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thanks for your report.
This has been fixed in the meanwhile and works fine in the latest Odoo 8.

Regards,
Yenthe
