### ISSUE TITLE
Nightly build file odoo_8.0.latest.exe is missing

### ISSUE THREAD

**Issue by ryan1967** [odoo/odoo#28039]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Hi, 8.0 is no longer supported.

The currently supported versions are 10.0, 11.0 and 12.0.

**Comment by Elkasitu** [comment]
Hi, this is normal as we no longer build a 8.0 `.exe`, you can download any of the other builds however
