### ISSUE TITLE
Multiple Purchase Agreement can not able to delete

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#28032]
Impacted versions: Odoo-12.0

Steps to reproduce:
Unlink more than one Purchase Aggrement(model: purchase.requisition)

Current behavior:
Get issue of "Expected singleton"

Expected behavior:
Use @api.multi and iteration.

Video/Screenshot link (optional):
![purchase requisition](https://user-images.githubusercontent.com/8874012/47297497-d7153400-d632-11e8-906f-cb378589419e.png)

**Comment by Yenthe666** [comment]
Thanks for the report @goyanipankaj! It has been solved in https://github.com/odoo/odoo/commit/585846d20aeb215bc7f906a060bc64a440f41650
