### ISSUE TITLE
Export data in XLSX format

### ISSUE THREAD

**Issue by HyacintheH** [odoo/odoo#28046]
Impacted versions: ALL

Steps to reproduce:

Current behavior: Data are exported in Excel 2003

Expected behavior: Data should be exported in XLSX to allow sheets with more than 256 columns

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@fgi-odoo do you know if this is in future plans?

**Comment by fgi-odoo** [comment]
Nothing for now. Is there any other issue with xls? Is it not even better compatibility-wise (with other spreadsheet tools).  Exporting more than 256 columns doesn't sound like a frequent usecase...

**Comment by HyacintheH** [comment]
At Subteno IT, we have several clients who request it. Notably in pivot views, for example, to cross article variant sales with partners.
The Excel 2003 format is now 15 years old and this limit of 256 columns is obsolete. Even Google has increased the limit of cells to 2 millions.

**Comment by pedrobaeza** [comment]
The most important limitation IMO is the other one: 65535 rows. For example, exporting move lines for an audit is not possible in a middle-size company.

**Comment by HyacintheH** [comment]
Yes, exactly. And scalability should be the next goal of Odoo if they want to acquire more big companies.

**Comment by Yenthe666** [comment]
Yep, I agree that the 65535 rows is a bigger problem. This has all been discussed at https://github.com/odoo/odoo/issues/23344 but nothing really seems to have happened with all this?

**Comment by DonFeraRRi** [comment]
Is this resolved as for now or its still under discussion because I face the same when I was exporting the POS order Lines and there are 80000+ lines to which this validation appeared.

**Comment by HyacintheH** [comment]
I am

**Comment by HyacintheH** [comment]
I am done with Odoo.
