### ISSUE TITLE
Wrong Debit credit entry!

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#28043]
Impacted versions:

Odoo 10.0
Steps to reproduce:

Create Customer Refund
Validate Refund Invoice.
Register Payment (@note: Partial payment with select Payment difference is "Mark invoice as fully paid")
Raise the warning: Wrong credit or debit value in accounting entry !
Current behavior:

Not allow to partial payment with refund invoice.
Expected Behavior:

As per my knowledge allow to refund invoice with partial payment.
Video/Screenshot link (optional):

Please refer this link.
Link: https://drive.google.com/open?id=1kEpfWeorNNMJZjF1wXg0t2ItAIQfQzJX

**Comment by sswapnesh** [comment]
@goyanipankaj  PR #28237 should resolve this

**Comment by Yenthe666** [comment]
Fixed at https://github.com/odoo/odoo/commit/bb939ffac0c8222a4b34523b739b64173f2258f8

**Comment by sswapnesh** [comment]
> Fixed at [bb939ff](https://github.com/odoo/odoo/commit/bb939ffac0c8222a4b34523b739b64173f2258f8)

This commit is for v11.
V10 is pending at https://github.com/odoo/odoo/pull/28237/commits/586c4f205ef40904ecd1fa97fe81a51a35de098f
