### ISSUE TITLE
[12.0] Mobile view is broken

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#28048]
Impacted versions: odoo 12 CE

Steps to reproduce:

* switch to mobile view

Current behavior:

* Menus are not visible

Expected behavior:

* *guess*

Video/Screenshot link (optional):
![ce](https://user-images.githubusercontent.com/186131/47348779-a03f2c80-d6cb-11e8-9aa2-e8bad6ed43e1.gif)

**Comment by pedrobaeza** [comment]
Duplicate of #28031
