### ISSUE TITLE
datev export error - l10n_de_reports module

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#28050]
Impacted versions:
Odoo V12 EE (tested on runbot)

Steps to reproduce:
Create a new company (f.ex. "Germany")
Open accounting and assign german chart of accounts (f.e. l10n_de_skr03, l10n_de_reports)
Create a new german customer and create a simple customer invoice.
Open General Ledger Report and click on "Export Datev (zip)"

Current behavior:
Error message:

Traceback (most recent call last):
  File "/home/odoo/runbot/runbot/runbot/static/build/388087-12-0-12554f/odoo/addons/account_reports/controllers/main.py", line 81, in get_report
    content = report_obj._get_zip(options)
  File "/home/odoo/runbot/runbot/runbot/static/build/388087-12-0-12554f/odoo/addons/l10n_de_reports/models/datev_export_csv.py", line 119, in _get_zip
    zf.writestr('EXTF_customer_accounts.csv', self._get_partner_list(options))
  File "/home/odoo/runbot/runbot/runbot/static/build/388087-12-0-12554f/odoo/addons/l10n_de_reports/models/datev_export_csv.py", line 148, in _get_partner_list
    move_line_ids = self.with_context(self.set_context(options), print_mode=True, aml_only=True).get_lines(options)
AttributeError: 'account.general.ledger' object has no attribute 'set_context'

Expected behavior:

a .zip archive with two .csv files.

Video/Screenshot link (optional):
<img width="1233" alt="bildschirmfoto 2018-10-23 um 11 23 48" src="https://user-images.githubusercontent.com/8348598/47351047-7aa82800-d6b7-11e8-8ed0-0a3061e3fda2.png">

**Comment by jco-odoo** [comment]
Is this still a problem as I suppose that set_context has been replaced with _set_context now?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe

**Comment by tv-openbig** [comment]
I have just checked on runbot again. The creation of the zip archive with two .csv files is working now.

**Comment by Yenthe666** [comment]
Great, thanks for the feedback!
