### ISSUE TITLE
Probleme in Kanban view when loging in

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28067]
Impacted versions: 12

Steps to reproduce: install a new theme (for example Lumen)

Current behavior: An errors shows:
**Uncaught TypeError: Cannot read property 'display' of undefined
http://ubuntuserver:8069/web/content/1004-6682e31/web.assets_backend.js:2935
Retraçage :
TypeError: Cannot read property 'display' of undefined
    at http://ubuntuserver:8069/web/content/1004-6682e31/web.assets_backend.js:2935:1616
Expected behavior: no error should appear**

Video/Screenshot link (optional):
![capture du 2018-10-23 14-23-17](https://user-images.githubusercontent.com/28365138/47363705-57897280-d6cf-11e8-859d-f9b46f2907a3.png)

**Comment by Yenthe666** [comment]
Hi there,

This is not an issue with Odoo but an issue with the third party theme. This theme, for example, is managed by Openworx so you should report it there (https://www.odoo.com/apps/themes/12.0/theme_lumen/)

P.S: Also try to add reproducable steps and run Odoo with `?debug=assets` for a good traceback.

Regards,
Yenthe

**Comment by aitalinassim** [comment]
Thanks for your answer,

But even I uninstalled the theme and reinstalled the default theme, the error is still here, I rebooted the server and even lot more but no think to solve.

Do you think that I shall reinstall odoo again ?

**Comment by Yenthe666** [comment]
Perhaps the theme does not delete everything nicely. You should try to do a `-u` and reload assets.

**Comment by aitalinassim** [comment]
Thanks for your answer,

Can you please give me the detailed procedure or a link to a webpage how to do this ?

Respectfully !!!

**Comment by Yenthe666** [comment]
To update a module: https://odoo-development.readthedocs.io/en/latest/odoo/usage/install-module.html#update

**Comment by aitalinassim** [comment]
Issue solved by replacing already existing file on the server "base_calndar.js" by the one download from odoo source from github. 

Is this procedure correct ?

**Comment by aitalinassim** [comment]
Left is old file and on the right is file from github

![capture du 2018-10-23 16-01-07](https://user-images.githubusercontent.com/28365138/47370175-0e401f80-d6dd-11e8-9a14-cbea9ed3e2b3.png)
