### ISSUE TITLE
[12.0/master] wishlist: ability to edit report header and footer with Odoo Studio

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#28070]
Impacted versions: 12.0 / master

Steps to reproduce: 
1. Go to sales > quotations, open studio, click on, click on reports and choose the quotation.
2. Try to edit the header or the footer now, it is impossible

Current behavior: An enduser is not able to edit the report header and footer, two very important parts on a report. The only way to edit the report header and footer now is by finding the right report from the four templates and by opening the right one under settings > views.
https://github.com/odoo/odoo/blob/1868713dbd07e0b518f91dffe73e62d85e6ab9a6/addons/web/views/report_templates.xml#L165-L337
This means:
- User needs advanced rights on settings
- User needs good knowledge of how the reporting engine works
- User needs technical knowledge to modify/code XML.

Expected behavior: Ability to modify the report header and footer with Odoo studio too.

**Comment by Yenthe666** [comment]
@ged-odoo, @aab-odoo and @mge-odoo I'd love to discuss this one with you guys. I assume there is a technical reason why this is not in place yet? Perhaps because it is another `QWeb` view that is being rendered in another `Qweb` view which is rendered in the `FormView`? 

We already have people asking how they can edit their own header/footer with Studio and I assume the number of people asking this will go up. Are there any plans to add this in and if so, would that be V13 or? I'd like to hear something from the team that made this as I'm curious. 👍

**Comment by mge-odoo** [comment]
Hi @Yenthe666 

There were both functional and technical reasons for not to allow the user to edit the header/footer.

About the functional, we didn't want the user to think "I'm customizing this report" while in fact, when customizing the header/footer, he was actually modifying **all** reports using the template.

About the technical, in the external layout, the layout templates are called with a dynamic `t-call` (see https://github.com/odoo/odoo/blob/12.0/addons/web/views/report_templates.xml#L357 ) which makes the parsing of `t-call` more difficult (see https://github.com/odoo/enterprise/blob/12.0/web_studio/controllers/report.py#L146 ).

We thus decided to let these templates non editable.

We however wanted to do something special for the header/footer in 12.0, in a functional point of view. Like a special screen for header/footer customization. We didn't find a good way to do it back then but the task is still there and needs to be specified so probably for master.

I have shared your feedback with the Studio PO to help him specify this.

**Comment by farazda1** [comment]
@Yenthe666 was this possibility made available later to be able to modify header footer using studio ?

**Comment by Yenthe666** [comment]
@farazda1 no, it is not yet implemented.

**Comment by juchheim-gmbh** [comment]
This would be really a nice feature and is really expected behauvior.

**Comment by timdri01** [comment]
@Yenthe666 Any word if this has been implemented yet in 15?

**Comment by Yenthe666** [comment]
Nope, still exactly the same as in V12 I'm afraid :(

**Comment by timdri01** [comment]
Looking at 15 enterprise and it does offer some basic ability to modify the header and footer.
