### ISSUE TITLE
8.0 yaml: context passed to create() is not the same passed to _defaults

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#2807]
See

https://github.com/lepistone/purchase-workflow/blob/8.0-add-purchase-extended/purchase_extended/test/process/po2order.yml#L3-L11

I need to pass the context twice because it is not the same one that gets passed to `create()` and `_defaults`, which is weird.

Thanks!

**Comment by BT-astauder** [comment]
Link is no longer valid/public. Can this be closed?

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
