### ISSUE TITLE
[11.0, 12.0] Work Orders marked as Enterprise Only but available in Community version.

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#28080]
**Impacted versions:**

11 and 12

**Steps to reproduce:**

1. Activate the developer mode
2. Install Manufacturing (mrp) module
3. Go to: Manufacturing -> Configuration -> Settings
4. Try to enable Work Orders
5. "Get this feature and much more with Odoo Enterprise!" popup
6. Go to Settings -> Users & Companies -> Users -> Administrator (or other user) -> Edit -> Select "Manage Work Order Operations" -> Save -> Refresh website
7. Work Orders Enabled

**Current behavior:**

Work Orders wrongly marked as Enterprise Only; strange way of enabling it in the Community version. Misleading information in settings.

**Expected behavior:**

Remove enterprise flag from settings; option to enable work orders via settings.

**Comment by pedrobaeza** [comment]
Fixed in #28081, so closing.

**Comment by Yenthe666** [comment]
Yep, done at https://github.com/odoo/odoo/commit/7c45f22ceac8246f627f62ed38df020b96d9a0a6 😄
