### ISSUE TITLE
Error when company supplied in API call is different from current company

### ISSUE THREAD

**Issue by measwel** [odoo/odoo#28085]
Good day,

I would like to create an invoice for a particular company ( I have a multi company setup ) via the rpc API. When I supply the company_id in the call, then I get an error depending on what is the current company for the user. If the current company is the same as the one supplied in the call, then there is no error and the invoice is created.

Generally; how do I let odoo know for what company I am performing the call? Must I set the current company for the user before I make the call? Or can I just specify the company in the call, even if current company is different? 

Thank you.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
