### ISSUE TITLE
Direct message not shown immediately after active workers parameter in configuration file

### ISSUE THREAD

**Issue by szegc** [odoo/odoo#28088]
Impacted versions:11 Enterprise version
Steps to reproduce:
After active workers parameter and restart odoo, you will notice that the direct message in Discuss module cannot be displayed immediately.

Current behavior:

Expected behavior:
It's should be appear after send.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
