### ISSUE TITLE
project.task.type fold property appears to do much more than is documented

### ISSUE THREAD

**Issue by colinnewell** [odoo/odoo#2809]
The documentation for the fold property says 'This stage is folded in the kanban view when there are no records in that stage to display.'.  In reality the code appears to use this property to determine whether a stage is a 'closed' state, replacing the state behaviour that was previously in the project model.  This doesn't seem obvious from the user interface.  You can see that the default stages follow that pattern, but the help could be better in that regard.

**Comment by ahvensoppa** [comment]
Version 9.0-20151001 still behaves the same, slightly incomprehensible way. Tasks to be closed need to be moved into stages configured as folded. Only then their Working Time Progress reaches 100%.

**Comment by ahvensoppa** [comment]
In Version 9.0-20151001 the checkbox for setting a stage to 'closed' is actually available in the developer mode...

**Comment by Yenthe666** [comment]
Hi @colinnewell,

Thank you for your report.
It is correct that this can behave to determinate if the project is closed or not. 
If you'd like this documented you're welcome to make a PR against the documentation.

Regards,
Yenthe
