### ISSUE TITLE
Bad '%s' translations

### ISSUE THREAD

**Issue by aek** [odoo/odoo#281]
There are a large number of typos in locale specific .po translations related to the '%s' placeholder that get translated to '% s', notice the extra space in the string. For example in the web module es.po:

#. module: web
#. openerp-web
#: code:addons/web/static/src/js/view_list.js:1349
#, python-format
msgid ""
"Grouping on field '%s' is not possible because that field does not appear in "
"the list view."
msgstr ""
"Agrupar por el campo '% s' no es posible debido a que dicho campo no aparece "
"en la vista de lista."

This kind of typos are all over openerp i18n po files sometimes throwing errors in the warning dialog like:
Uncaught Error: [_.sprintf] huh?

**Comment by mart-e** [comment]
Hello,

I have just corrected a several of them but if others, they should be corrected on Transifex, not on Github. Please see the [wiki page](https://github.com/odoo/odoo/wiki/Translations) about translation for details.
Regards
