### ISSUE TITLE
[12] "The record has been modified" warning on Duplicating Invoice

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28119]
Impacted versions: 12.0

Steps to reproduce: Duplicate Invoice

Current behavior: It Duplicates Invoice but Displays Warning 
![screenshot 55](https://user-images.githubusercontent.com/16624719/47448275-357e1600-d7dd-11e8-8e9b-24210640f67d.png)

Expected behavior:
No Warning
Video/Screenshot link (optional):
![peek 2018-10-24 22-36](https://user-images.githubusercontent.com/16624719/47448319-58a8c580-d7dd-11e8-9e3f-2d9f14cdaed2.gif)

**Comment by pedrobaeza** [comment]
It seems you drag the dirty flag from other place, as I'm doing the same without the warning.

**Comment by sswapnesh** [comment]
No, This was on new invoice. I have recorded this from latest Runbot build

**Comment by pedrobaeza** [comment]
As said, you should make other operation before. Check the GIF:

![peek 24-10-2018 21-04](https://user-images.githubusercontent.com/7165771/47454830-7ae81680-d7d0-11e8-84cd-f25729f297ba.gif)

**Comment by pedrobaeza** [comment]
OK, I see the problem. It happens exactly with the invoice from "Deco Addict" that is validated. This is probably a problem with demo data that doesn't set properly one of the fields.

**Comment by kebeclibre** [comment]
solved with #28759 at 596af12c21ae1df4679bfc526c6724e9b5453e0b
