### ISSUE TITLE
Asking to fill Employee field which is not existing in the form

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28123]
**Impacted versions:**
Odoo 12

**Steps to reproduce:**
Install odoo 12
Fetch to last git version
Install module to manage employees expenses
create a new user and login with his credentials (user not employee)
Create new expense
Fill fields: Description and Article
Click on save button

**Current behavior:**
Error message asking to fill employee name or select employee

**Expected behavior:**
Save the expense
In Odoo12 before fetching, this error was not observed.
when tring to create directly and expense report without creating the expense, in the form we can see the field "Employee" so the Employee field is missing in the form to create an expense.

**Comment by pedrobaeza** [comment]
This is the expected behavior. You have to link your user to an employee.

Closing as no issue.

**Comment by aitalinassim** [comment]
Thanks for the answer, but some users are not employees.

Check this page:
https://www.odoo.com/forum/help-1/question/how-employee-and-a-user-are-linked-93484

**Comment by pedrobaeza** [comment]
But for expenses is a requirement.

**Comment by aitalinassim** [comment]
Sorry, but if a user (not employee) want to save the expense of an employee, how can he do it ?

**Comment by pedrobaeza** [comment]
Just fill the employee field:

![seleccion_008](https://user-images.githubusercontent.com/7165771/47484082-229a2e80-d83b-11e8-8fc6-ab6fe59448c5.png)
