### ISSUE TITLE
[12.0][RFI] hr: identification_id usage

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28128]
Requesting input: `identification_id` is declared over here [addons/hr/models/hr.py#L141](https://github.com/odoo/odoo/blob/12.0/addons/hr/models/hr.py#L143) right next to SSN & SIN, used over here [addons/hr_payroll/views/report_payslipdetails_templates.xml#L29](https://github.com/odoo/odoo/blob/12.0/addons/hr_payroll/views/report_payslipdetails_templates.xml#L29) as arbitrary Employee ID and used over here [addons/l10n_fr_hr_payroll/report/report_l10n_fr_fiche_paye.xml#L51](https://github.com/odoo/odoo/blob/12.0/addons/l10n_fr_hr_payroll/report/report_l10n_fr_fiche_paye.xml#L51) as SSN (I guess?).

Questions:
1. Are `ssnid` and/or `sinid` used in enterprise version? No references to those found in community edition.
2. `identification_id` should be used as SSN/ITIN/country-specific-SSN (seems so, since it's present in payslips)?

**Comment by alexey-pelykh** [comment]
This question blocks https://github.com/OCA/hr/pull/488 a bit

**Comment by pedrobaeza** [comment]
@simahawk you migrated it to v11. Can you answer?

**Comment by simahawk** [comment]
on v10 and v11 I don't see any specific usage in enterprise code. Nor in v12 actually. 
But I'm not an expert on the subject. @gurneyalex any insight?

**Comment by gurneyalex** [comment]
identification_id is an identification number for the employee used internally in the company. 

ssnid is the social security number of the employee (assigned outside the company). In some countries, including France, it is forbidden by law to use this field as a unique identifier for a person if you are not the national social security, because it is a globally unique number over all the population, and there are risks of privacy intrusion through cross indexing. But at the same time, it is required to have this information on the payslip and when interacting with the social security. 

sinid is to be used for private insurance number. In France, for the reasons explained above, it cannot be the same as ssnid (because the private insurance is not the national social security). 

So my opinion is that we need these numbers and we cannot merge them.

**Comment by gurneyalex** [comment]
"No s. s." is definitely 'Numéro de sécurité sociale' in french (Social Security number). 

and yes, in a payroll report I'd expect identification_ID as ID (french: "Matricule") and ssnid in "No s.s.". I guess l10n_fr_hr_payroll is wrong there, but solving this is going to be a migration nightmare. I'm curious if anyone is using that module anyway (French payroll being a special place in hell).

The "matricule" is typically generated from a sequence.

**Comment by alexey-pelykh** [comment]
Awesome! This means that I may proceed with `hr_employee_id` migration as-is. What do you think, would a PR that exposes `ssnid`/`sinid` to the UI directly to `hr` module be accepted? Alternatively/additionally I may add a `hr_employee_tin` module for the tax-only purposes, yet usually TIN and SSN are the very same thing.

Regarding the `l10n_fr_hr_payroll` data migration - for sure that would be so much pain, and I'm not sure if I may help anyhow there

**Comment by gurneyalex** [comment]
A PR in OCA, certainly :smile_cat: . On Odoo, I don't know, it may be against stable policy. 

In any case, these informations are not public, so if displayed they must go in the HR tab, which has a restricted visibility.

**Comment by alexey-pelykh** [comment]
Well, exposing `ssnid`/`sinid` would be beneficial for Odoo itself. Since fields are declared but not used anywhere - for what reason they are there? Maybe showing them in same restricted page (visible only to HR) would be good?

**Comment by gurneyalex** [comment]
I don't question the wisdom of Odoo developers. And I don't have write access to the odoo repository. Make the PR but be prepared for it to be rejected.

**Comment by alexey-pelykh** [comment]
Exactly what I was planning to. I suppose this issue may be closed, except I wonder as well what would be with l10n_fr_hr_payroll eventually

**Comment by Yenthe666** [comment]
@alexey-pelykh you're always welcome to make a PR to try and get the field(s) into the form view.

**Comment by alexey-pelykh** [comment]
Here it is: #28174
