### ISSUE TITLE
[12.0] Issue with Attachments when adding attachment using Drag and Drop feature

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28120]
Impacted versions: 12

Steps to reproduce:  Use Odoo's Drag and Drop feature to add Image in Chatter
Current behavior: It adds attachment there but Does not display In attachment counter or View Attachments

Expected behavior: Attachment should be there with correct Number

Video/Screenshot link (optional):

![peek 2018-10-24 22-56](https://user-images.githubusercontent.com/16624719/47449416-31072c80-d7e0-11e8-8168-3dd45e40ab0c.gif)

**Comment by pedrobaeza** [comment]
This is because you are embedding an image, but not handled as attachment.

**Comment by sswapnesh** [comment]
Yes, But I think that should be parts of attachments. (or may be I am wrong here)

**Comment by pedrobaeza** [comment]
No, it's not that way, as the image can't be an attachment and be embedded at the same time (take into account that you are sending, not receiving). When receiving a mail, Odoo analyzes mail and extract as attachments embedded images, but it's something that can do at this side.

Closing as no perceived issue.
