### ISSUE TITLE
database backup error

### ISSUE THREAD

**Issue by xwjh** [odoo/odoo#28138]
Impacted versions:
Odoo 12.0-20181008(docker)
Steps to reproduce:
web/database/backup,backup the database
Current behavior:
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmpva5pui5s/dump.sql', 'odoo12') error 1
Expected behavior:
backup database
Video/Screenshot link (optional):

**Comment by fractalf** [comment]
I had the same problem.

The problem:
https://github.com/odoo/odoo/issues/30599

The fix until they update the .deb file is to manually install *pg_dump* (see issue)

**Comment by d-fence** [comment]
It seems to be a Docker image issue.
The problem is explained in #30599 
Docker image will be fixed soon.
