### ISSUE TITLE
Down Payment line stays in sale order after refund of the corresponding invoice

### ISSUE THREAD

**Issue by palmieric** [odoo/odoo#28168]
Impacted versions: 10.0 (but I didn't test it on the v11.0/v12.0)

Steps to reproduce: Create and confirm a sale order. Create, validate and register a Down Payment. Refund the down payment. Create the invoice for the full sale order.
 
Current behavior:The amount of the full invoice of the sale order is reduced by the down payment even if it has been refunded.

Expected behavior: After the refund of a down payment invoice the corresponding line in the sale order should be automatically deleted as the same way the line is automatically added.

**Comment by Yenthe666** [comment]
Dear @palmieric,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue and a personal sorry that I didn't get around to watching your video either.

Regards,
Yenthe
