### ISSUE TITLE
[12.0][IMP] hr_holidays: add days to weeks, months, years

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28184]
https://github.com/odoo/odoo/blob/25e82a5c6837c6b55478222942038bbcb3a06a66/addons/hr_holidays/models/hr_leave_allocation.py#L119

Having days there (or at least make it somehow extendable) would be great

**Comment by Yenthe666** [comment]
@alexey-pelykh why don't you use `add_selection` in an inherit though?
You could propose a PR for master but I don't think anyone will allow that change on stable.

**Comment by alexey-pelykh** [comment]
One of possibilities, yet I'd have to do something with https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave_allocation.py#L155 that is not quite modular

**Comment by tivisse** [comment]
Hi @alexey-pelykh 

Thanks for the feedback.

Internal task targeting the master branch opened at https://www.odoo.com/web#id=2168023&action=333&active_id=1251&model=project.task&view_type=form&menu_id=4720

Have a nice day,

Yannick.

**Comment by tivisse** [comment]
Hi @alexey-pelykh 

For your information, it has been done at : https://github.com/odoo/odoo/pull/46751

Thanks.
