### ISSUE TITLE
[12.0][IMP] hr_holidays: during migration to Odoo, employees creation date may be far in future

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28185]
https://github.com/odoo/odoo/blob/25e82a5c6837c6b55478222942038bbcb3a06a66/addons/hr_holidays/models/hr_leave_allocation.py#L169

It should be or earliest contract, or something

**Comment by RomainLibert** [comment]
I agree that the create_date is not the best indicator for the hiring date of an employee, but sadly it seems to be the only thing that make sense without adding an dependance on the module (hr_contract for instance).
The other method to add this to hr_holidays would be to create a new module that would depend on hr_holidays and hr_contract and get us the hiring date for the employee.

**Comment by alexey-pelykh** [comment]
Yes, in my plan it's a bit more complex (two modules actually, since not all use hr_contract), one of them already under review https://github.com/OCA/hr/pull/502, other one will depend on it. With default accrual implementation there not that many extension points and some code lines are just odd:
https://github.com/odoo/odoo/blob/d226f8b4ff6f873e1e93d8c671c08ad69d2339a9/addons/hr_holidays/models/hr_leave_allocation.py#L333

**Comment by mart-e** [comment]
Hi,

As explained Romain, while not perfect, this is the best we have at the moment without adding a dependency (which we try to avoid, to stay modular).
If you have a concrete suggestion of improvement, don't hesitate to submit a PR for master.
Thanks
