### ISSUE TITLE
ODOO11 MTO NO procurement rules found

### ISSUE THREAD

**Issue by ndemoreau** [odoo/odoo#28180]
Impacted versions: 11

Steps to reproduce:
In the runbot, when you try to order the ipod e-com12 (which is set as make to order), when confirming the sales, I get this error message:

**No procurement rule found. Please verify the configuration of your routes**

This also happens in my Odoo 11 instances. It worked previously though.

I've checked the routes and everything seems to be fine. I think this message is strange because in a MTO product, you are not supposed to have reordering rules.

This is why I think it's a bug.

Thanks for your help.

**Comment by sle-odoo** [comment]
mto on its own isn't enough, try to tick to buy and add a vendor for instance
it's a configuration issue

**Comment by ndemoreau** [comment]
We tried this before but it didn't work. Did you try it on your end?
