### ISSUE TITLE
Existing partner_id not taken into account when converting a lead to an opportunity.

### ISSUE THREAD

**Issue by wamdam** [odoo/odoo#2821]
When converting a crm.lead into an opportunity, you can use an existing res.partner to connect with the opportunity. This happens in the crm/wizard/crm_lead_to_opportunity.
But during conversion, the partner_id is not taken into account.

What works however is that you add the res.partner to the crm.lead before converting and convert then.

**Comment by Yenthe666** [comment]
Hi @wamdam,

Thank you for your report (and PR).
This was fixed by https://github.com/odoo/odoo/commit/65de6e7f27344be275c5372a4dd76fa4396a2a9d as you pointed out but the issue has never been closed.

Regards,
Yenthe
