### ISSUE TITLE
No changes after the installation of a new theme.

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28224]
**Impacted versions:**
12

**Steps to reproduce:**
Install odoo CE
Download new theme (https://apps.odoo.com/apps/themes/12.0/theme_lumen/)
Install the new theme and activate it

**Current behavior:**
Now changes notices in the user interface

**Expected behavior:**
User interface should change as per the downloaded theme, even the website.

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
