### ISSUE TITLE
[Odoo Apps Store] no email when new comments, no possibility to answer

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#28221]
Hi @dmo-odoo @rar-odoo

When a guy post a comment in the page of the module (for exemple : https://apps.odoo.com/apps/modules/11.0/account_standard_report/), I don't received email, and it is not possible to answer.

It could be great to answer quickly if there is a bug.

Regards

**Comment by pedrobaeza** [comment]
You should write to apps team to apps at odoo.com instead of putting an issue here.

**Comment by pedrobaeza** [comment]
Thanks David for commenting this in public. Good to know that is in the roadmap, although with no specific date.
