### ISSUE TITLE
Followup contact information is not displayed in crm lead

### ISSUE THREAD

**Issue by emanjuGbr** [odoo/odoo#28227]
Impacted versions: 11 and 12

Steps to reproduce: Create new crm lead and  choose contact (partner). The Followup information like adress, city, mail adress etc is not pulled to the crm lead. By selecting the same contact once again in the crm lead the information are displayed.  

Current behavior: Contact Information is not displayed in Followup information of the crm lead, except name. Tested on demo.odoo.com

Expected behavior: All Contact Information should be displayed in the Followup information of the crm lead directly when created.

Video/Screenshot link (optional):
![issue](https://user-images.githubusercontent.com/35203703/47617426-42de1d80-dac7-11e8-8308-869ea8be4384.gif)

**Comment by pedrobaeza** [comment]
Do you mean that is not shown in the kanban view?

**Comment by emanjuGbr** [comment]
Sorry, wrong screenshot. I mean the initial contact information are not pulled directly after creating a new crm lead. (Screenshot is should be)
![image](https://user-images.githubusercontent.com/35203703/47617513-2d1d2800-dac8-11e8-8f8c-769cbd9c77e8.png)

**Comment by pedrobaeza** [comment]
That information only appears if you have created a contact the same time you create the lead. Is that the case?

**Comment by emanjuGbr** [comment]
No it's independent. The same behaviour appears for new contacts as for existing ones. The problem is that after creating a new lead, the initial contact information (Followup) is not displayed automatically. 
![image](https://user-images.githubusercontent.com/35203703/47617884-9141eb00-dacc-11e8-8762-eeb65d461085.png)

**Comment by pch-odoo** [comment]
Seems like it has been fixed already. :) 
@pedrobaeza

**Comment by pedrobaeza** [comment]
Thanks for the followup. Closing.
