### ISSUE TITLE
[12.0] hr_holidays: accrual issue?

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28236]
https://github.com/odoo/odoo/blob/29dc21ae4bf40cfa184820b40c7e219ac3da1a80/addons/hr_holidays/models/hr_leave_allocation.py#L169

won't this cause an issue when `holiday_type != 'employee'`? Since accrual calculation is quite employee-centric, shouldn't it be available only for `holiday_type == 'employee'`?

**Comment by RomainLibert** [comment]
This has actually been fixed as it would cause some problems with department allocations, ... Here is the commit : https://github.com/odoo/odoo/commit/9ee9546d5967b1e7b534d9059cd4a79f471f250a
