### ISSUE TITLE
[12.0] Autoinstall theme_*

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#28266]
### Impacted versions:
v12.0
### Steps to reproduce:
At v11.0 themes were installed just by adding them as a dependency in your main app.
Now at v12.0 you need to execute `button_choose_theme` function of the module `website_theme_install`.

So in order to automate the installation, the button execution was tried to be made by a function record at a data file

Current behavior:
The installation gets cycled:
- Load main app data/theme_install.xml
- install theme_*
- Reload main app
- install theme_*
- cycled

## Expected behavior:
Provided a way to atomate thems installation or fix the the proccess followed above.

Video/Screenshot link (optional):

OPW 1904437

**Comment by dbh-odoo** [comment]
Hello @hugho-ad 
In v11 there is no concept for multi-website there is one website one theme;
So you can install one theme at a time and use that theme for the website.

While in V12 there is one feature added for multi-website, now user can use more than one website and different theme per website, so there is a case when more than one theme is installed at a time for the different website; that's why not be able to identify which theme will apply on which website.

So you have to choose a theme for every website from website setting, to apply a theme for that particular website.
When button_choose_theme is executed; It will find the current website and the current theme 
 module(theme_*); it will add website_id for that theme and load all the assets of that particular theme only for linked website_id.

Hope it's helpful to you.

**Comment by hugho-ad** [comment]
Hello @dbh-odoo 

> so there is a case when more than one theme is installed at a time for the different website; that's why not be able to identify which theme will apply on which website.

Yes, it's possible by passing the `website_id` by context or sessión https://github.com/odoo/odoo/blob/5e055a2afd23bd4e6a29c18c86d1978dcd98fc9f/addons/website/models/website.py#L461

I understand the new feature, but this seems to my kind of buggy, because it must provide a way to pre-install a theme for any website. e.g.

- Main App 
  - Create Website A
  - Create Website B
  - Inherit Default Website (for customization purposes only)
  - Install Theme A for Website A
  - Install Theme B for Website B and Default Website

At the end of Main App installation we expect 3 differents websites each with a theme installed.
But that ain't happen because the cycled issue reported above.


Regards!

**Comment by dbh-odoo** [comment]
Hello @hugho-ad sorry for late 

> [odoo/addons/website/models/website.py](https://github.com/odoo/odoo/blob/5e055a2afd23bd4e6a29c18c86d1978dcd98fc9f/addons/website/models/website.py#L461)
>  website_id = self.env.context.get('website_id') 

As I said if the user wants to reference website for the theme then need to set `website_id` to a theme. 

For the case you have mentioned; when a user wants to reference theme for a particular website then need to set `theme_id` for that particular website.

https://github.com/odoo/odoo/blob/01706392620e909b8deb9fdb1ea7793516bb8e16/addons/website/models/website.py#L106

in the website, there is one field `theme_id` which reference theme which will use for that particular website; if `theme_id` id is set and that theme is installed then it will use that theme directly for that website. 

currently when `button_choose_theme` method call it will set `theme_id` for that website and it will get  `website_id` from `get_current_website` method

https://github.com/odoo/odoo/blob/01706392620e909b8deb9fdb1ea7793516bb8e16/addons/website_theme_install/models/ir_module_module.py#L354

> * Main App
>   
>   * Create Website A
>   * Create Website B
>   * Inherit Default Website (for customization purposes only)
>   * Install Theme A for Website A
>   * Install Theme B for Website B and Default Website

so, in this case, manually you have to set Theme A  as `theme_id` for Website A
same for Website B; set Theme B as  `theme_id` for Website B
Now when you install the theme it will directly use Theme A for Website A and Theme B for Website B
you dont have to go to choose theme page.

Hope it will help

If you still have any doubt you can ask :).

**Comment by hugho-ad** [comment]
@dbh-odoo 

> so, in this case, Manually you have to set Theme A as theme_id for Website A
same for Website B the value of theme_id should be Theme B
Now when you install the theme it will directly use Theme A for Website A and Theme B for Website B
you don't have to go to choose theme page.

So you are saying to do somthing like following:

Create data for main app
```xml
<odoo noupdate="1">
    <record id="website.default_website" model="website">                                                                                                                                                                                      
        <field name="theme_id" ref="base.module_theme_vauxoo"/>                    
    </record> 
<odoo 
```
And add theme_A module as dependency of mail app module?

**Comment by dbh-odoo** [comment]
@hugho-ad 

> ```
> <odoo noupdate="1">
>     <record id="website.default_website" model="website">                                                                                                                                                                                      
>         <field name="theme_id" ref="base.module_theme_a"/>                    
>     </record> 
> <odoo 
> ```
> 
> And add theme_A module as dependency of mail app module?

yes; it will use theme_A for `website.default_website`

if you want to use theme A for website A and theme B for website B then do something like this

 ```
       <record id="website_a" model="website">
            <field name="name">Website A</field>
            <field name="theme_id" ref="base.module_theme_a"/>
       </record>
       <record id="website_b" model="website">
            <field name="name">Website B</field>
            <field name="theme_id" ref="base.module_theme_b"/>
        </record>
 ```
And put Theme_A and Theme_B as dependency of main app. 
 so when you install main app it will create Website_A and Website_B and use Theme_A for Website_A and Theme_B for Website_B.

**Comment by hugho-ad** [comment]
That's exactly what I'm doing, but It doesn't work

.scss and other static files, doesn't appear, I know that because it fails at style compilation 
I'm inheriting like following:
```xml
<odoo>                                                                             
    <template id="assets_frontend" inherit_id="website.assets_frontend">
        <xpath expr="//link[last()]" position="after">                             
            <link href="/main_app/static/src/scss/apps.scss" rel="stylesheet" type="text/scss"/>                                                                                                                                                 
            <link href="/main_app/static/src/scss/main.scss" rel="stylesheet" type="text/scss"/>
            <link href="/main_app/static/src/css/apps.css" rel="stylesheet" type="text/css"/>
        </xpath> 
    </template>
<odoo>
```

Style compilation failure
![image](https://user-images.githubusercontent.com/10233975/48373606-ef9fc980-e687-11e8-9f8c-c109bd6e65ca.png)

### What I'm doing **manually** is update theme_a in order to simulate  https://github.com/odoo/odoo/blob/80cef9e8c52ff7dc0715a7478a2288d3de7065df/addons/website_theme_install/models/ir_module_module.py#L314
I also sure that theme_a is on main_app dependencies.
After that, my static files appear on assets_frontend correctly
```python
odoo-bin -u theme_a
```

**Comment by dbh-odoo** [comment]
@hugho-ad 
> That's exactly what I'm doing, but It doesn't work

But it is working on my side.

![48373606 ef9fc980 e687 11e8 9f8c c109bd6e65ca png 974x882](https://user-images.githubusercontent.com/20393833/48424717-32959600-e789-11e8-8821-cc302a70d0f9.png)

in this image, the error is because of less variable not because of the theme.
you have used a variable before assignment; what I meant to say is you have to load the file first in which you have defined the variable and after that the file in which you have used that variable you can't change the sequence. 

> ```
> <odoo>                                                                             
>     <template id="assets_frontend" inherit_id="website.assets_frontend">
>         <xpath expr="//link[last()]" position="after">                             
>             <link href="/main_app/static/src/scss/apps.scss" rel="stylesheet" type="text/scss"/>                                                                                                                                                 
>             <link href="/main_app/static/src/scss/main.scss" rel="stylesheet" type="text/scss"/>
>             <link href="/main_app/static/src/css/apps.css" rel="stylesheet" type="text/css"/>
>         </xpath> 
>     </template>
> <odoo>
> ```

in this; if you defined a variable in main.scss then you have to change the sequence, it should be like: 
- first main.scss
- apps.scss
- apps.css

In assets bundle always load the less file first in which you have defined the variable then other files which are using that variable.

**Comment by hugho-ad** [comment]
Hi @dbh-odoo 

The style error it because of  theme_a isn't loaded, the var undefined error that you see, its because, that var is defined at theme_a but since theme_a is never loaded the style error,  and I'm using that var in the main app waiting for that var be always defined after installation. 

The theme_a is loaded until I made manually -u theme_a.

So this is not a problem with sequences.

Regards!

**Comment by hugho-ad** [comment]
@dbh-odoo 

I ain't receive any feedback yet about my last comment

**Comment by hugho-ad** [comment]
@dbh-odoo 

I ain't receive any feedback yet about my last comment

**Comment by dbh-odoo** [comment]
@hugho-ad 
Sorry for late replay 
what you can do is define a variable in the main app and override it in the theme module and then use it in the main app it will work

For reference see bootstrap_overridden/ primary_variable files in themes it's working

**Comment by hugho-ad** [comment]
@dbh-odoo 

Your not seeing the main point, **theme_a assets aren't loaded** until the -u theme_a process.
I know that because the error explained above, style errors appears after installation process finish.

There **must not** be any need of a secondary process (-u) after main_app installation.

I hope I was clear.

Best regards!

**Comment by hugho-ad** [comment]
@rda-odoo 

Waiting for a fix or a workaround.

**Comment by hugho-ad** [comment]
@JKE-be 

Thanks! Cool, that is the same that I did at my end, but it seems to me that auto-installs a theme process must be improved don't you think?

I think it must be enough with setting the following

```xml
  <record id="new_website" model='website'>
            <field name='name'>My new website</field>
            <field name='theme_id' ref="base.module_theme_default" />
        </record>
```

Regards!

**Comment by JKE-be** [comment]
No thanks for the proposition.

And next time, provide your code if you have something that works!
That will avoid to loose time creating a module just to show you with details how to do it.

**Comment by rda-odoo** [comment]
@JKE-be  Thanks!
