### ISSUE TITLE
[12] Expected singleton: uom.uom() on selecting uom on Invoice line

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28269]
Impacted versions: 12
Runbot: http://391558-12-0-fb2042.runbot14.odoo.com/web

Steps to reproduce:
Enable Multiple UoM feature from settings
![screenshot 66](https://user-images.githubusercontent.com/16624719/47671839-7e1b4200-dbd6-11e8-9628-47afc14cc1c3.png)

Select UoM on Invoice line
Current behavior:
![screenshot 65](https://user-images.githubusercontent.com/16624719/47671775-54fab180-dbd6-11e8-8876-dbd49a1d1fde.png)

![screenshot 64](https://user-images.githubusercontent.com/16624719/47671735-42807800-dbd6-11e8-805b-9627285c6a79.png)

Expected behavior:
Able to select Uom
Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
This makes sense functionally, you cannot choose a `uom.uom` if you haven't chosen a `product.product`, as the available uom depend on the chosen product.

However, I agree that this is not handled gracefully, PR #28278 should fix this, thanks.
