### ISSUE TITLE
[12.0] unable to see license key in ir.config_parameters

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#28265]
Impacted versions: 12.0

Steps to reproduce:
1. Install an Odoo and add some apps
2. Fill in your enterprise license

Current behavior: There is no `database.enterprise_code` created in the `ir.config_parameter` table
The update notification does go off:
![image](https://user-images.githubusercontent.com/6352350/47662159-b43ad080-db9a-11e8-8a85-a94484c5b639.png)
The function with the license key too:
![image](https://user-images.githubusercontent.com/6352350/47662225-d2083580-db9a-11e8-8a65-17ea58d3c3cb.png)
After this is done all values are added as parameters except for the `database.enterprise_code`:

![image](https://user-images.githubusercontent.com/6352350/47662307-f401b800-db9a-11e8-8ac8-52e754f32d5d.png)

Expected behavior: There is a `database.enterprise_code` created in the `ir.config_parameter` table just like in old versions, so you can see the enterprise license

**Comment by nim-odoo** [comment]
Expected for partnership contracts
