### ISSUE TITLE
Discussion inbox doesn't work

### ISSUE THREAD

**Issue by nurlanf** [odoo/odoo#28274]
I am setting domain, incoming mail server and alias. Can't get messages to my discussion inbox. Same way at odoo 11 works like a charm

**Comment by pedrobaeza** [comment]
Without more information is impossible to know what happens. Logs? Configuration? Stack trace?

**Comment by nurlanf** [comment]
Setting External mail server from general settings
Setting Domain.
Setting incoming mail server with catchall user and confirming.
Setting alias for admin@domain.com for Administrator like below:

Aliased Model | Users
-- | --
Record Thread ID | 1
Default Values | {}
Alias Contact Security | Everyone
Owner | Administrator
Parent Model | Users
Parent Record Thread ID | 1

Can see lead creation from info@domain.com but can't get  messages sent to admin@domain.com. I set in simple mail client on my computer, and I get all messages to catchall@domain.com as well as for admin@domain.com.

I am not sure what else I can provide.  If you guide me, I will try. THanks

**Comment by pedrobaeza** [comment]
Creating an alias in Odoo doesn't serve if you don't configure the same alias in your mail server. Any way, this is definitively not a problem of Odoo, so closing the issue.

You should make additional question on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

**Comment by nurlanf** [comment]
same alias configured in my mail server and as I mentioned before it works for Odoo11 well. If I get mails from other mail client, it means alias is configured on Postfix correctly.  please check it on your side. I tested million times, and also on Odoo Saas 12, it didn't work. You just try to close the issue without confirmation
