### ISSUE TITLE
[12] Invalid form view for Invoices created from Dashboard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28271]
Impacted versions: 12

Steps to reproduce:
Create New Customer Invoice from Invoicing Dashboard
![screenshot 67](https://user-images.githubusercontent.com/16624719/47672772-d5baad00-dbd8-11e8-9a11-24992006a907.png)

Current behavior:
Invalid form View on Refresh
Expected behavior:
Customer Invoice View should be there
![peek 2018-10-30 00-13](https://user-images.githubusercontent.com/16624719/47672777-d9e6ca80-dbd8-11e8-8517-0055dbbb6021.gif)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something expected, as you lose the context of the action. There's no better solution I'm afraid. Something similar happens if you reload being on a child view. You lose the breadcrumb of previous parents.

Closing as won't fix due to current architecture.
