### ISSUE TITLE
[12.0] hr: home address check issue?

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28273]
https://github.com/odoo/odoo/blob/fb204253bbfbb14b207fe8c1a18942d07b10d82c/addons/hr/models/hr.py#L289

Shouldn't this check if `employee.address_home_id.type == 'private'` then it's ok?

**Comment by pedrobaeza** [comment]
You can define private addresses for other uses. In fact, "private" type was introduced after all of this was created, and the other check has been in use for a lot of versions being correct IMO.

**Comment by alexey-pelykh** [comment]
In my case, a `res.partner` is linked to a user that is employee, and that user has a company linked to it (seems normal?) yet same `res.partner` can not be a Related User of the employee - makes no sense, it seems. To overcome this I have to OR have 2 different `res.partner` for a single human, or have single `res.partner` yet not linked to the company

What was the idea behind this? I guess I'm not using it correctly then?

**Comment by pedrobaeza** [comment]
You have 2 partners linked to your employee: the company one, having as parent the company partner, and another private home one, with your personal mobile, personal e-mail, and personal home address, which is this one (and not linked to any company).

**Comment by alexey-pelykh** [comment]
And how to make that "personal" partner invisible from the contacts list for others? Or address on that record? Or that's something not available?

**Comment by pedrobaeza** [comment]
That's something handled by record rules that apply over private address type. If you set this type, other won't see that records (except HR managers).

**Comment by alexey-pelykh** [comment]
Well, this check is still wrong - I've created a separate `res.partner` w/o any link to the company, did not enter an address in it, added a Private Address to that contact, selected that address from the contacts list to be the Private Address of the person - and still the warning is shown

**Comment by alexey-pelykh** [comment]
So there's no actual way to may a private address private

**Comment by pedrobaeza** [comment]
As said, you don't have to put a parent company on the home address. It should be a "dangling" partner. Closing this any way as there's no issue.
