### ISSUE TITLE
 You try to install module 'school' that depends on module 'report'.

### ISSUE THREAD

**Issue by Atul1413** [odoo/odoo#28303]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Atul1413** [comment]
![module report](https://user-images.githubusercontent.com/11453397/47765791-b1062880-dcf1-11e8-9fd6-8a2932e28d20.JPG)

**Comment by Yenthe666** [comment]
Hi,

This is about a custom module and not a bug in the official Odoo code. The module 'report' existed in V9 & V10 but no longer in 11 and up, perhaps the developer did not solve that. You should reach out to the other of the module.

Regards,
Yenthe
