### ISSUE TITLE
[12]Currency symbol not change in sale order line(sub total field)  after changing price list

### ISSUE THREAD

**Issue by JagdishPanchalSCS** [odoo/odoo#28304]
Impacted versions:12

Steps to reproduce:
Create sales Order with Pricelist having USD currency
Add sale order line and save then change the price list having currency EUR or other
The sale order main total fields currency symbol changed but in sale order line(sub total field)  it remain usd symbol

Current behavior:
Currency symbol not change in sale order line(sub total field) after changing price list
Expected behavior:
It should change the symbol of odrder line(Sub total field) when change the price list
Video/Screenshot link (optional):
![odoo eur1](https://user-images.githubusercontent.com/33276865/47767947-e9126900-dcfb-11e8-9cb1-0007516022cf.png)
![so121 odoo123](https://user-images.githubusercontent.com/33276865/47767949-e9aaff80-dcfb-11e8-90bd-9af760538f05.png)

**Comment by sunny-kumar38** [comment]
Hi Team,
Any update on this issue.
Thanks

**Comment by Feyensv** [comment]
Fixed by https://github.com/odoo/odoo/pull/38759 ;).
