### ISSUE TITLE
[master] hr_holidays: Datetime vs Date for date_from/_to?

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28305]
https://github.com/odoo/odoo/blob/f9b93e867ae2e9de629acc5ba630ebbb7439734d/addons/hr_holidays/models/hr_leave_allocation.py#L49

any particular reason to make `date_from`/`date_to` a `Datetime` instead of `Date`?

**Comment by Elkasitu** [comment]
Hi, please read our [contribution guidelines](https://github.com/odoo/odoo/wiki/Contributing) before opening any more issues.

This applies to #28306 as well.
