### ISSUE TITLE
[12] Activity icon on top menu not automatically updated

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28308]
**Impacted versions:**
12

**Steps to reproduce:**
Creat two activities for today
refresh screen
icon of tasks in top menu shows 2 activities for today
press Today 2
The two activities shows
make one of them done

**Current behavior:**
Icon on top menu shows the number 2 instead of 1
it shown the number 1 only when clicking on the icon

**Expected behavior:**
Since 1 activity was done, number shall become 1 instead of 2

**Comment by sswapnesh** [comment]
Works well on latest v12.
It would help If you can add some screenshots or Video

**Comment by Yenthe666** [comment]
Hi,

I've just tested this too and it works fine on the latest 12.0. Please update your local Odoo instance.
If you can still reproduce it on the latest V12 runbot (runbot.odoo.com) then please provide a video or screenshots simulating the behaviour.

Regards,
Yenthe
