### ISSUE TITLE
Default stock locations in Stock module don't have translations in spanish (es)

### ISSUE THREAD

**Issue by icoro** [odoo/odoo#28336]
Impacted versions: V12

Missing translation terms for default stock locations in es.po in stock module.

Missing translations such as:

#. module: stock
#: model:stock.location,name:stock.stock_location_locations_partner
msgid "Partner Locations"
msgstr "Ubicaciones de empresas"

#. module: stock
#: model:stock.location,name:stock.stock_location_locations
msgid "Physical Locations"
msgstr "Ubicaciones físicas"

and several others are missing.

**Comment by Yenthe666** [comment]
Hi @icoro,

You can always translate them through Transifex, where all source terms from Odoo are hosted.
See https://www.transifex.com/odoo/
