### ISSUE TITLE
[12] Sales Delivery Order gives Error about Unit of Measure

### ISSUE THREAD

**Issue by netronuk** [odoo/odoo#28332]
Impacted versions:
Odoo 12

Steps to reproduce:
https://www.odoo.com/forum/help-1/question/odoo-12-delivery-order-gives-error-about-unit-of-measure-141461

Current behavior:
Odoo 12 accept creating UOM conversion on both in BOM and Purchase Order, but not in Sales Delivery Order. When BOM is configured as KIT, we get the error message.

Expected behavior:
Sales Delivery Order should be DONE after click on Receive Products.

Video/Screenshot link (optional):
https://www.odoo.com/forum/help-1/question/odoo-12-delivery-order-gives-error-about-unit-of-measure-141461

**Comment by netronuk** [comment]
This issue was Odoo BUG.
As of TODAY (9/11/2018) it is fixed by Odoo Team.

**Comment by matteoopenf** [comment]
> This issue was Odoo BUG. As of TODAY (9/11/2018) it is fixed by Odoo Team. Please CLOSE the issue.

Hi,  which is the pull request I have a similar error.
Thank you
