### ISSUE TITLE
[v10] validating consume picking do not update consumed material in MO

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#28334]
Impacted versions:
V10

Steps to reproduce:
install purchase managment
install mrp
configure product catchase egory,  real cost and perpetual valuation, set relevant account for inventory move
create manufactured product
create components product
create BOM
create MO
check material availability
purchase component and validate the receiving

in this step the consume picking will have to process and if we reserve material is available
edit consume picking line for done qty
validate the consume picking

I expect the consumed material in the MO is updated withstock move from consume picking
but it is not 
 

Current behavior:
validating consume picking move, not updated consumed qty in MO
validating consume picking also not generating journal (although perpetual valuation is set)
consume picking once validated,  automatically create other consume picking for the MO

Expected behavior:
the consumed qty in MO should be updated (as material is transfered to production become wip

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @bunhin,

As Odoo 13 has been released last week it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
