### ISSUE TITLE
User with Technical settings (group_no_one) but cannot display email messages

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoo/odoo#28340]
When a user has the debug mode (Technical Settings) activated they cannot display the mails associated to mail tracking, due to a permissions issue. Only users in group Administration/Settings  can access to object mail.tracking.value.

It is very common for certain users to have the technical settings (base.group_no_one) activated. 

IMHO the root cause of the problem is that mail_tracking provides the ability for any user to access emails. tracking values associated to mail.message should only be accessible by Administrator/Settings users, not by 'base.group_no_one'.

**Comment by Yenthe666** [comment]
@tde-banana-odoo for your interest!
