### ISSUE TITLE
can't search product by barcode/ref in sale order view

### ISSUE THREAD

**Issue by 159820** [odoo/odoo#28344]
Impacted versions:
12
Steps to reproduce:
create a part:   'Part01'  with ref: 'PN001' and barcode: 'PN001'
create a SO, and add 'Part01' into SO line

In SO view, when search by Product with keyword 'Part01' , we can find ths SO created.
When search by Product with keyword 'PN001', now result shown.

Current behavior:

Expected behavior:
should find the SO when search by Product with keyword 'PN001'

Video/Screenshot link (optional):

**Comment by janbec** [comment]
I tested this on v12e runbot and can confirm that you cannot search for products in sale order tree view search, will display 'no data' as search result...

**Comment by pedrobaeza** [comment]
Please attach a video of the problem, as reading what you describe I don't see the problem.

**Comment by pedrobaeza** [comment]
@janbec thanks for the video. Now I understand you, but that's simply something not implemented. I don't consider it a bug, but an enhancement.

@mart-e what do you think about including the internal reference in the search of the product (probably `name_search`)?

**Comment by janbec** [comment]
@pedrobaeza Sure, no problem :). This works in v11 though and I wouldn't want to live without it on our prod database

**Comment by 159820** [comment]
@pedrobaeza this wotks fine in odoo11.  i ckecked the code and find the search field in odoo11 is 'product_id' ,but in odoo12  the search field is 'order_line'.

when search a product, the name_search function in model SaleOrderLine is not triggered.

probably we sould override the name_search function in model SaleOrder?
