### ISSUE TITLE
[12.0] How to migrate database from 11.0 to 12.0?

### ISSUE THREAD

**Issue by ywiyogo** [odoo/odoo#28341]
Impacted versions: 12-0

Steps to reproduce:
1. Working with Odoo 11
2. `git clone https://github.com/odoo/odoo.git`
3. sudo systemctl start postgresql
4. `./odoo-bin --logfile=odoo.log` 

Current behavior:
On browser I see Internal Server Error.
In the odoo.log I can see this error:
```
File "/home/user/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_lang.week_start does not exist
LINE 1: ...e_date","res_lang"."date_format" as "date_format","res_lang"...
```

Expected behavior:
No error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You can't migrate that way a database. You need to subscribe to Odoo enterprise service or look for a community alternative like OpenUpgrade, but it's quite technical and requires deep skills.

Closing as no real issue.
