### ISSUE TITLE
missing dependency in js

### ISSUE THREAD

**Issue by aaguptaayush** [odoo/odoo#28359]
Missing dependencies:    (2) ["mail", "mail_base.base"] 
Rejected modules:        ["web_tour.tour"] 
Rejected linked modules: (11) ["account_accountant.tour", "sale_stock.tour", "crm.tour", "hr_expense.tour", "hr_recruitment.tour", "mail.tour", "sale.tour", "project.tour", "sale_crm.tour", "web_tour.DebugManager", "web_editor.tour"]

**Comment by pedrobaeza** [comment]
Please include steps to reproduce the problem.

**Comment by aaguptaayush** [comment]
i have call send_notification in my custom module

**Comment by pedrobaeza** [comment]
Then it's problem of your custom code. Please fix it there.

Closing as no real issue in Odoo core.
