### ISSUE TITLE
i was getting a similier error but when upgrade all modules.

### ISSUE THREAD

**Issue by aaguptaayush** [odoo/odoo#28357]
in log message i got :
 Invalidating all model caches after database signaling.
and on browser got this :

![image](https://cloud.githubusercontent.com/assets/7659863/20036135/28b46c62-a431-11e6-966e-956ce966533d.png)

_Originally posted by @bimajatiwijaya in https://github.com/odoo/odoo/issues/9297#issuecomment-258666000_

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment or your custom modules, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by aaguptaayush** [comment]
i have this issue when i up the server in odoo-10
