### ISSUE TITLE
[10/11/12] 'selection' is always empty on ir.model.fields

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#28360]
Impacted versions: 10, 11 and 12

Steps to reproduce:
Connect to runbot as admin.
Enable developper mode.
Go to the menu "Settings > Database structure > Fields
Choose a selection field in the list: you will see that the field "Selection Options" (technical name: selection) is empty, cf screenshot.

![odoo_selection_empty](https://user-images.githubusercontent.com/1157917/47922292-fde72c00-deb6-11e8-8880-cdc39fc7297a.png)

**Comment by pedrobaeza** [comment]
Fixed in 5f5bb5e26b0cf49dc48d00eeac80fa25bca315c5

**Comment by odony** [comment]
The fix broke custom fields and was reverted - see #31447. It's a reminder that it's always risky to fix minor details in stable versions, as it can backfire badly for something that was unimportant to begin with.

**Comment by pedrobaeza** [comment]
Wasn't it reverted?

**Comment by Elkasitu** [comment]
5f5bb5e was forward-ported but the revert commit too, so it should be fine

**Comment by mart-e** [comment]
And can be closed again as fixed in 13/master with the `ir.model.fields.selection`
