### ISSUE TITLE
no quantity updating in pick components and finished product receipt 

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#28379]
Impacted versions:
CE 12
Steps to reproduce:
create a MO 
update quantity to produce
neither pick components nor finished product receipt will be updated

Current behavior:
no quantity updating in pick components and finished product receipt 

Expected behavior:
quantity updating in pick components and finished product receipt 

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @ccandito 
This seems working fine on latest 12 CE.
Qty of components are Increased If we update Quantity To Produce
![screenshot 82](https://user-images.githubusercontent.com/16624719/47963001-5818f600-e04b-11e8-8ffc-787c1a938534.png)
![screenshot 83](https://user-images.githubusercontent.com/16624719/47963010-6e26b680-e04b-11e8-8bff-0e20e8f16554.png)
![screenshot 84](https://user-images.githubusercontent.com/16624719/47963011-6ebf4d00-e04b-11e8-9949-5e111c7e236e.png)


Ps: We cannot Increase finished product by Updating Quantity To Produce in MO, For that we have to Process Work Order with new quantities

**Comment by pedrobaeza** [comment]
@sswapnesh did you check again the issue?

**Comment by sswapnesh** [comment]
Not yet 

_(Too bad for me that I have missed it)_

**Comment by sle-odoo** [comment]
This should be working, let's hear from @ccandito  if he's able to reproduce the issue again.

Regards
