### ISSUE TITLE
[12] Uploading Document Via html field does not work

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28375]
Impacted versions: 12

Steps to reproduce:
![screenshot 75](https://user-images.githubusercontent.com/16624719/47960234-be871f80-e01d-11e8-8be0-1e3481faa230.png)
![screenshot 76](https://user-images.githubusercontent.com/16624719/47960238-d2cb1c80-e01d-11e8-9d20-8dab9e053cbe.png)
![screenshot 77](https://user-images.githubusercontent.com/16624719/47960265-42410c00-e01e-11e8-93e0-b50f03eca357.png)

Current behavior:
Wrong button String  (In v11 too)
Uploading Doc doesn't work 
![screenshot 78](https://user-images.githubusercontent.com/16624719/47960270-440acf80-e01e-11e8-8f04-fe7fa9959f5b.png)

Expected behavior:
As v11
![screenshot 79](https://user-images.githubusercontent.com/16624719/47960282-761c3180-e01e-11e8-86c1-dba259415ad1.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That button is not for uploading documents to the message, but for uploading resource to the website part, and link there in the message, so I don't see the problem.

**Comment by sswapnesh** [comment]
But it should add Docs as it is doing in v11.
