### ISSUE TITLE
[11.0 CE] 10-15 POS tabs push the minus, plus and close buttons away from being able to be selected

### ISSUE THREAD

**Issue by svenv** [odoo/odoo#28373]
Impacted versions: 11.0

Steps to reproduce:

1. Open a POS-session on any device on any browser (I've tried many).
2. Click + sign to add more orders
3. When more than 10-15 orders are open, the Close, Minus and Plus button disappear. Once the minus button disappears you'll be unable to close any orders.

Video/Screenshot link (optional):

Video link: https://photos.app.goo.gl/mQRNJQ2ERGvUMmqPA

**Comment by pedrobaeza** [comment]
I don't consider this as a general problem, as the number of opened orders is still high and there's not too much practical cases when you got to that situation.

**Comment by switch87** [comment]
@svenv Thank you for reporting this issue. 
As @pedrobaeza mentions, on your video it are unlikely many orders, but on my smartphone this problem occurs after 3 opened orders so it could indeed be a problem in some cases.

**Comment by pedrobaeza** [comment]
A CSS trick for doing that scrollable maybe?

**Comment by svenv** [comment]
It's one of the reasons why we haven't switched from Windows to a Tablet, because on a tablet you can only have 5-10 or so open, depending on the screen resolution.

Issue #28592 can contribute to this issue as well.

**Comment by pedrobaeza** [comment]
This has been fixed in #28605 and we'll be forward-ported in 11.0 and 12.0 soon, so I close the issue.
