### ISSUE TITLE
Payroll module not visible

### ISSUE THREAD

**Issue by karigarweb** [odoo/odoo#28380]
Impacted versions: 12

Steps to reproduce: Goto to apps interface

Video/Screenshot link (optional): 
![screenshot_2018-11-04 apps - zeenaterp](https://user-images.githubusercontent.com/13769303/47962219-43ccfd00-e03b-11e8-98b0-fdea7e4915fb.png)
![screenshot_2018-11-04 apps - zeenaterp 1](https://user-images.githubusercontent.com/13769303/47962220-44659380-e03b-11e8-832e-23b05fe7d579.png)

For some reasons Payroll module is not appearing for us.

**Comment by Yenthe666** [comment]
Hi there,

I've just checked this on 12.0 but the app is right there:
![image](https://user-images.githubusercontent.com/6352350/47987730-8eed1b80-e0e0-11e8-84c6-b726c2168aa3.png)
You might want to filter/search on it.


Regards,
Yenthe

**Comment by Yenthe666** [comment]
No problem, happy you've solved it!
