### ISSUE TITLE
A question about weird line of code

### ISSUE THREAD

**Issue by s265925** [odoo/odoo#28383]
Hello everybody 
I am looking at the '/web/login' route in "addons/web/controllers/main.py"
and there is a line i cant understand the reason of it .
in the web_login function :
`if not request.uid:`
`        request.uid = odoo.SUPERUSER_ID`
could any body please explain why it is there ? and what it is doing ?
I looked at blame and there is a small comment in commit

`[FIX] /web/login: Set request.uid on auth=none so it's correct if overloaded with auth="public"
bzr revid: fme@openerp.com-20140211113916-2to1g41pccimbsgq`

Thanks for the help

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
