### ISSUE TITLE
Email sent History from odoo for complete audit

### ISSUE THREAD

**Issue by HYROPES** [odoo/odoo#28432]
**Impacted versions:**
All
**Problem:**
At moment, there is no single place for system admin audit all emails sent from Odoo.

**This is a good example:**
User just request a password reset. Admin click reset password and Odoo sent out an Email.
However, This email record can not be traced anywhere in Odoo system.(besides the notification above that user profile page)
I checked the following place, cannot see any trace of sending such email.
```
- Settings – Technical – Messages
- Settings – Technical – Emails
```

This makes audit email sending not easy, 

- How to make sure that Odoo keep a record of what been sent and retrieve such record in future?
- How to audit that reset password email been sent XXX times a day? Is those information hide deep somewhere?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by HYROPES** [comment]
Okay, no problem. Thanks for the reply.
