### ISSUE TITLE
[Odoo Apps] it is only possible to connect to iOS/Google Apps with a login/password

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#28437]
this app https://itunes.apple.com/be/app/awesome-timesheet/id1078657549?mt=8 is only compatible with a login/password authentification.

it is not possible to use OAuth Authentication

**Comment by HYROPES** [comment]
Hi @fmdl 
The same issue with Enterprise Odoo Official iOS app. 

But I think this is not an Odoo issue, rather than ask the App developer to support such a feature.
Contact Odoo official support, you might have a more direct handle on such feature support.
https://www.odoo.com/help

**Comment by adr-odoo** [comment]
Hello,
@fmdl Thx for your feedback
I will create a task to add OAuth support in Awesome timesheet app but I can't guarantee that we will do it.

@HYROPES In my mind iOS app shoud support Oauth from version 11.0.

Regards,

**Comment by adr-odoo** [comment]
@HYROPES As I need some other sensitive information, feel free to contact our support on
https://www.odoo.com/help.

I will handle your issue.

Regards,

**Comment by HYROPES** [comment]
@adr-odoo I had just send email with my ticket number to your email address.

**Comment by fmdl** [comment]
https://itunes.apple.com/fr/app/odoo/id1272543640?mt=8 is not compatible with OAuth Authentication

**Comment by HYROPES** [comment]
To everyone who interested in finding support for OAuth login for iOS app. 
The official reply from Odoo is they have already create an internal task for the feedback, but can not guarantee the development time or the feasibility. They need to discuss it internally.

I still keep the hope high as OAuth authentication were increasingly popular, having a mobile app that support this feature can only help Odoo grow better and faster.
