### ISSUE TITLE
[12] Bubble information

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#28443]
Impacted versions:
12

Steps to reproduce:
Click on the top left menu icon
Information bubble appears near for example "Project"
Scroll down

Current behavior:
When scrolling down, the bubble stays in same place, does not move with the first indicated item.
Also some times, we see free flowing bubbles on the top left corner or the browser frame.

Expected behavior:
Information bubble shall move up and down as user is scrolling the menu up and down

**Comment by Yenthe666** [comment]
Really not a bug & it was made that way 😉

**Comment by aitalinassim** [comment]
:-(
