### ISSUE TITLE
Order (sort) is not working on search filter

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#28446]
### Impacted versions:

11.0

### Steps to reproduce:

This applies for all models, I will only take sale orders model as example.

* Go to sale orders tree view.
* filter by salesman Administrator
* order by customer
* save filter in favorites.
* (the order is not been taking into account when the favorite filter is saved). I activate developer mode and update the filter manually and set sort ["partner_id"]. 

### Current behavior:

The results are filtered but the order does not work, it seems like the sort field is not been applied. Note: I tested in version 9.0 and the sort is working so I think that in some point this feature crash.

We have two problems

1. the order is not saved when we save the filter
2. if we manually update the search filter and set the order, this one is not been applied to the search results neither.

### Expected behavior:

Be able to save the order (sort) in the search filter and that this "sort" does apply the results, this way I can select a saved filter and review the results in the specific order needed.

### Video/Screenshot link (optional):
https://youtu.be/rFlaZjQhkwA

-- 
This was tested in runbot build http://394471-11-0-349fd9.runbot17.odoo.com/

**Comment by zaoral** [comment]
opw-1906968

**Comment by vincentph** [comment]
It does not also save the view type once saved in favorites.

1. Go to CRM > pipeline
2. Select List view
3. Group by customer
4. Order by "Expected Revenue" descending
5. save in favorites (Eg. "Per Customer")

I expect that every time I clicked the "Per Customer" in favorites, it will automatically display the "List View" page of the pilpeline but instead it displays the default view which is the kanban view.

**Comment by kebeclibre** [comment]
closed by #28766 at https://github.com/odoo/odoo/commit/e713ed2a69af9fe97fbe2d54843adc8f1ce689aa
