### ISSUE TITLE
Auto_delete switch on mail templates revert back automatically

### ISSUE THREAD

**Issue by HYROPES** [odoo/odoo#28452]
**Impacted versions:**
V11 +
**Steps to reproduce:**
Turn **OFF** the Auto Delete in - Settings – Technical – Templates – **Auth Signup: Reset Password** - Auto Delete
Chose any user to perform a password reset -[Send Reset Password Instructions]
go back to check that Template, Auto delete is **turn on** again. (After the reset Email been sent)

Also, there are no trace of Email recorded under - Settings – Technical –Emails

**Current behavior:**
Certain Email template auto_delete switch changed without user interaction.

**Expected behavior:**
Those auto_delete switch shall stay put until user decide to change them.
If that is a design behavior of Odoo, then the issue is to protect user settings from other action.

No matter what other function might switch auto_delete on, but a setting in Email Template shall not be effected automatically. Otherwise, what is the point of such switch?

**Comment by sswapnesh** [comment]
This is by design to Delete Sensitive Mail, (Even auto_delete is True)

**Comment by HYROPES** [comment]
@sswapnesh Thansk for the reply, if this behavior is by design. would be better that certain changes were prohibited from changing in the first place ?
For Example, better to **lock** auto_delete from changing in sensitive mail template,Instead of **hardcode** such rules into Odoo.

**Comment by sswapnesh** [comment]
I don't think this will be handled in currency arch.
Maybe @odony  can add reviews.

**Comment by odony** [comment]
Indeed, it is an implementation constraint for security reasons, and we don't plan to change the way it is done. Besides the auto-delete flag, several other sensitive fields of the Password Reset template are enforced by the system, and will be reset before use.
Making those fields read-only for a single case (that particular template) would require a significant amount of (elatively ugly code, for the sole purpose of being *a little bit* more user-friendly in the very infrequent cases where someone would modify those fields. We prefer keeping the code simple and clean, at the cost of this minor drawback.

**Comment by HYROPES** [comment]
Thanks @odony for the explanation , I will keep it in mind.
