### ISSUE TITLE
[10.0] Barcode scanner does not work when creating new serial number

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#28453]
Impacted versions:
10.0

What are the steps to reproduce your issue?
1. Connect a barcode scanner to the computer.
2. Select a transfer with a product that is tracked "By Unique Serial Number".
3. Set the Picking Type of the transfer allows "Create New Lots/Serial Numbers" and "Use Existing Lots/Serial Numbers".
4. Press the "Lot Split" to process the transfer.
5. Press "Add an item" and scan the serial number barcode.

What is the current behavior that you observe?
An empty line is created and "Lot/Serial Number required" will be raised when the "Save" button is pressed. 
![image](https://user-images.githubusercontent.com/27185427/48107846-0acf9b00-e27c-11e8-8a90-5ae93c985529.png)

What would be your expected behavior in this case?
A new "Lot/Serial Number" record should be created automatically created upon the scanning of the barcode.

**Comment by TimLai125** [comment]
@intero-chz  I admit this issue is not a blocking issue and understand that it is not necessary to press the button when the user wishes to use existing lots/serial numbers, but it will be nice if Odoo also handles this operation pattern.

**Comment by Yenthe666** [comment]
Dear @TimLai125,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue and a personal sorry that I didn't get around to watching your video either.

Regards,
Yenthe

**Comment by PatosMarco** [comment]
Dear @TimLai125 ,

have you found a solution?

Regards,

Marco
