### ISSUE TITLE
AccessError - Portal user - Preferences

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#2845]
Fresh "Portal user" can not change password, etc..

Steps to reproduce:
1. Install Odoo v 8 with demo data
2. Install  module website
3. Login form website as "Demo portal user"   (or register new user)
4. Select web user menu "Preferences"
5. ...AccessError...     -  expected ... account edition

**Comment by dmo-odoo** [comment]
Hello,

This issue has been fixed by https://github.com/odoo/odoo/commit/a93ef48a7072f62e4b9dd728d54ddad901c92db4.

Best regards,
David

**Comment by m3dbedb** [comment]
Hello. Similar sutuatiot. I can't find where to edit demo portal user password and anble the portal. When I press in messaging>contacts>contact>Portal Access Management, selected contact didn't receive activation url.
Maybe somebody know demo portal user default password?
