### ISSUE TITLE
[12.0][Enterprise] Barcode Scanning "Tap to Scan" button doesn't work

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#28470]
Impacted versions: 12.0

Steps to reproduce:
1. Go to demo.odoo.com
1. Install the barcode app
1. Go to the barcode app
1. Use Chrome developer tools to comment out line 13 of `stock_barcode_mobile/static/src/js/stock_mobile_barcode.js` (`this.$el.find(".o_stock_mobile_barcode").remove();`)
1. Go to main menu and return to the barcode view
1. Set a debugger breakpoint to the beginning of function `open_mobile_scanner` 
1. Click on the "Tap to Scan" button (nothing happens)
1. Remove the element `<img alt="Barcode" src="/stock_barcode/static/img/barcode.png">` using Chrome developer tools
1. Click on the "Tap to Scan" button (now it finally triggers the `open_mobile_scanner` function)

You can verify the same by using the Odoo app by logging to https://demo3.odoo.com

Current behavior:
You cannot click the "Tap to Scan" button because there's an image in front of it

Expected behavior:
You can click the "Tap to Scan" button and it will open the mobile camera

Video/Screenshot link (optional):

**Comment by 159820** [comment]
yes , this function did not work in odooo mobile. nothing happen when you clicked 'tap to scan'.

**Comment by 159820** [comment]
no one watch this?
