### ISSUE TITLE
The chat window focus first messages instead of the last ones

### ISSUE THREAD

**Issue by Aeriah** [odoo/odoo#28485]
Impacted versions:
Version 10 on Ubuntu 18.04.1 LTS.

Steps to reproduce:
When I open a chat, the chat window focus on the first messages instead of the last ones. When there are a lot of messages, we have to scroll to the last messages.

Video/Screenshot link :
https://screenshots.firefox.com/E9dtoDXy6xdTTrLS/null

Odoo Forum Link :
https://www.odoo.com/fr_FR/forum/aide-1/question/chat-window-target-focus-first-messages-instead-of-the-last-ones-odoo-v10-141661

Thank you for your help :)

**Comment by Yenthe666** [comment]
Dear @Aeriah,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
