### ISSUE TITLE
[10.0,11.0,12.0] Model _description won't be translated in templates

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#28481]
Impacted versions: 10.0, 11.0, 12.0 (tested in runbot for 10.0 and 12.0)

Steps to reproduce:

1. Activate another language like German
2. Load the translation German (or another language)
3. Create an invoice by invoicing a demo sales order

Current behavior:

A note/comment will be created on the invoice telling the user "This invoice was created from: `<link to the order>`"

In German it's "Diese/r/s invoice wurde angelegt von: `<link to ther order>`"

Expected behavior:

It should be "Diese/r/s Rechnung wurde angelegt von: `<link to ther order>`"

https://github.com/odoo/odoo/blob/0662a1948b71ebd46313cbe40774553594f1c9e0/addons/mail/views/mail_templates.xml#L141-L147

The first problem here is the `lower()`, ok, especially for the German language. But i don't think using a view (QWeb view) for such messages isn't the right way, because you will always get into such problems with them. Wouldn't it be better to use mail templates? If they can't be used for notes/comments, that's maybe a feature for the Odoo v13 wishlist?

The second problem: the models _description won't be translated into the message. Non translated model descriptions makes these messages really ugly (always two languages...).

**Comment by pedrobaeza** [comment]
@mart-e can you comment about this?

**Comment by mart-e** [comment]
This is a typical example of [bad practice](https://www.odoo.com/documentation/12.0/reference/translations.html#blocks) for translations, splitting the translation in small blocks won't work for translators.
The model description is translatable so it should be possible to get the value (but use the field `name ` of the `ir.model` record).

I don't get your comment about mail template? We try to get rid of them to replace them with QWeb (maintaining and customizing mako templates is very painful).

**Comment by intero-chz** [comment]
@mart-e that's odoo original code not mine ;-) I'm with you on the mako part. Thought that mako will be replaced in mail templates by qweb. That would be very nice!

Actually i didn't dig very deep into the issue yet. `self` in this context is a recordset. Is there a way to get the models "name" from a recordset instead of using `_description` ?

**Comment by mart-e** [comment]
> that's odoo original code not mine

I know, that should not stop me for saying when it is badly written ;-)

> Is there a way to get the models "name" from a recordset instead of using _description

Starting in v11 (cf 5d746d0ac663232d656bb57e82fec290bb5d82fd), there is a `_get` method.

Something like 5d746d0ac663232d656bb57e82fec290bb5d82fd for the stable should do it.
For master, we can fully change the way we compose the message to have something nicer to translate.
