### ISSUE TITLE
Hungarian translation completly emptied with last update?

### ISSUE THREAD

**Issue by kovika** [odoo/odoo#28491]
Impacted versions:12

Steps to reproduce:static

Current behavior:No hungarian translation

Expected behavior:HUngarian translation

Video/Screenshot link (optional):

Ther is no translated terms in hungarian po files. It was updated with transifex 4 days ago, but on transifex project page, there is no translated terms for this language now.

Any info about this?

**Comment by pedrobaeza** [comment]
@mart-e do you know what happened?

**Comment by mart-e** [comment]
Not sure. Was it translated before or was it recently added to Transifex?

When you add a new language to a project, it happens frequently that the translation memory (what allows to reuse translations cross projects and resources) is not started automatically.

I have manually forced it and now Hungarian is at 52%.
I will be included in the next synchronisation.

**Comment by kovika** [comment]
Thank You,

I see now that Hungarian at 60%

Simple apt upgrade pull the translation?

**Comment by mart-e** [comment]
The synchronisations from Transifex to Github are done every Sunday. If you are using the debian/ubuntu package, it should be included in the Monday's package then.
