### ISSUE TITLE
Emails cannot contain custom reports

### ISSUE THREAD

**Issue by gcbirzan** [odoo/odoo#28513]
Impacted versions: Everything after 3425752eaca236c1e4b4d616aa49b3faa6cfd957 (not sure it was working before that, it was probably broken when `render_report` disappeared)

Steps to reproduce: Try to send an email with a custom report type.

Current behavior: An error about unsupported report type is shown.

Expected behavior: Report should be generated.

The problem comes from this:

https://github.com/odoo/odoo/blob/532d82a7a9952c5ee843f91e63aae1ca986c6c9d/addons/mail/models/mail_template.py#L472-L474

A special case for `qweb-html` might be needed, but, otherwise, `.render()` should be called on the report and it will work.

**Comment by pedrobaeza** [comment]
@tde-banana-odoo do you know why this restriction?

**Comment by gcbirzan** [comment]
My guess (as a new odoo user) is that older versions came with other types of reports that were removed and this was just a cleanup that didn't consider custom report types. We're using a patched version now and it (at first glance) seems to work as expected.

**Comment by pedrobaeza** [comment]
Well, custom reports are still allowed (see for example https://github.com/OCA/reporting-engine/pull/248), so this restriction is too much IMO.
