### ISSUE TITLE
[12.0] Timezone Preferences

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#28518]
Impacted versions:

Version 12.0

Current behavior:

Date values are always displayed according to the browser time.

Step 1:
![screenshot_20181108_225504](https://user-images.githubusercontent.com/4851083/48230033-fab5d980-e3a9-11e8-94e5-fbf8566097fb.png)

Step 2:
![screenshot_20181108_225608](https://user-images.githubusercontent.com/4851083/48230044-01445100-e3aa-11e8-8fa1-e1d62ea51e16.png)

Expected behavior:

Timezone Widget Text: 
The time in Odoo is displayed according to the timezone set on your user's preferences.

My Insight:

As far as I could see this method from the Odoo session is used everywhere to format and display a date: https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/core/session.js#L403

``` javascript
getTZOffset: function (date) {
        return -new Date(date).getTimezoneOffset();
},
```
However, this uses `new Date` to determine which time should be displayed and therefore in my eyes always the browser time is taken and not the user set timezone.

I think the best option would be to include the timezone in the `session_info` object and then change the `getTZOffset` method accordingly.

https://github.com/odoo/odoo/blob/12.0/addons/web/models/ir_http.py#L21

If this is not a bug and the described behavior is what you expect, you are welcome to close this issue. However, you might want to adjust the text in the timezone widget or remove it altogether.

**Comment by mart-e** [comment]
Yes, it has been raised in the past. Our advises is to always have the same date in your browser and user preference (hence the warning) as we use the browser at some places and the user at other (e.g. in server side code).
I think we will always need both as you can modify the behaviour of `new Date` to use a custom timezone (or I am not award of it) to avoid the need of patching everywhere we use `Date`.

**Comment by pedrobaeza** [comment]
@keshrath is there any real use case when you need to have a different timezone in the browser? Any way, you have already seen the technical problems of that, so it's not easy to fix.

**Comment by keshrath** [comment]
I don't think it's a big problem, after all, is usually the timezone set and the browser's is the same. So maybe it's enough to adjust the text in the widget, because the display in the frontend doesn't work with the timezone from the settings.

I did some searching and found this thread (https://www.odoo.com/es_ES/groups/technical-62/community-framework-13213033?mode=thread&date_begin=&date_end=). So yes, the problem didn't just occur with version 12.0, but has existed for some time. There are also some cases described where it might make sense to change the displayed time zone.

So if this problem is known or already reported this issue can be closed.

**Comment by pedrobaeza** [comment]
@keshrath the problem is that it can't be avoided without other drawbacks (like performance if everything has to be converted on the fly), so yes, better to just live with this.

**Comment by davispuh** [comment]
This sucks... It's really confusing that changing user's timezone has no effect. Especially because timezone information doesn't appear anywhere.
So you call your colleague to check order at 15:00 but he's currently abroad so he logins in and can't find order at that time because his computer's timezone is different.
This makes it pretty annoying for people who go to business trips frequently as each time you'll have different timezone and you wouldn't really expect that order times in Odoo suddenly change.

**Comment by pedrobaeza** [comment]
@davispuh please calm down the tone of your messages. You can have your opinion and express it here, but using toxic and offensive words don't help anybody. If you don't like current behavior, make the needed changes for changing it and propose them to Odoo.

**Comment by sertaikov** [comment]
> > when he is abroad then it is advised to change user preference timezone as well
> 
> This is the most retardest thing ever... there should be no expectations for user to do/change something as most people won't know nor remember to do it anyway. Especially if you travel frequently it sounds like real PITA.
> 
> Really, this is an issue and it should be fixed. The way I see how it would work is that server-side date/time calculations (including RPC/API) would be done in UTC and all user input is converted from user's timezone to UTC. User can specify in settings what timezone he wants to use for displaying (there could be option to use browsers timezone too). So then all date/time which is outputted to user would use that timezone.
> Then if for some reason server-side really needs user's timezone that should be a separate setting for user's home (default) country's timezone which wouldn't be used for displaying in browser.

I just want to share your frustration. This is absolutely retarded. We have a distributed team and team members do travel a lot.
It's few years later and the issue was not addressed. And i cant believe the amount of money we pay to odoo.

**Comment by fa-amorel** [comment]
Old thread but I shared this frustration too... if solution working on v18 can help :
In a custom module, add user timezone in session_info
`
# -*- coding: utf-8 -*-
from odoo import models
from odoo.http import request


class Http(models.AbstractModel):
    _inherit = "ir.http"

    def session_info(self):
        res = super(Http, self).session_info()
        if request.env.user:
            res["tz"] = request.env.user.tz or "UTC"
        return res
`
Then, load a js file in web.assets_backend to set default zone for Luxon :
luxon.Settings.defaultZone = session.tz
