### ISSUE TITLE
[12.0] Payroll report doesn't show currency

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#28528]
Impacted versions: 12

Steps to reproduce:

Current behavior:
In report_payslip_templates.xlm, lines:
                                <td><span t-esc="line.amount"
                                          t-esc-options='{"widget": "monetary", "display_currency": o.company_id.currency_id}'/></td>
                                <td><span t-esc="line.total"
                                          t-esc-options='{"widget": "monetary", "display_currency": o.company_id.currency_id}'/></td>
The currency symbol doesn't appear. 
 
Expected behavior:

Video/Screenshot link (optional):

**Comment by tivisse** [comment]
Hi @elperrofarelo 

Thanks for the feedback. This will be fixed at https://github.com/odoo/odoo/pull/28964

Have a nice day,

Yannick.

**Comment by elperrofarelo** [comment]
Ok. Thanks for fixing it
