### ISSUE TITLE
Float rounding problem in _product_reserve when selling a product in a different UOM

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#2854]
Selling a product in a different UOM than the one defined on the product doesn't work at all.

steps to reproduce (runbot 7.0):
-create a new unit of measure (pack8) in category unit with rounding 1 and ratio 8 (bigger)
-check rounding of unit is 1
-on a stockable product (ex Computer Case), in the inventory tab, update stock quantity to get 15 units in stock (the product must be configured in the 'information' tab with 'unit of mesure' set to 'Unit')
- create a SO for 2 pack8 of this product -> the system doesn't complain!
- confirm the SO -> in the inventory tab you have -16 in the outgoing quantity
- View delivery and ckeck availability -> the system doesn't complain!
- deliver the product -> the system doesn't complain! and your stock is now - 1

**Comment by lmignon** [comment]
@odony @jco-odoo @beledouxdenis No news for 3 months, Do you think that the linked PR #3457 will be considered? What is missing? 

Regards

**Comment by Yenthe666** [comment]
Hi @lmignon,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
