### ISSUE TITLE
Unable to find "application" callable in file .../odoo-bin

### ISSUE THREAD

**Issue by nitcheulegrand** [odoo/odoo#28548]
Impacted versions: 11.0
Steps to reproduce: 
Current behavior: Odoo 11 do not start but return error "Unable to load app 0"
Expected behavior: Odoo 11 starting well
Video/Screenshot link (optional): no screenshot

Hello,
I want odoo app to be accessible on my web site.
I set virtualenv and i use pip to install requirements and packages.
But i while runing, i got error that i copy from the log file in the following lines.
`
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1163736)
spawned uWSGI worker 1 (pid: 1163737, cores: 1)
spawned 1 offload threads for uWSGI worker 1
unable to find "application" callable in file /home/legrandsoft/flexdistribution/odoo-bin
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
`
How can i process to come to solution please ?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
