### ISSUE TITLE
[Proposal] Data Driven Business Document Transitions

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#28549]
@fpodoo 

### Remarks:
- For discussion & evolution unless there is a better alternative on the horizon.
- NIH disclaimer: Based on inspiration by SAP Business One experience

### Proposal
- In order to improve data driven business document transitions (aka "boilerplate for workflow engines"),
- Odoo should implement a generic `def emitter()` and `def receiver()` API on all supported business documents
- Which can communicate on one or several _realms_,
- Where each _realm_ defines a super set _interface struct_ of data points.
- Any receiver should be able to handle the _data point interface struct_ in it's _entirety_.
- A document dependent subset of data points of this _interface struct_ should be emitted by the emitter.
- The _realm instance_ provides a shared meta-state* without struct data itself.

\* The struct's data points should not be in that meta-state, but rather a copy operation to not forego flexibility throughout the life cycle of a realm instance.

### Implications:

- Business domain driven transition white- or blacklisting can become data.
- External or internal workflow engines (as well as external enterprise buses) can plug into this API.
- UX features like a end-to-end realm-instance-graph become possible (see SAP Business One killer feature).
- UX: Create becomes an optional "create from transition" with some selection of allowed incoming transitions (see current "add PO on invoices" functionality).
- UX: Semantical "Validate" becomes an optional "Validate and Continue" with some selection of allowed outgoing transitions (see current create invoice wizard)

Obviously there are many type of words fitting into the same thoughts. This can be probably read also as an epxression of the need for proper workflow handling. I think however, SAP business one with it's "Copy from" and Copy to" has found a particularly compelling answer in search for balance between flexibility and structure.

**Comment by blaggacao** [comment]
ping @fpodoo this is popping up again for highly transversal features which currently would have to patch quite an amount of modules.

**Comment by blaggacao** [comment]
@rco-odoo I guess you maybe might also spent a thought on this. :wink:

**Comment by pedrobaeza** [comment]
As this has been here for a while without comments, I'm closing it, because any possible ideas for new versions has been already taken.
