### ISSUE TITLE
Error when print chart of account item from General Ledger and balance sheet.

### ISSUE THREAD

**Issue by asiamatrix** [odoo/odoo#28552]
Impacted versions: Odoo11 Enterprise Edition

Steps to reproduce:
Go to Accounting -> Reporting
Select "Balance sheet" (or any other report) and click on Chart of Account item and then "Click" -> "General Ledger or Journal Item"

Current behavior:
Error:
Uncaught TypeError: data.CompoundContext is not a constructor

localhost/web/content/698-d92bc6b/web.assets_backend.js:2926
Traceback:
TypeError: data.CompoundContext is not a constructor
    at Class.trigger_action (localhost/web/content/698-d92bc6b/web.assets_backend.js:2926:642)
    at HTMLAnchorElement.<anonymous> (localhost/web/content/521-b22f7e1/web.assets_common.js:3923:11)
    at HTMLDivElement.dispatch (localhost/web/content/521-b22f7e1/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (localhost/web/content/521-b22f7e1/web.assets_common.js:865:173)

<img width="941" alt="1" src="https://user-images.githubusercontent.com/44358604/48304044-33d48200-e541-11e8-84c3-6929eba9e7b7.png">
<img width="944" alt="2" src="https://user-images.githubusercontent.com/44358604/48304045-346d1880-e541-11e8-8bbf-c226ccc57b96.png">
<img width="944" alt="3" src="https://user-images.githubusercontent.com/44358604/48304046-346d1880-e541-11e8-8471-8124923fdecf.png">

**Comment by Yenthe666** [comment]
Hi @asiamatrix,

Thanks a lot for your report. This was indeed broken a few weeks ago but should have been resolved in the meanwhile. I can no longer reproduce it on the latest official Odoo 11 instances either.
Please update your local Odoo instance to resolve this.

Regards,
Yenthe
