### ISSUE TITLE
Error reporting ticket in odoo.com/help

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#28593]
### Steps to reproduce:

* Login with you odoo user
* Go to odoo.com/help
* load information of you odoo enterprise bug report.

### Current behavior:

It throws an "400: Bad Request" page.
Here is a screenshot with more info about erros in the inspect console.

![image](https://user-images.githubusercontent.com/7593953/48360852-db0b0380-e67e-11e8-878c-44e1362d51df.png)

### Expected behavior:

Be able to create odoo entprise ticket

**Comment by rim-odoo** [comment]
Hello @zaoral 

I just tried to submit a ticket with your user account (kz@...), and it looked it worked.

If you still encounter this error, would you mind to have a look at the "Network" tab of your browser's console?
I would be very interested in the content of the headers + the response of the request posted to `odoo.com/help/submit`
If you have also the exact timestamp, we can check our server logs.

Thanks

**Comment by zaoral** [comment]
Hi @rim-odoo 

Thank you for your help.
I have tested today and it works I was able to create my ticket.
I will take into account the next time to have a look to the "Network" tab when reporting something similar.

Best Regards.

**Comment by mart-e** [comment]
Also, if you spend more than one hour with the open form, the CSRF token will expire and you won't be able to submit it. Not sure if the same error message but could be an explanation.

**Comment by zaoral** [comment]
> Also, if you spend more than one hour with the open form, the CSRF token will expire and you won't be able to submit it. Not sure if the same error message but could be an explanation.

Thank for the info @mart-e 
Good to know.
Not sure that this is the reason in this case, but be assured that I will take this info into account when creating new tickets
