### ISSUE TITLE
JavaScript in char field

### ISSUE THREAD

**Issue by adrianoinformatico** [odoo/odoo#28646]
Impacted versions: Odoo 10
Steps to reproduce: In Char Field insert <script>window.location.replace("http://stackoverflow.com");</script>
Current behavior: When list the model in tree the web page redirect to http://stackoverflow.com
Expected behavior: Dont execute script (sanitize field content before show it)

**Comment by mart-e** [comment]
Hello,

You don't give much information about this. Is it a problem reproducible in standard or in your custom code?

If you want to display the content of a field, you must use a `t-esc` attribute, not `t-raw`.
If it is in standard, and you think there is a security issue in Odoo, please make a [responsible disclosure report](https://www.odoo.com/security-report).

**Comment by adrianoinformatico** [comment]
I'm not sure that it should be treated as a security incident but it should be reviewed as unwanted behavior.
The issue is present in the standard version of Odoo, not in my code.
A user can affect the behavior of an entire application just by putting a JavaScript code in a field of type Char (like the one shown in the issue).
Thank you

**Comment by mart-e** [comment]
Please describe more how you achieve that (e.g. make a video maybe?). I just tested on a standard odoo 10.0 and I did not get this issue.

But, if you succeed to reproduce it on a standard Odoo, please do not describe it here, do contact the security team !
Thank you for your research.
