### ISSUE TITLE
[12] Issue with outstanding_credits_debits_widget

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28642]
Impacted versions: 12

Steps to reproduce: 

Current behavior:
![screenshot 85](https://user-images.githubusercontent.com/16624719/48425205-560d1080-e78a-11e8-9d6d-4cd6a96a9cc5.png)

Expected behavior:
![screenshot 86](https://user-images.githubusercontent.com/16624719/48425206-573e3d80-e78a-11e8-9066-f5d43d58e9cb.png)

Video/Screenshot link (optional):

**Comment by luismaring** [comment]
Small detail that improves usability

**Comment by qdp-odoo** [comment]
should have been solved, long ago, by https://github.com/odoo/odoo/commit/d395accd94b5041782bf9c24cb2a8f65061e4ade

**Comment by sswapnesh** [comment]
Yeah, Works well now. 
Thanks
