### ISSUE TITLE
[12.0] hr_timesheet: project_time_mode_id vs timesheet_encode_uom_id

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28649]
https://github.com/odoo/odoo/blob/8efa9e5fe9e8748b3a264a89416ef90c9b8d2683/addons/hr_timesheet/models/hr_timesheet.py#L130

should not over here a timesheet UoM be used? Especially if the unit_amount is specified in `timesheet_encode_uom_id` visually?

https://github.com/odoo/odoo/blob/8efa9e5fe9e8748b3a264a89416ef90c9b8d2683/addons/hr_timesheet/models/res_company.py#L33

**Comment by pedrobaeza** [comment]
@jem-odoo can you please answer this?

**Comment by jem-odoo** [comment]
Hello,

'project_time_mode_id' is the UoM used to store the timesheet amount, while 'timesheet_encode_uom_id' is used to encode it. The conversion factor of those 2 UoM will be apply but the widget on field on form, list and grid views. The purpose is purely visual, the business behind has not changed.
Every 'unit_amount' send from the webclient to the server have to be expressed in the UoM defined on 'project_time_mode_id'.
Hope it answer you question.

**Comment by alexey-pelykh** [comment]
Did I get it right that `timesheet_encode_uom_id` is used as an UoM for _rendering_ only, while `project_time_mode_id` actually specifies what is stored in `unit_amount`?

**Comment by jem-odoo** [comment]
Excatly. And the UoM conversion factor is passed to the webclient here : https://github.com/odoo/odoo/blob/12.0/addons/hr_timesheet/models/ir_http.py#L20
