### ISSUE TITLE
[12.0] EE: Current user not being applied in domain to filter My Tickets

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#28657]
Impacted versions: 12.0 EE

File: /odoo/enterprise/addons/helpdesk/controllers/portal.py
Lines: 31/32 

Current behavior: The "user" variable is unused, not inserted into the domain.

Expected behavior: Seems like it'd be used in the domain in order to filter the user's tickets, considering it's in "My Tickets".

Inserting the user variable in the domain produced the expected result:
domain = [('partner_id.id', '=', user.partner_id.id)]

**Comment by Yenthe666** [comment]
@JKE-be for you guys, there was a domain set in V11:
https://github.com/odoo/enterprise/blob/ebe6f1db1c1c40b365712dbcbe9452050a8a0b12/helpdesk/controllers/portal.py#L25-L26

Not in V12:
https://github.com/odoo/enterprise/blob/2955b8f1291ccd37828047ea0b4d90dd440f5546/helpdesk/controllers/portal.py#L31-L32

**Comment by JKE-be** [comment]
Seems by design since commit https://github.com/odoo/enterprise/commit/51a947910ce1e4211914d051e1f352613c5b63e1#diff-3b469dffd2d365f5718915a8fadc8722 

Do you report issue because you see a problem ?

**Comment by reinaldoramosarxi** [comment]
Seems to me that a page called "My Tickets" should only show the current user's tickets. If it is by design, then I don't understand why the functionality would be removed.

**Comment by JKE-be** [comment]
Or you are employee and you should use backend... And see all the tickets that you can read.
(some internal discuss to maybe redirect automaticlally employee from /my to /web)

Or you are Portal User and go to the portal /my, and you should see only your own ticket since it is limited by acl.

An employee don't need to have access in read to purchase.order for example.
While a portal user have access in read for their own record.
So /my/purchase for an employee have none sense, while a portal user will see 0 PO

**Comment by reinaldoramosarxi** [comment]
Still looks like a hastily suppressed functionality, which is why I reported it. The unused variable just didn't make any sense to me.

**Comment by JKE-be** [comment]
> Still looks like a hastily suppressed functionality, which is why I reported it.
Not really, As you can see there are a task linked to this commit.
So their are analyze, specs, tests, review and much more done... by several employee that valid this task
> The unused variable just didn't make any sense to me.
Sure, but that have no negative impact. So yes it will be removed a day when somebody will see it and update this file for another fix, but by default we avoid useless commit that don't change anything.
