### ISSUE TITLE
I don't see button order?

### ISSUE THREAD

**Issue by dinhnghia** [odoo/odoo#28664]
![desktop screenshot](https://user-images.githubusercontent.com/13850307/48478174-156ad100-e836-11e8-8359-07af2109065c.png)

**Comment by Yenthe666** [comment]
Please follow the template to log issues and give details. What version? How to reproduce? Can you reproduce on official instance?
Closing as clearly zero effort is put into this.

**Comment by dinhnghia** [comment]
Version: odoo 11
When I created the database but did not select 'Load demonstration data', I did not see the 'Order' button appear.
