### ISSUE TITLE
no i18n folder for website_google_map

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#28676]
Impacted versions:
odoo 12
Steps to reproduce:
see the code
Current behavior:
no i18n folder in the addon
not list on transifex
Expected behavior:
add one
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Actually, there has never been one so it seems. There is however not really something that should be translated, is there?
Final call to @mart-e but I don't think there is a need.

**Comment by mart-e** [comment]
Hi,

There is nothing to translate in this module so it is not published.
