### ISSUE TITLE
[12] Invalid Date when Grouped By Date in Kanban

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28696]
Impacted versions: 12

Steps to reproduce: Tested With Events 
Do not configure timezone in Preferences

Current behaviour: 
![screenshot 88](https://user-images.githubusercontent.com/16624719/48501952-701b2180-e864-11e8-898f-890b0372630d.png)

![screenshot 89](https://user-images.githubusercontent.com/16624719/48502015-993bb200-e864-11e8-9676-ed159752bbd1.png)

Expected behavior: Dates should be same

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's logical. You should have a timezone set in your user for converting properly things.

**Comment by sswapnesh** [comment]
Don't you think the behaviour should be same at both places.

**Comment by sswapnesh** [comment]
Well, I found once last week but Not able reproduce now (Maybe I am not doing same)

**Comment by pedrobaeza** [comment]
OK, if you find it, then that can be a proper issue.

**Comment by sswapnesh** [comment]
Was trying to Reproduce this (https://twitter.com/sswapnesh/status/1058066380497522689)
![](https://pbs.twimg.com/media/Dq8Box_WwAM1Bpj.jpg)
but still we can consider this due to bad timezone

**Comment by pedrobaeza** [comment]
Uhm, I see it correct...
