### ISSUE TITLE
[12] Could not delete Email

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28694]
Impacted versions: 12

Steps to reproduce: Try to Delete Email (Logged in with admin account not Superuser)

Current behavior:
![screenshot 87](https://user-images.githubusercontent.com/16624719/48500546-1d8c3600-e861-11e8-8190-6dec11ef3504.png)

Expected behavior: Able to Delete an email

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@tde-banana-odoo for you! 😉

**Comment by sswapnesh** [comment]
Ticket: 2026533

**Comment by Yenthe666** [comment]
I actually had a very similar ticket recently. It was closed and denied as you can add or modify the rule and they want to keep it like this by default. Let me know if you get the same feedback.

**Comment by sswapnesh** [comment]
Hello, It was similar answer from them for this too.

(They accepted this is not Ideal behavior but they don't want to change it)

Related PR https://github.com/odoo/odoo/pull/34348 was also closed.

**Comment by Yenthe666** [comment]
Then we should close this one. Too bad.

**Comment by sswapnesh** [comment]
@Yenthe666  They have accepted this as Bug (After long Conversation on same) and had been forwarded to bug fix team.

**Comment by Yenthe666** [comment]
Sweet! I hope it finally gets a neat fix in the security rules.

**Comment by sswapnesh** [comment]
> The ticket is a bit lower priority because it's not a blocking issue in itself, and it could be considered reasonable to require sudo rights to perform that action.

@Yenthe666  This is the latest update on the Ticket

**Comment by Yenthe666** [comment]
Hmm that's okay I guess. Let's wait and see :)

**Comment by sswapnesh** [comment]
@Yenthe666  It won't be handled in Stable version and they have submitted Internal Feedback for master. (For now, you have to do this from superuser mode :no_good_man: ) 

Cc: @odony  (To be followed up from https://github.com/odoo/odoo/pull/33084#issuecomment-488766023, Just one rare use-case of Superuser)

**Comment by Yenthe666** [comment]
Hmm the OPW is leading and as they have submitted an internal feedback I'd suggest to close this one :) Nothing to be done here.
