### ISSUE TITLE
[12] Do not load social share dialog on blank question/answer on Forum

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#28697]
Impacted versions: 12

Steps to reproduce: 
Post Empty Question
![screenshot 90](https://user-images.githubusercontent.com/16624719/48503253-9db59a00-e867-11e8-8bbc-05b46dbd4911.png)
Bad Request: Question should not be empty.
![screenshot 91](https://user-images.githubusercontent.com/16624719/48503277-b1610080-e867-11e8-94d9-e115077c9f16.png)
Go back using browser's Back button

Current behavior:

![screenshot 92](https://user-images.githubusercontent.com/16624719/48503315-cd64a200-e867-11e8-8e98-cd569841fdde.png)

Expected behavior:
Do not load social share dialog
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Ps: Wrong Error message while submitting Blank Answer (This has also same behaviour)
![screenshot 93](https://user-images.githubusercontent.com/16624719/48503432-1e749600-e868-11e8-82ee-f17595d15d19.png)
![screenshot 94](https://user-images.githubusercontent.com/16624719/48503463-36e4b080-e868-11e8-9d1d-d4a4f54c1f96.png)

Go back
![screenshot 95](https://user-images.githubusercontent.com/16624719/48503479-4106af00-e868-11e8-9d7b-83afd796dbc9.png)

**Comment by pedrobaeza** [comment]
@JKE-be are you the one handling this?

**Comment by JKE-be** [comment]
Not critical, but yes we will try to improve it in a futur version

**Comment by JKE-be** [comment]
we just merged in master the fix for bad request message.

About the 'Thanks for posting', the code is ugly and need to be rewrite...
Actually it is set in the localsessionstorage when you click on "Post", so we cannot remove it server side in case of bad request. 

After, as said previously, it not so critical ;)
