### ISSUE TITLE
[12.0] hr: should not this also check that parent is_company?

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28705]
https://github.com/odoo/odoo/blob/774991946e491ee1c7fdf772405bc0e2c111fdaa/addons/hr/models/hr.py#L289

**Comment by pedrobaeza** [comment]
The same answer as https://github.com/odoo/odoo/issues/28273#issuecomment-434218842 can apply here.

**Comment by alexey-pelykh** [comment]
Repeating myself, sorry
