### ISSUE TITLE
[11.0][12.0] Multiple Messges sent when double clicking portal send button on my project tasks, project, tickets

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#28704]
Impacted versions:
11.0 12.0
Steps to reproduce:
Span send button at portal my tasks project, tickets
Current behavior:
Many messages sent
![image](https://user-images.githubusercontent.com/10233975/48515359-1bf14c80-e826-11e8-91a8-ffdcd043ab41.png)

https://youtu.be/w-Dm4lHLXns
Expected behavior:
Only one message sent, and disable button
Video/Screenshot link (optional):

OPW 1909547

**Comment by pedrobaeza** [comment]
This has been reported previously if I don't remember bad, and there was an opened task about this, but probably won't reach stable versions.

@JKE-be can you confirm?

**Comment by hugho-ad** [comment]
@pedrobaeza 

I think you refer to this
https://github.com/odoo/odoo/issues/27233

It's the same problem but at a different place

**Comment by pedrobaeza** [comment]
Not that one. It has been reported double clicks on "website" part, like clicking on "Pay Now", on "Checkout", and so on, and this one is similar in related technology I think.

**Comment by hugho-ad** [comment]
This is the issue you are talking about 
https://github.com/odoo/odoo/issues/27976

**Comment by pedrobaeza** [comment]
Yes, that's it

**Comment by JKE-be** [comment]
I have the same bug when I let my finger on the ring, the bell ring several times.

So as discuss previously, we plan to improve it in a future version, and apply a debounce case by case for only critical button... Critical case, so not this one

**Comment by JKE-be** [comment]
If you really find it critical in your business, you can still use the http post instead of the ajax...

**Comment by nhomar** [comment]
>> So as discuss previously, we plan to improve it in a future version, and apply a debounce case by case for only critical button... Critical case, so not this one

Why?

I think this is the form that yopu put in front of your customers, if they do not feel secure you are loosing sales dude.

Even if not critical from a technical stand point it is from other PoV.

BTW I think it is simpler to solve in the core than add a new module. Don't you think?

**Comment by moylop260** [comment]
@JKE-be 
You are right using the example of a bell ring.
Maybe, you could be interested to see another point of view:
 - [The Design of Everyday Things by Don Norman](https://www.amazon.com.mx/Design-Everyday-Things-Don-Norman/dp/0465050654/ref=asc_df_0465050654/?tag=gledskshopmx-20&linkCode=df0&hvadid=295499298236&hvpos=1o1&hvnetw=g&hvrand=5408298712368296089&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1010058&hvtargid=pla-416263148589&psc=1)

I mean, a good example is the case of the elvator.
If you use an elevator from point A to go to point B then you press the button B of the elevator.

If this button doesn't give you feedback then you will press it again and again.
Now, imagine that the elevator go from point A to point B for each time that you pressed that button.

**Comment by JKE-be** [comment]
We don’t speak about a new module but about a new 
way to handle the ´click’ event.

We cannot apply this in stable version since it will make a big change and probably new bug in some case.

So we just prefer to fix the case in v12 with a manual debounce where it is critical only. 

So in the case of the lift, that can maybe take sense... in case of print report too, but a first view not especially when you want to add 1 product in your cart.

About chatter, since it is a widget that is used at many place, we will probably try to do smthing since fix one will fix all. 

But We don’t plan to handle all cases at this moment if there are not real negative impact and irreversible due to the double click

Jeremy Kersten

**Comment by nhomar** [comment]
>> About chatter, since it is a widget that is used at many place, we will probably try to do smthing since fix one will fix all.

agree (and that's the correct answer), we can wait, but do it in stable please.!

**Comment by nhomar** [comment]
>About chatter, since it is a widget that is used at many place, we will probably try to do smthing since fix one will fix all.

Perfectly understandable, let's see the result and we can test.
