### ISSUE TITLE
Trackback while using _compute_type_name method in script

### ISSUE THREAD

**Issue by rashik-bista** [odoo/odoo#28713]
Impacted versions: 12

Steps to reproduce: No need to reproduce clearly shows the issue 

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

1) V12
2) Addons/sale/models/sale.py line number 262
 
@api.multi
    @api.depends('state')
    def _compute_type_name(self):
        for record in self:
            record.type_name = _('Quotation') if self.state in ('draft', 'sent', 'cancel') else _('Sales Order')

@Yenthe666 can you check this out.
In the above method in for loop replace record with self otherwise it gives me 

ValueError: Expected singleton: sale.order(10, 1, 3, 4, 5, 6, 8, 9)

**Comment by sswapnesh** [comment]
Added PR https://github.com/odoo/odoo/pull/28742
