### ISSUE TITLE
[12 E] Partner Aged balance error on filter custom date

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#28734]
Impacted versions:
12
Steps to reproduce:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7775116/48561169-50790d00-e8e7-11e8-8b4e-eef431d717bc.gif)

Note: no alway can reproduce the error, but on 2 instance of runbot has same error
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please open the corresponding OPW ticket at odoo.com/help.
