### ISSUE TITLE
[12] Editing a Draft Invoice adds a new tax line, doubles tax

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#28756]
Impacted versions:
v12

Steps to reproduce:
- Create a new invoice in draft state, save
- Check the taxes applied, is ok
- Edit the invoice, eg change the analytic account, save
- Check taxes again

Current behavior:
- Now there are two tax lines, the tax amount has doubled
- Total amount includes 2x the applicable tax
Expected behavior:
- Proper calculation of taxes applied

**Comment by sswapnesh** [comment]
@haconsult  Works well on latest Runbot
http://400896-12-0-48a2ee.runbot17.odoo.com/web?#id=169&action=505&active_id=126&model=account.invoice&view_type=form&menu_id=324

**Comment by haconsult** [comment]
Ok, I can't reproduce either. I guess it was something in connection with the db upgrade I was working on.
Thanks anyway.
