### ISSUE TITLE
Order print on odoo 8 only print quantity without products

### ISSUE THREAD

**Issue by ali611** [odoo/odoo#2876]
when I print order 

![capture](https://cloud.githubusercontent.com/assets/9005103/4502338/e4d38f86-4ac4-11e4-8042-b5892cb80ad2.PNG)

printed like this

![imag0266](https://cloud.githubusercontent.com/assets/9005103/4502341/f99cc0c2-4ac4-11e4-95a4-15e690c7922b.jpg)

**Comment by Yenthe666** [comment]
Hi @ali611,

I can no longer produce this issue on the latest codebase from Odoo 8.
If you still face this issue please update your Odoo codebase.
Closing this issue since I can no longer reproduce this issue.

Regards,
Yenthe
