### ISSUE TITLE
[11.0, 12.0] possible ZeroDivisionError in Incoming Shipments

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#28778]
Impacted versions: looked into 11.0 and 12.0 (produced in 11.0)

Steps to reproduce:

1. Get a product into negative stock (-1)
2. Do an incoming shipment with quantity 1 of that product

Current behavior:

ZeroDivisionError

Expected behavior:

No Error and correct handling of such situations.

Related Code:

Odoo 11
https://github.com/odoo/odoo/blob/1da3ff5a0a6f46d6334f33cd876d1155e4941b36/addons/stock_account/models/stock.py#L394

Odoo 12
https://github.com/odoo/odoo/blob/7765689f63b50f6e292db704fe1182548416aa49/addons/stock_account/models/stock.py#L395

**Comment by pedrobaeza** [comment]
I don't think so, as you have this line for that case:

https://github.com/odoo/odoo/blob/1da3ff5a0a6f46d6334f33cd876d1155e4941b36/addons/stock_account/models/stock.py#L386

**Comment by intero-chz** [comment]
I had this issue on one of our customer's Odoo 11 just today. Maybe it was fixed in Odoo 12, i just compared the methods very fast.

**Comment by intero-chz** [comment]
@pedrobaeza i think you're right, i will dig deeper into it.

**Comment by fardnia** [comment]
we had same problem . we try this  

`if product_tot_qty_available == -move.product_qty:
                    new_std_price = (move._get_price_unit() * qty) / ( move.product_qty)
                else:
                    new_std_price = ((amount_unit * product_tot_qty_available) + (move._get_price_unit() * qty)) / (product_tot_qty_available + move.product_qty)
`
