### ISSUE TITLE
[12.0] Documentation request: how to trigger a refresh/reload of data in list/kanban?

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#28771]
```
def action(self):
    return { 'type': 'ir.actions.client', 'tag': 'reload' }
```
does the job for the list, yet kanban stays unaffected.

Tried to implement own action as
```
odoo.define('my_refresh', function (require) {
    "use strict";

    var core = require('web.core');
    var AbstractAction = require('web.AbstractAction');

    var MyAction = AbstractAction.extend({
        init: function(parent, action) {
            this._super(parent, action);
            this.action_manager = parent;
        },

        start: function() {
            var self = this;

            console.log('this.action_manager', this.action_manager)

            return $.when().then(function () {
                console.log('let\'s go back', self)
                self.trigger_up('history_back');
            });
        },

    });

    core.action_registry.add(
        'my_refresh',
        MyAction
    );

});
```
yet `trigger_up` doesn't do what's needed. Looked through the Odoo sources to find something similar as a reference and no luck, thus have to request for documentation on the matter

**Comment by pedrobaeza** [comment]
Questions are not usually allowed here, Alexey. I let a change that @ged-odoo answer this as indeed JS part is still not fully documented, but if he refuses, then I'll close this.

**Comment by alexey-pelykh** [comment]
I'll take my chance, since I've been all across the sources and google for entire day trying to figure that out

**Comment by Yenthe666** [comment]
I'm curious, in what case would you like to reload a kanban view?

**Comment by alexey-pelykh** [comment]
Meanwhile I'll add information (for further generations? :) )

In Odoo 10.0, in there was a `do_reload` in `addons/web_kanban/static/src/js/kanban_view.js`, that called `do_search` which actually performed a search, thus `web_auto_refresh` (https://github.com/OCA/web/pull/972) was able to work.

In Odoo 12.0 this is not the case, `do_search` is now part of `addons/web/static/src/js/views/search/search_view.js` that collects things via `build_search_data` and fires a `search` (seems like it may be triggered via `ir.actions.client` as well, with search data from `action.env`)

Btw, `reload` is available via `addons/web/static/src/js/views/basic/basic_controller.js` I think, not related to (or overridden) one found here `addons/web/static/src/js/core/misc.js`

Another candidate for workarounding the `reload` in Kanban is `set_dirty`

**Comment by alexey-pelykh** [comment]
@Yenthe666 glad you've asked! One of buttons on kanban card triggers an action that creates a new instance of a model that is being viewed right now. List shows that new item almost instantly (`reload` makes somewhat more solid, whatever that means), while kanban does nothing at all and only clicking on search button will reveal that new item

**Comment by Yenthe666** [comment]
Ahh I see 👍 I'm curious about the feedback from Gery.

**Comment by alexey-pelykh** [comment]
(investigation continues!) According to comments found in https://github.com/OCA/web/pull/972, the `reload` has not been working for Kanban in 10.0 as well, thus probably same behaviour is present in 12.0.

`reload` is implemented in `addons/web/static/src/js/views/abstract_controller.js` and it calls `update`. Update is implemented in:
 * `addons/web/static/src/js/views/abstract_controller.js`
 * `addons/web/static/src/js/views/basic/basic_controller.js`
 * `addons/web/static/src/js/views/list/list_controller.js`

In `kanban_controller`, there's no `update` function, yet there's an `_update` function that is called by `update` of `AbstractController`

Meanwhile, it seems that clicking on button on the kanban card refreshes the card only thanks to `KanbanController._onButtonClicked` that triggers `KanbanController._reloadAfterButtonClick`, that calls `self.model.get` with ID of the record.

Additionally, `KanbanController._onButtonNew` has code
```
this.do_action(this.on_create, {
    on_close: this.reload.bind(this),
    additional_context: state.context,
});
```
meaning that calling `reload` (that is called by `_onReload`) is supposed to work?

Getting back to `_onButtonClicked`, list-view seems to handle the item update in the very same manner. (making calling `{ 'type': 'ir.actions.client', 'tag': 'reload' }` explicit in case no new record was created)

**Comment by alexey-pelykh** [comment]
So, I did something, and Odoo reacted somehow:
```
return {
    'type': 'ir.actions.client',
    'tag': 'reload',
    'params': {
        'db_id': new_id,
    },
} if new_id else None
```
Triggers an entire page refresh, loosing all filters and groupings, and surely shows the newly created item in both list and kanban mode, yet a little not as expected xD

**Comment by alexey-pelykh** [comment]
In the end, seems like `ListController` is refreshing entire dataset due to way how button click is handled, where in the end
https://github.com/odoo/odoo/blob/7765689f63b50f6e292db704fe1182548416aa49/addons/web/static/src/js/views/basic/basic_controller.js#L270

and how [selectively] `KanbanController` reacts to button click:
https://github.com/odoo/odoo/blob/7765689f63b50f6e292db704fe1182548416aa49/addons/web/static/src/js/views/kanban/kanban_controller.js#L267

**Comment by Yenthe666** [comment]
Hi @alexey-pelykh,

Did you get around this? Is it solved for you?

**Comment by alexey-pelykh** [comment]
@Yenthe666 yes, though in another way: https://github.com/OCA/web/tree/12.0/web_ir_actions_act_view_reload

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!

**Comment by DevSergioDr** [comment]
> @Yenthe666 yes, though in another way: https://github.com/OCA/web/tree/12.0/web_ir_actions_act_view_reload

Hi @alexey-pelykh, thank you for information.
