### ISSUE TITLE
[12.0] gamification start challenge bug

### ISSUE THREAD

**Issue by kalway-tony** [odoo/odoo#28773]
Impacted versions:
Odoo12
Steps to reproduce:
http://400273-12-0-b60f9b.runbot17.odoo.com
create a challenge, start date = 2018-11-01   end date = 2019-01-31
click start challenge 
Current behavior:
Odoo Server Error
psycopg2.ProgrammingError: syntax error at or near "g"
LINE 6: ...         AND g.start_date = '2018-11-01'::dateAND g.end_date...
Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31125609/48667957-548e7000-eb1d-11e8-8c77-0b55a3d16d51.png)

**Comment by tivisse** [comment]
Hi @kalway-tony 

Thanks for the feedback. Unfortunately I'm not able to reproduce your issue with the information you provide. 

Could you please elaborate ? 

Thanks.

**Comment by sswapnesh** [comment]
Hello @tivisse
I am able to Reproduce same on latest Build http://406121-12-0-e942c3.runbot18.odoo.com/web?debug#id=33&action=205&model=gamification.challenge&view_type=form&menu_id=4
![screenshot](https://user-images.githubusercontent.com/16624719/49177675-d4190c00-f373-11e8-9c7a-dc9d0413f36a.png)
![screenshot](https://user-images.githubusercontent.com/16624719/49177693-de3b0a80-f373-11e8-9fc0-ba01163c23cc.png)
![screenshot](https://user-images.githubusercontent.com/16624719/49177710-ea26cc80-f373-11e8-865d-c7b906cc1bf2.png)

![screenshot](https://user-images.githubusercontent.com/16624719/49177732-f743bb80-f373-11e8-8258-12c969c0c50c.png)

**Comment by sswapnesh** [comment]
Can someone remove/add correct labels here ? (Will be easy for Reference)
