### ISSUE TITLE
[12.0] New installed website module doesn't work once the website page had been edited

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#28774]
Impacted versions:
12.0
Steps to reproduce:
Edit a website page element, such as the footer or description text on the right side in the product page.
Then install a website module such as product comparison.

Current behavior:
The new installed module won't work normally.

When editing the product page, I found in the pg database, ir_ui_view table, odoo will duplicate the line with the key 'website_sale.product' to a new one, and then generate other related template modification lines, (the inherit_id point the new line)

but after editing page, the new installed website module does not generate related line point to above edited line accordingly. The module's customization option doesn't appear in the menu item list.

Expected behavior:
Fix bug, we can install website module anytime.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you be a little more precise including which changes and detailed steps to reproduce the problem?

**Comment by jlzhou** [comment]
@pedrobaeza This issue is complicated to describe clearly, I just want to give a hint to odoo developer. 

The website 'Product' view templates will be duplicated in db to save the changes once the page element has been edited, but after this, new installed website module still inherits to the origin templates. So the new website module doesn't work.

**Comment by pedrobaeza** [comment]
Yeah, I know, but if you don't provide such exact steps, it's not reproducible and thus not fixable...

**Comment by Yenthe666** [comment]
@jlzhou perhaps you can make a video showing the issue?

**Comment by jlzhou** [comment]
@pedrobaeza I will make an exact steps description lately... in a tight schedule now, sorry.

**Comment by Yenthe666** [comment]
@jlzhou did you get around to checking this yet?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe
