### ISSUE TITLE
Project Managers can delete Stages in one project that are deleted in other projects

### ISSUE THREAD

**Issue by sseerrggii** [odoo/odoo#28811]
From: https://github.com/odoo/odoo/issues/11016#issuecomment-439534537

**Impacted versions:** Reproduced in 11.0 (Community Edition)

**Steps to reproduce:**

1. As project Manager enter in a project and delete stage that you don't need in this specific project 

![peek 19-11-2018 19-56](https://user-images.githubusercontent.com/2297137/48728451-45024a80-ec35-11e8-82f2-45dea623d90c.gif)

**Current behavior:** The stage is deleted for all projects, also is not available from global stages config

![peek 19-11-2018 20-00](https://user-images.githubusercontent.com/2297137/48728679-e7bac900-ec35-11e8-80c7-59fd0a4380d8.gif)

**Expected behavior:** Remove the stage from the current project but keep it for other projects.

**Comment by pedrobaeza** [comment]
This is the expected behavior, as the projects links the stages by a many2many. The solution is to not remove stages that way or to use independent stages for each project.

Closing this as no real issue, but expected behavior.

**Comment by bennals** [comment]
It may not be technically a bug but I think it's extremely poor design and can result in a big mess being created by a user who isn't aware of what they're doing.

**Comment by pedrobaeza** [comment]
Don't give project manager permission to that user.

**Comment by bennals** [comment]
Yes, sure, there are always work arounds, but wouldn’t it be better if that action just removed the link between that particular project and the stage, rather than delete the stage completely from the database?

**Comment by pedrobaeza** [comment]
You can consider this as a framework limitation, but no, it's not possible. If you click on remove, you are removing the record, not the link in that project.
