### ISSUE TITLE
Use by default work center view

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#28841]
Impacted versions:
Manufacturing 11.0.2.0

Steps to reproduce:
1. Open Manufacturing app.
2. Select Work orders from the dashboard.
![image](https://user-images.githubusercontent.com/40301417/48775254-30758f00-ecd5-11e8-853c-e732d70a6669.png)
3. Group by for example "Created on":
![image](https://user-images.githubusercontent.com/40301417/48775494-dfb26600-ecd5-11e8-9f7e-5f8129a5fd60.png)
4. Save current search and use this filter and view as default.
![image](https://user-images.githubusercontent.com/40301417/48775527-f22c9f80-ecd5-11e8-8fa1-254a7eb29438.png)
5. Go back to your dashboard and open again the same work center work orders view.
![image](https://user-images.githubusercontent.com/40301417/48775584-2e600000-ecd6-11e8-9dd2-5d0a52692ac4.png)

Current behavior:
Currently "Use by default" search is not applied.
![image](https://user-images.githubusercontent.com/40301417/48775616-42a3fd00-ecd6-11e8-8682-7ee2bd292cfe.png)

Expected behavior:
If I haved saved filter and I want it to be used by default, then "Use by default" saved search should be automatically applied:
![image](https://user-images.githubusercontent.com/40301417/48775659-62d3bc00-ecd6-11e8-9915-d4559b62889b.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something expected, as clicking on the button forces an specific action with a defined context, so you are not going to get any default filter. You can consider this a technical limitation.

Reference line: https://github.com/odoo/odoo/blob/8bff607f07f7515c26145c46135855329665a5a2/addons/mrp/views/mrp_workcenter_views.xml#L164

@ged-odoo do you consider here that the web client should inject that filter?
