### ISSUE TITLE
odoo.com: I am not receiving messages responses from reported tickets

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#28854]
I have reported tickets in odoo I am always checking the state of this ones when I do not receive any email response from odoo telling me that someone is working on it or that has been assigned to Technical team, etc.

Thanks to this I notice that some tickets were answered but I do not receive any news via email, normally when support team add a message to the ticket I received in mail inbox.

In this case I was lucky getting to the portal and be able to see that I actually have new messages to read. This happens to me and also to  a college last week. And example of a message that I do not receive in my mail inbox is the message sent by Oriane Malburny (oma) in ticket 1907678

I have notice that something change in the way that odoo.com portal looks last week so maybe some bug was introduced that make that the messages are not sent via email?

This happens again today with ticket 1906968. I do not receive the ticket messages, however I do receive the "Satisfaction email: Tell us how you feel about our service" message to my inbox.

![image](https://user-images.githubusercontent.com/7593953/48790941-408a7000-eccf-11e8-99d1-e7c395953e86.png)

**Comment by JKE-be** [comment]
Hi Katerine,

Please keep this channel for issue and not issue about issue ;) 

From what I see, the last answer of Oriane ask you more details about your issue 6 days ago.

So if you have already replied, please send again your answer (we don't have feedback from you), and we will be able to help you.

Best regards

**Comment by JKE-be** [comment]
Sorry didn't read all your question.

We will double check in internal, but from what I know, there are no more issues of email.

Best regards

**Comment by Yenthe666** [comment]
@jke-be I seem to have a new one since today where every response appears to come from OdooBot actually. You might want to check that too.

**Comment by zaoral** [comment]
Roget that @JKE-be

I just though that will be important to tell you about that maybe is something wrong with outcoming messages that could not been informing to your customers. 

In future.. when I notice any problem or error related to odoo.com where should be the proper channel to reported?

**Comment by JKE-be** [comment]
@zaoral 

In case of a bug of odoo.Com and not the core of odoo code, you can use the traditional "ticket" process.

If you really have some doubts that your ticket is created (error 500, ...); in this case don't hesitate to open an issue github to warn us ;)

**Comment by JKE-be** [comment]
@Yenthe666 

User with ID = 1 is called OdooBot 
You have now "2 admins", the admin bot that make automations, bypass rules, ... and the admin user.

**Comment by Yenthe666** [comment]
@JKE-be yeah I know that. Your system is doing it, not mine 😉
