### ISSUE TITLE
PDF report menu items not showing under Reporting menu in Accounting module

### ISSUE THREAD

**Issue by kbirkbr** [odoo/odoo#28861]
Impacted versions: Odoo 11 EE

Steps to reproduce:

Create a new database.
Install account_accountant module.
Current behavior:

Not appearing PDF reports under Reporting Menu in Accounting module.
Not even list out in Menu items under Settings -> Technical -> User Interface.
Have to refresh the account module to make PDF report menu visible.

Expected behavior:

Show PDF reports under Reporting Menu in Accounting module
Expected behavior:

Video/Screenshot link (optional): [Sample Video](https://drive.google.com/open?id=1DvchHBi3RVwzDvlHaEObMSuqPzV3FoAj)

**Comment by pedrobaeza** [comment]
That's something expected, as enterprise edition has other more advanced reports, so PDF reports are removed from that version.
