### ISSUE TITLE
[8.0] sales team dashboard raise  INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#2890]
odoo run on windows 7 and locale set to china, when click sales team menu item.  odoo raise internal error. 
i have traced the code, found that the time formatted as locale.
>`        section_result = [{
                          'value': 0,
                          'tooltip': (month_begin + relativedelta.relativedelta(months=-i)).strftime('%B %Y'),
                          } for i in range(self._period_number - 1, -1, -1)]`

in locale china, this should be `一月`, `二月`, and so on.
but simplejson can not decode it, then raise the error.

see another issue report #2775

**Comment by beledouxdenis** [comment]
Solved with f9b1161ea7da48690208825d7cfaf3383e7b7f9b
