### ISSUE TITLE
[8.0] after upgrade to the latest code. all form view lost data

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#2892]
the action field have set in tree view. but not set in from view.

and tree view.
![baidushurufa_2014-10-3_21-30-50](https://cloud.githubusercontent.com/assets/1404460/4506335/b65e4ef6-4b01-11e4-868f-00420d246072.png)

and form view.
![baidushurufa_2014-10-3_21-32-4](https://cloud.githubusercontent.com/assets/1404460/4506397/32719de0-4b02-11e4-9ddb-02a357b99070.png)

**Comment by Yenthe666** [comment]
Hi @jeffery9 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
