### ISSUE TITLE
[12.0] Website cart and sales not taking into account variants

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#28928]
Impacted versions: 12.0

Adding product variants to the online shopping cart doesn't add the variant itself if the attributes' "create_variants" selection is set to "no_variant", just the base product. Works on regular backoffice sale orders.

The goal would be to sell user-configured variants online without having to store each specific variant in the database.

**Comment by seb-odoo** [comment]
This is going to be fixed with #/28079 (still work in progress, hoping to merge next week).

**Comment by seb-odoo** [comment]
Btw I think you should use in your case the attribute value "custom" and not no_variant.

**Comment by seb-odoo** [comment]
The PR has been merged, hopefully this resolves your issue.
