### ISSUE TITLE
[ERROR] city is no dropdown on CRM leads

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#28930]
**Impacted versions:**
v12.0 / v 11.0

**Steps to reproduce:**
- On a full database (demo.odoo.com) Install `base_address_city`
- Change portugal to enforce cities
- Create City "Lisboa" for portugal
- Create an opportunity
- Set Portugal as the country on that opportunity (follow up tab)

**Current behavior:**
- City field is not a dropdown

**Expected behavior:**
- City field should be a drop down, also on CRM (and all other instances where a address is entered)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
`base_address_city` doesn't cover CRM. You should develop an extra module `crm_address_city`.

Closing as no issue, but missing feature. Maybe this proposed module can be added in later versions.

**Comment by blaggacao** [comment]
I don't agree with your line of argument. It's not precisely user centric. Could you reopen, please?

Please also not the difference between "Error" and "(Software)Bug".

**Comment by pedrobaeza** [comment]
I think my message is clear, and this is not going to be "fixed" in stable.

**Comment by blaggacao** [comment]
I think my message is understandable, too: Please reopen. Your acting in a rougue way, again.

Well, leave it closed, as I hate to recover from a conversation that has been slammed by your unhelpful way of communicating or dismissal of valid arguments that don't come out of your head or are not aligned with your narrowed down point of views.

It's exhausting! You should stay away from Odoo issues in the best interest of this community.

**Comment by pedrobaeza** [comment]
@blaggacao keeping this opened is not going to lead to anything, and that's why I closed it.
