### ISSUE TITLE
[12.0]Why is the route Buy set on the product by default? 

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#28937]
**Impacted versions:**
12

**Steps to reproduce:**
When odoo is used in a manufacturing enterprise, the most of the products we created is manufactured by this enterprise. After install the purchase module, the route Buy is selected by default when we create a product, we should unselected it manually.If we create a product in bom line, then the Buy route is set on the product, we should open the product , unselected it manually.

**Current behavior:**

**Expected behavior:**
Do not set the route Buy on the product by default.

**Video/Screenshot link (optional):**
<img width="710" alt="wx20181122-141246 2x" src="https://user-images.githubusercontent.com/5561864/48884737-ba059800-ee60-11e8-9c11-cb2b614216a3.png">

<img width="1312" alt="wx20181122-142406 2x" src="https://user-images.githubusercontent.com/5561864/48885181-4f555c00-ee62-11e8-8ec3-ede0f40b944f.png">

**Comment by pedrobaeza** [comment]
This is the best default. If you don't want it, just set another default to "Manufacture". That can be done through debug mode.

Closing as no issue.

**Comment by tanghulu0608** [comment]
@pedrobaeza  OK.Thank you.

**Comment by krister-ts** [comment]
@pedrobaeza I cannot see any Route field in the set defaults.

@tanghulu0608 were you able to set "Manufacture" route as default?

**Comment by krister-ts** [comment]
I figured out that I could create User-Defined Default for `route_ids`. I got the values from external identifiers `stock.route_warehouse0_mto` and `purchase_stock.route_warehouse0_buy`. Is there a way to use the identifiers instead of the the values?

![untitled](https://user-images.githubusercontent.com/44512474/49113953-c6686700-f24b-11e8-822f-c147a4557655.png)

**Comment by pedrobaeza** [comment]
Not on the DB, but possible on a custom module.

**Comment by krister-ts** [comment]
How does one go about changing the default (without custom module)? There should be someway to find this field in the debug mode "set defaults".

**Comment by pedrobaeza** [comment]
Well, yes, look for the ID of the route... just look for example on the URL when viewing it and you'll see its ID encoded there.

**Comment by krister-ts** [comment]
I guess the IDs are not changing often (or at all).

**Comment by pedrobaeza** [comment]
No, they don't change in your DB, unless you remove them. But each DB might have different IDs depending on the record insertion order.
