### ISSUE TITLE
[12.0] The ecommerce product image can't be magnifying when has extra images.

### ISSUE THREAD

**Issue by CakJuice** [odoo/odoo#28940]
Impacted versions: 12

Steps to reproduce: Install ecommerce & sale module, create a product, add an image then add extra images.

Current behavior: The image product can be magnifying when the product only has one image. And can't be magnifying when the product has extra images.

Expected behavior: The image product should be can magnifying when the product has extra images.

![odoo_issue](https://user-images.githubusercontent.com/7473166/48930710-ebe03280-ef24-11e8-986a-9a929f4234ee.gif)

**Comment by CakJuice** [comment]
@pedrobaeza I have added gif video

**Comment by pedrobaeza** [comment]
Thanks for the extra video. Seems legit. @JKE-be can you take a look and assign?

**Comment by JKE-be** [comment]
we are working on a big fix for product configurator that will fix this too.
Hope to have it merged next week

**Comment by seb-odoo** [comment]
For reference #28079 if you want to test the commit "[FIX] website_sale: fix product variant image zoom".

Keep in mind the PR is still a work in progress.

**Comment by seb-odoo** [comment]
The PR has been merged, hopefully this resolves your issue.

**Comment by CakJuice** [comment]
@seb-odoo after update with a new version, this issue still appears to me

**Comment by seb-odoo** [comment]
@CakJuice I can have a look, could you describe me how to reproduce the issue on runbot?

**Comment by CakJuice** [comment]
Sorry @seb-odoo , I just found out that only large size images can be magnified. Thank you.
