### ISSUE TITLE
[8.0] eCommerce: Public Pricelist Item: product.product in case of a template without variant is not applied in webshop

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#2900]
## Impacted versions:
8.0 and above

## Steps to reproduce:
* Create a product with only one variant (actually just create the product)
* Change the public price list version item 1 which is pointing to a product.template. Remove the template pointer and add your newly created product in the product.product field to match (20% discount)

## Current behavior:
* It does only show the discount in front end shop if you put the created product in the product.template BUT not if you try to assign it via product.product.

## Expected behavior:
* Price list retrieval should also match for the product.product (=single variant)

**Comment by wtaferner** [comment]
What is still not working for a single product/variant (respectively template) are
* Product Overview
* Shopping cart representation (initial request) - on update it does calculate the correct price (ajax request which is doing that)

**Comment by mart-e** [comment]
Indeed, there was a second bug in pricelist. It has been fixed at 9e1100ae2f014ad82886fbb98d2e6deb4f6df4cd.
It should work now.

**Comment by wtaferner** [comment]
Now it works as expected. Thank you.
