### ISSUE TITLE
Internal transfers between different warehouses treated like one transfer only

### ISSUE THREAD

**Issue by infoitservit** [odoo/odoo#29008]
Impacted versions: odoo11

Steps to reproduce: 1main warehouse, 2 sub warehouses that will be refurnished by the main one. Set everything as per documentation: setting with multiple warehouse and locations. Create reorder rules for a product to be procured to the 2 sub warehouses and run scheduler.

Current behavior: one delivery order only.

Expected behavior:I would expect 2 delivery orders to the 2 sub warehouses and 2 receipts, one for each subwarehouse

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please specify what is "Set everything as per documentation"? Ideally, make a video from 
runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin) with all the steps needed.

**Comment by infoitservit** [comment]
Ok, i do a video.
Please, check configurations and reordering rules, then at 1:28, after scheduler trigger, take a look at the delivery orders. I would expect 2 delivery orders with a partner indication (warehouse A and warehouse B). I know that the problem it's related to procurement routes, the question is which route should i use and why odoo doesn't "split" routes automatically.

To be definitely clear, i would like to treat this transfers as "inter company warehouse transfers", and the main warehouse responsible should know the destination of any transfer. If you look at the video, at 1:28, you will find that there is no indication about the destination of that delivery.
[video.zip](https://github.com/odoo/odoo/files/2616070/video.zip)

**Comment by wtaferner** [comment]
@infoitservit 
It is not supported to transfer between two warehouses like that. You must do the transfer through the transit location afaik. So, internal transfer picking type should be made only per warehouse not cross warehouses.

Not sure if there is already an UI to make inter warehouse transfers possible without creating own rules making this possible for you...it is not as easy as doing a simple operation type  or create a transfer and configure something which is not supported.

Murphy is nobodies friend :wink:

**Comment by infoitservit** [comment]
What if i create n transit locations for n sub warehouse? Cause the problem seems to be that the transit location is one only and the sub warehouses are 2. So i could make these 2 routes

WH Main -> Transit Location to WH A (Delivery Order to A)
From Transit Location WH A to WH A/Stock

WH Main -> Transit Location to WH B (Delivery Order to B)
From Transit Location WH B to WH B/Stock

The main point is: if I have a main warehouse and 4 point of sale, and any point of sale has its own warehouse and warehouse/stock-location, how can i auto refurbish those 4 point of sales using reordering rules? It seems that everything could be easily done, but maybe i miss a step in routes or something similar.

**Comment by infoitservit** [comment]
Am I asking something impossible?

**Comment by infoitservit** [comment]
Ok, i think we should close this, but the question is still open: how to replenish x point of sales with procurement rules using at the same time pick+pack+ship on delivery procedure, getting each point of sale treated separately with specific documents?

**Comment by pedrobaeza** [comment]
Please do it on the forums instead.

Closing this.
