### ISSUE TITLE
[11.0] Taxes missing in expense by mail

### ISSUE THREAD

**Issue by Vartkat** [odoo/odoo#29014]
Impacted versions: 11 CE (hr_expense module)

Steps to reproduce:
- Expense configuration-> with email
- Create a (template) product with account and taxes and an internal short code for email
- Send email to mail address with object = [code] blabla 123.45

Current behavior:
Expense is well created when mail is received, amount is the right amount, account is the account of the template product, **but taxes are not there **
Expected behavior:

Taxes should be the ones setup in the template product.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I'm not able to reproduce this problem in my side. Can you please try on runbot and specify all the steps to reproduce it?

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no extra information in a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe
