### ISSUE TITLE
Optimization problem with a lot of users / groups

### ISSUE THREAD

**Issue by etobella** [odoo/odoo#29013]
Impacted versions: 11.0

Steps to reproduce: Create a lot of groups and ir.module.categories. Access Users and it will take a lot of time to open it

Current behavior: It takes a lot of time (On my case, 48 seconds for 180 groups and 115 categories)

Expected behavior: Be fast

The problem seems related to https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_users.py#L824 It takes too much time. It could be solved by creating two new fields (stored and computed folloowing the logic of the function), one on ir.module.category and another in res.groups in order to solve this performance issue. I made the changes locally and it become much more faster. 

I can make a PR on 11.0 if you think that it can be accepted.

**Comment by pedrobaeza** [comment]
@etobella this won't be accepted in any stable version due to stability policy: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

Maybe on master, a rework can be done for improving performance with that kind of techniques.

**Comment by Yenthe666** [comment]
Indeed, this can't be done in 11.0 A PR against the master version is always welcome, then somebody can look at it.

**Comment by etobella** [comment]
Ok! If you think that it is not critical to make odoo unusable (a process cannot take more than 60 seconds if you have workers, and 48 seconds is not far), you can keep these way. You should think that if you take more than 60 seconds, you are unable to create new users or edit the current ones.

I will make a commit for my branch and solve it in my system. Right now, I cannot make the improvement on master.

**Comment by Yenthe666** [comment]
@etobella,

Just so you know. @pedrobaeza and me are both volunteers and do not even work for Odoo S.A. Whenever we hit a problem or something we can improve we always make a PR to fix it in the core instead of complaining.

**Comment by etobella** [comment]
It is not complaining, I was prepared to make the commit on 11.0 and I already did it, If Odoo does not care about performance issue, then I will fix it on my system.
What I was doing was warning that this performance issue can give major problems on big installations.

**Comment by pedrobaeza** [comment]
@etobella you have to understand that some things simply can't be done on a stable version, or they will compromise all the users of this version. One of them is to change DB schema (adding, removing or changing files). As we consider this a long run, we prefer to have this fixed on latest version and we will enjoy it very soon. Meanwhile, a hot patch on your fork (not very recommended), or a community module are the typical solution.

**Comment by etobella** [comment]
As I said, this is not a problem of enjoy. This is related to make your system unusable.

**Comment by pedrobaeza** [comment]
Well, your system, not all the systems ;)

**Comment by moylop260** [comment]
Could you attach the patch, please?

**Comment by etobella** [comment]
https://github.com/etobella/odoo/commit/1ba3de59a78d22c870b7dde353cae236efe0fe2f

**Comment by moylop260** [comment]
Hi @etobella 
Maybe using lru-cache could be a good approach in order to avoid the stable policies adding new fields.

If you use a lru-cache you will have a similar effect but without a new field.
