### ISSUE TITLE
CRM Meeting Count is wrong..!!

### ISSUE THREAD

**Issue by muhsinalungal** [odoo/odoo#29018]
Impacted versions: 11.0, 12.0 (all versions)

Steps to reproduce: goto CRM -> create new -> schedule a meeting -> go for edit from the calendar screen (not create).
go back to the CRM screen. check the meeting count (it is wrong)

Current behavior: Meeting count is only counted when it created immediately only. 

Expected behavior: it should be counted in both cases (quick create and edit then create)

Video/Screenshot link (optional):
https://vimeo.com/user92141385/review/302779042/049866de46

**Comment by pedrobaeza** [comment]
Video link is incorrect. Can you please fix it?

**Comment by pedrobaeza** [comment]
You have put an internal link that is only visible by you:

![seleccion_034](https://user-images.githubusercontent.com/7165771/49005106-300e4580-f166-11e8-9f42-f8bed6cf5cb1.png)

**Comment by muhsinalungal** [comment]
[crm_bug-2018-11-26_13.03.55.zip](https://github.com/odoo/odoo/files/2614808/crm_bug-2018-11-26_13.03.55.zip)
please check the above video.

**Comment by pedrobaeza** [comment]
But that number is a field that you have added via some custom code, so the problem should be there, not on Odoo.

Closing as no Odoo issue, but custom code.

**Comment by muhsinalungal** [comment]
> But that number is a field that you have added via some custom code, so the problem should be there, not on Odoo.
> 
> Closing as no Odoo issue, but custom code.

Noooooooooooo... Please man, I added that field in view to show for you people. please try to reproduce the issue...
Its a bug I am 150% sure. please check it again

**Comment by pedrobaeza** [comment]
But why don't you reproduce it in normal conditions? The field is shown in smart-button on opportunities. Try there. Any way, on some occasions, you have to refresh your page for having updated info.

**Comment by muhsinalungal** [comment]
> But why don't you reproduce it in normal conditions? The field is shown in smart-button on opportunities. Try there. Any way, on some occasions, you have to refresh your page for having updated info.

Ok, will you please accept if I am reproduce it in smart button.?
and one more thing, I have already reloaded the page..

**Comment by muhsinalungal** [comment]
Please check the below video, the issue is reproduced from opportunity screen .
[crm_bug-2018-11-26_19.37.35.zip](https://github.com/odoo/odoo/files/2615870/crm_bug-2018-11-26_19.37.35.zip)

for kind attention: I already specified how to reproduce the bug in " steps to reproduce". please read the issue completely at least for once.

**Comment by Yenthe666** [comment]
@muhsinalungal can you please paste the code here for the smart button? I'm happy to give it a try for you. I assume you used the already existing field `activity_ids` for the smart button?

**Comment by muhsinalungal** [comment]
> @muhsinalungal can you please paste the code here for the smart button? I'm happy to give it a try for you. I assume you used the already existing field `activity_ids` for the smart button?

Actually I didn't Added even a single line of code. the bug I have noted is from the core CRM module and the video is taken from the odoo runbot.. the smart button already exist its not 'activity_ids', its "meeting_count"

**Comment by pedrobaeza** [comment]
@muhsinalungal thanks for the video and the patience. Now it's much more clear the problem. It seems a problem of context propagation of the default value that links to the opportunity, so I'm going to tag it for framework team.

**Comment by muhsinalungal** [comment]
@pedrobaeza You got it. Thanks, man..

**Comment by NathanQj** [comment]
Any news on that issue?

**Comment by mart-e** [comment]
Hi there,

It was fixed in 12.0 at 59d154dcc1524c8f08c6a1e7aee18c722ab2e0ad
Thanks for the report
