### ISSUE TITLE
[11.0] many2one no_quick_create not working completely

### ISSUE THREAD

**Issue by dz-hurricane** [odoo/odoo#29042]
**Impacted versions:** 11.0

**Steps to reproduce:**  in xml , add  attribute option={'no_quick_create': True} to a many2one field to disable quick creating option

**Current behavior:** This option disable create option but clicking outside the field will popup a window with 3 buttons 'Create' , 'Create and Edit' , Cancel, so the 'Create' button will enable quick creating.

**Expected behavior:** Disable the Create Button from popup window

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Same in v12 too.
Adding Screenshot for Reference.
In `account.invoice_form` `no_quick_create: True` is added for `partner_id`
![screenshot 100](https://user-images.githubusercontent.com/16624719/49100292-96e04b80-f299-11e8-910a-39203eb08855.png)

Click outside
![screenshot](https://user-images.githubusercontent.com/16624719/49100319-a9f31b80-f299-11e8-9c3f-6286766abf38.png)
This should consider the field's Option

**Comment by dz-hurricane** [comment]
The workaround for this is to override the name_create method to deny quick name creation.

**Comment by yusraalroom** [comment]
type option={'no_create': True}

**Comment by pedrobaeza** [comment]
@dz-hurricane did you try the option specified by @yusraalroom ?

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe

**Comment by Jerther** [comment]
The `no_create` option also removes the "Create and edit" item in the dropdown, but there is already the `no_create_edit` option for that.

The goal is, at least for my use case, to allow creation but also force the user into a form view with required fields, which are marked required in the view only.

**Comment by JheffSan** [comment]
Hi there!

I have the same issue. Can you please help me how to remove the create popup and shows create and edit option only?
