### ISSUE TITLE
[12.0] Uncaught TypeError: Cannot read property 'isPassword' of undefined

### ISSUE THREAD

**Issue by chowderpally** [odoo/odoo#29051]
Impacted versions: 12.0

Steps to reproduce: activate developer mode, go to customers, choose some country in the address bar, save it. Now, go to developer options/tools drop down and you see this error.

Current behavior:
![image](https://user-images.githubusercontent.com/24877539/49064254-57d1dc00-f240-11e8-8876-16233e06849f.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/24877539/49064284-77690480-f240-11e8-83f4-7d1ef1146bb4.png)

**Comment by Yenthe666** [comment]
Hi @chowderpally,

Thanks for your report!
I don't seem to be able to reproduce it on the latest 12.0. Can you reproduce it on an official runbot at runbot.odoo.com? If so, can you make a small recording please?

Regards,
Yenthe

**Comment by chowderpally** [comment]
Thanks, @Yenthe666 I see that the latest build that doesn't exist. 
doing `git pull origin 12.0` should help me fix this bug right? Or do I need to make any changes post getting the latest build? Help appreciated. Thanks again! you are always helpful.

**Comment by Yenthe666** [comment]
You're welcome! Indeed pull the latest code and then restart your Odoo service, that should be enough to fix your issue. :)

**Comment by datenpol** [comment]
We are using Odoo.sh with version 12E and we still have this issue.

Reproduce:
- In a Project Task in Debugmodus click on "Set Default value" and then the error appears:

![image](https://user-images.githubusercontent.com/47249280/56417630-cc132780-6294-11e9-99ab-e43c5dd4293c.png)

It is curious, that an same tasks the error appears and in some it does not.
