### ISSUE TITLE
Reserving zero quantities on a delivery order

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#29068]
Impacted versions: 10.0

Steps to reproduce: If You set the quantity of an item to 0 on a delivery order.

Current behavior: EM pops on reserving: "You can not reserve a negative quantity or a negative quant."

Expected behavior: Zero is not a negative number!! Odoo shall skip the items, just like when You hit the "Force Availability" button.

Video/Screenshot link (optional): https://drive.google.com/file/d/1TDm5Z-kiJ2nwM3T6-YUE483WEVXeyI4g/view?usp=sharing

**Comment by pedrobaeza** [comment]
Well, it's not negative, so maybe the message is not the more suitable, but the goal is the same: there's no sense on putting a zero quantity delivery. Why do you use that?

**Comment by nagybal** [comment]
Because Odoo does not allow me to delete a line item from a confirmed delivery order. I would like to replace it with a different, better, upgraded, quality.

**Comment by pedrobaeza** [comment]
For that, you have to say no when the backorder is ready. It's true that you have to validate the existing transfer, but for v10 there's no better solution. On v11, this is already solved.

**Comment by nagybal** [comment]
And how will the warehouse know that they are not supposed to load the original (cheaper) version of the product?

Where can I set this rule to bigger than zero as a workaround?

**Comment by pedrobaeza** [comment]
You should change code for that.

**Comment by nagybal** [comment]
Dear All!

Where can I change the minimum item quantity on a delivery order from
<= 0 
to
< 0
?

**Comment by Yenthe666** [comment]
Dear @nagybal ,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe

**Comment by Fahadrm** [comment]
Force Availability button in Delivery Order not available odoo 13
