### ISSUE TITLE
[8.0] AssertionError: Implicit/Canonical naming of m2m relationship table is not possible when source and destination models are the same

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#2909]
With latest revision, I am getting

```
AssertionError: Implicit/Canonical naming of m2m relationship table is not possible when source and destination models are the same
```

When the service is started and is loading fields.  It is triggered on res.groups, for field trans_implied_ids, but there is no recent change related to them.

Seems related to changes on the way modules are loaded/updated...

Regards,
-Mario

**Comment by Yenthe666** [comment]
Hi @TheCloneMaster ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by maicoldlb** [comment]
@TheCloneMaster , you have to add **relation, column1 and column2** parameters in order to fix this bug.
Best regards
