### ISSUE TITLE
incl. archived string

### ISSUE THREAD

**Issue by anandkansagra** [odoo/odoo#29090]
Impacted versions:
12.0

Steps to reproduce:
1) Go to apps **(which are installed in your system)**
2) Go to `Module Info`.
3) Click on `Uninstall` button. At that time, there seems a Popup
4) In the Popup, there is a list view of `The following documents will be permanently lost` which contains two column like `Document` and `Count (incl. archived)`
5) I think the string of `Count (incl. archived)` should be in `CamelCase` like `Count (Incl. Archived)`

Current behavior:
String:- `Count (incl. archived)`

Expected behavior:
String:- `Count (Incl. Archived)`

Video/Screenshot link (optional):
![3](https://user-images.githubusercontent.com/45279628/49131448-37685700-f2fe-11e8-94c0-69bc1accb411.png)

**Comment by Yenthe666** [comment]
Hi,

Closing for the following reasons:
- Just an improvement
- You already made a PR (https://github.com/odoo/odoo/pull/29092) so there is no reason to keep an issue open.

I don't see much benefit / profit in it though. Halfway a sentence you don't add a capital on a word either, do you? I personally don't get it but that is just my five cents :)
Somebody from Odoo will check the PR at some point and will either approve or decline.
