### ISSUE TITLE
[11.0] base: upgrading module is not updating views

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#29102]
### Impacted versions:
11.0

### Steps to reproduce:
1- Change a view in a custom module (or update odoo with a new view change in the core)
2- Upgrade the module, or do a `-u all`

### Current behavior:
Views are not being updated, nor being recreated (if deleted)

### Expected behavior:
Update the view with new changes or recreate the view if deleted.

**NOTE**
This is very odd and it's being very hard to find the root cause as there's no error shown on the upgrades in the log. Is there something 'phishy' that could be causing this kind of behavior without showing a Warning or error?

**Comment by pedrobaeza** [comment]
Well, without a explicit example this can't be traceable, but I can assure you that this doesn't happen, unless any other error involved or if the record is marked as noupdate="1".

**Comment by Yenthe666** [comment]
I honestly didn't have this yet either and I update Odoo's regularly. Perhaps you have some views marked as noupdate as Pedro mentioned? Can you find a reproducable way?

**Comment by gustavovalverde** [comment]
I'll do my homework and test with a clean install. Remove an inherited view and then upgrade. I'll close this so it does not generate noise while I test this.

**Comment by Yenthe666** [comment]
Thanks!
