### ISSUE TITLE
[10.0] Product Variants cost price reverting

### ISSUE THREAD

**Issue by jayo2005** [odoo/odoo#29114]
Impacted versions:10

Steps to reproduce: Create Product Variant and try set cost price

Current behavior: cost price defaults back to 0.00

Expected behavior: Cost price is applied to variants

Video/Screenshot link (optional):
I am using product variants in Odoo 10. When i set cost price on main product it reverts back to €0.00. I though default behavior on variants was the cost was same on all variants taken from main product. I've tried on two different instances of Odoo and I have to set cost price individually for each variant. Can someone clarify if this is default behavior

**Comment by pedrobaeza** [comment]
If you have several variants, you have to set the cost price on each variant. This is done for reducing chances of massive changing a cost price.

Closing as no issue, but design decision.

**Comment by thsdrouot** [comment]
I reopen the discussion because a lot of Odoo users tell me that it is not so clever as design decision. It would be very great to have an option in "standard price valuation" to change the behavior. Is it maybe already in the roadmap ?
