### ISSUE TITLE
[wish] HR attendance worked_hours_compute need to concern Work Schedule Rule

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#2911]
those company such as manufacture there have work schedule rule, the attendance module, need to concern the rule set.

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
