### ISSUE TITLE
[12.0] Don't allow to add unavailable product to Cart

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29112]
Impacted versions: 12.0

Steps to reproduce:  Reproduced on http://406121-12-0-e942c3.runbot18.odoo.com/shop/product/customizable-desk-9

Current behavior: It allows you to add unavailable optional Product to cart
![ss](https://user-images.githubusercontent.com/16624719/49172106-20f5e600-f366-11e8-8843-8b4a64065c89.png)
![screenshassasaot](https://user-images.githubusercontent.com/16624719/49172107-218e7c80-f366-11e8-8ac6-fdf06467934e.png)

Expected behavior: Do not allow to add Product

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Should be fixed by https://github.com/odoo/odoo/pull/28079 as soon as it has been merged.
Hope to merge it next week.

**Comment by seb-odoo** [comment]
The PR has been merged, hopefully this resolves your issue.
