### ISSUE TITLE
[11.0/12.0 ] Could not create Customer/Vendor Receipts without Product (account) in lines

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29118]
Impacted versions: 11/12

Steps to reproduce: Create Customer or Vendor Receipts with selecting Product (Product is not required)

Current behavior: On Saving record
![screenshot](https://user-images.githubusercontent.com/16624719/49175509-bdbc8180-f36e-11e8-9db7-dcb9f1098108.png)

Expected behavior: Account should be required (and visible on view).

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Edit: May be I am missing something or just bad configuration here as this works well If user is added to Account group `account.group_account_user` (Show Full Accounting Features) 
![screenshot](https://user-images.githubusercontent.com/16624719/49175986-d4170d00-f36f-11e8-935a-7e3cde98e291.png)

**Comment by pedrobaeza** [comment]
Yeah, the product is not required, but you should put an account then, and if you don't have full accounting group, you won't see that field, so it's a dead end, as you can't put a required condition on the product based on that group.

Any way, we can consider this as a requirement that if you don't put product, you need the accounting features, so closing as won't fix, but not special problem. Maybe one day ORM is improved to allow that condition on the `attrs` option of the field (or any other option) and it would be possible.

**Comment by sswapnesh** [comment]
But still its designing bug, How can accounting user (Without Full features access) can create receipt?

**Comment by pedrobaeza** [comment]
It can create receipts putting the product, so no special problem.
