### ISSUE TITLE
[wishlist] web: update font awesome from 4.7.0 to 5.5.0

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#29117]
Impacted versions: All (to be done in masters)

Current behavior: Font Awesome 4.7.0 is available in Odoo (https://github.com/odoo/odoo/blob/12.0/addons/web/static/lib/fontawesome/css/font-awesome.css)

Expected behavior: Font Awesome 5.5.0 is available in Odoo 13 

Video/Screenshot link (optional):

**Comment by tanghulu0608** [comment]
I like Font Awesome 5.5.0 too

**Comment by Yenthe666** [comment]
It looks like we'll get the request in the upcoming V13!
Font Awesome 5.10.1 will be integrated into Odoo 13.
PR: https://github.com/odoo/odoo/pull/35826
