### ISSUE TITLE
[11/12] Could not set Unit price to Zero in Sales Receipt

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29119]
Impacted versions: 11/12 CE

Steps to reproduce: Create Receipt --> Add New Line --> Select Product --> Change Price to Zero

Current behavior: Onchange set the unit price again

Expected behavior: It should stay Zero

Video/Screenshot link (optional):

![peek 2018-11-29 00-54](https://user-images.githubusercontent.com/16624719/49176678-5c49e200-f371-11e8-83df-16f4f32a816e.gif)

**Comment by pedrobaeza** [comment]
This is done on purpose. If price is 0, it's reset to product price, as there's not much sense in adding a 0 line. Why do you want to put 0 there?

**Comment by sswapnesh** [comment]
It should like Invoicing where it is allowed to add 0 in line. (When it's free product)

**Comment by celm1990** [comment]
> It should like Invoicing where it is allowed to add 0 in line. (When it's free product)

@sswapnesh When product is free must be set discount 100%, is better

**Comment by william-andre** [comment]
You can also put the price at 0 in the DB by editing/creating the article if the product is really free and it is not a discount.

**Comment by sswapnesh** [comment]
Yes, But still its a patch not a solution.

**Comment by william-andre** [comment]
It is the case since v9 c04065abd8f62c9a211c8fa824f5eecf68e61b73 and it might be a side effect of https://github.com/odoo/odoo/blob/d76182c58270a3326ff71ae0e63928b7335f1ed5/addons/account_voucher/models/account_voucher.py#L471 and all other similar lines to evaluate 0.0 as False.
@qdp-odoo should I patch this or was it the intended behaviour?

**Comment by qdp-odoo** [comment]
I don't think it's necessary to patch anything: the issue isn't that annoying and there are workarounds (100% discount or changing the unit price of the product).

So I wouldn't consider that as a bug. 
Thanks for your contribution, anyway

**Comment by sswapnesh** [comment]
Hello @qdp-odoo 

IMO both are workarounds looks patch not valid solution.

**discount** - Enabling discount just to make Price Zero doesn't seems good solution
**changing the unit price of the product** - No one accepts this for real products, Make price Zero --> Create Receipt With Zero Price--> Set Original Price on Product again

Final decision is up to you.
Thanks

**Comment by pedrobaeza** [comment]
@sswapnesh this is a receipt, so no legal obligation of anything, and more for this corner case...

**Comment by qdp-odoo** [comment]
ok, I heard you: let's report that to the product owners team so that we can improve this in master for a next version. 

@apr-odoo can you create a task for that in the pipe?

thanks

**Comment by sswapnesh** [comment]
Thanks @qdp-odoo
