### ISSUE TITLE
Odoo Stores all SMTP as well as IMAP passwords in Postgres in plain text. 

### ISSUE THREAD

**Issue by tonybenoy** [odoo/odoo#29127]
Impacted versions:
All

Steps to reproduce:
 select * from ir_mail_server;

Current behavior:
Passwords visible as plaintext under smtp_pass column

Expected behavior:
Password should be hashed and stored in the database to prevent a security risk.

**Comment by Yenthe666** [comment]
Hi,

Yes, this is in fact with all password fields by design. You could write a module to hash/obfuscate all passwords before storing I guess.
If you'd like to talk/discuss about this I'd advice you to do it through the official security channel (see https://www.odoo.com/nl_NL/security-report)
