### ISSUE TITLE
Issue with adding images to products #20655

### ISSUE THREAD

**Issue by dennisclevo** [odoo/odoo#29123]
I had the same issue with images on my local 10 CE Odoo version. I think it started after installing a new module (and of course i do not remember which module it was...)

**Comment by Yenthe666** [comment]
@pedrobaeza he is referring to https://github.com/odoo/odoo/issues/20655 (which was closed by me).
We really need reproducable ways though and as you already stated it happened after you've installed a new module it means it is not an issue in the Odoo core but in a custom app probably.
Don't hesitate to add reproducable steps if you can reproduce it on a clean Odoo with only official code.

**Comment by dennisclevo** [comment]
Thank you , I had recoverd this trouble.

Pedro M. Baeza <notifications@github.com> 於 2018年11月29日 週四 上午9:26寫道：
