### ISSUE TITLE
[8.0] POS: Fiscal Position only partially applied (Set Customer/Invoice)

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#2912]
## Impacted versions:
8.0 and above

## Steps to reproduce:
* Add a tax which has a fiscal mapping to a POS product
* Open a POS session
* Choose the product and set a customer with a fiscal position
* Pay by invoice

## Current behavior:
* Account fiscal position mapping is correct
* Tax fiscal position mapping is skipped and not applied

## Expected behavior:
* Tax fiscal position mapping should work too

Related invoice (from a test on runbot latest 8.0)
![pos-tax-fisscal-position](https://cloud.githubusercontent.com/assets/362478/4517854/486d6d6a-4c5e-11e4-9536-4f8bf146a601.jpg)

**Comment by mylbco** [comment]
@fvdsn any progress on this ?

**Comment by wtaferner** [comment]
Closed with cec7a02.
