### ISSUE TITLE
Blog 'select to comment' not working

### ISSUE THREAD

**Issue by wakiem** [odoo/odoo#29148]
Impacted versions: 11.0, 12.0

Current behavior: The select to comment function is not working. The selected text is not added in the comment box.

Expected behavior: The selected text should be added in the comment box.

File `odoo/addons/website_blog/static/src/js/contentshare.js` has the code:
`$(".o_website_chatter_form textarea").val('"' + selected_text + '" ').focus();`

`.o_website_chatter_form` is last used in Odoo 10.0, in file `odoo/addons/website_mail/views/website_mail_templates.xml`

But seems to be replaced in Odoo 11.0 by `o_portal_chatter_composer_form` in file `odoo/addons/portal/static/src/xml/portal_chatter.xml`

**Comment by JKE-be** [comment]
Thanks for the reporting, it has been fixed!
