### ISSUE TITLE
[11] Qweb Report: Record does not exist or has been deleted. 

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#29154]
Impacted versions: 11

Steps to reproduce:
Create a custom module just to add a qweb report (in my case I tested account.invoice, res.partner, res.users)
Here is my code:
```
<odoo>
    <data>
        <template id="my_module.other_report_template">
            <t t-call="web.html_container">
                <t t-foreach="docs" t-as="o">
                    <t t-call="web.external_layout">
                        <div class="page">
                            This is a test report
                        </div>
                    </t>
                </t>
            </t>
        </template>

        <report
                id="other_report"
                model="account.invoice"
                string="Ohter Report"
                report_type="qweb-pdf"
                name="my_module.other_report_template"
                file="my_module.other_report_template"/>
    </data>
</odoo>
```

Current behavior:
When I click on Ohter Report under print I get the following error:
`Record does not exist or has been deleted`
Expected behavior:
Print the report

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question on your custom code. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by guidev224** [comment]
@pedrobaeza 

1. I think the main issue is not my custom code because there is nothing specific to my code
2. There is no custom code in the account.invoice model, I mean didn't inherit it from python side
3. There are plenty issues related to custom code here [like this one](https://github.com/odoo/odoo/issues/24927)
