### ISSUE TITLE
search_default_internal_loc in context should be domain,  in quant action

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#29152]
https://github.com/odoo/odoo/blob/1868713dbd07e0b518f91dffe73e62d85e6ab9a6/addons/stock/views/stock_quant_views.xml#L120

Scenario is User want to see the quantity/cost on hand, means, in internal location at specific date. 

Can you imagine any reason they remove the topright filter ? see qty/cost in virtual location will never contribute value to end user, agree ?

so my suggestion is convert the filter to domain, so that fewer data considered and user never bother by the default filter.

**Comment by sle-odoo** [comment]
Hi,
This should be definitely fixed by 1ae66862d5570ebdb97ba0301ff591c27b969254

Thanks
