### ISSUE TITLE
Automated action - Odoo 10

### ISSUE THREAD

**Issue by Aeriah** [odoo/odoo#29165]
Hello,

**Impacted versions:**
Odoo 10

**Steps to reproduce:**
First, I wanted to create an automated action that changes the internal category of an article when the article is archived, but I didn't succeed. So I tried to change the name of an article when this article is updated :
1. Create an automated action 
2. Related Document Model : **Product**
3. When to run : **On Update**
4. In Actions tab, add an item with :
     - Base Model : **Product**
     - Action To Do : **Write on a record**
     - Value Mapping : 
             Field : **Name (product.product)**  
             Evaluation Type : **Value**  
             Value : **Test**
5. Then Save
6. Modifiy a product

**=> The product name will not change**

I have already tested on product categories, partner and it works :+1: 
But on product, it doesn't work.

**Screenshot link:**
Automated Actions :  
- Conditions Tab : https://screenshots.firefox.com/vjQcbjm6zPPJhUtc/192.168.1.231
- Actions Tab : https://screenshots.firefox.com/NvMq2F1fj2IYRTDN/192.168.1.231

Server actions : https://screenshots.firefox.com/0IaVYXgSOuyVs0wu/192.168.1.231

Also, when I create an automated action with "When to run" field set on **Based on form modification** to do pretty much the same thing, it does not work.

**Screenshot link:**
Automated Actions :  
- Conditions Tab : https://screenshots.firefox.com/aQqsfp596gYEhZZ9/192.168.1.231
- Actions Tab : https://screenshots.firefox.com/drAGBbr2JzKFiH1K/192.168.1.231

Server actions : https://screenshots.firefox.com/loIOx64akWZSdQBL/192.168.1.231

(I also tried this on Odoo 11, it works perfectly :))

Thank you :)

**Comment by seyed-mohammad-motahar** [comment]
Having exactly same problem here.

Note that there are several other requests in the forum like below ones that indicates there is no documentation / examples / Answers for automated actions in Odoo for options like "Based on form modification" at all. 

https://www.odoo.com/forum/help-1/question/how-to-use-based-on-form-modification-automated-actions-118315

https://www.odoo.com/forum/help-1/question/automatic-emails-based-based-on-form-modification-v-9-105390

https://www.odoo.com/de_DE/forum/hilfe-1/question/how-to-change-the-value-of-a-field-through-based-on-form-modification-of-automated-action-and-server-action-in-odoo-9-117422

**Comment by Yenthe666** [comment]
Dear @Aeriah,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
