### ISSUE TITLE
Search records with empty many2many

### ISSUE THREAD

**Issue by mreficent** [odoo/odoo#29163]
**Impacted versions:** only tested in v11

**Steps to reproduce:**

Suppose you have "`model`" model with a "`field`" field. This model has two records with ids 1 and 2. Suppose record 1 has `field` = False and record 2 has `field` = 1.

case A: `env.['model'].search([('field', 'in', [False, 1])])`
case B: `env.['model'].search(['|', ('field', '=', False)]), ('field', 'in', [1])])`

- If `field` is a many2one, then in both cases A and B has the same result. ✔️
[result: `model(1, 2)`]
- But if `field` is a many2many, then this two cases has different result.   ❌
[result in A: `model(2)` and result in B: `model(1, 2)`]

Why this different behavior if `field` is a many2one or a many2many?

**Current behavior:**

`env.['model'].search([('field', 'in', [False])])` unexpectedly doesn't work like `env.['model'].search([('field', '=', False)])` if `field` is a many2many.

`env.['model'].search([('field', 'in', [False])])` will result empty always if `field` is a many2many.

**Expected behavior:**

if `field` is a many2many, then one expects that `env.['model'].search([('field', 'in', [False])])` has the same result as `env.['model'].search([('field', '=', False)])` like when `field` is a many2one.

Video/Screenshot link (optional):

**Comment by rco-odoo** [comment]
As explained in the former comment, this behavior is intended.
