### ISSUE TITLE
[12.0] Change Company in One Tab is executed Across All Tabs but Company Name NOT Updated in Other Tabs

### ISSUE THREAD

**Issue by krister-ts** [odoo/odoo#29166]
**Impacted versions:**

12.0 maybe older versions as well.

**Steps to reproduce:**

1. Open odoo in two tabs of browser.
2. In tab _A_, change company from _X_ to _Y_.
3. In tab _B_, look at the inventory, purchase orders and other data.

**Current behavior:**

It is company _Y_'s data but the dropdown to change company says you are looking at _X_.

**Expected behavior:**

1. The dropdown should say _Y_ when viewing data from _Y_ **(required)**
2. Allow data from both companies to be viewed at the same time in separate tabs **(optional)**

**Comment by krister-ts** [comment]
P.S. I did try both Chrome and Firefox. I think it probably is not the browser that is the issue.

**Comment by Yenthe666** [comment]
You basically shouldn't open your Odoo in multiple tabs and expect that all data is fully updated in all tabs at all times. @pedrobaeza do you agree?

**Comment by pedrobaeza** [comment]
Well, as the company switch is something that is done by the user, he/she should be responsible to know that and be consequent on the rest of the tabs. Said that, we can't blame the user for a forgetfulness or other non advisable - but allowed - practices (like have hundred of opened tabs in the browser). There's a module in OCA that adds an intermediate solution which can be the most interesting one:

https://github.com/OCA/web/tree/10.0/web_switch_company_warning

showing a big warning when this situation happens. It's not perfect right now, as if you switch in the other tab to the second company and switch again to the first company, it will still show the warning, although you are finally on the same initial company, but it can be a beginning.

Odoo has already incorporates some warnings like this one, for example with user timezone, so I seem legit to ask to @ged-odoo if they can consider this, and more now that we have the bus mechanism for not overloading communications with this.

**Comment by krister-ts** [comment]
@Yenthe666 it is not that the data is not updated. The fact that it says you are in one company and you can be navigating all over in another company' data while it is still saying you're in the first company is a big problem! You should at least be locked out of second company's data if you have first company selected.

**Comment by krister-ts** [comment]
Could not the company you have selected in that tab be passed along to the server so it can tell you that the PO or whatever you are creating for Company B as a user in Company A is not allowed?

**Comment by Linekio** [comment]
I just made v11 and v12 versions of https://github.com/OCA/web/tree/10.0/web_switch_company_warning :
https://github.com/OCA/web/pull/1302 (11.0)
https://github.com/OCA/web/pull/1303 (12.0)

**Comment by pedrobaeza** [comment]
There are already other PRs in the same repo for that feature/module.
