### ISSUE TITLE
[12.0] "Generate Missing Terms" does not seem to work

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#29184]
**Impacted versions:**
12.0

**Steps to reproduce:**
1. Install a new language by"Load a Translation"
2. Change a string representation in any place, e.g. string in form view
3. Run "Generate Missing Terms"

**Current behavior:**
New translation record is not being created for the new string.

**Expected behavior:**
New translation record should be created like in v11.0.

**Video/Screenshot link (optional):**
https://drive.google.com/file/d/1wJ9DoshZsxA30bUNQiI38IKyGfOiAsx7/view

**Comment by pedrobaeza** [comment]
I think this is not how "Generate Missing Terms", as the term is not missing right now: you have the ir.translation entry with the reference to the view part, but it's not with the updated source term as you have changed it in screen.

**Comment by TimLai125** [comment]
@pedrobaeza I think in v11.0, the source term is actually updated/a new record for the source term is created. I understand it turnout might not be an issue but It will be nice to know in details how the behavior is changed, escpecailly for people who work a lot in translation.

**Comment by pedrobaeza** [comment]
Have you tried to export the translations of that module to see what is exported?

**Comment by yostashiro** [comment]
Maybe we should just forget about terms modified through screen for now.  I am having trouble with generating missing terms for the **standard** strings.
![e27d4ae9-c9de-455e-b9cc-eeb7fbf21078](https://user-images.githubusercontent.com/7766939/50203097-be5f9b00-03a3-11e9-8484-b80c90fa4b5c.GIF)

Here we want to translate "Purchase Agreement" which is a standard string, but "Generate Missing Terms" does not seem to do the job.

**Comment by yostashiro** [comment]
@mart-e Would you be so kind to take a look at this?  It makes it difficult for us to work on the translation in Transifex as well, since we normally jump to Transifex from the link button in ir.translation records.
