### ISSUE TITLE
Event badges not showing (rendering) correctly

### ISSUE THREAD

**Issue by zizou4426** [odoo/odoo#29195]
Impacted versions: 12

Steps to reproduce: First create an event, confirm event, add participants, print event badges

Current behavior: Attendee name not showing (Nor does ticket name)

Expected behavior: Attendee name must show 

Video/Screenshot link (optional):

**Comment by zizou4426** [comment]
![capture](https://user-images.githubusercontent.com/29745250/49305900-88c44200-f4c8-11e8-8d95-b1eeadc29e3e.JPG)

**Comment by zizou4426** [comment]
![image](https://user-images.githubusercontent.com/29745250/49305971-c0cb8500-f4c8-11e8-88f3-6a24ffc9997b.png)
Normal badge image

**Comment by Yenthe666** [comment]
Hi @zizou4426,

Thanks a lot for your report!
The attendee its name is indeed not printed so I can confirm that this is a bug in V12.
@tivisse who can look at this?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@qsm-odoo this might actually be for you, I believe it is one of those BS4 quirks.

**Comment by zizou4426** [comment]
Hi @Yenthe666 
Badge still not showing correctly: With 3 attendees for example, the second attendee badge is split and a part shows up on the third page 
![image](https://user-images.githubusercontent.com/29745250/50190915-186c4c00-0323-11e9-85be-b098199d7060.png)

**Comment by Yenthe666** [comment]
@qsm-odoo for your interest!
