### ISSUE TITLE
Editing shipping address on e-commerce checkout updates also the billing address

### ISSUE THREAD

**Issue by jusle** [odoo/odoo#29192]
Impacted versions:

8-12

On Odoo e-commerce checkout, when customer edits the shipping address, it also changes the billing address. On Odoo 12, new checkbox has been added to create a new shipping address, but this is not enough. It still behaves wrong. The functionality is very misbehaving to the user, because if the user edits shipping address, the program should update the delivery address and not the billing address! This "feature" causes unhappy Odoo customers and end users. Thus, this should be treated as a bug.

PS. Also reported to enterprise support.

**Comment by jusle** [comment]
Here's a screenshot of the e-commerce checkout step where this bug appears: https://drive.google.com/file/d/1nxI3khdTz-uJLdXYqOmX69N9cEl_sS2t/view?usp=sharing

**Comment by JKE-be** [comment]
@nim-odoo 

Probably my PR (#29484) was related to this issue

**Comment by JKE-be** [comment]
It has been improved in v12 to show a warning.

We don't plan to backport it since it is an improvement.
