### ISSUE TITLE
[doc] doc build html failed

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#29197]
Impacted versions:
12 

Steps to reproduce:
switch to doc directory, and execute `make html`

Current behavior:
build failed. report `pyjsparser.pyjsparserdata.JsSyntaxError: Line 116: Unexpected identifier`

the details is
> 
> sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
> 
> Exception occurred:
>   File "/mnt/c/_odoo/odoo/doc/_extensions/pyjsparser/parser.py", line 1048, in throwUnexpectedToken
>     raise self.unexpectedTokenError(token, message)
> pyjsparser.pyjsparserdata.JsSyntaxError: Line 116: Unexpected identifier
> 

Expected behavior:

Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
Can't reproduce, builds fine (though with warning).

**Comment by jeffery9** [comment]
still can't build the doc.
env:
 ubuntu 
 python3.5 
 sphinx  1.3.6

report  `  ValueError: Docs for BarcodeEvents (<class 'autojsdoc.parser.jsdoc.InstanceDoc'>) should be a dict or namespace `

details as 
> ubuntu@VM-0-4-ubuntu:~/odoo/doc$ make html
> sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
> WARNING: intersphinx inventory 'http://docs.sqlalchemy.org/en/rel_0_9/objects.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 110] Connection timed out>
> 
> Exception occurred:
>   File "/home/ubuntu/odoo/doc/_extensions/autojsdoc/parser/parser.py", line 82, in deref
>     raise ValueError("%r (%s) should be a dict or namespace" % (obj, type(obj)))
> ValueError: Docs for BarcodeEvents (<class 'autojsdoc.parser.jsdoc.InstanceDoc'>) should be a dict or namespace
> The full traceback has been saved in /tmp/sphinx-err-b103d0y9.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:52: recipe for target 'html' failed
> make: *** [html] Error 1
>
