### ISSUE TITLE
[BUG] hr: result_qty is tested negatively while present in localdict

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#29205]
@tivisse 
On v12, right from the interactive debugging session:

```python
>>> localdict['result_qty']
0.0
>>> 'result_qty' in localdict and localdict['result_qty'] or 1.0
1.0
```

That's a bug.

**Comment by blaggacao** [comment]
Ticket
#1914485
submitted

**Comment by blaggacao** [comment]
Here is the line: 
https://github.com/odoo/odoo/blob/8c3bf092a297ee5e64af79368f932e7b1536548e/addons/hr_payroll/models/hr_salary_rule.py#L230

**Comment by Yenthe666** [comment]
@blaggacao can't we close the ticket if you have an OPW and a PR though? 😄
