### ISSUE TITLE
bug in account/models/account_bank_statement.py

### ISSUE THREAD

**Issue by ndemoreau** [odoo/odoo#29202]
Impacted versions:
v12 all
Steps to reproduce:
If you import bank statements and that, for a line of the statement, the partner is not recognized. In the reconciliation screen, you then select the partner. This partner already has a bank account defined.

When you click "validate", an error message pops up telling that the bank account must be unique

Current behavior:

The system tries to create the bank account because it has a partner and in the bank statement line it doesn't see any account_number. 

Expected behavior:

Before creating the bank account, it should check that the bank account doesn't exist.

line 658 of account_bank_statement.py
        #create the res.partner.bank if needed
        if self.account_number and self.partner_id and not self.bank_account_id:
            self.bank_account_id = self.env['res.partner.bank'].create({'acc_number': self.account_number, 'partner_id': self.partner_id.id}).id

The only workaround for now is to delete the bank_account from the partner to let the system re-create a new one. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please copy the permalink of the line for a fixed reference?

**Comment by smetl** [comment]
This issue is already fixed on 12.0 by this commit:
https://github.com/odoo/odoo/commit/05d31187d4ede241b0fe48d27d4020440e207e23
