### ISSUE TITLE
[8.0] Account Types Menu should be by default accesible for Financial Manager Group.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#2920]
This is the kind of errors will bring a lot of unnecesary support when everybody starts to close Fiscal Years.

This menus should be accessible for the Financial Manager to be able to fix the closing process without be a technical guy (even if we know it is normally what happens).

![Account Types Menu.](https://www.evernote.com/shard/s158/sh/c0e8e249-4bd7-4aaf-a9f2-97bbf654d3c0/5bccc7bab38314c5823ae6735fca983e/deep/0/Menu-Items---Odoo.png)

I know it is functionally easy to solve, but IMHO it should be by default on this way.

**Comment by dmo-odoo** [comment]
Hello,

I reached to the accounting dev team and they told me they didn't want to change the access rights for this menu so I'm closing this.

You can open account types from the form view of an account with the Financial Manager rights. Just open the account you want to fix the type for, click Edit, then you will see a blue box with an arrow at the right side of the Account Type field, this will open the form view of the account type where you can make changes.

Best regards,
David
