### ISSUE TITLE
[BUG] Import/Export - Duplicate variants for same product and inventory qty issues

### ISSUE THREAD

**Issue by svenv** [odoo/odoo#29213]
Impacted versions: 
11.0 Community

Steps to reproduce:
1. Do an import-compatible export with all products with the following fields:

- Public Price
- Products/Name
- Products/Pricelist Items/Pricelist
- Products/Pricelist Items/Fixed Price

![field-list](https://user-images.githubusercontent.com/913827/49364046-5434ce00-f6f4-11e8-91af-09988d64e386.png)

2. Add prices for a custom pricelist. In our case we had a custom pricelist but for some products the price for this pricelist was missing, which we updated using export/import.

3. Re-import the file. We re-imported after 1 hour and the test import did not give any errors. Note we're doing sales on the POS during this hour.

Current behavior:

1. While there are no duplicates for the products seen in the Master Data, there are duplicate products seen in the POS, as well as when creating a PO, see below.

![master-data-no-duplicate](https://user-images.githubusercontent.com/913827/49364344-269c5480-f6f5-11e8-8a5c-030a3ed4756a.png)
![duplicate-po](https://user-images.githubusercontent.com/913827/49364343-2603be00-f6f5-11e8-891b-d9b11f6cda4d.png)

2. Also, it seems the duplicate product has its own stock counting. We tried to change the quantity of one product from 2 to 1, using Update Qty on hand-button on the product itself, and it changed to 0. Then we tried to change it again using the same button to 1, it remained 0. Then we did an inventory adjustment instead for the product, where we're now able to select either of both products. One is giving a theoretical quantity of 1, the other is giving a theoretical quantity of -1.

![theoretical-quantity-and-real-quantity-2](https://user-images.githubusercontent.com/913827/49364955-87785c80-f6f6-11e8-9f62-9eb459327317.png)
![theoretical-quantity-and-real-quantity](https://user-images.githubusercontent.com/913827/49364959-89422000-f6f6-11e8-93a4-8bab5bf46d4e.png)

Changing both to "1", changes the qty in the master data to "2".

![quantity-on-hand-afterwards](https://user-images.githubusercontent.com/913827/49365077-e5a53f80-f6f6-11e8-830e-62319b980882.png)

3. And then we see the imported file created another pricelist instead of updating one.

![double-pricelist](https://user-images.githubusercontent.com/913827/49365256-5ea49700-f6f7-11e8-81b3-432126dc144b.png)

Expected behavior:

No duplicate records in any way.

How export list now looks like (I've added product_variant_ids/id and product_variant_ids/pricelist_id/id to get more data):
![exported-file](https://user-images.githubusercontent.com/913827/49365506-13d74f00-f6f8-11e8-8dd7-68e1af99fa50.png)

**Comment by Yenthe666** [comment]
@switch87 probably relevant for you.

**Comment by switch87** [comment]
@svenv If you import product.product into you database and this product is already there, It is expected behaviour there will be a new product.product generated based on the same product.template. If I understand it right this is what you did? you will not see the 2 variants on the products page (actually the product.template page) but they will be both present at the product variants page. 

I will close this issue for now, If this is not what happened, please comment so it can be opened again.

@Yenthe666 If this ticket needs opening again, it will not be handled by me, I am not familiar enough with the importing and exporting code in Odoo.

**Comment by svenv** [comment]
@switch87 Hi Gert, it's exported and re-imported with the export-ID, so the expected behavior is the update the existing product, not create a duplicate product. At least that's what I understood from the documentation, hence we did an import-compatible export.

**Comment by pedrobaeza** [comment]
@svenv, you are using export-ID for the product, not for the subtable, so the product will be updated, but for the subtable product.pricelist.item, a new one will be added.

**Comment by svenv** [comment]
@pedrobaeza I see now.. Thanks.
