### ISSUE TITLE
Can't edit website button / link in Safari

### ISSUE THREAD

**Issue by davidmw** [odoo/odoo#29215]
Impacted versions: V12 Enterprise

Steps to reproduce: Must be on OSX Safari

Current behavior: When editing website - a 'button' inner content block can't be put into edit mode with double click.

Expected behavior: The edit link dialog should display with all fields correctly populated

Creating an 'in-line' link within a text block allows creation of a link (or with button styling). But editing this link after creating it will show a missing or [IMG] label in the edit dialog, no URL destination, and no preview of the link being edited.

This problem does not happen on OSX Chrome and did not happen in Safari with Odoo v11.

**Comment by pedrobaeza** [comment]
Hi @davidmw, are you able to reproduce the problem in runbot infrastructure on latest code version (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by rdeodoo** [comment]
Lot of changes happened during last year.
We just gave it a try and it worked fine. It was probably fixed meanwhile.
Thank you for your report, sorry for the long delay.
