### ISSUE TITLE
Element '%s' cannot be located in parent view

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#29226]
Odoo 11.0-20181203 Ubuntu 18.04 LTS
https://github.com/odoo/odoo/blob/e0b1718e4a1ab641f56fef242ae1d6c13254b53c/odoo/addons/base/ir/ir_ui_view.py#L591

I am updating the base version from 10 to 11.
The database uses many third-party modules.
I used the base with OpenUpgraid and now I'm trying to update all modules with command: `/usr/bin/odoo --config /etc/odoo/odoo.conf -d erp11 **-u all**`
And I get the error: 

` Element '<xpath expr="//button[@name='split_lot']">' cannot be located in parent view`
This error is just one example. I get a **lot** of similar errors in many Views in many Modules. But, one by one! I can't see all errors. I fix one error, start update all modules, get new error, fixing it, start update all modules, get new error, fixing it,... This is a **very unproductive** way.

### Looking ahead to tell the reason: 
if you changed several Views at once in several modules that refer to the same model, then you will get an error when updating because the algorithm sequentially updates Views, but before saving it checks them. For this test, odoo previously does NOT UPDATE (!) all other Views of this model, but takes them from the base. But if you have incorrect Views in the database, then during this check a failure occurs and odoo does not allow you to update the module.
My manual solution: go to the database, menu, Settings, Views, filter by field **arch_db**(Arch Blob) field contain `<xpath expr="//button[@name='split_lot']">`, open View, Edit, **Active = False**, Save. Then I click Update module and it is updated.
This is a very inefficient way, because modules can be to many! and errors may be several in each.

This error is cyclical and below I will explain why:
### The reason for the error is in detail:
1. In odoo 10 there is an official "**stock**" module and a model "**stock.picking**" and **View** for it.
2. There is a third-party **stock_X1** module for **odoo 10** that extends this view with `<xpath expr =" // button [@ name = 'split_lot'] "> `(stock_x1/view/stock_picking_inherited.xml file).
This view is completely **correct** for odoo 10. 
Like all other Views, it is recorded in the base itself in the ir_ui_view table.
3. There is also a **stock_X2** module, which also extends the Views of the **stock.picking** model and contains the same `<xpath expr =" // button [@ name = 'split_lot'] "> `(file stock_x2/view/stock_picking_inherited.xml).
4. The modules **stock_Х1** and **stock_Х2** - do not depending from each other, but depend only on the **stock** module.

Note: the **stock_Х1**, **stock_Х2** modules and their Views work **perfectly** in **odoo 10**, because in odoo 10 in the **View** for **stock.picking** model there is "**<button name = 'split_lot' ..**."

-------------------------

After update the database to the 11th version, I completely **deleted** (!!!) from the files
stock_x1/view/stock_picking_inherited.xml **and** stock_x2/view/stock_picking_inherited.xml
the Views along with `<xpath expr =" // button [@ name = 'split_lot'] ">`.

5. But when I do make `/usr/bin/odoo --config /etc/odoo/odoo.conf -d erp11 -u all`
I get the error: ` Element '<xpath expr="//button[@name='split_lot']">' cannot be located in parent view` in the presentation loaded from the file **stock_x1**/view/stock_picking_inherited.xml

6. If I go to odoo 11 and update the module **stock_x1**, then I get the same error in the View which loaded from **stock_x2**/view /stock_picking_inherited.xml

7. If I go to odoo 11 and update the **stock_x2** module, then I get the same error in the View which loaded from  **stock_x1**/view/stock_picking_inherited.xml

This is a **cyclical** problem! 
It turns out if I update the **stock_x1** module, and in it the Views for the **stock** modules, then odoo updates only(!) the Views of the **stock_x1** module, 
but at the same time it checks **all** (!!!) Views of the model **stock.picking**,
 which get from database and this Views not updated yet!
I need to update **several** Views of the **stock.picking** model in **several** modules at once!

PLEASE pay attention: files  **stock_x1**/view/stock_picking_inherited.xml and **stock_x2**/view /stock_picking_inherited.xml do NOT contain code `<xpath expr =" // button [@ name = 'split_lot'] ">`, because I remove(**delete**) this code from them. But despite this, I get an error about incorrect View, because odoo get old View **from database**!

I have to **manually** (!) find these Views in the database and disable them (Active = False), and then Update modules. This increases the time required for porting the base and modules.

### I believe that:
- when odoo updating a module, 
- when odoo loading a View1 from file(**stock_x1**/view/stock_picking_inherited.xml) of "this module"(**stock_x1**) for some model(**stock.picking**) into the database, 
- when odoo check this View and automaticaly check **OTHER**(!) Views for this model(**stock.picking**)
- BEFORE checking the **OTHER**(!) View of this model(**stock.picking**) from other modules(**stock_x2**) for errors, 
- odoo **at first** need to **update** (!!!) View(again^ **update BEFORE! checking** from file **stock_x2**/view/stock_picking_inherited.xml) and **only after update** - start checking View! Or at least provide such an option: update all launched Views of models. Instead of updating only the Views of the **current** module.

Or create option allowed to check Views only in module which I update now. Do not check View on this model which loaded from other modules.

**Comment by pedrobaeza** [comment]
@KomarovAlea this is not something that you can report here, as it comes from a custom migration that doesn't belong to Odoo, but neither on OpenUpgrade, as this is something specific to your installation, where you have some dependent views that are not removed. You should remove all the dependency tree before updating.

Closing as no Odoo issue.

**Comment by KomarovAlea** [comment]
> You should remove all the dependency tree before updating.

How I can do it? I need to clear table ir_module_module_dependency and then update all modules?
I can't find information about "removing dependency" in documentation of OpenUpgrade and in Internet. Please describe what you mean?

**Comment by pedrobaeza** [comment]
Sorry, but you have to dig in this by yourself, as there's no a general recipe for this.
