### ISSUE TITLE
odoo.sh psql how i can update table

### ISSUE THREAD

**Issue by khk-optesis** [odoo/odoo#29236]
Impacted versions: postgres 10.6

Steps to reproduce:

Current behavior:
ERROR:  permission denied for relation pg_roles
<img width="1278" alt="error" src="https://user-images.githubusercontent.com/44680721/49435837-70e20c00-f7af-11e8-94ff-31a4757f91cd.png">

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

A tip: it seems a PostgreSQL permission problem.

Closing this by the reason above.
