### ISSUE TITLE
Big Margin only on Edge

### ISSUE THREAD

**Issue by DmorelC2S** [odoo/odoo#29252]
Impacted versions:
10
Steps to reproduce:
Edge
Current behavior:

Expected behavior:
![edgemargin](https://user-images.githubusercontent.com/38214061/49455775-06998d80-f7e8-11e8-8a85-42aef9f81746.PNG)

Hello,

On Edge only, i have big margin every where (menus, status bar, …).
It cause hidden component because there are behind other.
Is it possible to correct it ?

Regards

**Comment by Yenthe666** [comment]
Dear @DmorelC2S,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
