### ISSUE TITLE
Impossible to do product inventory if uom is not in unit category

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#29305]
Impacted versions:
12.0 - tested on runbot community and enterprise
Steps to reproduce:
* Go to any product whose uom is not units (tested using cable management box that was in kgs)
* Click update qty on hand
* Click Start Inventory
* Fill the prefilled line then add a line. (imagine you need to update multiple lots or locations - its not turned on in runbot but you still get the error)

Current behavior:
UoM Mismatch Error

Expected behavior:
Not UoM Mismatch Error

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What is the exact error given by Odoo?

**Comment by gdgellatly** [comment]
The unit of measure kg defined on the order line doesn't belong to the same category than the unit of measure Unit(s) defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category. 

so i guess thats a second bug, because it isnt an order line.

**Comment by pedrobaeza** [comment]
OK, thanks for the extra info.

@jco-odoo I suppose this one is for you.

**Comment by gdgellatly** [comment]
@jco-odoo maybe a simple fix is a better default function. kind of masks the issue but effectively - if product is set default product uom, else units

**Comment by jco-odoo** [comment]
@gdgellatly or just remove the default function.  I see it was added in the conversion to the new api.  Normally, the uom was set in the onchange, but in this case, the line is probably created automatically by the update qty and the uom should be passed there.  @Whenrow  @nim-odoo Better to bugfix.

**Comment by jir-odoo** [comment]
@jco-odoo We can remove default , as it will execute on-change , if someone create directly inventory 
(xmlrpc) field is required they need to pass uom of the product..So we can remove default ..

Thanks...

**Comment by jco-odoo** [comment]
Indeed
