### ISSUE TITLE
Error while importing account.account.csv

### ISSUE THREAD

**Issue by qndi** [odoo/odoo#29326]
Impacted versions: 12.0E + 12.0C

Steps to reproduce:
Export an account.account to CSV with Field "reconcile"
Import the same file.

Current behavior:
syntax error at or near ")" LINE 4: ... WHERE full_reconcile_id = NULL AND account_id IN () ^ in Zeile 3
![image](https://user-images.githubusercontent.com/5363782/49601177-64171100-f985-11e8-8b47-85e67a521a7e.png)

Expected behavior: no error

Description:
If an existing account is imported with reconcile=False and the field is already False, then the method _toggle_reconcile_to_false is called with an empty recordset.

Proposed Fix: 

in the method _toggle_reconcile_to_false
if not self.ids:
    return None

**Comment by Yenthe666** [comment]
@qdp-odoo this is indeed an issue, we had it for a customer too last week. Can you check?
