### ISSUE TITLE
social media icons not displayed

### ISSUE THREAD

**Issue by tarbib** [odoo/odoo#29333]
Impacted versions: V12 Community 

Steps to reproduce:
Go to website / configuration / Settings 
Check the checkbox social media
Add a link in the Twitter field to a twitter account: https://twitter.com/account

Current behavior:
Does not display any icons.

Expected behavior:
Should display a Twitter icon with a link to the twitter account.

Video/Screenshot link (optional):
Twitter link filled
![image](https://user-images.githubusercontent.com/2255433/49625620-35467c80-fa11-11e8-946d-140604027822.png)
Twitter icon not displayed
![image](https://user-images.githubusercontent.com/2255433/49625627-38da0380-fa11-11e8-9666-def8b047f6a3.png)

**Comment by pedrobaeza** [comment]
Did you activate website custom footer?

**Comment by JKE-be** [comment]
@pedrobaeza 
Custom footer doesn't exists anymore in v12

@tarbib 
I cannot reproduce the error.
https://drive.google.com/file/d/1J5RpbXqxz7Qfgl0hnbwFj8xLH23PugqX/view

**Comment by pedrobaeza** [comment]
@JKE-be thanks, I haven't dug enough yet on v12, but I'm glad to know that there's no more that weird duality!

**Comment by tarbib** [comment]
Thanks all for your feedback, on my particular website I added the logo manually, no idea why it still does not work while it worked when I created a new website like in your video @JKE-be . Only difference I saw is I do not have English installed nor as the default language. But I don't think it's the reason.
