### ISSUE TITLE
8.0: duplicate button "View Product Lines" on requisition

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#2933]
To reproduce:
- Assign a user to "Technical Features" and "Advance bidding process"
- create  a new call for bids, and advance to the state "Bid Selection" (`open`)

There are two buttons: "View Product Lines" and "Choose product lines". They do the same thing (they both call the method `open_product_line`.

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
