### ISSUE TITLE
UI: No all menus have the open to right click and open in new tab

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#29345]
Impacted versions: V12

Steps to reproduce:Right click on the main menu or the app drawer Menu give no option to open in new tab

Current behavior:  No option to right click

Expected behavior: should give open in new tab and open the related first menu under the app drawer menu

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please add an screenshot of what do you mean?

**Comment by omalbastin** [comment]
![screenshot from 2018-12-07 17-33-44](https://user-images.githubusercontent.com/381874/49646801-48277400-fa46-11e8-9127-f95d71208cbf.png)

**Comment by pedrobaeza** [comment]
Well, this case is a bit special, as this menu doesn't contain URLs per se, so it's not possible to open that in the link.

@qsm-odoo I agree with @omalbastin that it would be great to be possible to open the area in another tab, but is that possible if you know?

**Comment by qsm-odoo** [comment]
@ged-odoo

**Comment by Yenthe666** [comment]
@ged-odoo any update on this one please? Still relevant.

**Comment by Yenthe666** [comment]
@qsm-odoo can you maybe get this going again?

**Comment by qsm-odoo** [comment]
No sorry, my framework powers are gone. You would have to check with @ged-odoo @aab-odoo but I think they already have a lot going on right now :wink:

**Comment by Yenthe666** [comment]
Yeah I tried to avoid them intentionally as they're both pretty busy probably. 😄 I guess we'll need to wait for feedback from one of both then.

**Comment by Yenthe666** [comment]
@ged-odoo and @aab-odoo could you give feedback please? 🙏
