### ISSUE TITLE
[ <-- 12.0] Add tax codes for 9% and also update the fiscal position, The Netherlands

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#29352]
Impacted versions:
[10.0]
[11.0]
[12.0]

The Dutch taxes will change the low tax 6% to 9% on 01/01/2019. Please add these tax code in the system and also change the affected fiscal positions. Both 6% and 9% needs to exist during the transition period.

More information can be found here (in Dutch).
https://www.rijksoverheid.nl/onderwerpen/belastingen-voor-ondernemers/verhoging-lage-btw-tarief
https://www.rijksoverheid.nl/onderwerpen/belastingen-voor-ondernemers/nieuws/2018/06/08/geen-naheffing-bij-verhoging-btw-tarief

**Comment by Yenthe666** [comment]
@qdp-odoo and @oco-odoo this is indeed a fact, it will become effective on 01/01/2019.
Can we just add a tax code or?

**Comment by william-andre** [comment]
Merged : closing
