### ISSUE TITLE
[12] Issue with decimal precision in Lunch order report

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29364]
Impacted versions: 12

Steps to reproduce: 
![screenshot](https://user-images.githubusercontent.com/16624719/49661874-4ffc0e00-fa70-11e8-9333-8b3a87955750.png)

Current behavior:  Total is 61.60000000000001 $
![screenshot from 2018-12-07 22-35-14](https://user-images.githubusercontent.com/16624719/49661902-63a77480-fa70-11e8-85b0-d538de6af6ae.png)

Expected behavior: Total should be 61.60 and also  currency symbol on the report should consistent 

Video/Screenshot link (optional):

**Comment by tivisse** [comment]
Fixed at https://github.com/odoo/odoo/pull/29541

Thanks.
