### ISSUE TITLE
Exchange gain or loss on partial payments

### ISSUE THREAD

**Issue by ganesheverbest** [odoo/odoo#29369]
Impacted versions: 11

Steps to reproduce:
1) Make 2 different Multi currency Invoices for the single supplier
2) Modify the current exchange rate under currencies
3) Make a partial payment for one single invoice with exchange difference

Current behavior:
It does not generate the Exchange gain or Loss for the partial invoice payments

Expected behavior:
Irrespective of the full payments or partial, it should generate the Exchange gain or Loss as per the payment date and Invoice record Date
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you explain a bit more the steps to reproduce the problem? It's not enough to say "Make a partial payment" and things like that. You should comment every step, where do you click, and so on. For example, with your explanations, I see no sense in creating 2 invoices instead of only one, as you are saying in mega-step 3 that you are doing the payment for one single invoice.

**Comment by alfredourena** [comment]
@pedrobaeza @ganesheverbest 

Any news or solutions with this issue? It's causing us some trouble with some customers.

**Comment by pedrobaeza** [comment]
Not yet. It has been tagged, but there's no obligation by Odoo to check all the issues reports. If you want this to be checked and you have an enterprise contract, then you can issue an enterprise ticket with the problem and the reference to this one.

**Comment by alfredourena** [comment]
@pedrobaeza Thanks for the information.

I've created the enterprise ticket. Here's the number #1974196

**Comment by lexerpars** [comment]
@ganesheverbest  Did you find a solution to this problem?
I have exactly the same problem..

**Comment by alfredourena** [comment]
No solution yet... This is causing me a lot of issues with customers

**Comment by MOGwebz** [comment]
I have same problem with a Customer. Did any one find a Solution?

**Comment by atrivia** [comment]
@MOGwebz @ganesheverbest @lexerpars  Maybe this could help:

https://github.com/odoo/odoo/issues/37469

**Comment by Yenthe666** [comment]
I guess the OPW should have solved/answered this plus V11 is no longer supported.
