### ISSUE TITLE
[12.0] Iotbox date time prevents https requests to server

### ISSUE THREAD

**Issue by h4818** [odoo/odoo#29365]
Impacted versions: 
Odoo Enterprise 12.0 on odoo.sh (ssl) 
iotbox 18.10

Steps to reproduce: 
Try to connect Iotbox to server after a few weeks from creation date of box.
Try to connect to server using curl https://server.odoo.com/ from iotbox

Current behavior:
Since the time is incorrect, the posbox is unable to connect to secure server.
setting the time manually seems to fix it but it is not persistent across reboots.

Expected behavior:
NTP should be running to continually update the time and hence allow secure connections to public odoo instances.

Video/Screenshot link (optional):

**Comment by switch87** [comment]
@qle-odoo , can you take a look at this?

**Comment by fluential** [comment]
Same here

**Comment by qle-odoo** [comment]
We solve this problem.
Now IoT Box make request without check certificate : 
https://github.com/odoo/odoo/blob/1a4f3114a712a152ff21e61beceab40e3baca56c/addons/hw_drivers/controllers/driver.py#L421
