### ISSUE TITLE
[12] Issue with previous_order widget in Lunch application

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29363]
Impacted versions: 12

Steps to reproduce: 
`                            <field name="previous_order_widget" widget="previous_order" class="o_lunch_last_orders"/>` is used in `lunch.lunch_order_view_form`

Current behavior:
![download 2](https://user-images.githubusercontent.com/16624719/49661137-496c9700-fa6e-11e8-804d-4c342c668e3f.png)

Expected behavior:
![download 3](https://user-images.githubusercontent.com/16624719/49661147-525d6880-fa6e-11e8-8ee0-742bf7af5162.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Similar issue in kanban view too
```
<span class="badge badge-pill float-right">
         Price: <t t-esc="record.price.value"/>
</span>
```
v12
![download 4](https://user-images.githubusercontent.com/16624719/49661589-740b1f80-fa6f-11e8-919a-49b1fbcfacbc.png)



v11
![screenshot](https://user-images.githubusercontent.com/16624719/49661573-6c4b7b00-fa6f-11e8-8183-cf56d2e9dbcd.png)

**Comment by pedrobaeza** [comment]
I'm not sure to classify this as bugs, but change of appearance. I tag any way for letting the developers of the module to say.

**Comment by sswapnesh** [comment]
True, However It should be Improved (May be in master) for better appearance.

**Comment by sswapnesh** [comment]
`btn-link` should be used there. (But still few Improvements)

![screenshot](https://user-images.githubusercontent.com/16624719/49663730-92741980-fa75-11e8-89af-489998e05693.png)

**Comment by tivisse** [comment]
Fixed at https://github.com/odoo-dev/odoo/commit/8fd17a4cc3d0e0e81b504b64d8575260079832e7
