### ISSUE TITLE
odoo12,how to use .yml to run python code every time when module update

### ISSUE THREAD

**Issue by guohuadeng** [odoo/odoo#29370]
is that .yml is no longer support in odoo 12?
what if I want to run a python script every time we update the module?
thanks

Impacted versions: 12

Steps to reproduce: add run.yml file to __manifest__.py

Current behavior:
"Can't load unknown file type %s.", 'data/run.yml'

Expected behavior:

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
You can't. Compare any v12 localization to v12 to see how in xml.

**Comment by pedrobaeza** [comment]
YAML format has been removed in this version. You can use XML `<function>` tag.

Closing as no issue, but intended removal.
