### ISSUE TITLE
[11.0] Wrong logic in convert_to_onchange field

### ISSUE THREAD

**Issue by xubiuit** [odoo/odoo#29380]
Hi guys,

Please check the logic below as we already checked there is no record ID but we're still using that variable. If there is no record ID then we should force (0, **0**, {vals}) instead of get ref
https://github.com/odoo/odoo/blob/77e7d952b4c72d58c1b8f34b57e355f5b98c88b0/odoo/fields.py#L2145
Please help me to review and get back as soon as possible.
Thanks and Best regards,

**Comment by Yenthe666** [comment]
@xubiuit please make a PR if you think something is wrong and if you know a solution. PR's are handled a lot faster 😉

**Comment by xubiuit** [comment]
@Yenthe666 2 PRs were already created, what should I do now without waiting?

**Comment by pedrobaeza** [comment]
Closing the same as the PR.
