### ISSUE TITLE
[8.0] Purchase Order - Wrong price computation

### ISSUE THREAD

**Issue by mvercruysse** [odoo/odoo#2938]
Hi everyone,

**Impacted versions**
8.0

**Steps to reproduce**
1. Go to a v8 runbot instance
2. Activate in the purchases settings the box : "manage price per supplier"
3. Go to the pricelist tab and check the Default Purchase Pricelist configuration
4. One pricelist item line should be in the pricelist version with all products based on the cost price ( coeff = 0; price_surchage = 0 )
5. Create a purchase order on a product having a cost price already defined and with a supplier having the Default Purchase Pricelist set

**Current behavior**

The unit price computed is always 0

**Expected behavior**

The unit price should be the cost price of the product.

Here is a small video of the problem encountered: https://www.youtube.com/watch?v=71KjYLGF24o&feature=youtu.be

Regards, Matthias

**Comment by Yenthe666** [comment]
Hi @mvercruysse,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
