### ISSUE TITLE
[12.0] Unsubscribe btn and bell icon overlays

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#29387]
**Impacted versions:**

12.0

**Steps to reproduce:**

Install chatter, select Polish language (or other with long word for unsubscribe)

**Current behavior:**

Unsubscribe button and bell icon overlay, hard to use bell icon.

**Expected behavior:**

elements do not overlay

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/5862658/49734610-1a7c3e00-fc85-11e8-9db1-eda27f620069.png)

**Comment by intero-chz** [comment]
It's the same for German in several Odoo versions.
