### ISSUE TITLE
Cache error odoo V8 in projects

### ISSUE THREAD

**Issue by DavidCasa** [odoo/odoo#29397]
Impacted versions: 
Odoo v8

Steps to reproduce:
when entering projects

Current behavior:
value = self._recs.env.cache field self._recs.id 
key error: 390

Expected behavior:

SHOW ALL EXISTING PROJECTS IN ODOO

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but version 8 is no longer supported (current ones are v10, v11 and v12), so closing it. If you reproduce the problem in these version, feel free to open a new issue.
