### ISSUE TITLE
Inheriting web.webclient_bootstrap throws javascript error (session_info)

### ISSUE THREAD

**Issue by mersed** [odoo/odoo#29402]
Impacted versions: Odoo version 12.0

Steps to reproduce: Create a new template which will inherit web.webclient_bootstrap template.

Current behavior: Getting a blank page with javascript error "dashboard:20 Uncaught SyntaxError: Unexpected token ;", where unexpected token is refereed to the session_info.

Expected behavior: Expecting for this view to be inherited with all of the backend elements where I can customize body of it as I want.

Video/Screenshot link (optional): 
![odoo-js-session-info-error](https://user-images.githubusercontent.com/2763483/49779349-e303a500-fd09-11e8-808c-f60c72f7c945.png)

Additiona Notes:
I would like to inherit webclient with all its properties (menus), and blank body (so I can place in that body my custom panel, buttons and data). After I investigated code, I found that, inheriting template above and inserting data within its main div should serve my purpose.

```
<odoo>
    <data>
        <template id="dashboard" inherit_id="web.webclient_bootstrap">
            <xpath expr="//div[@class='o_main']" position="inside">
                <div>
                    Test
                </div>
            </xpath>
        </template>
    </data>
</odoo>
```

**Comment by pedrobaeza** [comment]
Hi, @mersed, sorry, but this is not how the webclient works, as there's not total decouple between the layers. You should dive a lot more inside JS web client architecture before being able to perform this kind of operations. Unfortunately, the documentation is not completed. There is more and more version per version, but it should improve still. Check it at https://www.odoo.com/documentation/12.0/reference/javascript_reference.html.

Closing this as no real issue, but incorrect use of the JS framework.

**Comment by mersed** [comment]
@pedrobaeza  Indeed. I was aware that webclient is "single page", but i though that you are able to provide some parameters as part of the template render.

Anyway, I sorted out by using ir.action.client, static empty template etc ... which servers my purpose ... (so, thank you for the advice). But I find weird to be honest, that this specific action is not documented (based on my opinion, it is one of the best things odoo provide). Basically, the path for the implementation was to check how odoo provided addons, are implemented.

Also, by checking the core for different versions of odoo, I can see that the registration of actions, widgets declarations and other, are changing dramatically from version to version. That is fine, as long as it is documented. 

In general, without documentation about these stuff, larger scale adoption of odoo from perspective of dev community will be little bit hard.
