### ISSUE TITLE
[11.0][12.0] Wrong FIFO with Inter-warehouse moves

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#29406]
### Impacted versions:
11.0, 12.0

### Steps to reproduce:
1. Product 1 with FIFO as the Costing Method
2. Create another warehouse "WH2" additional to the default one "WH"
3. **Purchase 10 units** of Product 1 | **Unit Price: 100**
4. Receive those tem units into the WH/Stock
5. **Purchase 10 units** of Product 1 | **Unit Price: 200**
6. Receive those tem units into the WH/Stock
7. **Move 5** from WH to WH2 (WH/Stock -> Transit -> WH2/Stock)
8. **Send** 10 from WH/Stock to Customer location (WH/Stock -> Customer)

### Current behavior
10 units which were sent to customer has **1000** as its valuation.
It seems that Odoo does not regconize that the first 5 units were sent out priorly, then it uses the price unit from the first stock-in move (100*10 = 1000)

### Expected behavior
It is expected to have **1500** as the valuation: 100 * 5 + 200 * 5

I am not sure if this is desired behaviour? I don't see this issue if the first 5 is sent to customer.

**Comment by pedrobaeza** [comment]
@davidtranhp was this handled somehow or solved?

**Comment by sle-odoo** [comment]
We implement the financial FIFO and your first move is not valued, that's why the oldest incoming shipment is used when making the delivery.

Regards
