### ISSUE TITLE
TypeError: el is undefined in web.assets_common.js

### ISSUE THREAD

**Issue by zukunft** [odoo/odoo#29418]
Impacted versions: 12.0

Steps to reproduce: 
On Kubuntu 18.10 do:
```
sudo wget https://raw.githubusercontent.com/Yenthe666/InstallScript/12.0/odoo_install.sh
sudo chmod +x odoo_install.sh
sudo ./odoo_install.sh
```
and in Firefox open http://localhost:8069/web?debug=

Current behavior: 
TypeError: el is undefined
http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3739
Traceback:
computeFloatOuterWidthWithMargins@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3739:52
_adapt@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3738:425
initAutoMoreMenu@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3732:533
start@http://localhost:8069/web/content/248-d0e87cb/web.assets_backend.js:844:185
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3537:485
_widgetRenderAndInsert/<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3682:47
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
add@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:797:467
then/</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:649
each@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:625:758
then/<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:553
Deferred@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:803:189
then@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:518
_widgetRenderAndInsert@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3681:165
prependTo@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3672:873
instanciate_menu_widgets/<@http://localhost:8069/web/content/248-d0e87cb/web.assets_backend.js:564:45
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:803:56
rpc/<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3587:436
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:803:56
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:803:56
genericJsonRpc/<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:3556:1
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:678
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
then/</</<@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:802:874
fire@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:796:281
fireWith@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:801:198
done@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:1192:86
callback@http://localhost:8069/web/content/247-66c54ea/web.assets_common.js:1212:15

Could not execute command 'sassc'This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/fonts.scss
    - /web/static/src/scss/ui.scss
    - /web/static/src/scss/ui_extra.scss
    - /web/static/src/scss/navbar.scss
    - /web/static/src/scss/mimetypes.scss
    - /web/static/src/scss/modal.scss
    - /web/static/src/scss/animation.scss
    - /web/static/src/scss/rainbow.scss
    - /web/static/src/scss/datepicker.scss
    - /web/static/src/scss/banner.scss
    - /web/static/src/scss/colorpicker.scss
    - /web/static/src/scss/keyboard.scss
    - /web_tour/static/src/scss/tip.scss
    - /web_tour/static/src/scss/keyframes.scss

Expected behavior: Show the odoo start page

Video/Screenshot link (optional): 
![screenshot_20181211_114943](https://user-images.githubusercontent.com/5895333/49795713-fed36f00-fd3a-11e8-8772-7ad75cc2d410.png)

**Comment by sswapnesh** [comment]
@zukunft  Make sure you have installed all required libraries. (You have to trace error manually as you are using automated script)

**Comment by Yenthe666** [comment]
Hi @zukunft,

What traceback do you get when you run the Odoo with `?debug=assets` in the URL? Your URL would be `http://localhost:8069/web?debug=assets`, can you post that one too please?

**Comment by sswapnesh** [comment]
try
sudo pip3 install - r requirement.txt from you odoo source folder.

**Comment by zukunft** [comment]
OK, it is not really the same. I just looked at the first line. Here is the complete response:


TypeError: el is undefined

http://localhost:8069/web/static/src/js/core/dom.js:438
Traceback:
computeFloatOuterWidthWithMargins@http://localhost:8069/web/static/src/js/core/dom.js:438:17
_adapt@http://localhost:8069/web/static/src/js/core/dom.js:427:35
initAutoMoreMenu@http://localhost:8069/web/static/src/js/core/dom.js:362:9
start@http://localhost:8069/web/static/src/js/chrome/menu.js:73:9
OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/static/src/js/core/class.js:90:35
_widgetRenderAndInsert/<@http://localhost:8069/web/static/src/js/core/widget.js:399:20
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://localhost:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://localhost:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://localhost:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://localhost:8069/web/static/lib/jquery/jquery.js:3271:48
_widgetRenderAndInsert@http://localhost:8069/web/static/src/js/core/widget.js:393:33
prependTo@http://localhost:8069/web/static/src/js/core/widget.js:234:16
instanciate_menu_widgets/<@http://localhost:8069/web/static/src/js/chrome/web_client.js:125:23
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62
rpc/<@http://localhost:8069/web/static/src/js/services/ajax_service.js:16:17
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62
genericJsonRpc/<@http://localhost:8069/web/static/src/js/core/ajax.js:59:9
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49
done@http://localhost:8069/web/static/lib/jquery/jquery.js:9275:33
callback@http://localhost:8069/web/static/lib/jquery/jquery.js:9685:57

**Comment by zukunft** [comment]
> try
> sudo pip3 install - r requirement.txt from your odoo source folder.

You mean with the requirement**s**.txt file from https://github.com/odoo/odoo/blob/12.0/requirements.txt ?

**Comment by sswapnesh** [comment]
Yes

**Comment by zukunft** [comment]
After running sudo pip3 install -r requirements.txt the system returns

Successfully installed Babel-2.3.4 Jinja2-2.8.1 Mako-1.0.4 MarkupSafe-0.23 Pillow-4.0.0 Werkzeug-0.11.15 XlsxWriter-0.9.3 decorator-4.0.10 docutils-0.12 gevent-1.1.2 greenlet-0.4.10 html2text-2016.9.19 libsass-0.12.3 lxml-3.7.1 num2words-0.5.6 ofxparse-0.16 passlib-1.6.5 psutil-4.3.1 psycopg2-2.7.3.1 pydot-1.2.3 pyldap-2.4.28 pyparsing-2.1.10 pyserial-3.1.1 python-dateutil-2.5.3 pytz-2016.7 pyusb-1.0.0 qrcode-5.3 reportlab-3.3.0 requests-2.20.0 suds-jurko-0.6 vobject-0.9.3 xlrd-1.0.0

But the result has not changed.

**Comment by zukunft** [comment]
After a restart odoo is running. Thanks. 

Should `sudo pip3 install -r requirements.txt ` not be part of the odoo_install.sh script?

**Comment by Yenthe666** [comment]
@zukunft at some point the Odoo requirements file was not well managed and missing things. Because of that I diverted from the requirements.txt but at this point it is actually better than my own configured script. It's on my todo list to divert back to the requirements.txt (with a few extra packages), I just haven't gotten around to it yet.

**Comment by zukunft** [comment]
@Yenthe666 Thanks for the Info. The script helped my a lot to setup odoo. Actually I did a second installation using Docker (https://hub.docker.com/_/odoo/) on an univention server. This started with the first try, but after an update and a restart it is not (yet) starting any more.

**Comment by Yenthe666** [comment]
You're welcome, I'll keep the change in the back of my mind too. ;)

**Comment by pmutua** [comment]
If you are using `odoo version 12` then you should run  `sudo pip3 install -r requirements.txt` worked for me like magic : +1:  :100:

**Comment by bashirk** [comment]
> try
> sudo pip3 install - r requirement.txt from your odoo source folder.

This is what worked for me as well. Thanks :)

**Comment by maspamz** [comment]
> 
> 
> try
> sudo pip3 install - r requirement.txt from your odoo source folder.

thanks :D

**Comment by jeanpaul-mupagasi** [comment]
i'm using bitnami odoo 12 and i have the same issue, help me to fix this error?
