### ISSUE TITLE
Field permissions don't extend to computed fields

### ISSUE THREAD

**Issue by Altreus** [odoo/odoo#29444]
**Impacted versions**: 11.0

**Steps to reproduce**: 

1) Have a user with none of the following permissions:
```
- Inventory/User
	- Purchases/User
	- Purchases/Manager
	- Accounting & Finance/Billing
	- Other Extra Rights/Portal
```
2) Ask `res.partner` what fields the current user can see using `check_field_access_rights` with a falsey `fields` parameter. This returns a list of all fields the current user can read.
3) Pass this list as the `fields` parameter to an RPC request to `read`

**Current behavior**: An `AccessError` is thrown because of `(Document model: purchase.order)`. This is because the response from `check_field_access_rights` returns `purchase_order_count`

**Expected behavior**: `purchase_order_count` should have the same access rights as the relevant fields on `purchase.order`.

In general, computed fields should have the same access rights as the fields they use. As it stands, `check_field_access_rights` is useless to avoid attempting to read fields the user cannot access. I did not search for other instances where this "hidden access control" problem occurs.

**Comment by sswapnesh** [comment]
May be user has access to the field (`purchase_order_count`) but it does not allow to compute the function because of access rights (because of object `purchase.order`)

Ps: adding related group on `purchase_order_count` should be the solution

**Comment by pedrobaeza** [comment]
Yes, this seems a bit specific. Do you have other examples with the same problem?

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/36247

**Comment by mart-e** [comment]
Closing as got no update from Pedro's question.
I just tried the given scenario and got no error. Either it was already fixed, either missing some information. Also, it seems a bad idea to add the "Portal" group, this may be reason for things messed-up.
