### ISSUE TITLE
[11.0] payment matching is allowed even when a payment is full used in one invoice.

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#29446]
**Impacted versions: v11**

**Steps to reproduce:**
1. Set the multicurrency option
![image](https://user-images.githubusercontent.com/19410285/49834923-06fbd080-fd74-11e8-83b1-9d2075f5490b.png)

2. Set the rates for two different currencies
- company currency in 1 (currency 1)
![image](https://user-images.githubusercontent.com/19410285/49835140-afaa3000-fd74-11e8-9860-22f780765a77.png)
- the another with two different rates. The last one must be higher. (currency 2)
![image](https://user-images.githubusercontent.com/19410285/49835203-d8cac080-fd74-11e8-9e8b-e4c0c4a76d57.png)

3. Create one invoice with the currency 2 (different from the company currency) with a date to get the lower rate (0.5)
![image](https://user-images.githubusercontent.com/19410285/49835409-7aeaa880-fd75-11e8-9c23-13cad8aa967c.png)

4. Create another invoice with currency 1 (company's currency) don't care the date.
![image](https://user-images.githubusercontent.com/19410285/49835475-aa99b080-fd75-11e8-9d2b-f2a48e95daf0.png)

5. Create a partial payment in USD for the invoice in EUR. With a date to get the other rate (0.45).
![image](https://user-images.githubusercontent.com/19410285/49835792-b5087a00-fd76-11e8-84d9-312ed934eff2.png)

the residual and amount applied are correct because the rate is different
![image](https://user-images.githubusercontent.com/19410285/49835817-c3ef2c80-fd76-11e8-94cc-bb42ab5b0bdb.png)

**Current behavior:**
Even when the payment was a partial payment for an invoice and it was fully used. The payment is not fully reconciled
![image](https://user-images.githubusercontent.com/19410285/49835960-57c0f880-fd77-11e8-88fd-6b8309a046a8.png)
![image](https://user-images.githubusercontent.com/19410285/49835998-7626f400-fd77-11e8-8374-381ef08fe736.png)

The amount residual can be used in the invoice 2 or another invoice with USD as currency.
![image](https://user-images.githubusercontent.com/19410285/49836088-cbfb9c00-fd77-11e8-91a8-6694bf2b9f31.png)

**Expected behavior:**

The payment has to be full reconcile when the partial amount is applied.

**Video/Screenshot link (optional):**
https://youtu.be/SBPRUWjKUsw

**Comment by GavyMG** [comment]
cc @JulioSerna @hbto

**Comment by william-andre** [comment]
Closing since the patch has been merged

**Comment by hbto** [comment]
@william-andre issue is still valid

OPW#1917150

**Comment by william-andre** [comment]
@hbto  Yes, sorry. I didn't see the commit was only related to the issue but didn't solve it.

**Comment by kebeclibre** [comment]
After discussing with my peers, it is normal that the payment still appears in the reconciliation widget, since it is true that there is some amount that needs allocation and will be allocated with an exchange gain/loss entry at full reconciliation time.

**Comment by jga-odoo** [comment]
Hi @nim-odoo -- I just wanted to mention we still get support requests from Mexican customers regarding this issue; here is a recent one: https://www.odoo.com/web#id=2007799&action=333&active_id=49&model=project.task&view_type=form&menu_id=4720

**Comment by hbto** [comment]
This is related to https://github.com/odoo/odoo/pull/41512

**Comment by hbto** [comment]
Though this is a ticket for 11.0 this still valid for v12.0
