### ISSUE TITLE
[8.0] many2many field very slow to update because of loop

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#2945]
Version: odoo v8 branch
postgres 9.2 / Ubuntu

Problem:
Inserting into many2many is extremely slow because the ids are interated over. The more ids, the slower. Have not examined the core code, but it appears that either each record is loaded/ an insert statement is executed for each row, resulting in an exponentially slow insert depending on the number of ids in the tuple:   category_ids: [(6, 0, [1,2,3,4,5])] OR [(4, [1,2,3,4,5])]

The insert operation is what is slow. Unlinking existing ids is fast and works great when you use 6,0

How to reproduce:
1. Create a many2many field on any object. Say a multi category assignment on product.product.
(product_id, category_id)
1. As a test, measure the amount of time it takes to update many products without passing the many2many field.
2. Then, perform the same test except add the many2many field in vals with only 2 or 3 category ids each.

In my tests, updating a many2many field will double the amount of time it takes to normally update a record. If you have a couple many2many fields and each field contains 3 or more records, its painfully slow.

Expected:
Perhaps I am misunderstanding something. Why is it necessary to do a for loop over the ids and insert for each? In my particular case, I was forced to do a direct sql statement for a particular many2many field because it meant the difference of 2 minutes (sql) vs 2 hours for an ORM update of only 900 sku. SQL syntax supports multiple insert in a single statement which is exponentially faster. Example:

INSERT INTO table_name (col1, col2) VALUES (id1, id2), (id1, id3), (id1, id4)

**Comment by Yenthe666** [comment]
@xmo-odoo @odony and @gdgellatly could somebody give feedback or can we lock this one?

**Comment by gdgellatly** [comment]
@Yenthe666 funnily enough I saw a duplicate or near enough of this the other week, where it caused different issues other than performance so was resolved.  Personally I'd close it. I don't think there was an actual bug reported was there, more just a chat.

**Comment by Yenthe666** [comment]
Thanks for the feedback!

**Comment by harirock4499** [comment]
i need to send many2many field value to another many2many field 

thanks in advance
