### ISSUE TITLE
[12.0] Error when click on save as new template from invoice

### ISSUE THREAD

**Issue by vjd8866** [odoo/odoo#29527]
Impacted versions: 12.0

Steps to reproduce: click on send & print button from account.invoice and click on save as new template

Current behavior: trackback 

Expected behaviour: it should be save as template

Video/Screenshot link (optional):

![inv20180003 - odoo](https://user-images.githubusercontent.com/22145648/49957174-fe9ac580-ff2c-11e8-9354-7036ec73ffb3.gif)

![screenshot from 2018-12-13 23-09-20](https://user-images.githubusercontent.com/22145648/49957195-0eb2a500-ff2d-11e8-8d85-d566efea9970.png)

**Comment by sswapnesh** [comment]
This can be closed now.
