### ISSUE TITLE
If no results for search - return empty list or false not product.public.category()

### ISSUE THREAD

**Issue by unwasted** [odoo/odoo#29524]
https://github.com/odoo/odoo/blob/f3b341b6b9f1de120f33d96872f61e7be1bc3980/addons/website_sale/controllers/main.py#L273

That should fix it:
            'search_categories_ids': search_categories.ids if search_categories is not False else False,

**Comment by pedrobaeza** [comment]
Why is this a problem? It returns an empty list (`[]`), which is Falsy.

**Comment by unwasted** [comment]
It would be easier to expect list or false.

**Comment by unwasted** [comment]
BTW it returns an category object with no id's... Not a list!

**Comment by pedrobaeza** [comment]
Yeah, you are right about the returned value, but it's the same falsy result, so you should adapt your code to check anything evaluating as boolean.

Closing this as no real improvement nor issue.
