### ISSUE TITLE
[11.0] wrong calc for price_display in pos ui when tax included in price is set. 

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#29537]
Impacted versions: 11.0

Steps to reproduce:
1. on pos config set Tax included in price
2. on pos ui, add a product and a discount on product

Current behavior:
on export_for_printing => price_display = price

Expected behavior:
on export_for_printing: 
price_display =  be price without discount
price = discounted price

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please be more specific what is `export_for_printing`?

**Comment by joezsweet** [comment]
@pedrobaeza sure:

https://github.com/odoo/odoo/blob/069278b6520be7d57a9eebb4a77b3c4fb0a3f7a8/addons/point_of_sale/static/src/js/models.js#L1562

**Comment by pedrobaeza** [comment]
Is this still happening in latest source code?

**Comment by GSLabIt** [comment]
will double check and confirm

**Comment by GSLabIt** [comment]
@pedrobaeza it seems problem is still there ..

Boni Orange set as 4% vat included

Basically price before discount (€ 1.98/kg) is lost, it is need to recompute it taking in account discount applied. 

```
{
discount: 10
price: 1.78
price_display: 1.78
price_with_tax: 1.78
price_without_tax: 1.71
product_description: false
product_description_sale: false
product_id: 45
product_name: "Boni Oranges"
product_name_wrapped: ["Boni Oranges"]
quantity: 1
tax: 0.07
unit_name: "kg"
}
```

**Comment by Yenthe666** [comment]
@switch87 this might be for your interest too. I hope you don't mind me pinging you.

**Comment by switch87** [comment]
@yenthe666 no problem at all, please do. I like to be informed about everything wrong with point of sale.

**Comment by Yenthe666** [comment]
Awesome! A big thank you for keeping track of the issues and caring so much. Thanks, you're doing great :)

**Comment by switch87** [comment]
@GSLabIt You describe a variable in a function that has a wrong value, but can you give the functional impact of this issue? Preferable with a short video or screenshots.

**Comment by GSLabIt** [comment]
@switch87 problem i seen is sending receipt to fiscal printer and, for some clients, displaying values on customer display. 

As for EPSON FP series you need to pass to the printer the full price and the discounts (all of that must be positive values). When discount is applied for product, it's needed to send to FP (as the example above): 1,98 (full price), the amount discounted (0,198 if we consider 10% discount) all as abs values; the FP will take care of all computations. 

As for customer display, some clients would like to display to the client full price, discount and final price, so even there the full price is needed. 

Hope to be clear :)

**Comment by switch87** [comment]
@GSLabIt 

We do not support the fiscal printer format, this change should be done in the 3rd party addon for this purpose.

For the Customer display part, this has nothing to do with the function export_for_printing. The original price is available on the order lines, so the customization you want to do can be done without adapting this function.

**Comment by GSLabIt** [comment]
That's what we did.. for both cases
