### ISSUE TITLE
[12.0] Error from product when click on action compute price from BOM.

### ISSUE THREAD

**Issue by vjd8866** [odoo/odoo#29552]
Impacted versions: 12.0

Steps to reproduce: enable product variant and click on action Compute price from BOM 

Current behavior: traceback

Expected behavior: Not sure

Video/Screenshot link (optional):
![cons_25630 screw - odoo](https://user-images.githubusercontent.com/22145648/50041042-57c14100-0074-11e9-9353-269c475092aa.gif)

![screenshot-414843-12-0-8f4b98 runbot18 odoo com-2018 12 15-14-18-30](https://user-images.githubusercontent.com/22145648/50041050-69a2e400-0074-11e9-8a22-2841b46f4121.png)

**Comment by pedrobaeza** [comment]
This is an incorrect BoM definition, with a line with 0 quantity.

**Comment by sswapnesh** [comment]
True, But we can consider this as Bug and Handel situation better.

**Comment by pedrobaeza** [comment]
But I would handle this at BoM line level with a constraint avoiding to save a quantity <= 0

**Comment by sswapnesh** [comment]
Well [constraint](https://github.com/odoo/odoo/blob/12.0/addons/mrp/models/mrp_bom.py#L244) is already there to prevent negative quantities, So In this case we can return 0 If `product_qty > 0 `or Execute function form components with `product_qty > 0`

![download 5](https://user-images.githubusercontent.com/16624719/50056831-6ac53580-0188-11e9-9ae0-009d277b28ce.png)

Ps: Maybe we can get similar error here too (https://github.com/odoo/odoo/blob/12.0/addons/mrp/models/mrp_bom.py#L173)

**Comment by pedrobaeza** [comment]
OK, tagged for improving this in any of the proposed ways.

**Comment by sswapnesh** [comment]
Hello @pedrobaeza , 
I have checked code and this is not because of Zero quantity in Bom line.
Proposed fix at https://github.com/odoo/odoo/pull/29758

**Comment by sle-odoo** [comment]
Closing since the linked pr is merged.
