### ISSUE TITLE
[12] Error on invalid date format on date field input

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29551]
Impacted versions: 12.0

Steps to reproduce: Date Field --> Add Invalid Date (Wrong Format or some Character)

Current behavior: Error
![screenshot](https://user-images.githubusercontent.com/16624719/50040895-e1bbda80-0071-11e9-946f-c0b7c1ba5bf3.png)
![1screenshot](https://user-images.githubusercontent.com/16624719/50040896-e1bbda80-0071-11e9-9303-22d9c80cc5c5.png)

Expected behavior: Warning for Invalid or Make current date default in the Input

Video/Screenshot link (optional):

![peek 2018-12-15 14-04](https://user-images.githubusercontent.com/16624719/50040955-9c4bdd00-0072-11e9-97c9-c3078eca99a7.gif)

Ps: Have a look at https://github.com/odoo/odoo/issues/32995 (Expected Behavior Part) which adds pointer to the Issue.

**Comment by sswapnesh** [comment]
Ticket: 1974747

**Comment by Yenthe666** [comment]
@sswapnesh so you've got yourself an enterprise license to log the tickets hmm?

**Comment by sswapnesh** [comment]
> @sswapnesh so you've got yourself an enterprise license to log the tickets hmm?

Not really, Used someone else's and added me as Follower.

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/9ed9710b2b9ad685f4f09e42930e212d3cec71e5

**Comment by sswapnesh** [comment]
> Closed with [9ed9710](https://github.com/odoo/odoo/commit/9ed9710b2b9ad685f4f09e42930e212d3cec71e5)

Reproduced same again on latest build
http://537492-12-0-63e19c.runbot13.odoo.com/web?#id=&model=hr.leave&view_type=form&menu_id=236
![Screenshot from 2019-06-12 00-46-01](https://user-images.githubusercontent.com/16624719/59299915-79aa2200-8cab-11e9-8e4e-e29fefa036ee.png)

**Comment by Yenthe666** [comment]
@simongoffin can you recheck?

**Comment by msh-odoo** [comment]
@sswapnesh should be fixed with https://github.com/odoo/odoo/commit/fbbfa6ddcaf5cb8ef75672a73d1a928704484850

**Comment by aab-odoo** [comment]
Closed by https://github.com/odoo/odoo/pull/36211
