### ISSUE TITLE
bar code and fonts is not loaded in docker version of odoo12

### ISSUE THREAD

**Issue by masterdungeon** [odoo/odoo#29560]
Impacted versions: odoo12
Current behavior: bar code not printing.

**Comment by Yenthe666** [comment]
Did you install all required fonts and configured fonts to work?

**Comment by Yenthe666** [comment]
Hi,

Closing as there has been no feedback in months.

**Comment by masterdungeon** [comment]
Thanks for closing as the problem is solved with the help of fonts and correct version of wkhtmltopdf.

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!
