### ISSUE TITLE
Can't assign time to analytic account unless flagged for invoicing to a customer

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#2956]
Version: Master

Steps to reproduce:
- Create analytic account
- Set account type to Analytic Account
- Check the Timesheets box
- Can't leave pricelist_id or to_invoice selections empty

Alternate steps:
- Create analytic account
- Set account type to Analytic Account
- DON'T check the Timesheets box
- Create a detail line on a timesheet
- Can't assign time on the analytic account because the domain hides it

How can I track time spent on internal work?  I'm not going to invoice myself!

The problem starts here:

commit b42fcb7575092d9e354accc3295e878256f325b5
Author: cod-odoo
Date:   Wed Jun 25 17:40:27 2014 +0530

```
[IMP] hr_timesheet, project: various usability-related improvements

hr_timesheet: merged use_timesheets and invoice_on_timesheets fields on account.analytic.account
that basically tells the same thing (project using timesheets). Propagated this change in
the various views using it.
project: various improvements in views to ease the user experience.
```

**Comment by Yenthe666** [comment]
Hi @matt454357,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
