### ISSUE TITLE
[Functional Error] Debit note != in_refund

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#29579]
@jorenvo It happens so that the semantics encoded [in here](https://github.com/odoo/enterprise/blob/a3764384c225f0095d3302c511ab2ca33656f04b/l10n_co_edi/models/account_invoice.py#L111-L112) are plain wrong semantics.

`debit note != in_refund`, rather a debit note (`ND`, for nota debito) refers to an increase of an outgoing invoice, due to for example interest rates on overdue payments, adjustments due to negotiation or other surcharges that rise after issuing the original invoice.

It would rather be semantics of an `out_invoice` -> `out_debit_note`, whereas for credit notes, the semantic `out_invoice` -> `out_refund` is correct.

/cc @tebanep @gustavovalverde

**Comment by blaggacao** [comment]
@qdp-odoo What's the best approach to fix that problem for good? I think it's kind of a design limitation of the current invoice design. You probably would say: If you have to charge more (debit note), just generate a new invoice, but then a new invoice consume a sequence, which is not allowed by local legislation. A debit note is a modification of an existing invoice, just as a credit note (which can be configured to not to consume from the same sequence).

As a reference might serve the UBL2.0 definition of business documents which include `CreditNotes` and `DebitNotes` alongside `Invoices`

**Comment by gustavovalverde** [comment]
> rather a debit note (ND, for nota debito) refers to an increase of an outgoing invoice, due to for example interest rates on overdue payments

That's correct.

**Comment by aliencrash** [comment]
We have the same issue

**Comment by ren-odoo** [comment]
Hi 
This issue was fixed a couple of years ago: https://github.com/odoo/enterprise/blob/8f3bb2a78777af3cd9c22faaa5b5daf3f8efe414/l10n_co_edi/models/account_invoice.py#L624
