### ISSUE TITLE
Back Button doesn't behave properly

### ISSUE THREAD

**Issue by probabble** [odoo/odoo#29590]
Impacted versions:
12.0

Steps to reproduce:
Navigate to an app, then hit "Back". 

Current behavior:
The browser does not respond, or refreshes the current view.

Expected behavior:
The browser should return to the previous view.

Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Indeed, it is a known limitation but it is not something we currently support.
We use context variables so not something that is persistent. You will get the same issue when using direct links or opening in a different tab, you will lose some context or information and the app may misbehave.

**Comment by probabble** [comment]
@mart-e besides just being terrible UX design, this **is a bug** that`[ violates accessibility standards](https://www.w3.org/TR/IMPLEMENTING-UAAG20/#sc_315)`, whether or not Odoo SA thinks it's important.

If this isn't a high priority on the roadmap, Odoo has lost its way. cc @jam-odoo

**Comment by probabble** [comment]
Also, @mart-e : where in the Odoo documentation does it say that the Back button is unsupported? Or is this just your opinion?

**Comment by mart-e** [comment]
We have a breadcrumb when you navigate through the app, if you want to go back, you can use it to go back to the previous page.
When you hit a direct link or use the back button, we do our best based on the information contained in the URL but, if the page you are on, needs some information from the execution context (like the actions you were previously doing), it will not succeed to render it properly but for most views, that is not issue.

**Comment by probabble** [comment]
@mart-e this issue shouldn't be "Closed". The back button doesn't work, and it should work, so this issue should be "Open" and undergoing triage.... @jam-odoo

**Comment by pedrobaeza** [comment]
@probabble this is properly closed as this won't be fixed. You try to change whole current architecture for this to work in the way you think it should work, but that's not possible, and less in current stable versions. A whole redesign would be needed for completing this for new versions, and this will made more unusable or even problematic in other terms (recreate all of this via URL may disclose some information, URL length can be longer than the browser admits, etc).

Any way, this doesn't mean back buttons doesn't serve in general. For most parts, you can go back pressing the button. The exceptions are on the actions that require some contexts as said by Martin.

Then better focus your energy in proposing alternatives to the use case for what you need the back button (even here) than to rant about something not possible.

**Comment by probabble** [comment]
The back button is a primary feature of the browser and you will never convince me that it’s acceptable to break it.

If this is standard Odoo behavior it should be documented as such. Where does Odoo officially admit to breaking the back button?

**Comment by pedrobaeza** [comment]
And what do you try to probe of that specific thing not being documented?

As said, my advise is to focus on the real need instead of wasting energy. If you want this documented, you can propose a PR. If you have a specific problem that implies the back button, expose it here and people will be able to propose alternative solutions.

**Comment by probabble** [comment]
The “real need” is to provide a UX that conforms to expectations of the modern web. The back button is a basic core of that expectation. New users will likely feel distrust of the product when their expectation is not met.

Which leaves two options: 
1) meet user expectation 
2) modify user expectation

I would argue that the right answer is to meet the expectations, even if it requires migrating to a new front end framework that supports it.

A product that intentionally violates this expectation should document why and the available workarounds. You claim that breadcrumb links provide this workaround. Do you expect users to find this closed issue on github when they wonder why their ERP isn’t working like they expect it to?

The option of “close issue, shoot down person who filed issue, pretend everything is ok” is the worst approach.

**Comment by switch87** [comment]
@probabble many modern web applications behave badly or do not react at all when pressing the back button. 2 examples that come up my mind right away are PayPal and many of the big webshops in the checkout procedure. Sometimes it is just impossible to go back and therefore it's not desirable to have a proper working back button.

**Comment by probabble** [comment]
I am not convinced by this characterization of "impossible". Web applications that are "behaving badly" should be fixed to behave better.

**Comment by Yenthe666** [comment]
Don't underestimate the complexity of what you're asking either. Odoo has breadcrumbs, smart buttons and shortcut keys, plenty of ways to get around the application.

**Comment by probabble** [comment]
I'm amazed that the consensus here is that it's okay to have a broken back button. Amazed in a ... not great way.

**Comment by josselex** [comment]
> I'm amazed that the consensus here is that it's okay to have a broken back button. Amazed in a ... not great way.

This is also amzing to me.
The handling of back buttons is in general what differentiates a good web app (most from google etc, ...)

@Yenthe666 
> Don't underestimate the complexity of what you're asking either. Odoo has breadcrumbs, smart buttons and shortcut keys, plenty of ways to get around the application.

Yes. But the back button should always just take you back to the site you where before. And this is actually quite simple. And this is possible. Also in a complex environment.

@mart-e 
Can you please reopen the issue? At least to see that it is an issue that should be still discussed about and is important to many people?

**Comment by mart-e** [comment]
@josselex this issue is that not every contextual information is present in the URL. You can use the back button but depending on the page you are at, you may have some missing information.
I have closed the issue because we have already discussed this with the @odoo/rd-framework-js and this is a known limitation unfortunatly. Sorry but we do not plan to change at the moment so I prefer to leave this issue closed.
We may change this in the future but nothing I can guarantee.

If you have a patch for some specific pages, feel free to open a PR and we will review it.

**Comment by sdegueldre** [comment]
We've been using the history API for a while now and using the back button should work in most contexts without a triggering a page reload. If you have a specific case in mind where it doesn't work feel free to open a ticket, but in those cases it is likely that it doesn't work because some actions that the user has taken have made the previous state invalid. This issue as originally reported is now fixed. Navigate to an app, hit back, the view is updated correctly in almost all cases.

**Comment by blackoakit** [comment]
This is still the problem.
I am using Odo 16CE for my clients now and all of them have this issue

**Comment by sdegueldre** [comment]
> This is still the problem. I am using Odo 16CE for my clients now and all of them have this issue

I cannot reproduce the issue in version 16CE. Please note that this issue was originally opened for version 12.0, for which this was not supported and not intended to be. If you are encountering this issue in a more recent and supported version please open a new issue.
