### ISSUE TITLE
Backend HTML editor > search fontawesome icon

### ISSUE THREAD

**Issue by Moka-Tourisme** [odoo/odoo#29618]
**Impacted versions:**
12.0

**Steps to reproduce:**
When backend html editor is use (notes, projects, ...) and you want to add a font awesome icon, tying to search in the search field, then you get an error

**Current behavior:**
Error box :
```javascript
Uncaught TypeError: Cannot read property 'then' of undefined
XXX/web/content/1540-0fdee5c/web_editor.assets_editor.js:347
Retraçage :
TypeError: Cannot read property 'then' of undefined
    at Class._onSearchInput (XXX/web/content/1540-0fdee5c/web_editor.assets_editor.js:347:946)
    at later (XXX/web/content/1576-55a0cb8/web.assets_common.js:46:255)
```

**Expected behavior:**

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/45973721/50164730-c2c47f00-02e3-11e9-8c0c-01220a8caa7f.png)

**Comment by Yenthe666** [comment]
Hi guys,

I just faced this one too and as it is also in V12 enterprise I made an official ticket at Odoo too.
OPW 1919549

**Comment by Yenthe666** [comment]
It has been fixed in https://github.com/odoo/odoo/commit/b87879c1f64c91a925f4814a03687d717791346c (https://github.com/odoo/odoo/pull/30077) in saas11.3 and should be in V12 soon.
