### ISSUE TITLE
Whole packages transfersd does not work in Odoo 11

### ISSUE THREAD

**Issue by stesifrancesco** [odoo/odoo#29622]
Impacted versions: 11

Steps to reproduce: I try to follow this tutorial:
https://www.odoo.com/documentation/user/10.0/inventory/settings/products/packages.html
It works fine in Odoo 10, and also in Odoo 12 (without click Mark as To Do) but no in Odoo 11

Current behavior:
Package session  is shown but you do not see the button "Add a Item"

Expected behavior:
I expect that if I choose "internal trasnfer" and "allow moving pack" is checked I can add Packages directly inside package section

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/17119418/50170856-2b662880-02f1-11e9-9c5b-20ada51c2840.png)

![image](https://user-images.githubusercontent.com/17119418/50170893-3de06200-02f1-11e9-827e-8bbae10522a6.png)

**Comment by pedrobaeza** [comment]
AFAIK, you have to click on "Put in Pack" button for creating the pack, so I don't see a real issue here. Can you please confirm?

**Comment by stesifrancesco** [comment]
Hi, thanks for your answer.
What if a user whant to move a specific package ?
In Odoo 10 and 12 I can chosse directly a package and move it from location 1 to location 2.
Why I cant do the same in Odoo 11 ?
Why I do not have the button "Add an Item" here:
![immagine](https://user-images.githubusercontent.com/17119418/50308218-e847b900-049a-11e9-9946-24e23fa8fa13.png)

Thanks again 

Francesco

**Comment by omarbros** [comment]
Hello I am also experiencing this issue, apparently this functionality has been disabled for some reason:
[](https://www.odoo.com/forum/help-1/question/package-and-barcodes-110672)

@stesifrancesco Have you found a work around?

**Comment by stesifrancesco** [comment]
@omarbros sorry.....no...I switched to version 12, where I have other problems but not this one.

**Comment by sle-odoo** [comment]
This is sadly a limitation of v11.
Regards
