### ISSUE TITLE
[12.0] Wrong days when creating leave from calendar view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29625]
Impacted versions: 12.0

Steps to reproduce: 
![screenshot](https://user-images.githubusercontent.com/16624719/50175228-40a77b00-0322-11e9-9ffd-c1bad3d9fb67.png)

Current behavior: 0.75 Days
![screenshot](https://user-images.githubusercontent.com/16624719/50175272-5b79ef80-0322-11e9-95dd-a2c0844a76c3.png)

Expected behavior: 1 Days
![screenshot](https://user-images.githubusercontent.com/16624719/50175324-7b111800-0322-11e9-820a-aa805ad15370.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Maybe it's because time zones...

**Comment by sswapnesh** [comment]
Its is because of timezone and works well if timezone is set correctly.
https://github.com/odoo/odoo/blob/12.0/addons/resource/models/resource_mixin.py#L70

**Comment by alexey-pelykh** [comment]
Not sure if related to #30666, also may be related to working times, since creating from calendar always uses 7am/7pm

**Comment by sswapnesh** [comment]
Did you tried after setting up correct timezone? (I have not checked your case yet but that solved my issue)

**Comment by alexey-pelykh** [comment]
It seems to me that I've completely overlooked the origin of the issue, though I'm not sure if my case is related to timezones, yet it's possible.
