### ISSUE TITLE
Bad menu position on small sized screens

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#29631]
Impacted versions: 
Odoo v.12

Steps to reproduce: 
1. Install "Sales" application
2. Enable french language
3. Select "Sales" application in main menu

Current behavior:
When display "Sales" appli on small sized screen like iPhone X the menu is invisible

Expected behavior:
The menu must be visible on screens of all sizes

Video/Screenshot link (optional):
![odoo_menu_ipad_pro](https://user-images.githubusercontent.com/9844780/50187644-fffa3280-031e-11e9-866d-837acd0e11e8.JPG)
![odoo_menu_iphone_x](https://user-images.githubusercontent.com/9844780/50187646-025c8c80-031f-11e9-9e0e-6698e21cff84.JPG)

Video:
https://1drv.ms/v/s!Ar21jmjw_wElsgJGKroE6lY0y142

**Comment by pedrobaeza** [comment]
This is already solved in #27247, but it's not being attended for now. @qsm-odoo do you think there's a chance of this being merged for fixing the problem?

**Comment by mart-e** [comment]
Sorry but mobile view is not supported on community version.
