### ISSUE TITLE
[11.0] [12.0] Color in calendar

### ISSUE THREAD

**Issue by aitorbouzas** [odoo/odoo#29648]
Impacted versions:
11.0 and 12.0

Steps to reproduce:
Add `color="field"` attribute to a calendar view. The `field` should be something containing a CSS color code.

Current behavior:
It doesn't show correct color.

Expected behavior:
It should show the color contained in the value of the `field`. This part of the JS code shows that the CSS is copied from the `_eventRender` result to the parent tag:
[https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/calendar/calendar_renderer.js#L389](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/calendar/calendar_renderer.js#L389)
But it doesn't copy the `background-color` attribute shown here:
[https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/xml/web_calendar.xml#L17](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/xml/web_calendar.xml#L17)
The value of the `background-color` is patched by the `getColor` method:
[https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/calendar/calendar_renderer.js#L267](https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/calendar/calendar_renderer.js#L267)

So, with the current behaviour we'll get all the events in the same color in the calendar (even though they get different CSS color codes) and the Color Map shown at the right of will show correct value<->color relation.

Adding:
`
                element.attr("style", $render.attr("style"));
`
To `eventRender` method will show the correct color here, but with a very ugly default-blue border color for every event.

**Comment by aitorbouzas** [comment]
@Yenthe666 any news with this?

**Comment by Yenthe666** [comment]
Hmm sorry no update. @JKE-be can anybody from your co-workers check this maybe?

**Comment by JKE-be** [comment]
@mge-odoo Our new calendar expert

**Comment by aitorbouzas** [comment]
Ping @mge-odoo

**Comment by aitorbouzas** [comment]
Any news about this?

**Comment by Yenthe666** [comment]
@mge-odoo could you please be so kind to check this?

**Comment by mge-odoo** [comment]
Hi guys :) I apologize on behalf of my fellow colleague @JKE-be who made a silly joke, I have nothing to do with the calendar view. Maybe @aab-odoo could take a look?

**Comment by Yenthe666** [comment]
You trolls! :-)

**Comment by aab-odoo** [comment]
Hello @aitorbouzas 

According to the [documentation](https://www.odoo.com/documentation/11.0/reference/views.html#calendar):

> color
name of a record field to use for color segmentation. Records in the same color segment are allocated the same highlight color in the calendar, colors are allocated semi-randomly. Displayed the display_name/avatar of the visible record in the sidebar

The given field shouldn't encode some sort of CSS color, but the colors (generated by the JS framework) are allocated to records according to their value for that specific field. I just checked and it seems to work as expected.

Regards
