### ISSUE TITLE
[11.0]Partial reconcile on  liquidity lines should not be available 

### ISSUE THREAD

**Issue by qpeyramale** [odoo/odoo#29654]
Impacted versions: 11.0

Steps to reproduce:
- Create a vendor payment of 100€
- Create a bank statement line with an amount lower than the payment
- Open bank reconciliation view
- Reconcile the bank statement line with the blue line of 100€, the triangle for partial reconcile appear.

Current behavior:
If you click the triangle, you can reconcile this payment with the statement line but it becomes unbalanced.

Expected behavior:
The triangle should not appear.

![image](https://user-images.githubusercontent.com/7935472/50231769-d6d5b280-03af-11e9-83ed-ead023ea5027.png)

I think the issue come from here, where the `already_paid` field is not queried properly due to lack of parenthesis :
https://github.com/odoo/odoo/commit/5450c5c3f7c003de460fed253cf8b8178b5ebdec?_pjax=%23js-repo-pjax-container#diff-683665f272a1fb6387202066f05fe42eR379

Thanks

**Comment by pedrobaeza** [comment]
Fixed in 4fde77393878782b8c480887392e9a05c719065d

**Comment by qdp-odoo** [comment]
thanks @pedrobaeza

**Comment by qpeyramale** [comment]
Thank you everyone
