### ISSUE TITLE
Feature request: t-field with dynamic field_name resolving

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#29658]
Over here a `t-field` + `t-field-record`/`t-field-name` would be great
https://github.com/odoo/odoo/blob/9b6073c3ea6264f59fb11e6f797f4fff200c3d5d/odoo/addons/base/models/qweb.py#L1295

since right now following is not possible
```
<t t-set="variable" t-value="record.some_func()"/>
<span t-field="record[variable]"/>
```

**Comment by gdgellatly** [comment]
What's wrong with t-esc? I don't really get the example. Wouldn't
t-esc="record[record.some_func()]" do the same?

**Comment by alexey-pelykh** [comment]
@gdgellatly `t-esc` won't format the value properly. E.g. if referenced field is m2o, it will print `model name, id` instead of name

**Comment by Yenthe666** [comment]
I don't see the problem either honestly. You can use a `t-esc` to display values and you can call functions to do more advanced operations. The last comment you gave, about the `model name, id` can also be solved by a `t-esc` for the right value or by passing it through a function and resulting your desired behaviour?

**Comment by alexey-pelykh** [comment]
@Yenthe666 exactly 👍 Especially in case "own function" is calling default converter, and not custom logic

**Comment by pedrobaeza** [comment]
You can also use `t-esc` with `widget` option for auto-formatting. That wishlist is not going to come as too broad and opened for problems, so I'm going to close it.
