### ISSUE TITLE
Odoo server sudden stop or loading issue due to ir attachment

### ISSUE THREAD

**Issue by prakashjain** [odoo/odoo#29660]
Impacted versions:
Odoo 9
Steps to reproduce:
Created binary field in odoo 9 and data stored in filestore. (attachment=True)
Current behavior:
Sometime log file below query is running at that time server is very slow and user unable to login system or server time out.
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
Expected behavior:
I would like to skip above query so user can login to system. The above query automatic run default odoo core module. Please let me know how to avoid to run the above query or skip? the above query run on which condition?
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

Odoo 9 is no longer supported and Github is a place for reporting bugs, not asking questions.
Please ask this on the official help forum at help.odoo.com

Regards,
Yenthe
