### ISSUE TITLE
[12.0][hr_holidays] Leaves Left counts outdated leaves

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#29665]
**Impacted versions:**

12.0

**Steps to reproduce:**

Create Legal Leaves for 2017 and 2016, assign days for those leaves.
![image](https://user-images.githubusercontent.com/5862658/50276333-02a17880-0442-11e9-8344-b25c68f85acc.png)
![image](https://user-images.githubusercontent.com/5862658/50276355-10ef9480-0442-11e9-9c69-71417e240c1a.png)

**Current behavior:**

Leaves Left information in employee form counts outdated leaves.
![image](https://user-images.githubusercontent.com/5862658/50276459-45635080-0442-11e9-80a5-fd75e55e7974.png)

**Expected behavior:**

20 days left, do not show days that cannot be used because leave type ended

**Comment by pedrobaeza** [comment]
AFAIK, on allocations, there are no applicable dates:

![seleccion_003](https://user-images.githubusercontent.com/7165771/50277069-c8d17180-0443-11e9-811b-14bfb1d283ce.png)

If you put "Legal leaves 2018", it's for your reference, but there's no way to apply it only on 2018.

**Comment by grzekru** [comment]
User is unable to use allocated leaves from 2016 and 2017 so i think that "60 Leaves Left" information is misleading.

**Comment by pedrobaeza** [comment]
This is a non existing feature on Odoo: if you don't want that a user uses the allocation from "Legal leaves 2016" in 2017, you have to add custom code for that, and then adapt the smart-button to that situation, which is not the current one. For now, as this is possible, the current behavior is correct.

Take into account that other companies simply create a holidays type called "Legal leaves", without year in its name, and add and subtract there all years leaves/allocations. If you are creating separated types for each year and want to give that meaning, then when the year has past, you have to de-allocate remaining leaves for the previous type, or as said, expand the behavior through a custom module.

Closing then as no issue.
