### ISSUE TITLE
[12][hr_holidays] Server Error when user without connected employee try to create leave

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#29666]
Impacted versions:

12

Steps to reproduce:

1. Create new user
2. Log as new user
3. Go to leaves
4. Click on calendar

Current behavior:

>   File "/home/gk/Software/odoo12/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/gk/Software/odoo12/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/gk/Software/odoo12/odoo/models.py", line 5430, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/gk/Software/odoo12/odoo/models.py", line 5283, in _onchange_eval
    method_res = method(self)
  File "/home/gk/Software/odoo12/addons/hr_holidays/models/hr_leave.py", line 325, in _onchange_type
    self.employee_id = self.env.user.employee_ids[0].id
  File "/home/gk/Software/odoo12/odoo/models.py", line 5053, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range

Expected behavior:

No server error, maybe alert in this place

**Comment by pedrobaeza** [comment]
Well, indeed this can be improved, but an employee is a requirement in this case, so it can be acceptable.

The code can be changed to:
```python
self.employee_id = self.env.user.employee_ids[:1].id
```
for total compatibility without error.

@tivisse can you consider this change?

**Comment by Yenthe666** [comment]
@pedrobaeza I'd go for a PR right away 😉

**Comment by sswapnesh** [comment]
@pedrobaeza 
> The code can be changed to:

or Maybe like this

`self.employee_id = self.env.user.employee_ids and self.env.user.employee_ids[0].id or False`

**Comment by sswapnesh** [comment]
This happens when current user is not linked to any Employee so here` self.env.user.employee_ids` will be `hr.employee()` which will generate same error.

**Comment by pedrobaeza** [comment]
No, it won't generate any. Check it. `.id` of an empty recordset is `False`.

**Comment by sswapnesh** [comment]
Sorry for this,  Honestly I was not aware of this.

**Comment by sswapnesh** [comment]
Got this error too with same steps at https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L271


![screenshot](https://user-images.githubusercontent.com/16624719/50301487-7c228080-04ad-11e9-86be-d5b8ac9575aa.png)

**Comment by pedrobaeza** [comment]
Another one that should be protected against 0 records, and there's another one in the next line, using `[-1]`.

**Comment by sswapnesh** [comment]
> @pedrobaeza I'd go for a PR right away

@Yenthe666 

and We have to prevent same here too (addons/hr_holidays/models/hr_leave.py", line 335, in _onchange_type)
![screenshot](https://user-images.githubusercontent.com/16624719/50303265-85621c00-04b2-11e9-9478-5dfb20905ba6.png)
 

self.department_id = self.env.user.employee_ids[:1].department_id.id

**Comment by sswapnesh** [comment]
or use
`employee = self.env.user.employee_ids[:1]` on the top and use that variable in method

**Comment by Yenthe666** [comment]
Haha I love your brainstorms / idea sharing. If you both make a PR we can so who wins hehehe.

**Comment by sswapnesh** [comment]
I would do this
![screenshot from 2018-12-21 00-23-11](https://user-images.githubusercontent.com/16624719/50304686-a167bc80-04b6-11e9-9497-fec1cb8b316e.png)


Ps: Still we have to check for https://github.com/odoo/odoo/issues/29666#issuecomment-449081447 (Maybe new Issue/Pr for that)

**Comment by sswapnesh** [comment]
> Got this error too with same steps at https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L271
> 
> ![screenshot](https://user-images.githubusercontent.com/16624719/50301487-7c228080-04ad-11e9-86be-d5b8ac9575aa.png)

(Not tested with all use cases yet but seems working without error)

Use` attendances[:1]`  and `attendances[-1:] `respectively
![screenshot from 2018-12-21 00-28-43](https://user-images.githubusercontent.com/16624719/50304944-6914ae00-04b7-11e9-8bf6-534c87e36ab6.png)

**Comment by sswapnesh** [comment]
This has been solved in https://github.com/odoo/odoo/pull/29773

**Comment by Yenthe666** [comment]
Yep, at https://github.com/odoo/odoo/commit/3b30f7ad05295ac47aca19b4fdab4fee513adb62 to be exact. Thanks!
