### ISSUE TITLE
Changing default_code in Multi-Company environment

### ISSUE THREAD

**Issue by qndi** [odoo/odoo#29686]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by qndi** [comment]
Impacted versions: v11

Steps to reproduce:
Share products across companies
Create Stock-product X1 in company A
Create inventory for product X1
With User in company B change default_code of Product X1


Current behavior:
Error due to multi-company Rule of inventory line:
[Der gewünschte Vorgang kann aufgrund von Sicherheitsbeschränkungen nicht ausgeführt werden. Bitte kontaktieren Sie den Systemadministrator.
(Dokumenten Typ: Inventory Line, Vorgang: write)

Expected behavior:
no error

Proposed Solution:
in stock_inventory line use "compute_sudo" for product_code:

    product_code = fields.Char(
        'Product Code', related='product_id.default_code', store=True, compute_sudo=True)

**Comment by sle-odoo** [comment]
Hello,
It was fixed.

Regards
