### ISSUE TITLE
[12] Date ( request_date_from) should be required in leave

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29697]
Impacted versions: 12

Runbot:http://417132-12-0-ddc5cc.runbot17.odoo.com/web?debug#id=&model=hr.leave&view_type=form&menu_id=233

Steps to reproduce: Create leave without adding start date
![screenshot](https://user-images.githubusercontent.com/16624719/50302650-afb2da00-04b0-11e9-80b0-1c2975df52b5.png)

Current behavior:
![screenshot](https://user-images.githubusercontent.com/16624719/50302499-492dbc00-04b0-11e9-92d7-1fab8b127414.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by tivisse** [comment]
Hi @sswapnesh 

This is fixed. Thanks for the feedback.
