### ISSUE TITLE
[12.0] Bar chart: corrupted axis with dates

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#29695]
Impacted versions:
Odoo 12.0-20181217

Steps to reproduce:
Get graph with wide range of data

Current behavior:
Date is improperly sorted

Expected behavior:
Date is properly sorted

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/345102/50300562-7321b700-048d-11e9-85f5-aab09f1582f0.png)

**Comment by Yenthe666** [comment]
@alexey-pelykh could you maybe provide an easy way to reproduce this?

**Comment by alexey-pelykh** [comment]
@Yenthe666 I've tested on recent Odoo 12.0-20190805 version and it does not reproduce at least after couple of tries

**Comment by Yenthe666** [comment]
Sweet! I hope you dont mind me closing it off then. If you can reproduce it then just ping me again with a way and we'll reopen :)
