### ISSUE TITLE
Invoices created from the Point of Sale have lines with wrong taxes

### ISSUE THREAD

**Issue by JVegaB** [odoo/odoo#29696]
Impacted versions:
Odoo 12.0

Steps to reproduce:
  - Create a product with customer taxes and other without them.
  - Configure a point of sale to create invoices and start a session.
  - Create an order with a customer and select the created products.
  - Pay it and create the invoice.

Current behavior:
 - Each line must have taxes only if its product has otherwise it shouldn't.

Expected behavior:
 - All lines have taxes and are chared with them.

Video/Screenshot link (optional):
[Order](https://user-images.githubusercontent.com/34751857/50300985-aba0a100-044b-11e9-83d4-494ed0bf0a0e.png) and [invoice](https://user-images.githubusercontent.com/34751857/50301011-b8bd9000-044b-11e9-852c-c84d9754dad9.png)

**Comment by switch87** [comment]
closed by: https://github.com/odoo/odoo/pull/33059
