### ISSUE TITLE
[12.0] Widget issue in mozilla firefox

### ISSUE THREAD

**Issue by vjd8866** [odoo/odoo#29700]
Impacted versions: 12.0

Steps to reproduce: Open expenses from firefox click on attach document

Current behavior: not working in firefox

Expected behavior: the file selector should be a open

Video/Screenshot link (optional):
![screenshot 1](https://user-images.githubusercontent.com/22145648/50329949-4c13c580-051f-11e9-9c88-a0dd490ea0e6.png)

**Comment by switch87** [comment]
duplicate of #29698
