### ISSUE TITLE
Employee can not schedule an activity in his own Appraisals

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#29713]
### Impacted versions:

11.0

### Steps to reproduce:

1. Create a employee with user, this will have the basic permissions: employee and project use (NOTE: This user has not avance permissions for Appraisals)

   ![image](https://user-images.githubusercontent.com/7593953/50353822-2ccd6600-0528-11e9-8869-e3ff0a7610e0.png)
 
2. With admin user create an appraisal for this employee and sent it.

3. With employee user created on (1) go to the appraisal menu and click in the kanban card of the appraisal.

4. From the apprisal form view try to create an activity

### Current behavior:

Is throwing permissions error and do not let me create the activity. here is the screenshot

![image](https://user-images.githubusercontent.com/7593953/50354034-df9dc400-0528-11e9-9b20-c3d58f6a04a5.png)

### Expected behavior:

The employee could be able to schedule an activity in his own appraisal evaluations records.
You can see this example video https://youtu.be/pja-XW2ecf8

**Comment by zaoral** [comment]
opw-1920037

**Comment by alaodoo** [comment]
Hi zaoral,
we have created a feedback about the issue for future development.
Ref: #1920631
