### ISSUE TITLE
Datetime fields on filters and wizards don't consider user time zone

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#2972]
Let me explain the whole picture first, so that you can recommend the best
solution...

A company doing everything in one time zone (as most odoo customers...)
Let's say it is GMT-6:00
A cashier entering POS orders (or HR time sheets, or any document that
relies on datetime fields)
A manager in same time zone, checking POS sales reports
POS order report, with a filter "Today" with domain
(date_order,"=",time.strftime('%Y-%m-%d')

On 09/30/14 18:01 local time, cashier enters a POS order A for $10.oo.  It is recorded as 10/01/14 00:01, just as expected. 
On 10/01/14  10:00 local time, cashier enters POS order B for $7.oo, (recorded as 10/01/14 16:00) 
On 10/01/14  17:59 local time, Manager tries to filter current orders for the day.  He will get BOTH order A and order B, as currently on expression.py the system will convert expression to range 10/01/14 00:00:00   to 10/01/14:23:59:59, but expressed on UTC time !! 
On 10/01/14  18:01 local time, cashier enters POS order C for $5.oo, (recorded as 10/02/14 00:01) 
The Manager goes to IT complaining that he is getting an entry from yesterday on today's sale report, but when he tries to show it to the IT guy, it is already 18:05 local time, so now the report is showing only order C, as expression.py will get "10/02/14" and will convert it to 10/02/14 00:00:00  to  10/02/14 23:59:59 UTC times...  
"Fixing" the report to use context_today() instead of time.strftime, you will solve the second problem, but the first one will remain.

Filtering is NOT working, even on Point of Sales "Order Analysis", just create records on year bundaries and you will see the errors.

Reporting is NOT working either, just try to get a correct Point of Sale "Sale Details", but do the testing using a timezone far from UTC...

**Comment by beledouxdenis** [comment]
Closed with 81a3f5665154bc3c864d5910d50a44496b4fc295.
