### ISSUE TITLE
8.0 Point of sale - token  increase problem

### ISSUE THREAD

**Issue by vilder** [odoo/odoo#2973]
When you press (   -   ) token increases without limits

![odoo-pos](https://cloud.githubusercontent.com/assets/7828591/4558766/b756c76c-4ee3-11e4-8b9c-2e02e0882585.PNG)

**Comment by Yenthe666** [comment]
Hi @vilder,

Thank you for your report.
This is actually the desired behaviour and wanted. Everytime you press the "-" sign it'll kill the session (with an id) and create a new one. This is what you see here.

Regards,
Yenthe
