### ISSUE TITLE
Not able to cancel Sale Order!

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#29741]
Impacted versions:
Odoo 12.0

Steps to reproduce:
1> Create SO and try to cancel it.

Got the error!
  File "/home/bista/workspace/odoo-12/addons/purchase_requisition/models/purchase_requisition.py", line 492, in _get_upstream_documents_and_responsibles
    return [(requisition_line.requisition_id, requisition_line.requisition_id.user_id, visited) for requisition_line in self.requisition_line_ids if requisition_line.state not in ('done', 'cancel')]
  File "/home/bista/workspace/odoo-12/addons/purchase_requisition/models/purchase_requisition.py", line 492, in <listcomp>
    return [(requisition_line.requisition_id, requisition_line.requisition_id.user_id, visited) for requisition_line in self.requisition_line_ids if requisition_line.state not in ('done', 'cancel')]
AttributeError: 'purchase.requisition.line' object has no attribute 'state'

Current behavior:
Get error when try to cancel SO.

Expected behavior:
Requisition line have not state.

Video/Screenshot link (optional):
![so cancel](https://user-images.githubusercontent.com/8874012/50422782-6c22ec00-0873-11e9-9d71-e6e066107c4a.png)

**Comment by sswapnesh** [comment]
Duplicate of #28980 and Solved in https://github.com/odoo/odoo/commit/595209a3e81506f455a308390c6529a6fc32079e PR #29715
