### ISSUE TITLE
[8.0] Missing menu to handle invoicing on SO 

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#2975]
I cannot see the menu Order lines to invoice under Sales / Invoicing whereas I have activated the option in Settings / Configuration / Sales / Generate invoices based on so lines

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
