### ISSUE TITLE
[12.0] hr_holidays: custom hours are selected as UTC w/o user notification

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#29751]
* Custom hours could've been implemented by using `date_from`/`date_to` fields directly
* For user it's unclear that custom hours selection is UTC (and it's not proper to ask regular user to calculate time in UTC)

**Comment by RomainLibert** [comment]
For the custom hours in UTC, it is indeed not intuitive to take leaves in UTC, I'll see if something can be done about this in stable
For the custom hours bit see (https://github.com/odoo/odoo/issues/29750)

**Comment by mart-e** [comment]
Closing as answered by Romain
