### ISSUE TITLE
[12.0] hr_holidays: leave request form

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#29752]
Why can't we do like this:
![image](https://user-images.githubusercontent.com/345102/50446601-71894080-091e-11e9-914e-89345b0741bc.png)

#29750 and #29751 are related

**Comment by alexey-pelykh** [comment]
Addressed via OCA https://github.com/OCA/hr/pull/547

**Comment by mart-e** [comment]
Hello,
Sorry but as explained by Romain on #29750 this is not the direction we want to go. We want to keep the leave requests simple and easy.
