### ISSUE TITLE
[12] Scheduled date should be required on Replenish wizard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29778]
Impacted versions: 12

Steps to reproduce: 
![screenshot](https://user-images.githubusercontent.com/16624719/50488926-e21d8380-0a2a-11e9-848b-5483750d53d5.png)

Current behavior: 
![screenshot](https://user-images.githubusercontent.com/16624719/50488945-fb263480-0a2a-11e9-8d85-bd3e43f2fd43.png)

Expected behavior: No error and create MO/PO based on Routes 

Video/Screenshot link (optional):

Ps: I can dot PR (making date required) but not sure If scheduled date can be handled from another place too

**Comment by Yenthe666** [comment]
@sswapnesh I'd just go for a PR, easy fix and it atleast resolves this one.

**Comment by sswapnesh** [comment]
ASFAIK, We can prevent this by

- Making date required in wizard

or 

- Set default date if not set

**Comment by sswapnesh** [comment]
Better to add
` or datetime.datetime.now()` at 
 https://github.com/odoo/odoo/blob/12.0/addons/stock/wizard/product_replenish.py#L75

instead of 
> Making date required in wizard

May be this will not be accepted as Stable Policy
