### ISSUE TITLE
[12] Wrong number Picking Late Picking records from Inventory dashboard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29777]
Impacted versions: 12

Steps to reproduce: 
![screenshot](https://user-images.githubusercontent.com/16624719/50488631-7d155e00-0a29-11e9-9121-bf3a88e6d3fd.png)

Current behavior: It shows 12 Picking
![screenshot](https://user-images.githubusercontent.com/16624719/50488657-93bbb500-0a29-11e9-85b7-0ded342d9903.png)

Expected behavior: Show 3 Picking (based on Filter)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo perhaps for you to check?

**Comment by sswapnesh** [comment]
@jco-odoo 
Can't we add default search in action too so both number will be aligned ?

**Comment by jco-odoo** [comment]
@sswapnesh It could just be changed in the XML, not necessarily in Python.

**Comment by sswapnesh** [comment]
> It could just be changed in the XML, not necessarily in Python.

True but its better to not change in xml part (Stable policy)

Can I make PR adding `search_default_available` in action context here ?
https://github.com/odoo/odoo/blob/12.0/addons/stock/views/stock_picking_views.xml#L532

**Comment by sswapnesh** [comment]
Adding search_default_available wont give correct result too.
we have to add more default filter in action (same as domain applied in field computation - 'assigned', 'waiting', 'confirmed')

https://github.com/odoo/odoo/blob/6e931e4e3cf2de8d1cdc203f3f0b4053788b5985/addons/stock/models/stock_picking.py#L85

I am closing related PR as Solution could be better than Proposed one. :+1:

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/3e6b4844d31e4b322688de8162a1746daaed3920 (Should be added in 12.0 soon)
