### ISSUE TITLE
[Wishlist] Allow to group by next activity

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#29786]
Hello

It seems that Odoo will use activity in business in most of the models so that I suggest to add a feature in next versions to allow end top managers to view as an example "Sale Orders" grouped by "Next Activity Type" and "Next Activity Responsible" to know the status.

**Comment by pedrobaeza** [comment]
There's already a new view for this in v12, called activity view. Have you tried?

Closing meanwhile.

**Comment by abdallamhafeez** [comment]
User want to view more data and options to grouping with details so it can make activity view more flexible to allow to group data dynamic as in list view.
