### ISSUE TITLE
[Wishlist] Consider By-Product on Unbuild Orders 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29807]
Impacted versions: All

Steps to reproduce: Install `'MRP Byproducts'` --> Create BoM to fulfil `A + B  -> D + E`
Eg, Main Product D having A and B ad BoM components and E is Byproduct

Create MO for Product `D` --> It will Produce` D + E`
![screenshot](https://user-images.githubusercontent.com/16624719/50537226-2b80e680-0b83-11e9-8658-f2faadf8de3b.png)

![screenshot](https://user-images.githubusercontent.com/16624719/50537241-46ebf180-0b83-11e9-8ff8-f58fd4c5327d.png)
Qty for E will be Increased (1 Kg in this example)
Create Unbuild order for `D` --> Unbuild it
![screenshot](https://user-images.githubusercontent.com/16624719/50537294-b4981d80-0b83-11e9-8643-5a0f65a33005.png)

Current behavior: It doesn't consider Product `E`
![screenshot](https://user-images.githubusercontent.com/16624719/50537298-be218580-0b83-11e9-9b77-a8472d92479c.png)

Expected behavior:  Consider all By-products and manage Inventory on Unbuild

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@jco-odoo @lap-odoo 
Can I propose PR in master if there are any plans to handle this situation?

**Comment by sswapnesh** [comment]
Ping  @jco-odoo  @sle-odoo  (From https://github.com/odoo/odoo/wiki/BugManagement)

**Comment by lap-odoo** [comment]
@sswapnesh It has been handled, you can test V12.3 or Master (on runbot)

**Comment by sswapnesh** [comment]
> @sswapnesh It has been handled, you can test V12.3 or Master (on runbot)
@lap-odoo 
I am not sure what's wrong on master branch but I never get By Product under Finished Products. (or I am missing something here)

**Comment by lap-odoo** [comment]
@sswapnesh I've tested in 12.3 and it works fine : 
https://nimb.ws/cx8CYr
https://nimb.ws/jHGufm

But there is well an issue in master for the moment.
