### ISSUE TITLE
[12] Wrong number of days in leave when Half day is checked

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29800]
Impacted versions: 12.0

Steps to reproduce: 

- Create leave from calendar
- Select Half day
 
Current behavior:![screenshot](https://user-images.githubusercontent.com/16624719/50522741-84546e80-0af2-11e9-9aad-4d1706a2af43.png)
Still 1 Days

Expected behavior: 0.5 Day

Video/Screenshot link (optional):

Not use if this due to latest changes in this module
Cc @tivisse 

Ps: Working time is configured well.

**Comment by sswapnesh** [comment]
PS: I don't know why but I cannot reproduce same in local system with latest code

**Comment by pedrobaeza** [comment]
Is this still happening in latest runbot?

**Comment by RomainLibert** [comment]
Probably related to these fixes : 
 * https://github.com/odoo/odoo/commit/765075ff475e0120d1c3f5564f2259c34d2386cc#diff-120bfde371591c6d73a9117c364862c2
 * https://github.com/odoo/odoo/commit/4b22f1ff5e7c350fa37459c106f52305e26f2ec9#diff-120bfde371591c6d73a9117c364862c2

Pushed to 12.0 on 28/12/2018

**Comment by sswapnesh** [comment]
Still I can reproduce same (Via different steps to reproduce)

**Comment by RomainLibert** [comment]
@sswapnesh Can you provide me the steps to reproduce it?

**Comment by sswapnesh** [comment]
Sure, Will update here once I get exact (and minimum) steps to reproduce.

**Comment by sswapnesh** [comment]
Reproduced on Latest Runbot:
http://420502-12-0-76e46b.runbot17.odoo.com/web?debug#id=63&model=hr.leave&view_type=form&menu_id=233
![peek 2018-12-31 23-40](https://user-images.githubusercontent.com/16624719/50565507-89652800-0d55-11e9-8f9f-9634fe32aaf3.gif)


I believe adding `request_unit_half` at https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L261 will solve it.
 (or Maybe I should Propose PR for this ?)

**Comment by einsty** [comment]
I am experiencing some related issue, although it may be a seperate case to be opened or a regression issue of this case.  Either way, I figured I'd start here.   

When we click on a calendar date to start a leave request, the default start day is the day clicked, but the end day is the next day and the duration is 1 day.  However, if I click then on the half day checkbox, and then uncheck the checkbox, the start and end day are the same and the duration is one day.  

![leave-request](https://user-images.githubusercontent.com/1541350/52862403-d3824d00-30fa-11e9-8d6e-14bf8e689395.gif)

So, there is a workaround to get the right data represented, but it is an annoyance.  Does anybody else experience this?
