### ISSUE TITLE
[11/12] Kanban tooltip is not working 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29802]
Impacted versions: 11/12

Steps to reproduce: Add Kanban tooltip with few fields on Kanban view
![screenshot](https://user-images.githubusercontent.com/16624719/50534394-f44e0d80-0b61-11e9-8b6f-d7bec55224f7.png)

Current behavior: Values are not there
v12
![screenshot from 2018-12-29 12-05-23](https://user-images.githubusercontent.com/16624719/50534401-092aa100-0b62-11e9-8ffc-8c6f96e0afdc.png)
![screenshot from 2018-12-29 12-05-49](https://user-images.githubusercontent.com/16624719/50534403-18a9ea00-0b62-11e9-9c19-f0e9f06a5876.png)

V11
![screenshot from 2018-12-29 12-06-15](https://user-images.githubusercontent.com/16624719/50534412-3d9e5d00-0b62-11e9-95ec-91b6ad776974.png)

Expected behavior: Values should be there in tooltip

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@ged-odoo one for the JS team

**Comment by Yenthe666** [comment]
Also bitten by this one now. Since there has been no response from the Odoo team I've reported it through an OPW (2055132)

**Comment by Yenthe666** [comment]
@kebeclibre  Literally nothing changed? See result on latest 11.0:
![image](https://user-images.githubusercontent.com/6352350/63585997-a7132600-c5a0-11e9-8633-5901bb705466.png)

**Comment by kebeclibre** [comment]
@Yenthe666 
Must be a bug in the Matrix, the runbot community has my fix applied

**Comment by sswapnesh** [comment]
> the runbot community has my fix applied

Seems working well on Community

http://595256-11-0-kanbantooltip-no-longer-fie-9ff357.runbot20.odoo.com/web?#view_type=kanban&model=maintenance.request&menu_id=197&action=233

**Comment by Yenthe666** [comment]
Not working on the latest V12 community either:
![image](https://user-images.githubusercontent.com/6352350/63766036-a1804d80-c8ca-11e9-9cb6-e2e5f4b93985.png)
Tested at http://601700-12-0-0aaf73.runbot11.odoo.com/web?debug=1#action=245&model=maintenance.equipment&view_type=kanban&menu_id=189

**Comment by Yenthe666** [comment]
Sorry its not yet synced to v12. V11 enterprise does work fine now.
