### ISSUE TITLE
[12]Expected singleton on Recording Production (Due to bad configuration)

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29808]
Impacted versions: 12

Steps to reproduce: Setup MRP Byproduct --> Add Same Product as Byproduct in BoM
![screenshot](https://user-images.githubusercontent.com/16624719/50537548-eced2b00-0b86-11e9-88ae-dedce41c67e6.png)

Create MO --> Produce
![screenshot](https://user-images.githubusercontent.com/16624719/50537555-055d4580-0b87-11e9-9e61-92b0a32cfcf2.png)

Current behavior: On Record Production 
![screenshot](https://user-images.githubusercontent.com/16624719/50537577-73a20800-0b87-11e9-8771-88d8a5e14980.png)

That's because of
![screenshot](https://user-images.githubusercontent.com/16624719/50537569-46555a00-0b87-11e9-81b7-efec8258e349.png)

Expected behavior: IMO Bad configuration should not be allowed on BoM (Byproducts)

Video/Screenshot link (optional):

Proposed solution:We should add constraints to block adding same Product in Byproducts on BoM.

**Comment by jco-odoo** [comment]
If it is the same product, how is it a byproduct?

**Comment by sswapnesh** [comment]
It is not. I was looking at code and found this. I think we can improve this bad configuration

**Comment by jco-odoo** [comment]
@lap-odoo @sle-odoo Maybe we need to avoid these configs.  So a constraint on the byproduct line that says that the BoM's product(/product template...) should not be the same as the byproduct.

**Comment by sle-odoo** [comment]
Closing as the linked PR is merged
