### ISSUE TITLE
Multi Company Multi Warehouse Stock Valuation

### ISSUE THREAD

**Issue by hilarak** [odoo/odoo#29826]
Impacted versions:
V8

Steps to reproduce:

    

1.     Company A and Company B, B child company of A.
2.     A purchases materials for B.
3.     Stock Valuation is real-time and costing is 'real price'.
4.     Purchase order created in company A, goods received in company A.
5.     Goods are moved to company B Via intercompany transit using routes by defining push rule.
6.     When goods are received in company B, the inventory value is 0. For all other goods transactions, inventory value is coming correctly.
7. 

Current behavior:

- While receiving goods in company B , for first time the inventory value is 0.

Expected behavior:

Video/Screenshot link (optional):
![uuuuuu](https://user-images.githubusercontent.com/24998694/50556779-dc5bc280-0cf6-11e9-964c-324e309ba118.png)

**Comment by pedrobaeza** [comment]
Sorry, but v8 is no longer supported by Odoo. The official supported versions right now are v10, v11 and v12.

If you find the same problem in that versions, then feel free to post again an issue against that version.

**Comment by hilarak** [comment]
Thanks For your reply.
