### ISSUE TITLE
[7.0] Dialog scroll editable list first focus positioning with Google Chrome

### ISSUE THREAD

**Issue by amsys** [odoo/odoo#2984]
Hello,

Steps to reproduce:
1) Create popup dialog with view so long that vertical scroll bar has to appear.
2) Place editable list view on bottom of the form.
3) Open new popup window, scroll down and focus on any editable form item in list view, on the first focus the item will appear out of its position with offset exactly as it was scrolled down.

Note after leaving the editable list view and focusing again the form element appears on correct position.

This is Google Chrome specific problem (does not happen in Firefox, but unfortunately Firefox is not browser of choice for OE due to performance issues), but I am posting the issue here as I can't describe exactly the reason to Chromium-dev or maybe we can find some workaround?

![image](https://cloud.githubusercontent.com/assets/164869/4571952/882c6540-4f7f-11e4-9468-788539920992.png)

**Comment by Yenthe666** [comment]
Hi @amsys ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
