### ISSUE TITLE
[WISHLIST] It will be better to move the tables created inside website_sale to seperate module

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#29840]
There are models like product.image and product.public.category which are defined in module website_sale to a separate module so that we can reuse those models in the connector framework. For example the model product.images and image_ids in product template can be used for image syncing from magento using magento connector and even we can show them in odoo website. 

Cheers,
Omal Bastin

**Comment by pedrobaeza** [comment]
Well, this would help to reuse them. `product` module can be a good host. @JKE-be do you plan to make such a move?
