### ISSUE TITLE
[12] Can not add Binary field from odoo

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29846]
Impacted versions: 12

Steps to reproduce: Create new Binary field (for model with _auto = False) 
![screenshot](https://user-images.githubusercontent.com/16624719/50575756-285b5400-0e2a-11e9-9d09-43f126deb3d6.png)

Current behavior: 
![screenshot](https://user-images.githubusercontent.com/16624719/50575762-3e691480-0e2a-11e9-8e2b-d828630eebcd.png)

Expected behavior: IMO field should not be added form Odoo for this type of model

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I consider this a bit recherche, as you are doing very advanced things and you should know the consequences of doing some wrong. This is not about creating a binary field, but any field that is not declared on the SQL that defines the source table. As the promoted way to add fields is through Odoo Studio, this case should be consider as marginal and thus although not correct, it's not either a business flow error.

Closing in the same spirit we talked about the other day of focusing in the best issues to solve.
