### ISSUE TITLE
[12] Wrong number of Allocated Days on  Leave type

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29845]
Impacted versions: 12.0

Steps to reproduce: Create Allocation for any leave type (Department or Company)

Current behavior: Allocation is correct(depends of Mode) however Counter is always Zero
![screenshot](https://user-images.githubusercontent.com/16624719/50575331-85074080-0e23-11e9-9f18-cad8f50613da.png)

Expected behavior: Correct number 
![screenshot](https://user-images.githubusercontent.com/16624719/50575332-8fc1d580-0e23-11e9-9abb-a3b4098fecb5.png)

Video/Screenshot link (optional):

Ps: Maybe I didn't understand this well but this doesn't looks correct to me.
https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave_type.py#L242 

(Why we are not considering` holiday_type = employee `over there, IMO we should only include this instead of excluding)

**Comment by sswapnesh** [comment]
Hello @tde-banana-odoo
This has been added from commit https://github.com/odoo/odoo/commit/bd5b2c9466eabe56bbb1e91d29a7e422e957550f 
It mentiones:
```
* add a "X days allocated" stmart button. If you set a general allocation
   of 20 days, the stat button will display 20 days. Even if you go update
   the allocation by employee after that. Purpose is to have the value of
   main allocation done in group, not individual cases of some employees;
```

As you mentioned to Indicate Days here, IMO we should display `Allocated Days * Number for employee for that allocation type`. (Technically All  allocations where Employee is Set)

By this way we can get exact number of days Allocated.

I am not sure about detailed functionality but you can decide what to do here.

Thanks

**Comment by Yenthe666** [comment]
@sswapnesh I'd suggest to create it in a PR and ask the review or feedback there.

**Comment by sswapnesh** [comment]
I can but I am not sure about  functionally what the nunber should display.

**Comment by sswapnesh** [comment]
Hello @tivisse @RomainLibert,

Could you please add you thoughts on this ? (or Maybe Adding PR would help)

**Comment by tivisse** [comment]
Hi @sswapnesh

Thanks for the feedback.
 
At the time this was done, it was explicitly requested by the Product Owners and Fabien. So I won't change anything, and it follows the specification.

The message on the PR is wrong for that case, sorry about that.

According to Fabien, we wish to track the individual allocations, not the allocations by department, company, ...

Have a nice day,

Yannick.
