### ISSUE TITLE
[12] Website:  Use correct labels on for product price on Cart page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29842]
Impacted versions: 12.0

Steps to reproduce: Enable B2B and B2C (I know this is not correct use case but still we can Improve it)
![screenshot](https://user-images.githubusercontent.com/16624719/50574969-1329f980-0e19-11e9-91e6-d1bd0d9cbf4c.png)

Current behavior:
Website Shopping cart page
![screenshot](https://user-images.githubusercontent.com/16624719/50574957-c9d9aa00-0e18-11e9-96dd-be0f70944816.png)

Expected behavior:Use two labels B2B price and B2C price based on User access rights

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Is the issue to you that you see both prices when checking them both on or?

**Comment by pedrobaeza** [comment]
You shouldn't checked both permissions as they are intended for different users depending on your kind of customers/viewers of the e-commerce: for user "Public User" you select if it's going to be B2C (taxes included) for general e-commerce view, and for selected users with portal access, you select B2B if they need to see without taxes.

I don't see here any issue, but Yenthe, I let you to decide if you escalate this or close it.

**Comment by Yenthe666** [comment]
Indeed, I see no issue either. You've checked both on as a user yourself honestly. Totally agree with Pedro, otherwise you'd have to make every single feature and option in Odoo idiot proof, which is impossible and generally a very bad idea to do.

**Comment by seb-odoo** [comment]
This is a technical field used internally by Odoo. The admin should never check both options. Those boxes should not even be used to make a setting per user, because it's going to be reset automatically if/when changing the general tax included/excluded setting.

I'm surprised it's not hidden under debug mode.
