### ISSUE TITLE
[12] Record missing_error on website shopping cart

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29841]
Impacted versions: 12.0

Latest Runbot 12: http://420643-12-0-76e46b.runbot15.odoo.com

Steps to reproduce:  Added in Gif

Current behavior:  Error in Console
`Server application error {"code":200,"message":"Odoo Server Error","data":{"name":"odoo.exceptions.MissingError","debug":"Traceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1032, in get\n    value = self._data[field][record.id][key]\nKeyError: (<odoo.sql_db.Cursor object at 0x7fa894d83400>, 1)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/fields.py\", line 970, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1034, in get\n    raise CacheMiss(record, field)\nodoo.exceptions.CacheMiss: ('sale.order.line(300,).event_ticket_id', None)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 654, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 312, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 696, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 344, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 337, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 939, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/http.py\", line 517, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/addons/website_sale/controllers/main.py\", line 445, in cart_update_json\n    value = order._cart_update(product_id=product_id, line_id=line_id, add_qty=add_qty, set_qty=set_qty)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/addons/website_sale_delivery/models/sale_order.py\", line 92, in _cart_update\n    values = super(SaleOrder, self)._cart_update(product_id, line_id, add_qty, set_qty, **kwargs)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/addons/website_event_sale/models/sale_order.py\", line 58, in _cart_update\n    ticket = line.event_ticket_id\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/fields.py\", line 977, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1036, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1074, in getter\n    raise exception\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/models.py\", line 2770, in read\n    values[name] = field.convert_to_read(record[name], record, use_name_get)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/models.py\", line 5049, in __getitem__\n    return self._fields[key].__get__(self, type(self))\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/fields.py\", line 970, in __get__\n    value = record.env.cache.get(record, self)\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1036, in get\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/home/odoo/runbot/runbot/runbot/static/build/420643-12-0-76e46b/odoo/api.py\", line 1074, in getter\n    raise exception\nodoo.exceptions.MissingError: ('Record does not exist or has been deleted.', None)\n","message":"Record does not exist or has been deleted.\nNone","arguments":["Record does not exist or has been deleted.",null],"exception_type":"missing_error"}}`

Expected behavior: No error

Video/Screenshot link (optional):
![peek 2019-01-01 22-50](https://user-images.githubusercontent.com/16624719/50574918-f0e3ac00-0e17-11e9-84cf-1930230e00d8.gif)

**Comment by pedrobaeza** [comment]
@sswapnesh it would be better if you capture videos with some kind of click signalling for knowing where do you click. I use peek + keymon for this task.

@JKE-be is there any recordset cached that can cause this behavior?

**Comment by sswapnesh** [comment]
@pedrobaeza  I am already using peek (and will try/use keymon also)

**Comment by seb-odoo** [comment]
I'm not sure to understand the minimal steps to reproduce, can you write them down please?

Also by trying on a clean runbot where the config is not changed such as checking both B2B and B2C settings because we don't support that.

**Comment by sswapnesh** [comment]
Sure, I will add more info here (It is not because of any settings as I was able to Reproduce this on new fresh Runbot)

**Comment by sswapnesh** [comment]
@pedrobaeza  :+1:  for suggesting key-mon .


@seb-odoo  
![screenshot](https://user-images.githubusercontent.com/16624719/50607666-fd3b3800-0eef-11e9-96f2-16be6d73bea0.png)
![screenshot](https://user-images.githubusercontent.com/16624719/50607834-a7b35b00-0ef0-11e9-886f-afdfe0c15f1e.png)


So basically you have to reproduce case when RPC call to remove call is made first and than you are increasing quantity of same line.(Before view is updated)

Added gif with Key-mon as well

![peek 2019-01-03 00-36](https://user-images.githubusercontent.com/16624719/50607632-d7ae2e80-0eef-11e9-8350-c69614870816.gif)

**Comment by pedrobaeza** [comment]
Thanks for extended information. `keymon` has also an option for showing a circle around cursor when doing click ("Highly visible click"). Try it to see if it's working properly on your side for better showcase (I didn't get it to work on some times).

**Comment by JKE-be** [comment]
It is always the same bug that you report every time ! It is a question of async call!

Stop to bullshit the UI and use the website like a real user and you will see that there are no bug !

If you decide to remove a article of your cart, and at the same time you are mad to decide to change the quantity it is true you have a warning in your log because you try to update the qty from a line that doesn’t exist... but no bug for end user... it is just a log... 

Please, take time to report real bug or propose PR instead to open issue just for fun.

A error in console JS is not a traceback or 500 that end user see!

Best regards and happy new year 🎊

**Comment by sswapnesh** [comment]
Happy new Year @JKE-be  

I am not doing this for any **FUN**. 
> It is always the same bug that you report every time !

No offence but Just look at all Issues reported by me and see If all are same or not (Yes, I know 3 or 4 because of Double click and few more related to module uninstall  - (Which blocks the operation))

I accidentally reproduced this where my screen was frozen and spent (Wasted now) few hours to reproduce same with minimal steps.

I know this is rare case but still we can manage this in better way.

Best regards

**Comment by pedrobaeza** [comment]
@sswapnesh but it's true that this is not throwing any error to the user, just a warning log in the console, which most users are unaware of, so this is far from critical. If you mask this warning, maybe other real warnings not caused by an async operation that leads you to click before receiving the line removal event might be masked. I wouldn't dig more in this.

Other issue reports are very valuable of course, although some times you have to learn about some typology that are not suitable for focusing on fixing the most critical ones. Having an issue tracker full of things good to be refined that distract from the blocking issues is not a good thing IMO.

And Happy New Year to all!

**Comment by JKE-be** [comment]
We prefer to spend time to fix real bug like uninstall that really block the user.

To improve the unprovable case like in your scenario we prefer PR to improve the product, since there are no real traceback it is not an issue!

And I know your level and your knowledge (I see your good participation into the security channel) so I’m sure that you know how to improve it in one line in a PR instead to write a long issue like this one ☝️ 

I continue my holiday :) see you next week 😝

Jeremy Kersten

**Comment by sswapnesh** [comment]
@JKE-be Enjoy your Holidays. (and sorry for the Noise)

As @pedrobaeza  said I would not dig more in this case.

**Comment by Yenthe666** [comment]
Agreed with all of you but wanted to add a little note. Keep up the good work, you have some great PR's and bug reports so kudos for that.

Happy new year to all of you.
