### ISSUE TITLE
error on change any config

### ISSUE THREAD

**Issue by rogeriojlle** [odoo/odoo#29848]
Impacted versions:
Odoo 13.0alpha1-20190101

Steps to reproduce:
change any item in general config ( ...web?#id=&action=91&model=res.config.settings&view_type=form&menu_id=4 )

Current behavior:
psycopg2.DataError: invalid input syntax for integer: "virtual_5"

Expected behavior:
none

[odoo_server_error.txt](https://github.com/odoo/odoo/files/2719991/odoo_server_error.txt)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

Thanks for your report. You shouldn't report against the Odoo 13 alpha (master) though. It is still 10 months untill its release and actively being developed on. It breaks all the time right now honestly.

Regards,
Yenthe
