### ISSUE TITLE
point_of_sale: Sales amount not  shown in the product

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#29856]
#### Impacted versions:
All

#### Steps to reproduce:
- Sale product A from the point of sale
- Go to product A record.

#### Current behavior:
- The Sales count is 0.

#### Expected behavior:
Sales count from the point of sale should be considered. As clients with mixed sales (from Sales module and Point of Sale) won't have the whole picture.

**Comment by Yenthe666** [comment]
@gustavovalverde I believe this was done by purpose and design. You can see all POS sales from the POS app, all 'normal' sales from the contact form.
@pimodoo could you confirm?

**Comment by Yenthe666** [comment]
@switch87 actually, I think you can confirm this.

**Comment by pedrobaeza** [comment]
@qle-odoo @switch87 I think this is discarded from your roadmap, or there's any plan to provide a general sales count computation from any channel?

**Comment by switch87** [comment]
@lca-odoo @lap-odoo

**Comment by mart-e** [comment]
Sale order and point of sale orders are indeed two different things. We do not plan to change that.
However, in version 13.0, the number of sale displayed on the product page aggregates both these information, you should see it there.
