### ISSUE TITLE
Pedidos de venta - Sales order

### ISSUE THREAD

**Issue by xaquinrosales** [odoo/odoo#2986]
Openerp 7
Cuando se hace un pedido de venta, se confirma, se le da salida a la mercancía y seguidamente se devuelve toda, ambos albaranes (Salida y Entrada), quedan con control de factura No aplicable, pero el pedido queda Realizado.
Esto influye en las estadísticas de ventas, ya que estas estadísticas únicamente tienen en cuenta los pedidos de venta.
En el caso mencionado me van a figurar ventas en esa estadística (Informes de ventas), cuando realmente no se ha producido ninguna.
Necesito una solución para este problema.

English
Openerp 7 
When a sales order is made, it is confirmed, it is output to the goods and then returns all both invoices (Input and Output), with control invoice are not applicable but the order is Done. 
This influences sales statistics, since these statistics only take into account sales orders. 
In the case mentioned I was going to include sales in that statistic (Sales Reports), when they do not there has been none.
I need a solution for this problem.

**Comment by Yenthe666** [comment]
Hi @xaquinrosales,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
