### ISSUE TITLE
DO has wrong creation user

### ISSUE THREAD

**Issue by devang-dreambits** [odoo/odoo#29872]
The issue is checked in odoo v12 and Odoo v11 also.

Impacted versions:
Odoo 11.0 & Odoo 12.0

Steps to reproduce:

1. Get logged in with a non-admin user and enable developer mode(or you can enable developer mode with admin log-in in private window to view metadata of the record - in my case the non-admin user is admin_1)

For Purchase order and Receipt
2. Create a purchase order & confirm it. It will generate stock.picking(Receipt). 
3. Now open that Receipt and open 'View metadata' from debug button, you'll see the creation user is "admin_1" and the Purchase Order is been created by the same non-admin user 

For Sales Order and DO
4. Create a sales order & confirm it. It will generate stock.picking(DO). 
5. Now open that DO and open 'View metadata' from debug button, you'll see the creation user is "OdooBot" even though the Sales Order is been created by the non-admin user 

The issue is been checked on the runbot with following details:
URL: http://421353-12-0-ea301b.runbot14.odoo.com/web/login
user: admin
pass: admin_123

Current behavior:
When a purchase order is been created by a non-admin user - the related receipt(stock.picking) is also been created by the non-admin user, but when the sales order is created by a non-admin user - the related Do(stock.picking) is been created by super admin.

Expected behavior:
When the Sales order is created by non-admin user - the related DO(stock.picking) should be created by non-admin user.

Video/Screenshot link (optional):
Purchase Order:
![purchase_order](https://user-images.githubusercontent.com/31969950/50627090-dfa1b900-0f57-11e9-87be-a5eb86e5d3a6.png)

Sales order:
![sales_order_do](https://user-images.githubusercontent.com/31969950/50627095-e3cdd680-0f57-11e9-9bdf-5101654a25a6.png)

**Comment by pedrobaeza** [comment]
This is due to the chain of operations implied, where some of them are performed with `sudo`, replacing the user with the admin one, so this is not really a problem. What problem do you see with this?

**Comment by sle-odoo** [comment]
Fixed in v13 with the sudo not changing the user.
