### ISSUE TITLE
 delivered quantities in product> sales disappears on service product

### ISSUE THREAD

**Issue by dlemireanybox** [odoo/odoo#29893]
Impacted versions: V12

Steps to reproduce: 

1. add project, timesheets modules
2. go to service product 

Current behavior:
 delivered quantities in product> sales disappears on service product
Expected behavior:
 delivered quantities in product> sales is visible on service product, in order to use expense product

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
It depends on the product configuration. If you put in "Service Invoicing Policy" = "Timesheets on tasks", then you have that field filled with the proper data.

Closing this as no real issue.

**Comment by dlemireanybox** [comment]
when product is service " delivered quantity option" is **missing**, is a problem in case we want use the fonctionnality re-invoice the expense .  
when i validate an expense, a line is add on origine sale order and populate the delivered quantity but there are no effect on invoice certainly due to not possibility to select "delivered quantity option"

**Comment by pedrobaeza** [comment]
Please read v12 user manuals about the topic, as it has been refactored in this version.

**Comment by dlemireanybox** [comment]
i follow this doc

**Comment by dlemireanybox** [comment]
https://www.odoo.com/documentation/user/12.0/sales/invoicing/expense.html
![delivered_quantity_missing](https://user-images.githubusercontent.com/32740203/50645123-120cdf80-0f73-11e9-80c2-a34bfda506b0.png)

**Comment by pedrobaeza** [comment]
That documentation is outdated, but the equivalent one should be "Timesheets on tasks".

@jem-odoo any chance of getting updated documentation on this and please confirm my sentence?
