### ISSUE TITLE
500 internal server error while saving Home website

### ISSUE THREAD

**Issue by akram1** [odoo/odoo#29895]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by akram1** [comment]
I was editing Home website. I hit save and 500 Internal Error appeared. I can access other pages. I tired to delete Home and recreate it same error and same behavior.

Error
'NoneType' object has no attribute '_fields'
Traceback (most recent call last):
  File "/mnt/Data/projects/odoo/server/odoo12/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_385_601
  File "<template>", line 2, in body_call_content_600
  File "/mnt/Data/projects/odoo/server/odoo12/odoo/addons/base/models/ir_qweb.py", line 368, in _get_field
    field = record._fields[field_name]
AttributeError: 'NoneType' object has no attribute '_fields'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute '_fields'
Template: 385
Path: /templates/t/t/div/section[2]/div/div/div[1]/div/h4
Node: <h4 t-field="p.name"/>

**Comment by akram1** [comment]
Impacted versions:

Steps to reproduce: v12

Steps to reproduce:: Install Website with bootswatch theme. Installed app: blog, presentation, event. Edit Homepage with default snippets. Added Cover and tried to add some text at the end of cover (Contact us  About Us) then deleted. Added Latest Post list change to 3 columns. Save and got 500 Internal Server Error

**Comment by pedrobaeza** [comment]
Sorry, but this due to your bad manipulation of the view content. Delete in backend the involved QWeb views and update website module for restoring them.

Closing as no issue, but bad manipulation.

**Comment by sherpya** [comment]
The problem still happens a lot, the view gets populated with a partial snippet from data template `s_latest_posts_list_template`, I find in the view only:

```xml
            <div class="media-body ml-3 pb-2">
                <h4 t-field="p.name"/>
                <p t-field="p.subtitle"/>
                <a class="btn btn-sm btn-secondary" t-attf-href="/blog/#{p.blog_id.id}/post/#{p.id}">Read More</a>
            </div>
```

without `t-foreach`, I think the data-template part it is not supposed to get in the generated view
