### ISSUE TITLE
[DOC] add information about how to restore a database on Odoo SaaS

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#29899]
Impacted versions: All (Saas)

Steps to reproduce:
See https://www.odoo.com/forum/help-1/question/database-restore-odoo-online-12-0-e-version-143661
Right now there is no option to restore a database on the Odoo SaaS but there is nothing in the docs explaining what the options are and if it is even possible.

Current behavior: No documentation about restoring a database

Expected behavior: Documentation about restoring a database

**Comment by Yenthe666** [comment]
@mart-e I saw the topic in the help forum and I was interested. If you just let me know what the option is then I'm happy to add a section to the docs at https://www.odoo.com/documentation/user/12.0/db_management/db_online.html

**Comment by Yenthe666** [comment]
@Feyensv maybe for your interest by the way!

**Comment by Feyensv** [comment]
Totally not in my field of work, i won't be able to provide any information/doc on this, sorry :confused:.

**Comment by Yenthe666** [comment]
Too bad, it was worth the shot. Thanks for the feedback. I guess it'll stay for @mart-e then.

**Comment by mart-e** [comment]
Hi,

Restoring a database is sometimes a bit tricky, you have to look out for a few things (filestore, versions, SaaS modules,...)
Allowing people to import databases potentially from a non-online server is not a good idea (a few things to adapt to work on the SaaS).
For this specific scenario, it is always best to go through the support.
Maybe if this is a frequent request, we will add the possibility, but at the moment we prefer to keep it a case-by-case workflow ;-)
