### ISSUE TITLE
[12] RFC - configuration needed to expire sessions after idle time

### ISSUE THREAD

**Issue by aelmanaa** [odoo/odoo#29906]
Impacted versions:
All
Steps to reproduce:
Log in with an active user 

Current behavior:
the user will be always logged in
Expected behavior:
It would be nice if Odoo exposed parameters to configure session timeout. Once the session times out , the user has to log in again
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@odony I think this has been discussed other times, isn't it? Do you have any link to that discussion?

**Comment by sswapnesh** [comment]
> the user will be always logged in

Session expires after 90 days (https://github.com/odoo/odoo/blob/12.0/odoo/http.py#L1433)
![screenshot from 2019-01-04 00-15-13](https://user-images.githubusercontent.com/16624719/50655357-dfd0a180-0fb5-11e9-8638-1fd51e2754b6.png)

**Comment by Yenthe666** [comment]
Yep indeed @sswapnesh and you could change this value to customise it to your own needs.

**Comment by aelmanaa** [comment]
thank you very much to all of you for the answers! However @Yenthe666: I understand that we can change the code to customise it to our own needs but isn't it an interesting improvement to the standard version of odoo? I mean allowing the possibility to set up the timeout through configuration and per database (Maybe some clients are interested but other are not interested so the admin will setup the timeout by database) can be a nice addition to Odoo

**Comment by nhomar** [comment]
Actually this should be nice have those numbers in the config file or at parameters level (per database) but I think there are some limitations to the last one.

What should be nice is do it and then give a more informated feedback once it is mature in our side.

**Comment by odony** [comment]
@pedrobaeza I couldn't find any reference to a discussion about this. Would be a sensible thing to support in the config file.

We could imagine allowing per-database override via `ir.config.parameter`, however this will require some extra plumbing vs current approach, and the default expire will still have to apply before login.

PR for master welcome ;-)

**Comment by sswapnesh** [comment]
Added PR https://github.com/odoo/odoo/pull/30004 (to manage this from `ir.config.parameter` )
Would be great If one can verify
