### ISSUE TITLE
[10, 11,12]base: Return trackback in POS payment screen

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#29909]
Impacted versions:
10.0 

11.0

12.0

Steps to reproduce:

1. Take order in pos
2. click payment button
3. click a payment journal
4. added price in payment (ex : 123)
5. click "minus" on a keyboard (ex: -123)
6. clear payment amount(ex: -12)

Current behavior:
raise error - is not a float

Expected behavior:
error will be not raise and clear minus button

Video/Screenshot link (optional):
![float](https://user-images.githubusercontent.com/29298578/50659361-612e3100-0fc2-11e9-9717-ed29c5b616f9.png)

https://drive.google.com/open?id=1GDCT8vgMxZFKtY4_R15ciAVcRSTKkBvn

**Comment by switch87** [comment]
see #30035 for the fix. Please feel free again to test yourself on runbot.
