### ISSUE TITLE
[12] website: Comments are not displayed on Slides

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#29901]
Impacted versions: 12.0

Reproduced on latest Runbot v12 (http://421723-12-0-b969c0.runbot13.odoo.com/slides/public-channel-1) w/o modifying any views

Steps to reproduce:
![screenshot](https://user-images.githubusercontent.com/16624719/50648248-b6f1e180-0fa0-11e9-81e5-5c19c6ce5ec6.png)

Current behavior:
![dd](https://user-images.githubusercontent.com/16624719/50648251-b8bba500-0fa0-11e9-85d8-77bd5c91d01f.png)

Expected behavior:
![screenshot](https://user-images.githubusercontent.com/16624719/50648289-cffa9280-0fa0-11e9-840e-dcd9b6007e25.png)

Video/Screenshot link (optional):

====================================================================
Ps: Adding small UI issue on same page
![screenshot](https://user-images.githubusercontent.com/16624719/50648414-2962c180-0fa1-11e9-95cb-07d2ab6eefd1.png)

Current behavior. 
![screenshot](https://user-images.githubusercontent.com/16624719/50648556-8f4f4900-0fa1-11e9-9b96-e15fd924951f.png)

Expected behavior:
![screenshot](https://user-images.githubusercontent.com/16624719/50648575-9c6c3800-0fa1-11e9-80f6-6dfb8a1468af.png)

@JKE-be  You can close this right away if you find this near to expected behavior in current framework.

**Comment by tde-banana-odoo** [comment]
Best team of the world will handle it.

**Comment by JKE-be** [comment]
thank you @tde-banana-odoo
