### ISSUE TITLE
[11,12]Point of sale: Keyboard backspace not work in payment screen 

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#29911]
working

11.0

12.0

Steps to reproduce:

Take order in pos

click payment button

click a payment journal

click "backspace" on a keyboard

Current behavior:

clear two buffer

Expected behavior:

clear only one buffer

Video/Screenshot link (optional):
https://drive.google.com/file/d/1qn4lRo30mL9jxGeG-3K2gyfgKC1xP3u_/view?usp=sharing

**Comment by switch87** [comment]
@ammarofficewla , thank you for reporting this issue. I created a pull request for resolving this issue. feel free to testing it on runbot http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-odoo-2?search=11.0-point-of-sale-payment-keyboard-gpe

#30031
