### ISSUE TITLE
[10, 11,12]Point of sale: stuck payment numpad

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#29910]
Impacted versions:

10.0

11.0

12.0

Steps to reproduce:

Take order in pos

click payment button

click a payment journal

click "minus" on a keyboard

click payment numpad button or keyboard

Current behavior:

keyboard and payment numpad not work

Expected behavior:

keyboard and payment numpad will be work

Video/Screenshot link (optional):
https://drive.google.com/open?id=1saRwWo2iWhwDM1ZVSMtLbWetePZN_7xK

**Comment by switch87** [comment]
see #30035 for the fix. Please feel free again to test yourself on runbot.

**Comment by sswapnesh** [comment]
This can be closed once related commit is forward ported.
 Cc @switch87
