### ISSUE TITLE
[12] BOM / BOM Structure different after editing product

### ISSUE THREAD

**Issue by Axel-G** [odoo/odoo#29916]
Impacted versions:
Odoo 12

Steps to reproduce:
create a bom
create (click) a/to bom-structure&cost

edit name of product (item of bom)

Current behavior:
look to bom: new product name is right
look to bom-structure: old name of product

Expected behavior:
update name of product in bom-structure

Video/Screenshot link (optional):

BoM-screen
![bom](https://user-images.githubusercontent.com/40705043/50667207-72724000-0fb8-11e9-899a-0fa4413a8f5f.png)

BoM-Structure&Cost-screen
![bom-structure](https://user-images.githubusercontent.com/40705043/50667209-743c0380-0fb8-11e9-81ee-91d28794bcba.png)

**Comment by Axel-G** [comment]
printing BoM Structure = correct description

**Comment by pedrobaeza** [comment]
I'm not able to replicate the problem. Please record a video about the problem.

**Comment by Axel-G** [comment]
ok, i tested more and its a other problem:

In multilanguage the Structure & Cost Site isn't translated, only english.
If i edit a existing product again, only the german translation is edited and the old english value remains.

So its only a problem of non-translation-view of cost&structure.

Thx, can be closed.
