### ISSUE TITLE
[12,12e] CacheMiss exceptions on a clean db backup -> restore

### ISSUE THREAD

**Issue by fractalf** [odoo/odoo#29914]
Hi, I'm an enterprise user and ran into this now, just 2 weeks before we will go into production. It happens  when migrating data from an old SAP db to Odoo. Basically I'm exporting data from a SAP db into my local Odoo (linux dev pc running Odoo in docker) which works fine. I then backup and try to restore on our production server. It affects both community and enterprise edition. I spend a lot of time debugging, but now I'm really stuck. I stripped away every bit of custom code, just using official code to reproduce the issue here.

**Impacted versions:**

12 build 20181126
12e build 20190103

**Steps to reproduce:**

_TLDR;_

- create a new db
- backup the db
- restore the db to another db name

_DETAILED STEPS_

I can reproduce this behaviour on both the community and enterprise edition, but will use the community edition as example here for simplicity

1. Install Odoo v12 using docker-compse and the offical docker image. This will install build 20181126, ref: https://github.com/odoo/docker/blob/master/12.0/Dockerfile

_docker-compose.yml_
```
version: '3'
services:
    db:
        image: postgres:10
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
    odoo:
        image: odoo:12
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./odoo.conf:/etc/odoo/odoo.conf
        depends_on:
            - db
        ports:
            - "8069:8069"
        tty: true
```
Note: _entrypoint.sh_ and _odoo.conf_ are exactly the same as the files from the github link above

2. When Odoo is up an running on locahost:8069, create a new database

3. Before installing any apps do a backup
```
docker exec -it odoo12_db /usr/bin/pg_dump -U odoo --no-owner --file=dump.sql dbname
docker cp odoo12_db:/dump.sql dump.sql
zip backup.zip dump.sql
```
_odoo12_db_ is the name of the postgres container and _dbname_ is the name of the db

4. Restore the db from this _backup.zip_ file from the Odoo gui (http://localhost:8069/web/database/manager) and call the new db something else than the original

5. Login in and the log will raise the exceptions listed below

**Current behavior:**
```
2019-01-03 21:45:09,663 1 INFO asdf odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/asdf/ed/ed0dd8839bc6a8b0211fda0de146d014050c4472 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fee21b310b8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).image_small', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fee21b310b8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.partner(3,).image_small', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fee216a9be0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(6,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/asdf/ed/ed0dd8839bc6a8b0211fda0de146d014050c4472'
```
This seems innocent on the community edition, but the enterprise edition won't boot properly at all.

**What causes these CacheMiss exceptions?**

Thanks a lot :)

**Comment by fractalf** [comment]
All this trouble was caused by taking backup with an old pg_dump version.
This issue reports the bug
https://github.com/odoo/odoo/issues/30599

closing..

**Comment by aliomattux** [comment]
I had a very similar issue however it was caused by the application depending on the existence of cache entries related to ir.attachment. It seems that once the database has stored attachments that the database can't be restored without the existence of the .filestore, but didn't look into it much. Just ended up deleting ir.attachment and it fixed the issue.
