### ISSUE TITLE
[12.0] activity type translation in activity view

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#29945]
Impacted versions:
12
Steps to reproduce:
- Load any language and change user to it
- Create new activity type and add translation
- schedule activity in any model that has activity view

Current behavior:
activity type is not translated

Expected behavior:
activity type should appear based on user lang

Video/Screenshot link (optional):
https://drive.google.com/file/d/1ipXOFlhTxi3YG8l1raZsVBfD_BfYsGd5/view?usp=sharing

**Comment by pedrobaeza** [comment]
Is this happening in latest version code?

**Comment by abdallamhafeez** [comment]
@pedrobaeza  Yes, it appears in runbot

**Comment by mart-e** [comment]
Sorry about the no reply. Just tested and it worked fine. I don't have access to the google drive so I have to assume I tested correctly and it's now fixed.
Let me know if it's not the case and how I can reproduce it.
