### ISSUE TITLE
Right to left support in Odoo CE

### ISSUE THREAD

**Issue by j209** [odoo/odoo#29958]
Hi
Why Odoo CE  does not support rtl languages?
Odoo EE support right to left languages out of the box!

**Comment by Yenthe666** [comment]
Hi,

This was a choice made by Odoo. This won't be moved from enterprise to community as far as I know. @mart-e could you confirm please?

**Comment by f4kh** [comment]
`https://www.odoo.com/fr_FR/forum/aide-1/question/rtl-display-in-odoo12-ce-vs-rtl-display-in-runbot-143854`

**Comment by pedrobaeza** [comment]
Please put screenshots of what you think is not supported.

**Comment by mart-e** [comment]
Hi,

Indeed, the RTL has nothing to do with enterprise edition. It should works on both.
If you do not have the interface switched, it is probably on a local install without the nodejs `rtlcss` package installed. See the [source install documentation](https://www.odoo.com/documentation/12.0/setup/install.html#id3) for the reference to RTLCSS.
I just checked and it works fine on a community runbot.

As said Pedro, please add screenshots when you want to show a layout issue.

Closing as lack of details. We can reopen if we see there is a real problem in CE vs EE

**Comment by j209** [comment]
Persian(fa code) is a rtl culture.
![1](https://user-images.githubusercontent.com/18129232/50757643-3f100980-1275-11e9-88f4-c890ec8e5de7.png)

When we choose "fa" in the language prefrences:

![2](https://user-images.githubusercontent.com/18129232/50757843-be9dd880-1275-11e9-9754-b1066f3f09ff.png)

UI is steel ltr!

![3](https://user-images.githubusercontent.com/18129232/50757874-d4ab9900-1275-11e9-9fd7-2fb7376268f1.png)

**Comment by mart-e** [comment]
Thank you for the screenshots but I still have to reject it.
You are obviously tested on a non-standard interface. You have a custom theme so I would first test without it if you have or not the issue. Contact the author of the theme to see if it support properly the RTL.

As I mentioned above, if you are on premise, check that RTLCSS is correctly installed.
I just tried on the latest community and it works fine.

![screenshot_2019-01-07 po00005 - odoo](https://user-images.githubusercontent.com/564822/50758200-cce1f980-1261-11e9-920b-8aa05e6bc473.png)

**Comment by pedrobaeza** [comment]
@f4kh please don't insist more as it's a problem of deployment (or simply not reloading the browser), but @mart-e has already seen you that is working on runbot.

**Comment by f4kh** [comment]
@pedrobaeza  this is the CE of Odoo12 latest 
and  @mart-e demand the test on odoo standard interface so i uploaded those imgs

**Comment by pedrobaeza** [comment]
As said, RTL needs special requirements. Check them.

**Comment by f4kh** [comment]
@mart-e can you post the output of : npm list -g --depth 0

**Comment by mart-e** [comment]
@f4kh I have rtlcss 2.4.0 installed. Have you installed it as well?
If you have installed it after creating a odoo db, you will need to invalidate the assets to recompute it or check in debug=assets mode.

**Comment by j209** [comment]
![image](https://user-images.githubusercontent.com/18129232/50820796-dbeca880-1342-11e9-90d9-8fd3aab3acaf.png)

**Comment by j209** [comment]
I become realy confused.
I have installed odoo 12 and  rtlss  on my system.
when I choose a RTL lang, my UI in odoo is still LTR!

![image](https://user-images.githubusercontent.com/18129232/50824043-be234180-134a-11e9-9ebe-9feae46c8e49.png)

**Comment by d-fence** [comment]
As stated in [documentation,](https://www.odoo.com/documentation/12.0/setup/install.html#id3) you need to install rtlcss AND edit the System Environment’s variable PATH and add the folder where rtlcss.cmd is located.
Here is a screenshot on how to do that:

1. search for "path" in the windows start menu
2. choose "Edit the system environment variables"
3. in the dialog, click the "Environment Variables" button
4. Choose the "Path" line in the **second** pane named **"System variables"**
5. Click "Edit"
6. In the third dialog, click "Edit"
7. Add the Path (adapt to the user who installed npm, the one in the screenshot is a dummy one):
   It should look like this:
   C:\Users\YOUR_USER_NAME\AppData\Roaming\npm

Once it's done, restart the Odoo service and regenerate the assets.
It should work as you can see in the screenshot's background
 
![screenshot_win10_rtlcss png](https://user-images.githubusercontent.com/334923/50890442-7cea6a80-13fa-11e9-8d6d-0056ec966ea7.png)

**Comment by j209** [comment]
It works.
Thank you very very much.

**Comment by bista-nimesh** [comment]
Facing RTL issue with following scenario.
OS Ubuntu
1) Create database and install modules 
2) install RTLCSS after database creation.
3) load the Arabic Language.

Log is showing following warning

"You need https://rtlcss.com/ to convert css file to right to left compatiblity. Use: npm install -g rtlcss' RTLCSS https://rtlcss.com"

**Comment by mart-e** [comment]
How have you installed your odoo server?
Have your restarted the odoo services after installing rtlcss?
With the same user as the one executing the odoo code, run `rtlcss --version` to see if it works

**Comment by bista-nimesh** [comment]
@mart-e Thank you for your prompt response.

Please find attached screenshot.

![rtlcss](https://user-images.githubusercontent.com/12413451/58175232-50eec800-7cbd-11e9-8188-ee0182976e73.png)

**Comment by mart-e** [comment]
Sorry but if you see the error, it means that your Odoo service is not able to access rtlcss

https://github.com/odoo/odoo/blob/9db8497a995720384334b63dfc43ce689fa98712/odoo/addons/base/models/assetsbundle.py#L541-L546

Check your deployment with what I asked above but it is a bit hard to understand with so little information.

**Comment by salytwo** [comment]
I have installed rtlcss 2.4.0 but still have the issue demonstrated in the image link
https://ibb.co/kBfXNms

can you send me to any clue ?

**Comment by mart-e** [comment]
@salytwo your error seems unrelated, it is a js issue, not a RTL. Please open a new issue with exact steps on how you get in this situation (which version, which platform, how it was installed, which modules, which customisations....)

**Comment by imjaypatel** [comment]
Hi @mart-e 
I am facing issue in RTL. In my server when I running Odoo manually RTL working fine. However, when I running Odoo using service. RTL not working. Any specially configuration required in `sudo nano /etc/odoo-server.conf` file?

Here is my `/etc/odoo-server.conf` file contains,

> [options]
> ; This is the password that allows database operations:
> admin_passwd = admin
> xmlrpc_port = 8069
> logfile = /var/log/odoo/odoo-server.log
> addons_path=/odoo/odoo-server/addons,/odoo/custom/addons

Thank you.

**Comment by mart-e** [comment]
@imjaypatel please open a new issue for your problems, this one is closed.
Also, check your logs, this is probably an issue that your service does not have access to rtlcss binary.

**Comment by imjaypatel** [comment]
Issue open https://github.com/odoo/odoo/issues/42575
