### ISSUE TITLE
[Master] New tracking commit makes chatter display wrong records

### ISSUE THREAD

**Issue by hanyelbana** [odoo/odoo#29963]
Impacted versions:
[Master]
Steps to reproduce:
Create new invoice -> save it -> validate it
Current behavior:
4 tracking records in chatter for validate action
This error after tracking commit : https://github.com/odoo/odoo/commit/c2c5785940bfdd0eb620ba39ae3697ec63426915
Expected behavior:
Should be one tracking record with Status Draft -> Open

Video/Screenshot link (optional):

<img width="1103" alt="screen shot 2019-01-05 at 7 52 32 pm" src="https://user-images.githubusercontent.com/5108996/50726857-c8afc200-1123-11e9-868a-883159c4610c.png">

**Comment by hanyelbana** [comment]
This test from runout : http://422692-master-70f356.runbot11.odoo.com/web?#id=173&action=509&model=account.invoice&view_type=form&menu_id=330

**Comment by Yenthe666** [comment]
@tde-banana for you to check as you made that commit not long ago :D
