### ISSUE TITLE
[12.0] Chatter: fail to upload very big file

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#29964]
**Impacted versions:**

12.0

**Steps to reproduce:**

Try to add 2GB zip file to chatter.
Tested on local odo instance, no proxy.
Very high memory limits in config file.

**Current behavior:**

![image](https://user-images.githubusercontent.com/5862658/50729827-c1e37800-1140-11e9-858c-33d43ecac3d8.png)

**Expected behavior:**

Upload file

**Comment by Yenthe666** [comment]
Hi,

Odoo doesn't allow such big files by default. This is done by design. See this line for example:
https://github.com/odoo/odoo/blob/8f4b98e67fe49516c0c830524de351db67c58357/addons/web/static/src/js/fields/basic_fields.js#L1414

Regards,
Yenthe

**Comment by grzekru** [comment]
It is possible to add file bigger than 25mb.
User is not warned when adding very big file, he get error message after upload.

**Comment by Yenthe666** [comment]
Not by default. If you want to be able to do so you will need to override the JavaScript and change the limit to allow bigger attachments.

**Comment by grzekru** [comment]
It is possible to upload bigger attachments via chatter.
Just uploaded 300mb file using default configuration on newest commit odoo 12.
No need for JavaScript override.

**Comment by Yenthe666** [comment]
Hmm odd, I think it used to be the same across the whole framework. Maybe it changed in newer versions. @mart-e do you know from the top of your head?

**Comment by grzekru** [comment]
My client need to upload bigger attachments via chatter and there is no config option to change default limit. Other users may also rely on this feature.
I suggest to leave this in current form.

**Comment by mart-e** [comment]
Sorry but this is not something we can customize at the moment. Probably needs to be customized on client and server side.
