### ISSUE TITLE
[DOC] can't build html

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#29961]
Impacted versions:
12

Steps to reproduce:
install python3-sphinx
change to doc directory, and  `make html`

Current behavior:

still can't build the doc.
env:
 ubuntu 
 python3.5 
 sphinx  1.3.6

report  `  ValueError: Docs for BarcodeEvents (<class 'autojsdoc.parser.jsdoc.InstanceDoc'>) should be a dict or namespace `

details as 
> ubuntu@VM-0-4-ubuntu:~/odoo/doc$ make html
> sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
> WARNING: intersphinx inventory 'http://docs.sqlalchemy.org/en/rel_0_9/objects.inv' not fetchable due to <class 'urllib.error.URLError'>: <urlopen error [Errno 110] Connection timed out>
> 
> Exception occurred:
>   File "/home/ubuntu/odoo/doc/_extensions/autojsdoc/parser/parser.py", line 82, in deref
>     raise ValueError("%r (%s) should be a dict or namespace" % (obj, type(obj)))
> ValueError: Docs for BarcodeEvents (<class 'autojsdoc.parser.jsdoc.InstanceDoc'>) should be a dict or namespace
> The full traceback has been saved in /tmp/sphinx-err-b103d0y9.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:52: recipe for target 'html' failed
> make: *** [html] Error 1
> 

related issue #29197 

Expected behavior:
build doc successful.

Video/Screenshot link (optional):

[sphinx-err-v0kylu22.log](https://github.com/odoo/odoo/files/2729035/sphinx-err-v0kylu22.log)

**Comment by pedrobaeza** [comment]
But AFAIK, translations are handled in Transifex: https://www.transifex.com/odoo/odoo-12-doc/dashboard/

**Comment by jeffery9** [comment]
Transifex hostes user documentation, not technical documentation. thanks.

**Comment by Yenthe666** [comment]
Maybe we should make those terms available on Transifex. @mart-e thoughts? I guess if people want to translate it should be possible.

**Comment by mart-e** [comment]
No sorry, we do not wish to translate the technical documentation at the moment (I don't say never but it is not planned at the moment). Developers speak English most of the time anyway.

Will check the build error with @xmo-odoo because I believe we are hit by that one too.

**Comment by xmo-odoo** [comment]
@jeffery9 should be fixed, not sure why I didn't repro it on the previous issue.

**Comment by jeffery9** [comment]
can read Chinese version via http://geninit.cn/doc/

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [DOC] can't build html (#29961)
发件人：xmo-odoo
收件人：odoo/odoo
抄送：Jeffery CHEN Fan ,Mention


@jeffery9<https://github.com/jeffery9> should be fixed, not sure why I didn't repro it on the previous issue.

―

**Comment by pedrobaeza** [comment]
> can read Chinese version via...

This is a way of speaking... :stuck_out_tongue_closed_eyes:

**Comment by jeffery9** [comment]
It's not authentic, but it can still be understood

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [odoo/odoo] [DOC] can't build html (#29961)
发件人："Pedro M. Baeza"
收件人：odoo/odoo
抄送：Jeffery CHEN Fan ,Mention


can read Chinese version via...

This is a way of speaking... 😝

**Comment by pedrobaeza** [comment]
Yeah, it was a joke, as for us occidental people, Chinese is not very readable. Congratulations any way by the effort.

**Comment by Yenthe666** [comment]
"not very" is really an understatement @pedrobaeza 😆
