### ISSUE TITLE
website_sale_comparison: attributes are not ordered with sequence

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#29980]
Impacted versions: master, 12, 11

Steps to reproduce:
Add attribtes with custom sequence to some products and compare them on website shop.

Current behavior:
Attributes are listed in random order because they are placed in [dictionary](https://github.com/odoo/odoo/blob/12.0/addons/website_sale_comparison/controllers/main.py#L20-L30).

Expected behavior:
Attributes should be listed same way as they appear on backend.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You can use Python 3.6 that has ordered dictionaries by default.

**Comment by lem8r** [comment]
> You can use Python 3.6 that has ordered dictionaries by default.

Thank you. It works as quick fix.

Since Odoo.sh and docker image are using Python 3.5 I think it should be fixed in code as well.
I can do a PR if OrderedDict is fine.

**Comment by JKE-be** [comment]
@lem8r 

PR is welcome, thank you

**Comment by lem8r** [comment]
Well, I started with 11.0.
It doesn't have `product_tmpl_id._get_valid_product_template_attribute_lines()` as opposite to 12.0 and master, so I had to sort attributes with search..

**Comment by JKE-be** [comment]
Target 12 only (will be fwdported to master)

**Comment by lem8r** [comment]
Okay

**Comment by lem8r** [comment]
@JKE-be What about 11.0? We have enterprise customer that is facing this issue and they are not planning to upgrade in near future.
