### ISSUE TITLE
11.0 How to deal with tax in website order with multi company products?

### ISSUE THREAD

**Issue by AjayViknesh** [odoo/odoo#29987]
I am using Odoo 11:

Lets assume there are 3 companies C1, C2, C3. C2 and C3 are child companies of C1.

Lets assume there is 18% tax available in C1, C2 and C3.

C1 adds C2 and C3 tax while creating the product.

C2 and C3 publish their products with tax in the C1 website. Customer purchases C2 products from website. Tax is applied for the product and C1 is able to see the tax in the order.

But C2 is not able to see the tax in the order/quotation table, but tax has been calculated with the total.

Same for C3 products purchased from website.

I need to apply different company tax for that company product and that company needs to see that too.

Please give me a solution for this.

Thank you

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by AjayViknesh** [comment]
@pedrobaeza This is question as well as an issue. Why is the child company tax not apply to the product when purchased from the website.

**Comment by pedrobaeza** [comment]
Multi-company doesn't work that way.
