### ISSUE TITLE
[8.0] website_quote ignores price list rules

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#2999]
Prerequisites:
- sale price list with a discount on a product category
- a quote template with product of this category

Actions:
- Create a sale quotation
- select price list
- select quote template

The price list rule is not applied on products in quotation.

**Comment by pna-odoo** [comment]
Here, I think no need to apply pricelist as in template we already allow discount.

**Comment by jeffersonLPAUS** [comment]
Hi Guys, having the same issue on the sales quotation(Not Web_quote) any ideas?

**Comment by RangerMcFriendly** [comment]
Still no solution on this? Have the same problem (also in sales quotation)
