### ISSUE TITLE
[11] CE, EE: Wrong quantity in stock delivery order when selling multiple lots in Point of Sale

### ISSUE THREAD

**Issue by carloselinge** [odoo/odoo#30006]
**Impacted versions:** Odoo 11. Community  (Odoo C) and Odoo 11 Enterprise (Odoo E)

**Steps to reproduce:**

Then I will put images of the odoo community as well as the enterprise so that no doubt what happens in both

**1.-** Create the Product

Odoo C

![image](https://user-images.githubusercontent.com/29591038/50801110-efe3cc00-12a8-11e9-8382-17c20d61a0ef.png)

![image](https://user-images.githubusercontent.com/29591038/50801143-0f7af480-12a9-11e9-847f-455212c3cd8b.png)

Odoo E

![image](https://user-images.githubusercontent.com/29591038/50801056-c32fb480-12a8-11e9-9b3a-124816dd32de.png)

**2.-** Buy it in the same transaction with different lots, in this case lot 12345 will buy 2 pieces and in lot 54321 will buy 3 pieces

![image](https://user-images.githubusercontent.com/29591038/50801238-6b457d80-12a9-11e9-9f65-e378f20efceb.png)

![image](https://user-images.githubusercontent.com/29591038/50801268-916b1d80-12a9-11e9-80b6-7ebdf69e92dc.png)

![image](https://user-images.githubusercontent.com/29591038/50801289-a647b100-12a9-11e9-8d36-51031af05281.png)

**3.-** The sale is made

![image](https://user-images.githubusercontent.com/29591038/50801342-e0b14e00-12a9-11e9-9595-a7988aadf6c3.png)

**4.-**The transaction is reviewed

Odoo C
![image](https://user-images.githubusercontent.com/29591038/50801491-9f6d6e00-12aa-11e9-9e72-465d840cc58b.png)

Odoo E
![image](https://user-images.githubusercontent.com/29591038/50801499-a5634f00-12aa-11e9-9212-6f0451de1af2.png)

As we can see the sale is correct they sold the 2 products of one lot and the 3 products of the other and the total is correct

**5.-** The inventory transfer of that transaction is reviewed

**We realize that the inventory moved by 10 units not by 5 as it should be**

Odoo C

![image](https://user-images.githubusercontent.com/29591038/50801718-c0828e80-12ab-11e9-8f72-35aad1af4774.png)

![image](https://user-images.githubusercontent.com/29591038/50802203-16efcd00-12ac-11e9-85c1-ffcab6333edc.png)

![image](https://user-images.githubusercontent.com/29591038/50802355-2c64f700-12ac-11e9-98f9-62a413ec3e32.png)

Odoo E

![image](https://user-images.githubusercontent.com/29591038/50802504-3f77c700-12ac-11e9-90c9-c9b5bc17eabd.png)

![image](https://user-images.githubusercontent.com/29591038/50802602-a301f480-12ac-11e9-8154-2bc090c19fb0.png)

And here it is confirmed that the system instead of moving 5 elements (2 "12345" and 3 "54321") moved 5 elements of each lot causing the inventory to be out of stock for 5 products

> Everything was reproduced in the official runbot 

Odoo C
http://423598-11-0-c07b72.runbot11.odoo.com/web#menu_id=133&action=148&active_id=channel_inbox

Odoo E
http://423578-11-0-1640c0.runbot18.odoo.com/web?#home

**Comment by pedrobaeza** [comment]
Hehe, don't be so dramatic about the corruption...

@switch87 can you take a look to this bug?

**Comment by carloselinge** [comment]
what one does for attention, but I think if it was too much, that's why I changed it

**Comment by carloselinge** [comment]
Incredible, for me at this moment is 5 am, then after I sleep another little I will run to review it, thank you very much for the support and so fast answer

**Comment by Adham-Bakry** [comment]
could you please send me the addon for this solution because when i sold product with different lot number it create one lot but it surplus the quantity in the picking order
