### ISSUE TITLE
How to set dynamic value in tree parameter?

### ISSUE THREAD

**Issue by zsdostar** [odoo/odoo#30015]
**Impacted versions:**
Odoo 10.0+e (Enterprise)

**Steps to reproduce:**
set dynamic value in tree parameter.
1)`<tree create="0" edit="1">`
It's not dynamic, so it does't match any requirements.

2)`<tree create="[('state','!=','done')]" edit="1">`
Does not take effect and gives an error.

Error message: 
```
Unknown CORS error
```
```
An unknown CORS error occured. The error probably originates from a JavaScript file served from a different origin. (Opening your browser console might give you a hint on the error.)
```

3)`<tree create="state!='done'" edit="1">`
Error is the same with above.

4)`<tree attrs="{'create':[('state','!=','done')]}" edit="1">`
No effect or error.

**Current behavior:**
error or no effect

**Expected behavior:**
set value dynamic successful

**Video/Screenshot link (optional):**
https://stackoverflow.com/questions/54088254/how-to-set-dynamic-value-in-tree-parameter

**Comment by pedrobaeza** [comment]
This feature is not possible currently, and doesn't make sense also, as you are trying to Durmid creating records based on a field of which record?

Closing any way as this kind of questions should happen on the odoo forums.

**Comment by zsdostar** [comment]
> This feature is not possible currently, and doesn't make sense also, as you are trying to Durmid creating records based on a field of which record?
> 
> Closing any way as this kind of questions should happen on the odoo forums.

Sorry about that my description is not clear.
The problem is solved. thanks.
```
<field>
    <tree attrs="{'create':[('parent.state','!=','done')]}">
     
    </tree>
</field>
```
I made a low-level mistake that I replace the attrs in another module, and the "state" should be "parent.state".
