### ISSUE TITLE
Pricelist rule based on category not working properly

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#30036]
#### Impacted versions:
- 11.0, 12.0

#### Steps to reproduce:
- Create a Pricelists based on category
- Set category 'Shirts', with a 20% discount with 2 items minimum
- Sell Shirt A and Shirt B (both from the **Shirts** category)

#### Current behavior:
- For the 20% discount to take place it's requiring the products to be same.
- Selling Shirt A and Shirt B on the same order is not applying the discount.

#### Expected behavior:
It's very common for the Retail Industry to make discounts on a whole category if 2 items from the same category are bought, and this should to be the intended behavior of applying the rule on a whole category with a minimum of products set.

**Ticket #1924262**

**Comment by fgi-odoo** [comment]
No pricelists are used to compute the price of the very line you add to an order. To manage promotions based on several order lines, you can rather use Coupons & Promotions (in Odoo Enterprise). You can almost manage your case in standard: https://drive.google.com/a/odoo.com/file/d/1I71o7VTtmuRb3oufKiJmerDvYEuYpFp5/view?usp=drivesdk. The discount applies to the cheapest product of your order or to the entire order.
