### ISSUE TITLE
OFX import: start balance is in fact end balance

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#3003]
Here are the steps to reproduce the bug on Odoo master:
1) install account_bank_statement_import_ofx
2) get an OFX file from your bank from the first day of this month until today. Write down the current balance of your bank account
3) Import the OFX file in Odoo and open the resulting bank statement:
You will see that the current balance of your account is displayed as the "Starting balance" in Odoo and that the "Ending balance" in Odoo is wrong.

Here is the explaination:
The OFX file contains the balance of the bank statement inside the <LEDGERBAL> tags: there is an amount and a date. When you look at the file, you will see that this amount corresponds to the ending balance... but openerp interprets this as the starting balance ! This is confirmed by the OFX samples files given on the official OFX website: http://www.ofx.net/OFXExamplesPage/OFXExamples.aspx

I was able to reproduce this bug with an OFX file of La Banque Postale (French bank).

Here is a patch that fixes the bug:
http://people.via.ecp.fr/~alexis/fix-ofx-balance-import.diff

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
