### ISSUE TITLE
Upgrade mail throws an error in pricelist version

### ISSUE THREAD

**Issue by jobiols** [odoo/odoo#3004]
Hi
I get an error when upgrading mail (Social Network) module, here are detailed steps to reproduce the bug Running OpenErp v7 on Ubuntu 14.0.4 LTS

Steps to reproduce:
1- Create a new database
2- Install sale module with default options
3- in Settings / Sales  ---> check “Use pricelists to adapt your price per customers”
4- in Pricelist / Pricelist version --->    delete “Default Public Pricelist Version”
5- Create an empty Pricelist
6- Upgrade module mail (Social Network)

An error comes:

"Error occurred while validating the field(s) date_start, date_end: 
You cannot have 2 pricelist versions that overlap!"

The database becomes useless...

it seems that te validation procedure tries to install the default pricelist and this overlaps with the one we just add.
It doesnt happen if we rename instead of delete and add the pricelist version.

**Comment by Yenthe666** [comment]
Hi @jobiols,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
