### ISSUE TITLE
[11.0 Enterprise] PayPal IPN charset set to utf-8 but receiving windows-1252

### ISSUE THREAD

**Issue by bhumiht** [odoo/odoo#30050]
Impacted versions:  11.0 Enterprise

**Comment by Yenthe666** [comment]
Hi,

Please fill in the steps for reporting a bug or issue. We should have reproducible steps with info/context to what you did.
P.S: Why don't you make a ticket on odoo.com/help by the way? You have an enterprise license. Bugs reported there are handled with a higher priority.

Please add more information to your report.

Regards,
Yenthe

**Comment by bhumiht** [comment]
Reproducing Steps:

1. Configure Paypal settings in odoo
2. Set Return URL in PayPal
3. In PayPal settings set Charset "UTF-8"
4. But when i tried to paid amount in paypal and after that redirect on order confirmation page and receive Invalid/Fail and in Charset return windows-1252

![shop confirmed my website](https://user-images.githubusercontent.com/46513719/50938921-a7a5f300-14ce-11e9-9d0f-29a8522f650f.png)

**Comment by bhumiht** [comment]
Hello

can any one give me some update for this issue.

Thanks

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
