### ISSUE TITLE
Activate Developer Mode is available for default Portal User Access rights.

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#3005]
Current default access rights for portal users allow portal users to activate developer mode.

**Comment by aftabnaveed** [comment]
This is still an issue.

**Comment by lukebranch** [comment]
this is in my mind a bit of a security issue. Perhaps there is no actual access available to anything useful for a would-be hacker, however this should definitely not be available to the end portal user in my opinion.

**Comment by aftabnaveed** [comment]
Correct we have it disabled by overriding the view, but it should not be
visible to portal user in first place

**Comment by aftabnaveed** [comment]
We fixed that issue by overriding the view, but this should not be visible to portal group in first place.

**Comment by Yenthe666** [comment]
@lukebranch and @aftabnaveed this is indeed correct, a portal user has the ability to enable the developer mode.
@mart-e and @odony is this something you guys would want to change or not? I find this a bit too much access rights for a portal user but that is my personal opinion.

**Comment by odony** [comment]
Well, you know how the security model works in Odoo: it's implemented at the ORM level, per-model, and not in the view/UI. The "developer mode" is a "debug mode" that displays technical fields and technical info, and provides a few shortcuts mostly useful for developers.
So having it for portal users is not a security issue, in the sense that it only shows you what you could have obtained through other means anyway (e.g. via direct RPC calls or by playing with the URL). This is a very important distinction.

Showing it to portal users is not particularly useful, but if a portal user is knowledgeable enough to use it and get info you did not want them to get, chances are they would have gotten the info without it as well ;-) (Remember: dev mode does not change your access rights in any way)

If someone wants to make a PR for master to hide the dev mode link for non-employees I won't veto it, but for now I'd close this issue as a minor wishlist.

**Comment by fpodoo** [comment]
Actually, we should remove the backend access to portal users and implement
the portal features in the front-end only. (Not because of security issues,
but more for usability)

**Comment by Yenthe666** [comment]
Yep, that is a very good idea. I hope somebody writes this down as to do? Would be neat to have it available in Odoo 10.

**Comment by lukebranch** [comment]
thanks for looking into this. I definitely agree on moving all portal features to the frontend only.

**Comment by AEK-BKF** [comment]
Any news?

**Comment by lukebranch** [comment]
@AEK-BKF ,

Take a look at v10 on the runbots. Once you're logged in as admin just go to the frontend website and click the dropdown for 'my account' to see what's there already in 10.0.

Odoo SA has done an awesome job moving most of the previous portal-only features to the website portal, and I believe that there is alot more on the way in v11 as well. 

I have also heard that Odoo has more in store for v11, and will be de-coupling the backend widgets from the backend, to allow them to be used on the frontend/website as well.
