### ISSUE TITLE
Demo site dont affect rtl langs.

### ISSUE THREAD

**Issue by j209** [odoo/odoo#30064]
Hi
I set fa lang(rtl)  as default in demo site.
UI is still ltr.
![12rtl2](https://user-images.githubusercontent.com/18129232/50894070-8fbf6800-1417-11e9-98b3-b7d7cf37a745.png)
![12rtl](https://user-images.githubusercontent.com/18129232/50894079-93eb8580-1417-11e9-96ea-12ec04623906.png)

**Comment by pedrobaeza** [comment]
Why do you repeat issues? This is a problem in your deployment, and Odoo colleagues have already told you how to do proper deployment.

**Comment by j209** [comment]
Whell demo site must work correctly!!

**Comment by pedrobaeza** [comment]
Which demo site?

**Comment by j209** [comment]
odoo demo site

**Comment by pedrobaeza** [comment]
Sorry, but this is out of scope. Runbot is working with RTL as proved, so that's enough.
