### ISSUE TITLE
[8.0]Public user can't get membership_lines

### ISSUE THREAD

**Issue by rainberg** [odoo/odoo#3006]
When the public user can vist the detail of members ,but they cant got the list of members.

ie.

http://www.wocai.org/members/11

http://www.wocai.org/members

how to set the right rights for public?

**Comment by mart-e** [comment]
To be public, a member should have "website_published" enabled on his partner and belong to a membership that is published as well.
Seems to work fine on runbot so closing but let us know if there is a bug.
