### ISSUE TITLE
Use Shift+Alt instead of Alt for hotkeys

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#30068]
**Impacted versions:** 12.0

**Current behavior:**

Odoo 12.0 started a "new"<sup>1</sup> feature where the user is empowered (and encouraged) to use hotkeys to make keyboard navigation easier and faster.

However, the new choice of using <kbd>Alt+[letter/number]</kbd> introduced some inconsistencies. Some of them are documented inline, as you can see here: https://github.com/odoo/odoo/blob/1e9ed52052f9537a210bcc9025c056c5b40e59b2/addons/web/static/src/js/chrome/keyboard_navigation_mixin.js#L20-L22

:point_up: That's possibly why now "Edit" is wierdly triggered by <kbd>Alt+A</kbd>, "Discard" by <kbd>Alt+J</kbd> and the apps menu by <kbd>Alt+H</kbd>. However, this, although it is weird, is not the worst problem.

Another conflict that has not been considered an inconsistency, but it is, is that **users lose the ability to use <kbd>Alt+[number]</kbd> to change the tab in the browser**. It will work in any tab that is not Odoo 12 (In Firefox and Chrome at least). This new feature is supposed to increase users' productivity, but a previously-productive-enough user that used those hotkeys will see its productivity reduced instead.

Another problem that you can see here is that, if you use Firefox with hidden menu bar, the Alt key displays it, which **produces clutter and alters users' focus**:

![peek 09-01-2019 11-40](https://user-images.githubusercontent.com/973709/50897242-744a6200-1403-11e9-9322-090767e52f67.gif)

**Expected behavior:**

<kbd>Shift+Alt</kbd> was good enough, it should have been kept. I imagine it's too late in the release cycle to change that, but it would be a good enhancement for master. 

---

<sup>1</sup> Actually using hotkeys is not new. However, it's true that it was a somehow "hidden" feature that was available since, at least, Odoo 8.0, where it used [the native `accesskey` feature that browsers have since HTML 4.1](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey), as you can see here: https://github.com/odoo/odoo/blob/9e8f70e4849b0eeaca8b5cf51372ecfa23dc561b/addons/web/static/src/xml/base.xml#L835-L847

The new approach breaks workflow of power users that were using this feature already previously.

**Comment by pedrobaeza** [comment]
@mart-e another generic one that we summon you for piping it to the proper team.

**Comment by VincentSchippefilt** [comment]
Hello @Yajo,

Thank you for your feedback. I acknowledge the problem you mention. I have implemented exactly this on purpose to help most users see and activate the shortcuts using the same keys over all browsers/OS's.

I don't think we want to implement your proposition as it is, as it would make the life harder for other people to use shortcut keys.
I have however created a feedback on our DB to allow users (especially power users) to configure which key combinaison should show and activate the access keys. I think this solution would help you while not making life more complicated for other users.

I don't know if/when this feedback will be implemented, but this is now managed by our feedback system and this issue can be closed.

Kind regards,
Vincent.

For our reference, the task ID is 1925301

**Comment by Yenthe666** [comment]
Making it configurable sounds like an awesome idea. I hope it gets accepted.

**Comment by imaistecnologia** [comment]
Hi, I install https://www.odoo.com/apps/themes/12.0/openworx_backend_theme/ and https://github.com/OCA/web/tree/12.0/web_responsive, but when i activated the theme the dashboard apps are gone.
https://imgur.com/a/OyHHgBy

https://imgur.com/a/KjZAT7j

**Comment by yostashiro** [comment]
`shift + alt` is something I often use to switch between languages (Japanese, English and Chinese), so it brings to me some usability issues if this combination is used for the hotkeys. I guess not many people do the same but some would certainly be affected.  +1 for making them configurable.

**Comment by gdgellatly** [comment]
On some chrome based browsers, alt highlights the hotkeys, but only shift +  alt works to use them. Vivaldi for 1 does that, so good solution for the alt haters.

**Comment by pedrobaeza** [comment]
@VincentSchippefilt can you give us any feedback about this task? Thanks.

**Comment by rafalkrupinski** [comment]
Is this configurable in any way in version 17?
