### ISSUE TITLE
Wrong order date and time on POS sales orders

### ISSUE THREAD

**Issue by olubiyi80** [odoo/odoo#30089]
Impacted versions:
Odoo v12

Steps to reproduce:

Current behavior:
Order date displaying different dates and time for Point of sales in the same time zone. Session open and closing dates are correct, but wrong dates and time on POS order date.

I've tried confirming user timezone and server timezone, they are correct. How can I set date and time for odoo.

Expected behavior:
Order date should be same with server. and should tally with session dates.

Video/Screenshot link (optional):

Thanks.

**Comment by switch87** [comment]
Hi @olubiyi80, Point of Sale is an offline JavaScript application inside Odoo, this includes the time of orders. The orders will take the time of your computer, the opening and closing on the other hand will take the time based on the clock and timezone of the server.

**Comment by Ngailo** [comment]
Hi,

Am using Odoo V13 Comunity, I am facing the same issue regarding order date displaying different dates and times for Point of sales.

Any solution for this?
![pos wrong date and time](https://user-images.githubusercontent.com/37793768/120712619-8a23ba80-c4c9-11eb-9aab-73c9ed248a88.PNG)
