### ISSUE TITLE
 convert Many2one field into Many2many field without losing any data?

### ISSUE THREAD

**Issue by jaballi** [odoo/odoo#30086]
I have a Many2one field already works in a lot of records in a point of sale  , now is needed that this field to convert Many2many  , is possible just change the field type from Many2one to Many2many without losing any data?

If yes, what's the correct way to do it? if not, how to do it?

thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
