### ISSUE TITLE
V12 email flag in contact communication

### ISSUE THREAD

**Issue by jcleonard2018** [odoo/odoo#30083]
Impacted versions: V 12

Steps to reproduce: difficult to reproduce

Current behavior: emailing followup alert

Expected behavior: spliting emailing alert from technical internal alerts

Video/Screenshot link (optional): 2019-01-08_16h14_01.zip

**Comment by jcleonard2018** [comment]
Hello, 
Sometimes we get a flag on message queue.
This flag indicate a confict. Users don't understand the meaning and send again the message. Nevertheless, the message havve been already sent.
I have attached a video explaining the issue. 
Is their a solution not displaying this alert if the message is sent?
What is the reason of issue correponding to the message concurrent acces?

[2019-01-08_16h14_01.zip](https://github.com/odoo/odoo/files/2741646/2019-01-08_16h14_01.zip)
Thank you
Jean-Christophe LEONARD
+33608321097

**Comment by pedrobaeza** [comment]
That flag is because the mail server has informed Odoo that the mail hasn't been delivered, so it's correct that appear. You should check why the mail server do this, but this is not an Odoo fault. Maybe mail server is not informing the correct delivery and that's why Odoo do this.

Any way, this is not an Odoo problem per se, so closing this.

**Comment by jcleonard2018** [comment]
The issue is that email was delivered but we received an error linked to an internal database conflict. I think the issue is different. Like a conflict inside odoo.

**Comment by pedrobaeza** [comment]
Then put what is the "internal database conflict". Log traceback or something. What you have to fix is that conflict. Maybe you have some third party modules that causes them.
