### ISSUE TITLE
[V12] web_studio: Uncaught TypeError: Cannot read property 'off' of undefined

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#30087]
**Impacted versions:**
v12

**Steps to reproduce:**

- activate studio (in home)
![image](https://user-images.githubusercontent.com/19410285/50924130-13cc1c80-1425-11e9-8ae0-3a165efec836.png)

- Try to go to accounting (for now the error is only in accounting)
![image](https://user-images.githubusercontent.com/19410285/50924164-2f372780-1425-11e9-819e-d42c68967c13.png)

**Current behavior:**
![image](https://user-images.githubusercontent.com/19410285/50924210-4e35b980-1425-11e9-82ad-c5d014b60dcd.png)

**Expected behavior:**
go to accounting

**Video/Screenshot link (optional):**
https://youtu.be/5n9PP_e2UAo

**Comment by Yenthe666** [comment]
Hi @GavyMG,

Thanks a lot for your report.
I've just tested this on the latest Odoo 12 but it seems to work fine. Can you still reproduce the problem on the latest official test instance at runbot.odoo.com?

Regards,
Yenthe

**Comment by GavyMG** [comment]
Hi @Yenthe666 

Yes, I can still reproduce it like in the video. 

PD: using the last instance in odoo/enterprise v12.

Regards.

**Comment by Julien00859** [comment]
A workaround is to first open accounting without studio then go back in the menu and re-open accounting using studio
