### ISSUE TITLE
expression.OR([[(0, '=', 1)]]) returns []

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#30113]
`expression.combine` optimises out the "unit" entirely, and while `OR([A, FALSE_DOMAIN])` is `A` `OR([FALSE_DOMAIN])` or `OR([FALSE_DOMAIN, FALSE_DOMAIN])` should be `FALSE_DOMAIN`.

The issue also applies to `expression.AND` though to a lower extent: because `AND([TRUE_DOMAIN])` combines to `[]`, `OR([AND(TRUE_DOMAIN), B])` will be combined to `B` when it should be `TRUE_DOMAIN`.

**Comment by pedrobaeza** [comment]
I think this is the same I reported some time ago in #26540
