### ISSUE TITLE
[10.0, 11.0, 12.0] The "is a Scrap Location?" checkbox in Location doesn't work as expected

### ISSUE THREAD

**Issue by MouTio** [odoo/odoo#30112]
Impacted versions: 
9.0, 10.0, 11.0, 12.0

Steps to reproduce:
1. Create a new location. This new location doesn't have a "Parent Location" and it is not a scrap location (the checkbox of **"is a Scrap Location?"** is not selected).
2. Go to Inventory -> Products -> Select a random product.
3. Click on "Update Qty on Hand"
4. Select the new location and put some quantity, for example 10.

Current behavior:
The quantity is updated in the "Product Moves", but the new quantity doesn't appear in the stock "On Hand". It appears that the new location is treated as scrap.

Expected behavior:
If the location is not selected as scrap, the quantity has to appear in the "On Hand".

Screenshots:

1:  Create a new location. This new location doesn't have a "Parent Location" and it is not a scrap location (the checkbox of **"is a Scrap Location?"** is not selected).
![scrap_location_1](https://user-images.githubusercontent.com/17930296/50975710-87862c00-14ee-11e9-8a9a-18e8687c30eb.PNG)

2: Go to Inventory -> Products -> Select a random product. -> Click on "Update Qty on Hand".
Select the new location and put some quantity, for example 10.
![scrap_location_2](https://user-images.githubusercontent.com/17930296/50975732-9240c100-14ee-11e9-9720-092606fab41a.PNG)

3: The quantity is updated in the "Product Moves"
![scrap_location_3](https://user-images.githubusercontent.com/17930296/50975734-9240c100-14ee-11e9-88b2-b6a3347a9a27.PNG)

Step 4: The new quantity doesn't appear in the stock "On Hand"
![scrap_location_4b](https://user-images.githubusercontent.com/17930296/50975994-2874e700-14ef-11e9-8d86-6f1337d2efe4.png)

**Comment by pedrobaeza** [comment]
It's not going to appear in the "On hand", as it's not a child of any warehouse stock location. Scrap thing is not related to that.

Closing as no valid.
