### ISSUE TITLE
[11.0] project tasks: Portal users can't see it's own tasks created from SO

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#30127]
Impacted versions:
11.0 maybe 12.0
Steps to reproduce:
- Create a Portal user with wizard portal access management
- Login with the portal user credentials
- Create and confirm SO
- tasks created from SO confirmed cannot saw by portal user
Optional
website sign feature.

Current behavior:

Portal user can't see tasks
Expected behavior:

Portal user can see all it's own and related tasks

Video/Screenshot link (optional):

Replicated at http://425811-11-0-3690c8.runbot13.odoo.com
See 
https://youtu.be/qmDFoM8j21o

OPW 1925720

**Comment by pedrobaeza** [comment]
For that purpose, you must change associated project visibility configuration, setting to following customers.

Closing as no real issue.

**Comment by hugho-ad** [comment]
@pedrobaeza 
Its done at minute 5:34 https://youtu.be/qmDFoM8j21o

![capture _2019-01-13-13-46-52 2](https://user-images.githubusercontent.com/10233975/51089946-729dd880-173a-11e9-8e96-162ff0300287.png)

Please reopen it
Regards!

**Comment by pedrobaeza** [comment]
But you haven't added the partner to the followers...

**Comment by hugho-ad** [comment]
@pedrobaeza 

That is an extra step that must not exist since the task is owned by the portal user itself. 

That is a part of this issue.

You should reopen this

Regards!

**Comment by pedrobaeza** [comment]
If you don't want that extra step, you must modify your record rules, but right now, this is the flow and this can't change in this version. Any way, I consider that correct.

**Comment by hugho-ad** [comment]
@pedrobaeza 

I made a new test but not adding the portal user as a follower of the task, the task appears on the task count list at my account page but the portal user can't see the tasks it' self because following 500 error

what do you think?

I followed the steps at the video, just adding the portal user to the followers.

![image](https://user-images.githubusercontent.com/10233975/51118797-d5dd4880-17d6-11e9-8a3f-28824f3d93f5.png)

![image](https://user-images.githubusercontent.com/10233975/51118801-d83fa280-17d6-11e9-9d4b-caa35343bebb.png)
![image](https://user-images.githubusercontent.com/10233975/51118911-1b017a80-17d7-11e9-827b-2d8022d34259.png)

![image](https://user-images.githubusercontent.com/10233975/51118905-176df380-17d7-11e9-97fc-d66c2b2e79e0.png)

Regards!

**Comment by pedrobaeza** [comment]
As said, you have to add it as follower to the project and to the task.

**Comment by hugho-ad** [comment]
nothing changed after doing that 

![image](https://user-images.githubusercontent.com/10233975/51119882-8a786980-17d9-11e9-807d-891f98d47962.png)

![image](https://user-images.githubusercontent.com/10233975/51119902-96fcc200-17d9-11e9-84a0-9b0a5f412660.png)

**Comment by hugho-ad** [comment]
@pedrobaeza 

did you see my last comment?

**Comment by moylop260** [comment]
@nim-odoo @nhomar 
Could you re-opening this issue since that it was closed so early by @pedrobaeza, please?

**Comment by pedrobaeza** [comment]
I'm reopening it until I have time to prove you what I'm saying.

**Comment by hugho-ad** [comment]
At version 12.0 the flow works as @pedrobaeza described

Just adding the portal user as a follower of the task and the portal user can see the task.

See the next video
https://youtu.be/8LOuoIhQE04
