### ISSUE TITLE
errors in reorder point procedure

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#3012]
Dear Consultant,
I've noticed two errors in the reorder point procedure:
1) the purchase lead time should be added for calculating the planned delivery time; so we have as follows: 
planned delivery date = today (day of planning run) + delivery lead time + purchase lead time .... calculated in forward mode
document date = today (day of planning run)

2) in case the planning delivery date is laying after the total lead time (delivery lead time + purchase lead time) another PO/RfQ should be generated, otherwise we are out of stock.

Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
