### ISSUE TITLE
Uncaught TypeError: Cannot read property 'static' of undefined

### ISSUE THREAD

**Issue by csapatenio** [odoo/odoo#30128]
Impacted versions:
Odoo11

Steps to reproduce:
- Generate Expense Report through Submit to Manager button in the expense
- Click Add an Item
- Select all expenses (must be more than 40 expenses)
- After clicking Select the error occurs

Current behavior:
- Uncaught TypeError occurs
- After closing the wizard, the page won't work anymore. You need to reload the page

Expected behavior:
- Must add all selected expenses to the expense report

Video/Screenshot link (optional):
![selection_193](https://user-images.githubusercontent.com/10607307/51011168-6b3bcb00-1592-11e9-82f4-b1ee99ff75ee.png)

**Comment by robles29** [comment]
Could you solve this? having a similar problem

**Comment by pedrobaeza** [comment]
Is this reproducible with latest code?

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
