### ISSUE TITLE
Point of sale returns v11

### ISSUE THREAD

**Issue by BrayhanJC** [odoo/odoo#30125]
Impacted versions: V11

Steps to reproduce: 
Select a product x,
Indicate quantity 1 or other,
Select +/-

![1](https://user-images.githubusercontent.com/2817970/50991871-b1862100-14e3-11e9-9a16-8e1a5e5068b7.PNG)
![2](https://user-images.githubusercontent.com/2817970/50991872-b21eb780-14e3-11e9-814c-7329d706b66a.PNG)

Current behavior: When a return of the product is made, it removes the taxes that this has

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
According screenshots, there seems to not be any problem. Can you be more specific about the problem and put screenshots about that?

**Comment by BrayhanJC** [comment]
In this case, you would have to return 178500, and not 150000. The taxes should also be 25000 and not 23949

**Comment by pedrobaeza** [comment]
Then what you are talking about is of the pricelist application, not on the taxes, but this can't be checked without having all the records. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by BrayhanJC** [comment]
I already made the respective changes, create a new product. I send captures. In this instance http://425666-11-0-617652.runbot14.odoo.com

![11](https://user-images.githubusercontent.com/2817970/50993921-d03ae680-14e8-11e9-8c5d-2c3fb5ff56a7.PNG)
![22](https://user-images.githubusercontent.com/2817970/50993922-d0d37d00-14e8-11e9-9369-57b48e117bfc.PNG)

**Comment by pedrobaeza** [comment]
Thanks for the extended information, but I still don't get how to get the problem. Is it possible a video with the steps?

**Comment by BrayhanJC** [comment]
1 Case
The product x, has a value for its sale of 178.50 + taxes of 26.78 for a total of 205.28.
178.50 + 26.78 = 205.28
This happens when we select x amount of said product, for now there is no problem. The quantity is positive (+)

2 Case
When you select a quantity of product x, and press the +/- button, in order to have a negative quantity (-1) Unit (s). The value of the product changes.

With positive sign (+) = 178.50 + 26.78 = 205.28

![111](https://user-images.githubusercontent.com/2817970/50996041-e8156900-14ee-11e9-982b-bce6143a2ef0.PNG)

With negative sign (-) = - 150.00 - 22.50 = -172.50

![222](https://user-images.githubusercontent.com/2817970/50996051-ecda1d00-14ee-11e9-997b-2882cc09ee87.PNG)

**Comment by BrayhanJC** [comment]
this is being done...
https://www.odoo.com/documentation/user/11.0/accounting/others/taxes/B2B_B2C.html

**Comment by Yenthe666** [comment]
@switch87 could you have a look maybe?

**Comment by switch87** [comment]
@BrayhanJC I tried to reproduce this but didn't manage to do so. Is this still happening?

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as there has been no more feedback on the last question. We assume that the problem has been solved in the meanwhile. If this is not the case then don't hesitate to respond back (with feedback) and we'll reopen it.

Regards,
Yenthe
