### ISSUE TITLE
account: Supplier --> payments, wrongly showing Point of Sale client's change

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#30143]
### Impacted versions:
All

### Steps to reproduce:
- Make a sale in the POS, with a total amount of $900
- Receive $1,000 as payment
- Validate the order

### Current behavior:
- $100 is returned to the client as *change*
- Those are shown in Accounting --> Supplier --> Payments as a payment made to a provider

### Expected behavior:
Showing this returns in the Supplier payments generate a bunch of trashy information in this view. It's something like showing client's Credit Notes inside the Supplier Bills view.

**Ticket #1920772**

**Comment by sswapnesh** [comment]
What was the answer from odoo help?

**Comment by gustavovalverde** [comment]
Support answer:

> As stated, what you are reporting corresponds to the normal behavior of Odoo. However, we do agree that it can be confusing to get the payment linked to the change in the Purchases > Payments menu. Therefore, I will provide a feedback to our Product owner team so our product can be improved in the future.

**Comment by Yenthe666** [comment]
If it is a feedback we can close it, Odoo S.A itselfs monitors those internally :) Thanks for the update.
