### ISSUE TITLE
[Wishlist] Odoo studio: ability to create Cohort views

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#30161]
Impacted versions: All

Steps to reproduce:
Go to a runbot, open Odoo studio and try to add a view. 

Current behavior: You can add all view types expect for the Cohort view.

Expected behavior: You can also create Cohort views with Odoo studio

**Comment by Yenthe666** [comment]
@mge-odoo & @aab-odoo is this anything that is planned for upcoming versions?

**Comment by mge-odoo** [comment]
@odoongr is the current Studio PO but I think nothing is currently planned.

**Comment by mge-odoo** [comment]
But he just told me that a feedback has been created on our side, thanks to your intervention.
Have a nice day.

**Comment by Yenthe666** [comment]
Good to hear, thanks a lot!
