### ISSUE TITLE
KeyError when changing MRP qty after amending bom

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#30173]
Impacted versions: 12.0

Steps to reproduce:
Create a BoM for a product
Create a Manufacturing order
Amend the BoM to add extra materials
On the order update the production qty.
Approve

Current behavior:
There is a KeyError because a new move is created after the done quantities have been determined.

Expected behavior:
I think in this case it is safe to assume that if no move previously existed, then the quantity done is 0.0 but not quite sure. Seems a regression from a recent change here. https://github.com/odoo/odoo/commit/8db7d70776a276d153d62708c9b703b0b756dae6

https://github.com/odoo/odoo/blob/6a0675d36dd888daa4183f3d609ce334ed3cb493/addons/mrp/wizard/change_production_qty.py#L76-L78

Maybe it just needs done_quantities.get(move, 0.0) on 77 and 78, or maybe just not trigger the conditional if the move isn't in done_quantities.

@len-odoo

Video/Screenshot link (optional):

**Comment by len-odoo** [comment]
On it, thanks for reporting.

**Comment by len-odoo** [comment]
Solved by df7953f3031a2d3b0f2abf30a41df4955fb6b553.
