### ISSUE TITLE
[11] 2 step receipts doesn't separate internal transfer by source document with procurement rules

### ISSUE THREAD

**Issue by infoitservit** [odoo/odoo#30172]
Impacted versions: 11

Steps to reproduce:
Activate multilocation and multistep inventory environment.
Set receipts for the main warehouse as "2 steps receipts".
Create procurement rules for products to buy from different suppliers.
The system creates different purchase proposals (correctly).
Confirm the orders.

Current behavior:
The system create different receipts (correctly) for each source document (purchase) but create only one internal transfer.
 
Expected behavior:
It should create different internal transfers and, if i cancel one of the confirmed orders, it should remove articles from internal transfer.

Video/Screenshot link (optional):

[video2.zip](https://github.com/odoo/odoo/files/2753256/video2.zip)

**Comment by infoitservit** [comment]
Isn't it a bug? Am i wrong in creating procurements?

**Comment by sle-odoo** [comment]
You're working with reordering rule and by default they don't create separate procurement groups, that's why the moves from input -> stock are merged in the same picking. You can achieve the behaviour you want by setting `group_id` to different values on your reordering rules.

Regards
