### ISSUE TITLE
[12.0] [wishlist] Search filter for "Supplier have Products"

### ISSUE THREAD

**Issue by Axel-G** [odoo/odoo#30170]
A search filter, if a supplier (contact) have relations to products (or not) would be a nice feature to see the unused supplier-contacts.

**Comment by sswapnesh** [comment]
IMO Adding `search` on `purchase_order_count` will do this with minimum customisation.

**Comment by pedrobaeza** [comment]
I'm so sure this is not something to be included in core, as this is a very marginal feature. There's no problem in having a lot of extra "unused" `res.partner` records in the database. If you want that feature, do it in a community module.

Closing by the reason above.
