### ISSUE TITLE
Email loop when partner uses autoreply from different email.

### ISSUE THREAD

**Issue by vvolas** [odoo/odoo#30190]
Impacted versions: 11, maybe others too.

Steps to reproduce: 
1. Create contact (customer, not internal user) lets say name.surname@domain.com. Partner must use different email to send emails for example odoo@domain.com. Lets say its holidays and when you send email to partner you get from odoo@domain.com:
 "name.surname is on holiday, we will answer soon!"

2. Create opportunity with partner added as follower.
3.  Send email "hello whoever you might be".

Current behavior: Emails starts looping, its probably misconfigured partner server to not include some error code? but result is our odoo instance starts killing itself too. Loop steps:
1. Our odoo sends first email "hello" to name.surname@domain.com
2. Partners auto answering machine sends email back to us from no-reply@domain.com "its holidays"
3. Since "no-reply@domain: is not "name.surname@domain.com" odoo sends message "its holidays" to internal odoo user and to follower name.surname@domain.com. 

And so 2 and 3 steps loops. 

Expected behavior: emails doenst loop.

Can I do something to prevent such harmful behavior. Or I m missing something.

**Comment by vvolas** [comment]
I found easier way to reproduce problem. Gmail ignores dots in emails. For example I have email andriusunishop@gmail.com

1. I added contact as andrius**.**unishop@gmail.com with dot which is valid.
2. I wrote to andrius.unishop@gmail.com via opportunity.
3. From gmail send reply. Address becomes andriusunishop@gmail.com without dot.
4 Odoo doenst detect its same contact. In opportunity mail is shown as "alien" so andriusunishop@gmail.com gets back  email he just send.

No loop in this case.

**Comment by pedrobaeza** [comment]
This is a misconfiguration due to catchall inbox getting the mail you have sent in Odoo. You have checked several things:

- Catchall configuration
- Server relay possibilities (for not replacing from address)
- Alias defined in Odoo

Closing as no real issue.

For more questions, please go to Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
