### ISSUE TITLE
[Web] Suggestion ListView checked

### ISSUE THREAD

**Issue by zuher83** [odoo/odoo#3019]
It would be good to add a new class "tr-checked" in the tree list view, when the check-box is checked.

```
<tr class="tr-checked"> 
     <th class="oe_list_record_selector"> 
            <input> 
```

This is just a suggestion, it may help to add color, or bold attribute on each lines "tr" when a selection of more than one line is checked

**Comment by nhomar** [comment]
I think with a combination of a proper usage of BS4 this is solved.
