### ISSUE TITLE
Wrong reserved and on hand decimal used

### ISSUE THREAD

**Issue by szegc** [odoo/odoo#30196]
Impacted versions:
V11 enterprise
Steps to reproduce:
We need use three product unit of measure, so we set in decimal accuracy for below:
Stock weight     2->3
product unit of measure     2->3

Current behavior:
But we still see two decimal of reserved and on hand  for product in inventory .
Expected behavior:
We need three decimal of product (reserved and on hand ) in inventory too.

Video/Screenshot link (optional):
[issue.docx](https://github.com/odoo/odoo/files/2755549/issue.docx)

**Comment by pedrobaeza** [comment]
Are you changing decimal precision or UoM precision rounding?

**Comment by sle-odoo** [comment]
Hi,
It seems to be working at my end.
Regards
