### ISSUE TITLE
expense to submit

### ISSUE THREAD

**Issue by 18428** [odoo/odoo#30206]
Impacted versions:
V11.0

The state of expense to submit is reported. Document content can no longer be modified in business. Is this a bug?

<img width="1364" alt="default" src="https://user-images.githubusercontent.com/34181313/51157800-748fa500-18bc-11e9-9736-deedaaac9a91.png">

**Comment by Yenthe666** [comment]
This is by design. Once it is submitted/reported only the manager can handle this.
