### ISSUE TITLE
Error maybe related to use of sudo somewhere in mrp procurement

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#30226]
Impacted versions: 12.0

Steps to reproduce:
Create and confirm a sales order as any user, admin if you like.
Make sure something needs manufacturing and qty is over 2 (I did it with an MTO manufacturing a drawer on runbot).
Notice that the responsible person for the production is OdooBot - why?

Current behavior:
What does this matter?
Now amend the sale order and reduce qty.
An exception task is raised for an invisible system user.

For added difficulty, do this in multicompany, record rule errors on res.users amending the order, so I guess thats why I think it is sudo in procurement in MRP, because the orders confirm fine initially.

Expected behavior:
At a minimum - the user that confirmed the order but obviously there maybe application access rights issues, or at least a user in the same company - maybe intercompany user of company (still system user but better). But what is really needed is a way of determining who that user should be. 

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
@sswapnesh Similar but different. Because their is no user_id field on pickings, so for the most part it all still works, you can increase and reduce quantities on the sale etc and exceptions occur assigned to that user. In this one you just can't. You are just stuck unless you amend record rule for users to include 'active = False'. But this one I can resolve with some quick custom dev in the short term, at least but I think if they want activities to work properly, then they are probably going to need a "Responsible" field as part of the mixin with an overridable default method.

For inventory I can imagine that we would want to pull a default from either the route or operation type.
MRP possibly the BoM, possibly the route.
Purchases from the template or supplier
Sales I think mostly is OK.
Invoices, well salespeople end up on them, but really that should be someone else in any company with an accounts department.

Wow, never realised how bad this was, guess activities was the true killer app.

**Comment by Yenthe666** [comment]
@jco-odoo & @sle-odoo for you guys

**Comment by sswapnesh** [comment]
@gdgellatly   Here is the _somewhere_

> create the MO as SUPERUSER because the current user may not have the rights to do it (mto product launched by a sale for example)

https://github.com/odoo/odoo/blob/12.0/addons/mrp/models/stock_rule.py#L41

**Comment by gdgellatly** [comment]
@sswapnesh Well kind of but not really. 

The issue is the default on the user_id which is set during the creation and then subsequently gets assigned as the default for activities. Thats why I say really the mixin for activities would be better to have a user_id field.

The creation isn't such a big deal, its the defaults  being set as sudo user that kill you, especially in multicompany because of record rules.

**Comment by sle-odoo** [comment]
@gdgellatly Did you set a responsible on your finished product? When you do so, the activities are assigned to him.

the responsible on the mo will be set as odoobot if the mo is created by the scheduler or a pull rule.

**Comment by gdgellatly** [comment]
@sle-odoo I didn't, but that isn't really feasible. In fact it is worse. You are basically saying this

The person responsible for product management is responsible for manufacturing.
The person responsible for manufacturing is responsible for manufacturing in all companies and warehouses.
The person responsible for a product must have access to all companies.

Honestly, I know there is no chance of this being fixed in stable, but take the particular case out of it and extrapolate to all the models using chatter, all the automatically created documents and activities and you see there is a real problem with

1. Security and record rules
2. Multicompany
3. Sensible assignation of automatically created activities.

Using this example - who is _responsible_ for managing manufacturing order change?
MRP Planner? Which one? Will be Warehouse/Product dependent.
First work order user (or if no workorders) the plant worker making it?

I actually really like the feature (really really like), but the whole controlling of assignation of activities is what turns this from great to demo to actually usable in production.

**Comment by sle-odoo** [comment]
thanks for the report

we slightly improved the situation in saas-12.2 in https://github.com/odoo/odoo/pull/31395
we have an internal task to make more manageable activities and group of user and its target is v13

let's close this one in the meantime because there's not so much we can do with the current implementation
