### ISSUE TITLE
Long list of followers unreachable

### ISSUE THREAD

**Issue by william-andre** [odoo/odoo#30237]
Impacted versions: at least 12.0

Steps to reproduce: Create a task with a lot of followers, the list has to be higher than the size of the browser's window. There must also be a (almost empty) chatter.
Try to scroll to the bottom of it.

Current behavior:
If the list of followers is longer than the chatter, you cannot get to the bottom of the followers.

Expected behavior:
See all the followers in all cases.

**Comment by sswapnesh** [comment]
will https://github.com/odoo/odoo/pull/30211 fix it? (I think yes)
