### ISSUE TITLE
Pricelist not calculated correctly when "Show public price & discount to customer" is selected

### ISSUE THREAD

**Issue by nppyro** [odoo/odoo#30243]
Impacted versions:
Odoo 12.0-20190114 (Community Edition), possibly others

Steps to reproduce:
Sales > Configuration > Settings > Pricing > Multiple Sales Prices per Product >  X  Multiple prices per product (e.g. customer segments, currencies)

Sales > Products > Pricelists > Create > Name:"Test Pricelist" >  Discount Policy > X "Show public price & discount to customer"

Sales > Products > Products > Create > Name:"Test Product" > Sales Price 180 > Sales Tab > Pricing > Add a line > Priceslist: Test Pricelist >  Price: 80 > Save

Sales > Orders > Quotations > Create > Customer: "Test Customer" > Pricelist: Test Pricelist > Add Product > "Test Product >

Current behavior:
Test Product is added. Shows unit price of 180, Discount of 55.56%. Subtotal of 79.99.

Final subtotal / unit price is being created based on the discount percentage that was calculated rather than using the actual price in the pricelist (80.00).

Expected behavior:
Test Product is added. Shows unit price of 180, Discount of 55.56%. Subtotal of 80. ( The actual price given in the pricelist)

Discount could be shown as a dollar amount rather than a percentage. This would help make the math actually work. Since showing a subtotal of 80 does not really compute given the discount percentage.

**Comment by pedrobaeza** [comment]
If you want exact amounts, you have to increase the decimal precision of the percentage discount, as this is a result of how pricelist engine works.

Closing as not possible to fix, but with the specified workaround.
