### ISSUE TITLE
Quantity on hand not updated

### ISSUE THREAD

**Issue by wguerram** [odoo/odoo#30247]
Impacted versions: 11

Steps to reproduce:

1. Create an inventory adjustment
2. Select one product and enter the real quantity.
3. After the adjustment is validated I can see the adjustment transaction in the Inventory Adjustment tab, looks correct to me.

My product location is type Internal Location, its parent is type View.

Current behavior:

The on hand quantity is not being updated in the product page. Does the location type has something to do here?

Expected behavior:

The on hand quantity should reflect the new value in the product page.

Video/Screenshot link (optional):

**Comment by wguerram** [comment]
Pedro I appreciate your interest for helping me, I did find the issue and fixed it. This is not a bug. The issue was caused because of the counter part location assigned to the items I was creating when importing a file to create products. I was uploading a location to this column property_stock_inventory/id overriding the location for the counter part. The value on that column must always be property_stock_inventory/id.

Thanks anyway.

**Comment by pedrobaeza** [comment]
Good to know. Thanks for reporting back.
