### ISSUE TITLE
ShowPaymentLineWidget Missing return

### ISSUE THREAD

**Issue by liweijie0812** [odoo/odoo#30267]
Impacted versions:11,12

Steps to reproduce:
path:  addons/account/static/src/js/account_payment_field.js

Missing return causes the widget to fail to expand

Can you add the following code to facilitate inheritance extension?
```
field_registry.add('payment', ShowPaymentLineWidget);

+return {
+   ShowPaymentLineWidget: ShowPaymentLineWidget
+ }
```

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please propose directly the PR, as this is an enhancement, not a bug. This might be accepted on stable branches, but the sure bet is target this to master.
