### ISSUE TITLE
Journal items view may show items that don't match account filter.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#3027]
##### Preamble

Summary:  The journal items view, while filtered by an account shows items from other accounts after clicking and bluring an item.

This was first reported in [launchpad](https://bugs.launchpad.net/openobject-addons/+bug/1280492).

The issue still is present in branch 7.0 commit id 03df412f.  I've also confirmed the issue is still present in branch 8.0 (commit ee69792).
##### Steps to reproduce
1. Create a DB (with demo data)
2. Install accounting.
3. Go to the Accounts and Choose an account for which you have some items (Debtors, for instance).
4. Click More and Journal Items.
5. Click over any of the show items and the click over another.

You'll see that several other items for other accounts appear. Actually all the items from the same entry.

Threre are couple of videos in the [original bug in launchpad](https://bugs.launchpad.net/openobject-addons/+bug/1280492), that show the bug in both versions.

**Comment by Yenthe666** [comment]
Hi @mvaled ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: accounting has been changed & rewritten quite a lot in the latest version so I don't think you'll be able to reproduce it anymore.

Regards,
Yenthe
