### ISSUE TITLE
Account Analytic Defaults app prevent set default analytic account for invoice line

### ISSUE THREAD

**Issue by MohsenWaleed** [odoo/odoo#30275]
**Account Analytic Defaults app prevent set default analytic account for invoice line**

Impacted versions:
 
 - 11.0 , 12.0
 
Steps to reproduce:
 
 1. Install Account Analytic Defaults app.
 2. modify the Form view of customer invoice by adding the below to the context attribute of invoice_line_ids
    'default_account_analytic_id': 'ANY ANALYTIC ACCOUNT'
 3. Try to add line to invoice, the default value will not be set.

I solved this issue by add condition to _onchange_product_id function in AccountInvoiceLine class as below:

Current Method:
```
    @api.onchange('product_id')
    def _onchange_product_id(self):
        res = super(AccountInvoiceLine, self)._onchange_product_id()
        rec = self.env['account.analytic.default'].account_get(self.product_id.id, self.invoice_id.commercial_partner_id.id, self.env.uid,
                                                               fields.Date.today(), company_id=self.company_id.id)
        self.account_analytic_id = rec.analytic_id.id
        return res
```

Updated Method:
```
    @api.onchange('product_id')
    def _onchange_product_id(self):
        res = super(AccountInvoiceLine, self)._onchange_product_id()
        rec = self.env['account.analytic.default'].account_get(self.product_id.id, self.invoice_id.commercial_partner_id.id, self.env.uid,
                                                               fields.Date.today(), company_id=self.company_id.id)
         if rec:
            self.account_analytic_id = rec.analytic_id.id
        return res
```
 
Current behavior:
 
 - The analytic account default value not set to a invoice line.
 
Expected behavior:
 
 - The analytic account default value should be set to a invoice line.

**Comment by sswapnesh** [comment]
Why are you using Account Analytic Defaults if this is not what you want?

**Comment by MohsenWaleed** [comment]
> Why are you using Account Analytic Defaults if this is not what you want?

I use it for specific conditions only and if there is no conditions applied it should take the default value. Even if I don't need it, you have to check any variable if it's has a value or not.

**Comment by pedrobaeza** [comment]
@MohsenWaleed you can propose a PR to Odoo with that change.

**Comment by MohsenWaleed** [comment]
> @MohsenWaleed you can propose a PR to Odoo with that change.

Thanks @pedrobaeza Is their any requirement to propose a PR?

**Comment by pedrobaeza** [comment]
To sign their CLA: https://github.com/odoo/odoo/wiki/Sign-CLA

**Comment by pedrobaeza** [comment]
I don't think so... You have to create the PR over odoo/odoo, not over your fork.

**Comment by MohsenWaleed** [comment]
Thanks @pedrobaeza 
I have created it over odoo/odoo
https://github.com/odoo/odoo/pull/30282

**Comment by Yenthe666** [comment]
The PR's have been merged & V11 is no longer supported so we should've closed this ages ago :)
