### ISSUE TITLE
Odoo standard allow to readonly for lines One2many list view, but for the new record, it will auto empty the value when edit again.

### ISSUE THREAD

**Issue by Reinhard-sheng** [odoo/odoo#30289]
Impacted versions:
odoo V10.0
Steps to reproduce:
Go in **Accounting**/**Sales**/**Customer Invoices**, open an invoice record. Change the form view to make the field quantity of  account.invoice.line readonly like `attrs="{'readonly': [('quantity', '==', 12)]}"`, the 12 is the quantity for this invoice line. Then create a new invoice line, modify the quantity, add necessary informations, click blank area out of the sub list view to save the invoice line. Then click the record again. 
Current behavior:
It will empty the new invoice line quantity.
Expected behavior:
Not empty the new invoice line quantity.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23512285/51299978-3a153c00-1a65-11e9-961c-21f2a57804b3.png)
![image](https://user-images.githubusercontent.com/23512285/51299985-3ed9f000-1a65-11e9-85cf-df939f9d89df.png)
![image](https://user-images.githubusercontent.com/23512285/51299865-ce32d380-1a64-11e9-90a5-88cee8875d81.png)
![image](https://user-images.githubusercontent.com/23512285/51300005-587b3780-1a65-11e9-812f-e9ef03c80f5d.png)

**Comment by nhomar** [comment]
I did not test myself but did you make F5 or refresh after change the view? if not the view in memory is not the correct one.

**Comment by elicoidal** [comment]
@Reinhard-sheng ?

**Comment by Reinhard-sheng** [comment]
Thanks for you feedback, I refreshed after changing the form view. The readonly for old line is True.

**Comment by Reinhard-sheng** [comment]
@nhomar 
Emm, issue not solved,
Refresh not solve this issue. Please check it.

**Comment by gdgellatly** [comment]
Everything is working as expected, just your view definition is wrong for the behaviour you want. If you want to write a readonly field in a view you must use force_save in the view definition.

**Comment by Reinhard-sheng** [comment]
`('quantity', '=', 12)` is to make the first record field quantity is readonly.
The key point is, for the second invoice line the field quantity is not readonly, but when modify it again, it will auto empty the value for the second invoice line. 
Could this solved by force_save ? I'm not find any case in odoo source code.

**Comment by Reinhard-sheng** [comment]
@elicoidal 
May be I should reproduce this for you first, seems I can't express this very well.

**Comment by pedrobaeza** [comment]
The problem is that a readonly field is not sent to the server, so that's why you are "losing" the value. You have to use another technique for what you want to achieve. On v11, it's possible to use `force_save` argument for avoiding this, but not for v10.

**Comment by gdgellatly** [comment]
Well I just tried on runbot, without force_save and a correctly formed domain and it worked just fine (well except if I enter qty 12 it changes to 1, but force_save fixes that.

http://429147-10-0-302d8a.runbot20.odoo.com/web?debug#id=72&view_type=form&model=account.invoice&action=376

**Comment by Reinhard-sheng** [comment]
I think I know what should I do.
Thank you for your help!
