### ISSUE TITLE
Pricelist Dropdown Selector does not display at website store *PARTIAL FIX PROVIDED

### ISSUE THREAD

**Issue by waterproau** [odoo/odoo#30284]
**Impacted versions:**
Tested in Odoo 12 Enterprise

**Steps to reproduce:** 
1. Enable 'Multiple Sales Prices per Product' from Sales->Configuration->Settings
2. Create one or more pricelists from Sales->Product->Pricelists
3. On one or more Pricelists enable checkbox 'Selectable' from Sales->Product->Pricelists
4. Check if Pricelist Dropdown Selector is displaying on Website Store...

**Current behavior:**
1. Pricelist Dropdown Selector does not display on Website Store. *FIXED SEE SOLUTION BELOW
2. After applying solution below to resolve point 1. If checkbox 'Selectable' from Sales->Product->Pricelists is unchecked for all Pricelists. The Pricelist Dropdown Selector still displays on the website.

**Expected behavior:**
1. When checkbox 'Selectable' is enabled for one of more Pricelists, the Pricelist Dropdown Selector should display on website, but does not. *FIXED SEE SOLUTION BELOW
2. After applying solution below to resolve point 1 - When checkbox 'Selectable' from Sales->Product->Pricelists is disabled for all Pricelists, the Pricelist Dropdown Selector should not display on the website, but still does.

**Solution for Point 1:**
There is a bug in the following view:

**View Name:** Pricelists Dropdown
**Key:** website_sale.pricelist_list
**View Type:** QWeb
**Line:** 4

<div t-attf-class="dropdown#{'' if website_sale_pricelists and len(website_sale_pricelists)&gt;1 else ' d-none'} #{_classes}">

Change dropdown# to #dropdown

**Comment by pedrobaeza** [comment]
@JKE-be can you please check?

**Comment by waterproau** [comment]
Is any more information required on this? Is it a confirmed bug or do I misunderstand how multiple pricelists are displayed on the website?

**Comment by JKE-be** [comment]
Fix in progress: https://github.com/odoo/odoo/pull/28301

Jeremy Kersten

**Comment by rdeodoo** [comment]
I can confirm this behavior is fixed with the mentionned PR, see:

![pl-before](https://user-images.githubusercontent.com/30048408/52849889-6d092900-3112-11e9-8874-0e1cb3c451d5.png)


![pl-after](https://user-images.githubusercontent.com/30048408/52849887-6d092900-3112-11e9-893f-84f8ff9dda7b.png)

**Comment by waterproau** [comment]
> I can confirm this behavior is fixed with the mentionned PR, see:
> 
> ![pl-before](https://user-images.githubusercontent.com/30048408/52849889-6d092900-3112-11e9-8874-0e1cb3c451d5.png)
> 
> ![pl-after](https://user-images.githubusercontent.com/30048408/52849887-6d092900-3112-11e9-893f-84f8ff9dda7b.png)

Great stuff! I'll test and provide any relevant feedback.

**Comment by JKE-be** [comment]
@waterproau any feedback ? 
we plan to merge it start of next week.

Thks

**Comment by rdeodoo** [comment]
Fixed at https://github.com/odoo/odoo/pull/28301
