### ISSUE TITLE
[10, 11, 12] Missing ondelete cascade: Stock Move and Stock Move Line (Many2one)

### ISSUE THREAD

**Issue by bobslee** [odoo/odoo#30283]
Impacted versions: 10, 11, 12

Is there any particular reason for this below?

Steps to reproduce:
- In model `stock.move` the `picking_id` (many2one) field has **no** `ondelete='cascade'`.
- In model `stock.move.line` the `move_id` (many2one) field has **no** `ondelete='cascade'`.

Current behavior: Both result in orphaned records with those foreign-keys set to NULL (by default).

Expected behavior: In case the parent record is deleted, those `stock.move(.line)` records, should be deleted as well.

**Comment by nhomar** [comment]
can you tell us the functional way we can generate such cascade elements?

since v11.0 and in V12 AFAIK thats a need for FIFO control (but not sure).

Regards.

**Comment by sswapnesh** [comment]
Hello @bobslee 

Are you sure about this behaviour ?

`ondelete='cascade'` is default if there is not `ondelete` option on that field definition.

See: https://github.com/odoo/odoo/blob/11.0/odoo/fields.py#L1943

> In model stock.move the picking_id (many2one) field has no ondelete='cascade'.
> In model stock.move.line the move_id (many2one) field has no ondelete='cascade'.

I have checked field definition for both fields and There is no `ondelete` option there so default should work there

Cc: @pedrobaeza  Can you confirm this ?

**Comment by pedrobaeza** [comment]
That default behavior is only for transient models, but it's not the case. The default one is `set null` for regular models.

**Comment by sswapnesh** [comment]
Ah correct, didn't saw that line.

**Comment by Yenthe666** [comment]
@bobslee could you give feedback on the questions please? Otherwise we'll have to close this issue.

**Comment by sswapnesh** [comment]
@bobslee 

> Expected behavior: In case the parent record is deleted, those stock.move(.line) records, should be deleted as well.

Moves are deleted in unlink of `stock.picking` at https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_picking.py#L527

Move lines are deleted at https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L499

**Comment by Yenthe666** [comment]
Good point @sswapnesh

**Comment by bobslee** [comment]
Indeed, the API already handles this. Fair enough :)
