### ISSUE TITLE
No more Option to Print Budgets or Budget Summary Report since Odoo 9. Bug or Feature Removed?

### ISSUE THREAD

**Issue by waterproau** [odoo/odoo#30285]
**Impacted versions:**
10, 11, 12

**Steps to reproduce:**

1. Go to Accounting->Adviser->Budgets
2. Create a Budget
3. Try and Print a Summary or Budgets PDF report

**Comments:**
Last known version to have this feature was Odoo 9, as per attached screenshot.

Was this intentionally removed from Odoo 10 onwards?

<img width="672" alt="print budget report" src="https://user-images.githubusercontent.com/20077718/51289081-ce27d900-1a4e-11e9-8076-72fa356a89f2.png">

**Comment by nhomar** [comment]
Actually yes, this was removed, I do not know why but I suppose looking for the move to enterprise.

**Comment by pedrobaeza** [comment]
This can't be considered a bug IMO, so should be closed.
