### ISSUE TITLE
[12.0] Vendor Bill sort products

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#30292]
Impacted versions:
12.0
Steps to reproduce:
1. Open Accounting dashboard
2. Click on "New Bill"
3. Choose PO number from "Auto-Complete" field
4. Add a new product
5. Choose another PO number from "Auto-Complete" field
6. Click on "Save"

Current behavior:
Odoo resort products to be auto-complete together then manual adding after them

Expected behavior:
Make lines with the same sort as before save record

Video/Screenshot link (optional):
https://drive.google.com/file/d/1s1Ii4eJxihKDcVuek_CVkLkW7aaH7KnC/view?usp=sharing

**Comment by pedrobaeza** [comment]
Each model has a defined order, that is applied on save, so this behavior is expected. The only way to assure the order is to drag and drop lines for resetting the sequence field.

**Comment by nhomar** [comment]
what @pedrobaeza says
