### ISSUE TITLE
Barcode unique to company

### ISSUE THREAD

**Issue by bl3d1D** [odoo/odoo#30316]
I want to add products with same barcode but different Companies.

Done everything like at issue : 
https://github.com/odoo/odoo/issues/20727

But is not working (maybe because i've got odoo 11). 
Tried to overwrite class product.product but no result.

My code : 
class CompanyProduct(models.Model):
    _inherit = 'product.product'
   product_company = fields.Many2one('res.company', 'Company', related='product_tmpl_id.company_id', store=True)

    _sql_constraints = [ ('barcode_uniq', 'unique(product_company, barcode)', ("Barcode should be unique by company!")), ]

    @api.model
    def _auto_init(self):
        res = super(ProductProduct, self)._auto_init()
        self._sql_constraints = [('barcode_uniq', 'unique(company_id, barcode)', _("Barcode should be unique by company!")),]
        return res

Anyone tried or know the solution ?

**Comment by pedrobaeza** [comment]
Please don't open new issues for a question, and more related to an already opened issue. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
