### ISSUE TITLE
[11] act_window object with groups property does not work

### ISSUE THREAD

**Issue by Nimja** [odoo/odoo#30317]
Steps to reproduce: 
Put in any view:
```
    <act_window id="random_action"
        name="Random Action"
        src_model="res.partner"
        res_model="mail.wizard.invite"
        view_mode="form"
        key2="client_action_multi"
        target="new"
        groups="base.group_system"/>
```
Is visible to ALL users, no matter the group.

```
    <act_window id="random_action"
        name="Random Action"
        src_model="res.partner"
        res_model="mail.wizard.invite"
        view_mode="form"
        groups="base.group_system"/>
```
Is visible to NO users (except userID 1), no matter the group.

Go to contacts, go to list view, select one (or more) contacts.
Click on actions menu.

Current behavior:
Either not or always visible (see 2 variations).

Expected behavior:
Only visible for users in group: "base.group_system"

**Comment by sswapnesh** [comment]
Hello @Nimja 
I tried to reproduce this on Latest V11 by adding group `"groups="base.group_system"` on All Invoices but seems working as expected to me based on User's/Actions's Group.
```

<act_window
            id="account.action_all_partner_invoices"
            name="All Invoices"
            res_model="account.invoice"
            domain="[('partner_id', 'child_of', active_id)]"
            groups="base.group_system"
            src_model="res.partner"/>
```

So here **All Invoices** action is visible to users with group **Administration / Settings** 
(or Maybe I am missing something)

**Comment by Nimja** [comment]
The point is that the action is ALSO visible with people who DO NOT have this group.

**Comment by sswapnesh** [comment]
> The point is that the action is ALSO visible with people who DO NOT have this group.

I tried to reproduce this again on Latest v11 Build (http://500251-11-0-0b2dbb.runbot15.odoo.com/web#id=9&view_type=form&model=res.partner&action=48) and it seems working as expected.

Eg, Added Multi Companies group on "All Invoices" action.

![Screenshot](https://user-images.githubusercontent.com/16624719/56163293-9861a480-5feb-11e9-958d-84d99b355b84.png)

User is not able to see that Action

![Screenshot](https://user-images.githubusercontent.com/16624719/56163327-ab747480-5feb-11e9-9c6d-66ae0c23505f.png)
Cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
@Nimja can you try with latest code version?

**Comment by sswapnesh** [comment]
Tried again and seems working well.
This can be closed now.

**Comment by pedrobaeza** [comment]
Closing. Please comment if still with the problem.
