### ISSUE TITLE
[8.0] start a survey create two user inputs (one is a doubloon)

### ISSUE THREAD

**Issue by MadeleineHero** [odoo/odoo#3032]
**Current behavior**:
Menu : Marketing / Surveys / Surveys
On "User Feedback Form" survey, click on "Test".
Click on "Go back to surveys"
Check Answers, we see 2 user input records (often with one second gap)
the second is a doubloon, it will stay always incomplete.

**Expected behavior**:
when we start a survey, it should create only one user input record (answer record)

**Comment by rim-odoo** [comment]
A fix will be merged soon with #4725
