### ISSUE TITLE
@kamleshahir,

### ISSUE THREAD

**Issue by kamleshahir** [odoo/odoo#30320]
@kamleshahir,

I've tested it and it works fine in both V10 and V11.
Steps:
1. Login with account X and add a message on a task
2. Login with account Y and apply the filter.

Result:
![image](https://user-images.githubusercontent.com/6352350/51323657-0f2ce700-1a69-11e9-816e-a3bdec1d244e.png)

You might want to update your Odoo.

_Originally posted by @Yenthe666 in https://github.com/odoo/odoo/issues/30250#issuecomment-455182504_

**Comment by pedrobaeza** [comment]
Closing as already handled in another issue

**Comment by Yenthe666** [comment]
Yeah & I reopened & confirmed the behaviour, there is indeed something wrong. 
Thanks for the quick actions @pedrobaeza
