### ISSUE TITLE
I need to modify network printer ticket in odoo 11

### ISSUE THREAD

**Issue by groupgloval** [odoo/odoo#30327]
I have a point of sale with pos_restaurant_network_printer and I need to modify the information printed on the ticket, for example I want the name of the product and the quantity to be centered, could someone tell me where I can find the file that contains that information? I imagine it is an .xml that is somewhere but I can not find it. Thank you.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
