### ISSUE TITLE
Invoice layout is not translated in PDF

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#3033]
Yes I have looked  at #1755  but this seems to be something else.

According to the qweb views for invoice the language of the invoice should be the partner language. And when I use invoice type HTML I get the correct text (Norwegian).

But then I changed to PDF and it is back to English.

This also hits when trying to send invoices by email, since that uses PDF by default, regardless of what is set in the report type.

**Comment by inspiraluna** [comment]
I had the same problem! And it was caused through deactivation of the "customer portal" under Settings-Configuration-General Settings. I activated it again now it looks much better again!
