### ISSUE TITLE
Very Minor UI issue in import - relations field greyed out if no column labels

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#30330]
Impacted versions: 12

Steps to reproduce:
Go to a model
Click import
Select a csv (any csv, it doesn't matter).
Untick Box thats says first row contains column labels.

Current behavior:
The UI greys out Show fields of relation fields, giving the impression it is non selectable.
The defer computation and history fields etc disappear entirely.

Expected behavior:
Given it is still selectable and valid (column names should make no difference), don't grey it out / hide it.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/51360842-3996a700-1b32-11e9-9ccf-db3504c3926a.png)

**Comment by Boudmir-Ibrahim** [comment]
@gdgellatly, 
I don't think this is an issue. 
Maybe for a better UI, it's recommended to replace the gray with another color so that the user don't confuse it with a non selectable elements. 
The class responsible for that behaviour is `text-muted`. which has the gray color in style
