### ISSUE TITLE
[11.0] Experiencing problem with limiting partner using security rule.

### ISSUE THREAD

**Issue by joezsweet** [odoo/odoo#30349]
Impacted versions: 11.0 update from repo today.

Steps to reproduce:
1. create a new group like: 
<img width="1010" alt="schermata 2019-01-18 alle 12 52 48" src="https://user-images.githubusercontent.com/11652845/51385564-f8959700-1b1f-11e9-927f-d9a621697fc7.png">

2. create a record rule, like:
<img width="1002" alt="schermata 2019-01-18 alle 12 49 57" src="https://user-images.githubusercontent.com/11652845/51385622-1b27b000-1b20-11e9-9df3-8a58e2cd4134.png">

3. add user to the group:
![image 2019-01-18 12 51 53](https://user-images.githubusercontent.com/11652845/51385526-d56ae780-1b1f-11e9-9850-c1c48dc74d3c.jpg)

Current behavior:
user can see all partners:
![image 2019-01-18 12 54 58](https://user-images.githubusercontent.com/11652845/51385681-43afaa00-1b20-11e9-9c52-4ffbd9f0a5ab.jpg)

Expected behavior:
User should see his partner only.

Am I doing something wrong? or is this an issue?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by joezsweet** [comment]
@pedrobaeza i'm experiencing the problem ..this is an issue ..can u reopen? i'm not sure why u close all my issues ..but i'll open another if you'll not reopen this one ...

**Comment by pedrobaeza** [comment]
@joezsweet I close them because they are not issues with Odoo, but not enough knowledge of the ORM. In this case, it's because security rules applied to groups are additive, and you have another security rule that is allowing you to all.

I'll continue doing the same while you don't post valid issues.

**Comment by joezsweet** [comment]
Yeah, though that one ..double checked all rules on Contact (res.partner) and that's what i found: 

<img width="1028" alt="schermata 2019-01-18 alle 13 06 56" src="https://user-images.githubusercontent.com/11652845/51386261-19f78280-1b22-11e9-95b6-8cdfdd866f2c.png">

So still think that seems to be an issue ..

**Comment by pedrobaeza** [comment]
No, it isn't. I have already explained what is happening. You need to disable both 2nd and 3rd rule for yours to work.

**Comment by joezsweet** [comment]
@pedrobaeza i'll double check and get back ..

**Comment by pedrobaeza** [comment]
@joezsweet no problem while you understand my motivation for keeping questions over issues isolated in their proper places. I can be wrong qualifying an issue of course, but the discussion after the closing can take place for leading me to reopen. I prefer to keep it closed meanwhile.
