### ISSUE TITLE
[11]E. Mexican localizaion, New validation in CFDI 3.3 return error 301 when creating invoice with tax. 

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#30383]
Impacted versions:

11 Enterprise. 
2018-01-10

Steps to reproduce:
Try to create an invoice with a taxed product. Trying to sing it via a PAC, returns a error from SAT:
 
Current behavior:

Odoo returns Error de validaciones adicionales [Error #CFDI33149] El valor del campo Importe no se encuentra entre el limite inferior y superior permitido. Folio: 1. Serie: NOCFD/xxxxx/. El importe "xx" del concepto "product" es menor al límite inferior x 

Expected behavior:

It sings the invoice correctly. 

Video/Screenshot link (optional):
![captura de pantalla de 2019-01-20 14-35-59](https://user-images.githubusercontent.com/7807363/51444767-8f4d8980-1cc1-11e9-8afa-b6482fd875ba.png)

It turns out there has been a change in the way the xml should   be created. http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/cfdv33.pdf

I have patched the problem, by changing one line in cfdi.xml. However I am not sure if I can post the patch here, due to odoo license, since this module is exclusive of odoo enterprise.

**Comment by nhomar** [comment]
Can you put a ticket in odoo.com/help please? and put the reference here.

1. I am signing with no problem and 301 problem is a validation in the sat, 
2. Can you try set download the [XSD as is explained in the documentation](https://www.odoo.com/documentation/user/12.0/accounting/localizations/mexico.html) **(look for XSD and you will find the steps)** to retrieve the error locally instead the generic error from the PAC?, that will help to solve the specific problem.
3. You pan put the patch in the ticket or here no problem, but thiso kind of problems are 100% covered by the licence and warranty,you just need to put a ticket and if your patch solve the problem (if any) we can merge it with no problem.

Regards.

**Comment by hydrosIII** [comment]
It seems working again no patch or anything, today afternoon-night, we had these problem for about 4 days, but now it is fine. I am wondering this is a problem  with the PAC (solucion factible), or maybe and update in SAT.  I hope it stays like that. It is weird. I have put a ticket.  For now I am closing this.  If the problem reapeas in the week , i will reopen it.
