### ISSUE TITLE
[12.0] Opening attachment menu cause search_read to read content of all attachments 

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#30394]
**Impacted versions:**

12.0

**Steps to reproduce:**

1. Install projects
2. Create and go to task
3. Add few big attachments to chatter
4. Open attachments menu
5. Look into browser console/debbuger

**Current behavior:**

Heavy search_read
![image](https://user-images.githubusercontent.com/5862658/51464092-16a00900-1d65-11e9-98dc-7a81940b2eaa.png)
This causing problems with proxy limits in tasks with many attachments  / big attachments

**Expected behavior:**

search_read reads only basic information about attachments

**Comment by pedrobaeza** [comment]
Please propose the way to fix this.

**Comment by fmdl** [comment]
It is strange because in the list of fields there are no the `datas` field
https://github.com/odoo/odoo/blob/12.0/addons/document/static/src/js/document.js#L131

Maybe it come from the `search_read` of the chatter.

**Comment by mart-e** [comment]
Hi,

I agree this is not normal, until we are actually displaying/downloading the attachment, we shouldn't download it.
I made a try to fix it at #30415 

cc @ThanhDodeurOdoo

**Comment by ThanhDodeurOdoo** [comment]
hey,

It was changed in 12.1 with 73d9b9588f24788766c66aacd69ed436bb0223f4 , there is a task to backport this commit to 12.0 (mainly to have the added features that replace the sidebar's attachment menu).
