### ISSUE TITLE
Bug 1089229: Wrong treatment of UoS among objects

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#304]
**Impacted versions:**
6.1 and above

**Steps to reproduce:**
See https://bugs.launchpad.net/openobject-addons/+bug/1089229

**Current behavior:**
- If you change units of sale (uos) quantity in sales order, uom quantity is not recalculated, thus breaking the relation between uom and uos (uos_coeff).
- If you change the uom or uos within their category in sales order or invoice, nothing happens --> Thus breaking again the relation between uom and uos (there is no recalculation, and it's not the same selling grams and kilograms).
- Sale order lines shows only uom quantities and uom prices.

**Expected behavior:**
- If you change units of sale (uos) quantity in sales order, uom quantity should be recalculated accordingly (as happens viceversa).
- If you change uom or uos within their category in sales order or invoice, the other quantity is recalculated. Also, price should be recalculated (because of the change of unit, price(kg)=1000*price(g); and also because if quantity changes, another pricelist may apply).
- If using a secondary uos, sale order lines should show both uom and uos, as well as price_unit(uom) and price_unit(uos). --> This is a much desired feature for salespeople, because many times they know the Sale unit and its price (not the uom and price(uom), which may be more related to warehouse in such cases).
-Both UoM and UoS related info (quantities, prices) should be both available in product, sale and invoice objects.

**Further info**
This bug (and its code implications) https://bugs.launchpad.net/openobject-addons/+bug/1089229 is still there in master as of today (checked code a few minutes ago, and in runbot there is something weird with the reports so I cannot obtain the sale order report, but the invoice report shows sale unit price in tax column).

Maybe this is just the right time (just before v8) to harmonize uom/uos and price_unit_uom/price_unit_uos among different objcts (product.product, sale.order, account.invoice) and be able to keep all info lossless.
Also to fix the uom category conversions (look at the 'FIXME' in code, for example: https://github.com/odoo/odoo/blob/master/addons/sale/sale.py#L1031 )

**Comment by alejandrosantana** [comment]
@odony Anything about this for v9?

**Comment by niecw** [comment]
Linking my question in Odoo Help that explains where the incorrect codes are.  There are more than the UoS - UoM relationship in SO that is broken wrt the code.  It also affect PO (surprise surprise!) and more:   https://www.odoo.com/forum/help-1/question/what-is-the-proper-way-of-using-uom-and-uos-in-stock-move-85772

**Comment by eLBati** [comment]
Hello, see if https://github.com/odoo/odoo/pull/7311 solves

**Comment by niecw** [comment]
Hi Lorenzo,

Thank you for your update.  However it does not solve the problem I'm 
facing.  The problem I'm facing is that I'm not using UoS at all but the 
UoS got updated and used anyway, incorrectly.  E.g. if you change the 
UoM (not the quantity) of the sold product from 1 pce to 1 dozen, the 
UoS stays as 1 * UoS coeff.  Whereas now, the product is 12 folds.
Now, the UoS is what is used when creating invoice from delivery, giving 
no chance for user that does not intend to use UoS in the first place to 
use UoM to create related invoice.  Whereas, the quantity is now 
"linked" to UoM (which may have been different from the Product's 
Default UoM.

So, in a way UoS handling is pretty much broken in the first place and 
affecting not only Sales (which is where UoS is supposed to be used) but 
also Purchase.

Thank you,

**Comment by Yenthe666** [comment]
Dear @alejandrosantana,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
