### ISSUE TITLE
Field with compute and company_dependent doesn't init properly

### ISSUE THREAD

**Issue by kosz85** [odoo/odoo#30410]
Impacted versions: 11, probably all

Steps to reproduce:
Create filed like:
```
shop_discount = fields.Float(string="Shop Discount", company_dependent=True, default=0)
shop_price = fields.Float(string="Shop Price", company_dependent=True, compute='_compute_shop_price')
```
`_compute_shop_price` has to set `shop_price` based on some value and `shop_discount`

Current behavior:
`shop_price` inits as `0`, then in UI after any action on related fields (reaction on @api.onchange) it sets to correct value. Without `company_dependent` on `shop_price` it works ok.

Expected behavior:
It should init initial value based on computation and company dependent values.

It's not critical, but probably a bug related to company dependent values.

**Comment by pedrobaeza** [comment]
A compute field can't be by definition be company dependent. If you want to do that, you should use another data structure like computed man2many.

Closing as this is not a valid use of the ORM.
