### ISSUE TITLE
price not update at pos

### ISSUE THREAD

**Issue by xgj1988** [odoo/odoo#30418]
Impacted versions:
12.0
Steps to reproduce:
1:create product and set price value is 5$ .
2:open post and sell the product .we can see the price is 5$.
3:modify the price is 10$, 
4:if you don't refresh the browser ,the price stall is 5$ ,although you click the check button . 

Current behavior:
When you modify the price of product ,the pos can't update (except refresh browser).

Expected behavior:
When i submit the form of pos ,i hope odoo should check the price of student  automatically.

Video/Screenshot link (optional):

No

**Comment by pedrobaeza** [comment]
This is the expected behavior, as PoS works in offline mode, so no sync is done unless you refresh.

Closing as no real issue.

**Comment by xgj1988** [comment]
@pedrobaeza Is there  has a way to configure this .  Or how to modify the problem that i want pos check the price when i create a new bill.

**Comment by pedrobaeza** [comment]
For that, you have to develop that feature and renounce to have offline possibilities, as it will require a permanent connection to check that.

**Comment by xgj1988** [comment]
Maybe   we should check the price if the network signal is connected . if the network is broken . step two  we don't check the price . i think this  is good solution.

**Comment by pedrobaeza** [comment]
Well, as said, that has to be a custom development.

**Comment by xgj1988** [comment]
ok  thx.

**Comment by xgj1988** [comment]
i think odoo could  consider build in this feature in next version. wish odoo grow better and better

**Comment by Yenthe666** [comment]
@xgj1988 the whole module (Point of Sale) is specifically designed with Backbone.js to prevent needing internet or connection, at any point.
There are plenty of third party apps that allow syncing products, prices or customers at some point, just look at the appstore.

**Comment by xgj1988** [comment]
@Yenthe666  yes, I found the app  for this problem .thx

**Comment by Yenthe666** [comment]
You're welcome, best of luck.

**Comment by pedrobaeza** [comment]
I think this is twisting so much the features, but I wish you don't have troubles with these kind of modules...

**Comment by Yenthe666** [comment]
@pedrobaeza depends, in some cases you might need this if you work with a big bulk of products that are both being handled and sold from sale orders/invoices and the POS. We've had a case before too.

**Comment by pedrobaeza** [comment]
The chances of inconsistencies is very big. And more if you handle pricelists, fiscal positions and so on. It's very complex to be handled and I doubt these modules cover all cases. For simple scenarios, they can work, but you know the Murphy's law...

**Comment by EwetoyeIbrahim** [comment]
Its disheartening that this is still overlooked.
This must be an alternative and the assumption of no internet connectivity shouldn't be Odoo's headache, as long as it's clearly written on the option.
Some businesses doesn't see internet as a constraint so why should odoo be the constraint here?
