### ISSUE TITLE
Inheriting portal.frontend_layout doesn't work

### ISSUE THREAD

**Issue by yezyilomo** [odoo/odoo#30431]
Impacted versions: 12

Steps to reproduce: Inherit  portal.frontend_layout and put some contents in it

Current behavior: Contents plugged doesn't show up

Expected behavior: Contents plugged to show up

Video/Screenshot link (optional): 
![custom_search](https://user-images.githubusercontent.com/20328561/51535731-5c8ac900-1e5a-11e9-9425-06ce7b7ec43f.png)

**Comment by pedrobaeza** [comment]
This is because in v12, multi-website makes a copy of each view, and you have to recreate the website, but it's not an Odoo issue itself.

Look for more information in #28695
