### ISSUE TITLE
[V12] consumed material and finished product to be the same

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#30459]
Impacted versions: all

Current behavior: odoo does not allow me to create a BOM for drying. It is basically "taking water" from the same batch...

Expected behavior: consumed material and finished product should be the same on BOM and MO

**Comment by pedrobaeza** [comment]
No, you can't do that. You have to create 2 different products, as they are not the same although you think they are. If you perform a transformation of "Product A", what you get is "Product A (transformed)", and as such, you have to have different stock levels for both products, different name, etc.

Closing as no real issue, as the constraint is put on purpose.

**Comment by nagybal** [comment]
I have my final product, lets call it Product A on storage. Before delivery I need to put it back to the dryer. I am not creating a new product. What I need to some kind of inventory action in form of an MO.

You can configure the dryer for temperature and time You can not check the humidity during the production.

Currently I am forced to open a new MO in order to transform the Product B back to Product A (the one I am selling), without any actual data change.

**Comment by pedrobaeza** [comment]
The "Product A" without being dried can't be the same as the one dried, as their properties convert the product to another one. You can't sell "Product A". You have to sell "Product A (dried)". They are semantically and technically implemented as different products.

**Comment by nagybal** [comment]
Product A was dried before. As again it has reached its final form in production. Its wight changes however because it acts like a sponge. Attracts moisture in the air.
