### ISSUE TITLE
[V10] Filter on 'Components' for Products and Product Variants shows built items instead of components

### ISSUE THREAD

**Issue by KangOdoo** [odoo/odoo#30456]
Impacted versions: 10

Steps to reproduce: Used filter on 'Components' for Products and Product Variants in Purchases, Sales, Inventory and Manufacturing apps with same result

Current behavior: Only the built items (from Bill of Materials) are displayed, components vanish

Expected behavior: Components, or items used in the build only, should be shown

Video/Screenshot link (optional):
![components](https://user-images.githubusercontent.com/36682465/51570488-3cf3af00-1ef3-11e9-977c-f04502907776.jpg)

![component definition](https://user-images.githubusercontent.com/36682465/51570510-4715ad80-1ef3-11e9-962a-6badb4d08be3.jpg)

**Comment by Yenthe666** [comment]
Dear @KangOdoo ,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
