### ISSUE TITLE
[11.0] odoo mixing up users

### ISSUE THREAD

**Issue by andriisem** [odoo/odoo#30462]
Impacted versions: 11.0

Steps to reproduce:
I think this is a single case

Current behavior:
The bug is as follows: at a certain point in time, user A (who logged in to system with his login password) becomes user B (The same time user B is kicked out form the system).

When user A became user B, he can perform any actions and write-read any messages form the name of user A. In fact, for the system side he became B and got all his rights. Such a bug appears more often when a large number of people (more than 20) begin to use the system and actively using the system. The bug arises in different modules and even with the first login to the system.

Expected behavior:
not sign in as another user

**Comment by pedrobaeza** [comment]
This seems something bad in your deployment, probably with the store of credentials, but I can assure you that this is not something that happens on regular Odoo. Please check your deployment method and check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
