### ISSUE TITLE
[8.0] header and footer loss in pdf report but ok in html

### ISSUE THREAD

**Issue by sparedimare** [odoo/odoo#3047]
Hello,

we have a problem with pdf reports. When we want print a invoice or other documents in pdf, the document loses header and footer. Html reports are correct.
Is this a problem with wkhtmltopdf?

The system is w2008 and wkhtmltopdf is the last version stable 0.12.1

Thanks

**Comment by jbvidex** [comment]
I'm having the same problem, except that only the header is missing.  The footer seems to be okay.  Looking at the server output, I do see this:

`2015-01-20 17:16:21,146 22730 INFO JB-1-19 werkzeug: 127.0.0.1 - - [20/Jan/2015 17:16:21] "GET /web/binary/image?model=res.partner&field=image_small&id=3&resize= HTTP/1.1" 304 -`

Perhaps it's only a problem in the header, and after Odoo is unable to retrieve the logo, the whole header section dies?
