### ISSUE TITLE
wrong exchange rate in HR.expenses when posting journal entry

### ISSUE THREAD

**Issue by dashtech** [odoo/odoo#30471]
Impacted versions: odoo 12 EE

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional): 
https://drive.google.com/file/d/1PrAlvkF1erC_DkzYL2ST-fIKAXSna-ZT/view?usp=sharing

**Comment by pedrobaeza** [comment]
It's better if you put the text and the images directly in the issue report instead of a document (GitHub allows that).

**Comment by dashtech** [comment]
Hi pedrobaeza,
sorry for that i will do it next time
