### ISSUE TITLE
"Private Address" value from res.partner/type is not in translated

### ISSUE THREAD

**Issue by hmartinet** [odoo/odoo#30483]
Impacted versions: Odoo 10.0

Steps to reproduce: Open the create contact button on a partner

Current behavior: "Private Address"

Expected behavior: "Private Address" in user language

Video/Screenshot link (optional):

I think this needs an export of base.pot because the value is not in the file (but if I export the module myself I can find it).

Workaround: Add these lines in i18n_extra/fr_CH.po in a custom addon (adapt file name to your locale):

    #. module: base
    #: selection:res.partner,type:0
    msgid "Private Address"
    msgstr "Adresse personnelle"

**Comment by mart-e** [comment]
Hello,

It will be fixed at #30488
Thanks for the report
