### ISSUE TITLE
[12.0CE] Form view stuck after warning

### ISSUE THREAD

**Issue by anhvu-sg** [odoo/odoo#30509]
Impacted versions: 12CE

Steps to reproduce:

1. Try on http://runbot.odoo.com/runbot

1. Create new attendance (menu: Attendances > Manage Attendances > Attendances)

1. Add new record, try to input  **Check In** > **Check Out**

1. The warning is shown > close this warning > discard

Current behavior:
After finishing this step, I cannot do everything, stuck on the screen (I have tried on V10 and v11 but it work well)

Expected behavior:
Form should reload after clicking on discard

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7898318/51674701-fe014e80-2003-11e9-8a30-6c96e79c07af.png)

![image](https://user-images.githubusercontent.com/7898318/51674828-64866c80-2004-11e9-93b8-1cd683d5506c.png)

![image](https://user-images.githubusercontent.com/7898318/51675006-fee6b000-2004-11e9-94fa-3c1ffd2410de.png)

**Comment by Boudmir-Ibrahim** [comment]
I confirm that the issue is reproducible on V12 CE
