### ISSUE TITLE
[BUG][11.0] stock : on internal picking operation initial demand is not editable

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30515]
**Impacted versions:**
11.0

**Steps to reproduce:**
Go to runbot enterprise V11
- Inventorie
- Internal transfert
- Create a new
- add a new line
--> inital demand is not editable

**Current behavior:**
It is not possible to reserve product, you can only set the done quantity. You can only set the `done_quantity`

**Expected behavior:**
For transfert (internal, income, outcome) which don't come from sale or purchase, on draft mode, I will be great to set the initial demand to reserve product.

In V10 it works better.

It is a normal beahviour ?

@sla-subteno-it 

**Note:**
the logic between `stock.move` and `stock.move.line` for this field `is_initial_demand_editable` is not super logic:
the field `is_initial_demand_editable` is used to readonly for `product_uom_qty` on `stock.move`, and it is use for `qty_done` on `stock.move.line`.

**Comment by pedrobaeza** [comment]
I think you have to click on the 3 dots in the picking type and click on "Immediate transfer".

**Comment by fmdl** [comment]
@pedrobaeza you are right, but you need to click on `planned transfert` :-)

it is not easy to use, because if you come back in the list of transfert the context have not `planned_picking` and you cannot update the value.

@jco-odoo it is possible to save that is a planned transfert in the picking ?

**Comment by sle-odoo** [comment]
hi
everything is fixed in v12: default transfers are planned one, the immediate is no longer a context key but a field

regards

**Comment by fmdl** [comment]
ok, good
thanks

**Comment by ValentinoDefelice** [comment]
Hi @Yenthe666 !
¿Are you planning apply this fix about planned transfers to V11?

**Comment by Yenthe666** [comment]
@ValentinoDefelice it has been resolved in V12 so a backport of this is very unlikely, unless @sle-odoo would approve it.
