### ISSUE TITLE
pivot_column_groupby not working 

### ISSUE THREAD

**Issue by BT-dherreros** [odoo/odoo#30526]
Impacted versions:
11.0

Steps to reproduce:
Go to a pivot view.
Expand a column you want to save.
Add the search as favorite user filter.
Select the filter.

Current behavior:
Nothing happens yet the filter appears on ir_filter with the expanded fields selected under  'pivot_column_groupby'
Expected behavior:
Get back the view saved as favorite, with the selected columns expanded

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/37086217/51690176-76621280-1ff8-11e9-86b8-eca45e1b7a29.png)

![image](https://user-images.githubusercontent.com/37086217/51690216-8974e280-1ff8-11e9-8182-5ba348e8d878.png)

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/26194

**Comment by pedrobaeza** [comment]
It seems is not the same, although they can be related to the same root cause, because this is saving a favorite.

**Comment by sswapnesh** [comment]
I am sure I tried with adding favorite filter and that didn't worked (So I don't added that as Favorite filter was not necessary to reproduce issue)
You can keep this open if you wish. 🙂
