### ISSUE TITLE
Odoo 12 Enterprise VoIP Module doesn't perform outgoing call

### ISSUE THREAD

**Issue by gsusrafael** [odoo/odoo#30531]
Impacted versions: 12

Steps to reproduce: configure the VoIP module, open the dial pad and dial any number (including internal extensions)

Current behavior: sip.invitecontext.sessionDescriptionHandler | un1l2f7gvh3boonjkri2vultko1q74 | unable to acquire stream

Expected behavior: to perform and initiate the call

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/916851/51704429-6eea3b80-1fef-11e9-9c0f-05b6d72ad602.png)

**Comment by pedrobaeza** [comment]
As this is something enterprise, you should put an OPW ticket in odoo.com/help instead. I'm going to close this as this is also very old.
