### ISSUE TITLE
[BUG][11.0] base: pivot view, the column is not save

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30532]
**Impacted versions:**
11.0

**Steps to reproduce:**
Go to : Accounting/Journal Items
Select pivot view
On row : group by account
On column : group by date / week
Click on cell to see some record
Come back on pivot
On column : group by partner
Click on cell to see some record
Come back on pivot

--> issue the column group by is back to date / week

**Current behavior:**

**Expected behavior:**
keep the same group by

**Video/Screenshot link (optional):**
https://www.youtube.com/watch?v=KgeZSIN_tRA

**Comment by fmdl** [comment]
OPW 1937831

**Comment by nle-odoo** [comment]
Hi,


It seems to be solved with https://github.com/odoo/odoo/pull/31407

Regards.
