### ISSUE TITLE
[12] Fails to install on Fedora 29 using rpm package due to Python

### ISSUE THREAD

**Issue by Dylan-M** [odoo/odoo#30579]
Impacted versions:
I've only tried 12, but likely others

Steps to reproduce:
sudo dnf install https://download.odoocdn.com/12.0/nightly/rpm/odoo_12.0.latest.noarch.rpm

Current behavior:
$ sudo dnf install -y ~/Downloads/odoo_12.0.latest.noarch.rpm 
Last metadata expiration check: 0:19:28 ago on Sat 26 Jan 2019 01:20:10 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.6 needed by odoo-12.0.post20190126-1.noarch

Expected behavior:
Odoo to install and run correctly because the version is greater than that needed, but it's looking for a specific version only

Other Info:
Python 3.7 is installed
$ rpm -q --provides python3
python(abi) = 3.7
python3 = 3.7.2-4.fc29
python3(x86-64) = 3.7.2-4.fc29
python37 = 3.7.2-4.fc29
system-python = 3.7.2-4.fc29
system-python(abi) = 3.7
system-python(x86-64) = 3.7.2-4.fc29

**Comment by pedrobaeza** [comment]
@d-fence are you the packager?

**Comment by d-fence** [comment]
Landed here 7eec6b3643999cb26216e56c001eb8aae65031ea in 11.0.
Will be forward-ported in next forward port.

**Comment by Dylan-M** [comment]
Being unfamiliar with your release process, do you have an ETA on when that might happen?

**Comment by d-fence** [comment]
Approximately once a week

**Comment by Dylan-M** [comment]
Perfect, thanks for the quick work. That's a great timeline for me.
