### ISSUE TITLE
[BUG][11.0] base: handle widget is still active on a readonly One2many field

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30573]
Impacted versions:
11.0 and maybe other

Steps to reproduce:
Go to purchase
Create a new purchase order
Add two order line
Confirm purchase
-> after confirmation the field order_line is readonly
Edit order
--> issue you can use the handle to change order of order lines.

Current behavior:
handle is show

Expected behavior:
handle will be not show

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=4AE1pOyVSts

**Comment by pedrobaeza** [comment]
@fmdl the field is not read only by default confirming purchase orders, as this is a new feature to make it equivalent with sales orders, and the video you have made confirm this as you can see the "Add line" action. Maybe the sequence field can be made readonly when the purchase order is confirmed, but that's another discussion to do not related with this issue.

Closing as no valid issue unless further information is provided.
