### ISSUE TITLE
[BUG][11.0] base: handle widget is still active on a readonly One2many field

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30580]
Impacted versions:
11.0 and maybe other

Steps to reproduce:
Go to purchase
Create a new purchase order
Add two order line
Confirm purchase
**Lock purchase** (order state pass to `done`)
-> after locking the field `order_line` is readonly
Edit order
--> issue : you can use the handle to change order of order lines.

Current behavior:
handle is show

Expected behavior:
handle will be not show

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/16716992/51802875-925ef180-224e-11e9-8a0d-214088d85259.png)

@pedrobaeza

**Comment by fmdl** [comment]
OPW 1937833

**Comment by fmdl** [comment]
ping @ged-odoo

**Comment by Yenthe666** [comment]
@fmdl I'm curious. Why a ping from ged-odoo while you have an official ticket? What is the response on the OPW?

**Comment by mge-odoo** [comment]
Hi @fmdl 

Thanks for reporting the issue ; it has been fixed in https://github.com/odoo/odoo/pull/31743
I will also close the associated ticket.

@Yenthe666 the ticket was considered as "non-blocking bug" so it took more time than usual.

Martin
