### ISSUE TITLE
Master / 8.0 - website menu <li> gets no class=active

### ISSUE THREAD

**Issue by copmn** [odoo/odoo#3059]
impacted versions:
- 8.0
- master

steps to reproduce:
- installed version from github (today=10/13/2014)
- install fresh clean database
- install website-builder
- goto contac us page (class=active not appearing) / home page (class=active is appearing)
- create new page with menu entry and go there (class=active not appearing)

notes:
- with a earlier 8.0alpha it works fine
- probably because it uses the older links like (..page/website.contactus | ..page/website.test-entry) maybe it has something to do with that, but until now I can't figure it out.

update
======
What I found out is: if you rebuild the menu links over ```Content / Edit Menu``` it works.

![menu-1](https://cloud.githubusercontent.com/assets/7815772/4625484/e8d81c2c-5376-11e4-9611-e81202a50370.jpg)
![menu-2](https://cloud.githubusercontent.com/assets/7815772/4625485/ef189e90-5376-11e4-901b-36f25dcac37c.jpg)

update2
=======
During editing (cut off the ```website.``` for the menu entries) there came up a nother little problem:

![menu-3](https://cloud.githubusercontent.com/assets/7815772/4626651/b27fce06-5383-11e4-9763-a01fcb0a874b.jpg)

Similar menu entries are highlighted together. So the second change ist to avoid this problem.

**Comment by Fl0rianFischer** [comment]
@copmn Thanks a lot for this fix. I installed the changes using a patch.

I am now getting the active class on the list items for all website menus but for Home and Blog. These two pages remain the same when selected.

Do you have any ideas how this could be fixed?

Thanks!

**Comment by copmn** [comment]
@Fl0rianFischer nomally it could be fixed with my pull request #3059 but it is open since 4 month :-(.

**Comment by Nowheresly** [comment]
Any chances to see this PR merged ?

**Comment by copmn** [comment]
@Nowheresly I don't think they will merge this. To get rid of this you can easily remove ```website.``` from all the links which are comming with the installation of the module.

**Comment by Nowheresly** [comment]
After removing `website.`, it works as expected. Thanks @copmn !
