### ISSUE TITLE
[12] Please fix old dependency on postgresql-client

### ISSUE THREAD

**Issue by lastalfriday** [odoo/odoo#30599]
Impacted versions:
12/12e

More info:

Odoo 12 uses postgresql v10
Both the community and enterprise edition have an old dependency on the *postgresql-client* which contains *pg_dump* used to backup databases

```
 Package: odoo
 Version: 12.0+e.20190128
 Architecture: all
 Maintainer: Odoo S.A. <info@odoo.com>
 Installed-Size: 613099
 Depends: init-system-helpers (>= 1.18~), python3-babel, python3-dateutil, python3-decorator, python3-docutils, python3-feedparser, python3-gevent, python3-html2text, python3-jinja2, python3-lxml, python3-mako, python3-mock, python3-ofxparse, python3-passlib, python3-pil, python3-psutil, python3-psycopg2, python3-pydot, python3-pyparsing, python3-pypdf2, python3-reportlab, python3-requests, python3-serial, python3-tz, python3-usb, python3-vatnumber, python3-werkzeug, python3-xlsxwriter, python3:any (>= 3.3.2-2~), adduser, lsb-base, postgresql-client, python3-chardet, python3-libsass, python3-suds
```

The correct dependency should be *postgresql-client-10*
https://www.postgresql.org/download/linux/debian/

This causes the backup routine to fail

Thanks :)

**Comment by pedrobaeza** [comment]
Are you talking about the .deb file? AFAIK, the packaging is done with latest stable Debian version available when the version was released. The problem can be that you are using a PG server version not synchronized with that (v10 vs 9.6).

**Comment by lastalfriday** [comment]
Yes, the info I posted was from the downloaded .deb file (both community and enterprise) that I downloaded today.

I'm using postgresql 10.6.
As I understood Odoo v12 uses this verison?
Alt least that's what this say: https://docs.docker.com/samples/library/odoo/ (scroll down to the docker compose file example)

**Comment by pedrobaeza** [comment]
Why do you mix Docker with .deb? Can you confirm that the Debian stable version available at release date shipped with PG 10.6 as the server?

**Comment by lastalfriday** [comment]
Thanks guys. I agree now this is not a direct Odoo .deb dependency issue. Also like @pedrobaeza says something should be dont with the odoo/docker info so this is clear.

A possible solution is to update the odoo v12 dockerfile to install the correct *postgresql-client* for v10 of postgresql by installing updated apt sources described here
https://www.postgresql.org/download/linux/debian/

Anyway, you guys seems to be on top of it. I'm just happy I found out this, cause it was causing major local problems here.

**Comment by d-fence** [comment]
@lastalfriday Thanks for reporting this problem that we were not aware of.
I'll try to fix the Docker image as you suggest in the hope that it will not breaks the other way.
I close this one as it's more a packaging problem.

**Comment by pedrobaeza** [comment]
@d-fence for your reference, we have this in our specialized Docker image (Doodba) for using latest PG client tools without interfering in PG server: https://github.com/Tecnativa/doodba/blob/fe41a23e0bc48725609aea8a67a00b94a6d35ca8/11.0.Dockerfile#L58, thanks to the backwards compatibility in them.

**Comment by d-fence** [comment]
@pedrobaeza thanks

**Comment by lastalfriday** [comment]
@d-fence Regarding the link @pedrobaeza posted, be aware of this:

```
root@178df594c640:/# apt search postgresql-client
Sorting... Done
Full Text Search... Done
postgresql-client/stretch-pgdg 11+197.pgdg90+1 all [upgradable from: 9.6+181+deb9u2]
  front-end programs for PostgreSQL (supported version)

postgresql-client-10/stretch-pgdg,now 10.6-1.pgdg90+1 amd64 [installed]
  front-end programs for PostgreSQL 10
...
```
In other words if you update the apt sources like described and just install **postgresql-client** and not **postgresql-client-10** you might get the client used to connect to posgresql v11 which could lead to problems

**Comment by pedrobaeza** [comment]
By my part, no known problems from now using postgresql-client 11 with PG server 9 to 11.

**Comment by lastalfriday** [comment]
Well ok, I guess you're fine then :)

**Comment by d-fence** [comment]
I hope that they are backward compatible, otherwise it would be a no go.
That's why I wrote "in the hope that it will not breaks the other way".

**Comment by lastalfriday** [comment]
@d-fence I tested on our database now with backup and restore and had no problems. If not a confirmation, at least a strong indicator that this will work

**Comment by d-fence** [comment]
@lastalfriday I'm currently updating the Dockerfile's and I'll test them against 9.4 and 11.0 databases.
Thanks for the information, it helps.

**Comment by d-fence** [comment]
Latest Docker images landed here https://github.com/docker-library/official-images/commit/17410b20ede0234ae328af22da38abab8abf902e
