### ISSUE TITLE
[12.0] Bug with pricelist

### ISSUE THREAD

**Issue by BT-aestebanez** [odoo/odoo#30601]
Impacted versions: 12.0

Steps to reproduce: 
https://github.com/odoo/odoo/blob/d259b5b8a616da5a75fb5c4635708c670c28cc56/addons/product/models/product_pricelist.py#L209
if the rule.base == 'pricelist' but the rule does not have a base_pricelist_id set (rule.base_pricelist_id), it goes to the else clause of the given link.
Then the price_type is 'pricelist' but the product does not have such field defined, so it crashes in this line:
https://github.com/odoo/odoo/blob/d259b5b8a616da5a75fb5c4635708c670c28cc56/addons/product/models/product.py#L581

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please put a real example made in runbot? Or this something that you can only force by code?

**Comment by BT-aestebanez** [comment]
Sorry, I cannot remember how to reproduce the bug.
However, I think it is clear enough and the solution to fix it quite simple.

**Comment by pedrobaeza** [comment]
Sorry, but not really clear although you think it is. If we don't have a way to reproduce, then virtually there's no bug.

**Comment by pedrobaeza** [comment]
Closing as no more answer.

**Comment by BT-aestebanez** [comment]
I have not answered because I could not reproduce it in runbot

**Comment by pedrobaeza** [comment]
When you'll able to do it, please answer and it will be reopened.

**Comment by BT-aestebanez** [comment]
Ok, thanks
I will try to do it one more time
