### ISSUE TITLE
Unnecessary code lines in mail_thread

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#30611]
Odoo 11.0
https://github.com/odoo/odoo/blob/5f77d0e77d9003765e16232cc44d432ecd3967c5/addons/mail/models/mail_thread.py#L1652

Look at the full code:
```
            partner_id = False  # <<-- Attention!
            email_address = tools.email_split(contact)
            if not email_address:
                partner_ids.append(partner_id)  # <<-- ?
                continue
            if exclude_aliases and self.env['mail.alias'].search([('alias_name', 'ilike', email_address)], limit=1):
                partner_ids.append(partner_id)  # <<-- ?
                continue
```
'partner_id' is **always** equals False! Is't it?
Why it needed "partner_ids.append(**False**) " ?

These lines need to be removed.

**Comment by pedrobaeza** [comment]
Please don't create more issues with code and propose directly the PRs.
