### ISSUE TITLE
Inconsistent behavior considering the currency for the cost of the products

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#30616]
## Impacted versions:

11.0 and 12.0

## Steps to reproduce:

1. Install the next modules `sale_margin` and `mrp_bom_cost`
2. On Settings, activate: `Multi-Currencies`, `Multi-companies` and set `​Multiple Sales Prices per Product` with `Prices computed from formulas` option
3. Go to Companies and change `My Company, Chicago` currency to `EUR`
4. Create product with the next specifications:

   ```
    name: Product EUR (Sale 100, Cost 50)
    company: My Company, Chicago
    sale price: 100
    cost: 50
    Product Type: Storable Product
   ```

5. Create product with the next specifications:

   ```
    name: Product USD (Sale 100, Cost 50)
    company: Demo Company
    sale price: 100
    cost: 50
    Product Type: Storable Product
    ```

6. Create a new Pricelist with the next specifications:

   ```
    name: Based on Cost
    Pricelist Items: (add one line) 
       Apply on: Global
       Compute Price: Formula
       Based on: Cost
   ```

7. Create a Sale order with `Based on Cost` pricelist and choose products created in step 4 and 5.
8. Validate the sale order, go to related picking, force done quantity to 1 for both products and validate it.
9. Open a new tab, activate developer mode and go to menu `Invetory / Reporting / Stock Moves`
10. Add `price_unit` and `value` fields to the tree view using developer mode option "Edit view: List".
11. Remove actual filters and filter by Product searching "USD" and "EUR".
12. Open a new tab, activate developer mode and go to `Inventory / Reporting / Inventory Valuation`. Leave default option and confirm
13. Filter by Product searching "USD" and "EUR"
14. Create new product:

   ```
    name: Mixed (USD - EUR)
    company: Demo Company
    Create BOM with components: USD and EUR products
    Product Type: Storable Product
   ```

15. On the product form view click on `Compute price from BOM` button.

## Current behavior:

We consider that Odoo has an inconsistent behavior because it has two different ways to consider the currency for the cost of the product:

* Case 1: Odoo considers the cost on the product_product.currency_id
* Case 2: Odoo considers the cost on the env.user.currency_id (which really is the property company's currency)

Here some examples:

*On sale order:* 

* Regarding sale price, Odoo considers that the cost of the product "Product EUR (Sale 100, Cost 50)" is on "EUR" and convert it to "USD" [Case 1]
* Regarding the cost price, Odoo considers that the cost of the same product is in USD (currency of the company) [Case 2]

![image](https://user-images.githubusercontent.com/7593953/51843496-e969d280-22f1-11e9-9b48-aaf9aefd0bcf.png)

*On stock moves:*

* Unit price are computed as 50 for each product (which means that Odoo considers the cost on USD) but the field's help said [Value given in company currency and in product uom](https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L109-L111) [Case 1]
* the method [_prepare_account_move_line](https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/stock.py#L523) uses the `stock_move.value field` and is used as if it is on the company currency [Case 2]

![image](https://user-images.githubusercontent.com/7593953/51843575-0f8f7280-22f2-11e9-88cd-a8b6696cf6b0.png)

*On inventory valuation:*

* Value is shown on `product_template.currency` which are USD or EUR. The inventory valuation should be in the company's currency. Also the sum is not valid as we are mixing USD and EUR [Case 1]

![image](https://user-images.githubusercontent.com/7593953/51843614-23d36f80-22f2-11e9-8e93-2a89d8c8cd42.png)

*On product:*

* The widget for the cost field is based on the `product_template.currency_id` field [Case 1]
* The calculated cost is 100 which means that Odoo considers the costs on company currency [Case 2]

![image](https://user-images.githubusercontent.com/7593953/51843633-2cc44100-22f2-11e9-8503-c9d78c5948bf.png)

## Expected behavior:

The cost must be considered only in one criteria: on the product_template.currency_id or property company's currency.

We believe that a better behavior would be to consider it as the "property company's currency" because the standard_price is actually the "accounting cost for the company" and must be reflected always on the company currency

**Comment by zaoral** [comment]
FYI opw-1934443

**Comment by qdp-odoo** [comment]
@sle-odoo @lap-odoo this is something you may want to give a read

**Comment by jjscarafia** [comment]
thanks @qdp-odoo . This is bringing us headaches with some customers.

**Comment by zaoral** [comment]
Fixed in https://github.com/odoo/odoo/pull/31402

**Comment by infoedgarpc1** [comment]
I have the same problem with odoo 12 but doing the modifications of the odoo file does not work when I put the code of def _compute_cost_currency_id (self):
        for template in itself:
            template.cost_currency_id = self .env.user.company_id.currency_id.id
in addons / product / models / product_template.py
