### ISSUE TITLE
[BUG] _find_partner_from_emails exclude_aliases is not working

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#30610]
Odoo 11.0, 12.0
https://github.com/odoo/odoo/blob/5f77d0e77d9003765e16232cc44d432ecd3967c5/addons/mail/models/mail_thread.py#L1654

model mail.alias field 'alias_name' is **not contain** domain name, 
but email_address **contain** domain name. 
Example:
mail.alias alias_name = 'sales'
but email_address = 'sales@my-domain.com'

This search code is not working.

**Comment by KomarovAlea** [comment]
> If this is a code question, it's better to put the PR with the proposed change and discuss there the reasons of the change.

Sorry, I can't do it right(yet).

**Comment by pedrobaeza** [comment]
Any special reason or only time?

**Comment by KomarovAlea** [comment]
> Any special reason or only time?

No practice. Never did it ever again. I'm afraid to break something)

**Comment by pedrobaeza** [comment]
Don't worry about that, as you can't break anything in Odoo itself. The PR is a proposal, so until is accepted and merged, nothing happens. Git/GitHub flows requires a bit of practice, but you'll see that soon you'll do it as a natural task, and we are here for helping you in specific problems, but as you can understand, not being teachers for the whole process. For that, there are plenty of tutorials across Internet (as this is not Odoo specific).
