### ISSUE TITLE
POS : Blocking message on not certified connection

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#30613]
Set up a secured Odoo website (https).

Set up a point of sale with a 'PosBox-like device' (with https too but with self-signed certificate).

It's not possible to load POS anymore.

Blocking message: 

Https connection to IoT Box failed.

Make sure you are using IoT Box v18.10 or higher.

Due to https://github.com/odoo/odoo/commit/8e63bcb47c72240f5d520f157b0ae5ffa291a714

OPW-1934413

**Comment by rousseldenis** [comment]
@switch87 In production, it's 8069 one, but I reproduced it on another one (444). It does not depends on the port.

**Comment by rousseldenis** [comment]
Note that calling directly the url on a browser works.

**Comment by switch87** [comment]
To get it working on https you should open port 443.
https://github.com/odoo/odoo/blob/8e63bcb47c72240f5d520f157b0ae5ffa291a714/addons/point_of_sale/static/src/js/devices.js#L252

**Comment by rousseldenis** [comment]
@switch87 Mmmf, so with your modification, you cannot use another port than 443... as before, it uses the options.port
It's a llittle bit restrictive, uh ?

**Comment by rousseldenis** [comment]
@switch87 Could you not closing this as open issues here allow to maintain visibility and not to have duplicate issues? It's the first time I have an issue closed with that argument...

**Comment by Yenthe666** [comment]
I'd rather have issues open too honestly. They should be closed when the official ticket (at the Odoo support team through odoo.com/help) is resolved, not when it is ongoing.
Do you mind me reopening this @switch87?

**Comment by mart-e** [comment]
@rousseldenis thanks, I forgot that part.
But still what is your setup? What is this device doing?
If I understand correctly, you have a device that is running with HTTPS, it is configured in the pos interface as a posbox but isn't actually one and doesn't answer on the `/hello` route, right?

**Comment by rousseldenis** [comment]
Yes, it can happen that you want to start the POS and the device is not connected or has errors. You cannot restrict the starting of the POS on device errors...

**Comment by switch87** [comment]
@rousseldenis https://github.com/odoo/odoo/pull/32306

**Comment by nle-odoo** [comment]
This should be solved with https://github.com/odoo/odoo/pull/32306 that replace the loading error by an information popup on the first connection.

**Comment by houssine78** [comment]
@mart-e, @nle-odoo  is also impacting v11 and v12. could you port the fix to those branches ?

**Comment by nle-odoo** [comment]
Hello,


The fix is in 11.0 and 12.0 since 7 days ago in this forward-port commit:
 https://github.com/odoo/odoo/commit/214e819c1bbbbea2c55adc8feab6a269a845cdd4
