### ISSUE TITLE
Image Resize Ratio [Framework]

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#30632]
Impacted versions: All versions with eCommerce

Steps to reproduce: Add main product image and additional product images.  The method to add multiple images per product has changed.  In 12 it is added automatically if you install the eCommerce module and is in the eCommerce section on product page.  In previous version it was added by the configuration settings under website and sales.

Current behavior:  
Main product images use the method which creates  square (1024x1024) images regardless of the original image ratio.  Regardless if the image is png or jpg, the extra space is filled with white. 

Additional images retain their aspect ratio.  

Expected behavior:  That the main product image and the additional images would both keep the uploaded images aspect ratio.  

Video/Screenshot link (optional):
![side-by-side1](https://user-images.githubusercontent.com/14188201/51861843-1918da80-22f2-11e9-8ee7-44e10d59fd74.jpg)

**Comment by pedrobaeza** [comment]
@JKE-be I remember this being handled in a PR, right?

**Comment by rowemoore** [comment]
It's pretty easy to add another image field to product_template and use it for website_sale.  It's just surprising that this hasn't been a big enough issue to get it in core yet.  Maybe Odoo still thinks it's hip to be square. ;-)

**Comment by rowemoore** [comment]
> Not sure that you will be happy tomorrow when you pull your Odoo that all is broken because we added a new field and that you don't update all the modules.

Sorry, I just meant create a custom module that inherits product.template.  I also inherit website sale views to replace the original product image with my new one.  The nice thing about this method vs just using product.product pictures is that the user can easily control the main image.  Using product variants you would either need to make sure the main image was always in the same place (e.g. [0] ) or add _order sequence or a "main image bool" to product.image (via my custom module).  

When the problem is fixed in core it will be easy to populate the new image field(s) with my existing images and then uninstall my custom module.

Anyway, thanks for your help.   I would never hack core on my build.  I just came here to ask the pros if there was already an approved method for accomplishing this.

Have fun,

Cowboy Fudd
