### ISSUE TITLE
[10, 11, 12, master] resources in demo data are set without user relation

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#30631]
Impacted versions: 10.0, 11.0, 12.0, master

Steps to reproduce: Login with the administrator user on any of the Odoo versions. Activate developer mode and go to resources. You'll see that a lot of resources are set without a user, while the user field is required in the frontend:
![image](https://user-images.githubusercontent.com/6352350/51857685-2acea200-2333-11e9-8a96-a6e9e8ac005b.png)

Current behavior:
The demo resources are set without a related user while the user field in the frontend is required.

Expected behavior: Set a related user on this demo data?

**Comment by Yenthe666** [comment]
Hi @mart-e,

I found this one by coincidence. Do you agree that we should link the resources to user records? If so, should I create new users in the demo data and link these? Accepted in stable or master?

**Comment by mart-e** [comment]
Hi,

No not really. If you create manually a resource you have to set a value for the user but here it is automatic resources created for the demo data that are linked to the employee record (add the field `resource_id` to an `hr.employee` view to see the relation).

This menu is present for debugging reason but it is not really expected you create manually your resources, it will be automatic thanks to the mixin.

cc @tivisse is the attrs on the field `user_id` still required? It does not make much sense for demo data like these ones.

**Comment by tivisse** [comment]
The attrs makes sense if you try to create the resource by hand. Don't forget that this is a related field, if you set an user on the employee, it will appear automatically on the resource.

NB: You're not supposed to create a resource.resource, this work is delegated to the mixin.

I won't change anything.

**Comment by Yenthe666** [comment]
Ok. Thanks for the feedback and insight guys.
