### ISSUE TITLE
 Wkhtmltopdf seems to be broken issues

### ISSUE THREAD

**Issue by khiacow** [odoo/odoo#30668]
impacted versions: Odoo 12
OS version: Ubuntu Server 18.04 LTS (HVM)

try installing belowlink, but still no work "Your installation Wkhtmltopdf seems to be broken. The report will be shown in html.".

How to fix this issues?

sudo wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo wget http://download.odoo.com/deb/xenial/wkhtmltox-0.12.1_linux-trusty-amd64.deb
sudo wget http://download.odoo.com/deb/bionic/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-wheezy-amd64.deb
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-wheezy-amd64.deb

sudo dpkg -i XXXXXX.deb
sudo apt-get install -f
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

**Comment by khiacow** [comment]
reboot, fixed. 
but the output pdf file can't show the details.

https://i.imgur.com/yFSaqeV.png

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
