### ISSUE TITLE
[12.0][BUG] hr_holidays: global leaves during request calculation

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#30672]
Impacted versions:
12.0

Steps to reproduce:
1. Define a Working Time as 10:00-14:00 and 15:00-19:00 (8 hours in total) for Mon-Fri, resulting a 40-hour work-week
2. Define a Leave Type with hourly allocation
3. Define a global leave on Dec 25th, 2018 and Jan 1st, 2019
4. Request a leave from 12/19/2018 10:00:00 to 01/04/2019 19:00:00 for that leave type

In our setup there are 2 Working Times defined, one w/o global leaves, other one with.

Current behavior:
Observe that during editing it will calculate 104 hours of leave (13 days), that will change to 88 hours (11 days) after saving the leave request, while header will remain 13 days.

Expected behavior:
During editing and in title, the result would be correct 11 days, which is 13 workdays w/o global leaves on Dec 25th, 2018 and Jan 1st, 2019

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/345102/51960347-564faa80-2461-11e9-9a91-6b7bf0b38405.png)
![image](https://user-images.githubusercontent.com/345102/51960477-d1b15c00-2461-11e9-83af-ec71786b45e6.png)
![image](https://user-images.githubusercontent.com/345102/51960487-e4c42c00-2461-11e9-85ac-d025af1f14d6.png)
![image](https://user-images.githubusercontent.com/345102/51960515-01f8fa80-2462-11e9-8b93-2f7285607a3e.png)

**Comment by alexey-pelykh** [comment]
This was tested with #30363 applied, here are the logs:
```
_get_number_of_days (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'days': 13.0, 'hours': 104.0} 
```
88.0 hours appear due to different method usage at https://github.com/odoo/odoo/blob/bdfef60d60d78c5e7360fdabe80e70ea208e6078/addons/hr_holidays/models/hr_leave.py#L374
in `_compute_number_of_hours_display` (that may also benefit from specifying the correct timezone as per #30363? @sswapnesh @beledouxdenis what do you think?)

```
_get_number_of_days (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'days': 13.0, 'hours': 104.0} 
_compute_number_of_hours_display (2018-12-19 10:00:00, 2019-01-04 19:00:00) => 104.0 (104.0) 
```
Yet after saving this appears:
```
_compute_number_of_hours_display (2018-12-19 10:00:00, 2019-01-04 19:00:00) => 88.0 (88.0) 
```

**Comment by alexey-pelykh** [comment]
So, to summarize, there are two issues:
1. Inconsistent results of days/hours because `_compute_number_of_hours_display` uses different function, which is a fallback one for `_get_number_of_days`. Possible mitigation: implement `_get_number_of_hours` in a similar way.
2. Global (or all other?) leaves are not being excluded from computed amount of requested days

**Comment by dku729** [comment]
bro again it showing some another error may be because of removing resource
0.0.0 from requirement.txt

**Comment by alexey-pelykh** [comment]
@dku729 not sure I got it about resource and requirement.txt

**Comment by alexey-pelykh** [comment]
Maybe these logs would help.

During editing:
```
_get_number_of_hours (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'hours': 104.0, 'days': 13.0} 
_get_number_of_hours:get_leave_days_data (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'hours': 0, 'days': 0} 
```

After saving:
```
_get_number_of_hours (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'hours': 86.0, 'days': 10.75} 
_get_number_of_hours:get_leave_days_data (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => {'hours': 16.0, 'days': 2.0} 
```

where `_get_number_of_hours` is:
```
    @api.multi
    def _get_number_of_hours(self, date_from, date_to, employee_id):
        self.ensure_one()

        if employee_id:
            employee = self.env['hr.employee'].browse(employee_id)
            if employee.tz:
                tz = timezone(employee.tz)
                date_from = tz.localize(date_from)
                date_to = tz.localize(date_to)
            work_days_data = employee.get_work_days_data(date_from, date_to)
            _logger.info('_get_number_of_hours (%s, %s) => %s', date_from, date_to, work_days_data)
            _logger.info('_get_number_of_hours:get_leave_days_data (%s, %s) => %s', date_from, date_to, employee.get_leave_days_data(date_from, date_to))
            return work_days_data['hours']

        return self.env.user.company_id.resource_calendar_id.get_work_hours_count(date_from, date_to)

    def _compute_number_of_hours_display(self):
        for holiday in self:
            if holiday.date_from and holiday.date_to:
                holiday.number_of_hours_display = holiday._get_number_of_hours(
                    holiday.date_from,
                    holiday.date_to,
                    holiday.employee_id.id
                )
            else:
                holiday.number_of_hours_display = 0
```

**Comment by alexey-pelykh** [comment]
it seems that there's one more timezone-related issue that depends on whether we're editing the leave request or no, as in logs above after saving a 10.75 days appear, what means that somewhere in attendance calculation 2 hours get cut off by min/max, maybe somewhere here:
https://github.com/odoo/odoo/blob/bdfef60d60d78c5e7360fdabe80e70ea208e6078/addons/resource/models/resource.py#L218

which would explain this log:
```
_get_number_of_hours:attendance (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => [
	(
		datetime.datetime(2018, 12, 19, 8, 0, tzinfo=<DstTzInfo 'Europe/Kiev' EET+2:00:00 STD>),
		datetime.datetime(2018, 12, 19, 12, 0, tzinfo=<DstTzInfo 'Europe/Kiev' EET+2:00:00 STD>),
		resource.calendar.attendance(5,)
	),
...
```
vs
```
_get_number_of_hours:attendance (2018-12-19 08:00:00+02:00, 2019-01-04 17:00:00+02:00) => [
	(
		datetime.datetime(2018, 12, 19, 10, 0, tzinfo=<DstTzInfo 'Europe/Kiev' EET+2:00:00 STD>),
		datetime.datetime(2018, 12, 19, 14, 0, tzinfo=<DstTzInfo 'Europe/Kiev' EET+2:00:00 STD>),
		resource.calendar.attendance(45,)
	), 
...
```

**Comment by alexey-pelykh** [comment]
My further investigation shows that following is true for editing vs non-editing mode of leave request:
 * employee ID is the same
 * resource ID as `employee.resource_id.id` is the same (`21` in my case)
 * resource calendar ID as `employee.resource_calendar_id.id` changes (`1` vs `5`)
 * resource calendar ID as `employee.resource_id.calendar_id.id` _does not change_ (`1` in both cases)

I should mention that in my case, `1` is the default setting for the company, and `5` is the particular calendar set to the particular employee used for these experiments.

In database this person has:
 * a record ID `21` in `resource_resource` table, with `calendar_id = 1`.
 * a record ID `21` in `hr_employee` table, with `resource_calendar_id = 5`

In my case, this is not a unique case, all employees have proper calendar `5`, while all resources that match those employees have `calendar_id = 1`

**Comment by alexey-pelykh** [comment]
As @pedrobaeza suggested (many kudos for him), this means that related data went out of sync at some point, for all employees, and resetting calendar to `1` for everyone and saving those changes, then resaving again with `5` as calendar (all via UI) solved the issue for me, so it must have been something that interfered with data integrity.

**Comment by Yenthe666** [comment]
Thanks for the detailed feedback and report. I've been bitten by this one too today. :)
