### ISSUE TITLE
odoo can't translate  title tag  of template

### ISSUE THREAD

**Issue by xgj1988** [odoo/odoo#30674]
Impacted versions:
odoo 12.0
Steps to reproduce:
1:  translate pos modoule 
2: There is no item about 'odoo pos'
Current behavior:

We can find the 'odoo pos ' in pos_templates.xml.The template id is index.

Expected behavior:
export odoo pos item for translate.
I guest '<!DOCTYPE html> ' could affect  template to translate .but i remote <!DOCTYPE html>, it does't work too.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

All terms are exported and translatable on Transifex. See https://github.com/odoo/odoo/wiki/Translations#translating-with-transifex

**Comment by xgj1988** [comment]
ok 3Q
