### ISSUE TITLE
[8.0, 7.0] hr_timesheet/hr_timesheet_data.xml: Record without name data

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#3069]
Hello,

I already reported this on https://bugs.launchpad.net/openobject-addons/+bug/1312152,
but I'm not sure if bugs reported on launchpad  are still being processed.

hr_timesheet_data.xml contains:

```
    <record id="analytic_journal" model="account.analytic.journal">
        <field name="code">TS</field>
        <field name="name">Timesheet Journal</field>
        <field name="type">general</field>
    </record>

    <record id="hr.employee" model="hr.employee">
        <field name="journal_id" ref="analytic_journal"/>
    </record>
```

The hr.employee Record has no name value.
On a fresh DB that doesn't seem to matter during the installation, however in an existing DB when attempting to install the hr_timesheet module the following error occurs:

2014-04-24 09:15:54,402 9586 INFO odb701 openerp.modules.loading: module hr_timesheet: loading hr_timesheet_data.xml
2014-04-24 09:15:54,468 9586 ERROR odb701 openerp.sql_db: bad query: insert into "resource_resource" (id,"active","time_efficiency","company_id","resource_type",create_uid,create_date,write_uid,write_date) values (106,'True',1.0,1,'user',1,(now() at time zone 'UTC'),1,(now() at time zone 'UTC'))
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "name" violates not-null constraint

I would like to know if the hr.employee record can't be simply removed from this file or what's the reason of having it?

with kind regards,
Sven

**Comment by Symbiofi** [comment]
Hello,

I have the exact same issue with a fresh install (2 days ago).
this problem prevent me to install other modules.

Thanks for your help,
Regards
Régis

**Comment by Yenthe666** [comment]
Hi @svenpetersen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
