### ISSUE TITLE
Inventory Posting date changed when the physical inventory is posted

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#307]
Hello,

When I create a physical inventory document on the online odoo version, I can specify the date and it is saved in the document to be posted.
Unfortunately, when I validate the inventory, the date is changed to the validation date. 
Thank you for your remarks/corrections

**Comment by Yenthe666** [comment]
Dear @ybofr,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
