### ISSUE TITLE
Changing First Day of Week is not working in odoo 12

### ISSUE THREAD

**Issue by kamleshahir** [odoo/odoo#30709]
Impacted versions:
Odoo 12 
Steps to reproduce:
1: Go to  Languages
2: Change First Day of Week
3: Change language in preference and select any date  

Current behavior:
Showing Sunday first day of week

Expected behavior:
it should be show selected first day of week
Video/Screenshot link (optional):

![22](https://user-images.githubusercontent.com/16555768/52037450-0fdb7800-2555-11e9-864f-bd63e9cfd891.png)

![2222](https://user-images.githubusercontent.com/16555768/52037475-2550a200-2555-11e9-8133-952d6eea3a93.png)

![33](https://user-images.githubusercontent.com/16555768/52036903-cdfe0200-2553-11e9-92f9-555ee0df94da.png)

**Comment by kamleshahir** [comment]
yes but First day of week is Monday so it should be Monday right?

**Comment by pedrobaeza** [comment]
OK, I get it, but have you refreshed entirely your browser? Please press Ctrl+F5 and try again.

**Comment by kamleshahir** [comment]
yes i have tried all with Ctrl+F5 refresh

**Comment by Yenthe666** [comment]
Indeed nothing happens when changing it. @mart-e do you know to who it belongs?

**Comment by mart-e** [comment]
Hi,

It was added at 27b30daea54b02c45ed and has an impact on the calendar view type (e.g. event calendar view).

The datepicker you are showing is handled by another library, and use the [moment.js](https://momentjs.com/) locale configuration, not something configurable. For instance, in french:

https://github.com/odoo/odoo/blob/6ca2563155a5343c4dc8af05e20e2debb9438db3/addons/web/static/lib/moment/locale/fr.js#L56-L59

**Comment by Yenthe666** [comment]
@mart-e so if I understand correctly it looks only add calender views and nothing else?

**Comment by mart-e** [comment]
Yes, see #20640 for details when it was developed, the purpose was to impact the calendar view only.

**Comment by xabispacebiker** [comment]
I am having the same problem with date pickers, although the moment locale es_ES is loaded it does not affect the date picker. 

![captura_de_pantalla_2019-02-21_a_las_19_20_43](https://user-images.githubusercontent.com/1733884/53192315-790f5200-360e-11e9-9145-303871528697.jpg)

Any solution ?

**Comment by xabispacebiker** [comment]
Ok, I found the problem. In addons/web/static/src/js/widgets/date_picker.js change:

```
 43             calendarWeeks: true,
 44             buttons: {
 45                 showToday: false,
 46                 showClear: false,
 47                 showClose: false,
 48             },
 49             widgetParent: 'body',
 50             keyBinds: null,
 51             allowInputToggle: true,
 52         }, options || {});
```

to

```
 43             calendarWeeks: true,
 44             buttons: {
 45                 showToday: false,
 46                 showClear: false,
 47                 showClose: false,
 48             },
 49             widgetParent: 'body',
 50             keyBinds: null,
 51             **locale: moment.locale(),**
 52             allowInputToggle: true,
 53         }, options || {});
```

**Comment by andriisem** [comment]
https://apps.odoo.com/apps/modules/12.0/first_weekday/

**Comment by mart-e** [comment]
If you have a patch, please don't hesitate to submit it in master as an improvement for the next version

**Comment by naglis** [comment]
Could be related PR: https://github.com/odoo/odoo/pull/28586

**Comment by Yenthe666** [comment]
Yep, that PR would fix this issue.

**Comment by alexey-pelykh** [comment]
I doubt that #28586 would allow changing datepicker week-start-day. Shouldn't it be affecting https://github.com/odoo/odoo/blob/4b542b048499972a92d8ba734b31f63829fb82da/addons/web/static/lib/jquery.ui/jquery-ui.js#L7090 ?

**Comment by alexey-pelykh** [comment]
Isn't this issue fixed by https://github.com/odoo/odoo/commit/b6f11ace836e946eeeae110cdb08d16d80546238 ?
