### ISSUE TITLE
[12] Default port issue

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#30707]
Impacted versions:
12 on Ubuntu VPS 16.04

Steps to reproduce:
Install odoo on a fresh ubuntu 16.04 VPS

Current behavior:
odoo service is running perfectly
but, when browsing to : serveraddress:8069 it redirects to default port which is 80 and showing the home page of the web site (not odoo web pages)

Expected behavior:
Stays on port 8069 and browse odoo web pages

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something on your deployment, specifically with the reverse proxy you have set.

Closing as no real issue.
