### ISSUE TITLE
[10] website_sale scss img resize

### ISSUE THREAD

**Issue by Ark74** [odoo/odoo#30704]
After a recent update I applied I just noticed some weird behavior on the css, setting images on a wrong ratio for the website_sale module.

**Impacted versions:**
10 (and later?)

**Steps to reproduce:**
Set up products with images (demo is fine), go to online shop.
Check products images.

**Current behavior:**
Images on online store get resized with wrong ratio by sccs

**Expected behavior:**
Correct ratio image.

**Suggestion**
This element,
https://github.com/odoo/odoo/blob/10.0/addons/website_sale/static/src/css/website_sale.css#L46

```
.oe_product .oe_product_image img {
  max-width: 100%;
  max-height: 100%;
  margin: auto;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  z-index: 4;
}
```
could be changed with,

```
.oe_product .oe_product_image img {
  max-width: 100%;
  max-height: 100%;
  height: 100%;
  margin: auto;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  z-index: 4;
}
```
Video/Screenshot link (optional):
Tested on runbot. 438390-10-0-4a5862 on runbot11.odoo.com

![438390-10-0-4a5862_on_runbot11 odoo com](https://user-images.githubusercontent.com/7444518/52012256-bfeea980-249f-11e9-864e-d0eba7a1efb8.gif)

**Comment by pedrobaeza** [comment]
@JKE-be what do you think about this suggestion?

**Comment by JKE-be** [comment]
Hi

I cannot reproduce your problem.

Imo, add height:100% will force a bad ratio.
In actual case, we just use the bigger between width and height and avoid a bad resizing.

And adding height:100% will force small image to be display zoomed. (Eg: 404)
![image](https://user-images.githubusercontent.com/4848797/52043384-d8160580-253f-11e9-9a53-ba01be9ab2a9.png)

**Comment by Ark74** [comment]
> I cannot reproduce your problem.

That's weird, it was done on runbot.

> Add height:100% will force a bad ratio for small image.

Actually it doesn't, in you example, you'll see _Gold Membership_, _Apple Wireless K_., and other articles with small pictures not being resized, I've only seen "no picture" image being resized.
I've tested on 150 store db, and I see no other bad resizing.

Either way, thanks for taking the time to check.
I still I think there is work to be done there at least on v10.

Cheers!

**Comment by rdeodoo** [comment]
I tried on runbot Odoo 10.0 to create a new product and set up some different images but everything was displayed correctly on /shop.

Could you please retry on runbot and if the bug still occurs, provide us the exact picture you uploaded (eg a google drive link) and the step to reproduce the issue?

**Comment by Ark74** [comment]
@rdeodoo I tested with runbot
553193-10-0-e210fa.runbot16.odoo.com/shop

And as you mention seems this issue is no longer present.
Thanks for checking back on this issue, I'll be closing this.
