### ISSUE TITLE
[BUG][11.0] ir.filters, it is not possible to set a special domain

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#30708]
Impacted versions:
11 and later

Steps to reproduce:

Go to Settings / User Defined Filter
Create a new filter
Add a domain (with the widget domain), select a date field (ex : create on)
--> Issue : it is not possible to set `context_today().strftime('%Y-%m-%d'))`

Idea : Maybe create operators "today" "today plus x days" "today minus x days"

**Comment by pedrobaeza** [comment]
This has been discussed other times. I remember @Yenthe666 was involved. The conclusion is that right now, although it's true this is not possible due to the new domain widget, it's not expected to be fixed, and less in stable versions.

Maybe @ged-odoo can tell us if there's anything in the roadmap.

**Comment by Yenthe666** [comment]
Hi,

Yes indeed, there have been issues and tickets about this one. It was indeed lost in a migration and nobody ever returned it (sadly). In fact all dynamic date domains do not work in V11 and V12 and master now. I still miss this feature quite often honestly.
@ged-odoo do you know if there is any plans to get it back actually

**Comment by mreficent** [comment]
@Yenthe666 Maybe you could add the `wishlist` tag 😏

**Comment by Yenthe666** [comment]
Haha I sure can. Honestly, I still find this a bug as it was possible at a point in history, Odoo just doesn't agree..

**Comment by fmdl** [comment]
@Yenthe666 but you can remove `widget="domain"` in the xml view :-)

**Comment by Yenthe666** [comment]
@fmdl but then I'm still not able to make dynamic date filters, right?

**Comment by fmdl** [comment]
without the widget you can write what you want

**Comment by Yenthe666** [comment]
but does the filter also apply the domain to calculate the dates then?

**Comment by fmdl** [comment]
yes you can put a dynamic domain

**Comment by Yenthe666** [comment]
Thanks for the tip, that is very interesting!
