### ISSUE TITLE
[12] Running issue in new Ubuntu 16.04 VPS

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#30705]
Impacted versions:
12

Steps to reproduce:
Install odoo12 on a new Ubuntu server 16.04 VPS

Current behavior:
Installation OK but runing failed

Expected behavior:
Runs immediatly after installing

 **systemctl status odoo12**    gives:
● odoo12.service - Odoo12
   Loaded: loaded (/etc/systemd/system/odoo12.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-01-30 16:11:51 EST; 13min ago
 Main PID: 2806 (code=exited, status=1/FAILURE)

Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/configparser.py", line 696, in read
Jan 30 16:11:51 vps45433 odoo12[2806]:     self._read(fp, filename)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/configparser.py", line 1012, in _read
Jan 30 16:11:51 vps45433 odoo12[2806]:     for lineno, line in enumerate(fp, start=1):
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
Jan 30 16:11:51 vps45433 odoo12[2806]:     return codecs.ascii_decode(input, self.errors)[0]
Jan 30 16:11:51 vps45433 odoo12[2806]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 81: ordinal not in range(128)
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Unit entered failed state.
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Failed with result 'exit-code'.

**journalctl -u odoo12.service**   gives:
-- Logs begin at Wed 2019-01-30 16:02:35 EST, end at Wed 2019-01-30 16:26:12 EST. --
Jan 30 16:02:44 vps45433 systemd[1]: Started Odoo12.
Jan 30 16:02:45 vps45433 odoo12[507]: Traceback (most recent call last):
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo-bin", line 8, in <module>
Jan 30 16:02:45 vps45433 odoo12[507]:     odoo.cli.main()
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/cli/command.py", line 60, in main
Jan 30 16:02:45 vps45433 odoo12[507]:     o.run(args)
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/cli/server.py", line 176, in run
Jan 30 16:02:45 vps45433 odoo12[507]:     main(args)
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/cli/server.py", line 124, in main
Jan 30 16:02:45 vps45433 odoo12[507]:     odoo.tools.config.parse_config(args)
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 336, in parse_config
Jan 30 16:02:45 vps45433 odoo12[507]:     self._parse_config(args)
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 389, in _parse_config
Jan 30 16:02:45 vps45433 odoo12[507]:     self.load()
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 540, in load
Jan 30 16:02:45 vps45433 odoo12[507]:     p.read([self.rcfile])
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/usr/lib/python3.5/configparser.py", line 696, in read
Jan 30 16:02:45 vps45433 odoo12[507]:     self._read(fp, filename)
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/usr/lib/python3.5/configparser.py", line 1012, in _read
Jan 30 16:02:45 vps45433 odoo12[507]:     for lineno, line in enumerate(fp, start=1):
Jan 30 16:02:45 vps45433 odoo12[507]:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
Jan 30 16:02:45 vps45433 odoo12[507]:     return codecs.ascii_decode(input, self.errors)[0]
Jan 30 16:02:45 vps45433 odoo12[507]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 81: ordinal not in range(128)
Jan 30 16:02:45 vps45433 systemd[1]: odoo12.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 16:02:45 vps45433 systemd[1]: odoo12.service: Unit entered failed state.
Jan 30 16:02:45 vps45433 systemd[1]: odoo12.service: Failed with result 'exit-code'.
Jan 30 16:11:51 vps45433 systemd[1]: Started Odoo12.
Jan 30 16:11:51 vps45433 odoo12[2806]: Traceback (most recent call last):
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo-bin", line 8, in <module>
Jan 30 16:11:51 vps45433 odoo12[2806]:     odoo.cli.main()
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/cli/command.py", line 60, in main
Jan 30 16:11:51 vps45433 odoo12[2806]:     o.run(args)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/cli/server.py", line 176, in run
Jan 30 16:11:51 vps45433 odoo12[2806]:     main(args)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/cli/server.py", line 124, in main
Jan 30 16:11:51 vps45433 odoo12[2806]:     odoo.tools.config.parse_config(args)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 336, in parse_config
Jan 30 16:11:51 vps45433 odoo12[2806]:     self._parse_config(args)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 389, in _parse_config
Jan 30 16:11:51 vps45433 odoo12[2806]:     self.load()
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/opt/odoo12/odoo/odoo/tools/config.py", line 540, in load
Jan 30 16:11:51 vps45433 odoo12[2806]:     p.read([self.rcfile])
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/configparser.py", line 696, in read
Jan 30 16:11:51 vps45433 odoo12[2806]:     self._read(fp, filename)
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/configparser.py", line 1012, in _read
Jan 30 16:11:51 vps45433 odoo12[2806]:     for lineno, line in enumerate(fp, start=1):
Jan 30 16:11:51 vps45433 odoo12[2806]:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
Jan 30 16:11:51 vps45433 odoo12[2806]:     return codecs.ascii_decode(input, self.errors)[0]
Jan 30 16:11:51 vps45433 odoo12[2806]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 81: ordinal not in range(128)
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Unit entered failed state.
Jan 30 16:11:51 vps45433 systemd[1]: odoo12.service: Failed with result 'exit-code'.

**Comment by urielml1** [comment]
Hi aitalinassim,

I have a similar problem like you, but i used a centos VPS.
Can you resolve that problem?
Thank you.
Regreads..
