### ISSUE TITLE
Related field translation not working

### ISSUE THREAD

**Issue by MohsenWaleed** [odoo/odoo#30703]
Impacted versions:
11.0

Steps to reproduce:
 - Set translate=True to  **resource.name** field in resource.resource model.
 - **name** field in hr.employee is related field to resource.name, when I try to translate the **employee name** from employee form, it translate only  **resource.name**  and the translated name not shown in employee name.

Current behavior:
Translate related field value not showing for both fields.

Expected behavior:
Translate related field value should be showing for both fields.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something expected, as related fields are not supposed to be translatable this way. If you want that, you should setup a regular field, and synchronize through other way.

Closing as won't fix, due to known limitation of the ORM framework.

**Comment by MohsenWaleed** [comment]
Thanks @pedrobaeza what does you mean by "synchronize through other way"?

**Comment by pedrobaeza** [comment]
One possibility is to override create/write and iterate over active languages for getting/setting the field in the other model passing the lang context.

**Comment by MohsenWaleed** [comment]
I was able to do it through PO file and I can do it for all created employees but for new employee I need  my user to be able to enter the translation automatically. I will work on your idea. Many thanks.

![image](https://user-images.githubusercontent.com/24973578/52073186-f1e33700-2597-11e9-97a4-e07b94bb3bf2.png)
