### ISSUE TITLE
[11.0 e] Sale Order: Change of unit price in quotation after confirmed the sales order

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#30739]
**Impacted versions:** 11.0 e

**Steps to reproduce:**

1. Create quote
2. Confirm sales order
3. Edit lines and change quantities

**Current behavior:**

When confirming a quote or a sales order and you need to change the amount. The unit price changes to the value assigned by default to the sale price of the product. Makes unwanted billing changes

**Expected behavior:**

Once the quote is confirmed, the price is not changed automatically, unless it is changed manually by the user

**Video/Screenshot link (optional):**

https://drive.google.com/file/d/1ojK2nU1vfDgZzyn9SEPc86mLswIvwbF7/view

**Comment by pedrobaeza** [comment]
This is something expected, as if you change the quantities, prices can vary according scale pricelists. If you don't want that the price vary, don't assign manually prices in the SO, but put then on pricelists. The reverse case will happen that others will be unhappy if when they change the quantity, prices are not updated. You have the bad luck of being on the affected side.

Any way, I let @fgi-odoo to decide if reversing the "default" can make sense for future versions.

**Comment by fgi-odoo** [comment]
I confirm what Pedro says. Whatever the document status is, most users will expect the pricelists to be still taken into account. Anyway, any price change is recorded in the logs so it's easy to retrieve the original price.
