### ISSUE TITLE
[12.0] Multi website showing prices from price lists assigned to different websites

### ISSUE THREAD

**Issue by tomeyro** [odoo/odoo#30743]
Impacted versions: 12.0

Steps to reproduce:

Database with multi-website and multiple prices per product (by formula).
Having the default "My website" and "Public pricelist" (assigned to default website).
Create an additional website and an additional price list and assign to the new website.
Create a new product an publish it on the new website.
On the public pricelist assign a fixed price to all products of 999.
On the new pricelist assign a fixed price of 123 only to the new product.

Current vs Expected behavior:

As only the new price list is assigned to the new website, the price showing on the
site for the new product should be of 123, however, it is showing 999.

The only way to show 123 is by removing the website from the selection box of the
default price list, so it appears that the price displayed on the website is taken from
a price list that has any website assign and not specifically the website that is open.

Video/Screenshot link (optional):

https://drive.google.com/file/d/1HoYJc4lJ4wXMn_70y7tv9DzY1AvWzkFn/view?usp=sharing

**Comment by tomeyro** [comment]
opw-1935785

**Comment by tomeyro** [comment]
CC: @oscarolar

**Comment by rdeodoo** [comment]
This is going to be fixed this week hopefully.
There is a pricelist fix coming, part of it fix your flow. I will let you know what this is merged.
Thank you for reporting that issue.

**Comment by rdeodoo** [comment]
Hello, this should be fixed with https://github.com/odoo/odoo/pull/28301
