### ISSUE TITLE
[account] Aged Partner Balance does include Unposted Entries

### ISSUE THREAD

**Issue by mcassuto** [odoo/odoo#3077]
How to reproduce:
- create a new database with accounting and payments
- create a customer with an invoice
- confirm the invoice
- create a partial payment against this invoice
- even if the payment is posted, the related entry is unposted; let it unposted

The aged partner balance then shows a correct amount in the column 0-30, but the total column shows the total amount of the invoice.

**Comment by Yenthe666** [comment]
Hi @mcassuto,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
