### ISSUE TITLE
LOT stock location is ignored in stock move

### ISSUE THREAD

**Issue by andrestone** [odoo/odoo#30778]
**LOT stock location is ignored in stock move**

Impacted versions:

 - 12.0
 
Steps to reproduce:
 
 1. Find any product with stock available in a lot stored in a "Original Warehouse".
 2. Create "Warehouse Test1" and "Warehouse Test2"
 3. Select "Detailed Operation" in any "Internal Transfer" Operation Type.
 4. Make the internal transfer of any available quantity of the product lot found at the "Original Warehouse" from "Warehouse Test1" to "Warehouse Test2" (both with zero stock and just created).
 
Current behavior:
 
 - It does the transfer without any warnings / complains.
 
Expected behavior:
 
 - "Stock Unavailable" error message.

**Comment by pedrobaeza** [comment]
Are you forcing the quantity done in the move?

**Comment by andrestone** [comment]
Yes, I'm filling the "Done" field with the amount I want to transfer.
In contrast, I wouldn't be allowed to do that if the product / operation didn't have tracking enable (which would be the expected behavior, since there is no stock whatsoever in the "Source" location).

**Comment by pedrobaeza** [comment]
Yes, but forcing that, you are ignoring the stock levels that are got through "Check availability", so this is expected, and you will get negative stock levels when validating the picking.

If you don't want this, look for a module that prevents negative stock levels.

Closing as expected behavior.

**Comment by andrestone** [comment]
I just wonder why it should be expected to allow editing the "Done" quantity when using lot tracking while it is NOT expected when you're not using lot tracking. This is, at least, inconsistent and could be reasonably considered a malfunction.

**Comment by pedrobaeza** [comment]
It's not a malfunction, but an improvement over your use case. In other use cases, incoming stuff is not classified with lots, and the lot is put on delivery (for warranty reasons), so what you want will provoke problems or unwanted warnings. Although having the option is desirable, it's not something that is going to be "fixed" in current version.

**Comment by andrestone** [comment]
I strongly disagree. If your system allows you to print a flawed Tracking
Report, with zero warnings and absolutely no way to enforce consistency in
the information being reported, and moreover when it advertises "Full
Tracking Support", it really looks like to me as something to be fixed.

It would be less of a bug and more of a "misconception" if the behavior on
the non-trackable products was the same, but this is not the case.

**Comment by pedrobaeza** [comment]
I'm not saying your scenario is not interesting to also be covered, but that this is not something that can't happen in current versions, as it's a new feature.
