### ISSUE TITLE
Request Class not working in Odoo V12

### ISSUE THREAD

**Issue by HarshitTEmipro** [odoo/odoo#30776]
I am using odoo v12 I have to try to simple request to get any simple URL using request class but not retrieve any result such as I using.

import requests

r = requests.get("https://itstrianglemobile.com/images/phones/iphone-xr/iPhone-xr-1.jpg") 

when I execute that code using odoo it is not working. but when I try to execute using terminal it is working. I have no idea about that.

**Comment by pedrobaeza** [comment]
Odoo is not using REST, but XML-RPC/JSON-RPC. Please check how here: https://www.odoo.com/documentation/12.0/webservices/odoo.html
