### ISSUE TITLE
odoo shell: "AttributeError: environments"

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#30782]
Impacted versions:
12.0

Steps to reproduce:
1. Create a new database using
`odoo-bin -d newdb12 -i base`

2. Start odoo shell subcommand
`odoo-bin shell -d newdb12 --log-level=error`

3. Retrieve a search
`env['res.users'].search([])`
or
`self.env['res.users'].search([])`

Current behavior:
```traceback
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    self.env['res.users'].search([])
  File "odoo/models.py", line 1561, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "odoo/addons/base/models/res_users.py", line 422, in _search
    access_rights_uid=access_rights_uid)
  File "odoo/models.py", line 4055, in _search
    self.sudo(access_rights_uid or self._uid).check_access_rights('read')
  File "odoo/models.py", line 4714, in sudo
    return self.with_env(self.env(user=user))
  File "odoo/api.py", line 850, in __call__
    return Environment(cr, uid, context)
  File "odoo/api.py", line 794, in __new__
    env, envs = None, cls.envs
  File "odoo/tools/func.py", line 112, in __get__
    return self.fget.__get__(None, owner)()
  File "odoo/api.py", line 767, in envs
    return cls._local.environments
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    raise AttributeError(name)
AttributeError: environments
```

Expected behavior:
Browse list with the result like past versions

Video/Screenshot link (optional):
<img width="1300" alt="screen shot 2019-02-02 at 11 05 02 am" src="https://user-images.githubusercontent.com/6644187/52167029-6c1bd480-26da-11e9-981b-2a46135d237d.png">

Arch:
Ubuntu 16.04.4 LTS
Python 3.5.2
Sha 0336cbb50bac9b118c25e3e495f1f4d8f97e38b0

**Comment by moylop260** [comment]
Thanks for reply
I will try to reproduced it for an empty instance.
For now I will close it, thanks

**Comment by Espzai** [comment]
@moylop260 It looks like this error is with the bpython REPL only. Try in other REPL and you would be all set.

**Comment by moylop260** [comment]
I confirm that `bpython` is the issue.
I just uninstalled it and it worked fine!
