### ISSUE TITLE
website submenu can't be installed by module data file

### ISSUE THREAD

**Issue by wxwok** [odoo/odoo#30783]
All website submenu are installed to the website's default main menu.

Impacted versions:
12, revision:9cfd1eefd895cb21a600cd7c9f9c490ad637049a

Steps to reproduce:
create a module which includes website submenu like the following code:
`<record id="menu_shop" model="website.menu">
    <field name="name">Shop</field>
    <field name="parent_id" ref="website.main_menu"/>
    <field name="sequence" type="int">20</field>
</record>
<record id="menu_test_shop" model="website.menu">
    <field name="name">Sub Menu</field>
    <field name="url">/shop</field>
    <field name="parent_id" ref="menu_shop"/>
    <field name="sequence" type="int">20</field>
</record>`
Install the module.

Current behavior:
the submenu is installed to all website's default main menu.
Expected behavior:
the submenu "menu_test_shop" should be installed to its parent menu "menu_shop" which is specified by the ref="menu_shop"

Video/Screenshot link (optional):

I read the code of addons/website/models/website.py line 1149. The code is:
`            for website in self.env['website'].search([]):
                w_vals = dict(vals, **{
                    'website_id': website.id,
                    'parent_id': website.menu_id.id,
                })
`
it means that all menu's parent_id is set to website.menu_id.id. I think that is the reason but I don't know how to fix it. Anyone can tell me how to calculate the parent id by the field's ref="menu_shop" parameter?
I also asked the question in [the odoo forum](https://www.odoo.com/forum/help-1/question/how-to-add-a-sub-menu-to-website-module-145065)

**Comment by pedrobaeza** [comment]
As this is more a question than an issue, and having the forum entry, I close this one.

**Comment by wxwok** [comment]
Sorry for including too many information in the issue description, I will remove the forum entry and the question to only keep the issue.

**Comment by wxwok** [comment]
I read the code of addons/website/models/website.py line 1149. The code is:
`            for website in self.env['website'].search([]):
                w_vals = dict(vals, **{
                    'website_id': website.id,
                    'parent_id': website.menu_id.id,
                })
`
it means that all menu's parent_id is set to website.menu_id.id.

**Comment by MichiEnclustra** [comment]
Any news on this?

**Comment by madux** [comment]
This is really a bug, any hope on how to fix this?

**Comment by YnievesDotNet** [comment]
I have same problem... any guide to fix that

**Comment by lrstry** [comment]
Same here. The following import does not work as expected. The generated parent_path of "menu_onboarding_myprofile" is "4/9/", meaning: parent_id is still main_menu.

        <record id="menu_onboarding" model="website.menu">
            <field name="name">Onboarding</field>
            <field name="parent_id" ref="website.main_menu"/>
            <field name="sequence" type="int">60</field>
        </record>
        <record id="menu_onboarding_myprofile" model="website.menu">
            <field name="name">My Profile</field>
            <field name="url">/onboarding/employee</field>
            <field name="parent_id" ref="menu_onboarding"/>
            <field name="sequence" type="int">0</field>
        </record>

**Comment by kimjb98** [comment]
Hubo alguna solución? Tengo el mismo error

**Comment by kimjb98** [comment]
Was there a solution? I have the same error
