### ISSUE TITLE
Impossible to use comparaisons expression in mail template

### ISSUE THREAD

**Issue by ertus-odoo** [odoo/odoo#30819]
Impacted versions:
Odoo 10.0 Enterprise Edition, French database, Paris,French Timezone

Steps to reproduce:
Create new module with data XML file to create a new mail template. In body html field, add these lines :
```
<div>
% if 2 >= 1:
2 is greater than or equal to 1
% endif
% if 2 >= 1:
2 is greater than or equal to 2
% endif
</div>
```

Current behavior:
Error in log : TemplateSyntaxError: unexpected char u'&' at 14
When I edit the template in Odoo with debug mode, Odoo change my template :
```
<div>
% if 2 &lt;= 1:
2 is greater than or equal to 1
% endif
% if 2 &gt;= 1:
2 is greater than or equal to 2
% endif
</div>
```
I have the same result in translations... Sometime templates works, and suddenly, he doesn't work anymore.

Expected behavior:
Render my mail template with this kind of operators.

Video/Screenshot link (optional):
None

**Comment by pedrobaeza** [comment]
This is using Mako syntax:

https://docs.makotemplates.org/en/latest/syntax.html

For sure you will have some hidden characters editing this in HTML. Use code editor directly for that in debug mode.

Any way, this is not an Odoo fault, but something you have to take into account when editing via UI. Closing this with the mentioned advises.

**Comment by Yenthe666** [comment]
Yep, agree with Pedro. They're a pain to build sometimes though.

**Comment by pedrobaeza** [comment]
Yes, but use it with code editor, not directly in the HTML editor.
