### ISSUE TITLE
POS Order 'Return Products' duplicates stock journal entries

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#3082]
Impacted versions:
8.0 (haven't checked other versions)

Steps to reproduce:
1. Create a POS Order (thru POS interface)
2. Open the POS Order (Point of Sale > Daily Operations > Orders), and press 'Return Products', then 'Payment'

Current behavior:
Journal entries (stock journal) with exactly the same content are generated for the return order.

Expected behavior:
Only one journal entry should be generated.

**Comment by janicengyy** [comment]
The above behavior is only observed in our client's environment. We tried to reproduce in other testing environment with similar setting, everything seems normal and no duplicate entries was found. Still cannot identify which part of the setting brings the difference.

**Comment by mart-e** [comment]
@janicengyy maybe it's a bug fixed recently. Have you tried updating your code ?
I am closing this as can not be reproduced in standard but if you have more info on how to reproduce, we can reopen.
