### ISSUE TITLE
Wkhtmltopdf failed (error code: -8)

### ISSUE THREAD

**Issue by maulikbarad8** [odoo/odoo#30831]
Impacted versions: 12.0

Current behavior: Not printing. Wkhtmltopdf failed (error code: -8). Message: b''

Expected behavior:Show printing layout.

**Comment by maulikbarad8** [comment]
Wkhtmltopdf failed (error code: -8). Message: b''

**Comment by astirpe** [comment]
I think you are facing this issue: https://github.com/odoo/odoo/issues/27487

**Comment by maulikbarad8** [comment]
I found the solution.
When we start odoo server, it shows in log: 

> odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf


### You must check if "wkhtmltopdf" exists there.

I copied in /usr/bin and it worked for me.
