### ISSUE TITLE
[11.0] There is no "Done" state for both Purchase Orders and Sales Orders

### ISSUE THREAD

**Issue by svenv** [odoo/odoo#30856]
**Impacted versions:**

11.0 Community

**Steps to reproduce:** 

1. Create and confirm Purchase Order
2. Receive products
3. Create and validate Vendor Bill
4. Register payment

**Current behavior:**

- The progress bar of Purchase Orders does not have "Done" state. It only has "RFQ", "To Approve" and "Purchase Order". See image: https://prnt.sc/mha8gs
- When a PO has been received and the vendor bill has been paid for, the status remains "Purchase Order".

**Expected behavior:**

According to what I've read on the community forums, a PO should go to "Done" state when a PO has been received and the vendor bill has been paid for.

**Video/Screenshot link (optional):**
https://prnt.sc/mha8gs

**Comment by pedrobaeza** [comment]
Not seeing in the statusbar the state doesn't mean that it doesn't exist, as the UI can hide several statuses.

That state is got when you click on "Lock" button.

Closing as no real issue.

**Comment by svenv** [comment]
Hi Pedro,

Clicking the "Lock" button changes the state to "Locked", but not "Done"... There is simply no "Done" state...?

**Comment by pedrobaeza** [comment]
It was renamed in UI, but it's done state. Documentation can be improved for updating the nomenclature, but this doesn't belong here.

**Comment by svenv** [comment]
@pedrobaeza 

- So a purchase order doesn't automatically go into done (locked) state anymore?
- And a purchase order can be marked done (locked) even when no receiving has been done, nor payment has been made?

Why was this feature removed?

**Comment by pedrobaeza** [comment]
Locking orders is for avoiding editing orders once confirmed, but has nothing to do with invoicing and payments.

**Comment by svenv** [comment]
So that means it has nothing to do with the "Done" status as described here by Fabien...

https://www.odoo.com/forum/help-1/question/when-does-purchase-orders-get-the-status-done-363

So where did it go?
