### ISSUE TITLE
[12ce] multiwebsite single domain gelocation redirect

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#30859]
Impacted versions:
12ce

Steps to reproduce:
Create 2 websites with same domain
Specify regions for gelocation

Current behavior:
Always displays primary website from any geoip

Expected behavior:
Display alternative websites that match geoip region

Video/Screenshot link (optional):

**Comment by Moto017** [comment]
To expand on this, I have:

1. /usr/share/GeoIP/GeoIP.dat installed and directed in the odoo-server.conf as geoip_database = /usr/share/GeoIP/GeoIP.dat and this does not throw any errors.
2. I noticed Geoip2 in http resolver and changed to GeoLite2-City.mmdb which throws AttributeError: 'list' object has no attribute 'get' - - -


3. 
4.

**Comment by Moto017** [comment]
To expand on this, I have:

/usr/share/GeoIP/GeoIP.dat installed and directed in the odoo-server.conf as geoip_database = /usr/share/GeoIP/GeoIP.dat and this does not throw any errors.

I noticed Geoip2 in http resolver and changed to GeoLite2-City.mmdb from maxmind which throws error
```
"/odoo12/odoo12-server/odoo/http.py", line 619, in __init__
    self.params = dict(self.jsonrequest.get("params", {}))
AttributeError: 'list' object has no attribute 'get' - - -
```

**Comment by Moto017** [comment]
Reproduced on runbot.  So I am back to an issue with odoo.

**Comment by rdeodoo** [comment]
Hello,
What domain did you set on your websites?
Currently, the URL scheme should be removed when entering your domain (this will be fixed any time soon to allow scheme to be in domain without causing wrong behavior).
Eg, you should only write `github.com` and not `https://github.com`.
That might be your issue, let me know if this help you.

**Comment by seb-odoo** [comment]
Related to #30000 (especially 2nd commit)

**Comment by Moto017** [comment]
rdeodoo,
Thank  you for your comment.  I tested this by changing the domain to
- leaving blank
- setting IP
- setting to subdomain behind Nginx as well as confirmed geoip config is working.
Neither produces the result.  Always directs to fallback website

**Comment by Moto017** [comment]
@seb-odoo I tested your changes and works as expected.   Thank you!

**Comment by seb-odoo** [comment]
I'm closing this as the related PR #30000 has been merged already.
