### ISSUE TITLE
[12.0] project_timesheet_holidays: editing of the derived timesheet entry should be restricted

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#30850]
It's possible to modify timesheet entries created by `project_timesheet_holidays`, e.g. change duration, date, etc. what would lead to data inconsistency

**Comment by alexey-pelykh** [comment]
Addressed by https://github.com/OCA/hr-timesheet/pull/175 though should be eventually ported into `master`

**Comment by alexey-pelykh** [comment]
relates to #30854

**Comment by alexey-pelykh** [comment]
Addressed in https://github.com/odoo/odoo/pull/30863

**Comment by Yenthe666** [comment]
Hi,

I'm closing your issue as you've made a PR. Please don't make both an issue and a PR if you're planning to make a PR, it only adds double workload.
Thanks for the PR 😉

**Comment by alexey-pelykh** [comment]
Well, it was not planned, plans appear 15 minutes after :) Yet I got your message 😉

**Comment by Yenthe666** [comment]
Haha I see, those things tend to happen to me too. Happy that you made a PR 🙏
