### ISSUE TITLE
Credit card swipe raises a error - "Decryption service is unavailable - Failed to decrypt"

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#30862]
Impacted versions:
Odoo V11 Community

Steps to reproduce:
1.) Configure mercury credentials (username and password)
2.) Add products to pos order, make payment, select credit card payment. 
3.) Message will be displayed "Waiting for a card swipe" Swipe a card.
4.) Error will be generated.
5.) Card reader is recommended by Odoo

Current behavior:
On a card swipe an error is raised, "Decryption service is unavailable - Failed to decrypt".

Expected behavior:
Credit card payment must be processed sucessfully.

Video/Screenshot link (optional):

**Comment by jorenvo** [comment]
Where did you purchase your card reader? It has to be purchased through Worldpay (formerly Vantiv). The device needs to have Worldpay-specific encryption keys embedded in it to work with their services.

**Comment by jorenvo** [comment]
Closing due to lack of reply. If still necessary, you can reply and we can reopen.
