### ISSUE TITLE
[BUG] Error when open private address on Employee when base_address_city is installed

### ISSUE THREAD

**Issue by vijoin** [odoo/odoo#30901]
## Impacted versions:
12.0
## Steps to reproduce:
* Install modules `hr` and `base_address_city`
* Search for Mitchel Admin employee form
* Tab Private Information > field Private Address (click to open)
## Current behavior:
It gives an error like this
![captura de pantalla de 2019-02-06 18-02-40](https://user-images.githubusercontent.com/11879380/52376817-753dd600-2a39-11e9-9fb2-8e83eebfcf30.png)

## Expected behavior:
It is expected to open this form:
**base.res_partner_view_form_private**
![captura de pantalla de 2019-02-06 18-04-08](https://user-images.githubusercontent.com/11879380/52376890-af0edc80-2a39-11e9-8150-7f13fdf5b9bf.png)

## Analysis
In this line: https://github.com/odoo/odoo/blob/12.0/addons/base_address_city/models/res_partner.py#L77 there is a replacement in the domain and it needs a `parent_id` field, but it doesn't exist in the form `base.res_partner_view_form_private`: https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/views/res_partner_views.xml#L402

I think the solution is just add a `<field name="parent_id"/>` somewhere in that form

## Screencast
[Video1](https://drive.google.com/file/d/1NaGpsSpqnQTKkHEgEzcbnFq1t2BpdlGd/view?usp=sharing)

**Comment by Yenthe666** [comment]
Hi,

This has been fixed in https://github.com/odoo/odoo/commit/d928580d230ec2ea42e1372941b43cf9a9a69574!
