### ISSUE TITLE
kanban_label_selection deprecated for label_selection still used / not working causing console errors in exactly 18 views

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#30904]
Impacted versions: 12.0 - I saw an isolated 11.0 report but not sure if same issue #25928 - nonetheless look at that because I think the referenced PR is wrong as it just deleted the widget..

Steps to reproduce:
Switch to a mobile view for any of the following - with dev tools enabled is better
![image](https://user-images.githubusercontent.com/5093264/52396243-100be280-2b16-11e9-8cc9-17ccfd2cf31d.png)

Current behavior:
No nice state coloring as the widget is now just `label_selection`
widget not found error in console

Expected behavior:
Nice state coloring

Video/Screenshot link (optional):

**Comment by mge-odoo** [comment]
Thanks for reporting the issue. It has been fixed by the PR https://github.com/odoo/odoo/pull/31643
