### ISSUE TITLE
Rescue orders created in odoo Pos. version is 10

### ISSUE THREAD

**Issue by tinasanthosh** [odoo/odoo#30902]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by tinasanthosh** [comment]
When we closed the pos for the day, some orders were not posted. They were created as Rescue for pos_session_id. Why did this happen? Can someone throw some light on this? And how to sort this out.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
