### ISSUE TITLE
Wishlist - Cut Robodoo in half

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#30916]
Impacted versions: NA

Steps to reproduce: 
Watch odoo repo

Current behavior:
Screeds of messages in feeds etc of essentially useless messages saying that something has been labeled.
Buried in there some useful ones, like when things are actually merged.

It'd be nice if one robot could do the admin, and another one do the merging (Or things Odoo SA cares about, things Odoo Developers care about kind of split). As it stands I've just blocked the user because its too much noise, but it would be nice. But even then you still get all these r+ etc etc.

**Comment by sswapnesh** [comment]
Specially when @robodoo says _Merged, thanks!_ after merging PR.

**Comment by Yenthe666** [comment]
@sswapnesh that one actually feels like you atleast get a thank you from somebody at Odoo though? The enormous amounts of labelling and retries bothers me a lot more 😆

**Comment by sswapnesh** [comment]
Hahaha, I got it😉. However, I don't think you likes Robodoo thanking you everyday multiple times.

**Comment by Yenthe666** [comment]
If that means my PR's get merged I'm fine with it. If that is what it takes 😄

**Comment by pedrobaeza** [comment]
I think the bot is set since a long and the flow doesn't seem to change, so I'm closing this issue as "won't fix".
