### ISSUE TITLE
[11.0] Performance problem at reconciliation widget, reconcile bank statements

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#30934]
Impacted versions:
11.0
Steps to reproduce:
- Configure tax cash basis feature
- Create an invoice with almost 800 lines, all lines with tax and validate it.
- Create a Payment from a bank statement
- Try to reconcile

Current behavior:
The reconciliation widget got stock, and never finish,
because the for section: https://github.com/odoo/odoo/blob/11.0/addons/account/models/account_move.py#L1723

I made a profiler of the work case shown at the video and the results were:
https://drive.google.com/file/d/1HuQ1RmZRWN7A8uUBhC4GgzXC7Y87sJdN/view?usp=sharing

Where the highest results comes from 
create function
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_move.py#L1235

process_reconciliations
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_bank_statement.py#L808
_get_matched_percentage 
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_move.py#L1433
_compute_cash_basis
https://github.com/odoo/odoo/blob/9553240adc4a29d7b61d63708a53cbb612c0e123/addons/account/models/account_move.py#L372

Expected behavior:
Improve the performance of the reconciliation widget.
Video/Screenshot link (optional):

https://youtu.be/qVOh6aXLgUo

Replicated at http://443957-11-0-883838.runbot15.odoo.com/

OPW 1938216

**Comment by sswapnesh** [comment]
Video URL seems wrong

**Comment by hugho-ad** [comment]
Yeah, I've already fix it, thks!

**Comment by moylop260** [comment]
@hugho-ad 
Could you test the following patch?
I think it is related:

**Comment by moylop260** [comment]
@hugho-ad 
Could you test the following patch?
I think it is related:
https://github.com/odoo/odoo/pull/30979

**Comment by moylop260** [comment]
@hugho-ad 
I have created a big fix from the following PR:
 - https://github.com/odoo/odoo/pull/31014

Could you tested it, please?

Another medium fixes are:
 - https://github.com/odoo/odoo/pull/31007
 - https://github.com/odoo/odoo/pull/30979

**Comment by moylop260** [comment]
Closing by https://github.com/odoo/odoo/pull/31014
@KangOl FYI it is reproducible for 12.0 too
A fowardport is appreciate here
thanks in advance
