### ISSUE TITLE
[8.0] test_01_xmlrpc_login test froze if server has multiple workers

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#3094]
Run openerp with --test-enable and multiples workers. Test never finish and makes a timeout

**Comment by Yenthe666** [comment]
Hi @nbessi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
