### ISSUE TITLE
[12.0]Error with sass library

### ISSUE THREAD

**Issue by Ericklomeli** [odoo/odoo#30966]
Impacted versions: 12

Steps to reproduce: while Installing Enterprise Edition

I already install libsass using pip3 and sudo install python3-libsass and check every Issue in here! and the requiments.txtis successfully installed too.

Video/Screenshot link (optional):

![captura de pantalla de 2019-02-08 11-52-04](https://user-images.githubusercontent.com/46828719/52496298-97019f00-2b98-11e9-9461-e4030a85aaea.png)

![captura de pantalla de 2019-02-08 11-58-48](https://user-images.githubusercontent.com/46828719/52496492-08d9e880-2b99-11e9-8df4-25ec7f7420a1.png)

![captura de pantalla de 2019-02-08 12-00-00](https://user-images.githubusercontent.com/46828719/52496522-26a74d80-2b99-11e9-861a-a322fe436b87.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

You can share your problem also on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups),.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
