### ISSUE TITLE
[Loop] version_info, raised database connection.

### ISSUE THREAD

**Issue by JDSalcedo** [odoo/odoo#30964]
I got a database manager in AWS with a connection pool of 65 max, there are 7 databases installed and  around 15 concurrents users, based in AWS CloudWatch, one of this databases with 3 users, generated more than 40 connections to the database with no reason. Looking into odoo logs I noticed one line 'odoo.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1397 sec...' after this a lot of 'werkzeug: 201.240.60.64 - - [08/Feb/2019 14:29:42] "POST /web/webclient/version_info HTTP/1.1" 200 -' lines, I just stop and start the server for this client and connectios goes down to normal values, 45 for all my databases. This is not the first time I got this behavior, that happened with other database at least two times.

Postgresql Service:
![image](https://user-images.githubusercontent.com/8197930/52491296-c7dfd500-2b94-11e9-8b9c-e8259fd2e272.png)

Impacted versions:
11.0

Steps to reproduce:
Unknown

Current behavior:
One single database with 3 concurrent user can produce more than 40 database connections.

Expected behavior:
I don't know if one database with 3 users can produce that number of connections I hope it's less.

Video/Screenshot link (optional):
Metrics:
![image](https://user-images.githubusercontent.com/8197930/52491209-949d4600-2b94-11e9-868e-feb46317733c.png)
Log:
![image](https://user-images.githubusercontent.com/8197930/52491559-653b0900-2b95-11e9-8cc0-7e466fc15996.png)
![image](https://user-images.githubusercontent.com/8197930/52491708-b945ed80-2b95-11e9-87e6-6a30153ee974.png)
after few lines:
![image](https://user-images.githubusercontent.com/8197930/52491772-d7abe900-2b95-11e9-8cd8-69269358cefd.png)

**Comment by pedrobaeza** [comment]
This can be provoked by several things, like a low value for memory limit that abort workers. Any way, I'm afraid unless you be more specific in something that leads to alleviate the situation or give a hint about the problem, I have to close this as a non valid issue.
