### ISSUE TITLE
8.0: false positive in purchase_requisition tests

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#3096]
In 8.0 at least, tests for purchase_requisition pass by accident.
- https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/test/purchase_requisition.yml#L24: `purchase_ids` is empty, so the assertions are never run
- https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/test/purchase_requisition.yml#L38 a requisition from the demo data is used, instead of the one that was not generated automatically
- https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/test/purchase_requisition.yml#L40 a PO state is written without using the workflow. The state is actually `cancel`
- https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/test/purchase_requisition.yml#L89 The `state` is not `done` here, but the assertion passes because the word `assert` is missing

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
