### ISSUE TITLE
Issue in finding "employee.race" model

### ISSUE THREAD

**Issue by chinu1994** [odoo/odoo#30976]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by chinu1994** [comment]
I am getting error while installing l10n_sg_hr_payroll module and also I can't get "employee.race" model in odoo addons used in : 
ParseError: "employee.race" while parsing /home/chinu/Documents/odoo%2010/source/OCB-10.0/addons/l10n_sg_hr_payroll/data/hr_emp_race.xml:5, near
<record id="hr_employee_race_chinese" model="employee.race">
            <field name="name">Chinese</field>
        </record>

**Comment by Yenthe666** [comment]
Hi,

There is no such model in the default Odoo so the issue you're reporting here is related to a third party app. 
Please try asking these kind of questions on the official help forum (https://www.odoo.com/nl_NL/forum/help-1) or at the developer that made the module.

Regards,
Yenthe
