### ISSUE TITLE
[11.0] E Ce, update to AVCO does not work if the product previously had a manual costing method.

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#30971]
Impacted versions:
11 Enterprise.
11 community Edition
Steps to reproduce:

Create a product with the manual costing method. Configure its accounts,  Selle and buy some products. 
Pick the same product, change the costing method to AVCO, change te accounts of these products and configure it as the AVCO demands.  Then buy some products at different cost. The cost of the product doesn't update, ant the product remains in the manual costing method.

The issue comes from the added complexity and growth in a company. As complexitygrow in a process of sales and warehouse a decissión has to be taken to change to the AVCO method certain products if not all.  The solution is to create a new product and to scrap the previous one. However, it is difficult in a company that has a lot of products and involves a lot of accounting moves. 
Also if you do the previous steps, there is no warning that the products remain in the  manual costing method. As the AVCO is not calculated and there is no warning. This could lead to accounting error, and loses for the company.

¿What do I expect?

There should exist the possibility to change the costing method in a category or a product since I think that a lot of companies have the same use case, as the company grows.
Or maybe a restriction to change the costing method, in a product or category, and a way to track it.

**Comment by hydrosIII** [comment]
In odoo 12 works, however as far as I know in odoo 11 is still reproducible. Since i have a email from odoo explaining that this feature is not backportable. However I am not using odoo 11 anymore and I have moved to odoo 12. In odoo 12 the issue does not longer exists.

**Comment by pedrobaeza** [comment]
Thanks for the followup. Then we can close this with the conclusion that it has been solved, but not in this version.
