### ISSUE TITLE
Invoice - translation to french error

### ISSUE THREAD

**Issue by AntPhil** [odoo/odoo#30981]
Impacted versions: 12.0

Steps to reproduce: create invoice and print or preview in pdf 

Current behavior: Column UNIT PRICE stays in english and no translated to "Prix Unitaire"

Expected behavior: UNIT PRICE no translated in french

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because the translation is not done yet. You can do it following https://github.com/odoo/odoo/wiki/Translations

**Comment by AntPhil** [comment]
Thks but this word seems translated in Transifex for invoice. Regards

**Comment by Yenthe666** [comment]
@AntPhil it can be that the translation is not yet in the Github sources here (happens once a week) or that you haven't updated your terms locally yet.

**Comment by AntPhil** [comment]
OK I apologize! Thks :)

Le dim. 10 févr. 2019 à 18:21, Yenthe V.G <notifications@github.com> a
écrit :
