### ISSUE TITLE
[11.0] Total amount of Sales Order is not updated by the onchange api

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#30989]
**Impacted versions:**
11.0

**Steps to reproduce:**
1. Open a sales order.
2. Edit the Unit Price of any sales order line.

**Current behavior:**
The "Margin" is updated while the "Untaxed Amount", "Taxes" and "Total" are not updated immediately until the "Save" button of the sales order is pressed.

**Expected behavior:**
The "Margin", "Untaxed Amount", "Taxes" and "Total" are updated immediately as long as the "Subtotal" of any order line is updated.

**Comment by TimLai125** [comment]
The behavior is not reproducible in Runbot but I would like to know if anyone here encountered similar issue with me.

**Comment by pedrobaeza** [comment]
Sorry, but if this is not reproducible in runbot, then it's not something of Odoo code nor ORM, but custom code that avoids the proper recomputation of fields (maybe a compute overwrite without the depends, or changes in that computed fields).

Closing as no issue with standard.
