### ISSUE TITLE
[12.0] problem during an internal transfer 

### ISSUE THREAD

**Issue by abdellatifnait** [odoo/odoo#30994]
When changing the destination location after entering lines it does not update the destination location of the lines,the problem in method create stock picking:
the method must be like below:
    @api.model
    def create(self, vals):
        # TDE FIXME: clean that brol
        defaults = self.default_get(['name', 'picking_type_id'])
        if vals.get('name', '/') == '/' and defaults.get('name', '/') == '/' and vals.get('picking_type_id',
                                                                                          defaults.get(
                                                                                                  'picking_type_id')):
            vals['name'] = self.env['stock.picking.type'].browse(
                vals.get('picking_type_id', defaults.get('picking_type_id'))).sequence_id.next_by_id()

        # TDE FIXME: what ?
        # As the on_change in one2many list is WIP, we will overwrite the locations on the stock moves here
        # As it is a create the format will be a list of (0, 0, dict)
        if (vals.get('move_lines') or vals.get('move_ids_without_package')) and vals.get('location_id') and vals.get(
                'location_dest_id'):
            for move in (vals.get('move_lines') or vals.get('move_ids_without_package')):
                if len(move) == 3 and move[0] == 0:
                    move[2]['location_id'] = vals['location_id']
                    move[2]['location_dest_id'] = vals['location_dest_id']
        res = super(Picking, self).create(vals)
        res._autoconfirm_picking()
        return res

**Comment by pedrobaeza** [comment]
Can you please do a PR with the fix if you have it clear?

**Comment by sle-odoo** [comment]
This should be fixed by 2899a9d1edaafce9b48f808d08c0b61202dcaa3e
