### ISSUE TITLE
Double click on a confirm wizard button triggers action twice

### ISSUE THREAD

**Issue by fractalf** [odoo/odoo#30996]
This was done on Odoo Enterprise v12

```
<button
    name="action_foo"
    string="Foo"
    type="object"
    confirm="Are you sure?"
/>
```

This will pop up a confirmation box. If the user is "old school" he/she might double click the ok button which triggers _action_foo_ twice. This could result in unexpected behaviour as both functions are executed before any record change takes place (so it can't be fixed directly in the action)

A fix could be to store a button state disabling the second click. I tried to extend this code below to fix this temporary, but must admit I reached the limit of my Odoo skills.

https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/views/form/form_controller.js#L448-L485

**Comment by pedrobaeza** [comment]
Is this happening also without `confirm` attribute?

**Comment by fractalf** [comment]
No sure I follow you. Without the `confirm` attr the popup box won't even show, so then there really isn't an issue.

**Comment by githubtaotao** [comment]
Try this code.

odoo.define("confirm_click_once", function (require) {
    "use strict";

    var Dialog = require('web.Dialog');
    var dom = require('web.dom');

    var ConfirmClickOnce = Dialog.include({
        set_buttons: function (buttons) {
            var self = this;
            this.$footer.empty();
            _.each(buttons, function (buttonData) {
                var $button = dom.renderButton({
                    attrs: {
                        class: buttonData.classes || (buttons.length > 1 ? 'btn-default' : 'btn-primary'),
                        disabled: buttonData.disabled,
                    },
                    icon: buttonData.icon,
                    text: buttonData.text,
                });
                $button.on('click', function (e) {
                    var def;
                    if (buttonData.click) {
                        def = buttonData.click.call(self, e);
                        $button.attr('disabled', "true");
                    }
                    if (buttonData.close) {
                        $.when(def).always(self.close.bind(self));
                    }
                });
                self.$footer.append($button);
            });
        },

    });

});

**Comment by ShavaShav** [comment]
> 
> 
> Try this code.
> 
> odoo.define("confirm_click_once", function (require) {
> "use strict";
> 
> ```
> var Dialog = require('web.Dialog');
> var dom = require('web.dom');
> 
> var ConfirmClickOnce = Dialog.include({
>     set_buttons: function (buttons) {
>         var self = this;
>         this.$footer.empty();
>         _.each(buttons, function (buttonData) {
>             var $button = dom.renderButton({
>                 attrs: {
>                     class: buttonData.classes || (buttons.length > 1 ? 'btn-default' : 'btn-primary'),
>                     disabled: buttonData.disabled,
>                 },
>                 icon: buttonData.icon,
>                 text: buttonData.text,
>             });
>             $button.on('click', function (e) {
>                 var def;
>                 if (buttonData.click) {
>                     def = buttonData.click.call(self, e);
>                     $button.attr('disabled', "true");
>                 }
>                 if (buttonData.close) {
>                     $.when(def).always(self.close.bind(self));
>                 }
>             });
>             self.$footer.append($button);
>         });
>     },
> 
> });
> ```
> 
> });

Just a warning to others: This solution causes *all* buttons across Odoo to become disabled.

**Comment by donimuzur** [comment]
> No sure I follow you. Without the `confirm` attr the popup box won't even show, so then there really isn't an issue.

is this issue already solved ?

**Comment by fractalf** [comment]
Problem is solved, I don't know if this is fixed in core Odoo code... closing..
