### ISSUE TITLE
[12.0] parent_path is not computed for pre-existing entries when model becomes _parent_store = True

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#31010]
To workaround such a situation a
```
def post_init_hook(cr, registry):
    env = api.Environment(cr, SUPERUSER_ID, {})

    env['MODEL']._parent_store_compute()
```
has to be in place. This behaviour is not described anywhere in the docs, at least for v12.

**Comment by Yenthe666** [comment]
@alexey-pelykh why don't you make a direct PR to add it to the docs?

**Comment by alexey-pelykh** [comment]
@Yenthe666 I'd be happy to do that as soon as someone could verify/backup my statement, I'm not that confident in my understanding of Odoo internals

**Comment by alexey-pelykh** [comment]
On top of that, `_parent_store_compute` seems like a "private" method, not intended for direct call, thus I believe this should be addressed not only via docs

**Comment by Yenthe666** [comment]
@pedrobaeza I think you're the best person to confirm this 👍

**Comment by pedrobaeza** [comment]
I think this can be considered a bug, not something to document, as by inheritance you can add this to any existing model, and the need of forcing that computation seems odd and not inline with the rest of update process.

@rco-odoo what do you think?

**Comment by alexey-pelykh** [comment]
```
compute='_parent_store_compute'

**Comment by pedrobaeza** [comment]
Well, that's an ugly hack and we don't no if there can be side effects.

**Comment by Yenthe666** [comment]
sounds like an easy way to trigger yourself into recursion if you don't watch out what you're doing too hehe.

**Comment by alexey-pelykh** [comment]
Then it's a bug in core, not docs :)

**Comment by pedrobaeza** [comment]
Thinking deeper, I know the first side effect: it computes all records each time, no matter the invalidation set. And a second one: if you don't put `depends`, you'll get the contrary effect, not being properly updated.

**Comment by ccandito** [comment]
Dear All,
do you have any news about it?
thanks
claudio
