### ISSUE TITLE
Website_sale shipping address

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#31024]
Impacted versions:10.0 11.0 12.0

Steps to reproduce: When creating more than one quotation from the e-commerce with different shipping addresses, it combines the last quotation with new one and overrides the old shipping address.

Current behavior: Combines all quotations regardless of their shipping address.

Expected behavior: It should create a new quotation.
In model: website_sale, def: sale_get_order, line: 181
sale_order_id = last_order.state == 'draft' and last_order.pricelist_id in available_pricelists and last_order.id

Fix:
sale_order_id = last_order.state == 'draft' and last_order.pricelist_id in available_pricelists and last_order.partner_shipping_id.id == partner.address_get(['delivery']) and last_order.id

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
Hello,

Could you please provide a way to reproduce it? Eg a small step to reproduce.

> When creating more than one quotation from the e-commerce with different shipping addresses
sale_order_id = last_order.state == 'draft'

As far as I know there is no way to create multiple **draft** quotation from the e-commerce?

Thank you

**Comment by rosenvladimirov** [comment]
I fix this problem with module [sale_only_company](https://github.com/rosenvladimirov/sale-workflow/tree/11.0/sale_only_company) This module switch e-commerce to work in B2B
