### ISSUE TITLE
Failure to execute inline ... violates CSP uploading .jpeg or .tiff

### ISSUE THREAD

**Issue by newnativeabq** [odoo/odoo#31027]
Impacted versions:
CE 12
Steps to reproduce:
Login through Chrome browser with no-script suite lite
Open new task under projects.  Log note.  Type text into note .  Click attachment icon. Attempt to upload .jpeg or .tiff.
**Issue resolved by trusting Odoo server IP in No-Script Suite Lite
Current behavior:
Page displays uploading attachments.  If attempt to log, uploading error.  On page reload, white screen.  On server reset, no web access allowed.
Expected behavior:
Log note.  Page display.  Alert to user that script-blocker will affect loading of the page.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this is not Odoo task to be aware of any possible addon you have on the browser, as there are tons of possible ad blockers, each one with their mechanisms. If you use it in your organization, include in your processes that whitelisting.
