### ISSUE TITLE
auth_signup: invitation signup template not respecting list_db=False

### ISSUE THREAD

**Issue by zachwaite** [odoo/odoo#31038]
Impacted versions: 11.0

Steps to reproduce:
1. Set list_db=False in config file
2. Start Odoo and install auth_signup
3. Invite a user to signup
4. Navigate to the generated signup link

Current behavior:
'Manage Databases' link is visible

Expected behavior:
'Manage Databases' link not visible

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/6884125/52652219-b449ac80-2ebb-11e9-8873-e523c6a21fcd.png)

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
