### ISSUE TITLE
German translation is wrong and causes the program to break (expense payment)

### ISSUE THREAD

**Issue by ruifranco** [odoo/odoo#31036]
Impacted versions: 12

Steps to reproduce: Set language to german and pay an expense

Current behavior: The program breaks because the translation does not have enough string placers

Expected behavior: There should be five string placers

This is the current translation:

#. module: hr_expense
#: code:addons/hr_expense/wizard/hr_expense_sheet_register_payment.py:104
#, python-format
msgid ""
"A payment of %s %s with the reference <a href='/mail/view?%s'>%s</a> related"
" to your expense %s has been made."
msgstr "<a href=\"/mail/view?%s\"/>"

**Comment by pedrobaeza** [comment]
Please fix the translation through Transifex: https://github.com/odoo/odoo/wiki/Translations
