### ISSUE TITLE
Manufacturing Order with Routing Lot/Serial based BOM components cause duplicate inventory moves...

### ISSUE THREAD

**Issue by jmnapoli** [odoo/odoo#31031]
Impacted versions: 11.0 CE

Steps to reproduce:  I have created a simple Manufacturing order using a BOM that contains a single component.  That component uses lot/serial tracking.  

Our manufacturing facility is set up with various processing stations where this component will pass through the repair process.  I have set the work order to consume the BOM component on the first work order process.  

When I click done on the work order I notice the system has created two identical inventory moves for the serialized product into production.  I have spent several days trying to understand how this happens.  

If I remove the route from the BOM it all works fine.  I am a newbie to routing tied to an MO so not quite sure if its a simple thing I missed.  

Current behavior:

Expected behavior:  The MO would create multiple WOs.  On the WO you would link the serial consumed to the new serial created and only 1 unit would be removed from stock.  Currently it tries to move 2 units.

Video/Screenshot link (optional):    https://www.dropbox.com/s/lcdc9agzpx5fh0q/Capture.JPG?dl=0

**Comment by sle-odoo** [comment]
They ere temporary move lines (not reserved). They're gone in v13.0.
