### ISSUE TITLE
Incorrect / Incomplete Documentation on Server Actions

### ISSUE THREAD

**Issue by probabble** [odoo/odoo#31044]
Impacted versions: 12 (and more?)

Steps to reproduce: Read the examples of server actions and attempt to create your own action. 
https://www.odoo.com/documentation/12.0/reference/actions.html#server-actions-ir-actions-server

Current behavior:
No documentation of `binding_model_id` 
Unclear/incorrect documentation of variables accessible in a `code` block.

Expected behavior:
The documentation should cover:

- All fields available to the XML declaration of a server action, and their options
- All variables that are available to the execution context of `code` blocks
- Any restrictions on code execution from `code` blocks (for example, I discovered I can't use `print`)

**Comment by luisg123v** [comment]
I agree on the point that all available variables could be documented e.g. `b64encode` and `b64decode`.

**Comment by Yenthe666** [comment]
Let us be honest that the whole documentation is very limited honestly. In general there is barely anything useful in it.

**Comment by probabble** [comment]
The first step toward recovery is admitting you have a problem

**Comment by Yenthe666** [comment]
Yep! Don't be shy to make some PR's for extra documentation either, PR's are generally handled faster.

**Comment by enricostano** [comment]
Use case with `state: object_create` would also be helpful. You can generally find examples only with `state: code`.

**Comment by sehrishnaz** [comment]
did you try this: http://learnopenerp.blogspot.com/2020/01/odoo-server-action.html

**Comment by pedrobaeza** [comment]
@Feyensv can we close this then?
