### ISSUE TITLE
[ Odoo 12 - CE ] Quotation preview cumulated values of a single line

### ISSUE THREAD

**Issue by taOsemc** [odoo/odoo#31058]
Impacted versions: 12

Steps to reproduce:

A bug I can't fix.

1) Create a product with a description

2) Create any quote with this article and give it a value.

3) Put this article under a section

4) Preview this quote.

5) The Section's Subtotal is not well calculated in the customer preview

Video/Screenshot link (optional):

**Customer portal preview (with sample datas):**
![2019-02-13 10 38 06](https://user-images.githubusercontent.com/32459602/52703701-41096e80-2f7f-11e9-8a55-2fd7c18d5211.png)

You can see in this screenshot only one line has a value of 2200€ in my quote, however it seems that it is counted twice and a line 4400€ appears.

**Backend**
![2019-02-13 11 08 00](https://user-images.githubusercontent.com/32459602/52703907-b70dd580-2f7f-11e9-89a7-7c27f6b3cd0e.png)

**Comment by Boudmir-Ibrahim** [comment]
Hi @taOsemc, 

I just tested this in V12 and works perfectly for me and your issue is not reproducible.
Note that I have respected all the steps you mentioned.
![v12](https://user-images.githubusercontent.com/43453694/52707145-f687f200-2f7e-11e9-9ffb-0910aaf9fad2.png)

Please check if any custom code/module is added to the online quotattion.

**Comment by taOsemc** [comment]
Hi @Boudmir-Ibrahim thank you for testing. Could yo utry to add 3 products instead of one  don't forget to add a description for customer.

**Comment by Boudmir-Ibrahim** [comment]
Oh i see ! 
Actually _Adding_ the **sections** generates this issue. 
![gitub](https://user-images.githubusercontent.com/43453694/52711698-62bc2300-2f8a-11e9-9350-eeec90bfc0f9.png)

**Comment by taOsemc** [comment]
Ahh! I'm happy that it's not due to my installation ! :)

**Comment by taOsemc** [comment]
I've also notcied that it's somehow breaking the css of the page.

**Comment by taOsemc** [comment]
Bug is confirmed @pedrobaeza

**Comment by pedrobaeza** [comment]
Labelled, but it's not in my hands to solve it.
