### ISSUE TITLE
journal_id on account_move_line database validation

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#31077]
Impacted versions: v11

Steps to reproduce: 
execute "ALTER TABLE account_move_line ALTER COLUMN journal_id SET NOT NULL;" then create a new invoice and post this.

Current behavior:
Odoo server error: [object with reference: journal_id - journal.id]

Expected behavior:
Invoice should be posted to accounting

Video/Screenshot link (optional):

**Comment by ahetland** [comment]
Data validation for journal_id should take place at database level as this is a crucial field for data integrity.

**Comment by pedrobaeza** [comment]
Why are you doing such things? If you are using Odoo, it's for using the ORM layer. If you try to bypass it at DB level, then you are tricking the system.

Closing as no valid issue.
