### ISSUE TITLE
Email Attachment field isn't showing up until refreshing the page in Chrome or Firefox.

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3108]
When I go into the email templates via settings -> technical -> email -> templates, the template widget is not appearing in chrome and firefox until the page is reloaded. I tried upgrading from the release version of 8.0 to latest and the problem persists.

![screenshot 2014-10-16 15 49 41](https://cloud.githubusercontent.com/assets/48965/4659723/4ac2c15e-5510-11e4-8b8b-8cbd91d9305a.png)
![screenshot 2014-10-16 16 41 26](https://cloud.githubusercontent.com/assets/48965/4659724/4ac83828-5510-11e4-9fff-74a7142160fd.png)

I also have module that inherits `email.template` with the exact same problem. It's form is much simpler:

```xml
<record model="ir.ui.view" id="email_template_form">
      <field name="name">sale.order_email_template.form</field>
      <field name="model">sale.order_email.template</field>
      <field name="arch" type="xml">
        <form string="Templates">
          <sheet>
            <div class="oe_title">
              <label for="name" class="oe_edit_only"/><h1><field name="name" required="1"/></h1>
              <group>
                <field name="model_id" required="1" />
                <field name="model" invisible="1" />
              </group>
            </div>
            <label for="subject"/>
            <h2 style="display: inline-block;"><field name="subject" placeholder="Subject (placeholders may be used here)"/></h2>
            <field name="body_html"/>
            <field name="attachment_ids" widget="many2many_binary"/>
          </sheet>
        </form>
      </field>
    </record>
```

**Comment by Yenthe666** [comment]
Hi @kitsunde,

This issue is no longer present in the latest codebase from Odoo.
If you still face this issue please update your Odoo codebase and it will be resolved!

Regards,
Yenthe
