### ISSUE TITLE
[doc] building module advanced view give error

### ISSUE THREAD

**Issue by as3mbus** [odoo/odoo#31088]
Impacted versions:
12.0
Steps to reproduce:
following the docs to create custom module
Current behavior:
on advanced view step (calendar view) model code for _get_end_date get the following error : 
```TypeError: 2019-02-14 02:23:59 (field openacademy.session.end_date) must be string or date, not datetime. - - -  ```
Expected behavior:
redefining 
`r.en_date = fields.Date.from_string(start+duration)`
work but i don't know if it's the proper way to do it.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
I'll make a quick doc fix for that today.

**Comment by mreficent** [comment]
can be closed

**Comment by pedrobaeza** [comment]
Indeed.

**Comment by Yenthe666** [comment]
Yep, fixed in https://github.com/odoo/odoo/commit/cc0e65487602ef6282ca68f47eb95369c6c0870f
