### ISSUE TITLE
NO DOCKER VERSION - Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmp9gvmk_j_/dump.sql', 'PRYXIDANET') error 1

### ISSUE THREAD

**Issue by nikolaiortiz** [odoo/odoo#31085]
Impacted versions: 
odoo 12.0 (NO DOCKER)
pg_dump: server version: 10.6; pg_dump version: 9.2.24
pg_dump: aborting because of server version mismatch
CENTOS 7.

Steps to reproduce:
Fresh install
git clone https://www.github.com/odoo/odoo --depth 1 --branch 12.0 /opt/odoo12/odoo
Then create a new DB, then try to Backup DB.

Current behavior:
When trying to backup DB gives error:
Database backup error: Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--file=/tmp/tmp9gvmk_j_/dump.sql', 'PRYXIDANET') error 1

Expected behavior:
Create a DB Backup.

**Comment by pedrobaeza** [comment]
pg_dump version is outdated. It should be at least the same of the server.

**Comment by nikolaiortiz** [comment]
For CENTOs 7:
`
ln -s /usr/pgsql-10/bin/pg_dump /usr/bin/pg_dump --force
`
Thanks a lot
