### ISSUE TITLE
DB restore only works with superuser role

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#31115]
**Impacted versions:**
all

**Steps to reproduce:**
Seen on postgres version 11, but should affect other versions, too. As long as `plpgsql` (or any other extension) is installed by default.

- `CREATE ROLE odoo WITH CREATEDB PASSWORD 'odoo';`
- Use that user for odoo to connect to the database cluster
- Backup through the odoo interface (sql dump);
- Ensure `cat db.dump | grep plpgsql` containes `COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';`, report back if not.
- Try to restore the database through the UI.

**Current behavior:**
- Restoring fails. with postgres error `ERROR:  must be owner of extension plpgsql`
- Reason: the statment `COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';` acts on the `pg_catalog` schema which is (by default) only accessible to the *Superuser* role. 

**Expected behavior:**
- Database restore does not fail.

**Solution:**
- Something arround [this](https://github.com/xoe-labs/dodoo-initializer/blob/d9d252624bd59e3e798592de20c3cf08a780b35e/src/backuper.py#L20) 
- Change `cmd = ["pg_dump", --no-owner", dbname]` to
- `cmd = ["pg_dump", "--schema=public", "--no-owner", dbname]`

**Comment by blaggacao** [comment]
@odony I beleive this is related to a failing restore in the upgrade platform. 
Reported under task: 1999043

**Comment by pedrobaeza** [comment]
What is the status of this? There were answer?

**Comment by blaggacao** [comment]
No idea, over a year ago... :zany_face:

**Comment by pedrobaeza** [comment]
Well, should we close it then?
