### ISSUE TITLE
EasyPost Shipping Integrator sending package dimensions as (centimetres) instead of (inches)

### ISSUE THREAD

**Issue by waterproau** [odoo/odoo#31122]
Impacted versions: 12 Enterprise

EasyPost Documentation states that Package Dimension are in INCHES (IN) and go to one decimal point. https://www.easypost.com/docs/api#parcels

Package dimensions in Odoo are recorded in CENTIMETRES (CM). Odoo is not converting centimetres to inches when sending request to Easypost, resulting in a higher rate being returned from carrier. e.g

A 10cm x 10cm x 10cm package in Odoo is being received at EasyPost as 10inch x 10inch x 10inch instead of 3.9inch x 3.9inch x 3.9inch. EasyPost then convert 10inch x 10inch x 10inch to 25.4cm x 25.4cm x 25.4cm before forwarding the request to integrated carrier. Carrier returns a rate for package dimensions 25.4cm x 25.4cm x 25.4cm instead of original request of 10cm x 10cm x 10cm.

When raising this issue with EasyPost support, the following response was received:
--
That adds up - we do indeed process all weights in ounces and all dimensions in inches. We then convert as necessary when passing to carriers.

I checked the info that was passed to us on your account, and given the instance you've presented, I think I found the call:
"parcel": {
          "weight": "14.200000000000001",

          "length": "10",

          "width": "10",

          "height": "10"​
        },
Here, we see that the weight was calculated correctly (0.4kg ~= 14oz), but the dimensions were passed directly without conversion.

I would reach out to Odoo to see if they are intending to send it this way (perhaps there's a user setting to adjust) or if they need to make a change on their end.

**Comment by amoyaux** [comment]
@waterproau Effectively it's a bug. I will fix it now.
Thanks for investigating and reporting the issue.

**Comment by amoyaux** [comment]
After further investigation, it seems that the dimension on delivery package do not specify UoM. You can directly encode them as inches. However, I agree that the user can't guess it's inches and not centimetre. In order to fix it, I can't do an explicit conversion from centimetre to inches since other user could have directly encoded inches. Instead I will add an explicit unit of measure in the form view.

**Comment by waterproau** [comment]
> After further investigation, it seems that the dimension on delivery package do not specify UoM. You can directly encode them as inches. However, I agree that the user can't guess it's inches and not centimetre. In order to fix it, I can't do an explicit conversion from centimetre to inches since other user could have directly encoded inches. Instead I will add an explicit unit of measure in the form view.

Thanks for your quick action on this! Agreed, I think your solution is ideal. Please advise when a fix is implemented and I can then test it and provide feedback.

**Comment by amoyaux** [comment]
https://github.com/odoo/enterprise/pull/3661
I created a feedback for future development in order to be able to manage unit of measure for packages dimensions.

**Comment by waterproau** [comment]
> [odoo/enterprise#3661](https://github.com/odoo/enterprise/pull/3661)
> I created a feedback for future development in order to be able to manage unit of measure for packages dimensions.

So Unit of Measure will be handled in the same way as DHL & UPS Connectors, where the user can select preferred Package Dimension Unit e.g Inches or Centimetres from the Delivery Method configuration. If Inches is selected no conversion is necessary when sending request to EasyPost. If Centimetres is selected, Odoo will convert Centimetres to Inches before sending request to EasyPost?

<img width="1095" alt="package dimensions unit" src="https://user-images.githubusercontent.com/20077718/53061328-55181780-350d-11e9-9a03-9a8352f7c7f6.png">

**Comment by amoyaux** [comment]
We will probably do the same, yes.

**Comment by pimodoo** [comment]
After investigations, Easyposts only accept inches, so when you create packagaes for easypost the size is set in Inches. Fixed in rev: https://github.com/odoo/enterprise/commit/27ad7e55362715b0774cad611276d26dbc6195f3#diff-b50f4aa8b56949abe4f6b265a2831b98 inversion 12.0

**Comment by waterproau** [comment]
> After investigations, Easyposts only accept inches, so when you create packagaes for easypost the size is set in Inches. Fixed in rev: [odoo/enterprise@27ad7e5#diff-b50f4aa8b56949abe4f6b265a2831b98](https://github.com/odoo/enterprise/commit/27ad7e55362715b0774cad611276d26dbc6195f3#diff-b50f4aa8b56949abe4f6b265a2831b98) inversion 12.0

I assume adding a label (Inches) to Package Dimensions is a temporary fix? A full solution would be to provide the user choice of Centimetres or Inches for Package UoM when configuring an EasyPost Delivery Method. This option already exists for DHL & UPS, as per my previous screenshot, so it makes sense that EasyPost would do the same.

**Comment by amoyaux** [comment]
@waterproau It would require a new field on the delivery carrier. We can't add a new field in a stable version. So this fix will remains in this version and will be improved in master
