### ISSUE TITLE
Payments made in Point of Sale as type Batch Deposit cannot be reconciled with Bank Statement

### ISSUE THREAD

**Issue by waterproau** [odoo/odoo#31123]
Impacted versions: 12 Enterprise

Batch Deposit Payments registered through Point of Sale cannot be reconciled with Bank Statement. 
Odoo Server Error: A selected move line was already reconciled.

Steps to reproduce:
1. Create New Payment Journal
- Type = Bank
- Use In Point Of Sale = True
- Payment Method Type For Incoming Payments->Manual = False
- Payment Method Type For Incoming Payments->Batch Deposit = True

2. Enable Point of Sale->Settings->Bills & Receipts->Invoicing = True
3. Open new Point of Sale Session and record transactions with an Invoice.
4. Close Point of Sale Session and Post Entries.
5. View registered payments at Accounting->Customers->Payments. They should have Payment Method Type = Batch Deposit

**Important Note:** Payments registered from Point Of Sale have Status 'Reconciled' where as Payments registered directly on Invoice from backend using the same Payment Journal have Status 'Posted'.

6. Select the recorded Point of Sale Payments at Accounting->Customer->Payments and create 'Batch Payment' from Action Menu.
7. Create a deposit in Bank Statement which matches the total amount of Batch Payment in step 6.
8. From Bank Statement Reconciliation. Match 'Batch Payment' created in step 6 with deposit created in step 7 and Reconcile.
9. Odoo Server Error: A selected move line was already reconciled.

<img width="1137" alt="pos batch payment already reconciled" src="https://user-images.githubusercontent.com/20077718/52826694-d9375d00-3111-11e9-90cb-f0269f986b7d.png">

**Comment by Elenaodoo** [comment]
Dear Clint, 

I have replied to you on ticket n°1948271 that you created for our support team. 

In order to centralize our interactions on one channel, could you please reply to me on the ticket and not here? :) 

Thanks and have a nice day!
Kind regards,

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this issue as there is clearly an OPW through which is communicated. Please don't duplicate tickets to the Github issue tracker, it'll just create overhead and noise which results in twice the work load.
Thanks for pointing it out @Elenaodoo

**Comment by waterproau** [comment]
@Yenthe666 Issue was created here 4 weeks ago. No one responded, so I created a Support Ticket and made it clear this issue is already open by providing @Elenaodoo the link to this issue. She has chosen to communicate via the Support Ticket instead, which is what we will do.

**Comment by Yenthe666** [comment]
Ahh I understand. If you have an enterprise license you're probably best off reporting it through the Odoo website. Response times are quite a bit better there as this is usually best effort and partly managed by volunteers like me. :) Best of luck.
