### ISSUE TITLE
[8.0,master] List view ID column is not sortable

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#3115]
The Project Issues list view has an ID columns.
For some reason clicking on the ID column header to sort the list by ID doesn't do anything.
In all the other columns it works.

**Comment by 4fuss** [comment]
Hi, I'm facing the same problem. Have you found out what is the reason of this behaviour?

**Comment by dreispt** [comment]
No. In fact I also noticed the same issue on Many2one fields on other tree views...

**Comment by 4fuss** [comment]
It is fixed by this: https://github.com/odoo/odoo/pull/7487

**Comment by Yenthe666** [comment]
Hey @dreispt,

Closing this one as it has been solved in https://github.com/odoo/odoo/commit/0920c2fae06d2fda8298bcc55c6388eedefefdf5

Regards,
Yenthe
