### ISSUE TITLE
python crashed on windows

### ISSUE THREAD

**Issue by modeste2015** [odoo/odoo#31166]
Python crached on windows after last message in the log of generating routing map
![capture_log](https://user-images.githubusercontent.com/16214860/52896898-84a9e580-31d6-11e9-958d-192a4d0d711e.JPG)

**Comment by pedrobaeza** [comment]
The log you are showing doesn't contain any error, so you should provide more information for being a valid issue. This is probably a deployment problem.

Closing meanwhile.
