### ISSUE TITLE
odoo12:how to hide edit button in form fro state value ?

### ISSUE THREAD

**Issue by sehngya** [odoo/odoo#31167]
Hello everyone!
I want to hide edit button on the form view for state value in odoo12 ?  
Can it be done?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
