### ISSUE TITLE
Shipping address does not show in purchase order print

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#31171]
### Impacted versions:

12.0

### Steps to reproduce:

Install purchase and stock apps, create purchase order and print a PDF report.

### Current behavior:

Shipping address does not show.

This commit https://github.com/odoo/odoo/commit/c71da7db84f20ba8fb8c4da83d6a3ee063bb1c01#diff-462715c8faf9066fcc990e26a5e2d224 must have brought the issue since `dest_address_id` is always blank when the goods are delivered to a warehouse.

### Expected behavior:

Shipping address should show.

### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7766939/52924948-49dcb480-3372-11e9-9f5b-d7eac0bbbfa0.png)

**Comment by JanneKjellman** [comment]
Same problem here with 12.0-20181118 (Community Edition).

**Comment by yostashiro** [comment]
This commit https://github.com/odoo/odoo/commit/88348f8ff90cf0b01374f5c3ba0b5097c1712105 seems to have fixed the issue.
