### ISSUE TITLE
[8.0/Master] Traceback when create stock move.

### ISSUE THREAD

**Issue by cod-odoo** [odoo/odoo#3120]
Impacted Version:
   8.0,master
Step to reproduce:
->Go to Warehouse > Stock Move
->Go to search view filter by product ie.iMac
->Click on create button you got traceback
Current behaviour:
       Traceback:DataError: invalid input syntax for integer: "iMac"
                 LINE 2:   WHERE product_product.id IN ('iMac') AND...
Expected behaviour:
     Traceback should not come.

**Comment by pna-odoo** [comment]
Not reproduced.
