### ISSUE TITLE
Issue when creating invoices from set of sale orders

### ISSUE THREAD

**Issue by juppe** [odoo/odoo#31203]
**Impacted versions:** 10.0
Tested on 10.0, but the problematic piece of code in addons/sale/models/sale.py --> action_invoice_create, is very similar in 11.0 and 12.0

**Steps to reproduce:**
Choose a set of sale orders to invoice. Use the action _Invoice Order_ in the _Sales to Invoice_ view. If for some reason one of the orders chosen to be invoiced has invoice_status == _to invoice_, but despite that has no invoiceable lines, we will run into trouble.

**Current behavior:**
In addons/models/sale.py the sale order with no lines to invoice is detected and a _UserError_ is raised [here](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L376-L377). The real issue is that the _UserError_ is raised inside this [for loop](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/sale.py#L373-L393) that is adding/computing  taxes for the created invoices. The raise breaks the loop and we are left with invoices without taxes.

**Expected behavior:**
We expect to get invoices with their taxes computed correctly, even though the set of created invoices contains an invoice with no lines, when invoicing multiple sale orders at once.

**Comment by pedrobaeza** [comment]
What I don't get is how can you force that the invoice_status == to invoice, but there's no invoiceable lines. Don't you see here an inconsistency? If this reproducible with standard code? If not, then you should adapt your custom code to cover that situation, pre-filtering the orders to invoice before calling the general invoicing wizard method.

**Comment by juppe** [comment]
Correct! I'm not exactly sure on how to reproduce the error that is leading to the inconsistent state of the invoice_status on the sale order. It seems that it happens in some cases on sale orders which have multiple deliveries and possibly also return deliveries done before invoicing. I would however treat that as an separate issue, and focus here on the problem that the raising of the UserError inside the for-loop in the action_invoice_create method causes. It leaves us with invoices without taxes.

**Comment by pedrobaeza** [comment]
Well, they are connected, as if the condition is not reproducible, then it's correct to have that raise there. I wouldn't want to make half of the operations, and this is the general Odoo paradigm.

**Comment by Yenthe666** [comment]
I actually think that we should consider this desired behaviour (or a limitation of the system, whatever you prefer) and should close this off. What do you think @pedrobaeza?

**Comment by pedrobaeza** [comment]
Yes, let's close it.
