### ISSUE TITLE
Deleting Admin/Admin Account breaks upgrades

### ISSUE THREAD

**Issue by probabble** [odoo/odoo#31216]
Impacted versions: 12.0 [more?]

Steps to reproduce: Delete the default admin account from the system using the user management feature. Next, try to upgrade an app (e.g. Account module). 

Current behavior:
Hard fail during upgrade. No clear path to restoring deleted user. 

Expected behavior:
Accounts that are hardcoded dependencies of the system should not be allowed to be deleted. Messaging about performing dangerous behavior when attempting deletion of these accounts should be presented when users escalate their permissions and attempt this operation. 

A clear path toward recreating the deleted users should be supplied in case of deletion. Currently this is being handled by a high-level Odoo SA representative on our behalf because the correct procedure for restoration is undocumented.

**Comment by pedrobaeza** [comment]
Update `base` module.

**Comment by probabble** [comment]
Thanks for the reply @pedrobaeza ... unfortunately doing this breaks the interface completely :( 
```
Uncaught Error: QWeb2: Template 'web_studio.SystrayItem' not found
```

**Comment by probabble** [comment]
Interesting: that QWeb thing is a separate issue when upgrading the base module that can be resolved by logging out and logging back in.

**Comment by probabble** [comment]
Now, where should the documentation about the importance of this admin user and how to restore it in case it gets accidentally deleted (if upgrading the `base` module is really the best way of doing it)?

**Comment by Yenthe666** [comment]
There are more 'quirks' like this in Odoo. Usually you find or figure them out by looking at the traceback and then doing a grep through the code. :) Why would you ever delete your admin user though?

**Comment by probabble** [comment]
I thought I wanted to delete it because we set up accounts for our actual admins, and the default admin account seemed like it was for demonstration. I personally object to it silently creating a password that is the same as the user account. This seems dangerous to me. I thought, "better to remove this sketchy default user and use my own users".

**Comment by probabble** [comment]
I would like to encourage this community to move away from the implicit requirement for source diving when trying to do anything. Documentation is a good thing. Have you looked at [Django's docs](https://docs.djangoproject.com) lately?

**Comment by probabble** [comment]
**If there's really no acceptable case for deleting the admin user, then this action should be prevented by the user interface.**

**Comment by Yenthe666** [comment]
@probabble you don't have to convince me about documentatio, but I don't work at Odoo 😉

**Comment by sswapnesh** [comment]
Reported at https://github.com/odoo/odoo/issues/27413

**Comment by pedrobaeza** [comment]
There are some golden rules that you should apply:

- Don't delete, but archive things if possible.
- Tests are done in a test environment, not in production.
- And finally, if you don't know, don't touch. Ask before.

**Comment by sswapnesh** [comment]
Yeah True,👍.
But also Let's prevent the blocking situation where possible.

**Comment by probabble** [comment]
@pedrobaeza can you link to these “rules” in the docs?

Rule 3 would be much better as “if you don’t know, don’t touch. *Look it up in the official documentation first*”

**Comment by pedrobaeza** [comment]
These are common sense rules in any tech activity, specially last 2 ones (as the first can be considered Odoo specific). If you want, please contribute to the docs adding them in the best place you find.

Closing this as side effect of touching. It would be advisable to prevent this situation, but it's not critical. #27413 if properly rephrased, can serve for tracking the wishlist item.

**Comment by probabble** [comment]
@pedrobaeza this issue should not be closed. The other issue does not describe the problem described here. And this problem is not resolved.

Telling customers to write the docs is very backwards. This points to deep mismanagement of the Odoo project. 

Once again, a very unsatisfying issue reporting experience :( .

**Comment by pedrobaeza** [comment]
Maybe that's because you only rant and demand things instead of having a constructive dialog and contribute in a sane way...

**Comment by probabble** [comment]
@odoo Someone should remove @pedrobaeza from this moderation role.

**Comment by Yenthe666** [comment]
@pedrobaeza you're slightly in the passive agressive zone here 😉 
I think we can all agree that there is indeed too little documentation and guidelines. Odoo does not seem to find this a priority and is focusing on other things so it seems. Perhaps at some point this will come though.
@probabble you're always welcome to contribute to the docs - and no this is not a must do - but I'm afraid for now nobody is looking into this. If you have an enterprise license you could technically create a ticket about this although I expect similar results.

Note: This is my personal opinion and not related to Odoo S.A itself.

**Comment by pedrobaeza** [comment]
Yes, I'm very direct because it's very easy to complain, but the words are proved with facts. I prefer to contribute and then complain if no action is done, as you can see in my profile activity. If not contributing that way, then contribute paying the enterprise contract and complain putting enterprise tickets, not issues in this tracker.

**Comment by probabble** [comment]
I am an enterprise customer, and I guess I'll try my luck there. I was trying to be helpful here by identifying under-documented behavior that can have catastrophic impact on an instance of this software. 

I really hope that @pedrobaeza is a loose cannon here, and doesn't represent the actual policies around interaction with this community.
