### ISSUE TITLE
Sales order line tree

### ISSUE THREAD

**Issue by hassans2020** [odoo/odoo#31221]
Impacted versions:
9.0

Steps to reproduce:
1. Create Quotation
2. Add one order line and save
3. Edit add second order line and change product in first order line and save

Current behavior:
Last order line remove

Expected behavior:
It should be not removed

Video/Screenshot link (optional):

**Comment by hassans2020** [comment]
I tested on Odoo 10 runbot and the issue available too.

It is on any One2many tree editable bottom.

**Comment by pedrobaeza** [comment]
Can you please provide a video showing the problem?

**Comment by hassans2020** [comment]
Below the link of video

[2019-02-21 15-42-18.zip](https://github.com/odoo/odoo/files/2889291/2019-02-21.15-42-18.zip)

**Comment by hassans2020** [comment]
Is there any updates?

**Comment by hassans2020** [comment]
Did you see the video?

**Comment by hassans2020** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
It has been tagged and waiting for being reviewed, but no answer is guaranteed, being this non critical and non paid service.

**Comment by Yenthe666** [comment]
Hmm I see I've labeled this 10.0 while the issue says 9.0. Where you able to reproduce this in V10, V11 or V12? V9 is end of life now.

**Comment by hassans2020** [comment]
@Yenthe666

My video testing was on V10, which mean the issue on both versions V9 and V10

https://github.com/odoo/odoo/files/2889291/2019-02-21.15-42-18.zip

**Comment by Yenthe666** [comment]
I can't seem to reproduce it on the latest 10.0 builds though. Can you test and try to reproduce it on runbot.odoo.com on a 10.0 build?

**Comment by hassans2020** [comment]
@Yenthe666

I just test it again on your runbot and see the issue still there. Did you see the video I attached?

**Comment by Yenthe666** [comment]
Yeah and I did the same steps without an issue on the latest 10.0, that is why I asked you if you can still reproduce it. Odd, I must miss something..

**Comment by hassans2020** [comment]
@Yenthe666 

I did it again on your runbot.odoo.com and still the issue V10.

Do exactly what I did on the video.

Add one product in the invoice, then save it. After that, edit the invoice again and add second product, then change the product of the first one to another product, and you will see the issue.

I am using chrome last version.

Thanks

**Comment by Yenthe666** [comment]
Dear @hassans2020,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue and a personal sorry for not replying back on your last comment.

Regards,
Yenthe
