### ISSUE TITLE
when change language to Arabic I get error on style 

### ISSUE THREAD

**Issue by modadev** [odoo/odoo#31238]

**Comment by modadev** [comment]
yesterday odoo was working very well , today i did pull from repository and i got error message when i change language to Arabic 


![image](https://user-images.githubusercontent.com/6012702/53011094-90084580-3450-11e9-8ded-8592ef9e5cba.png)


![image](https://user-images.githubusercontent.com/6012702/53011112-a1515200-3450-11e9-912f-96b692ec31f9.png)

**Comment by pedrobaeza** [comment]
@modadev which version? Have you tried on runbot? You should update your DB always you make a change in code.

**Comment by modadev** [comment]
I removed the DB and create new now but the problem still exist.

**Comment by pedrobaeza** [comment]
Can you please try in runbot to see if you can reproduce the problem there?

**Comment by modadev** [comment]
it work with runbot , and after i tried this command less-plugin-clean and it work again now  
thanks a lot
