### ISSUE TITLE
[11.0 12.0] Unable to import CAMT statement with multiple currency journal from same bankaccount

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#31249]
Impacted versions:
[11.0 12.0] 

Steps to reproduce:
Create 3 different journals with the currencies USD, CAD and EUR (make sure that the currency is set on the journal and accounts). Use the same IBAN account number for all the journals NL49RABO0123456789. Try to import the test file in all journals. 

In [11.0] You can import it in 1 journal, but it imports all the 3 statements. The test file consist of 3 statements all with a different currency, but with the same IBAN. In the other journals you get the error that the currency is not allowed.

In [12.0] You can import it in all the journals, and it imports all the 3 statements in every journal. The test file consist of 3 statements all with a different currency, but the same IBAN.

Current behavior:
see above

Expected behavior:
Import the statement belonging to the correct journal with the right currency. So in this test case it should import 1 statement per journal.
The test file is anonymized but it is the correct format that the Dutch Rabobank allows the user to download if they have 1 IBAN account with multiple currency.

Video/Screenshot link (optional):

[testcamt.xml.zip](https://github.com/odoo/odoo/files/2880373/testcamt.xml.zip)

**Comment by pedrobaeza** [comment]
This is something enterprise AFAIK.

**Comment by Yenthe666** [comment]
I believe so too. @yung-wang is there actually a reason why you log issues on Github and not with your enterprise licenses through odoo.com/help? I'm curious.

**Comment by yung-wang** [comment]
Oops, my mistake. I'm so used to the community version that i forgot to put it in the right repository. I will close this one and open another in the Enterprise.
