### ISSUE TITLE
"import compatible" exported CSV not importable due to floating point format

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#31256]
Impacted versions: 11.0

Steps to reproduce:  Put a very small value such as 7.7e-05 into a float field. Export the record using the CSV export tool and include that column. Try to import the file created by the export. 

Current behavior: Error message that column contains "incorrect values (value: 7.7e-05)"  (see screen shot). 

Expected behavior: Float fields expressed in standard formats should be imported, particularly when the CSV is generated by the Odoo export tool. 

Video/Screenshot link (optional):

![screen shot 2019-02-19 at 12 15 40 pm](https://user-images.githubusercontent.com/11529401/53048043-b2966080-3448-11e9-8b54-b1078406377f.png)

**Comment by pedrobaeza** [comment]
You can't use scientific notation. You have to put full value.

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
