### ISSUE TITLE
[12.0] Easypost is having error during rate request

### ISSUE THREAD

**Issue by ravi-webkul** [odoo/odoo#31262]
Impacted versions:
odoo v12.0 EE
Steps to reproduce:
Configured Australia post inside Easypost and then added new delivery carrier "Australia Post". After that inside sales order when i click on "Get rate" then below error gets raised.

https://prnt.sc/mnipv2

Expected behavior:
it should not happen.

**I have looked into below code(line 319 - 323): delivery_easypost/models/easypost_request.py**

`rate = [rate for rate in rates if rate['service'] == carrier.easypost_default_service_id.name][0]
 if not rate:
                error_message = _("There is no rate available for the selected service level for one of your package. Please choose another service level.") + warning_message
else:
                rate = rate[0]`

rate is already have dictionary but again in last line rate is treated as list.

Video/Screenshot link (optional):

https://prnt.sc/mnipv2

**Comment by pedrobaeza** [comment]
Can you please post this as an enterprise ticket at odoo.com/help?

**Comment by amoyaux** [comment]
https://github.com/odoo/enterprise/pull/3688

**Comment by ravi-webkul** [comment]
ok that's good, thanks!!!
