### ISSUE TITLE
How to get Tabular Form of Pivot View?

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#31299]
I try to get tabular format of pivot view in Odoo, how to do this? Is it possible with current state of Odoo

Impacted versions:
8,9,10,11..

Steps to reproduce:
Open a view with pivot sucah as  purchase order or report

Current behavior:
The pivot view only display  compact form, where added group on rows always make new row at bellow of the preveious group

Expected behavior:
The display layout need to be  in tabular form (or selectable whether to use compact form or tabular form),  tabular form more brief and easy to process in excel after export.

Video/Screenshot link (optional):

![compact vs tabular format of pivot view](https://user-images.githubusercontent.com/7310629/53136854-28b6d680-35b3-11e9-95ab-4ebf4a557a5e.jpg)

**Comment by Yenthe666** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on the Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Tip: You can get the same data although it might be slightly differently formatted in Odoo.
