### ISSUE TITLE
[12.0] Account: Invoice residual shall not change with FX differences

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#31294]
Impacted versions:
12.0 maybe 11.0

Steps to reproduce:
Following test case
https://github.com/odoo/odoo/pull/31257
Current behavior:
Exchange Difference Gains affected Invoice residual
Expected behavior:
Exchange Difference Gains must not affect Invoice residual

Video/Screenshot link (optional):

https://youtu.be/Oq9Zyu1WyRk

OPW 1943518

**Comment by pedrobaeza** [comment]
@hugho-ad were there any OPW response to this? Can you please close or update this if so?

**Comment by hugho-ad** [comment]
@pedrobaeza 

The discussion thread is on https://github.com/odoo/odoo/pull/31257

@hbto can we close this?

**Comment by pedrobaeza** [comment]
Seeing the linked thread, I'm going to close it. Please tell me if I shouldn't. Thanks for the follow-up
