### ISSUE TITLE
12.0 res_partner_title acls naming is wrong

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#31300]
Impacted versions: 12.0

https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/security/ir.model.access.csv#L64 

user is manager and vice versa

**Comment by Yenthe666** [comment]
It has actually been the same ever since version 10 (https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/security/ir.model.access.csv#L63)
@rco-odoo it looks like you've been active as last person on this one (in 10.0), what do you think?

**Comment by mart-e** [comment]
Good catch, as it is just the name, we could clean that and switch both in master. The good news is that the rules have not been inverted ;-)

**Comment by Yenthe666** [comment]
@mart-e do you make a PR/fix or want somebody else to do it - looks at himself - 😉

**Comment by mart-e** [comment]
And done at #31537, thanks for the report :+1:
