### ISSUE TITLE
Field does not exist

### ISSUE THREAD

**Issue by Abdullah1353** [odoo/odoo#31305]
Impacted versions: v11
I have seen all the issues on github and odoo platform related to this topic but still m unable to find a solution, I am trying to add a field in purchase.order . i can edit the attributes of the existing fields in its tree  but when i try to add a new one it comes back with an error that field doesnt exist but it does exist in hr.py. Kindly tell me how to resolve this issue

![capture3](https://user-images.githubusercontent.com/44639133/53147682-1b591680-35ca-11e9-86f0-93bc70e0ae33.PNG)
![capture12](https://user-images.githubusercontent.com/44639133/53147683-1b591680-35ca-11e9-9ea5-071995f3a57c.PNG)
![capture44](https://user-images.githubusercontent.com/44639133/53147684-1b591680-35ca-11e9-9941-72775bd112b7.PNG)

**Comment by Yenthe666** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on the Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
Create a custom view with an xpath and your field in the form; should work fine.
