### ISSUE TITLE
[11.0] Impossible to see journal_id and group_by fields in pos.config form view

### ISSUE THREAD

**Issue by MGinshe** [odoo/odoo#31304]
Confirmed on v11 CE.

Reproduce by installing `point_of_sale`, then visiting the pos.config form.

AFAIK, the `account_accountant` module has been removed from v11 CE. However, the `pos.config` form view still has two fields (`journal_id` and `group_by`) whose visibility depends on that module being installed.

Overview:
 - See the [form view here](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/views/pos_config_view.xml#L471) (note that visibility depends on _is_installed_account_accountant_).
 - And [here is the function](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_config.py#L167) that computes _is_installed_account_accountant_.

Assuming `account_accountant` is gone from CE, the fields will never be displayed, and are not updateable via the UI.

This is especially difficult for people who migrated from v10 -> v11, as the two fields  could have been set pre-migration, and it is now impossible to change them. These fields are fairly important!

Suggested fix: Remove the attr that hides the fields, or check for the `account_invoicing` module instead of `account_accountant`.

Would this type of change be allowed in stable? If so, I can write a quick PR to fix the issue.

**Comment by switch87** [comment]
Hi @MGinshe , 

Thank you for reporting this issue, It would be great if you could do this pr. Please try to describe as good as possible what the implications are for CE users if this is not fixed. I think it could also be checked on the module account? (Did not really investigate so I could be wrong. If your pr is ready you can set nim-odoo as reviewer.

**Comment by MGinshe** [comment]
Thanks for the advice @switch87 - I will create a PR.
