### ISSUE TITLE
`track_visibility` doesn't work for computed+stored fields

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#31301]
Impacted versions:
- 12.0

Steps to reproduce:
- Add `track_visibility=onchange` to any computed and stored field, e.g. invoice's residual
- Trigger a change on that field, e.g. validate or pay the invoice

Current behavior:
The field is not tracked.

Expected behavior:
The field is tracked.

AFAIK, this is because tracking works inheriting `create` and [write](https://github.com/odoo/odoo/blob/f7fc5bc0d597bb79f1fb0d7b851b953ad6a711b4/addons/mail/models/mail_thread.py#L316), but computed fields are written using `_write`, not `write`.

**Comment by luisg123v** [comment]
opw-1943646.

CC @moylop260

**Comment by Elkasitu** [comment]
I would say this is a misuse of the ORM api or was never a use-case, therefore I have retagged it to Services

**Comment by luisg123v** [comment]
Apparently, this issue is already solved, as computed fields seem to be tracked correctly. This was reproduced a few months ago. Therefore, I will close this issue.

If I find this issue to be reproduced in the future under some specific circumstances, I'll reopen it providing its corresponding explanation.

**Comment by elmeriniemela** [comment]
This same issue is currently in 13.0 with the field 'invoice_payment_state' on account.move, that is computed, stored and tracked. Tracking the payment status of invoices is critical for our customers, so hopefully this could be fixed for newer versions of Odoo as well.
