### ISSUE TITLE
Pricelist: "Show public price & discount to the customer" not working in order created from website

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#31337]
### Impacted versions:
11.0

### Steps to reproduce:
1. "Sales / Configuration / Settings", search by "Multiple Sales Prices per Product" and select option "Prices computed from formulas (discounts, margins, roundings)"
2. Go to "Website / Catalog / Pricelists", select "Public Pricelist" and set "Discount Policy: Show public price & discount to the customer"
3. In another tab, please go to the Shop in the website and search by product "iPad Retina Display" (this product has a discount)
4. Add product to cart and then click in button "Proceed to Checkout"
5. In the backend, please go to "Website / Orders / Orders "
6. Remove the default search filter "Confirmed Orders" and search by Customer "Administrator"

### Current behavior:

When I check the create sale order in the backend it shows the "Ipad Retina Display" line with the discount applied directly to the unit price. it does not show the information related to the corresponding discounts.

![image](https://user-images.githubusercontent.com/7593953/53199983-34c88580-35ff-11e9-97bc-50248dd89b58.png)

### Expected behavior:

If in the same sale from the backend (or in any other) I add the same product, you can see that the line have the detailed and real information about the product price and the applied discount. 

![image](https://user-images.githubusercontent.com/7593953/53199990-3c882a00-35ff-11e9-83c5-652a301d1b50.png)

![image](https://user-images.githubusercontent.com/7593953/53200258-e10a6c00-35ff-11e9-967f-24072fc1a645.png)

-- tested in http://456445-11-0-5917ef.runbot15.odoo.com/

**Comment by zaoral** [comment]
FYO opw-1943989

**Comment by intero-chz** [comment]
@zaoral could you please update the state of your OPW? I'm very interested in this issue, because a customer has the same problem and i would like to know, what will happen: either it will be fixed or not or whatever Odoo is stating about it. Thank you!

**Comment by zaoral** [comment]
Hi @intero-chz 

Sure! the OPW was reported just 4 days ago. we do not have answer from Odoo yet.
I will keep you informe via this issue.

Best Regards

**Comment by zaoral** [comment]
@intero-chz update: the ticket has been forwarded to Odoo's bug fix team

**Comment by intero-chz** [comment]
@zaoral that is a really good news!

**Comment by janbec** [comment]
Interesting indeed. I submitted that for the point of sale a while ago (discount is deducted but not displayed although ticked in pricelist) and it was not considered a bug.
Good thing this got fixed at least!

**Comment by zaoral** [comment]
This issue is resolved.
