### ISSUE TITLE
[11.0] View Quotation link in mail does not work for portal users if they are not logged in

### ISSUE THREAD

**Issue by katyukha** [odoo/odoo#31348]
Impacted versions: 11.0

Steps to reproduce:
1. login as employee
2. Create Sale Order
3. Add portal user to followers of created SO
4. Subscribe portal user to *Sale Order Confirmed* mail type on created SO
5. Confirm created Sale Order
6. Check mail box of portal user. There is mail with link like [View Quotation](http://456443-11-0-21e44d.runbot15.odoo.com/mail/view?message_id=9268). Copy that link.
7. Open new browser session (anonymous window/tab), user unauthenticated.
8. Paste copied link in browser. Request will be redirected like: `http://456443-11-0-21e44d.runbot15.odoo.com/web/login#view_type=form&model=sale.order&id=103&active_id=103&view_id=False`
9. Login as portal user

Current behavior:

After login portal user redirected to ```http://456443-11-0-21e44d.runbot15.odoo.com/#view_type=form&model=sale.order&id=103&active_id=103&view_id=False```

Expected behavior:

Portal user redirected to ```http://456443-11-0-21e44d.runbot15.odoo.com/quote/103/ee8a38e4-fc09-4153-9bf7-7506e6466ebb```

**Comment by mart-e** [comment]
Hello,

Sorry but this mail is sent indentically to all the followers of a document. We have some specific "Send by email" button that will take care of the portal view but if you use some internal communication via the chatter, this will stay internal. The goal is that every follower get the same link.

![Screenshot_2020-02-25 SO032 - Odoo](https://user-images.githubusercontent.com/564822/75223645-39da8a80-57a7-11ea-88f0-24fda59f3441.png)
