### ISSUE TITLE
chose a payroll localization is always empty

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#31359]
Impacted versions: 12

Steps to reproduce: 

http://458575-12-0-27f8bb.runbot13.odoo.com/web#id=&action=581&model=res.config.settings&view_type=form&menu_id=393

just go to payroll settings 

Current behavior:
no module is listed 

Expected behavior:
to list available modules

l10n_be_hr_payroll
l10n_in_hr_payroll

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/17784575/53240601-6c870a00-369f-11e9-9677-00f4109e46cc.png)

**Comment by mart-e** [comment]
Looks like it was introduced at 6ee7c68efa60a18ddf25a42d2bf966567cc00480

@tivisse should we just remove the category filter from the context?
https://github.com/odoo/odoo/blob/198ab837e466f3155ea1c3b35811b981b1c1e537/addons/hr_payroll/views/res_config_settings_views.xml#L7

**Comment by tivisse** [comment]
Hi @mart-e 

If you remove the category_filter, you'll display several unwanted modules, like 'l10n_be_hr_payroll_fleet', or worse 'test_l10n_be_hr_payroll_account' that was introduced one version aftwerward.

As there is/will be a mismatch between the module categories, why not removing the context completely and replacing it by a domain like: [('name', '=like', 'l10n____hr_payroll')]

I've tested it, I'm gonna make the fix myself ! 

Thanks for the feedback @icf20 ;)

**Comment by tivisse** [comment]
Will be fixed at https://github.com/odoo/odoo/pull/51220

Thanks.
