### ISSUE TITLE
[12][XML-RPC] Variants get deleted after template update

### ISSUE THREAD

**Issue by Donderda** [odoo/odoo#31369]
Hi everyone,
this is surely just a small issue. Currently I'm having an issue with the Update process:

I can create and update the `product.template` with no issue via the XML-RPC. I can also create a new Variant for the `product.template`. No problems so far.

But if I update the product.template after the variants were created, the variants get deleted. I assume it has something to do with the `product.template.product_variant_ids` field.

Has anyone an example how it should look like? I just want to keep the Variants which were generated :(.

The documentation (https://www.odoo.com/documentation/12.0/reference/orm.html#odoo.models.Model.write) didn't help me neither.

I tried these values for `product.template.product_variant_ids`
```
1: [[4,ID1,false],[4,ID2,false],[4,ID3,false], ... ]
2: [[0, false, [ID1,ID2,ID3,...]]]
```

I would really appreciate if someone could give me a hint what to do :)

**Comment by Donderda** [comment]
Update: The Log gives this message:
`odoo.models.unlink: User #8 deleted product.product records with IDs: [213003, 213004, 213005, 213006, 213007] `

**Comment by katyukha** [comment]
Hi!

`product_variant_ids` is `One2many` field, and it think it is not a good idea to update variants through this field. 

Documentation by your link tells following:

    (4, id, _)
    adds an existing record of id id to the set. **Can not be used on One2many**.

But deletion of records is strange bechavior....

**Comment by Donderda** [comment]
Thank you for your reply.
Yes, I also doubt that `(4, id, _)` is the correct one. But I have no idea what I should use instead... Maybe `(1, id, values)` ? But what should be the values?

**Comment by katyukha** [comment]
In case of `(1, id, values)`, `values` is dictionary with fields to be written to related model (in your case it is `product.product` (product variant))

I think it would be better to not write `product_variant_ids` as field, remove this field from values passed to `write` method.

**Comment by Donderda** [comment]
I just added it, because the the variants got deleted :(. 

I enabled the debug output of the odoo instance, but sadly there are no further information: The field  `product_variant_ids` isn't touched after I removed the field. But the Logger still keeps telling me that the variants get deleted:

```
call product.template(4705,).write({'image': 'imagedata', 'lst_price': 0.0, 'uom_po_id': 1, 'sale_ok': True, 'active': True, 'list_price': 0.0, 'type': 'product', 'taxes_id': [[6, False, [15]]], 'uom_id': 1, 'price': 0.0, 'id': 4705,  'default_code': 'MyProduct-p'}) 

2019-02-22 15:13:32,141 28395 INFO odoo1 odoo.models.unlink: User #8 deleted mail.message records with IDs: [220410, 220409, 220408] 
2019-02-22 15:13:32,172 28395 INFO odoo1 odoo.models.unlink: User #1 deleted ir.property records with IDs: [149251, 149252, 149253] 
2019-02-22 15:13:32,319 28395 INFO odoo1 odoo.models.unlink: User #8 deleted product.product records with IDs: [212440, 212439, 212438] 
2019-02-22 15:13:32,347 28395 INFO odoo1 odoo.models.unlink: User #1 deleted mail.followers records with IDs: [219828, 219829, 219830] 
2019-02-22 15:13:32,349 28395 INFO odoo1 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
```

Did I miss a configuration setting?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip: This seems you are mangling the attributes or its values, and that's why everything is reset.

Closing this by the reason above.

**Comment by Donderda** [comment]
Thank you for your tip. I found my error :). Excuse my misuse of the issue section!
