### ISSUE TITLE
[12.0] Account Analytic _name_search method domain bug

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#31371]
Impacted versions: 12.0

URL: https://github.com/odoo/odoo/blob/12.0/addons/analytic/models/analytic_account.py#L155

Expected behavior: Searching for name in field account_analytic_id should return the analytic accounts that have either the searched name, code or partner name.

Actual behavior: It only returns searched accounts by partner name.

After changing it, we found that the issue may be related to the fact that the domain applied in the _name_search method re-implementation uses two logic "OR" operators and three conditions, and it makes it only apply to the last one (partner name) for some reason.

**Comment by pedrobaeza** [comment]
Looking at the code, the domain is correct, applying an OR to all with 2 `|` operands. Any way, I don't get what you want to achieve. If you have a specific proposal, please make instead a PR, and the discussion can be around that alternative code.

Closing by the reasons above.

**Comment by reinaldoramosarxi** [comment]
The domain looks correct, and that is why we find it strange that it doesn't work.

The behavior, however, is not correct, and that, I believe, classifies the issue as a bug. 

But I'll add some more information:
It seems that, if the analytic account does NOT have a linked partner, the search filter doesn't work at all. It does work otherwise.

**Comment by BT-rmartin** [comment]
I also noticed this problem and I fully agree with Reinaldo. 
The problem comes when partner is not set in the analytic account, as then it cannot navigate to name and results are wrong. When partner is set it works as expected. 
Please, @pedrobaeza reopen this issue

**Comment by pedrobaeza** [comment]
Please propose the patch for fixing it.

**Comment by hassans2020** [comment]
Any updates about this issue, I have this issue too. I cannot search by name field of analytic account.

**Comment by kebeclibre** [comment]
The issue should be solved with https://github.com/odoo/odoo/pull/31881
