### ISSUE TITLE
[12.0] Invoice: Due date not being calculated from payment term when creating invoice from sale order

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#31377]
Impacted versions: 12.0

Steps to reproduce:
1. Create quotation and fill in the payment terms (eg. 15 days, 30 days...)
2. Create invoice from said quotation

Current behavior: The created invoice draft has the date_due field empty on creation and only calculates it based on the payment terms if, while editing, the payment term is re-selected.

Expected behavior: The created invoice draft should have the date_due field filled in automatically on creation.

Video/Screenshot link (optional): ![duedate](https://user-images.githubusercontent.com/42942314/53257991-6a36a700-36c3-11e9-8f34-da05ef7530bf.png)

**Comment by pedrobaeza** [comment]
But this is validating the invoice or only on draft state?

**Comment by reinaldoramosarxi** [comment]
Only on draft state. If you validate, it does the calculation.

**Comment by pedrobaeza** [comment]
Then this is something expected. If you change the payment term, then the result is displayed for you to see if this is what you want, but on automation, that "preview" is not needed.

Closing as no real issue.
