### ISSUE TITLE
vat value dint work correctly 

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#31380]
Impacted versions: 12

Steps to reproduce:
cant reproduce on run bot i will  try to reproduce this in coming days if i can 

Current behavior:
VAT goes crazy in value

Expected behavior:
just go up 21% 

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/17784575/53266575-7598cb00-36e1-11e9-82f0-e8ed57482ebb.png)

the workaround is too re conciliate and so on

**Comment by pedrobaeza** [comment]
You need also to specify more details on the steps to reproduce the problem.

**Comment by icf20** [comment]
any suggestion of what info do you need?

**Comment by pedrobaeza** [comment]
All detailed steps from login to get to the problem: click here, introduce this, and so on...

**Comment by icf20** [comment]
i think i managed to reproduce this run bot
http://459930-12-0-9434ee.runbot11.odoo.com/web?debug=#id=183&action=506&model=account.invoice&view_type=form&menu_id=325

INV/2019/0007 has 

Untaxed Amount | $ 859.44
-- | --
Tax | $ 128.94
Total | $ 988.38

while on Invoices Analysis 

17,790.84 |  
-- | --

**Comment by pedrobaeza** [comment]
OK, I see the problem, and it's in the SQL query for getting this:

https://github.com/odoo/odoo/blob/917ad030263a02994ea62bb6bd98667e629d58d6/addons/account/report/account_invoice_report.py#L117

It's using an invoice amount for adding it on each invoice line, so the amount is multiplied by the number of lines.

@qdp-odoo can you check this important one? Do we have the total with tax at line level?

**Comment by Yenthe666** [comment]
Hi - just adding a note in here to get explicitly notified. I saw this one too today.

**Comment by pedrobaeza** [comment]
My only fear is to not have the amount at invoice line level, so replace that wrong expression will be difficult, but I haven't dug enough for seeing that.

**Comment by william-andre** [comment]
This was fixed by https://github.com/odoo/odoo/pull/31991
