### ISSUE TITLE
<function DataSet.call_kw at 0x7f681503f268>, /web/dataset/call_kw/res.partner/load_views: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

### ISSUE THREAD

**Issue by AthmanZiri** [odoo/odoo#31390]
Impacted versions: 12 enterprise

Steps to reproduce: Install odoo 12 enterprise using https://github.com/Yenthe666/InstallScript/blob/12.0/odoo_install.sh.
Install Inventory, sales, purchase, Invoicing and Accounting

Current behavior: Getting connection lost when i go to Sales > Orders > Customers or Purchase > Vendors.
When i inspect, i get this: <function DataSet.call_kw at 0x7f681503f268>, /web/dataset/call_kw/res.partner/load_views: Function declared as capable of handling request of type 'json' but called with a request of type 'http' 

I cannot do anything else after this happens. I have to manually stop and start odoo-service.

I get the above when i install with or without sample data.

Expected behavior: I should get customer list or Vendor list 

Video/Screenshot link (optional):
![bug](https://user-images.githubusercontent.com/16459329/53324547-152ca800-38f2-11e9-8a9e-50d8b5efead6.jpeg)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by AthmanZiri** [comment]
Hi, thanks for the quick response. will try to use this https://www.odoo.com/documentation/12.0/setup/install.html and give give feedback
