### ISSUE TITLE
[10.0][BUG][stock] stock.production.lot : Quantity is wrong

### ISSUE THREAD

**Issue by morekvn** [odoo/odoo#31391]
Impacted versions: 10.0

Steps to reproduce:
LOT-000006
Virtual Locations/Inventory loss ============ 200
Stock/Internal Location =================== 1000

Current behavior:
Quantity is wrong because it sums Internal and Virtual location.
It should deduct virtual from the first internal.
For the moment, it add everything together.

Expected behavior:
Quantity should be 800, not 1200

**Comment by pedrobaeza** [comment]
I don't see your reasoning. If you have 1000 in internal location, why it should 800? And stock in virtual locations is for sure not sum on quantity on hand. Where are you looking to that? You should record a video or put screenshots to illustrate what you are saying? You should try also on a runbot clean instance (https//runbot.odoo.com - admin/admin).

**Comment by Yenthe666** [comment]
Hi there,

As there has been no feedback since the last questions from my colleague I'm closing off this ticket.
Don't hesitate to respond back with more info and we'll reopen it then.

Regards,
Yenthe
