### ISSUE TITLE
new .csv account chart for l10n_de_skr04 misses data in field reconcile

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#31393]
Impacted versions:
12.0
module l10n_de_skr04

Steps to reproduce:
look in source code of module l10n_de_skr04 the file .../addons/l10n_de_skr04/data/account.account.template.csv

Current behavior:
The field reconcile is empty which could lead to issues as all accounts might get the default value for the reconcile boolean field. Check here:
https://github.com/odoo/odoo/blob/12.0/addons/l10n_de_skr04/data/account.account.template.csv
and compare here:
The field reconcile is empty which could lead to issues as all accounts might get the default value for the reconcile boolean field.
Check here as it is ok in that file:
https://github.com/odoo/odoo/blob/12.0/addons/l10n_de_skr03/data/account.account.template.csv

Expected behavior:
The boolean field "reconcile" should get the right values for l10n_de_skr04 in the same way as the module l10n_de_skr03.  The right values for the boolean field are here (V11):
https://github.com/odoo/odoo/blob/11.0/addons/l10n_de_skr04/data/l10n_de_skr04_chart_data.xml

... or you can get the values from replaced l10n_de_skr04_chart_data.xml.

**Comment by Yenthe666** [comment]
Are https://github.com/odoo/odoo/pull/31392 and https://github.com/odoo/odoo/pull/31389 not resolving this too?

**Comment by jco-odoo** [comment]
As the default value is False, why is this causing problems?

**Comment by tv-openbig** [comment]
@Yenthe666 
No both PR's are not related to that issue.
No, #31389 concerns V11, where the account chart data is in .xml files.
For #31392 i wanted to change the reconcile flag for just one account.
That was the moment i stumbled over the missing "reconcile" values for all accounts in the module l10n_de_skr04 (V12).

@jco-odoo 
We have 27 accounts in the affected module l10n_de_skr04 (V12) where we need the "True" value. If you want i can make another PR, where i complete the column "reconcile". Otherwise these are the relevant accounts from the commit https://github.com/odoo/odoo/commit/d8058ccc6a1c70c3c21489b89c47da3bb06c4829#diff-d4c7462aafe4e963471a2f8ae1b55dd3 

... where account chart data was changed from .xml to .csv, without keeping the relevant "reconcile" field as active:

    6              <field name="code">1460</field>
    7              <field name="name">Geldtransit</field>
    8:             <field name="reconcile" eval="True"/>
    9              <field name="tag_ids" eval="[(6,0, [ref('l10n_de.tag_de_asset_bs_B_II_4')])]"/>
   10              <field name="user_type_id" ref="account.data_account_type_current_assets"/>
   ..
 1038              <field name="code">1200</field>
 1039              <field name="name">Forderungen aus Lieferungen und Leistungen</field>
 1040:             <field name="reconcile" eval="True"/>
 1041              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1042              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1046              <field name="code">1205</field>
 1047              <field name="name">Forderungen aus Lieferungen und Leistungen (Odoo)</field>
 1048:             <field name="reconcile" eval="True"/>
 1049              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1050              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1054              <field name="code">1210</field>
 1055              <field name="name">Forderungen aus Lieferungen und Leistungen ohne Kontokorrent</field>
 1056:             <field name="reconcile" eval="True"/>
 1057              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1058              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1062              <field name="code">1215</field>
 1063              <field name="name">Forderungen aus Lieferungen und Leistungen zum allgemeinen Steuersatz</field>
 1064:             <field name="reconcile" eval="True"/>
 1065              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1066              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1070              <field name="code">1216</field>
 1071              <field name="name">Forderungen aus Lieferungen und Leistungen zum ermäßigten Steuersatz </field>
 1072:             <field name="reconcile" eval="True"/>
 1073              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1074              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1078              <field name="code">1217</field>
 1079              <field name="name">Forderungen aus stfr. oder nicht stb. Lieferungen und Leistungen</field>
 1080:             <field name="reconcile" eval="True"/>
 1081              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1082              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1086              <field name="code">1218</field>
 1087              <field name="name">Forderungen aus Lieferungen und Leistungen gemäß §24 UStG</field>
 1088:             <field name="reconcile" eval="True"/>
 1089              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1090              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1094              <field name="code">1219</field>
 1095              <field name="name">Gegenkonto 1215-1218 bei Aufteilung der Ford. nach Steuersätzen (EÜR)</field>
 1096:             <field name="reconcile" eval="True"/>
 1097              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1098              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1102              <field name="code">1220</field>
 1103              <field name="name">Forderungen nach § 11 EStG für § 4/3</field>
 1104:             <field name="reconcile" eval="True"/>
 1105              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1106              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1158              <field name="code">1240</field>
 1159              <field name="name">Zweifelhafte Forderungen </field>
 1160:             <field name="reconcile" eval="True"/>
 1161              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1162              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1214              <field name="code">1250</field>
 1215              <field name="name">Forderungen aus Lieferungen und Leistungen gegen Gesellschafter </field>
 1216:             <field name="reconcile" eval="True"/>
 1217              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_1')])]"/>
 1218              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1238              <field name="code">1260</field>
 1239              <field name="name">Forderungen gegen verbundene Unternehmen</field>
 1240:             <field name="reconcile" eval="True"/>
 1241              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_2')])]"/>
 1242              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1262              <field name="code">1266</field>
 1263              <field name="name">Besitzwechsel gegen verbundene Unternehmen </field>
 1264:             <field name="reconcile" eval="True"/>
 1265              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_2')])]"/>
 1266              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1294              <field name="code">1270</field>
 1295              <field name="name">Forderungen aus Lieferungen und Leistungen gegen verbundene Unternehmen </field>
 1296:             <field name="reconcile" eval="True"/>
 1297              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_2')])]"/>
 1298              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1334              <field name="code">1280</field>
 1335              <field name="name">Forderungen gegen Unternehmen mit Beteiligungsverhältnis</field>
 1336:             <field name="reconcile" eval="True"/>
 1337              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_3')])]"/>
 1338              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 1390              <field name="code">1290</field>
 1391              <field name="name">Forderungen aus Lieferungen und Leistungen gegen UN mit Beteiligungsverhältnis</field>
 1392:             <field name="reconcile" eval="True"/>
 1393              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_asset_bs_B_II_3')])]"/>
 1394              <field name="user_type_id" ref="account.data_account_type_receivable"/>
 ....
 3318              <field name="code">3300</field>
 3319              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen</field>
 3320:             <field name="reconcile" eval="True"/>
 3321              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3322              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3326              <field name="code">3301</field>
 3327              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen (Odoo)</field>
 3328:             <field name="reconcile" eval="True"/>
 3329              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3330              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3334              <field name="code">3305</field>
 3335              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen zum allg. Umsatzsteuersatz</field>
 3336:             <field name="reconcile" eval="True"/>
 3337              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3338              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3342              <field name="code">3306</field>
 3343              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen zum erm. Umsatzsteuersatz</field>
 3344:             <field name="reconcile" eval="True"/>
 3345              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3346              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3350              <field name="code">3307</field>
 3351              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen ohne Vorsteuer</field>
 3352:             <field name="reconcile" eval="True"/>
 3353              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3354              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3366              <field name="code">3310</field>
 3367              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen ohne Kontokorrent</field>
 3368:             <field name="reconcile" eval="True"/>
 3369              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3370              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3406              <field name="code">3340</field>
 3407              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen gg. Gesellschaftern </field>
 3408:             <field name="reconcile" eval="True"/>
 3409              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_4')])]"/>
 3410              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3502              <field name="code">3420</field>
 3503              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen gg. verbundene UN</field>
 3504:             <field name="reconcile" eval="True"/>
 3505              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_6')])]"/>
 3506              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 3566              <field name="code">3470</field>
 3567              <field name="name">Verbindlichkeiten aus Lieferungen und Leistungen gg.UN m.Bet.verh.</field>
 3568:             <field name="reconcile" eval="True"/>
 3569              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_7')])]"/>
 3570              <field name="user_type_id" ref="account.data_account_type_payable"/>
 ....
 4414              <field name="code">3850</field>
 4415              <field name="name">Aufgeschobene Einfuhrumsatzsteuer</field>
 4416:             <field name="reconcile" eval="True"/>
 4417              <field name="tag_ids" eval="[(6, 0, [ref('l10n_de.tag_de_liabilities_bs_D_8')])]"/>
 4418              <field name="user_type_id" ref="account.data_account_type_current_liabilities"/>

27 matches in 1 file

**Comment by jco-odoo** [comment]
For the accounts you give, I see "True" for the reconcile column in csv.

**Comment by tv-openbig** [comment]
OK, im very sorry @jco-odoo.  I was blinded by the first lines without any entry in that column. You are totally right, i missed to scroll down therefore i assumed all lines are empty (in l10n_skr_03 all lines either contained "False" or "True").

**Comment by jco-odoo** [comment]
So, I suppose this one can be closed?  I will check the other ones.
