### ISSUE TITLE
[BUG][10.0][Calendar]

### ISSUE THREAD

**Issue by Ash3s** [odoo/odoo#31405]
Impacted versions: 10.0

Steps to reproduce: Create an event, set privacy = 'only me', set show_as = 'free'. Then remove every attendee and change the owner of the event

Current behavior: Event loses all its field values and just appears with "Busy" as name.

Expected behavior: Not losing all fields and simply be an event with no attendees and changed owner.

Video/Screenshot link (optional):

[Test - Odoo - Event Bug.zip](https://github.com/odoo/odoo/files/2900974/Test.-.Odoo.-.Event.Bug.zip)

**Comment by pedrobaeza** [comment]
IMO, this is something expected as you should respect at least one attendee.

**Comment by Ash3s** [comment]
I get the same problem even if I change attendees removing original one and adding new ones

**Comment by pedrobaeza** [comment]
OK, I tag for deeper analysis, but no real obligation for Odoo team to check this unless you have an enterprise contract and publish the OPW ticket.

**Comment by Ash3s** [comment]
Thanks a lot in advance :)

**Comment by Yenthe666** [comment]
Dear @Ash3s,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
