### ISSUE TITLE
Image title attribute removed when selecting image in website builder

### ISSUE THREAD

**Issue by angholt** [odoo/odoo#31406]
Impacted versions: 11, 12

Steps to reproduce: In the website builder, add an image to the page, open dialog to edit alt and title attributes, enter some text in the Tooltip field, click save, click somewhere on the page to deselect image, click on the image again to select it.

Current behavior: Title attribute is removed from image element.

Expected behavior: Title attribute is not removed from element.

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=s9ovcc3qR1I

I tested this on my local environment as well as the latest v11 release on runbot and whatever v12 release is on https://demo3.odoo.com.

The issue seems to be related to some interference between Summernote and the Bootstrap Tooltip library which seems to be used to display the standard "Double click to edit" tooltip that shows when you click an image in the website builder. You can see briefly in the Video that after I have edited the tooltip for the image the standard Summernote tooltip is replaced with what I just added to the image.

**Comment by rdeodoo** [comment]
I just had a quick look while sorting issues and it seems like this was somehow fixed?
I tried on 11.0 and 12.0, the title is preserved.
