### ISSUE TITLE
[11.0][12.0][Docker] Odoo and actual lxml v4.3.1 causes odoo-container to stop/restart

### ISSUE THREAD

**Issue by MartinHeisig** [odoo/odoo#31416]
Impacted versions: 11,0 12.0 Docker

Steps to reproduce: Update python package lxml to version 4.3.1

Current behavior: Most of the pages (frontend and backend) let the odoo-container stop/restart, so the postgres-container asserts "unexpected EOF on client connection with open transaction":

Container-Log (no more lines listed for each case)
```
postgres_container | 2019-02-26 09:48:17.130 CET [29] LOG:  unexpected EOF on client connection with an open transaction
postgres_container | 2019-02-26 09:48:22.722 CET [32] LOG:  unexpected EOF on client connection with an open transaction
odoo_container exited with code 139
```

Environment:
tested with customized Odoo11 or 12 official docker builds with several daily versions from this year on a debian stretch container, also on an uncostomized odoo12 odoo docker build (latest version with odoo from 20190128)
Postgres 11.2 on Alpine 3.9 container

Solution:
Downgrade lxml back to v4.3.0

No idea if its a problem with odoo or within lxml. While the log lines above are the only starting point I have I cannot dig deeper and it was a riddle to enclose it to the specific package of lxml.

**Comment by pedrobaeza** [comment]
You should publish this in the specific Docker project: https://github.com/odoo/docker.
