### ISSUE TITLE
Sales Invoice : Group By Partner (Very Slow)

### ISSUE THREAD

**Issue by PortCities** [odoo/odoo#31419]
Impacted versions:
Odoo 11 EE

Steps to reproduce:
https://drive.google.com/open?id=1RCrt3w9j874W1wRXUXr3Fst6ZOOC_v1z
accouting -> sales -> sales Invoice -> group by : Partner

Current behavior:
10000 account invoice
8000 res_partner
around 2 min 45 s

Expected behavior:
under 30 s

Video/Screenshot link (optional):
https://drive.google.com/open?id=1Lxk8_JCV4cajJjnU9D5CZozqp2PbjC_j

**Comment by pedrobaeza** [comment]
Unless you have specific suggestions for improving this, this can't be considered as a bug. There are several factors to take into account: your deployment method, your browser client (as most of the time can be the own browser for displaying such huge table), possible custom modules, etc.

It's true that as this is computing information in real time, it might delay over other methods like OLAP cubes, but have other advantages as you get up-to-date information, so the design decision was that one. There are modules in the community for storing other kind of information for instant access.

Any way, the Odoo team continuously work for improving the performance on each of the components, as they are aware about the concepts of code complexity and performance tuning.

Closing then by the reasons above.
