### ISSUE TITLE
[8.0] WMS Picking Barcode Interface - scan > triggers Ctrl+J in Chrome, Ctrl+Shift+B in Firefox

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#3142]
Hello,

I'm experiencing some weird behavior when scanning in a Picking.
If I scan
Chrome immediately opens chrome://downloads/ (Ctrl+J)
or
Firefox opens the library window (Ctrl+Shift+B).
If I return to odoo's tab, the quantity has been increased.

The Barcode scanner returns the barcode value + a LF and is working as expected e.g. in an Editor.
Tested with a local installation and also odoo 8 runbot build 22605-8-0-bc38c3.

I'd appreciate any ideas.

with kind regards,
Sven

**Comment by Yenthe666** [comment]
Hi @svenpetersen ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
