### ISSUE TITLE
[V10] SO stuck in locked status

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#31441]
Impacted versions: V10

Current behavior: A Sales Order got stucked. It is in fully invoiced and payed status. Still it wont disappear. I can not unlock it either.

Expected behavior: Sales Oder shall disappear from the list.

Video/Screenshot link (optional):
![kepernyokep errol 2019-02-26 16-29-24](https://user-images.githubusercontent.com/27618042/53424997-88aee200-39e4-11e9-9bed-65de78562252.png)
![kepernyokep errol 2019-02-26 16-29-02](https://user-images.githubusercontent.com/27618042/53425010-8f3d5980-39e4-11e9-9f3f-fccca847f612.png)

**Comment by pedrobaeza** [comment]
What do you mean by "Stucked"?

**Comment by Yenthe666** [comment]
@pedrobaeza he is talking about the "Locked" status. @nagybal somebody in your company manually locked this sale order though.

**Comment by pedrobaeza** [comment]
But what is the problem with that?

**Comment by Yenthe666** [comment]
in my opinion, nothing. Default Odoo behaviour if you work with locked orders.

**Comment by nagybal** [comment]
I can not cancel it because it is locked! (see screenshots above)
I can not delete it because the EM pops:
> You can not delete a sent quotation or a sales order! Try to cancel it before.

**Comment by pedrobaeza** [comment]
Although not locked, you won't be able to cancel it if the picking is validated, but yes, on v10, if a SO is locked, you can't unlock it. This has been solved for v11, where an "Unlock" button is available, but I don't think this is going to be included in v10.

**Comment by nagybal** [comment]
v10 is great for sake of stability but I do not understand these unsolvable bugs :face_with_head_bandage:

**Comment by Yenthe666** [comment]
Yeah this is not possible in V10 sadly. You could backport the solution from V11 to V10 to solve this issue. Closing as it is known behaviour and it won't be changed in an almost phased out Odoo version.
