### ISSUE TITLE
EasyPost option 'label_date' required during rate request

### ISSUE THREAD

**Issue by waterproau** [odoo/odoo#31448]
Impacted versions: Odoo 12 Enterprise

Sorry for posting an Enterprise Issue here. However, I can view the Enterprise Repository, but cannot report issues there. I suspect I don't have permission to do so. Can someone please move this issue to the Enterprise Repository for me?

ISSUE:
Some EasyPost carriers (e.g CouriersPlease) will not pass rates back, unless the rate request contains option 'label_date'.

EasyPost support have confirmed this as per below response:

> I checked our logs of what CouriersPlease passed back to us more generally, and I see that within a few milliseconds of order_aced4a6c7a9d40a7b01c331a35fe10b6 being created (the last order create on that carrier account), we'd received a message from CouriersPlease back separately: errors: ['shipment.options.label_date: Required']

To fix this issue. The following changes in bold were made to our server. It may be a good idea to implement this fix or similar fix to Enterprise Code.

[](https://github.com/odoo/enterprise/blob/12.0/delivery_easypost/models/easypost_request.py)

Line 200
 **import datetime**
        shipment = {
            'order[shipments][%d][parcel][weight]' % shipment_id: weight,
            'order[shipments][%d][options][label_format]' % shipment_id: label_format,
            **'order[shipments][%d][options][label_date]' % shipment_id: datetime.datetime.today()**
        }

**Comment by pedrobaeza** [comment]
Please publish a ticket in odoo.com/help instead.

**Comment by waterproau** [comment]
A ticket was already raised at odoo.com/help on 22/02/19. I received a response this morning requesting access to our server for investigation. However, a fix had already been implemented, hence why I'm posting the problem/solution here.

I'll respond to the Odoo ticket and perhaps request they open a new issue on the Enterprise Repository, so this one can be closed.

FYI - I left the link for file requiring change out of my original post. Again solution is mentioned below in bold with link to file:

https://github.com/odoo/enterprise/blob/12.0/delivery_easypost/models/easypost_request.py

Line 200
**import datetime**
shipment = {
'order[shipments][%d][parcel][weight]' % shipment_id: weight,
'order[shipments][%d][options][label_format]' % shipment_id: label_format,
**'order[shipments][%d][options][label_date]' % shipment_id: datetime.datetime.today()**
}

**Comment by pedrobaeza** [comment]
OK, thanks for the explanations. Then I close this one as specified.

**Comment by sle-odoo** [comment]
@amoyaux can you double check? i can't see the provided fix in v12

**Comment by amoyaux** [comment]
@waterproau Thanks for the information. It will be added in enterprise code

**Comment by waterproau** [comment]
> @waterproau Thanks for the information. It will be added in enterprise code

Sure thing! Glad I can help.

**Comment by avg-odoo** [comment]
Additional comment provided by @waterproau in support ticket : 1944080

Please note, I provided an incorrect link for Predefined_Packages.
Missing StarTrack Predefined_Packages can be found at:
https://www.easypost.com/docs/api#predefined-packages
and should be added to the following json file:
https://github.com/odoo/enterprise/blob/12.0/delivery_easypost/static/data/packagings_by_carriers.json
I haven't checked if any other carrier Service Levels and Predefined Packages are missing other than StarTrack and CouriersPlease.
