### ISSUE TITLE
 [BUG] test_testing_utilities: Recursive o2m/m2o fields

### ISSUE THREAD

**Issue by smetl** [odoo/odoo#31458]
Steps to reproduce:

Make a model having both a one2many & many2one to itself.

Current behavior:

RecursionError when using the Form view emulator even both fields are readonly.

branch adding a test depicting this issue:
https://github.com/odoo/odoo/compare/master...odoo-dev:master-form-recursive-o2m-las

**Comment by xmo-odoo** [comment]
ping @svs-odoo

**Comment by smetl** [comment]
@xmo-odoo Thanks!
