### ISSUE TITLE
Root user and all inactive users receive email notifications no matter of notification_type on preference

### ISSUE THREAD

**Issue by digitalsatori** [odoo/odoo#31481]
Impacted versions: tested on V12

Steps to reproduce:

Create or validate any invoice

Current behavior:
send notification  email to OdooBot(root)

Expected behavior:
No email sending (as the OdooBot is default to "inbox" for "notification_type", ideally no notification should be generated for OdooBot or disabled users)

Video/Screenshot link (optional):

I think the regression was introduced by this commit: #28730

@tbe-odoo @tde-banana-odoo @KangOl The changes there does not looks correct, because notification works on `res.partner` not on `res.users`. When you filtered out the inactive users in the query, it only makes the `users.notification_type` hence `notif` value to Null and subsequently the notification type will become `email`.

The consequence of this change is that the system will generate **email notification** for `root` user (and all `inactive` users) for the subscribed activities.

**Comment by digitalsatori** [comment]
OPW-1947150

**Comment by tanghulu0608** [comment]
I have the same issue

**Comment by tbe-odoo** [comment]
Hello guys, I have made a different patch.


What do you think about this one => http://pastesha.re/gJTJ?diff

**Comment by digitalsatori** [comment]
Thanks for the fix. Looks good to me.

**Comment by tbe-odoo** [comment]
PR fixing this issue => https://github.com/odoo/odoo/pull/31734

**Comment by digitalsatori** [comment]
Thanks. I'm closing this issue
