### ISSUE TITLE
[8.0] Check procurement is not working

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#3150]
Sorry for repeat it again but jco-odoo closed the issue 3141 without an answer.
If it is not a bug, why the button check of procurement is not assigning the moves when they are in stock ??
The description of procurement_git module says:

"If you install this module, you will not have to run the regular procurement
scheduler anymore".

When i run the scheduler the moves of procurements are assigned when possible. But check a individual procurement doesn't assign the moves, so procurement_git is not doing his work.
When i create a sale orede, user is forced to check availability or run ALL the procurements. I think this is very bad.
I think the button check of procurement must assign the moves if we have availability of them in stock.
¿It is a bug?, if not, why in odoo 8 we can check availability automatically when installing procurement_git or why when i press the check procurement button the related picking is not assigned??

**Comment by Yenthe666** [comment]
Hi @javierjcf ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
