### ISSUE TITLE
[11.0] tuple index out of range when compare two products in ecommerce

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#31517]
**Impacted versions:**
11
**Steps to reproduce:**

1. Create attribute with create_variant = false
2. Create two values to this attribute
3. Create a product with this attribute and add its two values.
4. Add other attributes
5. Compare product with other product in shop

**Current behavior:**
Error: tuple index out of range 
![desktop screenshot 2](https://user-images.githubusercontent.com/17258001/53596706-1c1c1a80-3b7f-11e9-983c-fe0838827a0d.png)

**Expected behavior:**
Comparison of the two products

[Video/Screenshot link (optional):](https://youtu.be/Coxpz4EgYoo)

**Comment by nle-odoo** [comment]
Hello,


Thanks for the report, this should be solved with this change in 11.0:
 https://github.com/odoo/odoo/commit/fa4552926c

Regards.
