### ISSUE TITLE
[ALL] base: Can't use new GeoIP's database, as legacy is no longer available

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#31514]
### Impacted versions:
All

### Steps to reproduce (1):
Try to:
```shell
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz \
&& gunzip GeoLiteCity.dat.gz \
&& mkdir /usr/share/GeoIP/ \
&& mv GeoLiteCity.dat /usr/share/GeoIP/
```

### Current behavior (1):
404, as the legacy database is no longer available

### Steps to reproduce (2):
```shell
wget --quiet http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -O /tmp/GeoLite2-City.tar.gz \
    && mkdir -p /usr/share/GeoIP \
    && chown -R odoo /usr/share/GeoIP \
    && tar -xf /tmp/GeoLite2-City.tar.gz -C /tmp/ \
    && find /tmp/GeoLite2-City_* | grep "GeoLite2-City.mmdb" | xargs -I{} mv {} /usr/share/GeoIP/GeoLite2-City.mmdb \
    && pip --quiet install GeoIP
```

### Current behavior (2):

```2019-02-28 17:39:13,469 1 WARNING odoo odoo.addons.http_routing.models.ir_http: Cannot load GeoIP: Invalid GeoIP database: '/usr/share/GeoIP/GeoLite2-City.mmdb'```

### Expected behavior:
A functional Geolozalization if the legacy database from Maxmind is no longer available

--

**Comment by pedrobaeza** [comment]
Do you have an updated path with a valid one?

**Comment by gustavovalverde** [comment]
Even though it's a documentation issue, it works using `GeoIP2` instead of the `GeoIP`. Where in the documentation should this go (maybe I could do a PR including this)

**Comment by pedrobaeza** [comment]
Can you point where in the documentation points to this?

**Comment by gustavovalverde** [comment]
It's not in the documentation, just in the code: https://github.com/odoo/odoo/blob/8f4b98e67fe49516c0c830524de351db67c58357/addons/http_routing/geoipresolver.py#L10

**Comment by Yenthe666** [comment]
Honestly, if this import fails it should write a warning in the logs. First one for the `geoip`:
`_logger.error('Failed to import the dependency "geoip", we'll try the "geoip2" dependency now.')`

Then a second one for the geoip2:
`_logger.error('Failed to import the dependency "geoip2".')`

@odony what do you think? Would such a PR be accepted?

**Comment by pedrobaeza** [comment]
@Yenthe666 definitively it shouldn't be an error logger, as this will break all CIs that parse log text looking for `ERROR` (like OCA Travis), and not sure about a warning.

**Comment by Yajo** [comment]
> not sure about a warning

Yes, it'd break OCA too, unless of course the dependency is added in the base image.

**Comment by Yenthe666** [comment]
@pedrobaeza yeah sorry I've copied over an example from somewhere, it should have said _logger.warn but you're right that it'll also make builds show the warning.. I didn't think about that part. I wonder if there is an option to only write a log if two imports fail as then it is a justified warn/error in the logs.
