### ISSUE TITLE
[IDEA] new json controller type

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#31516]
Hello,

I've an idea for a new json controller type. This new type works the same way as the current one, but it doesn't inject the [Odoo jsonrpc data](https://github.com/odoo/odoo/blob/master/odoo/http.py#L604).

Why do this you may ask, well if we want create a JSON API controller, the json controller will inject the jsonrpc data and to remove it we would need to patch (or monkey patch) Odoo.

What do you think about this? If you think that is a good idea, I can create a PR with the changes.

Best Regards,
Hugo Rodrigues

**Comment by pedrobaeza** [comment]
What is the aim of this?

**Comment by hmrodrigues** [comment]
> What is the aim of this?

For example, if you want a JSON endpoint to be used by a external program. Sometimes you can't force the external program to not pass the Content-Type header, so using a http controller doesn't work since Odoo forces a json controller when the header is set.

I know that there's a OCA module to create REST endpoints, but it would be nice to have the same controller logic with these _raw_ json controllers

**Comment by pedrobaeza** [comment]
I personally don't see this useful. If you need it for a very special case, then you can add a module doing it, but not something for the core.

**Comment by Yenthe666** [comment]
To me it seems rather specific & custom development too honestly. @JKE-be can I ask you to make the decision for this idea please?

**Comment by hmrodrigues** [comment]
> To me it seems rather specific & custom development too honestly. @JKE-be can I ask you to make the decision for this idea please?

Yes, this idea came from a custom development of two (independent) modules. Since I needed the same feature for two different things, I thought maybe other people also had the same requirement, so I posted the idea to check if people actually need the feature or not.

**Comment by pedrobaeza** [comment]
Isn't better to add a community module with that feature?

**Comment by hmrodrigues** [comment]
> Isn't better to add a community module with that feature?

The problem is the controller type validation on [http.py](https://github.com/odoo/odoo/blob/master/odoo/http.py#L507). To bypass that the module would need to monkey patch Odoo and reimplement the method. That way any fix/improvement in Odoo will be ignored

Same thing on the [response builder](https://github.com/odoo/odoo/blob/master/odoo/http.py#L602).  A monkey patch is needed to chance the response in case of a _raw_ json controller

**Comment by pedrobaeza** [comment]
You have post_load and register_patch for these things AFAIK.

**Comment by hmrodrigues** [comment]
> You have post_load and register_patch for these things AFAIK.

Hmm, I didn't know about those, but that doesn't avoid the need for the monkey patch.

**Comment by xmo-odoo** [comment]
Duplicated / replaced / superseded by #32035.
