### ISSUE TITLE
Useless "Validate closing & Post Entries" when many orders inside POS session

### ISSUE THREAD

**Issue by mardisiaw** [odoo/odoo#31548]
Impacted versions: 12.0 CE

Steps to reproduce & Current behavior:
In POS Session, It takes a long time to Validate Closing & Post Entries when the session had more than 1000++ orders. (Tested around 15++ minutes, but sometimes failed).

Is there any solutions for this? I've tried to patch with:
"[FIX] pos: fast closing for large pos session #24605", but it still the same problem.

**Comment by mart-e** [comment]
Hello,

We are aware the pos validation is slow, especially when you got a lot of orders.
For instance, in master c0222efd1393bf88720c56799ad8e6 we have added a message to remind users that they need to close their sessions frequently.
I wish I could give you a good solution for that. You should try to close it overnight with local patch #24605 but the reconciliation of thousands of records is slow, we won't be able to change that easily.

**Comment by pedrobaeza** [comment]
We should close this then as answered and won't fix, isn't it?

**Comment by mart-e** [comment]
You are right, I doubt we will change that in stable. Maybe in master we will be able to improve the reconciliation.
