### ISSUE TITLE
[OE][Wish] web: button div : two line option, sequence attribute

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#31546]
Dear @mge-odoo @ged-odoo 

On some view (like contact or product), there are lot of button in the button box. After 7 button, all other button are in the more button. 7 is not enought, it could be nice to have an option to allow two lines.
Other idea : implemante a sequence attribute to order easely the button, xpath inside is too arbritary.

![image](https://user-images.githubusercontent.com/16716992/53678540-bdf75080-3cc0-11e9-9fb1-2b3a869ae2d5.png)

Regards

cc @sla-subteno-it

**Comment by pedrobaeza** [comment]
A sequence would require to have some JS for ordering the buttons after loading them, so it would some kind of black magic.

About the 7 shown buttons, it's a design decision of the enterprise backend theme. You can tweak it or use another backend theme.

Any way, I let this opened for other opinions.

**Comment by Yenthe666** [comment]
Ehh I don't see a lot of benefit in this. If you want to have more and have two bars - as one of your suggestions - you can just do it in custom code? I think that if we start allowing to make these kind of things configurable it'll quickly spiral out of control. CC @mart-e

**Comment by mge-odoo** [comment]
Hi @fmdl 

Thank you for your feedback ! However, as @pedrobaeza and @Yenthe666 mentioned, your concern is a design decision that has been taken for enterprise. A small customization on `form_renderer.js` that overrides `_renderButtonBox` will let you do whatever you want with it.

Morever, if you want a particular button to be displayed in a particular position, you can just modified the corresponding xpath to be more precise than just "inside the buttonbox".

Concerning the sequence, it might seems like a good idea but it would break the logic of inheritance defined with xpaths.

Regards.

**Comment by fmdl** [comment]
@mge-odoo thank for the tips for the customization.
