### ISSUE TITLE
sale order does not  generate stock picking odoo12

### ISSUE THREAD

**Issue by Adasquirrel** [odoo/odoo#31544]
Impacted versions:
sale order does not  generate stock picking . odoo 12 

We need sale order merge into one PO,then change change Propagation of Procurement  to  Leave Empty from Propagate.
Steps to reproduce:
MTO ,change Propagation of Procurement  to  Leave Empty
Current behavior:
confirm sale order,but it does not  generate stock picking for this sale order.
Expected behavior:
create a new stock picking ,like  Propagation of Procurement  is Propagate
--

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but your English is not very understandable. For what I deduce, until you don't confirm the purchase order, you don't get the delivery order. That's the intended behavior.

**Comment by Yenthe666** [comment]
Hi there,

Indeed, you do not get a delivery order untill the purchase order is confirmed. This is by design.
If we missed something - or misunderstood - then please don't hesitate to comment back with more feedback.

Regards,
Yenthe
