### ISSUE TITLE
Performance of Partner Import

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#31549]
Impacted versions: 12.0

Steps to reproduce:
Import a csv file of 18,000 partners to create, 17,999 with parents (referenced via xml_id, which I know slows a little, but thats maybe the first 20 mins, all other references are database ids).

Current behavior:
`2019-03-02 23:37:21,709 87 INFO master werkzeug: 172.16.24.48 - - [02/Mar/2019 23:37:21] "POST /web/dataset/call_kw/base_import.import/do HTTP/1.1" 200 - 667238 742.122 10061.288`
So 2.8 hours? - I don't know exactly, it failed first time, so upped cpu-time limits, started it and went to the beach.

This particularly server is bare metal, solely dedicated to this task with 128gb RAM, 40 cores. Postgres properly tuned although it never goes over 1% CPU.

Expected behavior:
An import of 24,000 records without parent ids takes around 10 minutes, I guess I'm saying there are clearly performance issues somewhere in those computed fields if it can only manage a little over 100 records/minute on average which might be worth looking at. Pretty vanilla file as well, no images, only 4.7MB in size.

Video/Screenshot link (optional):

**Comment by moylop260** [comment]
What fields are you filled?
What modules you have installed (community, enterprise, custom)?

Maybe, you are interesting to see the following case:
https://m.youtube.com/watch?v=FbW0Wu5buY8

**Comment by gdgellatly** [comment]
Its just vanilla enterprise plus a couple of booleans, couple of text fields and an int field store the original id. But what does it matter? 

Without parents, identical columns set, 10 minutes, with parents 2.8 hours and the other fields have no dependence on parents. All other relational fields are referenced directly by id, plus all those are resolved within 20 minutes.  It is the creation thats killing it, and specifically I imagine its all the fields sync that goes on. There are no sales, invoices, account moves or stock moves.

**Comment by xmo-odoo** [comment]
@gdgellatly could you say what modules you have installed on the system and provide sample data? A preliminary check does show a significant slowdown when importing partners with a parent_id (compared to an other less critical m2o like country_id) but nowhere near the extent you're reporting. "Vanilla enterprise" doesn't really mean much.

**Comment by gdgellatly** [comment]
@xmo-odoo I can, but not just yet, I'd need to anonymise it and go live is 8 days away so no time. But just the usual stuff sales, purchase, account, stock, project.

Interestingly I saw your PR #31804, pricelist_id wasn't one of the fields because its multicompany, plus pricelist is a synced field so doesn't make a lot of sense on a partner with a parent_id. 

I did pricelists with a back to back shell command over 130,000 partners and it was done in minutes, although I guess only 24,000 were parents.

**Comment by xmo-odoo** [comment]
@gdgellatly 

> Interestingly I saw your PR #31804, pricelist_id wasn't one of the fields because its multicompany, plus pricelist is a synced field so doesn't make a lot of sense on a partner with a parent_id.

If you have `product` installed (which you probably do given the modules you've listed) and the partner being created has a parent, that field will get sync'd. The synchronisation of commercial fields and addresses is the one big difference between having and not having a parent_id, and in my tests property_product_pricelist had a pretty outsized impact on the profiling. Though admittedly my test case is pretty artificial (I'm importing 10k partners who all have the same parent).

**Comment by gdgellatly** [comment]
@xmo-odoo 

Yes, I figured it was the syncing of commercial fields, given postgres was idle My file batch size was 18,000 records all with parent_ids. 

At the time of import, there were no pricelist records set, precisely because some partners have different pricelists in different companies, although I guess it still created the property records with the default for whichever company I imported from.

I imagine the 2 payment term fields suffer the same issue.

**Comment by xmo-odoo** [comment]
> At the time of import, there were no pricelist records set, precisely because some partners have different pricelists in different companies, although I guess it still created the property records with the default for whichever company I imported from.

IIRC there's always at least one pricelist somewhere, and regardless it's going to go look for one [which would be the hard work](https://github.com/odoo/odoo/blob/5b32f1b5cdbe71301896b251b7a0a4b81601a46e/addons/product/models/product_pricelist.py#L317-L349) as despite what its name hints the field [specifically isn't a property field](https://github.com/odoo/odoo/blob/a12c4d284c2f65c59fe0b12c62442ac55ed40252/addons/product/models/res_partner.py#L11), and gets invalidated all the time during the import because it depends on country_id, and updating country_id is the step right after copying the commercial fields (and since it's not a stored field it gets invalidated for all records).

**Comment by xmo-odoo** [comment]
@gdgellatly and if the data is "only" "business-sensitive" it might be possible to just encrypt it (using e.g. pgptools) so it's safe during transit.

**Comment by xmo-odoo** [comment]
@gdgellatly or maybe upload it to something like https://send.firefox.com, and send me the URL via a private channel (e.g. email).

**Comment by gdgellatly** [comment]
@xmo-odoo Thanks for looking at this. It is kind of a commercial sensitivity issue, but moreover, it is just difficult. These particular files are from a v7 migration with custom xml_ids which are created outside of the import process, so none of the imported parent records have any xml id in the import files. 

Obviously I could fix it, but really then it is no different to just creating a random set of data.

**Comment by xmo-odoo** [comment]
@gdgellatly sure, I get it.

> Obviously I could fix it, but really then it is no different to just creating a random set of data.

Maybe, maybe not, there could be other odd fields or corner cases in your data which we'd missed. Either way if you want to test #31876 it *should* improve performances.

**Comment by xmo-odoo** [comment]
@gdgellatly mind checking #31876 to see if it improves performance (and ensure it doesn't break anything) on your data set?

**Comment by gdgellatly** [comment]
@xmo-odoo I'm 4 days in to a new site launch with that data, so working around the clock fixing initial issues. Mid next week is probably earliest I can try but I've still got all the files.
