### ISSUE TITLE
Translation partially loaded 

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#31557]
Impacted versions:

Odoo 11.0-20190128 (Community Edition) 

Current behavior:
We added a view to res.partner, with some terms who need translation. Initial language is English, and we translated them in french.

After reload the french language, only some terms are displayed in French. The fields labels are in French, but the group titles are still en English. After looking in "Translated terms", I can find the title not displayed en French. So, Odoo know them but didn't use them.

I checked the browser cache and language, the res.parter language, and the Odoo log: Nothing strange, nothing wrong, no error.

We have the same problem with officials Odoo apps: some terms are translated, in the UI, some not. But all are known in the "translated terms" part.

**Comment by pedrobaeza** [comment]
What do you mean by "group titles"? Some screenshots will help.

**Comment by sebastienhasa** [comment]
![capture d ecran du 2019-03-04 11-07-33](https://user-images.githubusercontent.com/48090545/53726738-e8870c00-3e6e-11e9-9aa3-76d243843f1f.png)

Number of Characters are in English instead of French CH, but if I check the translated terms:

![capture d ecran du 2019-03-04 11-14-31](https://user-images.githubusercontent.com/48090545/53726786-06ed0780-3e6f-11e9-93aa-4ae5c7287a57.png)

**Comment by sebastienhasa** [comment]
And the XML for the group in this view are:
```xml
                    <group name="chars_lenght" string="Number of Characters">
                        <group>
                            <field name="password_length"/>
                        </group>
                    </group>
```

**Comment by pedrobaeza** [comment]
Is this used in local with `--dev` option enabled?

**Comment by sebastienhasa** [comment]
command: `odoo --proxy-mode --dev=all --test-enable`

**Comment by pedrobaeza** [comment]
Then you have your answer :wink: Remove `--dev=all` for having all translations loaded. If not, views are loaded on the fly and thus translations are not loaded for them.

**Comment by sebastienhasa** [comment]
Thank you.

Can we have a note in the official documentation, in "Translating Modules" and in "Command-line interface: odoo-bin" section?

**Comment by pedrobaeza** [comment]
Feel free to do it through a PR :)

**Comment by sebastienhasa** [comment]
Is it all option of `--dev` who cause this prolem, or only `all` and `xml`?

**Comment by pedrobaeza** [comment]
Yeah, the 2 you have exposed, which loaded views on the fly.

**Comment by sebastienhasa** [comment]
Did I need to sign the CLA for this contribution

**Comment by pedrobaeza** [comment]
Yes

**Comment by sebastienhasa** [comment]
My company is an Odoo partner, is it necessary or do we already signed this document? (I'm not the one who manage it)

**Comment by pedrobaeza** [comment]
It seems not, as the PR indicates it.
