### ISSUE TITLE
Website drop down is ill formatted 

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#31576]
Impacted versions:
Current odoo.com website

Description:
When I click my user name on the website the drop down is not displayed correctly.
My screen resolution is 1920x1080

Screenshot:
![image](https://user-images.githubusercontent.com/20386024/53787021-19764800-3f26-11e9-83c1-d657f5432545.png)

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by andriisem** [comment]
<img width="1436" alt="screen shot 2019-03-05 at 10 40 52 am" src="https://user-images.githubusercontent.com/2995736/53791931-3a916580-3f33-11e9-9316-bd1a870ea7b0.png">

also with the list of languages have trouble in french

**Comment by rdeodoo** [comment]
Hi @obayit has this been fixed?
It is odoo.com related and I don't see this issue anymore.

**Comment by ubay-abdelgadir** [comment]
I only noticed the issue on odoo.com website itself.
But the drop down list is not cut anymore. Thanks!

But for some reason when I zoom the page for 125%, using chromium on ubuntu 18. The menu text looks fuzzy (looks like it is stretched).
![image](https://user-images.githubusercontent.com/48674897/54586243-20708080-4a25-11e9-9408-d4412ba7f324.png)

**Comment by obayit** [comment]
I only noticed the issue on odoo.com itslef.
The menu text is not cut anymore, thanks!

But for some reason the menu text looks fuzzy when I zoom the page to 125% (using chromium, on ubuntu 18, a 1080 monitor)
![image](https://user-images.githubusercontent.com/20386024/54586739-a3460b00-4a26-11e9-84b1-bc1c88637d4f.png)
