### ISSUE TITLE
Odoo client error

### ISSUE THREAD

**Issue by AlmaG2018** [odoo/odoo#31572]
Impacted versions: 12.0

Steps to reproduce: look for a vendor, select one from the list

Current behavior: Shows error screen

Expected behavior: Load vendor data

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/45275955/53772185-1b4ef580-3eab-11e9-9cb2-e6a98aa3ff4a.png)

**Comment by Yenthe666** [comment]
Hi,

This seems to work fine in the latest Odoo 12.0.
Can you please try to reproduce it on the latest runbot (at runbot.odoo.com) or update your Odoo to the latest version and try again?
If you can still reproduce it can you please add a video?

Regards,
Yenthe

**Comment by AlmaG2018** [comment]
I got my Odoo instance on premise, could you tell me how can i update it? Thank you so much.

**Comment by AlmaG2018** [comment]
I´ve tried with the upgrade page, but they answered whit this: 

> Detected database version is 12.0 and therefore can not be upgraded to version 12.0. 

Aditionally, i can´t access to runbot, i need an invitation to use that database.

Thanks for your answer.

**Comment by Yenthe666** [comment]
Hi,

You shouldn't upgrade your Odoo but update it. if you installed through Github you should do a git pull.
Runbot is always available by default with the user "admin" and the password "admin".

**Comment by AlmaG2018** [comment]
Thank you Yenthe, i'm going to check for the git pull on my installation.
