### ISSUE TITLE
Blog posts shown in one column only in Grid View

### ISSUE THREAD

**Issue by mettadipa** [odoo/odoo#31574]
**Impacted versions**: Odoo V12

**Steps to reproduce:**
- Go to blog
- On the top menu: Go to Customize -> Turn on Grid View

**Current behavior:**
- All blogs posts are shown in one column

**Expected behavior:**
- Blogs posts should be shown in two columns as in previous versions

**Screenshot**
Odoo 12: 
![one_colum_grid](https://user-images.githubusercontent.com/10968690/53777368-b38cbf00-3f2b-11e9-9ac2-4e9b1cb87540.png)

Odoo 11 (expected): 
![odoo_11_two_columns_grid](https://user-images.githubusercontent.com/10968690/53777397-ce5f3380-3f2b-11e9-832a-06ee84448726.png)

**Comment by JKE-be** [comment]
Thank for the feedback, it has been fixed

**Comment by mettadipa** [comment]
@JKE-be @Yenthe666 Please reopen the issue. The new fix has created more bugs:

1. If you have 3 blog posts + right sidebar. Here is how it looks (the sidebar area becomes messy):
(Screen resolution: 1280px 800px)

![3blogs-sidebar](https://user-images.githubusercontent.com/10968690/54138151-840d1380-4451-11e9-9c9e-b279cd18b5c2.png)

2. If you have 3 blog posts + no right sidebar. Here is how it looks (too much left-margin and no right margin. The 3 posts should be centred instead):

![3blogs-no-sidebar](https://user-images.githubusercontent.com/10968690/54138236-a6069600-4451-11e9-8626-f30d183ca5f4.png)

3. If you have 4 blog spots, all posts will be in a row:

![4blogs-no-sidebar](https://user-images.githubusercontent.com/10968690/54138364-e49c5080-4451-11e9-90be-7f0749f607fd.png)

**Comment by Yenthe666** [comment]
@JKE-be sorry still looks a bit off 😉

**Comment by Moto017** [comment]
I got this same issue.  fixed with adding class="d-flex flex-wrap"

**Comment by JKE-be** [comment]
oups my bad, I check it asap

**Comment by mettadipa** [comment]
@JKE-be @Yenthe666 Did you have time to look into the issue? 
Many thanks.

**Comment by rdeodoo** [comment]
I think it has been fixed with https://github.com/odoo/odoo/pull/31870
Can you confirm
