### ISSUE TITLE
[ODOO 11 ENTERPRISE] Consumable Items are not listed in journal as it is sold as Stock Interim Account (Delivered)

### ISSUE THREAD

**Issue by notalentgeek** [odoo/odoo#31590]
We are using Odoo Enterprise 11 and we have this case:

We want to have a non-stockable item in Odoo consists of stockable items:

For example:

Surprise Milk Pack will consist of:
1 Chocolate Milk
3 Grape Milk

Every 1 Surprise Milk Pack sold will deduct 1 Chocolate Milk and 3 Grape Milk from the inventory. And in the jurnal there should be at least:

AR
VAT Out
Change in Inventory
Stock Interim Account (Delivered)
Sales

===

At this point I implement this with the help of Manufacturing app to create Bill of Material.

Surprise Milk Pack is set as consumable (also listed there as a Bill of Materials) as we don't want to keep track of the stock. As soon as there is an order of Surprise Milk Pack we will grab 1 Chocolate Milk and 3 Grape Milk straight from our warehouse and assemble Surprise Milk Pack. We don't want to specifically allocate 1 Chocolate Milk and 3 Grape Milk straight up front for Surprise Milk Pack.

Chocolate Milk is set as stockable.
Grape Milk is set as stockable.

Now what happen now is that for every Surprise Milk Pack sold there are only these accounts in the jurnal:

AR
VAT Out
Change in Inventory
Sales

We need to have Stock Interim Account (Delivered) to be listed there as well (Credit) as the stock valuation decreases as soon Surprise Milk Pack bought.

How we can achieve this?

**Comment by pedrobaeza** [comment]
I would say the requirement is to have it as stockable the product pack.

**Comment by notalentgeek** [comment]
> I would say the requirement is to have it as stockable the product pack.

I see. But what if we don't want to reserve the stock? We need to keep our stock as dynamic as possible. We need to only assemble Surprise Milk Pack when the order comes.

**Comment by pedrobaeza** [comment]
Then do it MTO (make to order).

**Comment by notalentgeek** [comment]
> Then do it MTO (make to order).

Alright, thank you so much. This makes my day!
