### ISSUE TITLE
Odoo v12: SUPERUSER_ID is not 1 and this leads to issues

### ISSUE THREAD

**Issue by b-kannan** [odoo/odoo#31606]
Impacted versions: v12

Steps to reproduce:
1. Login as administrator (has id=2 and odoobot user has id=1)
[Ensure payment acquirers are available]
[odoo/odoo/__init__.py defines SUPERUSER_ID as 1]
2. Go to Sales/Configuration/Settings
3. Check 'Online Payment' option

Current behavior:
Get an error "For this kind of document, you may only access records you created yourself ?"

Expected behavior:
Since the user is adminstrator account, this should be allowed.

**Comment by moylop260** [comment]
Do you check the ACL groups of your “admin” user?

Maybe you need assign it a extra permission since that now admin is not a Chuck Norris user

**Comment by luisg123v** [comment]
@b-kannan   
If I log-in as administrator (ID=2) I'm not able to replicate your issue, I'm able to mark and unmark the checkbox and save the changes.

On the other hand, I think the title of you issue is wrong, `SUPERUSER_ID` is actually defined as `1`.

Also take into account that the admin user (id=2) should not have access to everything only by being the administrator, it should be added to the required groups. Only the system user should have all privileges, because it needs them to create records, load data, etc.

**Comment by b-kannan** [comment]
@luisg123v : I was able to analyze it further. There was another user in the system (user_id=7) that had privileges to update accounting configuration. As a result of this, the res.config.settings records were owned by user_id=7.

Since administrator (user_id=2) is not the owner of those records (userid=7), and since SUPERUSER_ID=1, the administrator can no longer edit the configuration.

The issue here is not that administrator has id=2 but that the administrator user has now been relegated to a regular user and not a superuser. 

Assigning additional permissions to the administrator accounts beats the purpose of defining it as an administrator.

If odoobot user (user_id=1) needs to be a superuser, then the SUPERUSER_ID should be replaced with SUPERUSER_IDS = [1,2] which will allow administrators to make necessary configuration changes. Other solutions are welcome too (just not adding additional permissions to administrator account please).

**Comment by gdgellatly** [comment]
No. Just enter debug mode as administrator and choose become super user.

**Comment by Yenthe666** [comment]
Nope, the diverge from administrator to the superuser was with a clear purpose: separate the behaviour of the two and it does now. This behaviour won't be changed for sure. As @gdgellatly said, just switch to the super user from debug mode (as it is intended)

**Comment by b-kannan** [comment]
@gdgellatly : I believe "Become Superuser" is possible only to users with "Settings" access. Tested and solution is acceptable. Thanks
