### ISSUE TITLE
Post category pager options & positions

### ISSUE THREAD

**Issue by mettadipa** [odoo/odoo#31603]
Impacted versions: v11, v12

**Steps to reproduce:**
- Try to find the option to set up the number of posts per category page

**Current behavior:**
- No UI option, the only way to find out the number of posts per cat page is to look at the code
- After 20 posts, the pager will appear, but on the top right (see the screenshot)

**Expected behavior:**
- More visible options to control pager for post category page
- Better position for the pager: bottom left/center could be much better.

**Screenshot:**
![blog-pager](https://user-images.githubusercontent.com/10968690/53818447-a824ac80-3f9a-11e9-85e0-9ebd01565831.png)

**Comment by Yenthe666** [comment]
@mettadipa it is not configurable through the frontend by design.

**Comment by mettadipa** [comment]
@Yenthe666 This is an improvement request:

- Option to specify the number of posts per page (UI option, no need to fix in codes)
- Pagination should not be pulled top right like that (I don't see the good UX here)

**Comment by Yenthe666** [comment]
Yeah I'm all up for this, to me it are both good improvements. It is labelled so the right team will check it at some point.
