### ISSUE TITLE
[ODOO 11 ENTERPRISE] In assembly product (has bill of materials) how can I have the cost of assembled item derive automatically from its materials' cost?

### ISSUE THREAD

**Issue by notalentgeek** [odoo/odoo#31615]
This is follow up from the: https://github.com/odoo/odoo/issues/31590.

With the same case:

> We are using Odoo Enterprise 11 and we have this case:
> 
> We want to have a non-stockable item in Odoo consists of stockable items:
> 
> For example:
> 
> Surprise Milk Pack will consist of:
> 1 Chocolate Milk
> 3 Grape Milk
> 
> Every 1 Surprise Milk Pack sold will deduct 1 Chocolate Milk and 3 Grape Milk from the inventory. And in the jurnal there should be at least:
> 
> AR
> VAT Out
> Change in Inventory
> Stock Interim Account (Delivered)
> Sales
> 
> ===
> 
> At this point I implement this with the help of Manufacturing app to create Bill of Material.
> 
> Surprise Milk Pack is set as consumable (also listed there as a Bill of Materials) as we don't want to keep track of the stock. As soon as there is an order of Surprise Milk Pack we will grab 1 Chocolate Milk and 3 Grape Milk straight from our warehouse and assemble Surprise Milk Pack. We don't want to specifically allocate 1 Chocolate Milk and 3 Grape Milk straight up front for Surprise Milk Pack.
> 
> Chocolate Milk is set as stockable.
> Grape Milk is set as stockable.
> 
> Now what happen now is that for every Surprise Milk Pack sold there are only these accounts in the jurnal:
> 
> AR
> VAT Out
> Change in Inventory
> Sales
> 
> We need to have Stock Interim Account (Delivered) to be listed there as well (Credit) as the stock valuation decreases as soon Surprise Milk Pack bought.
> 
> How we can achieve this?

The solution there was to set the assembly Product Template into: Product Type: Stockable and to turn-on Make to Order option. After this there is Stock Interim Account (Delivered) for every sales of that assembly product (in this case that Surprise Milk Pack). However, the cost of Surprise Milk Pack is 0 (hence the jurnal is still nominally wrong, despite the account is now recorded).

How can I have the assembly product's Cost to be taken from the sum of Costs of the element items (in this case the cost of 1 Chocolate Milk and the cost of 3 Grape Milk)?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip: see `product_extended` module.

Closing this by the reason above.
