### ISSUE TITLE
Duplicating Routes assigns duplicated route to products of original route

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#31610]
Impacted versions: 12.0 (note runbot for 12.0 was down, also tested on saas 11.3)

Steps to reproduce:

- Enable Multistep routes
- Assign Buy route to a product.
- Duplicate Buy route

Current behavior:
Duplicated route assigned.

Expected behavior:
Duplicated route not assigned, it makes zero sense to assign it. 

The only reason to duplicate a route is to edit it do something different. There is no point duplicating an existing route and keeping it identical. If you wanted to change the behavior of the existing route you would just edit it. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/53839266-f61dcc80-3ffb-11e9-8c5f-117bbceba112.png)
![image](https://user-images.githubusercontent.com/5093264/53839356-32512d00-3ffc-11e9-994d-eac8c697c5b6.png)

**Comment by Yenthe666** [comment]
@sle-odoo
