### ISSUE TITLE
[wms] there have no menu link to setup putaway strategies   

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#3163]
the problem as the title descried.  there have a workaround to complete this mission, you can setup it via  location putaway strategies selection popup window.

**Comment by clonedagain** [comment]
Yes, it feels like it would make sense to have a menu entry for this, given that there is a menu entry for all other logistic rules.

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
