### ISSUE TITLE
[12.0] Double incoterm field on account.invoice

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#31641]
Impacted versions: 12.0

Steps to reproduce:
1) Connect to runbot v12
2) In the menu "Sales > Configuration > Settings", enable the option "Incoterms"
3) In the menu "Invoicing > Customer > Invoices", open a customer invoice and go to the "Other Info" tab: you will see 2 incoterm fields !!!

![incoterms_double_v12](https://user-images.githubusercontent.com/1157917/53892818-4f522400-402d-11e9-94a6-5387d266f69f.png)

Code analysis:
The first incoterm field (**incoterm_id**) is defined in the account module, cf https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_invoice.py#L377
The second incoterm field (**incoterms_id**) is defined in the sale_stock module, cf https://github.com/odoo/odoo/blob/12.0/addons/sale_stock/models/account_invoice.py#L10

According to this code (https://github.com/odoo/odoo/blob/12.0/addons/sale_stock/models/sale_order.py#L128), the incoterm field of sale.order is copied to the second field (incoterms_id) of invoices.

I think we really need to sort this our rapidly and decide which one should "really" be used on invoices. We should at least change the form view of invoices.

**Comment by smetl** [comment]
Already fixed in master at revision:
https://github.com/odoo/odoo/commit/569a498d360b99b2a1d8e64a6e6bcc259d0910e4

We are currently working to hide the incoterm field coming from sale_stock in stable versions.

**Comment by tuomoaura** [comment]
@smetl Why would you hide the one which was set on Sale order (sale_stock)? That's what has been agreed with the customer and that's the one to keep and show in the invoice.

**Comment by smetl** [comment]
@tuomoaura As this field has been integrated to the 'account' module that is a dependency of 'sale_stock', the 'incoterm_id' field coming from 'account' is the one to keep.

**Comment by tuomoaura** [comment]
@smetl Aha, then sale_stock needs to write the value into this field.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/6233c37f1448c8e004264505ecaa282b705df7be
