### ISSUE TITLE
Sales Order Line - Delivered Quantity 

### ISSUE THREAD

**Issue by WallerZhang** [odoo/odoo#31650]
Impacted versions:
Odoo 12 Enterprise
Steps to reproduce:
1, Create SO and Product Line, that Product with MTO and BUY, Ordered Quantity like 50, 
2, Create Delivery Order after conform SO by system automaticlly, the Initial Demand Qty is 50. 
3, Create PO base on Route by system automatically, the Product Ordered Qty is 50. 
4, Confirm PO that create Reciept with Product Qty 50. 
5, do the Receipt shipment with more Qty than Ordered like 55. and Validate.
6, do the Delivery Order link to SO, change the Qty as PO received Qty (more than Ordered Qty)
7, Can not Vlidate, when Validate, the Done Qty is Zero and create back order automatically with intial Qty in Ordered Qty
8. Validate the back order with Ordered Qty.,
9. Copy the Delivery Order, change the Qty for additional Qty, that is PO Received Qty - SO Ordered Qty, and Validate
10, in SO line, the Delivered Qty is Orddered Qty + additional Qty + additional Qty.
Current behavior:
the SO Delivered Qty is Ordered Quantity + 2 * additional Qty.
Expected behavior:
the SO Delivered should be the Done Qty by delivery order. 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You can put an enterprise ticket at odoo.com/help for using paid service, as this is only based on voluntary best effort

**Comment by tanghulu0608** [comment]
@WallerZhang  hello

**Comment by sle-odoo** [comment]
I can't reproduce, at point 7) i'm able to process the 55 units.

Regards
