### ISSUE TITLE
Account Move show sum of debit (not correct in accounting context)

### ISSUE THREAD

**Issue by ahetland** [odoo/odoo#31654]
Impacted versions: all

Steps to reproduce: Create a journal with Dr. 100 Receivables, reduce the Receivable with Cr. 10 (credit sales and debit discount respectively). 

Current behavior: The account move view shows the sum of Debits (110), this is naturally correct in terms of summing the debits, but makes little sense in the context of accounting. The receivable amount is 90 and is what the accountant would expect to see.

Expected behavior:
The values presented should have meaning in its context, either the view for account moves should be removed or the view should be sensitive to its context (and show sum of receivables). 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you put an screenshot to illustrate what you mean?

**Comment by ahetland** [comment]
![img1](https://user-images.githubusercontent.com/3541706/53950639-e5895700-40cc-11e9-9e23-225edc7c1812.png)
![img2](https://user-images.githubusercontent.com/3541706/53950640-e621ed80-40cc-11e9-8365-2047e5a350ec.png)

**Comment by pedrobaeza** [comment]
OK, now it's clearer. My opinion that this is correct, as it shows the total of the column, not linked to other interpretation. You have other tools for seeing residual amounts, and you can have account moves with no payable/receivable accounts that require to check the totals of the columns.

But I let @qdp-odoo the last word about this.

**Comment by gdgellatly** [comment]
I'm with @pedrobaeza on this one. Take an extreme example (but a very common entry for accountants).

DR AR Partner A
DR AR Partner B
DR AR ...
CR AR <No Partner>.

By that logic the sum of debits would be 0. But I have no idea why you would want sum of debits = sum of Receivables, and a debit is no more to do with AR than any other account. You've added amount to the right side of the ledger, and added amounts to the left and they equal, honestly I'd find the suggestion way more confusing.

Again by that logic the following entry would sum to zero

DR Depn Expense $800,000,000
CR Accum Depn $800,000,000

However, sometimes there are cases to nett them off (especially with supplier invoices, anglosaxon and perpetual inventory), but that's precisely what you do, dedupe the lines, either manually or in code.

**Comment by ahetland** [comment]
The point is that "account move" does not have a meaningful amount, only "account move line" has meaning as here the amount is set in its context (an account). To display something that has no meaning only confuses the user and should be changed or removed.

**Comment by gdgellatly** [comment]
Only to you it has no context. For many people it is actually an important check. Imagine entering a big payroll via import, or any manual transaction, or trying to work out why a transaction isnt balancing. Those sums matter.

**Comment by pedrobaeza** [comment]
I think we don't need more feedback, and at the end, if the sums are useless for you, just ignore them.

Closing, but if someone from Odoo considers this important, feel free to reopen.
