### ISSUE TITLE
style error

### ISSUE THREAD

**Issue by mhadiahmed** [odoo/odoo#31653]
Impacted versions:
odoo 12

I have installed it from a deb pack on ubuntu server 
this error shows up after installation and creates DB in the browser

`خطأ:
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3744
تتبع الأثر:
TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at computeFloatOuterWidthWithMargins (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3744:73)
    at _adapt (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3743:461)
    at Object.initAutoMoreMenu (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3737:533)
    at Class.start (https://odoo-deal.vpstaxi.com/web/content/248-e39ae77/web.assets_backend.js:847:189)
    at Class.prototype.(anonymous function) [as start] (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3538:488)
    at https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:3683:52
    at https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:802:681
    at fire (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:796:299)
    at Object.add [as done] (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:797:467)
    at Array.<anonymous> (https://odoo-deal.vpstaxi.com/web/content/247-267e1a6/web.assets_common.js:802:649)`

I try to install sass but the seam error still on I hope to find a solution

**Comment by mhadiahmed** [comment]
sudo pip3 install libsass==0.12.3
this is the solution

**Comment by salytwo** [comment]
> sudo pip3 install libsass==0.12.3
this solution is already satisfied in my case but still I have the exact same error after installing rtlcss.

Can you help pls

**Comment by v-garcies** [comment]
> > sudo pip3 install libsass==0.12.3
> > this solution is already satisfied in my case but still I have the exact same error after installing rtlcss.
> 
> Can you help pls

Simply clean your browser's cache to resolve the issue if you have already installed libsass

**Comment by chrys-exaucet** [comment]
Hello, 

I cleaned the brower cache and installe proper version of libsass but the error kepps poping .

**Comment by abenezermb** [comment]
> Hello,
> 
> I cleaned browser cache and installed proper version of libsass ( 0.12.3 then 0.17.0) but the error keeps poping .
> 
> Odoo 14 - python 3.8 - windows 10
> 
> ```
> Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
> http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4741
> Retraçage :
> TypeError: Cannot read property 'getBoundingClientRect' of undefined
>     at computeFloatOuterWidthWithMargins (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4741:93)
>     at Class._adapt (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4740:477)
>     at later (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:142:255)
> ```

Same error persisting here. Can anyone give the fix for this problem?

**Comment by LuanNguyen4720** [comment]
> > Hello,
> > I cleaned browser cache and installed proper version of libsass ( 0.12.3 then 0.17.0) but the error keeps poping .
> > Odoo 14 - python 3.8 - windows 10
> > ```
> > Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
> > http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4741
> > Retraçage :
> > TypeError: Cannot read property 'getBoundingClientRect' of undefined
> >     at computeFloatOuterWidthWithMargins (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4741:93)
> >     at Class._adapt (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:4740:477)
> >     at later (http://localhost:8069/web/content/2484-7241e80/web.assets_common.js:142:255)
> > ```
> 
> Same error persisting here. Can anyone give the fix for this problem?

I have the same problem but after testing Odoo test tour, I found out that the odoo.sh test require the module to have "website_sale" depend.
