### ISSUE TITLE
Error when schedule an activity on a document which the user can read but can not create and write.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#31663]
Impacted versions:
12
Steps to reproduce:
I have set some record rule: saleman can read all leads, but can only create and edit their own leads. When a saleman schedule an activity on a lead which created bu other saleman, raise an error.
Current behavior:

Expected behavior:
There is a _mail_post_access setting on mail.thread. Add some setting like this on mail.activity.
Video/Screenshot link (optional):
![qq 20190307204146](https://user-images.githubusercontent.com/5561864/53957520-86056880-4119-11e9-98c5-e45af2346422.png)

**Comment by pedrobaeza** [comment]
This is something expected, as you don't have access to the object itself (write), so you can write an activity on it.

You would need to adapt code for achieving that effect, but it's not possible through that record rules.

Closing by the reasons above.

**Comment by tanghulu0608** [comment]
@pedrobaeza  I don't understand. I don't write the document,just add a actitity on it . Why need the write access ?

**Comment by gdgellatly** [comment]
Activities are part of the document, so the same write rules apply. But actually this should be feature request imo, because i think this behaviour is widely desirable and might be able to lead to stricter groups for users.
