### ISSUE TITLE
[7.0] Request Procurement will lead to wrong inventory quantity when input location rather than stock

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#3166]
Here're the steps to reproduce the issue at runbot -   

```
 1. define a new item with 'buy' supply method 
 2. define a warehouse with input location - quality control (that has a chain to stock)
```

![screenshot from 2014-10-20 10 46 02](https://cloud.githubusercontent.com/assets/3712729/4695950/84473796-5846-11e4-800c-e411ab60e80e.png)

![screenshot from 2014-10-20 10 49 06](https://cloud.githubusercontent.com/assets/3712729/4695963/be1e775e-5846-11e4-9dfd-b695a801c231.png)

![screenshot from 2014-10-20 10 49 45](https://cloud.githubusercontent.com/assets/3712729/4695969/de9ec25e-5846-11e4-9c76-6ea5dc7dc529.png)

```
3. Request Procurement  - 3 pcs
```

![screenshot from 2014-10-20 10 52 30](https://cloud.githubusercontent.com/assets/3712729/4695977/37d6ffc6-5847-11e4-9acc-819d8225a761.png)

![screenshot from 2014-10-20 10 53 34](https://cloud.githubusercontent.com/assets/3712729/4695982/5f68a9ae-5847-11e4-9ec1-d7605c4139f3.png)

```
4. update the po's destination location to quality control and then conform the po
```

![screenshot from 2014-10-20 10 55 53](https://cloud.githubusercontent.com/assets/3712729/4695993/b1c3870a-5847-11e4-937b-a9f639d8d0cd.png)

```
5. the future stock move of this item
```

![screenshot from 2014-10-20 11 00 08](https://cloud.githubusercontent.com/assets/3712729/4696036/d5cdf8fa-5848-11e4-88ca-25540edda392.png)

```
6. receive the products and process the internal move from quality control to stock. The inventory quantity of this item turn out to be 6 pcs
```

![screenshot from 2014-10-20 11 06 01](https://cloud.githubusercontent.com/assets/3712729/4696046/34b6054c-5849-11e4-91cb-99bf017cb257.png)

![screenshot from 2014-10-20 11 06 35](https://cloud.githubusercontent.com/assets/3712729/4696048/3a53951e-5849-11e4-8bb4-ca8af3d94dcd.png)

**Comment by Yenthe666** [comment]
Hi @oliverzgy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
