### ISSUE TITLE
Can't group by integer field

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#31684]
Impacted versions: 11

Steps to reproduce: Try to "Add custom group" for a field of type integer in any list view

Current behavior: Integer fields are not in the list of fields to group by

Expected behavior: Should be able to group by an integer field , e.g. Age in years

Video/Screenshot link (optional):

**Comment by elgow** [comment]
The source of this problem is at  `addons/web/static/src/js/chrome/search_menus.js:418`

       ` var groupable_types = ['many2one', 'char', 'boolean', 'selection', 'date', 'datetime'];`

Grouping by integers is certainly supported by the DB and there are plenty of cases where it's needed

**Comment by elgow** [comment]
The source of the problem is `addons/web/static/src/js/chrome/search_menus.js:418`

`        var groupable_types = ['many2one', 'char', 'boolean', 'selection', 'date', 'datetime'];`

Grouping by integer fields is certainly supported by the DB, and there are numerous cases where it's needed.

**Comment by gdgellatly** [comment]
@elgow I think the illustration of your point is m2o is an integer type in db.

**Comment by Yenthe666** [comment]
Please add some sample code & steps on how to reproduce. I can assure you I have dozens of filters like this.

**Comment by william-andre** [comment]
@Yenthe666 There is no code needed, everything is selected from the list view
@gdgellatly You can group on m2o from the list. It is even in the `var groupable_types` elgow put above

**Comment by elgow** [comment]
@Yenthe666 and @gdgellatly, 

Thanks for looking at this issue.   This pair of fields in the Odoo sales model would illustrate the difference if shown in a simple list view of the `sale.order` model. 
```
        currency_id = fields.Many2one("res.currency", related='pricelist_id.currency_id', 
                              string="Currency", readonly=True, required=True)
        invoice_count = fields.Integer(string='# of Invoices', compute='_get_invoiced', 
                               readonly=True)
```

The first would be groupable in a simple list view, the second would not. It's easy see that a grouping by invoice_count could be informative. Many other integer typed fields with a fairly constrained number of distinct values can be similarly useful, e.g. my earlier example of age_in_years.

I would especially note that using a many_2_one is not a reasonable substitute because one would certainly like to have a field like age_in_years be subject to the avg() calculation when the list is grouped by a different field. 

There is definitely no technical barrier to allowing grouping by integer fields and not having available it removes valuable functionality from the list view.

**Comment by gdgellatly** [comment]
> @gdgellatly You can group on m2o from the list. It is even in the `var groupable_types` elgow put above

@william-andre indeed, that was my point

**Comment by elgow** [comment]
@william-andre @gdgellatly The fact that m2o is, in reality, an integer type does make it clear that there is no technical barrier to grouping by integers. I'm not sure if that's what you two are getting at, or whether you are suggesting using m2o instead of integer.

I'd again like to emphasize that _m2o is not a useful substitute for a plain integer type_ in many cases. By using it you lose the ability to see the avg() or sum() of the field in a view that is grouped by a different field. 

Since the fix is as simple as adding integer to the list of groupable types, and since it adds very useful functionality to the basic list view, I would urge Odoo to move on fixing this.

**Comment by gdgellatly** [comment]
@elgow I wasn't suggesting that at all. But if you want Odoo to move on it, generally a PR is best, especially for small fixes. Really the issue tracker is best for issues you don't really care about the resolution time. 

PR's, Enterprise Tickets get dealt to faster.

**Comment by auyeung112002** [comment]
Agree with elgow. Adding this function would be easy and is definitely needed.

**Comment by elgow** [comment]
@gdgellatly Thanks for the tip. I'm in no rush because I don't really expect to get to use any fix for this issue, or indeed most of those I file. We're on Odoo 11 and any fix would be in 13 at the earliest. We use the platform but not any ERP plugins. Most of the development since 11 seems to have been in the plugins. My most serious issue, full-text search, has not AFAIK been addressed at all.  As such we have not had much reason to upgrade from 11. 

I really don't know when we might upgrade. Upgrade is a paid feature and Odoo doesn't provide a way for us to pay just for upgrade, preferably in a one payment per upgrade way. This means that even filing issues for fixing in a future release is more than I should probably spend time on. I think Odoo is a great platform, though, so I file them anyway.

**Comment by sswapnesh** [comment]
Handled in master through https://github.com/odoo/odoo/pull/31789

**Comment by Yenthe666** [comment]
Handled for the upcoming V13 in https://github.com/odoo/odoo/commit/9aac7c92861ae7af031fdc15e4c8a66760edfabb

**Comment by pedrobaeza** [comment]
I would say this is now possible from >=v10...
