### ISSUE TITLE
[11.0-account] Account overdue report layout should support multicompany

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#31690]
Impacted versions: 11.0

Steps to reproduce:
In multicompany environment (let's say company A and company B), set up 'company_share_partner' to True
Setup a partner with company A. The company_id field is then set up to company A
Switch to company B and print an overdue report for this partner
Current behavior:
The external Layout is taken from company A

Expected behavior:
The external Layout should be taken from company B because the user is trying to print the overdu for company B
Video/Screenshot link (optional):

**Comment by cvinh** [comment]
I think that the external layout report should take in priority the user's company instead of the object's company. That happens here : https://github.com/odoo/odoo/blob/d2d7f575298f57365c23d86566f7fb5ea50c284c/addons/web/views/report_templates.xml#L309

**Comment by cvinh** [comment]
fixes here https://github.com/odoo/odoo/pull/31691

**Comment by pedrobaeza** [comment]
Please don't open an issue if you plan to open a PR. Put the issue report on the PR. Closing now as there's the PR.

**Comment by cvinh** [comment]
I'm sorry I did not intend to do a PR at the first place
