### ISSUE TITLE
Save one2many field from website

### ISSUE THREAD

**Issue by entissar12** [odoo/odoo#31715]
Impacted versions: 12.0

Steps to reproduce: 
1- Adding one2many field in hr.applicant Model representing diplomas
2 - Saving the diplomas list from the website when applying

Current behavior:
Application form saves all data except one2many fields.

Expected behavior:
Website_form addons should allow to save one2many fields from the website.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you talking about enterprise module for doing website forms? If so, please report this in odoo.com/help instead of here.

**Comment by nhomar** [comment]
Hello.

Can you share a video? on my side it is working ok!.

**Comment by Yenthe666** [comment]
Hi,

I'm closing this issue off as we didn't recieve any feedback from you in a month.
Don't hesitate to respond if your issue is still present. Please provide us with more feedback then.

Regards,
Yenthe
