### ISSUE TITLE
[12.0] hr.applicant - demo data : Stages alway set 'Initial Qualification'

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#31733]
Impacted versions:
12
Steps to reproduce:
Recruitment -> Applications -> All Applications
![image](https://user-images.githubusercontent.com/40818338/54110877-1d6a0480-4415-11e9-8020-3a5cbde43097.png)
![image](https://user-images.githubusercontent.com/40818338/54110906-31156b00-4415-11e9-940f-0b1a7ee72bcf.png)
(http://477053-12-0-9d4aad.runbot15.odoo.com)
Current behavior:
https://github.com/odoo/odoo/blob/12.0/addons/hr_recruitment/models/hr_recruitment.py#L264
![image](https://user-images.githubusercontent.com/40818338/54111207-eb0cd700-4415-11e9-9327-a652c0d87483.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get what is the problem and why it's a problem. Can you please specify the steps in text, as images are sometimes misleading (we don't get the sequence).

**Comment by dhamedic** [comment]
When i created "hr.applicant", 'stage_id' always sets False

**Comment by dhamedic** [comment]
This is values
![image](https://user-images.githubusercontent.com/40818338/54112175-25777380-4418-11e9-8913-82bd9f7dee71.png)

**Comment by Yenthe666** [comment]
Please give us reproducable steps about what you do, how you do it and what you believe is going wrong. Your answer and report is too vague.

**Comment by dhamedic** [comment]
I have create a video.
https://youtu.be/yPC6LUij_yY

**Comment by Yenthe666** [comment]
@dhamedic thanks for the video, you're right this is a bug.

**Comment by dhamedic** [comment]
@Yenthe666 Maybe i must create a video

**Comment by Yenthe666** [comment]
It has already been fixed - please update your Odoo codebase 👍
