### ISSUE TITLE
When validating an import, emails are sent

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#3173]
While validating the import of `project.task` from earlier OE versions, emails are sent to task responsibles, announcing stage changes.

I'm not sure if those should be sent when importing, but when validating definitely not.

**Comment by Yenthe666** [comment]
@tde-banana-odoo any update on this one?

**Comment by dreispt** [comment]
This is a deep problem: emails are sent even if the transaction is not finished/ is rolled back.
I find the same problem with validations that abort a Stage change, but the Stage changing notification email is sent the same, generating user confusion.

**Comment by Yenthe666** [comment]
Hmm fair point there.. Perhaps we should atleast label this issue? @mart-e asking your input here.

**Comment by mart-e** [comment]
I agree, an email should not be sent if there is a chance of rollback. A commit should be made when the mail is sent.

**Comment by Yenthe666** [comment]
@mart-e could we assign somebody to this one? It has been open for quite a while so I'd really like this one fixed in V10.

**Comment by Yajo** [comment]
Well really mailing should be inhibited when validating import, instead of committing. Maybe setting test mode when validating would disable mailing just like when unit testing.

**Comment by mart-e** [comment]
Actually there is an option for that!
![screenshot from 2016-06
-07 16-46-36](https://cloud.githubusercontent.com/assets/564822/15862356/b6dbee68-2ccf-11e6-8168-0ed500198696.png)

**Comment by Yajo** [comment]
Then disable that for validation and you have it.
