### ISSUE TITLE
[8.0]Onchange product_uom qty and product_uos_qty it's not working

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#3174]
When you have checked in the warehouse settings "Invoice products in a different unit of measure than the sales order", if you set a product with unit of sale kg and factor conversion of 0,5. In the sale order line if i change the product_uom_qty from 1 to 10 the onchange is returning the same values.

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

P.S: Please don't create duplicates - just comment on the first bug report.

Regards,
Yenthe
