### ISSUE TITLE
Access error on _compute_signup_url

### ISSUE THREAD

**Issue by FanisTGT** [odoo/odoo#31744]
Impacted versions: 10

Steps to reproduce: Create role with readonly access to res.users and try open res.users form

Current behavior: Access Error (write) on opening res.users form

Expected behavior: Opening form in readonly mode

On opening res.users form the system computes signup_url but cannot to do it because the method _compute_signup_url check access rights to write self.env['res.users'].check_access_rights('write')

**Comment by mart-e** [comment]
Hello,

You mean trying to access another user?
Sorry but this is actually expected. A user with only readonly access to users should not access their user form, it contains sensitive information (like the reset token) and we wish to restrict the access to administrators only.

**Comment by FanisTGT** [comment]
The case is: One of department manager want to clean access of users, but he is not a system admin. He only want to see what access rights employees have and what they can do in the system. I've created new group with reading rights to res.users. 

Why user of this group can not do what I allowed him? I am confused. 

I understand that by default this form only for Administrators, but user of this group can not write anything to res.users object. He want to only "read". And checking access right by such method "self.env['res.users'].check_access_rights('write')" is not a proper way. signup_url is computed field, I can't even put an option compute_sudo because the error will still happen.

**Comment by moylop260** [comment]
I had a similar issue one month ago for 12.0
But it was fixed from:
 - https://github.com/odoo/odoo/commit/a87485898177

I didn't check it if it is a valid case for 10.0
Another related fixes/issues:
 - https://github.com/odoo/odoo/commit/fdce99424b292badd172df8efd81109115cc5d5f
 - https://github.com/odoo/odoo/pull/31646#issuecomment-470966762

**Comment by mart-e** [comment]
> Why user of this group can not do what I allowed him? I am confused.

Actually, reading that field means being able to do more.
The reset token allows to modify a user's password so, being able to read that field means being able to modify that user. To be able to modify a user, you should have the _write_ access right.

If you wish to access the user profile without these fields, try adding a group (like configuration - access rights) on the view [auth_signup.res_users_form_view](https://github.com/odoo/odoo/blob/49ca43d75cb9a97642c820c2466d454f1ce604cb/addons/auth_signup/views/res_users_views.xml#L4)

**Comment by FanisTGT** [comment]
> reading that field means being able to do more

Incorrect. Reading means reading. If user have reading access it means user can read but can not write?

I've resolve this issue by inheriting res.partner and doing this to avoid incorrect access checking:
```python
    @api.multi
    def _compute_signup_url(self):
        """
        Using sudo to avoid access error.
        Default method is here: addons.auth_signup.models.res_partner.ResPartner#_compute_signup_url
        """
        self = self.sudo()
        super(Partner, self)._compute_signup_url()
```

After this modification user can open res.users form without access error popup window. User does not see edit button in form header and If user try to change password or anything else he gets access errors related with write access. And it is correct behaviour. 

I've created this issue only to signalize about incorrect code of framework.

Also if signup_url is so secure you can fix it like this:
because signup_url is the computable and not storable field.
```python
@api.multi
def _compute_signup_url(self):
       """ proxy for function field towards actual implementation """
        result = self.sudo()._get_signup_url_for_action()
        for partner in self:
            if any(u.has_group('base.group_user') for u in partner.user_ids if u != self.env.user):
                if not self.env['res.users'].check_access_rights('write', False):
                    continue
            partner.signup_url = result.get(partner.id, False)
```

just by disabling raising and returning access rights checking result

**Comment by moylop260** [comment]
> If you wish to access the user profile without these fields, try adding a group (like configuration - access rights) on the view auth_signup.res_users_form_view

Is not enough adding a group to py field definition?

https://github.com/odoo/odoo/blob/10.0/addons/auth_signup/models/res_partner.py#L29

Like @nim-odoo comment https://github.com/odoo/odoo/pull/31646#issuecomment-471469838

https://github.com/odoo/odoo/blob/9d4aad2d67019a3dd2ff5c45c89f3cc1a6202e78/odoo/addons/base/models/ir_ui_view.py#L788-L794

**Comment by pedrobaeza** [comment]
@FanisTGT if one of the best Odoo developers is saying to you that reading that field means a potential security violation and is equivalent to write, you should attend him.

Any way, I'm with @moylop260 about avoiding to show the field when no permissions adding the group to that inherited view.

**Comment by FanisTGT** [comment]
@pedrobaeza, I have no doubt about the professionalism of @mart-e

But I am sure checking write access on computing field like that is not a proper way. Odoo is a great and flexible framework, but if developer checks access in python code, the access rules do not have the proper weight  and erp administrator can not give proper access without amending python code.

**Comment by pedrobaeza** [comment]
@FanisTGT on security things, being secure is more important, and this one is one of them why it has been put. Don't generalize.

Any way, you are free to put the modifications you want in your installations with the involved security risks.

The "workaround" of not showing that field according security group seems a good middle solution as already said.

**Comment by mart-e** [comment]
For security reason, you should use your second code snippet instead of your override with `sudo`.
Or even simpler, just set the group on the view as explained above.

**Comment by Yenthe666** [comment]
In all honesty, `.sudo()` is almost never the answer and it can have a lot of side effects if you don't think it through.

**Comment by sswapnesh** [comment]
What about adding group (`groups="base.group_erp_manager"`) on field ? Ref: https://github.com/odoo/odoo/commit/cbce12642570e6b65d7b21738712c189f6cdee5d
(than we don't need to check `check_access_rights`)

> If you wish to access the user profile without these fields, try adding a group (like configuration - access rights) on the view auth_signup.res_users_form_view


@mart-e 
Adding group on view will try to read DB as you mentioned in https://github.com/odoo/odoo/pull/31646#issuecomment-471469838

**Comment by pedrobaeza** [comment]
@sswapnesh @moylop260 the trick is to add the group to the view, not the field inside the group. That way, the view is not populated and no fetch of the field is done.

**Comment by sswapnesh** [comment]
Adding group in view will perform read in the DB and adding group on field definition won't Perform read in DB.

```
"""Apply group restrictions,  may be set at view level or model level:: 
            * at view level this means the element should be made invisible to 
              people who are not members 
            * at model level (exclusively for fields, obviously), this means 
              the field should be completely removed from the view, as it is 
              completely unavailable for non-members 
```

Or Maybe I missed something here.

**Comment by pedrobaeza** [comment]
Yes, that description is for applying the group on the field definition inside the view, not for view security as I'm mentioning.
