### ISSUE TITLE
12.0 CE Multi-website view inheritance not inheriting across all pages

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#31758]
Creating multiple websites with shared views.  Documentation states editing in the backend to effect all pages and removing website field.  Multi websites are displaying odd behavior with some websites inheriting views and other websites not.

eg:
Customize footer with front end
Delete website field to apply on all websites
optional: archive original footer

eg2:
create Blog Posts (oe_structure_website_blog_post_short_1)
Delete website field to apply on all websites

Result: Displays original or does not inherit new view.

This may be possibly due to frontend / backend editing linking views not associated with website field?

**Comment by rdeodoo** [comment]
Hi, yes, that is how it works.
Editing a page in frontend will create a copy of that page and set it a website_id.
If that page suit your needs and you want to spread it to every websites, you will then have to remove the website_id of that view to make it generic, and remove the original generic one.

But that's not as simple as that.
First, the parent view of that view that you want to remove the website_id might also have a website_id and be specific. Thus, removing the website_id of its child view won't do anything. That view will still be specific as included in the specific tree.

Second, your other websites might also have their own duplicate page for the page you will try to make generic by removing its website_id.
In that case, yes the page will become generic but some website might still have their own specific.

Let me know if you experience something wrong or if I can further help you.
