### ISSUE TITLE
code类型的翻译问题

### ISSUE THREAD

**Issue by diwu01** [odoo/odoo#31760]
Impacted versions:
12
Steps to reproduce:
When trying to override the original terminology translation of the same Po file for the same code from different py files
Current behavior:
alert "ON CONFLICT DO UPDATE problem"
Expected behavior:
Successful loading translation
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hello,

Indeed, a term is unique since v12 so you can't have a term twice with the same reference.
What are you trying to do exactly?

**Comment by diwu01** [comment]
i want to translate a term twice in two  different py file

**Comment by mart-e** [comment]
Please give some code sample/po content so we can be sure we are talking about the same thing.
You mean a code translation (with `_(...)` call) for the same term but in different python file?
I am afraid that won't work, the code translations are global for all odoo's code.

**Comment by diwu01** [comment]
yes，like this po code
#. module: dy_fin_mdm
#: code:addons/dy_fin_mdm/models/account_account.py:77
#, python-format
msgid "code unique"
msgstr "编码唯一！"

#. module: dy_fin_mdm
#: code:addons/dy_fin_mdm/models/account_type.py:24
#, python-format
msgid "Code unique!"
msgstr "编码唯一"

**Comment by diwu01** [comment]
ca we modify the translate method,like "ir.translate"'s unique index

**Comment by mart-e** [comment]
But both terms are different (`code unique` and `Code unique!`). I am sorry but I don't get your issue.
Please give more information on how to reproduce your bug. Also, give the full traceback with a bit more context.
The unique index was added for performance reasons and also because it was hiding issues (you should never get duplicated terms).

**Comment by diwu01** [comment]
sorry，i am worng,the right code like this
#. module: dy_fin_mdm
#: code:addons/dy_fin_mdm/models/account_account.py:77
#, python-format
msgid "code unique!"
msgstr "编码唯一！"

#. module: dy_fin_mdm
#: code:addons/dy_fin_mdm/models/account_type.py:24
#, python-format
msgid "Code unique!"
msgstr "编码唯一"

**Comment by pedrobaeza** [comment]
Are you generating this by hand?

**Comment by diwu01** [comment]
YES

**Comment by mart-e** [comment]
I am sorry but this is out of the intended scope. We expect developers to use the existing export of translations (Settings > Translations > Export source terms) and get a po file that works.
If you are creating manually a po file, you may get an invalid one and odoo will not import it. As a reminder, the po _standard_ requires a unique `msgid` inside a file.
