### ISSUE TITLE
Should use superuser to recompute function field?

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#3178]
Impacted versions:
8.0 stable, Oct 15

Steps to reproduce:
1. Use new API to define a field with compute method
2. Use api.depends to define dependency on any field of other model. And user don't have read right(ir.model.access) on the model being depended.

Current behavior:
Fail to save because of access error in recompute method in model.py

Expected behavior:
Recompute method compute the new value as superuser.

**Comment by rco-odoo** [comment]
@auyeung112002 @lmignon please check the alternative fix in #5087: instead of *always* recomputing fields as user admin, we introduce an explicit flag on the field to do it.

This should provide you a solution without breaking the behavior of other modules.

**Comment by auyeung112002** [comment]
Hi @rco-odoo 
What if there are two compute fields using the same compute function, but these two fields have different compute_sudo setting?
