### ISSUE TITLE
mail: Attach file js widget _onUploadAttachments doesn't rollback if there is a raise

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#31798]
# Impacted versions:
12.0

# Steps to reproduce:
1. Create a constraint to raise error if an attachment is not good for your business logic.
  e.g. api.constraint
1.1 In order to reproduce it from runbot I used a base.automation on_create just raising a error.
2. Open a invoice
3. Use the message post attachment button to upload a file
 - https://github.com/odoo/odoo/blob/37689b189ee904497eb0ce0097ecf013cac1a91c/addons/mail/static/src/js/attachment_box.js#L17
4. Upload file

# Current behavior:
It doesn't show the error
Save the file without rollback

# Expected behavior:
Show the error
No save the file, rollbacking it because of there is a raise error.

# Video/Screenshot link (optional):
![attachment uploaded](https://user-images.githubusercontent.com/6644187/54220038-1d6e1100-44b6-11e9-8e91-d11b6c6f42cf.gif)

OPW#1950945

**Comment by dbo-odoo** [comment]
Hi,

The opw was closed a year ago.  It was not fixed in time for 13.0, but it has been fixed since then (071e03f1782a7ac6033d2f424275892ef89d2e4c) and will be in 14.0.

KR,
