### ISSUE TITLE
Supplier stock not shown in stock value report

### ISSUE THREAD

**Issue by mhapponen** [odoo/odoo#3180]
Hello All,

I have v8 and I receive goods to supplier stock to my warehouse (this is due to the fact that supplier owns the goods at my stock until they are shipped out to the customer). The stock report "Stock value at date" (Reporting-Warehouse-Stock valuation) shows that goods would have been received to regular valuated 'internal stock' which I own. On the other hand when you go to the product and press the inventory button, you see correct stocks and also correct location 'supplier stock'

Scenario:
Location 1: Warehouse 1 / internal stock (owned and in stock valuation)
Location 2: Warehouse 2 / supplier stock (owned by the supplier and not in stock valuation)
Goods received to Location 2 with a put away strategy under Location configuration

Testing:
Create location of Location type "Supplier location" under your regular warehouse. Set Put away strategy to your location which puts goods to this location in goods receive. Create purchase order and receive goods.

**Comment by Yenthe666** [comment]
Hi @mhapponen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
