### ISSUE TITLE
[12.0] Minimun 'db_maxconn' configuration to avoid 'The Connection Pool Is Full'

### ISSUE THREAD

**Issue by JDSalcedo** [odoo/odoo#31830]
Hi everyone, I got an VM in AWS(EC2) with minimun hardware, for max 4 conurrent users:
Ubuntu 18.04
1 CPU
1 GB RAM
And postgresql like a service in AWS too, with a 65 connections pool, this service is shared with another 4 EC2 with the same caracterist.

**Impacted versions:**
12.0 EE

**Steps to reproduce:**
- Configure workers > 0
- Set `db_maxconn = 3`, thinking every worker can open 3 connection to postgres and get 9-12 connection in total.

**Current behavior:**
When the server start it works fine, but when crons excecuted some of them 'Procurement: run scheduler', 'Post process payment transactions', 'Calendar: Event Reminder' jobs raise 'psycopg2.pool.PoolError: The Connection Pool Is Full'.

**Expected behavior:**
Dont get 'The Connection Pool Is Full' error, I think I need to raise `db_maxconn` value but how much?

**Configurations:**
odoo.conf
`[options]`
`addons_path = /opt/odoo12/enterprise,/opt/odoo12/odoo/addons,[HIDE]`
`proxy_mode = True`
`logfile = /var/log/odoo/12/demo/odoo.log`
`syslog = False`
`log_db = False`
`logrotate = False`
`; pidfile = /run/odoo/odoo-server.pid`
`admin_passwd = [HIDE]`
`db_name = False`
`db_host = [HIDE]`
`db_port = 5432`
`db_user = [HIDE]`
`db_password = [HIDE]`
`db_template = template1`
`dbfilter = ^factiva-odoo12$`
`; list_db = False`
`unaccent = False`
`geoip_database = /usr/share/GeoIP/GeoLiteCity.dat`
`data_dir = /home/odoo/datas`
`xmlrpc = True`
`xmlrpc_interface = 127.0.0.1`
`xmlrpc_port = 8020`
`longpolling_port = 8022`
`db_maxconn = 3`
`workers = 2`
`max_cron_threads = 1`
`limit_time_cpu = 60`
`limit_time_real = 120`
`limit_memory_soft = 524288000`
`limit_memory_hard = 838860800`
`limit_request = 8196`
`osv_memory_count_limit = False`
`osv_memory_age_limit = 1.0`

Ngnix:
`#http://jdss.ml server`
`upstream jdss_longpoll {`
`        server 127.0.0.1:8022;`
`}`
`upstream jdss.ml {`
`        server 127.0.0.1:8020;`
`}`
`server {`
`        listen 80;`
`        server_name jdss.ml;`

`        # Add Headers for odoo proxy mode`
`        proxy_set_header X-Forwarded-Host $host;`
`        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`        proxy_set_header X-Forwarded-Proto $scheme;`
`        proxy_set_header X-Real-IP $remote_addr;`

`        #log`
`        access_log /var/log/nginx/jdss.ml.com.access.log;`
`        error_log /var/log/nginx/jdss.ml.error.log;`

`        # Redirect longpolling requests`
`        location /longpolling {`
`            proxy_redirect off;`
`            proxy_pass http://jdss_longpoll;`
`        }`
`        # Redirect requests to odoo backend server`
`        location / {`
`                proxy_redirect off;`
`                proxy_pass http://jdss.ml;`
`        }`
`}`

htop:
![image](https://user-images.githubusercontent.com/8197930/54312256-6ef4c980-45a4-11e9-94aa-a97f640e1a1f.png)

**Video/Screenshot link (optional):**
Log:
![image](https://user-images.githubusercontent.com/8197930/54312118-2210f300-45a4-11e9-943f-5f5bcdfacf48.png)

**UPDATE:**
I rised `db_maxconn` to 4, and 'The Connection Pool Is Full' error is not fired for now, BUT, now I get `At least one model cache has been invalidated, signaling through the database.`, I just configure to fire every 1 min.
![image](https://user-images.githubusercontent.com/8197930/54314444-add94e00-45a9-11e9-9145-683cd18d06a6.png)

It seems to be related to [https://github.com/odoo/odoo/issues/25029](url) issue, but for v12 it should be fixed.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
