### ISSUE TITLE
[12.0] picking validate return nothing

### ISSUE THREAD

**Issue by DamonLiu0814** [odoo/odoo#31835]
https://github.com/odoo/odoo/blob/0201d896d877c8055070093342f89e4ad776de0d/addons/stock/models/stock_picking.py#L756

**Comment by DamonLiu0814** [comment]
when i call button_validate in my code, the result is Fasle ,I think it's a bug.

**Comment by pedrobaeza** [comment]
Why is this a bug? Which problem do you have with that return?

**Comment by DamonLiu0814** [comment]
@pedrobaeza  usually funtion return True/False，action，obejct or raise some error in the end of function，
but in this funciton return nothing。
If  i call this function like
  **res = super(MyClass, self).button_validate()** ,
I can't  know Whether it exe success , and this function can't trigger by my function which exe by **on_barcode_scanned** 
here is my code：
![image](https://user-images.githubusercontent.com/13128021/54344080-307e0e00-467b-11e9-961e-e691d82f7f3c.png)
picking  validate fail， but i call it in normal function(by button)  picking validate success。

sorry for my poor english，I hope you can understand it ：）

**Comment by pedrobaeza** [comment]
Yes, but it's not an issue. If there's an error, an exception will be risen. The return value serves for nothing in these terms.

Closing as no real issue.

**Comment by DamonLiu0814** [comment]
Thank you for your answer ：）
