### ISSUE TITLE
[12.0] PDF reports not displaying Partner name correctly with long company name

### ISSUE THREAD

**Issue by AMhadhbi** [odoo/odoo#31844]
Impacted versions:
12.0 community&enterprise

Steps to reproduce:
Log in to latest current [[runbot]](http://479230-12-0-0201d8.runbot15.odoo.com)
Update the company name with long name as we found in our instance for example : Your company Your company Your company, Your company GmbH.
Open up quotation pdf report.

Current behavior:
Our customer have a long name as in this example : Your company Your company Your company, Your company GmbH.
PDF reports not displaying Partner name correctly 
[Quotation - SO150 (8).pdf](https://github.com/odoo/odoo/files/2966273/Quotation.-.SO150.8.pdf)

Expected behavior:
Partner name displayed correctly.

Video/Screenshot link (optional):
None.

Thanks

**Comment by gdgellatly** [comment]
@AMhadhbi that's life. Customise your external layouts for your situation. Either/both of paperformat header and top margins and layouts.

I got a big square logo, similar issue.

**Comment by Yenthe666** [comment]
Honestly, I'd solve this with the top margins, which should solve this issue in a matter of minutes. I do agree it is not ideal but if we'd create more space from the top it will look bad in other cases (shorter names) and then somebody else will complain about that.

**Comment by AMhadhbi** [comment]
@Yenthe666  @gdgellatly 
I agree with you, I updated the Header spacing and it solved. Thank you

**Comment by Yenthe666** [comment]
Awesome, best of luck with Odoo!
