### ISSUE TITLE
Weird Caching Issue with prices

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#31845]
Impacted versions: 12.0

Steps to reproduce:
I can give a basic outline but not specific steps. However given the prevalance of looping, and with_context calls it might be a major so thought I'd put up. Of course it could also be my mistake and we aren't meant to use with_context within a for loop of a recordset if changes in that context change the value of a computed field.

When accessing `price` of product template it is a computed field.
That computed field, ultimately depends on `def _compute_price_rule` of product pricelist
That function depends on context keys like `date`,  `uom`.

I tried a shell script to reproduce but can't quite get it right. But the code that reproduces it essentially loops over a recordset.

```python
for t in templates:
    price = t.with_context(<pricing context variables based off some condition>).price
```

And after its worked a few times, all of a sudden half a dozen records, no calls are made, all with different `with_context` args, then they are sent as one with a single context argument to the compute method of `product.template`. disabling prefetch didn't help although I probably did it wrong. Eventually it required rebrowsing each record, then it all worked.
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but we need an specific shell script or code for reproducing the problem. We can even say that this is not Odoo code and be tempted to close it, but as you are a regular contributor, I'm keeping this opened meanwhile.

**Comment by gdgellatly** [comment]
@pedrobaeza you can close if you want. I found an issue, I have resolved for myself but realized that the consequences may be something bigger than my own situation and felt it important to alert people, even if I can't give steps, not because it is custom code, but because it is a common idiom.

**Comment by gdgellatly** [comment]
Closing as while I can reproduce the behaviour, it turns out it is a bug in pricelists when fetching for multiple templates not caching.
