### ISSUE TITLE
[Website_event_sale ] 404: Page not found! 

### ISSUE THREAD

**Issue by pji-odoo** [odoo/odoo#3186]
[Effected version : master]
on Backend side in  > marketing > event > kanban View 
for any 'event' when clicking on "Register " link it  gives   404: Page not found! error ....

>youtube link :
 https://www.youtube.com/watch?v=p3Ej70bMZZw

**Comment by Yenthe666** [comment]
Hi @pji-odoo,

This issue is no longer present in the latest code so I'm closing this one.

Regards,
Yenthe
