### ISSUE TITLE
purchase_discounts 8.0.1.0

### ISSUE THREAD

**Issue by roberto-barreiro** [odoo/odoo#3190]
This module can be installed without any issue, but no discount field appears on purchase orders.

**Comment by Yenthe666** [comment]
Hi @roberto-barreiro,

Am I correct this module is made by the community or some developer? There is no such module in the default Odoo code.
Github issues are only for the official Odoo code though, no other modules. I'd suggest you to contact the developer(s) of this module so they can help you.

Regards,
Yenthe
