### ISSUE TITLE
Context passed to tree edited inline not updating  values

### ISSUE THREAD

**Issue by dairondv1986** [odoo/odoo#31913]
Impacted versions: 10

Steps to reproduce: 
We most create a form view, imagine that a field is using values by defining some context ej:
   We have One2Many field (aples_id):
```xml
      <field name="toys_id"/>
       <field name="apples_id" context="{'toys_id': toys_id}">
           <tree editable="bottom">
                  ....
          </tree>
      </field>
```

Current behavior:
Only is happening on inline tree view edition.
The context value is only updated once at begin of page load for the tree objects begin created. If I change the toys values, the change is not reflected to new ones created under apples_id(tree).

Expected behavior:
The context variable may be updated, like using the form view that is displayed if we don't using tree inline modification.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear @dairondv1986,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
