### ISSUE TITLE
wrong translate cause the payment fail to confirm

### ISSUE THREAD

**Issue by JoneXiong** [odoo/odoo#31925]
https://github.com/odoo/odoo/blob/273fc4af6eb515db6ee63855679f2b65bd0583ac/addons/payment/i18n/zh_CN.po#L1718

![image](https://user-images.githubusercontent.com/2276625/54543204-2d1ab780-49d8-11e9-8adf-1e2665cfce29.png)

**Comment by pedrobaeza** [comment]
You can fix it for yourself in Transifex: https://github.com/odoo/odoo/wiki/Translations

**Comment by Yenthe666** [comment]
Hi,

As answered on the PR. You should do this in Transifex, not in a PR.
See https://github.com/odoo/odoo/wiki/Translations#translating-with-transifex

Regards,
Yenthe
