### ISSUE TITLE
Archived sub task is not visible when applying "Archived filter" on sub tasks.

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#31934]
**Impacted versions:** 
12

**Steps to reproduce:**
Create task
Create 2 sub tasks
Archive one sub task
Return to main task (by clicking on Parent tasks button)
Clic on sub tasks button to see the sub tasks.

**Current behavior:**
Only 1 sub task is shown, OK; but when click on Filter then Archived, the sub task already archived is not showing, 

**Expected behavior:**
Archived sub task shall be visible when applying the filter.

Noted:

When returning to the current project tasks, it shows the main task and the non archived sub task, OK but when click on filter then archived, the archived task is shown, also great.

**Comment by sswapnesh** [comment]
This is is expected behaviour as You are going to the Sub-task (Which shows only Active tasks) using Smart button, So All Archived tasks wont be there (Not even under Archived records as it return Active records list only).

Maybe @pedrobaeza  can add more light on this.

**Comment by sswapnesh** [comment]
![](https://image.prntscr.com/image/QOOGTRlARN2w30xricinlg.png)

It will display only one task even you remove all applied filters.

![Screenshot](https://user-images.githubusercontent.com/16624719/54706515-22415d80-4b65-11e9-90cf-4d3d1a6c6b46.png)

**Comment by pedrobaeza** [comment]
In this case it seems a bug, as the domain for getting subtasks is hardcoded in a domain with `child_of`, so it should include the `active_test=False` context for the action:

https://github.com/odoo/odoo/blob/12.0/addons/project/models/project.py#L939

**Comment by sswapnesh** [comment]
That's also True, However we have similar situation at other Places too. (I don't think we always count Archived records)
