### ISSUE TITLE
can not config multi website for different domain name in one database. 

### ISSUE THREAD

**Issue by guohuadeng** [odoo/odoo#31931]
we are Edition: enterprise.
Version: 12.0
we open ticket but get useless support!!
so post issue here, thanks.

hi, support,
we have read the doc "Manage Multi Websites"

https://www.odoo.com/documentation/user/12.0/website/publish/multi_website.html

but still not setup well for 2 domain name.

for example.

1. we are using nginx to redirect to odoo.

2. the odoo.conf is "dbfilter = ^%d$"

3. we want to setup 2 website in 1 database like

http://site1.abc.com, http://site2.abc.com.

both use 1 database like site1.

how to do it.

thanks.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
