### ISSUE TITLE
Fragments of XML to include it in multiple views

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#31947]
This is a feature request:

I have seen you closed the issue #4041, and without a hint on if you considered this feature or not, I am proposing this.

**Proposal**

I call them "fragments", which are includable piece of XML fields, pages, notebooks, ... whatever we can put in forms, trees, kanban, gantt...

To illustrate why this could be useful, let us say I am modelizing renting vehicules. I created 3 models : bikes, cars, and trucks. I will have 3 form views. 

I am abstracting the "reservation" with 2 fields:

```python
# /rent/models/vehicule_bike.py
from odoo import models, fields

class VehiculeAbstractReservation(models.AbstractModel):
  _name = 'vehicule.abstract_reservation'

  booked = fields.Boolean(
    string=u'Booked?',
    help='Check this if this vehicule has been booked',
    default=False
  )

  booking_date = fields.DateTime(
    string=u'Booking date',
    help='Fill this field with the date when the customer want to order this vehicule.'
  )
```

This is where it comes all new, we could be able to create a "fragment" only containing those 2 fields:

```xml
<!-- /rent/views/vehicule_abstract_reservation.xml -->
<odoo>
  <data>
    <record id="vehicule_abstract_reservation_form" model="ir.ui.view.abstract">
      <field name="name">Abstract vehicule reservation form fields</field>
      <field name="model">vehicule.abstract_reservation</field>
      <field name="arch" type="xml">
        <field name="booked" />
        <field name="booking_date" />
      </field>
    </record>
  </data>
</odoo>
```

Which we could then call (like QWeb does) to include them in multiple forms. In this case this would save duplications, and help improve maintenance of these fields in case they change.

```xml
<!-- /rent/views/vehicule_bike.xml -->
<odoo>
  <data>
    <record id="vehicule_bike_form" model="ir.ui.view">
      <field name="name">Vehicule bike form</field>
      <field name="model">vehicule.bike</field>
      <field name="arch" type="xml"
        <sheet>
          <group name="general" string="General information">
            <field name="name" />
            <field name="write_uid" />
            <field name="write_date" />
          </group>
          <group name="reservation" string="Reservation">
            <fragment ref="vehicule_abstract_reservation_form" />
          </group>
        </sheet>
      </field>
    </record>
  </data>
</odoo>
```

What do you think? With my team we often had the discussion, and if we could do that that would be a real time savior! Thank you for reading.

**Comment by Yenthe666** [comment]
@khalyomede maybe I miss something but there is no difference with making `xpath` expressions and just adding the fields in the view by inheriting the original view is there? Or am I missing something here?

**Comment by khalyomede** [comment]
@Yenthe666 You totally right, this would be the solution, but in my case I am already inheriting a view, which make it complicated to do. Maybe there is another way for solving my specific issue?

**Comment by Yenthe666** [comment]
Hmm no there is no other way right now than creating 3 inherits for your 3 views and adding your custom fields there. I don't see another good solution/way either honestly. If you make your suggestion and are able to insert a part of code in multiple views it'll break quite fast the other way around, right? If you'd change one of the 3 views and you have a snippet applying it to multiple views then they will all break too.

CC @pedrobaeza I assume you have an opinion/feedback here too 😉

**Comment by khalyomede** [comment]
Yes @Yenthe666 , I agree this would also multiply the number of failures in case the "fragment" is not correct, in case the model including the fragment does not have the required field, and so. I understand if you guys feel this is a error prone feature and do not worth to spend times on it. I would be cursious to know if you and the core team had encountered this issue of duplicating fields, and if so if they found a workaround.

**Comment by Yenthe666** [comment]
I don't think it'll be implemented/wanted. I'll leave the final call to @mart-e for this though.
@mart-e or @pedrobaeza can probably also tell you if they ever needed this need.

**Comment by mart-e** [comment]
Hi,

I think you are over-engineering your views. Sometimes, it is better to just duplicate some code than introduce complexity to avoid a few lines of XML.

You can have a look at the `product` module where we do some complicated things where we mix view types (`product.template` and `product.product`) and where a model inherit from a view of a different model.
However, I do not recommend you to do this if you can avoid it. This is adding complexity which makes it way more difficult to maintain. We had some nasty bugs in the past when mixing these two models.
My advise would be to just duplicate the view content if you are only talking about these few lines.

Closing as we do not plan to add a way to add support for fragments like you show.
