### ISSUE TITLE
Event - Track: massmailing speakers

### ISSUE THREAD

**Issue by MathAndrews** [odoo/odoo#31954]
Impacted versions: 11

Steps to reproduce: 
- Install module: event, website_event_track, mass_mailing_event (may be some other modules are require)
- Setup the "outgoing email server"
- Create a event
- Add a track to the event
- Set a "Speaker" to the track
- In the event: click the "Mail Track Speakers" button on the top right
- Wait for the cron to run the massmailing
- You will have an error in the logs and the emails are not sent

Current behavior:
Throw a SQL error:
```
bad query: b"\n            SELECT lower(substring(email_from, '([^ ,;<@]+@[^> ,;]+)'))\n              FROM mail_mail_statistics s\n              JOIN event_track t ON (s.res_id = t.id)\n             WHERE substring(email_from, '([^ ,;<@]+@[^> ,;]+)') IS NOT NULL\n        \n               AND s.mass_mailing_id = 2\n               AND s.model = 'event.track';\n            "
ERROR: column "email_from" does not exist
LINE 2:             SELECT lower(substring(email_from, '([^ ,;<@]+@[...
```

In the function `_get_seen_list` of the file addons/mass_mailing/models/mass_mailing.py l.619: select the `mail_field` between `email` or `email_from` but the model `event_track` don't have any of those fields

Expected behavior:
Get the correct field `partner_email` for the SQL query and send the email.

**Comment by Yenthe666** [comment]
@jke-be you know who can check?

**Comment by MathAndrews** [comment]
I add: 
```PYTHON
class Track(models.Model):
    _inherit = "event.track"

    email = fields.Char('Email', store=True, related='partner_id.email')
```
and the email are sent, not sure this is the right way to do it

**Comment by pedrobaeza** [comment]
Do you have latest Odoo code? @mart-e added a fix some time ago for something similar to this

**Comment by JKE-be** [comment]
fix in question: https://github.com/odoo/odoo/commit/83b37a8

**Comment by JKE-be** [comment]
@MathAndrews

thanks but it cannot be done in stable

**Comment by MathAndrews** [comment]
@pedrobaeza I might not have le latest version, but on from end February or beginning March
@JKE-be Thanks, this fix is not in the branch 11 now?

**Comment by pedrobaeza** [comment]
@MathAndrews it seems so, and as @JKE-be has stated, it can't be done in stable, so we have to close this as "won't fix" for that version. If you can add that field for solving the problem, then it's good enough.

**Comment by JKE-be** [comment]
@pedrobaeza 

Imo fix proposed by Math is not doable in stable but we could try to backport @mart-e fix from 12 to 11.

**Comment by MathAndrews** [comment]
I just try something, it was not meant to be a fix ;), I'll not keep it any way, as I discovered this issue, while trying the mailing option on events.

If the fix done by @mart-e can be put in 11, that can be helpful.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/9854e0e908a6e960ff2445b94ffcad3489be4dfd https://github.com/odoo/odoo/pull/31967

@jke-be Not sure but I think Github doesn't close two Issues/PR using same keyword.

**Comment by pedrobaeza** [comment]
No, it's because main branch is 12.0, not 11.0, so issues are only auto-closed when merging in main branch.

**Comment by sswapnesh** [comment]
Thanks for clarification, I was not aware about this.

**Comment by MathAndrews** [comment]
Thanks
