### ISSUE TITLE
[12.0] Tests crashing with deep nested inheritance

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#31960]
### Impacted versions:
12.0  (as far as tested) 

### Steps to reproduce:
Inherit **report_invoice_document**, specifically this table data: https://github.com/odoo/odoo/blob/716ff76d5e639654171a8795461282f3e80a74dc/addons/account/views/report_invoice.xml#L95 

Try a bunch of approaches:
```xml
<xpath expr="//table[hasclass('o_main_table')]/tbody//td[hasclass('o_price_total')]" position="inside"> 
```
```xml
<xpath expr="//table[@name='invoice_line_table']//td[hasclass('o_price_total')]" position="inside">
```
```xml
<xpath expr="/t/t/div/table/tbody/t[2]/tr/t[1]/td[hasclass('o_price_total')]" position="inside">
```
```xml
<xpath expr="//t[@name='account_invoice_line_accountable']/td[hasclass('o_price_total')]/span[@t-field='line.price_total']" position="after">
```

### Current behavior:
CI crashes in Odoo.sh, Travis, etc.

**Example:** https://travis-ci.org/odoo-dominicana/l10n-dominicana/jobs/508555770#L1972

### Expected behavior:
No crash, as this is working as expected and showing the information in the PDF report and HTML. Even doing it with Studio gives a similar output which also crashes

**Comment by moylop260** [comment]
The line that raise the error is
“account_invoice_line_accountable”
Is this field available in the original view?

FYI maybe another xml is inheriting original view to add this field.
It might works from UI since that all is installed but from unittest is not installed all modules when the test is executed
