### ISSUE TITLE
Google Drive’s Integration and functionalities

### ISSUE THREAD

**Issue by belisac** [odoo/odoo#31989]
**Impacted versions:**
11.0

**Steps to reproduce:**
1.) To active the option, should go to Settings → General Setting → Integrations → Google Drive

2.) Fill out the Authorization Code that google generates (after click on “Generate Autorization Code”) 

3.) Create the Google Drive’s template in Odoo and in Drive (to get the Template’s URL that should be fill out when the template is created in Odoo)

**Current behavior:**
Right now, the option allows to create documents and attach them to Odoo's order / ticket / picking through the Template created when was configured, the documents from the template are saving in Drive. However it does not allow to view and manage Google Drive folders, does not create them, neither upload files into a folders.

**Expected behavior:**
From Odoo using Google Drive’s interface, allow to create folders and attach files (copies,images,..) in Drive, and then linked to an order/ticket/picking. At the end, folders and files are store in Drive and in Odoo we have the link to those folders/files. 

**Video/Screenshot link (optional):**
![OpenERP Drive](https://user-images.githubusercontent.com/44980860/54694411-9399f580-4afe-11e9-81bb-c6c5d5a6cacb.png)

![OpenERP Drive 2](https://user-images.githubusercontent.com/44980860/54694424-98f74000-4afe-11e9-9227-ef7d1039f00b.png)

![Open ERP Drive 3](https://user-images.githubusercontent.com/44980860/54694461-a6142f00-4afe-11e9-97bf-6cc3bdee7971.png)

**Comment by pedrobaeza** [comment]
Reading the issue, this is not a wishlist for an existing feature, but a totally new feature like a DMS with integration with GDrive. Now that `documents` are there in enterprise, it's more feasible, but this is something outside of this issue tracker IMO. It's like proposing that Odoo to be able to handle Dropbox or similar.

@Yenthe666 I let you to decide if you want to keep this issue opened for a long.

**Comment by Yenthe666** [comment]
Thanks for the follow-up @pedrobaeza. I agree with you now that we have documents in place you can handle way more in Odoo and that this one has become less interesting. Besides this issue didn't get a single response or upvote in over a year so I assume very little people would need it. 

Let's close it since it will be kept open for ages without anything moving otherwise.
Thanks for reporting the idea though @belisac. :)
