### ISSUE TITLE
Events and Web fails for registration for Events

### ISSUE THREAD

**Issue by FDiaz-EnovaTICs** [odoo/odoo#31990]
Impacted versions:
Odoo 12

Steps to reproduce:
Install modules (Events and Web) Create a new Event, Publish on the Web and try to register to the event as a visitor
Current behavior:
When a visitor tries to register for the event , the system crash as it does not find pricelists.
Only works if ecommerce is installed, then you can assign prices for the event.
ERROR: 'website' object has no attribute 'get_current_pricelist'

Expected behavior:
The system should allow visitors to register "for free" in published events, there is no intent to sale tickets, just to be able to register free of charge.

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/8963791/54694438-272fee00-4b20-11e9-9fce-940093678dae.png)
[TraceBack.txt](https://github.com/odoo/odoo/files/2988770/TraceBack.txt)

**Comment by sswapnesh** [comment]
Hello @FDiaz-EnovaTICs 
This has been fixed at https://github.com/odoo/odoo/commit/f7acbf6466a712dd086d13b14a69f415afe7dc13 (PR: https://github.com/odoo/odoo/pull/31953)

Please update your source code.

**Comment by pedrobaeza** [comment]
Thanks for the pointer, Swapnesh.

Closing as fixed.

**Comment by FDiaz-EnovaTICs** [comment]
Thanks
