### ISSUE TITLE
selection_add not working in fields.selection when using a method 

### ISSUE THREAD

**Issue by Daniel-CA** [odoo/odoo#3200]
Hi,
If you have a field.selection(_method, 'name') and you want to extend using the selection_add there is an error:

TypeError: unsupported operand type(s) for +: 'function' and 'list'

**Comment by hugho-ad** [comment]
Hi,
I've the same problem

    from openerp import fields, models

    class AccountInvoice(models.Model):
        _inherit = 'account.invoice'

        state = fields.Selection(
            selection_add=[('validate', 'By validating')])

And the following error appears

      File "/home/sergio/vauxoo/odoo/openerp/fields.py", line 1341, in set_class_name
        self.selection = OrderedDict(self.selection + selection_add).items()
    TypeError: unsupported operand type(s) for +: 'function' and 'list'

@rco-odoo , can you help us

Regards
