### ISSUE TITLE
[Odoo8.0] website_sale + portal miss leading warning message 

### ISSUE THREAD

**Issue by foutoucour** [odoo/odoo#3202]
We had faced a missleading warning message when we used website_sale in couple with portal.

To reproduce the environment.
- install website_sale and portal
- create a new user
- set it as a sale manager
- add it in the portal group
- go to sale menu and create a new article
- set a name (only required field) and save it.

You should have a double error message with a validateError and an AccessError

![selection_001](https://cloud.githubusercontent.com/assets/547282/4704389/ab47a27e-5871-11e4-8cc7-bec9d7727cdc.png)

This message let us think we had issue with UoM validation and/or read access to product.template.

After hours, we just discovered the issue came from an access rule set in portal group [('website_published', '=', True), ("sale_ok", "=", True)] 

If the same process is done but you hit the published button (in sale page), the product.template is created properly.

We were largely misguided by the warning message and the warning message would need an update to help users to make the right decision.

Could the error message updated to guide to the real solution?

**Comment by Yenthe666** [comment]
Hi @foutoucour,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
