### ISSUE TITLE
12.0 unwanted write happening while saving a record having related field

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#32033]
Impacted versions: 12.0

Steps to reproduce:
Install mrp and Activate variants Tracking is set as none. Then create a manufacturing order for a product. Click on the produce button which will open a transient view. Now click Record produce. It will create the transient records as well as it will initiate a write to product.product with data {'tracking':'none'}, and then to the product.template as there is a field in 'mrp.product.produce.line' called product_tracking which is a related field to product.product's tracking field.

I dont know whether its correct or not. It is actually creating an unwanted write as there is no change in the main field.

**Comment by pedrobaeza** [comment]
On v12, related fields are by default readonly. If not readonly, the write is done, so can you confirm if the field is readonly?

**Comment by omalbastin** [comment]
Field is readonly at the xml view
https://github.com/odoo/odoo/blob/12.0/addons/mrp/wizard/mrp_product_produce_views.xml#L19
On the python side its not readonly
https://github.com/odoo/odoo/blob/12.0/addons/mrp/wizard/mrp_product_produce.py#L176

**Comment by pedrobaeza** [comment]
That's the problem then. This was a result of conservative action for previous behavior in https://github.com/odoo/odoo/commit/3f4f77fd9d5c79c21665fa08d703bba7571decd8, so we should change it to `readonly=True` (or simply remove it for letting the default value which is True). Can you do the PR?

**Comment by Yenthe666** [comment]
I quickly made the PR as it was an easy fix to do.

**Comment by Yenthe666** [comment]
Resolved in https://github.com/odoo/odoo/commit/92313e11dc3182f850f090f615e645f0d40bcb71
