### ISSUE TITLE
[11.0] account: View partially reconciled entries button never is showed

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#32043]
With this change we lose the possibility of using the button defined below with the opposite domain.

https://github.com/odoo/odoo/blob/d2d7f575298f57365c23d86566f7fb5ea50c284c/addons/account/views/account_view.xml#L1169

https://github.com/odoo/odoo/commit/d7f75040c61b10ebf62cafb8890daab9e301a7e1#r32874066

@Tecnativa

**Comment by pedrobaeza** [comment]
Can you put a real life example where that button is needed in the opposite domain?

**Comment by carlosdauden** [comment]
If you have a partial reconciled move line you can't view related reconciled move lines.

**Comment by Yenthe666** [comment]
@qdp-odoo for you

**Comment by pedrobaeza** [comment]
Possible solution in #32216

**Comment by pedrobaeza** [comment]
Fixed in 27f03ab02352c16c0c8f56615420f2b7a0a8b6f0
