### ISSUE TITLE
[11] When product no has variants its accessories not shown in the cart.

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#32054]
Impacted versions:
11.0
***Steps to reproduce:***

• Create a new product and add one accessory to it
• Publish it in the website
• Visit the website
• Add the newly created product to the cart
• Go to the shopping cart

***Current behavior:***

• Product accessories are not shown in the cart

***Expected behavior:***

• Product accessories are shown in the cart

Note: If the product has variants, the expected behaviour occurs.

[Video/Screenshot link](https://youtu.be/dA6QcjzaqtQ)

**Comment by sswapnesh** [comment]
Hello @maitaoriana 
I have tested this on latest Runbot v11(http://484456-11-0-3a0bed.runbot11.odoo.com) and it seems working fine.

Make sure you have Published Accessory Products on website too.

**Comment by maitaoriana** [comment]
Hello@sswapnesh
I tried it again and you are right the products were not published, thank you very much.
