### ISSUE TITLE
Field of type Boolean, default=True and @api.constrains

### ISSUE THREAD

**Issue by macoronado** [odoo/odoo#32053]
Impacted versions: 11

Steps to reproduce:

1 - Define a field of type Boolean with default value set to True:
    available = fields.Boolean('Available', required=True)

2 - Define a constraint like:

@api.onchange('available')
    def _check_something(self):
        if self.available and ANOTHER_CONDITION:
            raise ValidationError(_('My error.'))

Current behavior:

Constraint is never executed.

Expected behavior:

Constraint should be executed.

**Comment by pedrobaeza** [comment]
There's no sense of making a boolean as required, as it always have a value: False or True, but not "not set", so that's the problem.

**Comment by macoronado** [comment]
There was a type in the description, I meant default not required.

**Comment by macoronado** [comment]
Please, review again.

**Comment by pedrobaeza** [comment]
Constraints are not put with `@api.onchange`

**Comment by macoronado** [comment]
Another typo in the example, sorry.
Fixed.

**Comment by pedrobaeza** [comment]
Sorry, but doing things properly, it works. Tested on my daily programming.
