### ISSUE TITLE
Sign In/Out By Project in hr_timesheet excludes contract analytic accounts

### ISSUE THREAD

**Issue by sbuttgereit** [odoo/odoo#3206]
Hi--

Trying to sign in/out of projects using the Sign In/Out By Project facility in Odoo v8 hr_timesheet, however the only projects listed are those associated with a "normal" analytic account.  This would seem to limit the functionality from being useful in perhaps a more meaningful use case: time spent on contracts ("contract" type analytic accounts).  I'm not sure if there is a compelling limitation that excludes contract analytic accounts, but if not this seems like an oversight.  Someone else posted bug on Launchpad for this ( Launchpad user: "Juan José Scarafía (ADHOC)") which describes the issue more precisely (copied from https://bugs.launchpad.net/openobject-addons/+bug/1309085 below):

When using "human resource/attendances/sign in sign out by project", the domian for account_id is wrong, you can not select accoutns of type "contract or project"

The issue can be solved changing in "hr_timesheet/wizard/hr_timesheet_sign_in_out.py"

FROM: 'account_id': fields.many2one('account.analytic.account', 'Project / Analytic Account', domain=[('type','=','normal')]),

TO: 'account_id': fields.many2one('account.analytic.account', 'Project / Analytic Account', domain=[('type','in',['normal','contract'])]),

**Comment by zbik2607** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @sbuttgereit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by sbuttgereit** [comment]
Quite OK.  I stopped using Odoo ages ago.

**Comment by Yenthe666** [comment]
Sorry to hear - you might want to look at V11, it has grown quite a bit. 😉
