### ISSUE TITLE
[wish] website_sale shouldn't depend on website_portal_sale

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#32065]
Impacted versions: 10
Why eCommerce (website_sale) does depend on website_portal_sale ? AFAIK there is no code from website_portal_sale used by ecommerce.
It should be install only when admin activate portal features.

**Comment by pedrobaeza** [comment]
This has changed a lot since v10. Have you checked in v11/v12? Any way, this kind of changes in stable are not allowed, so this wishlist is not possible, and thus closing.
