### ISSUE TITLE
[10.0][11.0] point_of_sale: payment method not filtering

### ISSUE THREAD

**Issue by umiphos** [odoo/odoo#32067]
Impacted versions:
11.0 
12.0

Steps to reproduce:
- Check that you only have a payment method in the session of the POS
- Create 1 or more journals that are allowed in POS
- Create an order, and go to that order
- Hit the button "Payment" it's a wizard
- Select the payment options

You will see all the journals allowed in POS, not only those in the session

Current behavior:
It shows all the payment methods allowed in POS

Expected behavior:
It should only show us the methods related to that session

Video/Screenshot link (optional):

[![IMAGE DESCRIPTION](http://img.youtube.com/vi/H-1E5Tz_1vw/maxresdefault.jpg)](https://youtu.be/H-1E5Tz_1vw "Video description")

NOTE: In 12.0 I haven't been able to replicate it, maybe it was solved there, but I tried the code in there and wasn't the solution...

**Comment by pedrobaeza** [comment]
Hi, @umiphos, I'm afraid you are mixing concepts: one thing is the initial balance you put on the session, for expressing coins and money you have in cash type journals, and another different one is the available journals/payment methods, which is not defined by session, but by POS config.

Closing then this issue as not valid.

**Comment by umiphos** [comment]
@pedrobaeza then, it's expected that in the payment wizard we see ALL the journals that are available in POS? that's a really bad way to operate the filter

**Comment by pedrobaeza** [comment]
Yes, that's the expected behavior.
