### ISSUE TITLE
[10.0] Get full recordset range in form view coming from a tree view in dashboard

### ISSUE THREAD

**Issue by adilakbaruae** [odoo/odoo#32078]
Impacted versions: 10.0

Steps to reproduce:

Current behavior: I am using odoo Dashboards app. I have added a treeview through "favorites->Add to My dashboard". Now when i click on any record from a treeview it shows only that record with pager disabled and i cant navigate to different pages. 

Expected behavior: What i want is that like the orginal behavior when i click any record in my tree view it should show all forms with pager enabled and i can navigate through different forms, I am attaching screnshots also.
![Adding to dashboard](https://user-images.githubusercontent.com/48018987/54897498-11d11000-4ee2-11e9-916d-e8c95ed5a217.png)
![Original Job order Tree view](https://user-images.githubusercontent.com/48018987/54897500-1269a680-4ee2-11e9-860e-0572078f2637.png)
![Pager disabled and cant navigate](https://user-images.githubusercontent.com/48018987/54897502-1269a680-4ee2-11e9-8103-de58b769309d.png)
![Pager enabled when i open a record](https://user-images.githubusercontent.com/48018987/54897504-1269a680-4ee2-11e9-8f31-e2b262020899.png)
![Same tree view added to dashboard](https://user-images.githubusercontent.com/48018987/54897505-1269a680-4ee2-11e9-970b-4bcc0a11e868.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I have observed this too. Changed the title a bit for reflecting better (IMO) the issue

@ged-odoo basically, the problem is that you can't navigate between records when coming from a dashboard. The pager always says 1/1.

**Comment by adilakbaruae** [comment]
Yess. You got it. So how can i pass a list of records from tree view to get
the exact behavior that i am getting in the original tree view. Can you
please help? I know we have to modify the js but how and what can you
please tell?

**Comment by pedrobaeza** [comment]
Odoo should fix it if possible. This is not something I can answer right now without digging. The issue is tagged and with some luck, it will be caught and fixable by Odoo staff.

**Comment by adilakbaruae** [comment]
Ok thank you so much.
Actually i have been working on it for like 5 days and i am frustrated with
this now.

**Comment by adilakbaruae** [comment]
@pedrobaeza any luck?

**Comment by pedrobaeza** [comment]
hehe, I'm afraid these things don't go on that speed.

**Comment by adilakbaruae** [comment]
Ok no problem. I am actually in the center of my project and things cant go forward without this step thats why i am in a hurry. Well, no problem i just want the solution for this.

**Comment by adilakbaruae** [comment]
any idea sir? @ged-odoo
