### ISSUE TITLE
There is no less in bootstrap 4

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#32073]
https://github.com/odoo/odoo/blob/aed56c9bdaded5cbb84d6c86e17c58df63771ee2/odoo/addons/base/models/assetsbundle.py#L892

so please remove the elif leg for this 'txt/less'

at our side, somebody install a module with .less file and it make the backend keep raising lessc error

Error: index out of bounds for `nth($list, $n)`&NewLine;        on line 3249 of /stdin&NewLine;>> $-palette-default: nth($o-color-palettes, $o-color-palette-number);
 -------------------
This error occured while compiling the bundle 'web.assets_common' containing:
 /web/static/lib/bootstrap/scss/_functions.scss
 /web/static/lib/bootstrap/scss/_mixins.scss
 /web/static/src/scss/utils.scss&NewLine 
/web/static/src/scss/bs_mixins_overrides.scss&
/theme_common/static/src/scss/mixins.scss
 /theme_treehouse/static/src/scss/mixins.scss
/theme_common/static/src/scss/mixins.scss
 /theme_treehouse/static/src/scss/mixins.scss

**Comment by JKE-be** [comment]
@rde-odoo

**Comment by JKE-be** [comment]
@rdeodoo

**Comment by pedrobaeza** [comment]
AFAIK, less is still supported, but deprecated. It has nothing to do with BS4. The problems can be:

* Incorrect variable names.
* less compiler (lessc) not deployed.

**Comment by rdeodoo** [comment]
Indeed, less is still supported.

> keep raising lessc error
Error: index out of bounds for nth($list, $n) on line 3249 of /stdin >> $-palette-default: nth($o-color-palettes, $o-color-palette-number);

But the error shows `$` variables which are from sass/scss language, not less (`@`)?
