### ISSUE TITLE
error format on calendar view when choose Arabic language

### ISSUE THREAD

**Issue by modadev** [odoo/odoo#32081]
Impacted versions: 12

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/6012702/54905342-da6a5f80-4ef1-11e9-86c7-f4e20ea86bd2.png)

video record for the issue : http://g.recordit.co/5oIyc9TCcS.gif

Hello every one ,
when i change layout to Arabic language i could not create new leave from calendar
the issue is also excise on runbot.

**Comment by pedrobaeza** [comment]
@mart-e real issue or problem with translation?

**Comment by modadev** [comment]
it is real issue not in translation, it is because the Arabic number in date format 

check the video please 

http://recordit.co/A6GeIydGSY

**Comment by mart-e** [comment]
Thanks, it should be fixed at #32102
