### ISSUE TITLE
Cannot find a chart of accounts with demo data

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#32091]
Abstract:

I was written some unittests that need to create an invoice, but get an error when run on a new DB with demo data:
`odoo.exceptions.RedirectWarning: ('Cannot find a chart of accounts for this company, You should configure it. \nPlease go to Account Configuration.', 246, 'Go to the configuration panel')`

The goal of demo data isn't to be useful when you write unittests and saving your time?
In this case, it would be good to have a chart of account in demo data, because Odoo is already too tentacular.

Impacted versions:
Odoo 11.0-20190128 (Community Edition) 

Steps to reproduce:
- Create a DB with demo data
- Write a unittest that create an invoice

Current behavior:
Get an error :
`odoo.exceptions.RedirectWarning: ('Cannot find a chart of accounts for this company, You should configure it. \nPlease go to Account Configuration.', 246, 'Go to the configuration panel')`

Expected behavior:
No error

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by sebastienhasa** [comment]
This **is** an Odoo issue: It miss data in Odoo demo data and this missing causes errors when it shouldn't.

**Comment by pedrobaeza** [comment]
No, if you do it properly. Check Odoo source code that is testing these things, or there are lot of examples on OCA modules.
