### ISSUE TITLE
[hr_holidays] Validity on leave type is partially Broken

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#32107]
Impacted versions: 12.0

Steps to reproduce: Add Start date on Leave type (Do not fill end date)

![](https://image.prntscr.com/image/kXkp-JGgTKixPGmiqiryFw.png)

So Ideally employee cannot take leave before "01/01/2019"

Current behavior: 
Employee can take leave.
![Screenshot](https://user-images.githubusercontent.com/16624719/54943676-c6f1df80-4f57-11e9-8bfe-a4e131d88b87.png)
https://github.com/odoo/odoo/blob/df324c885771814efde7918cfecfa7940a38591f/addons/hr_holidays/models/hr_leave.py#L233

This method works If Leave type has `Start Date` and `End Date`.

Expected behavior: 
It should work when Leave type has `Start Date` or `End Date` or Both
Employee should not be able to add leave.

Video/Screenshot link (optional):
Related commit: https://github.com/odoo/odoo/commit/df324c885771814efde7918cfecfa7940a38591f

**Comment by sswapnesh** [comment]
Hello @tivisse, 

I believe we should extend this based on Start date or End date or Both in master.

What are your thoughts on this ?

**Comment by sswapnesh** [comment]
Ticket 2009800

**Comment by nim-odoo** [comment]
Working on #34225 34225
