### ISSUE TITLE
Wrong place for security issue,delete it please

### ISSUE THREAD

**Issue by oldrev** [odoo/odoo#32104]

**Comment by oldrev** [comment]
Guys, this is an emergency security breach. 

If you're using "payment acquirer" related module, like payment.paypal, you should remove all your APIPassword/token etc. from them immediately, otherwise you are taking the risk to lose your money.

Anyone can login into your system also could see your 3rd-party payment's secret parameters as well.

**Comment by pedrobaeza** [comment]
Then you shouldn't use this open channel for that. Check https://www.odoo.com/security-report

**Comment by oldrev** [comment]
Thanks, I will check it out later.
