### ISSUE TITLE
[12.0]Error in share

### ISSUE THREAD

**Issue by yuniesky1986** [odoo/odoo#32118]
Impacted versions:
12.0
Steps to reproduce:
Share into form of all models.
Current behavior:
in portal_share file into portal module in the line 13
```python
record = self.env[result['res_model']].browse(result['res_id'])
```
but result is empty dictionary
Expected behavior:
If cut this code and paste in line 15 it is solved...
Video/Screenshot link (optional):

**Comment by mart-e** [comment]
Hi,

If you have a fix, please create a pull request with the patch.
Thanks

**Comment by pedrobaeza** [comment]
Closing as no answer
