### ISSUE TITLE
[7.0] "From" field in email templates are ignored

### ISSUE THREAD

**Issue by JaHicks** [odoo/odoo#3212]
The email_from field specified on an email template is ignored and instead the user's email is always used.

Related to: https://bugs.launchpad.net/openobject-addons/+bug/1171505
(which suggests that there is also an issue with the Reply-to field)

**Comment by Yenthe666** [comment]
Hi  @JaHicks,

Thank you for your report.
Odoo 7 is however no longer supported by Odoo itself (they only support the three latest versions).
If this issue is still present in V8, V9 or V10 please do create a new issue (or PR).

Regards,
Yenthe
