### ISSUE TITLE
Can't display field named "constructor" in view

### ISSUE THREAD

**Issue by Zelwak** [odoo/odoo#32147]
**Impacted versions:** 12.0

**Steps to reproduce:** 
- Adding field name "constructor" in a model. eg: `constructor = fields.Boolean(string='Constructor')`
- Adding the field in a view: `<field name="constructor" />`

**Current behavior:** An error is thrown.

**Expected behavior:** The field should be displayed.

**Video/Screenshot link (optional):**
Traceback (debug=assets)

> Error: Syntax error, unrecognized expression: .o_form_label[for=function Object() {
>     [native code]
> }]
> 
> http://localhost:8072/web/static/lib/jquery/jquery.js:1473
> Retraçage :
> Sizzle</Sizzle.error@http://localhost:8072/web/static/lib/jquery/jquery.js:1473:15
> Sizzle</Sizzle.tokenize@http://localhost:8072/web/static/lib/jquery/jquery.js:2087:25
> Sizzle@http://localhost:8072/web/static/lib/jquery/jquery.js:845:42
> find@http://localhost:8072/web/static/lib/jquery/jquery.js:2704:25
> $@http://localhost:8072/web/static/src/js/core/widget.js:303:16
> _updateView/<@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:973:39
> _.forEach@http://localhost:8072/web/static/lib/underscore/underscore.js:145:9
> _updateView@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:964:9
> _renderView/<@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:926:13
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
> then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
> each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:49
> then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:49
> Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:25
> then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:48
> _renderView@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:925:38
> _render@http://localhost:8072/web/static/src/js/views/basic/basic_renderer.js:511:16
> start@http://localhost:8072/web/static/src/js/views/abstract_renderer.js:37:23
> OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:90:35
> start@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:43:16
> OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:90:35
> _widgetRenderAndInsert/<@http://localhost:8072/web/static/src/js/core/widget.js:399:20
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
> then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
> each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:49
> then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:49
> Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:25
> then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:48
> _widgetRenderAndInsert@http://localhost:8072/web/static/src/js/core/widget.js:393:33
> appendTo@http://localhost:8072/web/static/src/js/core/widget.js:164:16
> start@http://localhost:8072/web/static/src/js/views/abstract_controller.js:94:13
> OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:90:35
> start@http://localhost:8072/web/static/src/js/views/basic/basic_controller.js:54:16
> OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:90:35
> _widgetRenderAndInsert/<@http://localhost:8072/web/static/src/js/core/widget.js:399:20
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
> then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
> each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:49
> then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:49
> Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:25
> then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:48
> _widgetRenderAndInsert@http://localhost:8072/web/static/src/js/core/widget.js:393:33
> appendTo@http://localhost:8072/web/static/src/js/core/widget.js:164:16
> _startController@http://localhost:8072/web/static/src/js/chrome/action_manager.js:894:16
> _executeAction/<@http://localhost:8072/web/static/src/js/chrome/action_manager.js:343:36
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
> then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
> each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:49
> then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:49
> Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:25
> then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:48
> _executeAction@http://localhost:8072/web/static/src/js/chrome/action_manager.js:334:14
> _executeWindowAction/</<@http://localhost:8072/web/static/src/js/chrome/action_manager_act_window.js:341:24
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> updateFunc/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3360:49
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> _createViewController/<@http://localhost:8072/web/static/src/js/chrome/action_manager_act_window.js:233:21
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> updateFunc/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3360:49
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> updateFunc/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3360:49
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> rpc/<@http://localhost:8072/web/static/src/js/services/ajax_service.js:16:17
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> Deferred/</deferred[tuple[0]]@http://localhost:8072/web/static/lib/jquery/jquery.js:3321:62
> genericJsonRpc/<@http://localhost:8072/web/static/src/js/core/ajax.js:59:9
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:86
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3283:104
> fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:38
> fireWith@http://localhost:8072/web/static/lib/jquery/jquery.js:3231:49
> done@http://localhost:8072/web/static/lib/jquery/jquery.js:9275:33
> callback@http://localhost:8072/web/static/lib/jquery/jquery.js:9685:57

**Comment by pedrobaeza** [comment]
You are using a forbidden word, so no possible solution except renaming the field, for example to `is_constructor`. The same happens for example using `length`.
