### ISSUE TITLE
[12] name_get not performed by admin

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#32153]
Impacted versions:
12, 11 maybe, 10 not affected

Steps to reproduce:
```
class PublicModel(models.Model):
    _name='public.model'
    restrict_model_id=fields.Many2one('restrict.model')

class RestrictModel(models.Model):
    _name='restrict.model'
    name=fields.Char()

<form string="Public Model">
    <field name="restrict_model_id" />
</form>

<record id="public_model_action" model="ir.actions.act_window">
    <field name="name">Public Model</field>
    <field name="type">ir.actions.act_window</field>
    <field name="res_model">public.model</field>
    <field name="view_mode">tree,form</field>
    <field name="context">{'default_restrict_model_id':1}</field>
</record>
```
1. Create 2 models as above.
2. Create 1 normal user who don't have access right  on restrict model.
3. Create a restrict model as superuser
4. Create a public model as superuser
5. Login as normal user and browse the public model record(No access error, since the record name is fetched as admin)
6. Click "Create" on public model list view
7. Error occur since normal user has no access right.

Current behavior:
The web client will try to read the name field on restrict model. Error occurs since normal user has no access right on restrict model. It is because name_get is not performed as superuser.
This issue creates unbalance experience because user can read the restrict_model_id.name on the public model created by someone else, but can't read the exact same value when he tries to create public model record.

If it is by design, then it is a security issue in version 10(No error occurs).
If it is not by design, then it is a bug related to name_get.

Expected behavior:
Normal user can see the restrict_model_id.name and no error occurs.

**Comment by pedrobaeza** [comment]
I don't think this is a security issue not a bug in name_get. If you don't have permissions, you can't interact with that model. The no access error can be accidental, but it doesn't mean an information leak, as it's only the display_name information.

**Comment by mart-e** [comment]
It's neither a bug, nor a security issue. If a record is already selected in a many2one, you can access it's name_get content but trying to interact with it or change the values raises an error.
