### ISSUE TITLE
Wrong Behaviour by clicking cancel in import view

### ISSUE THREAD

**Issue by rba-odoo** [odoo/odoo#3215]
Steps to Reproduce:

on database without demo data
1. In any list view click on Import link beside create button
2. Then click on cancel link. It will navigate directly to messages

Effected Version: Master only.

**Comment by Yenthe666** [comment]
Hi @rba-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
