### ISSUE TITLE
[11.0][Enterprise] Project forecast view forgets the filter when a new forecast is added

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#32171]
**Impacted versions:**
11.0

**Steps to reproduce:**

1. Filter the Project Forecast view on some criteria, for example employee name
1. Add a new forecast for the employee

**Current behavior:**
Odoo will just load the default forecast view and ignores the filter I added.

**Expected behavior:**
Odoo will respect the filters that I set before.

**Video/Screenshot link (optional):**
![Odoo11-ForecastBug](https://user-images.githubusercontent.com/1525066/55085585-94f39100-50af-11e9-9866-061ad742b49e.gif)

**Comment by pedrobaeza** [comment]
You should report this to odoo.com/help being an enterprise issue.
