### ISSUE TITLE
[11.0, 12.0 EE] Reload parent view during actions in Wizard without closing it

### ISSUE THREAD

**Issue by Apollo21ap** [odoo/odoo#32190]
# **Impacted versions:**
V11, V12 - Enterprise
# **Steps to reproduce:**
Open "merge selected contacts" and do some merges without close the current wizard.
You need "CRM" module for doing this.

# **Current behavior:**
The parent view (tree view that contains contacts) is not reloaded after doing some merges and if you don't close the wizard. 
In this wizard, you can do as many merges as you want without closing it.

# **Expected behavior:**
I would like to reload parent view (tree view) after doing action of merge from the current wizard without closing it!
If I press "Deduplicate more contacts" still doesn't reload the parent view. It will reload only if I close the wizard.
This is just one example. If I would like to make a way to open a wizard multiple times and complete some records from stock moves or product lines without closing it, at some point I will not know what I have changed only if I close the current wizard (that's not ok all the time). And a parent view reloading is the one that can solve this problem.

# **Video/Screenshot link (optional):**
Before
![screenshot-localhost-8069-2019 03 28-09-05-00](https://user-images.githubusercontent.com/48286081/55137447-aa150200-5139-11e9-9d80-2859f5223f00.jpg)
After merge, parent view still the same.
![screenshot-localhost-8069-2019 03 28-09-05-33](https://user-images.githubusercontent.com/48286081/55137462-b39e6a00-5139-11e9-95c3-46fc34badf74.jpg)
After closing the wizard, it is reloaded..
![screenshot-localhost-8069-2019 03 28-09-08-09](https://user-images.githubusercontent.com/48286081/55137488-c2851c80-5139-11e9-98cb-2ba8a70f5cf3.jpg)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip: you have to return the action window dictionary on the button method.

Closing this by the reason above.
