### ISSUE TITLE
Odoo 10 hangs when sending mail or when owner of document is different

### ISSUE THREAD

**Issue by johnny-longneck** [odoo/odoo#32196]
This is our company odoo setup and I am kind of frustrated after still not finding the issue on this, any help is highly appreciated.

### Impacted versions: ###
Odoo 10.0
### Steps to reproduce: ### 

DigitalOcean Droplet | Yenthe Install Script for Odoo 10 | Reverse Proxy with Nginx
2 Scenarios when Odoo is hanging:
First:
- A user creates a sale order, saves and leaves it
- A different user opens the sale order, confirms it and when creating an invoice from a sale order which user is not the user that creates the invoice then odoo hangs

Second:
- Trying to send emails via outgoing email server - let's say send sale order by mail
- Odoo hangs for some minutes, sometimes with success, sometimes timeout.

### Current behavior: ### 
Odoo hangs with loader icon for minutes
### Expected behavior: ### 
Odoo creates invoices and sends emails directly

Video/Screenshot link (optional):
From the log:
```
2019-03-27 16:15:44,166 1786 DEBUG pls odoo.api: call mail.compose.message(26430,).send_mail_action()
2019-03-27 16:16:43,894 1786 DEBUG ? odoo.service.server: cron0 polling for jobs
2019-03-27 16:16:44,606 1786 DEBUG pls odoo.addons.base.ir.ir_mail_server: send:
```
Here you can see, it takes exactly one minute until something gets processed
There is always a one minute break until next action happens. With several followers on a document, this can take several minutes

Odoo config:
```
[options]
addons_path = /odoo/odoo-server/addons,/odoo/custom/addons
admin_passwd = XXXXXXXXXX
csv_internal_sep = ,
data_dir = /odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_template = template1
db_user = odoo
dbfilter = .*
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
import_partial = 
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 300
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
server_wide_modules = web,web_kanban
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 4
xmlrpc = True
#xmlrpc_interface = 127.0.0.1
xmlrpc_port = 8069
http_enable = False
```

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
