### ISSUE TITLE
[12] Recruitment: An error occurred when moving quickly on the "All Applications"

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#32191]
Impacted versions:
12
Steps to reproduce:
Recruitment -> Applications -> All Applications
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![Screenshot from 2019-03-28 14-47-01](https://user-images.githubusercontent.com/40818338/55140059-c92b8800-5169-11e9-87c7-fc93f949d280.png)
![Screenshot from 2019-03-28 14-47-42](https://user-images.githubusercontent.com/40818338/55140065-ccbf0f00-5169-11e9-8ee3-32f09b29846e.png)
https://youtu.be/PGyThjetBdU

**Comment by pedrobaeza** [comment]
This is because JS hasn't been fully loaded on that moves. Although it would be preferable to not have an error, it's something that can't be prevented easily just now. Just wait to have it fully loaded.

So closing as won't fix.
