### ISSUE TITLE
Missing translations from new terms in point_of_sale

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#32217]
When this patch was applied to `11.0` https://github.com/odoo/odoo/commit/4a5862a492fff66a474b7069cb5ba45836249a0e the translation terms were not updated for the module point_of_sale, so they can't be translated on transifex.

cc @Tecnativa @mart-e

**Comment by pedrobaeza** [comment]
It was a half backport of the commit then. Do you have the commit reference for 11.0?

**Comment by chienandalu** [comment]
This is the commit that's put on the blame: https://github.com/odoo/odoo/blame/11.0/addons/point_of_sale/static/src/js/screens.js#L2081

**Comment by mart-e** [comment]
The commit 4a5862a  was merged in 10.0, as the translations are ignored during forward ports, it was not present.
I added them at  #32232
Thanks for the report

**Comment by chienandalu** [comment]
Thanks!

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/32232
