### ISSUE TITLE
How to configure workers and longpolling in WSGI?

### ISSUE THREAD

**Issue by wangsamas** [odoo/odoo#32221]
Impacted versions:12

Steps to reproduce:install odoo using bitnami, modify workers > 0

Current behavior:errors in production log

Expected behavior:no errors

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
