### ISSUE TITLE
[12.0] Date of RFQ created from SO doesn't validate if SO date is today

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32222]
**Impacted versions:** 12.0

Tested on runbot.

**Steps to reproduce**: 
- Create Sale Order
- Input product that uses Make To Order (to trigger a RFQ) and assign a vendor to it
- In the vendor-product wizard, input a Delivery Lead Time larger than 0
- Confirm the SO

**Current behavior:** The generated RFQ will set the default Order Date to current date minus however many days in the Delivery Lead Time input, even if the resulting date is before the current one.

**Expected behavior:** There should be a validation present in the method that would limit the Order Date to the current one.

https://github.com/odoo/odoo/blob/12.0/addons/sale_purchase/models/sale_order.py#L175-L179

**Comment by pedrobaeza** [comment]
This is done on purpose. Please check https://www.odoo.com/documentation/user/12.0/purchase/replenishment/flows/compute_date.html
