### ISSUE TITLE
Hebrew font not enough readable

### ISSUE THREAD

**Issue by fgi-odoo** [odoo/odoo#32228]
There are some complains about the Hebrew font. It wouldn't be enough readable (too small, similar to writing machine).

Current: 
![hebrew_current](https://user-images.githubusercontent.com/7600016/55218011-29213d80-5201-11e9-8fdd-8c66664308f9.png)

Suggested (Open Sans Hebrew):
![hebrew_suggested](https://user-images.githubusercontent.com/7600016/55218010-29213d80-5201-11e9-8eb8-8fb3a404a6d3.png)

You can test this new font by importing this inherited view in your database (it only applies to Hebrew): 
[open_sans_hebrew.xlsx](https://github.com/odoo/odoo/files/3021645/open_sans_hebrew.xlsx)

We would like to collect more opinions on this from users in Israel. 

What do you think about the current font?
What do you think of the suggested one (Open Sans Hebrew)?

Using a specific font for a language hasn't been considered yet. It would be a critical change for Odoo as all the UI has been optimized for current font family. A new font might induce some displaying glitches.
Ideally we would like to hear from real users testing it during a few days in order to assess the change.

Thanks in advance for your feedback.

**Comment by fgi-odoo** [comment]
We use Lato in community, Roboto in Enterprise. Roboto has an Hebrew extension called  Heebo: https://fonts.google.com/specimen/Heebo?selection.family=Heebo

What do you think of it?

**Comment by rdefygth** [comment]
Hi,

maybe it worth mantioning here, Hebrew/Arabic read or write from right to left. So could you request a support for in more advance versions of odoo.

**Comment by mart-e** [comment]
Technically, I have found 2 solutions:

- we could ship specific fonts that would be only loaded if we explicitly specify the content is in a language
https://www.w3.org/International/questions/qa-css-lang
Technically, this requires we specify in which language the current content is (which may be tricky with assets and stuff)
- we could declare multiple fonts with a specific `unicode-range` to the font-familly and only use one font when needed
(idea from https://stackoverflow.com/a/6487102 )

I like the second one (easiest) but we need to investigate the impacts of each one.

@rdefygth we already support RTL in odoo 12.0 so this shouldn't be an issue.
