### ISSUE TITLE
Inventory Valuation (FIFO) not working properly with multi stock location.

### ISSUE THREAD

**Issue by arjunb-ept** [odoo/odoo#32249]
Odoo Version: **11.0 Enterprise**
Tested on: **Runbot**
Date: **March 28th, 2019**

**Issue**: While selling the same product from different stock location its use the same incoming move for both delivery orders and for valuation entries as well as stock decrease.

**Steps to Re-Produce the issue:**

**01 - Create a Product with Stockable type**

![01_create_product](https://user-images.githubusercontent.com/36621458/55234207-a6c06a00-5250-11e9-8bd2-3f6c6948acb7.png)

> 01.1 -> Product Type: **Stockable Product**
> 01.2 -> Category: **All / Saleable / Physical**

**02 - Configure Product Category**

![02_category_config_fifo](https://user-images.githubusercontent.com/36621458/55234882-1b47d880-5252-11e9-89eb-12c0be72d2b7.png)

> 02.1 -> Costing Method: **First In First Out (FIFO)**
> 02.2 -> Inventory Valuation: **Automated**

**(For create Automated Incoming and Outgoing Journal Entries)**

**03 - Create a 1st Purchase order (PO00075)**

![03_PO0075_01](https://user-images.githubusercontent.com/36621458/55234975-59dd9300-5252-11e9-9702-89d7649a8b74.png)
![03_PO0075_02](https://user-images.githubusercontent.com/36621458/55234984-5fd37400-5252-11e9-805c-7bae368461ac.png)

> 03.1 -> Product: **Test Product**
> 03.2 -> Quantity: **10**
> 03.3 -> Unit Price: **$10.00** 
> 03.4 -> Deliver To: **YourCompany: Receipts**
> 03.5 -> Confirm Purchase Order

**04 - Incoming Shipment (PO00075)**

![04_IS_wh_in_109_01](https://user-images.githubusercontent.com/36621458/55235165-de301600-5252-11e9-8c3a-d02393ffb07c.png)

> 04.1 -> Confirm Incoming Shipment: **PO00075 -> WH/IN/0109**
> 04.2 -> Verify Destination Stock Location: **WH/Stock**

**05 - Journal Entry of Incoming Shipment(WH/IN/0109)**

![05_JE_wh_in_109](https://user-images.githubusercontent.com/36621458/55235207-0455b600-5253-11e9-83ef-d93e96edb4b4.png)
> 05.1 -> Credit/Debit=(Purchased Qty **x** Purchased Unit Price)
	     Credit/Debit=(10 **x** $10) = **$100**
> 05.2 -> Value of stock move is also **$100**

**06 - Create a 2nd Purchase order (PO00076)**

![06_PO0076_01](https://user-images.githubusercontent.com/36621458/55235288-35ce8180-5253-11e9-985a-794f4c792793.png)
![07_PO0076_02](https://user-images.githubusercontent.com/36621458/55235300-3e26bc80-5253-11e9-986e-ec89aa7856ce.png)
> 06.1 -> Product: **Test Product**
> 06.2 -> Quantity: **10**
> 06.3 -> Unit Price: **$20.00** 
> 06.4 -> Deliver To: **My Company Chicago: Receipts**
> 06.5 -> Confirm Purchase Order

**07 - Incoming Shipment (PO00076)**

![08_IS_myco_in_003_01](https://user-images.githubusercontent.com/36621458/55235383-73cba580-5253-11e9-8c97-e7d69817a3bd.png)

> 07.1 -> Confirm Incoming Shipment: **PO00076 -> My Co/IN/0003**
> 07.2 -> Verify Destination Stock Location: **My Co/Stock**

**08 - Journal Entry of Incoming Shipment(My Co/IN/0003)**

![09_JE_myco_in_003](https://user-images.githubusercontent.com/36621458/55235486-aa092500-5253-11e9-8220-37f3c8da0791.png)

> 08.1 -> Credit/Debit=(Purchased Qty **x** Purchased Unit Price)
		Credit/Debit=(10 **x** $20) = **$200**
> 08.2 -> Value of stock move is also **$200**

**09. Create 1st Sale Order (SO141)**

![10_SO141_01](https://user-images.githubusercontent.com/36621458/55235649-1126d980-5254-11e9-83e0-df47c27f2336.png)

![11_SO141_02](https://user-images.githubusercontent.com/36621458/55235656-15eb8d80-5254-11e9-9f12-84925e5e797c.png)

> 09.1	-> Product: **Test Product**
> 09.2	-> Quantity: **5**
> 09.3	-> Warehouse: **YourCompany**
> 09.4	-> Confirm Sale Order

**10. Delivery Order (SO141)**

![12_DO_WH_00173_01](https://user-images.githubusercontent.com/36621458/55235712-31569880-5254-11e9-81c6-8854c55e84c4.png)

> 10.1	-> Confirm Delivery Order **SO141 -> WH/OUT/00173**
> 10.2	-> Verify Source Location **WH/Stock**

**11. Journal Entry of Delivery Order (WH/OUT/00109)**

![13_JE_WH_00173](https://user-images.githubusercontent.com/36621458/55235770-51865780-5254-11e9-93dc-bce49e04fd9b.png)

> 11.1 -> Credit/Debit=(Sale Qty **x** Incoming Stock Unit Price)
		   Credit/Debit=(5 **x** $10) = **$50** 
> 11.2 -> Outgoing Stock Move value also **$50** 

**12. Create 2nd Sale Order (SO142)**

![14_SO142_01](https://user-images.githubusercontent.com/36621458/55235830-75e23400-5254-11e9-8afa-c5d4fc51b0fc.png)
![15_SO142_02](https://user-images.githubusercontent.com/36621458/55235833-78448e00-5254-11e9-9cfa-d8f380e114e5.png)

> 12.1 -> Product: **Test Product**
> 12.2 -> Quantity: **2**
> 12.3 -> Warehouse: **My Company, Chicago**
> 12.4 -> Confirm Sale Order

**13. Delivery Order (SO142)**

![16_DO_my_co_001_01](https://user-images.githubusercontent.com/36621458/55235895-aaee8680-5254-11e9-8a5d-a56d3c16a3c4.png)

> 13.1 -> Confirm Delivery Order **SO142 -> My Co/OUT/00001**
> 13.2 -> Verify Source Location **My Co/Stock**

**14. Journal Entry of Delivery Order (My Co/OUT/00001)**

![17_JE_my_co_001](https://user-images.githubusercontent.com/36621458/55236019-f6089980-5254-11e9-976d-697812667b0b.png)

> 14.1 -> Credit/Debit=(Sale Qty **x** Incoming Stock Unit Price)
> 		   Credit/Debit=(2 **x** $10) = **$20** 
> 14.2 -> Outgoing Stock Move value also **$20**

**Issue**: Here **WH/IN/0109**’s stock move used as candidate move which is wrong, as per actual flow/logic for **My Co/OUT/00001** delivery order it should take value and quantity from      **My Co/IN/0003**.

**15. Stock Move of WH/IN/0109**

![18_SM_wh_in_109](https://user-images.githubusercontent.com/36621458/55236150-4c75d800-5255-11e9-860e-e103caff2177.png)

> 15.1 -> Inital Demand: **10**
> 15.2 -> Unit Price: **$10** 
> 15.3 -> Real Quantity: **10**
> 15.4 -> Remaining Quantity: **3**
> 15.5 -> Remaining Value: **$30**

**1st Issue**: Here Remaining Quantity should be **5** and Remaining Value should be **$50**, because from **WH/Stock** we sell only **5** qty in **SO141 (WH/OUT/00173)**. But by this result, we can say a incoming move candidate which used for **SO142 (My Co/OUT/0001)** is **WH/IN/0109**
	
**2nd Issue**: If we sell more **5** quantity from the **YourCompany** warehouse then it will decrease quantity from **WH/IN/0109** stock move and make the remaining quantity **-3**.

**16. Stock Move of My Co/IN/0001**

![19_SM_my_co_in_001](https://user-images.githubusercontent.com/36621458/55236276-9bbc0880-5255-11e9-82a0-00cc7eb28e73.png)

> 16.1 -> Inital Demand: **10**
> 16.2 -> Unit Price: **$20** 
> 16.3 -> Real Quantity: **10**
> 16.4 -> Remaining Quantity: **10**
> 16.5 -> Remaining Value: **$200**

**Issue**: **My Co/OUT/00001** this delivery order should be used Quantity as well as Value from **My Co/IN/0001** incoming shipment, but it wasn’t. 

**17. Quantity on Hand**

![20_product_on_hand](https://user-images.githubusercontent.com/36621458/55236387-d02fc480-5255-11e9-84eb-bed9fd9a64db.png)

> 17.1 -> While we check the Quantity on Hand from Product view it shows proper stock location wise.

**18. Stock Move Lines**

![21_stock_move_lines](https://user-images.githubusercontent.com/36621458/55236431-ea69a280-5255-11e9-9f5b-d8d1fcb3b8b4.png)

**Comment by sle-odoo** [comment]
Hi,
There's differences between the fifo removal strategy and the fifo cost method.
The fifo cost method is company wise, the fifo removal strategy will consider the locations.
Regards
