### ISSUE TITLE
Inheriting/superseding menuitems

### ISSUE THREAD

**Issue by mreficent** [odoo/odoo#32257]
**Impacted versions:** supposedly all (tested in v11)

**Steps to reproduce:**
As an example, you have in `stock` the following menuitem:
```xml
    <menuitem name="Inventory" id="menu_stock_root" sequence="30"
        groups="group_stock_manager,group_stock_user"
        web_icon="stock,static/description/icon.png"/>
```
Then in a custom module named `stock_plus` (that depends on `stock`) you have:
```xml
    <menuitem id="stock.menu_stock_root"
        groups="group_stock_manager,group_stock_user,group_extra_stock"
        web_icon="stock_plus,static/description/icon.png"/>
```
The result is that the original menuitem loses its name (is replaced by its xmlid). This is **error 1**.

Then, if you uninstall `stock_plus`, then the original name of the menuitem is still lost. This is **error 2**.

**Current behavior:** The errors above happen.

**Expected behavior:** The errors above doesn't happen.

Video/Screenshot link (optional):

**Comment by mreficent** [comment]
ping: @Elkasitu

**Comment by pedrobaeza** [comment]
@mreficent you are accumulating some development mistakes and "known issues":

* You mustn't "override" a record using a shortcut tag like `<menuitem>`. They expected to be fully defined. For changing only several fields, use `<record>` tag instead.
* If uninstalling the module, you should provide an uninstall_hook that restores the behavior, or just update the module `stock` afterwards.

For me, this can be considered invalid, but as @Elkasitu has self-assigned, I let him to judge.

**Comment by mreficent** [comment]
I get an `etree` error if I try to override with `record` tag instead of `menuitem`.

**Comment by mreficent** [comment]
If I use `record` tag instead of `menuitem`, I get this error:
```yml
  File "/.../odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/.../odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/.../odoo/odoo/tools/convert.py", line 839, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:194922)
AssertionError: Element odoo has extra content: data, line 5
```

**Comment by pedrobaeza** [comment]
Because you have to use `<record>` syntax, with fields as children `<field>` tags

**Comment by mreficent** [comment]
I have used that.

**Comment by pedrobaeza** [comment]
If you don't put full example I can't tell you which is the error.

**Comment by mreficent** [comment]
Just
```xml
<record id="stock.menu_stock_root">
    <field name="groups">group_stock_manager,group_stock_user,group_extra_stock</field>
</record>
```

**Comment by pedrobaeza** [comment]
Put more or less this, which is the proper field name and syntax:
```xml
<record id="stock.menu_stock_root">
    <field name="groups_id" eval="[(4, ref('stock.group_stock_manager')), (4, ref('stock.group_stock_user')), (4, ref('group_extra_stock'))]"/>
</record>
```
and you can remove existing groups if already added by the standard.

In this case, if I'm understanding the whole context (that is that you want to add an extra group to the menu), uninstalling the module will unlink the extra group, and then the group will be auto-removed from here, so nothing to do on uninstalling.

**Comment by mreficent** [comment]
Uh, I was too fast I didn't thought that way. Ok, nice. But I tried again with your proposal and still fails with same error.

**Comment by pedrobaeza** [comment]
Well, I have written without the rest of the context, but it's that. Maybe wrong XML-IDs, a missing comma...

**Comment by intero-chz** [comment]
@pedrobaeza @mreficent `model` is missing in node `record`. It should be `ir.ui.menu`.

**Comment by pedrobaeza** [comment]
Totally! I missed that one, so comment amended, but the purpose was to showcase the technique. Any way, closing this as no valid.

**Comment by mreficent** [comment]
thanks @intero-chz, that worked :)

**Comment by intero-chz** [comment]
@pedrobaeza i know it was for showcase ;-)

Am i the only one who thinks that these shortcuts should be removed? I don't see the big advantages having them. But i see disadvantages like a more expensive maintenance of the documentation, attributes with other names then the fields (for example groups -> groups_id) and problems with introducing new fields to the models behind the shortcut (paperformat_id on reports for example).

**Comment by pedrobaeza** [comment]
Well, they provide a more direct syntax for usual records, but I agree it comes with a maintenance burden and this kind of misunderstandings.
