### ISSUE TITLE
Posbox enables wireless AP even when Ethernet connected

### ISSUE THREAD

**Issue by elementgreen** [odoo/odoo#32269]
Impacted versions:
posbox_image_v17 on a Raspberry pi 3 B+

Steps to reproduce:
Boot a POSBOX with Ethernet connected using DHCP and no client wireless configured.

Current behavior:
Wireless access point gets enabled with an IP address of 10.11.12.1, even though Ethernet gets assigned an IP via DHCP.
/var/log/syslog on POSBOX says:
raspberrypi posbox_wireless_ap: No wired IP

Followed by log entries showing that eth0 got assigned an IP from dhcpcd.

Expected behavior:
Wireless AP should not get enabled when using Ethernet. This seems like a security risk, especially when coupled with the default Raspberry pi login, which is difficult to change (have to remount root partition R/W). Ideally wireless AP should not be enabled unless explicitly configured, which would require connecting via Ethernet initially.

Can be disabled by commenting out the following line in /etc/rc.local:
/home/pi/odoo/addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh &

Also, I was not able to find the posbox and hw_ related addons on github. Where is this hosted?

**Comment by elementgreen** [comment]
Had to add:
service odoo restart

To rc.local, since it seems wireless_ap.sh does this. Odoo doesn't start when disabling the call to that script.

**Comment by mart-e** [comment]
The ip is found via the command
```
$ python3 -c "import netifaces as ni; print(ni.ifaddresses('eth0').get(ni.AF_INET) and ni.ifaddresses('eth0')[ni.AF_INET][0]['addr'] or '')"
```

Could you log on the posbox, execute it and give us the result?

The script is here:
https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
