### ISSUE TITLE
Blog Post followers are not notified

### ISSUE THREAD

**Issue by selamatbobo** [odoo/odoo#3226]
Hi,

Running odoo 8 with website and a blog.

Blog's followers are not receiving email notification when a new post is published. They follow discussion, new post and post published but the only email they receive is when a comment is post on a blog post.
Tried it in every angles without success...

**Comment by Yenthe666** [comment]
This has been handled in https://github.com/odoo/odoo/commit/4bf9dc4078a5ca413539a6fd16400fd5aad46907 but nobody ever closed this.
