### ISSUE TITLE
Base table dropped when remove a custom module

### ISSUE THREAD

**Issue by stesifrancesco** [odoo/odoo#32273]
Impacted versions: Odoo 12

Steps to reproduce:
When I install my custom module where I import this simple model:

from odoo import api, fields, models

class PurchaseOrderLine(models.Model):
    _inherit = 'purchase.order.line'

...
    order_transport = fields.Boolean(default=False)
...

Current behavior:
When I unistall this custom module table purchare_order_line is dropped from DB

Expected behavior:
I expect that only added fields will be dropped from DB 

I have this problem only with sale_order_line and purchase order line....

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Hello @stesifrancesco 

I am not able to reproduce this on latest Runbot Build. (http://489556-12-0-3b5f33.runbot21.odoo.com)
I uninstalled `sale_stock` and `sale_purchase` there which adds few new fields and `sale.order.line` is still there.

**Comment by pedrobaeza** [comment]
@stesifrancesco this is due to an outdated code in your installation. It was fixed several weeks ago.

Closing for now, but comment if with latest code, it's still happening.
