### ISSUE TITLE
POSBOX customer facing display does not show ir_attachment images

### ISSUE THREAD

**Issue by elementgreen** [odoo/odoo#32272]
Impacted versions:
odoo-12.0.20190325 nightly deb package for Ubuntu.
posbox_image_v17 on a Raspberry pi 3 B+

Steps to reproduce:
1. Configure a POSBOX with a customer facing HDMI display with a POS shop.
2. Edit the display layout to change either the logo image or advertising image.
3. Upload an image attachment.
4. Save the config
5. Open a POS session
6. Note that the attached images are not shown on the POSBOX customer facing display

Current behavior:
Attached images in POS customer facing display layout are not shown, but static images are (using an existing static image background works fine). odoo-server.log shows 404 errors when posbox attempts to retrieve image attachments from main Odoo server, since it does not know which database it belongs to (? shown for database name in log). Loading up the customer facing display in a web browser on the main Odoo server, by clicking the appropriate link on the posbox odoo webpage works, because odoo determines the correct database. I'm not sure how Odoo determines which database an ir_attachment URL applies to though.

Expected behavior:
POS customer facing display should show ir_attachment images.

As an additional test, I manually added a static ir_attachment image to the database and placed the file under addons/website/static and it worked fine.

**Comment by pedrobaeza** [comment]
This seems a deployment issue, with a multi-database server without proper dbfilter, but not an Odoo issue.

**Comment by elementgreen** [comment]
I was not aware of dbfilter in relation to multi-database setups, so you're probably right. I'll close this for now and re-open if it turns out to be a genuine issue.
