### ISSUE TITLE
[8.0, 7.0] discount field is displayed on supplier invoices by error

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#3227]
Activate "Allow setting a discount on the sales order lines" option in Sales Configuration creates and displays a discount field on sales and customer invoices, but also on supplier invoices.
As customers and suppliers invoices are on the same object, it needs:
- a distinct option to know if the user wants a discount on supplier invoices.
- a distinct res.groups

to conditionally display the discount on invoice views.

**Comment by lfreeke** [comment]
^Agree 

The option "Allow setting a discount on the sales order lines" should only be available for the sales invoice and not for the purchase invoice. 

The <field name="discount" groups="sale.group_discount_per_so_line"/> should not be present in the account.invoice.supplier.form or create the same option as discount on sale but than for the purchase.

**Comment by Yenthe666** [comment]
Hi @rdeheele ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
