### ISSUE TITLE
[7.0][Stock] Stock move partial delivery does not correctly convert quantity and UoM

### ISSUE THREAD

**Issue by alhashash** [odoo/odoo#3228]
To replicate using demo database with sale_stock module installed:

1. Enable "Manage different units of measure for products" from `Settings`>`Configuration`>`Warehouse`
2. From `Warehouse`/`Deliver Products` select multiple moves
3. From `More` select `Deliver/Receive Products`
4. For one move change unit to `Dozen(s)` instead of `Unit(s)`
5. In another move increase quantity

When changing UoM, the new UoM is ignored and the quantity is assumed to be in the original UoM
When increasing quantity the move is processed using the original quantity

**Comment by mart-e** [comment]
Hello,

It was fixed at 0b2bc27adc9ced899744c3bd06789d69e5b990f5, thanks for the reporT.
