### ISSUE TITLE
[11.0] [12.0] warning or blocking message is ignored when duplicating invoice

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#32307]
Impacted versions:
[11.0] [12.0]

Steps to reproduce:
tested in runbot.odoo.com
1. Make sure you have enabled the settings in invoice: Get warnings when invoicing specific customers.
2. Set a blocking message on a customer like Deco Addict.
3. Try to create a invoice. The customer is blocked [OK].
4. Open an existing invoice of Deco Addict and duplicate the invoice. Nothing happens [NOT OK]

Expected behavior:
When I duplicate an invoice it is the same as creating a new one. The system should check if I have set a Warning or Blocking message.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The warning behavior is only expected to work on the first scenario, not the second one. Although desirable, that feature is a new one, but not a bug.

I still let this opened looking for the opinion of a functional person like @fgi-odoo to see if it's interesting for future versions.

**Comment by fgi-odoo** [comment]
It would look quite weird to hit "Duplicate" and then get the warning straight on. The warning can be blocking, meaning the new invoice couldnt be saved. It's a new logic to implement.

But anyway, duplicating an invoice is more used in the case of vendor bills, where warnings are not really needed. Therefore I wouldn't improve this for the moment. It's not a priority.

**Comment by yung-wang** [comment]
@fgi-odoo Maybe you can raise a info message for a warning and an error message for a blocking.
I don't agree the business case about only vendor bills. If you don't use subscription, and you have recurring invoices, you would want to simple this proces by duplicating older customer invoices.
Please reconsider this issue, because there is a reason to block a customer. Is you duplicate something, you can still invoice someone. You might have a bad relation with this customer, or you dont want to sell them something for some reason.

**Comment by fgi-odoo** [comment]
I agree those warnings must be somehow improved, but it's not a priority for the next version. But don't worry, we have it in mind for later.
