### ISSUE TITLE
[11.0] [12.0] Terms and Conditions are emptied when switching from customer

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#32309]
Impacted versions:
[11.0] [12.0]

Steps to reproduce:
1. Create an invoice with a customer and enter some text in Terms and Conditions (field: comment).
2. Save the invoice.
3. Edit the invoice and change the customer. The text in Terms and Conditions is emptied. [NOT OK]

Current behavior:

Expected behavior:
You cannot link Terms and Condition on a customer. So there is no reason to empty the field when you switch from customer.
The business case is when the user duplicates an existing invoice or just want to change the customer to the invoice address of the same customer. The user will lose all the information stored in the Terms and Conditions.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
You should consider to set Default terms here.
![Screenshot from 2019-04-01 20-50-53](https://user-images.githubusercontent.com/16624719/55339259-f6f13380-54bf-11e9-80d5-7140f3b72757.png)


However, It also makes sense to keep original terms when Invoice is Copied or Partner is changed.

**Comment by Yenthe666** [comment]
As far as I know this is default behaviour honestly. @mart-e what do you think?

**Comment by mart-e** [comment]
Looks like a side effect of 9bf1f97d9bfa2128f36a103fbb8aa671a91b5417
@simongoffin can you have a look?

**Comment by yung-wang** [comment]
@mart-e Thank for the research!
@sswapnesh That option is only available when you have installed the sale module. We are talking here about the invoices (account module). So not an solution.

**Comment by mart-e** [comment]
@yung-wang you should not have the issue only with account module, I could reproduce it only if the sale module was installed. Could you check which modules are installed exactly?

**Comment by yung-wang** [comment]
@mart-e Sorry, i was confused with sale_management and sale. We have sale installed, but dont use sale_management. We cannot remove sale, because it is a dependency.
