### ISSUE TITLE
[11.0] [12.0] automated action send mail will send an e-mail even when the customer has no e-mail address

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#32310]
Impacted versions:
[11.0] [12.0]

Steps to reproduce:
1. Create a customer without e-mail address.
2. Create an automated action that sends a mail when an invoice is validated. See screenshot:
![image](https://user-images.githubusercontent.com/30628967/55337941-e3ce6b80-549f-11e9-9d83-aa8b74cab9f7.png)
3. Create an invoice with this customer and validate the invoice. You will see that Odoo creates an e-mail. But the e-mail will not be sent.

Current behavior:

Expected behavior:
When you create an invoice and you manually send the e-mail, the system will raise an error that you need to fill in the e-mail address. The system should also raise some message for the user for the automated actions.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Automated action should never raise any of these messages, as the automation might be part of other automation (cron, process, etc). If so, you'll block this automation.

Closing as no valid issue.

**Comment by sswapnesh** [comment]
> When you create an invoice and you manually send the e-mail, the system will raise an error that you need to fill in the e-mail address. 

Thats because of many2many_tags_email (Which doesn't block any operation)

**Comment by yung-wang** [comment]
@pedrobaeza Please reconsider and reopen this issue. I only encountered this problem using the automated action, but maybe that is not the root cause. Maybe we should spend some more time investigating this.
I dont know much about the technical side of the other automation, so it is possible that the solution is not to be found in the automated action.

The strange thing that is happening here, is that the system allows to send an e-mail even when there is no e-mail address to be found. That should be considered a bug. If I try to send a mail in Gmail or Thunderbird without a receiving e-mail address, it is just not possible.
In Odoo it is 'allowed' and this e-mail will be waiting in the mail queue. In the chatter in the invoice you even see a logging that the mail is sent. This is very confusing for the end-user. He will think that his customer has received the mail.

![image](https://user-images.githubusercontent.com/30628967/55384628-7d8f2a80-552b-11e9-944c-1abdacb5fc22.png)

**Comment by pedrobaeza** [comment]
Odoo allows as you are sending a message, not an email, which is a different concept. You can see messages also through portal or in the backend, so I still think it's not an error.

**Comment by yung-wang** [comment]
@pedrobaeza 
Ok, I'm a functional person, I don't know exactly how different it is, but if you say so than I agree.

But in the end, there will be an e-mail waiting in the mailqueue, that cannot be send. What do you think about this? Think about the end-user perspective. He sees in the chatter the mailmessage and thinks his customer is receiving the invoice. But his customer never gets it.
To me a functional person, this should not be possible and that is why I think this is a bug in Odoo. So I still hope we can reopen this issue.

**Comment by pedrobaeza** [comment]
For me that's not a problem, but an advantage: you can check that mails and fix the thing.

**Comment by yung-wang** [comment]
But what about the end-user? He will only know after the payment term has ended or maybe call the customer. That can be quite some time. The end-user might even start an credit control run.

**Comment by pedrobaeza** [comment]
Invoice sending through automated action is something that you have mounted in your system, not provided by default, so you should deal with possible drawbacks.

**Comment by yung-wang** [comment]
ok, no problem. Thanks for the investigation. We will try to find another way to solve this.

**Comment by pedrobaeza** [comment]
Take a look to https://github.com/OCA/social/tree/11.0/mail_tracking

**Comment by yung-wang** [comment]
Thanks, we are using mail_tracking also. Its a great module. Our business case is that we validate Invoices in batch (50+). So for the end-user difficult to find out if something has happened. But maybe I just have to give them access to the mail queue.

**Comment by pedrobaeza** [comment]
There's an improvement we have in our roadmap for `mail_tracking` that is to have a filter over all documents that inherit `mail.thread` to filter which of them have any kind of error, so it's checkable through regular tree view. But we haven't got funding for this yet.

**Comment by yung-wang** [comment]
Maybe we can help with it, I will ask around.

**Comment by pedrobaeza** [comment]
OK, if you want, I can share the technical design for developing that.
