### ISSUE TITLE
Stock Quants with lot are ignored

### ISSUE THREAD

**Issue by marcwimmer** [odoo/odoo#32319]
Impacted versions:
11.0

Steps to reproduce:
- Add 10 Products without lot to stock
- remove 1 Product by lot number from stock
- click "Update Stock Quantity" in product form

--> wrong stock.move is done - it is ignoring the lot move from above.

Background:
addons/stock/models/product.py line 101:
if lot_id is not None:     so a domain is created filtering out any stock move with a lot.

Seems to be fixed in V12 - there is no serial field in the wizard.

**Comment by pedrobaeza** [comment]
I don't get the exact steps to reproduce the problem. Can you get some screenshots or a video?

**Comment by Yenthe666** [comment]
Hi there,

As there has been no additional feedback or reaction in over a month I'm closing off this bug report.
Feel free to respond with more details and we'll reopen it then.

Regards,
Yenthe
