### ISSUE TITLE
[8.0] Calendar shows wrong recurring event times

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#3232]
Impacted versions:

8.0 and 7.0

Steps to reproduce:
create calendar entry with recurring events
. weekly with end date

Current behavior:
calendar views show wrong times
check this image, settings of event and views
![odoo-recurring-events](https://cloud.githubusercontent.com/assets/4398840/4732111/ea9ca186-59b6-11e4-96d9-436b2e859676.png)

Expected:
correct times in calendar views...

If there is a issue in Timezone Settings, let me know ;)

Tested in runbot: http://23393-8-0-9d5fb6.runbot6.odoo.com/web

**Comment by hamlinux** [comment]
Is there any progress on this issue.  i am using Version 8.0-20150401 from the official Docker build and this is a critical CRM function for one of my customers.  They need to be able to schedule recurring events N weeks into the future for X recurrances however for example a recurance that should be set for 14-10-2015 is set for example 3-1-2016.  Any help would be greatly appreciated

**Comment by Yenthe666** [comment]
@mart-e there still seem to be some problems with this in 8.0.
I've created a recurring meeting like this:
![image](https://cloud.githubusercontent.com/assets/6352350/15773588/02bd106a-2978-11e6-9959-b099fa60beae.png)

When I look in the treeview:
![image](https://cloud.githubusercontent.com/assets/6352350/15773604/23a0b08e-2978-11e6-9d2e-0adaf21989a7.png)
All of a sudden (starting at 04/11/2016) the time changes by an hour? Why?
After a while it again moves from 09:00 to 10:00:
![image](https://cloud.githubusercontent.com/assets/6352350/15773683/90266410-2978-11e6-852c-810d5090eb78.png)

**Comment by Yenthe666** [comment]
@mart-e this problem is also in V9.

**Comment by mart-e** [comment]
@Yenthe666 what you show looks like a daylight saving shift. The issue reported in the first post looks like a problem of configuration between the user and browser timezone.

**Comment by Yenthe666** [comment]
I actually forgot the daylight saving shift as an option, thanks for pointing that out. Well, I did try with another timezone on the user to simulate the major time difference but I couldn't reproduce that one.

**Comment by be-cloud-js** [comment]
Hello,

Is there any work around or way to plan recurring events over daylight saving shift ?

Jerome

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@be-cloud-js I don't believe there is at the moment, there is another report about this somewhere too.

Regards,
Yenthe

**Comment by JonathanStein** [comment]
We have tried to solve this problem in version 8 with the following read method. (I think the problem still occurs in later versions, and it should be possible to port the method).
Feel free to comment on the approach - we haven't tested it much yet.

```
from openerp import api, fields, models, tools, _
from openerp import fields as api_fields  # Needed in read method because of naming conflict
from datetime import datetime, timedelta
import pytz

class CalendarEvent(models.Model):
    _inherit = 'calendar.event'

    def read(self, cr, uid, ids, fields=None, context=None, load='_classic_read'):
        '''
        Adjust time fields for recurring events when recurrence DST and master DST is different
        '''
        res = super(CalendarEvent, self).read(cr, uid, ids, fields=fields, context=context, load=load)
        data = []
        # Get the timezone from context
        tz = context and context.get('tz')
        if tz:
            tz = pytz.timezone(tz)
        for r in res:
            # Adjust for DST if event is not allday and id is a string (it's not the master event) and timezone is set
            if not r.get('allday') and isinstance(r['id'], (basestring)) and tz:
                # Find the DST status of the master and the current event
                master_id = self.browse(cr, uid, int(r['id'].split('-')[0]), context=context)
                master_dst = tz.localize(api_fields.Datetime.from_string(master_id.start_datetime)).dst()
                current_dst = tz.localize(datetime.strptime(r['id'].split('-')[1], '%Y%m%d%H%M%S')).dst()
                # Check for differences
                if master_dst and not current_dst:
                    delta = timedelta(hours=1)
                elif not master_dst and current_dst:
                    delta = timedelta(hours=-1)
                else:
                    delta = False
                if delta:
                    # Current event has different DST status than master - adjust possible time fields
                    for f in ['start', 'stop', 'start_datetime', 'stop_datetime']:
                        if f in r and r[f]:
                            # The field exists and is not false - adjust the time
                            r[f] = api_fields.Datetime.to_string(api_fields.Datetime.from_string(r[f]) + delta)
            data.append(r)
        return data
```
