### ISSUE TITLE
Multiple-paginated sale orders scramble product sequences

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#32333]
Impacted versions: 12.0 (That we've tested)

Steps to reproduce:
- Add enough products to a sale order that the form view shows pagination (over 40 will do it)
- Add a section and move it around

Current behavior: Some products will be out of order below the new section

Expected behavior: Products should maintain their orders and positions

Tested on runbot, and it happens there too.

**Comment by pedrobaeza** [comment]
Can you please add a video explaining this?

**Comment by reinaldoramosarxi** [comment]
Hello,

Sorry, we tried to reproduce it on runbot again but never managed to. Then we tested that again on our deployed servers and it only happens in the one that originally had the problem, so maybe the sequence is being overridden somewhere in that server.

It's probably a non-issue, so I'll close it for now.
