### ISSUE TITLE
Cant remove field in search ( set searchable = False)

### ISSUE THREAD

**Issue by advance** [odoo/odoo#32342]
Impacted versions: 11

I want remove field from advance tree view search filter.
I also want that this field will store.
I set attr searchable = False, but it not work. (in python)
In code i found this 

@property
def _description_searchable(self):
    return bool(self.store or self.search)

Is it mean i cant set nonsearchable for stored field??

Is it bad to change code this way? 

    @property
    def _description_searchable(self):
        return bool(self.searchable and (self.store or self.search))

and add 'searchable':True to _slots ( class class Field)
dedault it will be searchable like now, but if u want off it.... it will work.

**Comment by pedrobaeza** [comment]
This is not possible right now in current framework status, so it's not your error. Simply, a non supported feature.

This has been addressed any way in future v13 version, if I don't remember bad, but I don't have details right now.

Any way, closing this as no issue, but unsupported feature.
