### ISSUE TITLE
point_of_sale: point of sale stock management and restrictions

### ISSUE THREAD

**Issue by umiphos** [odoo/odoo#32356]
Impacted versions:
12.0

**Steps to reproduce:**
- Create a new season and add a couple of orders
- Close the session
- Open a new(different session) and go to orders
- Return products

**Current behavior:**
The return will be made into another session, I know it's expected, but, can be a restriction or configuration added to not allow orders to be closed from another session? this might be useful for saas users

Video/Screenshot link (optional):
[![IMAGE DESCRIPTION](http://img.youtube.com/vi/Y7kTZZh3pEY/maxresdefault.jpg)](https://youtu.be/Y7kTZZh3pEY "Video description")

**Comment by pedrobaeza** [comment]
Why is this useful for saas users? And what is the exact problem with current method?

**Comment by umiphos** [comment]
I've a current case where it's needed for the admin to cancel certain orders, I know that behavior it's not expected by POS, because you will return products in the session you are opening, but if we add that check in configuration of the session to not allow orders from another session to be returned, then we can protect users from a future headache.

The exact problem is that if we allow admins to return products whether its the session of the order or not, we are going to mess around with the inventory if each session has a different warehouse configuration.

What do you think? @pedrobaeza

**Comment by pedrobaeza** [comment]
Are you sure about that? AFAIK, when you return products, locations are taken from previous picking, so no possible side effect although you do from other session.

**Comment by umiphos** [comment]
@pedrobaeza I've not been able to replicate the issue in odoo, it happen in the saas of the client, let me check again how they have configured their warehouses and their logic

**Comment by switch87** [comment]
@umiphos for functional problems on saas you should submit a support ticket on the website of Odoo. The support team has the necessary tool-set to find a specific solution for your client. https://www.odoo.com/help

**Comment by umiphos** [comment]
Closing the issue for not been able to replicate the error in runbot about the moves in the stock
