### ISSUE TITLE
Set `qty_delivered` as `product_uom_qty` if not moves

### ISSUE THREAD

**Issue by AfroMonkey** [odoo/odoo#32354]
https://github.com/odoo/odoo/blob/4df568549a685cb38cd66f6098e057ebee8be656/addons/sale_mrp/models/sale_mrp.py#L20

This line evaluate to `True` if not moves are in `line`

**Comment by Yenthe666** [comment]
Hi,

Please make a PR if you believe something is wrong and if you already provide a 'fix', it'll get handled a lot faster and better 😉 

Regards,
Yenthe

**Comment by sle-odoo** [comment]
Closing since the linked per is merged.

Thanks!
