### ISSUE TITLE
Regarding the Open Source License adopted

### ISSUE THREAD

**Issue by WoodpeckerBaby** [odoo/odoo#32350]
I noticed today that this repository is under GNU LGPL license, which is not permissive. For all projects under Cloud Native Computing Foundation (https://www.cncf.io) or Apache, the Apache 2.0 License is mandatory. I'm not sure if the license is there intentionally or just there because Github put it there. 

For a simplified comparison, please see this table here https://choosealicense.com/appendix/

Basically, it means if it is a variant of GNU license, the software cannot be used, and there is no point developing anything on top of it. 

I'm also confused about why the enterprise addon is not open source since it is a derivative or developed on top of the main program. Isn't that the whole point of GNUing? 

I hope this repo can adopt the Apache 2.0 license, otherwise, there will be a lot of legal issues down the road.

**Comment by pedrobaeza** [comment]
This project is not under Cloud Native Computing Foundation. Why are you saying so?

**Comment by WoodpeckerBaby** [comment]
> This project is not under Cloud Native Computing Foundation. Why are you saying so?

Yes, but CNCF, Apache, BSD, MIT, Creative Common, is usually the standard for open source project. For example, the RISC-V project is licensed under Berkeley, the Kubernetes Project is licensed under Apache 2.0. One of the direct competitors of this software - Apache OFBiz project (https://ofbiz.apache.org) is, well, obviously licensed under Apache.

**Comment by Elkasitu** [comment]
> I'm also confused about why the enterprise addon is not open source since it is a derivative or developed on top of the main program. Isn't that the whole point of GNUing?

They're not; they simply make use of odoo's API.

**Comment by pedrobaeza** [comment]
@WoodpeckerBaby `the standard for open source projects` is relative. All are open source, and you can't discuss that. If you don't like this license, just pick up another project, but the license of this open source project has been decided some time ago by the company driving the project according several parameters and it's not going to change for now.

**Comment by WoodpeckerBaby** [comment]
> the standard for open source projects is relative. 

The relativity of relative is relative. Projects that are similar to this one use one of the aforementioned licenses, that is the CNCF, Apache, BSD, MIT, Creative Common. This one is an oddball. For things that obviously need all modifications to be open sourced are licensed under Mozilla. Compilers like clang are licensed under BSD. 

> All are open source, and you can't discuss that

Of course, I can discuss that. It's a free country and this is an open project. 

> but the license of this open source project has been decided some time ago by the company driving the project

That's the point of this question. It would be more helpful if the owner (that is the for-profit company) of the project gives a rationale behind it. Instead of having you and I guessing around. 

> according [to] several parameters

Would be a lot more helpful if you provide citations to those parameters. That's the point of the question. 

> and it's not going to change for now

Well, since you don't own the project, I can't regard that statement with sufficient weight.

**Comment by elicoidal** [comment]
@woodpeckerbaby discussion is always welcome of course.
Nevertheless as @pedrobaeza said, the decision was taken 3 years ago by Odoo SA. I let you google it but you can find some information here:
* https://www.odoo.com/zh_CN/blog/odoo-news-5/post/adapting-our-open-source-license-245

You are welcome to argue the change or alternative for the license but I am not sure this place (dedicated for technical question / issues) is the best place to do it. 

You might better go to the [forum](https://www.odoo.com/forum/help-1) or one of the [mailing lists](https://www.odoo.com/forum/help-1)

**Comment by mart-e** [comment]
> Well, since you don't own the project, I can't regard that statement with sufficient weight.

You can trust Pedro. I confirm that part, we (Odoo SA) have no plan to change the license at the moment.
Please check the blog post given by Eric regarding the rationale of changing to LGPL.
This was not accidental but to serve our goal of being able to use both open source _and_ proprietary modules (let it be [our modules](https://accounts.odoo.com/page/editions) or made by [somebody else](https://apps.odoo.com/)).

> Basically, it means if it is a variant of GNU license, the software cannot be used, and there is no point developing anything on top of it.

I disagree with that interpretation. Check a presentation we made about it at the time of the change.
https://www.odoo.com/slides/slide/open-source-licenses-196

**Comment by WoodpeckerBaby** [comment]
@mart-e @elicoidal Thank you for all the information above. I have reviewed the posts and the presentation. Is there a reason why Apache 2.0 would not fulfill what LGPL's role for Odoo SA? I am curious how you guys think about Apache 2.0 license and the potential reasoning for deciding against it. I would be far more convenient for most developers and companies of any size to integrate an Apache 2.0, MIT, or a variant of the BSD license.

**Comment by mart-e** [comment]
The choice for LGPL is more historical. @fpodoo went with GPLv2 in 2005, at the creation of the software. Changing to AGPL and then LGPL were the easiest as variants of the current license.

Maybe Fabien can explain better the rationale of his decision for GPL at that time but I believe the disclosure of the modified version was explicitly what we wanted. We are fine with people forking the software and reusing it for their own business as long as their fork remain open source.
However we do not allow to fork Odoo and make a proprietary product without giving anything back to the community.

> There is a lot of internal logic in the core that I obviously need to modify before I can use it

Not so obvious to me I am afraid. Odoo is supposed to be very modular and quite generic so allows to go pretty far in the customisation without changing the internals of the core. What is blocking you and what you can't change with your own module?
Even if changing directly the internal is sometimes easier, it is often not a good idea for the maintenance. Are you sure it is the only way?

**Comment by WoodpeckerBaby** [comment]
Okay, fine, I will ride with LGPL wagon and open source modified everything. I won't even bother forking off. I will just adopt the main tree and push everything up if I think it is worthy of a change. The first idea so far I have is to explore more of the software, and make sure I can cleanly separate the PostgreSQL database from the Odoo runtime. By that I mean they must be able to **not** live in a single container in Kubernetes. The Odoo runtime must be able to run multiple instances simultaneously within one Kubernetes cluster and also with instances from other clusters, federated or un-federated, with reference to a single master database locally within a cluster or remotely over a secure connection. The PostgreSQL databases must be able to run real-time master-slave replication where the master database node is behind a scheduler. The data structure used by Oodo runtime must be flexible and adaptable so that I don't have to make the data tables the certain way that will break compatibility with other code that is also pulling Oodo data from the database. So I have to closely review the source code to see if I can design a new compatible architecture to integrate Oodo nicely. The interface reminds me of Oracle NetSuite by the way. When I was auditing a multibranched company once, I worked a lot with their NetSuite software. That was some pretty fun times busting cooked books. My background by education is in Electrical and Computer Engineering, and also in Econometrics.
