### ISSUE TITLE
Payment Stripe acquirer is not working with portal user on odoo 10 eCommerce

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#32376]
Impacted versions: odoo 10

Steps to reproduce:

Install payment acquirer Stripe in backend and fill the test credentials. Make it published on website.

Current behavior:
Works well with admin account. For portal user, select Stripe click 'Pay Now' button will get '400: Bad Request' error. And I got the following errors in log:

2019-04-03 09:02:43,804 1065 WARNING My-Server odoo.http: No CSRF validation token provided for path '/shop/payment'

Odoo URLs are CSRF-protected by default (when accessed with unsafe
HTTP methods). See
https://www.odoo.com/documentation/9.0/reference/http.html#csrf for
more details.

* if this endpoint is accessed through Odoo via py-QWeb form, embed a CSRF
  token in the form, Tokens are available via `request.csrf_token()`
  can be provided through a hidden input and must be POST-ed named
  `csrf_token` e.g. in your form add:

      <input type="hidden" name="csrf_token" t-att-value="request.csrf_token()"/>

* if the form is generated or posted in javascript, the token value is
  available as `csrf_token` on `web.core` and as the `csrf_token`
  value in the default js-qweb execution context

* if the form is accessed by an external third party (e.g. REST API
  endpoint, payment gateway callback) you will need to disable CSRF
  protection (and implement your own protection if necessary) by
  passing the `csrf=False` parameter to the `route` decorator.
                    
2019-04-03 09:02:43,811 1065 WARNING My-Server odoo.addons.website.models.ir_ui_view: Could not find view object with xml_id 'website.400'

Expected behavior:
Stripe payment window should popup for fill in credit card information.

The Strange thing is that admin account works well. I use many third party apps and I use a multi-website app as well as a commercial theme. I do not know who to blame. And I am new to python. So any help is appreciated. Thank you!

![2](https://user-images.githubusercontent.com/10336015/55472841-abfe2a00-563f-11e9-8794-a8efccce7f7a.png)
![1](https://user-images.githubusercontent.com/10336015/55472842-ac96c080-563f-11e9-9512-98201f7dbd68.png)

**Comment by rdeodoo** [comment]
Hi, I just tested it on runbot in Odoo 10.0 community edition and it worked as expected both for the admin and portal user.

Could you please confirm that you are able to reproduced the error on runbot, and if so how?

Thank you

**Comment by frankmiao2015** [comment]
> Hi, I just tested it on runbot in Odoo 10.0 community edition and it worked as expected both for the admin and portal user.
> 
> Could you please confirm that you are able to reproduced the error on runbot, and if so how?
> 
> Thank you

@rdeodoo Sorry for the late reply. I found the issue was raised by the following oca module. I uninstalled it and the issue was gone. You can remove this issue of mark it as solved. Thank you.

https://github.com/OCA/website/tree/12.0/website_js_below_the_fold
