### ISSUE TITLE
stock quant package location_id

### ISSUE THREAD

**Issue by htetard** [odoo/odoo#32395]
Impacted versions:
12
Steps to reproduce:
Move package PACK01 from Stock/location1 to Stock/location2

Move package PACK02 from Stock/location2 to initial Stock/location1

Current behavior:
field location_id of stock package is not updated in the second case
Expected behavior:
field location_id should always bu updated
Video/Screenshot link (optional):
https://youtu.be/FQjotr9DzZw

**Comment by pedrobaeza** [comment]
Please specify HOW you move package with all detailed steps. Even with video or screenshots.

**Comment by htetard** [comment]
Sorry : video here : https://youtu.be/FQjotr9DzZw

Regards,

**Comment by htetard** [comment]
Found a solution.
Change _compute_package_info@api.depends and add quant_ids.quantity field; it's working.
![image](https://user-images.githubusercontent.com/11721940/55552942-216d0780-56df-11e9-87af-11a7784c52e1.png)

**Comment by Yenthe666** [comment]
@htetard can you please convert this into a PR?

**Comment by sle-odoo** [comment]
fixed by 7a5f1068fa60a93c59273040db17811617a039d7
