### ISSUE TITLE
Unable to find Wkhtmltopdf on this system - needs better text

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#3239]
addons / report / static / src / js / qwebactionmanager.js

the log data says
openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf

the problem is the browser cache - must be cleared (chrome) to get rid of this message

suggestion:
add 
"Try to clear browser cache" 
to the error message

**Comment by IsNull** [comment]
Ah finally, this was the hint! Thank you for mentioning the cache problem. After 2h digging completly in the wrong direction...

I think your suggestion is a good idea, probably also improve the logging when invoking a external program (include error code etc so it is easy to tell if the invoked tool did its job)

**Comment by Yenthe666** [comment]
@sle-odoo can this one be closed or should it still be improved?

**Comment by jpaulin** [comment]
By the way I noticed that 'W' is used in the lookup of the wkhtmltopdf executable, whereas Unix is case-sensitive. It means that (for example me now working ad hoc on a Odoo 10 version) a workaround for one kind of wkhtmltopdf problem was to copy the PDF-printing tool (executable) to a new name. 

Odoo really tries wrongfully tries to look up a tool by literal name: 
/usr/bin/Wkhtmltopdf

So open up a shell on that machine. Then:

in /usr/bin
cp ./wkhtmltopdf ./Wkhtmltopdf

Symbolic links might also work. What do you think? Did this relate to the problem, by the way? I've seen a bit of variants around the PDF printing here in Github.

**Comment by Yenthe666** [comment]
@sle-odoo friendly reminder.

**Comment by sle-odoo** [comment]
We try to find "wkhtmltopdf", not "Wkhtmltopdf", [see here](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_actions_report.py#L42).

Also, we did not have any feedback regarding the original issue so i suppose the improvement in changing the message is really minor. I thus close this issue.

Regards
