### ISSUE TITLE
wrong Invoice layout in pt_BR

### ISSUE THREAD

**Issue by rogeriojlle** [odoo/odoo#32402]
Impacted versions:
    12 an 13 (master)
Steps to reproduce:
    change language from english to portuguese ( debug mode active is irrelevant )

Current behavior:
    wrong Invoice layout: not show the report

Expected behavior:
    show report in a iframe

Video/Screenshot link (optional):
![english](https://user-images.githubusercontent.com/562996/55511793-d21fcc00-5637-11e9-8346-f4016bf88301.png)
![portuguese](https://user-images.githubusercontent.com/562996/55511797-d51abc80-5637-11e9-9a75-7534c0c4dd0e.png)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by rogeriojlle** [comment]
I used the debian versions nightly, installed on the same date that I posted the images.
Even in runbot the same behavior happens ... The invoice display only appears in the English language
Here are sample videos, one in each version, 12 and master


[videos.zip](https://github.com/odoo/odoo/files/3044572/videos.zip)

**Comment by rogeriojlle** [comment]
To reproduce the error, in a fresh install, add the invoicing module and the Brazilian Portuguese language pack

**Comment by pedrobaeza** [comment]
So the problem is that it appears in English? That's logical if the translation is not done... See https://github.com/odoo/odoo/wiki/Translations for contributing to them.

**Comment by rogeriojlle** [comment]
I agree, but in case of not being translated it would not imply to continue exhibiting in English, keeping the layout correct?
Notice that even CSS changes when the language is changed.
How do I find the Transifex item that corrects this page?

**Comment by pedrobaeza** [comment]
> I agree, but in case of not being translated it would not imply to continue exhibiting in English, keeping the layout correct?

Then the translation has been somehow corrupted.

> How do I find the Transifex item that corrects this page?

Compare both (English and pt_BR versions) and look for the differences.

**Comment by rogeriojlle** [comment]
Good news!

The module "account" has a typo, it was missing the **\</b>** tag, which messed up the whole layout.
I already suggested the change in transifex.
For those who have Odoo already installed, it is in line 297 of the file
`/usr/lib/python3/dist-packages/odoo/addons/account/i18n/pt_BR.po`
```
#. module: account
#: model_terms:ir.ui.view,arch_db:account.portal_invoice_page
msgid "<i class=\"fa fa-fw fa-comments\"/><b>Send message</b>"
msgstr "<i class=\"fa fa-fw fa-comments\"/><b>Enviar mensagem"</b> <---here
```

**Comment by pedrobaeza** [comment]
OK, glad to hear that. @mart-e maybe you can accept that suggestion?

**Comment by mart-e** [comment]
Thanks for the report, I see somebody else already did the correction 2 hours ago
https://www.transifex.com/odoo/odoo-12/translate/#pt_BR/account/153230438?q=text%3A'Send+message'
The correction will be in the next synchronisation of translations, on Sunday
