### ISSUE TITLE
Wrong Product wise Sale total in the Sales report

### ISSUE THREAD

**Issue by burhan-vakharia** [odoo/odoo#32413]
Impacted versions: V11 Community

Steps to reproduce:
1) Initiate a new instance in Odoo runbot.
2) Create a new product(Product ABC) with sale price 100 and publish it on Website - https://prnt.sc/n7ckid .
3) I purchased 3 quantities of it and here is the checkout page - https://prnt.sc/n7cl4l .
4) Confirm Payment - https://prnt.sc/n7clwe
5) Now go to the backed and manually confirm the order. - https://prnt.sc/n7cmdm .
6) Now head to Sales > Reporting > Sales. Switch to the Pivot view. Now group by Sales Channel and then groupby Product. - https://prnt.sc/n7cnm0 . 

Current behavior: Wrong amount shown for Product ABC which is 233.75.

Expected behavior: Amount must be shown 300.

Video/Screenshot link (optional):

Screenshot - https://prnt.sc/n7cnm0

Video Link - https://nimb.ws/gaUOQE

**Comment by sswapnesh** [comment]
@burhan-vakharia  You missed Currency rate which is 1.2834 here.
![Screenshot from 2019-04-04 21-31-30](https://user-images.githubusercontent.com/16624719/55570729-9fea9900-5721-11e9-9c26-06c2beb28a71.png)

(Change it to 1 If Its base currency)
So here it converted based on Currency rate (300 / 1.2834 = 233.75)

**Comment by pedrobaeza** [comment]
Thanks for the insight, @sswapnesh, so it's clear, and thus, closing the issue.
