### ISSUE TITLE
How to restrict users from editing the website that is not their company

### ISSUE THREAD

**Issue by andete22** [odoo/odoo#32420]
I want to restrict the user to the website edition if it does not belong to your company.

But if I enter as UserB (which belongs to the COB company), I can edit the COA website.

To configure it I followed these steps:
https://www.odoo.com/documentation/user/12.0/website/publish/multi_website.html

It is also configured: settings >> active users >> select user >> under "allowed companies" set the company the user has rights to

My configuration is this:

Company A
https://i.ibb.co/HXtbsCs/CoA.png

Company B
https://i.ibb.co/bFTZ7dc/CoB.png

User A, with your only company allowed (Editor and designer mode)
https://i.ibb.co/WBQNgQD/UserA.png

User B, with your only company allowed (Editor and designer mode)
https://i.ibb.co/GHkj3Zh/UserB.png

Users Company A (Only UserA and administrator belong)
https://i.ibb.co/SxFp0Tq/Usuarios-Co-A.png

Users Company B (Only UserB and administrator belong)
https://i.ibb.co/tP1bCZY/Usuarios-Co-B.png

Websites (Default configuration)
https://i.ibb.co/rw9ctv4/Websites.png

Website A
https://i.ibb.co/Vjhnt4m/WebA.png

Website B
https://i.ibb.co/VpYNwCJ/WebB.png

Website A config (WebB in company CoB)
https://i.ibb.co/8jQ54cx/Web-A-config.png

Website B config (WebB in company CoB)
https://i.ibb.co/HChCtzD/Web-B-config.png

I also have configured as:
Multiwebsite and multicompany
https://i.ibb.co/fNSmq1q/multiwebsite.png
https://i.ibb.co/Z6pYZYt/multicompany.png

When I enter as another user (for example UserA) I can edit all the websites (for example WebB)
https://i.ibb.co/4ggrRqK/error1.png

And here editing a website to which my company does not belong
https://i.ibb.co/6bfvL29/error2.png

<b>What is expected is that you can only edit the websites that belong to our company</b>

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

AFAIK, what you want to achieve is not possible.

Closing this by the reason above.

**Comment by Yenthe666** [comment]
Indeed not possible out of the box, unless you can remove the full access for the company where the user shouldn't be able to edit the webpages.

**Comment by andete22** [comment]
> Lo sentimos, este no es un problema de Odoo, sino una pregunta. Debe hacerlo en los foros oficiales de Odoo ( https://www.odoo.com/forum/help-1 ) o en las listas de correo ( https://odoo.com/groups ), pero no aquí.
> 
> AFAIK, lo que quieres lograr no es posible.
> 
> Cerrando esto por el motivo anterior.

Ok, I've already sent it to the right forum. Thank you

**Comment by andete22** [comment]
> De hecho, no es posible de forma inmediata, a menos que pueda eliminar el acceso completo a la empresa donde el usuario no debería poder editar las páginas web.

Can you explain how I can do it?
https://www.odoo.com/es_ES/forum/ayuda-1/question/how-to-restrict-users-from-editing-the-website-that-is-not-their-company-147984
