### ISSUE TITLE
[12] Error: QWeb2: Template 'mail.systray.MessagingMenu' not found

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#32432]
12.0 package install from Odoo on Ubuntu server 18.04.2 LTS, postgresql on a separate server. Database in demo mode, ecommerce module installed. website access is OK, Apps is OK, but every other apps (Discuss, Website, Invoicing, Settings) show blank page (only top menu bar) with error message.

### web client message in debug mode with assets
[12] Error: QWeb2: Template 'mail.systray.MessagingMenu' not found
`http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:48
Traceback:
exception@http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:48:19
_render@http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:482:24
render@http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:450:21
renderElement@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:246:21
_widgetRenderAndInsert/<@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:397:13
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3271:48
_widgetRenderAndInsert@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:393:33
prependTo@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:234:16
_loadItems/<@http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:50:29
_.forEach@http://vps670169.ovh.net:8069/web/static/lib/underscore/underscore.js:145:9
_loadItems@http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:47:9
start@http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:28:9
OdooClass.extend/</prototype[name]</<@http://vps670169.ovh.net:8069/web/static/src/js/core/class.js:90:35
attachTo/<@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:177:20
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3271:48
attachTo@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:176:33
start@http://vps670169.ovh.net:8069/web/static/src/js/chrome/menu.js:71:9
OdooClass.extend/</prototype[name]</<@http://vps670169.ovh.net:8069/web/static/src/js/core/class.js:90:35
_widgetRenderAndInsert/<@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:399:20
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
add@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:383:49
then/<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3332:25
then@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3271:48
_widgetRenderAndInsert@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:393:33
prependTo@http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:234:16
instanciate_menu_widgets/<@http://vps670169.ovh.net:8069/web/static/src/js/chrome/web_client.js:125:23
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3321:62
rpc/<@http://vps670169.ovh.net:8069/web/static/src/js/services/ajax_service.js:16:17
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3321:62
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3321:62
genericJsonRpc/<@http://vps670169.ovh.net:8069/web/static/src/js/core/ajax.js:59:9
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3276:86
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
then/</</<@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:3231:49
done@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:9275:33
callback@http://vps670169.ovh.net:8069/web/static/lib/jquery/jquery.js:9685:57`

### message from browser console
`Error: QWeb2: Template 'mail.systray.MessagingMenu' not found qweb2.js:48:19
http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:48
http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:482
http://vps670169.ovh.net:8069/web/static/lib/qweb/qweb2.js:450
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:246
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:397
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:393
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:234
http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:50
http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:47
http://vps670169.ovh.net:8069/web/static/src/js/chrome/systray_menu.js:28
http://vps670169.ovh.net:8069/web/static/src/js/core/class.js:90
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:177
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:176
http://vps670169.ovh.net:8069/web/static/src/js/chrome/menu.js:71
http:/</prototype[name]</< http://vps670169.ovh.net:8069/web/static/src/js/core/class.js:90
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:399
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:393
http://vps670169.ovh.net:8069/web/static/src/js/core/widget.js:234
http://vps670169.ovh.net:8069/web/static/src/js/chrome/web_client.js:125
http://vps670169.ovh.net:8069/web/static/src/js/services/ajax_service.js:16
http://vps670169.ovh.net:8069/web/static/src/js/core/ajax.js:59`

`/etc/odoo/odoo.conf` double checked for addons path. 
`im_support/static/src/xml/systray.xml` in the right place.

I can provide odoo-server.log with odoo.addons.web.http:DEBUG handler

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by zeroheure** [comment]
Indeed I've checked my deployment, because I thought like you. But there is nothing special :  
it is just a new standard server on which I've setup Odoo yesterday : `apt install odoo`, external database config in `odoo.conf`, then create demo db and module install. That's all.

**Comment by pedrobaeza** [comment]
But as said, on runbot it's not failing. Please check possible extra modules in addons path.

**Comment by zeroheure** [comment]
there is no extra modules

**Comment by zeroheure** [comment]
new VPS, new install, new db with demo datas, no modules. Same error on Settings page.

**Comment by pedrobaeza** [comment]
Are you starting with a language different from English?

**Comment by zeroheure** [comment]
French

**Comment by pedrobaeza** [comment]
Then that should be the problem: an incorrect translation in one of that elements.
