### ISSUE TITLE
Traslations does not works for buttons in Odoo 12 

### ISSUE THREAD

**Issue by stesifrancesco** [odoo/odoo#32450]
Impacted versions:
Odoo 12
Steps to reproduce:
Load Italian translation (in my case) thank skip to this language than go (for example) in sale's Form
Current behavior:
Buttons are not traslated both in base addons and in custom addons:

Expected behavior:
If traslation exist buttons are traslated

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/17119418/55622807-8426d780-57a1-11e9-91e0-cd3ef6040223.png)

**Comment by pedrobaeza** [comment]
Are you working with any `--dev` option?

**Comment by stesifrancesco** [comment]
Yes....thanks a lot for your advice...I understood my mistaket:
without --dev=all it works perfetct.
Thanks again

Francesco
