### ISSUE TITLE
cannot inherit SwitchCompanyMenu

### ISSUE THREAD

**Issue by bjccdsrlcr** [odoo/odoo#32497]
Impacted versions:
 version 10.0
Steps to reproduce:
when a user has multicompany , we can change the current company , but the ir.rule will always occured, so change the behavior of click the dropdown company menu, but without the return {SwitchCompanyMenu: SwitchCompanyMenu} we cannot inherit the SwitchCompanyMenu widget
Current behavior:
just reload the current page
Expected behavior:
redircting /web
Video/Screenshot link (optional):
`odoo.define('web.SwitchCompanyMenu', function (require) {
    "use strict";

    var Model = require('web.Model');
    var session = require('web.session');
    var SystrayMenu = require('web.SystrayMenu');
    var Widget = require('web.Widget');

    var SwitchCompanyMenu = Widget.extend({
        template: 'SwitchCompanyMenu',
        willStart: function () {
            if (!session.user_companies) {
                return $.Deferred().reject();
            }
            return this._super();
        },
        start: function () {
            var self = this;
            this.$el.on('click', '.dropdown-menu li a[data-menu]', _.debounce(function (ev) {
                ev.preventDefault();
                var company_id = $(ev.currentTarget).data('company-id');
                new Model('res.users').call('write', [[session.uid], {'company_id': company_id}]).then(function () {
                    location.reload();
                });
            }, 1500, true));

            self.$('.oe_topbar_name').text(session.user_companies.current_company[1]);

            var companies_list = '';
            _.each(session.user_companies.allowed_companies, function (company) {
                var a = '';
                if (company[0] === session.user_companies.current_company[0]) {
                    a = '<i class="fa fa-check o_current_company"></i>';
                } else {
                    a = '<span class="o_company"/>';
                }
                companies_list += '<li><a href="#" data-menu="company" data-company-id="' + company[0] + '">' + a + company[1] + '</a></li>';
            });
            self.$('.dropdown-menu').html(companies_list);
            return this._super();
        },
    });

    SystrayMenu.Items.push(SwitchCompanyMenu);
     // return {
    //     SwitchCompanyMenu: SwitchCompanyMenu
    // }
});`

**Comment by pedrobaeza** [comment]
Sorry, but this something expected and it's not going to be changed. It's preferable to be kept in the same URL, although if you are in a document with no access from the other company, you receive the error. For most of the cases (list view for example), this is not a problem.

Any overwrite you want to do is not an issue, but an improvement.

**Comment by HananeTech** [comment]
Hello,
@bjccdsrlcr I'm facing the same problem, did you find a solution to the issue?
