### ISSUE TITLE
[11.0] Picking validation with 5000+ move lines takes 20+ minutes

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#32525]
Impacted versions:

11.0

Steps to reproduce:

Create a transfer with 1 move and 5,000+ stock move lines
Validate the transfer

Current behavior:

Odoo spins for 20+ minutes to validate the picking.

Expected behavior:

The picking is validated in less than 5 minutes.

Pyflame graph:
[Picking-validation.zip](https://github.com/odoo/odoo/files/3055653/Picking-validation.zip)

Enterprise Ticket:
https://www.odoo.com/my/task/1965966

**Comment by max3903** [comment]
[20190408-inventory-valuation-report.zip](https://github.com/odoo/odoo/files/3056361/20190408-inventory-valuation-report.zip)

**Comment by max3903** [comment]
I am at commit https://github.com/odoo/odoo/tree/a9a8eeac1de7a62182ad8c32cc745c0ac093520b

**Comment by moylop260** [comment]
@sle-odoo 
FYI part of the performance issue is the following line for odoo 11.0:
 
 - https://github.com/odoo/odoo/blob/1cf284e91e88a0df95f9fd5fcadf5688d6709760/addons/stock/models/stock_quant.py#L224

I saw odoo 12.0 using a background process:
 - https://github.com/odoo/odoo/blob/c0d7a05730dca242ad60192b9905891e3afa9a90/addons/stock/models/stock_rule.py#L375

**Comment by fmdl** [comment]
`qaunt.unlink()` is a big issue in V11, and Odoo don't want patch in V12, but you can use this PR in V11 : https://github.com/odoo/odoo/pull/26513

**Comment by max3903** [comment]
@fmdl Thanks. I am down to 2 minutes now. :+1:

**Comment by moylop260** [comment]
> @fmdl Odoo doesn't want patch it in V12

FYI It is already patched in v12, see the following commit:
 - https://github.com/odoo/odoo/commit/c0d7a05730dca242ad60192b9905891e3afa9a90

**Comment by fmdl** [comment]
@moylop260 typing error :-)

**Comment by sle-odoo** [comment]
Hi,
I'm closing this one since it is fixed in v12.

Regards
