### ISSUE TITLE
Project Task Delecation

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#3252]
Try with latest runbot branch of odoo 8.
Go to Project Task,
Click on Delegate.

It opens wizard for "Project Task Delegate".
Create task from that wizard and set validation to "Pending or Done"

Now Click on Done to your parent task.

It is allow you to mark done your parent task without completing child task.

Thanks,
Nimesh

**Comment by Yenthe666** [comment]
Hi @nimeshcontractor ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
