### ISSUE TITLE
[11.0] No computed qty delivered with kit product- list of materials

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#32530]
Impacted versions:
11.0 maybe 12.0

Steps to reproduce:
Create a manufacturing product with a list of materials type kit and invoicing when delivered
Create a SO
Current behavior:
When delivering a part of the picking, the qty delivery is not computed until hole picking is transferred.
![image](https://user-images.githubusercontent.com/10233975/55764549-a171d500-5a31-11e9-85d8-c1878e00dc5b.png)

Expected behavior:
Delivery qty computed

Video/Screenshot link (optional):
https://youtu.be/H9M7QvUwtQk

OPW
1966170

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/odoo/commit/d5e3b1d04e6e97de3fed8d14b276c7c91bc02f79

**Comment by hugho-ad** [comment]
@simongoffin I've tried the same scenarios posted at the issue's video, and the behavior remains the same, could you reopen this please

**Comment by simongoffin** [comment]
@hugho-ad 
The delivered_qty on the SO line with a kit is of course not automatically updated
(as in this case, a right value is not computable, imagine 5 kits K composed by 5 units of component A and by 5 units of component B and you deliver 3 units of A and 4 units of B. What's the right value delivered for K in this case?). But the delivered_qty on the SO line
was not updatable  manually before the fix and now it's possible to edit it manually.
