### ISSUE TITLE
[12.0] My Quotations filter is misleading

### ISSUE THREAD

**Issue by gr22** [odoo/odoo#32541]
`<filter string="My Quotations" name="my_quotation" domain="[('user_id', '=', uid)]"/>`

It shows all the sale orders not just quotations. It could be called "My Orders" or added a condition to show only quotations.

**Comment by gdgellatly** [comment]
haha, the entire idea of quotations is misleading. however, TPTB at Odoo decided it was too confusing for users to see only quotations in the quotations menu. I kid you not. See the many similar issues raised and closed.

**Comment by Yenthe666** [comment]
Yeah and in all honesty so should this one be closed. We've gotten the feedback from Odoo numerous of times that this was done by design & not something they want(ed) to change.
@mart-e close off or shall we discuss this (again)?

**Comment by intero-chz** [comment]
@Yenthe666 @mart-e i'm just curious what will happen in Odoo 13. With this new column trigger feature for list views, wouldn't it be better to just minimize `sale.order` to one menu item?

**Comment by intero-chz** [comment]
@dbo-odoo what was the reason for closing this issue?

**Comment by dbo-odoo** [comment]
Hi @intero-chz 
see msgs from @Yenthe666 @gdgellatly from a few days ago - issue was raised before, this is a conscious choice, etc. etc.

**Comment by intero-chz** [comment]
@dbo-odoo thanks for the answer, but i had hoped that with this new feature a "new" discussion for at least Odoo13 is worth it.
