### ISSUE TITLE
Website: watch.js and IE8 Problem

### ISSUE THREAD

**Issue by davidbru** [odoo/odoo#3254]
Hello,

on my installation the ODOO website is not working in IE8 because it throws an error in watch.js.

In my last issue (https://github.com/odoo/odoo/issues/2957) it was briefly discussed whether watch.js as a whole is still needed, but there was no answer to that question.

The file in question: https://github.com/odoo/odoo/blob/8.0/addons/web/static/src/js/watch.js

I think if it is still needed it needs some rework to work with IE8:
http://stackoverflow.com/questions/21175290/object-defineproperty-alternative-for-ie8#21175380

Cheers,
David

**Comment by Yenthe666** [comment]
Hi @davidbru ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: you might want to use Google Chrome or Firefox for Odoo - it works way better there.

Regards,
Yenthe
