### ISSUE TITLE
how to send email at modification using python code

### ISSUE THREAD

**Issue by abhishek8singhai** [odoo/odoo#32545]
Impacted versions: 11

Steps to reproduce: Go to Purchase Order option. Create Purchase Order. Go to Automation steps. Here I want to send a email when there is any change to the form ( at the time of Confirm Purchase click). What I understood so far is that there is an option to write the python code to send a email if you want to use the option - At the time of modification to the form. 

I searched a lot in the google, but could not find any python code where I can use the variables from the form to get mail having reference from the record which is getting created. I am able to send the static mail but using the variable i could not find. 

Please let me know if someone is having a working custom code to be used under python code tab in Odoo 11. I want to send the mail by having the records order and order line items details. 

Thanks 

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @abhishek8singhai,

I'm sorry but the Github issue tracker is only for bug reports in the official code.
This is not the place to ask questions. You can do this at https://www.odoo.com/forum/help-1

In short: create an `@api.onchange` and in this onchange call the e-mail template to be sent.

Regards,
Yenthe
