### ISSUE TITLE
Website: Not-Editable Flag for certain snippets

### ISSUE THREAD

**Issue by davidbru** [odoo/odoo#3255]
Hello,

is there some kind of Not-Editable flag for snippets?

The reason I ask is: I made a snippet which uses RoyalSlider (http://dimsemenov.com/plugins/royal-slider/). If you load the page where you included the RoyalSlider snippet, the DOM of this snippet gets altered.

For example this original code: http://pastebin.com/qDvQDTk3
Is converted on page load into: http://pastebin.com/CLiLRf6y (notice the added rsBullets and the rsArrows)

If I now edit the page where the RoyalSlider plugin is placed, change some text in another totally unrelated content block and save the whole page the altered code get's saved as well. Which causes problems with the behavior of the plugin.

Is there such a flag and I'm simply not aware of? Or is it possible to create such a flag?

Cheers,
David

**Comment by Yenthe666** [comment]
Hi @davidbru,

I don't believe there is one in Odoo (sorry for the very late reply).
You're better of asking these kind of questions on the official help forums at odoo.com/help in the future. The Github issue tracker is only for bugs in the code really.

Regards,
Yenthe
