### ISSUE TITLE
[12.0] Can't delete Partner after commit abc45b19d02dffebfeb867feeb3051c6c751d0a0 

### ISSUE THREAD

**Issue by chrisdilbert** [odoo/odoo#32563]
Impacted versions:
**12.0**

Steps to reproduce:
- Open a partner 

- Try to delete partner

**What is the current behavior that you observe?**

Record does not exist or has been deleted.

This issue is caused by this commit abc45b19d02dffebfeb867feeb3051c6c751d0a0 
https://github.com/odoo/odoo/blob/abc45b19d02dffebfeb867feeb3051c6c751d0a0/addons/mail/models/ir_attachment.py#L20

**Comment by Yenthe666** [comment]
@len-odoo can you check please?

**Comment by len-odoo** [comment]
@Yenthe666 There's a subtlety of the ir.attachment model that was completely lost on me. We'll make a fix today.

**Comment by chrisdilbert** [comment]
@len-odoo Thanks!
