### ISSUE TITLE
chart of accounts UAE

### ISSUE THREAD

**Issue by shyamalajinju** [odoo/odoo#32573]
Impacted versions:11

Steps to reproduce:

Current behavior:

Expected behavior:Hi,

 I need my chart of accounts as per UAE standard which include 3 level grouping like  Expense->Indirect Expense->Employee Salary , How do I configure this in Odoo11 and how it will affect accounting reports, I need to categorize reports based on the parent category, like inside indirect expense employee salary account will be there while viewing balance sheet.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
