### ISSUE TITLE
[Feature]Allow views to disable sheet tag by a simple attribute

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#3257]
Hy,

Many people are asking me to "drop" the sheet part of some specific views. From now the only way to do this is to override the entire view and delete the sheet node.

It would be nice if we could implement something like that  :

```
Add a new attribute in the sheet tag that will be called "active"
use this attribute to manage the beahviour of the view, if it's active it'll work like now and if active=False then the behaviour will be ignored (A kind of removal)
Add a preference value in the user profile and in the context so that the info would be passed in actions and views.
```

Hope it could be considered as a good feature

**Comment by chesucr** [comment]
+1

**Comment by chesucr** [comment]
Check another workaround [in the answer of this question in SO](http://stackoverflow.com/questions/32694804/how-can-i-delete-the-sheet-node-keeping-its-content-intact)

**Comment by jamshu** [comment]
It Worked ...Thanks

**Comment by pedrobaeza** [comment]
I don't see this very useful nowadays, with main backend themes (Odoo enterprise responsive and OCA responsive ones), expanding the sheet to proper dimensions, so I'm closing this wishlist, unless the issuer says other reasons for this sheet removal.
