### ISSUE TITLE
Search view disable custom filters

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#3258]
search_disable_custom_filters is not used on popup mode from o2m field.
## Impacted versions:

v8: In fact since action_id was added on ir.filter, its happen only through the same action.
v7: this is especially true, and it's why I created this issue!
## Steps to reproduce:
- Instatll sale module (Or any which would add the menu to configure res_partner)
- create a custom filter using group by on Sales > Sales > customers view list, save it as default filter.
- make sure you are more than 10 companies to see search more on parent_id (company) one2many field on res.partner
- create a new customer, select the company and clik to search more...
- the popup is open with the custom filter, even if I specify a default search (search_default_xxx)
  in the company field view definition, the default custom filter will be used:
  
  ``` xml
  <xpath expr="//field[@name='parent_id']" position="replace">
      <field name="parent_id"
             placeholder="Company"
             context="{'search_default_type_company': True}"
      />
  </xpath>
  ```
  
  where type_company is difined in the search view like:
  
  `<filter string="Companies" name="type_company" domain="[('is_company','=',1)]"/>`
- There is already an option to disable custom filter in the search view but not initialized when
  creating a popup, so a simple snipet code will looks like:
  
  ``` xml
  <xpath expr="//field[@name='parent_id']" position="replace">
      <field name="parent_id"
             placeholder="Company"
             context="{'search_disable_custom_filters': True,
                             'search_default_type_company': True}"
       />
  </xpath>
  ```
## Expected behavior:

Let developer the capabilities to disabled the custom default filter when he explicitly specified
it in the context.

Again It's especially true on v7 where there is only the model name to select default custom filter
on the search view. So on v7, if you decide to select a customer on a sale order, you will get the
default custom filter which could be annoyed to select a customer.

I'll push a PR.

**Comment by Yenthe666** [comment]
Hi @petrus-v,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
