### ISSUE TITLE
[10.0] hr_timesheet_sheet amount of timesheet_ids not updated when changing unit_amount

### ISSUE THREAD

**Issue by gmarcon** [odoo/odoo#32600]
Impacted versions: 10.0

Steps to reproduce:
create a timesheet, add a line for a project, insert 8 hours for a day, save, edit timesheet reducing the hours to 4 hours

Current behavior:
the cost set in amount should is 8 * timesheet_cost of the employee instead of 4 * timesheet_cost of the employee.
The amount as unit_amount * timesheet_cost is calculated in the following code, that skips the calculation if an amount is already provided:
https://github.com/odoo/odoo/blob/10.0/addons/sale_timesheet/models/account.py#L37

Expected behavior:
amount updated accordingly to unit_amount

**Comment by pedrobaeza** [comment]
Closing as #32608 is opened. There's no need to open an issue and a PR. Next time, you can put the issue description text in the PR itself.
