### ISSUE TITLE
Reconciliation Widget proposes anglosaxon interim stock moves for reconciliation

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#32611]
Impacted versions: 12.0
opw -1967462

Steps to reproduce:
Use anglosaxon / real time and have some unreconciled moves from sales in the interim stock accounts. I'm not sure if this is configuration or expected. My guess is expected because there is now a function to explicitly reconcile anglosaxon moves, so those interim stock accounts are now set by default reconciliable in localizations.

Current behavior:
Reconciliation widget proposes all moves from accounts that can be reconciled against that partner.

Expected behavior:
I'm not sure, I think there are 2 answers.
In bank statements, limiting lines to accounts of receivable, payable seems sensible.
However in manual reconciliation it isn't, so I guess there is a bigger question of why do we have/need partner_id stored against these essentially internal entries anyway.

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
support says it is intended behaviour - drives me nuts that they can say internal stock related transactions are intended on bank statements. Anyway, I ended up creating a module `account_reconciliation_not_stupid` to resolve the various issues present in the reconciliation widget, although some of the stupidity is quite hard to work around.

**Comment by Yenthe666** [comment]
I'm sorry to hear that @gdgellatly. I'm afraid there's not much we can do so I guess we can close this one off too?

**Comment by gdgellatly** [comment]
you never know, may as well leave it open, people who actually understand the issue might read it.

**Comment by Yenthe666** [comment]
@qdp-odoo or @lap-odoo might want to have a second look but no promises.

**Comment by CasVissers** [comment]
@gdgellatly I use OCA module https://github.com/OCA/account-reconcile/tree/11.0/account_skip_bank_reconciliation for this. Not yet ported to v12 though.

**Comment by gdgellatly** [comment]
@CasVissers thanks. See it was worth leaving open.

**Comment by gdgellatly** [comment]
And this shows the randomness of the Odoo support experience. #32957
