### ISSUE TITLE
Problem in inventory returns

### ISSUE THREAD

**Issue by fa-odoo** [odoo/odoo#32620]
Impacted versions:
12.0
Steps to reproduce:
return a picking and try to make an other return from the same picking.
Current behavior:
the returned quantity is not removed from the proposed quantity to return.
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is now the default behavior, but I agree is misleading.

@jco-odoo is there any plan to change this?

**Comment by fa-odoo** [comment]
@abdellatifnatif

**Comment by jco-odoo** [comment]
@lap-odoo I think you can use this feedback.  There is a way to calculate how much was returned or rereturned, so it should not be too hard.

**Comment by fa-odoo** [comment]
@pedrobaeza it is a wrong behavior cause it leads to wrong stock values when the user creates multiple returns for the same picking

**Comment by pedrobaeza** [comment]
@fa-odoo no, that's not happening. Once the return picking is created, you can't validate it if you don't have that stock (unless you force it).

**Comment by lap-odoo** [comment]
Ok, I'll it in our backlog (1945885)
