### ISSUE TITLE
[12] sitemap crashes with non-assigned country of published partner 

### ISSUE THREAD

**Issue by Moto017** [odoo/odoo#32636]
Ran into this error in V12ce and found this reference

https://gitlab.merchise.org/merchise/odoo/commit/dee3b87ae4b7c67f21a445ed8caecdd6fa36277f

**Comment by rdeodoo** [comment]
Hi, we will investigate this issue as soon as possible.
In the meantime, do not hesitate to create a pull request, it will most likely speed up the process.
Thank you for reporting.
