### ISSUE TITLE
Auto restart after login docker

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#32641]
Impacted versions: **Auto restart after login on docker**

Steps to reproduce: 
Install odoo on docker as document

-> Restore local database to docker server
-> And login 

> version: '2'
   services:
       odoo:
          #build: .
          image: odoo:12.0
          depends_on:
             - db
         ports:
            - "8099:8099"
            - "1111:22"
        restart: always
        tty: true
       volumes:
           - odoo:/var/lib/odoo
           - ./config:/etc/odoo
           - ./addons:/mnt/extra-addons
           - ./packages:/packages
           - ./odoo_addons:/mnt/odoo-addons
    #command: cd  /packages ; rpm -Uvh *.rpm
    #environment:
    #  - ADDONS_REPO=https://github.com/OCA/web.git
      db:
        image: postgres:11
        restart: always
        environment:
           - POSTGRES_PASSWORD=odoo
           - POSTGRES_USER=odoo
           - POSTGRES_DB=postgres
           - PGDATA=/var/lib/postgresql/data/pgdata
           - PG_SYSTEM_SHARED_BUFFERS=256MB
           - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
           - PG_SYSTEM_WAL_BUFFERS=8MB
           - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
       volumes:
           - db:/var/lib/postgresql/data/pgdata
           - ./backup:/mnt/bakcup
  volumes:
     odoo:
     db:

**Comment by pedrobaeza** [comment]
I don't get the problem, but any way, any Docker related thing should go to odoo/docker.
