### ISSUE TITLE
inconsistent behavior: use parent address

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#3264]
I haven't find what sould I do for launchpad issues in the guidelines.
I wrote that issues: https://bugs.launchpad.net/openobject-server/+bug/1315436 and still true on odoo v8.

When I check use parent address, on the res_partner form (on edit mode),  I expected that all adresses fields will be readonly what ever the selected country/language

## Impacted versions: ##

7.0 and above

## Steps to reproduce: ##

* Select "France" on the company' country field of your logged user
* look the behavior on a customer when checking "Use company address" (use_parent_address) on a customer it's not the same for English companies.

## Current behavior: ##

Some fields still editable depending the address format

## Expected behavior: ##

Same behavior what ever the selected format (can't remember it's through the user language or select country) look the pull request on launchpad!

regards

**Comment by petrus-v** [comment]
I've changed the description for steps to reproduce.

**Comment by beledouxdenis** [comment]
This issue is closed with rev. 5b283419d34f333e4e53ba376c35bcadf6352d35
