### ISSUE TITLE
Wrong translation when data is imported then name changed and name translated

### ISSUE THREAD

**Issue by MartinAavastik** [odoo/odoo#32654]
Impacted versions:
Tested on 11.0, but might be other version as well
Tested even in Odoo runbot also where I could reproduce the error. 

Steps to reproduce:
You need to install some other language than english first.
I am using estonian language.

1. Import for example Product Categories through excel file
Example
```
id | name | parent_id/id
-- | -- | --
category_lambid | Tuled | product.product_category_all
```
2. Then change the name "Tuled" to "Lights"
3. Go to the freshly created product category, edit, and click translation
And change translated value to "Tuled"
4. Change current user language to Estonian or some other language

Current behavior:
On the tree view, product name is "Lights"
but when you click and go to form view, then its "Tuled"

Expected behavior:
I expect both in tree and form view names to be translated to "Tuled"

Video/Screenshot link (optional):
Tree view:
![Selection_087](https://user-images.githubusercontent.com/8569032/56032169-1858e780-5d2a-11e9-9ccb-39a8785478eb.png)

When clicking on the form view:
![Selection_088](https://user-images.githubusercontent.com/8569032/56032192-2575d680-5d2a-11e9-99e9-95150a38f45a.png)

Note that the breadcrumb shows name "All / Lights" though but it probably should be "All / Tuled".

Translated Terms
![Selection_089](https://user-images.githubusercontent.com/8569032/56032465-f01db880-5d2a-11e9-9a3e-44fc6888a5ac.png)

**Comment by mart-e** [comment]
Hello,

This is a recurring report and known limitation, see my comment about this at 
https://github.com/odoo/odoo/issues/23867#issuecomment-405267037

We have unfortunately no solution this at the moment than putting everything in one language. For the future, we should probably not making this field translatable.
