### ISSUE TITLE
[12] account_voucher Cannot create unbalanced journal entry.

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#32667]
**Impacted versions:**
Tested on runbot V12
**Steps to reproduce:**
_**With round per line working fine**_
![Voucher](https://user-images.githubusercontent.com/7775116/56083555-16575d00-5dec-11e9-9d7e-2cc27ba1186a.gif)

**_With round globally get error_**
![Voucher round global](https://user-images.githubusercontent.com/7775116/56083565-36871c00-5dec-11e9-9db8-8f9a97a4eab1.gif)

commits related are 3e147220fd3b410ad8b530daccff5f697e1749c6 and db1c7765cba0692cfc4eda34ead000b048da4dae

CC @nim-odoo 

**Current behavior:**

**Expected behavior:**

Video/Screenshot link (optional):

**Comment by celm1990** [comment]
Posible bad forward porting??
_first commit_
![image](https://user-images.githubusercontent.com/7775116/56083623-2885cb00-5ded-11e9-9fef-562cd9a2827e.png)

_forward port_
![image](https://user-images.githubusercontent.com/7775116/56083649-68e54900-5ded-11e9-8d24-d121a8e0876e.png)

**Comment by pedrobaeza** [comment]
@KangOl can you please check?

**Comment by KangOl** [comment]
The forward-port was correct.
In version 12, the `apply_taxes` flag has been removed from context, leading to having the same line written in both code branches (`if` and `else`). I, therefore, move it outside the condition and remove the now empty `else` clause.

**Comment by pedrobaeza** [comment]
@KangOl what about the shared screencast?

**Comment by KangOl** [comment]
There may be a bug, but it does not seem to be due to this forward-port.

**Comment by pedrobaeza** [comment]
OK, let's keep it opened and tagged then.

Thanks for your insights, Christophe.

**Comment by sswapnesh** [comment]
Just got the same Error. 
(Reproduced at http://545484-12-0-811471.runbot15.odoo.com/web?debug=#id=4&action=692&model=account.voucher&view_type=form&menu_id=327)

Ticket 2026534
