### ISSUE TITLE
[10.0 -> 12.0 + master][l10n_fr_cert_pos] Anti fraud module is broken with fiscal position 

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#32665]
**Impacted versions:**
All versions with french certification. (V10 / V11 / V12 / master)

**Steps to reproduce:**

- in a French certified context
- Create a Pos Order with a customer with a fiscal classification
- confirm the order. (the hash is generated and stored)
- alter a fiscal setting that is needed to compute the field ``tax_ids_after_fiscal_position`` (``pos.order.line`` model) (product, partner, fiscal position)

**Current behavior:**
- the hash is corrupted

**Expected behavior:**
- the hash should be unaltered.

**Reason :**

The hash is computed on a non stored and computed field ``tax_ids_after_fiscal_position``. The computation depend on fiscal settings that can be changed.

**Links:**
- point of sale
  - Compute Section : [V10](https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/models/pos_order.py#L949) / [master](https://github.com/odoo/odoo/blob/master/addons/point_of_sale/models/pos_order.py#L1156)

  - Non stored definition : [V10](https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/models/pos_order.py#L1037) / [master](https://github.com/odoo/odoo/blob/master/addons/point_of_sale/models/pos_order.py#L1063)

- l10n_fr_pos_cert : 
  - Hashed fields : [V10](https://github.com/odoo/odoo/blob/10.0/addons/l10n_fr_pos_cert/models/pos.py#L56) / [master](https://github.com/odoo/odoo/blob/master/addons/l10n_fr_pos_cert/models/pos.py#L58)

CC odoo team : @KangOl, @pimodoo, @qdp-odoo, @kebeclibre
CC : OCA :  @flotho, @alexis-via,

**Comment by Yenthe666** [comment]
You basically pinged nobody really actively working on the POS haha. @switch87 any chance you could have a look?

**Comment by kebeclibre** [comment]
@legalsylvain 
The only issue I see is the lack of protection around the function in the pos_certification module and probably an @api.depends around it.

Otherwise, it seems logical and justified business wise to have corrupted the hash as the tax_after_fiscal_position field is one of the field that is hashed

And since:
`line.tax_ids_after_fiscal_position = line.order_id.fiscal_position_id.map_tax(line.tax_ids, line.product_id, line.order_id.partner_id)`

Seems justified that if you change taxes or product or partner, that it would corrupt the whole order, doesn't it ?

**Comment by switch87** [comment]
@legalsylvain thank you for reporting this problem. This should indeed be prevented. We will discuss internally at Odoo to find a proper solution.

**Comment by switch87** [comment]
@Yenthe666 thank you for pinging me :+1:

**Comment by legalsylvain** [comment]
Hi @kebeclibre. Sorry if I didn't explained the problem correctly. Indeed, if we alter product, taxes_id, or partner_id of `the pos.order` / `pos.order.line`, the hash is corrupted, and **it is OK**.
The problem I see is if we change the settings of the fiscal_position. (changing tax_dest_id, or couple of tax_src_id / tax_dest_id). In that case, the result of the map_tax call, will change, and so _without changing any data of the pos.order_, the hash will change and the chain is broken.

I overestimated the problem because, as product & partner was arguments of the function, I knew that changing the fiscal settings of the items had an impact. But in fact, it seems that both arguments are unused. (and so I don't understand the design of the function, but that's another story). Is it to allow inheritance ?
https://github.com/odoo/odoo/blob/12.0/addons/account/models/partner.py#L49 

To resume : 
-> changing the settings of the fiscal positions : real problem
-> changing fiscal settings of partner or product : theoritical problem

@switch87, thanks for reopening the issue.

@Yenthe666 : thanks for pinging the correct people. In fact, It's quite a problem to know who to contact or ping. (I justed pinged the authors and main reviewers of the function).

@Yenthe666 / @switch87, do you know if there is a webpage, with the list of responsibles ?

**Comment by switch87** [comment]
@legalsylvain here is the list of responsibles: https://github.com/odoo/odoo/wiki/BugManagement

**Comment by legalsylvain** [comment]
> @legalsylvain here is the list of responsibles: https://github.com/odoo/odoo/wiki/BugManagement

:100: :+1: Thanks A lot ! I pinned this page.

**Comment by legalsylvain** [comment]
Note : it's partially out of the scope, but I don't understand the reason of both fields `tax_ids` and `tax_ids_after_fiscal_position` in the point of sale, in the recent version. In other accounting models. (`sale.order` / `account.invoice` / `purchase.order`) there are no such fields. (only the currents taxes applied). Explanation welcome !

**Comment by legalsylvain** [comment]
Proposal : One of the solution i see is to set `tax_ids_after_fiscal_position` stored. (in fact, this is the only field non-stored of all the list fields).

As processing the change between non stored to stored is quite long for existing databases. (compute for each `pos.order.line`), I think that we could : 
-> increase version of module `point_of_sale`
-> add a pre migration script, with a sql script that populate `tax_ids_after_fiscal_position` from the tax_ids fields. (In 99% of the case, it is the same value)
-> add a post migration script, to call the computation of `tax_ids_after_fiscal_position` in the case that the fiscal position of the order is not the default fiscal position of the point of sale.

My two cents.
