### ISSUE TITLE
display loaded data in popup 

### ISSUE THREAD

**Issue by supermery** [odoo/odoo#32671]
Impacted versions:
HI,
i create a custom model sepend with pos ,i want to load fields from this model and display it in popup ,
this is the code for loading custom model fields
models.load_models([{
model : 'jsproject.jsproject',
fields : ['num_vehicule', 'client', 'mar'],
loaded : function(self,result){
var list =[];
for (var i =0 ;i <result.length; i++){
list.push({'label':result[i]});
}
console.log(list)
}
}]);

but when i tired to display it in the popup it wouldn't work
can anybody help me to fix this ,thnx
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @supermery,

I'm sorry but the Github tracker is only for bugs in the official code. This is not the place to ask questions about custom development.
You can ask these on the official help forums at https://www.odoo.com/forum/help-1

Regards,
Yenthe
