### ISSUE TITLE
Odoo mobile app - Enter server first, then press next

### ISSUE THREAD

**Issue by Nimja** [odoo/odoo#32686]
The Odoo app now has the following screen when you start it:

 ```
Server:
User:
Password:
[Login Button]
```

Unfortunately, this means that if an app uses a different method of user validation, like OpenID or OAuth, it does not work.

-------

Wouldn't it be nicer to have:

Screen 1:
```
Server:
[Next button]
```

Screen 2 - Already on that server, showing the correct logo, etc.
```
User:
Password:
[Login Button]
```

By running screen 2 on the server in question, they can use whatever implementation of the login process they desire.

**Comment by Yenthe666** [comment]
@adr-odoo could you check? Related to the mobile app.

**Comment by est-odoo** [comment]
Hello , 

The mobile application currently does not support this feature but you can set up a password on your users as a workaround.
