### ISSUE TITLE
general setting bug: this.getFocusableElement is undefined

### ISSUE THREAD

**Issue by nvietthuan2010** [odoo/odoo#32688]
Impacted versions: 12.0

Steps to reproduce: setting -> general setting

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @nvietthuan2010,

Thanks a lot for your bug report. I've tested this on the latest Odoo 12.0 (runbot.odoo.com) but it seems to work fine out of the box.
Can you update your Odoo instance and try again or test on runbot.odoo.com if you can still reproduce the problem there?
Please add more information if you still have this issue.

Regards,
Yenthe

**Comment by nvietthuan2010** [comment]
> 
> 
> Hi @nvietthuan2010,
> 
> Thanks a lot for your bug report. I've tested this on the latest Odoo 12.0 (runbot.odoo.com) but it seems to work fine out of the box.
> Can you update your Odoo instance and try again or test on runbot.odoo.com if you can still reproduce the problem there?
> Please add more information if you still have this issue.
> 
> Regards,
> Yenthe

hi Yenthe,
Thank for reply with my request. runbot not problem. it warning by:


TypeError: this.getFocusableElement(...) is undefined

http://cloud.posplus.vn/web/static/src/js/fields/abstract_field.js:324
Traceback:
setIDForLabel@http://cloud.posplus.vn/web/static/src/js/fields/abstract_field.js:324:9
setIDForLabel@http://cloud.posplus.vn/web/static/src/js/fields/basic_fields.js:838:9
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
_setIDForLabel@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:993:9
_postProcessField@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:359:9
_renderFieldWidget/<@http://cloud.posplus.vn/web/static/src/js/views/basic/basic_renderer.js:617:13
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
add@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3275:77
each@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:383:49
then/<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3332:25
then@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3271:48
_renderFieldWidget@http://cloud.posplus.vn/web/static/src/js/views/basic/basic_renderer.js:602:9
_renderTagField@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:717:16
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:609:20
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderGenericTag@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:443:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:617:16
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_.collect@http://cloud.posplus.vn/web/static/lib/underscore/underscore.js:164:24
_renderTagForm@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:729:24
_renderNode@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:609:20
_renderNode@http://cloud.posplus.vn/mail/static/src/js/form_renderer.js:66:20
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
_renderView@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:922:21
_render@http://cloud.posplus.vn/web/static/src/js/views/basic/basic_renderer.js:511:16
_render@http://cloud.posplus.vn/base/static/src/js/res_config_settings.js:269:19
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
_render@http://cloud.posplus.vn/muk_web_branding/static/src/js/views/res_config_settings.js:33:19
OdooClass.extend/Class.include/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:123:35
start@http://cloud.posplus.vn/web/static/src/js/views/abstract_renderer.js:37:23
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
start@http://cloud.posplus.vn/web/static/src/js/views/form/form_renderer.js:43:16
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
start@http://cloud.posplus.vn/base/static/src/js/res_config_settings.js:27:9
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
_widgetRenderAndInsert/<@http://cloud.posplus.vn/web/static/src/js/core/widget.js:399:20
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
add@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3275:77
each@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:383:49
then/<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3332:25
then@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3271:48
_widgetRenderAndInsert@http://cloud.posplus.vn/web/static/src/js/core/widget.js:393:33
appendTo@http://cloud.posplus.vn/web/static/src/js/core/widget.js:164:16
start@http://cloud.posplus.vn/web/static/src/js/views/abstract_controller.js:94:13
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
start@http://cloud.posplus.vn/web/static/src/js/views/basic/basic_controller.js:54:16
OdooClass.extend/</prototype[name]</<@http://cloud.posplus.vn/web/static/src/js/core/class.js:90:35
_widgetRenderAndInsert/<@http://cloud.posplus.vn/web/static/src/js/core/widget.js:399:20
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
add@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3275:77
each@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:383:49
then/<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3332:25
then@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3271:48
_widgetRenderAndInsert@http://cloud.posplus.vn/web/static/src/js/core/widget.js:393:33
appendTo@http://cloud.posplus.vn/web/static/src/js/core/widget.js:164:16
_startController@http://cloud.posplus.vn/web/static/src/js/chrome/action_manager.js:894:16
_executeAction/<@http://cloud.posplus.vn/web/static/src/js/chrome/action_manager.js:343:36
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
add@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3275:77
each@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:383:49
then/<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3272:49
Deferred@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3332:25
then@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3271:48
_executeAction@http://cloud.posplus.vn/web/static/src/js/chrome/action_manager.js:334:14
_executeWindowAction/</<@http://cloud.posplus.vn/web/static/src/js/chrome/action_manager_act_window.js:341:24
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3321:62
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3321:62
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3321:62
_createViewController/<@http://cloud.posplus.vn/web/static/src/js/chrome/action_manager_act_window.js:233:21
then/</</<@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3276:86
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38
fireWith@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3321:62
fire@http://cloud.posplus.vn/web/static/lib/jquery/jquery.js:3119:38

**Comment by nvietthuan2010** [comment]
> 
> 
> Hi @nvietthuan2010,
> 
> Thanks a lot for your bug report. I've tested this on the latest Odoo 12.0 (runbot.odoo.com) but it seems to work fine out of the box.
> Can you update your Odoo instance and try again or test on runbot.odoo.com if you can still reproduce the problem there?
> Please add more information if you still have this issue.
> 
> Regards,
> Yenthe

ok Thank YenThe
