### ISSUE TITLE
[11] Channel on Discuss scroll bar position 

### ISSUE THREAD

**Issue by anabeladamas** [odoo/odoo#32694]
**Impacted versions:**
Odoo version 11.0-20190404

**Steps to reproduce:**
When you click on Discuss , and then choose a channel.

**Current behavior:**
You are redirected to the start of the conversation, if the conversation is big, this is annoying because you have to scroll down to check the last messages. 

Expected behavior:
You should be redirected to the end of the conversation (scroll bar totally down), so you can check the last messages and reply to them.

**Comment by alexkuhn** [comment]
Seems to auto-scroll to last message correctly when clicking on a channel from the sidebar of discuss app the 1st time.

Note that the scroll positions of conversations are remembered upon changing conversations, so if you were at the top of a conversation and click on the conversation again, it will display the conversation with the scroll position at the top.
