### ISSUE TITLE
 two "warehouse_count" field in "stock.warehouse" class

### ISSUE THREAD

**Issue by chapsticks** [odoo/odoo#32699]
Impacted versions:
Odoo version 12, master
![image](https://user-images.githubusercontent.com/2037397/56176862-0c716c00-602f-11e9-8e3c-ee484ae97759.png)

 two "warehouse_count" field in "stock.warehouse" class.

**Comment by Yenthe666** [comment]
Thanks for reporting @chapsticks - you're right! I've made a PR to remove the duplicated field definition.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/8c402ca38a3d09594f41f9e9fe8555ade9cb80ac
