### ISSUE TITLE
Thousand separator is not applied by web module

### ISSUE THREAD

**Issue by yann-papouin** [odoo/odoo#327]
It looks like it's not working since a long time since 6.1, 7.0 and trunk are affected.

"openerp.web.insert_thousand_seps" is defined and used in "format.js" but the internal function "openerp.web.intersperse" does not seems to work correctly.

**Comment by Adoniasv** [comment]
Is a Bug.

Change this file:

addons/web/static/js/formats.js

Find this line in function instance.web.parse_value:
```javascript
  case 'float':          
     tmp = Number(value); 
     if (!isNaN(tmp))
        return tmp; 
```
and change for this (Coment whit //)
```javascript
 case 'float':          
     //tmp = Number(value); 
     //if (!isNaN(tmp))
        //return tmp; 
```
is working for us

**Comment by xmo-odoo** [comment]
> Thousand separator is not applied by web module

Can't see any issue with it, on Runbot 8.0:

![screen shot 2015-03-30 at 10 02 17](https://cloud.githubusercontent.com/assets/7571158/6892398/e79eb58e-d6c3-11e4-8b77-0e10203866a1.png)

Have you configured a "separator format" for your current language?

> "openerp.web.intersperse" does not seems to work correctly.

Do you have a case for intersperse not working correctly?

**Comment by yann-papouin** [comment]
Following are screenshots from runbot 7 & 8 on latest Chrome and Firefox on Windows 8.1 fr

![sshot-126](https://cloud.githubusercontent.com/assets/2794099/7132499/29a7ea82-e28a-11e4-8ea3-7dad1c10f29b.png)
![sshot-127](https://cloud.githubusercontent.com/assets/2794099/7132500/29b16aee-e28a-11e4-849a-6d02c6c50926.png)

**Comment by xmo-odoo** [comment]
> Following are screenshots from runbot 7 & 8 on latest Chrome and Firefox on Windows 8.1 fr

Again, have you configured the "separator format" of your current language? By default it's an empty list, which means no "thousands" separator. For western formatting (groups of 3 digits starting at the decimal separator and going right-to-left) you want to set it to `[3,0]`.

**Comment by Yenthe666** [comment]
Dear @yann-papouin,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
