### ISSUE TITLE
Some kind of rounding error causing Check Availability to fail

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#32707]
Impacted versions: 12.0

Steps to reproduce:
OK this took some time to replicate on runbot. Simple configs worked, so had to build out fully.
http://500789-12-0-77a241.runbot20.odoo.com/web?#id=389&action=392&active_id=135&model=stock.picking&view_type=form&menu_id=555 is the example picking

Create a product with a UoM precision of 0.001, MTO, Manufacture, Tracking Lots.
Create a Bill of Materials for it.
Create an SO for 22.400 of the product.
Manufacture the created manufacturing.
Go to the delivery and press check availability

Note while these seem very specific it was a direct replication of a single example. We have hundreds of these with different numbers and precisions failing. 

Current behavior:
Check availability never works because of a .000000000000000000002 difference. You can see this if opening the reserved move lines

Expected behavior:
Product reserves correctly.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/56190903-64d05a00-607f-11e9-9d9b-0e565ec4a6b8.png)

OPW to follow

**Comment by gdgellatly** [comment]
@Yenthe666 Stock

**Comment by gdgellatly** [comment]
opw 1969888

**Comment by Yenthe666** [comment]
Oops, sorry, took the wrong one. Thanks for the ping.
