### ISSUE TITLE
[12] Can not Install German Accounting

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#32714]
Impacted versions: v12

Steps to reproduce:

- Create a new database with German localisation
- Try to install accounting App

Current behavior:

- Won't install
- ERROR xytest odoo.sql_db: bad query: b'INSERT INTO "account_account" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "company_id", "currency_id", "deprecated", "group_id", "name", "note", "reconcile", "user_type_id") VALUES (nextval(\'account_account_id_seq\'), 1, (now() at time zone \'UTC\'), 1, (now() at time zone \'UTC\'), \'3551\', 1, NULL, false, NULL, \'Wareneingang, im Drittland steuerbar (7%)\', NULL, false, 16) RETURNING id'
ERROR: duplicate key value violates unique constraint "account_account_code_company_uniq"
DETAIL:  Key (code, company_id)=(3551, 1) already exists.

- Error occours only after post20190416
- post20190415 is working just fine

- Maybe same account number 3551 exists 2x?

**Comment by william-andre** [comment]
There is indeed a declaration for 

| id | code | name | tag_ids/id | user_type_id/id | chart_template_id/id | reconcile |
| --- | --- | --- | --- | --- | --- | --- |
| account_3551 | 3551 | Wareneingang, im Drittland steuerbar | l10n_de.tag_de_pl_05 | account.data_account_type_expenses | l10n_de_skr03.l10n_de_chart_template | False |
| chart_skr04_3551 | 3551 | Erhaltene Kautionen - Restlaufzeit bis 1 Jahr  | l10n_de.tag_de_liabilities_bs_D_8 | account.data_account_type_current_liabilities | l10n_de_skr04.l10n_chart_de_skr04 |   |


in the first line is in l10n_de_skr3 and the second in l10n_de_skr4. I don't know about the german localization but it is weird...

When I try to install a new db with the german localization I don't get an error and both modules are installed. @jco-odoo Any insight ?

**Comment by jco-odoo** [comment]
As the two are different CoAs it should not matter much.  But I will still do a check.

**Comment by jco-odoo** [comment]
hm, I could reproduce it.

**Comment by jco-odoo** [comment]
It is the 3557 account that somehow got code 3551
