### ISSUE TITLE
[12.0] base: Can't export/re-import many2many fields

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#32732]
#### Impacted versions:
12.0

#### Steps to reproduce:
From `res.users` export the **groups_id** field.

#### Current behavior:
When trying to import the same file, Odoo won't accept it as the many2many are separated in rows. In v11 they those were separated by commas.

#### Expected behavior:
Successful import.

**P.D.:** This is a complete halt for data importation in v12
![image](https://user-images.githubusercontent.com/16890942/56215060-04183180-602d-11e9-9390-5d03b795684f.png)

opw-1970070

**Tested on Runbot**

**Comment by gustavovalverde** [comment]
This is just a bad UX implementation. Can live with it.

**Comment by msh-odoo** [comment]
Should be fixed in #37407
