### ISSUE TITLE
[11.0] Regenerate Asset Bundle

### ISSUE THREAD

**Issue by amirpadilla** [odoo/odoo#32749]
Impacted versions:
11

Current behavior:
After uninstall a module that handle odoo attachments I got the following error

> Style error

> The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

> Could not get content for /web_editor/static/src/less/web_editor.common.custom.web.assets_frontend.less defined in bundle 'web.assets_frontend'.
Could not get content for /portal/static/src/less/website.wrapwrap.custom.web.assets_frontend.less defined in bundle 'web.assets_frontend'.
(b'', b"NameError: .o-create-color-classes is undefined in - on line 4350, column 17:
4349 
4350                 .o-create-color-classes(~'alpha-lighter', @color-alpha-lighter);
4351                 .o-create-color-classes(~'alpha-light', @color-alpha-light);

I know in Odoo 12 there's a way to regenerate Asset Bundles from debug menu.

My question is: what are the necessary steps to regenerate Asset Bundles in Odoo 11 CE

I'm using this as a source https://medium.com/@reedrehg/odoo-images-and-attachments-explaining-and-regenerating-assets-d1eb7fe8a3ed

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by obayit** [comment]
@amirpadilla hello,

I know this was a log time ago, but did you find how to regenerate assets in odoo `11.0`?
