### ISSUE TITLE
[question][hr_payroll_account] Make account move line with a partner different to employee

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#3274]
We need manage deduction based on alimony, loan, social security (SSA) and more...
Then hr_payroll_account is a good module to control all this situation and work very fine even accounting matter is fine.
However, there is a little problem.
The field "account_move_line.partner_id"

If is a SSA matter we need make a account move line with a partner named "Social Security"
If is a loan matter we need make a account move line with a partner named "Bank loaner SA".
If is a alimony matter we need make a account move line with a partner named "My $$ Wife".

There is the possibility to send the partner to use?

Something as this:
[hr example](https://docs.google.com/file/d/0BwPeHBuUYqNsUWN0VmxqRVdtc00/edit)

![salary structures - odoo - example](https://cloud.githubusercontent.com/assets/6644187/4761158/c79a0bac-5af5-11e4-92e1-d1d0a989ea75.png)

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your question / bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
