### ISSUE TITLE
[12.0] l10n_*: Stock Interim accounts were not correctly ported to v12

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#32757]
#### Impacted versions:
12.0

#### Steps to reproduce:
- Try to invoice using anglosaxon / real time on a new l10n_do install

#### Current behavior:
- It complains that the **Interim Account** is not reconcilable

#### Expected behavior:
- Successful invoicing

**Note:** This is also crashing some tests when a module requires any of those l10n_* that were not ported correctly.

Related to: #32611

**Comment by gustavovalverde** [comment]
cc: @jco-odoo this might be impacting other localizations

**Comment by gustavovalverde** [comment]
PR made for l10n_do: https://github.com/odoo/odoo/pull/32758

**Comment by gustavovalverde** [comment]
I'm also having the doubt, should these accounts have been like this before? Was this the correct configuration in v11, v10?

**Comment by jco-odoo** [comment]
@gustavovalverde Indeed, this should have been reconcilable already from v10, although not a lot of people will create a new instance in v10 I suppose.  I should indeed check for the other localizations.

**Comment by gustavovalverde** [comment]
I think it could be easy for all the localizations that have the **property_stock_account_****_categ_id** set.

So basically, If we have an install currently in production in v11, with this accounts as reconcilable FALSE, we should be setting that to TRUE (even though it will complain and we'd have to workaround that).

**Comment by jco-odoo** [comment]
@gustavovalverde You should be able to change them indeed.

**Comment by gustavovalverde** [comment]
The only thing is that those accounts already have account move lines, and there's a constraint for changing if an account is reconcilable after having moves.

I might use https://github.com/OCA/account-reconcile/tree/10.0/account_set_reconcilable, as it seems safe enough.

**Comment by gustavovalverde** [comment]
This has been fixed
