### ISSUE TITLE
Salary rules to introduce different overtime rates based upon public holidays, weekends and normal day

### ISSUE THREAD

**Issue by Mtui** [odoo/odoo#32769]
Impacted versions: 12

Steps to reproduce: Install public holidays, payroll and overtime addons/ modules Writing python codes and conditions in salary rules to check if approval OT days are holidays or weekend then applying its OT rate (x 2.0 ) in hourly salary payment and the same for the OT if it's normal day but different OT rate (x 1.5)

Current behavior: flat OT rate

Expected behavior: Different OT rates

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@Mtui public holidays is not something supported for payrolls.

**Comment by Mtui** [comment]
@pedrobaeza the issue is not either public holidays is supported or not in payroll, what am requesting is having different overtime rates depending on the calendar date. The first trigger is the date on which OT is applied if it is weekends (sunday & saturday) the rate should be higher than that for week days (mon-fri) and the same apply to holidays.

**Comment by pedrobaeza** [comment]
Well, that's something not supported, but it has been pointed in other occasions, and maybe it would be added in future versions, but meanwhile, closing this and you should check community modules doing this or develop it.
