### ISSUE TITLE
[11.0/12.0] product: Barcodes should not disappear when archiving a product

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#32763]
#### Impacted versions:
11.0, 12.0

#### Steps to reproduce:
- Someone archives **Product A** with barcode: 12345
- You try to a new **Product B** using barcode 12345
- It raises an error that a product with that barcode already exists

#### Current behavior:
- If you try to lookup **Product A** by barcode it won't appeared on archived products
- If you try to export all the archived products, **Product A** won't export the barcode.
- So we can't create **Product B** using barcode 12345, but we cant neither find the product that has this barcode.

#### Expected behavior:
- Allow the user to find products by barcode even if they are archived.

#### Video/Screenshot link (optional):
https://youtu.be/CgKQH6kQNHE

**NOTE:** This happens with all the other fields that gets hidden when archiving.

**opw-1970452**
**Tested on Runbot**

**Comment by Yenthe666** [comment]
Good point. Maybe Odoo should only check for active products with a barcode.

**Comment by seancallahan88** [comment]
This occurs in in my 10.0E as well.

**Comment by sswapnesh** [comment]
Hello @gustavovalverde 
It seems fix for this is at https://github.com/odoo/odoo/pull/33483 (For master and don't refer to your opw reference)

**Comment by gustavovalverde** [comment]
Thank you @sswapnesh

**Comment by Yenthe666** [comment]
@gustavovalverde is this issue still open or did you get an answer/solution on the official ticket?

**Comment by sswapnesh** [comment]
> Hello @gustavovalverde
> It seems fix for this is at #33483 (For master and don't refer to your opw reference)

This PR was closed and https://github.com/odoo/odoo/pull/34769 is the new PR for this

**Comment by Yenthe666** [comment]
Odd that it has been this long.

**Comment by pedrobaeza** [comment]
Any news on this? What happened to OPW?

**Comment by nirmalraj-erp** [comment]
@Yenthe666 Is it still open ? Is there any fix apart from touching source. I am facing the same issue in 13,14 and 15 as well. 
Barcodes disappearing when product is archived. 
Search of product via barcode doesn't find the product once it is archived.

**Comment by Yenthe666** [comment]
As far as I know still relevant :(

**Comment by sswapnesh** [comment]
> It seems fix for this is at #33483 (For master and don't refer to your opw reference)

@nirmalraj-erp  I am sure it was Fixed but for some reason now its not working anymore

**Comment by sswapnesh** [comment]
This has been fixed in v15 (Via PR https://github.com/odoo/odoo/pull/84293)
