### ISSUE TITLE
can't add more then one tag to Questions in the Help Forum

### ISSUE THREAD

**Issue by vrms** [odoo/odoo#3276]
https://www.odoo.com/forum/help-1

expected behavior: 
- you can add more then 1 tag to a question
- tags are being separated by a space
- autocomplete function for existing tags (not just your own)

actual behavior
- if you use a space after a keyword (in order to add a second tag) like "v8 [space] database" you don't get two tags [v8] [database] but one tag v8 database]
- autocompletion only works with the tags stored in your browsers cache and not with existing tags previousely used in the Help Forum
- if you reopen a question to edit it your tags vanish

I think this is a bug

**Comment by Yenthe666** [comment]
Hi @vrms,

Thank you for your report and sorry for the late reply.
This has been fixed in the meanwhile and you can add multiple tags to a question.

Regards,
Yenthe
