### ISSUE TITLE
11 Odoo installed with Managed PostgreSQL (Azure Database) Uncaught Error: QWeb2: Template 'PlannerLauncher' not found

### ISSUE THREAD

**Issue by ChristopheLux** [odoo/odoo#32786]
Impacted versions: v11

Steps to reproduce: Installing Odoo on Ubuntu 18.04 LTS (with nginx+letsencrypt certificate) up to date with separate postgresql server on Azure Database for PostgreSQL 
odoo user is memeber of azure_pg_admin
                                                 List of roles
    Role name    |                         Attributes                         |    Member of     | Description
-----------------+------------------------------------------------------------+------------------+-------------
 azure_pg_admin  | Cannot login                                               | {}               |
 azure_superuser | Superuser, Create role, Create DB, Replication, Bypass RLS | {}               |
 odoo            | Create role, Create DB                                     | {azure_pg_admin} |
 postgresqladmin | Create role, Create DB                                     | {azure_pg_admin} |

odoo user is correctly owner of odoo database
    Name        |      Owner      | Encoding |          Collate           |           Ctype            |          Access privileges
-------------------+-----------------+----------+----------------------------+----------------------------+-------------------------------------
 azure_maintenance | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | azure_superuser=CTc/azure_superuser
 azure_sys         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 |
 postgres          | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 |
 template0         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/azure_superuser                 +
                   |                 |          |                            |                            | azure_superuser=CTc/azure_superuser
 template1         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/azure_superuser                 +
                   |                 |          |                            |                            | azure_superuser=CTc/azure_superuser
 ****test****              | odoo            | UTF8     | English_United States.1252 | English_United States.1252 |

Current behavior:
it seems database creation going well no error message during creation (either with or without demo data)

Error: when going to the url to log in in Odoo
Uncaught Error: QWeb2: Template 'PlannerLauncher' not found

https://FQDN/web/content/242-b119a71/web.assets_common.js:3689
Traceback:
Error: QWeb2: Template 'PlannerLauncher' not found
    at Object.exception (https://FQDN/web/content/242-b119a71/web.assets_common.js:3689:7)
    at Engine._render (https://FQDN/web/content/242-b119a71/web.assets_common.js:3734:103)
    at Engine.render (https://FQDN/web/content/242-b119a71/web.assets_common.js:3730:151)
    at Class.renderElement (https://FQDN/web/content/242-b119a71/web.assets_common.js:3949:1078)
    at https://FQDN/web/content/242-b119a71/web.assets_common.js:3949:917
    at https://FQDN/web/content/242-b119a71/web.assets_common.js:802:681
    at fire (https://FQDN/web/content/242-b119a71/web.assets_common.js:796:299)
    at Object.add [as done] (https://FQDN/web/content/242-b119a71/web.assets_common.js:797:467)
    at Array.<anonymous> (https://FQDN/web/content/242-b119a71/web.assets_common.js:802:649)
    at Function.each (https://FQDN/web/content/242-b119a71/web.assets_common.js:625:767)

Expected behavior:
Work as normal

Video/Screenshot link (optional):

I can provide access on demand

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by ChristopheLux** [comment]
Yes it is related to deployment and where if not here we can ask support for new methods of deployment

I am feeling that you are not even reading the report.

Maybe this should not be classified as an issue but as a RFE

**Comment by Yenthe666** [comment]
@ChristopheLux you can ask help on the official help forums (https://www.odoo.com/nl_NL/forum/help-1).

**Comment by pedrobaeza** [comment]
Not sure what RFE is, but as said by my colleague, this issue tracker is not for helping on deployment questions, but on issues on Odoo code itself.

**Comment by ChristopheLux** [comment]
RFE is Request For Enhancement

@Yenthe666 Whe I try to post on the forum I have always a 403..

**Comment by Yenthe666** [comment]
@ChristopheLux have you confirmed your email address and have you tried afterwards again?
Are you trying to attach images in the initial question?

**Comment by ChristopheLux** [comment]
yes confirmed email address
No..I have finally succeeded
Thanks

**Comment by ChristopheLux** [comment]
just FYI my post in Odoo Community
https://www.odoo.com/forum/help-1/question/11-odoo-installed-with-managed-postgresql-azure-database-uncaught-error-qweb2-template-plannerlauncher-not-found-148563

But as i have read multiple post about that issue and the way to solve it is to modify the pg_hba.conf to trust which is not possible in managed database on Azure and that Odoo should always use username/password if provided in odoo-server.conf

**Comment by ChristopheLux** [comment]
Hello Guys

I think it would be great to have Odoo working on Azure and other Cloud with PaaS offerings (Platform as a Service) for the PostgreSQL part
And I would really appreciate you consider investigating and making it a Request For Enhancement
So I spent some time in order to make a comparison
Case A: Odoo v11 with PostgreSQL on a separate Ubuntu VM
Case B: Odoo V11 with PostgreSQL on Azure PostgreSQL Database
The same frontend was used in both cases
The same database was created with English and Country Luxembourg. 
Log_level was set on debug in each case: no error reported

I made a dump of both database
zorvm = case A
zor = case B

The 2 dumps were compared with Notepad++ and compare plugin (time was not taken into consideration as an actual difference)
The lines are the line given by Notepad++

[zor.zip](https://github.com/odoo/odoo/files/3144476/zor.zip)
[zorvm.zip](https://github.com/odoo/odoo/files/3144477/zorvm.zip)


Very few tables with differences
Difference at line
**10593 public.ir_attachmen**t
10603 same table
10604-->620
10622
10626
10638
10928 public.ir_model
10929-->943
10944-> 949
10948 is in 11025???
10929 is in 11043….11065???
**11201 pubic_ir_model_constraint**
The model column is different
-->11332
**11340 public.ir_model_data**
-->11660 so only on module data there are differences
**16371 public.ir_model_relation**
-->16384 difference only in module column
**16392 public.ir_module_category** 
-->16416
**16454 public.ir_module_module**
-->16787 
**16791 public.ir_module_module_dependency**
--> 17339 does the id of modules have an importance?
**In public.ir_ui_view**
17707 
17773
17747 
**In public.res_groups**
19051 difference of category_id for Employee
19363 difference in pg_catalog.setval('public.base_cache_signaling', 5, true); 3 instead of 5 in Azure PG
19566 difference in SELECT pg_catalog.setval('public.ir_attachment_id_seq', 250, true); 248 in Azure PG
19902 difference in pg_catalog.setval('public.res_users_log_id_seq', 2, true); 1 in Azure PG
