### ISSUE TITLE
Making One2many field required is not working

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#32798]
Impacted versions:11

Steps to reproduce:
1. Activate developer mode and edit sale order line form view to make the field order_line required
2. Create a sale order without order line and save. The SO got saved without order lines

Current behavior:
Required one2many fields got saved without lines

Expected behavior:
Must not allowing the user to save a record without its lines (required one2many)

I have tried it on a runbot instance (community) and locally.

**Comment by pedrobaeza** [comment]
Hi @guidev224, I'm afraid making a one2many required is not supported right now in the framework. A possible workaround is to add a constraint that checks this condition over a field that is always included on create (like typical `name` field).

Closing as something not possible.
