### ISSUE TITLE
JS test data is committed

### ISSUE THREAD

**Issue by rven** [odoo/odoo#32818]
Impacted versions: 12.0 or later

Steps to reproduce: 
Create a custom module, which depends on the account module.
Change the currency of the main company in this module.
```xml
    <!-- Update main company data -->
    <record id="base.main_company" model="res.company">
        <field name="currency_id" ref="base.EUR"/>
    </record>
```
Current behavior:
When running Odoo with --test-enable and installing the custom module.
At the point of installing the custom module, the following error is raised:
**You cannot change the currency of the company since some journal items already exist**
This error is raised because the test exists after the test is executed.

Expected behavior:
The test data should not exist after the execution of JS test.

**Comment by pedrobaeza** [comment]
This is not a problem of Odoo, but a constraint introduced in Odoo that you can avoid using SQL instead inside the test. It has been done across several OCA modules from to the introduction of the constraint.

Closing as no real Odoo issue, but business logic constraint.

**Comment by rven** [comment]
@pedrobaeza Can you give an example of this?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/account-financial-tools/commit/186fa09ada0c1bfdf5325fd9684e961b54de0e84
