### ISSUE TITLE
No update for menu dashboard

### ISSUE THREAD

**Issue by jo541** [odoo/odoo#32828]
Impacted versions:12.0

In the file board_view.xml of module board. 

A menu is created but the noupdate is set on the data ? Is it normal ? 

https://github.com/odoo/odoo/blob/12.0/addons/board/views/board_views.xml

**Comment by Yenthe666** [comment]
@alexkuhn looks like on for you. It is to prevent an update destroying dashboard content, no?

**Comment by jo541** [comment]
It's only the entry point of menu. If I would like change sequence. In all other module the menu isn't in noupdate mode. 

A mistake ? or bad copy / past ? or other logic reason.

**Comment by alexkuhn** [comment]
This `noupdate="1"` is there for a very long time (~7 years). To be honest, I don't know why it is there, but I am pretty confident this cannot be removed in stable versions.
We had some discussions about this mode, and maybe this will be dropped in the future.

**Comment by Yenthe666** [comment]
Absolutely not in stable nope. Maybe for master though?

**Comment by jo541** [comment]
Have you any solution to don't display the menu ? (via XML)

In first time I used the xml code 

> <delete model="ir.ui.menu" id="board.menu_board_my_dash"/>
But this make me a warning error each time I upload my module.

**Comment by jo541** [comment]
I don't know if it's the better solution. But In wait of Odoo answer. I used this peace of code. 

```
<data noupdate="1">
        <record id="mode_data_of_menu" model="ir.model.data">
            <field name="name">menu_board_my_dash1</field>
            <field name="res_id" ref="board.menu_board_my_dash"/>
            <field name="noupdate" eval="False"/>
            <field name="module">board</field>
            <field name="model">ir.ui.menu</field>
            <field name="write_uid">2</field>
        </record>

        <delete model="ir.model.data" search="[('name','like', 'menu_board_my_dash'), ('write_uid','=', False)]"/>

        <record id="mode_data_of_menu" model="ir.model.data">
            <field name="name">menu_board_my_dash</field>
            <field name="res_id" ref="board.menu_board_my_dash1"/>
            <field name="noupdate" eval="False"/>
            <field name="module">board</field>
            <field name="model">ir.ui.menu</field>
            <field name="write_uid">2</field>
        </record>

        <delete model="ir.model.data" search="[('name','like', 'menu_board_my_dash1'), ('write_uid','!=', False)]"/>
    </data>
```

**Comment by mart-e** [comment]
As mentioned, will not be changed in stable, however, for the sake of consistency, I have changed it in master at #43209.
Will be in the future version 14.
Thanks for the feedback
