### ISSUE TITLE
Record Rules Not Working

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#32837]
Impacted versions: Odoo-12.0

Steps to reproduce:
I have added M2M **warehouse_ids** field in User and added Record rules for Model: Sale Order.

Application Accesses
--
Sales | User: Own Documents Only

**Record Rule:**
**Model:** sale.order
[('warehouse_id','in',user.warehouse_ids.ids)]
**Group Name**
--
Sales / User: Own Documents Only

After the login user can able to right records as per record rules.
But after the add new warehouse in **warehouse_ids** from User view.
Login Sales User can not able to new warehouse sales order.

Current behavior: Record rules is working proper after Create & Write.

Expected behavior: Need to user clear_cashes() in model create() and write() function.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this is something in your custom code, dealing with the special `user`, that is cached for special reasons. You'll need to restart service or re-login for getting that.

Closing as no direct Odoo issue, but special framework particularities with user model.

**Comment by goyanipankaj** [comment]
Yes, You are right its a custom code, But when the records rules related records want to see In the particular models recors.
That time must need to restart the server or need to use clear_cashes() in Create() and write() function.
