### ISSUE TITLE
[11.0] Performance issue Closing POS Session. May last an hour with 1000 sold products.

### ISSUE THREAD

**Issue by jobiols** [odoo/odoo#32849]
Impacted versions: 11.0 CE EE

**Steps to reproduce:**
Create database, 
install point_of_sale
open pos session
begin selling products
close POS Session.

**Current behavior:**
When hitting **Validate Close & post entries** a performance issue is observed, **with 1000 products sold** the process may last an hour. Profiling the sources, we can observe that the method process_reconciliation() is called once per product and lasts about 2.9 sec to complete.

**Expected behavior:**
The POS closing process should take a reasonable amount of time. ie inside the usual worker timeout.

**Comment by pedrobaeza** [comment]
There's a lot of operations involved in this closing, so this is expected, although indeed this is something that can be improved. There are efforts in this sense, some of them have already landed on stable versions (but not sure if in v12 or also v11). Try to update to latest code first to see if there is any improvement.

Any way, increase the worker timeout if not enough, and be tuned for news on future versions improving this, as the amount of changes that can be done on stable are limited. There is a patch with SQL that is not going to land on the official branch (but done by Odoo) that assumes certain things for improving the performance, but I don't have either the link. Try to look for similar past issues.

Closing this as somehow duplicated.
