### ISSUE TITLE
Portal access send to shipping address instead of customer

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#32848]
Impacted versions: all (8/9/10/11/12)

Steps to reproduce: It is more obvious with ecommerce. Create a customer with an email address, add a contact as shipping address without email as usual in ecommerce. Then try to grant portal access to the user.

Current behavior: Portal access is given to the shipping contact instead of the customer.

Expected behavior: Never try to send portal access to shipping contact. Specialy for individual customers.

**Comment by zeroheure** [comment]
portal_wizard should check if user is an individual or a company

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/41334ca2a5510c934d94da5b9501c8cf4cd38fb3
