### ISSUE TITLE
Server os busy when I try update any module. 

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#32852]
Impacted versions: 11

Steps to reproduce:

Current behavior:
The server is busy right now, module operations are not possible at this time, please try again later.

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because there is a cron job being executed in that moment.

Closing as no issue, but expected behavior.

**Comment by Alexandre-Bernardes** [comment]
6 days executing a cron?
and when I back to last version its work.
Is there any way for me to know which cron is preventing the installation?
thanks in advance.

**Comment by pedrobaeza** [comment]
Well, you should have a cron that is stuck in some way. No, there isn't any way to know it. You can guess it by last execution time.

**Comment by Alexandre-Bernardes** [comment]
OK.
Thanks a lot!
