### ISSUE TITLE
Is Odoo 12 Support Google Cloud Load Balancer ..? | TypeError: odoo.define is not a function

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#32856]
Impacted versions:
V12 EE , CE April 2019  

Steps to reproduce:
1- Install This Odoo Architecture On GCP 
![architecture](https://user-images.githubusercontent.com/9639673/56490651-8d78a980-64ee-11e9-8f29-ca5dac23b09d.png)
 2- instead of creating My PostgreSQL VMs I use Google SQL Service [ PostgreSQL V11 ]
3- When I am using Nginx as a Load Balancer I face no problem Everything working Good.
4- When I start to use GCP Load Balancer I face these problems: 
![loadbalancer](https://user-images.githubusercontent.com/9639673/56490855-51921400-64ef-11e9-80b7-b8d20e0cba1c.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by Elbagoury** [comment]
I always post my Issus as a question I don't like to post it as an statement like this: Odoo does not Support Google Cloud Load Balancer , I believe it is both odoo and google Issue.

**Comment by pedrobaeza** [comment]
Yeah, but it's not something that Odoo must support, so in any case it should be a feature request, but a very lazy feature request, but any way, this is something that enters in the field of deployment, so first is to explore in the forum why it doesn't work, and then maybe provide feedback about the specific part that is not working well.

**Comment by Elbagoury** [comment]
I believe any web application should support any famous Load Balancers and Web browsers.

**Comment by Elbagoury** [comment]
I believe GCP Load Balancer change something in JS and CSS files in client side  I am still testing it and I will share the feedback with odoo , Inshallah .

**Comment by pedrobaeza** [comment]
It's not the same to support a web browser than a load balancer.

**Comment by Elbagoury** [comment]
Thank You for your answers, I will continue testing it and Fix it and share the fix with odoo .
