### ISSUE TITLE
Can't change the allowed company in 

### ISSUE THREAD

**Issue by hitrosol** [odoo/odoo#32854]
Impacted versions: 12

Steps to reproduce:
1. Check the multi company setting
2. Create user for multi company, i.e : company A and Company B, I set Company A as current Company.
3. Save.
4. Edit and take out the Company A from Allowed company, then I set current company to Company B.

Current behavior:
Odoo Server Error - Validation Error

Error while validating constraint

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: res.users, Operation: read)
None

Expected behavior:
Admin can change the allowed company.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You have to become superuser for doing that things. This has changed in v12.

Closing as no Odoo issue, but misunderstanding on the use.
