### ISSUE TITLE
Line doesnt follow strict mode JS

### ISSUE THREAD

**Issue by KarstenK77** [odoo/odoo#32873]
Impacted versions: 11 / 12
My IDE is reporting an error with that line https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/static/src/js/screens.js#L1308

In strict mode the keyword arguments isnt allowed as property.

**Comment by pedrobaeza** [comment]
@switch87 not sure if it's a false positive linter error, but can you please check?

**Comment by switch87** [comment]
@KarstenK77 @pedrobaeza This is indeed a false positive. This error can be ignored.

**Comment by KarstenK77** [comment]
@switch87  Anway I get in Chrome the error: Uncaught TypeError: Assignment to constant variable.
Which point directly to this line.

**Comment by KarstenK77** [comment]
You can easily test it when creating an pos user without email address, that will produce an error.

**Comment by switch87** [comment]
> You can easily test it when creating a pos user without email address, that will produce an error.

I cannot reproduce this. Can you please try to reproduce this on runbot.odoo.com on the latest build? login: admin password: admin
