### ISSUE TITLE
webfrontend-errormessages

### ISSUE THREAD

**Issue by Axel-G** [odoo/odoo#32871]
Its difficult to repoduce this error-messages, but since today i get this message, clicking on a project in projects. The project "opens" correctly to task-view.

`

Error: Permission denied to access property "apply"

https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:887
Zurückverfolgung
trigger@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:887:28
trigger/<@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:937:134
each@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:625:758
each@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:613:636
trigger@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:937:113
jQuery.fn[name]@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:1134:355
_openRecord@https://xxxxxxxxxxx.xx/web/content/3791-1600151/web.assets_backend.js:2950:381
OdooClass.extend/Class.include/</prototype[name]</<@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:3541:368
_openRecord@https://xxxxxxxxxxx.xx/web/content/3791-1600151/web.assets_backend.js:2974:494
OdooClass.extend/Class.include/</prototype[name]</<@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:3541:368
_onGlobalClick@https://xxxxxxxxxxx.xx/web/content/3791-1600151/web.assets_backend.js:1813:13
dispatch@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:892:378
add/elemData.handle@https://xxxxxxxxxxx.xx/web/content/3711-4f51efa/web.assets_common.js:865:151

`

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Axel-G** [comment]
i cant reproduce the problem :-(

**Comment by rag57** [comment]
Environement: Debian Buster, lxc
Kubuntu 18.04,  firefox 67.0.4

After Installation via:
 echo "deb http://nightly.odoo.com/11.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list

Every time I click on Button Administrator, 1 get:

 Fehler:
Error: Permission denied to access property "apply"

http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:887
Zurückverfolgung
trigger@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:887:31
trigger/<@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:937:147
each@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:625:767
each@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:613:643
trigger@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:937:118
Dropdown.prototype.toggle@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:2676:7
dispatch@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:892:451
add/elemData.handle@http://rz26.rz:8069/web/content/245-44dc930/web.assets_common.js:865:173

**Comment by eblandon** [comment]
Hi, i have the same problem, but only with Firefox.
With Chrome no error.

**Comment by 3piece** [comment]
For anyone experiencing this error in the future. Check your browser extensions. 

Try opening Odoo in a private browser or a different browser.
Try turning all extensions off, or loading the browser in safe mode.
