### ISSUE TITLE
No sale_journal field in config

### ISSUE THREAD

**Issue by KarstenK77** [odoo/odoo#32875]
Impacted versions: 11 / 12

The field sale_journal is an important field in class pos.config, but I cant find the place where to configure.
In views https://github.com/odoo/odoo/blob/12.0/addons/point_of_sale/views/pos_config_view.xml I cant find it.

**Comment by pedrobaeza** [comment]
Check if this module is what you need: https://github.com/OCA/pos/tree/11.0/pos_config_show_accounting

**Comment by KarstenK77** [comment]
I will. Thanks Pedro!
