### ISSUE TITLE
Odoo session issue

### ISSUE THREAD

**Issue by ahmedkhak** [odoo/odoo#32888]
I don't know it is issue or not but I faced it very often on odoo 10 and 11

Impacted versions:
---------------------
odoo 10 and odoo 11

Steps to reproduce:
----------------------
I've got two different odoo installations on different ports. Please consider a scenario
First port is 8069 and other 8088. On both ports I assign different DB user like "odoo1" to 8069 installation and "odoo2" to 8068 installation. 

Current behavior:
------------------
I open "localhost:8069" in one chrome browser tab and "localhost:8088" in other tab. I faced it many times "localhost:8088" fetch db's of 8069 port, and sign in to that DB. And even when i open some other odoo installation on different ip and port like "so.me.i.p:port", it will fetch information of my "localhost:8069" url. And i think that should not happen. It may cause very harmful effects to db. I faced that issue on new installations as well.

Expected behavior:
-------------------
Every port or URL must fetch its respected information in browser

Video/Screenshot link (optional):
----------------------------------

**Comment by pedrobaeza** [comment]
Hi, this is something related to your deployment, so please be sure you are following the proper installation instructions, and I'm afraid this is not an Odoo issue, but more a deployment question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
