### ISSUE TITLE
Gevent instance does not respect proxy settings and shows proxy ip in logs

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#32914]
Following up this ticket #18052 and #27198.
I upgraded werkzeug to 0.15.2 and workers now show client's ip address.
Here is an example from live logs:

```
barrier_odoo     | 10.88.10.50 - - [2019-04-24 11:54:24] "POST /longpolling/poll HTTP/1.0" 200 402 12.930094
barrier_odoo     | 2019-04-24 11:54:27,176 16 INFO barrier werkzeug: 5.39.164.163 - - [24/Apr/2019 11:54:27] "POST /web/dataset/call_kw/barrier.resident/load_views HTTP/1.0" 200 - 114 0.258 0.355
```
You can see that worker shows real ip and gevent shows proxy ip.

I am using Odoo 12.

**Comment by xmo-odoo** [comment]
> I upgraded werkzeug to 0.15.2 and workers now show client's ip address.

By saying you upgraded are you saying that 0.14 or earlier gevent did show the "correct" (forwarded) client address?

**Comment by Yajo** [comment]
Confirmed in Odoo 11.

**Comment by xmo-odoo** [comment]
@litnimax @yajo yeah looks to me like it's never worked at all, and @julienlegros seems to confirm: longpolling / gevent has its own WSGI server (not werkzeug's), which obviously isn't aware of werkzeug's proxyfix and lives outside of it, so

1. apparently it dumps its logging to stderr (which should be easy to fix)
2. it dumps the pre-proxyfix REMOTE_ADDR, I've got to check how Werkzeug's WSGI server integrates with proxyfix to see how to make it dump the right REMOTE_ADDR depending on the proxy configuration (without hand-rolling the bloody thing myself)

**Comment by xmo-odoo** [comment]
Fixed for 13.
