### ISSUE TITLE
[8.0] Sending emails from the Inbox adds recipients to subscribers regardless of the recipient's wishes

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#3291]
Steps to reproduce:
1. Log into a new DB with admin.
2. Install the hr module, so that you can send emails to external addresses (see issue #2042)
3. Go to your Inbox, click on the "Share with my followers" box and expand it so that you can write to an external party...
4. Add "kino@example.com"  (I assume you have an development SMTP server that accepts example.com addresses).
5. Write "Welcome Kino!" and send the message.

Now Kino is automatically subscribed to the admin's wall regardless of Kino's intentions to follow or not the admin.

**Comment by mvaled** [comment]
Hi @tde-banana-odoo ,

Can you check this issue? It is an issue?  Or it will be solved if #2042 is fixed?

**Comment by AlanBell** [comment]
I think this is related to #7374 in part, customers get random notifications because they are made followers of things, people turn this off and then the customers don't get actual emails they are sent.

**Comment by Yenthe666** [comment]
Hi @mvaled ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
