### ISSUE TITLE
'account.coa.report' object has no attribute 'date_range'

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#32933]
Impacted versions:
12.0

Steps to reproduce:
1. Open the "trial balance" report
2. Try to open the Journal Items in one line

Current behavior:
A traceback is returned:
![Screen Shot 2019-04-24 at 2 18 10 PM](https://user-images.githubusercontent.com/7606656/56687417-d28e0e80-669b-11e9-8982-f900d66d8f61.png)

Expected behavior:
The Journal Items are show

Video/Screenshot link (optional):
https://youtu.be/K8_0hMO3meE

opw#1974183

**Comment by nim-odoo** [comment]
Indeed, `date_range` only applies to reports inheriting from `account.financial.html.report`.
