### ISSUE TITLE
[10.0] Bug duplicated elements in one2many after cancel a confirm dialog message.

### ISSUE THREAD

**Issue by hmartinet** [odoo/odoo#32942]
Impacted versions: 10.0 (not checked on 11.0 and 12.0)

Steps to reproduce:
* Create a new DB and install Accounting.
* Update de account.invoice form, add a confirm="Are you sure?" on the validate button.
* Create a new invoice (with no lines) and save it.
* Edit the invoice, add a line with valid data.
* Instead of "Save", click on "Validate" and click "Cancel" in the confirm dialog. Then click "Save".

Current behavior:
* The created line is duplicated

Expected behavior:
* The new line is created

This will occurs with all one2many if you cancel a confirmation message. This is very annoying if you have a lot of confirm because of irreversible workflows.

**Comment by pedrobaeza** [comment]
This is a known issue, but already solved in later versions, so this is not going to be solved. If you have an enterprise ticket, you can put the corresponding OPW ticket in odoo.com/help to see if they consider to fix it, or propose you to upgrade to a newer version.

Closing this as won't fix.
