### ISSUE TITLE
[12.0] Update to sale order's lock method is a breaking change in a stable version

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#32944]
### Impacted versions: 
- 12.0

### Steps to reproduce:
1. Open the Odoo shell
2. Take more than one sale order into a recordset
    ```python
    sales = self.env['sale.order'].search([])
    ```
3. Call `action_done` on the recordset.
    ```python
    sales.action_done()
    ```

### Current behavior:
A `ValueError` is raised with the message "Expected singleton".

### Expected behavior:
Call should not expect a singleton record.

### Further motivation of issue:

When version 12.0 was released, the `action_done` method of `sale.order` looked like this:
```python
@api.multi
def action_done(self):
    return self.write({'state': 'done'})
```
[Here is the method at the point of a commit on January 3rd](https://github.com/odoo/odoo/blob/581c16ef94798efc8f3720829b97e63354ce948b/addons/sale/models/sale.py#L647)

In February, @jpp-odoo fixed a bug associated with paying by wire transfer: https://github.com/odoo/odoo/commit/6b7bb096e1894b0d8d03eb61ea426dd8730a176d

After this fix, the method now looks like this:
```python
@api.multi
def action_done(self):
    tx = self.sudo().transaction_ids.get_last_transaction()
    if tx and tx.state == 'pending' and tx.acquirer_id.provider == 'transfer':
        tx._set_transaction_done()
        tx.write({'is_processed': True})
    return self.write({'state': 'done'})
```
The problem is that this changes the implicit functioning of the method. It used to be a method that could be called for multiple records at once. But if you try to do it now, you will cause a singletonerror.

We had a customization that allows users to select multiple sales from the list of sales and mark them done simultaneously which broke due to this change.

The reason I think this is a breaking change is that the old version of the method gave no indication that it would only work for a single record at a time. In fact the use of `write()` instead of assigning the value gives a strong hint that it is purposefully designed to be callable with more than one record.

I think the transaction handling should be moved into a `for`-loop so that `action_done` can still be called with multiple records at once.

**Comment by pedrobaeza** [comment]
Well, although multi-record capacity is desirable, it's not really a bug, as all Odoo core calls that method with one single record, so you should do also that. It's not a breaking change in stable.

**Comment by aisopuro** [comment]
So what you are saying is that if a method is decorated with `api.multi`, does not use `ensure_one` and gives no indication of expecting a single record, I still need to go through all the places it is called, and if it is only called as a singleton, that means that I should assume it is called as a singleton?

If this is the philosophy that should be used, what about this example:
```python
@api.multi
def some_method(self):
    for record in self:
        record.something = 23
```
Semantically, this method behaves in exactly the same way: it does not use `ensure_one`, and the body of the method implies that it is designed to be called using multiple records.

But if the UI only allows it to be called on a single record at a time, I can make this change:
```python
@api.model
def some_method(self):
    self.another_field = 'assuming singleton here'
    for record in self:
        record.something = 23
```
If I saw someone making that kind of change, I would be pretty weirded out. If we say this is not a breaking change then we are either saying:
- A) The change I just described is fine and not strange at all
- B) There is something fundamentally different between doing
    ```python
    for record in self:
        self.something = 23
    ```
    and
    ```python
    self.write({'something': 23})
    ```

If A, I disagree and think that would lead to no-one being able to reason about what the code is doing by even reading the code.

If B, I don't see how they are different.

**Comment by pedrobaeza** [comment]
It's not a question of the decorator, but if Odoo code uses it in a multi-record way. If not, it's not a bug, but a desirable thing to have. All methods are `@api.multi` by default. It depends on the contained code if it's limited to one record or to several.

Any way, you have already #32947 for "fixing" it, courtesy of @jpp-odoo
