### ISSUE TITLE
[11.0] Journal Difference Report shows operations from other journals

### ISSUE THREAD

**Issue by alfredourena** [odoo/odoo#32959]
**Edition: enterprise**
**Version: 11.0**
Odoo Ticket: 1974673

**What are the steps to reproduce your issue?**

- create an internal transfer from **Journal A** to **Journal B**

- Open the **difference** report of journal A (Both operations show in the report)

- **Reconcile** the journal entry of **Journal A** in a bank statement

- Check the difference report of **Journal A**

What is the current behavior that you observe?

- The **Journal B** operation shows up in the **Journal A** difference report.

What would be your expected behavior in this case?

**Only journal A** operations should show up in Journal A

**Comment by gdgellatly** [comment]
I thought this was what the transfers account was for?

**Comment by atrivia** [comment]
> I thought this was what the transfers account was for?

Yes. This was working correctly 2 weeks ago.
