### ISSUE TITLE
"Physical Locations"  have been renamed to Chinese，But displayed in English。 

### ISSUE THREAD

**Issue by fenshuajiang** [odoo/odoo#3296]
1）The following image shows "Physical Locations" have been renamed to Chinese。
![image](https://cloud.githubusercontent.com/assets/7471985/4777696/86bdd7b8-5bd5-11e4-9a69-1792340adb1c.png)

2）The following image shows "Physical Locations"  have been displayed in English，But it should be displayed in Chinese。
![image](https://cloud.githubusercontent.com/assets/7471985/4777676/0750b5e0-5bd5-11e4-9438-93e8805bf87b.png)

**Comment by Yenthe666** [comment]
Hi @fenshuajiang,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
