### ISSUE TITLE
I am trying to get cashdrawer open/close status but its giving me RuntimeError: cannot set daemon status of active thread

### ISSUE THREAD

**Issue by ganeshwaghmare248** [odoo/odoo#32969]
Impacted versions: **Odoo-11 Community** 

Steps to reproduce: Create controller for getting cashdrawer status and call the same after each 2 seconds. Following is the code snippet for the same:
**Controller:**
`# -*- coding: utf-8 -*
from odoo import http
import json
import logging
_logger = logging.getLogger(__name__)
from odoo.addons.hw_escpos.controllers.main import EscposDriver
from odoo.addons.hw_escpos.escpos.printer import Usb

class CashDrawerController(http.Controller):
  
    @http.route('/get_cash_drawer_status', type='http', auth="none", csrf=False, cors='*')
    def get_cash_drawer_status(self):
        drawer_status = True
        driver = EscposDriver()
        printers = driver.connected_usb_devices()
        if len(printers) > 0:
            printer = Usb(printers[0]['vendor'], printers[0]['product'])
            if printer:
                status = printer.get_printer_status()
                if 'printer' in status and 'drawer_pin_high' in status['printer'] and not status['printer'].get('drawer_pin_high'):
                    drawer_status = False
                _logger.info("Cash Drawer Status:{}".format(drawer_status))
        return json.dumps(drawer_status)`

Current behavior: Currently i am able to get cashdrawer status but it gives **RuntimeError: cannot set daemon status of active thread** issue. After that need to restart posbox.

Expected behavior: I want cashdrawer status and both printer and cashdrawer should work fine. Is there any other way to get cashdrawer status from printer.

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/27670967/56785673-d80e6480-6813-11e9-970a-30243c7c8bb2.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about custom code. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by rachmataditiya** [comment]
I have similiar issue without customing the code,

**Comment by pedrobaeza** [comment]
Well, if you give reproducible steps to get to the error (and it doesn't depend on your deployment), then go ahead.
