### ISSUE TITLE
12.0 Bank Statement Import not multicompany safe

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#32971]
Impacted versions: 12.0

Steps to reproduce:
In a multicompany environment import a bank statement using a user with access to all companies (and partners) without partners shared.
The import file must contain transactions for multiple companies.
This line

https://github.com/odoo/odoo/blob/7228c10884aaa4b4fdd5d5c21b08dbca8fca016e/addons/account_bank_statement_import/account_bank_statement_import.py#L195

will retrieve any bank and partner the user has access to, but if partner sharing is not enabled it should be filtered by journal.company_id.id or company_id is False.
Current behavior:
AccessError when single company user attempts to open.
Expected behavior:
Don't assign partners and bank accounts for other companies.
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
You're on a roll for multicompany issues 😉

**Comment by gustavovalverde** [comment]
Lovely multicompanies
