### ISSUE TITLE
Broken link in the icon module

### ISSUE THREAD

**Issue by pitmaster40** [odoo/odoo#32996]
Impacted versions: 12.0

Steps to reproduce:
When a new module is created under another language, the icon module is not shown in application list. It appears as broken, in spite of having it in the right folder: module_name/static/description/icon.png

Current behavior:  src image: es-CO/module_name/... 

Expected behavior:  module_name/...

**Comment by pedrobaeza** [comment]
I don't think so. The problem should be another. I have been doing this all the time without that problem, or you are not giving enough information...

**Comment by pitmaster46** [comment]
Ok, maybe, I couldn't explained it well at all. I did other test. My browser's language setting is Spanish. If you look the icon's image link better: es-CO/module_name/static/description/icon.png, Odoo server is changing it. I try to access this icon directly with the right url: module_name/static/description/icon.png, it is changed by: **es-CO**/module_name/static/description/icon.png.
English modules do not have this issue. I don't know what more information I could provide you additionally.

**Comment by pitmaster40** [comment]
Ok, maybe, I couldn't explained it well at all. I did other test. My browser's language setting is Spanish. If you look the icon's image link better: es-CO/module_name/static/description/icon.png, Odoo server is changing it. I try to access this icon directly with the right url: module_name/static/description/icon.png, it is changed by: es-CO/module_name/static/description/icon.png.
English modules do not have this issue. I don't know what more information I could provide you additionally.

**Comment by pedrobaeza** [comment]
But how are you accessing the icon?

**Comment by pitmaster40** [comment]
Directly into the browser:
Icon module of the problem: https://citpa.co/es_CO/library2_app/static/description/icon.png 
Sample Module 'library2_app' : application environment in Spanish.

This icon from an Odoo module: https://citpa.co/mail/static/description/icon.png

If you try to access:  https://citpa.co/library2_app/static/description/icon.png, is changed by: https://citpa.co/es_CO/library2_app/static/description/icon.png

This is what is happening inside the web page content.

**Comment by pedrobaeza** [comment]
But you don't have to do that, as website controller changes that, but if you access the resource from an XML file for example, everything works as expected. Please try.

**Comment by pitmaster40** [comment]
I think, you have misunderstood about what I tried to explained. Please, refer to this screenshot. I don't know if you have already understood what I try to say. The above comment was only an explanation in order to support and picture my issue.

[screenshot1.pdf](https://github.com/odoo/odoo/files/3128946/screenshot1.pdf)

**Comment by pedrobaeza** [comment]
That broken link is due to incorrect addons path or similar, but not a question of languages. I can assure you that this works no matter the language.

![Selección_002](https://user-images.githubusercontent.com/7165771/56922726-34e67500-6ac9-11e9-9e41-767c87f1354a.png)

**Comment by pitmaster40** [comment]
But why?, I am using this addon path: /opt/bitnami/apps/odoo/custom_addons , could it be for this?

**Comment by pedrobaeza** [comment]
Not sure, as Bitnami is a bit tricky on these things. You should try standard installation. Any way, it's clear now that this is not an Odoo problem, so I close.
