### ISSUE TITLE
many2many relationship

### ISSUE THREAD

**Issue by laurisdjilo** [odoo/odoo#32992]
Hello every body! I have an issue with the many2many relationship in odoo 11.
Let say i have a model A defined as follow
class A(models.Model):
    _name = 'module.A'
    b_ids = fields.many2many('B')

class B(models.Model):
    _name = 'module.B'

    def my_method(self):
            #my method

What i want to do in 'my_method' is to get the recordset of A model related to B current record. How can i do that please?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
