### ISSUE TITLE
Odoo Istallation in linux environment 

### ISSUE THREAD

**Issue by mady143** [odoo/odoo#33008]
Hi Everyone,

                     I am getting and error while installing odoo i am running these commands like 

* sudo apt install postgresql -y
* wget https://nightly.odoo.com/12.0/nightly/deb/odoo_12.0.latest_all.deb 
* sudo dpkg -i odoo_12.0.latest_all.deb
* sudo apt install -f

these are commands i am running to install odoo in my linux env  system 

but unfortunately i was unable to installed it successfully so please help me according to the following error i am getting 

=>  **wget https://nightly.odoo.com/12.0/nightly/deb/odoo_12.0.latest_all.deb** - for downloading
=>  **sudo dpkg -i odoo_12.0.latest_all.deb** - to run the downloaded file here i am getting error

Selecting previously unselected package odoo.
(Reading database ... 220217 files and directories currently installed.)
Preparing to unpack odoo_12.0.latest_all.deb ...
Unpacking odoo (12.0.20190429) ...
dpkg: dependency problems prevent configuration of odoo:
 odoo depends on python3-babel; however:
  Package python3-babel is not installed.
 odoo depends on python3-dateutil; however:
  Package python3-dateutil is not installed.
 odoo depends on python3-decorator; however:
  Package python3-decorator is not installed.
 odoo depends on python3-docutils; however:
  Package python3-docutils is not installed.
 odoo depends on python3-feedparser; however:
  Package python3-feedparser is not installed.
 odoo depends on python3-gevent; however:
  Package python3-gevent is not installed.
 odoo depends on python3-html2text; however:
  Package python3-html2text is not installed.
 odoo depends on python3-jinja2; however:
  Package python3-jinja2 is not installed.
 odoo depends on python3-lxml; however:
  Package python3-lxml is not installed.
 odoo depends on python3-mako; however:
  Package python3-mako is not installed.
 odoo depends on python3-mock; however:
  Package python3-mock is not installed.
 odoo depends on python3-ofxparse; however:
  Package python3-ofxparse is not installed.
 odoo depends on python3-passlib; however:
  Package python3-passlib is not installed.
 odoo depends on python3-psutil; however:
  Package python3-psutil is not installed.
 odoo depends on python3-psycopg2; however:
  Package python3-psycopg2 is not installed.
 odoo depends on python3-pydot; however:
  Package python3-pydot is not installed.
 odoo depends on python3-pyparsing; however:
  Package python3-pyparsing is not installed.
 odoo depends on python3-pypdf2; however:
  Package python3-pypdf2 is not installed.
 odoo depends on python3-serial; however:
  Package python3-serial is not installed.
 odoo depends on python3-tz; however:
  Package python3-tz is not installed.
 odoo depends on python3-usb; however:
  Package python3-usb is not installed.
 odoo depends on python3-vatnumber; however:
  Package python3-vatnumber is not installed.
 odoo depends on python3-werkzeug; however:
  Package python3-werkzeug is not installed.
 odoo depends on python3-xlsxwriter; however:
  Package python3-xlsxwriter is not installed.
 odoo depends on postgresql-client; however:
  Package postgresql-client is not installed.
 odoo depends on python3-libsass; however:
  Package python3-libsass is not installed.

dpkg: error processing package odoo (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.21) ...
Errors were encountered while processing:
 odoo

=> **sudo apt install -f** - to install the dependencies for the packages

sudo apt -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  odoo
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 484 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 243190 files and directories currently installed.)
Removing odoo (12.0.20190429) ...

This is the problem i am facing so please help me in this 

Thanks in Advance,
Happy Codding....

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by mady143** [comment]
okay sir, and thank you sir for you valuable answer
