### ISSUE TITLE
[12.0] Sections and notes in invoices losing context on credit note view, turning into products

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#33024]
Impacted versions: 12.0, that we've tested

Steps to reproduce: 
- Create invoice with sections and notes, as well as products
- Validate it
- Add credit note to invoice
- Validate it
- Add the outstanding debit from the created invoice
- Through the "i" button on the "Paid on" section, view the invoice

Current behavior:
- The invoice shows product lines, complete with quantity, unit price, taxes and amount, where notes and sections should be.

Expected behavior:
- The notes and sections should be shown as such, like they're shown in the invoice through the invoice views

I'm thinking it's again the lost context at work here. Seems like a whole lot of problems related to that, which I hope the 13.0 architecture will fix (it's a problem for customers, even if it isn't for us).

**Comment by sswapnesh** [comment]
> I'm thinking it's again the lost context at work here

No, I believe That's because of View Priority (Vendor Bill form view has High Priority by default).

**Comment by sswapnesh** [comment]
AFAIK This can be solved by passing `view_id` based on type of Invoice (and also res_model) at https://github.com/odoo/odoo/blame/12.0/addons/account/static/src/js/account_payment_field.js#L120

**Comment by pedrobaeza** [comment]
Yes, it's the used view, that is not the customer one. @qdp-odoo can you please check this?

**Comment by reinaldoramosarxi** [comment]
Hello,

I will assume that since the other issue was closed because it's by design, that that is the case for this one as well.

Thank you.
