### ISSUE TITLE
There is no way to inherit ReprintButton widget

### ISSUE THREAD

**Issue by rquevedo** [odoo/odoo#33027]
Impacted versions: 10.0

Steps to reproduce: Try to inherit by code ReprintButton widget

Current behavior: When try to inherit this widget by "var reprint_screens = require('pos_reprint.pos_reprint')" the result is undefined.

Expected behavior: When try to inherit this widget by "var reprint_screens = require('pos_reprint.pos_reprint')" the result should be an instance of of this js definition.

Video/Screenshot link (optional):

This error occurs because "return ReprintButton;" or "return {ReprintButton: ReprintButton};" is missing at the end of file "odoo/addons/pos_reprint/static/src/js/reprint.js"

**Comment by pedrobaeza** [comment]
Sorry, but this is not an Odoo error per se. If you want to inherit from something and there's no hook, propose it for master branch in a PR.

Closing by the reason above.

**Comment by sswapnesh** [comment]
Hello @rquevedo ,

Better to add PR with the suggest diff.

Maybe this
```diff
diff --git a/addons/pos_reprint/static/src/js/reprint.js b/addons/pos_reprint/static/src/js/reprint.js
index 8c49beb8e16..b93411b0d3c 100644
--- a/addons/pos_reprint/static/src/js/reprint.js
+++ b/addons/pos_reprint/static/src/js/reprint.js
@@ -36,4 +36,8 @@ screens.define_action_button({
     },
 });
 
+return {
+    ReprintButton: ReprintButton
+};
+
 });
```
Not sure about stable policy here.

**Comment by rquevedo** [comment]
Thanks for the hint @sswapnesh, i will try to make the PR. This kind of hook should be available for all base modules.
