### ISSUE TITLE
internal  server error after new databse

### ISSUE THREAD

**Issue by oitsuki** [odoo/odoo#3302]
Hello,

I try to install a new database inside odoo via the backup function

When I do that :
http://mydomain.com:8069/web/login?db=imaginis . it's ok because it's my first database

but when I decide to change the database. I have an error

http://mydomain.com:8069/web/login?db=odoo ==> my backup databse come from an other server (same version odoo 8.0) 

and when i go http://mydomain.com:8069 and I select before odoo database, the program create also an error.

I try also to stop odoo (sudo service odoo stop) and restart  but it's always the same problem.

I need to do that to access at odoo : http://mydomain:8069/web/login?db=imaginis 
When imaginis is selected then all is ok.

--------------------------------------------------------------
error -  Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Other issue
if i select in dropdown my new database (odoo), I have this error, 
and i go back, I have my odoo in the dropbox
I try to login, but it doesn't work and go back on login page

**Comment by caiki** [comment]
Help, Also I have the same problem.

**Comment by mart-e** [comment]
Hello,

It doesn't seem related. Your issue is about your POP3 server that is not accessible.
By the way, always try to use a `--db-filter` if you have issue connecting before reporting an issue.
Closing this issue as got no details anyway.
