### ISSUE TITLE
Account_cancel does not show option in Journal view in Miscellaneous type 

### ISSUE THREAD

**Issue by timsmet** [odoo/odoo#33043]
Steps to reproduce:
- Install addon
- Enter dev mode
- Go to accounting - settings - journals - any miscellaneous journal
Current behavior:
- Does not show the option "Allow Cancelling Entries"
Expected behavior:
- Should Show it 
Solution: 
- Think it is because the Field "group_invoice_lines" does not exists in Miscellaneous journals (see attachment) 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/34832587/56953503-02765f80-6b3d-11e9-9915-568f1953ac19.png)

![image](https://user-images.githubusercontent.com/34832587/56953511-0609e680-6b3d-11e9-8269-665ad349d397.png)

![image](https://user-images.githubusercontent.com/34832587/56953514-099d6d80-6b3d-11e9-9afd-3c49f6d25c9d.png)

**Comment by pedrobaeza** [comment]
@qdp-odoo is this done on purpose?

**Comment by timsmet** [comment]
FYI if it was done on purpose there is a way to work around it (what I did). Is to change the Journal type back and forth to sales (without saving)

**Comment by qdp-odoo** [comment]
no it isn't. Just an unlucky xpath targetting a field only visible for sale/purchase journals.

@nim-odoo don't you have someone in your team working on that issue already?

**Comment by nim-odoo** [comment]
@qdp-odoo I think it hasn't been reported to my us

**Comment by FlorianGilbert** [comment]
Hi,

This issue is corrected here: f24d5dd2b6c2db1726f41f36fb748f93de76dbdf

Thanks!
