### ISSUE TITLE
Unable to choose a smallest Pictogram in website

### ISSUE THREAD

**Issue by loslolos** [odoo/odoo#3305]
When i tried to choose a smallest pictogram on the website, the biggest one is selected. Seems that all Odoo versions are affected.

**Comment by maclarensg** [comment]
Once selected, click on the pictogram and  select Customize > Change. You can choose the preferred size now.

**Comment by Yenthe666** [comment]
Hi @loslolos,

As stated by @maclarensg you should click on the pictogram then select customize > change. 
After doing this you can choose the size you'd like and it will be followed up by Odoo.

Regards,
Yenthe
