### ISSUE TITLE
some kanban views are truncated

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#33064]
Impacted versions: 11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

some of my kanban views are truncated.
the cards are squeezed.
Have you ever been through this?

![FireShot Capture 003 - Projetos - Odoo - jarvis](https://user-images.githubusercontent.com/12830044/56985568-03b88400-6b5f-11e9-9453-310691cbb399.png)
![FireShot Capture 002 - Ponto de Venda - Odoo - jarvis](https://user-images.githubusercontent.com/12830044/56985503-e2579800-6b5e-11e9-9ff8-2d4707eac499.png)

**Comment by pedrobaeza** [comment]
You have a custom backend theme, so the problem should be there.

Closing meanwhile this is not proved to be on Vanilla Odoo.
