### ISSUE TITLE
[Idea] optionable Quick Create

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#33086]
Quick Create is a good idea for senior user or to make demo,. But for beginer user, intensive user or for a database in production from longtime, this feature is horrible.

I find some different solution to implement this.

Solution 1:
merge this PR https://github.com/odoo/odoo/pull/32013 to remove Quick Create by inherit

Solution 2:
create a group : `base.no_quick_create`

Solution 3:
add a field on user : Desactivate Quick Create

What is your opinion.

Note : by default quick create is stay active.

**Comment by pedrobaeza** [comment]
OCA modules for the same:

- https://github.com/OCA/server-ux/tree/11.0/base_optional_quick_create
- https://github.com/OCA/web/tree/12.0/web_m2x_options

**Comment by fmdl** [comment]
Yes, but is not user dependant.

**Comment by gustavovalverde** [comment]
It would be great if this could be an option on Odoo

**Comment by gdgellatly** [comment]
Personally I'd just extend `web_m2x_options` to support both model and user level options. It's 90% there already. 

To do for users in `web_m2x_options` is really just a case of one security group, and editing one function. Although I wouldn't do as a security group. I'd create a Selection field called `use_quick_create` on the user with options

`false`: Never
`default`: Default (e.g. use web_m2x defaults)
`true`: Always

and default of `default`

Then just edit `get_m2x_options` to get the value from user.

Models is a bit longer, but pretty straightforward as well.

**Comment by gustavovalverde** [comment]
I've just tested `web_m2x_options` and I must say that's the best module **ever** 😄
