### ISSUE TITLE
[11.0] Changing a translatable field doesn't change the 'source' term

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#33088]
**Tested on Runbot**
**OPW-1981683**

#### Impacted versions:
11.0, 12.0
#### Steps to reproduce:
- Create a database in Spanish (main language)
- Add a new language (English for example)
- Create a product with the `name`: **Product A** (while being in spanish)
- Change the field `name` to: **Product B**
#### Current behavior:
- The `source` field in the translation stays as **Product A**
#### Expected behavior:
- The source **must** change each time we change the product name. When changing the name in the product is the source name that we're changing, not the translation.

**This causes a bunch of unexpected behaviors:**
- If we would like to clean the translations (delete them to recreate them), all the actual product names, categories names, etc...get overriden by the old values.
- If we sent a purchase order via email in another language it shows the `source` (old value) of the field instead of the new one.
#### Video
https://youtu.be/HE6lLi2rW9E

**Comment by gustavovalverde** [comment]
This comment is also an unexpect behavior:
https://github.com/odoo/odoo/issues/22060#issuecomment-414671042

cc: @mart-e

**Comment by wtaferner** [comment]
@gustavovalverde 
This is expected behavior as you are translating in the current language of your user...there is even a blue not after saving. In case you deactivate English as a language and only Spanish is available for the users it will do what you expect.

**Comment by mart-e** [comment]
Hi,

Keep in mind that English is always the master version and another language are translations. When you are modifying a record in Spanish, you are modifying translations. If you modify in English, it will modify the master version (in your example, directly on the product.template record)

Also, aren't you mixing the fields `src` and `source`?
The `source` is not stored and should always reflect the right value.
`src` is more for internals/debugging and should not be used.

Does it answer your question?

**Comment by gustavovalverde** [comment]
So what would be the expected use for a **final user** that always uses the system in a non-english language? Considering that they have multiple language installed for the sole purpose of sending Quotes and RFQ in the client/supplier language:

(a) Change the product name, then going to the translation and also changing the source term (because we don't want the old value there for any of the other languages)?
(b) The user should change the language to english in its preference, change the product name, then change the language to his main?

Shouldn't we be able to set a **main** language for a company/database, so each time a user changes a name in **that** main language, they don't have to make all the steps above each time?

**Comment by mart-e** [comment]
The (b) is the simple cases but see #31090 where we are developing a better way to manage translations without accessing the technical view with the list of translations.

About setting a different language than English as the reference, this is a frequent feedback. Hopefully we will have this one day but at the moment, this is not the case. There is still [too many](https://github.com/odoo/odoo/search?l=Python&q=en_US) places in the code where we assume en_US is the default.

Closing as not showing a bug on the translation system (but I agree the usability should be improved).
Hopefully with #31090 we will already remove some confusion.

**Comment by gustavovalverde** [comment]
Thanks for your answers @mart-e, I'm at ease knowing that there's a WIP for this matter.
