### ISSUE TITLE
Blur Menu: When We used Google Chrome Browser

### ISSUE THREAD

**Issue by nikul-serpentcs** [odoo/odoo#33096]
Impacted versions:
* When I Used Version 12 server in Google Chrome Browser.

Steps to reproduce:
* Run Server In Google Chrome Browser after Zoom 90%, Odoo menu is Blur.

Current behavior:
* If Zoom 100% work Fine, But If Zoom Out and 90% or 80% Menu did not appear Good, It's Like as Blur.

Expected behavior:
* If we Zoom In 100% or Zoom out 90% Menu screen look like as it's.
* Look Like FireFox Web Browser: 
![mozila firefox menu](https://user-images.githubusercontent.com/17664321/57062455-c9292580-6cdd-11e9-9364-74bdd30eface.gif)

Video/Screenshot link (optional):
![latest Menu Blur Google browser](https://user-images.githubusercontent.com/17664321/57061834-055b8680-6cdc-11e9-9609-d7bacc293f9c.gif)

**Comment by pedrobaeza** [comment]
I don't have that problem in my Firefox. Is it maybe due to your fonts?

**Comment by thuaniwebsite** [comment]
Firefox works normal as pedrobaeza stated. I tested on my machine.

Chrome and Brave has this problem.

It's the dropdown that's causing it.

Class: dropdown-menu show > 
border-radius: 3px;

If you change it to 0px, it's clear

.dropdown-menu 
/web/content/661-031de62/web.assets_backend.0.css

**Comment by pedrobaeza** [comment]
Thanks for the extra information. Tries on Chrome and confirms the problem. @mge-odoo are you the responsible for handling this?

**Comment by nikul-serpentcs** [comment]
> I don't have that problem in my Firefox. Is it maybe due to your fonts?

Yes Firefox Is Good but Problem in `Chrome`

Also, I Added `Steps to reproduce`

> Steps to reproduce:
> 
> Run Server In Google Chrome Browser after Zoom 90%, Odoo menu is Blur.

**Comment by mge-odoo** [comment]
@pedrobaeza not anymore but @aab-odoo can maybe take a look?

**Comment by pedrobaeza** [comment]
Thanks for the ping.
