### ISSUE TITLE
QR code scanner with odoo

### ISSUE THREAD

**Issue by GauswamiSaumil** [odoo/odoo#33126]
i am scanning the QR code  with QR code scanner machine...

i attached it with my machine but when my record is fetched .. it is in <?xml format ....

i want to store that data into a string ..how i can do that?

**Comment by Yenthe666** [comment]
Hi,

Are you sure you did not misconfigure your scanner or your custom development? I can assure you scanning barcodes works just fine in Odoo. We have dozens of customers working with scanners.
Can you reproduce it in runbot?

**Comment by GauswamiSaumil** [comment]
sir,it's working correctly but i want the fetched data into a string  or some temp variable ..

it's returning the data but with code ..and than i save it than it's fine...but when i click on the field and fetch data from machine their i can see like ....<?xml name="xyz" ....etc.

**Comment by Yenthe666** [comment]
Hi,

So you're talking about custom development & want to alter it yourself or? The descriptions are really vague.

**Comment by GauswamiSaumil** [comment]
yes sir exactly... 
data is coming from QR code scanner right?...after that data came i want to store it in some variable before it go to the database..

**Comment by Yenthe666** [comment]
Hi,

The Github tracker is only for issues in the official code though. You should ask this on the official help forums (at https://www.odoo.com/forum/help-1) where people can help you.
In short: you can create a Python variable and do whatever you like with the value there.
