### ISSUE TITLE
XSS on the chatter

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#33135]
**Impacted versions:**

earlier?
11.0
12.0

**Steps to reproduce:**

Go to [https://github.com/odoo/odoo/blob/11.0/addons/mail/static/src/xml/thread.xml#L215](https://github.com/odoo/odoo/blob/11.0/addons/mail/static/src/xml/thread.xml#L215)

**Current behavior:**

Emails saved with malicious HTML tags like `<base target="_self" href="https://malicious.com" />` could redirect traffic to another endpoint.

**Expected behavior:**

using `t-esc` instead of `t-raw` to print the body of the message.

**Video/Screenshot link (optional):**

No need, everything is in the steps to reproduce.

**Comment by pedrobaeza** [comment]
Please see https://www.odoo.com/security-report

**Comment by Yenthe666** [comment]
I'd rather close this issue off honestly. Feel free to report security issues through the responsible channels, which are not publicly available (as @pedrobaeza has mentioned).
CC @odony
