### ISSUE TITLE
[11.0] [base_vat] Country code not checked

### ISSUE THREAD

**Issue by elarapuntsistemes** [odoo/odoo#33136]
**Impacted versions:**
11 and above

**Steps to reproduce:**
    1. Install base_vat module.
    **2. Create a new partner and select a country. I.e.: Belgium**
    3. Write a vat number without country code. I.e.: 0477472701
    4. Save.
  

**Current behavior:**
As you can see in the image, Odoo allows to save the partner without the country code.

![imagen](https://user-images.githubusercontent.com/17743542/57135073-82ecc880-6da8-11e9-8f89-75c03c342394.png)

**Expected behavior:**
This feature was working different in previous versions: 10.
It was mandatory to write country code in the vat number field, otherwise, it didn't allow to save.

![imagen](https://user-images.githubusercontent.com/17743542/57135095-9304a800-6da8-11e9-8740-e3d427036f6f.png)

**Comment by pedrobaeza** [comment]
Already answered in https://github.com/OCA/OCB/issues/848#issuecomment-489064351
