### ISSUE TITLE
[8.0]Wishlist method to be more modulize

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#3313]
Hi Odoo,

I like to suggest that the writing the method on Odoo must be more modulized, because there's some method that hard to be overide.

For example: method make_mo in MRP module.
This method use for making manufacture order from procurement, and it directly confirm too in this method.

I think this must be separate, 

for example:
we must create a new method to prepare the value, and then method to create a MO, and then another method to confirm the MO,

This way we can easily overide each method when we want to make a change.
We have this kind of code in Sale module, and some another module which is great,
Why we don't standardize this way?

Here the list method that I wist to be more modulize:
1. make_mo (MRP)
2. _action_compute_lines (MRP)
3. _make_production_line_procurement(MRP)
4. _create_pickings(procurement)
5. recompute_voucher_lines(account_voucher)
6. split (stock)
7. do_partial(stock)

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: you're always welcome to make PR's to fix these kind of things!

Regards,
Yenthe
