### ISSUE TITLE
[8.0] Sales Receipts rounding problem

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#3314]
Impacted versions:
7.0 and 8.0

Steps to reproduce:
Set currency rounding factor to 0.05 and you create a Sales Receipt with amount of 77.60, journal entries will be unbalanced!

Check this screenshots:
![sale-receipts-rounding-01](https://cloud.githubusercontent.com/assets/4398840/4789461/6f27308a-5dc5-11e4-8d6d-df8c8d8c1e97.png)

![sale-receipts-rounding-02](https://cloud.githubusercontent.com/assets/4398840/4789464/73fc26c4-5dc5-11e4-890a-a57297e95fe8.png)

Current behavior:
If currency rounding factor is 0.05, journal entries are wrong and unbalanced:
line amount will be rounded to 0.05 but tax of the Sale Receipts won't be rounded

Expected behavior:
Rounding factor should also be applied to taxes on Sales Receipts..

Test on runbot: http://23958-8-0-24ec22.runbot6.odoo.com/web

**Comment by Yenthe666** [comment]
Hi @thomich ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
