### ISSUE TITLE
[11.0] mrp: Products can be multicompany shared, but their BoMs aren't

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#33148]
**opw-1984901**

#### Impacted versions:
11.0, 12.0
#### Steps to reproduce:
- Create Product A, which is shared between 8 companies
- Create a BoM of type Kit that could be used between companies
#### Current behavior:
The BoM requires a single company
#### Expected behavior:
We must be able to use a single BoM for multiple-companies. Otherwise each time a company/product is created a BoM has to be created for each of the companies.

**Comment by gdgellatly** [comment]
@gustavovalverde It just isn't that simple in practice.

Quality Control
Routings are typically location specific
Revisions

I had a similar thought to you, but in the end, it just got too complicated even for simple manufacturing. Now for Kits maybe you have an argument, but that argument probably is they shouldn't be BoM's at all.

Beyond the obvious, its the little things that get you. e.g. component A is transitioning to component B and location 1 has 20,000 of A left in stock, but B has none. Location 1 has a machine which runs twice as fast as location 2. 

But actually, now in practice with many thousands of BoM's across 12 companies, it isn't that bad maintaining. In fact, now we see the individual companies taking ownership of them and optimizing for their own markets, stocking situations.

**Comment by pedrobaeza** [comment]
I agree. Enabling that feature would provoke a lot of misunderstandings. Closing then.

**Comment by gustavovalverde** [comment]
> Now for Kits maybe you have an argument, but that argument probably is they shouldn't be BoM's at all.

@gdgellatly as my argument is based on Kits, what would be your proposal to solve this problem?

I'm mainly dealing with a client selling franchises, each being a new company that inherits all the logic from the headquarters (another company, which is not a parent company). An they sell kits, which are all the same for all the franchises.

As we can't **copy** the configurations from one company to the other, most of the accounting has to be manually done. But it's not so complex as there's not a bunch of difference from Odoo's core CoA, which gets created for each new company.

But dealing with over **4,000** products and having to duplicate each configuration and each BoM for  franchises that get sold on a bimonthly basis to people that's just open Odoo, hit & sell, it's just too laborious for the headquarter which has just 1 person creating products on a daily basis.

Any ideas on how you'd tackle this @pedrobaeza ?

**Comment by gdgellatly** [comment]
Export/import works for initial loading. 4000 is not so much especially if they don't change a lot. 

Sorry I wasn't proposing anything, just merely observing that using boms to define bundles conflates 2 different things. One is a recipe with lots of complexity. The other is just a list of products that get sold together.

**Comment by andrp92** [comment]
@pedrobaeza please review what @gustavovalverde said after you closed the ticket. It makes sense to do something when it comes to kits. What would be the best solution ?

**Comment by pedrobaeza** [comment]
Too much overhead for that residual feature. And kits will probably have another treatment in v13, according Odoo's roadmap, so this continues as won't fix.
