### ISSUE TITLE
[11.0] product: Attribute is not shown in many2one if there's just 1 value

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#33166]
**opw-1985180**
**Tested on Runbot**

#### Impacted versions:
11.0, 12.0
#### Steps to reproduce:
- Choose the iPad Retina Display in the demo database
- This product has a **Wi-Fi** attribute with just one value
- It's even shown on each variant of the product (expected)
- Go to the sales app
#### Current behavior:
- On the sales order lines it doesn't show the **2.4 Ghz** Wi-fi **attribute value** on the variants
#### Expected behavior:
- If there's an attribute with just 1 value, it must be part of the computed name of the variant.
#### Video/Screenshot link (optional):
https://youtu.be/_OaDRoF7Sx8

Related to: https://github.com/odoo/odoo/issues/5225 (from 2015)

**Comment by dbo-odoo** [comment]
Hi,

This is the expected behaviour. Including an attribute with a single value brings no information, only clutter in the UX.

Cfr https://github.com/odoo/odoo/blob/11.0/addons/product/models/product.py#L407 in the code if you want.
