### ISSUE TITLE
What’s the development goal of Odoo in the future? Today countless Python projects like Dropbox, Zhihu, YouTube etc. start to use Golang as their programming language, does Odoo have this idea in mind in short/long terms, so as to improve the performance?

### ISSUE THREAD

**Issue by i-lifei** [odoo/odoo#33160]
What’s the development goal of Odoo in the future? Today countless Python projects like Dropbox, Zhuhai, YouTube etc. start to use Golang as their programming language, does Odoo have this idea in mind in short/long terms, so as to improve the performance?

**Comment by pedrobaeza** [comment]
No plan for using Go in the short term.
