### ISSUE TITLE
Import product using csv with new added attribute and attribute value

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#33165]
Impacted versions: Odoo 11.0

Steps to reproduce:

- Check `Attribute and Variants` in Inventory settings.
- Click `Attributes`, pick an attribute and export fields `id, name, value_ids/id, value_ids/name`
- Add a new name into `value_ids/name` with a given external ID in `value_ids/id`.
- Import .csv file, click **Test Import** and receive an error `No matching record found for external id` 

Current behavior: Import function not able to create a new record for the model.

Expected behavior: Import function create a new record in the model with given **external ID** and **value**.

More Information: I remember that when I using **odoo12**, I came across a checkbox which is similar to **Create if not exist** when using the import function.

**Comment by MarissaLin** [comment]
Hi 

I came across the same issue with Odoo v13. Have you ever got a solution to this? 

Thank you. 

Kind regards
Marissa
