### ISSUE TITLE
Internal transfer numbering

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#3317]
There are some cases in which the stock picking name is not set with the corresponding sequence, e.g. when an internal transfer is create.

Impacted versions: 7.0

Steps to reproduce: Confirm a manufacturing order

Current behavior: 
Internat transfer name = Null

Expected behavior: 
The internal transfer name should be based on the corresponding sequence e.g. INT/2014/0078

Actual code:
addons/stock/stock.py:  
633  def create(self, cr, user, vals, context=None):
634        if ('name' not in vals) or (vals.get('name')=='/'):
635            seq_obj_name =  self._name
636           vals['name'] = self.pool.get('ir.sequence').get(cr, user, seq_obj_name)
637        new_id = super(stock_picking, self).create(cr, user, vals, context)
638        return new_id

Proposed change:
634        if ('name' not in vals) or (vals.get('name') in ('/', False)):

**Comment by Yenthe666** [comment]
Hi @jalzaga,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
