### ISSUE TITLE
backorder_id field not filled

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#33189]
Impacted versions: 11.0 and 12.0 (These are the ones I tested upon even on runbot)

Steps to reproduce:

1. Create a stock picking (Delivery, Receipt, Internal Transfer)

2. Validate the picking

3. Return products by clicking the button Return. The backorder gets created but its field has no value

Current behavior:
Field backorder_id not filled
Expected behavior:
The created return picking's field backorder_id must be equal to the id of the picking from which the return is created

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Backorder is for other thing: When you delivered half of the picking, and you decide that want to delivery the rest of the remaining goods in another picking. That's a backorder and the field is filled in that case.

Closing as no valid.
