### ISSUE TITLE
Getting error when try to download multiple invoices

### ISSUE THREAD

**Issue by ntihomir** [odoo/odoo#33182]
Impacted versions:12.0

Steps to reproduce:Select more than 6 invoices to print

Current behavior: Getting error when try to print multiple invoices

Expected behavior:

Video/Screenshot link (optional):

![Invoices   Odoo](https://user-images.githubusercontent.com/40853383/57221586-153ad980-7000-11e9-8d2e-fc61705ff0da.png)

**Comment by Yenthe666** [comment]
Hi @ntihomir,

I've just tested this on the latest 12.0 but this issue was no longer reproducable.
Can you reproduce it on the latest runbot (at runbot.odoo.com) or after updating your Odoo source code to the latest version?

Regards,
Yenthe

**Comment by ntihomir** [comment]
Hi @Yenthe666 ,

I upgraded to new version, and that resolved the issue.
Thx.

Regards,
Tihomir

**Comment by Yenthe666** [comment]
Good to hear, thanks a lot for the feedback.
