### ISSUE TITLE
invoice advance

### ISSUE THREAD

**Issue by DavideSavoneEVE** [odoo/odoo#33190]
Impacted versions:
10
Steps to reproduce:
Make and adavance invoice - fixed - 
Current behavior:
The line generated on the final invoice has negative quantity that block forward steps, like fatturapa_out for the electronic invoice
Expected behavior:
The generated line should be with negative amount but positive quantity
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

Please fill in all the fields on the Github issue. Otherwise we cannot help you.

**Comment by DavideSavoneEVE** [comment]
v10

problem. on make_invoice_advance 
The problem is related to the generated when we do the total invoice. 
On the final invoice, the line recalling the advance invoice has -1 quantity, that means the next export to xml will fail for the Agenzia Entrate rules . For that xml we can only have 0 or more quantity and a price_subtotal that can be negative.

**Comment by DavideSavoneEVE** [comment]
> Hi,
> 
> Please fill in all the fields on the Github issue. Otherwise we cannot help you.

I changed the description, quite clear now .

**Comment by Yenthe666** [comment]
Dear @DavideSavoneEVE,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
