### ISSUE TITLE
[10.0] Disconnections through public ip/nginx

### ISSUE THREAD

**Issue by JeremyOL** [odoo/odoo#33199]
Hi, I have a problem when connected to my odoo instance through port forwarding, the problem comes when I put workers > 0.
I don't have this problem with workers = 0

- Impacted versions:

   10

- Steps to reproduce:
  1. Set a port forward from my router IP to my server IP.
  2. Configure workers > 0
 This is my workers configuration:

    ```
    workers = 14
    limit_memory_hard = 13690208256
    limit_memory_soft = 11408506880
    limit_request = 8192
    limit_time_cpu = 120
    limit_time_real = 240
    max_cron_threads = 2
    ```
  3. Run server
  4. Enter to Odoo from outside the LAN and through the public ip address, do a SO, quotation or something.
     - The best way to get the error is trying to get a list of all SO, the job needs to show the loading for a minute to send it, this occurs into and outside the LAN.
     - The problem is the same using nginx for proxy reverse.

- Current behavior:
  - The server disconnects me and show a dialog of reconnect occasionally when trying to do a quotation (outside the LAN).
   - The server disconnects me and show a dialog of reconnect all the times when a request lasts 1 minute (outside/into the LAN).
    - This only occurs through the public ip or nginx.

- Expected behavior:
  - The server should works without the disconnect and reconnect.

- Video/Screenshot link (optional):
   Disconnected occasionally:
   I put the image when the error triggers, it occurs but not all the time.
   Disconnected at minute:
   ![image](https://user-images.githubusercontent.com/49690644/57251977-f9cfce80-6fff-11e9-8707-a1d60e1e669f.png)

All the issues are triggered only when the connection is through the public ip or nginx, entering with the local ip of the server is ok.

**Comment by pedrobaeza** [comment]
Sorry, but this is something of your deployment, not of Odoo. You should query about this on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
