### ISSUE TITLE
[12.0] Wrong Amount Due in Credit Note for Vendor

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#33201]
**Impacted versions**: 12.0

**Steps to reproduce**:
- Create a Product Category with the following configuration:
   * Costing Method:  Average Cost (AVCO)
   * Inventory Valuation: Automated
   * and set the Price Difference Account, with an Income Type Account

- Create a Storable Product and set the Product Category just created, and set the Cost as 56.04
- Create a Credit Note for Vendor with the product just created and set: 
   * Price Unit = 56.0
   * Discount = 3.0
- Validate the Invoice

**Current behavior**:
The Total and the Amount Due is different

![image](https://user-images.githubusercontent.com/5191766/57265135-1c83d680-7044-11e9-87f0-1a609ee287d2.png)

**Comment by goliveirab** [comment]
FYI

@moylop260 @luistorresm

**Comment by gdgellatly** [comment]
@goliveirab this is a duplicate, mine is under OPW for a couple of weeks now, and also on this issue tracker. It is literally an 8 character fix, but support is now saying that it is somehow related to another issue (I presume the one I showed could in no way be related) so they can't do anything.
