### ISSUE TITLE
[12.0]Permissions error trying to update partner with subscription

### ISSUE THREAD

**Issue by tomeyro** [odoo/odoo#33200]
**Impacted versions:**

12.0

**Steps to reproduce:**

On a multi-company environment where the companies are not under one another.
1. Create a partner without company and without country.
2. On company 1, create a subscription for partner.
3. On company 2, create another subscription to the same partner.
4. Try to edit partner  and set its country.

**Current behavior:**

An error is raised saying I don't have permissions to edit subscription.

**Expected behavior:**

The partner is saved correcty without raising any errors.

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/8657959/57256756-1d554200-701d-11e9-9b5e-6a3f101308ae.png)

**Assumptions:**

The subscription model has a country_id field that is a related field that  
points to the partner country field. This, when the partner changes its  
country, it will try to recompute, and fail on save.

**Related to:** 

OPW-1985688

**Comment by simongoffin** [comment]
Closed with https://github.com/odoo/enterprise/commit/c2696065d7c967c25c92c5cc504a76d636195880
