### ISSUE TITLE
Fix WorkerHTTP timeout message log level 

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#33207]
I use Sentry to track errors.
And it is annoying to get a new issue every time a timeout happens.
Especially when there is no requests at all (at night for example).
So I have 2 proposals:
1) Set WorkerHTTP timeout message level from ERROR to at least WARNING or INFO
2) If a timeout happends during call execution level should be WARNING, if timeout is due to lack of activity level should be INFO (why at all restart worker that did not do anything!?).

Thanks for your attention.

**Comment by pedrobaeza** [comment]
IMO you should filter out that one or don't let the timeout to happen. I don't have that timeouts in my system normally.

**Comment by Yenthe666** [comment]
I can agree it is being annoying being shown in Sentry however if your workers have long enough times you shouldn't get these in the logs in the first place. Right?

**Comment by litnimax** [comment]
This is IoT app. So RPC calls are short.
Only "hang" calls last more then a few seconds.
So I set worker timeout to 30 seconds to restart and reset these hang requests.
And I noticed that I get this error even when there is no requests.
Ok guys I can easily live as is.
Just decided to get this up to make a better Odoo :-)
As I think worker restart deserves a warning and not error :-)
You can close it if you think it's ok.
Thanks.
