### ISSUE TITLE
Document Management taks rename and remove task v12

### ISSUE THREAD

**Issue by ElisevanM** [odoo/odoo#33202]
Impacted versions: v12

2 problems

Steps to reproduce:
problem 1
Create a task with the action button
the task is created
Rename the task
Go to My task
You can see the renamed task and the attached documents.

When you go back to the document management and the document, you can see the task has the initial task name and not the renamed task.

Problem 2
When you remove the task, the document is als removed in the document management app.

See video:

https://www.screencast.com/t/au10Eej5Ax

Kind regards,
Elise van Maarschalkerweerd
dutchworld.nl

**Comment by Yenthe666** [comment]
@ThanhDodeurOdoo probably for you to check.

**Comment by ThanhDodeurOdoo** [comment]
@Yenthe666 Hey, it seems to be the same problem as: https://www.odoo.com/fr_FR/my/task/1943295

**Comment by Yenthe666** [comment]
@ThanhDodeurOdoo thanks for the feedback! I don't think you know but I don't have internal task rights :) I only have nearly full Github access as I'm a contributor. I basically do this to help Odoo. Can you share the main feedback/info from the task here maybe?

**Comment by ThanhDodeurOdoo** [comment]
@Yenthe666 hey, sure:

the field displayed there is just a related to the res_name field of the ir.attachment; the problem seems that it is a stored computed field that depends on res_model and res_id, so it doesn't seem to be recomputed if the name (display_name, which in the case of invoice should indeed be based on invoice.name and invoice.number) of the record (res_model/id) changes.

**Comment by Yenthe666** [comment]
Aha, that makes sense! I guess in that case we can confirm this as a bug. Is there a related OPW for it or a task for somebody internal to change this?

**Comment by ThanhDodeurOdoo** [comment]
I don't think there are active tasks to fix this

Here was the PR for a potential fix: https://github.com/odoo/enterprise/pull/3765
 @jpp-odoo probably knows more than me on the current state of the matter.

**Comment by pedrobaeza** [comment]
This being enterprise and so old, I think it should be closed.

**Comment by Yenthe666** [comment]
Yep, let us assume it is solved.
