### ISSUE TITLE
Update module bug with deleted field 

### ISSUE THREAD

**Issue by jo541** [odoo/odoo#33221]
Impacted versions:12.0
more version information:
ODOO_RELEASE=20190424
ODOO_SHA=3885be6791b9b8c2a74115299e57213c71db4363
I used odoo docker version 

Steps to reproduce: 

1. Create a new field in Python
2.  Add it in inherited view of res.partner
3. Update odoo with -u "./odoo-bin -u "your_module"
4. Remove the field in python file and xml file in same time
5. Update odoo again with -u 
6. Error message say the field xxxx doesn't exist.

Current behavior: 
Error message and I need update in first time XML and after python . 

Expected behavior:
Have a possibility to update Xml and py in same time

It's like a server update python and remove field and try to load view without update .

**Comment by pedrobaeza** [comment]
This is supported by default. If you don't put the exact error, it's difficult even to know the problem.

**Comment by jo541** [comment]
An exemple of message. 

```
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3269, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3413, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `our_brands` does not exist
```

**Comment by gdgellatly** [comment]
I think if you read the full error message you will find you've left that field in a view somewhere. Maybe a dependent module even. But if you are using docker, then you have all sorts of new problems which are hard to diagnose. Like did you restart, did you rebuild, re-up what's the orchestrator.

I use docker quite widely, but default Odoo docker image is hardly a development image. And generally you don't do updates inside the container because then you'd have 2 Odoos running, one with old code, one with new. Usually its in a seperate container using docker run or similar.

**Comment by Yenthe666** [comment]
As @gdgellatly has answered you've forgotten a field in an XML definition somewhere.
I can assure you this works fine out of the box. Our whole team does this on a daily basis without issues.

**Comment by jo541** [comment]
I created a specific field and this field are only in one place in XML. I'm sure I removed all xml definition of this field. Because when I update in first time in xml and after I update python . I don't have a error message .

**Comment by jo541** [comment]
I found the real bug. It's because I inherit "sale.res_partner_view_buttons" before  "base.view_partner_form". and when I try to updated module with modification in "base.view_partner_form" in same time removed field in python file and XML.
