### ISSUE TITLE
Module: sale_crm. Salesteam not updated nor propagated correctly to invoice

### ISSUE THREAD

**Issue by codeback** [odoo/odoo#3327]
Impacted versions:
- 7.0

Steps to reproduce:
1. Create a new sale order
2. Select a partner
3. The partner's salesteam is not shown in the sale order
4. If you select the salesteam and confirm the sale order and your configuration is set to "Generate invoices after and based on delivery orders", the salesteam is not stored in the invoice.

**Comment by Yenthe666** [comment]
Hi @codeback,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
