### ISSUE TITLE
purchase price miss purchase UOM information

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#33277]
When setting purchase price (vendor price) on products with various UOM, users have difficulties to remember if purchase price should be set on _one_ product only or on _purchase UOM_ products.
The help doesn't help here see the reference :
https://github.com/odoo/odoo/blob/f1d6a6108e40569d4716cf45feb2b30cabf547bd/addons/product/models/product.py#L750

I don't know if the help should be rewrited, because of many possible options. Adding the purchase UOM value after the vendor price field might be a better solution. In this case, the Product's vendor price form would became :
**Price List** 
Minimal Quantity ________ dozen
Price                   ________ _for dozen_

**Comment by sle-odoo** [comment]
It s clearer in master now with the inline editable list.

**Comment by zeroheure** [comment]
@sle-odoo coujld you show me the reference ? thanks.
