### ISSUE TITLE
Odoo V12 CE Segmentation fault (core dumped) facing this issue at the time of login after database restore

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#33281]
> 2019-05-09 07:42:49,840 608 INFO crm odoo.modules.loading: 104 modules loaded in 3.11s, 0 queries
> 
> 2019-05-09 07:42:50,970 608 INFO crm odoo.modules.loading: Modules loaded.
> 
> 2019-05-09 07:42:55,479 608 INFO ? odoo.http: HTTP Configuring static files
> 
> 2019-05-09 07:42:55,508 608 INFO crm odoo.addons.base.models.ir_http: Generating routing map
> 
> 2019-05-09 07:42:57,637 608 INFO crm odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [6094]
> 
> Segmentation fault (core dumped)

**Comment by pedrobaeza** [comment]
Please use odoo/docker for reporting these issues, and without more information, I don't think it can be solved.
