### ISSUE TITLE
[12.0] finish refactor of stock.warehouse._get_all_routes()

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#33286]
Impacted versions:
12.0

Steps to reproduce:
Try to implement advanced routes in code like MTS+MTO

Current behavior:
Practically all implementations/overrides of `stock.warehouse._get_all_routes()` call their parent's implementation of `get_all_routes_for_wh()` which is a reference to `stock.warehouse._get_all_routes()` but that means that the route 'mixin' behavior can be skipped. (the reference is to the base implementation of `_get_all_routes()`)

Whichever `_get_all_routes()` implementation gets called first, jumps straight to the base implementation and will skip any of the other valid routes for that warehouse.  
If this is intentional, I cannot think of a reason.

Expected behavior:
The core would call the parent's method, or provide a good comment as to why this is expected.

I can provide a pull request to fix, but I wanted to make sure that there wasn't some deeper meaning going on here.

**Comment by pedrobaeza** [comment]
Why don't providing a PR with the fix instead?

**Comment by jaredkipe** [comment]
@pedrobaeza Sure thing!
