### ISSUE TITLE
Magic fields have no index

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#33292]
From odoo/models.py:
```
if self._log_access:
            add('create_uid', fields.Many2one(
                'res.users', string='Created by', automatic=True, readonly=True))
            add('create_date', fields.Datetime(
                string='Created on', automatic=True, readonly=True))
            add('write_uid', fields.Many2one(
                'res.users', string='Last Updated by', automatic=True, readonly=True))
            add('write_date', fields.Datetime(
                string='Last Updated on', automatic=True, readonly=True))
```

IMHO they must be created with index=True by default.
What senior developers think?

**Comment by gdgellatly** [comment]
Why? I've optimized postgres indexes in Odoo a long time and never once has these fields been the culprit.

Thats a lot of overhead for rarely used fields in most models. Lets face it 90% of indexes are rarely used for most models anyway. I doubt for example any index on res_company is ever used by anyone.

What common orm read/select queries are using these? what is the performance impact, both in terms of read and write, across all models?

**Comment by litnimax** [comment]
Ok seems it's just my case.
Thanks for your attention.
