### ISSUE TITLE
 import journal entry in odoo v 11

### ISSUE THREAD

**Issue by lili94** [odoo/odoo#33297]
hi i am trying to import journal entry in odoo v 11 with excel file i have one journal entry with 6 record in journal item but i got 6 record in journal entry not one i don't have any error but result is false can anyone know how to import

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
