### ISSUE TITLE
[12.0]The time of traceability report of product is not the correct local time.

### ISSUE THREAD

**Issue by hzh0292** [odoo/odoo#33309]
Version: 12.0
The time of traceability report of product is uct time.
It should be transformed into local time.
![](https://i.bmp.ovh/imgs/2019/05/30abd9f26524be15.png)

**Comment by sswapnesh** [comment]
Added Fix at https://github.com/odoo/odoo/pull/33310

**Comment by hzh0292** [comment]
It works.[#33310](https://github.com/odoo/odoo/pull/33310)

**Comment by hzh0292** [comment]
It works.[#33310](https://github.com/odoo/odoo/pull/33310)

**Comment by sswapnesh** [comment]
Better to leave it open till that PR or similar  solution is getting merged.

**Comment by hzh0292** [comment]
> Better to leave it open till that PR or similar solution is getting merged.

OK

**Comment by hzh0292** [comment]
reopen
