### ISSUE TITLE
Creating supplier from product_supplier form, system creates customer

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#3330]
Use case:

Go to product
Go to procurement
Suppliers --> add an item
Write something and quick create 
Open created partner form

Record is created: 
is_company= false (should be true), 
is_supplier = false (should be true), 
is_customer = true (should be false).

Thank you!!
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
