### ISSUE TITLE
Zero valuation error while trying to update qty after processing Manufacturing order.

### ISSUE THREAD

**Issue by tejasthakar333** [odoo/odoo#33329]
Impacted versions: Odoo 11, Odoo 12

Steps to reproduce: Create a stockable product with any cost and sale price make sure you use Costing Method as **Average Cost** and Inventory Valuation as **Automated**. Create a **stockable component** with **14.999 qty** on hand and set any cost and sale price(in my case cost is 3.24$ and sale price is 1$). Create a manufacturing order with 15 qty and process order to **In Progress** state.
Now, Create another manufacturing order same as above in the **Confirmed** state. Now try to update qty of the component to 15.

Current behavior: While updating qty on hand it will give you zero valuation error: `The cost of Demo component is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation.`

Expected behavior: There shouldn't be an error instead of error qty update operation should be done.

Video/Screenshot link (optional):

![First MO](https://user-images.githubusercontent.com/17230264/57618658-a92d1800-75a1-11e9-84f4-6113eb96cf9b.png)
![product](https://user-images.githubusercontent.com/17230264/57618662-ab8f7200-75a1-11e9-8966-1d05674ed6cc.png)
![Second MO](https://user-images.githubusercontent.com/17230264/57618667-ae8a6280-75a1-11e9-815b-12be4a3ba083.png)
![update onhand qty](https://user-images.githubusercontent.com/17230264/57618669-af22f900-75a1-11e9-862c-79794bb87ed8.png)

**Comment by sswapnesh** [comment]
I am not sure but it seems it was handled in https://github.com/odoo/odoo/pull/32951 before few days.
Cc @pedrobaeza

**Comment by Yenthe666** [comment]
@tejasthakar333 could you update, test and confirm please?

**Comment by tejasthakar333** [comment]
@Yenthe666  I checked commit @sswapnesh mention in the previous comment. I can't find any configuration for **allow_zero_cost ** .
I already checked my issue in Odoo runbot that include this commit.

**Comment by sswapnesh** [comment]
Create new System Parameter and try again

![Screenshot - 2019-05-27T233837 312](https://user-images.githubusercontent.com/16624719/58434286-8ee25680-80d8-11e9-8207-ea7a7821dcc6.png)

**Comment by pedrobaeza** [comment]
Closing as answered

**Comment by tom10271** [comment]
Just in case someone wanted to copy the xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <record id="allow_zero_cost" model="ir.config_parameter">
            <field name="key">stock_account.allow_zero_cost</field>
            <field name="value">True</field>
        </record>
    </data>
</odoo>
```
