### ISSUE TITLE
POS Virtual Keyboard : Switch to AZERTY

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#33331]
**Impacted versions:**
12

**Steps to reproduce:**
Using POS interface

**Current behavior:**
When using keyboard, no way to switch it to AZERTY (default mode is QWERTY)

**Expected behavior:**
Possible to use correct disposition based on user language or on OS configuration

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/45974412/57621274-4c266780-758b-11e9-8560-460773313c8c.png)

**Comment by Yenthe666** [comment]
@pimodoo could you give us some insight/thoughts about this?

**Comment by pimodoo** [comment]
@gregory-moka @Yenthe666 Hello, it is currently not possible to choose the layout of the keyboard.

**Comment by Yenthe666** [comment]
@pimodoo nah we knew that. I'm rather curious if we can put this on the todo/wishlist or if you really don't want to support it.

**Comment by gregory-moka** [comment]
I will try to create a app to be able to switch between the 2 dispositions.
Where is located the keyboard_frame view ?

**Comment by switch87** [comment]
> I will try to create a app to be able to switch between the 2 dispositions.
> Where is located the keyboard_frame view ?

https://github.com/odoo/odoo/blob/988018a5baa1a10ee44eaeff3065bd8ce4859877/addons/point_of_sale/static/src/xml/pos.xml#L1616

**Comment by gregory-moka** [comment]
Hello,
I need help, please.
I'm looking for the calling method to get the cashier language at the POS load.
As I have this value, I'm able to display the keyboard in the cashier language.

**Comment by gregory-moka** [comment]
Pull request done : https://github.com/odoo/odoo/pull/34788

**Comment by pedrobaeza** [comment]
@switch87 is this going to be work on or should we close it?
