### ISSUE TITLE
[12.0] Search favorites not working in some tree views

### ISSUE THREAD

**Issue by Yousskill** [odoo/odoo#33342]
Impacted versions:
- Odoo 12.0+e

Steps to reproduce:
- Go to Accounting > Overview
- Click in a kanban record and it will take you to a tree view
- Save a filter in favorites as default
- step out the tree view and come back 

Current behavior:
- The tree view search Bar is empty

Expected behavior:
- I expect to see my default filter

**Comment by pedrobaeza** [comment]
This is expected as default filters are only expected to work through different menu items, not through clicks over kanban records.

Closing as won't fix due to technical restrictions.

**Comment by sswapnesh** [comment]
> Click in a kanban record and it will take you to a tree view
> Save a filter in favorites as default
Hello @Yousskill 
In order to see Default filters to be applied to you have to go to Invoice from Propper menu.

**Comment by Yousskill** [comment]
Thank you
