### ISSUE TITLE
[11.0] Anyone can unsubscribe followers

### ISSUE THREAD

**Issue by aitorbouzas** [odoo/odoo#33341]
Impacted versions:
11.0
I don't know if this a bug, or a expected behaviour.

Steps to reproduce:
Connect as an "Employee" permission user. Enter any document and start deleting followers.

Current behavior:
It let's you delete any follower if you have write permission in the document. For example: if you can write on a ```sale.order``` it will let you delete or modify any follower.

Expected behavior:
As of [this](
https://github.com/odoo/odoo/blob/11.0/addons/mail/security/mail_security.xml#L17) permission
It shouldn't let you edit other followers than yourself. I guess the problem is in [this two lines](https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_thread.py#L2057) where the permissions of write is checked in the parent and then the ```unlink``` is done through ```sudo()```

**Comment by sswapnesh** [comment]
Cc @odony

**Comment by pedrobaeza** [comment]
I would say this is a feature, not a bug, but it can be largely discussed.

**Comment by aitorbouzas** [comment]
I'm afraid that, as you say Pedro, this is a feature. The thing is that, in my opinion, the unlink shouldn't be done with sudo. This way you first check if the user can write on the parent model, then check if the user can edit/unlink the followers.
I kwow that sudo must be there for a good reason, but let's see if someone can throw some more light on this.

**Comment by Yenthe666** [comment]
@tde-banana-odoo can probably give us good feedback about the reason. :)

**Comment by tde-banana-odoo** [comment]
Hello,

Modifying followers is considered as modifying the document. Indeed if you are allowed to update a document it makes sense to be able to manage its followers. It is considered as part of the document. Communication history (chatter) is managed the same way. Rights on followers do not come from the model itself but from its "holder".

You should consider mail.followers model as technical. Security rules on mail.follower model are indeed a bit misleading. They indicate a behavior but the actual behavior is not completely related to the rules.

In master we are going to make this model completely technical. It means soon only administrators will have rights to modify followers entries directly. We are going to remove rights and rules on followers model. For standard users only the interface will allow to modify followers if they own rights on the related document.

Thanks,

**Comment by aitorbouzas** [comment]
Sweet! Thanks for clarifying this.

**Comment by Yenthe666** [comment]
Thanks a lot for the detailed feedback! Appreciate it.

**Comment by sswapnesh** [comment]
> In master we are going to make this model completely technical.

https://github.com/odoo/odoo/pull/31292/commits/bec1ede3cbc4f87431f1df6d8e6ee181890af4cc This one ?
