### ISSUE TITLE
Changing the invoice's sender mail

### ISSUE THREAD

**Issue by soward42** [odoo/odoo#33355]
Impacted versions: 12

Steps to reproduce: 
1. Create a template for your invoice
2. In email configuration change the sender field. (personally i did set it with object.company_id.email)
3. Create an invoice
4. Save it and validated it
5. Send it with send & print

Current behavior:
The mail is send but it's using the user email.

Expected behavior:
I expect that the mail is sent with the company email.

**Comment by pedrobaeza** [comment]
This is something that depends on your outgoing mail server that allows to have mail relay possibilities, being able to replace the sender by any inside the domain.

Closing as no Odoo issue, but mail environment condition.
