### ISSUE TITLE
Quotation/Sales order view doesn't show correctly product lines, optional products or other information tab

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#33357]
Impacted versions:
Odoo v12 modules:
* sales_management 12.0.1.0
* account 12.0.1.1
* purchase 12.0.1.2

Steps to reproduce:

1. Open Google Chrome or Firefox and go to Odoo.
2. Go to Sales module.
3. Create quotation.

or

1. Open Google Chrome or Firefox and go to Odoo.
2. Go to Accounting module.
3. Select Customers -> Invoices.
4. Create an invoice.

or

1. Open Google Chrome or Firefox and go to Odoo.
2. Go to Purchase module.
3. Create request for quotation.

Current behavior:
You can't see tabs "Order lines", "Optional products" or "Other information" properly:
![image](https://user-images.githubusercontent.com/40301417/57692648-e94ad400-764f-11e9-9d02-aa42cf3c0f4d.png)

Expected behavior:
To see tabs correctly like in Odoo v11:
![image](https://user-images.githubusercontent.com/40301417/57692696-16978200-7650-11e9-9e23-0e5b841efaa0.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something specific of the enterprise interface, so please report it at odoo.com/help. Closing here for not very relevant at community level.
