### ISSUE TITLE
[12.0] No company domain on sale_order_template_id

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#33366]
Impacted versions: 12.0

Steps to reproduce:
- On a multi-company context, set the common product catalog to false
- Create a quotation template on one company
- Change companies and create a quotation
- Try to change the quotation template

Current behavior:
- The quotation template created on the other company will show up, even if it doesn't allow you to set it (different company access rights)

Expected behavior:
- The template shouldn't show up at all, since it was created on a different company.

A domain can't be inserted validating the company since the record itself doesn't have a company context.

**Comment by sswapnesh** [comment]
Good to have this :+1:   (and awesome when it is aligned with Product Sharing config )

**Comment by Feyensv** [comment]
This will be done in v13 (where it is much more needed because of the changes in multi-company, and because it isn't a true bug in v12) with PR #34342 (WIP).
Thanks for the feedback :).

**Comment by dbo-odoo** [comment]
Can't be done in 12 since there is *no* company_id field on sale templates.
Done in 13.0 though.

I close this issue.
