### ISSUE TITLE
Private projects is visible to all Users or Managers 

### ISSUE THREAD

**Issue by Gumaa** [odoo/odoo#33378]
Impacted versions: 12.0

Steps to reproduce:
- Create projects with _Visible by following customers_ setting
![firefox_BWpfQOKvNu](https://user-images.githubusercontent.com/16503469/57760271-8282f480-76fb-11e9-9902-8dd718a76d10.png)
- Create user with Project Manager or Project User group and add him as follower to only one project
![firefox_2P8JGXTdVd](https://user-images.githubusercontent.com/16503469/57760338-9e869600-76fb-11e9-8baf-155a7f878421.png)
- Deactivate rules for "See all"
![firefox_30gQNr2I8Y](https://user-images.githubusercontent.com/16503469/57760599-35535280-76fc-11e9-8dc6-e02f3536e9ad.png)

Current behavior:
User with assigned group is able to see all the projects.

Expected behavior:
User should see only project that they are assigned to as followers.

**Comment by pedrobaeza** [comment]
This is not how it works. That option only applies to portal users, not regular users. The rest of the employees will see all projects, regardless of the rest.

You need to tweak record rules + adding some fields for controlling these.

Closing as no Odoo issue.
