### ISSUE TITLE
[Wishlist] web_tour: ability to prioritize tour on main screen

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#33405]
Impacted versions: All

Steps to reproduce:
Create any custom tour in Odoo that starts from the main apps screen.

Current behavior:
There is no way to set or make sure that your tour pops up as a first. As Odoo has multiple tours starting on the homepage (for different apps) and as only one is shown at a time there is no option for you 'push' your tour to the first.

Expected behavior:
The ability to make sure your tour comes first in line. Perhaps we can do it by adding a `sequence` field on the model `web_tour.tour` on which the JS framework priorities for the tours?

**Comment by Yenthe666** [comment]
@aab-odoo could you be to kind to give feedback/insight on this one? As far as I know there is not a single way to make sure some specific tour pops up first before all other tours on the main screen.

**Comment by Yenthe666** [comment]
@aab-odoo what do you think?

**Comment by aab-odoo** [comment]
Hello @Yenthe666 

This may be a good idea.

Regards

**Comment by Yenthe666** [comment]
Thanks a lot @aab-odoo, that is great to hear! Do you have any idea if it is in any task at Odoo itself?

**Comment by aab-odoo** [comment]
@odoongr

**Comment by Yenthe666** [comment]
@odoongr & @aab-odoo hi! any update?

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. Any news about this?

**Comment by aab-odoo** [comment]
@pedrobaeza @Yenthe666 A internal task has been created for this.

**Comment by Yenthe666** [comment]
Woo-hoo, nice. I'll close this ticket since there's an internal task now. It would be great to get a ping here once it's implemented. :)
