### ISSUE TITLE
[>=v8] Graph -> operator : min, max doesn't work anymore ?

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#3340]
Hi,

I am really interested about use these attribute on some graph on my module. 

Do you(openerp r&d team) plan to put them back available ??

Thanks..

**Comment by vak0160** [comment]
Any news of this feature? Since I really need it.

**Comment by ged-odoo** [comment]
sadly, this will definitely not make it before v9.  We are working on other projects right now.  No idea for later, I hope to implement it sometimes this summer.

**Comment by vak0160** [comment]
@ged-odoo Thanks for the follow up. I'll wait.

**Comment by Yenthe666** [comment]
@ged-odoo can you give an update on this one?

**Comment by Yenthe666** [comment]
@ged-odoo can you give an update on this one?

**Comment by pedrobaeza** [comment]
I think we can close this as no answer from Géry, no more interest in original issuer, and a lot of improvements have arrived in 11.0, 12.0 and 13.0

**Comment by ged-odoo** [comment]
@pedrobaeza for your information, I learned this week that we will have a new BI team at odoo... I think that we can expect a lot of improvements for v14 :)

**Comment by pedrobaeza** [comment]
Wow, that's great. Let's go for a full-fledged BI!
