### ISSUE TITLE
URGENT: REgression - Invalid Date

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#33408]
Impacted versions: 12.0

Steps to reproduce:
In a latest build with this PR #33362 and custom language settings for date as shown in screenshot. Just switch the %m and %d.
Create a sales order

Current behavior:
Invalid date
Invalid date

error boxes x 2

Expected behavior:
no errors

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5093264/57817025-a6b10500-77d1-11e9-8ebb-c20a28a41beb.png)
![image](https://user-images.githubusercontent.com/5093264/57817232-89c90180-77d2-11e9-82dc-b8e515e2f7ac.png)

**Comment by gdgellatly** [comment]
opw-1998971

**Comment by Yenthe666** [comment]
Haven't looked far but probably related to https://github.com/odoo/odoo/commit/9ed9710b2b9ad685f4f09e42930e212d3cec71e5 ?
@simongoffin has introduced this fix two weeks ago.
