### ISSUE TITLE
[8.0/Master] Firefox-specific bug with website_sale.js and input field on order line on website_sale.cart page.

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#3342]
<h2>Impacted versions:</h2>

<p>Odoo 8.0 and above</p>
<p>Latest stable version of Firefox - 33.0.1 and Aurora (I have not tested earlier versions yet)</p>

<h2>Steps to reproduce:</h2>

<ul class="task-list">
<li>Create a user with the only the following access rights: <br/>
<img src="https://cloud.githubusercontent.com/assets/2337666/4820064/04c13bfa-5f0f-11e4-8a22-0478f5387707.png"/>
</li>
<li>Logout from admin and login as the new user.</li>
<li>Add 3 products with varying quantities (for my example i've used 30, 25, and 2): <br/>
<img src="https://cloud.githubusercontent.com/assets/2337666/4820071/13d28aea-5f0f-11e4-8558-e31796e7b0f3.jpg"/>

</li>
<li>Remove the product in the middle by adding a 0 value to the input box or by clicking the minus arrow on the input field until you reach 0 and the product is removed from the cart 
<img src="https://cloud.githubusercontent.com/assets/2337666/4820079/2e7d8390-5f0f-11e4-87ad-cb0300386895.jpg"/>
</li>
</ul>

<h2>Current behaviour:</h2>

<ul class="task-list">
<li>The product underneath the one you have removed has carried the value of the deleted line (ie. 0), however the actual cart amount is correct (ie. the 0 seems to be there, but the actual value on the input field is somehow correct). A page refresh does not resolve this issue, however if you go back to another page (eg. /shop) and then click the shopping cart icon (header nav) the 0 quantity is back to the correct value for that product (in my case 2 units): <br/>
<br/>
<img src="https://cloud.githubusercontent.com/assets/2337666/4820086/3763aca0-5f0f-11e4-9a62-0fe9c7ad32f4.jpg"/>
</li>
</ul>

<h2>Expected behaviour:</h2>

<ul class="task-list">
<li>After removing a product from the cart the product underneath the removed item should have the correct value (in my example 2 units) rather than inheriting the 0 from the deleted line.</li>
</ul>

<h2>Preferred behaviour:</h2>

<h3>In website_sale.js:</h3>

<ul class="task-list">
<li>Refresh all fields (even custom order lines) on cart page input field change:<br/>
eg. <span class="amount" t-field="line.price_subtotal" t-field-options="{                                      &quot;widget&quot;: &quot;monetary&quot;,                                      &quot;display_currency&quot;: &quot;user_id.partner_id.property_product_pricelist.currency_id&quot;                                  }"/> for order line total. This could be achieved by adding a class to the custom field to make sure it is refreshed just like the core values.</li>
</ul>

**Comment by odony** [comment]
@JKE-be Can you have a look, please?

**Comment by lukebranch** [comment]
@odony ,

Thanks for taking a look at this.

**Comment by lukebranch** [comment]
@JKE-be ,

thanks!
