### ISSUE TITLE
[11.0] l10n_es for Cooperatives

### ISSUE THREAD

**Issue by danypr92** [odoo/odoo#33424]
Hi!

We are looking for the chart of accounts and other required accounting stuff for cooperatives related to the Spanish legislation. 

We are following the @acysos repository with the content that we need, but they told that are migrating it to Odoo 11.0 and will open a PR to the official Odoo repository: https://github.com/acysos/odoo-addons/tree/11.0/l10n_es_coop

Any knows another repository with this content updated to odoo 11.0?

Thanks!

**Comment by pedrobaeza** [comment]
This is not the best place for this kind of questions, as this is for issues with current code.

Any way, the answer is short: there isn't any known.

**Comment by danypr92** [comment]
ok. thanks.
