### ISSUE TITLE
I want save the state names in the students table

### ISSUE THREAD

**Issue by mady143** [odoo/odoo#33433]
Hi every one , i need a help from you guys i am working odoo created a module called teachers in that i created a form with the following fileds 
--name
--age
--dob
--gender
--email
--blood group
--country -->this country is coming from res_country table followed by a many2one relation in my model as well as state 
--state

now my problem is when i selecting the country from my countries drop down should displays the particular states relates to that country

and now i want add a new state apart from the states present in res_country_states table (states table) by adding the new state directly into my teachers_teachers table as name of the state  not in the states table 

can any one help me in this ....

**my model:**

from odoo import models, fields, api

class teachers(models.Model):
    _name  = 'teachers.teachers'

    name   = fields.Char(string='Name', required = True)
    age    = fields.Integer(string='Age')
    email  = fields.Char(string='Email')
    phone  = fields.Char(string='Mobile Number')
    gender = fields.Selection([('male', 'Male'), ('female', 'Female'), ('others', 'Others')], string='Gender')
    dob    = fields.Date(string='Date of Birth')
    blood_group = fields.Selection(
    	[('A+', 'A+ve'), ('B+', 'B+ve'), ('O+', 'O+ve'), ('AB+', 'AB+ve'),
     	('A-', 'A-ve'), ('B-', 'B-ve'), ('O-', 'O-ve'), ('AB-', 'AB-ve')],
    	string='Blood Group')
    country_id = fields.Many2one('res.country',string='Country')
    state   = fields.Many2one('res.country.state',string='State')

    @api.onchange('country_id')
    def _onchange_country_id(self):
        if self.country_id:
            return {'domain': {'state': [('country_id', '=', self.country_id.id)]}}
        else:
            return {'domain': {'state': []}}

**my view:**

<odoo>
  <data>
    
    
    <record model="ir.ui.view" id="teachers.list">
      <field name="name">Teachers list</field>
      <field name="model">teachers.teachers</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="email"/>
          <field name="phone"/>
          <field name="gender"/>
          <field name="blood_group"/>
        </tree>
      </field>
    </record>
    

    
    
    <record model="ir.actions.act_window" id="teachers.action_window">
      <field name="name">Teachers window</field>
      <field name="res_model">teachers.teachers</field>
      <field name="view_mode">tree,form</field>
    </record>
    
    <record id="teacher_free_view" model="ir.ui.view">

          <field name="name">Teacher Form</field>

          <field name="model">teachers.teachers</field>
          
          <field name="arch" type="xml">

              <form string="Teacher">

                  <sheet>
                      <div class="oe_title">
                          <h3>
                              <field name="name"/>
                          </h3>
                      </div>                    
                      <group>
                         <group>
                              <field name="age"/>
                              <field name="gender"/>
                              <field name="email" widget = "email"/>
                              <field name="country_id"/>

                          </group>
                          <group>
                              <field name="dob"/>
                              <field name="phone"/>
                              <field name="blood_group"/>
                              <field name="state" options="{'no_create': True,'readonly':True}"/>
                          </group>
                      </group>
                   </sheet>
              </form>
          </field>
        </record>

    
    
    <menuitem name="teachers" id="teachers.menu_root"/>
    
    
    
    <menuitem name="Menu 1" id="teachers.menu_1" parent="teachers.menu_root"/>
    <menuitem name="Menu 2" id="teachers.menu_2" parent="teachers.menu_root"/>
    
    
    
    <menuitem name="List" id="teachers.menu_1_list" parent="teachers.menu_1"
              action="teachers.action_window"/>
    
  </data>
</odoo>

Thanks in advance...
Happy codding....

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by mady143** [comment]
hi @pedrobaeza  actually i couldn't understand your reply i ma new to odoo so can you explain me clearly what i have to do for my  issue that i have posted 

Thanks in Advance...
Happy Codding

**Comment by pedrobaeza** [comment]
This is not the place for doing questions, sorry.

**Comment by Yenthe666** [comment]
Ask it on the help forums, there are plenty of people who can help you there :)
