### ISSUE TITLE
Purchase order cancelling or deletion does not handle associated procurements correctly

### ISSUE THREAD

**Issue by leio** [odoo/odoo#3344]
If a purchase.order.line is deleted from a purchase.order, then the associated procurement is properly cancelled via addons/purchase/purchase.py: class purchase_order_line unlink method - it finds all procurements where purchase_line_id is the relevant one that is deleted and it calls the cancel method nicely on the relevant procurement before the associated foreign key is deleted. This way when a new PO should happen for the same product (e.g to satisfy an orderpoint), it actually creates the PO draft again on a scheduler, etc. It is explicitly deleted, so it should implicitly delete/cancel the implicitly created procurement orders as well, which it does, so all is good in this case.

But none of this is done when either the whole PO is cancelled or when the PO draft is outright deleted.
For some reason it seems purchase.order.line unlink isn't called when purchase.order unlink is, or it somehow doesn't trigger the procurement cancelling parts. It really should, so the user doesn't need to care about implicitly created objects that are sort of like implementation specific technical details (even though procurements are useful outside POs as well, but they are implicitly and automatically created here).
Also when the whole PO is cancelled, the procurement cancellation should run as well for the order lines, as if the whole PO is cancelled, then obviously the order lines should be cancelled too, which in this case takes the form of procurement cancellation.

This makes handling of MRP usages where POs for raw materials are grouped up based on types and then sent out to different suppliers severely inconvenient, as various technical details bleed through and normal purchase managers need to worry about remembering to manually cancel implicitly created different objects than purchase orders.

**Comment by jco-odoo** [comment]
I don't see it as logical that it would cancel the procurement.  Suppose your product is MTO (not through the orderpoints), then it will cancel the procurement without the sale order being notified.  It is logical to check the Procurements in Exception in that case.  

Cancelling a delivery order is different as it will continue to cancel everything before automatically.  (if the cancel and split...)

**Comment by leio** [comment]
The point is the inconsistency. If you cancel the PO lines one by one before cancelling the whole thing, it does cancel the procurements; logically cancelling the whole PO should act as if each line was cancelled as well - but it does not.
If cancelling the whole PO doesn't do that automatically (leaving those in exception), then doing it one by one should act the same, and not cancel them. Which is also very inconvenient, but at least wouldn't surprisingly act differently.

The code should logically first cancel each line, then cancel the whole PO, then it would work as we desire, unless per-line cancelling/deleting behaviour is changed as well.

And not just cancelling of PO, I also said it doesn't work as expected when outright deleting (unlink) of the draft PO. It does not call unlink on the order lines, which is wrong.

**Comment by vahursuvi** [comment]
I am agree with leio and aliomattux
Its not normal, that Canceling the whole PO - all lines going to Exeption.

**Comment by dportenlanger** [comment]
If v7 recreates the draft PO, why would we not expect identical logic for v8.  This can potentially lead to a missed purchase, delayed manufacturing and in the end, a late shipment, an unhappy customer and lost revenue.

**Comment by aliomattux** [comment]
I don't understand how someone could go through this and logically conclude that there is not a problem. Sure the procurement goes into exception, I just got a call today from a business owner that cannot understand why the system is not generating new procurements.

Not every business user is going to be able to manage purchase orders and procurements. In my opinion managing procurements is sort of silly and adds an extra layer of complexity. A business user wants to manage stock levels and purchase orders, Not procurements. Study standard software and see the difference

**Comment by aliomattux** [comment]
@dportenlanger Odoo is indirectly implying that you should login to Odoo every few hours and click on exception procurements to see what manual work needs to be done or fixes so the system works the way you would expect it to.

We should hire a procurement manager thats only job is to go to the procurement menu and see what ugly exceptions appear, and only in this menu because the information isn't available anywhere else

**Comment by spadae22** [comment]
@dportenlanger YES, they not implying, the are saying it. I fought this battle with v7 to v8. They told me it was an enhancement? I add back the code from v7. Since the exceptions were a joke since you had to search to find the issue. At least v7 gave the reason. I fought a simliar issue: https://github.com/odoo/odoo/issues/2814

**Comment by aliomattux** [comment]
If you have a proposed patch that will solve this issue please post a link to it here. If not I will need to create one. If you have a patch, I can put it into a module that others can use. It is often that Odoo reject functional changes even if they are seemingly common sense.

**Comment by aliomattux** [comment]
I dont think the referenced issue is related. The issue reported here is that if you cancel a receipt the procurements are placed in exception instead of being canceled. The issue you referenced is about manufacturing

**Comment by spadae22** [comment]
Well, same issue with exceptions, unless you check them all day, or in live environment, its too late. So the example for a Buy or Manufacture Product that is MTS, and reorder rule is not created, Purchasing and/or Manufacturing will never know. At the end of the day, we have the same issue:
```If v7 recreates the draft PO, why would we not expect identical logic for v8. This can potentially lead to a missed purchase, delayed manufacturing and in the end, a late shipment, an unhappy customer and lost revenue.```

I really gave up on asking to "improve" logical issues in v8.

**Comment by dportenlanger** [comment]
I have a module to fix it on enterprise.


Sent from Outlook Mobile






On Mon, Feb 29, 2016 at 1:26 PM -0800, "E.R. Spada II" <notifications@github.com> wrote:





Well, same issue with exceptions, unless you check them all day, or in live environment, its too late. So the example for a Buy or Manufacture Product that is MTS, and reorder rule is not created, Purchasing and/or Manufacturing will never know. At the end of the day, we have the same issue:
```If v7 recreates the draft PO, why would we not expect identical logic for v8. This can potentially lead to a missed purchase, delayed manufacturing and in the end, a late shipment, an unhappy customer and lost revenue.```

I really gave up on asking to "improve" logical issues in v8.





---

**Comment by spadae22** [comment]
+1

**Comment by aliomattux** [comment]
I dont know about some "Enterprise" module, but I put together something quickly that does it. It still needs work but proves the concept.

https://github.com/aliomattux/purchase_procurement_cancel_work

All I did was literally a single word change and it works....
