### ISSUE TITLE
Bug on fields "Delay Field" and "Duration Unit" when creating a Gantt view on Odoo Studio

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#33449]
**Impacted versions:**
11.0

**Steps to reproduce:**

- Go to this odoo/enterprise runbot: [http://521119-11-0-adc60c.runbot11.odoo.com/?db=521119-11-0-adc60c-all](http://521119-11-0-adc60c.runbot11.odoo.com/?db=521119-11-0-adc60c-all)
- Go to the "Attendances" app
- Go to "Manage Attendances" > "Attendances"
- Click on Odoo Studio
- Create a Gantt view and choose whatever date field you want
- Choose a value in the "Delay Field" or "Duration Unit" dropdown
- An error occurs

**Current behavior:**
The following error toast appears:

> This operation caused an error, probably because a xpath was broken.

**Expected behavior:**
No error should occur.

**Video/Screenshot link (optional):**

![Error occured when I select one of the field value above](https://i.ibb.co/mCYvXp6/Capture-d-cran-de-2019-05-16-17-05-29.png)

**Comment by pedrobaeza** [comment]
As this is something for enterprise, please report it in odoo.com/help.

**Comment by tivisse** [comment]
Hi @khalyomede 

As @pedrobaeza proposed, you should open a support ticket for this kind of issues.

Thanks for the feedback anyway,

Yannick.

**Comment by Julian-Dumitrascu** [comment]
You display this error when one chooses the model to link through a many2many field. 
We cannot use a computer program without such a basic feature.
Let's agree on how to make Odoo work!
It did not work any time we've tried since 2016.
