### ISSUE TITLE
Pos Fiscal Position Issue

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#33448]
Impacted versions: Odoo-12.0

Steps to reproduce: 
- Configure fiscal position in Pos and replace accounts.
- After create the pos order, close and validate session.
- After check the Journal entries but no replace the accounts.

Current behavior: 
Not able to replace the account based on fiscal position.
Only taxes can replace.
Odoo Link; http://521272-12-0-39e05c.runbot15.odoo.com/pos/web/?debug=true
Expected behavior:
Also need to replace the account same as taxes can replace based on fiscal position.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@switch87 it sounds to me that this is handled in master. Isn't it?

**Comment by sswapnesh** [comment]
Seems like this was Handled in https://github.com/odoo/odoo/pull/29433

**Comment by pedrobaeza** [comment]
Yeah, that was what I remember.

Then, the answer is that this is not going to be fixed on 12.0, but solved on master.

**Comment by switch87** [comment]
@yenthe666 @pedrobaeza @sswapnesh thank you for your help and research 👍
