### ISSUE TITLE
Postgresql & psycopg2 ports does not match

### ISSUE THREAD

**Issue by ghs-raqeem** [odoo/odoo#33453]
Impacted versions: 12.0

Steps to reproduce:
Postgresql listens on port 5433, The reason is a previous installation on the same machine, so it listens on 5433 instead of 5432. While the psycopg2 connects to 5432 by default; so connection do not initiate.

Current behavior:
odoo could not connect to postgresql and could not create any database nor install modules to it. Port could not be changed in the postgresql.conf file since it is used by another service

Expected behavior:
connecting to the postgresql on the port it uses.

Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
So change the psycopg2 port.

**Comment by Yenthe666** [comment]
Yeah this is out of the scope of Odoo and is a deployment/configuration issue.
