### ISSUE TITLE
[12.0] Monetary widget not applied on website_sale_delivery checkout

### ISSUE THREAD

**Issue by jtmoniker** [odoo/odoo#33451]
Impacted versions:

12.0

Steps to reproduce:

1. Go to yourdomain/shop and add a product to your cart.
2. Go through the checkout process, once you reach /shop/payment route, look at delivery methods.

Current behavior:

shipping methods are being displayed as a non-monetary float (ex. 10.0)

Expected behavior:

Shipping methods should be a monetary field (ex. $10.00)

Video/Screenshot link (optional):
![Screen Shot 2019-05-16 at 7 00 17 PM](https://user-images.githubusercontent.com/38473911/57898235-0547a480-780d-11e9-81af-0343b1e9a91a.png)

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by rdeodoo** [comment]
Thank you for reporting the issue, fix is coming
