### ISSUE TITLE
odoo could not access

### ISSUE THREAD

**Issue by gg2003love** [odoo/odoo#33477]
Impacted versions:  odoo12 for windows

expert,

i installed the odoo12 latest in windows server 2012r. But when i started to access the localhost:8069 with chrome, the result was could not connected and open the web page. My firewall was closed. I installed with default all in one and the procedure was not error.

   Please give me some guide. Thank you!

**Comment by Rochbetta** [comment]
Hi, I have the same problem. Please help!

![image](https://user-images.githubusercontent.com/93293909/152629824-30fa1266-7c10-4fdd-90a8-5d640d5aefd7.png)

**Comment by lathama** [comment]
@gg2003love is this still an issue today? Can you close this issue?
