### ISSUE TITLE
How to create a text filed  based on the selection value from the drop down list

### ISSUE THREAD

**Issue by mady143** [odoo/odoo#33486]
Hi Everyone,

Actual i am having a States table in that i added the "Others" as one of the value when i was select the others immediately an empty text field appears bellow and when ever i added a new into that the text filed it must be save into the db in odoo

Can any one help me ...

Thanks in Advance...

Happy Codding...

**Comment by Yenthe666** [comment]
Hi @mady143,

The Github issue tracker is only used for bugs in official code, it is not the place to ask custom development questions.
You can ask these on the official help forums at https://www.odoo.com/forum/help-1

Regards,
Yenthe
