### ISSUE TITLE
[12.0] view_users_form does not generate strings in English

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#33482]
**Impacted versions:**
12.0

**Steps to reproduce:**
When Creating Database
1. Create a Database and select a language other than English
2. Upgrade the `base` module

When Disable English Language
1. Changing all users' language to language other than English
2. Upgrade the `base` module

The main cause of the behaviour is the language setting of the `System` user, if you change the language setting of that user and upgrade the any modules that affect the `res.group`, the issue can be reproduced.

**Current behavior:**
`base.view_users_form` is generated, however the "strings" inside the form view is in other language. Therefore when user switches to other language, the strings will not be translated.

**Expected behavior:**
`base.view_users_form` should always be generated in English.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/27185427/57996207-b47bc880-7af8-11e9-86fa-ba0e81b42811.png)

![image](https://user-images.githubusercontent.com/27185427/57996234-d2e1c400-7af8-11e9-82fa-9ffe5057e25a.png)

**Comment by pedrobaeza** [comment]
Are you by chance using `--dev` parameter? If so, that can be the root cause.

**Comment by TimLai125** [comment]
Hi @pedrobaeza , I don't think so. I can reproduce  the issue by changing the language of `__system__` user manually in both Odoo bot and my customer's environment.

**Comment by pedrobaeza** [comment]
OK, let's hear comments from @mart-e. Maybe `__system__` language is not expected to be changed.

**Comment by mart-e** [comment]
Hi,

Thanks for the report, this happens only for the specific user view `base.user_groups_view`.
The translations seems actually on purpose, cf the following comment, introduced at #3921

https://github.com/odoo/odoo/blob/90dec44a286c69f31b3fbcf3302f16fdf90d4a5d/odoo/addons/base/models/res_users.py#L995-L998

The fact that it is not translated at database install is a side effect (the code is executed before the translations are loaded in database).

I don't think this is a good behaviour, I will see if we can change it.
