### ISSUE TITLE
[7.0] Rounding problem with _compute_qty in product_uom

### ISSUE THREAD

**Issue by etsinko** [odoo/odoo#3350]
This is one more bug report for rounding problem that happens in _compute_qty(). This error happens when from_uom_id = to_uom_id. 
Instead of returning the same quantity as is passed to the function, _compute_qty converts the quanity to the quantity in the reference UoM and then converts it back to the original UoM introducing rounding errors in the process.

Steps to reproduce:
1. Create a fresh database with demo data
2. Install following modules: stock, purchase
3. Enable Technical Features, and Manage Units Of Measures for admin user
4. Create a new UoM:
   name: ft
   category: Length
   type: Smaller
   Factor: 3.28084
5. Create a new product:
   Name: Wire
   UoM: ft
   In Procurements Tab add a supplier:
   Supplier: AsusTek
   Minimal Quantity 1000.0
6. In Purchases Create a new Quation:
   Supplier: AsusTek
   Add a new PO Line:
   Product: Wire
   Notice how Quantity changes to 1000.010
   If you try to change it to 1000, the OpenERP will give you a warning and change it back to 1000.010

A simple fix would be checking if from_uom == to_uom, and returning the original qty if they are equal.

**Comment by Yenthe666** [comment]
Hi @etsinko,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
