### ISSUE TITLE
[12.0] POS refund+lot -> sign error in stock.move.line

### ISSUE THREAD

**Issue by mbaena** [odoo/odoo#33512]
https://github.com/odoo/odoo/blob/659ff0da13951d0b940c24a070a4a7e51b0897bb/addons/point_of_sale/models/pos_order.py#L870

qty should be positive:

```
qty = abs(pos_pack_lot.pos_order_line_id.qty)
```

**Comment by Yenthe666** [comment]
@switch87 another one for you

**Comment by switch87** [comment]
@mbaena can you motivate this with an example where it gives errors or wrong results? I tested a refund in the PoS and it works.

**Comment by switch87** [comment]
@mbaena  never mind my previous answer. I could reproduce the error.
