### ISSUE TITLE
Odoo 11 JS load_fields problems with browsers

### ISSUE THREAD

**Issue by Floaterz** [odoo/odoo#33536]
**Impacted versions:** Odoo 11

**Steps to reproduce:**
- Create a new field in inherited class "product.template" named product_type ( Selection )
- Create JS file inheriting from POS.
- Try to load new field: 
-- var models = require('point_of_sale.models');
-- models.load_fields("product.product", "product_type");

**Current behavior:**
Using 2 browsers to test this ( Firefox & Chrome ). 
On Firefox, the new field appears
On Chrome, the new field does not appear 

**Expected behavior:**
The field to appear, regardless of the browser used

**Using Firefox:**
![using_firefox](https://user-images.githubusercontent.com/27363209/58102274-eebc9700-7bd8-11e9-9ad2-87f9668821a8.png)

**Using Chrome:**
![using_chrome](https://user-images.githubusercontent.com/27363209/58102275-eebc9700-7bd8-11e9-8721-93196532e289.png)

**Comment by pedrobaeza** [comment]
Sorry, but this is not an Odoo fault, but custom development issue.

You should make your development questions on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
