### ISSUE TITLE
[12.0] Attachment uploaded by non admins get incorrect mimtype

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#33543]
Impacted versions:

12.0

Steps to reproduce:

Upload an XLSX attachment as admin
Upload the same file as demo user

Current behavior:

The Upload for the admin works as expected and the attachment has the right mimetype.
For the demo user the mimetype for the attachment, which was created from the same file is set to text/plain.

Expected behavior:

Both admin and demo user should be able to create an attachment with the correct mimetype.

Video/Screenshot link (optional):

As far as I was able to determine the reason this seems to be done on purpose. Therefore I create this issue and not a pull request. I don't understand the reason behind this method to force a "wrong" mimetype. If this is really not the desired behaviour I can create a pull request. Otherwise I would be grateful for an explanation for this behavior.

Method: https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_attachment.py#L260

![image](https://user-images.githubusercontent.com/4851083/58121433-c009e500-7c07-11e9-93d0-e787a6e259e6.png)

![image](https://user-images.githubusercontent.com/4851083/58121486-db74f000-7c07-11e9-8e60-e361c3c3ef2e.png)

![image](https://user-images.githubusercontent.com/4851083/58121524-ef205680-7c07-11e9-8ae9-5c38860466c6.png)

Screenshots (https://demo.odoo.com/)

**Comment by pedrobaeza** [comment]
This is a known problem. A possible fix is in #31849

@odony do you have an idea when any of the possible fixes will be merged for solving this?

**Comment by ivantodorovich** [comment]
Any updates on this issue?
