### ISSUE TITLE
Create Purchase order fail: index row size 3352 exceeds maximum 2712 for index

### ISSUE THREAD

**Issue by chupavn** [odoo/odoo#33549]
Impacted versions: 11, 12

Steps to reproduce: Create PO with  long value in Description field and click Confirm Order
Current behavior: Show odoo server error

Expected behavior: Create PO successful

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31997780/58142756-8ae6ac80-7c72-11e9-8028-da7d92304a60.png)

**Comment by Elkasitu** [comment]
Can you reproduce on [runbot](http://runbot.odoo.com/runbot)? Also how much is "long value"? I tried in a 11.0 runbot with ~20 paragraphs of Lorem ipsum and didn't run into any issues.

What's more, I checked the code and that field does not seem to have an index by default

**Comment by chupavn** [comment]
In code, name of  "stock.move" have index 
![image](https://user-images.githubusercontent.com/31997780/58160230-41b14f80-7ca8-11e9-9e12-c7b7377e16f6.png)

Any help?

**Comment by chupavn** [comment]
If you get self.name[:2000] then server error not show, but name of "stock.move" will be lack of information

**Comment by Yenthe666** [comment]
@chupavn something very similar was actually done on the communication size of payments too at https://github.com/odoo/odoo/commit/c545783b95b15f65a9798003b614f75685dc434e

**Comment by Elkasitu** [comment]
Unfortunately this is the best we can do for a stable version, for master it should be checked with the logistics team to see whether the index on that specific char field is necessary or not
