### ISSUE TITLE
Emailed invoices created in wrong company

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#33553]
Impacted versions:

Steps to reproduce:
Good luck trying this on runbot.
However, have a purchase journal in company A with an email alias.
As admin user (2) set your company to unrelated Company B
Email invoice from an email address not in the system, to email alias (in this case it is routed via a catchall)

Current behavior:
Invoice will be created in Company B.

Logs show correct route match on alias for journal in company A
I don't really understand why user id 2 is selected for processing these messages.
But then due to record rules, I think the search for the matching journal fails due to record rules here.
https://github.com/odoo/odoo/blob/90dec44a286c69f31b3fbcf3302f16fdf90d4a5d/addons/account/models/account_invoice.py#L702-L704

Expected behavior:
Create invoice in correct company

OPW to follow
Video/Screenshot link (optional):

**Comment by gdgellatly** [comment]
opw-2001179

**Comment by gdgellatly** [comment]
I'm kind of torn on whether this is an issue now or not. The workaround seems to be you need to assign a single company user to the alias, or no user, but the problem is you never manually create the alias, you just add an email to the journal and Odoo goes and gets it wrong automatically for you in multicompany.

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed aliases do not support multi company by themselves, and the company will most likely come from the user that creates the record (probably root or admin in case of mailgateway, depending on the version).

However in stable you have a workaround that is giving creation values in the alias itself using alias_defaults and giving it a company_id value. This is rather technical but feasible. In stable we will not consider this behavior as a bug, even if I understand it might be annoying.

In master we are working on improving multi company support of aliases and mail gateway. In stable versions some tweaking is necessary but is doable :) .

Thanks,

**Comment by Yenthe666** [comment]
So in short: you're working on it and the upcoming V14 will add better support for this? If that is the case then I believe we can close this off as you guys manage the internal task for this.

**Comment by tde-banana-odoo** [comment]
Indeed, we are trying to make some spec about company-based alias domain / aliases. It is quite complicated so currently nothing to show :) .
