### ISSUE TITLE
I can not select vehicles from combobox for new contracts

### ISSUE THREAD

**Issue by Mephysto666** [odoo/odoo#33565]
Impacted versions: 12

Steps to reproduce: Create more than one vehicle and try to create a new contract from Vehilces application menù, not from specific vehicle

Current behavior: When I try to create a new vehicle contract, I can not select any vehicle from combobox (it is empty, but I have four vehicles)

Expected behavior: I can select vehicles from relative combobox

Video/Screenshot link (optional):
![Capture](https://user-images.githubusercontent.com/3337127/58167557-7c0cf380-7c8c-11e9-9fad-f2d67bd3ca03.JPG)

Very kind regards.

Meph

**Comment by rdc02271** [comment]
Hello,

Did you specify a driver on the Vehicle form?
 I am able to replicate your situation if I don't specify a driver on the Vehicle form.

However, I am a newbie to Odoo so I don't know if this is a bug or not.

**Comment by pedrobaeza** [comment]
That's indeed the problem.

Closing as no issue.
