### ISSUE TITLE
POS Odoo11- New versión chrome

### ISSUE THREAD

**Issue by carlositurri** [odoo/odoo#33587]
Hello,
In the latest version of chrome, the odoo POS 11, when selecting a product several times either manual or barcode, the quantity of the product does not increase only, instead it adds several lines of the same product. Anyone know of an update of Odoo or Fix to avoid problems with the latest version of Chrome?

**Comment by pedrobaeza** [comment]
@carlositurri can you specify the exact Chrome version? Are you able to reproduce this in runbot?

@switch87 are you aware of this?

**Comment by carlositurri** [comment]
My version of chrome is Version 74.0.3729.169 (Official Build) (64 bits) before I worked correctly with Version 68.0.34 thanks @pedrobaeza

**Comment by switch87** [comment]
@carlositurri I tested with the exact same chrome version as you but didn't notice any strange behaviour. maybe there wend something wrong in the browser cache with updating? you could try ctrl+F5 for a forced reload of the cache for odoo.

**Comment by carlositurri** [comment]
@switch87 Thank you for your response, I did what you recommended but without success.
This problem is replicated in all my users who use the latest version of chrome (Version 74.0.3729.169), they select more than once a product to sell in the POS and not only adds the quantity of the product, but also adds new ones lines what is not its correct functioning, I'm using odoo11.

I attach the image of how is the operation
![image](https://user-images.githubusercontent.com/11946302/58256715-79b6a200-7d3d-11e9-9d9c-e3a1c5d5b6e1.png)

**Comment by pedrobaeza** [comment]
@carlositurri please try to reproduce the problem in runbot (http://runbot.odoo.com/runbot - admin/admin)?
If not reproducible, then this is something in your end (outdated code, custom modifications...).

**Comment by carlositurri** [comment]
@pedrobaeza thank you, I try to login to odoo runbot admin / admin but it tells me Wrong login / password can help me enter and perform the test?
I am looking forward to your response

**Comment by pedrobaeza** [comment]
A not respectful person has changed the admin password. Please try in an older build in the same line.

**Comment by carlositurri** [comment]
@pedrobaeza thank you very much, the problem was solved when updating my odoo with git pull, I appreciate your time, thanks
