### ISSUE TITLE
Leaves module. Activity default assignee user

### ISSUE THREAD

**Issue by GeorgeIvlev** [odoo/odoo#33594]
Hi! I have a question about "Leaves" module. When i create a leave in calendar by any user the leave itself has an "Leaves Approval for OdooBot" in "Planned activities" section and our HR does not retrieve any email notification until i press edit button in "Planned activities" section and manually change "Assigned to" field from OdooBot to our HR. So question is, can i somehow change the default assignee user for activity type? Thanks! And sorry if my question does not corresponds to issue creation rules...

![leave_q](https://user-images.githubusercontent.com/12997597/58209130-1f8ef000-7cef-11e9-90f7-0566dc673842.png)
![leave_q2](https://user-images.githubusercontent.com/12997597/58209134-20c01d00-7cef-11e9-903e-32dfd15aeaa3.png)

**Comment by intero-chz** [comment]
That looks like a `sudo()` problem:

https://github.com/odoo/odoo/blob/086b9ad879664448d8a4c9102b2cf158def04444/addons/hr_holidays/models/hr_leave.py#L789-L819

**Comment by GeorgeIvlev** [comment]
@intero-chz thanks! So i see only one way, rewrite this section of code to automatically assignee to our HR.

**Comment by intero-chz** [comment]
@GeorgeIvlev yes and no, it should be fixed in Odoo ;-)

I don't know why this was implemented with `sudo`, but it obviously has something to do with access rules. That was always a pain in the ass in the holiday app.

**Comment by Yenthe666** [comment]
@RomainLibert for your interest

**Comment by sswapnesh** [comment]
Hello @GeorgeIvlev 

> So i see only one way, rewrite this section of code to automatically assignee to our HR user.

For now you can Prevent this by setting Correct Manager on Leave/ or Employee/Department's manager. (If this suits your workflow) OR Just edit activity and set correct user.


Hello @intero-chz  

> I don't know why this was implemented with sudo, but it obviously has something to do with access rules. 

See commit message on https://github.com/odoo/odoo/commit/21430a4d027f9b3e5a83b078477a77bdb17e61a0


Cc: @tbe-odoo based on https://github.com/odoo/odoo/commit/21430a4d027f9b3e5a83b078477a77bdb17e61a0

**Comment by GeorgeIvlev** [comment]
@sswapnesh Thanks for your help!

**Comment by intero-chz** [comment]
@sswapnesh interesting commit (21430a4), but why should someone from the "wrong" company be allowed to confirm/validate a leave. IMO that is wrong, because it's bypassing the multi company rule...

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/33804

**Comment by sswapnesh** [comment]
This has been fixed in 691dc424a1d04c7ea4fb87663b17922efd5bcaf5
