### ISSUE TITLE
product and components in delivery order

### ISSUE THREAD

**Issue by wredwan** [odoo/odoo#3359]
Hi Guys,
I think if we can show the parent product above it's components ,it will be more useful. So How can i do it?

**Comment by Yenthe666** [comment]
Hi @wredwan ,

Thank you for your suggestion and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some. You could have done this with custom development.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).

Regards,
Yenthe
