### ISSUE TITLE
odoo not starting

### ISSUE THREAD

**Issue by vinayakybhatt** [odoo/odoo#33600]
Impacted versions:
odoo12

i was following this document for downloading odoo12 on ubuntu 
https://www.getopenerp.com/install-odoo-12-on-ubuntu-18-04/
i reached upto 13th step and got an error on doing ./odoo-bin

odoo not starting up showing internal error(500)

Video/Screenshot link (optional):
![Screenshot_2019-05-23_14-22-32](https://user-images.githubusercontent.com/38060145/58239282-69ff8380-7d66-11e9-8411-7c78f4d6a649.png)

**Comment by Yenthe666** [comment]
Hi,

Your user "vinayak" does not have a postgreSQL user / access rights which is causing this.
This is because of an invalid deployment and has nothing to do with Odoo itself. You could alternatively try my script too (https://github.com/Yenthe666/InstallScript)

**Comment by vinayakybhatt** [comment]
Thank you so much for your help

**Comment by Yenthe666** [comment]
No problem, best of luck with Odoo!
