### ISSUE TITLE
[7.0] Fleet module. Write on fleet_vehicle fails if setting the driver to NONE

### ISSUE THREAD

**Issue by pedrorgil** [odoo/odoo#3363]
When you set a driver for a vehicle and save, it is no further possible to set the driver to NONE (i.e. False). The method 'write' inside the fleet_vehicle class is not checking if the value for vals['driver_id'] is False, so the browse over res.partner fails as it attemps to browse over an id=False:

``` python
411 if 'driver_id' in vals and vehicle.driver_id.id != vals['driver_id']:
412     # THIS NEXT LINE WILL THROW AN EXCEPTION. BROWSE OVER ID=FALSE
413     value = self.pool.get('res.partner').browse(cr,uid,vals['driver_id'],context=context).name
414     olddriver = (vehicle.driver_id.name) or _('None')
415     changes.append(_("Driver: from '%s' to '%s'") %(olddriver, value))
```

This error is easy to reproduce if you edit a vehicle, set a driver and save. Next edit the vehicle again and set the driver to none. When save it throws the exception.

To solve this issue the value for vals['driver_id'] must be checked in addition to check if 'driver_id' is present in vals and if it is different to the current driver, like this:

``` python
411 if 'driver_id' in vals and vehicle.driver_id.id != vals['driver_id']:
412     value = _('None')
413     if vals.get('driver_id'):
414         value = self.pool.get('res.partner').browse(cr,uid,vals['driver_id'],context=context).name
415     olddriver = (vehicle.driver_id.name) or _('None')
416    changes.append(_("Driver: from '%s' to '%s'") %(olddriver, value))
```

**Comment by Yenthe666** [comment]
Hi @pedrorgil,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
