### ISSUE TITLE
[12.0] Cache seems to be the same even with context change

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#33641]
Impacted versions:

12.0

When iterating on object with context change, the cache has to be invalidated to have good results.

Something like :

```python
res = {}
for warehouse in warehouses:
    res[warehouse.id] = self.product.with_context(warehouse=warehouse.id).qty_available
```

produces same result for all warehouses even if they are different.

You have to do :

```python
res = {}
for warehouse in warehouses:
    self.product.invalidate_cache(['qty_available'])
    res[warehouse.id] = self.product.with_context(warehouse=warehouse.id).qty_available
```

Code was working in v10.

Can someone confirm this ?

@mreficent @rco-odoo @mart-e

**Comment by mart-e** [comment]
Hi,

Why do you think so? I made a very simple test adding a print statement in the compute method,

```python
>>> product.with_context(foo=42).qty_available
"Executing _compute_quantities with id 62"  # first call to _compute_quantities
0.0
>>> product.with_context(foo=43).qty_available
"Executing _compute_quantities with id 62"  # new call to _compute_quantities
0.0
>>> product.with_context(foo=42).qty_available
0.0  # no print, reuse the value in cache
```

**Comment by rousseldenis** [comment]
> Why do you think so?

product quantities are different in several warehouses, but the result dict contains same values.

I will try to do it on a fresh v12 env and let you aware of my result

**Comment by rousseldenis** [comment]
It was not exactly as described: it's on a model that inherit**s** on 'product.product'.

The inherited model seems to have that problem.

I'm currently writing test shell script to show it

**Comment by rousseldenis** [comment]
Here is an example script in shell (I miss a part to correctly build the registry, but this is the idea):


`

import logging

from odoo import models, fields

_logger = logging.getLogger(__name__)


class ProductInherit(models.Model):

    _name = 'product.inherits'
    _inherits = {'product.product': 'record_id'}
    _description = 'Product Inherits'

    record_id = fields.Many2one('product.product')


def _add_stock_to_product(self, product, location, qty):
    """
    Set the stock quantity of the product
    :param product: product.product recordset
    :param qty: float
    """
    wizard = self.env["stock.change.product.qty"].create(
        {
            "product_id": product.id,
            "new_quantity": qty,
            "location_id": location.id,
        }
    )
    wizard.change_product_qty()


self = self  #

_logger.info('Initializing model')

context = self.env.context.copy()
instance = ProductInherit._build_model(self.env.registry, self.env.cr)
self.env.registry.init_models(self.env.cr, [ProductInherit._name], context)

_logger.info('Model initialized')

vals = {
    'name': 'PRODUCT 1',
    'type': 'product',
}

product_product = self.env['product.product'].create(vals)
vals.update(
    {
        'record_id': product_product.id,
    }
)
product = self.env['product.inherits'].create(vals)

wh1 = self.env.ref('stock.warehouse0')
wh2 = self.env.ref('stock.stock_warehouse_shop0')

_add_stock_to_product(self, product, wh1.lot_stock_id, 100)
_add_stock_to_product(self, product, wh2.lot_stock_id, 200)

_logger.info('Global: %s', product.with_context(warehouse=[wh1.id, wh2.id]).qty_available)
for p in product:
    _logger.info('WH1: %s', p.with_context(warehouse=wh1.id).qty_available)
    _logger.info('WH2: %s', `p.with_context(warehouse=wh2.id).qty_available)`
`

**Comment by rousseldenis** [comment]
And the good one that works :

```python

import logging

from odoo import models, fields

_logger = logging.getLogger(__name__)


class ProductInherit(models.Model):

    _name = 'product.inherits'
    _inherits = {'product.product': 'record_id'}
    _description = 'Product Inherits'
    _module = 'base'

    record_id = fields.Many2one('product.product')


def _add_stock_to_product(self, product, location, qty):
    """
    Set the stock quantity of the product
    :param product: product.product recordset
    :param qty: float
    """
    wizard = self.env["stock.change.product.qty"].create(
        {
            "product_id": product.record_id.id,
            "new_quantity": qty,
            "location_id": location.id,
        }
    )
    wizard.change_product_qty()


self = self  #

_logger.info('Initializing model')

context = self.env.context.copy()

ProductInherit._build_model(self.env.registry, self.env.cr)
_logger.info('Register')
self.env.registry.setup_models(self.env.cr)
_logger.info('Init')
ctx = dict(self.env.context, update_custom_fields=True, module='base')
self.env.registry.init_models(self.env.cr, [ProductInherit._name], ctx)

_logger.info('Model initialized')

vals = {
    'name': 'PRODUCT 1',
    'type': 'product',
}
product = self.env['product.inherits'].create(vals)

wh1 = self.env.ref('stock.warehouse0')
wh2 = self.env.ref('stock.stock_warehouse_shop0')

_add_stock_to_product(self, product, wh1.lot_stock_id, 100)
_add_stock_to_product(self, product, wh2.lot_stock_id, 200)

_logger.info('Global: %s', product.with_context(warehouse=[wh1.id, wh2.id]).qty_available)
for p in product:
    _logger.info('INHERITS WH1: %s', p.with_context(warehouse=wh1.id).qty_available)
    _logger.info('INHERITS WH2: %s', p.with_context(warehouse=wh2.id).qty_available)

    _logger.info('PRODUCT WH1: %s', p.record_id.with_context(warehouse=wh1.id).qty_available)
    _logger.info('PRODUCT WH2: %s', p.record_id.with_context(warehouse=wh2.id).qty_available)

```
