### ISSUE TITLE
[12.0] [stock] quants with qty == 0 in the Stock location

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#33657]
**Impacted versions:**

12.0

**Steps to reproduce:**

1. install the sales and stock application

2. create a stored product tracked with unique serial numbers

3. create an initial inventory for this product with 2 SN 001 and 002 and validate it

4. create a sale order for 1 unit of the product, and deliver it using SN 001

5. Display the product form view

**Current behavior:**

In the form view of the product, the quantity on hand is 1 (correct), but when I click on the smart button, I see that the Stock location has a quant for SN 001 and a quantity of 0

**Expected behavior:**

There should not be a quant with qty = 0 in stock.

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/33687
