### ISSUE TITLE
Barcode doesn't appear

### ISSUE THREAD

**Issue by alzubairy** [odoo/odoo#33659]
Hello,,
Ubuntu Server 18.04.2 LTS

I have used the following instructions, But the barcode doesn't appear
https://www.odoo.com/documentation/12.0/setup/install.html#prepare.

![image](https://user-images.githubusercontent.com/45852699/58382034-af71ba00-7fcd-11e9-979c-f1f84dc6d281.png)

**Comment by alzubairy** [comment]
![image](https://user-images.githubusercontent.com/45852699/58382028-a7197f00-7fcd-11e9-8a45-d3eb06693c87.png)

**Comment by Yenthe666** [comment]
Did you install the extra Python libraries for barcodes though?

**Comment by alzubairy** [comment]
Yes you have installed it.
After searching it turns out that the problem is in the company's servers
I moved to another company and the barcode works well.

thank you for your reply

**Comment by Yenthe666** [comment]
Good to hear, best of luck with Odoo!
