### ISSUE TITLE
制造里主生产排程没做是吗？

### ISSUE THREAD

**Issue by mxz19901102** [odoo/odoo#33664]
制造---配置---计划---主生产排程

**Comment by hzh0292** [comment]
企业版才有这个功能，不过好像也很简陋，没啥用处。

**Comment by Yenthe666** [comment]
@mxz19901102 can you please make the report in English and add more information?

**Comment by mxz19901102** [comment]
I have already know this problem,thank you very match.normal version odoo is not having this function.




------------------ 原始邮件 ------------------
发件人: "Yenthe V.G"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午3:57
收件人: "odoo/odoo"<odoo@noreply.github.com>;
抄送: "楚&轩"<1140936353@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [odoo/odoo] 制造里主生产排程没做是吗？ (#33664)




@mxz19901102 can you please make the report in English and add more information?

**Comment by Yenthe666** [comment]
Okay, thanks for the feedback!
