### ISSUE TITLE
[12.0] CRM lead missing followers from a team

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#33691]
Impacted versions: 12.0
Tested on a latest runbot.

Steps to reproduce:

You should have a sales team with followers.
1. Open CRM lead/opportunity kanban view via activities menu (clock icon) on the top right.
2. Create a new lead and set sales team that has followers.

Current behavior: 
Lead doesn't get followers from a sales team

Expected behavior: 
Lead gets all followers from a sales team

Video/Screenshot link (optional):
Both cases are shown via this video https://drive.google.com/file/d/1ETi-wzf0ruvLfyBVXwrDcAo9huy3pPCY/view?usp=sharing

**Comment by pedrobaeza** [comment]
This has probably something to do with passed context.

**Comment by sswapnesh** [comment]
Missing `default_team_id` in context

`default_team_id` not available when we create from Activities
![Screenshot from 2019-05-27 23-33-29](https://user-images.githubusercontent.com/16624719/58434167-f0ee8c00-80d7-11e9-8587-6e114e8b229e.png)


From Main menu
![Screenshot from 2019-05-27 23-33-42](https://user-images.githubusercontent.com/16624719/58434187-05328900-80d8-11e9-931f-b5dbc67b46ff.png)
