### ISSUE TITLE
billing to delivery orders for stock_picking module

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#337]
Billing partner for grouping, enter the field fiscal_position in the function module "_prepare_invoice_group"  stock_picking to allow transcoding of accounts in the table fiscal_postion also in the billing partner for delivery of orders

**Comment by Yenthe666** [comment]
Dear @roccocesetti,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
