### ISSUE TITLE
Ecommerce: cost for delivery method incorrectly reported on checkout page

### ISSUE THREAD

**Issue by apprique** [odoo/odoo#3371]
On the checkout page Delivery method can be chosen. If the delivery method has a condition to apply for a minimum order quantity, the cost of the delivery is evaluated in a wrong order. Example:

Order value: 180
Delivery method: DHL (not imporant)
Delivery price for minimum 200: 0
Delivery price below 200: 50

This results in 50 being reported for delivery just below the total cost and total cost is correctly 230.
However, where you choose the delivery method, it now shows 0 for this delivery method (probably because total order value is now above 200). This logic is incorrect.

**Comment by Yenthe666** [comment]
Hi @apprique,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
