### ISSUE TITLE
Odoo Search

### ISSUE THREAD

**Issue by jtunez90** [odoo/odoo#33718]
Hi all!
I need to perform a search for a field in a table that has the following relationship:

class AiHrEmployee (models.Model):
     _inherit = ['hr.employee']

    collaborations_ids = fields.One2many ('hr.employee.collaboration.line', 'employee_id', "Collaboration activities")

class AiCollaborationActivityLine (models.Model):
     _name = "hr.employee.collaboration.line"

     employee_id = fields.Many2one ('hr.employee', 'Employee')
     country_id = fields.Many2one ('res.country', 'Place of collaboration')
     activity = fields.Char (string = "Activity of collaboration", size = 80)
     time = fields.Integer (string = "Time", help = "Time of collaboration")
  
Country class:
    _name = "res.country"
    name = fields.Char ()

In the view I want to do the search, the employees are listed, I need to show all the employees that have had collaboration in a certain country (country) that I must pass as a parameter.

Regards

**Comment by Yenthe666** [comment]
Hi @jtunez90,

The Github tracker is only used for reporting issues in the official code, it is not the right place to ask questions.
I saw you already opened up a question on the help forum too so I'm closing this one.

Regards,
Yenthe
