### ISSUE TITLE
Ecommerce: address line 2 in Odoo, does not end up in correct field in PayPal

### ISSUE THREAD

**Issue by apprique** [odoo/odoo#3372]
Address line 2 in Odoo, does not end up in correct field in PayPal, instead it is concatenated with address line 1.

**Comment by Yenthe666** [comment]
Hi @apprique,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by apprique** [comment]
Hi Yenthe,

I think it’s an absolute disgrace that you respond to a business blocking issue over 3 years (THREE YEARS!) after it was raised.

How could I trust that Odoo takes me as a potential reselling partner serious?

Best regards,

Maarten

**Comment by gdgellatly** [comment]
Hi @apprique 

1. @Yenthe666 is a volunteer who voluntarily monitors the FREE community github support issues.  There are no guarantees here.  
2. As a reselling partner, or as an enterprise customer, you get priority support and bugfixes via another channel.
3. Through that channel, your issue would have been fixed, it is quite likely it was fixed regardless, just not updated here.  

I'm sure as a potential reselling partner you can understand the need for a business to prioritise limited resources towards paying customers.  That said, the closure rate on free support requests seems to be improving.

**Comment by Yenthe666** [comment]
Hi @apprique,

I'm sorry that you feel this way. As @gdgellatly has mentioned I'm doing this voluntarily. At this point I'm only trying to clean up all the very old bug reports and to label/segment the new bug reports for V11. When you look at all V11 bug reports you'll see quite a good increase in response and solve rates (https://github.com/odoo/odoo/issues?q=is%3Aopen+is%3Aissue+label%3A11.0). At this point 152 are solved and 66 are open, which is way better than any previous versions.

If you ever become a partner you have a dedicated support channel that always responds and solves a lot of the issues too.
Again, sorry that nobody responded faster to your bug report.

Regards,
Yenthe

**Comment by apprique** [comment]
Hi Yenthe,

Sorry for my somewhat strong response. I highly appreciate your voluntary work. From your profile I understood that you were working for odoo directly. I guess since the issue I raised was so clearly described in a reproducable way, I was very surprised it was never followed up. I hope that indeed new issues receive better follow-up, even in the unpaid channel. Me raising an easy to reproduce issue is, after all, also done voluntarily and serves to make odoo better.

Best regards,

Maarten

**Comment by Yenthe666** [comment]
Hi Maarten,

I don't work for Odoo, I only have access to the Odoo repository here on Github (which probably looks like if I work for them?).
I do understand your frustration. This bug report should have been handled too.
If you ever make a new bug report then just ping me and I'll make sure it gets the attention it needs.

Regards,
Yenthe
