### ISSUE TITLE
[11.0] Form not closed after click a button

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#33737]
Impacted versions:
11.0

Steps to reproduce:
Open a form like wizard [By Setting target is new], That form contains a Custom Button and particular action(It navigate to another model [From Sales to Customers]).

Current behavior:
When i click a custom button, Current form not closed.

Expected behavior:
When i click a custom button, Current form need to be closed.

**Comment by pedrobaeza** [comment]
Yes, this behavior won't be fixed in 11.0, but it has been changed in 12.0.

Closing as solved in newer versions.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza Can you provide the location of modified file ?

**Comment by pedrobaeza** [comment]
No, sorry. You can check on runbot for trying this feature in version 12.0
