### ISSUE TITLE
Defaulting to string en_US

### ISSUE THREAD

**Issue by bnisevic** [odoo/odoo#33750]
Impacted versions: 12

Steps to reproduce:
- Save a transaction programmatically with its create method without explicitly stating values for partner fields and with --load-language other than 'en_US'. I use odoo-bin with --load-language de_DE. 'en_US' is not active on my system.

E.g. of transaction being created:
```
self.env['payment.transaction'].create({
            'date': payment_date,
            'acquirer_id': acquirer_id,
            'type': 'server2server',
            'state': 'draft',
            'state_message': _('Payment initiated.'),
            'amount': params['amount_value'],
            'currency_id': currency_id,
            'reference': transaction_reference,
            'partner_id': payuca_partner.partner_id.id,
            'payment_id': payment.id,
            'is_processed': True,
            # Fields to populate later on next steps:
            # 'acquirer_reference': '',  # PSP reference for the transaction.
            # 'invoice_ids': None,
        })
```  
- If just a `partner_id` is provided, following lines are supposed to fill-out missing transaction fields: https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L880-L889
```
            values.update({
                'partner_name': partner.name,
                'partner_lang': partner.lang or 'en_US',
                'partner_email': partner.email,
                'partner_zip': partner.zip,
                'partner_address': _partner_format_address(partner.street or '', partner.street2 or ''),
                'partner_city': partner.city,
                'partner_country_id': partner.country_id.id or self._get_default_partner_country_id(),
                'partner_phone': partner.phone,
           })
```

But following line is the bug: https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L882
```'partner_lang': partner.lang or 'en_US',```

If partner.lang is not defined it is trying to fill-out transaction.partner_lang with 'en_US'. And  transaction.partner_lang being defined here as Selection field https://github.com/odoo/odoo/blob/12.0/addons/payment/models/payment_acquirer.py#L587 defined by ` _lang_get` which propagates to self.env['res.lang'].get_installed() causes the error if `'en_US'` in `res_lang` doesn't have `active` field set to true which is my case of the Odoo setup.

Also the field  `partner_lang` has its default value defined. There is no need to use `'partner_lang': partner.lang or 'en_US',`.

Current behavior:
```ValueError: Wrong value for payment.transaction.partner_lang: 'en_US' ```

Expected behavior:
 Save default partner_lang in transaction if partner.lang is not defined.

This is related to the issue reported here and closed but not resolved: https://github.com/odoo/odoo/issues/15165

**Comment by bnisevic** [comment]
Actually `default=lambda self: self.env.lang` won't work for `partner_lang` field in transaction model. For some reason self.env.lang returns 'en_US' even when my active language is 'de_DE'.

**Comment by mart-e** [comment]
Hi,

Thanks for the report and analysis.
I agree I don't think the `or en_US` part is useful. The `partner_lang` is not required no value is better that a wrong one,

@dbo-odoo I think this code is from a long time ago (382829686def6cd1cc6a09f8cf61a7c6ba55a9c0) when en_US was not deactivable. Could you confirm it is fine to remove it?

> For some reason self.env.lang returns 'en_US' even when my active language is 'de_DE'.

This is odd, could you elaborate that part please?

**Comment by dbo-odoo** [comment]
The field should probably be required, since some payment providers expect to find a value in the payment form (IIRC this is why the falback to en_us was added in the first place)
another possibility would be to add the fallback to en_US during the form rendering

in any case, i'm pretty confident a fallback is necessary; either the one from the current user somehow or the first active res.lang or something (or fallback to en_us in the rendering)

**Comment by bnisevic** [comment]
>>  For some reason self.env.lang returns 'en_US' even when my active language is 'de_DE'.

> This is odd, could you elaborate that part please?

I've queried languages SQL table and only one had active=true which de_DE which I initiate on odoo-bin. But yet when I stop in CLI during debugging and I output `self.env.lang` I get 'en_US'. But localization works fine in other parts.

I can make another issue with reproducing this again, if you think that would be useful.

**Comment by mart-e** [comment]
@bnisevic there may have a good reason for that but it is worth investigating, maybe another incorrect defaulting to `en_US`.
If you know how to reproduce it, please open another issue so we can discuss it there.
