### ISSUE TITLE
[10.0] Problem with refund/order returns without cash payment method in POS

### ISSUE THREAD

**Issue by alvarosalinero** [odoo/odoo#33752]
Impacted versions: 10.0

We have a Point Of Sale (POS) terminal configured only with the "Card payment method" and we can not make refunds/order returns.

The error we get when trying to do it is the following:

"There is no cash payment method available in this point of sale to handle the change.\n\n Please pay the exact amount or add a cash payment method in the point of sale configuration" 

We have found in the code that in the function  "order_is_valid" the following checkup is made:

<pre>
Math.abs(order.get_total_with_tax() - order.get_total_paid()) > 0.00001
</pre>   

Therefore, in the case of refunds with negative values, the absolute value of the difference between both values considered is always bigger than 0.00001. Then, the POS tries to look for the "cash payment method" (which is not active in our POS).

How can we perform this refund?

Thank you

**Comment by pedrobaeza** [comment]
@switch87 what do you think about this?

**Comment by Yenthe666** [comment]
Dear @alvarosalinero,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
