### ISSUE TITLE
[10.0] ondelete attribute is not correctly shown on field form

### ISSUE THREAD

**Issue by bjccdsrlcr** [odoo/odoo#33788]
Impacted versions: 10

Steps to reproduce: any many2one field define fields.Many2one("item.sales", string="2 hours sales", ondelete='cascade')

Expected behavior:
the form of ir.model.fields should show the correct value in ('cascade', 'set null', 'restrict') . now is all null 

Video/Screenshot link (optional):
please check and repair it
![image](https://user-images.githubusercontent.com/30322340/58693879-538ba480-83c4-11e9-8175-fdcc93ed504e.png)

**Comment by bjccdsrlcr** [comment]
I think I have found the problem. seems here when to reflect models and fields not add the key "on_delete"
![image](https://user-images.githubusercontent.com/30322340/58707093-7a5ad280-83e6-11e9-9be2-5314e57eabf6.png)

**Comment by bjccdsrlcr** [comment]
> I think I have found the problem. seems here when to reflect models and fields not add the key "on_delete"
> ![image](https://user-images.githubusercontent.com/30322340/58707093-7a5ad280-83e6-11e9-9be2-5314e57eabf6.png)

**Comment by bjccdsrlcr** [comment]
so if I made this change, will there be other bugs?

**Comment by Elkasitu** [comment]
requires backport of https://github.com/odoo/odoo/pull/27906

**Comment by bjccdsrlcr** [comment]
> requires backport of #27906

I have seen this, but the version is 12. since version 10 and 12 exists much differences, I haven't found the solution of 10

**Comment by pedrobaeza** [comment]
@Elkasitu then I suppose we should close this as won't fix in 10, but fixed on v12, isn't it?

**Comment by Elkasitu** [comment]
I will let @mart-e judge whether the fix is backportable to v10 or not

**Comment by mart-e** [comment]
Hi,

Sorry but I prefer not to backport it in 10.0. The 10.0 is in end of life and changing the behaviour in ir.model is never without risks. As this is not a blocking bug, lets not change it now.
