### ISSUE TITLE
Slugify lib is called with None instead of 0

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#33807]
Impacted versions: 11.0, 12.0, master

Steps to reproduce:
Slugify lib is never user because most of the time it is called with wrong default parameter.

When `slugify` is [called](https://github.com/odoo/odoo/blob/fef49061ead4a437bac922d9d32270f76addd014/addons/http_routing/models/ir_http.py#L61) with `max_length=None` there is an exception.

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/slugify/slugify.py", line 174, in slugify
    if max_length > 0:
TypeError: unorderable types: NoneType() > int()
```
It has to be called with `max-length=0` according to [signature](https://github.com/un33k/python-slugify/blob/master/slugify/slugify.py#L77).

Current behavior:
Slug for non latin characters is not working even if slugify lib is installed.

Expected behavior:
Slug for non latin characters shold be working if slugify lib is installed.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please indicate the places in code where this happens or even better, propose a PR changing it?

**Comment by lem8r** [comment]
`slugify` is called without `max_length` param https://github.com/odoo/odoo/blob/fef49061ead4a437bac922d9d32270f76addd014/addons/http_routing/models/ir_http.py#L95 so it is `None` by default.

`slugify` is calling `slugify_one`
https://github.com/odoo/odoo/blob/fef49061ead4a437bac922d9d32270f76addd014/addons/http_routing/models/ir_http.py#L77-L78

which is calling `slugify_lib.slugify`
https://github.com/odoo/odoo/blob/fef49061ead4a437bac922d9d32270f76addd014/addons/http_routing/models/ir_http.py#L61

 which expects `max_length` to be integer.
https://github.com/un33k/python-slugify/blob/master/slugify/slugify.py#L77-L95

Docsting of `slugify_one` also says that `max_length` should be `int`.
https://github.com/odoo/odoo/blob/fef49061ead4a437bac922d9d32270f76addd014/addons/http_routing/models/ir_http.py#L47-L56

For which branches can I do PRs? It would be great to fix this since 11.0 an up.

**Comment by Yenthe666** [comment]
Lowest version where you encounter it. CC @JKE-be

**Comment by JKE-be** [comment]
PR in version 11 is ok.
The bug only appear with python3

Thank you

**Comment by lem8r** [comment]
Is it possible to merge for 11.0 too?

Thanks

**Comment by JKE-be** [comment]
History on https://github.com/odoo/odoo/pull/33835 is not clean.

You have a merge commit into the pr

**Comment by lem8r** [comment]
Yes, sorry.
Now history is clean.
