### ISSUE TITLE
[10.0][purchase] Purchase order final pric

### ISSUE THREAD

**Issue by manuelviejo** [odoo/odoo#33819]
Impacted versions: 10

Steps to reproduce:

1. Create purchase order:
   1.1 1 product, with product uom kg 
2. Confirm purchase order
4. Receive products (Create picking)
5. Validate picking
6. Return picking
   6.1 Check to refund so
   6.2 Change the quantity
   6.3. Confirm return
7. Validate return picking

Current behavior:
When generating the invoice, it takes the new quantity correctly, but the purchase order total price is taking old quantity.

Expected behavior:
I think the purchase order should take the new quantity for computing the price, like the invoice.

More:
I am the boy who asked you in the journeys of Santiago

**Comment by Yenthe666** [comment]
Dear @manuelviejo,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
