### ISSUE TITLE
error when run odoo

### ISSUE THREAD

**Issue by taxuannam** [odoo/odoo#33847]
Impacted` versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

vesinhminhthuy360@odoo:/opt/odoo/odoo$ ./odoo-bin
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/opt/odoo/odoo/odoo/__init__.py", line 73, in <module>
    import babel
ModuleNotFoundError: No module named 'babel'

**Comment by sswapnesh** [comment]
Install requirements.txt using

`sudo pip3 install -r requirements.txt` or  `sudo pip install -r requirements.txt` based on odoo version.

Refer to https://www.odoo.com/documentation/12.0/setup/install.html#id4 for more details.

**Comment by pedrobaeza** [comment]
Yes, this is not an Odoo issue itself, so closing.
