### ISSUE TITLE
[8.0/Master] Error in Send by Email :whene try to delete the pre-attached document.

### ISSUE THREAD

**Issue by cod-odoo** [odoo/odoo#3384]
Impacted versions:
   -> 8.0 and master

Steps to reproduce:
 1.Go to sales > Quotation
 2.Create a new Quotation with some required datas
 3.Click on Send by Email button
 4. Now try to delete the pre-attached document (e.g. Attached pdf of Quotation).
 
Note:It is also reproduce in sale order,invoice,purchase quotation,purchase order...

Current behavior:
Uncaught TypeError: Cannot read property 'no_unlink' of undefined

Expected behavior:
Error should be fixed and  i can delete pre-attached document.

**Comment by Yenthe666** [comment]
Hi @cod-odoo,

This issue is no longer present in the latest 8.0 (and neither in 9.0).
Closing this issue since it has been fixed somewhere along the line.

Regards,
Yenthe
