### ISSUE TITLE
[12.0] After yesterday's Chrome update, on debug assets mode, bootstrap js file is not being loaded.

### ISSUE THREAD

**Issue by deepak-ksolves** [odoo/odoo#33854]
Impacted versions: 12.0

Steps to reproduce: System - Ubunutu 16.04. 
1. Update chrome to latest update. 
2. Activate debug assets mode.
3. On console, bootstrap file will give error (popover.js file error).

Current behavior: All pop up menu stops working.

Expected behavior: All pop up menu work like default.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/45991086/58853639-9d240a00-86b8-11e9-99dd-69d980002b5a.png)

**Comment by Yenthe666** [comment]
@deepak-ksolves I can't reproduce this one (anymore). Could you test again on the latest runbot instance please?

**Comment by deepak-ksolves** [comment]
Looks like it was only on specific version of chrome and now its working fine.
