### ISSUE TITLE
[12.0] No access to technical access rights

### ISSUE THREAD

**Issue by Axel-G** [odoo/odoo#33850]
I installed a fresh odoo from github.
And i get now access to technical access rights in user view, not with debug and not with debug=assets.

Its this a new feature?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

A little tip: nothing has changed about this.

Closing this by the reason above.

**Comment by Axel-G** [comment]
Hello @pedrobaeza, one question again please to these topic.

On the same instance: i access with port 8069 to the instance i see all technical forms in debug mode, but if i access with https to the same instance i can see only a part of the technical possibilities.
over nginx:
https://domain.tld/web?debug=assets#id=2&action=68&model=res.users&view_type=form&menu_id=4
![https](https://user-images.githubusercontent.com/40705043/59151040-e4015f00-8a2c-11e9-9860-2d71cfb3d03c.png)

http://10.1.1.2:8069/web?debug=assets#id=2&action=68&model=res.users&view_type=form&menu_id=4
![https](https://user-images.githubusercontent.com/40705043/59151051-20cd5600-8a2d-11e9-920d-4e13ea45dcf2.png)

Is  this a normal behavior? I can reproduce this. Its only by new installation from actual git. by my old installations this is not. The nginx-conf of old an new is the same.

Maybe it gives a parameter to set?
