### ISSUE TITLE
New field cannot be shown correctly before standard_price.

### ISSUE THREAD

**Issue by telesoho** [odoo/odoo#33889]
Impacted versions:

origin/12.0 bd3a78847998d117ebb32b303eaa3886f00c50ba

Steps to reproduce:

I create a view in a new module  add a new field sku_price before standard_price like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <record id="product_sku_price_view" model="ir.ui.view">
            <field name="name">product.sku.price.view</field>
            <field name="model">product.product</field>
            <field name="inherit_id" ref="product.product_variant_easy_edit_view" />
            <field name="arch" type="xml">
                <field name="standard_price" position="before">
                    <field name="sku_price" widget='monetary' options="{'currency_field': 'cost_currency_id', 'field_digits': True}"/>
                </field>
            </field>
        </record>
    </data>
</odoo>
```
Then install this new module, but the sku_price cannot be shown correctly.

![image](https://user-images.githubusercontent.com/10979091/58934267-e8b3e200-87a4-11e9-9743-1c45b4f87425.png)

I found standard_price be defined in 

https://github.com/odoo/odoo/blob/bd3a78847998d117ebb32b303eaa3886f00c50ba/addons/product/views/product_views.xml#L292
 
So I try to put sku_price before lst_price defined in:

https://github.com/odoo/odoo/blob/bd3a78847998d117ebb32b303eaa3886f00c50ba/addons/product/views/product_views.xml#L291

I changed view define like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data>
        <record id="product_sku_price_view" model="ir.ui.view">
            <field name="name">product.sku.price.view</field>
            <field name="model">product.product</field>
            <field name="inherit_id" ref="product.product_variant_easy_edit_view" />
            <field name="arch" type="xml">
                <field name="lst_price" position="before">
                    <field name="sku_price" widget='monetary' options="{'currency_field': 'cost_currency_id', 'field_digits': True}"/>
                </field>
            </field>
        </record>
    </data>
</odoo>
```
After updating the module, It's work fine.

![image](https://user-images.githubusercontent.com/10979091/58934695-311fcf80-87a6-11e9-8534-65b4e8e19478.png)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

Little tip: check full arch to understand that you are putting the field in the middle of a structure (probably a div), and thus is placed incorrectly.

**Comment by Yenthe666** [comment]
Just change your xpath expression and you'll have it working too.

**Comment by telesoho** [comment]
@pedrobaeza 

I try to activate the developer mode, notice that 'standard_price' field has been changed by other  'product.product_variant_easy_edit_view' odoo's inheriance view.

So I try to change my view sequence from 16 to 1.

![image](https://user-images.githubusercontent.com/10979091/58945726-5f5dd900-87bf-11e9-9c3f-08badcefd6d5.png)

![image](https://user-images.githubusercontent.com/10979091/58945751-6c7ac800-87bf-11e9-9dd5-d7215980cbc6.png)

Refreshing the page, the sku_price has been shown correct.

![image](https://user-images.githubusercontent.com/10979091/58945810-887e6980-87bf-11e9-86bc-d1ec0c23118e.png)

**Comment by pedrobaeza** [comment]
As said, this is not the place for this kind of questions.

**Comment by telesoho** [comment]
Sorry!
