### ISSUE TITLE
Product search on Sale order limited to current viewset

### ISSUE THREAD

**Issue by jeroen7s** [odoo/odoo#33907]
Impacted versions: 11.0

Steps to reproduce:
go to sale order
search product using barcode or name
check result

Current behavior:
result shows sale orders that were in original view of 80, filtered by the product with the barcode.
It should return all Sale orders, filtered by the product with the barcode.
i'm on the standard sale order list view
it has 75k sale orders, but only shows 1-80 by default (until I click next to show the next 80)
if I search for a product, using it's barcode, it only returns the results of the first 80 sale orders, not all 75k, even though the initial resultset was 75k

Expected behavior:
odoo should give a list of all sale orders containing that product, not just the ones in the original view

Video of the issue: https://youtu.be/LSASAEWwPYA
You can see at first, it returns 55 of the 80
Then I change the view to show 800 and filter again, showing 563 records
I also change the order by date, changing the result to 653, which seems to confirm that the search is confined to the viewset, and not the entire recordset

**Comment by pedrobaeza** [comment]
I don't get the problem. If you are in a view that restricts currently viewed sales orders, the filter is over that recordset, not on the whole. Go to a view that shows all the records at the beginning and then apply the barcode. That's the paradigm for all and I see it OK.

For other flows, you need to customize your end according your needs and paradigm.

@Yenthe666 if you consider the same, I let you to close for a second opinion before pinging anyone.

**Comment by jeroen7s** [comment]
@pedrobaeza, i'm on the standard sale order list view
it has 75k sale orders, but only shows 1-80 by default
if I search for a product, using it's barcode, it only returns the results of the first 80 sale orders, not all 75k,  even though the initial resultset was 75k

**Comment by pedrobaeza** [comment]
That's very weird, but indeed if that's the problem, there's a bug. Please change the initial comment for clarifying this and if you provide a video, it would be great for showcasing the problem.

**Comment by Yenthe666** [comment]
& try to reproduce it on a runbot / instance without custom development to be sure.

**Comment by jeroen7s** [comment]
Did add a video showing what happens.
If you change the view from showing 80 items to 800, and then add the filter, it will show a lot more records.

Also if you change the order of the records, it returns a different recordset.
Sale Order themselves were cut off from the video for GDPR reasons, but the search bar, headers and result count should be enough to demonstrate the issue.

**Comment by pedrobaeza** [comment]
OK, tagging then.

**Comment by jeroen7s** [comment]
a search_read is called on model sale.order with limit 80(current viewset) when adding this search, but i'm not sure what calls this search_read

**Comment by GSLabIt** [comment]
@pedrobaeza we're experiencing this on v 12.0, any feedback from odoo sa?

**Comment by Yenthe666** [comment]
Nothing as long as there is no comment sadly.

**Comment by GSLabIt** [comment]
@Yenthe666 could ping someone at odoo to double check this?

**Comment by Yenthe666** [comment]
That would be @tde-banana-odoo

**Comment by GSLabIt** [comment]
@Yenthe666 thx.

**Comment by theangryangel** [comment]
@GSLabIt did you get to the bottom of this issue at all? I'm seeing this for the on a 12.0 installation and was perhaps you've made progress with this issue in the interim?

**Comment by GSLabIt** [comment]
@theangryangel unfortunately no news

**Comment by travish2** [comment]
A bit more info for anyone coming across this:

Steps to duplicate (happens in both v12 and v13, not v14) with demo data:
1) Open S00011 and add a 3rd line for Acoustic Bloc. Important to add the line and not increase the first line for the same product. <br/><img width="478" alt="Step1" src="https://user-images.githubusercontent.com/30615274/149680434-7e1bc277-3996-465b-bfc7-25cefd5dbf8b.PNG">
2) On Sale Order list view, search for "Acoustic" product. Notice it returns 10 results<br/><img width="957" alt="Step2" src="https://user-images.githubusercontent.com/30615274/149680436-211d0b3b-9ca6-4531-9ca4-45d5c744189c.PNG">
3) Clear the search filter and set the pager to 1-5 <br/><img width="496" alt="Step3" src="https://user-images.githubusercontent.com/30615274/149680439-3d1afa04-415c-43b5-a0d7-0dbf2291fa77.PNG">
4) Search again for "Acoustic" product. It returns only 4 results <br/><img width="956" alt="Step4" src="https://user-images.githubusercontent.com/30615274/149680440-82c23d5a-25ca-4a77-8e22-13cd75193c8a.PNG">

What is happening:
The private _search() method (under odoo/models.py) has a _uniquify_list() function that removes the duplicate order result and makes the length incorrect in addons/web/controllers/main.py:do_search_read()


Odoo will not fix as they consider a "limitation in 12.0 and 13.0"

**Comment by jeroen7s** [comment]
Ok, thanks a lot for the explanation
If it's not going to be fixed, I'll close this ticket.
The customer that reported this issue is now on v14, so we no longer need this to get fixed.
Good to finally have an explanation though.
