### ISSUE TITLE
[12.0] Generate SO from project

### ISSUE THREAD

**Issue by hmrodrigues** [odoo/odoo#33914]
Impacted versions: 12

Steps to reproduce:
On project that can create sales orders, service products can't be added because service products products [must have](https://github.com/odoo/odoo/blob/12.0/addons/sale_timesheet/wizard/project_create_sale_order.py#L32):

- invoice_policy = delivery
- service_type = timesheet

But this settings can't be changed because:

- invoice_policy: [Only available when the product isn't a service](https://github.com/odoo/odoo/blob/12.0/addons/sale_timesheet/views/product_views.xml#L10)
- service_type: [Is always invisible](https://github.com/odoo/odoo/blob/12.0/addons/sale/views/sale_views.xml#L1027)

Current behavior:
A user can't configure a product in order to use it to create a sale order from a project

Expected behavior:
Allow the user to set the values of invoice_policy and service_type of a service product so users can use them to create SO from projects

Video/Screenshot link (optional):
![Screenshot from 2019-06-05 14-45-17](https://user-images.githubusercontent.com/8062666/58961762-b785e280-87a1-11e9-94e8-79deca9d1349.png)
![Service_Consumable](https://user-images.githubusercontent.com/8062666/58961774-bce32d00-87a1-11e9-856b-25a35901ef8a.jpg)
![Service_Consumable_Invoice_Policy](https://user-images.githubusercontent.com/8062666/58961776-bce32d00-87a1-11e9-95dd-ac2f5beb0f22.jpg)
![Serive_Service](https://user-images.githubusercontent.com/8062666/58961777-bd7bc380-87a1-11e9-9096-c537dc47d246.jpg)
![Service_Service_Invoice_missing](https://user-images.githubusercontent.com/8062666/58961780-bd7bc380-87a1-11e9-9b01-377e9f8f9481.jpg)
![Requirements_Sale_Order](https://user-images.githubusercontent.com/8062666/58961782-be145a00-87a1-11e9-9af0-cc13866ecbf2.jpg)

Screenshots from [Runbot](http://533977-12-0-0e403f.runbot20.odoo.com)

**Comment by hmrodrigues** [comment]
cc @andrealexandrewangliu

**Comment by pedrobaeza** [comment]
@hmrodrigues is this still happening? Can you point to the code where the constraint about the invoicing policy is set?

**Comment by andrealexandrewangliu** [comment]
It seems to be solved on runbot, atleast it seems to work solved if you set Service Invoice Policing to Timesheets on tasks. It automatically sets the product to Delivered Quantities.

**Comment by mart-e** [comment]
I am closing this issue as it seems to be fixed, in case it does happen again, let me know and we will investigate.
