### ISSUE TITLE
Handle both 'http' and 'json' request

### ISSUE THREAD

**Issue by lalibrerie-solidaire** [odoo/odoo#33916]
Hello,

I couldn’t find a solution to make odoo able to handle both http and json type request on the same url. I would like to be able to have something like this:

```
class MyController(http.Controller):

    @http.route(route='myurl', type='http')
        def process_http(self, **kw):
            do_something

    @http.route(route='myurl', type='json')
        def process_json(self, **kw):
            do_something_else
```

so that, if I get an http request, it is processed with the 'process_http' function, and json requests with 'process_json' function, with 'myurl' being the same in both cases.

I tried to implement it the way it is in the example, but it doesn’t work, the first method is taken into account, the second one is totally ignored. I also tried to define two different controller class (one for each method) but one controller is used and the other is totally ignored.

Thanks,

La Librerie

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
