### ISSUE TITLE
Error message on login after apt-get upgrade

### ISSUE THREAD

**Issue by d-techdave** [odoo/odoo#33923]
Impacted versions: 11.0-20190605

Steps to reproduce: apt-get update, apt-get upgrade, then log into Odoo

Current behavior:
Error window appears:
"
(b'', b'TypeError: sys.print is not a function
    at /usr/lib/nodejs/less/bin/lessc:384:25
    at tree.importVisitor.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)
    at tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)
    at Object.parse (/usr/lib/nodejs/less/lib/less/parser.js:675:22)
    at parseLessFile (/usr/lib/nodejs/less/bin/lessc:345:12)
    at Socket. (/usr/lib/nodejs/less/bin/lessc:407:9)
    at Socket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
')This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/lib/bootstrap/less/mixins/clearfix.less
    - /web/static/lib/bootstrap/less/mixins/size.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less
    - /web/static/src/less/fonts.less
    - /web/static/src/less/navbar.less
    - /web/static/src/less/mimetypes.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/animation.less
    - /web/static/src/less/rainbow.less
    - /web/static/src/less/datepicker.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_tour/static/src/less/tip.less
    - /web_tour/static/src/less/keyframes.less
    - /stock/static/src/less/stock_traceability_report.less
" 
You can close the window and Odoo appears to run normally.

Expected behavior: No error window

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That is not enough for Odoo. You have to update your modules inside Odoo DB (with -u all for example). Any way, not an Odoo issue itself, but a deployment problem. Closing.
