### ISSUE TITLE
Clicking "Test Import" adds sequence numbers and leads to wrong sequences

### ISSUE THREAD

**Issue by geniustaha** [odoo/odoo#33950]
When we are importing products in bulk, if we click on the button test import, it updates the sequence numbers. (Even if we dont upload the sheet.)
**Impacted versions:** 
Version 11
Module: https://apps.odoo.com/apps/modules/11.0/product_sequence/
**Steps to reproduce:**
Go to product Import.
Upload the sheet.
Click on Test Import Button.
**Current behavior:**
Suppose there were 10 products of a certain category, the sequence number jumps by 10. Suppose there were 4 products, it jumps by 4.
Suppose if we press the test import twice, the sequence jumps by double the numbers.
**Expected behavior:**
No change in sequence number when Test import is clicked.
We need a mechanism to detect test imports and not to make the next sequence number update when the test import button is pressed.
OR
Unroll the sequence number jump caused by test import.
Reported this on Module page. They said its an Odoo issue and not related to module.
https://github.com/OCA/product-attribute/issues/487

**Comment by pedrobaeza** [comment]
@xmo-odoo I have observed this problem as well, that sequences are not rolled back to their previous value. In this case, it's showcased with a community module, but it happens with any sequence. I think you are the one that touches import mechanism, isn't it?

**Comment by Yenthe666** [comment]
This has been the case in Odoo for years, across multiple versions actually. I once saw a big topic about this but can't find it anymore..

**Comment by sswapnesh** [comment]
May be this one https://github.com/odoo/odoo/pull/25066

**Comment by geniustaha** [comment]
I am new to odoo development. Pardon me if it's naive. 
I was thinking of putting the sequence code in an if statement and to run it only when an actual import occurs. 
For this, we need to detect in Python code if test import is clicked or import. 
Please let me know if this is possible as a quick fix.

**Comment by sswapnesh** [comment]
@geniustaha  This was suggestd at https://github.com/odoo/odoo/pull/25066/files#diff-eeba4a9f5244f4843e219e9d8817e028R248

**Comment by geniustaha** [comment]
> @geniustaha This was suggestd at https://github.com/odoo/odoo/pull/25066/files#diff-eeba4a9f5244f4843e219e9d8817e028R248

Thanks. I applied the fix and it worked. Thanks everyone.
