### ISSUE TITLE
BOM count does not display on the product variant

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#33955]
Impacted versions: V10

Current behavior:
- on the product (template) page the counter is displayed correctly
- on the product variant page, if  I click on the counter 0, the list of BOMs show just fine.

Video/Screenshot link (optional):
![product variant BOM display bug](https://user-images.githubusercontent.com/27618042/59036141-03eb2400-886f-11e9-92b4-7272ca229955.png)
![list of bom](https://user-images.githubusercontent.com/27618042/59036274-3a28a380-886f-11e9-859c-6a964c4918ee.png)

**Comment by Yenthe666** [comment]
Dear @nagybal,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
