### ISSUE TITLE
[10.0][BUG] ordering records by reference number fails

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#33987]
Impacted versions: V10

As Odoo would not know the ABC. It fails quite frequently. It is really embarrassing. What I am doing wrong? Could someone assist me here with proper troubleshooting?

Video/Screenshot link (optional):
![ordering issue](https://user-images.githubusercontent.com/27618042/59107500-13cf3a80-8939-11e9-9ba9-8feed2a5975b.png)

**Comment by pedrobaeza** [comment]
The order is done through the SQL column, not taking into account translations.

**Comment by nagybal** [comment]
Since when is an unique identifier of an inventory move (record) a translated field? oO please set the priority to high!!!

**Comment by pedrobaeza** [comment]
Which field are you sorting by (technical name)?

**Comment by nagybal** [comment]
Field: name
Object: stock picing
Type: char

**Comment by pedrobaeza** [comment]
Is it reproducible in runbot?

**Comment by pedrobaeza** [comment]
The screenshot I'm seeing is for stock.move, not stock.picking

**Comment by nagybal** [comment]
I am not familiar with the runbot.

You are right. It is little different if I go through the traceability view. Is the reference number generated via the picking? Or am I wrong?

You It is little different if I go through the traceability view:
![Képernyőkép erről: 2019-06-07 15-48-51](https://user-images.githubusercontent.com/27618042/59108806-0f585100-893c-11e9-93a3-50f341ca57a0.png)
