### ISSUE TITLE
[OE][BUG] web: odd even color on tree views doesn't work when groupby is used.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#33994]
Impacted versions: 12

Steps to reproduce:
Connect to runboot
Goto product, grouby Unit (works on any group by)

Current behavior:
![image](https://user-images.githubusercontent.com/16716992/59122641-923cd400-895b-11e9-8b37-ca7b0dd620d6.png)

when you passe the mousse only 1 line on 2 is highlighted:
![image](https://user-images.githubusercontent.com/16716992/59122726-c57f6300-895b-11e9-90e3-49309871613e.png)
![image](https://user-images.githubusercontent.com/16716992/59122749-d29c5200-895b-11e9-9d81-74d2e953301a.png)

(blue circle is the mousse).

Expected behavior:
same without groupby:
![image](https://user-images.githubusercontent.com/16716992/59122791-ee9ff380-895b-11e9-8689-3e068045b316.png)

Video/Screenshot link (optional):

**Comment by fmdl** [comment]
OPW #2031964

**Comment by Yenthe666** [comment]
@fmdl what is the state of the OPW?

**Comment by fmdl** [comment]
Close ...

**Comment by fmdl** [comment]
but it is not solve

**Comment by Yenthe666** [comment]
What was the feedback in the OPW? That it won't be fixed or is desired behavior I assume?

**Comment by fmdl** [comment]
The Odoo answer :

> Dear Florent,
> 
> Thank you for contacting Odoo Support.
> 
> I have discussed this with our Technical Department. I can confirm that this behavior is not desired but we can't consider it as a blocking issue. However, I have created feedback for our usability team in order to improve it for the next versions.
> 
> Thank you again for your feedback and do not hesitate to contact me for more related information.
> 
> Kind Regards,

**Comment by Yenthe666** [comment]
Okay that's fine, it happens more and more. If it is in the todo task list at Odoo it'll be handled eventually and we shouldn't keep Github issues open for those.
