### ISSUE TITLE
MTO Overprocess Error

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#34005]
Impacted versions: 12.0

Steps to reproduce:
Reproduced on Runbot Community like so.

- Have a reasonably advanced inventory setup (i.e. use UoM's, tracking, routes etc)
- Create a tracked product Apples with a UoM of kg and tracked by lot.
- Give it a Buy and MTO route.
- Select to invoice on delivered quantities. (This doesn't matter AFAIK but more realistic)
- Set a supplier 'Apple Supplier' at an arbitrary price.
- Create a sales order for 5kg of apples.
- Confirm Sales Order.
- Confirm Purchase Order.
- Receive in 6kg of apples under arbitrary lot number for that purchase.
- In delivery Order, open stock move and change qty done to 6kg
- Validate.
- Confirm overprocess.

Current behavior:
1kg is shipped and a backorder created for 5kg.
New draft Purchase Order created for 1kg of Apples.

Expected behavior:
6kg shipped and no backorder created.
No new purchase order.

Video/Screenshot link (optional):
opw 2008113
if you are fast, full runbot replication is here http://536343-12-0-0ebee5.runbot11.odoo.com/web?#id=154&action=826&model=sale.order&view_type=form&menu_id=555

**Comment by amoyaux** [comment]
@gdgellatly You should directly update the sale order, it will modify the linked purchase order. Or if you want to modify only the delivery you should create a new line with the over processed quantity. We know that it's not good at a usability point of view but we have some trouble to merge MTO and MTS moves.

**Comment by gdgellatly** [comment]
@amoyaux That makes zero sense. Sales doesn't know about received quantities and doesn't care. 

The person receiving the goods into stock doesn't have access to modify sales. Indeed it is none of their concern. They just got some stock in, they don't even know if it is linked to a sale or not. (And the actual use case is a great big truck, multiple times daily with tens of orders on it, every one of them a different weight to what was ordered, and maybe once a week is MTO). 

But you can't use 0 0 reordering rule here, because for 1, there already is a reordering rule for stock, and 2, the products are required to be individually tracked and assigned to a customer for legal/insurance reasons, and with all the other orders coming in it would be chaos.

Its not like this isn't a common use case. Many industries sell by weight but for many reasons cannot specify or deliver an exact quantity, e.g. in the apples example, nobody will cut an apple in half to make a weight, or livestock, or diamonds.

Or are you saying to do this after receiving the stock in? That might work. It will piss the client off hugely, but it is probably doable.

**Comment by gdgellatly** [comment]
@amoyaux Also even if it is impossible to fix, and it causes these errors, there needs to be a way to stop users inadvertently making this error. Some kind of block.
