### ISSUE TITLE
[7.0] "Reply-To" and "To (Partners)" fields not functioning on email templates

### ISSUE THREAD

**Issue by JaHicks** [odoo/odoo#3400]
The fields "Reply-To" and "To (Partners)" are not functioning despite being specified on an email template.  These have been tested specifically with the Invoice template, however, it may be that these are more general issues.

"To (Partners)" works with the "Send by Email" button, but does not work when using the send_mail() function in a server action (i.e. both Recipients and To are left blank).

"Reply-To" works when using the send_mail() function in a server action, but does not work with the "Send by Email" button (i.e. Reply-To is left blank).

The specific server action has the following python code:

<pre>
data_pool = self.pool.get('ir.model.data')
ids = data_pool.search(cr, uid, [('model', '=', 'email.template'), ('module', '=', 'account'), ('name', '=', 'email_template_edi_invoice')])
pool.get('email.template').send_mail(cr, uid, data_pool.browse(cr, uid, ids)[0].res_id, context['active_id'], context=context)
</pre>

**Comment by Yenthe666** [comment]
Hi @JaHicks,

This is actually the desired behaviour. As quoting from Olivier:

> It's the expected behavior. When posting a message on a SO/PO/.., replies should go to the document, nowhere else, otherwise you lose history and tracking. "Reply-To" on mail templates is meant to be used for mass-mailing purposes, not for direct posting on documents.
