### ISSUE TITLE
Group By - invisible issue

### ISSUE THREAD

**Issue by o2deepak** [odoo/odoo#34008]
Impacted versions: community 12.0

Steps to reproduce: Invisible not work in Group By

Current behavior: 

Expected behavior: invisible="context.get('type') in ('in_invoice','out_invoice')"

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That feature is not available in current framework for groups, so closing as won't fix.

**Comment by o2deepak** [comment]
@pedrobaeza Thank you so much to update.
