### ISSUE TITLE
[8.0/Master] [FIX] point_of_sale : issue while scanning EAN13 package

### ISSUE THREAD

**Issue by AdilHoumadi** [odoo/odoo#3401]
Looking for a product by EAN13 while using packaging

***Impacted versions:***

- 8.0 and above

***Steps to reproduce:***

first of all,  you need an Ean13 scanner in order to reproduce this bug.

1. Go on runbot and pick a v8.0 instance;
2. Sign in to the ERP (database using all modules);
3. Via this Menu you have to enable this option (Settings -> Configuration -> Warehouse -> Allow to define several packaging methods on products);
4. Pick up a product (iPad Mini as an example) and set a scannable EAN13, after that create a Packaging for this product and add an EAN13 to it;
5. Go to (point of sale Menu) and click on New Session or resume an old one;
6. Look for the product via the EAN13 (iPad Mini); you should flag the product in the backend to make it visible on the POS;
7. If we scan the product via EAN13 Barcode field, the product is added to the ticket but if we scan the package, we got an error.

***Current output:***

 - Get an error and the product is not added on the ticket

***Expected output:***
- We should be able to scan the package and the product should be listed on the ticket

***Solution:***

the problem is inside this function, product_id is not the right attibute of pack, you can to access to the id via product_tmpl_id
```javascript
point_of_sale/static/src/js/db.js
```

```javascript
get_product_by_ean13: function(ean13){
    if(this.product_by_ean13[ean13]){
        return this.product_by_ean13[ean13];
    }
    var pack = this.packagings_by_ean13[ean13];
    if(pack){
        return this.product_by_id[pack.product_id[0]];
    }
    return undefined;
},
```
The fix is :
```javascript
get_product_by_ean13: function(ean13){
    if(this.product_by_ean13[ean13]){
        return this.product_by_ean13[ean13];
    }
    var pack = this.packagings_by_ean13[ean13];
    if(pack){
        return this.product_by_id[pack.product_tmpl_id[0]];
    }
    return undefined;
},
```
![image](https://cloud.githubusercontent.com/assets/462805/4846315/05eebd9e-604b-11e4-9e28-d278b2177a9c.png)

**Comment by Yenthe666** [comment]
@Gorash and @fvdsn could you guys give your input on this one? Is this bug report still active or can it be closed?

**Comment by Gorash** [comment]
fvdsn was the lead developer on the project in v8, I just propose changes but I have not followed this issue. The project was taken over by @jorenvo he would know if this change in the next versions.
