### ISSUE TITLE
[12] BoM Structure & Cost prints wrong if there are variants

### ISSUE THREAD

**Issue by gr22** [odoo/odoo#34025]
**Impacted versions**: 12 CE

**Steps to reproduce:** You need to have a product with 2 or more variants. Create a BoM for variant1 and different BoM for variant2 then go to one of the BoM -> Structure & Cost and print a PDF.

**Current behavior:**
 The PDF contain a page for every variant not just the one you have open and the structure of all of them is the same (the active one)

**Expected behavior:**
There should be only the current variant printed or all of them but with the corresponding structure

**Comment by pedrobaeza** [comment]
I think the button is for template, not for variant itself.

**Comment by gr22** [comment]
Well, it doesn't matter in fact. The results are still wrong.

**Comment by sle-odoo** [comment]
closing since the linked pr is closed
