### ISSUE TITLE
Sales Team name example is missing a space

### ISSUE THREAD

**Issue by sharpelectronics** [odoo/odoo#34045]
Impacted versions: 12.0e

Steps to reproduce: CRM - Configuration - Sales Teams - Create

Current behavior: In the field for Sales Teams Name, there is a grey example that says "Salesteam name...".

Expected behavior: "Sales Team name..."

Video/Screenshot link (optional): 
![Annotation 2019-06-11 113648](https://user-images.githubusercontent.com/51717377/59295215-5d24d000-8c40-11e9-9a3c-d7a19b4b9513.png)

**Comment by pedrobaeza** [comment]
@mart-e what do you think about this change?

**Comment by Yenthe666** [comment]
IMP for master in a PR ;)

**Comment by mart-e** [comment]
As @Yenthe666 says :wink: can be changed in master, changing in stable would break the view translation

**Comment by Yenthe666** [comment]
I made a quick PR to resolve this and some comment messages.

**Comment by Yenthe666** [comment]
This has been handled in https://github.com/odoo/odoo/commit/ebb755a95d387be8fd79861f961067f8c6028aba for the upcoming V13.
