### ISSUE TITLE
Bug on address customer inrelation with invoice in Odoo (big) 8.0

### ISSUE THREAD

**Issue by oitsuki** [odoo/odoo#3404]
Hello,

Currently I write a webservice between my ecommerce platform and Odoo

Description
When I change a payment address during the payment process (new payment address) on my ecommerce platform, the payment address is write in hard inside database and the old address is not updated.

But in Odoo, this not the same thing, if  during the process payment, the customer change this payment address, all the invoice (new and old) has the new address.  If I change the address in Odoo,this is the same thing.

I think there is a big bug in odoo because the address has an impact on invoice and lot of element inside Odoo..

I tried to change just in Odoo, a customer address, all the invoice has been impacted, new and old invoice included the validate invoice. 

What the solution to resolve this problem, because it's important.

Thanks

**Comment by Yenthe666** [comment]
Hi @oitsuki ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
