### ISSUE TITLE
[12.0] Website module: unable to alter the home page template in xml code

### ISSUE THREAD

**Issue by KengneMabou** [odoo/odoo#34077]
Impacted versions: odoo 12 community and entreprise

Steps to reproduce:
create a basic module structure that depends on website module
create an xml file and put the following code:

```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <data noupdate="0">
     <template id="hackhomepage" name="hackhomepage" inherit_id="website.homepage" customize_show="True">
            <xpath expr="//div[@id='wrap']" position="replace">
                    <div id="wrap" class="oe_structure">
                          <div>Hello</div> 
                    </div>
            </xpath>
        </template>
    </data>
</odoo>
```

Install/update the module

Current behavior: Nothing happen... the home page is still blank

Expected behavior: Expected the display of 'Hello' on home page in the website

I have even try calling the template with <t t-call="website.homepage"> syntax but nothing still happen
Video/Screenshot link (optional):

**Comment by nhomar** [comment]
Recomendation.

1. Create your own **My Homepage**.
2. create a menu with the lower sequence.
3. Assign such menu to open your custom homepage.

Done..... the main homepage will be the one that you did.

Regards.
