### ISSUE TITLE
Malformed JSON kills bus

### ISSUE THREAD

**Issue by litnimax** [odoo/odoo#34080]
When /longpolling/poll is called with last=0 (first time polling) bus dispatcher sends all messages for the given channel.
But if there is a bad JSON message it fails:

```
barrier_odoo_panels | Traceback (most recent call last):
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
barrier_odoo_panels |     return super(JsonRequest, self)._handle_exception(exception)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
barrier_odoo_panels |     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
barrier_odoo_panels |     raise value
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
barrier_odoo_panels |     result = self._call_function(**self.params)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
barrier_odoo_panels |     return checked_call(self.db, *args, **kwargs)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
barrier_odoo_panels |     return f(dbname, *args, **kwargs)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
barrier_odoo_panels |     result = self.endpoint(*a, **kw)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
barrier_odoo_panels |     return self.method(*args, **kw)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
barrier_odoo_panels |     response = f(*args, **kw)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 42, in poll
barrier_odoo_panels |     return self._poll(request.db, channels, last, options)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/controllers/bus.py", line 32, in _poll
barrier_odoo_panels |     return super(MailChatController, self)._poll(dbname, channels, last, options)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/main.py", line 30, in _poll
barrier_odoo_panels |     return dispatch.poll(dbname, channels, last, options)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/models/bus.py", line 130, in poll
barrier_odoo_panels |     notifications = env['bus.bus'].poll(channels, last, options)
barrier_odoo_panels |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/models/bus.py", line 90, in poll
barrier_odoo_panels |     'message': json.loads(notif['message']),
barrier_odoo_panels |   File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
barrier_odoo_panels |     return _default_decoder.decode(s)
barrier_odoo_panels |   File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
barrier_odoo_panels |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
barrier_odoo_panels |   File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
barrier_odoo_panels |     obj, end = self.scan_once(s, idx)
barrier_odoo_panels | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

And there is no chance of getting over it as the client needs to know last id to skip the bad message.

To solve this I see 2 options:

* Remove bad JSON document
* Send message id in JSON error result so that client can handle the situation and re-poll using this id + 1.

I personally vote for the 1-nd one.

Also there could be a possibility to remove all bus messages for a given channel from the client side but bus.bus has no permission to do this. 

So currently the only exit from the situation is to wait until bus vacuum cron job will remove all messages that is actually not an option if your IoT box is using long polling.

**Comment by pedrobaeza** [comment]
But how to get a malformed JSON?

**Comment by litnimax** [comment]
Good question :-)
I work on message exchange between Odoo and another messaging system.
So I connect to postgres directly and add records to bus.bus can call notify imbus.
Now I think if only Odoo is used this cannot happen.
Close the ticket?
Thanks for your response.

**Comment by pedrobaeza** [comment]
Yes, if it's because some manipulation outside Odoo, it shouldn't be ironed that way.

**Comment by christophlsa** [comment]
I recently checked our odoo (v11) logs on live because some users reported that sometimes odoo shows that the connection is lost and I could find the same error message in the logs. And we didn't modified anything related to the bus.

The error doesn't happen so often so I couldn't find out yet how the message looks like and why the json is malformed. I will write here if I can find out something.

**Comment by litnimax** [comment]
As Pedro closed the ticket I posted it here - https://www.odoo.com/groups/technical-62/technical-83203675?mode=thread&date_begin=&date_end=

**Comment by christophlsa** [comment]
From my side I could find out that we did some html sanitising which broke the created messages in the bus. So it was more our problem.

But in general the code should maybe have a try-except for the json parsing. :)
