### ISSUE TITLE
Record rule "Personal Order" work on global but not work in group Sale/User: own documents only

### ISSUE THREAD

**Issue by congt80** [odoo/odoo#34131]
Impacted versions: 12

Steps to reproduce:
1. Enable group Sale/user setting "own documents only" have record rule "Personal order"
2. Create 2 user
3. User 1: create sale order 1
4. User 2: create sale order 2
Current behavior:
If inactive record rule "Personal order" in this group to global, this rule work, but if mark rule in this group it's not work
user 1 still see sale order of user 2 
user 2 still see sale order of user 1

Expected behavior:
user 1 cannot see sale order of user 2
user 2 cannot see sale order of user 1
Video/Screenshot link (optional):
![62382843_2330080910392907_1006919155145768960_o](https://user-images.githubusercontent.com/8214827/59500125-04b13500-8ec3-11e9-8360-8e2426695c5d.jpg)

**Comment by pedrobaeza** [comment]
Have you altered other record rules related to this model?

**Comment by congt80** [comment]
we have two add on but not relate to rule: lc_discount and lc_sale_base, please see detail as image
![image](https://user-images.githubusercontent.com/8214827/59502595-560ff300-8ec8-11e9-9878-a5265141a026.png)

**Comment by pedrobaeza** [comment]
"Expense Employee can read confirmed SO" is the rule that is avoiding the other one to act, as they are joined with OR.

@jem-odoo the rule you introduced in https://github.com/odoo/odoo/commit/751330a843f30298f50a479cba3d22b5ffaf6cb3#diff-ab673a6f76f07b1540845fe3df529ec8R8 is breaking the personal orders rule. Can you please check?

**Comment by jem-odoo** [comment]
The fix landed in 12.0 with https://github.com/odoo/odoo/commit/f8e41c6b00131bf387843c24d1003310cde92a5e

For this fix to be applied on existing databases, it will required a module (sale_expense) update, and manually desactivate the ir.rule "Expense Employee can read confirmed SO". 

Regards,

  jem

**Comment by pedrobaeza** [comment]
Thanks, Jérome!
