### ISSUE TITLE
[12.0] Journal creation with dedicated credit note sequence as Advisor user raises permission error

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#34153]
Impacted versions: 12.0

Steps to reproduce:
- As a regular user with Advisor permissions (not Admin) on accounting & Finance, create a new sale or purchase Journal
- Set the refund_sequence boolean to True
- Save record

Current behavior: Odoo throws an access error on ir.sequence.date_range model.

Expected behavior: Advisor permissions should allow the user to access that model in order to create the record.

After searching for a little bit, we came across this line:
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account.py#L705

The absence of sudo() on the creation might be the problem. Of course, granting that extra permission also works, but it feels like it's supposed to work out-of-the-box.

**Comment by sswapnesh** [comment]
Added Fix in https://github.com/odoo/odoo/pull/34157

**Comment by mart-e** [comment]
Could you please submit the full traceback? It is strange as it looks like all the calls to `._create_sequence` are already made with `sudo`
Are you sure your code is up to date?

**Comment by sswapnesh** [comment]
@mart-e  I could reproduce the Issue on http://638602-12-0-2ccf05.runbot28.odoo.com `Billing Manager `user.

When using "Dedicated Credit Sequence"
![Screenshot](https://user-images.githubusercontent.com/16624719/66042718-e1c29380-e53a-11e9-9ea2-fea6ce370a0d.png)

**Comment by mart-e** [comment]
@sswapnesh but a Billing user does not have the rights to create an accounting journal

**Comment by sswapnesh** [comment]
I was talking about Billing Manger
