### ISSUE TITLE
IoT box customer display when using SSL

### ISSUE THREAD

**Issue by dishdoctor** [odoo/odoo#34158]
Impacted versions: 12

Current behavior: 
odoo 12 community edition with SSL enabled and IoT v19.04. The IoT box connects to the pos session when using https://192.168.1.82 in the pos settings. The issue is that the HDMI output on the raspberry pi only shows up as white screen. but if I go to the IoT box site on a computer (https://192.168.1.182/point_of_sale/display) it shows the customer display with product images. can someone explain why it works when accessing it from a remote device, but directly connected HDMI monitor only shows white screen?

Images:

![pos settings](https://user-images.githubusercontent.com/38015071/59534226-ab91d300-8ebb-11e9-90f6-f1e66ae2d8ed.PNG)
![odoo](https://user-images.githubusercontent.com/38015071/59534240-b51b3b00-8ebb-11e9-88ad-fc03a9f42018.PNG)

(HDMI output from raspberry pi)
![tv](https://user-images.githubusercontent.com/38015071/59534246-b8162b80-8ebb-11e9-946d-9f3ce5068845.PNG)

(website display https://192.168.1.182/point_of_sale/display)

![display](https://user-images.githubusercontent.com/38015071/59534252-bcdadf80-8ebb-11e9-847f-383c49b8fbe7.PNG)

**Comment by pedrobaeza** [comment]
Not sure, but I would say because there's no direct display for this. This is web service application.

@switch87 can you confirm?

**Comment by dishdoctor** [comment]
I do have a display directly connected to the HDMI port in the pi, when connected to pos using https it shows white screen, when http it works fine, showing product photos and company logo.

**Comment by switch87** [comment]
Actually there is no need to put https in the POS config, so if it works without it is OK.

At the other hand, pure for the user-experience this is of course bad behavior, so I will investigate on it.

**Comment by dishdoctor** [comment]
It doesn’t work with just the IP address either just shows white screen with total and no product imaged on the display connected to the box

**Comment by switch87** [comment]
@dishdoctor I cannot reproduce this problem. With me it works fine.

Make sure you are on the latest version of Odoo 12.0. One problem I can think of is that the certificate of your Odoo server is not trusted and therefore is blocked by Firefox on the IoT box?

**Comment by dishdoctor** [comment]
I am on the latest version of both odoo and iot box. I have setup odoo server with valid ssl certificate from lets encrypt. 
I have tried using customer display on different servers with same results when pos is loaded over https I get white screen, product images disappear. If I load Nginx to open the pos only over http the product images load again.
I have added the iot box self signed certificate to my trusted certificates, still no success.

**Comment by switch87** [comment]
@dishdoctor we don't give support for non-bug related issues in community. If you have an enterprise subscription you can open an issue with our support team and give them access to the server to find the problem. I cannot help you any further with this issue.

**Comment by dishdoctor** [comment]
I have found another way to reproduce the problem I am having. if I load the customer display over web browsers (chrome and Firefox) the customer display is normal. however If I try to load the customer display using internet explorer, the screen turns white, the same screen that I get on the HDMI output on the IoT Box..


(pos loaded with valid ssl cert on Firefox)
![1](https://user-images.githubusercontent.com/38015071/59798630-939dc300-92b0-11e9-88d8-822f54796048.PNG)

![4](https://user-images.githubusercontent.com/38015071/59798668-ad3f0a80-92b0-11e9-8a59-3dd2e5eb429a.PNG)


(iot customer display loaded on chrome)
![2](https://user-images.githubusercontent.com/38015071/59798262-b5e31100-92af-11e9-9482-515968c5f61f.PNG)

(IoT customer display loaded on internet explorer.. Also shows this on IoT Box)
![3](https://user-images.githubusercontent.com/38015071/59798266-ba0f2e80-92af-11e9-885b-ea4df185aa6c.PNG)

**Comment by pedrobaeza** [comment]
AFAIK, Internet Explorer is not supported.

**Comment by switch87** [comment]
The IoT Box uses Firefox, but you could try finding out in the development tools console of Internet explorer what goes wrong. If you need further help you can try on the community forum: https://www.odoo.com/forum

**Comment by dishdoctor** [comment]
@switch87 
Hi I have finally figured out the problem I am having!
It seems the IoTBox's date and time is incorrect causing it to reject my valid ssl certificate. 
I am using the latest IoTBox image starting up with ethernet connected.. 

please investigate as to why the date and time is not being set on the raspberry pi 3+

![Screen Shot 2019-06-21 at 11 16 11 AM](https://user-images.githubusercontent.com/38015071/59932813-096f6f00-9416-11e9-9079-8b1957a51b2e.png)

(this is Firefox on the iotbox.. once I clicked on add exception to my odoo ssl site it now works!
I modified the RKiosk mode so I could see the navigation bar and browse to my odoo site on the box.. )

![IMG_2811](https://user-images.githubusercontent.com/38015071/59932635-9ebe3380-9415-11e9-99f9-3ca4957590e0.jpg)

**Comment by switch87** [comment]
@qle-odoo can you take a look at this?

**Comment by qle-odoo** [comment]
Can you try to change the date of your box ?
`sudo date -s "21 Jun 2019 21:24:44"`

**Comment by dishdoctor** [comment]
I tried sudo date -s "21 Jun 2019 21:24:44" then reboot
still says 02/04/19 on Firefox when trying to access any https site
tried sudo mount -o remount, ro / and thenv sudo date -s "21 Jun 2019 21:24:44"
no change.

**Comment by qle-odoo** [comment]
Don't reboot the box
And try the customer screen after change the date

**Comment by dishdoctor** [comment]
yes it works if I do that. but as soon as a reboot then it stops

**Comment by qle-odoo** [comment]
yes 
I know this issue
Next week we release a now IoT Box
Thank for your investigation

**Comment by dishdoctor** [comment]
thank you very much!!

**Comment by gregory-moka** [comment]
@dishdoctor : Hello, does this new version solved your problem ?
