### ISSUE TITLE
[V8.0] Inventory Data of Inventory Adjustment cannot be export/import 

### ISSUE THREAD

**Issue by u8621011** [odoo/odoo#3415]
2 possible issues about inventory adjustment import.(I still don't understand the inventory process of odoo8 wholly)
1. The Inventory Data Field cannot be seen in import-compatible field list.
2. After import the created stock.inventory csv which line_ids  are also list, the list entry would be deleted (or not imported).

**Comment by Yenthe666** [comment]
Hi @u8621011,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
