### ISSUE TITLE
l10n_es tax rate for P_IRPFT is not up to date

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#34161]
Impacted versions:
10, 11, 12
The actual rate for the Work Retentions in Spain is now 15% instead of 21%. It affects te code P_IRPFT
Find the actual rates in this link: 

https://www.agenciatributaria.es/AEAT.internet/Inicio/La_Agencia_Tributaria/Campanas/Retenciones/Cuadro_informativo_tipos_de_retencion_aplicables__2019_.shtml

**Comment by pedrobaeza** [comment]
Thanks for the link. It's interesting to keep that link documented somewhere in the module for future references. Do you plan to do a PR amending the percentage? What do you think about adding other retention types that are shown in the document?

**Comment by Yenthe666** [comment]
@pedrobaeza maybe you can make the PR as you're from Spain, right?

**Comment by pedrobaeza** [comment]
@jco-odoo I don't remember if we finally merged this during the merge sprint. Did we?

**Comment by pedrobaeza** [comment]
Please check #54914 for the patch

**Comment by pedrobaeza** [comment]
Closing as merged.
