### ISSUE TITLE
[12.0] Option "I have a promo code" is visible on community while being ENT feature

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#34183]
Impacted versions: 12.0

Steps to reproduce:
1. Login to the latest Odoo 12.0 community on runbot .
2. Go to the shop and add a product to your cart

Current behavior:
You will see the option "I have a promo code"
![image](https://user-images.githubusercontent.com/6352350/59602763-e38d5600-9107-11e9-8928-533ad6e91bfa.png)

This comes from
https://github.com/odoo/odoo/blob/cfa1e101e2c98313e6205719bfe34426f39a1b57/addons/website_sale/views/templates.xml#L1568
Expected behavior:
The option is not shown on community / without the app being installed as it is an enterprise feature:
![image](https://user-images.githubusercontent.com/6352350/59602846-22231080-9108-11e9-9a56-106997f2b6a8.png)

**Comment by Yenthe666** [comment]
@JKE-be for you guys.

**Comment by JKE-be** [comment]
can be used with code field on pricelist.

**Comment by Yenthe666** [comment]
Hah, today I learned. I don't touch the community version a lot :) thanks!
