### ISSUE TITLE
[Whislist] Replace fields.Date.today() by fields.Date.context_today()

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#34194]
**Impacted versions:**
all
**Steps to reproduce:**
On countries with time zone < 0(Ecuador for example is UTC-5) after 19:00(+5 = 00:00), function `fields.Date.today` returned next day, it is problematic when is used on fields type Date. instead must be use `fields.Date.context_today`

Some examples: PR #22651 #25342 (now worked fine) #34193

search on *.py files on server get following result
![image](https://user-images.githubusercontent.com/7775116/59647695-ca090000-9141-11e9-8410-c016ee14aaee.png)

Is possible replace all occurrences?, 
I can create a PR for replace all ocurrences, but only where use is for fields Date, on fields Datetime not problem.

CC: @mart-e

**Comment by Elkasitu** [comment]
No, there are cases were we want a `Date` field to be UTC (`fields.Date.today`) and there are cases where we want it to be in the timezone of the end user (`fields.Date.context_today`), they each have their use cases and it's up to the developer to know which one to use in which scenario

**Comment by celm1990** [comment]
@Elkasitu sorry for confusion, but I meant: _replace ocurrences where use is for fields Date, no replace on fields Datetime(it work fine)_
