### ISSUE TITLE
The behaviour of proposing partner's default pricelist is changed

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#34195]
Impacted versions:
v10, v11

Steps to reproduce:
1. Create a new partner

Current behavior:
"Sales Price" is proposed as the pricelist of the partner by default.
 
Expected behavior (Previous behaviour):
Previously, the pricelist with the highest sequence is proposed.

**Comment by TimLai125** [comment]
I think the behaviour is changed after this commit: https://github.com/odoo/odoo/commit/917127ff705f305f5d5252d29ad780b96aec65bb#diff-66d6a43551b9b9ed55015b6def049903

Previously, we can adjust the default pricelist by changing the sequence of the pricelists.
Now we need to activate the debug mode to access the `ir.property` records (Company Properties) and change the `value` of the `property_product_pricelist` (Please let me know if there is another way to do it).

The commit is causing the signup portal users having a different pricelist after the commit if the internal users do not know how to change the default pricelist. They will need to change the pricelist manually for every new portal user.

**Comment by pedrobaeza** [comment]
The mentioned commit if for 12.0, not 10.0 or 11.0

**Comment by yostashiro** [comment]
@pedrobaeza The commit is for 10.0 as far as I can see.  (I'm not sure how Github shows the branch 12.0 with the commit message, though...)

**Comment by pedrobaeza** [comment]
OK, let's see if @dbo-odoo knows something about this. I haven't been able to look myself (I'm on holidays).

**Comment by sswapnesh** [comment]
Seems in v10 from PR https://github.com/odoo/odoo/pull/29689

**Comment by dbo-odoo** [comment]
Hi @TimLai125 ,

Could you be more specific in the description of the problem?

When creating a new partner from Sales > Orders > Customers in v11, my tests seem to indicate that it behaves as expected given the old code before the mentioned revision:
-> search for pricelist explicitely set for that partner (in case of new partner, none found)
-> search for pricelist applying to the country for that partner based on pricelist country groups (with demo data, this means that a partner in belgium will get the Benelux pricelist, a partner in France or another EU country will get the EUR pricelist)
-> if no country on the partner or if the seach for a country-specific pricelist, then find the first pricelist with no country group (in demo, Public Pricelist)
-> if none found, check for the default property value (the one you talked about that you can set in debug)
-> if none found, take the first pricelist it finds

When reading the diff of the mentioned commit, I don't see how this would be different. I just tested with several countries on new partners on runbot by changing the pricelist order and it seems to work... (cfr video [here](https://youtu.be/sOHTP2JA1os))

The ordering of pricelists for the search was not changed, so the sequence is still applying correctly in my tests.

If you have exact steps and/or a video, it would help clarify what you describe :) Make sure to take country groups into account as well.

I did not encounter the issue in a clean v10 on my machine either.



thx!

**Comment by TimLai125** [comment]
@dbo-odoo Thank you for the comment. Please check the video below, I pull "USD" to the top in the pricelists tree view but the "Your Company" pricelist is still being proposed to the new customer.
https://drive.google.com/file/d/1-JGH6enO_8Yy46Id3aMDShhlGz64soic/view

-> if none found, check for the default property value (the one you talked about that you can set in debug)
-> if none found, take the first pricelist it finds

There seems to be a default property value in the begining therefore the last statement will not be reached unless someone deletes the default property value which I think it is not a good design.

**Comment by dbo-odoo** [comment]
I believe this behaviour comes from this particular piece of code: https://github.com/odoo/odoo/blob/10.0/addons/product/models/res_company.py

I'm not here to discuss the goodness of the design though; if this has been the behaviour for a few years then I certainly won't change it in a stable version (cfr our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean)). I would revert it back to its original behaviour if it had been altered recently as a side-effect of another change (these things happen), but given the code I found this doesn't seem to be the case.

Unless you can show me that this was changed recently, I'm afraid I'll close the issue - I plan on investigating the behaviour in the master branch and possibly change it there for Odoo 13 (I do agree that it's not a really good experience), that's something I'll have a look at internally.
