### ISSUE TITLE
[V8.0] Destination Address field of Stock Move be wrong

### ISSUE THREAD

**Issue by u8621011** [odoo/odoo#3420]
After the goods transferd of purchase order, the  destination address of corresponding  stock move will have wrong value(be set to partner)

**Comment by Yenthe666** [comment]
Hi @u8621011,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
