### ISSUE TITLE
[Docs] Postgres version compatibility should be added to odoo/doc/setup/install.rst 

### ISSUE THREAD

**Issue by jleaders** [odoo/odoo#34226]
Postgres version compatibility should be mentioned in the installation instructions where it mentions Postgres: [odoo/doc/setup/install.rst
](https://www.odoo.com/documentation/11.0/setup/install.html)
Are Postgres 9.3, 9.4, 10.0, etc all compatible?

**Comment by jleaders** [comment]
I just tested, Postgres 10.0 does NOT work on Odoo 11.0, it needs to be 9.4

**Comment by jleaders** [comment]
PR for convenience https://github.com/odoo/odoo/pull/34227

**Comment by gdgellatly** [comment]
Sure it does. I've got a number of v11 installs on pg10

**Comment by pedrobaeza** [comment]
Even in PG10, but I agree it can be noted on documentation.

**Comment by jleaders** [comment]
Ah, then the error I was getting was probably due to 9.3? At one point I had 10.0 and 9.3 on my box, and it was throwing errors

**Comment by pedrobaeza** [comment]
I can't say, but it can be

**Comment by jleaders** [comment]
I don't know why mine was failing, but I had PG10 and was getting errors, and all i did for a fix was downgrade to PG9.4, no other changes to my knowledge

**Comment by Yenthe666** [comment]
We've got multiple Odoo 11 instances running with PG 10+ too so I can confirm it works fine. I guess we can add some documentation for preferred versions though.

**Comment by etlweather** [comment]
Odoo 12 does not seem to work with Postgres 9.4. Would be nice to have that noted on this page.

```
2019-07-22 21:26:33,907 1 ERROR test odoo.sql_db: bad query: b"\n                INSERT INTO ir_model_data (module, name, model, res_id, noupdate, date_init, date_update)\n
            VALUES ('base', 'field_base__id', 'ir.model.fields', 1, false, now() at time zone 'UTC', now() at time zone 'UTC'), ('base', 'field_base__display_name', 'ir.model.fields', 2, false, now() at time zone 'UTC', now() at time zone 'UTC'), ('base', 'field_base____last_update', 'ir.model.fields', 3, false, now() at time zone 'UTC', now() at time zone 'UTC')\n                ON CONFLICT (module, name)\n                DO UPDATE SET date_update=(now() at time zone 'UTC') \n            "
ERROR: syntax error at or near "ON"
LINE 4:                 ON CONFLICT (module, name)
                        ^

2019-07-22 21:26:33,907 1 ERROR test odoo.addons.base.models.ir_model: Failed to insert ir_model_data
('base', 'field_base__id', 'ir.model.fields', 1, False)
('base', 'field_base__display_name', 'ir.model.fields', 2, False)
('base', 'field_base____last_update', 'ir.model.fields', 3, False)
2019-07-22 21:26:33,910 1 WARNING test odoo.modules.loading: Transient module states were reset
2019-07-22 21:26:33,914 1 ERROR test odoo.modules.registry: Failed to load registry
```

**Comment by alexsegura** [comment]
Just had the same problem as @etlweather, `ON CONFLICT` is only available starting at Postgres 9.5

**Comment by mart-e** [comment]
Postgresql 9.5 is the minimum since Odoo 12.0 and should work with all the upper versions of postgresql. We are adding a bit of doc at #58554 but having the latest version of postgresql does help for the performances (if you are still on 9.5 you should really consider upgrading).

**Comment by Yenthe666** [comment]
Is postgreSQL v13 officially supported too?
