### ISSUE TITLE
[Feature Request] Support root selector in QWeb template

### ISSUE THREAD

**Issue by langbamit** [odoo/odoo#34229]
Now it impossible to do something like this:
```xml
<!-- Simple template -->
<header t-name="MenuHeader">
</header>

<!-- extend template -->
<t t-extend="MenuHeader">
    <t t-jquery="header" t-operation="whatever">
        <!--- Do something --->
    <t/>
</t>
```
Suggest:
Maybe change [this line](https://github.com/odoo/odoo/blob/12.0/addons/web/static/lib/qweb/qweb2.js#L499) to
```js
target = jQuery(jquery, template_dest).addBack(jquery);
``

**Comment by pedrobaeza** [comment]
QWeb uses other mechanism for selecting elements through xpath, not through jQuery selectors, and it's not expected to implement this option as not needed. Why do you want to duplicate functionality?

**Comment by langbamit** [comment]
It was my fault. I mean client-side QWeb template (using qweb2.js), not server-side QWeb.
My problem was I can't add class (other attributes also) to my header tag in MenuHeader template when using `extend` (not js please)

**Comment by pedrobaeza** [comment]
AFAIK, there's `t-extend` directive for these things.

**Comment by Yenthe666** [comment]
Yep, `t-extend` for the win there. Closing as I don't see anything to be added at this point.
