### ISSUE TITLE
Field in sale.order.line doesn't exist

### ISSUE THREAD

**Issue by kevinpre** [odoo/odoo#34233]
Impacted versions: 12.0

The order_lines_layouted () function in the sale.order module refers to the layout_category_id field in sale.order.line which in Odoo 12 no longer exists (line 732 of sale.py for sale module). This causes problems if the function is used for PDF reporting.

**Comment by Feyensv** [comment]
Indeed, the field doesn't exist anymore (and the model it was referring neither) but this function isn't used anymore in odoo codebase.  It won't cause errors unless a custo/third party module use it.  It could be removed.

**Comment by pedrobaeza** [comment]
That is a code leftover, but as said, not being used on standard code means no issue at all. It can be misleading to find a method, and not being able to use it, but you must simply not use it. You can propose a PR for removing it though.

Closing by the reasons above.
