### ISSUE TITLE
Employee PIN is visible to all by custom grouping

### ISSUE THREAD

**Issue by spilymp** [odoo/odoo#34231]
**Impacted versions:**
Tested with 11.0, 12.0 and 13.0alpha1 community

**Steps to reproduce:**
- Install App Attendance
- Activate PIN for Attendances
- Goto App Attendance --> Manage Attendances --> Kiosk Mode
- Goto select Employee
- Group By --> Add Custom Group --> PIN

**Current behavior:**
PINs for all employee are visible as group

**Expected behavior:**
PINs should not be visible for all employee

**Comment by Yenthe666** [comment]
@switch87 this one is for you and it is a rather important one. I've checked this and it is in fact true, all PIN's are open for grabbing by default:
![image](https://user-images.githubusercontent.com/6352350/60399029-2c5cfa00-9b5f-11e9-93a5-caa8fd914134.png)

**Comment by Yenthe666** [comment]
It is also questionable if this one shouldn't be reported as a security issue honestly.. CC @odony

**Comment by nhomar** [comment]
**cat dying here**

**Comment by alexander-heyber-manatec** [comment]
No one interested in closing such an security issue? By this, every one in a company using odoo time tracking in kiosk mode is availabe to see all PINs of every employee..

**Comment by switch87** [comment]
@alexander-heyber-manatec @spilymp I opened an internal task for it. We will keep you updated.

https://www.odoo.com/web#id=2079330&action=333&active_id=49&model=project.task&view_type=form&menu_id=4720

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/46aa4cd9fe1579fc0929d5d49c38577e18d61649
