### ISSUE TITLE
Empty inbox after installing Website module

### ISSUE THREAD

**Issue by sbd5674** [odoo/odoo#34240]
Impacted versions: 11

Steps to reproduce:
Inbox not empty before install website module, but after install this module all messages will go to archived, even new messages will not be showing in inbox.
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
I just checked on runbot 11.0 both CE and EE and I was not able to reproduce your error.
Admin and Demo users both have X unread messages without website installed. After installing website, they both have their unread X messages.

Could you please reproduce the error on runbot so we can qualify this as a bug and start investigating/fixing it?
Such a bug in 11.0 should have been detected sooner, are you sure you don't use any third party code?

Thanks

**Comment by sbd5674** [comment]
Hi rdeodoo, thanks for your response,
I checked to reproduce the problem on runbot, I select a "base" database, I installed first CRM, website and Live chat , inbox still display unread notifications but the notification counter is not correct.
For the version that I installed on my local machine using Ubuntu 16.04 and install  odoo 11.0 CE from source (git clone https://www.github.com/odoo/odoo --depth 1 --branch 11.0 --single-branch)
I faced the problem of marking all notifications as read.
Mybe it's a problem of odoo version or configuration problem.

Thanks

**Comment by rdeodoo** [comment]
I must miss something, since I can't reproduce it, could you please check [this video](https://drive.google.com/file/d/1M4XQn91Jcbxg_9rBRKaeKfelXqSMxYQu/view) where I reproduce your flow on runbot Odoo 11.0 CE.
The counter shows 21 unread messages and I can indeed count 21 messages in the list.

**Comment by sbd5674** [comment]
I checked from database table mail_message_res_partner_needaction_rel that field res_partner_id is changed from 3 (admin) to 6 (demo user) and is_read field is changed to true that's why old messages didn't display in admin inbox.

**Comment by rdeodoo** [comment]
I will need a clear step by step to reproduce. I tried to reproduce your flow on runbot (see my last message for the video link) and it worked fine.

Could you please tell me what you did differently that me on the video, where I tried to reproduce the flow you described?
