### ISSUE TITLE
erase incoming email addresses

### ISSUE THREAD

**Issue by hugo49** [odoo/odoo#34251]
Impacted versions: 12

I am trying to erase all incoming email addresses in odoo. There is one left and I can not delete it. The web interface runs for half an hour and nothing more, the email address is still there.
The mail process is working, I can not make changes in the modules because the system is busy (24/24). I restarted odoo, the server several times, no change. 

How can I delete this email address?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
