### ISSUE TITLE
Timesheet Entries Project Report

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#34254]
Impacted versions: 11 and 12

Steps to reproduce: odoo runbot
Projects, Research & Development, (3 dots) Timesheets, Select All, Print, Timesheet Entries

Current behavior:
![image](https://user-images.githubusercontent.com/11006126/59797830-19bd0800-92b7-11e9-8385-f1bc9fd408bf.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/11006126/59798053-99e36d80-92b7-11e9-9a1a-b10791f1585d.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The report is for the selected timesheets (coming from the project), but it's not a specialized project report, so the title is not expected.

Closing this as won't fix.

**Comment by nicomacr** [comment]
Hi @pedrobaeza , I understand your point with respect to the report, but it would be better if you listed the name of the project of which the timesheets belong.

**Comment by SBollatti** [comment]
Pedro
When serverals entries from diferents projects, "timesheet entries" report in Timesheet module shows:
![image](https://user-images.githubusercontent.com/11006126/59965514-9d5c3c00-94e5-11e9-8a68-43f6cf2d028a.png)
But, when to report a "Project consumed time" asked from CEO, Tittle is needed do diferenciate with others Projects because shows no Project/Task column like the issue i'd reported.
Expecting your point of view for this case.

**Comment by pedrobaeza** [comment]
OK, I get your point, but not sure this will be changed in stable. Any way, I reopen and ask @jem-odoo for his opinion about this.

**Comment by SBollatti** [comment]
@jem-odoo  Jerome, waiting for your point of view / opinion about this.
Regards
Seba
