### ISSUE TITLE
Unpublish one Slider cause whole Channel 403: Forbidden for public user

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#34271]
I unpublished one slider under a channel, when I visit the channel as public user, It raise 403: Forbidden error.
Impacted versions: 12

Steps to reproduce:
For odoo runbot with domo data, we simple open one slide under Public Channel. I simply click the button Unpublished on top right so that I can unpublish the slide. It looks no difference with admin logged in. But when I visit the public channel as public user,  It raise 403: Forbidden error.

Expected behavior:
After admin unpublished one slide, the other slides under the same channel should be visible.

**Comment by rdeodoo** [comment]
I think you are unpublishing the `featured slide` from the channel, which inevitably makes the channel page 403 forbiden.

I just had a look, and indeed if I unpublished the featured slide, the channel page becomes 403, but any other slide can be unpublished without causing side effects.

Can you confirm that's the channel you were unpublishing?

**Comment by frankmiao2015** [comment]
Yes, You are Right! I simply tried the first one which is the featured slide. But what if we really need to unpublished the featured slide. There seems no way to switch the featured slider or I just did not find the button. Thank you!

**Comment by rdeodoo** [comment]
You will find the featured slide option under the channel form view, under website.
![Screenshot from 2019-07-02 10-34-31](https://user-images.githubusercontent.com/30048408/60497695-a7382900-9cb5-11e9-9251-d4bc0f5d0610.png)
