### ISSUE TITLE
[11.0] website_editor: image size in forum post cannot be adjusted

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#34288]
Impacted versions:
11.0

Steps to reproduce:
1. Reply to any post in website forum.
2. Add two images to the reply.
3. Adjust one of the image size to 25%.

Current behavior:
Two images are displayed in the same size. Besides, the image is not resized when user access the page with mobile.

Expected behavior:
One of the images should be smaller as the size is adjusted and the image should be re-sized responsively.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1nJAwkRDQ5rrGenM_ZF0pk63mEIaiNGu9/view
![image](https://user-images.githubusercontent.com/27185427/59901827-12206f00-942f-11e9-81a8-d4e71184c1d6.png)

**Comment by TimLai125** [comment]
The issue is probably caused by the resizing css is not applying to the image. I suspect there is soemthing need to be fixed with the `web_editor` module?

e.g.
https://github.com/odoo/odoo/blame/fef49061ead4a437bac922d9d32270f76addd014/addons/web_editor/static/src/js/editor/rte.summernote.js#L303
https://github.com/odoo/odoo/blame/8f4b98e67fe49516c0c830524de351db67c58357/addons/web_editor/static/lib/summernote/src/js/Renderer.js#L423-L427

@gorash @qsm-odoo can I have some quick comments on this issue?

**Comment by JKE-be** [comment]
V11 is no more supported.
Please open new issue if bug is still present in v12

Thank you

**Comment by JKE-be** [comment]
Since you rename the thread 15 days ago, maybe you can confirm and just rename to 13.0 ?

Was thinking that it was an outdated issue

**Comment by Yenthe666** [comment]
why you think it is now for V13 Jérémy?
