### ISSUE TITLE
payment term "Explanation for Customer" not printed on invoice

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#3428]
Example:
payment term = "my intern text"
Explanation for Customer = 250% prepayment, rest 30 days after delivery"

Result
Payment Term = "my intern text"

Expected Result
Payment Term = 50% prepayment, rest 30 days after delivery

**Comment by Yenthe666** [comment]
Hi @ferdiga ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: You could add this with custom development too. 😉 

Regards,
Yenthe
