### ISSUE TITLE
Create backorder can not be completed due to security restrictions when transfer was created by Odoobot 

### ISSUE THREAD

**Issue by congt80** [odoo/odoo#34286]
Impacted versions: 12

Steps to reproduce:
1. Set record rule on Transfer Object: 
1.1. Personal Transfer: [('create_uid', '=', user.id)]
1.2. All Internal Transfer for Stores: [('picking_type_id.code', '=', 'internal'),
('location_id.location_id.name', 'not in', ['WH002','WH003','WH004','WH005','WH007','WH008','WH009','WH010','WH011','WH012'])]
1.3. Outgoing Transfer Store: ['&',('location_id.location_id.name', '=', 'WH001'),('create_uid.name', '=ilike', 'Odoobot')]
1.4. All State Stock Move: [('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available']),('picking_type_id.code', 'not in', ['incoming','outgoing'])]
1.5. stock_picking multi-company: ['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]
1.6. Portal Follower Pickings in Group User type/Portal: ['|', '|', ('message_partner_ids', 'in', [user.partner_id.id]), ('partner_id', '=', user.partner_id.id), ('sale_id.partner_id', '=', user.partner_id.id)]

2. Set record rule on Warehouse Object:
Stock Warehouse WH001: [('id', '=', 202)]
Stock Warehouse WH010: [('id','=', 201)]

3. Create Group Inventory/WH001 with Record Rules above

4. Create Routes for WH001 with Action: Pull From, Operation type: Internal Transfer, Move Supply Method: Take from Stock: Source Location: WH010/001, Destination Location: WH001/001

5. Create User A, set in Group Inventory/WH001

6. An Internal Transfer was created by Routes with creator is Odoobot

7. User A validate this internal transfer and create backorder because "You have processed less products than the initial demand. "

Current behavior:
User A cannot create backorder

Odoo Server Error - Access error
"The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: stock.picking, Operation: read)"

Expected behavior:
User A can create backorder

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/8214827/59856191-9ed01c00-93a0-11e9-9bce-8cb29f114a13.png)

**Comment by sswapnesh** [comment]
> 1.1. Personal Transfer: [('create_uid', '=', user.id)]

Isn't is because of  this ?

**Comment by congt80** [comment]
Yes, but I add record rule 

1.7. Create Transfer by Odoobot:  [('create_uid.name', '=ilike', 'Odoobot')]
It's still not work

**Comment by congt80** [comment]
Others
1.2. All Internal Transfer for Stores: [('picking_type_id.code', '=', 'internal'),
('location_id.location_id.name', 'not in', ['WH002','WH003','WH004','WH005','WH007','WH008','WH009','WH010','WH011','WH012'])]
User A can see this transfer but why cannot create backorder?

**Comment by sswapnesh** [comment]
It might be because of one existing Record rule.

**Comment by congt80** [comment]
I checked many ways:
If I using
['|', ('create_uid', '=', user.id),('create_uid.name', '=ilike', 'Odoobot')]
['|', ('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available']),('picking_type_id.code', 'not in', ['incoming','outgoing'])]
it's work
This way is not meet our requirements for users
and if I using
['&', ('create_uid', '=', user.id),('create_uid.name', '=ilike', 'Odoobot')]
['&', ('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available']),('picking_type_id.code', 'not in', ['incoming','outgoing'])]
it's not work
I think have problem with '&' 2 domain in Odoo, can you advise?
Thanks

**Comment by sswapnesh** [comment]
Backorder functionality works well out of the Box on Runbot. (With Admin account)

Picking : http://545484-12-0-811471.runbot15.odoo.com/web?debug=#id=392&action=395&active_id=2&model=stock.picking&view_type=form&menu_id=281

Backorder is created: http://545484-12-0-811471.runbot15.odoo.com/web?debug=#id=393&model=stock.picking&view_type=form&menu_id=281

I couldn't help you more as this because of Invalid/Wrong domains you have added.

Cc: @pedrobaeza

**Comment by congt80** [comment]
Backorder also work well with normal record rule in our database
In this case, rule is quite complicate, it's have issue when we change 'done_quantity' in "move_line_ids" please see detail as image
I checked:
some kind of rule as
['|',('picking_type_id.name', '=ilike', 'Internal'),('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available'])]
or
['|','|',('picking_type_id.code', '=', 'internal'),
('location_id.location_id.name', 'not in', ['WH002','WH003','WH004','WH005','WH007','WH008','QM009','WH010','WH011','WH012']),
('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available'])]
or
['|',('picking_type_id.name', '=ilike', 'Internal'),('create_uid.name', '=ilike', 'Odoobot')]
it's work
but
['&',('picking_type_id.name', '=ilike', 'Internal'),('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available'])]
or
['&','&',('picking_type_id.code', '=', 'internal'),
('location_id.location_id.name', 'not in', ['WH002','WH003','WH004','WH005','WH007','WH008','QM009','WH010','WH011','WH012']),
('state', 'in', ['draft', 'waitting', 'confirmed', 'assigned', 'done', 'cancel', 'partially_available'])]
or
['&',('picking_type_id.name', '=ilike', 'Internal'),('create_uid.name', '=ilike', 'Odoobot')]
it'not work
we guess '&' have error
![image](https://user-images.githubusercontent.com/8214827/59965044-73ca0180-9533-11e9-9ab0-e7220740fd3a.png)
![image](https://user-images.githubusercontent.com/8214827/59965103-15e9e980-9534-11e9-95c5-69b444776f26.png)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
