### ISSUE TITLE
[12] website_sale: View Sale Order button with multi-website use web.base.url domain

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#34309]
Impacted versions: 12.0
I use multi website for eCommerce. When the portal customer place an order on  website B, he will receive an order confirmation email. There is a button "View Sale Order" in the email which redirect the link to website A which I find is the web.base.url. 
Thanks.

**Comment by rdeodoo** [comment]
Are you able to reproduce the error on runbot?
This kind of issue should have been solved a few time ago.

**Comment by frankmiao2015** [comment]
@rdeodoo Yes, I just reproduced it in odoo runbot. Please you can try this one.

http://548271-12-0-044c5c.runbot23.odoo.com

I did the following steps:
1. I added my own SMTP outgoing email.
2. Since I have no idea how to assign different domain for odoo runbot, I did a freeze to the web.base.url(web.base.url.freeze: True). And changed the web.base.url to something else(127.0.0.1:8069). In this way, we will know if the View Order button redirect to domain (http://548271-12-0-044c5c.runbot23.odoo.com) or web.base.url(127.0.0.1:8069)
3. I enabled portal signup under website setting.
4. I logout as admin and placed an order with another email of mine and received the order confirmation.
5. I click the View Sale Order button in the email. It redirect the link to 127.0.0.1:8069 which is the web.base.url.

I am serious user for multi-websites function. I really doubts there is many others using the eCommerce for multi website function.

Thank you!

**Comment by rdeodoo** [comment]
> Since I have no idea how to assign different domain for odoo runbot,

You can add `-all` (or `-base`) on the runbot URL just before the `.runbot` part. You will land on the same runbot but with another domain and session.
Eg `http://548873-master-c80b53-all.runbot24.odoo.com`
That way you can have 2 website with different domain on a same runbot/instance.

Anyway, about your issue, this kind of problem had been fixed previously with c1be1993f9b but the example you mention still needed to use that fix.

I will let you know once the fix is done and merged.

Thank you for reporting the issue.

**Comment by frankmiao2015** [comment]
@rdeodoo Thank you for working on this. Just want you know that beside the View Order button, there is also a company logo on the right of the button. I am aware of that the odoo core code do not have website logo function. But OCA have an module website_logo for that. The point is that at least you should let us change the company logo in the template. But for now, it is hard coded same as the view order button.

Thank you.

**Comment by rdeodoo** [comment]
>  I am aware of that the odoo core code do not have website logo function.

We are working on this and a improvement should be merged pretty soon in master to allow a different logo for the website

> The point is that at least you should let us change the company logo in the template. But for now, it is hard coded same as the view order button.

I reported your feedback on the website logo task :wink:
