### ISSUE TITLE
allow to create the Swiss federally mandated electronic bills

### ISSUE THREAD

**Issue by ralfhauser** [odoo/odoo#3430]
https://www.news.admin.ch/message/index.html?lang=fr&msg-id=54757

this would be great - and probably make us a paying openERP user

**Comment by Yenthe666** [comment]
Hi @ralfhauser,

Thank you for your suggestion and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
At this point Odoo is relooking at all accountings/localisations so if somebody still wants this it should pop up.

Regards,
Yenthe
