### ISSUE TITLE
[12] IotBox RuntimeError("cannot set daemon status of active thread")

### ISSUE THREAD

**Issue by rachmataditiya** [odoo/odoo#34313]
Impacted versions:
12 Community, 12 Enterprise

Steps to reproduce:
connect printer and run 
./odoo-bin --load=web,hw_proxy,hw_posbox_homepage,hw_scale,hw_scanner,hw_escpos

Current behavior:
RuntimeError("cannot set daemon status of active thread")
also
usb.core.USBError: [Errno 110] Operation timed out
Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/32624220/59976014-142e2d80-95e9-11e9-8f9d-8d8b92c393dc.png)
![image](https://user-images.githubusercontent.com/32624220/59976036-56576f00-95e9-11e9-922f-ef36a45d1514.png)

![image](https://user-images.githubusercontent.com/32624220/59976116-45f3c400-95ea-11e9-8f42-767ba41369ca.png)
pyusb version
![image](https://user-images.githubusercontent.com/32624220/59976172-e1853480-95ea-11e9-89d8-86bd8697b442.png)

**Comment by rachmataditiya** [comment]
Fyi: I Tried python 3.5, 3.7 just the same

**Comment by pedrobaeza** [comment]
This is a problem with your setup, where USB times out, but nothing with Odoo itself, so closing. 
Try to ask for help on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by xabispacebiker** [comment]
I had the same problem, in my case it was some settings in odoo.conf.. I am not sure which one exactly, but after commenting them out it stop happening.

#workers = 3
#limit_memory_hard = 1053893154
#limit_memory_soft = 843114523
#limit_request = 8192
#limit_time_cpu = 120
#limit_time_real = 180
#max_cron_threads = 2
