### ISSUE TITLE
Payment dates on Invoice reports not displayed in localized format

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#34317]
Impacted versions:
12.0

Steps to reproduce:
Configure Odoo to use French language (with date format like 24/06/2019)
Generate report for a paid invoice

Current behavior:
Payment dates are shown in english format (2019-06-24) when all other dates are in the expected format (24/06/2019).
The payment dates on invoice form are also displayed in expected format, the only issue being on reports.

Expected behavior:
Display payment dates on invoice reports in localized format

Screenshot :
![image](https://user-images.githubusercontent.com/30716308/60001344-96106c00-9666-11e9-889b-7895150fcdf0.png)

**Comment by qdp-odoo** [comment]
fixed in v12.0 at revision https://github.com/odoo/odoo/commit/fdbabfdc59d2d8deb62d08c7bd132a93a5f2f738

thanks for the contribution @remi-filament
