### ISSUE TITLE
Meetings with wrong date/time format for pt-PT

### ISSUE THREAD

**Issue by andredasilvapinto** [odoo/odoo#3431]
It should be `yyyy/MM/dd HH:mm` not `MM/dd/yyyy hh:mm aa`

**Comment by Yenthe666** [comment]
Hi @andredasilvapinto,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
