### ISSUE TITLE
[12] Required attribute doesn't work when Radio widget is used

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#34311]
Impacted versions: 12 (CE+EE)

Steps to reproduce: Add field selection field  (required=1) and apply Radio widget
![screenshot-545484-12-0-811471 runbot15 odoo com-2019 06 22-17-49-48](https://user-images.githubusercontent.com/16624719/59963838-428f0880-9516-11e9-8ce2-653011eee74f.jpg)

Current behavior: Field is not required (Record is saved)
![screenshot-545484-12-0-811471 runbot15 odoo com-2019 06 22-17-52-18](https://user-images.githubusercontent.com/16624719/59963867-841fb380-9516-11e9-8fdb-baa671463501.jpg)

Expected behavior: It should be required.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
You're right and it is also a bug in V13. I'm creating an OPW for this one as one of my customers actually has this in production and I've never noticed the field not being enforced :) OPW `2166454`

**Comment by Yenthe666** [comment]
Official feedback from Odoo:

> Hello,
Thank you for your patience as I have received additional input on this behavior. It is expected that a radio button be given a default value. When this is the case, a required radio button selection field will have one option pre-selected. I am attaching a brief video to illustrate this process (note that the video cuts off before a new contact is created; however, you would see the set default option already selected in that case).

I don't agree with this though as setting a default value should not be a requirement to make something wrong. I'm replying on this

**Comment by sswapnesh** [comment]
Any update?

**Comment by Yenthe666** [comment]
It was denied the second time too. Final feedback:

> Thank you for sending this follow up message. I do understand your perspective. I cannot guarantee if anything related to this behavior is going to be changed in the future, but we certainly appreciate your feedback and always consider it when looking into possible updates for future version releases! 
I will go ahead and close this ticket now. Please do not hesitate to file additional tickets at odoo.com/help for any inquiries that you might have in the future.

**Comment by sehrishnaz** [comment]
Show one2many field record as radio button widget: http://learnopenerp.blogspot.com/2020/05/show-one2many-field-records-as-radio-button-in-odoo-wizard.html

**Comment by Yenthe666** [comment]
@sehrishnaz stop spamming on various issues with links to your personal blogs. If this behaviour proceeds I will get you completely banned.

**Comment by sehrishnaz** [comment]
ok sorry i deleted this

**Comment by sswapnesh** [comment]
@Yenthe666  Finally after 2 years this has been fixed https://github.com/odoo/odoo/pull/87375
