### ISSUE TITLE
[V8]Setting sequence in public product category is not used

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#3433]
Hy,

Whatever the sequence you set in the public product category it's always the ENGLISH alphabetic order that is kept.
It would be nice if the the sequence could be taken into account and if the language of the connected user could be used for alphabetic order.

regards

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
