### ISSUE TITLE
[10.0] Why the canceled status in stock_pack_operation isn't allowed to delete it?

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#34380]
https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_pack_operation.py#L169

https://github.com/OCA/OCB/issues/857

**Comment by Yenthe666** [comment]
Dear @igallart,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
