### ISSUE TITLE
[12.0] Can create record in one2many field (tree mode with create="false")

### ISSUE THREAD

**Issue by langbamit** [odoo/odoo#34381]
Impacted versions: 12.0

Bug: Show "Save & New" button in FormViewDialog when click a row in one2many field (tree mode with create="false")

Video/Screenshot link (optional): [Youtube](https://youtu.be/lnJfulzXDgc)

**Comment by pedrobaeza** [comment]
I think you should define the form view of the one2many model with empty `<footer>`
