### ISSUE TITLE
How to remove dialogue balloons

### ISSUE THREAD

**Issue by Doliprane500** [odoo/odoo#34400]
hello everyone, my version of Odoo is 12.0 , my problem is the following

 I would like to remove the dialogue balloons from instant messaging, I wanted to remove the message module but I'm afraid it will remove the web module

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
