### ISSUE TITLE
[12.0][HR] Unknown field parent_id in domain

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#34405]
**Impacted versions:** 12.0

**Steps to reproduce:** Set Employee private address and open on clicking on it
[runbot](http://549390-12-0-29d17b.runbot14.odoo.com/web?#id=319&action=216&model=hr.employee&view_type=form&menu_id=167)
**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/22585204/60252445-dfbbb980-98e7-11e9-97b2-004377bbd689.png)

**Comment by pedrobaeza** [comment]
I'm not able to reproduce it. Please indicate all the steps or put a video with them.

**Comment by smurf-U** [comment]
PFA

[emp.zip](https://github.com/odoo/odoo/files/3334217/emp.zip)

**Comment by sswapnesh** [comment]
Happens when `base_address_city` is installed.

**Comment by pedrobaeza** [comment]
OK, thanks for the pointer. Tagged.

**Comment by sswapnesh** [comment]
Added fix on https://github.com/odoo/odoo/pull/34498

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/30901
