### ISSUE TITLE
Wrong Session Login

### ISSUE THREAD

**Issue by aryaadiputra** [odoo/odoo#34438]
Impacted versions:
9 and 11

I got dangers issue, On Odoo Session Login.

Case :
1. Set Users More than 1000
2. Module Website installed
3. Example, Have user 'A' & 'B' 
4. Case 1: I Try Sign In with username & Password user A ,but when login successed web page redirect to Home page Website with User 'B' Signed.
5. Case 2: days 1 I was login with User 'A' not issue appear, all working well normal then I close browser without logout, tomorrow days 2 I open browser again system open with User 'B'.

Note : I never login with user 'B', I worried odoo take wrong session filestore so make I got wrong user login.

Please give me advise

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by aryaadiputra** [comment]
@pedrobaeza Hi Thanks for your responds, I think my Odoo installation already correct, can you give clue which part may be I missed? so this case happend. Thanks a lot

**Comment by pedrobaeza** [comment]
Check that the filestore where sessions are stored is not shared with other instances and have the proper permissions, but I can't give you more clues.
