### ISSUE TITLE
[12.0] Manual Field: one2many field with integer relation field

### ISSUE THREAD

**Issue by langbamit** [odoo/odoo#34458]
Impacted versions: 12.0

Steps to reproduce: Create manual field like image below

Current behavior: Raise error if relation field is integer field.

Expected behavior: Create successfully.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/43192714/60379943-bb3a1b80-9a66-11e9-9a90-4a033c6f5bfb.png)

**Comment by sswapnesh** [comment]
> Current behavior: Raise error if relation field is integer field.


As you already know `res_id` is integer field so it is not possible to add o2m with that field.

Cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
`inverse_name` must be a many2one field, so it's not something to be fixed.

**Comment by langbamit** [comment]
But why this work? https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_activity.py#L505-L506

**Comment by pedrobaeza** [comment]
Because that's abstract model that it's overwritten on each model with proper value
