### ISSUE TITLE
[master] no debug button.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#34460]
Impacted versions:

master

Steps to reproduce:

1. enable debug mode

Current behavior:

1. No debug button to read technical information.

![image](https://user-images.githubusercontent.com/338634/60387846-4cad8b80-9a6f-11e9-898e-7bb9d318a6fd.png)

Expected behavior:

2. Have access to technical information.

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
> Current behavior:
> No debug button to read technical information.
> 
You should consider adding  `cisd` in url. (Won't work if you enabled it using Odoo debug extension)

https://github.com/odoo/odoo/blob/master/addons/mail/controllers/main.py#L74

Eg, http://551489-master-be35ae.runbot19.odoo.com/web?debug=1#action=620&model=account.journal&view_type=kanban&cids=1&menu_id=558

**Comment by jat-odoo** [comment]
> Won't work if you enabled it using Odoo debug extension

@sswapnesh 
We will soon release update for Odoo Debug extension(Still we are working) which is compatible with v13 and also have backward compatibility.

**Comment by sswapnesh** [comment]
> We will soon release update for Odoo Debug extension(Still we are working) which is compatible with v13 and also have backward compatibility.

@jat-odoo 
Thanks a lot for making debugging in odoo super easy.
Here :pizza: for you :wink:.

**Comment by nhomar** [comment]
Closing because better things are comming.
