### ISSUE TITLE
Set different  accounts payable and receivable for partner

### ISSUE THREAD

**Issue by lili94** [odoo/odoo#34472]
Impacted versions: V.11

hi in my company we have for some partner different account paybale and receivabale (not the default for all chart account) so when i want to show customer ledger nothing show how can resolve this problem please

**Comment by Yenthe666** [comment]
Hi,

This is not an issue or bug but a question. Please ask this on the official help forums at https://www.odoo.com/forum/help-1

Regards,
Yenthe

**Comment by lili94** [comment]
thanks but can we do somthing like this @Yenthe666

**Comment by Yenthe666** [comment]
Sure, just create extra accounts and assign them on the partner you wish?

**Comment by lili94** [comment]
i try it befor for exemple my default account paybale (411100) and receivabale(401100)
Partner /BNA have  paybale (411200) and receivabale(405000) i replace it for them . but in costumers ledger  nothing show

**Comment by Yenthe666** [comment]
Again, this is not the place to ask, ask help on the official help forums. It should work just fine if you configure it well.
