### ISSUE TITLE
[11.0 e] Product: To edit products variants in multicompany

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#34501]
**Impacted versions:** 11.0 e

**Steps to reproduce:**

1. Modify the admin user, so that only belongs to the company: "Company 1".

2. Modify the demo user, give manager permissions for the inventory module.

3. With the demo user edit the variant of a product for the product graphics card from "YourCompany"

4. With the user admin and from company 1, create a purchase order for the graphics card product and receive the product

5. With the demo user edit the variant of a product for the product graphics card from "YourCompany"

**Current behavior:**

When you edit the variant of the product and try to save it appears a security restriction. Record rule "Stock Move multi-company"

![stock_move_rule](https://user-images.githubusercontent.com/5775695/60474295-19215b80-9c3f-11e9-8a00-04f877db9a2f.png)

**Expected behavior:**

We expect edit products variants, logged by any company

**Video/Screenshot link (optional):**

https://youtu.be/rRSVPncxEyk

**Comment by deivislaya** [comment]
OPW:  2030918

**Comment by sswapnesh** [comment]
Seems fixed on v12 at  https://github.com/odoo/odoo/pull/34369

**Comment by pedrobaeza** [comment]
Yes, it seems so.

Closing, but if not solved in that case, please comment back.

**Comment by sswapnesh** [comment]
I did not find this code on 11.(Not sure)

**Comment by pedrobaeza** [comment]
OK, I have written on the PR to see
