### ISSUE TITLE
kanbancard color

### ISSUE THREAD

**Issue by intisankar** [odoo/odoo#34504]
Impacted versions:odoo12 CE

Current behavior: it's having only one sigle left line 5px to set color

Expected behavior: needs total kanban card color (In purchases based upon the value of the state some custom colors need to assigned for  more visibility )

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Hi, this is not a bug, it's intended; In v10 it was possible to color the entire kanban card, from v11 onwards, only the left border is colored, it's a design decision

**Comment by intisankar** [comment]
Is there any alternative method to achieve  this ?

**Comment by intisankar** [comment]
Yeah, 
I found the solution for but its somewhat unprofessional coding!.
But I do not get a better solution for that.
Q: Need Different colors in Purchase Quotation kanban view (kanban card) depends on stages ?
A: I used the Qweb filtering and apply the style information (means colors for individual state)
  note: (I tried the External Js and CSS but it won't work )
These are the following sample code for different stages involved in PQ 
`<templates>
                        <t t-name="kanban-box" >
                            
                            <t t-if="record.state.value == 'RFQ'">
                              <div style="background: white" t-attf-class=" oe_kanban_card oe_kanban_global_click">
                                   <div class="card-text o_kanban_record_top mb16">
                                        <div class="o_kanban_record_headings mt4">
                                            <strong class="o_kanban_record_title"><span><t t-esc="record.partner_id.value"/></span></strong>
                                    </div>
                                    <strong><field name="amount_total" widget="monetary"/></strong>
                                    </div>
                                    <div class="o_kanban_record_bottom">
                                        <div class="oe_kanban_bottom_left">
                                            <span><t t-esc="record.name.value"/> <t t-esc="record.date_order.value and record.date_order.value.split(' ')[0] or False"/></span>
                                        </div>
                                        <div class="oe_kanban_bottom_right">
                                            <field name="state" widget="label_selection" options="{'classes': {'draft': 'default', 'cancel': 'default', 'done': 'success', 'approved': 'warning'}}"/>
                                        </div>
                                    </div>
                                </div>
                            </t>

                            <t t-if="record.state.value == 'RFQ Sent'">
                                <div style="background: yellow" t-attf-class=" oe_kanban_card oe_kanban_global_click">
                                    <div class="card-text o_kanban_record_top mb16">
                                        <div class="o_kanban_record_headings mt4">
                                            <strong class="o_kanban_record_title"><span><t t-esc="record.partner_id.value"/></span></strong>
                                        </div>
                                        <strong><field name="amount_total" widget="monetary"/></strong>
                                    </div>
                                    <div class="o_kanban_record_bottom">
                                        <div class="oe_kanban_bottom_left">
                                            <span><t t-esc="record.name.value"/> <t t-esc="record.date_order.value and record.date_order.value.split(' ')[0] or False"/></span>
                                        </div>
                                        <div class="oe_kanban_bottom_right">
                                            <field name="state" widget="label_selection" options="{'classes': {'draft': 'default', 'cancel': 'default', 'done': 'success', 'approved': 'warning'}}"/>
                                        </div>
                                    </div>
                                </div>
                            </t>

                            <t t-if="record.state.value == 'Purchase Order'">
                                <div style="background: lightgreen" t-attf-class=" oe_kanban_card oe_kanban_global_click">
                                    <div class="card-text o_kanban_record_top mb16">
                                        <div class="o_kanban_record_headings mt4">
                                            <strong class="o_kanban_record_title"><span><t t-esc="record.partner_id.value"/></span></strong>
                                        </div>
                                        <strong><field name="amount_total" widget="monetary"/></strong>
                                    </div>
                                    <div class="o_kanban_record_bottom">
                                        <div class="oe_kanban_bottom_left">
                                            <span><t t-esc="record.name.value"/> <t t-esc="record.date_order.value and record.date_order.value.split(' ')[0] or False"/></span>
                                        </div>
                                        <div class="oe_kanban_bottom_right">
                                            <field name="state" widget="label_selection" options="{'classes': {'draft': 'default', 'cancel': 'default', 'done': 'success', 'approved': 'warning'}}"/>
                                        </div>
                                    </div>
                                </div>
                            </t>
                         <t t-if="record.state.value == 'Locked'">
                                <div style="background: grey" t-attf-class=" oe_kanban_card oe_kanban_global_click">
                                    <div class="card-text o_kanban_record_top mb16">
                                        <div class="o_kanban_record_headings mt4">
                                            <strong class="o_kanban_record_title"><span><t t-esc="record.partner_id.value"/></span></strong>
                                        </div>
                                        <strong><field name="amount_total" widget="monetary"/></strong>
                                    </div>
                                    <div class="o_kanban_record_bottom">
                                        <div class="oe_kanban_bottom_left">
                                            <span><t t-esc="record.name.value"/> <t t-esc="record.date_order.value and record.date_order.value.split(' ')[0] or False"/></span>
                                        </div>
                                        <div class="oe_kanban_bottom_right">
                                            <field name="state" widget="label_selection" options="{'classes': {'draft': 'default', 'cancel': 'default', 'done': 'success', 'approved': 'warning'}}"/>
                                        </div>
                                    </div>
                                </div>
                            </t>
                            
                            <t t-if="record.state.value == 'Cancelled'">
                                <div style="background: #f06868" t-attf-class=" oe_kanban_card oe_kanban_global_click">
                                    <div class="card-text o_kanban_record_top mb16">
                                        <div class="o_kanban_record_headings mt4">
                                            <strong class="o_kanban_record_title"><span><t t-esc="record.partner_id.value"/></span></strong>
                                        </div>
                                        <strong><field name="amount_total" widget="monetary"/></strong>
                                    </div>
                                    <div class="o_kanban_record_bottom">
                                        <div class="oe_kanban_bottom_left">
                                            <span><t t-esc="record.name.value"/> <t t-esc="record.date_order.value and record.date_order.value.split(' ')[0] or False"/></span>
                                        </div>
                                        <div class="oe_kanban_bottom_right">
                                            <field name="state" widget="label_selection" options="{'classes': {'draft': 'default', 'cancel': 'default', 'done': 'success', 'approved': 'warning'}}"/>
                                        </div>
                                    </div>
                                </div>
                            </t>

                        </t>
                    </templates>
                </kanban>`
