### ISSUE TITLE
[11.0]: stock_barcode: Wizard no pop-ups when products are in other paging page, more than 40 operation on picking

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#34502]
Impacted versions:
11.0
Steps to reproduce:
Create a picking with more than 40 lines on operations
Go to them from barcode app
Try to scan a product that is not on the current page on the list view (remember that only 40 lines are displayed, the rest will be visible if modify the limit or change the page)
Current behavior:

No product being prompt nor product qty increase  
Expected behavior:
When a barcode is scanned, the product should prompt the wizard for serial or increase the qty done.
Video/Screenshot link (optional):
https://youtu.be/BetsDUYK8v4

tested on http://552614-11-0-02a868.runbot24.odoo.com

OPW 2030934

**Comment by kebeclibre** [comment]
Unfortunately, this use case is not supported and for many reasons. Chief among them is data consistency.
Indeed you don't want to modify data that has not been fetched yet.
Also, the data that is on another page is not fetched, and this is the expected behavior.

The right means to achieve scanning in this case is indeed to expand the x2many list view to its maximum.

**Comment by hugho-ad** [comment]
Hi @kebeclibre 
there is a way to make x2many list views display the maximum by default?

**Comment by hugho-ad** [comment]
@kebeclibre 

the feature is used on handheld, which has a mobile display, the main idea is to scan products faster, imagine a picking with more than 1000 rows, that could impact on the performance, or the usability itself.

please re-open this

Regards!

**Comment by hugho-ad** [comment]
@kebeclibre 

Also, I noticed that after the wizard is closed, the paging of the x2many list view, is reset, I mean:

- Change to the second page (41, 80 )
- Scan a barcode, the wizard is open, validate the wizard
- The paging is reset to 1-40( the first page of operation)

The above behavior is totally impractical and made the scanning process too slow

please re-open this

**Comment by kebeclibre** [comment]
@hugho-ad 
There is nothing we can do in the code, but there is a workaround
In the definition of the embedded list view, you can put an attribute limit.

```
<form>
   ....
   <field name="x2many_ids">
       <tree limit="10000000">
         ......
       </tree>
    </field>
</form>
```
