### ISSUE TITLE
Odoo 12 - menu not working in assets debug mode

### ISSUE THREAD

**Issue by bileser** [odoo/odoo#34506]
Impacted versions: 12

Steps to reproduce: install Odoo 12, Python 3.5 or Python 3.7, install dependencies with pip, use Mac OS 10.14.5 and klick on the advanced developer mode so that ?debug=assets shows in the address bar

Current behavior:

There is a JavaScript error making the menu unusable:

![Bildschirmfoto 2019-07-02 um 09 26 30](https://user-images.githubusercontent.com/12259945/60492562-87036c80-9cab-11e9-9d55-0a83915c7fc6.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot - admin/admin), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by bileser** [comment]
Had this error in odoo 11 yesterday too! ;) So I desperately switched from Chrome to Firefox and it worked. Then I deleted all browser data in Chrome and it works again. Very strange issue, but indeed, it has nothing to do with odoo

**Comment by pedrobaeza** [comment]
OK, good to know that you are working again correctly. Sometimes cache gets dirty with some toying. Incongnito windows also help for detecting this kind of problems.
