### ISSUE TITLE
Some fields become invisible when there are variants

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#34513]
### Impacted versions:

12.0 (possibly others also, but I haven't checked)

### Steps to reproduce:

- Install delivery module.
- Create variants for a product template.

### Current behavior:

`hs_code` and `responsible_id` appear in neither of product template and variant form views for the product template (the fields are taken away from the template form by this https://github.com/odoo/odoo/blob/78004338969b996d6ca0b881691d60e74ff77a65/addons/stock/views/product_views.xml#L346-L348, and there are no corresponding fields in `product.product`).  Therefore there is no way for the user to maintain these fields.

### Expected behavior:

These fields should still show when there are variants for the product.

**Comment by sswapnesh** [comment]
`hs_code` can be added from `delivery_hs_code` module. (But still `responsible_id` is missing)
![screenshot-553718-12-0-eedb1b runbot26 odoo com-2019 07 03-00-36-43](https://user-images.githubusercontent.com/16624719/60540096-f751d280-9d2b-11e9-937c-9076690a5326.jpg)

**Comment by yostashiro** [comment]
@sswapnesh I see. I missed to check the variant form view. The design, however, is still not ideal when HS Code field disappears from product template form when the field belongs to the template, not the variant.

**Comment by sswapnesh** [comment]
I find this Expected behavior as HS code should be managed at variants level not Template level.(And for that Reason it becomes invisible when there are multiple variant for Template)

**Comment by yostashiro** [comment]
@sswapnesh If so, then `product.product` should also have dedicated `hs_code` field which is currently not the case.  Besides, I am not sure if there are many cases where HS code should be managed at the variant level in reality.
