### ISSUE TITLE
Odoo does not compute date by working (business) days

### ISSUE THREAD

**Issue by yann-papouin** [odoo/odoo#3452]
All delays must be computed with the configured working days of a company:
http://www.free-online-calculator-use.com/business-day-calculator.html

It would be nice to have "res.config" parameter where we can set (check) working days (for each company):
- [x] Monday
  - 08:00 - 12:00
  - 13:00 - 18:00
- [x] Tuesday
  - 08:00 - 12:00
  - 13:00 - 18:00
- [x] Wednesday
  - 08:00 - 12:00
- [x] Thursday
  - 08:00 - 12:00
  - 13:00 - 18:00
- [x] Friday
  - 08:00 - 12:00
  - 13:00 - 17:00
- [ ] Saturday
- [ ] Sunday

And a list of exceptions with range support:
- List of days worked :
  - 09/11/2014
    - 08:00 - 12:00
    - 13:00 - 17:00
- List of work-free days:
  - 25/12/2014
  - 01/01/2015
  - 01/05/2015
  - 03/08/2015 - 14/08/2015

And, as icing on the cake function, an update button to add/get common national holidays for a specific country: http://www.timeanddate.com/holidays/.

And a generic function called from the company object to compute delays from this settings that could be used by all addons the same way. 
That way, all timedelta/relativedelta computation would be covered by the company object.

This function should allow forward delay:
  eg: `delivered_date = now + delay`
And backward delay:
  eg: `manufacture_start_date = delivered_date - manufacture_delay`

This function could also take a parameter to be easily extended by this party modules:
get_forward_delay(---, "delivery")
get_forward_delay(---, "sale")
get_forward_delay(---, "mrp")

A good start could be to use an existing library: https://bitbucket.org/shelldweller/python-bizdatetime

**Comment by Yenthe666** [comment]
Hi @yann-papouin ,

Thank you for your very detailed bug report/wishlist.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: As it is labeled wishlist it will keep popping up too.

Regards,
Yenthe
