### ISSUE TITLE
[ALL] module categories have unneccesary duplicates

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#34531]
Impacted versions: All

Steps to reproduce:
1. Create a new menuitem with Odoo studio that links to the model `ir.module.category` and drag the field `module_ids` on the formview.
2. Open up the tree view and look at the module categories

Current behavior:
You will see that some categories are 'duplicated' as they just have a one character difference in it. An example for "Human Resource" and "Human Resources":
![image](https://user-images.githubusercontent.com/6352350/60522149-be443e80-9ce8-11e9-9c61-466a39d6e326.png)
![image](https://user-images.githubusercontent.com/6352350/60522228-e338b180-9ce8-11e9-900e-761e5a0a3dd3.png)

This is because the app `hr_contract_salary` has "Human Resource" in its manifest while the app `l10n_in_hr_payroll` has "Human Resources" in its manifest. There also seem to be duplicated items with same names, such as for "Sales":
![image](https://user-images.githubusercontent.com/6352350/60522366-1d09b800-9ce9-11e9-897f-a00c5c222f15.png)
I can't figure out the reason for this one though as they're both identical in naming.

Expected behavior:
There are no duplicated `ir.module.category` records, neither because of minor typo's nor because they're identical.

**Comment by Yenthe666** [comment]
@mart-e perhaps you could shed some light on this? Some are easy to handle, such as "Human Resource" and "Documents management". The other one is unclear to me as to why the exact same name is created twice? It seems to be related to apps/security groups.

**Comment by mart-e** [comment]
The duplicates are usually errors when somebody write something different in the manifest and it can changed.
It seems the Sales you found are linked to "fake" modules with the `to_buy` flag, so probably a bug (to investigate)

https://github.com/odoo/odoo/blob/78004338969b996d6ca0b881691d60e74ff77a65/odoo/addons/base/data/ir_module_module.xml#L119

**Comment by Yenthe666** [comment]
@mart-e thanks for the quick feedback.
For the duplicates: indeed, this just means changing the manifest in master as an improvement. If you'd like I can make you a PR for this.
For the "fake" modules: it always seems to happen when you tie a `ir.module.category` to a `res.groups` record in XML.

**Comment by mart-e** [comment]
Also, maybe @tivisse will be able to check these ones as he worked on it at ec07e72845a390cdf9cf72ebbbf4369ea92ecfbe

**Comment by tivisse** [comment]
This has nothing to do with the ir.module.category declaration in xml. It the xml_id is modified, the old record should be removed from the database (is not referenced elsewhere).

In fact, we shouldn't declare ir.module categories in xml files (but unfortunately this is the case to display the enterprise modules in the community version to push the users to the Odoo website to discover the enterprise version).

When loading the modules at the database initialization, the categories are created from the definition in the manifest. See: https://github.com/odoo/odoo/blob/master/odoo/modules/db.py#L87

Example:
``` python
{
    'name': 'Sales',
    'version': '1.1',
    'category': 'Sales/Sales',
}
```
Here we will create 2 categories, one name 'Sales' and another named 'Sales' with the first one as parent_id. You could have 'Sales/Retail', etc and create that way a correct module hierarchy. This is the first root for your duplicates.

The second one 'Human Resource' instead vs 'Human Resources' is not a duplicate, they don't have the same name. Just fix the typo in the manifest for 'hr_contract_salary' and it will be fixed ;)

Have a nice day,

Yannick.

**Comment by Yenthe666** [comment]
Closing as Odoo did a pretty big refactor in the master version which solved many of these.
