### ISSUE TITLE
Many2many_tags not displayed

### ISSUE THREAD

**Issue by RemiFr82** [odoo/odoo#34533]
Impacted versions: 12.0 (and maybe previous ones)

Steps to reproduce:
Create an inherited view on the sale.order form to add the invisible attribute on the field tax_id of the field order_line tree view in the sale.order form.
Then refresh and create a new sale.order and a line with a product that has a tax in th current conditions.
Save and click on the line to open its form view, you see the "taxes" label but not the tags.
Remove the many2many_tags from the tax_id field of the field order_line form view.
Refresh and reopen the sale.order.line form, here are the taxes in tree mode and visible

Current behavior:
The taxes tags are not displayed on the sale.order.line form in read mode.

Expected behavior:
The taxes tags should be displayed in the sale.order.line form in read mode.

_Note :_ Sorry, I'm not good enough in JS to solve this and make a PR...

**Comment by sswapnesh** [comment]
Seems related to https://github.com/odoo/odoo/issues/33592 (Adding screenshot here would be good to Identify the Issue)

**Comment by pedrobaeza** [comment]
Totally, it seems a duplicated of it. @RemiFr82 please confirm and close this issue then in favor of the other one.
