### ISSUE TITLE
Odoo v10 ldap Error!

### ISSUE THREAD

**Issue by batzaya** [odoo/odoo#34537]
I have using odoo v10 community.
Then i installed auth_ldap module, python-ldap packege after configuring ldap server info. Then i try login ldap user but can't login. So i debug the source code then this line doesn't work
**results = conn.search_st(conf['ldap_base'].encode('utf-8'), ldap.SCOPE_SUBTREE, filter, retrieve_attributes, timeout=60)** 

showing error:

**-__________ QUERY START _________
_________ BIND __________
2019-07-03 08:38:40,735 62270 ERROR ckbank_1122 odoo.addons.auth_ldap.models.res_company_ldap: An LDAP exception occurred: {'info': u'000004DC: LdapErr: DSID-0C090A4C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839', 'desc': u'Operations error'}**

![image](https://user-images.githubusercontent.com/4206565/60576942-f7e07c80-9db0-11e9-8e97-12d242ab5057.png)
![error_ldap](https://user-images.githubusercontent.com/4206565/60577107-4db52480-9db1-11e9-91cd-6a66e5f28d8b.png)

**Comment by pedrobaeza** [comment]
You must query your LDAP server to know which is the error. This is probably some kind of configuration mismatch.

**Comment by batzaya** [comment]
> 
> 
> You must query your LDAP server to know which is the error. This is probably some kind of configuration mismatch.

Hi @pedrobaeza  

showing this error:

**Comment by pedrobaeza** [comment]
But that's the returned error, which is not explanatory.

**Comment by pedrobaeza** [comment]
You are not even saying which LDAP server you have....

**Comment by batzaya** [comment]
> 
> 
> You are not even saying which LDAP server you have....

We using Microsoft active directory. Doesn't install ldap server

**Comment by pedrobaeza** [comment]
That non standard LDAP requires special configuration. You should move this to the Odoo forums to ask for help. Also look for existing posts that covers this topic.

**Comment by batzaya** [comment]
> 
> 
> That non standard LDAP requires special configuration. You should move this to the Odoo forums to ask for help. Also look for existing posts that covers this topic.

Changing ldap port to 3268 it works.

**Comment by slimit** [comment]
> > That non standard LDAP requires special configuration. You should move this to the Odoo forums to ask for help. Also look for existing posts that covers this topic.
> 
> Changing ldap port to 3268 it works.

Same.
