### ISSUE TITLE
"Test Import" adds sequence numbers 

### ISSUE THREAD

**Issue by jprokop1** [odoo/odoo#34562]
Impacted versions: 12

Steps to reproduce:
install module https://github.com/OCA/product-attribute/tree/11.0/product_sequence
although designed for version 11, it also works with 12
try test import some products

Current behavior:
although nothing has been imported, the sequences have been incremented

Expected behavior:
no gaps in sequences

this issue was fixed in version 11:  #33950: Clicking "Test Import" adds sequence numbers and leads to wrong sequences
with [FIX] base, base_import: test import sequenced object no gaps #25066

**Comment by pedrobaeza** [comment]
If fixed in 11.0, then the commit should be propagated soon to 12.0, if not yet there.

**Comment by sswapnesh** [comment]
These two References were never merged.(And one if them refers to Issue)
This can be closed IMO.

**Comment by pedrobaeza** [comment]
OK, then the same answer apply to this, so closing.

**Comment by sswapnesh** [comment]
@jprokop1  Have a look at https://github.com/odoo/odoo/issues/33950#issuecomment-499620831 (Incase you want to fix it by own)
