### ISSUE TITLE
[12.0][BUG] account: impossible to change account analytic if a manual tax line is reconciled.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#34567]
Impacted versions: 12.0
**Description of the issue:**
In case where you change manualy the compute of the tax (because the rounding made by the supplier is different), and this tax line is reconciled (to make the VAT declaration), it not possible to change analytic account.

**Current behavior before PR:**
- create a Journal with allow cancel entries
- create a journal Entries A with:
    - account 600 - debit 1000, tax 20% (line C)
    - correct the tax line, replace 200 by 201 (because the rounding made by the supplier is different). (line A)
    - account 400 - credit 1201 (amount set automatically)
- post
- create a journal Entries B (when you make the VAT declaration)
    - account VAT : 201 € (line B)
    - account VAT declation : 201 €
- post
- reconcile line A and line B
- return to the journal entrie A
- unpost
- add an analytic account to the line C
- the amount of the VAT changed to 200, you rechange to 201
--> try to save : it impossible : `You cannot do this modification on a reconciled entry. You can just change some non legal fields or you must unreconcile first.`

**Desired behavior after PR is merged:**
You can change the analytic account.

@qdp-odoo 

Part of solution : check if the value is modified. https://github.com/odoo/odoo/pull/34568

**Comment by fmdl** [comment]
OPW #2031961

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com. Was this solved through OPW?

**Comment by fmdl** [comment]
Solution: Don't cancel Invoice, Cancel Journal Entrie
