### ISSUE TITLE
odoo 11 not upload language/not update strings [pl_PL] [PO file] 

### ISSUE THREAD

**Issue by dzegar** [odoo/odoo#34573]
**Impacted versions:** Odoo 11.0-20190204 Community Edition
**language code:** pl_PL
**Steps to reproduce:** export full language then try to import it, you will experance connection lost then autoreconnect but nothing happened, same string as it was before - not translated. (i attached my po file - zippyshare) u can try upload it
**Current behavior:** nothing happend
**Expected behavior:** upload language or change existing with new translation strings
**PO file:** [https://www23.zippyshare.com/v/Axs8ti6U/file.html](https://www23.zippyshare.com/v/Axs8ti6U/file.html)
**Logs:** it inform about upload then, bloody nothing.
Thank you in advance for any help with this issue.
David.

**Comment by pedrobaeza** [comment]
This is not because Odoo, but your configuration with short CPU time limits (maybe the default ones), and then the import being cut at half. Please check this.

Closing as no valid issue.
