### ISSUE TITLE
 I am using a Honeywell barcode scanner 1450g. I printed a product label from odoo 10 but when the scanner scanned the barcode on the label, the label was 1000000000002 but after the scan on my notepad it read 1000000000009. Kindly help

### ISSUE THREAD

**Issue by Kev48** [odoo/odoo#34572]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is not something with Odoo, but with your scanner. Check its configuration.

Closing as no valid Odoo issue.

**Comment by Kev48** [comment]
It scans other product labels barcode correctly but for odoo's
