### ISSUE TITLE
Cannot trigger popup modal when embeding Odoo in an iframe.

### ISSUE THREAD

**Issue by bcho** [odoo/odoo#346]
Impacted versions:

- 7.0 (only tested on 7.0)

Environments:

- Server OS: ubuntu 14.04, ubuntu 12.04
- Browser: Firefox / Chrome

Steps to reproduce:

1. Create a parent page which have a Odoo site iframe.

```html
<!doctype html>
<iframe src="http://192.168.55.10"></iframe>
```

2. Host this parent page in a different domain (like 127.0.0.1)

3. Open parent page, and click on any links/buttons that should pop up a modal (like `Create and edit`)

Current behaviour:

- Cannot pop up the modal.

- In Chrome's console, shows that:

> Uncaught SecurityError: Blocked a frame with origin "http://192.168.55.10" from accessing a frame with origin "http://127.0.0.1". Protocols, domains, and ports must match.

Expected behaviour:

- Pop up a modal.

Why the iframe page wants to access the parent page?

**Comment by Yenthe666** [comment]
Dear @bcho,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
