### ISSUE TITLE
base: Contact Creation group wrongly labeled or wrong behavior

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#34602]
#### Impacted versions:
All

#### Steps to reproduce:
Remove the **Contact Creation** group to a user

#### Current behavior:
It can edit Partners information and create new partners

#### Expected behavior:
This user is (at least) not allowed to create new partners

**Comment by sswapnesh** [comment]
Hello @gustavovalverde 
It seems working well on v12.
I removed `Contact Creation` Group and User can only read` res.partner`
![screenshot-localhost-8069-2019 07 25-00-40-47](https://user-images.githubusercontent.com/16624719/61821621-41cef680-ae75-11e9-8617-f646b8f69034.jpg)

Am I missing something ?

**Comment by pedrobaeza** [comment]
Closing as no answer.
