### ISSUE TITLE
When copying a task, the sub tasks are not copied

### ISSUE THREAD

**Issue by administrator20** [odoo/odoo#34634]
Impacted versions:12

Steps to reproduce:

Current behavior: When copying a task, the sub tasks are not copied

Expected behavior: When copying a task, i want to copy the sub tasks of tasks

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is something done on purpose for not duplicating somehow "hidden" records (it's not the same as for example sale.order.line).

If you want that behavior, just look for or develop a custom module that does that.

Closing as no issue, but desired use case not covered.

**Comment by administrator20** [comment]
but when we copy the project that subtasks of task copied! 
its important to when copying a task, the sub tasks of that tasks copied

**Comment by pedrobaeza** [comment]
The project copy all tasks, including subtasks. This is out of scope of a bug, as it's a new feature.
