### ISSUE TITLE
[FIX] point_of_sale: Initial balance of a new statement in the POS 

### ISSUE THREAD

**Issue by juancr83** [odoo/odoo#34673]
What are the steps to reproduce your issue?
1. I have 2 session with point of sale.
2. One session with user Seller01
3. Second session with user Seller02
4. Seller 01 makes several invoices
5. Seller02 into session2, start session.

Problem, session start Starting Balance, with balance Session02

What is the current behavior that you observe?

Problem, session start Starting Balance, with balance Session02, not start balance with 0.

What would be your expected behavior in this case?
it is for this change

https://github.com/odoo/odoo/commit/46d0b461cdf246fdd1b7922401a9f1859a4fe55d#diff-f0aa3e0f5e29080288e68f327654dc6c

this change, initialize Starting Balance, but not validate session from point of sale.

                                                    
![PointOfSaleError](https://user-images.githubusercontent.com/18051207/60832657-a7cf3480-a179-11e9-9672-299c51aeb313.jpg)

@simongoffin what do you think about this?

**Comment by Yenthe666** [comment]
@switch87

**Comment by juancr83** [comment]
@simongoffin

**Comment by switch87** [comment]
@juancr83 The two sessions are probably using the same cash account (cash drawer), thus this behaviour is correct. You should make a separate cash account for each config.
