### ISSUE TITLE
Mobile Notification

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#34714]
Impacted versions:

12.0 -> https://github.com/odoo/odoo/issues/15532

Steps to reproduce:

Get a notification on an Android device while chrome brwose is on the background / tab is inactive.

Current behavior:

![image](https://user-images.githubusercontent.com/4851083/60933645-79f60700-a2c3-11e9-8c25-793a1c853352.png)

https://github.com/odoo/odoo/blob/master/addons/bus/static/src/js/services/bus_service.js#L83
https://bugs.chromium.org/p/chromium/issues/detail?id=481856

@pimodoo @Yenthe666

**Comment by pimodoo** [comment]
@adr-odoo

**Comment by pedrobaeza** [comment]
@adr-odoo any news about this?

**Comment by adr-odoo** [comment]
Fixed in https://github.com/odoo/odoo/pull/50324
