### ISSUE TITLE
[10.0] Unbuild with tracked components does not work

### ISSUE THREAD

**Issue by nagybal** [odoo/odoo#34727]
Impacted versions: tested with 10.0 (on runabout as well)

Steps to reproduce: if the components does have tracking by lot enabled.

Current behavior: EM pops "You don't have in the stock the required lot/serial number for _Table Head_. I have created a lot manually for the component _Table Head_, but it makes no difference.

Expected behavior: I should be able to select lot numbers for the components.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Dear  @nagybal,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
