### ISSUE TITLE
[website_sale] : link of product redirect to view in edit mode after create product

### ISSUE THREAD

**Issue by sys-odoo** [odoo/odoo#3473]
See video for reproduce this issue:
https://www.youtube.com/watch?v=FMCWZGAgyjo&feature=em-upload_owner

Affected version : 8.0, master

**Comment by Yenthe666** [comment]
Hi @sys-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
