### ISSUE TITLE
[8.0/Master] point_of_sale : UoS / UoM

### ISSUE THREAD

**Issue by AdilHoumadi** [odoo/odoo#3474]
POS UoS / UoM

***Impacted versions:***

- 8.0 and above

***Steps to reproduce:***

1. Go on runbot and pick a v8.0 instance;
2. Sign in to the ERP (database using all modules);
3. Via this Menu you have to enable this option in order to invoice in different UoM than the sales order (Settings -> Configuration -> Warehouse -> Invoice products in a different unit of measure than the sales order);
4. Pick up a product (Boni Oranges as an example) and set this data : 

  - Purchase Unit of Measure : kg
  - Unit of Measure : kg
  - Unit of Sale : Unit(s)
  - Unit of Measure -> UOS Coeff : 0.16

Then save the product.
5. Go to (Point of Sale) and click on New Session or resume an old one;
6. Look for this product (Boni Oranges) and added it to the ticket.

***Current output:***
- The computed price is wrong !

***Expected output:***
- The price should be computed using this formula : uos = uom * coeff => 0.31/unit = 1.98/kg * 0.16 which not the case.

**Comment by sbidoul** [comment]
@fvdsn any news about the review of this branch? Any chance it can be merged in 8.0?
