### ISSUE TITLE
Language setting on multiwebsite is going wrong

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#34755]
Impacted versions: V12

Steps to reproduce:
1. Create a new company
2. Go to website settings
3. Try to create a new website
4. The following error is shown

![image](https://user-images.githubusercontent.com/186591/60972251-2f59a680-a326-11e9-9397-bb49a5da6f4d.png)

5. Try to set the language by hand and save
6. Come back to website settings. The language has been lost again.

7. Try to select an existing website, so the language is set but saving the settings, the website and language has been lost again.

Current behavior:
It's not possible to assing a new website to an additional company 

Expected behavior:
At less one language by default on settings, should be assigned by default. as the field is mandatory.

Video/Screenshot link (optional):

The user case is configured on runbot http://560068-12-0-d0f3e8.runbot13.odoo.com

*-*-*-

This behavior can be also tested with sample data "Chicago company" since "my website" and "my website 2" are owned by "my company".

**Comment by anajuaristi** [comment]
@JKE-be @pedrobaeza Could you take a look and tell me if the issue is well explained? 
I tried to do my best!!
:)

Thank you!!
Ana

**Comment by JKE-be** [comment]
HI @anajuaristi 

We are working on a fix for it (following of https://github.com/odoo/odoo/commit/bb473003d762d36e5a446e3bae3b67d66026ada0) : https://github.com/odoo/odoo/pull/34706/files

thank you

**Comment by anajuaristi** [comment]
I tried to test the changes on runbot but build is not available at the moment. Anyway the changes LGTM

Thank you very much!!
Ana

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/34706
