### ISSUE TITLE
[12][Enterprise] Unable to close onboarding panel on Firefox 67/68

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#34768]
Impacted versions:

12 Enterprise only, works fine on community

Steps to reproduce:

1. Create new database
2. Install Sale module
3. Go to sales and try to close onboarding panel using Firefox 67 or 68 (latest)
Tested on archlinux

Current behavior:

"Remove Configuration Tips" is inactive and impossible to confirm

![image](https://user-images.githubusercontent.com/5862658/61009009-8afd5180-a371-11e9-83a4-55c10b8d171d.png)

**Comment by pedrobaeza** [comment]
I confirm the problem, but you should put an OPW ticket at odoo.com/help.

**Comment by mart-e** [comment]
Hi,

I just tested (now with firefox 72) but did not get the issue. Does this still happens or can we consider it is fixed?

**Comment by pedrobaeza** [comment]
Closing as no more answer.
