### ISSUE TITLE
Issue in currencies. When selecting “empty” symbol position, symbol still shows up in report.

### ISSUE THREAD

**Issue by JMarc44** [odoo/odoo#3478]
Issue in currencies. When selecting “empty” symbol position, symbol still shows up in report.

Impacted versions:
• 8.0 and above

Steps to reproduce:
1.  ( Accounting -> Miscellaneous -> Currencies )
2.  ( Select our currency ->Click edit  -> Symbol position -> and then choose the “empty” option )
![2014-11-05_1315](https://cloud.githubusercontent.com/assets/9482853/4917674/d1dd3dfe-64e7-11e4-83f5-7bee21aa2c56.png)

Expected output:
• After selecting the “empty” symbol position in the selection box, the expected output would be that there is no currency symbol showing next to the amounts on screen and in the report.

Current output:
• On screen the currency symbol is correctly removed, but in the report the currency symbol is unfortunately still showing up after the amount. 

Screen: OK                              

![2014-11-05_1317](https://cloud.githubusercontent.com/assets/9482853/4917684/ec94b226-64e7-11e4-8fa6-61226307c441.png)

Report: BUG!! Currency symbol is still showing up regardless of the prior selected “empty” symbol position.

![2014-11-05_1323](https://cloud.githubusercontent.com/assets/9482853/4917685/f2dd1ea2-64e7-11e4-9755-1f0b320387a0.png)

**Comment by Yenthe666** [comment]
Hi @JMarc44 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
