### ISSUE TITLE
windows odoo12 odoo-bin always restart the server

### ISSUE THREAD

**Issue by iaminvictus1993** [odoo/odoo#34781]
Impacted versions:git ce12

Steps to reproduce:
```
>  python odoo-bin --addons-path myAddons,addons 
```

Current behavior:
below command will try to connect the database and restart a serve,but I just want to set addons-path

**Comment by Yenthe666** [comment]
Why don't you just manually edit the configuration file and modify the addons path there?

**Comment by iaminvictus1993** [comment]
> Why don't you just manually edit the configuration file and modify the addons path there?

yes, thank you,you solve my problem . but  I just wonder it
