### ISSUE TITLE
[11.0 CE] Sum attribute 's result does not take into account multi-currency

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#34794]
Impacted versions: 11.0 CE

Steps to reproduce:
**1-** Activate mutli-currency
**2-** Create 2 invoices at least with different currencies **(5749.99 USD** and  **700 EUR**)
**3-** Go to invoices tree view and check the sum of the total column you will find the value is **6449.99** (Currency not indicated)

Current behavior:
Odoo sums up values without taking into account the difference of currencies

Expected behavior:
Should convert the foreign currency to the company's main currency using the conversion rate between the two currencies.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31063466/61048662-fd058300-a3d1-11e9-82b6-efbf5660b4ff.png)

**Comment by pedrobaeza** [comment]
This is something expected, as the sum is done with the column values at client level, without business logic behind. This can't be fixed, and that's why in newer versions the summarized total has been directly hidden for avoiding this.

Closing this as won't fix.
