### ISSUE TITLE
[12.0] Horizontal scrollbar in filter popover UI issue

### ISSUE THREAD

**Issue by hw-aka** [odoo/odoo#34809]
Impacted versions:
12.0
odoo: 57320593f76bc7f6e8c477b6da06b9e3eb49d813 
enterprise: bcabe51eb7c9fe434597d8ddb6c31d86ca9e2a0c 
themes: e6c60322a2f55bc110672703210a82391ffdc5c0 

Steps to reproduce:
1. Open any app, "Events" for example
2. Click "Filters"
3. Click "Add Custom Filter"

Current behavior:
- There is a horizontal scrollbar at bottom of the popover
- On Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

Expected behavior:
- There should not be a horizaontal scrollbar. There is enough room for the popover to expand horizontally to avoid that scrollbar
- There is no such UI issue in Odoo 11

Video/Screenshot link (optional):
![odoo 12](https://user-images.githubusercontent.com/34575341/61071677-0bf73000-a3e8-11e9-86ef-726be20fb614.PNG)
(With custom filter)

![odoo 11](https://user-images.githubusercontent.com/34575341/61071687-11ed1100-a3e8-11e9-965c-9eb7de86b562.PNG)
(Correct behaviour in Odoo 11)

Since I'm on Odoo.sh, I have submitted a ticket 2034625, got this: "We appreciate your feedback. This is the intended behavior. It is not an issue. " - very funny, if so, what an UI/UX from heXX.

**Comment by pedrobaeza** [comment]
Is this happening in community interface? I don't think putting this here will solve anything... I would go for insisting in the OPW ticket.

**Comment by Yenthe666** [comment]
The OPW usually wins over the Github issue yes. Your best bet is there.
