### ISSUE TITLE
Tutorial Building a website Error details: Field `message_follower_ids` does not exist

### ISSUE THREAD

**Issue by hiekmann-fnordbedarf-de** [odoo/odoo#3481]
# Impacted versions: #
8.0 and above

## Steps to reproduce: ##
Perform [tutorial](https://www.odoo.com/documentation/8.0/howtos/website.html) until Discussions and notifications. Go on including the following lines in *academy/views.xml*

    <div class="oe_chatter">
    <field name="message_follower_ids" widget="mail_followers"/>
    <field name="message_ids" widget="mail_thread"/>
    </div>

Restarting Odoo server, upgrading the module will result in an error message.

### Current behavior: ###

```
Error details.

Field `message_follower_ids` does not exist

Error context:
View `Academy courses: form`
[view_id: 724, xml_id: academy.academy_course_form, model: academy.courses, parent_id: n/a]" while parsing /home/one/DevEnv/workspace/odoo_netheimur/addons/academy/views.xml:57, near
<record id="academy_course_form" model="ir.ui.view">
			<field name="name">Academy courses: form</field>
			<field name="model">academy.courses</field>
			<field name="arch" type="xml">
				<form>
					<sheet>
						<label for="name"/>
						<field name="name"/>
						<label for="teacher_id"/>
						<field name="teacher_id"/>
					</sheet>
        <div class="oe_chatter">
          <field name="message_follower_ids" widget="mail_followers"/>
          <field name="message_ids" widget="mail_thread"/>
        </div>

				</form>
			</field>
		</record>
```

### Expected behavior: ###
I do not know exactly, but the tutorial goes on stating: "At the bottom of each course form, there is now a discussion thread and the possibility for users of the system to leave messages and follow or unfollow discussions linked to specific courses."

**Comment by xmo-odoo** [comment]
Tried again, can't reproduce the error.

1. reach the step right before that section
2. add the relevant lines to the model (`_inherit`) and view (fields)
3. restart the server with `-u academy`

The chatter box correctly appears, no error.

**Comment by vx0532** [comment]
do you have resolve this porblem?
I encounter this to stop my learning odoo8

**Comment by superxiaow** [comment]
in this particular case,
keep _name = 'todo.task' when inherit models.

**Comment by osvalr** [comment]
I found this is still valid when doing the [10.0 website tutorial](https://www.odoo.com/documentation/10.0/howtos/website.html#discussions-and-notifications)

**Comment by mayyas-nakhli** [comment]
I was having the same problem.
Then I realized that I'm adding the `_inherit = "mail.thread"` to the `Teacher` class not to the `Courses` class.
