### ISSUE TITLE
Shipping Estimator for odoo

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#34839]
I am not sure if it is proper to post here but I think it is a basic feature request for odoo eCommerce.

For every other eCommerce system I ever encountered, there is shipping estimator on cart page to estimate shipping cost according to countries. Some of them every have the shipping estimator on product page. But for odoo there is nothing but only reveal the shipping cost on checkout page. I should say it is against most customers' shopping rabbit. No one is willing to register until the total including shipping cost is satisfied, especially for international trading.

There is no such app on odoo app store either. And I consult several engineer for developing, no one doing good. I paid one but it is still in a mess after several month.

I just wonder why no one else demand it for such a basic feature. Is there anyone really use odoo eCommerce as I do? And did odoo team even consider about it? 

Thank you!

**Comment by pedrobaeza** [comment]
There's no need of shipping estimator, as the delivery price is computed automatically on checkout when the address is given. It can be arguable that you need to introduce address data before, but what I see more useless to introduce address data in the estimator and then again on the checkout process.

**Comment by frankmiao2015** [comment]
@pedrobaeza I wonder do you every run an eCommerce store? Or did you have a lot of experience shopping online. Every other shopping platform including Amazon and ebay have shipping estimator. I have running eCommerce store for more than 10 years and odoo is the only one without shipping estimator. Your simulation is your customer will shop with you for certain no matter what is the shipping cost . Did you every consider the new customer who never registered and or even old customer feel complicated to calculate shipping cost because he could only see the shipping cost on the final step. I recently just switch our stores to odoo eCommerce. Our survey shows even our old customers are troubled with the shipping cost. And we receive so many online support asking what is the shipping cost to my place. They just do not want to register to see the final steps!

**Comment by pedrobaeza** [comment]
Yes, I run several of them and my conclusion was the previous one. Any way, I'm just giving my opinion as community member, which is not Odoo's one.

@fgi-odoo as Odoo's product owner, can give you Odoo's vision.

**Comment by fgi-odoo** [comment]
It's clearly advanced. No small ecommerce does need that. They simply write it down in the product description if needed. Our main focus for the standard ecommerce module is still on basic needs and general UX (multi levels menu, quick and clean customer flow including easier payments). See some work here: https://github.com/odoo/odoo/issues/28179

**Comment by boogsau** [comment]
This would be a really nice feature to help reduce abandoned carts...
