### ISSUE TITLE
Cost price not showing as default price on purchase order

### ISSUE THREAD

**Issue by ToBeReplaced** [odoo/odoo#3485]
Installation from: https://github.com/odoo/odoo/commit/18b7b28bc1ee676a8d245f50821d4a9aeb844158

Cost price is no longer showing as default price on a new purchase order.

Expected Behavior:
"Add an Item" should show the "Cost price" of the chosen product in its "Unit Price" field.

Observed Behavior:
"Add an Item" shows "0.00" in the "Unit Price" field for all products.

Issue was not present as of the tagged 8.0 release.

**Comment by ucay** [comment]
any update on this ?

**Comment by seyed-mohammad-motahar** [comment]
You can use the vendor list price. When you create PO then it shows the cost price taking from the vendor pricelist.

**Comment by ucay** [comment]
Thanks @seyed-mohammad-motahar
