### ISSUE TITLE
Could not get content for /web_search_range_date/static/src/css/web_search_range_date.css defined in bundle 'web.assets_common'

### ISSUE THREAD

**Issue by shamimislam39** [odoo/odoo#34891]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image_2019_07_16T04_03_07_493Z](https://user-images.githubusercontent.com/18749760/61265373-ab823d00-a7b1-11e9-8a64-b526e95329e9.png)

**Comment by gdgellatly** [comment]
That is a custom module, you won't find help here.

**Comment by Yenthe666** [comment]
Hi,

It looks like your Odoo module cannot find and load your `.css` file. As @gdgellatly pointed out it is a custom module and not one from Odoo though. Create a bug report on the repository of the auther or fix the issue yourself.
You can always ask help on the official help forums too (https://www.odoo.com/forum/help-1) but don't forget to add enough info and code then.

Regards,
Yenthe
