### ISSUE TITLE
Expense account not honored on purchase invoices

### ISSUE THREAD

**Issue by ToBeReplaced** [odoo/odoo#3490]
Create a product category `All/Goods` with:

```
Stock Input Account: 100110 Goods
Stock Output Account: 529000 Purchases - Resale Items
Stock Valuation Account: 100110 Goods
Income Account: 479100 Sales of Goods
Expense Account: 100120 Goods In Transit
```

Create a product with an empty `Inventory` tab other than:

```
Inventory Valuation: Real Time (automated)
Internal Category: All/Goods
```

Make a purchase for the new product. The resulting invoice shows the `Account` as `100110 Goods`, when it should read `100120 Goods In Transit`.

Odoo 8, commit from the last 5 days.

**Comment by Yenthe666** [comment]
Hi @ToBeReplaced,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
