### ISSUE TITLE
[master 12 11 10]Wishlist：Move mrp.bom class into product module

### ISSUE THREAD

**Issue by Bonainifo** [odoo/odoo#34926]
Impacted versions:

Now mrp.bom class was in mrp module. 
When dealing with the kit business in the sales process, it has nothing to do with the production business, but we have to install the production module just to use this bom.
At the same time, the bom data itself should be an integral part of the product's underlying data.

Steps to reproduce:

Current behavior:

Expected behavior:
Suggested plan：Move mrp.bom into product module，keep kit bom type. In mrp module，inherited mrp.bom from product，and deal with manufacture business

Maybe we can modify the code without any impact on any existing business, and apply the improvements to versions 10, 11, and 12 at the same time.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This has been asked other times and Odoo has already heard this petition, so closing this one for not having several of this opened.
