### ISSUE TITLE
[Question] Attachment Chunks

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#34943]
I can still remember that at the Odoo Experince 2017 it was talked about that the handling of files with base64 has some disadvantages. Especially with larger files, because everything has to be loaded into memory and the system can easily run out of memory when converting. In 2017 it was mentioned that this problem is under consideration. Now my question: Is this still under consideration or are there concrete plans?

**Comment by Yenthe666** [comment]
@ThanhDodeurOdoo any chance you can enlighten some here? I know its technically not a bug but most likely nobody on the help forums will/can answer this anyways.

**Comment by ThanhDodeurOdoo** [comment]
Yes, b64.encodebytes for example loads the file in memory while encoding; that's usually a bottleneck when trying to upload large files

https://docs.python.org/3/library/base64.html#base64.encodebytes

```
def encodebytes(s):
    """Encode a bytestring into a bytes object containing multiple lines
    of base-64 data."""
    _input_type_check(s)
    pieces = []
    for i in range(0, len(s), MAXBINSIZE):
        chunk = s[i : i + MAXBINSIZE]
        pieces.append(binascii.b2a_base64(chunk))
    return b"".join(pieces)
```

I don't know of any plans on the matter

**Comment by keshrath** [comment]
@ThanhDodeurOdoo Thanks for the info. Would be really great to see a progress in this matter in the odoo framework, even though I am aware that this would be a pretty big one. I will close the issue after my question has been answered. If there is any news I would be grateful for an info.
