### ISSUE TITLE
[website_sale] : Discussion not working on product 

### ISSUE THREAD

**Issue by sus-odoo** [odoo/odoo#3495]
Steps to reproduce : 
* Click shop in website.
* Select any product.
* click on upper right menu customize and check on discussion.
* write a message in chatter box and try to post.

![product discussion](https://cloud.githubusercontent.com/assets/7599685/4933765/b44fcbd6-659a-11e4-8c2c-e3c61b5c5a94.png)

Affected version : 8.0, master

**Comment by pna-odoo** [comment]
Post button also gives "500: Internal Server Error" if public user try to comment on product(without login).

**Comment by Yenthe666** [comment]
Hi @sus-odoo,

This issue is no longer present in Odoo 8. Example:
![image](https://cloud.githubusercontent.com/assets/6352350/15771985/bfabc1da-296e-11e6-8628-cac59f875a25.png)
Closing this issue since it has been fixed.

Regards,
Yenthe
