### ISSUE TITLE
[8.0 document] upload word file to document raise PIL error.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#3497]
8.0 installed knowledge and document application.  when i upload word file even excel file to document directory, odoo raise PIL error.  but if i upload PDF, it worked.
`
OverflowError: Python int too large to convert to C long
`

have reviewed the code of ir.attachment in document module. i guess that ` _index()` return the wrong file type, that cause odoo call PIL to process the uploaded office file.

    def create(self, cr, uid, vals, context=None):
        if context is None:
            context = {}
        vals['parent_id'] = context.get('parent_id', False) or vals.get('parent_id', False)
        # take partner from uid
        if vals.get('res_id', False) and vals.get('res_model', False) and not vals.get('partner_id', False):
            vals['partner_id'] = self.__get_partner_id(cr, uid, vals['res_model'], vals['res_id'], context)
        if vals.get('datas', False):
            vals['file_type'], vals['index_content'] = self._index(cr, uid, vals['datas'].decode('base64'), vals.get('datas_fname', False), None)
        return super(document_file, self).create(cr, uid, vals, context)

**Comment by Yenthe666** [comment]
Hi @jeffery9,

I can no longer reproduce this bug on the latest Odoo 8.
If you still face this problem please update your Odoo and everything should work fine.
If you still face an issue (after updating your Odoo) please create a new issue or comment on this one and I'll reopen it.

Regards,
Yenthe
