### ISSUE TITLE
Odoo V12 (Account) : Post At Bank Reconciliation not working for POS

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#34978]
Impacted versions: 12 Enterprise

Steps to reproduce:
1. Set journal with BANK Type and Set True Post At Bank Reconciliation
2. Now use this Journal for the Payment at POS (where not set any Bank / Mercury Credentials)
3. Close the POS session and check the Payment and JE's

Current behavior: JE's generated with state "Posted" instead of Unposted 

Expected behavior: If Post At Bank Reconciliation set True, than JE's Should be  generated with state Unposted.

Video/Screenshot link (optional): 
https://drive.google.com/open?id=1kuQ1ARRi9CULE5_ae_LDgnNvmcb27hfP

**Comment by Yenthe666** [comment]
@switch87 for your interest.

**Comment by switch87** [comment]
@AmitBista @Yenthe666 I checked with the product owner and she told me that this is not a valid use-case for payment methods in point of sale. Therefore we will not fix this in 12. For version 13 the reconciliation in point of sale will be completely refactored and this behaviour will also be changed. As I can understand out of your explanation of the issue the new behaviour will be more like you would like it to be.
