### ISSUE TITLE
Right-to-left (RTL) interface in Arabic, Farsi, Hebrew, etc.

### ISSUE THREAD

**Issue by mightyiam** [odoo/odoo#35]
Thank you for awesome software.

The interface of right-to-left languages should be right-to-left.

**Comment by Yenthe666** [comment]
Dear @mightyiam ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
P.S: The wishlist label remains so this will keep popping up, even after I closed this.

Regards,
Yenthe
