### ISSUE TITLE
Multi-website: Odoo is confuse with pages having same path on multiple websites

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#35009]
Impacted versions:

Odoo 11.0-20190128 (Community Edition) 

Steps to reproduce:

Create multiple websites, then create a page on each website with the
same name, the same path but different content.

Current behavior:

Some time, the url to the respective page on each website return the
respective page. But some time, it return the same page with the same
content.

Example: website1.com/presentation and website2.com/presentation are
totally different pages. Their got created separately at different
times. They've got only path and title in common, they've got
different content and are attached to different website. But when a
visitor go to theses 2 url, they got the same content. The content
from the website 1 are also on the website 2. It's like Odoo mingle the
page on the website 2 with the page on the website 1.

To fix it, I had to add a different suffix on the path on each page.

Note: This bug happened on page we created some weeks ago. If I try to
reproduce it with new page the problem didn't happen. Is it possible
that some pages lost the attachment to their website following a module
update and now Odoo consider them as page available on all website?

Expected behavior:

Odoo who known which page to return to the visitor.

**Comment by pedrobaeza** [comment]
Multi-website support in v11 is not complete nor official, so you can expect this kind of problems.

**Comment by rdeodoo** [comment]
> Is it possible that some pages lost the attachment to their website following a module update and now Odoo consider them as page available on all website

No, it should not be the case as the view you created are not 'xml view' coming from a module data.

As @pedrobaeza said, I'd not advice you to dig further into multiwebsite in Odoo 11.0 as it was not really supported (there might be some code to work with but that would need some customization to enable everything).

On the other hand, multiwebsite is fully suported in Odoo 12.0, you should give it a try and think about moving to that version :-)

**Comment by pedrobaeza** [comment]
Closing then as won't fix if any, being v12 the first official multi-website version.
