### ISSUE TITLE
Product template modeling issues

### ISSUE THREAD

**Issue by Gorash** [odoo/odoo#3500]
The model implemented in version 8.0 on the product template seems to cause issues. We list the errors to discuss internally a better structure for data and objects.

#3401
#3204

**Comment by Yenthe666** [comment]
@Gorash any update on this one? The issue has been open for 1.5 year so I assume this can be closed?

**Comment by Gorash** [comment]
I was not the lead developer on the project in v8, I just propose changes but I have not followed this issue. The project was taken over by @jorenvo he would know if this change in the next versions. Normally it was fixed.
