### ISSUE TITLE
[12] Purchase order from Sale for Service in multicompany will use wrong sequence and warehouse

### ISSUE THREAD

**Issue by alexander-heyber-manatec** [odoo/odoo#35026]
Impacted versions:
12
Steps to reproduce:
- purchase, sale, contacts and sale_purchase installed
- Multi Company environment enabled, 2 companies created (Company 1, Company 2)
- Create several sequences for each company for purchase (e.g. company1 = CO1/PO/ and company2 = CO2/PO)
- Select company2 as current company
- Create Product (Type = Service, saleable and purchaseble, Purchase automatically enabled)
- Create Sale order, sell the service-product
- Confirm Order

Current behavior:
- PO is created from SO with wrong sequence (company 1's sequence is used), also other company-related settings are wrong (company 1 used)

Expected behavior:
- PO is created from SO with company 2 sequence

- I think this is caused by the usage of sudo() in sale_purchase when confirming the SO to create the PO. Seems that current company ID is lost when using sudo...

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think you have your sequence mis-configured. Each sequence must have explicitly the company_id with the company scope.

**Comment by alexander-heyber-manatec** [comment]
There is nothing misconfigurated. Each company has a own sequence with ist own number-circle (as i mentioned). Also, I removed the .sudo() from the line of code and it worked. Since sudo() seems to loose the company of the current user, the information for the sequence is lost too. I think there is a missing _context...

**Comment by pedrobaeza** [comment]
Please indicate the code lines where that happens

**Comment by alexander-heyber-manatec** [comment]
/sale_purchase/models/sale_order.py : 26 - 31
`    
@api.multi
    def _action_confirm(self):
        result = super(SaleOrder, self)._action_confirm()
        for order in self:
            order.order_line.**sudo()**._purchase_service_generation()
        return result
`

**Comment by pedrobaeza** [comment]
@dbo-odoo is this something in your side or more for purchase part (it's the module `sale_purchase`)?

**Comment by alexander-heyber-manatec** [comment]
Are there any news to this issue? This issue can be fixed by just giving context.. (with_context(force_company=self.env.user.company_id.id)
Maybe also the language should be supplied...

**Comment by pedrobaeza** [comment]
If you have clear the solution, please put a PR for solving it.

**Comment by alexander-heyber-manatec** [comment]
I have no clear solution, since there maybe other things that are involved, e.g. language. 
The code that I use to fix it is:
`    @api.multi
    def _action_confirm(self):
        context = self.env.user.context_get()
        context.update({"force_company": self.company_id.id})

        res = super(SaleOrder, self.with_context(context))._action_confirm()
        return res`

**Comment by sa3m** [comment]
I am facing the same issue. Seems like it's OdooBot's current company setting that is taken instead of the user's current company.
I tried changing OdooBot's current company to generate a PO and it takes the right sequence but it cannot be a solution because it breaks the settings for the first company.

Any news on merging the PR ?

Thanks
