### ISSUE TITLE
You can create a res.user even if there is already a login

### ISSUE THREAD

**Issue by emilianoNM** [odoo/odoo#35039]
https://github.com/odoo/odoo/blob/72339a530136868896a10f34386554a387eea4c9/addons/auth_signup/controllers/main.py#L34

this can solve the case 

if request.env["res.users"].sudo().search([("login", "=", qcontext.get("login"))]):
                    qcontext["error"] = _("Another user is already registered using this email address.")

**Comment by pedrobaeza** [comment]
Please give a proper line reference (permalink)

**Comment by emilianoNM** [comment]
This  is  the permalink 

https://github.com/odoo/odoo/blob/72339a530136868896a10f34386554a387eea4c9/addons/auth_signup/controllers/main.py#L34

thanks

**Comment by pedrobaeza** [comment]
I still see an empty line...

**Comment by emilianoNM** [comment]
An apology, I think I did not understand well,

The case  is based on a user's registration flow, it seems that the single sign-up, the   restriction does not work, because for the login unique not working. 

I propose is to add the following lines in the line 34 odoo/addons/auth_signup/controllers/main.py   to mitigate the case, doing a login search.

if request.env["res.users"].sudo().search([("login", "=", qcontext.get("login"))]):
   qcontext["error"] = _("Another user is already registered using this email address.")

**Comment by pedrobaeza** [comment]
But that will make that you can impersonate as other user only requesting this...

**Comment by emilianoNM** [comment]
Ok is this possible maybe is possible change the message error for 'the data is not  invalid
'
I am think for this case, maybe not i think in others possible cases.

![image](https://user-images.githubusercontent.com/25286827/61650817-22b84500-ac7a-11e9-8e46-c9ced7c4a88d.png)

**Comment by pedrobaeza** [comment]
Well, better that you propose the corresponding pull request with that improvement. Closing meanwhile.
