### ISSUE TITLE
Odoo.com Website Issue 

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#35038]
Impacted versions:
www.odoo.com
Steps to reproduce:

Current behavior:
Pakistan as a country missing in Odoo Mug link
Expected behavior:
Pakistan as a Country should be show in Odoo Mug Link 

Video/Screenshot link (optional):

![imageedit_152_4887645456](https://user-images.githubusercontent.com/22232100/61595547-0ed8f880-ac12-11e9-9de1-22f0995401bc.png)

**Comment by pedrobaeza** [comment]
@mart-e not sure which can handle this

**Comment by karamtabba** [comment]
Malaysia is also missing?
I'd like to show-off with my brand new Odoo Mug please.

-Super hero

**Comment by usmanfarzandali** [comment]
@karamtabba not only Pakistan & Malaysia many other countries are also missing ...

**Comment by mart-e** [comment]
> not sure which can handle this

All odoo.com related questions should be handled by the [support](https://www.odoo.com/help) as github is for bug report on the software.

The limitation of the list of countries is on purpose (hardcoded list). My guess is that it is for delivery reasons (e.g. specific carrier does not deliver world wide) but again, you will get better answer with the [support team](https://www.odoo.com/help) if it is not possible to add these countries.

**Comment by Yenthe666** [comment]
A lot of similar issues are also reported at https://github.com/odoo/odoo/issues/33709 by the way

**Comment by mart-e** [comment]
@JKE-be is too kind :wink: but IMHO this is the right place to talk about odoo.com related issues.
