### ISSUE TITLE
Unexpected url prefixing with lang

### ISSUE THREAD

**Issue by dolfinus** [odoo/odoo#35036]
Impacted versions: 12.0, maybe 11.0 also

Steps to reproduce:
Add addon with simple GET controller, like:
```@http.route('/bpm/widget/users/check', type='http', auth='user', methods=['GET'], website=False)```
This endpoint will be used by some JS included in view source.
Then import translation for some language, ru_RU for example, and change current user language to it.

Expected behavior:
JS sends request:
`GET /bpm/widget/users/check`
And receives controller execution result.

Current behavior:
Behavior is the same as expected but only if just one language is used or current user language is _en_.
After changing user lang to ru_RU or some other, this request returns 302 code with header:
`Location: https://domain/ru_RU/bpm/widget/users/check`
And of course there is no controller for such endpoint, so JS receives 404 while redirecting to it.

Redirect is caused by this line:
https://github.com/odoo/odoo/blob/8a6e2caa04cbe9d3fd33b226146485725f7fceb0/addons/http_routing/models/ir_http.py#L355

This bug is caused by:
https://github.com/odoo/odoo/blob/8a6e2caa04cbe9d3fd33b226146485725f7fceb0/addons/http_routing/models/ir_http.py#L172
and 
https://github.com/odoo/odoo/commit/953a693df1284

In second line Odoo finds no router because method is GET but without any reason it search for POST. So even if controller route set with `website=False`, it affects nothing.
It was not a problem before second commit, but now not found router error causes returning True from `is_multilang_url` and then redirecting to incorrect url.

I propose to change this line to:
`func = router.match(path, method=request.httprequest.method, query_args=query_string)[0]`

Odoo already knows that HTTP method was received, so just try to search for controller using this exact method instead of fixed POST.

**Comment by rdeodoo** [comment]
Wasn't this fixed with https://github.com/odoo/odoo/pull/40398 ?

**Comment by dolfinus** [comment]
I have no Idea, not using Odoo anymore :)
