### ISSUE TITLE
[Wishlist] website blogs: improve blog SEO with extra og content

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35031]
Impacted versions: All

Steps to reproduce:
1. Open up a runbot instance, go to blogs and open a blog.
2. Open up the editor and look at the SEO in your head, it'll look like this:
![image](https://user-images.githubusercontent.com/6352350/61576650-d683ce00-aadc-11e9-9d9a-fef00c3e60af.png)

Current behavior:
As you can see the `og:type` is defined as `website` while the open graph protocol also has an option for `og:type` defined as `article` which is used for blog posts and new stories.

Expected behavior:
`og:type` defined as `article`.
The great part with this is that the the type `article` has extra parameters to be supplied. Quote from http://ogp.me/#type_article:

> article:published_time - datetime - When the article was first published.
> article:modified_time - datetime - When the article was last changed.
> article:expiration_time - datetime - When the article is out of date after.
> article:author - profile array - Writers of the article.
> article:section - string - A high-level section name. E.g. Technology
> article:tag - string array - Tag words associated with this article.
> 

What is great about this part is that you can also define `article:tag`, which can be filled up with the blog post tags that already exist in Odoo. 
By setting this article value and its contents the SEO of your blogpost should/could go up in the Google search results.

I believe we could handle this in the controller in the `_default_website_meta` function by doing a check if it is a blog post or not and if so filling in the extra values here:
https://github.com/odoo/odoo/blob/8a6e2caa04cbe9d3fd33b226146485725f7fceb0/addons/website/models/website.py#L844-L850

**Comment by Yenthe666** [comment]
Just to give some pseudocode for a better idea:
```
        # Default meta for OpenGraph
        default_opengraph = {
                'og:type': 'website',
                'og:title': title,
                'og:site_name': company.name,
                'og:url': request.httprequest.url,
                'og:image': img,
        }

        if 'blog' in request.httprequest.url:
            blog_id = int(re.sub(r"\D", "", request.httprequest.url.rsplit('/', 1)[-1]))
            blog = request.env['blog.post'].sudo().browse(blog_id)
            print('blog: ' + str(blog))
            if blog:
                default_opengraph = {
                    'og:type': 'article',
                    'og:title': title,
                    'og:site_name': company.name,
                    'og:url': request.httprequest.url,
                    'og:image': img,
                    'article:published_time': blog.post_date,
                    'article:modified_time': blog.write_date,
                    'article:author': blog.author_id.name,
                }
                if blog.tag_ids:
                    default_opengraph['article:tag'] = blog.sudo().tag_ids[0].name
```

**Comment by Yenthe666** [comment]
I'm already going to go ahead and close this one in favour of my PR at https://github.com/odoo/odoo/pull/35060

**Comment by luhuan97** [comment]
nice

**Comment by Mohammed329** [comment]
No worries:)
Thanks
