### ISSUE TITLE
effective date in SO is not updated after first delivery is done [10.0]

### ISSUE THREAD

**Issue by mmotahar-ia** [odoo/odoo#35047]
Impacted versions:
10.0e 
Tested on Runbot:
http://567475-10-0-619185.runbot27.odoo.com/web?debug=1#id=220&view_type=form&model=ir.module.module&menu_id=5&action=37

Steps to reproduce:
Install sale_order_dates module
Create an order for a stockable product and confirm it. 
Navigate to it's generated delivery order and validate it (mark it as done)
Go back to the original sale order
Review the value against effective_date

Current behavior:
effective date (which is a date on which the first delivery order is created) is still empty

Expected behavior:
It must be (as per the definition) the date of the first confirmed DO. 

Please note that it has been tested on V12 and it's working fine on V12.

**Comment by Yenthe666** [comment]
Dear @mmotahar-ia,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
