### ISSUE TITLE
Problem with checkboxes in Safari

### ISSUE THREAD

**Issue by drdran** [odoo/odoo#3507]
Hi,
I'm using safari 8.0 (10600.1.25) with OS X Yosermite, I have a javascript pop up error when click on every checkboxes.

I've attached a screenshot from runboot:
![screenshot 2014-11-06 23 07 42](https://cloud.githubusercontent.com/assets/4396444/4944834/687fc60e-6601-11e4-828c-263dbec92b9c.png)

Does anyone have the same problem?

Regards

**Comment by Yenthe666** [comment]
Hi @drdran ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 (which I highly doubt) we encourage you to create a new bug report.

Regards,
Yenthe
