### ISSUE TITLE
[Wishlist] website: add optional metadata into Open Graph

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35071]
Impacted versions: All

Current behavior:
At this point in Odoo we do not set the Open Graph parameters `og:description`, `og:locale` and `og:locale:alternate` while Open Graph itself says it is generally recommended to add (http://ogp.me/#optional):

> The following properties are optional for any object and are generally recommended:
og:description - A one to two sentence description of your object.
og:locale - The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.
og:locale:alternate - An array of other locales this page is available in.

Expected behavior:
Add these options to the default Open Graph values?

**Comment by Yenthe666** [comment]
@JKE-be what do you think?

**Comment by rdeodoo** [comment]
Adding `Wishlist` label might have unexpected results :wink:

**Comment by Yenthe666** [comment]
@rdeheele haha, well, it is a wishlist item as it is not yet implemented and something I want I guess? What do you think @rdeodoo? :)

**Comment by rdeodoo** [comment]
By unexpected results I mean I will always focus on 'non-wishlist items' first, so any wishlist PR will be handled.. well.. when there will be no 'non-wishlist PR' left.. in let's say.. a few years if we are lucky :yum:

**Comment by Yenthe666** [comment]
Haha, I doubt that time will even come, ever. 😄 So, I should just label them website and not wishlist, even though it is an issue to ask for feedback? Do let me know if a PR would be welcome.

**Comment by rdeodoo** [comment]
Yep, so we can see it and flag it wishlist ourself. Honestly I won't even notice it otherwise, and I think no one will in website team.

> Do let me know if a PR would be welcome.

let's way first for the other one about article if it goes through

**Comment by JKE-be** [comment]
og:description is already supported

```bash
> /home/odoo/src/odoo/odoo/addons/website/models/mixins.py:
>    87:             opengraph_meta['og:description'] = self.website_meta_description
> 
> /home/odoo/src/odoo/odoo/addons/website/static/src/js/menu/seo.js:
>   260:         var description = $('meta[property="og:description"]').attr('content');
> 
> /home/odoo/src/odoo/odoo/addons/website_blog/models/website_blog.py:
>   273:         res['default_opengraph']['og:description'] = res['default_twitter']['twitter:description'] = self.subtitle
> 
> /home/odoo/src/odoo/odoo/addons/website_event/models/event.py:
>   155:         res['default_opengraph']['og:description'] = res['default_twitter']['twitter:description'] = self.date_begin
> 
> /home/odoo/src/odoo/odoo/addons/website_forum/models/forum.py:
>   391:         res['default_opengraph']['og:description'] = res['default_twitter']['twitter:description'] = self.plain_content
> 
> /home/odoo/src/odoo/odoo/addons/website_sale/models/product.py:
>   389:         res['default_opengraph']['og:description'] = res['default_twitter']['twitter:description'] = self.description_sale
> 
> /home/odoo/src/odoo/odoo/addons/website_slides/models/slide_slide.py:
>   678:         res['default_opengraph']['og:description'] = res['default_twitter']['twitter:description'] = self.description
```

og:locale and co should use the alternate language of the page btw, a get is already done to see the other tag. Not a priority to implement it in Odoo, really specific use case.
