### ISSUE TITLE
Reserved quantity remove when set assign owner in pack operation

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#35080]
Impacted versions: 12 Enterprise and 12 community

Steps to reproduce: 

- Activate option **Delivery Packages** from Inventory > Configuration > Settings, in that go to Operations section

- Now Activate option **Product Packagings** from  Inventory > Configuration > Settings, in that go to Products section,

- now create any product which has configured as:
         - Product Type = Storable Product
         - Set Routes as (Make To Order and Manufacture)
         - Now create any variants of that product and set product packages like pack of 100 or pack 
           of 50 (Means create product packages of that variant)
        - Created BOM for this product

- Then i have created warehouse which has **Outgoing Shipments** as Pack goods, send goods in output and then deliver (3 steps)
- Then i have created sale order and set warehouse that created in above step, and added product in line that created in above steps and set quantity and select product package in order line.
- Now clicks on Confirm button
- Now it will create manufacturing order, go to order and produce quantity and click MARK AS DONE.
- Now go to created sale order and go to Delivery, You can see there are 3 orders there, and one (picking order) is ready.
- Now add done quanity and click put in pack button, create 2-3 package and then click validate (Don't set owner here)
- Now Pack order automatically in ready step, add done quantity for packages and then set owner and click on Assign Owner link, on clicking Assign Owner link, it will set owner to all done qty lines but it will remove reserved quantities.
- This is the flow that we are working. Let us know if anything is in wrong step.

Current behavior: When we don't add owner in picking order and add owner in pack order (Add 2-3 packages, Put in pack thorough) and when you set owner and clicks on Assign owner it will remove reserve quantity for all lines.

Expected behavior: When we don't add owner in picking order and add owner to pack order it should not unreserve quantity of lines.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1v5POMVpHjDbzftZo6hljOEy_PsjYo_j4/view

**Comment by pedrobaeza** [comment]
@hareshkansara you can't set owner in the middle of a chained picking operation and expect everything to go well, as the initial procurement values don't count with the owner change, so it won't be able to chain the new quants with the owner. Any way, why do you want to set an owner? I think you are misinterpreting the use of that field.

**Comment by sle-odoo** [comment]
> done qty lines but it will remove reserved quantities

That's the point actually: the move line was reserved on a quant without owner. Now that you set an owner, the system will try to update the reservation on a quant with an owner and, if it fails, removes the reservation.

**Comment by hareshkansara** [comment]
Ok thank you all for explaining perfect flow. What actually we are doing is, we are creating packages dynamically in pick operation and set pick operation as done when manufacturing is done, so we have to set owner in pack operation. but it's occur problem. 
So it there any other solution to set owner in the middle of chained operations or it need's customisation?

**Comment by pedrobaeza** [comment]
I still don't get why you need to set owner for that, but if you need to, you have to overwrite all the logic involved, which is not recommended.
