### ISSUE TITLE
pruschase_stock: Approving an RFQ requires create permission on stock.picking/stock.move

### ISSUE THREAD

**Issue by fhossfel** [odoo/odoo#35099]
Impacted versions: 12.0

Steps to reproduce: Take away the permission to create/write stock.picking stock.move from the group purchase user.

Current behavior: Error message telling the user that he has no right to create a stock.picking document

Expected behavior: RFQ should be approcved and become a PO.

Background information: Fairly large customer. Buyers create and approce invoices but are not allowed to create stock.picking/stock.move because that would allow them to mark the orders as delivered and trigger payment. This can only be done by the warehouse. Therefore we have remove the create/write permission from purchase_stock.access_stock_move_purchase_user / purchase_stock.access_stock_picking_purchase_user.

This should still allow he users to create RFQ but they can'T approve it. The reason for this is this peace of code:

    @api.multi
    def button_approve(self, force=False):
        result = super(PurchaseOrder, self).button_approve(force=force)
        self._create_picking()
        return result

Which calls this:

    @api.multi
    def _create_picking(self):
        StockPicking = self.env['stock.picking']
        for order in self:
            if any([ptype in ['product', 'consu'] for ptype in order.order_line.mapped('product_id.type')]):
                pickings = order.picking_ids.filtered(lambda x: x.state not in ('done', 'cancel'))
                if not pickings:
                    res = order._prepare_picking()
                    picking = StockPicking.create(res)
                else:
                    picking = pickings[0]
                moves = order.order_line._create_stock_moves(picking)
                moves = moves.filtered(lambda x: x.state not in ('done', 'cancel'))._action_confirm()
                seq = 0
                for move in sorted(moves, key=lambda move: move.date_expected):
                    seq += 5
                    move.sequence = seq
                moves._action_assign()
                picking.message_post_with_view('mail.message_origin_link',
                    values={'self': picking, 'origin': order},
                    subtype_id=self.env.ref('mail.mt_note').id)
        return True

Please note the _create_picking() is declared and therefore can't be ovverriden in a submodule. I believe the call to self._create_picking should use sudo() or it should be possible to override _create_picking (by not making it private) so it is possible to intervene.

**Comment by pedrobaeza** [comment]
But that's something expected, and it's why purchase user has that permission. It should be that way and if you remove the ACL, you will have the problem. Not possible to do this on sudo, as it will change some information and possible multi-company problems.

You must find another way for doing what you want.

Closing as no real issue, but expected behavior.

**Comment by fhossfel** [comment]
Yes, but the expected behaviour is bad(tm). Maybe using sudo is not the best approach but  one should be able to assign different roles for creating an **expected** delivery and creating am **actual** delivery - which will trigger the payment. Not being able to differentiate these two does open up companies to various frauds

 The current approach may be technically feasible but it severely limits the use in any but the smallest companies.

**Comment by pedrobaeza** [comment]
I don't think so, as I have implemented Odoo in big customers. It just that you have to work with same play rules than the ecosystem that you are adapting.
