### ISSUE TITLE
[website] within an editable region, if the same field is present twice editing the first one fails 

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#351]
On edition, the region itself is marked as `oe_dirty` and saved. If the same `t-field` is present twice *in the same editable region*, editing the first one and saving will save the first one and overwrite it with the old value in the second one.

**Comment by JKE-be** [comment]
Probably fixed meanwhile ... else don't hesitate to reopen an issue :)
Thanks for the reporting ;)
