### ISSUE TITLE
[12] multiwebsite / multidomain with nginx incorrectly redirects second domain to first

### ISSUE THREAD

**Issue by LiamMulder** [odoo/odoo#35109]
Impacted versions:
12

Steps to reproduce:
Odoo is installed for the biggest part with Yenthe's script
Nginx is configured like this:
https://www.odoo.com/documentation/12.0/setup/deploy.html#id7
First website is configured as .nl and second is added as .be in the same database.

Current behavior:
When using the proxy server, the .be is redirected to the .nl website (from html inspection is says data-website-id=1 instead of 2). Connecting directly to server:8069 with the domainnames set up in my local hosts file it redirects correctly, the .nl redirects to .nl and the .be to .be (with data-website-id=2)

Expected behavior:
When using the proxy server, the .be gets redirected to the correct website.

**Comment by pedrobaeza** [comment]
Sorry, but this seems to be a deployment issue in you Nginx configuration, not an Odoo problem.
You should ask for recommendations on this on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
