### ISSUE TITLE
[12.0] Invoicing - price of product not updated when qty is changed

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#35122]
Impacted versions:
12.0 C
Steps to reproduce:
On the runbot:
1) Open a product(fe screw) and in "Sales" tab set the "Pricing" for the product to be 10€ if minimum qty is 10
2) Create an invoice and insert edited product(in this case screw) and set the qty as 10. **Price and discount won't be updated**
Current behavior:
Product price is not updated on invoices when it depends on qty(Product/Sales tab/Prices).
Expected behavior:
This feature should work as on the Sales Orders, where price is correctly updated when changing the qty on sales order lines
Video/Screenshot link (optional):
https://pasteboard.co/Ipl8FR2d.png

**Comment by pedrobaeza** [comment]
Pricelists are only applied in sales order, not in invoices, so the behavior is expected. Check OCA module https://github.com/OCA/account-invoicing/tree/12.0/account_invoice_pricelist for that.

Closing issue as expected behavior.
