### ISSUE TITLE
uid is not defined in attrs

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#35128]
Impacted versions:
10, 11,12

Steps to reproduce:

If we used this expression inside  any domain field: 
<field name="domain">[('user_id', '=', uid)]</field>
will work very good 🥇 

but if we used  it inside attrs like this :
attrs="{'invisible': [('user_id', '=', uid)]}"
This error will apeare:
<class 'NameError'>: "name 'uid' is not defined" while evaluating attrs="{'invisible': [('user_id', '=', uid)]}"

**Comment by pedrobaeza** [comment]
Yes, this is a non existing feature. Use groups for elements visibility.

Closing as no issue, but feature missing.
