### ISSUE TITLE
payment credit card check

### ISSUE THREAD

**Issue by nanxiaomo** [odoo/odoo#35139]
Impacted versions:
odoo 12
Steps to reproduce:
in the odoo/addons/payment/static/lib/jquery.payment/jquery.payment.js ,it is old version.
credit card number check has changed 
[[credit card]](https://ja.wikipedia.org/wiki/%E3%82%AF%E3%83%AC%E3%82%B8%E3%83%83%E3%83%88%E3%82%AB%E3%83%BC%E3%83%89%E3%81%AE%E7%95%AA%E5%8F%B7)
Current behavior:
MasterCard add new card number,but in the odoo can't use
Expected behavior:
upadate javascript
Video/Screenshot link (optional):
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

**Comment by Yenthe666** [comment]
@dbo-odoo maybe for you? Not sure who's responsible for this one.

**Comment by dbo-odoo** [comment]
Hi,

You are indeed correct. I've referenced this issue in a PR which should address the issue (or at least discuss it, as there was matter to discussion at the time).

**Comment by nim-odoo** [comment]
The lib was adapted from v11 in https://github.com/odoo/odoo/pull/42483

Thanks for the report
