### ISSUE TITLE
Multi-currency issue(Invoice & payment) - Openerp v7

### ISSUE THREAD

**Issue by dinilud** [odoo/odoo#3513]
When i check with multi currency, i am getting some strange outputs. I dont know it is my understanding issue. 
According to my view, when we pay the invoice with a different currency, the customer receivable should become zero, and the difference in exchange rate should go, currency gain or loos account. Or we have to move it manually? Please provide your valuable instructions

Sorry for my bad english. Please check the attached images.., it will tell the story
![screen shot 2014-11-07 at 1 55 28 pm](https://cloud.githubusercontent.com/assets/7458334/4951352/8280aa04-6666-11e4-8d29-4d3d162852b5.png)
![screen shot 2014-11-07 at 1 58 05 pm](https://cloud.githubusercontent.com/assets/7458334/4951345/6833412a-6666-11e4-8436-445e89a28fa0.png)
![screen shot 2014-11-07 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/7458334/4951367/b1f7c89e-6666-11e4-9eb5-8abd5431fb86.png)
![screen shot 2014-11-07 at 1 56 27 pm](https://cloud.githubusercontent.com/assets/7458334/4951368/b23ca824-6666-11e4-8cff-3dc54155f72b.png)
![screen shot 2014-11-07 at 1 57 38 pm](https://cloud.githubusercontent.com/assets/7458334/4951369/b23fcc66-6666-11e4-9519-b0d15a8e9d98.png)

**Comment by Yenthe666** [comment]
Hi @dinilud,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 (& Odoo 8) is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
