### ISSUE TITLE
[12.0]Manufacturing a product get a odoo warning 'The cost of 'X' is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation'

### ISSUE THREAD

**Issue by lheredia8606** [odoo/odoo#35158]
Impacted versions: 
12.0

Steps to reproduce: 
Setup a new product (X) whit its Bill of Materials (BoM) All the products of the BoM have its respective cost. setup the product (including the products of the BoM) category inventory valuation as "Automated", Costing Method as "Average Cost (AvCo)" and try to manufacture some products 'X'

Current behavior: 
odoo send a warning 
The cost of 'X' is currently equal to 0. Change the cost or the configuration of your product to avoid an incorrect valuation. 

Expected behavior: 
Create some Products X based on the BoM and more important, recalculate the AvCo of product X whit the cost of the BoM like if I have purchased some products X

P.S If I define an initial cost of product X the warning dissapear but odoo don't recalculate the Average Cost.

**Comment by sle-odoo** [comment]
If you're in automated inventory valuation, every incoming or outgoing move need to have an accounting entry. You can create an ir config parameter to bypass this check with "stock_account.allow_zero_cost".

Regards

**Comment by lheredia8606** [comment]
Thanks for your help. I'll try to fix the error but i can not find the
property that you told me. Let me google it.
