### ISSUE TITLE
Odoo 11 blank view.

### ISSUE THREAD

**Issue by Fransmoiz** [odoo/odoo#35175]
I've restore from odoo 11 enterprise, 
1. When I run http://localhost:8068/en_US/ the website look like mess
![13](https://user-images.githubusercontent.com/41319057/61868709-34ad1880-af04-11e9-9489-c77215045001.png)

2. When I login, http://localhost:8068/web?#home , the view is blank.
![14](https://user-images.githubusercontent.com/41319057/61868721-3c6cbd00-af04-11e9-8a1f-50f06841c5a6.png)

I have try... DELETE FROM ir_attachment; but it is still same.. Please help.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
