### ISSUE TITLE
[12.0] Invoice payment blocked after cancel it

### ISSUE THREAD

**Issue by josepmy** [odoo/odoo#35196]
Impacted versions: 12

Steps to reproduce:
Create an invoice
Register the payment
Cancel the payment
Move the payment to draft

Current behavior:
Can't delete the invoice payment

Expected behavior:
Should delete the invoice payment

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is the expected behavior: either you leave them on cancel state, or you reuse them.

Closing as no issue.

**Comment by josepmy** [comment]
OK. I can understand left on cancel state, but reuse? ever the movement have the link to a nonexistent journal entry. How can I reuse them?
