### ISSUE TITLE
[11.0] ir_actions_report: assert len(outlines_pages) == len(res_ids) AssertionError: No extras <h?> html tags accpeted

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#35191]
Impacted versions:

Steps to reproduce:
- Go to invoice report template account.report_invoice_document
- Add an extra <h?> html tag like following image:
![image](https://user-images.githubusercontent.com/10233975/61894089-3f03ee00-aed5-11e9-9762-d2fed3114292.png)

- Go to invoices, select more than one, and print them

Current behavior:

```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/data/build/odoo/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/data/build/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/data/build/odoo/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/data/build/odoo/odoo/addons/base/ir/ir_actions_report.py", line 657, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/data/build/odoo/odoo/addons/base/ir/ir_actions_report.py", line 537, in _post_pdf
    assert len(outlines_pages) == len(res_ids)
AssertionError
```
![image](https://user-images.githubusercontent.com/10233975/61894035-1ed42f00-aed5-11e9-9a72-edadc18f5af9.png)

Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/vzPih9RX5N0

OPW
2042727

**Comment by kebeclibre** [comment]
@hugho-ad 
FYI @smetl 
This is the consequence of a feature. Reports are rendered in batch, with only one pass in wkhtmltopdf.
Then, we use the PDF tags that h tags make to redivide into each object's report

**Comment by hugho-ad** [comment]
@kebeclibre 

That looks like a bug, nice feature, but is still a bug, you can NOT leave these gaps that made crash simple print report action

**Comment by hugho-ad** [comment]
@kebeclibre 
Please re-open it, since is not fixed or informed across any documentation

**Comment by smetl** [comment]
@hugho-ad Hello. It's not a bug. The current implementation only supports one <h/> tag per document to be able to split the result of wkhtmltopdf (1 outline = 1 document). This is a choice made to greatly improve the performance when generating the pdf.
