### ISSUE TITLE
[MASTER] onchange currency on invoice add new line

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#35198]
Impacted versions:

- master / v13 (CE and EE)

Steps to reproduce:

- Enable multicurrency
- Create new invoice, add one line
- Change invoice currency

Current behavior:

- New invoice line is created

Expected behavior:

- No new line being created

Video/Screenshot link (optional):
[Error on CE but also happens on EE](https://drive.google.com/file/d/14uueZB7Qu2HOUu8Yhqhxy1Xh-7oHQ9S4/view)

**Comment by Yenthe666** [comment]
@qdp-odoo probably for your interest.

**Comment by qdp-odoo** [comment]
@smetl I suppose this was fixed long time ago? can you confirm?

**Comment by smetl** [comment]
@jjscarafia  I tried to reproduce your issue without any success... Do you have a particular setup I need to take care about?

**Comment by jjscarafia** [comment]
Hi, no particular setup, but it seams to be solved now. Closing...
