### ISSUE TITLE
Blog, posts list: Some bold html tags are shown as row text in text preview

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#35208]
Impacted versions:

Odoo 11.0-20190424 (Community Edition)

Steps to reproduce:

- Create a blog post
- Add a text block (snippet) as the first block of the post
- Remove any title in this block of text, keep only simple text
- Then, put some words in bold
- Save
- Go to the blog to see your article, more specifically the preview of
  the text

Current behavior:

The bold html tag are not removed in the text preview of the blog post
and the tag are shown by the browser as it: `<b>…`. Any other tag,
like italic, are correctly removed in the preview.

Expected behavior:

The bold html tag are removed in the text preview of the blog post.

Video/Screenshot link (optional):

The text in the blog post:

![Capture d’écran du 2019-07-26 10-29-18](https://user-images.githubusercontent.com/48090545/61939198-03c7f480-af93-11e9-8f4b-472085628c5e.png)

The text in the preview of the blog post text:

![Capture d’écran du 2019-07-26 10-29-35](https://user-images.githubusercontent.com/48090545/61939224-12161080-af93-11e9-9f3c-2e94f3d3a7cb.png)

**Comment by rdeodoo** [comment]
Can't reproduce the issue in 12.0
