### ISSUE TITLE
Language of messages after duplication

### ISSUE THREAD

**Issue by Tatider** [odoo/odoo#35213]
Impacted versions: 12.0

Steps to reproduce:
1. Set for user any lang except `English`. 
2. Create (for example) a CRM Lead
3. Duplicate created lead.

Current behavior: Language of "Opportunity created" message in origin lead will be current user, language of message of duplicated lead will be in English.

Expected behavior: Both messages should be in current user language.

Video/Screenshot link (optional):
1. Message of origin Lead (User language is Russian)
![origin_message](https://user-images.githubusercontent.com/13586985/61944655-e4d35d80-afa6-11e9-82c0-78a8e2da3be1.png)
2. Message of copy
![message_of_copy](https://user-images.githubusercontent.com/13586985/61944684-f3ba1000-afa6-11e9-92cf-7d0d058ca8e3.png)

The source of problem is in two places:
1. Core method `copy` [here](https://github.com/odoo/odoo/blob/12.0/odoo/models.py#L4293)
```
new = self.with_context(lang=None).create(vals)
```
2. And `create` method for `mail.thread` [here](https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_thread.py#L291)
```
if 'lang' not in self._context:
```
Everything will be okay if in `mail.thead` change condition to this:
```
if not self._context.get('lang'):
```
because lang actually in context keys, but it's value is `None`

**Comment by Yenthe666** [comment]
@mart-e what do you think?

**Comment by mart-e** [comment]
Hi,

Thanks for the report and analysis.
I agree, replacing it by
```python
if not self._context.get('lang'):
```
makes sense.
Do you wish to make a PR?
cc @tde-banana-odoo who will surely review it.

**Comment by Tatider** [comment]
Hi, @mart-e 
Thank you, I have created  PR.
