### ISSUE TITLE
[8.0/Master] Navigation Broken for Partner List on Website (even with odoo.com)

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#3522]
**Impacted versions: 8.0 and Above**

Partner listing using website_reseller works perfect when used with limited data (which is sufficient for first page).

**Steps to reproduce:**

When you want to list all records by clicking on "All Countries" it will list up data in multiple pages.
(pager at bottom for quick navigation as well). 
I tried in Odoo's most stable instnace, odoo.com it self.

e.g. https://www.odoo.com/partners?&country_all=True

Then when you click on second page, it will instead of continue showing records, it will take you to that specific country's list view from where the request is being made. ( It is not something which is expected. !!! ). 

**Current behavior:**
Instead it should continue showing the records it shows list of partner of country from where the request is being made.

**Expected behavior:**
It should continue listing partners after first page. 

This seems to be a broken navigation.

**Comment by odony** [comment]
Appears to have been fixed by #3695 a long time ago.
