### ISSUE TITLE
Impossible to sync a previously created gmail to odoo. (But the new gmails are able to sync with odoo)

### ISSUE THREAD

**Issue by Parsia** [odoo/odoo#35240]
Impacted versions: 12.0

Current behavior: Unable to sync old gmail addresses.

Expected behavior: Enable odoo to sync all of gmail addresses (old or new gmails)

Video/Screenshot link (optional): 
![sync-gmail](https://user-images.githubusercontent.com/52624519/62004462-98208b80-b13a-11e9-857d-41a88669f374.jpg)

**Comment by pedrobaeza** [comment]
Sorry, this is not a problem of Odoo, but on your Gmail configuration. Probably you need to enable "non-secure" (bad wording by Google) connections, or allow third party applications.

Closing as no real Odoo issue.

**Comment by Parsia** [comment]
Great! Thank you. My issue was solved after I adjusted this setting in google account.
