### ISSUE TITLE
HOW TO LET A SALESMAN ONLY ACCES TO HIS OWN CONTACT (COSTUMERS) DATA?

### ISSUE THREAD

**Issue by carlosmzvaldi** [odoo/odoo#35242]
HELLO, I dont know how to configure the odoo 12 to let a salesman only to acces to his own contacts (costumers database). Some one could help me with this issue?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
