### ISSUE TITLE
Fetch Mail Problem

### ISSUE THREAD

**Issue by chinu1994** [odoo/odoo#35247]
Impacted versions: 12.0

Steps to reproduce: Connected via external server mail and some mail is not being fetched by ODOO and it shows "odoo.addons.base.models.ir_cron: 0.185s (cron Mail: Fetchmail Service, server action 119 with uid 2) 
2019-07-29 08:28:02,540 17409 DEBUG ? odoo.service.server: cron1 polling for jobs

odoo.addons.fetchmail.models.fetchmail: Fetched 0 email(s) on imap server Incoming Mail Server; 0 succeeded, 0 failed."

Current behavior: It fetches mail all the times, but sometimes it skipped some emails

Expected behavior: It must fetch all the mail from the incoming mail

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You need to provide information about when that mails aren't fetched.

I doubt this is really an Odoo problem, but something on your server part. For example, you are using IMAP and reading mails in a mail web client or similar, and thus, that mails aren't fetched as they are already read.

**Comment by chinu1994** [comment]
![export (22)](https://user-images.githubusercontent.com/20063717/62067966-a6fa6180-b252-11e9-8bf6-f3bdfcff2c4a.png)
![export (21)](https://user-images.githubusercontent.com/20063717/62067968-a792f800-b252-11e9-9551-64fcfe058d38.png)


you can see the two files I have configured
My external mail server forward all the mail to my gmail account
And today I tried connecting with gmail(that is I configured my incoming mail to my gmail account and deactivate my external mail server incoming mail server configruation) as well, but then 9 out of 10 mail skipped and I immediately reverted my settings

**Comment by chinu1994** [comment]
please help me in this as my business gets disturbed and also I am using this module:
https://apps.odoo.com/apps/modules/12.0/gt_helpdesk_support_ticket/
And I have asked them also, but they have no solution for this

**Comment by pedrobaeza** [comment]
Sorry, but the problem has been already outlined, so unless you have clear steps to reproduce a problem in Odoo, this is not an Odoo issue. Ask in the forums for more help.

**Comment by chinu1994** [comment]
But the mail is not fetched, is it not odoo problem?

**Comment by chinu1994** [comment]
> Sorry, but the problem has been already outlined, so unless you have clear steps to reproduce a problem in Odoo, this is not an Odoo issue. Ask in the forums for more help.

But my problem is not solved!

**Comment by carlosecv** [comment]
chinu1994 check if you are not fetching the emails from another client.
