### ISSUE TITLE
[12.0] Favicon error odoo 12 docker

### ISSUE THREAD

**Issue by hustlercoder** [odoo/odoo#35259]
Impacted versions: 12.0

Steps to reproduce: Install odoo via docker

Current behavior: Favicon seems to have an incorrect padding

Expected behavior: Fix the error

Video/Screenshot link (optional):

Hi there idk if this can be a issue only for mebut the favicon on fresh odoo install return a 500 server error with the log: incorrect padding

**Comment by pedrobaeza** [comment]
If this is something of Docker image, please put it in the Odoo Docker project.

**Comment by gdgellatly** [comment]
@pedrobaeza it isn't docker specific afaik but it is a duplicate of a longstanding issue

**Comment by pedrobaeza** [comment]
Yeah, but nobody provide proper steps to reproduce the problem it seems...

Any way, this is a duplicated then, so closing.

**Comment by JADCO5692** [comment]
When we upload a favicon it gets resolved. seems error with the default one
