### ISSUE TITLE
[saas-12.4] Journal entry for cash basis is not created for invoice refunds

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#35276]
**Impacted versions:**
saas-12.4 

**Steps to reproduce:**

1. Active cash basis in the accounting settings
2. Configure the Tax Due = Based on Payment on the purchase tax
3. Generate a new supplier invoice with the same tax configured.
4. Validate and pay the invoice
5. Create a credit note from the paid invoice (using the `ADD CREDIT NOTE` button)
6. Validate and pay the credit note.

**Current behavior:**

- The invoice created the 3 moves: invoice, payment and cash basis

- The credit note create the reversal only for 2 moves: invoice and payment

Note: This behavior is not reproduced when the credit note is created from the credit notes view.

**Expected behavior:**

- The credit note should created the cash basis move when the credit note is paid (right?).

**Video/Screenshot link (optional):**
https://youtu.be/ocwcNZI9UKg

**Comment by luistorresm** [comment]
Hello @qdp-odoo 

In saas-12.4 is correct that when is created an invoice refund from an invoice is not generated the entry for Tax Effectively Paid?

Regards

**Comment by smetl** [comment]
@luistorresm I'm fixing this issue

**Comment by smetl** [comment]
This issue has been fixed on saas-12.4
