### ISSUE TITLE
Download attachments on selected lines ListView

### ISSUE THREAD

**Issue by pepitovadecurt** [odoo/odoo#35273]
Hello, need to download all attachments on the selected lines in list view. 
You known a module to do this? 
Have ODOO 10 CE.
Thanks.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
