### ISSUE TITLE
[10,11,12] Register page of EVENTs is not Responsive

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#35279]
Impacted versions: 12.0

Steps to reproduce:

Current behavior: EVENTs register In mobile phones (responsive view) is not good. 

Expected behavior: Register modal view in EVENT page with mobile phone ui fixed

Video/Screenshot link (optional):

![Screenshot from 2019-07-30 11-51-58](https://user-images.githubusercontent.com/51145639/62108933-7bae5b80-b2c0-11e9-95b1-08ce4f8f5381.png)

**Comment by pedrobaeza** [comment]
Have you tried latest version in runbot?

**Comment by bahram-css** [comment]
Yes i have. It was the same and it hasn't good appearance.

**Comment by Yenthe666** [comment]
@JKE-be for your reference.

**Comment by JKE-be** [comment]
strange, already see a PR for it a long time ago
and merged in my mind

**Comment by rdeodoo** [comment]
Thanks for reporting the issue.
The whole event layout has been improved in 13.0 with a complete refactoring, and this issue do not exists anymore up there.
Also, fixing it in stable, would require some change against the stable policy.
This is far from perfect I admit, but this doesn't really qualifies as a bug.
You could fix it in your own database easily if that's really a big concern.
Some people might have fixed it with xpath in their own code/database, changing it could break stuff.. (probably not but not worth the risk)

Given all this, the risk/reward is not worth it. We won't do that kind of change in our codebase.
