### ISSUE TITLE
V11 Request / Question to make post inventory button visible for posting raw mat before production

### ISSUE THREAD

**Issue by bunhin** [odoo/odoo#35272]
Request to make post inventory button visible again in V11 when there is raw mat ready to consume although there is no finish good ready yet. 

What is the reason the post inventory button shown only when there is finish good has been produced?, with this treatment user can not post raw material to consume while production still in progress and not complete any finish good.

In many situation we need to post the raw materials first even the finish good not completed yet

please reconsider.

Thank you

**Comment by sle-odoo** [comment]
Hi,
This issue is finally [fixed in v13](fa98cee00df477a0692f1a3be79bbd5f7a367692) due to various refactoring. It is sadly not possible to allow the intermediate post inventory and handle correctly all cases in v11 and v12.

I hope you understand.

Regarrds
