### ISSUE TITLE
[10.0] sale_stock not search when filter is Sale Order is not set

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#35287]
Menu All Transfers, when filter is Sale Order is not set it not return results.

https://github.com/odoo/odoo/blob/47587de19b616120e14b1f40c8ff5b846a132364/addons/sale_stock/models/stock.py#L62

**Comment by Yenthe666** [comment]
Hi,

Can you please add extra information to your report and how to reproduce the behaviour?
Just a one liner with a link to a function doesn't tell us a lot so extra input is really welcomed!

Regards,
Yenthe

**Comment by igallart** [comment]
Hi, I show the method name because is where the search is. I have tested in runbot, and it not search. With the filter in advanced search with sale order is not set, it not filter, not return results. With sale order is set it works.  Sorry by my english.

**Comment by igallart** [comment]
If is necesary I can attach a record screen.

**Comment by Yenthe666** [comment]
A record screen would be very welcomed :)

**Comment by igallart** [comment]
@Yenthe666 
Record screen

[01-08-19 14:22:08.zip](https://github.com/odoo/odoo/files/3456655/01-08-19.14.22.08.zip)

**Comment by Yenthe666** [comment]
Dear @igallart ,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back or create a new issue.
Sorry that we didn't get around to resolving your issue and a personal sorry that I didn't get around to watching your video either.

Regards,
Yenthe
