### ISSUE TITLE
ormcache is not cleared when an exception is encountered

### ISSUE THREAD

**Issue by fish-face** [odoo/odoo#35289]
Impacted versions: 11, 12, master
---

Decorating a method with `@tools.ormcache` causes the result of that method to be cached on the `cache` member of the `Registry` object, accessible from any model as `model.pool`. When an exception is encountered during a request, this needs to be cleared. For example, during the course of the request, a new model could have been created, whose id has been cached. Future requests would receive this stale id and break because the id doesn't refer to anything which exists, the transaction which would have persisted it to the database having been rolled back.

The code which handles the exception state arising in requests is https://github.com/odoo/odoo/blob/master/odoo/http.py#L299, which calls `Registry.reset_changes`. This, however, does not necessarily reset changes to the ormcache; it only does so if `Registry.cache_invalidated` is True. This does not seem to be the intended behaviour; this property is *only* set to `True` when `Registry._clear_cache` is called, which **also clears the cache itself.** In other words, `Registry.reset_changes()` clears the cache **if and only if it has already been cleared.** (The property is set to `False` after each request)

~~I suspect the fix is to remove the `cache_invalidated` property. It currently is not used at all.~~ (It is used to tell whether to signal cache invalidation - I suspect the fix is to remove the *check* in `reset_changes` though.) However, there is an issue of performance to consider, and before making this change on our own fork I would like to hear from devs about this. Making this change would mean that any time a request fails (e.g. encounters a validation error) the whole ORM cache would be invalidated. How great of a performance impact is this going to have? Would we be better off working around issues that arise from this until a full fix (which would involve only invalidating those parts of the cache which had been touched in the failed request) can be written?

Steps to reproduce:
---
Unknown in general; can be forced by decorating a method with `@tools.ormcache` which returns a value which will change each request (e.g. an auto-incrementing global variable) and raising an exception during the request. Running the request multiple times will result in only one or two values coming out. A more elaborate example can be constructed which creates an object, caches the id, then raises an exception. The cached id will be returned in subsequent invocations, which is what would typically lead to actual errors.

Current behavior:
---
The cache can contain invalid data after a transaction is aborted

Expected behavior:
---
Data that does not get committed to the database never persists in the cache

**Comment by pedrobaeza** [comment]
It's your duty to do that on the failing query. ORM mustn't assume which caches must be cleared in your logic.

**Comment by fish-face** [comment]
What about exceptions such as validation errors which are raised by Odoo, or database integrity errors? That would involve additional code in every single `create` method for starters, and I don't see any such catering for this in models provided by Odoo.

Moreover the code in `registry.py` is clearly incorrect as described above.

**Comment by pedrobaeza** [comment]
But again ORM can't infer what is the logic of your cached method, as you decide it, so the risk is that an abusive cache clearing will happen. Is there any Odoo cached method that suffers this problem or is in your custom code?

**Comment by fish-face** [comment]
I would like to focus, at least for now, on the fact that `Registry.reset_changes` never clears caches *except when it is most likely unnecessary.* This is clearly a bug. Either:

1. `reset_changes` should not be checking for whether the cache was already cleared in order to clear it itself, or
2. there should be other situations where `Registry.cache_invalidated` is set to True (this was the case at the time the parameter was introduced), or
2. it was never supposed to clear the cache at all.

I suspect, since `self.cache.clear()` is written in that method, that the intention was 1 or 2 and probably 1 because it simply doesn't make sense to clear the cache whenever the cache was cleared during a failed request.

Each scenario takes us in different directions as far as solutions and further questions go:

In case 1, what is the performance impact?

In case 2, what other situations are those?

In case 3, how should users of the cache handle exceptions?

I do not want to get onto answering that last question without a definitive answer to what scenario we are really in. I note that @rco-odoo was the person to introduce the `reset_caches` method, so maybe they can help there.
