### ISSUE TITLE
Running Odoo 10  from eclipse 

### ISSUE THREAD

**Issue by nsane9129** [odoo/odoo#35299]
Hello,i'm facing some issues while running Odoo 10 from eclipse on windows 10 .So i need some help please!

this is what shows up on the console!

![k](https://user-images.githubusercontent.com/31731547/62134146-e1f2a880-b2d7-11e9-9232-ee44d2f676ff.PNG)
![d](https://user-images.githubusercontent.com/31731547/62134148-e1f2a880-b2d7-11e9-9585-3f5c0eaa001b.PNG)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
