### ISSUE TITLE
when request https://github.com/odoo/enterprise , response returned "Page Not found"

### ISSUE THREAD

**Issue by alsalqan** [odoo/odoo#35319]
Impacted versions: Odoo 12

Steps to reproduce: request : https://github.com/odoo/enterprise

Current behavior: response returned "Page Not found"

Expected behavior: must go to odoo/enterprise 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because that repository is private. If you are an Odoo partner, request the access to it.

Closing as no issue.
