### ISSUE TITLE
[11.0][12.0][master] stock: Minor fix redundant condition

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#35318]
Redundant condition `ml.product_id.type == 'product'` in
https://github.com/odoo/odoo/blob/ce00210b612b2691ff37bb6e06ce908375e4b6cf/addons/stock/models/stock_move_line.py#L432

Already checked in https://github.com/odoo/odoo/blob/ce00210b612b2691ff37bb6e06ce908375e4b6cf/addons/stock/models/stock_move_line.py#L424

**Comment by pedrobaeza** [comment]
This only qualifies for master, as this is not a bugfix. Please do the PR for master removing it. Any way, be sure there's no path that don't pass through the initial if.

**Comment by mart-e** [comment]
Closing as not an a bug but a code cleaning. As said Pedro, don't hesitate to submit a PR in master for this.
Best,
