### ISSUE TITLE
[12.0] can not update compute fields value when pass context in overriding compute method

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#35314]
Impacted versions: odoo 12.0

Steps to reproduce:
Override compute method  _compute_price of account.invoice.line object to pass context in the super call.

Example:
    @api.one
    @api.depends()
    def _compute_price(self):
        super(AccountInvoiceLine, self.with_context(currency_id=20))._compute_price()

Note: where 20 is INR currency Id.

Current behavior:
As currency passed in context. it stopped complete calculation of the amount in invoice form. But as I can see in logs it shows after method call value is updating in fields but not viewing in invoice form view. 

Expected behavior:
As the context is passed, but it should not stop the default calculation of the invoice line method.

Video/Screenshot link (optional):
https://ibb.co/nQTLhxm

@Yenthe666: can you please help me!
Thanks in advance

**Comment by pedrobaeza** [comment]
This is not due to "stopping" compute calculation, but changing context you change the environment, and thus cached values.

Summary: you can't do that for compute methods.

Closing as no issue, but ORM behavior.

**Comment by sswapnesh** [comment]
> Summary: you can't do that for compute methods.

@pedrobaeza  Is it documented somewhere or Any reference on this ?

**Comment by pedrobaeza** [comment]
Well, it's noted that the environment depends on that variables, so implicitly yes.
