### ISSUE TITLE
binary field can't save less than 25mb file in odoo v10 on centos 7

### ISSUE THREAD

**Issue by batzaya** [odoo/odoo#35312]
![image](https://user-images.githubusercontent.com/4206565/62181723-d5795900-b386-11e9-98fa-ca72174498d4.png)
**

> **but can upload less than 500kb file.**

**

**Comment by pedrobaeza** [comment]
This must be due to your reverse proxy configuration, as Odoo doesn't have that limitation. Try on a runbot demo instance for proving it.

Closing as no real Odoo issue.
