### ISSUE TITLE
[12.0] Rounding issue in invoice and related Journal entries

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#35334]
Impacted versions: odoo V12

Steps to reproduce:

Company Currency - AED
- Configure Currency rate as per below.
AED - 1.00
INR - 19.00

- Create an Invoice with INR currency.

Let's take an example:
add one product in invoice line with 10 qty and price 500
and apply 5% Tax
so Invoice total becomes - 525 INR
and Total amount of invoice in company currency will be shown in 27.63 AED in invoice form view.

Please check the video for more information.

Current behavior:

Now, When validating an invoice, go to respective journal entries from 'other info' tab of the invoice form view. as you can see journal entries amount 27.64 AED

Now back to invoice, do register payment and select AED currency in register payment wizard, it will become 27.63 AED in the amount field.

Expected behavior:
The amount in company currency should be 27.63 AED in journal entries or 27.64 AED in invoice form view.

Video/Screenshot link (optional):
https://drive.google.com/open?id=12IyQ_VGKXqbcKzfZFQ0rz5Pz6RLvNAKb

@Yenthe666 : can you please review it!
Thanks in advance!

**Comment by rohitramnani1994** [comment]
Hello Team,
can you please update us?

**Comment by rohitramnani1994** [comment]
@sswapnesh  can you please review it ?

**Comment by sswapnesh** [comment]
> Video/Screenshot link (optional):
> https://drive.google.com/open?id=1uN43NRKAl6DSKZcV55MqMbVA_Br2zN8S

As I said on your another Issue as well, Please make Video accessible to all.

**Comment by sswapnesh** [comment]
> add one product in invoice line with 10 qty and price 500

So in that case Subtotal would be 5000

However, I am able to reproduce inconsistent behaviour.
Invoice
![screenshot-localhost-8069-2019 08 03-22-17-08](https://user-images.githubusercontent.com/16624719/62414684-780e3200-b63c-11e9-8164-fc624fa0f504.jpg)

![screenshot-localhost-8069-2019 08 03-22-17-57](https://user-images.githubusercontent.com/16624719/62414691-95db9700-b63c-11e9-93f0-81945756ddc0.jpg)


JE
![screenshot-localhost-8069-2019 08 03-22-15-12](https://user-images.githubusercontent.com/16624719/62414667-367d8700-b63c-11e9-9a43-a353adabff87.jpg)

**Comment by sswapnesh** [comment]
It's says all
525/19 = 27.6315789  (27.63)

25/19 = 1.31578947 (1.32)
500/19 = 26.3157895 (26.32)



![screenshot-localhost-8069-2019 08 03-22-47-36](https://user-images.githubusercontent.com/16624719/62415040-58c5d380-b641-11e9-9c5f-697ec60daa85.jpg)

I am not sure How to handle this.
Maybe @nim-odoo  or @qdp-odoo could add some info.

**Comment by rohitramnani1994** [comment]
> > Video/Screenshot link (optional):
> > https://drive.google.com/open?id=1uN43NRKAl6DSKZcV55MqMbVA_Br2zN8S
> 
> As I said on your another Issue as well, Please make Video accessible to all.

Apologies for the same 

can you please try with following link !
https://drive.google.com/open?id=12IyQ_VGKXqbcKzfZFQ0rz5Pz6RLvNAKb

**Comment by rohitramnani1994** [comment]
> It's says all
> 525/19 = 27.6315789 (27.63)
> 
> 25/19 = 1.31578947 (1.32)
> 500/19 = 26.3157895 (26.32)
> 
> ![screenshot-localhost-8069-2019 08 03-22-47-36](https://user-images.githubusercontent.com/16624719/62415040-58c5d380-b641-11e9-9c5f-697ec60daa85.jpg)
> 
> I am not sure How to handle this.
> Maybe @nim-odoo or @qdp-odoo could add some info.

@sswapnesh : when adding tax , rounding issue become. may be some issue with tax.
result should be 27.63 AED in JE.

waiting for more information !

**Comment by rohitramnani1994** [comment]
@qdp-odoo: can you please help us!

**Comment by qdp-odoo** [comment]
PR is merged, so I guess this issue can be closed as well

**Comment by sswapnesh** [comment]
I am sure the PR was not related to this Issue.( I will test this again to be sure)

**Comment by sswapnesh** [comment]
Hello @qdp-odoo 
Have a look at https://github.com/odoo/odoo/pull/35412#issuecomment-519832614

**Comment by sswapnesh** [comment]
@rohitramnani1994  I have added Ticket 2053301 for the same.

**Comment by rohitramnani1994** [comment]
> @rohitramnani1994 I have added Ticket 2053301 for the same.

Thank you @sswapnesh
