### ISSUE TITLE
Tutorial Building a Website

### ISSUE THREAD

**Issue by h4818** [odoo/odoo#3534]
I am following the tutorial https://github.com/odoo/odoo/blob/8.0/doc/howtos/website.rst

and I've encountered the following error:
```
ParseError: "ValidateError
Field(s) `res_model, src_model` failed against a constraint: Invalid model name in the action definition." while parsing /opt/odoo/my-modules/academy/views.xml:25, near
<record id="action_academy_courses" model="ir.actions.act_window">
	    <field name="name">Academy courses</field>
	    <field name="res_model">academy.courses</field>
	  </record>
```

I have attempted to upgrade the module using `-u academy -d demo1`

**Comment by xmo-odoo** [comment]
The message says the `academy.courses` model is not installed/loaded in the registry, but I don't really see how that could happen and I can't reproduce it.

If it's still an issue or you can provide a more extensive repro, please do comment.
