### ISSUE TITLE
[saas-12.4] Error with taxes to python code

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#35358]
Impacted versions:
saas-12.4

Steps to reproduce:
1. Create a tax with the next python code
result = price_unit * 0.16
2. Create an invoice line with qty=0 and price unit=100
2.1 Create an invoice line with qty=1 and price unit=100

Current behavior:
In step 2, the tax amount is 0
In step 2.1, the tax amount is negative

Expected behavior:
The tax amount in both cases must be 16.

Video/Screenshot link (optional):
https://youtu.be/CaEbzUASG70

**Comment by luistorresm** [comment]
Hello @qdp-odoo @smetl 

You have considered this Issue in saas-12.4 with the taxes to python code?

Regards

**Comment by jco-odoo** [comment]
@luistorresm It is certainly an issue we need to fix.  (even if we want to avoid the usage of it)

**Comment by luistorresm** [comment]
Hello @jco-odoo 

This now works fine, thanks.

But now I get an error when I try to pay an invoice with a line with python tax.

### What are the steps?
1. Enable tax cash basis in the instance
2. Create a tax with:
  - python code = proce_unit * 0.10
  - Tax Due = Based on Payment
  - Base Tax Received Account
  - Cash Basis Transition Account

3. Create a new invoice with qty 0 and with the new tax
![Screen Shot 2019-09-25 at 6 32 47 PM](https://user-images.githubusercontent.com/7606656/65647050-e6c79600-dfc2-11e9-8d4e-34a97a17ba50.png)

4. Post the invoice

5. Try to generate the invoice payment, when you try to validate the payment returns the next error:
![Screen Shot 2019-09-25 at 6 32 39 PM](https://user-images.githubusercontent.com/7606656/65647070-05c62800-dfc3-11e9-8afa-20046e34ff02.png)

[Here](https://youtu.be/dAqifYCc1Nk) a video.

Note: This error is new, the last week (Friday) this works fine.

Cc @nim-odoo @moylop260 @nhomar

**Comment by smetl** [comment]
@luistorresm I'll fix this issue.

**Comment by smetl** [comment]
@luistorresm will be fixed by https://github.com/odoo/odoo/pull/37486
