### ISSUE TITLE
[12] vendor pricelists is not used for RFQ if product is new

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#35361]
Impacted versions: all (tested)

Steps to reproduce: Import or create a vendor pricelist with products you never created in Odoo before. Then start a Request For Quotation (RFQ) to same vendor and try to add new products wich were in the vendor pricelist.

Current behavior: New product are created, unrelated to the vendor ones.

Expected behavior: At least, automaticaly search the product name or reference in the vendor pricelist. This would increase productivity : import full vendor pricelist, then create product in Odoo on the fly when you need to buy one.

**Comment by Yenthe666** [comment]
Hmm I don't think this is on the wishlist/desired behaviour list honestly. @mart-e could you give feedback?

**Comment by mart-e** [comment]
Hi,

>  Import or create a vendor pricelist with products you never created in Odoo before.

What do you mean? How did you referenced the products?
Please give an example to reproduce (i.e. a CSV file we can import).

**Comment by zeroheure** [comment]
Here's the supplier pricelist I've imported [import Grille Tarifaire 18.06.19.zip](https://github.com/odoo/odoo/files/3468196/import.Grille.Tarifaire.18.06.19.zip). It contains some products already referenced in Odoo (product_tmpl_id/id field is populated) and some new products. Yes, I've imported more supplier products than the ones already referenced. 

Later, one create RFQ to the same supplier, add some referenced products and some new, un-referenced, products that were in the pricelist (same vendor product name is used) : these new products are automaticaly created but are not "magicaly" related to the supplier pricelist, even if one type the supplier SKU. A browse list of supplier product was expected.

**Comment by mart-e** [comment]
Thanks for the file but I still don't fully understand your issue.
First there is two things odd in your file:
- `barcode` is not a field of `product.supplierinfo`, are you using custom modules?
- you can't import both `name/id` and `name`, you have to skip one

The two first lines are (after removing barcode and name):

| name/id | product_tmpl_id/id | product_code | product_name | price | min_qty | date_start | date_end | delay |
|-|-|-|-|-|-|-|-|-|
res_partner_2194 | product_template_5345 | 70001 | Boîte Mécanique | 12.43 | 1.0 | 2019-06-18 | 2019-08-31 | 8
| res_partner_2194 |  | 70002 | Théâtre | 14.51 | 1.0 | 2019-06-18 | 2019-08-31 | 8 |

After the import, 2 supplier pricelists are created, one linked to the existing product 5345 "Boîte Mécanique" and the second one linked to no product but with a Vendor Product Name at "Théâtre".

But no product record is created. Do you expect that an existing product "Théâtre" will be magically linked to the pricelist?

**Comment by zeroheure** [comment]
Thank you for trying to understand my poor english language !

> barcode is not a field of product.supplierinfo, are you using custom modules?

My mistake, this field wasn't imported.

> you can't import both name/id and name, you have to skip one

I guess `name` was added only to help.

> But no product record is created. Do you expect that an existing product "Théâtre" will be magically linked to the pricelist?

No, I don't expect that. 
Later, I create a RFQ for that same supplier : when I add "Théâtre" in the RFQ, a new product will be created, as allways. I expect that this new product is magicaly linked to the supplier pricelist. At least, a pop-up could help by proposing corresponding products in the supplier pricelist.
Small retailers need that automation like that.

**Comment by mart-e** [comment]
Ok I understand, unfortunately this is not how the selection of seller works.
You can see here how the seller is selected but the name of code is not used

https://github.com/odoo/odoo/blob/ff9ddfdacc9581361b555fd5f69e2da61800acad/addons/product/models/product.py#L564

If you check the help message of the fields, you will see it is only for display, not selection

> - This vendor's product name will be used when printing a request for quotation. Keep empty to use the internal one.
> - This vendor's product code will be used when printing a request for quotation. Keep empty to use the internal one.

**Comment by zeroheure** [comment]
Thank you for your help.
Could this report be converted as a wish list or too much changes in Odoo internal would be necessary ?

**Comment by mart-e** [comment]
That sounds is a bit complicated to do it at the creation of the product. The issue is that there is a lot of different ways to create a product (e.g. from a RFQ, from a manufacturing order, from the point of sale configuration,...).
Matching on the name of the product if there is an existing value in a supplier pricelist seems very specific and not that easy. I am afraid it would slow down the product creation for a corner case that will rarely match (and sometimes we do massive import of products, it must stay fast).

However, I will report that the supplier pricelist is a bit confusing as you expected a different behaviour. We will see if we can clarify that.

**Comment by zeroheure** [comment]
From a small retailer point of view it would improve productivity, but it is not a big problem (however it can be seen as a great usability improvement for very small companies).
Again, THANK YOU for your help.

**Comment by zeroheure** [comment]
@mart-e Sorry for asking again, but I'm curently creating a RFQ with referenced product and the behaviour is not what you described :

> [vendor reference] is only for display, not selection

I can type a vendor product reference in a RFQ instead of my reference or my product name and Odoo "magicaly" find my referenced product.

Should it be possible to create "ghost products" when importing vendor pricelist and to search in those the vendor reference ? I've done that in Perl long time ago (unfortunatly I understand only obfuscated languages, not Python ;-).

>You may say I'm a dreamer
But I'm not the only one
I hope some day you'll join us 
And Odoo will be that one
