### ISSUE TITLE
[saas-12.4] Error payment cancellation

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#35362]
Impacted versions:
saas-12.4

Steps to reproduce:
1. Create a customer invoice
2. Make a payment for the invoice 1
3. Try to cancel the payment

Current behavior:
I get the next raise:

> You cannot do this modification on a posted journal entry, you can just change some non legal fields. You must revert the journal entry to cancel it.
> Move name (id): BNK1/2019/0003 (637).

Expected behavior:
The payment is cancelled

Video/Screenshot link (optional):
https://youtu.be/cRkmUb_FNKg

**Comment by luistorresm** [comment]
Hello @qdp-odoo @smetl 

You have considered this Issue in payment cancellation?

Regards

**Comment by jco-odoo** [comment]
@smetl I reproduced the error.

**Comment by hbto** [comment]
This same issue applies for master

**Comment by qdp-odoo** [comment]
closed with https://github.com/odoo-dev/odoo/commit/aee464ed93eb8632ae679264f74f2267a96f3ace
