### ISSUE TITLE
I can not open submenus in ipad when menu is in extra (+) menu status.

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#35365]
Impacted versions: 12.0

Steps to reproduce: 

Current behavior: I can not open submenus in ipad when menu is in extra (+) menu status.

Expected behavior: To ability to open and use submenus in extra menu status.

My ipad width is 768px.
I try it on runbot.

Video/Screenshot link (optional):
![Screenshot from 2019-08-01 10-38-50](https://user-images.githubusercontent.com/51145639/62269576-c22ec200-b448-11e9-964e-1f62d0d2d8e2.png)

**Comment by pedrobaeza** [comment]
Why can't you open it?

A video showcasing the problem will be more explanatory.

**Comment by bahram-css** [comment]
https://youtu.be/GzIJzRi3Xk8

**Comment by pedrobaeza** [comment]
OK, thanks for the video.

@JKE-be FYI

**Comment by rdeodoo** [comment]
It is not really that you can't open it, it is already opened, both the 2 submenus are already displayed.

@qsm-odoo It looks to me this is done on purpose?

![62269576-c22ec200-b448-11e9-964e-1f62d0d2d8e2](https://user-images.githubusercontent.com/30048408/63683205-10da3c80-c7fa-11e9-9d41-595f6a18e3c7.png)

**Comment by pedrobaeza** [comment]
Or they can be a bit indented.

**Comment by qsm-odoo** [comment]
Yes, the submenu is already opened... We will improve this in the future, we are working on a feature which will allow the creation of better menus.
