### ISSUE TITLE
Tutorial: Web Client - module not loading

### ISSUE THREAD

**Issue by h4818** [odoo/odoo#3537]
I have cloned the odoo/petstore git repository and included the folder in my `--addons-path`.

My clean demo database with (eCommerce installed) does not display the petstore module on the back office Settings->Local Modules.

**Comment by Yenthe666** [comment]
Hi @h4818,

Thanks for the report and sorry for the very late reply.
You'd have to update your Odoo (modules list) before the app would show up. Simply adding it to the configuration is not enough.

Regards,
Yenthe
