### ISSUE TITLE
Execute action on triggering restaurant POS order button

### ISSUE THREAD

**Issue by oxwivi** [odoo/odoo#35387]
Please excuse me if this is the wrong place to ask but I couldn't get the information anywhere else. I have installed `pos_mrp_order` module available on the Odoo store; it creates a manufacturing order for relevant items once payment has been validated. I want to replicate the same manufacturing order function but with the Order button that is present when the restaurant/bar option is enabled for the POS.

I can see in the `model.js` that the manufacture order logic goes inside `pos_screens.PaymentScreenWidget.include()`, but I don't know what function to call to do the same with the Order button. Where can I find relevant documentation? Google, Odoo Help was were not helpful.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
