### ISSUE TITLE
invitation link leads to invalid signup token error when previously connected to another database

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#3538]
set up two or more databases on an odoo server,
have a user log in to one database and log out again as an admin or another user.
create the user in the second database and send an invitation email
the user clicks the link and gets a blank reset password form and an invalid signup token error. 
If the user clicks "back to login" and selects the second database in the list, (no need to save or submit, just choose it from the picklist, might not even have to do that if it is the default option in the list) then clicks the link from their email again it will work.

**Comment by Gouravchawla** [comment]
I'm facing the same issue with Odoo v8.

**Comment by Yenthe666** [comment]
Hi @AlanBell,

Thanks for the report and answering your own report. This should have been closed ages ago but nobody looked at it anymore.

Regards,
Yenthe

**Comment by vanillabush** [comment]
I am Facing this problem in odoo version 14. the token the system generated and the token sent to the user is not the same, hence when they click on the link, they get an invalid token error
