### ISSUE TITLE
HTML view of Quotation/Order does not get updated after editing xml template

### ISSUE THREAD

**Issue by cheart0** [odoo/odoo#35386]
Impacted versions: 12

Steps to reproduce:
Set sale.report_saleorder template report type to HTML. Edit web.external_layout_standard XML template then go to sales->quotations->print to check the effect, first several rounds looks good,  I can print out html type quotation which reflecting my template changes. After doing this for several times the html type quotation stop to reflect my changes.
 'Non-updatable' attribute of external_layout_standard's Model Data is unchecked. 'Reload from attachment' was already unchecked too.

But if changing sale.report_saleorder template report type to PDF, sales->quotations->print will creat PDF page which reflecting my modification.

Current behavior:
Report page does not get updated after editing template sale.report_saleorder

Expected behavior:
Report page should always reflecting modified templates.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this problem seems something specific on your environment, as this working without problems in regular Odoo (I do it all days).

Unless you provide detailed steps for reproducing the problem, there's no other sign of an Odoo issue, so I close this meanwhile.
