### ISSUE TITLE
Unable to inherit a class in odoo js

### ISSUE THREAD

**Issue by anandgodavarma** [odoo/odoo#35396]
Impacted versions:v10

Steps to reproduce: unable to inherit the class mail.char_client_action in my new module
 var mailChatAction = require('mail.chat_client_action');

Current behavior: Unable to inherit, the console shows as undefined

Expected behavior: the console should show the class

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a problem on your custom development. You should ask on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
