### ISSUE TITLE
[11.0] "Add to Cart" button creates duplicate quotations

### ISSUE THREAD

**Issue by TimLai125** [odoo/odoo#35399]
Impacted versions:
11.0, 12.0 should have the same issue as well.

Steps to reproduce:
1. Ensure there is no online quotation for the current user.
1. Double click on the "Add to Cart" button in the product page.
2. Two "Add to Cart" wizards will be popped up.
 (Depends on the server spec and you will get two pop-up in certain frequency)
3. Click "Continue Shopping" in both wizards.

Current behavior:
Two quotations are created and the portal user will only know the latest quotation.

Expected behavior:
There should be always 1 online quotation for the user, or simply there should not be 2 wizards popping in the begining.

Video/Screenshot link (optional):
https://drive.google.com/file/d/1iWTXQVGsFTMz6xmG1RAJ0kx9ozricoWo/view

**Comment by TimLai125** [comment]
I think this issue depends on server spec., if you have a small-scale server like single core and 2 GB ram, you will be more likely having this issue.

**Comment by pedrobaeza** [comment]
Is this still happening in latest version?

**Comment by JKE-be** [comment]
@pedrobaeza 
No, we have already fixed it in the latest version, with async button click, that make a second click unavailable.

Not a critical issue imo. First quotation can just be ignored like any other abandoned cart. And the double popup is like if you double click on a link, it open 2 tabs if you are faster than your browser.

**Comment by Yenthe666** [comment]
Well since it is fixed in the newest versions & 11.0 is no longer supported there is literally no reason to keep this open anymore? :)
