### ISSUE TITLE
very slow product_product query in website_sale addon

### ISSUE THREAD

**Issue by guaka** [odoo/odoo#3539]
We have about 1M product_product entries and a query is taking 3,5s each time. It is run whenever you want to see the products in the backend.
The simplified version of the query:
`SELECT pp.id FROM product_template AS pt, product_product AS pp WHERE (pp.product_tmpl_id = pt.id) AND ((pp.active = true) AND (pt.sale_ok = true)) ORDER BY pp.default_code, pp.name_template limit 80;`

Only sorting on `pp.name_template` or `pp.default_code` will speed up the query to ~100ms.

I guess "double" sorting should be avoided or done/cached in Python.

**Comment by Yenthe666** [comment]
Should have been handled at https://github.com/odoo/odoo/commit/a70ea6d03b3ddea0bf6b616f59085f8947219944
