### ISSUE TITLE
[12.0] [account_voucher] unable to validate voucher when adding tax in voucher lines.

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#35403]
Impacted versions: Odoo V12

Steps to reproduce:
- Enable multi-currency and assign rights to the user -multi-currency
- My base currency - USD
- Create a new journal in a different currency ( i created in euro).
- create a receipt with new create journal and add one product in voucher lines with tax.

Current behavior:

- Now, validate the same receipt and you will get a warning message like : 
 "The amount expressed in the secondary currency must be positive when account is debited and negative when account is credited."

Expected behavior:
When validating the receipt, it will create related journal entries.

Please see the video for more information.

Video/Screenshot link (optional):
https://drive.google.com/open?id=1Gngf9mRXXJYytfSbO0SNYzJqIcJId7_3

Let me know if anything required more information

@Yenthe666: can you please help us!
Thank you!

**Comment by sswapnesh** [comment]
> Video/Screenshot link (optional):
> https://drive.google.com/open?id=1Gngf9mRXXJYytfSbO0SNYzJqIcJId7_3

Its not accessible Publicly.

**Comment by sswapnesh** [comment]
It seems working well on Runbot http://578789-12-0-c93f37.runbot20.odoo.com/web?debug=1#id=3&action=692&model=account.voucher&view_type=form&menu_id=327

![screenshot-578789-12-0-c93f37 runbot20 odoo com-2019 08 02-22-19-05](https://user-images.githubusercontent.com/16624719/62385766-8fcdb380-b573-11e9-9d46-f0998f20e1e8.jpg)

**Comment by rohitramnani1994** [comment]
Thanks for your response!

can you please try with multi currency and create new journal in different
currency and create a new record with that journal.

Hope you understand!

**Comment by rohitramnani1994** [comment]
> > Video/Screenshot link (optional):
> > https://drive.google.com/open?id=1Gngf9mRXXJYytfSbO0SNYzJqIcJId7_3
> 
> Its not accessible Publicly.

@sswapnesh 
permission granted, please check video and help me
https://drive.google.com/open?id=1Gngf9mRXXJYytfSbO0SNYzJqIcJId7_3

**Comment by sswapnesh** [comment]
> can you please try with multi currency and create new journal in different
> currency and create a new record with that journal.
> 

@rohitramnani1994  Yes, Company(base) currency is USD, Journal currency is EURO.
Check Runbot http://578789-12-0-c93f37.runbot20.odoo.com/web?debug=1#id=3&action=692&model=account.voucher&view_type=form&menu_id=327 yourslef to check configuration (Might be I missing out something there)

> permission granted, please check video and help me
> https://drive.google.com/open?id=1Gngf9mRXXJYytfSbO0SNYzJqIcJId7_3

Are you sure ?
![screenshot-drive google com-2019 08 03-15-20-29](https://user-images.githubusercontent.com/16624719/62410376-4d06ec80-b602-11e9-9f85-7a1dc591075e.jpg)

**Comment by sswapnesh** [comment]
@rohitramnani1994  I have added Fix at https://github.com/odoo/odoo/pull/35422, Feel free to test.
Thanks.

**Comment by rohitramnani1994** [comment]
@sswapnesh Thank you!
waiting for merge in 12.0
