### ISSUE TITLE
How to create a group of wholesalers

### ISSUE THREAD

**Issue by Parsia** [odoo/odoo#35424]
Impacted versions: 12

Current behavior: I couldnt find any way to create a group of contacts.

Expected behavior: Is there any way to allocate contacts to a wholesale group? I want to allocate a pricelist to a group in which there are some contacts.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
