### ISSUE TITLE
Negative time value with less than 1h (e.g. -0.5h) results in 00:30 instead of -00:30 in qweb

### ISSUE THREAD

**Issue by rm-jawengo** [odoo/odoo#35459]
The last changes at the following method hasn't fixed the bug. It has changed the bug to another bug. Now all float times between -0.001 und - 0.999999 will result in a positive time (e.g. 00:45) instead of a negative time (e.g. -00:45).

https://github.com/odoo/odoo/blob/3682232d1e547440419b0a3a035da25fa0b04822/odoo/addons/base/ir/ir_qweb/fields.py#L377

**Comment by pedrobaeza** [comment]
Who did the commit?

**Comment by Yenthe666** [comment]
@kebeclibre did work on this at https://github.com/odoo/odoo/commit/44ea58234ec0d902ddf0caf7aefb367acc013627#diff-e796826fc513aa484f999d8347577ef8

**Comment by pedrobaeza** [comment]
If you are going to open a PR, don't open an issue. Put directly the issue text on the PR. Closing this one now that there's a PR.
