### ISSUE TITLE
sale.order.line object has no attribute 'layout_category_id'

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#35463]
Impacted versions:12.0

Steps to reproduce:
add a line   _order_lines_layouted_ of sale order replace in[report_saleorder_document line](https://github.com/odoo/odoo/blob/12.0/addons/sale/report/sale_report_templates.xml#L69)
```    
<t t-foreach="doc.order_lines_layouted()" t-as="page">
            <table class="table table-sm o_main_table">
...
        </table>
      </t>
```

Current behavior:
```
 File "/opt/odoo/odoo12.e/odoo/addons/sale/models/sale.py", line 779, in <lambda>
    for category, lines in groupby(self.order_line, lambda l: l.layout_category_id):
AttributeError: 'sale.order.line' object has no attribute 'layout_category_id'

Error to render compiling AST
AttributeError: 'sale.order.line' object has no attribute 'layout_category_id'
Template: sale.report_saleorder_document
Path: /templates/t/t/div/t[2]
Node: <t t-foreach="doc.order_lines_layouted()" t-as="page">
                        <table class="table table-condensed">
```

**Comment by pedrobaeza** [comment]
This is because your wild replace. You should do your custom development in other way.

Closing as no Odoo issue.

**Comment by m3asmi** [comment]
the function is still in [sale.order](https://github.com/odoo/odoo/blob/12.0/addons/sale/models/sale.py#L772)

**Comment by pedrobaeza** [comment]
Yeah, but it's not used by any piece of code inside Odoo. You simply mustn't call that method. It has been removed already in master AFAIK.

**Comment by ap-wtioit** [comment]
Also ran into this issue with an odoo 12.0 migration, closing it does not really help.

Can we remove order_lines_layouted() in odoo 12.0 (it is not working and never called in official odoo code)? Currently in migrations i think a better error would be having order_lines_layouted() missing instead of it throwing an error that a field is missing.

**Comment by pedrobaeza** [comment]
As said, don't use that code. I know it's not the best option, but can't qualify to a bug if it's not being used in any place in standard Odoo.

**Comment by ap-wtioit** [comment]
https://cwe.mitre.org/data/definitions/561.html
