### ISSUE TITLE
Disable inactive views in website (in other words, allow to disable /website/info)

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#3546]
Impacted versions:

- 8.0-8e6d5be (and probably any 8.0 version).

Steps to reproduce:

1. Install website module.
2. Navigate to `/website/info`.
3. Realize you don't want to tell to the world which modules you installed.
4. Go to Settings - User Interface - Views.
5. Search the view "Odoo Information".
6. Edit it and uncheck "active".
7. Repeat step 2.

Current behavior:

- The view still renders.

Expected behavior:

- View not rendered.

Additional suggestions (IMHO):

- This feature should be documented and clearly warned.
- This feature should not be enabled by default because it exposes installation information from the that probably most users don't want to display.
- This feature could be in an external module for easier maintenance by the web admin.
- [Related forum question](https://www.odoo.com/forum/help-1/question/hide-website-info-page-64665).

**Comment by Yajo** [comment]
Reading [the source](https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_ui_view.py#L171), I can see now that the `active` checkbox does not do what I was expecting. It's only used when extending views.

After a recent update, [there's a message saying *To hide this page, uncheck it from the top Customize menu.*](https://github.com/odoo/odoo/blob/8.0/addons/website/views/website_templates.xml#L462), but you cannot actually do it. That menu does not have anything to disable the info view.

**Comment by mart-e** [comment]
Hello,

Indeed there was supposed to have an option to disable it. It is now done. So no longer need strange workaround.
Also it's true some of the information were sensitive like the exact list of modules. We have restricted the public information displayed adding groups for technical users only.
Thank you for the report.

(PS: please avoid +1 comments really not adding anything to the discussion)

**Comment by nhomar** [comment]
@mart-e 

In your commit says that you left only apps publically availables.

There is a technical reason for such decision?, can it be blocked also?.

Regards.

**Comment by mart-e** [comment]
@nhomar if you disable the option"Show Odoo Information" in customize menu (available on `/website/info` page), the whole page will be empty so no more information. The list of apps is only for those who do not change the setting.
