### ISSUE TITLE
Invoing wizard do not create the fiscal year and the account periods.

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#3547]
Hello, I trying to create a fiscal year and periods using the account.config.settings wizard at Settings > Configurations > Invoicing. I fill the requested fields (date start, date stop, and the type of the new periods to be create). Then I click the Apply button, the wizard run correctly but the fiscal years and periods were not created. 

I follow all the steps indicated in https://doc.odoo.com/book/3/3_9/periods_and_fiscal_years/ to create the fiscal year using the Settings > Configurations > Invoicing wizard.

I made this test using Openerp 7 and Odoo 8.0 in a local instance in my computer, this because the runbot have data demo including already created fiscal years and periods, and the unit test need to have not data demo about fiscal years and periods. In both versions, 7.0 and 8.0 the same problem was shown. I add a video with the test at http://youtu.be/wVdsZCF2XV8 

Note: please check the resolution of the video to more detail, recommended 720p

Intances revnos were the test was run:
7.0: server 5318 addons 10123 web 4197
8.0: odoo  6239cf5c493c0f20dbaa40a941b45eaccceb120e

What I get:
No fiscal year and periods were created.

What I expect:
A new fiscal year and 12 periods associated need to be created.

**Comment by mart-e** [comment]
Hello,
As discussed on the support ticket, the configuration was not very clear but you need to install a chart of account to get a fiscal year. Made it more clear with a tooltip.
Regards
