### ISSUE TITLE
Creating a user also calls a write method

### ISSUE THREAD

**Issue by Gumaa** [odoo/odoo#35480]
**Impacted versions:** 12.0 Community

**Steps to reproduce:** 
- Create group with _read_ and _create_ access on a res.users model
- Create a user and give him this group
- Try to create new user with this user

**Current behavior:** 
User with access to **create** a record is unable to create user and gets error that he does not have write access. 
![20190805_153032](https://user-images.githubusercontent.com/16503469/62523281-b91c6700-b833-11e9-831d-694e50b9e07f.png)

**Expected behavior:** 
User with create access is able to create new records - but not to edit them.

**Comment by pedrobaeza** [comment]
This is because `res.users` is an inherited by delegation model of `res.partner`, so you need permissions to that model as well.

Closing as no issue at all.

**Comment by Gumaa** [comment]
But even when I have all the permissions on `res.partner` (read, write, create, delete) it still says that I don't have write permission on res.users. This makes no sense.

**Comment by pedrobaeza** [comment]
This is because there's a lot of involved models in that operations (followers, messages...), so you have to start from a regular user with basic permissions, not an isolated one.
