### ISSUE TITLE
[8.0] refund cleanup lines call in old api and method definition in new api 

### ISSUE THREAD

**Issue by jorgescalona** [odoo/odoo#35501]
Impacted versions:
8.0
Steps to reproduce:

1. From a previously validated account.invoice and with its transferred lines
2. Reverse invoice
3. In the wizard define Refund Method = **"Modify: create the refund, reconcile and create a draft invoice"**.
4. Define description.
5. Click on button **"Create Refund"**

Current behavior:

throws a traceback error of incompatibility between new and old Api.
![err_revert_fact_05082019_01](https://user-images.githubusercontent.com/11073475/62547440-968e4c00-b83b-11e9-9039-7272de88bff8.png)

Expected behavior:

Creation of the return and the details of the draft invoice in draft.

- It is of interest to note that the base code of the version the [declaration of the method](https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L1064) is in new api and [the call](https://github.com/odoo/odoo/blob/8.0/addons/account/wizard/account_invoice_refund.py#L194) to it in old api

- Aftaer in version 9.0 [the call](https://github.com/odoo/odoo/blob/9.0/addons/account/wizard/account_invoice_refund.py#L89) if it was changed to new api.

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
8.0 and 9.0 are deprecated versions.
