### ISSUE TITLE
[master] account_reports: Traceback in trial balance

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#35514]
Impacted versions:
master

Steps to reproduce:
1. Create a new database (Is necessary without journal entries)
2. Install account_accountant
3. Open the trial balance

Current behavior:
I get the next traceback:
![Screen Shot 2019-08-07 at 1 27 03 AM](https://user-images.githubusercontent.com/7606656/62600124-b5c8c000-b8b3-11e9-8b23-642ddfb087ac.png)

Expected behavior:
The trial balance is shown with empty data

Note: I do not test in your runbot, because runbot has journal entries posted.

**Comment by jco-odoo** [comment]
@smetl
