### ISSUE TITLE
Follow Up - Customer Payment Promise is kept on completion

### ISSUE THREAD

**Issue by spadae22** [odoo/odoo#3553]
When you click 'Mark as Done' the Customer Payment Promise from the last promise is kept. It should not. This is confirmed on http://26603-8-0-b8efdb.runbot6.odoo.com/web?db=26603-8-0-b8efdb-all#id=1583&view_type=form&model=res.partner&menu_id=74&action=60

As the message " I will not go away" does not.

**Comment by Yenthe666** [comment]
Hi @spadae22 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
