### ISSUE TITLE
[FR] Implement json serializer interface on fields

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#35533]
Please implement a json serializer interface on the `fields.Field` type.
Currently there is a silo implementation in `date_utils.json_defaults` for the `fields.Date` and `fields.Datetime` types.
Defining new field types is a powerful means to extend the framework for new use cases.
Therefore an interface is useful, needed. As generic it is also safe.

/cc @agentdeu

**Comment by blaggacao** [comment]
If anyone things about a `convert_to_json` please note that according to the [docs](https://docs.python.org/3/library/json.html#json.dump) it looks like it shall rather be `convert_to_json_encodable`

**Comment by Elkasitu** [comment]
You might be interested in #35595
