### ISSUE TITLE
[master] By default the field **PArtner ID** is not in the list of customer invoices.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#35545]
Impacted versions:

[master]

**Steps to reproduce:**

Go to list view of Invoices.

**Current behavior:**

![image](https://user-images.githubusercontent.com/338634/62646152-42ef3180-b913-11e9-865f-edd26b9b57b6.png)

**Expected behavior:**

Have the aprtner **by default** with no configuration required (I know I can add it with new custom list view) but the partner is a key field on invoices....

Video/Screenshot link (optional):

**Comment by nhomar** [comment]
I correct myself: **It is not possbile** even with the new custom widget.

![image](https://user-images.githubusercontent.com/338634/62646339-bd1fb600-b913-11e9-89ef-fa3fee36dc8d.png)

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/35531

**Comment by Yenthe666** [comment]
Indeed, I guess we can close this one off?

**Comment by nhomar** [comment]
@Yenthe666 let's wait the merge, once done I'll close it myself. (I have a long list of pending stuff)

**Comment by sswapnesh** [comment]
>  let's wait the merge.

#35531 has been merged.

**Comment by nhomar** [comment]
NICE
