### ISSUE TITLE
[8.0] BUG When creating a new sale order with a text int the customer filter

### ISSUE THREAD

**Issue by javierjcf** [odoo/odoo#3554]
If you go to sale orders list view and write a text in the searchbox in order to filter a client, if you click create button with the text in the checkbox an error is raised, something like this:

```
File "/home/bak/runbot/extra/runbot/static/build/26525-8-0-ccba67/openerp/models.py", line 3226, in _read_from_database
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/home/bak/runbot/extra/runbot/static/build/26525-8-0-ccba67/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/bak/runbot/extra/runbot/static/build/26525-8-0-ccba67/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "hu"
LINE 2:                     WHERE res_partner.id IN ('hu') AND (TRUE…
```

It seems to be in the customer filter, because if you search a sale order is not raised.

**Comment by Yenthe666** [comment]
Hi @javierjcf ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
