### ISSUE TITLE
[12.0] BUG in _on_login_cooldown

### ISSUE THREAD

**Issue by rodrig92** [odoo/odoo#35544]
Hi,

https://github.com/odoo/odoo/blob/3f634f29bd042b7e13b8e48507f8aa7a3a7ec50c/odoo/addons/base/models/res_users.py#L837

The correct return value is False. "<login_cooldown_after>th (0 to disable)."

To reproduce:
Follow the instructions in the previous method "_assert_can_auth(self)":
"Login attempt ignored for %s on %s: "
"%d failures since last success, last failure at %s. "
"You can configure the number of login failures before a "
"user is put on cooldown as well as the duration in the "
"System Parameters. Disable this feature by setting "
""base.login_cooldown_after" to 0."

You can't singin in Odoo

Regards.

**Comment by pedrobaeza** [comment]
@odony @KangOl can you please check this?

**Comment by odony** [comment]
Looks right, @xmo-odoo that would be for you. I guess not many people tried to disable it. ;-)

**Comment by sswapnesh** [comment]
>I guess not many people tried to disable it. ;-)

We can do this by deleting  ICP `'base.login_cooldown_after'` but still add considering 
`        :returns: whether the user is currently in cooldown phase (true if cooldown, false if no cooldown and login can continue)` on docstring it can be consider this as Bug
