### ISSUE TITLE
Stock Not showing in Product Master, SO and DO after latest pull - 10-11-2014

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#3555]
After updating latest code. System not showing stock level in product master, sale order and delivery note. Steps to reproduce
1. Create a new product (Real Price - Costing, Real Time Valuation and Anglo Saxon Accounting)
2. Purchase the same 500 qty
3. Check the Stock Valuation Report in Reports warehouse its working fine showing 500 qty
4. Check Stock Move its showing 500 qty
5. Go to product template and variant - In inventory tab showing 0 stock
6. Go to Sales Order and select the product its showing 0 stock
7. Confirm Sales Order and got to delivery order - Showing waiting availability.

**Comment by Yenthe666** [comment]
Hi @orchidinfosys ,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
