### ISSUE TITLE
Angolan Localization

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#35592]
Hello,

We are developing the localization for Angola, and it will require the translation of several terms that differ from Portuguese of Portugal. There aren't any language differences between Portugal and Angolan Portuguese, but there are a lot of technical terms that are different.

The issue is that there is no pt_AO available yet, and we don't really know how to proceed in order to make it available both in Odoo and in Transifex.

Thank you.

**Comment by mart-e** [comment]
Hello,

See this wiki page: [How to translate my chart of account into multiple languages?](https://github.com/odoo/odoo/wiki/Translations#how-to-translate-my-chart-of-account-into-multiple-languages)
The chart of account must be explicitly set as translatable, this is done by depending of the module `l10n_multilang`.
As the language `pr_AO` is not available yet in Odoo, you can submit a PR to add it in the [res.lang.csv](https://github.com/odoo/odoo/blob/9269e876fd62e51360d695342f0634dffdf6f87d/odoo/addons/base/data/res.lang.csv) file and I will integrate it.

**Comment by mart-e** [comment]
For technical terms that are outside of a l10n module, you can simply create a PR to add them. We do not add the regional versions of a language on Transifex but can accept PR with translations of the terms that are different from the reference language (Portuguese in your case).
I hope it helps

**Comment by reinaldoramosarxi** [comment]
Thank you.

The created pull request is at https://github.com/odoo/odoo/pull/35600.
