### ISSUE TITLE
is it possible i upload this odoo repository to my web hosting? for live usage?

### ISSUE THREAD

**Issue by Hamzaqureshi401** [odoo/odoo#35606]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
