### ISSUE TITLE
[12.0][OE]account_predictive_bills: predicting different company's account

### ISSUE THREAD

**Issue by bizzappdev** [odoo/odoo#35607]
Impacted versions: V12 Enterprise version

Steps to reproduce:
Have a multi-company environment.
Company A
Company B
configure chart of account for Company A 
configure chart of account for Company B

Create an account in company A with sla in the name of the account. and type expense or any type group with expense type

create the vendor bill for company B
the current user has to be company B
No superuser should be used.
select then vendor.
add the new line instead of selecting product just add the description in the line 'sla' or 'bla bla - sla'
make sure no account is preselected.

now from account_predictive_bills module, it is trying to predict the account.
as it does not have any old invoice from company B it is trying to predict based on account.
and there it goes wrong.
https://github.com/odoo/enterprise/blob/12.0/account_predictive_bills/models/account_invoice.py#L124
this do not have company in where condition. which is causing the Company A account in the result. and trying to use that account for company B invoice.

**Comment by Yenthe666** [comment]
@bizzappdev why don't you guys report it through odoo.com/help though with an OPW?
@qdp-odoo for your interest!

**Comment by bizzappdev** [comment]
PR created https://github.com/odoo/enterprise/pull/5088

@Yenthe666 we will also do that thanks

**Comment by Yenthe666** [comment]
🎈
