### ISSUE TITLE
[12.0] sale.order.line unit price doesn't calculate correctly when a fiscal position applies a new 'included' tax

### ISSUE THREAD

**Issue by vincentius** [odoo/odoo#35605]
Impacted versions:
12.0

Steps to reproduce:
- Create 2 identical VAT codes with VAT included in the price (eg. 6% INCL and 6% INCL (Copy))
- Create a fiscal position that replaces the 6% INCL by 6% INCL (Copy)
- Create a product of 10 EUR that has 6% INCL in its Tax ID's
- Create a sale order with the fiscal position that we defined earlier
- Create a sale order line with the product we created earlier

Current behavior:
Unit price of the sale order line is set to 9.43

Expected behavior:
Unit price of the sale order line should be set to 10

Video/Screenshot link (optional):
https://youtu.be/jfQgihNV28M

**Comment by intero-chz** [comment]
Since when is the `price_unit` changed by taxes anyways?? Did i miss a change?

**Comment by pedrobaeza** [comment]
Closing due to the feedback given in #34604
