### ISSUE TITLE
(master) account: Use another var for Journal Entry Type other than `type`

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35617]
Impacted versions:
master

type is a reserved keyword of python
https://github.com/odoo/odoo/blob/master/addons/account/models/account_move.py#L91

```
    type = fields.Selection(selection=[
            ('entry', 'Journal Entry'),
            ('out_invoice', 'Customer Invoice'),
            ('out_refund', 'Customer Credit Note'),
            ('in_invoice', 'Vendor Bill'),
            ('in_refund', 'Vendor Credit Note'),
            ('out_receipt', 'Sales Receipt'),
            ('in_receipt', 'Purchase Receipt'),
        ], string='Type', required=True, store=True, index=True, readonly=True, tracking=True,
        default="entry")
```

**Comment by Yenthe666** [comment]
@qdp-odoo would a PR be accepted to change this in master (after the big accounting apocalypse)?

**Comment by Yenthe666** [comment]
same for survey by the way (https://github.com/odoo/odoo/blob/344d20a6c40e2be73af3dbdb32ce9a2fa721ca01/addons/survey/models/survey.py#L437) so it is the same in multiple places.

**Comment by sswapnesh** [comment]
> same for survey by the way (
> 
> https://github.com/odoo/odoo/blob/344d20a6c40e2be73af3dbdb32ce9a2fa721ca01/addons/survey/models/survey.py#L437
> 
> ) so it is the same in multiple places.

At 33 Places actually

**Comment by Yenthe666** [comment]
I think we should rather ask @mart-e what he thinks about changing all of these. I remember that somebody from Eficent (@jbeficent maybe you know?) has made a PR at some point for this i believe?

**Comment by jbeficent** [comment]
Yes, @mreficent proposed to change all type names

**Comment by mart-e** [comment]
Indeed we started to rename it but it was a bit tricky and we stopped as it introduced regressions (we had to revert one that was causing issues with the runbot for instance).
@hbto what is blocking you? Even if not ideal, it should not block you to have a field name `type`

**Comment by hbto** [comment]
@mart-e we can live with it, but should keep in mind this for next releases. 
I am aware you, all Odoo team, have made a great job with this new release and several keywords related to python were changed. But the introduction of this on a very core model like `account.move` will be something hard to be taken away in the future, as you mentioned, it was causing issues now, let us think the headaches that it will cause for v14, not only for you, but for the rest of the community.

Regards.
