### ISSUE TITLE
(master) account: Journal Items created from automatic reconciliation are not linked to Reconciliation models

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35615]
Impacted versions:
master

Check the video (2m 51s)
https://youtu.be/1xs44K-RmSA

At the request of people who do not watch videos here are the steps in indexable format text

- Step 1: Create a Reconciliation Model
-- Select Suggest Counterpart values
-- Do *not* select To check
-- Set a Label to use: Match Regex: set your label
-- Set an account 

Something like this could be useful
<img width="1155" alt="Screen Shot 2019-08-09 at 10 17 29 PM" src="https://user-images.githubusercontent.com/7598010/62816892-a20b9c80-baf3-11e9-84cb-5037f03742bb.png">

- Step 2: Create a Bank Statement
-- Be careful and try to use in the label the same label you set in step 1.

This could make the case
<img width="1070" alt="Screen Shot 2019-08-09 at 10 18 30 PM" src="https://user-images.githubusercontent.com/7598010/62816927-fadb3500-baf3-11e9-8c9d-0733b5a696d4.png">

- Step 4: Reconcile
-- Hit the `Reconcile` Button and then you are presented with something like this

A suggestion to reconcile is shown
<img width="1164" alt="Screen Shot 2019-08-09 at 10 22 13 PM" src="https://user-images.githubusercontent.com/7598010/62816944-4392ee00-baf4-11e9-8589-d7798d48acc9.png">

Do not forget to hit `reconcile`.

- Step 5: Check the Reconciliation Model

As you can see Journal Entries created from this reconciliation model are counted and can be displayed if `Journal Entries` button is clicked.

<img width="1164" alt="Screen Shot 2019-08-09 at 10 24 34 PM" src="https://user-images.githubusercontent.com/7598010/62816964-881e8980-baf4-11e9-882c-d6ecd5e046db.png">

- Step 6: repeated Step 1. but this time choose ` To check` option

<img width="1164" alt="Screen Shot 2019-08-09 at 10 27 09 PM" src="https://user-images.githubusercontent.com/7598010/62816994-f6fbe280-baf4-11e9-818f-2beb6bb93060.png">

- Step 7: Add a new bank statement line using the label in your step 6.

<img width="1077" alt="Screen Shot 2019-08-09 at 10 29 03 PM" src="https://user-images.githubusercontent.com/7598010/62817014-480bd680-baf5-11e9-856e-a0ec848ec0f3.png">

- Step 8: Do not forget to hit reconcile:

Check that the reconciliation has been automatically performed

<img width="1157" alt="Screen Shot 2019-08-09 at 10 31 58 PM" src="https://user-images.githubusercontent.com/7598010/62817025-8acdae80-baf5-11e9-9a08-72d6adfc8adc.png">

- Step 9: check on the reconciled Journal Items by click the link.

<img width="593" alt="Screen Shot 2019-08-09 at 10 33 56 PM" src="https://user-images.githubusercontent.com/7598010/62817040-d08a7700-baf5-11e9-9aec-9413d9a32bc3.png">

- Step 10 - Check the Item lines by grouping them by Reconciliation Model

They are not linked to the Reconciliation Model that created them
<img width="1255" alt="Screen Shot 2019-08-09 at 10 35 27 PM" src="https://user-images.githubusercontent.com/7598010/62817057-029bd900-baf6-11e9-9058-93477083f470.png">

<img width="1092" alt="Screen Shot 2019-08-09 at 10 36 42 PM" src="https://user-images.githubusercontent.com/7598010/62817075-3aa31c00-baf6-11e9-96bc-e207ba8af3ba.png">

Regards

**Comment by qdp-odoo** [comment]
was fixed in the meanwhile
