### ISSUE TITLE
Autosubscribe message send to document owner

### ISSUE THREAD

**Issue by rquevedo** [odoo/odoo#35612]
Impacted versions: 10.0

Steps to reproduce: Login with user diferent from Administrator and create an Invoice(Or other object that have user_id field)

Current behavior: Send a mail message to mail address of logged in user(document creator)

Expected behavior: Dont send a mail message. Mail would be sent if other user assign a document to logged in user.

Video/Screenshot link (optional): I think that issue is caused by a sudo call in Invoice create. In odoo/addons/mail/models/mail_thread.py in method "message_auto_subscribe" there is a code to avoid notify to author `user_pids = [user_pid for user_pid in user_pids if user_pid != self.env.user.partner_id.id]` but in this case self.env.user.partner_id.id is alwais Administrator because sudo call and alwais evaluate negative.

**Comment by pedrobaeza** [comment]
Yeah, I agree this is not optimal. @william-andre @qdp-odoo can you please tell us about this?

**Comment by qdp-odoo** [comment]
it's not a bug, it's a feature

**Comment by rquevedo** [comment]
> it's not a bug, it's a feature

Hi @qdp-odoo, if we guide by code comment the author wants to send a mail message to users when they not be the authors. This code works ok but in others modules call create or write with sudo and user_id change to "Admin". This behavior full user inbox with notifications without value(The user knows that an invoice was created). In one small size company Pos manager user receive about 50 mails in a day.
