### ISSUE TITLE
Invoicing: tax not carried over to the extra move

### ISSUE THREAD

**Issue by koljenovic** [odoo/odoo#3562]
1. SO is confirmed and the order sent to be fulfilled by the WH (to be invoiced On Delivery Order), tax rate specified for items
2. WH (for whatever reason) transfers a bigger quantity than the SO specifies
3. An invoice is created, reflecting the original quantity and the extra move for the added quantity, **but the tax rate selected for the item is not applied to the extra move**, as shown in the image below
4. Also IMHO the _Description_ field for the extra move is discontinuous with the other values, as it follows the form of "Extra move:" + product_name, this causes a minor issue when you have product variants, as in this case where only the parent product name is shown instead of the variant name.

I would like to add that it would make more sense not to split the original and the extra move QTY in the invoice, as the invoice is primarily supposed to render the summarized information of financial relevancy, contrary to the delivery order which is supposed to track the "real" product.

![invoice](https://cloud.githubusercontent.com/assets/236839/4994419/1d02a58c-69b9-11e4-9581-03fd8b2e2197.png)

**Comment by Yenthe666** [comment]
Hi @koljenovic ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
In V9 and up this behaviour changed so there should be nothing to do here.

Regards,
Yenthe
