### ISSUE TITLE
[master]  Not possible more than 1 current year earning.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#35620]
Impacted versions:

master

Steps to reproduce:

Create more than 1 **Current year earning** account.

Current behavior:

```
    raise ValidationError(_('You cannot have more than one account with "Current Year Earnings" as type. (accounts: %s)') % [a.code for a in account_unaffected_earnings])
odoo.tools.convert.ParseError: "You cannot have more than one account with "Current Year Earnings"
```

Expected behavior:

Allow more than one:

In some countries (that follows IFRS) for example **Perú** the year earning are asked per category and business line, then it is normal to ask for more than one.

**Allow more than one account**

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@jco-odoo for your interest.
