### ISSUE TITLE
[v8] Barcode interface skips scans

### ISSUE THREAD

**Issue by npiganeau** [odoo/odoo#3564]
## Impacted versions:

8.0 
## Steps to reproduce:
- Open a v8 runbot
- Go to warehouse/barcode interface and select any picking
- Scan several times the same product in the picking to increase the quantity, with minimu delay between the scans 
## Current behavior:
- If the scans are not spaced of at least 2 seconds (which is unusable in real life) the last scans are skipped. Let say you scanned 5 times, the quantity would increase by 2 or 3 depending on the delay between each scan.
- Oddly, if you try to scan again, the quantity will not increase until you reached again the initial quantity.Example:
  - You scanned 5 times in the first place
  - The interface only increased the quantity by 2
  - You need to scan 4 more times (5 - 2 +1) to get a new increase in quantity of 1 (and you have to keep a long delay between scans)

Note that my barcode scanner gives the correct output in a text file.
## Expected behavior:

The quantity scanned is displayed correctly on the interface even if the delay between different scans is short.

Looks like the barcode interface does not buffer properly the barcode scanner inputs

**Comment by npiganeau** [comment]
I pushed a PR that solves the issue. 

The interface still takes a huge amount of time to record the scans, but at least it doesn't skip any anymore. I tried 10 scans in less than 2 seconds both on default_code and ean13 and it worked like a charm.

**Comment by zhavir** [comment]
where PR is stored? can you give me the link? thank you

**Comment by npiganeau** [comment]
Just above... #4637.

If you prefer a module, I have created a fix_barcode_scanner module which does the same in https://github.com/ndp-systemes/odoo-addons

**Comment by Yenthe666** [comment]
Hi @npiganeau ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: The interface and scanning functionality have been fully rewritten in V9 so this shouldn't be a problem anymore.

Regards,
Yenthe
