### ISSUE TITLE
[12.0] Product Warranty

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#35641]
Impacted versions: All versions

Steps to reproduce: I want to be able to register a warranty period at a product, making it possible for the "sales team" to see if they should accept a "return" or not.

Current behavior: Currently there is no field that allows to set the warranty on a product, there is no logic between the shipment date and the warranty. Meaning Sales team has to calculate manually the warranty based upon the shipment date and the date the customer calls or emails, which is very easy to make a mistake and costs lots of time.

Expected behavior: Set a specific "warranty in months" at a product, when creating a "return" the system should indicate the months left under warranty. When the period is negative, the system should give a message making it clear that the warranty has passed.

**Comment by pedrobaeza** [comment]
This is not an issue, but a feature request. On v13, you will have on enterprise an RMA system, so this may be covered by it.

Meanwhile, closing as above explanations.

**Comment by BusinessAgilityMasters** [comment]
> This is not an issue, but a feature request. On v13, you will have on enterprise an RMA system, so this may be covered by it.
> 
> Meanwhile, closing as above explanations.
This is also available in version 12.0, the field "Warranty Expiration" but it is a manual field when creating a "Repair Order":
![image](https://user-images.githubusercontent.com/39414107/62859048-5b3cc300-bcfc-11e9-8160-5408d85c4e4e.png)

Is there a possibility to request new features?

**Comment by pedrobaeza** [comment]
Yes, that field is only informative. As said, please explore v13 where a new RMA system is included in enterprise.

New features in stable are forbidden due to stability policy.

You can search for third party modules in current version that add this feature as well.
