### ISSUE TITLE
[8.0] Multi-Company MO Sequence Error

### ISSUE THREAD

**Issue by damlu** [odoo/odoo#3565]
If using multiple companies, and each has its own mrp.production (Production order) sequence, it is possible for a procurement to generate an MO using the wrong sequence.

**Steps to reproduce:**
1.) Create at least two companies. (A, B)
2.) Create a warehouse for each company.
3.) Create a Production order sequence for each company.
4.) Set procurement method of a product in Company B to "Manufacture".
5.) Request procurement of the product.

**Expected Behaviour:**
  A Manufacturing Order is created for the product using Company B's MO sequence.

**Actual Behaviour:**
  A Manufacturing Order is created using the sequence of whichever company the SUPERUSER  currently belongs to.

**Relevant code:** Line 97 of addons/mrp/procurement.py

96:`#create the MO as SUPERUSER because the current user may not have the rights to do it (mto product launched by a sale for example)`
97:`produce_id = production_obj.create(cr, SUPERUSER_ID, {`

**Comment by Yenthe666** [comment]
Hi @damlu ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: If you ever face bugs like this again and you know how to fix them then please create a PR. They get a higher priority then the bug reports. 😉 

Regards,
Yenthe
