### ISSUE TITLE
Reconciliation lines not matched

### ISSUE THREAD

**Issue by gediminasvenc** [odoo/odoo#35650]
Impacted versions: 12ce, 12ee

Steps to reproduce:
Register payment for any invoice or vendor bill for example:
![image](https://user-images.githubusercontent.com/19407260/62863071-71547e80-bd10-11e9-9bae-e5be28cacf87.png)
Make a manual payment, add bill name, date and amount. Like in the screenshot:
![image](https://user-images.githubusercontent.com/19407260/62863138-9ea12c80-bd10-11e9-9674-4c6239264575.png)
And try to reconcile it:
![image](https://user-images.githubusercontent.com/19407260/62863171-bb3d6480-bd10-11e9-8846-edf61a8d09b2.png)

Current behavior:
Vendor bill payment is not found for automatic reconciliation (settings are set to communicate trough invoice number in accounting settings).
![image](https://user-images.githubusercontent.com/19407260/62863327-2129ec00-bd11-11e9-81bc-1b7d0d146ee4.png)

Expected behavior:
In v10 and v11 its working just fine, lines for reconciliation are matched. All tests were done in runbot

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you sure in v12 you have also the other line with 1.000,50 kr in the other side? That's the reason why it doesn't automatically matches.

**Comment by gediminasvenc** [comment]
But im trying to match 6250,00kr, and not 1000,50. And this was not a problem in earlier versions. If i add a partner in the payment line it matches straight away.
![image](https://user-images.githubusercontent.com/19407260/62863821-9b0ea500-bd12-11e9-81a8-cb26aa49a322.png)
Here is a match if the partner is added:
![image](https://user-images.githubusercontent.com/19407260/62863851-b679b000-bd12-11e9-8594-d75b8f88e9bb.png)

**Comment by pedrobaeza** [comment]
But again, are you sure on v11 this was working, or it happens the same?

**Comment by gediminasvenc** [comment]
@pedrobaeza you can try it, it takes only couple of minutes to try. And yes its working fine in v10 and v11

**Comment by pedrobaeza** [comment]
OK, it's enough if you tell me so.

@qdp-odoo has the matching algorithm changed in v12?

**Comment by pedrobaeza** [comment]
I have been toying with this recently and now matching goes through reconciliation models. You should have the standard default one called "Invoices Matching Rule", that has the mark "Partner Is Set & Matches". If you remove that check, it should behave the same as in v11.

**Comment by gediminasvenc** [comment]
@pedrobaeza hi, i have found it as well but you were quicker to submit it :) anyway, thank you for your help! Hope this issue will help people who don't know this new feature, thanks again!

**Comment by pedrobaeza** [comment]
Great, then let's close this as it's not an issue per se, but a change in configuration.
