### ISSUE TITLE
[All] base: Can't use an alternative dir for Unix Socket to the database

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#35669]
#### Impacted versions:
All
#### Steps to reproduce:
- Use a different location than **/var/run/postgres** for Unix Sockets in /unixsocket
- Set the **db_host** = /unixsocket
#### Current behavior:
- Odoo tries to connect to /unixsocket with TCP
#### Expected behavior:
- A Unix Socket connection is supposed to be used when a directory is being used in **db_host**

**Comment by nhomar** [comment]
Why do you need this option? (curiosity)

**Comment by gustavovalverde** [comment]
In this case, It's an already established infrastructure; which uses Unix Sockets on a different directory for security measures.

On my side, I also had this issue on **Google Cloud Platform**, using their Cloud SQL Proxy; which also uses a different directory for the Unix Socket (seems like doing this is a security standard). I was forced to use TCP in GKE because of this.

**Comment by gustavovalverde** [comment]
Related: https://github.com/odoo/docker/issues/265

**Comment by nhomar** [comment]
**interesting** AFAICR my team achieve (with the current code) do what you are trying to de.

**Comment by Yenthe666** [comment]
Hmm, most likely @xmo-odoo

**Comment by xmo-odoo** [comment]
@gustavovalverde seems to work fine. I edited the pg conf to alter "unix_socket_directories", restarted postgres, tried connecting without specifying anything (successfully which failed), providing the new directory via CLI (worked) and providing the new directory via the config file (also worked).

AFAIK Odoo just passes the db_host config as the `host` key to `psycopg2.connnect` (or as the `PGHOST` envvar if it needs to invoke psql externally), it doesn't do anything special itself.

**Comment by gustavovalverde** [comment]
Closing, as modifying the pg conf should be the right approach.
