### ISSUE TITLE
(master) account: Credit Notes Journal Entries are not updated when in multi-currency

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#35670]
Impacted versions:
master
Steps to reproduce:
- Set your currency rates (USD local currency):

![Screen Shot 2019-08-12 at 2 47 00 PM](https://user-images.githubusercontent.com/7598010/62893386-1884e600-bd10-11e9-8de4-ba8db9e8eac3.png)

- Create a Vendor Bill in Euros and Validate

![Screen Shot 2019-08-12 at 2 48 18 PM](https://user-images.githubusercontent.com/7598010/62893517-70235180-bd10-11e9-8c9c-b6f1fe782e3f.png)

- Check Journal Entry

![Screen Shot 2019-08-12 at 2 48 35 PM](https://user-images.githubusercontent.com/7598010/62893535-787b8c80-bd10-11e9-8da2-147e3c40b15b.png)

- Add a Credit Note

![Screen Shot 2019-08-12 at 2 50 53 PM](https://user-images.githubusercontent.com/7598010/62893609-9b0da580-bd10-11e9-9492-fe53cac747d6.png)

- Now let us check the preview Journal Entry, No changes are applied

![Screen Shot 2019-08-12 at 2 50 53 PM](https://user-images.githubusercontent.com/7598010/62893654-b8427400-bd10-11e9-8924-d74e4a342db5.png)

If validated, the Credit Note, the Journal Entry will be wrongly posted. It is not taking into account the accounting date to fetch de right currency rate. 

![Screen Shot 2019-08-12 at 2 56 07 PM](https://user-images.githubusercontent.com/7598010/62894096-a57c6f00-bd11-11e9-90de-2d19f7e98009.png)

Only after moving any of the fields that could trigger the change in debit/credit fields for multi-currency is that the fields are changed. This could lead to unintended results.

![Screen Shot 2019-08-12 at 2 58 17 PM](https://user-images.githubusercontent.com/7598010/62894110-ac0ae680-bd11-11e9-8ee3-6a9d92ca392c.png)
Look at the changes in the value because the Accounting date has changed.

Regards.

**Comment by smetl** [comment]
It will be fixed by https://github.com/odoo/odoo/commit/5d405332ec152a3ee195df5036ffad0d186bdc88

**Comment by smetl** [comment]
Fixed on saas-12.4
