### ISSUE TITLE
Avatar missing from the main screen and CRM on a fresh installation

### ISSUE THREAD

**Issue by luisvzqz** [odoo/odoo#35672]
Impacted versions:
12
Steps to reproduce:
1.Make a fresh install - Shows OK the Avatar !!
2. Install the CRM - DON'T show the avatar !!
Current behavior:
 Install the CRM - DON'T show the avatar !!
Expected behavior:
 Install the CRM - 
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_9_28](https://user-images.githubusercontent.com/24595734/62911111-a977b380-bd48-11e9-9c53-2f8213ca5a12.png)
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_9_27](https://user-images.githubusercontent.com/24595734/62911114-aaa8e080-bd48-11e9-8a28-9e129695544b.png)

show the avatar !!
Video/Screenshot link (optional):

**Comment by luisvzqz** [comment]
The problem happens with any app that you install from the fresh installation !! Help !!!
Thanks, 
-LV
![AwesomeScreenshot-dev-360fin-mx-web-2019-08-12_9_39](https://user-images.githubusercontent.com/24595734/62911335-a3ce9d80-bd49-11e9-9f90-6274212cd1f9.png)

**Comment by nhomar** [comment]
I think this is a cache problem on you deployment, did not you have several DB's on your test environment?

**Comment by luisvzqz** [comment]
On this development machine I have 3x dbs, running one a time, but in the
production sites I only have one dbs running, and it happens the same
behaviour, thanks for your advice, -LV
_____________________________
Luis Vázquez
Chief Empowerment Officer
e. luis.vzqz@mulaware.com
t. +52.1.553147.7941
w. www.mulaware.com

**Comment by pedrobaeza** [comment]
I can confirm this is a problem on your deployment, as I haven't faced that problem in my local, staging or productions DBs, so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by luisvzqz** [comment]
Pedro, can you please give me a heads up then, why it was working ok, and suddenly it stop working ? thanks, -LV

**Comment by pedrobaeza** [comment]
Why don't you try to reproduce the problem in runbot using base database (http://runbot.odoo.com/ - admin/admin).
