### ISSUE TITLE
[12] Mixed content on customer invoices

### ISSUE THREAD

**Issue by cgarnier** [odoo/odoo#35671]
Impacted versions:
12 (docker)
Steps to reproduce:
Send an invoice by mail, click on the button in the mail.
Current behavior:
The invoice page dont load correcly. The preview doesnt display and there is a mixed content error in the preview.
Expected behavior:
Load with no error and wither the preview.

Video/Screenshot link (optional):

![Capture d’écran de 2019-08-12 23-11-43](https://user-images.githubusercontent.com/1249958/62898914-ea76c480-bd56-11e9-89e6-7c72788c3ee7.png)

http is redirected to https by the loadbalancer (traefik)
web.base.url starts with https
web.base.url.freeze is True

**Comment by pedrobaeza** [comment]
This is something on your deployment, as I don't get that problem in mine. Check your proxy configuration, werkzeug version and so on.

Closing meanwhile there's no more proof of Odoo itself issue.

**Comment by cgarnier** [comment]
Please dont close it until i didnt find where is the issue.

**Comment by pedrobaeza** [comment]
I will open it when that happens.

**Comment by cgarnier** [comment]
I found that the src link of the iframe:
`https://xxxx/my/invoices/6?access_token=448fa9da-1338-42cd-9df8-b6f71f081f8b&report_type=html`

is making a 302 redirection to `http://xxxx/FR_fr/my/invoices/6?access_token=448fa9da-1338-42cd-9df8-b6f71f081f8b&report_type=html`

It s what is causing the mixed content. 
I dont understand yet why odoo is redirecting with a http link.

**Comment by pedrobaeza** [comment]
As said, that's because your proxy or werkzeug version. I can't deep more, as it depends on that configurations that are very different per configuration, but you can check that with our Docker solution - https://github.com/Tecnativa/doodba - it's working, as fast option for contrasting the problem (this is not advertising, but a way to check that is working).

**Comment by cgarnier** [comment]
In fact i just added proxy_mode = True in /etc/odoo/odoo.conf and now it s working well.

**Comment by pedrobaeza** [comment]
Oh, I was assuming you already had that. Well, I noted for others with the same problem. Glad you found the deployment problem.

**Comment by cgarnier** [comment]
Maybe you could add a paragraph about it in this readme: https://hub.docker.com/_/odoo
I think most people use this docker behind a reverse proxy.
Thanks for your help.

**Comment by pedrobaeza** [comment]
Well, I'm only a contributor giving a hand managing Odoo issues, but not Odoo employee or Docker image maintainer, but I think it's your duty to check general documentation about that, where it's indicated: https://www.odoo.com/documentation/12.0/setup/deploy.html

**Comment by cgarnier** [comment]
Yes you right, but the point to use docker is to not have to read install documentation :D 
It should work out the box by linking services together and it should expose some usefull env var to setup this kind of options.

**Comment by pedrobaeza** [comment]
I don't agree on that part. Docker only provides a layer for not bothering with some install things. But this is configuration, not installation, and you can't assume that default configuration. For example, enabling that and using Docker for development in local machine with that option would make it to fail in other ways.

**Comment by cgarnier** [comment]
Yes ofcource but this kind of options should be settable via some env var to not have to edit any conf files.
`-e ODOO_PROXY_MODE=True`

**Comment by pedrobaeza** [comment]
Well, for that, you should:

* Check that there's no already an option for that.
* Check if there has been already requests about this and the answer.
* Put the issue for suggesting that or the PR adding the option in that project, not here.

**Comment by alexandregodard** [comment]
Hi,
In my config 
Proxy_mode=True, web.base.url = https://... and web.base.url.freeze =True weren't enough

Need to fixe my nginx proxy too with : 
        proxy_set_header X-Forwarded-Host $host;
        **_proxy_set_header X-Forwarded-Proto $scheme;_**
        proxy_set_header X-Real-IP $remote_addr;
