### ISSUE TITLE
Point of sale duplicating products

### ISSUE THREAD

**Issue by hydrosIII** [odoo/odoo#3568]
Steps to reproduce.

1.Go to Point of Sale, Order.
2.Create a new order.
3.Add a product, the go to the next line.

4.Quickly scan a product with a barcode scanner, press tab and enter quicky.
You can reproduce the bug by writing the product code, name or whatever reference you use to search the product then quickly pressing tab and enter.
The key to reproduce this bug is pressing tab--enter quicky.

5.The new product won't appear instead the point of sale will duplicate the previous product. 

This is grave, because sellers scan the products quickly, creating a lot of errors in the sale order.
Tested in the newest version of odoo 7.

**Comment by hydrosIII** [comment]
@JulioSerna, @ruiztulio, Can you provide the patch, please?

**Comment by Yenthe666** [comment]
Hi @hydrosIII,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Good to hear, thanks for verifying.
