### ISSUE TITLE
[master] demo file added in data category in manifest

### ISSUE THREAD

**Issue by aman-webkul** [odoo/odoo#35684]
Impacted versions: [master]

Steps to reproduce: Go to /master/addons/l10n_in_sale/__manifest__.py

Current behavior: file data/product_demo.py is in data category

Expected behavior: file data/product_demo.py should be in demo category

Video/Screenshot link (optional): https://github.com/odoo/odoo/blob/master/addons/l10n_in_sale/__manifest__.py

**Comment by sswapnesh** [comment]
This has been Fixed

**Comment by pedrobaeza** [comment]
Closing then, and it's an issue about master branch.

**Comment by Yenthe666** [comment]
Yep, at https://github.com/odoo/odoo/commit/1244dd0fb1113592e5f737cd1c5fc85358217376 to be specific. Thanks for the heads up @sswapnesh
