### ISSUE TITLE
Product Unit of sale does not respect the Unit of Sale coefficient when delivering goods

### ISSUE THREAD

**Issue by jon-willdooit** [odoo/odoo#3569]
Example (first enable multiple units of measure) and how to recreate:

1) set product unit of measure to "Each" (product information tab)
2) set product unit of sale to "3Pack" with a "Unit of Measure -> UOS Coeff"=3, and "Measure Type"="Fixed"
3) Sell one of the above products using the unit of sale, ie "3Pack"

Result:
1) A delivery order is created selling 1 item with a unit of "3Pack" - this is correct
2) HOWEVER, when the delivery order is confirmed only 1 product is moved - BUT 3 of the base products should have been moved - this is the bug.

Compare to purchases: If I had a supplier Unit of Measure of "3Pack" and purchased 1 from the supplier then 3 units would have been moved into stock. Sales should work the same way in my opinion.

**Comment by Yenthe666** [comment]
Hi @jon-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
