### ISSUE TITLE
[v8.0]Can't confirm MO

### ISSUE THREAD

**Issue by yy5512** [odoo/odoo#3571]
The login user(MFG001)  have only the standard right "Manufacturing/User".

After using the account MFG001 to create a MO,I can't confirm the MO.

Below is the error message.

AccessError

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Purchases/User
  - Purchases/Manager
  - Warehouse/User

(Document model: purchase.order)

**Comment by Yenthe666** [comment]
Hi @yy5512 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
