### ISSUE TITLE
invoice smart button -> draft and cancelled invoices are included in total

### ISSUE THREAD

**Issue by mylbco** [odoo/odoo#3574]
Scenario runbot : 26782-8-0-95e79c.runbot.odoo.com
1) goto Sales/Customers
2) select Agrolait
3) amount in the smart button 'invoiced' is 11010 Euro
4) dubbelclick on this button

--> also draft and canceled invoices are included in this amount !

**Comment by Yenthe666** [comment]
Hi @mylbco,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
This should have been fixed on Odoo 9 and up but if you can still reproduce it feel free to create a new bug report!
P.S: Thanks for the Linkedin invite 😉 

Regards,
Yenthe
