### ISSUE TITLE
[12] partner_autocomplete: Help on partner_id field should be specific to the module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#35779]
Impacted versions: 12.0

Steps to reproduce:  partner_autocomplete adds feature to search partner by  _You can find a contact by its Name, TIN, Email or Internal Reference._ on SO and Invoice.

https://github.com/odoo/odoo/blob/a6e1eb9f0ad285fac7d0ca0b9f89f046d78ec9c7/addons/sale/models/sale.py#L157

https://github.com/odoo/odoo/blob/a6e1eb9f0ad285fac7d0ca0b9f89f046d78ec9c7/addons/account/models/account_invoice.py#L282

Current behavior: This is misleading when partner_autocomplete is not installed and help on the fields is still there

Expected behavior: Help on the fields should be Module specific, Should be displayed only when module is installed.
 
Video/Screenshot link (optional):

(Ps: On the first look on thelp I thought it can be from custom name_search based on those fields)

**Comment by pedrobaeza** [comment]
Looking at this issue through codetriage.com, I'm seeing that the help is correct, as all that fields are used in the `name_search`, no matter if ` partner_autocomplete` is installed or not. That module what does is to fill the rest of the partner data when creating one, not when searching for it on the sales order.
