### ISSUE TITLE
Context badly extracted from odoo web client calls

### ISSUE THREAD

**Issue by jbaudoux** [odoo/odoo#35770]
Impacted versions: v10 most likely not only

Steps to reproduce: 
- Create a method with arguments with default value.
def demo(self, arg1=False, arg2=False)
- Make a button on a view calling that method.
- The context is not properly extracted and passed as first argument arg1.

The issue is in api.py split_context method:
`return kwargs.pop('context', None), args, kwargs`
The web client sends the context as non named argument: 
`call model(id,).demo({u'lang': u'fr_BE'})`
If context does not exist in kwargs, it should use the last argument of args

**Comment by pedrobaeza** [comment]
Why it should behave that way? Is there any problem with this in standard code? If not, I'm afraid you would need to adapt your code to this way of working, or propose a PR solving this for better acceptance.

**Comment by mart-e** [comment]
Hello,

Indeed, as said Pedro, if it is a problem only in your code, we will not change it in standard, especially in 10.0. Consider it as a limitation of the web framework.
If you want to provide a patch to improve it (but targeting master branch), we would gladly look at it.
