### ISSUE TITLE
m2m line add requires create right

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#35776]
**Impacted versions:** 12.0

This tiny add line action
![screenshot-odoo localhost-2019 08 16-14_55_20](https://user-images.githubusercontent.com/7548295/63194531-e63bf700-c035-11e9-997d-df7440979cf0.png)

requires `acl.perm_create = True ` on the target model,

although the view defines: `options="{'no_create': True}"`

**Request:** It should be possible to iron out this case with the most conservative ACL possible.

**Comment by blaggacao** [comment]
Note to myself: revert 192db1cf082dfd790cf787cf83215d8d5f83ba69 upon solution

**Comment by Yenthe666** [comment]
Ehhm, where exactly is this in Odoo itself? ;)

**Comment by blaggacao** [comment]
@Yenthe666 I din't find it myself neither, but I think it's somewhere in the web client which doesn't check for `options="{'no_create': True}"` when assessing the required access rights for this or that display option.

**Comment by sswapnesh** [comment]
> Ehhm, where exactly is this in Odoo itself? ;)

@Yenthe666  You can add m2m with any model where particular user has no rights to create records for that model.

---------------------------------
@blaggacao  I noticed this too during submitting https://github.com/odoo/odoo/pull/33156 as it checks at view level only. (Can't remember the exact point )

**Comment by blaggacao** [comment]
This should be probably addressed even in 11.0 as it encourages better security practice.

**Comment by sswapnesh** [comment]
> This should be probably addressed even in 11.0 as it encourages better security practice.

I don't think they will change this for v12 (or even 13) as its not blocking point. :expressionless:

**Comment by blaggacao** [comment]
@sswapnesh It's a question of honor and dev ethics to not to force people to loosen ACL because of such oversights...

**Comment by sswapnesh** [comment]
Isn't it already discussed in https://github.com/odoo/odoo/issues/50709

**Comment by Yenthe666** [comment]
Yeah indeed. Closing for the same reason as in the linked issue.
