### ISSUE TITLE
Allow folding the left menu for more space

### ISSUE THREAD

**Issue by vivekbics** [odoo/odoo#3577]
Hi, 

There was dock bar for menu section in 6.1. But it was removed from 7 onwards. 

It would be great if we have dock bar capability for the menu section in odoo 8.  

Thanks

**Comment by Yenthe666** [comment]
Hi @vivekbics,

Thanks again for this suggestion / idea.
I'm closing this bug report. It is labelled as wishlist so it will keep popping up and will be still looked at. We're closing all (very) old bug reports in an effort to clean up the tracker and improve the support.

Regards,
Yenthe
