### ISSUE TITLE
Unable to input characters after the converted character inside the search box.

### ISSUE THREAD

**Issue by nakometal** [odoo/odoo#35789]
### Impacted versions:

10.0 / 11.0 / 12.0

### Steps to reproduce:

* Login to Odoo by MacOS with any web browser (e.g Chrome / Safari).
* Open any menu that has a search box.
* Input Japanese characters including Kanji in the search box, and use the Enter key to convert.

### Current behavior:

* The searching tag is completed and unable to input characters after the converted character.
* This problem does not happen on Windows web browsers.

### Expected behavior:

* Input characters are converted and able to input characters after the converted character.

### Video/Screenshot link (optional):

![input](https://user-images.githubusercontent.com/45782518/63247376-da536d80-c29f-11e9-962e-3cd0a42d3902.gif)

**Comment by nakometal** [comment]
Similar Issue
https://github.com/odoo/odoo/issues/19592

**Comment by mart-e** [comment]
I believe fixed at #36284
