### ISSUE TITLE
[12.0] HR Leaves security issues

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#35799]
Impacted versions:
12 CE, 12 EE 

Steps to reproduce:
Create 3 employees and 2 managers to test leaves approvals as the following :
emp 1 --> manager1 
emp3-->emp2-->manager2
manager2 ---> sales department manager 
manager1 ---> Administration department manager 

Current behavior:
1- manager 1 and manager 2 can edit all employees data because they are  part of employee officer group by default when we assign leave officer group to them 
2- manager 1 and manager 2 can approve any leave requests not only their employees 
3- manager2 can change the leave type because we want him to approve the second approval 

Expected behavior:
1-manager 1 and manager 2 should not be able to approve all leave requests
2- manager 1 and manager 2 should not be able to edit employees data it is HR  job 
3-manager 1 and manager 2 should not be able to edit leave type it is HR  job

**Comment by usp-sa** [comment]
@Elbagoury We test it and we faced the same issues.

**Comment by pedrobaeza** [comment]
@RomainLibert maybe you can take a look to this
