### ISSUE TITLE
Share module bug list

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#3582]
Hi friends,
                  I found few bugs in share module let me list it down. 
1) I created share url without create permission because it is not available
2) While create new share url system creates new users.
3) Permission denied for ir.sequence and ir.action.actions
    Eg:-
           I generated share url and i accessed via liferay iframe. i was not able to access page
           https://cloud.githubusercontent.com/assets/7625330/5044891/efcb72e6-6c1b-11e4-8c5b-59d3ea71b232.png
           https://cloud.githubusercontent.com/assets/7625330/5045494/e30bbf54-6c23-11e4-948b-974fc852513d.png

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
