### ISSUE TITLE
Odoo 12 failed to decode fonts

### ISSUE THREAD

**Issue by hustlercoder** [odoo/odoo#35833]
Impacted versions: 12

Steps to reproduce: Try to create a new page with custom fonts

Current behavior: Failed to decode downloaded font

Expected behavior: 

Video/Screenshot link (optional):

Failed to decode downloaded font: <URL>
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/themify.woff?-fvbane
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/ElegantIcons.woff
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/fontawesome-webfont3e6e.woff2?v=4.7.0
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/ElegantIcons.ttf
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/themify.ttf?-fvbane
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/fontawesome-webfont3e6e.woff?v=4.7.0
:3000/#:1 Failed to decode downloaded font: http://ip:3000/web/content/426-47bd8db/1/s_assets/static/src/fonts/fontawesome-webfont3e6e.ttf?v=4.7.0

**Comment by pedrobaeza** [comment]
And how are that custom fonts added? The problem should be there.

**Comment by hustlercoder** [comment]
I add the font via <link rel="stylesheet" href="assets/css/themify-icons.css">...the classic way

**Comment by pedrobaeza** [comment]
Please put full detail.

**Comment by hustlercoder** [comment]
This is the standard way to include fonts in html...but also fontawesome..same error...and fontawesome is included in odoo

**Comment by pedrobaeza** [comment]
This is not simply HTML, so you must follow examples of how this is done in other places, and if you have doubts, make them on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing as this is not an Odoo issue itself.
