### ISSUE TITLE
[IMP]Warehouse:create and edit in Quants.

### ISSUE THREAD

**Issue by bpa-odoo** [odoo/odoo#3583]
In Warehouse -> Traceability -> Quants.

->Quants are automatic create, directlty can't create or edit quants.
Current Behavior:
-----------------
Display create and edit button in quants form view.

Expected Behavior:
-----------------
No need to display create and edit button in quants form view.

->see in video:http://youtu.be/QnhO1MOZjU8

**Comment by pna-odoo** [comment]
Fixed and merged in v8 and master. Thanks for reporting.
