### ISSUE TITLE
[IMP] use uom._compute_price() instead of hard coded factor conversion

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#35840]
https://github.com/odoo/odoo/blob/e1128c93872d060cc4557b7508d1e8da79599879/addons/purchase_stock/models/stock.py#L47

should we better use uom._compute_price() instead of hard coded factor conversion in the mentioned line ?

Regards

**Comment by pedrobaeza** [comment]
What is the advantage of using that method? Isn't the computation the same?

**Comment by mohamedhagag** [comment]
Yes it's the same, but from system design & OOP PoV we should use the helper functions.

For example if we need to modify the UoM computation method for any reason, current code will make it hard as we will need to override this function.

**Comment by pedrobaeza** [comment]
Yeah, but chances to get this changed on a stable version are less without any bug about it.

**Comment by Yenthe666** [comment]
To be honest there is no way it would even be accepted in a stable version. You could take a chance by making a PR against master though.

**Comment by mohamedhagag** [comment]
I know, and I made the PR against master.
although, I believe it should be accepted in all stable versions as it will have no effect.

**Comment by mohamedhagag** [comment]
I'm closing as the PR already exists.
