### ISSUE TITLE
multi company : duplicate product is not complete

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#3587]
Duplicate a product with many suppliers (attach to company) are not all duplicated

step to reproduce (runbot 7.0):

Configure demo user with the following access right:
- Warehouse Manager
- Multi Companies
- Connect with demo user (assert he is on Your Company) and configure many suppliers on a product with different company (OpenERP BE, OpenERP US).
- Change company (for OpenERP BE)
- Duplicate the product
- Change company (for Your Company)

-> Only Suppliers from OpenERP BE are copied, I think all supplier info should be copied.

**Comment by Yenthe666** [comment]
Hi @laetitia-gangloff,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 (& Odoo 8) is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
