### ISSUE TITLE
when installing odoo odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "stock_location_barcode_company_uniq"

### ISSUE THREAD

**Issue by luisvzqz** [odoo/odoo#35876]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This error indicates that you have some unique keys duplicated, but it's not a problem of Odoo itself. Self your DB and the installed modules.

**Comment by luisvzqz** [comment]
But it is a fresh installation ?
-LV

**Comment by pedrobaeza** [comment]
A fresh installation of what? A third-party module? You are not even indicating basic information like the followed steps, Odoo version, etc.
