### ISSUE TITLE
[12.0] Email Marketing: can not load theme_* assets templates because multiwebsite

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#35875]
Impacted versions:
12.0

Steps to reproduce:
- Create theme_A module with some scss styles or var colors
- Create a MyApp module that depends on theme_A in order to automatically install theme_A
- Set the theme_A as the theme of the default website
- Add some styles to home page template e.j. Header color : $ theme_a.var_color
- Create a mass mailing 

Current behavior:
While loading assets and compiling them fo html_frame widget field
This error occurred while compiling the bundle 'web.assets_frontend' containing:

![image](https://user-images.githubusercontent.com/10233975/63370543-15a97700-c348-11e9-802d-5bc88b63f718.png)

This happens because of the assets template on theme_A are set with a website_id
making theme only available for that website only while the original and the my_app website.assets_frontend does not have any website_id set
![image](https://user-images.githubusercontent.com/10233975/63370894-af712400-c348-11e9-8ff5-40b98edae6cf.png)

Expected behavior:
No set a website_id on assets_frontend inheritance templates
or fix it properly.

Video/Screenshot link (optional):

OPW  2057059

**Comment by rdeodoo** [comment]
> Create a MyApp module that depends on theme_A in order to automatically install theme_A

Installing a theme module does nothing to your website, it just create theme record that will be used later on when you install the theme on your website.
Installing a theme is not possible as it is not shown in the apps anymore but will only be installed once you select it to be loaded onto your website, throught the website configuration backend.

> Add some styles to home page template e.j. Header color : $ theme_a.var_color

That's expected, as the theme module is installed but not loaded onto your website.

Not directly related but to gather everything together: https://github.com/odoo/odoo/issues/28266#issuecomment-442509389 and https://github.com/odoo/odoo/issues/28695#issuecomment-441007826

**Comment by rdeodoo** [comment]
> So, when installing module my app, I mean that the theme_A will also be installed and set as the theme of the default website, I accomplish that with a short data in theme_A
> 
> ```
>     <record id="website.default_website" model="website">
>         <field name="theme_id" ref="base.module_theme_A"/>
>     </record>
> ```
> So After that there is not need to installe the theme manually.

As mentionned on https://github.com/odoo/odoo/issues/28266#issuecomment-442509389 it is not enough to set `theme_id`, it won't install the theme on the website. You need to call the appropriate method to do it, which is `_theme_load` according to the reply on the mentioned thread.

Please try with this method in module post install python code.

**Comment by rda-odoo** [comment]
@hugho-ad Hi I think you want to comment @rdeodoo 
Romain, please take note.
Thanks!

**Comment by jpp-odoo** [comment]
@hugho-ad 

Hello Hugo,

As said in the PR, if you want to use variables from the theme, you need to change the assets.xml of the application to inherit the assets of the theme. If you change this, you shouldn't have any more the Undefined Variable Error.

Best regards,

Jorge

**Comment by hugho-ad** [comment]
Hello @jpp-odoo ,

so, I should inherit each inheritance of website.assets tempalte? I mean to inherit all theme_x.assets, and all website_x_module.assets in a different tag template if I want use them just for a variable?

Regards!

**Comment by nhomar** [comment]
@jpp-odoo You have unanswered questions here....

**Comment by jpp-odoo** [comment]
Hello @hugho-ad ,

If you want to use or modify a variable/function/or other 'A' that came from an asset 'X', in a module 'Y'. In your new module 'W', you will need to create an asset 'Z' that inherits from asset 'X' to be able to see, use and modify the elements in the asset 'X' including the variable 'A'. Note that, as the asset 'X' inherits already from website.assets_frontend you will be had access to the elements of website.assets_frontend in the asset 'Z'. This behaviour is exactly the same as the one for the views.

Regards,

Jorge
