### ISSUE TITLE
Session expried warning

### ISSUE THREAD

**Issue by goyier** [odoo/odoo#35879]
Impacted versions:master

Steps to reproduce:when logout from odoo and open the login page

Current behavior:raise a session expried warning

Expected behavior:

Video/Screenshot link (optional):
![2019-08-21 08-05-15屏幕截图](https://user-images.githubusercontent.com/8132937/63393260-c6695200-c3ec-11e9-92cd-e0830c2106fb.png)

**Comment by goyier** [comment]
I debug the code last night,found the reason cause this issue.The method 'get_frontend_session_info' which is in the file 'web/models/ir_http.py',should be use the user info depends on current request.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html. Specifically, it might be `proxy_mode` not activated in Odoo conf.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
