### ISSUE TITLE
[master] account: unable to install chart of accounts

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35885]
Impacted versions: Master

Steps to reproduce:
1. Setup a new database on the latest master branch
2. Search for the app `l10n_be` or `l10n_nl` and install

Current behavior:
Traceback:
```
psycopg2.IntegrityError: insert or update on table "res_company" violates foreign key constraint "res_company_transfer_account_id_fkey"
DETAIL:  Key (transfer_account_id)=(340) is not present in table "account_account".
```

Expected behavior:
You're able to install a chart of account.

**Comment by Yenthe666** [comment]
@jco-odoo or @smetl probably for your interest.

**Comment by smetl** [comment]
@Yenthe666 In fact, everything is currently broken in master :)

**Comment by Yenthe666** [comment]
Aha, okay. If you keep this one open I'll check back in a few weeks to see how it is going :) Good luck!

**Comment by mart-e** [comment]
As I

**Comment by Yenthe666** [comment]
@mart-e you sneaky little guy. ;)

**Comment by mart-e** [comment]
@Yenthe666 as I told you, no need to report master issues, we know it is broken ;-)

**Comment by Yenthe666** [comment]
Yep, its noted!
