### ISSUE TITLE
[master] payment acquirers: something went wrong error when opening acquirer

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#35886]
Impacted versions: Master

Steps to reproduce: 
1. Login to the latest master build and go to `Website` > `eCommerce` > `Payment Acquirers`
2. Click on a payment provider such as PayPal

Current behavior:
A warning is raised, which seems related to IAP
![image](https://user-images.githubusercontent.com/6352350/63413010-2c5bd680-c3f9-11e9-8b87-6a9ed0085941.png)

Expected behavior:
Able to open the payment provider.

**Comment by Yenthe666** [comment]
It comes from the new enterprise module `payment_sepa_direct_debit` which adds the field `iap_sms_credits`:
https://github.com/odoo/enterprise/blob/242b6004b3fd8267753c6f5014a8909180a6d5f4/payment_sepa_direct_debit/models/payment.py#L68
Which does a compute:
https://github.com/odoo/enterprise/blob/242b6004b3fd8267753c6f5014a8909180a6d5f4/payment_sepa_direct_debit/models/payment.py#L81-L84

@dbo-odoo for your interest. This only works for `SEPA direct debit` but not for the others.

**Comment by dbo-odoo** [comment]
pbly linked to the ORM refactoring where compute methods need to write in all cases, even falsy ones

**Comment by Bonainifo** [comment]
New version cannot install sale app. The error message was base.payment_sepa_direct_debit id not found. Log have error KeyError: 'payment.acquirer'

**Comment by dbo-odoo** [comment]
original error is corrected
@Bonainifo i'm unable to reproduce your issue. Sales app install correctly (as is the case on our CI tool, otherwise we would have noticed quickly).
Please provide a way to reproduce if this still happens

**Comment by Yenthe666** [comment]
Indeed solved, thank you!
