### ISSUE TITLE
Not possible to create a pricelist which is visible just for "one contact" not any one alse!

### ISSUE THREAD

**Issue by Parsia** [odoo/odoo#35893]
**Impacted versions:** 12.0

**Current behavior:** I want to allocate a pricelist to a contact (suppose he/she is a wholesaler) but its impossible to create a pricelist that can be seen just by that contact. In fact when we create a pricelist we have 4 choices. before applying price computation, we should allocate the discount to all or some or one of the products! so all of the users can choose that discount in product's website view. 
I tested another way to allocate the discount to just one contact. I omitted the «selectable» option and its just shown by this contact but when he chooses another pricelist in website view, the pricelist disappears (this is a bug!)

**Expected behavior:** I want to allocate a pricelist to a contact and I dont want anyone alse (any other user) see it!

**Comment by pedrobaeza** [comment]
Sorry, but that's not possible with current code, so you should create a custom module for achieving that. And it has been made by purpose for avoiding some inconsistencies in business processes.

Closing as no issue at all, but different wanted behavior.

**Comment by Parsia** [comment]
Thank you. but I didn't become convinced! This behavior is used in most of the ecommerce websites. We expected odoo to use this practical behavior too...
