### ISSUE TITLE
[13] Automated Actions: On Update Journal entries

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#35924]
Impacted versions: 13

Steps to reproduce:

- Create an Automated Action
- Model: Journal Entries
- Trigger Condition: On Update
- Go to Invoices and try to create a new Invoice
- Try to set the Customer

Current behavior:

An error like the following will be displayed when Create an Invoice (but you will be able to enter to the draft invoice) and when you try to set the Customer:

![image](https://user-images.githubusercontent.com/5191766/63441809-0128b580-c400-11e9-926f-8d6144bdd201.png)

Video/Screenshot link (optional):
https://drive.google.com/file/d/1a9qmI_pWkAx4auDyOzEu3i10srraCcCC/view

**Comment by Yenthe666** [comment]
Hi,

This is work in progress, there is a lot of refactoring and changing going on for accounting but it should be fixed soon!

Regards,
Yenthe
