### ISSUE TITLE
[12.0] EE Mexican localization errors when mixing MXN & USD invoices with a payment in MXN

### ISSUE THREAD

**Issue by oldyguy** [odoo/odoo#35934]
Impacted versions:
12.0

Steps to reproduce:

1) create an invoice in MXN
2) create an invoice in USD
3) import bank statement or manually register a payment in MXN, with an exchange rate different than invoices one (usual buss case)
4) run conciliation
5) apply payment to those invoices
6) register the residual amount in the exchange gain or loss account
7) return to Customer - Payments
8) Look up for the payment
9) Generate the SAT's proof of payment 

###### Current behavior:
 - legend always says payment is greater than invoices total
###### Expected behavior:
 - regarding payment is really greater or lower than, legend should change accordingly
 
<br>
 
###### Current behavior:
 - instead using the exchange gain or loss account
 - create an advance payment invoice
 - it's XML includes exchange rate for all invoices, both MXN & USD ones
###### Expected behavior:
 - XML should use exchange rate only in USD invoices, not in MXN ones
 
<br>
 
###### Current behavior:
 - the XML total is calculated by adding all document totals, regarding its currency
###### Expected behavior:
 - the XML should add all amounts in MXN
 
<br>
 
###### Current behavior:
 - exchange rate is wrong
###### Expected behavior:
 - exchange rate should be prorated between the USD invoices only, discounting the MXN ones

Video/Screenshot link (optional):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pago10="http://www.sat.gob.mx/Pagos" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd" Version="3.3" Sello="***" SubTotal="0" Moneda="XXX" Total="0" TipoDeComprobante="P" Fecha="2019-08-19T14:10:07" Folio="21" Serie="19-08-" NoCertificado="00001000000414002619" Certificado="***" LugarExpedicion="06820">
  <cfdi:Emisor Rfc="***" Nombre="***" RegimenFiscal="601" />
  <cfdi:Receptor UsoCFDI="P01" Rfc="***" Nombre="***" />
  <cfdi:Conceptos>
    <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" />
  </cfdi:Conceptos>
  <cfdi:Complemento>
    <pago10:Pagos Version="1.0">
      <pago10:Pago FechaPago="2019-08-19T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="8700.00" NumOperacion="0027" NomBancoOrdExt="Banorte IXE" CtaOrdenante="***" CtaBeneficiario="***">
        <pago10:DoctoRelacionado IdDocumento="470D8894-5E27-4C10-92BC-3A9ABA5538B7" Serie="INV/2019/" Folio="30" MonedaDR="USD" TipoCambioDR="0.050000" MetodoDePagoDR="PPD" NumParcialidad="1" ImpSaldoAnt="145.00" ImpPagado="145.00" ImpSaldoInsoluto="0.00" />
        <pago10:DoctoRelacionado IdDocumento="4E751748-1A52-44BC-8239-00FFC1D0D6D9" Serie="INV/2019/" Folio="27" MonedaDR="USD" TipoCambioDR="0.050000" MetodoDePagoDR="PPD" NumParcialidad="1" ImpSaldoAnt="290.00" ImpPagado="290.00" ImpSaldoInsoluto="0.00" />
      </pago10:Pago>
    </pago10:Pagos>
  <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd" Version="1.1" UUID="***" FechaTimbrado="2019-08-19T14:08:05" RfcProvCertif="***" SelloCFD="***" NoCertificadoSAT="***" SelloSAT="***" /></cfdi:Complemento>
</cfdi:Comprobante>
```

**Comment by nhomar** [comment]
hello:

Can you share?

1. OPW ticket? uyour ticket in odoo.com/help
2. SHA or origin of your source code?

This problem is really old and was fixed few month ago (but we can verify if there is a regression after you share the information above).

**Comment by oldyguy** [comment]
David,

Por favor pásale a Nhomar los datos de acceso a una base de prueba para
mostrar los cuatro errores que están teniendo.

Nhomar,

Por favor no cierres mis tickets sin consultarme previamente.


Saludos,
César.
