### ISSUE TITLE
Onchange -> write for read-only

### ISSUE THREAD

**Issue by SimonasTr** [odoo/odoo#35967]
Impacted versions:
v11
Steps to reproduce:
2 fields. 
1st field 2nd field readonly
onchange function for 1st field to change value on the 2nd field.
Click save -> in write method it does not catch that 2nd field value has changed if 2nd field is readonly

**Comment by pedrobaeza** [comment]
If you have that field as readonly, you must put `force_save="1"` in your view.

Closing as no Odoo issue.
