### ISSUE TITLE
(master) CRM: Not Working 'Do not link to a customer' while create New Quotation from lead

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#35987]
Impacted versions: Master

Steps to reproduce:
1. Go to CRM > Pipeline - Create new lead
2. Not link any customer, Just provide contact name and company name
3. Now add New Quotation from lead with option - "Do not link to a customer". But system link customer on Quotation.

Current behavior:
Logically and practically wrong behave - System link customer on Quotation even select option "Do not link to a customer"

Expected behavior:
Remove this option from wizard - "Do not link to a customer"

Video/Screenshot link (optional):
https://drive.google.com/open?id=13Tvan8UlRzsfqqY2YYdmiNoCaYP7HyZY

**Comment by pedrobaeza** [comment]
Master branch is very unstable as it's a work in progress, so not sure this should be reported.

**Comment by sswapnesh** [comment]
Interesting 

This field  (`action`) has actually two options 
https://github.com/odoo/odoo/blob/4c9c249cc398d42e93939646e1237a1d0ff61166/addons/sale_crm/wizard/crm_opportunity_to_quotation.py#L27-L30

but as `crm.quotation.partner` is inherited from `crm.partner.binding`

https://github.com/odoo/odoo/blob/4c9c249cc398d42e93939646e1237a1d0ff61166/addons/sale_crm/wizard/crm_opportunity_to_quotation.py#L10-L12

so It should display only two Options

-------------------------------------
Currently is is showing all those original three Selection options
![screenshot-597871-master-dfc802 runbot27 odoo com-2019 08 22-21-35-37](https://user-images.githubusercontent.com/16624719/63531187-a0939880-c525-11e9-96fb-6e1711c3bb5b.jpg)


Maybe @mart-e has some Idea as he has worked on selection fields  (cc @dbeguin as you were the Author)

**Comment by mart-e** [comment]
Hi,

I know, I did it at 1d2bccd0dbd2770e0625a26b66a8b48c954b2c86 and it is planned to be changed (started a branch about it). Should be fixed in a few days.
@AmitBista as Pedro said, no need to report master bugs, it is an unstable branch. We will soon release the saas-12.5 which will be in stabilisation period to become the future 13.0. Until that, the latest "testing ready" branch is saas-12.4.

**Comment by dbeguin** [comment]
Well, I'm currently working on https://github.com/odoo/odoo/pull/35864 that removes the crm_partner_binding mixin that is not so useful after all.
cc @mart-e
