### ISSUE TITLE
[master] Payroll: Payslip batch generated even with no contract or running contract

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#35991]
Impacted versions: 13

Steps to reproduce:

- Create a new Batch
- Remove all the employees
- Add a new line and select one (or more) employee without a Contract or with a Contract in New state.
- Generate it

Current behavior:

The batch is generated and set as Verify, and let me continue as a normal process:
![image](https://user-images.githubusercontent.com/5191766/63540711-97d1a100-c4ea-11e9-9447-ffb1e6ca21a5.png)

Is this the expected behavior? Even when there is only one employee and this employee does not have a running contract? or Do you have plans to change this?

**Comment by pedrobaeza** [comment]
Master branch is evolving continuously, so don't expect coherence until freeze time, which will happen soon.

**Comment by goliveirab** [comment]
> Master branch is evolving continuously, so don't expect coherence until freeze time, which will happen soon.

Ok!   I'll be checking this out until then...

Thanks.

**Comment by Yenthe666** [comment]
Plus we kinda do not want to keep issues open that are for the master branch. They'll be fixed soon enough and Odoo doesn't officially support issues on the upcoming version.
