### ISSUE TITLE
[10.0] hr_timesheet_sheet don't change amout on analytic line during modification existing record

### ISSUE THREAD

**Issue by sluger25** [odoo/odoo#36030]
Impacted versions: 10.0

Steps to reproduce:
I use the following modules on odoo 10.0 community edition:
hr_timesheet_sheet
hr_timesheet_task
sale_timesheet

Current behavior:
I noticed a problem with the hr_timesheet_sheet module.
When you add a new record on the summary tab, the appropriate analytical entry with the correct value is created. But when you try to modify existing record on the Summary tab (attached screenshot: srceen1 ), only the unit_amount changes in the analytical account and the amount remains.
When you make modifications on the _Details_ tab, everything works fine and both unit_amout and amout change correctly.

Expected behavior:
When you modify an existing record on the _Summary_ tab, the variable _amount_ is calculated correctly.

Video/Screenshot link (optional):
![srceen1](https://user-images.githubusercontent.com/44207615/63598041-10099680-c5bf-11e9-82f6-bf1d2a8276b1.PNG)

**Comment by Yenthe666** [comment]
Dear @sluger25,

As Odoo 13 has been released today it means that our support for Odoo version 10 has been stopped.
If you can still reproduce this issue on a newer version (version 11, 12 or 13 at the point of writing) then please do respond back
or create a new issue.
Sorry that we didn't get around to resolving your issue.

Regards,
Yenthe
