### ISSUE TITLE
[12] Share Document should not be available for multiple records 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#36044]
Impacted versions: 12.0

Steps to reproduce: Select Multiple records from list --> Share
![screenshot-598052-12-0-7b9720 runbot19 odoo com-2019 08 24-22-39-03](https://user-images.githubusercontent.com/16624719/63640634-2fd4b380-c6c0-11e9-9311-07075c56d3a0.jpg)

Current behavior: It shares documents for one record only (First record)
![screenshot-598052-12-0-7b9720 runbot19 odoo com-2019 08 24-22-36-14](https://user-images.githubusercontent.com/16624719/63640609-bb017980-c6bf-11e9-90ef-ed22bea81e6f.jpg)

Expected behavior: Action should not be available or Enable Sharing for multiple records

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

I'm closing this one off as I've already reported this to Odoo a while ago under an OPW.
They said it is not a breaking or real issue for now but it is noted as a feedback task for one of the upcoming versions. They'll change this at some point.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
> They said it is not a breaking or real issue

I don't agree here as It creates Wrong assumption, End user don't know If all documents are shared or only one.
