### ISSUE TITLE
[12][stock] Drag and Drop should be blocked on Incoming Products 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#36043]
Impacted versions: 12.0

Steps to reproduce:
![screenshot-598052-12-0-7b9720 runbot19 odoo com-2019 08 24-22-28-41](https://user-images.githubusercontent.com/16624719/63640490-8f31c400-c6be-11e9-97f1-67f8893999f0.jpg)

Current behavior: Drag and Drop is Possible (Which create Inconsistency on the moves)

Expected behavior:  Drag and Drop should be blocked

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
and this should be also blocked
![screenshot-598052-12-0-7b9720 runbot19 odoo com-2019 08 24-22-31-48](https://user-images.githubusercontent.com/16624719/63640524-0c5d3900-c6bf-11e9-8738-2a40601b0066.jpg)

**Comment by pedrobaeza** [comment]
@sle-odoo maybe you can check this.
