### ISSUE TITLE
Recursion error when signaling workflow in server action. (SaleOrder)

### ISSUE THREAD

**Issue by adamwojt** [odoo/odoo#36083]
Impacted versions: 8.0

Steps to reproduce:
Send signal workflow in server action that runs on write or create.
Eg. `self.signal_workflow(cr, uid, ids, 'order_confirm')`.
Method that caused problem in my case was `action_button_confirm` on sale order. 

Current behavior:
Recursion error occurs as `signal_workflow` doesn't pass context `{action =True }` down the line.

Expected behavior:
Stop after one loop.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo 8 is no longer an officially supported version. Odoo only supports the last three versions (v10, v11 and v12 at this point). Closing the issue because of this.

Regards,
Yenthe
