### ISSUE TITLE
Odoo 11, 12 Not reserve qty on delivery order even stock available on-hand 

### ISSUE THREAD

**Issue by carlosecv** [odoo/odoo#36148]
Impacted versions: 11, 12
Modules: sales_management, stock, purchase
Steps to reproduce:
Create 2 Products
Create 4 suppliers

Product A 
Stockable, Procurement: Purchase, 
Add 2 Suppliers:
Supplier 1, Qty minimum: 1 Price: 20
Supplier 2, Qty minimum: 0 Price: 25

Product B
Stockable, Procurement: Purchase, 
Add 2 Suppliers:
Supplier 3, Qty minimum: 1 Price: 40
Supplier 4, Qty minimum: 0 Price: 45

Create sale Order SO
Detail:
Product A, Qty: 5
Product B, Qty: 1

Validate SO
Go to Purchase
We see 2 Purchase Orders Created by the SO One for Supplier 1 another for Supplier 3

Validate PO for Supplier 1 and receive products
Duplicate PO for Supplier 3 then change Supplier 3 for Supplier 4
Validate new PO receive products

Go to SO the go to Delivery try to reserve products then you see you have no products on hand to reserve

Current behavior:
Odoo links the created POs to Delivery, so if you want to create a Manual PO for another Supplier Odoo cannot reserve from Quantity on hand just if you use the created PO you will get reservations. 

Expected behavior:
If you have multiple Suppliers for products you not always will use the POs created by Odoo Procurement Purchase Method Odoo have to be able to check quantity on hand and allow user select the products on hand not linked to purchase order created automatically

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is the expected behavior, as there's no way to trace the source of the goods from other manually created POs. If you want to change the supplier, change it on the created PO, not on a new one.

Closing then as no issue, but expected behavior.
