### ISSUE TITLE
Getting VHD issue in Virtual machine

### ISSUE THREAD

**Issue by happycool007** [odoo/odoo#36154]
Impacted versions: 8.0

Steps to reproduce: Download and launch

Current behavior: Working

Expected behavior: Recovery

Video/Screenshot link (optional):
https://www.vdiskrecovery.com/blog/how-to-fix-vhd-vhdx-file-is-corrupted-and-unreadable-issue/

**Comment by pedrobaeza** [comment]
Closing as off-topic
