### ISSUE TITLE
[13.0] web_map: does not set pointers if added on custom model & takes no many2one

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#36168]
Impacted versions: Master

Steps to reproduce:
1. Create a new module in V13 and add an address field on the model. In this example for `sale.order`:
```
# -*- coding: utf-8 -*-

from odoo import models, fields, api


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    contact_address_complete = fields.Char(string='Address')

    @api.onchange('partner_id')
    def set_contact_address(self):
        if self.partner_id:
            self.contact_address_complete = self.partner_id.contact_address_complete
```

2. Now create a `Map` view with this `contact_address_complete` field and an action to trigger the map view:
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="sale_order_map_view" model="ir.ui.view">
       <field name="name">sale.order.map.view</field>
       <field name="priority">999</field>
       <field name="model">sale.order</field>
       <field name="arch" type="xml">
           <map>
               <marker-popup>
                   <field name="name" string="Name "/>
                   <field name="contact_address_complete" string="Address "/>
               </marker-popup>
           </map>
       </field>
   </record>

    <record id="action_sale_order_map_view" model="ir.actions.act_window.view">
        <field name="sequence" eval="999"/>
        <field name="view_mode">map</field>
        <field name="view_id" ref="sale_order_map_view"/>
        <field name="act_window_id" ref="sale.action_quotations_with_onboarding"/>
    </record>
    <record id="tutorial_sale_order_form_view" model="ir.ui.view">
        <field name="inherit_id" ref="sale.view_order_form"/>
        <field name="model">sale.order</field>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='partner_id']" position="after">
                <field name="contact_address_complete"/>
            </xpath>
        </field>
    </record>
</odoo>
```

3. Install this module

Current behavior: The map view is added but there are no pointers shown on the map view, even though the sale orders have addresses:
![image](https://user-images.githubusercontent.com/6352350/63841223-b5878600-c982-11e9-85bb-06d8ef40096b.png)
![image](https://user-images.githubusercontent.com/6352350/63841235-be785780-c982-11e9-9560-2f4376ecca35.png)

Expected behavior:
- Pointers should show up
- You should be able to use `Many2one` fields in the field definition
- You should be able to use the priority to decide the position of the icon from the view switcher.

I think there are three issues:
1. The pointers do not seem to be shown on the map view.
2. There is no option to use fields from other models, such as the `Many2one` field that links to the address of the contact. To do something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="sale_order_map_view" model="ir.ui.view">
       <field name="name">sale.order.map.view</field>
        <field name="priority">999</field>
       <field name="model">sale.order</field>
       <field name="arch" type="xml">
           <map>
               <marker-popup>
                   <field name="name" string="Name "/>
                   <field name="partner_id.contact_address_complete" string="Address "/>
               </marker-popup>
           </map>
       </field>
   </record>
</odoo>
```

3. When setting a priority on the action that triggers the `Map` view it doesn't influence in which position the `Map` icon is shown at the top?

**Comment by Yenthe666** [comment]
Hi @vincentadriaensen I see that you and "Thomas Werland" created this module and a big thanks to you guys!
I've tested this module for custom implementations of the map views and found the above three things. Could you please check this and see what can be done? :D I'd love to add this.

**Comment by Yenthe666** [comment]
Ignore points one and two: I'm just an idiot.
This works:
```
<map res_partner="partner_id">
  <marker-popup>
    <field name="name" string="Name "/>
    <field name="contact_address_complete" string="Address "/>
  </marker-popup>
</map>
```

**Comment by Yenthe666** [comment]
I found one other annoying bug. This will work:
`<field name="currency_id" string="Currency"/>`
This won't work:
`<field name="currency_id"/>`
Can't we just allow setting a field without string and get the string from the field itself?

**Comment by vincentadriaensen** [comment]
Hi @Yenthe666 , You tagged the wrong person. I don't think i was involved in this module. :)

**Comment by Yenthe666** [comment]
Sorry, corrected, should've been @VincentSchippefilt

**Comment by VincentSchippefilt** [comment]
@Yenthe666 Hello, thank you for being patient with your questions. This feedback is appreciated, and now that the rush of OXP is passed I'll try to catch up.

The map view has been designed with a link to res_partner in mind, so we expect your model to have a relation to res_partner. That is this relation that you have to mention in the "res_partner" part of the xml. I would be a good improvement to generalize the behavior needed to use the map view, may be in a mixin, to be used in multiple models, but that's not in the plans AFAIK.

Sequence is just used to select which view will be displayed when multiple are created for the same model/action (not 100% sure about this)

Setting fields without strings is probably an oversight. No biggie, I created a task to allow that and default the name of the field from the model: Task Id 2082134

I think I replied to all your questions. If I forgot any, can you ask again pls and if you are satisfied, can I close this issue ?

**Comment by Yenthe666** [comment]
Hi @VincentSchippefilt,

Thanks a lot for the detailed response! 🎉  It leaves me with two questions:
1) Can we add an option so that we can map the address from a `Many2one` field?
Right now we should do this:
`<field name="contact_address_complete" string="Address "/>`
Which means we have to make a related field to the address from the contact in order to show it on the map. If we could do `<field name="partner_id.contact_address_complete" string="Address "/>` we wouldn't need an extra field on our model and it would be much cleaner

2) Love the fact that you're adding an option to make the field definitions work without strings, thats a nice plus. Is there any way to keep me up to date about this task or a way to follow it? I'd love to know when it has landed into Odoo.

You can close this issue after answering these two :)

Regards,
Yenthe

**Comment by VincentSchippefilt** [comment]
@Yenthe666 
1. not for now: it's not just the complete address we need, it's also latitude & longitude as well as the onchanges on the parts that compose the complete address. Because it's not trivial and we don't have use cases for it, I don't think we will do it. 

2. I added "Please notify @Yenthe666 on issue https://github.com/odoo/odoo/issues/36168 when the dev is merged and in which version" in the description of the task. Let's see if it works ;)

**Comment by Yenthe666** [comment]
Thanks a lot 🙏

**Comment by Yenthe666** [comment]
To give an update: using a `Many2one` ID seems to work just fine now! For example:
```
<record id="some_calculator_map_view" model="ir.ui.view">
       <field name="name">some.model.map.view</field>
       <field name="model">some.model</field>
       <field name="priority">999</field>
       <field name="arch" type="xml">
           <map res_partner="customer_id">
               <marker-popup>
                   <field name="customer_id" string="Customer"/>
               </marker-popup>
           </map>
       </field>
</record>
```

This makes map views less complex and easier to implement. Thanks guys.
