### ISSUE TITLE
Can't have dynamic domains values in attrs attribute of xml tags

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#3617]
[Related forum question.](https://www.odoo.com/forum/help-1/question/what-is-the-evaluation-context-of-attrs-and-domain-attributes-in-view-fields-177)

It's not possible to have "dynamic" domains in the attrs attribute of an xml tag.
By dynamic I mean domains that use the value of a field (or context, or something else) as **value** of the domain (i.e. the element of the tuple) instead of a static string, bool or integer.
#### Example of a use case:

I have two dates on a model, `date_expected` and `date_promised`, and I want to show a button only where `date_expected != date_promised`.
I would use `<button attrs="{'invisible': [('date_expected', '=', date_promised)]}">` but this gives `NameError` during initialization because the domain is evalued without any context so `date_promised` is not defined.
#### Workaround

At the moment the best workaround I could find, and it was also recommended by others, is to add a function that evaluates the domain condition and returns True/False, and then check for True/False in the attrs domain.
#### What I would like:
- This feature to be implemented or, if this is impossible/impractical/not recommended, a good technical explanation on why.
- A mention on this fact on the docs, I spent a discrete amount of time trying to find out if this was possible or not, and the linked forum questions is the best I've found anywhere.

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
