### ISSUE TITLE
TypeError: el is undefined in web/static/src/js/core/dom.js:527:24

### ISSUE THREAD

**Issue by HatsuMora** [odoo/odoo#36209]
Impacted versions:
12.0-20190828

Steps to reproduce:
Install Odoo from the debian repository following the guides.
Enable Activate the developer mode (with assets)

I have try solution in #29418 but it didn't worked. 
I have install pip3 packages.

Current behavior:
Loads the interface in developer mode with assets

Expected behavior:
UI is not displayed with css/js content

I'm new to Odoo, please let me know what other info is relevant for the issue. Or a guidance where to start.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5619209/63891176-e8fafc80-c9e4-11e9-81e4-12904ea0d203.png)

This is the error log:
TypeError: el is undefined

https://odoo.domain.com/web/static/src/js/core/dom.js:527
Traceback:
computeFloatOuterWidthWithMargins@https://odoo.domain.com/web/static/src/js/core/dom.js:527:24
_adapt@https://odoo.domain.com/web/static/src/js/core/dom.js:516:35
initAutoMoreMenu@https://odoo.domain.com/web/static/src/js/core/dom.js:450:9
start@https://odoo.domain.com/web/static/src/js/chrome/menu.js:73:13
OdooClass.extend/</prototype[name]</<@https://odoo.domain.com/web/static/src/js/core/class.js:90:38
_widgetRenderAndInsert/<@https://odoo.domain.com/web/static/src/js/core/widget.js:399:25
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3276:89
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
add@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3165:49
then/</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3275:77
each@https://odoo.domain.com/web/static/lib/jquery/jquery.js:383:58
then/<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3272:56
Deferred@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3332:30
then@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3271:55
_widgetRenderAndInsert@https://odoo.domain.com/web/static/src/js/core/widget.js:393:33
prependTo@https://odoo.domain.com/web/static/src/js/core/widget.js:234:21
instanciate_menu_widgets/<@https://odoo.domain.com/web/static/src/js/chrome/web_client.js:125:33
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3276:89
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3283:104
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3321:62
rpc/<@https://odoo.domain.com/web/static/src/js/services/ajax_service.js:16:29
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3276:89
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3321:62
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
Deferred/</deferred[tuple[0]]@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3321:62
genericJsonRpc/<@https://odoo.domain.com/web/static/src/js/core/ajax.js:65:18
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3276:89
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
then/</</<@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3283:104
fire@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3119:58
fireWith@https://odoo.domain.com/web/static/lib/jquery/jquery.js:3231:49
done@https://odoo.domain.com/web/static/lib/jquery/jquery.js:9275:42
callback@https://odoo.domain.com/web/static/lib/jquery/jquery.js:9685:57

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

Ask also on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups) for more help, but not here.

Closing this by the reason above.
