### ISSUE TITLE
[12.0] 'NoneType' object has no attribute 'id' on website.id

### ISSUE THREAD

**Issue by hustlercoder** [odoo/odoo#36201]
Impacted versions: 12

Steps to reproduce: I create a template with the basic structure from the odoo documentation.Try to reach the url created but it doesnt work

Current behavior: 'NoneType' object has no attribute 'id' in website.id
`<t` t-set="x_icon" t-value="'/web/image/website/%s/favicon/' % `website.id"/>`

Expected behavior: 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by hustlercoder** [comment]
@pedrobaeza this is not a question but an issue...the server goes on 500 http error for this so..its not a question...

**Comment by pedrobaeza** [comment]
It's a question as you don't know how to do that. A real issue for this tracker is if something in Odoo without "touching" is not working.

**Comment by hustlercoder** [comment]
@pedrobaeza but i don't do anything....i take the code from the odoo documentation without touching anything and try to implement this with multi website...but it goes on error

**Comment by pedrobaeza** [comment]
Multi-website is perfectly working of fresh databases in runbot: http://runbot.odoo.com/. Try there.

**Comment by hustlercoder** [comment]
@pedrobaeza thank you i will try :)
