### ISSUE TITLE
[8.0] refreshing data in google spreadsheet report

### ISSUE THREAD

**Issue by eLBati** [odoo/odoo#3622]
In odoo 8, I installed google_spreadsheet.
I created a spreadsheet with 'add to google spreadsheet' under the advanced search.
I am able to load data of my DB into the spreadsheet writing a formula like

```
=oe_browse("res.partner";"display_name phone email";"[['customer','=',1],['customer','=',1]]")
```

Although the tutorial says

> The following data is loaded from your database, it is updated everytime you open this document. 

when I open the spreadsheet I always see the same data, even if they are in changed in odoo.

Moreover, if I use the spreadsheet as a template and launch it from within the partner, in my formula field I see

```
At least one connection detail is not set. You can set them Odoo > Settings in the menu bar (line 294, file "Code")
```

So, I always need to authenticate again and write the formula again in order to see the updated data.

Thanks

**Comment by jjscarafia** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @eLBati ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
