### ISSUE TITLE
Big images in thread messages get stretched

### ISSUE THREAD

**Issue by gaikaz** [odoo/odoo#36227]
Impacted versions:
11, 12 and future 13

Steps to reproduce:
- In any way create a `mail.message` record that in body contains an image that is horizontally larger than the viewport of browser window.
- `img` tag should set `width` and `height` parameters inline (some email clients might do that when attaching images to letter body)

Current behavior:
Large images in message contents are not allowed to overflow the viewport horizontally, but allow height to still be set inline.
![image](https://user-images.githubusercontent.com/17097810/63938006-7fbecc00-ca6c-11e9-8824-59c0662fbee2.png)

Expected behavior:
Images should keep their original aspect ratio.
![image](https://user-images.githubusercontent.com/17097810/63938092-aaa92000-ca6c-11e9-85a4-3618441b02fb.png)

**Comment by pedrobaeza** [comment]
Yeah, I agree it's weird. @tde-banana-odoo who takes care of this?

**Comment by tde-banana-odoo** [comment]
@alexkuhn

**Comment by gaikaz** [comment]
Looked at this way deeper and I think I found a some valuable info. The way I thought it could be fixed is by simply adding `height: auto;` just after this line https://github.com/odoo/odoo/blob/12.0/addons/mail/static/src/scss/thread.scss#L173
Then I found that it was already fixed with this commit: https://github.com/odoo/odoo/commit/e7bc4e9703954fa952f24b4f96e75dc4299bbb28
But for some reason removed with this PR: https://github.com/odoo/odoo/pull/15542
Sorry I didn't find this before the issue. It's because of CSS postprocessor change from `less` to `scss`, which covered up the file history.

**Comment by pedrobaeza** [comment]
Thanks for extra info. Very valuable.
