### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by OmniaGit** [odoo/odoo#36235]
Impacted versions:
9,10,11
Steps to reproduce:
go to settings and click on Project under implementation dashboard. a new pop up windows will be opened with information regarding the capability of odoo.
if you look at the following str **Invoice your customers (every month)**, you will fine the following descriprion:
**Invoice your customers (every month)**
If you work on a Time & Material project, you'll probably want to extract a Timesheet of the tasks and issues to invoice directly to the customer. To do that:

Activate '**Allow invoicing based on timesheets**' from the Human Resources Settings.
This will add an Invoice Tasks menu in the Project module, that can be used to select the Timesheet to invoice
that is not true, becouse ther is no human resource module, and A**llow invoicing based on timesheets settings.**

Expected behavior:
remove wrong description ..

**Comment by pedrobaeza** [comment]
Indeed that description belongs to 8.0, but not sure if at this point this is going to be fixed.

@mart-e what do you think?
