### ISSUE TITLE
[12.0] Odoo server client error in Timesheets module

### ISSUE THREAD

**Issue by m0r7y** [odoo/odoo#36240]
Impacted versions: 12.0

Steps to reproduce: Go to the module Timesheets > To Validate > Then click the button "VALIDATE" a pop up shows up then click "CANCEL" button

Full log error [here](https://pastebin.com/T6P4DzCk)

Video/Screenshot link (optional):
![odoo_bug](https://user-images.githubusercontent.com/45004342/63947550-a548d700-ca66-11e9-80f3-636a82d84943.png)

**Comment by m0r7y** [comment]
TypeError: cannot use 'in' operator to search for 'context' in 'special'

http://localhost:8072/web_grid/static/src/js/grid_model.js:125
Retraçage :
reload@http://localhost:8072/web_grid/static/src/js/grid_model.js:125:13
update@http://localhost:8072/web/static/src/js/views/abstract_controller.js:240:45
reload@http://localhost:8072/web/static/src/js/views/abstract_controller.js:202:21
_executeActionInDialog/</<@http://localhost:8072/web/static/src/js/chrome/action_manager.js:421:32
trigger@http://localhost:8072/web/static/src/js/core/mixins.js:225:31
trigger@http://localhost:8072/web/static/src/js/core/mixins.js:329:42
destroy@http://localhost:8072/web/static/src/js/core/dialog.js:216:18
OdooClass.extend/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:90:38
_closeDialog@http://localhost:8072/web/static/src/js/chrome/action_manager.js:296:49
_executeCloseAction@http://localhost:8072/web/static/src/js/chrome/action_manager.js:516:14
_handleAction@http://localhost:8072/web/static/src/js/chrome/action_manager.js:687:29
_handleAction@http://localhost:8072/web/static/src/js/chrome/action_manager_report.js:163:28
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:123:38
_handleAction@http://localhost:8072/web/static/src/js/chrome/action_manager_act_window.js:476:28
OdooClass.extend/Class.include/</prototype[name]</<@http://localhost:8072/web/static/src/js/core/class.js:123:38
doAction/<@http://localhost:8072/web/static/src/js/chrome/action_manager.js:179:25
then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:89
fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:58
add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:58
then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:56
Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:30
then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:55
doAction@http://localhost:8072/web/static/src/js/chrome/action_manager.js:171:41
_onExecuteAction/<@http://localhost:8072/web/static/src/js/chrome/action_manager_act_window.js:802:25
then/</</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3276:89
fire@http://localhost:8072/web/static/lib/jquery/jquery.js:3119:58
add@http://localhost:8072/web/static/lib/jquery/jquery.js:3165:49
then/</<@http://localhost:8072/web/static/lib/jquery/jquery.js:3275:77
each@http://localhost:8072/web/static/lib/jquery/jquery.js:383:58
then/<@http://localhost:8072/web/static/lib/jquery/jquery.js:3272:56
Deferred@http://localhost:8072/web/static/lib/jquery/jquery.js:3332:30
then@http://localhost:8072/web/static/lib/jquery/jquery.js:3271:55
_onExecuteAction@http://localhost:8072/web/static/src/js/chrome/action_manager_act_window.js:760:26
proxy/<@http://localhost:8072/web/static/src/js/core/mixins.js:278:23
trigger@http://localhost:8072/web/static/src/js/core/mixins.js:225:31
_trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:340:34
_trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:342:20
trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:335:14
_callButtonAction@http://localhost:8072/web/static/src/js/views/basic/basic_controller.js:268:14
_onButtonClicked@http://localhost:8072/web/static/src/js/views/form/form_controller.js:491:24
proxy/<@http://localhost:8072/web/static/src/js/core/mixins.js:278:23
trigger@http://localhost:8072/web/static/src/js/core/mixins.js:225:31
_trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:340:34
_trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:342:20
trigger_up@http://localhost:8072/web/static/src/js/core/mixins.js:335:14
_addOnClickAction/<@http://localhost:8072/web/static/src/js/views/form/form_renderer.js:310:18
dispatch@http://localhost:8072/web/static/lib/jquery/jquery.js:4641:58
add/elemData.handle@http://localhost:8072/web/static/lib/jquery/jquery.js:4309:63

**Comment by pedrobaeza** [comment]
As this is an enterprise only problem, please put the problem as an OPW ticket through odoo.com/help.
