### ISSUE TITLE
The location barcode field is not searchable and it should be

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#3624]
First I add a location barcode to an existing location.
![01 add location barcode to a exist location](https://cloud.githubusercontent.com/assets/7593953/5036280/b328627a-6b50-11e4-92d1-6f8334989e09.png)

Then I go tho the stock.location tree view and search the location using the location barcode in the search field. Do not return the location record I am searching for. 
![03 search by location barcode](https://cloud.githubusercontent.com/assets/7593953/5036291/c3616984-6b50-11e4-915a-949ae1733285.png)

After I create a new location and try to add the location with barcode as its Parent Location. I enter the location barcode into the Parent Location field but it not find the location that I am looking for.
![04 find a location via m2o field using the location barcode](https://cloud.githubusercontent.com/assets/7593953/5036301/d401fad8-6b50-11e4-872f-8b7b23127a7f.png)

Test Enviroment:
This test was run in http://27282-8-0-e826e8.runbot.odoo.com/web

What I get:
The search for the location do not return results.

What I expect:
The search should return the location with the given location barcode.

**Comment by moylop260** [comment]
What about this issue?

**Comment by moylop260** [comment]
FYI I have create the following https://github.com/odoo/odoo/pull/12043

**Comment by HairBear22** [comment]
So what's the status of this? Did it ever get implemented? I'm looking for the same functionality.

**Comment by mart-e** [comment]
Hello,

Implemented that at 4a3699bea98
Thanks
