### ISSUE TITLE
[account] wrong amount due after reconcile refund and invoice with different currency

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#36252]
Impacted versions:
* 11.0

Steps to reproduce:
* Create invoice with currency same of the company USD and validate
* Create refund invoice with currency different from company EUR and validate
* Reconcile from refund invoice with invoice

Current behavior:
The amount due of the invoice is calculated on currency of the refund invoice
The journal item of the invoice is set with currency of the refund invoice

Expected behavior:
The amount due should not be compute in currency of the refund invoice
The journal item should not be set with the currency of the refund invoice

Video/Screenshot link (optional):
https://youtu.be/IXAcwGdWpEo

**Comment by nhomar** [comment]
@JulioSerna can you share an opw-ticket please?

**Comment by JulioSerna** [comment]
@nhomar 
[2062103](https://www.odoo.com/my/task/2062103)
