### ISSUE TITLE
Export yielding incorrect data

### ISSUE THREAD

**Issue by intermodaltelematics** [odoo/odoo#36251]
Impacted versions:  11.0

Steps to reproduce:
1. Go to a module. 
2.Select records. 
3. Action >Export (csv or xls)

Current behavior:
Inconsistent and varied data is returned. Completely different records and information.
Sometimes blank rows are added or a row with 1 column of data from the previous row, sometimes in blocks of 3.

Expected behavior:
Consistently correct data export

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but what you think is inconsistent have a logic over, so unless you expose a real problem with that data, specifying specific issues and steps to reproduce, this doesn't qualify for an issue.

Closing meanwhile then.
