### ISSUE TITLE
Unit Tests not running when test module depends on another module

### ISSUE THREAD

**Issue by oliver633** [odoo/odoo#36282]
Impacted versions: 12

Steps to reproduce: 

- Create Module with following file:

**person.py**

```
from odoo import models, fields


class CdcModulePerson(models.Model):
    _name = 'some_module.person'
    name = fields.Char('Name', required=True)

```

- Create test module with following files:

**test_test.py**
```
from odoo.tests.common import TransactionCase


class TestTest(TransactionCase):

    def test_test(self):
        self.env['some_module.person'].create(dict(name='Johnny'))
        self.assertEquals(1, 2, "1 != 2")

    def setUp(self):
        super(TestTest, self).setUp()
```

**__manifest__.py**

```
{
    'name': 'Test Test',
    'version': '1',
    'depends': ['some_module'],
    'data': [
    ],
    'auto_install': False,
    'installable': True,
}
```

- Run tests

`odoo-bin -c your_config -d your_db -i test_module --test-enable  --stop-after-init`

Current behavior:

No tests running. missing lines:

```
2019-08-30 12:48:39,886 6751 INFO odoo12 odoo.modules.loading: Module test_module: loading demo 
2019-08-30 12:48:39,900 6751 INFO odoo12 odoo.modules.module: odoo.addons.test_module.tests.test_test running tests.
```

 When the dependency is removed, test run and fail, since 1 != 2

Expected behavior:

Guess what

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is working in my side, so this only means that you are not doing something properly (maybe your logging level), but I can't say without more information (and I shouldn't say, as this issue tracker is for issues with Odoo code, not specific deployment questions). Go to forums for more assistance.

Closing meanwhile you don't add information that proves that this is a real Odoo problem.

**Comment by oliver633** [comment]
Yes, if I run the tests in a blank database with -d db_new, it is working as expected. So it must have something to do with my database, but what??

**Comment by pedrobaeza** [comment]
I'm afraid you have to dug by yourself or ask for help on forums.

**Comment by oliver633** [comment]
Yeah, sure, thanks much!
