### ISSUE TITLE
[11.0] xmlrpc.client.Fault: <Fault 4: "('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\\n\\n(Document type: stock.picking.type, Operation: read)', None)"

### ISSUE THREAD

**Issue by mhdsyarif** [odoo/odoo#36295]
Impacted versions: 11.0

Steps to reproduce:
We had created multi company.
stand-alone company no subsidiary

Current behavior:
Validation picking using a user other than administrator using xmlrpc
```
def ValidatePicking():
    # Search 
    pick_id = models.execute_kw(db, uid, password,
    'stock.picking', 'search',
    [[['name', '=', 'Warun/OUT/00007'],['company_id','=',8]]])
    # Execute method
    models.execute_kw(
        db, uid, password, 'stock.picking', 'button_validate',pick_id)
```
Expected behavior:
By using the xmlrpc admin account it can be run, other accounts should also be able to run

access error:
```
File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 4: "('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\\n\\n(Document type: stock.picking.type, Operation: read)', None)">
```

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5978109/64037949-15e41680-cb81-11e9-897f-4721675dc5fb.png)

**Comment by pedrobaeza** [comment]
The problem is that the XML-RPC user doesn't have enough permissions. Grant them the needed permission.

Closing as no Odoo issue.
