### ISSUE TITLE
[11.0 e] crm: Partner is not assigned to meetings

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#36296]
**Impacted versions:** 11.0 e

**Steps to reproduce:**

1. Select a partner and press the schedule activity button
2. Select activity type meeting
3. Select date to schedule the meeting

or

1. Select an opportunity related to the partner and press the schedule activity button
2. Select activity type meeting
3. Select date to schedule the meeting

**Current behavior:**

The partner is not assigned to meetings configured from the client profile or from an opportunity but the partner is assigned from a direct meeting, this it is a disadvantage

**Expected behavior:**

The partner can be assigned from his profile and from an opportunity to a meeting

**Video/Screenshot link (optional):**

https://youtu.be/PtF2HcjBXWM

**OPW**
#2062786

**Comment by pedrobaeza** [comment]
@deivislaya did you get any answer from enterprise service?

**Comment by deivislaya** [comment]
@pedrobaeza  Yes, the enterprise service answered the following:

> Hello,
> 
> Thank you for contacting Odoo support and for your patience regarding this ticket.
> 
> The behavior you are reporting is the intended behavior of Odoo. Indeed, as a next activity is something that you plan for yourself, the meeting will only be assigned to you.
> 
> The only way to create a meeting and invite your partner is as shown in your video, by using the stat button "Meeting". Clicking on it will lead you to a calendar view and creating a meeting from this screen will add you + your partner to the attendees. 
> 
> Don't hesitate to come back to me if something is unclear.

I understand what the expected behavior is, depending on where the meeting is requested

**Comment by pedrobaeza** [comment]
Great, thanks for the followup.

Then let's close it as answered as expected behavior.
