### ISSUE TITLE
Project task selection widget bug in form view.

### ISSUE THREAD

**Issue by mvidhin** [odoo/odoo#3629]
Bug Video : https://drive.google.com/file/d/0By4GWTWr6HDNMzN4TGR1WXFkY2c/view?pli=1
Version : V8 and Master
Solution : instance.web.form.KanbanSelection widget -> method "set_kanban_selection" ->
             In that write rpc call replace  [self.record_id] with [self.view.datarecord.id].

**Comment by Yenthe666** [comment]
Hi @mvidhin,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
