### ISSUE TITLE
[Master] Traceback when printing Original Vendor Bill from Customer Invoice.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#36300]
Impacted versions: [Master C]

Steps to reproduce:

- Select multiple customer invoices.
- Click on Print > Original Vendor Bill.

Current behavior:
- It is throwing traceback.

Expected behavior:
- It should print report I believe.

Video/Screenshot link (optional):

[http://tinyurl.com/y3s6qtbu](url)

**Comment by Yenthe666** [comment]
@dipsshah42 please don't create issues for the upcoming master version. Odoo does not support bug reports for the upcoming version and they won't be handled.
I'm closing this issue for that reason.
CC @mart-e
