### ISSUE TITLE
[Master C] Traceback when printing original vendor bills.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#36303]
Impacted versions: [Master C]

Steps to reproduce:
- Select Invoices.
- Click on Print > Print Original vendor Bills.

Current behavior:
- It is throwing traceback.

Expected behavior:
- it should print a report or should not give a tracebacak

Video/Screenshot link (optional):

[https://youtu.be/Rh2bZgES5zc](url)

**Comment by pedrobaeza** [comment]
Please don't open issues on master branch, as it's a branch on continuous development, so errors are expected. You will be able to do it when the version is released.

Closing by the reason above.
