### ISSUE TITLE
Timesheet  grouping attendance records on incorrect day, with wrong total

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#3630]
Impacted versions:
* 7.0 and above

Steps to reproduce:
* Set user timezone to US/Mountain
* Create sign-in today at 16:30 hours
* Create sign-out today at 17:30 hours
* View the summary table (period_ids) on timesheet attendances tab

Current behavior:
*  Shows 30 minutes for today and 30 minutes for tomorrow

Expected behavior:
* Show 1 hour for today

View "hr_timesheet_sheet_sheet_day" is grouping some attendance records on the wrong day, and coming up with the wrong total attendance for the day.

![Uploading Screenshot from 2014-11-13 23:01:54.png . . .]()

**Comment by beledouxdenis** [comment]
Closed with cb17a78be8b04dc2735749e5a57a018eb7347de4.
