### ISSUE TITLE
[12.0, 13.0] Quotations template + Website body color > Unable to read

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#36308]
**Impacted versions:**
12.0

**Steps to reproduce:**
- Edit website theme (with Default theme)
- Change body color (to a dark one)
- Change layout to wide or boxed
- Go to a quotation template

**Current behavior:**
- Quotation page is affected by the body color

**Expected behavior:**
- The quotation background color should be editable

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/45974412/64099023-91ec8300-cd68-11e9-929e-581d9763aa68.png)

**Comment by JKE-be** [comment]
2 year later, it has been fixed in our last version...

You can add background on your block if you want
You can always apply your own css to change it if needed.

The final customer will see it with a blank background by default: 86e63450951353c160d51c2bf96249b22fdec479
