### ISSUE TITLE
[Master C] Traceback when Create invoices from Repair Orders

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#36305]
Impacted versions: [Master C]

Steps to reproduce:

- Select Repair Orders, 
- listview > Click on Action > Create invoices,
- Select > Group by partner invoice address, Click on Create Invoices button on the wizard.

Current behavior:
- It is Throwing Traceback.

Expected behavior:
- it should create an invoice.

Video/Screenshot link (optional):
[https://youtu.be/mn5tNxV-9Nw](url)

Thanks!

**Comment by pedrobaeza** [comment]
Please don't open issues on master branch, as it's a branch on continuous development, so errors are expected. You will be able to do it when the version is released.

Closing by the reason above.
