### ISSUE TITLE
[7.0][account] Bank statement wrong currency

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#3638]
Hi,

The bank statement currency is taking user company currency which is wrong. Ideally it should take currency from journal.

The following patch worked for me

``` python
=== modified file 'account/account_bank_statement.py'
--- account/account_bank_statement.py   2014-08-14 15:13:25 +0000
+++ account/account_bank_statement.py   2014-08-21 12:08:48 +0000
@@ -70,13 +70,13 @@
     def _currency(self, cursor, user, ids, name, args, context=None):
         res = {}
         res_currency_obj = self.pool.get('res.currency')
-        res_users_obj = self.pool.get('res.users')
-        default_currency = res_users_obj.browse(cursor, user,
-                user, context=context).company_id.currency_id
+        #res_users_obj = self.pool.get('res.users')
+        #default_currency = res_users_obj.browse(cursor, user,
+                #user, context=context).company_id.currency_id
         for statement in self.browse(cursor, user, ids, context=context):
-            currency = statement.journal_id.currency
-            if not currency:
-                currency = default_currency
+            currency = statement.journal_id.currency or statement.journal_id.company_id.currency_id
+            #if not currency:
+                #currency = default_currency
             res[statement.id] = currency.id
         currency_names = {}
         for currency_id, currency_name in res_currency_obj.name_get(cursor,
```

[Steps to reproduce Bug]
- Create or import bank statement with currency different than base currency. (Set currency on Journal)
- The currency symbol shows logged in user currency instead of journal currency. 

Let me know if more information is needed. 

Regards,
K

**Comment by Yenthe666** [comment]
Hi @kenvac ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
