### ISSUE TITLE
[12.0] WO open from MO don't go back to the MO at leave

### ISSUE THREAD

**Issue by Sirfanas** [odoo/odoo#36381]
### Steps to reproduce
Go in a MO, click on Work Order smart button, open one of the Work Order and click on "Process", then leave it with back arrow or by ending it)

### Current behavior:
Go back to the Production main action

### Expected behavior
Go back to the MO

### Comment
I think it would be better to go back in the MO used to open WO (or on the WO list)

**Comment by sle-odoo** [comment]
@svs-odoo we have a task ongoing for this, don't we?

**Comment by sle-odoo** [comment]
actually fixed in v13 at a6f647dcb6a2626b00f14144a69137b36e279070

**Comment by Sirfanas** [comment]
Is it possible to report the "fix" in 12.0 ?
