### ISSUE TITLE
[12.0 CE] [Inventory] Issue when changing the batch number and print of delivery slip, Confirmed in [ RUNBOT ]

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#36380]
Impacted versions:
12.0

**Steps to reproduce:**
Create new PO
Receive the products which should be trackable by LOT (batch)
Goto configuration of inventory and check the case track products by lot in delivery slip
Print delivery slip
Update the lot number of any of the products
Print again the delivery slip

**Current behavior:**
When changing the lot number, it is changed in the screen; but not changed in the delivery slip

**Expected behavior:**
Lot number changes as per the input on the screen, and do not keep the initial inputed value.

**Video/Screenshot link (optional):**
First line: lot 123
Send line: Lot 123 modified to 1234; but still print 123 as per initial value before update.
[Delivery Slip - Addison Olson - WH_IN_00107 (3).pdf](https://github.com/odoo/odoo/files/3569555/Delivery.Slip.-.Addison.Olson.-.WH_IN_00107.3.pdf)

**Comment by aitalinassim** [comment]
@sle-odoo

**Comment by sle-odoo** [comment]
Hi,
The delivery slip is meant to be used on deliveries, not on receipt.

Regards
