### ISSUE TITLE
[12.0][BUG] Product category complete.name field is not displayed in the language of the user

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#36402]
Impacted versions: 12.0

Steps to reproduce: Go on runbot, change language of current user to french be (for example). Take a product category with a translated name (For example "Note de frais"). You'll directly see a problem because you see the field "complete_name" in the field arian and it is stored and recomputed only when we change the name or parent so the value is in english for the complete_name but we see the name in french.
![image](https://user-images.githubusercontent.com/7678583/64235750-47e6d700-cef9-11e9-8a75-5aa0c6ca1963.png)

And this bug creates problem when we try to do a "group by product categories" on products for example:
![image](https://user-images.githubusercontent.com/7678583/64235833-795fa280-cef9-11e9-9e18-44b1e5898b8b.png)

Current behavior: complete_name of product category is computed and stored depending on the language of the last user that change the name or parent field

Expected behavior: We should see the complete name of the product category in the language we are connected

Video/Screenshot link (optional):

**Comment by kebeclibre** [comment]
Not a bug; a limitation, rather
The displayed field is a stored computed because we need to make the whole category hierarchy to be able to search in them
