### ISSUE TITLE
[12.0] web : date field impossible to set short date

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#36422]
**Impacted versions**: 12.0 (and maybe other)

**Steps to reproduce:**
Go to runbot
Go to Account/Create a new vendor Bill
Set a vendor.
Write the short date `0931` or `09312019` (for the 31 september 2019) in the `bill date` field , press Enter or Tab

**Current behavior:**
Field cleared

**Expected behavior:**
Field with `09/31/2019`

You need to write the full date `09/31/2019`.

Maybe linked to https://github.com/odoo/odoo/issues/36211 because a few days ago it works.
@hsi-odoo

**Comment by hsi-odoo** [comment]
thanks @fmdl i will short out issue as soon as possible

**Comment by sswapnesh** [comment]
Each time Something is broken with Patch of fixing trackback on Invalid date.
Hope for the Fix this time :+1: 


Ref https://github.com/odoo/odoo/issues/33408 and https://github.com/odoo/odoo/issues/29551#issuecomment-500984754

**Comment by hsi-odoo** [comment]
thanks @sswapnesh i will short out issue as soon as possible

**Comment by fmdl** [comment]
@hsi-odoo the solution it is on the way ?

**Comment by sswapnesh** [comment]
Should be fixed by https://github.com/odoo/odoo/pull/36821

**Comment by jpp-odoo** [comment]
Closed by https://github.com/odoo/odoo/commit/5481c429efb50be8d8617e4c17b04999c5a7fce8
