### ISSUE TITLE
Date type field is limited on year 1900 

### ISSUE THREAD

**Issue by tglukhov** [odoo/odoo#36438]
Impacted versions:
V11, V12, probably others versions too.

Steps to reproduce:
Choose date field and set year before year 1900 (01/01/1889 for example).

Current behavior:
Not possible to add a date before year 1900

Expected behavior:
Possibility of adding dates before 1900 

We'are entering old data in our base, for example, someone who born in the end of 19th century but Date fields  (type : date) can't afford it. 

Someone can help me with this issue?

**Comment by tglukhov** [comment]
@cvinh

**Comment by Yenthe666** [comment]
Hmm I believe it was once said that this was a known limitation of the current system and that there was no plan to change this.
@mart-e do you remember the related topic?

**Comment by pedrobaeza** [comment]
Yeah, this was a limitation at least on Python 2, and it has treated in other threads. This limitation may be now overpassed in Python 3 (although I remember also another problem), but if someone wants to work on this, a PR is welcome. Closing this for keeping this cleaned without duplicated topics.

**Comment by mart-e** [comment]
As explained here https://github.com/odoo/odoo/issues/41788#issuecomment-565437104 it is a python limitation but in newer versions, it should be solved at #43055
