### ISSUE TITLE
A partially reconciled credit note incorrectly gets paid in full on customer payment.

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3648]
I've tested this on `tags/8.0.0` and latest in `dev`. Steps to reproduce:
1. Create a refund invoice for 100
2. Create an invoice for 10
3. Make a customer payment. Which puts the open balance to 90 on the credit note.
4. Make an invoice for 200
5. 100 gets allocated towards the new invoice instead of 90

What should happen:

90 should get allocated towards the new invoice.

Screenshots:

![screenshot 2014-11-14 21 56 15](https://cloud.githubusercontent.com/assets/48965/5046876/63cd7af8-6c4a-11e4-8853-f817ec05f93b.png)
![screenshot 2014-11-14 21 57 16](https://cloud.githubusercontent.com/assets/48965/5046877/656f1c0e-6c4a-11e4-9a99-037d16cf6a16.png)

This is obviously quite bad as we would be loosing money every time a credit note has only partially reconciled.

**Comment by Yenthe666** [comment]
Hi @kitsunde,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
