### ISSUE TITLE
Pos iot box prinitng error

### ISSUE THREAD

**Issue by ali-darakjian** [odoo/odoo#36490]
Impacted versions:
Odoo Version 12.0
Iotbox 19_07
Downloaded from the link below

https://nightly.odoo.com/master/iotbox/

Steps to reproduce:
New Session >> Place New Order >> Validate

Current behavior:
Sometimes gets me an error while printing the receipt and sometimes not
and the printer prints the following error on the receipt .

not well formed (Invalid Token) : Line 76 column 58
Traceback (most recent call last):
file "/home/pi/odoo/addons/hw_escops/escops.py" line 701, in receipt
root = ET.formatstring(xml.encode('utf-8'))
file "usr/lib/python3.5/xml/etree/ElementTree.py" line 1344, in XMLparser.feed(text)
File "<string>", line None
xml.etree.ElementTree.ParserError not well formed (Invalid Token) : Line 76 column 58
Expected behavior:

Video/Screenshot link (optional):
![IMG_5197](https://user-images.githubusercontent.com/47788806/64356320-a92da980-cfd0-11e9-94b3-cfe8d54b8859.jpg)

**Comment by Yenthe666** [comment]
@switch87 for your interest

**Comment by aprieels** [comment]
@ali-darakjian I couldn't reproduce your issue. Did you modify `addons/point_of_sale/static/src/xml/pos.xml` or installed any module that modifies the receipt from https://apps.odoo.com/apps?

**Comment by ali-darakjian** [comment]
Yes I have some modules modifiies the xml receipt , but sometimes after restaring the iotbox it works and after a while it stuck again with the same error.

Any sugestions ??

Thanks

**Comment by aprieels** [comment]
The fact that you're using an iPad shouldn't have any impact on the printed receipts. Are you able to reproduce this issue without this module installed?
