### ISSUE TITLE
[6.1, 7.0] Draft invoice to pro-forma without check tax

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#365]
In the workflow tax amount is check just for the invoice validation.

For example, on a draft invoice with lines, edit a line in changing quantity of product.
Save your invoice, amount is compute but tax is not compute and keep is old value. You can change from draft invoice to pro-forma and you send at your customer this document with wrong amount. You must be awake, check manually tax and compute it with compute button.

see https://bugs.launchpad.net/ocb-addons/+bug/941817 for discussion

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
