### ISSUE TITLE
> @davidgonzalezb: Hello, How you reselved the error?. We have the same problem. Thanks

### ISSUE THREAD

**Issue by davidgonzalezb** [odoo/odoo#36513]
> @davidgonzalezb: Hello, How you reselved the error?. We have the same problem. Thanks

Hi, everybody!  
Just to share the knowledge... I found out what the problem is.

Hopefully, it could be useful for someone else! 🙃

---

From Odoo 12 on, the basic structure of the `*.po` files has changed.

This problem occurs when you try to load a `*.po` file that was generated on a previous version of Odoo (e.g. Odoo 11).

---

To solve this problem, you have to export a new file `*.po` directly from the latest Odoo version.

That's it.

_Originally posted by @Byloth in https://github.com/odoo/odoo/issues/31583#issuecomment-528808567_

**Comment by davidgonzalezb** [comment]
Hello @Byloth 
Thanks for your information
What file * .po do you mean? Do you have any examples? the file path?
Thank you

**Comment by Yenthe666** [comment]
Hi,


Sorry but it has no useful purpose to copy an issue its response and create a new issue. There is no longer an active issue to solve and this is a known limitation of the system.
Im closing this topic for these reasons. 


Regards, 
Yenthe
