### ISSUE TITLE
[12.0] Failed to decode downloaded font: <URL> with every font....also the fontawesome included in odoo

### ISSUE THREAD

**Issue by hustlercoder** [odoo/odoo#36536]
Impacted versions: 12.0

Steps to reproduce: Try to create a basic theme with a custom font or font-awesome

Current behavior: Odoo cannot decode any fonts ... including its awesome default..font

Expected behavior:

Video/Screenshot link (optional):

![aaad](https://user-images.githubusercontent.com/33348950/64509582-57429780-d2e0-11e9-8ede-dba69a3b0916.PNG)

**Comment by pedrobaeza** [comment]
The problem should be on your deployment or your code, as this is working properly in Odoo themes in runbot (http://runbot.odoo.com/).

Closing meanwhile you don't provide more information to confirm it's a problem with Odoo.
