### ISSUE TITLE
[11.0][12.0] Costing issue when choice costing method is FIFO 

### ISSUE THREAD

**Issue by ata-sw** [odoo/odoo#36533]
Impacted versions: v11 and v12

Steps to reproduce:
1. Install sale_management, stock, account_accountant and purchase.
2. Enable "Lots & Serial Numbers" from Inventory/Configuration/Setting.
3. Create a product tracking with lot then change the 'Costing Method' field on the category to 'FIFO' and change the 'Inventory Valuation' filed on the category to 'Automated'.
4. Create a purchase order with the above product with unit price equal to 10 then receive the product with "lot-1" as lot name.
5. Duplicate the above purchase order, change the unit price to 3 then receive the product with "lot-2" as lot name.
6. Create a sale order with qty = 1 from for the above product and deliver from "lot-2".
7. Reviewing the stock valuation entry created from the delivery order above, the value of journal entry is 10.

Expected behavior:
Value of the stock valuation entry should be 3 as we have delivered from “lot-2”.

**Comment by hassans2020** [comment]
I checked it on v13 abd same issue, Serial number is deducted from serials/lots but inventory valuation and customer invoice cost select first purchase not the selected serial.

Thanks

**Comment by sle-odoo** [comment]
We implement the financial fifo cost method, what you're describing is the individual costing cost method.

Regards

**Comment by rto-odoo** [comment]
¨We implement the financial fifo cost method, what you're describing is the individual costing cost method.¨   This doesn't make sense, then what you are saying is that ¨financial fifo cost method¨ only works with products that are not tracked by serial or lot numbers, the FIFO cost should be the individual cost, there are not supposed to be different methods.

**Comment by agavariat** [comment]
> Impacted versions: v11 and v12
> 
> Steps to reproduce:
> 
>     1. Install sale_management, stock, account_accountant and purchase.
> 
>     2. Enable "Lots & Serial Numbers" from Inventory/Configuration/Setting.
> 
>     3. Create a product tracking with lot then change the 'Costing Method' field on the category to 'FIFO' and change the 'Inventory Valuation' filed on the category to 'Automated'.
> 
>     4. Create a purchase order with the above product with unit price equal to 10 then receive the product with "lot-1" as lot name.
> 
>     5. Duplicate the above purchase order, change the unit price to 3 then receive the product with "lot-2" as lot name.
> 
>     6. Create a sale order with qty = 1 from for the above product and deliver from "lot-2".
> 
>     7. Reviewing the stock valuation entry created from the delivery order above, the value of journal entry is 10.
> 
> 
> Expected behavior:
> Value of the stock valuation entry should be 3 as we have delivered from “lot-2”.

Did you solve this issue?. Regards!

**Comment by bunhin** [comment]
closed without solution, it seems from the statement above, FIFO  cost method has to enforce FIFO in physical of goods during delivery out as well
