### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isOpen' of undefined

### ISSUE THREAD

**Issue by ChandniGandhi** [odoo/odoo#36543]
Impacted versions:
ODOO 12 Community and Enterprise
Odoo 11 community

Steps to reproduce:
Go to Timesheet > My Timesheets menu > create/edit one time in List view, add project and description and go to tasks list, click on Search More, then click on group by any field, now click on any one to open that grouped by. Error.

Current behavior:
It is giving error and reproduced on Runbot odoo's latest release.

Expected behavior:
Should group by and work normally as it should in all tree views.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/32623588/64516881-e5764800-d2f7-11e9-860d-a532ef6bd39a.png)

**Comment by rdeodoo** [comment]
![Screenshot from 2019-10-28 18-13-21](https://user-images.githubusercontent.com/30048408/67700719-c36f7c80-f9ae-11e9-954a-cdc7607ae727.png)

**Comment by rdeodoo** [comment]
More seriously, thank you for your report.
I am sure someone will be checking this one ASAP but hiding the traceback might slow down the process.
Unless I am wrong, I don't think there should be anything private in the traceback? Displaying it might help understanding the issue right away without digging further and allow your issue to be picked up by someone faster.

**Comment by ChandniGandhi** [comment]
> More seriously, thank you for your report.
> I am sure someone will be checking this one ASAP but hiding the traceback might slow down the process.
> Unless I am wrong, I don't think there should be anything private in the traceback? Displaying it might help understanding the issue right away without digging further and allow your issue to be picked up by someone faster.

**Comment by ChandniGandhi** [comment]
@rdeodoo : PELASE CHECK NOW.

**Comment by pedrobaeza** [comment]
@ChandniGandhi This is free support, and as such, you can't demand anything. Having directly an Odoo core developer asking you for more details for trying to solve it is already something very good, so please try to make things easier.

If you are paying an enterprise contract, then you can demand an answer corresponding to the SLA in odoo.com/help, not here.

**Comment by rdeodoo** [comment]
> @rdeodoo
MUST TRY TO FOLLOW STEPS AND REPRODUCE IT BEFORE ASKING SUCH.

That's the whole point of my previous message. Sometimes, the traceback might be enough to identify and understand directly the issue without the need to investiguate. In such a case, the dev will more likely handle your issue right away.
I was trying to help your issue getting handled faster. Anyway in this case the traceback does not help much.

> @rdeodoo : PELASE CHECK NOW.

I AM NOT WORKING ON TIMESHEETS MODULE, but I will check if someone can give it a look.

**Comment by ChandniGandhi** [comment]
> > @rdeodoo
> > MUST TRY TO FOLLOW STEPS AND REPRODUCE IT BEFORE ASKING SUCH.
> 
> That's the whole point of my previous message. Sometimes, the traceback might be enough to identify and understand directly the issue without the need to investiguate. In such a case, the dev will more likely handle your issue right away.
> I was trying to help your issue getting handled faster. Anyway in this case the traceback does not help much.
> 
> > @rdeodoo : PELASE CHECK NOW.
> 
> I AM NOT WORKING ON TIMESHEETS MODULE, but I will check if someone can give it a look.

Good to know again that you are not working with Timesheet module but still you checked this issue however it is written in first steps of steps to reproduce. (TIMESHEET)  and yes I know sometimes traceback is enough, but here it was clear that I can able to easily follow steps in 2 minutes to reproduce it, even in runbot. so my point was not to hurt developers feeling, but just to look at it out as easy as possible without anything more. Thank you for your time. Hope this will resolve soon. :)

**Comment by ChandniGandhi** [comment]
> > @rdeodoo
> > MUST TRY TO FOLLOW STEPS AND REPRODUCE IT BEFORE ASKING SUCH.
> 
> That's the whole point of my previous message. Sometimes, the traceback might be enough to identify and understand directly the issue without the need to investiguate. In such a case, the dev will more likely handle your issue right away.
> I was trying to help your issue getting handled faster. Anyway in this case the traceback does not help much.
> 
> > @rdeodoo : PELASE CHECK NOW.
> 
> I AM NOT WORKING ON TIMESHEETS MODULE, but I will check if someone can give it a look.



> @ChandniGandhi This is free support, and as such, you can't demand anything. Having directly an Odoo core developer asking you for more details for trying to solve it is already something very good, so please try to make things easier.
> 
> If you are paying an enterprise contract, then you can demand an answer corresponding to the SLA in odoo.com/help, not here.



> @ChandniGandhi This is free support, and as such, you can't demand anything. Having directly an Odoo core developer asking you for more details for trying to solve it is already something very good, so please try to make things easier.
> 
> If you are paying an enterprise contract, then you can demand an answer corresponding to the SLA in odoo.com/help, not here.

Hi,

Thanks for collaborating here, I can report there also as I am using enterprise paid version but I have reported here cause it is also giving error in community version. I know it is free support but remember it is also open source to report and to ask for something. I am not demanding about it just about to make it as easy as possible as I have clearly given steps to reproduce the issue and that can be done in 2 minutes. and yes with only error developer can't solve the problem without having that bug in local. I may wrong about it but I am also developer and consultant so according to that point of view I raised questions and comments here.  thank you and sorry :)

**Comment by Yenthe666** [comment]
@ChandniGandhi feel free to create a support ticket through odoo.com and linking the ticket number here though! You'll get way faster response rates :)

**Comment by ChandniGandhi** [comment]
> @ChandniGandhi feel free to create a support ticket through odoo.com and linking the ticket number here though! You'll get way faster response rates :)

Thanks.

**Comment by antdesigner** [comment]
at list view,use editable='top' property in <tree.create a new line ,  open  many2one field  to choose  item.
grouping items ,and then expand the group.An error hanppend

Uncaught TypeError: Cannot set property 'isOpen' of undefined
http://127.0.0.1:8069/web/static/src/js/views/basic/basic_model.js:1299
追溯:
TypeError: Cannot set property 'isOpen' of undefined
    at Class.toggleGroup (http://127.0.0.1:8069/web/static/src/js/views/basic/basic_model.js:1299:26)
    at Class._onToggleGroup (http://127.0.0.1:8069/web/static/src/js/views/list/list_controller.js:582:14)
    at Class.<anonymous> (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:278:23)
    at Class.trigger (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:225:31)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:340:34)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:342:20)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:342:20)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:342:20)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:342:20)
    at Class._trigger_up (http://127.0.0.1:8069/web/static/src/js/core/mixins.js:342:20)

**Comment by rdeodoo** [comment]
@aab-odoo Looks like you are the best suited for this one :muscle:

**Comment by mart-e** [comment]
Was fixed at #42602
