### ISSUE TITLE
Can Nginx block wkhtmltopdf creating Qweb report?

### ISSUE THREAD

**Issue by ZOOUQinn** [odoo/odoo#36556]
I have successfully installed odoo (11.0 Community Edition) along with wkhtmltopdf on Ubuntu 18.04

The version of wkhtmltopdf is 0.12.5, I get deb package(wkhtmltox_0.12.5-1.bionic_amd64.deb) from download page(https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5).

The created PDF report is fine with Odoo serve web pages by itself.
[Order - SO007.pdf](https://github.com/odoo/odoo/files/3590316/Order.-.SO007.pdf)

However, the report lost its style when set a reverse proxy (Nginx) for this odoo.
[Order - SO007 (1).pdf](https://github.com/odoo/odoo/files/3590319/Order.-.SO007.1.pdf)

Are there anyone can give me advise for this issue?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: Check your report.url system parameter to point to `http://localhost:8069`.

**Comment by ZOOUQinn** [comment]
I figure it out. Thanks for your assist.
________________________________
发件人: Pedro M. Baeza <notifications@github.com>
发送时间: 2019年9月9日 12:00
收件人: odoo/odoo <odoo@noreply.github.com>
抄送: ZOOU Qinn <ofssetpr_github@outlook.com>; Author <author@noreply.github.com>
主题: Re: [odoo/odoo] Can Nginx block wkhtmltopdf creating Qweb report? (#36556)


Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: Check your report.url system parameter to point to http://localhost:8069.

―
