### ISSUE TITLE
Changing the Delivery quantity resets the unit price to the product price.

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3655]
1. Create a delivery product, set price to 0
2. Create a deliver method, set price to 15
3. Pick the delivery method, it gets added with quantity 1 and price 15
4. Change quantity to 2 and watch the price get set to 0

Expected behavior:

The price should either remain, or be set to 15.

It was very unexpected to see the delivery get added with the price set as `normal_price`, but then change when manipulating the quantity. I also don't quite understand why changing the quantity should also reset the price to begin with, but I'm assuming that is intentional.

**Comment by Yenthe666** [comment]
Hi @kitsunde,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. 

Regards,
Yenthe
