### ISSUE TITLE
[8.0] Text truncated after ENTER

### ISSUE THREAD

**Issue by dhongu** [odoo/odoo#3660]
Test Case
1. From the menu Sales->Product is filled field "Description for Quotations" with text on multiple lines.
2. Go to WebSite - Shop
3. The text for the field "Description for Quotations" is displayed correctly on multiple lines
4. If you click on the Edit line breaks are removed 
5.  If you enter text on multiple lines and click on Save, it will save only first line of text.

**Comment by Yenthe666** [comment]
Hi @dhongu,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
