### ISSUE TITLE
[8.0] Item labels report for incoming products not found

### ISSUE THREAD

**Issue by dsabrinarg** [odoo/odoo#3663]
Hello.

I am trying to print item labels report for incoming products but this is not in 8.0 Odoo version.

What I get:
![v8](https://cloud.githubusercontent.com/assets/7597456/5054875/f6258ee8-6c1f-11e4-8904-6d2f275601ea.png)

What I expect:
![v7](https://cloud.githubusercontent.com/assets/7597456/5054874/f0da681e-6c1f-11e4-8c9c-8591d51aef25.png)

**Comment by Yenthe666** [comment]
Hi @dsabrinarg,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
This is indeed not in Odoo V8 and neither in newer versions, it is not something that will be added anytime soon.

Regards,
Yenthe
