### ISSUE TITLE
How to view the data from .py to view without saving into table

### ISSUE THREAD

**Issue by mady143** [odoo/odoo#36664]
Hi Everyone,
                   I had created a custom model and create a one table called table 1
from that table 1 writing a sql query as my requirement and i want to show that data on the fly into the view without saving into another table i want view that data directly in the tree view in odoo 11 version 
could any one help me in  this issue i am facing since last 15 days i was unable to rectify it 

Thanks in advance,
Happy codding.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
