### ISSUE TITLE
Incorrect rounding for amount total in account invoice

### ISSUE THREAD

**Issue by marcelopereiraarxi** [odoo/odoo#36675]
Impacted versions: 12.0

Steps to reproduce: 
Create an invoice with 2 lines:
-Line 1: 55.55 Unit price and 23% tax
-Line 2: 11.11 Unit price and 23% tax

Current behavior:
Amount total for 23% tax = 15.34

Expected behavior:
Amount total for 23% tax = 15.33

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/42939603/64685203-7d9e3980-d47e-11e9-833e-0a6cb954b7aa.png)

**Comment by pedrobaeza** [comment]
This depends on your rounding configuration in settings. You can round by line or globally. Change it and test again.

Closing as no real issue.

**Comment by nunosilvaarxi** [comment]
Even with round globally, in certain cases (and with line discounts), the tax rounding is still off.

![image](https://user-images.githubusercontent.com/35144292/64687068-b68bdd80-d481-11e9-8685-c4c446d40e84.png)

![image](https://user-images.githubusercontent.com/35144292/64687036-a247e080-d481-11e9-9a50-2a34e8f0f55e.png)

**Comment by pedrobaeza** [comment]
Price after discount is rounded to the number of decimals of product price, so if you want "more accuracy", you need to increase that product price decimal precision.

**Comment by nunosilvaarxi** [comment]
That solves it, but it's a bit convoluted that, in order to get the correct tax amount rounding when using discounts, you need to increase the product price decimal precision.

**Comment by pedrobaeza** [comment]
Yeah, that's the rounding price
