### ISSUE TITLE
[8.0] Delivery Method specified on Sale Order does not transfer to Delivery Order

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#3667]
Issue: Delivery Method on sales order does not populate to created delivery order.

Steps to reproduce: Create a new sales order, invoice method on demand. Add an item and a delivery method. Confirm sale. Delivery order is created without Delivery Method.

For some, this would be pretty important. Using latest 8.0 code.

I reviewed the code that generates a stock.picking to see why this field is not populated. It appears that the picking is created from a procurement group/order. Technical workflow is Sale > Procurement > Delivery Order.

The method that creates the delivery order from my review is in stock/stock.py method: _picking_assign. If this is indeed the correct place, I was disappointed by this method. If a developer wanted to add any other field from a sale order, it would not be possible without overriding the entire method. Perhaps there is some other way to achieve this that I am not aware of.

IMO, the method _picking_assign should get its vals for stock.picking record from a helper method that returns a dict. This way a developer could call super on the prepare method to add fields with some customized business logic.

**Comment by Yenthe666** [comment]
Hi @aliomattux ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
