### ISSUE TITLE
[11.0] Js errors when workers>0

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#36684]
Impacted versions: 11.0 (clone 2 days ago)
Installed on an Ubuntu server with 8G RAM 2 CPUs.
Steps to reproduce:
Set the number of workers greater than 0 (5 in my case i.e 2*2+1)

Current behavior:
Got random weird JS errors when I acces my_ip_address:port/web

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/31063466/64688103-306c9880-d47b-11e9-8f5c-705b401dd35e.png)

![image](https://user-images.githubusercontent.com/31063466/64688279-86d9d700-d47b-11e9-89ba-b9fcc89ce8d2.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.
