### ISSUE TITLE
Remove default value 0 and add place holder text for integer and float fields

### ISSUE THREAD

**Issue by vivekbics** [odoo/odoo#3668]
Hi,

There are many situations in which an integer or float field that is made mandatory. Since the field has default value of 0, the validation is not done like other fields (char, date...). The integer and float values should be empty be default. You can use place holder text to differentiate the field type.

**Comment by phuctoantruong** [comment]
_default = {
        'your_field': lambda *a: -1,
    }

**Comment by phuctoantruong** [comment]
It's rule of Odoo. If type field is number is default = 0

**Comment by Yenthe666** [comment]
This is desired behaviour and not something that'll be changed.

Regards,
Yenthe

**Comment by deepakkumarserpentcs** [comment]
Yes we can.
<field name="residual" readonly="1" string="Amount Due" sum="Amount Due" 
attrs="{'invisible':[('residual','=',0.0)]}"/>

**Comment by tirtharahaman** [comment]
I understand this is the default behaviour in Odoo but this is useless. The user is always forced to remove the '0'/'0.00' before typing a numeric value they desire. If the goal is to tell the user that the field is int/float, the same can be achieved using a placeholder. That way the user does not need to first remove the 0s.

An expert user can circumvent these annoying 0s using a keyboard. Odoo's end users are not geeks though. Hope, someone will reopen this :+1:

**Comment by andrepurnomo** [comment]
Yes i hope so, our end users use small gadget to input some data. And zero default value make they to remove it before insert.

**Comment by Clark-G** [comment]
> This is desired behaviour and not something that'll be changed.
> 
> Regards,
> Yenthe

desired by who?

**Comment by pedrobaeza** [comment]
By Odoo designers. Handling with NaN (or equivalent meaning) values in numbers is a mess.

**Comment by quentinDupont** [comment]
Totally agree with what @tirtharahaman said.
Users have made the same remark to me, many times

**Comment by Aeriah** [comment]
It's also problematic when you need to add the "required" parameter..
