### ISSUE TITLE
Send email in Project Task in Odoo 12

### ISSUE THREAD

**Issue by FreeDoo2018** [odoo/odoo#36695]
Impacted versions: 12

Steps to reproduce:

1.- Create a project with email address
2.- Send an email to project address
3.- Odoo save the client address with this format in the email_from field : "Juan Ignacio Ubeda juani@freedoo.es"
4.- When you send an email with an action (manual or automated) Odoo send the email to juani@freedoo.es&gt

juani@freedoo.es&gt (juani@freedoo.es>)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please specify the extra information I requested in OCB issue tracker.

**Comment by Yenthe666** [comment]
Yeah this is too little info.

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe
