### ISSUE TITLE
Cannot set a default journal on expenses

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#3670]
I can repoduce easily this one on v7 and v8. (probably on 6 and 6.1 as well but I've not tried).
- connect as admin
- install the expense module
- switch to developer mode
- from the expense list, click on Create
- select a different journal on the Accounting Tab
- from the developer dropdown list, select Set Defaults
- Select the Journal field for the default value and save
- Try to create a new expense
  → The default value is not set

**Comment by pedrobaeza** [comment]
Well, I think the use case doesn't apply, because if search doesn't return nothing, it's because the journal you have as default is not an allowed one for that user, so it shouldn't be kept.

**Comment by ccomb** [comment]
No, this is just impossible to set a default journal, even if it's of correct type.   The inherited method is just wrong.

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by jalzaga** [comment]
I confirm the issue, you can see that the user default value is correctly set but when you go to create the expenses you can see the default journal you set up for less than a second and then it disappears. The journal is a valid one because you can select it manually.

**Comment by StefanRijnhart** [comment]
I think I see @pedrobaeza's point. If no journal is found, the original code returns False. But if no journal is found, then no journal is accessible for the given currency and user. The change also allows for an inconsistent combination of journal and currency, so it seems dubious.
What I can imagine is that the code should verify that the current journal has the chosen currency. But that is tough in the old API without a signature change.

**Comment by ccomb** [comment]
I think this point is a different one and should be treated separately. For now I've just fixed a basic python error that prevented to define a default journal in all cases, be it valid or not.

**Comment by StefanRijnhart** [comment]
OK, thanks for the response.

**Comment by jmazigo** [comment]
i edit View shr.expense.sheet.form on 

<group>
                            <field name="journal_id" domain="[('type', '=', 'purchase')]" groups="account.group_account_user" options="{'no_open': True, 'no_create': True}" attrs="{'invisible': [('payment_mode', '!=', 'own_account')]}"/>
                            <field name="journal_id" groups="account.group_account_user" options="{'no_open': True, 'no_create': False}" attrs="{'visible': [('payment_mode', '!=', 'company_account')]}" domain="[('type', 'in', ['cash', 'bank'])]"/>
                            <field name="accounting_date" groups="account.group_account_user" attrs="{'invisible': [('state', 'not in', ['approve', 'post', 'done'])]}"/>
                            <field name="account_move_id" invisible="1"/>
                        </group>

the default payment by company was bank now it goes to expanses

**Comment by Yenthe666** [comment]
Hi @ccomb ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
