### ISSUE TITLE
Cannot cancel a sale order whose delivery order has been returned

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#3674]
Following these steps:
1. Create a sale order with an stockable product.
2. Confirm the sale order.
3. Go to the delivery order and make the transfer.
4. Revert the transfer.
5. Try to cancel the sale order.

**Expected behaviour**: sale order can be cancel, or even better, it goes automatically to a special state like 'Shipping exception'.

**Obtained behaviour**: sale order cannot be canceled, and "Create invoice" button is still available on the sale order, provoking an inconsistent behaviour.

**Comment by kasa3000** [comment]
hello I have the same product, but i don't  understand why a procuremnte is generated and how can I cancelled this procurement.

**Comment by AntMoreno** [comment]
Same problem here. A frequent scenario could be that a customer orders some items. You prepare the delivery order and transfer the items. While the items are on their way the customer cancels you the order. Ok, you can do a "reverse transfer", you can even set the sales order or both delivery orders (outgoing and incoming) to "Not invoiceable" (depending on your invoicing method), but the sale order will remain forever in state "Done", and if you use the sale orders data for reporting, or just use the tree or graph views as reports for sales, you'll obtain unacurate information.
The proposed "Reverse tranfer and cancel order" button could be a good solution, provided the reverse transfer where for the total quantities and products of the original order.

**Comment by avanzella** [comment]
Is there any progress on this issue?
Being able to cancel a delivery order with its related sale order should be an easy task as it is regularly requested for various reasons.

**Comment by SuperBiiz** [comment]
Here is waiting for the feature of canceling a delivered order too!

**Comment by Joycean** [comment]
Waiting for this feature too

**Comment by gdgellatly** [comment]
You can do that already.  However sending a delivery then returning it then cancelling the sale is not,  which is correct IMO.

**Comment by Joycean** [comment]
Thank you, Graeme. So it is impossible to cancel a delivered order even the shipping is reversed. In this case the order will always be in "Sale Order" (not paid) or "Done" (paid) in the database while in fact they are invalid and should not be counted.

**Comment by avanzella** [comment]
I agree, one should be able to cancel a sale order when the shipment has been cancelled (returned) and the invoice has not yet been issued. I don't find a way to do it as for now.

**Comment by AntMoreno** [comment]
I found a workaround for this using the "Mass editing" addon, although I advise you it is not a solution but a "trick" just to get rid of all those sales order that have been returned and are kept in state "Done" or "Sale Order". After installing the Mass Editing addon, you can create a "Cancel Sale Order" mass editing button using the "Sale Order" object, and selecting the "Status" field. This will allow you to bypass the ORM and workflow and to be able to mark a Sale Order as cancelled (or draft or whatever) whenever you want via the "More" buttom. Of course you should also configure permissions only for the specific users you want to use the feature.

**Comment by ljrodriguez** [comment]
Gracias, antonio ... you save me

**Comment by Yenthe666** [comment]
Hi guys,

Thanks for the report and feedback. My apologies that there has been no response from Odoo itself.
I believe this has been answered & workarounds where found. Closing as Odoo 7 & Odoo 8 are no longer supported.

Regards,
Yenthe

**Comment by teppix** [comment]
@Yenthe666 
Not sure why the issue was closed, as the exact same problem still exists in Odoo 11. I believe this should be reopened.

**Comment by Yenthe666** [comment]
@teppix please do create a new bug report then. It would be nice to have a clean report for the newest version with all the steps explained.

**Comment by teppix** [comment]
@Yenthe666 
All steps are explained, and it's already pretty clean. The problem is very easy to recreate and it definitely still exists in v11. It's just as valid now as it was when the issue was created.

If you think anything is unclear, it's better if you just ask. I don't see how a duplicate of the issue will help.

**Comment by dansanti** [comment]
that is because state i s computed, and depends from move lines, so, if all move is cancelled, sale order will cancelled, is not a bug, they must add some another feature, to make it cancell.
