### ISSUE TITLE
[8.0] Operations oe_kanban_stock_picking_type min-height property

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#3675]
Version 8.0 latest code

Problem: If you add more than the built in selections to oe_kanban_stock_picking_type, it does not size the box dynamically to fit the options. The box is a fixed size of 245px. There is a css property that is set to override everything in class oe_kanban_stock_picking_type with the !important tag.

Additionally, if you add more entries, they are overlapped by the gauges because of the top margin 100px property. I am not sure of the best solution to this problem. I hope I have explained it clearly.

To solve my issue as a work around I put an inline style for the height property in class oe_kanban_stock_picking_type. Since the height is already static, I just increased the amount of px to what I needed it for.

**Comment by Yenthe666** [comment]
Hi @aliomattux ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
