### ISSUE TITLE
[6.1] ACCOUNT : can not duplicated tax

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#368]
If you try to duplicate an existing tax using the button 'duplicate' on the form view, OpenERP will raise an error.

The fix is simple and it's here : https://code.launchpad.net/~sebastien.beau/openobject-addons/openobject-addons-account-duplicate-tax

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
