### ISSUE TITLE
[8.0] resource get_working_hours only uses full hours and takes one working day too much

### ISSUE THREAD

**Issue by ehirt** [odoo/odoo#3681]
resource.py line 339/340 only transfers full hours to interval -> working hours are calculated wrong when from/to hour includes minutes

In our setup it calculates a working day extra. Found that in line 381 the end date is forced to last day+nextdata 00:00. Why?

**Comment by tobru** [comment]
We're facing the same issue and this patch fixes it for us. Any chance that this PR gets merged soon?

**Comment by ehirt** [comment]
Dear Tobias,

Thanks for your request.

Unfortunately, we are still on 6.1 and as such I have no
testinstallation on V8 to prepare the required tests.

If you might add them to my patch then it could get released.

If you decide to do the task then first ask me for an update as I have
corrected other pieces in 6.1 that could be transferred, too.

Best Regards

Etienne

**Comment by Yenthe666** [comment]
Hi @ehirt ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
