### ISSUE TITLE
UOM Rounding is not computed in Transfers

### ISSUE THREAD

**Issue by NathanQj** [odoo/odoo#36811]
https://github.com/odoo/odoo/blob/a3f2c82789520af5a58aa4193d462f4acf8ba529/addons/stock/models/stock_move.py#L235

Impacted versions: Odoo Enterprise 12

Steps to reproduce: 
- Configure a Unit of Measure with a rounding precision of 1.0
- Configure a Product with this UOM
- Create a Delivery Order
- Create a stock.move with said Product
- Set Product QTY to a decimal number
- Save the Delivery Order

Current behavior:
- The product_uom_qty will stay a decimal even though the rounding precision is defined for whole numbers.

Expected behavior:
- The product_uom_qty is rounded up according to the Product's UOM definition.
(The tooltip of Rounding Precision in UOM is: "The computed quantity will be a multiple of this value. Use 1.0 for a Unit of Measure that cannot be further split, such as a piece." and is not what happens.)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/9081438/64808986-54f16f00-d566-11e9-8068-8743c938462d.png)
![image](https://user-images.githubusercontent.com/9081438/64809157-aef23480-d566-11e9-9580-94cdf2aef8a0.png)

**Comment by pedrobaeza** [comment]
So, what is the problem, please summarize

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no extra information in quite a while I'm closing this issue.
Don't hesitate to respond back with detailed information and then we'll reopen this issue.

Regards,
Yenthe
