### ISSUE TITLE
Ecommerce orders remains in "quotation sent" state

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#3682]
An order placed via ecommerce (paid with wire transfer) remains in "quotation sent" state.
I think it should go in "order confirmed".
Therefore the client receives a email referring to a quotation rather  than an order despire the fact is has not been paid yet.
Is there a way to change the sales order status?

**Comment by Yenthe666** [comment]
Hi @avanzella,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
