### ISSUE TITLE
[6.1] E-mail sent have no date

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#369]
If you go to Settings / Configuration / Email / Messages, you'll see the e-mails you have sent (by the marketing campaign, for example). You can see using the state which e-mails have been sent, but you cannot see when they have been sent. The field date stay blank.

After searching in the code, it appears that the field date is used only for received e-mails. Why is the date not used for sent message, like in all mail clients?

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
