### ISSUE TITLE
Session expired (invalid CSRF token) -> only when proxyfied

### ISSUE THREAD

**Issue by open7c** [odoo/odoo#36956]
Impacted versions:

11.0-20190816 

Steps to reproduce:

We want to use Odoo through a (Apache) Reverse Proxy.

Most things are working, but on POSTs (ie at /web/dataset/call) after login we get:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Session expired (invalid CSRF token)</p>
```
The Settings of Reverse Proxy:

```
ProxyRequests Off
<Proxy *>
Order deny,allow
Allow from all
</Proxy>

SSLProxyCheckPeerName Off
SSLProxyEngine On
SSLProxyCheckPeerCN off
SSLProxyCheckPeerExpire off

ProxyPass / https://proxy.example.com/
ProxyPassReverse / https://proxy.example.com/
ProxyPassReverseCookieDomain .example.com test.odoo.example.com
```
`proxy.example.com` is a System that takes everything (Parameters, POST, GET, COOKIES...) and passes it through to odoo, and passes the Response 1:1 back to the Client.

What could be the Problem? Is the Proxy Host casing Problems?

**Request**: Browser -> test.odoo.example.com -> (Reverse proxy) -> Odoo 
**Response**: Odoo -> (Reverse proxy) -> test.odoo.example.com -> Browser

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: check if you have activated proxy_mode = True in your Odoo conf.

**Comment by rockcesar** [comment]
It's a recurrent problem. There should be a solution. Maybe a parameter in Apache or NGINX, conf. Proxy mode is activated, but I have the same problem for some client, but other clients can browse without problems.

@open7c Did you found the solution?.

**Comment by rockcesar** [comment]
I guess you need longpolling published, and set the workers > 0, in Odoo conf:

workers = 2

And in Apache set:

ProxyPass /longpolling/        http://127.0.0.1:8072/longpolling/ retry=0
ProxyPassReverse /longpolling/ http://127.0.0.1:8072/longpolling/ retry=0

ProxyPass / http://127.0.0.1:8069/ retry=0
ProxyPassReverse / http://127.0.0.1:8069/ retry=0
