### ISSUE TITLE
[12.0] - Technical settings (group_no_one) are not displayed 

### ISSUE THREAD

**Issue by elholly** [odoo/odoo#36950]
Impacted versions:
Odoo 12 Community Version

Steps to reproduce:
1. Clean install on Debian server.
2. Install Website module.
3. Activate debug mode
4. Go to Settings/Users/Form

Current behavior:
Several menu options, with group='base.group_no_one', are not displayed in debug mode.

Expected behavior:
All fields with the group 'base.group_no_one' should be displayed for users linked to that group. 

Video/Screenshot link (optional):
The ratio button to define the user type is not displayed, despite the fact, that the current user has the right linked with the group='base.group_no_one'.

<img width="309" alt="Bildschirmfoto 2019-09-16 um 14 39 28" src="https://user-images.githubusercontent.com/35347329/64958680-fc84df00-d88f-11e9-98bd-adb485ff083d.png">

no user type option is displayed.

<img width="269" alt="Bildschirmfoto 2019-09-16 um 14 40 09" src="https://user-images.githubusercontent.com/35347329/64958654-f0991d00-d88f-11e9-873c-6aae2c6a351e.png">

**Comment by pedrobaeza** [comment]
That radio button is only displayed on edit mode. Meanwhile, it stays as a normal dropdown, as you can see in your screenshot.

Closing as no valid issue.

**Comment by elholly** [comment]
I'm sorry, i mixed up the screenshots. Therefore i updated my issue and included the correct one.

**Comment by pedrobaeza** [comment]
But are you assigning manually that group? You shouldn't do that. Entering in debug mode, auto-assign such group. Any way. this is working in runbot. Try there.

**Comment by elholly** [comment]
The group was assigned during the user creation from the system.
I have tried it on my local machine as well, there it is working.
The problem is, that it is not working on our Debian server without displaying any indication why.
I have already tried a completely new installation with a new database. The problem sill exists.

**Comment by pedrobaeza** [comment]
Try doing the question on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
