### ISSUE TITLE
 [Trunk/6.1] External file storage not working

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#370]
In the document module the "external file storage" does not store documents at the right place.

Applicable to 6.1 and probably trunk, as the code did not change.

How to reproduce:

- install the document and project modules
- in Knowldege > Configuration, create a new Storage Media of type External File Storage named External File Storage
- in Knowldege > Configuration, remove all directories except the root (Document)
- change the storage of the Document Directory to External File Storage
- create a new Directory named Projects of type Folder per Resource and set Project as Resource
- create 2 projects named Project1 and Project2
- attach a pdf file to Project1
- attache the same pdf file with the same name to Project2
- browse over FTP: files are visible in folders Projects/Project1 and Projects/Project2 -> ok
- browse the file system: only one PDF can be found at the root of the file store -> strange
- in Project1, remove attachment
- in Project2, try to open the attachment -> system error

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
