### ISSUE TITLE
Expected singleton error in hr_holidays

### ISSUE THREAD

**Issue by MeeleCode** [odoo/odoo#37018]
Impacted versions:
master

Steps to reproduce:
- create more than one leave that has to be validated
- select more than one leave from the tree view that has to be validated
- go to Action > Manager Approval or HR Approval

Current behavior:
- you get an error "Expected singleton" because of self.employee_id.id (and self is a list of browse records) -> line 649 in write function when trying to execute _check_double_validation_rules

Expected behavior:
- should change the _check_double_validation_rules to support multi self or run the check for each browse record in self

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Will be great if you can go ahead with PR as you know the solution already
(and also this is referring to the master so there are fewer chances someone will look into it)

**Comment by fmdl** [comment]
What is the version of odoo ?

**Comment by MeeleCode** [comment]
Version master, as stated in the first post

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as Odoo only accepts issues that target a support version. The master version is not supported and Odoo doesn't allow bug reports for it.
Please do create that PR to fix it, as @sswapnesh suggested :)

Regards,
Yenthe
