### ISSUE TITLE
[6.1, 7.0] ressource interval_hours_get does only consider full day leaves

### ISSUE THREAD

**Issue by ehirt** [odoo/odoo#3702]
Backport odoo 8.0 version including corrections described in  #3681 to include any leaves.  

Where can I place my diff or prepare the patch?

**Comment by Yenthe666** [comment]
Hi @ehirt,

Thank you for your report / patch.
Since this is against V6.1 and this version is no longer supported I'm afraid it won't be accepted anymore. As this has been fixed in V8 there is nothing to do here anymore. 😉 

Regards,
Yenthe
