### ISSUE TITLE
confirm="message" not working for buttons in list view

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#37036]
Impacted versions: 11, 12? 

Steps to reproduce: Add a button to a list view with a `confirm="Really do?"` attribute. Load the view and press the button for a list item. Note whether the confirm dialog appears. 

Current behavior: No confirm dialog in list view, either editable or non-editable

Expected behavior: Button press should trigger confirm dialog. 

Note:  I looked for examples of this in Odoo code but I could not find any buttons in list views with `confirm=` attributes to test this on runbot. 

Video/Screenshot link (optional):

**Comment by elgow** [comment]
Also worth noting that `confirm=` is documented for buttons in the list section of developer docs and is allowed for buttons generally in the rng schema [here](https://github.com/odoo/odoo/blob/3c5338dce8db7606ac2ac0101473bcafe3bd4f76/odoo/addons/base/rng/common.rng#L335).

**Comment by pedrobaeza** [comment]
This is allowed for buttons in form header, but not in lists.

**Comment by elgow** [comment]
Can you point me to the place in the docs where it says that, because I have already pointed to the place where it says otherwise. The rng schema also allows it.

**Comment by pedrobaeza** [comment]
Well, I'm talking over experience, not over documentation.

**Comment by elgow** [comment]
My experience agrees with yours on this. The docs, though, say something else, so it's at least a documentation bug. I don't think there's any real technical barrier to making it work as documented, and it seems as worthwhile now as it must have when they originally documented it. I suspect that this is similar to the `on_write` case and is something that worked for versions <= 10 and got lost in the move to the new v. 11 javascript front end.

I hope that someone at Odoo will take up this issue and either fix the docs or, preferably, put the feature back  into the front end code.
________________________________

**Comment by Yenthe666** [comment]
@Feyensv perhaps something to check for your doc PR's too ;)

**Comment by sswapnesh** [comment]
> Well, I'm talking over experience, not over documentation.

@pedrobaeza  Why are you not reporting these kinds of undocumented Facts here? :thinking:  (Maybe Issue or PR with Such Improvement)
This will help us a lot. :pray:

**Comment by pedrobaeza** [comment]
It's only a matter of time... but that's why I have kept it opened.

**Comment by Yenthe666** [comment]
@pedrobaeza is like a walking encyclopedia for Odoo. 🥇

**Comment by elgow** [comment]
I find myself once again wanting a confirmation dialog on a button in a list view. I keep seeing reasons that this feature was provided before the new v11 UI was implemented. Is there any chance of getting this issue moved from Documentation to UI? Just removing it from the docs solves the inconsistency issue, but degrades the product.

**Comment by Feyensv** [comment]
The feedback to request consistency between list/form/kanban views for the confirm attribute on buttons has been done.  At least for now it's fixed in the doc.
