### ISSUE TITLE
[13.0 ALPHA][BUG] WEB HTTPS

### ISSUE THREAD

**Issue by fresth** [odoo/odoo#37035]
Impacted versions: 13Alpha

Steps to reproduce:
When installing the web module
When you connect through Cloudflare and activate https
Google crhome reports that an malicious file was attempted to load, the problem is that the navigation menu does not load.
Commenting on line 444 of the file:
web / view / webclient_templates.xml
When commenting on those lines, if you load the navigation menu, google chorme does not report the loading of the malicious file; but, of course, commenting on these lines leaves other causal problems; I ask you to review that topic. Thank you.
![2](https://user-images.githubusercontent.com/9604848/65067964-4da6d880-d94d-11e9-8ccc-807146f570ee.png)
![3](https://user-images.githubusercontent.com/9604848/65067965-4da6d880-d94d-11e9-81fc-31c5f7392130.png)

**Comment by Yenthe666** [comment]
Hi @fresth,

Sorry but Odoo does not allow bug reports against the master version from Odoo. Only the last three stable versions are supported and as the master version is constantly changing they've decided not to allow bug reports.
CC @JKE-be as website related.

Regards,
Yenthe

**Comment by JKE-be** [comment]
probably not a bug. But misconfiguration of server / instance

=> check domain
-> check header request with documentation

We use a relative url, so if you have a non ssl request, it is probably due to missing header:

>  ## Add Headers for odoo proxy mode
>  proxy_set_header X-Forwarded-Host $host;
>  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>  proxy_set_header X-Forwarded-Proto $scheme;
>  proxy_set_header X-Real-IP $remote_addr;

Bg report is not clear on the configuration used.
