### ISSUE TITLE
[7.0] [8.0] Wrong amount for invoices generated from picking when the currency is not the company currency,

### ISSUE THREAD

**Issue by joaoalf** [odoo/odoo#3704]
After 8973217ea77e939337ede0890a4dcfdac22b1cd5 the invoices generated from pickings with a currency other than the company currency are generated with wrong amounts.

Steps to reproduce:
1. Create a purchase other in a currency other than the company currency
2. Configure Odoo to generate invoices from reception orders
3. Validate and receive the purchase.
4. From the picking confirm the reception and generate the invoice

Expected result:

Invoice with the same amount as PO

Result:

Invoice with a different amount.

**Comment by Yenthe666** [comment]
Hi @joaoalf,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
