### ISSUE TITLE
Chinese word in the view xml was not exported by translation

### ISSUE THREAD

**Issue by kevin3274** [odoo/odoo#3706]
in openerp/tools/translate.py

```
def _push(callback, term, source_line):
    """ Sanity check before pushing translation terms """
    term = (term or "").strip().encode('utf8')
    # Avoid non-char tokens like ':' '...' '.00' etc.
    if len(term) > 8 or any(x.isalpha() for x in term):# this line was skiped the Chinese word
        callback(term, source_line)
```

**Comment by Yenthe666** [comment]
Hi @kevin3274,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. Translations have improved quite a bit in the newest versions though. 😉 

Regards,
Yenthe
