### ISSUE TITLE
bill task work selects wrong receivable account in multi-company context

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#371]
When running Bill Task Work, it is possible to create an invoice where the partner account (field account_id) is from a different company than the invoice.

This one applies to 6.1 and trunk.
It is a variant of lp:1047826.

How to reproduce:
1. install trunk and accounting module and hr_timesheet_invoice module
2. create 2 companies A and B with diferrent charts of account
3. create a 3rd company M as partent of A and B
4. set set user preferences to company M
5. create a partner
6. create an analytic account named Project1 for company A with invoice factor = 100%
7. create timesheets on Project1
8. run bill task work
9. you get a draft invoice for company A (the account's company), this is correct
10. if you click on the receivable account to see the details, you see it is the receivable account of company M -> this is not correct.

I'll attach a merge proposal.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
