### ISSUE TITLE
Paypal payment redirect to web.base.url only for odoo 12 multi websites

### ISSUE THREAD

**Issue by eversatis** [odoo/odoo#37120]
Impacted versions: Odoo 12

Steps to reproduce: Set one same paypal account payment for multiple websites

Current behavior: PayPal redirect to web.base.url website for all websites

Expected behavior:PayPal redirect to relevant websites

I remembered this issue is not exist for sandbox environment. But all my customer feedback that my live websites redirect to my web.base.url websites after payment. Anyone else lively use paypal on odoo 12 multi website environment? Thank you.

**Comment by rdeodoo** [comment]
The base url retrieval was improved in later version with https://github.com/odoo/odoo/commit/573ed74c121c1572b3fab6f9553ed7f93f7b3f99
Generally, base url was improved to handle multi website in a better way in Odoo with https://github.com/odoo/odoo/pull/68201
