### ISSUE TITLE
Wrong behaviour of web calendar on drag if first_day_of_week is monday!

### ISSUE THREAD

**Issue by greenflash1357** [odoo/odoo#3712]
Impacted version: 
7.0 (maybe others)
Server: Debian
Client: Windows 7, Mozilla Firefox

Reproduction steps:
1. Change the users language to (any) language which has monday as first_day_of_week in calendar. (I have only tested 'German/Deutsch')
2. Open a calendar view.
3. Create a new event by dragging from any day to any monday!

Current behaviour:
The pop up form shows a new event with wrong date_deadline (not shown) and duration (only 1 hour). The behaviour is exactly that of clicking on a date in calendar view.

Excpected behaviour:
Correct date_deadline as defined by the drag and correct duration calculation.

Screenshot:
![drag](https://cloud.githubusercontent.com/assets/8362810/5085173/8714e45c-6f0f-11e4-9117-f19cfd63e00a.png)

[Issue related help forum topic](https://www.odoo.com/forum/help-1/question/is-there-an-issue-with-drag-in-calendar-view-when-end-date-is-monday-63679)

**Comment by Yenthe666** [comment]
Hi @greenflash1357,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by bjkim47** [comment]
When I click Monday on calendar to make leaves request, web browser pops up error message even though following process can be done without autonomous day count. I am using community version 11.

**Comment by Yenthe666** [comment]
@bjkim47 please make a new bug report for this and add in detail how you can reproduce it.
