### ISSUE TITLE
calendar duration not computed correctly

### ISSUE THREAD

**Issue by hparfr** [odoo/odoo#37158]
Impacted versions:
12.0
Steps to reproduce:

Create an calendar.event, set a duration.
(you have start + duration == end)

Now change the duration, 
(you get start + duration != end)

Current behavior:
Stop is not the sum of start + duration when duration or start is changed.
https://github.com/odoo/odoo/blob/12.0/addons/calendar/models/calendar.py#L967

Expected behavior:
The behavior should be consistent and predictable. Do not remove this 1 second.

**Comment by sswapnesh** [comment]
Have a look at Description https://github.com/odoo/odoo/commit/ec801b54365590a392bb0f71aa51cea13f778fdb

Cc @dbeguin

**Comment by sswapnesh** [comment]
One more proof for the same

![Screenshot (11)](https://user-images.githubusercontent.com/16624719/66955403-dfeee900-f07f-11e9-8fe3-66c93c3db2d3.png)

![Screenshot (12)](https://user-images.githubusercontent.com/16624719/66955425-eda46e80-f07f-11e9-8005-8bad1c6724cf.png)

**Comment by dbeguin** [comment]
if you can handle this flow, ok for me as it's more clear to have rounded time :

"when switching from all day event to not all day event, due to
stop time = 23h59m59s, the rounding for duration leads to make the stop
pass to the next day (00h00). each time you switch between all day and
not all day, the duiration is incremented by 24h."

**Comment by hparfr** [comment]
Here, we are not switching from all day to not all day. 

That's why this fix ec801b5 is a regression.
While trying to fix this all day / not all day switch, it introduces unexpected changes in other contexts (like postpone, or duration change).

**Comment by mart-e** [comment]
Hi,

It was fixed at f6ae9f0aea5a250cbff
