### ISSUE TITLE
[12.0 CE] [Manufacturing] First partially produced quantity could not be sold before the end of the related manufacturing order

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#37169]
**Impacted versions:**
12.0 CE

**Steps to reproduce:**
Create new manufacturing order of a product X, quantity to produce for example 1000
Create corresponding working orders
Start working
Set current quantity to 600 for example
Click on Done

**Current behavior:**
Go go inventory and check the available quantity of the product X; it shows 0 even if I already produced 600 units

**Expected behavior:**
The produced 600 units should be directly ready for sale.
I shall make the 400 remaining quantity in scab; but it is not the case;
For me; when I click on Pause or Done; the manufacturing quantity shall enter to my stock.

**Comment by aitalinassim** [comment]
@sle-odoo

**Comment by jco-odoo** [comment]
You have to post inventory
