### ISSUE TITLE
[12.0] Optional Products can create several sale order lines, only reference last one

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#37162]
Hello,

We seem to have stumbled upon a bug in the sale_management, regarding optional products.

After adding optional products to a sale order, you can generate several sale order lines from each of those optional products. Therefore, it makes sense for Odoo to add the sale order line ids to each sale order option.

What happens, however, is that the field relating the sale order option to the sale order lines it generates is a Many2one. In the same manner, there is a One2many field declared in the sale order line model connecting it to the sale order option model, which means that it's reversed (right now it's allowing each sale order line to store several sale order option ids and not the opposite, while it's the sale order option that can generate several sale order lines).

The sale order option add_option_to_order() method just replaces the Many2one line_id field with the last one, instead of adding it to a pool of ids (which would probably make more sense).

One2many field: https://github.com/odoo/odoo/blob/12.0/addons/sale_management/models/sale_order.py#L142

Many2one field: https://github.com/odoo/odoo/blob/12.0/addons/sale_management/models/sale_order.py#L162

Write method on add_option_to_order(): https://github.com/odoo/odoo/blob/12.0/addons/sale_management/models/sale_order.py#L204

Thank you.

**Comment by sswapnesh** [comment]
> Write method on add_option_to_order(): https://github.com/odoo/odoo/blob/12.0/addons/sale_management/models/sale_order.py#L204


Here we are adding `Sale Order Line` reference (Which we just created) on existing `Optional Product line `  Which LGTM.

I am not sure why we need `sale_order_option_ids` is on `sale.order.line` as it will be always one to one

------------------------------

Cc: @Feyensv  I could not find reference but we have discussed about `sale_order_option_ids` some where

**Comment by reinaldoramosarxi** [comment]
Hello,

Seems like this issue has been solved.

Thank you.
