### ISSUE TITLE
Website editor blocked by CORS policy when using SSL

### ISSUE THREAD

**Issue by jcdrubay** [odoo/odoo#37175]
Impacted versions:

- master (13alpha)

Steps to reproduce:

- Click on the button "Edit" of the website builder with https.

Current behavior:

 - Nothing seems to happen
 - In the Console, I see: Access to XMLHttpRequest at 'http://master.odoovanilla.xxx/website/translations/026ae15487c2067877f7b82ffb991974c070d399?mods=&lang=' (redirected from 'https://master.odoovanilla.xxx/website/translations//026ae15487c2067877f7b82ffb991974c070d399?mods=&lang=') from origin 'https://master.odoovanilla.xxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Expected behavior:

- Should load the Editor ...

Notes:

 - using the same nginx configuration as for other projects running in v12, I don't have this issue
 - everything works well in my local (without SSL) and same on Runbot (no SSL either)
 - the the System parameters, I have configured both entries:
   - web.base.url.freeze: True
   - web.base.url: https://master.odoovanilla.xxx

**Comment by mart-e** [comment]
Hi,

The weird part in your error is

> Access to XMLHttpRequest at http://master... (**redirected from https://**... has been blocked by CORS policy

So the request was initiated on https but was redirected to http.
Could you check your server is correctly behaving?

By the way, the master is very unstable, errors are expected. Could you test on a stable version if you have the same issue?
Also, if your plan is to test the future 13.0, you should check the saas-12.5 version instead.

**Comment by jcdrubay** [comment]
I am facing the same issue with `saas-12.5` as I was facing with `master`.

With the same configuration, I have no problem on a version `12.0`.

Can someone confirm that website can be edited with SSL?

**Comment by mart-e** [comment]
cc @JKE-be or @rdeodoo could you have a look if you know this issue?

**Comment by JKE-be** [comment]
You opened issue highlights a useless redirection. We will fix it.

But redirect from https to http is more a problem of config from your side.
Take a look here: https://www.odoo.com/documentation/12.0/setup/deploy.html#id7

so if you don't fix your configuration, you will probably have the same bug later on another request.

**Comment by JKE-be** [comment]
internal note: 
_introduced in saas-12.4_

**Comment by jcdrubay** [comment]
This is now working for me in v13 without changing the configuration on the server.

**Comment by mart-e** [comment]
Thanks for the update. I guess somebody fixed it in parallel ;-)

**Comment by JKE-be** [comment]
Strange when you know that the redirection is not yet fixed.

But nice to listen that

https://github.com/odoo/odoo/blob/13.0/addons/http_routing/models/ir_http.py#L305

**Comment by JKE-be** [comment]
My bad, fixed here: 08108486d5af4125324190eb61a6be0dedcba7a7

Probably the wrong place, but that explain why you don't have anymore the bug.
