### ISSUE TITLE
this place has a bug

### ISSUE THREAD

**Issue by mxz19901102** [odoo/odoo#37189]
model:  account.abstract.payment     method:  _compute_journal_domain_and_types

line:188    has_invoices is not a field of this model

**Comment by pedrobaeza** [comment]
Which version? And please don't make reference to line numbers, as this moved in time. Provide the permalink at least.

**Comment by sswapnesh** [comment]
Seems duplicate of https://github.com/odoo/odoo/issues/31411
Related PR https://github.com/odoo/odoo/pull/32847

**Comment by pedrobaeza** [comment]
Yes, closing.
