### ISSUE TITLE
Reverse Transfer double inventory valuation

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#3719]
Double Reverse Transfer doubles of the stock

Steps to reproduce:
1. Purchase 1 unit iMac from Supplier
2. Reverse Transver (without invoicing) to supplier (repair) - picking XXX
3. Reverser Transfer - click Reverse Transfer on picking XXX  (without invoicing) from supplier (from repair)
Current Inventory valuation.... 2 pcs!!!
Product info - Quantity On Hand = 1pcs
Report Stock valuation ... 2 pcs!!!

**Comment by fanha99** [comment]
hi,

the other ways to reproduce this bug.
1. purchase 1 unit from supplier with PO1, receive product, not receive invoice yet.
2. sale 1 unit to customer. transfer product, invoice, done.
3. purchase 1 unit again with PO2, receive product, invoice, done.
4. reverse transfer 1 from the picking of PO1, with out invoicing.
5. receive invoice of PO1, cancel it, corrected fix the PO1.

Report Stock valuation = -1 
Product info - Quantity On Hand = 0

**Comment by fanha99** [comment]
is this the same as:
https://github.com/odoo/odoo/issues/5848

**Comment by Yenthe666** [comment]
Hi @zbik2607 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
