### ISSUE TITLE
budget position should support view accounts

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#372]
https://bugs.launchpad.net/ocb-addons/+bug/1070418

In account_budget module, when creating a budget position, the user can select view accounts and also accounts with consolidation children, in addition to normal accounts.

However, when viewing budgets with positions containing only view accounts, the "practical amount" field is always zero.

Since these type of accounts are accepted as budget positions, the system should take into account children and consolidation children when computing the practical amount.

How to reproduce:
1. install account_budget module
2. create some moves on a general account
3. create a budget position containing one *view* account -> debit and credit values are shown correctly in the budget position
4. create a budget with one line referring to the above budget position -> the practical amount is always 0

**Comment by beledouxdenis** [comment]
Fixed in odoo 7.0 from revision da9d1a8c4594835217a7af78fe66f188e3260b63, coming from PR #1247.
It will be ported to Odoo 8.0 and newest releases in the coming days, through a forward-port.
