### ISSUE TITLE
Incorrect spellings in the Workflow graph view.

### ISSUE THREAD

**Issue by Nick-OpusVL** [odoo/odoo#3720]
Go to Settings -> Workflows -> Workflows

Click a workflow and choose the graph view.

Note the following string:

When customizing a workflow, be sure you do not modify an existing node  or arrow, but rather add new nodes or arrows. If you absolutly need to  modify a node or arrow, you can only change fields that are empty or set  to the default value. If you don't do that, your customization will be  overwrited at the next update or upgrade to a future version of Odoo.

"overwrited" should be "overwritten"

**Comment by Yenthe666** [comment]
Hi @Nick-OpusVL,

Thanks a lot for the bug report.
You can fix translations on Transifex and the source terms with a PR to Github. For more information see https://github.com/odoo/odoo/wiki/Translations
If you can reproduce these kind of cases in Odoo 9 and up you can create a new report, report it with an enterprise license or fix it your own.
I'm closing this one as Odoo 8 is no longer supported.

Regards,
Yenthe
