### ISSUE TITLE
Admin's Access Rights Page is not correclty rendered after --update-all

### ISSUE THREAD

**Issue by mariusmarolla** [odoo/odoo#3721]
Impacted Odoo Version: 8.0

Steps to reproduce:
1. create a new DB
2. Enable Technical View for Admin user
3. Reload page
4. Exit
5. Stop server
6. Start server with "--update=all --i18n-overwrite" options
7. Login to DB
8 Access "Settins / Users / Admin"
9 Page should not be rendered correclty

Current behavior:
Page only contains a list of groups

Expected behavior:
Dropdownas etc. should be shown to manage user access rights

Operating Systems:
Debian 6, Windows 7, Windows 8.1

Browsers
Firefox, Chrome, IE

**Comment by Yenthe666** [comment]
Hi @mariusmarolla ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
