### ISSUE TITLE
[8.0] [7.0] Missing mandatory field (place) relative to incoterms

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3724]
In the Sale Order you have the possibility to select incoterms. However for some incoterms you have to specify the port/place you will deliver through. 

So we need a extra text field next to the current field-selection 'Incoterms' 

Thanks

Frederic 
camptocamp

![incoterm in so](https://cloud.githubusercontent.com/assets/5735158/5087621/ac932d18-6f2a-11e4-9140-04fa4a444653.png)

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
