### ISSUE TITLE
wedsite-builder custom images removed following db-upgrade

### ISSUE THREAD

**Issue by CraigBarnesOpusVL** [odoo/odoo#3725]
I have updated our platform to the current git 8.0 branch.

Following db upgrade the website-builder images are removed and various other artefacts are changed.

This is the upgrade command that I am using
`openerp-server --stop-after-init -i all -c /srv/odoo/odoo.conf --without-demo=WITHOUT_DEMO -d <db>`

before upgrade db https://crl.odoocloud.uk/page/services
after upgrade db https://updatecrl.odoocloud.uk

Both sites are running from the same odoo instance.

**Comment by Yenthe666** [comment]
Hi @CraigBarnesOpusVL ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
