### ISSUE TITLE
Wrong cache when changing context

### ISSUE THREAD

**Issue by lucio-itecnis** [odoo/odoo#3728]
When the context is changed (recs = recs.with_context(key=value) ) before the record is saved, the values in recs.env.cache are lost.

For example, I want to add values to the context of "product_id_change" of account.invoice.line and when doing so before calling the super, I can no long access self.incoive_id.

I have done this change in api.py (line 739) replaced with:

env = Environment(cr, uid, context)
env.cache = self.cache
return env

It is working for me, but I am not 100% sure that this won't break anything...

**Comment by rco-odoo** [comment]
What you observe is intentional: the field values depend on the environment. Therefore, the cache depends on the environment. In other words: each environment has its **own** cache.

See my presentation on https://www.odoo.com/slides/slide/advanced-features-of-the-api-206 (slide 19).

**Comment by lucio-itecnis** [comment]
Thanks for your response Raphael.

Nevertheless, somehow it doesn't seem right for me that, if try to put
something in the context you lose the values for example in on_change
methods.

In the old API you used to pass all arguments  explicitly so you where able
to modify the context and also keep the values passed from the view.

I encountered this problem sometimes when inheriting a model and calling
super and needing to modify the context. Maybe I should manually assign the
original-context-instance's values to the context-switched-instance in this
cases.

Anyway, thanks for your response.

Bye!

2015-09-04 12:23 GMT-03:00 Raphael Collet <notifications@github.com>:

> What you observe is intentional: the field values depend on the
> environment. Therefore, the cache depends on the environment. In other
> words: each environment has its *own* cache.
>
> See my presentation on
> https://www.odoo.com/slides/slide/advanced-features-of-the-api-206 (slide
> 19).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/3728#issuecomment-137765076>.
>



-- 
Lucio Nardelli
[image: Imágenes integradas 2]
                      La simplicidad es la sofisticación suprema
