### ISSUE TITLE
[WISH] Product's attribute filter per website category

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#37302]
In retail ecommerce we can have many kind of products. Attributes filters would be more useful if some of them could be enabled or visible only per ecommerce categories.
For example, in a selling toys website size filter is useful in "disguise" category, but not used elsewhese.

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/e-commerce/tree/11.0/website_sale_product_attribute_value_filter_existing

**Comment by zeroheure** [comment]
Thanks, you are the one ! Nobody else knows all OCA modules !
