### ISSUE TITLE
[11.0]psycopg2.OperationalError: could not obtain lock on row in relation "ir_sequence_date_range"

### ISSUE THREAD

**Issue by prasojojiwandono** [odoo/odoo#37318]
Hi.
I try to make customer payment in odoo 11 , and I got an error like this
psycopg2.OperationalError: could not obtain lock on row in relation "ir_sequence_date_range"

![payment error](https://user-images.githubusercontent.com/23108110/65482448-58b8b600-dec3-11e9-9719-6031f0ae4fe9.png)

any suggestion to handle this error?

**Comment by pedrobaeza** [comment]
This is because several users use the same sequence simultaneously. Use standard sequences instead of no gap ones.

Closing as this is not an Odoo issue itself.

**Comment by prasojojiwandono** [comment]
> This is because several users use the same sequence simultaneously. Use standard sequences instead of no gap ones.
> 
> Closing as this is not an Odoo issue itself.

Thank you
