### ISSUE TITLE
[7.0] Manual entries posting : Wrong computation when 'taxe included' taxe are used

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3731]
Step to reproduce: 
- Create a new instance with l10n_fr 
- Go to Accounting / Journal entries / Journal items
- create a new line with whatever date and account but select the tax : TVA déductible (achat) 10,0% TTC and a debit = 100
- When you press enter to create the seond line, you should see teh VAT line automatically created.

The error is that the computation is wrong since the untaxed amount should be 100 / 1.10 = 90.91 and the vat 9.09 since it is a taxe inclusive. Please check out the printcreen.

![wrong_vat](https://cloud.githubusercontent.com/assets/5735158/5090145/52d467e0-6f40-11e4-8ba0-ea366442cc4a.png)

This mecanism works fine in V8.0. 

Thanks

Frederic Clementi

**Comment by mdietrichc2c** [comment]
Hello,
any news on merging this issue?

Best regards,
Matthieu Dietrich

**Comment by skh-odoo** [comment]
PR created for this issue: https://github.com/odoo/odoo/pull/4922

**Comment by mart-e** [comment]
Hello,

Fix was merged in 7.0 at 39010d38567a4d679cbdb8c0e21cffec6c3bb6b0, backport from 8.0.
Thanks for the report
