### ISSUE TITLE
Can somebody upload a serious working step-by-step installation guide? 

### ISSUE THREAD

**Issue by CMauricioRuizCh** [odoo/odoo#37311]
Impacted versions: 12 and 13

Steps to reproduce: A real installation gudie

Current behavior: I simply cant startup my odoo 12 in Ubuntu+AWS

Expected behavior: Something that actually works

Video/Screenshot link (optional):

**Comment by CMauricioRuizCh** [comment]
I'm a new developer with Odoo. 
I'm working for a new startup in Colombia, they've got a community version of Odoo 8, connected to prestashop. I want to change that and migrate them to a enterprise version 12 or 13 and woocommerce. But first I need to run a sandbox, 'cause we want to implement a Omnichannel solution. 

It's been basically a pain in the ass to get odoo 12 or 13 community version up an running. I've been trying, but right now I just can't.

Please, HELP!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
