### ISSUE TITLE
[11.0] Wrong "To consume" calculation when Produce an MO

### ISSUE THREAD

**Issue by Lopsanz** [odoo/odoo#37354]
Impacted versions:
11.0

Steps to reproduce:
Traceability by lots on components.
Make a BOM X for 1 UNIT or product F (1 unit of product A and 1 unit of product B)
Make a MO for 1 DOZEN of product F based on BOM X
Check availability
Click on "Produce"

Current behavior:
to make 1 DOZEN of product F, the field "to consume" in components list takes 1 unit of each product A and B.

Expected behavior:
Field "To consume" must be filled with 12 units of each product.
![image](https://user-images.githubusercontent.com/22096355/65505763-4726dc80-deca-11e9-9710-81d2c33b27de.png)
Calculation is good!
![image](https://user-images.githubusercontent.com/22096355/65505739-35ddd000-deca-11e9-9da8-2e649ec35416.png)
What a mess!

**Comment by kos94ok-3D** [comment]
Hi, @Lopsanz. I think you can close it.

**Comment by Lopsanz** [comment]
Tested. Ty
