### ISSUE TITLE
[8.0/Master] HTML not escaped properly in forum comments (see screenshot)

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#3737]
<h2>Impacted versions:</h2>

<p>8.0 and above</p>

<h2>Steps to reproduce:</h2>

<ul class="task-list">
<li>Go to Odoo.com and login as a normal user for commenting in the forum.</li>
<li>comment on a forum post with some XHTML code.</li>
<li>Post the comment and take a look.</li>
</ul>

<h2>Current behaviour:</h2>

<ul class="task-list">
<li>XHTML is not properly escaped in the comments. See screenshot and code example below:</li>
</ul>

<img src="https://cloud.githubusercontent.com/assets/2337666/5101222/3299e69e-6fef-11e4-9d89-281d83519cdc.png"/>

    <template id="product_add_to_cart_Genesis" inherit_id="website_sale.product" name="Add To Quote - Logged In" customize_show="True">
        <xpath expr="//a[@id='add_to_cart']" position="replace">
	    <a t-if="not user_id.partner_id.name == 'Public user'" id="add_to_cart" class="btn btn-primary btn-lg mt8 js_check_product a-submit" href="#"><i class="fa fa-angle-double-right">    </i>&amp;nbsp;&amp;nbsp;&amp;nbsp;Add to Quotation</a>
        </xpath>
    </template>

<h2>Expected behaviour:</h2>

<ul class="task-list">
<li>XHTML is fully escaped in the comments.</li>
</ul>

<h2>Preferred behaviour:</h2>
<ul class="task-list">
<li>Reply to comment features (use facebook as an example) to allow users to comment on specific comments. The reply would be slightly indented underneath the comment being replied to.</li>
<li>Basic html formatting allowed by use of forum-specific markup in comments to allow for better organisation of comments (eg. line breaks, <code> tags for code snippets, etc.)</li>
</ul>

**Comment by Yenthe666** [comment]
Hi @mart-e and @JKE-be,

This issue is still present in Odoo and in all honesty it is really annoying, especially on the Odoo help forum.
Could we  improve the current parser in order to be able to allow this? At this point posting code is quite hard.

**Comment by mart-e** [comment]
Hi,

Thanks for the report, we have fixed it at 30f06fd39e856a97c5aed7cff461e1bb207232bc

**Comment by lukebranch** [comment]
@Yenthe666 , @mart-e ,

Thanks for the fix!
