### ISSUE TITLE
Odoo live forum tags field going stuck, losing asked question. 

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#3738]
Hello, Recently when I try to ask new question in live <a href="https://www.odoo.com/forum/help-1/ask" target="_blank">Odoo forum</a>. 
I wrote question heading, description text normally as like other. But when I was come tags fields I press simply "odoo" character and page going to stuck. Page doesn't response. and finally my question heading, whole question description was lost.

I find the reason there is so many tags are exist, even if I'm type any word in tag field that are not existing tags create automatically. 

<b>Suggest:</b> 
1. Need to refactor existing tags.
2. I think OP's select only existing tags, can not create new tag on ask question page. 
3. Can create tags - Get this privileges if karma more then specified (i.e. if ABC user karma more than 1000, ABC can create new tag). 
4. When OP post new question, moderation must take a review of the OP question. If need then moderator can asked question update tags, Is this not worth it point but one of the possibility.

<b>Effected in</b> : version 8(Live <a href="https://www.odoo.com/forum/help-1/ask" target="_blank">Odoo forum</a>) or may be in master.

**Comment by Yenthe666** [comment]
@JKE-be I believe this can be closed?

**Comment by JKE-be** [comment]
@Yenthe666 thanks for your help ;)
