### ISSUE TITLE
[12.0] orm: multi "depends on non-stored field"

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#37400]
Impacted versions: 12.0 (last)

Durring install/upgrade module there is multi time the same line with "xxx depends on non-stored field xxx". Before there is only one line.

![image](https://user-images.githubusercontent.com/16716992/65576114-9b38cc00-df71-11e9-9b62-b9bcd19b1477.png)

@rco-odoo 
@nim-odoo

**Comment by pedrobaeza** [comment]
Being silenced in https://github.com/odoo/odoo/pull/37242

**Comment by fmdl** [comment]
Close by : https://github.com/odoo/odoo/pull/37242
