### ISSUE TITLE
[11.0] Odoo Repeat journal entries sequence (numbering)

### ISSUE THREAD

**Issue by prasojojiwandono** [odoo/odoo#37410]
Hi,

I have a problem with journal entries numbering, The number is repeated.
![repeate_number](https://user-images.githubusercontent.com/23108110/65587312-dc4fd100-dfaf-11e9-9cb2-a52b86a28e90.png)

my suspect is because we do change the sequence from no gap to standard , and the reason we change the sequence is because of [this](https://github.com/odoo/odoo/issues/37318) problem. if that is true how to handle the repeated number (sequence)?

or do you have any idea how to deal with this repeated number (sequence)?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: Change next number in sub-sequences.
