### ISSUE TITLE
[8.0] server error return strang message in web client

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#3743]
SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data is raised in weclient when server returns : 

```
  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> 
  <title>500 Internal Server Error</title>
  <h1>Internal Server Error</h1>
  <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: You shouldn't be able to reproduce this on newer versions anymore. 😉 

Regards,
Yenthe
