### ISSUE TITLE
Error after cloning branch 12.0

### ISSUE THREAD

**Issue by FelipeEnriqueGG** [odoo/odoo#37458]
Impacted versions:
12.0
Steps to reproduce:
clone the repository (branch 12.0)
Current behavior:
error 500 Internal Server Error

Logs:
sep 25 13:55:49 hb-lap-0007 odoo12[18364]: 2019-09-25 18:55:49,649 18364 INFO ? werkzeug: 127.0.0.1 - - [25/Sep/2019 18:55:49] "GET /web/database/selector HTTP/1.1" 500 - - - -
sep 25 13:55:49 hb-lap-0007 odoo12[18364]: 2019-09-25 18:55:49,652 18364 ERROR ? werkzeug: Error on request:
sep 25 13:55:49 hb-lap-0007 odoo12[18364]: Traceback (most recent call last):
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     execute(self.server.app)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 193, in execute
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     application_iter = app(environ, start_response)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo/odoo/service/server.py", line 409, in app
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     return self.app(e, s)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 128, in application
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     return application_unproxied(environ, start_response)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     result = odoo.http.root(environ, start_response)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo/odoo/http.py", line 1319, in __call__
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     self.load_addons()
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/opt/odoo12/odoo/odoo/http.py", line 1335, in load_addons
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     manifest = ast.literal_eval(pycompat.to_native(manifest_data))
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     node_or_string = parse(node_or_string, mode='eval')
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:   File "/usr/lib/python3.7/ast.py", line 35, in parse
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     return compile(source, filename, mode, PyCF_ONLY_AST)
sep 25 13:55:49 hb-lap-0007 odoo12[18364]: File "<unknown>", line 34
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:     <<<<<<< HEAD
sep 25 13:55:49 hb-lap-0007 odoo12[18364]:      ^
sep 25 13:55:49 hb-lap-0007 odoo12[18364]: SyntaxError: invalid syntax - - -

Expected behavior:
It should show the database selector

**Comment by pedrobaeza** [comment]
You have merged incorrectly the branch and have conflicts. Solve that.

Closing as not Odoo issue.
