### ISSUE TITLE
Scheduled Actions not running in Odoo 8.0

### ISSUE THREAD

**Issue by andylemay** [odoo/odoo#3746]
Hi,

I have installed odoo Version 8.0-83bd9ee via bitnami and am trying to get the "scheduled actions" to work for incoming email.  Manual "Fetch" works perfectly

"Fetchmail service" appears to be configured correctly and is active.  No errors in the log.

I have tried altering the parameters but it makes no difference.

Does anyone have any ideas why none of the schedule actions are running?

Thanks 

Andy

![screen shot 2014-11-19 at 13 12 16](https://cloud.githubusercontent.com/assets/5936400/5104742/bfb16e14-6fed-11e4-89ba-e3af46a4ed9e.png)

**Comment by Atheryl** [comment]
Did you check your openerp-server.log ?

I was stuck for many days and realised that I used another Database name and my openerp-server.conf still mention the old one generating and error at start for this instances only.

**Comment by mdauphin** [comment]
Restart server work for me

**Comment by Yenthe666** [comment]
Hi @andylemay ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by rossigee** [comment]
This is easy to reproduce, and still occurs with latest Odoo 11 image. I have filed a fresh bug report (#23002) with steps to reproduce.
