### ISSUE TITLE
invoice_date_due does not change when payment_term_id changed

### ISSUE THREAD

**Issue by hileut2016** [odoo/odoo#37473]
on odoo 13 invoice_date_due does not change when payment_term_id changed in vendor/customer bill

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo doesn't accept bug reports against the master version. As V13 is not yet released this branch is in active development and tickets are not handled.
I'm closing this issue because of this reason. If you still face it once V13 is out we can reopen this ;)

Regards,
Yenthe
