### ISSUE TITLE
[Website_Blog] Subtitle Problem

### ISSUE THREAD

**Issue by amindehghani** [odoo/odoo#37470]
Impacted versions: v12

Current behavior: cannot delete blog subtitle when 2 languages are active.
it translates the subtitle and when i delete it replaces it again from the translate

Expected behavior: able to delete blog subtitle without the need of changing the translation to empty

**Comment by pedrobaeza** [comment]
Until v13, what you can do is only to let for example an space for simulating an empty string.

This is a know problem, but as said, it will be repaired on next version, so closing as won't fix for previous versions.
