### ISSUE TITLE
wrong french translation on e-shop confirmation

### ISSUE THREAD

**Issue by sballe73** [odoo/odoo#37478]
Impacted versions: 12

Steps to reproduce: use french interface, allow user self registration, as unregistered user purchase a product and go to confirmation. 

Current behavior:
The button proposing to register indicates "S'inscrirer" which is wrong

Expected behavior:
correct to "S'inscrire" without the final R.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/8128986/65692062-3a44ed00-e072-11e9-8b56-6019181deb40.png)

**Comment by pedrobaeza** [comment]
Please see how to correct the translation in https://github.com/odoo/odoo/wiki/Translations

Closing as no Odoo code issue.

**Comment by sballe73** [comment]
Thanks, I registered there but I cannot find anywhere the "Transifex Integration" module mentionned in the doc I should add to my base.

**Comment by pedrobaeza** [comment]
You can search the term directly through Transifex. Any way, the module is https://github.com/odoo/odoo/tree/12.0/addons/transifex

**Comment by sballe73** [comment]
Thanks, I understand now that I had to remove the application filter to see it.
It could be indicated in the translation page, as well as the fact you need to activate developper mode and go to general configuration/translations (for newbies like me)
I found the translation and can correct my own base, but the transifex link is missing and I cannot find it in transifex as I do not get what ressource name correspond to this element :
![image](https://user-images.githubusercontent.com/8128986/65696518-a5de8880-e079-11e9-92d8-8d140f282ac9.png)

**Comment by pedrobaeza** [comment]
Do it directly in Transifex as indicated.

**Comment by sballe73** [comment]
I got that in the first place and tried, but you have 310 resources files, how to you find wich one contains the term ?
You cannot search globally from a translated term there or I could not find how.
![image](https://user-images.githubusercontent.com/8128986/65698812-6619a000-e07d-11e9-845e-c374e0ef5b4c.png)

**Comment by pedrobaeza** [comment]
You have to click on "Traduire", then go to the end of the resources list, and click on all resources, and then search "globally". Or you can see which module this term belongs and go directly to that resource.

**Comment by sballe73** [comment]
Miracle, I finally got it :)
Thanks !
