### ISSUE TITLE
README.md file not added to translations

### ISSUE THREAD

**Issue by feketemihai** [odoo/odoo#3747]
Create a module with the description in README.md file, if you will export the pot file for the module, the description from the file isn't add in the pot file.

**Comment by Yenthe666** [comment]
Hi @feketemihai ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
This is still the case in all Odoo versions. I've recently asked feedback about this but it is not on the wishlist/to do list for now. You could add the translations yourself in the `.po` files though.

Regards,
Yenthe
