### ISSUE TITLE
[12.0] B2B and B2C taxes error

### ISSUE THREAD

**Issue by Odoolatam** [odoo/odoo#37481]
Impacted versions:
12.0

Steps to reproduce:
- Go to Accounting > Configuration > Settings
- On **Line Subtotals Tax Display** select _Tax-Included_ and save the changes.
- Select _Tax-Excluded_ again and save the changes.

Current behavior:
An Odoo Server Error is raised

> A user cannot have both Tax B2B and Tax B2C.
> You should go in General Settings, and choose to display Product Prices
> either in 'Tax-Included' or in 'Tax-Excluded' mode
> (or switch twice the mode if you are already in the desired one).

Expected behavior:
It should be possible to change the values for **Line Subtotals Tax Display** without problems.

Video/Screenshot link (optional):
![Screenshot_20190926_134104](https://user-images.githubusercontent.com/48928654/65708390-df58c900-e064-11e9-9c1e-d93318aaab28.png)

![Screenshot_20190926_134216](https://user-images.githubusercontent.com/48928654/65708416-eb448b00-e064-11e9-8f21-415e1cf756d6.png)

![Screenshot_20190926_134240](https://user-images.githubusercontent.com/48928654/65708424-ef70a880-e064-11e9-81bf-7f633a264d39.png)

**Comment by pedrobaeza** [comment]
That's because you have manually changed groups of one user to belong to the other group (B2B / B2C) that you are selecting.

**Comment by Odoolatam** [comment]
I don't have change anything on users, I'm just making the test on runbot odoo and I get the same result on both community and enterprise.

![Screenshot_20190926_140043](https://user-images.githubusercontent.com/48928654/65709098-66f30780-e066-11e9-9555-31e3e8fa2b20.png)

**Comment by pedrobaeza** [comment]
OK, then some default groups can be misconfigured. Tagging.

**Comment by Odoolatam** [comment]
I thought the problem was in our instance, that's why I did the tests on runbot

**Comment by sswapnesh** [comment]
Seems from https://github.com/odoo/odoo/commit/9badedcd98fcb63e02a5c6de8be86e558433dd44
@len-odoo  Could you please have a look ?

**Comment by len-odoo** [comment]
Tomorrow morning I'll have a look.

**Comment by len-odoo** [comment]
Should be solved by https://github.com/odoo/odoo/pull/37517 (soon).

**Comment by Odoolatam** [comment]
Hello, any notice about this?

**Comment by sswapnesh** [comment]
This has been Fixed in #37517
