### ISSUE TITLE
When a product is added to wishlist from a portal or an internal user on website. After deleting the product from the wish-list you are not able to add it again in the wish-list

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#37485]
Impacted versions: Odoo12

Steps to reproduce: Add a product in wishlist from the portal or public user, then delete the same from wishlist then you will not be able to add the same product again.

Current behavior: 

Expected behavior: It should be add again once if we delete it.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

**Comment by jahangir260** [comment]
Hi, Thanks for your quick response.
Yes, I am able to generate the same on above-mentioned link as well.
https://prnt.sc/pbm26k

**Comment by fja-odoo** [comment]
https://github.com/odoo/odoo/pull/37135
This PR will fix that

**Comment by jahangir260** [comment]
@fja-odoo Thanks..

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/37135
