### ISSUE TITLE
Manufacturing module not displaying products/variants created in Inventory module

### ISSUE THREAD

**Issue by csidon** [odoo/odoo#37483]
Impacted versions:
11.0 Community

Steps to reproduce:
Let's say I have some earplugs that can be sold as individual replacement parts, or as a full set.
I've set it up so that:
**Parts**
Set up as Products with multiple variants
Can be purchased, Can be sold, Buy
Category: Accessories
**Example:** ![image](https://user-images.githubusercontent.com/12772213/65745893-51a6d780-e151-11e9-89de-8054fc03615e.png)

**Full sets**
Set up as Products with multiple variants
Can be Sold, Make to Order, Manufacture
Category: Product Set 
![image](https://user-images.githubusercontent.com/12772213/65746026-c24df400-e151-11e9-82dd-f7b150c5c5a9.png)

I then create BOMs (Kit) for each variant. So a Red 15 dB Earplug would have a BOM with a Red Eartip, a 15 dB Filter, a carrying pouch, a product manual and cords. 
![image](https://user-images.githubusercontent.com/12772213/65746073-e7426700-e151-11e9-9f63-82161229da66.png)
![image](https://user-images.githubusercontent.com/12772213/65746163-2c669900-e152-11e9-8b3c-cc3dea6bdaa4.png)
![image](https://user-images.githubusercontent.com/12772213/65746239-646ddc00-e152-11e9-9a37-c370533c4afb.png)
(Instead of creating a single BOM with multiple variants for the changing components, I've gone the tedious way round to create individual BOMs for each variant since it allows me more control over multiple areas. But I've tested with a single BOM too and the same issue still occurs.)

This is great because I can sell a Red 15 dB Earplug Set instead of selecting 1 eartip, 1 filter, 1 pouch and so on. It also allows me to calculate the "set" pricing according to fluctuations in component prices/currency fluctuations. Website sales work beautifully with this configuration as well.

HOWEVER, when I complete the sale and click on Delivery, I get the message "Status: Draft  Waiting Another Operation". Selecting "Check Availability" does absolutely nothing, and my Reserved items are shown as 0. (I have stock available for each of the components). 
![image](https://user-images.githubusercontent.com/12772213/65745800-068cc480-e151-11e9-868a-80c62651823e.png)

When I click in on the individual component, the item is "reserved", but not "manufactured" into a kit.

After some investigation, I realised that the Manufacturing module isn't picking up ANY of the products that I've created. The BOMs are all there, but when I try to manually create a Manufacturing Order, NONE of the products/BOMs in my inventory are reflected in the dropdown menu:
![image](https://user-images.githubusercontent.com/12772213/65746550-3dfc7080-e153-11e9-9849-624c702a12f6.png)
![image](https://user-images.githubusercontent.com/12772213/65746564-45bc1500-e153-11e9-9373-af0e8cd5ccff.png)
(The "products" shown there were created _in_ the Manufacturing Order itself since I was testing to ensure that the Manufacturing Operation actually works.)

Strangely enough, though, the products and BOMs are reflected under Manufacturing > Master Data > Products/Bill of Materials. But the Manufacturing Order simply isn't picking up on it.
![image](https://user-images.githubusercontent.com/12772213/65746730-ad726000-e153-11e9-9379-4b806086d302.png)
 
Has anyone else encountered the same problem? I saw in the forums that another person seems to be having a similar issue. https://www.odoo.com/fr_FR/forum/aide-1/question/product-and-or-bom-variants-odoo-11-community-133492
The suggested workaround was to use Product_Configurator_MRP but I can't see how that would actually accomplish what I need. Also it seems strange that the Manufacturing Order itself simply isn't picking up any of the Products or Variants created via the Inventory Module.

**Comment by csidon** [comment]
Anyone has any ideas around how to solve this issue?

**Comment by csidon** [comment]
@Yenthe666 the Odoo guru! Have you encountered this issue before, and would you know of any way to solve this please?

**Comment by Yenthe666** [comment]
Hmm I don't directly see the issue, sorry. Perhaps @sle-odoo could have a look at this though!

**Comment by sle-odoo** [comment]
i'm not sure i completely understood the flow but it seems you're using kit, so you shouldn't expect manufacturing order to be created for them (a kit is like a set of products)

also with the "buy" route, according to other settings a purchase order could be created and that's why your delivery would be waiting another operation, it is waiting the validation fo the receipt from the supplier

anyway this is more a bug tracker than a help forum, i suggest you to try to get help on the [forum](https://www.odoo.com/forum/help-1). 

if there's indeed a bug in the code feel free to ask to reopen this issue

regards

**Comment by csidon** [comment]
Hi @sle-odoo 

According to this article, "The assembly of the kit will be described by a manufacturing order rather than a packing operation". Shouldn't this mean that I'm expecting a manufacturing order?
https://www.odoo.com/documentation/user/10.0/manufacturing/overview/bill_of_materials/kit_shipping.html

I also tried experimenting with creating a Kit in Manufacturing, then Purchasing that Kit via the console, a BOM is created and processed, leading me to think that this would be the expected behaviour.

As mentioned before, my products and BOMs are reflected in Manufacturing, but the manual creation of a BOM isn't picking up on any of the items. This leads me to think that this is a bug, therefore this post. 

I don't select "Buy" for the kits, just for the individual components that make up the kit. So it shouldn't be awaiting that process, especially since all the individual components are in stock.

I also tried posting it on the forum but keep getting a "301 Not Authorised" error, so I'm really not sure what I can do. Would you please be able to help?
![image](https://user-images.githubusercontent.com/12772213/66537943-e01e4e80-eb7e-11e9-90d5-5cb766c038da.png)

Many thanks in advance.

**Comment by sle-odoo** [comment]
actually the whole sentence is 

> When you create the bill of materials, select the BoM Type Manufacture this product. The assembly of the kit will be described by a manufacturing order rather than a packing operation.

It means if you select manufacture on your bom, ant *not* kit, a manufacturing order will be created . The wording is strange and i created a feedback about it, but the rest of the article is clear about that in my opinion. If the bom type is manufacture, you'll get MO, if the bom type is kit, you won't get one.
