### ISSUE TITLE
[Master] Update fullcalendar

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#3749]
Hi,

I was wondering if you planned to upgrade the web_calendar to the last Fullcalendar version which is 2.1 ? 

Thanks in advance..

**Comment by sapperdeflap** [comment]
been on a goosehunt the past week as well to find something to create "resource view" in odoo, so thanks for the work on this,
pretty new to odoo and python, but this javascript is really not my field.

any chance to see these changes in action in odoo?
when using the commit fullcalendar2 in odoo 8.0 i get the following error:
"TypeError: viewclass is not a constructor"

same when checking out master-fullcalendar2-xmo

not sure if more then those 6 files are required or that its simply not ready yet as a whole

**Comment by llacroix** [comment]
You should consider speeding that change as on my firefox installation, fullcalendar 1.6 raise an exception: `allocation size overflow`. The module seems to be appending text in a loop and that may raise such kind of error...

**Comment by jkei** [comment]
Any news regarding this issue ?

**Comment by llacroix** [comment]
Regarding the issue that I found, it is a firefox bug.

**Comment by jkei** [comment]
I meant the global issue regarding the update of fullcalendar in version 2.x.x

**Comment by samersarhan** [comment]
Any update for this issue?

**Comment by klausjulius** [comment]
is there any update? i tried the above update method in odoo 9, but this doesn't work.
is there any solution for odoo 9. i need fullcalendar 2.x for the resource view. i want to realize different timelines for therapierooms. Does anybody have experience in updating fullcalendar in odoo 9?

**Comment by smorele** [comment]
i'm currently implementing the 2.x version on Odoo 8, resourceView works like a charm but I have some regression and bugs in the classic calendar view (in messaging)

**Comment by Yenthe666** [comment]
@xmo-odoo any update on this one?

**Comment by Yenthe666** [comment]
Hi @tfossoul ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by jzaburunov** [comment]
Hi, @smorele 

Is it available to see your progress with fullcalendar 2.x ? I will very love it.

**Comment by jzaburunov** [comment]
Here is my adaptation of fullcalendar 2.x for odoo 10 https://github.com/jzaburunov/groupcal

**Comment by BenasR** [comment]
Seeking. Any news about calendar possibility with drag n drop feature?
