### ISSUE TITLE
 Inventory lines should be sorted on screen and print documents

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#375]
https://bugs.launchpad.net/ocb-addons/+bug/1087033

inventory lines must be sorted

a multi page document with unsorted lines is unusable

In the same manner, unsorted lists are unusable on screen too when users have to enter the values.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
