### ISSUE TITLE
Many2many relation table links to wrong table when using _inherit and different _name

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#3751]
**Many2many relation table links to wrong table when using _inherit and different _name**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. Declare a model

```
class A(orm.Model):
    _name = 'model.a'
    _columns = {
        'name': fields.char(string='Name')
    }
```
1. Declare an new model with a "prototype" inheritance, with a many2many

```
class B(orm.Model):
    _name = 'model.b'
    _inherit = 'model.a'
    _columns = {
        'user_ids': fields.many2many('res.users', string='Users')
    }
```

Current behavior:
- A relation is created between `model.a` and `res.users`

Expected behavior:
- A relation is created between `model.b` and `res.users`

Workaround:
- Declare all the fields in the many2many:

```
    _columns = {
        'user_ids': fields.many2many('res.users', 'model_b_res_users_rel', 'model_b_id', 'user_id', string='Users')
    }
```

**Comment by Yenthe666** [comment]
Hi @guewen ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
