### ISSUE TITLE
Company logo does not display if you have two databases created on the server

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#3753]
it reverts to the default placeholder logo, this may also affect till receipt printing, see #1308 it can be solved by setting db-filter or adding a call to ensure_db to /addons/web/controllers/main.py line 1190

   def company_logo(self, dbname=None, **kw):
        ensure_db()

**Comment by TKeePeR** [comment]
Hi,

I have the same issue: company logo was updated on login page but not in main ones. 

I fixed it in:  addons/web/static/src/js/chrome.js line 1296, function update_logo
current: var img = this.session.url('/web/binary/company_logo' + (company ? '?company=' + company : ''));
fix: var img = this.session.url('/web/binary/company_logo' + (company ? '?company=' + company + '&company_rand=' + Math.floor(Math.random()*10000000): ''));

Not so clean by efficient. It limits browser caching on image.

**Comment by echterhoff** [comment]
Thanks @AlanBell !
Adding ensure_db() did for me the trick.

**Comment by mart-e** [comment]
Company logo fixed by using the database name parameter (was done at a few places).
Closing but if you still have it somewhere else, let us know (with info where exactly)

**Comment by TKeePeR** [comment]
Using database name will solve the issue as soon as browser cache is cleared from previous image.

**Comment by Bob1nz** [comment]
Hi I know this issue is no longer open but I am having the same issue described here although I only have the default postgres database and one other for odoo.
where exactly did you place "ensure_db()" in the main.py?

**Comment by treviser** [comment]
@mart-e I do have this issue again with 9.0c the latest version. When accessing the server using dbfilter it always displays the Odoo logo in the website, no matter what I do concerning my browser caches, it works properly in the backend though. When I'm accessing the server by IP address and selecting the database in the database selector, it works properly.

**Comment by mmalorni** [comment]
Same issue. The database name is not part of the URL for the image or anything else making it unique so the image is cached and doesn't change until you have cleared your cache. The link to retrieve the image should be unique per database and per company.
