### ISSUE TITLE
[12.0] When you try validate stock inventory with stock_account installed

### ISSUE THREAD

**Issue by renatonlima** [odoo/odoo#37554]
Impacted versions:
12.0

Steps to reproduce:
If you try execute method stock_inventory without inventory lines to close.

There is one logical problem in method post_inventory from https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/stock.py#L28

```python
@api.multi
    def post_inventory(self):
        acc_inventories = self.filtered(lambda inventory: inventory.accounting_date)
        for inventory in acc_inventories:
            res = super(StockInventory, inventory.with_context(force_period_date=inventory.accounting_date)).post_inventory()
        other_inventories = self - acc_inventories
        if other_inventories:
            res = super(StockInventory, other_inventories).post_inventory()
        return res
```

if variable other_inventories is false, in next line 'return res', you will get this error:

`Traceback (most recent call last):
  File "/opt/odoo/src/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/src/odoo/tools/convert.py", line 343, in _tag_function
    _eval_xml(self, rec, env)
  File "/opt/odoo/src/odoo/tools/convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "/opt/odoo/src/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/src/addons/stock/models/stock_inventory.py", line 181, in action_validate
    self._action_done()
  File "/opt/odoo/src/addons/stock/models/stock_inventory.py", line 189, in _action_done
    self.post_inventory()
  File "/opt/odoo/src/addons/stock_account/models/stock.py", line 31, in post_inventory
    return res
UnboundLocalError: local variable 'res' referenced before assignment
`

**Comment by sle-odoo** [comment]
Hi,
Can you give the steps to reproduce the issue? 
Thanks

**Comment by Swapnesh-SerpentCS** [comment]
@sle-odoo  Have a look at https://github.com/odoo/odoo/issues/29694

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by sswapnesh** [comment]
Yes @pedrobaeza

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/47727

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/pull/48733/commits/b6e77f7220a359e2bca97a66971873041d6429dc
