### ISSUE TITLE
[12.0] Calendar time chosen in FARSI language does not work

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#37551]
Impacted versions: 12.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

https://youtu.be/6Q5X91UaE-I

As you see on video, time picker on my locale language(FARSI) is not working and I can not choose hour, minute, second by clicking on it, while in English language that works correctly.
Tip: FARSI is a rtl language and number characters are different from ENGLISH.
I think it happens in other languages that their number character are different.

**Comment by bahram-css** [comment]
Do you need more information?

**Comment by pedrobaeza** [comment]
@mart-e maybe you can take a look to this

**Comment by mart-e** [comment]
Hi,

Thanks for the report but it looks like it's an issue with the upstream library tempusdominus
See https://github.com/tempusdominus/bootstrap-4/issues/320 for an example with Arabic
It should be fixed there and then we can update our library to fix it as well here.

**Comment by Mohsen1213** [comment]
I'm facing the same issue with Arabic Language. how can we solve it?

**Comment by RachidAlassir** [comment]
@mart-e FYI
@bahram-css, @Mohsen1213  I made a quick fix here [62549](https://github.com/odoo/odoo/pull/62549)
You can take these few lines until they they fix the issue in ` tempusdominus`.

**Comment by RachidAlassir** [comment]
@mart-e FYI
@bahram-css, @Mohsen1213 I made a quick fix here 62549
You can take these few lines until they fix the issue in tempusdominus.

**Comment by RachidAlassir** [comment]
@mart-e FYI
@bahram-css, @Mohsen1213 I made a quick fix here [62549](https://github.com/odoo/odoo/pull/62549)
You can take these few lines until they fix the issue in `tempusdominus`.

**Comment by RachidAlassir** [comment]
@bahram-css , @Mohsen1213  

```
.o_rtl {
    .timepicker {
        direction: rtl;
    }
}
```
Just put these lines as `assets_common`  anywhere in your codebase until they fix it.

**Comment by RachidAlassir** [comment]
@bahram-css , @Mohsen1213  

```
.o_rtl {
    .timepicker {
        direction: rtl;
    }
}
```
Just put these lines as `assets_common`  in your codebase until they fix it.
