### ISSUE TITLE
[12.0] Button style did not change after selecting other options

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#37552]
Impacted versions: 12.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/gMQZr_zj1BE

As you see on video, its not possible to return Default style for buttons after selecting other options in "Link to" window.

**Comment by pedrobaeza** [comment]
@rdeodoo any news about this?

**Comment by rdeodoo** [comment]
I couldn't reproduce the issue on this day.
