### ISSUE TITLE
bootstrap-datepicker No today button

### ISSUE THREAD

**Issue by grey27** [odoo/odoo#37556]
as far as know  fields date and fields  datetime use the bootstrap-datepicker controls,It has a parameter todayBtn: 'linked', set to show the today button, but I'm now trying this parameter doesn't seem to work.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
