### ISSUE TITLE
Display of type of operation in purchaseorder is not clear

### ISSUE THREAD

**Issue by mylbco** [odoo/odoo#3757]
http://28513-8-0-c87b9c.runbot6.odoo.com

Scenario : 

1) Goto Type of operations 
![selection_173](https://cloud.githubusercontent.com/assets/3402495/5106624/70182dfe-6ffa-11e4-9bcc-665f1be6093d.png)

2) Duplicate and change picking Type name to : Receipts Demo Material

![image](https://cloud.githubusercontent.com/assets/3402495/5106638/90e04288-6ffa-11e4-97bd-3b272cb9a450.png)

3) Goto Purchase / Request for Quotaton and CREATE

![image](https://cloud.githubusercontent.com/assets/3402495/5106665/dbef4fa8-6ffa-11e4-81a5-d3be990b761a.png)

You get 2 times the same special_shortend_wh_name, but this is 2 times the same. 

It should be possible to know with type of operation you are selecting.

**Comment by Yenthe666** [comment]
Hi @mylbco ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
