### ISSUE TITLE
 Incorrect moves when several manual moves created for delivery (chained location)

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#376]
https://bugs.launchpad.net/ocb-addons/+bug/1088412

Tested on trunk - addons rev 8266 - server rev 4644

Description:
------------
I want to setup two manuals steps for picking products and then deliver to the customer.
When I performed this setup I get two issues:
  - Internal move is generated with no Reference (INT/XXXX is missing)
  - The "Create/Invoice" can only be performed on Internal moves and not on the last move (The delivery order)
     - Internal move field "Invoice control" is set to "To be Invoiced"
     - OUT move field "Invoice control" is set to "Not Applicable""
        I expect to see "To be invoiced" on OUT move

Steps to reproduce the bug:
---------------------------

- Create a new db with demo data
- Install module:
  - Sales management
  - Warehouse
- Choose France accounting and all other options by default
- Put admin user in extended view (Technical Features")
- In warehouse configuration select:
  - Manage multiple locations and warehouses
- Go to Warehouse -> Configuration -> Location, select Output location
 - Edit chained location customer: Set "Chaining type" to "Manual operation"
- Confirm sale order SO006.
- Run schedulers
   - A new internal move is generated but with no reference. (INT/XXXX is missing)
   - A new OUT move is generated but impossible to generate invoice from this move.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
