### ISSUE TITLE
[11.0][base_automation] Access Error read when triggering a model write method  

### ISSUE THREAD

**Issue by AndersonJim** [odoo/odoo#37644]
Access Error read when write method triggers in a model with automated action.

Impacted versions:
11.0

Steps to reproduce:
- create an Automated Action for some model with trigger conditions On update or  On creation & update.

- Add to a model a code like this, where you write fields using write method.
`@api.onchange('partner_id')`
`def dummy(self):`
`....self.write({'some_field': some_value})`
 
- Then go create a new record of that model or an action that trigger the method.

Current behavior:

![error](https://user-images.githubusercontent.com/47535245/65918420-9a57ce00-e3a7-11e9-9c50-994e5285d659.png)

Expected behavior:
some_field changed without problem

Video/Screenshot link (optional):

https://drive.google.com/file/d/1B5qMuktFJY-4QhhHqI_8ZLHPEC0YPFpJ/view

**Comment by Elkasitu** [comment]
I'm pretty sure you're not supposed to call `write` inside onchanges as you may be working with a record that does not yet exist (= exists only in memory and not in the database).

You can, however, set the field in memory like so:

`self.some_field = some_value`
`self['some_field'] = some_value`
`self.update({'some_field': 'some_value'})`

`update` works in the cache exclusively so it's one of the few CRUD operations that work with "new" records

The error being shown is probably a byproduct of the api misuse, but it could be helpful to know where it comes from, can you share the full traceback?

**Comment by AndersonJim** [comment]
Now it's looks so simple, and feel kinda dumb for bother with something I was supposed to know.
Thank you for making this clear to me.

About the traceback, as it is an AccesError it only shows this message in the log:
`2019-10-01 13:42:40,100 70 INFO atrdev odoo.models: The requested operation cannot be completed due to record rules: Document type: sale.order, Operation: read, Records: <odoo.models.NewId object at 0x7f79c950bdf8>, User: 1`

When I was looking for the origin of this problem I found that the Access Error occurs right here:
[https://github.com/odoo/odoo/blob/11.0/addons/base_automation/models/base_automation.py#L229](https://github.com/odoo/odoo/blob/11.0/addons/base_automation/models/base_automation.py#L229)
when the patched _write method try to read old values from records.

**Comment by Elkasitu** [comment]
Do not worry, it's an honest mistake and one that happens quite frequently, which is why I've updated the documentation at https://github.com/odoo/odoo/pull/37665
