### ISSUE TITLE
[13] Nightly build deb packages are down since 20 september

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#37698]
While RPM, exe and tarball for version 13-alpha are all generated daily, there is no deb package since 20 september.

**Comment by d-fence** [comment]
working on it: https://github.com/odoo-dev/odoo/tree/saas-12.5-packaging-moc
Hope to finish it before 13

**Comment by sswapnesh** [comment]
Will be fixed soon in https://github.com/odoo/odoo/pull/37766

**Comment by Yenthe666** [comment]
Fix was done at https://github.com/odoo/odoo/commit/8c4c4394730bf77d44f831ca97d565bc2fb14e47
deb is also available now. See http://nightly.odoo.com/13.0/nightly/deb/
