### ISSUE TITLE
[V7.0] document_page/document_page_view.xml 

### ISSUE THREAD

**Issue by diassynthesis** [odoo/odoo#3771]
Missing <<  encoding="utf-8"  >> in document_page_view.xml

**Comment by Yenthe666** [comment]
Hi @diassynthesis,

Thank you for your report!
As this is in V7 and V7 is no longer supported (Odoo supports the latest three versions) this won't be changed or fixed anymore.
I'm closing this since V7 is no longer supported and this has been solved in newer versions.

Regards,
Yenthe
