### ISSUE TITLE
This property has still value when I delete the account statement from statement management, then I can't delete payment

### ISSUE THREAD

**Issue by Lopsanz** [odoo/odoo#37760]
https://github.com/odoo/odoo/blob/70d7f68475ac76717e832c69ec7a7dad18300ba6/addons/account/models/account_payment.py#L489
Impacted versions:
11.0

Steps to reproduce:
Settings: Allow cancel activated.
1. create and validate a payment order from invoice.
2. Break conciliation, cancel and delete from statements management.

Current behavior:
property "move_name" has still the name of deleted statement so you can't delete the payment order.

Expected behavior:
property "move_name" should be reseted or not be considered as a restriction.

**Comment by pedrobaeza** [comment]
Please indicate steps to reproduce the problem.

**Comment by Lopsanz** [comment]
Is it now right, @pedrobaeza ?

**Comment by pedrobaeza** [comment]
OK, tagged now

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
