### ISSUE TITLE
> "version_info() got an unexpected keyword argument 'jsonrpc'"

### ISSUE THREAD

**Issue by vipin9457** [odoo/odoo#37765]
> "version_info() got an unexpected keyword argument 'jsonrpc'"

Seems from external module `custom_addons/lead_extends`. and more about the deployment arch.

_Originally posted by @sswapnesh in https://github.com/odoo/odoo/issues/37758#issuecomment-537429690_

Thanks for reply .. Extended module is working fine if we refresh the page then this error is gone away..this error coming only when connection is lost...

**Comment by Yenthe666** [comment]
Please don't open new issues for a comment/feedback but reply on the chain 😉
