### ISSUE TITLE
multi-page editable treeview error when editing a row and moving to next page

### ISSUE THREAD

**Issue by mhamra** [odoo/odoo#3777]
Hi,
i have a form with a one2many field shown as an editable treeview. If i retrieve more than 80 rows, the treeview allows me to move to the next page with the arrow image on the top of the treeview.

if a click on a row of the first page, the editable treeview allows me to modify values. If i move to the next page, the record of i've clicked in the first page maintains in edition mode superposed to the new page.

If I click on a record of the second page (while record of the first page is still being edited), the web client throws an error

I'm pasting screenshots to clarify the issue.

editing record of first page
![image](https://cloud.githubusercontent.com/assets/2949519/4466341/be1c4fe6-48e3-11e4-97d1-40ae62520480.png)
moving to second page
![image](https://cloud.githubusercontent.com/assets/2949519/4466346/cae70afe-48e3-11e4-95e1-a682b2a8a3c1.png)
error thrown after clicking a record of page 2
![image](https://cloud.githubusercontent.com/assets/2949519/4466353/d5178788-48e3-11e4-8541-67109338958e.png)

**Comment by Yenthe666** [comment]
Hi @mhamra,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
