### ISSUE TITLE
 Useless duplicates origin when merging purchase orders

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#378]
https://bugs.launchpad.net/ocb-addons/+bug/1091268

When merging multiple purchase orders from wizard, origin field is concatenated even if the origin is the same:
eg: :MO/00005 :MO/00005 :MO/00005 :MO/00005 :MO/00003 :MO/00003 :MO/00003

It should be avoided, at least because the origin field is limited to 64 chars. I'm attaching a patch to fix this

if porder.origin and not porder.origin in order_infos['origin'] : # Do not add duplicates origin, totally useless
   order_infos['origin'] = (order_infos['origin'] or '') + ' ' + porder.origin

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
