### ISSUE TITLE
Picking list is not translated

### ISSUE THREAD

**Issue by nafex** [odoo/odoo#3782]
**Picking list is not translated**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

- print picking list

Current behavior:

 - picking list is not translated

Expected behavior:

 - should be translated

**Comment by mlaitinen** [comment]
It is translated. `translate_doc` is only needed if you want to translate the document to language other than current user's.

IMHO this is not a bug and this issue (+PR) should be closed. You should check your browser cache, because I think I've seen the situation in which this occurs.
