### ISSUE TITLE
[13.0] Export All : Only Visible Records should be Exported

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#37849]
Impacted versions: 13.0

Steps to reproduce: Export Meetings (14  Records are there)
![Screenshot from 2019-10-03 08-23-47](https://user-images.githubusercontent.com/16624719/66096022-360b5900-e5b7-11e9-9a86-2e1f093a0ae4.png)

Current behavior: Extra Records are also Exported which is not on the List view  
19 Rows in the xls
![Screenshot from 2019-10-03 08-10-23](https://user-images.githubusercontent.com/16624719/66096053-55a28180-e5b7-11e9-8e80-389ac1714e3c.png)

Expected behavior: Only visible records should be there on List
 
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Not sure if this is only for calendar.event

**Comment by celm1990** [comment]
Only selected records must be exported, similar to [web_export_view](https://github.com/OCA/web/tree/12.0/web_export_view)

**Comment by LucasLefevre** [comment]
Hello @sswapnesh 
I'm confused. The first screenshot shows the calendar.event list, but the export screenshot shows res.partner. Wrong screenshot ?

And I'm not able to reproduce it on runbot.
Also, please note that one record might take several rows in the exported file if there are multiple attendees.

**Comment by sswapnesh** [comment]
I am also confused now looking at the screenshots 😂.
I will check this in detail and get back to you   in the next week.

**Comment by sswapnesh** [comment]
> Also, please note that one record might take several rows in the exported file if there are multiple attendees.

I was not aware of that, do we have these type of Special use case only for the calendar?
(I have checked and you are right, Number of Rows were dependent on attendees)

**Comment by sswapnesh** [comment]
@LucasLefevre  You were Right
Thanks
