### ISSUE TITLE
[13.0] Could not Create Channel Moderation

### ISSUE THREAD

**Issue by sunnydenero** [odoo/odoo#37858]
Impacted versions: **13.0**

Steps to reproduce: 
--> **Activate Developer Mode**

-->  Go to **Settings** > **Techinal** > **Channel Moderation** > Create New Record and Enter Data appropriately > after that try to save record / data.

Current behavior:

![screenshot-639263-13-0-7e0ed8 runbot22 odoo com-2019 10 03-14_23_11](https://user-images.githubusercontent.com/40389535/66112947-69ff7200-e5e9-11e9-8816-70af2d1de5bf.png)

**Traceback**

![screenshot-639263-13-0-7e0ed8 runbot22 odoo com-2019 10 03-14_24_19](https://user-images.githubusercontent.com/40389535/66112993-83082300-e5e9-11e9-9926-f8862dc09df6.png)

Expected behavior:
**Record should be Created Successfully**

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The problem is the channel you are adding seems to be not moderated.

**Comment by Yenthe666** [comment]
I believe @mart-e once said this was by design and not considered a bug. @mart-e can you confirm?

**Comment by mart-e** [comment]
I don't recall saying that but the past-me was right. Only users in the list of moderators can create moderation records (and, as explained by Pedro, if the channel has no moderator, nobody can create moderation records).
So no bugs.

**Comment by sunnydenero** [comment]
@mart-e @pedrobaeza @Yenthe666 
Thanks to all.
