### ISSUE TITLE
[13.0] Export All: Columns name should respect string attribute from List view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#37851]
Impacted versions: 13.0

Steps to reproduce: Add string on the List view
Eg, Default Sales Order list view
`<field name="name" string="Quotation Number" readonly="1"/>`
![Screenshot (1)](https://user-images.githubusercontent.com/16624719/66096681-72d84f80-e5b9-11e9-8bee-8690c9c7aad7.png)

Current behavior: Export All
![Screenshot from 2019-10-03 08-40-40](https://user-images.githubusercontent.com/16624719/66096703-8683b600-e5b9-11e9-87c4-69a41a593106.png)

Expected behavior: Same Column names

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Related One: ( or Maybe its good to create new Issue for that)
Sum is not Exported to xls (sum/avg attribute)
![Screenshot (2)](https://user-images.githubusercontent.com/16624719/66096926-2e00e880-e5ba-11e9-9570-db5d37452812.png)

![Screenshot from 2019-10-03 08-45-54](https://user-images.githubusercontent.com/16624719/66096943-3bb66e00-e5ba-11e9-8535-506bba3b02f7.png)

**Comment by msh-odoo** [comment]
@sswapnesh the headers given here are used to match columns while importing(column matching are based on ir.fields string), I am not sure this should be considered as bug, what do you think @mart-e ?

**Comment by sswapnesh** [comment]
Maybe as a Wishlist

**Comment by mart-e** [comment]
The header in the export and in the view are two different things. An export is not linked to the list view used (only to the model) so it should not influence the exported file.
I don't think it is a good idea that two exports made from different views return a different result.

**Comment by sswapnesh** [comment]
IMO it should respect the Labels which are present on Current view.
If Two views are different than Results ( Columns) should be different.

**Comment by mart-e** [comment]
I disagree on that, the export is and should be based on the records, not the current layout.
