### ISSUE TITLE
[8.0] Delivery method update traceback

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#3785]
Steps to reproduce

Create a delivery method in the UI. Press Save.
Edit the record. Change any field. Press Save.

014-11-20 20:05:01,047 17815 ERROR development openerp.sql_db: bad query: INSERT INTO "delivery_grid_line" ("id", "list_price", "name", "sequence", "price_type", "max_value", "standard_price", "grid_id", "variable_factor", "operator", "type", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('delivery_grid_line_id_seq'), 0.0, 'Default price', 10, 'fixed', 0.0, 0.0, 33, 'weight', '>=', 'price', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/usr/local/openerp/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "delivery_grid_line" violates foreign key constraint "delivery_grid_line_grid_id_fkey"
DETAIL:  Key (grid_id)=(33) is not present in table "delivery_grid".

There is an override in write() method causing this bug

**Comment by nim-odoo** [comment]
Fixed in dd23586e16f8938f4fac6a73978e8771e3804198
