### ISSUE TITLE
mass_mailing module is broken in v. 13

### ISSUE THREAD

**Issue by gitsponge** [odoo/odoo#37852]
Impacted versions:

13.0

Steps to reproduce:

Install mass_mailing and click on Email Marketing

Current behavior:

KeyError: 'mailing.mailing'

Expected behavior:

Should work

Video/Screenshot link (optional):

![Screenshot from 2019-10-03 00-15-05](https://user-images.githubusercontent.com/655918/66098997-e3a84900-e572-11e9-8fd5-a46709cbd65a.png)

**Comment by pedrobaeza** [comment]
Have you tried on runbot?

**Comment by Yenthe666** [comment]
It seems to work just fine on the latest 13.0 runbot. Even after deinstalling and reinstalling the app.

**Comment by pedrobaeza** [comment]
Closing then.

**Comment by sswapnesh** [comment]
I am gonna Re-install most of the Apps.( Like I did last year)😃

**Comment by Yenthe666** [comment]
There we go again.. ;)
