### ISSUE TITLE
Serial number tracking for products at POS level?

### ISSUE THREAD

**Issue by pifiu** [odoo/odoo#3789]
Version 8.0 and lower.

Steps to reproduce: None, feature not supported.

We sell products via retail that have unique serial numbers for each unit from the manufacture. It doesn't seem like Odoo POS is able to sell + scan, lookup or assign the serial number being sold to the customer. It would also be ideal to display the sold serial number on the POS receipt under the line item.

This is important to us in order to track returns, warranty and suppliers for claims. What would we need to do to track the seral numbers sold to each customer?

Are there any plans to implement this soon? It seems so fundamental for many businesses.

**Comment by Yenthe666** [comment]
Hi @pifiu ,

Thank you for your bug report (suggestion) and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
I will label it wishlist so it keeps popping up, even after being closed.

Regards,
Yenthe
