### ISSUE TITLE
Correctly compute taxes in round_per_line / round_globally behavior for invoice with ONE line

### ISSUE THREAD

**Issue by SimoRubi** [odoo/odoo#37896]
(from https://github.com/odoo/odoo/pull/28788 )
**Impacted versions**
13.0

**Steps to reproduce**

0. Activate debug mode;
1. In Accounting > Configuration > Settings, set rounding method "Globally";
2. Create an invoice with unit_price = 348.35, 16 pieces, 4% discount, 22% tax;
3. Check that total is 6527.80.
4. In Accounting > Configuration > Settings, set rounding method "Per line";
5. Create an invoice with unit_price = 348.35, 16 pieces, 4% discount, 22% tax;
6. Check that total is 6527.81.

**Current behavior**
Totals in step 3 and 6 are different.

**Desired behavior**
Totals in step 3 and 6 are the same (6527.81).

**Comment by Yenthe666** [comment]
@qdp-odoo for you guys!

**Comment by SimoRubi** [comment]
Hi, any news on this one? Thanks!

**Comment by GSLabIt** [comment]
@qdp-odoo any chance to double check? It seems to happen on v 12.0 as well.

Could https://github.com/odoo/odoo/issues/41511  be related to this?

**Comment by SimoRubi** [comment]
Hi, any news on this one? Thanks!

**Comment by GSLabIt** [comment]
@SimoRubi https://twitter.com/fpodoo/status/1229213042002391040?s=19

**Comment by pedrobaeza** [comment]
I suppose this can be closed due to the answer in Twitter?

**Comment by SimoRubi** [comment]
@pedrobaeza I can't link this issue with the answers in Twitter: should this be closed because of 'when to round' or 'decimal vs float' or 'choice by design'?

I still can't see how what I described can be the expected behavior.

**Comment by qdp-odoo** [comment]
It's normal to have different results if you compute things differently: that's precisely the whole purpose of rounding per line or globally.

**Comment by GSLabIt** [comment]
@qdp-odoo wow ..big thx for lighting it up .. 👍

**Comment by qdp-odoo** [comment]
I supose I need to clarify: 

> if you select 'Round per line' : for each tax, the tax amount will first be computed and rounded for each PO/SO/invoice line and then those rounded amounts will be summed, leading to the total amount for that tax. 
> If you select 'Round globally': for each tax, the tax amount will be computed for each PO/SO/invoice line, then these amounts will be summed and eventually this total tax amount will be rounded. 

so making a sum of rounded values or a sum of unrounded values can make a slight difference sometimes, that  _IS_ the purpose of the field. Some countries needs one method or the other, that's the reason we have both.

**Comment by GSLabIt** [comment]
@qdp-odoo thanks for the explanation. As far as i could double check, there are a couple of problems over this:

1. the precision used to compute line subtotal: it's set as the currency precision (2 decimals for €), that's a problem when user will set `Price Precision` > 2. In this case you're a going to loose decimal precision before rounding it. 
_IMHO, precision should be in any case at least Product Price precision._ 

2. `amount_subtotal`, `amount_total`, and all other signed fields, are set as `Monetary` field so it will loose precision even if setting `Round globally`. 
_IMHO, better use `Float` field, and monetary widget._

At the end of the day, actually, in both cases: `Round per line`, `Round globally`, you're going to loose precision and computation get wrong values. 

You can double check by yourself:  https://github.com/odoo/odoo/issues/41511

**Comment by SimoRubi** [comment]
@GSLabIt that is not what I wanted to point out in this issue, the problem I describe should not depend on the precision used.

> I supose I need to clarify:
> 
> > if you select 'Round per line' : for each tax, the tax amount will first be computed and rounded for each PO/SO/invoice line and then those rounded amounts will be summed, leading to the total amount for that tax.
> > If you select 'Round globally': for each tax, the tax amount will be computed for each PO/SO/invoice line, then these amounts will be summed and eventually this total tax amount will be rounded.
> 
> so making a sum of rounded values or a sum of unrounded values can make a slight difference sometimes, that _IS_ the purpose of the field. Some countries needs one method or the other, that's the reason we have both.

Thanks for the detailed explanation, I understand that the following results can be different:

- (round per line) = round(tax_line_1) + round(tax_line_2) + ... + round(tax_line_N)
- (round globally) = round(tax_line_1 + tax_line_2 + ... + tax_line_N)

That is absolutely correct.

Anyway the steps I describe in this particular issue lead to the creation of an invoice that only has **one line**, so I expect both methods to return the same result because the procedure as you describe it should be (same as above, with N = 1):

- (round per line) = round(tax_line_1)
- (round globally) = round(tax_line_1)

But these two values are not the same in the created invoice; could you please re-open the issue and help me understand why these results should be different in Odoo?

**Comment by GSLabIt** [comment]
@SimoRubi problem in your case is due to the precision used to calculate tax. 

round per line: precision 2 
round globally: precision 7

So, you'll fall back to this:
> 1. the precision used to compute line subtotal: it's set as the currency precision (2 decimals for €), that's a problem when user will set `Price Precision` > 2 or computation will need more than 2 decimal precision. In this case you're a going to loose decimal precision before rounding it.

**Comment by SimoRubi** [comment]
@GSLabIt, in the explanation https://github.com/odoo/odoo/issues/37896#issuecomment-630034539 there is no mention about different precisions used in the different methods.

I'm trying to understand precisely what's the Odoo's idea behind this, in my opinion, strange behavior: an invoice with **one line** returns different results based on the method used.

I'm trying not to look at how it is implemented (different rounding/precisions/other), and would like to know if the **current behavior** in the description matches Odoo's idea of how this works, and why.

**Comment by GSLabIt** [comment]
@SimoRubi good luck ..

**Comment by SimoRubi** [comment]
@qdp-odoo could you please explain where is the flaw in the reasoning I explained in https://github.com/odoo/odoo/issues/37896#issuecomment-630640367?
Thanks!

**Comment by SimoRubi** [comment]
@qdp-odoo could you please re-open?
I've changed the description to stress the fact that the error happens for invoices with only one line, and I think it is pretty straight-forward that `round_globally` and `round_per_line` should behave the same (see https://github.com/odoo/odoo/issues/37896#issuecomment-630640367 for a more detailed explanation).

**Comment by qdp-odoo** [comment]
mmh ok, that indeed seems dubious. We'll check that :+1:

**Comment by smetl** [comment]
@nim-odoo This issue has already been fixed in saas-13.2 at revision:
https://github.com/odoo/odoo/commit/eec0b80756557ecd543a50f25b8f63f94e23de7c

However, you disagreed to merge it directly in saas-12.3 to avoid any trouble in stable version like POS closing entries. This is the reason why you made this instead:
https://github.com/odoo/odoo/commit/8982bef6e55d6878ff1a33135441c4e94461c047

What do you think we should do now?

**Comment by SimoRubi** [comment]
Hi, any update on this? Thanks

**Comment by smetl** [comment]
@nim-odoo Can you have a look plz?

**Comment by SimoRubi** [comment]
Hi, any update on this?
Thanks!

**Comment by nim-odoo** [comment]
> Hi, any update on this?
> Thanks!

It was fixed from 13.0 in https://github.com/odoo/odoo/commit/32d47d32c62abade2d27ffa231940811771566b7. That was a clear change of behavior, but it was decided to be merged in 13.0 nevertheless.

A minimal diff in 12.0 would probably be https://gist.github.com/nim-odoo/22895f9ff9cb933578b58b888300b43f

**Comment by SimoRubi** [comment]
Verified in runbot CE v13, thanks!
