### ISSUE TITLE
Add ability to dynamically resize tiles in My Dashboard view

### ISSUE THREAD

**Issue by jpwarren** [odoo/odoo#3790]
Rather than having fixed spaces for dashboard items, it would be nice to be able to dynamically grab the tiles and resize them, as you can with windows on any modern windowing desktop.

Then a user could design their own dashboard layout, and resize the tiles to suit the way they want to look at the information.

Right now, the interface is somewhat restrictive.

**Comment by Yenthe666** [comment]
Hi @jpwarren,

Thank you for your suggestion (and sorry for the delay in the response).
I've labelled this wishlist so that it'll come up when the R&D team checks this.
No promisses though!

Regards,
Yenthe
