### ISSUE TITLE
[13.0] change tree fields is global not user dependent

### ISSUE THREAD

**Issue by lreficent** [odoo/odoo#37916]
Impacted versions: 13.0

Steps to reproduce:
change any tree view fields to display and log as another user.

Current behavior:
fields displayed in the tree view also changed for the second user.

Expected behavior:
Fields selected by one user does not modify other user's tree view.

Video/Screenshot link (optional):
![tree-view-fields-issue](https://user-images.githubusercontent.com/23449160/66143410-6b3f9780-e607-11e9-85a6-8b0b0038eacd.gif)

@Eficent

**Comment by sswapnesh** [comment]
> Fields selected by one user does not modify other user's tree view.

Not sure if this can be done in the current Arch.
(I remember this has been discussed to keep as it is, Couldn't find the reference now)

**Comment by pedrobaeza** [comment]
Well, that seems a big usability problem, as any user switching the columns in the view will make the others to also change, so imagine in a medium system with hundred of users what can be the impact.

**Comment by msh-odoo** [comment]
@sswapnesh @pedrobaeza optional fields are stored locally in localstorage, and key generated depends on fields that user can access, model, view type, if you are logging different users on same system then it will normally happen because different user have different roles and access, so view architecture maybe different for each user.

**Comment by pedrobaeza** [comment]
Oh, thanks for the clarification. Then I think it's enough with that, as it's not usual that several users connect through the same system.

**Comment by Yenthe666** [comment]
@lreficent can you check if all is well for you after the response from @msh-odoo?

**Comment by lreficent** [comment]
I tested with 2 different browsers and it worked good now, thanks for the clarification.
