### ISSUE TITLE
[8.0] binary file name download extension not working

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#3792]
View

```
<field name="name" invisible="1" />
<field name="label_image" filename="name" readonly="1"/>
```

Model
'name': fields.char('Name', readonly=True),
'label_image': fields.binary('Label Image', readonly=True),

I have tried this with a wizard or just a form view. When the view appears, the link to download appears correctly, and the filename appears correctly, but when you click to download the file it does not have the correct extension. just the model name_id. The file format is a .gif. 

I have reviewed several examples, and am convinced my code is correct and that there is a bug.

Please confirm

**Comment by mapeal2** [comment]
@aliomattux 
I've tried this as well and the file gets downloaded in the original format but not with the original file name, as in your case. This happens with Chrome, but when I use Firefox (version 35.0) the file gets downloaded just in binary format (.bin). Have you tried Firefox?

**Comment by aliomattux** [comment]
Yes,
I usually only use firefox. I do not know why this does not work, its very frustrating, and especially to get no response from Odoo on any issue I file. They must be busy. I already created a workaround to the issue by returning a report containing an image instead of trying to use the Binary file

**Comment by Yenthe666** [comment]
Hi @aliomattux ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
