### ISSUE TITLE
[12.0, 13.0] New "server is busy" constraint is too hard to debug 

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#37962]
#### Impacted versions:
12.0, 13.0
#### Steps to reproduce:
Have a **busy** multi-tenant environment

#### Current behavior:
Always getting the message:
https://github.com/odoo/odoo/blob/9d0f172f29085a6b164313bf20178270b9572cc2/odoo/addons/base/models/ir_module.py#L567

#### Expected behavior:
Show the name of the cron which is hanging the server and/or allow to forcibly stop the actual cron.

cc: @Elkasitu @rco-odoo

**Comment by Elkasitu** [comment]
How can we know which `ir.cron` is blocking if the table is locked?

**Comment by gustavovalverde** [comment]
As far as I'm concern just doing a query to the database can give you this information. But most of Odoo users don't have access to it.

Let's say we know which `ir.cron` is blocking the table (Cron A), but we need to update another module and we don't know when Cron A will finish its execution (this is a harder information to get).

Based on the information at hand, the user won't be able to know when the server **will be available**, even though he knows which cron is making it busy. 

When approaching this problem, there should also be a way to override the current cron to allow to execute the update.

**Comment by gustavovalverde** [comment]
@Elkasitu  related information on what's locking a table (behold): https://wiki.postgresql.org/wiki/Lock_Monitoring

**Comment by Elkasitu** [comment]
> As far as I'm concern just doing a query to the database can give you this information.

Except if it's already been locked, which is exactly what triggers the message in the first place

> Let's say we know which ir.cron is blocking the table (Cron A), but we need to update another module and we don't know when Cron A will finish its execution **(this is a harder information to get)**.

If by hard you mean [impossible](https://en.wikipedia.org/wiki/Halting_problem) then yes, and we don't know which cron is blocking (programmatically), see point above.

I tried playing around with Lock Monitoring but it doesn't give any meaningful information, mostly which table is currently locked, which local user triggered it and how long has it been locked for which would be useful if we didn't have timeouts already.

I suggest you look at your server logs, find the error and then work backwards to see which was the last cron executed, but I am open to suggestions to improve this limitation.

**Comment by gustavovalverde** [comment]
I'm kind of lost on which information I should be looking for in the server logs. Is there something in the logs that tells me when a cron started, when it finished and how long it took to execute?

That information would help me to identify the culprit.

**Comment by gustavovalverde** [comment]
@Elkasitu by trial & error I got this message trying to archive a Cron: https://github.com/odoo/odoo/blob/9d0f172f29085a6b164313bf20178270b9572cc2/odoo/addons/base/models/ir_cron.py#L290

And basically, from one of the databases, it was the cron causing the permanent lock on updates and other activities.

This somehow tells me that it is possible to programmatically identify the cron causing the deadlock

**Comment by Elkasitu** [comment]
When a cron is executed, you get a message in the log like so:

```
2019-10-08 06:24:05,458 70606 INFO cronlock odoo.addons.base.ir.ir_cron: Starting job `lock the cron table`.
```

To find the culprit all you have to do is either grep the logs or use a log handler such as `odoo.addons.base.ir.ir_cron:INFO`, then see which was the last cron to be executed before the error message.

> This somehow tells me that it is possible to programmatically identify the cron causing the deadlock

In this case you can because the `ir.cron` causing the deadlock is `self`, in the case of an install/uninstall/upgrade `self` is the module being operated on and you cannot query the `ir_cron` table because it's locked.

**Comment by nilshamerlinck** [comment]
As an alternative to checking the logs, you could execute a query such as `SELECT query FROM pg_stat_activity WHERE pid IN (SELECT l.pid FROM pg_locks l JOIN pg_class c ON (relation=c.oid) WHERE c.relname = 'ir_cron' AND l.mode = 'RowShareLock');` to get the id(s) of the running `ir.cron`

**Comment by mart-e** [comment]
Closing as given workaround and as we are not going to modify the constraint.
