### ISSUE TITLE
The list view of column headings are not placed parallelly, correctly when the window size is minimized or user has a small computer screen

### ISSUE THREAD

**Issue by ztsiklauri** [odoo/odoo#3797]
**The list view of column headings are not placed parallelly, correctly when the window size is minimized or user has a small computer screen**

Impacted versions:
- 7.0 and above

Steps to reproduce:
1. Open any list view with multiple columns.
2. Minimize the window to some extent 
3. then gradually decrease/increase and you'll see):

![1](https://cloud.githubusercontent.com/assets/9009384/5141910/21209cd0-7195-11e4-9df7-d8e736b2f27d.png)

Current behavior:
- Column headings aren't aligned to each other, are not in one line across each other.

Expected behavior:
- No matter the size of the window, the column headings should be across each other.

_**Note:**_ This problem is not occurring only because of window minimisation: If the size of the computer screen is small, then this problem is reproduced again.

**Comment by Yenthe666** [comment]
Hi @ztsiklauri ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As Odoo 8 and up have a new interface this shouldn't ever come up again.

Regards,
Yenthe
