### ISSUE TITLE
[13.0] Cannot change contact to Customer or Vendor

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#37991]
Impacted versions: 13

Steps to reproduce:
Create a new person or company in the Contact application, go to the "Sales" or "Purchase" application and you are not able to see the created contact. Standard there is the filter "Customer" active for Sales and "Vendor" under Purchase application.

In Version 12, you were able to select "Customer" or "Supplier" under the Sales / Purchase tab of a customer. This made it possible to select if a customer is either a customer or a vendor. 

Current behavior:
We are no longer able to select if a contact is a "customer" or a "vendor" (see screenshot).

Expected behavior:
Ability to use a contact as both a vendor and a supplier, also being able to change or extend the use of a contact from only either vendor or supplier to both.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/39414107/66225079-d8226280-e6d7-11e9-9266-e3d57243b89b.png)

**Comment by Yenthe666** [comment]
This was implemented and done by design. By default your contact is available everywhere and can be used as you wish. It's not a bug.

**Comment by BusinessAgilityMasters** [comment]
> This was implemented and done by design. By default your contact is available everywhere and can be used as you wish. It's not a bug.

So how to make a contact be visible for both filters so with the Supplier and Vendor filter active? 

Cannot create 2 seperate contacts, this makes it impossible to select the correct one when creating a "Sales Order" or "Purchase Order" as we now get to see both contacts.

**Comment by sswapnesh** [comment]
@BusinessAgilityMasters 
>*Found out a Contact becomes a "customer" or "supplier" when it is has been invoiced from the related application.

See https://github.com/odoo/odoo/commit/8766f388 and https://github.com/odoo/odoo/commit/8b7f42ab for more details
```
<filter string="Customers" name="customer" domain="[('customer_rank','>', 0)]"/>
<filter string="Vendors" name="supplier" domain="[('supplier_rank','>', 0)]"/>
```
