### ISSUE TITLE
[13.0] Image not proper display in Contacts & Addresses Form View.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#37999]
**Impacted versions:** 
   
1. Odoo 13.0

**Current behaviour:**
1)  Proper Image not display 
![Kapil Patel - Odoo1](https://user-images.githubusercontent.com/24518821/66251279-36992080-e76c-11e9-8459-fa45eb714bca.png)

**Expected behaviour:**
Image should be display in Contacts & Addresses form view.
![Selection_018](https://user-images.githubusercontent.com/24518821/66251589-5e3db800-e76f-11e9-93f3-bfcc8c98c42b.png)

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/24518821/66251267-123d4400-e76c-11e9-8cf7-9a332864aacf.gif)

**Comment by Yenthe666** [comment]
I've reproduced the issue. @mart-e can you check please?

**Comment by mart-e** [comment]
@seb-odoo can you have a look? Isn't it linked to your changes with `image_<size>` fields?

**Comment by seb-odoo** [comment]
It is more than likely linked to my changes, I would say if I removed the image_128 field from the kanban definition to use the url route (to benefit from cache) maybe it is not able to link it to the parent image anymore, or something like that. I'll check in more details.

**Comment by seb-odoo** [comment]
Fix in https://github.com/odoo/odoo/pull/38108
