### ISSUE TITLE
POS Order bar not perfectly work

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#37993]
Impacted versions:
13.0, 12.0

Steps to reproduce:
1. Start new or resume session
2. Added orders using **plus** in pos order screen.

Current behavior:
WiFi icon and cashier name are overlap in a screen.

Expected behavior:
WiFi icon and cashier name are not overlap in a screen.

Video/Screenshot link (optional):
12.0 

![21](https://user-images.githubusercontent.com/29298578/66232948-b93bc480-e707-11e9-903b-779b43bdfbe0.png)

13.0
![2](https://user-images.githubusercontent.com/29298578/66232958-c0fb6900-e707-11e9-8503-098a772e9e22.png)

**Comment by Yenthe666** [comment]
@switch87 perhaps an improvement for you to do.

**Comment by switch87** [comment]
@Yenthe666 thanks for tagging me!

**Comment by Yenthe666** [comment]
You're welcome ;)

**Comment by switch87** [comment]
@ammarofficewla For the v12 problem, there is a scrollbar underneath the tabs to see the buttons and icons. I see it is there in your screen shot. I guess you are using Google Chrome, in this browser scrollbars are very small.

**Comment by ammarofficewla** [comment]
@switch87 for v12 you are right but we can do only scrollbar for order not all panel .

**Comment by mart-e** [comment]
Looks like it was fixed in 13.0 at #38227
