### ISSUE TITLE
[13.0 C] E-learning app : Traceback on group by and Export.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#37998]
Impacted versions: Odoo 13.0 C

Steps to reproduce:

- Go to **E-learning** app
- Group by : Add custom group like e.g **Course Ranked**. and Apply
- Click on '**Export All**' Button.

Current behavior:
      - Producing Traceback

Expected behavior:
      - It should export data.

Video/Screenshot link (optional):
[https://nimb.ws/PQWXs7](https://nimb.ws/PQWXs7
)

Just for ref. i checked and verified on 2 Runbot instance :

[http://641118-13-0-b1d5dd.runbot21.odoo.com/web?#action=865&model=slide.channel&view_type=list&cids=1&menu_id=625](http://641118-13-0-b1d5dd.runbot21.odoo.com/web?#action=865&model=slide.channel&view_type=list&cids=1&menu_id=625)

[http://640993-13-0-a0605e.runbot19.odoo.com/web#action=865&model=slide.channel&view_type=list&cids=&menu_id=625](http://640993-13-0-a0605e.runbot19.odoo.com/web#action=865&model=slide.channel&view_type=list&cids=&menu_id=625)

**Comment by Yenthe666** [comment]
Reproduced:
![image](https://user-images.githubusercontent.com/6352350/66251611-4efc4180-e752-11e9-80c0-b61c52c00b48.png)
@mart-e who is responsible for e-learning? Can you add the new apps to the wiki at https://github.com/odoo/odoo/wiki/BugManagement please?

**Comment by sswapnesh** [comment]
@Yenthe666  This seems related to the "Export All" feature not `e-learning` app, as It happens when Grouping by Any Integer field and Export.

**Comment by sswapnesh** [comment]
@dipsshah42  Added fix at #38007 
http://runbot.odoo.com/runbot/build/641387

**Comment by sswapnesh** [comment]
>  Can you add the new apps to the wiki at https://github.com/odoo/odoo/wiki/BugManagement please?

and also this https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch

**Comment by Feyensv** [comment]
I updated the wiki pages to the extent of my knowledge ;). Do not hesitate to ping me for Wiki related problems.

**Comment by sswapnesh** [comment]
@Feyensv  This is still referring to 12.0

`<li><a href="https://www.odoo.com/documentation/12.0/" rel="nofollow">Technical Documentation</a></li>
` 


![Screenshot (18)](https://user-images.githubusercontent.com/16624719/67148159-dd77d380-f2b9-11e9-81fd-b1feba431cab.png)

**Comment by Feyensv** [comment]
Fixed by martin 4h ago (I was a tad late :D). Ty
