### ISSUE TITLE
Chrome rendering: rendering issue in status widget (form header)

### ISSUE THREAD

**Issue by dbo-odoo** [odoo/odoo#3799]
Impacted versions:

 - master on Chrome 39 in Ubuntu (checked Firefox and Opera: problem does not appear).

Steps to reproduce:

 On master, install Manufacturing (for example) and go in the form view a stock move. The status bar (new > waiting availability > available > done) is faulty.

Current behavior:

 - Status bar break alignment
![screenshot from 2014-11-21 14 08 48](https://cloud.githubusercontent.com/assets/9530767/5142781/f4aab2b0-7187-11e4-9a62-d8e685a7c2fe.png)

Expected behavior:

 - Status bar is float:right in header

**Comment by wangyueming** [comment]
Yes, I have the same issue.

**Comment by wangyueming** [comment]
Please see https://github.com/odoo/odoo/commit/a8943b416a892c4da76aa0887886622e525db8b8
