### ISSUE TITLE
 "Default debit / credit account" fields on the journal form view are not visible without horizontal scrolling

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#380]
https://bugs.launchpad.net/ocb-addons/+bug/1100427

On the live demo at openerp.com, get to the form to edit or view a journal. The two fields, "Default Debit Account" and "Default Credit Account" are on the page, but to the right of the area normally visible. I've attached a screenshot.

Not sure if this is a problem in openerp-web or openobject-addons.

Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:18.0) Gecko/20100101 Firefox/18.0

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
