### ISSUE TITLE
[12.0] Fiscal positions not working correctly in Point of sale (PoS) , odoo 12.0 

### ISSUE THREAD

**Issue by RodmanII** [odoo/odoo#38005]
Impacted versions: 12.0

Steps to reproduce: 

1. in https://demo2.odoo.com, and also in runbot http://641003-12-0-1b8acd.runbot11.odoo.com database all, and of course in my local development environment.
2. ​I defined two taxes, one as 13% of price, not included in price, and another one as 1% of price not included in price. 
3. Then I defined a fiscal position where 13%, will be replaced by 13% and 1%, to apply both taxes.
4. Then I created several products with default tax 13% and make them available in the pos, I leave everything else to its default value. 
5. In the Point of Sale Configuration I configured Fiscal Position per Order and selected the previously created fiscal position
6. ​Tax excluded prices and cash as only payment method. Also selected invoicing
7. ​Then I resumed the sale in the PoS I configured those options in.
8. I sell two products, one unit each, with prices of 25 and 20. the total was 50.85, the result of applying only 13% tax, yet the fiscal position was selected. The pos ticket showed the same but the invoice has the correct values. 
9. The pos sale in the backend shows both taxes but the amounts are still wrong.
Testing in http://640993-13-0-a0605e.runbot19.odoo.com, a runbot of 13.0 version, I noticed the opposite, the taxes are correct in pos sale, but not in the invoice.

Current behavior: 
The amount total of the pos sale is not consistent with the taxes in the fiscal position, if you review the sale in the backend the line has the two taxes but the total only includes the default tax of the product, but the invoice from the sale has the correct values.

Expected behavior:
Total amount of pos sale includes all taxes of the fiscal position, and is equal to the values from the invoice.

Video/Screenshot link (optional):
The same description is in this file but with images:
https://1drv.ms/w/s!AsYPCrqa-LtmjFDEiYD00eObbRZs?e=HrXbWu

**Comment by pedrobaeza** [comment]
Support for several target taxes was added on v13 on a19eb47, so this is something expected. If you want it in previous versions, you can try to backport it. We did that in OCA/OCB in #822 for 11.0, and probably we will do it for 12.0 as well.

Any way, closing as it's a missing feature that has been added in 13.0.
