### ISSUE TITLE
[13.0]In Partner Kanban and Form views default image not set.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38001]
**Impacted versions:**
Odoo 13
**Steps to reproduce:**
     1) Create Partner/Customer without selecting Profile image
     2) After Creating Partner go back to kanban check image 
**Current behaviour:**
      1) Create Partner/Customer without selecting Profile image
![Patel Brothers - Odoo](https://user-images.githubusercontent.com/24518821/66252422-19b71a00-e779-11e9-8a37-6fa76e9cc4cf.png)
      2) In Kanban view default image not display
![Selection_023](https://user-images.githubusercontent.com/24518821/66252521-7109ba00-e77a-11e9-96bf-8bfb59877bfe.png)
 
**Expected behaviour:**
     1) It can be set default Image when we not selecting any profile image in form view(So It looks pretty from view and kanban view)
 
![Selection_020](https://user-images.githubusercontent.com/24518821/66252328-e758ed00-e777-11e9-955b-6cd26811819d.png)

![Selection_022](https://user-images.githubusercontent.com/24518821/66252600-2f2d4380-e77b-11e9-8c91-65659f6134fb.png)

**Video/Screenshot link (optional):**
![Peek 2019-10-05 13-49](https://user-images.githubusercontent.com/24518821/66252638-63086900-e77b-11e9-9817-8f230edc3fef.gif)

**Comment by pedrobaeza** [comment]
This might be a design decision for avoiding extra burden of non representative images.

**Comment by seb-odoo** [comment]
Thanks for the report, I'll have a look.

It wasn't intentional, we did indeed remove the default image from the database (so we can actually differentiate between partners with and without image, and we don't have to store a default image millions of time for no reason) but there is supposed to be a placeholder instead.

**Comment by i-vyshnevska** [comment]
@seb-odoo  seems default image still not available for form view

**Comment by seb-odoo** [comment]
@i-vyshnevska 
You'll need to manually update the view that was changed by the commit if you want the fix.

To avoid breaking customization with bugfix we can't automatically reset the views that are in database.

**Comment by seb-odoo** [comment]
I don't think we want the placeholder on the form view, as the layout there is not depending on it.
