### ISSUE TITLE
[13.0] Creating first invoice is too complicated, require additional configuration

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#38004]
**Impacted versions:**

13

**Steps to reproduce:**

1. Create new database, my country setting is Poland
2. Install invoicing module
3. Try to create new invoice with products
4. "If you want to use "Off-Balance Sheet" accounts, all the accounts of the journal entry must be of this type"
5. ???

**Current behavior:**

Creating invoice require some kind of additional configuration

**Expected behavior:**

Simply create invoice like in previous odoo versions, no additional accounts configuration required

**Comment by pedrobaeza** [comment]
This seems a problem of Poland localization, not accounting itself. Can you please try with other chart of accounts to see?

**Comment by grzekru** [comment]
Yes I don't see this problem on other accounting

W dniu sob., 5.10.2019 o 17:03 Pedro M. Baeza <notifications@github.com>
napisał(a):

**Comment by pedrobaeza** [comment]
Great, then we have delimited the scope of this. I'm going to properly tag this for working on that specific part.

@jco-odoo for your interest.

**Comment by kharkot** [comment]
Hi Gents,

Indeed , the problem with with the definition of taxes, specifically the new account type "Taxes" provided by the Polish localization.
After changing account type in the tax account connected with tax, for e.g. Current liabilities, everything works OK.
Best,
Krystian

btw., source: community\addons\l10n_pl\data\account_tax_data.xml

    <record model="account.account.type" id="account_type_tax">
      <field name="name">Podatki</field>
    </record>

question - If such additional account type is allowed? If not community\addons\l10n_pl\data\account.account.template.csv should be changed.

![tax_account](https://user-images.githubusercontent.com/43400881/66748694-21b53f00-ee88-11e9-9f64-3726df2ab803.jpg)

**Comment by jco-odoo** [comment]
@kharkot Ok, we tried to reach to partners to replace in order to use existing account types instead of this extra one.  But it was on short notice too.  The problem with using extra account types is that they don't appear in the balance sheet anymore.  (why we put the off-balance sheet)

The best thing would be to replace the Podatki with current liabilities, but we need to be sure.  Another one is putting another internal group on Podatki, but I would like to avoid that.

**Comment by jco-odoo** [comment]
@jcr-odoo You must know somebody who can help us quickly here.

**Comment by kharkot** [comment]
@jco-odoo 

HI, I am representing one of the partners from Poland (Trilab) and no one has tried to contact us.

If additional account type is not recommended, sale type tax cen has liability type, but purchase tax is rather receivables type.

We can help and provide proper account definition.

Best 
Krystian

**Comment by jco-odoo** [comment]
@kharkot Indeed, the generic approach would be to change the sale tax accounts to current liabilities and the purchase ones to current assets.  Of course, if you can help us improve (preferably without changing everything at once) it would be really helpful.  

@nim-odoo

**Comment by kharkot** [comment]
@jco-odoo no problem, I attach 
a. account.account.template_release13.csv (account def)
b. l10n_pl_chart_data__release13.xml

without l10n_pl.account_type_tax. 
This is minimal change (but all Polish localization should be changed including COA, taxes, and eg obligo financial reports (https://apps.odoo.com/apps/modules/12.0/trilab_pl_reports/)



[l10n_pl.zip](https://github.com/odoo/odoo/files/3725412/l10n_pl.zip)
If you would like I can do PR

**Comment by jco-odoo** [comment]
@kharkot If you can agree with #38875 ?  I would like to merge this and then check your account def later on.

**Comment by jco-odoo** [comment]
@kharkot http://655186-13-0-l10n-pl-fix-accounts-jva-80adbe.runbot21.odoo.com/web/login

**Comment by kharkot** [comment]
@jco-odoo tested on company "Poland" with PL COA and taxes - works OK (both in and out invoice are accounted without errors).

**Comment by jco-odoo** [comment]
@jva-odoo Can you also check the zip?

**Comment by jva-odoo** [comment]
@jco I already checked
