### ISSUE TITLE
[13.0] No option to removing Attachment after adding.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38003]
Impacted versions:
odoo 13
**Current behaviour:**
1) By Mistake Added wrong  attachment no option to remove.
![Selection_026](https://user-images.githubusercontent.com/24518821/66253155-58e96900-e781-11e9-8c99-7366e0619c06.png)

**Expected behaviour:**
1) There need such option to remove attachment.
![Selection_025](https://user-images.githubusercontent.com/24518821/66253083-8c77c380-e780-11e9-8dfe-c747666553cb.png)

**Video/Screenshot link (optional):**
![Attach](https://user-images.githubusercontent.com/24518821/66253077-81249800-e780-11e9-8328-8d27c20ce557.gif)

**Comment by pedrobaeza** [comment]
Indeed this is happening, but it's probably a side effect. @mge-odoo are you the responsible of this?

**Comment by seb-odoo** [comment]
He doesn't work anymore, I suppose I would be responsible for this.

I think on the portal there is no delete button on purpose (but I'll have to double check) but from the admin page this is definitely strange.

**Comment by seb-odoo** [comment]
We have an internal task for this, not sure what the final PR will be but I posted this issue to it.

**Comment by pedrobaeza** [comment]
Thanks for the follow-up
