### ISSUE TITLE
[13.0] Couldn't Uninstall "Invoicing" module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38006]
Impacted versions: 13.0

Steps to reproduce:
![Screenshot from 2019-10-06 01-32-09](https://user-images.githubusercontent.com/16624719/66260211-3a16c100-e7d9-11e9-9ec4-a9656ca0c8cf.png)

Current behavior: 
![Screenshot from 2019-10-06 01-33-07](https://user-images.githubusercontent.com/16624719/66260217-46028300-e7d9-11e9-83d5-6ceaa411d808.png)

Expected behavior: Successful Uninstall

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Here we go again ;)

**Comment by burhan-vakharia** [comment]
I confirm this issue in Odoo 13 Enterprise version too.
![invoicing_uninstall](https://user-images.githubusercontent.com/36418276/66310304-7eb17200-e929-11e9-90d4-25041db2997f.png)

**Comment by Yenthe666** [comment]
Tested on the latest 13.0 community & ENT and works fine now.
