### ISSUE TITLE
[13.0]Sales Team(Invoices): TypeError: Cannot read property 'list' of undefined

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38016]
**Impacted versions:**

1. Odoo 13.0

Steps to reproduce:

1. Go to Sales > Orders > Sales Team 

**Current behaviour:**
1) When we click on Invoice It raise TraceBack
![Sales Teams - Odoo](https://user-images.githubusercontent.com/24518821/66266040-0a99a000-e83d-11e9-82bc-e43107af8924.png)

![Sales Teams - Odoo](https://user-images.githubusercontent.com/24518821/66266059-43397980-e83d-11e9-935b-dc03c6b2cc0b.png)

**Expected behaviour:**

1. Traceback should not come when we click on invoice,Invoice list should be open.

**Video/Screenshot link (optional):**
![salesteam](https://user-images.githubusercontent.com/24518821/66265959-38cab000-e83c-11e9-8638-3f2cc104dae2.gif)

**Comment by sswapnesh** [comment]
This is because the `calendar` view doesn't exist for account.move 

Made a fix at https://github.com/odoo/odoo/pull/38022
