### ISSUE TITLE
[8.0] Overwrite user_id attribute from module analytic_user_function

### ISSUE THREAD

**Issue by stijnh92** [odoo/odoo#3801]
When trying to overwrite the required attribute of field user_id in module analytic_user_function, it does not work. My custom module depends on analytic_user_function and i import this file in my **init**.py. 

Original class definition:

``` python
class analytic_user_funct_grid(osv.osv):
    _name="analytic.user.funct.grid"
    _description= "Price per User"
    _rec_name="user_id"
    _columns={
        'user_id': fields.many2one("res.users", "User", required=True,),
        'product_id': fields.many2one("product.product", "Service", required=True,),
        'account_id': fields.many2one("account.analytic.account", "Analytic Account", required=True,),
        'uom_id': fields.related("product_id", "uom_id", relation="product.uom", string="Unit of Measure", type="many2one", readonly=True),
        'price': fields.float('Price', digits_compute=dp.get_precision('Product Price'), help="Price per hour for this user.", required=True),
    }
```

Overwritten:

``` python
class analytic_user_funct_grid(osv.osv):
    _inherit="analytic.user.funct.grid"
    _description= "Price per Role"

    _columns={
        'user_id': fields.many2one("res.users", "User", required=False,),
    }
```

**Comment by Yenthe666** [comment]
Hi @stijnh92 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

P.S: You're better off asking these kind of questions on the official forum (at help.odoo.com).

Regards,
Yenthe
