### ISSUE TITLE
[13.0] Lunch : Alert menu > With filter and with and without records listview columns shrinking.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38018]
Impacted versions: 13.0 C

Steps to reproduce:

- Go to Lunch app > Configuration > Alerts.
- Click on Filter named: 'Currently inactive'.
- Now See the listview's every column width and space without entering any record. and also see after entering a record.

Current behavior:
- Beginning columns are expanding .So at the end, last columns are shrinking only without records.but with records its seems fine.

Expected behavior:
- it should show the same in both cases. with filter either with a record or without it.

Video/Screenshot link (optional):

without any record : [http://tinyurl.com/yxukn32n](http://tinyurl.com/yxukn32n)
with record : [http://tinyurl.com/yxrk7z3q](http://tinyurl.com/yxrk7z3q)

**Comment by Yenthe666** [comment]
This was fixed in https://github.com/odoo/odoo/commit/5f3f58a41f92f6b90f48beb11d89fb253945564d
