### ISSUE TITLE
[8.0] Record Rules: no support for a single group-specific FALSE_LEAF rule

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#3802]
...`FALSE_LEAF`
## Explanation

If you add a record rule like this

```
<record id="this_rule_should_restrict_access_but_will_never_be_apply" model="ir.rule">
        <field name="name">This rule will never be apply</field>
        <field name="model_id" ref="module.model_name" />
        <field name="domain_force">[(0,'=',1)]</field>
         <!-- <field name="domain_force">[('type','=','always_false')]</field> -->
        <field name="groups" eval="[(6,0,[ref('module.supposed_to_not_have_access')])]"/>
        <field name="perm_read" eval="0"/><field name="perm_write" eval="1"/>
        <field name="perm_create" eval="1"/><field name="perm_unlink" eval="1"/>
</record>
```

Then during the evalution into the `expression.py` the `def combine(operator, unit, zero, domains)` will first evaluate this as `False`
So we have  `domain == unit` and then it will `continue` (logically to remove unecessary/useless `False` result into `OR` expression)

**However** case where this is the only one expression the result will be an empty list.

This is why it seems there is a problem into the `_compute_domain` (`ir_rule.py`):

```
            if group_domains:
                group_domain = expression.OR(map(expression.OR, group_domains.values()))
            else:
                group_domain = []
            domain = expression.AND(global_domains + [group_domain])
```

Actually `group_domain` will be returned as `[]` (because of the `combine`) and domain will not be the representation of wanted expression

I think this is not normal to have `group_domain` equals to [] for other case than the `else` because that potentially means that this is not what we expected with this rule.

A solution should be to check the result after the `expression.OR` and then add the `FALSE_LEAF` for at least have an expression for next step (in this case we want to evaluate this False expression into the result).

**Otherwise** even if you set this rule : the user of the group **will be able to CRUD as he want**

Thanks in advance

-jne

**Comment by Yenthe666** [comment]
Hi @JonathanNEMRY ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. As Olivier has mentioned this is more of a far-fetched situation though. I honestly do not believe this is the right way to go?

Regards,
Yenthe
