### ISSUE TITLE
[13.0]  Could not Display the Selected Image on Sales order

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38026]
Impacted versions: 13.0

Steps to reproduce: Add Non Image file to on Signature on Sale Order

Current behavior:  'Could not Display the Selected Image' when the record is loaded

Expected behavior: Don't save Non-Image binary 

Video/Screenshot link (optional):

![Peek 2019-10-07 00-22](https://user-images.githubusercontent.com/16624719/66274107-b3291d80-e898-11e9-8db7-516e6d09a85a.gif)

Not sure If it is duplicate/related to  https://github.com/odoo/odoo/issues/38021

**Comment by seb-odoo** [comment]
Thank you for the report, but this doesn't look like a bug: if it just didn't show it, the user would wonder why its file is not saved and could not correct its mistake.

**Comment by sswapnesh** [comment]
Then this behaviour should be consistent everywhere 

Remove Selected file or Don't allow to save the record

**Comment by seb-odoo** [comment]
Actually reopening, the issue is that the `signature` field is `Binary` instead of the new `Image` so it doesn't crash at save like it should.

It does make sense the error is there the first time, but not after.
