### ISSUE TITLE
[WISH] Price rules miss a condition on shipping

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#38030]
Price rules in pricelists miss a condition on shipping (delivery method).

Often ecommerce works with fix prices for shipping cost, because it simplify the user experience. Sometimes the real cost is lesser than the one paid by customer, sometimes it is more. There is often two shipping options : one fast and expensive, the other slow and cheap. Usualy, we loose less money with the cheaper one.
Promotional code gives customers a rebate on products. It would be useful to force user to choose the cheaper shipping option.

**Comment by pedrobaeza** [comment]
This seems very specific to a use case and IMO should be modeled in a community module.

**Comment by Yenthe666** [comment]
I think this would be a nice request for OCA :)

**Comment by zeroheure** [comment]
Fix shipping price is a common case in small ecommerce retail.

**Comment by Yenthe666** [comment]
@JKE-be what do you think?

**Comment by pedrobaeza** [comment]
@zeroheure fixed price shipping already exists in Odoo. What requires a custom module is the other constraints for not allowing to select certain delivery prices if a coupon is applied, and as said, that's very use case specific IMO.

**Comment by zeroheure** [comment]
Well, working with a lot of very small companies gives me a different point of view : they don't ask for something if they don't know that it is possible. In other words, many of their needs remains uncovered because nobody ask. You are right that this is curently a specific use case, but I doubt that this is not a common need in ecommerce.

**Comment by JKE-be** [comment]
Ping @fgi-odoo, the king of the pricelist specs.

**Comment by fgi-odoo** [comment]
Yes it's too advanced.
