### ISSUE TITLE
Add rel="ugc" to user-generated content in website

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#38038]
Impacted versions: all

@JKE-be, as I was working in https://github.com/odoo/odoo/pull/37984, I just realized there's an attribute I personally didn't know existed, but makes much sense.

[Google says this about `<a rel="ugc">`](https://support.google.com/webmasters/answer/96569):

> **We recommend marking user-generated content** (UGC) links, such as comments and forum posts, as ugc.

Also [about comment spam](https://support.google.com/webmasters/answer/81749):

> `<a href="http://www.example.com/" rel="ugc">This is a nice site! </a>`
>
> This new link will generally **not be taken into account when calculating PageRank**. This won't prevent spam, but it will avoid problems with passing PageRank and deter spammers from targeting your site. By default, many blogging sites (such as Blogger) automatically add this attribute to any posted comments.

So I think Odoo should add that out of the box to all links generated from users comments in the website.

@Tecnativa

**Comment by JKE-be** [comment]
Hi

Yes, a new thing that google release a few week ago and is IMO to young to support.
Or at least support both: `rel="nofollow ugc"`  as the doc allow it, but not sure that marketing tools and other search engine will understand it for now.

We should probably wait before to use it everywhere... at least a few month to see how it evolves.

Interesting related link:
https://www.linkresearchtools.com/google/no-follow-links-2-0-ugc-sponsored/
and https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

But in all cases, thank to ping us with this new feature, didn't know before your thread.

**Comment by JKE-be** [comment]
@dmo-odoo 

Maybe we could handle into the new editor a way to specify when you instantiate the editor, if you are in 'User Generated Content' (comment, forum, ...) or when it is the admin to support at least the nofollow tag and why not the ugc later...

Even if doing the job in client side is not enough, it will be a first step where it is not critical.
Btw on the forum it should be handled server side for sure...

**Comment by dmo-odoo** [comment]
@JKE-be I'm not sure I understand what you mean. Here are a few interpretations:

- Letting the user check a box for this when he creates a link using the "create link" modal: easy

- Setting it automatically when creating a link by choosing a forum or comment page: probably not very hard, but will require a way to mark these pages as ugc that would live outside of the editor

- Somehow "detect" that the url *manually entered* by the user when creating his new link is in fact a ugc: I have no idea how that could even work.

Tell me what you meant to be sure we're talking about the same thing... :)

**Comment by JKE-be** [comment]
Was talking about thé second point :)

When you instanciate thé editor/chatter as comment, talk proposal, forum post, ... auto add attr rel=« ugc » on générated link

**Comment by pedrobaeza** [comment]
@JKE-be any news about this?

**Comment by dmo-odoo** [comment]
@pedrobaeza I don't think this will make the cut for Odoo 14. I just re-discussed the issue with @JKE-be however and we were able to find a common understanding of what would have to be done. I created a proper task in the web_editor project for it. Thanks for the suggestion.

**Comment by pedrobaeza** [comment]
OK, thanks for the follow-up. Having a task for that seems enough now, so closing this issue.
