### ISSUE TITLE
Cancelling a procurement with PO related does not erase quantity/line on PO

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#3806]
Tested on runbot
http://29238-8-0-1e009e.runbot.odoo.com/web

Go to sales order
Create one
select a product procurement make_to_order, buy
Confirm SO
Delete picking
Cancel SO

Only first procurement is cancelled, and second one remains running, so.. cancel manually second one who has got related PO where product to procure has been included correctly.

So:
.- Cancel procurement manually
.- Go to related PO (Existing before, procurement just added a new line) 
.- You will see that product remains still on PO even if I cancelled procurement. 

Thank you:
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
