### ISSUE TITLE
Uncaught TypeError: linkInfo.range.commonAncestor(...).closest is not a function

### ISSUE THREAD

**Issue by burhan-vakharia** [odoo/odoo#38083]
Impacted versions: Odoo13 Community & Enterprise

Steps to reproduce:
In the HTML editor, system shows an error when clicking on the Link Insert icon.
Kindly refer the attached Video.

Current behavior:

Expected behavior:
It must show the "Add Link Popup"
![link_add](https://user-images.githubusercontent.com/36418276/66311475-334c9300-e92c-11e9-9c6c-04dcc1a1ed37.png)

Video/Screenshot link (optional):
![link_add_html_view](https://user-images.githubusercontent.com/36418276/66311622-81fa2d00-e92c-11e9-9932-68715a90de8d.gif)

**Comment by louigigr** [comment]
I am having the same issue.
I am able to edit links it existing templates, but I get the same error when I try to create a new link,

**Comment by Yenthe666** [comment]
Hi,

This one has been fixed in the meanwhile! Proof:
![image](https://user-images.githubusercontent.com/6352350/68765484-299a0780-061d-11ea-94a0-6c1f23a3909a.png)

If you update your local instance it will be solved :)

Regards,
Yenthe
