### ISSUE TITLE
 [6.1 / 7.0 / trunk] account_financial_report does not use sign in comparison column

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#381]
https://bugs.launchpad.net/ocb-addons/+bug/1101811

When running financial reports (account/report/account_financial_report.py) in comparison mode, the sign property of report entries is not taken into account in the comparison column.

How to reproduce:
- run a report that has some "sign" property = -1, such as Luxembourg P&L (in l10n_lu)
- make sure you have entries for 2 fiscal years
- notice the sign is correct in the base column but not in the comparison column.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
