### ISSUE TITLE
13.0 Chat with us Functionality not work in mobile

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38117]
Impacted versions:
13.0

Steps to reproduce:
Go to your website and open your menu bar and click chat with us tab in bottom.
 
Current behaviour:
I have no option to close menu ans also refresh page chat menu directly open  

Expected behaviour:
Option close menu and or work back button functionality in mobile.

Video/Screenshot link (optional):

https://drive.google.com/open?id=1DHV5GFSUdIsSzs1eV7NnuLXh6ENUQNou

**Comment by pedrobaeza** [comment]
Isn't the problem that you are logged in?

**Comment by pedrobaeza** [comment]
Then there it is! This problem is not going to happen with public visitors

**Comment by sswapnesh** [comment]
> I have no option to close menu ans also refresh page chat menu directly open

With Public User (No Login)
![Screenshot from 2019-10-07 23-52-04](https://user-images.githubusercontent.com/16624719/66337806-7bd07480-e95d-11e9-8567-df77c25d7656.png)


----------------

> This problem is not going to happen with public visitors
@pedrobaeza  It works well with Public User

**Comment by pedrobaeza** [comment]
And with portal one as well, so closing this.
