### ISSUE TITLE
13.0 : User address not perfectly display in my account

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38116]
Impacted versions:
13.0

Steps to reproduce:
Go to website >  click on user > Go to account

Current behavior:
Overlap details and icon in website

Expected behavior:
Not overlap details and icon in website 

Video/Screenshot link (optional):
![w1](https://user-images.githubusercontent.com/29298578/66323650-bfb58080-e941-11e9-99f9-7993a52f4a15.png)

**Comment by pedrobaeza** [comment]
I confirm it

**Comment by rdeodoo** [comment]
Working fine now in 13.0
![image](https://user-images.githubusercontent.com/30048408/120684180-afe79a00-c49e-11eb-85bb-6389a6e19592.png)
