### ISSUE TITLE
13: Search Clear in website

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38125]
Impacted versions:
13.0

Steps to reproduce:
Go to website > shop > product
1. search a product in search bar 
2. click product and open product page

Current behavior:
Search bar contain search text

Expected behavior:
search text clear in a search bar

Video/Screenshot link (optional):

https://drive.google.com/file/d/1Nt8M9BAcRlQLD_ZVbAtqioBxIv1OuVOh/view

**Comment by sswapnesh** [comment]
[amazon.in](url) has also the same behavior :smile:  (Flipkart has not)

**Comment by pedrobaeza** [comment]
This is a design decision and I think it's correct, but as other things, it's a matter of taste.

Any way, this can't be considered as an issue, so closing.
