### ISSUE TITLE
13.0 : Add to cart not display

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38128]
Impacted versions:
13.0
Steps to reproduce:
Go to website > shop
1. Choose product and open product page
2. Click on add to cart button
3. click on continue shopping

Current behavior:

Cart product not display in  cart

Expected behavior:

Cart product display in cart when  click on continue shopping button

Video/Screenshot link (optional):

https://drive.google.com/file/d/1KVoyml_-dLOrFttoZN13pvcrxjKzC0QP/view

**Comment by sswapnesh** [comment]
@ammarofficewla 

> Cart product not display in cart

Continue Shopping and Refresh the Page, It will be Visible.
 (Still, we should Improve this, Cc @JKE-be )

**Comment by fja-odoo** [comment]
Fixed here: https://github.com/odoo/odoo/pull/37132

**Comment by JKE-be** [comment]
Thanks  @ammarofficewla  for reporting
Thanks @sswapnesh for followup
Thanks @fja-odoo for fix
