### ISSUE TITLE
13.0 : Add to compare button not display in mobile view

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38126]
Impacted versions:
13.0

Steps to reproduce:
Go to website > shop
1. see compare button in website.

Current behavior:

Compare button not display in mobile.

Expected behavior:

Compare button display in mobile

Video/Screenshot link (optional):

https://drive.google.com/open?id=1DW7W5H6uaYWQpyqQNuGprZRpRUx2d5Yz

**Comment by seb-odoo** [comment]
Thanks for the report.

It was already like that in previous versions too.

It's actually hidden on purpose because the compare page is not mobile friendly at all. This is advanced feature for large screens only.
