### ISSUE TITLE
13.0: Ticket view not perfectly display.

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38133]
Impacted versions:
13.0

Steps to reproduce:

Go to website > event
1. Open any event
2. Click on ticket click on register
3. Close ticket.
4. Again click on ticket

Current behavior:
Ticket toggle are not display perfectly

Expected behavior:

Ticket toggle displayed perfectly

Video/Screenshot link (optional):

https://drive.google.com/open?id=1DmBLbeQDYMHQEbbCVk-sFdUIteDyQJSB

**Comment by sswapnesh** [comment]
@ammarofficewla  Please use some Screen recording software (Eg, https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn)

**Comment by ammarofficewla** [comment]
ok, 
Right now I have issued in my screen recording software
I will update link As Soon As Possible

**Comment by pedrobaeza** [comment]
Is there a custom theme?

**Comment by ammarofficewla** [comment]
No

**Comment by pedrobaeza** [comment]
Then please record it better

**Comment by Yenthe666** [comment]
Hi there,

Since we haven't gotten any feedback in a while I'm closing off this issue.
Don't hesitate to respond back with more information. We'll reopen the issue if there is enough information to explain this issue.

Regards,
Yenthe
