### ISSUE TITLE
13.0 : Speaker Description no perfectly display in mobile

### ISSUE THREAD

**Issue by ammarofficewla** [odoo/odoo#38130]
Impacted versions:
13.0
Steps to reproduce:
Go to website > event
1. Open any event 
2. see speaker information 
Current behavior:

Speaker information description not perfectly displayed.

Expected behavior:

Speaker information description display as paragraph

Video/Screenshot link (optional):

![speaker description](https://user-images.githubusercontent.com/29298578/66334577-f21da880-e956-11e9-8e1f-b30d297735e8.png)

**Comment by pedrobaeza** [comment]
This can't be considered an issue, as the word is longer enough for not fitting in the available width. Use other font, size or theme.

Closing then.

**Comment by ammarofficewla** [comment]
what about  word are  not perfectly display in a screen.
 please see image and check **applications** word

**Comment by pedrobaeza** [comment]
Exactly. That's what I say. The word can't be split, as it's very long.
