### ISSUE TITLE
[11.0] Grouping employee by PIN causes traceback on screen

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38132]
Impacted versions: 11.0 (From Commit https://github.com/odoo/odoo/commit/46aa4cd9fe1579fc0929d5d49c38577e18d61649)

Steps to reproduce: Employees --> Group By PIN --> Open Employee Form --> Go Back to List View

Current behavior: 
![Screenshot from 2019-10-07 23-53-48](https://user-images.githubusercontent.com/16624719/66337951-c0f4a680-e95d-11e9-9a48-5e325c4d5896.png)

Have a look at https://youtu.be/v5CGyGzeX5k for more details

Expected behavior: No traceback

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is made on purpose for avoiding show that information.

**Comment by sswapnesh** [comment]
:thinking:  Traceback too?
See https://youtu.be/v5CGyGzeX5k?t=21

**Comment by pedrobaeza** [comment]
No, that shouldn't happen indeed

**Comment by Yenthe666** [comment]
@nim-odoo you broke it ;)

**Comment by Yenthe666** [comment]
@sswapnesh this seems to be handled now:
![image](https://user-images.githubusercontent.com/6352350/71814799-d8871c80-307d-11ea-908e-aa708ec70553.png)
