### ISSUE TITLE
[12] point_of_sale, refund without payments

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#38147]
**Impacted versions:**
12, tested on runbot
**Steps to reproduce:**
Create a Order with negative quantity and go to payment screen
**Current behavior:**
Can validate order without payments.

Issue is introduce on commit https://github.com/odoo/odoo/commit/302d8a526441b85120f1b4501bae3efcbe700d47#diff-1c14accbe350f7a177b3e81e5846861bL2262 

CC @jorenvo @jpp-odoo 
**Expected behavior:**
Enter payments for order and validate only if total payments is equals to amount due
**Video/Screenshot link (optional):**

![Untitled Project](https://user-images.githubusercontent.com/7775116/66365609-3b6bf900-e953-11e9-9b60-14dc5e59a2d9.gif)

**Comment by switch87** [comment]
@celm1990 This is known behaviour. There was decided upon keeping it like this. 
Once the order is validated without a negative payment done, a cash payment will automatically be created in the database.

There is a check on this though; If the cashier doesn't pay the customer enough he/she will get a complaint, If the customers don't pay enough they will probably pretend they did. ;)

**Comment by celm1990** [comment]
Ok, thank for clarify
