### ISSUE TITLE
Odoo to many redirects http -> https

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#38152]
Impacted versions: 12

Current behavior:
If I open http://mywebsite.com NGINX redirects to https://mywebsite.com - it tooks about 80ms. 
But when odoo detect than it should change language then it redirect to http://mywebsite/languange (150/200ms) and then redirect againt to https://mywebsite/language (300/400ms)

system parameters
web.base.url set to https://mywebsite.com
web.base.url.freeze True
Tried with proxy mode true 

How to eleminate this redirect to http? I would like to odoo redirect straight to https

**Comment by Yenthe666** [comment]
Looks like a misconfiguration in NGINX?

**Comment by zozolpl** [comment]
Are you able to help with that? 
I find out, that website is not working on mobile devices, and when I check it on pagespeed insight google get error Lighthouse returned error: NO_FCP I guess it is caused by nginx too

nginx.conf
`   ##
        # Gzip Settings
        ##

        gzip on;

         gzip_vary on;
         gzip_proxied any;
         gzip_comp_level 7;
         gzip_buffers 16 8k;
         gzip_http_version 1.1;
         gzip_types
                text/plain
                text/css
                text/js
                text/xml
                text/javascript
                text/json
                application/javascript
                application/json
                application/xml
                application/rss+xml
                image/svg+xml
                image/jpg
                image/png
                image/jpeg
                font/plain
                font/truetype
                font/opentype;
        gzip_static on;
        gzip_min_length 10;


        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
`

sites-enabled -> mywebsite.com
`server {
 listen 80 default_server;
 listen [::]:80 default_server;
 server_name water-display.com www.water-display.com;
 rewrite ^ htts://water-display.com$request_uri? permanent;
 client_max_body_size 100M;
 #return 301 $scheme://water-display.com$request_uri;
  return 301 https://water-display.com$request_uri;
}

server {
client_max_body_size 100M;
    listen 443 ssl;
    server_name water-display.com www.water-display.com;
    ssl_certificate /etc/water-display.com.crt;
    ssl_certificate_key /etc/water-display.com.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

   access_log /var/log/nginx/odoo.access.log;
   error_log /var/log/nginx/odoo.error.log;




#ssl weryfikacja plik
location ^~ /.well-known/ {
 default_type "text/plain";
 alias /var/www/acme-challenge/;
  autoindex on;
}

location / {

      proxy_set_header        Host $host;
        proxy_set_header        X-Forwarder-Server $host;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
     # proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        X-forwarder-Host $host;
      # Fix the “It appears that your reverse proxy set up is broken“ error.
      proxy_pass          http://localhost:8069;
     # proxy_read_timeout  90;

#      proxy_redirect      http://localhost:8069 https://water-display.com;
}
}
`

sites-enabled -> mywebsite.com.conf
`server {
  listen 443;
  server_name water-display.com www.water-display.com;

  include snippets/letsencrypt.conf;
}

server{
listen 80;
server_name water-display.com www.water-display.com;
}
`

**Comment by Julien00859** [comment]
You have duplicated server definition

    server {
        listen 80;
        server_name mywebsite.com www.mywebsite.com;
    }

and

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name mywebsite.com www.mywebsite.com;
        rewrite ^ htts://mywebsite.com$request_uri? permanent;
        client_max_body_size 100M;
        return 301 https://mywebsite.com$request_uri;
    }

`server` block must have unique `listen`/`server_name` pairs across your configuration otherwise it leads to weird behaviors.

I suggest you read the [documentation concerning odoo deployment behind nginx](https://www.odoo.com/documentation/13.0/setup/deploy.html#https).

**Comment by malkindy** [comment]
I am facing similar problem of redirection and am not able to resolve it as I am not expert in setting odoo  v15 and I could not understand the guide from NGINX 

dump of the file :server {
    listen 80;
    server_name xx.xx.xx.xx;
    return 301 https://www.example.com;
}
server {       server_name xx.xx.xx.xx example.com/web  www.example.com/web;     

		access_log /var/log/nginx/testing-access.log;    
		error_log /var/log/nginx/testing-error.log;    
		location /longpolling {        
			proxy_connect_timeout   3600;        
			proxy_read_timeout      3600;        
			proxy_send_timeout      3600;        
			send_timeout            3600;        
			proxy_pass http://127.0.0.1:8072;
	}
		location / {        
			proxy_connect_timeout   3600;        
			proxy_read_timeout      3600;        
			proxy_send_timeout      3600;        
			send_timeout            3600;        
			proxy_pass http://127.0.0.1:8069/;        
			proxy_set_header Host $http_host;        
			proxy_set_header X-Forwarded-Host $http_host;        
			proxy_set_header X-Real-IP $remote_addr;        
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    
	}

	gzip on;
        gzip_min_length 1000;

	listen 443 ssl;
        ssl_certificate /etc/nginx/ssl_new/ssl-bundle.crt;
        ssl_certificate_key /etc/nginx/ssl_new/ssl-key.key;

	
	}
upstream odoo {
	server 127.0.0.1:8069 weight=1 fail_timeout=0;
}
upstream odoo-im {
	server 127.0.0.1:8072 weight=1 fail_timeout=0;
