### ISSUE TITLE
How to create notification/action on Incoming email

### ISSUE THREAD

**Issue by yn1989** [odoo/odoo#38159]
Impacted versions: 12

Steps to reproduce:
Actions to Perform on Incoming Mails->Create a New Record->calendar.event
Current behavior:

Expected behavior: Nothing happens
creates a new event in the calendar

Video/Screenshot link (optional): no

The task as a whole is to put the deadline \ tag on the contact to which the letter has arrived. Or create a new event. In version 12 in the Incoming email server there is no Server action item

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
