### ISSUE TITLE
Adding contact to a supplier/vendor makes it supplier/vendor too, v12

### ISSUE THREAD

**Issue by gr22** [odoo/odoo#38158]
If I add a contact to existing customer (let's say adding a shipping address) it will automatically inherit `default_customer = True` . Now When I create a Sale Order I always see both contacts when searching for the right customer.
This seems confusing to me.

The shipping or invoicing address should not appear as a separate partner when creating SO/PO ...

I would say the context of `child_ids` in res.partner can be changed to` default_customer: False, default_supplier: False`

**Comment by pedrobaeza** [comment]
This is something very subjective, as I would prefer the current behavior, doing it also a customer/vendor.

**Comment by gr22** [comment]
It could be subjective. For some customers I have several shipping addresses and other contacts and I don't know the case where you'll need to select the shipping address as a customer of a SO. I have changed this myself but I posted here in case would be considered useful.
Regards

**Comment by pedrobaeza** [comment]
Yeah, you can find valid use cases for both behaviors, as I have shipping addresses that are the sales order partners and invoices addresses.

Closing this then as design decision.
