### ISSUE TITLE
[8.0] Make to order sales order / Reordering rules min/max RFQ issue

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#3815]
Latest 8.0 code in use on Ubuntu

Problem: When a procurement request is generated from a make to order sales order, the quantity already on the RFQ / Reordering rule is not considered

Steps to reproduce:
1. Create 1 product A with procurement method make to order
2. Ensure No stock on hand
3. Assign product to a Supplier with a minimum order quantity of 5
4. Create a reordering rule. 5 minimum 10 maximum.
5. Compute schedulers or minimum stock rules
6. A RFQ is created for 10 units.

----- So far everything working as expected. ------
1. Create a sales quotation for 1 quantity of product A.
2. Confirm the order
3. ISSUE: 5 quantity is added to the RFQ exceeding the maximum quantity rule.

Explanation
The maximum quantity on hand for the reordering rule is 10 units which is what the purchase quotation is for. Since there is only 1 unit in demand, the RFQ should have only been increased by 1 unit as the amount on order already satisfies the reordering rule AND the minimum amount to order. When the 1 unit is received, it would allocate to the order and the rest would satisfy the maximum quantity on hand.

If you repeat the test, but instead create the sales order first, then compute the schedulers, 6 is added to the RFQ correctly. 1 on demand, 10 max quantity in location = 11.

I believe when a sale order for make to order is confirmed it does not check if the quantity on order is sufficient. The reverse operation (make to stock computation) does.

**Comment by Yenthe666** [comment]
Hi @aliomattux ,

Thank you for your detailed bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
