### ISSUE TITLE
when duplicate a product.product under variant, the product.template would also duplicate with wrong quanlity.

### ISSUE THREAD

**Issue by guohuadeng** [odoo/odoo#38151]
Impacted versions:
13.0
Steps to reproduce:
1. go sales->products->product variant.
2. find Customizable Desk (CONFIG)
3. duplicate  Customizable Desk (CONFIG) of legs: aluminium, color:black, name to  Customizable Desk (CONFIG) 11111

Current behavior:
4. get 7 new product.product of Customizable Desk (CONFIG)11111
5. get 1 more product.template of Customizable Desk (CONFIG)11111

Expected behavior:
4. get 1 new product.product 
5. no new product.template create

Video/Screenshot link (optional):
![skuerror](https://user-images.githubusercontent.com/8255692/66372618-0609ee80-e9d9-11e9-9ec0-2ea9983666c9.jpg)

**Comment by pedrobaeza** [comment]
The creation of a new template is expected, as you can't have other variant with same attributes than the previous one. The only erroneous thing I see is that the new template has 7 variants instead of 6.

**Comment by seb-odoo** [comment]
Agree with @pedrobaeza, the fix should be fairly easy in override of `copy`, I'll check.

**Comment by altanmur** [comment]
Hello, @pedrobaeza 

How to show "duplicate menu" on Product.product?
