### ISSUE TITLE
What is the reason why lang field or res.partner is of type Char instead of Many2one?

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#38161]
**Impacted versions:**

- 11.0 (probably prior versions too)
- maybe 12.0 and 13.0 (but the location of the file in the current behavior section has changed)

**Steps to reproduce:**

1. Go to the file [https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_partner.py#L151](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_partner.py#L151)

**Current behavior:**

The field is of type `Selection`.

**Expected behavior:**

I expected to find a `lang_id` of type `Many2one` targeting `res.lang` model instead.

**Video/Screenshot link (optional):**

None.

**Question:**

Is there any reason why this field is not a `Many2one` field? Do you plan any rework on this?

I guess this could have been a legacy code, because I can see on a git blame it has been initially commited 7 years ago : 

> [REF] res.partner: updated model due to res.users inheriting from res.partner. lang and tz fields are now added as standard fields, with their default methods.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
