### ISSUE TITLE
Employee Master Country Selection applying to all the employees

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#3816]
step : 1 Create one employee and set the country X
step : 2 Create another employee and set the country  Y

All the employees country will be changed to the last updated employee country.
In short only the same country employee can be created in current scenario.

**Comment by Yenthe666** [comment]
Hi @orchidinfosys ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
