### ISSUE TITLE
[13.0] Invoice / Bill : Traceback when printing Invoice/ Bill.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38175]
Impacted versions: 13.0 C

Steps to reproduce:
- Go to app invoicing
- Create any invoice/vendor bill without Lines. And Cancel it.
- Print: Invoicing / invoicing without payment reports.

Current behavior:
- Throwing traceback.

Expected behavior:
- It should print report without any error.

Video/Screenshot link (optional):

[Link](https://youtu.be/Y273ofWKdBQ)

**HINT: just need to check whether invoice lines present or not.if not then do not need to use max() function.**

Thanks!

**Comment by Yenthe666** [comment]
@dipsshah42 I've just tested this on the latest 13.0 runbot instance and it already seems to be fixed? Can you test again on the latest runbot?

**Comment by Yenthe666** [comment]
See http://643648-13-0-dc8cbe.runbot18.odoo.com/web#id=9&action=550&model=account.move&view_type=form&cids=&menu_id=383 as a reference

**Comment by dipsshah42** [comment]
@Yenthe666 I checked but its not fixed. Actually need to cancel the invoice and then print. i forgot to mention that step.

**Comment by Yenthe666** [comment]
Ah yes, confirmed. Thanks.
