### ISSUE TITLE
[Question] 13.0 ORM Changes

### ISSUE THREAD

**Issue by keshrath** [odoo/odoo#38178]
This isn't really an issue, but I still hope to get some feedback. I've already asked this question in the forum, but I don't think the community is ready to answer such questions yet, as the new ORM is still brand new. The talks of @fpodoo and @rco-odoo on the Odoo Experience gave a good overview, but at least for me there are still some questions left unanswered on how to best handle certain scenarios in the future. 

Post: https://www.odoo.com/de_DE/forum/hilfe-1/question/orm-in-odoo-13-0-156981

Here are 2 examples that came to my mind and I'm sure there a more. I appreciate any insight and feedback.  

**Example scenario is to get the absolute name of a hierarchy**

_Odoo 12_

```python
@api.depends('name', 'parent_id', 'parent_id.computed_field')
def _compute_something(self):    
    ...
```
But that's making the ORM go recursively through all the child records which means a lot of queries. For version 12 I would have changed it as follows:

```python
@api.depends('name', 'parent_path')
def _compute_something(self):    
    ...
```

```python
@api.multi
def write(self, vals):    
    if 'name' in vals:        
        with self.env.norecompute():            
            res = super(SuperModel, self).write(vals)            
            domain = [('id', 'child_of', self.ids)]            
            records = self.sudo().search(domain)            
            records.modified(['parent_path'])        
        if self.env.recompute and self.env.context.get('recompute', True):            
            records.recompute()        
        return res      
    return super(SuperModel, self).write(vals)    
```

_Odoo 13_

Since norecompute has no effect in version 13, it would look like the following:

```python
@api.depends('name', 'parent_path')
def _compute_something(self):    
    ...
```

```python
def write(self, vals):    
    res = super(SuperModel, self).write(vals)    
    if 'name' in vals:        
        domain = [('id', 'child_of', self.ids)]        
        records = self.sudo().search(domain)        
        records.modified(['parent_path'])    
    return res    
```

But as far as I understood, the search would automatically trigger a flush. Is this in your opinion still the better way or is it now better to let the ORM handle this case and write the compute method as follows:

```python
@api.depends('name', 'parent_id', 'parent_id.computed_field')
def _compute_something(self):    
    ...
```

**Another variant that was often used in V12 to minimize the queries is something like this**

```python
@api.multi
def _inverse_something(self):    
    updates = defaultdict(set)    
    for record in self:        
        values = ...        
        updates[tools.frozendict(values)].add(record.id)    
    with self.env.norecompute():        
        for vals, ids in updates.items():            
            self.browse(ids).write(dict(vals))    
    self.recompute()  
```

Does that still make sense? As far as I understand it, it's already being optimized at the ORM level now, right?

**Comment by pedrobaeza** [comment]
I think these questions should go to the forum, not here. What do you think, @Yenthe666?

**Comment by Yenthe666** [comment]
I was a bit divided one this one for two reasons. It's about version 13 and I don't think there are a lot of people with detailed knowledge on the help forums. I estimate that only a few dozen people could potentially answer these questions. I think that an official response would be great but I assume the guys from Odoo are too busy for this too.

**Comment by llabusch93** [comment]
Hello @keshrath and @Yenthe666 

So there is still no answer for this one? I would also be happy to get an official recommendation how to do it the best way, before spending a lot of time to find a hack myself, what may be potentially not as good as something the designer of the ORM had in mind.

Thanks in advance.

**Comment by BT-aestebanez** [comment]
+1
