### ISSUE TITLE
[12.0] Inventory valuation: Inventory valuation by location WH

### ISSUE THREAD

**Issue by rafamarpe** [odoo/odoo#38180]
Impacted versions: 12.0

Steps to reproduce: Inventory - Reporting -> Inventory valuation

Current behavior: In v11.0 Inventory valuation grouped by location

Expected behavior: grouped by location

Video/Screenshot link (optional):

Is it possible to take inventory valuation grouped by warehouse? Is it being valued?
Thank you

**Comment by pedrobaeza** [comment]
@sle-odoo this has been added in v13, isn't it?

**Comment by sle-odoo** [comment]
yep [here](c861edefaa0009ba214d79a53376c85ab9f45991)

**Comment by pedrobaeza** [comment]
@rafamarpe this is something existing in v13, but there's no plans for backporting it in v12 due to stability policy. You can take that code and extract it in a community module, as this can work pretty the same in both versions.

Closing this as won't fix in 12.0, sorry.
