### ISSUE TITLE
[13.0] social marketing: link account gives white "unauthorized" page on local instance

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#38185]
Impacted versions: 13.0

Steps to reproduce:
1. Install an Odoo 13 enterprise instance locally and install the 'social media' app
2. Go to Social marketing > Configuration > Social Media and click on "Link account"

Current behavior:
A redirect to the IAP website giving an "Unauthorized" text message without anything else:
![image](https://user-images.githubusercontent.com/6352350/66392357-e5896680-e9cf-11e9-8f83-fd51d30c43fd.png)

Expected behavior:
A nice warning page telling you what is wrong/missing.

**Comment by Yenthe666** [comment]
@awa-odoo I'm not sure but I guess IAP/social media belongs to you?

**Comment by awa-odoo** [comment]
@Yenthe666 Are you sure you have the latest 13.0 version?

This should not be the case anymore.
Just tried on my side and I get the correct behavior: 

![Selection_294](https://user-images.githubusercontent.com/41282536/66392977-a4925180-e9d1-11e9-9371-89908088314c.png)

**Comment by Yenthe666** [comment]
Woha, it has indeed been solved in the meanwhile, in just two days.
