### ISSUE TITLE
[8.0] Purchase Unit of Measure in product is not proposed in purchase order when there are multiple UOMs sharing the same category

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#3818]
**Purchase Unit of Measure in product is not proposed when there are multiple UOMs sharing the same category**
### Impacted versions:
- 8.0 (haven't checked other versions)
### Steps to reproduce:
1. create multiple UOMs with the same Product Category (category_id), each of them being 'Reference Unit of Measure for this category'.  Here, create a new Unit of Measure 'Piece(s)' with Product Category 'Unit' and Type 'Reference Unit of Measure for this category' (suppose the pre-defined UOM of Unit(s) is not disabled)
2. create a product with Purchase Unit of Measure as 'Piece(s)'
3. create a purchase order and select the product of above step
### Current behavior:
- Product Unit of Measure in PO line does not propose the Purchase Unit of Measure (it stays as 'Unit(s)' instead of 'Piece(s)')
### Expected behavior:
- Purchase Unit of Measure 'Piece(s)' is proposed

**Comment by Yenthe666** [comment]
Hi @yostashiro ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: No I don't believe it was supported by default in V8.

Regards,
Yenthe
