### ISSUE TITLE
[survey] Invitations - invited user can't answer survey

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#382]
https://bugs.launchpad.net/ocb-addons/+bug/1103072

Version 7.0-20130122-001415, Survey module.

After sending invitations to a partner, a user is created with a random password, and both are send in the e-mail.
However, when logging in with that username/password, absolutely no options are available.

After adding the "Portal" access right to this user, now some menu options are presented, but no Survey dialog is opened, nor there is an option available to access surveys.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
