### ISSUE TITLE
[13.0]E-learning:  After Duplicate the record attendees must be 0 in smart button.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38230]
**Impacted versions:**

1. Odoo 13

**Steps to reproduce:**

1. eLearning > Course >> select any one and duplicate.

**Current behaviour:**

1. When we duplicate the course Attendees  smart button value also duplicated.
![eLearning Overview - Odoo](https://user-images.githubusercontent.com/24518821/66411797-f5299f00-ea11-11e9-9c0e-88411ee22936.png)
 

**Expected behaviour:**
1.  After Duplicate the record attendees should be shows 0 and  smart button value also 0.
**Video/Screenshot link (optional):**
![Peek 2019-10-08 21-11](https://user-images.githubusercontent.com/24518821/66412066-6e28f680-ea12-11e9-830a-da1ceeb5bf06.gif)

**Comment by sswapnesh** [comment]
> After Duplicate the record attendees should be shows 0 and smart button value also 0.

No,  `self.env.user.partner_id.id` will be there.
https://github.com/odoo/odoo/blob/8ca7f866c8c17dece0e2fa50ea9d6df43dc4ebac/addons/website_slides/models/slide_channel.py#L341

**Comment by sswapnesh** [comment]
Added Fix on https://github.com/odoo/odoo/pull/38235

**Comment by sswapnesh** [comment]
Has been fixed in https://github.com/odoo/odoo/commit/900e2311bcf2d321b2d714b30dceb14ffa1f4e32
