### ISSUE TITLE
Non-admin users can't import an .xlsx file

### ISSUE THREAD

**Issue by uwine-fr** [odoo/odoo#38236]
Impacted versions: 12

Steps to reproduce:
As a non-admin user, try to import data from an .xlsx file

Current behavior:
Nothing happens (screen stays the same, no error message).

Relevant exception logs:

```
[...]
File "/home/odoo/src/odoo/odoo/models.py", line 3395, in _write
    val = field.convert_to_column(val, self, vals)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1794, in convert_to_column
    raise UserError(_("Only admins can upload SVG files."))
odoo.exceptions.UserError: ('Only admins can upload SVG files.', '') - - -
```

Expected behavior:
The import screen should be displayed to complete the import process.

**Comment by uwine-fr** [comment]
A bit of analysis: 
- the `convert_to_column` method tries to decode the file content as if it were encoded in base 64, then tries to guess the mimetype
- the base64-decoded content happens to start with a `<`
- the mimetype is therefore guessed as being `image/svg` (!)
- non-admin users are not allowed to upload svg images for security purposes

A number of non-merged PR would probably fix the issues here: #36081, #31849, #28936

At least the system should provide an helpful error message describing the limitation!

**Comment by pedrobaeza** [comment]
This is being handled in several PRs like #31849

**Comment by uwine-fr** [comment]
@pedrobaeza Indeed, I saw these. I created an issue to maybe draw a bit of attention to the matter; do we have an estimate of the time to get them merged ?

**Comment by pedrobaeza** [comment]
I was talking with @odony at Odoo XP last week and indeed this should be tackled soon. I'm still recovering from the week-off, but I will try to improve the code with the points both talked about.

**Comment by Julien00859** [comment]
I'm closing it as this is a known issue we are working on :)
