### ISSUE TITLE
[13.0] Products : Not able to replenish product.Error of invalid fields.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38238]
Impacted versions: 13.0 C

Steps to reproduce:
- Go to products (Product Variants),
- Open product and Select replenish option from Action toolbar. Or Select replenish from Action by selecting multiple products in listview.

Current behavior:
- Its showing warning of Following fields are invalid with fields.
    > Product Template, Product, Category, Unity of measure. 

Expected behavior:
- It should allow to replenish. Seems like Mandatory fields are not set when doing replenish from Action toolbar.

Video/Screenshot link (optional):
[link](https://youtu.be/Bc_Uvwef0M4)

**Comment by sswapnesh** [comment]
@dipsshah42  It would be great if you can add few screenshots as well on your new Reports, So one can quickly  verify it

**Comment by sswapnesh** [comment]
> Seems like Mandatory fields are not set when doing replenish from Action toolbar.

@dipsshah42  `default_product_id` was not passed on Action's context

Added Fix on https://github.com/odoo/odoo/pull/38239

**Comment by dipsshah42** [comment]
@sswapnesh  Thanks a ton. will keep adding screenshot now onwards.
