### ISSUE TITLE
Purchase: Don't update Received field

### ISSUE THREAD

**Issue by alxarce** [odoo/odoo#38241]
Impacted versions: 13C

Steps to reproduce:
    • Go to Purchase
    • Select a Purchase Order → Receive products 
    • Receive a partial or total amount of products and confirm.
    • Upon returning to the Purchase Order
      
Current behavior:
    • The system does not update the field of units received

Expected behavior:
    • That the system updates the field of units received correctly.

http://644433-13-0-8ad360.runbot29.odoo.com/web 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you specify a bit more the product configuration you have used?

**Comment by alxarce** [comment]
You can close the issue.

The problem was that the order lines were saved as the reception method 'manual' and not as 'stock moves'
