### ISSUE TITLE
[12.0] statement account error with reconciled entry in report

### ISSUE THREAD

**Issue by As400it** [odoo/odoo#38242]
Impacted versions:
12.0
Steps to reproduce:
create an invoice of 464,09 
create a payment of 464,19 (extra payment of 0,10) 
reconcile and add a 0,10 adjustment . 

the invoice is full paid . noting to reconcile . 

Current behavior:
in the report statement account there is 3 line   

Expected behavior:
in the report statement account it should 0 line    

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/11019886/66453746-c1786480-ea65-11e9-97ae-c1b33a3366aa.png)

![image](https://user-images.githubusercontent.com/11019886/66453824-fbe20180-ea65-11e9-85cd-4d9a8ab526d8.png)

**Comment by pedrobaeza** [comment]
Isn't that a community module? What is the path for printing that report?

**Comment by As400it** [comment]
yes is a community module .
