### ISSUE TITLE
[12.0] Calendar SMS reminder is not using partner_id timezone

### ISSUE THREAD

**Issue by avmediadesign** [odoo/odoo#38243]
Impacted versions: 12
Steps to reproduce: Get sms reminder set on appointment
Current behavior: sms gets send with meeting info in UTC time
Expected behavior: sms gets send with meeting info in partner_id timezone

**Comment by LucasLefevre** [comment]
Hello @avmediadesign
Thanks for the feedback! 
This will be handled in #38400

**Comment by avmediadesign** [comment]
Hello @LucasLefevre 
Thanks for the quick fix.

**Comment by bennals** [comment]
This issue is also present in 11.0 CE.  Does it require a separate issue to be created or can this fix be backported?

**Comment by LucasLefevre** [comment]
Hello @bennals 
The fix cannot be backported, it would break the sms translations for all existing customers in 11.0.

**Comment by avmediadesign** [comment]
What about 12.0?

**Comment by bennals** [comment]
that's a shame, but thanks for letting me know
