### ISSUE TITLE
[13.0] Bill : Traceback error when add credit note. 

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38307]
Impacted versions:
1. Odoo 13.0

**Steps to reproduce:**

1. Create bill > Validate > click on "Add Credit note " > Wizard will open enter reason > click to "Reverse"

**Current behaviour:**
1. Getting traceback error
![BILL 2019 0003 - Odoo](https://user-images.githubusercontent.com/24518821/66502565-1d350300-eae3-11e9-9146-c0d8a1adac83.png)

**Expected behaviour:**
1. No traceback

**Video/Screenshot link (optional):**

![billodoo](https://user-images.githubusercontent.com/24518821/66503041-15299300-eae4-11e9-82bd-84fdf65dd1b4.gif)

**Comment by Yenthe666** [comment]
Seems to work fine in the meanwhile (tested on the latest 13.0 runbot instances).
