### ISSUE TITLE
[13.0]Getting traceback error when delete payment terms.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38308]
**Impacted **versions:**

1. Odoo 13.0

**Steps to reproduce:**
1. Go To invoicing > Configuration > Payment Term > Select any one and Delete 

**Current behaviour:**
1. Getting traceback error when delete payment terms.
![15 Days - Odoo](https://user-images.githubusercontent.com/24518821/66504886-ce3d9c80-eae7-11e9-8982-abb41a3b10c3.png)

**Expected behaviour:**
1. No traceback

**Video/Screenshot link (optional):**
![pt](https://user-images.githubusercontent.com/24518821/66504984-0a70fd00-eae8-11e9-9457-40cdfec5427f.gif)

**Comment by sswapnesh** [comment]
Added fix on https://github.com/odoo/odoo/issues/38309
