### ISSUE TITLE
[v8.0] Bank statement : Import invoice wizard does not work in multi-currency

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3830]
Step to reproduce : 

1 - create a customer invoice in currency (USD in my case)
2 - create a bank statement based on a journal in USD
3 - click on 'import invoice' and select the USD invoice

Problems : 
On the view where you select the invoice to be imported you do not see the currency amount
![image](https://cloud.githubusercontent.com/assets/5735158/5163733/3b672460-73cf-11e4-8b7a-bb53fea3df29.png)

Column amount_currency & currency must always be displayed as long as the multi-currency is activated in Odoo (AND EVEN if the bank is not in currency beacuse you may want to import a USD invoice in a company currency bank account)

**Comment by mart-e** [comment]
Thanks for the report, it was fixed at 8b95a8424bdbef91dc3d5100662ad4c398f7001b

**Comment by fclementic2c** [comment]
No. I think your fix is related to autocompletion of bank statement lines.
This bug report is only a matter of view : the 2 columns currency and amount currency must be visible.

**Comment by mart-e** [comment]
Oh my bad, I read too quickly the opw which was referring to two issues. Now it's done at a3c0742 (adding a bit of scroll but I agree it's an important information)
