### ISSUE TITLE
Print button is not working properly showing Access denied Error For All users

### ISSUE THREAD

**Issue by vaibhav14b** [odoo/odoo#3831]
Hello
As per below link 
http://localhost:8069/barcode/web/ 

Find Print button which is not working showing Access Rights Warning for all users.
Showing Below Odoo Warning

AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: stock.picking.type, Operation: read)

Tried to give full access rights for admin user - for object stock.picking.type but still not working.

Thanks in advance

**Comment by Yenthe666** [comment]
Hi @vaibhav14b,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
