### ISSUE TITLE
[13.0] Couldn't create Refund for Bill with Zero Amount

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38310]
Impacted versions: 13.0

Steps to reproduce: Create Bill with Zero and Post
![Screenshot (27)](https://user-images.githubusercontent.com/16624719/66514437-bfacb080-eafa-11e9-8765-2d2511a4e8f9.png)

Current behavior: On adding Credit Note
`odoo.http: ('Cannot create unbalanced journal entry. Ids: [34]\nDifferences debit - credit: [20.0]', '') `

![Screenshot (28)](https://user-images.githubusercontent.com/16624719/66514496-df43d900-eafa-11e9-919c-a497cc9aad96.png)

Expected behavior: Able to Create Refund

Video/Screenshot link (optional):

------------

Same Issue on Duplicate
![Screenshot (29)](https://user-images.githubusercontent.com/16624719/66514577-10bca480-eafb-11e9-99b0-927759ed18b9.png)

**Comment by Yenthe666** [comment]
@sswapnesh this works in the meanwhile :)
