### ISSUE TITLE
[11.0, 12.0, 13.0] ZeroDivisionError in picking

### ISSUE THREAD

**Issue by sajadkk** [odoo/odoo#38313]
**Impacted versions:**
13.0, 12.0, 11.0

**Steps to reproduce:**
Product P1 has on hand quantity of -5, when i try to adjust the done qty in incoming shipment and save it gives me the error

**Current behavior:**
gives error when saving

https://github.com/odoo/odoo/blob/1b647b8ead1fc70c18223914c96619c7f9a21b6e/addons/stock_account/models/stock_move.py#L306-L315
```python
forced_qty = 5
product_tot_qty_available = -5
qty_done = 20
move.product_qty = 15
qty = forced_qty or qty_done
new_std_price = ((amount_unit * product_tot_qty_available) + (move._get_price_unit() * qty)) / (product_tot_qty_available + qty) 
```
product_tot_qty_available + qt will be Zero

**Expected behavior:**
should not give any error

**Screenshot:**
![picking](https://user-images.githubusercontent.com/1268273/66540524-3074bc80-eb3d-11e9-9c1c-484f1825e74b.jpg)

![division_error](https://user-images.githubusercontent.com/1268273/66540460-ee4b7b00-eb3c-11e9-872e-611dfc2604bb.jpg)

**Comment by mart-e** [comment]
cc @sle-odoo may be introduced by f6c4afe8c317b4cb90080f6388a6c2046e67ff20

**Comment by sle-odoo** [comment]
arg
