### ISSUE TITLE
[7.0] [8.0] The name_get function on accounting journal should not add the currency if no secondary currency are set.

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3832]
The name_get function on accounting journal should not add the currency if no secondary currency are set.

Today, if I do a customer invoice in EUR whereas my company currency is CHF I do not want to see that teh Journal is : Sales Journal (CHF) like in the following example.

![image](https://cloud.githubusercontent.com/assets/5735158/5163852/8219a9fe-73d0-11e4-8851-f3ef1a054762.png)

However, it can be a interesting information for a bank journal with a secondary currency.

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
