### ISSUE TITLE
[8.0] Different supplier per company not set correctly in procurement PO

### ISSUE THREAD

**Issue by CretaOkada** [odoo/odoo#3833]
Version 8.0-ebbfda9

Supplier set on product page is not set correctly in the generated PO (procurement)

To reproduce:
Set up 2 companies, 2 users, enable multi-company
Set up product:
*Supplier 1 assigned to Company 1
*Supplier 2 (which in my case is Company 1) assigned to Company 2
Log in to Company 1, create SO for product, confirm, run scheduler - Supplier 1 shows up in PO (good!)
Delete PO (so Odoo doesn't consolidate)
Log in to Company 2, create SO for same product, confirm, run scheduler - Supplier 1 shows up in PO (bad!)

I tried to find the calls Odoo is making by debugging the sql:

openerp.sql_db: query:
SELECT "product_supplierinfo".id FROM "product_supplierinfo" WHERE
("product_supplierinfo"."product_tmpl_id" in (2)) ORDER BY
"product_supplierinfo"."sequence"  
openerp.sql_db: query: 
SELECT product_supplierinfo."product_tmpl_id",product_supplierinfo."id" FROM
"product_supplierinfo"
                    WHERE product_supplierinfo.id IN (1, 2) AND (TRUE)
                    ORDER BY sequence

openerp.sql_db: query: 
SELECT
product_supplierinfo."create_uid",product_supplierinfo."product_code",product_supplierinfo."create_date",product_supplierinfo."name",product_supplierinfo."sequence",product_supplierinfo."write_uid",product_supplierinfo."company_id",product_supplierinfo."min_val",product_supplierinfo."delay",product_supplierinfo."write_date",product_supplierinfo."id",product_supplierinfo."min_qty",product_supplierinfo."qty",product_supplierinfo."product_tmpl_id",product_supplierinfo."product_name"
FROM "product_supplierinfo"
                    WHERE product_supplierinfo.id IN (1, 2) AND (TRUE)
                    ORDER BY sequence

I believe this is a bug, or i've missed something very obvious

**Comment by PeterA-OpusVL** [comment]
Thankyou - this merge fixes the issue i posted on 23 Dec :+1:
