### ISSUE TITLE
Onchange is called even for the field which is not dirty in the form

### ISSUE THREAD

**Issue by msh-odoo** [odoo/odoo#3835]
Impacted versions:
    8.0
Steps to reproduce:
Create Purchase Order -> Purchase Order line, now when you create new purchase order line, there is a default value on UOM but default_value is overwritten by onchange result(It is expected behavior that onchange result should overwrite the value of defaults but here due to unexpected call to onchange_product_id returns uom_id=False).

When I dig into this issue I found onchange_product_id is called for the field product_id even though it is not dirty(not changed due to default_get), there is three fields in view of purchase order line which contains oncahnge i.e. product_id, product_uom and product_qty.

When Form is loaded it calls onchange without trigerfield, and hence all onchanges are called according to field's order so onchange_product_id is triggerred for the field product_id even though it is not changed.

**Comment by kurkop** [comment]
Could yout re-evaluate in the light of #6927 and confirm there? thanks.

**Comment by Yenthe666** [comment]
Hi @msh-odoo ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
