### ISSUE TITLE
After warehouse install, products that are not in pricelists, when selected do nor raise an error

### ISSUE THREAD

**Issue by pishpecki** [odoo/odoo#3837]
After installing MRP i got a problem with products that are not in pricelists. When creating quotation and selecting a product that is not in the pricelist defined (on the quotation), I do not get an error : "No valid pricelist line found ! ..." 
After examination of the problem, I found that in sale_stock.py "product_id_change_with_wh" "overrides" the "product_id_change" method from sale.py . In the new method the "product_id_change" from the original sale_order_line calss is called correctly and returns an error, but in the last line of the product_id_change_with_wh method this gets overwriten. 
My solution is to add this on the line 350 in sale_stock.py:
        if (res['warning']) != False:
            warning_msgs = warning_msgs + res['warning']['message']

This will cause the error message to be forwarded correctly to the user.

Regards

**Comment by Yenthe666** [comment]
Hi @pishpecki,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by pishpecki** [comment]
Wow. This is so old post I forgot I made it 😊

I am working on ver. 7 for the last 3 years and have developed it so much that we have features above ver 11.

Just fun to mention


________________________________
Best Regards,
Martin Pishpecki


________________________________
