### ISSUE TITLE
states and attrs do not work at the same time. At a minimum, that should be documented.

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#3838]
This was reported as https://bugs.launchpad.net/openobject-client/+bug/941901 and closed as "invalid".

It basically means that if you use `"states=draft"` and then add `attrs={'invisible': [('my_field', '=', True)]}`, then your element will appear on all states.

I find this very surprising. Even as it is left as is, it should at least be documented.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
