### ISSUE TITLE
[v8.0] Bank statement : Does Import invoice wizard auto-complete correct fields ?

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3839]
Step to reproduce:
- create a customer invoice (simple case)
- create a new bank statement and import this invoice
- click on 'Reconcile'

Problem:  No match between the bank statement line and the invoice move line can be found simple the communication field is '/'. (The invoice number is in the field 'Reference')

So maybe the auto-completion is ok because it is working like in v7 but the real problem is on the reconcile view which should propose a matching based on the reference field also (not only communication). What do you think ?

**Comment by mart-e** [comment]
Thanks for the report, we have merged at fix at 223c92f to use first the supplier number before the invoice origin,

**Comment by fclementic2c** [comment]
This bug report is still un-fixed for customer invoices.
Import an invoice from the bank statement and you will see that the reference does not go the the communication field -> so the reconcile does not work...

Thanks
