### ISSUE TITLE
[Trunk/7.0] document webdav : 500 error on connection

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#384]
https://bugs.launchpad.net/ocb-addons/+bug/1104559

cadaver http://localhost:8069/webdav/se_20130124_2246
Authentication required for OpenERP User on server `localhost':
Username: ferdinand
Password:
Could not open collection:
500 Internal error
dav:/webdav/se_20130124_2246/

openerp.service.http_server: Found user="ferdinand", passwd="***" for db="se_20130124_2246"

BTW it seems mandatory to add the DB-name. this should go into the module description

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
