### ISSUE TITLE
[13.0] Removed selection still appears after module upgrade

### ISSUE THREAD

**Issue by zeliklil** [odoo/odoo#38411]
Impacted versions: 13.0

Steps to reproduce:
Remove a `selection` choice from a module and upgrade the module

Current behavior:
The removed `selection` choice still appears on the ui
Using this choice raises a `ValueError`

Expected behavior:
The removed `selection` choice should no longer appear

**Comment by zeliklil** [comment]
I tried again and I didn't get the problem on a new database.
On the database where I got the error, the `ir.model.fields.selection` records still exist but the xml_ids for these records don't exist anymore.

**Comment by zeliklil** [comment]
I'll just close this issue and maybe open a new one if I can reproduce the error on a new database.

**Comment by mart-e** [comment]
@zeliklil removing a selection in another module is not a good idea, you can not guarantee records are not using the previous selection, this is not a supported scenario.
If you really need less selections, it is better to make your field non-stored with a dynamic selections.
