### ISSUE TITLE
[All] bus: Harcoded longpolling timeout does not consider big data loading

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#38425]
### Impacted versions:
11.0, 12.0, 13.0

### Steps to reproduce:
Create thousands of res.partners: over **100k**

### Current behavior:
Point of Sales does not load because the longpolling/poll timeout is reached while executing the method:  `https://<URL>/web/dataset/call_kw/res.partner/search_read`

https://github.com/odoo/odoo/blob/5ee0147c1ab9903d97d5409c972910eecd688fc7/addons/bus/models/bus.py#L17

![image](https://user-images.githubusercontent.com/16890942/66584483-3d9ca600-eb53-11e9-9272-26c9364aa0eb.png)

### Expected behavior:
Partners load without crashing the Point of Sale. Maybe not respecting the longpolling timeout in this scenarios.

**Enterprise Ticket**: 2086968

**Comment by pedrobaeza** [comment]
This shouldn't be the problem, but your reverse proxy timeout.

**Comment by blaggacao** [comment]
`https://<URL>/web/dataset/call_kw/res.partner/search_read`
doesn't route over the long polling route.

**Comment by gustavovalverde** [comment]
@pedrobaeza I've tested with: nginx, envoy and traffik (all with 900s timeouts) and each time the process is killed in 1 min

**Comment by blaggacao** [comment]
cloudflare?

**Comment by gustavovalverde** [comment]
@blaggacao cloudflare was hell without the expensive plans, I dropped that a while ago :D

**Comment by pedrobaeza** [comment]
Well, I haven't experimented that problem with longer times of PoS load than a minute, but I can't go deeper. I let the issue then opened.

**Comment by gustavovalverde** [comment]
By the way, this works flawlessly with **workers=0**. But that's not an option in production.

**Comment by andrp92** [comment]
Same has happend to me. Is good to mention that when wokers are set to 0 (multithreaded mode), I don't have this problem.

**Comment by blaggacao** [comment]
workers timouts? memory limits?

**Comment by gustavovalverde** [comment]
Just as a reference:

```yaml
limit_memory_hard = 5368709120
limit_memory_soft = 4294967296
limit_time_cpu = 1200
limit_time_real = 2200
limit_time_real_cron = 3200
max_cron_threads = 3
workers = 7
```

Memory limit is not being hit (not even near 70%). All scenarios are crashing after 50s

**Comment by blaggacao** [comment]
I want to know the answer!

**Comment by gustavovalverde** [comment]
opw-2086968

**Comment by rim-odoo** [comment]
This question does not make sense: when loaded with ``--workers=n`` (with _n_ > 0), Odoo spawns _n_ workers dedicated to your regular usage + 1 specific worker dedicated to the long-polling (that specific worker is furthermore running on a specific port -- 8071 by default).

How can the long polling time out interfere with your "regular" Odoo workers?

This issue is probably due to a problem in your deployment or another issue that breaks the loading of ``https://<URL>/web/dataset/call_kw/res.partner/search_read``
By the way, in your screenshot, the call to ``search_read`` was returned with an HTTP-200 status code, even though a traceback might be the payload of that call (but we can't see it...).

Please follow the usual steps to report a bug:
- on a standard install
- with no custom modules
- detailed steps to reproduce the issue
- please post the relevant log excerpts

Thanks.

**Comment by blaggacao** [comment]
@gustavovalverde You could try with latest DockeryOdoo it isolates the longpolling in a complete separated docker (just to bullet proof what @rim-odoo said about interference...)

**Comment by gustavovalverde** [comment]
Following up on this issue.

This is a deployment issue on **multi-tenant** environments. I'll be opening a new issue as this a "grey zone" on deployments. I've seen a bunch of information on the subject (official and non-official) about using tools like pgbouncer, but this is practical if used in `transaction` mode, which completely breaks Odoo's longpolling functionality (causing issues like the one presented here).

**Comment by nilshamerlinck** [comment]
Hi @gustavovalverde to use pgbouncer in transaction mode while keeping longpolling functional, you can have a look at [`bus_alt_connection`](https://github.com/OCA/server-tools/blob/e6e75bd8148d2abd4cef80f164d83d7bd6c218ce/bus_alt_connection/README.rst)

**Comment by blaggacao** [comment]
With a little luck, pgbouncer might migrate into the reverse proxy realm. There is a research document propoding to add connection pooling to envoy proxy.

**Comment by fjouatte2** [comment]
In 14.0 EE we have the same behaviour, multiprocess mode, 100K+ customers and POS crashing on `load_partners`. Switching to multithread mode(i.e. workers = 0) make it works.
@gustavovalverde did you find any appropriate solution ?
