### ISSUE TITLE
[v8.0] Journal entry manual posting shoud keep date from previous entry

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3843]
How to reproduce:
Create a new entry from Journal items menu chang the date to the 15/10/2014 for ex. and create a 2 lines to balance the entry.
Press Enter and start a new line (it will be a new entry as well / new move). 

Problem : on this new entry the date is by default the 1st day of the selected period. This is not ergonomic and slow down manual posting -> accounting system usually keep the same date (than the previous move) 

see below:

![1](https://cloud.githubusercontent.com/assets/5735158/5166813/6f6baea6-73f3-11e4-89af-bcc968c9ac3d.png)

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
