### ISSUE TITLE
duplicated README.md and module description

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#3846]
Modules like **stock** have two READMEs: a new `README.md` file, and the old description in `__openerp__.py`.

That seems a bit confusing, Is it intentional? If we delete the description from `__openerp__.py`, the `README.md` will be taken in automatically.

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your report.
There is indeed a `readme.md` and a description in `__openerp__.py`.
@mart-e can you give feedback? I believe this is intentional.

**Comment by mart-e** [comment]
The readme is usually the long description for the [app store](https://www.odoo.com/apps) and the manifest the short one to display in Odoo itself.
It is true that having two descriptions is a bit redundant and I would accept PR removing the one in the manifest in master.
