### ISSUE TITLE
[8.0] Supplier invoice number not propagated into journal entry

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#3847]
![1_supplier_invoice](https://cloud.githubusercontent.com/assets/5735158/5168499/f114a23a-73ff-11e4-81be-f1420ce87bb4.png)

![2_supplier_invoice_journal_entry](https://cloud.githubusercontent.com/assets/5735158/5168503/f896e89c-73ff-11e4-8542-8c52aa905985.png)

Without this reference it will be almost impossible to match with payment.

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
