### ISSUE TITLE
Warehouse configuration menu items disappear when activating 'Track lots or serial numbers' option

### ISSUE THREAD

**Issue by franckbret** [odoo/odoo#3849]
**Warehouse configuration menu items disappear when activating 'Track lots or serial numbers' option on warehouse configuration options page**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. start with a fresh db
2. as the 'admin' user install 'warehouse management' module
3. go to 'settings/configuration/warehouse' and check the 'Track lots or serial numbers' option
4. go to 'warehouse/configuration'

Current behavior:
- 'warehouse/configuration/warehouses' menu item is not there
- 'warehouse/configuration/locations' menu item is not there

Expected behavior:
- 'warehouse/configuration/warehouses' menu item should be there to configure new warehouses
- 'warehouse/configuration/locations menu item should be there to configure new stock locations

Additional notes : 
If you add technical feature to the admin user the first the item disappear, sometime the missing items menu can reappear.
If you deactivate the previously checked the 'Track lots or serial numbers' option the missing items are not coming back...

On master branch the bug is quite the same with the difference that you must add 'technical features right' to the user to see warehouse and location menu item (they are hierarchically displayed in master)

**Comment by cor9003** [comment]
Hello, I have the same issue. ANny solution or workaround ?. I don´t knw how display the location list

**Comment by johns10** [comment]
I went to views and looked up the warehouse configuration menu item in views, and edited it and saved it - it came back.

**Comment by Yenthe666** [comment]
Hi @franckbret,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
