### ISSUE TITLE
action_stock_invoice_onshipping missing on stock.picking

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#385]
https://bugs.launchpad.net/ocb-addons/+bug/1108228

Invoicing multiple lines in "Deliveries to Invoice" is not possible because of a missing action:

Action: missing on stock.picking
Model: stock.picking

This action exists on stock.picking.in and stock.picking.out but not on stock.picking.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
