### ISSUE TITLE
Field with many2many_checkboxes widget no refresh if the domain change

### ISSUE THREAD

**Issue by cmayo** [odoo/odoo#38509]
**Impacted versions:**

11, 12

**Steps to reproduce:**

This is an example of a view form:

    <field name="ref_id"/>
    <field name="some_field_ids" widget="many2many_checkboxes" domain="[('ref_id','=',ref_id)]"/>

**Current behavior:**

If the `ref_id` field changes, the `some_field_ids` field still show first loaded records. It not refresh the view and not show the records according the new domain value.

**Expected behavior:**

The view of the widget should be refreshed according the new value for the domain. It works as this in previous Odoo version like 10 or 9.

In those versions, in the `form_relational_widget.js` file, the `FieldMany2ManyCheckBoxes` field is listening to the _view_content_has_changed_ event and set the new value for the domain. But now, in Odoo 11 or 12,  I can't find any listening event like this in the `FieldMany2ManyCheckBoxes` field definition.

**Comment by agentdeu** [comment]
@cmayo @pedrobaeza 
We fixed this with the following changes:
```diff --git a/addons/web/static/src/js/fields/relational_fields.js b/addons/web/static/src/js/fields/relational_fields.js
index 2f92ad737d3..e517419e5e1 100644
--- a/addons/web/static/src/js/fields/relational_fields.js
+++ b/addons/web/static/src/js/fields/relational_fields.js
@@ -1944,19 +1944,23 @@ var FieldMany2ManyCheckBoxes = AbstractField.extend({
     //--------------------------------------------------------------------------

     /**
+     * @override
      * @private
      */
-    _render: function () {
-        var self = this;
-        this._super.apply(this, arguments);
+    _renderEdit: function () {
+        this.m2mValues = this.record.specialData[this.name];
+        this.renderElement();
         _.each(this.value.res_ids, function (id) {
             self.$('input[data-record-id="' + id + '"]').prop('checked', true);
         });
     },
     /**
+     * @override
      * @private
      */
     _renderReadonly: function () {
+        this.m2mValues = this.record.specialData[this.name];
+        this.renderElement();
         this.$("input").prop("disabled", true);
     },
```

**Comment by pedrobaeza** [comment]
Thanks for providing that patch. Maybe you can provide a pull request with that changes?

**Comment by cmayo** [comment]
I confirm that those changes fix the problem of this issue. Thanks

**Comment by pedrobaeza** [comment]
@ged-odoo would you consider a PR with that changes?

**Comment by cmayo** [comment]
Can I make a pull request for this?

**Comment by pedrobaeza** [comment]
Yes, please, let's see if this speed up the solution, but technically I haven't checked if it's correct.

**Comment by cmayo** [comment]
Ok, this issue affects to 11, 12 and 13 so, by which version do I make the pull request? 11?

**Comment by pedrobaeza** [comment]
Yes, you can do it on 11.0, and if the patch changes too much in upper versions, then repeat it on that version. If not, there's a bot for applying automatically to that versions.
