### ISSUE TITLE
[8.0] wkhtmltopdf 0.12.1 fails with error code -6 bad_alloc

### ISSUE THREAD

**Issue by cv-clearcorp** [odoo/odoo#3850]
I am using wkhtmltopdf 0.12.1 from wkhtmltopdf.org.
When I try to print a webkit report on v8.0 I have this error on the screen:
```
Wkhtmltopdf falló (error code: -6). Mensaje: terminate called after throwing an instance of 'St9bad_alloc'
what(): std::bad_alloc
```
I tried running the same command in the console. The command that odoo is trying to run is:

    /usr/local/bin/wkhtmltopdf --cookie session_id 80ded140e2dd320700fa7686b2787d2bee159d30 --quiet --page-size A4 --margin-top 40 --dpi 90 --header-spacing 35 --margin-left 7 --margin-bottom 23 --margin-right 7 --orientation Portrait --header-html /tmp/report.header.tmp.6VJOkP.html --footer-html /tmp/report.footer.tmp.zB_m7Q.html /tmp/report.body.tmp.cnet9z.html /tmp/report.tmp.ka2xTt.pdf

So I kept the temp files and ran it on the terminal with the same user that is running the instance. The PDF was generated successfully, no errors whatsoever.
I am running odoo with several workers.

**Comment by geekrohit** [comment]
+1 Same issue. Running 8.0 . And pdf can be generated easily from tmp files, but somehow from interface it fails.

**Comment by sle-odoo** [comment]
Hi,
What OS are you runnnig? Do you start Odoo with workers?

**Comment by sle-odoo** [comment]
@cv-clearcorp you are talking about printing a webkit report but is it working with qweb report? (the default invoice for example)

**Comment by busel7** [comment]
Same here, I install Odoo 8 on Raspberry with ARMHF architectur. wkhtmltopdf always fail.

Message when i Print to pdf from Odoo:
-----------------
Report (PDF)

Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display

**Comment by cubells** [comment]
@busel7 You need wkhtmltopdf with patched QT.

See what I have:
$ wkhtmltopdf -V
wkhtmltopdf 0.12.1 (with patched qt)

**Comment by busel7** [comment]
@cubells where can I get wkhtmltopdf 0.12.1 (with patched qt) package?

**Comment by cubells** [comment]
I'l got it from here:
http://wkhtmltopdf.org/downloads.html
but I have debian/ubuntu servers.

**Comment by busel7** [comment]
I've tried, but it does not support, because my machine use Debian for raspberry, has a different architecture.

**Comment by cubells** [comment]
You'll have to compile from source.

Example: http://natepinchot.com/2014/01/31/building-static-wkhtmltopdf/

**Comment by busel7** [comment]
After all day compiling finaly I can print to pdf on my raspberry pi 2, thank you Mr.@cubells for your guide, following which I have done:

1. Remove wkhtmltopdf and related package
$ sudo apt-get remove libqt4-dev qt4-dev-tools wkhtmltopdf

$ sudo apt-get autoremove

2. Install requirement package for compiling
$ sudo apt-get install openssl build-essential libssl-dev libxrender-dev git-core libx11-dev libxext-dev libfontconfig1-dev libfreetype6-dev fontconfig

3. Clone from git wkhtmltopdf and qt source
$ git clone git://github.com/wkhtmltopdf/wkhtmltopdf.git wkhtmltopdf

$ mkdir qt-wkhtmltopdf && cd qt-wkhtmltopdf

$ git clone https://www.github.com/wkhtmltopdf/qt --depth 1 --branch wk_4.8.7 --single-branch .

4. Compile qt
$ sudo ./configure -nomake tools,examples,demos,docs,translations -opensource -prefix "`pwd`" `cat ../wkhtmltopdf/static_qt_conf_base ../wkhtmltopdf/static_qt_conf_linux | sed -re '/^#/ d' | tr '\n' ' '`

$ sudo make

$ sudo make install

5. Compile wkhtmltopdf
$ cd ../wkhtmltopdf

$ sudo ../qt-wkhtmltopdf/bin/qmake

$ sudo make

$ sudo make install

6. Reboot
$ sudo reboot

**Comment by Amit-Parik** [comment]
I think issue is when you start odoo with multiple workers , it fails to print qweb report..
We have removed the workers and it works fine, but Is there any solution that wkhtml works with multiple workers?

**Comment by bistaray** [comment]
Also having the problem with workers > 1 on v9.

Webkit installed is wkhtmltopdf 0.12.1 (with patched qt)

**Comment by twinklebob** [comment]
Why was this closed? I see no resolution to the issue involving multiple workers and wkhtmltopdf?

I've got `wkhtmltopdf 0.12.2.1 (with patched qt)` and 2 workers and I'm getting the same error:

```
Wkhtmltopdf failed (error code: -6). Message: terminate called after throwing an instance of 'St9bad_alloc'
what(): std::bad_alloc
```

Can anyone tell me what I can do, short of going back to 1 worker and crippling the longpolling?

**Comment by Yenthe666** [comment]
@twinklebob don't use 0.12.2.1, use version 0.12.1 instead.

**Comment by twinklebob** [comment]
Thanks @Yenthe666, I'll give that a try. Can't see a deb for jessie at http://download.gna.org/wkhtmltopdf/0.12/0.12.1/, do you know which would be the best alternative?

**Comment by sle-odoo** [comment]
There' s ours on [nightly](http://nightly.odoo.com/extra/)

**Comment by twinklebob** [comment]
I'm still getting the same behaviour with 2 workers and version 0.12.1.2

**Comment by sle-odoo** [comment]
@twinklebob there should not be any issue regarding wkhtmltopdf and the worker mode. If you could detail your setup and you configuration i could try to reproduce it at my end.

**Comment by twinklebob** [comment]
Thanks @sle-odoo. I'm using the [turnkey linux image ](https://www.turnkeylinux.org/odoo) on an AWS T2.micro (1GB RAM, 1vCPU and 10G rootfs).

If I set workers to anything above 0 the PDF generation fails with that message.

```
workers = 2
max_cron_threads = 1
limit_time_cpu = 60
limit_time_real = 170
limit_memory_soft = 255652815
limit_memory_hard = 1395864371
limit_request = 8196
osv_memory_count_limit = False
osv_memory_age_limit = 1.0
```

Let me know if you need any more detail from me.

**Comment by twinklebob** [comment]
Is it actually as simple as the machine running out of memory in that moment?

**Comment by sle-odoo** [comment]
you better have a look with htop of odoo in threaded mode, in worker mode and in worker mode when printing a report to have an overview of the memory and cpu used

**Comment by bistaray** [comment]
I resolved this by increasing the memory available to workers.

**Comment by NRamakrishna** [comment]
@bistaray, please let me know how to increase the memory to the available workers.

**Comment by bistaray** [comment]
https://www.odoo.com/forum/help-1/question/openerp-v8-wkhtmltopdf-0-12-0-error-bug-52041
