### ISSUE TITLE
[13] hr.employee phone field marked as readn only

### ISSUE THREAD

**Issue by daniespejel** [odoo/odoo#38518]
Impacted versions: 13.0

Steps to reproduce: edit private employee info (tested on local server and latest runbot)

Current behavior: phone field is read only

Expected behavior: field should be editable

Video/Screenshot link (optional):
![imagen](https://user-images.githubusercontent.com/14876947/66659849-cfff8100-ec09-11e9-9867-253eb6956518.png)

**Comment by pedrobaeza** [comment]
That field is a related one to the address you have selected. In fact, I would say the contrary: all the fields should be readonly, or they confuse the user doing a change in the employee form, but actually changing the associated partner.

Tagging any way for being discussed with Odoo team.
