### ISSUE TITLE
[all] Command line "--logfile" can't disable config file "logfile"

### ISSUE THREAD

**Issue by dannyadair** [odoo/odoo#3852]
https://github.com/odoo/odoo/blob/8.0/openerp/tools/config.py#L386

For the 'logfile' configuration parameter, the strings 'None' and 'False' are converted to a boolean, but the following block reads the command line parameter overrides as-is. That means

```
--logfile=None
```

will create a file "None" and log to it.

I believe the logfile/pidfile conversions need to be done after the command line parameter overrides.

See also https://www.odoo.com/forum/help-1/question/disable-logfile-from-command-line-68282

**Comment by dannyadair** [comment]
The commits that were made since I opened this ticket did not solve the issue.
Here's an example call - the file odoo-server.conf specifies a valid log file that I want to disable for the "update all" call:

[ubuntu@odooci-danny-test-app] sudo: HOME=/opt/odoo /opt/odoo/odoo/openerp-server -c /etc/odoo/odoo-server.conf -u all -d MigrationTarget --logfile=None --stop-after-init

[ubuntu@odooci-danny-test-app] out: ERROR: couldn't create the logfile directory. Logging to the standard output.

**Comment by xmo-odoo** [comment]
`--logfile=` without a value should do what you want.

**Comment by dannyadair** [comment]
Sorry, it doesn't. `--logfile=` leads to no output at all. I want logging to stdout but not to file.

**Comment by dannyadair** [comment]
The issue arises when I want to override the config file setting in the command line. That is something that seems to work with all parameters but not this one...

Steps to replicate:

A) command line "--logfile" only works:
 - DON'T specify "logfile" parameter in config file
 - run openerp-server with "-c yourconfigfile" and "--logfile=None"
 - as exepected, it logs only to stdout

B) config file "logfile" only works:
 - specify "logfile" parameter in config file
 - run openerp-server with "-c yourconfigfile"
 - as exepected, it logs to file and not to stdout (this is a good setup for production)

C) I) override with None/False doesn't work:
 - specify "logfile" parameter in config file
 - run openerp-server with "-c yourconfigfile" BUT ALSO "--logfile=None" (or False) to override the config file setting
 - expected: "logfile" parameter from config file is overridden, now that no logfile is used, logging goes to stdout
 - instead: string "None" ("False") seems to be taken literally - either "ERROR: couldn't create the logfile directory. Logging to the standard output." or logfile by that name is written (depending on file permissions in current directory)

D) II) override with blank parameter doesn't work:
 - specify "logfile" parameter in config file
 - run openerp-server with "-c yourconfigfile" BUT ALSO "--logfile=" to override the config file setting
 - expected: "logfile" parameter from config file is overridden, now that no logfile is used, logging goes to stdout
 - instead: no logging at all

Dirty workaround: specify "--logfile=/notallowedtowrite.log" and let Odoo fall back to stdout logging due to file permission problem.

**Comment by dannyadair** [comment]
I think this is the reason:

openerp/tools/config.py:

```python
        # Verify that we want to log or not, if not the output will go to stdout
        if self.options['logfile'] in ('None', 'False'):
            self.options['logfile'] = False
```

C) I) and C) II):
At this point the command line isn't parsed yet, and "logfile" is an actual filepath from the config file, so nothing happens.

Just a couple of lines down:

```python
        for arg in keys:
            # Copy the command-line argument (except the special case for log_handler, due to
            # action=append requiring a real default, so we cannot use the my_default workaround)
            if getattr(opt, arg):
                self.options[arg] = getattr(opt, arg)
```

'logfile' is one of those keys getting looked up in the command line opts.

C) I):
The filepath from the config file is overridden with the literal string from the command line, and now Odoo is told to write to logfile named "None" or "False". (which it may or may not be allowed in the current working directory)

C) II):
The command line option 'logfile' was given, but because it's an empty string its boolean value is False, and the option won't be overriden. It's still the filepath from the config file.

openerp/netsv.py:

```python
    if tools.config['syslog']:
        ...
    elif tools.config['logfile']:
        ...
```

**Comment by dannyadair** [comment]
Long story short: openerp-server offers a command line parameter "--logfile" but it only works if you don't use -c with a config file that also defines "logfile"

**Comment by dannyadair** [comment]
P.S.: Renamed this issue for clarification. If the config file says logfile=None then the command line _can_ specify a file and that indeed will be used correctly. It just can't be the other way around - overriding to None via command line not possible.

**Comment by leorochael** [comment]
As a workaround, on linux, you can do: `--logfile=/proc/self/fd/1`

**Comment by Yenthe666** [comment]
Hi @dannyadair,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by holdenrehg** [comment]
For reference @Yenthe666 , this is still an issue even on the current build of `master` (I'm working on an Ubuntu machine).

I ran into this while running tests. I wanted to use the existing `odoo.conf` file while overriding just a few parameters. One of which was forcing log output to stdout.

```sh
$ /odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf --xmlrpc-port=9999 --longpolling-port=9998 --test-enable --stop-after-init --logfile= --log-level=info --log-handler=:INFO -d demo -i my_module
```

All of the comments on this PR do still apply on the current Odoo builds too:

- Adding `logfile=None` or `logfile=False` will just create respective files called `None` or `False.
- Adding `logfile=` will just use the original `odoo.conf` values instead of overriding with a blank value.
- Using `logfile=/proc/self/fd/1` is a temporary workaround for Linux.

**Comment by Yenthe666** [comment]
Hmm, I've actually just reproduced this on an Odoo 13.0 instance. Thanks for those pointers @holdenrehg!
@mart-e who could look at this?

**Comment by mart-e** [comment]
@Julien00859 could you have a look? We have a hack for [the config file](https://github.com/odoo/odoo/blob/9e72590ad7b601f41d0ed5796728492f45dec63a/odoo/tools/config.py#L410-L412) of `logfile=False` but not for the command line.

**Comment by Julien00859** [comment]
Ok

**Comment by holdenrehg** [comment]
:tada:
