### ISSUE TITLE
Odoo 13 Bug After Installation (windows , linux)

### ISSUE THREAD

**Issue by turkimaki** [odoo/odoo#38531]
Hello after installation of odoo 13 in Windows and also on linux  I get those problem :

I can't reach general settings or user/company
I can't also see the version of installed all the menu settting not appear.
I can't update my liste apps the menu doesn't exist when I click on Apps + mode debug
In Odoo 13 Windows the installer show that is odoo 12 but the installation is for 13 and after installation I found the new apps like time off or export to excel but i can't work on odoo 13.

Please need help thanks for all the team .

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
