### ISSUE TITLE
Deleting a language doesn't remove the res.partner default language.

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3854]
1. Create a language
2. Set it as default through settings->actions->User-defined actions->default language
3. Delete the language
4. Try to create a new partner

This means we can't add new partners.

**Comment by kurkop** [comment]
I can see this error in Odoo v10, is necessary change in ir.values the record with id 

```
UPDATE public.ir_values
   SET value='S''es_CO''
p1
.'
 WHERE id=1;
```

Odoo should change this value when uninstall a language.

**Comment by mart-e** [comment]
Hello,

Sorry but if you manually create a language, manually specify it as the default then delete it, I don't see why you can' t change the default too?
Sorry but these steps looks like you are looking to break the system...
