### ISSUE TITLE
[13.0] Binary fields can not be added to contact forms because of website_crm

### ISSUE THREAD

**Issue by feelwhy** [odoo/odoo#38559]
Impacted versions:
13.0

Steps to reproduce:
1. Add a binary field (with file name field) to the model crm.lead
2. Add binary input to contact us form (/contactus)
3. Fill this field with a file
4. Send a form

Current behavior:
1. Lead is created with an empty binary field but with correctly set filename

Expected behavior:
1. Binary field and its filename should be correctly filled)

Possible reasons
The commit -https://github.com/odoo/odoo/commit/20fb024a33b3ceed2a1a41f65a315477699378de:
- the method extract_data is called twice: in website_crm/controllers/main - the method website_form, and in its super - in the website_form
- hence, the method read() of a file is called twice. But the second time it results in empty binary, since read() changes state of the file. Have a look for example, at: https://stackoverflow.com/questions/3906137/why-cant-i-call-read-twice-on-an-open-file.

Extra comments
- Beside, the bug itself: it seems not optimal to call the method extract_data twice. A possible solution is to call super at the beginning of the method website_form of website_crm and use already extracted data to make phone validation.
- Try / except seems unreasonable contruction since if it fails here, it should also fail in super. Perhaps, it is somehow linked to dependancies, so not totally sure

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by feelwhy** [comment]
Just pulled the latest Odoo 13: to this moment it is the same. 
Binary is read still twice, and hence it is not parsed from the form.

**Comment by GeertSurkijn** [comment]
When I use the form builder and relate it to the task model it is working. When I relate it to opportunity / leads it isn't.

**Comment by gustavovalverde** [comment]
Having the same issue when adding an attachment to a contact through the Form Builder.
