### ISSUE TITLE
[13.0] Employee: Equipments smart button counter not work.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38557]
**Impacted versions:**

1. Odoo 13.0

**Steps to reproduce:**

1. Go to Employees > Create Employee. Than
2. Go to Maintenance > Equipment > Create Equipments > but not forget to select employee which you have created.
3. Than got to employee and check Equipment smart button counter. 

**Current behaviour:**

1. Equipment smart button counter not work properly in employee.
![equipemployee1 - Odoo](https://user-images.githubusercontent.com/24518821/66697146-a8371880-ecf0-11e9-9c63-d5684d29a611.png)

![equipemployee2 - Odoo](https://user-images.githubusercontent.com/24518821/66697151-ad946300-ecf0-11e9-97b7-56f77010a03d.png)

**Expected behaviour:**

1. It should count proper equipment for employee.

**Video/Screenshot link (optional):**

![equip](https://user-images.githubusercontent.com/24518821/66697189-f4825880-ecf0-11e9-84c3-dbd88aa47f79.gif)

**Comment by LucasLefevre** [comment]
Fix merged at 07bd725
