### ISSUE TITLE
[12.0][13.0] Maintenance: State should not be copied on duplicate.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38558]
**Impacted versions:**

1. Odoo 12.0
2. Odoo 13.0

**Steps to reproduce:**

1. Go to Maintenance > Maintenance Requests  > Create  new maintenance > Change state to In progress.> duplicate the record. 

**Current behaviour:**

1. State should be copied on duplicate.

**Expected behaviour:**

1. State should not be copied on duplicate.state should be "New Request".

**Video/Screenshot link (optional):**
![Maintenance](https://user-images.githubusercontent.com/24518821/66697892-2eeef400-ecf7-11e9-8d5a-2861b50be890.gif)

**Comment by Yenthe666** [comment]
Hmm, I agree with you and I think it should be changed. I made a PR at https://github.com/odoo/odoo/pull/38573 - let's see if Odoo agrees.

**Comment by KapilPatel-KP** [comment]
@Yenthe666 Thanks 👌😊

**Comment by KapilPatel-KP** [comment]
I can reproduce the same on v11 also.
