### ISSUE TITLE
Salesman can not see validated invoice for access error

### ISSUE THREAD

**Issue by feiyu4581** [odoo/odoo#3855]
version: odoo 8.0 latest
Step to reproduce:

> 1. Create a new user with 'See Own Leads'
> 2. Log in with this user and create a new quoation, confirm it and create invoice
> 3. Log in with admin and validated the invoice
> 4. Log in with the new user with 'See Own Leads', open the sales order and click the button 'View Invoice'

expected result:
The invoice should be open
result:
read access error
![qq 20141125112225](https://cloud.githubusercontent.com/assets/2360288/5177560/3175ce58-7496-11e4-984b-2ab92a098efb.jpg)
Solution

> access_account_move_salesman,account.move invoice,account.model_account_move,base.group_sale_salesman,1,0,0,0

in addons/sale/security/ir.model.access.csv

**Comment by Yenthe666** [comment]
Hi @feiyu4581,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
