### ISSUE TITLE
Expired price becomes 0 (zero)

### ISSUE THREAD

**Issue by tuantrankim** [odoo/odoo#38560]
Impacted versions: Odoo 12.0

Steps to reproduce: 
- Add a new price list item with a fix price and set an end date
- The price show correctly on shop page
- Update end date to a past date
- The price show 0 (zero) on shop page

Current behavior:
- The price show 0 (zero) on shop page

Expected behavior:
- Next price list item should be applied (e.g. : all products)

Video/Screenshot link (optional):
![bug](https://user-images.githubusercontent.com/3781959/66708354-281aae00-ed04-11e9-86fe-85f5845b7ed2.png)

**Comment by pedrobaeza** [comment]
@dbo-odoo maybe this is a similar case to #30453
