### ISSUE TITLE
[13.0] Text on the web_ribbon widget is not translated.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#38568]
Impacted versions:
13.0

Expected behavior:
Text on the web_ribbon widget is translatable.

Video/Screenshot link (optional):
<img width="1022" alt="WX20191013-170850@2x" src="https://user-images.githubusercontent.com/5561864/66713337-320fe000-eddc-11e9-93bd-9f7544c07fed.png">

**Comment by Yenthe666** [comment]
@JKE-be this does indeed seem to be the case. Can you check?

**Comment by JKE-be** [comment]
Probably for @mart-e

**Comment by Yenthe666** [comment]
Wow, I was thinking Martin and pinged you, sorry 😆

**Comment by mart-e** [comment]
@tivisse is there a reason to use the format `<widget name="web_ribbon" text="Archived" />` for ribbon?
If we had used something like `<span widget="web_ribbon" value="Archived" />` nothing was needed to be done for translation

**Comment by tanghulu0608** [comment]
<span widget="web_ribbon" value="Archived" />

I like this format very much.😁

**Comment by tanghulu0608** [comment]
@tivisse  Any solution to this issue?

**Comment by tivisse** [comment]
Hi. The ribbons have been developed by @pko-odoo , even if I merged a skeleton of it to use it in another feature branch before him.

@pko-odoo Could you please check this issue ?

Thanks.

**Comment by tivisse** [comment]
@mart-e Concerning:
> @tivisse is there a reason to use the format `<widget name="web_ribbon" text="Archived" />` for 
ribbon?
> If we had used something like `<span widget="web_ribbon" value="Archived" />` nothing was needed to be done for translation

What do you mean ? ``widget="foo"`` only works for ``<field/>`` tags if I'm not wrong.

**Comment by Yenthe666** [comment]
Guys, can we just come to a conclusion/fix? It's been almost two months.

**Comment by tanghulu0608** [comment]
web_ribbon widget is very cool. It's better to make the text can be translated.

**Comment by tanghulu0608** [comment]
@nim-odoo  Good job.

**Comment by Yenthe666** [comment]
Here's the other commit https://github.com/odoo/odoo/commit/924b63c1abe8bc8696b4b22dedcaca4b398c10b6 that updates all the widgets.

**Comment by tanghulu0608** [comment]
@Yenthe666  Thanks
