### ISSUE TITLE
[13.0] Event : Trackback when printing Registration Badge for an Attendee

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38564]
Impacted versions: 13.0

Steps to reproduce:
- Create Event,
- Go to Attendee smart button
- Create Attendee and save.
- Click on Print > Registration Badge.

Current behavior:
- Trackback when printing Registration Badge.

Expected behavior:
- It should handle/print it properly. 

Video/Screenshot link (optional):
[Video ref](https://youtu.be/Hamn4JLBBfY)
[Screenshot](http://tinyurl.com/yymerkc5)

**Comment by sswapnesh** [comment]
Hello @dipsshah42  
This was happening only when there is no **Attendee Name** there, I made fix for v11 at https://github.com/odoo/odoo/pull/38582 (This bug was present there too)
