### ISSUE TITLE
[13.0][WISH] Event : attendee kanban card showing blank.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38565]
Impacted versions: 13.0

Steps to reproduce:
- Go to event > Create it > go to attendee > create and save without entering anything
- Go to a kanban view of the attendee.

Current behavior:
- Its showing blank Card/box of kanban.

Expected behavior:
- Either it should not allow saving blank attendees. or make Attendee name mandatory if possible.

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/yxuq2myk)

Somewhat related to this issue #38564

**Comment by sswapnesh** [comment]
@tde-banana-odoo  Can we please make `Attendee Name` required in v13 at least? (On XML)

We won't need  https://github.com/odoo/odoo/pull/38582 if it is required 
(or we should make it required for v14 from python side)

**Comment by sswapnesh** [comment]
@mart-e  Based on Discussion made on https://github.com/odoo/odoo/pull/38767, I don't think this will be Improved on v13.
https://github.com/odoo/odoo/pull/38767#issuecomment-542106556 
Cc @mart-e

**Comment by mart-e** [comment]
@sswapnesh in 13.0, we could accept the change with XML but will see what the feedback says first (regarding the need of anonymous registration or not)
Cc @sswapnesh

**Comment by sswapnesh** [comment]
We won't need https://github.com/odoo/odoo/pull/38767 If we are gonna make that required in v13.

**Comment by mart-e** [comment]
Indeed it is not required but it is not bad to keep it. When migrating databases, it is frequent we are not able to add required constraint (due to previous records), this way, it still works on database that were not able to add the `not null`.

**Comment by sswapnesh** [comment]
@mart-e  Any Feedback? (or yet to get )

**Comment by tde-banana-odoo** [comment]
Name is required in 13.3+ https://github.com/odoo/odoo/commit/14ce43f2eec7f26fd59c9647f0d4a2b838eb3a4b .

**Comment by sswapnesh** [comment]
This one can be closed as it is already Improved in Upper version.
