### ISSUE TITLE
[13.0] Event : In Location name field should be mandatory.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38566]
Impacted versions: 13.0

Steps to reproduce:
- Go to event > Configuration > Locations.
- Create it.

Current behavior:
- It allows saving blank record. 

Expected behavior:
- as we can see everywhere in the odoo interface, Same here also Name field should be mandatory in Event Location. 

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/yyzxua46)

**Comment by Yenthe666** [comment]
Confirmed, I made a fix at https://github.com/odoo/odoo/pull/38571

**Comment by sswapnesh** [comment]
This has been fixed in #38571
