### ISSUE TITLE
[13.0] Event : Event Tracks > Kanban state field in form not showing properly. Overlapped.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38567]
Impacted versions: 13.0

Steps to reproduce:

- Go to Event App > Event tracks menu,
- Create new > in form view > Click on Kanban state field (Having values like > Gray , Red, Green ).

Current behavior:
- It overlapping with Sheet. so not able to see it properly.

Expected behavior:
- The small selection box of that field should open either right side so that we can select state's value properly.

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/y65q7a4b)

**Comment by sswapnesh** [comment]
@dipsshah42  Added fix at https://github.com/odoo/odoo/pull/47123
