### ISSUE TITLE
Warehouse staff can not finish full purchase receipt

### ISSUE THREAD

**Issue by feiyu4581** [odoo/odoo#3856]
version: odoo 8.0 latest
Step to reproduce:

> 1.Create a user with 'Warehouse user'
> 
> 2.Log in with admin, create and confirm a purchase order
> 
> 3.Log in with the new user, click Warehouse/All Operations/YourCompany: Receipts/Ready, then open the picking associate with the new purchase order and click the Transfer, Apply it

expected result:

> The picking finish full purchase receipt

result:

> accessError

![qq 20141125121716](https://cloud.githubusercontent.com/assets/2360288/5178204/aae5ca52-74a2-11e4-9408-cfb0793124d3.jpg)

Solution:

> access_purchase_order_stock_worker,purchase.order,model_purchase_order,stock.group_stock_user,1,1,0,0

replace it in addons/purchase/security/ir.model.access.csv line 10

**Comment by Yenthe666** [comment]
Hi @feiyu4581,

This indeed seems like a misconfiguration of rights for the user.
As Odoo 8 is no longer supported this can be closed.

Regards,
Yenthe
