### ISSUE TITLE
[13.0]Fleet: TypeError: Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38575]
**Impacted versions:**
1. Odoo 13.0

**Steps to reproduce:**

1. Fleet > Vehicles > Open Any Vehicles > Click o service Smart button > Create > Enter details > Put Odometer Value as it is 0.0 > add Included Services line> than save > one warning raise. > click okay > in  Included Services click to one2many field lable.

**Current behaviour:**

1. Giving traceback error "TypeError: Cannot read property 'length' of undefined."
![Nffew - Odoo](https://user-images.githubusercontent.com/24518821/66714860-e1978300-edd9-11e9-84b9-ab61dda5f626.png)

**Expected behaviour:**

1. No Traceback

**Video/Screenshot link (optional):**
![fLEET2](https://user-images.githubusercontent.com/24518821/66714865-efe59f00-edd9-11e9-972d-b6f96148c50c.gif)

**Comment by jbm-odoo** [comment]
Thanks for your feedback !
This issue is related to issue #38574 
It will be fixed by #38583

**Comment by LucasLefevre** [comment]
Merged at 7fa8037
