### ISSUE TITLE
[13.0] [Sales Module] in Customer Preview the invoice is displayed "waiting payment" even though it has been successfully paid

### ISSUE THREAD

**Issue by yousafi** [odoo/odoo#38577]
Impacted versions:
13.0
Steps to reproduce:

Current behavior:
The invoice is displayed "waiting payment" in customer preview even though the invoice is fully paid.
Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/40589224/66714986-12c08500-edd3-11e9-8e9d-234867ef2d02.png)

![image](https://user-images.githubusercontent.com/40589224/66714992-223fce00-edd3-11e9-8d1c-4b484f8a861a.png)

**Comment by Yenthe666** [comment]
This one has been fixed in the meanwhile. A few weeks ago somebody made another PR (can't directly find the link) which fixed the last state issues on the frontend.
