### ISSUE TITLE
[13.0] CRM : Partner Level should be mandatory.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38579]
Impacted versions: 13.0

Steps to reproduce:
- Go to CRM > Configuration > Partner Level.

Current behavior:
- It allows saving blank record.

Expected behavior:
- At least one field should be needed required.

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/yyvpu58y)

**Comment by Yenthe666** [comment]
I already made a PR for this one at https://github.com/odoo/odoo/pull/38211 - once it is merged this is solved too ;)

**Comment by Yenthe666** [comment]
Solved at https://github.com/odoo/odoo/commit/dfc6d3ffb6813d5e7144c6b8e34f43f01e1de4ed
