### ISSUE TITLE
[13.0]Fleet: Vehicles Services Logs Screen stuck when we click on save button.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38574]
**Impacted versions:**

1. odoo 13.0

**Steps to reproduce:**

1. Fleet > Vehicles > Open Any Vehicles > Click o service Smart button > Create > Enter details > Put Odometer Value as it is 0.0> than save > one warning raise. > click okay > 

**Current behaviour:**

1. Vehicles Services Logs Screen stuck when we click on save button, after that you can not save the record or discard or anything else.
![New - Odoo](https://user-images.githubusercontent.com/24518821/66714671-2a9a0800-edd7-11e9-80c8-156aa53ef63c.png)

**Expected behaviour:**

1. Record should be save.

**Video/Screenshot link (optional):**

![Fleet](https://user-images.githubusercontent.com/24518821/66714683-47ced680-edd7-11e9-9b24-038b53bb885f.gif)

**Comment by Yenthe666** [comment]
@mart-e under which label does fleet fall?

**Comment by sswapnesh** [comment]
This was failing due to `_get_odometer`  method

Because of  `Assigning default value for non-stored compute fields is mandatory in new ORM.`

Added fix at https://github.com/odoo/odoo/pull/38583

**Comment by mart-e** [comment]
Thanks for the patch and review !
