### ISSUE TITLE
[13.0] POS : Not able to delete POS Floor even though its not used anywhere.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38581]
Impacted versions: 13.0

Steps to reproduce:
- Go to Point of Sale
- Configuration  > Floor Plans > Create and Delete Floor Plan

Current behavior:
- It showing Warning = **You cannot remove a floor that is used in a PoS session, close the session(s) first**: 
  - But actually Floor Plan is just created.

Expected behavior:
- It should allow to delete it as it is not used anywhere.

Video/Screenshot link (optional):
[Video](https://youtu.be/4jSD48_nFTs)
[Screenshot](http://tinyurl.com/y3wrcj8w)

Thanks!

**Comment by pedrobaeza** [comment]
Have you closed the PoS session?

**Comment by sswapnesh** [comment]
> Have you closed the PoS session?

I don't think so looking at the code

https://github.com/odoo/odoo/blob/a248171d96de3ad6d8e22c855886dfae61e145e2/addons/pos_restaurant/models/pos_restaurant.py#L21-L26

From https://github.com/odoo/odoo/commit/a248171d96de3ad6d8e22c855886dfae61e145e2 commit message
```

To avoid all this consistencies, we have restricted the deletion of some
records in specific cases.
```
Cc @pimodoo

**Comment by dipsshah42** [comment]
> Have you closed the PoS session?

@pedrobaeza  No. but its actually not related with any session.as i just create it only.

**Comment by Yenthe666** [comment]
CC @switch87

**Comment by pimodoo** [comment]
@dipsshah42 You are right, for now the condition in the code checks that there are some pos config with table management activated. So we'll modify it to allow deletion if table is not used.

**Comment by pimodoo** [comment]
fixed in https://github.com/odoo/odoo/pull/38674
