### ISSUE TITLE
[12.0] Error: QWeb2 - template['mail.widget.Thread.Message']: Runtime Error: TypeError: dict.message.hasPartnerTrackings is not a function

### ISSUE THREAD

**Issue by L00N1** [odoo/odoo#38584]
I'm experiencing the following issue, where I have any relevant modules and functions for eCommerce installed. When I go to products page and click on a product, I get an error that disables me to edit any product.

Could you please help me identify the issue?

Impacted versions: 12.0

Steps to reproduce: 
Go to List of Products in any module (Sales/Inventory/Website), click on product, the error pops up:
Error:
Uncaught Error: QWeb2 - template['mail.widget.Thread']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Content']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Content.DESC']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Messages']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Message']: Runtime Error: TypeError: dict.message.hasPartnerTrackings is not a function

https://***/web/content/506-00b013f/web.assets_common.js:3374
Traceback:
Error: QWeb2 - template['mail.widget.Thread']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Content']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Content.DESC']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Messages']: Runtime Error: Error: QWeb2 - template['mail.widget.Thread.Message']: Runtime Error: TypeError: dict.message.hasPartnerTrackings is not a function
    at Object.exception (https://***/web/content/506-00b013f/web.assets_common.js:3374:7)
    at Engine.eval (eval at _render (https://***/web/content/506-00b013f/web.assets_common.js:3416:73), <anonymous>:28:29)
    at Engine._render (https://***/web/content/506-00b013f/web.assets_common.js:3415:296)
    at Engine.render (https://***/web/content/506-00b013f/web.assets_common.js:3415:151)
    at Class.render (https://***/web/content/801-825afd7/web.assets_backend.js:2899:20)
    at https://***/web/content/801-825afd7/web.assets_backend.js:2892:2307
    at https://***/web/content/506-00b013f/web.assets_common.js:802:681
    at fire (https://***/web/content/506-00b013f/web.assets_common.js:796:299)
    at Object.add [as done] (https://***/web/content/506-00b013f/web.assets_common.js:797:467)
    at Array.<anonymous> (https://***/web/content/506-00b013f/web.assets_common.js:802:649)

Current behavior:
After clicking on Edit, Error pops up and doesn't allow to edit any product.

Expected behavior:
After clicking on Edit, products should be editable

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
`template['mail.widget.Thread.Message']: Runtime Error: TypeError: dict.message.hasPartnerTrackings is not a function`

It seems from the external module.

@L00N1 Are you using any third-party module?

**Comment by L00N1** [comment]
@sswapnesh 
Thank you for looking into this.

Yes, I'm using external modules (please see screenshot).
I don't know exactly what I have changed in the settings. But in other Database2 with a very similar setup (the DB2 was duplicated from the one with error several days ago) and more external modules is working just fine.

![Odoo](https://user-images.githubusercontent.com/20923954/66721749-03a6fa80-ee06-11e9-9655-4586c910c74d.jpg)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by L00N1** [comment]
Reproduce:
With ecommerce setup:
1. Install mass_mailing
2. Deploy [mail_tracking](https://github.com/OCA/social/tree/12.0/mail_tracking) - wide load
3. Not installing mail_tracking nor [mail_tracking_mass_mailing](https://github.com/OCA/social/tree/12.0/mail_tracking_mass_mailing)
4. Go to products list
5. Select/edit any product
6. Error above

=> Installing step 3 resolves the issue.

Thanks for your time and effort.
