### ISSUE TITLE
Bug found in Company Creation

### ISSUE THREAD

**Issue by lloyd-oa** [odoo/odoo#3858]
**Company details are not saving when creating new company**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. create a new company via settings in the backend interface or sending values to the res.company create function.
2. input the name and a couple more additional fields, 
3. after clicking save you will notice only the name is saved to the database, the other values disappear and become null somehow. Only when editing the fields do they update. 

Good day, I am busy working on a latest instance of odoo downloaded from the nightly builds, I've come across a bug whereby if you create a company only the name field is updated, all other fields don't get saved when creating a new company, they only get updated if you go back in and edit the company.

Regards

Lloyd
OpenERP Africa

**Comment by Yenthe666** [comment]
Hi @lloyd-oa,

Thank you for the report.
I've just tested this on the latest Odoo 8.0 and this problem is no longer present in Odoo.
Please update your Odoo source code if you still face this issue and try again.

Regards,
Yenthe
