### ISSUE TITLE
 webkit helper.embed_logo_by_name not multicompany ready

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#386]
https://bugs.launchpad.net/ocb-addons/+bug/1112580

While it is possible to define the same logo name (with different images) in ir_header_img for different companies , no possibility (seems to) exists, to choose the correct logo in the report

the attached patch allows the following syntax

    helper.embed_logo_by_name('company_logo', None, height=70, company_id=company.id)

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
