### ISSUE TITLE
[13.0] duplicating user fails because of security rules

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#38602]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest Odoo 13.0 runbot
2. Go to Settings > Users, open a user and duplicate it

Current behavior:
Error:
![image](https://user-images.githubusercontent.com/6352350/66737699-f2450900-ee6c-11e9-8aa8-83eed796c255.png)

Expected behavior:
Ability to duplicate a user and his/her rights

**Comment by Yenthe666** [comment]
@mart-e I'm not sure who's responsible for users?

**Comment by mart-e** [comment]
@Yenthe666 nobody because there is no application "Users", it depends on what is the cause of this error. I just tired, the issue does not appear on a "base" database but well on a runbot so it is probably a side-effect of a specific module.
To investigate...

**Comment by Yenthe666** [comment]
OPW 2086661 - I decided to log it through my customers contract to get it handled.

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/37847

**Comment by Yenthe666** [comment]
Sorry I've missed that one. Perhaps it is best to close yours as I've linked mine to an OPW? It'll be most likely handled way faster as it is already in bug fixing at Odoo.

**Comment by sswapnesh** [comment]
Sure, I have added this as a reference and closed that one.

**Comment by len-odoo** [comment]
Fix was merged with its test.
