### ISSUE TITLE
Purchase Order csv import fail.

### ISSUE THREAD

**Issue by DeepSilver** [odoo/odoo#3861]
**Importing purchase.order.csv fail**
Missing required value for the field 'Order Reference' (name) 

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Go to Purchase -> Requests for Quotation -> Import cvs
with minimum required field: date_order,Supplier	name,name,partner_ref,pricelist_id/id,location_id/id,Order Lines/Product, order_line/product_qty,order_line/price_unit,order_line/date_planned
	
Current behavior:

 - Import fail with error "Missing required value for the field 'Order Reference' (name) between rows"

Expected behavior:

 - Order Reference (name) should be recognized and pass validation.

![2014-11-25_154748](https://cloud.githubusercontent.com/assets/3600848/5180375/6dc31330-74bd-11e4-8520-bf2b0bae13a2.png)

**Comment by asameer** [comment]
I faced the same error but with this simple columns
Products/Name","Products/Price"
when I removed the "Prodects/" and left the column Header just with "Name" value .
the import works with me .

**Comment by JYFInternational** [comment]
Hi, 
i try to do as your request but i cannot solve the problem.
[purchase.txt](https://github.com/odoo/odoo/files/130538/purchase.txt)
![2016-02-15_12h03_12](https://cloud.githubusercontent.com/assets/17249415/13046973/3afd73b2-d3dc-11e5-947e-4855162ef3c6.png)


Could you help me to build the template ?
thanks

**Comment by lukebranch** [comment]
@Yenthe666 ,

Sorry to ping you on this one. I've run into this issue in Version 10.0e and reported it through the enterprise support channel with ticket number: 753073

It appears that it is impossible to import purchase order lines using the following unique references:

Product Variant External ID
default_code
name

I have attempted exactly the same method in the Sales Order Lines and it works just fine, however in the purchase order lines it appears impossible to do.

This is a huge issue for some of our customers who have to import thousands of purchase order lines per document, per day.

I don't remember having the same issue in version 8.0, or 9.0 with importing purchase order lines. Any help would be appreciated.

**Comment by Masabus** [comment]
Problem seems to be still there with Odoo 12.0-20190321 community edition.

I'm unable to import order lines to specific sales order. But if i import the whole sale order with order lines then it works. 

I would need update order lines when sale order is opened and not the whole sale order itself.

This is the error always when trying to update order lines:
Missing required value for the field 'Order Reference' (order_id) at row 2 (7 more)

'Order Reference' doesn't seem to work or 'Name' doesn't work either.
