### ISSUE TITLE
Automatic Fiscal positions in Purchase Orders don't work

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#3863]
Steps to reproduce
1. Create Fiscal Position with Automatic = True (map standard purchase tax to another)
2. Create Sale Order MTO
3. Purchase Order Tax ..... not maped!!!

Similar problem if invoice is created from picking, for example in Inter Company Transit.
Function get_fiscal_position with ('auto_apply', '=', True) is used only in sale.py

**Comment by PeterA-OpusVL** [comment]
@simongoffin @sve-odoo 
Hi, I noticed this was not working for manually created POs a few months ago, and this was patched in https://github.com/odoo/odoo/commit/1062905acbb8c1dac004005b9bd7c43592a45e74

However, now I have also noticed they are not working for MTO 'generated' POs (from procurements) as @zbik2607 says. The fiscal_position field on the PO is blank, and has not been assigned the correct one based on suppliers country_id.

**Comment by PeterA-OpusVL** [comment]
It seems that onchange_partner_id is not getting hit when the PO is generated.

It does get hit, and works successfully when partner_id is manually changed on the generated PO.
