### ISSUE TITLE
[12.0,13.0] framework: unable to add more than 40 records to many2many_tags_email widget

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#38658]
Impacted versions: 12.0, 13.0 atleast

Steps to reproduce:
1. Login to the latest Odoo 12.0 and go to a view that contains a `many2many_tags_email` widget. For example by clicking on "Add followers" in the chatter of a contact.
2. Add 40 recipients in the field and now try to select another one (number 41).

Current behavior:
You're unable to add more than 40 records, they're no longer added and nothing happens.
Example on surveys:
![image](https://user-images.githubusercontent.com/6352350/66739097-42719a80-ee70-11e9-8842-c24b89854a1a.png)
Example on chatter:
![image](https://user-images.githubusercontent.com/6352350/66739224-8fee0780-ee70-11e9-9dbe-4002ef5c0c5a.png)

Expected behavior:
You're able to add more than 40 records on a `many2many_tags_email` widget, just like with other fields.

**Comment by Yenthe666** [comment]
OPW 2086666

**Comment by Yenthe666** [comment]
Sadly this has been denied by Odoo as a bug (which I honestly do not agree on but ok). Official response:

> This topic is quite controversial and I could gather different options on its merit. Firstly, please note that this behaviour is a consequence of a more general limitation on the widgets. 
More information here: https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/views/form/form_view.js#L163
This said, considering the functional purpose and intended use of the emails from the chatter, our Team has decided to not consider this as a bug, but simply as a suggestion to revaluate this feature in the future.
In fact, functionally speaking, Odoo offers another tool, which was designed to send emails to multiple people, Email Marketing.

**Comment by pedrobaeza** [comment]
That can fit only if there's a bridge between survey and mass_mailing. If not, you can argue about that.

**Comment by Yenthe666** [comment]
I know they'll still deny it as a framework limitation afterwards though, that is how they usually 'win' the support tickets. I'll let this one go as there are more important ones probably :D

**Comment by pedrobaeza** [comment]
OK, as you prefer :smiley:

**Comment by Yenthe666** [comment]
I don't want to bother & 'fight' on too many subjects haha, I'm already one of the more difficult persons I assume 🤣 Thanks for the suggestion though @pedrobaeza!

**Comment by vixrodriguez** [comment]
Well, I think that this will have no solution. (I reported this bug in the forum) :(
