### ISSUE TITLE
Windows packaging improvements

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#3868]
Laundry list of possible or desirable improvements
- [ ] sign installer with [Authenticode](http://msdn.microsoft.com/en-us/library/ie/ms537359.aspx) to try and avoid SmartScreen's dialog of death (or at least provide recognised publisher name). EV-signed gain reputation faster than non-EV signed (self-signed or unknown root) and unsigned. [See also](http://blogs.msdn.com/b/ie/archive/2012/08/14/microsoft-smartscreen-amp-extended-validation-ev-code-signing-certificates.aspx)
- [ ] geolocation, do we want it to work OOTB on windows?
  - [ ] bundle geolocation dependency
  - [ ] bundle geolocation data (does license allow bundling it?)
  - [ ] geolocation default file path should not be /usr/…
- [ ] configuration file should not be in `%PROGRAMFILES%`, it should be in `%APPDATA%`. Use `openerp.toools.appdirs` to get the right directory maybe
  - [ ] change install.rst to indicate that the file moved
- [ ] log file should not be in `%PROGRAMFILES%`, default to `logging.handlers.NTEventLogHandler` on Windows? At least store next to config file in `%APPDATA%`.
- [ ] allow passing parameters to server via service config (parameters currently ignored)
- [ ] rename various files from `openerp` to `odoo` (e.g. `openerp-server.exe`, `openerp-server.conf`)
- [ ] Odoo Server can be unselected during installation, which makes no sense
  - [ ] allow upgrading existing installation when one is detected

**Comment by Yenthe666** [comment]
@xmo-odoo is it fine to close this one? I see some more are already handled in the meanwhile. Do you want to keep it open or can we close?

**Comment by xmo-odoo** [comment]
@Yenthe666 thanks for pinging me here, I'd completely forgotten this thing existed.

I'll assign @d-fence as he's working on packaging, he'll decide what he wants of that.

**Comment by Yenthe666** [comment]
Awesome - thanks!

**Comment by d-fence** [comment]
hmmm, I'll try to not forget this wishlist :-)

**Comment by Yenthe666** [comment]
@d-fence can I ask you for an update? :)

**Comment by pedrobaeza** [comment]
@d-fence this isse has converted into one of the oldest one. Is it still relevant?

**Comment by d-fence** [comment]
Never got enough time to check all that.
Authenticode is a no go because, AFAIK, the process has to be done for each build ... every day :-)
So, I like this checklist even if I forget it each time I start to work on packaging.
I propose to keep it open

**Comment by pedrobaeza** [comment]
OK, I'll ping you in a year then :stuck_out_tongue_closed_eyes:

**Comment by d-fence** [comment]
No, I really want to improve the windows installer before the next release.
I just need a brain with more RAM
