### ISSUE TITLE
[13.0][WEB] IconWidget Not work properly

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#38693]
**Impacted versions:** 13.0

**Steps to reproduce:**
- Add Features snippet box in the homepage 
- Double click on icon and change try to change it  

**Current behavior:**
![icon_v13](https://user-images.githubusercontent.com/22585204/66741685-ace80200-ee93-11e9-84cc-d9bea807273e.gif)

**Expected behavior:**
![icon_v12](https://user-images.githubusercontent.com/22585204/66741801-eb7dbc80-ee93-11e9-8fd3-41ff27c1e46f.gif)

- Open Direct pictogram tab
- On select on an icon, it will replace just class as version v12. No need to add a new span class...

[web_editor/static/src/js/wysiwyg/widgets/media.js](https://github.com/odoo/odoo/blob/341b568773b28b2bbce02f3532215e9664b318ec/addons/web_editor/static/src/js/wysiwyg/widgets/media.js#L891)

At the above line,  
`        if (!this.$media.is('span')) {`

this.$media always undefine...

**Comment by Yenthe666** [comment]
Hi @smurf-U,

Thanks a lot for reporting this one. I've just tested this on the latest 13.0 and it has been fixed in the meanwhile! 🥳 

Regards,
Yenthe

**Comment by smurf-U** [comment]
Awesome :tada:
