### ISSUE TITLE
[13.0] Interview form not working in recruitment & interview survey results cannot be viewed from the survey results page

### ISSUE THREAD

**Issue by yousafi** [odoo/odoo#38690]
Impacted versions:
13

Steps to reproduce:
[A] Can't view survey form:
1. Create a interview survey form
2. Set the created interview form to a job position.
3. Start the recruitment for the newly created position. [Make sure the survey is in progress state]
4. Click on start interview
5. Click on the start survey button.

[B] Can't see submitted survey results:
1. Having submitted at least one filled interview survey form from recruitment, Go to the survey Module and select the survey and click on the See Result Button. 

Current behavior:
[A] The system does not display the interview survey form for the first time.
[B] The system does not display the result
Expected behavior:
[A] The system should display the survey form so that the interview panel could fill in the questions
[B] The system should display the result.
 
Video/Screenshot link (optional):
[A]  Survey form after clicking on start survey button for the first time.
![image](https://user-images.githubusercontent.com/40589224/66740694-0f87d080-ee89-11e9-901a-ad16649e5b1a.png)

[B]  Survey results can not be displayed (after having submitted 3 filled survey forms):
![image](https://user-images.githubusercontent.com/40589224/66740819-5d9cd400-ee89-11e9-865f-5d081dfb9d96.png)

**Comment by pedrobaeza** [comment]
Not sure what you are expecting to have...

Also, have you tried on runbot?

**Comment by yousafi** [comment]
@pedrobaeza  I have updated the issue description. please have a look at it again.

**Comment by yousafi** [comment]
Fixed and closing the issue.
