### ISSUE TITLE
Landed Cost in WMS - system allow to delete posted records

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#3873]
Create landed cost document and do the calculation, then post the same
your stock value will be updated and accounting jv will be created.
after deleted the posted record from warehouse> landed cost.
Its allowing to delete posted records.

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
