### ISSUE TITLE
[13.0] Manufacturing : Components One2many view issue 

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38744]
**Impacted versions:**

1. odoo 13.0

**Steps to reproduce:**

1. Manufacturing > Master Data > Bills of Materials > Create > Check For Components Tab

**Current behaviour:**

1. Components One2many views not proper.
![New - Odoo](https://user-images.githubusercontent.com/24518821/66771724-a4fe8100-eed8-11e9-9073-17d8aadb5b76.png)

**Expected behaviour:**

1. View should be same as other one2many.
![New - Odoo (1)](https://user-images.githubusercontent.com/24518821/66771922-2229f600-eed9-11e9-9ed1-fe70219b343f.png)

**Video/Screenshot link (optional):**

**Comment by sle-odoo** [comment]
@aab-odoo i'm sorry but do you still have an ongoing task to fix this? i believe it was fixed at some point around the 13 release. thanks in advance

**Comment by aab-odoo** [comment]
@sle-odoo @Arcasias is working on it. This is due to the invisible columns. See task 2076721.

**Comment by sle-odoo** [comment]
@aab-odoo thanks
