### ISSUE TITLE
[13.0] Manufacturing: BOM Product attachment kanban image not display. 

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#38747]
**Impacted versions:**

1. Odoo 13.0

**Steps to reproduce:**

1. Manufacturing > Master Data > Bills of Materials > Create > Add components > Add product attachment.

**Current behaviour:**

1. In kanban image not display.
![Attachments - Odoo](https://user-images.githubusercontent.com/24518821/66772570-9fa23600-eeda-11e9-8be5-94bc2ac9a476.png)

**Expected behaviour:**

1. In kanban view image should be displayed.
![Attachments - Odoo (1)](https://user-images.githubusercontent.com/24518821/66772663-da0bd300-eeda-11e9-80e9-9c4aa52227d5.png)

**Video/Screenshot link (optional):**

![kanbanmanufacture](https://user-images.githubusercontent.com/24518821/66772679-e4c66800-eeda-11e9-9f83-dca72bb8f780.gif)

**Comment by mart-e** [comment]
@amoyaux could you have a look? Why is there a `?field=thumbnail` in the URL of the image ? It is not a field of ir.attachment

https://github.com/odoo/odoo/blob/3299450dfa6dc3a8a00660b24ba0e045017da732/addons/mrp/views/ir_attachment_view.xml#L22

**Comment by amoyaux** [comment]
@mart-e Yep seems to be the issue. @pedrobaeza fix on the way, thanks for reporting it.
