### ISSUE TITLE
[13.0] POS : Not able to delete POS Session (pos.config) which just created.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38752]
Impacted versions: 13.0 C

Steps to reproduce:
- Go to Point of sale, Configuration -> Point of Sale
- Create any Record (pos.config). Just save and Try to delete it.

Current behavior:
- It preventing and showing a warning of the pos.config sequence.

Expected behavior:
- It should allow deleting the config which I just created, even though POS Session is also not started yet.

This is something like #38581 @pimodoo 

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/y2mgondy)
[VIdeo](https://youtu.be/gCyOuqkqgOc)

Thanks!

**Comment by Yenthe666** [comment]
@switch87 and @pimodoo for you guys.

**Comment by caburj** [comment]
@dipsshah42 Thank you so much for reporting this issue. It's now fixed in 13.0 (see referenced pull request above). I believe we can close this issue.
