### ISSUE TITLE
[13.0] POS : Giving traceback when recursion happening in PoS Product Categories. Should raise warning properly instead Traceback.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38753]
Impacted versions: 13.0

Steps to reproduce:
- Create Category, Save it, and assign the same category in the parent category of that category.

Current behavior:
- It throwing traceback.

Expected behavior:
- It should handle in well way. instead traceback should raise warning!

Video/Screenshot link (optional):
[Screenshot](http://tinyurl.com/y2kuomy2)

**Comment by sswapnesh** [comment]
Fixed in #38769

**Comment by pedrobaeza** [comment]
Closing this one.
