### ISSUE TITLE
What is the use of the model and the res_id ?

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#38763]
https://github.com/odoo/odoo/blob/a12e29c963201add0ea6b15a1e8e19a6af1db032/addons/mail/models/mail_thread.py#L1977

they are reveived from the parameters,bu never used.Maybe they can be used here:
 values = {
            'parent_id': parent_id,
            'model': self._name if self else False,
            'res_id': self.id if self else False,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by tanghulu0608** [comment]
OK thank you.
