### ISSUE TITLE
[11.0], [12.0], [13.0]  Button URL in website blog post creation email not working properly.

### ISSUE THREAD

**Issue by khishigbat** [odoo/odoo#38765]
**Impacted versions:** 
[11.0], [12.0], [13.0]

**Steps to reproduce:** 
Create website blog post and publish it. A notification email will be sent, containing the URL for this new post. Click on "Access post" button.

**Current behavior:** 
When you press on this "Access post" button, you will not be directed to the post, instead you'll be directed to the list of all blog posts. 

**Expected behavior:**
"Access post" button should link to the post, which was published.

**Solution:**
/website_blog/views/website_blog_templates.xml -->
`<!-- Chatter templates --> `  -->
`<a href="/blog/#{slug(object)}/post/#{slug(post)}"`
This line should be like this instead: `<a t-attf-href="/blog/#{slug(object)}/post/#{slug(post)}"`

**Comment by Yenthe666** [comment]
@JKE-be for you guys, if you like I can make you a PR.

**Comment by JKE-be** [comment]
pr in v13 is ok ;)

thanks @Yenthe666

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/534e5fbc4782a23162ce69d93a640fdd5dd99f9b
