### ISSUE TITLE
Deprecated link

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#38806]
Impacted versions:
13.0
Current behavior:
The page https://www.odoo.com/page/docs is still referenced in [[1]](https://github.com/odoo/odoo/blob/babcbf8a2bdf3ea9813705c5fce42e883831e009/doc/_extensions/odoo_ext/layout.html#L154) and [[2]](https://github.com/odoo/odoo/blob/babcbf8a2bdf3ea9813705c5fce42e883831e009/addons/mail_bot/models/mail_bot.py#L59)

But it appear that this page is not supported anymore, it even have some link to the version 11.0 that return a 404

**Comment by Yenthe666** [comment]
@frlanxpertiz what doesn't work for you? I can open https://www.odoo.com/page/docs and the main items there redirect me to V13 content?

**Comment by frlanxpertiz** [comment]
The links for User, Developer, API and Installation at the top of the page point to the doc of 11.0

**Comment by frlanxpertiz** [comment]
And I just found out that the link to the API Docs on the page https://www.odoo.com/page/community point to the version 10.0

**Comment by Yenthe666** [comment]
@mart-e

**Comment by mart-e** [comment]
Hello,

The links have been updated (even if the links to 11.0 are not "deprecated", it still makes sense in 2019).
Thanks for the report
