### ISSUE TITLE
[USABILITYBUG] Voucher Reference is not posted on duplicated vouchers

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#3884]
##### Steps to reproduce:
1. Copy an existing voucher
2. Do NOT update voucher lines
3. Set a value on the voucher's reference field
4. Save
##### Behaviour:

In the Jurnal Items, the reference is not propagated on these vouchers
##### Expected behaviour:

As on the voucher line, there is no visible field "reference", I would expect the reference to be propagated to the jurnal items on an onchange of the very voucher's reference field
##### Note:

The reference is update if you change the voucher line field Company. It seems to have the onchange method on the line level, which obviously is not expected for a field you set on the per voucher level.

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
