### ISSUE TITLE
[BUG] Rounding error

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#3885]
##### Reproduction

I've rounding on account entries 0
Display in Spanisch language is set to: [3,3,3,3], Decimal separator ",", thousand separator "."
Rounding factor on the Money (COP): 1.000000, computational accuracy: 4
##### What happens is this, since I changed rounding on account from 2 to 0

**_During Editing**_
![captura](https://cloud.githubusercontent.com/assets/7548295/5192420/4d5e974c-74c5-11e4-9bda-91adc1f9ff78.PNG)
**_After Editing**_
![captura2](https://cloud.githubusercontent.com/assets/7548295/5192421/50dfd08e-74c5-11e4-8043-ca365eee3e76.PNG)

417.311 reduces to 417
### UPDATE:

On an user account with english separators:
thousand ","
decimal "."
this behaviour does not occur, which might be the hint to the solucion that some rounding method of an account accuracy 0 has a hard coded decimal separator and does not respect the language setting.

**Comment by Adoniasv** [comment]
Is a Bug.

Change this file:

addons/web/static/js/formats.js

Find this line in function instance.web.parse_value:
```javascript
  case 'float':          
     tmp = Number(value); 
     if (!isNaN(tmp))
        return tmp; 
```
and change for this (Coment whit //)
```javascript
 case 'float':          
     //tmp = Number(value); 
     //if (!isNaN(tmp))
        //return tmp; 
```
is working for us

**Comment by blaggacao** [comment]
@qdp-odoo A ping. Seems a confirmed bug with proposed solution.

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
