### ISSUE TITLE
[8.0] Wrong quantity on Current Inventory Valuation screen when returning shipment

### ISSUE THREAD

**Issue by sabrinahung** [odoo/odoo#3887]
When returning shipments, it will show wrong Product Quantity and Inventory Value on Current Inventory Valuation screen.

e.g.,
Costing Method = Real Price, Inventory Valuation = Real Time (automated)
1) Purchase 100 pcs from supplier
2) Return 10 pcs to supplier

When returning 10 pcs to supplier, Current Inventory Valuation shows 100 pcs returned instead of 10pcs. Please refer to screen shot as attached, thanks.

![wrong on inventory valuation](https://cloud.githubusercontent.com/assets/8923286/5194300/3c699be0-7546-11e4-8284-31a9fc008249.png)

**Comment by Yenthe666** [comment]
Hi @sabrinahung ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
