### ISSUE TITLE
Wrong base amount on invoice with tax configured without GL account

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#3888]
# How to reproduce

Using version 8 (might also be the case on other version) on Ubuntu 14.04
- Create a database and install account_accountant
- Create 2 taxes with no GL accounts in their configuration (so that the taxes use the expense account as explained in the tooltip)
- Create an invoice with those 2 taxes
- Click on update to compute the tax
# Result

The tax table has one line with the base amount twice the total of the invoice.

Screenshot:
![supplier_invoices](https://cloud.githubusercontent.com/assets/939952/5554422/bd25f2d6-8c22-11e4-9279-73eae301a5e0.png)
# Expected result

2 tax lines with the total of the invoice as the base amount on each line

**Comment by Saroufrodon** [comment]
I confirm I have the same issue with the latest Odoo 8.
The base amount is twice the subtotal! 
The base amount should be the subtotal, and this for each tax.

**Comment by Yenthe666** [comment]
Hi @max3903 ,

Thank you for your detailed bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
