### ISSUE TITLE
Google Analytics tracking script in Website/"Main Layout" not working

### ISSUE THREAD

**Issue by corradopagliarini-bikm** [odoo/odoo#38891]
Impacted versions: 13

Steps to reproduce:

The strim function for the Google Analytics ID included in the Main Layout of Website doesn't work properly:

_<script id="tracking_code" t-if="website and website.google_analytics_key and not editable">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', _.str.trim('<t t-esc="website.google_analytics_key"/>'), 'auto');
            ga('send','pageview');
        </script>_

**Without the trim function, the script works nice and easy.**

Current behavior:

The Google Analytics ID is not tracked, and no analytics is provided.

Expected behavior:

The Google Analytics ID should be correctly trimmed and tracked, providing working analytics.

Video/Screenshot link (optional):

**Comment by corradopagliarini-bikm** [comment]
Corresponding ticket created on Odoo.com/help: 2089296

**Comment by flaviusfrantz** [comment]
Is it now fixed? Does Google Analytics work in Odoo v.13 ?
