### ISSUE TITLE
General account should not be required on analytic entries

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#389]
https://bugs.launchpad.net/ocb-addons/+bug/1146923

The manual for analytic accounts states[1] : "Each analytic entry can be linked to a general account, or not, as you wish. Conversely, an entry in a general account can be linked to one, several, or no corresponding analytic accounts."

But the field 'general_account_id' is defined as "required=True" in account/account_analytic_line.py
I suggest that this requirement should be relaxed to allow greater flexibility in analytic accounting.

[1] http://doc.openerp.com/v6.1/book/4/4_10_Accounts/index.html

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
