### ISSUE TITLE
Backspace weird behavior in Odoo10

### ISSUE THREAD

**Issue by H24H** [odoo/odoo#38909]
Impacted versions:10

Steps to reproduce:press backspace to delete item bar-code

Current behavior:delete the price or quantity of the previous item

Expected behavior:just delete 1 character from the bar-code 

Video/Screenshot link (optional):https://wetransfer.com/downloads/e60b7775fbbe6bd52b9a8303e507073220191016232922/58db361e5a7f8079938485c464253a3620191016232922/8438cf

**Comment by pedrobaeza** [comment]
Sorry, version 10 is out of support, as only last 3 versions are. If the behavior is reproducible in latest versions, please open a new one with the steps to reproduce the problem in that version.
