### ISSUE TITLE
[13] Unarchive All should not "Archive" records

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38903]
Impacted versions: 13.0 (Haven't checked on 12)

Steps to reproduce:  For Any kanban view with Archive/Unarchive All action
![Screenshot (7)](https://user-images.githubusercontent.com/16624719/66952519-686a8b00-f07a-11e9-9d5e-de93170c7b33.png)

Current behavior: It is Archiving records

Expected behavior: Nothing should happen, As they are already Unarchived (This works correctly on List view )

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Is it a framework behaviour that you can reproduce on multiple places or is it just here?

**Comment by sswapnesh** [comment]
Other places as well.
