### ISSUE TITLE
[13.0] MRP: BoM creation from Kanban should be blocked

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38904]
Impacted versions: 13.0

Steps to reproduce:
![Screenshot (8)](https://user-images.githubusercontent.com/16624719/66952852-065e5580-f07b-11e9-807b-eb89ac077056.png)

Current behavior:
![Screenshot (9)](https://user-images.githubusercontent.com/16624719/66952863-0e1dfa00-f07b-11e9-8b15-ccd00a9f857a.png)

Expected behavior: BoM creation from Kanban should be not possible

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sle-odoo for your interest.

**Comment by lap-odoo** [comment]
Thanks, we'll take care of this.
Ticket ID : 2124162.

**Comment by Yenthe666** [comment]
@nle-odoo would have been an even better message if it said where from it should be created then. ;)
