### ISSUE TITLE
[13.0] Link for "Request Document" not working

### ISSUE THREAD

**Issue by VannotAlexi0x73** [odoo/odoo#38929]
__Impacted versions:__
V.13

__Steps to reproduce:__
When I want to create "Request Document", the link present in the mail is not working. Open the link in a new private browsing and you will get "Not found"

__Current behavior:__
In a new private browsing, the link does not work.

__Expected behavior:__
Maybe redirects to login page ? (to get a session)

__Video/Screenshot link (optional):__
![odoo_1](https://user-images.githubusercontent.com/34712990/66995978-25d39d80-f0d0-11e9-9c4e-19c5970aed76.png)
![odoo_2](https://user-images.githubusercontent.com/34712990/66995989-29ffbb00-f0d0-11e9-954a-5872dc445977.png)
![odoo_3](https://user-images.githubusercontent.com/34712990/66995994-2c621500-f0d0-11e9-8969-4ae3b46b8b7b.png)

**Comment by pedrobaeza** [comment]
Being this something in an enterprise module, please put the OPW ticket in odoo.com/help instead.

**Comment by Yenthe666** [comment]
Plus this is because the instances on runbot have multiple databases. I'm pretty sure it'll work just fine on a single database or with the right configuration.
