### ISSUE TITLE
Error 3d Secure Notofication

### ISSUE THREAD

**Issue by hugo49** [odoo/odoo#38958]
Impacted versions: 12

I have a problem with 3D Secure. A customer attempted to settle an invoice. He never received the SMS with the code. A few hours later he retried, the payment was validated. But no information was transmitted to Odoo. The payment is still pending. I can not create an invoice, everything is waiting.
STRIPE asks me for the default in the API.

Logs. 

{
  "object": {
    "id": "xxxxxxxxxxxxxxxxx,
    "object": "payment_intent",
    "amount": 3000,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "charges": {
      "object": "list",
      "data": [
      ],
      "has_more": false,
      "total_count": 0,
      "url": "/v1/charges?payment_intent=xxxxxxxxxxxxxxxxx
    },
    "client_secret": "pi_xxxxxxx_secret_Lxxxxxxx4",
    "confirmation_method": "automatic",
    "created": xxxx1318xxx69,
    "currency": "eur",
    "customer": "cus_xxxxxxxxx",
    "description": "FAC/2019/xxxx-3",
    "invoice": null,
    "last_payment_error": null,
    "livemode": true,
    "metadata": {
    },
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": null,
    "payment_method_options": {
      "card": {
        "installments": null,
        "request_three_d_secure": "automatic"
      }
    },
    "payment_method_types": [
      "card"
    ],
    "receipt_email": null,
    "review": null,
    "setup_future_usage": "off_session",
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "requires_payment_method",
    "transfer_data": null,
    "transfer_group": null
  }

**Comment by dbo-odoo** [comment]
Hi,

Odoo is not ressponsible for the SMS delivery, so there's nothing I can do here. This happens on the customer's bank side.

Regarding the update of the payment, if it was validated off-line at a later point in time, then Odoo will not be notified of the change in status (as of Odoo 13, we do not support listening from notifications from Stripe to update payment status after the payment flow is done, though this will probably be done for Odoo 14).

The log you included is for a failed payment (as indicated by the status being `requires_payment_method`; cfr the Stripe doc here https://stripe.com/docs/api/payment_intents/confirm ).

I'm afraid there's very little I can do with this information. If you have more details (a video showing the problem, for example - and a complete description of what exactly the customer did), we could reopen it - as it stands, I will close this as there is far too little information.
