### ISSUE TITLE
[13.0][WISH] Inventory : Landed cost : Prevent user from creating vendor bill from here or allow fully to do it.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#38993]
Impacted versions: 13.0

Steps to reproduce:
- Go to inventory > Landed Cost 
- Create Vendor bill > Open that bill, try to post, duplicate, etc.

Current behavior:
- It's allowing to create a Vendor bill but when posting its throwing warning to add lines but nowhere in that view we have an option to add bill lines.

Expected behavior:
- Either Prevent users to create a bill from Landed cost form or add lines options also .

Video/Screenshot link (optional):

[Video](https://youtu.be/GpUAI6vv_-k)

**Comment by sle-odoo** [comment]
There's now the possibility to add the missing lines if you want to use the quick create in this view.

Regards
