### ISSUE TITLE
 mrp_bom_component_tree_view shouldn't allow reordering

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#390]
https://bugs.launchpad.net/ocb-addons/+bug/1155581

Opening mrp_bom_component_tree_view via "Manufacturing / Configuration / Bill of Material Components" gives a tree view that is reorderable. This is very likely to mess up orderings in the single boms, as there all BOM components are thrown together. Reordering should be suppressed here.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
