### ISSUE TITLE
[V13]When install Social Push Notifications , will be an error.

### ISSUE THREAD

**Issue by mengzeyang** [odoo/odoo#39007]
Impacted versions: V13

Steps to reproduce:
Install modules
Current behavior:
Unable to install module "social_push_notifications" because an external dependency is not met: Python library not installed: firebase_admin
Expected behavior:
No error
Video/Screenshot link (optional):

![图片](https://user-images.githubusercontent.com/36189881/67078982-f488c980-f1c4-11e9-8d54-d9501445b63e.png)

**Comment by Yenthe666** [comment]
@mengzeyang the module social needs a Python dependency, `firebase_admin`. You can install it manually on your server, this is the desired behaviour.

CC @mart-e see, I told you so 😉

**Comment by ray-odoo** [comment]
sudo pip3 install firebase-admin

**Comment by arvind28990** [comment]
> @mengzeyang the module social needs a Python dependency, `firebase_admin`. You can install it manually on your server, this is the desired behaviour.
> 
> CC @mart-e see, I told you so 😉

hi i installed the firebase-admin but even though i am getting this error can you help me

**Comment by arvind28990** [comment]
> sudo pip3 install firebase-admin

hi i installed the firebase-admin but still getting the error
