### ISSUE TITLE
[11.0],[12.0] Display wrong created user name in delivery chatter while creating delivery from SO

### ISSUE THREAD

**Issue by Riya-Sathavara** [odoo/odoo#39006]
Impacted versions: Odoo11 Comunity

Steps to reproduce: 

**Please find the following steps to Reproduce this**
- Login with Another user (Not Admin)
- Confirm Sale Order which have stockable or consumable products
- In created delivery's chatter area display **Note by Administrator**

Current behavior: I have login with another user but while creating time of delivery which related to SO it's display created by Admin in chatter

Expected behavior: In delivery's chatter area display created user name instead of Admin user name
**Note** : If we make delivery from PO then it will take perfect user name in chatter area

Video/Screenshot link (optional):
https://drive.google.com/file/d/1DGiY3YxPcaZhajv72slhfhwoW76uYe7I/view?usp=sharing

**Comment by pedrobaeza** [comment]
This can't be as this operation is performed with sudo (admin) for avoiding permission problem. This is solved in 13 where changing permissions role doesn't change user, but in this version there's no other solution.

Closing as not fixed in <=12, but fixed in 13.

**Comment by Riya-Sathavara** [comment]
Thanks for your quick response.

**Comment by RiyaSathavara** [comment]
I am still facing the same issue in the Odoo14 Enterprise 

Can anyone help me with that?

**Comment by pedrobaeza** [comment]
If that's the case, please expose your full case with detailed steps to reproduce in a new issue.

**Comment by RiyaSathavara** [comment]
Hi @pedrobaeza  ,

Here I have attached a demo video to explain the issue with Steps (Video created from Run boot )

Demo video :
[Issue on Chatter Author](https://drive.google.com/file/d/1OgLjimGRRBW5cczsvoRtK4mWTcVSFcs2/view?usp=sharing)

Now v14, If created Delivery from Sale Order and Receipts from the Purchase then also faced Author Name issue on delivery or Receipts
