### ISSUE TITLE
You can not restrict a Portal user can not delete or create shared Filters

### ISSUE THREAD

**Issue by nicomacr** [odoo/odoo#3904]
Create a rule so that the user portal can't delete shared filters from other users, and that rule arises no effect
Impacted versions: Odoo 8.0
Steps to reproduce:
1. Create a Record Rule for the "filters" object. 
Domain:[(1,'=',1)]
Access Rights: Apply for Read
Groups: Portal User
2. Create a filter and share (in user admin)
3. Login to Portal User and try to delete the filter, and create new

**Comment by Yenthe666** [comment]
Hi @nicomacr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
