### ISSUE TITLE
[11] Failed to render template (Send By Mail -> Custommer Receipt)

### ISSUE THREAD

**Issue by gpperez** [odoo/odoo#39059]
Impacted versions: Odoo11 2019-10-18

Steps to reproduce:

Try to "Send by mail" customer receipt (pressing button inside form view). No admin user. The error ocurs even with an user with administrative permissions. 

I've test it with an previous version of odoo (from 2019-07-31) and the error not occurs.

Current behavior:

Error

Failed to render template <Template memory:7f53b7138ef0> usando los valores {'user': res.users(35,), 'format_date': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f53b615b510>, 'object': account.payment.group(658,), 'format_amount': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f53b615bf28>, 'format_tz': <function MailTemplate.render_template.<locals>.<lambda> at 0x7f53b615bc80>, 'ctx': {'active_model': 'account.payment.group', 'active_ids': [658], 'active_id': 658, 'default_template_id': 11, 'tz': False, 'default_composition_mode': 'comment', 'uid': 35, 'default_use_template': True, 'default_res_id': 658, 'tpl_partners_only': True, 'search_disable_custom_filters': True, 'safe': False, 'default_model': 'account.payment.group', 'lang': 'es_AR', 'params': {'action': 272}}}

Expected behavior:

Wizard with all data about the custommer receipt, redy to be sent by mail

**Comment by pedrobaeza** [comment]
This is because the translation is not correct for that template. Please check https://github.com/odoo/odoo/wiki/Translations for knowing how to fix it in source (or update your installation if already fixed).

**Comment by gpperez** [comment]
Ive test it with a fresh odoo instalation from today, and the error still happens. Also I heard about the translation error, but Ive test it with other languajes, but without solution. Only when I downgrade odoo to previous release date the error did dissapear

**Comment by pedrobaeza** [comment]
Have you tried in English? If working, then the problem is in the translation.

**Comment by gpperez** [comment]
Yes I did
