### ISSUE TITLE
Very slow performance with a remote postgresql server

### ISSUE THREAD

**Issue by lgarcia11** [odoo/odoo#39066]
Steps to reproduce:
Point odoo to a remote PostgreSQL server and initialize a new db.

Current behavior:
Takes more than 10 minutes to initialize.

Expected behavior:
Initialize in seconds.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/12752396/67138436-16a83900-f211-11e9-86bf-52a5e2dbb15d.png)

**Comment by pedrobaeza** [comment]
This is not a problem of Odoo itself, but your infrastructure. Check network connection and the rest of configuration.

Closing as no issue.
