### ISSUE TITLE
[12.0][13.0][WISH] Product Margins: No need of create button in reporting 

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#39069]
**Impacted versions:**

1. Odoo 12, 13

**Steps to reproduce:**

1.  Go To Invoicing > Reporting > Product Margin> Wizard Open > Open Margin

**Current behavior:**

1. Product Margins: No need of create button in reporting 
![Screenshot](https://user-images.githubusercontent.com/24518821/67139724-e42e2880-f270-11e9-9361-daff72be762b.png)

**Expected behavior:**

1. Create button should not be visible

**Video/Screenshot link (optional):**

**Comment by sswapnesh** [comment]
Added  #39072 to Improve this

**Comment by sswapnesh** [comment]
Improved in master at https://github.com/odoo/odoo/pull/39072 at https://github.com/odoo/odoo/pull/39072/commits/385bf79b9ae91bdd1b7ae14301767fa4b4cd48d8
