### ISSUE TITLE
[12.0][13.0]Product Margins: Accepting wrong dates

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#39068]
**Impacted versions:**

1. Odoo 13.0, 12.0

**Steps to reproduce:**

1. Go To Invoicing > Reporting > Product Margin> Wizard Open > Enter From Date"01/01/2019" > To Date"12/31/2018"

**Current behavior:**

1. It Accepting, from date is greater than to date
![Screenshot1](https://user-images.githubusercontent.com/24518821/67139556-3706e080-f26f-11e9-9484-2d18177676e5.png)

**Expected behavior:**

1. The from date must be anterior to the to date., (To date should be greater than from date)

**Video/Screenshot link (optional):**

![product_margin](https://user-images.githubusercontent.com/24518821/67139561-3f5f1b80-f26f-11e9-989b-268cd2e53d46.gif)

**Comment by pedrobaeza** [comment]
Well, this is not an error at all, as putting that interval simply doesn't show anything, so for me is correct.

**Comment by sswapnesh** [comment]
Good to have Validation for dates in master.

**Comment by Yenthe666** [comment]
Yep, feel free to make a PR against master to improve this but in the current versions I don't consider this an issue. :)
