### ISSUE TITLE
[13.0/12.0/11.0] calendar: Wrong number of Meetings count on Partner

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#39075]
Impacted versions: 13.0/12.0

Steps to reproduce: Go to Meeting Smart Button on Contact

Current behavior: 
![Screenshot (16)](https://user-images.githubusercontent.com/16624719/67144915-fa041380-f299-11e9-8e85-287540513b2b.png)

![Screenshot (17)](https://user-images.githubusercontent.com/16624719/67144919-04bea880-f29a-11e9-8133-85f9109b3967.png)

Expected behavior: Count should be 6, Total should Include Re-current Meetings as well 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@mart-e I've seen a few calendar issues now but I don't think we have a label for it? Under what should we categorise this?

**Comment by sswapnesh** [comment]
IMO it should be under `Services`

**Comment by sswapnesh** [comment]
So we are still using `name` for default search (Since last 4 years ) :thinking: 

 
https://github.com/odoo/odoo/blob/ff70835db4f6354de62a00dc717682c2835a105c/addons/crm/models/res_partner.py#L53


Strange that no one noticed this so far.

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/39403 for v11

**Comment by sswapnesh** [comment]
I think we can close this based on @mart-e  's https://github.com/odoo/odoo/pull/39403#issuecomment-554963412
