### ISSUE TITLE
[12.0] Nightly build deb packages are down since october, 14th

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#39073]
Impacted versions: 12

There is no more nightly builds for debian since october 14th. Other packages are ok.

**Comment by pedrobaeza** [comment]
@d-fence can you please check?

**Comment by d-fence** [comment]
I'm on it. Need a backport of packaging stuffs

**Comment by sswapnesh** [comment]
Should be fixed in https://github.com/odoo/odoo/pull/39091

**Comment by d-fence** [comment]
Fixed here aabac72a0ad8bcfd4a5ffce243f4a750a3dd3b9f
