### ISSUE TITLE
[12/13] base_import: Import Template for Products is outdated

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#39074]
Impacted versions: 12.0 / 13.0
 
Steps to reproduce: Try to Import this file again
![Screenshot (14)](https://user-images.githubusercontent.com/16624719/67144232-329fef00-f292-11e9-8666-dbc09014d8d4.png)

Current behavior:
![Screenshot (15)](https://user-images.githubusercontent.com/16624719/67144237-4cd9cd00-f292-11e9-9460-39b9f942f4d6.png)

Expected behavior: Able to Import

Video/Screenshot link (optional):

We have to Add new Names according to v12's demo data based on https://github.com/odoo/odoo/blob/9d0f172f29085a6b164313bf20178270b9572cc2/odoo/addons/base/data/res_partner_demo.xml

**Comment by pedrobaeza** [comment]
@mart-e I ping you as wildcard for this kind of things

**Comment by mart-e** [comment]
@xmo-odoo I believe you were the one who introduced this template at b60de0db41bbe4af3c2f. Could you have a look?
