### ISSUE TITLE
Multi website - choosing a theme

### ISSUE THREAD

**Issue by foxroxracer** [odoo/odoo#39076]
Impacted versions: V13

Steps to reproduce:
-> Create 2 websites
-> Go to Settings->Website
-> Pick your second website from the "Select the website to configure" form
When clicking on "choose a theme" it wil change the theme of the first website in the
"Select the website to configure" form. (even when first clicking on save)

Current behavior:
- When picking a website and clicking on "Choose a theme" it always uses the first website in the list, and not the website you've picked.

Expected behavior:
- Pick website you want to configure and when clicking on "Choose a theme" it should pick the selected website to alter the theme.

Video/Screenshot link (optional):
![Knipsel](https://user-images.githubusercontent.com/17411564/67146160-6bd36180-f288-11e9-95e4-0ee242212980.PNG)

**Comment by sargamm** [comment]
Hi, I would like to work on this. Before I can start could you guide me a little? Thanks!

**Comment by pedrobaeza** [comment]
If you have an enterprise contract, you can put an OPW ticket at odoo.com/help and demand an SLA answer, but here this is a voluntary effort based on the good will, so no promise of solution.

**Comment by rdeodoo** [comment]
Hi, thank you for the report.
I just had a quick look on both community, enterprise and design-theme and everything is working as it should.
The bug you experience seems like a bug we fixed over a week ago, among others.
Could you please retry on a fresh updated database?

**Comment by foxroxracer** [comment]
hi, thanks for the responses!

I thought demo.odoo.com was the latest odoo version...
I now updated my odoo and the bug is fixed :) 

Thanks!
