### ISSUE TITLE
[12.0][13.0] no variant attribute printed like a variant in website

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#39080]
Impacted versions: 12, 13 (untested on older ones)

Steps to reproduce: 

- Install ECommerce, in settings activate Product Comparison Tool. 
- Creates a product attribute, check Never in Creates Variant, creates some values. 
- Add several of these values on a product. 
- Open the product on the ecommerce website.

Current behavior: 

- This Never Create Variant attribute is printed at top of the page under product name, with choice enable, like for variants.
- In the comparison table, attribute's values are separated with "or"

Expected behavior:

- a Never Creates Variant attribute shouldn't be printed like a variant one, with choice enable, but as a list
- if the comparison table is printed, this attribute shouldn't be printed at top of the page under the product name, but only in the table
- in the comparison table, this attribute's values should be separated with comma or "and"

**Comment by pedrobaeza** [comment]
Can you include some screenshots with annotation for better understanding of what you are telling about?

**Comment by zeroheure** [comment]
Below I've created an attribute, checked Never Create Variants and added 3 values. Then I've added the 3 values to the product. I've also added some other attributes, but with one value only.
![Attribute without variant](https://user-images.githubusercontent.com/24126/67320825-0644d680-f50f-11e9-97c4-bb1c6074a7cf.jpeg)
As you can see all attributes are display in the Specification table. But there is an "or" word between values of the "Attribute without variants creation" , while it should be "and" or a comma (better).
This attribute offer also to choose a value in the pop-down, while it shouldn't because there is no variant.

**Comment by pedrobaeza** [comment]
@JKE-be which was your idea about attributes for that comparison?

**Comment by zeroheure** [comment]
@pedrobaeza you never sleep ? :-)

**Comment by JKE-be** [comment]
@pedrobaeza imo it is correct...

When you add attribute « Color » and value « black » and « white » on an iPad ... it is as well black as well white ... so a OR

No create variant is the same principe... just that product have no variant black or white, but it is only write into the description ...

**Comment by pedrobaeza** [comment]
Maybe an improvement to master in website_sale_comparison can be to specify at attribute level which join nexus to use through a selection (`and`, `or`, `,`) - that can even be extended in custom module -?

**Comment by zeroheure** [comment]
If you add some ISO standards to a product, it is expected to read "ISO 1123 **and** ISO 456" or "ISO 1123 **,** ISO 456".
Using commas in  all cases (variants or not) works very well.

**Comment by zeroheure** [comment]
And what about the attribute that offer to choose a value, while it shouldn't because there is no variant ?

**Comment by zeroheure** [comment]
I've added screenshots before/after in my PR

**Comment by JKE-be** [comment]
@zeroheure As explain in my previous comment, there are no bug imo.

Seems like you are hacking the function of this field.
It is just to avoid to create thousand of variant in some case where you want to allow the user to select one of the 1000 values proposed (and just follow the value into the description)

As shown in the printscreen from your issue, you need to choose one of the value on the top right before to add to cart, so value A or value B or value C.

KR

**Comment by JKE-be** [comment]
ps this code in v13 is refactored, you can now have for a same attribute, several value...

------

>  attA->| value1 value2 value3

 you can only chose one value of them


-------

>   attA -> value1
>   attA -> value2
>   attA -> value3

in this case, you have nothing to choose, all values are part of your product

**Comment by zeroheure** [comment]
@JKE-be are you talking about dynamic variant creation ? My report is about the "Never create variant" option which I've found very useful to record and show all product attributes. In other ecommerce softwares, it have strong SEO effect (attributes are display in a structured table) — stronger if we add schema.org micro datas (using external module) — and it filter products. In this use case, user doesn't have to choose between values.
If we are both talking about the "Never create variant" option, I should write a wish on a missing ecommerce feature... Anyway, thank for taking time to answer.

**Comment by JKE-be** [comment]
Never create / always / dynamic  is used to define variantes (created or not) with exclusives attribute value.

But since v13, you can use several attributes lines with same attribute, but 1 value.

Example of usecase is for Wine:
You have an attribute Cepage, and values "Cabernet", "Sauvignon", "Syrah".
It is not one or the other, but a mix of the 3 values.

![image](https://user-images.githubusercontent.com/4848797/68214571-fd0f3b80-ffdd-11e9-8993-bd9b2b6f2aef.png)

![image](https://user-images.githubusercontent.com/4848797/68214752-4f505c80-ffde-11e9-9688-83898dcaff77.png)

![image](https://user-images.githubusercontent.com/4848797/68214801-698a3a80-ffde-11e9-8be2-324065d862cd.png)

![image](https://user-images.githubusercontent.com/4848797/68214915-9b9b9c80-ffde-11e9-9162-80bb99f62b36.png)

**Comment by zeroheure** [comment]
Thank you very much for the detail explanation.
