### ISSUE TITLE
Search on one2many is not correct when there is record rule

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#3908]
step to reproduce (runbot 7.0):

Configure demo user with the following access right:
Multi Companies

Connect with demo user (assert he is on Your Company)
On a product, set suppliers (but not for company OpenERP BE)
Change company (for OpenERP BE)
Open the product, and check you see no suppliers
Make Advanced Search on Suppliers with is not set
![image](https://cloud.githubusercontent.com/assets/7602419/5216137/8be63860-762f-11e4-8043-ff955645c06d.png)

-> the product is not in the result !

**Comment by Yenthe666** [comment]
Hi @laetitia-gangloff,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
