### ISSUE TITLE
Reporting invoice analysis doesn't display all invoices

### ISSUE THREAD

**Issue by nextma** [odoo/odoo#3911]
If you create a invoice in an another fiscal year 

only analysis for invoices in current fiscal year appear in reporting , invoices analysis  even if "This year" is not selected in the filter

**Comment by Yenthe666** [comment]
Hi @nextma,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
