### ISSUE TITLE
[13.0] Share partner as Sale Customer and Purchase Vendor

### ISSUE THREAD

**Issue by bobslee** [odoo/odoo#39144]
Impacted versions: 13

_Apparently things changend how a Partner becomes a Customer and/or Supplier, since v13._

**Since v13:**
After creating a Sale or Purchase Order, a partner becomes either a Customer or Supplier.
To flag a partner as the other type, one has to create, confirm and pay a first (Sale or Purchase) Order.

**Until v12:**
It was possible to flag a Partner as supplier and/or customer, from the Partner form-view.
However those checkboxes (bool fields: customer, supplier) had been removed since v13.

https://github.com/odoo/odoo/commit/8766f388da9b642ba4433d8d5d670847b472cff8#diff-0f105e6ed828fa38dd57ce6d8ab0b7bf

**Some code review:**

The partners search-view `account.res_partner_view_search` filters on `customer_rank` and `supplier_rank` fields.
https://github.com/odoo/odoo/blob/13.0/addons/account/views/partner_view.xml#L220

However either one of the fields `customer_rank` or `supplier_rank` is stored by:

1. Partner creation (from the context Purchase or Sale):
https://github.com/odoo/odoo/blob/13.0/addons/account/models/partner.py#L497

2. Post of account move:
https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L2088

**Question:**
Is it still possible to flag an existing Customer as a Supplier, without posting a Vendor/Purchase Bill?
(And also vice versa?)

**Comment by Feyensv** [comment]
You just need to set its supplier_rank to 1 manually as I see it.

As you can see in the two actions showing customers / suppliers, the field is set to 1 through the context to make them considered as supplier/customer when created through the corresponding menu (and action).  Thus setting the corresponding count to 1 will show them as customer/supplier.
https://github.com/odoo/odoo/blob/6a08db92769da82023d25d04072027f8a54659b8/addons/account/views/partner_view.xml#L226-L255

It is also done at creation depending on res_partner_search_mode context key ;).
https://github.com/odoo/odoo/blob/aa33704ad061d41c34c56a89728e9dbd77a50abf/addons/account/models/partner.py#L491-L501

**Comment by pedrobaeza** [comment]
Closing the issue as answered. Thanks for it, @Feyensv

**Comment by bobslee** [comment]
Thanks for answering.
Indeed, I already understood and slightly made that point of view.

However those fields (customer_rank, supplier_rank) are nowhere visible on a Partner form-view. So there's a need to do some customization to get these visible, for regular/functional users?

**Comment by pedrobaeza** [comment]
You can import them via the regular import way, or export-import.

**Comment by bobslee** [comment]
> You can import them via the regular import way, or export-import.

Yeah, but that's not what regular users expect (I'm experiencing with my clients).

**Comment by bobslee** [comment]
@pedrobaeza could you re-open this? Because I expect this shall be a global fuzz and request.

**Comment by pedrobaeza** [comment]
No, it has been answered as said. Nothing to re-discuss.

**Comment by bobslee** [comment]
> Well, the idea is to not need to force that ranking, so that's why it's hidden. You are trying to mimick the flags behavior and this is what Odoo is trying to remove.

Regarding the "ranking", I understand and makes sense to not mis-use it in a way to flag as Supplier / Customer.

However, since v13 it's impossible to flag a partner both as Supplier and Customer from the Odoo GUI.

**Comment by bobslee** [comment]
> No, it has been answered as said. Nothing to re-discuss.

Clear, well, good luck to you all !

**Comment by pedrobaeza** [comment]
> However, since v13 it's impossible to flag a partner both as Supplier and Customer from the Odoo GUI.

You don't need to do that. Just search it in the RfQ and select it. This is only a aid for presenting first some results.
