### ISSUE TITLE
Odoo 13 nightly doesn't seem to be up to date with the 13.0 branch 

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#39150]
Impacted versions:
13.0
Steps to reproduce:
Download this version:
https://nightly.odoo.com/13.0/nightly/src/odoo_13.0.20191021.tar.gz
Check the file addons/web/static/src/js/chrome/abstract_web_client.js
for method getScrollPosition
But here: https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/chrome/abstract_web_client.js#L324 
It does. 
Current behavior:
The file doesn't have the method getScrollPosition defined. But here in github the method has been defined for around 21 days from the writing of this issue yet the nightly build is from today. 

Here's the actual commit:
https://github.com/odoo/odoo/commit/9e6acaa0657f9652b32c06286ec85bb0ad2b4432

Expected behavior:
A nightly build should be up to date with the code in github today. With that in mind, it's unclear what is the code being on nightly build. As a result, odoo enterprise will fail to install with a nightly release of odoo. 

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Ehh, Odoo 13 is not equal to master. You know that right? New changes that are made into master will not land in V13.

**Comment by llacroix** [comment]
I'm talking about 13.0 branch not master.

**Comment by Yenthe666** [comment]
Ahh I get you now. I know there where some packaging problems with 12.0, perhaps it is the same for V13. @d-fence can you check?

**Comment by llacroix** [comment]
I just checked, and the nightly for 22 October has the missing changes. Ah, I get it. the commit date from 21 days ago but the MR got merged 9hours ago. So I guess it's okay.

**Comment by d-fence** [comment]
Ok, so we can close this.

**Comment by llacroix** [comment]
I probably got in the middle of 2 version fetching breaking change in enterprise that just got merged into odoo but too soon for nightly builds.
