### ISSUE TITLE
[13.0] call to with_user create a new env with the same cache as others envs

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#39196]
## Impacted versions: 

13.0

## Steps to reproduce: 

Access to a record with a user having the required permission (acl )
Call with_user with a user without the required permissions and browse the same record.(read permission disallowed by record rules)

## Current behavior:

No access error raised

## Expected behavior:

AccessError is raised

My understanding of the new api in odoo 13.0 is:

* call to `sudo` suspends the security check and records read when the security is suspended are in the global cache (we must therefore pay attention that the cache could contains records/info not accessible to the current user)
* call to `with_user`, changes the current user. Therefore in my mind I expect that the cache is not shared with the global one...

**Comment by pedrobaeza** [comment]
@rco-odoo can you answer about this?

**Comment by rco-odoo** [comment]
You are perfectly right, but it is not a *bug*, it's actually a *feature* :wink: 

In Odoo 13.0 there is only one cache per request, except for fields that are explicitly declared context-dependent.  It was done like that to get the best possible performance from the cache.  And in most cases, it's the behavior that you want.

If you want access rights to be checked upon accessing some fields, then it's **up to you** to invalidate the cache for those fields.  (Side note: don't forget to `flush()` before invalidating the cache.)  We found out that this case is uncommon in business code.  Alternatively, you can explicitly call `check_access_rights()` and `check_access_rule()` in your code.

This design choice is no accident, and it was much debated among the "heads" here.  This was found acceptable as it gives most performance with little sacrifice.

Note that the cache is still *consistent*: fields whose value depends on the environment always have the right value in cache.  There is an extra indirection in the cache in this case, in fact.  This is also guaranteed for x2many fields, for which the value is implicitly filtered by the user's access rules.

**Comment by lmignon** [comment]
@rco-odoo Thank you for your clarification on this matter!
