### ISSUE TITLE
The Javascript API Doc page has not been ported to 13.0

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#39204]
Impacted versions:
13.0 Documentation
Steps to reproduce:
go to https://www.odoo.com/documentation/13.0/reference/javascript_api.html#

Expected behavior:
https://www.odoo.com/documentation/12.0/reference/javascript_api.html#

**Comment by pedrobaeza** [comment]
@ged-odoo are there any deadline for that documentation?

**Comment by Feyensv** [comment]
It has been disabled by @xmo-odoo since the auto generation of javascript API documentation made the documentation build crash frequently.  I cannot say when and if it will come back.

**Comment by nkerr123** [comment]
a

**Comment by nkerr123** [comment]
a

**Comment by mart-e** [comment]
The javascript api page has been removed and we do not plan to publish it again at the moment (as explained by Victor, was no longer building, mainly thanks for es6 not being supported by the JS parsing library.
The reference pages (whatever the version) are 
https://www.odoo.com/documentation/13.0/reference/javascript_reference.html
https://www.odoo.com/documentation/13.0/reference/javascript_cheatsheet.html
