### ISSUE TITLE
Calendar "Sync With Google" : choose a different calendar ?

### ISSUE THREAD

**Issue by rubensben** [odoo/odoo#39221]
Hi dear community, we got a google account with many calendars and would like to make the sync happen on a specific one (and not the main one), is there a way to do that ? That would help a lot of workflow as we have a calendar per company/country.

Impacted versions: 12 CE / 13 CE
Steps to reproduce:
settings > enter google calendar API credential
calendar > sync with google calendar
Current behavior: No choice of calendar, syncing the main one
Expected behavior: Be able to select with calendar to sync

Thanks in advance !

**Comment by pedrobaeza** [comment]
@mart-e I think this is not possible. Isn't it?

**Comment by Yenthe666** [comment]
Nope, it is all calendars or nothing, you can't configure this. The scheduler takes them all now. You could however write a little module that adds an option on the calendars to sync/not sync. Override the controller function and apply a domain on the search to limit this.

**Comment by mart-e** [comment]
Indeed, all the synchronisations works with the "primary" calendar

https://github.com/odoo/odoo/blob/8efaa086db271cde792da77bca7a95a0d593df4d/addons/google_calendar/models/google_calendar.py#L263

FYI I have reported a feedback (_memo for myself: feedback 2116020_) about this to our R&D to see if they can add the feature. So check back in a few months if things have changed but, if accepted, it would be for the next version anyway.

**Comment by BeniKing99** [comment]
@mart-e Is there any update on this? (Using Odoo 15)

**Comment by mart-e** [comment]
Sorry but the feedback was rejected. I am not saying it was a bad feedback but we have to decide where focus efforts and find a good balance of features vs ease of use (adding more options make the software more complicated and more difficult to support).
Best,

**Comment by LuvForAirplanes** [comment]
For future reference, I wrote a quick and dirty module to fix this problem. It's private code, I can make a gist if any future alien wants it.

**Comment by alexramo** [comment]
@LuvForAirplanes did you ever make a gist for the code, would love to give it a try?
Thank you!
