### ISSUE TITLE
odoo v10 api.onchange don't work sometimes

### ISSUE THREAD

**Issue by grey27** [odoo/odoo#39220]
Impacted versions: 10

Steps to reproduce:
I have an onchange method for calculating the price and price_taxed 
```
@api.onchange('price', 'tax_rate')
    def onchange_price(self):
        price = self.price_taxed / (1 + self.tax_rate * 0.01) 
        decimal = self.env.ref('core.decimal_price')
        if float_compare(price, self.price, precision_digits=decimal.digits) != 0:
            self.price_taxed = self.price * (1 + self.tax_rate * 0.01)
```
It can help me figure out priceo or price_taxed,But sometimes, it doesn't work,
I wonder if api.onchang doesn't work when the network is unstable?
I don't understand a method sometimes works and sometimes doesn't.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a developer question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

And also version 10 is already out of official support, being only last 3 versions (11, 12 and 13) supported.

Closing this by the reason above.
