### ISSUE TITLE
[8.0] new API - Cannot override computed stored field

### ISSUE THREAD

**Issue by yvaucher** [odoo/odoo#3922]
How to reproduce

    class sale_order(models.Model):
        _inherit = 'sale.order'

        @api.one
        @api.depends('order_line')
        def _get_shipped(self):
            self.shipped = True

        shipped = fields.Boolean(
                compute='_get_shipped',
                string='Delivered',
                store=True)

Result

The field will never be True, though compute method is correctly triggered.

If remove store, it seems it get the values from old api style.

**Comment by yvaucher** [comment]
Test case is available at https://github.com/OCA/sale-workflow/pull/83

**Comment by Cedric-Pigeon** [comment]
Same problem here. The field is well evaluated in cache but on screen it is the value computed by old api method.
I tried to override margin in sale_margin addon.

**Comment by Cedric-Pigeon** [comment]
@rco-odoo What's your opinion on this issue ?

**Comment by JonathanNEMRY** [comment]
any news about this issue?

**Comment by yvaucher** [comment]
Sticked an OPW to it.

**Comment by rco-odoo** [comment]
This is a limitation of the field overriding mechanism: basically it does not work when the original field is an old-api function field. A possible workaround is to first override those fields with old-api fields, then to inherit the result and introduce new-api fields:

    from openerp.osv import fields

    class sale_order(models.Model):
        _inherit = 'sale.order'
        _columns = {
            'shipped': fields.boolean('Delivered'),
        }


    from openerp import fields

    class sale_order(models.Model):
        _inherit = 'sale.order'

        shipped = fields.Boolean(
                compute='_get_shipped',
                string='Delivered',
                store=True)

        @api.one
        @api.depends('order_line')
        def _get_shipped(self):
            self.shipped = True

**Comment by leio** [comment]
Sorry, but citing a potential and, by the sound of it untested, ugly workaround does not make the issue resolved.

**Comment by rco-odoo** [comment]
I am currently testing a patch.
So maybe a actual bug fix...

**Comment by JonathanNEMRY** [comment]
Thanks to reopen this issue @rco-odoo !!! Will wait for the fix

**Comment by Cedric-Pigeon** [comment]
Yes this is critical to write clean new api code.

**Comment by yvaucher** [comment]
@rco-odoo Thanks for the hack and for reopening it. I hope we can find a cleaner way.

**Comment by JonathanNEMRY** [comment]
@rco-odoo : will there a hope to apply the same fix for "default" 's field  attribute behavior?

**Comment by yvaucher** [comment]
@rco-odoo Not sure it is related but here is another issue for overriding of computed fields:

(in case of selection field state of stock_picking)
https://github.com/OCA/carrier-delivery/pull/47

Any clue how to get ride of this exception on module install ? 

    File "/home/travis/odoo-8.0/openerp/models.py", line 4397, in _store_set_values
        result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
    File "/home/travis/odoo-8.0/openerp/osv/fields.py", line 222, in get
        raise Exception(_('undefined get method !'))
    Exception: undefined get method !

Same error came out there:
https://www.odoo.com/fr_FR/forum/help-1/question/inherit-model-cross-api-versions-field-selection-computed-87983

The workaround of defining a field in old api without function, doesn't work.

**Comment by luistorresm** [comment]
Hello @yvaucher 

Do you can solve the last error?

`File "/home/travis/odoo-8.0/openerp/models.py", line 4397, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
File "/home/travis/odoo-8.0/openerp/osv/fields.py", line 222, in get
    raise Exception(_('undefined get method !'))
Exception: undefined get method !`

Regards

**Comment by vinay-vperfect** [comment]
This error still exist, Are you plan to fix this issue on 8.0 branch ? If any body fixed on 8.0 branch , it would be nice to share related diff.

**Comment by khwunchai** [comment]
I get "undefined get method !" instead.
This issue shouldn't closed.

**Comment by josemoralesp** [comment]
Hello @rco-odoo 

This issue is still open because there are still compatibility errors at the moment to override computed stored field.

I have the same error reporte by @yvaucher [here](https://github.com/odoo/odoo/issues/3922#issuecomment-129874599).

@rco-odoo Can you please re-open this issue? Or let me know what I need to do.

Best Regards.

**Comment by antespi** [comment]
For anyone waiting for a workaround on this, this could be useful.
The problem is related with ```pool._store_function``` dictionary. This disappears in v10, because is not used in new API fields. There is no way to remove specs in this dict, so if some addon adds one spec, other addon that inherits from it can't remove it.

@yvaucher, this is a tricky solution that you can use in you case (model: ```stock.picking```, fields: ```state```):

```
from openerp import models, fields, api

class StockPicking(models.Model):
    _inherit = "stock.picking"

    membership_state = fields.Selection(selection=[...], string="...", compute="_compute_state")

    def __init__(self, pool, cr):
        super(StockPicking, self).__init__(pool, cr)
        for model, store in pool._store_function.iteritems():
            pool._store_function[model] = [
                x for x in store
                if x[0] != 'stock.picking' and x[1] != 'state']

    @api.multi
    def _compute_state(self):
        # Your staff, call super, whatever
        return True
```

This will remove the old-specs from ```_store_function``` in those cases where exist, for instance, where new addon is installed but server is not restared (so ```_store_function``` is not created from scratch). This is typical in travis tests.

**Comment by pedrobaeza** [comment]
You should do that on _register_hook method, not on init, to avoid collisions on multi-DB instances.

**Comment by antespi** [comment]
```_register_hook``` is not working in this case, because modules are not loaded (and then ```_register_hook``` called) every time a new addon is installed when you install a list of addons, for instance, in travis test

**Comment by pedrobaeza** [comment]
You have to do it manually for tests, like in https://github.com/OCA/server-tools/blob/464ccb6b59036ad38a55c649e1d2bc37e701481d/base_suspend_security/tests/test_base_suspend_security.py#L28, but it's the correct way to do it until v10.

**Comment by antespi** [comment]
The problem is not there, error appears when sale XML data for demo is loaded.
