### ISSUE TITLE
default website menu could not be translated

### ISSUE THREAD

**Issue by HengzheLi** [odoo/odoo#39243]
Impacted versions:
12.0
Steps to reproduce:
1. Install a fresh odoo
2. Install website module
3. Install Chinese Translaion
4. Back to the website homepage and switch to Chinese language

Current behavior:
The website menu(locate at top-right) still is English

Expected behavior:
The website menu(locate at top-right) should be translated to the selected language

Video/Screenshot link (optional):
No

I check the Webiste's menu, and found that there is duplicated Top menu for the default website. And it seems that this menu is not be translated.
Then I check the code, and found that when the first default website is created. Its menu will be copy. The origin one is translated but the copied one isn't. 
What is the purpose of the COPY operation?
```
# ----------------------------------------------------------
    # Page Management
    # ----------------------------------------------------------
    def _bootstrap_homepage(self):
        standard_homepage = self.env.ref('website.homepage', raise_if_not_found=False)
        if not standard_homepage:
            return

        new_homepage_view = '''<t name="Homepage" t-name="website.homepage%s">
        <t t-call="website.layout">
            <t t-set="pageName" t-value="'homepage'"/>
            <div id="wrap" class="oe_structure oe_empty"/>
            </t>
        </t>''' % (self.id)
        standard_homepage.with_context(website_id=self.id).arch_db = new_homepage_view

        self.homepage_id = self.env['website.page'].search([('website_id', '=', self.id),
                                                            ('key', '=', standard_homepage.key)])
        # prevent /-1 as homepage URL
        self.homepage_id.url = '/'

        # Bootstrap default menu hierarchy, create a new minimalist one if no default
        default_menu = self.env.ref('website.main_menu')
        self.copy_menu_hierarchy(default_menu)

    def copy_menu_hierarchy(self, top_menu):
        def copy_menu(menu, t_menu):
            new_menu = menu.copy({
                'parent_id': t_menu.id,
                'website_id': self.id,
            })
            for submenu in menu.child_id:
                copy_menu(submenu, new_menu)
        for website in self:
            new_top_menu = top_menu.copy({
                'name': _('Top Menu for Website %s') % website.id,
                'website_id': website.id,
            })
            for submenu in top_menu.child_id:
                copy_menu(submenu, new_top_menu)

```

**Comment by pedrobaeza** [comment]
Have you tried to load Chinese language again and include recently created website?

**Comment by HengzheLi** [comment]
Yes, I tried. And tried other languages but the same result.

**Comment by pedrobaeza** [comment]
Well, I do the same with Spanish and I don't have that problem, so any missing step is there. Any way, why don't you simply translate it afterwards? It's only a term to translate.

**Comment by HengzheLi** [comment]
Ok. that might be something miss in my side. I will check again. 
BTW, could you help to explain why the menu will be copied to a duplicated one?

**Comment by pedrobaeza** [comment]
This is the mechanism due to the multi-website capacity, that needs to copy the master template for applying to each website. Closing this meanwhile.
