### ISSUE TITLE
[12.0, 13.0] OCR not "learning" suppliers

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#39265]
Impacted versions: 12.0, 13.0

OCR is a great addition, and works well with most fields.

Unfortunately, we've noticed that it doesn't work so well for partner names.

When sending a vendor bill through OCR for the first time, the partner name isn't extracted. Which isn't a big problem, since we can still add it manually, but then there's a problem. 

When adding a vendor manually to a bill that went through OCR, we're expecting OCR to start learning that that specific type of bill will have that vendor.

Of course, we understand that machine learning isn't foolproof, but even after sending a lot of the same type of invoice through OCR, it still won't assume the partner that we originally set.

We've tested it on versions 12.0 and 13.0, on local machines, Odoo.sh, demo.odoo and runbot, using many of the same kind of invoices.

Is this normal? Or is OCR currently having difficulty with acquiring supplier names?

Thank you.

**Comment by pedrobaeza** [comment]
Please put an enterprise at odoo.com/help for this.

**Comment by reinaldoramosarxi** [comment]
I will, thank you.

**Comment by fpodoo** [comment]
To detect the vendor, we don't use the name, but the VAT number, the website, email addresses, or IBAN,ABN,ABA numbers. One of them is usually enough to match the vendor. Can you send samples of invoices to fda AT odoo DOT com

**Comment by reinaldoramosarxi** [comment]
I will, thank you. Do I need to reference this issue?

**Comment by pedrobaeza** [comment]
If you give full information on the mail, no other reference is needed IMO.
