### ISSUE TITLE
impot log note content cant show

### ISSUE THREAD

**Issue by victoryangn** [odoo/odoo#39302]
Impacted versions: I export data from odoo12, import the data in odoo13

Steps to reproduce: 
1. i export the data from odoo 12 in contacts / products/ supplier
2. i choosed messages / content
3. i get the excel list with correct log note in my odoo 12
4. i import in odoo 13
5. i test the import is correct 
6. it can't be showed in odoo 13

Current behavior: i try to export more items in messages but failed to show in odoo 13 also 

Expected behavior: i hope that i can see my log note in odoo 13 after import messages / content from odoo 12

Video/Screenshot link (optional):

**Comment by victoryangn** [comment]
this is my first report, i hope some one can help me to fix the import problem, many thanks

**Comment by victoryangn** [comment]
anyway, thank you, i do searched a lot and tried for some days, but it seems no body can fix it at this moment, that's why i asked here, sorry for that

**Comment by pedrobaeza** [comment]
Try exporting/importing very few columns, and then expand to more columns until you discover the problem.

**Comment by victoryangn** [comment]
ok, many thanks to get your reply, i will try to make it.
