### ISSUE TITLE
Purchase requisition Warehouse with procurement

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#3931]
the run fuction of procurement order at line 
file purchase_requisition.py at line 405
                'warehouse_id': warehouse_id and warehouse_id[0] or False,
must be the same warehouse_id as the procurement order :
                'warehouse_id': procurement.warehouse_id.id  or False,

**Comment by Yenthe666** [comment]
Hi @m3asmi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
