### ISSUE TITLE
Odoo live chat error, no AJAX style behavior on web visitor frontend

### ISSUE THREAD

**Issue by Parker27** [odoo/odoo#3934]
We have problems with fresh installation of ODOO Live Chat,
We have two user in our odoo V8 installation (Including admin user), we are making tests, this happen with every new user in backend.

If admin/OrElse user is chatting with web visitor (We open other browser windows for testing), the messages that are sent to visitor are visible in admin chat backend window but the visitor can't see his messages or admin response messages until hit F5/Refresh page ... there's no AJAX style behaviour in chat.

What could be the problem?

Best Regards
Parker27

**Comment by Atheryl** [comment]
Same problem here, did you find any solution ?

**Comment by jem-odoo** [comment]
This problem doesn't seem to happen on runbot. Did you test on your machine ?
Is it happening for all the messages, or just for the first one ? (if only the first, the problem is known).

**Comment by Atheryl** [comment]
It's happening for all messages. I did test with multiple browser.

**Comment by jem-odoo** [comment]
Do you have this kind of exception in your console/log : 
```
[Fri Nov 21 08:14:50 2014] [error] ERROR:openerp.http:Exception during JSON request handling.
[Fri Nov 21 08:14:50 2014] [error] Traceback (most recent call last):
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 500, in _handle_exception
[Fri Nov 21 08:14:50 2014] [error]     return super(JsonRequest, self)._handle_exception(exception)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 517, in dispatch
[Fri Nov 21 08:14:50 2014] [error]     result = self._call_function(**self.params)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 283, in _call_function
[Fri Nov 21 08:14:50 2014] [error]     return checked_call(self.db, *args, **kwargs)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
[Fri Nov 21 08:14:50 2014] [error]     return f(dbname, *args, **kwargs)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 280, in checked_call
[Fri Nov 21 08:14:50 2014] [error]     return self.endpoint(*a, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 733, in __call__
[Fri Nov 21 08:14:50 2014] [error]     return self.method(*args, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/openerp/http.py", line 376, in response_wrap
[Fri Nov 21 08:14:50 2014] [error]     response = f(*args, **kw)
[Fri Nov 21 08:14:50 2014] [error]   File "/opt/odoo/odoo/addons/bus/bus.py", line 188, in poll
[Fri Nov 21 08:14:50 2014] [error]     raise Exception("bus.Bus unavailable")
```
??

Make sure your configuration respect the requirements of https://www.odoo.com/documentation/master/setup/deploy.html#id4

**Comment by Atheryl** [comment]
No error on my side 

122.116.73.156 - - [13/Feb/2015:07:19:21 +0000] "GET /openerp.wsgi/longpolling/poll?session_id=xxxxxxxx&jsonp=jQuery18302996272558812052_1423811919713&r=%7B%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22call%22%2C%22params%22%3A%7B%22channels%22%3A%5B%22cefbd78a-e289-4656-b8d5-e3986a60f64b%22%5D%2C%22last%22%3A0%2C%22options%22%3A%7B%22im_presence%22%3Afalse%7D%7D%2C%22id%22%3A109055583%7D&session_id=xxxxxxxx&_=1423811961272 HTTP/1.1" 200 582

**Comment by Atheryl** [comment]
Just to make it more clear, it's working great on the odoo for the operator. Only the client side is not working.

So basically, only visitor don't get updated.

**Comment by jem-odoo** [comment]
Hello, 
to use longpolling, you need to have a proxy for the route /longpolling/, as decribe here : https://www.odoo.com/documentation/master/setup/deploy.html#livechat
So it is a deployment problem, change your server config and everything will be all right !

**Comment by Parker27** [comment]
Thanks for your help Jem, we are looking at that information.
Best Regards

**Comment by Atheryl** [comment]
Hi,

 +1 thanks Jem, actually i expected to be fully workable on the second port, i will try the proxy solution. I might be back on tuesday with a "tutorial" to share, parker27 if you do it before, let me know :)

**Comment by Atheryl** [comment]
Jem,

 Actually I already setup my configuration (It was even done before actually)

ProxyPass /longpolling/poll http://localhost:8072/longpolling/poll/
ProxyPass /longpolling/poll/ http://localhost:8072/longpolling/poll/
ProxyPassReverse /longpolling/poll/ http://localhost:8072/longpolling/poll/

In the apps/odoo/conf/httpd-app.conf

Still it's not working properly.

**Comment by flotho** [comment]
Hy @Atheryl, did you succeed in setting this on Apahce?
regards

**Comment by flotho** [comment]
@Atheryl , I found an nginx con : http://nils.hamerlinck.fr/blog/2015/04/09/install-odoo-vps-ubuntu/ it shoyld help to tunn correctly the apache on

**Comment by flotho** [comment]
@Atheryl ,

The doc said : 
> Instead you must have a proxy redirecting requests whose URL starts with /longpolling/ to the longpolling port

Additionnaly, the apache official doc http://httpd.apache.org/docs/trunk/mod/mod_proxy.html#proxypass precise that the order of directive is important. 
So I don't think your proxy pass is correct. Personnaly I would have tried someything like this (with longer url first):
```
ProxyPass /longpolling  http://gestion:8072/
ProxyPassReverse /longpolling  http://gestion:8072/

ProxyPass / http://gestion:8069/
ProxyPassReverse / http://gestion:8069/
```

**Comment by flotho** [comment]
Unfortunately, I have 404 error intead of bus.error

**Comment by flotho** [comment]
@jem-odoo, I think we're almost done. 

First tests, I set up the foolowing conf and had a dbus error : 
```
ProxyPass / http://gestion:8069/
ProxyPassReverse / http://gestion:8069/

<Proxy />
    Order deny,allow
    Allow from all 
</Proxy>

ProxyPass /longpolling/  http://gestion:8072/
ProxyPassReverse /longpolling/  http://gestion:8072/

<Proxy /longpolling/>
    Order deny,allow
    Allow from all 
</Proxy>

<Location /longpolling/>
    Order allow,deny
    Allow from all
</Location>

<Location />
    Order allow,deny
    Allow from all
</Location>
```
Then I changed the order of the proxies and have a 404 error in odoo :
```
ProxyPass /longpolling/  http://gestion:8072/
ProxyPassReverse /longpolling/  http://gestion:8072/

<Proxy /longpolling/>
    Order deny,allow
    Allow from all 
</Proxy>

ProxyPass / http://gestion:8069/
ProxyPassReverse / http://gestion:8069/

<Proxy />
    Order deny,allow
    Allow from all 
</Proxy>
```
gives :
```
File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
```
So, my proxy is correctly handling the longpolling request but not passing a correct request to odoo. Do you recommand any additionnal set up on preserving host, headers, etc... ?

**Comment by flotho** [comment]
Here are my apache logs :
```
proxy: HTTP: canonicalising URL //gestion:8072/poll
[Sat Apr 25 13:28:51 2015] [debug] proxy_util.c(1521): [client 10.0.130.26] proxy: http: found worker http://gestion:8072/ for http://gestion:8072/poll, referer: https://mind-and-go.com/web
[Sat Apr 25 13:28:51 2015] [debug] mod_proxy.c(1020): Running scheme http handler (attempt 0)
[Sat Apr 25 13:28:51 2015] [debug] mod_proxy_http.c(1967): proxy: HTTP: serving URL http://gestion:8072/poll
[Sat Apr 25 13:28:51 2015] [debug] proxy_util.c(2026): proxy: HTTP: has acquired connection for (gestion)
[Sat Apr 25 13:28:51 2015] [debug] proxy_util.c(2082): proxy: connecting http://gestion:8072/poll to gestion:8072
```

**Comment by flotho** [comment]
any additionnal idea?

**Comment by flotho** [comment]
Additionnaly, could it come from a port renumbering behind a gateway?

**Comment by flotho** [comment]
this one #3793 saved my days, I've setted up the interfaces that wasn't listening on the correct IP.

**Comment by Yenthe666** [comment]
Hi @Parker27,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
