### ISSUE TITLE
[12.0] Calendar: Access error when trying to dismiss calendar notification (calendar_last_notif_ack)

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#39358]
Impacted versions:
v12.0
Steps to reproduce:
Create an event with reminders
![image](https://user-images.githubusercontent.com/10233975/67514583-97789200-f662-11e9-83e2-a1de2e131ada.png)

Add an attendance test user with most basic permissions of an internal users 
![image](https://user-images.githubusercontent.com/10233975/67514663-c8f15d80-f662-11e9-9e67-648e90c16722.png)

Current behavior:

When the notification pop-up, on test user sessión and trying to click on ok button, an access error is triggered

![image](https://user-images.githubusercontent.com/10233975/67514802-17066100-f663-11e9-8b96-04ccd33c946a.png)

Expected behavior:
User with basic permissions be able to check that notification and avoid that they appear again and again

Video/Screenshot link (optional):
https://youtu.be/w4X682HODhU
Replicated at http://665475-12-0-500944.runbot26.odoo.com

**Comment by sswapnesh** [comment]
Seems to be missing `sudo` at 
https://github.com/odoo/odoo/blob/f3d77a650941c1f59da49a63d7b4672874ad2494/addons/calendar/controllers/main.py#L73


Cc @jem-odoo

**Comment by sswapnesh** [comment]
Added Fix on https://github.com/odoo/odoo/pull/39407
