### ISSUE TITLE
[WISH] Save the size of column in tree view after resized.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#39360]
**Impacted versions:**
13.0

**Steps to reproduce:**
odoo 13 add a new feature. User can resize a column in tree view. But if we refresh the web page, the column size is become not resized agian.

![QQ截图20191025105322](https://user-images.githubusercontent.com/5561864/67539742-b08e4b00-f715-11e9-8848-53e4bed4cb89.png)
![QQ截图20191025105359](https://user-images.githubusercontent.com/5561864/67539780-cc91ec80-f715-11e9-9816-8b6c135bafe5.png)

**Expected behavior:**
Save the size of column in tree view after resized.

**Comment by Yenthe666** [comment]
I like the idea, we already have something similar in place for the optional fields in a treeview. This is pretty similar I guess.
@ged-odoo what do you think about this suggestion?

**Comment by tanghulu0608** [comment]
optional fields is a very cool feature,and setting on  optional fields can be saved in the browser. Wish column size can be saved to.

**Comment by pedrobaeza** [comment]
Or maybe the resizing ability is just an unwanted side effect... :stuck_out_tongue_closed_eyes:

**Comment by Yenthe666** [comment]
I actually like it, side effect or not 😆

**Comment by pedrobaeza** [comment]
I'm deciding if I like it or not... In one hand, it's good for "stripping" large auto-sized columns or avoid 2 lines rows, but having the side scroll bar...

**Comment by tanghulu0608** [comment]
users can show or hide some column,and resize the width, this is very cool 😁

**Comment by tanghulu0608** [comment]
Hello everyone, will this feature be added to odoo ?

**Comment by ged-odoo** [comment]
we discussed about this. The main issue is that if we save the column width, then it could happen that a user choose a specific layout, with a browser page opened on a large monitor, then close it, then later, reopen Odoo in a smaller browser window.  Then, the layout of the tree view would be restored and probably completely messed up, with no easy way of making it right, except by manually redoing it, which could be very annoying.

**Comment by ged-odoo** [comment]
Maybe we could save it, along with the current width of the browser window, and when we restore the tree view later, we can check if the width has changed. If it is the same, then we restore, otherwise, we use the default layout

**Comment by pedrobaeza** [comment]
Yeah, not bad idea!

**Comment by Yenthe666** [comment]
Sounds like a good plan @ged-odoo :)

**Comment by tanghulu0608** [comment]
good idea!😀

**Comment by tanghulu0608** [comment]
Hello everyone, any solution to this?

**Comment by pedrobaeza** [comment]
This is not going to be "solved" in stable. It's only an idea for future versions.

**Comment by tanghulu0608** [comment]
OK. Thanks.

**Comment by PrajithPragmatic** [comment]
Bro, Do you resolve this issue???.

**Comment by tanghulu0608** [comment]
Seems not resolved yet.

**Comment by PrajithPragmatic** [comment]
Thanks for the replay Bro

**Comment by zageeks007** [comment]
This is a joke. Resizing of columns shoild be straight forward. ged-odoo's worry can always be fixed with a simple button saying - restore default sizes...! 

I have so many people complaining that they resized something, then when going to the next page it resizes back to whatever. 

Who HIRES people like ged-odoo with that mindset anyway???

**Comment by pedrobaeza** [comment]
@zageeks007 when you have half of the experience or knowledge of Géry, then you will be able to talk about why he is saying that, which is not right now, as you are missing a lot of pieces. Anyway, as your comment is not adding anything valuable to the conversation, I hide it as abuse.

**Comment by Yenthe666** [comment]
I guess we can actually close this topic? One of the product owners basically just said they will not add this:
https://twitter.com/bouvyd/status/1613546353237401605

**Comment by pedrobaeza** [comment]
Yes, I think so.

**Comment by zageeks007** [comment]
> 

you feel abused? 

The thing is - people like you guys make our name feel bad! We think of customer experience. to state that maybe the person suddenly looks at the system from a different screen size and therefore, let's not give that functionality is just pretty stupid if you asked me. And trust me I got more experience that one Javascript dude! 

Anyway - mark it abusive - feel good about yourself!

**Comment by zageeks007** [comment]
@pedrobaeza - I have made a complaint against you! I had a legit request and you publicly stated I have less than half of this developer's experience! 

Let me make something clear - I know odoo inside out and I have made my own coding around it! So please - your bully tactic while I had a PROPER concern regarding this specific subject is totally uncalled for.

**Comment by pedrobaeza** [comment]
I'm locking the thread right now for avoiding further answers that don't add value to the issue.
