### ISSUE TITLE
Define a list of restricted name for fields and raise error when a fied is defined with a restricted name.

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#39361]
Impacted versions:
I'd guess pretty much any version:

Steps to reproduce:
define a field called `init`

```
class Model(models.Model):
    _name = "abc"

    init = fields.Boolean(string="Not ok")
```

Current behavior:

It will fail on the line:
odoo/modules/registry:297 

```
        for model in models:
            model._auto_init()
            model.init() # it will try to call a boolean
```

Expected behavior:

We should be prevented to override important attributes of class using an attribute of type Field. 

Video/Screenshot link (optional):

**Comment by llacroix** [comment]
One solution would be to rename methods to prevent name clashing. In practice, it would make sense to make use of the `__` prefix.

**Comment by Yenthe666** [comment]
Well that's just one of the things you need to keep in mind when developing modules. If we really have to handle every single case like this we'd get an ERP system that would become unworkable because it becomes so complex and with so many options. @pedrobaeza can I get your thoughts?

**Comment by pedrobaeza** [comment]
Name mangling as Python does with `__` is not a good choice in my opinion, as it forces you to set a new layer of naming translation on each possible interaction on the ORM. About the list of "forbidden" names, they are potentially infinite, as you can have a method with that name like the example, but it's difficult to be controlled, as it relies on Python layer (Python allows to do that, having a variable and a method with the same name, being the scope the one that decides which is you invoking). Maintaining a list of already typical forbidden words (init, create, write, unlink...) is also a work that requires a lot of effort across versions. So for me you have to simply learn over the experience and don't use them.

**Comment by Yenthe666** [comment]
Yep, I agree so let's close it off.

**Comment by llacroix** [comment]
>  If we really have to handle every single case like this we'd get an ERP system that would become unworkable because it becomes so complex and with so many options. 

Obviously there is no need to handle single cases, it should be fairly easy to implement something that will detect if the type of an attribute change from a method to a field or the opposite and output a proper warning/error. It doesn't have to be maintained by hand. 

Odoo when buiding a model can track the attributes and prevent changing their types. While allowing callable to have different signatures. So each time it adds a new layer it can execute a check that changes with the same name aren't different things completely. A field could change from one type to an other and a callable could have a different signature but having a callable becoming a field should be non authorized and output a proper warning explaining which model is doing something illegal.

Because right now, if a core module will add a method with the same name as an attribute in a module in let say OCA that has been there for years without issue. The moment the update will be pushed it will completely break external module even thought the modules were "designed" with the experience to not use some names. But you can't predict names that will be used in the future.

Just using a prefix in the odoo code base like _o_init would free some space in the available scope name and reduce the possible collision with the rest of the codebase. 

I mean, if there is an infinite possiblities for naming, then reducing the infinite possibilities to different scope can still prevent collisions in infinite ways. If there's no scope and the decision is to keep it as is and go on with the feel... I may just as well get a vodoo puppet to keep the stack running.
