### ISSUE TITLE
Odoo 13 cron activate button gone?

### ISSUE THREAD

**Issue by codeagencybe** [odoo/odoo#39375]
Impacted versions:
Odoo V13 CE and EE

Steps to reproduce:
Create or edit any available cron in technical settings
In list view, there is a column "active" but if you edit the record, there is no option or button to activate or deactivate a cron

I tried in both my own personal on-premise demo and at official demo demo.odoo.com.
Same issue is in all cases. 

Current behavior:
nothing, button is gone

Expected behavior:
In Odoo 11 and 12, there is a button "on/off" to switch between cron status. 
I would expect Odoo 13 has same button? 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7568546/67568977-f48d4a00-f72d-11e9-89b1-dd885c0b9fce.png)

If somebody can elaborate if this is a bug/known issue or if there is some design change and the activate/deactivate button/toggle is somewhere else? 

Thanks!

**Comment by pedrobaeza** [comment]
Now activate/deactivate records is handled from Action > Archive/Unarchive.

Closing as no issue.

**Comment by codeagencybe** [comment]
euhm... very weird since archiving records means something completely different than enable/disable a function/cron... It's for hiding records like sale orders, tickets, .... 

But thanks for clarifying this. I find this a very bad and confusing design change.

**Comment by pedrobaeza** [comment]
It's a generic mechanism that fits in almost every case. Giving an specific name for each provokes more code maintenance, translation effort, etc.

Any way, for this specific one, it's no so bad at all: you are archiving that cron, which means it's not activated.

**Comment by codeagencybe** [comment]
@pedrobaeza 
Hmm wel perhaps yes, but it still is confusing if you come from Odoo 10, 11, 12 background and then it changes into this at Odoo 13 :)

**Comment by sylnsr** [comment]
@codeagencybe Agreed. Its always appeared to me that the point of these changes is to make sense to the developer deeply involved and not necessarily for newer people who want to spread adoption. The only thing I can recommend is to get used to it.
