### ISSUE TITLE
[13.0] Missing Menu items on website

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#39377]
Impacted versions:
[13.0]

Steps to reproduce:
![missing menu](https://user-images.githubusercontent.com/35446152/67569422-1d620f00-f72f-11e9-80e3-80fc65b0afea.JPG)
missing menu items
![cant click on menu](https://user-images.githubusercontent.com/35446152/67569430-23f08680-f72f-11e9-91df-9a1d5b7e0241.JPG)
cant click on menu in mobile version
Current behavior:
Menu items buttons do not appear on my website.

Expected behavior:
I can edit menu items under Pages tab, but can't get them to show on my website.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Are you clicking in the 3 horizontal lines button?

**Comment by implementosk** [comment]
Yes, in mobile version those 3 horizontal lines don't work and there are no menu items in browser version at all.

**Comment by pedrobaeza** [comment]
Well, in fact I'm not seeing the menus as well in desktop mode.

@JKE-be @rdeodoo do you know why?

**Comment by rdeodoo** [comment]
@qsm-odoo will have a fix asap

**Comment by qsm-odoo** [comment]
Hello, very sorry about that problem. We merged a fix yesterday evening... which broke the loading of the JS in charge of making the menus appear. The solution is being merged by @robodoo (see https://github.com/odoo/odoo/pull/39385).

Again, I apologize for the problems this has caused.

**Comment by pedrobaeza** [comment]
Thanks for the quick reaction!

**Comment by rdeodoo** [comment]
You are welcome, thanks for the report anyway.
The website team at his finest.
I replied to this PR, @JKE-be edited my reply and @qsm-odoo did the job :tada:

**Comment by pedrobaeza** [comment]
Very good team! :smiley:
