### ISSUE TITLE
[13] Customer, vendor references in filters and menus

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#39376]
Impacted versions: 13

Steps to reproduce:
**Module Contacts**
- Filters
- Select filter Customers or Vendors

**Module Sales**
- Menu Orders
- Submenu Customers

**Module Purchase**
- Menu Orders
- Submenu Vendors

Current behavior:
- There is no option to select if partner is a customer or vendor anymore.
- I can select any partner in purchase or sale views.
- So my question is. Why is there a filter for Customers and Vendors and menu items associated with these filters.
- Filter for vendors works for  partners created from Purchase/Orders/Vendors
- Menu item Sales/Orders/Customers dont apply filter Customers at all.

Expected behavior:
- No filter and menus with Customer, Vendor reference.

Video/Screenshot link (optional):
<img width="1013" alt="Screenshot 2019-10-25 at 13 55 58" src="https://user-images.githubusercontent.com/35446152/67569450-3c60a100-f72f-11e9-908d-e8479747c297.png">
<img width="1155" alt="Screenshot 2019-10-25 at 13 53 26" src="https://user-images.githubusercontent.com/35446152/67569451-3c60a100-f72f-11e9-9f1f-f4741f7242e1.png">

**Comment by pedrobaeza** [comment]
This is a design decision. No more that division for avoiding duplicates in vendors and customers. Now there's a rank for putting first in searches those that have made any sale/purchase operation.

Closing as no issue, but feature.

**Comment by implementosk** [comment]
> This is a design decision. No more that division for avoiding duplicates in vendors and customers. Now there's a rank for putting first in searches those that have made any sale/purchase operation.
> 
> Closing as no issue, but feature.

Ok I understand.

Works fine for customers with any sales.

But it seems it doesnt work for vendors.
- I created purchases from different partners.
- I applied Vendors filter on contacts.
- It shows empty view.

**Comment by pedrobaeza** [comment]
I think you have to post invoices.

**Comment by implementosk** [comment]
OK, thanks, tried it, it works that way.
