### ISSUE TITLE
Weird db state after installing website over an empty odoo instance (multiple workers)

### ISSUE THREAD

**Issue by sherpya** [odoo/odoo#39387]
Impacted versions:
13 (maybe also older)

Steps to reproduce:

```
./odoo-bin --addons-path addons --stop-after-init --no-xmlrpc -d odoo13 -i base
./odoo-bin --addons-path addons --workers=8
```

using anonymous browser window:
- login
- installed website
- selected default theme

Current behavior:
- page says the session is expired in multiple places of the page (not always)
- postgres has 10+ idle in transaction processes:

select query from pg_stat_activity where datname = 'odoo13':

ROLLBACK
ROLLBACK
COMMIT
COMMIT
COMMIT
COMMIT
COMMIT
ROLLBACK
ROLLBACK
COMMIT
ROLLBACK
COMMIT
COMMIT
COMMIT
COMMIT
COMMIT
ROLLBACK
COMMIT
COMMIT
ROLLBACK
COMMIT
ROLLBACK
COMMIT

Expected behavior:
None of above

**Comment by sherpya** [comment]
lol @pedrobaeza

**Comment by sherpya** [comment]
I wonder if you are awarded for the number of closed issues (even if not resolved).

The real answer here is that the odoo db connection pool is very lazy closing connections, the problem is you run out of 64 default maxconn easy, even if using single worker

**Comment by pedrobaeza** [comment]
I'm not rewarded nor paid for this. I only remove things that I consider distract the focus on solving issues that are solvable or debatable. The laziness on closing connections is a very deep debate that has been already kept by very skilled people inside Odoo and that surface analysis that you bring is not going to change anything. Also deployment configuration has to do in these things.

That's why I close it as it doesn't provoke any reproducible error currently. Keeping opened more and more issues with no roadmap doesn't bring any value to this issue tracker.

**Comment by sherpya** [comment]
the report is reproducible, **always** (just follow what I wrote), you linked pages that does not talks at all about multiple workers

I'm very bored of you closing bugs without even reading them, it is not the first time.
So be a bit more professional, thanks

**Comment by pedrobaeza** [comment]
As said, that's not an error, it's only a behavior that you don't like and don't understand why, but that's not enough for keeping this opened for ages. If you have an enterprise contract, you can submit it to the paid team for them to consider if it's a problem or not. You can also hire a success pack to Odoo for investigating these things and you'll receive a whole explanation on the thing.

**Comment by sherpya** [comment]
@pedrobaeza I doubt enterprise paid team can fix this behavior (breaking visualization because of connections problems), since I've seen similar problems on odoo site, the problem is different, your reply is pointless and useless, so a this point just close with "I don't want this issue open because I'm pedro", I would be more happy, I mean it, pedro

**Comment by pedrobaeza** [comment]
I want to make you happy, so... "Closing this because of me".

**Comment by gdgellatly** [comment]
Weird, I run 60 workers with 16 default max connections. Never had this. Normally this is a postgres setting, not an odoo one. If you put 8 workers then obviously you will need 64 x 8 plus a few max conns in postgres or use a pooler. Seeing 64x8 touches over 500, you're in pooler territory imo.
