### ISSUE TITLE
[12.0] [web]: Incorrect record filtering when Time ranges is applied on Pivot

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#39397]
Impacted versions: 12.0

Steps to reproduce:   Open Pivot and Apply Time Range Filter
![Screenshot (8)](https://user-images.githubusercontent.com/16624719/67595785-03531b80-f785-11e9-9c7f-8451a8ad978b.png)

Click on `Total` Cell to view filtered records (Eg, October 2019 shows correct records)

Current behavior:
It displays All 39 Records instead of Filtered ones
![Screenshot (7)](https://user-images.githubusercontent.com/16624719/67595670-d56dd700-f784-11e9-8da3-76d63b21d84c.png)

Expected behavior: Display Filtered records (Like v13)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
OPW 2093880

**Comment by sswapnesh** [comment]
@Yenthe666  It should be tagged for `12.0`

**Comment by Yenthe666** [comment]
Oops my bad ;)

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/40344 at https://github.com/odoo/odoo/commit/a355bea5ec7863ae0eefa2c385aa0246cd8098a2
