### ISSUE TITLE
fechtmail service error when job is executed

### ISSUE THREAD

**Issue by ceballos59** [odoo/odoo#39390]
Impacted versions: 11

Steps to reproduce: 
activate service fetchmail job.

Current behavior:
Oct 25 15:05:19 intranet odoo11: ValueError: <class 'imaplib.IMAP4.error'>: "command CLOSE illegal in state AUTH, only allowed in states SELECTED" while evaluating
Oct 25 15:05:19 intranet odoo11: 'model._fetch_mails()'
Oct 25 15:10:21 intranet odoo11: 2019-10-25 12:10:21,098 4534 ERROR tdms2205 odoo.addons.base.ir.ir_cron: Call from cron Mail: Fetchmail Service for server action #102 failed in Job #4

Expected behavior:

line 195 fetchmail              finally:
                                             if imap_server:
                                                 --> i added this line imap_server.select("INBOX")
                                             imap_server.close()
                                             imap_server.logout()
https://techoverflow.net/2019/04/08/how-to-fix-python-imap-command-close-illegal-in-state-auth-only-allowed-in-states-selected/
after that error was fixed.

**Comment by pedrobaeza** [comment]
This is because you haven't configured properly your credentials, so any way, closing that means the same, as no mail is retrieved anyhow.

Closing this as no real issue.
