### ISSUE TITLE
Issue in dropdown menu view

### ISSUE THREAD

**Issue by j209** [odoo/odoo#39402]
ltr mode:

![ltr](https://user-images.githubusercontent.com/18129232/67621178-c89bc280-f81a-11e9-8f0a-7e2b80a8855b.png)

rtl mode:

![rtl](https://user-images.githubusercontent.com/18129232/67621182-d3eeee00-f81a-11e9-8792-056e4173ce5a.png)

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by j209** [comment]
Version 13

**Comment by pedrobaeza** [comment]
@mart-e can you point to the right person for this CSS RTL issue?

**Comment by j209** [comment]
https://github.com/odoo/odoo/issues/38722

**Comment by mart-e** [comment]
This would be @dmo-odoo who developed this web widget.
Could you have a look please? Missing a RTL rule somewhere.

**Comment by dmo-odoo** [comment]
ping @kebeclibre cc @aab-odoo
