### ISSUE TITLE
[odoo 8] context of product_id field in sales form (id: view_order_form) will cause error when search more product 

### ISSUE THREAD

**Issue by u8621011** [odoo/odoo#3940]
The context setting of product_id in form(view_order_form) will bring up the default value of uom in sales order line(product_uom_unit) which will cause user  get a message like "Conversion from Product UoM XXX to Default UoM YYY is not possible as they both belong to different Category!." after click "Search More" of Product Field of sales order line.

**Comment by Yenthe666** [comment]
Hi @u8621011,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
