### ISSUE TITLE
Support move item in test form O2MProxy

### ISSUE THREAD

**Issue by mathben** [odoo/odoo#39404]
Impacted versions: 12/13

It's missing implementation to move item in O2MProxy.
https://github.com/odoo/odoo/blob/13.0/odoo/tests/common.py#L1799

We cannot test when moving item in form.

We can "new", "edit" and "remove".
Or how can we add item in different index?

Thanks for you feedback.

**Comment by pedrobaeza** [comment]
This is not an issue in the software as is. Not having a facility for certain test thing (which I don't really understand at all, as inheritance allows to usually do what you want), it's not something to be fixed.

Any way, if you think it can be improved, please propose a pull request with that improvement, but check stability policy for avoiding improvements in current version, and point to master branch instead.

Closing then as no issue as explained.
