### ISSUE TITLE
13 Error on when try create invoice from sale order,

### ISSUE THREAD

**Issue by bumblebeey** [odoo/odoo#39411]
Impacted versions: 13

Steps to reproduce: Create Invoice from Sales Order

Current behavior:

Expected behavior:

  File "/opt/odoo/odoo/addons/account/models/account_move.py", line 1471, in _move_autocomplete_invoice_lines_create
    move = self_ctx.new(new_vals)
  File "/opt/odoo/odoo/odoo/models.py", line 5316, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo/odoo/odoo/models.py", line 5015, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
ValueError: Invalid field 'origin' on model 'account.move'

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is this reproducible in runbot with latest code?

**Comment by sswapnesh** [comment]
Seems working well on Runbot v13 (With all 3 Invoicing Options)

**Comment by Yenthe666** [comment]
@bumblebeey could you give us an update please? I couldn't reproduce it either.

**Comment by bumblebeey** [comment]
Partner company issue

**Comment by TeleNocPak** [comment]
i also have same problem and i don't know how to use runbot . kindly give answer here..i want to create invoice in odoo13 and here is get error. 
raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'origin' on model 'account.move'

**Comment by sswapnesh** [comment]
> Partner company issue

@bumblebeey  Can you tell me what was the exact Issue?

**Comment by bumblebeey** [comment]
Our partner company write a addon for us,  error source was thats addon. They fixed bug, working well now

**Comment by ITBetty** [comment]
Hola me aparece ese error y no logro avrir los presupuestos: raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'delivery_set' on model 'sale.order'
