### ISSUE TITLE
Stock picking address not printed

### ISSUE THREAD

**Issue by matmicro** [odoo/odoo#39419]
Impacted versions: 10.0

Steps to reproduce:
Go to inventory > Delivery order to do > click on an item > Click Print button
The "Picking Operations.pdf" is printed, but it does not mention the customer shipping address.
Only the name and the email is written.

Current behavior:

Expected behavior:
I need this PDF to mention also the customer address (shipping and billing).

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Version 10 is not more supported

**Comment by pedrobaeza** [comment]
Yes, I'm afraid it's out of support.

If the problem still remains in v11, v12 or v13, please put another issue.

Closing then.
