### ISSUE TITLE
[11] localhost odoo does not appear

### ISSUE THREAD

**Issue by prasojojiwandono** [odoo/odoo#39414]
I have a trouble to run odoo in my local machine. I am using linux manjaro and running odoo 11 in docker, 

and I have starting the docker container by execute command "docker-compose start" or "docker-compose up -d" and when I go to localhost:8069 it just show blank page, but there is odoo logo in tab.

![image](https://user-images.githubusercontent.com/23108110/67663707-af208500-f998-11e9-9cd7-369bd5e0b27b.png)

is there any suggestion to this problem?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a deployment question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
