### ISSUE TITLE
The export of stock.history does not work 

### ISSUE THREAD

**Issue by nono6677** [odoo/odoo#3942]
Hi,

Why the export of export of stock.history does not work ? it's a bug or it's it's normal because there are no view form ?

**Comment by flotho** [comment]
Hy @nono6677, could you precise?
Any message, any screenshot?

**Comment by Yenthe666** [comment]
Hi @nono6677,

I've just tried to export the stock and it works without problems.
If you still face this issue (on the latest source code) please do add more information (screenshots, video, ...) of how to reproduce this and I'll reopen this issue!

Regards,
Yenthe
