### ISSUE TITLE
[13.0] Label on Invoices is not translatable

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#39430]
Impacted versions: 13.0

Steps to reproduce:
Create a new database, install "Invoicing" and go to "Configuration -> Settings -> Taxes -> Advanced Options" field "Label on Invoices".

Current behavior:
The field "Label on Invoices; (account.tax; model - Description; field) does not seem to be translatable. This causes issues that the label on the invoiceline cannot be translated but the "Tax Group" is translatable. 

Expected behavior:
Being able to translate the field "Label in Invoices" so I can set different translations for different taxes as it works with "Tax Group".

Video/Screenshot link (optional):
image of field "Label on Invoices" not translatable:
![image](https://user-images.githubusercontent.com/39414107/67674401-a7eb7e00-f97c-11e9-9751-d23032342f49.png)

image of field "Name - Tax group" is translatable:
![image](https://user-images.githubusercontent.com/39414107/67674545-10d2f600-f97d-11e9-8599-63d570331d07.png)

**Comment by Yenthe666** [comment]
@mart-e is it ok to add the translate option on the field (in stable)?

**Comment by mart-e** [comment]
@Yenthe666 it is ok to add it if the field is not already translatable (spoiler, it is ;-))

**Comment by Yenthe666** [comment]
Yep, you're right, should've checked first. @BusinessAgilityMasters you just didn't install a second language. Result with two languages:
![image](https://user-images.githubusercontent.com/6352350/68744092-2179a200-05f4-11ea-807b-9340980c15de.png)

**Comment by mart-e** [comment]
It is a bit more complicated than that:
The fields are translated when you install the `l10n_multilang` module

https://github.com/odoo/odoo/blob/8bf4b8e015fa61f3929dbb8f1d81e1127272cfbb/addons/l10n_multilang/models/account.py#L26-L30

This module is automatically installed on the chart of accounts of countries with multiple official languages (Belgium, Switzerland, Canada,...). If you wish to have translations on your taxes, you can manually install this module.

**Comment by Yenthe666** [comment]
Ahhh that explains why I've never noticed this, I always use COA's from companies with multi lang. Thanks for the extra clarification!

**Comment by BusinessAgilityMasters** [comment]
> Yep, you're right, should've checked first. @BusinessAgilityMasters you just didn't install a second language. Result with two languages:
> ![image](https://user-images.githubusercontent.com/6352350/68744092-2179a200-05f4-11ea-807b-9340980c15de.png)
We did install 2 languages, to indicate this we provided 2 screenshots with 1 showing a translatable "group tax" and the other one the "tax field". 

The issue is with the "Dutch localization", manually installing l10n_multilang indeed solves this but I believe this should be included in the Dutch localization.

**Comment by mart-e** [comment]
> The issue is with the "Dutch localization", manually installing l10n_multilang indeed solves this but I believe this should be included in the Dutch localization.

Why? There is only one official language in the Netherlands.
The idea is that you only need to translate the accounts and taxes in the languages of the country. If you have specific needs, you can easily fix it by installing this module. This seems fine to me.

**Comment by pedrobaeza** [comment]
@mart-e I can agree somehow with the general idea that you want to translate for example taxes although you live in one language country, as you want to give your entire document translated to foreign customers. Example: in Spain, I want to give to one English customer the invoice putting "0% VAT", instead of "0% IVA".

**Comment by Yenthe666** [comment]
I'm with Pedro here, it makes sense in any country.

**Comment by mart-e** [comment]
This reminds me a bit of the discussion about the currency label at #25531
The main reason about not putting `translate=True` by default on every char field is to avoid having a massive amount of terms to translate while many people would not care about it.
I do understand your point and it would be more user-friendly to have it by default but we don't want to add Chinese translations of every Spanish tax (especially when some are just numbers).

We do not have perfect solution so having a mechanism for it in l10n_multilang seemed like a good compromise.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation, but I don't think it's the same: you don't need to have Spanish taxes translations in `l10n_es` because... they are different objects! What you have there is `account.tax.template`. What is translatable is `account.tax`.

**Comment by mart-e** [comment]
You make a point, I am running out of good reasons so it could be acceptable to translate this field in account :thinking:

**Comment by pedrobaeza** [comment]
@qdp-odoo what is your opinion on this?
