### ISSUE TITLE
[13.0]The user with only warehouse access can not open the product form.

### ISSUE THREAD

**Issue by caihongsoft** [odoo/odoo#39431]
Impacted versions:13.0c&e

Steps to reproduce: Configure a user with only warehouse manager access.

Current behavior:An error occurred when the user open a product form.
the error is  'Something went wrong,  product.product(2,).sales_count'

Expected behavior:

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Looking at the error it seems due to Not setting default value for sales_count

**Comment by Yenthe666** [comment]
It's reproducable on a default Odoo 13 runbot instance.

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/39446

**Comment by caihongsoft** [comment]
Thanks all.

**Comment by sswapnesh** [comment]
The fix isn't merged yet so it should be okay to keep this open.
