### ISSUE TITLE
l10n_ch - Automation of ISR vendors bills creation 

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#39469]
As discussed with @jcr-odoo, I would like to describe here what is usual process in Switzerland to register supplier invoices.

1 - you create your vendor bill manual and fill in the ISR number manually
2 - You have a paypen (ie: https://shop.crealogix.com/scanner/paypen-ii.html?___store=fr). it works like a keyboard : you put your cursor into field payment reference on the vendor bill form  and you scan the ISR
3 - very common use case : you scan the scan line on the payment slip (the very long one at bottom right) and the system create a new vendor bill, it can recognize the correct supplier thanks to the client number + postal account number and the total amount of the invoice is put as unit price on the invoice line. 
4 - For large company : same principle but you use the giromat (https://www.youtube.com/watch?v=8PpCy_lOCd4). You can put into this machine several payment slip at once. It will create new supplier invoices in mass.
5 - You scan a batch of pdf invoices + ISR. The system knows that after each ISR payment slip this is a new invoice. A draft invoice is created in the system for each recognized invoice+ISR. Scanned Invoices+ISR are added as attachment for each draft invoice. And there is a double check mechanism comparing sum of all invoice lines with the total amount from scan line.

**Comment by dscherrer** [comment]
Comment to point 5: 
I added a screenshot of the leading swiss ERP system Abacus that shows their way to create vendor bills from a batch of vendor invoices in a PDF file:
https://www.abacus.ch/de/produkte/enterprise/finanzsoftware/#gallery-4
and the respective documentation, see page 27 of the PDF:
https://media.abacus.ch/abacus/produkte/finanzsoftware/Prosp_Aba_Finanzsoftware_2019_FR_WEB.PDF
