### ISSUE TITLE
[11.0] Widget image not render on pdf report from website portal or  xmlrpc api

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#39476]
Impacted versions:
11.0
Steps to reproduce:
1.- on a report add a field image
2.- set tag <span t-field='o.partner_id.image' t-field-options="{'widget': 'image'}" />
3.- render pdf nor backoffice, use example, website customer portal , ( with partner's invoice) or fire print report from external xmlrpc api

Current behavior:
1.- using image widget works only if pdf is rendered from backoffice

2.- but if widget is replaced by <img t-att-src="'data:image/png;base64,%s' % to_text(o.partner_id.image)"/> works

Expected behavior:

render pdf if it is not fired from backoffice

**Comment by pedrobaeza** [comment]
The image widget is not intended for that use. If you want an image in a PDF, please check how they are generated in several parts of Odoo, like the header.

Closing as no issue, but misuse of the widget.
