### ISSUE TITLE
Fiscal position is not recalculated on change in a contact

### ISSUE THREAD

**Issue by wakiem** [odoo/odoo#39495]
Impacted versions: 12.0

Steps to reproduce:
You need a fiscal position with "VAT required" (let's call it FP1).
Create a contact without VAT number.
Create a SO for the contact.
Fiscal position NULL will be saved on the SO.
Add a VAT number to the contact.
Add products to the SO.

Current behavior:
The SO will not use FP1, it will still use FP NULL

Expected behavior:
The SO should use FP1.

**Comment by pedrobaeza** [comment]
And why it should use FP1? I don't see in your steps anything that indicates that it "should use it".

**Comment by wakiem** [comment]
I have this fiscal position:
![Screenshot 2019-10-29 at 12 37 15](https://user-images.githubusercontent.com/21678441/67763830-df276100-fa48-11e9-9972-d741901aaae9.png)

And all my products are set up with Tax: _S. 21%_

So any customer with an address in the EU (excl. Belgium) and with a VAT number, should get this tax: _S. 0% EU M._

Now consider this scenario:
1. I create a customer with an address in Italy but without a VAT number
2. I create a SO for this customer and add a product, the tax will be: _S. 21%_. At this point the fiscal position on the SO will be set to NULL.
3. I realize the customer actually has a VAT number and I update the customer.
4. I add new products to the existing SO (or I duplicate the SO and add some products in there).
5. The tax will still be _S. 21%_ on these new products, even though the customer already has a VAT number assigned to him at this point. The customer is living in Italy, and has a VAT number assigned to him, so at this point any product added to the SO should be using _S. 0% EU M._ But because the fiscal position is saved on the SO, and not updated when a change is made to the customer, the tax is still _S. 21%_

**Comment by Yenthe666** [comment]
@wakiem this is indeed true and happens for all of us. The only way to get this working is if either Odoo or you add custom code to detect changes on the customer and check it every time on the quotes/SO's.
I think this was not done on purpose for performance :) @qsm-odoo perhaps you can give feedback?

**Comment by pedrobaeza** [comment]
It should be that way. You can't pretend that adding the VAT in the partner triggers the re-computation of all the existing sales orders without notice, using a dark heuristic for solving conflicts like sales order half invoiced, other fiscal position assigned, etc, and getting down the performance of the operation.

To solve the problem, simply assign manually the fiscal position in the sales order and then the re-computation will be done on that sales order.

Or under your own responsibility, do the custom module that triggers that.

Any way, I have it very clear that this is not an issue per se, but how the system works, so closing without waiting for further comments. If I'm wrong, this can be reopened.

**Comment by Yenthe666** [comment]
@pedrobaeza not quite. Setting the fiscal position after you've saved the SO won't change the VAT on the SO lines, I've come around a similar case very recently.
But, yes, to conclude: this is all desired behaviour, it would become way to dangerous/random if we'd try to recompute them on every change. This is not going to be changed (for a good reason)

**Comment by wakiem** [comment]
I'm not saying that existing SO's should be changed. Definitely not. But simply that it doesn't make sense that products added after the VAT change are still using the old fiscal position, which at that point is not the correct one anymore.

**Comment by pedrobaeza** [comment]
@wakiem the same rationale applies to that: you have already changed partner, that is where fiscal position is evaluated, and doing what you say will trigger same re-computations.

@Yenthe666 since https://github.com/odoo/odoo/commit/94716a3f14d929574c46ef165e4364d12a5903ed#diff-3de7d15f09aac4a2e96ae7740b24a100R66-R69, the update of the fiscal position triggers the recomputation of taxes.

**Comment by qsm-odoo** [comment]
@Yenthe666 I think that you wanted to ping @qdp-odoo

**Comment by Yenthe666** [comment]
AHHHH! Yes indeed. Sorry! :)

**Comment by qdp-odoo** [comment]
Listen to @pedrobaeza, he's right :-)
