### ISSUE TITLE
Pricelist report doesn't apply the "Supplier price form product form" rule.

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#395]
https://bugs.launchpad.net/ocb-addons/+bug/1174160
1. Open the product "USB Adaptor" sale price 18.00.
2. Open the public pricelist(Sale), create the 4 different rule more.
   - Min qty 4: Discount 5%
   - Min qty 9 : discount 10%
   - Min qty 19 : Discount 15%
   - Min qty 29 : discount 20%
3. Try to print pricelist report with qty, 1, 5, 10, 20, 30 which print correct.(works fine this)
4. Open the product form view, go to supplier tab enter the price and qty which is also one kind of pricelist.
5. enter the value
   
   qty price
    5 12
   10 11
   20 10
   30 09
6. open the both pricelist, go to pricelist version>rule and select the price based on "Supplier price form product form" for both the sale and purchase pricelist both.
7. try to print pricelist report with any pricelist it doesn't affect the value and always print the sale price doesn't affect the pricelist rule.

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
