### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [odoo/odoo#39531]
Impacted versions: 12.0

Steps to reproduce: just activate the developer mode and goto settings->technical->scheduled actions, then double click on a action to edit.

Current behavior: Uncaught TypeError: Cannot read property 'tooltip' of undefined

Expected behavior: edit the document

Video/Screenshot link (optional):

![erro odoo](https://user-images.githubusercontent.com/12830044/67789206-58778180-fa52-11e9-9c4a-b8714f431892.png)

This steps was reproduced on odoobot (http://runbot.odoo.com/runbot - admin/admin) as screenshot

Thanks in advanced.

**Comment by pedrobaeza** [comment]
Why double click instead of one single click? Maybe it's because you do the second click while loading the form.

**Comment by Yenthe666** [comment]
True that it just takes one click but there are plenty of people who click twice actually :) I guess we could still resolve it. @ged-odoo for the JS team

**Comment by Alexandre-Bernardes** [comment]
> Why double click instead of one single click? Maybe it's because you do the second click while loading the form.

Because my users insist on using a double click! 
But still not a problem to be solved?

**Comment by pedrobaeza** [comment]
Yes, but there's an inner problem in asynchronous operations in web clients that are difficult to handle. It's the same problem as clicking on a half loaded web page: you will get unexpected results. The desirable thing is to avoid any possible error, but this is not always easy to be got. And it's even not easy to be reproducible, as you need to act in a certain moment of time when the resources are loaded in a certain state.

**Comment by devxetechs** [comment]
Saludos!
El error no es nada mas por hacer hacer doble clic.

The error is nothing more to double click

**Comment by gustotc** [comment]
The same thing happens to me and my clients.

Suggestion: How would you handle the error of not showing on the screen? Because it scares customers of such messages.
