### ISSUE TITLE
[13.0] Error when editing MRP tree view (mrp.view_stock_move_raw_tree)

### ISSUE THREAD

**Issue by andrenaught** [odoo/odoo#39543]
Impacted versions: 13.0

Steps to reproduce: 

1. Debug ON, Go to Technical -> User Interface -> Views
2. Search and go into `stock.move.raw.tree`, external ID should be: `mrp.view_stock_move_raw_tree`
3. Edit -> add `editable = "top"` attribute to the `tree` tag

```
<tree editable="top" delete="0" default_order="is_done,sequence" ...>
```

4. Save. An error will pop out:

```
Error while validating view

Field 'product_uom_category_id' used in attributes must be present in view but is missing:
 - 'product_uom_category_id' in domain="[('category_id', '=', product_uom_category_id)]"

Error context:
View `stock.move.raw.tree`
[view_id: 617, xml_id: mrp.view_stock_move_raw_tree, model: stock.move, parent_id: n/a]
```

Proposed Solution:
Currently I just follow the what error says and add `<field name="product_uom_category_id" />` inside the tree, and it fixes it (probably a good idea to add `invisible` attribute as well). Just add this field in the core module's view

**Comment by pedrobaeza** [comment]
Please propose the PR adding that.

**Comment by Yenthe666** [comment]
I've made a PR for it and indeed you can only edit the tree view once the field is in there to qualify the domain.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/4873e5ef3192480fdd3889331f13ff0e10ba5d6a
