### ISSUE TITLE
Importing translation does not import source

### ISSUE THREAD

**Issue by unproZhai** [odoo/odoo#39544]
Impacted versions: v12

Steps to reproduce: Settings -> Translations -> Translated Terms -> Import

Current behavior: source is not imported

Expected behavior: source should be imported

Video/Screenshot link (optional): 
<img width="1178" alt="Screen Shot 2019-10-29 at 17 50 39" src="https://user-images.githubusercontent.com/42622194/67812105-ab623080-fa74-11e9-9734-ed504b6739b8.png">

Additional Details: I was trying to import translations for product names and category names. And I tried to import them with all other different data columns, but all other data are imported except source. The internal source is successfully imported and I can search through it. But since source is not imported, translation is not successfully done.

**Comment by Yenthe666** [comment]
Hi,

Can you reproduce this on the latest Odoo 12.0 at runbot.odoo.com? Can you add steps and an example CSV to reproduce this behaviour please?
CC @mart-e

**Comment by mart-e** [comment]
> The internal source is successfully imported and I can search through it. But since source is not imported, translation is not successfully done.

`source` is not an importable field, it is a computed field (unlike `src`, the "internal source"). All these are technical, you should not really worry about if it is recomputed or not but, does the translations works or not?
For instance, in version 13, we have removed the field `source` as it is not very useful, so you should not have any issue with your translations, even if you don't see a value there.

**Comment by unproZhai** [comment]
The translation does not work, and internal source is successfully imported.

**Comment by unproZhai** [comment]
Thank you so much for the response but how would I get the record id (res_id)? The correct translated term with record id is not showed in the translated term list unless I go to the category page and click that little earth icon.

**Comment by mart-e** [comment]
Even if a field is not displayed, you can add it in the export wizard. Also it is simply the ID of your product.category so easy to fetch from there too.

**Comment by unproZhai** [comment]
So first of all, thanks a lot for all the info. I followed your steps and the translation works! And there is another problem, that is when I go to the category tree view in Chinese mode: the tree list show like this: in English
<img width="930" alt="Screen Shot 2019-10-31 at 09 46 14" src="https://user-images.githubusercontent.com/42622194/67952199-4a953e00-fbc3-11e9-81f5-96733a008a27.png">
And if I click any category in this list and enter the specific category page, it's showed back in Chinese:
<img width="937" alt="Screen Shot 2019-10-31 at 09 47 06" src="https://user-images.githubusercontent.com/42622194/67952264-68fb3980-fbc3-11e9-8f13-4f72298b84ba.png">
Also, if I search by English words (cuz the words are displayed in English in the list), I can not find anything (even I can see the word is right there in the list):
<img width="937" alt="Screen Shot 2019-10-31 at 09 47 56" src="https://user-images.githubusercontent.com/42622194/67952328-87613500-fbc3-11e9-87c9-8cff4cc63288.png">
If I search by Chinese, I can do find the category, still display in English tho. You can clearly see the difference.
![image](https://user-images.githubusercontent.com/42622194/67952472-bd061e00-fbc3-11e9-9687-33e0aeb3d203.png)
I also went to click the little earth icon to check the actual translated term and that one is correct. Please let me know how to fix this. Thank you!

**Comment by mart-e** [comment]
The tree view is not translatable, this is a different issue that has already been raised multiple time
See #23867 for instance.
Unfortunately, there is no solution for this (in 13.0 we even removed the translate attribute on the category name directly).

**Comment by unproZhai** [comment]
LMAO Still thanks a lot!
