### ISSUE TITLE
Changing sql constraints from parent model no longer possible

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#3957]
In OpenERP 7 there was an established pattern that allowed creators of inheriting model classes to modify sql constrained defined in parent class. You just needed to define a new constraint with the same name (the technique is for example [described in this forum thread](https://www.odoo.com/forum/help-1/question/remove-sql-constraints-5431)).

In Odoo 8 this no longer works. If you define a constrain with the same name as the one in parent model Odoo tries to use them both, but the parent's constraints are executed later, so child constraint is immediately overwritten by the parent constraint.

It seems to be caused by the following line in `BaseModel`'s `_build_model` method:

    sql_constraints = cls._sql_constraints + \
                      parent_class._sql_constraints

Because of this constraints from parent class are placed AFTER current class's constraints. The list is later used in the `_add_sql_constraints` method, which uses the list to execute the constraints one after another, in the same order.

I wonder if the change of behavior between OpenERP 7 and Odoo 8 was intentional. As far as I know there are no workarounds or other patterns for modifying parent class's SQL constraints.

**Comment by rco-odoo** [comment]
Fixed by 35edb68.
