### ISSUE TITLE
[base] Date field in res.partner

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#39585]
Date field does not use anywhere and always is null but we build an index for it.
Maybe remove it in master?
https://github.com/odoo/odoo/blob/ebdbdde5a64cc9226991ec4a2d200e976a0802bd/odoo/addons/base/models/res_partner.py#L143

**Comment by Yenthe666** [comment]
Feel free to create a PR if you think you can improve something in Odoo :-) Indeed against master.
