### ISSUE TITLE
[Master] Human Resources -> My Current Timesheet Uncaught Error: QWeb2

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#3958]
When attempting to view current time sheet the following error is thrown via the browser.
Uncaught Error: QWeb2 - template['hr_timesheet_sheet.WeeklyTimesheet']: Runtime Error: TypeError: undefined is not a function
https://www.andrews-enterprise.co.uk/web/js/web.assets_common/2a94a6d:1017

Checking the log file no error was visible.

Attempted with Website Settings of compress html and use cdn both on and off to see if this was the cause.

Using up to date master branch updated last at 29/11/14 16:00 GMT.

**Comment by Yenthe666** [comment]
Hi @AidenAndrews ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
