### ISSUE TITLE
Receiving Products doesn't update average cost

### ISSUE THREAD

**Issue by quique123** [odoo/odoo#3959]
The system is calculating average cost.  Its just that if I enter a PO and receive those products in:

Purchasing > Receive Products > Receive Products ... it doesnt update the unit cost.  It only updates the qty.

if I receive those new products via:

Warehouse > Products Moves > Receive Products ... it doesnt update the unit cost.  It only updates the qty.

It only works if I receive those products via:

Purchasing > Receive Products > Incoming Shipments

**Comment by Yenthe666** [comment]
Hi @quique123 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
