### ISSUE TITLE
[7.0] Wrong entry generated on expenses

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#396]
https://bugs.launchpad.net/ocb-addons/+bug/1181283

Wrong entries generated if on you expenses you have a product with a vat 'tax included' or tax 0% (even with no tax code set up on vat amount ... only on base amount)

please see my print screen attached

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
