### ISSUE TITLE
[v11]Google Calendar double sync with users that use Outlook

### ISSUE THREAD

**Issue by anabeladamas** [odoo/odoo#39606]
**Impacted versions:**
11.0-20191004
**Steps to reproduce:**
I have several users doing Sync with google calendar, some of them use Outlook (GSuite Calendar).
**Current behavior:**
After sync I get several meetings for the same event. 
id   state  partner_id  create_uid google_internal_event_id 
17	"accepted"	114	172	"_60q30c1g60o...0"
16	"needsAction"	143	172	"_60q30c1g60o...0"
18	"accepted"	113	172	"_60q30c1g60o...0"
1833	"accepted"	113	172	"hfqcrlh8ae...42ceo"
1835	"needsAction"	143	172	"hfqcrlh8ae...42ceo"
1834	"accepted"	114	172	"hfqcrlh8ae...42ceo"

**Expected behavior:**
The meetings starting with "_" shouldn't create an event. 
I thougth this https://code.forksand.com/odoo/odoo/commit/4ca9ee2548cda201133ff20a42e404b005082b59?lang=pt-BR prevent this, but my version has this code and I'm still having the event twice in my database. 

How can I prevent this duplication?

**Comment by anabeladamas** [comment]
I figure it out how to reproduce this error.
**Steps to reproduce:**
I have several users doing Sync with google calendar, some of them use Outlook (GSuite Calendar).
* User A creates an event in Outlook and invite the user B; 
* User B, in Odoo, click on button "Sync with Google"; 
* User A, in Odoo, click on button "Sync with Google" ---> in this step, 2 events are already created (info duplicated )); 
* User B, in Odoo, click on button "Sync with Google" ---> in this step, 3 events are already created. 
* User A, in Odoo, click on button "Sync with Google" ---> in this step, 4 events are already created.

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe
