### ISSUE TITLE
OpenERP [8.0] version couldn't installing from .deb with packages

### ISSUE THREAD

**Issue by Bharath069** [odoo/odoo#39619]
When I was installing the OpenERP 8.0 version **odoo_8.0.20171009_all.deb Not found**
Please update the correct version of 8.0 with packages, could not installing from this below command line.

**wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/8.0/nightly/deb/ ./" >> /etc/apt/sources.list
apt-get update && apt-get install odoo**

**Comment by Bharath069** [comment]
Please be adding the **odoo_8.0.20171009_all.deb** in Nightly odoo deb folder

**Comment by Elkasitu** [comment]
Hi, Odoo version 8.0 is no longer supported.

Currently supported versions are 11, 12 and 13.
