### ISSUE TITLE
date_start and date_stop on mrp.bom and mrp.bom.line doesn't take into account the date of the manufacture only the creation date.

### ISSUE THREAD

**Issue by kitsunde** [odoo/odoo#3962]
Since delayed manufacturing is a core portion of `sale.order` through the `_get_date_planned` method, it seems like `date_start` and `date_stop` should be calculated against that rather than the manufacturing creation date. We schedule 4 weeks worth of manufacturing independently of the order creation date.

**Comment by matt454357** [comment]
No, let's remove bom_id from the procurement order.  Why is it there, anyway?  Shouldn't we fix the mrp.bom model?

The BOM gets selected when the MO is confirmed. 
As you must know, _bom_find() uses "time" (now) for comparison:
```python
domain = domain + ['|',
    ('date_start', '=', False), 
    ('date_start', '<=', time.strftime(DEFAULT_SERVER_DATETIME_FORMAT)),
    '|',
    ('date_stop', '=', False), 
    ('date_stop', '>=', time.strftime(DEFAULT_SERVER_DATETIME_FORMAT))]
```
So does _bom_explode():
```python
for bom_line_id in bom.bom_line_ids:
    if bom_line_id.date_start and bom_line_id.date_start > time.strftime(DEFAULT_SERVER_DATETIME_FORMAT) or \
            bom_line_id.date_stop and bom_line_id.date_stop < time.strftime(DEFAULT_SERVER_DATETIME_FORMAT):
                continue
```

**Comment by Celc** [comment]
@matt454357 Yes I know and I agree with you, my code above is only a workaround and not an actual fix. My initial attempt was to fix it there but for reasons I can't recallI struggled to get all the contextual information I needed when it was scheduling the MO's for components.

This issue is only about it time now in `_bom_find()` and  `_bom_explode()` as opposed to using the actual manufacturing date.

**Comment by Yenthe666** [comment]
Hi @kitsunde ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Your proposed PR might still make sense against 9.0 but it is outdated so it would need work again.

Regards,
Yenthe
