### ISSUE TITLE
Odoo 8: BUG Tree editable="bottom"

### ISSUE THREAD

**Issue by Julien-BARRAU** [odoo/odoo#3966]
Hi,

In Form View with field having tree editable bottom like :  <tree string="Account Mapping" editable="bottom"> in addons/account/partner_view.xml

When scrolling in window, the first click on a row make the row display in the wrong place. 

![editable_bottom_bug](https://cloud.githubusercontent.com/assets/8124255/5242201/3497a2ae-7947-11e4-99b6-17ea25915cbc.PNG)

Moreover, having validation issue, back in Tree view, click on Create, the line edited is displayed

![image](https://cloud.githubusercontent.com/assets/8124255/5242241/1aae9efa-7948-11e4-875d-631a9550851f.png)

Then click on create :

![image](https://cloud.githubusercontent.com/assets/8124255/5242250/4a4a5f28-7948-11e4-8762-6c4402231e92.png)

Regards,

**Comment by nle-odoo** [comment]
Hello,

It should be solved since https://github.com/odoo/odoo/commit/e2930e19
