### ISSUE TITLE
Refuse Leave Allocation will raise singleton error

### ISSUE THREAD

**Issue by pooja-zakhariya** [odoo/odoo#39688]
Impacted versions:
12.0

Steps to reproduce:
- Create a leave allocation with Mode By Company
- Approve it than refuse it. It will process to cancel linked allocations but as iteration removed in commit 'e6d26946e62c3e6df5a0511d0102c04c533d2472'.

Current behavior:
System raise singleton error for linked allocations when Refuse main allocation

Expected behavior:
System should Refuse all linked allocations
![leave_allocation_error](https://user-images.githubusercontent.com/4104012/68005721-29ece700-fc9c-11e9-8125-4968bd7ffad9.png)

Video/Screenshot link (optional):
![leave_allocation_error](https://user-images.githubusercontent.com/4104012/68005738-35d8a900-fc9c-11e9-9164-0c8975a2b5f4.png)

**Comment by Yenthe666** [comment]
@RomainLibert I think you've introduced this one with https://github.com/odoo/odoo/commit/e6d26946e62c3e6df5a0511d0102c04c533d2472 ;)

**Comment by LucasLefevre** [comment]
Hello @pooja-zakhariya 
The issue was fixed in https://github.com/odoo/odoo/pull/39721
Thanks for the feedback!

**Comment by pooja-zakhariya** [comment]
> Hello @pooja-zakhariya
> The issue was fixed in #39721
> Thanks for the feedback!

Thank you for fixing this quickly
