### ISSUE TITLE
Event: price on website event list always "FREE"

### ISSUE THREAD

**Issue by fr3aker** [odoo/odoo#39691]
Impacted versions:
Odoo 13 (branch `13.0`) (5e562eae40c2c09cfc0545ed78ad2e91af525dd5)

Steps to reproduce:
1. activate Odoo event module
2. create a new event
3. add event ticket with price
4. go to website event list (default http path: `/event`)
5. event price shows "FREE"

note:
when viewing the event itself the ticket price is shown correctly on the registration form

Current behavior:
price shown is always "FREE"

Expected behavior:
price shown is lowest price (or price range), depending on associated tickets

Video/Screenshot link (optional):
![admin](https://user-images.githubusercontent.com/114561/68030443-c2de2b00-fcb9-11e9-9016-7aeef61bbac4.png)
![website](https://user-images.githubusercontent.com/114561/68030444-c2de2b00-fcb9-11e9-931e-767f1cc3ee7c.png)

**Comment by sswapnesh** [comment]
I could not reproduce this on latest Runbot at http://674908-13-0-12a2d1.runbot14.odoo.com/event/conference-for-architects-2019-11-06-3/register

It seems working well there
![Screenshot (1)](https://user-images.githubusercontent.com/16624719/68068555-0f8a3a80-fd7c-11e9-8bf5-4ec284cb8c98.png)
![Screenshot (2)](https://user-images.githubusercontent.com/16624719/68068559-20d34700-fd7c-11e9-8e39-b16830faba17.png)

**Comment by LaMachinerieDigitale** [comment]
i confirm. The issue still exist on the lastest runbot

**Comment by hydrandt** [comment]
I am about to investigate this. If you've solved this issue, please share :-)

**Comment by bst-bhc** [comment]
@mart-e we still face the issue on the runbot :(

**Comment by Yenthe666** [comment]
This is indeed still a bug in Odoo it seems. I've reported it through my enterprise license to get this resolved. OPW `2256857`

**Comment by josafar** [comment]
still a bug... OE version

**Comment by sswapnesh** [comment]
> This is indeed still a bug in Odoo it seems. I've reported it through my enterprise license to get this resolved. OPW `2256857`

Any updates on OPW ?

**Comment by Yenthe666** [comment]
This was pretty much handled in https://github.com/odoo/odoo/commit/169f01be771adf857bd9a71e9c4dad55e8c1ca8f
@josafar can you reproduce it on the latest 13.0 builds? If so, can you add steps?

**Comment by sswapnesh** [comment]
Checked on Runbot and has been Fixed (On Community + Enterprise both)
