### ISSUE TITLE
       [Trunk/7.0] Refund payment: Error occurred while validating the field(s) amount_currency

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#397]
https://bugs.launchpad.net/ocb-addons/+bug/1181291

http://7-0-11185.runbot.openerp.com/?db=7-0-11185-all&ts=1368805793379#id=62&view_type=form&model=account.invoice&menu_id=422&action=462

I create a purchase refund in USD

I pay it with usd bank (USD journal)

pay and

ValidateError

Error occurred while validating the field(s) amount_currency: The amount expressed in the secondary currency must be positive when the journal item is a debit and negative when if it is a credit.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
