### ISSUE TITLE
The title on the UOM category is wrong as well as no Group by given on the UOM

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#3970]
Go to Sales - > Configuration -> Unit Of Measure

In the List view the heading of the second column is wrong , it should be UOM Category not Product Category (See the link)

https://docs.google.com/file/d/0B5j41T1Hqv1sTjlvOUZwY0xhOUk/edit?usp=drivesdk

Second issue is , there should be a group by which should be on UOM Categories , when I apply that group I can see the UOMs of that category (for example WEIGHT (category) , KG,GRAM and Tonne are the UOM of this category)

**Comment by Yenthe666** [comment]
Hi @jni-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
