### ISSUE TITLE
IoTBox Not Detecting Printer

### ISSUE THREAD

**Issue by khalidtkl** [odoo/odoo#39702]
Impacted versions: 19.10 IoTBox, Odoo 13

Current behavior: I have burnt the latest version of IoT 19.10 on raspberry pi 3 to run on Odoo 13. It runs properly but it does not detect the connected POS printer by USB. I have tried many printers, Marvel 16080 and Epson TM-T88V knowing that they used to work with Odoo 12 and IotBox 19.07. Any help with this problem?!

**Comment by pedrobaeza** [comment]
You need to put at least some logs of the IoTBox for trying to know the problem.

**Comment by khalidtkl** [comment]
where I can find the log of the IoTBox??

**Comment by pedrobaeza** [comment]
You have to access via SSH or directly through an screen and keyboard connected to the device, and check for the file /var/log/odoo/odoo-server.log.

**Comment by khalidtkl** [comment]
I have checked using "tail -f /var/log/odoo/odoo-server.log" and it totally empty. 
![Screenshot from 2019-11-04 12-00-33](https://user-images.githubusercontent.com/51122022/68109140-db895380-fefa-11e9-8845-da8ef51b6307.png)

**Comment by pedrobaeza** [comment]
Maybe that one is not the current path in IoTBox. Please check for the config file to see which one is used.

**Comment by khalidtkl** [comment]
I have checked and I found that it is the same path.
[odoo.txt](https://github.com/odoo/odoo/files/3803333/odoo.txt)

**Comment by pedrobaeza** [comment]
Then something seems to not be working at all if no output is thrown... Is Odoo running on IoTBox?

**Comment by pedrobaeza** [comment]
@switch87 maybe you can help me here if I'm overseeing something.

**Comment by khalidtkl** [comment]
> Then something seems to not be working at all if no output is thrown... Is Odoo running on IoTBox?

I did burn the image from this link "https://nightly.odoo.com/master/iotbox/" which supposedly it works automatically. It runs and gives an IP but it does not detect the POS printers, while it detects other printers shared on the network.

**Comment by pedrobaeza** [comment]
I'm afraid this is out of my scope then, as I haven't used directly an IoTBox. I have pinged already someone that can give you a hint, but not sure the problem is on IotBox itself.

**Comment by qle-odoo** [comment]
@khalidtkl 
Hello can you go to cups and take a screen shoot of your list of printer ?
![screenshot-10 30 16 21_8069-2019 11 04-14_25_54](https://user-images.githubusercontent.com/38907656/68124299-58262d00-ff0f-11e9-9e38-9425d92d6736.png)
![screenshot-10 30 15 188_631-2019 11 04-14_27_15](https://user-images.githubusercontent.com/38907656/68124298-58262d00-ff0f-11e9-98dc-e6feb53ec260.png)
![screenshot-10 30 15 188_631-2019 11 04-14_28_46](https://user-images.githubusercontent.com/38907656/68124345-72f8a180-ff0f-11e9-9f40-c230330628ee.png)

**Comment by khalidtkl** [comment]
Here is the printers list.

![Screenshot from 2019-11-04 17-20-42](https://user-images.githubusercontent.com/51122022/68127910-d8588c80-ff27-11e9-8e38-60ffc16aaf39.png)

**Comment by khalidtkl** [comment]
Any update for this problem??

**Comment by khalidtkl** [comment]
Is there anything I can help with to figure out the problem??

**Comment by Yenthe666** [comment]
@khalidtkl as long as there is no response it means nobody had time to look at this issue yet. The Github tracker is based on a a best effort so you'll need some patience.

**Comment by khalidtkl** [comment]
@qle-odoo Thank you. It does work right now.

**Comment by flotho** [comment]
hi @khalidtkl ,

did you do something special to solve this issue ?
