### ISSUE TITLE
[13.0] Issue in RTL pivot reports view

### ISSUE THREAD

**Issue by j209** [odoo/odoo#39728]
ltr mode:

![ltr](https://user-images.githubusercontent.com/18129232/68117202-e7ccdb00-ff11-11e9-8d5f-d33dec20c4cc.png)

rtl mode:

![rtl](https://user-images.githubusercontent.com/18129232/68117213-ed2a2580-ff11-11e9-88c0-416a30b970d8.png)

**Comment by pedrobaeza** [comment]
Odoo version? (please always include this basic information)

**Comment by j209** [comment]
Pardon me!
Version 13.

**Comment by j209** [comment]
Any update?

**Comment by j209** [comment]
Fixed and resolved via [this PR](https://github.com/odoo/odoo/pull/41200)
