### ISSUE TITLE
Email attachment is not working in Marketing / Mass mailing 

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#3977]
It is possible to attach a file to an email in the mass mailing module (v8) but the file is not send out with the message.

**Comment by Yenthe666** [comment]
Hi @avanzella,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
