### ISSUE TITLE
Multicompany error when doing an inventory adjustment

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#39785]
Impacted versions: 13

**Steps to reproduce:** Create an inventory adjustment with two products

**Current behavior:** Error message (see below)

**Expected behavior:** Default to current company?

![Inventory adjustment error](https://user-images.githubusercontent.com/38899643/68175822-75193980-ffbd-11e9-9bed-674797038710.png)

The requested operation ("create" on "Inventory" (stock.inventory)) was rejected because of the following rules:
- Inventory multi-company

Note: this might be a multi-company issue.

(Records: Inventory (id=8), User: Mitchell Admin (id=2))

**Comment by Yenthe666** [comment]
Thanks for the report @ctringham! I can confirm this is an issue on the latest Odoo 13. 
I've reported it with my enterprise license as we'll need to do inventory adjustments like this too soon :)
OPW `2119338`

**Comment by Yenthe666** [comment]
Okay I've checked this one with Odoo and I've got feedback. Conclusion:
- This is desired behaviour as you cannot create an inventory adjustment under the other company. You should switch to another company. They've logged a feedback in order to improve the warning though.

**Comment by ctringham** [comment]
Thanks Yenthe - but I don't understand why this is "desired behaviour".  If you can't create an inventory adjustment in the other company, why not default to the current company?

**Comment by Yenthe666** [comment]
@ctringham it usually defaults to the company you're in, unless you have an user with a lot of rights you cannot even see the other ones actually.
