### ISSUE TITLE
Source code for odoo 9.0 release 2019-04-24 is missing.

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#39782]
Impacted versions:

Odoo 9.0 release 20190424

Steps to reproduce:

Open this link and check for 20190424
https://nightly.odoo.com/9.0/nightly/src/

Current behavior:

This file is linked as dating of 20190424 and would logically be a symlink to the latest archive. When trying to open this url it return 404 as if it was a broken symlink.
https://nightly.odoo.com/9.0/nightly/src/odoo_9.0c.latest.tar.gz

Expected behavior:

Release 20190424 should be available just like deb/rpm are.

**Comment by pedrobaeza** [comment]
That version is out of support, but I suppose the symbolic link should link to latest available version.

@d-fence would you mind checking this?

**Comment by llacroix** [comment]
@pedrobaeza While the version may be out of support, it's rather strange that the last release of 9.0 is simply gone. Even if the symlink was updated it's rather strange that something got deleted, and the most recent version. It would be the oldest archive it would be a non issue.
If something is removing archive, it could happen on other versions and not just 9.0. 

As for the 20190424, I do have a few docker images based off this version and they stopped building during the weekend. That's what raised the warning.

**Comment by d-fence** [comment]
Thanks for the good catch.
It's fixed now.
