### ISSUE TITLE
ValueError: External ID not found in the system (Not loading xml fom custom module)

### ISSUE THREAD

**Issue by yumingchangsabodota** [odoo/odoo#39789]
Impacted versions:

Steps to reproduce:

Current behavior:
I am just trying to load an empty xml for my custom module which has nothing yet. I am just trying to figure out how the routing structure works in odoo. 
However, I keep getting the error -  ValueError: External ID not found in the system: uberfoodpanda.templates
I have updated the __manifest__.py file and tried reinstall the module, but still no luck at all. I even tried to rebuild a new db but still. 

Here are my controller and manifest file

controller

```
from odoo import http

class Uberfoodpanda(http.Controller):
    @http.route('/uberfoodpanda/uberfoodpanda/', type='http',auth='public', website=True)
    def index(self, **kw):
        #return "Hello, world"
        return http.request.render('uberfoodpanda.templates', {})
```

manifest

```
{
    'name': "uberfoodpanda",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Food/Food',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base'],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
    'application': True,
}
```

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/28509278/68194023-2edcce00-ffef-11e9-9da4-6a571d88317a.png)

**Comment by Yenthe666** [comment]
@yumingchangsabodota where is your XML record with the ID `templates` in XML though?

**Comment by yumingchangsabodota** [comment]
@Yenthe666 I am fairly new to odoo, I am not sure what you are talking about. Do I need to specify a record tag in the xml file? Honestly I am not sure what to do here, and I am having hard time finding a manual that guide me through this.

**Comment by Yenthe666** [comment]
Yeah sadly the Odoo documentation is poor and bad. For every controller funtion that you have that does a `http.request.render` you will need to have an XML record with the ID that you call in this render. In your example (`http.request.render('uberfoodpanda.templates', {})`) you would need to have an XML record named `templates` in order for Odoo to render it. For example like in https://github.com/odoo/odoo/blob/9d9508bbae8933a5a50a6add2acbde336144bb87/addons/website_blog/views/website_blog_templates.xml#L521-L540

**Comment by pedrobaeza** [comment]
Closing this as answered and belongs to custom code, so this fits better on forums.
