### ISSUE TITLE
[6.1][7.0][trunk] price_surcharge must be affiliated with product uom

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#398]
https://bugs.launchpad.net/ocb-addons/+bug/1188629

The price_surcharge is not linked to product uom. It's a mistake or a design choice ?

eg: ProductA with an UOM = PCE with a price of 10.0

If in the pricelist, you defines a surcharge of 2.0

When the price is computed you will have:

    ProductA with Quantity 1.0 x PCE = 10.0 + 2.0 = 12.0
    ProductA with Quantity 1.0 x 10PCE = 100.0 + 2.0 = 102.0
    ProductA with Quantity 1.0 x 50PCE = 500.0 + 2.0 = 502.0

That's not correct, you should have:

    ProductA with Quantity 1.0 x PCE = 10.0 + 2.0 = 12.0
    ProductA with Quantity 1.0 x 10PCE = 100.0 + 20.0 = 120.0
    ProductA with Quantity 1.0 x 50PCE = 500.0 + 100.0 = 600.0

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
