### ISSUE TITLE
addons/hr_timesheet_sheet/hr_timesheet_sheet.py

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#3980]
Where in addons/hr_timesheet_sheet/hr_timesheet_sheet.py is the function that show me all the contracts in the summary of the timesheet? 
I want to change that function.
I need for each employee only the contracts that he is writed on. Not everytime all those contracts in timesheet.

**Comment by Yenthe666** [comment]
Hi @diezcode,

Sorry for the very late response. The Github bug tracker is only for bugs in the official code, not for asking questions. You can ask these type of questions on the help forums at odoo.com/help.

Regards,
Yenthe
