### ISSUE TITLE
Translate html fields

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#3983]
I many cases, for example:
- "Guidelines" in a forum
- "Note" memo
- "Invite mail"
- "Payment acquirer"
- etc.

in the fields definitions,  missing Translate = True.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for the bug report and apologies for the delay..
I've just double checked this and most of these are already fixed (I just made a PR for two more at https://github.com/odoo/odoo/pull/18324).
If you do still miss some you're always free to make a PR so we can merge it in!

Regards,
Yenthe
