### ISSUE TITLE
[11.0] Consumed quantity of material calculated incorrectly after updating quantity to produce of manufacturing order 

### ISSUE THREAD

**Issue by Azratosh** [odoo/odoo#39866]
Impacted versions: 
- 11.0

Steps to reproduce:
1. Create a new Manufacturing Order and choose any quantity to produce (e.g. 100)
2. Produce a part of the total quantity to produce (e.g. produce 50 of 100)
3. Update quantity to produce (e.g. from 100 to 200)
4. Produce another part of the total quantity to produce (e.g. produce 50 again)
5. Check consumed materials

Current behavior:
100 units of Test Product 01 were to be produced initially. Each Test Product requires two Test Material 01. 50 units were produced at first, where 100 units of the material were correctly consumed. Then, the quantity to produce was updated from 100 to 200. After that, another 50 were produced, but only 75 units of the material were used.

Expected behavior:
Consuming 100 units of material; rate of consumption remaining constant after updating quantity to produce.

Screenshots:
![grafik](https://user-images.githubusercontent.com/26200153/68296067-0529b280-0094-11ea-8885-6554b4e1ac44.png)
![grafik](https://user-images.githubusercontent.com/26200153/68298156-f265ac80-0098-11ea-9d90-c6fbd51686b7.png)

Thankfully my colleagues can easily circumvent this issue for the time being by just making a new manufacturing order if more units are required than initially planned.

Kind regards,
Max

**Comment by pedrobaeza** [comment]
@amoyaux is this part of the flexible consumption task you are developing in master or is it a separate bug?

**Comment by amoyaux** [comment]
No, seems to be the intermediate 'post inventory' that cause some trouble. I tried the usecase without post inventory and it works fine.

**Comment by pedrobaeza** [comment]
Then maybe prevent that change once posted?

**Comment by amoyaux** [comment]
No just the update quantity that ignore the qty already produced. I will provide a small fix for it.

**Comment by pedrobaeza** [comment]
Great, thanks!

**Comment by pedrobaeza** [comment]
Fixed in #39963
