### ISSUE TITLE
Invoice state set to none when return stock pickings

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#3986]
Impacted versions:  - 7.0 
Current behavior: when a stock picking with invoice state= 2binvoiced or invoiced is returned (completely or complete lines) the invoice state is changed to none. 
The situation is not coherent: if the stock picking was invoiced it becomes not invoiced, if the stock picking was prepared to be invoiced it becomes not to be invoiced.

Expected behavior: The invoice state of the original stock picking should not be modified.

Proposed change: in /addons/stock/wizard/stock_return_picking.py 
Change line 161 :   set_invoice_state_to_none = True  
                       by:   set_invoice_state_to_none = False

**Comment by Yenthe666** [comment]
Hi @jalzaga ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
