### ISSUE TITLE
psycopg2 Version 2.7.3.1 not working with odoo13 and python >= 3.7

### ISSUE THREAD

**Issue by aaly-dp** [odoo/odoo#39873]
Hello,
I noticed that the psycopg2 version 2.7.3.1 which is used in the requirements.txt file cann not be installed with pipenv right now.
I am working in odoo 13 running with python >= 3.7 and ubuntu 18.04.

psycopg2 = "==2.7.5" is working on the other hand. Please consider updating the version in the requirements.txt file.

Impacted versions:
odoo13

Steps to reproduce:
pipenv --python 3.7 install -r requirements.txt

Current behavior:
[pipenv.exceptions.InstallError]: ['Collecting psycopg2==2.7.3.1', '  Using cached https://files.pythonhosted.org/packages/6b/fb/15c687eda2f925f0ff59373063fdb408471b4284714a7761daaa65c01f15/psycopg2-2.7.3.1.tar.gz']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /home/aaly/.local/share/virtualenvs/fb-automation-DcU80gK0/bin/python -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-_wr531x5/psycopg2/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-_wr531x5/psycopg2/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-install-_wr531x5/psycopg2/pip-egg-info', '         cwd: /tmp/pip-install-_wr531x5/psycopg2/', '    Complete output (7 lines):', '    running egg_info', '    creating /tmp/pip-install-_wr531x5/psycopg2/pip-egg-info/psycopg2.egg-info', '    writing /tmp/pip-install-_wr531x5/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO', '    writing dependency_links to /tmp/pip-install-_wr531x5/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt', '    writing top-level names to /tmp/pip-install-_wr531x5/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt', "    writing manifest file '/tmp/pip-install-_wr531x5/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'", "    Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\\n'", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']

Expected behavior:
no error

**Comment by pedrobaeza** [comment]
The error doesn't seem to be about the psycopg2 version, but your deployment install method. Please follow https://www.odoo.com/documentation/13.0/setup/install.html.

**Comment by aaly-dp** [comment]
I know that the installation from the documentation is working, but this installation uses the compiled odoo13 version. Even odoo.sh is using python 3.6 for odoo13 as far as I know. The problem is when using the source code from the repository and installing the python packages while using python3.7

The requirements.txt file has different versions for some packages when using python >= 3.7 
It is just a suggestion to do this also for psycopg2

**Comment by pedrobaeza** [comment]
But the question here is not about Python, but about the availability of some libraries (`postgresql-server-dev-...`) for installing psycopg2 via pip.

**Comment by aaly-dp** [comment]
O yeah, installing the postgresql-server-dev-10 package solved the problem with psycopg2 Version 2.7.3.1

Previously I was installed psycopg2 = "==2.7.5" so I didn't need the postgresql-server-dev-10 package.

I guess this issue is solved

Thanks
