### ISSUE TITLE
[8.0] new API raise faulty warning

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#3988]
Imagine I have a model `res.partner.bank` defined in v7 API.

In my module I inherit `res.partner.bank` to add a fields and a constrains.
If I have following code:  
   
    @constrains('new_field_added_in_v8', 'old_field_existing_in_v7')
    def my_const_meth(self):
         pass

I will have a warning when installing updating module:
    
    @constrains('new_field_added_in_v8', 'old_field_existing_in_v7') parameters must be field names
    
Even if the parameters are correct fields and code seems to behave as expected. 
It looks like that the field declared in version 7 is not taken as a valid parameter.

Regards

Nicolas

**Comment by rco-odoo** [comment]
Looks like an old bug.
I cannot reproduce it today.
