### ISSUE TITLE
planned_hours, total_hours, effective_hours are wrongly calculated in parent project

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#399]
https://bugs.launchpad.net/ocb-addons/+bug/1189480

planned_hours, total_hours, effective_hours are wrongly calculated in parent project when you edit a task.
The parent value is sum twice once (each child sum individually + once again the sql aggregated sum)

**Comment by Yenthe666** [comment]
Dear @gurneyalex ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
P.S: It doesn't seem to be around anymore either.

Regards,
Yenthe
