### ISSUE TITLE
[11.0] Stock: inventory adjustments

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#39902]
Impacted versions:
11.0

Steps to reproduce:
Create Inventory adjustment
  Inventory of One product only
  select any product
Start inventory
Then add new inventory line
Try to save Inventory

Current behavior:
Error Product is not set in inventory line

**Comment by pedrobaeza** [comment]
What is the use case for that? I would say that if you want that, you have to select "Add lines manually" option

**Comment by kos94ok-3D** [comment]
I have product which tracked by serial number.
In odoo I have n qty this product but real n+1 so I need to add one extra line.

**Comment by pedrobaeza** [comment]
OK, I can confirm the problem:

![Peek 07-11-2019 10-08](https://user-images.githubusercontent.com/7165771/68375212-bab53e00-0146-11ea-9c2e-adab971de818.gif)

Meanwhile the solution is to use the mentioned option of selecting products manually.

@amoyaux I think this can be solved with `force_save="1"` on `product_id` field in view.

**Comment by pedrobaeza** [comment]
Fixed in #39935
