### ISSUE TITLE
Wrong account types

### ISSUE THREAD

**Issue by Maurice67205** [odoo/odoo#39938]
Impacted versions:
Module : l10n_fr
Branch : 12.0
Repository : enterprise
When generating the aged receivable report , all account with receivable types are handled
Some account like 471, 4387,4687 should not appear in such a report, so their account type should not be receivable or we should be able to exclude them from the aged receivable report

regards
Maurice

**Comment by pedrobaeza** [comment]
@jco-odoo something for you

@Maurice67205 this kind of hard changes in CoAs must be supported by any documentation that states about that accounts not being AR.

**Comment by Maurice67205** [comment]
@jco-odoo can we discuss this "offline" so that you can explain to me how I should proceed to have those changes ?
regards
Maurice

**Comment by pedrobaeza** [comment]
I don't think that should happen oflline. Why?

**Comment by jco-odoo** [comment]
@Maurice67205  We also think it needs to be changed.  The question is a bit to what other type?  In Belgium, the "compte d'attente" is done with the current liabilities.  @avw-odoo

**Comment by jco-odoo** [comment]
@Maurice67205 I think you are right here and that we should change it.  I don't know if you know about any other changes to do?  @william-andre

**Comment by jco-odoo** [comment]
@Maurice67205 We are doing a complete overhaul of the CoA in https://github.com/odoo/odoo/pull/48723

**Comment by william-andre** [comment]
Closing wince linked PRs are closed
