### ISSUE TITLE
Export audit file - General Ledger gives an error - Skip RS (Serbia) country code

### ISSUE THREAD

**Issue by bizzappdevteam** [odoo/odoo#39934]
Impacted versions:
Module : l10n_nl_reports
Branch : 12.0
Repository : enterprise

Steps to reproduce:
- When we go to accounting - reporting - general ledger and click on the button "Export (XAF)" and if we skip the RS (Serbia) country code, we got the following error

{"code": 200, "message": "Odoo Server Error", "data": {"name": "odoo.exceptions.UserError", "debug": "Traceback (most recent call last):
 File \"/home/bizzappdev/v12/odoo/odoo/tools/xml_utils.py\", line 16, in _check_with_xsd
 xsd_schema.assertValid(tree_or_str)
 File \"src/lxml/etree.pyx\", line 3537, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '13'; this exceeds the allowed maximum length of '10'., line 16558

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File \"/home/bizzappdev/v12/enterprise/account_reports/controllers/main.py\", line 51, in get_report
 content = report_obj.get_xaf(options)
 File \"/home/bizzappdev/v12/enterprise/l10n_nl_reports/models/account_general_ledger.py\", line 140, in get_xaf
 _check_with_xsd(audit_content, xsd)
 File \"/home/bizzappdev/v12/odoo/odoo/tools/xml_utils.py\", line 20, in _check_with_xsd
 raise UserError('\
'.join(str(e) for e in xml_errors.error_log))
odoo.exceptions.UserError: (\"<string>:16558:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '13'; this exceeds the allowed maximum length of '10'.\
<string>:16558:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'PA 19406-0317' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:30733:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '14'; this exceeds the allowed maximum length of '10'.\
<string>:30733:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'not applicable' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:38109:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}telephone': [facet 'maxLength'] The value has a length of '33'; this exceeds the allowed maximum length of '30'.\
<string>:38109:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}telephone': '00390498863823 // 0039 0498862882' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String30'.\
<string>:51019:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '11'; this exceeds the allowed maximum length of '10'.\
<string>:51019:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'GR - 265 00' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:51046:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '11'; this exceeds the allowed maximum length of '10'.\
<string>:51046:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'GR - 265 00' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:51073:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '11'; this exceeds the allowed maximum length of '10'.\
<string>:51073:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'GR - 265 00' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:51100:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '11'; this exceeds the allowed maximum length of '10'.\
<string>:51100:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': 'GR - 265 00' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\
<string>:52642:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': [facet 'maxLength'] The value has a length of '12'; this exceeds the allowed maximum length of '10'.\
<string>:52642:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}postalCode': '90505 - 5245' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}String10'.\

**Comment by Yenthe666** [comment]
@bizzappdevteam guys, Erwin/ Odoo Experts has a partnership license and so does the customer so report it through odoo.com/help as @pedrobaeza mentioned in the other ticket ;)
