### ISSUE TITLE
Company name with a dot and email gateways 

### ISSUE THREAD

**Issue by mantissefr** [odoo/odoo#3995]
Hello,

I have a company name with a dot in it.

The company name on Odoo website strips that dot but email gateways keep the dot in it so, for example, creating a lead with an email does not work.

Thanks for explaining me if it is really a bug or if I can change the gateway domain on Odoo Saas offer.

Cheers,

Mantisse_fr

**Comment by Yenthe666** [comment]
Hi @mantissefr ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
