### ISSUE TITLE
[8.0]TypeError: Cannot read property 'arch' of undefined #3769, view_form.js Line 547

### ISSUE THREAD

**Issue by jose-eezee** [odoo/odoo#3997]
Hello everybody,

When I make click on button Portal access management in customers the Odoo shows the next error:

![image](https://cloud.githubusercontent.com/assets/8819836/5263943/cf10bba6-7a08-11e4-94fa-621e216e424f.png)

I see the javascript console and shows the line 547. I know about a similar issue in the past days but, I have running the last version of Odoo, thanks in advanced.

**Comment by flotho** [comment]
Hy @jose-eezee 
Did you solve your issue?
I have the same problem here #4912

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
