### ISSUE TITLE
can't Register payments in account_invoice!

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#3998]
I couldn't register payement in account_invoice 
and the residual is always equal 0 
you can verify with this server: https://test-qs.odoo.com/
user:contact@qamarsoft.com
pass:demo

**Comment by Yenthe666** [comment]
Hi @m3asmi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
