### ISSUE TITLE
Lot Number is not updating in Quality check: Odoo V13

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#39999]
Impacted versions: 13.0

Steps to reproduce: Create a product with Lot tracking.
create a Quality Check for This product.

Now create a Purchase order and confirm it.
While receiving  it will ask you for lot number and to do quality check.
Validate the receiving document.
It should update lot number in QC record. but it is not updating lot even if qc has Lot Id field.

Current behavior:
It is not updating lot number in QC record even if receiving document has lot number. 

Expected behavior:
It should update the lot number in QC record as receiving document has lot number. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As this belongs to an enterprise module, please put a ticket in odoo.com/help instead.

**Comment by sle-odoo** [comment]
Hello,
Closing as per pedro's comment, and i'm pretty sure the lot_id is only used in mrp_workorder and not in quality_control.

Regards
