### ISSUE TITLE
Error with adding new menu item on website

### ISSUE THREAD

**Issue by johny1500** [odoo/odoo#40002]
Impacted versions: 13.0

Steps to reproduce: 
- run fresh database
- install website module
- try to modify website menu by adding new menu item

Current behavior:
Error:
TypeError: data is undefined

http://92.222.86.109:8069/web/content/545-f4d0650/1/website.assets_editor.js:15
Traceback:
init@http://92.222.86.109:8069/web/content/545-f4d0650/1/website.assets_editor.js:15:885
OdooClass.extend/</prototype[name]</<@http://92.222.86.109:8069/web/content/543-9883e80/1/web.assets_common_lazy.js:3761:488
Class@http://92.222.86.109:8069/web/content/543-9883e80/1/web.assets_common_lazy.js:3762:65
_onAddMenuButtonClick@http://92.222.86.109:8069/web/content/545-f4d0650/1/website.assets_editor.js:17:3023
proxy/<@http://92.222.86.109:8069/web/content/543-9883e80/1/web.assets_common_lazy.js:3845:11
dispatch@http://92.222.86.109:8069/web/content/543-9883e80/1/web.assets_common_lazy.js:925:447
add/elemData.handle@http://92.222.86.109:8069/web/content/543-9883e80/1/web.assets_common_lazy.js:911:166

Expected behavior:
New menu item added
Video/Screenshot link (optional):
![obraz](https://user-images.githubusercontent.com/57521808/68462468-e3a00680-020c-11ea-9c85-aa5d6fab2b93.png)
![obraz](https://user-images.githubusercontent.com/57521808/68462507-fc102100-020c-11ea-8bf9-9e3a952b03e2.png)

**Comment by pedrobaeza** [comment]
I confirm the problem in runbot.

@JKE-be can you please take a look?

**Comment by Yenthe666** [comment]
I've reported it through odoo.com under the OPW `2122918` as my customer is impacted too.

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/ab7f501ff401cc1a85a95dd3cc65d80ecfeec2cc
