### ISSUE TITLE
Odoo not communicate with different postgres port

### ISSUE THREAD

**Issue by kathpalrk** [odoo/odoo#40007]
Impacted versions: Have tried with 11 ,12 & latest one

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by kathpalrk** [comment]
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? - - -
^C2019-11-08 05:47:49,305 439 INFO ? odoo.service.server: Initi

I am using the diff postgresql port which I've already definded under odoo.conf file, but its still not able to communicate.

I've tried to connect the Postgresql from CLI which is working but its not allowing me to connect the same from odoo web level. Is there any other configuration where we have to mentioned the postgres port and host information apart from conf file.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
