### ISSUE TITLE
Unable to create model in batch using type()

### ISSUE THREAD

**Issue by songkang1993** [odoo/odoo#40010]
Impacted versions:12.0

Steps to reproduce:
1. I need to create some similar classes.
2. so I use type() to do it.
![image](https://user-images.githubusercontent.com/38366752/68467445-271c6400-0251-11ea-80e4-20b249db64a7.png)
3. It does not automatically create tables;
4. Modify code
![image](https://user-images.githubusercontent.com/38366752/68467418-179d1b00-0251-11ea-9d7a-6d0b95a89508.png)
5. It will automatically create tables;
Current behavior:
It does not automatically create tables when I use type()
Expected behavior:
It automatically creates a table；

Video/Screenshot link (optional):

**Comment by songkang1993** [comment]
> Impacted versions:12.0
> 
> Steps to reproduce:
> 
> 1. I need to create some similar classes.
> 2. so I use type() to do it.
>    ![image](https://user-images.githubusercontent.com/38366752/68467445-271c6400-0251-11ea-80e4-20b249db64a7.png)
> 3. It does not automatically create tables;
> 4. Modify code
>    ![image](https://user-images.githubusercontent.com/38366752/68467418-179d1b00-0251-11ea-9d7a-6d0b95a89508.png)
> 5. It will automatically create tables;
>    Current behavior:
>    It does not automatically create tables when I use type()
>    Expected behavior:
>    It automatically creates a table；
> 
> Video/Screenshot link (optional):

from odoo import models, fields

for i in range(10):
    num = str(i)
    attrs = {
        "_name": "some_module.table_name_%s" % num,
        "_description": "create multiple tables: no %s" % num,
        "_rec_name": "one_filed",
        "one_filed": fields.Float("one filed", digits=(9, 2)),
        "__module__": __name__
    }
    type("ClassName%s" % num, (models.Model,), attrs)

**Comment by pedrobaeza** [comment]
Sorry, this is a misuse of the ORM framework and can't work that way. You have to create classes the traditional way for being recognized as proper ORM models.
