### ISSUE TITLE
[v8] Validate Order with Wire transfer takes more than1 minute  to confirm for the end user 

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#4001]
Impacted versions:
 - 8.0 and later

Steps to reproduce:
 1. add product to cart 
 2. Process checkout
 3. Complete Billing information. 
 4. Select payment method ( wire transfer must be available) 
 5. Click Pay and wait for confirmation
 6. Order SO021 Confirmed
Thank you for your order.
Your transaction is waiting confirmation

Current behavior:
Wait time for confirmation is more than 1 min.

Expected behavior:
Wait time for confirmation 5 to 10 seconds max.

**Comment by SBollatti** [comment]
+1 Same issue
