### ISSUE TITLE
Manufacturing Order Produce Wizard Pop-up Fire the JS Error

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#4003]
In <b>manufacturing</b> &raquo; manufacturing order form &raquo; produce wizard,  even if change previoused consumed qty, raise the js error for <code>Uncaught TypeError: Cannot read property 'set' of undefined</code>.

View this video: http://youtu.be/dZSJwlpdl-c
<b>Produced version</b> : v8

**Comment by Yenthe666** [comment]
Hi @imjaypatel ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
