### ISSUE TITLE
[8.0][Old API] Can`t set the fields parameter to False by _inherit.

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#4004]
**Can`t set the fields parameter to False by _inherit**

Impacted versions:
- 8.0

Steps to reproduce:

 1.create a new module with this code:

```
class product_constaints(osv.osv):
    _inherit = 'product.uom'

    _columns = {
        'name': fields.char('Name', required=False),
        }
```

2.install the module.

Current behavior:
- The fields `name` of `product.uom`  required.

Expected behavior:
- The fields `name` of `product.uom`  not required.

More:

But it works if I use the new API like this :

```
name = fields.Char(required=False)

```

**Comment by Yenthe666** [comment]
Hi @joshuajan ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As this is about the old API, which is dropped in the newer versions, this won't be a problem in the future anymore.

Regards,
Yenthe
