### ISSUE TITLE
[13.0] account: search panel for chart of account digit [Wishlist]

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#40058]
Hello
I wish to make computation of display chart of account based on number of digits configure in chart of account template not fixed to be first 2 number only.

**Comment by pedrobaeza** [comment]
Please specify steps to reproduce what you want. Any way, as this is not an issue, but something you want, there are little chances to get this, but we can try.

**Comment by Yenthe666** [comment]
Please add more info about the wishlist item so we can see if it is a valuable feedback or not :)

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on our last responses.
