### ISSUE TITLE
Cannot close session in Bar POS - Odoo 13

### ISSUE THREAD

**Issue by ivaqmo123** [odoo/odoo#40053]
Impacted versions: Odoo 13 (runbot env)

Steps to reproduce: 
1.- Login as admin, go to POS, enter to "Bar" , click on 1st table.
2.- Add lines to order and then delete all of them.
3. Go back to table mgmt and try to close session and below error appears.
"Something went wrong !      There are still orders in draft state in the session. Pay or cancel the following orders to validate the session: /"

Current behavior: cannot close a session with empty order (which previously had a draft order)

Expected behavior: should be able to close the session with balance 0.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @ivaqmo123,

Thanks for the report. I've just tested this but it seems to work fine. Could you make a video please? I assume I'm missing a step.
CC @switch87 

Regards,
Yenthe

**Comment by ivaqmo123** [comment]
Hi @Yenthe666 ,
 Just entered again to the runbot as admin, and tried to close the BAR POS session and I still can't. One thing I forgot to mention is that the issue happens when clicking on "Validate Closing & Post Entries" button to totally close the session. Please let me know if this clarification help.

**Comment by switch87** [comment]
@ivaqmo123 I've taken a look into the run it session you started. To be able to close the session, click orders in the upper right corner. It indicates there is one order, and this order is in the new/draft state. If you or validate or remove this order the session can be closed.

**Comment by ivaqmo123** [comment]
@switch87 , got it. But is it not supposed to be able to close that draft order from table management & POS view? .... If i click on the table that has that draft order, there is nothing there, I even click on the "-" tab in order to delete any draft order but the "1" number in black circle still appears in table mgmt view as you can see in this attachment:
[Issue.docx](https://github.com/odoo/odoo/files/3826112/Issue.docx)

**Comment by switch87** [comment]
@ivaqmo123 it should indeed work that way. I think I know what's going wrong, I will investigate on the problem next week. I'm reopening the issue.

**Comment by switch87** [comment]
@ivaqmo123, The fix is merged into the latest v13. https://github.com/odoo/odoo/pull/40103

**Comment by B4y4ng4n** [comment]
I think something is missing on merged or it is being removed again? I use Odoo 13.0-20200626 (Community Edition) and the same thing happend. Saying cannot close POS because draft order still open.
```
There are still orders in draft state in the session. Pay or cancel the following orders to validate the session:
/, /
```
But the session already closed, Now trying to Validate and Post. How to fix this @switch87 ?
I have multiple floor layout with several tables. All in the POS already paid normally and all has been accounted. Yet the error showed up.
