### ISSUE TITLE
Change in a translated term is not reflected - Odoo 13 POS Restaurant

### ISSUE THREAD

**Issue by ivaqmo123** [odoo/odoo#40068]
Impacted versions: Odoo 13 (runbot)

Steps to reproduce: 
1.- Load Spanish-PE translation and activate it.
2.- In Settings>Translation>Translated Terms. Filter "Translated Field = addons/pos_restaurant/static/src/xml/multiprint.xml"
3.- Select the record whose internal source is "Order" and change their translated value from "Pedido" to "Orden"
4.- Change admin user language to Spanish-PE.
5.- Go to POS> Bar > and place an order, you will see in the receipt that the "translated value" of POS reference is still "Pedido" and not "Orden".

Current behavior: Change in translated term is not reflected in Odoo POS Restaurant. I even restarted odoo services but the translation still not working.

Expected behavior: Change in translated term should be reflected in Odoo POS Restaurant

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's probably because you haven't reloaded PoS tab.

**Comment by ivaqmo123** [comment]
@pedrobaeza , i reloaded the tab, open a new browser but it didnt work.
I also tried in my instance by restarting odoo service, rebooting machine...but none of them work.

**Comment by pedrobaeza** [comment]
But I'm not sure this is the place where you need to touch for getting what you want. Modify the .po, start from a fresh database, and then try again.

**Comment by ivaqmo123** [comment]
Hi @pedrobaeza , I modified the es_PE.po file corresponding to pos_restaurant addon located in /usr/lib/python3/dist-packages/odoo/addons/pos_restaurant/i18n/, however it doesn't work (the translated text is not reflected) even when restarting odoo service.

**Comment by Yenthe666** [comment]
I don't see any step that says your updating the terms though?

**Comment by Yenthe666** [comment]
Closing as there has been no feedback on our last responses.

**Comment by ZERO20** [comment]
i have the same problem :(
