### ISSUE TITLE
Error in Google analytics tracking code

### ISSUE THREAD

**Issue by mamaf** [odoo/odoo#4006]
In the last version of Odoo (8.0), the javascript code generated by Odoo for Google Analytics doesn't work any more (no stats are returned by Google Analytics)

After investigating, I found the error (in website_templates.xml) :
Instead of :
 ga('create', '<analytics-id>', 'auto');
the new version of Odoo generates :
ga('create', _.str.trim('<analytics-id>'), 'auto');

which causes an error in Google analytics stat generation

**Comment by syci** [comment]
I confirm that also happens to me , why it takes so long unsolved being so little?

**Comment by JKE-be** [comment]
Thanks for the reporting

It should be fixed meanwhile...
