### ISSUE TITLE
to fix: odoo13 debug in pycharm error. "Process finished with exit code -1073740940 (0xC0000374)"

### ISSUE THREAD

**Issue by guohuadeng** [odoo/odoo#40061]
Impacted versions:
odoo13, odoo12

Steps to reproduce:
use pycharm as ide.  python 3.6~3.8 as interpreter
when debug odoo. show

pydev debugger: process 306632 is connecting

Connected to pydev debugger (build 191.8026.44)

Process finished with exit code -1073740940 (0xC0000374)

Current behavior: Fixed
change code /odoo/tools/translate.py L1141, add `ln = ln[0:ln.index('.')]`
```
def resetlocale():
    # locale.resetlocale is bugged with some locales.
    for ln in get_locales():
        try:
            ln = ln[0:ln.index('.')]
            return locale.setlocale(locale.LC_ALL, ln)
        except locale.Error:
            continue
```

Expected behavior:
merge to master

Video/Screenshot link (optional):

**Comment by guohuadeng** [comment]
also in /odoo/addons/base/models/res_lang.py #105

**Comment by pedrobaeza** [comment]
Unless you explain more the problem, this can't be considered as an Odoo bug. From what I understand, setting the lang in your OS is basic for proper operation. If PyCharm doesn't support that, then it's a problem of PyCharm.

**Comment by guohuadeng** [comment]
thanks for quick reply.

This is not odoo bug.  it is a python issue. please check
https://bugs.python.org/issue36792#msg342966

everyone use windows to develop odoo13 would sure to meet this issue.
also this cost me lots of time to find out the fix way.

If we can fix this, it would help lots of people in odoo windows develop.

Many thanks.

**Comment by Yenthe666** [comment]
Hmm doesn't feel like an issue for Odoo itself to me honestly. Plus you're way better of developing on Linux too by the way ;)
@mart-e I summon you, the powerful language manager.

**Comment by pedrobaeza** [comment]
You can do as well a pull request with the possible solution.

**Comment by mart-e** [comment]
Do you have a traceback ?
cc @VincentSchippefilt who is the only brave one that develops on Windows at Odoo AFAIK. Do you know this kind of issue ?

**Comment by Yenthe666** [comment]
@VincentSchippefilt @guohuadeng any update from both of you?

**Comment by guohuadeng** [comment]
I  do report the issue.

if u try debug in window.
u destiny meet the problem.

**Comment by kami23** [comment]
Hello, I am facing the same problem, did anyone find out a fix for this?

**Comment by guohuadeng** [comment]
get fixed file here.

https://github.com/guohuadeng/odoo13-x64/tree/master/fixed/odoo
