### ISSUE TITLE
CONTACTS classification

### ISSUE THREAD

**Issue by americanoilfield** [odoo/odoo#40064]
Impacted versions: 13

Steps to reproduce: Open contact app, create a contact, and try to set as a VENDOR or as a CUSTOMER. that basic option is not show

Current behavior:

Expected behavior:
is a vendor =true/false
is a customer =true /false

Video/Screenshot link (optional):

**Comment by danielhasan1** [comment]
I think in odoo that option is abstract and given.
for a vendor or customer, that option is individual,
and the other is a company. You can select a tag as a vendor or service if you want to distinguish between these.

**Comment by pedrobaeza** [comment]
In this version there's no more isolation by that checks. See https://github.com/odoo/odoo/issues/39376#issuecomment-546326409 for some details.

Closing as no issue, but design decision.
