### ISSUE TITLE
[11.0-13.0] No RPM repodata directory in 11.0-13.0 nightly repositories

### ISSUE THREAD

**Issue by anassahmed** [odoo/odoo#40072]
Impacted versions:
- 11.0
- 12.0
- 13.0

Steps to reproduce:
- Add the odoo-nightly repo to a CentOS 8 server
- Run `dnf install odoo`.

Current behavior:
- Fails, with the output:
```bash
Cannot download 'http://nightly.odoo.com/11.0/nightly/rpm/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
Error: Failed to synchronize cache for repo 'odoo-nightly'
```

Expected behavior:
- Installs the proper version.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's because there's no packaging for that distribution.

@d-fence any plans for including that distribution. Maybe a wishlist, or should we directly close it as won't fix?

**Comment by anassahmed** [comment]
@pedrobaeza What about Fedora 26+? No RPM repodata means no packages for any redhat based distro. 

I may also help in packaging for CentOS 8 if you need help.

**Comment by d-fence** [comment]
@anassahmed I'm investigating, the gen_rpm_repo [is called](https://github.com/odoo/odoo/blob/3e9b2acc60a37f92c3e0ffb9fa6375e7854338ef/setup/package.py#L528-L529) and I verified that we use --sign arg when we generate the package.

@pedrobaeza that should work with CentOS, I 'll fix it

**Comment by anassahmed** [comment]
@d-fence I hope this gets fixed soon. We've to deploy to a client abroad, and I'm going to travel to them in 2 weeks.

About CentOS, does this mean you will support CentOS 8?!

**Comment by anassahmed** [comment]
@d-fence Worth following [this](https://pagure.io/epel/issue/94) and [this](https://fedoraproject.org/wiki/Changes/EnablingPythonGeneratorsByDefault) about packaging RPM with python dependencies for F31+ and maybe CentOS/RHEL 7.7+ and 8.0+.

**Comment by anassahmed** [comment]
BTW, [repodata](https://nightly.odoo.com/11.0/nightly/rpm/repodata/) is back again! :clap:

**Comment by d-fence** [comment]
@anassahmed I know, I fixed our repo :cowboy_hat_face: 
Thanks for the links.

**Comment by anassahmed** [comment]
@d-fence Thanks. I would like to help in packaging Odoo 11.0-13.0 for both CentOS 7.7+ and CentOS 8.0. I'm looking up EPEL packages to satisfy the `python3-*` packages that Odoo depends on. I hope we get them on par soon to what F30+ have as I can't rely on Fedora in production (we need RH support in some high-scale deployments ... etc).

**Comment by d-fence** [comment]
@anassahmed I verified this morning and it does not work with CentOS 8, even with the epel-release installed. Sorry.

**Comment by d-fence** [comment]
Fixed

**Comment by anassahmed** [comment]
@d-fence I know it doesn't. I'm communicating with EPEL maintainers to help package necessary dependencies `python3-*` for Odoo to be installed on CentOS8/7.

**Comment by d-fence** [comment]
@anassahmed thanks a lot.
