### ISSUE TITLE
Wrong assert message about required python version

### ISSUE THREAD

**Issue by FUNNYDMAN** [odoo/odoo#40070]
Impacted versions: odoo 13

Steps to reproduce:
1) Try to use python 3.6

Current behavior:
`assert sys.version_info > (3, 6), "Outdated python version detected, Odoo requires Python >= 3.6 to run."`
Expected behavior:
`assert sys.version_info >= (3, 6), "Outdated python version detected, Odoo requires Python >= 3.6 to run."`

**Comment by pedrobaeza** [comment]
Where is that located? You can do a pull request changing that comparison, that seems to be indeed incorrect.

**Comment by FUNNYDMAN** [comment]
@pedrobaeza https://github.com/odoo/odoo/blob/13.0/odoo/__init__.py#L19

**Comment by pedrobaeza** [comment]
Thanks for the pointer. I think the best thing to do is to create a pull request fixing that.

**Comment by sswapnesh** [comment]
![Screenshot from 2019-11-10 22-21-12](https://user-images.githubusercontent.com/16624719/68547530-883a6800-0408-11ea-8403-532df60f9f4c.png)

It seems to be working well.

**Comment by pedrobaeza** [comment]
Thanks for that, @sswapnesh! Yeah, it's then OK, as nobody is going to use 3.6.0 (and maybe it's incompatible at all).

Closing as seems to be not a valid issue.

**Comment by sswapnesh** [comment]
Still better to Improve this
```diff
- >= 
+ >
```
