### ISSUE TITLE
Statusbar widget not loading properly

### ISSUE THREAD

**Issue by nurlanf** [odoo/odoo#40089]
Impacted versions:
v11, v12

Steps to reproduce:
1. Add selection field in python module:
```
    state = fields.Selection([('draft', 'Draft'),
                            ('deployed', 'Deployed'),
                            ('destroyed', 'Destroyed')], 
                            string="Status", default='draft')
```
2. Add state field inside header of form view
```
       ............
        <form>
              <header>
                  <button name="deploy_app" string="Deploy" type="object" class="oe_highlight" attrs="{'invisible': [('state', '!=', 'draft')]}"/>
                  <button name="destroy_app" string="Destroy" type="object" class="oe_highlight" attrs="{'invisible': [('state', '!=', 'deployed')]}"/>
                  <field name="state" widget="statusbar" clickable="False"/>
              </header>
              ........
```

Current behavior:
It doesn't load like statusbar widget, but it shows up as drop/down selection field in normal form fiew but in header. 

![image](https://user-images.githubusercontent.com/18286626/68594879-c41d0e00-0498-11ea-83bb-5b9b061bdbf8.png)

Expected behavior:

It suppose to load properly like statusbar

Video/Screenshot link (optional):

**Comment by Boudmir-Ibra** [comment]
<field name="state" widget="statusbar" options="{'clickable': '0'}"/>

**Comment by Boudmir-Ibra** [comment]
Actually, this is how you do it: 
<field name="state" widget="statusbar" options="{'clickable': '1'}"/>

**Comment by Boudmir-Ibra** [comment]
Actually, this is how you do it:
field name="state" widget="statusbar" options="{'clickable': '1'}"

**Comment by Yenthe666** [comment]
Yeah, misuse of the code.
