### ISSUE TITLE
Wrong datejs locale name halts page load

### ISSUE THREAD

**Issue by koljenovic** [odoo/odoo#4008]
This issue is related to changes made as a result of issue #3480 solved by 65d92dadf47a833dca731f7d0cf5b0690a503777, the same incorrect locale occurs in `addons/web/static/lib/datejs/globalization`. File `bs-BS.js` is incorrect and results in error 404 which halts the page loading in the browser, the proposed solution is renaming `bs-BS.js` to `bs-BA.js`.

![image](https://cloud.githubusercontent.com/assets/236839/5278447/d7d0fd88-7ad9-11e4-9446-8cbe86c66c0d.png)

**Comment by Yenthe666** [comment]
Hi @koljenovic,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
