### ISSUE TITLE
Deletin Menu Problems

### ISSUE THREAD

**Issue by FreneticTutorials** [odoo/odoo#40087]
Impacted versions: v12.0

Current behavior: deletes all menus that has same urls

Expected behavior: delete one menu without deleting other menus with same url

Hi
This problem Occurred recently when i try to delete a menu it deletes all the menus with same url

i will be happy if this gets solved soon.

**Comment by pedrobaeza** [comment]
Which menus are you talking about? Please specify detailed steps to reproduce the problem.

**Comment by FreneticTutorials** [comment]
> Which menus are you talking about? Please specify detailed steps to reproduce the problem.

i mean the front end website menus

**Comment by pedrobaeza** [comment]
Please specify detailed steps to reproduce the problem.

**Comment by FreneticTutorials** [comment]
> Please specify detailed steps to reproduce the problem.



![Inkedscreenshot-localhost_8069-2019 11_LI](https://user-images.githubusercontent.com/55325445/68587010-3ee72880-049b-11ea-994a-37a78aa0a38b.jpg)
this is the problem i want to delete one but it deletes all of the menus with same link address

**Comment by pedrobaeza** [comment]
Why aren't you using menu edition from the website, not from backend?

**Comment by FreneticTutorials** [comment]
i can use it but is there a problem with this side?

**Comment by FreneticTutorials** [comment]
it is important for us to manage menus from here for some reasons

**Comment by pedrobaeza** [comment]
You will have that effect doing from backend.

Closing as expected behavior.
