### ISSUE TITLE
No partner /vendor name in pdf reports

### ISSUE THREAD

**Issue by sspankaj** [odoo/odoo#40081]
Impacted versions:
13.0
Steps to reproduce:
1.install fresh odoo13
2.install purchase module
3.set company address street ,state

Current behavior:
no partner/vendor name print in po/invoice/quotation 
Expected behavior:
should be print in all reports
Video/Screenshot link (optional):
![no_partner_name_print](https://user-images.githubusercontent.com/29782180/68563427-88238200-0473-11ea-8362-7a293c030f50.png)

**Comment by pedrobaeza** [comment]
That's because your header is taller than the default space in paper format configuration, because you have added all the address lines. Modify that configuration for being visible.

Closing as no issue, but a change of configuration.
