### ISSUE TITLE
Update the source code issue after customization

### ISSUE THREAD

**Issue by alan6666-erp** [odoo/odoo#40082]
Impacted versions:
odoo 12.0

Suppose today I am developing with the odoo version of 20190101 source code and customizing expense and account, but I want to update source code to 20191111 today. 
When I update source code, 
do you need to update all addons?
Or 
do you just need to update sourcecode? 
Thanks.

If I make a big change to expense and account, will it cause the update to fail ?
Thanks.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
