### ISSUE TITLE
Punto de venta - Crear Clientes

### ISSUE THREAD

**Issue by jaimeandres79** [odoo/odoo#40090]
Actualmente Tengo odoo 12 . y habilite la configuracion para manejar multicompañias 

En una de las compañias tengo habilitado el modulo de punto de venta y ya hice las configuraciones básicas para este modulo. con lo que no he podido es con la creación de los clientes desde el modulo de punto de venta ya que al momento de crearlo me lo permite ; pero la ahora de facturar me sale un error donde me dice que para este cliente no se ha defino una cuenta por cobrar.
 
<img width="960" alt="error2" src="https://user-images.githubusercontent.com/7283743/68623929-9d180980-04a3-11ea-8f5b-854079306977.png">

Lo que me toca es ir al modulo de punto de ventas y crear el cliente y asignarle manualmente la cuenta por cobrar y la de pagar.

Como puedo evitar hacer esto sin necesidad de estar saliendome de la caja de ventas. y realizar el procesos manual.

Agradezco su  apoyo. 
<img width="960" alt="error" src="https://user-images.githubusercontent.com/7283743/68623964-b620ba80-04a3-11ea-89ca-0f316e4c6a93.png">

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by JPML94** [comment]
Puedes ir a las configuraciones de contabilidad y seleccionar un paquete de localizacion o definir la cuenta que quieres como un valor por defecto de usuario.
