### ISSUE TITLE
[IMP] mail - mail_message

### ISSUE THREAD

**Issue by JKE-be** [odoo/odoo#40095]
https://github.com/odoo/odoo/blob/aa0554d224337e1d966479a351a3ed059d297765/addons/mail/models/mail_message.py#L1003

Try to -i 2x a module that depend of mail, you will have 

>   File "/home/odoo/src/odoo/odoo/odoo/tools/convert.py", line 578, in _tag_record
>     record = model._load_records([data], self.mode == 'update')
>   File "/home/odoo/src/odoo/odoo/odoo/models.py", line 3976, in _load_records
>     data['record']._load_records_write(data['values'])
>   File "/home/odoo/src/odoo/odoo/odoo/models.py", line 3914, in _load_records_write
>     self.write(values)
>   File "/home/odoo/src/odoo/odoo/addons/mail/models/mail_message.py", line 1096, in write
>     self._invalidate_documents()
>   File "/home/odoo/src/odoo/odoo/addons/mail/models/mail_message.py", line 1004, in _invalidate_documents
>     if issubclass(self.pool[model], self.pool['mail.thread']):
>   File "/home/odoo/src/odoo/odoo/odoo/modules/registry.py", line 176, in __getitem__
>     return self.models[model_name]
> odoo.tools.convert.ParseError: "False" while parsing /home/odoo/src/odoo/odoo/addons/mail/data/mail_demo.xml:2, near

The first time, you don't try to invalide so it works, the second time you have no record linked to your mail.message, so env[False] will crash

Cannot reproduce in real usecase (not try), but maybe no cost to add a check "if model " to avoid the warning.

**Comment by seb-odoo** [comment]
I can't reproduce the issue on the latest master.

Do you have a specific version and scenario that I can use to reproduce it?

I tried 2x -i on mail itself, portal, website, website_sale and didn't have the issue with any of them.

**Comment by JKE-be** [comment]
ok, we close... I will reopen if reprodctible
