### ISSUE TITLE
'prepaid' order policy is missing in the configuration of default order policy

### ISSUE THREAD

**Issue by tmotyl** [odoo/odoo#4013]
sale.order "order_policy" field can take 3 values (manual, picking, prepaid)
see https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock.py#L88
However in the configuration (Settings->Sales->Invoicing process->"The default invoicing method is ") there are only 2 options available:
https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/res_config.py#L40

Is there a reason for that? Can we add 'prepaid' option to the default configuration options?

**Comment by Yenthe666** [comment]
Hi @tmotyl ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
