### ISSUE TITLE
Discussion group names are not translated in the menu 

### ISSUE THREAD

**Issue by clonedagain** [odoo/odoo#4014]
In v7 and v8, the menu entries for the discussion groups in "Messaging/My groups" are not translated.
Example in French on runbot:
![untranslated chat groups](https://cloud.githubusercontent.com/assets/391953/5280841/edc6d33e-7af6-11e4-96a4-75320f905b43.png)

**Comment by clonedagain** [comment]
Still the same in V8.
The strings are there on Transifex, the group names in lists/forms are translated, but the menu entries are not.

**Comment by Yenthe666** [comment]
Hi @clonedagain,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
