### ISSUE TITLE
account_check_printing incorrect invoice lines per stub

### ISSUE THREAD

**Issue by cw-mswanson** [odoo/odoo#40157]
Impacted versions: 12

Steps to reproduce: print a check with 20 invoices

Current behavior: each stub page is missing 4 lines (with total 4* len(pages) invoices missing)

Expected behavior: each stub page has all lines

Video/Screenshot link (optional):

My workaround (inside custom module):  This work around changes 'l10n_us_check_printing.ckus_stub' template to print 9 lines to match the line 'INV_LINES_PER_STUB = 9' in /account_check_printing/models/account_payment.py'. After installing my custom module with this workaround the check stubs are no longer missing lines.

    <template id='cw_inh_check_stub' inherit_id="l10n_us_check_printing.ckus_stub">
        <xpath expr='//tbody/t[1]' position="attributes">
            <attribute name="t-foreach">
                page['stub_lines'][:9]
            </attribute>
        </xpath>

        <xpath expr='//tbody/tr[1]' position="attributes">
            <attribute name="t-if">
                len(page['stub_lines']) > 9
            </attribute>
        </xpath>

    </template>

**Comment by pedrobaeza** [comment]
As this is something enterprise, please publish a ticket on odoo.com/help instead.

**Comment by Yenthe666** [comment]
@pedrobaeza please don't add `OE` on the report as long as there is no OPW generated, otherwise it'll be hard to keep track

**Comment by pedrobaeza** [comment]
For me that's the label to say that it's something enterprise. It doesn't matter if there's OPW ticket or not. Can we create another label for that, @mart-e ?

**Comment by mart-e** [comment]
No, if you check the label tooltip, it is "the report is linked to a support ticket (opw-...)", so should be set when it is related to an support ticket.

@cw-mswanson Pedro has a point though, for enterprise source code issue, you should create a support ticket instead, this is mainly for the community part.
If you have a fix for the issue, you can directly create a PR on https://github.com/odoo/enterprise

**Comment by cw-mswanson** [comment]
Ticket at odoo.com/help is #2123856
Also, my initial decision was to open an issue at OE, however access to that repo is held by the boss, so here we are.  If we think about it, this issue involves OE and OCE since one module is OE and one is OCE.

**Comment by Abridbus** [comment]
Had to be a little bit more complete
Here is the PR https://github.com/odoo/enterprise/pull/7090 for v12

Thanks for your input!

**Comment by cw-mswanson** [comment]
This has been merged
