### ISSUE TITLE
Contracts list view - slow processing/rendering of view contents

### ISSUE THREAD

**Issue by giangori** [odoo/odoo#4015]
Hi,
We've noticed that in v7 (and most likely in v8 as well) the processing time required to display contracts list view can become unjustifiable lengthy. Of course few contracts aren't enough to show the problem, but try creating 200-300 contracts and you may have to wait from 5 to 15 seconds before getting the view updated.
The tests we made included simple contracts (no linked timesheet lines) and service contracts with a lot of timesheet lines.

**Comment by Yenthe666** [comment]
Hi @giangori,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
