### ISSUE TITLE
[11.0] Many2many values not Updated While using many2many_checkboxes widget

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#40160]
Impacted versions:
11.0

Steps to reproduce:
1. Create Many2many field
2. Set Widget as Many2many_checkboxes
3. Update many2many value using self.update

Current behavior:
1. Values not Updated

Expected behavior:
1. Values need to be Update

Many2many Values not Updated while using many2many_checkboxes widget. Otherwise its's working fine.

**Comment by pedrobaeza** [comment]
Duplicate of #38509
