### ISSUE TITLE
[12.0] Overwrite javascript in field_utils.js

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#40174]
How can overwrite date function in field_utils.js
`odoo.define('web.field_utils', function (require) {
"use strict";

/**
 * Returns a string representing a date.  If the value is false, then we return
 * an empty string. Note that this is dependant on the localization settings
 *
 * @param {Moment|false} value
 * @param {Object} [field]
 *        a description of the field (note: this parameter is ignored)
 * @param {Object} [options] additional options
 * @param {boolean} [options.timezone=true] use the user timezone when formating the
 *        date
 * @returns {string}
 */
function formatDate(value, field, options) {
    if (value === false) {
        return "";
    }
    if (field && field.type === 'datetime') {
        if (!options || !('timezone' in options) || options.timezone) {
            value = value.clone().add(session.getTZOffset(value), 'minutes');
        }
    }
    var date_format = time.getLangDateFormat();
    return value.format(date_format);
}
}`

**Comment by Yenthe666** [comment]
Hi,

Sorry but this issue tracker is only used for reporting bugs in the official Odoo code.
Please ask questions on the official help forums at https://www.odoo.com/forum/help-1

Regards,
Yenthe
