### ISSUE TITLE
[12.0] POS translation

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#40178]
**Impacted versions:**
12.0

**Current behavior:**
Some sequences are not show on transifex, so, a lot of messages are not translated (only available in english)

**Expected behavior:**
To be able to find text in transifex

**Video/Screenshot link (optional):**
Example, message displayed when attempting to close offline session : 
[View on github](https://github.com/odoo/odoo/blob/13.0/addons/point_of_sale/static/src/js/gui.js#L287)

Result on transifex : 
[View on Transifex](https://www.transifex.com/odoo/odoo-12/translate/#fr/point_of_sale?q=text%3A'You+can+exit+the+Point+of+Sale%2C+but+do')

**Comment by Yenthe666** [comment]
@switch87 this does seem to be the case.
Look at this part of the code:
https://github.com/odoo/odoo/blob/de47582bc326b02b770f94570cb2aa39035b8155/addons/point_of_sale/static/src/js/gui.js#L283-L292
You can see the first part of the term in the `pot` file at
https://github.com/odoo/odoo/blob/de47582bc326b02b770f94570cb2aa39035b8155/addons/point_of_sale/i18n/point_of_sale.pot#L3984-L3989
While the second part of the term is not showing up in the `.pot` file, such as "You can exit the Point of Sale, but do"

Cc @mart-e as it is about translations.

**Comment by mart-e** [comment]
Damn, these people really didn't understood how translations are working.
Fixed at #40191

**Comment by Yenthe666** [comment]
😉

**Comment by gregory-moka** [comment]
Thanks,
I do not know how it work, but, clever to be able to spot the issue.
Thanks @mart-e & @Yenthe666 :)

**Comment by Yenthe666** [comment]
Well if you have a translation term that is splitted with `,` on multi-line and if you join it with `.join(' ')` then the framework doesn't pick up the terms. The PR from Martin will resolve this :)

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/54e5779cfffe309ced08e8fc5426c1b5e4f56ec6

**Comment by Yenthe666** [comment]
Thanks for the quick fix Martin.
