### ISSUE TITLE
on_change event not triggered on one2many fields when item is added

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#4018]
**Adding items to one2many fields doesn't trigger on_change events**

Impacted versions:
- 7.0 and 8.0 (master not tested) --> web module

Steps to reproduce:
1. simply add on_change method for sale.order field 'order_line' (code samples below)
2. add on_change attribute in view (v7 only; code sample below)
3. add breakpoint to method
4. open new sale order
5. add an order line, so that you're not editing the line anymore
6. no on_change trigger 'happening'

Additional:
- deleting an item is triggering the event
- editing an existing item is triggering the event

Current behavior:
- event not triggered

Expected behavior:
- event triggered

Code Samples v7:

```
from openerp.osv import orm

class sale_order(orm.Model):
    _inherit = "sale.order"

    def onchange_order_line(self, cr, uid, ids, order_line, context=None):
        return {}



<record id="sale_order_test_o2m_onchange" model="ir.ui.view">
    <field name="name">test o2m on_change event</field>
    <field name="model">sale.order</field>
    <field name="inherit_id" ref="sale.view_order_form" />
    <field name="arch" type="xml">
        <field name="order_line" position="attributes">
            <attribute name="on_change">onchange_order_line(order_line, context)</attribute>
        </field>
    </field>
</record>
```

Code Samples v8:

```
from openerp import models

class sale_order(models.Model):
    _inherit = "sale.order"

    @api.onchange('order_line')
    def onchange_order_line(self):
        pass
```

**Comment by Yenthe666** [comment]
Hi @intero-chz,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
