### ISSUE TITLE
[8.0] check date in period constraint appears too late with new bank statement

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#4020]
If I create a new bank statement for the période of december and one of the bank statement line belongs to an other period (and I have previously set my bank journal  as Check Date in Period = true).

I will see eventually the following blocking message but far too late since it appears in the reconcile view at the move creation. 

ValidateError

Field(s) `date` failed against a constraint: The date of your Journal Entry is not in the defined period! You should change the date or remove this constraint from the journal.

Could not we have this constraint when user try to switch to the reconcile view ?

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
