### ISSUE TITLE
Add RPM dependencies: python-gevent

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#4021]
Installing the RPM package from http://nightly.odoo.com/8.0/nightly/rpm/ should install too `python-gevent` (used when running `openerp-gevent`) and `wkhtmltopdf`.

**Comment by Yenthe666** [comment]
@Yajo I believe we can close this now right? 😉 It has been handled in newer versions.

**Comment by Yajo** [comment]
Since Docker I don't care about RPM packages anymore 😆
