### ISSUE TITLE
Responsive POS

### ISSUE THREAD

**Issue by ljacobo** [odoo/odoo#40210]
Impacted versions:
Odoo CE 11

----

Hi, i've tried to use the POS with iPads and the web is totally responsive, but not with Android devices.

How can i set the webview of the POS responsive to those devices?

Thnks

**Comment by pedrobaeza** [comment]
PoS interface doesn't provide responsiveness for now.

@switch87 any plans to add it in future versions?

**Comment by switch87** [comment]
@ljacobo It is not supported for now. I noticed that it looks better on some browsers on mobile, so try to experiment a little. Setting the page to desktop version in the browser menu also helps on some devices.

@pedrobaeza my colleague is working on it for master https://github.com/odoo/odoo/pull/39793

**Comment by pedrobaeza** [comment]
Thanks for the info, Gert!
