### ISSUE TITLE
IE 11 incompatibility with some JS code

### ISSUE THREAD

**Issue by Apollo-develop** [odoo/odoo#40219]
**Impacted versions:**
13.x

**Steps to reproduce:** 
Go to website Odoo and open your console (debug)

**Current behavior:**
Some problems with JS.

I think IE doesn't understand this : 
`() => {...}`

But that is OK : 
`function () {...}`

Actually, there are 14 files (29 results) where Odoo uses this syntax...

**Expected behavior:**
No problem ?

**Video/Screenshot link (optional):**
![Error JS](https://user-images.githubusercontent.com/26792532/68780929-49d6c000-0637-11ea-8373-6a599f49274b.png)

**Comment by pedrobaeza** [comment]
IE is not compatible with Odoo 13, so this is the reason it fails.

Closing as incompatible browser.
