### ISSUE TITLE
[v11]Google Calendar sync  double events when an attendee is a Group from G Suite

### ISSUE THREAD

**Issue by anabeladamas** [odoo/odoo#40229]
Impacted versions:
11.0-20191004
Steps to reproduce:
I have several users doing Sync with google calendar , those users belong to a  company that uses G Suite. 
In G Suite create a group with 4 Odoo users (steps to create a group : https://support.google.com/a/answer/9400062?hl=en )

Current behavior:
1) With user1 https://calendar.google.com/ create an event with only the group as the ateendee. 
2) With user2  in Odoo click on button "Sync with Google";
3) With user3  in Odoo click on button "Sync with Google";
4) With user4  in Odoo click on button "Sync with Google". 

In steps 2), 3) 4) the Odoo is creating an event, so for the same meeting I have 3 event in Odoo. 
![image](https://user-images.githubusercontent.com/10194171/68791720-cbcbe680-0641-11ea-8506-5f994013dcb6.png)

Expected behavior:
Only one meeting should be created in Odoo. 

How can I prevent this duplication?

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.

Regards,
Yenthe

**Comment by agusramdan** [comment]
in version 13 we have same issue like this.
