### ISSUE TITLE
Error in the kanban view of Inventory Module

### ISSUE THREAD

**Issue by JerryPan1122** [odoo/odoo#40233]
Impacted versions:
Odoo V 12 
Steps to reproduce:
1. In the overview of inventory, select 'Warehouse' under 'Group By'
2. Click 'Add a Column', type anything in the input box and then click 'ADD'
Current behavior:
Error popped up 
Expected behavior:
Don't Know
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/39695517/68824038-886c8900-06d0-11ea-86dc-e0fc3061cfe6.png)
![image](https://user-images.githubusercontent.com/39695517/68824051-90c4c400-06d0-11ea-9c9e-19a88e5979c3.png)
![image](https://user-images.githubusercontent.com/39695517/68824061-98846880-06d0-11ea-9552-9faea59351ce.png)

**Comment by JerryPan1122** [comment]
@lap-odoo Hi, Laura, would you please help to see this issue?

**Comment by lap-odoo** [comment]
@JerryPan1122 Thanks Jerry, we'll take care of this. (Ticket : 2124162)
