### ISSUE TITLE
posonlyargs missing from arguments

### ISSUE THREAD

**Issue by dunkin1922** [odoo/odoo#40232]
Impacted versions: 13

Steps to reproduce: clone fresh odoo git

Current behavior: unable to render web/login view due to Qweb exception

Expected behavior: render a log in screen

Video/Screenshot link (optional):

odoo.addons.base.models.qweb.QWebException: required field "posonlyargs" missing from arguments
Traceback (most recent call last):
  File "/Users/dunkin/odoo-dev/odoo/odoo/addons/base/models/qweb.py", line 314, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
TypeError: required field "posonlyargs" missing from arguments

Error when compiling AST
TypeError: required field "posonlyargs" missing from arguments
Template: web.login
Path: /t/t/form/input[2]
Node: <input type="hidden" name="redirect" t-att-value="redirect"/>

**Comment by tanghulu0608** [comment]
I have the same issue too.

**Comment by pedrobaeza** [comment]
Odoo is not yet compatible with Python 3.8, so it's normal that you face this. Use 3.6 or 3.7.

**Comment by bodedra** [comment]
@pedrobaeza I have following configuration:

OS - Ubuntu 20.04
Python - 3.8

I face same issue with only few restored database. Not all restored database or fresh database.

Any suggestion?

**Comment by bodedra** [comment]
@pedrobaeza JFI I have setup python3.7 venv and it works fine.

**Comment by pedrobaeza** [comment]
Yes, using P3.8 is not advisable IMO.

**Comment by shazzwazz20** [comment]
Any road map for making odoo compatible with 3.8?
 https://en.wikipedia.org/wiki/History_of_Python
As per wiki 
Support cycle already ended 2018-12-24 and security fixes ending next year by 2021-12.
Screenshot attached 
![screenshot-en wikipedia org-2020 10 20-20_00_30(1)](https://user-images.githubusercontent.com/60392726/96601239-6ed7b680-130f-11eb-93ca-892086795eba.png)

**Comment by Yenthe666** [comment]
A lot is already done, e.g https://github.com/odoo/odoo/pull/59480
Still some fixes being written too though: https://github.com/odoo/odoo/pull/55027
Browse through the history to find them all :)
