### ISSUE TITLE
[WISH] Notification handle by Email and Odoo，or other ways.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#40234]
Impacted versions:
All Version

Current behavior:
User can select only one option in Notification. Maybe sometimes ,they want to be nofitied in Email and in odoo, or other ways,for example Wechat in China.

Expected behavior:
Multiple select in Notification settings

Video/Screenshot link (optional):
<img width="410" alt="image" src="https://user-images.githubusercontent.com/5561864/68827426-e737ff80-06dc-11ea-9a99-42c0f8d949e0.png">

**Comment by Yenthe666** [comment]
Wouldn't you basically get a big overload of messages though? You'd get both emails **and** notifications. That doesn't seem very effective to me.

**Comment by tanghulu0608** [comment]
for example ,in github, when I get some notitications,I receive the email
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/5561864/68839309-6b00e480-06fb-11ea-8cfd-7263c8ff396a.png">
and got a github notification too
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/5561864/68839351-84a22c00-06fb-11ea-9c1a-77dd711e3f51.png">

**Comment by pedrobaeza** [comment]
That was the behavior prior to 11, and it was changed due to user confusion to be one or the other, but not both, so closing this as won't fix, as it has been discarded previously.

**Comment by Yenthe666** [comment]
Yeah and its probably not a good idea anyway, it generates confusion 😉

**Comment by tanghulu0608** [comment]
What about make this an option in system setting.Let system administrator device which behavior is good.🤓

**Comment by Yenthe666** [comment]
@tanghulu0608 once a feature has been removed in Odoo they won't introduce it again in 99% of the cases. Why don't you go with a custom module for this?

**Comment by tanghulu0608** [comment]
@Yenthe666  Thank you for your reply. But I still want this behavior very much.💔

**Comment by linhhonblade** [comment]
Anyone has the link to the commit which changed the behavior of this notification settings? My customer still want this behavior.

**Comment by pbanswer** [comment]
Hope that question is actual. is there any work in this direction? why i can't choose behavior that i need

**Comment by SpeiserS-manaTec** [comment]
I didn't test it, but this app seems to solve this question: https://apps.odoo.com/apps/modules/16.0/to_mail_notif_and_email/

someone already tested it and can recommend it or not recommend it?
