### ISSUE TITLE
[13.0] accounting: cannot add or remove analytic tag when reconcile bank statement

### ISSUE THREAD

**Issue by yankinmax** [odoo/odoo#40246]
Impacted versions: 13

Steps to reproduce:
1. From Accounting Dashboard choose Bank then press Import statement. Or, if you have already imported statement, choose Reconcile items.
2. Choose Partner then Manual Operations page is opened.
3. Add or Remove Analytic Tags from Search More popup.
Current behavior:
When choose Analytic Tag from dropdown everything works properly. When choose Search More to add many Analytic Tags they are not correctly added and cannot be removed.
Expected behavior:
Analytic Tags added from Search More are shown correctly and can be removed.
Video/Screenshot link (optional):
http://joxi.ru/DmBw53Dfzdvaa2

**Comment by pedrobaeza** [comment]
@Yenthe666 I would say this is something more of the web client

**Comment by Yenthe666** [comment]
Hmm I agree after reading again. Perhaps framework?

**Comment by yankinmax** [comment]
What do you mean @Yenthe666 , when you say framework? I have tried it several times in different browsers. This also happen with my project on Odoo.sh, so code is up-to-date and container is built by Odoo.sh environment. Can you help me? Probably you can advise another way to import bank statements. Accountants in my company need Analytic tags.

**Comment by yankinmax** [comment]
Can anybody say, what should be done next, after creating the issue? Will somebody from Odoo fix this?

**Comment by Yenthe666** [comment]
@yankinmax you basically have to wait untill somebody from Odoo S.A checks it. This can be in days, weeks, months or even years. If you have an enterprise license I'd enourage you to create an issue at odoo.com/help as the Github issue tracker is based on best efforts.

**Comment by yankinmax** [comment]
@Yenthe666 thank you very much for your answer, I suggested, that all these issues are considered to be fixed. I was wrong. I will definitely write to my Manager in Odoo.

**Comment by yankinmax** [comment]
This issue was fixed with commit
https://github.com/odoo/odoo/commit/99b23da7c5ebd0ae2f1816d5db659ac026a7ef9c
Have a nice day!

**Comment by Yenthe666** [comment]
🎉 thanks for the update!
