### ISSUE TITLE
Create lines purchase quotations

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#4025]
1) Steps to reproduce the issue you have observed
- I create a new quotation order.
- I complete required data
- I add several lines to order
- I press in two ocations the button 'new line'

Can find a demonstrative video here: 
https://www.youtube.com/watch?v=fk40MjDCDHo&feature=youtu.be

2) The result you observed:
I can press in two ocations the button 'new line', although this have required fields

 3) The result you expected
Unable to add a new line if you have not completed the required data

4) The platform your are using
Ubuntu 14.04

Revno openerp V7.
d6daf5fa2f3960d40b0fdf7e93365d918dade565

**Comment by Yenthe666** [comment]
Hi @luistorresm ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
