### ISSUE TITLE
[8.0] Incorrect journal entries created when using drop shipping flow

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#4028]
Hello,

When a sales order is created with an item containing the route "drop shipping", where the product has inventory valuation = Real Time, no account journal entry is generated in the move from the supplier to the customer.

However, at the time of accepting the supplier invoice the product's stock input account is credited in the associated Account Journal Entry. The stock input account is also known in the accounting context as a " Goods Received Not Invoiced" account, and it is considered a Current Liabilities account. But this account is never going to be debited, because the physical move was not recorded in the Account Journal.

On the side of the customer invoice, when it is accepted, the product's stock output account is credited in the associated Account Journal Entry. The stock output account is known as "Goods Issued Not Invoiced" and it is considered as an Accrued Expenses account. But this account is never going to be debited, because the physical move was not recorded in the Account Journal.

In my opinion, a proper drop shipment flow should not make use of the stock input or stock output accounts. The overall process should consider the product as a physical product from a logistic perspective, and as a service from an accounting perspective.

Regards,
Jordi Ballester

**Comment by sdalexander** [comment]
Hi Jordi
did anything happen with this Issue? 
as I am getting the same issue at a client of mine who has real time accounting set on the product but does Drop ship as well. 
The customer invoice does a move from the output account on the category to the Expense account,
but as the stock does not come into his locations , no entry is made from from stock to the output account to balance it out.

I am looking for a solution to this.

regards
Steve Alexander 
Opensys Ltd

**Comment by bistaray** [comment]
See also https://github.com/odoo/odoo/issues/12687

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
