### ISSUE TITLE
No print "document layout" - Odoo 13 CE

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#40293]
Impacted versions: Odoo 13

Good morning, in Odoo 13 community version, when I try to print a PDF quotes, orders, the document layout are not printed.

I attach document with the error
[Cotización - S00349.pdf](https://github.com/odoo/odoo/files/3847463/Cotizacion.-.S00349.pdf)

I appreciate the help, thanks.

Luis

**Comment by pedrobaeza** [comment]
You have to configure properly your proxy and maybe put a `report.url` system parameter pointing to `http://127.0.0.1:8069`. If not, please search for this common problem across issues or forum.

Closing as no Odoo issue, but deployment problem.

**Comment by LSR29** [comment]
Thanks!
