### ISSUE TITLE
Update code error

### ISSUE THREAD

**Issue by mom988** [odoo/odoo#40306]
Impacted versions:
V13 Enterprise , 20191114
Steps to 
1. Copy an existing database name 13e_database_20191021updatetest
2. Create a new configuration file to refer to the new code and configuration database information
3. perform: / etc/odoo# / usr/bin/odoo - config/etc/odoo/odoo20191014up conf - logfile/var/log/odoo/odoo13e - server - uptest. Log - stop - after - init - d 13e_database_20191021updatetest - u all
4. Report error after logging in this database
- reproduce:

```

错误:


追溯:
getScrollPosition@http://myurl/web/content/1763-2e54c80/web.assets_backend.js:506:1
OdooClass.extend/</prototype[name]</<@http://myurl/web/content/1762-64070bd/web.assets_common.js:3866:488
toggle_home_menu/<@http://myurl/web/content/1763-2e54c80/web.assets_backend.js:504:101
setTimeout handler*resolve/<@http://myurl/web/content/1762-64070bd/web.assets_common.js:925:8
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:909:231
fireWith@http://myurl/web/content/1762-64070bd/web.assets_common.js:915:181
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:916:36
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:909:231
fireWith@http://myurl/web/content/1762-64070bd/web.assets_common.js:915:181
mightThrow@http://myurl/web/content/1762-64070bd/web.assets_common.js:922:32
resolve/</process<@http://myurl/web/content/1762-64070bd/web.assets_common.js:922:89
setTimeout handler*resolve/<@http://myurl/web/content/1762-64070bd/web.assets_common.js:925:8
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:909:231
fireWith@http://myurl/web/content/1762-64070bd/web.assets_common.js:915:181
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:916:36
fire@http://myurl/web/content/1762-64070bd/web.assets_common.js:909:231
fireWith@http://myurl/web/content/1762-64070bd/web.assets_common.js:915:181
done@http://myurl/web/content/1762-64070bd/web.assets_common.js:1317:95
callback/<@http://myurl/web/content/1762-64070bd/web.assets_common.js:1330:322
EventHandlerNonNull*send@http://myurl/web/content/1762-64070bd/web.assets_common.js:1330:543
ajax@http://myurl/web/content/1762-64070bd/web.assets_common.js:1309:31
jsonRpc/<@http://myurl/web/content/1762-64070bd/web.assets_common.js:3836:650
_genericJsonRpc@http://myurl/web/content/1762-64070bd/web.assets_common.js:3831:111
jsonRpc@http://myurl/web/conten
```

Current behavior:
Error popped up
Expected behavior:
See main menu normally and use normally
Video/Screenshot link (optional):
![图片](https://user-images.githubusercontent.com/6219061/68924329-892e1980-07bb-11ea-9e4f-a88605b10a31.png)
![图片](https://user-images.githubusercontent.com/6219061/68924454-d611f000-07bb-11ea-816e-0767c4dfa051.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by mom988** [comment]
thank you ,i will try it again
