### ISSUE TITLE
No collation by user

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#40318]
Impacted versions: all

Steps to reproduce:

1. Import these partners: [res.partner.xlsx](https://github.com/odoo/odoo/files/3850904/res.partner.xlsx) (They're just partners called "test AA", "test AB", "test LB", "test ZA", "test aa", "test ab", "test la", "test zb", "test ÄA" and "test äb").
1. Go to contacts list view.
1. Search for "test".
1. Order by name.

Current behavior:

![2019-11-15_10-00](https://user-images.githubusercontent.com/973709/68934559-cb8d3180-078e-11ea-8a13-07c21a1b38d4.png)

:point_up: That's enterprise runbot v13.

No mater what locale you user is using, the order is always unexpected. You can reproduce it easily with this SQL query:

```sql
SELECT foo FROM (SELECT UNNEST(ARRAY['test AA', 'test AB', 'test LB', 'test ZA', 'test aa', 'test ab', 'test la', 'test zb', 'test ÄA', 'test äb']) AS foo) AS bar 
ORDER BY foo;

   foo   
---------
 test AA
 test AB
 test LB
 test ZA
 test aa
 test ab
 test la
 test zb
 test ÄA
 test äb
(10 rows)

```

This happens always, no matter the table you're querying.

Expected behavior:

Result order should depend on user locale. This same recordset would be ordered differently in Austria and Finland:

```sql
-- Austrian collation
SELECT foo FROM (SELECT UNNEST(ARRAY['test AA', 'test AB', 'test LB', 'test ZA', 'test aa', 'test ab', 'test la', 'test zb', 'test ÄA', 'test äb']) AS foo) AS bar 
ORDER BY foo COLLATE "de-AT-x-icu";

   foo   
---------
 test aa
 test AA
 test ÄA
 test ab
 test AB
 test äb
 test la
 test LB
 test ZA
 test zb
(10 rows)

-- Finnish collation
SELECT foo FROM (SELECT UNNEST(ARRAY['test AA', 'test AB', 'test LB', 'test ZA', 'test aa', 'test ab', 'test la', 'test zb', 'test ÄA', 'test äb']) AS foo) AS bar 
ORDER BY foo COLLATE "fi-FI-x-icu";

   foo   
---------
 test aa
 test AA
 test ab
 test AB
 test la
 test LB
 test ZA
 test zb
 test ÄA
 test äb
(10 rows)
```

So, odoo's ORM should:

1. Query Postgres to see if there are ICU extensions available, easily done with `SELECT * FROM pg_collation`. That can be stored in the registry, the same way as `has_unaccent` (once per registry, to avoid too many queries): https://github.com/odoo/odoo/blob/c32126da5ac55a03637d82cf520b8655be8546e6/odoo/modules/registry.py#L141-L145
1. Add automatically the appropriate ICU collation to the `ORDER BY` clause if all of these are true:
   - User is ordering a char/text field.
   - There's a lang in the context.
   - `"{}-{}-x-icu".format(*env.lang.split("_")) in registry.available_collations` (pseudo-code)

This way, all users would get their expected order results, in any database installation (I mean, regardless of system locale, as long as there is ICU support).

@Tecnativa

**Comment by pedrobaeza** [comment]
Not sure who to ping with this. Maybe @odony or @mart-e?

**Comment by mart-e** [comment]
The problem of using a different collation is that you will lose the benefit of indexes for filtering and sorting. Doing so will greatly deteriorate the performances:

```
# explain analyze select display_name from res_partner where display_name = 'Martin Trigaux' collate "fr-FR-x-icu" order by display_name collate "fr-FR-x-icu" limit 10;
                                                                                  QUERY PLAN                                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=1000.43..47379.01 rows=5 width=48) (actual time=286.706..286.743 rows=2 loops=1)
   ->  Gather  (cost=1000.43..47379.01 rows=5 width=48) (actual time=286.705..312.327 rows=2 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Parallel Index Only Scan using res_partner_display_name_index on res_partner  (cost=0.43..46378.51 rows=2 width=48) (actual time=224.533..282.181 rows=1 loops=3)
               Filter: ((display_name)::text = 'Martin Trigaux'::text COLLATE "fr-FR-x-icu")
               Rows Removed by Filter: 597239
               Heap Fetches: 36791
 Planning time: 0.180 ms
 Execution time: 312.368 ms
(10 rows)
```
vs
```
# explain analyze select display_name from res_partner where display_name = 'Martin Trigaux' order by display_name limit 10;
                                                                       QUERY PLAN                                                                       
--------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.43..2.51 rows=5 width=16) (actual time=0.032..0.033 rows=2 loops=1)
   ->  Index Only Scan using res_partner_display_name_index on res_partner  (cost=0.43..2.51 rows=5 width=16) (actual time=0.030..0.031 rows=2 loops=1)
         Index Cond: (display_name = 'Martin Trigaux'::text)
         Heap Fetches: 0
 Planning time: 0.177 ms
 Execution time: 0.076 ms
(6 rows)
```

You could still benefit from the indexes using a collate but it means recomputing the indexes in each collation present on the server (we have ~15 languages on odoo.com, and our index table is already in Gb)

**Comment by Yajo** [comment]
:thinking: Hmm I see. However the results orders as they appear now are really very unexpected. OK, some ideas:

How about allowing to choose in which collation(s) will the indexes be made? Or, more specifically, which would be the default language of those installed, and if other ones are to be indexed too.

Also when a database is created, user is asked to provide a default locale. Can't that one be taken as a sensible default collation for the `CREATE DATABASE` command?

This would affect only char/text indexes OTOH. I guess most indexes are for FKs and PKs, so maybe string-only indexes are not so big...

**Comment by mart-e** [comment]
> How about allowing to choose in which collation(s) will the indexes be made?

This kind of changes are not worth the effort. Tricky to implement for a niche usecase for a small benefit.

> Can't that one be taken as a sensible default collation for the CREATE DATABASE command?

See also 276ea817f4675a7357 and the full discussion at #25196 using C by default and the commit message:

> Admins who want to apply a special collation can still do so by creating the database manually, instead of letting the system do it.

Using C is a good default but admin-system that know the implications can change it.

We have this problem since forever but users can live with it because of how users behave, most of the time, when they have a very long list of records:
1. filter the results down to an acceptable number
2. look for the one you are looking for in the page

Users don't go through a long list of records with a lot of pages (in which case the order would be an issue).

The cases with issues of order are usually "nice-to-have" and more on the cosmetic side. When you see the amount of issues (linked to indexes and performances) while modifying sensitive low-level code (expect tricky localisation-related bugs), it is usually just not worth it.
