### ISSUE TITLE
Issue with Registering payments

### ISSUE THREAD

**Issue by angelwax** [odoo/odoo#4031]
Hi,

Since doing an update to the e-invocing and payment register application I have been getting an error message each time that I try to register a payment from an invoice.

Can anyone help??

This is the message I am getting;

![screen shot 2014-12-04 at 11 02 36 am](https://cloud.githubusercontent.com/assets/10069421/5292997/13f417f2-7ba5-11e4-8c07-2793c0105d5c.png)

**Comment by Yenthe666** [comment]
Hi @angelwax ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
