### ISSUE TITLE
empty email_from causes error on confirming activity

### ISSUE THREAD

**Issue by ruifranco** [odoo/odoo#40326]
Impacted versions: 13 EE

Steps to reproduce:
Set an activity as done

Current behavior:
It throws an error: "Unable to log message , please configure the sender's email address."

Expected behavior:
Allow the activity to be set as done

Comment:
Although this might have to do with some missing configuration (up to the moment not found), the truth is that the problem was solved by adding small changes to mail/models/mail_thread.py _message_compute_author method

if author_id is None: BECAME...
if author_id is None or (not author_id):

if email_from is None: BECAME...
if email_from is None or (not email_from):

**Comment by pedrobaeza** [comment]
You have to put an email on the user for avoiding that message

Closing this as not Odoo issue, but misconfiguration.

**Comment by ruifranco** [comment]
All users had an email, their employee records, too, and so did the contacts.
Only admin didn't but I don't think that if user X sets an activity as done, an email is going to be sent by admin.

**Comment by pedrobaeza** [comment]
It's not a question of sending the email or not, but a pre-requisite for the involved actors. Please put it and solved!
