### ISSUE TITLE
Adding Existing Field to Forms using Website Form Builder V13.

### ISSUE THREAD

**Issue by Tjones787** [odoo/odoo#40354]
Impacted versions: 13.0

Steps to reproduce:

1. Install **website_crm** module.

2. Navigate to website builder on the front end and create a new form using the form builder widget.
![Screenshot (14)](https://user-images.githubusercontent.com/6373037/68950618-d068da00-07bc-11ea-85ac-e82d2178a87a.png)

3. Select **Create an Opportunity** from the Action Drop down then saved the record.

4. Edit the Form, navigate to Options tab then click on add existing field.
![Screenshot (16)](https://user-images.githubusercontent.com/6373037/68950891-5b49d480-07bd-11ea-9b06-5ad74358d2e2.png)

5. Select Customer from the field list then save.
![Screenshot (17)](https://user-images.githubusercontent.com/6373037/68951254-f5aa1800-07bd-11ea-95a0-eb2eee6f1116.png)

6. An error pops up on saving.

Current behavior:

It's showing error on adding customer field to the created form.

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/odoo13/odoo13-server/odoo/http.py", line 619, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/odoo13/odoo13-server/odoo/http.py", line 309, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/odoo13/odoo13-server/odoo/tools/pycompat.py", line 14, in reraise
>     raise value
>   File "/odoo13/odoo13-server/odoo/http.py", line 664, in dispatch
>     result = self._call_function(**self.params)
>   File "/odoo13/odoo13-server/odoo/http.py", line 345, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/service/model.py", line 93, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/http.py", line 338, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/odoo13/odoo13-server/odoo/http.py", line 909, in __call__
>     return self.method(*args, **kw)
>   File "/odoo13/odoo13-server/odoo/http.py", line 510, in response_wrap
>     response = f(*args, **kw)
>   File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1238, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1230, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/odoo13/odoo13-server/odoo/api.py", line 406, in call_kw
>     result = _call_kw_model(method, model, args, kwargs)
>   File "/odoo13/odoo13-server/odoo/api.py", line 379, in _call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/models.py", line 4734, in search_read
>     records = self.search(domain or [], offset=offset, limit=limit, order=order)
>   File "/odoo13/odoo13-server/odoo/models.py", line 1556, in search
>     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
>   File "/odoo13/odoo13-server/odoo/models.py", line 4275, in _search
>     if expression.is_false(self, args):
>   File "/odoo13/odoo13-server/odoo/osv/expression.py", line 215, in is_false
>     for token in reversed(normalize_domain(domain)):
>   File "/odoo13/odoo13-server/odoo/osv/expression.py", line 192, in normalize_domain
>     assert isinstance(domain, (list, tuple)), "Domains to normalize must have a 'domain' form: a list or tuple of domain components"
> AssertionError: Domains to normalize must have a 'domain' form: a list or tuple of domain components
> 

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
It's not very logic to add that field to the form, because you don't want to disclose your customer list, but any way, it shouldn't fail.

@JKE-be something for you?

**Comment by andrewukegbu** [comment]
The customer field for previous versions allows you to only input text information(customer name), it doesn't give you a drop down with your customer list.

**Comment by andrewukegbu** [comment]
Thank you Pedrobaeza but, the customer field for previous versions allows you to only input text information(customer name), it doesn't give you a drop down with your customer list.

**Comment by pedrobaeza** [comment]
@andrewukegbu I would say that's the "Customer's Name", not "Customer", but I haven't tried.

**Comment by andrewukegbu** [comment]
@pedrobaeza Customer name is not part of the fields. Do you know any other way I can capture customer names when they fill the forms? I could easily do this with Version 11.

**Comment by pedrobaeza** [comment]
I can't say. Let's wait for an Odoo stuff answer.

**Comment by Yenthe666** [comment]
@JKE-be can somebody from the web team have a look please?

**Comment by JKE-be** [comment]
@fja-odoo can you take a quick look since you are working on it for now. Thx

**Comment by Yenthe666** [comment]
@fja-odoo hi, did you have a look at this?

**Comment by fja-odoo** [comment]
Fixed in this PR: https://github.com/odoo/odoo/pull/43409
Thank you for the reminder @Yenthe666

**Comment by Yenthe666** [comment]
Awesome, thanks for the quick feedback!
