### ISSUE TITLE
[8.0]Forum tags: Defined tags get lost when editing a question

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#4037]
Thanks for all the new improvements, but this one is still annoying.

**Comment by tde-banana-odoo** [comment]
Hello,

This has been fixed in 8 at commit 5d58b5551fa11445c7ddbd2c84270946170fc803, and in master at commit 1840acf185be9d095c2bdb1d4eeb322a0cc2f654 . Thanks for reporting !
