### ISSUE TITLE
Multi Company PoS Customer filter by company ID

### ISSUE THREAD

**Issue by alensaqe** [odoo/odoo#40388]
Impacted versions: 12/13 

Steps to reproduce: Open a PoS from one company in Odoo and click "Customer". The list of the customers will load from an rpc call /web/dataset/call_kw/res.partner/search_read the model is as res.parnter label and the function is on line load_new_partners.

Current behavior: When you have multiple companies with different customer the PoS loads all the customers from all companies.

Expected behavior: When you have multiple companies the customer will be filtered out depending on the company they belong to so there should be another domain to define ["company_id", "=" CURRENTCOMPANYID]

This may even be a setting under the company or PoS Config for users to select the expected behavior in my opinion.

**Comment by pedrobaeza** [comment]
Just unmark the proper checks ;)

![Selección_018](https://user-images.githubusercontent.com/7165771/69017727-269a7080-09a9-11ea-8e8f-f27eaf1e99dc.png)

Closing as no issue, but misconfiguration.
