### ISSUE TITLE
Unable to update QTY in manufacturing Order V13

### ISSUE THREAD

**Issue by ykozize** [odoo/odoo#40389]
Impacted versions:
13

Steps to reproduce:
Routing of 2 steps
Bill of material for lot controlled product and the components also lot control. 
Routing of 2 operations and user can start next operation after 1 qty.

Create order with like 10 QTY and proceed with first work order with only 5 of 10 qty.
Back to the order and try to update the order QTY, you will receive error:

You cannot update the quantity to do of an ongoing manufacturing order for which quality checks have been performed.

Current behavior:

Error: You cannot update the quantity to do of an ongoing manufacturing order for which quality checks have been performed.

when updating the order QTY.

this same steps is working fine on V12

Expected behavior:

the system should be able to update the order QTY even if the order is partially processed.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As this involves enterprise modules, please report it to odoo.com/help.

**Comment by sle-odoo** [comment]
Closing as per @pedrobaeza comment.
