### ISSUE TITLE
[13.0] Mail reply does not go back to thread (and looks bad)

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#40461]
Impacted versions: 13.0 ce/ee

Steps to reproduce:
Setup and send mail on a thread, e.g. helpdesk.ticket, and reply to it externally (and fetch mail).

Current behavior:
New object, e.g. ticket, or just drops the email. Also the email looks bad/is plain text in Apple Mail.

Expected behavior:
New reply on original object.

The reason this behavior is not working is because the headers used to make this decision (References: and Message-ID:) are getting changed upon receipt, in this case by Gmail. I've tested with mail going through Haraka (poste.io) and MailGun with the same errors.

Here is a MailGun sent Message-ID and what it turned into when actually received.
```
Message-ID: <5dd3028a.1c69fb81.95ee9.2cc8SMTPIN_ADDED_BROKEN@mx.google.com>
X-Google-Original-Message-ID: =?utf-8?q?=3C027010048071444=2E1574109829=2E494792699813843-open?=
=?utf-8?q?erp-25-helpdesk=2Eticket=40odoo13-test-cbd7984dc-d8mdh=3E?=
```

Here is one sent through Haraka and actually received.
```
Message-ID: <5dd2f90f.1c69fb81.5e965.87d0SMTPIN_ADDED_BROKEN@mx.google.com>
X-Google-Original-Message-ID: =?utf-8?q?=3C627221898242243=2E1574107405=2E459551572799683-open?=
=?utf-8?q?erp-3-helpdesk=2Eticket=40c6f342e1056a=3E?=
```

I believe the problem was introduced into `odoo/addons/base/models/ir_mail_server.py` in https://github.com/odoo/odoo/commit/18299d7e5051cdad29854bc7280db5002a209500

If I checkout `odoo/addons/base/models/ir_mail_server.py` from the prior commit then the correct sending behavior is restored.

Additionally Apple Mail will display the HTML version of the email with this file overridden.

**Comment by jaredkipe** [comment]
@Julien00859 You are the author on the linked commit, do you need any additional information?

**Comment by Julien00859** [comment]
@jaredkipe the linked commit in not in v13

**Comment by Julien00859** [comment]
I cannot reproduce your problem on v13. Make sure your email configuration is right and that you're effectively running v13.

**Comment by Julien00859** [comment]
It is working on master too.

My setup:
1) Enable the external email servers (General Settings > Discuss > External Email Server)
2) Setup the alias domain on that email server (`domain.tld`)
3) Setup a catchall incoming email (`catchall@domain.tld`)
4) Setup a bounce outgoing email (`bounce@domaine.tld`)
5) Setup the email alias for helpdesk (`support@domain.tld`)

My test:
1) Send an email to `support@domain.tld` using my own address.
2) Reply using Mitchel Admin in the chatter of the created ticket.
3) Reply to that email from my email client.

All messages were sent by email and logged in the chatter correctly.

Don't hesitate to open a support ticket !

**Comment by jaredkipe** [comment]
You are correct, I must have some left over master stuff that didn't make it into 13 in my 13 branch.  

That said, the issue will happen with that commit's odoo/addons/base/models/ir_mail_server.py  file.  The issue isn't sending mail or receiving it if you're receiving a known email.  The problem is that the "Message-ID" header is malformed in some way that the receiver will modify the contents of the message so that when you reply to it, it no longer relates to the original. At least some of it might depend on who is doing the receiving.
