### ISSUE TITLE
Multi website not compatible with dbfilter = %h

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#40460]
Impacted versions: 12 (13?)

Current behavior:
Setting dbfilter = %h in config will cause the second site to show the default create new database window instead of the configured second website.

Expected behavior:
Perhaps have odoo check websites configured. 
Or Maybe even add a new flag to config to check websites instead of database name? 
Or something. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why do you say it's not compatible? We have several working without problem. The requirement is to have a reverse proxy + config properly configured.

**Comment by kimasplund** [comment]
Ooh my bad then. 
perhaps you can shed abit of light on the reverse proxy config. Cos i cant seem to get it working
closed this issue if its just me that cant get it configured correctly thats the issue :D

**Comment by Yenthe666** [comment]
@kimasplund have a look at https://www.odoo.com/documentation/13.0/setup/deploy.html#https - it might help you get you started. ;)

**Comment by kimasplund** [comment]
@Yenthe666 
That is pretty much the config i have working, and it works fine for first domain. 
But what should i change to get it working with second domain? If i make a second one like that for second domain it will give me a create new database.
