### ISSUE TITLE
[8.0]Human Resource: model in a module and its menu in an other

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#4046]
The model hr.job is declared and used in the hr module.
But no menu is declared to manage it.

To get it you have to install the hr.recruitment module. Even if you don't need it.

Don't you think it is inconsistent ?
The menu declaration should be moved from hr.recruitment to hr.

Regards

**Comment by Yenthe666** [comment]
Hi @user,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. It shouldn't be a problem anymore though. 😉 

Regards,
Yenthe
