### ISSUE TITLE
[7.0] Image data not embedded in manually-sent email

### ISSUE THREAD

**Issue by tompickering** [odoo/odoo#4047]
When manually sending am email from OpenERP v7.0 which features the company logo, the image data is not embedded properly.

Steps to reproduce:
- From a fresh installation, ensure that the company is configured with a logo.
- Embed the image in an email template (e.g. the default 'Invoice - Send by Email') by using the following (for example); "&lt;p&gt; &lt;img src="data:image/png;base64,${object.company_id.logo}" style="width: 300px;height: 80px;" /&gt; &lt;/p&gt;"
- Manually send the email to a partner (following the example, using the 'Send by Email' button on an invoice). The logo should be present and correct in the preview shown in the wizard.

Result: The email is received by the partner but the image data is not present (in Thunderbird, the image 'box' is displayed with a 'broken link' icon).

**Comment by tompickering** [comment]
We ultimateley managed to work around this by overriding a component of an imported module. The following code was inserted near the top of openerp/tools/mail.py in the server:

<pre>
# Override the regex as defined in the lxml.html.clean
# module in order to allow the preservation of image data.
clean._is_javascript_scheme = re.compile(
         r'(?:javascript|jscript|livescript|vbscript|about|mocha):',
         re.I).search
</pre>

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

Regards
