### ISSUE TITLE
[IMP] add phone number to partner name  

### ISSUE THREAD

**Issue by andriisem** [odoo/odoo#40479]
Impacted versions:
All

Current behavior:

method _name_get does not have options to display a phone number 

Expected behavior:

add option features show number 

like this:
```python
if self._context.get('show_phone') and partner.phone:
    name = "%s \n %s" % (name, partner.phone)
```

is it make sense? the second client asks me about this

**Comment by Yenthe666** [comment]
Hi @andriisem,

Thanks for the suggestion but `_name_get` should really just return the name of the contact. If you'd like to customize this I'd suggest you to do this in a custom module by inheriting the model. It looks like a rather specific request, which I didn't get from over 60 projects honestly.

Regards,
Yenthe

**Comment by andriisem** [comment]
Thank you @Yenthe666 

another question

```xml
<field name = "partner_id" widget = "res_partner_many2one" context = "{'res_partner_search_mode': 'supplier', 'show_vat': True}" placeholder = "Name, TIN, Email, or Reference" />
```
https://github.com/odoo/odoo/blob/13.0/addons/purchase/views/purchase_views.xml#L159:L160

why `partner_id` on `purchase.order` without option `{'always_reload': True}`?

not working `show_vat` 

how should it be right?

**Comment by Yenthe666** [comment]
It shouldn't always reload/update, especially not when confirmed :) It gets the VAT from the customer anyways so nothing needed?
