### ISSUE TITLE
Cannot import bom in v13

### ISSUE THREAD

**Issue by caihongsoft** [odoo/odoo#40488]
Impacted versions:enterprise 13

Steps to reproduce: import bom with the bom sample file

Current behavior:
Missing required value for the field 'product_id' at 2 different rows:
Between rows 2 and 8
Between rows 9 and 17
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you specify which bom sample file?

**Comment by caihongsoft** [comment]
Now I can import bom. because of wrong bom line field map.
