### ISSUE TITLE
[13.0] Duplicate field declaration

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#40521]
Hello,

We've noticed that the user_id field on the new account/models/account_move.py file is duplicated, with a minor difference (help string on the second one).

https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L125

https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L191

Thank you.

**Comment by sswapnesh** [comment]
https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L125 should be removed in master.

Cc @qdp-odoo

**Comment by Yenthe666** [comment]
I made a quick PR for this at https://github.com/odoo/odoo/pull/40542

**Comment by Yenthe666** [comment]
This has been fixed in https://github.com/odoo/odoo/commit/3cf3c2dbd40a8725284608f7b9cdffd65b0c7cc0
