### ISSUE TITLE
[13.0] UnboundLocalError 

### ISSUE THREAD

**Issue by o2deepak** [odoo/odoo#40538]
Impacted versions: 13.0

Current behavior:
odoo/13.0/addons/hr_recruitment/models/hr_recruitment.py", line 249, in _onchange_job_id_internal
    'company_id': company_id,
UnboundLocalError: local variable 'company_id' referenced

**Comment by pedrobaeza** [comment]
Already fixed in 47d2cc94009c6cfd7f1528b45602d56b7c17ed2e

Please always update your source code before posting things.
