### ISSUE TITLE
[12] Unable to Filter by Location or Warehouse

### ISSUE THREAD

**Issue by captivea-tja** [odoo/odoo#40534]
Impacted versions:
12
Steps to reproduce:
Inventory -> Master Data -> Products -> Filters -> Add Custom Filters -> Inventory Location
Current behavior:
Inventory Location field gives same result for is set and is not set.
Expected behavior:
To be able to filter by Inventory Location
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this a limitation of property fields search.

**Comment by sle-odoo** [comment]
This field is used to compute the available/forecast quantity per location. There's also a warehouse one. It won't make products appear or disappear in your kanban.

Regards
