### ISSUE TITLE
[13.0] Improve Or Bug？ Bom ：A variant of the same product template cannot be used in the bom details of the finished product (variant)

### ISSUE THREAD

**Issue by mom988** [odoo/odoo#40540]
Impacted versions:
ODOO 13 Enterprise
Steps to reproduce:

1. Create the product as A1000 with attributes of color (red, black) and length (100, 200);
2 Create BOM, produce product 1000 (red, 100), BOM detail is black 200*1
3 This operation can be saved in odoo12
   But Tips in Odoo13:
**BoM line product A1000 should not be the same as BoM product.**
Current behavior:
Cannot be stored as Odoo12
Expected behavior:
It can be saved like Odoo12
Video/Screenshot link (optional):
ODOO12：
![图片](https://user-images.githubusercontent.com/6219061/69219563-13a4bd80-0bae-11ea-961d-18f2c3137b2e.png)
![图片](https://user-images.githubusercontent.com/6219061/69219578-199a9e80-0bae-11ea-86c7-104cb51812df.png)
ODOO13：
![图片](https://user-images.githubusercontent.com/6219061/69219609-26b78d80-0bae-11ea-9458-407217e653f1.png)

**Comment by pedrobaeza** [comment]
You can't put as a raw material the same as the final product, or you will create infinite recursion, so the message error is correct.

Closing as no issue, but expected behavior.

**Comment by mom988** [comment]
@pedrobaeza

**Comment by mom988** [comment]
product.tmpl A0001
product_id A0001_1 & A0001_2 in product.tmpl A0001
the final product : A0001_1 
raw material : A0001_2

**Comment by pedrobaeza** [comment]
Apart from the screenshots that are in foreign language, you don't have variants activated in that DB (or seems so).

**Comment by mom988** [comment]
![图片](https://user-images.githubusercontent.com/6219061/69228428-828a1280-0bbe-11ea-96b8-38fbac6aacc1.png)
![图片](https://user-images.githubusercontent.com/6219061/69228458-8f0e6b00-0bbe-11ea-9138-39f1b23f1c56.png)
![图片](https://user-images.githubusercontent.com/6219061/69228522-afd6c080-0bbe-11ea-917d-978985f9dad7.png)
![图片](https://user-images.githubusercontent.com/6219061/69228583-c8df7180-0bbe-11ea-8aed-19c693c5b440.png)

**Comment by pedrobaeza** [comment]
OK, now seems clearer. I reopen.

**Comment by pedrobaeza** [comment]
@amoyaux can you please take a look to this?

**Comment by mom988** [comment]
@amoyaux  can you please take a look to this?
If this is an improvement, I need to tweak the application or develop the code.
Thank you very much !
