### ISSUE TITLE
VAT number check failed for valid spanish VAT number starting with ESB

### ISSUE THREAD

**Issue by meyer-jan** [odoo/odoo#40554]
Impacted versions: Enterprise 12, 13

Steps to reproduce:
Use a VAT Number like ESB27471977 for partner VAT

Current behavior:
error message that VAT number is not valid against VAT number scheme

Expected behavior:
spanish VAT number ares validated against the valid scheme and you can use vat number for spain  starting with ESB

> Spanish EU VAT numbers have 11 characters [ES + 1 letter + 8 digits]. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/43740803/69236081-1645e980-0b93-11ea-848b-8adfdcd0ea34.png)

**Comment by pedrobaeza** [comment]
NIF has a control digit for avoiding incorrect ones, and yours is incorrect, as you can check for example in https://comunidadhorizontal.com/utiles/validar-cif-nif-nie/

Closing as no real issue.
