### ISSUE TITLE
[13.0] Missing product.price.history table

### ISSUE THREAD

**Issue by RodmanII** [odoo/odoo#40556]
Impacted versions: 13.0

Current behavior:
In odoo 13.0 the table product.price.history that used to contain the cost of product as result of its valuation method is gone and has been replaced with the stock valuation layer as mencioned in the commit

https://github.com/odoo/odoo/commit/0477bdb75afafa62b204f29e9dbfc3fc5fd012d4

the new table doesn't contain the same values, it doesnt have the cost of the product as a result of the valuation method, as it was the case for the field cost of product.price.history, the unit_cost field in stock.valuation.layer is just the value of the purchase divided by the quantity purchased, regardless of the valuation method. In short, I need to know the cost of a product in past dates, the cost according to the valuation method, in odoo 12 this is easy I just query product.price.history, but where can I get such data in odoo 13, or is not saved anywhere and I should do development to save it in my own table?.

**Comment by sle-odoo** [comment]
in practice this table was used to get the value at date in standard and avco, now we have the same results with the valuation layers so business wise this table didn't make sense anymore with the introduction of the layers.

now i don't really get what you want, your usecase doesn't concern fifo right? and if it concerns avco or standard, the unit_cost on the layers contains what you want. The only difference is that you need to have a layer (ie you nee a stock move), just editing in place the standard price won't create a layer (but it used to add an entry to the history price table).

is it clearer?

**Comment by RodmanII** [comment]
> in practice this table was used to get the value at date in standard and avco, now we have the same results with the valuation layers so business wise this table didn't make sense anymore with the introduction of the layers.
> 
> now i don't really get what you want, your usecase doesn't concern fifo right? and if it concerns avco or standard, the unit_cost on the layers contains what you want. The only difference is that you need to have a layer (ie you nee a stock move), just editing in place the standard price won't create a layer (but it used to add an entry to the history price table).
> 
> is it clearer?

**Comment by RodmanII** [comment]
> in practice this table was used to get the value at date in standard and avco, now we have the same results with the valuation layers so business wise this table didn't make sense anymore with the introduction of the layers.
> 
> now i don't really get what you want, your usecase doesn't concern fifo right? and if it concerns avco or standard, the unit_cost on the layers contains what you want. The only difference is that you need to have a layer (ie you nee a stock move), just editing in place the standard price won't create a layer (but it used to add an entry to the history price table).
> 
> is it clearer?

I think i got the impression the values werent the same because, after checking in both 12 and 13,
using average cost, in 12 the calculation is made with the value without taxes, while in 13, it uses
the value with taxes from the purchase, ¿Is this correct?, ¿Is this the normal behavior or could be due to misconfiguration?

Asuming is the correct behavior in 13, getting the cost as it was done in 12, it is posible?, theres a field/model containing the cost from value without taxes in 13, or is something that requires coding?

**Comment by sle-odoo** [comment]
>  in 12 the calculation is made with the value without taxes, while in 13, it uses
the value with taxes from the purchase, ¿Is this correct?, 

i don't think so, just made the test in v13 and v12 and the values are the same: without taxes. So you can use the valuation layer to get the standard price at date.

regards

**Comment by aqeebimtiaz-bista** [comment]
Just wanted to ask: is the `product.price.history` model changed or migrated to another model? 

I'm upgrading a Odoo 11 module to Odoo 14, stuck with this `product.price.history` issue.
