### ISSUE TITLE
[BUG] Server_id cannot prevent the creation of duplicate order

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#40567]
Impacted versions:
13
Steps to reproduce:

https://github.com/odoo/odoo/blob/cdc09f5b70ad200014ac38f314bf1ec53cd5b8ca/addons/point_of_sale/models/pos_order.py#L408-L428
 

https://github.com/odoo/odoo/blob/cdc09f5b70ad200014ac38f314bf1ec53cd5b8ca/addons/point_of_sale/static/src/js/models.js#L946-L957

Current behavior:

If the order is synchronized to the background process, the front end does not get the server_id due to the timeout, which causes the synchronization to fail.
  In fact, the order in the background has been synchronized successfully. 
 Since the front end fails to get the server_id, the order needs to be synchronized again, which will cause the background to generate duplicate orders.
 I think this way is wrong.
 The front-end order should generate a guid as the only token, and the background determines whether the order already exists according to the guid.  .

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@switch87 do you get the possible problem. I'm not able to see it.

**Comment by sum1201** [comment]
@pedrobaeza @switch87 
I set a breakpoint on the backend, pause the run, and the frontend waits for a timeout, and then the sync fails.  
At this point I continue to run the backend code, which will result in duplicate orders.

**Comment by pimodoo** [comment]
@sum1201 It looks you are right, because in 12.0, we were checking for the pos_reference to see if a pos_order, already exists or not, and now we are using the server_id which cannot work if the request had time out. I'll check fix this issue in 13.0

**Comment by sum1201** [comment]
It looks you are right, because in 12.0, we were checking for the pos_reference to see if a pos_order, already exists or not, and now we are using the server_id which cannot work if the request had time out. I'll check fix this issue in 13.0

**Comment by sum1201** [comment]
@pimodoo Thank you very much. I spent another month in another issue and I have not solved it. I hope this will be resolved as soon as possible.

**Comment by pimodoo** [comment]
@sum1201 Hello, your issue has been fixed in https://github.com/odoo/odoo/pull/40600
