### ISSUE TITLE
Translation 500 error

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#40572]
Impacted versions: 13

Steps to reproduce:
Having several languages installed on backend but not active on website seems to sometimes cause a 500 error from website.language_selector if you have profile set to language that is not installed on webpage.

Video/Screenshot link (optional):
![Skärmavbild 2019-11-20 kl  17 24 56](https://user-images.githubusercontent.com/13152668/69251864-bc591a00-0bba-11ea-8c9d-697807661ed0.png)

**Comment by mart-e** [comment]
Hello,

Could you give your configuration or languages and website? It looks like you have zero languages on the website which should not be possible.

**Comment by kimasplund** [comment]
On this one i created db in finnish then added swedish to backend but not to website.

**Comment by mart-e** [comment]
Thanks for the information, indeed I was able to reproduce it this way
@rdeodoo could you have a look? Visiting the website with the user in a language not present in the website languages crashes.

**Comment by kimasplund** [comment]
Seems someone else had same problem.

https://github.com/odoo/odoo/issues/40078

**Comment by rdeodoo** [comment]
Working on it.
Was introduced quite recently with https://github.com/odoo/odoo/commit/3408c4dd1eb197bdded6e87577ff71d7ffeca267
So basically before the mentioned commit, we would only try to find a nearest lang among the website ones but since this commit, we will check all the installed langs.

**Comment by wpdigital** [comment]
I've tried without installing any new language and website editor is not working.

The error appears after installing clean Odoo instance with only one Website app installed.

Traceback:
Error: QWeb2: Template 'website.editorbar' not found

Odoo 13.0-20191115 (Community Edition)
