### ISSUE TITLE
[12.0] helpdesk: Customer message arrives as an internal ticket note

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#40591]
Impacted versions:
v12.0

Steps to reproduce:
- Configure incoming, outgoing mail servers
- Configure a support team on helpdesk app
- From a Customer email, send an email to the support team email alias
- Once ticket is created and received the automatic ack mail send a second mail
![image](https://user-images.githubusercontent.com/10233975/69273299-bacd2900-0b9d-11ea-8b4a-f69f6d0ada06.png)

Current behavior:

- On the created ticket we notice that the second message after the ack mail was received, was registered as an internal note instead of normal messages that notify all followers.

![image](https://user-images.githubusercontent.com/10233975/69273610-45ae2380-0b9e-11ea-84bb-f349aca62de6.png)

This is because customer kept responding from the ack mail that he received, the bug is not present when he answer from the internal user messages 
![image](https://user-images.githubusercontent.com/10233975/69274021-1ba93100-0b9f-11ea-87e2-b46ceeab8774.png)

**We** can't control from which mail thread customer will respond
So this leads that some mails be ignored since there are any notification because mail from customer registered as an internal note

Expected behavior:
Every message from the customer must no be registered as an internal note.

Video/Screenshot link (optional):
replicated at 
http://694653-12-0-fa5722.runbot22.odoo.com/

### OPW 2127778

**Comment by pedrobaeza** [comment]
Has this been handled by OPW?

**Comment by hugho-ad** [comment]
yes, let keep it open

![image](https://user-images.githubusercontent.com/10233975/78457414-3fa97280-7667-11ea-86c1-94d7df1154b3.png)

**Comment by Yenthe666** [comment]
Actually, it has no point to keep these open if Odoo says there is a feedback at Odoo now and no change is coming in the stable versions. I vote for a close, do you agree @pedrobaeza?

**Comment by pedrobaeza** [comment]
Yes, and more being enterprise, so closing. Thanks all for the feedback.

**Comment by guewen** [comment]
Isn't a subtype note supposed to be internal? This is so inconsistent to have exchanges with a customer as notes...
I'm sure there would have been a cleaner way to limit the emails sent to assigned users. :sob: 
Actually, the answer is partial and there is a bug IMO:

> Making this change would result in a lot of automated emails to be sent by your server to automatically assigned user and user assigned at creation of the tickets (even for tickets created manually).

Ok, but it doesn't explain why the *answers of the customers* are classified as Notes too.
I'll report this as a new OPW. The problem with the current implementation is, if you want some code / automated action to change the state if you receive an response (!= note), you can't know if it is a real note that shouldn't change the stage or an answer from the customer tagged as note.

**Comment by pedrobaeza** [comment]
As this is something enterprise, you can open an OPW about your points.
