### ISSUE TITLE
Qweb template and translation: Some translatable terms not detected

### ISSUE THREAD

**Issue by sebastienhasa** [odoo/odoo#40603]
Impacted versions:
Odoo 11.0-20190128 (Community Edition) 

Steps to reproduce:
- Create a Qweb template to be used with core.qweb JS module
- Inside this Qweb template, add some 1 char short terms
- Use this template from a website page by loading it from JS code,
  like described here:
  https://www.odoo.com/documentation/11.0/reference/javascript_reference.html
- Generate translatable terms from "Settings" -> "Translations" ->
  "Application Term" -> "Generate Missing Terms"

Current behaviour:
Some short terms, like "à", are (some times) not detected

Expected behaviour:
All translatable terms detected

**Comment by sebastienhasa** [comment]
I also tried to manually create a translation for my short term. 

I take another term, one who is detected as translatable and near my
short term, and I copy its record on the table "ir_translation". Of
course, I adapted its fields to correspond to the missing translation
term.

But, the term are still not translated on the web page. 

However, if I look at the network calls from the frontend, and more
specifically at the call to "/website/translations", I can see that
the JS code receive à JSON with my short term translated in it. Maybe
we got another problem with translations loading in the Qweb engine in
JS.

**Comment by pedrobaeza** [comment]
I don't think it's the short term, but not being enclosed in a proper tag. Can you include the template or try with a longer word as is to see if it's translatable in that case?

**Comment by sebastienhasa** [comment]
This is an extract of the template, the part that have problem:
```xml
<t t-if="widget.placeName">
    à
    <select id="radius-dropdown" class="select2">
        <t t-call="partner_list_viewer.select_radius_options">
            <t t-set="mapRadiusOptions" t-value="widget.mapRadiusOptions"/>
            <t t-set="mapRadius" t-value="widget.mapRadius"/>
        </t>
    </select>
    de
    <span class="search-place" t-esc="widget.placeName"/>
</t>
```

The short term not translated is "à".

I tried to replace the "à" with "a", but it didn't fix my problem.

But, if I replace the "à" with, for example, "banana", the term is
detected as translatable. And if I translate it, its translation is
shown on the final web page. So, apparently, the problem is the
translatable terms detection on 1 char short terms.

**Comment by pedrobaeza** [comment]
You have to wrap the term around a `<span>` element.

**Comment by sebastienhasa** [comment]
@pedrobaeza : Tried, didn't work

**Comment by pedrobaeza** [comment]
@mart-e can you help here?

**Comment by mart-e** [comment]
Unfortunately it is expected to skip the small terms, we only keep a few hardcoded ones as listed there

https://github.com/odoo/odoo/blob/b96e9e895b85c91b459df640306b3c33b3b6e331/odoo/tools/translate.py#L119-L120

but even that, it is not great as translating small words is usually not practical and out of context. In addition, it won't work in many languages (where the order of the words is different).

The best is to restructure your content generation to avoid to have small words like this.
