### ISSUE TITLE
Alignment for the two fields 'Name' and 'Active' is not proper on the Sequences form view

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#4063]
Steps to follow 

(1) Login with the admin user and make sure he / she has the technical features of the database

(2) Go to menu Settings -> Technical -> Sequences & Identifiers -> Sequences

(3) Try to create new sequence see the below link 
     https://docs.google.com/file/d/0B5j41T1Hqv1sSHJIWElld1FfWW8/edit?usp=drivesdk

(4) This alignment is only not proper when the multicompany group is not on , if the user tick the multicompany group and then follow the same above mentioned steps than the new company field is added in the form view and every thing looks proper , but for all other users who are not following multicompany group will see those fields not properly aligned.

**Comment by Yenthe666** [comment]
Hi @jni-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
