### ISSUE TITLE
readonly doesn't work on priority widget

### ISSUE THREAD

**Issue by jeroen7s** [odoo/odoo#40641]
Impacted versions: 
13.0

Steps to reproduce:
add priority widget to field on tree or form view
set readonly flag to True or 1

Current behavior:
Hovering over the widget highlights stars
Clicking on the widget makes it look like the priority has changed
*stars stay highlighted after moving away
*refreshing browser resets the stars back to normal

Expected behavior:
Hovering over priority widget doesn't highlight the stars when in readonly mode.
Clicking on stars doesn't change them.

**Comment by jeroen7s** [comment]
@pedrobaeza You might also want to add the 13.0 label to this, as that is the version I've used. But the 11.0 and 12.0 probably have the same issue.

**Comment by pedrobaeza** [comment]
Yeah, bad label assigning

**Comment by msh-odoo** [comment]
Should be fixed with #57732

**Comment by msh-odoo** [comment]
@jeroen7s  @pedrobaeza  The PR linked here is merged in 13.0, we can close this issue now.

**Comment by pedrobaeza** [comment]
Thank you very much.

**Comment by jatinduracube** [comment]
@Yenthe666 @jeroenev 
I am using ODOO 14 and widget priority ignores the attribute readonly

Any solution for ODOO 14 please let me know 

Thanks

**Comment by jeroenev** [comment]
@jatinduracube Figured out that using `readonly="1"` works, but `attrs="{'readonly': ...}"` doesn't
so you can add 2 fields, 1 with `readonly="1"` and 1 without, and then use `attrs="{'invisible':...}"` to make one or the other visible conditionally
