### ISSUE TITLE
Cant use context to pass data from many2one fields to name_get

### ISSUE THREAD

**Issue by jorgebarcelo** [odoo/odoo#4067]
For a project im working on i need to set a form view with a one2many field, having a many2one field inside the tree view (editable), and that many2one field need to show a specific field of the related model.

First i tried a related field. But the field dont update correctly while edditing the tree view.
Then i tried using the _reg_name in the model. This gives the perfect result in my view, but this change all the views.....wich makes this solution refused.

Finally i work with name_get function and use the context, but sadly i found that context are not correctly pass to the name_get function. After some debug i found the problem on js, where the context param is not used.

I dont know if this is bug, or purposely blocked.

Line in question:
https://github.com/odoo/odoo/blob/8.0/addons/web/static/src/js/view_list.js#L1094

**Comment by Yenthe666** [comment]
Hi @jorgebarcelo,

Thank you for your report but the Github bug tracker is only for bugs in the official code. It is not used for asking question/help.
Please don't hesitate to ask these kind of questions on the official help forum at help.odoo.com

Regards,
Yenthe
