### ISSUE TITLE
Invoice report breaking number with space as a thousand separator, and tax showing nbsp.

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#40673]
From our country numbers have spaces, in Odoo reports when the invoice have spaces it break the line in the numbers.  So to overcame this issue, we added in the language as a thousand separator the  **`&nbsp;`** This solved the problem for all number except for the tax resume that show the nbsp. this is due to the fact that its treating as char.

Impacted versions:
12.0
Steps to reproduce:
In Settings language, set thousand separator to &nbsp;
Current behavior:
In the invoice report  the resume value before the Total is not formatted to a number
Expected behavior:
If taxes would be presented as normal Monetary it would be possible to render the nbsp as expected,
Video/Screenshot link (optional):
![imagem](https://user-images.githubusercontent.com/10322162/69409015-6d20ff80-0d08-11ea-8ac3-cf66b7eb4703.png)

![imagem](https://user-images.githubusercontent.com/10322162/69408826-ff74d380-0d07-11ea-8d9a-6d1f6201c199.png)

**Comment by pedrobaeza** [comment]
`&nbsp;` is not a proper thousand separator. That's why this is not working. So I don't consider this an Odoo issue, as you try to hack the system and it doesn't work.

Any way, I let @mart-e the final decision on this.

**Comment by mart-e** [comment]
Why not add "` `", `chr(160)`) as thousand separator (not to be confused with "` `", `chr(32)`)?
This is what we do for the French language and it works pretty well.

**Comment by aliencrash** [comment]
> Why not add "` `", `chr(160)` as thousand separator (not to be confused with "` `", `chr(32)`)?
> This is what we do for the French language and it works pretty well.

Because it will break like this (look to the unit price)
![imagem](https://user-images.githubusercontent.com/10322162/69411461-5204be80-0d0d-11ea-97d3-8b5245b25391.png)

**Comment by aliencrash** [comment]
I Was able to use the char(160) after lot of trails, and it's working.

**Comment by mart-e** [comment]
Indeed, in your picture above you were using a regular space because the same example with a nbsp works fine.
