### ISSUE TITLE
[Odoo 13] Can not install website theme

### ISSUE THREAD

**Issue by physiii** [odoo/odoo#40746]
Following instructions [here](https://www.odoo.com/documentation/13.0/howtos/themes.html).

First I download a new [theme](https://apps.odoo.com/apps/themes/13.0/theme_kea/) and extract theme_ folders into the addons directory.

I navigate to the Website module and go to Configuration > Settings > Chooose a theme.

However the theme I put in addons folder does not appear even after restarting odoo.

![image](https://user-images.githubusercontent.com/6277642/69480086-d74da900-0dc9-11ea-8782-63e92719ee24.png)

Seems straightforward, what am I missing?

**Comment by sswapnesh** [comment]
You have to Update your app list
![screenshot-699344-13-0-b115bc runbot14 odoo com-2019 11 23-22_29_47](https://user-images.githubusercontent.com/16624719/69482399-cdb35800-0e40-11ea-936c-01c298ccc3e8.png)

![screenshot-699344-13-0-b115bc runbot14 odoo com-2019 11 23-22_30_21](https://user-images.githubusercontent.com/16624719/69482408-e0c62800-0e40-11ea-90b8-6aff591071f9.png)

**Comment by Yenthe666** [comment]
Hi there,

The issue tracker is for issues in Odoo itself, this is not the right place to ask questions about custom development or features you don't know.
You can ask these kind of questions on the official help forums at https://www.odoo.com/forum/help-1 (and @sswapnesh has answered it anyways).

Regards,
Yenthe
