### ISSUE TITLE
[V13] Purchase: Adding a note or section to Purchase order gives error (Forbidden values on non-accountable purchase order line)

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#40741]
Impacted versions: 13 Purchase

Steps to reproduce:
- Install only purchase application, no stock application
- Add Product and a note or section to a Purchase order
![image](https://user-images.githubusercontent.com/39414107/69463975-5ec0fb00-0d7d-11ea-97d2-0dd72a29df4a.png)

- Save the Purchase Order
- Edit the Purchase Order and change the **"Receipt date"** in the Other information tab.
![image](https://user-images.githubusercontent.com/39414107/69464035-86b05e80-0d7d-11ea-8fd6-56b095de375a.png)
- Save and get error: _Forbidden values on non-accountable purchase order line_

Current behavior: Get an error when changing the receipt date of an RFQ that has a section or note.

Expected behavior: That I can set the receipt date directly for all products at once using the "receipt date" in the Other information tab. The receipt date update does not check the type of purchase order line?

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@amoyaux can you take a look to this?

**Comment by BusinessAgilityMasters** [comment]
Great, thanks, seems to work 👍
