### ISSUE TITLE
[12.0] A template id is not correct

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#40753]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

This template ID (search count) is not correct. I think for id, underline must be used not space, like this "search_count"

File address: addons/website_sale/views/templates.xml

Video/Screenshot link (optional):
![Screenshot from 2019-11-24 11-17-04](https://user-images.githubusercontent.com/51145639/69491606-a4c8ac80-0eac-11ea-92e8-f7a2d4de986b.jpg)

**Comment by Yenthe666** [comment]
A PR is welcome for the master version ;)

**Comment by pedrobaeza** [comment]
External identifiers (XML-ID) can be any string, including spaces, but it's true that if it corresponds to a data that can be translatable (which is not the case, as this a QWeb template), it would be converted untranslatable. As said by @Yenthe666, it's good that this is avoided, but only for master version, as in stable branch this change can break inherited behaviors in third-party modules.

Closing this as non issue at all, but something preferable.

**Comment by Yenthe666** [comment]
It has been fixed in V13 actually:
https://github.com/odoo/odoo/blob/91551ae962cadc9dc258e5ffdafe5d6100b780c7/addons/website_sale/views/templates.xml#L119-L123
so nothing to do here.

**Comment by pedrobaeza** [comment]
OK, I suppose they have decided is too soon for someone to have inherited that template yet.
