### ISSUE TITLE
v13 Inventory

### ISSUE THREAD

**Issue by MindaugasPaul** [odoo/odoo#40798]
Impacted versions:13

Steps to reproduce:
multi warehouse (1 warehouse and 2 warehouse). multi location. product tracked by lot.
you receive "product A" to 1 warehouse 2qty ("LOT1").
So we have in 1 warehouse product A LOT1 2 qty.
We create internal transfer. source location (1 warehouse), destination location (2 warehouse) - we put product A. we have no possibility to check availability, only enter 'done' quantities. so we enter(e.g. by mistake 4 qty). validate (other options where is no in version 13).

Current behavior:
we have -2wty with lot and value in 1 warehouse. and we have 4 qty in 2 warehouse.

Expected behavior:
we need to check is it available and transfer only qty what is available and not reserved(this worked correct inversion 12).

Video/Screenshot link (optional):
[13v inventory bug-internal transfer.docx](https://github.com/odoo/odoo/files/3887163/13v.inventory.bug-internal.transfer.docx)

**Comment by MindaugasPaul** [comment]
on odoo sh, runbot, local version 13 (no custom modules).

**Comment by sle-odoo** [comment]
when creating your internal transfer, use a "planned transfer" 

<img width="839" alt="Screenshot 2019-11-25 at 16 07 43" src="https://user-images.githubusercontent.com/7601090/69551909-cc4b7200-0f9d-11ea-8d7a-c761ef4d512d.png">

**Comment by MindaugasPaul** [comment]
you closed it, but you making print screen from delivery order (operation type).
<img width="905" alt="444" src="https://user-images.githubusercontent.com/49023902/69552891-e7bb7a80-0fa7-11ea-9b42-45fb7cf61073.png">
and you will receive the same behaviuor. why you close if problem really still is?!

**Comment by MindaugasPaul** [comment]
and all normal(regular) users-for e.g. in company is 50users of odoo. So do not go to internal->create->because you will make mistake is not bug?
