### ISSUE TITLE
[8.0] Delivery cost tranfert to invoice grouped from stock_picking

### ISSUE THREAD

**Issue by zuher83** [odoo/odoo#4080]
The tranfer from "stock_picking" cost delivery of the module "delivery" isn't logical if I want create grouped invoices from pickings.

Example (actualy)

Picking 1 

```
Product one
Product two
Cost delivery
```

Picking 2

```
Product one
Product two
Cost delivery
```

Result in invoice grouped:

```
Product one (from Picking 1 )
Product two (from Picking 1 )

Product one (from Picking 2 )
Product two (from Picking 2 )
Cost delivery -> one line for delivery cost
```

I instead suggests to integrate with method "_invoice_create_line"

Result in invoice grouped with _invoice_create_line methode:

```
Product one (from Picking 1 )
Product two (from Picking 1 )
Cost delivery -> (from Picking 1 )

Product one (from Picking 2 )
Product two (from Picking 2 )
Cost delivery -> (from Picking 2 )
```

If I am wrong tell me

**Comment by Yenthe666** [comment]
Hi @zuher83,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
