### ISSUE TITLE
[11.0] Payment error not translate in website

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#40826]
**Impacted versions:**
11.0
**Steps to reproduce:**
1. Load a language other than English.
2. Select the downloaded language.
3. Add product to cart
3. Perform payment process, but do not select any payment method.
4. The error is displayed, but it is not translated into the selected language, even if the translation is done.

**Current Behavior:**
The error message is not translate
**Expected Behavior:**
The error message in the client's language

**Video link / screenshot (optional):**
https://youtu.be/cSsxEPEvx4Y

**Comment by pedrobaeza** [comment]
@JKE-be can you please take a look?

**Comment by mart-e** [comment]
I believe fixed at #40896
