### ISSUE TITLE
[Bug] Account Voucher: Adjustment/Reconciling logic is incorrect

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#4082]
I found a bug in the voucher logic... let me explain my scenario how I came across that issue..

Customer A made a advance payment  of INR 1500/-
Then a Invoice (Inv-01) of amount INR 1510/-

Now in the "Customer Payments" Screen when I selected the Customer A,
Credits(Invoice) will be 1510 and 
Debits(Payment) will be 1500, hence, Invoice (Inv-01) is partially reconciled with 1500 

Again same Customer A makes a second Advance payment of INR 3300/-
then a Invoice (Inv-02)  of amount INR 2000/-

Now I try to reconcile payments for that Customer A
In Credits allocation amount will be 2010  - i.e. 10 (balance of Inv-001) plus 2000 (Inv-02)
In Debits allocation  amount will be 3300 - i.e. payment  amount with reconcile flag set to true

So If you see the above reconciling voucher entry, it is trying to allocate 2010 (credits) with 3300 (debit) which is incorrect...

When I traced the logic I realized, while reconciling the amount, they have considered original amount of Inv-001 rather than considering the residual balance...

In Credit (tree), allocation and open balance are calculated correctly, but internally "total_debit" / "total_credit" variable which are used for summing up the amount and allocating are incorrect... instead of using amount_residual, they have used the original amounts

![voucher_reconcile](https://cloud.githubusercontent.com/assets/8802906/5330354/765633d4-7e12-11e4-9575-40afbaa2d2d1.png)

**Comment by Yenthe666** [comment]
Hi @deepa4lok,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
