### ISSUE TITLE
ODOO 13.0 - "Transient module states were reset" error on restart

### ISSUE THREAD

**Issue by zazula** [odoo/odoo#40832]
I'm new to ODOO but an experienced computer-type.  I'm installing from the Docker images and simply trying to run and restart the service using default configurations.   It's not working and I can't seem to figure out what is going on.  Note that the app seems fine if I simply install and run it but it goes downhill (see attached) if I restart it.  No exported volumes, no custom modules, just stock ODOO 13.

I've attached my Docker script and the output of a start/restart/restart sequence with no user interaction in between.

Impacted versions:
13 - latest

Steps to reproduce:
Install basic ODOO setup in Docker
Start ODOO
Stop ODOO
Start ODOO

Current behavior:
Many errors and CRITICAL messages

Expected behavior:
It just works

Video/Screenshot link (optional):
[docker.txt](https://github.com/odoo/odoo/files/3889173/docker.txt)
[odoo.txt](https://github.com/odoo/odoo/files/3889174/odoo.txt)

**Comment by zazula** [comment]
Note, I repeated the process on a completely different machine and received the same errors.

Installing Odoo 12 works fine, so maybe it is something with the latest rev of 13.

**Comment by zazula** [comment]
Installing 13 from the Dockerfile also produces:

2019-11-26 02:53:30,300 1 CRITICAL odoo-khome odoo.service.server: Failed to initialize database `odoo-khome`. 

when restarting the application.

**Comment by pedrobaeza** [comment]
It seems you are installing over a previous DB installation and some data overlaps. Please check with latest code and it not, please put the issue in Docker project (odoo/docker), not here.

**Comment by zazula** [comment]
It appears that the --init and --update flags can only be run once for a given database.  This is not clear from the docs located here:

https://www.odoo.com/documentation/11.0/reference/cmdline.html

The problem is that my Docker container included the --init flag and so the modules were being newly installed each time.  

I wanted to install a long list of modules during the setup process rather than through the UI.
