### ISSUE TITLE
[13.0] error when activating terms&conditions e-commerce 

### ISSUE THREAD

**Issue by tsteenbergen96** [odoo/odoo#40858]
Impacted versions:
Odoo 13
Steps to reproduce:
- login as admin or employee
- add something to basket
- go to checkout
- select the option "accept terms&conditions" ((that means that customer has to accept the conditions before he can is able to pay the order". The company could disable this option so customer does not have to accept the terms but I prefer to have it.)
- error occurs every time when customer or admin goes to checkout

Video/Screenshot link (optional):

<img width="832" alt="Schermafbeelding 2019-11-26 om 12 10 22" src="https://user-images.githubusercontent.com/54263300/69625207-6666f500-1046-11ea-8a3a-bc77238ef1f2.png">
<img width="372" alt="da96S" src="https://user-images.githubusercontent.com/54263300/69625208-66ff8b80-1046-11ea-8a97-1c10bfa89867.png">

**Comment by Yenthe666** [comment]
@tsteenbergen96 please update your Odoo instance. This has been fixed recently in https://github.com/odoo/odoo/commit/2741f3d9ab7833e3d777d87206537eca6894ef79
