### ISSUE TITLE
Duplicate Reconcile boolean in Chart of Accounts

### ISSUE THREAD

**Issue by pooja-zakhariya** [odoo/odoo#40881]
Impacted versions:
Odoo enterprise 13

Steps to reproduce:
Install account_accountant module

Current behavior:
Reconcile checkbox appearing two times

Expected behavior:
It should appear only once

The reason could be same code is in two views: account.view_account_form and account_accountant.view_account_form

![duplicate_reconcile](https://user-images.githubusercontent.com/4104012/69637637-0f314680-107f-11ea-97f7-e82a01fb7f2f.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @pooja-zakhariya,

Thanks a lot for your report. I've just tested this on the latest Odoo 13.0 instance but I can no longer reproduce it. See the screenshot:
![image](https://user-images.githubusercontent.com/6352350/70392740-7fc35600-19e3-11ea-8066-ed8256e099d0.png)

Could you test this on the latest Odoo 13.0 test instance at runbot.odoo.com and let us know if the issue is still reproducable please?

Regards,
Yenthe

**Comment by pooja-zakhariya** [comment]
Hello Yenthe,

I just checked with recent pull this view has been removed from account_accountant module.
-    <record id="view_account_form" model="ir.ui.view">
-        <field name="name">account.account.form</field>
-        <field name="model">account.account</field>
-        <field name="inherit_id" ref="account.view_account_form"/>
-        <field name="arch" type="xml">
-            <field name="internal_group" position="after">
-                <label for="reconcile" attrs="{'invisible': ['|', ('internal_type','=','liquidity'), ('internal_group', '=', 'off_balance')]}"/>
-                <div attrs="{'invisible': ['|', ('internal_type','=','liquidity'), ('internal_group', '=', 'off_balance')]}">
-                   <field name="reconcile"/>
-                   <button name="action_open_reconcile" class="oe_link" type="object" string=" -> Reconcile" attrs="{'invisible': [('reconcile', '=', False)]}"/>
-                </div>
-            </field>
-        </field>
-    </record>

Thanks for the update.

**Comment by Yenthe666** [comment]
Alright then we can consider this one solved :) thanks!
