### ISSUE TITLE
[8.0] Portal registration email body translation concatenating in single line

### ISSUE THREAD

**Issue by dragomireckijj** [odoo/odoo#4092]
Despite that `/addons/portal/wizard/portal_wizard.py` declares email message body as multi-line triple quoted string constant, new portal users recieving translated (utf8, ru) message as single line without breaks.

Don't know if `openerp.tools.translate` can deal with triple quoted strings and I don't have enough skills to check this. Instead, I would like to use "Email Templates" setting to configure title, body and their translations for this type of messages (as I do with new user template, meeting reminder, ...). 

Here is what I've got in related .po file:

````
#. module: portal
#: code:addons/portal/wizard/portal_wizard.py:34
#, python-format
msgid ""
"Dear %(name)s,\n"
"\n"
"You have been given access to %(company)s's %(portal)s.\n"
"\n"
"Your login account data is:\n"
"  Username: %(login)s\n"
"  Portal: %(portal_url)s\n"
"  Database: %(db)s \n"
"\n"
"You can set or change your password via the following url:\n"
"   %(signup_url)s\n"
"\n"
"%(welcome_message)s\n"
"\n"
"--\n"
"Odoo - Open Source Business Applications\n"
"http://www.openerp.com\n"
msgstr ""
"Здравствуйте, %(name)s,\n"
"\n"
"Компания %(company)s предоставила Вам доступ к клинтскому порталу "
"%(portal)s.\n"
"\n"
"Данные Вашей учетной записи:\n"
"  Имя пользователя: %(login)s\n"
"  Портал: %(portal_url)s\n"
"  База: %(db)s \n"
"\n"
"Вы можете установить или поменять свой пароль по следующей ссылке:\n"
"   %(signup_url)s\n"
"\n"
"%(welcome_message)s\n"
"\n"
"--\n"
"Odoo - приложения с открытым кодом для бизнеса\n"
"http://www.odoo.com\n"
````

**Comment by mart-e** [comment]
Hello,

It was fixed in 7.0 at 96d1520a5e7c402669e812dd9a5f7fc3f35eb284. Will be in 8.0 soon.
