### ISSUE TITLE
[8.0] Printing Sales Pricelist from Product Variants does not show full list of Pricelists

### ISSUE THREAD

**Issue by jookeng** [odoo/odoo#4095]
**Printing Sales Pricelist from Product Variants does not show full list of Pricelists**

Impacted versions:
- 8.0

Steps to reproduce:
1. Navigate to Sales > Products > Product Variants
2. Change to list view and select a product
3. Click on Print > Price List
4. Select the PriceList dropdown

Current behavior:
- Only the top 99 pricelists are returned

Expected behavior:
- All available pricelists returned

**Comment by gigidn** [comment]
Any news on this issue?

**Comment by agusddt** [comment]
Hi, any news?

**Comment by Yenthe666** [comment]
Hi @jookeng,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
