### ISSUE TITLE
[13.0] Wrong lot wise inventory Valuation with Costing Method : FIFO and Inventory Valuation : Automated

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#40987]
Impacted version: 13.0

Make a new product with inventory Valuation with Costing Method: FIFO and Inventory Valuation: Automated.

Makes purchase order with qty 1 price 10. and received it in lot: 001.

Makes second purchase order with qty 1 price 20. and received it in the same lot: 001.

The inventory report should show two lines with the exact lot with correct pricing. 

Currently, it shows an average price of 15 in line which is wrong. Its should show lot wise two lines.

<img width="1680" alt="Screenshot 2019-11-27 at 11 16 43 PM" src="https://user-images.githubusercontent.com/7733043/69747299-20a44c80-116c-11ea-8c38-b7be8a2d4038.png">
<img width="1680" alt="Screenshot 2019-11-27 at 11 17 26 PM" src="https://user-images.githubusercontent.com/7733043/69747301-20a44c80-116c-11ea-8a82-99af97e202ee.png">

link: http://705734-13-0-903e8f.runbot24.odoo.com/web?debug=#action=990&model=stock.valuation.layer&view_type=list&cids=&menu_id=259

**Comment by bhaveshselarka** [comment]
@pedrobaeza @nim-odoo

**Comment by bhaveshselarka** [comment]
<img width="1680" alt="Screenshot 2019-11-27 at 11 28 51 PM" src="https://user-images.githubusercontent.com/7733043/69748166-c2786900-116d-11ea-836b-e89ce64f440f.png">
<img width="1680" alt="Screenshot 2019-11-27 at 11 29 01 PM" src="https://user-images.githubusercontent.com/7733043/69748168-c310ff80-116d-11ea-94aa-51cc588cf3bd.png">
<img width="1680" alt="Screenshot 2019-11-27 at 11 29 07 PM" src="https://user-images.githubusercontent.com/7733043/69748170-c310ff80-116d-11ea-8eb7-b9c63b51da23.png">
<img width="1680" alt="Screenshot 2019-11-27 at 11 29 13 PM" src="https://user-images.githubusercontent.com/7733043/69748171-c310ff80-116d-11ea-8dec-cc3aa8a45a09.png">

**Comment by sle-odoo** [comment]
Hi,
We implement the financial fifo cost method, what you describe is the individual costing cost method.

The value in your original post is [an estimation](c861edefaa0009ba214d79a53376c85ab9f45991).

Regards

**Comment by sswapnesh** [comment]
@sle-odoo  Seems typo on the link

**Comment by bhaveshselarka** [comment]
Hi @sle-odoo ,

Thanks for sharing information but its average cost. 

Can you please explain how can we get the different real prices we have received material on different times with the same lot number.

Here what current behaviour is its merge them by lot no matter at a time it's received plus whats the cost of it.

its simply makes the merge line and do the average of the lot. Which completely wrong. By this case, we never get the real price of lot.

**Comment by sle-odoo** [comment]
@bhaveshselarka so what you clearly want here is the indivual cost method (explained [here](https://courses.lumenlearning.com/boundless-accounting/chapter/valuing-inventory/) as "specific identification": with this cost method, you would to able to know exactly the value of each serial number. 

The caveat is that to use this cost method, you have to be able to justify how you chose the value on your serial, ie prove the complete traceability of your product. Most companies aren't able to do that and that's why we implement the financial fifo cost method, which is more used and more flexible (end of year: your valuation is your last vendor bills).

If you really want the individual costing i advise you to make a custom development.

> Can you please explain how can we get the different real prices we have received material on different times with the same lot number.

it seems here you only want the account moves linked to the receipt though.

Regards

**Comment by agavariat** [comment]
> Versión afectada: 13.0
> 
> Haga un nuevo producto con valoración de inventario con método de costeo: FIFO y valoración de inventario: automatizado.
> 
> Hace un pedido de compra con la cantidad 1 precio 10. y lo recibió en lote: 001.
> 
> Realiza el segundo pedido de compra con la cantidad 1 precio 20. y lo recibió en el mismo lote: 001.
> 
> El informe de inventario debe mostrar dos líneas con el lote exacto con el precio correcto.
> 
> Actualmente, muestra un precio promedio de 15 en línea que está mal. Debe mostrar mucho dos líneas sabias.
> 
> <img alt="Captura de pantalla 2019-11-27 a las 11 16 43 PM" width="1680" src="https://user-images.githubusercontent.com/7733043/69747299-20a44c80-116c-11ea-8c38-b7be8a2d4038.png">
> 
> <img alt="Captura de pantalla 2019-11-27 a las 11 17 26 PM" width="1680" src="https://user-images.githubusercontent.com/7733043/69747301-20a44c80-116c-11ea-8a82-99af97e202ee.png">
> 
> enlace: http://705734-13-0-903e8f.runbot24.odoo.com/web?debug=#action=990&model=stock.valuation.layer&view_type=list&cids=&menu_id=259


solve?
