### ISSUE TITLE
[13.0] customized context will be overridden for variant

### ISSUE THREAD

**Issue by lilee115** [odoo/odoo#40995]
/website_sale_stock/controllers/variant.py
`kw['context'] = {'website_sale_stock_get_quantity': True}`
will override other custom context in another customizing module
[FIX:]
```python
class WebsiteSaleStockVariantController(WebsiteSaleVariantController):
    @http.route()
    def get_combination_info_website(self, product_template_id, product_id, combination, add_qty, **kw):
        if 'context' in kw:
            kw['context']['website_sale_stock_get_quantity']=True
        else:
            kw['context'] = {'website_sale_stock_get_quantity': True}
        return super(WebsiteSaleStockVariantController, self).get_combination_info_website(product_template_id, product_id, combination, add_qty, **kw)
```

**Comment by pedrobaeza** [comment]
Can you please propose the PR with that change?

**Comment by lilee115** [comment]
never did any PR in Github yet... but sure, will have a try

**Comment by lilee115** [comment]
> Can you please propose the PR with that change?

A couple of days ago I have proposed a PR with this change, will it be merged? @pedrobaeza

**Comment by pedrobaeza** [comment]
It doesn't depend on me. I'm not an Odoo employee. I only give a hand handling issue tracker.
