### ISSUE TITLE
[13]Adding Section in Quote, Invoice fail to generated 

### ISSUE THREAD

**Issue by binueda** [odoo/odoo#41009]
Impacted versions: 13

Steps to reproduce:
New Quote
Add Section -->  provide a name 
Add  products for quote and save
Confirm sale
Generate invoice 
invoice fail -- "Forbidden unit price, account and quantity on non-accountable invoice line"

Current behavior:
invoice fail -- "Forbidden unit price, account and quantity on non-accountable invoice line"
Expected behavior:
Invoice should be created with the Section 

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/22423777/69788530-bda2cc00-11e4-11ea-901d-dbd54e550d1a.png)

**Comment by pedrobaeza** [comment]
You must update your code, as it seems outdated. I have been able to do invoice a SO with sections:

![Selección_009](https://user-images.githubusercontent.com/7165771/69814728-1d08d800-11f5-11ea-83c4-858fe5a9f51b.png)

Closing meanwhile you don't provide more info if still reproducible.

**Comment by T2BE** [comment]
This is the fix : https://github.com/odoo/odoo/commit/e2742abdfd4b59e0a9f863bbf3f2d7e664e9dad3#diff-dd671a54296b170ea1393dca1a5f7798
