### ISSUE TITLE
attachment_indexation not work

### ISSUE THREAD

**Issue by 159820** [odoo/odoo#41002]
Impacted versions:
13
Steps to reproduce:
1: install attachment_indexation module
2: open one product, no 'ATTACHMENT'  button in use interface
Current behavior:
no 'ATTACHMENT'  button in use interface

Expected behavior:
should have a button fo use to upload attachment.
this function works well in version 12.
i checked directory : /odoo-server/addons/attachment_indexation
seems no view defined in this module.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This module is not for that, it's for attachment indexation!!

Attachments are handled from the chatter.

Closing as no issue.
