### ISSUE TITLE
[website_forum] Small design consideration / User exeperience 

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#4106]
I would like to request a small change in the order of command links in the forum software.  

First let me confess that I am a habitual editor of posts in the forum.  I will even confess that I sometimes make minor grammatical edits to the questions of non-English posters when their questions are not intelligible and it is doubtful that they will get any help (since their question is too difficult to understand).  

My request is that you swap the **Close** and **Edit** links in the question portion of the forum.  The software has conditioned me to know that **Edit** is the second option on the answer portion so when I click the second option on the question portion I am asked to **Close** the thread.

![forum](https://cloud.githubusercontent.com/assets/8161873/5339467/fe0152f2-7ebf-11e4-8a86-b514289d862b.jpg)

In the grand scheme of things this is a minor irritation but it is also something easily resolved in code.

**Comment by tde-banana-odoo** [comment]
I took it into consideration in a small usability improvements commit in master (see 7a10df6e565d2e2b4f5bf617a4f7f5b489061c97).

**Comment by smack815** [comment]
My **ARD** [Anal Retentive Disorder](http://en.wikipedia.org/wiki/Anal_retentiveness) thanks you. !(http://themeforest.net/images/smileys/nerdy.png)

**Comment by smack815** [comment]
@tde-banana-odoo My **ARD** [Anal Retentive Disorder](http://en.wikipedia.org/wiki/Anal_retentiveness) thanks you. ![nerd](http://themeforest.net/images/smileys/nerdy.png)
