### ISSUE TITLE
[13.0] changed pdf content despite attachment_use

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#41079]
Impacted versions: 13.0

Steps to reproduce:

1. Enable attachment_use for invoice report - for example account.report_invoice
2. Enable factur-x module
3. Print Invoice (printed include facturx.xml)
4. Stored attachment include facturx.xml, too
5. Print again invoice (theoreticaly from attachment if attachment_use)

Current behavior:
Printed again invoice NOT include embeded facturx - PDF changed

Expected behavior:
Saved and downloaded PDF file will never change

**Comment by pedrobaeza** [comment]
@smetl you were the original author of FacturX. Maybe you can check this.

**Comment by zbik2607** [comment]
This is not facturx problem. Base ir.action.reports rebuild in this case PDF -call _merge_pdfs. Issue is in base.

**Comment by pedrobaeza** [comment]
Well, as you have specified in your steps to reproduce factur-x explicitly...

Then remove it if it's the same with or without the module.

**Comment by zbik2607** [comment]
factur-x only  gives an example of using _post_pdf when an error occurs. merge_pdf should never be called if attachment_use.

**Comment by smetl** [comment]
@zbik2607 Print 2 invoices with `attachment_use`, you also need to merge the pdf. I will have a look on this issue.

**Comment by zbik2607** [comment]
Invoices example.  First original, next printed again.
[FV_2019_0014_DEMO.pdf](https://github.com/odoo/odoo/files/3905640/FV_2019_0014_DEMO.pdf)
[FV_2019_0014_DEMO(1).pdf](https://github.com/odoo/odoo/files/3905642/FV_2019_0014_DEMO.1.pdf)

**Comment by zbik2607** [comment]
PS. The original invoice should never be rebuilt. A PDF attachment can, for example, be permanently digitally signed

**Comment by smetl** [comment]
@zbik2607 I will produce a fix for that

**Comment by smetl** [comment]
Landing on 13.0 at revision: 
https://github.com/odoo-dev/odoo/commit/8cb094850604bb5ffe9c322b662569d7f0237784

**Comment by smetl** [comment]
@zbik2607 Thank you for having reported this bug
