### ISSUE TITLE
[12.0] Raises warning  "Compute field depends on itself; please fix its decorator @api.depends()" while there is no depending on itself 

### ISSUE THREAD

**Issue by crtmneric** [odoo/odoo#41081]
Impacted versions:
12.0
Steps to reproduce:

1. Make a compute field depends on it self
2. Build Once
3. Delete own dependency from api decorator
4. Build Again
5. Warning still Raises
6. Change Method name
7. Warning gone

Current behavior:
Raises warning  "Compute field depends on itself; please fix its decorator @api.depends()" while there is no depending on itself 

Expected behavior:
No warnings after deleting own dependincy

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
It's not enough with "building": you should update the module. Any way, this is a circumstantial consequence of doing bad things, and only in your development environment.

Closing as no real issue, but temporary condition while not updating.
