### ISSUE TITLE
[Odoo 11] Blank Page after server restart - Ubuntu 16.04

### ISSUE THREAD

**Issue by FlyingPigSolutions** [odoo/odoo#41102]
Impacted versions: **Odoo 11 Community**
Server Ubuntu 16.04
Original Odoo 11 install from [@chris001](https://github.com/Yenthe666/InstallScript/issues/58) which I thank
Not in `Nginx` (nor `apache` which @Yenthe666 recommend not to use as outdated)
> IMPORTANT ! This server is in production for 1,5 year now and was working fine till now

![image](https://user-images.githubusercontent.com/36439846/69861454-ade4bf80-1298-11ea-9558-83200b1060ef.png)
>Facing this issue for the last 4 days, i resort to your help guys, as I tried all I could find online and none works in my case. I am sure others face this issue to as it seems it is [redondant](https://github.com/Yenthe666/InstallScript/issues/58).
**Steps to reproduce**: (or more likely how the issue arised)
To solve a queue_job issue not sending job anymore, I was operating some change in configuration file and then restarted the server with command `sudo service odoo-server restart`.

The front page works though:
![image](https://user-images.githubusercontent.com/36439846/69862362-88f14c00-129a-11ea-88b4-fde6adc29538.png)

Then suddenly the **odoo page is blank**.

Current behavior: Not showing the menu. Only company logo, and black menu bar
Expected behavior: Content should be shown

Our actual configuration `/etc/odoo/odoo-server.conf` from Chris' mega install

> [options]
addons_path = /home/odoo/odoo-server/addons/l10n-spain-11.0,/home/odoo/odoo-server/addons,/home/odoo/custom/addons
admin_passwd = MYPASSWORD
channels = root:2
csv_internal_sep = ,
data_dir = /odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template1
db_user = False
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_soft = 414748364800
limit_memory_hard = 468435456000
limit_request = 8192
limit_time_cpu = 120
limit_time_real = 240
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
ODOO_QUEUE_JOB_CHANNELS=root:4
ODOO_QUEUE_JOB_PORT=8069
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = False
reportgz = False
server_wide_modules = web,queue_job
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 15

Solution I have tried without success after checking other similar issue online as #[19627](https://github.com/odoo/odoo/issues/19627) and few others
> I know @Yenthe666 will ask this as he does in all post :) (thank you for your patience) and same questions are coming back all the time so to make it short:
> Server is of course restarted after changes with `sudo service odoo-server restart`
> It's not related to a module install, as it was working fine the week before after installing modules.

1. Obviously its **not a cache issue**. We face the issue on different browsers and empty cache with the issue remaining.
> I believe its more an asset issue not loading correctly or broken somehwere.

2. **Reinstall the odoo instance**:
> We have the menu and content appearing again but lots of errors due to modules installed till now. Server under production
> But not an option as we have to reinstall all modules which now creates errors on each otherwises

3. **Removing ir_attachment** from db to force reload (as seen [#119627](https://github.com/odoo/odoo/issues/19627))
`sudo su - postgres`
`psql YOURDBNAME`

`select id,name from ir_attachment where res_model='ir.ui.view' and name like '%assets_%';`

![image](https://user-images.githubusercontent.com/36439846/69864898-39158380-12a0-11ea-8e5c-e23aba659779.png)

`delete from ir_attachment where res_model='ir.ui.view' and name like '%assets_%';`

`select id,name from ir_attachment where name like '/web/content/%%assets_backend%.css%';`
also DELETE FROM…

`select id,name from ir_attachment where name like '/web/content/%';`

![image](https://user-images.githubusercontent.com/36439846/69864913-403c9180-12a0-11ea-86ff-e5d812bab105.png)

`delete from ir_attachment where name like '/web/content/%';`

> `Control + D` to get go back to main x2 (or `\q`)
> Restart server using `sudo service odoo-server restart`
> Refresh the page in your browser
> **Not making any changes**
> Did I miss something?

4. Tried following solution from @ged-odoo, to regenerate assets in the debug manager (in master, commit [28491aa](https://github.com/odoo/odoo/commit/28491aac45dc912696c1fcc57a50e3ec98906336)) 
> Do the changes in the file directly in Terminal `cd ../home/odoo/odoo-server/addons/web/static/src/js/widgets/` using `sudo nano debug_manager.js`
![image](https://user-images.githubusercontent.com/36439846/69864165-a88a7380-129e-11ea-9f6d-843c8ffde51b.png)
![image](https://user-images.githubusercontent.com/36439846/69864198-b0e2ae80-129e-11ea-9406-3a1003b4fca6.png)
> `CONTROL + X` and `SAVE Y`(es)
> Same thing for base.xml (see link  [28491aa](https://github.com/odoo/odoo/commit/28491aac45dc912696c1fcc57a50e3ec98906336))
![image](https://user-images.githubusercontent.com/36439846/69864425-2c446000-129f-11ea-8802-2d8ee3692c6b.png)
![image](https://user-images.githubusercontent.com/36439846/69864432-2ea6ba00-129f-11ea-8a1f-36b04aa49d84.png)
> Restart server `sudo service odoo-server restart`
> **Not making a difference**

5. Reinstall the requirements
`sudo pip3 install - r ../home/odoo/odoo-server/requirements.txt` (in my case)
but could be for you just `sudo pip3 install - r requirements.txt`
> **Not making a difference**.

6. Tried solution 3+4
> **Not making a difference**

**General comment on this issue:**
It is **not the first time** I face this issue, but last time I **passed by it by coming back to previous weekly** environment **back up** from the Ubuntu server. But I would like to avoid that this time and **find why this issue occurs**

**Comment by FlyingPigSolutions** [comment]
> What I haven't tried, because the issue didn't come from module installation, but in case someone need to try that option and don't have access to your odoo page:

7. Remove all last modules installed
`rm -r MODULE_NAME` should be avoided
To remove module from terminal, prefer following steps:
step-1: `sudo su postgres`
step-2: `psql database_name`
step-3: `update ir_module_module set state='to remove' where name='module_name' and state='installed';`

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by FlyingPigSolutions** [comment]
> This can happen following the installation of one or more modules. My case here.
**1. You have to look if it is a missing python library**
For this you have to look at the type of error in the web browser with the developer tools.
![image](https://user-images.githubusercontent.com/36439846/77253125-bce0ea80-6c58-11ea-8bb8-d4c450e4061b.png)

Then in Terminal> launch the log detail: `tail -f / var / log / odoo / odoo-server`

This lets you know what is occurring and which Python libraries are missing after installing the module if that is the case.

So after checking I added the missing libraries `pip install XXXXX` and then followed step 4 and then 3.
Then `sudo service odoo-server restart`

And it fixed the issue for me.
