### ISSUE TITLE
[v8, Trunk] Calendar tree view -> "Group by" seems broken

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#4114]
Everything is on the title :)

**Comment by Yenthe666** [comment]
Hi @tfossoul ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
