### ISSUE TITLE
There's no such but, or the steps to reproduce it are missing, so closing unless you provide them. I'm using Odoo 8 years and I haven't lost any master password.

### ISSUE THREAD

**Issue by EarthJEE** [odoo/odoo#41153]
There's no such but, or the steps to reproduce it are missing, so closing unless you provide them. I'm using Odoo 8 years and I haven't lost any master password.

_Originally posted by @pedrobaeza in https://github.com/odoo/odoo/issues/41150#issuecomment-560102947_

**Comment by pedrobaeza** [comment]
Why are you still opening new issues without steps to reproduce? As said, while you don't provide them, there's nothing that can be done.
