### ISSUE TITLE
V11.0 - Not reflecting PO uom in Stock receiving uom

### ISSUE THREAD

**Issue by rjay1018** [odoo/odoo#41173]
I use pc(s) on PO but on receiving of products it still uses the default unit of measure of the product in this case Unit(s)

![Screenshot(90)](https://user-images.githubusercontent.com/5526244/69957280-4f8c3b00-153d-11ea-905e-aeebe398fa5c.png)

![Screenshot(89)](https://user-images.githubusercontent.com/5526244/69957192-19e75200-153d-11ea-9f7a-0f3164afcd5a.png)

**Comment by sle-odoo** [comment]
Hello,
By default we do not propagate the UoM, but you can set the ir.config_parameter "stock.propagate_uom" to "1" if you want this behavior.

Regards
