### ISSUE TITLE
wrong type for comparsion

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#41192]
https://github.com/odoo/odoo/blob/3abe39e785d28d1e0b1a18eb9b98c1d341e5a116/addons/web/static/src/js/views/pivot/pivot_view.js#L100

`this.fields_view.arch.attrs.disable_linking` is string, need to convert to bool first.

**Comment by Yenthe666** [comment]
@jeffery9 why don't you create a PR right away? 😄

**Comment by pedrobaeza** [comment]
I think this can be closed as no answer and no PR

**Comment by Yenthe666** [comment]
I agree. The PR is still welcome!
