### ISSUE TITLE
System raise error when install  account_accountant module

### ISSUE THREAD

**Issue by pooja-zakhariya** [odoo/odoo#41207]
Impacted versions:
Odoo 13 Enterprise

Steps to reproduce:
Install Odoo 13 account_accountant module. i will raise error 
ValueError: Element '<xpath expr="//div[@id='sale_purchase_refund']">' cannot be located in parent view

Current behavior:
System will raise error

Expected behavior:
System should allow installation without any error.

Video/Screenshot link (optional):
![Screenshot from 2019-12-03 12-44-57](https://user-images.githubusercontent.com/4104012/70028504-d509fc80-15ca-11ea-9626-7b3f064db63e.png)

**Comment by Yenthe666** [comment]
@pooja-zakhariya can you reproduce this on the latest runbot instances? I've tested this on the latest V13 builds but the module is working fine. If you can reproduce it on a runbot can you then please add the steps in detail?

**Comment by pooja-zakhariya** [comment]
Hello Yenthe,

I have tested this with latest pull and it is not reproducible.

Thanks for the update,

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback! We'll consider it solved then.
