### ISSUE TITLE
[11.0] Outstanding balance on paid invoices

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#41204]
**Impacted versions:** 11.0 e

**Steps to reproduce:**

1. Configure currency rates for two days 
2. Create an invoice with the date for the first currency rate
3. Create a statement bank in foreign currency  with the date for the second currency rate
4. Apply reconciliation on the invoice

**Current behavior:**

The invoices in open state with an outstanding balance after the full reconciliation

![INV 2019 0011 - Odoo](https://user-images.githubusercontent.com/5775695/70012762-d47e5100-154b-11ea-9ae6-8784a6a421bc.png)

**Expected behavior:**

The invoice on paid state

**Video/Screenshot link (optional):**

https://youtu.be/_RZDBSI5sJ4

### OPW: #2150035

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo V11 is no longer supported officially so we have to close this one.
Don't hesitate to update the ticket or create a new one if you can reproduce this in V12 and up though.
P.S: The OPW should be answered anyways

Regards,
Yenthe
