### ISSUE TITLE
[7.0]Partially transfer product in Internal Move - no number assigned in Back Order

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#4123]
https://bugs.launchpad.net/openobject-addons/+bug/1200619 

When can it be merged to 7.0?

**Comment by aldennis** [comment]
Any update on this?

**Comment by Yenthe666** [comment]
Hi @oliverzgy ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
