### ISSUE TITLE
odoo 12 css error after choosing database

### ISSUE THREAD

**Issue by Greentash** [odoo/odoo#41279]
Impacted versions: 
Odoo 12

Steps to reproduce:
I just ran the script from https://github.com/Yenthe666/InstallScript/tree/12.0 

Current behavior:
![odoo_error](https://user-images.githubusercontent.com/5729518/70065738-7c932900-15e3-11ea-9fc9-aee320c4e767.png)
![odoo_error_1](https://user-images.githubusercontent.com/5729518/70065742-7dc45600-15e3-11ea-95f0-f76937a668c7.png)

Expected behavior:
i would like to have normal odoo 12 frontend
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by Greentash** [comment]
Thanks dear @pedrobaeza 
I have ubuntu 18.04, odoo12 and postgresql 10. Except the choosing database view, everything is crash from login to all whole rest.
i try to solve the problem by following this l[https://www.odoo.com/zh_CN/forum/help-1/question/how-to-install-sassc-139497](url)
but nothing much despite dependencies installed
![libsass](https://user-images.githubusercontent.com/5729518/70066715-0abbdf00-15e5-11ea-861a-18837e84e986.png)

**Comment by pedrobaeza** [comment]
Sorry, but that guide, although valuable, it's not official, and even being that, I assure you that it works, so something in your side is not correct. Any step or similar. But you have to ask for help in other place, as here it's for problems in Odoo code, not deployment things.

**Comment by Greentash** [comment]
"The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made."
This is the first line of error in frontend.
Isn't here a problem of deployment. The issue comes from web module that i didnt install. Moreover no module, neither customized nor native
