### ISSUE TITLE
Purchase order created stock moves floating point issues in database

### ISSUE THREAD

**Issue by leio** [odoo/odoo#4127]
When creating a purchase order, the associated stock moves have floating point issues due to no proper usage of Decimal module.
E.g, purchase order contains a quantity of 116.81400, but the stock.move created from it has a quantity of 116.81400000000001

**Comment by Yenthe666** [comment]
Hi @leio ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: I believe this is fine and they're saved like this on purpose. The frontend should round down and show a human number. But that is my five cents.

Regards,
Yenthe
