### ISSUE TITLE
Selling Serlialized Consiment Stock Thru POS Generate Negative Quants

### ISSUE THREAD

**Issue by ali-darakjian** [odoo/odoo#41355]
Impacted versions:
12.0 and 13.0

Steps to reproduce:

Activate Consignment (Owner)  In Inventory Settings
![Consignment](https://user-images.githubusercontent.com/47788806/70156763-72743780-1682-11ea-8e15-5139d4d7334c.png)

Create Product (Track By Unique Serial Number)
![Item Created](https://user-images.githubusercontent.com/47788806/70156762-72743780-1682-11ea-967f-fc983fe3b612.png)

Recive The Item as Consignment 
![receiving](https://user-images.githubusercontent.com/47788806/70156927-aa7b7a80-1682-11ea-9ffe-7a933d887c9f.png)

Sell It thru the pos with serial number
![pos Order](https://user-images.githubusercontent.com/47788806/70156760-72743780-1682-11ea-87c8-ae9d4157f6bf.png)
Current behavior:
It doesn't attache the owner to the sold serial number which is creating negative quant.

![POS Picking](https://user-images.githubusercontent.com/47788806/70156759-72743780-1682-11ea-8a00-4d73f5511615.png)

![No Owner Assigned](https://user-images.githubusercontent.com/47788806/70156761-72743780-1682-11ea-84a2-c964b979a446.png)

Expected behavior:
the pos doesn't consider consigment stock at all .

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you indicated the partner in PoS?

**Comment by ali-darakjian** [comment]
Yeep
Please check the attached images

![pos orders](https://user-images.githubusercontent.com/47788806/70157587-d3e8d600-1683-11ea-88c0-3515a5ac2cbd.png)
![On hand](https://user-images.githubusercontent.com/47788806/70157589-d3e8d600-1683-11ea-8e96-2c101b665f1f.png)
![Picking](https://user-images.githubusercontent.com/47788806/70157591-d3e8d600-1683-11ea-9fa9-2a707f47d3c2.png)

**Comment by pedrobaeza** [comment]
OK, labelled, although not sure if this feature is officially supported

**Comment by ali-darakjian** [comment]
Thanks for your fast response , is there any way or workaround to make it work ?
actually it causes a lot of inventory issues at the moment and finally i think since this feature is there it should be supported and fully functioned work.

**Comment by pedrobaeza** [comment]
I can't say anything more without an official response.

**Comment by Yenthe666** [comment]
@switch87 could you give an official response please? I'm not sure either if this is officially supported.

**Comment by pimodoo** [comment]
Hello, the consignment stock is not handled yet in point_of_sale. We've added your issue in our feedbacks,

Thank you
