### ISSUE TITLE
[8.0] owner on picking not propagated on quants

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#4136]
version affected: 8.0

Steps to reproduce:

1. in settings / Warehouse, enable 'manage owner on stock', and enable Technical Features for your user
2. Create a incoming stock picking from partner = Camptocamp, with owner = Luc Maurer of 13 IPads
3. Process the picking
4. Display the IPad product and click on the button on the top right corner saying "13 on hand" (action_open_quants)

Expected:

in the displayed list, I expect to see 1 line with a quant of 13 units and owner = Camptocamp (the commercial_partner_id of Luc Maurer)

Actual:

there is no owner on the quant.

**Comment by lepistone** [comment]
Hi @skh-odoo @jco-odoo, 

Happy new year! :smile:

Three attemps were made to address this:
- https://github.com/odoo-dev/odoo/commit/3e26a5da4f5fa7542a5bf1097f8525a8037bbbfb
- https://github.com/odoo-dev/odoo/commit/bea8c6379409ba25038de6a2a117996b511c80b3
- https://github.com/odoo-dev/odoo/commit/88991878738757e2f1c86651936ad5625396a2ad

The first two were erased and redone, losing comments from @gurneyalex @jco-odoo and me. In fact, I was saying that the fix works (and does some other things that I'd split).

Could you please make a pull request? That way even if you do `push -f`, comments are kept.

Thanks!

**Comment by lepistone** [comment]
Related issue: odoo/odoo#5165.
