### ISSUE TITLE
[website_sale_delivery]Issue in selecting delivery method and applying coupon

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#41405]
Impacted versions:all

Steps to reproduce:
Activate multiple delivery methods on website.Set a promotional code for a pricelist. Now in website show select products and select a delivery method  other than the default deliverymethod set in the customer. Then apply the coupon. Delivery method changes to default

Current behavior:
While applying coupon delivery method changes to default delivery method set in customer
Expected behavior:
It should not change the delivery method. It should only recalculate if necessary.
Video/Screenshot link (optional):

[carrier_price.zip](https://github.com/odoo/odoo/files/3926828/carrier_price.zip)

**Comment by rdeodoo** [comment]
It is not related to coupon, a simple reload on the /shop/payment page will reset the delivery.
Applying a coupon reload the page, so the 'issue' appears.

**Comment by pierre-pde** [comment]
Hi,
Thanks for the notification.
I confirm this is not a priority at the moment.
