### ISSUE TITLE
Added fields to an inherited AbstractModel are not added to inherited Model classes

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#4146]
If you have one module with these classes:
```
class Abstract(models.AbstractModel):
    _name = 'abstract'
    field1 = fields.Boolean()

class Concrete(models.Model):
    _inherit = 'abstract'
    _name = 'concrete'
```
and you define one new field in the AbstractModel class in another module:
```
class Abstract2(models.AbstractModel):
    _inherit = 'abstract'
    field2 = fields.Boolean()
```
You would expect that field2 is also created on 'concrete' class, but the result is that is not.

**Comment by pedrobaeza** [comment]
This should be now solved in https://github.com/odoo/odoo/commit/35bcd2c2a497c02d496568203fb241f99691642a in master branch, but not possible to make a backport.

**Comment by fshahy** [comment]
@pedrobaeza I have similar issue:
in a module I have this
`
class Abstract(osv.AbstractModel):
    _name = 'abstract'
    def doSomething():
`
the in another module I write
`
class Abstract2(osv.AbstractModel):
    _inherit = 'abstract'
    def doSomething():
`

the new extended method **doSomething()** does not execute.

**Comment by pedrobaeza** [comment]
This is solved in master, but not on 8.0/9.0. You must rename second abstract class and inherit from it.

**Comment by maryguirola** [comment]
Hi, @pedrobaeza  I renamed the second abstract class and inherit from the first one but It doesn't work. Any idea?

**Comment by pedrobaeza** [comment]
I didn't remember well the exact code, but I got it that way.

**Comment by ddfs** [comment]
long time but seems it is still there and little buggy. 

V11, modules inheriting the abstract class, should be also added to dependency of new module which extends the parent abstract class. 
in my case, I was extending: WebsitePublishedMixin in dependency of my module only website was defined, module install fine, all models in website inheriting WebsitePublishedMixin has new columns added but website_partner was throwing errors column does not exist.
