### ISSUE TITLE
[account_anglo_saxon] Wrong period in journal entries

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#4147]
Impacted versions:
* 8.0

Steps to reproduce:
* To set  "Generate procurement in real time" in Configuration/Warehouse 
* To set product like inventory valuation equal to Real Time and to set accounts
* To create purchase order with **"Order Date" = 10/31/2014** and select the product previously set
* To Confirm purchase order and got to shipments
* To make  the transfer to the current date **12/09/2014**

Current behavior:
* Date of stock move is the current date **12/09/2014**
* Period of journal entries generated is equal to **10/2014** corresponds to the date of purchase **10/31/2014** 

Expected behavior:
* Period of journal entries should correspond to the stock move **12/2014**

I made a video,
https://www.youtube.com/watch?v=MfGvWfaCYTw

**Comment by moylop260** [comment]
Branch link: https://github.com/odoo-dev/odoo/commits/8.0-opw-619902-rda

**Comment by nhomar** [comment]
This bug report is affecting also the sales process mixed with real time valuation.
Whatch the video to be better explained in such context.

 http://youtu.be/v0P24cj-rWQ

**Comment by gdgellatly** [comment]
This patch will cause an error depending on your timezone and whether check
in period is set on journal. Find period is context aware, time.strftime is
not, so entries on the last day or first day will error until you pass the
offset from UTC period.

**Comment by mart-e** [comment]
Thanks for the report @gdgellatly , fixed at d281e7aebd58904e68ee4ac1dadf9866acc2b4bd
