### ISSUE TITLE
[stock] Wrong creation invoice from picking 

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#4148]
Impacted versions:
* 8.0

Steps to reproduce:
* To set "Allow multi currencies" in Configuration/Accounting
* To create purchase order and to set "Invoice control" = "Based on incoming shipments" and currenc_id = "USD" and choose one product with **quantity = 1**
* To Confirm purchase order and got to shipments
* Click in button to transfer and make the reception for more quantity for example **quantity = 3**
* To create invoice from picking with button "Create Invoice"

Current behavior:
* create two invoices with different currency

Expected behavior:
Only should create one invoice with the same product and quantity of picking received

I made a video,
https://www.youtube.com/watch?v=QFY33NUr0BI

Note,
This happens also when purchase order was created by a different user at that processed picking and confirm purchase order

When this happens creates two invoices with **Reponsible** different

**Comment by mart-e** [comment]
Hello,

It seems fixed (creating only one invoice) but I could not identify the exact commit.
I am closing but let me know if you still have the bug and we will reopen.

**Comment by JulioSerna** [comment]
I would like reopen this issue because also happen when transfer from purchase has different responsible

I made a video,
https://youtu.be/i9CqLY-8Fc4

I expected one invoice with responsible who make the invoice

**Comment by mart-e** [comment]
Hello,

This seems like a different problem (so should probably be in a different issue if you wish to discuss about it) but for version 8.0 the behaviour was to split invoices per saleman.
In saas-6, we have changed that at ca8c6bce9849b63c02f54d0e6b3b8c4fe0b5f739 to adopt the behaviour you wish to have.
We can not change that in version 8 as it would be a change of behaviour not suitable for stable versions.
