### ISSUE TITLE
Interface problem

### ISSUE THREAD

**Issue by alzubairy** [odoo/odoo#41496]
Odoo 13.0 CE
Windows 10

When you choose the Arabic language, errors appear in the system

Link:
https://drive.google.com/drive/folders/1y9wgxg6xWulTiUrEkJzRdeWLh_acskV2

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions about RTL languages.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
