### ISSUE TITLE
Remove HTTPS XML-RPC options

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#4151]
`openerp-server`/`odoo.py` still has a bunch of options related to XML-RPC over HTTPS, even though that's not supported anymore, Odoo only exposes an HTTP interface and an SSL termination proxy has to be used for HTTPS connections.

These options should be removed, but not sure what the BC impact would be e.g. should the system allow but ignore (and stop documenting) HTTPS-related options, or should they be removed altogether and generate errors when used?

**Comment by rvalyi** [comment]
I think is clean in recent Odoo versions and this can be closed, right?
cc @Yenthe666

**Comment by Yenthe666** [comment]
@xmo-odoo your final call but I think it could be closed?

**Comment by xmo-odoo** [comment]
Indeed, thanks for the ping @rvalyi
