### ISSUE TITLE
[feature] drag&drop to change lines order in invoice

### ISSUE THREAD

**Issue by jibe-b** [odoo/odoo#41513]
Current behavior:

Lines in an invoice you are creating cannot be reordered, implying lots of cut-pasting if you want to reorder them.

Expected behavior:

Ability to reorder the cells via drag&drop.

Video/Screenshot link (optional):

![Screenshot from 2019-12-08 21-42-17](https://user-images.githubusercontent.com/6146483/70395871-a5605780-1a03-11ea-9a21-06ba1fe480f7.png)

Thanks a lot for your amazing work!!

**Comment by pedrobaeza** [comment]
Uhm, which program the screenshot belongs to? That's not Odoo...

**Comment by jibe-b** [comment]
@pedrobaeza That's Odoo, but with a custom CSS.

But it's true that it's very different from the last version available in trial version : 

![Screenshot from 2019-12-08 22-08-16](https://user-images.githubusercontent.com/6146483/70396231-54526280-1a07-11ea-9ce3-d9d49591e6e8.png)

**Comment by pedrobaeza** [comment]
Lines are dragglable in standard Odoo, so closing this as invalid.

**Comment by jibe-b** [comment]
And there is drag&drop in this version.

![Screenshot from 2019-12-08 22-09-31](https://user-images.githubusercontent.com/6146483/70396248-7350f480-1a07-11ea-98e4-2703450599bd.png)

So let's close my feature request as already available.

Thanks for your quick answer @pedrobaeza!
