### ISSUE TITLE
Error on installing Accounting module

### ISSUE THREAD

**Issue by lithint** [odoo/odoo#41510]
Impacted versions: 13.0 Enterprise

Steps to reproduce:
Try install Accounting Module

Current behavior:
giving error when installing accounting module, 
<img width="961" alt="image" src="https://user-images.githubusercontent.com/7326014/70387965-33691d80-19c5-11ea-92f0-564eeb46474f.png">

Expected behavior:
should get install with out errors

Video/Screenshot link (optional):
<img width="961" alt="image" src="https://user-images.githubusercontent.com/7326014/70387967-3d8b1c00-19c5-11ea-8395-7380ca0be13c.png">

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
