### ISSUE TITLE
oe_no_button has no class defined but used in sales module

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#41517]
Impacted versions:
12 enterprise. not sure about community

oe_no_button is used here:
odoo/addons/sale/views/sale_views.xml:328

```
<field
    name="product_uom"
    force_save="1"
    groups="uom.group_uom"
    class="oe_inline oe_no_button"
    attrs="{
        'readonly': [('state', 'in', ('sale', 'done', 'cancel'))],
        'required': [('display_type', '=', False)],
    }"
/>
```

**Comment by pedrobaeza** [comment]
Well, that can be dead code but it doesn't provoke any problem AFAIK, so closing this as no issue, but "enhancement". You can propose to master branch to remove it if it still remains. If there's any problem associated to have this dead class, just tell.

**Comment by obayit** [comment]
I was just in a training session, and the tutor tried to use the class after he saw it in the documentation. Then searched for an example in the code, and found it in the sales form!
We all got confused. So I think removing it from the documentation is more important.

**Comment by pedrobaeza** [comment]
Can you point where in the documentation is?
