### ISSUE TITLE
Unable to select default fi language on website

### ISSUE THREAD

**Issue by unwasted** [odoo/odoo#41522]
Impacted versions: 13.0

Steps to reproduce:
1) install website with several languages and set fi_FI as default
2) change language to anything other than fi
3) try to change language back to fi

After some modification to:
https://github.com/odoo/odoo/blob/4ca265faeaa503dc26432f7f3e3ca1cfa87a76f4/addons/website/views/website_templates.xml#L420
t-att-data-url_code="lg[1]"> ----> t-att-data-url_code="lg[0]">

In any case you should set frontend_lang cookie to correct lang first place. fi_FI not fi

**Comment by Yenthe666** [comment]
@mart-e for your interest.
