### ISSUE TITLE
[8.0] Message Subtype Bug

### ISSUE THREAD

**Issue by jsh-odoo** [odoo/odoo#4153]
Impacted versions:
- 8.0 and above

Steps to reproduce:
1. Find any object which has the facility of chatter and having different Message sub type options.
2. Click on Follower Dropdown.
3. Double click on any of the Message subtype(mail.message.subtype) check box.

Current behavior:
- All the message sub types are doubled. Unable to change after doubled.

**Comment by goose1** [comment]
Were you able to find a resolution to this? The bug is still present on the current builds.

**Comment by Yenthe666** [comment]
Hi @jsh-odoo,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
