### ISSUE TITLE
Odoo created a view without installing its module 

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#41615]
Impacted versions:
12 enterprise
Steps to reproduce:
still unknown
Current behavior:
Some views are created in database without its module being installed.
Expected behavior:
A view shouldn't be created unless its module is installed.
Video/Screenshot link (optional):
![Screenshot from 2019-12-10 12-43-43](https://user-images.githubusercontent.com/20386024/70522996-bf588200-1b4a-11ea-9607-3c24e48df2a2.png)
on the left it shows that the pad module is not installed, but yet there is views created (on the right).

This happened to me many times on different server installations.
I have a one or more modules that depend on "project" btw. But still this shouldn't happen.

**Comment by pedrobaeza** [comment]
Sorry, but unless you have clear steps to reproduce the problem, this seems something in your end, so closing this meanwhile.
