### ISSUE TITLE
[web] domain on *2many fields

### ISSUE THREAD

**Issue by SimoRubi** [odoo/odoo#41617]
**Impacted versions**
13.0

**Steps to reproduce**
1. Open a tree view containing a *2many field (say it is called `o2m_field`),
2. add a new field (`my_invisible_field`) in the tree view,
3. in the `field` tag of `my_invisible_field`, add an attribute `attrs={'invisible': [('o2m_field', '!=', False)]}`

**Current behavior**
`my_invisible_field` is always invisible in the tree view.

**Expected behavior**
`my_invisible_field` should be visible in the tree view according to its domain.

**Video/Screenshot link (optional)**
I have tried in latest v13 runbot to add the `invisible` attrs to the `name` field:
![image](https://user-images.githubusercontent.com/32064796/70522797-1c036f00-1b42-11ea-8d10-4d46dbe3b1be.png)

And it always hides the `Title` field (first column):
![image](https://user-images.githubusercontent.com/32064796/70523000-6127a100-1b42-11ea-8f0e-1a61b873309f.png)

I think the root cause of this issue might reside in: 
https://github.com/odoo/odoo/blob/0a2a468fb3fc08a106d0722938c4752cda9121a8/addons/web/static/src/js/core/domain.js#L86
because it does not manage correctly when `fieldValue` represents a *2Many field.

**Comment by kos94ok-3D** [comment]
Hi @SimoRubi 
I think you need use [] instead of False for *2many fields

**Comment by SimoRubi** [comment]
Thanks, it works :)
closing
I was concerned because in backend the domain works with `False` as I described..
