### ISSUE TITLE
[13.0] onchange with many2many changes doesn't work with widget many2many_tags and readonly

### ISSUE THREAD

**Issue by BT-nstuder** [odoo/odoo#41618]
**onchange with many2many changes doesn't work with widget many2many_tags and readonly**

Impacted versions:
 
 - 13.0
 
Steps to reproduce:
 
 1. Install module `stock`
 2. Enable `Storage Locations` in the technical settings
 3. Add an `onchange` function which changes the values of any many2many (displayed as `many2many_tags`) field `location_ids`:
```python
from odoo import api, fields, models


class StockInventory(models.Model):

    _inherit = 'stock.inventory'

    random_field = fields.Boolean(string="Random")

    @api.onchange('random_field')
    def _onchange_random_field(self):
        if self.random_field:
            location_id = self.env['stock.location'].search([], limit=1)
            # locations_ids is the field which is displayed as many2many tags
            self.location_ids = [(6, 0, [location_id.id])]

```
  4. Add `readonly` attribute to the `many2many` field:
```xml
<odoo>
    <!-- Extension of existing FORM view -->
    <record id="stock_inventory_form_view" model="ir.ui.view">
        <field name="name">stock.inventory.form</field>
        <field name="model">stock.inventory</field>
        <field name="inherit_id" ref="stock.view_inventory_form"/>
        <field name="arch" type="xml">
            <!-- Add random field -->
            <field name="product_ids" position="before">
                <field name="random_field"/>
            </field>

            <!-- Adjust location_ids -->
            <field name="location_ids" position="attributes">
                <attribute name="attrs">{'readonly': [('random_field', '=', True)]}</attribute>
            </field>
        </field>
    </record>
</odoo>
```
 5. Change the field which triggers the `onchange` method

Current behavior:
 
 - Client side JavaScript error:
```
Traceback:
setIDForLabel@http://localhost:8069/web/content/272-a839c26/web.assets_backend.js:825:543
_setIDForLabel@http://localhost:8069/web/content/272-a839c26/web.assets_backend.js:1698:132
confirmChange/</<@http://localhost:8069/web/content/272-a839c26/web.assets_backend.js:1661:1179
_.forEach@http://localhost:8069/web/content/271-b6f59e8/web.assets_common.js:108:566
confirmChange/<@http://localhost:8069/web/content/272-a839c26/web.assets_backend.js:1661:1139
```
 - Client side error in console:
```
TypeError: this.getFocusableElement(...) is undefined: web.assets_backend.js:825:543
```

Expected behavior:
 
 - `many2many_tags` field set to `readonly=1`
 - `many2many_tags` field new value according to the `onchange` function

> I get the expected behavior after changing the widget to the default one instead of `many2many_tags`

Additional notes:
 - Client OS: `Ubuntu 18.04.3 LTS`
 - Server OS: `Debian GNU/Linux 9.9 (stretch)`
 - Browser: `Firefox 71.0 (64-bit)`

![image](https://user-images.githubusercontent.com/42113866/70524987-9d5d0080-1b46-11ea-8a77-1e2de16d3725.png)

**Comment by nle-odoo** [comment]
Hello,


Thanks for the report, this should be solved with this change that will be merged soon:
 https://github.com/odoo/odoo/pull/43137
