### ISSUE TITLE
[12.0] products archived in inventory

### ISSUE THREAD

**Issue by vipvalen** [odoo/odoo#41634]
Impacted versions:
v10 / v11 /v12 /v13
In the Inventory / reporting / inventory report menu, when a product is archived, it should not go out in the inventory, this inventory is distorted.

In version 13, when the stock quantity is archived it returns to 0, but it also continues to appear in the inventory report.

Archived Product
![imagen](https://user-images.githubusercontent.com/18347857/70531457-40b51200-1b55-11ea-8cd5-1193aff3a09c.png)

The product stock is converted to 0 when it is archived, but still displayed in the inventory.

![imagen](https://user-images.githubusercontent.com/18347857/70531593-7e199f80-1b55-11ea-815f-bd7d36654fa3.png)

**Comment by sle-odoo** [comment]
we reviewed the presence of archived products in the reports at https://github.com/odoo/odoo/pull/45586
