### ISSUE TITLE
Done Qty column is disable when multi-warehouse option activated 

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#41680]
Impacted versions:
Odoo V13 CE

Steps to reproduce:
Go to Inventory ---------------->Click on Overview----------->Click on Receipts

Current behavior:
Done Qty column is disable 
Expected behavior:
 Done Qty column is should be open 
Video/Screenshot link (optional):
![Screenshot from 2019-12-11 10-10-46](https://user-images.githubusercontent.com/22232100/70593479-14ee6680-1bff-11ea-9aea-788434597892.png)

![Screenshot from 2019-12-11 10-12-48](https://user-images.githubusercontent.com/22232100/70593466-07d17780-1bff-11ea-8b61-81483f68d642.png)

**Comment by pedrobaeza** [comment]
This is because you have to click on the icon next to the done field or activate "Detailed operations" on the picking type for direct access to that field.

Closing as no real issue.
