### ISSUE TITLE
One2many field attribute inverse_name NOT WORKING.

### ISSUE THREAD

**Issue by mizohamza** [odoo/odoo#41686]
Impacted versions: 12.0 and 13.0.

Steps to reproduce: 
Define a One2many field on a model (for exemple **sale.order**) like this exemle:

    class SaleOrder(models.Model):
    _inherit = 'sale.order'

    warehouse_ids = fields.One2many(
        comodel_name='stock.warehouse',
        inverse_name='user_id',
        string='Warehouses')
- As you see in the exemple above, we are pointing to stock warehouse model, but the field (user_id is not the inverse field for the sale order model).

Current behavior: **Odoo is magic, it works.**

Expected behavior: **It should not work.**

**Comment by pedrobaeza** [comment]
`inverse_name` only serves for filtering the values in the other table, without semantic about "what's correct". It can work if the IDs pointed in user_id field exists in table `sale_order`, or gives an error if not, but this is not any error, but how the SQL behind ORM works.

Closing as explained above.

**Comment by mizohamza** [comment]
@pedrobaeza But the data that are fetched  are not correct. and the worst is when used with inheritance.  For exemple we may have a draft inherited record that point to non-used recordset.

Normaly the ORM should verify if the inverse_name point to the same model (sale.order) in the exemple above. because if we dont we break all our datas logic.

**Comment by pedrobaeza** [comment]
There's no such check because if done, you can't do things like linking to a generic integer field (`res_id`) that contains the IDs you want. You are the responsible of keeping the logic correct.
