### ISSUE TITLE
wkhtmltoppdf for ARM

### ISSUE THREAD

**Issue by luca-vercelli** [odoo/odoo#41690]
It's sad to see that there is not a (patched) wkhtmltox compiled for ARM processor, yet.
This is related to issue #10393.
The only place where I can find the binary is an (untrusted) third-party google drive repository.
It would be nice to add support for it.
I will open an issue on wkhtmltox, too.

**Comment by pedrobaeza** [comment]
Yeah, this is not something with Odoo itself (except that Odoo is relying on this third party for report engine), but nothing to be done on this side, so closing.

**Comment by luca-vercelli** [comment]
For the records: I opened the issue https://github.com/wkhtmltopdf/packaging/issues/44
