### ISSUE TITLE
How to remove above side quotation date and Salesperson from the quotation order 

### ISSUE THREAD

**Issue by JDamour** [odoo/odoo#41698]
Impacted versions: 11.0

Steps to reproduce: Using this code

```
<xpath expr="//div[@class='col-auto mw-100 mb-2'][4]" position="replace"/>
                  <xpath expr="//div[@class='col-auto mw-100 mb-2'][3]" position="replace"/>
```

Current behavior: Getting these errors
` ValueError: Element '<xpath expr="//div[@class='col-auto mw-100 mb-2'][4]">' cannot be located in parent view `

Expected behavior:
Removing above side quotation date and Salesperson in PDF file.
Video/Screenshot link (optional):
 
![image](https://user-images.githubusercontent.com/10071875/70613731-d6ae7280-1c11-11ea-9ce0-53edd6c4d7e3.png)

**Comment by Yenthe666** [comment]
I've already answered this in https://www.odoo.com/forum/help-1/question/remove-right-side-quotation-date-from-the-quotation-order-160681
Do xpath's, replace the objects, reorder, be done.

**Comment by JDamour** [comment]
@Yenthe666  the following answer isn't correct but I was just it as is 
Thanks
