### ISSUE TITLE
[11.0] When I add a product twice to the cart two lines are generated

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#41739]
Impacted versions: 11.0

**Steps to reproduce:**

1. Activate optional product configuration.
2. Add an attribute to the product that has create_varian = False.
3. Add that product to the run.
4. Re-add the product.
5. The order will create two lines.

**Current behavior:**

If the product has an attribute with create_variant = False, and is added twice to the cart two lines are generated.

**Expected behavior:**

the quantity should be added to the first line, as if it did not have create_variant = False, because it is the same product.

**[Video/Screenshot link (optional):](https://youtu.be/r-nUxr55IU8)**

FYI:

This behavior is due to this [validation](https://github.com/odoo/odoo/blob/11.0/addons/website_sale/models/sale_order.py#L80), but I do not understand why creating different lines when it is the same product.

**Comment by Yenthe666** [comment]
@pedrobaeza do you know why?

**Comment by pedrobaeza** [comment]
I can't say exactly. We need @JKE-be's advice

**Comment by JKE-be** [comment]
In all case it it the same product, so if we want to merge the same no_variant attribute value, we should match the description of the line, what is probably not so sure.

But in case you add 2 distinct value for the no-create variants, it make sense to have 2 distinct lines to allow you to distinguish the selected value.
![image](https://user-images.githubusercontent.com/4848797/70701930-8268c880-1ccd-11ea-8e92-56c47c8a14e8.png)
