### ISSUE TITLE
Issues in 'Assign salesman of assigned partner'

### ISSUE THREAD

**Issue by ahadpashaeeian** [odoo/odoo#41758]
Impacted versions:  12.0

No reaction occurs when allocating the opportunity to the portal user!

Video/Screenshot link (optional):

![Screenshot from 2019-12-12 13-02-10](https://user-images.githubusercontent.com/9713041/70700819-92d66e80-1ce0-11ea-8574-c3f06a40cf56.png)

**Comment by pedrobaeza** [comment]
That's because there's no customer in that lead.
