### ISSUE TITLE
[V13][POS]Sale Details report does show payment methods

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#41815]
**Impacted versions:**
V13

**Steps to reproduce:**
1. Set a POS in Odoo with several payment method (bank, cash,etc...)
2. Open a session
3. Create sales with different payment method
4. Close the pos
5. Validate the pos entries
6. Go to "Reporting->Sales Details"

**Current behavior:**
The report does contain any line in "Payments" section

**Expected behavior:**
The report's "Payment" section must contain one line by payment method

**Video/Screenshot link (optional):**

Test on Odoo runbot: http://749816-master-bf4333.runbot21.odoo.com/web

**Comment by pedrobaeza** [comment]
Some screenshots?

**Comment by rgeromegnace** [comment]
Here it is.
![pb_sale_detail_report](https://user-images.githubusercontent.com/14253152/70752852-de514280-1d09-11ea-8cac-1fdd72cc25b1.png)

**Comment by pedrobaeza** [comment]
And there are payment methods shown in the screen or neither?

**Comment by rgeromegnace** [comment]
Neither.

**Comment by Yenthe666** [comment]
@switch87

**Comment by pimodoo** [comment]
@rgeromegnace Thanks for reporting this, we'll fix it. I'll keep you up to date when it is merged.

@Yenthe666 switch87 doesn't work with us anymore, you can ping me instead.

**Comment by pimodoo** [comment]
will be fixed in https://github.com/odoo/odoo/pull/41825

**Comment by Yenthe666** [comment]
Ohhh I'm sorry to hear that :( Did he completely stop at Odoo? Thanks for letting me know!

**Comment by rgeromegnace** [comment]
> 
> 
> will be fixed in #41825

Ok thanks!!!

**Comment by pedrobaeza** [comment]
Already merged, so we can close this.

**Comment by Yenthe666** [comment]
Committed in https://github.com/odoo/odoo/commit/2adce8b01cc19ae2bc0f3236d80d94b9725b32df
