### ISSUE TITLE
Not working after adding workers parameter in odoo.conf file

### ISSUE THREAD

**Issue by luhuan97** [odoo/odoo#41822]
Sorry, I use Google Translate to English.

### Impacted versions:Odoo13  Ubuntu18.04

When workers = 0 or not set, everything works fine.

I used workers = 2 in odoo.conf.
However, he cannot enter Odoo, and the Odoo interface is displayed in white. When installing the website, the front end works fine.

### odoo.conf:
```
csv_internal_sep = ,
data_dir = /var/lib/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = False
reportgz = False
screencasts = None
screenshots = /tmp/odoo_tests
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = False
test_tags = None
translate_modules = ['all']
unaccent = False
upgrades_paths =
without_demo = False
workers = 5
```

### Chrome browser logs:
```
GET http://xxx:8069/web/content/358-611cc55/web.assets_backend.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
web:38 GET http://xxx:8069/web/content/357-611cc55/web.assets_backend.css net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
web:39 GET http://xxx:8069/web/content/335-00aa9f2/web.assets_common.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
web:52 Uncaught TypeError: odoo.define is not a function
    at web:52
```

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by DanyFahed** [comment]
@luhuan97 how did you resolve your issue? I'm facing the same problem, i installed odoo 13 in Ubuntu 18.04 and all was working fine but when i add the workers parameter, i face the same problem.
Thanks in advance

**Comment by Yenthe666** [comment]
@DanyFahed you might want to ask this on the official help forums actually. See help.odoo.com

**Comment by yelizariev** [comment]
May be related: https://github.com/odoo/odoo/commit/49e3fd102f11408df00f2c3f6360f52143911d74

**Comment by d4nich3n** [comment]
> May be related: [49e3fd1](https://github.com/odoo/odoo/commit/49e3fd102f11408df00f2c3f6360f52143911d74)

Thanks I've solved my problem

**Comment by yasr3mr96** [comment]
@d4nich3n 
How Please?????????

**Comment by szegc** [comment]
> > May be related: [49e3fd1](https://github.com/odoo/odoo/commit/49e3fd102f11408df00f2c3f6360f52143911d74)
> 
> Thanks I've solved my problem

@d4nich3n 
   Could you share me how to solve it ?
