### ISSUE TITLE
[13/docker:latest] Failed to import inventory lines

### ISSUE THREAD

**Issue by misl6** [odoo/odoo#41831]
**Impacted versions:**
Tested on 13.0 (docker:latest)

**Steps to reproduce:**
Create an inventory, import csv file, then process it.

**Current behavior:**
 ``` Unknown error during import: <class 'KeyError'>: 'product_id' at 147 different rows:```

**Expected behavior:**
Import without errors.

It's my first inventory ever in odoo, so, maybe, I did something wrong.

I'm trying to import the inventory lines from a csv with External_ID and Counted Quantity (and other unnecessary columns that I'm not importing)

**Comment by pedrobaeza** [comment]
This is apriori not an Odoo bug itself, but not knowledge on how to handle import. Please can ask for help on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
