### ISSUE TITLE
Leave request in hours | Leave request changes hours after approval

### ISSUE THREAD

**Issue by bultrug** [odoo/odoo#41848]
Impacted versions: 13.0

Steps to reproduce: Add employee, allocate paid leave, set leave in hours. Employee working hours is Mo: 8:30-12:30, Tu-Fr: 8:30-12:30 and 13:00-17:30 (total of 38h per week).
Employee requests on week of leave. Total hours in request is 38. Manager approves.

Current behavior: Before approval the total hours in the request is 38. The manager approves and the total hours change to 40. Total remaining hours is also -40.

Expected behavior: After approval the requested hours should not change and remain 38. The total remaining hours should also be -38.

Video/Screenshot link (optional):

**Comment by tivisse** [comment]
Hi @bultrug 

I still have to write a test about this, but https://github.com/odoo/odoo/pull/42710 should solve the issue.

Thanks for the feedback, and have a nice week-end.

**Comment by bultrug** [comment]
Hi @tivisse,

I just tested the correction in the code (vimmed it) and it works like a charm. Thanks for the rapid fix.
