### ISSUE TITLE
[13][Fleet] Parent attribute on Cost module is not used by the system?

### ISSUE THREAD

**Issue by akselon** [odoo/odoo#41897]
Impacted versions:
13

Current behavior:
I've been extending the Fleet module a bit last days for a client. It looks like the Parent_id parameter on fleet.vehicle.cost is not used by the system. The user can only manually choose a parent cost when going on Cost form.

I thought, that f.i. when generating recurring costs contract, that the generated cost would be placed in Parent_id field, but it's not.

Does it make sense to have a parameter, called Parent on a module if the system never uses it? What was the meaning of this field?

**Comment by pedrobaeza** [comment]
Well, I can't say about the meaning of it, but I'm afraid that if that field is simply informative or an orphaned one, this can't be considered as a bug, and thus, I'm closing it. Ask on forums or check in documentation what is the purpose of the field.
