### ISSUE TITLE
accounting: validating an invoice without tax lines changes the total

### ISSUE THREAD

**Issue by mgmax** [odoo/odoo#4191]
Impacted versions:
- 7.0 and above

Steps to reproduce:
1. create an invoice.  set encoded total to 3300 (if the field is enabled. optional.)
2. add a line with product 'LAP-CUS', quantity 1, unit price 3300, taxes "19% VSt"= (=19% VAT on top of the price)
3. save the invoice. do NOT press the update below the sum
4. Validate the invoice (red button).

Current behavior:
- step 3: Total sum is shown as 3300
- step 5: without any warning the sum has changed to 3927
- Even if the encoded total was 3300, no warning appears and we now have a validated invoice with encoded total != real total.

Expected behavior:
- validate should fail with a warning

The bug is in the if branch following this line: https://github.com/odoo/odoo/blob/4ca389a1a60e7f3266c9e8aedb4961bb6d875bae/addons/account/account_invoice.py#L826

This function should probably be "read-only".

**Comment by Yenthe666** [comment]
Hi @mgmax,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
