### ISSUE TITLE
[13.0] Fetch incoming emails with scheduled actions

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#41927]
Impacted versions: Lastest version to this date.
Database runs on odoo.sh

Steps to reproduce: I set external email servers. Outgoing mails work properly, but when replied, Odoo doesnt fetch incoming email as it should with scheduled actions.

Current behavior: It works when i click Fetch now button or Run manually, but scheduler doesnt fetch emails and also doesnt schelude next action. 

Expected behavior: Expected to fetch automaticaly as scheduled and set next scheduled action.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
For incoming messages, you have to configure properly catchall address and domain, and have an incoming server with such mailbox. For further information, please go to forums or mailing lists.

Closing this as no Odoo issue, but configuration.
