### ISSUE TITLE
account_anglo_saxon module does not differentiate between Price Difference and Exchange Rate Difference on Foreign Currency Transactions

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#4197]
1) Set a multi-currency environment in Odoo, Company Currency EUR (Base)
2) Allow Real Time Valuation,
3) Make sure account_anglo_saxon is installed
4) Take product ITEM and set Account configuration accordingly for Product category & Costing Method = Real Price & Inventoy Valuation = Real Time.
5) Set exchange rates for USD: 01/DIC => 2.00, 15/DIC => 1.25
6) Create Purchase Order (Invoice Policy = From Shipping) Date: 30/NOV, Currency:USD
10 ITEMS x 2000USD = 20.000USD
Approved 
7) Receive 10 ITEMS (Today=12/DIC @2.00USD/EUR)
Inventory (Dr) 10.000. [20.000USD => Not written in Journal Entry]
Accrued Payable (Cr) 10.000 [-20.000USD => Not written in Journal Entry]
Posting Date is from 30/NOV / x11/2014 (Another Bug yet reported) Shall be 12/DIC  x12/2014

8) Create Supplier Invoice (Posting Date 15/DIC)
Accrued Payable (Dr) 10.000. [12.500USD]
Price Difference (Dr) 6.000 [7.500USD]
Payable (Cr) 16.000 [-20.000USD]

Supplier price for ITEMs has not changed so there is no price difference,
the only thing that has arised is Exchange rate difference, so the Journal
Entry shall be like:

Accrued Payable (Dr) 16.000. [20.000USD]
Payable (Cr) 16.000 [-20.000USD]
Exchange Rate Difference (Dr) 6.000 [0.00USD]
Accrued Payable (Cr) 6.000 [0.00USD]

This way leaving no gaps in Accrued Payable Entry Lines.

Accrued Payable (Cr) 10.000 [-20.000USD => Not written in Journal Entry]
Accrued Payable (Dr) 16.000. [20.000USD]
Accrued Payable (Cr) 6.000 [0.00USD]

Conclusion: Price Difference Account Shall not be used
Exchange Currency Difference Account Shall be used
When there has been no supplier price change on foreign currency purchases.

Best Regards.

**Comment by jbeficent** [comment]
Hello, we have fixed this and will be releasing a module. @hbto If you want we can discuss once it is published.

**Comment by Yenthe666** [comment]
Hi @hbto ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
