### ISSUE TITLE
[7.0][purchase] Incorrect unit price in foreign currency supplier invoices created from picking

### ISSUE THREAD

**Issue by alhashash** [odoo/odoo#4200]
**Steps to reproduce:**
1. In demo database with EUR as the company currency, create a purchase price list in USD currency.
2. Create a purchase order in USD price list and set invoice control to: `Based on incoming shipments`.  
3. Add a line using any stockable product and set unit price to `$100.00`.
4. Confirm, process picking and create invoice.

Result: **The unit price in the generated invoice is `$65.41` instead of `$100.00`**

The bug was caused by commit ff90f2181236868fc8e4e2bf041e7a656e2303ea which changed invoice unit price to use the value of `stock.move.price_unit` instead the PO price. This field value is in company currency and, according to its definition, is a technical field used only for average price calculations.

The mentioned commit was made to fix [bug lp:779064](https://bugs.launchpad.net/openobject-addons/+bug/779064). This bug was based on a case where users change the unit price in the stock move (May be to control stock valuation). As of current Odoo 7.0, unit price in stock move is not displayed in any view and, based on definition, it should not be editable. So, the mentioned bug is actually invalid.

I suggest to revert the commit. Another solution is to only use the move unit price if the original currency matches the PO currency.

**Comment by Yenthe666** [comment]
Hi @alhashash,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
