### ISSUE TITLE
7.0 : invoice from delivery with service and group by partner

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4201]
Here is the scenario to reproduce the bug:
1. Connect to runbot v7
2. Create a new sale order for Camptocamp with 3 sale order lines:
   1 x USB Adapter
   1 x Headset USB
   1 x Service
  On this sale order, set the "Create Invoice" = "On delivery Order"
  Validate the order.
3. On the related picking (let's say OUT-1), do a partial delivery with only 1 x USB Adapter
4. On the backorder picking (let's say OUT-2), delivery the USB Headset
5. On the tree view of the delivery orders, select the 2 pickings OUT-1 and OUT-2, which are linked to the order of camptocamp. Do "More > Create Draft Invoices"
In the wizard, select the option "Group by Partner" = True
6. Open the related draft invoice: in the invoice lines, you will have:
  1 x USB Adapter
  1 x Service
  1 x Headset USB
  1 x Service
That's the bug: we should only have 1 invoice line with 1 x Service !

**Comment by gurneyalex** [comment]
See also https://code.launchpad.net/~openerp-dev/openobject-addons/7.0-invoice-ondelivery-with-service-product-tpa/+merge/189068

**Comment by beledouxdenis** [comment]
Closed with fc11b58239f4097be907be3ad41b1c0757b00e7a.
