### ISSUE TITLE
Returning action_url object from backend leads to template rendering two times

### ISSUE THREAD

**Issue by jas-odoo** [odoo/odoo#4202]
When returning ir_action.act_url object from method or redirecting to specific url from backend, the related template is render/call two times.

Affected Module:

1) survey

        when clicking on test survey, it will redirect to website view ('survey/start/sureyName-1/token') and called two times.
        issue : this template will create user input object, so two user input object will be created on backend.

2) website_quote

        when clicking preview template, it will preview template on website side.
        issue : template is render two times, this will affect performance

Affected Branch : 8.0, master

see : http://youtu.be/CzdB5swExsY

**Comment by rim-odoo** [comment]
Fixed there https://github.com/odoo/odoo/commit/11f147f2d94c8aff729590183e24337b2c076c86
