### ISSUE TITLE
[13.0] [Accounting - Multicurrency] Wrong VAT Base Amount in Invoice report

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#42069]
Impacted versions:
[13.0]
Steps to reproduce:
Print a Invoice with VAT in other currency 
Current behavior:
![inv](https://user-images.githubusercontent.com/9564408/71055329-e3751e00-215d-11ea-9b29-30cfbb64563f.jpeg)

VAT Base amount is calculated from local currency in report. 
![inv2](https://user-images.githubusercontent.com/9564408/71055435-41096a80-215e-11ea-93d6-17d34557cd35.jpeg)

"Tax 15% on 1.69 €" is wrong
Expected behavior:
Should be : "Tax 15% on 1.11 €"
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@qdp-odoo maybe you can check this

**Comment by william-andre** [comment]
Should be fixed by https://github.com/odoo/odoo/pull/42463
