### ISSUE TITLE
[13.0] [Accounting] VAT Account type definition

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#42070]
Impacted versions:
[13.0]
Steps to reproduce:
If we change the VAT Account type to "Payable" instead of  "Current Liabilities", the VAT calculation is not correct.
Current behavior:
![acc1](https://user-images.githubusercontent.com/9564408/71055977-5a131b00-2160-11ea-9881-7cc5ec273812.jpeg)
![ac2](https://user-images.githubusercontent.com/9564408/71055978-5a131b00-2160-11ea-80a4-5cd8c6d401b7.jpeg)

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's because you are doing something incorrect: a tax account can't be of type payable.

Closing as no valid.

**Comment by elperrofarelo** [comment]
We're working with odoo 12 and we've defined the tax account as "Payable" without any problem.

**Comment by pedrobaeza** [comment]
As said, that's incorrect. If it works in 12, it's by chance.
