### ISSUE TITLE
Multiple fields with same name in view can not have different placeholders.

### ISSUE THREAD

**Issue by jeroen7s** [odoo/odoo#42105]
Not sure if this is a bug or a feature that doesn't exist yet. 

Impacted versions:
13.0

Steps to reproduce:
add 2 fields
a regular char field
a many2one field
add placeholder on both of those fields in the view

Current behavior:
Char field shows placeholder correctly
Many2one field does not.
(placeholder="value" attribute in web-page is set on div that surrounds the <input> tag, not the input tag itself, which is where it should be in the HTML)

Expected behavior:
both fields should show the placeholder correctly.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10954827/71084231-1e467880-2195-11ea-9b6b-f0d004bd1e7a.png)

**Comment by jeroen7s** [comment]
Not sure why this is not showing?
other many2one fields on the same view like title and city do shw the placeholderm but this field just seems unable to do that.

**Comment by jeroen7s** [comment]
Apparently fields that occur multiple times in a view can only have 1 placeholder.
I had xx_brand_id in this view twice, once on the Lead side and once on the opportunity.
One had the placeholder filled in, the other one didn't -> both fields had no placeholder
Easily reproducable when adding the same field twice with different placeholders after each other in the view.
![image](https://user-images.githubusercontent.com/10954827/71087374-52716780-219c-11ea-8c08-9b1bc2e24e46.png)

**Comment by pedrobaeza** [comment]
But that's something expected, as the field dictionary is unique, and field duplication, although supported, has that possible side-effects.

Closing as expected.

**Comment by jeroen7s** [comment]
Yeah was expecting this to get closed after finding the cause. 
Makes sense from a technical perspective. 
Is annoying if you spend hours searching for what causes this tho :smile: 
Hopefully this info can help someone that has the same issue.

**Comment by pedrobaeza** [comment]
Yeah, I agree sometimes some corners of any framework (being Odoo ORM, development language, etc) makes you lose a lot of time for these things. This is where guidelines comes for saving risky cases IMO. If you think this advise enters in any of the docs for Odoo/OCA, it would be good to add it.
