### ISSUE TITLE
Account module with demo data: duplicated Opening Period creation fail

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#4212]
Hi,
during the installation of the account module with demo data, the opening period is ceated twice, what is wrong, because there is a constraint what checks this and throw an exception.
At first the "Opening Period 2014" is created by the account.py line 900 method create_period.
Secondly the demo data at account/demo/account_demo.xml at line 21 creates the "X Opening Period 2014" named record with the same dates.

The constraint at account.py line 991 method _check_year_limit fails by the code:

``` python
            pids = self.search(cr, uid, [('date_stop','>=',obj_period.date_start),('date_start','<=',obj_period.date_stop),('special','=',False),('id','<>',obj_period.id)])
            for period in self.browse(cr, uid, pids):
                if period.fiscalyear_id.company_id.id==obj_period.fiscalyear_id.company_id.id:
                    return False
```

I just did a clean install with demo data enabled, installed crm, project, hr than hr_timesheet_sheet modules.

**Comment by Yenthe666** [comment]
Hi @tsabi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
