### ISSUE TITLE
Inventory Manager cannot unpack packages. OPW-2159512

### ISSUE THREAD

**Issue by edy1192** [odoo/odoo#42135]
Impacted versions:
11.0
Steps to reproduce:
- Assign demo user to the Inventory / Manager group
- Login with demo user and go to Inventory / Packages
- Unpack a Package

Current behavior:

- Got a security error

```
Sorry, you are not allowed to modify this document. Please contact your system administrator if you think this is an error.

(Document model: stock.quant) - (Operation: write, User: 5)
```

Expected behavior:

Unpacked package

Video/Screenshot link (optional):

https://youtu.be/RgocbalSd5s

This is the line of code that produces the security error 

https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_quant.py#L468

**Comment by nim-odoo** [comment]
https://github.com/odoo/odoo/commit/9c6fb547b99d4faf889af9ba8c8d0b156ad7bf12
