### ISSUE TITLE
Error after paying with Stripe

### ISSUE THREAD

**Issue by implementosk** [odoo/odoo#42142]
Impacted versions:
13
Odoo by Bitnami
Deployed on Google Cloud

Steps to reproduce:
Activate and setup Stripe
Add item to cart
Select Stripe as Payment
Fill out credit cart details
Stripe redirects back to Odoo website, but with error described bellow
Sale Order is not created

Current behavior:
Internal server error:
"Failed to render template &lt;Template memory:7f7b2e637d10&gt; using values {'format_date': &lt;function MailTemplate._render_template.&lt;locals&gt;.&lt;lambda&gt; at 0x7f7b2e478440&gt;, 'format_datetime': &lt;function MailTemplate._render_template.&lt;locals&gt;.&lt;lambda&gt; at 0x7f7b2e4780e0&gt;, 'format_amount': &lt;function MailTemplate._render_template.&lt;locals&gt;.&lt;lambda&gt; at 0x7f7b2e630170&gt;, 'format_duration': &lt;function MailTemplate._render_template.&lt;locals&gt;.&lt;lambda&gt; at 0x7f7b2e6309e0&gt;, 'user': res.users(1,), 'ctx': {'lang': 'en_US', 'force_send': True, 'default_mass_mailing_name': False, 'default_mass_mailing_id': False, 'active_id': 82, 'active_ids': [82], 'active_model': 'sale.order', 'default_composition_mode': 'comment', 'default_model': 'sale.order', 'default_res_id': 82, 'default_template_id': 11, 'custom_layout': 'mail.mail_notification_paynow', 'tpl_partners_only': True, 'safe': False}, 'object': sale.order(82,)}", '')

Expected behavior:
Should work without error.

Video/Screenshot link (optional):
<img width="1680" alt="Screenshot 2019-12-18 at 20 51 15" src="https://user-images.githubusercontent.com/35446152/71118332-2a075e80-21d8-11ea-8b23-c4cce145a71a.png">

**Comment by pedrobaeza** [comment]
It seems the translations for the mail template in the language you are using is not correct. Please try on English and locate that translation for being corrected in Transifex.

**Comment by dbo-odoo** [comment]
Not sure it's a translation issue, but definitely not a payment issue. The mail template that gets sent upon confirmation of the order is broken, preventing the confirmation to take place. You can restore the mail template to its original configuration by updating the `sale` base module (not to be mixed with the Sale app, which is another module).

I'll close this because it's definitely a configuration issue.

**Comment by Xodus-CO** [comment]
Can you post/pastebin the working email template code?   Running on the hosted enterprise version and once I added Stripe module, it broke.
