### ISSUE TITLE
A issue when I try to translate the name field in the res.company model

### ISSUE THREAD

**Issue by OmerAhmed1994** [odoo/odoo#42173]
Impacted versions:12.0
Current behavior: 
issue when I try to translate the name field in the res.company model.

name = fields.Char(related='partner_id.name', string='Company Name', required=True, store=True, readonly=False,translate=True)

Expected behavior:
It should work as normal as translating any other field in the model

**Comment by pedrobaeza** [comment]
A related field can't be translatable as well. You depend on the original field.

Closing as no valid issue, but expected behavior.

**Comment by OmerAhmed1994** [comment]
thanks @pedrobaeza
