### ISSUE TITLE
[8.0] [hr_timesheet_sheet] Can create overloap timesheets

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#4217]
In 8.0, it is possible to create overloap timesheets in "Human Ressources" / "Time Tracking" / "Timesheet to validate". 

When trying to create overloap timesheets in 7.0, the following message appears:
> Error occurred while validating the field(s) date_from, date_to: You cannot have 2 timesheets that overlap!
Please use the menu 'My Current Timesheet' to avoid this problem.

Scenario:
On runbot, as admin:
1/ Go to "Human Ressources" / "Time Tracking" / "Timesheet to validate".
2/ Create two timesheets on the same period

**Comment by beledouxdenis** [comment]
Issue solved in Odoo 8.0 with rev. 
https://github.com/odoo/odoo/commit/ccb4e4332ece5c5d14f0f3ac38ff376a32fbe877
