### ISSUE TITLE
Export of Journal Entries is incorrect

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#4218]
Impacted versions:

 - 7.0

Steps to reproduce (runbot):

 1. Export Entries/Credit and Entries/Debit from Journal Entries
![image](https://cloud.githubusercontent.com/assets/7602419/5415179/73afb24c-8225-11e4-8a0b-2b6370808dc1.png)

Current behavior:

 - The content of the column credit is strange
![image](https://cloud.githubusercontent.com/assets/7602419/5415191/98e169ac-8225-11e4-85cd-a1b7ed53f4f4.png)

Expected behavior:

 - If I export column in the order Entries/Debit and Entries/Credit, the result is ok (because with demo data debit line is always the first journal items):
![image](https://cloud.githubusercontent.com/assets/7602419/5415223/ed4b499a-8225-11e4-8979-7522c51dfe65.png)

**Comment by mart-e** [comment]
Indeed, there was a bug in the export method. It was fixed at ffacce7.
Thank you for the report and analysis.
