### ISSUE TITLE
Active menu highlighting in odoo 13

### ISSUE THREAD

**Issue by saikirubamj** [odoo/odoo#42223]
Impacted versions:13.0

Current behavior:No active menu highlighting

Expected behavior:Need Action menu highlighted(No difference b/w active and unactive menu in top navbar)

**Comment by Yenthe666** [comment]
Hi,

This is actually something by design. The color only changes slightly when you hover over the menu and not when you've clicked on it. It's not something thats going to be changes honestly.

Regards,
Yenthe

**Comment by buithedo** [comment]
Hi everybody. I tried searching on Google for a solution but only this article mentions it. So I coded myself, it took a little while for me to read the Qweb documentation. My steps do the following for odoo14:
1. Edit menu XML: ~addons\web\static\src\xml\menu.xml
```
<t t-name="Menu.link">
    <t t-set="depth" t-value="(depth || 0) + 1"/>

    <t t-if="!menu.children.length">
        <t t-set="_link">
            <a role="menuitem" t-attf-href="#menu_id=#{menu.id}&amp;action=#{menu.action ? menu.action.split(',')[1] : ''}"
                t-att-data-menu="menu.id"
                t-att-data-action-model="menu.action ? menu.action.split(',')[0] : ''"
                t-att-data-action-id="menu.action ? menu.action.split(',')[1] : ''"
                t-att-data-menu-xmlid="menu.xmlid"
                t-attf-class="#{inNavbar ? '' : 'dropdown-item '}o_menu_entry_lvl_#{depth}"
                data-toggle="collapse" data-target="#o_navbar_collapse.in">
                <span><t t-esc="menu.name"/></span>
            </a>
        </t>
        <li t-if="inNavbar" onclick="main_menu_onclick(this)" t-attf-class="#{menu_index == 0 ? ' active ' : ''}">
            <t t-raw="_link"/>
        </li>
        <t t-else="">
            <t t-raw="_link"/>
        </t>
    </t>
    <t t-else="">
        <div t-attf-class="dropdown-header o_menu_header_lvl_#{depth}">
            <span><t t-esc="menu.name"/></span>
        </div>
        <t t-foreach="menu.children" t-as="menu">
            <t t-call="Menu.link"/>
        </t>
    </t>
</t>

<!-- separate first level dropdown from the others to avoid nested dropdown -->
<t t-name="Menu.sections">
    <t t-foreach="menu_data.children" t-as="first_level_menu">
        <section t-att-class="first_level_menu.id">
            <t t-foreach="first_level_menu.children" t-as="second_level_menu">
                <t t-if="!second_level_menu.children.length">
                    <t t-call="Menu.link">
                        <t t-set="inNavbar" t-value="true"/>
                        <t t-set="menu" t-value="second_level_menu"/>
                        <t t-set="menu_index" t-value="second_level_menu_index"/>
                    </t>
                </t>
                <t t-else="">
                    <li onclick="main_menu_onclick(this)" t-attf-class="#{second_level_menu_index == 0 ? ' active ' : ''}" >
                        <a href="#" class="dropdown-toggle o_menu_header_lvl_1" t-att-data-menu-xmlid="second_level_menu.xmlid" data-toggle="dropdown" data-display="static" role="button" aria-expanded="false">
                            <t t-esc="second_level_menu.name"/>
                        </a>
                        <div class="dropdown-menu" role="menu">
                            <t t-foreach="second_level_menu.children" t-as="third_level_menu">
                                <t t-call="Menu.link">
                                    <t t-set="depth" t-value="1"/>
                                    <t t-set="menu" t-value="third_level_menu"/>
                                </t>
                            </t>
                        </div>
                    </li>
                </t>
            </t>
        </section>
    </t>
</t>
```
2. Add your own js file and run the jquery command::
```
function main_menu_onclick(e) {
	$('.o_main_navbar .o_menu_sections li').removeClass('active');
	$(e).addClass('active');
}
```
You then customize the css according to the 'active' class you added.
I apologize that this tutorial is for programmers only.

**Comment by Marvin256** [comment]
> Hi everybody. I tried searching on Google for a solution but only this article mentions it. So I coded myself, it took a little while for me to read the Qweb documentation. My steps do the following for odoo14:
> 
> 1. Edit menu XML: ~addons\web\static\src\xml\menu.xml
> 
> ```
> <t t-name="Menu.link">
>     <t t-set="depth" t-value="(depth || 0) + 1"/>
> 
>     <t t-if="!menu.children.length">
>         <t t-set="_link">
>             <a role="menuitem" t-attf-href="#menu_id=#{menu.id}&amp;action=#{menu.action ? menu.action.split(',')[1] : ''}"
>                 t-att-data-menu="menu.id"
>                 t-att-data-action-model="menu.action ? menu.action.split(',')[0] : ''"
>                 t-att-data-action-id="menu.action ? menu.action.split(',')[1] : ''"
>                 t-att-data-menu-xmlid="menu.xmlid"
>                 t-attf-class="#{inNavbar ? '' : 'dropdown-item '}o_menu_entry_lvl_#{depth}"
>                 data-toggle="collapse" data-target="#o_navbar_collapse.in">
>                 <span><t t-esc="menu.name"/></span>
>             </a>
>         </t>
>         <li t-if="inNavbar" onclick="main_menu_onclick(this)" t-attf-class="#{menu_index == 0 ? ' active ' : ''}">
>             <t t-raw="_link"/>
>         </li>
>         <t t-else="">
>             <t t-raw="_link"/>
>         </t>
>     </t>
>     <t t-else="">
>         <div t-attf-class="dropdown-header o_menu_header_lvl_#{depth}">
>             <span><t t-esc="menu.name"/></span>
>         </div>
>         <t t-foreach="menu.children" t-as="menu">
>             <t t-call="Menu.link"/>
>         </t>
>     </t>
> </t>
> 
> 
> <t t-name="Menu.sections">
>     <t t-foreach="menu_data.children" t-as="first_level_menu">
>         <section t-att-class="first_level_menu.id">
>             <t t-foreach="first_level_menu.children" t-as="second_level_menu">
>                 <t t-if="!second_level_menu.children.length">
>                     <t t-call="Menu.link">
>                         <t t-set="inNavbar" t-value="true"/>
>                         <t t-set="menu" t-value="second_level_menu"/>
>                         <t t-set="menu_index" t-value="second_level_menu_index"/>
>                     </t>
>                 </t>
>                 <t t-else="">
>                     <li onclick="main_menu_onclick(this)" t-attf-class="#{second_level_menu_index == 0 ? ' active ' : ''}" >
>                         <a href="#" class="dropdown-toggle o_menu_header_lvl_1" t-att-data-menu-xmlid="second_level_menu.xmlid" data-toggle="dropdown" data-display="static" role="button" aria-expanded="false">
>                             <t t-esc="second_level_menu.name"/>
>                         </a>
>                         <div class="dropdown-menu" role="menu">
>                             <t t-foreach="second_level_menu.children" t-as="third_level_menu">
>                                 <t t-call="Menu.link">
>                                     <t t-set="depth" t-value="1"/>
>                                     <t t-set="menu" t-value="third_level_menu"/>
>                                 </t>
>                             </t>
>                         </div>
>                     </li>
>                 </t>
>             </t>
>         </section>
>     </t>
> </t>
> ```
> 
> 2. Add your own js file and run the jquery command::
> 
> ```
> function main_menu_onclick(e) {
> 	$('.o_main_navbar .o_menu_sections li').removeClass('active');
> 	$(e).addClass('active');
> }
> ```
> 
> You then customize the css according to the 'active' class you added. I apologize that this tutorial is for programmers only.

I'm new to Odoo and I have a question: Is it regular to modify Odoo core files to add a feature? Shouldn't we add a hook to the menu subsystem instead?
