### ISSUE TITLE
Eliminate a company

### ISSUE THREAD

**Issue by DrMaravich** [odoo/odoo#42251]
Impacted versions: Odoo 12.0-20190424 (Community Edition)

Issue: I have created a branch company by mistake and when it comes to delete this new branch company the following error comes up.

Error message: The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: Project - project.project]

I would like to know how to solve it. I don't have the Odoo installed in my computer, everything I do is in the website/server.

Thank you.

**Comment by pedrobaeza** [comment]
This is not an Odoo issue, but more a question.

In a nutshell, you have linked data of that company (a project in this case). You must remove each linked data (which is not always possible).

Any way, closing. Any further question should be done in forums, not here.
