### ISSUE TITLE
[8.0] Variable delivery costs (in function of price) are based on sales price including taxes

### ISSUE THREAD

**Issue by LeenSonneveld** [odoo/odoo#4225]
In version 8.0 (tested on : http://34250-8-0-44e401.runbot6.odoo.com/, delivery cost are based on the totale price including taxes.

Setup a delivery method, check Advanced Pricing per Destination
Condition = Price >= 0
Price Type = Variable
in Function of = Price
Sale Price = 0.1

When using the delivery method in a sales order, the price is calculated based on the totale price including taxes

![image](https://cloud.githubusercontent.com/assets/7634140/5417483/2f125c10-823a-11e4-8fd2-4b7ba0585cef.png)

**Comment by rcarnes** [comment]
This is easy to fix, git diff is:

diff --git a/addons/delivery/delivery.py b/addons/delivery/delivery.py
index 4cc7e7d..44c7f51c 100644
--- a/addons/delivery/delivery.py
+++ b/addons/delivery/delivery.py
@@ -219,7 +219,7 @@ class delivery_grid(osv.osv):
             weight += (line.product_id.weight or 0.0) * q
             volume += (line.product_id.volume or 0.0) * q
             quantity += q
-        total = (order.amount_total or 0.0) - total_delivery
+        total = (order.amount_untaxed or 0.0) - total_delivery

         return self.get_price_from_picking(cr, uid, id, total,weight, volume, quantity, context=context)

**Comment by Yenthe666** [comment]
Hi @LeenSonneveld ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
