### ISSUE TITLE
Survey.Survey does not save properly when it has multiple pages

### ISSUE THREAD

**Issue by wlin-kencove** [odoo/odoo#42267]
Impacted versions:
13
Steps to reproduce:
1: Create a survey with multiple sections and set all questions to mandatory.
2: In options tab, set the layout as "One page per section"
3: Save the survey and start the survey
4: Fill out the survey
Current behavior:
We noticed that form validation did not trigger on the survey page. Required fields were allowed to be left blank on form submission. Even if we do fill in all the mandatory questions, none of the answers are saved after we submit the ticket. 
Expected behavior:
We expected that the form would save normally. The form validation works and the survey results save normally when we set the layout as 'One page with all the questions'.  It does not work when the layout is 'One Page per Section'
Video/Screenshot link (optional):

**Comment by wlin-kencove** [comment]
![image](https://user-images.githubusercontent.com/59095052/71277480-10bef900-2323-11ea-9bc1-d50c192326ab.png)

**Comment by wlin-kencove** [comment]
The previous screenshot is from the Review Survey Link

**Comment by lalitkumar2k10** [comment]
Any update on this? Also, the answers to the previous sections are not shown in the review.

**Comment by lalitkumar2k10** [comment]
@Yenthe666 can you please check?

**Comment by Yenthe666** [comment]
Seems to work perfectly fine:
![image](https://user-images.githubusercontent.com/6352350/89616322-7fd46800-d888-11ea-8a3b-67156769318b.png)


Tested with a survey with three sections that all have one or more questions per section (page):
![image](https://user-images.githubusercontent.com/6352350/89616360-8ebb1a80-d888-11ea-9556-012c90f02931.png)


See https://3787604-13-0.runbot50.odoo.com/web#action=survey.action_survey_form&cids=1&id=5&model=survey.survey&view_type=form&menu_id=278
