### ISSUE TITLE
TypeError("cannot marshal None unless allow_none is enabled")\nTypeError: cannot marshal None unless allow_none is enabled\n'>

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#42268]
Impacted versions:
13.0
Steps to reproduce:
Call run() method for from xml-rpc gives error because it's return None  from model ir.actions.server  method def **_run_action_code_multi_**  adding **return True** at the end solves the problem.
Current behavior:
Exception is thrown 

TypeError("cannot marshal None unless allow_none is enabled")\nTypeError: cannot marshal None unless allow_none is enabled\n'>

Expected behavior:
Should execute the run method without throwing the exception.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Method `run` of which model?

**Comment by aliencrash** [comment]
In the **ir.actions.server** model.

**Comment by pedrobaeza** [comment]
Please do a PR amending that problem.

**Comment by Boudmir-Ibra** [comment]
Since it's a XMLRPC call, i think all you need is to add the attribute allow_none=True.
Like this for exm : client.ServerProxy('http://localhost:8069/xmlrpc/common/', allow_none=True)

**Comment by Boudmir-Ibrahim** [comment]
Since it's a XMLRPC call, i think all you need is to add the attribute allow_none=True.
Like this for exm : client.ServerProxy('http://localhost:8069/xmlrpc/common/', allow_none=True)

**Comment by Yenthe666** [comment]
I made a PR in V12 as the issue is present there too. See https://github.com/odoo/odoo/pull/42272

**Comment by aliencrash** [comment]
> Since it's a XMLRPC call, i think all you need is to add the attribute allow_none=True.
> Like this for exm : client.ServerProxy('http://localhost:8069/xmlrpc/common/', allow_none=True)

Doesn't work I tried that too. I can not make a PR now because now I'm out of office without my pc. :(
