### ISSUE TITLE
[13.0] Social media posts labeled posted even if not the case

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42274]
Impacted versions: 13.0

Steps to reproduce: 
1. Connect both Facebook and Linkedin to the social media app (through Configuration > Social media)
2. Schedule a post in the future for both Facebook and Linkedin
3. Make sure the social media token for Facebook is expired or that you change the password for Facebook.
4. Wait for the scheduled post to be handled by the social media app and check the results.

Current behavior: 
1. The social posts screen shows that everything is posted well:
![image](https://user-images.githubusercontent.com/6352350/71322237-b27e4b80-24c5-11ea-8aec-bd28126c0201.png)
2A. The detail screen of the post shows that the Facebook post "Failed" with an ugly formatted error message
2B. The chatter says it is posted well three times:
![image](https://user-images.githubusercontent.com/6352350/71322260-fb360480-24c5-11ea-867a-8fc17adf5158.png)

Expected behavior:
1. The social posts screen shows a "Failed" or "Error" label because at least one post failed
2 A. The detail screen shows the error message nicely, so not in a dictionary format
2 B. The chatter says that one of the posts could not be posted instead of "Message posted".
2 C. The chatter doesn't say 'Message posted' if you click on 'Retry' for the failed social media type (in this example Facebook).

**Comment by Yenthe666** [comment]
OPW `2161231`

**Comment by jvm-odoo** [comment]
Hello,

> 1 The social posts screen shows that everything is posted well

After reading the code, it seems that it's the wanted behavior. As you can see on your screenshot, when there is an error the div is red-bordered.

When you create a post it creates a `social.post` who contains the posts for each social network and these are `social.live.post`.

- `social.post` does'nt have a "failed" status
- `social.live.post` does

This is why the parent containing the 2 posts is not "failed", the status are not handled for the same purpose.

> 2A The detail screen of the post shows that the Facebook post "Failed" with an ugly formatted error message
> 2B The chatter says it is posted well three times

https://github.com/odoo/enterprise/pull/7444

Regards,

**Comment by Yenthe666** [comment]
I can assure you that the border is very small and hard to see. Some of my customers are colorblind and just don't see it 😅 maybe an extra label would be better to identify this?

**Comment by jvm-odoo** [comment]
Indeed, a tiny border is not accessible for people with disabilities.

https://github.com/odoo/enterprise/pull/7455

**Comment by Yenthe666** [comment]
Woohoo, thanks for that change. That'll make my customer happy 🎉

**Comment by Yenthe666** [comment]
All done & handled and it's much better now. Thanks @jvm-odoo
