### ISSUE TITLE
Rtl Styles Not Loading

### ISSUE THREAD

**Issue by master041** [odoo/odoo#42277]
Impacted versions: 12.0 CE

Current behavior:
When i change the language to a rtl layout language it returns 404 in console

![Screenshot from 2019-12-23 11-52-24](https://user-images.githubusercontent.com/16923209/71345726-6097fd00-257b-11ea-8a97-8592a55f36f8.png)

and the css files are empty
![Screenshot from 2019-12-23 11-52-31](https://user-images.githubusercontent.com/16923209/71345753-6db4ec00-257b-11ea-8d40-2eb8e28df4a2.png)

i already have rtlcss 

![Screenshot from 2019-12-23 11-53-25](https://user-images.githubusercontent.com/16923209/71345747-6a216500-257b-11ea-9507-36de127df3c8.png)

Expected behavior:
it should return correct styles in rtl layout

i'm looking forward for an answer

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
