### ISSUE TITLE
Two(Or more) Users working on one Document - More time spent, more money spent.

### ISSUE THREAD

**Issue by ztsiklauri** [odoo/odoo#4228]
**Impacted versions:**
- 7.0 and above

**Steps to reproduce:**

Suppose I have two HR managers registering the employees and they are registering employees based on Applications. Now 1st user opened an application and starts working on it. Another User opened the same application a minute later and also started working on it. What we have now is: We have 1 application filled by 2 users. More time is spent on filling, consequently more money is spent. Imagine when they are registering 200 employees how much time will be spent in vain. This problem will occur not only in HR. Same is Sales, Purchases and every document. 

**Current Behaviour:**

Two or more users are working on one document at the same time.

**Expected Behaviour:**

System should fetch a warning message when second user tries to edit the document on which fist user is working. After, he/she can ignore the warning message.

**Result and Benefits**

When a company has multiple users working on same type documents. E.g. HR Employees working on hundreds of applications, the company will spend less resources and time for application filling. Same will be for other documents and companies.

**Comment by ztsiklauri** [comment]
Indeed.

**Comment by maljac** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @ztsiklauri ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
