### ISSUE TITLE
Problem of Freezing List View Headers - in 7.0(Not available) - in 8.0 (Its something else)

### ISSUE THREAD

**Issue by ztsiklauri** [odoo/odoo#4229]
**Impacted versions:**
- 7.0 and above

**Steps to reproduce:**

Try to scroll down the list view and **Headers don't stay Freezed**

**Current Behaviour:**

Headers in tree view are not freezed.

**Expected Behaviour:**

Headers should be feezed because its causing a trouble for analysis when users have a lot of documents and they want to scroll down the list.

**Comment by vak0160** [comment]
Sorry for necro-ing, is there any plan for this?

**Comment by Yenthe666** [comment]
Hi @ztsiklauri ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
