### ISSUE TITLE
POS Save Unpaid Order

### ISSUE THREAD

**Issue by Cywaithaka** [odoo/odoo#4231]
This is more of a feature request.
I suggest if there can be a way to push an unpaid POS order to the server in draft/unpaid state so that the cashier (a different user from the one who created it) can see it under orders list page and receive payments. 
Currently, an order on the POS screen remains private to the user that is creating it until the user clicks on the Validate button after which it is marked as paid before being sent out to the server.
This action could also print an order ticket/bill to act as the customer's bill.
I basically want to add the order creation action to the POS touch screen
![image](https://cloud.githubusercontent.com/assets/2064129/5424440/19c7891a-82a4-11e4-87de-d295afe3d69c.png)

**Comment by mfaheemkhan6** [comment]
@TheCloneMaster Installation generate error for your POS.

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 539, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 292, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 755, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1067, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4007, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4198, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1282, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `amount_subtotal` does not exist

Error context:
View `Orders`
[view_id: 774, xml_id: n/a, model: pos.order, parent_id: n/a]" while parsing /opt/odoo/odoo/customs/point_of_sale/point_of_sale_view.xml:122, near
<record model="ir.ui.view" id="view_pos_order_tree">
            <field name="name">Orders</field>
            <field name="model">pos.order</field>
            <field name="arch" type="xml">
                <tree string="POS Orders" colors="blue:state == 'draft';gray:state in ('done','cancel');black:state not in('done','cancel')">
                    <field name="name"/>
                    <field name="pos_reference"/>
                    <field name="partner_id"/>
                    <field name="date_order"/>
                    <field name="user_id"/>
                    <field name="invoice_id"/>
                    <field name="amount_subtotal" sum="Subtotal"/>
                    <field name="amount_tax" sum="Tax"/>
                    <field name="amount_total" sum="Total"/>
                    <field name="company_id" groups="base.group_multi_company"/>
                    <field name="state"/>
                    <field name="session_id"/>
                </tree>
            </field>
        </record>

**Comment by Cywaithaka** [comment]
Hi. Try to restart your openerp server after copying the modules to the
addons folder.

On Wednesday, February 4, 2015, mfaheemkhan6 <notifications@github.com>
wrote:

> @TheCloneMaster <https://github.com/TheCloneMaster> Installation generate
> error for your POS.
>
> Traceback (most recent call last):
> File "/opt/odoo/odoo/openerp/http.py", line 518, in
>
>
>
>
>
>
>
>
>
> *handle_exception return super(JsonRequest,
> self).handle_exception(exception) File "/opt/odoo/odoo/openerp/http.py",
> line 539, in dispatch result = self._call_function(*self.params) File
> "/opt/odoo/odoo/openerp/http.py", line 295, in _call_function return
> checked_call(self.db, *args, *kwargs) File
> "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper return
> f(dbname, args, *kwargs) File "/opt/odoo/odoo/openerp/http.py", line 292,
> in checked_call return self.endpoint(a, *kw) File
> "/opt/odoo/odoo/openerp/http.py", line 755, in __call*
> return self.method(*args, **kw)
> File "/opt/odoo/odoo/openerp/http.py", line 388, in response_wrap
> response = f(*args, **kw)
> File "/opt/odoo/odoo/addons/web/controllers/main.py", line 953, in
> call_button
> action = self._call_kw(model, method, args, {})
> File "/opt/odoo/odoo/addons/web/controllers/main.py", line 941, in _call_kw
> return getattr(request.registry.get(model), method)(request.cr,
> request.uid, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
> return old_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 450, in
> button_immediate_install
> return self._button_immediate_function(cr, uid, ids, self.button_install,
> context=context)
> File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
> return old_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 498, in
> _button_immediate_function
> registry = openerp.modules.registry.RegistryManager.new(cr.dbname,
> update_module=True)
> File "/opt/odoo/odoo/openerp/modules/registry.py", line 346, in new
> openerp.modules.load_modules(registry._db, force_demo, status,
> update_module)
> File "/opt/odoo/odoo/openerp/modules/loading.py", line 363, in load_modules
> loaded_modules, update_module)
> File "/opt/odoo/odoo/openerp/modules/loading.py", line 263, in
> load_marked_modules
> loaded, processed = load_module_graph(cr, graph, progressdict,
> report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
> File "/opt/odoo/odoo/openerp/modules/loading.py", line 182, in
> load_module_graph
> _load_data(cr, module_name, idref, mode, kind='data')
> File "/opt/odoo/odoo/openerp/modules/loading.py", line 118, in _load_data
> tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind,
> report)
> File "/opt/odoo/odoo/openerp/tools/convert.py", line 901, in convert_file
> convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
> File "/opt/odoo/odoo/openerp/tools/convert.py", line 987, in
> convert_xml_import
> obj.parse(doc.getroot(), mode=mode)
> File "/opt/odoo/odoo/openerp/tools/convert.py", line 853, in parse
> self._tagsrec.tag <http://self.cr,%20rec,%20n,%20mode=mode>
> File "/opt/odoo/odoo/openerp/tools/convert.py", line 763, in _tag_record
> id = self.pool['ir.model.data']._update(cr, self.uid, rec_model,
> self.module, res, rec_id or False, not self.isnoupdate(data_node),
> noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
> File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
> return old_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 1067, in
> _update
> res_id = model_obj.create(cr, uid, values, context=context)
> File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
> return old_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in
> create
> context=context)
> File "/opt/odoo/odoo/openerp/api.py", line 237, in wrapper
> return old_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/api.py", line 332, in old_api
> result = method(recs, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/models.py", line 4007, in create
> record = self.browse(self._create(old_vals))
> File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
> return new_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/api.py", line 464, in new_api
> result = method(self._model, cr, uid, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/models.py", line 4198, in _create
> recs._validate_fields(vals)
> File "/opt/odoo/odoo/openerp/api.py", line 235, in wrapper
> return new_api(self, *args, **kwargs)
> File "/opt/odoo/odoo/openerp/models.py", line 1282, in _validate_fields
> raise ValidationError('\n'.join(errors))
> ParseError: "ValidateError
> Field(s) arch failed against a constraint: Invalid view definition
>
> Error details:
> Field amount_subtotal does not exist
>
> Error context:
> View Orders
> [view_id: 774, xml_id: n/a, model: pos.order, parent_id: n/a]" while
> parsing /opt/odoo/odoo/customs/point_of_sale/point_of_sale_view.xml:122,
> near
>
> Orders
> pos.order
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4231#issuecomment-72931692>.
>


-- 


*Thanks,Cyrus G*

*<http://www.techiepot.com <http://www.techiepot.com>>*

**Comment by DirkUytt** [comment]
HI Cywaithaka , could you also share your module with me?
dirkuytt@telenet.be
I am also trying to save an order before it get's paid. 
Thx,
Dirk

**Comment by fbscarel** [comment]
Hello TheCloneMaster and everyone. I'm also interested in the preview version of the module that adds unpaid invoice generation from POS interface. If at all possible, I'd be very interested in testing the module and sharing feedback.

Regards,
fbscarel

**Comment by DirkUytt** [comment]
HI Cywaithaka , could you also share your module with me?
I am also trying to save an order before it get's paid. 
Thx,
Dirk

**Comment by tahirlanre** [comment]
Hello TheCloneMaster, could you please share your module with me as well.

Best Wishes,
Tahir

**Comment by adesouki** [comment]
Hi TheCloneMaster, Can you please share your module.

Thanks
adesouki

**Comment by homonxa** [comment]
Hello TheCloneMaster, I have the same problem, could you please share your module with me as well.

Best Wishes,
 lionel

**Comment by Cywaithaka** [comment]
Hi guys. For those interested in the moule to save unpaid order, share your email addresses and i will forward.

**Comment by tahirlanre** [comment]
Here is my email: tahirlanre@hotmail.com


Regards, 

Tahir

**Comment by adesouki** [comment]
My email: adesouki@live.com

Thanks.

**Comment by homonxa** [comment]
My email lionelger@gmail.com

Thanks

**Comment by homonxa** [comment]
Hi,

  Thanks to share your module my mail is lionelger@gmail.com

regards

**Comment by mfaheemkhan6** [comment]
mfaheemkhan6@gmail.com

**Comment by TheCloneMaster** [comment]
I haven't been able to do proper cleanup, but expect to do it this week and
then will upload on github, so that you can collaborate...
Regards

**Comment by webwarrior** [comment]
Hi,

Thanks for sharing your module my mail is prosoftnz at gmail.com.

I am working on something that will allow you to load the prices from a price list assigned to a customer, when selecting a customer.

regards

**Comment by TheCloneMaster** [comment]
I just uploaded all POS related modules to github.

They are still messy, but I will be cleaning them up in the next days.

You can find the branch at
https://github.com/TheCloneMaster/point_of_sale.git

Regards,
-Mario

**Comment by tahirlanre** [comment]
@TheCloneMaster Thank you for sharing!

**Comment by webwarrior** [comment]
Awesome!

Thanks for that!

On Fri, Jun 19, 2015 at 10:24 AM, Mario Arias Badila <
notifications@github.com> wrote:

> I just uploaded all POS related modules to github.
>
> They are still messy, but I will be cleaning them up in the next days.
>
> You can find the branch at
> https://github.com/TheCloneMaster/point_of_sale.git
>
> Regards,
> -Mario
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4231#issuecomment-113331917>.
>



-- 
Kind Regards,
Shaun O'Reilly
http://www.linkedin.com/profile/view?id=51406551&trk=tab_pro

**Comment by mausoto** [comment]
Hi,

  Thanks to share your module my mail is mauriciosoto.90@gmail.com

regards!

**Comment by TheCloneMaster** [comment]
Hi Mauricio et all,

Please download it from github at
https://github.com/TheCloneMaster/point_of_sale.git

Bug reports (and PRs) are welcomed !!   ;-)

Regards,
-Mario

**Comment by mausoto** [comment]
Great! Thanks a lot!

**Comment by MalickDGN** [comment]
Hi, 
Thanks to share your module my mail is malickdgn@gmail.com 
regards

**Comment by mprudhviram** [comment]
Hi Cywaithaka, 
Could you share your module with me ?
My email address is mprudhviram@gmail.com.

 Your help is much appreciated.


Thanks

**Comment by Cywaithaka** [comment]
Hi mprudhviram and all, @theclonemaster has shared the module here https://github.com/TheCloneMaster/point_of_sale/tree/master/pos_transfer All credits to him for the great work

**Comment by RicardoBer** [comment]
It saves the order as paid, any workaround?

**Comment by mohamedhagag** [comment]
the below module fixes the missing step of reconciling / paying pos invoice mentioned by @mfaheemkhan6 here https://github.com/odoo/odoo/issues/4231#issuecomment-68036070 .

https://github.com/mohamedhagag/dvit-odoo8/tree/master/pos_invoice_payment_auto_reconcile

**Comment by tsixpence** [comment]
Greetings everyone, is the module that saves unpaid POS orders functional. We have a client who needs this functionality enabled for their production server running odoo POS.

**Comment by TheCloneMaster** [comment]
Hi, there is a module made by yente that is far better, as it allows to
keep proper  track of debts per customer.

I will post the link as soon as I can find it.
Regards
Mario

**Comment by peaceman2u** [comment]
Hi,
I am new to odoo pos and i really need help in some features i saw posted in this forum
(1) how to put sale on hold or save
(2) how to add extra bar for search item or sorting.

I will appreciate if i can get a response of my request... i wont mind paying for the support

My email add is: nanotechisng@gmail.com

**Comment by Yenthe666** [comment]
Hi @Cywaithaka ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
This feature is not on the roadmap for Odoo at the moment.

Regards,
Yenthe

**Comment by elishah19** [comment]
Hello @Cywaithaka and @TheCloneMaster , could you also share your module with me?
I am also trying to save an order before it get's paid.  in fact, i'm finding if what model do exactly  the POS order unpaid stored or saved. Then I finally found this conversation. 
I hope you may help me with this one.. 

Thanks. and God bless.

Here's my email: elishah.garcia019@gmail.com

I'll wait for the response. Thanks again.

**Comment by manisharpatil** [comment]
Hi @Cywaithaka and @TheCloneMaster , Can you please share your module. In fact, I'm finding if what model do exactly the POS order unpaid stored or saved.


Here's my email: manisharpatil6@gmail.com
Thanks & Regards,
Manisha Patil.
