### ISSUE TITLE
View an expense, changes the `write_uid` and `write_date`.  OPW-2161650

### ISSUE THREAD

**Issue by edy1192** [odoo/odoo#42326]
Impacted versions:
**12.0
13.0**
Steps to reproduce:
- Login with user (demo in this test).
- Activate developer mode.
- Enter the expense module.
- View an expense that contains an attachment.
- Open developer tools.
- See the metadata of the document.

Current behavior:
- The **last modification by** (`write_uid`) and the **Latest Modification Date** (`write_date`), changes when the view is loaded.

Expected behavior:
- These fields should not change, because the user is not modifying anything in the document.

Video/Screenshot link (optional):
https://youtu.be/MpTmJ919GpA

This behavior happens [here](https://github.com/odoo/odoo/blob/12.0/addons/mail/models/ir_attachment.py#L30)

**Comment by sswapnesh** [comment]
This happens on enterprise only due to missing arg `force`  (Which is `True` by Default) on `register_as_main_attachment` 
https://github.com/odoo/odoo/blob/d42a951369ee87b50e834f73cd2af5cf031d43f7/addons/mail/models/ir_attachment.py#L18

**Comment by pedrobaeza** [comment]
Yes, please report this through odoo.com/help, being something specific of enterprise.

**Comment by edy1192** [comment]
Hi @pedrobaeza 

I reported this issue and a ticket at odoo.com/help the ticket number is 2161650

Regards.

**Comment by pedrobaeza** [comment]
OK, thanks. Please let us know when the ticket gets solved.
