### ISSUE TITLE
[13.0] SMS context actions are not deleted when deinstalling related module

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42328]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 (enterprise)
2. Activate developer mode and go to Settings > Technical > Phone > SMS > SMS templates
3. Open the record "Calendar Event: Reminder" and click on "Add Context Action"
4. Go to Calendar > Meetings, open a form view and click on "Actions". You'll see this new context action named "Send SMS (Calendar Event: Reminder)"
5. Go to Apps and deinstall the app "calendar_sms"
6. Go back to Calendar > Meetings, open a form view and click on "Actions". You'll still see the context action named "Send SMS (Calendar Event: Reminder)". Click on it.

Current behavior:
Traceback:
Record does not exist or has been deleted.
(Record: sms.template(2,), User: 2)
![image](https://user-images.githubusercontent.com/6352350/71375409-63681180-25be-11ea-8e08-714f5111e638.png)

Expected behavior:
Context actions created from SMS templates for the module that you deinstall should be deleted too. They should no longer be kept as the SMS template itself is deleted anyways.

**Comment by Yenthe666** [comment]
OPW `2161653`

**Comment by sswapnesh** [comment]
> Context actions created from SMS templates for the module that you deinstall should be deleted too. They should no longer be kept as the SMS template itself is deleted anyways.

Not sure if this will be handled or not, We have other similar cases too

**Comment by dbo-odoo** [comment]
Hello @Yenthe666 
If you opened an opw, there is no need for a github issue:
- it will not be faster
- if the opw is refused, we won't accept the issue
- there is no added value to doing both (unlike opening an opw and a PR, which is constructive)

In a nutshell: 
- opw + PR = yay
- opw + issue = nay

I'm closing the recent issues you opened where you referenced an opw number.

Thx for your understanding :)
