### ISSUE TITLE
Error message : "Too much recursion" in IE and Firefox

### ISSUE THREAD

**Issue by carrotte2000** [odoo/odoo#4232]
Hello,

I have often the error message : "too much recursion" in IE or Firefox, when I save something. So, I have to refresh the Navigator to close the message, the screen is closed without saving, and I have to start again.
It's the same thing for a Windows local installation or Linux server installation.

  Versions tried with Windows 7 local installation (very few error messages) :
  IE : 9.0
  Firefox : 33.1

  Versions tried with Linux server installation :
  IE : 11.0.13
  Firefox : 31.0
  Chrome : 37.0 

  Thanks for help

**Comment by mvaled** [comment]
This errors may happen when the CIEditor gets data that has non properly nested data.  We have found that some emails we receive if passed to the CIEditor trigger this issue.  The solution is simply to ensure the HTML sent to the CIEditor is well nested.

**Comment by lithint** [comment]
This Issue(Error message : "Too much recursion" in IE and Firefox) 
 is open for a long. Any fix?

**Comment by mart-e** [comment]
Without any useful information (at least the used version and how to reproduce), not likely we will have a fix...

**Comment by Yenthe666** [comment]
Closing as there has been no good feedback and at this point Odoo 7 & Odoo 8 are no longer supported.
