### ISSUE TITLE
[12.0] Odoo Community suddenly not working (Nginx reverse proxy configuration) 

### ISSUE THREAD

**Issue by rubensben** [odoo/odoo#42359]
Hi dear community, something that just happened few days ago, I have looked everything and all the configuration seem to be good but I can't find the issue. 

The problem : by trying to access to https://myodoo.myserver.com and im getting redirected constantly to "https://odoo/web/login"

This problem happened suddenly. Odoo was working perfectly before, no change have been done in the server configuration, just updates "sudo apt-get update":

Impacted versions: 12 Community

Steps to reproduce:

Configuration :
/etc/odoo/odoo.conf

[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons
admin_passwd = hashedpass
csv_internal_sep = ,
data_dir = /var/lib/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter =
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog =
test_enable = False
test_file = False
test_tags = None
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 2
xmlrpc_interface = 127.0.0.1
netrpc_interface = 127.0.0.1

Nginx (all non http requests are transfered to https via return 301 https://$host$request_uri; )

upstream odoo {
server 127.0.0.1:8069;
}
upstream odoochat {
server 127.0.0.1:8072;
}

server {
listen myexternalip:443;
server_name odoo.mydomain ;
client_max_body_size 200M;
proxy_read_timeout 720s;
proxy_connect_timeout 720s;
proxy_send_timeout 720s;

proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;

ssl on;
ssl_certificate /home/admin/conf/web/ssl. odoo.mydomai.pem;
ssl_certificate_key /home/admin/conf/web/odoo.mydomain .key;
ssl_session_timeout 30m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
ssl_prefer_server_ciphers on;
error_log /var/log/apache2/domains/odoo.mydomain.error.log error;

location / {
proxy_redirect off;
proxy_pass http://odoo;
}

location /longpolling {
proxy_pass http://odoochat;
}

location ~* /web/static/ {
proxy_cache_valid 200 90m;
proxy_buffering on;
expires 864000;
proxy_pass http://odoo;
}

location /error/ {
alias /home/admin/web/odoo.mydomain /document_errors/;
}

location @fallback {
proxy_pass https://myextermalip:8443;
}

 common gzip
gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
gzip on;

}​

When checking the service and ports everything looks normal, nothing special in /var/log/odoo/odoo-server.log neither :

root@myserver:~# sudo service odoo status
● odoo.service - Odoo Open Source ERP and CRM
Loaded: loaded (/lib/systemd/system/odoo.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2019-12-24 14:57:06 UTC; 3min 9s ago
Main PID: 27067 (odoo)
Tasks: 11 (limit: 4506)
CGroup: /system.slice/odoo.service
├─27067 /usr/bin/python3 /usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log
├─27094 /usr/bin/python3 /usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log
├─27095 /usr/bin/python3 /usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log
├─27096 /usr/bin/python3 /usr/bin/odoo gevent --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log
├─27097 /usr/bin/python3 /usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log
└─27098 /usr/bin/python3 /usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log

Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_generalledger has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_trialbalance has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_tax has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_agedpartnerbalance has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_journal has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:WARNING:odoo.models:The model report.accounting_pdf_reports.report_financial has no _description
Dec 24 14:57:14 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:INFO:odoo.modules.loading:70 modules loaded in 0.70s, 0 queries
Dec 24 14:57:15 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:INFO:odoo.modules.loading:Modules loaded.
Dec 24 14:57:15 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:INFO:odoo.addons.base.models.ir_http:Generating routing map
Dec 24 14:57:15 mydomain odoo[27095]: Odoo Server 12.0-20190928:odoo-good:INFO:werkzeug:ip - - [24/Dec/2019 14:57:15] "GET / HTTP/1.0" 303 -

Ports : 
odoo 18730 odoo 6u IPv4 5835218 0t0 TCP 127.0.0.1:8069 (LISTEN)
odoo 18763 odoo 6u IPv4 5835218 0t0 TCP 127.0.0.1:8069 (LISTEN)
odoo 18764 odoo 6u IPv4 5835218 0t0 TCP 127.0.0.1:8069 (LISTEN)
python3 18766 odoo 6u IPv4 5836062 0t0 TCP 127.0.0.1:8072 (LISTEN)

Current behavior:
Redirect to https://odoo/web/login 

Expected behavior:
Access to Odoo dashboard

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/4449630/71442371-375ba600-270e-11ea-928c-9d4d18bb2f38.png)

Kindly !

**Comment by sergeiruzkiicode** [comment]
Same issue 
13e deb downloaded 20191225

**Comment by pedrobaeza** [comment]
@d-fence maybe a packaging problem?

**Comment by rubensben** [comment]
Found the solution ! It was an nginx issue, in the config file put like this 

 location / {
   proxy_redirect off;
   proxy_pass http://odoo;
proxy_set_header Host            $host;
 proxy_set_header X-Forwarded-For $remote_addr;
 }

**Comment by pedrobaeza** [comment]
OK, good to know. Closing then.
