### ISSUE TITLE
[13.0] eLearning: Remove Selection on Ratings is not Working

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42362]
Impacted versions: 13.0

Steps to reproduce: Try to Remove Selection for one of them
![Screenshot (10)](https://user-images.githubusercontent.com/16624719/71449480-3446d100-2773-11ea-8e93-6285362aa9ed.png)

Current behavior: It stays there
![Screenshot (11)](https://user-images.githubusercontent.com/16624719/71449485-52accc80-2773-11ea-9d41-94a2ab315dd6.png)

Expected behavior: Should be Removed

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I'm not getting the exact problem.

**Comment by sswapnesh** [comment]
> I'm not getting the exact problem.

I have checked again still the same Behavior.

Can you please send me Screenshot or Am I Missing any steps here?

**Comment by pedrobaeza** [comment]
Checking the screenshots, I don't see that the review stays as it was. Sorry for not seeing it.

**Comment by Yenthe666** [comment]
I'm honestly not seeing the issue either :/ The "4" part is not showing any, the one you have opened is a one star rating?

**Comment by sswapnesh** [comment]
> The "4" part is not showing any

Even if there are 4 stars Ratings, It's not Removed. IMO Section should be Removed regardless of rating is there or not on that part.

**Comment by Yenthe666** [comment]
Okay I see what you mean now. Clicking on "Remove selection" won't actually delete the ratings, they're kept.

**Comment by sswapnesh** [comment]
Clicking on "Remove selection" removes the Filter applied on Reviews (With that Rating number) below.

See: https://youtu.be/sPWDpZrVX5Y
