### ISSUE TITLE
[13.0] Elearning: Inconsistency between Comments/Ratings Count

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42365]
Impacted versions: 13.0

Steps to reproduce: Add Comments/Ratings from Multiple Users on Slide

- **3 Comments + 3 Ratings with Average of 2.33**

![Screenshot (13)](https://user-images.githubusercontent.com/16624719/71449672-f7c9a400-2777-11ea-8e14-cb9123998630.png)

- Unpublish 2 or one of them and Observe  Comments/Ratings'  Count

Current behavior:
![Screenshot (14)](https://user-images.githubusercontent.com/16624719/71449685-45461100-2778-11ea-9b5f-a03520ce3b27.png)

In this case, 

- Comments count is Including Unpublished Comments
- Rating count is not Including Unpublished Comments

Expected behavior: Comments/Rating Count should Include or Exclude Unpublished Comments

Rating count should be 2.33 or Comments Count should be 1

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please report only one thing per issue.

About the number of comments, it appears 3 because you are seeing the slide with a backend user with permissions to see unpublished comment, so the number is put accordingly that. Please try with other user and you'll see the correct number.

About the rating, that one is computed and can have only one value, so the "correct" one without counting unpublished comments is put for everyone.

Closing this then as no valid.

**Comment by sswapnesh** [comment]
> Please report only one thing per issue.

This was about Inconsistency between two Numbers (So I had to compare both fields)

> About the number of comments

Yes, You are right

> About the rating

As we seeing this from backend it should Count Unpublished Ratings (As it's doing in the case of comments)

**Comment by pedrobaeza** [comment]
> As we seeing this from backend it should Count Unpublished Ratings (As it's doing in the case of comments)

Being a store field, it can't be.

**Comment by sswapnesh** [comment]
In that case, we should keep this issue open.

**Comment by pedrobaeza** [comment]
I don't think so. I see the behavior correct, as unpublished comment shouldn't count for the rating.

**Comment by sswapnesh** [comment]
According to my Ideal behavior, It should be

For Backend Users:
 - Count Unpublished Comments (Works :heavy_check_mark: now, As count is 3) 
 - Ratings Count, It should Take Average from All Rating Including ones from Unpublished Counts as well (As it includes Unpublished comments then it should be the same logic to Count Ratings)

**Comment by pedrobaeza** [comment]
As said, that's not possible, but it's not a problem and get consistency on rating computation.
