### ISSUE TITLE
[13] Do not load social share dialog on blank question/answer on Forum 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42363]
Impacted versions: 13.0

Steps to reproduce: Post Empty Question
![Screenshot from 2019-12-26 00-09-04](https://user-images.githubusercontent.com/16624719/71449541-6a388500-2774-11ea-816e-df51ed234af7.png)

Current behavior:
![Screenshot from 2019-12-26 00-08-18](https://user-images.githubusercontent.com/16624719/71449515-de265d80-2773-11ea-8be3-cccdd4de989f.png)

Expected behavior: Do not allow Empty Questions

Video/Screenshot link (optional):

Duplicate of https://github.com/odoo/odoo/issues/28697 and was supposed to be solved in https://github.com/odoo/odoo/issues/28697#issuecomment-445182739
 @JKE-be  Am I missing something here? (Not sure)

**Comment by Yenthe666** [comment]
OPW `2168116`

**Comment by Yenthe666** [comment]
Discussed with Odoo. It won't be changed in stable versions but they've made a feedback ticket for future versions.
