### ISSUE TITLE
[13.0] Re-attaching Attachment Doesn't work on "Add a review"

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42364]
Impacted versions: 13.0

Steps to reproduce: 
![Screenshot (12)](https://user-images.githubusercontent.com/16624719/71449569-49bcfa80-2775-11ea-9966-b605258481b1.png)

Select any attachment and Remove it
![Screenshot from 2019-12-26 00-19-00](https://user-images.githubusercontent.com/16624719/71449573-5f322480-2775-11ea-8f25-b84e17c9f4f6.png)

Current behavior: You can not select the same attachment again

Expected behavior: Able to select the attachment again

Video/Screenshot link (optional): https://www.youtube.com/watch?v=KVa5iTPcBaw&feature=youtu.be

**Comment by pedrobaeza** [comment]
Why do you want to add twice the same attachment?

**Comment by sswapnesh** [comment]
I just discovered this when I accidentally Removed the Attachment I wanted to add. (And I got this Bug)

**Comment by pedrobaeza** [comment]
But why is it a bug? I see correct to not put twice the same attachment, although you command to do it.

**Comment by sswapnesh** [comment]
Select Attachment "ABC.png" --> Remove it --> Select "ABC.png" --> It doesnt work at all (No any updates on view/No warning)

This same thing works at 
![Screenshot (14)](https://user-images.githubusercontent.com/16624719/71548212-17a7d480-29d1-11ea-9b61-8dfa5bd5701b.png)

**Comment by pedrobaeza** [comment]
OK, now I understand you. Indeed it should work. Tagging.

**Comment by sswapnesh** [comment]
I don't think this is Related to Marketing as I can Reproduce this at 

![Screenshot (29)](https://user-images.githubusercontent.com/16624719/71558448-8b9db780-2a79-11ea-92e6-abc36c7c2121.png)

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/61597
