### ISSUE TITLE
[12/13] repair: Add validation on Unlink of Repair Orders based on States

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42370]
Impacted versions: 12/13

Steps to reproduce: Create Repair Order --> Perform Operations (Confirm/Complete it/Create Invoices)

Current behavior: Current Functionality doesn't Restrict Unlink of Order Based on States (Unlike Everywhere Unlink of the record is allowed in Draft stage only) 

Expected behavior: Add Validation on Unlink based on State, 
Eg, Order should be deleted only in Draft state

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@sle-odoo Maybe an Internal task for this one?

**Comment by sle-odoo** [comment]
https://github.com/odoo/odoo/pull/45888

**Comment by sswapnesh** [comment]
@sle-odoo  I think we can close this one as this had been handled in master.

-------------------------
Moreover, Can we add a currency too? (Making float fields as monetary) 
We already have Pricelist there.
