### ISSUE TITLE
[8.0] Waiting on other operation moves stuck if reservation canceled and assigned to other order

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#4237]
Once you cancel the reservation on a linked waiting move that has been assigned, it is never possible to get a new assignment unless you force availability

Steps to reproduce:
Product A make to order with Supplier A

2 sales orders for Product A
sale A qty 2
sale B qty 3

Confirm PO for 5 units
Receive only 2 units.

Sale A delivery order is made available automatically.
Cancel reservation on delivery order
Perform adjustment of inventory to 3 of product A
Force availability on Sale order B delivery order.
Transfer goods.

Receive remaining product from vendor A OR do another adjustment to have sufficient quantity to fulfill order A.

Order A is now infinitely stuck in waiting on other operation. Check availability will fail. Scheduler will fail. There is no way to make delivery order A available unless you force availability.

This is not a good business practice, but this could happen, and this is not the only way to reproduce this problem. There are several ways.

CAUSE:
in method do_reserve: https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L1830
the product goes back to a waiting other operation when the reservation is canceled because the move has ancestors. Once the inventory is assigned to any other order, the history on stock.quant is lost.

This problem cascades to requesting availability because it will attempt to use a domain filter to find quants that have history of ancestor: 
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2188 

IMO once product is received and the linked sales delivery order is made available, the M2O transaction is complete. If a user wants to cancel the reservation, it should not maintain the link and use the inventory in the warehouse for future requests of availability.

it should unlink the move_dest_id on the ancestor moves in method do_unreserve()  so it will flow normally since the M2O transaction was already completed.

**Comment by jco-odoo** [comment]
The notion of move_dest_id and ancestors is important because when something is MTO e.g., it should come from the purchase order/ sale order/... it was meant for.  The force availability is the way to go around that.  And doing the unreserved move in the same way was simplest and most straightforward.  

Maybe you unreserve and afterwards, you still change your mind...  But on the other hand when you take quants from another move, you could put that other move in a 'waiting availability' state.  (but what if it is only partially, ...)

**Comment by aliomattux** [comment]
Hello,

You didn't touch base on the fact that when you force and cancel, or cancel, the move is infinitely stuck. I already wrote a module that addresses this problem. There are lots of business cases where a user would want to cancel the move and assign it 'naturally'.

Forcing the user to 'Force Availability' as the only option to bypass the problem is awkward from a business process standpoint and bypasses any allocation logic the system provides. An example case would be a user has a product defined to order from supplier. The PO is created, but later the product is transferred or received from another warehouse/supplier. There is now no need for this waiting move.

The user should be able to cancel the move, the inventory will auto allocate if available and go to waiting availability. There needs to be a mindset that there is more than one workflow, and not only one way to process a picking

**Comment by m3asmi** [comment]
same issue here 
did you solve it ?

**Comment by Yenthe666** [comment]
Hi @aliomattux,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
