### ISSUE TITLE
[7.0] New Location error

### ISSUE THREAD

**Issue by antoniofcano** [odoo/odoo#4241]
When I try to create a new location into the stock app, I get this error:

File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20140630_231039-py2.7.egg/openerp/osv/orm.py", line 4540, in create
    cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

I found into the orm.py file that chaging this line (4534) it works fine:
                    Old: pleft = pleft_old
                    New: pleft = pleft_old or 0

**Comment by Yenthe666** [comment]
Hi @antoniofcano ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
