### ISSUE TITLE
[7.0] Allow saving journal item without amount in currency

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#4242]
On version 7.0
- Create a new journal entry
- Choose a journal in a secondary currency
- Create a journal item with an amount in debit or credit and choose a secondary currency
- Create a second journal item that balance with the first one
- Save

Result: Journal entry is saved.

Expected result : An error message "The amount in the secondary currency is missing."

![amount_in_currency](https://cloud.githubusercontent.com/assets/939952/5430045/0742eada-83d2-11e4-9665-e97f5fbb6566.png)

**Comment by Yenthe666** [comment]
Hi @max3903 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
