### ISSUE TITLE
[13.0] [Wishlist] Add Custom Hours duration on Leave name

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42438]
Impacted versions: 13.0 (Maybe 12.0 too)

Steps to reproduce: Add Leave for custom Hours

![Screenshot (26)](https://user-images.githubusercontent.com/16624719/71549538-09fc4a00-29e5-11ea-9dd8-884619836b1f.png)

Current behavior: See the Leave name (Sharlene Rhodes on Compensatory Days : 0.00 hours)
![Screenshot (25)](https://user-images.githubusercontent.com/16624719/71549525-ea652180-29e4-11ea-9a9b-01841cf4465a.png)

Expected behavior: It should be displayed as "Sharlene Rhodes on Compensatory Days : hh:mm hours"

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's because the leave is outside working calendar, so no leave hours at all.

Closing by that reason.
