### ISSUE TITLE
[13.0]  Tracback on Post entries from Invoices List

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42434]
Impacted versions: 13.0

Steps to reproduce: Runbot http://802424-13-0-b02404.runbot22.odoo.com/web
![Screenshot (18)](https://user-images.githubusercontent.com/16624719/71548783-52156f80-29d9-11ea-99fa-ec22040f1013.png)

Current behavior:
![Screenshot (17)](https://user-images.githubusercontent.com/16624719/71548784-53469c80-29d9-11ea-8c6f-2734a584a257.png)

Expected behavior: Post Entries

Video/Screenshot link (optional):

Ps: Works well on Posting Individual Invoice

**Comment by mart-e** [comment]
@william-andre could you have a look? Looks like due to 5b745eb61377e5b4532f2e370f9b1559a9b66c0a
My guess is that `m.ref` is not defined in some of the records, so a `m.ref or ''` should fix it (but did not tested)
