### ISSUE TITLE
Doubles Pos tickets V13

### ISSUE THREAD

**Issue by NAJEM-BRAHIM** [odoo/odoo#42430]
Impacted versions:  ODOO POS (V13)

Steps to reproduce:  In POS V13 I get double sales with the same ticket number, 

Current behavior: Odoo pos v13 I always find some double tickets this happens 3 to 4 times a day

Expected behavior: I mean that in 100 sales it always doubles some

Video/Screenshot link (optional):
![Captura](https://user-images.githubusercontent.com/8737971/71547211-4e63f780-299d-11ea-8367-8d20bfa3eb0a.JPG)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment]
Similar to #42367, but both lacks information to reproduce the problem.

**Comment by NAJEM-BRAHIM** [comment]
It is a clean installation without extra modules, it is a database with 3 points of sale. The error occurs without time logic.example yesterday there are no double tickets today if sometimes it is doubled and sometimes up to 20 times the same ticket

**Comment by pedrobaeza** [comment]
Yeah, but not having the logic behind the error, it's barely impossible to be solved.

**Comment by NAJEM-BRAHIM** [comment]
for 2 days I am looking for sales lines if there is an article or a barcode causing the problem but I cannot find an answer

**Comment by NAJEM-BRAHIM** [comment]
for the second time he left a point of sale without internet until he accumulated more than 90 tickets in the cache and in this case they went up to the backend without doubles

**Comment by pedrobaeza** [comment]
I don't get what you mean

**Comment by Yenthe666** [comment]
Please provide us with a video or clear to reproduce steps. Otherwise we can't really help you and there's a good chance that this ticket will be closed off.

**Comment by NAJEM-BRAHIM** [comment]
I can not reproduce the problem, for example today we had only 2 double tickets, but yesterday many doubles there is no time logic.

**Comment by NAJEM-BRAHIM** [comment]
Pedro lo quería decir es que   deje al punto de venta sin internet todos los tickets de venta acumulados en el caché más de 90 subieron al servidor sin dobles

**Comment by NAJEM-BRAHIM** [comment]
Yesterday we have canceled more than 100 tickets

![Screenshot_20191229-173935_Gallery](https://user-images.githubusercontent.com/8737971/71560482-bfbdac00-2a6a-11ea-9857-6e83a40a5509.jpg)

**Comment by NAJEM-BRAHIM** [comment]
today I have only 2 doubles, and with the same ticket reference

![20191229_174218](https://user-images.githubusercontent.com/8737971/71560531-3d81b780-2a6b-11ea-9162-46139f14bfd2.jpg)

**Comment by Yenthe666** [comment]
@pimodoo does this ring any bells to you?

**Comment by NAJEM-BRAHIM** [comment]
Non

**Comment by pimodoo** [comment]
@NAJEM-BRAHIM Hello, it seems that we fixed only partially the code in this commit: https://github.com/odoo/odoo/pull/40600

We'll re-fix it for your use case.

**Comment by pimodoo** [comment]
@NAJEM-BRAHIM I've just retest the 13.0 with the commit from PR #40600, and was not able to reproduce the bug. Are you sure your code is up to date?

**Comment by NAJEM-BRAHIM** [comment]
I will update the code and keep you informed thanks

**Comment by NAJEM-BRAHIM** [comment]
the problem solved after the update thank you @pimodoo @Yenthe666
