### ISSUE TITLE
[12.0] Trying to mass delete all vendors on product

### ISSUE THREAD

**Issue by unproZhai** [odoo/odoo#42439]
Impacted versions: 12

Steps to reproduce: N/A

Current behavior: All imports are doing nothing but adding new vendors

Expected behavior: Delete all vendors on product through import or through other methods? 

Video/Screenshot link (optional): I know insertions and modifications are possible through csv file, but I don't know bout deletion. Or can I delete the vendor ids or connections in database? The reason I asked is I imported extra vendors for the wrong product massively. So what should I do to clean up the vendors on products?

**Comment by sswapnesh** [comment]
>  So what should I do to clean up the vendors on products?

There is no Specific Menu/Action for  "vendors on products", You have to delete it directly from Database. (Or Just Create the corresponding Action and Delete them)

**Comment by pedrobaeza** [comment]
Yeah, that's something not supported, so closing.
