### ISSUE TITLE
[Odoo Critical] XMLRPC Didn't receive 200 OK from remote server. (HTTP/1.1 301 Moved Permanently

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#4244]
We getting below issue during rpc communication.

XMLRPC Didn't receive 200 OK from remote server. (HTTP/1.1 301 Moved Permanently

Can you please quick update on this.

**Comment by xmo-odoo** [comment]
We'd need more information there, what is the RPC endpoint you're hitting and how are you hitting it?
