### ISSUE TITLE
[13] Customers crerated from Sales/Repair are not visible under Customers Menu

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42449]
Impacted versions: 13.0

Steps to reproduce: Create Customer from Sale Order's from view
![Screenshot (40)](https://user-images.githubusercontent.com/16624719/71560775-11c6f780-2a94-11ea-8f42-79dfb7782418.png)

Current behavior:
Newly created Customer Is not Visible on  Customer's List

![Screenshot from 2019-12-29 23-37-23](https://user-images.githubusercontent.com/16624719/71560788-30c58980-2a94-11ea-83ce-9aaafc779152.png)

Expected behavior: Same things work on Invoice Form 
![Screenshot (38)](https://user-images.githubusercontent.com/16624719/71560719-8baab100-2a93-11ea-90e2-ad2af99d5827.png)
![Screenshot (39)](https://user-images.githubusercontent.com/16624719/71560728-97967300-2a93-11ea-85fa-84e4939d068d.png)

Video/Screenshot link (optional):

**Comment by Feyensv** [comment]
In sales, it seems to work for me (but for repair, the new customer isn't recognized as a customer indeed).
