### ISSUE TITLE
[13.0] [im_livechat] in LiveChat Support link in Website Don't Work.

### ISSUE THREAD

**Issue by odoo-backend-dev** [odoo/odoo#42441]
Don't popup livechat in support url
http://803348-13-0-9d1a29.runbot16.odoo.com/im_livechat/support/1
![Screenshot from 2019-12-29 11-00-29](https://user-images.githubusercontent.com/58971895/71553779-70f02200-2a2a-11ea-92d3-a592cdab31fa.png)

**Comment by pedrobaeza** [comment]
That's something configurable in options, so closing as no valid.
