### ISSUE TITLE
Style Error after installing Odoo V11 at the login page 

### ISSUE THREAD

**Issue by hkbluesky** [odoo/odoo#42440]
IHi, I have a fresh installation of odoo V11 and got this error at the login page. Does anyone know how to solve the problem? Thanks

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

(b'', b'TypeError: sys.print is not a function
at /usr/lib/nodejs/less/bin/lessc:384:25
at tree.importVisitor.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)
at tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)
at Object.parse (/usr/lib/nodejs/less/lib/less/parser.js:675:22)
at parseLessFile (/usr/lib/nodejs/less/bin/lessc:345:12)
at Socket. (/usr/lib/nodejs/less/bin/lessc:407:9)
at Socket.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1184:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
')This error occured while compiling the bundle 'web.assets_common' containing:
- /web/static/lib/bootstrap/less/variables.less
- /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
- /web/static/lib/bootstrap/less/mixins/buttons.less
- /web/static/lib/bootstrap/less/mixins/clearfix.less
- /web/static/lib/bootstrap/less/mixins/size.less
- /web/static/src/less/variables.less
- /web/static/src/less/utils.less
- /web_editor/static/src/less/web_editor.variables.less
- /web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less
- /web/static/src/less/fonts.less
- /web/static/src/less/navbar.less
- /web/static/src/less/mimetypes.less
- /web/static/src/less/modal.less
- /web/static/src/less/animation.less
- /web/static/src/less/rainbow.less
- /web/static/src/less/datepicker.less
- /web_planner/static/src/less/web_planner_common.less
- /web_tour/static/src/less/tip.less
- /web_tour/static/src/less/keyframes.less

![image](https://user-images.githubusercontent.com/47656333/71550439-46f11e00-299e-11ea-9b69-7a27dc726d38.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by theodcr** [comment]
Hi, I had the same problem on Ubuntu 18.04 and solved it by installing less with `sudo npm install -g less` (as recommended in the documentation) instead of `sudo apt install node-less` (as I had seen somewhere on a forum). Hope it can help.
