### ISSUE TITLE
[13.0] Public profile is not Visible on Website

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42446]
Impacted versions: 13.0

Steps to reproduce: Make User Profile Visible from Settings

![Screenshot (32)](https://user-images.githubusercontent.com/16624719/71560168-4a62d300-2a8c-11ea-9664-f44bbadb6f5b.png)

Current behavior: Public profile is not Visible on Website
![Screenshot from 2019-12-29 22-37-12](https://user-images.githubusercontent.com/16624719/71560122-c90b4080-2a8b-11ea-8132-d0e47ec1843e.png)

Expected behavior: Profile should be visible

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
OPW `2168113`

**Comment by Yenthe666** [comment]
This was the final response:

> Public profile are not meant to be visible by unregistered/anonymous users. In this context, public means "internally public".
to be able to see a public profile, you need to both be signed in as a user and have the minimum karma required (150 if you are using the demo data)
so basically with the demo data, only your admin user has enough karma to see public profiles
Here is the code:
https://github.com/odoo/odoo/blob/c395eb91c769ea4bd3b74b89b0ee980f4169c3e0/addons/website_profile/controllers/main.py#L40-L48

**Comment by sswapnesh** [comment]
> public means "internally public".

:thinking:

**Comment by Yenthe666** [comment]
Yeah I know, but they really didn't want to change it :-/
