### ISSUE TITLE
[12.0/13.0] Option always_reload is not Working 

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42444]
Impacted versions: 12.0/13.0

Steps to reproduce: Notice the Partner field with `options="{&quot;always_reload&quot;: True}"/>` applied
Eg,
V11 at http://803566-11-0-567ca3.runbot17.odoo.com/web?#id=30&view_type=form&model=sale.order&menu_id=521&action=696
![Screenshot (30)](https://user-images.githubusercontent.com/16624719/71558675-cc96cb80-2a7b-11ea-88a1-0aa4e58f576b.png)

Current behavior: No Such Detailed Address on V12/V13
![Screenshot (31)](https://user-images.githubusercontent.com/16624719/71558688-ee904e00-2a7b-11ea-8661-f474851b8d62.png)

Expected behavior: Full Detailed Address should be displayed (Same as 11)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
`alway_reload` option is not for showing full address AFAIK.

**Comment by Yenthe666** [comment]
> always_reload: boolean, default to false. If true, the widget will always do an additional name_get to fetch its name value. This is used for the situations where the name_get method is overridden (please do not do that)

As far as I know it has nothing to do with the full address so I agree with Pedro. There is no issue here?

**Comment by pedrobaeza** [comment]
I think the reason for this problem is #42401, but it's applied on 12 in that PR.

**Comment by sswapnesh** [comment]
@pedrobaeza  PR #42401 Fixes this behavior 
Tested on http://815470-12-0-46bf72.runbot25.odoo.com/web?#id=4&action=804&model=sale.order&view_type=form&menu_id=552 and seems to be working well

![Screenshot (46)](https://user-images.githubusercontent.com/16624719/71682579-1e11c400-2db6-11ea-9529-3d260ed3bf05.png)


This can be closed

**Comment by luisg123v** [comment]
FYI this was successfully forward-ported to 13.0, which was the other version this issue was reported for.
