### ISSUE TITLE
[13.0] [Wishlist] Document Button should be Invisible if Related record is no longer available

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42450]
Impacted versions: 13.0

Steps to reproduce: Create Calendar Event from Lead
![Screenshot (41)](https://user-images.githubusercontent.com/16624719/71560971-14c2e780-2a96-11ea-88a2-4851b421f4cb.png)
![Screenshot from 2019-12-29 23-51-18](https://user-images.githubusercontent.com/16624719/71560975-24dac700-2a96-11ea-9e22-4b6647af7978.png)
![Screenshot (42)](https://user-images.githubusercontent.com/16624719/71560980-42a82c00-2a96-11ea-835a-6f1ec40ae8a0.png)

**Delete the Source Lead** 

Current behavior:
Still 'Document' is visible which Does nothing

Expected behavior: Button should be Invisible or There should Waring saying Record no longer exists.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this is a bit elaborated, but let's tag it as wishlist

**Comment by MiquelRForgeFlow** [comment]
This issue should be closed.
