### ISSUE TITLE
Test test_13_m2o_order_loop_multi failing on CI

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#42468]
#### Impacted versions:
12.0 (13 not tested)
#### Steps to reproduce:
Create a CI pipeline
#### Current behavior:
When testing, the test `test_13_m2o_order_loop_multi `fails

```python
Step #2: 2019-12-30 09:34:55,383 1 ERROR  project-12.0-aa9ae6f odoo.modules.module: Module base: 1 failures, 0 errors 
Step #2: 2019-12-30 09:34:55,381 1 INFO  project-12.0-aa9ae6f odoo.addons.base.tests.test_search:  (failures=1) 
Step #2: 2019-12-30 09:34:55,381 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: FAILED 
Step #2: 2019-12-30 09:34:55,380 1 INFO  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: Ran 5 tests in 0.600s 
Step #2: 2019-12-30 09:34:55,380 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` + [46, 48, 47, 45] 
Step #2: 2019-12-30 09:34:55,380 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` - [47, 45, 46, 48] 
Step #2: 2019-12-30 09:34:55,379 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: `  
Step #2: 2019-12-30 09:34:55,379 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` 46 
Step #2: 2019-12-30 09:34:55,379 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` 47 
Step #2: 2019-12-30 09:34:55,378 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` First differing element 0: 
Step #2: 2019-12-30 09:34:55,378 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: `  
Step #2: 2019-12-30 09:34:55,378 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ` AssertionError: Lists differ: [47, 45, 46, 48] != [46, 48, 47, 45] 
Step #2: 2019-12-30 09:34:55,377 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: `     self.assertEqual(found_ids, expected_ids) 
Step #2: 2019-12-30 09:34:55,377 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: `   File "/opt/odoo/odoo/addons/base/tests/test_search.py", line 150, in test_13_m2o_order_loop_multi 
Step #2: 2019-12-30 09:34:55,377 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: Traceback (most recent call last): 
Step #2: 2019-12-30 09:34:55,376 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: FAIL: test_13_m2o_order_loop_multi (odoo.addons.base.tests.test_search.test_search) 
Step #2: 2019-12-30 09:34:55,376 1 INFO  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: ====================================================================== 
Step #2: 2019-12-30 09:34:55,375 1 ERROR  project-12.0-aa9ae6f odoo.addons.base.tests.test_search: FAIL 
```

#### Expected behavior:
No test failing or having a way to track this behavior. What could cause something like this?

**Comment by gustavovalverde** [comment]
Related? https://github.com/odoo/odoo/issues/42432

**Comment by pedrobaeza** [comment]
Is this failing in Odoo runbot?

**Comment by gustavovalverde** [comment]
It's not, I even tested with the same modules on v11 (the test is passing), in v12 is not, different repositories, none of them modifying the order of m2o fields.

**Comment by pedrobaeza** [comment]
Then it should be something on your pipeline.

Unless you provide steps to reproduce the problem here in Odoo, this can't be fixed. Closing meanwhile.

**Comment by jansier** [comment]
This test is also failing for me on a fresh Odoo 13 installation. And as far as I understand it should fail:
users in this test are first ordered by related partner which is ordered by 'create_uid, name'.
Tests are run as odoo bot user (id=1, always?) u1 and u3 are created by this user, while u2 and u4 are created by some new users with higher ids.
So u3 and u1 should be before u2 and u4 on the list in found_ids?
Probably I misunderstood something in this test, could anybody explain? @pedrobaeza ?

**Comment by jansier** [comment]
Well, it's a fresh install without any custom modules. But could you explain why expected_ids should be in this order? [u2, u4, u3, u1] If my understanding of the test is correct it should indeed be [u3, u1, u2, u4], like in the example from gustavovalverde, so most probably the way I understand the test is wrong ;)

**Comment by pedrobaeza** [comment]
Sorry, I haven't dug to that detail, as my role only belongs to redirect issues to the suitable persons in Odoo as a voluntary effort, and if we don't have such error in runbot tests, then this is not something to be analyzed by that people.

You can do your query on the forums for other contributors to try to answer you.

**Comment by findsomeoneyys** [comment]
i try use github actions to run test with odoo， and i meet same problem here...

at before i use this [config](https://github.com/findsomeoneyys/sample_test_module/blob/baf8045ee7613c49a949be765fe6e32aab77497a/.github/workflows/odoo-test.yml), it use the iamge `postgres:10 `, and in [GITHUB CI](https://github.com/findsomeoneyys/sample_test_module/runs/572565485?check_suite_focus=true), it fails

and finally i use the image `postgres:10-alpine`, in this [CI](https://github.com/findsomeoneyys/sample_test_module/runs/572625054?check_suite_focus=true) every thing works fine.

but i don't know why...is this a postgresql problem?

**Comment by gustavovalverde** [comment]
@KangOl @rco-odoo This test is failing me using **Github Actions** and **Cloud Build**. Why changing the database image would have an impact on this test? 

It hard to say if it's an Odoo bug or an environment bug, as this behavior requires some very deep understanding on the reason why this test exists.

I'd be glad to test further, but I'd also need a bit of information on what I might need to look at.

**Comment by gustavovalverde** [comment]
I can confirm that changing the database to use the `*-alpine` version does not crash this test in **Cloud Build** also.

But this does not explain why the test fails with the official debian-based variant.

@pedrobaeza let's keep this open, as this is an odd behavior with an installation without extra modules; and other people might be having this same issue, and I'm not sure if you know how the official runbot postgres has been installed. Is it the alpine version a requirement for CI tools?

**Comment by pedrobaeza** [comment]
I can't say, but AFAIK having an opened issue for failing tests in certain conditions (maybe packaging) is not the purpose of this issue tracker, but detecting issues on code itself. if any of Odoo stuff considers so, he/she can reopen it.

**Comment by gustavovalverde** [comment]
I don't think there's another place to report this type of issues. If there's doubt (considering there's an actual issue) closing it shouldn't be the default decision.

**Comment by llacroix** [comment]
It's definitely a bug in the test not that the code doesn't work as it should.

The test is a self referential test as create_uid is a res.users. It will test that fields are properly dereferenced so the actual sort order is

partner_id.create_uid.login desc,
partner_id.name
login desc

Or at least it's what should it be or something close to it...

The issue thought is this:

The user for which user u1 and u3 are create has for login "__system__". This will fail the order based on the collation used for the database.

In collate "C", _ is before letters, but in en_US.utf-8 it will be after. So a better test would test with a user with its login with letters to prevent the strange behaviour that break some systems...

**Comment by yhaelopez** [comment]
> I can confirm that changing the database to use the `*-alpine` version does not crash this test in **Cloud Build** also.
> 
> But this does not explain why the test fails with the official debian-based variant.
> 
> @pedrobaeza let's keep this open, as this is an odd behavior with an installation without extra modules; and other people might be having this same issue, and I'm not sure if you know how the official runbot postgres has been installed. Is it the alpine version a requirement for CI tools?


I can continue to confirm that this issue is gone when I changed from postgres:15.1 to  postgres:15.1-alpine.

**Comment by devKanapka** [comment]
Tried running unit tests for Odoo 13 in Docker container.
Got same issue which was fixed after changing docker image from postgres:15.3 to postgres:15.3-alpine.
