### ISSUE TITLE
Create an individual contact associated with a company - should be in the same company

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#42522]
Impacted versions: **13**

Steps to reproduce: **Create a "company" contact in a company (e.g. Demo Company).  Then create an individual contact that is linked to the company contact.**

Current behavior: **Individual contact is set with blank company**

Expected behavior: **Should have same company as the parent**

**Comment by pedrobaeza** [comment]
Reviewing this, I don't think it should behave that way, as each contact can be linked independently to one company or other, as the general default is the one that applies (you can define a default for your company if you want).

Example:

- Parent contact "Customer A" without company_id for being seen in both companies X and Y in the DB.
- Children contact "Contact A1" only visible in company X.
- Children contact "Contact A2" only visible in company Y.

**Comment by ctringham** [comment]
The scenario you describe seems possible but unlikely!!  

It seems far more probable that if a user in company X creates a contact for Customer A they would expect it to be visible in both Companies X and Y.  If it's not shared, then they (or someone else) in Company Y (who can't see the contact) might create it again.

But the problem I reported was the other way around.  That a customer is in Company A only, so the contact should also be in Company A.

**Comment by pedrobaeza** [comment]
@tivisse not sure if you are the suitable for judging this. Probably a `'default_company_id': parent.company_id` in the context is enough for this and can be valuable. Any way, I doubt this change should be in stable, but for next version.

**Comment by tivisse** [comment]
Hi ! 

Thanks for the feedback. I tend to agree with Pedro.

I've created a feedback so that the product owners may take functional decision. ;)

We'll keep you updated. 

Have a nice day,

Yannick.
