### ISSUE TITLE
[12.0,13.0] hr_timesheet: reassign project on task  does not change in the timesheet.

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#42521]
Impacted versions:
12.0, 13.0

Steps to reproduce:
Create a task, assign a  project
assign to self, add a timesheet line. Save. Edit, change project and
 Open Timesheet app, go in "My Timesheets" (use list view for simplicity),
search the timesheet line.

Current behavior:
The project id will be the original one,  this is because the project_id is not propagated
during the modification.

Expected behavior:
Project id on timesheet lines must be updated with the project set on the task
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10233975/71608897-fe766380-2b49-11ea-8b34-ef3dec8df948.png)

**Comment by pedrobaeza** [comment]
@rafaelbn is this the same you reported?

**Comment by rafaelbn** [comment]
OPW #2077380 26th september 2019

**Comment by Yenthe666** [comment]
26'th of september 2019? In what state is that ticket then?

**Comment by hugho-ad** [comment]
Hardik Jetalpuriya (hje) said:

![image](https://user-images.githubusercontent.com/10233975/71835228-a2926a00-3076-11ea-9b8f-6dcd6479a109.png)

> As we explicitly did not want to move the timesheet from the project because it can change the currency of the project overview,

When reassigning a new project on task, users must be explicitly notified about this, I think this is totally a user's decision.

> Also, the cost of the timesheet will be transferred to the new project.

Transfer the cost to the new project is what I expected

**Comment by Yenthe666** [comment]
Hmm makes sense to me. So basically this won't be changed and this report can be closed, right?
