### ISSUE TITLE
[13.0][Enterprise] Cannot add landed cost to receipt of a subcontracted product

### ISSUE THREAD

**Issue by rainierking** [odoo/odoo#42535]
Impacted versions: 13

Steps to reproduce:
1. Create a subcontractor contact
2. Create a component product
3. Create a subcontracted product with route Resupply Subcontractor on Order
4. Create a BoM of subcontracted product with the ff. details
    - Subcontractor: contact created in Step 1
    - Component: product created in Step 2
5. Purchase and receive component product so that it will have stock
6. Purchase and receive subcontracted product
7. Create landed cost for receipt in Step 6
8. Compute then validate

Current behavior:
Odoo Error occurs

Expected behavior:
Landed cost validation is successful and valuation of received subcontracted product is updated

Video/Screenshot link (optional):
![Screenshot from 2019-12-31 19-27-32](https://user-images.githubusercontent.com/19146898/71620775-ba956400-2c06-11ea-8314-f3d8365d8961.png)

Additional Info:
Adding landed cost for a purchase of a non-subcontracted product works fine

**Comment by pedrobaeza** [comment]
Please report it through odoo.com/help instead of here for effective handling of the enterprise support team.

**Comment by rainierking** [comment]
I understand. Will now close this issue. Thank you very much.
