### ISSUE TITLE
Some users are not showing in the ranking page in odoo.com/profile/users.

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#42549]
Impacted versions:
current odoo.com website
Steps to reproduce:
visit [https://www.odoo.com/profile/users/page/10](https://www.odoo.com/profile/users/page/10) and you will not be able to find my profile [https://www.odoo.com/profile/user/621858](https://www.odoo.com/profile/user/621858), now I should be in page 10 because my XP is 5048. Also one of my friends has the same issue. I think many users are not showing for some reason!

**Comment by pedrobaeza** [comment]
Your profile is private, and that's why it doesn't appear there.

**Comment by Yenthe666** [comment]
Yep, private profiles are not shown.

**Comment by obayit** [comment]
Thanks.
I just edited my profile and set the boolean field "Public Profile". Now I am listed in the ranking :)

![Screenshot from 2020-01-02 00-00-20](https://user-images.githubusercontent.com/20386024/71644711-eb52c780-2cf2-11ea-8af8-f6cfdc3d8163.png)
