### ISSUE TITLE
Error when using data parameter in report_action function

### ISSUE THREAD

**Issue by mehdibenhac** [odoo/odoo#42544]
Impacted versions:
12.0

Steps to reproduce:
Call the **report_action** function with both **docids** and **data** parameters: `self.env.ref('module.report_id').report_action(self, data=data)`
on a report that has the **attachment** attribute set to anything other than False: 
```
<report id="report_id" [...] attachment="True"  />
```

Current behavior:

This will throw an error, because the **docids** necessary for the report to be attached to the record(s) are not correctly set in the conditional bloc of the  **_makeReportUrls** function declared in the **action_manager_report.js** file:
```
_makeReportUrls: function (action) {
        var reportUrls = {
            html: '/report/html/' + action.report_name,
            pdf: '/report/pdf/' + action.report_name,
            text: '/report/text/' + action.report_name,
        };
        // We may have to build a query string with `action.data`. It's the place
        // were report's using a wizard to customize the output traditionally put
        // their options.

        if (_.isUndefined(action.data) || _.isNull(action.data) ||
            (_.isObject(action.data) && _.isEmpty(action.data))) {
            if (action.context.active_ids) {
                var activeIDsPath = '/' + action.context.active_ids.join(',');
                reportUrls = _.mapObject(reportUrls, function (value) {
                    return value += activeIDsPath;
                });
            }
        } else {
            var serializedOptionsPath = '?options=' + encodeURIComponent(JSON.stringify(action.data));
            serializedOptionsPath += '&context=' + encodeURIComponent(JSON.stringify(action.context));
            reportUrls = _.mapObject(reportUrls, function (value) {
                return value += serializedOptionsPath;
            });
        }
        return reportUrls;
    },
```
This ends up returning a url like this one: /report/pdf/[MODULE.REPORT_ID]**?options=...**
whereas it must return this for it to properly work: /report/pdf/[MODULE.REPORT_ID]**/[IDS]**

Once the url is generated, it is used to call on this controller:

```
 @http.route(['/report/download'], type='http', auth="user")
    def report_download(self, data, token):
        """This function is used by 'action_manager_report.js' in order to trigger the download of
        a pdf/controller report.

        :param data: a javascript array JSON.stringified containg report internal url ([0]) and
        type [1]
        :returns: Response with a filetoken cookie and an attachment header
        """
        requestcontent = json.loads(data)
        url, type = requestcontent[0], requestcontent[1]
        try:
            if type in ['qweb-pdf', 'qweb-text']:
                converter = 'pdf' if type == 'qweb-pdf' else 'text'
                extension = 'pdf' if type == 'qweb-pdf' else 'txt'

                pattern = '/report/pdf/' if type == 'qweb-pdf' else '/report/text/'
                reportname = url.split(pattern)[1].split('?')[0]

                docids = None
                if '/' in reportname:
                    reportname, docids = reportname.split('/')

                if docids:
                    # Generic report:
                    response = self.report_routes(reportname, docids=docids, converter=converter)
                else:
                    # Particular report:
                    data = url_decode(url.split('?')[1]).items()  # decoding the args represented in JSON
                    response = self.report_routes(reportname, converter=converter, **dict(data))
```
The controller tries to extract the docids from the url in this bloc:

```
docids = None
if '/' in reportname:
reportname, docids = reportname.split('/')

if docids:
# Generic report:
response = self.report_routes(reportname, docids=docids, converter=converter)
```

But if the data parameter is passed to the **report_action** function, the url doesn't contain any docids, and as such continuing the execution will result in an error.

Expected behavior:

The JS function needs to correctly return a url that contains the DOCIDS in order to properly continue the execution:  /report/pdf/[MODULE.REPORT_ID]**/[IDS]?options=...**

Here is an example of a URL that does not stop the execution (can be generated correctly if the data parameter is not passed to the report_action function): `/report/pdf/mandate.mandate_management_report/87,69`

Here is an example of a URL that throws an error:
`/report/pdf/mandate.mandate_management_report?options=[...]`

Keep in mind: this only seems to happen when the report has the **attachment** attribute set to anything other than False.

**Comment by pedrobaeza** [comment]
If you have clear the solution, please do a PR over the repository.

**Comment by mehdibenhac** [comment]
Haven't found a solution, yet. i'm still looking into it.

**Comment by pedrobaeza** [comment]
I would say that using both arguments (`docids` and `data`) is not something supported.

**Comment by mehdibenhac** [comment]
If that's the case, I don't see any other way to pass data on to the report. Here's my use case: When the user clicks on a button, a wizzard pops up in which the user defines two dates: start_date and end_date. Once they click on validate, both dates need to be sent to a report in order to filter through data. This needs to be done within the xml code of the report, and cannot be done python-side. Using both docids and data work if the attachment attribute is set to False, but once it's set to True, using data alongside docids leads to an error.

**Comment by pedrobaeza** [comment]
This enters in the development question side, and I'm afraid this issue tracker is not for that. Use forums for asking how to do it or look to community/OCA modules that print things for comparing.

If you find a use case in Odoo standard code that implements this behavior and gives error, then please resubmit the issue with that case. For now, I'm closing this as custom development.
