### ISSUE TITLE
[12.0] HR: Department Model Name

### ISSUE THREAD

**Issue by abdallamohamedcore** [odoo/odoo#42559]
Impacted versions:
12.0

Steps to reproduce:
1. Go to HR department view
2. Create new department with name as example "Sales"

Current behavior:
message appear in chatter "HR Department created".

Expected behavior:
- it should message will be "Department created". as current message is misunderstand for end user. I found that model name has name  `_description = "HR Department"` and this should be changed to be `_description = "Department"`

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/57271690/71661108-db200400-2d55-11ea-898d-1e82580e8ccd.png)

**Comment by Yenthe666** [comment]
That's an improvement. A PR for the upcoming V14 (now master) is welcomed :)

**Comment by sswapnesh** [comment]
> That's an improvement. A PR for the upcoming V14 (now master) is welcomed :)

At https://github.com/odoo/odoo/pull/42648

**Comment by sswapnesh** [comment]
This can be closed

**Comment by Yenthe666** [comment]
Thanks for the PR @sswapnesh
