### ISSUE TITLE
Bugs in MRP_Subcntacting

### ISSUE THREAD

**Issue by 159820** [odoo/odoo#42551]
Impacted versions:
13

Steps to reproduce:
1: create parts: table , wood
2: create BOM:  table with components  wood,  and set BOM type to Subcontacting
3: please a purahcase order to the subcontactr with qty 1
4: confirm the purahase, and the corrsponding picking and moves and subcontact MO will be created automaticly

=========================================

above is the right procudure.
the foreast qty for 'wood' is 0 BEFORE we placed the purchase order.
the foreast qty for 'wood' is -1 AFTER we placed the purchase order.

5:  cancel the purchase order by click cancel button, the order state will be cancel, and the picking will be cancel too.  BUT, the subcontacting MO is ramain 'confirm' state  in system, and the stock move belong to this MO is valid too.   *** the MO and it‘s stock move is INVISIBLE in system but you can find it in database***

***the foreast qty for 'wood' is -1 AFTER we cancel the purchase order.***

Current behavior:
the subcontacting MO is not canceled when cancel subcontact PO
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@amoyaux or @sle-odoo can you please check this?

**Comment by amoyaux** [comment]
@159820 It should be working now. Thanks for reporting.

> the foreast qty for 'wood' is 0 BEFORE we placed the purchase order.
the foreast qty for 'wood' is -1 AFTER we placed the purchase order.

It's the expected behavior since the subcontractor components will not be in your own warehouse anymore

**Comment by pedrobaeza** [comment]
@amoyaux thanks for the fast reaction.

About the stock, isn't at fiscal/legal aspect still yours and should be included in stock valuation while in subcontractor? In Spain at least is that way.

**Comment by sle-odoo** [comment]
@pedrobaeza they are still included in your valuation, just not below a warehouse

**Comment by pedrobaeza** [comment]
Ah, OK, thanks for the clarification.
