### ISSUE TITLE
[12.0] Required Selection fields with widget Radio not getting required Effect

### ISSUE THREAD

**Issue by ikaltech** [odoo/odoo#42561]
Impacted versions: 12.0

Steps to reproduce: Define a required Selection field with widget radio, then try to save without filling up the field.

Current behavior: get : System server Error => The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead...

Expected behavior: Warning notification saying that "the following fields are invalid..." 

Any suggestion please ?

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/34311

**Comment by Yenthe666** [comment]
Indeed, closing as duplicate.
