### ISSUE TITLE
[13.0] Odoo studio domain is not supported errors

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42609]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 and go to Accounting > Vendors > Bills
2. Activate Odoo studio
3. Click on the field "Vendor" (not the label, the actual field)
4. In the Odoo studio editor click on the "Domain" field
5. You can do the same for other fields such as "Payment terms" for example

Current behavior:
Error "This domain is not supported."
![image](https://user-images.githubusercontent.com/6352350/71673009-d1a79380-2d77-11ea-847a-6176bd6eb810.png)

Expected behavior:
No traceback and the domain is editable

**Comment by Yenthe666** [comment]
OPW `2166421`

**Comment by jvm-odoo** [comment]
Hello,

Thanks for reporting.

The domain used for some fields are too complex for studio. The hidden error is that `company_id` is `undefined`.

If the domain contains a python variable like `('company_id', '=', company_id)`,
the domain parser will eval it according to 

https://github.com/odoo/odoo/blob/67697d9087cf35a09c83d4f65eba36be25a98855/addons/web/static/src/js/core/domain.js#L373:#L376

and we doesn't have the `company_id` value. 

If you want to edit a domain like this one, should you should edit it directly in the XML or do a custom module who override it or add an `xpath` in the view's studio_customization file.

I will make a feedback to our RD team to check if it's possible to handle this in the future versions.

**Comment by Yenthe666** [comment]
@jvm-odoo thanks for the feedback. I understand why it happens but I can't really say that I can take that as an acceptable answer though. My customer wants to use Studio for quite some things and this error happens on a lot of things.  Just to name a few:
- Sales team on leads
- Scoring rules on leads (it actually gives an other error):
![image](https://user-images.githubusercontent.com/6352350/71725436-201a6800-2e34-11ea-8348-06ca0e0a206b.png)

- Customer on sale order
- Invoice address on sale order
- Quotation template on sale order

Etc, etc, etc. So that's not workable.

**Comment by jvm-odoo** [comment]
Hello,

As you can see here https://github.com/odoo/odoo/blob/67697d9087cf35a09c83d4f65eba36be25a98855/addons/web/static/src/js/widgets/domain_selector.js#L398:L399

This case is not implemented yet so I can't do anything in stable. Our RD team is already looking at the problem to find a solution for the next version.

Sorry for the inconvenience.

**Comment by Yenthe666** [comment]
Ohh man, I've never seen this one :( Now that's a bit of a setback. So I can assume this is confirmed and will be implemented for V14 then?

**Comment by jvm-odoo** [comment]
They are only analyzing possible solutions at the moment, but I think that such a glaring problem should be solved V14.

**Comment by Yenthe666** [comment]
I agree and happy to hear :) Shall we close this Github issue and can you give me further updates through the OPW when you know more maybe?

**Comment by jvm-odoo** [comment]
IMHO, you can close this issue and I will close the OPW. The analysis and the specs writing could take a moment so I recommend to open a new OPW if the problem persists in V14.

**Comment by sgrotz** [comment]
Seems to be exactly the same issue in Odoo v14 - trying to edit the domain in Odoo 14.0+e (Enterprise Edition) 👎

**Comment by Yenthe666** [comment]
Asked to reopen the ticket & fix it in V14.

**Comment by SIC-brunorocha** [comment]
Still not fixed in Odoo v14 at this point

**Comment by Yenthe666** [comment]
Nope, nobody reacts on the ticket after weeks either.. Maybe @yelizariev can give this one some TLC.

**Comment by yelizariev** [comment]
TODO is still there

https://github.com/odoo/odoo/blob/eabab5f20fe3ba79b3117b83af5c62453edc84a4/addons/web/static/src/js/widgets/domain_selector.js#L398:L399

From what I know, it's decided to don't implement it in near versions. Maybe because it's too complicated.
Then only way to get it is making an investment and prepare pull request by yourself.
