### ISSUE TITLE
[13.0] free themes still contains OPL license file

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#42613]
All Odoo LGPL themes contains a LICENSE file with Odoo Proprietary License. Please update them.

**Comment by pedrobaeza** [comment]
Where are they hosted? If you are talking about downloads in the Odoo Apps Store, then that's expected, as the cleaning is going to be done on the move to the GitHub repository.

**Comment by zeroheure** [comment]
I didn't know that, sorry for the noise. It was downloaded from the  Odoo store.

**Comment by zeroheure** [comment]
I didn't know that, sorry for the noise. It was downloaded from the  Odoo store.
