### ISSUE TITLE
[13]Helpdesk: When Duplicate the ticket it gives traceback.

### ISSUE THREAD

**Issue by KapilPatel-KP** [odoo/odoo#42656]
**Impacted versions:**

1. Odoo 13 Enterprise

**Steps to reproduce:**

1. Login to the latest runbot 13.0 Enterprice build then Go to Helpdesk >> Tickets >> My tickets >> 
     Select any from existing or create new one and dupicate the ticket.

**Current behavior:**

1. When Duplicate the ticket it gives traceback.
![Screenshothelp](https://user-images.githubusercontent.com/24518821/71684270-0721a080-2dbb-11ea-8b80-10fedfb2217a.png)

**Expected behavior:**

1. No traceback

**Video/Screenshot link (optional):**
![PeekEE](https://user-images.githubusercontent.com/24518821/71684411-70a1af00-2dbb-11ea-8fcb-fa62eccc03cf.gif)

**Comment by pedrobaeza** [comment]
As this is something enterprise, please put instead an OPW ticket in odoo.com/help for better assistance through the enterprise support team.

**Comment by Yenthe666** [comment]
I've made a PR at https://github.com/odoo/enterprise/pull/7508 which fixes this issue (there where actually two). Let's see if Odoo approves with my idea.

**Comment by Yenthe666** [comment]
@KapilPatel-KP This one is fixed! I did find a follow-up bug further down the line now:
1. Login to the latest runbot and go to Helpdesk > Tickets > My Tickets
2. Open the ticket "Kitchen Collapsing" and duplicate it
3. Go to the kanban view and drag it from the stage "New" to "In progress".
4. Traceback

Reported it to @tivisse too :)
