### ISSUE TITLE
[8.0] reconcile issue with opening entries

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#4267]
Hello,

The reconcile_ref field seems to not be set correctly with opening entries.

How to reproduce:
* on runbot 8.0
* create next FY (2015)
* run "Generate Opening Entries" to close 2014 and open 2015
* open the generated journal entry
* notice the Reconcile column is correctly initialized
* view the associated journal items
* notice the Reconcile Ref column is empty where it should have the same value as the Reconcile column in the journal entry

**Comment by sbidoul** [comment]
A proposed fix in in this branch, although I'm not sure it is the best possible solution: https://github.com/odoo-dev/odoo/compare/8-opw-620369-rmu

**Comment by mart-e** [comment]
Hello,

We have merged a slightly different patch at 365eb138b445aaf7086502d16255f04d104d1adf. Thanks for the report.
