### ISSUE TITLE
Enterprise version of inventory management. Can you pick items in the product area and then collect them in one place?

### ISSUE THREAD

**Issue by talway** [odoo/odoo#42697]
Impacted versions:
Odoo 13 Enterprise version 

With the enterprise version of inventory management, can I pick up goods in multiple partitions of a commodity warehouse, and then collect goods in one place?

The enterprise version also finds the choice of the corresponding collection location,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
