### ISSUE TITLE
[13] stock: Drag and Drop should be blocked on Inventory Overview

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42724]
Similar to https://github.com/odoo/odoo/issues/36043

Impacted versions: 13.0 (Maybe All)

Steps to reproduce:
![Screenshot (51)](https://user-images.githubusercontent.com/16624719/71767973-05311c00-2f38-11ea-97a5-e3c533a62618.png)

Current behavior: Drag and Drop is Possible (Which create Inconsistency on the Warehouse/Operation Types)

Expected behavior:Drag and Drop should be blocked

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
fixed by https://github.com/odoo/odoo/pull/42929

**Comment by sle-odoo** [comment]
thank you for the report by the way!
