### ISSUE TITLE
[12.0] account: Multiple accounting tests failing with localizations (l10n_xx)

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#42726]
### Impacted versions:
12.0 (tested), 13.0 (not tested)
### Steps to reproduce:
- Install l10n_do
- Run tests
### Current behavior:
The following test fails https://github.com/odoo/odoo/blob/59601b5d15377453b615a9c9d7bb1938e2528f32/addons/account/tests/test_payment.py#L537
### Expected behavior:
This tests (and others) are failing because it's searching for **receivable** and **payable** accounts based on a search which limits to the first occurrence: https://github.com/odoo/odoo/blob/12.0/addons/account/tests/test_payment.py#L30
Then, it creates an invoice (using this account) which is matched to a payment that needs to match the partner account.
The issue here is that the account returned on the search (the first of type "receivable" on the CoA) might not be same as the one used on the partner if we have a property_account_receivable_id set on the CoA, like in l10n_do and other localizations.

This causes the following error:
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L991

### Proposal:
Instead of this definition
```python
self.account_receivable = self.env['account.account'].search([('user_type_id', '=', self.env.ref('account.data_account_type_receivable').id)], limit=1)
```
Use something like:
```python
self.account_receivable = self.env['ir.property'].get('property_account_receivable_id', 'res.partner').id
```

I tried this myself, but other tests started to crash, so it might not be as straightforward as that, that's why I'm creating an issue and not a PR

**Ticket 2167368**

**Comment by gustavovalverde** [comment]
The same happens with this test: 

https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/account/tests/test_reconciliation_matching_rules.py#L344

**Comment by gustavovalverde** [comment]
Another case:
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/account/tests/test_reconciliation_matching_rules.py#L25

Caused by:
https://github.com/odoo/odoo/blob/054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8/addons/account/tests/test_reconciliation_matching_rules.py#L39

**Comment by randall-vx** [comment]
cc: @hbto

**Comment by pedrobaeza** [comment]
Why don't you propose a PR solving the problem?

**Comment by gustavovalverde** [comment]
@pedrobaeza I explained that in last line:

> I tried this myself, but other tests started to crash, so it might not be as straightforward as that, that's why I'm creating an issue and not a PR

If no one in Odoo makes the PR in the following days, I'll take a time to analyze it further and do it.

**Comment by gustavovalverde** [comment]
cc: @smetl @kebeclibre

**Comment by smetl** [comment]
@gustavovalverde The current tests in the standard modules (e.g. `account`) are not designed to run with any localization. It works for some of them but you need to have at least the minimal chart of accounts including at least one receivable / payable account. Searching on `ir.property` will not help you because such property is linked to an existing account meaning performing the `search` on `account.account` should work in that case.

**Comment by gustavovalverde** [comment]
@smetl I'm sure that the problem is not the localization, as it has all the needed accounts with the correct types. Basically, the **tests** are returning **different accounts** for **invoices** and **payments**, because different (incompatible) methods are being used to **search** for the account.

This only happens on CoAs with more that one receivable / payable account.

**Comment by gustavovalverde** [comment]
By the way, this also means that odoo.sh can't be use with localizations, as it will always be **red**

**Comment by gustavovalverde** [comment]
Fixed by https://github.com/odoo/odoo/pull/44376
