### ISSUE TITLE
Barcode scanning for packages is not working

### ISSUE THREAD

**Issue by senolsun** [odoo/odoo#42727]
Impacted versions:13

Steps to reproduce: Activate product packaging, add a barcode and a package count to the product. Create a delivery order and scan the barcode of the PACKAGE. It will say product not found. Simply put, the barcode reading mechanism is NOT checking the package barcodes, only product barcodes are checked. 

Current behavior:

Expected behavior: Scanned barcodes must be parsed properly, package barcodes must be included in the barcode search.

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
are you using the barcode app or the picking view form?

**Comment by senolsun** [comment]
not the barcode app, this can be reproduced by trying to add a product to a POS Sales order using its package barcode.

**Comment by sle-odoo** [comment]
can you confirm you're trying to scan the product packaging on a stock picking form ?

related rev 02a74e9bce5eed95d8cc3482276dc58da5c9146b

**Comment by senolsun** [comment]
yes, i can confirm that this issue persists on 
-stock picking operations
-pos sales operations

**Comment by senolsun** [comment]
after discussing this with many odoo developers, i have been convinced that odoo does not support recognizing package barcodes on POS sales or stock picking form view.

**Comment by sle-odoo** [comment]
Hi,
I just tested it and it is working as expect on stock.picking, both via the form and the barcode client action (barcode app).

This feature is not supported in pos order.

Regards
