### ISSUE TITLE
[13.0] Map view doesn't look at timezones

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42732]
Impacted versions: 13.0

Steps to reproduce:
1. Go to the latest 13.0 runbot and login
2. Go to CRM > Pipeline and create a new datetime field with Studio. For example `x_studio_some_date`
3. Activate developer mode and open up the map view of the Pipeline. At the top click on the debug icon and click on "Edit View: Map" and add in your new Odoo studio field (`x_studio_some_date`)
4. Create a new lead and fill in the current datetime in this field.
5. See how it says `01/06/2020 09:05:58` for example:
![image](https://user-images.githubusercontent.com/6352350/71804901-13308b00-3065-11ea-9c52-00326bcac035.png)

6. Switch to the map view and click on the related record to see the datetime field too. See how it shows another time as it does not look at the timezone like other views:
![image](https://user-images.githubusercontent.com/6352350/71804856-feec8e00-3064-11ea-8bc4-d4072b57b837.png)

Current behavior:
The Map view doesn't look at the timezone configuration of the user and blindly shows the UTC datetime that is in the database.

Expected behavior:
The Map view looks at the timezone configuration of the user and shows the time in the current user his/her timezone.

**Comment by Yenthe666** [comment]
OPW `2167606`

**Comment by dbo-odoo** [comment]
Hello @Yenthe666 
If you opened an opw, there is no need for a github issue:
- it will not be faster
- if the opw is refused, we won't accept the issue
- there is no added value to doing both (unlike opening an opw and a PR, which is constructive)

In a nutshell: 
- opw + PR = yay
- opw + issue = nay

I'm closing the recent issues you opened where you referenced an opw number.

Thx for your understanding :)
