### ISSUE TITLE
[8.0] Changing a related field into a standalone field

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#4273]
I try to change a related field into a standalone field. For example, I try give every product.supplierinfo its own UOM.

Simply saying

```
    product_uom = fields.Many2one(related=None)
```

will not work, because if related is falsy, it won't trigger a new call to _setup_related. And this function doesn't seem to contain code to revert the related properties. So my question is: What is the canonical way to make a standalone field in a module when inheriting a related field?

For the record, the code below works, but I don't feel that's the right approach:

```
    # we need to do this with an old style field
    _columns = {
        'product_uom': low_level_fields.many2one(
            'product.uom', string='Supplier Unit of Measure',
            required=True, readonly=False),
    }

    def _register_hook(self, cr):
        # it seems we can't override the readonly flag for some strange
        # interplay between new style and onld style api
        self._fields['product_uom'].readonly = False
        self._fields['product_uom'].column.readonly = False
```

On a side note, I want to make the field non-readonly for obvious reasons, that didn't seem to work otherwise than the way I do it above.

**Comment by rco-odoo** [comment]
@hbrunn Have you tried using `False` instead of `None`?
`None` is indeed discarded by `Field`'s init method (probably not a good idea in retrospect).

(And, hum, sorry for the late reply.)

**Comment by hbrunn** [comment]
@rco-odoo thanks foro looking into this. I did, but it doesn't change anything. I suspect this needs some code to revert the effects of `_setup_related`. I made you a demo module at https://github.com/hbrunn/OCB/tree/8.0-odoo-reset_related_field_demo/addons/google_drive_model_not_related for convenience, there's always the possibility I do something stupid.

**Comment by Yenthe666** [comment]
Hi @hbrunn,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
