### ISSUE TITLE
[13.0] Quotation/order email sent in wrong language

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42740]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 and activate developer mode
2. Install the language "Dutch / Netherlands" and make sure that the option to sign quotes online is activated.
3. Create a new customer, for example "Yenthe", and set his language to Dutch/Netherlands.
4. Create a new quotation for this customer and add some product to it. Now e-mail the quotation to the customer. Open up Mailhog to see the simulated e-mail:
![image](https://user-images.githubusercontent.com/6352350/71813831-00c14c00-307b-11ea-8ac7-1866a7b0b86d.png)

5. Open the link of this e-mail in an incognito tab and sign it through the portal (thanks to the token) and then pay it with some testing account.
6. Go back to the non-incognito tab and go back to your order. You'll see that it is confirmed and that there's is a confirmation plus an e-mail from OdooBot:
![image](https://user-images.githubusercontent.com/6352350/71813758-c6f04580-307a-11ea-9072-5fd7389dbdfc.png)

7. Go back to Mailhog and look at the email about the payment:
![image](https://user-images.githubusercontent.com/6352350/71813900-30705400-307b-11ea-834b-783866b065ee.png)

Current behavior:
Both the initial quote email and the confirmation email are in a mixture of Dutch and English. 

Expected behavior:
As the customer his/her language is Dutch both e-mails  should be sent in Dutch.

**Comment by Yenthe666** [comment]
OPW `2167780`

**Comment by dbo-odoo** [comment]
Hello @Yenthe666
If you opened an opw, there is no need for a github issue:

    it will not be faster
    if the opw is refused, we won't accept the issue
    there is no added value to doing both (unlike opening an opw and a PR, which is constructive)

In a nutshell:

    opw + PR = yay
    opw + issue = nay

I'm closing the recent issues you opened where you referenced an opw number.

Thx for your understanding :)
