### ISSUE TITLE
[13.0] validate order blocked when cancelling payment method

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#42742]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 instance
2. Go to Sales > Quotations and create a new quote for a customer. For example:
![image](https://user-images.githubusercontent.com/6352350/71814231-0b301580-307c-11ea-8e80-2a5d9b74cf2d.png)

3. Send this quotation by email and open up the unique token link from the email in an incognito tab
4. Click on "Sign & Pay" and sign the quote.
5. When the payment dialog shows up click on "Credit Card (powered by Authorize)" as a payment option and click on "Pay & Confirm", fill in some details and now close the dialog as you decided to use another payment method
=> see https://drive.google.com/file/d/1JWuSOphdBFbsa-nFtc2TBc41zIcW1ej3/view for this step in video format

Current behavior:
The "Pay & Confirm" button keeps spinning and the button is disabled even if you switch the payment method in this screen

Expected behavior:
The "Pay & Confirm" button is no longer locked and you're able to choose and validate another payment method.

**Comment by Yenthe666** [comment]
OPW `2167792`

**Comment by dbo-odoo** [comment]
Hello @Yenthe666 
If you opened an opw, there is no need for a github issue:
- it will not be faster
- if the opw is refused, we won't accept the issue
- there is no added value to doing both (unlike opening an opw and a PR, which is constructive)

In a nutshell: 
- opw + PR = yay
- opw + issue = nay

I'm closing the recent issues you opened where you referenced an opw number.

Thx for your understanding :)

**Comment by Yenthe666** [comment]
Closed with the following response:

> Hello,
given how authorize.net api works, we could not find a way to listen to the popup close event.
we will keep that in mind if it really causes an issue at some point, but at the moment there doesn't seem to be any good solution and it's non-blocking.
you can see the pr here:
https://github.com/odoo/odoo/pull/44270

**Comment by fhe-odoo** [comment]
@Yenthe666 
https://github.com/odoo/odoo/pull/60571

**Comment by Yenthe666** [comment]
Thanks for linking! :)
