### ISSUE TITLE
[v8.0] In the CRM module, Salesperson is not saved successfully in "Convert to opportunities", but is saved successfully in "Convert to opportunity"

### ISSUE THREAD

**Issue by mliu7** [odoo/odoo#4279]
To reproduce:
- In the CRM module, go to the list of leads
- Click on the check box next to one or more lead
- In the dropdown at the top, click on "More" -> "Convert to opportunities"
- Choose a person as the salesman
- Click "Convert to Opportunities"
- Notice that none of the leads you selected have the salesmen successfully attached to the newly created opportunities. This is a bug since the user expects the salesmen to be attached after selecting them in the previous step.

Also, it's worthwhile to notice that this functionality works fine when converting just a single lead. Here is what I'm talking about:
- In the CRM module, go to the list of leads
- Click on any lead
- Click "Convert to Opportunity"
- Set the salesperson
- Click "Create Opportunity"
- Notice the salesperson is set successfully as you would expect.

**Comment by Yenthe666** [comment]
Hi @mliu7 ,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
