### ISSUE TITLE
[13.0][Time Off] Group by "Companies" not working

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#42796]
Impacted versions: 13.0 Enterprise

Steps to reproduce:
In odoo bot http://832977-7359-e73acd.runbot28.odoo.com/web
1) Go to "Time Off" app
2) Select all companies in multi company menu
3) Select "View List"
4) Go to Group By > Add Custom Group > "Company"

Current behavior:
Odoo cannot detect the company's time off.

Expected behavior:
Odoo must detect the company's time off.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/14253152/71831229-d6718d80-307e-11ea-832d-bd430acda0de.png)

![image](https://user-images.githubusercontent.com/14253152/71831194-c6f24480-307e-11ea-9f44-8e5b521c456f.png)

**Comment by Yenthe666** [comment]
@tivisse

**Comment by tivisse** [comment]
Hi @rgeromegnace 

I know that it looks like a bug, but the group by 'Company' actually refer to the field ``mode_company_id``, which is used in the case you create a leave request for a whole company. 

Once validated this leave request will generate a specific leave request for all the employees under that company.

We certainly will improve this in master, but I fear that this is not really a bug that we should solve in a stable release.

Thanks for the feedback.

Yannick.
