### ISSUE TITLE
New VAT numbers in the netherlands

### ISSUE THREAD

**Issue by wpichler** [odoo/odoo#42830]
Impacted versions:
All

Steps to reproduce:
Create Customer with country set to netherlands, enter new valid VAT number, validation will fail

Current behavior:
Validation fails

Expected behavior:
Validates correct

The netherlands got a new vat numbering system since 01.01.2020 - so odoo should implement the new numbering for validation.
Take a look here:
https://www.vat4u.com/en/2019/11/26/netherlands-vat-update-a-new-intra-community-vat-number/

**Comment by Yenthe666** [comment]
@qdp-odoo and @oco-odoo for your interest!

**Comment by oco-odoo** [comment]
@Yenthe666  
Our bugfix team is already on it ;) @jhk-odoo Has a PR for it here https://github.com/odoo/odoo/pull/42681

**Comment by Yenthe666** [comment]
Nice, thanks for the reference! Good job you guys.

**Comment by nim-odoo** [comment]
Fixed in v11 with https://github.com/odoo/odoo/pull/42681
Forward-port ongoing.
