### ISSUE TITLE
Scanning barcodes in mobile browsers

### ISSUE THREAD

**Issue by zitom4** [odoo/odoo#42835]
Hello!

My name is Lorenzo, from Sistemas de datos, Tenerife, Canary Islands.

Using the module OCA/stock-logistics-barcode, stock_barcodes in a mobile browser, the barcode reading is not correct.

We have found using a mobile browser, that the keyboard is showed automatically in the middle of the scan. This happens because when we scan a barcode, the event focus() over the input which stores the barcode is called and when the focus event is called over an input field,the keyboard is showed automatically.

https://github.com/odoo/odoo/blob/fb3d00e1d2fbca4d1929e92e27f683071ed994e1/addons/barcodes/static/src/js/barcode_events.js#L224 

When the keyboard is displayed in the middle of the scan, the code input is delayed more than 55s, which is the time configured between keys pression and this produces the barcode to divide.

https://github.com/odoo/odoo/blob/fb3d00e1d2fbca4d1929e92e27f683071ed994e1/addons/barcodes/static/src/js/barcode_events.js#L30

To solve this, we can use the global attribute inputmode over the dynamic input with value none.
[Referencia](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode)
It's important to check the browsers versions compatible with this attribute (firefox not supported).

If the used browsers are supported, to solve the problem, we have modified the following line

https://github.com/odoo/odoo/blob/fb3d00e1d2fbca4d1929e92e27f683071ed994e1/addons/barcodes/static/src/js/barcode_events.js#L59

 ```
// Creates an input who will receive the barcode scanner value.
        this.$barcodeInput = $('<input inputmode="none"/>', {
            name: 'barcode',
            type: 'text',
            css: {
                'position': 'fixed',
                'top': '50%',
                'transform': 'translateY(-50%)',
                'z-index': '-1',
            },
        });
```

**Comment by pedrobaeza** [comment]
This shouldn't be here, as it's not about Odoo standard, but an extra module.

**Comment by zitom4** [comment]
Hi Pedro.
Thanks for your reply.

Yes, i'm using an extra module, but if i'm not wrong, the problem is in the standard, because as you can see, what i'm talking about is not modified in the extra module.

- Extra module URL:
[https://github.com/OCA/stock-logistics-barcode/tree/12.0/stock_barcodes/static/src/js](https://github.com/OCA/stock-logistics-barcode/tree/12.0/stock_barcodes/static/src/js)

**Comment by pedrobaeza** [comment]
As said, it's on the extra module where the possible patch should be applied. Any way, we are the authors of that module and we haven't found that problem. Put the issue on their corresponding repo and my colleague that developed it may take a look.
