### ISSUE TITLE
Incorrect behaviour for date before 1900

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#42875]
Impacted versions: 12.0 but most probably all versions since 3 years

Steps to reproduce: import a file with dates before 1900

Current behavior: the object will not be displayed on frontend with a JS error : 

Error: '1882-01-01' is not a correct date

Expected behavior: Object is properly shown with the dates inside

It has also been confirmed that if you try to set manually (via frontend) a date to a year before 1900, Odoo will not take it.

This behaviour is traced to parseDate function in addons/web/static/src/js/fields/field_utils.js, line 408, and more specifically to line 424 :
`        if (date.year() >= 1900) {`

Is there any reason for blocking dates before 1900 ?
Is it safe to assume that this could be related to https://bugs.python.org/issue1777412 which is fixed since Python 9.2 and therefore not necessary anymore ?

**Comment by pedrobaeza** [comment]
Duplicated of #41788

**Comment by remi-filament** [comment]
Thanks @pedrobaeza, strange I could not find it while searching for date and 1900, good to know there is no limitation anymore so that I can propose a PR solving this...

**Comment by pedrobaeza** [comment]
Yeah GitHub search is a bit limited and I had to find it through my mail history, and my ability of remembering useless data triggered the thing about existing something in the topic :stuck_out_tongue: .
