### ISSUE TITLE
Leave request in hours | Leave request changes hours after approval, ignoring global time off

### ISSUE THREAD

**Issue by bultrug** [odoo/odoo#42877]
Impacted versions: 13.0

Steps to reproduce: Add employee, allocate paid leave, set leave in hours. 
Standard workweek is set to 40 hours. 5 days 8h per day
Global Time off: Dec.25 00:00:00 - Dec.26 23:59:59

Employee requests one week of leave, during christmas (dec.25 and dec. 26 in the week). Manager approves.

Current behavior: Current behavior: Before approval the total hours in the request is 24. The manager approves and the total hours change to 40. Total remaining hours is also -40.

Expected behavior: After approval the requested hours should not change and remain 24. The total remaining hours should also be -24.

This is a similar issue as issue #41848 which has been fixed in #42710

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@tivisse

**Comment by tivisse** [comment]
Hi @bultrug 

Thanks again for the feedback. :)

I'm gonna look at this asap ;)

Have a nice day.
