### ISSUE TITLE
[13] Project: Wrong number of Task on Project Dashbaord

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42886]
Impacted versions: 13.0 (Maybe 12 too)

Steps to reproduce: Open Task from here
![Screenshot (62)](https://user-images.githubusercontent.com/16624719/71918836-32383580-31a9-11ea-80a7-a88b2b4fcd9b.png)

Current behavior: See the number of Record on the List view
![Screenshot (63)](https://user-images.githubusercontent.com/16624719/71918867-4845f600-31a9-11ea-8e93-272d71e96a77.png)

Expected behavior: Correct number on Dashboard

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because the tasks listed there are only the opened ones, and if I remember well, this is this way since a lot (even 8.0)

**Comment by Yenthe666** [comment]
Yeah I believe Pedro is right and that this is done on purpose

**Comment by sswapnesh** [comment]
I would suggest to add filter to exclude those records so user can see correct number of records on view nd remove filter to see all records

**Comment by Yenthe666** [comment]
To me it only adds extra clicks if you want to see all the data though?

**Comment by pedrobaeza** [comment]
And by default done tasks are folded.

**Comment by Yenthe666** [comment]
I honestly think there is nothing to do here and that we should close this, sorry :)

**Comment by sswapnesh** [comment]
Yes but it will be aligned with the Number in the Dashboard.

To Pedro: You are Right but this makes confusion where task number is large nd List view is loaded on that action.

**Comment by sswapnesh** [comment]
Maybe be better to ask Responsible from Odoo.
