### ISSUE TITLE
[13.0] mass_mailing: Issue due to sharing same Model for Email/SMS Marketing

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#42884]
Impacted versions: 13.0

Steps to reproduce: Crate SMS Marketing Record

Current behavior: 
![Screenshot (57)](https://user-images.githubusercontent.com/16624719/71915785-7bd15200-31a2-11ea-8367-c8642f8aceae.png)

Expected behavior: More meaningful model name  (or Separate mode for each :wink: )

Video/Screenshot link (optional):

**Comment by tde-banana-odoo** [comment]
Master task will handle it :) .

**Comment by sswapnesh** [comment]
Hello @tde-banana-odoo  Still same on master 

https://2812218-master-1229b9.runbot21.odoo.com/web#id=2&action=447&model=mailing.mailing&view_type=form&cids=&menu_id=336 
![Screenshot from 2020-05-26 21-55-04](https://user-images.githubusercontent.com/16624719/82925699-b4c86280-9f9b-11ea-8327-ae917a0c9dc2.png)

I thought this was going to be handled on https://github.com/odoo/odoo/commit/16bb5795d805e9bba9d9d6e2c7453210ffcacb74
