### ISSUE TITLE
[8.0, 7.0] misleading display of purchase order lines in a product form

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#4295]
_Impacted versions:_
7.0 & 8.0

_Steps to reproduce:_
Cancel a purchase order with a product A
Look at the product form of this product A...
In 8.0, check "Purchases" button (with a caddie icon) 
In 7.0, check the link "More/Purchase Order Lines"
it leads to purchase order lines linked to this product.

_Current behavior:_
All the lines linked to the product are displayed, even cancelled lines. But we have no displayed information about state of the lines.
A user can easily think that these lines are lines effectively purchased.

_Expected behavior:_
The state of the lines should be displayed.
In this context, maybe the cancelled lines could be not displayed.
In all cases, the user need more information to know if lines are draft, cancelled or done.

**Comment by Yenthe666** [comment]
Hi @rdeheele ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
