### ISSUE TITLE
Bug: boolean_toggle widget in tree views not properly working

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#42963]
### Impacted versions:

13.0

### Steps to reproduce:

1. Go a to a view that has the boolean_toggle widdget in the tree view.
2. Try to click in the button to be able to activate/deactivate the boolean
 
### Current behavior:

Is not working:

1. If there is a tree view without form will will not do anything.
2. If there is a tree view and a form view, will let us to the form view (not chaining the boolean field).

Only working if the tree view is editable

### Expected behavior:

Be able to use the widget in the tree view without need to make the view editable, no matter is is a single tree view, or a tree and form view, be able to activate/deactivate the boolean field where the widget is set.

Video/Screenshot link (optional):

https://youtu.be/7FO2VNDQMoY

**Comment by zaoral** [comment]
Hi @jco-odoo 

This is the ticket we talk about in the last meeting. Please link the info about the related OPW ticket.

**NOTE:** This is the PR with the change we made in order to be able to use the widget in the Identification Types (make the view editable and all the fields readonly except the active field) https://github.com/odoo/odoo/pull/41677

Best Regards

**Comment by jco-odoo** [comment]
@zaoral This should have been solved in v13.0.  It is opw-2154055.

**Comment by zaoral** [comment]
Hi @jco-odoo 
Excellent, thank you!
