### ISSUE TITLE
[V8] + and - don't work correctly when you click on them fast in order to increase the quantity in the shopping cart

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#4298]
Impacted versions:
 - 8.0

Steps to reproduce:
 1. create a new sale order
 2. click(fast) on + to increase the qty to 10

Current behavior:
qty increases and decreases randomly and a lag is visible 

Expected behavior:
qty increases not lag

Tested on many versions of 8.0 on other websites and subdomain.odoo.com

**Comment by sharkutz** [comment]
fixed

**Comment by sharkutz** [comment]
Again it's doesn't work if you click fast on + to increase the qty.

**Comment by michaelkarrer81** [comment]
+1 very annoying

**Comment by wtaferner** [comment]
You might take a look at https://github.com/OCA/OCB/pull/185 which could be one solution to improve the situation...

**Comment by PCatinean** [comment]
The issue is explained inside the OCA PR, it can only happen if the user makes a quantity adjustment in less than half a second on a second product after clicking on the first, highly unlikely but I had to mention it to be fair
