### ISSUE TITLE
refund is in a error loop

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#42995]
Impacted versions:
12

Steps to reproduce:
1 go to http://846140-12-0-5d44cf.runbot27.odoo.com/web#id=&action=490&model=account.invoice&view_type=form&menu_id=324

2 start a refund

3 try to save

Current behavior:
![image](https://user-images.githubusercontent.com/17784575/72012163-b8ad4f80-325b-11ea-8246-142a383a5590.png)

1 i am not in a invoice
2 i do try to create a refund

Expected behavior:
odoo should recognize is a refund not an invoice

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is the price negative?
