### ISSUE TITLE
Theoretical Quantity in inventory adjustment gets updated upon save

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#42997]
### Impacted versions:

11.0, 12.0 (haven't checked 13.0)

### Steps to reproduce:

1. Create and start an inventory adjustment. Let's say, Theoretical Quantity is 10 for a product.
2. Create a delivery and ship out quantity 1 of the product. (Now the stock is 9 for the product in the system.)
3. Go back to the inventory adjustment, change Real Quantity to 9, and save.

### Current behavior:

Theoretical Quantity is updated to 9, reflecting the current quantity on hand.

### Expected behavior:

Theoretical Quantity stays as 10, representing the quantity as of the start of stocktaking.

Not really sure about the design idea behind this behavior. I was thinking Odoo should sort of "lock" the theoretical quantity when an inventory adjustment initiates, even if it doesn't allow back-dated moves, so that it allows the possibility of not stopping the stock move operations when it takes time to collect the result of physical inventory and update the system. With the current behavior, however, it gets a bit tricky to adjust inventory using this function without stopping the stock move operations until the inventory adjustment is done.

**Comment by sle-odoo** [comment]
Hi,
I advise you to test v13. In this version, `theoretical_qty` is stored and you now have an `outdated` computed field to inform you when it actually is outdated. Plus there's an action to update the `theoretical_qty` manually when it is actually outdated.

Regards

**Comment by yostashiro** [comment]
Thanks for your input @sle-odoo . Good to know that the function has been improved in v13.  Is the behavior in the earlier versions **intended**, though? If it is, why? If not, maybe you can consider leaving the issue open?

**Comment by sle-odoo** [comment]
Doing anything about it will in earlier versions would break the stable policy, so i think no need to keep this issue opened.

**Comment by yostashiro** [comment]
I understand. Thanks for your reply.
