### ISSUE TITLE
[11.0] [12.0] [13.0] Consistent use of mail layout in chatter [Send message] vs button [Send & Print]]

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#43034]
Impacted versions:
All versions [11.0] [12.0] [13.0]

Steps to reproduce:
- using button [Send & Print]
Create an invoice and sent the mail using the button [Send & Print]
The email will look like this:
![image](https://user-images.githubusercontent.com/30628967/72065419-7842e580-32de-11ea-9ebf-784afcdd6fe1.png)

In the chatter you will see this:
![image](https://user-images.githubusercontent.com/30628967/72065503-ade7ce80-32de-11ea-8d3f-b91bb2282f22.png)

- using chatter [Send message]
Create an invoice and sent the mail using the chatter [Send message] 
The email will look like this:
![image](https://user-images.githubusercontent.com/30628967/72065473-96104a80-32de-11ea-9ba7-9f015e90b3ff.png)

In the chatter you will see this:
![image](https://user-images.githubusercontent.com/30628967/72065519-b8a26380-32de-11ea-8f61-03b27b3eb06e.png)

Current behavior:
As you see, the mail using the button [Send & Print] has a nicer layout with all the company data with logo compared to the one using the chatter [Send message].

Expected behavior:
- I would expect that the outgoing message/mail would use the same mail layout with the same header and footer.
- Maybe you can make it an option in the system.
- Maybe make the mail composer exactly WYSIWYG. Now you only see the body, but not what is really going out.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
On the second way, are you using the mail template or have you copied manually the text?

**Comment by yung-wang** [comment]
I use the same mail template in both ways. I tested in runbot and just using the default invoice template.

**Comment by YanisBatatia** [comment]
Hi, I have the same issue, i made a automated action that send a mail under certain condition and i'd like the layout of this mail to be the 'default' one instead of just plain text... But i can't understand how to do it.
