### ISSUE TITLE
OE - Mobile view does not allow to print or start actions

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoo/odoo#43090]
Impacted versions: 11.0, 12.0, 13.0 Enterprise

Steps to reproduce:
Open the browser in a mobile. Navigate to the CRM app and open the Pipeline.

Current behavior:
The mobile view does not provide access to users to the options "Print" or "Actions".

![image](https://user-images.githubusercontent.com/7683926/72093875-7cd6c080-3315-11ea-85f3-ece458992a6b.png)

![image](https://user-images.githubusercontent.com/7683926/72093913-911abd80-3315-11ea-8c63-efd4e5d18fff.png)

Expected behavior:

The mobile view should allow the users to access to the Print / Actions available to a given Model.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Official statement other times has been that the mobile view has to be simpler. Any way, you can try to put an OPW ticket in odoo.com/help, as this one is an enterprise module. If not, you know that OCA `web_responsive` includes this action dropdown :wink:

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza thanks. I know ;)
