### ISSUE TITLE
Apps Description not showing

### ISSUE THREAD

**Issue by sciallo** [odoo/odoo#43092]
Impacted versions: 12

Steps to reproduce: Go to apps, click module info on any app (not "extra")

Current behavior: Description doesn't show

Expected behavior: Description should show

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/17577898/72119124-528b0000-3321-11ea-8b4d-09a3da6ce757.png)

**Comment by mohamedmagdy** [comment]
I have the same issue as shown in the following screenshot!

![Screenshot_20200110_041604](https://user-images.githubusercontent.com/4986782/72120249-04492180-3360-11ea-908a-45fa89a62a5e.png)

**Comment by pedrobaeza** [comment]
For that standard Odoo modules, you have to click on "Learn more" to go to the website description.

**Comment by sciallo** [comment]
That is if the module has one... Many don't. It sure was nice to get a quick description right then and there... I guess it's another odoo philosophy we need to live with....

**Comment by pedrobaeza** [comment]
AFAIK, if the module doesn't have that link, you see the module description the same way as before.

**Comment by sciallo** [comment]
On my install "calendar" (just as an example, there is many more) doesn't have a link, the description still doesn't show...

After further digging, it looks like there is no description in any of the ODOO modules anymore :-( also there is no README.rst

Modules that do have it (eg. OCA geoengine_demo) show it, link or no link.
That makes modules selection really hard IMHO

**Comment by sciallo** [comment]
... Although a simple text description in the manifest file shows if 'application': False, it does not if application: True regardless of link existence as far as I can tell.
