### ISSUE TITLE
Non-employee cannot add attachments from the openchatter

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#4309]
We have an application ([Anytracker](https://bitbucket.org/anybox/anytracker/)) to which customers have access and can create tickets. A customer is not an employee and has very few permissions, they can create and write on a ticket, add attachments on the tickets, and send messages from the openchatter.

Since last our last update, customers cannot add attachments anymore from the openchatter :
https://bitbucket.org/anybox/anytracker/issue/39/a-customer-cannot-create-attachments-from
The problem comes from one of the last commits eb9113c restricting access to orphaned attachments for non-employees.
The issue comes from the fact that attachements created from the openchatter are temporarily orphaned : they are first attached to a res_model=mail.compose.message with res_id=0, then when the message is sent, they are updated to the correct res_model and res_id (in our case an 'anytracker.ticket').

**Comment by beledouxdenis** [comment]
Closed with eaad70daac22fd0fde1c63484b7f29eae6302e41.

Will be ported in Odoo 8.0 in the coming days.

**Comment by ccomb** [comment]
Thanks, I've checked it also fixes the issue in our application
