### ISSUE TITLE
Permission ir.mail

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#4311]
1) Steps to reproduce the issue you have observed 
1.- I create a user manager to sale.
2.- I create a new email template, with a Outgoing Mail Server.
3.- I login with the user created.
4.- I create a new quotation, and send this by email to customer, but I select the template created in the step 2.

You can see the next video:
http://youtu.be/aLEwWeZIwh0

2) The result you observed.
I check mi terminal, and have a error message, because the user haven't permission to ir.email. But a user manager to sales I don't hope that he having permissions to settings, only sales.

 3) The result you expected.
That my terminal dont't have errors

 5) The OpenERP version
version.- 8.0
commit.- 0f78618d276ce86ca93e91a70f2ea49fdb779109

**Comment by luistorresm** [comment]
Hello,

I would like know the status of this Issue, I haven't news.

Regards

**Comment by mart-e** [comment]
Hello,

Giving read access to employee on mail server is definitely not a good idea (this contains username and password) !
The error seen in the logs is not really important, it's just that the server was not able to retrieve the name of the mail server but we don't care as the field is hidden, everything will still work as expected.

However, this means that the return format of onchange is not optimal (trying to retrieve the name from web client while the server could directly return the name_get). For the v9, we will be trying to improve the way the onchange behave but this needs changes in the orm and is definitely an improvement.

**Comment by Yenthe666** [comment]
Hi @luistorresm,

I'm closing this bug report as per the feedback from Martin and because Odoo 8 is no longer supported. If you still face this in newer versions please do create a new bug report.

Regards,
Yenthe
