### ISSUE TITLE
[12.0] Inventory Valution is different in Current Inventory and At a Specific Date when Costing method is FIFO and valuation is realtime

### ISSUE THREAD

**Issue by tpa-odoo** [odoo/odoo#43120]
Impacted versions: 12.0

Steps to reproduce: 

When we check the valuation of the product at date and valuation at the current date it should be the same, but in the current scenario, it is different.

In a normal cases it will be fine but if there was any diff in qty by account move and stock move results ill be different. 

1> Set the product with FIFO and Automated valuation configuration.
![ACS - Odoo](https://user-images.githubusercontent.com/7599790/72151429-33967780-33ce-11ea-9e74-fc94aa6e337d.png)

2> Just create one stock move for the vendor location to an internal location. (it will create account move.)
3> Change the type of location from internal to vendor location. (Make sure there are other moves also.)
4> Now check inventory valuation at the date and current date.
Current Inventory Valuation. (which will be current date and time) 
![Inventory Valuation - Odoo](https://user-images.githubusercontent.com/7599790/72151262-c7b40f00-33cd-11ea-8b60-2a376166d43e.png)

Inventory Valuation at the date. (which will be current date and time so same as current inventory.) 
![Inventory Valuation - Odoo (1)](https://user-images.githubusercontent.com/7599790/72151269-caaeff80-33cd-11ea-9bbd-4f5884a9d3e9.png)

Current behavior:
When we check the valuation of the product at date and valuation at the current date it is different.

Expected behavior:

When we check the valuation of the product at date and valuation at the current date it should be the same.

Tested on http://856451-12-0-0f69d9.runbot27.odoo.com/ (if DB is not dropped it can be reproduced for the product ACS)

Maybe it would be hard to reproduce but when you check code it will be more easy to understad. (At least for developers.)

**Comment by sle-odoo** [comment]
> 3> Change the type of location from internal to vendor location

Why would you do that?

**Comment by tpa-odoo** [comment]
At the beginning customer did a mistake in the configuration. But when we corrected configuration we faced such unexpected results. Raise issue so it can save someone's time.

**Comment by sle-odoo** [comment]
We consider this a configuration issue. Sadly these reports are brittle in v11 and v12, due to the fact we sometimes use the stock moves and sometimes the account moves. Hopefully everything is solved now in v13 with the introduction of the valuation layer and a very simple valuation report/ valuation at date report.

I'm closing this one since it isn't a valid use case in my opinion.

Regards

**Comment by tpa-odoo** [comment]
> We consider this a configuration issue. Sadly these reports are brittle in v11 and v12, due to the fact we sometimes use the stock moves and sometimes the account moves. Hopefully everything is solved now in v13 with the introduction of the valuation layer and a very simple valuation report/ valuation at date report.
> 
> I'm closing this one since it isn't a valid use case in my opinion.
> 
> Regards

I agree in the first sign it is configuration issue. But if you look at pull request you will understand it is issue in code.
