### ISSUE TITLE
[12.0] ValueError: Expected singleton: res.partner.bank() on creating of Bank Account for l10n_ch

### ISSUE THREAD

**Issue by dbu-odoo** [odoo/odoo#43122]
Impacted versions: 12.0 Community and Enterprise

Steps to reproduce: 
1) Install "l10n_ch" module
2) Go to Invoicing for community
   Go to Accounting for Enterprise
3) Go to Bank Accounts
4) Try to create new one with name field only

Current behavior:
gives error "ValueError: Expected singleton: res.partner.bank()", if "Bank Account" field is not entered

Expected behavior:
Able to save without "Bank Account" field

Video/Screenshot link (optional):
![New - Odoo](https://user-images.githubusercontent.com/12182249/72153822-f08bd280-33d4-11ea-872f-6694be0419a0.png)

![Bank Accounts - Odoo](https://user-images.githubusercontent.com/12182249/72153923-3b0d4f00-33d5-11ea-8ca3-ab3de4288b87.gif)

**Comment by pedrobaeza** [comment]
Is this reproducible from runbot?

**Comment by dbu-odoo** [comment]
Yes, the gif file and the screenshot is taken from runbot only

**Comment by dbu-odoo** [comment]
Problematic Code:

**Comment by pedrobaeza** [comment]
OK, thanks for the details.

**Comment by sswapnesh** [comment]
Added Fix at https://github.com/odoo/odoo/pull/43158
