### ISSUE TITLE
Work order

### ISSUE THREAD

**Issue by klogas** [odoo/odoo#43134]
Impacted versions:
So far odoo 12
Steps to reproduce:

Current behavior:
In the mrp_workorder_views.xml file of the mrp_workorder module, in the mrp_workorder_view_form_tablet view, they refer to the is_first_wo field that does not exist in any in the mrp.workorder model. This means that the module cannot be installed and the "Work orders" configuration cannot be activated. It was a change uploaded on 10/07/2019 by Goffin Simon.

Expected behavior:
That field be removed, which according to what is stated in the source code must be used to obtain the first work order of the production orders. Or be included in the mrp.workorder model, so that it performs the expected behavior.

Video/Screenshot link (optional):
https://drive.google.com/open?id=1dYaDSEb55RSVXT9uevHroWjUkIdOti6t

**Comment by sle-odoo** [comment]
Hello,
To report an enterprise issue, please open a ticket on odoo.com

Regards
