### ISSUE TITLE
[report_engine] Can not create internal links

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#43131]
Steps to reproduce:
1. Add in a template line:
  <a href="#test_link">Click me to go to Test link.</a>
2. Print PDF report
3. Open the report and click on a link

Current behavior:
An open web page like href="http://localhost:8069/#test_link

Expected behavior:
Move-in the current position in pdf to tag with id="test_link"

Hi, @pedrobaeza. Is it a question for the forum or can it be posted this?

**Comment by pedrobaeza** [comment]
Yeah, I'm afraid this is a development question to be done on forum, sorry.
