### ISSUE TITLE
Take a long time when validate an inventory adjustment with 5000+ inventory lines.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#43153]
Impacted versions:
13.0

Steps to reproduce:
1. Use a python script to create an inventory adjustment with 5000+ inventory lines.
2. Then validate it.
3. It takes about 6 minutes on a ubuntu server with 2 CPU,8G memory, and postgresql is optimized using settings generate by [pgtune](https://pgtune.leopard.in.ua/#/)

Expected behavior:
Is there any way to speed up ?

**Comment by sle-odoo** [comment]
Hi,
6 minutes to validate 5000 stock moves seems correct to me.

If you're not happy with this result then please provide a pyflame so we can see if there's a blocking point somewhere in the process. In the meantime, i'm closing this issue since.

Regards

**Comment by dymaxel** [comment]
> Impacted versions:
> 13.0
> 
> Steps to reproduce:
> 
> 1. Use a python script to create an inventory adjustment with 5000+ inventory lines.
> 2. Then validate it.
> 3. It takes about 6 minutes on a ubuntu server with 2 CPU,8G memory, and postgresql is optimized using settings generate by [pgtune](https://pgtune.leopard.in.ua/#/)
> 
> Expected behavior:
> Is there any way to speed up ?

@tanghulu0608, This performance is extremely good, we want to achieve it as well. Could you please share your Odoo Config File and PostgreSQL Config File so that we can have an idea and configure our files accordingly.

In our case it takes too long just to validate 1000 lines of adjustment.

I would appreciate if you would be able to share the requested config files.

Regards
Akram

**Comment by tanghulu0608** [comment]
I use following PostgreSQL Config File Setting.I get this from https://pgtune.leopard.in.ua/#/

#------------------------------------------------------------------------------
# CUSTOMIZED OPTIONS
#------------------------------------------------------------------------------
# DB Version: 10
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 6 GB
# CPUs num: 2
# Data Storage: ssd

max_connections = 300
shared_buffers = 1536MB
effective_cache_size = 4608MB
maintenance_work_mem = 384MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 5242kB
min_wal_size = 2GB
max_wal_size = 4GB
max_worker_processes = 2
max_parallel_workers_per_gather = 1
max_parallel_workers = 2

in odoo config file,
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648

This is my setting.I Hope I can help you.

**Comment by dymaxel** [comment]
Thanks a lot for sharing this information. Could you please also tell, how many concurrent users are there in your environment, cause that is an important factor to consider as well?

 

Regards

Akram

**Comment by tanghulu0608** [comment]
Most of time ,2 concurrent users in this environment, total 5 users.
