### ISSUE TITLE
Cropped images in html widget are saved in database, not in the attachment.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#43152]
**Impacted versions:**
13.0

**Steps to reproduce:**
1. Upload a picture in html widget.
2. odoo generate the html code like this
`<p><img class="img-fluid o_we_custom_image o_we_selected_image" src="/web/image/1254/pic.jpg?access_token=cb1e7010-b6e2-4210-ab6b-d87217ac52bb"><br></p>`
the picture is save in attachment ,and get it using access_token. This works well.
3. crop the image, see the picture bellow
<img width="1225" alt="WX20200111-131959@2x" src="https://user-images.githubusercontent.com/5561864/72199309-41eb9e80-3475-11ea-8d50-2c9c18410e7b.png">
4. odoo generate the html code like this
<img width="934" alt="WX20200111-132026@2x" src="https://user-images.githubusercontent.com/5561864/72199323-6d6e8900-3475-11ea-998d-dc8238aa0663.png">
the picture data is saved in html code, after click the save button, the picture data is save in db.
When there are a lot of pictures need upload and crop in odoo, the database will be be became very large and slow.

**Current behavior:**
Cropped images in html widget are saved in database

**Expected behavior:**
Cropped images in html widget are saved in the attachment.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be I'm pretty sure you've got a good idea about the why's for this one?

**Comment by kig-odoo** [comment]
This issue is too old it was there since Cropdialog was introduced [12.0].
I've created [PR](https://github.com/odoo/odoo/pull/43522) for it.

**Comment by tanghulu0608** [comment]
☹️Thank you.

**Comment by kig-odoo** [comment]
Hey @tanghulu0608 ,

This issue is fixed with this PR: https://github.com/odoo/odoo/pull/46400 for V13.
You can close this issue :+1:

**Comment by tanghulu0608** [comment]
@kig-odoo  Thanks
