### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get' - - -

### ISSUE THREAD

**Issue by sherpya** [odoo/odoo#43156]
Impacted versions:
12

Current behavior:
I suppose they are jsonrp probes, 
```
  File "/opt/odoo/12.0/ce/test/odoo/odoo/http.py", line 621, in __init__
    self.params = dict(self.jsonrequest.get("params", {}))
AttributeError: 'list' object has no attribute 'get' - - -
```
self.jsonrequest:
```
[{'jsonrpc': '2.0', 'id': 0, 'method': 'eth_accounts'}]
```

also:
`ValueError: dictionary update sequence element #0 has length 8; 2 is required - - -`
self.jsonrequest:

```
{'id': 0, 'jsonrpc': '2.0', 'method': 'eth_getBlockByNumber', 'params': ['0x1d4c00', False]} 
```

Expected behavior:
Return bad reques, no spam in the log

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by sherpya** [comment]
`curl --data-binary '[{"jsonrpc": "2.0", "id": 0, "method": "eth_accounts"}]' -H "content-type: application/json" https://odoo/jsonrpc`

**Comment by Yenthe666** [comment]
Please add more details/info. What are you doing, how are you doing it and why are you doing it? Just pasting a little bit of content (which also seems to miss authentication etc) isn't enough for us to help you.

**Comment by sherpya** [comment]
looks like odoo does not support [jsonrpc 2 batch call](https://www.jsonrpc.org/specification#batch)
it's not my call, as I said it someone probing my server (for vulnerabilities?)

@Yenthe666 pick the payload of your preferred jsonrpc call and wrap the object into an array

**Comment by sherpya** [comment]
the second error may be an invalid request, but I think should return bad request and not internal error

**Comment by sherpya** [comment]
actually probes for ethereum nodes https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_accounts

**Comment by pedrobaeza** [comment]
Closing as no reproducible.

**Comment by sherpya** [comment]
> Closing as no reproducible.

damn pedro aren't you able to launch:

`curl --data-binary '[{"jsonrpc": "2.0", "id": 0, "method": "eth_accounts"}]' -H "content-type: application/json" https://your_damn_odoo_server/jsonrpc`

and check your server log?

I thought you were smarter than this, if you give me the url of your odoo installation I can execute curl for you if it's so difficult.

As I can see the only ability you have is closing bugs without even trying them.

**Comment by pedrobaeza** [comment]
This is a not expected use, and so, it shouldn't be "fixed". You haven't specified any reproducible steps for a normal use, so that's why I have closed. If you don't like it, pay an enterprise contract and demand a "more extended" answer from Odoo support about this (and maybe a fix), but meanwhile, my "clever" option as voluntary is to clean this issue tracker from non usable issues reports.

**Comment by sherpya** [comment]
So you closed the bug as "no reproducible", when I said you never tried to reproduce it the reason become "This is a not expected use, and so",
but you don't understand that:

1) it's an intended use, check jsonrpc specs and I'll find odoo does not implements batch actions, so odoo has an incomplete json rpc implementation that causes spam in the log, someone may want to use this existing features in real jsonrpc implementations
2) I'm not using this way by myself, there are a lot of script kiddies probes and I don't want a lot of this spam in my log, so the problem is real
3) I already have an enterprise support, but I'm able to fix it by myself, unfortunately looking at your position and my past attempts to contriobue, I will only waste my time, because my pr wouldn't be accepted.
4) Your "clever" option as voluntary is to clean issue tracker from reports you don't understand? great!

**Comment by pedrobaeza** [comment]
Yes, my option is to close it because if not, it will remain opened for ages with no more actions (and you can see that this is the case as you posted this on 11 of January).

Now, you have changed the tittle to something more inline with the spirit of a good issue report. Now it rests 

- Why Odoo should support this "batch call"?
- Is this affecting something in regular Odoo use?

One thing is also clear: if this is not a bug (as it's not, it's only a missing feature), this only be considered for new versions due to stability policy: https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean.

And of course everyone wants to improve Odoo, but there has to be certain order and priority on what's more interesting to be added, as this addition needs to be maintained. So if this feature you are asking for (being enough explained the rationale to add it) is very interesting, I will be the first to add for feedback about that. It's also more probable to be accepted if it's through a pull request in master branch, that also means very little changes.

**Comment by sherpya** [comment]
@pedrobaeza I've changed the title to "something more inline with the spirit of a good issue report" because if you read my comment you'll find I discovered the problem after, and to make clear you close bugs regardless of the content.

The not implemented feature causes the actual bug (a lot of stacktrace in the log), so if no one is interested to use this feature, at least a check should be added instead of having tons of spam in the log.

I make a legit call and odoo raises an embarassing error, and fills the log, this is a **BUG**

I can **FIX** this **BUG** by adding an if, but it is trivial, and anyway no one will approve my pr.
This is really not the spirit of an open source project, and I don't think you are adequate for having close ticket permission because of your arrogance.

**Comment by pedrobaeza** [comment]
OK, as you prefer.

**Comment by pedrobaeza** [comment]
This is an interesting article for you to know my flow that you call arrogance: http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by Yenthe666** [comment]
@sherpya I get that this can be frustrating, I really do. You have to take one thing into mind though: Pedro is doing his very best to manage this issue tracker and he is not awarded or paid anything to do so. Neither am I. Every once in a while we will get somebody that gets mad at us for closing issues and they'll start demanding better support, saying we're incapable and so on.

What we are trying to do is to keep this issue tracker reasonable clean and to get the most important issues or improvements seen by the right pair of eyes. We only have a limited amount of time to do this and we do this as we think is best.

Please don't take this personally but there's just the two of us fighting a big stream of issues - which usually are pretty bad usage - for free to help the eco-system. Again, feel free to make a PR to contribute for these kind of things ;)

**Comment by sherpya** [comment]
@pedrobaeza 
It's like playing a pigeon chess with you, I made the report, I added how to reproduce,
then I found by myself an explanation, and the missing implementation of the specs.
I wasted more time than I can afford.

@Yenthe666 unfortunately is not the first time for pedro:

- https://github.com/odoo/odoo/issues/34306
- https://github.com/odoo/odoo/issues/39387

I also helped a guy with a problem with a bug with a bug closed by pedro as not reproducible (but not remember the number)

and about PR (not about pedro):

- https://github.com/odoo/odoo/pull/20657 

So I understand none of you get paid, but neither am I, wasting my time reporting bug that get closed without reading and PR that get rejected without a reasonable motivation.

As I understand If I have a problem, I need to use different channels **enterprise**, that I also have of course, but I still say this is not the spirit of an opensource project.

I'll never open a bug o propose a pr to odoo repository in the future, if the result is not reproducible because pedro does not get paid, but instead he has nothing better to do rather cleaning the issue tracker from bugs that have no replies in a while, let's be honest, this is the real criteria pedro applies.
You can even simplify the pedro's job, there is a way for github to auto close bugs that not get replies for a while.

**Comment by Yenthe666** [comment]
I've decided to lock this conversation as it is clear this is just ending up in one big discussion in which both parties won't agree basically.
I won't give feedback on the previous issues but I agree with Pedro about this specific issue. It is indeed something that is not implemented. I know Odoo well enough that if we keep this issue open it will never be implemented, along as we have had hundreds of others. You're very welcome to make a PR to add it and I will do my best to fight for your addition to be added but there is not much more we can do.

Sorry if that does not satisfy your needs. Pedro can be heated but he's really experienced and knows what he is talking about so please do give him the benefit of the doubt.
