### ISSUE TITLE
[v12] Is there anyway I can use the store credit/credit memo from sales on POS

### ISSUE THREAD

**Issue by unproZhai** [odoo/odoo#43157]
Impacted versions: 12.0

Steps to reproduce: N/A

Current behavior: Cannot find how to use store credit/credit memo created by regular sales order on pos order.

Expected behavior: When the store credit/credit memo is issued by any sales order, for the same customer, the store credit/credit memo can be used as payment when he/she want to place order through POS.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
