### ISSUE TITLE
Errors in russian .po files

### ISSUE THREAD

**Issue by qqqoid** [odoo/odoo#43161]
Impacted versions:
12
Steps to reproduce:
turn on russian translation
Current behavior:
tons of errors in russian .po files hypotheticaly added with [commit](https://github.com/odoo/odoo/commit/673eaba76f1d21a1f26295de0651762730487dc2#diff-3685fa1d1dd705e837ea7966d1b6f2c4) 
like this translations:
```
"%(user_name)s invited you to follow a new document."
```
to
```
"% (User_name) s пригласил вас следить за новым документом."
```
or
```
"Could not retrieve URL: %(url)s [%(field_name)s: L%(line_number)d]: "
```
to
```
"Не удалось получить URL:% (url) s [% (field_name) s: L% (line_number) d]:% "
```
makes some modules unworking (calendar and mail atleast). 

most part of another "translation" work submited there, exept this two and tons of same errors, goggle-made

Expected behavior:
they may work, i know
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @qqqoid,

Thanks a lot for letting us know. Is there any chance you can correct them yourself on Transifex? See https://github.com/odoo/odoo/wiki/Translations for more information.
@mart-e putting you in here so you're aware about these issues.

**Comment by pedrobaeza** [comment]
I think this was auto-translated from Ukranian as initial best translation available, but it's better than nothing.

**Comment by mart-e** [comment]
@yelizariev could you have a look please? It looks like your translations introduced problems with placeholders

**Comment by yelizariev** [comment]
Yeah, I'll take care of that

**Comment by qqqoid** [comment]
> Thanks a lot for letting us know. Is there any chance you can correct them yourself on Transifex? 

sorry, next time
quickfixed mine by select russian translations containing \%, in my case there was not so much records for manual review every, have no time to do it more thoughtful now

**Comment by qqqoid** [comment]
> I think this was auto-translated from Ukranian as initial best translation available, but it's better than nothing.

not sure, but maybe, anyways translation must work in any case ;)

**Comment by yelizariev** [comment]
@qqqoid I'm sorry for the inconvenience. I've updated the translations on transifex, but it will be synced to this repository on Sunday only.

For a while, you can get corrected translations here: https://github.com/yelizariev/odoo/commits/12.0-fix-russian-i18n

Alternatively, you can get translations from transifex:

```
    # https://www.transifex.com/user/settings/api/
    export TX_TOKEN=<your_Transifex_API_token>

    tx pull -r "odoo-12.*" -l ru -f

```

**Comment by oleg-babintsev** [comment]
Problem is still ongoing.
Typical example from mail addon:
``` 
msgid "%(user_name)s invited you to follow a new document."
msgstr "%(User_name)s  пригласил вас следить за новым документом."
``` 
That will not work correctly because name of placeholder is case sensitive.

Minor issue: in many places you add redundant space symbol before or after placeholder.
Examples:
``` 
msgid "%(user_name)s invited you to follow a new document."
msgstr "%(User_name)s  пригласил вас следить за новым документом."

msgid "%d days overdue"
msgstr " %d дней просрочено"

```

**Comment by yelizariev** [comment]
Latest updates:

* fix &amp;CODE; https://github.com/yelizariev/odoo/commit/a71f7d66bbeabcd109f07ce694f0e3fdffad031b
* fix $ { https://github.com/yelizariev/odoo/commit/f527abe3510c4b14708b01840ad571eda96a2e2b
* fix %(User_name)s, %(Trigger_value) https://github.com/yelizariev/odoo/commit/6ef6e8d0cda4978729dda86a87c43e512db8193a
*  fixing broken mako templates https://github.com/yelizariev/odoo/commit/dee4be07161d6434ac0c1c8cd3c7bba22685417d

I don't see a way to automatically fix extra spaces in translation. It's not really a bug. I'd prefer to have translation with extra spaces on it rather than don't have translation at all.

**Comment by mart-e** [comment]
I have planned a synchronisation of the 12.0 terms for this night as there was some blocking issues. It should be on github tomorrow.

**Comment by yelizariev** [comment]
@mart-e yes, please. I've fixed all known issues

**Comment by mart-e** [comment]
@yelizariev thanks, could you check the other versions too? I am afraid the wrong translations were propagated to the other versions with the [translation memory](https://docs.transifex.com/translation-memory/tm-introduction) of Transifex
For instance, in 13.0 at https://www.transifex.com/odoo/odoo-13/translate/#ru/mail/180734557

**Comment by yelizariev** [comment]
I'll check with 13 and if all works, I apply scripts for 11 and 10.

PS If I will ever  do automatic translation, I would skip all terms with any special characters :tired_face:

**Comment by Yenthe666** [comment]
Nothing beats good old manual translations. I do them manual for a reason 😄

**Comment by yelizariev** [comment]
13.0 is fixed: https://github.com/yelizariev/odoo/commit/ecf58836901a6c35673849c34b5b58a60ef58af4#diff-3685fa1d1dd705e837ea7966d1b6f2c4L45-L53

Script: https://gist.github.com/yelizariev/5cc80c634cce9271132fb141971fe23a#file-move-translation-sh
