### ISSUE TITLE
Tax Base Amount not used in invoice when creating the account move 

### ISSUE THREAD

**Issue by TRESCLOUD** [odoo/odoo#432]
Using OpenERP 7.0, Postgres 9.1, Ubuntu 12.04

When validating a Supplier Invoice (click on button validate) the “Base” amount of the tax lines is not used at all!. That is the created journal entry reports as “Base Tax Amount” the total amount of the invoice instead of reporting the base amount as shown in the invoice form, see attached image which explains it.

![image](https://cloud.githubusercontent.com/assets/2141142/3209746/02e4e2be-ee85-11e3-93ea-1fdb637703c6.png)

Steps to reproduce:
1. Configure a Root Tax (ie “TAX A”) with Tax Type = 10%, and select “Tax on Children”.
2. Configure a Child Tax (ie “TAX A - 1% OF 10% OF TOTAL INVOICE”) with Tax Type = 1%, Account Base Code = “TAX A BASE AMOUNT”, Account Tax Code = “TAX A”
3. Create a purchase invoice, and select the created tax, 
4. Click on validate

Would anybody help confirm if this is an error? I consider this a serious issue as may affect the tax reports.

I think the problem is in file account_invoice.py line 940, the method “move_line_get” should include the field “Base Tax Amount”. Prior going further I would appreciate any support in defining the correct behaviour.

**Comment by Yenthe666** [comment]
Dear @TRESCLOUD,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
