### ISSUE TITLE
[13.0] account: Missing pre-validation hooks before posting an account move

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#43200]
#### Impacted versions:
13.0
#### Steps to reproduce:
Create an invoice with some pre-validation steps before consuming a sequence at post():
https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L2108
#### Current behavior:
There's just a single function `post()` with no easy inheritance and no hooks available for prevalidation steps.

#### Expected behavior:
Have some hooks like we had before:
https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L384

https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_invoice.py#L1368

**Comment by gustavovalverde** [comment]
cc: @smetl @qdp-odoo

**Comment by gustavovalverde** [comment]
Doing this would not require unhealthy workarounds like this one: https://github.com/odoo/odoo/blob/13.0/addons/l10n_latam_invoice_document/models/account_move.py#L33

**Comment by Yenthe666** [comment]
@gustavovalverde why don't you make a PR to improve it? :D

**Comment by gustavovalverde** [comment]
I'm working on PRs for `l10n_do` and `l10n_latam_invoice_document`, after ending those I can surely do it if not done already.

**Comment by nhomar** [comment]
Hello @gustavovalverde 

The way it works now is:

- Overwrite the [action_post](https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py#L2146) (not the post).
- Set your conditions (pre-super).
- Then call the super.

Let me know if it works.

**Comment by nhomar** [comment]
Feel free to re-open the issue if you considere is not solved.

**Comment by gustavovalverde** [comment]
So I suppose this should be change to `action_post`:
https://github.com/odoo/odoo/blob/23e2824794b64624c8dbb1b8132d443657781830/addons/l10n_latam_invoice_document/models/account_move.py#L92

Considering it's a base module for others to inherit, the things done here are to be kept as pre-validations, which could be changed by other localization which depend on `l10n_latam_invoice_document` at `action_post()` or `post()`

cc: @zaoral

**Comment by gustavovalverde** [comment]
PR for `l10n_latam_invoice_document` considering @nhomar suggestion: https://github.com/odoo/odoo/pull/43311/files

**Comment by gustavovalverde** [comment]
Related #43195
