### ISSUE TITLE
[ALL] Wishlist: Add Option for 'binding_view_types' on 'Create Contextual Action'

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43219]
Impacted versions: All

Steps to reproduce: 

![](https://image.prntscr.com/image/KQlQl3-8QCiyq78JR8lPkg.png)

Current behavior:
This action will be Available on List and Form (As `binding_view_types` has a default value `list,form`)
https://github.com/odoo/odoo/blob/0735547086aaab819369b1a08e6810baeac3783d/odoo/addons/base/models/ir_actions.py#L50

![Screenshot (72)](https://user-images.githubusercontent.com/16624719/72266416-4fa34e80-3644-11ea-8fe5-3c7be35fcd8a.png)

![Screenshot (73)](https://user-images.githubusercontent.com/16624719/72266438-59c54d00-3644-11ea-8c44-563de3fecc77.png)

Expected behavior:
Adding an Option for `binding_view_types` during `Create Contextual Action
`
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't consider this as needed, as you can always edit easily the created record and modify it.

**Comment by Yenthe666** [comment]
Yeah this seems out of scope to me too. Remember that we don't want to create an ERP software that has 10.000 options to configure every single detail. This usually results in people getting lost in the options and no longer understanding the system etc.

**Comment by sswapnesh** [comment]
> I don't consider this as needed, as you can always edit easily the created record and modify it.

`binding_view_types` is not visible on view.
