### ISSUE TITLE
[13] [delivery] computed field return_label_ids in stock_picking

### ISSUE THREAD

**Issue by yevbes** [odoo/odoo#43270]
Impacted versions: 13

Compute method  **_compute_return_label** of **return_label_ids** missing the else condition with picking.return_label_ids = False

```python
    def _compute_return_label(self):
        for picking in self:
            if picking.carrier_id:
                picking.return_label_ids = self.env['ir.attachment'].search([('res_model', '=', 'stock.picking'), ('res_id', '=', picking.id), ('name', 'like', '%s%%' % picking.carrier_id.get_return_label_prefix())])
            else:
                picking.return_label_ids = False
```
Steps to reproduce:
Adding **return_label_ids** field to view of model **stock.picking** Odoo throws error 
![imagen](https://user-images.githubusercontent.com/8654386/72340977-735ca800-36c9-11ea-8778-834d82fb10de.png)

Expected behavior:
Able to display stock.picking view

**Comment by nhomar** [comment]
Can you point the functional way to test it please?

thanks in advance.

**Comment by yevbes** [comment]
> Can you point the functional way to test it please?
> 
> thanks in advance.

There is no functional way, it's the code error. Becouse I'm developing Android app and when I'm trying to load stock.picking by it's id, Odoo throws me the following error **load() failed with stock.picking(25,).return_label_ids**, it's becouse when I retrive return_label_ids field it's null not False. And the solution of this I puted above it's simply adding else condition.

Thanks!

**Comment by sle-odoo** [comment]
@pimodoo a small delivery bugfix

**Comment by pimodoo** [comment]
PR: https://github.com/odoo/odoo/pull/43386

**Comment by sle-odoo** [comment]
@yevbes Thanks for you report, this issue will be fixed by https://github.com/odoo/odoo/pull/43386

Regards
