### ISSUE TITLE
Strange behaviour associated with exchange difference entry and context value default_journal_id

### ISSUE THREAD

**Issue by FanisTGT** [odoo/odoo#43285]
Impacted versions: 10.0

Steps to reproduce: Validate some vendor bill (Purchase Journal) and register payment after which exchange different entry will be generated.

Current behavior: exchange different entry account.move is generated inside "Purchase Journal "

Expected behavior: exchange different entry account.move is generated inside "Exchange Gain or Loss Journal" set in company config.

account.move.line
has the related field
journal_id = fields.Many2one('account.journal', related='move_id.journal_id', string='Journal',
        index=True, store=True, copy=False)  # related is required
**but this field is not marked as readonly**

addons.account.models.account_move.AccountFullReconcile._prepare_exchange_diff_move

In the method _prepare_exchange_diff_move we have 
res = {'journal_id': company.currency_exchange_journal_id.id} 
and move created correctly **but** after that line for this move are generated with context that contains default_journal_id therefore move`s journal ("Exchange Gain or Loss Journal") is replaced with ("Purchase Journal").

If I inherit account.move.line and make the field journal_id as readonly this functionality works correctly.
journal_id = fields.Many2one(readonly=True)

What errors can this lead to or is this fix a good solution?

**Comment by Yenthe666** [comment]
Hi,

Sorry but Odoo 10 is no longer officially supported so this means this won't be checked/changed anymore.

Regards,
Yenthe

**Comment by FanisTGT** [comment]
I see this field is not readonly till version 13. I assume this behaviour is reproduced.

**Comment by ws-manatec** [comment]
can also be reproduced in 12
