### ISSUE TITLE
Error: [Errno 13] Permission denied: '/odoo12/odoo12-server/addons/om_hospital/venv'

### ISSUE THREAD

**Issue by mm82299** [odoo/odoo#43293]
Hello,
I'm using Odoo12 CE on ubuntu 18.04, i tried to open a module with Pycharm but i got this error message: 
Error: [Errno 13] Permission denied: '/odoo12/odoo12-server/addons/om_hospital/venv'

**Comment by Elkasitu** [comment]
Not related to Odoo but your deployment (or maybe pycharm, but that's unlikely), your user doesn't have the correct permissions.

You can check who owns the `/odoo12/odoo12-server/addons/om_hospital` directory by doing
```bash
ls -l /odoo12/odoo12-server/addons/om_hospital
```
