### ISSUE TITLE
Payment on account in case of partial payment is wrong

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#43291]
Impacted versions:
13, 12, 11?

Steps to reproduce:
Odoo13 with accounting module
create a vendo bill : 
![Screenshot from 2020-01-14 16-21-55](https://user-images.githubusercontent.com/5735158/72356718-01488b00-36ea-11ea-8ed2-1e8c5623e587.png)

Create a bank statement to post a partial payment on this invoice.
![image](https://user-images.githubusercontent.com/5735158/72357597-82ece880-36eb-11ea-834c-b1a28835e8f1.png)

Reconcile with a payment on account (not a partial payment)
![image](https://user-images.githubusercontent.com/5735158/72357704-b465b400-36eb-11ea-9ec3-12feab744516.png)

The journal entry generated is:
![image](https://user-images.githubusercontent.com/5735158/72357773-d101ec00-36eb-11ea-894b-41abb3f0bff7.png)

You see that odd create a extra line for 141.10 $

Now check on the invoice:
![image](https://user-images.githubusercontent.com/5735158/72357978-22aa7680-36ec-11ea-853b-c144ce8e19b0.png)

Current behavior:
The invoice is fully reconciled and marked as paid whereas it is a partial payment so this is wrong.

Expected behavior:
In case of partial payment (payment amount < invoice amount), Odoo should never give the possibility to do a payment on account -> only do a partial payment

Payment on account should be use only if you want to book a payment and there is no invoice against it.

Note that many software uses payment on account because they cannot handle partial payment so this is the only way...but with odoo we can perfectly handle it.

**Comment by william-andre** [comment]
The generated entry needs to be balanced, so we need to put the remaining amount in an account.

The invoice is marked as reconciled because you validated the reconciliation.
Note that the 141.10 credit line is not reconciled, so it will still appear as a due payment to the vendor in your reports and in the manual reconciliation widget.

**Comment by fclementic2c** [comment]
@william-andre If you just consider journal entries, it is correct, I agree... but think about consequences if you do this with odoo instead of doing a 'normal partial reconcile'.

2 examples:

**Case 1 : In case of partial payment on customer side:**: 
imagine you have a customer invoice for an amount of 525 and you get paid 400.

Print the followup report.
![image](https://user-images.githubusercontent.com/5735158/72523859-fd8b4480-3860-11ea-9134-e15449350ecd.png)
The customer receiving this letter do not know which invoice is open/partially paid

**Case 2 : In case of partial payment on customer side:**
let's say we have a supplier invoice for 525 and you have paid 400.
Then your invoice is fully paid and in the ledger you have an open amount of 125...which is ok.
Now, how can pay the 125 remaining the next time you want to pay you suppliers using SEPA electronic payment ?

you are suppose to select invoice to pay but your invoice is paid so ... we have a problem here

**Comment by william-andre** [comment]
Can you confirm that it is fixed by https://github.com/odoo/enterprise/pull/7074 ?

**Comment by fclementic2c** [comment]
@avw-odoo just informed us this was fixed here : https://t.co/6WwZ7SkwnX?amp=1

**Comment by william-andre** [comment]
Can we close this issue then?

**Comment by fclementic2c** [comment]
ok close it. I will reopen if test not ok

**Comment by eefahd** [comment]
Do you have any idea if this issue would be fixed in community edition as well?

**Comment by william-andre** [comment]
@eefahd No, it has been done in master; the fix will be available on the next release in saas-13.2.

If I'm not mistaken, we cannot backport because it changes the behavior and people might be used to it.
