### ISSUE TITLE
[BUG] Wrong string formatting

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#4331]
**Parts of the same string are mixed in the fields of type "char" and "text" (both) if string contains some Arabic symbols   (example: د.إ -used  in "res.currency"  as symbol of United Arab Emirates dirham)**

Impacted versions:
- 7.0 and above

Steps to reproduce:
1. make some purchases in USD 
2. add payment method for AED (at "Accounting/Configuration/Journals/Journals")
3. go to "Accounting/Suppliers/Supplier Payments" page
4. create a new supplier payment for the supplier you've purchased from in the [1] step and use payment method that you've created in [2] step. So, at this step a currency of payment method chosen is set to AED.

![setp_4](https://cloud.githubusercontent.com/assets/9282767/5491959/f23f266c-86f6-11e4-9fe8-6275c5f12299.png)

Current behavior:
- Broken field of type "text" (same happens with "char" fields too)
- It looks like the original string is broken down in two pieces and then right piece is reversed (because of right-to-left direction of the Arabic script?).

![result](https://cloud.githubusercontent.com/assets/9282767/5492020/6c03078e-86f7-11e4-9875-0bb0efaee62d.png)

OR another example:

![result_2](https://cloud.githubusercontent.com/assets/9282767/5492350/258f0584-86fa-11e4-81e8-0112ddc6a98d.png)

Expected behavior:
- Display string in "text" and "char" fields as is, without breaking it down and without distortion.

**Comment by Yenthe666** [comment]
Hi @tvibliani,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
