### ISSUE TITLE
Website Menus are not translated

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#43365]
Impacted versions:

* 12.0
* 13.0

but works in 11.0

Steps to reproduce:

* Activate translation on website for some language

Current behavior:

Only "Sign in" is translated

Expected behavior:

All menu are translated

Video/Screenshot link (optional):

13.0

![screenshot-879433-13-0-1f6a4e runbot29 odoo com-2020 01 15-20_48_06](https://user-images.githubusercontent.com/186131/72448198-71cdd580-37d8-11ea-92c2-437c21e12581.png)

12.0

![screenshot-876622-12-0-60a558 runbot19 odoo com-2020 01 15-20_48_25](https://user-images.githubusercontent.com/186131/72448222-7abea700-37d8-11ea-934d-9770f7bc7b80.png)

11.0

![screenshot-874842-11-0-10dc32 runbot36 odoo com-2020 01 15-20_48_39](https://user-images.githubusercontent.com/186131/72448254-86aa6900-37d8-11ea-85c0-0d3f4d78cfb5.png)

**Comment by pedrobaeza** [comment]
Have you tried to generate missing terms?

**Comment by yelizariev** [comment]
I've tried on runbot for 12.0 and it doesn't help

http://881129-12-0-3d74e7.runbot35.odoo.com/es_ES/

**Comment by pedrobaeza** [comment]
Indeed, it seems to not work, even loading translation overwriting and marking the website to be translated.

**Comment by Yenthe666** [comment]
Hmm, I've never noticed but you seem to be right actually. I've just tested it on the latest 13.0 with Dutch.
@JKE-be do you know more about this?

**Comment by JKE-be** [comment]
No yet checked, but since original menu is forked on each new website to keep a clean original menu, we probably forgot to duplicate translations.

**Comment by CarmenMiranda** [comment]
**OPW #2209864**

**Comment by hugho-ad** [comment]
@Yenthe666 
This same behavior also happens with qweb views, translations are not forked
