### ISSUE TITLE
[12.0/13.0] Transfer receipts are never translated to the partner's language

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#43377]
Hello,

We came across an issue that seems to be a bug originating from the following template:
https://github.com/odoo/odoo/blob/12.0/addons/account/views/report_payment_receipt_templates.xml#L58

The issue is that whenever printing a transfer receipt, the language is set as the partner_id language, but a transfer does not have a partner_id, which means it will default to English (and not the Company language).

Thank you.

**Comment by pedrobaeza** [comment]
A transfer can have a partner AFAIK, and any way, I think it defaults if not to your DB main language, which can be any.

**Comment by reinaldoramosarxi** [comment]
Hello,

Whenever choosing Internal Transfer, the Partner field is hidden, which means that for all intents and purposes, there is no partner_id.

As for the DB main language, we can't really change it when it comes to SH servers (as far as we know).

Thank you.

**Comment by pedrobaeza** [comment]
I don't know about odoo.sh. In on-premises deployments, it's possible. Tagging this for a proper explanation.

**Comment by sle-odoo** [comment]
Hello,
I think the current behaviour is the right one: "delivery slip" is translated in the partner's lang and "picking" is not translated (ie uses the main language of the database).

Delivery slip are meant to be given to customers, so it makes sense to translate them, while picking are meant to be used internally, so it makes sense to not translate them.

Regards

**Comment by reinaldoramosarxi** [comment]
Hello @sle-odoo ,

I'm sorry, but this template doesn't have anything to do with Stock, it's regarding account transfers (maybe I should've called them that instead of just "transfers"), and these documents are supposed to be viewed by customers.

Like I mentioned earlier, considering we can't change the database's language in SH, we can't really use the DB language as a default. Not only that, but whenever a client has several companies from several countries, they'll want their documents to be translated to those languages by default.

Thank you.

**Comment by sle-odoo** [comment]
Oh okay, i'm tagging this issue as accounting then. Sorry about that.

**Comment by reinaldoramosarxi** [comment]
Hello,

Could we get an update as to what the state of this issue is?

Thank you.

**Comment by reinaldoramosarxi** [comment]
Hello,

Sorry for bothering again, but are there any news regarding this issue?

Thank you.

**Comment by Yenthe666** [comment]
@reinaldoramosarxi nothing untill you hear back from somebody at Odoo. @qdp-odoo perhaps you could take a look?

**Comment by mart-e** [comment]
Hi,

The issue should be fixed at #56020 
Thanks for the report :+1:

**Comment by pedrobaeza** [comment]
Closing then as fixed.
