### ISSUE TITLE
Odoo logs causing server down | [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#43380]
**Impacted versions:**
11,12,13 Community and Enterprise

**Steps to reproduce:**
1- make multi company set up, (company A and B)
2-upload 100K products add some of it under company B
3-create some sales orders in company A and B
4- tray to update the invoicing policy for the 100K items at once 
5- Odoo will start to show this error
`The requested operation cannot be completed due to security restrictions.`
6- the log file will start to increase very fast every 1000 products error will add 3 GB to the logs at the end it will reach 300 GB, If your application server HDD small as most of us do in the deployment,  especially if you have another server for the database and the filestore the normal users can cause a server crash and this error will appear: 
`[Errno 28] No space left on device`

**Recommendation:**
for big files, Odoo should write the errors of the first 1000 lines only and ignore the remaining errors.

**Comment by Yenthe666** [comment]
Hmm interesting. @pedrobaeza what do you think about this? I'm a bit torn between 'you should handle this yourself' and 'maybe there should be at least some logic here'.

**Comment by pedrobaeza** [comment]
The important thing here IMO is the security error and if it's correct or not, but applied to one exact case. The rest is because the number of operations are high, and thus the log gets populated.

Questions:

- If you do it for only one, does it get completed?
- Any way, doing one per one (not all together), all of them are correct? Take into account that if you do things in batch, the whole batch should be correct or nothing will be committed.
- How are you updating that field?

**Comment by Elbagoury** [comment]
@pedrobaeza 
I made this update for 50 products( it was not a common product between the two companies) and no problem, I do it for 2000 products the log was 6 GB and the server not crashed it was crashed only when I used the full file because of the disk not large.

**Comment by Elbagoury** [comment]
@fpodoo @Yenthe666 @pedrobaeza 
I have many databases on odoo online and if someone does this scenario with multiple larger files he can make the odoo online servers crashed so if you are not planning to solve this issue soon please hide this GitHub issue from the public.

**Comment by pedrobaeza** [comment]
Well, I suppose each instance have a maximum log rotating size configured in SH, so not really a great problem, but someone must confirm.

About your problem, I think there's an underlying problem (maybe memory error, that is catched by any of the tries in Odoo code and looked like a security exception). Can you dig a bit more on the problem and locate the initial stacktrace? Also you are still not saying how are you doing that mass-update.

**Comment by Elbagoury** [comment]
@pedrobaeza about my problem I already solved it yesterday and removed the product of company B from the sheet and told my team to always take care of this point, I am only worried about using this kind of log issues as a security threat

**Comment by pedrobaeza** [comment]
If you define a sane deployment of rotating log, it's not. Maybe the noise can be reduced logging only once, but I consider that as an improvement, but not an issue per se.

**Comment by mart-e** [comment]
Hi,

Having 300GB of log files on one action is unusual. Have you checked the content to see if you have not a loglevel too high (e.g. in debug) ?
You should definitely configure a logrotate on your server to avoid having issues when the logfiles are too big (as we do on our SaaS plateform). If you have reasons to believe odoo.com servers are vulnarable to this as an attack vector (I don't think so but maybe I have missed something), please do not hesitate to contact our security team as explained on https://www.odoo.com/security-report

IMHO it is a deployment issue, not a bug of Odoo software.

**Comment by Yenthe666** [comment]
Let's conclude this is a deployment issue and not a bug.
