### ISSUE TITLE
Writing on a warehouse change his partner's default location.

### ISSUE THREAD

**Issue by hparfr** [odoo/odoo#43430]
Impacted versions:
9, 10, 11, 12, 13, master

Steps to reproduce:
Create a partner (supplier), by default his property_stock_supplier is set to Partner/Vendors
Create a warehouse, set it's address to the new partner (supplier)

Current behavior:
[New Partner].property_stock_supplier is set to transit location.

Expected behavior:
[New Partner].property_stock_supplier should not change.

Video/Screenshot link (optional):

Concerned line : https://github.com/odoo/odoo/blob/master/addons/stock/models/stock_warehouse.py#L250

Use case: 
You create warehouse for your supplier because you subcontract some logistics activities to him. You make a purchase order to this supplier. The receipt picking will have this wrong location and you will have some issue thereafter (like never available backorders).

**Comment by pedrobaeza** [comment]
I think this is done on purpose. Can you confirm, @sle-odoo ?

**Comment by pedrobaeza** [comment]
For what you want to do, stock owner should be used.

**Comment by hparfr** [comment]
Stock owner seams the opposite: my walls, other's goods.

**Comment by sle-odoo** [comment]
while i agree it could be unexpected, this behaviour is what most our users would like when working with warehouses.

you should have a look at v13, we greatly improved the subcontracting feature so this isn't needed anymore. see the module mrp_subcontracting and purchase_mrp_subcontracting

related rev 3a16cdebef8de5687070bed7691cf4c955bd128e
