### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by bochen87** [odoo/odoo#43433]
Hi,

Is there any plans to bring 2FA to odoo? In this modern age, where a simple email / password combination is not safe anymore, I would want a system that contains all our customers and finance information to be safe.

**Comment by Yenthe666** [comment]
@mart-e and @odony are the one and only guys who can give concrete feedback I guess :) They know the most.

**Comment by pedrobaeza** [comment]
For that you have OAuth authentication, that can incorporate 2FA or any other improvement, and AFAIK, there's no other plan of complicating Odoo itself incorporating 2FA directly in it having that option.

**Comment by Yenthe666** [comment]
& I guess there's also https://github.com/odoo/odoo/pull/33928

**Comment by bochen87** [comment]
> For that you have OAuth authentication, that can incorporate 2FA or any other improvement, and AFAIK, there's no other plan of complicating Odoo itself incorporating 2FA directly in it having that option.

I see, however i can't see an option to disallow sign in via normal sign-in and use OAauth only.

**Comment by pedrobaeza** [comment]
> I see, however i can't see an option to disallow sign in via normal sign-in and use OAauth only.

If you don't have any regular user, then you can't sign in through that way.

**Comment by odony** [comment]
Yes, there is #33928 :)

**Comment by odony** [comment]
This requires some core changes in the session management stack in order to do properly, so we don't plan to do that in stable versions. If OAuth/LDAP solutions are not satisfying in the meantime, third-party implementations might be of interest to you - see https://www.odoo.com/apps for example
