### ISSUE TITLE
When retrieve the price of a product with mehtod "_get_real_price_currency" use product_currency

### ISSUE THREAD

**Issue by nicomacr** [odoo/odoo#43439]
Impacted versions:
since 11.0

This would be better than instead of using the company's currency using the product currency which is a compute field that is calculated based on the company. This can be useful to allow inheriting that method.

[This](https://github.com/odoo/odoo/blob/11.0/addons/sale/models/sale.py#L1180) is part of the code that i suggest the change in this #43438

**Comment by pedrobaeza** [comment]
Please don't put an issue if you are going to create a pull request, and doing a pull request in stable versions should mean that there's something to fix, not an improvement, which I'm not sure is the case.
