### ISSUE TITLE
Integer value not supported in selection field.

### ISSUE THREAD

**Issue by rameshwordhakal** [odoo/odoo#43444]
Impacted versions: Odoo 13

Steps to reproduce: Create selection field with integer or boolean value and that shows the above error message. 

Current behavior: "Field %s with non-str value in selection" % self

Expected behavior: Expected to work as it was in Odoo 12.

Video/Screenshot link (optional):

Example:
```
class InvoiceStatus(Enum):
    OPEN = 1
    PENDING = 2
    CLOSED = 3
class Invoice(models.Model):
   _name = 'ir.invoice'
   status = fields.Selection([(InvoiceStatus.OPEN.value, 'Open'), (InvoiceStatus.PENDING.value, 
   'Partially Paid'), (InvoiceStatus.CLOSED.value, 'Closed')], default=InvoiceStatus.OPEN.value, 
   track_visibility='onchange')
```

![Screenshot from 2020-01-17 11-30-36](https://user-images.githubusercontent.com/13719738/72587291-d2fec180-391c-11ea-927f-78f45334e076.png)

**Comment by Elkasitu** [comment]
Not a bug, it was an intended change of #29039, integers are no longer valid keys for `Selection` fields

**Comment by omarKady** [comment]
> Not a bug, it was an intended change of #29039, integers are no longer valid keys for `Selection` fields
is that in version 13 only ??

**Comment by Elkasitu** [comment]
From version 13 onwards, yes
