### ISSUE TITLE
Wishlist: Modify testcase 'test_01_free_delivery_when_exceed_threshold'

### ISSUE THREAD

**Issue by t-sq1** [odoo/odoo#43478]
Impacted versions: v13

Steps to reproduce: unpublish 'free delivery charges' by default. That means adding this line to data.xml:
```
<record id="delivery.free_delivery_carrier" model="delivery.carrier">
        <field name="website_published" eval="False"/>
</record>
```

Current behavior: Testcase 'test_01_free_delivery_when_exceed_threshold' in website_sale_delivery module fails with the following error:
```
FAIL: TestUi.test_01_free_delivery_when_exceed_threshold
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/website_sale_delivery/tests/test_ui.py", line 23, in test_01_free_delivery_when_exceed_threshold
    self.start_tour("/", 'check_free_delivery', login="admin")
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1105, in start_tour
    res = self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1089, in browser_js
    self.fail('%s\n%s' % (message, error))
AssertionError: The test code "odoo.startTour('check_free_delivery')" failed
Tour check_free_delivery failed at step Check Free Delivery value to be zero (trigger: #delivery_carrier span:contains('0.0'))
```

Expected behavior: By modifying the setting
```
self.env.ref("delivery.free_delivery_carrier").write({
            'name': 'Delivery Now Free Over 10',
            'fixed_price': 2,
            'free_over': True,
            'amount': 10,            
        })
```
with 'website_published': True, the test would run successfully even the free delivery charges are unpublished in general. 

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
This test is not an unit test, it's an integration / business flow / UI test that assumes the role of an end user who tries to purchase something and use free delivery.

Of course, if you set the option for free delivery to `website_published=False` then the "user" won't see the free delivery option and thus the flow is broken and the test fails, this is normal.

**Comment by t-sq1** [comment]
@Elkasitu thanks for your comment. 
I know why the test is failing, but we don't need free delivery charges. We have our own delivery methods, so we would like to disable 'free delivery charges'.

The test runs successfully - even with 'free delivery charges' deactivated - when 'website_published = True' is added to the test.

**Comment by Elkasitu** [comment]
Sorry but I do not understand the problem, are you trying to run tests in a production environment or are you making your own module?

**Comment by t-sq1** [comment]
Yes, I made my own module and I switched off 'free delivery charges', because we have different shipping methods and don't need the standard ones. 
So far this is no problem. 

By installing my module on odoo.sh this testcase is always failing (for sure). That is way I asked to add the attribute `'website_published':True`. The test then runs as expected, but I can use my custom settings with free delivery charges deactivated/unpublished.

**Comment by Elkasitu** [comment]
Ah ok I understand now, since the test is executed at `post_install` while relying on the default setting of `website_published`, any module that extends this particular `delivery.carrier` (like yours) and changes the default will make the test fail, and the solution should indeed be what you suggest: explicitly setting `website_published` in the test.

I will make a PR later / tomorrow or you can try making one yourself if you feel confident :)

**Comment by t-sq1** [comment]
I have not made a Pull Request yet. Could you possibly tell me what I have to choose here: 

[
![image](https://user-images.githubusercontent.com/51234014/73237817-1b2ca800-4197-11ea-9a2c-c006783a0a64.png)
](url)

Do I have to create a branch in my repository containing this module with the change in the testcase for comparing?

Generally I feel confident to do so ;-)

**Comment by Yenthe666** [comment]
@t-sq1 yeah you create a new branch in your fork from Odoo. In this fork you make the changes and then you make a PR into the 13.0 branch from Odoo from your custom branch.

**Comment by t-sq1** [comment]
PR is done: https://github.com/odoo/odoo/pull/45148

Thanks!
