### ISSUE TITLE
[7.0] onchange dont update readonly fields

### ISSUE THREAD

**Issue by jorgebarcelo** [odoo/odoo#4348]
Hello.
Im aware everyone know the problem with on_change functionality where readonly fields dont update the value when the record is save. But this time i found this problem is more severe than that.

If you only worry about visualization, using on_change + field.function it works, because on_change update the actual web value and the field.function calculate the value when the record is beeing loaded. But im working on a more complicated functionality and found a problem (severe in my opinion).

I'm working in a form view, having a tree view specified for a one2many field. In soe of those fields i have on_change to calculate value of readonly fields. The problem come when i set on_change on on2many field, using itself as a parameter. On python i get the list of tuples, as anyone expect....but the values of the readonly fields are NOT upgraded. Those values only change when i save+reload the form, but it's too late for the on_change function set on the field, rendering that on_change in a complete failure.

Is this on purpose???? We need a noteditablebyuser feature :(

**Comment by yaniaular** [comment]
This affects me. For now I read that can be solved using a functional field, but I do not like..

**Comment by yaniaular** [comment]
The why and the solution https://www.odoo.com/forum/help-1/question/how-to-handle-reading-and-writing-to-read-only-fields-2247

**Comment by Yenthe666** [comment]
Hi @jorgebarcelo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
