### ISSUE TITLE
[13.0]account invoice report can not print label have  multi-line

### ISSUE THREAD

**Issue by SmithLin0618** [odoo/odoo#43516]
Impacted versions:13.0 

Steps to reproduce: 
1.go Accounting >Customers >Invoices
2.Create an invoice and enter multiple lines of text in the LABEL of the invoice details
3.Print report "invoices"or"invoices without Payment"

Current behavior:
account invoice report can not print label have  multi-line like gif

Expected behavior:
Like previous versions can print multiple lines

Video/Screenshot link (optional):
![錄製_2020_01_18_06_29_52_361](https://user-images.githubusercontent.com/38001362/72650699-2b38d080-39bc-11ea-802c-51af244f9aad.gif)

**Comment by william-andre** [comment]
Hello.

I just tried it in v13.0 (enterprise but it shouldn't be different), and I don't have that issue. Can you reproduce it on runbot?
![image](https://user-images.githubusercontent.com/44770049/73537508-e9327480-4428-11ea-9214-2ba39e0c6a68.png)

**Comment by Yenthe666** [comment]
I'm closing this issue as there has been no feedback on the question from @william-andre.
