### ISSUE TITLE
Odoo Mobile App

### ISSUE THREAD

**Issue by Maikelbeerens** [odoo/odoo#43519]
Impacted versions: 13 local server install

Steps to reproduce: Open the app

Current behavior: In the webbrowser Odoo can visualize 2 Companies at the same time or just one if you deselect the other. The functionality of selecting them both gives you the possibility to have a CRM overview of both companies at the same time.

Expected behavior: In the mobile app you can select only one company at the time, this could be improved by also visualizing the both companies. but this is not possible 

Video/Screenshot link (optional):

Double selection in webbrowser:

![image](https://user-images.githubusercontent.com/60045518/72669373-4abe1080-3a31-11ea-946f-c6cc9d510c5f.png)

single selection in App:

![Screenshot_20200118-203134_Odoo](https://user-images.githubusercontent.com/60045518/72669425-d3d54780-3a31-11ea-804a-da1db0200951.jpg)

Hope this can be improved.

Kind regards,

Maikel

**Comment by pedrobaeza** [comment]
As this is something of enterprise, and not specifically a bug, but an improvement, please put your report at odoo.com/help instead of here. I'm closing this then.
