### ISSUE TITLE
[13.0] can't create two refunds from same vendor bill

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#43518]
Impacted versions:
13.0

Steps to reproduce:
1. chose a demo vendor bill
2. make a partial refund and validate it
3. go back to the vendor bill
4. create a ne partial refund

Current behavior:
* this error is raised:
```
Duplicated vendor reference detected. You probably encoded twice the same vendor bill/credit note:
Azure Interior - Reversal of: BILL/2018/0001 - 01/18/2020
```

Expected behavior:
* No error raised

Video/Screenshot link (optional):
* Check in [this video](https://drive.google.com/file/d/1Q0f-b3f56cyDXbkurgePgxu4pW63M7E5/view)

**Comment by jjscarafia** [comment]
fyi @ren-odoo @jco-odoo @zaoral 
this is not related to l10n_ar o l10n_latam, it's odoo default behavior.

**Comment by william-andre** [comment]
Do you have a use case where it is needed to do multiple reversal of the same bill, at the same date?
Couldn't you just put something in the 'Reason' field?

**Comment by jjscarafia** [comment]
Well. Really it is not common to make to reversal on of the same bill on the same date. But it could happens.
For me it's a bug because we're raising an error and not giving the possibility to continue (it's not a warning).
I didn't figured out that using a reason would be enough. Perhaps, at least the message could give more information (like suggesting using a different message on the 'reason field')

It's not a big bug (or problem) for me. I just report it to help improving odoo (and to avoid tickets to odoo support team from users)

Thanks!

**Comment by william-andre** [comment]
I understand. The issue here is that we use the same field as the vendor reference field to put the reversal reason. We will take that into account for the master branch but we can't do anything in stable, as the message would be weird if we weren't in that specific case. (which is as you said is not common)

Thanks for your feedback.
