### ISSUE TITLE
How to change height v.12

### ISSUE THREAD

**Issue by Senarist01** [odoo/odoo#43520]
Hello, I want to change the height of all fields(search and all rows  Product Variants ) in module product_product.

what should I do for this? Thx
![d](https://user-images.githubusercontent.com/60047264/72670305-ebc2c080-3a5d-11ea-894d-90d41d2ae68f.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
