### ISSUE TITLE
[IMP][13.0] Inventory move validation timeout with large list of products, should process in batches like import

### ISSUE THREAD

**Issue by GamesmenJordan** [odoo/odoo#43523]
Impacted versions:

- 13

Steps to reproduce:

1. Create inventory move with a large list of products (eg. 20,000)
2. Submit move for validation
3. Eventually (depending on server configuration) the connection will drop and then Odoo will restore the connection and the inventory move will not have processed

Current behavior:

- Inventory move is impossible to complete

Expected behavior:

- Inventory move should be completed in batches like import
- Connection should be kept alive with polling

Whilst it is possible to work around this issue by creating smaller inventory moves, or by modifying server configuration for on-premises installations, but for companies with large amounts of SKUs this can introduce a lot of additional work splitting out stocktake reports and uploading each individually.

**Comment by pedrobaeza** [comment]
You must increase your timeout in your deployments for such a large case.

For the rest, the explanation given in https://github.com/odoo/odoo/issues/43153#issuecomment-573694540 applies the same here, so closing.

**Comment by GamesmenJordan** [comment]
What if you are on a managed platform like Odoo.sh where you cannot edit the nginx configuration to increase the timeout? Not to mention increasing the timeout of a HTTP request to say 1 hour is a terrible workaround for an application-level issue.

**Comment by pedrobaeza** [comment]
Nginx timeout doesn't abort the process. You will find the inventory validated when finished.

**Comment by GamesmenJordan** [comment]
That is not the experience that we have had. Regardless, the point stands that on a managed system it's not always possible to change the timeout and doesn't address my concern that increasing the timeout isn't the correct approach to solve this kind of issue, it's like burning down your house to kill a spider.

**Comment by pedrobaeza** [comment]
It's the only you have for now, or cut in smaller batches. Odoo is continuously trying to improve performance, but in a stable version, it's not possible to change that.
