### ISSUE TITLE
V12 Mybe a bug with default= fields.Datetime, Mybe more version

### ISSUE THREAD

**Issue by youngtl** [odoo/odoo#43524]
Impacted versions: V12, I think maybe more version have this problem

Steps to reproduce: default= fields.Datetime.now,this method or something put user local_time to UTC_time,when show in browser it's wrong result; 
I think this mybe between JS 、Server、Browser interaction problem,
And the doc https://www.odoo.com/documentation/12.0/reference/orm.html#date-and-datetime-fields use the same method.
In the Stock module use the same method too,and the problem also have.
This problem https://www.odoo.com/zh_CN/forum/help-1/question/solved-date-time-in-odoo-with-python-86073 is the same.
My english is not very well,Mybe the picture is good.

Current behavior:use this method  default=lambda self: fields.datetime.utcnow()

Expected behavior:change the JS or change the doc,

Video/Screenshot link (optional):

![Odoo Time 1](https://user-images.githubusercontent.com/30487691/72698202-0a1fdd80-3b7e-11ea-8790-882d72599c3c.png)
![Odoo Time 2](https://user-images.githubusercontent.com/30487691/72698203-0ab87400-3b7e-11ea-91e6-af2352f41074.png)
![Odoo Time 3](https://user-images.githubusercontent.com/30487691/72698204-0ab87400-3b7e-11ea-8fa7-41489c9bf1ec.png)
![Odoo Time 4](https://user-images.githubusercontent.com/30487691/72698205-0ab87400-3b7e-11ea-9b0d-f1e749a4a902.png)

**Comment by youngtl** [comment]
I clear the cookie , change the brower ,the problem also hace

**Comment by pedrobaeza** [comment]
Sorry, but your English is not understandable. It seems that you have to configure your timezone. Closing this while not information is given to think this is a bug.
