### ISSUE TITLE
[13.0] snailmail_account_followup broken method

### ISSUE THREAD

**Issue by i-vyshnevska** [odoo/odoo#43535]
Impacted versions:
13
Steps to reproduce:
install and run snailmail_account_followup

Broken piece:
method _execute_followup_partner in snailmail wasn't migrated properly and belongs to OTHER model
I am not sure that snail mail follows invoice addres as seems it send directly to partner

https://github.com/odoo/enterprise/blob/01b4f30022d6a9556813975eaeb4d3e279da9e93/snailmail_account_followup/models/account_followup_report.py#L15
on v13 it executed on self and doesn't have required argument for partner

**Comment by pedrobaeza** [comment]
As this is something enterprise, please report it in odoo.com/help instead.
