### ISSUE TITLE
Theme Odoo Enterprise version 11

### ISSUE THREAD

**Issue by HashiramaTwT** [odoo/odoo#43540]
Hello everyone, Which version browser can compatible with theme odoo enterprise 11?
1. Firefox.
2. Microsoft Edge.
3. Chrome.
Thanks,

**Comment by Yenthe666** [comment]
Hi,

It should work with all browsers :) IE is not a really loved browser and is usually a little worse than the others.

**Comment by HashiramaTwT** [comment]
But my customer want i must provide version

**Comment by Yenthe666** [comment]
The newest versions of those browsers will work fine ;)
