### ISSUE TITLE
ondelete='cascade' needed

### ISSUE THREAD

**Issue by stanevicius1** [odoo/odoo#43585]
https://github.com/odoo/odoo/blob/a13c05fa5df9c98504e8e1cdb09d8d4a8d13ea91/odoo/addons/base/res/res_users.py#L1029

**Comment by Elkasitu** [comment]
Can you elaborate?

- [ ] What version does this happen on?
- [ ] Does it trigger an actual bug in Odoo?
- [ ] What are the steps to reproduce this bug?

**Comment by sswapnesh** [comment]
> ondelete='cascade' needed 

https://github.com/odoo/odoo/blob/8622469e1fdd4789cc45ed52093d0f329abca14e/odoo/fields.py#L2337

ondelete='cascade' is default for transient model and required field

**Comment by stanevicius1** [comment]
> Can you elaborate?
> 
> * [ ]  What version does this happen on?
> * [ ]  Does it trigger an actual bug in Odoo?
> * [ ]  What are the steps to reproduce this bug?

11v community.
sentry captures not null error.
needs to be added ondelete='cascade' for a 'change.password.user' model on wizard_id field.
`wizard_id = fields.Many2one('change.password.wizard', string='Wizard', required=True, ondelete='cascade') 
`

**Comment by Yenthe666** [comment]
There's really no need, even if the ORM doesn't handle it directly the cron that cleans up wizard records will handle this every day anyways.

**Comment by stanevicius1** [comment]
> There's really no need, even if the ORM doesn't handle it directly the cron that cleans up wizard records will handle this every day anyways.

so you are saying that errors means nothing? because next retry will be ok so we can ignore wrong logic? :)
Wrong attitude.

**Comment by Yenthe666** [comment]
There's really no bug happening. The wizard loads, you can change the password and its being applied. The system will clean up transient records automatically and is designed to do that.. so I don't see any bug thats preventing you from doing anything?

**Comment by stanevicius1** [comment]
There is no cascade and that's why odoo is raising errors and flooding sentry.
it's simple logic mistake then you are requiring relation from temporary to temporary record without cascade because deletion doesn't check priorities of deletions. Am I wrong?

**Comment by Elkasitu** [comment]
It was fixed in `13.0` at #36738, however this fix is not backportable because it breaks our [stable policy](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).

Yes the logic is flawed but fixing it imposes a risk that makes the reward not worth it, worst case-scenario you wait for the transient records to be garbage-collected or you can force it by executing the autovacuum automated action.
