### ISSUE TITLE
[13] hr_holidays: Duration should be readonly if Time Off is Approved

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43594]
Impacted versions: 13.0

Steps to reproduce: Add Time Off request and Approve it
![Screenshot (83)](https://user-images.githubusercontent.com/16624719/72749514-45eb8f00-3be0-11ea-8c05-04a48a172882.png)

Current behavior:  Duration is Editable after Time Off request is approved

Expected behavior: Duration should be Readonly (Like Date fields)
![Screenshot (84)](https://user-images.githubusercontent.com/16624719/72749530-51d75100-3be0-11ea-9cd5-2e26ee6682f0.png)

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This seems on Purpose
From https://github.com/odoo/odoo/commit/09e515eecc5610c8af0c3989b5b023ad435ca437
```
6. In the leave form view, there are currently two duration fields
for managers. The readonly duration is an informative field for regular
employees and the editable duration is meant for managers, it's used if
the number of days needs to be manually set for some reason.
Make sure the manager only sees the editable duration fields.
```

Cc @LucasLefevre

**Comment by LucasLefevre** [comment]
@sswapnesh Thanks for the feedback. But as you mention, this has been done on purpose.
Hence, this issue is not really an issue ^^
I guess it can be closed.

Lucas
