### ISSUE TITLE
[13.0] Mega Menu doesn't open when menu is toggled

### ISSUE THREAD

**Issue by actonsys** [odoo/odoo#43599]
Impacted versions: 13.0 CE & EE, tested on runbot

Steps to reproduce:
    **For instance:
        1. Set Shop menu as "is_mega_menu"
        2. Drag Shop menu to the end of the menu list
        3. On website, click on + toggle menu sign, and click and try to open mega menu Shop**

Current behavior:
    **Following above case, megamenu Shop doesn't open and also toggled menu is closed**
    
**Such issue has a huge bad impact on Ipad screens.**

Expected behavior:
    Following above case, mega-menu Shop opens

Video/Screenshot link (optional):
![Peek 2020-01-20 19-07](https://user-images.githubusercontent.com/31458943/72752975-8c7ac280-3bbb-11ea-8a25-ba9cf0bba069.gif)

**Comment by pedrobaeza** [comment]
That's because megamenus can't be shown on the dropdown, so this expected.

Closing as something expected / assumed restriction.

**Comment by actonsys** [comment]
Where this limitation was stated by Odoo?

**Comment by pedrobaeza** [comment]
Where do you want that to be stated?

**Comment by actonsys** [comment]
No, keep it hidden.

**Comment by pedrobaeza** [comment]
I'm not keeping anything. I'm asking where do you expect to see it for improving that part.

NOTE: I'm not Odoo employee. I'm doing this as a community voluntary effort.

**Comment by actonsys** [comment]
It's a retoric question made from you. You know very well where it should be stated. 
Try to talk about this with an EE client and you will get a better answer.
Cheers.

**Comment by pedrobaeza** [comment]
TBH I don't get you, but if this is your final word then I can't help you in anything more.

**Comment by actonsys** [comment]
Who closes this BIG ISSUE was you, not me. So you gave the final word.
On contrary what you said, megamenu opens normally when menu is toggled but with the hamburger. The issue is only with the + toggle, so very doubtful it's a Oddo restriction and not an issue.
