### ISSUE TITLE
[13] crm_iap_lead_website: Statusbar is not visible properly in header

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43598]
Impacted versions: 13.0

Steps to reproduce: Have a look at `crm_iap_lead_website.crm_reveal_view_form`

Current behavior:  Observer the `reveal_state` field on Header
![Screenshot (85)](https://user-images.githubusercontent.com/16624719/72752327-edb88b00-3be7-11ea-8e72-a28bf493268f.png)

After Save
![Screenshot (86)](https://user-images.githubusercontent.com/16624719/72752402-1b053900-3be8-11ea-8ab0-7bca3b269985.png)

Expected behavior:  Should be displayed like 
![Screenshot (87)](https://user-images.githubusercontent.com/16624719/72752428-2b1d1880-3be8-11ea-93be-5f9a0b321d11.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Why don't you create a quick PR for it? :)These kind of things fill up the issue tracker for very small details.

**Comment by sswapnesh** [comment]
I tried but it didn't worked. 
You can see in the screenshot above. ( Adding readonly does display status bar properly)

**Comment by sswapnesh** [comment]
@Yenthe666  It seems to be an issue of Web Framework instead of crm_iap_lead_website
See https://github.com/odoo/odoo/issues/43701

**Comment by khuepham-novobi** [comment]
@sswapnesh Have you resolved this issue?

**Comment by sswapnesh** [comment]
This has been fixed meanwhile.
