### ISSUE TITLE
[IMP] Customer address changes should not propagate in historical sales orders

### ISSUE THREAD

**Issue by GamesmenJordan** [odoo/odoo#43608]
Sales Orders should preserve the historical data of the delivery/invoice (by way of copying the data instead of a reference) at the time of order with limited ability to edit the address and contact identity -- subject to configurable preferences (ex. only before payment, only by staff or never).

It is industry standard to make paid invoices immutable and depending on the law, may be legally required.

At an operations level, allowing customers to edit address causes the historical invoice data to become incorrect, this can cause problems when investigating delivery issues.

Furthermore, many anti-fraud systems use address data to validate orders, particularly savvy fraudsters could provide address which pass validation and change them to deliver to a different address - our sales and warehouse teams would not be aware of this and a notification on every customer address change would be overwhelming in volume of sales.

**Comment by pedrobaeza** [comment]
This has been discussed other times. @Yenthe666 do you have the reference to that issue?

**Comment by Yenthe666** [comment]
Hmm this has indeed been discussed a few times before. I couldn't directly find one of the discussions yet (but some search options for Odoo in Github are still messed up a bit). The conclusion didn't change though: it works as Odoo wants it to work and there was no plan to change this. You could further restrict it with some custom development on your own instance though :)
