### ISSUE TITLE
When I try to establish a multi-company set up this error occurs

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#4360]
cr.execute('update '+self._table+' set parent_left=%s,parent_right=%s where id=%s', (pleft+1, pleft+2, id_new))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
