### ISSUE TITLE
[13] [Wishlist] crm_iap_lead: Add Option to make 'Lead Mining Request' draft again

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43601]
Impacted versions: 13.0

Steps to reproduce: Create new Lead Mining Request and Submit it

Current behavior: On Error, there is no Option to Edir Request and Re-submit as all Fields are Readonly
![Screenshot (90)](https://user-images.githubusercontent.com/16624719/72753688-91576a80-3beb-11ea-963d-5079703ee58b.png)

Expected behavior: Add an Option to make it draft and edit some fields, so the user can re-submit it with correct values. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
For me the flow is clear: duplicate it and put other params.

**Comment by sswapnesh** [comment]
I would suggest adding A button As we have at all other places "Reset to Draft"

**Comment by pedrobaeza** [comment]
But there's no sense in reusing this "document". In other places where the button is there it's because it makes sense that.

**Comment by sswapnesh** [comment]
I just got to know the method to make it Draft is already implemented. (But Button is not added on View)

https://github.com/odoo/odoo/blob/13.0/addons/crm_iap_lead/models/crm_iap_lead_mining_request.py#L189

**Comment by pedrobaeza** [comment]
Well, let's see what Odoo thinks. Probably the method was added, but later thought the same as me.
