### ISSUE TITLE
[13] account: 'Invoiced' smart button doesn't dispaly Unposted Invoices after Removing default filter

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43605]
Impacted versions: 13

Steps to reproduce: Create Invoice for a Partner (Pay one of them and Keep one Unposted)
![Screenshot (92)](https://user-images.githubusercontent.com/16624719/72756135-5b69b480-3bf2-11ea-9ea4-20d490d939c8.png)
Go to Contact --> Invoiced Smart Buton --> Remove 'Posted' filter

Current behavior:   It doesn't display Draft Invoice

![Screenshot (93)](https://user-images.githubusercontent.com/16624719/72756294-bef3e200-3bf2-11ea-8dea-9c0214abc69c.png)
![Screenshot (94)](https://user-images.githubusercontent.com/16624719/72756348-eea2ea00-3bf2-11ea-83e9-534bb0bfb180.png)

Expected behavior: Display Draft Invoices

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/48557

**Comment by Yenthe666** [comment]
Thanks for cleaning up @sswapnesh
