### ISSUE TITLE
How a Salary Rule is parsed and evaluated ?

### ISSUE THREAD

**Issue by diassynthesis** [odoo/odoo#4363]
According to https://www.odoo.com/forum/help-1/question/hr-payroll-salary-rule-computation-bug-68602    https://github.com/odoo/odoo/issues/3916, why no SyntaxError or TypeError is raised ?

**Comment by jaredkipe** [comment]
Why would you think it should?
A typo in a variable name on assignment just results in a new variable, and this can be used to make more expressive computations.

Are you saying that if if result is not assigned at some point during execution you want an exception raised?

**Comment by Yenthe666** [comment]
Hi @diassynthesis ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
