### ISSUE TITLE
[13.0] Rule mts_else_mto not take the on hand quantity.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#43630]
Impacted versions:
13.0, master

Steps to reproduce:
1. Create a product A
2. Set Routes:  Replenish on Order (MTO) and Manufacture
3. Update Quantity: Set 5 on hand.
4. Create a sale order, sell 10 A.
5. Confirm the sale order
6. A Manufacture Order is created to manufacture 10 A

Current behavior:
There are 5 A in the stock , why not take 5 A from stock ,and manufacture 5 A.
Is there any way the get this behavior?

Expected behavior:
take 5 A from stock ,and manufacture 5 A

**Comment by sle-odoo** [comment]
Hello,
At the moment, the mtso rule doesn't split the procurement, it means if you create a SO for 1, 2, 3, 4 ou 5 units, nothing will be manufactured, if you create a so for 6, 7, etc.. everything will be manufactured.

We have an ongoing task to improve this behaviour and split the procurement between the qty available and the qty to buy, but it's a little tricky since 1) there will be two moves, one mts one mto 2) we have to actually reserve the mts move at this point, even if the settings to automatically reserve mo after an so is disabled.

Regards

**Comment by tanghulu0608** [comment]
thanks

**Comment by tanghulu0608** [comment]
@sle-odoo  Any news about this behavior ?

**Comment by sle-odoo** [comment]
@tanghulu0608 it's really not a priority at the moment

**Comment by tanghulu0608** [comment]
@sle-odoo  Thanks

**Comment by spoerp** [comment]
One of our prospect client really needs this kind of behavior. I can understand if its not a priority, but can you give some pointers on how can we achieve it.
It would be really helpful

**Comment by tanghulu0608** [comment]
Yes. We need this behavior too.

**Comment by tanghulu0608** [comment]
Hope V14 can bring this behavior.

**Comment by spoerp** [comment]
> Hello,
> At the moment, the mtso rule doesn't split the procurement, it means if you create a SO for 1, 2, 3, 4 ou 5 units, nothing will be manufactured, if you create a so for 6, 7, etc.. everything will be manufactured.
> 
> We have an ongoing task to improve this behaviour and split the procurement between the qty available and the qty to buy, but it's a little tricky since 1) there will be two moves, one mts one mto 2) we have to actually reserve the mts move at this point, even if the settings to automatically reserve the moves after an so is disabled.
> 
> Regards

Can't we modify the logic in the Stock Move itself, where a single move is created, which will reserve the stock from warehouse first, and then also trigger MTO for the remaining stock. And that move can have multiple stock.move.line to handle stock coming from our warehouse and lets say from Vendor.

**Comment by gandiff** [comment]
My company requires this behavior, so I've been trying to write a custom module to implement it, but I'm new to Odoo development. Has anyone successfully achieved this?

**Comment by anderwm** [comment]
Looks like they are looking to squash the whole MTS-MTO concept. I also thought it should work the way suggested above and started looking into it. It is difficult on a number of fronts. Another one not mentioned here is that how to reassemble the move.line(s) on the Manufacturing order. As it works (in v13) the amount procured is the amount in the consumed line (product_uom_qty). In other words the same move line is used in the downstream procurement as in the top level Manufacturing Order.

**Comment by tanghulu0608** [comment]
> Hello, At the moment, the mtso rule doesn't split the procurement, it means if you create a SO for 1, 2, 3, 4 ou 5 units, nothing will be manufactured, if you create a so for 6, 7, etc.. everything will be manufactured.
> 
> We have an ongoing task to improve this behaviour and split the procurement between the qty available and the qty to buy, but it's a little tricky since 1) there will be two moves, one mts one mto 2) we have to actually reserve the mts move at this point, even if the settings to automatically reserve the moves after an so is disabled.
> 
> Regards

Hello, Any news about this topic?

**Comment by andyengh** [comment]
@sle-odoo Is this already a priority?
