### ISSUE TITLE
[12.0/13.0] Mobile view doesn't show some document types' document names

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#43640]
Hello,

Whenever viewing documents on mobile, we think that some fields shouldn't be omitted, and the document name is an important one.

As it happens, the document name doesn't show on mobile views - at least in sale orders and stock pickings - while it does on invoices and manufacturing orders:
![image](https://user-images.githubusercontent.com/42942314/72801915-7a903280-3c42-11ea-8ea3-8aede7fc49b9.png)

![image](https://user-images.githubusercontent.com/42942314/72801982-a8757700-3c42-11ea-97db-2f2302fd38fd.png)

![image](https://user-images.githubusercontent.com/42942314/72801934-87ad2180-3c42-11ea-8c06-6d8dde57f3bc.png)

![image](https://user-images.githubusercontent.com/42942314/72801958-95fb3d80-3c42-11ea-86a9-97c7cfec6523.png)

One could argue that the name shows up in the breadcrumbs, but it's bad user experience to have these differences between different document views.

Thank you.

**Comment by pedrobaeza** [comment]
Please report this kind of things through odoo.com/enterprise, not here, as this is something related to the enterprise web client.

**Comment by reinaldoramosarxi** [comment]
Ok, thank you.
