### ISSUE TITLE
[web_forum] Direct link to a specific answer - New feature request

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#4364]
Since a lot of work is going on in the forum portion of odoo right now I thought I would put in my wish list idea.

There are times that I want to provide a direct link to a specific answer on the forum.  Each answer has it's own unique URL if you know how to build it.  However that url is not provide for each answer.  Here is an example URL:

https://www.odoo.com/forum/help-1/question/69767/#answer-69797

Currently the only place this URL is system generated is on the users answers (however you can only see the last 20 answers).

I would like to see every answer have the URL linked to it so that it could be copied.  The easiest place would be on the words "Answered on" that would link back to that specific answer.  Then I could right click and copy the link to be used elsewhere in a forum reply or on a blog post.

Maybe this feature should be part of the new SEO code that is being written for the forum making one of the options a direct link to the answer.

Just some ideas.

**Comment by JKE-be** [comment]
Hello,

We have fixed the issue in V8 about the 'direct link' for comment here : commit 30a6be0
We have fixed the issue in V8 about the name 'False' here : commit 0de1d89

Thank you for the reporting !

**Comment by Yenthe666** [comment]
Wooh awesome! When will this be ported into the help forums from Odoo @JKE-be ?

**Comment by JKE-be** [comment]
Hello,

View and python code has been updated ! 

Best regards

JKE
