### ISSUE TITLE
[IMP 8.0, 7.0, 6.1] hr_holidays leave day count calculation from resources 

### ISSUE THREAD

**Issue by ehirt** [odoo/odoo#4365]
There is an old todo line 260 in hr_holidays.py when calculation the day count of a leave in the procedure def _get_number_of_days that is used by the onchange_date_from and onchange_date_to that also have to be enhanced to do so.

Further the holidays_validate (holidays_validate2 for 6.1) procedure calculates wrong duration of the meetings.
And this procedure should further support the option to define leaves for calendar_id instead of only categories and employees for setting general leaves per calendar/for all calendar in the resources.

With the option to edit all resource_leaves in the holidays the hr_holiday shall make the resource_leaves also readonly and update the corresponding leave when editing the holday.

I'm happy to provided this improvement and otherwise do it for ourselfs anyway. Please comment

**Comment by Yenthe666** [comment]
Hi @ehirt,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

P.S: Don't hesitate to make PR's - they're very welcomed and usually have a much better response rate.

Regards,
Yenthe
