### ISSUE TITLE
[8.0] ( Critical ! )  Taxes in Supplier Invoice lines 

### ISSUE THREAD

**Issue by discovery6000** [odoo/odoo#4366]
Hello,

When I create an invoice from an outgoing shipments (without purchase order), the taxes ares not evaluated.

Here is the scenario :

1 - Create an outgoing shipment (without purchase order) with an article witch include a supplier tax
2 - Validate the shipment
3 - Create the invoice

The supplier taxes are not present in the invoice line,

Thanks

**Comment by Yenthe666** [comment]
Hi @discovery6000,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
