### ISSUE TITLE
Lack of documentation for plan attribute of gantt view

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#43686]
https://www.odoo.com/documentation/13.0/reference/views.html#gantt

The documentation doesn't explain what setting the plan attribute will do

**Comment by Feyensv** [comment]
Introduced in https://github.com/odoo/enterprise/commit/8f1368b097b496194de34407002489479c2fdac4, I'll add some documentation ;).

**Comment by Feyensv** [comment]
Well, it is documented, but not clearly enough ;).
![image](https://user-images.githubusercontent.com/19364378/72883800-4598e400-3d05-11ea-895f-5bf96eedd262.png)

**Comment by frlanxpertiz** [comment]
In addition to this point, 

- the description of the progress field doesn't really say what the value of the field will do in the view, how it will be represented visually.

-  IMO the use of [group_expand](https://github.com/odoo/odoo/pull/13496) to display groups that don't have record in the kanban view (like with the action planning.planning_action_schedule_by_employee) should be documented here, at least a short line that says that it's possible and that point to an example in the code.

**Comment by frlanxpertiz** [comment]
there's also a mistake in the possible value for decoration. I think that only 
        'decoration-secondary',
        'decoration-success',
        'decoration-info',
        'decoration-warning',
        'decoration-danger'

are allowed for Gantt view

**Comment by Feyensv** [comment]
Indeed, the other ones are not supported.
![image](https://user-images.githubusercontent.com/19364378/72895989-037c9c00-3d1f-11ea-845d-cdac89ac2dc0.png)

**Comment by Feyensv** [comment]
I'll link the group_expand information in the search views instead, as it impacts multiple views and is ultimately linked to the search.
