### ISSUE TITLE
[13] account: Invoice creation from Grouped Kanban should be blocked

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43699]
Impacted versions: 13.0

Steps to reproduce: Add New Invoice on from `Posted` column
![Screenshot (99)](https://user-images.githubusercontent.com/16624719/72832800-967bee80-3cab-11ea-94df-57110fef3d7e.png)

Current behavior:  New Invoice is created Directly on Posted State
![Screenshot (100)](https://user-images.githubusercontent.com/16624719/72832851-a98ebe80-3cab-11ea-8611-4fcdc0a0e6b4.png)

Expected behavior: Invoice should not be created from here.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Technically this is not incorrect: you are able to reset to draft.

**Comment by sswapnesh** [comment]
I would suggest something like this https://github.com/odoo/odoo/commit/abd9d1506ea4af29a98278c4cbd514e2cf4c54f3

**Comment by pedrobaeza** [comment]
I don't think Odoo should add all this specific code for something that is undoable. It complicates maintenance, and you know what are you doing using quick create that way.

**Comment by sswapnesh** [comment]
For Financial records, This should be blocked. 

(At least Posted Invoice without any Entries should not be possible ever)

**Comment by pedrobaeza** [comment]
Why? They are neutral.

**Comment by Yenthe666** [comment]
@oco-odoo can maybe make the final call on this one :)

**Comment by oco-odoo** [comment]
I agree with @pedrobaeza . I'm closing the issue, we won't change that ;)
