### ISSUE TITLE
[13.0] Cannot (re)assign a contact to an individual through base.view_partner_form

### ISSUE THREAD

**Issue by GamesmenJordan** [odoo/odoo#43708]
Impacted versions:

- 13

Steps to reproduce:

1. Add contact/alternative address to an existing individual type contact
2. Open the new contact from the contacts page (so the contact opens in base.view_partner_form)
3. Clear the parent_id field and try to add to the same or another individual

Current behavior:

- Currently assigned parent does not exist as a valid option
- Cannot assign an individual type contact only company type contacts

Expected behavior:

- Contacts can be children of any contact type, therefore all contacts should be valid options

**Comment by pedrobaeza** [comment]
I'm able to do do it in runbot. Maybe I have missed any step. Please provide a video with all the steps.

**Comment by Yenthe666** [comment]
I'm closing this bug report as there has been no response/feedback to the questions asked by @pedrobaeza
