### ISSUE TITLE
[13] web: widget="statusbar" is not displayed correctly if field name is other than state

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#43701]
Impacted versions: 13.0

Steps to reproduce:  Add widget="statusbar" on field (Eg, `reveal_state` See `crm_iap_lead_website.crm_reveal_view_form`)

Current behavior: 

![](https://user-images.githubusercontent.com/16624719/72752402-1b053900-3be8-11ea-8ab0-7bca3b269985.png)

Expected behavior: On local Instance, I have renamed field from `reveal_state` to `state` to check this and seem to work fine.

![Screenshot - 2020-01-22T002819 294](https://user-images.githubusercontent.com/16624719/72834059-1a36da80-3cae-11ea-8ded-d81a6f0881e7.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sswapnesh I think there has to be something else. I've got a custom module with a custom state field in V13 that works just fine:
![image](https://user-images.githubusercontent.com/6352350/72872710-4c682c80-3cee-11ea-8f89-ea8071324845.png)

**Comment by sswapnesh** [comment]
Maybe it's working fine in enterprise addition.
Can you please check on Community too?

**Comment by khuepham-novobi** [comment]
@Yenthe666 Was this issue resolved? I have got a same issue with odoo 13. I'm using enterprise edition
![image](https://user-images.githubusercontent.com/46312680/80709222-233e1000-8b17-11ea-8e02-614f9dbbd9a5.png)

**Comment by Yenthe666** [comment]
Works fine for me, I've got multiple in place in V13. What's your code?

**Comment by khuepham-novobi** [comment]
Hello, I resolved this issue, because I added the field "state" into the form, so it's duplicated. Need to copy a new field for displaying in the form instead of using state twice.

**Comment by Yenthe666** [comment]
Yep for sure :) @sswapnesh do you still have this issue though?

**Comment by sswapnesh** [comment]
This has been fixed meanwhile.

@khuepham-novobi  In my case it was from Framework itself. (As mentioned in #43598)
