### ISSUE TITLE
[13] Incorrectly calculated initial debit and credit 

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#43736]
Impacted versions:
13

Steps to reproduce:

Create opening move with two lines with the same account 
(Where summary balance is divided into a partner)
For example:

account: Account Receivable (code 121000), partner: ABC, Debit: 100
account: Account Receivable (code 121000), partner: XYZ, Debit: 222
 
Current behavior:

opening_debit = 222
(single randomly Debit)

Expected behavior:

opening_debit = 322

**Comment by pedrobaeza** [comment]
But where do you see that `opening_debit`?

**Comment by zbik2607** [comment]
Model account.account

    opening_debit = fields.Monetary(string="Opening debit", compute='_compute_opening_debit_credit', inverse='_set_opening_debit', help="Opening debit value for this account.")
    opening_credit = fields.Monetary(string="Opening credit", compute='_compute_opening_debit_credit', inverse='_set_opening_credit', help="Opening credit value for this account.")

**Comment by pedrobaeza** [comment]
But if that fields are not used in UI, you don't know what is their intention and how they are computed, so that doesn't mean this is an error. Please specify if this is used incorrectly in standard (for example, showing it in a runbot)

**Comment by zbik2607** [comment]
No comment, only quotation: **help="Opening debit value for this account."**

**Comment by pedrobaeza** [comment]
As said, where do you see it in UI?

**Comment by zbik2607** [comment]
UI is the only one usability of Odoo?

**Comment by pedrobaeza** [comment]
It's the proper way to query things. If they are not shown, they can be dead code or similar, so not always should be solved according what you expect to do.

**Comment by zbik2607** [comment]
I have a slightly different opinion on "code cleanliness and usability". If the code is dead, delete it.

**Comment by pedrobaeza** [comment]
That can't be done in a stable version. See https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean. Any way, I'm not saying that is dead code. I'm just saying that if you don't have any steps to reproduce the problem in UI, then the problem shouldn't be fixable and you as developer should use any other thing as foundation for what you want to do, unless someone in Odoo decides that the computed field deserves to be repaired.

**Comment by zbik2607** [comment]
Ok, your answer is reasonable. I only reported a problem.

**Comment by Yenthe666** [comment]
We'll it is in the wizard to setup accounts so it is in the UI though:
https://github.com/odoo/odoo/blob/7acd855ba155e0de33f4bd4634dd1daa0850a394/addons/account/wizard/setup_wizards_view.xml#L72-L86

And there are computes:
https://github.com/odoo/odoo/blob/7acd855ba155e0de33f4bd4634dd1daa0850a394/addons/account/models/account.py#L331-L343

Which mentions "could be executed at most twice: once for credit, once for debit" Since the second debit line is `222` and the query gives this back as last result it means it is set to `222` instead of `322` (your 100 + 222) since there is no += operator for the `opening_debit`
Maybe @qsm-odoo or @oco-odoo can explain this a bit more, my accounting knowledge doesn't go far enough :)

**Comment by qsm-odoo** [comment]
I guess you meant to ping @qdp-odoo

**Comment by Yenthe666** [comment]
I absolutely did. Sorry @qsm-odoo!

**Comment by oco-odoo** [comment]
Hmm, indeed this is a little buggy, though multiple lines were not suppose to happen if you only configured the opening move through the setup bar (which is the use of that computed field). 

It's fixed here https://github.com/odoo/odoo/pull/43903 . So, to compute the field, we add the total as @Yenthe666 suggested, and when using the setup list view and trying to overwrite the balance of multiple lines, we group them first into a single one.
