### ISSUE TITLE
[13.0] [eLearning] Image Problem

### ISSUE THREAD

**Issue by odoo-backend-dev** [odoo/odoo#43745]
Hi
in eLearning Module when you add video from youtube after save your videos thumbnail don't save.
![Screenshot from 2020-01-22 15-23-04](https://user-images.githubusercontent.com/58971895/72892616-36795c80-3d2c-11ea-84a6-8d2ec06e6bab.png)

**Comment by Yenthe666** [comment]
@dbeguin for you probably

**Comment by dbeguin** [comment]
Task created (https://www.odoo.com/web#id=2182638&action=333&active_id=965&model=project.task&view_type=form&menu_id=4720)
Thanks for your feedback ! 
We will handle this asap. (But we are in a rush for incoming freeze next week. So this might wait a bit)

**Comment by pedrobaeza** [comment]
Is this solved then?

**Comment by dbeguin** [comment]
Yes ! Fixed at https://github.com/odoo/odoo/commit/15af8734c5d16a358cababb6163863b30e24f8cc
