### ISSUE TITLE
Documentation clashes with code

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#4377]
The [orm reference#field-access](https://github.com/odoo/odoo/blob/8.0/doc/reference/orm.rst#field-access) doc says:
> Trying to read or write a field on multiple records will raise an error.

But [the code](https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L5486) says:
> If `key` is an integer or a slice, return the corresponding record
selection as an instance (attached to `self.env`).
Otherwise read the field `key` of the first record in `self`.
Examples::
inst = model.search(dom) # inst is a recordset
r4 = inst[3] # fourth record in inst
rs = inst[10:20] # subset of inst
nm = rs['name'] # name of first record in inst

The [slides from the odoo days](http://www.slideshare.net/openobject/odoo-from-v7-to-v8-the-new-api) (page 8) say the same thing as the code comment.

@xmo-odoo which one is correct?

**Comment by xmo-odoo** [comment]
@LeartS: the documentation. The original behaviour was for attribute access to operate on the first record of a recordset (as in e.g. jQuery), but when @rco-odoo discussed it with the community (e.g. @nbessi and others) during the opendays training the consensus was that this would lead to non-obvious behaviour and risk hiding bugs, and the behaviour was changed to not allow reading from recordsets with multiple records.

On master you can easily test it in the shell contributed by @dreispt:
```python
>>> env['res.partner'].search([]).name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "odoo/openerp/fields.py", line 764, in __get__
    record.ensure_one()
  File "odoo/openerp/models.py", line 5210, in ensure_one
    raise except_orm("ValueError", "Expected singleton: %s" % self)
except_orm: ('ValueError', 'Expected singleton: res.partner(6, 33, 32, 3, 7, 43, 42, 18, 57, 12, 48, 49, 14, 51, 17, 56, 19, 58, 59, 8, 44, 45, 9, 36, 35, 34, 5, 10, 46, 47, 31, 26, 66, 65, 64, 16, 55, 54, 13, 50, 20, 60, 30, 22, 61, 29, 11, 37, 24, 38, 21, 39, 40, 15, 52, 53, 23, 62, 63, 28, 67, 27, 41, 1, 68, 69)')
>>> env['res.partner'].search([])[0].name
u'ASUSTeK'
```
It looks like the docstring was not updated when the behaviour changed.
