### ISSUE TITLE
[12.0] Attribute requirered not work when dependent is text type

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#43776]
In a view with two fields, when a field is dependent of other, and is text type, it not work:

python:
a = fields.Char()
b = fields.Date() or (Text, Textarea, etc)

xml:
< field name="a"/>
< field name="b" attrs="{'required': [('a', '!=', False)]}"/>

I try also with:

< field name="b" attrs="{'required': [('a', '!=', '')]}"/>
< field name="b" attrs="{'required': [('a', '=', True)]}"/>

Is bug or this is incorrect?

**Comment by kos94ok-3D** [comment]
Which Odoo version?
And do you reload the page after changes?

**Comment by igallart** [comment]
Version 12.0, and yes, I reload, thanks.

**Comment by kos94ok-3D** [comment]
It is a bug.

**Comment by kos94ok-3D** [comment]
@pedrobaeza can you add Framework label for it?

**Comment by kos94ok-3D** [comment]
@Yenthe666 11.0 and 13.0 have the same bug

**Comment by sswapnesh** [comment]
This should work 
`< field name="b" attrs="{'required': [('a', '!=', '')]}"/>`

**Comment by cramosh** [comment]
![imagen](https://user-images.githubusercontent.com/34350771/72915277-5450bc80-3d40-11ea-9260-84326717d11f.png)

In firefox and in chrome the attrs required doesn't  correct function with dependent with text file. Neither with false nor with ''

**Comment by kos94ok-3D** [comment]
not only required, all attrs

**Comment by kos94ok-3D** [comment]
with '' all work.
Tested on Firefox 72.0.1 and Google Chrome 73.0.3683.103

**Comment by igallart** [comment]
In runbot, works fine, but when create, it is required and the value is empty. after if you save, it seems to be fine and works fine, It's a bit strange.

**Comment by sswapnesh** [comment]
> with '' all work.
> Tested on Firefox 72.0.1 and Google Chrome 73.0.3683.103

We can close it then
