### ISSUE TITLE
[8.0] POS picking transfers for service product

### ISSUE THREAD

**Issue by haroldtamo** [odoo/odoo#4378]
To reproduce the bug :
-create a service product available in POS
-open a POS session
-make an order with the service product
-go to warehouse>All operations for "Your company:POS orders"
a transfer has been created.
Not normal for a service product since it must not generate stock moves i guess.

**Comment by Yenthe666** [comment]
Hi @haroldtamo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
