### ISSUE TITLE
[13.0] Mobile many2one field dropdown issue

### ISSUE THREAD

**Issue by Sameerawan** [odoo/odoo#43790]
Impacted versions: odoo 13 Community and Enterprise

Steps to reproduce: Sale Order products should be shown in the dropdown mobile view.

Current behavior: Trying to create a sale order in mobile when i click on create then select product system is not showing any product.

Expected behavior: It should show the products in the dropdown mobile the same as a computer.

Video/Screenshot link (optional): 
![New - Odoo](https://user-images.githubusercontent.com/23479835/72913628-7b15ef80-3d4e-11ea-9ca8-15fd9604c4ed.png)
![New - Odoo (1)](https://user-images.githubusercontent.com/23479835/72913629-7b15ef80-3d4e-11ea-8c65-037f20b87fc7.png)

**Comment by Yenthe666** [comment]
@Sameerawan I just tested this on the latest 13.0 and it seems fixed in the meanwhile! 🥳
