### ISSUE TITLE
lines supplier payment

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#4385]
1) Steps to reproduce the issue you have observed 
1.- Create a new supplier payment
2.- Put this quantity: 74750.9000
3.- Save the payment
4.- Edit the payment
5.- Remove an lines to payment
6.- Save the payment

You can see the next video:
https://www.youtube.com/watch?v=Ve3W_WpYfNk
2) The result you observed
After that I removed the lines, when I save the payment the lines return.

 3) The result you expected
After to save, I dont have lines that I were removed.

4) The Odoo commit:
9ab18cd149fccbd844e075caf25e7239c2939dde

**Comment by rha-odoo** [comment]
fixed d17f22c
