### ISSUE TITLE
[Kanban] Misplaced arrow on tip

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#4386]
On some tips over a kanban item, the arrow is misplaced.

![misplaced arrow on tip](https://cloud.githubusercontent.com/assets/7599891/5534569/fb497726-8a89-11e4-847a-5d244a3082be.png)

![projects - odoo](https://cloud.githubusercontent.com/assets/7599891/5534558/bf4a3e4a-8a89-11e4-860c-daff74e1102a.png)

Automatically consider top position even if not change view port still it's consider.

Effected version: 8.0

**Comment by Yenthe666** [comment]
Hi @imjaypatel ,

Thank you for your bug report. This has been fixed in newer versions of Odoo.

Regards,
Yenthe
