### ISSUE TITLE
ORM / Sorted View Issue

### ISSUE THREAD

**Issue by kvangass** [odoo/odoo#439]
Impacted versions:
6.1 to current
This issue was found in the accounting currency module and traced back.

The issue is located in orm.py in the _read_flat function. On line 3343 there is a for loop that takes the requested ids and splits them into groups of 1000 which it then queries from the database. The result of the query is then appended to the "res" list. 

The problem is that the SQL engine is being used to sort the ids. So an unsorted list of ids is being send to _read_flat. Which then splits them into batches of 1000 and queries the database. The database then sorts the ids and returns them. It then gets it's next batch of ids and sorts them. The trouble is that there is no merge between the sorted list of ids. However many batches of 1000 there are are all sorted separately and appended together without any sorting.

The issue can be resolved by simply getting rid of the for loop.However I don't know if this will cause issues elsewhere in the system. I tried poking around on my local system but have not done any serious testing without the for loop. 

           query = 'SELECT %s FROM %s WHERE %s.id IN %%s' % (select_fields, ','.join(tables), self._table)
            if rule_clause:
                query += " AND " + (' OR '.join(rule_clause))
            query += " ORDER BY " + order_by
            for sub_ids in cr.split_for_in_conditions(ids):
                cr.execute(query, [tuple(sub_ids)] + rule_params)
                results = cr.dictfetchall()
                result_ids = [x['id'] for x in results]
                self._check_record_rules_result_count(cr, user, sub_ids, result_ids, 'read', context=context)
                res.extend(results)

**Comment by xmo-odoo** [comment]
I don't think there's a way to merge the lists, save by selecting the sorting criteria as first item of each tuple and re-sorting based on that (in which case there isn't really a point in doing an in-db sorting).

Removing the split could work, checking the history it seems to have been added because Postgres would crash on overly large `IN` parameters, checking 9.3 postgres is fine with a million ids in the `IN` clause, though from there on requests do start taking a long time (possibly more because of the request's serialisation than performing the request itself). Or maybe just increase the batch size to somewhat ridiculous sizes (100k?)

/cc @rco-odoo @odony

**Comment by odony** [comment]
What's the practical use case for changing this? Yes it can sometimes cause `read()` to return unsorted results, but the ordering of `read()` results is known to be irrelevant.
This is why all client stacks (including the web client) rely on `search()` or `search_read()` for the ordering, and reorder the results of `read()` accordingly if needed. Any direct call to `read()` where the ordering matters could presumably do the same.
If we bumped up the split limit we would not really get rid of this issue, just reduce the chances, and even if recent PG versions have better tolerance for longer lists, we cannot change this in older stable versions, which require compatibility with older releases (Odoo 6.1 = PG8.3, Odoo 7 = PG 8.4). The results probably also depend on the platform and PG configuration.

**Comment by xmo-odoo** [comment]
> What's the practical use case for changing this? Yes it can sometimes cause read() to return unsorted results, but the ordering of read() results is known to be irrelevant.

But in that case we might as well not tack on an `order by` to the query no?

**Comment by odony** [comment]
On 01/14/2015 05:45 PM, xmo-odoo wrote:
>
> But in that case we might as well not tack on an |order by| to the query no?

Well it's still nice provide a stable ordering of the results, at a relatively 
minor cost. The default semi-random ordering returned by PG tends to cause a 
lot of surprises for users and developers (POLA rule).
But `search()` is definitely the right method for looking up and ordering 
records, `read()` being then called only on a small relevant subset of the 
results returned by `search()`.

**Comment by Yenthe666** [comment]
Hi @kvangass,

@mart-e made a commit for this back in 2015 but this issue has never been closed.
Closing this since there has been a fix for it.
