### ISSUE TITLE
Final invoice amount does not consider deposite amount if credit note is linked Odoo 13 enterprise

### ISSUE THREAD

**Issue by pooja-zakhariya** [odoo/odoo#43919]
Impacted versions:
13.0
Steps to reproduce:
- Create sales order.
- Create down payment invoice with amount same as invoice amount and mark it as paid.
- Create credit note against this down payment with amount lower than down payment and mark it as paid.
- Create final invoice. Final invoice created with full amount as in sales order. It does not consider remaining down payment amount.

Current behavior:
Final invoice does not consider down payment remaining amount.

Expected behavior:
It should be created with sales amount - down payment remaining amount .

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=zccpRC6QsMs&feature=youtu.be

**Comment by Yenthe666** [comment]
Hi,

This is a limitation at the moment, I've reported something very similar. 
It won't be changed in stable versions so you won't see a solution for this before V14 for sure.

Regards,
Yenthe
