### ISSUE TITLE
[13] discount on product grid is not apply

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#43970]
**Impacted versions:**
13
**Steps to reproduce:**

- Configure pricelist to show discount
- Configure product with variants
- Configure **Order Grid Selection**
- Add product to Sale order, and discount is not aplied.

Note: First video show working fine, second video show bad working

![Untitled Project](https://user-images.githubusercontent.com/7775116/73139478-5bc3de80-403c-11ea-860a-77c8f8d638b0.gif)
**Current behavior:**
![after](https://user-images.githubusercontent.com/7775116/73139489-70a07200-403c-11ea-93ea-41b7385e5f4c.gif)
**Expected behavior:**
discount must be applied to products, independly product's configurator

CC: @dbo-odoo @nim-odoo 

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Added fix at #43972
