### ISSUE TITLE
[13.0]Missing filters in event track 

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#43982]
Impacted versions:13.0

Current behavior: Not showing tags

Expected behavior:Showing tags

Video/Screenshot link (optional):
![Design Fair Los Angeles   My Website](https://user-images.githubusercontent.com/51145639/73161700-66947700-4101-11ea-83b7-5f009ae7c5bd.png)

**Comment by pedrobaeza** [comment]
Are they published?

**Comment by bahram-css** [comment]
I used some tags for "event tracks" and they are not showing in list below of "All Tags" section on page.

**Comment by bahram-css** [comment]
Will you confirm this or not?

**Comment by JKE-be** [comment]
Hello

If your tag are in transparent (color: hide in kanban) their are not publishe don the website too.
You need to assign a color to your tag to make it visible.

Color transparent if for internal tag.
