### ISSUE TITLE
[13] sale: Improve warning message on Invalid Sales Target

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44051]
Impacted versions: 13.0

Steps to reproduce: Set Sales Target on Float or Some Chars (Typos)

Current behavior: Warning message saying "Float values are supported" while Target is Integer field

![Screenshot (81)](https://user-images.githubusercontent.com/16624719/73203806-cb80b900-4163-11ea-8844-26bdcf021957.png)

Expected behavior:  Warning should be "Only Integer Value should be valid."

We already have code  (Still not sure) for this at https://github.com/odoo/odoo/blob/41e196268c443ace08faa80023f8584edbed0efa/addons/sale/static/src/js/sale.js#L48

Video/Screenshot link (optional):

**Comment by Feyensv** [comment]
The float are currently not supported, but will have to be to fix #42992.
