### ISSUE TITLE
[Wishlist] propagate attrs attributes from parent tags to fileds

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#44090]
```
<group readonly="1">
    <field name="field1"/>
    <field name="field2"/>
</group>
```
Current behavior:
**Is equal**
```
<group>
    <field name="field1"/>
    <field name="field2"/>
</group>
```

Expected behavior:
**Is equal**
```
<group>
    <field name="field1" readonly="1"/>
    <field name="field2" readonly="1"/>
</group>
```

**Comment by sehrishnaz** [comment]
Hope these tips will help you: [Odoo Customization Tips](https://www.scoop.it/t/learn-openerp)

**Comment by pedrobaeza** [comment]
Group are not able to propagate readonly to its children, so it's the expected behavior, and thus closing.

**Comment by kos94ok-3D** [comment]
@pedrobaeza, sorry for my mistake.
I wanted to write the desired behavior.

**Comment by pedrobaeza** [comment]
Yeah, but I don't think this is easy to achieve nor following the best practices, as the readonly control is always by something visible, and group isn't it.
