### ISSUE TITLE
[13.0] Down payment doesn't keep track of changed amount on invoice line

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#44114]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 with the admin user
2. Go to Sales > Quotations and create a new quotation for a company. Add the product "Air Flight" on the order and confirm the order
3. Click on "Create invoice" and do a "Down payment (percentage)" for 50%. You'll now see an invoice like this:
![image](https://user-images.githubusercontent.com/6352350/73269828-d37d3f00-41dd-11ea-91ad-094a2949affc.png)
4. Modify this invoice and change the price from "350" to "200" and save.
5. Go back to the sale order from which you've created the down payment. You'll now see that the Down payment line still shows "350" while you've set it to "200" on the invoice:
![image](https://user-images.githubusercontent.com/6352350/73269938-06bfce00-41de-11ea-8be0-a79db38705fe.png)

Current behavior: You have inconsistencies now. The line on the sale order shows "350" while it should show "200" just like on the draft invoice. If you now go back to the sale order and click on "Create Invoice" again and then choose for "Regular Invoice" with the option "Deduct Down Payments" you'll get a second invoice which also seems to be wrong.

Expected behavior:
If the price on the Down Payment is changed it should change on the sale order line too.

**Comment by Yenthe666** [comment]
OPW `2184197`

**Comment by alpeshvalaki** [comment]
similar  to issue #44114

**Comment by ADVALAKI** [comment]
similar to issue #44114

**Comment by ADVALAKI** [comment]
similar to issue #43919

**Comment by Yenthe666** [comment]
The conclusion was that it won't be changed in a stable version. There's a feedback task to change this in future versions though so fingers crossed.

**Comment by ADVALAKI** [comment]
i thinks v13 is not as stable as 12 for accounting. there is number of issues. and some cant be fix in stable version. :(

**Comment by Yenthe666** [comment]
In most places Odoo 13 has improved quite a bit so its worth it I guess. They just did a big refactor so there are some things that need time
