### ISSUE TITLE
500: Internal Server Error / Template fallback  An error occured while rendering the template 3069.

### ISSUE THREAD

**Issue by Ahmedposhi** [odoo/odoo#44116]
![internal_server_error_500](https://user-images.githubusercontent.com/40128980/73271249-e8ab9b00-41e8-11ea-8ee5-69f77b927164.png)
Impacted versions:

Steps to reproduce: after uninstall third party module like: odoo debranding, website theme flexible, then the website give me this error as described in attached. current version is odoo 13.

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Can you please add reproducible steps? Without these steps there's nothing we can do to help.

**Comment by Alimaher10** [comment]
@Ahmedposhi
Hello,
did you solved the issue ?
please let me knows steps of solution.

**Comment by AquaMCU** [comment]
I have the same issue. Unfortunately I can not reproduce this. My client added some pages.

Unfortunately the template fallback does not work. 

Error while render the template
ValueError: Element „<xpath expr="//a[hasclass(&#39;oe_unremovable&#39;)]">“ kann nicht in der übergeordneten Ansicht lokalisiert werden.
Template: website.template_header_mobile
Path: /t/t/div/div/div[2]/ul[2]/t[4]
Node: <t t-call="website.header_call_to_action_large"/>

Der Fehler ist beim Rendering der Vorlage aufgetreten website.template_header_mobile und beim Evaluieren des folgenden Ausdrucks: <t t-call="website.header_call_to_action_large"/>
