### ISSUE TITLE
Translations are coming through http instead of https (mixed content blocked)

### ISSUE THREAD

**Issue by marclijour** [odoo/odoo#44110]
Impacted versions: 13

Steps to reproduce:
- install Odoo behind Nginx as a https endpoint and reverse proxy following [the instructions](https://www.odoo.com/documentation/13.0/setup/deploy.html#https)
- build a website in French (default language)
- enable English as a second language and translate the site

Current behavior:
- menus show up ok when user is logged in
- menus in the second language don't show for a public (not logged in) user (first language menus are ok)
- furthermore application like event registration are not working in the second language (javascript doesn't load)

Expected behavior:
- menus should show normally for all languages enabled
- applications such as event registration should work in all languages enabled

Video/Screenshot link (optional):

![Screenshot from 2020-01-28 08-30-20](https://user-images.githubusercontent.com/4466879/73268285-b8440c80-41a8-11ea-9893-b8acb0514376.png)
![Screenshot from 2020-01-28 08-29-31](https://user-images.githubusercontent.com/4466879/73268287-b8440c80-41a8-11ea-8fd2-acdc38be5cea.png)
![Screenshot from 2020-01-28 08-25-40](https://user-images.githubusercontent.com/4466879/73268288-b8440c80-41a8-11ea-86d5-b2d8314a9dfb.png)
![Screenshot from 2020-01-28 08-25-02](https://user-images.githubusercontent.com/4466879/73268289-b8440c80-41a8-11ea-8340-7bb9654591f5.png)
![Screenshot from 2020-01-28 08-24-03](https://user-images.githubusercontent.com/4466879/73268290-b8dca300-41a8-11ea-8b46-699cfb94c8ef.png)
![Screenshot from 2020-01-28 08-23-39](https://user-images.githubusercontent.com/4466879/73268291-b8dca300-41a8-11ea-9db5-4839f9121cd3.png)

**Comment by marclijour** [comment]
Looking more into this, the problem happens when a XMLHttpRequest is issued from @web.assets_commons_lazy.js. The https is ok in the requested URL but the response header comes back with a 302 to downgrade to http. I'm stuck there. (Is it possible this cannot connect to https thus trying http?)

![Screenshot from 2020-01-28 13-09-01](https://user-images.githubusercontent.com/4466879/73292248-b3468380-41cf-11ea-9f68-0946ba6c470c.png)
![Screenshot from 2020-01-28 13-13-07](https://user-images.githubusercontent.com/4466879/73292382-f30d6b00-41cf-11ea-92ef-5d93118f1100.png)

**Comment by marclijour** [comment]
My mistake. 
I was missing this line in the Nginx config file (which line is actually in the docs -ok).
`proxy_set_header X-Forwarded-Host $host;`

**Comment by hydrandt** [comment]
@marclijour, thank you for investigating this issue in here. I am facing the exactly same problem. However,  I do include `proxy_set_header X-Forwarded-Host $host;` already, yet, only this one specific 302 redirect happens. I can see it in Odoo log. Would be grateful for any suggestions.

**Comment by hydrandt** [comment]
In the end, the problem was `proxy_mode = True` slipping out of my odoo.conf. After re-adding it, the redirect happens over https again.

**Comment by C2dricLeroy** [comment]
Hello ! 

I am encoutering  the exact same problem,  

I do have proxy_mode = True in my odoo.conf and Nginx has the necessary headers (checked by my sysadmin). 

The weirdest part is that I have the exact same configuration in both preproduction and production, but the error only occurs in my preproduction environment.

I can provide details if needed, 

Does anyone have any idea ?
