### ISSUE TITLE
programming error: extra call of account.move.post() function.

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#4412]
**a post() function of "account.move" object  is called twice**

Impacted versions:
- 7.0 and above

Steps to reproduce:
1. Create a new journal entry, for do so go to "Accounting/Journal Entries/Journal Entries" page and click on "Create" button.
2. In the "Journal" field choose a journal with "Skip 'Draft' State for Manual Entries" property enabled. 
3. Fill in other mandatory fields as well.
4. Click on "Post" button.

Current behavior:
- The post() function is called twice, once upon account.move creation and then in the handler function of "Post" button. The two calls are made each time, instead of one call.

Expected behavior:
- Call post() function only once, regardless of state of "Skip 'Draft' State for Manual Entries" property. Second call should be avoided (in the second call you're posting an "account.move" entry, that is already posted by previous call).

**Comment by Yenthe666** [comment]
Hi @tvibliani ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
