### ISSUE TITLE
Bank Account when creating a request for Quotation

### ISSUE THREAD

**Issue by earceda** [odoo/odoo#44133]
**Impacted versions:** v13

**Steps to reproduce:** If I create a Bill from a request for quotation, the Bank Account field appears empty, even though the vendor has a bank account defined. But I create the bill directly from the Bill form the Bank Account field shows the value of the vendor´s bank account.   

**Current behavior:**  If I create a Bill from a request for quotation, the Bank Account field appears empty, 

**Expected behavior**:  If I create an invoice from a budget request, the Bank account field must complete the value of the vendor's bank account.   

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Added Fix at https://github.com/odoo/odoo/pull/44136
