### ISSUE TITLE
 odoo 12 :- TypeError: Cannot read property 'constructor' of undefined 

### ISSUE THREAD

**Issue by PranaliL** [odoo/odoo#44155]
Impacted versions: odoo 12

Steps to reproduce: issue is on timesheet list view 

Current behavior:
As shown in bellow screenshot issue is with the switch between grid view and list view by removing default added group 
![screenshot-localhost_8012-2020 01 29-12_16_56](https://user-images.githubusercontent.com/44016212/73334147-ea7d6900-4291-11ea-87e0-fefc1d8b9cb0.png)

![rsz_ddd](https://user-images.githubusercontent.com/44016212/73334811-b2772580-4293-11ea-992e-bd341b6be184.png)

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @PranaliL,

Thanks for your report. I'm not able to reproduce it though. Can you test it on the latest runbot and if you can still reproduce it make a short video please?

Regards,
Yenthe

**Comment by PranaliL** [comment]
Hi @Yenthe666 ,
      Thanks for response , I will test it on latest runbot and get back to you . 

Thanks and Regards,
Pranali

**Comment by Yenthe666** [comment]
Hi,

Since I haven't heard back from you I'm going to go ahead and close this issue.
Don't hesitate to come back with steps/extra info and we'll recheck it then.

Regards,
Yenthe
