### ISSUE TITLE
[13.0] pg_dump not found

### ISSUE THREAD

**Issue by schout-it** [odoo/odoo#44156]
Impacted versions: 13.0

Steps to reproduce:
start a new odoo instance with odoo-bin -c config.cfg -s
quit and restart the instance with this config

Current behavior:
when creating a backup, pg_dump is not found

Expected behavior:
backup of database

cause:
pg_path has no default value, and is set to None,
This is read as a string and the _normalize function changes this to ODOO-PATH/None/

posible solutions: #44059
or when loading the config check for string None and change to value None,
same as is done for boolean values

**Comment by pedrobaeza** [comment]
As there's a PR for this, I close the issue. You shouldn't open both. Just include the text of the issue on the PR.
