### ISSUE TITLE
[ASK] Odoo 11 - Cron

### ISSUE THREAD

**Issue by FerdinaKusumah** [odoo/odoo#44184]
How to run cron as specific user ??
let say i have cron A with user A
and same cron with user B

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
