### ISSUE TITLE
[7.0] date widget does not take into account the user timezone

### ISSUE THREAD

**Issue by max3903** [odoo/odoo#4420]
On version 7.0, I activated the developer mode and set my user timezone to 'Canada/Eastern'.

Then I go to Warehouse > Deliver Products to get:
![with_widget](https://cloud.githubusercontent.com/assets/939952/5550775/82ecc14a-8b7c-11e4-8bee-3532fc7bea40.png)

If I edit the tree view to remove the widget="date" on the date field, I get:
![without_widget](https://cloud.githubusercontent.com/assets/939952/5550778/9e8977b8-8b7c-11e4-800b-d1ece02ef2e3.png)

I am expecting to get the same date with or without the widget.

**Comment by beledouxdenis** [comment]
Issue solved with 2a162d9be71ee00f7698dda7075801ef8213c1d4

**Comment by max3903** [comment]
I tried on the latest Runbot, in Warehouse > Receive/Deliver Products > Deliver Products. I set UTC -9 and UTC +12 as my timezone and the date never changed.

I removed the widget=date on the date field and I got "02/03/2015 19:00:00" displayed whatever the timezone I set in my preferences. Always 7pm.

The fix is not working.

**Comment by beledouxdenis** [comment]
Where did you set the timezone ? 

This is the timezone of your browser which counts, not the timezone you set for your user. This is the case everywhere else in your client.

In order to test, you have to change the timezone of your computer itself, and then restart your browser.

Regards,

**Comment by max3903** [comment]
Ok, it works then. What is the use of the user timezone in the preferences then ?

**Comment by beledouxdenis** [comment]
The user time zone is used server-side mainly, for instance when another user do stuff for another one, in another timezone, and things like that.
