### ISSUE TITLE
One2many issue odoo 13.0 with more fields in tree view

### ISSUE THREAD

**Issue by mra-odoo** [odoo/odoo#44204]
Impacted versions: 13.0

Steps to reproduce: If we make on2many field on any object and try to add 20+ fields in one2many tree view then it will break tree view and hide some random fields from one2many and layout will be broken as well.

Current behavior: One2many in list view with 20+ fields will break layout of tree view of one2many

Expected behavior: It should allow all fields to be visible properly with its values.

Video/Screenshot link (optional): https://youtu.be/qQcKHT93r-c 

Thank you,
Mustufa Rangwala

**Comment by Yenthe666** [comment]
Maybe I'm missing something but I'm literally seeing no bug? :/ cc @pedrobaeza

**Comment by mra-odoo** [comment]
Thank you for your reply.

We have around 20+ fields on that one2many but only few are visible and also fields which are visible its view is not look good (like lables got decrease, values got decrease)..

**Comment by mra-odoo** [comment]
I will send more detail video tommorow.

**Comment by pedrobaeza** [comment]
I don't see the problem except the side scroll, which is expected. Do a design that don't require that fields or open them in popup.

**Comment by mra-odoo** [comment]
Hi @pedrobaeza 

Ok we will change design and hide some fields option hide mode. 

Thank you,
Mustufa Rangwala
