### ISSUE TITLE
[WEB/Listview] Delete button in one2many field on readonly mode

### ISSUE THREAD

**Issue by gan-odoo** [odoo/odoo#4422]
Reproduce in 7.0

Step to reproduce:
    1) Create a one2many record and save
    2) Reload this page and then display delete icon on one2many record in read only mode.

See video :  http://youtu.be/A7b6SdsU-UE

**Comment by Yenthe666** [comment]
Hi @gan-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
