### ISSUE TITLE
Error when using One2many relation with calendar.event model

### ISSUE THREAD

**Issue by alexeirivera87** [odoo/odoo#44223]
Impacted versions: 10.0

Steps to reproduce:

Add m2o field to calendar.event class, like this:

```
class CalendarEvent(models.Model):
    _inherit = 'calendar.event'

    reservation_id = fields.Many2one(
        'hotel.reservation', string='Reservation No.', copy=False)
```

then a o2m field:

```
class HotelReservation(models.Model):
    _name = "hotel.reservation"

    meeting_ids = fields.One2many(
        'calendar.event', 'reservation_id', string="Meetings", copy=False)
```

Current behavior:
When trying to add a new value in the one2many field, that points to calendar.event, the following error raises: 

  File "D:\Work\workspace\odoo_sourcecode\odoo-10.0\odoo\addons\calendar\models\calendar.py", line 46, in calendar_id2real_id
    return calendar_id and int(calendar_id) or calendar_id
ValueError: invalid literal for int() with base 10: 'one2many_v_id_106'

This error occurs in method calendar_id2real_id.

Expected behavior:
No error raised when trying to create a new calendar.event from a model who have a one2many relation with this model.

**Comment by pedrobaeza** [comment]
You can't do that (or not at least without a filtering) because calendar.event handles virtual IDs for recurring events. Ask on forums for workarounds.

Closing as known limitation.
