### ISSUE TITLE
Delay in Top Menu in Website Sale.

### ISSUE THREAD

**Issue by andrea92** [odoo/odoo#44237]
**Impacted versions:** Odoo 13 Community

**Steps to reproduce:** 
1.-Install websate_sale module.
2.-Install default template.
3.-Go to Website.

**Current behavior:** 
When the page loads completely, the menu does not load until after 10 seconds or more.

**Expected behavior:**
The menu should automatically load along with the page.

![image](https://user-images.githubusercontent.com/1821838/73385659-e8bca100-42a3-11ea-94e4-4ae7310efd8d.png)

I hope you can help me.

Thank you. Greetings.

**Comment by pedrobaeza** [comment]
This is not happening in my case. There's an animation, but it delays a second at maximum. Please check your browser and try with another one.

**Comment by Yenthe666** [comment]
Closing as there hasn't been any feedback and as we are unable to reproduce the problem.

**Comment by melbaz** [comment]
Same issue is here with me as typically described by @andrea92 .

**Comment by zahra1478** [comment]
Same issue in here with odoo 14

**Comment by sgheller** [comment]
Could it be related to #77843?

**Comment by Carlosmlb22** [comment]
Same Issue, Odoo 13.
