### ISSUE TITLE
when using states into Many2many get the error : Error: QWeb2 - template['ListView.rows']: Runtime Error: Error: QWeb2 - template['ListView.row']: Runtime Error: Error: Unknown field state in domain [["state","not in",["draft"]]]

### ISSUE THREAD

**Issue by Bhaviraj** [odoo/odoo#4430]
its an imergency plz give me solution

**Comment by xmo-odoo** [comment]
As @bba-odoo replied, you probably have an attrs of some sort depending on the record's state so the list view attempts to compute that attr when displaying the record, but the `state` field isn't present in the view and thus has not been fetched, which makes the computation fail.

To fix it, simply add the `state` field to the relevant view, and set it `invisible="1"` so it is not shown to users.
