### ISSUE TITLE
Sales Teams: click planned revenue for opportunities than give a traceback

### ISSUE THREAD

**Issue by ssh-odoo** [odoo/odoo#4431]
Impacted versions:
Master , 8.0

Steps to reproduce:
1. Menu : Sales / Sales Teams /

Click on Planned Revenue For Opportunities than give a traceback ..

Current behavior :

throws trace back... AttributeError: Field `total_revenue` does not exist Error context:
View `crm.opportunity.report.graph`
[view_id: 338, xml_id: crm.view_report_crm_opportunity_graph, model: crm.opportunity.report,       parent_id: n/a]

Expected behavior:
    
Resolve the traceback .

**Comment by kkoci** [comment]
This is also happening to me, is this solved?
