### ISSUE TITLE
[13.0] [wishlist] Support colored Tags in List Views

### ISSUE THREAD

**Issue by ray-odoo** [odoo/odoo#44339]
Impacted versions:

11.0, 12.0, 13.0

Steps to reproduce:

Make some CRM Tags and change their colors by clicking on them:
![image](https://user-images.githubusercontent.com/41073831/73466265-7a74ee80-4336-11ea-8b3d-43ee6e7efe58.png)

Add these to the TreeView of Leads

Current behavior:

![image](https://user-images.githubusercontent.com/41073831/73466313-8cef2800-4336-11ea-9dd0-72e25968866c.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/41073831/73466372-a42e1580-4336-11ea-8d58-e9121cbc0eb4.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Loving the idea Ray! Have you discussed it with anyone inside of Odoo yet or not?

**Comment by ray-odoo** [comment]
I have not.

**Comment by Yenthe666** [comment]
@ged-odoo what does your team think of this addition?

**Comment by ged-odoo** [comment]
hmm, weird, I really thought that it actually worked. right now, I don't see any reason why it wouldn't. Maybe this is a bug

**Comment by msh-odoo** [comment]
@ray-odoo Are you sure you added color_field in options of many2many_tags field? to have color on tags you must pass color_field in options, say for example:
```<field name="tag_ids" widget="many2many_tags" options="{'color_field': 'color'}"/>```

I tested on 13.0, would you please check on 11.0 and 12.0 as well?

cc: @Yenthe666 @ged-odoo

**Comment by ray-odoo** [comment]
I copy / pasted your field definition and this is what I see:

![image](https://user-images.githubusercontent.com/41073831/73551705-c0e05100-43fb-11ea-83ee-c70b0c332a13.png)

I confirmed each Tag has a color field value, and in the Form View - 'Product' is blue and 'Information' is red.

This was tested on today's runbot at http://1061844-13-0-c63269.runbot33.odoo.com/

CRM --> then change the Pipeline to List View.

**Comment by Yenthe666** [comment]
@ray-odoo I've tested it on the latest 13.0 but it works fine. See the screenshot:
![image](https://user-images.githubusercontent.com/6352350/73643193-59ccd180-4673-11ea-8cab-33dc34c89859.png)
See http://1070019-13-0-8c668b.runbot36.odoo.com/web?#action=751&model=crm.lead&view_type=list&cids=&menu_id=517
Only added `options="{'color_field': 'color'}"`

**Comment by ray-odoo** [comment]
It is working now.  Thanks for checking.  I tested 11.0, 12.0, 13.0 and 13.1.  I can only wonder if I didn't refresh properly after making the change.

**Comment by ray-odoo** [comment]
This is now happening on a new v13 Odoo.sh database using the default list view for Leads.

options="{'color_field': 'color'}" is not present in the View

@msh-odoo did you mean "it works without the customization" or "it works when you add the options tag" ?

**Comment by msh-odoo** [comment]
@ray-odoo You have to add option for color_field, you have to tell many2many_tags widget that use this field as color field in options, I just checked 13.0 code and there also it requires color_field in options

**Comment by ray-odoo** [comment]
Ok. So I am reopening this. Perhaps I need to restate what I am suggesting.

Functional: "Support colored tags without needing to modify the view."

Technical: "Add the options tag to the View definition so the User doesn't have to." 

We have the options tag in the Form View already. 

Did we design the List on purpose to show tags without colors?

**Comment by Yenthe666** [comment]
@ray-odoo do you mean support it with Odoo studio then?

**Comment by ray-odoo** [comment]
@Yenthe666 I mean support it without the user needing to modify any views, either via XML or Studio.


1. Install Odoo.
2. Create three tags and assign them colors.
3. It looks like this:
![image](https://user-images.githubusercontent.com/41073831/75632478-53b60c00-5bb1-11ea-903b-7c3d25ac3712.png)

Unless we designed the List on purpose to show tags without colors, and that reason makes me disagree with myself.

I'm looking at why it took me this long to make this clear.  Is it clear now?

**Comment by Yenthe666** [comment]
Aha, now I get what you mean. Yes, you're right that this would be a good small improvement.

**Comment by ray-odoo** [comment]
WISH GRANTED!!! 

This has been delivered at 13.2 so I am closing.

**Comment by Yenthe666** [comment]
🎉 nice! Good job Ray.
