### ISSUE TITLE
[13]  Do not set default value if Record is Archived

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44345]
Impacted versions: 13.0 (or all)

Steps to reproduce:  Archive the Record which is Used as Default Property
Eg, Archive **Normal Delivery Charges**
![Screenshot (86)](https://user-images.githubusercontent.com/16624719/73468554-f7da4680-43aa-11ea-8305-3846fea535b2.png)

Sales Order --> Add Shipping which uses this record as Default 

Current behavior:
![Screenshot (87)](https://user-images.githubusercontent.com/16624719/73468686-2f48f300-43ab-11ea-8e19-0b9800e07105.png)
https://github.com/odoo/odoo/blob/9edad5d9018ae357e955a5e21e9366e56caa8e31/addons/delivery/models/sale_order.py#L62

Expected behavior: It should not set archived record as Default

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@sswapnesh what you're reporting here is happening in multiple places across Odoo. It basically happens with anything depending on defaults
@mart-e I know you've responded on one of these related tickets before but Github searches don't seem to give back the topic where you did. Do you remember? I know the conclusion was for now that it was known before and something that could be improved right?

**Comment by sswapnesh** [comment]
True, But We should have an Option which ignores Inactive records as Default Property.

**Comment by mart-e** [comment]
Hello,

@sswapnesh Sorry but this is how many2one records work and we do not plan to change it generically.
If you have set a reference to a record somewhere, it is fixed, whatever the state of the record.
However, on a case by case, if it makes sense functionally, we can check the values in the code that selects the archived record.
Have you checked where this one is triggered?

@Yenthe666 sorry but it seems you have a better memory than myself ;-)

**Comment by sswapnesh** [comment]
@mart-e  

Can I make a PR which checks if it is active or not Before setting carrier here, If Record is archived we can set False

**Comment by mart-e** [comment]
@sle-odoo would you accept such patch? _TL;DR: check if the carrier is not archived in [action_open_delivery_wizard](https://github.com/odoo/odoo/blob/f03b4cb5576f264b6845242ba112f02422af4f5f/addons/delivery/models/sale_order.py#L55)_

**Comment by sle-odoo** [comment]
@mart-e it seems to me it should be handled at higher level, why making such a patch on this wizard while all other properties pointing to archived records will still work?
imo, it would be saner to prevent archiving a record if a property still points to it

**Comment by mart-e** [comment]
@sle-odoo IMHO the property fields should be considered as any many2one. The method, we use the property in the `else` clause but the same problem can occure in the first clause when we are reading the carrier from the SO.
The other option is to take action in the toggle_active method.

**Comment by sle-odoo** [comment]
> The other option is to take action in the toggle_active method.

i think it would chose this way. archiving a product is prevented if a RR still points to it, i would say archiving a carrier should be prevented if it's still a default on a partner.

but i don't think this patch is worth writing though
