### ISSUE TITLE
Sales Order in Multiple currencies not considering in sales analysis reports

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#4434]
In sale order multiple currencies accepting, but in reports and other analysis sum of sales value not consider the different currency effect.
Ex. I have sales orders like (5000-USD , 5000-EUR and 10000-AED)  
the total will show the total sales order value is 20,0000/-
It should show separately currency wise and one more column to show in local currency.
Otherwise the information is wrong.

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
