### ISSUE TITLE
[13.0][website] Unable to change color of the theme on the website!

### ISSUE THREAD

**Issue by bahram-css** [odoo/odoo#44352]
Impacted versions: 13

Steps to reproduce:
After I uninstall website module and install it again
I tried to change color of theme from "customize/customize theme" but it didn't worked

Current behavior:
The color didn't change
Expected behavior:
color changed

Video/Screenshot link (optional):
https://youtu.be/0hc7rDrEtCk

**Comment by Yenthe666** [comment]
Hmm seems to work fine on the latest runbot 13.0 that I've tested. You did get a traceback when uninstalling which I didn't seem to get..

**Comment by bahram-css** [comment]
Thats not working now.
http://1056331-13-0-9edad5.runbot28.odoo.com/

**Comment by Yenthe666** [comment]
Indeed! It seems to keep working on enterprise but not on community.
@JKE-be for your team

**Comment by bahram-css** [comment]
Uninstalling website module will not delete a record related to these settings(customize/customize theme) in the ir_attachment table and create another record by reinstalling it.
Duplicating this record causes problem

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by makwin** [comment]
Yes. Still happening

**Comment by nachoserra-domatix** [comment]
@bahram-css Is there any way that font selection works as well? Deleting *theme_color.css works for colors but not for the fonts

**Comment by qsm-odoo** [comment]
Hello :wave: 
I cannot reproduce the issue. On my side, the attachments you mentnion are actually deleted on website uninstall. Here is the code responsible for that: https://github.com/odoo/odoo/blob/13.0/addons/website/models/website.py#L196. Could someone provide the steps to reproduce the problem from a fresh 13.0 install / runbot?

**Comment by qsm-odoo** [comment]
If anyone has steps to reproduce this issue, please report them and we'll reopen this issue, thanks :+1:
