### ISSUE TITLE
[8.0]Web UI tweaks for pager border and status arrow

### ISSUE THREAD

**Issue by youring** [odoo/odoo#4435]
Pager border
Before
![1](https://cloud.githubusercontent.com/assets/4132418/5560715/8c91ff4a-8ddd-11e4-90be-68f7e835cdba.png)

Mod base.css and base.sass
.openerp .oe_pager_group {
  height: 24px;  /\* change 24px to auto */  
}
After:
![2](https://cloud.githubusercontent.com/assets/4132418/5560719/ba35eda8-8ddd-11e4-8a8d-85f5b6f51b1d.png)

Status arrow, specifically the last but one
Before
![3](https://cloud.githubusercontent.com/assets/4132418/5560721/0bd4a88e-8dde-11e4-965a-d5c1773495a4.png)

Mod base.css and base.sass
.openerp ul.oe_form_status li > .arrow, .openerp ul.oe_form_status_clickable li > .arrow {
  height: 30px;  /\* change 30px to 29px */
}
After:
![4](https://cloud.githubusercontent.com/assets/4132418/5560724/5021c788-8dde-11e4-85d4-e46318d46696.png)

**Comment by Yenthe666** [comment]
Hi @youring,

Thank you for your report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). In the meanwhile it all looks a lot cleaner and better 😉 

Regards,
Yenthe

**Comment by spadae22** [comment]
![Uploading Screen Shot 2017-10-27 at 11.11.19 AM.png…]()
BUG 3 YEARS AGO!

**Comment by spadae22** [comment]
![screen shot 2017-10-27 at 11 11 19 am](https://user-images.githubusercontent.com/7741100/32111389-5bad2192-bb08-11e7-8bb6-cd908ccece47.png)
