### ISSUE TITLE
[8.0] Pay Later or Group Funds for sale receipts generated unblanaced journal entries.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#4436]
latest odoo 8.0
when choose Pay Later or Group Funds in sales receipts, it should generated unlanced journal entries.
as 

![image](https://cloud.githubusercontent.com/assets/1404460/5560887/0fa2c608-8ded-11e4-9239-77e60a3de678.png)

comments,
 22210105 销项税额 is the tax account,
6001 主营业务收入  is income account
1122 应收账款  is AR account

if choose pay directly, it is ok,
what's mean Pay Later or Group Funds? what's the defierent between them,

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
