### ISSUE TITLE
[V7.0] hr_payroll: Issue with "other input" in payslip computation 

### ISSUE THREAD

**Issue by diassynthesis** [odoo/odoo#4438]
Even if the payslip is computed, the "other input(s)" are not taken into account.
https://www.odoo.com/forum/help-1/question/incentives-dont-calculated-in-the-payslip-why-71547

**Comment by Yenthe666** [comment]
Hi @diassynthesis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by kharbat** [comment]
I was able to reproduce this issue on v11.0 and I also uploaded a video to show the behavior on this issue #24156

**Comment by kharbat** [comment]
@diassynthesis were you able to fix this issue? can you give me any suggestions? I would really appreciate it
