### ISSUE TITLE
[res.partner] Contacts related to a company are not  automaticly archeved or deleted when the parent_id is archeved or deleted

### ISSUE THREAD

**Issue by SalouaSahnoun** [odoo/odoo#44385]
**Impacted versions:**
 All
tested in V11 & V13

**Steps to reproduce:**

when you archive a company ''res.partner'', the contacts linked to this company are not automatically archived, which I find strange because normally if a company is archived or deleted automatically its contacts must be deleted or archived. 

**Current behavior:**
when you archive a company ''res.partner'', the contacts linked to this company are not automatically archived,

**Expected behavior:**
if a company is archived or deleted automatically its contacts must be deleted or archived

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This has been issued other times and this is done on purpose for individual handling of each active visibility, so you can stick to this behavior or program a module that changes it.

Closing as won't fix.
