### ISSUE TITLE
iframe : display problem

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#444]
Hello,

I want to add an iframe on a web page.
To try to add an iframe, I use the HTML Editor : Customize > HTML Editor.

If I add the next HTML code (from http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe)
&lt;iframe src="http://www.w3schools.com"&gt;
&lt;p&gt;Your browser does not support iframes.&lt;/p&gt;
&lt;/iframe&gt;

Result:
The iframe is displayed empty.

Romain

**Comment by JKE-be** [comment]
It should be fixed meanwhile.
Else don't hesitate to reopen an issue.

Thanks @copmn for your help...
