### ISSUE TITLE
[8.0] can not close cash register.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#4441]
with odoo 8.0 cash register, can not close the opened cash register..
to reproduct this,
1. create a new cash register.
![image](https://cloud.githubusercontent.com/assets/1404460/5563692/ecce6866-8ec4-11e4-9d91-78367406dc4c.png)

2. take mony out. 
![image](https://cloud.githubusercontent.com/assets/1404460/5563726/c0be0076-8ec7-11e4-97cb-1f086449c088.png)

the close button lost.. what's the wrong i have made.
the cash journal have configured as 
![image](https://cloud.githubusercontent.com/assets/1404460/5563707/ae448bfa-8ec6-11e4-9029-bf8a2c25e965.png)

have reviewed the code. found that should not show the close button  if `all_lines_reconciled` is FASLE
![image](https://cloud.githubusercontent.com/assets/1404460/5563715/03dfe532-8ec7-11e4-9961-dcebc2c59b44.png)

but the class `account_cash_statement` does not call the `account.bank.statement.line` instead call  `account.cashbox.line`

how to use cash register? it is very defferent with odoo v7.

thanks for any help.

**Comment by NL66278** [comment]
The problem also exists in OpenERP/Odoo 7.0 (but not in 6.1).

The method balance_check in account/account_bank_statement.py used to take both cash and bank statements into account in 6.1, this was lost in 7.0.

Look (within the git odoo repository) at the output of $ git show 341c6b08 to show the commit that causes the error.

I will try to create a fix.

**Comment by beledouxdenis** [comment]
You just need to first reconcile your cash register, using the reconcile button; before being able to close it.
