### ISSUE TITLE
testing error while push custom module to odoo.sh

### ISSUE THREAD

**Issue by depodoo** [odoo/odoo#44410]
Impacted versions:
Odoo 13.0
Steps to reproduce:
push custom module to development branch
Current behavior:
odoo.addons.account_followup.tests.test_followup: Starting TestAccountFollowup.test_05_followup_multicompany ... Fails 
this happens before installing custom module. custom is installed as expected
odoo.modules.module: Module account_followup: 0 failures, 3 errors
Expected behavior:
No errors while installing custom module with 
"depends": ['account', 'account_asset'],
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, as this is something of Odoo.sh, you should contact to their support, not here.

**Comment by depodoo** [comment]
@pedrobaeza yes I know. I opened issue here to investigate probably somebody faced the same problem. Thanks
