### ISSUE TITLE
[8.0] financial report can not select report  when  set report type to `account_report`

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#4442]
when set type to  `account_report`, should not select the `account_report_id` from the report configure form.

           <?xml version="1.0"?>
           <form string="Account Report">
                            <group col="4">
                                <field name="name"/>
                                <field name="parent_id"/>
                                <field name="sequence"/>
                                <field name="type"/>
                                <field name="sign"/>
                                <field name="style_overwrite"/>
                            </group>
                            <notebook attrs="{'invisible': [('type','not in',['accounts','account_type'])]}">
                                <page string="Report">
                                    <group>
                                        <field name="display_detail" attrs="{'invisible': [('type','not in',['accounts','account_type'])]}"/>
                                        <field name="account_report_id" attrs="{'invisible': [('type', '!=', 'account_report')]}"/>
                                    </group>
                                    <field name="account_ids" attrs="{'invisible': [('type', '!=', 'accounts')]}"/>
                                    <field name="account_type_ids" attrs="{'invisible': [('type', '!=', 'account_type')]}"/>
                                </page>
                            </notebook>
                        </form>
                    

found that there have filterd the page.

we should change  `      <notebook attrs="{'invisible': [('type','not in',['accounts','account_type'])]}"> `    to     `      <notebook attrs="{'invisible': [('type','not in',['accounts','account_type', 'account_report'])]}">`

**Comment by mart-e** [comment]
Hello,

I believe it was already fixed at 220999037e843dbf81d9e8ff4abc4e9cd830c36f
Thanks for the report
