### ISSUE TITLE
[13] hr: Could not quick create and assign user to Employee

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44442]
Impacted versions: 13.0

Steps to reproduce: Create New User from Employee
 ![image](https://user-images.githubusercontent.com/16624719/73614256-6de8e280-4623-11ea-8fa9-b522a8520107.png)
![Screenshot (93)](https://user-images.githubusercontent.com/16624719/73614258-6fb2a600-4623-11ea-831f-e847211748f9.png)

Current behavior:
Related User is still empty
 ![image](https://user-images.githubusercontent.com/16624719/73614256-6de8e280-4623-11ea-8fa9-b522a8520107.png)

Expected behavior: New User should be set

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@tivisse what do you think about this case?

**Comment by tivisse** [comment]
I think that we shouldn't even allow to create a user from there ;)

I would add the nocreate option on the field.

**Comment by tivisse** [comment]
I'm creating an internal task to discuss it with the related PO.

Thanks for the feedback.

**Comment by Yenthe666** [comment]
Thanks @tivisse! Let's close this one off then since you have an internal task.

**Comment by tivisse** [comment]
FYI, it has been fixed at https://github.com/odoo/odoo/pull/45411

Have a nice day, and thanks for the feedback !
