### ISSUE TITLE
`dbfilter` does not work in cron threads

### ISSUE THREAD

**Issue by dennybiasiolli** [odoo/odoo#44458]
Impacted versions: 11.0

Steps to reproduce:

- create multiple odoo databases (i.e. "odoo-test1", "odoo-test2", "other-db"

- create an example cron thread for each database (i.e. logging something to console every minute)

- filter out databases with `dbfilter = ^odoo-.*$`

- relaunch odoo and wait for cron to execute, it will execute crons for every database and not only for "odoo-test1" and "odoo-test2"

Current behavior: odoo executes crons for every database and not only for those filtered by `dbfilter` parameter

Expected behavior: odoo should execute crons only for databases filtered by `dbfilter` parameter

**Comment by Yenthe666** [comment]
@dennybiasiolli have a look at https://github.com/odoo/odoo/pull/19537 - this has been proposed before. The conclusion was

> I think there is an easy (and even clean) solution to the problem: use different Postgres users, and isolate your database instances by restricting their access to an appropriate user.

**Comment by dennybiasiolli** [comment]
@Yenthe666 so in a big environment, serving multiple databases with a single instance and making cron works with only filtered dbs is possible only using `db_name` with comma-separated values, right?
We are currently configuring nginx header to select a specific db for "published" area, we were searching an easy solution to have the cron kuberbetes pods working with filters, but as you said it's not possible

**Comment by Yenthe666** [comment]
Yep, or split them up with different users

**Comment by dennybiasiolli** [comment]
@Yenthe666 what do you think about a new config parameter similar to `dbfilter` but for cron workers? If you think it's a good idea, I can help providing a PR with all changes needed 😉

**Comment by Yenthe666** [comment]
@dennybiasiolli personally I'd be for but that's not my call. I know that most of the guys are not a big fan of introduction extra config parameters because there are already quite a few. @mart-e what's your call?

**Comment by mart-e** [comment]
Sorry but, as Yenthe said, we prefer not to introduce new config parameters when workaround are possible (in this case, use `db_name`).
