### ISSUE TITLE
[12.0/13.0] Purchase Requisition bug

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#44489]
Hello,

We've gotten some tickets from clients that started having trouble today on Call For Tenders and Blanket Orders.

Apparently there was an update in which the code tries to access a self.env.company in a purchase.requisition, which obviously raises an attribute error.

The commit: 1818ba785cbeab0d16810114b8d323dda60c0f1b
The code: https://github.com/odoo/odoo/blob/12.0/addons/purchase_requisition/models/purchase_requisition.py#L86

![reinaldes](https://user-images.githubusercontent.com/42942314/73655212-5cd0bd80-4685-11ea-963a-e473f2da67fb.png)

Thank you.

**Comment by pedrobaeza** [comment]
Yeah, I have experimented the same.

@jhk-odoo @nim-odoo can you please check? Or should I do the PR changing to `self.env.user.company_id`?

**Comment by pedrobaeza** [comment]
Note that in v13 it should work, so I only tag for 12.0.

**Comment by nim-odoo** [comment]
My bad, fix in progress in https://github.com/odoo/odoo/pull/44511

**Comment by sswapnesh** [comment]
Has been fixed in https://github.com/odoo/odoo/commit/49c338ed506a0fe28d77b9e1c68368d2f2bd22fa
