### ISSUE TITLE
Imposible to make full inventory

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#4451]
Tested on runbot
http://36940-8-0-8347d3.runbot6.odoo.com/web?db=36940-8-0-8347d3-all#menu_id=151&action=156
1. Create a new product (Newforinventory)
2. Go to warehouse / inventory adjustment
3. Create new one
4. Select inventory for all products --> Confirm

You will see that Newforinventory product is not listed. 
Inventory adjustments is getting only products that had any stock.move on inventory selected location. 
It should take any stockable/consumable product from product form, never mind if it has got stock moves or not.

**Comment by Yenthe666** [comment]
Hi @anajuaristi ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
