### ISSUE TITLE
Small Screen Area for Desktop/Mobile browsing breaks add product functionality

### ISSUE THREAD

**Issue by Phaunswater** [odoo/odoo#44520]
Impacted versions:  v13.0 Community Edition

Steps to reproduce:
1.  Access Odoo via a desktop or mobile browser with a smaller screen area (for example, an iPhone 5s that renders at 640x1136)
2.  Create a Quotation
3.  Scroll to Order Lines

Current behavior:

- On a smaller screen, both in desktop and mobile environments, the user is not offered "Add Product |  Add Section  | Add Note" functionality, but is instead given a single "Add" button
![IMG_4760](https://user-images.githubusercontent.com/9247338/73673700-1e370500-467d-11ea-8350-5d4c51f0a80a.PNG)

- Clicking "Add" pops up a dialog to CREATE a new product... product list is not searchable, does not filter based on what the user types in, and no matter what the user types in the only option is to create an entirely new product!
![IMG_4761](https://user-images.githubusercontent.com/9247338/73673904-740bad00-467d-11ea-8e5c-00b950ccf90e.PNG)
![IMG_4762](https://user-images.githubusercontent.com/9247338/73673986-9d2c3d80-467d-11ea-940b-9ceec227dc4d.PNG)

- I am fine with forcing the user to add the product in a dialog on a smaller screen, but the current UI breaks functionality completely for adding order lines of existing products on a small screen!

Expected behavior:
- With a large enough screen, when adding Order Lines the user is offered "Add Product |  Add Section  | Add Note"
- User selects "Add Product", begins typing and a filtered list of options appears for the user to select as shown below
![IMG_4759](https://user-images.githubusercontent.com/9247338/73673492-b4b6f680-467c-11ea-9966-feeb8ee0ce41.PNG)

- Can this be fixed with a theme/reskin or an adjustment to my implementation's CSS or UI Code?

**Comment by pedrobaeza** [comment]
Try https://odoo-community.org/shop/product/web-responsive-2681, as the community UI interface is not responsive, so closing as won't fix.

**Comment by Phaunswater** [comment]
Thank you Pedro!
