### ISSUE TITLE
Stripe - Apple Pay

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#44578]
Impacted versions: 10, ?

Current behavior: To enable Apple Pay in Stripe you need to host a verification file in "https://example.com/.well-known/apple-developer-merchantid-domain-association"

Expected behavior: Maybe add option to upload this file in Stripe Payment module?

<img width="686" alt="Screenshot 2020-02-04 at 13 30 06" src="https://user-images.githubusercontent.com/13152668/73741488-003bd400-4753-11ea-8c39-3dd51e1e2cd1.png">

**Comment by Yenthe666** [comment]
Hi,

Sorry but V10 is no longer an official support version plus adding the verification file (manually) works.

Regards,
Yenthe

**Comment by kimasplund** [comment]
Yes i understand 10 is not supported. But the same "issue" is in 13.0 also. 

(and where do i upload the domain specific file if i do it manually?) 

//kim :)

**Comment by Yenthe666** [comment]
Usually it is done with a domain rule that contains the verification key as a value.
@JKE-be maybe something as a feedback for V14?

**Comment by kimasplund** [comment]
Indeed. The need to make DNS rules for a static file seems a bit counter intuitive and somewhat difficult for "normal" users when a simple upload from payment module would solve it in 5 seconds.

**Comment by JKE-be** [comment]
you can just create a new page "/.well/apple-developer-xxx-domain-association" and paste the content of the file.

Or you can upload it in attachment and add "/.well/apple-developer-xxx-domain-association" as url

**Comment by kimasplund** [comment]
> you can just create a new page "/.well/apple-developer-xxx-domain-association" and paste the content of the file.
> 
> Or you can upload it in attachment and add "/.well/apple-developer-xxx-domain-association" as url

Im not really sure how i would go about doing that :D Dont really seem to be possible out of the box in community ed.

**Comment by JKE-be** [comment]
Attachment method: https://youtu.be/7iH0_-5gpXA

Page method: https://youtu.be/6cTZZ4FymxM


(page method need to be updated from backend since ".well" will be slugged to "well" in fast create mode


KR
