### ISSUE TITLE
[13]sale: Error when upgrade module

### ISSUE THREAD

**Issue by EgyCrash** [odoo/odoo#44571]
Impacted versions:
13.0-20200204 (Community Edition) 
Steps to reproduce:
When upgrade module
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

[sale.txt](https://github.com/odoo/odoo/files/4152761/sale.txt)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
