### ISSUE TITLE
Generate PO from Bid

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#4460]
Setp 1 : Go to Purchase -> Calls for Bids

Create Bid with a product and set  Bid Selection Type   : Select multiple RFQ

Setp 2 : Click on Confirm Call Button

Setp 3 : Click on "Request for quotation"  and select supplier1 for bid
Do the same process for supplier 2

Setp 4 : Click on "Close Call for Bid" button

Setp 5 :  Click On "Choose Product Line" Button

Here you can select product lines.

How wever you select product lines form bidline view and click on "Generate PO" button.

It will give you pop up 
"Warning!
You have no line selected for buying. "

even though we have selected product lines.

Thanks,
Nimesh Contractor

**Comment by Miftahussalam** [comment]
Hi bba-odoo..
I have a same problem with Nimesh Contractor even though I have Confirmed Order and selected product lines.

**Comment by Yenthe666** [comment]
Hi @nimeshcontractor,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
