### ISSUE TITLE
Odoo 11 - Missing <!DOCTYPE html> in the website page if the user is not logged in

### ISSUE THREAD

**Issue by newodoo** [odoo/odoo#44612]
Impacted versions: 11

Steps to reproduce: view source code of the page with logged user and with not logged user

Current behavior: when the user is not logged the <!DOCTYPE html> declaration is not there

Expected behavior:<!DOCTYPE html> should be always in the html generated

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I have just tried in runbot and that's not true:

![Selección_004](https://user-images.githubusercontent.com/7165771/73777753-511aef00-478a-11ea-985c-def5015da155.png)

Check your deployment. Meanwhile, closing this as no valid.

**Comment by newodoo** [comment]
Before opening the issue I checked also in runbot, but my odoo version is Odoo 11.0-20180321 (Community Edition).

Howewer, can you please suggest how to debug the issue, 
in the web.layout view the code is there:
<t name="Web layout" t-name="web.layout">&lt;!DOCTYPE html&gt;

I've checked also the translation and it is ok, same string in both language.

**Comment by Yenthe666** [comment]
Works just fine on the latest 11.0 without being logged in:
![image](https://user-images.githubusercontent.com/6352350/73827270-87468600-47ff-11ea-94e7-617145f93dc3.png)

**Comment by newodoo** [comment]
Do you know if were fixed some bug since Odoo 11.0-20180321? Or can you help me to force the declaration? I've created a custom addon:
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>

<template id="custom_layout" name="Custom Main layout" inherit_id="web.layout">
    <xpath expr="//html" position="before">
		&lt;!DOCTYPE html&gt;
    </xpath>
</template>
</odoo>
```

but, if the user is logged, the declaration is printed twice, if the user is not logged the declaration is missing.

**Comment by Yenthe666** [comment]
Don't try to do those kind of hacks, its very ugly. Just update your Odoo instance to the latest code first.

**Comment by newodoo** [comment]
I have updated the instance to the last, but the behavior is always the same, and this is causing a side issue in shop page, the product table on IOS small device is not correclty diplayed, it shown just the first column.
This issue is very critical for prod environment, can you please suggest a workaround to insert the DOCTYPE html? Meanwhile I will keep investigating on the root cause (mybe a third party application).

Thanks in advance.

**Comment by pedrobaeza** [comment]
Your reverse proxy should be misconfigured. Check documentation on https://www.odoo.com/documentation/11.0/setup/install.html. See also if you have proxy_mode=True in your configuration.

**Comment by newodoo** [comment]
Proxy Mode is True as specified in documentation you linked:

> Configuration sample
> Redirect http requests to https
> Proxy requests to odoo
> in /etc/odoo.conf set:
> 
> proxy_mode = True

This is my Apache configuration:
```
<VirtualHost *:443>
	ServerName domain.it
	ServerAlias www.domain.it
	
	SSLEngine on
	SSLProxyEngine on
	SSLCertificateFile "C:\wamp\bin\apache\apache2.4.9\conf\key\certificate.crt"
	SSLCertificateKeyFile "C:\wamp\bin\apache\apache2.4.9\conf\key\private.key"
	SSLCertificateChainFile "C:\wamp\bin\apache\apache2.4.9\conf\key\chain.crt"
	
	RequestHeader set X-Forwarded-Proto "https"
	
	ProxyPreserveHost On
	ProxyRequests Off
	<Proxy *>
		#AllowOverride All
		Order deny,allow
		Allow from all
	</Proxy>

	ProxyPass / http://127.0.0.1:8069/
	ProxyPassReverse / http://127.0.0.1:8069/
    
	<IfModule mod_rewrite.c>
       RewriteEngine On
 
       #Permanent redirect (301 HTTP) if no canonical domain name
       RewriteCond %{HTTP_HOST} !^domain.it
       RewriteRule ^/(.*)$ https://domain.it/$1 [R=301,NE,L]
	   RewriteRule ^/orologi-usati.*$ https://domain.it/shop/ [R=301,L]
    </IfModule>
	
	<Location />
#		AllowOverride All
		Order allow,deny
		Allow from all
		Require all granted
	</Location>
```

Since all is working as expected, except for Doctype it is not simple for me to find misconfiguration

**Comment by pedrobaeza** [comment]
Yeah, but this is out of scope of this issue tracker. Try to ask for help in forums.

**Comment by newodoo** [comment]
I was just giving evidence of the issue and possible solution, it seems linked to the issue tracker, even because we are not sure on the root cause, it could be common to other user.

**Comment by pedrobaeza** [comment]
But this is not an Odoo issue, but a deployment one, and it's the first time someone comes with it, so it's not something normal to happen. I don't know what's your problem, and if you finally find the problem and it's due to a bad documentation, then you can come back here to say it and then it will be a documentation issue to be solved, but meanwhile, there's nothing more we can do.

**Comment by flotho** [comment]
@newodoo , any OCA modules installed ?

**Comment by newodoo** [comment]
In my case the issue wal linked to:
Website Lazy Load Images module, I was forced to remove it, with high decrease of performance...
