### ISSUE TITLE
[13.0] [MRP] Consumed quantity not update properly with Lot from work-order.

### ISSUE THREAD

**Issue by ADVALAKI** [odoo/odoo#44625]
Impacted versions: 13.0

Steps to reproduce:

**Please refer video for more detail to reproduce issue.**

1. Create BoM with product which have Lot Enable and add operation on BoM line.
2. Create Production Order with 5 Quantity (i have tested it with given qty)
3. Click on Plan button to generate workorder.
4. Click on process button to process work order.
5. process manufacturing Qty partially(i have process 1 and then 4 qty).
6. Check consumed material line in manufacturing order. it will not updated based on BoM.

Current behavior:
It's not updating consumed quantity based on BoM from workorder when Lot is enable for raw material.

Expected behavior:
It should update consumed quantity based on BoM.

Video/Screenshot link (optional):
https://gofile.io/?c=G1ZOmU

Runbot Link :
http://1091741-12-0-cbf4a4.runbot17.odoo.com/web?#id=19&action=685&model=mrp.production&view_type=form&menu_id=460

--

**Comment by Whenrow** [comment]
Hello, 
Thank you for the well documented issue. I saw your video was made on a V12 database. This explain the strange behavior you encounter. Indeed at 1:03, you change the quantity to produce from 5 to 1. The quantity of raw product to consume is not updated properly (it stay to 10). 
It means to produce one unit of table, you are consuming 10 units of raw product.
From V13 we improved this production view by updating the quantity to consume in case of changing the quantity to produce.
Hopes it will help you

**Comment by ADVALAKI** [comment]
> Hello,
> Thank you for the well documented issue. I saw your video was made on a V12 database. This explain the strange behavior you encounter. Indeed at 1:03, you change the quantity to produce from 5 to 1. The quantity of raw product to consume is not updated properly (it stay to 10).
> It means to produce one unit of table, you are consuming 10 units of raw product.
> From V13 we improved this production view by updating the quantity to consume in case of changing the quantity to produce.
> Hopes it will help you

Updated version number from 12 to 13.0.

**Comment by ADVALAKI** [comment]
> 10

You mean to say that we need to update raw material qty when i change quantity producing?

**Comment by Whenrow** [comment]
@ADVALAKI .That's right, in V12, the quantities need to be synchronised by the user. It allows you to choose the quantity to consume even if it's different from the Bill of Material.
