### ISSUE TITLE
Many2many relation issue

### ISSUE THREAD

**Issue by mokamo** [odoo/odoo#44627]
Impacted versions:13

Steps to reproduce: 
# create the next code
```python
class BasePropData(models.Model):
    _name = 'base.data'
    xx_ids = fields.Many2many(comodel_name="x.model", relation="base_data_x_model_rel",
                                                 column1="base_entity_id",
                                                 column2="entity_calc_id")
    yy_ids = fields.Many2many(comodel_name="x.model", 
                                                 relation="base_data_x_model_ext_rel",
                                                 column1="base_entity_id",
                                                 column2="entity_calc_id")
class PropertyObj(models.Model):
    _name = 'base.data.extension'
    _inherit = 'base.data'
    _description = 'Property'
```

Current behavior:
I think odoo tries to auto-generate the relation name on the new model so after creating it for xx_ids field with " base_data_extenstion_x_model_rel " try to auto-generate for yy_ids field with the same criteria so gives this error
TypeError: Many2many fields base.data.extension.yy_ids and base.data.yy_ids use the same table and columns - - -

So I need to add the relation parameter on the inherit model 'base.data.extension' manually to make it unique for one of the 2 fields

Expected behavior:
should be handled on this situation to be more flexible in creating  more than 1 many2many fields so it doesn't crash on the inheritance

**Comment by pedrobaeza** [comment]
Sorry, but this is a limitation on current framework and it's not going to be handled automatically AFAIK. You have to manually add `_relation`, and optionally `_column1` and `_column2` for differentiate both.

Closing as won't fix.

**Comment by javl** [comment]
@pedrobaeza The modified code below seems to work (using the same definition but using a unique relation name), but it seems quite convoluted to overwrite every many2many field this way when you inherit a model. Do you know of a better way to do so? (you mentioned `_relation`?) I can't seem to find any example in the basic addons that uses this structure.


```
from odoo import models, fields

class BasePropData(models.Model):
    _name = 'base.data'
    xx_ids = fields.Many2many(comodel_name="x.model", relation="base_data_x_model_rel",
                                                 column1="base_entity_id",
                                                 column2="entity_calc_id")
    yy_ids = fields.Many2many(comodel_name="x.model",
                                                 relation="base_data_x_model_ext_rel",
                                                 column1="base_entity_id",
                                                 column2="entity_calc_id")

class PropertyObj(models.Model):
    _name = 'base.data.extension'
    _inherit = 'base.data'
    _description = 'Property'

    xx_ids = fields.Many2many(comodel_name="x.model", relation="base_data_extended_x_model_rel",
                              column1="base_entity_id",
                              column2="entity_calc_id")
    yy_ids = fields.Many2many(comodel_name="x.model",
                              relation="base_data_extended_x_model_ext_rel",
                              column1="base_entity_id",
                              column2="entity_calc_id")

```

**Comment by pedrobaeza** [comment]
Sorry, I meant the attributes without _. It was a typo in my writing.

**Comment by mokamo** [comment]
@pedrobaeza 
so If I'm inheriting res.partner table I have to check all m2m fields (with auto-generated relation ) and override the field with new relation.
this doesn't make any sense
