### ISSUE TITLE
[11.0] Quantity on Hand not being correctly calculated - Location parent left/right not computed upon creation

### ISSUE THREAD

**Issue by Azratosh** [odoo/odoo#44667]
**Impacted versions:**
11.0; possibly others?
Steps to reproduce:
1. Create a new database and install Inventory app
(?. Enable **Storage Locations** and **Multi-Warehouses** in Settings --> Not sure if that makes any difference)
2. Create new product
3. Update Qty on Hand
4. Notice that value on product form remains 0
5. Click on `On Hand`
6. Notice that there is indeed the entered value in WH/Stock

**Current behavior:**
Parents left and right of `stock_location` are not being set upon creating default locations; impossible to create a new warehouse.

**Expected behavior:**
... that they are set correctly and warehouses can be created.

**Solution:**
I noticed that upon attempting to create a new warehouse, I get an error like in this Odoo forum issue [here](https://www.odoo.com/de_DE/forum/hilfe-1/question/typeerror-unsupported-operand-type-s-for-nonetype-and-int-91803). I tried fixing it with the methods described in the thread, and it is indeed corrected when left and right parents of table `stock_location` are (re-)computed through the shell. Seems like those aren't set in the database when installing the Inventory app.

**Comment by gdgellatly** [comment]
@Azratosh I have had this bug a few times, its been reported a lot in the past. A quick fix is to drop the parent_left and parent right columns of stock_location and then update stock module.

**Comment by pedrobaeza** [comment]
This has been fixed in >= v12 due to the change in the way hierarchies work, and there's no fix expected for this version, so you can do the workaround said by @gdgellatly, but I'm going to close it as "won't fix on v11 but fixed on >=v12".
