### ISSUE TITLE
[13] Reset View Architecture always shows diff

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44676]
Impacted versions: 13.0

Steps to reproduce: Go to Any View --> Action -->Reset View Architecture
![image](https://user-images.githubusercontent.com/16624719/73870386-02e11b00-4872-11ea-9f87-e337aeadc799.png)
Do the Hard Reset
![image](https://user-images.githubusercontent.com/16624719/73870414-0d031980-4872-11ea-9fa8-9a3a9d968b3a.png)

Current behavior: Even after Hard Reset It always shows the diff

Expected behavior: 

![image](https://user-images.githubusercontent.com/16624719/73870831-bcd88700-4872-11ea-9bac-69cad6dc4d67.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Does it really matter though? Doesn't seem like its worth any code to me honestly. @pedrobaeza your thought?

**Comment by sswapnesh** [comment]
But its a very small change to make it Perfect (Or at least as Improvement as @rdeodoo already working on similar thing on https://github.com/odoo/odoo/pull/44646 )

**Comment by Yenthe666** [comment]
Well feel free to make a PR I'd say 👍 😄

**Comment by sswapnesh** [comment]
Not sure if this is related to  `difflib` library

**Comment by pedrobaeza** [comment]
Indeed I don't see this critical, as it doesn't suppose any error nor confusion: you are not seeing any diff, so that means there's no change to do. Even if you click on reset view, no modification will be performed, so what's the problem?

**Comment by sswapnesh** [comment]
>  so what's the problem?

Technically Nothing but still There should be no Diff and the Ideal Behaviour should be 

![](https://user-images.githubusercontent.com/16624719/73870831-bcd88700-4872-11ea-9bac-69cad6dc4d67.png)

**Comment by pedrobaeza** [comment]
As said, I don't see that a problem and prefer to focus in real customer problems, but as @Yenthe666 has said, PRs are welcome.

**Comment by sswapnesh** [comment]
I would like to have Opinion of @rdeodoo  as He is currently working on a similar thing

**Comment by rdeodoo** [comment]
Agree with @pedrobaeza and @Yenthe666 , PR welcome tho

**Comment by rdeodoo** [comment]
Fixed in https://github.com/odoo/odoo/pull/44646
