### ISSUE TITLE
[13] Missing validation on model on updating  ir.ui.view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44682]
Impacted versions: 13.0 (Might be All)

(Maybe too Technical)

Steps to reproduce:  Create new View with wrong model name or typo
It raises Warning

![image](https://user-images.githubusercontent.com/16624719/73878909-750d2c00-4881-11ea-9148-8c1c510e552f.png)

Now, Change Model on the existing view (On a custom module I have faced this due to some missing dependency but I found we are missing this validation)
Current behavior: 
It allows you to enter Invalid model name
![image](https://user-images.githubusercontent.com/16624719/73879114-e3ea8500-4881-11ea-86a9-e66c2786808c.png)

Expected behavior: Validation should be there on Updating view as well

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Honestly, if you're a developer you just have to know what you're doing and keeping an eye out. The view will fail with a traceback anyways so its up to you as a dev to solve it.

**Comment by sswapnesh** [comment]
True but Still That's something we can Always improve.
If something is blocked during creation of the Record than same should be blocked on edit.

**Comment by Yenthe666** [comment]
I'd say a PR is welcome but it's very unlikely that the Odoo team itself will do it though.
