### ISSUE TITLE
[13.0] website: pictogram removed when trying to change Button Color

### ISSUE THREAD

**Issue by vickybizople** [odoo/odoo#44689]
Impacted versions:

**13.0**

**Steps to reproduce:**

1. Edit Website Page
2. Drag'n Drop the "Call to Action" Building Block.
3. Change Contact Us Button Color

**Current behavior:**
when user change contact us button color **pictogram** automatically removed from the Button
Please check the video for better understanding 

**Expected behavior:**

Pictogram need to stay as it is.

Video/Screenshot link (optional):
https://youtu.be/3BV1lWy4p-k

**Comment by Yenthe666** [comment]
@qsm-odoo could you please check this one? :)

**Comment by qsm-odoo** [comment]
I know that this issue existed but I reported it at some point and it seems fixed. Strange if you managed to reproduce it yesterday though... anyways, I cannot reproduce it, can you? :+1:

**Comment by Yenthe666** [comment]
@qsm-odoo yes still reproducable in the latest 13.0 runbot by default. See https://drive.google.com/file/d/1eoDR8hys8XI8wMtPvu1PMrcVS5rQmJCw/view

**Comment by qsm-odoo** [comment]
Ok, it happens 1 time over 10 tries on my side. I'll let the editor team try on its side and judge :+1: 
cc @dmo-odoo

**Comment by vickybizople** [comment]
@qsm-odoo also you can check in the Inspect Elements <span> and <i> tag both removed when we click on save.
see https://youtu.be/zD7LMBaQwcw

**Comment by dmo-odoo** [comment]
@qsm-odoo I was able to reproduce it perfectly and found the cause of the issue. The pictograms are not recognized correctly until the `computeFonts` method of `wysiwyg.fonts` is called. It is called in the `init` method of the `IconWidget`, which is instantiated with by the `MediaDialog`. So basically, if you pretend to insert a media by clicking on the media button then close the modal then edit the "Contact Us" button, it will work. You just have to click on the media button once.

My suggestion for a fix: require `wysiwyg.fonts` in the loading of the website in edit mode and call its `computeFonts` method before letting the user edit the page. However, I fear there may be a catch in that there might be a reason why this `computeFonts` mechanic is so isolated so there might be a reason why we might not want to call `computeFonts` in all cases. Though considering pictograms aren't somewhat *understood* by the editor until `computeFonts` is called, I would still suggest to call it in all cases.

**Comment by qsm-odoo** [comment]
@dmo-odoo I think the bug is only there in 13.0 post editor revert so it was working before and in fact exactly thanks to the solution you suggest: `computeFonts` **is called** at the start of the editor so it should work... but it is not the same `computeFonts` as it was duplicated somehow with the editor revert, that may be the cause :+1:

**Comment by dmo-odoo** [comment]
@qsm-odoo Oh oh, interesting. I'll investigate, thanks !

**Comment by vickybizople** [comment]
Fixed Thanks 
@dmo-odoo @Yenthe666 @qsm-odoo
