### ISSUE TITLE
[13.0] account_invoice: Error while creating a free invoice

### ISSUE THREAD

**Issue by umiphos** [odoo/odoo#44687]
### Impacted versions:

- 13.0

### Steps to reproduce:

1. Create an invoice
2. Set the price of the products to 0
3. Save it or post it

### Current behavior:

We get a warning about unbalanced entries in the journal, seems ok but it's not, sometimes we need to create this kind of invoices for free movements, like prices or donations

![image](https://user-images.githubusercontent.com/4094256/73908404-31112b80-486f-11ea-9892-3d9305ecf6f2.png)

**Comment by Yenthe666** [comment]
@qdp-odoo for you

**Comment by sswapnesh** [comment]
I can confirm this Behaviour

Adding `vals = {'price_unit':0.0}`
at https://github.com/odoo/odoo/blob/5c544adbcf0f0af67b29a39c191e190a59fed90c/addons/account/models/account_move.py#L2820

works well but still not sure


PS: Maybe we can also fix inconssitency on calculating Unit price during changing Product qty

**Comment by qdp-odoo** [comment]
I suppose this is legit?

@smetl @avw-odoo any objection to this patch?

**Comment by qdp-odoo** [comment]
https://github.com/odoo/odoo/pull/45531
