### ISSUE TITLE
[8.0] stock: stock.move required number of production.lot but this field is not present.

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#4468]
Stock move view is a good way to transfer product by many users at the same time.
But if you have a product with "tracking all lots" this view show a error but not show a field to fix it.

![stock moves - odoo - serial number](https://cloud.githubusercontent.com/assets/6644187/5580586/67a8de88-9012-11e4-953c-8ea62543638b.png)

**Comment by jco-odoo** [comment]
Click on the reference to go to the picking and process it there.

**Comment by moylop260** [comment]
Hello @jco-odoo,
Thank for your answer

As I mentioned
Stock move view is a good way to transfer products by `many users` at the same time of one picking.
If you use one picking with `many users`  you will have concurrency issues.

Then we need use stock.move, but if we have production.lot this functionality is disabled into v8 (This work fine in v7)

**Comment by nhomar** [comment]
@jco-odoo 

Are you kidding us dude?

One view is not showing a required field and you solution is "go to other view"?

It is like the solution proposed for viruses by windows "reinstall the system".

Technically and conceptually it is a wrong answer, a view which need a field to be used in an action "must" show the field.

regards,

and BTW: we use a lot the move's for logistical reasons as @moylop260 is mentioning.

**Comment by jco-odoo** [comment]
No, I am not kidding!  Lots should be handled by the pack operations and
not the stock moves.  It is only when stock moves are treated individually
that you can use the restrict_lot_id field in the stock move.  But I
encourage you to use only the picking view.

**Comment by moylop260** [comment]
@jco-odoo 
You did not answer my question of "concurrency"

**Comment by nhomar** [comment]
2015-01-05 3:38 GMT-06:00 Josse Colpaert <notifications@github.com>:

> No, I am not kidding! Lots should be handled by the pack operations and
> not the stock moves. It is only when stock moves are treated individually
> that you can use the restrict_lot_id field in the stock move. But I
> encourage you to use only the picking view.
>

@jco-odo

You can not have a vie which have a required field which can not be setted,
it is a bug. Please can you explain me better why do I have a "tranfer
button" then in stock move?

It is wrong answer in my opinion dude.

We use this view in almost all our customers.

-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by jco-odoo** [comment]
In v8, when a move is in a picking and there are pack operations (either made by the bar code interface or the transfer wizard), the lots are handled by the pack operations.  That is why they are not in the view of the stock moves.  

Because there are sometimes moves without picking (or this works also when you would transfer the move only and there are no pack operations e.g. inventory, production), it is possible to put a restrict_lot_id in the move.  That way you could also work in the view of the stock moves (answers question of moylop206), but you should not mix both.  (but why not work with backorders or split pickings to assign them to different workers)

I wonder why your customers always work through this view as you can search pickings on the product also and it is logical to handle picking by picking.  That is what they are made for.

**Comment by moylop260** [comment]
@jco-odoo 
I will explain.
Imagine that a customer has many picking with 1000 products in a picking with qty > 10 in each move line.
They have 20 employee that capture this picking because is too much work for one employee.
In v7.0 we work with stock.moves view.
What is your proposal to capture the entrance to this picking (with serial number) in v8?

**Comment by rvalyi** [comment]
@moylop260  let me see if I understood correctly what you said: you mean:
how do we handle each stock move lot in the case we have a picking with several moves of the same product (to split them in smaller quantity or process them at different times eventually)?

"Funnily", I was banging my head in the wall about this right now. I just re-developed a split lot wizard per move like for v7 (hopefully soon in OCA, may be you can help) but when you have 2 moves with the same product in the same picking, it falls short. Are we talking about the same issue? cc @nhomar

**Comment by moylop260** [comment]
@rvalyi thanks for you comment.
Our main problem is the concurrency if we use same picking.
With split moves or unified moves.
How I can capture the entrance of a picking with 1000 products * 10 qty (unique lot) of a way efficient by many employees?

**Comment by nhomar** [comment]
2015-01-13 12:08 GMT-06:00 moylop260 <notifications@github.com>:

> @rvalyi <https://github.com/rvalyi> thanks for you comment.
> Our main problem is the concurrency if we use same picking.
> With split moves or unified moves.
> How I can capture the entrance of a picking with 1000 products * 10 qty
> (unique lot) of a way efficient by many employees?


And this specific bug" is that throught this view, you have a not shown
'required field' which make the behavior of the line unconsitent with the
behavior of the picking.

I honestly sometimes think that the concept of "Oriented Object
programming" when comes in odoo to business elements is completly incorrect.

The "Transfer" feature must be programmed in the stock.move and called from
several places (line, opicking, wizard cool, or whatwever).

But simply They don't understand such issue.....

No matter where I fill a move it "must" be conssitent.


-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>
