### ISSUE TITLE
Update base Module Raises Error

### ISSUE THREAD

**Issue by ieyring** [odoo/odoo#44697]
Impacted versions: 3.0-20191103

Steps to reproduce:
Simply try to update BaseModul

Current behavior:
raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
But there is only one referenceUnit in the category!
Expected behavior:
Simply update the Modul

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The error is pretty clear: you have changed your unit of measures and change the one of reference, and now when updating there are 2 with that type.

**Comment by ieyring** [comment]
You have read my Description?
**there is only one referenceUnit in the category**

**Comment by pedrobaeza** [comment]
As said, it can be not what Odoo expects and try to put again as reference. Have you switch the reference one?

**Comment by ieyring** [comment]
No I didn't change the reference. I have created new categories.
The criticized Category is "Volumen".

![grafik](https://user-images.githubusercontent.com/9789918/73933368-994a2680-48dc-11ea-9ac7-63fbd5851c72.png)

**Comment by pedrobaeza** [comment]
Maybe you have an archived one or as said, the expected one have been changed. I see in runbot than the expected one for volume is liters, not m3.

**Comment by ieyring** [comment]
Ok, because the errorhandling has an Error itself, where in the Code could/should i look for this problem?

**Comment by pedrobaeza** [comment]
I don't get you.

**Comment by ieyring** [comment]
There is none archived Volume, There is none changed Category, There are only newly created entries for categories. Kategorie Volume has only one reference unit: liters!

If i try to update the BaseModul i get an Error:  Error code: 200 
>Error message: Odoo Server Error 
>Error data message:
>UoM Kategorie Volume sollte nur eine Referenzmaßeinheit haben.
>None

during handling of the above exception another exception occured.
Where could i look to take a grip of the problem with the Volume Category?

**Comment by pedrobaeza** [comment]
I think you remove a category and recreate it by hand, but then, the XML-ID is not linked and Odoo is trying to create it again. Check which UoM doesn't have XML-ID.

**Comment by ieyring** [comment]
Ok, thanks.

**Comment by ieyring** [comment]
OK. i've tried.
Whats wrong with this xml?

File "/usr/lib/python3/dist-packages/odoo/addons/uom/models/uom_uom.py", line 93, in _check_category_reference_uniqueness
    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.env['uom.category'].browse(uom_data['category_id']).name,))
odoo.tools.convert.ParseError: "UoM Kategorie Volume sollte nur eine Referenzmaßeinheit haben.
None" while parsing /usr/lib/python3/dist-packages/odoo/addons/uom/data/uom_data.xml:2, near
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data noupdate="1">
         <record id="product_uom_categ_unit" model="uom.category">
            <field name="name">Unit</field>
            <field name="measure_type">unit</field>
        </record>
        <record id="product_uom_categ_kgm" model="uom.category">
            <field name="name">Weight</field>
            <field name="measure_type">weight</field>
        </record>
        <record id="uom_categ_wtime" model="uom.category">
            <field name="name">Working Time</field>
            <field name="measure_type">working_time</field>
        </record>
        <record id="uom_categ_length" model="uom.category">
            <field name="name">Length / Distance</field>
            <field name="measure_type">length</field>
        </record>
        <record id="product_uom_categ_vol" model="uom.category">
            <field name="name">Volume</field>
            <field name="measure_type">volume</field>
        </record>
       
        <record id="product_uom_unit" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_unit"/>
            <field name="name">Units</field>
            <field name="factor" eval="1.0"/>
            <field name="rounding" eval="0.001"/>
        </record>
       <record id="product_uom_dozen" model="uom.uom">
            <field name="category_id" ref="uom.product_uom_categ_unit"/>
            <field name="name">Dozens</field>
            <field name="factor_inv" eval="12"/>
            <field name="uom_type">bigger</field>
        </record>

        <record id="product_uom_kgm" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="name">kg</field>
            <field name="factor" eval="1"/>
            <field name="rounding" eval="0.001"/>
        </record>
        <record id="product_uom_gram" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="name">g</field>
            <field name="factor" eval="1000"/>
            <field name="uom_type">smaller</field>
        </record>

        <record id="product_uom_day" model="uom.uom">
            <field name="name">Days</field>
            <field eval="uom_categ_wtime" name="category_id"/>
            <field name="factor" eval="1.0"/>
        </record>
        <record id="product_uom_hour" model="uom.uom">
            <field name="name">Hours</field>
            <field eval="uom_categ_wtime" name="category_id"/>
            <field name="factor" eval="8.0"/>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_ton" model="uom.uom">
            <field name="category_id" ref="product_uom_categ_kgm"/>
            
            <field name="name">t</field>
            <field name="factor_inv" eval="1000"/>
            <field name="uom_type">bigger</field>
        </record>
        <record id="product_uom_meter" model="uom.uom">
            <field name="category_id" ref="uom_categ_length"/>
            <field name="name">m</field>
            <field name="factor" eval="1.0"/>
        </record>
        <record id="product_uom_km" model="uom.uom">
            <field name="category_id" ref="uom_categ_length"/>
            <field name="name">km</field>
            <field name="factor_inv" eval="1000"/>
            <field name="uom_type">bigger</field>
        </record>
        <record id="product_uom_cm" model="uom.uom">
            <field name="category_id" ref="uom_categ_length"/>
            <field name="name">cm</field>
            <field name="factor" eval="100"/>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_litre" model="uom.uom">
            <field name="name">Liters</field>
            <field name="category_id" ref="product_uom_categ_vol"/>
            <field name="factor" eval="1"/>
            <field name="rounding" eval="0.001"/>
        </record>

        
        <record id="product_uom_lb" model="uom.uom">
            <field name="name">lbs</field>
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="factor">2.20462</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_oz" model="uom.uom">
            <field name="name">ozs</field>
            <field name="category_id" ref="product_uom_categ_kgm"/>
            <field name="factor">35.274</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_inch" model="uom.uom">
            <field name="name">inches</field>
            <field name="category_id" ref="uom_categ_length"/>
            <field name="factor">39.3701</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_foot" model="uom.uom">
            <field name="name">foot(ft)</field>
            <field name="category_id" ref="uom_categ_length"/>
            <field name="factor">3.28084</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_mile" model="uom.uom">
            <field name="name">miles</field>
            <field name="category_id" ref="uom_categ_length"/>
            <field name="factor_inv" eval="1609.34"/>
            <field name="uom_type">bigger</field>
        </record>
        <record id="product_uom_floz" model="uom.uom">
            <field name="name">fl oz</field>
            <field name="category_id" ref="product_uom_categ_vol"/>
            <field name="factor">33.814</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_qt" model="uom.uom">
            <field name="name">qt</field>
            <field name="category_id" ref="product_uom_categ_vol"/>
            <field name="factor">1.05669</field>
            <field name="uom_type">smaller</field>
        </record>
        <record id="product_uom_gal" model="uom.uom">
            <field name="name">gals</field>
            <field name="category_id" ref="product_uom_categ_vol"/>
            <field name="factor_inv" eval="3.78541"/>
            <field name="uom_type">bigger</field>
        </record>
    </data>
</odoo>
