### ISSUE TITLE
deinstallation of Website Category Modul inlfluences Odoo Settings

### ISSUE THREAD

**Issue by ieyring** [odoo/odoo#44701]
After deinstallation of Website Categorie Modul the Settings of Odoo are no more reachable. 

It results in an Error:

Server application error 
Error code: 200
Error message: Odoo Server Error
Error data message: Das Feld `category_style` existiert nicht
Impacted versions: 13.0

Steps to reproduce: deinstall Website Categorie Modul

Current behavior: Odoo Settings no more reachable

Expected behavior: simply deinstall the modul

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Which module are you talking about? Is an Odoo standard one?

**Comment by ieyring** [comment]
It's the website category Modul from Softhealer.
The Support from Softhealer said: "Because uninstall things odoo manage automatically, it's not in our control."

**Comment by pedrobaeza** [comment]
That's not true, and Softhealer seems to be a bad developer then if they don't know this. A module can touch anything in an irreversible way although the module is uninstalled, and Odoo can't do anything about that. It's the responsibility of the module developer to provide an uninstall hook for "restoring" that.

Any way, not sure that it's totally something of them and not a bad deployment. Have you restarted the Odoo service after the uninstallation for being sure?

Closing this as no Odoo issue, but third party one.
