### ISSUE TITLE
[13.0] Rename account.move Internal Note or make it actually internal

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#44728]
Impacted versions: 13.0

Steps to reproduce:
1. Create a customer invoice
2. Write some internal secrets in the "Add an internal note..." text field
3. Print the invoice

Current behavior:
You will see your internal note on the invoice.

Expected behavior:
You either won't see the internal note on the invoice (since it's internal)
OR
the field wouldn't be called "Internal Note" but "Additional Information" instead, and the placeholder would be "Add additional information..." instead of "Add an internal note..."

This placeholder already lead me to believe that Odoo no longer has a "comment" field and it could lead to even worse situations if someone actually writes something that's meant for internal purposes only.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1525066/73954948-3754e580-490b-11ea-99e3-1f2db8f46a72.png)

![Selection_026](https://user-images.githubusercontent.com/1525066/73954875-1e4c3480-490b-11ea-8896-419310174512.png)

**Comment by pedrobaeza** [comment]
Yeah, I agree the placeholder is misleading. @qdp-odoo do you think this can be changed in stable?

**Comment by qdp-odoo** [comment]
indeed, it is misleading and should be change to remove the 'internal'

**Comment by sswapnesh** [comment]
So this can be closed as well

**Comment by mlaitinen** [comment]
What? So it'll stay as an "internal note" forever?

**Comment by Yenthe666** [comment]
@mlaitinen it'll be resolved in the upcoming V14.
