### ISSUE TITLE
[13] Website: Wrong date format on My account --> opportunity

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44811]
Impacted versions: 13.0

Steps to reproduce: 
Go to My opportunity

Current behavior: Different Date formats
![image](https://user-images.githubusercontent.com/16624719/73971575-22954380-4945-11ea-9598-03d3db615e4a.png)

Expected behavior: Same date format

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
It seems to behave multiple Issues on this Page

1: Notice the Rounding 
![image](https://user-images.githubusercontent.com/16624719/73971752-7acc4580-4945-11ea-80db-ab408a9a4e87.png)

![image](https://user-images.githubusercontent.com/16624719/73971783-8f104280-4945-11ea-90a6-7680ad0304f1.png)



------------

2: Two Date pickers and traceback
![Peek 2020-02-07 01-04](https://user-images.githubusercontent.com/16624719/73971925-da2a5580-4945-11ea-9526-dd8d0137013e.gif)


@Yenthe666 @pedrobaeza Should create New Issues for this?

**Comment by Yenthe666** [comment]
I guess its fine in one as its all in the same view and app?

**Comment by rdeodoo** [comment]
Indeed, `datetimepicker-input` from tempus dominus should not be input of type `date`.
https://github.com/odoo/odoo/commit/b2b639b693dd7215e3ee501ac89c35f3a6b88bb5 introduced that.
The rounding and the double datetimepicker should be fixed.
About the different format, to check but nothing critical IMO.

**Comment by JKE-be** [comment]
Since the datetimepicker and rounding is fixed by rde, I close It.
