### ISSUE TITLE
[ Odoo Failed ]  [Bug] Product variant and product

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#4481]
Hello,

I had created a new product, updated product stock 10.

Then I added product variants.

Then try to create sale order, with variant product. order lines alert for stock not available.

Seems in stock moves, 10 qty for my main product. 

Alert is correct, because variant is not in stock, but unwated first created stock move their, unable to remove it any how. also keep that 10 qty in moves, not so logical.

Let me know what should be good their ? does it bug, or your development issue ?

Kindly let me know how to remove or avoid it, or how clients can avoid this kind of mistakes.

Thanks,

**Comment by tejastank** [comment]
Since 24 days, no update ?

**Comment by Yenthe666** [comment]
I can no longer reproduce this issue. This has probably been fixed in the meanwhile.
