### ISSUE TITLE
Odoo v11 Stock Movement - Configuring operation type doesn't work

### ISSUE THREAD

**Issue by GitFuturenet** [odoo/odoo#44837]
Impacted versions: v11

Steps to reproduce:

Create a new operation type (for delivery) to give default destination location different from Partner/Customers. Create sale order --> Delivery --> Select the new operation type which you created.

Current behavior:
The destination location we set in operation type is not changing. Always it is Partners/Customer

Expected behavior:
The destination location should be fetched from the default destination location defined in Operation Type

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Did you configure the destination location on the customer though?

**Comment by GitFuturenet** [comment]
By customer, you mean customer master ? I only configured in Inventory --> Configuration --> Operation Type. 
![Screenshot_2020-02-07 Global FMS Delivery Orders - Odoo(1)](https://user-images.githubusercontent.com/52448373/74026226-c0cbec80-49cb-11ea-80c6-6a95e14b267f.png)

**Comment by GitFuturenet** [comment]
Kindly let me know where do I need to configure as you suggested ? 

> Did you configure the destination location on the customer though?

**Comment by Yenthe666** [comment]
Sorry seems to work different in V11 then V13 so not sure there.

**Comment by GitFuturenet** [comment]
@Yenthe666 Would you be able to tag someone who could clarify this ? We are struck with this issue here.

**Comment by Yenthe666** [comment]
Labelled it for the right people. Whenever somebody at Odoo has time for this they'll look at it but it might take a while. Alternativaly you could ask this on the official help forums at help.odoo.com.

**Comment by Yenthe666** [comment]
Sorry but in the meanwhile V11 is no longer supported so we have to close this off. Don't hesitate to update this issue or create a new one if you can reproduce this in newer versions though.
