### ISSUE TITLE
POS rounding issue

### ISSUE THREAD

**Issue by sheltonfreddy** [odoo/odoo#4484]
**POS rounding issue**

Impacted versions:
- 7.0 

Steps to reproduce:
1. create a new pos order with a product sale price 2.30 and discount 5%
2. validate the pos order

In front end, it shows a total of 2.19 and in back end it shows 2.18 and the pos order remains in new state.

**Comment by sheltonfreddy** [comment]
Odoo 8 have fixed this, but not odoo 7.

**Comment by Yenthe666** [comment]
Hi @sheltonfreddy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by jzahid** [comment]
Hi @Yenthe666 
I confirm that this bug is still in v10.   We have a customer using POS ,daily transaction volume si ~ 300 , every day they report price mismatch between list price and calculated price in pos frontend , difference is always 0.01$. 
Some times session can't be closed because of differences in payement. 
Regards

**Comment by Yenthe666** [comment]
Hi @jzahid,

Thanks a lot for the feedback.
Please create a new bug report for yours as there are three versions between this and there is probably quite a big difference in the functionality/way to trigger it.
Can you please create a new bug with steps on how to reproduce?

Regards,
Yenthe

**Comment by uktc87504** [comment]
Hi @Yenthe666, @jzahid
I confirm that this bug is still in v11.
New bug with steps to reproduce created as [POS rounding issue #36732](https://github.com/odoo/odoo/issues/36732)
