### ISSUE TITLE
Calendar Meeting Invitation Issue.

### ISSUE THREAD

**Issue by jsh-odoo** [odoo/odoo#4487]
**If Administrator is creator of Calendar-Meeting and Administrator is also subscribed to 'Invitation' subtype, email notification is not reached to him when attendee accepts or declines the Meeting invitation.**

Impacted versions:
- 8.0 and above

Prerequisite:
- Set Out going email server
  -Set real email addresses for Administrator and Meeting Attendees.

Steps to reproduce:
1. Login by Administrator
2. Create Calendar-Meeting and add attendees.
3. Subscribe Administrator for 'Invitation' subtype from following dropdown.
4. Accept / Decline Meeting Invitation from email of attendee.

Current behavior:
- Invitation email notification works fine for every user except Administrator.

Expected behavior:
- There can be situation where Administrator is the creator of the meeting. At that time Administrator is required to notify when the attendees accept/decline invitation if Administrator is subscribed with Invitation subtype.

**Comment by Yenthe666** [comment]
Hi @jsh-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
