### ISSUE TITLE
[13] Removing Default Groupby Filter doesn't update Kanban view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44906]
Impacted versions: 13
http://1158815-13-0-43a580.runbot32.odoo.com/web#model=hr.employee&view_type=kanban&cids=&menu_id=204

Steps to reproduce:
![image](https://user-images.githubusercontent.com/16624719/74051716-7f086980-49fe-11ea-939d-7e523271f7fb.png)

Current behavior:
![image](https://user-images.githubusercontent.com/16624719/74051763-9a737480-49fe-11ea-854b-8e7f9c3ea028.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/16624719/74051777-a2cbaf80-49fe-11ea-878b-3e8e5e84abd6.png)

Video/Screenshot link (optional):

**Comment by Feyensv** [comment]
Ping @mcm-odoo ;)

**Comment by jvm-odoo** [comment]
According to this test: https://github.com/odoo/odoo/blob/8c1bb22ec0222dca652e0649454b986c06cb1368/addons/web/static/tests/views/kanban_tests.js#L1603

It seems that this is a wanted behavior.
