### ISSUE TITLE
Allow to use employee accounts in salary rules

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#4491]
If we define an account for each employee in her home address, there is no way to use these accounts in the accounting tab of the salary rules. We are forced to use a unique global account for the rule.

**Comment by Yenthe666** [comment]
Hi @ccomb,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
