### ISSUE TITLE
[13] website: Wrong Untaxed Total sold on Website Analytics Dashbaord

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#44926]
Impacted versions: 13.0
http://1167424-13-0-60d818.runbot13.odoo.com/web#menu_id=370

Steps to reproduce: 
![Peek 2020-02-09 14-42](https://user-images.githubusercontent.com/16624719/74099497-78870880-4b4a-11ea-974e-aea54260fc97.gif)

Current behavior: $ 0.00 on Dashboard and 155.84 when we Open that

Expected behavior: Correct Amount at both place

Video/Screenshot link (optional):

**Comment by bso-odoo** [comment]
Not reproducible in 13.0 on 2020-10-26.

"At a glance" value is the sum of the values shown in the plot, and those do match the values in the "Online Sales Analytics" pivot table (switch to grouping by day to isolate the same data as the plot).
They both are obtained from `price_subtotal` of `sale.report` having a `website_id` and having `state` either `sale` or `done`.

**Comment by Yenthe666** [comment]
Let's consider it fixed in the meanwhile :)

**Comment by rdeodoo** [comment]
Some dashboard errors got fixed with https://github.com/odoo/odoo/pull/61333, the errors shown in report were probably coming from data from another website in order to be reproduced.
