### ISSUE TITLE
[13.0] Error when Packages Transfer between Warehouses Using Route (push to)

### ISSUE THREAD

**Issue by ibrahim08** [odoo/odoo#44928]
**Impacted versions:**
odoo13 enterprise edition
**Steps to reproduce:**
1. activate Multi-Company, Delivery Packages, multi warehouses, and multi-steps routes in inventory
2. User Company: Your Company
3. create 2 Warehouses: WH1, WH2 in Your Company
4. create new Route: apply it in WH1, create Rules:
   action:push to
   Operation Type: WH2 Receipts
   Source Location: /Virtual Location/Inter Company Transit
   Destination Location: WH2/Stock
   Automatic Move: Manual Operation
   Company: Your Company
5. in WH1 Receipt and Internal Transfer Operations Type: activate Move Entire Package, Pre-fill Detailed Operations 
6. Create Purchase Order: select Storable Product, confirm Purchase Order
7. go to PO Receipt , put product in pack and validate picking
8. create Internal Transfer in WH1:
     Source Location: WH1/Stock
     Destination Location: Virtual Location/Inter Company Transit
     Select package created in step 7 (Move Entire package is activated in Operation Type)
     confirm and validate picking

**Current behavior:**
error: record does not exist or has been deleted, (Record stock.move.line(81,),User:2) error in odoo package
**Expected behavior:**

- new picking triggered in WH2 Receipt operation

Video/Screenshot link (optional):

*Note:
  Steps works fine in odoo12 enterprise

**Comment by ibrahim08** [comment]
![Route](https://user-images.githubusercontent.com/22815708/74129454-a0c94280-4bf0-11ea-8c80-b396abfbea29.png)

![Route](https://user-images.githubusercontent.com/22815708/74129342-6495e200-4bf0-11ea-809f-3f58e56485fd.png)

**Comment by ibrahim08** [comment]
Error when Validating Package Delivery to transit Location:
![Error](https://user-images.githubusercontent.com/22815708/74130167-7c6e6580-4bf2-11ea-8ddc-a5e37b8c946c.png)

Operation Type:
![OPType](https://user-images.githubusercontent.com/22815708/74130174-82fcdd00-4bf2-11ea-8efc-93578bcedea9.png)

Route:
![Custom_Route](https://user-images.githubusercontent.com/22815708/74130179-86906400-4bf2-11ea-83b4-195bc0981ef3.png)

Rule:
![Rule](https://user-images.githubusercontent.com/22815708/74130180-88f2be00-4bf2-11ea-9603-7acbbe75556e.png)

**Comment by ibrahim08** [comment]
Error:
![Error](https://user-images.githubusercontent.com/22815708/74130597-762cb900-4bf3-11ea-893c-41ea794c276d.png)

Operation Type:
![OPType](https://user-images.githubusercontent.com/22815708/74130621-86dd2f00-4bf3-11ea-96da-c55dfefa4bf2.png)

Route:
![Custom_Route](https://user-images.githubusercontent.com/22815708/74130632-8cd31000-4bf3-11ea-8795-f4225d4b2cce.png)

Rule:
![Rule](https://user-images.githubusercontent.com/22815708/74130641-9197c400-4bf3-11ea-9419-ee6aa7ed647c.png)

**Comment by sle-odoo** [comment]
Hi,
Not sure about what's triggering the issue but if you're making an inter-warehouse move in the same company, you should use the "Inter-warehouse transit" loction. Futhermore, you could use the "Resupply From" field on the warehouse form.

Regards

**Comment by ibrahim08** [comment]
> Hi,
> Not sure about what's triggering the issue but if you're making an inter-warehouse move in the same company, you should use the "Inter-warehouse transit" loction. Futhermore, you could use the "Resupply From" field on the warehouse form.
> 
> Regards

Hi,
It's somethings related to package transfer using Route that trigger another operation Type, its work fine with products transfer but something went wrong when triggering Route using Package Transfer, can you check with a simple route and package transfer, I tested it in the Runbot but the same Error. 

Regards

**Comment by ibrahim08** [comment]
Any Update on this?
Maybe it's a Bug in Version 13.0, because the same Steps works fine in version 12.0 Enterprise

**Comment by ibrahim08** [comment]
resolved
