### ISSUE TITLE
Traceback on Clicking Adminstrator/Preferences

### ISSUE THREAD

**Issue by rba-odoo** [odoo/odoo#4492]
Effected Version:
8.0 and Master

Steps to Reproduce:
- Go to Settings/Language and uncheck Active checkbox in English Language
- Click to Administrator/Preferences and throws traceback

![6918950](https://cloud.githubusercontent.com/assets/7599745/5592129/b91b287c-91dc-11e4-8342-425f85d76ccb.png)

**Comment by Yenthe666** [comment]
I've reported the same problem here: https://github.com/odoo/odoo/issues/4453

**Comment by Yenthe666** [comment]
@rba-odoo this issue has been fixed and is no longer present in the newest Odoo version!
