### ISSUE TITLE
Odoo v8 POS image upload error when create customer.

### ISSUE THREAD

**Issue by pquochoang2007** [odoo/odoo#4494]
remove line 784 and 805 in /addons/point_of_sale/static/src/js/screens.js function resize_image_to_dataurl
img.onload = function(){ // line 784
} // line 805

**Comment by ppa-odoo** [comment]
Hello @pquochoang2007 working fine, i can't reproduce any type of error on my side can you provide me error detail.

**Comment by pquochoang2007** [comment]
Thanks for replied me, i use odoo 8.0rc1, you can reproduce with 3 step.
step 1: open POS
step 2: click on create customer icon
step 3: click on upload image icon ->error "event is not defined" will be appeared.
