### ISSUE TITLE
Cost price for product in multi company environment showing 0 from sub company

### ISSUE THREAD

**Issue by manigandakrishnappa** [odoo/odoo#4495]
The cost price for a product in sub company is showing as zero, but the cost price has been assigned in main company.
A -> Main company
B- > Sub company
To reporduce the isssue:
1. Create a product named 'TEST' and make it as global(not for company specific)
2. assign the cost price for the product.

3. login with sub company user let us assume B
4.open the product 'TEST' and check the products cost price

**Comment by jco-odoo** [comment]
That is the way it is supposed to work.  The cost price of a product can be different depending on your company.  They can be valued differently in comp.

**Comment by Danisan** [comment]
How do I configure it to share the cost?
