### ISSUE TITLE
[11][12][13] Long memo text (1 word) in payment info is not wrapped correctly at the invoice view

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#44967]
Impacted versions:
[11][12][13] 

Steps to reproduce:
Create an customer invoice. Register a payment on this invoice and put a very long word in the Memo. Once the invoice is reconciled click on the info icon near the total amount. You will see that the text in the Memo field is not wrapped correctly.

![image](https://user-images.githubusercontent.com/30628967/74150315-ec3c1a80-4c09-11ea-8fdd-483957f1d1a4.png)

Current behavior:
See above

Expected behavior:
Nicely wrapped text in the popup window.

Video/Screenshot link (optional):

**Comment by qdp-odoo** [comment]
fixed by https://github.com/odoo/odoo/commit/2cae50a70505b5a93f7fabb6623a135bda163781
