### ISSUE TITLE
[8.0] stock: performance in sale order confirm

### ISSUE THREAD

**Issue by diagramsoftware** [odoo/odoo#4496]
The sale order confirm operation is taking too long in a relatively big database. We've submitted a pull request (#4416) but it seems unable to run successfully through the runbot tests. Can someone check it, please? (more info in the description).

Thanks in advance.

**Comment by mart-e** [comment]
Please do not update issue to ask help on your pull request. Issues are for bug reports. Let's keep the discussion on the pull request only.
