### ISSUE TITLE
[13.0] Replying on internal message results in email being sent to customer

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45044]
Impacted versions: 13.0

Steps to reproduce:
1. Login to the latest runbot 13.0 with the administrator user 
2. Go to Settings > Users and change the notification type from "Handle by Emails" to "Handle in Odoo" for the user "Marc Demo". Give the user "Administrator" rights on the sales app for easier testing.
2. Create  a new quotation for `Deco Addict`, add some line on the quote and either e-mail the customer or add him as a follower on the quote.
3. Log an internal note to `Marc Demo` (with an @ to Marc so he gets a message).
4. Login with the user `Marc Demo` and open the messages from the top. You'll see a message from `Mitchel Admin` with the message:
![image](https://user-images.githubusercontent.com/6352350/74220425-e0a32f00-4caf-11ea-9d5a-690ca1f9d590.png)
5. Reply on this message with something like "Yes this is true":
![image](https://user-images.githubusercontent.com/6352350/74220449-f1ec3b80-4caf-11ea-82fc-825eaacba156.png)
6. Logout and login with `Mitchel Admin` again and now go back to this order. Now look at the history of the chatter:
![image](https://user-images.githubusercontent.com/6352350/74220543-2f50c900-4cb0-11ea-80cd-df2049ca677c.png)

Current behavior:
The reply that was done by `Marc Demo` didn't keep track of the message type. The reply has become a normal reply which is emailed to all followers.

Expected behavior:
As the ping was an internal message from somebody internal to somebody internal the reply from the chatter on this message should also become an internal note. Now the customer is emailed with internal communication which can potential hold important internal information not meant for the customer.

**Comment by Yenthe666** [comment]
OPW `2194944`

**Comment by thomaspot** [comment]
Same problem here for one of our clients..
For client this results in privacy problems as they use the chatter a lot; 
Created also a ticket for Odoo as they use Enterprise.. (2197875)

I would suggest to also use @usernamexxx feature to sent message? (same behavior as in chatter)

**Comment by Yenthe666** [comment]
The response on the ping should follow the privacy settings of the message from the ping honestly. If it's an internal ping and you reply it should stay an internal message. If it's a normal message with a ping the customer just gets a copy.

**Comment by tde-banana-odoo** [comment]
And the inverse would be true: I reply to something in the livechat window and it is not sent to followers because it was a note.

Either we have buttons to choose between discussion and note, either I would not change anything. The "last message sent" heuristic is tricky for me. It makes sense for emails because you reply to a specific message; in the livechat you post on the global discussion thread.

**Comment by Yenthe666** [comment]
Mhmm, I get your reasoning @tde-banana-odoo. Is there a reliable way to figure out to which message the user responds or is it literally just adding a +1 message to the chain without a backlink?

**Comment by tde-banana-odoo** [comment]
There is no real thread (except mail channels were you can have discussion threads separated within a single group). First implementation of Discuss was threaded but now all messages are linked to the same first message, considering it as a flat thread. Rationale behind that model is to avoid supporting complex discussions mechanisms where people answer to a specific message, then answer that specific answer, leading to a tree of messages. That was complex to support (model is not really difficult, more for UX and display mode).

When you reply by email we know which message you received using the headers (in reply to / references). In livechat or discuss it is not as easy.

**Comment by Yenthe666** [comment]
Hmm yes I see your current problem :) I guess this now automatically goes to "maybe for master" then hmm? It could be a user setting in master for example or a configurable option with a default on a message. /wildideas

**Comment by piotrgraczykbg** [comment]
@tde-banana-odoo @Yenthe666 I have the same problem. How can I change chatter to replay with internal note when its internal note instead of sending an email?
