### ISSUE TITLE
[13.0] How I can inherit from other module JS

### ISSUE THREAD

**Issue by m-abdalrahman** [odoo/odoo#45089]
Impacted versions:
13.0

Steps to reproduce:
var wsp = require('website_sale.payment');
console.log(wsp);

Current behavior:
undefined

Expected behavior:
object of website_sale.payment

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
