### ISSUE TITLE
[13] stock: Wrong/Missing documentation on three steps Receipt/Delivery

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45122]
Impacted versions:  13.0

Steps to reproduce: Have a look at the documentation on three steps Receipt

Process a Receipt in three steps (Input + Quality + Stock)
https://www.odoo.com/documentation/user/13.0/inventory/management/incoming/three_steps.html

Current behavior: 
Here, All the Screenshots are related to delivering Products in 3 steps while Document is for **Process a Receipt in three steps (Input + Quality + Stock)**

Similarly, https://www.odoo.com/documentation/user/13.0/inventory/management/delivery/three_steps.html should be for delivery in three steps
Here, All the Screenshots seem correct while the document title is wrong.

Expected behavior: Correct Title + Screenshot

Video/Screenshot link (optional):

Courtesy of @punamshah26

**Comment by sswapnesh** [comment]
Probably for @Feyensv

**Comment by Feyensv** [comment]
For the user documentation (functional: /documentation/user on odoo website), I would recommend creating issues in https://github.com/odoo/documentation-user instead ;).

The functional documentation content isn't managed by Odoo developers, but by Odoo marketing team ;).

**Comment by pedrobaeza** [comment]
Closing this as it's documentation related. Please open it as said on odoo/documentation-user.
