### ISSUE TITLE
[13] Tracback on Re-Arranging Activity Type

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45126]
Impacted versions: 13.0

Steps to reproduce:
![Peek 2020-02-11 23-08](https://user-images.githubusercontent.com/16624719/74262733-71672280-4d23-11ea-818c-aa8ca8dbfaac.gif)

Current behavior: Error

```
Traceback:
TypeError: Cannot read property 'res_id' of undefined
    at http://1197935-13-0-94739a.runbot13.odoo.com/web/content/1572-55cfdb9/web.assets_backend.js:1378:294
    at Function._.map._.collect (http://1197935-13-0-94739a.runbot13.odoo.com/web/content/1571-63ab530/web.assets_common.js:109:270)
    at action (http://1197935-13-0-94739a.runbot13.odoo.com/web/content/1572-55cfdb9/web.assets_backend.js:1378:209)
    at http://1197935-13-0-94739a.runbot13.odoo.com/web/content/1571-63ab530/web.assets_common.js:3870:607

```
Expected behavior: No trackback and able Re-arrenge

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
One of my customers has been bitten by a very similar one. It's a framework thing.
1. Go to contacts, create a new one, click on "Delivery methods" and then "Search more"
2. Reorder the records
3. Traceback

OPW `2256818`

**Comment by nle-odoo** [comment]
thanks for the report, this should be solved with this change that is being merged today:

https://github.com/odoo/odoo/pull/51827
