### ISSUE TITLE
Create Product causes TypeError: el is undefined

### ISSUE THREAD

**Issue by mirnovak** [odoo/odoo#4514]
In Odoo 8 creating a new product by
Purchases/Products/Products -> Create
causes: Odoo Client Error TypeError: el is undefined
It is not possible to save the product because of error: Integrity Error [object with reference: Tax - account.tax] 
It is not possible to select Customer nor Supplier Taxes due to error TypeError: el is undefined.

This is caused by the empty field Default purchase tax in Settings/Configuration/Accounting
which can be emptied by deleting the currently selected tax in Accounting/Configuration/Taxes/Taxes

**Comment by mart-e** [comment]
Hello,

Can not reproduce on local and runbot. Please give more detail on how to reproduce. IF you have a traceback, post it.

**Comment by mirnovak** [comment]
Hi, to reproduce the bug:
1. In Accounting/Configuration/Taxes/Taxes and make a duplicate of a tax, e.g. OTAX S 
2. In Settings/Configuration/Accounting selelect Settings/Configuration/Accounting  the newly created duplicate tax
3. In Accounting/Configuration/Taxes/Taxes delete the newly created duplicate tax
4. In Purchases/Products/Products press Create
The Odoo Client Error TypeError: el is undefined appears

How can I get the traceback?

**Comment by mart-e** [comment]
Ok I see what happens, thanks for  the additional info.
Well actually it's a known issue. When we delete a record, the linked default values are not deleted (too complex to cover all cases).
To fix that, you have to go back to settings and put a different value/remove it.

**Comment by mirnovak** [comment]
Ok, thanks. At least this post will help somebody else in the same problem.
It took me half a day to find out what caused the problem as I could not find the solution on the web..
