### ISSUE TITLE
login redirection to /web lead to 500 server error

### ISSUE THREAD

**Issue by monami7000** [odoo/odoo#4518]
if a user is has only 'public' access right when he signs up in website, why is he redirected to /web?...
this will rise 500 server error, because he dosent have access right to /web?...

reproduction of the issue:
-> make sure the website module is installed
-> enable public signup from setting and change to 'public user'
->logout then press login then signup
->enter mail and username and password then press signup

**Comment by mart-e** [comment]
Public user are not intended to sign up, this user is intended to access the website without logging in, it's for some kind of website user interface.
So indeed this will not work but we do not plan to make it work.
What we could accept in a pull request is hiding the "Public User" from the list of users.
