### ISSUE TITLE
BBA Structured Reference missing

### ISSUE THREAD

**Issue by dimitriverhelst** [odoo/odoo#45244]
Impacted versions:
13

Steps to reproduce:
install l10n_be_invoice_bba
Current behavior:
configuration panel under accounting is missing
Expected behavior:
configuration panel is visible.  the view, present in Odoo 12, was not forwarded to Odoo 13

**Comment by dimitriverhelst** [comment]
The configuration option appears to have moved to the account journals, under advanced.
The readme on the module is outdated.

**Comment by pedrobaeza** [comment]
Which readme are you mentioning? Maybe you can put a pull request fixing that.
