### ISSUE TITLE
[13.0] Barcode inventory adjustment in multi-warehouse, couldn't scan Location is not child of the main Location

### ISSUE THREAD

**Issue by ibrahim08** [odoo/odoo#45247]
Impacted versions:
13.0 Enterprise
Steps to reproduce:
0. Create 2 Warehouse: WH1, WH2 go to WH2/Stock  and print Barcode
1. Open Barcode Application
2. Select Inventory Adjustment
3. Scan Barcode of WH2/Stock

Current behavior:
Warning: The Location is not child of the main Location

Expected behavior:
Select Location Scanned when using Multi Warehouse

Video/Screenshot link (optional):
![Barcode Error](https://user-images.githubusercontent.com/22815708/74374980-8eb5f280-4df0-11ea-982a-cc15b4845869.jpeg)

**Comment by pedrobaeza** [comment]
As this is something enterprise, please report it at odoo.com/help instead.
