### ISSUE TITLE
[13.0] Purchase to Bill: Source Document field have no information about purchase name

### ISSUE THREAD

**Issue by vmaxadmin** [odoo/odoo#45250]
Impacted versions:
13.0 Community

Steps to reproduce:
- Install the Accounting module
- Install the Purchase module
- Create a new Purchase Order, add products
- Confirm the Purchase Order
- Then create a bill and save.

Current behavior:
- The Source Document field on Vender Bill empties

Expected behavior:
- I expect this field to have information that is the original purchase name.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/16912480/74408517-3bcb5200-4e67-11ea-9529-5c48bc645e8c.png)

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/45456
