### ISSUE TITLE
Chinese Chart of Accounts - only Chinese Character

### ISSUE THREAD

**Issue by vrms** [odoo/odoo#4526]
account_chart_small_business_template.xml
account_chart_template.xml
account_tax.xml
account_tax.xml

contain accounts and account categories in Chinese Characters. So this CoA is only usable for users who can read Chinese. There should be bi-lingual (en_zh) versions of those files, so Chinese companies with users that can not read Chinese can use these template

I will provide a pull request shortly that adds such copies

**Comment by mart-e** [comment]
Hello,

The chart of account is currently in only one language, check with Chinese community (cc @jeffery9) if there is plan to make bilingual but it's not currently the case.

If you plan to work on it, check l10n_be or l10n_ch modules which already have multilang support.
