### ISSUE TITLE
Project task showing wrong date deadline on kanban view

### ISSUE THREAD

**Issue by Rafaellinos** [odoo/odoo#45310]
Impacted versions: ODOO13

Steps to reproduce:
In Project module, create a project and a new task, set the field 'date_deadline' to today. The date informed in kanban view is one day late, this is happening if you set the date for tomorrow aswell.

Current behavior:
Showing the date_deadline one day late
Expected behavior:
Shows the correct date in kanban view.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/46793145/74446024-12ee9100-4e56-11ea-9039-98f626e35f2e.png)

![image](https://user-images.githubusercontent.com/46793145/74446056-1c77f900-4e56-11ea-912a-f9901bd0c438.png)

**Comment by pedrobaeza** [comment]
Is your timezone set?

**Comment by Rafaellinos** [comment]
Yes.
![image](https://user-images.githubusercontent.com/46793145/74473934-41cf2c00-4e83-11ea-8cfa-15868c3fb497.png)

**Comment by pedrobaeza** [comment]
Then that should be the problem: in kanban view the date is not shown with tz. This means this seems a bug, but at least you have the explanation.

**Comment by Rafaellinos** [comment]
The problem seems to be related to this part:
`<t t-if="record.date_deadline.raw_value and moment(record.date_deadline.raw_value.toISOString()).startOf('day') lt moment().startOf('day')">`
I changed to:
`<t t-if="record.date_deadline.raw_value and moment().toDate() > record.date_deadline.raw_value">`
In order to show the date correct and in add the 'red' class. i'm also showing the field direcly <field name="date_deadline"/>, instead of setting the date.

**Comment by Rafaellinos** [comment]
I found out that this problem was already solved on that commit https://github.com/odoo/odoo/commit/a5f85558219107b57a3055722a3803e3848eab3e#diff-3386c184153aa56f2a2be82ad681abdb
Sorry about it guys.
