### ISSUE TITLE
__bool__ returns False on any NewId, even if origin is set to an existing record

### ISSUE THREAD

**Issue by fdegrave** [odoo/odoo#45346]
Impacted versions: 13.0

Steps to reproduce: Call bool(...) on any NewId, even with `origin` set to an actual id.

Current behavior: This causes issues when converting values returning from an onchange call, because since the latest version recordsets in onchange are not "actual" recordsets with "actual" ids, but rather recordsets with NewId instances as ids. That means for example that if you set a Many2one field during the onchange using such a record as the value, since `convert_to_onchange` on the Many2one field considers the NewId object as "False", it returns an actual "False" to the client as the value

Expected behavior: The value returned by `convert_to_onchange` should treat, for example, res.partner(<NewId origin=3>,) the same way as res.partner(3,)

Video/Screenshot link (optional):

**Comment by Elkasitu** [comment]
Do you have a concrete business case / workflow where this is an issue?

It's doable by changing the the `convert_to_onchange` of the `Many2one` class but we would need a solid use case to implement it (and test it), if implemented it probably would not be done in 13.0 as it'd break our stable policy.

**Comment by fdegrave** [comment]
[foo.zip](https://github.com/odoo/odoo/files/4216124/foo.zip)

Here you can find a simple example to demonstrate the error (no ir_model_access, need to be superuser to test it). The example is quite stupid but simple enough to show that the error will probably happen for you in the future as well: basically, when a tag is added to the tag_ids field (many2many), a new line is added to line_ids (one2many) with tag_id set to the newly added tag (through an onchange - same behavior with a writable functional field, though). As you can see when doing
`new_line.tag_id = tag`
the line is created with an empty tag_id (the json returned to the client contains false for tag_id) while
`new_line.tag_id = tag.browse(tag.id.origin)`
is the only thing that seems to work (but is ugly).

**Comment by pedrobaeza** [comment]
Coming to this through codetriage.com.

@Elkasitu did you have the chance to take a look to this?
