### ISSUE TITLE
'Time & Material to Invoice' is duplicating descriptions in invoice

### ISSUE THREAD

**Issue by kvdb** [odoo/odoo#4536]
Impacted versions:
- 8.0

Steps to reproduce:
1. Create several time sheet entries.
2. In Sales -> Invoicing -> Time & Materials to Invoice
3. Select all entries listed (several time sheet entries for 2 users)
4. Select More -> `Create Invoice`
5. Select [x] Date, Time spent, Description
6. Select `Create invoices`
7. Observe a new invoice, has been created

Current behavior:

The invoice has 2 invoice lines. The `quantity` represents the number of hours what each users has spent. However, the `description` field of each invoice line contains all descriptions that were entered in the timesheet for both users combined. Effectively duplicating that information.

Expected behavior:

Each invoice line should have a description the shows only the descriptions entered in the timesheet for the one user that the invoice line represents.

**Comment by samuellefever** [comment]
Affecting me too!

**Comment by stephaniemillet** [comment]
Badly affect customer with contract number - M1505132226441 - going live next monday.
Thank you for an urgent correction

**Comment by Yenthe666** [comment]
Hi @kvdb ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
