### ISSUE TITLE
[8.0] unexpected footer in invoice PDF report

### ISSUE THREAD

**Issue by kvdb** [odoo/odoo#4537]
Impacted versions:

 - 8.0

Steps to reproduce:

 1. Settings -> Companies -> my Company -> Report Configuration
 2. Observe `Custom footer` is off. (default setting)
 3. Observe `Report footer` contains bank account.
 4. Click Preview Header/Footer. Observe bank account shows in footer.
 5. Accounting -> Customer Invoices -> Create a new customer invoice -> Save -> Print

Current behavior:

Observe the PDF invoice has a different footer not containing bank account information.

Expected behavior:

The PDF invoice should show the same footer as defined in my Company.

Workaround:

The expected footer shows correctly on the PDF invoice when performing these steps.

 1. Settings -> Companies -> my Company -> Report Configuration
 2. Enable `Custom footer`
 3. Save

Another workaround: http://odootricks.wordpress.com/2014/11/05/how-to-change-the-default-headerfooter-in-odoo-8-pdf-reports-salequoteinvoice/

**Comment by sle-odoo** [comment]
Hi,
The preview header/footer button you clicked is in the rml category, so it previews the rml report. Invoice report (and most of the legacy reports) are qweb reports.

Regards

**Comment by sle-odoo** [comment]
They [don't share](https://github.com/odoo/odoo/blob/8.0/addons/report/views/layouts.xml#L99) the custom footer. I suppose RML reports also have a default footer and show the custom one only when it's enabled.
It's there to ease the transition from RML to QWeb report. But yeah it's kind of not intuitive.

Regards

**Comment by jadoux** [comment]
Unfortunately kvdb solution doesn't seem to work, I followed the instructions and enabled custom footer, even restarted odoo service, and still an invoice is not showing any bank account details ...

**Comment by forvas** [comment]
@jadoux in my case, @kvdb solution worked for me. Have you checked the invoice report you are printing is not being reloaded from attachment? Got to *Settings > Technical > Reports > Reports* and look for the *Invoices* report. Then, open it and check that *Reload from Attachment* option is disabled. If not, disable it, save, and try to print the account invoice again.
