### ISSUE TITLE
[All] translation: removal of non-active plural-language files

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45401]
Impacted versions: All supported versions

Steps to reproduce: 
Imagine having a language where there are different plurals, for example Dutch (`l10n_nl`) and Flemish (`l10n_be`), and that the language was removed on Transifex at some point. The `.po` files will remain in Odoo and will be forward ported even though they're no longer being used. This uses up extra space/files etc that have no added value.

Quite a while ago the Flemish language has been removed from Transifex (`l10n_be`) but all the `.po` files have been forward ported to V11, V12, V13. You can see an example of a source file at https://github.com/odoo/odoo/blob/13.0/addons/account/i18n/nl_BE.po 
Since the sources are no longer available for translations (see http://www.transifex.com/odoo/odoo-9/language/nl_BE for example) and since this language has so little translations I wonder why all those sources files are kept.

Why don't we remove all the `nl_BE.po` files and just take the translations from Dutch? We can't manage the source terms anymore anyways.

**Comment by Yenthe666** [comment]
@mart-e hey is there a good reason why we still keep `l10n_BE` in the `i18n` direct? Couldn't we remove it all and fall back to Dutch (`l10n_nl`)? Maybe I'm missing something though

**Comment by mart-e** [comment]
Hi,

Aren't you mixing up l10n (chart of accounts) and i18n (translations) ?

Do you actually have an issue with nl_BE.po files?
If a source term is not found in a nl_BE.po, it will just look at the nl.po file, no problem to keep these files even if they are not managed on Transifex.
Keep also in mind that git stores **diff**, so forward porting by merging a bunch of commits into from one branch to another cost almost nothing. If you add and remove a 1MB file, it costs you 2MB of diff. Removing it will just increase the size of your repository and not decrease it.

Even if not managed on Transifex, we can also accept PR for translations of regional terms (for words that would be different in nl_BE than nl).

**Comment by Yenthe666** [comment]
@mart-e no, I don't think I'm mixing things up. 

The `l10n_be` files are 99% empty or so though.
What good do the po files have if they cannot be managed on Transifex and if they are so empty? I don't see much added value in them now. Especially not since both languages are nearly identical in terms of vocabulary.

Note: didn't know that removal would end up with a bigger repository than a smaller.. Interesting.

**Comment by mart-e** [comment]
> no, I don't think I'm mixing things up
> Couldn't we remove it all and fall back to Dutch (l10n_nl)?

Sorry but I don't get how you would fallback the translations of one localisation to another one, there is no link between l10n_be and l10n_nl.
Also are you talking about `nl_BE.po` files in general or in `l10n_be`? I feel like we are mixing two subjects (translations of localisations and translations in regional languages).

For `l10n_be` the translations lies in two folders `i18n` and `i18n_extra`. All the important translations are in `i18n_extra`. This is for historical reason and now there is not much that justify keeping both. We will probably merge them at one point.

Regional translation files (like `fr_BE.po`) are expected to be mostly empty. The point is to put there only the terms that are different from the reference language.

**Comment by Yenthe666** [comment]
> This is for historical reason and now there is not much that justify keeping both. We will probably merge them at one point.

I guess you could take this as a conclusion :) Is there anything planned for this?

**Comment by mart-e** [comment]
No, not really because as explained, it does not cause any issue to leave them.
The most likely is that we will remove them at the same as we move all the .po files outside of odoo/odoo repository (but this is really a long time plan).
Closing as nothing to be done now :)

**Comment by Yenthe666** [comment]
Yeah that's still the dream, to separate it all from Odoo its directory. Alright, thanks for the feedback.
