### ISSUE TITLE
 Kanban view remove default grouping condition invalid

### ISSUE THREAD

**Issue by liweijie0812** [odoo/odoo#45405]
Impacted versions:
13.0
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://youtu.be/_RQTmSMscGc

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/44906

**Comment by pedrobaeza** [comment]
Closing then
