### ISSUE TITLE
[13] web: Issue on Exporting html field

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45435]
Impacted versions: 13.0

Steps to reproduce: Export View which contains HTML field
![image](https://user-images.githubusercontent.com/16624719/74587985-c4d8b980-501e-11ea-8ff5-f1d68b1f1ea9.png)

Current behavior: HTML body is exported instead of visible text 
![Screenshot from 2020-02-15 18-13-05](https://user-images.githubusercontent.com/16624719/74587994-dae67a00-501e-11ea-84c2-d29dbc1c0ea2.png)

Same at
![Screenshot from 2020-02-15 18-11-54](https://user-images.githubusercontent.com/16624719/74588001-e2a61e80-501e-11ea-902f-786be105a7df.png)

Expected behavior: Plain text should be exported

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
For me it's correct to output raw HTML for being able to later re-import that field with what you want. If you want to be "readable", then transform it on your end. Export option is not only for being human readable.

**Comment by Yenthe666** [comment]
Yep, this is for sure desired behaviour. It worked like that even back in V8 and it should work like this. How else should you modify the HTML content? If you export text and then import it you loose all the HTML features.
