### ISSUE TITLE
[odoo crash]  odoo crash on server.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#4544]
Hell o odoo,

Odoo I had setup on VPS server with 4 GB RAM + 90 GB HDD, 4 Core CPU.

It was running for 2 days and sudden stop after getting few traffic on website which build from odoo framework.

Also few server access,  even not high traffic.

Its stop to working, need to restart again many time, only issue with v8.

Thanks,

**Comment by Yenthe666** [comment]
@tejastank you have no logfiles, no proof, no screenshots and this is probably not even an issue.
You should post to the official Odoo help forum (https://www.odoo.com/forum/help-1) and provide your logfile. Other people that like to use Odoo will help you there with this problem.

**Comment by tejastank** [comment]
@Yenthe666 ,

If you do not want to deal with issue kindly avoid to answer, Their is issue, so users of odoo post issue here, 

1. I had no log configured, because we do not expected.

As sudden server stopped in server, how can I send screenshot ? which things working in background. 

If always other people like to help then please close issue permission of other world.

@Yenthe666  really gives disappointing response.  Lease respect who helps to correct this product.
I hope next time you respect other who already gives contribution since version 5,6,7...

People who new or old users of openerp, kindly repsect their post and consider their are issues so people ask to odoo.

Its bug, not question of erp flow that I ask to other guys.

I hope you kind of people understand this.

If you till not understand, kindly leave this issue, I will manage coordination with other from community or other odoo guys.

**Comment by Yenthe666** [comment]
@tejastank configure logfiles the next time though. If you get an internal server error and you have no logfiles the only place to find anything out is by terminal. Logfiles are a great way to find out what went wrong in the past!
Provide a printscreen from the terminal showing the error here then? Perhaps this give a general idea about what went wrong. 

I'm sorry that you took this as offensive/dissapointing, I didn't mean to offend you in any way. Its just that these kind of reports get closed all the time without any help so I thought I'd give you another way to find a solution too.

Can you provide anymore details about the problem?

**Comment by smack815** [comment]
@tejastank you should really [configure Odoo logs](https://www.odoo.com/documentation/8.0/reference/cmdline.html#logging) on all your servers so that the community and Odoo can be more helpful to your requests.  Sorry we could not be more helpful.
