### ISSUE TITLE
[13.0] [website] Two CSS error windows with different layout

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#45447]
Impacted versions: 13.0

Steps to reproduce: create a CSS problem in a website module, or just install [auto_register](https://apps.odoo.com/apps/modules/13.0/odoo_auto_register/), whichever theme is used.

Current behavior: website creates two successive CSS error windows, with different layout as shown in screenshots :
![white OK button on the right](https://user-images.githubusercontent.com/24126/74604454-8bf02180-50be-11ea-8588-146a2a3d94fc.jpg)
![purple OK button on the left](https://user-images.githubusercontent.com/24126/74604452-8561aa00-50be-11ea-864f-fecbaa4fc612.jpg)

Expected behavior: very minor issues, but OK button should at least be on the same side.

**Comment by rdeodoo** [comment]
@qsm-odoo Your input would be welcome here.
See https://github.com/odoo/odoo/commit/c248674a5c615c9db113357eec9d9adaf50b888e, given the commit message it should be a fallback but it alctually shows the alert even if the dialog is shown.

**Comment by qsm-odoo** [comment]
Mmh probably introduced by JS lazy loading and/or use of native promises. The current code can not work indeed. I'll fix that.
