### ISSUE TITLE
Better documentation for `t-debug` and QWeb debugging

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#4547]
The [documentation on the QWeb debug features](https://www.odoo.com/documentation/8.0/reference/qweb.html#debugging) is not very helpful (IMHO).

In particular, it is not clear how the `t-debug` directive is to be used, and no example for it is available in the source code. Is it possible to provide some usage examples?

**Comment by dreispt** [comment]
Until the docs get updated, is it possible to give us some quick insight on it here? Thanks in advance.

**Comment by guewen** [comment]
Place <t t-debug="pdb"/> somewhere and the server will stop in pdb (you can
also put pudb or ipdb...)

**Comment by dreispt** [comment]
Thanks Guewen. I thought it was a Javascript side breakpoint.

**Comment by LeartS** [comment]
I may be remembering wrong, but I think I tried <t t-debug> in the past and it worked like a javascript breakpoint.

**Comment by guewen** [comment]
For reports, qweb is rendered server-side in python, see where the t-debug attribute is handled: https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_qweb.py#L288-L290

@LeartS you are right, it could also be a javascript breakpoint when qweb is rendered client side https://github.com/odoo/odoo/blob/8.0/addons/web/static/lib/qweb/qweb2.js#L761-L763

So, qweb server-side (reports): `<t t-debug="pdb"/>` and qweb client-side: `<t t-debug/>` I guess.

**Comment by dreispt** [comment]
@LeartS @guwen Nice, I will try both and report back.
 The docs only mention the Javascript support only, so I guess they're incomplete.

**Comment by LeartS** [comment]
Nice, thanks

**Comment by JKirega** [comment]
I have tried using the same `<t t-debug="pdb"/>` in the Qweb reports but i  cant get the breakpoint. My server keeps running as though there is no breakpoint.

**Comment by phillipstack** [comment]
I am trying to work through this as well right now. However I found ( for server side rendering ) in order to have the debugger stop at the breakpoint you need to run the server with the following flags in the commandline 

./odoo-bin -d your_db_name --dev qweb

If you do not have this enabled you will see the following in your log file

@t-debug in template is only available in dev mode options

**Comment by hkbluesky** [comment]
But how do I know a qweb is server-side or client-side? How about /addons/web/src/xml/base.xml
Is this a server-side or client-side qweb?

**Comment by dreispt** [comment]
For Kanban Views, it is rendered Client Side.
For Reports and Website pages, it is rendered server side.

**Comment by evorion** [comment]
This handles t-debug:

`    def _debug_trace(self, debugger, values):
        """Method called at running time to load debugger."""
        if debugger in SUPPORTED_DEBUGGER:
            __import__(debugger).set_trace()
        else:
            raise ValueError(f"unsupported t-debug value: {debugger}")
`

So if it's a Python debugger it will break in the Odoo server. If no debugger is passed it will break in JavaScript.
