### ISSUE TITLE
--save command line option does not handle log_handler correctly

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#4552]
Affected versions: 7.0 and later

steps to reproduce:

1. run:

    openerp --save -c /tmp/config  --stop-after-init

2. edit `/tmp/config`:
    * remove the line`log_level = info`
    * change the line `log_handler = [':INFO']` to `log_handler = [':CRITICAL']`

3. run `openerp -c /tmp/config --stop-after-init`

Expected result: no log line with a level less than CRITICAL is displayed

Actual result: I get lots of INFO level log lines

4. edit `/tmp/config`
    * change the line `log_handler = [':CRITICAL']` to `log_handler = :CRITICAL,openerp.service:INFO`

5. run `openerp -c /tmp/config --stop-after-init`

Observed result: only openerp.service INFO log level displayed

My conclusion is that either the parsing of the configuration file must be fixed, or the generation of the configuration file must be fixed. As is things are broken and difficult to figure out.

**Comment by gurneyalex** [comment]
See also #4550

**Comment by gurneyalex** [comment]
My personnal take on this is that `--save` should produce the current working configuration in order not to break existing deployments.

**Comment by xmo-odoo** [comment]
@gurneyalex #4157?
