### ISSUE TITLE
[12] Oauth session expired when logging in on other device/browser

### ISSUE THREAD

**Issue by Bart-DCBO** [odoo/odoo#45526]
Impacted versions: 12

Steps to reproduce:
Log in with a user with Oauth in on a device/browser, then log in with the same user on another device/browser (on same device) with Oauth.

Current behavior:
For Oauth users you will get a session expired on the 1st device/browser

Expected behavior:
To be the same as normal username/password users, we can work on both browsers/devices.

Note:
This issue came to light when a warehouse user wanted to use his account both on his pc and a Zebra handscanner for barcode scanning.

**Comment by pedrobaeza** [comment]
I don't have this problem working with Google OAuth, so something should be triggering that disconnection. Maybe the OAuth server configuration?

**Comment by Bart-DCBO** [comment]
This problem occurs when logging in with 1 user on 2 devices/browsers at the same time.

**Comment by Bart-DCBO** [comment]
We added no advanced configuration, we used a new Google account to set up Oauth, and just followed the steps in: https://www.odoo.com/documentation/user/12.0/general/auth/google.html

A quick way to reproduce the issue is to login with an Oauth user in Chrome, then login with that same Oauth User in firefox, the user will then get a session expired in Chrome, when we login again in Chrome we will get the session expired in firefox.

**Comment by pedrobaeza** [comment]
Yeah, but this seems something of Oauth configuration in your end (not in Odoo's end).

**Comment by pedrobaeza** [comment]
Closing as no more answer.

**Comment by mlaitinen** [comment]
For anyone looking for a solution, try this amazing module by OCA: https://github.com/OCA/server-auth/tree/12.0/auth_oauth_multi_token

It allows you to have multiple OAuth Access Tokens and you will no longer be logged out when using >1 devices to access Odoo using OAuth.
