### ISSUE TITLE
[8.0,master] Helpdesk and support display follower list below chatter

### ISSUE THREAD

**Issue by pna-odoo** [odoo/odoo#4553]
**Effected Version :** 8.0, master

**Steps:** Go to Sales > After Sale Services , open or create Helpdesk request. The follower list display at wrong position.
![documentation for crm- - odoo](https://cloud.githubusercontent.com/assets/7599574/5628986/2c5915a6-95d4-11e4-9e26-be53c39f1658.png)

Same problem in Fleet also:
![1-ack-205 - odoo](https://cloud.githubusercontent.com/assets/7599574/5641426/d0842668-965e-11e4-8cea-0d1a97d763d7.png)

**Comment by mart-e** [comment]
@pna-odoo probably just the view definition, could you make a pull request ?
