### ISSUE TITLE
[12.0] Error raised when creating quotation from lead

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#45546]
Hello,

We have several clients that use automated actions to add follower channels to quotations when they're created from leads, in order to notify their sales teams.

When creating a quotation from one of those leads (that has a partner_id associated, but no follower at that time) and saving it, the constraint 'partner_xor_channel' is triggered and prevents saving that quotation, with the message "Error: A follower must be either a partner or a channel (but not both).". It seems that the partner_id is being added to the vals as if it was a follower.

In order to reproduce the error:
- Create an automated action to add a channel as follower on sale order creation;
- Create a lead with a set partner_id;
- Create a quotation from the lead.

This is something that was probably brought on by a very recent update, since those clients have been using this system for a long time and only started getting this error today.

Thank you.

**Comment by reinaldoramosarxi** [comment]
Hello,

This issue is really crippling for our clients, we would like to know if there's anyway that we could get to a quick solution.

Thank you.

**Comment by pedrobaeza** [comment]
If you have an enterprise contract, report it through odoo.com/help. Odoo assures an SLA in that cases.

**Comment by reinaldoramosarxi** [comment]
Thank you, I will.
