### ISSUE TITLE
In Odoo Help Forum: Convert answer to comment and author name changes

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#45568]
Impacted versions: 13

Steps to reproduce: Convert answer to comment

Current behavior: Author name changes to person who converted answer to comment

Expected behavior: Author stays the same!

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/38899643/74708646-06a07480-5258-11ea-970b-50406ba7f9b9.png)

https://www.odoo.com/forum/help-1/question/multi-company-setup-how-to-stop-sharing-contacts-v13-sh-163867

**Comment by rrahir** [comment]
Hi, a fix is already on the way #45732  and the situation should be back to normal by next week.

**Comment by ctringham** [comment]
Will this fix correct the answers already in the Odoo Help Forum or only apply to new activity?

(The example shown above is still showing the wrong author for that answer / comment)

**Comment by Yenthe666** [comment]
@ctringham I expect odoo.com hasn't been updated yet :)

**Comment by ctringham** [comment]
It's still showing the wrong author for answers converted to comments, which is very confusing!!

**Comment by ctringham** [comment]
Currently it seems that it's not changing the author but it does change the date to when it was converted to an answer.  It should stay the same!

And old answers converted to comments still don't have the correct author.

**Comment by rrahir** [comment]
It seems indeed that the issue was not properly solved by the suggested commit and that we need to make a more indepth bugfix. I have transfered this to our dedicated bugfix team that will assert a proper way to address this problem.

**Comment by Yenthe666** [comment]
@rrahir what is the status of this?

**Comment by rrahir** [comment]
We are still wrking on a solution. I will keep you informed once we find a suitable solution. I apologize for the time it takes but we have more urgent matter to attend.

**Comment by ray-odoo** [comment]
I am now getting this when trying to convert an answer into a comment:

![image](https://user-images.githubusercontent.com/41073831/82603067-dde58f00-9b66-11ea-8729-a18d6656d58c.png)

Just for information (in case it helps).

This was the post: https://www.odoo.com/forum/help-1/post/re-opening-statement-first-synchronization-bank-synchronisation-170825/convert_to_comment

The account I am using has 7145XP.

**Comment by Yenthe666** [comment]
Would it add any value if I make an OPW for this?

**Comment by rrahir** [comment]
@ray-odoo  @Yenthe666 I think an OPW request is in order here. This last issue doesn't seem related to the problem at hand.
@ctringham 
The bugfix has paused the  request for now as they have bigger priorities. So we will probably make a local customization to solve the author issue but the date issue will probably have to wait some more to be corrected.

**Comment by Yenthe666** [comment]
OPW `2262832`

**Comment by ctringham** [comment]
I think the example from @ray-odoo should be posted here: https://github.com/odoo/odoo/issues/51296
(which is currently closed, but should be re-opened?)

**Comment by Yenthe666** [comment]
Don't worry we have this issue & an OPW about both these issues so they should be handled anyways.

**Comment by Yenthe666** [comment]
I've got the 403 today too on https://www.odoo.com/forum/help-1/question/odoo-server-configuration-connection-lost-restore-170909 when trying to convert the answer from Driss Doukkali. I've got 37K+ karma so yeah 😆

**Comment by rrahir** [comment]
We have posted a local fix on our production platform. The karma related issue is still being investigated by our support team and will be addressed in the OPW craeted by @Yenthe666.
I will now close this issue and invite you to follow https://github.com/odoo/odoo/issues/51296 for the karma related issue.

**Comment by nim-odoo** [comment]
Note: it's an AccessError, not a Karma error. It should be fixed with https://github.com/odoo/odoo/commit/ce63a20ca26f1773ea7e1133b0a3796fda692e11
