### ISSUE TITLE
Odoo help forum: clicking on "Tags" menu gives too many requests errors

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45576]
Impacted versions: Odoo.com

Steps to reproduce:
1. Go to https://www.odoo.com/forum/help-1
2. Click on "Tags"

Current behavior:
The window loads very slowly, nearly crashing your browser and the amount of requests (because of the amount of tags) causes 429 too many requests errors:
![image](https://user-images.githubusercontent.com/6352350/74714752-8237fc80-522b-11ea-863b-953cd82fb53e.png)

Expected behavior:
Partial tag loading or loading them all without the too many requests errors (and faster).

**Comment by Yenthe666** [comment]
This also causes this:
![image](https://user-images.githubusercontent.com/6352350/74714821-9ed43480-522b-11ea-8719-90ad4b4e2fca.png)


Which is very annoying

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/pull/35749#discussion_r319149551 :man_shrugging: 
We will investigate this one asap

**Comment by rdeodoo** [comment]
The page will be accessible again. Problematic code has been removed temporarily while a fix is made.

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/commit/c593e7d5985f2332d3d0534eb46a742d459d4fd1

**Comment by Yenthe666** [comment]
Great fix @rdeodoo - good job!

**Comment by ltcompanym3** [comment]
![image](https://user-images.githubusercontent.com/105342143/169496412-e7166c36-381c-46ac-9d5e-21c0b83d797a.png)

**Comment by JKE-be** [comment]
thank you @ltcompanym3 for this up of topic. But it is unlinked to the forum this time ;)

**Comment by ray-odoo** [comment]
Please check browser extensions if you are being rate limited, our analysis so far has identified two problematic extensions.

1. Odoo Terminal
2. Odoo Info

Extension location for Firefox: 
- https://addons.mozilla.org/en-US/firefox/search/?q=odoo

Chrome
- https://chrome.google.com/webstore/search/odoo?hl=en

See also https://github.com/Tardo/OdooInfo/issues/2
