### ISSUE TITLE
Odoo help forum: no longer possible to accept answers

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45575]
Impacted versions: Odoo.com
 
Steps to reproduce: See https://www.odoo.com/forum/help-1/question/after-deletion-of-module-from-addons-the-app-is-still-appearing-in-apps-list-164935 for example
 
Current behavior:
There is no accept answer option shown

Expected behavior:
The option to accept an answer is shown and you can mark an answer as accepted/not accepted

**Comment by rrahir** [comment]
The migration apparently set the existing forums to the wrong mode, which prevented people from acceptng answers. The situation should now be solved.

**Comment by Yenthe666** [comment]
It is indeed fixed and the best part is: we can now remove the accepted answer or give it to somebody else if there is a better answer. Neat!
