### ISSUE TITLE
Purchase order billing problem if no article?

### ISSUE THREAD

**Issue by nono6677** [odoo/odoo#4557]
Hi,

I have created purchase order with no article but with a description (name of purchase order line) and when i valid,  i have a problem.
I can neither start  billing nor cancel the purchase order, it's normal ? i think the workflow doesn't has path for this case 
For information, if i change the payment method to "order" it's ok..
Why article as not required in other payment method (manual, picking) ?
It's a bug ?
my fault ?

best regards,

**Comment by flotho** [comment]
Hy nono6677, maybe #4131 could solve your problem

**Comment by Yenthe666** [comment]
Hi @nono6677,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
