### ISSUE TITLE
Odoo Help Forum: Comments displayed oldest first!

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#45571]
Since the upgrade, comments are displayed oldest first, which is rather confusing (especially since the time is not shown).  Can it be put back to how it was before?

![image](https://user-images.githubusercontent.com/38899643/74708492-9134a400-5257-11ea-9fb3-19b9839b60c9.png)

**Comment by rrahir** [comment]
Hi,
A pull request has been suggested and it will be fixed in production is the coming minutes.
#45817
