### ISSUE TITLE
Odoo help forum: badges 

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45579]
Impacted versions: odoo.com

Steps to reproduce: Go to https://www.odoo.com/profile/ranks_badges?badge_category=forum
![image](https://user-images.githubusercontent.com/6352350/74716253-7863c880-522e-11ea-898c-c6757836e7e4.png)

Current behavior: 
No badges or info shown

Expected behavior:
Badges and info are shown

Video/Screenshot link (optional):

**Comment by rrahir** [comment]
Thanks for reporting this. I have republished the badges linked to the forum :)

**Comment by Yenthe666** [comment]
Woohoo, thanks a lot @rrahir 😃 There also seems to be an issue with the badge icons on the preview of a user:
![image](https://user-images.githubusercontent.com/6352350/74923019-60c44580-53d0-11ea-8f43-4d9185ca91d2.png)

**Comment by rrahir** [comment]
Yup, I saw that while going through the forum issues, it's in my backlog ;-)

**Comment by ammarelamin** [comment]
Hey Yenthe,
badges don't appear in my profile, I completed many courses and have over 5000 xp, yet have only one badge **Find your Catalyst** . I reviewed many related questions and followed a lot of steps, but nothing changed.
here's link to my profile [https://www.odoo.com/profile/user/1425209](url)
Any suggestions!?

**Comment by ammarelamin** [comment]
Hey Yenthe,
badges don't appear in my profile, I completed many courses and have over 5000 xp, yet have only one badge Find your Catalyst . I reviewed many related questions and followed a lot of steps, but nothing changed.
here's link to my profile https://www.odoo.com/profile/user/1425209
Any suggestions!?

**Comment by Yenthe666** [comment]
Sadly badges break a LOT of times, I've seen them fail/break probably 10 times in the last 3 years. @JKE-be are you aware of any new issues?

**Comment by ammarelamin** [comment]
The weird thing is some updates are running fine for some users, am tracking **Latest achievements** in learning platform and some people are getting their badges.

**Comment by rrahir** [comment]
Still have to identify the reason behind this issue but it's fixed on prod for now.
