### ISSUE TITLE
Statusbar clickable in view mode

### ISSUE THREAD

**Issue by Garcicasti** [odoo/odoo#45581]
Impacted versions: 11.0, 12.0, 13.0

Steps to reproduce: Create a custom view with statusbar, option clickable = True.

Current behavior: The statusbar is clickable whether we are editing the record or not.

Expected behavior: We should probably only be able to change the state by clicking on the statusbar **if** we are in **edit mode**.

Video/Screenshot link (optional): 

![image](https://user-images.githubusercontent.com/23293693/74716707-5fa7e280-522f-11ea-98bf-31bb4b31c942.png)

![image](https://user-images.githubusercontent.com/23293693/74716756-7817fd00-522f-11ea-85cf-7e004bba3505.png)

Thanks for your help!

**Comment by Yenthe666** [comment]
This is absolutely done by design and with purpose. Won't be changed.

**Comment by Garcicasti** [comment]
@Yenthe666 Do you have any suggestion on how to do this change in a client-level personalization? 
Thanks.

**Comment by Yenthe666** [comment]
Either by adding a JS widget to control this or by adding another logic to trigger state changes only when in edit mode (for example with buttons or api.onchange)
