### ISSUE TITLE
[Inventory] On owner assignment system auto changing reserved qty from 1 to 0

### ISSUE THREAD

**Issue by vishwanathchannagiri** [odoo/odoo#45595]
Impacted versions: 
**ODOO 12.0**

Steps to reproduce:
Internal Stock Movement
- I have enabled the Consignment configuration in the Inventory Settings.
- While doing internal transfer between the locations in the same warehouse with the owner assignment.

Current behavior:
- While doing internal transfer between the locations in the same warehouse with the owner assignment, system auto changing the reserved qty to zero while assigning the owner to the stock move line, Because of this it is creating a negative entry in the stock quant object this leads to a mismatch in the stock at the particular source location. System proposing the already processed serial nos for the next time because of this behavior
Expected behavior:
- While doing internal transfer between the locations in the same warehouse with the owner assignment, the system should not auto-change the reserved qty to zero while assigning the owner to the stock move line, then all the stock movement will place correctly including in the source location stock
Video/Screenshot link (optional):

[out.zip](https://github.com/odoo/odoo/files/4218508/out.zip)

**Comment by sle-odoo** [comment]
This is the intended behaviour.

You're not changing the owner of the the product, you're forcing the system to use a product of an owner, that's why the reservation goes to 0 and a negative quant is created.

Owner can only be assigned when receiving products in your company.
