### ISSUE TITLE
[V13][BUG] XML tag function

### ISSUE THREAD

**Issue by jo541** [odoo/odoo#45592]
Impacted versions:
V13

Steps to reproduce:
1 . Create a tag function to change noupdate value
2 . In the function add comment
3 . Update the module
```
  <function name="write" model="ir.model.data">
            <!-- This is a comment -->
            <function name="search" model="ir.model.data">
                <value
                        eval="[('module', '=', 'board'), ('name', '=', 'menu_board_my_dash')]"
                />
            </function>
            <value eval="{'noupdate': False}"/>
        </function>
```

Current behavior:
An error is return 
`odoo.tools.convert.ParseError: "write() takes 2 positional arguments but 4 were given"`
The comment is read and is given has "None"

Expected behavior:
The comment in XML must be simply skip.

**Comment by 10537** [comment]
Hello Guys!

I have the same error.

**Comment by jorgeoandres** [comment]
I was looking for a solution for overwriting record rules. Thanks @jo541, by deleting the comments the code works.

**Comment by pedrobaeza** [comment]
Yes, this is a question of how lxml parses this, and not everything is allowed in the XML.
