### ISSUE TITLE
Wkhtmltopdf error

### ISSUE THREAD

**Issue by asmabelhadj123** [odoo/odoo#45605]
I installed wkhtmltopdf on a managed infomaniak server (ubunto 18.04),
I tried first with a simple code but I got this error :

 "**Warning: Unexpected character in input: '' (ASCII=15) state=0 in /usr/local/bin/wkhtmltopdf on line 2548

Warning: Unexpected character in input: '' (ASCII=2) state=0 in /usr/local/bin/wkhtmltopdf on line 2548

Parse error: in /usr/local/bin/wkhtmltopdf on line 2548**"

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by asmabelhadj123** [comment]
the problem I am on an managed server my access rights are very limited, I installed wkhtmltopdf from the "dashboard" page of my server
the version of wkhtmltopdf is "**wkhtmltopdf 0.12.5 (with patched qt)**"

**Comment by pedrobaeza** [comment]
Yeah, sorry, I'm afraid this is not something to be handled in this issue tracker, as it's only for bugs with Odoo code.
