### ISSUE TITLE
MO or work order do not check the availability of the required material or component

### ISSUE THREAD

**Issue by digitalsatori** [odoo/odoo#45621]
Impacted versions:
Tested on V13
Steps to reproduce:

Create a MO for a product A with a BOM composed of Material B (0 stock)

Current behavior:

1. I can produce the product A without Material B in stock, which caused Material B negative stock.

2. If we setup a routing for the BOM, The generated work order can also proceed without the availability of material B.

3. If Material B is config for lot tracking, I can assign any consumed lot ( the lot that is 0 stock) for material B and proceed with manufacturing process

Expected behavior:

It seems the first two are made on purpose, but I don't know the reasoning. 

I assume the expected way should be blocking the process and wait for the availability of material B, or Clicking a 'force produce' button if you really want to proceed.

The third one is really confusing, there supposed be a proper domain to filtered out all the consumed lot.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Please add more info.

**Comment by digitalsatori** [comment]
Sorry @Yenthe666 , this issue was generated by mistake. (I don't even know when did I create it)
I updated info anyway, would you mind to re-open it, thank you!

**Comment by sle-odoo** [comment]
This is the intended behaviour, we don't want to block the user.
