### ISSUE TITLE
User invitation URL returns 404 error

### ISSUE THREAD

**Issue by lesterhv** [odoo/odoo#4563]
1. Create a new user
2. Generate and send an invitation
3. Verify the URL works by clicking on it.
4. Copy URL to clipboard
5. Log out of browser, clear cache to simulate browser which has never logged into odoo 
6. Load URL - URL goes 404

odoo-server.log step 3
2015-01-06 19:49:41,216 49987 INFO MTI werkzeug: 192.168.111.189 - - [06/Jan/2015 19:49:41] "GET /web/reset_password?token=W6axQqJdyscOG18bsuL3&db=MTI HTTP/1.1" 200 -

odoo-server log step 6
2015-01-06 19:51:27,470 49987 INFO None werkzeug: 192.168.111.189 - - [06/Jan/2015 19:51:27] "GET /web/reset_password?token=W6axQqJdyscOG18bsuL3&db=MTI HTTP/1.1" 404 -
2015-01-06 19:51:27,555 49987 INFO None werkzeug: 192.168.111.189 - - [06/Jan/2015 19:51:27] "GET /favicon.ico HTTP/1.1" 404 -
2015-01-06 19:51:27,568 49987 INFO None werkzeug: 192.168.111.189 - - [06/Jan/2015 19:51:27] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by lesterhv** [comment]
This seems to be an issue when multiple databases are in use - see
https://www.odoo.com/forum/help-1/question/new-users-cannot-accept-invitation-to-create-password-65943

**Comment by Yenthe666** [comment]
This is indeed because of your multi-db and this is something Odoo has to fix urgently. 
Websites, mass mailing and invitation URL's will not work with multiple databases.
@lesterhv if you really need this working you can use the -d databaseName parameter on boot. Note that only one database is available then though..

**Comment by sle-odoo** [comment]
Hi,
Please refer to our [documentation about deploying odoo](https://www.odoo.com/documentation/8.0/setup/deploy.html#dbfilter).
A db-filter is mandatory with multiple databases setup, it's not a bug and concerning 8.0 it will stay as it.

Regards

**Comment by Yenthe666** [comment]
@sle-odoo could you please tell me why this logic was made? 
Why would you make a ERP that has the ability to have multiple databases but doing so will break all mass mailing etc. Is there a reasoning for this? Will there be a fully working V9 with multi-db for mail campagnes etc too?

**Comment by mart-e** [comment]
@Yenthe666 odoo *does* support multiple databases but if you are doing so, **have to** use a db-filter. It's just an extra configuration step. On our saas we have many databases on the same server and customers can use mass mailing because we have configured a db-filter.

**Comment by Yenthe666** [comment]
@mart-e I see. You do mean -d databaseName for the db-filter then right? And with this logic I couldn't have two databases that are able to run mass mailing, right?

P.S: Sorry for posting these question on this but there are barely any details about this subject available.

**Comment by mart-e** [comment]
No I mean the option [`--db-filter`](https://www.odoo.com/documentation/8.0/reference/cmdline.html#cmdoption-odoo.py--db-filter).
The idea is to use a domain-based filter so that, we know that a mass-mailing linked to foo.odoo.com does not use the same db as the one linked to bar.odoo.com. You can have both databases running massmailing at the same time.
With a quick search, you should find some examples of configuration.

**Comment by Yenthe666** [comment]
Hmm I wasn't aware of this option. Quite strange because we had contact with Odoo support (two different people) and they both didn't know how to fix these issues...
Alright thank you for the info @mart-e!

**Comment by lesterhv** [comment]
I guess my issue is one of documentation then.  Odoo is very intuitive and almost self documenting.  Create websites by drag and drop - it is a perfect solution for small, not tech savvy operations.  

So when users see the link for manage databases, and the ability to create new ones, they think - perfect!  Now I can create a new database with fake data and do testing or training.  So they add another database without knowing that it will break existing functionality - all without any warnings - even in the logs.

Having an obscure webpage that identifies a workaround doesn't remove the fact that someone using the product in an intuitive way is going to run into problems.  Now I wonder if using other intuitive features such as adding a quote section to a webpage is going to break something in the accounting module...  ...I'm sure there would be a page about it somewhere.

At the very least there should be a warning pop up when adding an additional database.
