### ISSUE TITLE
undocumented home-calling/information sharing

### ISSUE THREAD

**Issue by fr3aker** [odoo/odoo#45644]
Impacted versions:
12.0, probably others

Steps to reproduce:
install self-hosted odoo with `mail` module

Current behavior:
odoo is sending usage statistics unencryptedly to `http://services.openerp.com/`. Collection of usage statistics and how they are processed is not documented on https://www.odoo.com/privacy and active by default. It is submitted once per day in the automatically created cron job "Mail: Notify channel moderators". This is a breach of privacy.

code in question:
https://github.com/odoo/odoo/blob/12.0/addons/mail/models/update.py
https://github.com/odoo/odoo/blob/f080964694c01a79c52e05c0ceb42c18d4c77df5/odoo/tools/config.py#L81

Expected behavior:
Collection of usage statistics **must** be documented and **must** be possible to easily disable, especially for non-enterprise versions of odoo.

**Comment by Yenthe666** [comment]
Actually, @sswapnesh has reported this before too. @sswapnesh can you link your topic again? Github search seems to filter stuff again.

**Comment by sswapnesh** [comment]
https://github.com/odoo/odoo/issues/27469 (I had to search on Google to find this, Github search sucks)

and _[here is the link about that `hidden` cron job](https://twitter.com/Ajepebabatope/status/1229672744725417984)_

**Comment by fr3aker** [comment]
Thanks for linking that issue and the dubious find in that twitter post, @sswapnesh. In that context I'd just like to mention that this "feature" here is completely unrelated to IAP.

**Comment by sswapnesh** [comment]
@fr3aker  I haven't read your Issue but just added Related link.
I think its good to have opinion from @odony

**Comment by Yenthe666** [comment]
@odony this might be for your interest. It has been reported before but as you notice quite some people are not happy about it and the ethics behind it are debatable. Any changes planned for this? I still think we should have cleaner opt-out options or better info about it. It feels masked on purpose now to me.

**Comment by sswapnesh** [comment]
> It feels masked on purpose now to me.

Especially after looking at the commit https://github.com/odoo/odoo/commit/192c56b48a0f333897c23c684d327c6cd43d9c50

**Comment by mart-e** [comment]
Hi,

The update notification ping do not contain personal information (it contains business information, like company name) so are not covered in our privacy policy.
They are used for all subscription contracts but if you don't have any, there is no issue to disable them (if you have a contract, it's a requirement however).

**Comment by fr3aker** [comment]
Sorry if I used the wrong legal term when using the word "privacy". I'm neither a native English speaker nor a lawyer. Would it be more fitting to say odoo secretly exfiltrates business sensitive information?

You say there is "no issue to disable them", but how would anyone know to disable them if they are not documented and, as pointed out by @sswapnesh, even hidden from the user's eye? You can only find this "feature" by accident (in my case monitoring the network traffic) and even then it's not clear how to disable it.

**Comment by mart-e** [comment]
> Would it be more fitting to say odoo secretly exfiltrates business sensitive information?

Not exactly, this is not secret, nor sensitive business information. The code is open source, you can verify exactly what is sent. We don't offer an easy "click here to disable" (you need to have technical knowledge to do so, that's true) but if you worry with this information, there are some community module to disable it or disabling the cron record works too.

**Comment by fr3aker** [comment]
> Not exactly, this is not secret, nor sensitive business information.

I don't agree with this assessment. Especially the number of total and active users (which may well be very close to customer counts) is usually data a company would not share, thus sensitive. Disclosing the installed modules can be used to gain a good idea about what a company does and what internal structures and workflow they have (especially with more narrow third-party modules). Tracking the url of the odoo instance can leak information about rebrandings or similar organisational incidents that may not be intended to be public knowledge.

This all tied to the unique database identifier and other information to allow easy identification of individual odoo instances and recorded at regular intervals can leak a lot of sensitive business information. And there are probably much more possible unwanted disclosures than the few cases I just described.

**Comment by Yenthe666** [comment]
Well Odoo needs to ping and needs to verify data for the enterprise licenses though. This includes checking the amount of users and apps. I'd say Odoo has no business with `nbr_share_users` and `nbr_active_share_users` though as there is no reason for them needing it, that is just for internal statistics and metrics. All the rest can be connected to legit usecases in my opinion.
