### ISSUE TITLE
stock_account: Returning merchandise to Supplier uses First Value Available

### ISSUE THREAD

**Issue by hbto** [odoo/odoo#45671]
# Main
Returning merchandise to Supplier uses First Value Available and not the value itself of the merchandise being returned this leads to incorrect values in the accounting valuation (and to incurring in a huge difference in the COGS).

# Current Situation
## Create a Product
- set Costing Method: FIFO.
- set Valuation to Automatic.

## Make Purchase to Supplier A
- Make a Purchase Order to Supplier A. 
- set price_unit 100
- set qty to 10 (ten)

##  Merchandise Receipt
- receipt merchandise, and
- check accounting entries

|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 1000 ||
|Stock In| 0 |1000|

## Check the Accounting valuation
|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 1000 ||
|**Total Inventory**|**1000**||

## Accrue Supplier A Bill

|account| debit | credit|
|-|-:|-:|
|Stock In| 1000 ||
|AP|  |1000|

## Make Purchase to Supplier B
- Make a Purchase Order to Supplier A. 
- set price_unit 500
- set qty to 1 (one)

##  Merchandise Receipt
- receipt merchandise, and
- check accounting entries

|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 500 ||
|Stock In|  |500|

## Check the Accounting valuation
|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 1000 ||
|Inventory Valuation| 500 ||
|**Total Inventory**|**1500**||

## Accrue Supplier B Bill

|account| debit | credit|
|-|-:|-:|
|Stock In| 500 ||
|AP|  |500|

## Return Merchandise to Supplier B
- From Purchase Order to Supplier B check on the pickings a make full return of the merchandise.
- check accounting entries

|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 100 ||
|Stock In| |100|

## Check the Accounting valuation
|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 1000 ||
|Inventory Valuation| 500 ||
|Inventory Valuation||100|
|**Total Inventory**|**1400**||

# Expected Behavior

## Return Merchandise to Supplier B
- From Purchase Order to Supplier B check on the pickings a make full return of the merchandise.
- check accounting entries

|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 500 ||
|Stock In| |500|

## Check the Accounting valuation
|account| debit | credit|
|-|-:|-:|
|Inventory Valuation| 1000 ||
|Inventory Valuation| 500 ||
|Inventory Valuation||500|
|**Total Inventory**|**1000**||

# OPW
2199454

**Comment by sle-odoo** [comment]
This is the intended behavior.
