### ISSUE TITLE
In Odoo Help Forum: cannot validate a flagged question

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#45674]
Happening since the upgrade on Sunday.

One question is flagged (incorrectly, because it's a good question with a good answer).  It seems not possible to validate it (i.e. remove the flag):

![image](https://user-images.githubusercontent.com/38899643/74791505-892b4180-52f5-11ea-951e-6abf265556fa.png)

https://www.odoo.com/forum/help-1/question/production-stop-or-hold-by-product-or-bom-164753#answer-164756

Will someone review all these problems with the Help forum?

**Comment by Yenthe666** [comment]
@ctringham there are like a dozen more issues. I've got a tonload of bug reports open under my enterprise contract too. It usually takes them four to 8 weeks to get stuff back going honestly.

**Comment by JKE-be** [comment]
probably fixed meanwhile, please open new issue / or reopen this one if still existing !
