### ISSUE TITLE
[12] Invalid VAT Number 

### ISSUE THREAD

**Issue by gityopie** [odoo/odoo#45691]
Impacted versions:
12.0

Steps to reproduce:
1. Enable setting "Verify VAT Numbers" on Settings > Accounting
2. Create new contact with the following data:
Name: Any name
Country: France
VAT number: FR82246200638

Current behavior:
Any time create new contact using the data above, the VAT number validation always failing. 

Expected behavior:
I can create new contact using VAT number above without any error.

Video/Screenshot link (optional):

Additional note:
We have a customer from France and they gave us this SIRET number 24620063800145 and then we used this website http://www.ebsoft.org/mambo/ressources/clefs.htm and this https://www.l-expert-comptable.com/calculateurs/trouver-le-numero-de-tva-intracommunautaire-partir-de-votre-numero-de-siren.html to generate VAT number (both website generate the same VAT number).
After checked the generated VAT number on this website http://ec.europa.eu/taxation_customs/vies/ it is detected as invalid number.
I'm not sure if this issue from Odoo side but any help or comment will be very helpful for us.
Thank you!

**Comment by Yenthe666** [comment]
@nim-odoo and @jhk-odoo this is yet another report of VAT number issues. Maybe worth a check too?

**Comment by jhk-odoo** [comment]
Hello, 
your siret number looks valid (I checked on INSEE search) 
but if vies indicates your VAT number as invalid then you need to check with your fiscal administration for any issue.
This specific case is not related with odoo, we mostly rely on vies for our internal checks anyways.

Regards.

**Comment by Yenthe666** [comment]
Oops I read it as "is detected as valid". Indeed if its invalid in VIES then Odoo will fail too.

**Comment by gityopie** [comment]
Thank you @jhk-odoo for the feedback and @Yenthe666 for follow this up
