### ISSUE TITLE
Emailing invoice from POS payment screen sends receipt instead

### ISSUE THREAD

**Issue by Roro148** [odoo/odoo#45729]
Impacted versions: Odoo 13.0+e-20200127

Steps to reproduce: Finish payment and try to send invoice to customer directly from payment screen in POS

Current behavior: Sends a customer receipt via email to the customer

Expected behavior: sends a customer invoice via email to the customer

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@pimodoo one more for you ;)

**Comment by pimodoo** [comment]
@Roro148 Hello,

Could you confirm me that you have you code, up to dat, I've just tested on the runbt, and when I thick "invoice", the mail contains both the receipt and the invoice.

See attached screenshot
![Receipt Order 00002-001-0002 - Odoo](https://user-images.githubusercontent.com/20767708/74934686-0e425380-53e7-11ea-8a16-38c1760ed27b.png)

**Comment by Roro148** [comment]
Hi,

You’re right. It now works.



Van: pimodoo <notifications@github.com>
Verzonden: donderdag 20 februari 2020 13:44
Aan: odoo/odoo <odoo@noreply.github.com>
CC: Ronald | SlendersBeauty <ronald@slendersbeauty.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [odoo/odoo] Emailing invoice from POS payment screen sends receipt instead (#45729)


@Roro148<https://github.com/Roro148> Hello,

Could you confirm me that you have you code, up to dat, I've just tested on the runbt, and when I thick "invoice", the mail contains both the receipt and the invoice.

See attached screenshot
[Receipt Order 00002-001-0002 - Odoo]<https://user-images.githubusercontent.com/20767708/74934686-0e425380-53e7-11ea-8a16-38c1760ed27b.png>
