### ISSUE TITLE
[13.0][BUG] journal entries / items can - mixed companies

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#45728]
Impacted versions:
13.0

Steps to reproduce:
* go into demo.odoo.com
* enable my company + demo company for the user
* create a journal entry with items

Current behavior:
* you can create a journal entry for "my company" with accounts / taxes of "demo company"

Expected behavior:
* do not allow to use accounts / taxes of different companies on a journal entry

Video/Screenshot link (optional):
https://drive.google.com/file/d/1zY6P-EYtmNhUokeKAKFhEM9RoVJojzBF/view

OPW: #2200066

**Comment by pedrobaeza** [comment]
Is this something of demo data only or a general multi-company boundaries problem?

**Comment by jjscarafia** [comment]
General multi-company problem. There is no constraint and domain to enforce same company. I believe that it could be fixed with the new "_check_company_auto" y "check_company=True" functionality

**Comment by jjscarafia** [comment]
Fixed on master. Odoo tells it won't be improved on v13
