### ISSUE TITLE
sale_stock view replaces product_id field instead of using position="attributes", breaking inheritance.

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#4573]
I spent a lot of time trying to add a domain to the `product_id` field in the view of the `sale.order.line` model.
I was inheriting `sale.view_order_form` and using an xpath like

```
<xpath expr="//tree/field[@name='product_id']" position="attributes">
    <attribute name="domain">my_domain</attribute>
</xpath>
```

But it didn't work. After some debugging, I've found out that's because [sale_stock **replaces** the product_id field](https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock_view.xml#L32) instead of editing its attributes, which destroys all changes done to `product_id` by other modules that inherit `sale.view_order_form`.

**Comment by rvalyi** [comment]
+1 for using attributes instead of replace here

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
