### ISSUE TITLE
No way to edit domain with onchange based on a related model (one2many, many2one) field

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#4574]
To better illustrate the problem, here's the concrete example I'm working on:
I've added a selection field to products for their shelf life (short, long, maybe others in
the future) and a similar selection field to sale order (goods_type:
fresh, dry, mixed, maybe others in the future).

I want the domain of the product_id field of the order lines to change
according to selected goods_type of the sale order:
- `fresh -> [('shelf_life', '=', 'short')]`
- `dry -> [('shelf_life', '=', 'long')]`
- `mixed -> []`

I tried "both ways": (`_get_domain()` here is just a placeholder here for the logic that gets that correct domain according to the sale order `goods_type`)
the onchange on the sale order model that tries to change the domain of its order lines:

```
@api.onchange('goods_type')
def onchange_order_goods_type(self):
    return {
        'domain': {
            'order_line.product_id': [('shelf_life', '=', _get_domain())]
        }
    }
```

Which doesn't give any error but doesn't work, and the "inverse" way:
onchange on the sale.order.line model triggered by a change on the related sale.order:

```
@api.onchange('order_id.goods_type')
def onchange_order_goods_type(self):
    return {
        'domain': {
            'product_id': [('shelf_life', '=', _get_domain())]
        }
    }
```

[Which gives an error on initialization](https://gist.github.com/LeartS/f45a0201039172ef0698)

Is there a way to change the domain of a field of model B when a field of model A is changed? cc @rco-odoo @odony

**Comment by maljac** [comment]
+1

**Comment by oerp-odoo** [comment]
Would like to know this too

**Comment by Frei7777** [comment]
Hi, still no solution? I tried almost everything

**Comment by oerp-odoo** [comment]
Well for example, I'm using this onchange domain and it is working:
```python
    @api.onchange('use_insurance')
    def onchange_use_insurance(self):
        res = {}
        if self.use_insurance:
            res['domain'] = {'partner_id': [('policyholder', '=', True)]}
        else:
            res['domain'] = {'partner_id': []}
        return res
```

**Comment by Frei7777** [comment]
Thanks for the answer, but I solved it in definition of a filtered field using var `parent` instead of `order_id`. 

```python
class sale_order_line(models.Model):
    _name = "sale.order.line"
    _inherit = "sale.order.line"
    product_id = fields.Many2one('product.product', 'Product',
                                 domain="[('product_tmpl_id.product','=',parent.product)]",
                                 change_default=True, readonly=True,
                                 states={'draft': [('readonly', False)]},
                                 ondelete='restrict')
```

It was the last shot but it worked, but still don't know why it doesn't worked with `order_id`, which should be pointing on the same object like `parent`.

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by brainafesoh** [comment]
Hi guys, I have the same difficulty. I'm using odoo 12. Any solutions yet @Yenthe666 ?

**Comment by cmeravi** [comment]
+1

**Comment by Yenthe666** [comment]
Can you guys create a new report based on V12 please? :)
