### ISSUE TITLE
[13.0] sale_expense: Quantity of Report is not added to Sale Order Line

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45747]
Impacted versions: 13.0

Steps to reproduce: 
Create Expense Report 
![screenshot-localhost_8069-2020 02 17-16_44_53](https://user-images.githubusercontent.com/16624719/74649058-da77eb80-51a4-11ea-9e6b-44ab3c0dc7d1.png)

Select SO in Reinvoice Customer
![screenshot-localhost_8069-2020 02 17-16_45_48](https://user-images.githubusercontent.com/16624719/74649117-fb404100-51a4-11ea-9d81-b82fe83909d1.png)

Create Report --> Confirm --> Submit--> Approve and Post Entries

Current behavior:
0 Qty on SO
![screenshot-localhost_8069-2020 02 17-16_45_15](https://user-images.githubusercontent.com/16624719/74649093-eb286180-51a4-11ea-9802-38757e2c8f08.png)

Expected behavior: Set Quantity

Video/Screenshot link (optional):

Ps: Not sure If This is Functionally correct as its setting Delivered Qty.

**Comment by pedrobaeza** [comment]
You are not using the functionality correctly, as the invoice policy should be to re-invoice expenses, and the SO line must be added automatically.

Closing then.

**Comment by sswapnesh** [comment]
> the SO line must be added automatically

Yes, It was added automatically on the Confirming Expense report.
So IMO that quantity should be reflected here.
