### ISSUE TITLE
[13.0] hr_expense: Re-Invoice Expenses of product is not considered

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45748]
Impacted versions: 13.0

Steps to reproduce:
- Create Expense Product
- Set Sale/Cost Price
![screenshot-localhost_8069-2020 02 17-15_46_59](https://user-images.githubusercontent.com/16624719/74644759-cb8d3b00-519c-11ea-937d-a292dd4f8fb3.png)
- Re-Invoice Expenses  --> Sales price
![screenshot-localhost_8069-2020 02 17-15_52_28](https://user-images.githubusercontent.com/16624719/74645265-96cdb380-519d-11ea-8abe-313be60cfc6f.png)

Current behavior:
On adding new Expense Report, Unit Price is wrong

![screenshot-localhost_8069-2020 02 17-16_13_09](https://user-images.githubusercontent.com/16624719/74646752-718e7480-51a0-11ea-8fea-d7e9697dfc88.png)

Expected behavior: It should be Sales price 800.00)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Re-invoice policy is not for that, but for adding the line of the expense in the sales order.

Closing as no real issue.

**Comment by sswapnesh** [comment]
You are Right :+1: 
Thanks.
