### ISSUE TITLE
 Shipping costs problem at checkout

### ISSUE THREAD

**Issue by hansw1** [odoo/odoo#4576]
I have my webshop set up with Odoo 8.0 online version. I have a problem with setting up my shipment costs at the check out page.
I made a delivery pricelist: orders below €50 --> €6.95 shipping costs order above €50 --> €0 shipping costs.
At the checkout page you have 4 main blocks (review order / shipping & blling / payment / confirmation). When a client is choosing from the first time the correct quantity there is no problem. The problem is that when a customer is adjusting quantities in block "review order" the shipping costs don't follow the new order value. Odoo does not adjust the shipping costs directly and that is very confusing for customers. 

Has anybody got a solution?

**Comment by ddfs** [comment]
this is different than mine. i am trying to adjust free shipping for a product but no success. 
and still checking it if anyone did or a solution exists for that.

**Comment by Yenthe666** [comment]
Hi @hansw1 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
