### ISSUE TITLE
Customer KanBan view shows unconfirmed quotes as sales.

### ISSUE THREAD

**Issue by eaddison** [odoo/odoo#458]
The customer KanBan view will include unconfirmed quotes in the number of sales displayed next to customer icon. I have included two screen shots, the KanBan view and a list view of the customer data to confirm the number of sales in KanBan is incorrect.

![kanban_bug](https://cloud.githubusercontent.com/assets/665966/3233244/385cdf80-f0bc-11e3-808b-eee010b92a63.png)
![list of customer quotes and sales](https://cloud.githubusercontent.com/assets/665966/3233243/385ca1c8-f0bc-11e3-9bf6-01ddca4543e1.png)

**Comment by Yenthe666** [comment]
Hi @eaddison,

Thank you for your report but this is expected behaviour. This makes it very easy to find all sale related items, even if they're still in quotation / draft state.

Regards,
Yenthe
