### ISSUE TITLE
[8.0][issue][Timesheet] Timesheet Task doesn't update project overview (0/X hours)

### ISSUE THREAD

**Issue by miscs** [odoo/odoo#4581]
**Timesheet Task doesn't update project overview (0/X hours)**

Impacted versions:

 - 8.0 and above (not checked with lower versions)

Steps to reproduce:

1) Create a fresh project
2) Create a Task for this Projekt with "estimated hours" = 10
3) Log time on this project via "My current timesheet" (e.g. 5 hours)
4) Return to Project overview -> It shows ("hourglass" 0/10 hours) instead of ("hourglass" 5/10 hours). The task itself is correctly updated.

Current behavior:

 - Project shows ("hourglass" 0/10 hours") which is incorrect

Expected behavior:

 - Project shows ("hourglass" 5/10 hours") 

It´s not a big thing (only a refresh-problem) but I first thought the hours were not correctly tracked because I only checked at the project-level.

Thanks!
miscs

**Comment by mart-e** [comment]
Hello,

Indeed the time displayed on the project is based on the worklog on the tasks, not the timesheets, it's just two different concepts.
However we are working to unify the work log and timesheet to make it work in your scenario. Current work is at #2635
