### ISSUE TITLE
Odoo search and filter not working on models with delegation inheritance

### ISSUE THREAD

**Issue by rumeysayilmaz** [odoo/odoo#45811]
Impacted versions: 12.0 

**Steps to reproduce:** 

1. create a super class model (_name="hr.my.first.super.class") with a dummy field such as **title**.

2. create a sub super class that inherits the super class created in step 1 (delegation inheritance=true on the model named, _name="hr.my.first.sub.class"), 
3. create another model named (_name="hr.sub.class.of.my.first.sub.class") with a delegation inheritance on "hr.first.sub.class" created in step 2.  
4. create another model named (_name="hr.sub.of.sub.class.of.my.first.sub.class") with a delegation inheritance on "hr.sub.class.of.my.first.sub.class created in step 3.  
5. Create a dummy view such as tree view with a search filter on the model created in step 4 (i.e. "hr.sub.of.sub.class.of.my.first.sub.class")
6. On the search area, create a custom filter to filter **title** from the model created in step 1.

**Current behavior:** After clicking on filter,an error is produced as shown below. The length of the model names grow up through chaining in the sql query made by odoo search. There has been no mention of model name length constraint on odoo developer v12 documentation on the odoo website.

> SELECT "hr_sub_of_sub_class_of_my_first_sub_class".id FROM "hr_my_first_sub_class" as "hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id","hr_my_first_super_class" as "hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id__hr_m_2dc3b677","hr_sub_class_of_my_first_sub_class" as "hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id","hr_sub_of_sub_class_of_my_first_sub_class" WHERE ("hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id"."hr_my_first_sub_class_id"="hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id"."id" AND "hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id"."hr_my_first_super_class_id"="hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id__hr_my_first_super_class_id"."id" AND "hr_sub_of_sub_class_of_my_first_sub_class"."hr_sub_class_of_my_first_sub_class_id"="hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id"."id") AND ("hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id__hr_m_2dc3b677"."title" = %s) AND TRUE ORDER BY "hr_sub_of_sub_class_of_my_first_sub_class"."id" limit 80

> psycopg2.ProgrammingError: missing FROM-clause entry for table "hr_sub_of_sub_class_of_my_first_sub_class__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id__hr_my_first_"
> LINE 1: ...__hr_sub_class_of_my_first_sub_class_id__hr_my_first_sub_class_id"."hr_my_first_super_class_id"="hr_sub_of...

**Expected behavior:** The filtering should bring the title matching the case from the respective model. The length of the model names should not constrain the working of an sql query made through the ORM structure of odoo.

**Comment by pedrobaeza** [comment]
Well, the limitation is AFAIK in the PostgreSQL part. You can change the table name through `_table` variable, so this case is covered, and so, it's not a problem itself, and thus I'm closing.

Of course this extreme case can be documented anywhere, but there are so many extreme cases that can happen if you force the ORM, that are impossible to be covered. If you are interested in reflecting this one on the documentation, please do a PR improving it with the case.

**Comment by rumeysayilmaz** [comment]
Thank you very much @pedrobaeza for giving the idea of using  __table_. The ORM layer was aliasing the table names by the model name and hence creating a very long alias name that exceeds the 63 byte size limitation of postgresql. Defining the _table for the models (SQL table name used by model) has resolved the creation of such long aliases, and hence the truncation problem resulting in failure of the sql query.
