### ISSUE TITLE
Purchase requisitions list products that are not flagged as 'Can be purchased'

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#4582]
Hi,

Currently at the time of creating a purchase requisitions the user will be able to list products that are not flagged as 'Can be purchased'. This behaviour is inconsistent with that of the purchase orders, where the field 'product_id' in object 'purchase.order.line' contains as domain 'purchase_ok = True'.

Regards,
Jordi Ballester

**Comment by rvalyi** [comment]
:+1: for the request
