### ISSUE TITLE
[8.0][issue][mail] Mail alias is not being created when create a new user

### ISSUE THREAD

**Issue by JoaoPauloSouza** [odoo/odoo#4583]
seems like when i create a new user the mail aliases not being created

![issue](https://cloud.githubusercontent.com/assets/5462568/5652927/b9063aa6-969c-11e4-9b66-187dcc786b96.png)

**Comment by mart-e** [comment]
Hello,

Yes we no longer create aliases for users because it was not very useful to have that by default (but you can still do it manually)

**Comment by JoaoPauloSouza** [comment]
then how i receive mails in a specific inbox without this feature?

**Comment by mart-e** [comment]
you can still modify the existing alias to specify the alias of your choice and make it active
