### ISSUE TITLE
[WISHLIST] pos_restaurant should handle table asignment

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#4584]
Take this issue as a wishlist or feature request, as I hear it everytime I talk to someone in restaurant/bar/hotel business:
pos_restaurant should handle table asignment

I mean, you should note that 3 Pepsi + 2 teas goes for "table 5", then 2 black coffees + 1 doughnut to "table 2", etc. It is a must for such businesses.

Also be able to split the bill as people often want to pay only what they have consumed, not the whole lot.

**Comment by mart-e** [comment]
Hello,

This is possible in the pos_restaurant module (in master, not sure for version 8).
You need to create a floor plan linked to your session and then you will be able to add orders to specific table and then switch from tables.
Splitting bills is also possible with an option in the configuration of your point of sale.

**Comment by jholze** [comment]
@mart-e i tested it on current master and it does not seem to run, because the assigned floor plan is nor loaded. Also the floor plan manager within the POS App is gone :(
