### ISSUE TITLE
[13.0] social media: posts are reposted on social media in case of concurrent update

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#45846]
Impacted versions: 13.0

Steps to reproduce:
Hard to say but in some cases the social media app creates a concurrent update:
```
2020-02-20 15:35:44,912 24634 ERROR production odoo.addons.base.models.ir_cron: Call from cron Social: Publish Scheduled Posts for server action #646 failed in Job #29 
2020-02-20 15:42:10,350 24627 ERROR production odoo.sql_db: bad query: UPDATE "social_account" SET "write_uid"=2,"write_date"=(now() at time zone 'UTC') WHERE id IN (2)
ERROR: could not serialize access due to concurrent update
```
When this happens Odoo has already pushed out the content to the remote platforms though, causing content being reposted over and over again as it keeps failing at the Odoo side but not the social media side.

Example when manually executing the cron job:
![image](https://user-images.githubusercontent.com/6352350/74952901-39d23780-5401-11ea-9c7f-cbe1514eb0c7.png)

On Facebook the post is posted:
![image](https://user-images.githubusercontent.com/6352350/74953492-017f2900-5402-11ea-98ad-bbc53e914989.png)

Odoo still says the post is scheduled (because of the concurrency update):
![image](https://user-images.githubusercontent.com/6352350/74953192-a5b4a000-5401-11ea-9589-e3729c59d954.png)

Current behavior:
When there is a concurrency the state of the social media post is not updated in Odoo but the post is made on social media

Expected behavior:
Either the social media post its state is first updated, then pushed to social media or there is some fallback or try/catch logic for this

**Comment by Yenthe666** [comment]
OPW `2201233`

**Comment by chrisfoose** [comment]
Can I try and help with this?

**Comment by Yenthe666** [comment]
@chrisfoose thanks but you'd need acces to the enterprise repository which you most likely don't have? Odoo is already testing and writing fixes though.

**Comment by Yenthe666** [comment]
This was solved :)
