### ISSUE TITLE
[12.0] [13.0] Unable to translate Name of an account

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#45847]
Impacted versions:
[12.0] [13.0] 

Steps to reproduce:
Install multiple languages and switch to another language.
Go to Accounting > Configuration > Chart of Accounts. You will see that the language icon is not visible for translation. That used to work in V11.
![image](https://user-images.githubusercontent.com/30628967/74954118-e95bd980-5402-11ea-8f6d-aca965790311.png)

Current behavior:
Unable to translate name of account in chart of account

Expected behavior:
See above

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Install https://github.com/odoo/odoo/tree/13.0/addons/l10n_multilang for that.

**Comment by Yenthe666** [comment]
@yung-wang it works just fine? See the screenshot:
![image](https://user-images.githubusercontent.com/6352350/74955280-b61a4a00-5404-11ea-98bd-9b7b4c04d7bd.png)

**Comment by yung-wang** [comment]
thanx, my mistake. It was indeed the missing module.
