### ISSUE TITLE
[12.0][BUG] account : when you send a credit note in the mail it is write invoice

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#45864]
Impacted versions:
12.0 (and maybe other)

Steps to reproduce:
Go to runbot
Create a creadit note
Validate
Send and Print

Issue in the body of the mail it is write 'invoice' indead 'creadit note'.
![image](https://user-images.githubusercontent.com/16716992/74960316-6c356200-540c-11ea-9253-e2e4060748a4.png)

**Comment by fmdl** [comment]
opw #2201312

**Comment by pedrobaeza** [comment]
Any news from OPW team?

**Comment by Yenthe666** [comment]
It might be there is still no feedback, the ticketing system seems to be swamped lately. I have a lot of open tickets that are 2-5 weeks old too.

**Comment by fmdl** [comment]
Response of OPW : duplicate the template dans change "invoice" to "credit note"

**Comment by Yenthe666** [comment]
I guess we can close it then even though its rather a workaround then a solution.
