### ISSUE TITLE
[13.0] POS multi-currency, Feature is missing

### ISSUE THREAD

**Issue by alyngsoe** [odoo/odoo#45889]
Impacted versions:
v13e online

Steps to reproduce:
Setup two POS payment method
1: base currency
2: foreign currency

Current behavior:
In a pos session, when using the payment method with the foreign currency, the amount is not recalculated to show the amount to pay in foreign currency

Expected behavior:
The amount should be recalculated to handle payment with the foreign currency

This is a very basic functionality of a pos system, and i wonder why this is not possible in Odoo standard - maybe we have overlooked something ? ( i can find extra modules for this feature, but we are going fo odoo-online/saas for smaller customers. )

**Comment by chrisfoose** [comment]
I'd like to help

**Comment by pimodoo** [comment]
@alyngsoe Hello, the multi-currency is not available in POS for now, we already have it in our feedback, but nothing planned for now.

@lap-odoo FYI

**Comment by Yenthe666** [comment]
Closing as there is already a feedback (which means an internal task)
