### ISSUE TITLE
[13] widget="monetary" doesn't work on calendar view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45881]
Impacted versions: 13.0

Steps to reproduce: Open Calendar view of  Sales order (or Purchase Order)

Current behavior:
https://github.com/odoo/odoo/blob/045dad7bdb3dbd8444a8b9ee363fd6314fb1b851/addons/sale/views/sale_views.xml#L119
Currency symbol is not there
![screenshot-1209369-13-0-0347a2 runbot13 odoo com-2020 02 12-14_52_34](https://user-images.githubusercontent.com/16624719/74320896-6fdf3e00-4da7-11ea-8b10-b6a41c7823c7.png)

Expected behavior: Display Currency symbol

![screenshot-1209369-13-0-0347a2 runbot13 odoo com-2020 02 12-14_53_59](https://user-images.githubusercontent.com/16624719/74320970-8a191c00-4da7-11ea-8542-ae3cb174f2d6.png)
(I have added <field name="currency_id"/> there to make it work )
Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
OPW 2214445

**Comment by mhabboush97** [comment]
just a note that this issue happens on Odoo 14 and not yet fixed

**Comment by mhabboush97** [comment]
@Yenthe666 just a note that this issue happens on Odoo 14 and not yet fixed

**Comment by Yenthe666** [comment]
@jvnm-odoo @nle-odoo could you guys check if this still needs a forward into 14.0 please?

**Comment by nle-odoo** [comment]
this fix is in master (that became 14.0)

this should fix the new issue in 14.0: https://github.com/odoo/odoo/pull/65451
