### ISSUE TITLE
[13] event:Traceback on Moving Event from Kanban

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#45882]
Impacted versions: 13

Steps to reproduce: Group Kanban by Responsible -> Move Record
![image](https://user-images.githubusercontent.com/16624719/74974062-93128900-544a-11ea-8279-d571b8d1cb80.png)

Current behavior: 
![image](https://user-images.githubusercontent.com/16624719/74974083-99086a00-544a-11ea-9d11-16bc962fa4c4.png)

Expected behavior:
Move record to another column
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Closing as there's linked PR.
