### ISSUE TITLE
[13.0] oldname is deprecated

### ISSUE THREAD

**Issue by kenneth-vkd** [odoo/odoo#45893]
Impacted versions:
13.0

When deploying custom modules on Odoo 13.0, we have noticed lines in the logfile telling us that usage of the oldname attribute is deprecated and that an upgrade/migration script should be used instead.
There is however no documentation available on how to implement such script.
Are there any plans to update the documentation to include the missing information or are there any official odoo modules currently using such scripts, which we can use for reference?

**Comment by pedrobaeza** [comment]
There's no information about that because:

1. It's only needed when switching the name.
2. It depends on the way you want to do it and what involves.

For example, in community we use openupgradelib and use the method `rename_fields`.

Closing this as no issue, but question.

**Comment by mjrk** [comment]
If somebody needs to do a quick rename for an instance he has control over:

You can simulate the oldname behavior easily with a computed stored new field, that sets the value (if empty) to the old one. After you upgraded the module and the migration is done, in a second step, you can remove the compute method and the old field.

This is done in few minutes and the compute methods provides more control. oldname keywords tended to be kept forever. Thus, understandable that oldname was deprecated.
