### ISSUE TITLE
[8.0,master]Field 'Reference:' is not included for translations

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4589]
**Reference field on report is nowhere included for translations**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. create a new order and then make an invoice from the order.
 2. print it out in english
 3. Install a second language and give the customer this language.
 4. Make a second order and then make an invoice from the order.

Current behavior:

 - Prints out 'Reference:' in every language on invoice reports.
<img src="http://i.imgur.com/VSwUP5G.png" />

Expected behavior:

 - The field 'Reference:' should be added so it is translatable and is taken up in the .po files.
The field is only added in the QWeb report (through) xml and there is nothing provided for translations in any languages. The 'Reference:' is nowhere to be found on https://translations.launchpad.net/openobject-addons/8.0/ either.

**Comment by intero-chz** [comment]
Hi,

i tried to reproduce it on a runbot server (8.0), but it wasn't possible with german language. Reference was translated to "Beschreibung". The only difference on the report was the position of this field.

**Comment by mart-e** [comment]
Hello,

It's just that this term was added recently in the report so it is not present in the po file.
We will re-export the translations soon so it will be present in po.

**Comment by Yenthe666** [comment]
@intero-chz I just tried it on the runbot on the problem is still there.
Created new german customer:
<img src="http://i.imgur.com/0JQzzou.png"/>
Created an invoice (from a sale order):
<img src="http://i.imgur.com/iq0xJY0.png"/>
The report:
<img src="http://i.imgur.com/WLJFPOP.png"/>

@mart-e even if it is not in the po file... It isn't on https://translations.launchpad.net/openobject-addons/8.0/+lang/nl either, so how will there ever be a translation in the .po file then?

**Comment by mart-e** [comment]
Yes it's neither in po file, not on launchpad **yet**. We will resynchronise the translations soon, it's a task that we do manually from time to time.

If you need a quick fix, you need to manually create an entry in the translated terms (tip: duplicate an existing terms like "Source:/Quelle:" to directly get the correct ids and type).

**Comment by Yenthe666** [comment]
@mart-e the translations will also be added to the languages on launchpad too then? 
So if I understand it correctly it will go like this:
1) Somebody from Odoo will add new words / sentences to translate to launchpad
2) Launchpad users translate the new words / sentences
3) Somebody from Odoo merges them in Odoo

Is there any date on when this will happen? There seem to be quite some more translations with these problems.

**Comment by mart-e** [comment]
yes, that's the process.
No date but it was done in 7.0 yesterday at d0cd92bb9fc106eeff4d6b4820810f2b424c7e18 so shouldn't be long before the same in 8.0.
