### ISSUE TITLE
Contact-Page in German not found

### ISSUE THREAD

**Issue by youngcut** [odoo/odoo#45896]
Impacted versions: 12.0

Steps to reproduce: Create new Website. Got to 'Contact Us'

Current behavior: 404-Page appears

Expected behavior: Contact Us-Page showing up

**Comment by pedrobaeza** [comment]
I doubt this is because German, but a modified instance. Please try on runbot: https://runbot.odoo.com with admin/admin.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
