### ISSUE TITLE
Invalid JSON data

### ISSUE THREAD

**Issue by NirmalaSudhirr** [odoo/odoo#45892]
Hi everyone,

   I am try to get a product list from odoo through postman. I have below code sinnpet

       @http.route( '/api/product.template/', auth='user', methods=['GET'], csrf=False)
        def get_product_template(self, model, **params):
           records = request.env[model].search([])
                if "query" in params:
                 query = params["query"]
               else:
                 query = "{*}"
           record = records.browse(rec_id).ensure_one()
           serializer = Serializer(record, query)
           return http.Response(
                json.dumps(serializer.data),
                status=200,
                mimetype='application/json'
             )

I tried  this url http://domain.com/api/product.template(not passing any body parameters). But I get the below error

2020-02-20 08:39:07,874 8663 INFO testodoo odoo.http: /api/product.template/: Invalid JSON data: '' 2020-02-20 08:39:07,875 8663 INFO testodoo werkzeug: 127.0.0.1 - - [20/Feb/2020 08:39:07] "GET /api/product.template/ HTTP/1.1" 400 -

Can somebody tell me whats wrong with the Api call?

thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Quick tip: Odoo is not a REST API.

Closing this by the reason above.
