### ISSUE TITLE
Invalid JSON data

### ISSUE THREAD

**Issue by NirmalaSudhirr** [odoo/odoo#45894]
Impacted versions:
odoo 11

Steps to reproduce:
1. clone this repo   [https://github.com/yezyilomo/odoo-rest-api](url) in to odoo/addons/
2. Edit the code snippet 
`
          
          @http.route(
              '/api/<string:model>/<int:rec_id>',
              auth='user', methods=['GET'], csrf=False)
             def get_model_rec(self, model, rec_id, **params):
                    records = request.env[model].search([])
                    if "query" in params:
                       query = params["query"]
                   else:
                       query = "{*}"
                   record = records.browse(rec_id).ensure_one()
                  serializer = Serializer(record, query)
                  return http.Response(
                            json.dumps(serializer.data),
                           status=200,
                           mimetype='application/json'
                          )
`
to 
'

           @http.route(
                  '/api/product.template/',
                 auth='user', methods=['GET'], csrf=False)
                 def get_product_template(self, model,  **params):
                       records = request.env[model].search([])
                       if "query" in params:
                           query = params["query"]
                       else:
                           query = "{*}"
                       record = records.browse(rec_id).ensure_one()
                       serializer = Serializer(record, query)
                        return http.Response(
                              json.dumps(serializer.data),
                              status=200,
                              mimetype='application/json'
                    )
`

    Call the above api using Postman 
       http://localhost:8069/api/product.template

Note: before calling the api/product.template you must call the /auth for authentication. I have called the api/product.template without passing any params in the request body.

Current behavior:
    It throws the below error
  

> 2020-02-20 08:39:07,874 8663 INFO testodoo odoo.http: /api/product.template/: Invalid JSON data: '' 2020-02-20 08:39:07,875 8663 INFO testodoo werkzeug: 127.0.0.1 - - [20/Feb/2020 08:39:07] "GET /api/product.template/ HTTP/1.1" 400 - 

Expected behavior:

It should return the list of products from odoo product.template

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Sorry but this is not a default Odoo module but custom app. You should ask the author of that app for support, this is only for issues in the official Odoo (without custom dev)

**Comment by NirmalaSudhirr** [comment]
Hi Yenthe666,
   Thanks for your reply. I am checking with him as well.

**Comment by altanmur** [comment]
Hello NirmalaSudhirr 
Do you solved the problem?

**Comment by foxeslover** [comment]
In the POST request header for /authenticate/ must have Content-Type: application/json and in the GET you must remove the json header so the response will be ok.

**Comment by Habiba-Amroune** [comment]
@foxeslover Thanks a lot, u can't imagine how u saved my day :)
