### ISSUE TITLE
eMail duplicate on mail server

### ISSUE THREAD

**Issue by martinauger03** [odoo/odoo#459]
When OpenERP fetch a user email, it send it back right away on the mail server but with the OpenERP user signature.  So it's not really a duplicate because we can see a different signature and the sender is the identification of the Openerp user...  This is not a protocol problem because it do the same things using IMAP or POP.

The users are confuse because customer (or any body else) send a email in the user email account and the user receive again the same message on the mail server but sent by him self...

Do we do something wrong? or it's a bug!  

![test2-duplicate](https://cloud.githubusercontent.com/assets/1906270/3236636/f362d3e8-f0df-11e3-9273-ae15b2a19efe.png)

Thx for your help!

Martin

**Comment by Sameer1990** [comment]
Is there any way to stop sending email from openerp to my email again ?

**Comment by Yenthe666** [comment]
Dear @martinauger03,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by shurshilov** [comment]
I have this bug in odoo 9. 
1. I'm sending a letter from Google account which has nothing to do with odoo. to another account which is registered as an incoming odoo
2. I get 2 letters. One of my Google account is not associated with odoo directly through the mail. A second notification from odoo from outgoing server odoo. 
P.S.
When I off notification in user/preference it solves the problem. But then I do not get any notifications at all.
