### ISSUE TITLE
How to auto login in Odoo's Web-module for res.user, not for res.partner?

### ISSUE THREAD

**Issue by ganesh-trabacus** [odoo/odoo#45915]
**1.My requirements:** 

- Autologin in Odoo's backend without login-screen, by token-passing or else, but it should work for all email-types, as OAuth only works with Microsoft Account.

- I am working on POS-Module and have 2 users as :

1. regular customer(uses only site, developed by using Odoo's Community edition) and
2. business user who uses odoo's backend module, 

I wanted to auto login to business user when I turn on it and login to backend automatically as res.partner.

**2.My approaches:**

- am trying to login using token-based Auth, because we are using Odoo-web module in mobile-app. 
 currently using GET-method url-passing approach which is "UNSECURE" on websites without SSL certificates and localhost-websites, as 
  myurl.com?username=foo&password=bar

- I found this authenticate() method in core-modules of odoo in http-controllers file and I am calling 
   that only now, as:

   request.session(db, username, password)

   but I wanted it to be token based without hardcoding password as different passwords for different 
  partners, which I can't hardcode and it's bad approach.
 
**3. My doubts/issues:**

How can I do that using Token based approach or passing credentials in POST-method, in Odoo-12?

how can I do it by passing token and validating it?

**Comment by ganesh-trabacus** [comment]
My Stackoverflow question is here:https://stackoverflow.com/questions/60280924/how-to-auto-login-in-odoos-web-module-for-res-user-not-for-res-partner

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
