### ISSUE TITLE
Missing authorisations when printing a check in batch

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#4599]
When a user belonging to the group 'Invoicing & Payments' or 'Accounting Manager' attempts to print a check using the action "Print Check in Batch" she faces the error message:

Access Denied
Sorry, you are not allowed to modify this document. Only users with the following access level are currently allowed to do that:
- Administration/Settings

(Document model: ir.sequence)

Currently module 'account_check_writing' performs a write action to the object 'ir.sequence' in account_check_batch_printing.py, but only a user that belongs to the group "Administration/Settings" has the rights to write on that object.

This does not make sense at all.  A user belonging to the groups:
account.group_account_invoice
account.group_account_manager

,should at least have permissions to read and write on model base.model_ir_sequence.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
