### ISSUE TITLE
[12.0][BUG] AAL currency_id should refer to analytic account

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#45995]
https://github.com/odoo/odoo/blob/be09fa8ebcefe1794577c90236fa210efaa2125e/addons/analytic/models/analytic_account.py#L190

Instead of `company_id.currency_id` it should be `account_id.currency_id`

**Comment by Yenthe666** [comment]
@alexey-pelykh feel free to make a PR if you identified the issue and found a fix ;)

**Comment by alexey-pelykh** [comment]
Those PRs can hang in for years, honestly. But here you go #46005

**Comment by qdp-odoo** [comment]
it didn't. 

PR was rejected: I don't consider it as a bug. Feel free to comment
