### ISSUE TITLE
Messaging on partner without the partner like a follower, no info or link on the concerning record

### ISSUE THREAD

**Issue by martinauger03** [odoo/odoo#460]
In v7, if we wrote a message from partner record, and we remove the Partner from the message as a follower, all followers receive the message but they don't know on which object and record this message came from.  

If we wrote a message from a Project we can see a title like "Projects / test" and if we select it with the mouse it open directley the project.  And that's greate!

But for partner, we don't have this and the followers can not know the message are linked on a specific partner if the partner is not in the follower.  And the follower can not clic with the mouse to open the partner because the information is not there...  But if we do a "Reply" the partner name appear like a follower but still not possible to open the record from there...

Thx,

Martin

**Comment by Yenthe666** [comment]
Dear @martinauger03,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
