### ISSUE TITLE
[12.0] hr_expense and hr_timesheet group name collision

### ISSUE THREAD

**Issue by alexey-pelykh** [odoo/odoo#46001]
https://github.com/odoo/odoo/blob/feb7c99f47cae55fff77035fe53975ea4a14d624/addons/hr_expense/views/hr_expense_views.xml#L10
and
https://github.com/odoo/odoo/blob/70941ab9b1386549925b612ed00f8712b087e010/addons/hr_timesheet/views/hr_views.xml#L36

**Comment by Yenthe666** [comment]
Why does it give a collision? It doesn't break anything does it?

**Comment by alexey-pelykh** [comment]
`<xpath expr="//field[@name='timesheet']" position="inside">` is logically to be a bit more deterministic? :) Feels just like a copy-paste error

**Comment by Yenthe666** [comment]
We could do a PR as an improvement for master but changes to this probably won't be accepted in a stable

**Comment by alexey-pelykh** [comment]
In master this is no longer present, so I guess can be closed then?

**Comment by Yenthe666** [comment]
Yep, thanks for checking!
