### ISSUE TITLE
<report> tag is missing a "paper_format_id" attribute

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#4601]
The `paper_format_id` allows setting the paper format for a report, but the <report> tag is not capable to accept an attribute for that field. The workaround is to use a <record> instead.
Found both in 8.0 and master.

**Comment by sle-odoo** [comment]
Indeed. Still on the todo list. If you or someone else is willing to make a pull request i'll be glad to review and merge it quickly..

**Comment by sle-odoo** [comment]
Done at rev 91b2ec771f00567f2dacfcae919087e2b1e72e4c
Thanks @dbo-odoo
