### ISSUE TITLE
[8.0] theme_clean does not install properly in Odoo 8.0: ParseError: "null value in column "name" violates not-null constraint

### ISSUE THREAD

**Issue by lukebranch** [odoo/odoo#4604]
I've emailed design@odoo.com, however I thought I would post this here as well, as i'm not sure what the suggested method is for reporting issues with the design-theme repository themes.

I've received my copy of the theme_clean module from the indiegogo campaign, however i'm having issues installing in 8.0.

Here's the email I sent to the design team - design@odoo.com:

Hi Design Team,

Is this theme compatible with the 8.0 branch? I’m getting the following traceback when installing on an 8.0 instance:

ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (28, 1, 2015-01-09 05:29:16.360576, null, null, /theme_clean/static/src/img/content/image_content_01.png, null, 1, 1, null, binary, null, 2015-01-09 05:29:16.360576, 0, null, null, null, null, null, null).
" while parsing /opt/odoo/custom/addons/theme_clean2/views/image_content.xml:23, near
<record id="theme_common.image_content_01" model="ir.attachment">
        <field name="url">/theme_clean/static/src/img/content/image_content_01.png</field>
    </record>

And when I simply comment on the offending images in the  /opt/odoo/custom/addons/theme_clean2/views/image_content.xml file I seem have an installable module that destroys the formatting on the website frontend (see screenshot attached). Is there a possibility that website_less is not working as it should with the 8.0 branch?

Here’s my environment:

OS:						Ubuntu 14.04 64 Bit Server Edition
PostgreSQL Version:		9.4
Odoo Version:			8.0 
Install Method:			https://github.com/lukebranch/odoo-install-scripts/blob/master/odoo-saas4/ubuntu-14-04/odoo_install.sh

Here’s the output from my latest pull:

From https://www.github.com/odoo/odoo
   4be70c8..255f50d  8.0        -> origin/8.0
   9191115..d0cd92b  7.0        -> origin/7.0
   f9cb753..1c6eec0  master     -> origin/master
   879fca0..32246d9  saas-3     -> origin/saas-3
Merge made by the 'recursive' strategy.
 addons/crm_helpdesk/crm_helpdesk_view.xml       |    2 +-
 addons/fleet/fleet_view.xml                     |    2 +-
 addons/hr_timesheet_sheet/hr_timesheet_sheet.py |   14 +++++--
 addons/sale/wizard/sale_line_invoice.py         |   47 +++++++++++++----------
 addons/sale/wizard/sale_make_invoice_advance.py |    3 +-
 addons/stock/stock.py                           |    3 +-
 addons/stock_account/stock.py                   |    4 +-
 addons/website/static/src/css/snippets.css      |    5 ++-
 addons/website/static/src/css/snippets.sass     |    5 ++-
 addons/website_sale/controllers/main.py         |    5 ++-
 openerp/fields.py                               |    9 ++++-
 11 files changed, 63 insertions(+), 36 deletions(-)

Is theme_clean only compatible with master at this point in time?

Here’s my steps to reproduce:

Create a fresh database with no demo data
Unzip theme_clean.zip into /custom/addons directory path (already included in my odoo-server.conf file) (including website_less, theme_clean and theme_common folders)
Update modules list
Install theme_clean
Complete traceback is here: https://gist.github.com/lukebranch/efd6cb2e1b10441361a3

**Comment by vilder** [comment]
On my server theme_clean installs without errors , but website module then does not load css and other less element

**Comment by wtaferner** [comment]
I tested yesterday on runbot and there was still an issue and currently @antonylesuisse seems to work on fixing it for Version 8 himself.

http://runbot.odoo.com/runbot/repo/git-github-com-odoo-design-themes-3

**Comment by lukebranch** [comment]
@vilder ,

Thanks for your help.

I had a feeling it might have been an npm version problem. I'll do the same and post back if it works for me as well.

**Comment by antonylesuisse** [comment]
Yes i updated the documentation about it:

**Comment by lukebranch** [comment]
@vilder ,

Thanks, installing from source worked for me.

@antonylesuisse ,

Thanks for all your help via the mailing lists today, and for responding so quickly. I look forward to seeing what I can build using theme_clean as a boilerplate for new projects.

**Comment by copmn** [comment]
I had the same problem, even after take a new download from the link. 

```
    <record id="theme_common.image_content_01" model="ir.attachment">
        <field name="url">/theme_clean/static/src/img/content/image_content_01.png</field>
    </record>
```

It misses the ```<field name="name">```. By adding it it works fine. So if you have this error you should add it. After, it should look like this:
```
    <record id="theme_common.image_content_01" model="ir.attachment">
        <field name="name">image_content_01.png</field>
        <field name="url">/theme_clean/static/src/img/content/image_content_01.png</field>
    </record>
```

You must repeat this for every ``ìmage_content```record.

**Comment by dmo-odoo** [comment]
@copmn I think you are trying to install an old version which has an issue with the image records.
Could you please try to re-download the zip from the link you should have received by mail ?

**Comment by nuelgoz** [comment]
That dependencies must meet ubuntu to work this theme?

**Comment by dmo-odoo** [comment]
@nuelgoz No, I don't think you especially need to be on Ubuntu, you just need nodejs, npm, lessc and the clean-css plugin for lessc, but the steps to install them on your distributions may be different.

**Comment by nuelgoz** [comment]
I think I have these packages on ubuntu ok, but I get this error and do not know how to fix it.

I use ubuntu 14.04 and Odoo 8

https://drive.google.com/file/d/0B0aLTGofHxAsNVA5UnpaRGF6YUE/view?usp=sharing

**Comment by antonylesuisse** [comment]
The v8 deb packaging was missing some files.

$ apt-get update && apt-get install odoo

Then retry.

**Comment by mgielissen** [comment]
For Ubuntu 14.04 you can also try:

apt-get install node-less

Op 18-01-15 om 13:54 schreef antonylesuisse:
