### ISSUE TITLE
[13.0] base: res.config.settings errors give traceback instead of warning

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#46138]
Impacted versions: 13.0

Steps to reproduce:
1. Create some field on `res.config.settings` from the type `Binary` which is not supported:
```
# -*- coding: utf-8 -*-

from odoo import models, fields, api


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    signature = fields.Binary(
        string='Signature',
        config_parameter='signature'
    )
```
2. Create a view for it:
```
<?xml version="1.0" encoding="utf-8"?>
<odoo>

    <record id="res_config_settings_view_inherit_form" model="ir.ui.view">
        <field name="name">res.config.settings.view.form.inherit</field>
        <field name="model">res.config.settings</field>
        <field name="priority" eval="50"/>
        <field name="inherit_id" ref="base.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <xpath expr="//div[hasclass('settings')]" position="inside">
                <div class="app_settings_block" data-string="some_app"
                     string="Some app"
                     data-key="some_app">

                <h2>Some app</h2>
                <div class="row o_settings_container">
                    <div class="col-xs-12 col-md-6 o_setting_box" id="signature">
                        <div class="o_setting_right_pane">
                            <label string="Signature" for="signature"/>
                            <div class="text-muted">
                                The official signature
                            </div>
                            <div class="mt16">
                                <field name="signature" required="1"/>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </xpath>
        </field>
    </record>
</odoo>
```
3. Install the app and go to the view. You'll get a traceback:
![image](https://user-images.githubusercontent.com/6352350/75166682-86c94d00-5724-11ea-89a7-b487f0f92420.png)

Current behavior:
You get an ugly traceback

Expected behavior:
A clean traceback such as from a `UserError`. I propose to change:
https://github.com/odoo/odoo/blob/08540d7853d497e326182e822b359cd6fcb05d59/odoo/addons/base/models/res_config.py#L450-L473

So that all raise `Exception` lines become raise `UserError`

**Comment by Yenthe666** [comment]
@mart-e hi, before I create a PR I wanted to make sure if there is no reason why this was done on purpose? I'd much rather get an `UserError` instead of those ugly tracebacks but maybe I'm missing something for why this was done :)

**Comment by mart-e** [comment]
Hi!

This is fine to throw ugly traceback at developers, less at end users. In this case, storing an attachment as a config_parameter does not work (because not sure what you expect anyway) and it's raised for the developer that tries its app.

One may argue that you could ship it without properly testing but the idea is:
- traceback for wrong code that must be fixed
- clean errror for bad a user behaviour

One may also argue that a user should never see a traceback and, maybe, one day we will implement a "Error 5223x75467, please report to admin" kind of message...

So in this case, this is fine I think.

**Comment by Yenthe666** [comment]
Don't you think it is cleaner to just throw an `UserError` though? It shows the same info as an ugly traceback and its cleaner to show to the developer (or the end user if the developer didn't really test things well). I dunno, I don't like the full traceback error :) 
& FYI: I was hoping to store a small signature sign in the general settings but I've solved it differently.

**Comment by mart-e** [comment]
Yes but tracebacks are useful, they show a lot of debugging information.

I agree with you it is not good to show a traceback to the end user, as I said in my last message, maybe one day we will fully hide the traceback information (I think @rim-odoo wants to implement something like this). But this is not done changing the type of error that is raised, but by how the exceptions are handled. By the way, to display your screenshot, you already had to click on the "See details" button. By default, you don't see the error.

But, anyway, in this case, this is a _programmation_ error, it is semantically not correct to consider it as a _user_ error.

**Comment by Yenthe666** [comment]
Okay got it, thanks for the feedback Martin!
