### ISSUE TITLE
[12.0/13.0] Replies to messages in Discuss channels does not post them on the document

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#46151]
Hello,

We came across a strange behavior, and confirmed it on several servers, locals and runbot, and it happens everywhere.

Whenever a channel is added as a follower of a document, any messages posted on the document's chatter are automatically added to that channel and visible in Discuss.

However, when trying to reply to messages through Discuss (via the reply button), the message will show up in Discuss but it won't be posted to the document's chatter (although a pop up says it was), and therefore won't send an email or post a note. It just won't exist in that document.

Thank you.

**Comment by seb-odoo** [comment]
Hello,

Replying on the channel is a reply on the channel, not on the document.
If the goal is to reply on the document, it should be done in the document.

Note that channel follower will be removed altogether in v15.
