### ISSUE TITLE
Account Report. Add support for sum_if_plus1year, sum_if_5year and sum_if_plus5years

### ISSUE THREAD

**Issue by aliencrash** [odoo/odoo#46171]
Impacted versions:
12,13
Since account reports supports sum_if_neg and sum_if_pos, It would be also interesting to add support for 
sum_if_plus1year -> This would sum if the move.line has date_maturity superior to one year.
sum_if_5year -> This would sum if the move.line has date_maturity till 5 year.s
sum_if_plus1year -> This would sum if the move.line has date_maturity superior to 5 years.

I'm trying to implement this now but it could be useful for everybody. Any hit would be helpful too.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by aliencrash** [comment]
it's a suggestion
