### ISSUE TITLE
Take into account date format changes when printing existing invoices

### ISSUE THREAD

**Issue by fotiDim** [odoo/odoo#4618]
Impacted versions:
- 8.0-a2115ef

Steps to reproduce:
1. create a new invoice
2. Change language date format settings
3. print invoice (pdf)

Current behavior:
- Date format in "%m/%d/%Y" while the new date format settings for the corresponding (and in my case every) language are "%d/%m/%Y" 

Expected behavior:
- Date format in "%d/%m/%Y"

**Comment by Yenthe666** [comment]
@NaviDeck-fdim I have the exact same problem on my Odoo's. (although I've custom coded new things to fix this).
However if I try one of the newest runbots (http://39213-8-0-010dd5.runbot6.odoo.com/) the dateformat seems to be correct! Can you have a look at this runbot and give it a try too?

As to the developer: if this is fixed, when/where is the patch supplied?

**Comment by NaviDeck-fdim** [comment]
Turns out I needed to create new invoice for locale changes to take effect. Changing title and description of issue.

**Comment by Beast141** [comment]
Im having the same issue: the date format changed immediately on the quotations list and quotations, but not invoices. i will wait till igenerate a new invoice so that i can see any change.. Il keep you posted.

**Comment by Beast141** [comment]
Okay i see that the date also changed on the invoices too. Its all good on my side.

**Comment by Yenthe666** [comment]
Hi @fotiDim ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
