### ISSUE TITLE
base_action_rule TypeError: 'months' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by OEGEM** [odoo/odoo#4620]
Hi,
using module, base_action_rule with branch 8.0, I create an automated action based on "On timed Condition",
I have this error log when the sheduler run: 

2015-01-09 14:39:23,685 26998 ERROR crm openerp.addons.base.ir.ir_cron: Call of self.pool.get('base.action.rule')._check(cr, uid, _(True,)) failed in Job 7
Traceback (most recent call last):
  File "/home/cygas/instances/8.0/openerp-8.0-ccfd/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/home/cygas/instances/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/home/cygas/instances/8.0/openerp-8.0-ccfd/openerp/addons/base_action_rule/base_action_rule.py", line 333, in _check
    action_dt = self._check_delay(cr, uid, action, record, record_dt, context=context)
  File "/home/cygas/instances/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/cygas/instances/8.0/openerp-8.0-ccfd/openerp/addons/base_action_rule/base_action_rule.py", line 288, in _check_delay
    delay = DATE_RANGE_FUNCTION[action.trg_date_range_type](action.trg_date_range)
  File "/home/cygas/instances/8.0/openerp-8.0-ccfd/openerp/addons/base_action_rule/base_action_rule.py", line 37, in <lambda>
    'month': lambda interval: timedelta(months=interval),
TypeError: 'months' is an invalid keyword argument for this function

This works with this patch : 

--- addons/base_action_rule/base_action_rule.py 2015-01-09 15:23:39.832267248 +0100
+++ addons/base_action_rule/base_action_rule.py 2015-01-09 15:29:50.139523774 +0100
@@ -19,7 +19,8 @@
 #
 ##############################################################################

-from datetime import datetime, timedelta
+from datetime import datetime
+from dateutil.relativedelta import relativedelta
 import time
 import logging

@@ -31,11 +32,11 @@
 _logger = logging.getLogger(__name__)

 DATE_RANGE_FUNCTION = {
-    'minutes': lambda interval: timedelta(minutes=interval),
-    'hour': lambda interval: timedelta(hours=interval),
-    'day': lambda interval: timedelta(days=interval),
-    'month': lambda interval: timedelta(months=interval),
-    False: lambda interval: timedelta(0),
-    'minutes': lambda interval: relativedelta(minutes=interval),
-    'hour': lambda interval: relativedelta(hours=interval),
-    'day': lambda interval: relativedelta(days=interval),
-    'month': lambda interval: relativedelta(months=interval),
-    False: lambda interval: relativedelta(0),
  }
  
  def get_datetime(date_str):

I verified code for openerp older versions since 6.0, and should have the same error I think ..., but I did not test for this older versions.

Bye

**Comment by astirpe** [comment]
I confirm the error. It occurs on branch 8.0. I didn't try on older versions.

**Comment by Yenthe666** [comment]
Hi @OEGEM,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
