### ISSUE TITLE
V8: Mail templates: no possibility to edit picture 

### ISSUE THREAD

**Issue by sandraMARIONEX** [odoo/odoo#4621]
Impacted version
8.0

Steps to reproduce
1/ go to Marketing/Mail Template/create template/ edit template (using website)
2/ drag and drop block and/or insert image
3/ select the image to try to get the menu dedicated to a picture (like in the normal website page) - it is not available - there is no possibility to edit the picture

Current behavior:
see screenshot: 
![image 3](https://cloud.githubusercontent.com/assets/10046359/5681758/82ca72d8-981b-11e4-9aeb-5ac94db592ba.png)
the image is selected but no menu appears

Expected behavior:
It would be nice to get the menu to edit a picture like in the normal webpage
![image 1](https://cloud.githubusercontent.com/assets/10046359/5681770/943ca3c4-981b-11e4-87b8-60a5cfb54062.png)

**Comment by Yenthe666** [comment]
Hi @sandraMARIONEX ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
