### ISSUE TITLE
[8.0] Change quantity on purchase line implies reset price unit from product cost price

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#4622]
Hi,

At change on quantity field on a purchase order line, the price unit of this line is directly reset from the product cost price.

How to reproduce :

- Go on runbot
- Click on purchase and select request for quotation submenu
- Click on create
- Click on Add an item to add purchase line
- Select a product ([1] Ice cream)
- Set 1 for the quantity
- Change price unit to 1000
- Move the focus out of the field area
- Change quantity to 2

Current behavior:
The price unit is reset to the product cost price. Then, the custom price unit is lost.

This behavior is a little strange if think the expected one is to reset price unit only at product change.

Best regards,

**Comment by adrienpeiffer** [comment]
OPW 622203

**Comment by Lioncode** [comment]
Hi,
i am facing this issue on odoo v8.0 and i cant decrypt your message "OPW 622203". I imagine this is the code of a commit made by someone but i cannot find it. I would appreciate it if you could help.

**Comment by Yenthe666** [comment]
@Lioncode it refers to the enterprise ticket under which this was reported. So you can't access that ticket or see the info, only what is here.
@adrienpeiffer can you enlighten?
