### ISSUE TITLE
Cancel invoice from sale with other user

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#4623]
1) Steps to reproduce the issue you have observed 
1.- Create 2 users, 
- Sales, (manager sales)
- Invoice, Sale (see own leads), Accounting & Finance (Invoicing & payments)

2.- With sales:
Create a new sale.order -> confirm -> Create Invoice

3.- With invoice
Validate the invoice created by Sale order by step 2 -> Cancel the same invoice

Can find a demonstrative video here: 
http://youtu.be/M3X56UY6xIU

2) The result you observed 
I can not cancel the invoice, for permission to sale.order

 3) The result you expected
Can cancel the invoice with user 'invoice'

4) The OpenERP version
Version .- 7.0
Commit.- https://github.com/odoo/odoo/commit/38aa984f31f525539d27f2bf47806352705830ba

**Comment by Yenthe666** [comment]
Hi @luistorresm ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
