### ISSUE TITLE
[8.0] Pricelist: Rules based on other pricelist don't work properly

### ISSUE THREAD

**Issue by gaultp** [odoo/odoo#4624]
There is a problem with pricelists that use rules based on other pricelist.
It seems that it does not manage priorities and use only one rule even if you use several.

Scenario:
Price List A : with a rule applied on category of product A, discount of -40% on public price.
Price List B : with a rule applied on single product P which is not in category A, fix price of 100 (instead of public price 200)
Price List X :  with 2 rules based on other pricelist. First rule based on price list A, second based on price list B.

Expected behaviour: 
Sale order with Price List X as Price list.
When you add order lines: 
Line 1: Product P, Pricelist B
Line 2: Product Q from category A, Pricelist A

Observed behaviour:
Sale order with Price List X
When you add order lines:
Line 1: Product P, Pricelist A (price=0 because Pricelist A doesn't include Product P in the scope)
Line 2: Product Q from category A, Pricelist A 
Line 3: Product R from other category, Pricelist A (price=0 because Pricelist A doesn't include Product R in the scope)

**Comment by realsaiko** [comment]
Got the same problem.
I think the bug is in /addons/product/pricelist.py line 356
The 'break' is outside 'if price is not False:', so it just takes first rule, gets price false or not false and breaks to check other rules.
It took me two days to sort it out...

**Comment by Yenthe666** [comment]
Hi @gaultp ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
