### ISSUE TITLE
Error when installing clean theme

### ISSUE THREAD

**Issue by mamaf** [odoo/odoo#4626]
I installed the clean theme and I get this error when visualising the new site :

Could not get content for /website_less/statis/src/css/snippets.css defined in bundle 'website.assets_editor'
Could not get content for /website_less/statis/src/css/editor.css defined in bundle 'website.assets_editor'

**Comment by lukebranch** [comment]
@mamaf I think your issue may be related to #4604:

https://github.com/odoo/odoo/issues/4604

A similar issue was resolved for me after installing npmjs from source.

**Comment by mamaf** [comment]
How to go back to the standard theme ?
I uninstalled the clean theme but the errors are still here

**Comment by dmo-odoo** [comment]
Hello,

You are probably missing a dependency for lessc, here are the instructions to get lessc working correctly, taken from https://www.odoo.com/documentation/8.0/setup/install.html#source-install.

- On Linux, use your distribution’s package to install nodejs and npm.
    In debian you need at least jessie, as the packaged version of npm before that does not work. In Ubuntu you need at least Ubuntu 14.04, as the packaged version of npm before that does not work. Otherwise install nodejs and npm manually.

    Once you have npm working, install less and less-plugin-clean-css.

    $ sudo npm install -g less less-plugin-clean-css

    On debian and Ubuntu you also need to set a symbolic link from nodejs to node because the shebang line of lessc uses node.

    $ sudo ln -s /usr/bin/nodejs /usr/bin/node

- On OS X, install nodejs via your preferred package manager (macports, homebrew) then install less and less-plugin-clean-css.

    $ sudo npm install -g less less-plugin-clean-css

- On Windows, install nodejs then reboot and install less and less-plugin-clean-css.

    C:\> npm install -g less less-plugin-clean-css

If you still want to go back to the previous theming system, you need to remove the website_less module and not theme_clean only. Website_less is the one which adds support for less and which needs the aforementioned nodejs dependency.

**Comment by lukebranch** [comment]
@mamaf ,

I think you'll need to uninstall the dependencies for the module:

website_less and theme_common after you have uninstalled theme_clean. For me this put everything back as it was with the default (base) theme.

**Comment by dmo-odoo** [comment]
@lukebranch, mamaf: Yes, if you don't want to install the repositories to make lessc working correctly, then you need to uninstall website_less because, of course, it needs less. Uninstalling website_less will uninstall everything related to the new themes and less, avoind the error you get. Anyway, you will need to install those less dependencies if you want to use the new themes as they all use less.

**Comment by lukebranch** [comment]
@dmo-odoo ,

Thanks. I've found that when uninstalling theme_clean, it obviously is not designed to remove those two 8.0 modules:

website_less (compatibility layer)
theme_common (shared snippets, etc.)

I've managed to get lessc working no problem on Ubuntu 14.04, however I have not been able to get it to work with the apt-get and symlink method. It only seems to work for me when I install from source as @vilder has mentioned.

**Comment by dmo-odoo** [comment]
@lukebranch It is probably related to the version of npm packaged in Ubuntu 14.04 being quite old. On the npm website (https://docs.npmjs.com/getting-started/installing-node), they say that the latest version is 2.1.18 and the one from apt in Ubuntu 14.04 is 1.3.10. 

However, it seems you could have updated your npm from the one installed by apt instead of installing from source by running: 
$ sudo npm install npm -g

**Comment by lukebranch** [comment]
@dmo-odoo ,

Thanks for the tip, i'll give your suggestions a go as soon as I am in front of a terminal.

**Comment by FedwaSlimani** [comment]
@lukebranch I installed Extensia theme to try it but i found many fonctionnalities don't work and when I want to uninstall it I got this error "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application" how to fix this problem ? I want to go back to the standard theme of odoo.

**Comment by pedrobaeza** [comment]
@FedwaSlimani please don't hijack other threads with your same question.

**Comment by FedwaSlimani** [comment]
@pedrobaeza it's not a same question, this is another theme and another error so please either you answer or let other answer my question !

**Comment by pedrobaeza** [comment]
Please ask that steps in the forums or mailing lists, not here.
