### ISSUE TITLE
Scheduler - quants are not reserved by cron or administrator in multicompany environment

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4627]
Environment: Company B child of Company A
Company A - warehouse AA
Company B - warehouse BB

Steps to reproduce:
1. As user company B, create SO in warehouse BB, product XXX qty 10 (Qantity On Hand in BB = 90)
2. As Administator (main company A) use menu Run Schedulers ..... quants not reserved!
3. Activate cron Run mrp Scheduler ..... quants not reserved!
4. As user company B use menu Run Schedulers .....all OK, quants reserved!

Expected:
Quants are reserved if Administrator use menu Run Schedulers 
Quants are reserved if cron is active.

Suggestions:
Cron is called as Administrator only for Company A.
Menu Run Schedulers call both companies but In stock.py - V8 - method _quants_get_order()

domain += [('company_id', '=', self.pool.get('res.users').browse(cr, uid, uid, context=context).company_id.id)]

 in effect, in both cases admin reserve quants only for its main company.

**Comment by flotho** [comment]
Hi @zbik2607 

Maybe this could help : https://github.com/odoo/odoo/issues/11062#issuecomment-188245452

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
