### ISSUE TITLE
[13] [Wishlist] Possibility to update create_date and create_uid fields via ORM

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#46285]
Wishlist: Possibility to update create_date and create_uid fields via ORM

My use case require custom create_date for tasks, different than current date.
It was possible to change in older odoo versions (8?). 
Right now this can be archived with sql commands (self.env.cr.execute) after record create.

**Comment by pedrobaeza** [comment]
Sorry, but this is done on purpose, as that fields are intended for auditing, so this is not going to be done ever. If you want to do that risky customization, do it on your end.

Closing as won't fix due to the stated reason.
