### ISSUE TITLE
Scrapping from production order opens an empty stock.picking

### ISSUE THREAD

**Issue by npiganeau** [odoo/odoo#4632]
Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Open a runbot instance
 2. Go to production orders in mrp module
 3. Scrap a product from the move_lines tree in the production order

Current behavior:

 - After scrapping, a new empty stock.picking form opens

Expected behavior:

 - The scrap popup closes and the user is sent back to the production order

This is actually due to the modification of bdd5ec8216d375ef2baf3e9903c394a8f13061a1 which only checks if active_id is set before reloading a stock.picking, whereas it should also check if the move defined by active_id is from a picking or from a production order.

**Comment by jco-odoo** [comment]
I agree with you, but then it should be inherited in mrp somehow.  And maybe this also possible in the tree view of stock moves.

**Comment by npiganeau** [comment]
@jco-odoo I think it should be inherited in mrp only if mrp needs a specific behaviour, but mrp only needs to close the window. If you check the PR, you'll see that it does not make any reference to mrp models, it just checks that the move picking_id is not False before reloading the picking, and just closes the window otherwise.

For the tree view of moves you are right:

1. If you scrap a move that is associated to a picking, then it loads the picking afterwards => I don't know if this is a wanted behaviour. The user experience is a bit strange, but it is not a great issue. My PR doesn't change anything to this behaviour.
2. If you scrap a move that is not associated to a picking (e.g. to a production order) then the bug appears and we have an empty stock.picking window opening => My PR also solves this case

**Comment by nim-odoo** [comment]
Closed with accd3b472a1b0c01e62d47cb571a68dd88238d21
