### ISSUE TITLE
Checking if the payment is successful after the customer paid a sale order but the server was down while confirming the payment

### ISSUE THREAD

**Issue by khalyomede** [odoo/odoo#46369]
**Impacted versions**: 11.0 (tested), all (supposition)

**Steps to reproduce**: 

1. Go to the general configuration and activate online payment
2. Configure a Payment acquirer of your choice in Invoicing > Configuration > Payment acquirer
3. Create an sale order, attach a product and a customer
4. Before saving, go to the "Other information" tab and check "Confirmation mode" to "online payment"
5. Save, and click on the button "Send by email"
6. While you have the email preview open, copy the "Confirm and pay online" button link, and open it in another browser or go in private navigation to open it and view it as a public user
7. Click on the "Pay now" button, and wait until you arrive on the payment acquirer payment page (in my case, I used Adyen for testing purposes)
8. Cut your local instance of Odoo server
9. Confirm the payment, you should see a "unable to display the page" browser warning
10. Restart your local webserver
11. Close the public sale order page and use the sale order email button link again to view it
12. You can see that the payment has not been accounted, but the payment acquirer has it accounted

**Current behavior**: The payment is not accounted, and the user could be tricked in paying the same amount again.

**Expected behavior**: A way (but technically, how?) to asynchronously fetch the payment in case a payment is accounted but not in Odoo.

**Video/Screenshot link (optional)**: None

**Notes**: In this case, the transaction is in "draft" state. My issue is regarding how to proceed, technically and architecture speaking, to check if a payment has been accounted in this case:

1. Is there a state-of-the-art way to check it regardless the payment acquirer?
2. Should I go for a cron, and use any acquirer specific API to make sure Odoo is in line with what the payment acquirer has accounted?
3. Any other suggestions?

**Comment by pedrobaeza** [comment]
In v12, the cron is already there for this kind of things.

Closing unless there's other question.
