### ISSUE TITLE
[performance] many2many: Slow query using "WHERE" instead of "LEFT JOIN"

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#46407]
# Impacted versions:
Tested 11.0 and 13.0
Maybe: 12.0

# Steps to reproduce:
Start odoo-bin using shell and `--log-level=debug_sql`
I mean,
`~/odoo-13.0/odoo-bin shell -d db --log-level=debug_sql`

Execute the following commands:
```python
users = env['res.users'].search([]).with_context({})
users.groups_id
```

Notice the following output:
```sql
SELECT res_groups_users_rel.uid, res_groups_users_rel.gid 
FROM res_groups_users_rel,
           "res_groups"
WHERE 1=1 AND 
    res_groups_users_rel.uid IN (2, 7, 6) AND
    res_groups_users_rel.gid = res_groups.id
ORDER BY "res_groups"."name"
OFFSET 0
```

Now, execute the same query but using `EXPLAIN`
And removing the `ORDER BY` section (in order to separate the issue)

```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
 SELECT res_groups_users_rel.uid, res_groups_users_rel.gid
 FROM res_groups_users_rel,
            "res_groups"
 WHERE 1=1 AND
     res_groups_users_rel.uid IN (2, 7, 6) AND
     res_groups_users_rel.gid = res_groups.id
```

Check the following output:
```rst
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| QUERY PLAN
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| Nested Loop  (cost=0.15..13.52 rows=34 width=8) (actual time=0.040..0.175 rows=34 loops=1)
|   Output: res_groups_users_rel.uid, res_groups_users_rel.gid
|   Buffers: shared hit=159
|   ->  Seq Scan on public.res_groups  (cost=0.00..1.01 rows=1 width=4) (actual time=0.013..0.017 rows=46 loops=1)
|         Output: res_groups.id, res_groups.name, res_groups.comment, res_groups.category_id, res_groups.color, res_groups.share, res_groups.create_uid, res_groups.create_date, res_g
|         Buffers: shared hit=1
|   ->  Index Only Scan using res_groups_users_rel_gid_uid_key on public.res_groups_users_rel  (cost=0.15..12.50 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=46)
|         Output: res_groups_users_rel.gid, res_groups_users_rel.uid
|         Index Cond: ((res_groups_users_rel.gid = res_groups.id) AND (res_groups_users_rel.uid = ANY ('{2,7,6}'::integer[])))
|         Heap Fetches: 34
|         Buffers: shared hit=158
| Planning time: 0.218 ms
| Execution time: 0.202 ms
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Now change the query using `LEFT JOIN - ON`  instead of `FROM - WHERE`
```sql
EXPLAIN (ANALYZE, VERBOSE, BUFFERS)
 SELECT res_groups_users_rel.uid, res_groups_users_rel.gid
 FROM res_groups_users_rel
--            "res_groups"

LEFT JOIN res_groups
   ON res_groups_users_rel.gid = res_groups.id

 WHERE 1=1 AND
     res_groups_users_rel.uid IN (2, 7, 6)
--     res_groups_users_rel.gid = res_groups.id
```

Check the following output:
```rst
+---------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                            |
|---------------------------------------------------------------------------------------------------------------------------------------|
| Bitmap Heap Scan on public.res_groups_users_rel  (cost=8.72..19.19 rows=34 width=8) (actual time=0.031..0.034 rows=34 loops=1)        |
|   Output: res_groups_users_rel.uid, res_groups_users_rel.gid                                                                          |
|   Recheck Cond: (res_groups_users_rel.uid = ANY ('{2,7,6}'::integer[]))                                                               |
|   Heap Blocks: exact=1                                                                                                                |
|   Buffers: shared hit=4                                                                                                               |
|   ->  Bitmap Index Scan on res_groups_users_rel_uid_idx  (cost=0.00..8.71 rows=34 width=0) (actual time=0.022..0.022 rows=34 loops=1) |
|         Index Cond: (res_groups_users_rel.uid = ANY ('{2,7,6}'::integer[]))                                                           |
|         Buffers: shared hit=3                                                                                                         |
| Planning time: 0.132 ms                                                                                                               |
| Execution time: 0.065 ms                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------+
```

# Current behavior:
Joining tables using`FROM - WHERE` is calling an extra sequence scan.

# Expected behavior:

Joining m2m tables using `LEFT JOIN - ON` instead.

It looks like is not a big deal but for a live production instance the execution time is 20,000x faster
 - https://gist.github.com/moylop260/726efd44d2b3ac2615c2eab095baae55

FYI I have checked the difference of records returned for both queries and it is the same.
Disclaimer: Maybe I don't know a corner case where it is different.

UPDATED: In fact, IMHO for this case should be a context to avoid ordering since that it is joining another table to use only the `order by` 
Similar to https://github.com/odoo/odoo/pull/46392 but for m2m

cc @rco-odoo @odony @xmo-odoo

**Comment by odony** [comment]
Are you sure about the query plans? The `Output: res_groups.id, res_groups.name, res_groups.comment ...` part does not seem to match the query?

Testing on 13.0 I indeed get the following queries:

```
2020-02-27 09:36:05,901 30145 DEBUG 13e odoo.sql_db: query: SELECT "res_users".id FROM "res_users" LEFT JOIN "res_partner" as "res_users__partner_id" ON ("res_users"."partner_id" = "res_users__partner_id"."id") WHERE ("res_users"."active" = true) ORDER BY "res_users__partner_id"."name" ,"res_users"."login"   
2020-02-27 09:36:06,192 30145 DEBUG 13e odoo.sql_db: query: SELECT "res_users"."id" as "id" FROM "res_users" WHERE "res_users".id IN (8, 6, 2, 9) 
2020-02-27 09:36:06,193 30145 DEBUG 13e odoo.sql_db: query:  SELECT res_groups_users_rel.uid, res_groups_users_rel.gid FROM res_groups_users_rel, "res_groups"
                    WHERE 1=1 AND res_groups_users_rel.uid IN (2, 6, 9, 8) AND res_groups_users_rel.gid = res_groups.id
                     ORDER BY "res_groups"."name"    OFFSET 0
```

But the query plan for the last query is quite different (PG 10):

```
                                                            QUERY PLAN                                                  
------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=6.64..6.73 rows=36 width=30) (actual time=0.160..0.166 rows=66 loops=1)
   Output: res_groups_users_rel.uid, res_groups_users_rel.gid, res_groups.name
   Sort Key: res_groups.name
   Sort Method: quicksort  Memory: 29kB
   Buffers: shared hit=3
   ->  Hash Join  (cost=3.42..5.71 rows=36 width=30) (actual time=0.054..0.099 rows=66 loops=1)
         Output: res_groups_users_rel.uid, res_groups_users_rel.gid, res_groups.name
         Inner Unique: true
         Hash Cond: (res_groups_users_rel.gid = res_groups.id)
         Buffers: shared hit=3
         ->  Seq Scan on public.res_groups_users_rel  (cost=0.00..2.19 rows=36 width=8) (actual time=0.011..0.035 rows=6
               Output: res_groups_users_rel.gid, res_groups_users_rel.uid
               Filter: (res_groups_users_rel.uid = ANY ('{2,6,9,8}'::integer[]))
               Rows Removed by Filter: 69
               Buffers: shared hit=1
         ->  Hash  (cost=2.63..2.63 rows=63 width=26) (actual time=0.037..0.038 rows=63 loops=1)
               Output: res_groups.name, res_groups.id
               Buckets: 1024  Batches: 1  Memory Usage: 12kB
               Buffers: shared hit=2
               ->  Seq Scan on public.res_groups  (cost=0.00..2.63 rows=63 width=26) (actual time=0.007..0.019 rows=63 l
                     Output: res_groups.name, res_groups.id
                     Buffers: shared hit=2
 Planning time: 0.264 ms
 Execution time: 0.201 ms
(24 rows)
```

And when I run the same query on a large prod database I get very decent performance (less than 1ms).

**Comment by odony** [comment]
Also your LEFT JOIN should be an INNER JOIN, but that's beside the point.

**Comment by moylop260** [comment]
Hi @odony 
Thanks for reply

Good catch!
I didn't realize that `Seq Scan` is retrieving all columns of `res_group`

I'm testing PG 10 too and yes the query plans is correct, It is so weird.

I send you an image:
 - ![Screen Shot 2020-02-27 at 12 27 17](https://user-images.githubusercontent.com/6644187/75474733-1fe2a880-595d-11ea-9495-22a7faa1ec05.png)

I will create a new PR in order to check if in runbot can be reproduced

**Comment by gdgellatly** [comment]
@moylop260 I looked at some db stats here on a large production database with a lot of groups. Average of 8500 call / hour at 0.13ms average during business hours. Or put another way, a total cost of about 1 second / hour. 

I also tested every version of the query posted here on pg11 and as expected (as postgres WHERE and INNER JOIN I believe are meant to plan identically) got identical query plans, except LEFT JOIN which is different but timing about the same.

**Comment by moylop260** [comment]
Hi @gdgellatly 
Ok, thank for reply and tested it

However, it was reproduced from a [runbot build](http://runbot.odoo.com/runbot/build/1551367) - [full.log](http://runbot20.odoo.com/runbot/static/build/1551367-46483-37b5f6/logs/all_at_install.txt):
 - https://github.com/odoo/odoo/pull/46483

The output is retrieving all fields too.

```txt
odoo.addons.test_performance.tests.test_performance:550 test_m2m_query_issue_46407

FAIL: TestPsqlPerformance.test_m2m_query_issue_46407
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/test_performance/tests/test_performance.py", line 550, in test_m2m_query_issue_46407
    self.assertNotIn('Seq Scan on ', res_str, "It is using an extra seq scan.")
AssertionError: 'Seq Scan on ' unexpectedly found in "Nested Loop  (cost=0.15..13.52 rows=34 width=8) (actual time=0.011..0.032 rows=9 loops=1)
  Output: res_groups_users_rel.uid, res_groups_users_rel.gid
  Buffers: shared hit=40
  ->  Seq Scan on public.res_groups  (cost=0.00..1.01 rows=1 width=4) (actual time=0.003..0.004 rows=11 loops=1)
        Output: res_groups.id, res_groups.name, res_groups.comment, res_groups.category_id, res_groups.color, res_groups.share, res_groups.create_uid, res_groups.create_date, res_groups.write_uid, res_groups.write_date
        Buffers: shared hit=1
  ->  Index Only Scan using res_groups_users_rel_uid_gid_idx on public.res_groups_users_rel  (cost=0.15..12.50 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=11)
        Output: res_groups_users_rel.uid, res_groups_users_rel.gid
        Index Cond: ((res_groups_users_rel.uid = ANY ('{7,6,2}'::integer[])) AND (res_groups_users_rel.gid = res_groups.id))
        Heap Fetches: 9
        Buffers: shared hit=39
Planning time: 0.097 ms
Execution time: 0.043 ms" 
: It is using an extra seq scan.
```

cc @odony

**Comment by gdgellatly** [comment]
@moylop260 Runbot is not very good for testing SQL query plans. Because the tables have such little data in them the planner will often choose a seq scan as faster than an index scan. The problem isn't a seq scan as you can see from the performance, it is the correct choice with little data. Also runbot postgres configuration is tuned for precisely doing CI, it is not a production config.

So your test on runbot is essentially on an unrealistic dataset with an unrealistic config. You can't really generalize it.

**Comment by gdgellatly** [comment]
I just reran all those queries again. 

Using LEFT JOIN is not identical to the original query. You need to use INNER JOIN. Obviously LEFT JOIN doesn't need to scan the RIGHT table, so you don't get a scan there as it doesn't check for existence as none of the output of the RIGHT table is required in your truncated query. 

But your query cutting to remove noise is your issue. You have effectively written an entirely different query to the original by removing the ORDER BY clause and using a LEFT JOIN and created a situation that doesn't exist. Because regardless of whether you use LEFT or INNER the full query with ORDER BY will require a scan of the RIGHT table. So there is no performance gain at all.

In fact running the full query using LEFT, INNER and WHERE all produce exactly identical results and query plans for me.

**Comment by moylop260** [comment]
@gdgellatly 
Thanks for reply

> Runbot is not very good for testing SQL query plans. 

I know, Is there another open and standard environment to reproduce these kind of issues?

> Because the tables have such little data in them the planner will often choose a seq scan as faster than an index scan. The problem isn't a seq scan as you can see from the performance, it is the correct choice with little data. 

I know, the problem really is not the `seq scan` as you can see my comment where I'm talking about the `output` it is returning all columns.

> Also runbot postgres configuration is tuned for precisely doing CI, it is not a production config.

I know, the same case was with the configuration of the `collate=c`
Check the following PR:
 - https://github.com/odoo/odoo/pull/25196
The final result was so good here.

In fact, if you know the configuration to avoid retrieving all columns it is welcome.

> You have effectively written an entirely different query to the original by removing the ORDER BY clause

`ORDER BY` was removed since that I have created PR to removed it (check my other PRs since that we don't need a order for all cases, but this is another history).


The summary of this issue is that:
 - LEFT JOIN is not a good solution since that returns different results (like my disclaimer comment)
 - It is not a Odoo's ORM issue
 - There is not a good environment to reproduce it

Real issue:
 - PG is retrieving all columns but they are not used.

For that I closed this issue for odoo.

But if someone knows the `why` or `solution` the reply are welcome.
Thanks!
