### ISSUE TITLE
[12] [Email Alias] Failed to process mail from imap server

### ISSUE THREAD

**Issue by adedip** [odoo/odoo#46420]
Impacted versions: 12

Steps to reproduce: don't know, it happened out of the blue, what I know is that on webclient configured with imap I do receive the full message with no errors

Current behavior: I have some email configured as incoming email via IMAP, I have the catchall configured too. Everything was working as supposed to. Every email I received for each of these email went straight into the associated project creating a new task. Few hours ago something went wrong (no deploy or configuration changed) Odoo still creates new task in the project but there's no email body in the chatterbox.

This is the error I get in the log:

`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | 2020-02-27 09:17:27,808 1 INFO odootabprod odoo.addons.fetchmail.mode
ls.fetchmail: start checking for new emails on imap server mario imap `
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | 2020-02-27 09:17:30,353 1 INFO odootabprod odoo.addons.mail.models.ma
il_thread: No matching user_id for the alias mario.scagnetti `
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | 2020-02-27 09:17:30,368 1 INFO odootabprod odoo.addons.mail.models.ma
il_thread: Routing mail from "Andrea D'Ippolito" <dippolito@**********.it> to mario.scagnetti@***********.it with Message-Id <CAL3top5hp-g
vd0XF=tY71JxNt+gUraCTJAfZ_EGw+pmLAYjiSQ@mail.gmail.com>: direct alias match: ('project.task', 0, {'project_id': 29}, 1, mail.alias(187,)
) `
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | 2020-02-27 09:17:30,407 1 INFO odootabprod odoo.addons.fetchmail.mode
ls.fetchmail: Failed to process mail from imap server mario imap. `
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | Traceback (most recent call last):`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/fetchmail/models/f
etchmail.py", line 178, in fetch_mail`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     res_id = MailThread.with_context(**additionnal_context).message_p
rocess(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 1432, in message_process`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     thread_id = self.message_route_process(msg_txt, msg, routes)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mass_mailing/model
s/mail_thread.py", line 47, in message_route_process`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     return super(MailThread, self).message_route_process(message, mes
sage_dict, routes)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 1338, in message_route_process`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     thread = MessageModel.message_new(message_dict, custom_values)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/project/models/pro
ject.py", line 861, in message_new`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     task = super(Task, self.with_context(create_context)).message_new
(msg, custom_values=defaults)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 1462, in message_new`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     return self.create(data)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "<decorator-gen-289>", line 2, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _mo
del_create_single`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     return create(self, arg)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/project/models/pro
ject.py", line 694, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     task = super(Task, self.with_context(context)).create(vals)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "<decorator-gen-124>", line 2, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _mo
del_create_multi`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     return create(self, [arg])`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 298, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     thread.message_track(tracked_fields, initial_values)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 649, in message_track`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     record.message_post(subtype=subtype_xmlid, tracking_value_ids=tra
cking_value_ids)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/mail
_thread.py", line 14, in message_post`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     message = super(MailThread, self).message_post(**kwargs)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_t
hread.py", line 2069, in message_post`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     new_message = MailMessage.create(values)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "<decorator-gen-120>", line 2, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _mo
del_create_single`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     return create(self, arg)`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_m
essage.py", line 951, in create`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     values['email_from'] = self._get_default_from()`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |   File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_m
essage.py", line 34, in _get_default_from`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    |     raise UserError(_("Unable to post message, please configure the s
ender's email address."))`
`58-odoo-tab-prod_odoo.1.maco0ecxuc10@server01    | odoo.exceptions.UserError: ("Impossibile pubblicare il messaggio, con
figurare l'indirizzo email del mittente.", '')`

Expected behavior: Every email I receive for each of these email than creates a task into the associated project, **should have body content**

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is because you have an automatic follower that hasn't configured the email address, so it's expected.

Closing as no real issue.

**Comment by adedip** [comment]
It worked thanks, I did remove the email from Odoo Bot contact, putting it back solved the problem.
Still is unclear to me how this is related to activity body, but it worked, so thanks! 👍
