### ISSUE TITLE
Pos iot box Order printing error

### ISSUE THREAD

**Issue by attthurein** [odoo/odoo#46421]
**Impacted versions:**
Odoo Version 13.0
IOT box 19_12
Epson printer TMU 220B

IOT box downloaded from the link below

https://nightly.odoo.com/master/iotbox/

**Steps to reproduce:**

POS > Take Food or Beverage > Print Order to the kitchen printer

**Current behaviour:**

If I printing to the kitchen printer, the font is not correct. (picture 1.jpg)

I try to reset the printer and print again, still, the error occurs. (picture 2.jpg)

Expected behaviour:

**Video/Screenshot link (optional):**

![1](https://user-images.githubusercontent.com/26271759/75438196-ef633480-5985-11ea-9cfe-1c0056382f38.jpg)
![2](https://user-images.githubusercontent.com/26271759/75438200-f12cf800-5985-11ea-8030-5093ada66cbf.jpg)

**Comment by AntoniRomera** [comment]
Now with the latest version of 04-March of the IOT, I have the same issue, only makes correct print of the ticket the first time after reset the printer
