### ISSUE TITLE
i have created one report and it is giving me an error. QWebException: ""'NoneType' object is not callable" while evaluating

### ISSUE THREAD

**Issue by Bhaviraj** [odoo/odoo#4643]
this is my code file give me solution plzzzzzzz....

<div><span t-esc="_get_total(o)"></span></div>

import time
from openerp.osv import osv
from openerp.report import report_sxw

class report_registration_recepy(report_sxw.rml_parse):

    def __init__(self, cr, uid, name, context=None):
        super(report_registration_recepy, self).__init__(cr, uid, name, context=context)
        self.localcontext.update({
            'get_date': self._get_total,
        })
        self.context = context

    def _get_total(self,data):
        print '\n\n data : ', data
        return True

class report_cook_registration(osv.AbstractModel):
    _name = 'report.recepy_module.cook_registration_template'
    _inherit = 'report.abstract_report'
    _template = 'recepy_module.cook_registration_template'
    _wrapped_report_class = report_registration_recepy

**Comment by xmo-odoo** [comment]
This is not the right place for questions about your code not working, please use the forum.
