### ISSUE TITLE
In Odoo Help Forum, some answers have no description in Answer List for user

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#46492]
Maybe this has been fixed, but some answers submitted after the upgrade have no description:

![image](https://user-images.githubusercontent.com/38899643/75507228-77dfe480-5a1b-11ea-8070-e430221cc785.png)

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by ctringham** [comment]
Yes!!
![Answers](https://user-images.githubusercontent.com/38899643/77869191-33d93d00-7270-11ea-8753-49610fc26e4e.JPG)

**Comment by pedrobaeza** [comment]
@JKE-be not sure who to ping for this.

**Comment by ctringham** [comment]
There's a small improvement.  The description is still missing, but there is a clickable link
![Answers2](https://user-images.githubusercontent.com/38899643/78034292-1accab00-739a-11ea-9b4e-592d40203930.JPG)

**Comment by ctringham** [comment]
Seems to be OK now

**Comment by pedrobaeza** [comment]
Then let's close it.
