### ISSUE TITLE
"group_by" not working in Odoo 13

### ISSUE THREAD

**Issue by Garcicasti** [odoo/odoo#46530]
Impacted versions: 12, 13 

Steps to reproduce: Create a custom view with a one2many field as follows:

`<field
                            name="alquiler_line"
                            widget="section_and_note_one2many"
                            readonly="1"
                            mode="tree"
                            nolabel="1"
                            context="{'group_by':'alquiler_espacio'}"
                            >`

Current behavior: The "table" standard view is shown, but the "group_by" option doesn't work. 

Expected behavior: I saw that this functionality was available in older versions of Odoo. See this link: http://www.zbeanztech.com/blog/filtering-one2many-fields-openerp

I believe this is a good option to have when creating custom modules, so should probably be ported to new versions.

Thanks a lot to all.

**Comment by pedrobaeza** [comment]
This is done on the search view, so please read current documentation.

Closing as no real issue, but misuse of the framework.

**Comment by Garcicasti** [comment]
Hi Pedro,

I know that this is usually done in the search view. The point is that I want to do something similar in the tree view. As you can see in the link I posted, it was possible to do so in some older version of OpenERP, that is, to use context tag in the tree view. But as me and my colleagues tried, it is not working on last versions of Odoo. 

![image](https://user-images.githubusercontent.com/23293693/75550718-c64cad80-5a32-11ea-91a9-62e596c3dadf.png)

Please reconsider closing the issue.

**Comment by pedrobaeza** [comment]
That option is not available anymore because Odoo doesn't consider it as a good approach.

**Comment by Garcicasti** [comment]
Okey, understood. Do you have any suggestions on which core functionality to use then? I have a o2m table and I would llike to distinguish in some way between the records that have a property in common.

![image](https://user-images.githubusercontent.com/23293693/75551112-baadb680-5a33-11ea-8cc1-dca0b3118bff.png)


Thanks for your support.

**Comment by pedrobaeza** [comment]
Multiple one2many with a domain on each one.
