### ISSUE TITLE
CMIS_WRITE

### ISSUE THREAD

**Issue by soncogan** [odoo/odoo#4655]
when I load the module cmi_write, the ccs is lost and not allowed in any option this messagen in logs: /web/css/web.assets_common/72360a8 Error 500 server internal error and File " /opt/odoo/custom/addons/cmis_write/ir_attachment.py " line 158, in _data_get
    _ ( "Document is not available in DMS; "

**Comment by Yenthe666** [comment]
Hi @soncogan ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
