### ISSUE TITLE
POS > PosBox : Epson TMT20II replaced by Epson TMT20III

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#46581]
As explained on the Odoo Point Of Sales page (here), the Epson TMT20II is recommanded for PosBox implementation.
This version is not supported by Epson anymore, but a new version of this printer was built : Epson TMT20**III** (with 3 i).

Is this new version compatible with PosBow as the older one was ?

**Comment by Yenthe666** [comment]
I believe it is but I'll let @pimodoo confirm it.

**Comment by pimodoo** [comment]
@gregory-moka Hello, we don't have the TMT20III yet, so we cannot guarantee you that it will work out of the box.

Once we'll have the printer we'll try it and upgrade it.

**Comment by gregory-moka** [comment]
Is there an (un)official list of compatible printers ? It could be easier for everyone, i guess, cause, even if the printer is ESC/POS ready, there are issues with the reciept's content...

**Comment by pimodoo** [comment]
In version 13.0, it is an image that is sent, so if it is a 80mm paper, you should not have esc/pos compatibility trouble.

We don't have a unofficial list. But Espon printers should work. We had some trouble with TM-T88V in v13.0 because the printer was named 'UNKNOWN' but with next box image, the printer named 'UNKNOWN' and connected in USB, will be added.

**Comment by gregory-moka** [comment]
I bought one on them, I'll try the compatibility of the printer, I'll keep you in touch.

**Comment by pimodoo** [comment]
OK, thank, w've ordered one too, so if it is not compatible we'll probably fix the box to handle it

**Comment by gregory-moka** [comment]
@pimodoo : Epson TMT20III has been recieved this morning, and works fine with Iotbox 19.12

**Comment by pimodoo** [comment]
@gregory-moka Thank you very much for your feedback.

@lca-odoo @lap-odoo FYI
