### ISSUE TITLE
What is the best practice to create users via API?

### ISSUE THREAD

**Issue by Jaquedeveloper** [odoo/odoo#46613]
I am building a mobile app which uses users and Odoo backend. 
The user should be able to create an Odoo user account via this app.
I can connect with the API and create a user but I am concerned about security issues.

If the user already have an account, he should connect to the backend using his credentials (login and password). If not, he should be able to create an account.

Currently the user is allowed to create new users and I can do that via API, with this "global" user, which I use to connect to the backend and create the real user account. Afterwards, the user which created the account is able to login with his own credentials and consume other services.

What is the best practice to use in this case?

Should I create a token or something to ensure the App is being accessed via device or to avoid possible hacker attacks e.g. creating a bunch of fake users, by discovering the database name, server and password, by faking the App use?

What should I implement to avoid this security issue?

This is most likely a Software Architecture question. Any help is appreciated.
Thank you.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by marcos-mendez** [comment]
@Jaquedeveloper Odoo.com forum is kind a useless they don't help that much the cummunity now a days because. Better is the odoo-community.org forum and also https://t.me/odoobr
