### ISSUE TITLE
[13.0] Marketing email changes are not visible after form has been saved

### ISSUE THREAD

**Issue by salmemik** [odoo/odoo#46618]
Impacted versions: 13 Community

Steps to reproduce:
- Go to Email Marketing module
- Create new marketing email
- Select template, add Subject and mailing list
- Save template
- Open Draft template again for editing and do changes (e.g. add images and texts)
- Save template - **Changes are not visible**
- Open template again - **Previous changes are still visible in edit mode**
- Warning "Wysiwyg immediate iframe double load detected" can be seen in Web Inspector

I retested this by installing Odoo 13 community to new Ubuntu 18.04 server on Sunday 1st March using this script: [https://github.com/Yenthe666/InstallScript/tree/13.0](https://github.com/Yenthe666/InstallScript/tree/13.0)

Video/Screenshot link (optional):

Changes are visible in edit mode:
![marketing email changes in edit mode](https://user-images.githubusercontent.com/11749898/75633222-cbb12000-5c0b-11ea-8053-fb288be7fa92.jpg)

But not after saving the changes:
![marketing email changes are not visible after form saved](https://user-images.githubusercontent.com/11749898/75633237-e2577700-5c0b-11ea-9625-bb9fc40a7f32.jpg)

**Comment by salmemik** [comment]
Very quick and easy to reproduce in runbot infrastructure ([http://runbot.odoo.com/runbot](http://runbot.odoo.com/runbot) - admin/admin). I tested & reproduced issue using both 13.0 and master branches. I tested with Safari and Chrome - same behaviour.

**Comment by salmemik** [comment]
Workaround: marketing email can be created if all is done correctly at once. Changes that are created before first saving will be visible also after saving.

**Comment by jcontrera87** [comment]
I have the same problem, some solution, I am in an emergency with this case, please

**Comment by salmemik** [comment]
I updated the server and Odoo and this issue does not exist anymore ==> I will close the issue.
