### ISSUE TITLE
[13.0] Incorrect cost of goods sold calculation on Anglo-saxon accounting with FIFO and Automated Inventory Valuation

### ISSUE THREAD

**Issue by abdullah-netlinks** [odoo/odoo#46615]
Impacted versions:
13

Steps to reproduce:

1. Activate 'Anglo-Saxon' accounting from Accounting > Settings.
2. Create a storable product with a cost price of $10, and assign a product category that has the following configuration:
a. Costing Method: FIFO
b. Inventory Valuation: Automated
c. Force Removal Strategy: FIFO
d. Setup the stock input, valuation and output accounts, as well as the product category's income and expense accounts. Make sure the cost of goods sold account is set in the 'expense account'.
3. Process a purchase order for the product created/configured, with a Qty of 5 and a unit cost of $8. Create and post the bill, and process the inventory receipt.
4. Process a purchase order for the same product, with a Qty of 8 and a unit cost of $12. Create and post the bill, and process the inventory receipt.
5. Process a sales order with a Qty of 1 for unit sales price of $20. Create and post the invoice, and process the delivery order. 
6. Process a sales order with a Qty of 6 and a unit sales price of $20. Create and post the invoice, and process the delivery order.
7. Check the Profit and Loss report

Current behavior:
For the second sales transaction (step 6), the system posts journal entry with a cost of goods sold amount equal to $48 (6 units @ $8).

Expected behavior:
For the second sales transaction (step 6), the system should post a journal entry with cost of goods sold amount equal to $56 (4 units @ $8) + (2 units @ $12)

Additional Notes and Observations:

- The system appears to pickup the cost price from the product form - which is updated by the removal strategy set. The fact that the cost price is picked up by the system from the product form leads the system to consider only one cost rate, while in reality - the sales transaction involves sales of products coming from 2 batches with different unit costs. Perhaps this is where the system needs to look at the unit cost in the related purchase order/bill instead of the product form?

- The inventory valuation for these transactions is done accurately, and Odoo appears to post the difference between the cost of goods sold price, and the inventory valuation to the Stock output account.

**Comment by oma-odoo** [comment]
Hi @abdullah-netlinks 
I have just tested on a V13.0 Runbot and the COGS entry for the second sale was well showing a debit of 56$, taking both cost prices ($8 & $12) into account.
In your test, did you well validate the second delivery order before creating the corresponding invoice? In case the product stock move hasn't been validated, it doesn't have any value and Odoo falls back on the standard price of the product form (which seems to be the case you are in here). 
Thank you and have a nice day

**Comment by abdullah-netlinks** [comment]
Thank you very much @oma-odoo.

I was indeed processing the bill before validating the delivery order, thinking that it was not relevant. Doing the reverse and now it is working as expected.

**Comment by nadunweediyage** [comment]
Hi, I am using Odoo Enterprise version and our business is in F&B. We use a third party PoS and extract data and upload sales invoices through odoo import feature.

The COGS entry currently recorded does seems to tie up with BOM or any other relevant number.

For example, Invoice INV-21-02-000060-IDRT has [FGFDMCBE002] item with sales quantity of 10 units. The BoM cost for this item is IDR 40,874.83. So I believe the amount that should capture in Invoice journal (GL entry) is 40,874.83 x 10 units = IDR 408,748.30. But what appears in invoice journal is IDR 1,950,169.95 and I am uncertain where these numbers are coming from.

![image](https://user-images.githubusercontent.com/80756395/111299529-9c3c4c80-8682-11eb-80e3-b4c983a74f57.png)

![image](https://user-images.githubusercontent.com/80756395/111299735-df96bb00-8682-11eb-8a4a-2825bcc27c19.png)

![image](https://user-images.githubusercontent.com/80756395/111299907-14a30d80-8683-11eb-9878-3bdbdf20b927.png)

![image](https://user-images.githubusercontent.com/80756395/111299918-18369480-8683-11eb-8fd9-34fdc21e36e3.png)

For this item inventory is valued at AVCO and automated. I am not quite sure where the numbers are coming from. Is there anyone who can help me in figuring this out.

Thank you so much

**Comment by nadunweediyage** [comment]
> Hi, I am using Odoo Enterprise version and our business is in F&B. We use a third party PoS and extract data and upload sales invoices through odoo import feature.
> 
> The COGS entry currently recorded does seems to tie up with BOM or any other relevant number.
> 
> For example, Invoice INV-21-02-000060-IDRT has [FGFDMCBE002] item with sales quantity of 10 units. The BoM cost for this item is IDR 40,874.83. So I believe the amount that should capture in Invoice journal (GL entry) is 40,874.83 x 10 units = IDR 408,748.30. But what appears in invoice journal is IDR 1,950,169.95 and I am uncertain where these numbers are coming from.
> 
> ![image](https://user-images.githubusercontent.com/80756395/111299529-9c3c4c80-8682-11eb-80e3-b4c983a74f57.png)
> 
> ![image](https://user-images.githubusercontent.com/80756395/111299735-df96bb00-8682-11eb-8a4a-2825bcc27c19.png)
> 
> ![image](https://user-images.githubusercontent.com/80756395/111299907-14a30d80-8683-11eb-9878-3bdbdf20b927.png)
> 
> ![image](https://user-images.githubusercontent.com/80756395/111299918-18369480-8683-11eb-8fd9-34fdc21e36e3.png)
> 
> For this item inventory is valued at AVCO and automated. I am not quite sure where the numbers are coming from. Is there anyone who can help me in figuring this out.
> 
> Thank you so much

After 1.5 years and with paid license, this is not yet resolved. Its pretty frustrating when it takes this long to resolve the issue
