### ISSUE TITLE
[12.0] summernote issue saveCroppedImages not a function

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#46638]
Impacted versions: 12.0

Steps to reproduce:
Add new activity on sale order or whatever
Current behavior:
it raise an error:
```
Error:
TypeError: this._summernoteManager.saveCroppedImages is not a function. (In 'this._summernoteManager.saveCroppedImages(this.$content)', 'this._summernoteManager.saveCroppedImages' is undefined)

https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:2439
Traceback:
commitChanges@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:2439:91
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3538:493
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:13:278
commitChanges@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1574:172
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:802:686
fire@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:796:304
add@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:797:471
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:802:649
each@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:625:771
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:802:564
Deferred@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:803:198
then@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:802:533
saveRecord@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1561:1060
saveRecord@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1671:371
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3538:493
saveAndExecuteAction@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1678:544
_onButtonClicked@https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1679:360
trigger@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3641:185
_trigger_up@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3647:385
_trigger_up@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3647:473
trigger_up@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:3647:291
https://www.mydomain.it/web/content/11649-39fa4dc/web.assets_backend.js:1633:314
dispatch@https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:892:456
https://www.mydomain.it/web/content/11231-5b2d131/web.assets_common.js:865:178
```

It seem due to: 
https://github.com/odoo/odoo/blob/4343ab0b79ed381cd5583d8189725f8317e7d71f/addons/web_editor/static/src/js/backend/fields.js#L60

Expected behavior: no error should be raised

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you updated all your local cached JS (with Ctrl+F5 or equivalent)? Is this reproducible on runbot?

**Comment by GSLabIt** [comment]
@pedrobaeza restarted again odoo, cleared cache and now is working. Thx for hint and sorry for the noise.

**Comment by pedrobaeza** [comment]
Why reopening?

**Comment by GSLabIt** [comment]
@pedrobaeza sorry reopened cause getting it wizard. Restarted again odoo, tested on firefox private window. See recording:  https://recordit.co/pgLBW8i2Nz

**Comment by pedrobaeza** [comment]
Please try on runbot to check if it's reproducible. If not, there's something different on your end or a custom module.

**Comment by GSLabIt** [comment]
@pedrobaeza link to runbot?

**Comment by pedrobaeza** [comment]
https://runbot.odoo.com

**Comment by GSLabIt** [comment]
@pedrobaeza error confirmed in custom module, sorry again for the noise.

**Comment by gacalixto** [comment]
I'm having a similar problem, when trying to create a new record on my custom_module
error:
`Uncaught TypeError: this._summernoteManager.saveCroppedImages is not a function
http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427
Traceback:
TypeError: this._summernoteManager.saveCroppedImages is not a function
    at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:2427:74)
    at Class.prototype.<computed> [as commitChanges] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:3538:488)
    at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:235
    at Function._.map._.collect (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:13:270)
    at Class.commitChanges (http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1574:169)
    at http://odoo.meucpd.com.br:8069/web/content/1355-29fc60c/web.assets_backend.js:1561:1093
    at http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:681
    at fire (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:796:299)
    at Object.add [as done] (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:797:467)
    at Array.<anonymous> (http://odoo.meucpd.com.br:8069/web/content/356-15f025e/web.assets_common.js:802:649)`


yesterday it was working fine

**Comment by sdegueldre** [comment]
@gacalixto have you tried emptying your cache and seeing if that fixes it? I can't reproduce this locally. This code path is hit when saving a `FieldTextHtmlSimple`, for example when saving a project task, but I'm not getting any error on my side.

**Comment by craigedmunds** [comment]
I've noticed the same error message after updating from a november 19 build, to yesterdays nightly.

Weirdly, setting debug=assets solves it for me.

**Comment by sdegueldre** [comment]
@craigedmunds have you tried to regenerate the asset bundles and see if that fixes it outside of debug=assets? I have a hunch that this is a problem with assets invalidation that didn't occur correctly.

**Comment by maitaoriana** [comment]
@craigedmunds The same thing happened to me and I did what @sdegueldre  suggested and it can be solved by activating debbug=assets and regenerate assets bundles

![Odoo (1)](https://user-images.githubusercontent.com/17258001/78049869-f77e0d80-7351-11ea-8c4a-fcb19c700826.png)

**Comment by craigedmunds** [comment]
Yes, that worked for me too - apologies - didn’t realise that was a thing!
