### ISSUE TITLE
werkzeug does not start with parameter "--no-xmlrpc"

### ISSUE THREAD

**Issue by baumgaro** [odoo/odoo#4666]
Impacted versions:

 - 8.0 - Commit 88ace35fa43d253e514f76d6f3053c6cffe1e959 

Steps to reproduce:

 1. Start Odoo Server with Parameter --no-xmlrpc

Current behavior:
this line will not appear in the Log:
2015-01-13 10:47:24,723 16949 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069

Expected behavior:
this line should appear in the Log - and it did in previous version of 8.0
2015-01-13 10:47:24,723 16949 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069

**Comment by xmo-odoo** [comment]
That's the expected behaviour, all "xmlrpc" options are actually HTTP options (`--xmlrpc-interface` and `--xmlrpc-port` are the HTTP host and port).

The `--no-xmlrpc` option was previously completely non-functional and had been "lost" for some time.
