### ISSUE TITLE
Manufacturing order in Unit(s) when product is other UOM incorrect reservation

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#46686]
Impacted versions:
12.0
Steps to reproduce:
Create new database using demo data
install manufacturing module
Create Product A with default uom of Dozen(s)
Create PO and receive 10 Dozen(s)
Create Product B set to manufacture
Create BOM for product B using a single component of 1 Unit(s)
Check Availability
Current behavior:
Reserved qty shows 0.960 Unit(s)
Expected behavior:
Reserved qty shows 1 Unit(s)
![2020-03-03_01-30-58](https://user-images.githubusercontent.com/1051273/75752635-c1b41d80-5cee-11ea-96fa-721cc4668d3f.png)

Video/Screenshot link (optional):

**Comment by aliomattux** [comment]
Check also production of goods seems messed up
![2020-03-03_01-34-50](https://user-images.githubusercontent.com/1051273/75752904-3e46fc00-5cef-11ea-9d02-7b4a8d6cb2be.png)

**Comment by sle-odoo** [comment]
it just seems to me you have a decimal accuracy of product unit of measures too small, just set it to 3 decimals and it'll be ok. you have to be able to go back and forth between dozens and unit.

**Comment by kos94ok-3D** [comment]
@sle-odoo 
[runbot](http://1602335-12-0-513930.runbot24.odoo.com/web?debug=1#id=5&action=607&model=mrp.production&view_type=form&menu_id=417)
![изображение](https://user-images.githubusercontent.com/33932458/75792971-5e220280-5d77-11ea-98a3-36ee09e8696b.png)
![изображение](https://user-images.githubusercontent.com/33932458/75793000-6712d400-5d77-11ea-89c5-b4abec7f9cfe.png)
![изображение](https://user-images.githubusercontent.com/33932458/75793064-7eea5800-5d77-11ea-8b0f-72cb44cf7b34.png)

**Comment by aliomattux** [comment]
I don't understand the response for 2 reasons.

1. I used only the demo data. If what you say is true, there is a problem with the core code defaults. Your saying that the new database was initialized using incorrect values

2. The decimal accuracy help suggests to use a value of 1 when it is a unit.

**Comment by sle-odoo** [comment]
well there's not even an issue here? you can reserve and unreserve without problems right? about 2, i think you're confusing uom rounding and decimal accuracy.

your product is in dozen, the quant is in dozen, you're reserving 1/12 which is truncated to 3 decimals before being converted to unit, that's why it's not exactly 1.0

**Comment by aliomattux** [comment]
I don't understand why your saying it isn't an issue. I should be able to create a manufacturing order for 1 unit when the product is stocked as a 12 pack.

The manufacturing order in my screenshot shows the uom represented as a unit, not a 12 pack. I understand the system behavior that even though I request a unit, it reserves a partial of a quant, but if thats the case then the manufacturing order should not show 1 unit because it isn't represented that way.

**Comment by aliomattux** [comment]
The quant shows 0.625 which is 1/12 but the manufacturing screen and the consume materials screen shows 0.960. To me that doesn't make sense.

**Comment by sle-odoo** [comment]
so you reserved one unit on a dozen
1/12 dozen = 0.083 dozen (truncated with 3 decimals)
1 dozen = 12 units
0.083 * 12 = 0.996 units

now the same thing when truncating with 2 decimals (which seems to be the default in your database?)
1/12 dozen = 0.08
1 dozen = 12 units
0.08 * 12 = 0.96 units

**Comment by sle-odoo** [comment]
i'd suggest to set the uom of the product as unit and the purchase uom as dozen, it seems to fit your needs and will prevent this kind of rounding issues
