### ISSUE TITLE
MissingError Message when adding Delivery Method to Quotation

### ISSUE THREAD

**Issue by johnpotter7** [odoo/odoo#4672]
Impacted versions:
- 8.0 sometime after 20/11/14.

Steps to reproduce:
1. In Sales menu, select a Customer,
2. Click on the Sales box within the Customer record, 
3. Click on Create in the Quotations and Sales list view, 
4. In the Quotation form click on the Delivery Method, 

Current behaviour: 
"MissingError - One of the documents you are trying to access has been deleted, please try again after refreshing." displayed in Odoo warning window.

Expected behaviour:
Delivery Methods displayed in drop down list.

Current workaround:  Do not create Quotation from within Customer record, i.e.
1. In Sales menu, select Quotations, 
2. Click on Create in the Quotations list view,
3. In the Quotation form click on the Delivery Method, 
    Delivery Methods are displayed in the drop down list as expected.

This error appears to have been introduced into v8 fairly recently as the issue doesn't occur in my previous build dated 20th November 2014.

Odoo v8 application installed from Github source 13/01/2015 running on Ubuntu 14.04.1 LTS.

**Comment by Yenthe666** [comment]
Hi @johnpotter7,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
