### ISSUE TITLE
Error when link User to Employee.

### ISSUE THREAD

**Issue by FaTaToo** [odoo/odoo#46730]
Impacted versions: 13.0

Steps to reproduce:
- From menu `Employees > Employees > Employees`, create new employee without user information (**Related User** is empty).
- From menu `Settings > Users & Companies > Users`, create new user.
- On Employee form view, set **Related User** is created user.

Current behavior:
- Value of field **Related User** is changed to empty.
Expected behavior:
- Value of field **Related User** should not changed to empty.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I have just recreated your steps without problems:

![Peek 03-03-2020 14-21](https://user-images.githubusercontent.com/7165771/75779659-4ab46e80-5d5a-11ea-8cd6-28ca9a5333fe.gif)

so maybe you have something wrong in your end. Update source code and be sure no custom module is breaking this. Closing now as no apparent issue.

**Comment by FaTaToo** [comment]
> I have just recreated your steps without problems:
> 
> ![Peek 03-03-2020 14-21](https://user-images.githubusercontent.com/7165771/75779659-4ab46e80-5d5a-11ea-8cd6-28ca9a5333fe.gif)
> 
> so maybe you have something wrong in your end. Update source code and be sure no custom module is breaking this. Closing now as no apparent issue.

Thanks you for your support. I forgot to update source code.

**Comment by FaTaToo** [comment]
I updated the source code and it work fine now. Thanks to commit _136c0dbea0ab00ff27daac69c27dc0824a16ff70_ of **Yannick Tivisse** :D
