### ISSUE TITLE
[V8] Sign up doesn''t work the classic way with Google autho active

### ISSUE THREAD

**Issue by sharkutz** [odoo/odoo#4679]
Impacted versions:
 -8.0 and above
Steps to reproduce:

 1. Install, configure and setup Login with google from settings/ General settings tab.
2.Go to your website 
 3. Go to Sign in page and click Sign up
 4. Create user from backend and request the user to click the activation link

Current behavior:
In both cases you are redirected to Google OAuth2 request. You can't create a new user and the user can't validate his account from the activation link because he is redirected to Google OAuth2 procedure.

Expected behavior:
Classic Sign up should be available when Log in with Google is active.
Users that are created from the backend should be capable to activate they account from the activation link sent to their email address.

**Comment by sharkutz** [comment]
Reset password doesn't work either!

**Comment by gghordijk** [comment]
I can confirm.

Google Oauth2 does not play nicely with the normal user sign-up and password reset.

**Comment by metaminux** [comment]
I think the same behaviour happens for all OAuth providers (Odoo.com, Facebook Graph and Google OAuth2 in v8).

It seems installing auth_oauth module and activating only one provider leads to disabling the "normal" (login / password) sign up and password reset features.

As I understand it, web_auth_signup and web_auth_reset_password methods from OAuthLogin class (defined in auth_oauth/controllers/main.py) are automatically redirecting if list_providers returns only one result (normal authentication isn't considered as a provider, of course)

Am I wrong ? Can someone tell me why is this issue closed ?

**Comment by sharkutz** [comment]
For me it works now!
