### ISSUE TITLE
Invalidating all model caches after database signaling with multi processing.

### ISSUE THREAD

**Issue by smurf-U** [odoo/odoo#46808]
**Impacted versions:**
Odoo v11 EE with user < 50
ubuntu 16.04
Python 3.5.2

Data files and code repository share with shared EFS among all server.
All server connected through one AWS ALB.

# Total Web server (EC2 c5.xlarge: 4 CPU, 8 GB RAM) * 3 
# Tuning Options
workers = 5
max_cron_threads = 0
limit_memory_hard = 2300000000
limit_memory_soft = 1300000000
limit_request = 9000
limit_time_cpu = 5400
limit_time_real = 5400
osv_memory_age_limit = 1.0
osv_memory_count_limit = False

# Total Cron server (EC2 c5.xlarge: 4 CPU, 8 GB RAM) * 3 
# Tuning Options
workers = 0
max_cron_threads = 5
limit_memory_hard = 2300000000
limit_memory_soft = 1300000000
limit_request = 9000
limit_time_cpu = 5400
limit_time_real = 5400
osv_memory_age_limit = 1.0
osv_memory_count_limit = False

**Current behaviour:**

On webserver after some time (1 hour, 2 Hour, 4 Hour, etc. [random pattern]) one by one server goes in `Invalidating all model caches after database signalling` looping in timeout and one by one worker goes down and not responding until restart service manually.

Cron server works fine with around 100 of active crons.

Please check below log. Also attached last 30 min log in the file.
[odoo.log](https://github.com/odoo/odoo/files/4283689/odoo.log)

> Mar 2 00:28:46 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105370]
Mar 2 00:28:56 odoo-web2 odoo-server.log DEBUG 30841 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105370]
Mar 2 00:28:57 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105370]
Mar 2 00:28:57 odoo-web2 odoo-server.log DEBUG 30841 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105370]
Mar 2 00:29:01 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105370]
Mar 2 00:29:13 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105371]
Mar 2 00:29:13 odoo-web2 odoo-server.log INFO 29610 INFO namastetech_production odoo.modules.registry: Invalidating all model caches after database signaling.
Mar 2 00:29:13 odoo-web2 odoo-server.log DEBUG 27539 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105370 -> 105371]
Mar 2 00:29:13 odoo-web2 odoo-server.log INFO 27539 INFO namastetech_production odoo.modules.registry: Invalidating all model caches after database signaling.
Mar 2 00:29:17 odoo-web2 odoo-server.log DEBUG 27539 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:27 odoo-web2 odoo-server.log DEBUG 27539 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:27 odoo-web2 odoo-server.log DEBUG 27539 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:27 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:31 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:41 odoo-web2 odoo-server.log DEBUG 27539 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:42 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]
Mar 2 00:29:42 odoo-web2 odoo-server.log DEBUG 29610 DEBUG namastetech_production odoo.modules.registry: Multiprocess signaling check: [Registry - 459 -> 459] [Cache - 105371 -> 105371]

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a deployment question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by ghhamza** [comment]
hi @smurf-U did you find the source of this problem?
