### ISSUE TITLE
Quotation from Webshop without product.name

### ISSUE THREAD

**Issue by guggenbergerl** [odoo/odoo#4680]
At the product master data I added in the sale tap a description for quotations.
![screen1](https://cloud.githubusercontent.com/assets/8057352/5728315/a6ffd53e-9b69-11e4-8f51-39866694ab9f.png)

If I create a quotation or sale order with the module sale, in the description of the product the product name and the description for quotation is shown. What is absolutely correct.
![screen2](https://cloud.githubusercontent.com/assets/8057352/5728406/42b3c36e-9b6a-11e4-9257-1c33d72c66ab.png)

In addons/sale/sale.py beginning at line 1091 the product.name is concatenated with product.description_sale:

```
            result['name'] = self.pool.get('product.product').name_get(cr, uid, [product_obj.id], context=context_partner)[0][1]
            if product_obj.description_sale:
                result['name'] += '\n'+product_obj.description_sale
```

But if I create the same order in the webshop (module website_sale) the product name is missing in the description of the product.
![screen3](https://cloud.githubusercontent.com/assets/8057352/5728464/b0b0909a-9b6a-11e4-8f03-c1140718dfc6.png)

In addons/website_sale/models/sale_order.py beginning at line 61 the code following:

```
            product = self.pool.get('product.product').browse(cr, uid, product_id, context=context)
            values['name'] = product.description_sale or product.name
```

At this point the concatenation from product.name and product.description_sale is missing. Is it possible to add this if a product.description_sale is averrable (same as it is in the sale module)?

Thanks a lot!

**Comment by guggenbergerl** [comment]
When will this issue be solved in Odoo v8? This issue is open now more than a half year.

**Comment by Yenthe666** [comment]
Hi @guggenbergerl,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
