### ISSUE TITLE
8.0 new API issue on duplicate with readonly related fields

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4681]
I think I found an issue in the new API when doing a copy() on an object that has a related field with readonly=True: odoo tries to make a write on the object on which the related field points to, but it shouldn't (this a problem because the user may not have write access on that object on which the readonly related field points to).

Here is a simple scenario to illustrate the problem on an up-to-date odoo v8 from github:
1) bzr branch lp:philemon
and add "philemon" to your addons_path
2) Create a new DB with demo data
3) install the module donation_recurring
4) logout and login as demo user
5) go to the menu Donation > Generate Recurring Donations. In this wizard, click on "Generate": you will get the following error message: 

```
Sorry, you are not allowed to modify this document. Only users with the following access level are currently allowed to do that:
- Administration/Access Rights
(Document model: res.company)
```
In the logs, you have:
```
2015-01-13 17:20:12,770 21492 WARNING o8_bugunaccent openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: write, uid: 4, model: res.company
```
Code analysis of the problem:
On the donation.donation object, there is a readonly related field company_currency_id (cf donation/donation.py line 144)

```
    company_currency_id = fields.Many2one(
        related='company_id.currency_id', string="Company Currency",
        readonly=True)
```

In the wizard to generate recurring donations, in donation_recurring/wizard/donation_recurring_generate.py on line 63, the donation object is duplicated:
```
        new_donation = donation.copy(default=default)
```
This call to copy() will trigger a write() on res.company with vals = {'currency_id': 1}. But the demo user doesn't have write access on res.company, which raises the error. I don't see any good reason to make a write on the currency_id field of res.company following a copy() of a donation that has a readonly related field "company_id.currency_id". So I think it's a bug in the new API.

**Comment by alexis-via** [comment]
In fact, if you want the proof that this bug is NOT present with the OLD API, you can try the same scenario with  lp:philemon in revno 77 (before the port to the new API ; note that you will have to manually add the demo user to the "Donation / User" group with this version) : you will not have any access rights issue with this version.

**Comment by rco-odoo** [comment]
@alexis-via Can you give a try to my patch e3bd0c2 above?

**Comment by alexis-via** [comment]
@rco-odoo I tried your patch e3bd0c2 and I confirm that it solves this bug. THANK YOU VERY MUCH for your fix Raphaël.

**Comment by rco-odoo** [comment]
@alexis-via you are welcome.
The pull request is going to be merged in a few minutes.
