### ISSUE TITLE
[ODOO12] Translation of computed field is not working properly

### ISSUE THREAD

**Issue by mucahitaz** [odoo/odoo#46812]
Impacted versions: ODOO12

Steps to reproduce: Create a computed field with python .format , for example: 
```
@api.depends('start_date')
    def _calculate_waiting_time(self):
        for rec in self:
            if rec.state == 'b_in_progress' or 'c_approval' or 'd_closed':
                diff = delta(rec.start_date, rec.create_date)
                rec.waiting_date = _('{} days {} hours'.format(diff.days, diff.hours))
                return rec.waiting_date
```

then translate it with poedit or by-hand , load your translation file then check your field.

Current behavior:Translation is not working as expected.  It is ignoring the field in po file. Field is still shown as "0 days 0 hours" on screen.

Expected behavior: Translation should work as expected and field language supposed to be Turkish. It has to show "0 gün 0 saat" on screen.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/51249755/75849158-3ec9ba80-5df5-11ea-82c6-a2424c279d56.png)

**Comment by pedrobaeza** [comment]
Is the field stored?

**Comment by mucahitaz** [comment]
> Is the field stored?

No it is not a stored field.

**Comment by pedrobaeza** [comment]
And it's `compute_sudo`? I'm asking because this works OK if none of those 2 cases or you change your language on the fly. Take into account that there's a cache that stores temporarily the result values for performance.

**Comment by mucahitaz** [comment]
> And it's `compute_sudo`? I'm asking because this works OK if none of those 2 cases or you change your language on the fly. Take into account that there's a cache that stores temporarily the result values for performance.

My field is:
`    waiting_date = fields.Char('Time Waited', compute='_calculate_waiting_time')
`
I don't know what you mean by 'compute_sudo' I have never used that, I have also cleared my browser cache but it does not seem to work.

**Comment by pedrobaeza** [comment]
Well, as said, that is working, so you should check on your end if there's something incorrect, like the translations load, or ask on the forums about the problem, but I'm closing this as no real issue.
