### ISSUE TITLE
Error unreconcile with exchange

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#4683]
1) Steps to reproduce the issue you have observed 
1.- Configurate currency company to EUR
2.- Create a register to rate in USD to the 2015/01/01 and 2015/01/13
3.- Create a supplier invoice with USD, and with date for 2015/01/01 and validate
4.- Create your payment, with date of today and validate
5.- You unreconcile the payment

Can find a demonstrative video here:
http://youtu.be/x9OWCWe_Gic

2) The result you observed
I can not unreconcile the payment

 3) The result you expected 
Can Cancel the voucher

4.- Odoo version
8.0
commit: ec25207b8fc961246444abcbdc3a6f96048fc6c8

**Comment by Yenthe666** [comment]
Hi @luistorresm,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
