### ISSUE TITLE
[8.0] One2many write error with _inherits

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#4685]
@rco-odoo 
Version 8, 13 Jan 2015

Problem:
The below code is "set" method from fields.one2many in osv/fields.py
It uses sql statement to double check if the link is already created.

It will fail if self._fields_id is inherited(using _inherits) from parent model. In the case, self._fields_id is a related field and not exist in database table. Therefore postgresql will raise error saying _fields_id is not found.

```python
    elif act[0] == 4:
                # table of the field (parent_model in case of inherit)
                field = obj.pool[self._obj]._fields[self._fields_id]
                field_model = field.base_field.model_name
                field_table = obj.pool[field_model]._table
                cr.execute("select 1 from {0} where id=%s and {1}=%s".format(field_table, self._fields_id), (act[1], id))
                if not cr.fetchone():
                    # Must use write() to recompute parent_store structure if needed and check access rules
                    obj.write(cr, user, [act[1]], {self._fields_id:id}, context=context or {})
```

**Comment by rco-odoo** [comment]
The code you mention never fails.
The query uses the right table: if the field is inherited, `field.base_field.model_name` is the actual model that has the field.

**Comment by auyeung112002** [comment]
@rco-odoo 

Normal setting without _inherits and all fields are stored:
 - on model mother, field one2many daughter_ids go to model daughter, with inverse field mother_id

execute: self.pool.get('mother').write(cr, uid, 123, {'daughter_ids':[(4,456)]})
The checking will be: select 1 from daughter where id=456 and mother_id=123
It is correct.


Consider the following setting with _inherits:
 - on model mother, field one2many granddaughter_ids to model granddaughter, with inverse field mother_id
 - on model granddaughter, field many2one mother_id is inherited (_inherits: {'daughter' : 'daughter_id'}) from model daughter
 - on model daughter, field many2one mother_id(to model mother) is stored

execute: self.pool.get('mother').write(cr, uid, 123, {'granddaughter_ids':[(4,456)]})
the checking will be: select 1 from daughter where id=456 and mother_id=123

It is totally different from the normal case and this check is irrelevant. The code will not raise exception but it will either call unnecessary write method(in most cases) or not change the inverse field as intended(rare case, happen when this statement return 1 by accident)

I think the correct checking should be: select 1 from granddaughter join daughter on granddaughter.daughter_id=daughter.id where granddaughter.id=456 and daughter.mother_id=123

**Comment by rco-odoo** [comment]
@auyeung112002 Damn it!  You are absolutely right, I did not pay attention to the condition on the `id` field.  Thanks for the explanation, I will try to fix this.

**Comment by auyeung112002** [comment]
Thank you very much!
