### ISSUE TITLE
POS > Multi currency

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#46875]
**Impacted versions:**
12.0

**Steps to reproduce:**
In general settings : Multi currency unchecked
In Point of sale settings : "Cash control" checked

**Current behavior:**
Open a POS session (on this POS) > A message concerning multi currency is displayed.

**Expected behavior:**
If Multi currency is not activated on the instance, POS should not display this message, cause nothing will be found concerning multi currency on the Cash register tab.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/45974412/75880266-3b4a2980-5e1d-11ea-84e0-06aa92e0d621.png)

**Comment by pimodoo** [comment]
@gregory-moka Hekko this massage has been removed in 13.0 in commit: https://github.com/odoo/odoo/commit/0d9c36254fe47a0ca64f598251780cb03c6ddeb6

you can easily remove it in your database, but removing it in stable won't have positive or negative impact as it will only work for new database, and doesn't fix a real issue.
