### ISSUE TITLE
restrict_partner_id (i.e. stock owner) is never propagated to the backorder

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#4692]
The move has a field `restrict_partner_id` that is used when reserving quants. The `owner_id` field on the picking is mostly unused.

When creating a backorder, the `restrict_partner_id` is not copied, because the method `split` at 

https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2439

takes a `restrict_partner_id` parameter that is never passed along, so in the backorder the field is always empty. I think we should just copy it along with the other fields.

**Comment by beledouxdenis** [comment]
Closed with 3349187aab929cda9db320769831532ddd0b10cb.
