### ISSUE TITLE
[12.0] Error if you try send invoice without reference and partner email is not set

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#46928]
https://github.com/odoo/odoo/blob/cdd1439a380810569db80d984c8cb80d213b1bf3/addons/account/wizard/account_invoice_send.py#L60

>   File "/opt/odoo/auto/addons/account/wizard/account_invoice_send.py", line 60, in _compute_invoice_without_email
    "\n".join([i.reference for i in invoices])
TypeError: sequence item 0: expected str instance, bool found

**Comment by carlosdauden** [comment]
![Peek 04-03-2020 18-51](https://user-images.githubusercontent.com/7701001/75907810-44e98680-5e49-11ea-8f09-559f99bdf7f5.gif)

**Comment by pedrobaeza** [comment]
@qdp-odoo @oco-odoo something for your team.

**Comment by sswapnesh** [comment]
@carlosdauden @pedrobaeza  Maybe we should use `display_name` as a fallback. (But it will be Always `Invoice` if the Invoice is never Validated)

Added PR to fix this https://github.com/odoo/odoo/pull/47141



(Ps: Maybe we should display `Invoice (* id)`  (Like v13) but that won't be a `FIX` but `IMP`)

https://github.com/odoo/odoo/blob/ed459c1bcfa8104c4116da2d5767d5ea4457463d/addons/account/models/account_move.py#L1813

**Comment by oco-odoo** [comment]
Thank you for the feedback. I just approved @sswapnesh 's PR. It's currently being merged by our bot, so I'm closing the issue ;)
