### ISSUE TITLE
Running odoo behind apache/mod_proxy for SSL, odoo falls back to http on login, logout

### ISSUE THREAD

**Issue by jobe451** [odoo/odoo#4696]
I am using an apache webserver as reverse proxy (with mod_proxy) as an additional security layer. It enforces SSL encryption and requires a client certificate as additional identification element. Odoo however at some ocasions calls links with hardcoded HTTP, so calls start failing. I added below a screenshot below, that explains this better.

This occures always on logout as well when I try to switch dbs on the login screen.

Defining web.base.url and setting web.base.url.freeze to "True" does not help with this issue. 

I am running Version 8.0-4c19080.

![image](https://cloud.githubusercontent.com/assets/910027/5739162/f4fe493c-9bf5-11e4-8811-16ca69130ae5.png)

**Comment by Yenthe666** [comment]
Hi @jobe451,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
