### ISSUE TITLE
Uncheck "produce" on warehouse disallow the possibility of recording warehouse configuration (only non english languages)

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#4697]
Hi
We detected an annoying issue that only affects to environments where user languaje is not english.

Steps to reproduce the error:
1. check the "production" check on Warehouse and save
or
2. create a new warehouse cheking the production field.

This piece of code is looking for a hardcode "Manufacture" string, but, proccess is looking for translation, so it doesn't exists on system and warning screen is shown telling:
"It doesn't exists any default route with that name"
Stock route Manufacture exists, but system can not look for it, so... it's not possible to save the warehouse record but only to discard it.

```
try:
    manufacture_route_id = data_obj.get_object_reference(cr, uid, 'stock', 'route_warehouse0_manufacture')[1]
except:
    manufacture_route_id = route_obj.search(cr, uid, [('name', 'like', _('Manufacture'))], context=context)
    manufacture_route_id = manufacture_route_id and manufacture_route_id[0] or False
```

For anyone who is now surffering this extrange bug, quick solution is very simple. Just change user language to english, check the field, save and it's done. 
After that.  change again user language to his  own one.

But... if you want to apply a patch to solve it... we made one here:
https://github.com/odoomrp/odoomrp-wip/pull/564

**Comment by pedrobaeza** [comment]
To complement Ana's issue, the field name is not translatable, but the string looked for is translated. That's why the search fails. Anyway, it's very dangerous to look for a harcoded string that can be changed across the time. Isn't any other option (include a flag or something similar)?

**Comment by clonedagain** [comment]
That looks fixed, can someone confirm and close this issue please?

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
