### ISSUE TITLE
[8.0] Old/New API compatibility Error Into Test

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#4698]
**Old/New API compatibility Error**

Impacted versions:
- 8.0

Steps to reproduce:
1. Add a button into a form view of a model (no matter which). This button is type of object and the related method is "@api.multi" decorated
2. Into this method call the method `onchange_product_id` from purchase.order.line **into new API**
3. Click on this button: it will work and you'll receive as well the result.
4. Create a test for this method and call it into api.v8 form the test. (self.env.button_method())

Current behavior:
- the `onchange_product_id` crash during the call with a bad number of arguments (6 given/waiting 9)

Expected behavior:
- calling this method should run with wrapper but it seems that it is not called

Note:
@api.cr_uid_ids_context on onchange_product_id seems to fix the problem

**Comment by rco-odoo** [comment]
@JonathanNEMRY is this issue still present?
