### ISSUE TITLE
[8.0] Impossible to group invoices from delivery order

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#4700]
## Impacted versions:
- 8.0
## Steps to reproduce  (Quite long but necessary) :
- Go to runbot and open a v8.0 instance.
- Click on Sales menu.
- Open Customers submenu
- Click on Agrolait
- Click on Edit button
- Go on Accounting page
- Change 'Communication type' to BBA Structured Communication
- Set 'Communication Algorithm' to random
- Click on Save
- Go Quotations submenu
- Click on Create
- Select Agrolait for the customer
- Add a line with a stockable product
- Go on Other information page
- Change 'Create Invoice' to 'on delivery order'
- Click on save
- Click on Confirm Sale button
- Click on more menu and select duplicate option
- Go on other information page of the duplicate quotation
- Change Salesperson to Demo User
- Click on save
- Click on Confirm Sale button
- Click on warehouse menu
- Go on All operations and select Your company delivery order all operations
- Select the two delivery order created from the sale order that have been created before
- Click on more menu and select create draft invoices
- Check group by partner option
- Click on create 
## Expected behavior :
- Creation of some invoices
## Current behavior:
- An exception is raised : The BBA Structured Communication has already been used!
  Please create manually a unique BBA Structured Communication.

Thanks !

**Comment by adrienpeiffer** [comment]
ANy news about this issue ?

**Comment by adrienpeiffer** [comment]
OPW 628118

**Comment by adrienpeiffer** [comment]
Fix on #5292

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

This was fixed at https://github.com/odoo/odoo/commit/aac5c4798018e17fcd2d21cc56be381a1cd219b6 but the issue itself was never closed.

Regards,
Yenthe
