### ISSUE TITLE
Do you imply that only the `FormView` can have breadcrumbs?

### ISSUE THREAD

**Issue by hbrls** [odoo/odoo#4702]
[The source code: /addons/web/static/src/js/views.js#L751](https://github.com/odoo/odoo/blob/7727a31d1f1bb404047aae1692a3829a1d0253ae/addons/web/static/src/js/views.js#L751):

```
this.on('switch_mode', self, function(mode) {
    var last = views.slice(-1)[0];
    if (mode !== last) {
        if (mode !== 'form') {
            views.length = 0;
        }
    views.push(mode);
    }
});
```

For all views except `FormView`, it will clear out the "history tracing" of "view switching".

I think the implication of this behavior is that:
1. All views except `FormView` are some sort of "List of All Records", not of any kind of "Viewing a Single Record"
2. You can switch from a "ListView Variant A" to "FormView" with a breadcrumb
3. If you switch from a "ListView Variant A" to "ListView Variant B", it resets as if you were coming directly into "B"

I'm caught by this behavior, because I'm developing a "FormView Variant" for a single record.

**Comment by Yenthe666** [comment]
Hi @hbrls ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
