### ISSUE TITLE
[11.0][12.0][stock] stock_inventory: Odoo server error on Start Inventory

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#47034]
Impacted versions: 11.0, 12.0

Steps to reproduce:
1. Create a new Inventory Adjustments with Inventory of One product only
![изображение](https://user-images.githubusercontent.com/33932458/76008185-e6d7a480-5f17-11ea-8f4b-510b6a609665.png)
2. Then set Inventory of One Lot/Serial Number
![изображение](https://user-images.githubusercontent.com/33932458/76008338-29997c80-5f18-11ea-8347-323ff614cef7.png)
3. Press button Start Inventory

Current behavior:
![изображение](https://user-images.githubusercontent.com/33932458/76008459-58afee00-5f18-11ea-8086-29a7e9667f27.png)

Expected behavior:
Start Inventory for selected Lot/Serial Number

The problem found in these functions:
<pre>
    @api.onchange('filter')
    def onchange_filter(self):
        if self.filter not in ('product', 'product_owner'):
            self.product_id = False
        if self.filter != 'lot':
            self.lot_id = False
        if self.filter not in ('owner', 'product_owner'):
            self.partner_id = False
        if self.filter != 'pack':
            self.package_id = False
        if self.filter != 'category':
            self.category_id = False
        if self.filter == 'product':
            self.exhausted = True

    def _get_inventory_lines_values(self):
        ....
        if self.exhausted:
            exhausted_vals = self._get_exhausted_inventory_line(products_to_filter, quant_products)
            vals.extend(exhausted_vals)
        return vals
</pre>

Possible solution: 
1. Set exhausted = False in onchange_filter function
OR
2. Add advantage conditional in _get_inventory_lines_values function like this: 
<pre>
    def _get_inventory_lines_values(self):
        ...
        if self._allow_get_exhausted_line():
            exhausted_vals = self._get_exhausted_inventory_line(products_to_filter, quant_products)
            vals.extend(exhausted_vals)
        return vals

    def _allow_get_exhausted_line(self):
        return self.exhausted and self.filter not in ('owner', 'product_owner', 'lot', 'pack', 'partial')
</pre>

**Comment by pedrobaeza** [comment]
The message you get is because there's another inventory in progress, or am I missing something?

**Comment by sswapnesh** [comment]
I just found this constraints is messed in v11
See: https://github.com/odoo/odoo/commit/ba5918ffcbe5fe9155308c53e014e5e93c588ca6#commitcomment-34539038

**Comment by kos94ok-3D** [comment]
If you select One product only and then change on One Lot/Serial Number field exhausted will be True, but exhausted not supported for One Lot/Serial Number.
And field hiden but set True

**Comment by pedrobaeza** [comment]
If you have clear the solution, you can propose a PR with it.

**Comment by sswapnesh** [comment]
I can confirm this behavior on latest Runbot v12 
http://1637045-12-0-319ea5.runbot11.odoo.com/web?#id=6&action=386&model=stock.inventory&view_type=form&menu_id=278
