### ISSUE TITLE
[13] purchase: Missing 'Purchase Representative' on PO created from Replenish wizard

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#47045]
Impacted versions: 13.0

Steps to reproduce: 
Configure a Product with **Buy** Route and Assign **Vendors** to it
![image](https://user-images.githubusercontent.com/16624719/74170548-16fe9100-4c53-11ea-9efe-eab3ef3f8ff8.png)

Replenish this Product
![image](https://user-images.githubusercontent.com/16624719/74170616-34335f80-4c53-11ea-950e-6e6b97152987.png)

Current behavior:
Missing Purchase Representative

![image](https://user-images.githubusercontent.com/16624719/74170710-5d53f000-4c53-11ea-8444-074473ae5b92.png)

Expected behavior:
Purchase Representative should be set as "Administrator" (Current User)
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As there's a linked pull request, we can close this issue and follow in the PR.
