### ISSUE TITLE
Stock Forecast problem on Odoo12 Community

### ISSUE THREAD

**Issue by brunoffreire** [odoo/odoo#47044]
Impacted versions: 12

Steps to reproduce: The image attached to this issue can explain.
![ODOO](https://user-images.githubusercontent.com/15147281/76032330-682f3700-5f18-11ea-95f5-183e4276dfd3.png)

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why is wrong? The image doesn't explain anything...

**Comment by Yenthe666** [comment]
Please add reproducable steps on how to get to this amount which you say is invalid.

**Comment by sswapnesh** [comment]
IMO This can be closed
