### ISSUE TITLE
[8.0] account.statement.operation.template is not multi-company aware !

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4706]
The object account.statement.operation.template (used to display buttons in the new great JS interface to reconcile bank statements) is not multi-company aware ! When you defined a button with an account in company A and you reconcile a bank statement of company B, you will see the button and it won't work of course.

2 ideas for solutions:
1) add a field company_id on account.statement.operation.template (could be a related field on account_id.company_id) and add a record rule for account.statement.operation.template
2) or set the account_id field of account.statement.operation.template a fields.property.

I think that solution 1 is better than solution 2.

**Comment by nhomar** [comment]
+1 I have this issue also

**Comment by Whisno** [comment]
Oops, we implemented this in a V9 development branch where account.statement.operation.template becomes account.operation.template and can also be used in manual account reconciliation but I neglected to backport it.

How about the following ?
```
company_id = fields.Many2one('res.company', string='Company', required=True, default=lambda self: self.env.user.company_id)
```
I think using the user company as default (multicompany users can manually choose the company) is the most straightforward way to do it.

**Comment by alexis-via** [comment]
@Whisno I would have prefered:
```
company_id = fields.Many2one(related='account_id.company_id', string='Company', readonly=True, store=True)
```
because, that way, you are always sure that account_id.company_id == company_id, without the need for a constraint.
And then, you need to add an ir.rule on account.statement.operation.template

**Comment by Whisno** [comment]
Bad news everyone. We don't plan to change this in V8 because it would require to change the model, which we prefer to avoid.

However, the account.statement.operation.template was improved in master (multi-company aware and manually sortable), yet its purpose didn't change. So making a patch for V8 is probably just a matter of copy-pasting the model and the views for account.statement.operation.template.

**Comment by alexis-via** [comment]
OK, let's fix it in OCB then :)

**Comment by alexis-via** [comment]
I eventually decided to fix this bug in a dedicated module named "account_statement_operation_multicompany" that is available for v8 in this project: https://github.com/akretion/odoo-usability

Enjoy !

**Comment by Whisno** [comment]
:+1:

**Comment by alexis-via** [comment]
FYI, I just updated my module "account_statement_operation_multicompany" because my users reported an issue when trying to create new account.statement.operation.template after the installation of the module. So, if you have already installed the module, you should probably upgrade it.

**Comment by alexis-via** [comment]
My module account_statement_operation_multicompany is moving from akretion/odoo-usability to OCA/bank-statement-reconcile : for the moment, you can find it in this PR https://github.com/OCA/bank-statement-reconcile/pull/90

**Comment by sbidoul** [comment]
@alexis-via @Whisno after having slept a night on it, I was wondering if a simple record rule ```[('account_id.company_id', '=', user.company_id.id)]``` would do the job? 

It is less performant than the usual stored company_id field, but since the number of statement operation templates is small performance will not be an issue. 

Is adding such a rule is acceptable for stable policy?

**Comment by Whisno** [comment]
Unfortunately that wouldn't work since the account_id field is optional.
