### ISSUE TITLE
Product Variants filter

### ISSUE THREAD

**Issue by florinmarica** [odoo/odoo#47117]
Impacted versions:
13.2
Steps to reproduce:
- Create product with variants
- in  the shop:
- Enable Product Atribute's Filter
- filter by one attribute
- click on product 

Current behavior:
when the product is open is selected the first variant 

Expected behavior:
select the variant from search result

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
This has been discussed with @JKE-be before and this won't be changed. (Will add the reference once I found it)

**Comment by sswapnesh** [comment]
>Unfortunately, we have until now, no way to open a product page with a pre-defined variant selected.


Have a look at https://github.com/odoo/odoo/issues/22982 
(Its two years old Issue, Maybe we can have some updates on this from the feedback Registered)

**Comment by JKE-be** [comment]
Feature has been added in v13

Select a variant and you should see the url hash updated ...
You can share it directly and the correct variante should be selected

Kr

Jeremy Kersten

**Comment by sswapnesh** [comment]
> you should see the url hash updated 

Yes, It updates but still https://github.com/odoo/odoo/issues/22982 exists as it doesn't Open Pre-selected Variant from the Main Page
![](https://image.prntscr.com/image/6VQxdCX8SkCVaZVuQZemPg.png)

**Comment by JKE-be** [comment]
Yes didn’t check the issue
Just your comment.

I could check if possible if no performance cost.
In the past, it was just no possible to open a product product :)

**Comment by JKE-be** [comment]
@sswapnesh 

This diff should do what you want ... since more than 2 year ;)
```javascript
diff --git addons/website_sale/static/src/js/website_sale.js addons/website_sale/static/src/js/website_sale.js
index 6fd463d7f4e..9e94258e6d8 100644
--- addons/website_sale/static/src/js/website_sale.js
+++ addons/website_sale/static/src/js/website_sale.js
@@ -200,12 +200,29 @@ publicWidget.registry.WebsiteSale = publicWidget.Widget.extend(VariantMixin, {
         var self = this;
         var def = this._super.apply(this, arguments);
 
+
+        var params = $.deparam(location.search.slice(1));
+        if (params.attrib) {
+            var default_val = [];
+            var attribs = typeof params.attrib == "string" ? [params.attrib] : params.attrib;
+            attribs.forEach(function (att_comb) {
+                var att_comb_split = att_comb.split('-');
+                var att = att_comb_split[0];
+                var val = att_comb_split[1];
+                var value = self.$('.js_variant_change[name="ptal-' + att + '"][value="' + val + '"]').data('value_id')
+                value && default_val.push(value);
+            });
+            if (default_val.length) {
+                history.replaceState(undefined, undefined, '#attr=' + default_val.join(','));
+            }
+        }
         this._applyHash();

```


jquery selector probably to format to avoid xss and co... but the idea is there

**Comment by JKE-be** [comment]
@florinmarica 

Not considered as a bug, but could be an improvement...
Thanks for feedback

**Comment by florinmarica** [comment]
> @florinmarica
> 
> Not considered as a bug, but could be an improvement...
> Thanks for feedback

Thank you for the help. I manage to work around

**Comment by JKE-be** [comment]
@florinmarica 

You can probably patch locally using https://github.com/odoo/odoo/issues/47117#issuecomment-595910856 meanwhile a competent guy can say if we add it or not.
//cc @sbuhl

**Comment by florinmarica** [comment]
> @florinmarica
> 
> You can probably patch locally using [#47117 (comment)](https://github.com/odoo/odoo/issues/47117#issuecomment-595910856) meanwhile a competent guy can say if we add it or not.
> //cc @sbuhl

if you want, I made a module for this, I don't know if is done 100% right regarding the best practice. but I can share it.
