### ISSUE TITLE
Hard to create leave requests by employee tag

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#4713]
We are trying to book public holidays into the system, we create an allocation request for the holidays for a particular place (e.g. England) and tag the employees who we want to get that allocation. We then try to create a leave request to use up that allocation, but creating it the holiday type is read only. It is possible to create a leave request for an employee, then go and edit it, reset to draft then change the holiday type, but it appears to be a bug that the holiday type field on a leave request is read only at the point of creation from the calendar.
Further discussion about the procedure, which used to work, I am pretty sure this is a regression.
https://www.odoo.com/forum/help-1/question/set-country-holidays-in-hr-module-387

**Comment by gitawego** [comment]
I've got the same problem. as there is no way to define public holidays, I need this hack to work :(

**Comment by AlanBell** [comment]
to be clear, the merged fix  linked above does not fix this issue at all, it is just a comment related to that fix.

**Comment by SaFi2266** [comment]
Recently I faced the same problem

**Comment by Yenthe666** [comment]
Hi @AlanBell ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
