### ISSUE TITLE
[Wishlist] improve country groups & pricelists for multi-currency

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#47137]
Impacted versions: All

Currently there are just two country groups: "Europe" and "South America" and there is just one pricelist by default named "EUR".
There are a number of issues/improvements possible here though. If you have a country that does not fall within South America that does pay in USD as primary currency it will be shown on the website in EUR as Odoo falls back to the default pricelist.

Let us take "Palau" as an example (see https://en.wikipedia.org/wiki/Palau). The official currency is USD but "Palau" is not added in the list of "South America" - and it is not within South America - but it is not listed anywhere under an USD pricelist or country group. This means that somebody from Palau visiting your shop does not get the shop prices in USD but in EUR if you work in multi-currency. This same behaviour happens for other locations such as:
- Timor-Leste
- Puerto Rico
- El Salvador
- Zimbabwe (debatable as they support multiple currencies officially)
- Guam
- Virgin Islands (both the US and British islands)
- Mariana Islands
- Micronesia

Possible changes:
- Add these countries under new country groups
- Automatically create an USD pricelist when the USD currency is activated and apply all the countries that have an USD currency
- ??

**Comment by Yenthe666** [comment]
@mart-e and @dbo-odoo hi - what do you guys think about this? I think we can improve this behavior :) I guess I can make a PR if we agree on which way to go.

**Comment by Yenthe666** [comment]
Notice that we could also create other country groups for other parts of the world such as "Asia" and the same could apply for pricelists such as "Yen".

**Comment by Yenthe666** [comment]
@mart-e and @dbo-odoo any update? :)

**Comment by Yenthe666** [comment]
Anyone? ;)

**Comment by Yenthe666** [comment]
@mart-e can somebody please check this one? I honestly think it is a huge flaw in Odoo at this point.

**Comment by mart-e** [comment]
@Yenthe666 I am not really suited to take this kind of decision. I have reported the feedback (feedback id 2245517), we will see what they say.

**Comment by Yenthe666** [comment]
Awesome, thanks :)

**Comment by Yenthe666** [comment]
@mart-e any feedback from the guys yet?

**Comment by Yenthe666** [comment]
@mart-e any update? Friendly reminder.

**Comment by mart-e** [comment]
@Yenthe666 no sorry, still nothing

**Comment by Yenthe666** [comment]
@mart-e could you check once more please?

**Comment by mart-e** [comment]
@Yenthe666 no sorry, there are a lot of feedbacks and only a limited number of product owners, also v14 features rush.

**Comment by Yenthe666** [comment]
Okay I'll assume this is not going to happen/change before the V14 release then. I'll check back in in like two-three months.

**Comment by Yenthe666** [comment]
@mart-e could you give me an update once more please?

**Comment by Yenthe666** [comment]
@mart-e just a reminder :)

**Comment by mart-e** [comment]
Well I have tried several time but as my feedback was not considered so far, I am afraid we should consider it as a no.
I will let you know if this changes later but let's close it now. Sorry

**Comment by Yenthe666** [comment]
Ahh :( Such a pity, this had so much potential. Thanks for trying.
