### ISSUE TITLE
How to achieve calendar week number count from Sunday to Saturday ? (odoo10-Pivot view issue)

### ISSUE THREAD

**Issue by a-gandhi** [odoo/odoo#47146]
Impacted versions:
In odoo 10 Pivot view :- Calendar week number count from 'Monday' to 'Sunday' but I want change week number count from 'Sunday' to 'Saturday'.

Steps to reproduce:
I have two records as below image and also define tree and pivot view.

![Screenshot from 2020-03-08 16-14-16](https://user-images.githubusercontent.com/10364767/76163832-129a9a80-6163-11ea-9645-45ba278d9f64.png)

On Date 08/03/2020 have Sunday and 09/03/2020 have Monday
When I checked pivot view group by Date and select Interval as '**WEEK**'

Current behavior:
I got two different week number **W10**(08/03/2020 - Sunday) and **W11**(09/03/2020  - Monday) based on odoo standard it's count week day from 'Monday' to 'Sunday'.

Result:- 
![Screenshot from 2020-03-08 16-15-43](https://user-images.githubusercontent.com/10364767/76163868-71601400-6163-11ea-8d9a-344203db8420.png)

Expected behavior:
I want start week day count from 'Sunday' to 'Saturday' So result will be week number **W11**

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Odoo 10 is no longer Supported (https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch)

**Comment by Yenthe666** [comment]
Indeed plus it is rather a question so please ask this on the help forums at https://www.odoo.com/forum/help-1
