### ISSUE TITLE
[8.0] To cancel the picking from WH/Input to WH/Stock You need to click on the button to force availability.

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#4718]
**What is the purpose of having to force the availability of a picking to be canceled because you can not perform as it was returned to the supplier?**

Impacted versions:

 - 8.0

Steps to reproduce:

 - Go to Warehouse/configuration/Warehouse
 - Edit principal warehouse and set "Unload in input location then go to stock (2 steps)" on Incoming Shipments.
 - Create a new purchase order and confirm.
 - Go to In shipments and transfer the picking from Partner Locations/Suppliers  to WH/Input.
 - In this picking click Reverse transfer.
 
![image](https://cloud.githubusercontent.com/assets/7605672/5758406/0a093b44-9c8b-11e4-831a-9e037ef46acb.png)
 - Go to Warehouse/All Operations and search by Source Document the Purchase Order generated.
 - Check that status of picking from WH/Input to WH/Stock is “Waiting Another Operation” and not shown the cancel button.
![image](https://cloud.githubusercontent.com/assets/7605672/5758856/a2c951c2-9c8e-11e4-8f5e-9437977c6f43.png)

Current behavior:

 - To cancel the picking from WH/Input to WH/Stock You need to click on the button to force availability.

Expected behavior:

 - Not having to force availability for cancel this picking.

**Comment by jco-odoo** [comment]
So, you would suggest to add a cancel button when it is in the waiting another operation state?

**Comment by ernesto-gm** [comment]
yes,  What would be the case of having to force availability for cancel picking?

**Comment by nhomar** [comment]
2015-01-15 11:03 GMT-06:00 Josse Colpaert <notifications@github.com>:

> So, you would suggest to add a cancel button when it is in the waiting
> another operation state?



Yes.

And just to compliment to Luis.

All the chained operations should be triggered, or "asked" to trigger.

Remove quants.
Clear the next steps (cancelling them too).

To the back (chanied operatins before this one).

We for security reasons (to avoid negative inventories) in "any" case is
allowd force availabilities, then we hide the buton as it should be come by
default (but it is another history).

Regardsd.

-- 
--------------------
Saludos Cordiales

  [image: --]
Nhomar Hernandez
[image: http://]about.me/nhomar
     <http://about.me/nhomar?promo=email_sig>

**Comment by jco-odoo** [comment]
Cancelling of next steps should be done automatically (if "propagate cancel and split" is still checked by default) and cancelling unreserves the quants.

**Comment by jco-odoo** [comment]
<button name="action_cancel" states="assigned,confirmed,partially_available,draft" string="Cancel Transfer" groups="base.group_user" type="object"/> in view picking form should have state waiting also.  Still needs to be changed.

**Comment by jco-odoo** [comment]
It is true however that cancelling a picking that is in waiting another operation state is something you want to avoid more as you are breaking a chain, than cancelling a picking in waiting availability...

**Comment by jco-odoo** [comment]
Usability team thinks about merging anyways too...
