### ISSUE TITLE
[V8>=] Stock invenroty : inventory of several product functionality / Antidated inventory ??

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#4720]
Hi,

Why did you remove the possibility to make a partial inventory with on 5 or 10 product ? We are forced to customize the systeme to allow the user to to it. We have to change the onchange edit the theorical qty...

All my customer use the tool like that...

Edit : We can't make anti dated inventory anymore...

**Comment by Yenthe666** [comment]
Hi @tfossoul,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
