### ISSUE TITLE
base_iban validate_iban

### ISSUE THREAD

**Issue by Kontrolix** [odoo/odoo#47213]
**Impacted versions:** 12.0+ 

**Steps to reproduce:** Create or update a res.partner.bank with acc_number

**Current behavior:** There is no effective validation

**Expected behavior:** To have an error when acc_number is not valid.

Maybe I'm missing something, but the purpose of module base_iban is: 

`This module installs the base for IBAN (International Bank Account Number) bank accounts and checks for it's validity.`

as it said in the __manifest__. However in the create and write method of res.partner.bank (of base_iban module) we found a **try/except: pass**

    @api.model
    def create(self, vals):
        if vals.get('acc_number'):
            try:
                validate_iban(vals['acc_number'])
                vals['acc_number'] = pretty_iban(normalize_iban(vals['acc_number']))
            except ValidationError:
                pass
        return super(ResPartnerBank, self).create(vals)

    @api.multi
    def write(self, vals):
        if vals.get('acc_number'):
            try:
                validate_iban(vals['acc_number'])
                vals['acc_number'] = pretty_iban(normalize_iban(vals['acc_number']))
            except ValidationError:
                pass
        return super(ResPartnerBank, self).write(vals)

And so if IBAN is not valid it never throw an error ! Which is the point of this module ! O_o 

My question is: Is there a good reason for this?

**Comment by pedrobaeza** [comment]
It's in a try because a non IBAN account can't be prettified, so that's the used method. Non IBAN accounts are allowed, and there's no error if no valid IBAN, but the type of the account is `bank` instead of `iban`.

Closing as no issue, but question, and being also answered.
