### ISSUE TITLE
[8.0] Replace a property field with a function field

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#4724]
Hi, 

Some weeks ago (On september), it was possible to replace a property field with a function field like this:
'property_account_expense': fields.function(_get_account, fnct_inv=_set_property, type='many2one', relation='account.account', string='Expense Account', multi="_get_account"),

Currently, this example does not work. The method defined on the function field isn't called

@rco-odoo Have you any idea what that could have changed this behavior ?

Thanks !

**Comment by adrienpeiffer** [comment]
This example worked before 619a844

**Comment by rco-odoo** [comment]
Fixed by #9214.
