### ISSUE TITLE
Context is overwritten when is used 'with_context' method in new api

### ISSUE THREAD

**Issue by sergioernestotostadosanchez** [odoo/odoo#4726]
Good day! I have the next issue related to the one2many fields:

Description
-----------
When I create a new record for the stock.picking model I assign the move_lines
field values with the (0, 0, {data_for_record}) option; so, when I used the
create method for a stock.picking object using the "with_context" method, I
watch that my record is not being created due to the context isn't arrived to
the create method with the values that I've set with the "with_context" method,
which is neccesary to trigger methods in the stock.move model to get
default values for some required fields. The record isn't created due to context
hasn't needed data to get default values for new record. I'm doing this in a:

- Python Unittest file
- Odoo version 8.0

How to reproduce it
-------------------

**1. Create a dictionary with the data for a stock.move record:**
::
stock_move_data = {
    'product_id':       [a product id],
    'product_uom':      [a unit_of_measure id],
    'product_uom_qty':  [a quantity],
    'name':             [a description]
    }
    
**2. Create an object for stock.picking model**
::
stock_picking_obj = self.env['stock.picking']

**3. Create a new record with the previously created object as indicated here:**
::
\# move_lines is the one2many field
picking_data = {
'name':             [a name],
'move_type':        [a type],
'picking_type_id':  [a picking type id],
'priority':         [a priority value from the selection options],
'move_lines':       [(0, 0, stock_move_data)]
}

stock_picking_obj.with_context(
    default_picking_type_id=self.env.ref('stock.picking_type_in').id
).create(picking_data)

**4. When you execute the code, the traceback show you something like this:**
...
IntegrityError: null value in column "location_id" violates not-null constraint

The data sent via context is needed to get default values for the location_id
an other fields, executing methods called _default_location_destination &
_default_location_source.

Done actions
------------

I realize that context is arriving empty in the methods that give us default
values in stock.move model, exactly by example in methods:
    - _default_location_source
    - _default_location_destination
The value found in this methods for context when are called is {'recompute': False},
this value arrives so by example in the next line:
https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L1786
The line I think is causing the overriding is this:
https://github.com/odoo/odoo/blob/8.0/openerp/osv/fields.py#L739
    
Thanks for your attention, any question I'm in the best availability to answer,
I'll be waiting your answer

**Comment by rco-odoo** [comment]
@sergioernestotostadosanchez This is not a bug but an intended feature.

Here is the explanation. When you create a record, if the context contains keys like `default_XXX`, then the corresponding values will be used as default values for the *main record* to create. When creating *secondary* records through a one2many or many2many field, all keys that start with `default_` are *removed* from the context. The goal is to ensure that **default values for the main record are not used for secondary records.**

If you want to pass default values through the context for secondary records, then you should put the default value under a different key, and retrieve that default value in a default method:

    def default_picking_type_id(self):
        # alternative to 'default_picking_type_id'
        pt_id = self._context.get('picking_type_id', False)
        return self.env['picking.type'].browse(pt_id)

    picking_type_id = fields.Many2one(..., default=default_picking_type_id)

Of course, you may override the original default method to consider *both* keys `default_picking_type_id` and `picking_type_id` in the context.

**Comment by sergioernestotostadosanchez** [comment]
Hi again, thanks for the answer! 

I comment you that all you explain me has been understood. IMHO it could be much work if all who wants to use this way to resolve it overwrite all odoo module methods where are being used a default.
IMHO the orm should be capable to receive a parameter that allow us to do more efficient efforts, that indicates to the method allow use this default values for secondary records
