### ISSUE TITLE
Bug when print quotation/order

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#4729]
Hi openERP,

When I move the database to another new server I found a bug when I tried to print quotation/order in sale order.
This bug is not happen when we are in old server.

This is what I got on the log file:
2015-01-14 08:32:02,769 917 ERROR HPS openerp.netsvc: list index out of rangeparagraph text u'<para></font></para>' caused exception
(<type 'exceptions.IndexError'>, IndexError("list index out of rangeparagraph text u'<para></font></para>' caused exception",), <traceback object at 0x7f5f332d15a8>)
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File "/opt/openerp/server/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/opt/openerp/server/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u"list index out of rangeparagraph text u'<para></font></para>' caused exception", (<type 'exceptions.IndexError'>,
IndexError("list index out of rangeparagraph text u'<para></font></para>' caused exception",), <traceback object at 0x7f5f332d15a8>))

Server environment: Ubuntu 14.0
OpenERP Version: just Today (15-01-2014) make bzr branch from bzr branch lp:openobject-server/7.0

Dump file:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=sLvgtSDEv2jv5K7GGAdVb72jqK09wz0kBJ7LI5tRoOM%3d&docid=0769ba53ea21c4c898c967b0ca75ec2be

partner: Falinwa Limited

**Comment by spadae22** [comment]
Take the latest pull from Git

**Comment by falinwa** [comment]
I have pull from the latest in Git, still have some problem

**Comment by falinwa** [comment]
closed.
it because ubuntu14 installed python report package version 3.

it must bellow 3 to work. so you must downgrade the python report package.
