### ISSUE TITLE
reference instead supplier invoice number in voucher line

### ISSUE THREAD

**Issue by scigghia** [odoo/odoo#4732]
as discussed here: https://github.com/OCA/OCB/issues/127
when paying a supplier invoice, with voucher, may be useful to show supplier invoice number instead of ref, only for supplier invoice.

**Comment by Yenthe666** [comment]
Hi @scigghia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
