### ISSUE TITLE
Module names are translated on the base module instead of its own translations

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#47334]
Impacted versions:
- 11.0
- 12.0
- 13.0

Steps to reproduce:
- Export translations of any module, either native or custom
- Open the resulting `.po` file and look for the module name
- Repeath the process but exporting translation for the base module

Current behavior:
The term that corresponds to the module name is included on the base module's translations, instead of the module itself.

Expected behavior:
Module name should be included into the translatable terms of its module. For native modules this might not be an issue, but it might actually be when dealing with custom modules, because manual translations (`i18n_extra`) would be required to translate its module name.

**Comment by pedrobaeza** [comment]
This is an old question that has been arisen several times. There's a technical problem in what you propose. @mart-e do you have the link to other of your answers about this?

**Comment by mart-e** [comment]
Unfortunatly, what you propose is not possible:

- The terms of a module are loaded only when the module is installed
- You want to have the module name/description translated also when the module is not installed

Moreover, technically, the `ir.module.module` entries have an external id linked to `base` module. Again, this makes sense as you can not have records with an external id of a module that is not installed. Also, when uninstalling a module, we remove all records with the external id of this module (and you do not want to remove an `ir.module.module` entry).

Sorry but I do not have a solution for the issue of custom module (except manually creating an `ir.model.data` inside your custom module but this will not solve the above problem).

**Comment by pedrobaeza** [comment]
@mart-e what about having `README.<lang>.rst` files for rendering the module description in the corresponding language, and if not exists, then continue with the regular translation mechanism? This way, we have the best of both worlds (translation of core modules description in Transifex + translation of community module).

**Comment by mart-e** [comment]
Thanks for the suggestion, I will open a feedback about it, will see.

**Comment by mart-e** [comment]
Sorry but the feedback was rejected, we don't want to add too much complexity only for module names. I am afraid it still needs to be done manually.

**Comment by pedrobaeza** [comment]
Well, I was talking not only the name, but the description...

**Comment by pedrobaeza** [comment]
@mart-e this problem has been depicted again in https://github.com/OCA/OCB/issues/929. Maybe you can ask again for feedback about the multiple description files?

**Comment by mart-e** [comment]
@pedrobaeza actually it's possible to go around manually.

Take the manifest of my module `foo`:
```py
{
    'name': "Foo",
    'summary': """
Foo Description""",
    'description': """
Foo Long Description
""",
...
}
```
Add a file `addons/foo/i18n_extra/base.pot`
```po
# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* base
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 13.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-05-18 13:24+0000\n"
"PO-Revision-Date: 2020-05-18 13:24+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: base
#: model:ir.module.module,summary:base.module_foo
msgid ""
"\n"
"Foo Description"
msgstr ""

#. module: base
#: model:ir.module.module,description:base.module_foo
msgid ""
"\n"
"Foo Long Description\n"
msgstr ""

#. module: base
#: model:ir.module.module,shortdesc:base.module_foo
msgid "Foo"
msgstr ""
```
and your `es.po` file alongside containing the translations.
When installing the module, the translations are loaded:
![Screenshot_2020-05-18 Foo - Odoo](https://user-images.githubusercontent.com/564822/82218863-d29f2300-991c-11ea-8fb8-e2b46063beb8.png)

**Comment by pedrobaeza** [comment]
Thanks for the tip. Indeed we can do that, although not very comfortable, and the main problem: you don't have translations until you install the module!

Talking about `i18n_extra`, there's now a problem since v12 if you want to include already translated terms in the source module in your custom module: the unique constraint arises. Have you thought about this problem?

**Comment by mart-e** [comment]
> the main problem: you don't have translations until you install the module!

That's true, it's the main limitation without having to modify how we evalute the manifest/scan of modules.

> there's now a problem since v12 if you want to include already translated terms in the source module in your custom module: the unique constraint arises

It shouldn't, at the import of translation there is the `ON DELETE DO NOTHING` clause that should handle that scenario.
https://github.com/odoo/odoo/blob/773d94fae0eb82d2df96226afd2caad2ff7c22cf/odoo/addons/base/models/ir_translation.py#L141


cc @dbo-odoo cf the task 2215268
