### ISSUE TITLE
Qweb Quotation template incorrect company name shown on validating invoice

### ISSUE THREAD

**Issue by DJzx** [odoo/odoo#4739]
When a user views the quotation, logs into the customer portal and accepts the quotation.
Above the signature box the wording is incorrect...

The wording says :

I agree that by signing this proposal, I accept it on the behalf of Odoo.com, for an amount of $6000 with payment terms: 

The company name in the validate order message is incorrect..is should be the partner company name..not the company name that sends the quotation

**Comment by avanzella** [comment]
To fix this issue, website_quotation.xml in website_quote/views line 250 should be modified from `object.company_id` to `object.partner_id`

**Comment by Yenthe666** [comment]
Hi @DJzx,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
