### ISSUE TITLE
[12.0/13.0] Unable to edit an expense after payment

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#47472]
Hello,

Some of our clients use the Expenses module, and have told us that it is limited in a way: whenever an expense is confirmed and paid, the account moves are created and from then on, you can't edit or cancel the expense document.

When cancelling the associated move, or unreconciling, editing and reconciling it again, there is no automatic change in the expense, which is counterproductive.

Usually, we'd tell the client that they'd need to cancel the move and then the expense, but the user can't even cancel the expense if there is an account move associated with it, even if it was cancelled.

This looks like an Odoo limitation, so we'd like to know if there are any plans to improve the expense module.

(tested on Runbot and demo.odoo.com)

Thank you.

**Comment by pedrobaeza** [comment]
Yes, this is a known limitation. You can use meanwhile https://odoo-community.org/shop/product/hr-expense-cancel-4665.

Closing then as missing feature.

@tivisse any plan to improve this?

**Comment by tivisse** [comment]
Dear all, 

Thanks for the feedback, I think that i makes sense. I'm gonna open a feature requested that will be validated by our product owners.

Thanks.
