### ISSUE TITLE
Shop configuration missing in OdooV8.0

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4751]
Dear Customer Support,
the Shop configuration is missing in 8.0 version.
I'm not able to find it in Sales Order also.
Regards
claudio Candito

**Comment by codingforfun** [comment]
I think @ccandito is talking about `sale.shop` model them seams to got removed between 7.0 / 8.0. 
I also miss this model as seam to do a lot of people if you search around.

https://www.odoo.com/fr_FR/forum/help-1/question/odoo-8-remove-sale-shop-63285

Please provide documentation for the reasoning behind removing this and by which concept it should get replaced. 

Link to mailing list discussions, concept paper or stuff like that would be helpfull. 

What is the conceptional approach for multi channel sales in Odoo 8.0 after removal of `sale.shop`? 

Thx

**Comment by codingforfun** [comment]
:-1: For removing this feature without any documentation or obvious reasons.

**Comment by Yenthe666** [comment]
Hi @ccandito ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Yes this was removed.

Regards,
Yenthe
