### ISSUE TITLE
Forum badges

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4752]
Question: https://www.odoo.com/forum/help-1/question/odoo-forum-account-not-working-72197

**Comment by smack815** [comment]
@zbik2607 Odoo is aware of the badge problems.  @mart-e is reviewing what can be done in the code.  The problem is the number of forum posts has caused the gamification system to run a very long time and not completing.

**Comment by mart-e** [comment]
@zbik2607 yep, it's a bug on odoo.com instance (huge db leads to too long cron that is killed before granting badges), not in the code. Searching for ways to optimise it.

**Comment by zbik2607** [comment]
After removing all spam posts and spammer accounts performance will be better.
