### ISSUE TITLE
[12.0] stock: Inventory adjustment on archived products

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#47549]
**Impacted versions:**
12.0

**Steps to reproduce:**
- Create a product
- Add some quantity by hand for that product
- Archive the product
- Perform an inventory adjustment

**Current behavior:**
The archived product quantity is not shown and not possible to be adjusted.

**Expected behavior:**
That quantity is shown and can be adjusted.

**Comment by pedrobaeza** [comment]
@sle-odoo @amoyaux can you please take a look to this?

**Comment by sle-odoo** [comment]
We're fixing this [here](https://github.com/odoo/odoo/pull/45586/files) and we don't plan to fix it in v12 right now as it'll change the behaviour for those who're happy to not see the qties of archived products.

**Comment by pedrobaeza** [comment]
OK, thanks for the answer.
