### ISSUE TITLE
Web Live chat disappears after 10 minutes

### ISSUE THREAD

**Issue by mgielissen** [odoo/odoo#4754]
I noticed that the Web Live Chat disappears 10 minutes after joining the channel. First I thought it was something with Nginx reverse proxy, so I tested it with a new  v8.0 installation on port 8069, same problem.

When I rejoin the channel, the Web Live Chat is visible on the website for 10 minutes.

**Comment by jem-odoo** [comment]
Hello,
On your website, the button is only displayed if at least one user of the channel is online. After 10 minutes of inactivity (in the backend), the user is considered as 'away', so no 'online' anymore. So this is a normal behavior.
Hope it helps ;)

**Comment by mgielissen** [comment]
@jem-odoo You're right! The chatbox pops up within a minute after activity in the backend.
