### ISSUE TITLE
could not get content for /base/static/src/css/modules.css defined in bundle 'web.assets backend'

### ISSUE THREAD

**Issue by Rads19** [odoo/odoo#4755]
Dear Contributors,

Any suggestion(s) with regards to the error "could not get content for /base/static/src/css/modules.css defined in bundle 'web.assets backend'" on Odoo v8.0 (Ubuntu server)

As well as I need suggestions on how to create and modify files like __init__.py, css, js, xml files when a module is created. 
Thank you for your time!

**Comment by SVQTQ** [comment]
@Rads19 You closed this 18 hours ago. Did you fix this error or do you have any suggestion(s) regarding this error?

**Comment by Rads19** [comment]
The issue was with the static folder I deleted and created new static folder and related files.

**Comment by antiflu** [comment]
Hi, I had this same issue. Apparently when Odoo is started and there is a Python error while loading one of the modules, the static folders of the modules (so also the static folder of the base module) does not get set correctly and links such as those to modules.css do not work. The issue is in odoo/openerp/ir/http.py.

So, check your logs, remove the module (on disk) that caused the python error, and the error should be solved.

**Comment by yizhaq** [comment]
hi' i have the same problem
windows 7
can you help me please?

**Comment by Rads19** [comment]
Please create new database. That solved the issue for me.

**Comment by zilbaouf** [comment]
I have the same problem. You're saying that I should delete the actual database used by Odoo and create a new one ?

**Comment by Rads19** [comment]
Yes, please.

**Comment by zilbaouf** [comment]
I'm trying to do so but I don't know how to. I've been strugling with this problem for days, could you please explain me how I should do ? I've tried many commands but none of them worked...

**Comment by Rads19** [comment]
Sorry to hear that. I understand it is a bit of struggle until we get
things right. Have you tried drop the database from Database Manger??

**Comment by zilbaouf** [comment]
I'm working on Ubuntu Server so I can't use DB manager, but could you explain me clearly what you did to make things work ? Should I drop the postgre database used by Odoo and create a new one with the same content ?

**Comment by zilbaouf** [comment]
Thanks for helping by the way!

**Comment by SVQTQ** [comment]
Using the same content might render you vulnerable to the same problem. I
think it's best if you try to find out what is going wrong and try to solve
that.
Can you paste the errorlog here, did you recently upgrade any modules? Did
you recently install new modules?

2015-06-01 17:49 GMT+02:00 zilbaouf <notifications@github.com>:

> Thanks for helping by the way!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4755#issuecomment-107599502>.
>



-- 
Kind regards
Sonny Valkeneers



ERP-Consultant at Cats&Dogs bvba
Industrieweg 1506 - 3540 Herk-de-Stad,   Belgium
Mobile : +32 497 90 46 24
Website: http://www.catsanddogs.com
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsf6pNdW4Xr82F1q0yjlW7gs3QC56dTmvf3zwpFs02?t=http%3A%2F%2Fwww.catsanddogs.com%2F&si=5058211664101376&pi=69deef44-76d8-4268-b1da-58b7e68a7eda>

[image: www.catsanddogs.com] <http://www.catsanddogs.com>

**Comment by zilbaouf** [comment]
Yes this error appears ("could not get content for /base/static/src/css/modules.css defined in bundle 'web.assets backend'") only when I try to install the magento-connector module. 

To do so, I changed my /etc/odoo-server.conf file to add a new addons path :
Before : addons_path = /opt/odoo/odoo/addons
Now : addons_path = /opt/odoo/odoo/addons,addonsMagento/connector-magento

I'm trying to install this module but everything I tried did not work...

**Comment by zilbaouf** [comment]
Here is what my log shows when I try to connect :


![image](https://cloud.githubusercontent.com/assets/3988060/7931777/b626837e-0913-11e5-9daf-5f2fd2fd5a90.png)

**Comment by SVQTQ** [comment]
Well, odoo says it cannot find the file /addonsMagento/connector-magento .
Are you sure you are not missing a '/' between addons and magento? Also,
the path you gave as 2nd parameter in addons-path is not absolute (starting
from the root). So what I'd try to do is to give the full path to the
addons-path. /srv/odoo/addons/magento for example. But it should start with
'/'

2015-06-02 10:41 GMT+02:00 zilbaouf <notifications@github.com>:

> Here is what my log shows when I try to connect :
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/3988060/7931777/b626837e-0913-11e5-9daf-5f2fd2fd5a90.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4755#issuecomment-107865310>.
>



-- 
Kind regards
Sonny Valkeneers



ERP-Consultant at Cats&Dogs bvba
Industrieweg 1506 - 3540 Herk-de-Stad,   Belgium
Mobile : +32 497 90 46 24
Website: http://www.catsanddogs.com
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsf6pNdW4Xr82F1q0yjlW7gs3QC56dTmvf3zwpFs02?t=http%3A%2F%2Fwww.catsanddogs.com%2F&si=5058211664101376&pi=69deef44-76d8-4268-b1da-58b7e68a7eda>

[image: www.catsanddogs.com] <http://www.catsanddogs.com>

**Comment by zilbaouf** [comment]
Yeah just realised that, thanks a lot! I'm new with ubuntu and having no graphic interface doesnt help :)

I changed the path to /home/me/addonsMagento/connector-magento and the error disappeard. 
The problem is that I updated the modules list but  I can't see the magento connector module in any of the Modules lists when I clear the filters and type magento...

**Comment by SVQTQ** [comment]
You still have the problem that you cannot find the module? Have you
restarted the odoo service after editing the addons path? Is it correct
this time? does the user you use to run odoo with (normally 'odoo') have
the correct rights on the addons folder? (ls -lha
/home/me/addonsMagento/connector-magento)
this lists the files under the path and shows you the owner and group of
the folders. This should be the user that runs odoo. To change this to eg
odoo: chown odoo.odoo -R /home/me/addonsMagento/

another possibility is that you went one level too deep with your
addonspath. if connector-magento is the name of the addon, then the
addon-path would be /home/me/addonsMagento/

Hope you get it fixed ^^

2015-06-02 14:47 GMT+02:00 zilbaouf <notifications@github.com>:

> Yeah just realised that, thanks a lot! I'm new with ubuntu and having no
> graphic interface doesnt help :)
>
> I changed the path to /home/me/addonsMagento/connector-magento and the
> error disappeard.
> The problem is that I updated the modules list but I can't see the magento
> connector module in any of the Modules lists when I clear the filters and
> type magento...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4755#issuecomment-107942071>.
>



-- 
Kind regards
Sonny Valkeneers



ERP-Consultant at Cats&Dogs bvba
Industrieweg 1506 - 3540 Herk-de-Stad,   Belgium
Mobile : +32 497 90 46 24
Website: http://www.catsanddogs.com
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsf6pNdW4Xr82F1q0yjlW7gs3QC56dTmvf3zwpFs02?t=http%3A%2F%2Fwww.catsanddogs.com%2F&si=5058211664101376&pi=69deef44-76d8-4268-b1da-58b7e68a7eda>

[image: www.catsanddogs.com] <http://www.catsanddogs.com>

**Comment by zilbaouf** [comment]
Thanks for the help ! Got the problem fixed and finally installed the connector. I'm still having some issues but i'll try to fix them by myself!

**Comment by SVQTQ** [comment]
Glad the problem is fixed. Good luck on fixing the other issues!

2015-06-03 18:26 GMT+02:00 zilbaouf <notifications@github.com>:

> Thanks for the help ! Got the problem fixed and finally installed the
> connector. I'm still having some issues but i'll try to fix them by myself!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/4755#issuecomment-108510350>.
>



-- 
Kind regards
Sonny Valkeneers



ERP-Consultant at Cats&Dogs bvba
Industrieweg 1506 - 3540 Herk-de-Stad,   Belgium
Mobile : +32 497 90 46 24
Website: http://www.catsanddogs.com
<http://t.signalequattro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsf6pNdW4Xr82F1q0yjlW7gs3QC56dTmvf3zwpFs02?t=http%3A%2F%2Fwww.catsanddogs.com%2F&si=5058211664101376&pi=69deef44-76d8-4268-b1da-58b7e68a7eda>

[image: www.catsanddogs.com] <http://www.catsanddogs.com>

**Comment by Cywaithaka** [comment]
Another possible source of this issue is when odoo system user doesn't have the access rights to the addons folder.

**Comment by dreamfly32** [comment]
for me, restart odoo container,problem was solved
