### ISSUE TITLE
Procurement Orders filter

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4757]
In view with id="procurement_action" is set search default context

```
        <field name="search_view_id" ref="view_procurement_filter"/>
        <field name="context">{'search_default_current':1}</field>
```

but in   id="view_procurement_filter" filter with name="current" not exist. In effect Procuremnet Orders are not filtered by default.

**Comment by Yenthe666** [comment]
Hi @zbik2607 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
