### ISSUE TITLE
[8.0] Wrong source document in lines of invoices created from Delivery Orders

### ISSUE THREAD

**Issue by angeliyuu** [odoo/odoo#4759]
Hello all,

I have noticed that the field "origin" of table account_invoice_line is wrong when an invoice is created by merging multiple delivery orders.

Impacted versions:
- 8.0

Steps to reproduce:

1- In "Warehouse" menu create two delivery orders for same customer with "Invoice Control" set to "To be invoiced"

2- On tree view select both delivery orders and under "More" tab select "Create draft invoices" with option "Group by partner" checked

3- You will see the draft invoice in "Accounting" menu. Invoice's source documents seem to be ok, but that is not the case for invoice lines. 

4- In your Odoo database check the field "origin" of table account_invoice_line 

Current behaviour:

For example if we have merged Delivery Orders "DO1" and "DO2" with a product line in each one we will see in field "origin" of table account_invoice_line the following:

"D01" as source document for first product line.
"[u'D01', u'D02']" as source document for second product line.

Expected behaviour:

"D01" as source document for first product line.
"D02" as source document for second product line.

Regards

**Comment by AntMoreno** [comment]
I can confirm this issue. Lines for the first merged Delivery Order are ok, but succesive Delivery Order lines seems to concatenate origins for the fisrt line of each new origin.

If you have, say, 4 Delivery Orders merged, each with two lines (total 8 rows), the rows in account_invoice_line.origin field will look like this:

Row#1 WH/OUT/00001
Row#2 WH/OUT/00001
Row#3 [u'WH/OUT/00001', u'WH/OUT/00002']
Row#4 WH/OUT/00002
Row#5 [u'WH/OUT/00001, WH/OUT/00002', u'WH\\OUT\\00003']
Row#6 WH\\OUT\\00003
Row#7 [u'WH/OUT/00001, WH/OUT/00002, WH\\OUT\\00003, WH\\OUT\\00004']
Row#8 WH\\OUT\\00004

And so on. Notice also that the slashes are sometimes forward sometimes backward, it is not a typo, they are recorded like this in the table.

**Comment by Yenthe666** [comment]
Hi @angeliyuu ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
