### ISSUE TITLE
[Question] Automate initial configuration

### ISSUE THREAD

**Issue by lonix1** [odoo/odoo#47614]
Upon first run we need to configure the app - and this is done manually.

It takes us to `https://example.com:8069/web/database/manager` and asks for this:

- Database Name
- Email
- Password
- Phone number
- Language
- Country
- Demo data

I noticed that in `odoo.conf` we can set some variables:
- `admin_passwd` -> corresponds to "Password"
- `db_name` -> corresponds to "Database Name"

But what about the other fields? And what about configuring SMTP, etc.?

We need to automate this - so how can we pre-configure everything before first run.?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
