### ISSUE TITLE
Sample Order / Sample Invoice

### ISSUE THREAD

**Issue by jonatasartur** [odoo/odoo#47636]
Has anyone ever needed to send a product as a sample?
Has anyone done something like that? How do they do it? 

Problem:
I would like to use the sales and inventory system to send the sample. I need to generate a sales order and invoice, and I need to specify the product value on the invoice, but without generating a payment order for the customer, or generate with 0.00.

If anyone has any suggestions or ideas ...

[I use Odoo 12 Community]

**Comment by Yenthe666** [comment]
@jonatasartur the Github tracker is only for bugs in the official code. Please ask these type of questions on the help forums at https://www.odoo.com/forum/help-1
You could create a line with a price of 0 I guess.
