### ISSUE TITLE
[13.0] website: passing title and default_title as metadata will result in no SEO title being set

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#47638]
Impacted versions: 13.0

Steps to reproduce: 
1. Login to the latest runbot 13.0
2. Login and go to the shop, open the first product.
3. Open the console and duplicate the `<metadata name="title">` block and rename it to `<metadata name="default_title">` (which is the same as passing them both along in a HTTP controller route.
4. Open the SEO dialog:
![image](https://user-images.githubusercontent.com/6352350/76685275-b6c48b80-6612-11ea-9ab1-eec80009ec8f.png)

Current behavior: The SEO title is not set. This comes back from
https://github.com/odoo/odoo/blob/aa98750fa4f9b1278eaf7d656c0c1a8c81f86325/addons/website/static/src/js/menu/seo.js#L353-L355
Besides of this there is a case (which I was not able to reproduce exactly yet) where the SEO dialog will fail if the `website_meta_title` is not set in the SEO tags:
![image](https://user-images.githubusercontent.com/6352350/76685338-1753c880-6613-11ea-924f-4f911cd55082.png)
Which comes back from:
https://github.com/odoo/odoo/blob/aa98750fa4f9b1278eaf7d656c0c1a8c81f86325/addons/website/static/src/js/menu/seo.js#L342

Expected behavior: The SEO title is set

**Comment by Yenthe666** [comment]
@JKE-be did you get around to checking this?

**Comment by JKE-be** [comment]
You closed this one, because no more present?

**Comment by Yenthe666** [comment]
Nope, still present. I closed it because nobody checks :)
