### ISSUE TITLE
 iot box  printing error

### ISSUE THREAD

**Issue by NAJEM-BRAHIM** [odoo/odoo#47635]
Impacted versions: Odoo Pos V13
Iot box V20 

Steps to reproduce:  when printing the sales receipt if there are less than 10 items it prints well but when there are more than 10 lines the impression goes wrong

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![20200313_190450](https://user-images.githubusercontent.com/8737971/76652177-524bf280-6566-11ea-9316-f6ffaae8f23c.jpg)

**Comment by NAJEM-BRAHIM** [comment]
I tried to print without the iot box, and the same scenario less than 10 articles the ticket prints correctly more than 10 articles erroneous printing.

**Comment by slastra** [comment]
I'm experiencing the very same issue using an Epson TM-T20II on Odoo v13 (20200421) and IoT box v20 (04-Mar-2020). Will print short receipts flawlessly, but if I exceed a certain number of order items I get seemingly random characters.
![receipt](https://user-images.githubusercontent.com/34750676/79943027-805a0780-842d-11ea-9691-513cf801cb70.png)
