### ISSUE TITLE
Company switcher widget is not usable anymore using the keyboard

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#47650]
Impacted versions:
- 13.0

Steps to reproduce:
- Enable access to multi companies so the company switcher widget is shown
- Navigate to the switcher widget, either clicking on it or pressing `<Tab>` until you reach it
- Try to select a company using the keyboard, using `<Tab` or `↓`

Current behavior:
Menu items corresponding to available companies are skipped

Expected behavior:
Menu items should be reachable using the keyboard.

This has to do with the refactor on the multi-company behavior performed in v13, because now there are two possible actions per company, depending on where they're clicked: switch to the company or toggle it. Such actions are handled using `<div>` elements, which aren't reachable by default:

https://github.com/odoo/odoo/blob/98977904c448f3a39849e11d25b6e31940c3c0a4/addons/web/static/src/xml/base.xml#L1487-L1489

https://github.com/odoo/odoo/blob/98977904c448f3a39849e11d25b6e31940c3c0a4/addons/web/static/src/xml/base.xml#L1498-L1500

**Comment by pedrobaeza** [comment]
As there's a PR, we can close this issue for continuing there.
