### ISSUE TITLE
[8.0], fields_get() does not return info whether a field is functional (ie python function) or db column

### ISSUE THREAD

**Issue by galtys** [odoo/odoo#4766]
In v7, fields_get() used to return function name for functional field. This has disappeared in v8. What is the latest api to be able to differentiate functional vs db fields. Many thanks.

**Comment by Yenthe666** [comment]
Hi @galtys ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
