### ISSUE TITLE
[base]: Indian currency symbol position should be before the amount

### ISSUE THREAD

**Issue by hareshjupical** [odoo/odoo#47687]
Impacted versions: 10,11,12,13

Steps to reproduce: Create company with indian chart of account. Create any transaction in sales or invoicing. Now you can see currency symbol (₹) is after amount, but it's not correct. 

Current behavior: currency symbol for indian chart of account is not correct. It should be before amount.

This is happening because **position** field value (which is **before**) is missing in demo data of INR currency (base.INR). We need to something like:
<field name="position">before</field>

Expected behavior: Currency symbol of indian chart of account is before amount

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Added fix for master at https://github.com/odoo/odoo/pull/47717

**Comment by hareshjupical** [comment]
Thank you everyone for merge.
