### ISSUE TITLE
Stock location assignment in Warehouse setting

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4771]
Dear Odoo Support,
I'm not able to find the setting for assigning the default Stock location in warehouse definition.
Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

You might want to ask this on the official help forums (odoo.com/help) in the future. The Github bug tracker is only for bugs in the official code, not for asking questions.
For more information look at the official docs at https://www.odoo.com/page/docs

Regards,
Yenthe
