### ISSUE TITLE
fields.function in openerp 8 not working

### ISSUE THREAD

**Issue by maduong** [odoo/odoo#4774]
Help me!

The "fields.function" not working in openerp 8.

**Comment by nafex** [comment]
please see here how to report issues:
https://github.com/odoo/odoo/wiki/Contributing#reporting-issues

**Comment by kevin8909** [comment]
There's no function fields in new API,please use "compute" key word instead.

e.g:
e_work_age = fields.Integer(string="Work Age", compute='_get_workage')

**Comment by Yenthe666** [comment]
Hi @maduong,

As stated by @kevin8909 you should use compute='_your_function') instead of fields.function, which is from V7.
Closing this one since it is a not an issue, concerns custom development and since it has already been answered.
