### ISSUE TITLE
[8.0] module project issue: bug on record rule domain

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#4775]
In case if a private project, your a not able to update an issue even if you are in the followers. 
The following record rule is responsible:
`<record model="ir.rule" id="issue_user_rule">
            <field name="name">Project/Issue: employees: public or employee or (followers and following)</field>
            <field name="model_id" ref="model_project_issue"/>
            <field name="domain_force">['|',
                                            ('project_id.privacy_visibility', 'in', ['public', 'employees']),
                                            '&amp;',
                                                ('project_id.privacy_visibility', '=', 'followers'),
                                                ('message_follower_ids', 'in', [user.id]),
                                        ]</field>
            <field name="groups" eval="[(4,ref('base.group_user'))]"/>
        </record>`

`[user.id]` should be  `[user.partner_id.id]`

**Comment by Yenthe666** [comment]
Hi @Cedric-Pigeon ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: You're always free to create a PR to fix the bug when you know what is wrong.

Regards,
Yenthe
