### ISSUE TITLE
Delegate Task

### ISSUE THREAD

**Issue by ta-clearcorp** [odoo/odoo#4779]
The wizard to delegate the task doesn´t update the ramaining hours in the delegated task according to the hours included, it maintain the parent task hours.

Step 1: Create a project
Step 2:Create a Task with 12 planned hours
Step 3: Delegate the task
Step 4: In the wizard, change the hours in the task. 10 in the delegated , 2 in the validation
Step 5: Press the delegated button
Step 6: The hours remaining in the delegated task should be 10, instead it has 12. In the second picture you can see the initially planned hours with 10, and the remaining hours 12.
![captura de pantalla de 2015-01-19 12 05 30](https://cloud.githubusercontent.com/assets/10601553/5805453/7cb4d3aa-9fd4-11e4-91da-3bdbda78a64d.png)
![captura de pantalla de 2015-01-19 12 05 48](https://cloud.githubusercontent.com/assets/10601553/5805467/adddc536-9fd4-11e4-94c0-6761473dd41b.png)
)

**Comment by Yenthe666** [comment]
Hi @ta-clearcorp ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
