### ISSUE TITLE
[8.0] New group for installed application will cause remove it from the user application list

### ISSUE THREAD

**Issue by alejandroperezcosio** [odoo/odoo#4781]
Version 8.0
Steps to reproduce: 
- Install Sales application
- Go to Configuration/groups and create a new group for Sales named "New sales group"
- Go to Configuration/Users and select admin or another user

Current behavior:
- In the "Application" sub-menu for the user, the line for Sales is not there anymore. 

Expected behavior: 
- The "New sales group" should appear in the Sales role list in the "Application" sub-menu for the user admin or other.

![users odoo](https://cloud.githubusercontent.com/assets/5828213/5807346/c66cfe36-9ff8-11e4-9b68-10251f835f44.png)

**Comment by livingmine** [comment]
Please have a look at [this](https://www.odoo.com/forum/help-1/question/how-to-add-a-new-group-for-an-application-odoo-8-73629#answer-117035).

**Comment by Yenthe666** [comment]
Hi @alejandroperezcosio ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
