### ISSUE TITLE
Bill time on task with invoice rate per user doesn't work correct

### ISSUE THREAD

**Issue by lbonjean** [odoo/odoo#4782]
*Product is ignored when reporting time on projects with invoice rate per user

Version 8.

Steps to reproduce
1. create a service product 'new service product'
2. create a user, define the default service product for that user
3. Create a project, define the 'new service product' as the product to use for that user. Make sure to enable tasks and timesheets on the project
4. Create a task in the project
5. Add time to the work summary of the task.
6. Save the task
7. check Time and material to invoice

Current behaviour:
The default product for the user is used

Expected behaviour:
The 'new service product' should be used

(If you report the time directly to the project, (not to a task), it works correctly.)

**Comment by Yenthe666** [comment]
Hi @lbonjean ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
