### ISSUE TITLE
TypeError: translate() takes no keyword arguments

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#47867]
**Impacted versions**: 12.0  (with python 3.5)

**Steps to reproduce**:

** Launch** one odoo instance with python 3.5 and use of [xml files](https://github.com/odoo/odoo/blob/12.0/odoo/fields.py#L1821) in binary fields

**Current behavior**:

Error in [convert_to_column](https://github.com/odoo/odoo/blob/54785e68c8b30bd33eb72245ba9d74a4af424148/odoo/fields.py#L1823) method of the *Binary* class:

`                decoded_value = base64.b64decode(value.translate(None, delete=b'\r\n'), validate=True)
`

According to the last version of the method [bytes.translate](https://docs.python.org/3.8/library/stdtypes.html?highlight=maketrans#bytes.translate) the **delete** keyword is not available anymore but it is now a positional parameter.

`Changed in version 3.6: delete is now supported as a keyword argument.`

**Expected behavior**:

No error is expected. The old syntax might be compatible even with the new instances:

`value.translate(None, b'\r\n')`

Alternatively might the [v12 required version](https://github.com/odoo/odoo/blob/54785e68c8b30bd33eb72245ba9d74a4af424148/setup.py#L60) be changed to **>=3.6**

Python *3.5* is no more compatible with the current **v12** code in **fields**.

**Comment by pedrobaeza** [comment]
Indeed we are facing the same issue in OCA as we are using Python 3.5:

https://travis-ci.org/github/OCA/l10n-spain/jobs/663434457#L2437

@odony @jpp-odoo can you please fix it passing it as positional argument? May I do the PR?
