### ISSUE TITLE
[7.0] Change in Sales Quotation multi-line entry behaviour changed

### ISSUE THREAD

**Issue by jon-willowit** [odoo/odoo#4786]
Commit: f406847613fe352908ff52f1babc3083fe6042ef, Jan 14 2015

Prior to this (not sure which version) if a user tabbed to a new order entry line the line would automatically open up for editing. The current behaviour (as at above revision), is that, firstly several extra "tabs" are required to move the cursor to the "add an item" field, and then secondly, the user must then press the "Enter" key to open up the new line. The previous behaviour was the correct one, especially when entering large orders.

**Comment by intero-chz** [comment]
Hi,

i have to correct or let me call it improve your issue. It's behaving the same in 7.0 and 8.0 tested on runbot servers (22.01. 11:00 GMT+1). And actually i don't like the new behavior in editable trees.

And that's why:
1. You will need more clicks, because you have to tab through buttons and readonly fields
2. It's nearly impossible to see wether you're on "add an item" or not... (using chrome)

Best Regards

**Comment by jon-willowit** [comment]
Hi

Thanks for the reply. Just so I am clear - so this means you will be fixing
it shortly?

Jon

**Comment by intero-chz** [comment]
Sorry, i really would do it, but my JavaScript skills are nearly non-existent.

I just wanted to support your issue.

Best Regards

**Comment by jon-willowit** [comment]
I reported this issue for a customer who has an OPW so Odoo have to respond
within a week. I'll keep an eye on it and remind them if no action happens.

**Comment by jon-willowit** [comment]
At minimum this is degraded behaviour if not an outright bug, and in no way could it be considered to be an improvement. My customer, how has an OPW,  is getting annoyed because they do enter 100 line orders and this new behaviour is slowing them down considerably. I cannot think in any way that this would be considered an optional usability issue - it should be fixed.

**Comment by ged-odoo** [comment]
I fixed a bug in commit 913fa445aa2d60d9edeba55960b4afc54d1715bf (in version 8.0).  The issue was that when the last column of an editable listview was readonly, the tab behavior was broken, and did not create a new entry.  Does that solve your issue?

**Comment by intero-chz** [comment]
Seems fixed in 8.0 :+1: 

But not in 7.0 :-1: and that's what issue was about.

Thanks for the fix anyway.

**Comment by ged-odoo** [comment]
now backported in 7.0 (commit 2d524c947cc6ef51e1c2a40dd69a518c9586afc2)
