### ISSUE TITLE
[8.0] Calendar weekly view corruption when displaying ovelapping entries

### ISSUE THREAD

**Issue by jon-willowit** [odoo/odoo#4787]
![untitled](https://cloud.githubusercontent.com/assets/891154/5812923/5abe930e-a0c8-11e4-82d0-4917b4c06a3f.png)

**Comment by dmo-odoo** [comment]
Hello,

We use the FullCalendar js api, which implements this behavior by default. This is not really an issue but rather a question of taste, as using separate columns wouldn't really help readability as the key problem is the lack of space in such a view. I will however escalate the question to the usability team to discuss internally whether it is preferable from a usability point of view to have it enabled or not by default.

In either case, if you are willing to modify the code, it is very easy to disable the overlap mode by modifying the web_calendar/static/src/js/web_calendar.js file and adding slotEventOverlap: false at the end of the object returned by the get_fc_defaultOptions function, so it would look like:
    aspectRatio: 1.8,
    snapMinutes: 15,
    slotEventOverlap: false
};

**Comment by jon-willowit** [comment]
Hi David

Thank you. BTW can we get Odoo to do some custom work on the calendar
widget?

Regards

Jonathan Wilson
www.willowit.com.au
ph: +61 3 8506 0393
mob: +61 4 000 17 444
*2013 OpenERP Best Partner Asia/Pacific*
*Creators of  Odoo-Pentaho integration project*

**Comment by dmo-odoo** [comment]
Hello,

Customizations are done by the Functional team, if any. I have reopened your ticket on our internal platform and forwarded it to said team.

Best regards,
David
