### ISSUE TITLE
not able to find odoo.config file

### ISSUE THREAD

**Issue by Suhaibsultan** [odoo/odoo#47873]
I am not able to find odoo.config file please suppport

**Comment by Yenthe666** [comment]
@SubodhDahal the Github issue tracker is for bugs/issues in the official code. This is not the place to ask questions, you can do this on the official help forum at https://www.odoo.com/forum/help-1.
That being said, you can usually find the file under `/etc` and usually has a `odoo-server.conf` like filename but it depends on how you've deployed your Odoo and on which system.

**Comment by SubodhDahal** [comment]
@Yenthe666 You taggedthe wrong person mate. I had nothing to do with this issue.

**Comment by Yenthe666** [comment]
Apologies ;)
