### ISSUE TITLE
Run Schedulers does not consider procurement_order.date_planned when processing Reordering Rules

### ISSUE THREAD

**Issue by scosist** [odoo/odoo#4788]
**Run Schedulers does not consider procurement_order.date_planned when processing Reordering Rules**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. set product orderpoint rule as follows
   - Minimum Quantity = 0
   - Maximum Quantity = 0
   - Quantity Multiple = 1
2. create a sales order to deliver one in 6 months (`sale_order.date_order`)
3. execute `Run Schedulers`

Current behavior:
- A single Manufacturing Order or Request For Quotation is created (depending on the product route) at the earliest possible date. 
- In the event that an RFQ or Draft PO for the same supplier already exists the product is assigned to the same RFQ even if the Order Date on this RFQ is in the past. Manufacturing Orders likely behave similarly.
  - In the event that this exact product already exists as a line item on this RFQ, with an earlier Scheduled Date than the 'new' product in question, the Quantity is simply incremented while maintaining the original Scheduled Date for the first shipment. Although related, perhaps this is a separate issue?

Expected behavior:
- Inventory Optimization: create an MO or RFQ at the latest possible date. MRP should generate an order for this relative to the scheduled date on the procurement of the product or material. IOW, we don't want this to sit on the shelf for 6 months.
- In the event that an RFQ for the same supplier and product exist, the additional product should be added as a new line item unless the Scheduled Date is the same. Or a new RFQ should be generated.

**Comment by lem8r** [comment]
I can confirm this issue too.
It can be reproduced in Odoo 8.0 and 9.0alpha.

I guess plroblem is in `addons/stock/procurement.py`
`_prepare_orderpoint_procurement` function sets `date_planned` with `datetime.today()`
but it supposed to be sheduled date instead.

``` python
    def _get_orderpoint_date_planned(self, cr, uid, orderpoint, start_date, context=None):
        date_planned = start_date + relativedelta(days=orderpoint.product_id.seller_delay or 0.0)
        return date_planned.strftime(DEFAULT_SERVER_DATE_FORMAT)

    def _prepare_orderpoint_procurement(self, cr, uid, orderpoint, product_qty, context=None):
        return {
            'name': orderpoint.name,
            'date_planned': self._get_orderpoint_date_planned(cr, uid, orderpoint, datetime.today(), context=context),
            'product_id': orderpoint.product_id.id,
            'product_qty': product_qty,
            'company_id': orderpoint.company_id.id,
            'product_uom': orderpoint.product_uom.id,
            'location_id': orderpoint.location_id.id,
            'origin': orderpoint.name,
            'warehouse_id': orderpoint.warehouse_id.id,
            'orderpoint_id': orderpoint.id,
            'group_id': orderpoint.group_id.id,
        }
```

**Comment by lem8r** [comment]
It seems like stock_calendar module in Odoo 9 (see master or saas-6 branch) should fix procurement ASAP behavior.

**Comment by Yenthe666** [comment]
Hi @scosist,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
