### ISSUE TITLE
[8.0]Add variable price delivery to quote price

### ISSUE THREAD

**Issue by R1k0ita** [odoo/odoo#4789]
I have created a new delivery method without "normal price" and with a new grid associated where the price is modified  depending to the quantity.
When I add the delivery method in a line of quote I obtain the error:
"No Grid Available! No grid matching for this carrier!"

If the delivery method have only "normal price" it work

**Comment by quique123** [comment]
Did you get this to work?

**Comment by Yenthe666** [comment]
Hi @R1k0ita,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
