### ISSUE TITLE
signature mismatch on price_get

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#4792]
Observed in 8.0.

The `price_get()` method receives a partner **id** (integer) when called from an onchange in the purchase order:

https://github.com/odoo/odoo/blob/8.0/addons/purchase/purchase.py#L1148

On the other hand, on validation of the move it passes a `browse_record`

https://github.com/odoo/odoo/blob/8.0/addons/purchase/stock.py#L108

The field is then used in one line only, as an integer:

https://github.com/odoo/odoo/blob/8.0/addons/product/pricelist.py#L306

It is a comparison, so it does not crash, but the partner is never used here. I believe that with a setup with multiple suppliers, the partner of the picking will be ignored (potentially generating moves and orders/invoices with different prices).

**Comment by yvaucher** [comment]
Good catch!

**Comment by rdeheele** [comment]
:cactus:

**Comment by mart-e** [comment]
fixed at ed6d9afecc7f48ba126034d627076f90c1e0f512

**Comment by lepistone** [comment]
thanks!
