### ISSUE TITLE
Please reverse PR #47660, because it may cause a serious system malfunction.

### ISSUE THREAD

**Issue by gmarczynski** [odoo/odoo#47936]
Please reverse this PR, because it may cause a serious system malfunction.

Some messages in `load` are not unrecoverable errors, but warnings (so the there is no `ROLLBACK TO SAVEPOINT` executed) and with changes added by this PR the load suddenly stops after 10 records with warnings.

The failure example is a CSV file loaded by a module on install/update with some data warnings like `{'rows': {'from': 0, 'to': 0}, 'type': 'warning', 'record': 0, 'field': 'active', 'message': 'Valeur inconnue "t" pour les champs booléens "Active", assumant "oui"', 'moreinfo': 'Utilisez "1" pour oui et "0" pour non'}`

The result of this PR is deletion of all records after the 10th which may cause system failure.

_Originally posted by @gmarczynski in https://github.com/odoo/odoo/pull/47660#issuecomment-600688429_

**Comment by pedrobaeza** [comment]
I don't get the problem. This only silence error messages, but nothing about deleting records.

**Comment by gmarczynski** [comment]
No, it breaks load after 10 records with only warnings not errors and after the update is finished in `env['ir.model.data']._process_end` all previously existing records are deleted, because they are not loaded any more.

**Comment by pedrobaeza** [comment]
OK, I don't know enough the process to say then.

@xmo-odoo what do you think about the potential problem?

**Comment by bplancher** [comment]
I think what @gmarczynski means is that this changes also impacts the CSV files we may have on modules, to import module's data (for example, the `res.country.state.csv` from `base` module).

If i understand correctly, importing such file (when updating a module) and having some "warnings" during the process may end-up in losing all data from this file (all `res.country.state` created by `base` module, in this case) on updated instance(s). Am i right @gmarczynski ?

Depending on the case, this can be a real issue, resulting in some data-loss (for example, if it triggers some SQL `ON DELETE CASCADE` constraints).

As a recall, the `env['ir.model.data']._process_end` is a post-process (after modules installation/update) that cleanup any data in the db not being present anymore on modules' data-files (XML, CSV, etc.).
In this particular case, this post-process wrongly assume that data are dropped from the module and so, delete those data (whereas we "only" received some warning messages).

**Comment by gmarczynski** [comment]
This is correct @bplancher . Thanks

**Comment by pedrobaeza** [comment]
Thanks for the extra info. Now I get more the possible problem. This seems any way that can proceed from a bad module code, but let's see if this can be mitigated.

**Comment by gmarczynski** [comment]
I would vote to revert this PR completely, because it changes the way `load` treats errors and warnings. Such change may be introduced in new version, like Odoo 14.0, but not in 11.0, in my opinion. Thank you for your help.

**Comment by xmo-odoo** [comment]
@gmarczynski it doesn't significantly change the way errors are treated, though you're completely correct that it does change the way warnings generated by `_extract_records` and `_convert_records` are handled and that is not correct. I should have counted the errors (exactly as the line following the loop does, in fact) not all messages, and that's my mistake.
