### ISSUE TITLE
customer invoices not always  using the first initial sequence defined by the user

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#47944]
### Impacted versions:

saas-13.2

### Steps to reproduce:

1. Create new journal
2. Create a new invoice related to journal in (1) in draft state (name endswith 0001).
3. Create a second invoice to the same journal and validated. The name wil endswith 0002.
4. Go hack to first invoice and post it.

### Current behavior:

After confirm the first invoice you will see that the name now endswith 0003. So the initial number is never used, the initial number configured by the user is skipped.

### Expected behavior:

When creating invoices in a new database (could be created manually, or imported invoices) not necessary will be post in the same order that the invoices were created. No matter this the first posted invoice should use the initial sequence defined by the user.

Video/Screenshot link (optional):

https://drive.google.com/file/d/1vcumImFMbwiEVk3mX0YSTNvJhDIFtlLx/view

**Comment by zaoral** [comment]
FYI opw-2220539

**Comment by zaoral** [comment]
ping @jco-odoo

**Comment by jco-odoo** [comment]
@william-andre

**Comment by william-andre** [comment]
Should have been closed automatically by https://github.com/odoo/odoo/pull/48074
