### ISSUE TITLE
Singleton Error in Website settings, without company

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#47967]
**Impacted versions:**

Tested in Version 12.0 and Version 13.0

**Steps to reproduce:**

General Settings -> Website -> Company field Empty -> Save

![image](https://user-images.githubusercontent.com/62367855/77031539-df100980-69c7-11ea-8e09-1622e6a1fdf5.png)

**Current behavior:**
Singleton Error!
![image](https://user-images.githubusercontent.com/62367855/77031320-3f527b80-69c7-11ea-847c-9c79388e439a.png)

**Expected behavior:**

Either handle this error or Company field changed to required field

**Comment by pedrobaeza** [comment]
I think a website must always belong to a company, but then that field should be required. cc @JKE-be

**Comment by rdeodoo** [comment]
Indeed, the res.settings website form view is missing `attrs="{'required': [('website_id', '!=', False)]}"`, see https://github.com/odoo/odoo/pull/41027#issuecomment-566479393

**Comment by sswapnesh** [comment]
Added fix at https://github.com/odoo/odoo/pull/48058

**Comment by sswapnesh** [comment]
This has been fixed
