### ISSUE TITLE
[8.0] odoo , theme_clean installing with ERROR bootstrap.less not found

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#4797]
I've a theme_clean module from the indiegogo campaign, I'me getting an issue when installing on Odoo 8.0 ,I'am work on Ubuntu 14.04 LTS, I’m getting the following traceback :

openerp.addons.website_less.ir_qweb: FileError: 'bootstrap.less' wasn't found in - on line 2, column 1:
1 /*! 667c730e-e846-40e4-95ed-429fc1750e9a */
2 @import "bootstrap";
3 

This error occured while compiling the bundle 'website.assets_frontend' containing:
    - /website_less/static/src/less/import_bootstrap.less
    - /website_less/static/src/less/colors.less
    - /website_less/static/src/less/website.less
    - /theme_clean/static/src/less/colors.less
    - /theme_clean/static/src/less/fonts.less
    - /theme_clean/static/src/less/theme.less
    - /theme_clean/static/src/less/customize_modal.less
    - /theme_clean/static/src/less/padding.less
    - /theme_common/static/src/less/s_discount.less
    - /theme_common/static/src/less/s_event_list.less
    - /theme_common/static/src/less/s_profile.less
    - /theme_common/static/src/less/s_icon_box.less
    - /theme_common/static/src/less/s_icon_box_circle.less
    - /theme_common/static/src/less/s_icon_box_square.less
    - /theme_common/static/src/less/s_pricing.less
    - /theme_common/static/src/less/s_process_steps.less
    - /theme_common/static/src/less/s_timeline.less
    - /theme_common/static/src/less/s_lead_bar.less
    - /theme_common/static/src/less/s_logo_bar.less
    - /theme_common/static/src/less/s_color_blocks_2.less
    - /theme_common/static/src/less/s_color_blocks_4.less
    - /theme_common/static/src/less/s_big_image.less
    - /theme_common/static/src/less/s_big_image_parallax.less
    - /theme_common/static/src/less/s_team_profiles.less
    - /theme_common/static/src/less/s_slide_banner.less
    - /theme_common/static/src/less/s_separator_shade.less
    - /theme_common/static/src/less/s_separator_color.less
    - /theme_common/static/src/less/s_text_highlight.less
    - /theme_clean/static/src/less/options/bg_shade_light1.less
    - /theme_clean/static/src/less/options/color_preset_1.less
    - /theme_clean/static/src/less/options/font_UbuntuPtSans.less

I'v install all dependencies for odoo .

**Comment by rruebner** [comment]
@Sameer1990 Can you check if you have the file bootstrap.less in addons/web/static/lib/bootstrap/less/bootstrap.less. If this file doesn't exist you should checkout the latest master branch of odoo version 8.

**Comment by Sameer1990** [comment]
@rruebner  Thanks for your help. It seems the copy of my src code for odoo is old , i upgrade it to a newer one and it works .
Thank you

**Comment by lukebranch** [comment]
@Sameer1990 , I think this issue is related to #4604 . If you are still having issues  you may want to refer to the steps suggested by @vilder.
