### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by diwu01** [odoo/odoo#47990]
Impacted versions:
12.o
error code file: addons\web\i18n\zh_CN.po
error_code:
         #. module: web
        #. openerp-web
        #: code:addons/web/static/src/js/core/misc.js:17
        #, python-format
        msgid "You may not believe it,<br />but the application is actually loading..."
        msgstr "请内心等待，<br />应用仍在加载..."
right code 
       msgstr "请耐心等待，<br />应用仍在加载..."

**Comment by pedrobaeza** [comment]
Please check https://github.com/odoo/odoo/wiki/Translations for doing changes in translations.
