### ISSUE TITLE
[13.0] Performance issue on loading warehouse analysis report

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#48014]
Impacted versions: 13.0

Steps to reproduce:
1. Have a database with 275.000+ products, 250.000+ moves and quite some purchase orders (800+) 
2. Go to Inventory > Reporting > Warehouse Analysis

Current behavior: The loading of the warehouse analysis is extremely slow. In an example of a database with 275.000 products and 250.000 moves it takes +- 6.5 minutes to load the report (with just one active user):
![image](https://user-images.githubusercontent.com/6352350/77068398-d4b13800-69e6-11ea-9a68-f6f6f5e5d1ac.png)

Expected behavior: The report opens in an acceptable time frame (let us say less than a minute)

**Comment by gdgellatly** [comment]
just as bad in 12.0

**Comment by nim-odoo** [comment]
This might be the quick and dirty solution: https://github.com/odoo/enterprise/pull/6150

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/enterprise/pull/10601
