### ISSUE TITLE
wrong timezone in schedule date on delivery determination

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4805]
Dear Odoo Support,
in the user master data the CET timezone is set.
I've entered manually the Requested date in sales order as 31/03/2015  16:59:57.
the Company's security day is 3 days. 
the requested date has been calculated as 28/03/2015  15:59:57: one hour is missing. 
We suppose this is due to the timezone which is not taken into account.
Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
