### ISSUE TITLE
Barcode scanner not working on form views

### ISSUE THREAD

**Issue by lgarcia11** [odoo/odoo#48067]
Impacted versions:
13.0

Steps to reproduce:
Go to any form view, scan a barcode command like "O-CMD.NEXT"

Current behavior:
Nothing happens.

Expected behavior:
Move to next record.

**Comment by pedrobaeza** [comment]
Where did you read about that behavior?

**Comment by lgarcia11** [comment]
@pedrobaeza I'm couldn't really find any documentation explaining how the barcode system works. I got the idea of that behavior from this file https://github.com/odoo/odoo/blob/6dff3024d19c9dd44c71992469540e3f09dd3247/addons/barcodes/static/src/js/barcode_form_view.js#L14

**Comment by pedrobaeza** [comment]
Me neither, but please ask about it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), not here.

Closing this as there's no issue, but doubts.

**Comment by Yenthe666** [comment]
I don't actually think it is supported either?

**Comment by lgarcia11** [comment]
I try it with a barcode scanner connected to a computer and it's working as described. So the issue seems to be only with the mobile app. Can we please reopen the issue?

**Comment by abbercyd** [comment]
Cessna



Sent from my Mi phone
On lgarcia11 <notifications@github.com>, Mar 20, 2020 11:11 PM wrote:

I try it with a barcode scanner connected to a computer and it's working as described. So the issue seems to be only with the mobile app. Can we please reopen the issue?

**Comment by pedrobaeza** [comment]
Mobile app doesn't support that.
