### ISSUE TITLE
Wrong language used when sale order line's description is taken from quotation template

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#48068]
Impacted versions:
- 13.0
- 12.0

Steps to reproduce:
- Install quotation builder
- Open quotation templates (Sales -> Configuration -> Sales orders -> Quotation Templates)
- Edit the default template and add a line with a customized description
- Using another language, edit the same description
- Create a sale order and set a customer whose language matches the second language

Current behavior:
The line description is in the original language

Expected behavior:
The line description should be in the customer's language, or at least in the user's language. Thhis also occurs if the customer is set after setting the quotation template.

The above occurs because the sale order line's description is set by [an onchange](https://github.com/odoo/odoo/blob/6dff3024d19c9dd44c71992469540e3f09dd3247/addons/sale_management/models/sale_order.py#L66) executed when the template is changed, [taking the language from the customer](https://github.com/odoo/odoo/blob/6dff3024d19c9dd44c71992469540e3f09dd3247/addons/sale_management/models/sale_order.py#L71). However, when that happens, the customer is not set yet and [the onchange for the customer](https://github.com/odoo/odoo/blob/6dff3024d19c9dd44c71992469540e3f09dd3247/addons/sale_management/models/sale_order.py#L42) only sets the note.

**Comment by luisg123v** [comment]
opw-2227060

**Comment by arj-odoo** [comment]
Thanks for your submission. This has been fixed in master.
https://github.com/odoo/odoo/commit/7636abd7246c3566c70dbd62fac12f4f8e33afed
Could you test on a latest runbot ?
