### ISSUE TITLE
[8.0] BoM ValueError: ""float division by zero" while evaluating

### ISSUE THREAD

**Issue by ccarly** [odoo/odoo#4807]
Please enable constrain of product_qty > 0.0, for mrp.bom

**Comment by Yenthe666** [comment]
Hi @ccarly ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Please do add more information on bug reports in the future.

Regards,
Yenthe
