### ISSUE TITLE
Sitemap is not Multi-website wised for product categories in odoo12

### ISSUE THREAD

**Issue by frankmiao2015** [odoo/odoo#48078]
Impacted versions: 12.0

Steps to reproduce and Current behavior: : 
Enable multi-website function. Set website A and website B. Create a product category "category for website A" which belong to website A only. Then open www.websiteB.com/sitemap.xml, you will find www.websiteB.com/shop/category/category_for_website_A is there. And if you manually open the link, you will get 404 error which is bad for SEO. The sitemap do product wised in multi website but not category wised.

Expected behavior:
The eCommerce categories should be multi website wised for SEO purpose.

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by JKE-be** [comment]
Cannot reproduce

Are you sure that you set website_id on your category ? 

Cannot reproduce

![image](https://user-images.githubusercontent.com/4848797/77172565-6dff4d80-6abe-11ea-9cec-eb16b8530eb9.png)

**Comment by frankmiao2015** [comment]
> Cannot reproduce
> 
> Are you sure that you set website_id on your category ?
> 
> Cannot reproduce
> 
> ![image](https://user-images.githubusercontent.com/4848797/77172565-6dff4d80-6abe-11ea-9cec-eb16b8530eb9.png)

Yes, I am sure. If I did not set the website id on my category, I will not get the 404 not found page error. I have still no idea on how to set the multi website instance on runbot. If you are sure this issue do not exist on the latest odoo12, I will do a latest pull for try. Thank you.

**Comment by JKE-be** [comment]
https://drive.google.com/file/d/12nVncc5abQ38tKCSx_-WHFsPhb3T0uxN/view

You can ignore 1m10 -> 1m45... Sitemap was open in another tab, so no recording...

0s -> 1m10 : product configuration
after 1m45: I open the 2 sitemaps

**Comment by JKE-be** [comment]
video public now ;) my bad

**Comment by frankmiao2015** [comment]
> video public now ;) my bad

yes, you are right. Very sorry for the trouble, it turns out a third party issue. Thank you for the efforts.
