### ISSUE TITLE
[hr_timesheet_sheet] When adding an Analytic Account, all Timesheet Activities with 0 hours are removed

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#4809]
Hello,

My users usually complete their timesheets identifying the Analytic Accounts that they work on, and once all the A.A. have been added, they will keep completing the hours worked progressively during the period of the timesheet.

But this does no seem to be the way it works in Odoo.

Every time that you add a new Analytic Account to the Timesheet, you MUST complete with hours at least one day. Otherwise, at the time of adding any other Analytic Account the previous timesheet lines entered with 0 hours are automatically removed.

Regards,
Jordi.

**Comment by Yenthe666** [comment]
Hi @jbeficent,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
