### ISSUE TITLE
Landed page is incorrect when the user revisit the survey which he click 'previous' the last time

### ISSUE THREAD

**Issue by digitalsatori** [odoo/odoo#4810]
This is the related issue for #2680 
commit f937690 only prevent the system from crash, when the below special case happened:
#special case if you click "previous" from the last page, then leave the survey, then reopen it from the URL, avoid crash

However, If clicking "previous" from any page in between , then revisit the survey, the landed page is till wrong.
Example: we have 10 pages for a survey, and we answered till **page 5** and I click 'previous' to go back to **page 4** and leave
when I revisit the survey, I expect to see **page 4**, but  we got  **page 6** instead.

commit f937690 may consider a temp workaround for the crash issue but not a real fix

**Comment by rim-odoo** [comment]
I know this special case, but this is not fixable without adding fields... which is not worthy

**Comment by digitalsatori** [comment]
I know we can't add fields in V8.  Will this problem be fixed in the latter version then? 
adding a wonfix tag seems not right for me.
