### ISSUE TITLE
[8.0] res.partner.bank form multi company error on company field

### ISSUE THREAD

**Issue by haroldtamo** [odoo/odoo#4813]
_company field generate error when configuring bank account with user who not belong to the main company_*

Impacted versions:
- 8.0

Steps to reproduce:
1- create a new user. (Hal)
2- assign a company to that user (not the main company). In my case Odoo BE
3- connect with that user
4 - Go to Accounting>Configuration>Accounts>Setup Your Bank Acc... and click on create button
![bugmulticompanyaccount](https://cloud.githubusercontent.com/assets/9885976/5835305/5234f472-a167-11e4-890e-d7b3a80e5200.png)

**Comment by Yenthe666** [comment]
Hi @haroldtamo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
