### ISSUE TITLE
POS Config won't accept a different currency from the company currency

### ISSUE THREAD

**Issue by BIZ4Africa** [odoo/odoo#48140]
Impacted versions:
Odoo 13.0+e (Online)
Steps to reproduce:
1. Activate multiple currencies (let it be USD and CDF)
2. Set company currency as USD (example)
3. Create Sales Journal for forein currency - ie 'POS Sales - CDF' 
4. Create Payment method for foreign currency - ie 'CASH CDF'
5. Create new POS with both payment method as (CASH CDF) and payment journal as "POS Sales - CDF"

Current behavior:
When you validate, you get below error message.
![image](https://user-images.githubusercontent.com/30595027/77192740-b54d0480-6ae5-11ea-80c9-b04834c449c0.png)

Expected behavior:
It should be accepted, as conditions are matched

**Comment by pedrobaeza** [comment]
Not sure, but I think it's because you are mixing in the same POS several currencies

**Comment by BIZ4Africa** [comment]
Hi @pedrobaeza,

I have all three in same currency.
1. Sales Journal
2. Payment method
3. Pricelist 

in pos_config.py - _check_currencies method, you'll find this:
`        if any(self.available_pricelist_ids.mapped(lambda pricelist: **pricelist**.currency_id != self.currency_id)):
            raise ValidationError(_("All available pricelists must be in the same currency as the company or"
                                    " as the Sales Journal set on this point of sale if you use"
                                    " the Accounting application."))`

I think **pricelist.currency_id** should be actually be **self.pricelist_id.currency_id**
I proposed it in PR #48141

**Comment by pedrobaeza** [comment]
OK, great, let's close this then as you have a PR solving it and it continues on the PR.
