### ISSUE TITLE
 Alerts without buttons

### ISSUE THREAD

**Issue by TEAM-CODESIGN** [odoo/odoo#48152]
Impacted versions:
12.0

Steps to reproduce:
Create a new item and discard it

Current behavior:
It shows the alert if I am sure I want to discard, but it does not have buttons.

Expected behavior:
What if I have the buttons

Video/Screenshot link (optional):

**Comment by TEAM-CODESIGN** [comment]
Important when I'm in developer mode if the alert buttons are seen.

**Comment by pedrobaeza** [comment]
I don't understand the issue you try to describe.

**Comment by sswapnesh** [comment]
Do you mean this ?
![screenshot-localhost_8069-2020 03 22-23_03_17](https://user-images.githubusercontent.com/16624719/77255980-5a581080-6c91-11ea-8536-46c4d94e5d41.png)


I have experienced same thing on Chrome (Old version) but Enabling developer mode solves this.

**Comment by luisg123v** [comment]
I also experienced this once on a rasonably-recent version of Firefox. The solution was (you won't believe it) clearing the browser's cache.

**Comment by pedrobaeza** [comment]
Then this seems something local, so I close.
