### ISSUE TITLE
time off module design glitch

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#48216]
Impacted versions:
13.2

Current behavior:
in form view fields are not aligned  

Expected behavior:

in form view fields must be aligned 
Video/Screenshot link (optional):

![Screenshot_2020-03-23_21-49-25](https://user-images.githubusercontent.com/62560455/77338736-c188ca00-6d50-11ea-93d8-61dc92e9b505.png)

**Comment by sangitassh** [comment]
@Yenthe666

**Comment by sangitassh** [comment]
@Yenthe666  ping

**Comment by sswapnesh** [comment]
> in form view fields are not aligned

I think this was on Purpose , Ref https://github.com/odoo/odoo/commit/02b27c1bd70df1eb70d2b3af3beeeaef9ac47701
Cc @tivisse

**Comment by sangitassh** [comment]
ok thank you
