### ISSUE TITLE
stock quantity at location level in Stock Valuation Report

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4821]
Dear Odoo Support,
I've performed the Stock Valuation Report and totalized for location.
The result is wrong for acceptance movements where three steps procedure has been performed.
Stock is stored in Stock location and the report shows quantities in Input location.
Regards
claudio

PS please note the Current Inventory Valuation Report has the same behaviour.

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
