### ISSUE TITLE
Supplier invoice: cannot select PO in the filed Auto-Complete

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#48214]
Impacted versions:
12.0
Steps to reproduce:
create more than 160 Purchase order in the state to invoice

Current behavior:
odoo return only the first 160 lines if I want to select the oldest PO it not gonna be shown in the list

Expected behavior: 
search in all the purchase order to be invoiced  even if it's oldest than 160

**Comment by pedrobaeza** [comment]
Are you talking about the "Search more..."? Press enter again in the popup dialog and you get whole recordset.

**Comment by m3asmi** [comment]
I hade an other state of purchase.order so it was not select in the purchase.bill.union
