### ISSUE TITLE
project module design glitch 

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#48218]
Impacted versions:
after 13.0

font size of name of name of project is same as font size of customer which is not looking good either you can hide the name of customer or you can remove the name of customer in kanban view 
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![a](https://user-images.githubusercontent.com/62560455/77339931-8be4e080-6d52-11ea-9136-3d2aeaad2fed.png)

**Comment by sangitassh** [comment]
@sswapnesh ping

**Comment by sangitassh** [comment]
@pedrobaeza ping

**Comment by sangitassh** [comment]
@tivisse ping

**Comment by pedrobaeza** [comment]
I don't see that as an issue and is a matter of taste. For me it's better this way.

**Comment by Yenthe666** [comment]
Indeed, that is personal taste and can hardly be called an issue or bug. For me this is worth an auto-close honestly @pedrobaeza

**Comment by pedrobaeza** [comment]
At your command!
