### ISSUE TITLE
[Wishlist] Project: Add Button to See Project Overview from Form view

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#48220]
Impacted versions: 13.0
 
Steps to reproduce:  Open Project Menu

Current behavior: Opening Project Overview is Possible from Kanban only
![screenshot-1869843-13-0-677401 runbot29 odoo com-2020 03 23-22_36_47](https://user-images.githubusercontent.com/16624719/77342836-d1a3a800-6d56-11ea-9a4d-a29b29eb343e.png)
![screenshot-1869843-13-0-677401 runbot29 odoo com-2020 03 23-22_37_19](https://user-images.githubusercontent.com/16624719/77342881-dec09700-6d56-11ea-87da-18ba8ccd2ebc.png)

Expected behavior: We should have Button on Project Form view to Open this veiw
![screenshot-1869843-13-0-677401 runbot29 odoo com-2020 03 23-22_37_38](https://user-images.githubusercontent.com/16624719/77342966-fa2ba200-6d56-11ea-9bd7-88d055856a2a.png)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Why dont' you make a 2 minute PR instead of an issue for a small improvement?

**Comment by sswapnesh** [comment]
> Why dont' you make a 2 minute PR instead of an issue for a small improvement?

I tried but Couldn't find from where that Button (Which Open this Qweb view) is added. :-1:  of me

**Comment by sswapnesh** [comment]
@Yenthe666 Added https://github.com/odoo/odoo/pull/48375
Thanks

**Comment by Yenthe666** [comment]
Thanks man, great job!
