### ISSUE TITLE
error in scheduling dates in reorder point procedure

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4827]
Dear Odoo Support,
I've noticed the reorder point procedure schedules forward and not backward.
The result is to have schedule dates in the past.
Perhaps I've missed something in system setting.
Regards
claudio

**Comment by ccandito** [comment]
Dear Odoo,
the reorder point procedure is very important. 
one of the mail feature is the scheduling forward (PULL model) instead of backwards typical in MTO scenario (PUSH logistic model).
its parameters should be included in a tab of product master data.
Two reports are necessary: one to recap ROP parameters and the mail one to list by date the positive and negative planning elements.
I could provide you all details for proceeding on development phase.
Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
