### ISSUE TITLE
Background image path wrong with werkzeug v. 0.16.0

### ISSUE THREAD

**Issue by thartmann15** [odoo/odoo#48353]
Impacted versions: 13

Steps to reproduce: use werkzeug v. 0.16.0 and install website module in a fresh database.

Current behavior: When you have to choose a theme, no background image is displayed for the themes. The log error message:

2020-03-24 15:58:13,326 11080 INFO odoo0 werkzeug: x.x.x.x - - [24/Mar/2020 15:58:13] "GET /web/image/theme_default/static/description/theme_default_screenshot.jpg HTTP/1.0" 404 - 478 0.431 1.020

The path is wrong: /web/image/ is incorrect.

Expected behavior: The correct path should be /theme_default/static/description/theme_default_screenshot.jpg

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You should use the werkzeug version indicated on requirements:

https://github.com/odoo/odoo/blob/428d2dc3f86dc49bfc1c9955f1bfb746eed55426/requirements.txt#L44

but any way, if you can detect the conflicting lines in the code, then this can be amended.

Meanwhile, I'm afraid this can't qualify for a bug.

**Comment by thartmann15** [comment]
Thank you. Next time I will carefully check requirements.txt to make sure I picked the right version.
Concerning werkzeug 0.16.0: As I could not see any other error message I have no clue where the problem originates.

**Comment by pedrobaeza** [comment]
But the same problem happens using the other version?

**Comment by thartmann15** [comment]
I downgraded to werkzeug v. 0.14.1 and created a new database. Then everything worked as expected: The background image had the right path and was displayed.

**Comment by pedrobaeza** [comment]
Then let's close this, but if you locate the possible problem in source code of the module it can be treated.
