### ISSUE TITLE
[V8]Procurement Bug in Multicompany environment

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#4837]
In the product information, we have supplier info.
This supplier info is used to select the supplier when we generate the procurement for automatic request for quotation(purchase order) creation.

The problem is, on the multicompany environment.
Supplier info has a company field, but the procurement not run based on that field.

Example:
I have:
Parent company
Brother company (the parent is parent company)
Sister company (the parent is parent company)

We have product A, that buy and make to order . This product is share to all company(we give blank value in company field)

In the supplier info:
First, We select supplier A, and set the company for brother company
Second, We select supplier B, and set the company for sister company

When we create a sale quotation for product A in sister company environment, and confirm it.
We run the procurement, the system will select the supplier A. This is wrong.
It must be supplier B because the procurement is for sister company not brother company.

From my point of view, this bug happen in Odoo version 8 because when we run the scheduler,
the code change the user to SUPERUSER_ID to run the process, before its uid. That's why the multicompany rule not apply on it.

I have report this to Odoo support, and they really slow to handle this even I have support hours.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=VckPKntBvGSDY6oQHmTKNmiMqKv9JDkHyFqq4fwQ4dU%3d&docid=0b05826e571a747a9930f7abed1a2ae27

**Comment by zbik2607** [comment]
Related: https://github.com/odoo/odoo/issues/4627

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
