### ISSUE TITLE
[V8]Bug in Internal Transfer

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#4838]
So before I make an internal transfer, I check the quants first for product: GLASS DOOR A
And I found I have the stock 99 in defective supplier scrap
and I want to move it to supplier rework area.

And then I make an internal transfer for this product, I test with 100 quantity, and I marked it as to do.
The problem is: 
1.  The system tell me that the availability is 100 (it should be 99)
2.  When I check the availability, the system reserved the 100 (it should be just reserved the 99)
3.  When I click transfer, the system tell me to move 75 from defective supplier scrap to rework area, and 25 from rework area to rework area. (This behavior is very strange)
4.  When I delete the 25, and change 75 to 100, I can do it. But when I check the quants, only 75 quantity that takes into the account of computation quants. (should be 100)

This is the video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=Hu1wpEuRNhboD9g4KLz5FOWIl8z%2bIb6PDzKWb7WMV9Y%3d&docid=01ad8fc3e9ce745e1b79617e1b00439f6

I already report this to Odoo support, but they really slow to handle this. Even I have Odoo support hours.

**Comment by kazacube-damien** [comment]
Hi I confirm this issue. Any help will be great. (Your video should be posted on youtube or something like this since it's too big)

**Comment by falinwa** [comment]
Hello, we are in China, and Youtube is block on our country.
We are really hope this bug is fixed.

**Comment by kkoci** [comment]
Is this fixed?

I have the same issue =(

**Comment by falinwa** [comment]
as our bold discussion with Odoo support,
they decide that they will not fixed this bug until version 9.

So we decide to developed a module that handle that kind of behavior.

**Comment by kkoci** [comment]
=/ This is upsetting

Is your module open source?

**Comment by GoodERPJeff** [comment]
Any news about this issue ?

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
