### ISSUE TITLE
owner of moves is not propagated by pull rules

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#4839]
The owner of the move (the `restrict_partner_id`) even though it is hidden by default, is indeed the field which is used when making stock reservations. It should be propagated when pull rules create new procurements and chained moves.

To reproduce:
- configure the warehouse as 3-step (pick-pack-ship)
- create a picking with a move from **output** to **customers**. The move should have the field `restrict_partner_id` set.
- chained moves will be created automatically. The `restrict_partner_id` is not set on those.
  The result is that the moves from **stock** to **output** will reserve stock with no owner, while the last one will look for stock with owner set, which does not make sense since the moves are chained.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
