### ISSUE TITLE
Issue or task thread does not use project email alias for reply-to, Bug?

### ISSUE THREAD

**Issue by emagma** [odoo/odoo#4845]
Hi,
Odoo 8.0 (20141231 nightly) + Project module
Unsetted mail.catchall.alias and mail.catchall.domain

I am trying to maintain a basic workflow for communicating by email around a task (or issue)
My project is configure with email alias
`myalias@mydomain.com`
Every email sent to `myalias@mydomain.com` then opens a new task;
When a follower A uses the UI to post a reply, follower B receives an email.

If follower A answers his mail directly on his webmail, mails goes to B email address, no to myalias@mydomain.com, then Odoo doe not catch the message and communication went out of the platform.

When project alias is set, shouldn't the expected behavior be to set reply-to to that alias?

**Comment by emagma** [comment]
Hi there, any advice on this one?

**Comment by Yenthe666** [comment]
Hi @emagma,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
