### ISSUE TITLE
Star / Unstar message doesnt work

### ISSUE THREAD

**Issue by ristecona** [odoo/odoo#48475]
Impacted versions:10 EE

Steps to reproduce: Go to discuss module, click on the Mark as to do, doesnt work, but refresh the page, it is starred / unstarred

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
This is a problem of your deployment, where longpolling is not correctly configured.

Closing as no apparent issue. Comment back if you are to reproduce the same problem on runbot (https://runbot.odoo.com - admin/admin).
