### ISSUE TITLE
[12.0] Product moves listing doesn't apply to forecasted quantities

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#48487]
Hello,

Some of our clients noticed that some of their products' forecasted quantities didn't add up in the product moves listing.

This is true for products used in manufacturing: they create an MO and then a picking in order to fill in that order and thus the product's forecasted quantities are updated to show that some quantities will be used for that MO. However, these product moves will not show in the product's moves listing, which doesn't give the user a good overview, and it'll seem that the numbers don't add up (which is a common complaint).

We haven't tested this in v13.0, but this happens in several v12.0 servers and runbot.

Thank you.

**Comment by pedrobaeza** [comment]
Please depict clear steps to reproduce the problem in runbot.

**Comment by reinaldoramosarxi** [comment]
Hello,

1. Create a new MO for a product (don't do any more actions on it) and keep track of its materials, namely the forecasted quantities and the product moves;
2. The products' forecasted quantities will be updated to reflect this usage but the product moves won't reflect this move, making it hard (not impossible) to find where exactly the product is being used.

Thank you.

**Comment by pedrobaeza** [comment]
Reinaldo, that's not clear steps, just some tips. Specify exactly where you go, what do you input (with demo data or specify which data you create).

**Comment by pedrobaeza** [comment]
Closing as no more answer.
