### ISSUE TITLE
[8.0] buy rules not created for a new warehouse

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#4853]
To reproduce:
- start with a base 8.0 instance from runbot
- install the module **stock**
- create a new warehouse
- install the module **purchase**
- now the new warehouse has the field **Purchase to resupply this warehouse** already selected by default.

However, the "buy" procurements do not work for the new warehouse, because no procurement rules have been created for it.

Workaround: in the new warehouse, deselect and select again the **Purchase to resupply this warehouse** checkbox and save.

This does not happen with the original warehouse on a demo instance because the issue has been worked around in `addons/purchase/purchase_demo.yml`, but clearly this does not seem like a good solution.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
