### ISSUE TITLE
Odoo 13: Mail Reply to Catchall - Information

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#48541]
Impacted versions: Odoo 13

I have already collected a lot of information and I have tried many ways to make it possible to respond to an email sent from Odoo 13 to a specific user.

I currently have Google Gsuit email accounts (free, no paid).

I would like to make the following queries:

1. Is it true that Gsuit does not allow emails to be redirected to aliases in Odoo 13?
2. Is it true that the Odoo 13 version does not allow receiving emails in the Odoo inbox?
3. If all email messages that come out of Odoo 13 are going to have an option to reply to Catchall, then will aliases only serve to communicate internally?
4. Are there any solutions and settings that you can recommend to make responding to not be catchall? I've already tried removing the option from the system parameters (it worked but Odoo 13 no longer feeds back with the responses), and setting the email in the templates doesn't work or maybe I'm doing it wrong.

Thank you for your attention, and I apologize if I have not mistakenly raised this issue in the right place.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by LSR29** [comment]
Thanks!
