### ISSUE TITLE
Qweb parsig errors not verbose enough

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#4854]
Affected versions: 8.0

Current behavior:

When a rendering error occurs in Qweb reports the stack trace provided does not give any indication of the element it was trying to render nor the line it was encountered.

It also does not provide the rendering error as it would if raising an error just after self.render_element method call in ir_qweb.py

Expected Behavior:

A verbose stack track regarding the element that failed rendering in the xml report so the user can quickly identify it and apply a fix without flailing around

**Comment by blaggacao** [comment]
I support this quest! :100:
It seems relevant to add, that in my case the rendering error did corrupt the database.

It left orphaned values in the table `accounting_reporting` after throwing an error when trying to render a report.

**Comment by sle-odoo** [comment]
Hi,
Do you have an example where the traceback is not useful at all?

**Comment by PCatinean** [comment]
Hi,
It has been over a year since the issue I can't remember for sure where the issue was. The qweb views have a good stack trace in the client but I think reports still do not.

For example when printing a report and messing up a t-field, it does not tell you which element it failed rendering, and if you have a huge report it's pretty nasty.

**Comment by sle-odoo** [comment]
I think the issue you're referring was fixed in rev https://github.com/odoo/odoo/commit/08604812d81c42904f2eebd7f453bcdcbf060642

With this patch, the whole stacktrace is shown in the webclient.
If you're still facing it, feel free to comment and i'll reopen.
