### ISSUE TITLE
[8.0] Content-type value of response header is wrongly set for attachment downloads from One2Many Widget

### ISSUE THREAD

**Issue by 10537** [odoo/odoo#4856]
Description

When an attachment is downloaded from a One2many widget, Odoo set the content-type value to 'application/octet-stream'. All file are downloaded as .bin files.

Impacted versions:

8.0

Steps to reproduce:
Using Firefox, with a clean Odoo install:

Install the Document module
Create a simple module with a link One2Many to model with attachment file and show this files in a One2Many widget
Go to the test module
Upload an image file attachment
Download the file attachment from the One2Many widget

Current behavior:

Firefox will download the as .bin file.
Expected behavior:

Firefox should download the file with the correct extension.
Additional information

'application/octet-stream' is hardcoded in the _format: method of ./addons/web/static/src/js/list_view.py
The content-type header should contain the file_type of the ir.attachment
Reference https://github.com/odoo/odoo/blob/b1f1596aef5e8968d22abb63f9e7bf8da72b009b/addons/web/static/src/js/view_list.js line 2298

**Comment by Yenthe666** [comment]
Hi @10537,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
