### ISSUE TITLE
[7.0-8.0-master] self.pool['account.move.line'].search(cr, uid, [('invoice', '=', False)]) always returns []

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#4857]
Here are the steps to reproduce the issue on an up-to-date openerp/odoo v7 or v8:
1) create a new DB and install the account_accountant module
2) In "Journal Items", create manually a new account move with 2 account move lines in the Misc journal (for example). So these 2 move lines are not linked to an invoice.
3) execute the following code:

```
res = self.pool['account.move.line'].search(cr, uid, [('invoice', '=', False)])
print "res=", res
```

It will print : res = []
That's a bug : it should return at least the IDs of the 2 move lines created at step 2.

Code analysis:
The 'invoice' field on account.move.line is a function field that has a fnct_search : this function is _invoice_search() in odoo/addons/account/account_move_line.py line 372.
When this method is called with args= [('invoice', '=', False)], then the value of qu1 will be  "AND(i.id IS NULL)" and qu2 will be [], so it will execute the following SQL query:

```
SELECT l.id FROM account_move_line l, account_invoice i WHERE l.move_id = i.move_id AND (i.id IS NULL);
```

and this SQL query never returns any record, so the _invoice_search() method returns [('id', '=', '0')]

**Comment by alexis-via** [comment]
On a side note, the code of the function _invoice() which compute the 'invoice' function field is surprising: 'invoice' is a many2one field, so we just need to return a dict with key = move_line_ID and value = invoice_ID or False. Here, the code returns a dict with key = move_line_ID and value = (invoice_ID invoice, name_get of invoice), which is not necessary. So the 7 last lines of the method _invoice() above "return res" can be dropped !

**Comment by alexis-via** [comment]
This bug also affects master.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Do you still face this issue?

**Comment by alexis-via** [comment]
AFAIK, the bug is still present. The patch that I proposed in my PR is still applied on the odoo for my customers that are impacted by this issue. I didn't test recently without my patch to confirm that the bug is still there... but it's easy to test with the simple scenario that I posted above.

**Comment by Yenthe666** [comment]
Hi @alexis-via ,

Thank you for your bug report.
At this point Odoo 7 and Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
