### ISSUE TITLE
[IMP] Opening chatter document links in new tabs

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#48583]
Impacted versions: 12.0; 13.0

Hello,

Some of our clients have pointed out that whenever they're working and need to open a document from a link that has been created in the chatter, they have to open a new Odoo tab and trace their steps and only then click on the link to open the document in that new tab.

We had noticed this before and it is indeed strange that a link to a document wouldn't allow you to open the document in a separate tab (it just defaults to the main app menu).

The following is one of many examples where these messages are sent to the chatter:
https://github.com/odoo/odoo/blob/13.0/addons/crm_livechat/models/mail_channel.py#L25

Thank you.

**Comment by pedrobaeza** [comment]
For me this behavior is correct as long as you have the breadcrumb, which is true for the mentioned link.

**Comment by pedrobaeza** [comment]
@Yenthe666 what's your opinion?

**Comment by Yenthe666** [comment]
Yeah, that is desired behavior and works fine. If you're not happy with it you could inherit the messages and apply a `target=_blank` in the HTML to open a new tab I guess?
Anyways, both me and @pedrobaeza see no issue in it so let us close this.
