### ISSUE TITLE
[13.0][IMP] Add tax_repartition_line_id index

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#48597]
I have detected that this field is searched in many cases, could we add an index?

https://github.com/odoo/odoo/blob/cedfbd0379a907650db9b23f6c5203522d4ced95/addons/account/models/account_move.py#L2493

@Tecnativa

**Comment by pedrobaeza** [comment]
Can you point to some of them in code?

@qdp-odoo @oco-odoo what do you think?
