### ISSUE TITLE
[12] Approving leaves by manager 

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#48599]
Impacted versions:12.0

Manager cannot confirm leaves of his employees !
in this view the `hr_holidays.edit_holiday_status_form` 
**validation_type** **must be visible** so we can choose validation by manager  otherwise it will never be the case!
```
 <group name="validation" string="Validation">
                            <!--field name="validation_type" widget="radio" invisible="1"/-->
                            <field name="validation_type" widget="radio"/>
                            <field name="double_validation"/>
                        </group>
```

**Comment by pedrobaeza** [comment]
Please specify clear steps to reproduce the problem from beginning to end. You are exposing your conclusions but not how to get there.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
