### ISSUE TITLE
POS Accounting Entry Posting Date- Session Opening Date, Closing Date or Posting Date ?

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#486]
POS Session Opening date is " 31-Dec-2013 10:11:12 " - After the sales shop closed late night

The Session Closing time will be " 01-Jan-2014 02:15:05 "  And the next day is off , because its new Year

Accounts trying to post the entries on 02-Jan-2014 after verifying the cash balance and Sales

While posting acounting and stock entries will be generated on 02-Jan-2014.

Actually they want to show the sales as on 31-Dec-2014 and closing stock also effected as on 31-Dec-2014

We have introduced One more date in Session called "SALE DATE" , Irrespective of date of sales - Corresponding Entries will be generated on " SALE DATE:"  

But No Luck , Still its posting on the date of posting, Any One can help me to configure this

**Comment by Yenthe666** [comment]
Dear @orchidinfosys,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by hemnanikalpana** [comment]
Hi Yenthe,

We are also facing the same issue in version 10. I also checked in version 13 on runbot. Result is same.

Test Case:
Session opening date: 18th Feb 2020.
Session closing date: 19th Feb 2020.
Total transaction value: $500
**POS Transaction for 18th: $200
POS Transaction for 19th: $300**

Now the journal entry will be posted on the 19th for $500. In this case, accounts won't be able to reconcile sales for the below reasons:

**Date| Sales |Accounting**
-------------------------
18th | $200|                0
19th | $300|         $500

**Comment by Yenthe666** [comment]
@pimodoo could you check?

**Comment by pimodoo** [comment]
@lap-odoo what do you think about this use case?

**Comment by lap-odoo** [comment]
@orchidinfosys In V13, you can easily correct the date of the accounting entries generated by the PoS. 
@hemnanikalpana You are supposed to close your Point of Sale every day. One accounting entry is created per PoS Session (not per day).

**Comment by hemnanikalpana** [comment]
@lap-odoo  Thanks for your reply. We are doing this daily basis only. Even one accounting entry per PoS session is also fine. Our issue is for the accounting entry date.

So let's take 1 use case: Here we are talking about **version 10 to 12.**
For some of the reasons, the session is not closed on the same day or (let's say some rescue session, which synchronized the other day). So in these cases, POS sales will never match with revenue.

How we will justify this.

I appreciate your suggestion on this.

Best Regards,
Kalpana

**Comment by lap-odoo** [comment]
Hello @hemnanikalpana , 

The manual correction I'm talking about only makes sense if this is an issue that happens from time to time (example: exceptionally, you couldn't close the session on the right day for some reason). 

If the problem is that you have many sessions overlapping two days, I wouldn't change anything about it. I don't really see the issue in having the accounting entry on the second day. It probably means you have some sales on day 1 and some sales on day 2, right? So no matter if the accounting entry is made on the day 1 or the day 2, part of it applies to day 1 and part of it to day 2.

**Comment by hemnanikalpana** [comment]
Hi @lap-odoo ,

Thank you so much for your response. 

Well on technical perceptive I will agree there is no issue.

But on the client's perspective, while having 200+ sessions and an average of 15000 transactions per day, reconciliation on a weekly / daily basis, the sales and cash entries will not match with the sales report. Also, please consider the month-end / year-end situation.

Awaiting your valuable feedback. 

Best Regards,
Kalpana

**Comment by lap-odoo** [comment]
@hemnanikalpana All the accounting entries will be made on the same date, so I don't really see the issue for the reconciliation. Except if you're not talking about the accounting reconciliation process but something else? For month-year end situation, again, you have two options. Manually change the date if you want the sales to appear in the last month or keep it as it is and accept the sales of the last day will be recognized on the next month.
