### ISSUE TITLE
[13.0]widget : section_and_note_one2many \ section_and_note_text can not use without account module

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#48626]
Impacted versions:
13.0

Steps to reproduce:
when develop a system using widget:section_and_note_one2many and widget:section_and_note_text , but there is not need to install account module, It can not work. Because these two widgets are defined in account module.

Expected behavior:
Move these widgets to web module ?

**Comment by pedrobaeza** [comment]
This is done for now on purpose, as there's no sense in core of using that without depending on `account` module, and this can't be done in a stable version.

@Feyensv can say if this can be considered for master branch.

**Comment by Feyensv** [comment]
The section_and_note widget is only for the purpose of lines on a model, having multiple functionalities, and therefore only used in account/sale/purchase.  It mainly targets a specific functional case (which is not very clean from a technical point of view) and doesn't have much generic purpose.

I don't think it will ever be moved to `web` unless you can provide a generic purpose it could have in custom modules and/or modules without `account` as dependency.

**Comment by tanghulu0608** [comment]
We are developing a system, using odoo as develop framework. We just need to install some basic modules, like web 、base 、mail. We do not need sale、purchase、stock and account. widget section_and_note_one2many is very cool, so we want to use it, but without account module installed.

**Comment by tanghulu0608** [comment]
this is some thing like this: [[FIX] fix the display of pdf_viewer](https://github.com/odoo/odoo/pull/26449)

**Comment by pedrobaeza** [comment]
It doesn't sound like reinventing the wheel is a good thing honestly, and you are not indicating at the end why you need it.

**Comment by tanghulu0608** [comment]
Currently, we use odoo as a develop framework, we don't needs erp modules , just the MVC framework.
And we want to use section_and_note_one2many.we are not reinvent anything that already exists in odoo.

**Comment by pedrobaeza** [comment]
OK, last word for @Feyensv, but I see that you want to reinvent sale/account modules if you want that widget out of them.

**Comment by tanghulu0608** [comment]
just move the code.  Not much work to do .

**Comment by Feyensv** [comment]
As said, this widget is highly linked to the `display_type` logic in the corresponding modules.  I keep finding no use to overload `web` with targeted widgets that have no generic use globally...

Unless in the future we need the section_and_note in a module independent from `account`, It'll probably stay there.

**Comment by tanghulu0608** [comment]
@Feyensv Thanks.

**Comment by dominiquekonsuntack** [comment]
we used this widget in a customisation of the quality module: 
- We created quality.check.line, and created section and notes, so as to group the quality "instructions", and this is finally used for printing a quality check report. 
- Because we also use the sales/invoice module, it was OK. 

Just to say that this widget can be used for other purposes than sales/invoice

**Comment by tanghulu0608** [comment]
@dominiquekonsuntack  Yes, I agree with you too.
