### ISSUE TITLE
POS invoice button not being translated [Solution in comment]

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4863]
**There is no _t() statement to translate this button*

**I've made a fix for this here: https://github.com/Yenthe666/odoo/pull/1** I'm just not sure how to do a pull in Odoo here.
Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Open a session for the POS
 2. Click on a payment method
 3. You will see the buttons 'Back', 'Validate' and 'Invoice'.
 4. Install a second language, set is as active, re-start your session and click on a payment button. All the buttons will be translated except the button 'Invoice'.

Current behavior:

 - Button 'Invoice' is never translated because there is no _t() statement around this button

Expected behavior:

 - Button is translated thanks to the _t() statement around the text.
This should be done is /addons/point_of_sale/static/src/js/screens.js
I have made a fix for this here: https://github.com/Yenthe666/odoo/pull/1 I'm just not sure how to do a pull in here. Can anybody do this please?

**Comment by mart-e** [comment]
I have merged it at 51ea2a3.
To make the pull request, you just need to select odoo/odoo as target repository instead of your own.

**Comment by Yenthe666** [comment]
Thanks for applying it @mart-e! Could you give me a bit more details about creating a pull request? Should I modify the code in my github branch and then do a pull from there or? I'd love to know how to do this for future fixes.

**Comment by mart-e** [comment]
@Yenthe666 the same way you have created  Yenthe666#1, just select odoo/odoo in the target branch.

![screenshot from 2015-01-27 13 55 28](https://cloud.githubusercontent.com/assets/564822/5918726/30549186-a62c-11e4-9f2e-281a81175795.png)

You create your branch and fixes on your local repository at Yenthe666/odoo and, once it's ready, you create a pull request against the corresponding odoo branch.
