### ISSUE TITLE
[12.0] Website promotions are applied to other sales orders when copying

### ISSUE THREAD

**Issue by maitaoriana** [odoo/odoo#48634]
Impacted versions: 12.0

**Steps to reproduce:**
1. Set options multi-website and Coupons & Promotions
2. Create promotion to a website and set Promo Code Usage with Automatically Applied
3. Create a sale order and copy

**Current behavior:**
The discount line of the website promotion program is added

**Expected behavior:**
Do not add any discount line because that order does not belong to the website

**Video/Screenshot link (optional):**

https://youtu.be/337dj2yc5Bs

**Comment by Yenthe666** [comment]
@dbo-odoo is this still under your branch? ;)

**Comment by dbo-odoo** [comment]
Nope, it's @tivisse now. Probably an override of `_filter_programs_from_common_rules` missing in `website_sale_coupon`, though the described flow is unusual so no promises.

**Comment by Yenthe666** [comment]
I wouldn't call that an unusual flow though. Quite some businesses copy a quotation/order to make two versions honestly.

**Comment by tivisse** [comment]
Hello @maitaoriana 

Thanks for the feedback. I'm opening an internal task to investigate/fix this issue. 

Thanks ;)

**Comment by tivisse** [comment]
TaskID: 2228249

**Comment by maitaoriana** [comment]
@Yenthe666  The bug is that the original quote did not have the discount but a discount is added to the copy. Thanks
