### ISSUE TITLE
[13] Dashboard does not render calendar content

### ISSUE THREAD

**Issue by kaotul** [odoo/odoo#48677]
Impacted versions:
13.0 CE
Steps to reproduce:
- Add calender view in to dashboard

Current behavior:
Dashboard display only calendar header

Expected behavior:
Dashboard should display all header and content.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/10023110/78040032-1358d200-7399-11ea-9a74-1c87f1caa6c0.png)

**Comment by dhp-odoo** [comment]
@kaotul 

I have tried with the odoo 13.0 community and enterprise and it's working fine. Refer screenshot

![Screenshot](https://user-images.githubusercontent.com/50165096/94104833-9e50eb80-fe55-11ea-99ff-7625a00943f2.png)

**Comment by msh-odoo** [comment]
@kaotul Would you please confirm if it is reproduced in the latest 13.0 code, if it is already fixed and can not be reproduced then we can close this.

**Comment by kaotul** [comment]
@msh-odoo Confirmed. Thank you very for your support.
