### ISSUE TITLE
Variety of problems with the document module

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#4868]
The description of the document module:
> This is a complete document management system.
* User Authentication
* Document Indexation:- .pptx and .docx files are not supported in Windows platform.
* Dashboard for Document that includes:
  * New Files (list)
  * Files by Resource Type (graph)
  * Files by Partner (graph)
  * Files Size by Month (graph)

Problems:
* I don't see any of the mentioned dashboards, tried both on my local installation and on runbot

* It seems like the attachments do not get correctly automatically linked to the correct directory, which basically makes it impossible to see a list of attachments documents, i.e. one of the main feature of a document module.
I attached a document to a product, and I expected to find it by going to 'Know How' -> 'Directory Structure' -> 'Products', but I get an empty list. Maybe I didn't understand how it's supposed to work though (see the last point).

* Document indexation should be an optional feature to select in settings, because takes up huge amount of space on the DB while being useless for those who want to use the document module as a simple system to attach files to a record, (actually because of the previous point is useless for everyone at the moment)

* Directories form view: a lot of abstruse and undocumented options. Dynamic Contexts? Directory types? The help strings are even more confusing, e.g. 
> Each directory can either have the type Static or be linked to another resource. A static directory, as with Operating Systems, is the classic directory that can contain a set of files. The directories linked to systems resources automatically possess sub-directories for each of resource types defined in the parent directory

Maybe it's just me, I would like to have some feedback from other users.
It sure isn't clear or intuitive, especially considering Odoo wanted to [avoid documentation by having significantly improved usability](http://beta.slashdot.org/story/205911)

**Comment by fotisp** [comment]
Did you ever figure it out? I am also at a loss here

**Comment by Yenthe666** [comment]
Hi @mart-e,

Could you give your input on this one please? I agree that the document module is not as clear as it should be and, well, it lacks some neat features. Could we label this as wishlist and could you give @LeartS some more feedback please?

**Comment by mart-e** [comment]
Hello,

Actually for the document module, we went the other way around, in 9.0, (done at 3ced0ff61bd5b48e8846c30dc8a972a81f1688f4) we removed these incomplete/confusing features to leave only the core of attachment management.
Sorry but it was decided that Odoo would not focus on document management at this time.

**Comment by Yenthe666** [comment]
@mart-e just wondering, is this somewhere on the roadmap for V11 or something? I really miss good document management.

**Comment by mart-e** [comment]
Sorry but no, as said above, no plan to focus on document management at the moment.
