### ISSUE TITLE
[8.0][regression] active_id no longer guaranteed to be present while evaluating action's context

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#4869]
I've got an action with a following context definition:

```
<field name="context">{
    'search_default_project': active_id,
    'search_default_group_by_project': not active_id,
}</field>
```

There may or may not be an actual value for `active_id`, depending on how user gets to the action (directly from the menu or via another form). This used to work prior to commit 8c3d71ccb88950ecc5741c76e7217e478e2f2988 from 10 days ago. In cases when an actual `active_id` was not present the value used to default to `None`. Since 8c3d71ccb88950ecc5741c76e7217e478e2f2988 in cases when an actual `active_id` is not present the following client error is thrown:

```
Uncaught Error: NameError: name 'active_id' is not defined
```

Since 8.0 is already released and is supposed to have a stable API I presume this change in behaviour was not intentional.

**Comment by yvaucher** [comment]
I confirm this, I got the same error this morning using an `active_id` in context couldn't find from where it came.

**Comment by lepistone** [comment]
Thanks a lot @ludwiktrammer for the analysis. Same problem here.

@xmo-odoo an action with a context like the one above is correct? If yes, this is a regression. If not, do we have an alternative?

Thanks!

**Comment by ludwiktrammer** [comment]
Can we have a status on this? Can we count on this being corrected or is this new behaviour here to stay? @xmo-odoo ?

**Comment by xmo-odoo** [comment]
> @xmo-odoo an action with a context like the one above is correct?

No. The behaviour was never specified and never guaranteed, it "working" there hinged in the context being evaluable at that point (which may or may not have been the case as the evaluation context there was a small subset of the "normal" evaluation context) and broke the basic reading of actions if their context happened to be evaluable (if it wasn't the context was returned as-is, otherwise it became a serialisation of the evaluated context)

>  If yes, this is a regression. If not, do we have an alternative?

AFAIK no, there is no supported way to carry context data between actions at this point

**Comment by ludwiktrammer** [comment]
> AFAIK no, there is no supported way to carry context data between actions at this point

I'm confused. Quick search of Odoo codebase shows that official Odoo modules use the trick of using `active_id` while setting action context all over the place...

**Comment by nono6677** [comment]
I confirm this, I got the same error this morning using an active_id in context.

**Comment by flotho** [comment]
+1

**Comment by michaelkarrer81** [comment]
+1

**Comment by blaggacao** [comment]
We have experienced a similar type of error, when dealing with subtrees of `2many` fields. `active_id` did always get set to the first line `id` of the subtree. We solved this inspired by `stock/stock/py - def split_lot()` like follows:

`<button name='action_name' type='object'>`
```
@api.mulit
def action_name (self):
    view = self.env.ref('module_name.view_external_id').id
    return {
        'type': 'ir.actions.act_windows',
        ...
        'res_id': self.id
    }
```

##### In the case of subtrees:
`<field name="many2many_field" options="{'reload_on_button': True}">`
did the elegant refreshing of the view (which isn't neither documented in no place on earth)

**Comment by Yenthe666** [comment]
Hi @ludwiktrammer,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
