### ISSUE TITLE
[13] Optional columns - where are stored and how to restart ? 

### ISSUE THREAD

**Issue by adamwojt** [odoo/odoo#48738]
This is just the question. 

I wonder where are optional columns (hide/show) stored in Odoo and how to restart them to default. Is there a way to restart that every time form is opened? 

Not a JS expert, but I see something happening [here](https://github.com/odoo/odoo/blob/13.0/addons/web/static/src/js/views/list/list_renderer.js#L305-L316).

**Comment by pedrobaeza** [comment]
This is question, not an issue, and should be done in forums.

Quick answer though: it's saved in browser local storage.
