### ISSUE TITLE
[13] mrp: Work order should not be deleted from calendar

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#48734]
Impacted versions: 13.0

Steps to reproduce: Plan MRP order --> Create Work orders

Current behavior: User can switch to Calendar mode and Delete Work order while Delete is already disabled on List/Form
![screenshot-localhost_8069-2020 04 01-21_33_30](https://user-images.githubusercontent.com/16624719/78159676-7f523d80-7460-11ea-8579-963d2fb9f0c9.png)

Expected behavior: Cannot delete the work order

Video/Screenshot link (optional):

------------------------
I just get to know  there is no such option `delete=0` on the calendar view.

**Comment by pedrobaeza** [comment]
@amoyaux maybe you can take a look to this

**Comment by amoyaux** [comment]
@oma-odoo

**Comment by amoyaux** [comment]
@pedrobaeza We did it in saas-13.2. Unfortunately delete="0" do not work in 13.0. You can check https://github.com/odoo/odoo/pull/40716

**Comment by pedrobaeza** [comment]
Thanks for the followup, then we should close this as fixed in saas-13.2/v14, but won't fix in current stable versions.

**Comment by sswapnesh** [comment]
Still I think this should be handled at models level.
WO should not been deleted if it's linked to Running PO.
What do you think @amoyaux ?
