### ISSUE TITLE
auth_openid need to be megrate from OpenID2 to openID Connect 1.0

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#4873]
Hello,

Could you please take in consideration this [announcement from Google](https://support.google.com/accounts/answer/6135882) to still allow people to connect through _auth_openid_ module on any odoo versions ?

Bellow the schedul plan pick [here](https://developers.google.com/accounts/docs/OpenID#shutdown-timetable):
Schedule for user-visible changes to the approval page:
- November 18, 2014: User-facing warning message may be shown on consent dialogs, directing users to this help article. Developers may suppress deprecation warnings by adding the openid_shutdown_ack parameter, as specified above.
- December 1, 2014: Auto-approval is disabled for a small number of requests on an intermittent basis, some users will be forced to re-consent.
- January 12, 2015: Auto-approval is progressivly disabled for more and more users, these users will be forced to re-consent. Developers passing openid_shutdown_ack are unaffected.
- February 23, 2015: Auto-approval is turned off, users must consent on each request. Developers passing openid_shutdown_ack are unaffected.
- March 23, 2015: Grace period for developers using the openid_shutdown_ack parameter ends, warning is shown and auto-approval turned off for all applications.
- April 20, 2015: OpenID is shut down. A static error page will be displayed on all requests. Make sure you have migrated well before this date.

**Comment by Yenthe666** [comment]
Hi @petrus-v,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
