### ISSUE TITLE
ERROR: gevent 1.4.0 has requirement greenlet>=0.4.14; platform_python_implementation == "CPython", but you'll have greenlet 0.4.13 which is incompatible.

### ISSUE THREAD

**Issue by mayanxoni** [odoo/odoo#48812]
Impacted versions: 12

Steps to reproduce:
cd odoo-12.0.post20200402
pip3 install -r requirements.txt

Current behavior: Packages in the requirements.txt are not getting installed.

Expected behavior: Packages should be installed, as all the necessary modules are installed for it.

Video/Screenshot link (optional):
![Screenshot (75)](https://user-images.githubusercontent.com/15159417/78217135-05aa6600-74d9-11ea-9afb-e792f21b5961.png)

**Comment by pedrobaeza** [comment]
This is something specific of your environment (maybe a non supported version of your Linux distribution). See https://www.odoo.com/documentation/13.0/setup/install.html for more details, and if not found the solution, please ask on the forum, but not here.
