### ISSUE TITLE
[BUG] Report not working.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#4884]
**XLS. Product lable report not working.**

Impacted versions:

 - 8.0 and above, working fine in 7.0

Steps to reproduce:

 1. product list view / form view.
 2. We had install product related XLS based report, but not showing up in product form or list view with data.
 
Why this happening with all XLS report ?

Current behavior:

 - Not show report in product form view / list view with selected records.

Expected behavior:

 - XLS report should works.

**Comment by tejastank** [comment]
Customer label working , same for product label not working ?

**Comment by tejastank** [comment]
I got product label report, but it generate issue.

ncaught SyntaxError: Unexpected end of input
http://localhost:8069/web?debug=#id=41&view_type=form&model=product.product&action=118&active_id=37:2

**Comment by tejastank** [comment]
I had resolved this issue, Now its working great for me & other all report too.
Also all our premium reports for odoo v8 working fine.

Thanks,

**Comment by sebytza05** [comment]
Hey,

How did u fix it?

Thanks
