### ISSUE TITLE
Broken handling of unlink events in o2m fields (Javascript and ORM)

### ISSUE THREAD

**Issue by ccomb** [odoo/odoo#4885]
Reproduced on a v7:
- Create or import an account statement with around 100 lines.
- Click on Edit to switch to edit mode
- Put your mouse over one trash icon at the end of the line
- Click fast to delete several lines ("fast" means: more that 2 clics per second)
- Click on Save

```
ValueError: Cannot fetch field "voucher_id" for "account.bank.statement.line" record with ID 992, that record does not exist or has been deleted
```

The problem comes from the fact that the javascript sends many identical delete events of the same line. The ORM is not able to handle several unlinks of the same id. So I think there are 2 bugs : 
- the javascript should not send twice the same delete event for a single line of a m2m field
- the ORM should be able to handle duplicated unlink orders (notice below the duplicated unlink events for id=992 : the 1st will works, and the traceback occurs at the 2nd one.
  `[2, 992, False], [2, 992, False]` : 

```
> ....parts/odoo/openerp/osv/fields.py(569)set()
-> obj.unlink(cr, user, [act[1]], context=context)
(Pdb) values
[[4, 995, False], [4, 996, False], [4, 997, False], [4, 998, False], [4, 999, False], [4, 991, False], [4, 1000, False], [4, 1001, False], [4, 1002, False], [4, 1003, False], [4, 1004, False], [4, 1005, False], [4, 1006, False], [4, 1010, False], [4, 1012, False], [4, 1009, False], [4, 1011, False], [4, 1013, False], [4, 1015, False], [4, 1014, False], [4, 1026, False], [4, 1023, False], [4, 1024, False], [4, 1016, False], [4, 1017, False], [4, 1018, False], [4, 1019, False], [4, 1020, False], [4, 1021, False], [4, 1022, False], [4, 1025, False], [4, 1027, False], [4, 1028, False], [4, 1029, False], [4, 1030, False], [4, 1031, False], [4, 1032, False], [4, 1033, False], [4, 1034, False], [4, 1035, False], [4, 1036, False], [4, 1037, False], [4, 1038, False], [4, 1039, False], [4, 1040, False], [4, 1041, False], [4, 1042, False], [4, 1043, False], [4, 1044, False], [4, 1045, False], [4, 1046, False], [2, 1008, False], [2, 992, False], [2, 992, False], [2, 1007, False], [2, 1007, False], [2, 1007, False], [2, 993, False], [2, 993, False], [2, 993, False], [2, 993, False], [2, 994, False], [2, 994, False]]
```

**Comment by ccomb** [comment]
Actually it's not m2m fields but rather o2m

**Comment by ccomb** [comment]
I just tested on latest v8 on the runbot, I get the exact same error

```
MissingError

One of the documents you are trying to access has been deleted, please try again after refreshing.
```

**Comment by Yenthe666** [comment]
Hi @ccomb,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
