### ISSUE TITLE
How to modify data-validation on E-commerce module? or how to use decimal numbers on quantities?

### ISSUE THREAD

**Issue by eranahum** [odoo/odoo#4889]
Hi,
please help, i try to sell vegetables on my website odoo shop but i need for my customers to be able to order by decimal numbers, is it possible to do?

**Comment by lukebranch** [comment]
@eranahum ,

I think this is a question that would be better posed to the community forums, as it is not a bug/issue report, but a question about an Odoo feature.

You can ask the question here:

<a href="http://help.odoo.com">http://help.odoo.com</a>

**Comment by Yenthe666** [comment]
Exactly - should have been for the help forums. Thanks @lukebranch!
