### ISSUE TITLE
Importing translation does not import source; translation fails

### ISSUE THREAD

**Issue by 88kbbq** [odoo/odoo#4891]
To reproduce the issue, navigate to Settings, then under Translations, select Application Terms-->Translated Terms. Upload a CSV with columns lang, src, source, state, name, value , type. Validations completes successfully, but translated terms are uploaded without the source, and none of the translated terms will show throughout Odoo. Also, all translated state values default to to_translate instead of translated. Bug or am I missing something?

**Comment by Yenthe666** [comment]
Hi @88kbbq,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
