### ISSUE TITLE
editable one2many list souldn't show form when click on read mode

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#48921]
Impacted versions: 13

Steps to reproduce: 

Read mode, click on A document with editable one2many list without Form view

Employee -> configuration -> plans

Current behavior: 

When you edit the document, click on one2many line will stay on the tree , it's good.

After you save the document, click on one2many line try to show the record in form view, that makes no sence to end user.  if developer didn't design form for this reacord, odoo
show default form view shows many low level detail of the record, and even show fields with GROUPS attribute on the tree field what make this a security issue. 

Expected behavior:

after save the document, when user click the one2many which are editable, just ignore the click, never try to show form. 

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1857069/78326640-76bb4d80-75ad-11ea-92a5-941571024005.png)

**Comment by intero-chz** [comment]
@GoodERPJeff that changed with Odoo 10 or 11. So i think it is a feature.

@ged-odoo would it be possible to implement this feature request as an option for x2many field widgets? Sometimes it makes sense to show/allow showing the form views, sometimes not.

**Comment by GoodERPJeff** [comment]
@intero-chz Thank you for your attention. 

I am sure it's not in 10, and 12 is the same with 13,so maybe 11 is the time, I never use 9 and 11

If it is a feature, I think this is a rarely used feature, consider the side effect, I hope it can be disable by default.

somebody suggest me a HTML attribute  style="pointer-events: none;" but I don't want add that to hundreds of my form view.

**Comment by intero-chz** [comment]
@GoodERPJeff you can also try to change the JS widgets for those x2many list views.

**Comment by pedrobaeza** [comment]
That's a matter of taste. I prefer to have the form view popup by default, although an option for disabling it is good to have.

**Comment by GoodERPJeff** [comment]
seems master branch just merge a change to add a option for this, will it been back port to 13 ?

**Comment by Yenthe666** [comment]
@GoodERPJeff no because it is an improvement and those are not backported. Since we have it in the upcoming V14 and it's an improvement there's nothing more to do solet's close it.
