### ISSUE TITLE
[8.0] Empty password in change.password.user view results in invalid 'Users' field message

### ISSUE THREAD

**Issue by mgorny** [odoo/odoo#4893]
Impacted versions:
- 8.0

Steps to reproduce:
1. Go to Settings -> Users.
2. Select a user,
3. More -> Change password,
4. Leave password empty and click 'Change password'.

Current behavior:
- The following fields are invalid: _Users_

Expected behavior:
- The following fields are invalid: _New password_

It's kinda curious. If you actually click the password field and press enter, you get the _New password_ error. Afterwards, clicking 'Change password' will trigger both errors :).

**Comment by Yenthe666** [comment]
Hi @mgorny,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
