### ISSUE TITLE
[STOCK] Wrong date in account_move_line on product delivery if Real Time Valuation is used

### ISSUE THREAD

**Issue by TheCloneMaster** [odoo/odoo#4894]
If you have Real Time inventory valuation, every product delivery registers an accounting move between Interim Delivery and Stock Valuation accounts.

Problem is that on account_move_line, the date used is "stock_move.date_expected", and not the actual date the picking is transfered.

Steps to reproduce:
Create a product with 7 days on "sale delay"
Create and validate a Sale Order for that product, with date 2015-01-25
Check for availability and transfer the related picking on 2015-01-25.
If your date is less than 7 days prior to month end, you will find that account_move_line is created in next period (february in this sample)  instead of being created in January, because it will use expected delivery date, that in this case will be 2015-02-01

**Comment by Yenthe666** [comment]
Hi @TheCloneMaster,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
