### ISSUE TITLE
stock.move in mrp not copy all data of origin stock.move

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#490]
when the product is  phantom_bom, the stock move should explode the bom, and make new  stock moves, but lost field `purchase_line_id`.
so when buy phantom_bom product, should not link the picking with PO

**Comment by Yenthe666** [comment]
Dear @jeffery9,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
