### ISSUE TITLE
Odoo Forum - user (spammer) with negative karma may publish

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4904]
User with negative karma (probably?) remain logged in and can continue to publish spam, such. answer.
See user with karma= -70 !!! - https://www.odoo.com/forum/help-1/user/370643 

UPDATE
I'm sorry I noticed there was an old question! but... spam still existed!
https://www.odoo.com/forum/help-1/question/email-invoice-to-parner-not-followers-of-document-38984

PS> spam answer removed

**Comment by smack815** [comment]
[https://www.odoo.com/forum/help-1/question/how-do-we-show-a-tree-search-view-of-issues-followed-without-using-a-record-rule-29310#answer_63018] (Answer) was either has today's date on it so I presume he added his answer today.

**Comment by smack815** [comment]
@zbik2607 maybe next time don't delete the answer record just edit it to remove the spam text so that development can review the history behind it.

**Comment by zbik2607** [comment]
If click on the spammer account, developer can see still exists answers

**Comment by tde-banana-odoo** [comment]
Closed questions are not available in search and not displayed. However indeed public users can see them currently. Currently closed questions may be duplicates, spam, ... We plan to better differentiate spam from questions closed for other reasons. Once spam is clearly identified it will not be available for public users.

**Comment by snowspy** [comment]
who can tell me? what is a good karma list for good user? please!!

**Comment by dk12dk** [comment]
may i know how to get karma? someone help me ! i am new to odoo community

**Comment by treviser** [comment]
Reading helps: read the forum guidelines https://www.odoo.com/forum/help-1/faq

**Comment by Yenthe666** [comment]
This has all been improved a lot! 😄
