### ISSUE TITLE
[8.0] Statement Operation Template should be multi-company aware

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#4907]
There is no company_id on statement.operation.template.

I'm aware fixing this would go against stable policy, so we'll do a small OCA module for this.

cc/ @Whisno @qdp-odoo

**Comment by Whisno** [comment]
@alexis-via already mentioned this issue and made a module to fix it. We discussed it in #4706

**Comment by sbidoul** [comment]
Right, I was sure I had seen that before... thanks for the pointer!
