### ISSUE TITLE
Font-family does not work in Qweb reports

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4908]
**font-family statement is ignored on QWeb reports**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Create a new report (or modify an existing one)
 2. Add style on an element and add the element font-family
 3. Print the report

Current behavior:

 - Report is printed without the font-family being applied

Expected behavior:

 - Report is printed with the font-family that is specified in the style.

Example:
I've added two elements. One with and one without a font-family like this:
```html
    <h3 style="font-family:Calibri !important;">THIS IS SAMPLE text</h3>
    <h3>THIS IS SAMPLE text</h3>
```

When I print the report out I get this:
<img src="http://i.imgur.com/VYMDEIf.png" />

When you run this, for example in a fiddle, everything works fine. Sample can be found here: http://jsfiddle.net/4zdLx827/1/

**Comment by Sameer1990** [comment]
My os is linux ubuntu 14.04 
To change the font-family and set to all report i do the following : 
1- install my font to os .
2- in my style template : 
<template id="style">
   								   body
									{
									    font-family: Times New Roman;
									}
</template>

so the report takes the Times New Roman font .

**Comment by Yenthe666** [comment]
@Sameer1990 while this <i>could</i> be a workaround it sure isn't a good thing..
You'd have to manually install the font on your system and then apply it to your styles (by default on <b>all</b> your reports)
This should really be fixed in Odoo itself.

**Comment by Yenthe666** [comment]
@sle-odoo any update on this?

**Comment by sle-odoo** [comment]
Hi,
It's working as expected. Here a sample with `Arvo` from google fonts.
```
<div class="page">

<style type="text/css">
<![CDATA[
/* Arvo */
@font-face {
  font-family: 'Arvo';
  font-style: normal;
  font-weight: 400;
  src: local('Arvo'), url(http://fonts.gstatic.com/s/arvo/v8/MViwy4K6e56oHcyeMzjbCQ.ttf) format('truetype');
}
]]>
</style>
<p style="font-family: Arvo;">Test Arvo</p>
```

![screenshot from 2015-03-02 14 49 22](https://cloud.githubusercontent.com/assets/7601090/6441780/46598dea-c0eb-11e4-8b09-fc8839e90bfb.png)

**Comment by crodriguezrossi** [comment]
Works just fine, for other people that are wondering how to get the URL of the font you need to copy the URL from google:
main site https://www.google.com/fonts#
<link href='https://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

Copy this part: https://fonts.googleapis.com/css?family=PT+Serif
and paste it on your browser, if using Firefox or Chrome it will return the font face for wotf format, if using safari you will get the ttf format.

Hope it helps, regards,

**Comment by Yenthe666** [comment]
You're talking about webfonts (through URL's) here, I'm talking about local added font files.

**Comment by crodriguezrossi** [comment]
Seems to be the only way to be done, I have tryed other ways and this is the only solution that actually works. Here is my code example for using a font to print receipt tickets:

<style type="text/css">
                    <![CDATA[
                        /* Inconsolata */
                       @font-face {
                       font-family: 'Inconsolata';
                       src: local('Inconsolata'), url(http://fonts.gstatic.com/s/inconsolata/v10/7bMKuoy6Nh0ft0SHnIGMuaCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
                       }
                   ]]>
                </style>

                <div style="font-family: Inconsolata; font-size: 1.6em; line-height:18px;">
the rest of my report
                </div>

Regards,

**Comment by eLBati** [comment]
@Yenthe666 I think [font-face](http://www.w3schools.com/cssref/css3_pr_font-face_rule.asp) is needed in this case

**Comment by lukebranch** [comment]
@Yenthe666 ,

@eLBati is right, i've had to use font-face when putting together reports with system fonts, for example:

```
  <template id="report_product_barcode_label_96_30_barrel">
    <t t-call="report.html_container">
      <t t-foreach="docs" t-as="o">
        <div class="page">
          <style type="text/css">
            <![CDATA[
        /* United */
        @font-face {
          font-family: 'United Sans Reg';
          font-style: heavy;
          font-weight: 400;
          src: local('United'), url(/usr/share/fonts/opentype/United/UnitedSansReg-Heavy.otf) format('opentype');
        }
        @font-face {
          font-family: 'United Sans Ext';
          font-style: heavy;
          font-weight: 400;
          src: local('United'), url(/usr/share/fonts/opentype/United/UnitedSansExt-Heavy.otf) format('opentype');
        }

        ]]>
          </style>
...
```

**Comment by Yenthe666** [comment]
Thank you for the extended answers & sample guys! Good job. 👍

**Comment by invitu** [comment]
Hello

In odoo v10, it seems to be super easy... That's what we did with google font Roboto :

- Inherit css with google :

`<xpath expr="." position="inside"> <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed" rel="stylesheet"/> </xpath>`

- Inherit the reports with font-family :

`<xpath expr="//div[@class='page']" position="attributes"> <attribute name="style">font-family: 'Roboto', sans-serif;</attribute> </xpath>`

- Inherit the header and footer with font-family :

`<xpath expr="//div[@class='footer']" position="replace"> <div class="footer" style="font-family: 'Roboto Condensed', sans-serif;">
`
...

**Comment by lukebranch** [comment]
@yenthe666, sorry, just realised this post issue is almost two years old and (@)sle-odoo has already given the same suggestion!

**Comment by Yenthe666** [comment]
Your answer is more detailed and better though 😉 
(no hate for (@)sle-odoo)

**Comment by invitu** [comment]
@Yenthe666  do you mind upvote my answer in https://www.odoo.com/fr_FR/forum/aide-1/question/how-to-add-custom-fonts-to-qweb-reports-88923 ?
I need karma ;-)
Thanks

**Comment by treviser** [comment]
@Yenthe666 @invitu @aek I would like to consolidate and combine different sources and findings in order to achieve this goal in a more generic way and adapted to the changes concerning assets in version 9.0 upwards, which are not reflected in the documentation.
Could you please have a look at this: https://www.odoo.com/forum/help-1/question/9-0-how-to-define-custom-fonts-to-css-in-report-assets-common-113812

**Comment by treviser** [comment]
@invitu Karma boost given :-)
