### ISSUE TITLE
Odoo 12 community 

### ISSUE THREAD

**Issue by saberabdelhady** [odoo/odoo#49097]
i use : Odoo 12 community 
how to monitor network performance  access link 
from external 

and how to monitors my Odoo server performance application and database

**Comment by usmanfarzandali** [comment]
this is issue/bug form 
you can find more information about odoo
https://www.odoo.com/forum/help-1
at odoo help forum

**Comment by Yenthe666** [comment]
Sorry but this is out of the scope of the bug tracker from Github, which is for bugs in the official code.
Please ask it at https://www.odoo.com/forum/help-1
