### ISSUE TITLE
Run Procurement Scheduler Issue 

### ISSUE THREAD

**Issue by emiproenterprise** [odoo/odoo#49098]
Impacted versions: Odoo Version 13

Steps to reproduce: Create multiple Reordering rules for different products and Run procurement scheduler.

Current behavior: System will check condition only for first rules and other lines will skip it.
Expected behavior: The system should check the condition for all rules.

Video/Screenshot link (optional):

![Screenshot from 2020-04-06 19-49-06](https://user-images.githubusercontent.com/16301120/78629849-dd927c80-78b5-11ea-9fd9-27b7af28e892.png)

**Comment by Yenthe666** [comment]
@sle-odoo for your interest.

**Comment by sle-odoo** [comment]
i don't understand the issue ? please explain the RR you've created and why it doesn't work as intended

**Comment by emiproenterprise** [comment]
for location_id,location_data in location_data.items():

location_data  will be overwritten
