### ISSUE TITLE
[12.0] No translations for custom terminology on widget `boolean_button` 

### ISSUE THREAD

**Issue by GavyMG** [odoo/odoo#49092]
**Impacted versions:**
12.0

**Steps to reproduce:**
add a custom terminology in a view. Example:

`
```xml
<button name="toggle_active" type="object" class="oe_stat_button" icon="fa-archive">
    <field name="active" widget="boolean_button" options="{'terminology': {'string_true': 'OK', 'string_false': 'Locked', 'hover_true': 'Locked', 'hover_false': 'Unlocked'}}"/>
</button>
````

Current behavior:
No translations are available for these terms.

Expected behavior:
We can translate these terms.

the ticket ID is #2232461

**Comment by pedrobaeza** [comment]
This is a technical limitation of that button, so basically is a won't fix.

I ping @mart-e for more details, but I think this has been removed in newer versions even.

**Comment by mart-e** [comment]
Hello,

Indeed, this was buggy to express it this way as not translatable. This widget was removed in upper versions.
If you really want to translate your custom view, you need to add some javascript too. See 98a92dc1aa14e25c6bbeaba607c6d1f287bab7d8 for an example on how to do so.
