### ISSUE TITLE
[8.0] State sales order, invoice creation on demand

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#4910]
**State sales order, invoice creation on demand**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new sale order
2. Set create invoice field with: On Demand
3. Confirm the sale order
4. Click on "view delivery order" button and deliver the products
5. Return to Sale Order and create the invoice
6. Validate invoice

Current behavior:
- Sales order remains in state "Sales Order"

Expected behavior:
- It should change the status of the sales order to done

**Comment by Yenthe666** [comment]
Hi @ernesto-gm,

Thanks for the response. The official statement was made at https://github.com/odoo/odoo/pull/6485. Quote:

> I believe this is the expected behavior to mark a SO as done as soon as the invoice is paid, not invoiced.
See this with tde, apr or qdp, but I am almost sure.
