### ISSUE TITLE
[7.0]Impossible to finalize registration through portal wizard

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#4912]
Hy folks,

I'm working on the latest git v7.0 and I activate the portal.
Here is my screen :
![portalwizard](https://cloud.githubusercontent.com/assets/1043935/5909475/44cead70-a5b1-11e4-8e11-756c4cf2a25e.png)

When I try to check a contact in this list I have this issue :
![portalwizard1](https://cloud.githubusercontent.com/assets/1043935/5909501/7301d366-a5b1-11e4-8c46-b975eaba327b.png)

Is anybody already had this issue?
Could it be related to #1010

**Comment by flotho** [comment]
Found the issue,

It was coming from a css overriding

**Comment by 10537** [comment]
Hello,

Yes, my problem was a customize module on V8 that modified the behavior in the listviews, you should review your custom modules, probably your problem are in one this modules.  be carefull with the custom modules that modified javascripts files, my problem was that.

review the file at_view_form.js =)
