### ISSUE TITLE
Footer not getting placed at the last page in qweb report

### ISSUE THREAD

**Issue by m3gadroider** [odoo/odoo#4913]
Im trying to modify the invoice qweb report and am trying to place the footer at the end of the report. I have had success with the html version, However when the pdf version is selected it doesn't get rendered as expected. I think this is an issue relating with wkhtmltopdf where it is unable to comprehend the css and place it at the end. 

Another issue is that if trying to manipulate and placing the footer in an absolute position via the page height attribute in CSS the page height starts from the first page of the pdf instead of starting from each respective page. 

 wkhtmltopdf also does not seem to understand CSS3 directives like @media print {} etc. which are generally used to get things done in printed pdf versions.

**Comment by sle-odoo** [comment]
footer at the end of the report: I advise you to read the code of the [get_pdf method](https://github.com/odoo/odoo/blob/8.0/addons/report/models/report.py#L179). A footer is always generated for each page,  but you can use the javascript to achieve what you want. Have a look at [subst.js](https://github.com/odoo/odoo/blob/8.0/addons/report/static/src/js/subst.js), you have the `page` and `topage` variables for the current and last page.

absolute position: i don't think it's the way to go. 1) Wkhtmltopdf will split the pages itself when the table is too big, so you don't *really* know when 2) the footer is not rendered with the page, it's another html page with its own structure and style, its own dom etc. No interaction with the body of the pdf.

media print: The default wkhtmltopdf behavior is to select the screen media and we do not alter this. If you want wkhtmltopdf to use the print media, you'll have to add `--print-media-type` to the arguments.

Regards

**Comment by vaab** [comment]
For extending on @sle-odoo answer, and show how you could have elements that would be displayed in the footer of the last page only, please have a look at:

http://stackoverflow.com/questions/28172283/checking-for-last-page-in-qweb-reports-in-odoo

For implementation details, and https://github.com/0k/report_extended for a module implementing it.

What about an inclusion in odoo one day ? along with ``odd-page``, ``even-page``, ``first-page`` ?

**Comment by singleroot** [comment]
Hi Vaab,

Your code works like a charm on the last page but not at the bottom...

I need to put the TOTALs at the bottom of the last page...
