### ISSUE TITLE
each user send emails withe own smtp in odoo 8

### ISSUE THREAD

**Issue by marfouk** [odoo/odoo#4914]
Hi ALL!
I have a issue with sending emails from odoo, can any one help me pleas, i have 4 users and i want each user send emails with his own smtp i did configur 4 outgoing servers (each one has parameters of each user) the 4 incoming servers works well (each user recive his email in his own inbox)

tnkx

**Comment by pvanthony** [comment]
Just tried the following module and it seems to work. Just did the install and simple testing.
https://www.odoo.com/apps/modules/8.0/tko_mail_smtp_per_user/

**Comment by marfouk** [comment]
Hi

Thank you for reply, i solove this issu, by configuring gmail smtp relay in
outgoing server.

Now i want to ask if i can creat a XML file to manag permissions.
For exmpl:
i have 4 users each user has own customers .

in the xml file i want to manage permissions to have each user can only
edit his own customers.

2015-04-29 16:25 GMT+00:00 P.V.Anthony <notifications@github.com>:

**Comment by pvanthony** [comment]
On 04/30/2015 02:23 AM, marfouk wrote:

> Now i want to ask if i can creat a XML file to manag permissions.
> For exmpl:
> i have 4 users each user has own customers .
>
> in the xml file i want to manage permissions to have each user can only
> edit his own customers.

That would be great. I too would like to have that feature. 
Unfortunately I do not know how to do it.

-- 
P.V.Anthony

**Comment by Yenthe666** [comment]
As answered - user itself found a solution.

**Comment by kazacube-ahmed** [comment]
Hi #pvanthony,

I didn't use any feature. we bought G-suit acount and had configur gmail smtp relay as outgoing server (note that you shoold configur odoo ip server in g-suit white list ).
I had tested the ko_mail_smtp_per_user feature, it was helpful too 👍 
https://www.odoo.com/apps/modules/8.0/tko_mail_smtp_per_user/

Thanx
