### ISSUE TITLE
Orphan field medic_exam

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#49164]
Impacted versions:
13
this [change](https://github.com/odoo/odoo/commit/e9d989827686d1089c1ea1c9a6b47b62a09e2de4#diff-1a19f74c907e298c401098df5e4162e5) has removed the field medic_exam from the employee form even though there is no mention of it in the commit message. Possibly a mistake? If that was voluntary shouldn't the field be removed from the model as it's not used anywhere?

**Comment by pedrobaeza** [comment]
Being something on master branch, comment on the corresponding PR.
