### ISSUE TITLE
Alarm menu is not found in the chatter

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#49167]
Impacted versions:

V13

Steps to reproduce:
Open any lead from the CRM

Current behavior:
in V12 there is an Alarm menu available in the chatter. but while looking in v13 there is no such option is available.
In V12:
![image](https://user-images.githubusercontent.com/62367855/78741711-b13f3480-7977-11ea-961d-0800b171c0bb.png)
In V13:
![image](https://user-images.githubusercontent.com/62367855/78741788-eb103b00-7977-11ea-9dc5-5f369a77bd18.png)
Expected behavior:
Is this option deprecated?
Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hmm @pedrobaeza do you know from the top of your head?

**Comment by pedrobaeza** [comment]
Yes, I remember that was removed for cleaning a bit the interface. You are always able to change your notifications from the dropdown and clicking the pencil in your name.
