### ISSUE TITLE
Domain in One2many field in xml is not working

### ISSUE THREAD

**Issue by mizohamza** [odoo/odoo#49200]
Impacted versions: 12.0

Steps to reproduce: For model Stock picking Add a domain=([('state', '!=', 'cancel')] in xml view ("stock.picking.form") like this:

`<field name="move_ids_without_package" domain="([('state', '!=', 'cancel')]"/>`

Current behavior: the domain is not working.

Expected behavior: The lines with Canceled state should be hidded.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Domain should be set in the field, not in the view.

**Comment by mizohamza** [comment]
@pedrobaeza But in works in Many2many fields for exemple, is it something related to One2many fields only ? 
also if we add domain in fields définition the actions done by python methods would not take into account the canceled records, as the search_read method would not alow that. so i need to add specific additionnal actions to take into account those record.

But al i want is to hide them in the UI. in the backend i still want to use them.

**Comment by pedrobaeza** [comment]
Yes, m2m are a different beast for that. Create multiple one2many, one with domain for UI, and another without for other things.

Closing as expected behavior.
