### ISSUE TITLE
Expression parsing sequence need to be swapped

### ISSUE THREAD

**Issue by niecw** [odoo/odoo#4920]
I think it would be better if the expression parsing (https://github.com/odoo/odoo/blob/8.0/openerp/osv/expression.py#L793) if sequence be swapped by putting `elif left == 'id' and operator == 'child_of':` and `elif not field and field_path[0] in MAGIC_COLUMNS:` before `elif not field and field_path[0] in working_model._inherit_fields:`.  This will solve the problem where the inherited fields contains MAGIC_COLUMNS.  Sometimes the MAGIC_COLUMNS need to be (re-)defined in order to use for it to be included in views (e.g. to be used in context, domain, etc.)  By swapping the sequence, all MAGIC_COLUMNS will be checked agianst and taken from the current model instead of the one in the inherit columns.  This also applies to older version, although the construct for v6.1 and v6.0 is different.

**Comment by Yenthe666** [comment]
Hi @niecw ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by infinity-solutions** [comment]
Hi @Yenthe666, the same construct is used in v9.0 as well: https://github.com/odoo/odoo/blob/ce038f5d1531107a1e45fd867de42e82940babdb/openerp/osv/expression.py#L833, so I guess it is still the case for v9.0.

It does seemed to be handled more properly starting from v10.0 (https://github.com/odoo/odoo/blob/dc5755698cc41e0c5f51ab5dccee1356a0f23a3f/odoo/osv/expression.py#L857) but unfortunately I have not got the luxury of time to redo the testing.

**Comment by niecw** [comment]
Hi @Yenthe666, the same construct is used in v9.0 as well:
https://github.com/odoo/odoo/blob/ce038f5d1531107a1e45fd867de42e82940babdb/openerp/osv/expression.py#L833
So I guess it is still the case for v9.0.

It does seemed to be handled more properly starting from v10.0: 
https://github.com/odoo/odoo/blob/dc5755698cc41e0c5f51ab5dccee1356a0f23a3f/odoo/osv/expression.py#L857
Unfortunately I have not got the luxury of time to redo the testing.

**Comment by Yenthe666** [comment]
@mart-e I see the context isn't passed along for example, should we still have a look at this for V9?

**Comment by mart-e** [comment]
Sorry but we are very unlikely to correct a corner case issue in expression.py in 9.0. Too risky for a stable version.
