### ISSUE TITLE
[13.0] Performance Issue: picking confirm with move lines have a lot of packages

### ISSUE THREAD

**Issue by ibrahim08** [odoo/odoo#49214]
Impacted versions:
13.0 Enterprise
Steps to reproduce:
create picking with move lines have ~20k packages
Current behavior:
taking a long time then function break
Expected behavior:
picking confirmed
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The break is due to your deployment configuration. Put higher timeouts.

If you have an enterprise contract, pass the case to the support team at odoo.com/help to see if it's fixable, but this issue can't be handled here in a general way, so closing.
