### ISSUE TITLE
]

### ISSUE THREAD

**Issue by ibrahim08** [odoo/odoo#49212]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by ibrahim08** [comment]
why this has been closed?

**Comment by pedrobaeza** [comment]
Because you opened it empty.

**Comment by Yenthe666** [comment]
Plus this was discussed at https://github.com/odoo/odoo/pull/47478 where sle gave you feedback already.
