### ISSUE TITLE
Free delivery coupons applied then disappear, then keeps randomly appear

### ISSUE THREAD

**Issue by jguerriat** [odoo/odoo#49245]
Impacted versions:
latest 13.0 to date

Steps to reproduce:
- create a promotion program for "free delivery"
- create coupons for this program
- go to the webshop
- add any article to your cart
- click on process checkout
- the delivery method price is added correctly to the price !
- use one of your coupon to get your free delivery
- apply
- the price is updated. So far, so good.
- then click on "return to cart"
- then click on "process checkout"
==> here is the first problem: the free shipping still appears, but it's not deducted from the total price

do the last steps multiple times ("return to cart", then "process checkout")
The free shipping will sometimes be deducted from the total, some times not

Current behavior:
the coupon is well applied from time to time, but not always

Expected behavior:
the coupon is applied correctly everytime

Video/Screenshot link (optional):
https://youtu.be/254gj9_IOak

(the video is uploading right now)

**Comment by rdeodoo** [comment]
Hello @jguerriat , sorry for the late reply.
May I ask you to check again and confirm this bug is still here?
I just checked and I wasn't able to reproduce the issue in your video. On the other hand I couldn't find a commit that would've fixed it.
Thank you
