### ISSUE TITLE
Questions about creating demo data and installation wizard

### ISSUE THREAD

**Issue by Benniphx** [odoo/odoo#4928]
Hi i like to create my own demo data by adding records and dependencies to one of my own add-ons. I created all the records but i get stuck with some Problems. I am using the newest Version  from odoo 8 from github. 

* I do not want the original demo data from odoo just my own, so i do not check the demo data box then creating a database. My demo Data comes from a data.xml.

 

Is it possible to integrate demo data for the installation wizards ? For example to set the tax by default to german 19% and use german Financing ? So all is set then I put in my add-on the dependency of the sale module?
I created demo sale orders and demo sale_order_lines and like to get some of them confirmed and i tried to make it like the original demo data but at the point then they should use a workflow like:      

    <record id="testing.sale_order_1" model="sale.order">
 		<field name="warehouse_id" ref="stock.warehouse0"/>
 		<field name="order_policy">prepaid</field>
	</record>

 
I get an error :

	ParseError: ""null value in column "account_id" violates not-null constraint" while evaluating
	u'action_invoice_create()'" while parsing /var/www/addons/testing/demo/sale/status.xml:456, near
	<record id="testing.sale_order_1" model=„sale.order">

 

But if I install the sale module upfront and set the tax and the financing it works like a charm and orders are confirmed an invoices are created and confirmed

 

How can i get the account_id in  the records, because i cant see how it is done with the original demo content. There is no information of a account_id and for my understanding account_ids are created from odoo.

my __openerp__.py looks something like this: 

	# -*- coding: utf-8 -*-

	{

    'name': 'Testing',
    'category': 'Generic Modules',
    'summary': 'Test suite with demo data',
    'version': '1.0',
    'description': """

	Testing
	======================

     """,

    'author': "bloopark systems GmbH & Co. KG",
    'website': "http://www.bloopark.de",
    'depends': [

        'account',
        'account_chart',
        'base',
        'crm',
        'product',
        'purchase',
        'sale',
        'sale_stock',
        'stock',
        'l10n_de',
        'account',
        'account_accountant',
        'account_chart',
        'account_followup',
        'account_voucher',
        'analytic',
        'auth_signup',
        'base_action_rule',
        'base_iban',
        'base_import',
        'base_report_designer',
        'base_setup',
        'base_vat',
        'board',
        'claim_from_delivery',
        'contacts',
        'crm',
        'crm_claim',
        'crm_helpdesk',
        'crm_partner_assign',
        'crm_profiling',
        'delivery',
        'document',
        'email_template',
        'fetchmail',
        'hr',
        'hr_expense',
        'hr_holidays',
        'knowledge',
        'l10n_de',
        'mail',
        'marketing',
        'marketing_campaign',
        'note',
        'procurement',
        'product',
        'product_expiry',
        'purchase',
        'report_webkit',
        'resource',
        'sale',
        'sale_commission',
        'sale_crm',
        'sale_stock',
        'share',
        'stock',
        'stock_invoice_directly',
        'warning',
        'web',
        'web_calendar',
        'web_diagram',
        'web_gantt',
        'web_graph',
        'web_kanban',
        'web_tests',
        'web_view_editor',
        'admin_technical_features',
        'disable_openerp_online',
        'mrp'

     ],

    'data': [ 

        'demo/account/payment_terms.xml',
        'demo/account/account.xml',
        'demo/base/partners.xml',
        'demo/base/filters.xml',
        'demo/settings/common.xml',
        'demo/settings/companies.xml',
        'demo/settings/email.xml',
        'demo/settings/sequence.xml',
        'demo/settings/users.xml',
        'demo/settings/hr.employee.csv',
        'demo/product/catgeories.xml',
        'demo/product/pricelists.xml',
        'demo/crm/crm.xml',
        'demo/crm/crm.phonecall.csv',
        'demo/crm/business_portfolio.xml',
        'demo/sale_commission/commissions.xml',
        'demo/sale_commission/res.partner.xml',
        'demo/sale_commission/sale.agent.csv',
        'demo/sale_commission/settlement.csv',
        'demo/partner/res.partner.csv',
        'demo/product/products.xml',
        'demo/sale/res.partner.xml',
        'demo/sale/sale.order.csv',
        'demo/sale/sale.xml',
        'demo/sale/status.xml',
        'demo/sale/account.voucher.csv',
        'demo/sale/account_voucher_line.xml',

    ],
    'demo': [
    ],

    'installable': True,
    'auto_install': False,
    }

**Comment by FelipeEB** [comment]
you may have a look at 	http://www.odoo.yenthevg.com/installing-default-data-in-odoo-module/

**Comment by kris3324** [comment]
Sorry for my oddo level but were i can uncheck demo data ?

**Comment by FelipeEB** [comment]
Hello,

 

if you create a new one you’ll se an Option 

i.e. open http://__YOUR_SERVER__/web/database/manager

                click on create Database

 



greetings

Felipe

 

Von: Kris [mailto:notifications@github.com] 
Gesendet: Mittwoch, 13. April 2016 21:13
An: odoo/odoo <odoo@noreply.github.com>
Cc: FelipeEB <welcome@feb.de>
Betreff: Re: [odoo/odoo] Questions about creating demo data and installation wizard (#4928)

 

Sorry for my oddo level but were i can uncheck demo data ?

**Comment by sle-odoo** [comment]
Hello,
The right place to ask questions is on the support or the forum.
https://www.odoo.com/page/community

Regards
