### ISSUE TITLE
Overlap of attachments and subscribers on the chatter

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#49296]
Impacted versions:
12.0

Steps to reproduce: 
Use a screen display of 1600x900

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/7910752/78881913-5842cf80-7a4f-11ea-965f-5c0b0d2d048f.png)

**Comment by pedrobaeza** [comment]
Is that with enterprise UI?

**Comment by m3asmi** [comment]
@pedrobaeza yes

**Comment by pedrobaeza** [comment]
Then you should put the OPW ticket at odoo.com/help and close this.

**Comment by m3asmi** [comment]
thanks @pedrobaeza
