### ISSUE TITLE
How to use a domain when choosing a parent for a project?

### ISSUE THREAD

**Issue by bg00071** [odoo/odoo#4931]
I want all users to be allowed to create subprojects, but only when they are a member of the project.

In the xml file, I tried to make use of the domain attribute, but I can only use fields of account_analytic_account in the left element of the tuple.

Could this be related to this bug: https://bugs.launchpad.net/openobject-addons/+bug/718890 ?

**Comment by Yenthe666** [comment]
Hi @bg00071,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
