### ISSUE TITLE
material consumption on project/contract

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#4940]
Dear Customer Support,
I'm not able to post cost amount related to material consumption on Projects/contracts.
I'm working on Odoo V8.0 and in the former Odoo version the module "Project Task Materials"  allowed it at task level.
Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
