### ISSUE TITLE
Translation issue in hr_holidays/report

### ISSUE THREAD

**Issue by RoganW** [odoo/odoo#4941]
The table header in addons/hr_holidays/report/holidays_summary.xls couldn't be translated to other languages, and display as black squares.
It seems missing a pair of <para> label between the string.
It displayed correctly after I added <para> labels between the strings.

Impacted versions:
7.0 and above

Steps to reproduce:
Click menu: Reporting / Human Resources / Reports / Leaves by Department, 
and add some departments to the wizard, then click Print button, and open the pdf report file.

Current behavior:
The first table header couldn't be display as user language.
The second table header display as black squares.

Expected behavior:
The word in table headers should be correctly translated and displayed.

**Comment by mart-e** [comment]
Hello,

Thank you for your report but the branch 7.0 is no longer supported. We only support the last 3 stable versions. We apology if we could not look at your request in time.
If the issue still makes sense for the upper version 8.0, please let us know. We will try to check it as soon as possible.
Regards
