### ISSUE TITLE
[8] theme_clean not installed correctly Odoo

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#4943]
OS : Linux ubuntu 14.04 
Src : 27-01-2015 latest source code

installing clean theme have an issue no file or directory found /usr/bin/env , but env file is exist on this directory 

error : 

WARNING test openerp.addons.website_less.ir_qweb: /usr/bin/env: node: No such file or directory
This error occured while compiling the bundle 'website.assets_frontend' containing:
    - /website_less/static/src/less/import_bootstrap.less
    - /website_less/static/src/less/colors.less
    - /website_less/static/src/less/website.less
    - /theme_clean/static/src/less/colors.less
    - /theme_clean/static/src/less/fonts.less
    - /theme_clean/static/src/less/theme.less
    - /theme_clean/static/src/less/customize_modal.less
    - /theme_clean/static/src/less/padding.less
    - /theme_common/static/src/less/s_discount.less
    - /theme_common/static/src/less/s_event_list.less
    - /theme_common/static/src/less/s_profile.less
    - /theme_common/static/src/less/s_icon_box.less
    - /theme_common/static/src/less/s_icon_box_circle.less
    - /theme_common/static/src/less/s_icon_box_square.less
    - /theme_common/static/src/less/s_pricing.less
    - /theme_common/static/src/less/s_process_steps.less
    - /theme_common/static/src/less/s_timeline.less
    - /theme_common/static/src/less/s_lead_bar.less
    - /theme_common/static/src/less/s_logo_bar.less
    - /theme_common/static/src/less/s_color_blocks_2.less
    - /theme_common/static/src/less/s_color_blocks_4.less
    - /theme_common/static/src/less/s_big_image.less
    - /theme_common/static/src/less/s_big_image_parallax.less
    - /theme_common/static/src/less/s_team_profiles.less
    - /theme_common/static/src/less/s_slide_banner.less
    - /theme_common/static/src/less/s_separator_shade.less
    - /theme_common/static/src/less/s_separator_color.less
    - /theme_common/static/src/less/s_text_highlight.less
    - /theme_clean/static/src/less/options/bg_shade_light1.less
    - /theme_clean/static/src/less/options/color_preset_1.less
    - /theme_clean/static/src/less/options/font_UbuntuPtSans.less

**Comment by sle-odoo** [comment]
You are missing the node-js and less dependencies. Please have a lookt at [our documentation](https://www.odoo.com/documentation/8.0/setup/install.html#installing-dependencies).

**Comment by Sameer1990** [comment]
I already install dependencies from the documentation , and update my source code with latest version , but the error still .

**Comment by sle-odoo** [comment]
try to symlink /usr/bin/nodejs to /usr/bin/node, i had a similar issue on debian

**Comment by Sameer1990** [comment]
thanks , it works .
