### ISSUE TITLE
[13.0] default project in task

### ISSUE THREAD

**Issue by abdallamhafeez** [odoo/odoo#49446]
Impacted versions:
13.0

Steps to reproduce:
- Go to "Project" app
- Click on "Create" and fill project name
- The system will open "Tasks" in kanban view and  then create "Stages"
- Go to "List" view
- Create a new task

Current behavior:
- Project does not fill automatically although if created from kanban view it will be filled.

Video/Screenshot link (optional):
Tested in runbot: https://drive.google.com/file/d/1VFAynkfgF2yaR2aIjrPTPThro9tBvm9Z/view

**Comment by sswapnesh** [comment]
Added Fix at https://github.com/odoo/odoo/pull/49448 (For v12)

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/652f5ff082e5b47f8aa2cc5e923a0ab5d230e78e
