### ISSUE TITLE
Editing mail template's body_html makes them fail

### ISSUE THREAD

**Issue by jguerriat** [odoo/odoo#49441]
Impacted versions:
13.0 enterprise

Steps to reproduce:
- For example, create any ecommerce order
- go the technical/settings/email templates
- search the sales order confirmation email template
- click on "preview"
- you get a nice preview of the email!
- close the preview, edit the template in "html code" mode. Add anything anywhere. In my video, i added a single character "?" at the beginning
- save
- open the preview again
- template is now destroyed and will always fail in english (the other language were not broken, so any other language might work)

Basically, after the edit of the mail template, for a reason i really don't understand, the body_html that gets stored into the database does not correspond to the body_html you have set.

For example, in my video, a part of the body_html of the mail template contains do a for loop on object.order_line.

all the % for, % if, % elif and % else are still at the right place. 

But everything that is in between those instruction gets messed up, and gets pushed back to after the end of the for loop.  In this example, i for example use this:

`<td align="left">${line.product_id.name}</td>`

But since this part of body_html gets pushed to after the end of the for loop, 'line' is not anymore in the scope, and thus the template cannot be rendered. 

I looks like the problem only appears when there are nested % instructions. 

Current behavior:
mail template body_html is destroyed

Expected behavior:
mail template body_html is not destroyed :D

Video/Screenshot link (optional):
https://www.youtube.com/watch?v=QvKzIVZKGKI&feature=youtu.be

**Comment by pedrobaeza** [comment]
This was fixed recently. Are you using latest mail template?

**Comment by jguerriat** [comment]
ha, i replicated it today on runbot, but indeed i used the mail_data.xml from a couple of days ago. The new body_html seems to fix the issue!

Thanks and sorry, i should have pulled the code ^^.
