### ISSUE TITLE
Installation fails '/var/lib/odoo' is missing

### ISSUE THREAD

**Issue by Enetrati** [odoo/odoo#49450]
Impacted versions:
13.0
Steps to reproduce:
- Install Ubuntu-18.04 LTS and update
- Download package 13.0)
sudo apt-get install --no-install-recommends ./odoo_13.0.latest_all.deb
Current behavior:
Setting up odoo (13.0.20200412)
chown: cannot access '/var/lib/odoo': No such file or directory
dpkg: error processing package odoo (--configure)
 installed odoo package post-installation script subprocess returned error exit status 1 
Expected behavior:
Installation succeeds without errors
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by ProVeg-Simon** [comment]
I have the exact same problem on a newly installed and fully upgraded Ubuntu Server 20.04. Following the install instructions to a t, when I run
`apt-get update && apt-get install odoo`
I'm getting
`Setting up odoo (13.0.20210125) ...
chown: cannot access '/var/lib/odoo': No such file or directory
dpkg: error processing package odoo (--configure):
 installed odoo package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 odoo
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by ProVeg-Simon** [comment]
When creating the directory manually, the package installs OK.
