### ISSUE TITLE
[Wishlist]: Same page anchors (bookmarks) in HTML editor field widget

### ISSUE THREAD

**Issue by emillan** [odoo/odoo#49451]
Impacted versions:
Odoo 13 EE/CE

It would be nice if there is a way to create anchors on the same using the HTML editor field widget page similar to this:
![anchor-same-page](https://ckeditor.com/cke4/sites/default/files/styles/screenshot/public/link/link_03.png)

This is very useful when we want to jump to specific sections of a page having very long content.

Also posted this in the [Summernote repo](https://github.com/summernote/summernote/issues/3668)

**Comment by pedrobaeza** [comment]
This is not something depending on Odoo itself, but as you said, on Summernote, so closing.

**Comment by emillan** [comment]
@pedrobaeza , doesn't Odoo maintain its own version of summernote in the `web_editor` module?

**Comment by pedrobaeza** [comment]
Yes and no: they need to modify SummerNote source code for injecting their needs as it's not possible through inheritance, but they don't fork it for adding features.
