### ISSUE TITLE
cannot return a warning from a button

### ISSUE THREAD

**Issue by Mitschmaster** [odoo/odoo#49499]
# Impacted versions:
13.0
# Steps to reproduce:
add a object button to a form view header
in the function:
return {'warning': {'title': 'Warning', 'message': 'Message'}}
# Current behavior:
nothing happens when clicking button
i also cannot open a ir.actions.windows
# Expected behavior:
a warning dialog should appear

**Comment by sswapnesh** [comment]
> nothing happens when clicking the button

I can confirm this behavior but

AFAIK, this is meant for `onchange` only. (Cc @pedrobaeza  To be sure)
 
(Is there a use case where do you want to return warning instead of Raising Error ?)

**Comment by pedrobaeza** [comment]
Yes, that's for onchanges, so it's expected behavior, and thus, closing.
