### ISSUE TITLE
[13.0-CE] Breadcrumb navigation bug

### ISSUE THREAD

**Issue by kmcalda** [odoo/odoo#49506]
Impacted versions:
- 13.0 CE

Steps to reproduce:
- Open any form that has a smart-button
- Click any smart-button
-  Click the back button of the browser
-  Repeat 

Current behavior:
- Tab stacks after doing the steps above
(Sorry for my bad English)

Video/Screenshot link (optional):
https://drive.google.com/file/d/16ZOCWNshObZewiGKEqgvDerh6lV2Ickw/view?usp=sharing

**Comment by pedrobaeza** [comment]
Duplicated of #46616
