### ISSUE TITLE
Procurement rule - multicompany

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4953]
In procurement rule view field company_id is missing (in tree exists).

PS. default value company_id (with enabled stock, Route with company_id, sub Pull rules) is not set???

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
