### ISSUE TITLE
odoo graph multiple measures

### ISSUE THREAD

**Issue by yasr3mr96** [odoo/odoo#49547]
odoo graph multiple measures

**Comment by Yenthe666** [comment]
Please follow the template and add more info.

**Comment by yasr3mr96** [comment]
in graph view when 
 <record id="crm_opportunity_view_graph2" model="ir.ui.view">
            <field name="name">crm.lead.graph.view</field>
            <field name="model">crm.lead</field>
            <field name="arch" type="xml">
                <graph string="Opportunities">
                    <field name="expected_invoice_date" interval="quarter" />
                    <field name="weighted_revenue" type="measure"/>
                    <field name="estimated_gross_profit" type="measure" />

                </graph>
            </field>
        </record>

the last measure  shown only not two measure

**Comment by yasr3mr96** [comment]
in graph view 
the last measure show only i want two measures show
![Screenshot from 2020-04-14 16-18-35](https://user-images.githubusercontent.com/47322110/79235283-b4508e00-7e6b-11ea-9a2f-2c5c52f40d59.png)

**Comment by Yenthe666** [comment]
Sorry but the Github issue tracker is only for bugs in the official code, this is not the place to ask questions about custom development. You can ask this at https://www.odoo.com/forum/help-1 though!

**Comment by yasr3mr96** [comment]
ok thanks
