### ISSUE TITLE
Stock Routes visibility in multicompany

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4954]
In multicompany environment need add ir.rule for Inventory Routes like 
['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]

**Comment by jco-odoo** [comment]
We might have left it out because you want it to be possible to create/apply intercompany rules.  There should be child_of user.company_ids (with s).

**Comment by zbik2607** [comment]
company_id can set in both rules and routes. Create/apply intercompany rules it should be possible, but user from child company, for example, should not see paths to suppliers or other he does not need.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
