### ISSUE TITLE
Multicompany MTO propagation (inter company transit) problem

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4956]
Scenario:

Main company AAA with warehouse A, child company BBB with warehouse B.
In warehouse B Default Resupply Warehouse = A (max priority)
User company BBB - visibility only stock warehouse B, product visibility ALL (shared)

Order MTO in company BBB in warehouse B, effect (depending on the settings of the company_id in  inter company rules):
- security restrictions - Document type: stock.location, Operation: read
- security restrictions - Document type: stock.move, Operation: read
- security restrictions - Document type: res.partner, Operation: read
- procurement exception

Expected:
active procurement in warehouse A

**Comment by jco-odoo** [comment]
Make sure you have access to both companies, or don't use procurement_jit so the moves are created by the schedulers that have access.

**Comment by jco-odoo** [comment]
Also partners that are shared should have no company_id.

**Comment by zbik2607** [comment]
Access to both companies is ok, partners company_id ok, too. Security read res.partner - probably supplier, supplier not shared. procurement_jit is enabled but it must be, because https://github.com/odoo/odoo/issues/4627, and why NO - this is PROBLEM! 

In my opinion, user from B should be able to run secheduler (even with disabled procurement_jit) without errors. Route Resupply is visibvle for user, if in rule A->Inter Company Transit (from this route) company_id is not selected (rule shared and visible for user), rule should propagate and be executed.

**Comment by flotho** [comment]
Hi @zbik2607 , did you have some news on this one?

**Comment by aario** [comment]
Sad too see that this is another one of thousands of bugs left open for years with no response! Very good software but unfortunately abandoned. Will post a fix if I found one.

**Comment by Yenthe666** [comment]
@aario not really abandoned, there are just not enough resources to maintain and fix all issues within the given time. The guys from Odoo really try to do there best though.. 
@jco-odoo could you perhaps have one more look at this please?

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
