### ISSUE TITLE
Problem with addons

### ISSUE THREAD

**Issue by jaime999** [odoo/odoo#49563]
Hi, i am a beginner with Odoo, and i am having troubles with the addons. When i start the odoo server, when i enter it with the browser, i get the next error: 

File "/usr/lib/python3/dist-packages/odoo/addons/mass_mailing_sms/tests/common.py", line 8, in <module>
    from odoo.addons.sms.tests import common as sms_common
ModuleNotFoundError: No module named 'odoo.addons.sms.tests'

However, when i go to the path '/usr/lib/python3/dist-packages/odoo/addons/sms/tests' , the file common.py is there. First i thought it was a problem of permissions, but for example the line 7, 

from odoo.addons.phone_validation.tools import phone_validation

dont give me any error, so i dont know what could be happening.

Any ideas? Thank you!

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
