### ISSUE TITLE
[13.0] One2many field with related field as inverse field is not recomputed

### ISSUE THREAD

**Issue by trinhanhngoc** [odoo/odoo#49585]
**Impacted versions:**
13.0

**Steps to reproduce:**
Consider the following models:
```python
class SampleOrderLine(models.TransientModel):
    _name = 'sample.order.line'

    order_id = fields.Many2one('sample.order')
    plan_ids = fields.One2many('sample.customer.plan', 'order_line_id')

    @api.model
    def create(self, vals):
        res = super(SampleOrderLine, self).create(vals)
        plan = self.env['sample.customer.plan'].create({'order_line_id': res.id})
        return res


class SampleOrder(models.TransientModel):
    _name = 'sample.order'

    line_ids = fields.One2many('sample.order.line', 'order_id')
    plan_ids = fields.One2many('sample.customer.plan', 'order_id')


class SampleCustomerPlan(models.TransientModel):
    _name = 'sample.customer.plan'

    order_line_id = fields.Many2one('sample.order.line')
    order_id = fields.Many2one('sample.order', related='order_line_id.order_id')
```
and a sample test:
```python
order = self.env['sample.order'].create({
            'line_ids': [(0, 0, {})]
        })
r1 = order.line_ids.mapped('plan_ids')
r2 = order.plan_ids
```

**Current behavior:**
In Odoo 12:
- r1 is a one id recordset
- r2 == r1

In Odoo 13:
- r1 is a one id recordset (same as 12.0)
- r2 is **empty** recordset

Expected behavior:
- r2 is recomputed same as Odoo 12.0

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you tried invalidating cache?

**Comment by trinhanhngoc** [comment]
@pedrobaeza Do you mean `invalidate_cache()`. I have tried it and it worked!.

```
r1 = order.line_ids.mapped('plan_ids')
order.invalidate_cache()
r2 = order.plan_ids
```

If I understand it correctly. Calling `invalidate_cache()` without passing any argument will clear all cache of current Environment and force ORM recompute all fields on next read ?

Was invalidating cache aimed to be used only when altering the database in raw SQL (https://www.odoo.com/documentation/13.0/reference/orm.html#sql-execution) ? If so, then this is probably a cache invalidation bug ? Thanks.

**Comment by pedrobaeza** [comment]
Well, let's see if @rco-odoo thinks it has to be manually executed or on contrary is something not flagged as dirty properly.

**Comment by namkazt** [comment]
So if it has to be manually executed then call `read( [ 'field_name' ] )` maybe better cause it read back only 1 field.

**Comment by Feyensv** [comment]
Computed fields are not computed until read/flush.  This means that order_id (related fields are computed fields) isn't re-computed in your case and therefore `order.plan_ids` is empty.

```python
order = self.env['sample.order'].create({
            'line_ids': [(0, 0, {})]
        })
r1 = order.line_ids.mapped('plan_ids')
r2 = order.plan_ids
# r1 = r2 # False
order.line_ids.plan_ids.order_id # the read triggers the computation (and therefore the inverse).
r3 = order.plan_ids
# r1 == r3 True
```

**Comment by pedrobaeza** [comment]
OK, then it's something expected and to be taken into account when doing this kind of things.

Thanks @Feyensv for your insights.

Closing thus.
