### ISSUE TITLE
Add an accounting chart for Algeria

### ISSUE THREAD

**Issue by bakhtout** [odoo/odoo#4961]
_New accounting chart for Algeria_*

Impacted versions:
- 8.0 and above

Steps to reproduce:

 1.install accounting module
1. choose Algeria - accounting

Current behavior:
- No Algeria chart of accounts available

Expected behavior:
- Algerian chart of account will be available

**Comment by bakhtout** [comment]
it is not clear in the guidelines whether to create a pull request through a branch or own fork?
how can I create a pull request for Odoo/8.0?

**Comment by barhamed** [comment]
I followed all these steps but there is still nothing

**Comment by Yenthe666** [comment]
Hi @bakhtout,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
