### ISSUE TITLE
[13] hr_holidays_calendar: Error on 'Everyone' menu after uninstalling this module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#49615]
Impacted versions: 13.0

Steps to reproduce: 

- Uninstall hr_holidays_calendar Module
- Click on the `Everyone` menu

![screenshot-localhost_8069-2020 04 15-22_30_33](https://user-images.githubusercontent.com/16624719/79365825-c82dea00-7f68-11ea-88e8-39d058fb0162.png)

Current behavior:
Tracback saying
```
  File "/home/sswapnesh/WorkSpace/13.0/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'hr.leave.report.calendar'
```

Expected behavior: Load old action

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Instead of Replacing action `hr_holidays.action_hr_holidays_dashboard` can't we create fresh action here and Assign it to existing Menu.

So on uninstall hook we can assign old action to this menu.

Cc @tivisse

**Comment by tivisse** [comment]
Hello.

Thanks for the feedback. This module is not supposed to be uninstalled. By the way, the modules are merged from 13.1.

I won't change it on a stable release.

**Comment by sswapnesh** [comment]
Why a module is not supposed to be Uninstalled?

Am I missing something?
This is on v13
https://github.com/odoo/odoo/tree/13.0/addons/hr_holidays_calendar

**Comment by Yenthe666** [comment]
That's ridiculous. A module should be uninstallable..
