### ISSUE TITLE
Odoo [v8] how to search products by it's “Attribute Values” in the standard search?

### ISSUE THREAD

**Issue by koyking** [odoo/odoo#4963]
NOTE1 : ORIGINAL POST FROM https://www.odoo.com/forum/help-1/question/v8-how-to-search-products-by-its-attribute-values-in-the-standard-search-69893

NOTE2 : It's not my post, but it's similar to my case.

in my case 80% of our products are called 'fabric'. So the name is nothing to distinguish one product from another.

It's the supplier, a product number, the composition, weight = in short it's attributes that matter. So I would love to be able to use the standard search to search trhough "attribute Values". By default I have to go to >Warehouse >Product Variants and then use the Advanced search > Attributes contains [my search term] in order to find what I am looking for.

Colleagues already have request to put all valuable infos in the product name which would result into something like KGJ1025FA_NUMIR_80%Polyester10%Cotton10%Elastan_width155cm_weight 210gsm.

To me that looks like pretty dirty workaround, but I must admit you can find things quickly with the default search like that.

Still I am looking for the clean solution and so I'd like to know how you could have either

"Attribute Values" to be searched by the standard search in "Product Attributes (view #359)   or to
add a search field "Attributes" or "Attribute Values" just beside the standard Search Bar in Product Variants (or maybe even in "Products"
has anybody developed something like that already? Or, how would you do that?

**Comment by koyking** [comment]
anybody ?

**Comment by Yenthe666** [comment]
To quote from the help forum:

> it's actually pretty easy (once you know it)
go to >Sales >Product Variants
type in your search term in the search bar on the upper right (don't hit 'enter' enter)
choose "Search Attributes for:" option from the drop down list that appears

Please do post questions on the help forum and not here. Github is only for bugs in the official code.

Regards,
Yenthe
