### ISSUE TITLE
 odoo11 (bootstrap.css.map) /*# sourceMappingURL=bootstrap.css.map */

### ISSUE THREAD

**Issue by darbi-a** [odoo/odoo#49678]
odoo versions: 11
bug google chrome in file:
DevTools failed to parse SourceMap: http://****/web/static/lib/bootstrap/css/bootstrap.css.map
solution:
If you just want to get rid of the error, you can also delete this line in /web/static/lib/bootstrap/css/bootstrap.css:
/*# sourceMappingURL=bootstrap.css.map */

**Comment by Yenthe666** [comment]
Please provide reproducable steps and test this on a runbot instance.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
