### ISSUE TITLE
[13.0] Stock: Problem When activating Lots/Series

### ISSUE THREAD

**Issue by SistemERP** [odoo/odoo#49685]
Impacted versions:
13.0
Steps to reproduce:

1. Activate to options: Lots & Serial Numbers in Configuration / Stock.
![img1](https://user-images.githubusercontent.com/28361796/79486979-2ac0cd80-7fdd-11ea-80d0-30c8d0a04533.png)

2. Create a storable product (stock "0"), traceability is not activated.
![img2](https://user-images.githubusercontent.com/28361796/79487152-69ef1e80-7fdd-11ea-9c43-d0c426b5bde4.png)

3. Confirm the sale and deliver the product.
![img3](https://user-images.githubusercontent.com/28361796/79487266-9b67ea00-7fdd-11ea-8f24-1bb008a85876.png)

4. It does not allow the workflow to complete, unless the product is manually added in operations.
![img4](https://user-images.githubusercontent.com/28361796/79487612-20eb9a00-7fde-11ea-8f61-6a26005a660a.png)

**Comment by pedrobaeza** [comment]
That has nothing to do with lots, but the fact that there's no reserved quantity.

Closing as no valid issue.

**Comment by SistemERP** [comment]
The behavior of warehouse exits is different when batches are not enabled in configuration.

**Comment by SistemERP** [comment]
> That has nothing to do with lots, but the fact that there's no reserved quantity.
> 
> Closing as no valid issue.

It seems to me that your answer is not correct if you have not verified the behavior since you enabled or disabled the batch option

**Comment by SistemERP** [comment]
When the batch option is active, are we required to have a reserved quantity even when the product is "Not Tracked"? @Yenthe666

**Comment by Yenthe666** [comment]
I'm pretty sure that Pedro is right actually.

**Comment by pedrobaeza** [comment]
You are seeing "Detailed Operations", that is not filled if no reservation is done. Deactivate that option in the picking type or go to the page "Operations" for seeing initial demand.

**Comment by SistemERP** [comment]
> You are seeing "Detailed Operations", that is not filled if no reservation is done. Deactivate that option in the picking type or go to the page "Operations" for seeing initial demand.

Sorry, you're right Pedro.
Thank you very much for your patience

**Comment by SistemERP** [comment]
> I'm pretty sure that Pedro is right actually.

Yes i already checked
Thank you
