### ISSUE TITLE
[13] fleet: Add validation on Unlink of Vehicle Contract based on States

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#49743]
Similar to https://github.com/odoo/odoo/issues/42370

Impacted versions: 13.0 (Probably All)

Steps to reproduce: Vehicle--> Contracts
![screenshot-localhost_8069-2020 04 18-21_51_52](https://user-images.githubusercontent.com/16624719/79643311-06711680-81c0-11ea-97d6-37b033ff43ff.png)

Current behavior:  Contracts can be deleted in Any stage, There is no Validation

Expected behavior: Add Validation on Unlink based on State.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Why would it matter though? You either close it off or delete it, I don't see a lot of value in adding extra restrictions here. @mart-e who can make the final call here?

**Comment by sswapnesh** [comment]
We have validation based on state at all places which prevents deletion of records based on states then why not here?

**Comment by mart-e** [comment]
Hi,
Fleet would be Yannick's team indeed but I agree with Yenthe. It's not like a sale order where it impacts your accounting. if the fleet manager wants to delete one and recreate a new one, it doesn't matter.
If this is an important restriction for your company, it should be easy to implement a state based rule in with an ir.rule.
