### ISSUE TITLE
[8.0] Translation sale order Quotation/Order report 

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#4974]
I tried to translate sale order quotation/order report , but the report doesn't translated to user language it still English .

Report from system used translate_doc in template , but i don't think the report takes the user language so the report not translated .

In my .po file the translated is set correctly , because other report in system or customized report Qweb are translated (the reports translated doesn't have translate_doc raw in template).

Odoo 8.0 
Source code : version 8.0-20150120

**Comment by alexis-via** [comment]
@Sameer1990 
The quotation report is not translated in the user language, but in the language of the customer, i.e. the Language parameter which is on the partner form view of the customer attached to the sale order.
Cf odoo/addons/sale/views/report_saleorder.xml line 132:
```
<t t-raw="translate_doc(doc_id, doc_model, 'partner_id.lang', 'sale.report_saleorder_document')"/>
```

**Comment by Yenthe666** [comment]
Hi @Sameer1990,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
