### ISSUE TITLE
Problem with selecting values in a many2many field

### ISSUE THREAD

**Issue by boemba** [odoo/odoo#4979]
I noticed the problem while making an invoice-line. 
The problem occurs when you want to remove the first item form the tax-many2many field in the invoice line. this is not possible because the drop down list is (partly) blocking the remove button. This makes that is impossible to remove the first value

![screenshot from 2015-01-29 17 28 42](https://cloud.githubusercontent.com/assets/8180696/5961372/8b7cebc4-a7dc-11e4-815f-09c840f12da6.png)

Thanks for looking in to this.

**Comment by Yenthe666** [comment]
Hi @boemba ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
This issue has been handled a while ago though and it also corrected in upper versions.

Regards,
Yenthe
