### ISSUE TITLE
[website_forum] Forum comments can not be deleted

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#4980]
The delete comment **X** is not working for deleting your own comments nor for deleting comments written by others.  This is true for high karma users and also the admin user.

I have [confirmed](http://43214-8-0-835065.runbot6.odoo.com/?db=43214-8-0-835065-all) this is broken in the official V8 fork via runbot.

**Comment by Yenthe666** [comment]
I'm having the same problems on the forum. The problem is in the JSON object as you can see here: 
<img src="http://i.imgur.com/LYBmwov.png"/>

**Comment by tde-banana-odoo** [comment]
Indeed. The URL called is wrong. Fix incoming in 8.

**Comment by Yenthe666** [comment]
Thanks @tde-banana-odoo! Give us an update if it is implemented in the Odoo forums please!

**Comment by tde-banana-odoo** [comment]
Fixed in 8 at commit 2a2cbfc5aea7b4da528c059b6b3527c4b46178ff . It will be deployed soon on our instance. Thanks for reporting !

**Comment by smack815** [comment]
@tde-banana-odoo patch has been applied to the odoo.com forum instance and is working as expected.  Thanks!

**Comment by Yenthe666** [comment]
Great job! Thanks @tde-banana-odoo
