### ISSUE TITLE
Promotional code on website_sales doesn't work

### ISSUE THREAD

**Issue by mamaf** [odoo/odoo#4983]
When  using demo data on list prices, a promotional code is defined on "Apple products" category
But when testing this code on Website_sales, on Shopping Cart page, the code (AK47) doesn't modify the prices
Is this functionality really operational ?

**Comment by Yenthe666** [comment]
Hi @mamaf,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
