### ISSUE TITLE
[BUG][12.0][OE] account : payment date <> statement date

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#49839]
**Impacted versions:**
12.0,13,0 and maybe other

**Steps to reproduce:**
Goto runbot
- create an vendor invoice (100€)
- register a payment (100€) 28/04/2020, you send a check or make a wire bank transfert
- payment are processed a few day latter
- import bank statement, the payment have been processed the 02/05/2020, reconcile

**Current behavior:**
Issue 1 : the account.move of the payment is posted and dated on 28/04/2020. It is not the accounting date. At the end of year it is wrong to have some payment (account.move) in 2020 whereas the bank have been processed in 2021.
Issue 2 : on Enterprise, open the Bank reconciliation select the 30/04/2020 date, and you see that the payment on the 28/04/2020 is not reconciled. It is wrong.

**Expected behavior:**
Issue 1: when you register a payment the account.move should NOT be posted, and when during the reconciliation the account.move date should the same of the bank statement and posted.
Issue 2: see issue 1

@qdp-odoo 

OPW 2242413

**Comment by fmdl** [comment]
OPW 2242413

**Comment by qdp-odoo** [comment]
see option `post_at` of the account.journal: it's doing what you want

**Comment by fmdl** [comment]
correct, thanks

**Comment by fmdl** [comment]
maybe we can activate this option when you select 'bank' type on the journal, and in the default/démo bank journal, no ?

**Comment by qdp-odoo** [comment]
Sorry Florent, I don't get your point...
