### ISSUE TITLE
sale.order commitment date: max vs min of order_line dates?

### ISSUE THREAD

**Issue by gooofy** [odoo/odoo#4984]
Hi,

we noticed that in sale_order_dates a field "commitment_date" is introduced which is auto-computed to be the _minimum_ date of all sale order lines (i.e. will result in the date the first delivery of that order could be made while others might have much greater lead times). however, documentation states:

"Date by which the products are sure to be delivered. This is "
                 "a date that you can promise to the customer, based on the "
                 "Product Lead Times."

which to me sounds more like the latest date products of that sale order will be delivered. 

wouldn't it make more sense (and be less dangerous!) to computer the _max_ date here instead of the _min_ date?

thanks,

   guenter

**Comment by Yenthe666** [comment]
Hi @gooofy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
