### ISSUE TITLE
Pick+pack+ship: pack keeps waiting when pick is transferred

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#4985]
**Pick+pack+ship: pack keeps waiting when pick is transferred**

Impacted versions:

 - 8.0 and above

Steps to reproduce (reproduced on Runbot):

* Go to `Warehouse > Configuration > Routes`
  * Duplicate "YourCompany: Pick + Pack + Ship", rename to "Export: Pick + Pack + Ship"
  * Set "Applicable on Products" on the new Route
* Go to `Warehouse > Configuration > Warehouses`
  * Edit YourCompany, set the Outgoing Shippings to "Ship directly from stock (Ship only)"
* Go to `Sales > Products`
  * Edit [A1232] iPad Mini
  * Set the route "Export: Pick + Pack + Ship"
* Go to `Sales > Sales Orders`
  * Create a new SO
  * Add 1 [A1232] iPad Mini
  * Click on "View Delivery Order"
    * Open the PICK and Transfer it

Current behavior:

- The PACK is still "Waiting Another Operation"

Expected behavior:

- The PACK should be "Ready for transfer"

Additional notes:

* The route on the procurements is well "Export: Pick + Pack + Ship".
* If the default route of the warehouse is "Pick + Pack + Ship", then the "Export: Pick + Pack + Ship" route works as expected.

**Comment by jco-odoo** [comment]
Normally this has nothing to do with the configuration of the routes at it is the moves that need to be connected with each other (move_dest_id, move_orig_ids)

**Comment by guewen** [comment]
Thanks for confirming that it shouldn't. According to the steps, we observe at least a correlation.

**Comment by gurneyalex** [comment]
@guewen can you check the src and dest location of the Pack stock picking type for your warehouse? (see #5181)

**Comment by guewen** [comment]
@gurneyalex I confirm I have the same outcome than in #5181: the Pack picking type is `Packing Zone → Stock` instead of `Packing Zone → Output`

**Comment by gurneyalex** [comment]
If you change the picking type, does it fix the issue ?

**Comment by guewen** [comment]
When I change the picking types to set the `output` location instead of `stock`, yes it fixes the issue.

**Comment by guewen** [comment]
Reading again #5181, this is definitely the same issue. Thanks for pointing this out.

**Comment by gurneyalex** [comment]
I came across #5181 while manually testing OCA/stock-logistic-workflow/pull/63 and this issue while looking for a duplicate... I guess we both were lucky :four_leaf_clover:

**Comment by guewen** [comment]
I could reproduce the same issue even when all the picking types are correct. I think it is the cause of the issue I described above.

Steps:
* Set the default route of the warehouse to "Pick + Pack + Ship", this change has as a side-effect to set the field `active` to `True` on the `Output` location
* Create a new route with 2 steps: one with `Stock → Output` and the second one with `Output → Customers`. Use new picking types instead of reusing the existing ones.
* Create a new sales order and check if the Ship transfer is available when the Pick transfer is done, it should be
* Change the default route of the warehouse to "Ship Only", this change has as a side-effect to set the field `active` to `False` on the `Output` location
* Create a new sales order, the Ship transfer is still waiting when the Pick transfer is done

Cause: 

The `Output` location is not active.

Resolution: 

When the default route is changed on the warehouse, it should not deactivate locations that are used elsewhere

**Comment by jco-odoo** [comment]
I have not been able to test the branch yet

**Comment by guewen** [comment]
> I have not been able to test the branch yet

The steps I wrote can be reproduced on runbot, they don't need a particular branch.

**Comment by jco-odoo** [comment]
The branch could be a solution already.

**Comment by guewen** [comment]
@jco-odoo oh! Sorry, I didn't noticed the reference to your branch. I test it.

**Comment by guewen** [comment]
@jco-odoo I confirm that your branch fixes https://github.com/odoo/odoo/issues/4985#issuecomment-76722936
