### ISSUE TITLE
Wrong transfer detail when forcing availability of one line

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#4987]
Wrong transfer detail when forcing availability of one line. 
You can see this video for reference: http://youtu.be/XaALLHAJm1s?hd=1

Impacted versions:
- 8.0

Steps to reproduce (reproduced on Runbot 8.0):
- Create (or use or duplicate) any picking list with more than one line.
- Mark as todo
- Select a line and "force avilabilty"
- Click on "transfer" of picking
- Showed line is ok
- close wizard without confirmation
- Select another line and "force availability"
- Click on "transfer" of picking
- Only first line is showed, there is no way to have other lines showed

Expected behavior:

Each line in available state should be shown in wizard

**Comment by mistotebe** [comment]
This is the same as #7725

**Comment by Yenthe666** [comment]
Hi @jjscarafia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
