### ISSUE TITLE
[13.0] Incorrect IP address logged when Odoo is behind proxy.

### ISSUE THREAD

**Issue by jasononggo** [odoo/odoo#49881]
Impacted versions: 13.0

Steps to reproduce:
1. create non-root user, add the new user to the wheel group.
2. git clone https://github.com/jasononggo/docker-odoo-letsencrypt.git
3. bash ./environment.sh
4. docker-compose start
5. make a request to /web/login from remote computer.

Current behavior:
Incorrect IP address logged in /var/log/odoo/odoo.log
`2020-04-21 14:26:00,285 1 INFO test odoo.addons.base.models.res_users: Login failed for db:test login:test2 from 172.18.0.3`

Expected behavior:
Correct IP address logged in /var/log/odoo/odoo.log

**Comment by pedrobaeza** [comment]
This is something of you deployment configuration, probably that you haven't put `proxy_mode=True` in your Odoo conf.

Closing meanwhile it doesn't bring new evidences.

**Comment by jasononggo** [comment]
> This is something of your deployment configuration, probably that you haven't put `proxy_mode=True` in your Odoo conf.
> 
> Closing meanwhile it doesn't bring new evidences.

It show different IP address (158.140.187.220) instead of (103.119.66.127).
This cause fail2ban to fail.

**Comment by pedrobaeza** [comment]
werkzeug version is other usually reason. Any way, as said, this is not something of Odoo code itself.

**Comment by jasononggo** [comment]
> werkzeug version is other usually reason. Any way, as said, this is not something of Odoo code itself.

Repeat #18052 discuss similar problem.
Repeat #36553 talk about werkzeug 0.15.x incompatible with Odoo.
`https://github.com/odoo/odoo/blob/13.0/requirements.txt` states the werkzeug version (0.14.1) for Odoo 13.0
Repeat #32914 upgraded werkzeug version to 0.15.2. xmo-odoo claimed `Fixed for 13`

@pedrobaeza could you please recommend me known compatible werkzeug version with Odoo:13.0 ?

**Comment by jasononggo** [comment]
> I would say that we are using 0.14.1 in Doodba (https://github.com/Tecnativa/doodba).
> 
> https://github.com/Tecnativa/doodba/blob/ab0afda59d5b219d87a7b75f8d9b72d6b4c9be4d/13.0.Dockerfile#L125
> 
> that leads to
> 
> https://raw.githubusercontent.com/odoo/odoo/13.0/requirements.txt
> 
> Have you tried that bundled deployment solution based on Docker?

That's great to know. I will take a look. I will also open a new issue regarding werkzeug version (1.14.1).

**Comment by pedrobaeza** [comment]
But this issue tracker is for Odoo code, not for deployment questions. Maybe you need to open it on odoo/docker if it's related to it, but for sure not here.

**Comment by jasononggo** [comment]
> I would say that we are using 0.14.1 in Doodba (https://github.com/Tecnativa/doodba).
> 
> https://github.com/Tecnativa/doodba/blob/ab0afda59d5b219d87a7b75f8d9b72d6b4c9be4d/13.0.Dockerfile#L125
> 
> that leads to
> 
> https://raw.githubusercontent.com/odoo/odoo/13.0/requirements.txt
> 
> Have you tried that bundled deployment solution based on Docker?

I will take a look and tried it ne

> But this issue tracker is for Odoo code, not for deployment questions. Maybe you need to open it on odoo/docker if it's related to it, but for sure not here.

I see, my bad. I will close it again.
