### ISSUE TITLE
[v7.0-9cbdb5f] Interaction between Timesheet and Sale Order

### ISSUE THREAD

**Issue by IljaSchumacher** [odoo/odoo#4990]
Hi Sirs,

The offered Product is a Service with Hours UOM.
The Product is being Produced by 'Make from Order'

I create a Quotation with a number of Hours to the customer.
After the customer accepts a Sale Order is created.
The Sale Order  autocreates a Task with the ordered amount of Hours.

Is there are way to get timesheet entries on this task to get accounted in the Sale Order that created it?

My goal is to bill the amount of already "delivered" Hours on the original Sale Order until the ordered amount is depleted. 
That way I still could use the Leads/Opportunities/Quotation/SaleOrder workflow .
But with timesheet based billing of the autocreated tasks.

Thanks a lot for your help in advance.

**Comment by Yenthe666** [comment]
Hi @IljaSchumacher,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
