### ISSUE TITLE
IBAN validation ignored 

### ISSUE THREAD

**Issue by huahyong** [odoo/odoo#49900]
https://github.com/odoo/odoo/blob/8776ee0875a8b6e882a9ca159b7a3db7cb1b7a41/addons/base_iban/models/res_partner_bank.py#L62

If customer input a wrong IBAN code, the system simply mark it as a "normal" account instead of signalling the sintax error.  The useful validate_iban function becomes useless.

**Comment by pedrobaeza** [comment]
That's done on purpose, as there are still some bank account numbers that are not IBAN, and they should work. The function serves for detecting if it's an IBAN account or not, and thus it fulfills its purpose.

Closing as no issue, but expected behavior.

**Comment by huahyong** [comment]
I think it is more useful to warn the user that the input account number is
wrong than to be clever (not enough, indeed) to guess an already known kind
of account number.
The first can save time and money when issuing ssd payments request, for
example, the second saves a click on a drop down menu.





Il giorno mer 22 apr 2020 alle ore 09:28 Pedro M. Baeza <
notifications@github.com> ha scritto:

**Comment by pedrobaeza** [comment]
That warning can cause in other automatic flows some problems.
