### ISSUE TITLE
[12.0] Payroll Global Leaves compute mistake

### ISSUE THREAD

**Issue by Saran440** [odoo/odoo#49902]
**Impacted versions:**
12 and 13

**Steps to reproduce:**
1. Setting timezone is Bangkok, Thailand (+07 )in computer or server.
2. Go to Settings -> Technical -> Resource -> Working Times
3. Global Leaves Tab and add Global Leaves 1 day (working time is 08.00 - 17.00)
![Selection_003](https://user-images.githubusercontent.com/20896369/79941915-b8923200-848f-11ea-91ce-06e1842cf46c.png)
4. Add contracts in employee
5. Go to Payroll -> Payslips Batches -> Create Payslips -> Generate Payslips -> add contracts -> Generate

**Current behavior:**
![Selection_004](https://user-images.githubusercontent.com/20896369/79942222-86cd9b00-8490-11ea-92dc-383345577029.png)
In Global Leaves line Number of Days and Number of Hours is a haft day

**Expected behavior:**
Number of Days and Number of Hours should be 1 day and 8 hours

**Video/Screenshot link (optional):**

![Peek 2020-04-22 12-03](https://user-images.githubusercontent.com/20896369/79942585-5afee500-8491-11ea-9049-63cb493e9e58.gif)

**Comment by sswapnesh** [comment]
Not sure but I think you have to set the correct timezone on your Working Time too.

https://nimb.ws/YbNvtj

**Comment by Saran440** [comment]
@sswapnesh yes, you're right. But payroll compute timezone from Schedule at Employee.
![Selection_001](https://user-images.githubusercontent.com/20896369/80059307-e8a40880-8555-11ea-90af-227ec92b4d09.png)
Thank you for your advise :)

**Comment by dixytudla** [comment]
> **Impacted versions:** 12 and 13
> 
> **Steps to reproduce:**
> 
> 1. Setting timezone is Bangkok, Thailand (+07 )in computer or server.
> 2. Go to Settings -> Technical -> Resource -> Working Times
> 3. Global Leaves Tab and add Global Leaves 1 day (working time is 08.00 - 17.00)
>    ![Selection_003](https://user-images.githubusercontent.com/20896369/79941915-b8923200-848f-11ea-91ce-06e1842cf46c.png)
> 4. Add contracts in employee
> 5. Go to Payroll -> Payslips Batches -> Create Payslips -> Generate Payslips -> add contracts -> Generate
> 
> **Current behavior:** ![Selection_004](https://user-images.githubusercontent.com/20896369/79942222-86cd9b00-8490-11ea-92dc-383345577029.png) In Global Leaves line Number of Days and Number of Hours is a haft day
> 
> **Expected behavior:** Number of Days and Number of Hours should be 1 day and 8 hours
> 
> **Video/Screenshot link (optional):**
> 
> ![Peek 2020-04-22 12-03](https://user-images.githubusercontent.com/20896369/79942585-5afee500-8491-11ea-9049-63cb493e9e58.gif) [ ![Peek 2020-04-22 12-03](https://user-images.githubusercontent.com/20896369/79942585-5afee500-8491-11ea-9049-63cb493e9e58.gif) ](https://user-images.githubusercontent.com/20896369/79942585-5afee500-8491-11ea-9049-63cb493e9e58.gif) [ ](https://user-images.githubusercontent.com/20896369/79942585-5afee500-8491-11ea-9049-63cb493e9e58.gif)

Hi, were you able to fix this? I'm experiencing the same error.

**Comment by Saran440** [comment]
@dixytudla May be you check timezone in employee. I think payroll calculate from that (not sure)
