### ISSUE TITLE
[8.0][master] manufacturing order: producing superior quantity impossible when doing partial productions

### ISSUE THREAD

**Issue by rvalyi** [odoo/odoo#4992]
Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. in runbot with demo data and mrp module, use manufacturing order MO00006 or duplicate it. Confirm it an force the reservation of the products.
 2. click on the produce button to create only 2 units instead of the 5 planned.
 3. click again on the produce button to create 4 units instead of the 3 remaining units.

Current behavior:

 - Total produced units is 5, not 6 as asked.

Expected behavior:

 - Total produced units should be 6 as asked.
May be this example with computer isn't the best one, but when manufacturing orders involve operations with plastics or liquids for instance, it happens that more units than usually expected is produced. If you enter a superior quantity than the planned quantity the first time you open the produce wizard, it works properly. But the problem is that as soon as you make several steps in the production you cannot produce more than expected anymore. This is a bug.

**Comment by rvalyi** [comment]
Hello, I confirm the bug is still here even after recent changes in mrp.py such as https://github.com/odoo/odoo/commit/656f5a44982282b5863a2ac8686ab1148811a225

Now it broke my patch and I'm updating it...

**Comment by rvalyi** [comment]
cc @jco-odoo

**Comment by jco-odoo** [comment]
@rvalyi I am sorry, but I can not reproduce.  I tested on runbot 8 and this works.

**Comment by rvalyi** [comment]
Hello @jco-odoo well I'm really curious, look at my own test here http://55621-8-0-accd3b.runbot.odoo.com/web?db=55621-8-0-accd3b-all#id=12&view_type=form&model=mrp.production&menu_id=733&action=912
as you can see total procuded quantity is 5, not 6 (I asked 2 and then 3 as described in the report). Are you sure you manage to produce more than planned?

**Comment by jco-odoo** [comment]
Tab Finished Products, produced products is 2+3+1 = 6.  The system supposes
however that you don't consume more than you thought to consume, but you
can adjust it manually.

**Comment by rvalyi** [comment]
Hum sorry, I have checked too fast just on the consummed products tab. So it seems it's fixed indeed! I'll double check to confirm my patch is useless and close the bug then. Thanks and sorry for the inconvenience.

**Comment by rvalyi** [comment]
ok so really it's fixed now.
