### ISSUE TITLE
Inter company invoice on shipping

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#4996]
Company B child A, warehouses BBB and AAA.  Transfer AAA->BBB must be invoiced, outgoing in AAA and incoming purchase in BBB (returns and refund, too) .

In this environment invoice on shipping (from transit location - inter company purchase) does not work properly.

In stock.invoice.onshipping method _get_journal_type only test dest_usage/src_usage equal supplier or customer, value transit is not tested (if route rules = To Be Invoiced), in effect journal_type = 'sale' in both cases (sale/purchase).

Additionaly problem is the return and invoice refund on this multi-company route.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
