### ISSUE TITLE
[13.0] Event : Event Tracks > Duration not displayed on kanban view

### ISSUE THREAD

**Issue by isabellerichard** [odoo/odoo#49980]
Impacted versions:
13.0

Steps to reproduce:
Go the event tracks view. Set a duration. Go back to kanban view of tracks.

Current behavior:
No duration is displayed.

Expected behavior:
Duration should be displayed.

This is fixed by updating view code with:
```xml
<t t-if="record.duration"><field name="duration" widget="float_time"/> hours</t>
```
instead of current code: https://github.com/odoo/odoo/blob/13.0/addons/website_event_track/views/event_track_views.xml#L37

**Comment by pedrobaeza** [comment]
Can you please propose the PR amending the problem?

**Comment by isabellerichard** [comment]
Hi, PR created: https://github.com/odoo/odoo/pull/49996
I close this issue.
Bye
