### ISSUE TITLE
Incoterms Configuration Missing Fields Titles

### ISSUE THREAD

**Issue by DeepSilver** [odoo/odoo#4999]
Impacted Version 8 master.
Menu -> Warehouse -> Configuration -> Incoterms -> EX WORKS -> Edit

![incoterms](https://cloud.githubusercontent.com/assets/3600848/5991580/50190698-aa2b-11e4-92d5-fc2ac2584996.jpg)

**Comment by alexis-via** [comment]
@DeepSilver Here is a PR to fix it https://github.com/odoo/odoo/pull/5002
That was an easy fix :) Enjoy !
