### ISSUE TITLE
Odoo doesn't allow PostgreSQL Streaming Replication

### ISSUE THREAD

**Issue by omacchioni** [odoo/odoo#5]
Odoo makes use of Hash indexes (for instance in ./openerp/addons/base/ir/ir_translation.py, I didn't check if there are other cases).

Hash Indexes are not compatible with Streaming Replication - cf http://www.postgresql.org/docs/9.1/static/indexes-types.html

Meaning that all attempts to create any kind of master - slave setup (either for easier failover in case of outage on the master server, or for load-balancing reasons in case external tools are using the same DB) are doomed.

I am not sure on the consequences for disaster recovery solutions based on WAL logs shipping (like http://www.pgbarman.org/ for instance).

Some possible options are:

- create a functional index on md5(src) and use it in the queries
- create a functional index on (substring(src for 50)) and use it

**Comment by rco-odoo** [comment]
@omacchioni The hash index has been replaced by a regular btree index on the master branch. So streaming replication should now work on the master branch and future releases.

Can you please close this issue if you consider it fixed? Thanks!

**Comment by omacchioni** [comment]
Thanks :)
