### ISSUE TITLE
Unable to uncheck the box next to in Manage Multiple Locations and Warehouses  Technical Settings

### ISSUE THREAD

**Issue by DeepSilver** [odoo/odoo#5000]
** Impacted version: 8 Master.

** Step to Produce
Make sure that the user have access to Technical Features, by going to ..
1. Menu - > Settings -> Users -> Administrator -> Edit
2. Check the box next to Technical Features and save.
3. Logout (Required in order to active settings)
4. Login
5. Menu - > Settings -> Users -> Administrator -> Edit
6. Uncheck the box next to Manage Multiple Locations and Warehouses
7. Save.

** Current behavior:
Unable to uncheck the box next to in Manage Multiple Locations and Warehouses  Technical Settings.

![settings](https://cloud.githubusercontent.com/assets/3600848/5991652/4fd2057c-aa30-11e4-9e38-0f68f2dc3044.jpg)

This accrue regardless of the setting found under..
Menu - > Settings -> Warehouse -> Manage multiple locations and warehouses

![warehouse](https://cloud.githubusercontent.com/assets/3600848/5991653/59ba7e2a-aa30-11e4-9db9-da27dee7f57b.jpg)

**Comment by alexis-via** [comment]
@DeepSilver 
The explanation is in odoo-80/addons/stock/security/stock_security.xml line 13:
```
    <record id="group_stock_user" model="res.groups">
        <field name="name">User</field>
        <field name="category_id" ref="base.module_category_warehouse_management"/>
        <field name="implied_ids" eval="[(4, ref('base.group_user')),(4, ref('stock.group_locations'))]"/>
    </record>
```
when you are a level "User" (or Manager) on the Warehouse application, it implies that you belong to the group "Manage Multiple Locations and Warehouses". It's automatic.

So I think that the group "Manage Multiple Locations and Warehouses" is useless in v8.
