### ISSUE TITLE
8.0 POS : Wrong period in sale account move

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5003]
Here is the scenario of the bug:
On the sale journal, activate the option "Check date in period"
Open a POS session on 31/01/2015 in the morning. You forget to close it on 31/01/2015 in the evening, so you want to do it on 01/02/2015 early in the morning.
=> You are blocked by the constraint: "The date of your journal entry is not in the defined period! You should change the date or remove this constraint from the journal".

**Comment by Yenthe666** [comment]
Hi @alexis-via ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
