### ISSUE TITLE
[8.0_Survey] Needs to disply warning in survey form

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#5008]
Needs to display warning when question is mandotory and the question having no any answer.

Steps to reproduce:

1) Go to Marketing >> Surveys >> Surveys
2) Create new survey, give a title, Click on 'Add an item', Give page title
3) Click on 'Add an item', Enter question name and Select Type of Question "Multiple choice: only one answer"
4) Go to tab Options and make checkbox true 'Mandatory Answer'
5) Do not write answer for this selection, keep it blank and save it, save it and test survey, you will get that mandatory field on survey form but you will not get there any option to select, Its wrong behaviour for mandatory question.

Should give warning on that form while going to save that for without having answer for mandatory questions.

Same for Type of Question "Multiple Choice: multiple answers allowed" & "Matrix"

**Comment by rim-odoo** [comment]
@dsu-odoo Pull requests are welcome, but it is not a real problem in my point of view: if you want to have a question with choices, you have to define choices.
