### ISSUE TITLE
Log rotate in odoo 13.0

### ISSUE THREAD

**Issue by snoomketrika** [odoo/odoo#50096]
Impacted versions: 13.0

Steps to reproduce: run odoo-bin --help

Current behavior: log rotate option have been removed

Expected behavior: how to have the same behavior as log rotate with previous version?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @snoomketrika,

This is rather a question but I can answer it for you :)
Create a new file in /etc/logrotate.d/your_instance and add config options:
```
/var/log/odoo13/*.log {
       daily
       rotate 14
       copytruncate
       delaycompress
       compress
       notifempty
       missingok
       su root root
}
```

Test it:
```
sudo logrotate -d /etc/logrotate.d/your-instance
```

Restart/force update:
```
sudo logrotate -f -v /etc/logrotate.d/your-instance
```

**Comment by pedrobaeza** [comment]
This is the commit where it was dropped:

https://github.com/odoo/odoo/commit/92d5a4bce5a3878e10427ec8dfef8c4b21f64f3d

Closing this as no issue at all.
