### ISSUE TITLE
[8.0_Survey] Wrong behavior, Displaying warning on another form

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#5009]
Steps to reproduce issue:
 
1) Go to Marketing >> Surveys >> Surveys
2) Create a new survey, Enter survey name
3) Click on 'Add an item' and enter page name and click on 'Add an item'
4) Enter Question and select Type of Question: 'Numerical Value'
5) In Option tab make check box true Validate entry
6) Enter Minimum value & Maximum value, Minimum value should be greater than Maximum value.
7) Save form and try to save survey form, It gives warning message because max value is smaller than min value.

Current behavior:

- If I select min and max validate entry value for "Numerical Value", there possible if I enter max value smaller than min value, here able to save that form and it displays error warning while going to save survey form.

Expected behavior:

- Should display warning on that particular form of question if there max value is smaller than min value. Have a look at: http://bit.ly/1zMaXtC

Same for type of Question : "Date and time"

**Comment by rim-odoo** [comment]
Users should be smart
