### ISSUE TITLE
Date picker shows wrong direction for (previous month, next month ) in RTL direction

### ISSUE THREAD

**Issue by RachidAlassir** [odoo/odoo#50090]
Impacted versions: 13.0

Steps to reproduce: Change language that supports RTL direction, click at any field of type datetime.

Current behavior: buttons next month, previous month are not in right position.

Expected behavior: Change these two buttons while in RTL direction.

Video/Screenshot link (optional):
![datepicker](https://user-images.githubusercontent.com/48803268/80162817-44a97400-85cc-11ea-812e-0d361ab626b3.jpg)

**Comment by Yenthe666** [comment]
@mart-e might be interesting for you (I was not sure which label & who to ping)

**Comment by RachidAlassir** [comment]
@Yenthe666  Probably the "Internationalization" label.

**Comment by Yemeni** [comment]
The issue is that the button gets rotates twice
I've done a quick fix to this by modifying the addons/web/static/lib/tempusdominus/tempusdominus.js to make it only rotate once
so in LTR languages, it won't matter, in Arabic RTL it will make it once
I will push a pull request

**Comment by Yemeni** [comment]
You can pull the commit linked to this issue directly @RachidAlassir or wait until they merge the pull request
