### ISSUE TITLE
Server error when I want to link linkedin account as social medial in Social Marketing App under settings

### ISSUE THREAD

**Issue by habihabib** [odoo/odoo#50106]
Impacted versions:
Trial instance V13

Steps to reproduce:
 I try to link linkedin account as social medial in Social Marketing App under settings.

Current behavior:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Expected behavior:
Make Linkedin accessible through new stream creation

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@habihabib why don't you report it through an official ticket at odoo.com/help? You have an enterprise license and this has priority.
Besides of this, nobody can help you with just a "Internal Server Error". Check the logs and add them please :)

**Comment by habihabib** [comment]
Thanks for that. Will open a ticket

**Comment by Yenthe666** [comment]
Alright, I'm closing this one in favor of the enterprise ticket as they're handled faster & this would probably keep floating around :)
