### ISSUE TITLE
IR_SEQUENCE not reset to zero when calling write method

### ISSUE THREAD

**Issue by lbellier** [odoo/odoo#5011]
I'have written a unit test to demonstrate the bug.
When we want to reset to 1 a sequence with implementation = standard, 
it's failed.
See the commit 0120f9d816a53e2c225b40f974818ad87ca20227.

**Comment by clonedagain** [comment]
Seemingly fixed in https://github.com/odoo/odoo/commit/2275af4b775c548804dd784d3034cb46dc8c4e14
