### ISSUE TITLE
yaml tests can't use the new API if there is no xml-id for the record

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#5012]
It seems from reading the answer to #2695 that there is no way of using the new api in yaml tests if we don't have an xmlid for the record.

**Comment by yucer** [comment]
Actually there is a little trick. You can pass False as id and the new **api** will be enabled.

```yaml
- !python {model: res.users, id: False}: |
    user = self.env.ref('fool')
    assert user.name == "Fool"
```

**Comment by Yenthe666** [comment]
Hi @gurneyalex ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
Also note that tests are changed from `yaml` to `python` for V12.

Regards,
Yenthe
