### ISSUE TITLE
[BUG][12.0] survey: using website module inside back template while the website module is not present in depends

### ISSUE THREAD

**Issue by f4kh** [odoo/odoo#50139]
Impacted versions:
12

Steps to reproduce:

> * Install survey module
> * Create a survey
> * Try to print the survey or test survey > review survey

Current behavior:
```
<template id="back" name="Back">
        <div groups="website.group_website_publisher" t-ignore="true" class="float-right">
            <a role="button" t-attf-href="/web#view_type=form&amp;model=survey.survey&amp;id=#{survey.id}&amp;action=survey.action_survey_form" class="btn btn-secondary">Back to Survey</a>
        </div>
    </template>
```

any template that call the back template will generate an error if website is not installed
and website in not included in depends in the manifest file

Expected behavior:
changing groups="website.groups" like odoo13

**Comment by JKE-be** [comment]
Fixed by commit afb1abb
thanks for reporting
