### ISSUE TITLE
Missing (CUD) ACL on product.pricelist.item when deploying only Sale addon

### ISSUE THREAD

**Issue by Olivier-LAURENT** [odoo/odoo#5015]
In fact, this ACL is coming with the Stock module for sales managers.
But if the Stock module is not loaded, nobody has the rights to create, update or delete pricelist items.
Maybe it would be better to move this sales manager's ACL from Stock module to Product module (i.e. where the "Sales Pricelists" group is defined).
Many thanks to fix this.

**Comment by Olivier-LAURENT** [comment]
Linked to opw626985

**Comment by dmo-odoo** [comment]
Hello,

I moved the ACL as suggested for 7.0, it will be applied for 8.0 with the next forward port.
https://github.com/odoo/odoo/commit/d7f30de9ae8a432c95fbd87e0ffbf8057b85992f

Best regards,
David
