### ISSUE TITLE
Lot No. functionality does not work in Odoo POS

### ISSUE THREAD

**Issue by parikshitbapat** [odoo/odoo#5017]
Hello

It is observed that Lot No. functionality does not work in Odoo POS if a product is marked as "Full Lots Traceability" & sold through POS screen.

**Comment by mgrohmann** [comment]
this may be related to my pull request #5020

**Comment by parikshitbapat** [comment]
Hello 
I think you are talking about an Barcode scanning interface on warehouse. I am looking for a Lot no. selection on Point of sales screen when product marked with "Full Lots Traceability" is sold though POS screen itself.

**Comment by wpichler** [comment]
Hello,

is there any progress on this issue. I do have the same problem here. Customer does have product with "Full Lots Traceability" - and does sell this product on the POS. In the POS session it is not possible to select the lot from which to take the product.

Any WIP in this area ?

**Comment by Yenthe666** [comment]
Hi @parikshitbapat,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
