### ISSUE TITLE
NewID api.onchange Odoo 13

### ISSUE THREAD

**Issue by elhamdaoui** [odoo/odoo#50183]
Impacted versions: 13.0

Steps to reproduce: Create new object and change the categories_id before saving

Current behavior: get NewID in all onchange and cannot resolve it

Expected behavior: the same error at api.depends (compute or constraints)
An exemple:
`

    @api.onchange('categorie_ids')
    def change_categ_ids(self):
        company_id = self.company_id and self.company_id.id
        domain = [('type', '=', 'product'), '|', ('company_id', '=', False), ('company_id', '=', company_id)]
        if self.categorie_ids:
            domain = ['&','&',('categ_id', 'in', [c.id for c in self.categorie_ids]),('type', '=', 'product'),'|', 
            ('company_id', '=', False), ('company_id', '=', company_id)]
        print("domain:", self.categorie_ids)
        return {
            'domain':{
                'product_ids': domain,
            }
        }`

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question on how to use new ORM. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
