### ISSUE TITLE
ir.translation _log_access = False ??

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#5019]
So, I just discovered that odoo doesn't keep create_uid, create_date, write_uid and write_date in model 'ir.translation' making impossible to track by who or when was changed a translation term.

Is there a technical or performance reason behind this? 

Is it recommended to keep it that way?

**Comment by dreispt** [comment]
Also curious on this.

**Comment by mart-e** [comment]
It was done like this probably (guess as it was done in the [first commit](https://github.com/odoo/odoo/commit/004a0b9)) because the ir.translations are updated ofter in SQL. It would be quite painful to maintain the log-access.

**Comment by dreispt** [comment]
@mart-e Still it would be good to have them, even if they are only updated on manual edits.

**Comment by mart-e** [comment]
@dreispt I disagree, if we add an information, we need it to be reliable. But PR welcome :)
