### ISSUE TITLE
[12.0] Bad ir.property creation for CustomerPortal class and fields company_dependent=True (property_account_position_id)

### ISSUE THREAD

**Issue by ddzopenforce** [odoo/odoo#50215]
**Impacted versions:**

- 12.0 (maybe 11.0 and 13.0 i don't know)

**Steps to reproduce:**

Extend the portal template `portal.portal_my_details` and add the Many2One field `property_account_position_id`.
Override the CustomerPortal too and manage `OPTIONAL_BILLING_FIELDS` list and `account()` method controller by adding fiscal position's values for `<option>`:

**_Template:_**
```
<h5>Fiscal position</h5>
<div class="row my-3">
    <div class="col-md-12">
        <label class="col-form-label label-optional" for="property_account_position_id">Your Fiscal Position *</label>
        <select class="form-control" id="property_account_position_id" name="property_account_position_id">
            <option value="">Fiscal position...</option>
            <t t-foreach="fiscal_positions" t-as="fiscal_position">
                <option t-att-value="fiscal_position.id" t-att-selected="fiscal_position.id == int(property_account_position_id) if property_account_position_id else fiscal_position.id == partner.property_account_position_id.id">
                    <t t-esc="fiscal_position.name"/>
                </option>
            </t>
        </select>
    </div>
</div>
```
**_Controller Override:_**

```
class CustomerPortal(CustomerPortal):

    OPTIONAL_BILLING_FIELDS = CustomerPortal.OPTIONAL_BILLING_FIELDS \
        + ['property_account_position_id']

    @route()
    def account(self, redirect=None, **post):
        partner = request.env.user.partner_id
        response = super().account(redirect, **post)
        # Get a recordset of fiscal positions
        fiscal_positions = self.get_website_fiscal_positions()
        response.qcontext.update({
            'fiscal_positions': fiscal_positions,
        })
        return response
```

**Current behavior:**
A new ir.property record will be created, but it has a wrong value into field `value_reference`
The new ir.property record have `value_reference` with only, for example `1`  (instead of `account.fiscal.position,1`).
The error after the first `write() `of this field is written below.
(easy to understand, because he can't split the single value `1` by comma)

**Expected behavior:**
The newly written value from portal must generate a record into ir.property with value_reference `<model>, <id>`

**TraceBack after first wrong creation from portal:**
```
Traceback (most recent call last):
  File "/opt/odoo/community_addons/bundles/commission/sale_commission/models/res_partner.py", line 74, in write
    return super(ResPartner, self).write(vals)
  File "/opt/odoo/odoo/odoo/addons/partner_autocomplete/models/res_partner.py", line 183, in write
    res = super(ResPartner, self).write(values)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_partner.py", line 570, in write
    result = result and super(Partner, self).write(vals)
  File "/opt/odoo/odoo/odoo/addons/mail/models/mail_thread.py", line 321, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/odoo/addons/mail/models/mail_activity.py", line 613, in write
    return super(MailActivityMixin, self).write(vals)
  File "/opt/odoo/odoo/odoo/models.py", line 3361, in write
    fields[0].determine_inverse(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 1144, in determine_inverse
    self.inverse(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 693, in _inverse_company_dependent
    Property.set_multi(self.name, self.model_name, values)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_property.py", line 322, in set_multi
    elif value != clean(prop.get_by_record()):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_property.py", line 157, in get_by_record
    model, resource_id = self.value_reference.split(',')
```

**Simple solution:**
This current problem can be fixed by adding this row into controller Override:
```
class CustomerPortal(CustomerPortal):

    OPTIONAL_BILLING_FIELDS = CustomerPortal.OPTIONAL_BILLING_FIELDS \
        + ['property_account_position_id']

    @route()
    def account(self, redirect=None, **post):
        partner = request.env.user.partner_id
       if post:
            if 'property_account_position_id' in post \
                    and post.get('property_account_position_id') != "":
                post['property_account_position_id'] = int(
                    post.get('property_account_position_id')
                )
        response = super().account(redirect, **post)
        # Get a recordset of fiscal positions
        fiscal_positions = self.get_website_fiscal_positions()
        response.qcontext.update({
            'fiscal_positions': fiscal_positions,
        })
        return response
```
With the INT cast the `ir.property` record will be correctly created.

My question and reason of Issue is:
_"It's a core problem that can't manage ir.property creation when receive a string instead of integer for many2one relation's field?"_

Anyway the portal module doesn't cast POST values with the proper DB type, so the many2one are written as-is (POST dict contains strings)

**Comment by pedrobaeza** [comment]
I would say that this should be handled at `website_form` level, for handling properties with integer values. What do you think, @JKE-be ?

**Comment by JKE-be** [comment]
since the code is in portal and not website_form. Not really related to website_form :)

Imo, not really a bug, but more a unhandled behavior.
You can as show in your own Issue, match your own record/property in a `if post and request.httprequest.method == 'POST':`

As it has been done e.g. for the state_id field that doesn't support empty string.

It could be improved in a future version, as you suggested, casting the value according to the matching type field.

Thanks for feedback

**Comment by ddzopenforce** [comment]
> I would say that this should be handled at `website_form` level, for handling properties with integer values. What do you think, @JKE-be ?

The portal module currently uses his own Controller that manage the route `/my/account`.

For the `website_form` POST management need a refactoring that changes custom controller with the generic one.

**Comment by pedrobaeza** [comment]
I see, thanks both for the precisions. Then indeed an extension module of the controller needs to be done.

**Comment by ddzopenforce** [comment]
> since the code is in portal and not website_form. Not really related to website_form :)
> 
> Imo, not really a bug, but more a unhandled behavior.
> You can as show in your own Issue, match your own record/property in a `if post and request.httprequest.method == 'POST':`
> 
> As it has been done e.g. for the state_id field that doesn't support empty string.
> 
> It could be improved in a future version, as you suggested, casting the value according to the matching type field.
> 
> Thanks for feedback

I think that the problem is the same for backend purposes.

For example if you make a write like this it's ok as i see into portal Controller:
```
Partner = self.env['res.partner']
Partner.write({'company_id':  '1'})
```

This is the same as:
```
Partner = self.env['res.partner']
Partner.write({'company_id':  1})
```

**But** if you write one field with attribute company_dependent=True like that:
```
Partner = self.env['res.partner']
Partner.write({'property_account_position_id':  '1'})
```
You got the same error.

I don't test it into backend but the `write()` method it's the same :)

What i try to say is that if you `write()` values like that `{'company_id':  '1'}` "normal" relational Many2One are correctly filled but `company_dependent` are not because generate a record with a wrong field `value_reference`.

This is the bug, no?
It not checked the field type before write() (not at all) or it's not managed that case for Many2One fields with `company_dependent` attribute.

Thanks for the attention.

**Comment by JKE-be** [comment]
It is easy for m2o to say, ok I should receive id, so if a receive a string, it is probably to handle like an int.

In case of value reference, it is no so straight forward, since provide a string 'model,id' is valid too (and the right way).
So to have the similar catch, we should check if values.isdigit() to handle this case.

Maybe @rco-odoo can have an opinion on it.

**Comment by ddzopenforce** [comment]
> It is easy for m2o to say, ok I should receive id, so if a receive a string, it is probably to handle like an int.
> 
> In case of value reference, it is no so straight forward, since provide a string 'model,id' is valid too (and the right way).
> So to have the similar catch, we should check if values.isdigit() to handle this case.
> 
> Maybe @rco-odoo can have an opinion on it.

I didn't find the code that manages that `ir.property` creation from a field with attribute `company_dependent=True`.
But it seems like that it can't manage when receiving a string instead of int for `many2one` fields type.
Because it writes just only the `id` and not the `model,id` as you say (for string value).

So, if the code manage cases of integer values for many2one fields and not strings values the "bug" can be in the code that generates the `ir.property` from many2one fields with that attribute?
