### ISSUE TITLE
[12.0][BUG] account: Impossible to reconcille 4000 lines

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#50245]
Impacted versions:
12 and maybe other

Steps to reproduce:
Select 4000 lines with balance is zero and the same account and same partner.
Action / reconcile.

Current behavior:
Some line have no amount.
--> it is impossible to reconcile

![image](https://user-images.githubusercontent.com/16716992/80387298-c63d2280-88a8-11ea-9574-7c56084f61d2.png)

@qdp-odoo

**Comment by pedrobaeza** [comment]
I don't get the part of "Some line have no amount."

**Comment by fmdl** [comment]
In the red boxes:
![image](https://user-images.githubusercontent.com/16716992/80390894-59785700-88ad-11ea-8b89-a27a55b12f6e.png)

**Comment by pedrobaeza** [comment]
Yeah, but how do you get to that? Unless you provide a data set for reproducing that (I don't think the problem is the number of lines), it's almost impossible to figure out what is the problem.
