### ISSUE TITLE
Field with name "length" cause onchange to not to anything

### ISSUE THREAD

**Issue by jguerriat** [odoo/odoo#50253]
Impacted versions:
13.0, latest commit

Hi! i just found a really weird bug when trying to update a field on my custom model. Basically, if a field is called "length", and if you try to update "length" in an onchange method, the onchange will basically do nothing. Neither "length" nor any other fields that you might have changed in your method are updated.

When using debug mode, you'll see that inside the onchange method, the values are correctly assigned to all the fields (and any subsequent onchange method that are called will have access to the new values), but the view (and the DB, of course) will never reflect any of those changes, or any of the subsequence changes that might happen. Basically, trying to update "length" will make everything miserably fail.

Steps to reproduce:
- on any model, add a field with the name "length". I personnaly used fields.Float()
- add an onchange event on any other field
- in your onchange method, try to update the field "length".

Current behavior:
- the field that should be updated by the onchange are not updated

Expected behavior:
- the fields are updated

Video/Screenshot link (optional):
https://youtu.be/VG5w5qxtm3w

**Comment by pedrobaeza** [comment]
Yes, basically you can't use `length` as field name. It can be considered a forbidden name. Odoo is leaving out this name from entire core (I think there's only one field remaining).

There's nothing that can be done because this collapses with JS, so please use another field name.

Closing as won't fix due to that reasons.

**Comment by jguerriat** [comment]
I indeed use another field name, but i think that if a specific name is problematic, that name should not be allowed :-).

There is indeed one remaining field with that name, in delivery, which was the one i tried to update. Took me a while to figure out that it was the name that was problematic, which is the reason i think something should be done. Someone else might lose time on this :)

Thanks anyway!

**Comment by pedrobaeza** [comment]
I agree, and maybe @rco-odoo or his team can mark explicitly it as forbidden for avoiding this or similar problems with this specific field name.
