### ISSUE TITLE
13 down payment in Sale order 

### ISSUE THREAD

**Issue by szegc** [odoo/odoo#50262]
Impacted versions:
13
Steps to reproduce:
Create sale order and confirm,then create invoce with down payment.wrong price generate in invoice.If SO delivered, create invoce with deduct down payments,wrong price also generate for invoice.
Current behavior:
Wrong price generated in invoice.
Expected behavior:
The same price as sale order line price for down payment in the first time,and when need pay for difference,only difference need pay in the second invoice.
Video/Screenshot link (optional):

[Down payment.docx](https://github.com/odoo/odoo/files/4543188/Down.payment.docx)

**Comment by pedrobaeza** [comment]
Can it be the down payment product is manipulated in the corresponding pricelist or different taxes from your sales order?

**Comment by szegc** [comment]
Hi ,Pedrobaeza,

     Do you have any feedback for this issue?

Thanks.

**Comment by pedrobaeza** [comment]
No, sorry. I tagged the issue, but nobody from Odoo has answered.
