### ISSUE TITLE
Accounting: Several Duplicate Account Types

### ISSUE THREAD

**Issue by williammead** [odoo/odoo#5026]
Impacted versions:
- 8.0 and above

Steps to reproduce:
1. Install Odoo V8
2. Add Accounting App
3. Use US Chart of Accounts 

Current Behavior:

Brand new install, has happened every time. I believe it's a duplication bug in l10n_us. There are duplicates Account Types:
Accounting > Accounts > Account Types

Asset
Bank
Cash
Cash
Check
Equity
Equity
Income
Income
Liability
Liability
...

Expected Behavior:

Just one of each Account Type:

Asset
Bank
Cash
Check
Equity
Income
Liability
...

Everything matches, even code name.  I checked and for example the Cash Account Types...

One is web#ID5:
Account Type: Cash
Code: cash
P&L / BS Category: Balance Sheet (Asset account)
Deferral Method: Balance

The other is web#ID19:
Account Type: Cash
Code: cash
P&L / BS Category: Balance Sheet (Asset account)
Deferral Method: Balance

I am not sure what add's them or which to remove?

**Comment by Yenthe666** [comment]
Hi @williammead,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
