### ISSUE TITLE
[13.0] - Navigation menu on Mobile interface error

### ISSUE THREAD

**Issue by minhhq09** [odoo/odoo#50264]
When I use a smartphone or mobile preview to display course. The navigation menu shows look like an error.

![image](https://user-images.githubusercontent.com/28040072/80453168-ed9bfa00-8951-11ea-9d93-ce1cbe724ce6.png)

**Comment by pedrobaeza** [comment]
Why do you think is an error?

**Comment by minhhq09** [comment]
I think it should display with the currently active menu like below.

![image](https://user-images.githubusercontent.com/28040072/80459721-fe9e3880-895c-11ea-92e7-7e43cc1fc7e6.png)

**Comment by pedrobaeza** [comment]
Uhm, I still don't get. I let @Yenthe666 to see if he gets it.

**Comment by Yenthe666** [comment]
He means that it should show "Basics of furniture creation" at the place where "Nav" is standing. Its not build that way if I'm not mistaking ;)

**Comment by pedrobaeza** [comment]
Well, very opinionated, but if you think it should be tagged, go ahead, Yenthe.

**Comment by Yenthe666** [comment]
Hmm I wouldn't call it a bug honestly. Do you find it a bug @pedrobaeza? I'd close it off if we both agree it is not a bug.

**Comment by pedrobaeza** [comment]
Me neither.
