### ISSUE TITLE
Flatten addon install or uninstall process

### ISSUE THREAD

**Issue by yucer** [odoo/odoo#50306]
Impacted versions: All

Steps to reproduce: 

* The developer specifies default values for `module_*` fields in xml files
* The database has a different state for that module than the one required

Current behavior:

* Odoo tries to *install* or *uninstall* addons inside the install process
* Conflicts with the update plan of odoo may arise (like #50282)
* install / uninstall procedure might be triggered inside another one, possibly inside another transaction.
* #47443 might be just one special case of the combinations of install / uninstall that can arise here.

Expected behaviour:

* That the onchange methods registered inside *res.config.settings* don't trigger immediately the update, they can queue the actions to be made to be performed later or at the end.

* Add to the documentation something related to the good practices in the Data LifeCycle Managment (DLM) regarding to some master data (like the settings), either in the implementation guide: The user and the developer agree if the settings that are going to be changed by hand or by code. Odoo can help for example optionally preventing the user to change objects that have an xml_id with noupdate == 0, or warning him that changes might be reverted by the next module update. It would be good even if such stuff is made only for `module_` settings. 

Notes: 

* It might appear that specifying values for the `module_` settings in xml data is a bad practice. But sometimes it might be logical for the module creator to use default values for them.

* Also they might want to specify incompatibility with some feature setting, although this can be handled now by the manifest. The proper wait to do it might be written somewhere in the documentation.

**Comment by pedrobaeza** [comment]
I don't think you should set that default values.

**Comment by pedrobaeza** [comment]
Following answer in https://github.com/odoo/odoo/commit/0ca82f2a75b7c2559fd77eed4b65bf6e7bc46576#r38793459, you mustn't do it due to commits, so closing this as invalid use of the framework.

**Comment by yucer** [comment]
I don't do it. But I think that the framework should be validated so that such things can not be done, or at least show WARNINGS, or write "the good practice" in some part of the documentation. 

And the fact is that is natural that the module designer want to specify an initial state of the feature, like [this one](https://github.com/OCA/stock-logistics-warehouse/blob/51d3787d0e6304d037967c2c3d64f25a504e59d1/stock_request_direction/views/res_config_settings.xml#L7). If those kind of use should be in noupdate="1" sections, that should be specified somewhere in the documentation.

My opinion is that no update of specific modules should trigger installs or uninstalls of another modules, but that is allowed by changing values of `module_*` fields in the *res.config.settings* and it guess it is designed for the user interface.

This is just a topic that came to tell us that Odoo needs to start writing  *Data LifeCycle Managment (DLM)* guidelines. So that module designers, stakeholders and users can agree of which objects are going to be controlled by source  and which not.

The same that happen with optional features that can be enabled by code or by the interface happens for all the master data. There is still the possibility in the system that xml files written in the demo sections of the module overwrite what the user has changed in the user interface. 

As long as I know there are no warnings for the user like:

`This object is being controlled by source (xml data), and your modifications might be reverted by future updates of the module`

or the at least in the logs for the update process:

`This lifecycle of this object was being controlled by source and the user did modify it. Reverting it to the state of the source`.

Although such a message exist for deletes.

**Comment by pedrobaeza** [comment]
If the framework fills up with all kind of warning for misuses, then there will be more code for warnings than for logic itself. TBH this is the first time I see someone abusing the framework this way. Any way, that's my humble opinion. If you want to propose such warning to be included, go ahead with a PR to see. Any way, this won't go further.
