### ISSUE TITLE
[MASTER] survey-The question displayed in the condition cannot save the answer.

### ISSUE THREAD

**Issue by niulinlnc** [odoo/odoo#50326]
Impacted versions:
master
Steps to reproduce:
survey
Current behavior:
The question displayed in the condition cannot save the answer.
Expected behavior:

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/11767049/80493822-79d11000-8998-11ea-9478-825713b9c040.jpg)
![2](https://user-images.githubusercontent.com/11767049/80493924-a2590a00-8998-11ea-9246-a31f9082a74b.jpg)

**Comment by pedrobaeza** [comment]
Master is a development version and thus it may contain bugs, but you can't report them here as they will flood this. If there's an opened PR, you can comment there, or wait until the release is close if you see it's not detected and fixed by Odoo team itself.

Closing due to this.

**Comment by dbeguin** [comment]
@niulinlnc : indeed, we are currently working on debugging the whole survey app, after a lots of refactoring and improvements, and a lot of added complexity in the configuration due to enlarge possibilities. But testing and reviewing every single case takes time. Be patient :)

Thanks @pedrobaeza !
