### ISSUE TITLE
[Issue][12.0]hr_expene : multi taxes

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#50343]
**Impacted versions:**
11,12,13

**Steps to reproduce:**
In France in a restaurant note you can have two taxes 10% for food and 20% for alcool.
For exemple
- Menu :40€, TVA 10%:4€, Base 36€
- Beer : 10€, TVA 20% : 2€, Base 8€
Total TTC : 50€
TVA :4+2 = 6€
Total HT:44€

When you register an expense you can select two taxes, but you can not give the untaxed base for each taxes.

--> Issue you must create 1 expense for Menu and 1 expense for Beer. Not easy when you send expense by email.

Idea for master: create `hr.expense.line` (like `account.move.line`) , `hr.expense` is like `account.move` and remove `hr.expense.sheet`.

@tivisse

**Comment by tivisse** [comment]
Hi @fmdl 

Thanks for the feedback. I've open an internal task to receive a validation from the product owner, and discuss what we do about this.

Have a nice day,

Yannick.

**Comment by tivisse** [comment]
I keep you in touch.

FYI: https://www.odoo.com/web#id=2247375&action=333&active_id=809&model=project.task&view_type=form&cids=1&menu_id=4720
