### ISSUE TITLE
Local time gets saved to the database when debugging with Visual Studio Code

### ISSUE THREAD

**Issue by johnw-bluemark** [odoo/odoo#50354]
__Impacted versions:__
12.0, 13.0, probably more

__Steps to reproduce:__
1. Have a non-UTC timezone set on the odoo server computer
2. Launch Odoo using the Visual Studio Code python debugger.
3. Create a record that uses readily visible timestamps, for example, a Sale Order
4. Observe creation timestamps.

__Current behavior:__
Local times are saved to the database

__Expected behavior:__
UTC times are saved to the database

__Explanation:__
Many places throughout the Odoo code use `datetime.now()` instead of `datetime.utcnow()` to get the current time. When Odoo is running normally, the behavior of `datetime.now()` is changed so that it always returns UTC time, making it equivalent to `datetime.utcnow()`. This is accomplished through a little hack in the `odoo-bin` startup file

```python
# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
```

However, the Visual Studio Code debugger works by running some python code _before_ this little hack has a chance to run. It probably uses the datetime module in that python code, which stops the hack from working.

__Solution:__
The solution is to change every instance of datetime.now() in the Odoo code to datetime.utcnow(), so that you will always get the time in UTC and you don't need to depend on a fragile hack. It also has the bonus of making the intent clearer to someone who is reading the code.

**Comment by pedrobaeza** [comment]
I don't think that should be done. It's a problem of debugging with VSCode, not something that happen in a production environment, and such change can have other impacts, but I let Odoo's gurus like @mart-e or @xmo-odoo to say.

**Comment by pedrobaeza** [comment]
Thanks for the answer, Julien, then should this be closed as "won't fix" or maybe you take that roadmap?

**Comment by johnw-bluemark** [comment]
I completely understand keeping the hack for backwards compatibility, but I still think the calls to `datetime.now()` should be changed. Odoo should strive to do things the correct way. IMO it's quite confusing to see the Odoo documentation say that timestamps are stored in the database as UTC, and then see `datetime.now()` all over the code, which is documented to return local time. I almost ended up opening this issue a week ago without realizing that it was the Visual Studio Code debugger that was breaking the hack.

**Comment by johnw-bluemark** [comment]
@pedrobaeza I don't buy the argument that this is Visual Studio Code's problem. Visual Studio Code makes the completely reasonable assumption that using the datetime library in their debug launcher won't break the application being debugged. Odoo, meanwhile, **changes the behavior of a standard library function** in order to work correctly.

**Comment by pedrobaeza** [comment]
Legit or not (I can agree it's a dirty hack), it's working in all places except VSCode debugger that we know, so that's why I say that. Any way, it's not in my hand to decide the roadmap to this, as I only voluntary assist on issue tracking, so that's why I asked Julien for next steps.
