### ISSUE TITLE
[8.0] Unnecessary account move line form bank statement

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#5036]
Hi,

In some cases, unnecassary move line is genereted from the bank statement reconcilation with taxes.
In this example we will use a 0% tax with a code for the base amount (This is a real situation in Luxembourg)

Here is a scenario on runbot 8.0

- First, we create the nex tax
![issue4](https://cloud.githubusercontent.com/assets/8035793/6016498/162c3000-ab83-11e4-957d-6531d176e3a3.png)
- Use this tax on a bank statement reconcilation
![issue2](https://cloud.githubusercontent.com/assets/8035793/6016562/13d308e6-ab84-11e4-96cb-3d3efa8d4d24.png)
- And go on journal entry genereted by the reconcilation
![issue3](https://cloud.githubusercontent.com/assets/8035793/6016567/237a18ca-ab84-11e4-887d-b4c7240c2855.png)

We can see a tax move line with debit, credit and tax amount equal to 0.0 and account use in this line not corresponding with account in the tax definition (No account in tax definition because is a 0% tax). The expected behavior is to not have this line.

**Comment by adrienpeiffer** [comment]
OPW 627055

**Comment by adrienpeiffer** [comment]
@Whisno Any news about this one ?

**Comment by Whisno** [comment]
Finally had the time to. Hopefully it's very easy to fix ; however I asked for a second check since I really don't want to mess up taxes creation in a stable branch
