### ISSUE TITLE
[12.0] Action name 'Translate' is not translatable :)

### ISSUE THREAD

**Issue by Uglaos** [odoo/odoo#50373]
**Impacted versions:** 12.0

**Steps to reproduce:** 

Inventory > Master data > Products > [product] > Edit > Product Name Field (translate icon on the upper right corner) > Action name on the top cannot be translated

**Current behavior:**

odoo/odoo/addons/base/models/ir_translation.py:755
action = {
            'name': 'Translate',

**Expected behavior:**

action = {
            'name': _('Translate'),

Video/Screenshot link (optional):

![Translate](https://user-images.githubusercontent.com/42736734/80580071-424f7b80-8a0b-11ea-8480-a1b671c01081.png)

**Comment by pedrobaeza** [comment]
@mart-e for you

**Comment by mart-e** [comment]
@Uglaos thanks for the report and analysis. Do you wish to make a PR to integrate the fix (as you have already identified the code)

**Comment by Yenthe666** [comment]
If not let me know and I'll create one for you guys if you'd like.

**Comment by Uglaos** [comment]
@mart-e I would like to :)

https://github.com/odoo/odoo/pull/50553

**Comment by mart-e** [comment]
Fixed at #50553, thanks again
