### ISSUE TITLE
Cancel receipt, refund, invoice does not work

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#5039]
**Unable to use cancel field on receipt, refund and invoice**

Impacted versions:

 - Master (done on runbot http://43962-master-7025a0.runbot7.odoo.com/)

Steps to reproduce:

 1. Go to 'Accounting' and click on 'Customer Invoices', 'Customer refunds', 'Sales Receipts' or 'Customer Payments'.
 2. Click on Create
 3. Click on 'Cancel ...'
<br /> <b>Note</b>: I assume the problem is in the button action and not specific to these. It will probably be the same in every place where you can 'Cancel ..'
Current behavior:
 - The following fields are invalid:
<img src="http://i.imgur.com/nOtaeZ7.png"/>

Expected behavior:

 - Record is cancelled and you're sent back to the previous screen.

**Comment by thomich** [comment]
don't cancel a new record!!!
eg. cancel means to cancel the created invoice after validation, cause it's was wrong or any other issue...

thomi

**Comment by nim-odoo** [comment]
As @thomich mentioned, you should not cancel a new record, but click on Discard instead.
