### ISSUE TITLE
Exceptions during "Scheduled Actions" (ir.cron) are not visible in the UI, not even the fact that it is failing

### ISSUE THREAD

**Issue by leio** [odoo/odoo#5040]
When an exception is thrown during a ir.cron scheduler run, it is logged in logfile, but it is not visible in any way from the web UI.
In Automation -> Scheduled actions even the fact that it is failing is not shown, so e.g the mrp scheduler (procurements really) does a lot of work every configured minutes, fails, automatic rollback, but that is not visible to even the admin user.
At least the fact that it has failed on the last run should be available and shown there, but better if also some sort of details on the error, like the exception text from the log. Even better if some notification via the core messaging framework to certain users with certain permissions/groups or at least admin.

This is especially important in SaaS-like deployments, where access to server is not available to users, or they simply aren't technical enough to go look there on a Linux server.

In the concrete case, a simple edit error turning a mrp.bom.line bom type from normal to phantom accidentally during other changes results in procurements not being run, with no feedback of that anywhere besides server log, potentially taking days before it is noticed that something is wrong, leading to real problems in fulfilling taken manufacturing result delivery commitments due to not knowing to procure necessary raw materials in time; leading to potential real monetary losses in penalties or lost contracts.

**Comment by Yenthe666** [comment]
Hi @leio,

Thanks for your report.
This is actually still the case and is for all `ir.cron` actions. Labeled it wishlist for the future.

**Comment by Yenthe666** [comment]
@odony and @mart-e this is actually something that is still bothering me as of today.
Can't we find something around this?

**Comment by mart-e** [comment]
Hello,

In 11.0, we now have a "Logging" table under the Settings > Database Structure menu.
In your server action, you can use the `log(message)` syntax and catch eventual errors and log them to the database.
So far, there is no other solution for this, sorry.

**Comment by jcdrubay** [comment]
@mart-e Hi, I am really not sure if this should be considered as a closed issue since the issue is still here.

Thanks for sharing some ideas on how to implement a patch by taking advantage of the Logging model, but I would hope this issue could be addressed in odoo code and in a generic way.

Another workaound seems to be this OCA module: https://apps.odoo.com/apps/modules/15.0/scheduler_error_mailer/
