### ISSUE TITLE
[13.0] website_sale: Do not leave address page on Wrong Promo code

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#50412]
Impacted versions: 13.0
 
Steps to reproduce: Go to Cart -->  Process Checkout --> Edit Address --> Apply some Promo (Wrong code is also okay)

![screenshot-2433542-13-0-691c9d runbot24 odoo com-2020 04 29-21_16_34](https://user-images.githubusercontent.com/16624719/80616693-d4cd3a80-8a5e-11ea-9937-69baa748ef13.png)

Current behavior: It is Redirect to Payment Page
![screenshot-2433542-13-0-691c9d runbot24 odoo com-2020 04 29-21_19_40](https://user-images.githubusercontent.com/16624719/80616991-2aa1e280-8a5f-11ea-99da-40e9877417c9.png)

Expected behavior: It should stay on Address Page

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
Fixed meanwhile if not wrong

thx for reporting

**Comment by sswapnesh** [comment]
Yes, It has been Fixed.
