### ISSUE TITLE
12.0 website_mass_mailing - newsletter popup on E-commerce

### ISSUE THREAD

**Issue by jado95** [odoo/odoo#50418]
Impacted versions:
12.0
The newsletter popup on e-commerce is displayed only visiting site from computer, if i visit e-commerce from mobile, newsletter popup is not displayed

**Comment by pedrobaeza** [comment]
@JKE-be do you know if that's on purpose?

**Comment by kig-odoo** [comment]
@jado95 Newsletter popup improvements are merged in 13.0 with this commit https://github.com/odoo/odoo/commit/34c4b3ad8a23988ecdd8112156ea13da518a2e90

Previously in 12.0, The popup was not appearing on mobile/tablet devices. Now, in
13.0 mobile/tablet devices will show the popup appears automatically after 5secs.

**Comment by Yenthe666** [comment]
That answers the question & proofs it was done on purpose :)
