### ISSUE TITLE
Field context not having an effect on view

### ISSUE THREAD

**Issue by PieceOfWire** [odoo/odoo#50424]
**Impacted versions:** 11.0

The module installed inherits and creates a new field in res.partner called _"x_commercial_name"_. It has no impact on the workflow and it is only used as an identifier. The __compute_display_name_ and _name_get_ methods were overriden since the displayed name in all views for a contact must be its _x_commercial_name_ UNLESS said view belongs to the account module. In said case it should be its original _name_ field. To achieve this a new context rule called 'legal_name' was added. If legal_name evaluates to true, _name_ should be  displayed, otherwise _x_commercial_name_ should be displayed.

**Steps to reproduce:**
1. Install this[ odoo module](https://github.com/PieceOfWire/oks_contacts) on a fresh install of Odoo 11.0 

2. Browse to Invoicing -> Sales -> Documents -> Customer Invoices and create a new invoice for "COMERCIAL KIWI S.A. DE C.V." 

3. Once the invoice has been created browse back to Customer Invoices

**Current behavior:** 
Customer name displayed corresponds to the field "x_commercial_name" created by the installed module. 

**Expected behavior:**
Customer name should display the original res.partner.name field.

A similar issue is found in the form view for vendor bills. The same context was applied to the partner_id field and the correct name is displayed while selecting the customer but once the invoice is saved it goes back to the incorrect name.

**Video/Screenshot link:**
![Screenshot_7](https://user-images.githubusercontent.com/61022169/80640394-f27fad00-8a28-11ea-9584-44f0f49461b8.png)
![Screenshot_8](https://user-images.githubusercontent.com/61022169/80640401-f4497080-8a28-11ea-9c7c-e427b6f440a3.png)
![Screenshot_5](https://user-images.githubusercontent.com/61022169/80640418-f9a6bb00-8a28-11ea-94b1-4e587864d621.png)
![Screenshot_6](https://user-images.githubusercontent.com/61022169/80640437-00353280-8a29-11ea-802c-297381893131.png)

**Comment by pedrobaeza** [comment]
I think this was fixed, but in later versions. Can you check in 13.0?

**Comment by PieceOfWire** [comment]
Thanks for answering. So is this a known bug? I would try it on later versions but the environment where I will deploy it only uses 11.0 

If there is no way to fix it other than to move up versions I guess I will just find some "hacky" way to achieve my goal.

**Comment by pedrobaeza** [comment]
I'm not sure, but that's why I ask you for trying in upper versions.

**Comment by PieceOfWire** [comment]
I see, thanks. I will try it then and come back with my findings.

**Comment by PieceOfWire** [comment]
Never got around to testing. Used extra fields instead of context to get the behavior I needed.
