### ISSUE TITLE
[Master] question about filtered_domain

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#50457]
Hi @rco-odoo 

I understand that `filtered_domain` have been introduced to speed up the ORM. Indeed in some case `filtered_domain` is more quick than `search(dom + ('id','in', ...))`. Exemple https://github.com/odoo/odoo/blob/master/odoo/models.py#L3320 `filtered_domain` is useful because it use the result of an other method.

But `filtered_domain` is used in other place where `filtered` can be used.
Exemples:
- https://github.com/odoo/odoo/blob/master/addons/account/wizard/account_payment_register.py#L474
- https://github.com/odoo/odoo/blob/master/addons/account/wizard/account_payment_register.py#L477
- https://github.com/odoo/odoo/blob/master/addons/calendar/models/calendar_event.py#L776
- https://github.com/odoo/odoo/blob/master/addons/digest/models/res_users.py#L17

Can you clarify if `filtered_domain` is an internal method use in ORM and in specifics cases, or it can be used like `filtered` ? I don't know what is the best to write `x.filetered(lambda x: x.truc)` or `x.filtered_domain([('truc','=',True)])`, I think is good idea to add a guideline to prevent both use (and complicate the code).

Regards

**Comment by Yenthe666** [comment]
@Elkasitu maybe you can shed some light on this?

**Comment by fla-subteno-it** [comment]
ping @Elkasitu
