### ISSUE TITLE
[Whishlist] Associate a personnalize message to a record rule.

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#5045]
It would be great to be able to show a personalize error message when a specific record rule is triggered to give more explanation on the current situation to the user without involving a system administrator. 

In the same way, a personalize message could help when an integrity error is displayed.

**Comment by kup-odoo** [comment]
Hello @anthony-muschang ,
Appreciate your request.

As we only discussing issues here, you can post your bugs/issues if any.
For feature request, you can send an email in feedback@mail.odoo.com
or can submit your request in odoo.com/help

This request will be closed from issues.
Thank You
