### ISSUE TITLE
group_by not working in calendar.event

### ISSUE THREAD

**Issue by alexteodor** [odoo/odoo#5048]
In calendar event (calendar.event) the grouping is not working (in list view).
it's showing the groups but you can not expand them

**Comment by Yenthe666** [comment]
I believe it was handled https://github.com/odoo/odoo/commit/e0ceab9efdd2af66cb6b1421005858ed7ee97f71
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
