### ISSUE TITLE
Odoo v8 are not supported on Internet Explorer 9

### ISSUE THREAD

**Issue by sylvainvanhoof** [odoo/odoo#5050]
Hello, 

With the latest version of Odoo v8, Internet Explorer 9 are not supported.
Some views are not correctly displayed. 

![screen shot 2015-02-03 at 16 43 56](https://cloud.githubusercontent.com/assets/8790593/6023401/eb5a9bfe-abc4-11e4-9c5f-b4bbe7c9b055.png)

Can you fix these errors ?

Thank for all,
Sylvain Van Hoof for Eezee-it

**Comment by charlycoste** [comment]
Internet Explorer's bugs should be fixed by Microsoft.

**Comment by ged-odoo** [comment]
i'll have a look this wednesday.  If it is easy, it could be fixed in a matter of minutes, if not, well, we'll see.

**Comment by ged-odoo** [comment]
argh, not enough time.  i'm still on it, will find time this week

**Comment by ged-odoo** [comment]
This issue is not so easy to solve.  I expect that it will take some time from Christophe to properly do it, but I believe it is doable.  Timeframe: hopefully next week

**Comment by Gorash** [comment]
This bug appears as IE9 can read a limited number of rules per css file. It depends on the number of module you have installed. You can use the debug mode to not have this problem.

**Comment by antonybrugger** [comment]
Does this mean that Odoo v8 is not officially supporting IE9?

**Comment by antonylesuisse** [comment]
Is it the default Odoo or does it break when we add more css in the assets

**Comment by antonylesuisse** [comment]
@Gorash we need to fix this either by removing un needed css from the assets or by splitting the assets attachement generated by t-call-assets.

**Comment by sylvainvh** [comment]
Hello, 

Can you give me a status about this issue ? Do you know the remaining time ? We will push the project in production in few days.

Thank for all !
