### ISSUE TITLE
Wrong Invoice Counter in Accounting Dashboard in Odoo 11 EE

### ISSUE THREAD

**Issue by usmanfarzandali** [odoo/odoo#50520]
Impacted versions:
Odoo 11 EE
Steps to reproduce:

Current behavior:
In Accounting Dashboard
I have two(2) open invoice, at he time on click count button its show correct that will be two(2) in tree view
but Counter Show Wrong Value 41

calculation wrong in Multi-company env.

Expected behavior:

Show 2 in Invoice Dashboard Counter Value 

Video/Screenshot link (optional):

![imageedit_5_8791284737](https://user-images.githubusercontent.com/22232100/80858659-3286a000-8c74-11ea-9a9f-c56d275b5590.gif)
![imageedit_2_8009904552](https://user-images.githubusercontent.com/22232100/80858662-34506380-8c74-11ea-82b3-696663730412.png)

**Comment by pedrobaeza** [comment]
As it's EE, you can open a ticket through odoo.com/help instead of here. Do you have Odoo updated to latest code?

**Comment by usmanfarzandali** [comment]
ok thanks

**Comment by usmanfarzandali** [comment]
you can close issue here ....

**Comment by sswapnesh** [comment]
FYI, I just fixed bug on v13 https://github.com/odoo/odoo/pull/50522

(Haven't checked on v11)

**Comment by pedrobaeza** [comment]
Well, v11 is totally different in that aspect, but thanks for the patch for v13!

**Comment by sswapnesh** [comment]
Yep and also This seems to be working fine on v11

**Comment by usmanfarzandali** [comment]
@sswapnesh so its also fix in Odoo 11 too or already ok in odoo 11 ? 
may i get latest pull for odoo 11 ?

**Comment by sswapnesh** [comment]
> already ok in odoo 11 ?

Yes

You can update your source code
