### ISSUE TITLE
Zero values not rendered on tree/list views

### ISSUE THREAD

**Issue by oscarolar** [odoo/odoo#5053]
Hello, Odoo team, any value in the tree views is not rendered, it stays empty on the tree/list view, it seems that is being taken as  a logical value (False) instead of a integer or float.

You can reproduce this issue by setting Quantity on account.invoice.line on the invoice form, here your will find a gif over here:

http://www.gfycat.com/ObviousImperturbableGrison

or attached to this issue
![tree_not_rendering_zero](https://cloud.githubusercontent.com/assets/3836433/6026408/39ca45fc-aba0-11e4-8d90-cfa5bbd244b4.gif)

Best regards

**Comment by beledouxdenis** [comment]
Hello Oscar, 

This issue should have been resolved with rev.

https://github.com/odoo/odoo/commit/93fa43f9003b625ccee2042be46fb6ff370c7694

Do you confirm ?

Regards,

**Comment by oscarolar** [comment]
Yes, you can now close the issue


On Fri, Feb 6, 2015 at 12:55 PM, Denis Ledoux <notifications@github.com>
wrote:

> Hello Oscar,
>
> This issue should have been resolved with rev.
>
> 93fa43f
> <https://github.com/odoo/odoo/commit/93fa43f9003b625ccee2042be46fb6ff370c7694>
>
> Do you confirm ?
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/5053#issuecomment-73291961>.
>



-- 




Ing. Oscar Alcalá Rivera
*312-107-1704* · oszckar@gmail.com <ozckar@gmail.com>

Vauxoo SA
Tlf: *3123111122*

*Open Source Enthusiast*

*LinuxCounter:**566085*
     [image: twitter] <http://twitter.com/oscarolar> [image: linkedIn]
<http://www.linkedin.com/pub/oscar-alcal%C3%A1/3b/a79/922>   [image:
Google+] <http://plus.google.com/107659954580035981067/posts>

[image: eco] No me imprimas si no es necesario. Protejamos el medio ambiente
