### ISSUE TITLE
Drop shipping from sales order - creating Supplier Invoice to Customer 

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#5054]
1. Drop shipping from purchase order is working fine.
2. Drop Shipping from Sales order lines have the following Flow
   A. Confirm SO > RFQ Created based on the supplier setting in product master
   B. Confirm RFQ > Customer Location by default and Receipt is working fine
   C. Create Supplier Invoice > After receiving Items, if we create supplier invoice > Odoo set customer name instead supplier name and linking to SO also.
   D. Expected behavior > Supplier Invoice should be created as normal flow and Create Invoice button should be visible in SO with View Delivery Order.

![image1](https://cloud.githubusercontent.com/assets/2189864/6036466/c73c6c08-ac5e-11e4-8fa1-a1c943247c14.png)

![image2](https://cloud.githubusercontent.com/assets/2189864/6036468/cc8a0760-ac5e-11e4-8dd1-21276eb7d5e7.png)

![image3](https://cloud.githubusercontent.com/assets/2189864/6036469/cf6ed0e6-ac5e-11e4-9096-2aacbdd46d1d.png)

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
