### ISSUE TITLE
Have worker settings recommendations in deployment documentation

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#5056]
it would be nice for the [deployment documentation](https://www.odoo.com/documentation/8.0/setup/deploy.html#builtin-server) to provide recommendations on the setting to use for multiworker setups.

For example, I recall that number or workers is recommended to be `CPUs*2+1` but I can't find that anywhere.

**Comment by Yenthe666** [comment]
Totally in the docs now (https://www.odoo.com/documentation/11.0/setup/deploy.html#worker-number-calculation) 😉
