### ISSUE TITLE
[7.0] unexpected SUPERUSER_ID value found in functional field. (fields.function)

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#5059]
Hi,

I recently write a function in a custom module that has to use uid value in the _get_my_field function. I saw that the uid is always SUPERUSER_ID and the correct uid (of the current user) is in the context dict.
Step to reproduce the bug:
* develop a custom module and overload any model, writting the following code;
* log into database with 'demo' / 'demo'. (uid = 3)

**Code**

    _columns = {
        'my_field': fields.function(
            _get_my_field, string='My Field', type='char')}

    def create(self, cr, vals, context=None):
         print "CREATE uid : %s" % (uid)
         print "CREATE context['uid'] : %s" % context['uid']
         return super(my_class, self).create(cr, uid, vals, context=context)

    def _get_my_field(self, cr, uid, ids, name, arg, context=None):
         print "FUNCTION uid : %s" % (uid)
         print "FUNCTION context['uid'] : %s" % context['uid']
         return {x: '' for x in bob}

**Résultat**

    CREATE   uid : 3
    CREATE   context['uid'] : 3
    FUNCTION uid : 1                # <-- Unexpected value
    FUNCTION context['uid'] : 3     # <-- Correct value

**StackTrace**
> ~/odoo7/openerp/osv/fields.py(1157)get()
-> result = self._fnct(obj, cr, uid, ids, name, self._arg, context)

> ~/odoo7/openerp/osv/orm.py(4770)_store_set_values()
-> result = self._columns[f].get(cr, self, ids, f, **SUPERUSER_ID**, context=context)

(Not a recent change, it was present 1 year ago : 
https://github.com/odoo/odoo/blob/3fb75a44c8f7bfd7ceba2cfdfe3e62456de7739e/openerp/osv/orm.py#L4654)
Regards.

**Comment by gurneyalex** [comment]
This was introduced in Dec. 2009, in https://github.com/odoo/odoo/commit/cb32d72dfa134e57c88742612c6c85bd13ee5797 and was part of odoo 6.0. 

The comment suggests it is related to multi company and security rules (superuser bypasses security rules checks). 

Maybe @fpodoo (or @odony) could provide more information.

**Comment by legalsylvain** [comment]
Thanks @gurneyalex for your investigation ! 
For me it's a bug, because if we have an API function with uid param, all developpers will think that it is the current user, and not the SUPERUSER_ID.
My current function bypass CLA and doesn't get correct property values, and so have a fully unexpected behaviour, I just discovered.

What is your PoV on that point ?

**Comment by gurneyalex** [comment]
I'm pretty sure that random breakage in a multicompany setup will result from changing back to uid. I don't know if this will result test breakage... You can easily test this though: make a PR on odoo/odoo with the change and see if runbot is green :smirk_cat:

**Comment by odony** [comment]
As @gurneyalex says, we can't really consider changing this behavior in 7.0 as it is a major change of the ORM internals and could break many modules.
On the other hand in 8.0 there was an attempt to get rid of this with the new API. Recently the super-user recompute was reinstated also in 8.0 upon request from the community (see PR #4847 and the related issues #4824 and #3178 for examples where developers ask for this).
However this seems to have too many side-effects so we're probably going to change it back and make it an opt-in option per field, similar to the `related_sudo` option for related fields.
@rco-odoo should submit a PR for this soon.
In the mean time I think we can close this issue, as we don't plan to change this in 7.0.
