### ISSUE TITLE
Can't print check in 8.0 

### ISSUE THREAD

**Issue by atuljain** [odoo/odoo#5062]
getting error 

  File "/home/odoo/runbot/extra/runbot/static/build/44408-8-0-90230a/openerp/addons/account_check_writing/report/check_print.py", line 39, in fill_stars
    if len(amount) < 100:
QWebException: "object of type 'bool' has no len()" while evaluating
'fill_stars(o.amount_in_word)'

**Comment by Symbiofi** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @atuljain,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
