### ISSUE TITLE
Error in crm_lead.py

### ISSUE THREAD

**Issue by mamaf** [odoo/odoo#5071]
In phonecall form view, update mode, On action to open lead linked to phonecall :
Replace
action = self._get_formview_action(cr, user, context['opportunity_id'], context=context)
By
action = self.get_formview_action(cr, user, context['opportunity_id'], context=context)

**Comment by Yenthe666** [comment]
Hi @mamaf ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
By the way, feel free to make a PR if you know what exactly has to be changed. 

Regards,
Yenthe
