### ISSUE TITLE
[8.0] Email template CSS styling do not apply correctly on Buttons and Comparisons

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#5073]
Odoo version 8.0_20150202
Ubuntu 14.04, Bitnami image on Amazon AWS.

How to reproduce the issue:
1. Go to Marketing > Mail template > Create new > Edit template
2. Choose an email template > Insert Blocks > Advanced Email Features > Insert "Button OK"
Put "Button OK" on the place > Point on the button and click "Change" 
Apply needed Color Style  and Size > Click Save.
The Style does not apply on the Button. 
When you send such a template by mail there is no styling of buttons, they are grey rectangles.
Same issue with "Comparisons", the Buttons which are below are not styled in the received email. 

Regards.

**Comment by Fl0rianFischer** [comment]
I am having a problem that might be related. 

I am trying to create an Email template where I put my styles into the head of the email. However, all of this style information is not rendered at all when I want to send an Email. In the email designer however, all the styles are applied correctly. 

In one of our earlier projects it was no problem to work like this. If we have to put all style information inline, we can't use media queries, which means no responsiveness.

Regards,
Florian

**Comment by Yenthe666** [comment]
Hi @sergueikp,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
