### ISSUE TITLE
email quoting systems do not show URLs in plain text

### ISSUE THREAD

**Issue by tmagik** [odoo/odoo#5074]
When odoo.com sends out a quotation via email, the URL of the quote is obfuscated in mime formatting, and the PDF version does not include any information about online payment information.

This is a problem for anyone using a text-only email client, or looking at the PDF to provide payment information. It is also a potential easy target for spear-phishing attacks if users open up the HTML version and do not check the URLs.

**Comment by Yenthe666** [comment]
Hi @tmagik,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
