### ISSUE TITLE
Purchase Order Product Description Overwriting Header

### ISSUE THREAD

**Issue by ITPS** [odoo/odoo#5076]
Given: user prints PO
And: PO has products listed that have very long description
Then: In the generated PDG report, the product descriptions are printed mix in with the header

**Comment by ITPS** [comment]
We have a hotfix and are willing to submit a pull request if needed to get this fix in the Odoo 8.0 branch.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Don't hesitate to create PR's! They get a higher priority.

Regards,
Yenthe
