### ISSUE TITLE
[BUG] core : SQL cascade unlink by pass ORM, you can unlink everything in silence

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#50801]
**Impacted versions:**
All

**Steps to reproduce:**
Go to runbot
In studio create a new model `test.unlink`.
In purchase order, with studio, add new many2one field `field_test` with relation `test.unlink`.
Edit the `field_test` (Settings/Databse/Fields), select `Cascade` in `On delete` field.
Create a new record `test.unlink`, named `AAAA`.
Go to in confirmed purchase order, if you try to delete it, it is impossible `In order to delete a purchase order, you must cancel it first.`
Edit the purchase order, in `field_test` select `AAAA`.
Now delete `AAAA`.
--> Issue : the purchase order is unlink (and there are no logs).

**Current behavior:**
SQL cascade unlinks records by SQL, and by pass ORM  (ACL, Rules, custom unlink(), ...).

**Expected behavior:**
Don't use SQL cascade and unlink with ORM, I have start to works here : https://github.com/odoo/odoo/pull/33113

@odony 
@rco-odoo 
@mart-e

**Comment by mart-e** [comment]
Hi,

What's the difference with #33113? @rco-odoo already explained it's not something we want to do.
The ondelete cascade is a feature of the ORM with its limitation that you need to know if you make custom fields.

**Comment by odony** [comment]
> The ondelete cascade is a feature of the ORM with its limitation that you need to know if you make custom fields.

To put it another way, indeed you can break some business rules by misusing cascade-deletion. But using Studio you're customizing the models and it's your responsibility to do it in a way that's consistent. Studio is a very powerful tool and it opens up an infinite number of ways to break your system (you can write server actions, so anything is possible).

We can help users and guard against the most obvious errors, but we cannot prevent all mistakes, and this one looks like a very advanced one that is too expensive to prevent and rather unlikely too.

If you have a good suggestion to improve the Studio UI to help avoid this mistake, it may be helpful, but changing the implementation of unlink() everywhere just for this unlikely problem is not an option (as discussed on #33113)

**Comment by fmdl** [comment]
@odony I think is not just an issue linked to studio,
- you can unlink data by mistake (it is not the same things to write cr.execute('delete ...') in server action)
- it can become an vulnerability
- there are no logging on unlink cascade
- attachments are not unlink
- computed fields are not recomputed
- ir.model.data are not unlink
- ACL, Rules, custom unlink() are by pass.

I understand that you prefere to keep SQL cascade to reduce the number of query.

When you write `ondelete='cascade'`, you don't know that is very powerful. Maybe in future we can introduce `cascade_sudo_sql` same current behaviour (SQL Casade) and `cascade` it is an ORM cascade.

Regards

**Comment by pedrobaeza** [comment]
> Studio is a very powerful tool and it opens up an infinite number of ways to break your system

And that's the exact reason why I forbid this module in all our installations :wink: 

I agree that `ondelete="cascade"` should remain relying on SQL, but maybe in ORM documentation can be stated more clear about the risks. What do you think?

**Comment by Yenthe666** [comment]
@pedrobaeza sorry to go a little bit off-topic but I'm curious. You mean that none of your customers are allowed to use Odoo studio? I decided to allow it - since it can be so helpful and powerful - but I will only allow it to users with sufficient knowledge and after talking them through it.

**Comment by pedrobaeza** [comment]
No, nobody under our maintenance service can use it, as the problem is not if they know how to use it or not (that they don't many times as much as you teach them), the key problem is in that word I have used: maintenance. The summary is that a system with Odoo + OCA that is updated, expanded (with more OCA modules under evolution of the company) and migrated, that is also touched with Studio, can't be maintained in acceptable ways. I can expand more the whys, but I let that for a beer conversation :wink:

**Comment by fmdl** [comment]
Note : during uninstall a module some data can be removed by mistake, due to an on delete cascade.

**Comment by pedrobaeza** [comment]
@fmdl but if so, that's because the module is dependent of the module being uninstalled, and it will be uninstalled as well. (or the dependency is not declared, which is an error...). Or am I missing something?

**Comment by fmdl** [comment]
@pedrobaeza, it is not an issue of dependency
- create a new model `test.unlink` in a new module `super_test`
- in `purchase.order` you write
`field_test = fields.Many2one('test.unlink', ondelete='cascade')`
- Now you set `field_test` on all `purchase.order`
- Uninstall `super_test`

--> The wizard said that you will unlink 'test.unlink', but in reality you also unlink `purchase.order`. (and you loose all purchase data)

Use SQL cascade is not an issue, issues are 
- some one have access to unlink `test.unlink` and have not access to unlink `purchase.order`, can still unlink `purchase.order`.
- you loose all `purchase.order` and you have nothing in logger.

A mistake can be made by any one, using the wrong ondelete, like here : https://github.com/odoo/odoo/pull/50889 

Note : cascade is most case used where there are parents and in models with lines (sale, purchase, ...). A soft cascade could not add lot of query in most case (because unlink is most case use directly by user). And we could use SQL cascade for tricky case.

I just give my opinion, as I suggested to @odony in 2017 to add ACL on transient model.

**Comment by pedrobaeza** [comment]
I consider that as a bad programming code, no other thing. There's no sense on doing that `ondelete="cascade"`.

**Comment by mrm-david** [comment]
> I agree that ondelete="cascade" should remain relying on SQL, but maybe in ORM documentation can be stated more clear about the risks. What do you think?

Please add something in the documentation !
