### ISSUE TITLE
cant login to odoo website

### ISSUE THREAD

**Issue by a-ali24** [odoo/odoo#50858]
i am sorry for posting this here but i think its an issue, i couldnt find any way else to report my problem, i was using odoo help perfectly no problem yesterday then suddenly my account stopped and gave me 500 internal server error
need someone from odoo technical support to contact me about my issue

Impacted versions:
odoo.com

Steps to reproduce:
when i login to my odoo account on odoo.com

Current behavior:
500 internal server error

Expected behavior:
to login normally

Video/Screenshot link (optional):

 here is the error traceback i get when i try to login

[login_error_traceback.txt](https://github.com/odoo/odoo/files/4592950/login_error_traceback.txt)

![error_1](https://user-images.githubusercontent.com/13247526/81295439-b5429d00-9070-11ea-9c1c-87b413152f98.png)

![error_2](https://user-images.githubusercontent.com/13247526/81295455-ba9fe780-9070-11ea-8006-675360408bb5.png)

**Comment by Yenthe666** [comment]
@JKE-be for you

**Comment by JKE-be** [comment]
can you logout and retry please: 

link to force a logout: https://www.odoo.com/web/session/logout

If it doesn't work after, please send me a mail with your login to jke[at]odoo.com
else jsut confirm here ;) 

thx

**Comment by a-ali24** [comment]
Tried and still get the same problem. I will send you the login now.

Thanks for your fast response.
