### ISSUE TITLE
[account] Customer bank account in customer invoices

### ISSUE THREAD

**Issue by omar7r** [odoo/odoo#5085]
Hi,

We found an usability issue on customer invoices, because, we are not able to select customer bank accounts. I didn't know if is only common at Spain but, we should be able to create customer invoices as direct debit.

Regards

**Comment by yvaucher** [comment]
Same here for switzerland, especially when printing payment slip to send to the customer.
You might want to be able to select the correct bank.

cc @fclementic2c

**Comment by Yenthe666** [comment]
Hi @omar7r,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
