### ISSUE TITLE
Analytic account selected on Manufacturing work center 

### ISSUE THREAD

**Issue by nurbahyt** [odoo/odoo#50884]
Impacted versions: Odoo V12

Steps to reproduce: Even I select an analytic account on the manufacturing work center when MO is done, the related analytic item is not created.

Current behavior: analytic item is not created

Expected behavior: related analytic item should be created.

Video/Screenshot link (optional):

![20200508](https://user-images.githubusercontent.com/47028545/81365198-15414e00-911a-11ea-9f99-b2f2cb8719b8.png)

**Comment by pedrobaeza** [comment]
Where and when do you expect that analytic item to be created? Where have you read that?

**Comment by nurbahyt** [comment]
I expect analytic item creation with the selected analytic account on the work center, when the Manufacturing order is done.

**Comment by pedrobaeza** [comment]
Well, this is not an Odoo error, but:

- or configuration problem
- or feature non existing

so you should ask on the forums for how this works and then, if we a proper combination of steps to reproduce the problem, you don't get the desired effect, so closing meanwhile.
