### ISSUE TITLE
name_get does not update names if modified

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5096]
I don't understand why modified name_get does not properly update names.

For example in `res.partner` model I have defined this:

```python
class res_partner(models.Model):
    _inherit = 'res.partner'

    is_branch = fields.Boolean('Is Branch?')
    parent_root_id = fields.Many2one('res.partner', 'Main Partner', domain=[('is_company', '=', True), ('is_branch', '=', False)])

    @api.multi
    def name_get(self):
        res = super(res_partner, self).name_get()
        res_dict = dict(res)
        for record in self:
            if record.parent_root_id and record.is_branch:
                res_dict[record.id] = "%s / %s" % (record.parent_root_id.name, res_dict[record.id])
        return res_dict.items()
```
The thing is, how names are displayed, only changes when one of two things happen - if new record is being created and on creation ```name_get```  satisfies condition ``` if record.parent_root_id:``` or if on write, field `name` is modified. 
But if for example I modify record and set ```is_branch = False```, display name of that record (in list, kanban views) does not change.

Scenario to better understand what I mean.

create record: name = 'test', is_branch = True, parent_id = 1 (let say it is `Asustek`).
When I go to list view, i see it displayed like this:
```Asustek / test```
OK, now I change condition to this is_branch = False.
When I go to list view, i see it displayed like this:
```Asustek / test```
In other words, nothing changes.
Now if do this name = 'test2'.
When I go to list view, i see it displayed like this:
test2

Now it changed, because I changed name, but if I changed fields that display name depends on, nothing change. But the thing on search (when searching in field for example in ```parent_id``` field), it displays correct display name (changes display correctly).

So I don't get it why it is not being updated if I change things like that. On Odoo 7, there was no such problem. 

P.S.
I also tried simply overwriting name_get (without ```super```) and adding one line that changes display name I need,  but even then I get same issue. My other method implementation I tried:

```python
    def name_get(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        if isinstance(ids, (int, long)):
            ids = [ids]
        res = []
        for record in self.browse(cr, uid, ids, context=context):
            name = record.name
            if record.parent_id and not record.is_company:
                name = "%s, %s" % (record.parent_name, name)
           if not record.parent_id and record.is_company and record.is_branch and record.parent_root_id:
                name = "%s, %s" % (record.parent_root_id.name, name)
            if context.get('show_address_only'):
                name = self._display_address(cr, uid, record, without_company=True, context=context)
            if context.get('show_address'):
                name = name + "\n" + self._display_address(cr, uid, record, without_company=True, context=context)
            name = name.replace('\n\n','\n')
            name = name.replace('\n\n','\n')
            if context.get('show_email') and record.email:
                name = "%s <%s>" % (name, record.email)
            res.append((record.id, name))
        return res
```

**Comment by clonedagain** [comment]
Did you try the always_reload option on the views?
https://bugs.launchpad.net/openerp-web/+bug/1297882/comments/3
