### ISSUE TITLE
[13] portal: Payment Method information is not Displayed on portal

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#50965]
Impacted versions:

Steps to reproduce:
![screenshot-2562296-13-0-cdf3b3 runbot38 odoo com-2020 05 09-00_33_19](https://user-images.githubusercontent.com/16624719/81439864-b537bf80-918c-11ea-9506-6bf202a7d0c7.png)

![screenshot-2562296-13-0-cdf3b3 runbot38 odoo com-2020 05 09-00_32_54](https://user-images.githubusercontent.com/16624719/81439841-a9e49400-918c-11ea-8afe-4bc1862b11cc.png)

Current behavior: No Information is Displayed of Saved Cards

Expected behavior: Display Information 
![screenshot-2562296-13-0-cdf3b3 runbot38 odoo com-2020 05 09-00_43_41](https://user-images.githubusercontent.com/16624719/81440745-2af05b00-918e-11ea-8ae7-905e08394b59.png)

Video/Screenshot link (optional):

**Comment by JKE-be** [comment]
@sswapnesh can you confirm that you have this visual bug only with the payment provider test, and so not in prod ? 
If it is the case, good to explain next time ;) like that we can prioritize on real bug.
thank you
