### ISSUE TITLE
[13] website_sale: Signup option should not visible if not enabled globally

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#50964]
Impacted versions: 13.0

Steps to reproduce: Place an Order from `/shop` without logging in

Current behavior: On the Order Page it is asking to Signup even if External Signup is not allowed

![screenshot-2562296-13-0-cdf3b3 runbot38 odoo com-2020 05 09-00_08_24](https://user-images.githubusercontent.com/16624719/81437706-3db46100-9189-11ea-913e-8055fe1fd1b4.png)

Expected behavior:  Signup Button should be displayed only if it is allowed

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think it's only a question of terminology, because what happens if you click there? You are redirected to the login page, right?

**Comment by sswapnesh** [comment]
I'm Redirected to the Signup page with Valid token linked to New Partner.

**Comment by pedrobaeza** [comment]
OK, then indeed it's a bug

**Comment by sswapnesh** [comment]
That's because of Odoo is using Value (`auth_signup.invitation_scope'`) from ICP, not from the Website.
