### ISSUE TITLE
[13] web: Could not add table on html without focus

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#50966]
Impacted versions: 13.0

Steps to reproduce: Add Table on Html field without clicking on the field 

Current behavior: It's not working, We have to click on the field explicitly to add a table
![Peek 2020-05-09 01-17](https://user-images.githubusercontent.com/16624719/81443356-ea471080-9192-11ea-9905-7995379a9d86.gif)

Expected behavior: It should work like other Option where the focus on the field is not required explicitly

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Actually, there are loads of breaking options with HTML editors apparently. OPW `2256835`
Some issues:
Create a new task, fill in a title and click on the "Ordered list"
=> Error
Create a new task, fill in a title and click on the "Unordered list" icon
=> Error
Create a new task, fill in a title and click on the "Table" icon
=> Table drawn in the top of the form, not the HTML
Create a new task, fill in a title and click on the "Checkmark" icon
=> Error
Create a new task, fill in a title and click on the "Style" icon
=> Error

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/pull/51956
