### ISSUE TITLE
[Feature Request] Multiple lines in line graph chart

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#50979]
I think having multiple lines in graph view will be very useful. And attractive to buisnesses. Fancy charts are alwayse attractive, right?

Suggesitons:
Maybe make grouping on line graph to be each group on a separate line, or having a measure for each line.
Also giving the developer the freedom to write some javascript to change chart data can be great.

**Comment by pedrobaeza** [comment]
AFAIK, that's already possible... can you describe a bit more with an screenshot what you are requesting?

**Comment by obayit** [comment]
I was able to do it, thanks @pedrobaeza 
It wasn't obvious for me though! I even looked at the javascript code, and didn't know it was possible.
![screenshot-eco-sd gsk-erp com-2020 05 10-16_03_21](https://user-images.githubusercontent.com/20386024/81501327-19b36580-92d8-11ea-9019-3864f19235ba.png)
