### ISSUE TITLE
Import of translations using CSV does not work

### ISSUE THREAD

**Issue by HarlekinSimplex** [odoo/odoo#50975]
Impacted versions:
odoo 13

Steps to reproduce:
Export a module translation as CSV file and try to reimport that file again.

Current behavior:
Import fails with an error.
```
2020-05-09 15:53:54,708 42 ERROR bitnami_odoo odoo.addons.base.wizard.base_import_language: File unsuccessfully imported, due to format mismatch.
Traceback (most recent call last):
File "/opt/bitnami/odoo/odoo/addons/base/wizard/base_import_language.py", line 43, in import_lang
lang_name=this.name, context=this._context)
File "/opt/bitnami/odoo/odoo/tools/translate.py", line 1106, in trans_load_data
 irt_cursor.finish()
File "/opt/bitnami/odoo/odoo/addons/base/models/ir_translation.py", line 71, in finish
 cr.execute(query + ", ".join(["%s"] * len(rows)), rows)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 164, in wrapper
  return f(self, *args, **kwargs)
File "/opt/bitnami/odoo/odoo/sql_db.py", line 241, in execute
   res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "account.field_account_tax__amount_type"
LINE 3: ...         VALUES ('ir.model.fields,help', 'de_DE', 'account.f...
                                                             ^
2020-05-09 15:53:54,710 42 ERROR bitnami_odoo odoo.sql_db: bad query: SELECT value FROM ir_translation
                       WHERE lang='de_DE' AND type in ('code') AND src='File %r not imported due to format mismatch or a malformed file. (Valid formats are .csv, .po, .pot)
Technical Details:
%s' AND md5(src)=md5('File %r not imported due to format mismatch or a malformed file. (Valid formats are .csv, .po, .pot)
Technical Details:
%s')
ERROR: current transaction is aborted, commands ignored until end of transaction block
```

Expected behavior:
Import of previously exported and unaltered CSV file containing translations should not fail.

Possible Cause:
In the export file there is no numeric res_id like it is in the po file.
Instead there is an text representation like "account.mail_template_data_payment_receipt".
Probably a bug in the export function, shelling out the wrong field or in the import function not resolving this key but expecting the numeric res_id.

Cheers
Stephan

**Comment by pedrobaeza** [comment]
@xmo-odoo can you please check?

**Comment by HarlekinSimplex** [comment]
Hi,
I crosscheck the issue again.
There is no res_id in the po file.

The entries just look like:
```
#. module: account
#: model:ir.model.fields,field_description:account.field_account_cashbox_line__number
msgid "#Coins/Bills"
msgstr "#Münzen/Geldscheine"

```
So I guess its a problem with the import routine not able to resolve the location key, which in understanding is the 'id' of the po format.

Hope that helps a bit.

Cheers
Stephan

**Comment by xmo-odoo** [comment]
@pedrobaeza this has to do with the translation import, not the data import, so it's more of an @mart-e thing.

**Comment by pedrobaeza** [comment]
OK, sorry for pinging you. @mart-e, your call.

**Comment by pedrobaeza** [comment]
Fix in #51049

**Comment by mart-e** [comment]
Thanks, should be fixed at https://github.com/odoo/odoo/commit/f276bf8ca5725c0980612e97512ea3a598e9e6de
For generally, we recommand .po file format, it's more adequate for translations handling.

**Comment by HarlekinSimplex** [comment]
Yes indeed!

Using .po files and POEdit is the preferred way to prepare new translations or change translations of a single module.
How ever, if you have to create a compilation of customized translations from several stock modules, PO edit is not very usefull to get the task done.

Since we have the no_update flag with data xml (e.g. nija templates) and already installed transalation terms are not replaced on module upgrade (quite old design descicion afaik) changing translations of stock modules by a custom module becomes quite a headache.
Even if you uninstall/install a custom modul, I saw lots of translation terms not properly deleted and recreated inside ir.translations.

So there was only one way left to go:
Using a custom module with <delete> statements and proper domain search clauses to remove invalid or deprecated translation terms directly from ir.translations and let them be loaded back again with a .po file inside that module that covers all the previous deleted terms.
In case you prefere not to have all and every translation terms of all effected modules inside that custom compilation (though during development that is a very convient way to preoceed) you need to filter and select the altered translations manually after exporting the whole bunch into a large po. file.
Pretty forcefull approach I know, but it was the only feasible way I found after more than 3 weeks of deep and desperate investigations and head banging against the translation 'walls'.

Unfortunately import of translations requires a .po or .csv file. .xlsx is not suitable.
So to achive my goal at the end of the day - EXCEL and .csv was the tool of choice not POEdit and .po, at least for me.
This way I found that little .csv import issue, which is fixed now - thankfully.

The reason for that whole approach was the customization of jina templates and their subjects that are used for several emails (edi sale, edi invoice, edi purchase, etc.).
Since such customizations are required for more or less every custom installation I needed a way to do that conveniently and quickly without any manual alterations of the translations by just installing a custom modul into my several odoo docker containers.

Dont get me wrong, the handling of translations in odoo does work properly, sort of... 
How ever it has some quirks and difficulties still, that might deserve some improvements in the (hopefully near) future.
Especially and foremost when it comes to the translation of jinja email templates used for automized daily business process communication that always needs to be changed to fit customer needs.
