### ISSUE TITLE
[12.0][13.0][FIX] base: res.partner no gravatar image loading because of missing context

### ISSUE THREAD

**Issue by skeller1** [odoo/odoo#50978]
Impacted versions: 12.0, 13.0

Steps to reproduce:

1. Enter debug mode
2. Goto contacts and open form for new record
3. Enter Email in form (with valid Gravatar email)

Current behavior:
 - Gravatar image is not loaded because of missing context `gravatar_image: True`
 - btw modifiers are also not displayed in popup

Expected behavior:
 - Gravatar image should be loaded

Video/Screenshot link (optional):
Screenshots for partner form in V11 (works fine), V12 and V13 showing the field information in debug mode popup for field `email`. Context and modifiers are missing in V12 and V13

![ContextOdoo11](https://user-images.githubusercontent.com/226753/81485081-ec6ca600-924a-11ea-83db-e5fb04839ee7.png)
![ContextOdoo12](https://user-images.githubusercontent.com/226753/81485083-ed053c80-924a-11ea-8bdb-ad92aced31f1.png)
![ContextOdoo13](https://user-images.githubusercontent.com/226753/81485084-ed9dd300-924a-11ea-84f6-ffffb79044d2.png)

**Comment by skeller1** [comment]
Found possible reason: mail addon is replacing the email field without context and modifiers. Contacts depends on mail, so this should be fixed.

V12: [mail/views/res_partner_views.xml](https://github.com/odoo/odoo/blob/28034c48c024284ea3bd6248451e186132aca4d0/addons/mail/views/res_partner_views.xml#L16)

V13: [mail/views/res_partner_views.xml](https://github.com/odoo/odoo/blob/cdf3b380b7090e1481acd96b80a20e851e88be81/addons/mail/views/res_partner_views.xml#L16)

V13:

**Comment by pedrobaeza** [comment]
@tivisse maybe for you?

**Comment by sswapnesh** [comment]
Added Fix at #50980

**Comment by sswapnesh** [comment]
Still Fix is not merged on 13.0
