### ISSUE TITLE
Sale coupon expirey date 

### ISSUE THREAD

**Issue by sangitassh** [odoo/odoo#50976]
Impacted versions:

Steps to reproduce:

Current behavior:

in local system login as an admin user and add item to cart after that  create coupon   which starting date is 11th May and 30 May as ending date now change the local system time to 15th May now when we try to apply coupon then it will show that coupon is expired
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
But why do you want to trick local date? All of this works with server time, not local one, and probably that manipulation leads to the problem.
