### ISSUE TITLE
Odoo Payloads getting blocked by AWS WAF.

### ISSUE THREAD

**Issue by manishbisht94** [odoo/odoo#50997]
Impacted versions: Odoo 12

Steps to reproduce: 
Setup a basic Odoo & enable AWS WAF pre-configured protections with OWSAP Top 10.

Current behavior: 
AWS WAF is active with pre-configured protections following OWSAP Top 10 rules.. 
Any request to Odoo with URL alike content in payload is getting blocked at AWS ELB by AWS WAF. 
As per the logs, the requests are getting blocked against RFI_BODY threat. This means that URLs in payload may refer to malicious content on Internet which the application may download & get compromised.  

Payload is simply a request/data payload sent in POST request.
E.g:- {"jsonrpc":"2.0","method":"call","params":{"args":[[84],{"website":"https://www.abcd.com"}],"model":"res.partner","method":"write","kwargs":{"context":{"lang":"en_US","tz":false,"uid":2,"search_default_customer":1}}},"id":981359328}

The requests end up with 403 Forbidden response.

These Firewall filter rules are basically implemented at Enterprise Level, how does Odoo anticipate such firewall rules. 

Expected behavior: 
The requests with payload should pass the AWS WAF as if No WAF was configured.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What do you mean by payload?

**Comment by manishbisht94** [comment]
By payload I mean the data/request payload sent in the Post Request. 
This could be a Post request to update customer's details. e.g. updating the customer's website address.  

Request Payload Example:-
{"jsonrpc":"2.0","method":"call","params":{"args":[[84],{"website":"https://www.abcd.com"}],"model":"res.partner","method":"write","kwargs":{"context":{"lang":"en_US","tz":false,"uid":2,"search_default_customer":1}}},"id":981359328}

The response I get is:-
content-length: 536
content-type: text/html
date: Mon, 11 May 2020 09:42:37 GMT
server: awselb/2.0
status: 403

**Comment by Yenthe666** [comment]
Did you first get an authentication token etc and passed this along though? How does your code look?

**Comment by manishbisht94** [comment]
No authentication tokes is received. I am performing these operations as logged in user. 
The above operation i.e. updating a customer's website address is performed on a default Odoo setup no code changes.

Two things to consider:-
1. The catch is that we have white-listed our corporate IPs in AWS WAF to avoid this error. So, this Odoo works seamlessly from our corporate n/w.  But the same operation fails from the public 
Network. 
2. If we try to update it with any non-url like content e.g "odoo" instead of FQDN, then request passes the firewall easily and can be witnessed in Odoo logs also.

**Comment by pedrobaeza** [comment]
I consider this as specific deployment bits, but not a problem of Odoo itself.

**Comment by manishbisht94** [comment]
We have this situation at our end.
We are considering the situation where Odoo can anticipate such firewall rules. 

As AWS WAF alike many other firewalls implements these OWSAP top 10 rules as standards, disabling these rules at WAF in production is not recommended as that may degrade security.
Not sure even if there is any way to do that as they are pre-configured protections. 

We are setting up Odoo at an enterprise level which includes best security practices.
In your experience, has there been such cases where Odoo was setup with strict firewalls. 
How does Odoo work with OWSAP Top 10 ?

**Comment by pedrobaeza** [comment]
Can you tell us which of that top 10 rules is being violated?

**Comment by manishbisht94** [comment]
AWS logs this under "Generic RFI_BODY" category, comes under broken access control.

**Comment by pedrobaeza** [comment]
I'm not able to find anything about that, even in https://d0.awsstatic.com/whitepapers/Security/aws-waf-owasp.pdf.

**Comment by manishbisht94** [comment]
You can search for "rfi" in  the shared documents. You will get it under "Broken access control".
May cause application to download suspicious file.

**Comment by pedrobaeza** [comment]
OK, I think @odony or @mart-e can say something about this.

**Comment by odony** [comment]
The AWS WAF is a generic tool, and it comes with sample sets of rules that are not application-specific. E.g. the one linked in the whitepaper is called "Example AWS WAF rule set covering generic OWASP Top 10 vulnerability areas with PHP backend specific misconfigurations" ([here](https://github.com/aws-samples/aws-waf-sample/blob/master/waf-owasp-top-10/owasp_10_base.yml)). The name is a hint.

The whitepaper does include some warnings, like *"the applicability of these rules to your particular web application can vary"*. Basically these sample rules may not be sufficient for some apps (false negatives), and may break legit features in others (false positives).

That's what's happening here.

If the ruleset blocks URL-like texts in query strings or POST payload, it's bound to trigger a lot of false positives and will break legit features of web apps. With Odoo you may not be able to use the Website Builder, OAuth2 flows won't work, etc. Other dynamic web apps would be impacted as well in different manners.

Odoo cannot/should not do anything about this, unless those parameters are used in an unsafe manner and are real vulnerabilities. More generally, you can read more how Odoo is designed to protect against common web app vulnerabilities on https://www.odoo.com/security#software.

It's not really the job of a web app to become compatible with WAFs, it's the other way around. Just like you need to open up some ports in your firewall depending on requirements of your systems running behind the firewall.
