### ISSUE TITLE
[13.0] CE There's no group called account.group_account_user

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#50992]
https://github.com/odoo/odoo/blob/fb17af76d791488c69eb3829376940b32998d374/addons/stock_account/views/product_views.xml#L21

Invoicing module doesn't have a group called account.group_account_user but instead account.group_account_invoice and manager

This makes product categories configuration for automatic inventory valuation impossible for the user without fixing this issue manually.

**Comment by pedrobaeza** [comment]
The group is defined here:

https://github.com/odoo/odoo/blob/fa219b7688676fce3212f0ff400db05cefb66c4d/addons/account/security/account_security.xml#L28

so no issue at all.
