### ISSUE TITLE
wrong quantity in internal transfer stock movement

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5100]
Dear Odoo,
I've performed for a consumable product the following internal transfer movements:
1) from stock location 1 (the standard STOCK) to SL 2 (created ad hoc) for quantity = 6
2) partial reverse = 2
3) from SL2 to SL1 = 1

the final stock quantity for SL1 is correct
in the SL2 is wrong = 6 instead of 3

Regards
claudio

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
