### ISSUE TITLE
[ALL] ORM: Odoo does not accept _order with null filters

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#51000]
Impacted versions: 13.0 and all others

Steps to reproduce:
Create a new model or inherit an existing one and apply an order on it.
For example:
`_order = 'score nulls last desc'`

Current behavior:
Traceback saying

> Invalid "order" specified. A valid "order" specification is a comma-separated list of valid field names (optionally followed by asc/desc for the direction)
This is because the regex expression in the core does not allow this:
https://github.com/odoo/odoo/blob/fb17af76d791488c69eb3829376940b32998d374/odoo/models.py#L68

Expected behavior: The `nulls last` option is allowed as it is an official SQL syntax (https://www.postgresql.org/docs/9.5/indexes-ordering.html) and allows you to order records based on a `desc` or `asc` and applying the empty rows to the end.
E.g without `nulls last` you get:
```
name | score
-------------------+----------------------
abc | 
def | 6.76
xxx |  5.8
```

With `nulls last` you get:
```
name | score
-------------------+----------------------
def | 6.76
xxx |  5.8
abc | 
```

We could do this by rewriting the regex in the core from:
```
^(\s*([a-z0-9:_]+|"[a-z0-9:_]+")(\s+(desc|asc))?\s*(,|$))+(?<!,)$
```

to for example:
```
^(\s*([a-z0-9:_]+|"[a-z0-9:_]+")(\s+(|desc|asc|desc nulls last|asc nulls last))?\s*(,|$))+(?<!,)$
```

**Comment by Yenthe666** [comment]
@odony I see you're the last one that has modified this regex. Do you think we can change this regex and if so, should it be master?
@rco-odoo I see you also did a lot on the models core, what do you think?

**Comment by pedrobaeza** [comment]
Duplicated of #26257

**Comment by Yenthe666** [comment]
Thanks for linking! Ugh I don't get why I sometimes don't seem to get back search results.
Maybe it is nice to replace the old one by this new one since the old one has been quiet for so long and was made/tested against old versions?

**Comment by pedrobaeza** [comment]
Well, as you prefer. If neither of both gets replied by ORM team, it's the same...

**Comment by Yenthe666** [comment]
OPW `2256828`

**Comment by odony** [comment]
I don't mind supporting NULLS clauses, but that would be for `master`. Also PRs welcome ;-)

**Comment by Yenthe666** [comment]
Awesome. I'll create one ASAP :)

**Comment by jcdrubay** [comment]
I hope this will work some day. 👀

**Comment by niyasraphy** [comment]
@jcdrubay https://github.com/odoo/odoo/commit/6a89f5b4f932b167a445427e0b3ee97be3cc8b44

**Comment by vava-odoo** [comment]
Added in 16.0 with https://github.com/odoo/odoo/pull/116464 (and updated in master as @niyasraphy pointed out).
