### ISSUE TITLE
[Website Forum] Fighting fraud and abuse of the voting system

### ISSUE THREAD

**Issue by smack815** [odoo/odoo#5106]
I have seen what I suspect to be abuse of the voting system, either to target an individual negatively or what I suspect are people who have a second account to upvote and/or accept their own answers.  One user [#431763] has five forum posts (one is a closed duplicate) and all five have been upvoted (two have since been downvoted by another user).

If Odoo sees this as a problem then it would be helpful if high karma users could see the voting history on questions and answers.  Possibly it might be a good idea to restrict the ability to see the voting history on a users own questions and answers so that resentments do not start among the users.

Either way, there will come a day that the forum will need some moderator type users to deal with issues such as these and probably a private forum to hold these discussions.

The more I type, the more I would prefer to see this ability restricted to trusted moderators only.  I guess that is what you get for making an issue wishlist request at 4am.  Feel free to close this if it is not deemed useful.

**Comment by Yenthe666** [comment]
Hey @smack815,

I believe a lot of this has been improved and the spam has dropped dramatically in the mean time!
P.S: We miss you around here! ❤️ 

Regards,
Yenthe
