### ISSUE TITLE
[12.0] Anomalous behaviour for some mandatory textbox on eCommerce check-out form

### ISSUE THREAD

**Issue by protontrigg3r** [odoo/odoo#51092]
The eCommerce shows a form during check-out process, in which a new customer have to enter the shipment address and other data. In this form some textbox related to a mandatory field (eg. ZIP code) have an anomalous behaviour: the label does **not have an asterisk** and the border does **not turn red** when you try to proceed leaving it empty.

**Comment by pedrobaeza** [comment]
Please put screenshot + the browser and version you are trying. Please also try with other browsers.

**Comment by protontrigg3r** [comment]
The attachments show the check-out form after filling in the mandatory fields and clicking "Next" button: you can see the "Some required fields are empty" message, but you don't know which these fields are (nothing is highlighted in red).

Please consider that the lack of the asterisk on the label of a mandatory textbox cannot be related to a page rendering problem ...

![Chrome_81 0_Windows10](https://user-images.githubusercontent.com/38140509/81785671-d981fc00-94fe-11ea-9c7a-322153884547.png)
![Chromium_81 0_Ubuntu18 04](https://user-images.githubusercontent.com/38140509/81785694-df77dd00-94fe-11ea-9d56-b3af5c5c70c4.png)
![Edge_44 17763_windows10](https://user-images.githubusercontent.com/38140509/81785706-e43c9100-94fe-11ea-90b9-2a626b7b9239.png)
![Firefox_76 0_Ubuntu18 04](https://user-images.githubusercontent.com/38140509/81785710-e4d52780-94fe-11ea-87ae-3b8ee8ade2b7.png)
![Safari_13 1_MAC](https://user-images.githubusercontent.com/38140509/81785714-e69eeb00-94fe-11ea-9064-f6d35289134c.png)

**Comment by JKE-be** [comment]
You are probably on a custom version.
Because there are no asterisk in standard. And zip is not required.

I cannot reproduce your error

**Comment by Yenthe666** [comment]
@protontrigg3r can you reproduce it on a default Odoo instance at runbot.odoo.com?

**Comment by protontrigg3r** [comment]
@JKE-be : You are right: I am using Clarico theme, but I have the same problem even without it. Now I suppose this is a problem related to the Italian OCA module "l10n_it_website_sale_fatturapa" which introduces extra checks for some fields that are mandatory for electronic invoicing ...

**Comment by protontrigg3r** [comment]
I re-checked it and the problem is not strictly related to the Clarico theme:
![Screenshot_2020-06-20 Address Management My Website](https://user-images.githubusercontent.com/38140509/85197113-3e3f2c00-b2df-11ea-92cf-a4623f9898c1.png)

**Comment by protontrigg3r** [comment]
I have opened an issues on [OCA / l10n-italy](https://github.com/OCA/l10n-italy/issues/1810)
