### ISSUE TITLE
Odoo new API, can't override old function field

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5112]
I need to override this field in res.partner:
```python
'display_name': old_fields.function(_display_name, type='char', string='Name', store=_display_name_store_triggers, select=True),
```
To be exact, need to update store parameter, but on new API it is a boolean value. So I figured I need to rewrite compute function, because there you add dependencies, not on store keyword.

So I did this (just an example to see if any value will be saved):

```python

display_name = fields.Char('Name', compute="_display_name_compute_new", store=True)

@api.one
@api.depends('parent_id', 'is_company', 'name', 'is_branch', 'parent_root_id')
def _display_name_compute_new(self):
    name = self.name_get()
    if name:
        self.display_name = name[0][1]
```
The thing is it computes name correctly and on time. But it just does not save it if it is triggered, when new dependency fields are used (in this example ```is_branch``` and ```parent_root_id```. If old dependencies are uses, then it works fine, because it seems it still uses old function and this one is just ignored.

So the only work around to make changes on that function field, was to use old API, which is not very good. And I did this:
```python
from openerp.addons.base.res.res_partner import res_partner as res_partner_orig
from openerp.osv import fields as old_fields

    _display_name_store_triggers = {
        'res.partner': (lambda self,cr,uid,ids,context=None: self.search(cr, uid, [('id','child_of',ids)], context=dict(active_test=False)),
                        ['parent_id', 'is_company', 'name', 'parent_root_id', 'is_branch'], 10)
    }
    _columns = {
        'display_name': old_fields.function(res_partner_orig._display_name, type='char', string='Name', store=_display_name_store_triggers, select=True),
    } 
```

**Comment by hardik-emiprotechnologies** [comment]
I will check this

**Comment by a0c** [comment]
Same here.
Even overriding the **compute** function itself does not work as expected (the new def is simply ignored).

**Comment by Cedric-Pigeon** [comment]
Same problem here

**Comment by yvaucher** [comment]
Might be related to https://github.com/odoo/odoo/issues/3922

**Comment by JonathanNEMRY** [comment]
any news about this isssue?

**Comment by oerp-odoo** [comment]
@JonathanNEMRY I guess not. No official response yet.
