### ISSUE TITLE
[13.0] Stock: show_operations is auto set when using multi locations

### ISSUE THREAD

**Issue by willmakenoise** [odoo/odoo#51121]
**Impacted versions:**
13.0
Not tested in earlier versions.

**Steps to reproduce:**
- show_operations on stock.picking.type is set to False
- Turn on Multiple stock locations.

**Current behavior:**
- show_operations on stock.picking.type is set to True by execute() in res_config_settings (stock module).
- If user manually sets this back to false, it will be overridden when later saving the config settings. Or upgrading Odoo, it seems.

**Expected behavior:**
The users settings on the picking type to be respected and not overridden.

Is there a reason why show_operations is automatically set to True when using multi locations?

**Comment by pedrobaeza** [comment]
Which UI option are you talking about? (please don't go so low level for this being reproducible at runbot/functional level). What `show_operations` does?

**Comment by sswapnesh** [comment]
I think this

**Comment by pedrobaeza** [comment]
Well, as you don't change that option continuously, I think it's good to provide that sane default, but can be manually changed afterwards.

**Comment by willmakenoise** [comment]
@sswapnesh Yes, that's the setting.

A default is fine. The issue is that it is reset every time the db is upgraded, or when other settings in the config are changed.

**Comment by sswapnesh** [comment]
I think this is a Bug since it's being changed everytime someone updates ResConfig.

**Comment by pedrobaeza** [comment]
Yes, if that's the case, then definitively. Tagging and pinging @sle-odoo and @amoyaux about this.

**Comment by sle-odoo** [comment]
Hi,

It was done on purpose, users have a better experience with this view once they have multi locations enabled (think order by source locations for different products).

If the complaint is that res.config sends even unchanged settings to the server, then that's a more broad issue (that we're aware of) and another one should be created and tagged to the framework team.

Regards

**Comment by willmakenoise** [comment]
Well, in this line the setting is overridden every time ResConfig is saved.

https://github.com/odoo/odoo/blob/84294948a4cc248e8c4e26f8ea93e2ff67435bb1/addons/stock/models/res_config_settings.py#L96

I don't get how that is a broader issue.. as it's done right there in the execute method, regardless of the setting having been set by the user or not.

**Comment by themreza** [comment]
> It was done on purpose, users have a better experience with this view once they have multi locations enabled (think order by source locations for different products).

I don't think confusion is a good user experience.

Multiple people have reported this, so it makes sense to:

* Add a description in the field's help explaining how it can get reset on its own
* Force enable it only if the multiple locations setting is being changed (right now any change triggers it)

It's a bit frustrating because we were puzzled for days as to what's turning it on.
We had to set breakpoints on all lines with `show_operations` to find the culprit.

**Comment by ryanc-me** [comment]
For posterity, this was fixed in #79632
