### ISSUE TITLE
Unittest - not able to test record rules on Runbot

### ISSUE THREAD

**Issue by sylvainvanhoof** [odoo/odoo#5114]
Hello,

I think there is a problem with unittest and Odoo.

### My situation
I want to check some record rules. To do that, I check if a error is raised.
```python
with self.assertRaises(orm.except_orm):
    self.res_partner.create(self.cr, vendor_id, values)
```
This test work pretty fine.

### What is the problem
When the method check_field_access_rights() raise a Warning, he write on the logger:
```python
if invalid_fields:
    _logger.warning('Access Denied by ACLs for operation: %s, uid: %s, model: %s, fields: %s',
        operation, user, self._name, ', '.join(invalid_fields))
```
This log is caught by Runbot is my commit is not accepted.

### How to fix this bug
Simply remove the logger in the method check_field_access_rights or _check_record_rules_result_count
Otherwise, we can change the regex of Runbot.

Thank for all,
Sylvain Van Hoof for Eeezee-it

**Comment by lepistone** [comment]
Hi,
have you tried `@mute_logger` ?
https://github.com/odoo/odoo/blob/8.0/openerp/tools/misc.py#L1114-1125

**Comment by sylvainvanhoof** [comment]
Hi lepistone,

Thank for your help. This decorator has fix my bug.
