### ISSUE TITLE
[Idea] Replace tree JS dashbord in simple QWEB 

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#51189]
In master, we can found dashbords in tree view : 
![image](https://user-images.githubusercontent.com/16716992/81827070-b2e0b700-9538-11ea-92e3-e81ebc7ddcc4.png)
![image](https://user-images.githubusercontent.com/16716992/81827137-c2f89680-9538-11ea-915c-38ea19d76026.png)

It is very nice and helpfull.

Those dashbords are coding in javascript (and xml, css, python, ...). I think we can make better. Indeed JS is not easy to use, to make a custom dev for a customer it is lot of line, hard to maintain ...

Last year I have suggest to add header in tree view : https://github.com/odoo/odoo/issues/33771

The idea is to replace the JS code by a using the QWEB render used in kanban view.

```xml
<header>
    <templates>
           <t t-set='data' t-value='JSON.parse(model._get_dashbord_data())'/>
           <span t-esc='data.count'/>
           <button .../>
           <a .../>
    </templates>
</header>
<tree>
     <field name="name"/>
</tree>
```

What is your opinion ?

@rco-odoo

**Comment by pedrobaeza** [comment]
I don't think this is nothing for ORM, but web client. Any way, the decision seems taken, and change the implementation at this stage is not possible. If you should comment on the PR...

About the extensibility in JS, it's debatable, and more with OWL.

Any way, issue tracker policy is to not put issues on master branch unless the deadline is very close and they are not being tracked, so I think we should close this (although it can be answered). @Yenthe666 what do you think?

**Comment by fmdl** [comment]
@pedrobaeza of course I don't ask to change the implementation now.
It is just a remark for next years.

**Comment by Yenthe666** [comment]
Well looking at the calls made by Odoo to create Owl and rewrite the JS side I don't see this fitting in anytime soon honestly. @ged-odoo could you please give the final call?

**Comment by fmdl** [comment]
ping @ged-odoo
