### ISSUE TITLE
Due date does not change after changing payment terms on invoice

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#5118]
**Due date not updated after changing the payment term**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Create a new invoice
 2. Fill in a customer and add a product
 3. Fill in a payment term (for example: 15 days)
 4. Save the record
 5. Go to the tab 'Other info' and look at the field 'Due date'. It has the date filled in of the default term that is selected (30 Net days)
 6. Edit the record and change the payment term. 
 7. Save this and go back to the tab 'Other info'.

Current behavior:

 - The 'Due Date' field is filled in by default 30 days ahead (the default payment term) and is never changed. Whatever the user fills in as payment term will not change the Due date.

Expected behavior:

 - Due date changes whenever the payment term is changed.

**Comment by Yenthe666** [comment]
@xmo-odoo could you have a look at this please? In my opinion this is a rather big bug..

**Comment by xmo-odoo** [comment]
Well I don't really know whether it's an accounting semantics issue or an implementation issue, and I can't refer to the 7.0 behaviour as it apparently didn't auto-fill the due date so I'll defer to @qdp-odoo for a first judgement on what should happen

**Comment by fclementic2c** [comment]
The expected behaviour is the see the due date calculated based on the actual payment terms (not the default one).

**Comment by Yenthe666** [comment]
@qdp-odoo any update on this please?

**Comment by qdp-odoo** [comment]
i confirm it is an implementation bug, there should be an onchange that (re)set the due date when the payment term is changed.

**Comment by Yenthe666** [comment]
Good to hear its confirmed. When will this be fixed @qdp-odoo ?

**Comment by pjmcdermott** [comment]
I have also experienced this issue. +1 for fixing.
Changing the invoice date *does* change the due date, so doesn't the onchange simply need to call the same function the invoice date onchange is calling?

**Comment by pjmcdermott** [comment]
If fact I would suggest replacing:

    <field name="payment_term" options="{'no_create': True}"/>

with:

    <field name="payment_term" options="{'no_create': True}" on_change="onchange_payment_term_date_invoice(payment_term, date_invoice)"/>

in account.invoice.supplier.form

Not that I have any experience hacking Odoo :innocent:

**Comment by Yenthe666** [comment]
Has been in the confirmed state for months without any fixes now. Any update on this guys?
@qdp-odoo @antonylesuisse @odony

**Comment by Yenthe666** [comment]
Has been in the confirmed state for months without any fixes now. Any update on this guys?
Ping number 2.
@qdp-odoo @antonylesuisse @odony

**Comment by odony** [comment]
@Yenthe666 This is a minor quirk, so if it is important to you, feel free to make a PR or sponsor someone to do it for you. That's more efficient than [repeatedly pinging R&D](https://github.com/odoo/odoo/blob/8.0/CONTRIBUTING.md) about it ;-)
The small change suggested by @pjmcdermott seems like it could work, so you could just try it and see if it fixes the problem.

**Comment by nim-odoo** [comment]
Closed with f41026631f05fa2c8a046f10c79ce564284c18a3
