### ISSUE TITLE
Reconciliation widget: ctrl + ENTER shorcut

### ISSUE THREAD

**Issue by LoisRForgeFlow** [odoo/odoo#51195]
Impacted versions: 11+

Steps to reproduce:
In v10 you could press ctrl+ENTER to reconcile all while in the reconciliation widget.

Current behavior:
In v11+ versions this is no longer the case. However the documentation says it is still possible, see for instance v12 documentation: https://www.odoo.com/documentation/user/12.0/accounting/bank/reconciliation/use_cases.html

Are there plans to readd the feature? or has it been substituted by something else?

Thanks

@ForgeFlow

**Comment by william-andre** [comment]
To my knowledge, nothing like that exists in v11.0 to 12.3.

In version 13.0 and above, you can use
* `up` for going to the previous transaction
* `down` for going to the next transaction
* `enter` to validate

We are thinking of improving the feature in future versions; it would be improved to be completely usable with the keyboard and minimize the mouse usage.
Unfortunately it won't be done in stable versions, nor in version 14.0
