### ISSUE TITLE
[8.0] Impossible to group invoices from delivery order when invoicing policy = manual

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#5120]
How to reproduce:
- Set a warehouse with a basic 1 step shipping pull rule but set the pull rule invoice status to 'To be invoiced' (since we want to invoice from delivery)
- Create a sale order with stockable products / invoicing method = manual /  partial delivery
- Validate the order
- Transfer the delivery

Do the same with duplcated order (same cutomer invoicing adress)

Now try to generate  group invoice for the 2 deliveries, validate the invoice and pay it. 
Go back to the Sale order -> The workflow is blocked, the sale orders are not 'Done'

**Comment by jco-odoo** [comment]
Why do you change the invoicing method on the sale order to manual and not to On Delivery Order?  Invoicing from delivery orders only works with on delivery order.

**Comment by fclementic2c** [comment]
I know Josse that my flow is a bit far fetched I admit it. 
In short, I have several shipping flow to handle but I would prefer to set the same manual invoice rule for all to simplify if feasible.

You say 'Invoicing from delivery orders only works with on delivery order' 
Since I can set any picking out as 'to be invoiced' on my pull rule...I am not so sure if it cannot be considered as a bug or not. The probleme is 'only' at the SO workflow ending.










My customer usually print invoices right before the shipment is validated.
Each each shipment package includes invoices.

**Comment by jco-odoo** [comment]
The invoice_state on the pull rule is not meant for doing this kind of
hack.  The workflow of the sale order presumes that when the method is
manual, it can wait for the creation of the invoice from the sale order.
(to my knowledge, this has always been like this)

If the invoices are printed before the shipment is validated, manual seems
logical as it is before the picking is transferred.  (that seems to be the
logic in Odoo right now)

It depends on your processes.  Maybe you can validate the picking and
automatically invoice and put the invoices on the packages at the very last
moment.  I don't know if invoicing before picking based on the invoice, is
a good practice.

On Fri, Feb 20, 2015 at 8:39 AM, Frédéric Clementi <notifications@github.com

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). I believe @jco-odoo answered the rest for you. 😉 

Regards,
Yenthe
