### ISSUE TITLE
related_sudo not respected on draft records

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#5121]
Related fields have a `related_sudo` option, which makes them being computed with super user privileges. The options is on by default. Unfortunately in one particular case the option is being ignored -  when the field is in a draft record (i.e. the record wasn't saved to the db yet).

Here is the beginning of the `_compute_related` method from openerp.fields.Field class:

    def _compute_related(self, records):
        """ Compute the related field `self` on `records`. """
        # when related_sudo, bypass access rights checks when reading values
        others = records.sudo() if self.related_sudo else records
        for record, other in zip(records, others):
            if not record.id:
                # draft record, do not switch to another environment
                other = record
            # traverse the intermediate fields; follow the first record at each step
            # [SNAP]

Those are the responsibe lines:

    if not record.id:
        # draft record, do not switch to another environment
        other = record

If `related_sudo` option is turned on `other` is in sudo mode initially, but it is overwritten by `record` which is not.

**Comment by rco-odoo** [comment]
@ludwiktrammer your analysis is correct. However, the weird code overwriting other is there on purpose.

Draft records only exist in cache, and their data is available in the cache of their environment only. If `record` is the draft record, `record.sudo()` is the same record but uses a different cache than `record`, and that other cache is empty for `record`. Therefore, traversing fields will always result in an empty value. This was a cheap fix for that case, but it does not always work.

**Comment by rco-odoo** [comment]
@ludwiktrammer it should work as you expect now!
