### ISSUE TITLE
Odoo v13 POS order lost

### ISSUE THREAD

**Issue by darmaa** [odoo/odoo#51217]
We are implemented odoo 13 point of sale module two company, but both many pos orders are lost. Not the same tab and only one session opened.

**Comment by pedrobaeza** [comment]
Sorry, but unless you give clear steps to reproduce the problem, there's no way to figure out any bug nor reason for that.

**Comment by darmaa** [comment]
We printed receipt bills everyday. 
Receipt bills are different to POS order.
Then we checked all, Some bills are lost.
This condition repeated all branches. There are not any log to server.

**Comment by pedrobaeza** [comment]
I'm afraid that are not clear steps to reproduce the problem. We need data and steps to get to the problem.

**Comment by darmaa** [comment]
Network and server normal and POS users write the same pos order but some order is lost. Around 300 users at the same time max. DB server 94 GB ram 64 core CPU, app server 64 GB ram 32 core CPU. and we are configured postgresql and odoo erp tuning

**Comment by Yenthe666** [comment]
Hi,

As @pedrobaeza already asked twice. Please write down reproducible steps so that we can reproduce this on a default Odoo 13. Without these steps we cannot do anything and this issue will be closed. You're providing system specifications and random info but not how to trigger the issue.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Closing as there has been no feedback & we lack good steps to reproduce.

**Comment by pioneersolutionsodoo** [comment]
Hi @Yenthe666 
We also facing this issue,
Lets say we have a order 00015-001-001 with product A with price - 200
some cases when we see in the backend for the same order 00015-001-001  this will be overidden by some other products such as product B price 300

This is little different scenario, not sure when this cases occurs.

We have different multi company setup and a session contains 10 different cashiers.

I hope this gives some insights
