### ISSUE TITLE
Assigned move is ignored in partial delivery of a sale order.

### ISSUE THREAD

**Issue by hans-van-dijk** [odoo/odoo#5122]
**Assigned move is ignored in partial delivery of a sale order**

Impacted versions:
- 8.0

Steps to reproduce:
1. create product P with routes buy and make to order, no stock.
2. create a new sale order
3. add a line with product P, quantity 7
4. validate the sale order
5. confirm the produced purchase order
6. receive the purchase order partially, quantity 2 or less (less then 50% from ordered).
   6a. stock_moves which are linked through move_dest_id will be split in either order. One pair (2 PCE) becomes done/assigned (purchase/sale) the other pair (5 PCE) remains assigned/waiting.
7. deliver the sale_order partially, odoo will propose 2 PCE as expected
8. click [Transfer]

Current behavior:
- stock is assigned by module=stock.py class=stock_picking method=recompute_remaining_quantity. This method selects the move with the largest quantity first (5 PCE in this case with state=waiting) and ignores that there is a move with state=assigned (2PCE). Finally the stock_moves are messed up.

Expected behavior:
- The assigned move is selected and set to done; a new picking is created from the remaining move(s).

**Comment by Yenthe666** [comment]
Hi @hans-van-dijk,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
